### ISSUE TITLE
"Open Windows Terminal here" disappeared!

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#10007]
### Windows Terminal version (or Windows build number)

10.0.19042.0, 1.7.1091.0

### Other Software

PowerShell 7.1.3
Ubuntu 20.04

### Steps to reproduce

1. Right-click on Desktop
2. Can't show "Open Windows Terminal here"
![Desktop Context menu](https://user-images.githubusercontent.com/23485114/116727041-4c7ad000-a9f9-11eb-8caf-b0789744a94b.png)

### Expected Behavior

Show "Open Windows Terminal here" on the Desktop and folder context menu.

### Actual Behavior

Previously, "Open Windows Terminal here" was displayed, but now it has disappeared!
I reinstalled the app several times but this was not added!

**Comment by vicky1999** [comment]
**Open Windows Terminal here** option will appear on **Shift + Right Click**.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9857 for more discussion.

/dup #9857

**Comment by xmha97** [comment]
> Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9857 for more discussion.
> 
> /dup #9857

I using the stable version, not the preview version.
Please reopen this issue.
