### ISSUE TITLE
Strikethrough expands when zooming in or out

### ISSUE THREAD

**Issue by vulpinefoxxo** [microsoft/terminal#10004]
### Windows Terminal version (or Windows build number)

1.4.3243.0

### Other Software

should not matter

### Steps to reproduce

1. Print strikethrough text (you can use `python -c print('\x1B[9mstrikethrough\x1B[0m')` or `echo -e '\x1B[9mstrikethrough\x1B[0m'` in bash)
2. Zoom in or out

### Expected Behavior

The strikethrough shouldn't have expanded.

### Actual Behavior

![](https://support.discord.com/attachments/token/IvKtQ54uBRG65gmjMN3LnD6gF/?name=0UIlgItWLF.gif)

edit: this also seems to happen with underlines (`\x1B[4m`), double underlines (`\x1B[21m`), overlines (`\x1B[53m`), this that I don't know how to name (`\x1B[7m`) and hyperlinks (`\x1B]8;;https://microsoft.com\x1B\\hyperlink\x1B]8;;\x1B\\`)

**Comment by zadjii-msft** [comment]
Alas, this is one of the oldest issues in the console codebase!

/dup #32
