### ISSUE TITLE
[Settings] Can't change properties of *PowerShell" Profile

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#10013]
### Windows Terminal version (or Windows build number)

Terminal: 1.7.1033.0

### Other Software

PowerShell 7.1.3

### Steps to reproduce

1. Install PowerShell 7.1.3 via msi
2. Open Terminal > Settings > "PowerShell" profile
3. Case A: Change name and click "Save" button. 
Case B: Click "Save" button.

_Note:_
_- The profile "PowerShell" is auto-generated._
_- Only happens on first start of wt after installing PowerShell 7.1.3.__

### Expected Behavior

On case A: Properties of profile are changed.

On case B: Nothing happend.

### Actual Behavior

A New corrupt profile is shown/generated.

**Comment by zadjii-msft** [comment]
Could you share your `settings.json`? This sounds just like #9962, but a sample of your settings would make it really easy to diagnose

**Comment by htcfreek** [comment]
@zadjii-msft 
Sory. The bug is only on first start of wt or after installing terminal. And btw it happens on every profile.

You should be able to reproduce it by deleting json and reopen wt.

**Comment by cinnamon-msft** [comment]
I just hit this in stable version 1.7.1091.0
I tried to apply acrylic to my newly installed PowerShell profile. Here's what my profiles look like in the JSON after attempting to edit the settings:
```
"list": 
        [
            {
                "commandline": "powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "useAcrylic": true
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            }
        ]
```
