### ISSUE TITLE
Add MOSH support like in fluent terminal

### ISSUE THREAD

**Issue by Luk164** [microsoft/terminal#10018]
# Description of the new feature/enhancement

Simmilar to fluent terminal, support for MOSH (https://mosh.org/) could be useful to some. For example in case of a connection loss it is able to reconnect, which is quite useful for when your connection is spotty. This is already implemented in fluent terminal (https://github.com/felixse/FluentTerminal)

**Comment by KalleOlaviNiemitalo** [comment]
MOSH and Fluent Terminal are licensed with GNU GPL so I don't think Microsoft is going to copy anything from these existing implementations to Windows Terminal. The MOSH source repository mentions a GPL-specific patent license for OCB encryption so reimplementing the protocol might require paying the patent holder. I think the most feasible way to enable MOSH in Windows Terminal is if somebody ports the MOSH code to Windows and it then runs as a separate process without Windows Terminal explicitly supporting it.

**Comment by zadjii-msft** [comment]
Also, `mosh` is just a shell, so I don't see why we'd need to build it directly into the Terminal. I bet you could get it working perfectly fine with WSL.

**Comment by DHowett** [comment]
@zadjii-msft in this case MOSH is actually _another terminal emulator_ like tmux/screen. It should work fine through WSL :smile:

**Comment by aress31** [comment]
+1

**Comment by zadjii-msft** [comment]
@aress31 If you'd like to "+1" this feature, the best way to do that is by hitting the 👍 button on this issue

![image](https://user-images.githubusercontent.com/18356694/96140789-ef3c8880-0ec5-11eb-82e0-30ce4977b9a7.png)

That way, you avoid unnecessarily pinging everyone following this thread. Thanks!

**Comment by zadjii-msft** [comment]
I don't believe there's anything for us to do here. The Terminal is perfectly capable of running mosh. It's not something that needs to be built-in to the Terminal at all. Unless I'm misunderstanding things. It doesn't look like there's a native `mosh.exe` available for Windows, that's something you should ask the maintainer of mosh to support. The terminal emulation should be more than sufficient by now ☺️

**Comment by Tamnac** [comment]
Asking for WSL just to run mosh is absurd. I push to re open this issue
