### ISSUE TITLE
Open  non default Terminal(S)  in folder

### ISSUE THREAD

**Issue by Rockdeldiablo** [microsoft/terminal#10014]
I have noticed that when i right click Open in windows Terminal  in a generic folder only the shell selected as a default open in that folder, the others (for me anaconda and powershell) open in the usual  C:\Users\Username.

Is it possible to add an option to let other shells open in the same place as the first one?  Anaconda in particular  for me

**Comment by PankajBhojwani** [comment]
It sounds like you want your new tabs/panes to open in the same directory as the one you're currently in, if so, then the discussion over at #3158 should inform you of our current position with regards to that! In short, the best solution we have for now is the one outlined here [3158 (comment)](https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033). That comment is for Powershell specifically, but it should be possible with Anaconda as well (probably with some tweaks)

**Comment by Rockdeldiablo** [comment]
> It sounds like you want your new tabs/panes to open in the same directory as the one you're currently in, if so, then the discussion over at #3158 should inform you of our current position with regards to that! In short, the best solution we have for now is the one outlined here [3158 (comment)](https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033). That comment is for Powershell specifically, but it should be possible with Anaconda as well (probably with some tweaks)

ah i hoped there was an easier solution, i guess i will wait. This is the first time i open an issue, what should i do now?  should i close the issue  with "close with comment" or leave it open?

**Comment by zadjii-msft** [comment]
This sounds like either #6111 or #8933.

/dup #6111
