### ISSUE TITLE
Misspelling of Color in UK English

### ISSUE THREAD

**Issue by BenConstable9** [microsoft/terminal#10016]
### Windows Terminal version (or Windows build number)

1.8.1032.0

### Other Software

N/A

### Steps to reproduce

Look for any reference to 'Color' within the text. Found issue when using Command Palette to search for Colour Profiles which doesn't return a command.

Minor issue.

### Expected Behavior

The word 'Color' should be spelt 'Colour' in UK English

### Actual Behavior

Word is spelt as the US version

**Comment by zadjii-msft** [comment]
That makes sense, I don't think we're building a en-GB localization. Nor do I think we have plans to - each language we translate to costs someone somewhere, so I'm not sure how valuable it is just to have someone come through and replace all the "color"s with "colour".

Thanks for the suggestion though!
