### ISSUE TITLE
wsl2 won't start anymore using Windows Terminal

### ISSUE THREAD

**Issue by snowgato** [microsoft/terminal#10015]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Click on Ubuntu-20.04 when launching Windows Terminal

### Expected Behavior

Be able to interact bash.exe and use linux commands

### Actual Behavior

when Ubuntu 20.04 is selected, a cursor appears at the top-left corner of the Terminal window and nothing more happens.
On the same time, Windows Terminal works fine using Powershell or Cmd.exe and I use wsl2 without issue with Windows Console Host ( the terminal used by default after wsl2 Ubuntu 20.04 install )
Thanks for your help !

**Comment by zadjii-msft** [comment]
Could you share your `setting.json`?

**Comment by fel1x0u** [comment]
Using Ubuntu 20.04 on WSL2 in Windows Terminal works completly.

**Comment by snowgato** [comment]
Hi,
actually the bug was probably a consequence of wsl2 overload, an intensive postgresql task was running on wsl2 and some usual commands also crashed on the regular bash terminal, like man or which.
Strangely, the cursor could blink and it was still possible to execute some simple commands with bash usual terminal.
I tried to uninstall and reinstall Windows Terminal that didn't solve the issue.
When I kill the postgress process that was exhausting the laptop and restarted the computer, Windows Terminal was working again.
