### ISSUE TITLE
Text cut off on the right side

### ISSUE THREAD

**Issue by juvtib** [microsoft/terminal#10010]
The author for https://github.com/microsoft/terminal/issues/2449 closed that issue. But the problem still exists and needs to be resolved. 

A work-around is to increase the Screen Buffer Height to more than the Window Size Height. Then the scrollbar will be positioned correctly.

**Comment by zadjii-msft** [comment]
We can just re-open the original thread, we don't really need a new one to track this. Thanks!

/dup #2449
