### ISSUE TITLE
Merger tab

### ISSUE THREAD

**Issue by Tim-Fang** [microsoft/terminal#10021]
Can support the merge tab?  
![图片](https://user-images.githubusercontent.com/60050973/116859341-71a65300-ac32-11eb-96d0-8b0d61554529.png)  
When I want to move another window from one window, I found that Windows Terminal can't do this...  
Please add this feature

**Comment by KalleOlaviNiemitalo** [comment]
That feature is tracked in <https://github.com/microsoft/terminal/issues/1256>.

**Comment by zadjii-msft** [comment]
Sure is.

/dup #1256
