### ISSUE TITLE
Terminal misbehaves when streaming with Discord (or Discord misbehaves) - important for remote pair programming during COVID

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#10020]
The zoom is constantly changing between the tab itself, and the full window. Thus it's impossible to track the text and typing etc because everything is jumping all the time (in the mode of choosing terminal as streamed app).

Maybe the problem is in the Tab control or some holder window.

**Comment by zadjii-msft** [comment]
Could you be more specific? Is the font size changing, or is the pane literally toggling it's "zoom" state, like the `togglePaneZoom` command? Is it the text in the terminal control, or in the _tab_? A gif would be super useful.

**Comment by vadimkantorov** [comment]
I'll record a GIF next time we play a CTF with my friends (that's when the problem reproduces stably).

Discord would zoom into the tab content for a split-second (in this state the tab headers are not seen, only a particular tab content is seen), then would zoom back out to the whole window. And this continues on loop.

Discord somehow tracks active "window" (of the selected app) to zoom into. I would think that somehow for Terminal the active window changes constantly from being the tab content "window" to being the whole Terminal "window".

**Comment by vadimkantorov** [comment]
It's not font size changing, it's that the active window somehow changes, and Discord zooms into the tab, and then zooms out to the whole Terminal window on loop.

**Comment by vadimkantorov** [comment]
When my friend does not select the Terminal window as the streamed app, and streams the whole screen, this problem does not happen (but then his screen is super huge, and on a laptop I can't see much, so he had to use huge fonts), but this is not very convenient.

**Comment by DHowett** [comment]
This is likely related to our use of a composition surface and somebody's misguided attempt to determine what is a game. I'm not certain what we can do apart from completely restructure our rendering stack. . .

**Comment by vadimkantorov** [comment]
Well, now it is completely unusable when Terminal is selected as streamed app... This should at least be documented somehow

**Comment by itsme-alan** [comment]
Now Microsoft should buy Discord to fix this.

**Comment by vadimkantorov** [comment]
Or at least talk to them, maybe complete rendering stack restructuring would not be needed after all...

**Comment by itsme-alan** [comment]
it's a joke

**Comment by vadimkantorov** [comment]
@zadjii-msft What sort of further feedback is expected of me? I think the bot is mistaken...

**Comment by zadjii-msft** [comment]
Oh I suppose that's right. I guess I was expecting a video of some sort, but from everything mentioned here, this sounds like some hijinks that Discord is playing with the window. This probably makes the most sense to file on the [Discord issue tracker](https://support.discord.com/hc/en-us/articles/360046057772-How-do-I-submit-a-bug-) - I'm not sure there's much else we can do to investigate this on our side.

**Comment by vadimkantorov** [comment]
Well, all other apps like browsers work fine. Have you tried streaming Terminal with Discord? This must be a frequent scenario for pair programming with COVID

As I said, I'd provide input next time I play a CTF contest with my friend

Thanks for thel ink, I'll also create an issue at Discord tracker

**Comment by Pitta** [comment]
I have this issue was well. Only seems to be a problem with Discord. Issue is exactly as described by @vladimkantorov

**Comment by lapo-luchini** [comment]
Here shows a tab 1 which contains `while true; do sleep 1; echo HELLO; done` and I manually wrote something in tab 2.
From my Windows GUI I'm always seeing a stable tab 2, but each time the `echo HELLO` goes on in tab 1 it's shown for a moment in the streaming. Another effect is that tab 2 is seen complete with the tab stripe at the top, while tab 1 is shown it's "zoomed in", without tabs on top.
https://user-images.githubusercontent.com/420454/179699365-335fc19a-4961-4996-9fda-4906627c9152.mp4

**Comment by vadimkantorov** [comment]
@zadjii-msft Above by @lapo-luchini is a sample similar to what I saw and meant by "zoom in"

**Comment by zadjii-msft** [comment]
I maintain that I suspect this is an issue with Discord itself. Did anyone ever open an issue on their issue tracker? If they can point at something we're doing wrong, we can revisit this, but other streaming apps don't seem to have this issue.

**Comment by vadimkantorov** [comment]
So I received a confirmation email with a bug ID: 26840839. But still no URL for a public tracker, so not sure how to collaborate with them on this.

**Comment by vadimkantorov** [comment]
It appears they do not assign public URLs to the bugs anymore and also there is no option for public discussion...
