### ISSUE TITLE
Terminal with 3 split-pane focuses on random pane

### ISSUE THREAD

**Issue by dc1992** [microsoft/terminal#10029]
### Windows Terminal version (or Windows build number)

1.8.1092.0

### Steps to reproduce

- setup Windows Terminal to have 3 terminal (example: "startupActions": "split-pane -p \"cmd2\"; split-pane -p \"cmd2\"")
- open Windows Terminal: the cursor is blinking on a random pane (example n1)
![cursor1](https://user-images.githubusercontent.com/28669515/117024640-76363e80-acfa-11eb-88cd-1f0723848131.png)
- close WIndows Terminal
- open Windows Terminal again: the cursor is blinking on a random pane (example n3)
![cursor2](https://user-images.githubusercontent.com/28669515/117024668-7b938900-acfa-11eb-9f76-dd0731e437f4.png)

### Expected Behavior

I expect to see the cursor always in the same pane: the one I chose as default.

### Actual Behavior

Whenever I open Windows Terminal, the cursor blinks in a different pane (looks like it's random); this causes the user to start writing in a random pane and force him to manually switch pane.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+focus+random+pane+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #6586 for more discussion.

/dup #6586

**Comment by dc1992** [comment]
> Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+focus+random+pane+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #6586 for more discussion.
> 
> /dup #6586

It doesn't look like the same problem to me, but maybe it's caused by the same bug.
