### ISSUE TITLE
Question about the workaround portable version.

### ISSUE THREAD

**Issue by holahapi** [microsoft/terminal#10030]
I follow the https://github.com/microsoft/terminal/issues/1386 ,extract the msix file to use as portable.

I hope not missing anything in the thread, but I find that the settings still store in the C drive  as follow "C:\Users\your_beautiful_name\AppData\Local\Microsoft\Windows Terminal\"

Is there a way to save  the setting inside the portable folder?

**Comment by DHowett** [comment]
The "unpackaged" version is not supported, and is not officially considered a "portable" version of Terminal. Sorry. ☹️

**Comment by holahapi** [comment]
thank you for the quick reply 😭
