### ISSUE TITLE
profile.json should have a schema

### ISSUE THREAD

**Issue by paulcam206** [microsoft/terminal#1003]
# Summary of the new feature/enhancement

`profile.json` is a bit of a bear to edit. I know that there will eventually be a UX around this, but there's still value in authoring a [json schema](https://json-schema.org/). It would allow users to make sure their edits are in spec, and allow editors to provide smarter autocomplete options.

**Comment by cspotcode** [comment]
It will also be important for Terminal to include a `"$schema"` property in the JSON pointing to the schema so that editors can pick it up.

**Comment by davidwin** [comment]
No proper PR, but I made [a gist](https://gist.github.com/davidwin/dad0126d20c53134851a2eb0b3437dfb) to try out a schema, and it works pretty well in VS Code at least. You can either download the file to the `RoamingState` folder and add `"$schema": "profile.schema.json"` to `profile.json`, or [link](https://gist.githubusercontent.com/davidwin/dad0126d20c53134851a2eb0b3437dfb/raw/3b7e8985fc3f285c0726e68da9b57ed09db6c1b5/profiles.schema.json) to the gist directly.

A few notes on the schema that I derived from [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md):
- `background` and `startingDirectory` are documented as required, but were missing from the default `profile.json` for all but the PowerShell profiles.
- A regex for the `keys` property would be cool. I should probably take a look at the parsing code to see if that can be done.
- Various strings and numbers could probably also be more constrained. Again, need to take a look at the parser first.

**Comment by NickyMeuleman** [comment]
@davidwin Just tested it locally by linking it in VSCode, it works great!

I had been diving through https://github.com/microsoft/Terminal/blob/master/src/cascadia/TerminalApp/Profile.cpp to get settings and their possible values.

**Comment by davidwin** [comment]
Thanks for the tip! I made a few tweaks based on how the parser currently works. In general, almost no option is actually required, but I'm only making `background` optional for now. It looks like `startingDirectory` is a bit funky - if you leave it out, the shell opens in `C:\Windows\system32`, but an empty string leads to `%USERPROFILE%`, which seems like a better default.

I'd like this in the project as well, at some point. In that case, does the schema belong to the app install directory, with the `$schema` property for `profiles.json` set to that path?

**Comment by DHowett-MSFT** [comment]
> belong to the app install directory

It absolutely does. I'd love to review a PR that adds the schema to our project!

**Comment by davidwin** [comment]
Great, I'll see what I can do! 

I've been thinking about whether there is any point in marking so many properties required. Reading the code, I see no real justification for why most properties in  [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) are listed as required, but maybe this is work in progress? Of course, properties such as `name` and `guid` should be required, but for most other properties, sensible and stable default values seem like a better approach (which is largely how the parser works today anyway).

If the point of the schema is largely to help someone editing settings in an editor, it's more important that additional properties are not allowed.

**Comment by shanselman** [comment]
👀 

@cinnamon-msft

**Comment by davidwin** [comment]
One thing I've noticed when playing with this is that support for schema validation in the VS 2019 JSON editor is not going to work friction free (if at all). Apparently, the JSON validator doesn't understand `file:` URIs in for the `$schema` property. It _looks_ alright with a clickable link and correct Schema metadata, but validation doesn't work until I remove the `file:///` prefix from the path:
![image](https://user-images.githubusercontent.com/9844625/61588778-45c2f600-aba1-11e9-857c-3a0f66ccab30.png)
However, then the `$schema` property isn't a valid URI and the VSCode editor will (correctly) flag this as an error and not enable JSON validation. Even the VS 2019 editor doesn't think it is a clickable link anymore, even if validation does work.

Unless VS2019 is fixed (I tried this in 16.1.6), the only universally accepted solution would be a `https` URI, but that would require hosting the schema somewhere. I guess deep-linking into this GitHub repo is technically possible, but is it desirable? I don't know which editors people are using for JSON - for me it's VSCode these days, so hopefully this isn't much of an issue.

**Comment by cspotcode** [comment]
Can VS2019 be configured to apply a schema to files named `profiles.json` *without* a `"$schema"` property?  I know VSCode supports this: you can configure filename -> schema mappings.  If VS2019 supports this, then that might be an acceptable workaround.

If this is a bug in VS2019, and there's a well-known workaround for VS2019's bug, then Terminal can stick to the standards and be compatible with editors like VSCode.  And VS2019 users can use the workaround.

**Comment by davidwin** [comment]
Yup, there is another way of associating the schema with the filename `profiles.json`: VS has a list of schema catalogs that it queries for this purpose, but it looks like these catalogs can't be located on the file system, so we're back on square one. However, one could submit a PR to [SchemaStore](https://github.com/schemastore/schemastore/) to add this snippet to http://schemastore.org/api/json/catalog.json, which is the schema catalog that VS uses:
```JSON
{
      "name": "profiles.json",
      "description": "Windows Terminal settings",
      "fileMatch": [ "profiles.json" ],
      "url": "https://gist.github.com/davidwin/dad0126d20c53134851a2eb0b3437dfb/raw/85e2ce051ec59916be0c07dda61f621f56a2ca33/profiles.schema.json"
}
```
Zero lines touched in Terminal, I'm almost tempted! :) However, if the schema file is going to be hosted online anyway, one might as well burn that URL into the `$schema` property.

**Comment by shanselman** [comment]
Can't just use a relative url for "$schema" : "./profile.schema.json"

Works great here.

**Comment by davidwin** [comment]
A relative URL appears to please VS2019 (great!), but then the schema would have to be copied out of the app install directory, presumably when the `profiles.json` is written. Not a problem, @DHowett-MSFT?

So far, I count four ways to associate a schema with the settings file:
1. `"$schema": "file:///C:/.../profiles.schema.json`. Fine with VSCode, not VS2019 (and at least one more editor I tested).
2. `"$schema": "./profiles.schema.json"`. Fine with VSCode and VS2019.
3. `"$schema": "https://raw.githubusercontent.com/microsoft/terminal/..."`. The schema file would still be hosted in this repo. At least VSCode and VS handle this, presumably also more editors.
4. Contribute to [SchemaStore](https://github.com/schemastore/schemastore/) and make the association based on file name (`profiles.json`). According to their docs, several editors in addition to VS and VSCode support this. Interestingly, anyone could do this independently of the Terminal project, but I guess that maintaining the schema in this repo would be preferable.

**Comment by shanselman** [comment]
I propose with do 2 and 4, together asynchronously.

However, just as this new profiles.schema.json becomes an authoritative source of truth over schemasettings.md, there should be an automatic CI/CD process (or manual with a checklist) to send updates to SchemaStore if it changes.

**Comment by DHowett-MSFT** [comment]
I'm okay with 2 through 4, honestly. I think having it refer back to the repository (3) might be a great way to make sure it's always in sync, but there's a chance it'll drift when we make releases.
2 has a chance of falling out of date; we need to make sure that we only copy the schema out of the application package when it's changed, otherwise we'll just waste time on every launch. I really wish we could not have to do it at all.

**Comment by davidwin** [comment]
The out-of-sync problem could be solved if the `$schema` property was set to point to the specific commit SHA of this repo for which that particular version of the application was built. It would require some minimal codegen at build time to construct the link, though.

To avoid too many writes in option 2, one could compare the modification dates before writing the schema file to the user settings directory.

Since CI/CD was touched upon, what are your thoughts on testing this? At a minimum, the schema file should be checked for validity, but perhaps there should be some tests to make sure that the JSON produced by `CascadiaSettingsSerialization.cpp` adheres to the schema. Unfortunately, the native `jsoncpp` package doesn't support validation, so one might have to integrate e.g JSON.NET in the native tests somehow. Then there's [rapidjson](http://rapidjson.org/) that supports validation at runtime (say a DEBUG build) with a streaming serialization API (which also avoids creating a JSON DOM, as is currently done). But, that would cause a lot of code churn, and I feel like I'm going off a tangent here already.

**Comment by JustinGrote** [comment]
Another valuable use of having a JSON schema is allowing applications that interact with Windows Terminal to dynamically update their interfaces. I'm thinking of MSTerminalSettings Powershell Module at the moment.

**Comment by JustinGrote** [comment]
I updated the @davidwin gist to include new 0.3 settings and sort all settings and enums alphabetically.
https://gist.githubusercontent.com/JustinGrote/ae4e13e522347af1af4154aecda8fe11/raw/profiles.schema.json
