### ISSUE TITLE
Visual Studio Code (VSCode) closes as well when started inside Windows Terminal and terminal (tab) closes

### ISSUE THREAD

**Issue by aheyer** [microsoft/terminal#10032]
### Windows Terminal version (or Windows build number)

10.0.19042.928 1.7.1033.0 

### Other Software

Visual Studio Code (VSCode) 1.55.0

### Steps to reproduce

1. Install VSCode
2. Open a WT CMD or PowerShell session
3. Start VSCode with "code" (PATH integration) or "start vscode"
4. Close WT session (e.g. exit)

### Expected Behavior

VSCode should run detached like any other Win32 app that was started. If you try e.g. "notepad"/"start notepad" and close the WT session, notepad.exe remains unaffected and stays open.

### Actual Behavior

VSCode closes immediately. It seems that changes to open files are saved without user confirmation.

**Comment by aheyer** [comment]
Okay, it seems not related to Windows Terminal. You can see similar behaviour if using the old Win command prompt. But in this case VSCode remains open when terminal is closed via "exit" – terminal window hangs. If you close the window instead VSCode crashes as well.

But: Am I the only one who uses VSCode from inside a Windows terminal who closes the terminal?

**Comment by aheyer** [comment]
Okay, I nailed it down. It seems that VSCode crashes when STDOUT and STDERR are closed with the terminal. When redirecting these descriptors to a file on start of VSCode I can close the terminal and VSCode remains unaffected.

**Comment by DHowett** [comment]
This looks a *lot* like /dup https://github.com/microsoft/vscode/issues/66750

:smile:
