### ISSUE TITLE
Graph lines in tig don't render at all font sizes

### ISSUE THREAD

**Issue by JelteF** [microsoft/terminal#10038]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

tig version 2.3.0 (inside WSL2, Ubuntu 18.04)

### Steps to reproduce

1. Set the following as font settings:
```
            "fontFace": "Consolas",
            "fontSize": 8
```
2. open `tig` in a git repo on your WSL

### Expected Behavior

What you see at fontsize 9:
![afbeelding](https://user-images.githubusercontent.com/1162278/117165802-1ad18280-adc6-11eb-86db-74db30fb24d7.png)

### Actual Behavior

At fontsize 8:
![afbeelding](https://user-images.githubusercontent.com/1162278/117165761-12794780-adc6-11eb-932d-474849f279af.png)

at fontsize 7:
![afbeelding](https://user-images.githubusercontent.com/1162278/117165951-3c326e80-adc6-11eb-9d03-2253aafe8476.png)

at fontsize 6:
![afbeelding](https://user-images.githubusercontent.com/1162278/117166439-ab0fc780-adc6-11eb-9d9b-0858707cf51f.png)

As you can see the exact lines that are missing differ based on the fontsize. I ran into this issue with fontsize 10 using this [Ubuntu Mono Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf), but as shown here it also reproduces with Consolas. One interesting thing is that all lines are visible with the Ubunutu font is that, on fontsize 8 and 10 all lines are visible, but on fontsize 9 not all are visible. So it's not just that the font is "too small" to display the lines.

I thought of commenting on this issue: https://github.com/microsoft/terminal/issues/909, but it seems unrelated after going through the comments there.

**Comment by DHowett** [comment]
Thanks!

This looks like either /dup #7927 (if the font has bitmap strikes) or /dup #6161 (if we try to draw them too small, they will be destroyed because they went below one pixel in size)
