### ISSUE TITLE
Wrong simplified Chinese translation such as "向竖起大拇指移动焦点"

### ISSUE THREAD

**Issue by JingHuaMan** [microsoft/terminal#10043]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Language: Simplified Chinese

`设置` (settings) -> `操作`

![image](https://user-images.githubusercontent.com/49118946/117235815-0d65d800-ae5a-11eb-9bac-c62fa7bbdef7.png)

### Expected Behavior

It seems that some of the translations are wrong:

1. Not `下面是当前绑定密钥`, it should be `下面是当前绑定热键`
2. Not `向 向下移动焦点`, it should be `向下移动焦点`
3. Not `向 竖起大拇指移动焦点`, it should be `向上移动焦点`
4. Not `打开设置。。。`, it should be `打开设置`

### Actual Behavior

![image](https://user-images.githubusercontent.com/49118946/117236233-e3f97c00-ae5a-11eb-9ef7-246490b67e91.png)
![image](https://user-images.githubusercontent.com/49118946/117236245-e8be3000-ae5a-11eb-9d4d-05025acd28b6.png)
![image](https://user-images.githubusercontent.com/49118946/117236257-ecea4d80-ae5a-11eb-8080-104666dfdd6c.png)

**Comment by skyline75489** [comment]
Thanks for the feedback! I've posted similar localization defects in #9328. Could you also organize these recommendation like that? It could be really helpful for us.

**Comment by JingHuaMan** [comment]
@skyline75489 Sorry, where can I get the key values like `Globals_LaunchModeMaximized.Content`?

**Comment by skyline75489** [comment]
Those strings are inside the source code of the terminal repo. If you can't find them, don't worry about it. I can fill up a table later.
________________________________
发件人: Hammer_Zhang ***@***.***>
发送时间: 2021年5月6日 18:38
收件人: microsoft/terminal ***@***.***>
抄送: Chester Liu ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/terminal] Wrong simplified Chinese translation such as "向竖起大拇指移动焦点" (#10043)


@skyline75489<https://github.com/skyline75489> Sorry, where can I get the key values like Globals_LaunchModeMaximized.Content?

―

**Comment by zadjii-msft** [comment]
In English, those resources can be found here: https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw. I think the translations get patched in later, so the chinese versions aren't anywhere in the repo. 

Looks like these are mostly just translations for various different actions, so that's not totally unexpected. @DHowett should we just combine these with the rest in #9328?

**Comment by JingHuaMan** [comment]
The wrong translation of "密钥" is already mentioned in #9328 .

<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n45" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(52, 73, 94); font-family: Ubuntu, &quot;Source Sans Pro&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">

Key | Recommandation | Comment
-- | -- | --
ResetFontSizeCommandKey | Change the translation of "font size" to "字体大小" | "字号" is not a wrong translation, but not so accurate
DirectionUp | 上 | not "竖起大拇指"
DirectionDown | 下 |  not "向下", otherwise there will be two duplicate "向"
OpenSettingsUICommandKey | Change "。。。" to "..." or "......" |  

</figure><br class="Apple-interchange-newline">
</body>
</html>

**Comment by skyline75489** [comment]
The internal workitem ([MSFT-32515306](https://task.ms/32515306)) associated with #9328 is closed. Maybe we need a new one?

You know what, how about I just double check the localization things when 1.9 is out, to avoid the fragmented reports regarding localization issues. Is it OK with you @JingHuaMan ? Thanks again for catching these.

**Comment by DHowett** [comment]
@skyline75489 You should be selfhosting 1.9 if you go to the store and update -- can you check your strings? :smile:

**Comment by skyline75489** [comment]
@DHowett I've received the 1.9 selfhost version and looks like most of my strings are better localized (don't really wanna brag but it is *a lot* better now). I'll double-check and file another issue to supersede this later. Let's squash those localization bugs before 2.0 😄

**Comment by skyline75489** [comment]
Hi @JingHuaMan I'm closing this in favor of #10174. Take a look if you like 😄

**Comment by v3470** [comment]
My Windows Terminal still use "密钥" represent `key` rather than "热键", does this issue already fixed?

Windows Terminal version: 1.11.2921.0, from Microsft store
OS version: Windows 10 21H1(19043.1288).
