### ISSUE TITLE
Use of TrueType fonts

### ISSUE THREAD

**Issue by SeanGephardt1** [microsoft/terminal#10040]
Implement the use of TrueType fonts for Windows 10, and whatever font system is needed for other operating systems.

**Comment by DHowett** [comment]
What? Terminal supports TTF and OTF fonts, and the Console supports TTF and OTF as well. So does the operating system. And we're not working on authoring software for a _different_ operating system on this team, so I am not sure what you're requesting?

**Comment by mdtauk** [comment]
I would presume, the poster may be referring to Proportional vs Monospaced fonts?

**Comment by DHowett** [comment]
That's fair.

If the poster wants proportional fonts, they can use Terminal :smile:

![image](https://user-images.githubusercontent.com/189190/117185661-b13e7d80-ad9f-11eb-80bd-75809b00759c.png)
