### ISSUE TITLE
No way to exit focus mode

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [microsoft/terminal#10044]
When configuring the terminal to open in focus mode, there is no way to exit it later, as the menu becomes inaccessible and the documentation doesn't indicate how to exit focus mode.

**Comment by zadjii-msft** [comment]
You could always use the [command palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette), <kbd>ctrl+shift+p</kbd>, and use that to toggle focus mode. But yea, this should be in the docs.

**Comment by zadjii-msft** [comment]
Moved to /dup https://github.com/MicrosoftDocs/terminal/issues/322
