### ISSUE TITLE
Tabs dragging does not work when WT is started with administrator privileges

### ISSUE THREAD

**Issue by AndrewNowosad** [microsoft/terminal#10049]
### Windows build number, Windows Terminal version

10.0.19042.0, 1.7.1033.0

### Other Software

No

### Steps to reproduce

1. Run WT as admin
2. Open two or more tabs
3. Try to drag one of them

Normal mode:  
![WT1](https://user-images.githubusercontent.com/20268663/117411203-043d3f80-af1c-11eb-9e38-b5a54d9156a4.gif)

Started with administrator privileges:  
![WT2](https://user-images.githubusercontent.com/20268663/117411212-056e6c80-af1c-11eb-86cc-d389a30cc22f.gif)

### Expected Behavior

Dragging is possible

### Actual Behavior

Dragging is not possible

**Comment by skyline75489** [comment]
This is actually by design. See #3581, #6893

**Comment by zadjii-msft** [comment]
Sure is!

/dup #3581
/dup #6893
