### ISSUE TITLE
Reconnect option after "process exited with code".

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#10056]
I am using Windows Terminal mainly to connect to Linux boxes using ssh.exe command in profile config.

I would like to propose option to reconnect/reinitiate profile opening in the same tab (from tab menu or at least by keyboard shortcut) after disconnection after loose connection to SSH server and we get "process exited with code X". This way we would not loose the terminal output history and we could work after disconnection in the same tab while our entire output history really is.

I loose connection with Linux box, I click re-connect from tab menu, Windows terminal reinitiate profile opening in the same tab and I do not loose output history as I can work in the same tab like disconnection never happened.

**Comment by AbobakrM55** [comment]
yes


‫في السبت، 8 مايو 2021 في 3:21 م تمت كتابة ما يلي بواسطة ‪4k3or3et‬‏ <‪
***@***.***‬‏>:‬
