### ISSUE TITLE
Terminal crashes when setting --tabColor in command line arguments

### ISSUE THREAD

**Issue by MSEvanhi** [microsoft/terminal#10053]
### Windows Terminal version (or Windows build number)

10.0.19042.0, 1.7.1033.0

### Other Software

Not other software, but I notice your default Windows Terminal version listed above is higher than my terminal version. I obtained mine from the Windows Store yesterday, so maybe this is fixed in a later version and you have yet to release that to the store?

### Steps to reproduce

1. Open Windows Terminal command line.
2. Attempt to create a new split window (vertical or horizontal) and set --tabColor
3. When typing past 1 character of tabColor, the terminal window will crash.

### Expected Behavior

For me to be able to type out my color value and not crash.

### Actual Behavior

Window crashes.

**Comment by zadjii-msft** [comment]
Wait, does the terminal that you're _typing in_ crash, or does the terminal that launches crash? 

What shell are you using?

**Comment by MSEvanhi** [comment]
_does the terminal that you're typing in crash, or does the terminal that launches crash?_
- I am using a single Windows Terminal window. I default to my PowerShell profile. I get the issue when attempting to use: `sp -H -p PowerShell --tabColor #FFFFFF` in the 'command pallet'. The Windows Terminal itself crashes, taking all tabs I have with it.

_What shell are you using?_
- Not sure what you're asking here. I'm typing into the Windows Terminal 'command pallet' that I open via `CTRL+Shift+P`.

**Comment by zadjii-msft** [comment]
Oh wow okay yep, that clears it up. Didn't realize it was the command palette! That crashes instantaneously. That we can work with, thanks!
