### ISSUE TITLE
Can't input Chinese punctuation in Terminal ipython

### ISSUE THREAD

**Issue by etern** [microsoft/terminal#10054]
### Windows Terminal version (or Windows build number)

Microsoft Windows [版本 10.0.19042.928]
Windows Terminal 版本: 1.7.1033.0

### Other Software

ipython 7.21.0 (inside powershell/cmd)
python 3.7.9

### Steps to reproduce

Inside Terminal
1. Open powershell or cmd in Windows Terminal
2. type(or paste) some Chinese punctuation, everything OK
3. Open ipython
4. type(or paste) some Chinese punctuation （ex ，。、；）,  input failed, nothing shows.
5. type some Chinese characters (ex 微软), input OK, the characters show.

Without Windows Terminal
1. Open powershell or cmd directly
2. Open ipython
3. type(or paste) some Chinese punctuation, everything OK

### Expected Behavior

can input Chinese punctuation in Terminal+ipython

### Actual Behavior

cannot input Chinese punctuation in Terminal+ipython

**Comment by etern** [comment]
I installed Terminal-preview(1.8.1032.0) from Microsoft Store.

It's not fixed, cannot input Chinese punctuation in Terminal-powershell-ipython

**Comment by skyline75489** [comment]
This is fixed in 1.9-preview. See #9052.
