### ISSUE TITLE
Multimedia Key Hotkey Support

### ISSUE THREAD

**Issue by allquixotic** [microsoft/terminal#10058]
# Description of the new feature/enhancement

In the documentation at https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#accepted-modifiers-and-keys the listed keys are:

```
Type | Keys
-- | --
Function and alphanumeric keys | f1-f24, a-z, 0-9
Symbols | `, plus, -, =, [, ], \, ;, ', ,, ., /
Arrow keys | down, left, right, up, pagedown, pageup, pgdn, pgup, end, home
Action keys | tab, enter, esc, escape, space, backspace, delete, insert, app, menu
Numpad keys | numpad_0-numpad_9, numpad0-numpad9, numpad_add, numpad_plus, numpad_decimal, numpad_period, numpad_divide, numpad_minus, numpad_subtract, numpad_multiply
```

The `Back`, `Forward`, and other multimedia keys are not mentioned. I have a TEX Shinobi and would like to bind the "Back" and "Forward" keys to previous/next tab. I had this working 10 years ago in gnome-terminal; would be nice to have this on Windows by now. :)

The nice thing about being able to use Back and Forward specifically for this is because those keys are already useful in web browsers to do what you would expect, so I don't have to write an AutoHotkey macro or rebind the behavior of the keys at the hardware level to get this working in both Terminal and on the web.

# Proposed technical implementation details (optional)

Not sure exactly, but I believe the multimedia keys have normal key codes, at least on Windows. PassMark KeyboardTest reports "Windows Key Code" 0xA6 (decimal 166) for Back and 0xA7 / decimal 167 for Forward. Not sure if they are handled the same way as other keys, since no "BIOS Key Code" gets sent. I've always suspected something was a little weird / non-standard about multimedia keys.

**Comment by zadjii-msft** [comment]
Hmm. I'd bet those keys are 

name | hex | description
-- | -- | --
VK_BROWSER_BACK | 0xA6 | Browser Back key
VK_BROWSER_FORWARD | 0xA7 | Browser Forward key
VK_BROWSER_REFRESH | 0xA8 | Browser Refresh key
VK_BROWSER_STOP | 0xA9 | Browser Stop key
VK_BROWSER_SEARCH | 0xAA | Browser Search key
VK_BROWSER_FAVORITES | 0xAB | Browser Favorites key
VK_BROWSER_HOME | 0xAC | Browser Start and Home key

Doesn't seem totally unreasonable to add those. We'd need to come up with sensible names for those keys, but then they could be added pretty easily.

**Comment by zadjii-msft** [comment]
I'd probably go with 

```
browser_back
browser_forward
browser_refresh
browser_stop
browser_search
browser_favorites
browser_home
```

I'd be a little worried with `back` maybe being confusing, and `start` might be confusing with the `win` key as well. At least that's got parity with the actual VKEY constants, so that makes sense to me. I'm pretty sure the only file you'll need to edit is `src\cascadia\TerminalSettingsModel\KeyChordSerialization.cpp`. @carlos-zamora can correct me if I'm wrong here.

**Comment by KalleOlaviNiemitalo** [comment]
Please edit [doc/cascadia/profiles.schema.json](https://github.com/microsoft/terminal/blob/66fdc645f748bfc4fe4ba8f123469de0ce2a66a3/doc/cascadia/profiles.schema.json#L6-L10) as well.
