### ISSUE TITLE
Default Profile drop down list (in settings UI) is going *outside* of windows term window

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/terminal#10059]
### Windows Terminal version (or Windows build number)

10.0.19043.0 1.8.1032.0

### Steps to reproduce

1. Open settings UI
2. Go to the startup tab
2. Click on the default profile list to make the different profiles show up in the list
3. Do not select any option and start scrolling on settings page WITHOUT closing or selecting an option in the default profile list

### Expected Behavior

Profiles list should be hidden or closed 

### Actual Behavior

The list overpasses the Windows Terminal window. Screen record attached :

https://user-images.githubusercontent.com/64481347/117571203-caac3600-b0cd-11eb-92a9-e41b5b427fe8.mp4

**Comment by j4james** [comment]
Thanks for the report, but this is already being tracked in issue #9320.

**Comment by cl-ement05** [comment]
> Thanks for the report, but this is already being tracked in issue #9320.

Sorry I didn't know
