### ISSUE TITLE
Why does Windows Terminal lock assets from "YourPhone"?

### ISSUE THREAD

**Issue by whorfin** [microsoft/terminal#10057]
### Windows Terminal version (or Windows build number)

10.0.19042.964, 1.7.1033.0

### Other Software

O&O AppBuster

### Steps to reproduce

Attempt to uninstall, yet again, and over and over, and every damn time windows updates, the ridiculous "YourPhone" which I will never use but consumes 256M and occasionally wakes up and eats my CPU.
That's not WindowsTerminal's fault, but the next bit is bizarre.
Have Windows Terminal open, launch O&O App Buster
https://www.oo-software.com/en/ooappbuster
and observe that WindowsTerminal has "NoiseAsset_256X256_PNG.png" from YourPhone open/locked
Killing Terminal, the uninstall completes, and Terminal seems unaffected

### Expected Behavior

I would expect WindowsTerminal to not be opening/locking files from rando Microsoft apps such as "YourPhone"

### Actual Behavior

![windowsterminal](https://user-images.githubusercontent.com/1237590/117551209-7afc3a80-aff9-11eb-84b4-68017028a319.png)

**Comment by whorfin** [comment]
...in case it is relevant, pretty much whenever i have WindowsTerminal open, I am running at least one Ubuntu bash shell

**Comment by KalleOlaviNiemitalo** [comment]
I wonder if this is caused by Windows deduplicating identical files between apps and "O&O App Buster" not supporting that.

**Comment by KalleOlaviNiemitalo** [comment]
If you try to uninstall YourPhone using [DISM /Online /Remove-ProvisionedAppxPackage](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-app-package--appx-or-appxbundle--servicing-command-line-options#app-package-servicing-options) and [Remove-AppxPackage](https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage?view=windowsserver2019-ps), does that work even while Windows Terminal is running?

**Comment by DHowett** [comment]
So, yeah, it's very likely something like that. The application packaging subsystem deduplicates data across different packages. This is one example of how applications that purport to "debloat" or in some other way damage your system _don't really know what's going on, and can break things._ We don't recommend their use.

**Comment by whorfin** [comment]
How do you recommend one _permanently_ remove YourPhone, then?
Terminal operates perfectly well without it installed 
Users would  not resort to such measures if you did not force unwanted apps on their machines

**Comment by Aldaviva** [comment]
There is indeed deduplication between assets of AppX packages, as alluded to above. This is documented in [`dism /Optimize-ProvisionedAppxPackages`](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-app-package--appx-or-appxbundle--servicing-command-line-options?view=windows-11#optimize-provisionedappxpackages):

> Optimizes the total file size of provisioned packages on the image by replacing identical files with hardlinks. Once an image with provisioned AppX packages is online, `/optimize-provisionedappxpackages` won't be able to optimize provisioned AppX packages. If you take an image offline and add packages, only the packages that are provisioned after the image was brought back offline will be optimized.

To permanently remove YourPhone, you can try using `Remove-AppxPackage` as mentioned above, as well as the machine-wide `Remove-AppxPackage --AllUsers` and `Remove-AppxProvisionedPackage`.
