### ISSUE TITLE
Ctrl-P is not recieved in vim

### ISSUE THREAD

**Issue by BrotifyPacha** [microsoft/terminal#10060]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

NVIM v0.5.0-dev+1256-gd19348923

### Steps to reproduce

- Open vim
- Bind something to ctrl-p : ```:nmap <Ctrl-p> :echo "Ctrl P triggered"```
- Press Ctrl-P

### Expected Behavior

Expecting to see "Ctrl P triggered" message

### Actual Behavior

Nothing is shown

**Comment by BrotifyPacha** [comment]
Tried unbinding it via
```
{
    "command": "unbound",
    "keys": "ctrl+p"
}
```
With no luck

**Comment by BrotifyPacha** [comment]
Thanks a lot! TLDR; It has nothing to do with Windows Terminal.

I had an extension in my browser that blocks desired key mappings. I configured it to block `Ctrl-P` and `Ctrl-W`, so when my vim reflexes poped up, i wouldn't close any tab or start printing it.

For some unknown reason extension also captured said keystrokes when browser was minimized.

I'm very sorry for bothering, thanks for suggested method of debugging it via wsl. The moment i pressed `Ctrl-P` and saw no keycode was exactly what made my brain click.

**Comment by zadjii-msft** [comment]
Glad you were able to figure it out!

\<off topic>

> For some unknown reason extension also captured said keystrokes when browser was minimized.

wow that sounds dangerous. Imagine if a malicious extension globally bound all keys, but then sent them through as if nothing happened. It could install itself as a global keylogger 😨

**Comment by BrotifyPacha** [comment]
Yeah, that sounds ominous. Will make an issue in Brave repo, maybe that's unintentional behavior.
