### ISSUE TITLE
Terminal hangs when running yarn watch statement over a few days(even close or minimise doesn't work)

### ISSUE THREAD

**Issue by brittotprince** [microsoft/terminal#10065]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software
webpack-cli 3.3.12
yarn v1.22.4

### Steps to reproduce

I have seen this issue multiple times when running **yarn** with a watch statement which inturn calls webpack

- Run webpack builds that watch over the changes in a specified folder.
- Leave it for over the weekend.

You can now see the whole 'terminal' is stuck. Not even close or minimize buttons work.

### Expected Behavior

The terminal shouldn't hang when running for continuous builds

### Actual Behavior

The terminal hangs after a couple of days. The top right buttons are also in the same state.

If we try to close 'Terminal' from the taskbar, the dialog box 'Do you want to close all tabs' comes up. But, it's not interactable and the clicks are not recorded.

The only way to close is to go to Task Manager and End the process.

Note: Verified that this issue is not happening for Command prompt.

**Comment by DHowett** [comment]
If you do end up with a Terminal instance in this state, can you use Task Manager to "Create [a] dump file..." of it (on the Details tab?) It's under `WindowsTerminal.exe`.

You can send that dump (please 7-zip it or something!) to me at the address on my GitHub profile.

**Comment by brittotprince** [comment]
Hi, I will try to recreate this issue and do as instructed.

**Comment by DHowett** [comment]
Oh, sorry about that! We may even be able to find crash reports if you file feedback _now_ for the instance that occurred 11 days ago. 😄

**Comment by brittotprince** [comment]
Hi,

Thank you for the message. I have shared the logs using the feedback hub just now. The title is the same as this thread and contains the issue number. Could you please check and let me know if something is missing.

Thankyou

**Comment by DHowett** [comment]
Sorry, we may need you to use the "Share a link to this feedback..." feature -- it turns out it is rather difficult to find an individual item in the feedback hub for us.

**Comment by brittotprince** [comment]
Hi,

Attaching the feedback link

https://aka.ms/AAco62y

**Comment by zadjii-msft** [comment]
Hey I dunno if we ever looked into this last year, but the feedback dump definitely timed out by now. Is this still happening/? If it is, filing feedback again might help debug. Otherwise, it might be easiest to do the following:


When the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us? 

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)

That's more likely to get a stack of windowsterminal that'll actually show us what's deadlocked.
