### ISSUE TITLE
Color transitions are not smooth

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#10062]
### Windows Terminal version (or Windows build number)

10.0.19042.928, 1.8.1032.0

### Other Software

lolcat (latest)

### Steps to reproduce

To reproduce, use Cygwin/MSys2/WSL, and run the following command in Bash:

```bash
printf '█%.0s' {1..400} | lolcat
```

### Expected Behavior

Running WSL in Xfce4 Terminal (VcXsrv): 

![image](https://user-images.githubusercontent.com/46838874/117581686-ceff4000-b11b-11eb-95df-9215baf84436.png)

### Actual Behavior

Running WSL in Windows Terminal:

![image](https://user-images.githubusercontent.com/46838874/117581663-b42ccb80-b11b-11eb-8ff5-aa73a305d072.png)

**Comment by j4james** [comment]
Try setting the truecolor option with `lolcat --truecolor` or `lolcat -t`.

**Comment by rashil2000** [comment]
It works with `--truecolor`, but I wonder why it behaves differently by default?

**Comment by j4james** [comment]
Looking at the source, I think lolcat checks the `COLORTERM` environment variable. So if you set that to `truecolor`, it'll probably select the truecolor option automatically. I'm guessing Xfce sets the `COLORTERM` variable itself.

**Comment by rashil2000** [comment]
Ah, thanks for the detailed answer! Since WT doesn't have a way to set env vars (I believe #9287 is still under review), I'll make a user-wide entry in the Start Menu -> Environment Variables for COLORTERM. 
Should I close this then?

**Comment by j4james** [comment]
Yeah. If you're happy that your issue has been addressed - or will be addressed by #9287 - then you can probably close.
