### ISSUE TITLE
It doesn't launch

### ISSUE THREAD

**Issue by vulture990** [microsoft/terminal#10061]
### Windows Terminal version (or Windows build number)

1.7.1091.0

### Steps to reproduce

when launching it

### Actual Behavior

it throws at me "Application installation failed with error message: error 0x80004004: Cannot install because the following applications must be closed Microsoft.WindowsTerminal_1.7.1091.0_x64__8wekyb3d8bbwe. (0x80004004)"

**Comment by vulture990** [comment]
Yeah sure here: ow srry it s in frensh but the message it said is:"Application installation failed with error message: error 0x80004004: Cannot install because the following applications must be closed Microsoft.WindowsTerminal_1.7.1091.0_x64__8wekyb3d8bbwe. (0x80004004)"
![ll](https://user-images.githubusercontent.com/73004418/117877101-aa2dd880-b293-11eb-973d-0e738081eca6.png)
,it seemed to work just fine in my other laptop but with the current one that I'm using now  it throws this

**Comment by DHowett** [comment]
This is going to sound like a very "Windows user" thing to ask, but . . . what if you reboot your machine?

Also, what build of Windows are you on?

**Comment by zadjii-msft** [comment]
That's so bizarre - the OS clearly thinks the app is in use, but presumably, after a reboot, it definitely wouldn't be. 

If you go to the Settings app, then go to Apps, does the Terminal appear in that list at all? If so, you might be able to fix this by going to Advanced Options, then hit "Repair"

**Comment by vulture990** [comment]
ow yeaaaah srry guys if im breaking your balls for this but even when I hit repair 
![b](https://user-images.githubusercontent.com/73004418/118279488-bba4f980-b4ba-11eb-88bd-8ff256191132.png)
IT couldn't open the message in the pop stats that it can't open bcz it s in update  and when I try to reopen it again it completely shuts down without showing me this pop up 
![lol](https://user-images.githubusercontent.com/73004418/118279511-c2337100-b4ba-11eb-907c-efba37d04900.png)

**Comment by vefatica** [comment]
> That's so bizarre - the OS clearly thinks the app is in use, but presumably, after a reboot, it definitely wouldn't be.

How about startup apps (TaskMgr, startup tab).  It's in there (disabled here).
