### ISSUE TITLE
The `nextTab` and `prevTab` actions do not work correctly when initiated via `wt.exe` or the command palette

### ISSUE THREAD

**Issue by gurnec** [microsoft/terminal#10070]
In short, `wt focus-tab --next` and `--previous` don't do anything at all on my system, while `Next tab` and `Previous tab` via the command palette behave oddly, although I can't imagine that the latter is often used by anyone.

### Windows Terminal version (or Windows build number)

1.8.1032.0

#### Case 1:
Run `wt -w new new-tab ; new-tab ; focus-tab --next` (or `--previous`).

#### Case 2:
Run `wt -w new new-tab ; new-tab`.

In the new window, run `wt -w 0 focus-tab --next` (or `--previous`).

#### Case 3:
Run `wt -w new new-tab ; new-tab ; new-tab`.

In the new window, open the command palette (by default using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and type in `Next tab` (or `Previous tab`) <kbd>Enter</kbd>.

#### Case 1:
The first tab is focused.

#### Case 2:
The first tab is focused.

#### Case 3:
The desired tab (according to the `tabSwitcherMode`) is focused.

#### Case 1:
The `focus-tab` subcommand is ignored; the second tab remains focused.

#### Case 2:
The `focus-tab` subcommand is ignored; the second tab remains focused.

Note that in the two cases above, `wt focus-tab --target 0` works correctly.

#### Case 3:
This depends on the `tabSwitcherMode`:

 * `mru` — the desired tab is focused for a split second, and then the originally-focused tab regains focus.
 * `inOrder` — the desired tab is focused for a split second, and then tab index 0 gains focus.
 * `disabled` — the desired tab is focused (there is no bug in this case).

----------

My apologies if I should have separated this into two issues.

Thanks!

**Comment by DHowett** [comment]
Discussion during triage: We probably shouldn't even be using MRU during `focus-tab`.

**Comment by Don-Vito** [comment]
Yeah, MRU during startup makes little sense. I will issue a PR (it is few lines of code). However, I thought we need to update this in documentation and found no documentation for these flags. Am I missing something?
