### ISSUE TITLE
Drag folder/file to '+' button to open new tab in directory

### ISSUE THREAD

**Issue by TomByrne** [microsoft/terminal#10073]
# Description of the new feature/enhancement

Would be nice if dragging and dropping a folder from explorer onto the plus button created a new shell within that directory.
If a file is dropped, then the parent folder should be used.

As a bonus it would be nice if dragging onto an existing tab set the CWD of that shell to the directory, but I believe this would require more configuration per shell-type (i.e. would need to know how to navigate to the folder, and in the case of unix-like shells how to transform the path).

Note: Currently dragging a file/folder into an existing shell (i.e. not the tab) pastes the path into that shell; I'm not suggesting that this change at all (although if the path-transformation issue mentioned above is solved then maybe it could be re-used here, as windows-format paths are fairly useless in a unix-like shell).

**Comment by zadjii-msft** [comment]
This is a neat idea, thanks!

> As a bonus it would be nice if dragging onto an existing tab set the CWD of that shell to the directory, but I believe this would require more configuration per shell-type (i.e. would need to know how to navigate to the folder, and in the case of unix-like shells how to transform the path).

Yea, you've pretty much laid out why that wouldn't work. What if you dragged a file into `vim`? You'd almost expect vim to open up the file, but there's no real way to tell `vim` "Hey the user drag-dropped {this path} onto the terminal"

We have a totally other issue on the repro tracking "drag drop for WSL should use WSL paths", but I'm too lazy to link that right now 😛

**Comment by skyline75489** [comment]
Here, #1772. I think this is what you looking for 😄
