### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by giantninja908** [microsoft/terminal#1007]
Project fails to build, same issue each time. 

MSB3073	The command "mc.exe /h D:\New Terminal\\obj\x64\Release\Propsheet.DLL\ /r D:\New Terminal\\obj\x64\Release\Propsheet.DLL\ strid.mc" exited with code 1.

0x3 trying to open file <Terminal\\obj\x64\Release\Propsheet.DLL\>.	Propsheet.DLL	D:\New Terminal\src\propsheet\mc

There is no file called "mc.exe" in src\propsheet is my guess, but can't pinpoint it directly.

**Comment by DHowett-MSFT** [comment]
I bet this is #438.

**Comment by uk0** [comment]
deal all this release Now !! https://github.com/uk0/microsoft-terminal-release
