### ISSUE TITLE
Pasting text adds the same content twice

### ISSUE THREAD

**Issue by buttoniusrex** [microsoft/terminal#10079]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Running Ubuntu with ZSH

### Steps to reproduce

1. Copy some text, using either CTRL+C, or using the right-click on the mouse
2. In the terminal, on a blank line, either CTRL+V or right-clicking on the mouse to paste the text

### Expected Behavior

The line I copied is pasted into the terminal once.

E.g. if I copy "this is a string i copied", that is all that should be pasted.

### Actual Behavior

I instead get "this is a string i copiedthis is a string i copied" with the second instance highlighted. Additionally, not only is the text duplicated, but it also overwrites the previous text that was there. So if I'm running `git add` and try to paste the file path, I end up with only the file path printed twice.

Closing and reopening the Windows Terminal fixes it temporarily, however shortly afterwards this behavior resumes.

![copied_test](https://user-images.githubusercontent.com/38411730/117897979-06d2d700-b318-11eb-9127-eb0eba0b78aa.PNG)

**Comment by zadjii-msft** [comment]
Does this only happen with `zsh`, or does it happen with other shells as well? `cmd.exe`, `powershell`, `bash`, etc.

> with the second instance highlighted.

That's definitely curious to me. If you click&drag to start a new selection, will the highlighted text go away? I'm trying to determine if that highlighting is from the Terminal's selection, or something that was output by `zsh`.

**Comment by buttoniusrex** [comment]
@zadjii-msft - I can only reproduce this in Windows Terminal. `cmd.exe`, `powershell` do not duplicate the code.

The issue also is that I cannot predict what causes it. It will work correctly for a time, and then suddenly I get duplicated text, which requires a restart of the Terminal.

**Comment by buttoniusrex** [comment]
The other thing I forgot to mention is that when I paste the text, not only is the text duplicated, but it also overwrites the previous text that was there. So if I'm running `git add` and try to paste the file path, I end up with only the file path printed twice.

(I've updated the Actual Behaviour section to reflect this)

**Comment by zadjii-msft** [comment]
Okay so this _really_ sounds like a `zsh`-specific problem, though my question would be "why is the text duplicated"? It seems like it shouldn't be by all accounts. More reading on the subject:


* [zsh selects a pasted text](https://unix.stackexchange.com/questions/331850/zsh-selects-a-pasted-text)
* [Why is pasted text highlighted in macOS Catalina's Terminal?](https://superuser.com/questions/1622933/why-is-pasted-text-highlighted-in-macos-catalinas-terminal)
* [Zsh 5.1 and bracketed paste](https://archive.zhimingwang.org/blog/2015-09-21-zsh-51-and-bracketed-paste.html)

Follow up questions:

* what version of `zsh` are you running? 
* What does your zsh config look like?
* What version of Ubuntu are you running?
* What's `TERM` set to?
* you're not using `ssh.exe` by any chance, are you?

I've just tested this out with what seems to be a pretty stock `.zshrc`, and I'm not seeing the duplicated text or the overwritting behavior. To me, that sounds like `zsh` is emitting the wrong set of escape sequences to highlight the pasted text, and instead returning to the start of the prompt, or... just plain not? It's definitely weird.

**Comment by buttoniusrex** [comment]
`zsh` version: zsh 5.8
`zsh` config: https://gist.github.com/buttoniusrex/408708c02ee30673cd2cc57437064361
Ubuntu version: 20.04 LTS

Not sure what `TERM` is, but if I run `echo $TERM` I get `xterm-256color`.

Not using `ssh.exe`, rather I'm running `wsl.exe`.

**Comment by kbalint** [comment]
70% of the cases it happens in Terminal>bash for me, 30% in Terminal>Command Prompt



https://user-images.githubusercontent.com/4146263/121695093-05d5c680-cacb-11eb-8f95-4d85b1db0337.mp4

**Comment by buttoniusrex** [comment]
Good idea to take a video. Right now I don't know how this can be addressed, since the reproducibility is quite unreliable.

**Comment by earthquakesan** [comment]
@buttoniusrex @kbalint 

I could reproduce this problem with zsh 5.8 on macos big sur. Simply set `set -o allexport` inside terminal session (I am using iTerm2) and then try to copy/paste something.

I am also using zsh on my windows machine (WSL2) and experienced the same behavior yesterday. Did not link it `set -o allexport` command then.

**Comment by buttoniusrex** [comment]
I can confirm what @earthquakesan has reported - this produces exactly the error I reported. I still cannot pinpoint how or why this happens at some point during an open Terminal session. Can anyone clarify why `set -o allexport` would be producing, on paste, an overwrite of the current line + a duplication of the text?

This issue unfortunately makes working with the Terminal day-to-day quite frustrating (even though I am immensely grateful to have it), since copy+paste is a basic feature I rely on for work.

**Comment by DHowett** [comment]
If you can reliably reproduce this _or_ put up with some amount of consistent annoyance, would you mind grabbing a trace from the ["debug tap"](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap)? It has to be enabled for an entire session, thus the annoyance, but it gives us an input/output trace. :smile:

**Comment by DHowett** [comment]
(That only captures the Terminal half of the transaction, but I'd like to see if Terminal is sending the string multiple times itself!)

**Comment by buttoniusrex** [comment]
@DHowett I think I've finally figured out what's causing it! Because of my work setup, I need to override some environment variables by running a script using, e.g. `source ~/work/config/env` with `env` being the script in question.

Before running `source`, copy+paste worked perfectly. I ran the command, copied the word "source", and presto! Pasting the word results in wiping that line and pasting the contents twice.

Debug tap displays the duplication:
`␛[200~source␛[201~␛[32msourcesource`

Now the question is: why the heck is `source` causing this?

**Comment by DHowett** [comment]
Hmmmm. It may be helpful to know what environment variables are in that `env` file; `source` alone shouldn't do anything except allow a script to modify the parameters of the current shell (!)

Which of those debug tap things is in red? Mind sending a screenshot of that part? Thanks!

**Comment by buttoniusrex** [comment]
OK so I looked into the file, and with some testing, I've discovered it's the `set -a` command at the beginning of the script that is the culprit. I wonder if that's related to @earthquakesan's comment about using `set -o`.

Here is a screenshot from debug tap before and after. I copied the text `~/work` as the test:
![debugtap](https://user-images.githubusercontent.com/38411730/132415295-3c1d5052-c1f8-422d-94f2-cbdf81400df2.JPG)

**Comment by DHowett** [comment]
I'm satisfied that this isn't a _terminal_ issue, but I am not satisfied that it is not an issue somewhere. Is adding/removing the `set -a` line the only difference between this working properly and it not working?

I've tried everything I can think of around that, and still can't reproduce it. Hmmm.

**Comment by DHowett** [comment]
> Glad to hear it! I sent a bug report to Zsh - turns out it's not the shell, but potentially something to do with the tooling or theming. I'm using Oh-My-Zsh and Powerlevel10K. Since you couldn't reproduce it, are you using either of those by any chance? Might help me to narrow it down.

I'm not using either of those! I was trying to repro with the stock config plus various options called out in this thread!

**Comment by buttoniusrex** [comment]
Great. I never thought to mention them because I blatantly assumed it was a Terminal issue. After chatting with the Zsh guys, I tested on stock setup and can't reproduce it either. So definitely something to do with the additional configuration I have. Anyways, that's about it from me - if I get the solution I might post it here anyway in case someone wanders down the same path I did.

**Comment by Loongphy** [comment]
For me, it only happened on right-clicking on the mouse. I'm sure that it is a terminal issue after I tried cmd.exe, powershell and bash.

**Comment by DHowett** [comment]
Please file a new issue with the template -- you're seeing something that is not covered by this thread :)
