### ISSUE TITLE
Color is not applied entirely on a tab

### ISSUE THREAD

**Issue by leduyquang753** [microsoft/terminal#10080]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

1. Open a tab.
2. Recolor the tab.

### Expected Behavior

The new color is applied entirely on the tab.

### Actual Behavior

The new color is not applied entirely on the tab, there are two spots of the original color on either side of the tab.

![image](https://user-images.githubusercontent.com/26449060/117933232-8918c680-b32b-11eb-9ef1-08b30f0a10ed.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #7133 for more discussion.

/dup #7133
