### ISSUE TITLE
Multi tab input from one textbox

### ISSUE THREAD

**Issue by marbaa** [microsoft/terminal#10089]
# Description of the new feature/enhancement
**Be able to send commands from one place to all active ssh sesions.**

I spent a lot of time working on remote linux servers. Often I need to run same commands on multiple servers. I think some common textbox, which wil send output to all tabs will be useful.

![terminal_multi_input](https://user-images.githubusercontent.com/40859847/118123450-8cc45000-b3f4-11eb-9f27-bb1301bc85e5.png)

# Proposed technical implementation details (optional)
I do not have implementation details, just some hints when I was trying to write little tool for it using WINAPI. It was working pretty good, but there was one observation.
While typing into textbox and live sending each key press to all sessions, it makes CPU usage very big. Whole OS got slowed down. Therefore typing text should appear only in textbox, and after Enter press, command will be sent to all tabs.

Rough example can be seen [here](https://www.youtube.com/watch?v=ndac2wgnwEg)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2634  for more discussion.

/dup #2634
