### ISSUE TITLE
zooming eats lines

### ISSUE THREAD

**Issue by nc-x** [microsoft/terminal#10087]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.8.1032.0

### Other Software

PowerShell 7.1.3
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

### Steps to reproduce

I am using ssh to connect to an Azure Ubuntu VM. I typed in a command, I typed in another command. Then I zoomed out using Ctrl-MouseScroll. A few lines (atleast 1 line) went missing and changing the zoom again does not bring it back again either. I am not sure whether the issue is with wt / pwsh / openssh.

For e.g. In the below screenshot, the commands `sudo apt upgrade` and `sudo apt install zip` got merged.

![image](https://user-images.githubusercontent.com/43749640/118090156-cbeba480-b3e6-11eb-869c-8d40e97ec251.png)

### Expected Behavior

Lines not getting eaten up.

### Actual Behavior

Lines getting eaten up.

**Comment by nc-x** [comment]
Actually, this is unrelated to zooming.

I can't show the exact output, however, I got this issue on another machine, while ssh'ed -
![image](https://user-images.githubusercontent.com/43749640/118129053-52b97500-b419-11eb-87ec-631f8debd7d2.png)
basically, i ran a command, and in-between its output, last two commands were displayed, and then the output continued.

This was with -
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
Windows Terminal Preview, Version: 1.8.1032.0
PowerShell Version 5.1.19041.906

**Comment by DHowett** [comment]
Thanks for the report! This looks like a /dup of #6546 with a little bit of flavor (in your original screenshot) of "applications that set scrolling margins don't do the exact right thing" (apt uses scrolling regions :P)
