### ISSUE TITLE
All dropdown lists in settings GUI are getting out of window bounds !!

### ISSUE THREAD

**Issue by Samarth2028** [microsoft/terminal#10082]
### Windows Terminal version (or Windows build number)

10.0.19042.928

### Steps to reproduce

Minimal steps to reproduce:
1.) Open the terminal (Not as full screen).
2.) Go to settings GUI and navigate to the appearance tab of either Powershell or Command Prompt
3.) Open any dropdown out of color-schemes, font-face, or font-weight and drag the scroll wheel to see the dropdown's getting out of window bounds.
![terminal_issue](https://user-images.githubusercontent.com/26890697/118041352-eb73c600-b32f-11eb-87a7-a4aff16d9d65.png)
 

### Expected Behavior

That at least dropdown lists not go out of window bounds, upon scroll event.

### Actual Behavior

![terminal_bug](https://user-images.githubusercontent.com/26890697/118041704-591ff200-b330-11eb-8598-55861ae1e777.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
