### ISSUE TITLE
Did it crash? I do not know

### ISSUE THREAD

**Issue by kavinluo** [microsoft/terminal#10085]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 版本: 1.8.1092.0

### Other Software

Win10 up to date 

### Steps to reproduce

  This is the second time I tried to install. The first time I installed it through the store, when I opened a new tab during use, it would become inoperable. I had no choice but to uninstall. The second time was just now. After I downloaded the latest installation from GitHub, the picture appears. This is every time I start it. 

### Actual Behavior

He was stuck for at least a few minutes 
![image](https://user-images.githubusercontent.com/7992924/118065609-d484b080-b3cf-11eb-8fad-0515e26b6544.png)

**Comment by DHowett** [comment]
This is really strange! Can you share the contents of your settings file?

It is here: `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`

**Comment by kavinluo** [comment]
year ，thanks

[settings.zip](https://github.com/microsoft/terminal/files/6490427/settings.zip)

**Comment by zadjii-msft** [comment]
Hmm. Okay, our theory that the color scheme is busted is definitely not right - that's all fine. 

I wonder if the problem comes from

```json
                "backgroundImage": "D:\\\u684c\u9762\u80cc\u666f\\mo\\01.jpg",
```

in your default profile. Could you try removing that, to see if it works fine without that image? It's possible that path might be upsetting the terminal for some reason.

This might be a weird variation on #6164

**Comment by kavinluo** [comment]
![image](https://user-images.githubusercontent.com/7992924/118605063-70efee00-b7e8-11eb-86d7-975d523813d8.png)
It is not caused by the background image. The problem exists even if I have not set the background image. 


So it doesn't matter

**Comment by zadjii-msft** [comment]
Weird. Can you interact with the Terminal at all? Does typing in the Terminal move the cursor at all? Does clicking on the new tab button work? Do keybindings work, like <kbd>ctrl+shift+t</kbd> for new tab, or <kbd>ctrl+shift+p</kbd> to open the command palette?
