### ISSUE TITLE
New feature required: save screen output to file

### ISSUE THREAD

**Issue by BarretRen** [microsoft/terminal#10086]
# Description of the new feature/enhancement
Can we add a new functionality to save the screen output to files, like Putty does.

# Proposed technical implementation details (optional)
I'm a programmer and I always use the Putty to connect the remote server via SSH. Often, I need to print the program traces/logs in Putty and save them to files on my loal PC. Then I can open the files with editors or share them to others.

Can we consider to add such functionality? I think that's very useful.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/642> likewise requests automatic logging to files.

**Comment by BarretRen** [comment]
OK, thank you all
