### ISSUE TITLE
add a settings to open termian with same size/position from last close

### ISSUE THREAD

**Issue by pcause** [microsoft/terminal#10088]
# Description of the new feature/enhancement

I want a setting to have terminal remember last size and position (and virtual desktop) as it had the last time terminal was closed.  There would be a launch option to override this behavior as well.  

# Proposed technical implementation details (optional)

 
Most windows applications from Microsoft seem to support such behavior just do it like they do.
.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766
