### ISSUE TITLE
Fix verb on command in OpenConsole.psm1 that is giving a warning on load

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#10097]
PS D:\src\terminal> ipmo .\tools\OpenConsole.psm1
WARNING: The names of some imported commands from the module 'OpenConsole' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

Someone added a command with an unapproved verb. Find it, choose an appropriate one, find usages and update them, etc.

**Comment by LuanVSO** [comment]
```
The 'Verify-XamlFormat' command in the OpenConsole' module was imported, 
but because its name does not include an approved verb, it might be difficult to find. 
suggested alternative verbs are "Test".
```

**Comment by zadjii-msft** [comment]
\*cough* https://github.com/microsoft/terminal/pull/9589#discussion_r603428546

**Comment by DHowett** [comment]
yes yes i caused this ;P
