### ISSUE TITLE
Combine pane taskbar states in the taskbar

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#10090]
> > It doesn't seem like a bad idea to combine these states somehow (with a setting), but we'd want to make sure we're clear what happens in cases like:
> > 
> > * one tab has progress=N%, another tab has no progress
> > * one tab has progress=N%, another tab has progress=M%
> > * one tab has progress=N%, another tab has progress=indeterminate
> > * one tab has progress=N%, another tab has progress=M% AND is in the error state
> > 
> > etc.
> 
> Sure, we have to specify this exhaustively.

It is specified in [Taskbar API here](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setprogressstate#how-the-taskbar-button-chooses-the-progress-indicator-for-a-group) how progress bars are combined for multiple windows collapsed into single button. For consistency it would be good idea to duplicate the behavior.

_Originally posted by @tringi in https://github.com/microsoft/terminal/issues/6700#issuecomment-770590932_

**Comment by zadjii-msft** [comment]
Interesting. There are already some other weird edge cases about the progress state I didn't notice before, but are making testing.... tricky.

* set one pane to indeterminate, the other to warning,75%. If you focus the warning pane, the taskbar will show warning,75%. If you then focus the indeterminate pane, the taskbar will switch to warning,100%. Focus another tab, then back to the tab with the indeterminate pane - correctly shows indeterminate in the TB.

**Comment by zadjii-msft** [comment]
I'm not sure I totally love this, the way it's exactly specified by the taskbar API. For them, they always combine the states of an entire group of windows, with a priority order. So if there's multiple windows with different states, then "Error" is more important than "Warning", more than "Normal", more than "Indeterminate". 

IMO, I'd almost expect more nuance to this. It feels weird to have the focused pane be set to indeterminate, then an adjacent pane set to (normal,25), and have the tab and taskbar show (normal,25).

![image](https://user-images.githubusercontent.com/18356694/125645766-36356dad-f8b7-447f-b11f-925c43b9081b.png)

I kinda think that the focused pane should always take priority, if it has progress set at all. If it doesn't, then I think we should fall back to the "combine" behavior. Same with the window itself - if the focused tab has a set progress state, let's use that one. Otherwise, we'll fall back to combining the states of all the other tabs.


Current progress is in `dev/migrie/b/progress-bugs`

**Comment by tringi** [comment]
The Taskbar rules, prioritizing errors, are designed to bring attention the user can solve.

For example: It would be irritating if you had put two copy operations on the background, and once one had finished, the button would turn from green to orange, to indicate prompt (e.g. overwrite) at 1%, which you could've solved much sooner and saved time.
