### ISSUE TITLE
Windows terminal does not accept keyboard

### ISSUE THREAD

**Issue by dcprj** [microsoft/terminal#10095]
"If you're experiencing an input issue that is not helped by exiting MSI Afterburner or re-enabling the "Touch Keyboard and Handwriting Service", please file a new issue."

I have the "Touch Keyboard and Handwriting Service" running and even so Windows Terminal does not accept keyboard input.
The installed version is "Windows Terminal
Version: 1.7.1033.0 "

Thanks

**Comment by zadjii-msft** [comment]
There's a bunch of help from @ebadger in #9890 - could you try following the steps in that thread, and see if that resolves the issue?

(sorry for the runaround, we really need to turn that thread into a guide on the troubleshooting page of the docs)

**Comment by dcprj** [comment]
Thanks

**Comment by edhCoder** [comment]
Having the "Touch keyboard and Handwriting Panel Service" running did not fix the issue.   Killing the MsCtfMonitor.dll  task per the instructions in  the above link:  [#9890](https://github.com/microsoft/terminal/issues/9890)  worked
