### ISSUE TITLE
Tab bar not shown.

### ISSUE THREAD

**Issue by 0324bence** [microsoft/terminal#10094]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Today I opened the terminal, and the Tabs bar didn't show up, so I cannot move my window. Powershell (my default terminal) still works.

### Steps to reproduce

1. Start the program
2. Have not title or tab bar

### Expected Behavior

To have a title and tab bar, so I can move the window

### Actual Behavior

![image](https://user-images.githubusercontent.com/61208059/118307883-967caf00-b4eb-11eb-9c0c-e27254aebd68.png)
This is how it looks. I have looked into the settings, and I cannot change anything that would make this go back to normal

**Comment by zadjii-msft** [comment]
Looks to me like the Terminal opened in focus mode. Could you press <kbd>Ctrl+,</kbd>, and verify what "Launch Mode" is set to?

**Comment by 0324bence** [comment]
Yes Thank you, this was the solutinon. I can't belive I didn't notice that.
