### ISSUE TITLE
ANSI characters appearing after setting the title

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#10104]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19042.985]

### Other Software

 'git' (2.31.1.windows.1) from scoop and using that as the Bash provider
 'aws' (2.2.5) AWS CLI that this is having problems with

### Steps to reproduce

When I do

```
aws logs tail --follow --region us-west-2 --since 0s my-cloudwatch-logs
```

I see the colors correctly, but when I set the title as follows

```
echo -ne "\033]0;☁ my-cloudwatch-logs \a" && aws logs tail --follow --region us-west-2 --since 0s my-cloudwatch-logs
```

The colors stop working and I see the ANSI escape codes.

This used to work before I reinstalled Windows

### Expected Behavior

Colors should appear and not ANSI codes.  Title should get set.

### Actual Behavior

ANSI Codes are appearing.  Title is getting set.

**Comment by zadjii-msft** [comment]
Also, does 

```
echo -ne "\033]0;my-cloudwatch-logs \a" && aws logs tail --follow --region us-west-2 --since 0s my-cloudwatch-logs
```

work as expected?

**Comment by trajano** [comment]
direct has color
![image](https://user-images.githubusercontent.com/110627/118517163-fac68b00-b704-11eb-88d7-0ba9dc41edd5.png)

No color when setting the title
![image](https://user-images.githubusercontent.com/110627/118517370-247fb200-b705-11eb-9e59-432bb18a7d64.png)

**Comment by zadjii-msft** [comment]
Definitely another case of VT processing being disabled, though I don't know why this wouldn't work when preceeded by an `echo`. We've got a pile of these elsewhere on the repo, but this one seems different. I don't have any idea why the echo in the same commandline would disable this. 


I wonder if 
```
printf "\033]0;☁ my-cloudwatch-logs \a" && aws logs tail --follow --region us-west-2 --since 0s my-cloudwatch-logs
```

would work instead?

**Comment by trajano** [comment]
@zadjii-msft yup I was actually hesitant on creating another one, but this is a very weird and specific scenario.

**Comment by zadjii-msft** [comment]
so this sounds like something that must have recently regressed in msys, between whatever version you had before you reinstalled windows and whatever's currently installed. Maybe this should get moved upstream?

**Comment by trajano** [comment]
It's actually the same version.  But I had a fresh install of Windows so I am not sure.

![image](https://user-images.githubusercontent.com/110627/118529006-05871d00-b711-11eb-8065-5df069d4ec23.png)

**Comment by trajano** [comment]
Hypothesis confirmed 

![image](https://user-images.githubusercontent.com/110627/118529394-77f7fd00-b711-11eb-97b9-30ff776368a1.png)

**Comment by zadjii-msft** [comment]
oh woah, this actually looks _exactly_ like #9607, with a touch of #6634

**Comment by trajano** [comment]
@zadjii-msft the difference betweem #9607 and this is that `aws` actually processes the data now.  But my comment in #6634 which points to https://github.com/starship/starship/pull/2258#issuecomment-771943572 actually gave me the workaround I need

Basically I have to close off the `stdin` 
```
(echo -ne "\033]0;☁ title  \a" < /dev/null)
```
![image](https://user-images.githubusercontent.com/110627/118532602-26517180-b715-11eb-8920-23182e1b1a68.png)

Closing this for now since I have a workaround and it appears to be an upstream msys/cygwin issue
