### ISSUE TITLE
Move SUI Preview border color away from ToggleButtonDisabledBorderThemeBrush

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10102]
It is not a toggle button, and so it should not be using ToggleButton's resources.

We should look up the base resource that `ToggleButtonDisabledBorderThemeBrush` is based on and use that instead.

**Comment by PankajBhojwani** [comment]
It uses `SystemControlForegroundBaseMediumLowBrush`! I think you were looking at an old commit

**Comment by DHowett** [comment]
Wow, I must have been. Thanks!
