### ISSUE TITLE
Bug Report, can't type @ on a norwegian keyboard.

### ISSUE THREAD

**Issue by carlhen** [microsoft/terminal#1010]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.113]
Windows Terminal version (if applicable): Commit https://github.com/microsoft/terminal/commit/0f62ec81d84e8abb97bece2b3e89f82f6fe09f42

Any other software?
```

# Steps to reproduce
1. Use the norwegian keyboard layout.
2. Open cmd in Windows Terminal
3. Try to do [alt gr] + 2 to get @.

# Expected behavior
Terminal prints @.

# Actual behavior
Terminal prints 2.
In an ssh connection, "(arg: 2)" comes up.

**Comment by zadjii-msft** [comment]
This is a dupe of #521
