### ISSUE TITLE
Crash in main when saving any setting with SUI

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#10103]
### Windows Terminal version (or Windows build number)

main

### Other Software

N/A

### Steps to reproduce

Note, this is separate from #10003.

Repro:
1. Open SUI
2. Click 'Save'
3. Crash

Did some digging and it seems that we have an unhandled exception when trying to navigate back to the last selected item in the SUI (in `MainPage::UpdateSettings`, in the `SettingsNav().SelectedItem(item)` call on lines 139 and 152). 

### Expected Behavior

No crash

### Actual Behavior

Crash

**Comment by mpela81** [comment]
It seems to happen if you "Discard changes" as well.

**Comment by PankajBhojwani** [comment]
This was resolved in #10124
