### ISSUE TITLE
Azure cloud shell exited unexpectedly

### ISSUE THREAD

**Issue by Jonathon52306** [microsoft/terminal#10100]
### Windows Terminal version (or Windows build number)

1.7.1091.0

### Steps to reproduce

launch Azure Cloud Shell and login

### Actual Behavior

![image](https://user-images.githubusercontent.com/46887506/118344636-cd8da780-b561-11eb-80f8-5b9dd531c09e.png)

**Comment by KalleOlaviNiemitalo** [comment]
Do you also get Chinese in the command palette etc., or only in the Azure Cloud Shell?

**Comment by KalleOlaviNiemitalo** [comment]
See also <https://github.com/microsoft/terminal/issues/8972#issuecomment-770832800>.

**Comment by skyline75489** [comment]
@KalleOlaviNiemitalo  I think he's complaining that Azure Cloud Shell immediately exits after connection.

**Comment by zadjii-msft** [comment]
Okay, so it crashed right around the `AzureConnection::_StoreCredential` code. I wonder if we crashed trying to store the credentials. A feedback hub dump would be informative.

/feedback
