### ISSUE TITLE
Duplicate the tab with the same path

### ISSUE THREAD

**Issue by Taswen** [microsoft/terminal#10105]
# Description of the new feature/enhancement
Now CTRL + SHIFT + D can copy the existing tab page (with the same configuration file). New tabs always start with the default path, such as `C:/Users/myUserName`, even though my working path has been moved to `D:/somePath`.
For me, opening a new tab is often just to operate around the previous path. If the path is too deep, I have to `cd`  in again.
It's also more annoying for remote operations.

# Proposed technical implementation details (optional)
1. For tab located on the local file system, it should just save the path and reopen in the new tab.
2. For tab that is connecting to a remote, to save SSH’s account temporarily for automatic login may help.

**Comment by skyline75489** [comment]
For local operations, it's possible. But you need to manually configure the shell for now. See https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033 for help if you're a PowerShell user.

There are also discussions about the SSH scenarios in #3158 and unfortunately that is not possible at the moment. Nor do I think it will be possible in the future.

**Comment by zadjii-msft** [comment]
Yep, that's all correct. For more info, see:

* #8330
* #8214
* #8166
* https://github.com/MicrosoftDocs/terminal/issues/285

/dup #3158
