### ISSUE TITLE
Tab size after closing another tab.

### ISSUE THREAD

**Issue by anujjoshi63** [microsoft/terminal#10101]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.7.1033.0

### Steps to reproduce

1. Open 2 tabs in windows terminal
2. While keeping 1st tab active, close 2nd tab using 'x' button and dont move the mouse cursor.

NOTE: moving the curor away from the 'x' button does do the thing which is expected.

### Expected Behavior

It was expected for the tab size to restore to single tab size.

![image](https://user-images.githubusercontent.com/14955086/118390824-d4461880-b64e-11eb-896c-141b5aab0127.png)

### Actual Behavior

Size of tab gets double (added up with closed tab's size) 

![image](https://user-images.githubusercontent.com/14955086/118390736-5124c280-b64e-11eb-9a4c-a7059d1bc3ef.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9822 and the upstream https://github.com/microsoft/microsoft-ui-xaml/issues/4971 for more discussion.

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/4971
