### ISSUE TITLE
Settings pane breaks input: cannot exit full-screen from settings pane nor access "ctrl+shift+p"

### ISSUE THREAD

**Issue by tabedzki** [microsoft/terminal#10116]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Microsoft Terminal 1.7.1033.0

### Steps to reproduce

Enter the new settings GUI/pane after loading up a terminal full screen. F11 does not work when trying to exit nor does ESC. 

Sample step:
1. Open Powershell in Terminal.
2. F11 to go full screen
3. Ctrl+shift+p, then "Open settings..."
4. Congratulations, you are now "locked" until you shift+tab to the other terminal. Ctrl+shift+p does not work in this settings pane either.

### Expected Behavior

Being able to easily escape full screen mode using F11 or esc. The F11 also does not work to enter full screen from the settings pane. 

### Actual Behavior

You are locked and no common tricks (alt+f4, esc, ctrl+shift+p) helps. Only the shift+tab works to get rid of this. Probably a niche case but I thought it was the full screen Windows settings app since it has a similar UI and I launched it full screen. I was locked until I try to kill it form the taskbar and it said, "do you want to kill all tabs" which gave me the idea of "shift+tab". 

Unrelated, is there a solid way to do screen record while capturing the inputs? I wanted to add a gif. I know that VSCode has a "Developer: Toggle Screencast Mode". Is there a feature like that in Windows overall? Where's the appropriate place to make a new issue for that feature?

**Comment by zadjii-msft** [comment]
Thanks for the request! This is basically jus a variation on #8767 - see that thread for more details.

/dup #8767

> Unrelated, is there a solid way to do screen record while capturing the inputs? I wanted to add a gif. I know that VSCode has a "Developer: Toggle Screencast Mode". Is there a feature like that in Windows overall? Where's the appropriate place to make a new issue for that feature?

There's another request already open elsewhere on the repo for that, but IMO the best solution is just to use a dedicated piece of software for recording the screen. I personally use ScreenToGif. The Terminal isn't ever going to be able to compete at recording itself vs what a dedicated screen recorder like ScreenToGif can do 😝

**Comment by tabedzki** [comment]
Thanks! I knew about the ScreenToGif but I didn't know they had a keystroke capture feature. Also, sorry for not finding the dup ticket. I went back a few pages to find a similar ticket but didn't search through all the tickets. Glad to see it is something y'all are working on.
