### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#10126]
I just want to thank you. I rarely thank devs and most of the time I am very critical of about 99% of software I use.

sure there is lots of room to improve and polish msterminal but I am happy that for the first time installing a terminal app I didn't have to waste time customizing the colors: they're just right!

**Comment by zadjii-msft** [comment]
You're welcome! It has been our absolute pleasure to help build this over the last two years, and we're looking forward to many more ☺️
