### ISSUE TITLE
How do I reevaluate "/.profile" for all terminals?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [microsoft/terminal#10120]
### Windows Terminal version (or Windows build number)

10.0.9

### Other Software

asdf

### Steps to reproduce

If I run "pip install flask"

then I am unable to run "flask" afterwards, because flask isn't in environmental variables. Running ". ~/.profile" will only work for the current terminal.

It says [here](https://askubuntu.com/questions/59126/reload-bashs-profile-without-logging-out-and-back-in-again) that in order to make it persistent for all terminals, I have to log in and out, but since I am running wsl, I am not able to log in and out. So what should I do?

### Expected Behavior

.

### Actual Behavior

.

**Comment by zadjii-msft** [comment]
I'm pretty sure that you can just close and reopen the Terminal. A better place for this question might be https://github.com/microsoft/wsl/discussions

**Comment by DHowett** [comment]
That's correct. You don't need to log out/log back in, and it will suffice to either source the newly-updated profile with `. ~/.profile` or relaunch your shells.
