### ISSUE TITLE
"Open JSON file" crashes the app if no settings.json exists

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#10127]
### Windows Terminal version (or Windows build number)

main-3866771

### Steps to reproduce

* Delete `settings.json`
* Build the current main branch
* Click on "Open JSON file" in the settings tab

### Actual Behavior

The app crashes.

**Comment by zadjii-msft** [comment]
ruh roh. 

Wait if there's no `settings.json`, don't we immediately create one on launch?

Either way, we shouldn't crash. That's mental.
