### ISSUE TITLE
Windows terminal shows different colors when running GNU screen on the remote Linux machine

### ISSUE THREAD

**Issue by kushlendramishra** [microsoft/terminal#10129]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

ssh
Screen version 4.05.01 (GNU) 25-Feb-17 (running on Linux)

### Steps to reproduce

1. Connect to a Linux remote machine from Windows Terminal using ssh
2. Run 'ls -la' in any directory. You will get nicely colored output which helps you distinguish files and directories (among other things) as shown below in expected behaviour
3. Now start a GNU screen session in the same directory (screen -S <session_name>).  
4. Run 'ls -la' in the screen session. The output doesn't have the same colors as before (i.e. without screen running) and is less readable.

### Expected Behavior

I should see the colors like below with and without running screen (this is without running screen)
![image](https://user-images.githubusercontent.com/546635/118752391-a34d2a00-b880-11eb-9e98-f70be9e2dfae.png)

### Actual Behavior

When I run screen the nice coloring is gone 
![image](https://user-images.githubusercontent.com/546635/118752497-d394c880-b880-11eb-8638-57e8e8855abb.png)

**Comment by skyline75489** [comment]
This feels like a `screen` configuration issue to me. Try setting `TERM=xterm-256color` for `screen`

**Comment by zadjii-msft** [comment]
Yea, this sounds like you've got the wrong `TERM` in `screen`.

**Comment by DHowett** [comment]
This is going to seem a somewhat silly question, but can you run `which ls` inside and outside of screen?

**Comment by kushlendramishra** [comment]
> This is going to seem a somewhat silly question, but can you run `which ls` inside and outside of screen?

Both give the same output.

Outside of screen:
![image](https://user-images.githubusercontent.com/546635/125413006-f113866e-3abb-4182-a06d-feffba78410b.png)

In screen session:
![image](https://user-images.githubusercontent.com/546635/125413206-dd4d68c3-b4de-44bd-a792-7cf2a18d6e79.png)

**Comment by kushlendramishra** [comment]
The issue seems to pertain to one particular color scheme, 'Solarized Dark'. In my latest installation (version 1.11.3471.0), I don't see this issue with color schemes other than 'Solarized Dark'.
