### ISSUE TITLE
Rendering abnormalities occur when Chinese fonts appear

### ISSUE THREAD

**Issue by romanholidaypancakes** [microsoft/terminal#10128]
### Windows Terminal version (or Windows build number)

1.7.1091.0

### Other Software

windows10 cmd

### Steps to reproduce

![Bg3Lik9vW4](https://user-images.githubusercontent.com/51652878/118744969-e1018100-b887-11eb-9750-b7d2becda128.gif)

### Expected Behavior

The font is rendered normally

### Actual Behavior

The font is not rendered normally

**Comment by zadjii-msft** [comment]
Huh, so if I'm reading this right - the font is changing weight ever so slightly when there's a run of Chinese characters present in the row. That's super weird - @skyline75489 any ideas why this might be happening? Would your work on the FontInfo, text complexity, perhaps help here?

**Comment by DHowett** [comment]
It looks like it's causing a font fallback for the entire run (??????) which should not be possible.

**Comment by skyline75489** [comment]
@notes365 can you provide your Terminal configuration here? I wonder if there’s something special about font in your settings.

**Comment by notes365** [comment]
> 
> 
> @notes365 can you provide your Terminal configuration here? I wonder if there’s something special about font in your settings.

where is the configuration file, my settings are all default

**Comment by notes365** [comment]
i reinstalled  version1.6.10571.0, reported the following error
![image](https://user-images.githubusercontent.com/51652878/119326453-7bacf600-bcb4-11eb-8987-a5f11246b4aa.png)
but everything is ok, may be the reason for the font Cascadia Mono

**Comment by lhecker** [comment]
I'm unable to reproduce this bug...
I've tried to enter some western/latin characters, followed by Chinese, the same way the issue was reported and I couldn't notice any shifts in font appearance.

Maybe this is some ClearType issue? Or some packages are missing on Windows?
It would be interesting whether this issue reproduces on a different machine.
