### ISSUE TITLE
able to choose a non-blinking cursor under profiles - appearance - cursor

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#10125]
# Description of the new feature/enhancement
Other terminal apps allow user to choose if the cursor blinks or not.

# Proposed technical implementation details (optional)
A checkbox under profiles - appearance - cursor 
[x] blinking cursor

aditionally, if i have the cursor not blinking, in some other terminal such as putty or mobaxterm the following escape code instructs putty to set a non-blinking cursor.
attempting to do this on msterminal is ignored 

````
$ cat /usr/local/bin/cursor.sh
echo -n -e '\e[?17;14;224c'
````

**Comment by mailinglists35** [comment]
note this is different than https://github.com/microsoft/terminal/issues/5318

I want the nonblinking all the time, not automatically after some timeout

**Comment by j4james** [comment]
I think you're probably asking for #1379.

**Comment by zadjii-msft** [comment]
Yep, that looks right to me.

/dup #1379

**Comment by mailinglists35** [comment]
thank you. I searched but could not find the original issue. 

workaround 
````
echo -e -n "\e[2 q"
```` 
seems to work meanwhile

**Comment by fweep** [comment]
> ```
> echo -e -n "\e[2 q"
> ```
>   
> seems to work meanwhile

Thanks! Do you know of a way to retain the bar cursor, but turn blinking off?

**Comment by j4james** [comment]
> Thanks! Do you know of a way to retain the bar cursor, but turn blinking off?

It's just a different parameter value for the `DECSCUSR` sequence:
```
echo -e -n "\e[6 q"
```
