### ISSUE TITLE
TAB button crashes process

### ISSUE THREAD

**Issue by h0nus** [microsoft/terminal#10123]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

Windows Powershell

### Steps to reproduce

Open new console, type a letter and try auto complete with TAB

### Expected Behavior

To autocomplete commands

### Actual Behavior

Process exited, maybe an issue with poweshell instead?

![image](https://user-images.githubusercontent.com/23401728/118687504-5e37e200-b805-11eb-89da-6e1d5fdf10d7.png)

**Comment by h0nus** [comment]
Ok, it was an issue with my own installation, fixed with:
`dism /Online /Cleanup-Image /RestoreHealth`
:)

**Comment by vefatica** [comment]
Off-topic, but 3221225477 is a pretty common one (0xC0000005).  Maybe WT could give the hex version of exit codes, perhaps parenthetically.
