### ISSUE TITLE
Exited process, code 3221225786

### ISSUE THREAD

**Issue by FANGOD** [microsoft/terminal#10137]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

terminal 版本: 1.7.1091.0 & v1.7.1033.0

### Steps to reproduce

I suddenly had this problem with the last version, so I upgraded it. It didn't appear at first, but it did appear when I opened ipython3 in a window.

Click the plus button, but not every time
![a602f07edfc019ee8bee919d560a8275](https://user-images.githubusercontent.com/21952721/118920443-07e3b400-b969-11eb-8dce-9e2e3ad60f66.png)

### Expected Behavior

Open a window

### Actual Behavior

Exited process, code 3221225786

**Comment by skyline75489** [comment]
Looks a lot like https://github.com/microsoft/terminal/issues/6790#issuecomment-653939277

**Comment by FANGOD** [comment]
> Looks a lot like [#6790 (comment)](https://github.com/microsoft/terminal/issues/6790#issuecomment-653939277)

Thanks, but not same

**Comment by FANGOD** [comment]
> Looks a lot like [#6790 (comment)](https://github.com/microsoft/terminal/issues/6790#issuecomment-653939277)

Thanks, Set: "closeOnExit": "always" is useful
