### ISSUE TITLE
[DefApp] launching WSL inside DefTerm yields “the parameter is incorrect”

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10134]
As in title

**Comment by miniksa** [comment]
As of today, I've determined this is LxssManager.dll (inside a SvcHost.exe) failing to open a process handle to whatever process it thinks it has determined is the server/host side of the console connection as this is being set up. It says it holds the handle so the process isn't closed and recycled while the WSL stuff is running.

It could be that the fact we're chain-loading the server is messing it up here and we'll need a different strategy or to work with them to refine this code.

**Comment by miniksa** [comment]
This has to do with the owner PID for the client session. 

The existing handoff is letting the inbox `conhost.exe` process end... but it looks like it might have to stick around.
