### ISSUE TITLE
Icons for colour scheme in Command Palette

### ISSUE THREAD

**Issue by DakshKK** [microsoft/terminal#10131]
# Description of the new feature/enhancement
Adding icons to the iterable Select colour scheme option in command palette, or to colour schemes in general.

It could be used to provide a preview of the colour scheme in a small icon/image, since like for me, I had no idea what colours the colour scheme may have, and had to select through all of them, to see which one I liked.

So maybe adding an icon could help the person (a really stupid thought on my part), like for me I re-wrote the command, as a nested command in my `settings.json`, with generated colour palettes icons, since I couldn't find a way to add icons for every command in an iterable command.

The colour schemes could have an icon option, just like profiles which are referenced in iterable commands, or we can add an option to let the `icon` property accept an array which would set the icon for respective commands, in iterable / nested commands.

**Comment by zadjii-msft** [comment]
Would it possibly be better if the color schemes were previewable as you went through the list in the Command Palette?

![image](https://user-images.githubusercontent.com/18356694/118867959-41ed8100-b8a9-11eb-9228-f156c09352b7.png)


(from #9794)

**Comment by DakshKK** [comment]
This would be even better, I did not think of this.

If this is already in the works, that's superb, and if it has been implemented, could someone please guide me around this.

**Comment by mdtauk** [comment]
> This would be even better, I did not think of this.
> 
> If this is already in the works, that's superb, and if it has been implemented, could someone please guide me around this.

Also isn't there a preview being added to the Settings UI?

**Comment by zadjii-msft** [comment]
It'll be in 1.9 ☺️
