### ISSUE TITLE
User should be able to save all the commands emitted

### ISSUE THREAD

**Issue by ChristophePichaud** [microsoft/terminal#1013]
# Summary of the new feature/enhancement
When the user emits commands, either in powershell or cmd, terminal can save them in memory (it's already done for the buffer) and enable the user to save them in a text file using a 'Save Commands in Text' item in a menu or via a button.

# Proposed technical implementation details (optional)
It should not be difficult to make a static classic with a static vector<wstring> and makeing a push_back everytimes and commands is started... I think it's already done for the bufer accessible with upper keyword key... Once the UI item is cliked, open the common dialog "Save As" and make a range for on th vector for writing the strings in a text file.
In theory, its about 20 lines of code... The idea is to properly catch the command after a carriage return or on upper wrapper called OnExecute(const wstring& command) or ireating through the memory buffer... Two possibilities.

**Comment by mdtauk** [comment]
These issues may be relevant #642 #644

**Comment by zadjii-msft** [comment]
Yea, this actually probably isn't solvable by the Terminal at all. It's the responsibility of the _shell_ to execute commands, as well as knowing what a command actually is. From the terminal's perspective, we're just sending keystrokes.

Lets look at an example: editing a file in vim. While working in vim, the user is going to type a lot of keystrokes, including carriage returns, but the large majority of them are actually _not_ commands. How could the terminal differentiate between keystrokes for vim vs keystrokes for cmd?

What about another example, powershell.exe. Say you use the [reverse search ](http://woshub.com/powershell-commands-history/) functionality in powershell.
> If you do not want to browse the entire history of PowerShell commands using up / down arrows, you can search the command history using CTRL+R (reverse search) or CTRL+S (forward search). Press the key combination and start typing part of the command that you want to find in previously executed commands. The text you entered will be found in the command history in any position (unlike search in PowerShell using F8 or Shift+F8, which allows to look for the matches from the beginning of the line only) and a suitable variant will be highlighted.

In the above case, a user typed Ctrl+R, then some subset of the command, then hit enter, but executed a much longer command. How could the terminal possible know what command was actually executed?

This _seems_ like it should be easy, but would actually very quickly devlove into a myriad number of special per-shell cases. This is a feature request that's probably better suited for [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell)

**Comment by ChristophePichaud** [comment]
In readDataCooked.cpp in Terminal\src\host, in the function _handlePostCharInputLoop, there is a way to handle the history in cmd line. The feature **is dedicated to cmd** for the moment.
Are you interested in ?

NTSTATUS COOKED_READ_DATA::_handlePostCharInputLoop(const bool isUnicode, size_t& numBytes, ULONG& controlKeyState) noexcept
{
../..
        if (FoundCR)
        {
            if (_commandHistory)
            {
                // add to command line recall list if we have a history list.
                _commandHistory->Add({ _backupLimit // <- 
                ::MessageBox(NULL, _backupLimit, L"command", MB_OK);
            }
../..
