### ISSUE TITLE
Automatically ^C when switching window

### ISSUE THREAD

**Issue by FANGOD** [microsoft/terminal#10136]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

terminal: 版本: 1.7.1091.0

### Steps to reproduce

Switch Window Only, under the WSL shell, will  `ctrl+c` auto;
under powershell, will see `^C` , and clicking anywhere will also happen;
under cmd, will see two blank lines;
And `ctrl+tab` not show this.

![35f7461b33524168a9a051748a406bae](https://user-images.githubusercontent.com/21952721/118918313-31024580-b965-11eb-9f20-8831b199c346.png)

![01cd1f2ab4473467cae24502e5c4f217](https://user-images.githubusercontent.com/21952721/118918218-01ebd400-b965-11eb-86a1-76fafe3f1b4c.png)

![e2fbc8a6b6484074eec0093be286d5a7](https://user-images.githubusercontent.com/21952721/118918333-365f9000-b965-11eb-9328-590b5c49bcbd.png)

### Expected Behavior

Nothing. 

### Actual Behavior

`Ctrl + C`

**Comment by skyline75489** [comment]
Is there other software you're using? I'm like 98% sure this is not a terminal issue.

**Comment by FANGOD** [comment]
> Is there other software you're using? I'm like 98% sure this is not a terminal issue.

Yes, It works well when there's only terminal.
