### ISSUE TITLE
Overlapping text in Command Palette submenu after deleting ">"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#10140]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

1. Press Ctrl+Shift+P. The Command Palette opens.
2. Scroll to the "Select color scheme…" item and click that. The Command Palette displays a list of color schemes.
3. Press Backspace. The list of color schemes disappears, but the "Select color scheme…" title is still visible.
4. Type `cmd`. Do not press Enter.

### Expected Behavior

It should tell me what will happen if I press Enter.

> Executing command line will invoke the following commands:  
> New tab, commandline: cmd

### Actual Behavior

The dim "Select color scheme…" title overlaps the description of the command line.

![image](https://user-images.githubusercontent.com/46201428/118999488-fadbba80-b992-11eb-9242-c605d9b428fc.png)

**Comment by KalleOlaviNiemitalo** [comment]
Found while trying <https://github.com/microsoft/terminal/issues/7910>.

**Comment by zadjii-msft** [comment]
Ooh, good point. I see two options:
* disable backspacing the `>` in a nested entry.
* Entering commandline mode in a nested entry should pop the nested entries stack. That should get rid of the `"< Select color scheme..."` element.
