### ISSUE TITLE
Running wt from "Run" dialog box doesn't work

### ISSUE THREAD

**Issue by sungvzer** [microsoft/terminal#10149]
### Windows Terminal version (or Windows build number)

10.0.19042.0 1.7.1091.0

### Other Software

Windows run dialog

### Steps to reproduce

- Press Windows+R to open the run dialog
- Type "wt" or "wt.exe"
- Press enter or ctrl+shift+enter, it doesn't launch with either

### Expected Behavior

The application would launch normally when launched from a run dialog.

### Actual Behavior

Open dialog closes, cursor goes to "loading" state, then everything turns back silent.
Running `Get-Command wt | Select-Object -ExpandProperty Definition`, it echoes back `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe`, and pasting this string into the run dialog actually opens the terminal.
That path is already in the system AND user paths.

**Comment by sungvzer** [comment]
Video describing the different behaviors.


https://user-images.githubusercontent.com/52582911/119164086-5756dc80-ba5c-11eb-8a6e-01414312b2db.mp4

**Comment by zadjii-msft** [comment]
This feels like one of the many issues we've had with the app execution alias in the past. @DHowett is usually the best at helping get to the root cause.

**Comment by KaranKad** [comment]
This happened to me when I tried to gain access to WindowsApps folder by changing permission, after that files were all messed up inside and some store apps stopped working properly. Terminal would work when normally launched by clicking the icon but opening from run dialog did not work. My only option was to do a clean install of windows.

**Comment by DHowett** [comment]
Unfortunately, that is one of the "NO FLY ZONES" in Windows -- editing the permissions on that folder. Sorry that happened to you!

**Comment by KaranKad** [comment]
Ah! no worries, I learnt my lesson.

**Comment by zadjii-msft** [comment]
@sungvzer Could you try toggling the "App Execution Alias" for the Terminal, in the Settings App? That might just fix it for you. Otherwise, there's an option in the Settings app to "Repair" an app (Settings > Apps and Features > Terminal > Advanced Options > Repair) which might work.

**Comment by sungvzer** [comment]
Did both things, no success

**Comment by Chaphasilor** [comment]
> @sungvzer Could you try toggling the "App Execution Alias" for the Terminal, in the Settings App? That might just fix it for you.

This should be in the FAQ (if it isn't already)! :D  
I recently had a strange bug where I couldn't run `wt.exe`, even when inside the folder containing the file. Got an error that the "file doesn't exist", when it obviously did. Toggling the App Execution Alias twice fixed it for me.

**Comment by zadjii-msft** [comment]
Sorry for the long turnaround on these. I'm gonna try reaching out to the App Execution Alias team to see if they have more guidance here. If the Terminal can be launched just fine from the Start Menu, but specifically `wt.exe` doesn't work<sup>[1]</sup>, then there's something outside our control that's going wrong that we'll need some help figuring out.

Usually toggling the app execution alias in the Settings app should fix this. Worst case, repairing the app via the settings app should also help. But for some reason those don't seem to help everyone, so we need to figure out what's wrong when those don't work. 

In the meantime, can you share the output of `icacls "C:\Program Files\WindowsApps"` (from an admin shell?)  Filing feedback on "Developer Platform > Desktop Bridge" might also help get some traces to the folks that own this.

![image](https://user-images.githubusercontent.com/18356694/151219053-b5a4b199-9c15-42f6-bedc-8bfa86ca888a.png)


<details>
<summary>Correct WindowsApps permissions</summary>

```
\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                           NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(GR,GE)
                           NT AUTHORITY\SYSTEM:(F)
                           NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                           BUILTIN\Administrators:(CI)(RX)
                           NT AUTHORITY\LOCAL SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\NETWORK SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\RESTRICTED:(OI)(CI)(RX)
                           BUILTIN\Users:(Rc,S,RD,REA,X,RA)
```

</details>

As a matter of cross-linking:
* #9452 is our bucket for "the permissions are wrong on WindowsApps, and that will break `wt.exe`
* #10149, #12249 and #12204 all seem to be the same "none of the above fixed it" issues. VERY good chance I de-dupe these all.

<sup>[1]</sup>: The Win+X menu is also powered by `wt.exe`.

**Comment by zadjii-msft** [comment]
Another debugging question from the AEA team: Do any other App Execution Aliases work from the run dialog or a console window? You can find all of them in the settings app. `spotify.exe`, `snippingtool.exe`, `winget.exe` are all good examples.

**Comment by sungvzer** [comment]
Hi, in the meantime I completely wiped the system, obviously that fixed the problem I had, so unfortunately I have no longer access to the faulty instance.

**Comment by zadjii-msft** [comment]
Welp that's alright. We've clearly got more than enough other reports, we'll use one of those to track this down. Thanks for the follow-up!

**Comment by Zubbbz** [comment]
I also have this issue. It appears that the process starts, and shortly after, closes. I never see it appear on screen. https://youtu.be/uoBcX7uYYTg

**Comment by zadjii-msft** [comment]
@Zubbbz Do you have the "App execution alias" for the Terminal enabled in the Windows Settings app?

From Start menu search, look for "App execution alias", which should take you to the Settings app:
![image](https://user-images.githubusercontent.com/18356694/186685905-7dbe858e-a9a8-4c99-9c28-82ce118d6715.png)
![image](https://user-images.githubusercontent.com/18356694/186686058-8ed70b09-814a-473e-ae1d-e2fbbb6c5d52.png)

If that's enabled, then try running `where wt`. If that can't find it, then either the `wt` App Execution Alias isn't enabled, or your %PATH% is messed up. 

First try toggling the App Execution Alias for WT off then in the Settings app. 

If that doesn't work, then make sure `C:\Users\<your user>\AppData\Local\Microsoft\WindowsApps\` is on your PATH.

**Comment by Zubbbz** [comment]
![image](https://user-images.githubusercontent.com/37497090/220453046-d6116264-9ffa-48cc-befc-16f0473df5d0.png)

oddly enough, since I have windows terminal set as my default terminal, even when the execution alias is off, if i run cmd from the win + r menu, it opens cmd in a windows terminal window

**Comment by Zubbbz** [comment]
I just now turned it off when I took that screenshot, before I had it on, the issue persisted.

**Comment by nwalkewicz** [comment]
@zadjii-msft I've been having the same issue and have too much important data to merit doing a clean install, so I'm working with a faulty wt.exe alias if you need some more diagnostics. Just so we're caught up, I tried toggling the App Execution Alias and performing an app repair via Settings, but neither worked for me. Symptoms for me are identical as the original video posted in this issue. I can't remember, but I might've messed with the permissions a while back, so I wouldn't be surprised if that was the cause. Looking back through the thread a bit, I saw you posted the correct permission for the WindowsApps folder; could you please elaborate on (or send a link that explains) the `:(OI)(CI)(IO)(F)(c,S,E)...` bit? I take it `(F)` means `Full Control`, then `(R|W|X)` mean `Read|Write|Execute` respectively, but I'm not familiar with the others.
