### ISSUE TITLE
Strike-through font attribute not working

### ISSUE THREAD

**Issue by dpifke** [microsoft/terminal#10155]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0)
 of 2021-02-09, modified by Debian
(but applicable to any program)

### Steps to reproduce

Send the xterm sequence for strikethrough.

### Expected Behavior

Text should appear with a line through it.

### Actual Behavior

Text is not rendered with a line through it.

Example from M-x xterm-color-test:

<img width="325" alt="Capture" src="https://user-images.githubusercontent.com/1194574/119241481-dfe48400-bb13-11eb-806e-b32be29132c3.PNG">

(Note that italics, underline, and bold work as expected.)

**Comment by j4james** [comment]
If this is a test that you're running from within Emacs, I suspect it might be Emacs that's doing something weird to produce that result. For example, that "bright + negative" test may appear to be working, but that's not what those attributes typically look like in Windows Terminal.

If you open a bash shell and type `printf "\e[9mThis is only a test\e[m\n"`, does that work for you?

**Comment by dpifke** [comment]
Hmm, works from the commandline.  I thought I had tried that before filing this, but apparently I had the wrong escape sequence.

Closing since this probably isn't a Windows Terminal issue (or at least needs more investigation).

**Comment by dpifke** [comment]
To anyone else finding this issue later: this appears to be an Emacs limitation, which is fixed in 28.1.  See https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e0e147e10389e407531ca81d0063a11a5716d765.
