### ISSUE TITLE
Issue with quotes in parameters

### ISSUE THREAD

**Issue by JonZeta** [microsoft/terminal#10158]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

Execute command:
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"

### Expected Behavior

Accepted

### Actual Behavior

Hi, i just found this thing. Using the same order on powershell is failing on windows terminal > powershell (tab).

![WindowsTerminal_Administrador_Windows_PowerShell_2021-05-23_18-59-14](https://user-images.githubusercontent.com/5842564/119269763-a4bc8080-bbf9-11eb-9014-887c37c45993.jpg)

In both cases i've was as adminstrator

**Comment by zadjii-msft** [comment]
Huh, that's weird. Does it work if you first `Remove-Module PSReadline`? If that doesn't work, does it work if you're running Command Prompt in the admin Terminal window?

**Comment by KalleOlaviNiemitalo** [comment]
Strange that the "Error: Parámetros no válidos" and "Aceptar" messages are yellow. Even stranger that the leading "E" is not.

**Comment by zadjii-msft** [comment]
> Strange that the "Error: Parámetros no válidos" and "Aceptar" messages are yellow. Even stranger that the leading "E" is not.

I think that's the highlighter tool that they've used in that screenshot 😉
