### ISSUE TITLE
Rendering bug inside WSL

### ISSUE THREAD

**Issue by bluretrece** [microsoft/terminal#10159]
### Windows Terminal version (or Windows build number)

Windows Terminal Versión: 1.7.1033.0

### Other Software

Neovim 0.5 nightly (inside WSL), but it happens in the stable version as well 

### Steps to reproduce

1. Open Windows Terminal
2. Open some file in neovim
3. Try to resize Windows Terminal
4. After refreshing it renders everything incorrectly.

### Expected Behavior

![Captura de pantalla 2021-05-23 135424](https://user-images.githubusercontent.com/10943988/119271242-bb011700-bbce-11eb-84b2-0a9fc6a2e6cd.png)

### Actual Behavior

![Captura de pantalla 2021-05-23 133824](https://user-images.githubusercontent.com/10943988/119271251-c3f1e880-bbce-11eb-927f-c857706bffb1.png)

It duplicates a lot of stuf

**Comment by zadjii-msft** [comment]
Huh, I can't get this to repro with a stock install of neovim. Mind sharing your config for neovim? Maybe there's something in there that's causing this.
