### ISSUE TITLE
Paste Hangs Terminal (Right Mouse Click)

### ISSUE THREAD

**Issue by thomashcampbell** [microsoft/terminal#10157]
When copying and pasting I use the right mouse click.  Highlight text, right mouse click.  Then right mouse click to paste.  If this is done too quickly it will hang the Windows  Terminal to the point where it has to be killed

**Comment by skyline75489** [comment]
Are you trying to paste a string with lot of characters? What application are you using as the target of the paste operation? You'll need to give us more information for everyone to better understand the isseue.

**Comment by thomashcampbell** [comment]
I could be one character or 100+.  I've noticed it for a few weeks.  

The only thing I've been able to notice is the speed with which I do it.  If I highlight text, and then right click (copy), right click (paste) then it'll freeze.

I just tried it and couldn't make it do it but the terminal was fresh.  Possibly has to do with the amount of time the terminal is running.

I'll attach more if I can figure out more conditions.

**Comment by devlie** [comment]
I'm reproing this frequently too. It doesn't have to be a long text. Would process dump at hanging state help?

**Comment by DHowett** [comment]
Thanks for the watson ID!

@carlos-zamora this is interesting--

During TermnalPage's PasteFromClipboard handler, it's starting to interact with the Windows.DataTransfer APIs to get the clipboard content. _During_ that handling, UIA is servicing a callback to get the selection information.

I thought that this would be easy, like "paste has a lock, and UIA wants the lock" but it _doesn't_ seem to have the lock.

Let me look at the other threads quick ...

**Comment by DHowett** [comment]
I can't find a single other thread that would be holding the lock. That's not great.

**Comment by devlie** [comment]
Nudging Bot.

**Comment by zadjii-msft** [comment]
@davclark which version of the Terminal?

IIRC we made some changes recently to how we take the lock for accessibility reasons, which might be fixed in 1.12. Not sure thought - it could be something else entirely.

**Comment by thomashcampbell** [comment]
I haven't had this happen in a long time.  Considered it fixed.  I'm on Windows 11 too.

**Comment by davclark** [comment]
I'm on 1.11.2921.0, running Ubuntu-20.04. I guess I'll try the preview and see if my problems go away?

Note that there may be some interaction with neovim (with `set clipboard=unnamedplus`, and a symbolic link to the `win32yank.exe` binary in `/usr/local/bin`). But once the problem starts occurring, it also happens with paste to a command prompt.
