### ISSUE TITLE
[Bug] Icon missing when searching start menu

### ISSUE THREAD

**Issue by buinguyenhoangtho** [microsoft/terminal#10156]
### Windows Terminal version (or Windows build number)

Version: 1.7.1033.0

### Steps to reproduce

I'm reinstall my Windows to latest version (21h1 build 19043.985) and download Windows 10 Terminal from microsoft store

### Expected Behavior

It should be show icon popup on Start menu but result is give me this blank icon

Things i tried: 
- Reset icon.DB
- Download and reinstall Terminal 

### Actual Behavior

![actual-bug](https://i.imgur.com/84xUVKs.png)

**Comment by DHowett** [comment]
Do you happen to have Google Drive installed?

**Comment by zadjii-msft** [comment]
This might be the thread that was mentioned in triage

https://superuser.com/questions/1319157/some-windows-10-uwp-icons-not-displaying-on-search-or-in-settings

**Comment by buinguyenhoangtho** [comment]
I'm sorry for late reponses. But i already fix it by re-installing the latest version of Windows. Thanks you.
