### ISSUE TITLE
Add support for assigning a keyboard shortcut to a given profile.

### ISSUE THREAD

**Issue by zoredache** [microsoft/terminal#10162]
# Description of the new feature/enhancement

Right now profiles get automatically assigned shortcuts like `Cntl+Shift+1`, `Cntl+Shift+2`, `Cntl+Shift+3`. This isn't as useful as it could be. These seem to be based on this order of the profiles in the json settings file.

It seems to me that it would be a lot more useful to allow users to **define a custom keyboard shortcut of their choosing to any profile**.  So I could have `Ctrl+Shift+P` for Powershell, `Ctrl+Shift+C` for CMD, and `Ctrl+Shift+W` for the default WSL instance, and `Ctrl+Shift+D` as a Debian WSL instance, just as an example.

**Comment by zadjii-msft** [comment]
You absolutely can do this today - you can edit the `actions` to bind `newTab` to whatever you want. See: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#new-tab
