### ISSUE TITLE
Dialog Focus

### ISSUE THREAD

**Issue by Rayvenhaus** [microsoft/terminal#10161]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

N/A

### Steps to reproduce

Run Windows Terminal Powershell, then run Powershell script that opens a Windows Dialog for user input.

### Expected Behavior

Opened Windows Dialog to appear in front of Windows Terminal and in Focus to accept user input, allowing the script to accept under input and proceed.

### Actual Behavior

The dialog opens behind Windows Terminal and is hidden, causing the user to think that the script has hung.

**Comment by skyline75489** [comment]
Is this just #2988 / #9888 ?

**Comment by Rayvenhaus** [comment]
It may very well be, but, since we are looking at 18 months and are still experiencing the issue reported in [#2988](https://github.com/microsoft/terminal/issues/2988) / [#9888](https://github.com/microsoft/terminal/issues/9888) and the PowerShell IDE works just fine in this aspect, I find Windows Terminal unusable in this state. If you wish to close it to track this under #2988 that's fine.

**Comment by zadjii-msft** [comment]
Yep, this is definitely /dup #2988
