### ISSUE TITLE
How to set the new terminal as default external terminal for VS Code?

### ISSUE THREAD

**Issue by umerf52** [microsoft/terminal#1016]
How do I launch the new terminal through shortcut such as Ctrl + Shift + C in Visual Studio Code?

**Comment by codefinger23** [comment]
search 'terminal ' and setting the Windows Exec with wls.exe , 'C:\WINDOWS\System32\wsl.exe' for me.

**Comment by umerf52** [comment]
wsl.exe launches Windows Subsytem for Linux for me with Ubuntu (It is the only distro installed).
Should I remove Ubuntu and then try?

**Comment by zadjii-msft** [comment]
I legitimately don't know how to do this - maybe @Tyriar might know?

**Comment by Summon528** [comment]
Maybe try setting it with something like `"%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wtd.exe"`?

**Comment by Tyriar** [comment]
Setting `"terminal.external.windowsExec"` to whatever the new executable is should work.

**Comment by DHowett-MSFT** [comment]
This seems to be answered.
