### ISSUE TITLE
Saving SETTINGS.JSON starts 11 processes

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10163]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations 10.0.19042.985 (2009, 20H2) WindowsTerminal: 1.8.1092.0

### Steps to reproduce

With none of the WSL-related services running, open SETTINGS.JSON vie the settings UI and save it, noting the time.

Observe the processes that were started at that time.

### Expected Behavior

Saving SETTINGS.JSON should not cause new processes to start.

### Actual Behavior

I saved the file at 11:53:21 and got

```
Start  Time            Pid       CPU(s)     WS(M)  Name
--------------------------------------------------------------------------------
05/24  11:53:21.392  10204        0.156      12.4  LxssManager             LxssManager
05/24  11:53:21.439   6980        0.016      10.9  vmcompute               Hyper-V Host Compute Service
05/24  11:53:21.587   5088        0.078      12.9  hns                     Host Network Service
05/24  11:53:21.604   5204        0.078       7.5  nvagent                 Network Virtualization Service
05/24  11:53:21.622   7548        0.031      18.8  SharedAccess            Internet Connection Sharing (ICS)
05/24  11:53:21.666   9552        0.125       6.7  NetSetupSvc             NetSetupSvc
05/24  11:53:21.457   9376        0.125      19.3  vmwp.exe
05/24  11:53:21.478   3556        0.531     418.0  vmmem
05/24  11:53:22.215  10188        0.016       4.8  wslhost.exe
05/24  11:53:22.222   8164        0.000      10.9  conhost.exe
05/24  11:53:22.235   3612        0.016       8.8  dllhost.exe
```

That does not happen when I start WindowsTerminal, possibly because I have "Windows.Terminal.Wsl" among "disabledProfileSources".  My guess is that it need not happen when the settings are reloaded.

**Comment by zadjii-msft** [comment]
Huh. Weird that we'd boot WSL even if it is disabled. We probably shouldn't do that.

**Comment by vefatica** [comment]
Hmmm!  Apparently it's happening when the startingDirectory path in my user-defined Ubuntu profile is validated.  It doesn't happen if I comment out the startingDirectory.  Does it have to do that?

```
"startingDirectory": "\\\\wsl$\\Ubuntu\\home\\vefatica"
```

**Comment by DHowett** [comment]
Fortunately, I think we just removed the code that does that.

**Comment by zadjii-msft** [comment]
Oh good catch! Turns out, _it won't anymore_! See #10045. We're gonna stop doing that in 1.9.

**Comment by vefatica** [comment]
That sounds good.
