### ISSUE TITLE
Nested previewable commands don't "cancel" when you navigate up the nesting stack

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10165]
### Windows Terminal version (or Windows build number)

1.8, 1.9

### Steps to reproduce

1. <kbd>ctrl+shift+p</kbd>
2. "Color scheme..."
3. Arrow down to Tango Light
4. <kbd>Tab</kbd> to select the `<` button
5. <kbd>Enter</kbd> or <kbd>Space</kbd> to select it
6. Escape to exit the palette

### Actual Behavior

The preview scheme is stuck!

**Comment by zadjii-msft** [comment]
okay good catch
