### ISSUE TITLE
Windows Terminal error 0x80070003 when launching `fedoraremix.exe'

### ISSUE THREAD

**Issue by lincolnthomas** [microsoft/terminal#10167]
### Windows Terminal version (or Windows build number)

10.0.19043.985, 1.7.1033.0, Fedora BUILD: 19043

### Steps to reproduce

After the latest Windows Update (which apparently included the Fedora Remix update to 19043), my existing Fedora profile in Windows Terminal stopped working. When you launch it, you get "error 0x80070003 when launching `fedoraremix.exe'"

Here's the settings stanza:
```
  {
                "fontSize": 10,
                "guid": "{d3f31bee-5823-5ed8-8e04-f31ed54f2cd9}",
                "hidden": false,
                "name": "fedoraremix GOOD?",
                "padding": "3",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "f:",
                "tabTitle": "Fedora Good?"
            },
```
After playing around a bit, I got it to work by adding this line to the stanza:

```
                "commandline": "C:\\Users\\Lincoln\\AppData\\Local\\Microsoft\\WindowsApps\\WhitewaterFoundryLtd.Co.FedoraRemixforWSL_kd1vv0z0vy70w\\fedoraremix.exe",
```

Thought you should know. I'm probably not the only one affected.

Is there a better way I should fix or re-add the profile?
Thanks,
Lincoln

### Expected Behavior

See above

### Actual Behavior

See above

**Comment by lincolnthomas** [comment]
(The "Good?" lines of the stanza I added during my experimenting)

**Comment by DHowett** [comment]
_Interesting._ If you go to the "manage app execution aliases" settings and turn fedoraremix.exe off and back on, does it fix itself?

Either the app execution alias has disappeared, or `%LOCALAPPDATA%\Microsoft\WindowsApps` has disappeared from your system `PATH`. ☹️

**Comment by lincolnthomas** [comment]
> If you go to the "manage app execution aliases" settings and turn fedoraremix.exe off and back on, does it fix itself?
Yes! That fixed it. Thanks.

I checked, before doing that: `%LOCALAPPDATA%\Microsoft\WindowsApps` had **_not_** disappeared from my system PATH. There was a `C:\Users\Lincoln\AppData\Local\Microsoft\WindowsApps\fedoraremix.exe` but clicking on it showed an error about no access to the file. Clicking the same file after doing the off/on setting now creates a Fedora window.

**Comment by AustinWise** [comment]
I had this problem too. Toggleing the execution alias also fixed it.

Oddly, this only was a problem when launching using the "wt" command. When launched by searching "terminal" in the start menu it was working fine.

In case it helps:

```
Faulting application name: WindowsTerminal.exe, version: 1.7.2104.13003, time stamp: 0x60761d23
Faulting module name: TerminalApp.dll, version: 1.8.2105.24004, time stamp: 0x60ac2df2
Exception code: 0xc0000005
Fault offset: 0x0000000000019d52
Faulting process id: 0x4f2c
Faulting application start time: 0x01d753711f6db509
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: edf473d4-ff78-4445-8f56-732623a9b4d3
Faulting package full name: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

I'm running Windows 10.0.19043.985
