### ISSUE TITLE
Release notes for 1.9.1445 and 1.8.1444 are currently unavailable

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10178]
Stay tuned.

**Comment by DHowett** [comment]
@jasnell you may want to follow this

**Comment by JohnLGalt** [comment]
How about the GitHub releases themselves?

**Comment by DHowett** [comment]
Same problem, sorry.

**Comment by JohnLGalt** [comment]
Just checking.  Store showed updated apps, so kinda surprised, is all.  I'll wait for the notification.

**Comment by DHowett** [comment]
The release notes are now available on the [releases page](https://github.com/microsoft/terminal/releases). Thanks!
