### ISSUE TITLE
Windows theme change (light <-> dark) not followed (until restart)

### ISSUE THREAD

**Issue by vriesk** [microsoft/terminal#10176]
### Windows Terminal version (or Windows build number)

1.7.1091.0 (on Windows build 19042.985)

### Steps to reproduce

1. Set the **Appearance -> Theme** to "Use Windows theme".
2. Toggle the Windows light/dark theme in Windows **Settings -> Personalization -> Choose your color**.

### Expected Behavior

I expect WT to follow the system theme changes automatically, like other apps (Chrome, VSCode, Slack...).

### Actual Behavior

 Windows Terminal does not follow that immediately.

After restarting WT, the correct new theme is shown.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1230 for more discussion.

/dup #1230
