### ISSUE TITLE
search web for highlighted text feature?

### ISSUE THREAD

**Issue by jamesfranklinnetsec** [microsoft/terminal#10175]
would be nice to highlight some terminal output and right click -> search in browser and it would just send whatever you highlighted to your default web browser.

would also be nice to have a "search stackoverflow" function, I was using google colab and when you get an error in that, it gives you a button that offers to search stackoverflow for you. might be nice to have a thing that detects text in your terminal looking like it might be an error message and offering the user a button to search web for that text. picture attached is what that looks like on colab.

![image](https://user-images.githubusercontent.com/57028307/119467928-5807af80-bd89-11eb-807c-b9c2bdef3df0.png)

so that button sends you here..
![image](https://user-images.githubusercontent.com/57028307/119468439-cb112600-bd89-11eb-940c-310454ad2144.png)

pretty simple little tool, but makes a world of difference.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is a neat idea for an extension, thanks!

**Comment by zadjii-msft** [comment]
accidentally the whole thing:  https://github.com/microsoft/terminal/compare/dev/migrie/fhl/10175-web-search-for-text

**Comment by BenConstable9** [comment]
> * The TODO! in `TerminalPage::_HandleSearchForText` might be tricker - should we join the lines with spaces? How does this interact with wrapped lines? Block selection? Basically, if you have answers there, that's good enough.

Could I just trim spaces from the end of each line and join with a single space? That way all wrapped lines would unwrap and block selection.

**Comment by zadjii-msft** [comment]
> Could I just trim spaces from the end of each line and join with a single space? That way all wrapped lines would unwrap and block selection

That seems like a sensible default to me! Dunno why I never thought of that 😅

**Comment by mpela81** [comment]
Made a PR, let's see how it goes 😄
