### ISSUE TITLE
Display a dialog when the user selects an invalid font

### ISSUE THREAD

**Issue by matt2405warner** [microsoft/terminal#1017]
# Summary of the new feature/enhancement

Currently when changing the 'fontFace' to a font that doesn't exist the font size just gets so small (~0.5 font size) that you can't read the text.

# Proposed technical implementation details (optional)

It would be nice if the terminal informed the user that the font is not valid - Maybe a pop-up/modal?

**Comment by metathinker** [comment]
I also see an earlier report (#550) that Terminal would actually crash when a profile referred to a nonexistent font name. Is that not happening anymore? Perhaps that problem was partially fixed, resulting in what you see.

**Comment by matt2405warner** [comment]
I haven't had it crash on me yet when I change the font to an invalid one. It just makes the font extremely small.

**Comment by zadjii-msft** [comment]
Well this is definitely relevant to #610, @miniksa might be interested in knowing that. I was certainly under the impression we'd crash when the font wasn't found.

**Comment by miniksa** [comment]
I mean, literally anyone who isn't me can go F5 the thing in Visual Studio setting a breakpoint in `dxrenderer.cpp` where it hands your font preference into DirectWrite's layout and see what it comes back with to reason out why this is. I think it's `GetProposedFont` method.

But if no one else does that, I'll get to this eventually.

**Comment by metathinker** [comment]
Well, for what it's worth, I can't reproduce this problem. I gave a profile a nonexistent font name and Terminal crashed as per #550 when creating a tab with that profile; it didn't show a tab with tiny text as you report here.

**Comment by matt2405warner** [comment]
@metathinker this occurred when I had a terminal tab already open when I was editing the profile. @zadjii-msft are you at least informing the user why the terminal crashed?

**Comment by zadjii-msft** [comment]
@matt2405warner considering the terminal was hard crashing, I don't think the app had a chance to catch the exception that triggered the crash. Now that #903 is complete, we certainly can add another message here

**Comment by kmoberg** [comment]
> I also see an earlier report (#550) that Terminal would actually crash when a profile referred to a nonexistent font name. Is that not happening anymore? Perhaps that problem was partially fixed, resulting in what you see.

I've tried changing to a non-existent font today, and it hard-crashes the entire application when I do.

**Comment by miniksa** [comment]
@kmoberg, I fixed #550 19 hours ago. It'll be in the next release or you can build from master to get the fix.

However, the way I fixed it just resulted in the DX renderer trying things until it can find a font. If we're to add a dialog too, we probably need to detect that the requested font doesn't match the returned font and display.

I can take the issue from here.

**Comment by offero** [comment]
How do you find the string that represents the font variant you want?
