### ISSUE TITLE
Z-Index Problem with dropdown menu in settings

### ISSUE THREAD

**Issue by simonmueck** [microsoft/terminal#10177]
When choosing the standard editor profile for new tabs the appearing dropdown menu is floating over the window borders when scrolling. 
https://user-images.githubusercontent.com/71900957/119511736-ff2d1c80-bd72-11eb-9240-8b1c349dc50b.mp4

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
