### ISSUE TITLE
Remove "feedback" from the dropdown, and replace with "Command Palette"

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#10171]
* we know for a fact that no one's filed any issues using the feedback button
* We know that the command palette is terribly undiscoverable
* the command palette is also a great entry to discover _basically every other command we have_

so let's yank feedback, and replace with the cmdpal.

In the future, the new tab dropdown will be defaulted to `[allProfiles, separator, toggleCommandPalette()]` (#1571), so someone can remove it if they want.

Notes: might need to manually toss focus to the cmdpal - let's be careful here

**Comment by KnapSac** [comment]
I'd like to give this a shot, am I correct that this would need to be changed:
https://github.com/microsoft/terminal/blob/27582a9186c39ea9f5caf070e08fd80e50e1d587/src/cascadia/TerminalApp/TerminalPage.cpp#L686-L696

**Comment by zadjii-msft** [comment]
@KnapSac That's exactly the spot! I believe the team consensus was to use the "LightningBolt" icon, which is `\xE945 `

**Comment by KnapSac** [comment]
I have a couple uni assignments to finish up, but I expect to have a PR ready by early next week.

In the settings UI, the "Actions" page has a keyboard icon. Wouldn't it make more sense to keep these 2 icons the same? Since the command palette provides access to those actions?

**Comment by zadjii-msft** [comment]
That's a good observation!

We're actually only _temporarily_ using the keyboard icon for the actions page. I think in the long run, we're actually planning on moving that to the lightning bolt as well. Right now the actions page only really works for actions that are bound to the keyboard, hence the keyboard icon. We have plans to update that page in the future to support configuring _all_ actions, including everything in the command palette. This ties into some other plans we have for having actions accessible from the keyboard, the command palette, the new tab dropdown, the context menu... basically a ton of places.

I'll also tag in @cinnamon-msft, who can override that decision if they like.

**Comment by Chips1234** [comment]
@zadjii-msft If we're going to get rid of the "feedback" menu item, should we then add a "feedback" link in the "About" window that needs to feedback hub or "Visit our GitHub repository" that leads here?
