### ISSUE TITLE
Bug Report - Application error : (0Xc0000142) Help-Wanted

### ISSUE THREAD

**Issue by CaptainMorgans** [microsoft/terminal#1018]
# Environment
Windows 10 Home 

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):
Microsoft Windows [Version 10.0.18362.145]
(c) 2019 Microsoft Corporation. All rights reserved.

Any other software?
```

# Steps to reproduce

# Expected behavior
Expected to see the terminal open into the Linux bash. Trying to open the cmd.exe produces the same error.

# Actual behavior
Terminal window opens with a message cmd.exe - Application Error - "The application was unable to start correctly (0xc0000142). Click OK to close the application"

# Help-Wanted

**Comment by zadjii-msft** [comment]
Are you launching the built-in cmd.exe/powershell.exe/wsl.exe/conhost.exe, or are you trying to launch OpenConsole.exe/Windows Terminal built from source in this repo?

What architecture is your machine, and if you're building from source, what platform are toy targeting?

**Comment by CaptainMorgans** [comment]
Hi,

What architecture is your machine X64 , and if you're building from source Yes from the GitHub repo, what platform are toy targeting wsl.exe?
I can open wsl.exe , cmd.exe, and even OpenConsole.exe , which results in a single terminal window which is not the new terminal application in appearance.

See the screenshot below. The second screenshot shows the error I am getting with the dev build terminal.


[cid:image001.png@01D516F1.044640A0]


[cid:image002.png@01D516F1.10249520]

Kind Regards,
Stephen

**Comment by zadjii-msft** [comment]
Hey for the record, your screenshots didn't work through email replying to github. You might have to respond on github for them to work.

When I ask about what platform you're targeting, I mean what's the Solution Platform set to in VS?
![image](https://user-images.githubusercontent.com/18356694/58707428-890ba000-837a-11e9-92b0-4dc478612ab3.png)

Here it's set to x64.

**Comment by CaptainMorgans** [comment]
This is the event viewer log created when I try to open the application. 

The application was working 100%, but after a Windows update it broke.


Log Name:      Application
Source:        Application Error
Date:          2019/06/09 12:31:17 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Dell2016
Description:
Faulting application name: WindowsTerminal.exe, version: 0.0.0.0, time stamp: 0x5ce9ca15
Faulting module name: Microsoft.UI.Xaml.Markup.dll, version: 0.0.0.0, time stamp: 0x5ce9c93c
Exception code: 0xc0000005
Fault offset: 0x000000000002decf
Faulting process id: 0x7748
Faulting application start time: 0x01d51eae6f1e2d27
Faulting application path: C:\Terminal\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\WindowsTerminal.exe
Faulting module path: C:\Terminal\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\Microsoft.UI.Xaml.Markup.dll
Report Id: 64717541-ed38-4710-a1c5-774f2b55f243
Faulting package full name: WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-06-09T10:31:17.983412600Z" />
    <EventRecordID>27114</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Dell2016</Computer>
    <Security />
  </System>
  <EventData>
    <Data>WindowsTerminal.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5ce9ca15</Data>
    <Data>Microsoft.UI.Xaml.Markup.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>5ce9c93c</Data>
    <Data>c0000005</Data>
    <Data>000000000002decf</Data>
    <Data>7748</Data>
    <Data>01d51eae6f1e2d27</Data>
    <Data>C:\Terminal\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\WindowsTerminal.exe</Data>
    <Data>C:\Terminal\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\Microsoft.UI.Xaml.Markup.dll</Data>
    <Data>64717541-ed38-4710-a1c5-774f2b55f243</Data>
    <Data>WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by CaptainMorgans** [comment]
> Hey for the record, your screenshots didn't work through email replying to github. You might have to respond on github for them to work.
> 
> When I ask about what platform you're targeting, I mean what's the Solution Platform set to in VS?
> ![image](https://user-images.githubusercontent.com/18356694/58707428-890ba000-837a-11e9-92b0-4dc478612ab3.png)
> 
> Here it's set to x64.

I did compile it in x64 architecture not ARM64.
