### ISSUE TITLE
Configurable Quake Mode window width, to accommodate ultra-wide resolutions

### ISSUE THREAD

**Issue by riverar** [microsoft/terminal#10180]
# Summary

Quake Mode (https://github.com/microsoft/terminal/pull/9274) provides, well, a Quake-like console that appears on use of a global hotkey. This console window opens at the maximum width of the active workspace, however, creating usability issues on ultra-wide displays.

Consider a user sitting at the center of this screenshot:
![image](https://user-images.githubusercontent.com/475132/119551409-78fedf00-bd4e-11eb-8fa9-0e41a38c1c61.png)

# Proposal

Allow for a user-configurable width, preferably in **relative** sizing units (to accommodate resolution changes).

Example:
```jsonc
{
  // ...
  "quakeMode.window.width": "50%"
}
```

**Comment by zadjii-msft** [comment]
So, IMO quake mode is more of an "easter egg" mode than anything else. If you want _exactly the behavior of quake mode_, then bind `quakeMode`. If you want some other behavior, then feel free to bind something else. I personally just use

```json
{ "keys": "win+`", "command": { "action": "globalSummon", "monitor": "any" } },
```

which just activates the window where it is, without all the other "quake mode" hijinks. So you could bind that, and the window would still obey the normal `initialRows`, `initialCols`, etc. Does that seem like a reasonable solution?

(we've also got #9992 tracking "allow users to set settings per-window name", which would let users change the `initialPosition`, `initialRows`, etc for the `_quake` window).

**Comment by DHowett** [comment]
_LOL_. Yeah, that makes sense.

@zadjii-msft, perhaps we can roll this into "per-window launch properties" where a launch size/initial width for `_quake` specifies magic?

**Comment by riverar** [comment]
This mode was communicated as such at Build 2021:

> Quake Mode allows users to quickly open a new terminal window from anywhere in Windows with a simple keyboard shortcut.

I wasn't aware of the global summon action so I'll try that out. I'll be looking for positioning configuration of that window as well.

If the team consensus is that _Quake Mode_ was designed to be a gimmick and not unlike how it was communicated at Build 2021, then feel free to close this issue.

**Comment by zadjii-msft** [comment]
Meh, yea, that's what we get when we try distilling a big release like this into two sentences 😆 

There's actually quite a lot of configuration possible - see [the docs for `globalSummon`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands)

**Comment by DHowett** [comment]
> If the team consensus is that _Quake Mode_ was designed to be a gimmick and not a useful feature.

This is not the team's consensus. An "easter egg" that is a specialization of a much more featureful _feature_ is not "a gimmick" that was designed to be "not a useful feature."

Please assume positive intent when you're on this repository. :smile:

**Comment by riverar** [comment]
Thanks @DHowett no negative vibes intended. But I completely disagree with your characterization of Quake Mode as an _easter egg_. It's not communicated that way via official Microsoft comms channels.

@zadjii-msft's workaround is great, so no changes needed. Closing issue.

**Comment by xinxilas** [comment]
> Thanks @DHowett no negative vibes intended. But I completely disagree with your characterization of Quake Mode as an _easter egg_. It's not communicated that way via official Microsoft comms channels. And "easter egg" implies "no support", hence my comment. Happy to be wrong there.
> 
> Regardless, @zadjii-msft's workaround is great, so no changes needed! Closing issue.

Sorry but how did you mannaged to adapt quake mode on ultra wide using the globalSummon directives ? I would like to open the quake mode at the middle of a really big screen with 50% width

**Comment by riverar** [comment]
@xinxilas I didn't. Wasn't worth the trouble.

**Comment by xinxilas** [comment]
Lol, ill try to use some custom globalsummon with without quake mode then 😂
