### ISSUE TITLE
Crash opening SUI on 1.9.1445.0

### ISSUE THREAD

**Issue by GTechnology-biz** [microsoft/terminal#10186]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

Upgrade GitHub version
Microsoft.WindowsTerminalPreview_1.8.1032.0_8wekyb3d8bbwe.msixbundle
with
Microsoft.WindowsTerminalPreview_1.9.1445.0_8wekyb3d8bbwe.msixbundle

Open Windows Terminal
Click the drop down icon
Click settings

### Expected Behavior

SUI Opens

### Actual Behavior

2 second delay
Terminal Closes with no message

**Comment by OscarL** [comment]
Just here to report that I'm too experiencing the same crash when attempting to open the Settings (by the Drop-down->Settings menu, or by hitting Ctrl+,).

Was working ok before upgrading to 1.9.1445.0. Was Using 1.7.572.0 before.

I don't have "Feedback Hub" installed so I won't be able to provide feedback that way.

**Comment by GTechnology-biz** [comment]
I am on a company managed system and do not have the Feedback hub.

**Comment by lminer** [comment]
I have the same issue

**Comment by bw1faeh0** [comment]
Same issue here. Feedback Hub is blocked (company managed system)...

**Comment by mingsxs** [comment]
I'm having the same issue, and I submit the Feedback Hub as requested.

**Comment by rudibaden** [comment]
As a temporary work around, editing C:\Users\%username%\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState works for me.

**Comment by zadjii-msft** [comment]
Hey when someone is able to capture this with the feedback hub, can you please make sure to share the link here?

![image](https://user-images.githubusercontent.com/18356694/119643017-e8251380-bde0-11eb-843c-420d3bf74beb.png)


It's actually neigh impossible for us to track down this specific issue without the link 😕

**Comment by andrefecto** [comment]
I am also having this issue (and can't use feedback hub.) but this shows in event viewer if it helps.

```
Faulting application name: WindowsTerminal.exe, version: 1.9.2105.24005, time stamp: 0x60ac3929
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.1474, time stamp: 0xce787f95
Exception code: 0xc000027b
Fault offset: 0x0000000000713790
Faulting process id: 0x3b0c
Faulting application start time: 0x01d7524bf517eed6
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 41362203-b075-4a30-8305-96b99b1ca619
Faulting package full name: Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Version: 1.9.1445.0 on Windows 10 Enterprise 1909

**Comment by DHowett** [comment]
Curious how all of the users with this issue are folks who don't have feedback hub. I wonder if there's something causative here?

Unfortunately, it turns out that WER reports without a "bucket ID" are not useful for diagnosing crashes 😦

**Comment by DHowett** [comment]
> I'm having the same issue, and I submit the Feedback Hub as requested.

We'll need you to actually share that feedback hub link with us using the instructions above, otherwise we cannot find it. I'm sorry.

**Comment by andrefecto** [comment]
> 
> 
> Curious how all of the users with this issue are folks who don't have feedback hub. I wonder if there's something causative here?
> 
> Unfortunately, it turns out that WER reports without a "bucket ID" are not useful for diagnosing crashes 😦

Are there physical log files, or a debug mode that could help? Or is feedback hub the only way?

**Comment by fritzy** [comment]
Windows 10 Enterprise 1909, Windows Terminal 1.9 Preview

Same crash. It sounds like there could be correlation with Enterprise Managed Windows 10.

Deleting/moving the settings.json did indeed reset my settings, but the settings UI still crashes the app.

**Comment by zadjii-msft** [comment]
I wonder if getting the build number to check if defterm is available fails? Clearly, if these are all 1909 machines, defterm isn't available, so we're probably not even hitting the registry lookup, but that's the code path that sticks out to me.

**Comment by sliepie** [comment]
Stacktrace of opening Settings UI in release build, on Windows 1909
![image](https://user-images.githubusercontent.com/2635154/119713722-4fcf7300-be62-11eb-87e0-8b5ffcfbf6fe.png)

**Comment by miniksa** [comment]
Is this #10106?

**Comment by mingsxs** [comment]
> > I'm having the same issue, and I submit the Feedback Hub as requested.
> 
> We'll need you to actually share that feedback hub link with us using the instructions above, otherwise we cannot find it. I'm sorry.

Hi Sorry, I didn't use Feedback Hub before, here is the link generated: <https://aka.ms/AAcoplu>

**Comment by mingsxs** [comment]
> > > I'm having the same issue, and I submit the Feedback Hub as requested.
> > 
> > 
> > We'll need you to actually share that feedback hub link with us using the instructions above, otherwise we cannot find it. I'm sorry.
> 
> Hi Sorry, I didn't use Feedback Hub before, here is the link generated: https://aka.ms/AAcoplu

For other requests, please let me know about it, I am in China timezone so the reply may be delayed.

**Comment by sliepie** [comment]
> Is this #10106?

Yep, seems the same when comparing the stack traces

**Comment by zadjii-msft** [comment]
Okay yep, this is definitely the same root cause as  #10106

/dup #10106

<hr>

> After a default terminal is set, how does that appear in the the settings.json file?

It's actually not in the `settings.json` at all - it's stored in `HKCU\Console\%%Startup`

```
[HKEY_CURRENT_USER\Console\%%Startup]
"DelegationTerminal"="{00000000-0000-0000-0000-000000000000}"
"DelegationConsole"="{00000000-0000-0000-0000-000000000000}"
```

But, with actual GUIDs - `{0}` will default back to conhost
