### ISSUE TITLE
Wrong size on Quake mode with hetero sized screens

### ISSUE THREAD

**Issue by kazuf3** [microsoft/terminal#10182]
### Windows Terminal version (or Windows build number)

10.0.19042.0 and 1.9.1445.0

### Steps to reproduce

- Activate Quake on big screen (4K) with mod4+`
- Hide it
- Activate Quake on small screen (FHD) with mod4+`

### Actual Behavior

Get this (instead of covering upper half of the screen, it only gives the corner part of terminal):
![image](https://user-images.githubusercontent.com/34043588/119569182-41e6f880-bd63-11eb-9134-9a22d1844b4d.png)

**Comment by kkoziarski** [comment]
There is also incorrect windows size when you move the quake mode window to second monitor using `Win+Shift+Right`. When you move it to a smaller monitor, the right side is cut off and impossible to scroll right.
![image](https://user-images.githubusercontent.com/6848262/119615218-727c7000-bdff-11eb-821a-1d299dd1de32.png)
