### ISSUE TITLE
Windows terminal as default terminal application breaks WSL2 launch when WSL2 debugConsole is enabled

### ISSUE THREAD

**Issue by reynoldsa** [microsoft/terminal#10194]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

1. WSL2
2. Windows 10 build 21387 or later, for the WSL2 `debugConsole` functionality

### Steps to reproduce

1. Install WSL2 + a distro and create the `%USERPROFILE%\.wslconfig` file with the following contents:

```
[wsl2]
debugConsole=true
```
2. Make sure that Terminal v1.9.1445.0 is installed, and that it's a) set as the default terminal b) has a profile for your WSL2 distro
3. Attempt to launch terminal in the WSL2 profile, either via the jump list or terminal's own profile menu

### Expected Behavior

1. WSL2 profile opens normally

### Actual Behavior

1. Windows terminal locks up and goes into a "not responding" state, with high system CPU usage from VM compute service
2. After the windows terminal process is killed, a legacy console window spawns with the expected WSL2 VM debug output
3. After the VM boots, another Windows terminal spawns without any tabs open, lacking any WSL profile, and doesn't respond to window close events
4. When the terminal instance from 3 is killed, and another one is spawned, this one will work normally

**Comment by rescenic** [comment]
This sucks.

**Comment by DHowett** [comment]
I see that you've posted on multiple "default terminal" issues. Thanks for adding your valuable insight. However: if you have nothing further to add, I'll kindly request that you just click Subscribe and go on with your life.

**Comment by miniksa** [comment]
My proposed fix idea for #10134 fixes this too.
