### ISSUE TITLE
WT preview crashed when opening settings UI

### ISSUE THREAD

**Issue by smezger** [microsoft/terminal#10198]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

1. Select Settings menu item from drop down menu or using the keyboard shortcut
2.  WT crashes
This behavior is 100% reproducible here did not occur with the v1.8.1092.0 (Scoop Compatibility)

### Actual Behavior

WT crashes, event log shows these details (sorry German)
```
Name der fehlerhaften Anwendung: WindowsTerminal.exe, Version: 1.9.2105.24005, Zeitstempel: 0x60ac3929
Name des fehlerhaften Moduls: Windows.UI.Xaml.dll, Version: 10.0.18362.1474, Zeitstempel: 0xce787f95
Ausnahmecode: 0xc000027b
Fehleroffset: 0x0000000000713790
ID des fehlerhaften Prozesses: 0x4ed8
Startzeit der fehlerhaften Anwendung: 0x01d751fdbc7684e6
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\Windows.UI.Xaml.dll
Berichtskennung: 1dd80988-e09a-4add-a034-d24e61b1580f
Vollständiger Name des fehlerhaften Pakets: Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App`
```

**Comment by skyline75489** [comment]
Thanks for the feedback! This seems serious as there's a lot of similar reports in #10186

**Comment by skyline75489** [comment]
Can you use Feedback Hub as described in https://github.com/microsoft/terminal/issues/10186#issuecomment-848291550 ?

**Comment by zadjii-msft** [comment]
Yea, I'm calling this a /dupe #10186
