### ISSUE TITLE
"Async" SSH typing experience like VSCode

### ISSUE THREAD

**Issue by JasonWei512** [microsoft/terminal#10195]
# Description of the new feature/enhancement

https://user-images.githubusercontent.com/16899918/119603537-fba39f00-be1f-11eb-831c-8189803b33b3.mp4

When you type something in VSCode's SSH terminal, it will be displayed in gray color immediately regardless of network latency. And when you get the response from the remote machine, those texts will turn white.
This feature improves user experience, especially under high network latency.

**Comment by skyline75489** [comment]
Thanks for the feedback! This is being tracked at #8178 .
