### ISSUE TITLE
Use English to search in command palette in other locales.

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#10196]
This is the obstacle that stops me from daily driving command palette. The idea is simple and VSCode has the support for it since 2016.

See https://github.com/Microsoft/vscode/issues/4679 and https://github.com/Microsoft/vscode/issues/4679#issuecomment-214741754

Note: In VSCode, You can use *both* the system language & English to search in command palette and it works just as expected.

**Comment by zadjii-msft** [comment]
This is actually already being tracked - see /dup #7039
