### ISSUE TITLE
Support to show tab bar in quake mode

### ISSUE THREAD

**Issue by 0xcaffebabe** [microsoft/terminal#10192]
# Description of the new feature/enhancement

In current preview version(1.9.1445), wt has no tab bar in quake mode:

![image](https://user-images.githubusercontent.com/34188127/119587160-ab691480-be00-11eb-8437-22fcd86e35b3.png)

It is inconvenient in multiple tab scenes. I only can use key binding(ctrl + tab or ctrl + shift + t) to change tab or create new tab. And how much tabs are opened is unclear in quake mode.

**Comment by skyline75489** [comment]
Thanks for the feedback! This is a known limitation atm. See #9992 for details of future work.

**Comment by zadjii-msft** [comment]
You can always exit focus mode, with <kbd>strl+shift+p</kbd>, "Toggle Focus Mode" (or whatever that's localized to). Otherwise yea, I'm gonna call this /dup #9992
