### ISSUE TITLE
Ability to store login details for SSH/telnet connections

### ISSUE THREAD

**Issue by maninderdeol67** [microsoft/terminal#10193]
# Description of the new feature/enhancement

As much as I love the new Windows Terminal and all the fancy features that it offers, not being able to store the login details for my SSH or Telnet connections is kind of a deal-breaker for me.

As a Network guy, I roughly have 200+ devices that I connect to over SSH or Telnet, and some of them I access multiple times in a day so, having the ability to store the login details securely is crucial.

I have also tried setting up the SSH keys for authentication but, it becomes overwhelming very quickly as there are always new devices getting added. Sometimes, the device on the other end is not capable of storing SSH keys.

So, adding the ability to store username and password will make Windows Terminal a suitable replacement for something like M-Remote or Secure CRT.

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
As much I love the SSH features in SecureCRT, XShells, etc, I wouldn't really ask for similar features in Windows Terminal, since Terminal is not a professional SSH client.  

See https://github.com/microsoft/terminal/issues/9486#issuecomment-798965251

**Comment by zadjii-msft** [comment]
Yea, the party line is that the Terminal is a great _terminal emulator_. That's what we're trying to be first and foremost - not a ssh client. This is a really good idea for someone to write an extension in the future (when those are supported), but it's not something we'll be adding ourselves. Thanks!
