### ISSUE TITLE
Make Quake mode run at startup?

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/terminal#10206]
Maybe I'm misunderstanding the options and this already exists somewhere?

**Comment by WSLUser** [comment]
You could probably create a profile using settings.json to automatically start in quake mode but not sure it's intended to work that way yet. You could try using the commandline parameter to see if it'll summon a quake window for your default profile.

**Comment by DHowett** [comment]
As a silly workaround until we have a better solution: make a shortcut that runs `wt -w _quake` and put it in your Startup folder. We don't have a good answer otherwise.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9996 for more discussion.

/dup #9996
