### ISSUE TITLE
[Suggestion] Auto set the title bar's length

### ISSUE THREAD

**Issue by wbsdty331** [microsoft/terminal#1020]
![image](https://user-images.githubusercontent.com/4280572/58380112-a7227a80-7fdf-11e9-831b-0c7604144e84.png)

The title bar is too long and It only have a little area to drag the Window (The red box).

**Comment by oising** [comment]
@wbsdty331 We're going to make the entire tab bar draggable, so this issue will be covered. We have another issue covering this, so I'll close this one. Thanks for your feedback.
