### ISSUE TITLE
I need to get back to the original setup settings to change those

### ISSUE THREAD

**Issue by geercom** [microsoft/terminal#10207]
![NO DOWN ARROW](https://user-images.githubusercontent.com/84856506/119686915-c6458400-be14-11eb-8baf-91defe1391e3.png)
I errantly set the settings so Windows Terminal opens full screen with no access to the settings or menu (upper-left in the open application). I don't see and can't get to any tabs or arrows. I can't change it so that I can. I can't uninstall it to do a doover. I can't find and edit the .JSON file. Any clueful Google search results suggest methods for redoing the settings that I can't get to or find. I need to go into the broad selection of Windows Terminal settings rather than properties. Is there a > path, or are there instructions that address my instance?

**Comment by vefatica** [comment]
Alt-Enter should take it out of full-screen mode.

**Comment by geercom** [comment]
Yes but it does not make the down arrow visible, so I can't get to the settings.

**Comment by DHowett** [comment]
You can also open the settings with <kbd>Ctrl+Comma</kbd>, open the command palette with <kbd>Ctrl+Shift+P</kbd> and type in "focus" or "full", or open `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_somethingsomething\LocalState\settings.json` in your favorite text editor.

You can also open the dropdown menu when it's hidden with <kbd>Ctrl+Shift+Space</kbd>.

**Comment by DHowett** [comment]
This looks like "maximized focus" mode -- so if you toggle "focus mode" using the command palette it will probably come back.

**Comment by geercom** [comment]
Thank you! Yes, could you type in the commands I need to do it? I don't know what/where is the command palette, new user of Windows Terminal, an infrequent user of PowerShell, just a little more experienced with DOS command prompt.

**Comment by geercom** [comment]
> You can also open the settings with Ctrl+Comma, open the command palette with Ctrl+Shift+P and type in "focus" or "full," or open `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_somethingsomething\LocalState\settings.json` in your favorite text editor.
> 
> You can also open the dropdown menu when it's hidden with Ctrl+Shift+Space.

This saved the day. Thank you, @DHowett .

**Comment by DHowett** [comment]
Sorry about that! It does, in retrospect, seem dangerous to offer a mode that is difficult to get out of as the automatic startup mode. 😁

**Comment by vefatica** [comment]
RE Alt+Enter ...

`Yes but it does not make the down arrow visible, so I can't get to the settings.`

I guess that means you're also in focus mode.  Shift+F11 should toggle focus mode.
