### ISSUE TITLE
Build is extremely slow

### ISSUE THREAD

**Issue by gabrielconl** [microsoft/terminal#10205]
### Windows Terminal version (or Windows build number)

10.0.19043.985

### Other Software

Microsoft Visual Studio Community 2019
Version 16.9.6

### Steps to reproduce

I followed the build steps from README.md.

### Expected Behavior

A reasonable build time

### Actual Behavior

Build takes about one hour and generates around 15GB of files. My computer only has a 5400rpm HDD - is that the issue? Is there a way to reduce the build time without upgrading to an SSD?

**Comment by zadjii-msft** [comment]
Oh no, that's very very expected. C++WinRT & XAML together result in pretty hefty pch.pch files (often 1GB+). It's something I'm vary passionate about trying to help fix, but we might be out of luck until C++20 modules are finished. 

I don't really have anything else to share at this time, but trust me when I say that this is my personal war, and I'm not gonna rest until this experience gets better
