### ISSUE TITLE
Windows Terminal as default breaks Visual Studio 2019 console based applications 

### ISSUE THREAD

**Issue by BenyErnest** [microsoft/terminal#10204]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

Set windows terminal preview as default terminal application.

### Expected Behavior

Starting Visual Studio 2019 console-based projects should show console or windows terminal.

### Actual Behavior

Starting Visual Studio 2019 console-based projects do not show console or windows terminal.

**Comment by rescenic** [comment]
Does anybody know how to revert it back to conhost as default terminal application?

**Comment by DHowett** [comment]
Did you perchance check the settings page where you opted into Terminal being the default terminal application?

**Comment by miniksa** [comment]
> ### Expected Behavior
> Starting Visual Studio 2019 console-based projects should show console or windows terminal.
> 
> ### Actual Behavior
> Starting Visual Studio 2019 console-based projects do not show console or windows terminal.

There are a lot of project types in Visual Studio 2019 that could be categorized as "console-type" projects.

@BenyErnest could you please provide additional detail or screenshots as to which project type you're using so I could narrow down the activation flow?

A sample solution could be useful too. Thanks!

**Comment by miniksa** [comment]
I did briefly look at this and I'm having a perfectly OK time with Release/x64 with the Hello World that comes out of the default VS2019 C++ Console App solution.

F5 --> loads in a console host through VS's console debug wrapper
Ctrl+F5 --> loads in a console host through VS's console debug wrapper
Double clicking from explorer --> Terminal loads and it runs then it exits/closes immediately as this Hello World app exits quickly and default Terminal behavior is close tab on exit; close app when no tabs are left.
Double clicking from explorer with Terminal already open --> tab flickers into existence then quickly out as the app runs and exits itself very fast.

**Comment by BenyErnest** [comment]
> > ### Expected Behavior
> > Starting Visual Studio 2019 console-based projects should show console or windows terminal.
> > ### Actual Behavior
> > Starting Visual Studio 2019 console-based projects do not show console or windows terminal.
> 
> There are a lot of project types in Visual Studio 2019 that could be categorized as "console-type" projects.
> 
> @BenyErnest could you please provide additional detail or screenshots as to which project type you're using so I could narrow down the activation flow?
> 
> A sample solution could be useful too. Thanks!

After I updated my Windows 10 insider version is working now. Thanks for the help.
