### ISSUE TITLE
Bug Report: Reaction to Keyboard input is anomalous 

### ISSUE THREAD

**Issue by MelulekiDube** [microsoft/terminal#1021]
# Environment

```none
Windows build number: [Version 10.0.18898.1000]
Windows Terminal version (if applicable): 0.0.1.0
```

# Steps to reproduce
1. Start terminal
1. ssh to a remote host
1. disconnect from the internet while connected to the network
1. Try to type something on the terminal and observe

# Expected behavior
The keyboard input should be working properly

# Actual behavior
Weird reaction to input. Although on enter the write input is processed.

![issue](https://user-images.githubusercontent.com/24409733/58383529-5bb89e00-7fd8-11e9-9151-7fb4ccb1a3e1.gif)
Also if an editor like vim was open as can be seen the screen is not cleared on loss of connection. 
It will be nice to have the normal error telling you of a timeout error and the terminal goes back to working as it was working before.

**Comment by MelulekiDube** [comment]
This is with ssh.exe Hadn't checked with wsl.

**Comment by zadjii-msft** [comment]
I'm going to say that there's a 99% chance then that this belongs in [PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/issues) instead then.

Does this only repro in the Windows Terminal, or does this repro from a standard console window too? (try opening cmd.exe or powershell.exe, then launching ssh.exe)

**Comment by MelulekiDube** [comment]
@zadjii-msft The standard console window has the issue with not clearing the screen as well but the input is handled fine as well. As shown below: 
![image](https://user-images.githubusercontent.com/24409733/58489214-19739600-816b-11e9-8360-2117d0c4ce95.png)

Powershell, on the other hand, results in both screen not being cleared and the reaction to keyboard input being anomalous. Find below the output from PowerShell:
![image](https://user-images.githubusercontent.com/24409733/58489386-7ec78700-816b-11e9-9e4d-c3f2bfee4422.png)

**Comment by DHowett-MSFT** [comment]
This looks like a standard case of what happens when the remote application has requested a specific terminal mode and been terminated without resetting it to default. In the vim case specifically, there’s nothing we can do about that!

**Comment by MelulekiDube** [comment]
@DHowett-MSFT understood. I guess the issue with the keyboard is caused by vim open vim aswell as this is not reproducable when it was not open.
Thanks for the feedback.

**Comment by DHowett-MSFT** [comment]
This seems to have been answered.
