### ISSUE TITLE
UI for displaying Windows Terminal version is unexpected; suggest printing version to STDOUT rather than displaying in dialog box

### ISSUE THREAD

**Issue by hcwesson** [microsoft/terminal#10216]
# Description of the new feature/enhancement
The `wt --version` command should produce textual output within the terminal context, i.e. via STDOUT; this is typical behavior for many CLI utilities. Output to STDOUT is easily parsed and script-friendly, and does not disrupt user workflow.

*Examples:*
`python --version`
![image](https://user-images.githubusercontent.com/24732832/119705751-bf237380-be1e-11eb-8f3c-8aedea841725.png)

`bash --version`
![image](https://user-images.githubusercontent.com/24732832/119705675-a87d1c80-be1e-11eb-8f62-ddb4694d0118.png)

`choco --version`
![image](https://user-images.githubusercontent.com/24732832/119705793-ccd8f900-be1e-11eb-8767-58f3ec540f29.png)
 

As of WT version 1.9.1445.0, issuing the `wt --version` command spawns a dialog box with the Windows Terminal version number:
![image](https://user-images.githubusercontent.com/24732832/119707101-63f28080-be20-11eb-9e19-d7073b226ab3.png)
This is unexpected, and non-optimal for the following reasons:

- The dialog box results in loss of focus of the terminal window
- The version number contained in the dialog box can't be selected, and therefore can't be copied to the clipboard
- The dialog box interface doesn't allow for (trivial) programmatic access to the version number

# Proposed technical implementation details (optional)

Desired behavior: instead of outputting the current version in a dialog box, output directly to the issuing shell instance (using some facility such as the `Write-Object` cmdlet, possibly).

**Comment by DHowett** [comment]
> this is typical behavior for many CLI utilities

This is very much the part that makes this impossible. WT is not a CLI utility. If it were, Windows would force it to _have an empty console window_ when we started it :smile:

There's a lot (a LOT) more information in this discussion (section "displaying output in a dialog"): https://github.com/microsoft/terminal/issues/4570#issuecomment-586551445

**Comment by DHowett** [comment]
There's also a plan for fixing this at the Windows OS level here: https://github.com/microsoft/terminal/blob/dev/duhowett/spec/console-allocation/doc/specs/%237335%20-%20Console%20Allocation%20Policy.md
