### ISSUE TITLE
Action for quake mode should be called "Quake mode" in SUI

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#10210]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

Navigate to the Actions page in the Settings UI and scroll down to commands starting with S.

### Expected Behavior

Quake mode should be listed as "Quake mode".

### Actual Behavior

Quake mode is listed as "Summon the Terminal window, name: _quake".

**Comment by zadjii-msft** [comment]
Oh wait no, we can't service resource changes. Nevermind that.

**Comment by DHowett** [comment]
We can, they just need time to bake :)

**Comment by zadjii-msft** [comment]
I'm also unassigning myself, considering I _doubt_ that I get to this before I leave on paternity pt. 2, but we should _definitely_ do this for 1.10

> We can, they just need time to bake :)

Oh, well that's neat!
