### ISSUE TITLE
Light/Dark option for the Color Scheme

### ISSUE THREAD

**Issue by KubaP** [microsoft/terminal#10224]
# Description of the new feature/enhancement
Seperate light/dark Colour Scheme option. Whilst the ui elements which make up the window respond to the windows system theme setting, currently there is only the option to define one colour scheme (per theme) for the text window. With this suggestion, you would be able to define one colour scheme for when windows is set to light mode and another one for dark mode (per theme). This would be nice for those of us who change the system theme regularly, whether manually or through an automated script.

# Proposed technical implementation details (optional)
Inside of the 'Colour Schemes' setting pane, have a toggle to select whether to use one or two schemes per theme; if two are selected, a secondary colour table becomes present. It would be important that the program is able to detect when the windows system theme setting changes and update the text colouring in real time, just like the winui elements already do (i.e. wouldn't require a restart of the program).

**Comment by KubaP** [comment]
On second thought, it wouldn't be strictly necessary to define light/dark colour schemes per theme. Just the option to specify which theme to use in light mode and which theme to use in dark mode would be enough.

**Comment by j4james** [comment]
This sounds very much like #4066.

**Comment by KubaP** [comment]
Ah yes, it does indeed. I did do a quick search before filing this but seems I didn't come across that one.
