### ISSUE TITLE
wt from explorer: it does not start from current folder

### ISSUE THREAD

**Issue by aborruso** [microsoft/terminal#10227]
### Windows Terminal version (or Windows build number)

10.0.19042.985

### Steps to reproduce

- open a folder inside win explorer (in example `C:\Users\aborr\Desktop\folder`)
- write wt in the path and press enter

### Expected Behavior

Have my WSL Linux opened in `/mnt/c/Users/username/Desktop/folder`

### Actual Behavior

My WSL Linux opened in my Linux home folder `/home/username`

**Comment by skyline75489** [comment]
See https://github.com/microsoft/terminal/issues/9469#issuecomment-797598250

**Comment by zadjii-msft** [comment]
This question's been answered a huge number of times before. 

You need to use `wt -d .` for the Terminal to get the correct path.

Please [search before filing new issues. ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22explorer+address+bar%22)

/dup #878
