### ISSUE TITLE
Set Windows Terminal preview as default terminal not working

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#10229]
### Windows Terminal version (or Windows build number)

Windows Terminal preview 1.9.1445.0

### Other Software

Microsoft Windows insider preview [version 10.0.21390.1]

### Steps to reproduce

- Open Windows Terminal preview settings
- Set Windows Terminal Preview as default terminal
- Save change
- Open cmd or PowerShell from the start menu

### Expected Behavior

The shell should be opened inside the Windows Terminal Preview

### Actual Behavior

The shell is open inside conhost

Here is the contents of my current registry corresponding to the console and terminal delegation to Windows Terminal Preview
``` reg
[HKEY_CURRENT_USER\Console\%%Startup]
"DelegationConsole"="{06EC847C-C0A5-46B8-92CB-7C92F6E35CD5}"
"DelegationTerminal"="{86633F1F-6454-40EC-89CE-DA4EBA977EE2}"
```

**Comment by zadjii-msft** [comment]
(okay I know it's not a crash, but repro'ing this with the Feedback hub _should_ collect some information that might be useful in tracking down why defterm didn't work)

**Comment by mveril** [comment]
Here is the link of my feedback https://aka.ms/AAcr3w6

**Comment by miniksa** [comment]
It will open in `conhost` still if the chain activation fails into the Terminal. The registered class IDs for the chain activation are correct for Terminal Preview. For some reason, I do not have access to the feedback, so I will have to come back around to this or ask my team if they know why I cannot get access. Do note this is labeled Alpha and the amount of diagnostics I've put in so far isn't great, so you might have to hang on for a bit while I still work on it.

**Comment by mveril** [comment]
Thank you @miniksa.
I am happy to see that `conhost` is a failback when the redirection not working.  So, in any case, we still have access to our command line apps even if there is an error.
Hope you can access to my feedback and it can help you.
Thank you for this unexpected feature! I never thought it would be possible one day!
If you don't mind and if it is possible, I would very much like you to let me know where the problem is coming from when you know it. I'll be interested to know what's wrong.
Thank you

**Comment by miniksa** [comment]
I wonder if this is related to #10243....

If I can figure it out, I'll tell you @mveril.

**Comment by mveril** [comment]
Thank you @miniksa

**Comment by miniksa** [comment]
I am hoping #10415 and #10751 have improved this. I'm not certain as I haven't managed to reproduce it, but both of those improved the stability and reliability of handoffs.

**Comment by mveril** [comment]
Thank you @miniksa 
Sorry for the delay. I forgot that I had not closed this issue
