### ISSUE TITLE
Italics look awkward and are hard to read (possibly different font entirely?)

### ISSUE THREAD

**Issue by faho** [microsoft/terminal#10231]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

In this case Debian 10 in WSL1, bash 5.0.3, ncurses 6.1+20181013-2+deb10u2

I don't think it matters.

### Steps to reproduce

Set font to Cascadia Code or Mono (which, as I understand it, is the default and recommended font?)

Inside bash (or fish) run:

```bash
printf '\e[3mitalic\n\e(B\e[mnormal\n'
```

This shows the a line with the text "italic" in italic, and a line that says "normal" in non-italic.

(`\e[3m` is xterm's "enter_italics_mode" and  `\e(B\e[m` is exit_attribute_mode)

### Expected Behavior

Italic font is essentially the same as the normal font and readable.

### Actual Behavior

Italic font is distracting and hard to read.

![screenshot](https://user-images.githubusercontent.com/5185367/119798276-49311200-bedb-11eb-9aa8-63666b57770b.png)

This is mainly an issue for me because my emacs configuration renders comments in italic, so it's hard to read the comments.

**Comment by skyline75489** [comment]
Actually this is expected. The font is called 'Cascadia "Curve"'. See https://github.com/microsoft/cascadia-code/releases/tag/v2105.24

**Comment by faho** [comment]
... is there a way to turn it off?

I legitimately find it distracting (because it's sooo different from the rest) and hard to read.

Cascadia itself is alright and the other fonts I have installed are bad, so I would prefer not to have to switch to something else entirely.

**Comment by zadjii-msft** [comment]
You know, we've got issues for "add setting to disable xyz font feature", so it's not unreasonable to have one for italics as well. I'll tag this up and include it in #1790

**Comment by DHowett** [comment]
I'm going to say that we should subsume this issue ("disable italics") into the fonr config one, close this one and _direct users who have complaints about Cascadia to move along to the Cascadia repository._

**Comment by DHowett** [comment]
So: if you have complaints about Cascadia, move along to [the cascadia repository](https://github.com/microsoft/cascadia-code).

**Comment by Uxorious** [comment]
Sure. But in the meantime, I suspect a lot of us will stop using Cascadia Code.

**Comment by DHowett** [comment]
You're welcome to do that.
