### ISSUE TITLE
Crash when invoking settings

### ISSUE THREAD

**Issue by randomascii** [microsoft/terminal#10239]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

I installed the latest Windows Terminal Preview and invoked its settings option. It crashed.

### Expected Behavior

No crash, settings dialog.

### Actual Behavior

The call stack is:

0:000> kc
 # Call Site
00 KERNELBASE!RaiseFailFastException
01 combase!RoFailFastWithErrorContextInternal2
02 Windows_UI_Xaml!DirectUI::ErrorHelper::ProcessUnhandledError
03 Windows_UI_Xaml!DirectUI::ErrorHelper::ReportUnhandledError
04 Windows_UI_Xaml!DirectUI::DXamlCore::FireEvent
05 Windows_UI_Xaml!AgCoreCallbacks::FireEvent
06 Windows_UI_Xaml!CFxCallbacks::JoltHelper_FireEvent
07 Windows_UI_Xaml!CCoreServices::CLR_FireEvent
08 Windows_UI_Xaml!CommonBrowserHost::CLR_FireEvent
09 Windows_UI_Xaml!CControlBase::ScriptCallback
0a Windows_UI_Xaml!CXcpDispatcher::OnScriptCallback
0b Windows_UI_Xaml!CXcpDispatcher::OnWindowMessage
0c Windows_UI_Xaml!CXcpDispatcher::ProcessMessage
0d Windows_UI_Xaml!CXcpDispatcher::WindowProc
0e user32!UserCallWinProcCheckWow
0f user32!DispatchClientMessage
10 user32!_fnDWORD
11 ntdll!KiUserCallbackDispatcherContinue
12 win32u!NtUserMessageCall
13 user32!SendMessageWorker
14 user32!SendMessageW
15 Windows_UI_Xaml!CXcpDispatcher::SendMessageW
16 Windows_UI_Xaml!CXcpBrowserHost::SyncScriptCallbackRequest
17 Windows_UI_Xaml!CEventManager::RaiseHelper
18 Windows_UI_Xaml!CEventManager::RaiseLoadedEventForObject
19 Windows_UI_Xaml!CEventManager::RaiseLoadedEvent
1a Windows_UI_Xaml!CCoreServices::NWDrawTree
1b Windows_UI_Xaml!CCoreServices::NWDrawMainTree
1c Windows_UI_Xaml!CWindowRenderTarget::Draw
1d Windows_UI_Xaml!CXcpBrowserHost::OnTick
1e Windows_UI_Xaml!CXcpDispatcher::Tick
1f Windows_UI_Xaml!CXcpDispatcher::OnReentrancyProtectedWindowMessage
20 Windows_UI_Xaml!CXcpDispatcher::ProcessMessage
21 Windows_UI_Xaml!CXcpDispatcher::WindowProc
22 Windows_UI_Xaml!CDeferredInvoke::DispatchQueuedMessage
23 Windows_UI_Xaml!CXcpDispatcher::MessageTimerCallback
24 Windows_UI_Xaml!CXcpDispatcher::MessageTimerCallbackStatic
25 CoreMessaging!Microsoft__CoreUI__Dispatch__TimeoutHandler$CallbackThunk
26 CoreMessaging!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch
27 CoreMessaging!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop
28 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch
29 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork
2a CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc
2b user32!UserCallWinProcCheckWow
2c user32!DispatchClientMessage
2d user32!_fnDWORD
2e ntdll!KiUserCallbackDispatcherContinue
2f win32u!NtUserGetMessage
30 user32!GetMessageW
31 WindowsTerminal
32 WindowsTerminal
33 KERNEL32!BaseThreadInitThunk
34 ntdll!RtlUserThreadStart

**Comment by randomascii** [comment]
A minidump can be found here:
https://drive.google.com/file/d/1vIjkUYs6ev_2r5UMso2jWOLJREhetLUC/view?usp=sharing

**Comment by miniksa** [comment]
/dup #10106 

I checked your dump. It should be this linked issue. Fix brought in today. Servicing candidate for Very Soon(TM).
