### ISSUE TITLE
strange "tabTitle" shows up when set "commandline" to bash.exe

### ISSUE THREAD

**Issue by DevShashi1993** [microsoft/terminal#10234]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Git-2.23.0.windows.1 (64-bit)

### Steps to reproduce

Below is the windows terminal config snippet, that I configured for one of my git repo in the settings.json file. I mostly use git bash terminal so, in order to use that here as well, I tried to integrate git bash in the windows terminal using the below config.

`
{
  "guid": "{0cac0dad-34be-5f56-a8ff-afc333ab6101}",
  "name": "myApp",
  "commandline" : "C:/Program Files/Git/bin/bash.exe",
  "startingDirectory" : "C:/Users/ssharma/myApp",
  "tabTitle": "myApp",
  "hidden": false,
  "colorScheme": "Dracula",
  "fontSize": 9,
}
`

### Expected Behavior

The windows terminal tab title bar should display the tab title as configured inside the settings.json file

### Actual Behavior

The windows terminal tab title bar displays a very strange text "MINGW64:/c/Users/ssharma/SafetyBot" instead of displaying "myApp" for the respective repo.
<img width="193" alt="terminal-bug" src="https://user-images.githubusercontent.com/52294535/119822040-da6eab80-bf10-11eb-8110-1a56a9e27b39.png">

**Comment by zadjii-msft** [comment]
Yep, that's how it works. Thanks!
