### ISSUE TITLE
Can't launche WT from explorer after the latest update

### ISSUE THREAD

**Issue by Ares9323** [microsoft/terminal#10230]
### Windows Terminal version (or Windows build number)

1.8.1444.0 (Windows version: 10.0.19042.985)

### Steps to reproduce

Type "wt" in the explorer bar

### Expected Behavior

Open the Windows terminal in a window

### Actual Behavior

Error: 
`Windows cannot find 'C:\Users\Ares\AppData\Local\Microsoft\WindowsApps\wt.exe". Make sure you've typed the name correctly, then try again.`

The "wt.exe" file is present in the folder (it's 0KB and it looks like a symlink), if I double click it it doesn't work and gives the error above

**Comment by ptreitler** [comment]
Same here, can't launch it via the shortcut / start menu either.
The icon briefly shows up in the taskbar, then disappears.

**Comment by Ares9323** [comment]
> Same here, can't launch it via the shortcut / start menu either.
> The icon briefly shows up in the taskbar, then disappears.

I was able to solve this, the wt.exe in WindowsApps is a symlink used to add windows apps in environmental variables, the real files are inside the app folder, in this case for example:
`C:\Users\Ares\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe`
Just uninstall the windows terminal and reinstall it from the store, it looks like it's not able to overwrite it..

Be sure to backup your .json settings if you have customized them because otherwise they'll be lost

**Comment by zadjii-msft** [comment]
If someone else runs into this in the future - it's also possible that you might be able to fix this by going into the Settings app, and toggling the "app execution alias" for the Windows Terminal. That might just cause the OS to update it correctly ☺️

**Comment by ayush-j** [comment]
My shortcut to `C:\Users\user\AppData\Local\Microsoft\WindowsApps\wt.exe -p "profile"` suddenly stopped working today and I can confirm that toggling the app execution alias off/on worked!

![image](https://user-images.githubusercontent.com/4624541/119988772-145cb200-bfe4-11eb-8f1a-524277a5eae6.png)

**Comment by Ares9323** [comment]
I wish I had known about the "toggle option" before uninstalling it 🤣, however I took the opportunity to clean my settings.json file since it was full of deprecated or unused parameters (since I use this terminal from the first beta release).
I'm glat this post could help other people in the future, Than you all for commenting and providing a better solution than mine

**Comment by helpimnotdrowning** [comment]
> If someone else runs into this in the future - it's also possible that you might be able to fix this by going into the Settings app, and toggling the "app execution alias" for the Windows Terminal. That might just cause the OS to update it correctly ☺️

This made the error go away, but now instead it shows the icon for a second or two and then dissapears.
