### ISSUE TITLE
Setting: Default Profile UI bug

### ISSUE THREAD

**Issue by iTanChi** [microsoft/terminal#10235]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

1. Open Terminal
2. Open Setting UI
3. Click on Default Profile to display the Profile list

### Actual Behavior

1. Can't click outside to close the list
2. Scroll the screen using a mouse or touchpad -> the Profile list is scrolled but outside of the Terminal window

![image](https://user-images.githubusercontent.com/45251281/119833721-8ae8a980-bf29-11eb-9733-d96a33318dfb.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+default+profile+outside+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to  #9320 for more discussion.

/dup #9320

There's also #8938 which was tracking the light-dismiss, which is the upstream https://github.com/microsoft/microsoft-ui-xaml/issues/3961
