### ISSUE TITLE
Scroll with opened list in settings

### ISSUE THREAD

**Issue by evgeniyBolnov** [microsoft/terminal#10247]
### Windows Terminal version (or Windows build number)

10.0.21390.0

### Steps to reproduce

1) Open settings
2) Expand any list(e.g. Default profile)
3) Scroll with mouse wheel or scroll bar

### Actual Behavior

![image](https://user-images.githubusercontent.com/750697/119930710-9dde9680-bf88-11eb-8548-cddbe93ca0ae.png)
I'm honestly not sure if this is a serious bug.
Thanks

**Comment by skyline75489** [comment]
This is #9320

**Comment by evgeniyBolnov** [comment]
Sorry
