### ISSUE TITLE
Powershell instructions cross compile by default

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1024]
Following the Powershell instructions in the README, commit `4c47631bf`, on an x64 system:

```
Invoke-OpenConsoleBuild
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin'.
All packages listed in packages.config are already installed.
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 5/26/2019 11:36:38 PM.
Project "C:\Users\mikem\Downloads\Terminal\OpenConsole.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|ARM64".
```

**Comment by zadjii-msft** [comment]
@adiviness owns the powershell scripts.

**Comment by adiviness** [comment]
I'd need to look into this deeper, but if I had to guess, `Set-MsbuildDevEnvironment` is calling vcvarsall.bat and probably needs some parameters to set what configuration we want to target for by default. You should be able to pass msbuild arguments to `Invoke-OpenConsoleBuild` like this: `Invoke-OpenConsoleBuild /p:platform=x64`  to get around this for now.

**Comment by DHowett-MSFT** [comment]
Does this mean you got #1023 working?

**Comment by zadjii-msft** [comment]
This looks like it was probably fixed in the past: 
![image](https://user-images.githubusercontent.com/18356694/142911298-f58be060-4043-47bf-9469-10539a6146b9.png)

Some combo of #1023, #930, #1113
