### ISSUE TITLE
Error launching wt.exe from Explorer Run dialog

### ISSUE THREAD

**Issue by AustinWise** [microsoft/terminal#10246]
### Windows Terminal version (or Windows build number)

1.8.1444.0, 10.0.19043.1023

### Steps to reproduce

1. Open the Run dialog in Windows Explorer. This can be accomplished by holding the Windows key and pushing R.
2. Type `wt`
3. Push enter

### Expected Behavior

Expecting Windows Terminal to open.

### Actual Behavior

The following dialog is displayed by Explorer:

```
[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe\wt.exe

[Content]
Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

[OK]
```

Note that running `wt.exe` from a command prompt or launching Windows Terminal from the start menu does work as expected.

**Comment by AustinWise** [comment]
Interestingly, I was experiance a crash of WindowsTerminal.exe before. Turning the "app execution aliases" off and on again as suggested in #10167 made that crash go away. The details of that crash in case it is interesting:

```
Faulting application name: WindowsTerminal.exe, version: 1.7.2104.13003, time stamp: 0x60761d23
Faulting module name: TerminalApp.dll, version: 1.8.2105.24004, time stamp: 0x60ac2df2
Exception code: 0xc0000005
Fault offset: 0x0000000000019d52
Faulting process id: 0x4f2c
Faulting application start time: 0x01d753711f6db509
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: edf473d4-ff78-4445-8f56-732623a9b4d3
Faulting package full name: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

That was with Windows 10.0.19043.985.

**Comment by AustinWise** [comment]
I used Procmon and filtered on unsuccessful operations involving paths containing "wt" or "terminal":

![image](https://user-images.githubusercontent.com/7751/119930449-4f071180-bf34-11eb-84a3-97d480055697.png)

I do see some failure operations, but I'm not sure they are relevant. I can send the whole Procmon capture if that would be useful

**Comment by zadjii-msft** [comment]
> 
> Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_**1.7.1033.0**_x64__8wekyb3d8bbwe\WindowsTerminal.exe
> Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_**1.8.1444.0**_x64__8wekyb3d8bbwe\TerminalApp.dll

This is another one of the "torn application state" crashes. @DHowett as an fyi. I think we've got a bucket somewhere around here for "MSIX can be bodgy sometimes"

**Comment by zadjii-msft** [comment]
Actually looks like we're tracking this one in /dup #10243

**Comment by AustinWise** [comment]
Awesome, thanks for finding the issue. I worked around it by uninstalling and reinstalling Windows Terminal. I had to reboot in between for some reason, as the reinstall was failing.
