### ISSUE TITLE
Windows Terminal Quits Immediately on Start #2

### ISSUE THREAD

**Issue by Sgt-Nukem** [microsoft/terminal#10249]
### Windows Terminal version (or Windows build number)

10.0.19043.0 Microsoft Windows NT 10.0.19043.0

### Steps to reproduce

Just click the Windows Terminal icon in the taskbar I have there for ages.

### Expected Behavior

Windows Terminal just starts - like always - with my WSL2 default profile.

### Actual Behavior

For the fraction of a second you can see that a windows was about to spawn, but then it vanishes immediately.

Note: Because of this this may be a separate bug to bug #10248.

**Comment by Sgt-Nukem** [comment]
Okay, I found the culprit: If I remove the `starting directory` (i.e. leave it blank) from my default profile everything is working again.

This was set to `/var/www/_Frontend_/` (i.e. a Linux path - the Apache site directory) for ages. The directory exists and it's no problem to just go there in a new WSL2 instance spawned manually from CMD.

The only real change this week has been the Feature Update of Windows 10 to 21H1.

**Comment by zadjii-msft** [comment]
What version of the Terminal do you have? You can find this with `wt --version`.

Out of curiosity, did the `startingDirectory` being set to `/var/www/_Frontend_/` ever actually _work_ before? Or did that profile just open in `%USERPROFILE%`?

**Comment by Sgt-Nukem** [comment]
> What version of the Terminal do you have? You can find this with `wt --version`.
> 
> Out of curiosity, did the `startingDirectory` being set to `/var/www/_Frontend_/` ever actually _work_ before? Or did that profile just open in `%USERPROFILE%`?

1.8.1444.0


I'm pretty sure it worked - although not 100% so as nowadays I don't use the WSL2 prompt that much anymore.

I found a workaround using `//wsl$/Ubuntu-20.04/var/www/` at least.
BUT: `//wsl$/Ubuntu-20.04/var/www/_Frontend_/` results in the bugged behavior, too!

Turns out: `_Frontend_` under `/var/www` is a symbolic link so Apache can access my project files on the Windows side. Maybe that's the culprit?


I think it should navigate into a default path at least instead of just closing the terminal window.

**Comment by ajurna** [comment]
i have the same issue but i'm just using the default config. there is no starting directory setting in my config.

**Comment by Sgt-Nukem** [comment]
> i have the same issue but i'm just using the default config. there is no starting directory setting in my config.

Same version?



> I'm pretty sure it worked - although not 100% so as nowadays I don't use the WSL2 prompt that much anymore.

I have more doubts now - as my other PC has set the `//wsl$/...` path, too - contrary to my memory. Take it as 50/50 at best.

(N.B.: But I would _expect_ Windows Terminal to support Linux paths! As a "wrapper" around many different console sessions it should obey their path particularities. I find it kinda strange to have to set it to `//wsl$/...` - **a hidden SMB/CIFS remote filesystem path** - to start in Apache's local DocumentRoot.)

**Comment by ajurna** [comment]
yes i confirmed it was the same version.

**Comment by koenigseggcc** [comment]
I have the same problem. However, the workaround of trying to start with a different shell does not work for me.

Application is completely borked.

**Comment by koenigseggcc** [comment]
Apparently there is some Windows Update that was required to get Terminal to run. I cannot tell which update it was, because when I initially opened the 'Updates' section, it told me there was nothing to install.

**Comment by ajurna** [comment]
well i updated to 21H1 and that resolved it for me. but hardly the best solution.

**Comment by zadjii-msft** [comment]
Okay so I think OP's issue here is #10245 - for everyone else in this thread, I'm gonna redirect you to #10305 which has a big ol' list of all the crashes we're seeing, and various steps to mitigate them.

/dup #10245

Thanks!
