### ISSUE TITLE
Windows Terminal not showing on top and various issues with opening default Terminal

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#10241]
### Windows Terminal version (or Windows build number)

1.9.1445.0 (Windows Version 10.0.21387.1)

### Other Software

Windows PowerShell (and other command shells)

### Steps to reproduce

1. Open PowerShell/CMD/any other shell. Make sure that Windows Terminal is set as the default terminal application in Settings.

### Expected Behavior

The Windows Terminal should open (or create a new tab) and be on top of other windows (as it is now in focus), and the tab title should ideally be the default PowerShell/CMD tab text or any name you set for it ("Windows PowerShell", for example).

### Actual Behavior

Windows Terminal launches a new window/tab, but it does not bring it to the front. It remains behind other windows.

In addition, the title of the tab is the file location of the shortcut that launched the new Terminal instance. For example, if I launched PowerShell via the Win+X menu, the tab text is:
"Ubuntu: C:\Users\nitis\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk"

**Comment by Stanfield911** [comment]
Hi, the titles of the referenced threads 9460 and 9458 above do not appear to have anything having to do with this Windows Terminal issue!

I'm currently working with W11 Pro, 22H2 OS build 22621.2428.  This issue has recently appeared on my PC, presumably after a recent Windows 11 update.  I have never seen it before, in +2 years of using W11.  The problem: If I already have an active Windows Terminal window open (i.e. wt.exe), and then I activate a new terminals window by means of a desktop shortcut, the new terminals window is hidden behind the previous one, and I have to minimize or move the original one to see the new one in behind, or use ALT-TAB to get there.  This is clearly wrong.  Does anyone have any ideas what screwed up my windows terminal?

**Comment by zadjii-msft** [comment]
@Stanfield911 what you're undoubtably seeing is #15479, a more recent regression in 1.18+. These linked threads here are from _two years ago_.
