### ISSUE TITLE
Windows Terminal Quits Immediately on Start

### ISSUE THREAD

**Issue by XieJiSS** [microsoft/terminal#10248]
### Windows Terminal version (or Windows build number)

10.0.19042, 1.8.1444.0

### Steps to reproduce

Basically, my PC installed a windows update (KB5003173) during a restart

![image](https://user-images.githubusercontent.com/24671280/119945382-f5502700-bfc7-11eb-9256-6389e3145cd7.png)

After the restart, I tried to start Windows Terminal from Startup Menu, from task bar and from my Right-click menu, but it always quits immediately.

https://i.loli.net/2021/05/28/iu1XHN9Whc8gUlQ.gif

This is the only thing showed up:

![image](https://user-images.githubusercontent.com/24671280/119946095-d43c0600-bfc8-11eb-9702-cdc690b9dc07.png)

(its full title is `DesktopWindowXamlSource`) and it will disappear in a short time (~5s).

I haven't changed any settings of my WT before (despite font size), but I did modified my $profile file (though it worked perfectly before the windows update).

I did use Huorong antivirus, but I think this won't affect because the same phenomenon still happens after I manually quit Huorong antivirus

---

Note that this is (as far as I can tell) not related to the `startingDirectory` option because there's no such word in my configuration file

### Expected Behavior

Windows Terminal should start properly

### Actual Behavior

Windows Terminal won't start

**Comment by awolman** [comment]
This is the second time this has happened to me (if I remember correctly the first time was on the 1.4 -> 1.5 upgrade).  Can someone please tell me how to install windows terminal in a way where the upgrades don't happen automatically, so that I can decide when to upgrade?

**Comment by XieJiSS** [comment]
I found #6304 by searching `DesktopWindowX`, and it appears to me that this window is a normal step during the initializing process of a Windows Terminal instance, but now it is failing at this step.

**Comment by mkaes** [comment]
I could fix this issue by using the repair options in the settings of the app

**Comment by XieJiSS** [comment]
@mkaes Thanks, I fixed it with the repair options too.

To clarify:

1. I found the "Settings" option here:
![image](https://user-images.githubusercontent.com/24671280/119966362-d066ae80-bfdd-11eb-9156-3450bcb4f42f.png)

2. Open "Settings", click "Repair" (**NOT** Reset)

**Comment by zadjii-msft** [comment]
I'm thinking that this is probably #10211, but there's only one way to know for sure. If you could repro this with the Feedback Hub, we could get a stack trace that we can make sure is the same thing.

/feedback

**Comment by XieJiSS** [comment]
> I'm thinking that this is probably #10211, but there's only one way to know for sure. If you could repro this with the Feedback Hub, we could get a stack trace that we can make sure is the same thing.
> 
> /feedback

Hmmm, I think maybe I need to rollback the 20H1 Update (and install it again) to reproduce this? I'm not quite sure whether I'm able to rollback the update, but I'll try anyway.

**Comment by zadjii-msft** [comment]
Oh sorry, no, don't bother with that. If you've already repaired and it's gone away, then reinstalling windows isn't going to re-break it again unfortunately. This is one of those things that only happens when an app is updated by the store.

I'll just assume that this one was #10211, based on the fact that a repair fixed it. We've got like 8 other "it crashed immediately" threads, so I'm sure whatever the underlying issue here is, it's tracked by _one_ of them 😆 

/dup #10211

**Comment by tvance929** [comment]
> I could fix this issue by using the repair options in the settings of the app

that did it for me as well 

![image](https://user-images.githubusercontent.com/1489627/120078387-f8552100-c074-11eb-8449-935589d2e695.png)

**Comment by bsap-git** [comment]
Same problem, same resolution... cheers everyone.
