### ISSUE TITLE
Bad translation in Portuguese from Portugal

### ISSUE THREAD

**Issue by gio-giorgio** [microsoft/terminal#10258]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

Open settings in Windows Terminal settings.

Also right-click in any folder.

### Actual Behavior

The settings menu is using a mix of portuguese from Portugal and Brazil:

![windows_terminal](https://user-images.githubusercontent.com/26188435/120009401-35210980-bfdc-11eb-8e06-de8e375080fb.PNG)

Also, the context menu option is not translated, as shown in the picture below:

![2](https://user-images.githubusercontent.com/26188435/120009425-3b16ea80-bfdc-11eb-80e8-df12a91a4063.png)

**Comment by skyline75489** [comment]
Thanks @jorgemieec for the feedback! We've received a bunch of localization issues. It would be very helpful if you could compose a table like https://github.com/microsoft/terminal/issues/9238#issuecomment-783777519 & https://github.com/microsoft/terminal/issues/9328#issue-819602260 for the localization team. See https://github.com/microsoft/terminal/issues/10043#issuecomment-833473347 if you're wondering where to find the string keys.
