### ISSUE TITLE
WindowsTerminal crashes on startup

### ISSUE THREAD

**Issue by LaurentRicci** [microsoft/terminal#10250]
The application has been working fine for month. But starting today, it crashes on startup.
Repro steps: Start the application from the start menu
Event viewer:
Faulting application name: WindowsTerminal.exe, version: 1.8.2105.24004, time stamp: 0x60ac2e94
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x46d0
Faulting application start time: 0x01d753a7675ca192
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 767a5e38-231f-476f-bc54-ff556bf933db
Faulting package full name: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
----------------------
Fault bucket 1320776192965560009, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.8.2105.24004
P4: 60ac2e94
P5: ucrtbase.dll
P6: 10.0.19041.789
P7: 2bd748bf
P8: 000000000007286e
P9: c0000409
P10: 0000000000000007

**Comment by XieJiSS** [comment]
I think this is a dup of #10248 because I see exactly the same log in my event viewer

![image](https://user-images.githubusercontent.com/24671280/119969920-bdee7400-bfe1-11eb-823c-7ba91e1167aa.png)

**Comment by zadjii-msft** [comment]
I'm thinking that this is probably #10211, but there's only one way to know for sure. If you could repro this with the Feedback Hub, we could get a stack trace that we can make sure is the same thing.

/feedback

**Comment by LaurentRicci** [comment]
Here's the link from the feedback hub:  [](https://aka.ms/AAcrdqz)

**Comment by Domain** [comment]
I have the same problem: https://aka.ms/AAcr6n5

**Comment by bcxpro** [comment]
Same thing for me, starting today. Sorry, it seems my account cannot access the feedback hub.
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-28T16:07:16.6888076Z" /> 
  <EventRecordID>32520</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>fxmerica</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WindowsTerminal.exe</Data> 
  <Data>1.9.2105.24005</Data> 
  <Data>60ac3929</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.789</Data> 
  <Data>2bd748bf</Data> 
  <Data>c0000409</Data> 
  <Data>000000000007286e</Data> 
  <Data>6a68</Data> 
  <Data>01d753db8718df70</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data>C:\WINDOWS\System32\ucrtbase.dll</Data> 
  <Data>719d39c5-91d4-40c9-8a8f-74c842c0e079</Data> 
  <Data>Microsoft.WindowsTerminalPreview_1.9.1445.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>`

**Comment by zadjii-msft** [comment]
Okay yep, this one is /dup #10211
