### ISSUE TITLE
Windows Terminal opens under other windows when opened as default terminal

### ISSUE THREAD

**Issue by dxgldotorg** [microsoft/terminal#10262]
### Windows Terminal version (or Windows build number)

10.0.21390.1, 1.9.1445.0

### Other Software

Command Prompt (cmd.exe)

### Steps to reproduce

Set Windows Terminal Preview to the default.
Open cmd.exe from Start/Run.

### Expected Behavior

Windows Terminal window should appear on the screen even when other windows are open.

### Actual Behavior

Windows Terminal opens underneath open windows.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9460 for more discussion.


/dup #9460
/dup #10241
