### ISSUE TITLE
Nerd font glyphs are rendered with irregular blank space

### ISSUE THREAD

**Issue by comiluv** [microsoft/terminal#10278]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

Powershell 7.1.3 (from Windows Store)
[oh-my-posh](https://github.com/jandedobbeleer/oh-my-posh) 3.159.0
[Caskaydia Cove Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode) 2.1.0

### Steps to reproduce

1. Install Powershell 7.1.3
2. Install oh-my-posh 3.159.0
3. Install Caskaydia Cove Nerd Font from Nerd Font repository version 2.1.0
4. Setup oh-my-posh to use jandedobbeleer theme (or any other theme that uses Nerd Font glyphs)
5. Set Windows Terminal to use Caskaydia Cove Nerd Font (or any other Nerd Font)
6. Run Windows Terminal

### Expected Behavior

oh-my-posh theme has no blank space in the command line, like the screenshot taken with pwsh.exe below
<img width="914" alt="pwsh-noblankbetweenicons" src="https://user-images.githubusercontent.com/19642705/120086098-4a02b780-c118-11eb-8e1e-fdee8455bd46.png">

### Actual Behavior

oh-my-posh theme has a blank space in the command line, like the screenshot below.
Notice hourglass glyph below is rendered without spaces, compared to the screenshot above in pwsh.exe, probably causing the blank space.
Also, strangely, it seems command line renders correctly without any blank space if there are more characters behind the hourglass glyph
<img width="866" alt="wt-gettingablankbetweenicons" src="https://user-images.githubusercontent.com/19642705/120086221-eb8a0900-c118-11eb-9626-a0b098b7c4c2.png">

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #8341 for more discussion.

/dup #8341
