### ISSUE TITLE
Window dimensions too large on starting

### ISSUE THREAD

**Issue by omerhijazi404** [microsoft/terminal#10272]
# Description of the new feature/enhancement
Automatically adjust window size for small monitors

# Proposed technical implementation details
If I start Windows Terminal on my PC which has a small monitor, it goes out of the screen and I always have to resize manually which is annoying.
And if I set the rows and columns by myself, it still starts near the bottom right
What I would like is for it to start in the center of the screen.

**Comment by zadjii-msft** [comment]
You know, there actually are settings for the:
* [launch size](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#launch-size)
* [launch position](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#launch-position)
* even one to [automatically center on launch](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#center-on-launch)
