### ISSUE TITLE
Admin shortcuts do not open in Terminal Preview

### ISSUE THREAD

**Issue by obrobrio2000** [microsoft/terminal#10276]
### Windows Terminal version (or Windows build number)

10.0.21390.1, 1.9.1445.0

### Steps to reproduce

1) Set WT Preview as the default terminal application following the steps described [here](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-9-release/);
2) Launch CMD/PS as administrator.

### Expected Behavior

Elevated CMD/PS should respect the default terminal choice just like when non-elevated.

### Actual Behavior

CMD/PS open in Terminal only if launched with standard privileges. When launched as administrator they still open in Console Host.
Feedback Hub link: https://aka.ms/AAcrn4y

**Comment by DHowett** [comment]
Unfortunately, this is by design right now. Due to a limitation in the app platform it is impossible for Terminal to be "discovered" as the handler when the application that needs a terminal is running elevated.

**Comment by xparadoxical** [comment]
just bumped my head into gerardog/gsudo#117 and, by extension, this. 😔

**Comment by zadjii-msft** [comment]
As a 2023 status update: This still doesn't seem to be supported by the platform. We're not sure when the COM team will be able to fix this.

**Comment by stdin82** [comment]
> As a 2023 status update: This still doesn't seem to be supported by the platform. We're not sure when the COM team will be able to fix this.

I don't think this should be implemented (fixed) before providing a way to detect if the current cmd or powershell is running within Terminal
e.g. when a batch script or powershell script is launched from explorer, WT_SESSION/WT_PROFILE are not set
currently, "Run as administrator" is the only reliable way to avoid Terminal, which is good (well, unless UAC is disabled, then all opens in Terminal)

**Comment by Echostorm44** [comment]
A year later, any update on this?  Still an issue in VS2022 and Windows 11.

**Comment by michalsteyn** [comment]
This issue has now been open for over 3 years. Shocking this is taking soo long.

**Comment by PogromistDev** [comment]
Visual studio developer command prompt runs in terminal only if you already run terminal as administrator and then executed "Developer Command Prompt for VS 2022"  .lnk file or just passed its command directly
`%comspec% /k "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64`

**Comment by Dovias** [comment]
> I see some workarounds (in chinese), maybe help: https://t.me/yscschan/7010 https://t.me/yscschan/7014?single

For anyone wondering how to make this work for now until this gets fixed, you can follow my guide (which is based on the yscshan's findings) which explains how to make Windows Terminal to open when executing PowerShell or Command Prompt executable as an administrator:
https://gist.github.com/Dovias/75338df14f3fbab19b72eefb7fb9b884

https://github.com/user-attachments/assets/ae4a8ee9-eff4-4846-a42e-898191cf179a
