### ISSUE TITLE
Bug Report: @ not working on AZERTY keyboard

### ISSUE THREAD

**Issue by jmoeyersons** [microsoft/terminal#1027]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.116]
Windows Terminal version (if applicable): WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe
```

# Steps to reproduce

Open and try to type @ on AZERTY keyboard (Belgian Point layout) --> Key-combination alt-gr + 2 should provide @ in the terminal application

# Expected behavior

@ should appear

# Actual behavior

Same output as pressing on button 2 resulting in é.

**Comment by Paul-Weisser** [comment]
dupe of #521

**Comment by DHowett-MSFT** [comment]
That's right. Thanks!
