### ISSUE TITLE
Clicking Settings on dropdown menu makes Windows Terminal quit/crash

### ISSUE THREAD

**Issue by pluma9** [microsoft/terminal#10271]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.9.1445.0

### Steps to reproduce

- Open windows terminal.
- Click the drop down menu icon next to the tab.
- Click Settings

Feedback hub submission link: https://aka.ms/AAcr8nv

### Expected Behavior

The Settings UI is opened

### Actual Behavior

The terminal exits (or crashes)

**Comment by j4james** [comment]
See issue #10106.
