### ISSUE TITLE
Can not launch git bash of 0x800700c1 error

### ISSUE THREAD

**Issue by Dragode** [microsoft/terminal#10270]
### Windows Terminal version (or Windows build number)

1.8.210524004-release1.8

### Other Software

git version 2.19.1.windows.1

### Steps to reproduce

I used to launch git bash on windows-terminal successful.
After udpate windows-terminal version to 1.8.210524004-release1.8,it failed.
And I can use it in the cmd.
![screenshot 2](https://user-images.githubusercontent.com/3380280/120067510-a3360100-c0ae-11eb-8fc8-4020cdd0126d.jpg)
This is the config:
{
    "commandline": "D:\\Program Files\\scoop\\apps\\git\\2.19.1.windows.1\\bin\\bash.exe",
    "name": "git-bash",
    "startingDirectory": null
}

### Actual Behavior

![screenshot 1](https://user-images.githubusercontent.com/3380280/120067434-2d319a00-c0ae-11eb-8fd6-c85c6f5b0fd7.jpg)

**Comment by KalleOlaviNiemitalo** [comment]
Is there a `D:\Program` file?According to <https://github.com/microsoft/terminal/issues/7195#issuecomment-720627551>, that could cause error 0x800700c1. If so, you could perhaps delete the file or add quotation marks around the path:

```JSON
{
    "commandline": "\"D:\\Program Files\\scoop\\apps\\git\\2.19.1.windows.1\\bin\\bash.exe\"",
    "name": "git-bash",
    "startingDirectory": null
}
```

(0x800700c1 is HRESULT_FROM_WIN32(ERROR_BAD_EXE_FORMAT), "%1 is not a valid Win32 application.")

**Comment by casterle** [comment]
> Is there a `D:\Program` file?

Thanks, from the future! 

I don't know where it came from but removing that 'Program' file it fixed by 'Got Bash' problems.

**Comment by NotYoojun** [comment]
This worked!
I found a sus `Program` file on my D. Deleting this file fixed everything!

<img width="886" alt="image" src="https://github.com/microsoft/terminal/assets/54567489/1654455b-65ad-4414-a8b4-87df231f0472">
