### ISSUE TITLE
Terminal exited without user interaction

### ISSUE THREAD

**Issue by soxhi8** [microsoft/terminal#10277]
### Windows Terminal version (or Windows build number)

WT 1.8.1444.0, Win 10 19042.985

### Steps to reproduce

Terminal was left running a tool in Powershell. Returning to the computer showed Terminal closed. Trying to reopen it, the process exits after a few seconds without opening a window.
From around the time that Terminal exited, this is found in event log (unlocalized from German):
`The access history in hive "\??\C:\Users\Username\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\Settings\settings.dat" was cleared updating 3 keys and creating 1 modified pages.`

### Expected Behavior

Terminal should not exit unless it is told to.

### Actual Behavior

Terminal went bye-bye without telling anyone.

**Comment by soxhi8** [comment]
The not-starting-part seems to be related to: https://github.com/microsoft/terminal/issues/10211
The part about closing without being told to close still stands.

**Comment by sin9yt** [comment]
Can confirm the same, able to replicate it

**Comment by kzvdar42** [comment]
The same for me happened at both of my machines. Restart didn't helped

**Comment by zadjii-msft** [comment]
Well the registry lookup sure is weird. Best way to get to the bottom of this is with a Feedback Hub trace: /feedback

**Comment by kzvdar42** [comment]
Created a crash report: https://aka.ms/AAcslt1

**Comment by soxhi8** [comment]
I created a report in the Hub, hopefully it has everything that could help:
https://aka.ms/AAcsm3k

**Comment by zadjii-msft** [comment]
Thanks! This is /dup #10211
