### ISSUE TITLE
WindowsTerminal.exe/ wt.exe uses different settings than Windows Terminal App

### ISSUE THREAD

**Issue by constantin-kuehne** [microsoft/terminal#10275]
### Windows Terminal version (or Windows build number)

1.8.1444.0 / 1.8.210524004-release1.8

### Steps to reproduce

When opening the Windows Terminal App via the Windows Terminal App Icon it uses the settings.json under C:\Users\User\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState while if you open it via the WindowsTerminal.exe/ wt.exe it opens the settings.json under C:\Users\User\AppData\Local\Microsoft\Windows Terminal, therefore if you use the wt command in the "search bar" of the explorer it opens it with the wrong settings.

Is this the intended behavior? 

Settings when opening with Windows Terminal App Icon
![Screenshot 2021-05-29 020149](https://user-images.githubusercontent.com/70445955/120080362-d9787e00-c0b8-11eb-897e-982db0af3caa.png)

Settings when opening with WindowsTerminal.exe/ wt.exe/ wt command in explorer
![Screenshot 2021-05-29 020214](https://user-images.githubusercontent.com/70445955/120080382-ef863e80-c0b8-11eb-965f-a188a098a30d.png)

Also the version numbers are different based on opening sequence. It is 1.8.1444.0 when opening with Windows Terminal App Icon and 1.8.210524004-release1.8 when opening with the WindowsTerminal.exe/ wt.exe / wt in explorer.

### Expected Behavior

The expected behavior would be that they use the same settings.

### Actual Behavior

They use different settings.json as stated above.

**Comment by DHowett** [comment]
If I had to guess, this is because you (or something on your system) changed the permissions on `C:\Program Files\WindowsApps`. It is critically important to the app platform (which supports all packaged applications on Windows) that the permissions on that folder are _not damaged._

See #9452 for more information, as well as remediations.

/dup #9452
