### ISSUE TITLE
Quake Mode multi monitor setup

### ISSUE THREAD

**Issue by SamirBanjanovic** [microsoft/terminal#10274]
I've been toying with `quake` mode and noticed some odd behaviors when running on multiple monitors, where one is on a vertical orientation.  On first summon quake mode dropped down from my desired "main" monitor.  Consecutive summons have it split between two monitors but never on a single monitor.  I tried changing the `monitor` and `desktop` values of the command without luck.

In the attached image you can see that the window dropped down to my left most monitor (which is vertical).  
It appears the drop down is tracing location of mouse relative to left|right of center in regards to the entire resolution of the combined screens (?).

If my mouse is towards left of center it will render on left most monitor, with the right edge meeting center of main screen.
![image](https://user-images.githubusercontent.com/2653176/120077325-efb21a00-c077-11eb-8a1e-5e3f0a006f71.png)

If my mouse is to the right of center of main screen it renders on the right "half" of the resolution, with the left edge meeting center of main monitor.
![image](https://user-images.githubusercontent.com/2653176/120077333-f9d41880-c077-11eb-99f3-d6b6d3cffab4.png)

Last interesting thing to happen is -- if my mouse is on the left edge of my left most screen it renders off screen.
![image](https://user-images.githubusercontent.com/2653176/120077359-14a68d00-c078-11eb-9d0f-82952bae4290.png)

**Comment by TomaszGrzmilas** [comment]
In my case, I got two monitors. On first I have no Windows taskbar, on second I got Windows taskbar located at right monitor edge.

When I run Quake mode on monitor 2 it is looking ok:

![image](https://user-images.githubusercontent.com/32311696/120359506-079fcd00-c308-11eb-83df-2331971a0524.png)

But when I do Quake mode on monitor 1, Windows Terminal is having gap in place where the Windows taskbar is on second monitor:

![image](https://user-images.githubusercontent.com/32311696/120359612-29994f80-c308-11eb-91ed-7cf6de8e035a.png)

**Comment by brentos99** [comment]
I've been having some issues with the quake mode on multi monitors. (love this new feature btw)..

My setup is a 4k landscape monitor above the laptop and a hd portrait monitor next to the that. All 3 monitors have different resolutions and scaling factors. 

When opening on the laptop screen it works perfectly, full width of the screen. 
When opening on the 4k screen, it only goes to 3/4 width of the screen. 
When Opening on the 1080, portrait screen, its width spills over to the 4k screen. 

Sometimes it gets confused and doesn't know which is the active screen and opens in the previous window, other times it opens in random places on the screen (usually the middle)

There is also what feels like screen tear in the slide down effect. 

Hope this helps in getting the bugs ironed out. If you want I provide screenshots.

Brent

**Comment by nico-abram** [comment]
I have two monitors, both have the task bar at the bottom, and both are using the regular orientation. However the quake mode terminal has the wrong width. It worked fine yesterday, I'm not sure what's wrong now:
![imagen](https://user-images.githubusercontent.com/24706838/123694345-9af8ef00-d82f-11eb-9763-118a8ae7dd19.png)

**Comment by zadjii-msft** [comment]
Welp, that's weird. I've been using QM for a while with multi-mon, but never ran into anything like this. Maybe the vertical/horizontal orientation is important here. I'll stick this on 2.0 for now, but if anyone who's actually hitting this could help debug, that'd definitely be appreciated.

**Comment by nico-abram** [comment]
Ok I think I can reproduce my issue now. Like I said before, I have two monitors, both have the task bar at the bottom, and both are using the regular orientation.

1) Open QM terminal with hotkey
2) Hit winkey+shift+[left or right arrow key] to move it to the other monitor
3) The terminal now has the wrong size in the second monitor
![imagen](https://user-images.githubusercontent.com/24706838/124823375-7d223d00-df47-11eb-860d-0b0188546f9c.png)
4) It is already wrong now, but if you move it back to the first screen (With either the QM terminal hotkey or winket+shift+[left or right arrow key] ), it is also wrong on the first monitor (It ends up like my screenshot in the comment above)

**Comment by zadjii-msft** [comment]
notes before I leave for the weekend:

* WM_WINDOWPOSCHANGING is probably not the right place to do this. 
  * It gets called way too often, we don't need to try and enterQuakeMode that many times
  * For whatever reason, doing enterQuakeMode there does calculate the right size, but then the window still ends up at the wrong dimensions. Maybe this is  getting followed up with a WM_SIZING or something. 
* Where is the right place to determine that we've moved? WM_MOVING? I suppose that might work

**Comment by b-hayes** [comment]
IM having a similar issue. I have horizontal screens layout but they're different resolutions and scaling. My secondary screen is 4k@150% scaling and my primary screen is 1440p. When the terminal opens on the secondary screen it doesn't go all the way across.

![image](https://user-images.githubusercontent.com/30540495/126919841-bcca1979-9f42-48d8-aad9-790992d78df4.png)


PS - Also really appreciate this quake console mode. I was doing it manually with AHK and then it wasn't working properly and realized you guys backed the feature in using the same hotkey 😅

**Comment by b-hayes** [comment]
Actually, is there any way to just turn this off? I want my own implementation back and WT won't let me use this keyboard shortcut for my AHK script anymore.

I thought it was cool but Quake mode is a hindrance I want it gone.
