### ISSUE TITLE
Can we has FIRZA 

### ISSUE THREAD

**Issue by chargen** [microsoft/terminal#10288]
Can we has FiraCode as embedded secure font in Windows Terminal https://github.com/tonsky/FiraCode  is a free monospaced font with programming ligatures (see site) 

# Proposed technical implementation details (optional)

**Comment by LuanVSO** [comment]
there's already a free monospaced font with programing ligatures included in terminal, it's called cascadia code

**Comment by zadjii-msft** [comment]
The Terminal's already got a great monospace font that we ship with - [Cascadia Code](https://github.com/microsoft/cascadia-code). I don't think we're interested in adding any more that we ship with by default, though you're always free to download other fonts yourself to use with the Terminal.

**Comment by chargen** [comment]
Does it have he same typographic properties of special alignment, I
understand ligatures are quickies I considered this the most elaborate font
configuration. i hope you will look into it and compare
