### ISSUE TITLE
Magic

### ISSUE THREAD

**Issue by angelcervantesa** [microsoft/terminal#10282]

**Comment by KalleOlaviNiemitalo** [comment]
Wasn't @msftbot supposed to close blank issues like it did in <https://github.com/microsoft/terminal/issues/5653>?

**Comment by zadjii-msft** [comment]
Oh, this one was probably missed because the doc template has a comment in it:

```
<!-- Briefly describe which document needs to be corrected and why. -->
```

anyways yea, this needs more info to be actionable.
