### ISSUE TITLE
Profile should support running a set of commands on creation

### ISSUE THREAD

**Issue by gilmishal** [microsoft/terminal#10285]
# Description of the new feature/enhancement

I would like the ability to run a set of commands when opening a new profile from the dropdown.
An example of it would be running a cli tool in a specific context (WSL), or setting some environment variable (WSL - export).

# Proposed technical implementation details (optional)
1. Add a section to Profile Settings called startup scripts/commands
2. Allow writing a bash/ps/batch scripts in a box

When creating a new terminal tab for this profile this script will run.

**Comment by LuanVSO** [comment]
you can do this on `.bashrc`, `.bashprofile`, `.profile`, `.bashlogin`, `.login` and on the command line property on terminal: like `wsl -- bash -c ~/mycoolconfig.sh`

**Comment by zadjii-msft** [comment]
Yep, you can absolutely run a bunch of commands in the [`"commandline"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-general#command-line) property. 

e.g. for cmd: `"commandline": "cmd.exe /k foo.bat"`
