### ISSUE TITLE
[settings] Acrylic opacity option could/should include percent sign.

### ISSUE THREAD

**Issue by chingucoding** [microsoft/terminal#10289]
# Description of the new feature/enhancement

Currently, when selecting the opacity of the acrylic option of a profile, the values range from 0 to 100. However in reality (and in the API of the AcrylicBrush) the values range from 0 to 1 (0 to 100%).

# Proposed technical implementation details (optional)

I think we can just include a `%` sign at the end of the label.

# Open questions
Does this need to be localized? Is a `%` sign optimal here or are there better alternatives?

-------------------

If it's fine I would like to try work on this issue.

**Comment by zadjii-msft** [comment]
That seems fine to me, good idea!
