### ISSUE TITLE
No documentation on adding bash tabs

### ISSUE THREAD

**Issue by EranGon** [microsoft/terminal#1028]
I have the Linux sybsystem installed on my Windows machine, but in the Cascadia window there's no option to create a new bash tab.
I didn't see any documentation on how to edit the configuration to enable this

**Comment by zadjii-msft** [comment]
I think as we stabilize the settings format, documentation on how to do this is definitely something we should add. 

Even a quick `docs/howto/AddACustomProfile.md` file would probably be very helpful.

@bitcrazed @cinnamon-msft

**Comment by Jeffery-Song** [comment]
This is how I enable bash in Windows Terminal:
* Use the `uuidgen` tool in Visual Studio Command Prompt to generate a `guid`
* Copy a `profile` in Windows Terminal's setting profile, replace:
  * `guid` with the one you generated
  * `name` : wsl
  * `commandline`: ubuntu.exe
  * `icon`: you can find it in `C:\Program Files\WindowsApps\` where ubuntu is located

**Comment by DHowett-MSFT** [comment]
Answered; thanks @jeffery-song.
