### ISSUE TITLE
Color scheme does not save

### ISSUE THREAD

**Issue by 0xdeadc0d3** [microsoft/terminal#10286]
### Windows Terminal version (or Windows build number)

10.0.19042.985, 1.8.1444.0

### Steps to reproduce

1. Open settings
2. Choose any color color scheme (except Campbell)
3. Click save button
4. Restart app

### Expected Behavior

Color scheme changes successfully 

### Actual Behavior

Color scheme does not change from settings, but it does when i edit settings.json. It seems that for some reason the terminal is unable to insert the colorScheme key into settings.json

**Comment by zadjii-msft** [comment]
Are you going to the "Color Schemes" page
![image](https://user-images.githubusercontent.com/18356694/115410049-eea7e600-a1b7-11eb-825c-c12ca8a3535c.png)

or are you changing the "color scheme" of a given profile:
![image](https://user-images.githubusercontent.com/18356694/115410168-05e6d380-a1b8-11eb-8a19-45f7acf4c6d1.png)


The first page is used for _editing the color scheme itself_. The second is for changing the appearance of the selected profile. The dropdown on the Color Schemes page is just used for _selecting which scheme you want to edit_. It doesn't apply that scheme to any profiles.

/dup #9775

**Comment by 0xdeadc0d3** [comment]
I change color scheme from the "Color Schemes" page
