### ISSUE TITLE
Rendering Problem when scrolling, minimizing or resizing.

### ISSUE THREAD

**Issue by RomelSan** [microsoft/terminal#10291]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Other Software

I am on Windows 10 21H1 using built in `ssh` to connect to linux boxes.

### Steps to reproduce

1. Log in using ssh.
2. Minimize or resize or scrolling. (Change the window size or just scroll)
3. The screen becomes weird.

### Expected Behavior

Normal rendering, same as using Putty or Kitty.

### Actual Behavior

The screen messes ASCii art and colored lines.  

![Animation](https://user-images.githubusercontent.com/11341002/120113033-43873680-c13e-11eb-93ab-e09f7932e428.gif)  

On linux with "Oh my ZSH" the command line or last lines are duplicated and/or not aligned.  

![Screen Stuff](https://user-images.githubusercontent.com/11341002/120112662-54cf4380-c13c-11eb-91e3-eb2a419809b8.PNG)

**Comment by RomelSan** [comment]
I am using a laptop Intel i3 10th gen. No fancy GPU. The screen is full hd. 1920x1080.  
Same behavior on my desktop computer with a GPU Nvidia GTX 1650.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #32 for more discussion.

/dup #32
