### ISSUE TITLE
"Git bash" profile in wt not loads ".bash_profile" config

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#10290]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.7.1091.0

### Other Software

- **Git bash:** GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

### Steps to reproduce

1. Create git bash profile
2. Create `.bash_profile` in `%userprofile% `
3. Run terminal and open Git bash tab

### Expected Behavior

Bash profile config is load.

### Actual Behavior

Bash profile isn't loaded.

### Config
**Windows Terminal**
```json
            {
                "backgroundImage": null,
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "name": "Git-Bash",
                "scrollbarState": "visible",
                "startingDirectory": "D:\\AppDev\\Github",
                "useAcrylic": false
            },
```

**Bash profile**
```bash
# Aliases
alias gl='git log --decorate --oneline --all --graph -10'
alias gc='git checkout'
alias gcn='git checkout -b'
alias gbl='git branch --list'
alias gbd='git branch --delete'
alias gcom='git commit -m'
alias cls='clear'
alias clear='clear;alias'


#Startup Commands
alias
gitk & disown
```

**Comment by LuanVSO** [comment]
you have to pass `-li` in the command line for bash to run as a login shell

**Comment by htcfreek** [comment]
@LuanVSO 
Thank you. It works. 👍
