### ISSUE TITLE
[error 0x800700c1 when launching `C:\Program Files\PowerShell\7\pwsh.exe']

### ISSUE THREAD

**Issue by Manbearpiet** [microsoft/terminal#10293]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.9.1445.0

### Steps to reproduce

Startup terminal as usual (with C:\Program Files\PowerShell\7\pwsh.exe as default)
Also happens when new tabs are opened with pwsh

### Expected Behavior

It starts C:\Program Files\PowerShell\7\pwsh.exe

### Actual Behavior

It throws [error 0x800700c1 when launching `C:\Program Files\PowerShell\7\pwsh.exe']

**Comment by zadjii-msft** [comment]
Out of curiosity, which architecture of pwsh 7 did you install, and what architecture is your machine? 

We've seen this before a few times (#7160, #7195), but not when someone's hardcoding the path.

Troubling that there are two similar reports (see also #10270) on the latest update.

**Comment by zadjii-msft** [comment]
Also, 

> Is there a `C:\Program` file? According to <https://github.com/microsoft/terminal/issues/7195#issuecomment-720627551>, that could cause error 0x800700c1. If so, you could perhaps delete the file?

**Comment by Manbearpiet** [comment]
> 
> 
> Out of curiosity, which architecture of pwsh 7 did you install, and what architecture is your machine?
> 
> We've seen this before a few times (#7160, #7195), but not when someone's hardcoding the path.
> 
> Troubling that there are two similar reports (see also #10270) on the latest update.

Using the exe
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Launching the path mentioned in the Terminal settings with run-command works fine.
![image](https://user-images.githubusercontent.com/43993129/120186433-cb8b4000-c213-11eb-851d-63d206743fcd.png)

When pasted:
![image](https://user-images.githubusercontent.com/43993129/120186589-fe353880-c213-11eb-8162-a1e1e0779f53.png)

settings.json:
Contains the following:
```
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",





            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            
           
```

**Comment by Manbearpiet** [comment]
> 
> 
> Also,
> 
> > Is there a `C:\Program` file? According to [#7195 (comment)](https://github.com/microsoft/terminal/issues/7195#issuecomment-720627551), that could cause error 0x800700c1. If so, you could perhaps delete the file?

This was the fix!!


The file blocking launch is a log file created with Citrix receiver updates:
```
[11F4:38F4][2021-05-28T13:24:51]i001: Burn v3.10.4.4718, Windows v10.0 (Build 19042: Service Pack 0), path: C:\Windows\Temp\{someguid}\.cr\vc_redist.x64.exe
[11F4:38F4][2021-05-28T13:24:51]i009: Command Line: '-burn.clean.room=C:\Windows\SysWOW64\config\systemprofile\Citrix\UpdaterBinaries\Ctx-someguid\Extract\vc_redist.x64.exe -burn.filehandle.attached=596 -burn.filehandle.self=736 /q /norestart /ACTION=Install /l C:\Program Files (x86)\Citrix\Logs\CTXReceiverInstallLogs-20210528-132448\CtxInstall-vc_redist-20210528-132449.log'
```

Removing the `C:\Program`-file fixed it

![image](https://user-images.githubusercontent.com/43993129/120187220-d5617300-c214-11eb-9bbd-e57f6e6094db.png)
