### ISSUE TITLE
Cannot open settings in Windows Terminal Preview 1.9.1445.0

### ISSUE THREAD

**Issue by toreaurstadboss** [microsoft/terminal#10298]
### Windows Terminal version (or Windows build number)

10.0.18363.0

### Steps to reproduce

Start Windows Terminal Preview 1.9. 
For simplicity of state I only run one pane with CMD in it

Choose Settings in drop down menu of Terminal
Windows Terminal Preview crashes

settings.json must be edited manually because of this

### Expected Behavior

Ability to select settings option in Windows Terminal Preview and access settings user interface

### Actual Behavior

It crashes. So I use VsCode to edit the settings.json - but this is of course not the easiest way to go around editing the settings of this otherwise great terminal.

Im attaching a Bandicam screen grab showing the crash

Note that the crash happens for both install options: GitHub MSI file from Releases and Windows Store. I am using newest Windows Terminal Preview 1.9

https://user-images.githubusercontent.com/49962899/120215446-07370180-c236-11eb-8fca-2a0ecb6019c4.mp4

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #10106 for more discussion.

/dup #10106
