### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/terminal#10295]
### Windows Terminal version (or Windows build number)

19042.928 1.7.1033

### Steps to reproduce

![image](https://user-images.githubusercontent.com/12285582/120187132-ffcc2400-c246-11eb-89cd-00ea9fe5a933.png)

### Actual Behavior

UI bug

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #8948 for more discussion.

/dup  #8948
