### ISSUE TITLE
Running `wt -w 0 -p <profile>` while existing Terminal window is open causes the window to be minimized

### ISSUE THREAD

**Issue by djsavvy** [microsoft/terminal#10292]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

This behavior started with Preview build 1.9.1445.0 in my experience. 

If I run `wt -w 0 -p <profile name>` __while the existing WT window is focused__, the new tab opens with the correct profile, but the entire window gets minimized for some reason. 

At first I though this was just an issue with AutoHotKey, but I was able to reproduce it by running the command via Win+R. Make sure that the existing WT window is focused, though, since focusing a different window and then running the command caused the new profile tab to open without the existing window being minimized. 

### Expected Behavior

The tab opening without the window being minimized, in all cases. 

### Actual Behavior

The tab opened, but the window got minimized.

**Comment by zadjii-msft** [comment]
Oh my god I know exactly what I did.

When we summon the window because a commandline has been dispatched to it, we use a default-constructed window summon behavior. And the default behavior is to toggle visibility. It shouldn't toggle, it should always just summon. Good catch!
