### ISSUE TITLE
Crashes immediately after launch

### ISSUE THREAD

**Issue by guyrleech** [microsoft/terminal#10303]
Was running fine before I hibernated my Win10 21H1 laptop but I noticed the existing Windows Terminal window was no longer present after resuming and every time I launch it, it crashes immediately. I have seen this once before but it is usually fine after resume from hibernation. I have full process dumps (95MB zipped). Attached is the windbg !analyze -v output but obviously doesn't tell me much as I don't have symbols for it. I have version 1.8.1444.0 according to the Store app.

[windowsterminal crash.TXT](https://github.com/microsoft/terminal/files/6574768/windowsterminal.crash.TXT)

**Comment by microhod** [comment]
I'm seeing the same behaviour on 1.8.1444.0 - I open the app, it waits a couple seconds and crashes.

I'm on Win10 2004 19041.985

**Comment by joeykins82** [comment]
Same issue: Terminal 1.8.1444.0 on Win10 2020H2 19042.985

**Comment by zadjii-msft** [comment]
Thanks for the `!analyze`! From the stack, this looks like /dup #10211. A Repair of the app might help you, or setting the default profile's `fontFace` to something other than the `Cascadia` family of fonts. Hopefully the hotfix should be shipping today or tomorrow.
