### ISSUE TITLE
c0000409 (Security check failure or stack buffer overrun) Crash On Startup

### ISSUE THREAD

**Issue by shanepowell** [microsoft/terminal#10301]
### Windows Terminal version (or Windows build number)

1.8.2105.24004

### Other Software

Since windows store updated Terminal to the latest version (on two different machines), terminal crashes on startup and generates a dump file with the c0000409 exception code.

Stack trace is:
STACK_TEXT:  
0000009a`971ad2c0 00007ff8`2e541f9f     : 0000009a`00000003 00007ff8`00000003 00007ff8`21cf52b0 00007ff8`21cf5280 : ucrtbase!abort+0x4e
0000009a`971ad2f0 00007ff8`21d81aab     : 0000009a`971ae580 0000009a`971ad420 0000009a`971adbf0 00000000`00000000 : ucrtbase!terminate+0x1f
0000009a`971ad320 00007ff8`21d82317     : 00000000`00000000 00000000`00000000 00000000`00000000 00007ff8`21ce2519 : VCRUNTIME140_1!_NLG_Return2+0x95b
0000009a`971ad4f0 00007ff8`21d840d9     : 00007ff6`33020000 0000009a`971ae580 0000009a`971addb0 0000009a`971adbf0 : VCRUNTIME140_1!_NLG_Return2+0x11c7
0000009a`971ad590 00007ff6`3303627c     : 0000009a`971ae8a0 00007ff6`3303c5c8 0000009a`971ae580 0000009a`971ae8a0 : VCRUNTIME140_1!_CxxFrameHandler4+0xa9
0000009a`971ad600 00007ff8`3089217f     : 00000000`00000000 0000009a`971adba0 0000009a`971ae580 00000000`00000001 : WindowsTerminal+0x1627c
0000009a`971ad630 00007ff8`30841454     : 00000000`00000000 0000009a`971adba0 0000009a`971ae580 00000000`00000001 : ntdll!RtlpExecuteHandlerForException+0xf
0000009a`971ad660 00007ff8`308411a5     : 00000000`00000000 0000009a`971ae420 00000000`00000000 0000009a`971addb0 : ntdll!RtlDispatchException+0x244
0000009a`971add70 00007ff8`2e094b89     : 00000000`00000000 00007ff6`3303d870 0000009a`971ae6d0 00000000`00000090 : ntdll!RtlRaiseException+0x185
0000009a`971ae560 00007ff8`21ce6480     : 000001c3`04367d18 00000000`00000000 00000000`00000000 00000000`00000000 : KERNELBASE!RaiseException+0x69
0000009a`971ae640 00007ff6`3302639f     : 00000000`00000000 00000000`88985004 00000000`88985004 00000000`00000000 : VCRUNTIME140!_CxxThrowException+0x90
0000009a`971ae6a0 00007ff6`33029154     : ffffffff`829321c7 0000009a`971ae880 0000009a`971aee00 0000009a`971ae800 : WindowsTerminal+0x639f
0000009a`971ae700 00007ff6`3302b203     : 0000009a`971ae909 00007ff8`3081aea9 00000000`00000000 00000000`00000540 : WindowsTerminal+0x9154
0000009a`971ae850 00007ff6`3302f055     : 00000000`00000000 00000001`00000000 00000000`00000000 00000000`00000000 : WindowsTerminal+0xb203
0000009a`971ae8a0 00007ff6`33032b18     : 00000000`00000000 0000009a`971ae9f8 0000009a`971ae9f0 00007ff8`2b520000 : WindowsTerminal+0xf055
0000009a`971ae970 00007ff6`330304e6     : 00000000`00000001 00000000`00000000 00000000`00000000 0000009a`971aee00 : WindowsTerminal+0x12b18
0000009a`971aea90 00007ff8`2ecee858     : 00000000`00570b46 00000000`00000001 00000000`00000000 00000000`00000000 : WindowsTerminal+0x104e6
0000009a`971aeb10 00007ff8`2ecee3dc     : 00000000`00570b46 00007ff6`33030430 00000000`00570b46 00005669`00000001 : user32!UserCallWinProcCheckWow+0x2f8
0000009a`971aeca0 00007ff8`2ed02bf7     : 00000000`00000000 00000000`00000000 00000000`00000000 ffffffff`ffffffff : user32!DispatchClientMessage+0x9c
0000009a`971aed00 00007ff8`30890c54     : 00000000`00000000 00000000`80000000 00000000`00008008 00007ff8`2ecee3dc : user32!__fnINLPCREATESTRUCT+0x87
0000009a`971aed60 00007ff8`2e391ec4     : 00007ff8`2ece7d8b ffffffff`ffff0000 00000000`00000000 0000009a`971af348 : ntdll!KiUserCallbackDispatcherContinue
0000009a`971aeed8 00007ff8`2ece7d8b     : ffffffff`ffff0000 00000000`00000000 0000009a`971af348 0000009a`971aefa0 : win32u!NtUserCreateWindowEx+0x14
0000009a`971aeee0 00007ff8`2ece7958     : 006c0061`00000006 00650078`00000000 00000000`00000000 00000000`00cf0000 : user32!VerNtUserCreateWindowEx+0x20f
0000009a`971af270 00007ff8`2ece77a2     : 0000009a`80000000 00000000`00000000 00007ff6`33020000 000001c3`043654a0 : user32!CreateWindowInternal+0x1a4
0000009a`971af3d0 00007ff6`3303108c     : 00000000`00000010 000001c3`04365538 0000009a`971af640 00007fff`97fe829b : user32!CreateWindowExW+0x82
0000009a`971af460 00007ff6`330276a5     : 000001c3`043654a0 000001c3`043654a0 0000009a`971af7c0 0000009a`971af7c0 : WindowsTerminal+0x1108c
0000009a`971af540 00007ff6`3302563d     : 00000000`00000005 00000000`00000005 00000000`00000000 00000000`00000000 : WindowsTerminal+0x76a5
0000009a`971af730 00007ff6`330348f2     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : WindowsTerminal+0x563d
0000009a`971af8e0 00007ff8`2e877034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : WindowsTerminal+0x148f2
0000009a`971af920 00007ff8`30842651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
0000009a`971af950 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

So it looks like something is going wrong in a try/catch handler.

Module information.
00007ff6`33020000 00007ff6`33071000   WindowsTerminal   (no symbols)           
    Loaded symbol image file: WindowsTerminal.exe
    Image path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
    Image name: WindowsTerminal.exe
    Browse all global symbols  functions  data
    Timestamp:        Tue May 25 10:54:12 2021 (60AC2E94)
    CheckSum:         000574E9
    ImageSize:        00051000
    File version:     1.8.2105.24004
    Product version:  1.8.2105.24004
    File flags:       0 (Mask 3F)
    File OS:          4 Unknown Win32
    File type:        1.0 App
    File date:        00000000.00000000
    Translations:     0000.04b0
    Information from resource tables:

It would be nice if the terminal pdb's where available via the normal Microsoft public pdb servers.

Both machines are development machines with latest versions of MSVC 2019 and MSVC 2019 preview installed.
Both machines generate the similar looking dump file stacks.

I have multiple full memory dmp files if you want them.  They are too big to attach to this bug report.

### Steps to reproduce

Start terminal.

### Expected Behavior

It should start.

### Actual Behavior

Flashes when exits, the OS generates the dump file due to the crash.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #10211 for more discussion.

/dup #10211
