### ISSUE TITLE
Quake mode not working

### ISSUE THREAD

**Issue by gnarlygeek** [microsoft/terminal#10313]
### Windows Terminal version (or Windows build number)

10.0.21390.0 1.9.1445.0

### Other Software

NA - Windows hot key issue

### Steps to reproduce

Removed existing settings.json file to force create update to the new terminal release.
Win+` generates tone - no quake mode.
Edit the new settings.json file - no quake mode found.
Add quake mode setting per the documentation - tried both entries - quick and long.
Get error on value toCursor - replaced with toCurrent.
Save settings.json
Win+` still does not load - just a tone.
Edit settings.json and change  key sequence to Win+shift+q and save.
Win+shift+q - does not load - same tone sounds.
## The prior step confirms that this issue isn't a hot key conflict - I do not have PowerToys installed.
[new-settings.zip](https://github.com/microsoft/terminal/files/6587460/new-settings.zip)

### Expected Behavior

Quake mode open

### Actual Behavior

A tone sounds instead and no screen activity.

**Comment by gnarlygeek** [comment]
Sorry about the formatting. I didn't realize the back tick would do that.

**Comment by zadjii-msft** [comment]
What happens if you try a key binding that doesn't involve the <kbd>win</kbd> key? What about something ridiculous like `ctrl+a` (obviously this is for testing, don't leave that bound, it'll steal <kbd>ctrl+a</kbd> from all apps).

**Comment by gnarlygeek** [comment]
Good suggestion. I tried ctrl+q and ctrl+shift+q - nothing - no sound - nothing.

**Comment by gnarlygeek** [comment]
Ok, new development. The issue is in the instructions/documentation. Nowhere does it explicitly mention that Windows Terminal must ALREADY be open before the hot key will work.  This is obvious to me now.  However it seems that one could also assume that the Terminal team had somehow used a Windows feature to enable the hot key without Terminal running. I will close this issue now, but recommend the usage text for Quake mode explicitly say that Windows Terminal (Preview) must already be open.

**Comment by zadjii-msft** [comment]
> Nowhere does it explicitly mention that Windows Terminal must ALREADY be open before the hot key will work.

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon-preview:

> * These key strokes will only work when an instance of the terminal is already running. To launch the terminal automatically on login, see startOnUserLogin.

🤔

**Comment by gnarlygeek** [comment]
Ouch! Thanks. I think I will set the launch on login.
