### ISSUE TITLE
 C1 control characters break SetConsoleTitleW API

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#10312]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

- Compile and run the following code:

```C++
#include <windows.h>

int main()
{
	if (!SetConsoleTitleW(L"\x80 Spanish Inquisition"))
		return 1;

	MessageBox(0, "I didn't expect that", 0, 0);
}
```
- Look at the screen and listen.

### Expected Behavior

The title is set.

### Actual Behavior

- Terminal *beeps* and prints the string *on the screen*. [MSDN](https://docs.microsoft.com/en-us/windows/console/setconsoletitle) doesn't mention any such visual or sound effects.
- The console title is not set, yet the function returns TRUE.

This is true for other C1 characters as well, not only 0x80.

P.S. The example is not synthetic: these characters can appear in directory and file names and applications can display the current path, the name of the opened file etc. in the console title.

**Comment by j4james** [comment]
I can't reproduce this in conhost - even a current build of OpenConsole - so I _think_ this one is actually just a conpty issue. It looks like we sanitize the string before passing it through, but only strip out C0 controls and not C1 controls. See here:
https://github.com/microsoft/terminal/blob/b3775bc2b0b46f9bca873594d47a739223211f21/src/host/getset.cpp#L1929-L1945
