### ISSUE TITLE
Run Terminal as another user

### ISSUE THREAD

**Issue by eglyn** [microsoft/terminal#10316]
Hi all, 

is there a way to launch a new tab with a different user ? 
We have differents username for a same user (with differents privileges), and we need to launch some ps command with another user than the current user.
The only way I found is to create another profile with the following command line: 
```
"commandline": "C:\\Windows\\System32\\runas.exe /savecred /user:domain\\anotherlogin powershell.exe",

```
But, it opens another windows PS, that is not a terminal windows, so with no split screen option, etc...

So is there a way to open a new tab with this user instead a new PS window ? 

Thx !

**Comment by rosettet** [comment]
If you are using Remote Management then you can specify a config file for each profile by adding -config /path/to/file to the end of the command line by using the '-config' flag.
You can even run custom commands to change profile on startup by adding the '-noexit' and '-command' tags to the end of the command line.
![image](https://user-images.githubusercontent.com/79660359/120690180-814fcc00-c46a-11eb-92a9-c18a19ba447f.png)
![image](https://user-images.githubusercontent.com/79660359/120690306-a80e0280-c46a-11eb-894a-178f0264f88c.png)
In your case (assuming wt is in your path) your Command Line may be:
C:\Program Files\PowerShell\7\pwsh.exe -noexit -command /savecred /user:domain\\anotherlogin wt.exe

**Comment by eglyn** [comment]
Yes thx it works ! with this command line: 
"commandline": "powershell -noexit -command runas /savecred /user:domain\\username wt.exe",

**Comment by eglyn** [comment]
I found a workarround, but not really perfect: 
- Download the last version 1.9
- extract the bundle with 7zip
- extract the x64 msix
- in the command line of WT this command: 
"commandline": "powershell -noexit -command runas /savecred /user:domain\\user-c C:\\WT\\WindowsTerminal.exe",

it opens another WT with privilege account, not really in the same tab, but it is WT, so I can open new tab with privileges accounts

**Comment by zadjii-msft** [comment]
I'm glad you found a workaround! We're not really planning on allowing mixed elevation levels / mixed users within a single terminal Window - there are unfortunately a few security issues with that which we're not willing to ship ourselves. There are more details in the threads linked to #5000.



/dup #2200
