### ISSUE TITLE
horizontal scroll gesture on trackpad scrolls viewport vertically

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#10329]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Steps to reproduce

with some scroll back on the buffer do a horizontal 2-finger swipe on the trackpad

### Expected Behavior

do nothing

### Actual Behavior

vertical scroll is performed

very annoying if your vertical scroll gesture looks like this:
![image](https://user-images.githubusercontent.com/43626415/120743986-6c0d8880-c4d0-11eb-81cf-e9b4f12004bc.png)

**Comment by zadjii-msft** [comment]
Yep, that's a real bug. Thanks!
