### ISSUE TITLE
Profile picker goes outside window during scrolling in settings screen

### ISSUE THREAD

**Issue by dtrailin** [microsoft/terminal#10325]
### Windows Terminal version (or Windows build number)

 1.8.1444.0

### Steps to reproduce

Go to the settings page. Then select the default profile picker and scroll down.

### Expected Behavior

I expect the picker to stay inside the terminal window.

### Actual Behavior

It looks like this:
![image](https://user-images.githubusercontent.com/1897547/120725396-b5d38000-c48a-11eb-9131-41b470cd9cb3.png)
****

**Comment by skyline75489** [comment]
Thanks for the feedback. This is a known issue. Please see #9320
