### ISSUE TITLE
New color schema request

### ISSUE THREAD

**Issue by ismailhkose** [microsoft/terminal#10324]
# Description of the new feature/enhancement
Can you add this color schema to default theme list?
https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/raspberry-ubuntu

Ubuntu users usually are very familiar with this color schema in gnome terminal. I usually add this myself after every reinstalling Windows Terminal. I would be happy if this become part of the package.

# Proposed technical implementation details (optional)

**Comment by mdtauk** [comment]
I do this also for my Ubuntu profile, it's quite distinctive and so should probably be included or added to the list when Ubuntu is detected.

**Comment by skyline75489** [comment]
I don’t think we accept new default schemes now but it is actually possible for WSL installation to provide this color scheme using [fragments](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions).

**Comment by ismailhkose** [comment]
I would prefer that ubiquitous theme to be part the package other than adding it on every installation. That's the reason of the ask. For now, I have already added it to JSON file.

It would be helpful to make it part of the color shema list.

**Comment by WSLUser** [comment]
We already have Tango Light and Tango Dark for Ubuntu. That's just an example color scheme. The most you could do is ask the WSL Ubuntu maintainers to publish a fragment when installing Ubuntu and detecting that Windows Terminal is installed but I'm guessing it'll be a no.

**Comment by zadjii-msft** [comment]
You know, I'm gonna reject this. We've got plenty of good color schemes as is, and plenty of bad ones. I don't think we should really be in the business of adding any more ourselves, tbh. Ubuntu can add this scheme themselves if they want with a fragment (and I believe that they intend to). 

If they don't, then it's really not _that much work_ to copy-pasta the scheme to your settings, if that's what you want.

Thanks for the suggestion though!
