### ISSUE TITLE
Split Screen

### ISSUE THREAD

**Issue by PizzaRules668** [microsoft/terminal#10327]
# Description of the new feature/enhancement

Being able to split the screen into multiple terminals

**Comment by skyline75489** [comment]
You mean [panes](https://docs.microsoft.com/en-us/windows/terminal/panes)?

**Comment by lord88d** [comment]
- [ ]
M_[]()_

**Comment by soroshsabz** [comment]
related to #1000

**Comment by lord88d** [comment]
> - [ ]
> M_[]()_

- - [ ]

**Comment by DHowett** [comment]
I would like to encourage you to stop whatever weird thing it is that you're doing.

**Comment by DHowett** [comment]
@PizzaRules668 thanks for the request! You cna split panes using alt+shift+- and alt+shift+plus (on a US-English keyboard). You can see the exact key bindings by opening the Command Palette (Ctrl+Shift+P) or the Action Editor (1.9+ only; Settings > Actions)
