### ISSUE TITLE
Acrylic  not working

### ISSUE THREAD

**Issue by kideas11** [microsoft/terminal#10333]
i try all method check my code re write code. use settings. enable gpu increase opacity but transprancy not  working

**Comment by skyline75489** [comment]
What are you expecting about “transparency”? Acrylic is not transparency. A screenshot would be nice.

**Comment by kideas11** [comment]
> What are you expecting about “transparency”? Acrylic is not transparency. A screenshot would be nice.

then how i achive transrarency with blur effect. its full black

**Comment by skyline75489** [comment]
What have you tried so far. Can you share a screenshot of what you have now?

**Comment by kideas11** [comment]
![image](https://user-images.githubusercontent.com/84661890/120955504-f7a24600-c76a-11eb-9cb9-eecce5454322.png)
here is image

**Comment by innocent-ghost** [comment]
Please any one reading this email please I beg you with the name of any
thing you worship please help me out with $200 am dieing but you can save a
life by helping me out I will really appreciate if my request are granted
am the one innocent, you can send me the money through Bitcoin, this my
Bitcoin wallet address 3HUj5eE3DApm6tW68aDVJMfrAUij2oTXD2 God bless you

**Comment by zadjii-msft** [comment]
Please check the [FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-does-acrylic-not-work). If acrylic works in Calculator but not the terminal, I'd definitely be surprised.

**Comment by kideas11** [comment]
i try all methods but nothing work if you want more you surely assit me using windows quick assist

**Comment by zadjii-msft** [comment]
Okay sorry, could you confirm that acrylic is working in the Calculator app?
