### ISSUE TITLE
Bug Report: cursor disappear after using Zhuyin (Traditional Chinese) input method

### ISSUE THREAD

**Issue by Po-wei** [microsoft/terminal#1033]
# Environment

Windows build number: Windows Version 10.0.18362.116

# Steps to reproduce
Use Cmd or WSL console.
If I switch to Zhuin input and type any character,
![image](https://user-images.githubusercontent.com/17596021/58459717-a19f6e80-815e-11e9-9286-5a3fcd690f53.png)
![image](https://user-images.githubusercontent.com/17596021/58459853-ea572780-815e-11e9-962a-e211cdc62c14.png)

Then, switch back to english input and my cursor disappear.
![image](https://user-images.githubusercontent.com/17596021/58460733-ce548580-8160-11e9-9668-c4620e4e8118.png)

# Expected behavior
![image](https://user-images.githubusercontent.com/17596021/58460829-f5ab5280-8160-11e9-9b1d-c8108ae64654.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/17596021/58460718-c85ea480-8160-11e9-83a1-2efc25b3a8c8.png)

**Comment by metathinker** [comment]
Could this be the same issue as #810?

**Comment by zadjii-msft** [comment]
It's very possible that those are the same issues. I'll let make @miniksa make the call

**Comment by miniksa** [comment]
It'll be the same problem. Resolving as duplicate.
