### ISSUE TITLE
Optional Splash / New Tab Page

### ISSUE THREAD

**Issue by coderforlife** [microsoft/terminal#10338]
# Description of the new feature/enhancement

When opened normally (without being given a specific directory or other command), it would be nice to have Windows Terminal open with a "splash page" that would allow one to select which terminal to open. Upon selecting one the splash tab would be replaced with that terminal. This would be instead of opening the default terminal.

The default terminal would still be used for things like right-clicking in a directory and choosing "Open in Windows Terminal".

Additionally, the new-tab button could be set to display this splash screen instead of the default terminal. This is akin to the "Home Page" concept in opening browser tabs, where they can be chosen to open a specific page (terminal) or a generic "home page" (i.e. the choose-which-terminal page).

The reason for all of this is that I mainly use Windows Terminals that are remote with no concept of "default". I rarely use a local terminal unless I choose to open one in a specific local directory.

**Comment by WSLUser** [comment]
That might be best added to something like Project Honolulu. Maybe as an extension though not sure how that would work considering you'd to keep track of all remotely installed instances of Windows Terminal. FWIW you can set the default shell/profile for each remote Windows Terminal as the default. But that's different than choosing which remote WT host to connect to by default.

**Comment by DHowett** [comment]
> That might be best added to something like Project Honolulu

I can always count on you to think of the most out-of-this-world solution to our feature requests.

**Comment by coderforlife** [comment]
When I said remote, I didn't mean the Windows Terminal sessions themselves were remote but that I primarily use terminal to SSH to Linux machines. Each of my profiles is like ssh.exe <machine-name>. I have a few other random ones like an IPython terminal and the typical local cmd and powershell ones.

This could be almost done by making a gui-like terminal program (using old school box drawing) and making that the default but somehow detecting when opening from the context menu as "Open in Windows Terminal" and then doing something different. But that isn't clickable...

I imagine with this set it would provide a screen like this:

![image](https://user-images.githubusercontent.com/1537688/121054420-52976580-c78a-11eb-8f63-6dbaf618a0fb.png)

except with the profiles listed out and not webpages... that screen would be used when a new terminal is opened (not from the context menu) or a new tab is requested.

**Comment by WSLUser** [comment]
You can create your own ssh profiles that run ssh.exe directly. https://docs.microsoft.com/en-us/windows/terminal/tutorials/ssh is the how-to for creating a ssh profile.  You can create as many as you want and are available from the drop down menu. Additionally a keybinding can be assigned so you can quickly launch a new tab or pane with a different ssh profile.

**Comment by coderforlife** [comment]
I already have those profiles. What I want it a nice little GUI for selecting them upon creating a new tab or when opening up the terminal. The selection screen would just list off the same profiles that the drop-down menu shows. It wouldn't try to invent anything on its own (like the browser ones might). It would just take the names and icons of the profiles, show them in boxes like that, and then when clicked set the profile being used by that tab (or if easier, open a new tab with that profile and close the splash screen tab).

A really advanced one (which I did not think about until right now) could be customizable with boxes that you could like enter an SSH command line to open or whatever, but as I said, that wasn't what I was expecting.

**Comment by mdtauk** [comment]
At the moment there is UI to select a Default Profile.
![image](https://user-images.githubusercontent.com/7389110/121375839-f292f180-c938-11eb-9711-0a3cb631dfbf.png)

If you did have a "New Tab" page, this could be where you set it, and then profiles are displayed.

Future new features could live here too maybe?  Resume a paused session? Shortcuts to run saved commands or scripts? "Find new Colour Schemes" button, Export settings, etc

**Comment by WSLUser** [comment]
SO this is now a UI issue and sounds like a great extension Idea once extension support includes custom UI for things like this.

**Comment by coderforlife** [comment]
@mdtauk I already have those profiles. What I want it a nice little GUI for selecting them upon creating a new tab or when opening up the terminal. The selection screen would just list off the same profiles that the drop-down menu shows. It wouldn't try to invent anything on its own (like the browser ones might). It would just take the names and icons of the profiles, show them in boxes like that, and then when clicked set the profile being used by that tab (or if easier, open a new tab with that profile and close the splash screen tab). A really advanced one (which I did not think about until right now) could be customizable with boxes that you could like enter an SSH command line to open or whatever, but as I said, that wasn't what I was expecting.

@WSLUser extensions that support UI sounds good - there should be a new option in settings for "New Tab" which gives options: default profile and then anything registered by extensions.

**Comment by zadjii-msft** [comment]
Alright before this thread gets more off topic: we're tracking a very similar request in #3586. That one specifically mentions "panes", but obv we'd make that work for tabs too.

/dup #3586
