### ISSUE TITLE
Show-Command popup behind wt window instead of getting focus.

### ISSUE THREAD

**Issue by freMea** [microsoft/terminal#10345]
### Windows Terminal version (or Windows build number)

wt 1.8.1444.0 | Windows 10 x64 10.0.19041.0 | pwsh 7.1.3

### Steps to reproduce

Run command like `Show-Command Get-ChildItem`

### Expected Behavior

When this command is run in console, the popup gets focus.
(This is animated gif, click on it if it doesn’t animate)
![console](https://user-images.githubusercontent.com/22337329/120889082-d53dea80-c5fb-11eb-8e2e-ded3616715b5.gif)

### Actual Behavior

When the same command is run in wt, the popup doesn’t get focus and is behind wt window.
(This is animated gif, click on it if it doesn’t animate)
![wt](https://user-images.githubusercontent.com/22337329/120889079-d3742700-c5fb-11eb-83f3-37aa52f0896d.gif)

**Comment by KalleOlaviNiemitalo** [comment]
That's <https://github.com/microsoft/terminal/issues/2988>, unfortunately difficult to fix.

**Comment by freMea** [comment]
> That's #2988, unfortunately difficult to fix.

For me, only cmdlet using GUI like `Show-Command Get-ChildItem` or `Get-ChildItem | Out-GridView` open behind the terminal. For now no issue while opening external app like `code $Profile` or `start .`

**Comment by freMea** [comment]
Interesting thing. If I use an alternative Out-GridView cmdlet from [here](https://devblogs.microsoft.com/powershell/out-gridview-returns/), the GUI opens in front.

**Comment by skyline75489** [comment]
Thanks guys for the report. I'll close this and redirect the discussion to #2988 .
