### ISSUE TITLE
German keyboard alt+ctrl doesnt work with some symbols

### ISSUE THREAD

**Issue by GodShin** [microsoft/terminal#10349]
### Windows Terminal version (or Windows build number)

 10.0.19042.0, 1.8.1521.0

### Steps to reproduce

On German (qwertz) Keyboard: Windows Terminal (Powershell, Ubuntu,...) Ctrl+Alt with 7, 8, 9 doesn't return { , [ and ] like AltGr. It returns nothing

### Actual Behavior

Ctrl+Alt with 7, 8, 9 doesn't return { , [ and ] like AltGr. It returns nothing

**Comment by KalleOlaviNiemitalo** [comment]
There is the [`altGrAliasing`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#altgr-aliasing) setting. The default value is apparently `true` but perhaps your `settings.json` changes it.

Does Ctrl+Alt work as Alt Gr with any other keys?



Does

**Comment by GodShin** [comment]
Yes, it works with 0 to }, with + to ~ and with < to | as well as with Q to @ 

The problem seems to be only with 7, 8, 9

**Comment by skyline75489** [comment]
CC @lhecker

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps the default `switchToTab` bindings take precedence.

<https://github.com/microsoft/terminal/blob/6617eb33ac640fcebad520bd94e53c11cf2e05fe/src/cascadia/TerminalSettingsModel/defaults.json#L322-L330>

**Comment by lhecker** [comment]
Yep this is a case of https://github.com/microsoft/terminal/issues/7177 and can be fixed like so:
```json
"actions":
[
    { "command": "unbound", "keys": "ctrl+alt+1" },
    { "command": "unbound", "keys": "ctrl+alt+2" },
    { "command": "unbound", "keys": "ctrl+alt+3" },
    { "command": "unbound", "keys": "ctrl+alt+4" },
    { "command": "unbound", "keys": "ctrl+alt+5" },
    { "command": "unbound", "keys": "ctrl+alt+6" },
    { "command": "unbound", "keys": "ctrl+alt+7" },
    { "command": "unbound", "keys": "ctrl+alt+8" },
    { "command": "unbound", "keys": "ctrl+alt+9" }
]
```

The fact that `Ctrl+Alt+<num>` is used to switch tabs might be considered an unfortunate choice from the past, but we currently stick with it, in order to not break the workflow for users who're already used to that.

And due to that I'd like to take the liberty to close this issue for now. 🙂

**Comment by KalleOlaviNiemitalo** [comment]
Would it make sense to:

1. Change the default value of `altGrAliasing` from `true` to `false`.
2. Not define any ctrl+alt key bindings by default if the user configures `"altGrAliasing": true`.

**Comment by lhecker** [comment]
@KalleOlaviNiemitalo Unfortunately this would drastically change the behavior of the AltGr key in Windows Terminal. For a very brief period of time `altGrAliasing` was (basically) false in the past and people were upset with it. For instance: https://github.com/microsoft/terminal/issues/5525
It would also make WT's text input behave entirely different to all other Windows applications. As such it's not possible to set `altGrAliasing` to false by default.

**Comment by innocent-ghost** [comment]
Please any one reading this email please I beg you with the name of any
thing you worship please help me out with $200 am dieing but you can save a
life by helping me out I will really appreciate if my request are granted
am the one innocent, you can send me the money through Bitcoin, this my
Bitcoin wallet address 3HUj5eE3DApm6tW68aDVJMfrAUij2oTXD2 God bless you
