### ISSUE TITLE
Quake mode hot-key stops working after a while.  Restart of terminal fixes it

### ISSUE THREAD

**Issue by aclinick** [microsoft/terminal#10340]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Steps to reproduce

Run terminal preview.  leave it in the background.  Go do something else for a while - say 30 mins.  Hit Win-` and notice how the quake sweetness has been obliterated (by a BFG perhaps?)  Restart terminal and quake goodness is back

### Expected Behavior

quake mode all the time....

### Actual Behavior

no quake sweetness

**Comment by zadjii-msft** [comment]
Well, that's definitely not expected. I'm assuming "do something else for 30 minutes" is basically just the same as "something causes the keybinding to stop working". As long as the Terminal is running, the keybinding _should_ work. We never unregister the hotkey (except on a settings reload), so there's no reason that the global hotkey should ever become unbound.

I'm not sure what kind of tracing we could get that would be valuable here. I suppose we could add tracing for when we _do_ get a hotkey message, but that would only really tell us if the hotkey was pressed, but we decided not to open an instance. I'm more worried that this is "we never got the hotkey message".

I'd welcome other input on this topic - as is, I'm not sure how to investigate this further.

**Comment by zadjii-msft** [comment]
@aclinick You still seeing this? We haven't really had any other reports of this, so I suspect it was just an intermittent issue on your machine. We might have some logging you can do if it is still happening with relative frequency.
