### ISSUE TITLE
WSL profile is not showing up

### ISSUE THREAD

**Issue by nt4f04uNd** [microsoft/terminal#10348]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19041.985]

### Other Software

WSL

```
C:\>wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Stopped         2
```

### Steps to reproduce

Add such entry for WSL in profile

```json
            {
                "guid": "{9acb9455-ca41-5af7-950f-6bca1bc9722f}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            }
```

### Expected Behavior

See the profile showing up.

As far as I know WSL should be detected and created automatically, meaning that the entry above should be always there (see https://github.com/microsoft/terminal/issues/3231#issuecomment-542966078), but this doesn't happen for some reason 

### Actual Behavior

Nothing happens

**Comment by nt4f04uNd** [comment]
This instance was created by docker-desktop.
I changed my default WSL instance to Ubuntu and now it's working just fine

**Comment by skyline75489** [comment]
I don't know the detail of this but I think docker-desktop related distros are not intended for usage outside docker.

**Comment by DHowett** [comment]
Correct. These distributions are an internal implementation detail of the Docker Desktop service. They are not intended to be used.

**Comment by innocent-ghost** [comment]
Please any one reading this email please I beg you with the name of any
thing you worship please help me out with $200 am dieing but you can save a
life by helping me out I will really appreciate if my request are granted
am the one innocent, you can send me the money through Bitcoin, this my
Bitcoin wallet address 3HUj5eE3DApm6tW68aDVJMfrAUij2oTXD2 God bless you

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/3556> was the request to hide the docker-desktop distros.
