### ISSUE TITLE
Cannot change font Icon size when using oh-my-posh

### ISSUE THREAD

**Issue by TimilsinaBimal** [microsoft/terminal#10343]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Other Software

Oh-my-Posh 3.159.0

### Steps to reproduce

Download and apply any oh-my-posh theme in the terminal with PowerShell.

### Expected Behavior

The icon size must be the same as that of the terminal font-size
![image](https://user-images.githubusercontent.com/45899783/120880794-1d551100-c5ec-11eb-8caa-677113c04a0e.png)

Icon size in VS Code integrated terminal

### Actual Behavior

The icon size is small as compared to the font size and even the icon is not showing fully as shown below:
![image](https://user-images.githubusercontent.com/45899783/120880832-64db9d00-c5ec-11eb-84a2-23f5c241cfb4.png)

**MY Terminal Settings**
```json
{
                "acrylicOpacity": 0.82999999999999996,
                "altGrAliasing": true,
                "antialiasingMode": "cleartype",
                "backgroundImage": null,
                "backgroundImageOpacity": 0.40000000000000002,
                "colorScheme": "Blue Matrix",
                "commandline": "pwsh.exe -nologo",
                "cursorShape": "bar",
                "experimental.retroTerminalEffect": false,
                "fontFace": "SFMono Nerd Font",
                "fontWeight": "medium",
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "startingDirectory": "%USERPROFILE%",
                "suppressApplicationTitle": false,
                "tabTitle": "PowerShell",
                "useAcrylic": true
            }
```

**Comment by skyline75489** [comment]
Related: #900 #5095
