### ISSUE TITLE
Windows Terminal 1.8.1521.0 Breaks wt.exe

### ISSUE THREAD

**Issue by richardcox13** [microsoft/terminal#10346]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Start | Run | wt <enter>

and get popup with 

> [Window Title] C:\Users\richard\AppData\Local\Microsoft\WindowsApps\wt.exe

> [Content]
> Windows cannot find 'C:\Users\richard\AppData\Local\Microsoft\WindowsApps\wt.exe'. Make sure >you've typed the name correctly, then try again.

Running from an open Windows Terminal tag with PowserShell 7.1.3 reports

> ResourceUnavailable: Program 'wt.exe' failed to run: The system cannot find the file specified.At line:1 char:1
> \+ wt
> \+ ~~.

This is immediately after the Windows Store pushed a new build (previously was running 1.8 as released 2021-05-21.

(Opening from the shortcut pinned to my task bar works correctly.)

### Expected Behavior

A new Windows Terminal window is opened with my default profile loaded.

### Actual Behavior

See steps to reproduce.

**Comment by richardcox13** [comment]
The problem appears to be the link `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe` has not been updated, it exists but links to `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\wt.exe` rather than `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe\wt.exe`.

**Comment by smaug9** [comment]
I'm getting a similar error. 

1. It looks like the `wt.exe` link in my user directory points to the wrong `wt.exe` in the `c:\program files\windowsapps`. 
2.  Additionally, it seems that my user doesnt have permissions to read/execute `wt.exe` in the `c:\program files\windowsapps`.

```
> dir C:\users\jeff\appdata\local\microsoft\WindowsApps\wt.exe

    Directory: C:\users\jeff\appdata\local\microsoft\WindowsApps

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          2021-04-17    11:46              0 wt.exe -> C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe\wt.exe
```


```
C:\>"c:\program files\windowsapps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe\wt.exe"
Access is denied.
```

**Comment by bikeoid** [comment]
I was able to resolve this by turning the App Execution Alias for WT off then on following the screen at https://stackoverflow.com/a/66539884/1743

**Comment by richardcox13** [comment]
In the end I tried a repair: and that worked (after a logoff/on and then a reboot had not).

It is annoying when Windows Terminal is restarted on me (all the state, history, and output lost) especially when I cannot quickly restore things.

**Comment by EdSF** [comment]
> I was able to resolve this by turning the App Execution Alias for WT off then on following the screen at https://stackoverflow.com/a/66539884/1743

@bikeoid Confirmed. Thank you!

**Comment by sairaghavak** [comment]
I know op is talking about version 
> Windows Terminal version 1.8.x

But, just in case if anyone has trouble with Preview version
> 1.9.1523.0

Initially after windows update
Couldn't open  windows terminal from 
> start -> run -> wt

In my case, after checking the Manage app execution aliases, Windows Terminal app is already turned on
After turning it off and on, and a round of restart worked for me.

**Comment by zadjii-msft** [comment]
FYI, this is something that can break basically any time the Terminal is updated. We're working with the platform team to try and get that fixed. see also: https://github.com/microsoft/terminal/issues?q=is%3Aissue+label%3ACulprit-Centennial, #9452

Thanks all!
