### ISSUE TITLE
"FISH"/autosugesstions/history

### ISSUE THREAD

**Issue by Chaython** [microsoft/terminal#10356]
# Description of the new feature/enhancement
Add an autofill and ongoing history/allow restoring of last session. An example I give is FISH https://fishshell.com/

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
This is a bunch of shell features. Are your suggesting for PowerShell?

**Comment by Chaython** [comment]
No I want terminal to have a persistent session, with logging, using the logging and known commands to offer autosuggestions. Many commands work both in powershell and cmd.

**Comment by skyline75489** [comment]
OK understood. I'll close this and redirect the discussions to existing threads #3121 and #6632. Thanks for requesting!
