### ISSUE TITLE
Sync settings

### ISSUE THREAD

**Issue by parthopdas** [microsoft/terminal#10352]
# Description of the new feature/enhancement

Sync settings would be a good feature to have, similar to VSCode

# Proposed technical implementation details (optional)

I have multiple machines and wish to move around why keeping the terminal settings same. Right I export the json and import it back. Which works great. But a sync settings will be even better.

PS: Thanks for creating this incredible thing.

**Comment by KalleOlaviNiemitalo** [comment]
A similar feature was requested in <https://github.com/microsoft/terminal/issues/2933>.

**Comment by skyline75489** [comment]
Thanks for the feedback. I'll close this and redirect all discussions to #2933.

**Comment by innocent-ghost** [comment]
Please any one reading this email please I beg you with the name of any
thing you worship please help me out with $200 am dieing but you can save a
life by helping me out I will really appreciate if my request are granted
am the one innocent, you can send me the money through Bitcoin, this my
Bitcoin wallet address 3HUj5eE3DApm6tW68aDVJMfrAUij2oTXD2 God bless you
