### ISSUE TITLE
Unclear wording: "Open JSON file"

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#10354]
### Windows Terminal version (or Windows build number)

10.0.19041.985

### Steps to reproduce

Open settings

### Actual Behavior

Not clear what "Open JSON file" means.

If it said "Open JSON settings file" or "Open settings.json file", it would be much clearer.

I was quite surprised to see a very generic "Open JSON file" function in the settings when I just opened it for the first time

**Comment by WSLUser** [comment]
I always found it intuitive. The json file clearly mean it was for settings or it would be presented as an option. If you want something more specific then it would be "Open settings.json".

**Comment by vadimkantorov** [comment]
Yep, "Open settings.json" would be clear that it's talking about precise settings.json, not just some arbitrary-format JSON format.

It also should be clear what "Open settings.json" does. Does it open the current settings.json in a text editor? Or will it show a file dialog for opening pre-saved settings.json (e.g. for import of settings from another machine)?

**Comment by DHowett** [comment]
There's limited space. Do you want it to say "Open the settings document, which is actually a JSON file called settings.json, in a text editor, so that you might observe its raw structure?"

**Comment by vadimkantorov** [comment]
I want the button text to indicate clearly what it does. Currently it says very generic "Open a JSON file"

There are at least two legitimate functions to be expected in this context:
- open an external user-provided settings.json (file dialog)
- open a current settings.json (text editor)

I'm sure one can find a concise enough wording much shorter than your proposal, e.g. "Open active settings.json"

But I'm not a native English speaker, so I don't take responsibility for telling actual native speakers what the exact wording should be. I'm sure other people would have better ideas.

**Comment by KalleOlaviNiemitalo** [comment]
> open an external user-provided settings.json (file dialog)

In the old days, that one would have a label ending with an ellipsis ("Open JSON file…") because it must ask for more information before it can do what it says. But I don't know if Microsoft has changed its guidelines since then.

**Comment by DHowett** [comment]
After a long discussion with the team, we realized that there's a tooltip that explains what it does. While I agree that the "Open" verb typically means "get external content into my application," we're choosing to accept the tooltip as a disambiguator.

Thanks/sorry!
