### ISSUE TITLE
Defterm launches into quake window

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#10358]
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

* Launch Windows Terminal Preview and ensure Terminal Preview is set as your default terminal
* Open a quake window
* Dismiss quake window with `Win+\``
* Close initial terminal window
* Launch a ps1 file from file explorer

Since the quake window is the only open Terminal window, defterm launches into that instead of creating a new terminal instance.

### Expected Behavior

A new terminal instance is created.

### Actual Behavior

The quake window is opened and attempts to run the selected file.

**Comment by miniksa** [comment]
I think #9475 might technically fix this as I believe the quake one won't allow other tabs to join it normally if dispatched through remoting...
