### ISSUE TITLE
"About" dialog backdrop does not scale with window resizing.

### ISSUE THREAD

**Issue by Tropix126** [microsoft/terminal#10351]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

 None

### Steps to reproduce

1. Open terminal.
2. Navigate to the dropdown next to the "New Tab" button.
3. Open the "About" dialog.
4. Resize the window.

### Expected Behavior

The ContentDialog backdrop should properly scale with the window.

### Actual Behavior

The ContentDialog backdrop keeps the static dimensions of the window when it was first opened and does not resize accordingly.

![image](https://user-images.githubusercontent.com/42101043/120943672-fedb3c80-c6f5-11eb-851b-f43706e59b63.png)

**Comment by skyline75489** [comment]
Thanks for the report! 

This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion.
