### ISSUE TITLE
Windows Search

### ISSUE THREAD

**Issue by Chaython** [microsoft/terminal#10355]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

Windows 10 21h1

### Steps to reproduce

[win] + [s], "terminal"

### Expected Behavior

Show window terminal [for me it doesn't show up at all in windows search, let alone at top.] (would also be nice to replace Command prompt in start context menu]

### Actual Behavior

Shows command prompt, node.js, random folders and files with terminal in their details....

**Comment by DHowett** [comment]
Yeah, this one has plagued us forever. We're actively working with the team who owns Start Menu search to get Terminal prioritized :smile:

**Comment by DHowett** [comment]
(Thanks for the request!)

**Comment by Chaython** [comment]
It seems to be an issue with Windows store apps in general, even if you go to shell:AppsFolder and manually create a shortcut, and paste it in the only indexed directory, it still ignores windows terminal.
