### ISSUE TITLE
ConPTY seems to have trouble with full-screen background resets?

### ISSUE THREAD

**Issue by nolemretaWxd** [microsoft/terminal#1036]
# Environment

```none
Windows build number: 10.0.18362.116

Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Start cmd tab
color [any color with bg]
color [not supported]

# Expected behavior

Bg should change

# Actual behavior
![colors](https://user-images.githubusercontent.com/31414969/58491230-ea5f2380-816e-11e9-91d3-f65d490ff351.png)

**Comment by zadjii-msft** [comment]
Could you more accurately fill out the expected and actual behavior? I'm not sure if what you've posted is the actual behavior or the expected behavior, and if it is the actual behavior, what you expect it to look like (or vice versa)

**Comment by WatermelonPL** [comment]
Now it's ok?

**Comment by DHowett-MSFT** [comment]
Can you share the *exact* commands you are using?

**Comment by WatermelonPL** [comment]
Commands:
1. color fc
2. (any, color is an example)
