### ISSUE TITLE
Couldn't resolve using "Can't use SSH with Powershell #4682"

### ISSUE THREAD

**Issue by N8TVTXN** [microsoft/terminal#10366]
I've read through the above mentioned case and I am still having issues running ssh in powershell. I setup the filters within ProcessMonitor and after setting the "path" filter, it doesn't show any log information. I've installed OpenSSH and confirmed it is running, however when trying to ssh to my Linux box, I receive the following message;

ssh : The term 'ssh' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and
try again.

If someone could help or point me to another case for resolution, I'd be very happy.

Thank you.

P.S. I am new to Linux. MS user since 1996 and Apple since 2006

**Comment by DHowett** [comment]
Sure! Can you share the output of (from powershell...) `Get-Item Env:/PROCESSOR*`?

**Comment by N8TVTXN** [comment]
Sorry. Forgot bout this thread and I’ve rebuilt the system.

**Comment by DHowett** [comment]
No problem. Thanks for getting back to us! Since the repro case is gone, I'm gonna close out this issue. Let us know if there's anything else ~ ~ strange ~ ~ going on.
