### ISSUE TITLE
Aliased (sharp) text while ClearType is on!!!

### ISSUE THREAD

**Issue by Farhankhosravi** [microsoft/terminal#10364]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

taking screenshots

### Expected Behavior

Microsoft store screenshot:
![Screenshot (110)](https://user-images.githubusercontent.com/77070895/121184980-daf53380-c87a-11eb-9cda-123c902a3115.png)

### Actual Behavior

Hi, i have latest versions of terminal and windows 10.
my app shows texts aliased, as you see in this picture:
![Screenshot (109)](https://user-images.githubusercontent.com/77070895/121185180-0d069580-c87b-11eb-80b0-c1c25874b2b7.png)
but i am turned on ClearType in all of my profiles!! compare my terminal picture with Store screenshot...
what's the problem? it's very hard to use terminal like this...

**Comment by DHowett** [comment]
I'm sorry, there must be something up with your screenshot. This looks **very antialiased** to me.

![image](https://user-images.githubusercontent.com/189190/121234061-ee8fa280-c858-11eb-8f16-75e281afa3f3.png)

For comparison, this is what aliased text looks like (no blurry edges):

![image](https://user-images.githubusercontent.com/189190/121234270-25fe4f00-c859-11eb-99e7-35b32e34c978.png)

**Comment by AnuthaDev** [comment]
@DHowett Maybe the issue is grayscale vs subpixel antialiasing🤔
