### ISSUE TITLE
can not find font "Cascadia Code ExtraLight"

### ISSUE THREAD

**Issue by FANGOD** [microsoft/terminal#10360]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

Windows Terminal
版本: 1.8.1521.0

### Steps to reproduce

Open a window and show tips. 
And failure to reinstall.

### Behavior

![b66c133f73edbde96c2aacff3bc2f6e3](https://user-images.githubusercontent.com/21952721/121114101-b6cb2f80-c845-11eb-8413-50c9173561fd.png)

![10f16efc4c64ae2595c9640b02630d4a](https://user-images.githubusercontent.com/21952721/121114276-0578c980-c846-11eb-94d6-cbed6d9edfe9.png)

![982420694c8f5bb5bef20ae7d4690e4a](https://user-images.githubusercontent.com/21952721/121114192-deba9300-c845-11eb-9549-a908110151c0.png)

**Comment by skyline75489** [comment]
For the font, you may want to try:

```json
{
 "fontFace": "Cascadia Code",
 "fontWeight": "extra-light",
}
```

**Comment by FANGOD** [comment]
> For the font, you may want to try:
> 
> ```json
> {
>  "fontFace": "Cascadia Code",
>  "fontWeight": "extra-light",
> }
> ```

Thanks, I uninstall and reinstall solved it
