### ISSUE TITLE
Latest store update `1.8.1521.0` caused problems with the installed preview Terminal

### ISSUE THREAD

**Issue by kapsiR** [microsoft/terminal#10363]
### Windows Terminal version (or Windows build number)

10.0.19042.0, 1.8.1521.0

### Other Software

Windows Terminal Preview

### Steps to reproduce

Yesterday I got a new Windows Terminal update via the store:  
![grafik](https://user-images.githubusercontent.com/7165033/121134774-14ef1700-c834-11eb-8f6d-536b0005e995.png)

My `wt.exe` suddenly pointed to the installed preview version of Windows Terminal instead my default stable one:
I'm using the following shortcut: `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe`

### Expected Behavior

When starting `wt.exe`, the stable Windows Terminal should launch

### Actual Behavior

When starting `wt.exe`, the preview version of the Windows Terminal comes up
Thanks to the different icons I saw it, that the wrong version comes up.

I uninstalled Windows Terminal Preview and installed it again - the problem was gone.

**Comment by DHowett** [comment]
This seems to be another symptom of /dup #10243. Sorry about that.

**Comment by kapsiR** [comment]
> This seems to be another symptom of /dup #10243. Sorry about that.

Thanks for the duplicate hint.  
I think it would be good to pin this information somewhere? It seems there are multiple duplicates already?
