### ISSUE TITLE
Saving in the Settings UI breaks "iterateOn"

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#10365]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Steps to reproduce

I have [written a blogpost](https://www.fesevur.com/2021/02/17/windows-terminal-command-palette/) on how to add the profiles to the command palette.

When I copy-paste the code mentioned on that page directly in `settings.json` everything works as expected.

When I open the Settings UI and press save the key `iterateOn` is deleted, even without changing anything.

For reference, this is a snippet:

```json
{
	"iterateOn": "profiles",
	"icon": "${profile.icon}",
	"name": "${profile.name}: New tab",
	"command": {
		"action": "newTab",
		"profile": "${profile.name}"
	}
}
```

### Expected Behavior

Saving from the Settings UI doesn't remove anything.

### Actual Behavior

Saving from the UI removes the `iterateOn` key-values pair from `settings.json`.

**Comment by DHowett** [comment]
(user settings loss bugs are no joke.)
