### ISSUE TITLE
Powershell input doesn't display Unicode characters correctly

### ISSUE THREAD

**Issue by Nimi142** [microsoft/terminal#10379]
### Windows Terminal version (or Windows build number)

10.0.19043.1052

### Steps to reproduce

- Open a Powershell tab on the Terminal.
- Paste non-Latin characters.
I tried inserting Hebrew, Arabic and Cyrillic letters.

### Expected Behavior

Powershell will show the characters correctly on the input line, like so: `echo היי`.

### Actual Behavior

Powershell shows question marks instead of the Unicode characters, as such: `echo ???`

If I execute the echo command, it does show the Unicode characters correctly in the output. The error only occurs when I am inserting characters into Powershell. The CMD also works correctly.

**Comment by zadjii-msft** [comment]
Which version of powershell are you using? 

Are you using PSReadline? If so, which version? 

I'm 99% sure this is something that's tracked on one of their issue trackers already.

**Comment by Nimi142** [comment]
I'm sorry, I can't tell you as I upgraded to the windows 11 beta and it works now.
