### ISSUE TITLE
Semi-transparent background

### ISSUE THREAD

**Issue by Nicoskin** [microsoft/terminal#10376]
Will there be a semi-transparent background(Acrylic material)? As in the calculator or in the Fluent terminal. I want the design to have a semi-transparent theme.

**Comment by skyline75489** [comment]
You mean [Acrylic](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#acrylic)?

**Comment by mdtauk** [comment]
This is already supported.

![image](https://user-images.githubusercontent.com/7389110/121344588-d92f7c80-c91b-11eb-82c8-91743ef48898.png)

**Comment by Nicoskin** [comment]
skyline75489 yes, I changed it. I hope that this feature will be implemented as in the fluent terminal(in the screenshot above)

**Comment by skyline75489** [comment]
I will close this for now.
