### ISSUE TITLE
Allow User Entered Args in Key Commands

### ISSUE THREAD

**Issue by TheBrenny** [microsoft/terminal#10375]
# Description of the new feature/enhancement

Windows Terminal should implement a feature similar to how user-entered arguments can be entered for Run Configurations in VSCode.

One example would be to have a `newTab` command bound to `ctrl+shift+n`, with the `profile` attribute set to `"${input:getProfile}"` (see the technical example below). A similar example would be splitting panes and selecting `horizontal` or `vertical` from a list.

This would allow for more flexibility within keyboard commands, and open up possibilities for many more interesting and helpful keyboard shortcuts.

# Proposed technical implementation details (optional)

In VSCode's `.vscode/launch.json` file, specifying an `"inputs": []` array and an object within allows you to use that input in the run configuration, such as entering specific arguments. This can be done by using `"${input:foo}"`, where foo is the `id` of an object in `inputs`.

This would allow Windows Terminal users to have a keyboard command like the following:
```json
{
    "command": {
    "action": "newTab",
    "profile": "${input:getProfile}"
    },
    "keys": "ctrl+shift+n"
}
```

where `getProfile` could be defined as:
```json
{
    "id": "getProfile",
    "type": "promptString",
    "description": "Enter a profile name or GUID"
}
```

**Comment by TheBrenny** [comment]
What was the feedback that I needed to provide?

**Comment by zadjii-msft** [comment]
Oh my god, I'm so sorry. I absolutely had a whole response typed up but must have never sent it. My bad!

<hr>

This sounds like exactly something the command palette can already do with "[iterable commands](https://docs.microsoft.com/en-us/windows/terminal/command-palette#iterable-commands)". There's already "New Tab..." commands in the palette that will display a list of profiles for you to pick from. I know that's not as generic as "allow arbitrary arguments", but is that what you're looking for?

**Comment by TheBrenny** [comment]
That solves one half of the problem! 🎉

But I'm also looking for a way to bind this to a key combination. For example, I can bind the single command `newTab` to `ctrl+n`, but having the command palette open to choose a profile bound to `ctrl+shift+n` would be ideal.

**Comment by zadjii-msft** [comment]
@TheBrenny That element of what you're looking for sounds like #10209

/dup #10209
