### ISSUE TITLE
Glitch on tab close

### ISSUE THREAD

**Issue by JekRock** [microsoft/terminal#10378]
### Windows Terminal version (or Windows build number)

1.8.1521.0 and 1.9.1523.0

### Steps to reproduce

1. Open two tabs in the Windows Terminal (it doesn't matter what tabs)
2. Switch to the first tab
3. Close the second tab

### Expected Behavior

When the second tab is closed, the first tab is rendered correctly and has the appropriate size.

### Actual Behavior

When the second tab is closed, the first tab is rendered as if it has double size (it expands to the size of the second tab that was closed).
When the mouse is moved outside of the expanded first tab, the first tab is rendered as a single-size tab.

Before closing the second tab:
![image](https://user-images.githubusercontent.com/5882133/121323599-9fa94200-c918-11eb-8786-d9a386487bcb.png)

After the second tab is closed and the mouse pointer remains at the same location:
![image](https://user-images.githubusercontent.com/5882133/121323705-b9e32000-c918-11eb-93e4-d3d8c0d611cc.png)

After the mouse pointer moves out of the first tab:
![image](https://user-images.githubusercontent.com/5882133/121323842-d5e6c180-c918-11eb-8a81-0dfbcc59e826.png)

I could reproduce this behavior with a different number of tabs. If there are more than two tabs, the issue is reproducible for the last two tabs.

Example for 4 tabs
Before closing the 4th tab:
![image](https://user-images.githubusercontent.com/5882133/121324642-94a2e180-c919-11eb-9701-db8c4261c6b6.png)

Switching to the 3rd tab and closing the 4th:
![image](https://user-images.githubusercontent.com/5882133/121324740-ac7a6580-c919-11eb-8707-973007983f4e.png)

Moving the mouse cursor out of the 3rd tab that was expanded:
![image](https://user-images.githubusercontent.com/5882133/121324844-c74cda00-c919-11eb-9875-8c7043dc85e1.png)

Note that when there are more than 2 tabs all the tabs get expanded.

The issue is reproducible for any Windows Terminal window size.

**Comment by skyline75489** [comment]
I think this is the same issue described in https://github.com/microsoft/terminal/issues/10101#issuecomment-842229537

**Comment by zadjii-msft** [comment]
Yep, this is definitely the same as that one. See also #9822

/dup microsoft/microsoft-ui-xaml#4971

**Comment by JekRock** [comment]
Overlooked that, sorry. Closing the PR
