### ISSUE TITLE
'Duplicate' icon incorrect representation

### ISSUE THREAD

**Issue by torquerrr** [microsoft/terminal#10371]
# Description of the new feature/enhancement

'Duplicate' icon actually looks like 'tri-plicate'.
![image](https://user-images.githubusercontent.com/25992594/121270623-baed6080-c8ca-11eb-9078-610398973e54.png)

# Proposed technical implementation details (optional)

It should show just two layers, not three.

**Comment by zadjii-msft** [comment]
Yea, that would be better, but I think we're unfortunately limited to the [Segoe MDL2 Assets](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font) icons, which I don't believe has a better icon 😕 

/cc @cinnamon-msft to check if there's a better solution, but I don't think so.

**Comment by torquerrr** [comment]
@zadjii-msft 
> if there's a better solution

To create a set of icons just for the Terminal?
