### ISSUE TITLE
Bug Report Cant select text in newly open tab occasionally

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#1038]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18898.1000]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1. Open new tab in flyout menu
2. Try to select text in the newly created tab

# Expected behavior
Text should be selected as normal

# Actual behavior
Terminal doesn't response to mouse dragging occasionally

![Imgur](https://i.imgur.com/0LTBd84.gif)

**Comment by Summon528** [comment]
Hmmm apparently this bug only happens with release configuration

**Comment by DHowett-MSFT** [comment]
Probably fallout from #856.
