### ISSUE TITLE
Provide an option to integrate Windows Terminal into Windows Explorer Ribbon

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#10381]
# Description of the new feature/enhancement

Provide an option to integrate Windows Terminal into Windows Explorer Ribbon as using the context menu every time is very painful. This would improve the user experience a lot.

# Proposed technical implementation details (optional)

Upon adding this, opening the Terminal in the context of a folder from Explorer view is just a click away, no need to open the context menu and look for the Open in Windows Terminal option from long list of applicable items would go away.

**Comment by zadjii-msft** [comment]
Can you provide another example of an app that integrates into the File Explorer ribbon? I wasn't aware that there was any way for an app to do that.

**Comment by KalleOlaviNiemitalo** [comment]
[Extending the Ribbon](https://docs.microsoft.com/en-us/windows/win32/shell/extending-the-ribbon) looks like you cannot add custom buttons to the ribbon of File Explorer. Even if you could, it might still not be possible to host a Windows Terminal window in the [folder view](https://docs.microsoft.com/en-us/windows/win32/shell/nse-works#folder-view) when the folder itself is not provided by Windows Terminal.

**Comment by mdtauk** [comment]
a future Windows version will allow Windows Terminal to be the default.  I assume this includes File Explorer interfaces

**Comment by WSLUser** [comment]
So I could be confused on where the Ribbon is in Explorer but I believe OpenShell modifies it: https://github.com/Open-Shell/Open-Shell-Menu

**Comment by egvijayanand** [comment]
Hope it makes way as part of Windows 11 where Terminal becomes the de facto.

Pass on this request to the team working with the Explorer Ribbon so that it becomes part and parcel of it.

**Comment by zadjii-msft** [comment]
I'm just going to take this thought experiment to it's logical conclusion - if an app can add itself to the ribbon in explorer, then every app that can _will_. Now you've got _two_ places where apps will be adding themselves, and now you've just got two giant lists of applications, where it's hard to find what you're actually looking for. 

If there's overwhelming community demand for this feature, we can revisit this.
