### ISSUE TITLE
Replace class-based XAML converters with bound function converters

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10387]
With the Settings UI, we have had an immense proliferation of class-based xaml converters.

They're pretty heavy, and they clutter the metadata with classes (and, well, clutter our build with idl files!). We also have to keep instances of them laying around for every xaml page that uses them.

We should instead bind more things with [x:Bind Functions](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings)!

Proposal:

Introduce `Microsoft.Terminal.Settings.Editor.Converters` which has static conversion functions on it.
Use them exclusively in the settings editor.
Get rid of all the converter classes.

Evaluate the need for `BindBack` reverse converters. :smile:

**Comment by chingucoding** [comment]
Awesome, thank you @DHowett !

**Comment by chingucoding** [comment]
Out of curiosity, what is "blocking" this? Are there technical reasons or is it just that other things are more important than this?

**Comment by DHowett** [comment]
Nothing at all, just available developer time. :smile:

We've got so much to do, and only so many hours in the work week.

**Comment by chingucoding** [comment]
Ah haha I see, the classical developer problem! Good to know though that it's up for grabs then and not blocked by technical issues!

**Comment by DHowett** [comment]
If you're interested in doing it, I'd be happy to assign you so that someone else doesn't come swoop in and do it! 😁

**Comment by chingucoding** [comment]
I currently have a lot of things on my plate, so I'm not sure when I would get to this. I'll let you know when I have more time and would be able to work this; if someone else wants to work on this, I don't want to block anyone here.

**Comment by chingucoding** [comment]
@DHowett I would like to take a look at this now, feel free to assign this to me :)

**Comment by DHowett** [comment]
Awesome! Thanks :)

**Comment by chingucoding** [comment]
So after working on this and finally realizing how BindBack works, it seems that we will need to modify some models to provide a BindBack function. Is that fine behavior? In that case, should the converters reside in the Settings:Editor project and be shared to other projects?
