### ISSUE TITLE
[DefApp] Handoff to active window causes visibility to be toggled

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10386]
### Windows Terminal version (or Windows build number)

1.9

### Steps to reproduce

From an open Terminal window, `start cmd`

### Expected Behavior

It opens

### Actual Behavior

It minimizes!

**Comment by zadjii-msft** [comment]
this is _like_ #10292, but _different_

**Comment by miniksa** [comment]
> this is _like_ #10292, but _different_

OH. Ok. I can fix that one too then.
