### ISSUE TITLE
Launch as administrator from limited account fails

### ISSUE THREAD

**Issue by davidakerr** [microsoft/terminal#10397]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Steps to reproduce

From a limited account : 

1. Right click windows terminal
2. Select run as Administrator

### Expected Behavior

I expect to type my admin password and have an elevated command prompt

### Actual Behavior

Password is requested twice
Error then appears
![image](https://user-images.githubusercontent.com/31540828/121568349-86d38600-ca17-11eb-8735-c9c02912f603.png)

**Comment by jborean93** [comment]
Have you installed the Windows Terminal app on your administrator account?

**Comment by davidakerr** [comment]
I installed it on the account I'm using. Although I did so before I switched the account from admin to limited.

**Comment by Goldor0ck** [comment]
I confirm I have the same issue with the 1.8.1521.0 version, with the same behaviour. I hadn't it with 1.7, however.
Installed on both 'admin' and 'standard' accounts, running fine in both icons, and elevated in the 'admin' account. But not as elevated in the 'standard' account.
And it has a "funny" side-effect: 'Run as Administrator' breaks the icon in the menu tiles (not on the taskbar), which becomes dark grey with a bold white line below; the only way to restore it is to remove the icon and re-add it.

**Comment by zadjii-msft** [comment]
> I installed it on the account I'm using. Although I did so before I switched the account from admin to limited.

Okay, so that sounds like you _don't_ have the Terminal installed on your Admin account? That's something that simply doesn't work today. See #7806, /dup #4217
