### ISSUE TITLE
Should we have a ThrottledFunc that works without a dispatcher?

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#10393]
I found that I need something like ThrottledFunc, but works in DxRenderer. There's something that's such a pain point, is that we're wasting valuable CPU times redrawing cursors when we actually don't need to . I know this long ago, just hit this again when investigating #10362 . This is an example WPR trace:

![image](https://user-images.githubusercontent.com/4710575/121506972-cfd70a80-ca16-11eb-9d3c-c87d2d266bb6.png)

To update the cursor, the underlying buffer is frequently checked for `IsCursorDoubleWidth`, which consumes valuable CPU times and totally not necessary. 

A simple solution would be remember the timestamp of the last update and refuse to update it until a certain period of time passes.

**Comment by skyline75489** [comment]
CC @lhecker for thoughts

**Comment by lhecker** [comment]
@skyline75489 I wrote a `til::throttled_func` without a dispatcher just yesterday. hahahahaha
I can contribute it separately today if you want to. 👍
