### ISSUE TITLE
windows terminal freezing while changing the background image

### ISSUE THREAD

**Issue by Ankit006** [microsoft/terminal#10395]
### Windows Terminal version (or Windows build number)

Terminal version: 1.8.1521.0

### Steps to reproduce

1.  Terminal setting
2.  choose profile in the profile section
3.  Go to appearance
4.  Choose background image than click save

### Actual Behavior

Terminal freeze for a moment after click the save button

**Comment by skyline75489** [comment]
Did it freeze for a moment then everything just works? Or did it freeze for a moment then crashed?

**Comment by Ankit006** [comment]
@skyline75489  sometime it freeze for a moment then works and sometime it freeze for a moment then crashed

**Comment by skyline75489** [comment]
What CPU & GPU are you using?

**Comment by Ankit006** [comment]
@skyline75489  CPU - Intel i5 8400
                         GPU - gtx 1660 (driver version 466.47)

**Comment by skyline75489** [comment]
Wonder if this is a driver issue. We've seen driver issue causing crashes & instability before.

What is the Windows version you are using?

**Comment by Ankit006** [comment]
@skyline75489  version 21h1( build  19043.1023)

**Comment by skyline75489** [comment]
Can you try this option here?

![image](https://user-images.githubusercontent.com/4710575/121629622-26435800-caae-11eb-9612-b36531eaae62.png)


This will force software rendering. Sometimes it helps mitigating GPU driver issue. Details can be found [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/rendering#use-software-rendering).

**Comment by Ankit006** [comment]
@skyline75489  ok thanks 🙂. I will try it
