### ISSUE TITLE
Automatic color scheme based on theme (dark/light)

### ISSUE THREAD

**Issue by boop5** [microsoft/terminal#10407]
I use an app to automatically change the OS setting to dark/light mode depending on the time of the day. Using this with tools like edge is extremely comfortable because it reacts and changes it theme. At day I have a light edge, at night a dark edge. 

In Terminal one can only change the window theme, but not the color scheme of the console.

-------

# Description of the new feature/enhancement

The window theme can switch according to the current system theme (dark/light). But the color scheme will always be the same.
![image](https://user-images.githubusercontent.com/4655466/121651638-20904700-ca9b-11eb-9baa-61c4b453de1a.png)

I wish I could optionally set a color scheme per theme. 

Example: 

Light theme: One Half Light
Dark theme: Campbell

When I change the OS dark/light mode setting I want the color scheme in the terminal to change.

**Comment by skyline75489** [comment]
Hi, thanks for the suggestion. This is being tracked at #4066 . I'll close redirect the discussions to that thread.

**Comment by boop5** [comment]
thanks
