### ISSUE TITLE
New Tab page UI for choosing the profile to open from a grid list of profile icons

### ISSUE THREAD

**Issue by ADTC** [microsoft/terminal#10402]
# Description of the new feature/enhancement

## New Tab UI for choosing the profile to open

At this moment, opening Windows Terminal (without specifically choosing a profile) would open a window with the default profile. Some power-users such as myself may need to open a different profile based on our immediate need. This would require me to open a second tab with the correct profile, then close the tab with the default one. (Or we'd have to create profile shortcuts in our Desktop or Start Menu.)

Modern web browsers have a built-in New Tab page which often shows frequent shortcuts or recently visited pages to be helpful to the user in deciding where they would like to go. A simplified version of such a page could be added to Windows Terminal, that simply displays a list of all the profiles. Choosing one could open it in the new tab that's already created and waiting for a profile.

![image](https://user-images.githubusercontent.com/6047296/121598937-f4fa6600-ca74-11eb-835b-54648951d7df.png)

In Settings, the _Default Profile_ selection can have an option called _"Show the New Tab page."_ Consequently, the New Tab button on the tab bar would always show the New Tab page instead of opening a profile. This further increases the usefulness of this feature by giving the same convenient UI to pick a profile. (This may negate the need for the drop-down which could be removed or made optional.)

**Note:** The checkbox, if checked, would set the chosen profile to the _Default Profile_ selection in Settings. Subsequently, all new tabs and windows will open in that profile until the user returns to the Settings and resets the selection to _"Show the New Tab page."_ (The checkbox would be unchecked again.)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3586 for more discussion.

/dup #3586

(curiously enough, this was requested earlier this week over in #10338 as well)

**Comment by ADTC** [comment]
@zadjii-msft Thank you! And sorry, I tried searching but couldn't find anything similar. Thanks for pointing out the duplicates.
