### ISSUE TITLE
Pencil icon (Edit button) on Actions page is invisible with light theme

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#10406]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.9.1445.0 on Windows 10.0.19043.1052

### Other Software

N/A

### Steps to reproduce

1. Select the light theme in Windows settings (Personalization, Colors).
2. Start Windows Terminal Preview.
3. Open the Settings tab.
4. Close the session tab. (Only to exclude it from screen shots.)
5. Select the Actions page of the Settings tab.
6. Press the Tab key a few times, to select one of the actions listed.

### Expected Behavior

Should have a pencil icon at the right side of the description of the key binding.

The pencil icon would show up all right with a dark theme:

![image](https://user-images.githubusercontent.com/46201428/121649597-65b77780-caa1-11eb-99c2-0c635d4aa4ea.png)

### Actual Behavior

No pencil icon is visible, but if you press Tab once more, the focus rectangle moves to the invisible pencil icon anyway.

![image](https://user-images.githubusercontent.com/46201428/121649232-0bb6b200-caa1-11eb-94c0-425f5abef94c.png)

![image](https://user-images.githubusercontent.com/46201428/121649267-16714700-caa1-11eb-90a6-5e1dd4b2ea65.png)

**Comment by KalleOlaviNiemitalo** [comment]
This belongs to the <https://github.com/microsoft/terminal/issues/6900> epic.

The pencil icon is likewise invisible when the mouse pointer hovers on an action while using a light theme.

**Comment by KalleOlaviNiemitalo** [comment]
I guess it is caused by the white foreground color here: <https://github.com/microsoft/terminal/blob/227ec3777a216613c3796991d9bc01db6d184d24/src/cascadia/TerminalSettingsEditor/Actions.xaml#L243-L250>

**Comment by mdtauk** [comment]
Should be using Theme Resources so the colour changes as the theme does

**Comment by KalleOlaviNiemitalo** [comment]
@mdtauk, when I first noticed the invisible icon, I had been using the light theme for several days (perhaps weeks) and even restarted Windows for the June security updates. That makes this bug different from <https://github.com/microsoft/terminal/issues/1230>.

**Comment by mdtauk** [comment]
I wonder if this is an issue about the buttons which appear on hover, not appearing when the control is **focused**

**Comment by KalleOlaviNiemitalo** [comment]
@mdtauk, in that case, the bug would occur with the dark theme as well. It doesn't.

**Comment by DHowett** [comment]
/cc @carlos-zamora



> I wonder if this is an issue about the buttons which appear on hover, not appearing when the control is **focused**

They certainly should appear when the control is focused :smile:
