### ISSUE TITLE
Add ability to run in background

### ISSUE THREAD

**Issue by Gravifer** [microsoft/terminal#10419]
# Description of the new feature/enhancement

I think it would be more convenient to be able to put the terminal host in the background.

As I imagine, in the fullest form:
- when any instance is put to the background (which may be set as the default behavior when the window is minimized), the host leaves an icon in the task bar;
- when the icon is clicked, a menu pops up and lists all running instances, with simple notification (running/error/finished) of status for each.

**Comment by WSLUser** [comment]
This is related to the defterm stuff. You can execute a long running script on conhost and the console window can be hidden and run in the background. With Windows Terminal able to become the default console, it should provide similar functionality/experience. The Terminal devs are still fleshing out issues with the defterm and I think you require an Insiders build to test it out.

**Comment by Gravifer** [comment]
@WSLUser thanks for your reply. I think what I'm suggesting requires Terminal to be the defterm.
I am not clear about the limitations of Terminal's current status, though Chrome and Slack are able to "hide themselves to the task bar", which doesn't seem to require more than standard API (I'm not sure though).
Maybe it is possible to provide a similar experience in Terminal? In this case, neither the shell sessions nor the processes running in them are really put to the background; technically only the Terminal window is hidden.
To my mind, this is enough to provide a decent user experience. This is like using tmux without setting it up as the default shell: it only serves to hold the sessions and prevents accidental hang up.

**Comment by skyline75489** [comment]
I think this is similar to #5727?

**Comment by Gravifer** [comment]
@skyline75489 you're right. Sorry for overlooking similar issues in my initial search.
