### ISSUE TITLE
Windows Terminal makes Start Menu not closing automaticlly after opening a folder pinned from Start Menu itself

### ISSUE THREAD

**Issue by clariojohan** [microsoft/terminal#10418]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

1. Install the Windows Terminal from Microsoft Store
2. Pinned a folder to Start Menu
3. Open the pinned folder from the Start Menu
4. Start Menu don't close automaticlly and show the folder.

### Actual Behavior

Windows Terminal makes Start Menu not closing automaticlly after opening a folder pinned from Start Menu itself.

I just installed windows terminal and find out that my start menu did not working properly as before. When I open a folder that've beed pinned to the start menu, the start menu did not close automaticlly and I have to close it manually or click anywhere around the folder that I opened.

I hope Microsoft fix the issue, thank you.

**Comment by j4james** [comment]
This sounds like issue #7122, and is apparently caused by the "Open in Windows Terminal" shell extension. If you don't need that functionality you can disable it via the registry as explained here: https://github.com/microsoft/terminal/issues/7008#issuecomment-662621638

**Comment by DHowett** [comment]
Thanks, James! This is definitely a /dup of #7122.

**Comment by cjmax9x** [comment]
found solution to fixed it:
https://www.youtube.com/watch?v=wauA3rUMq5A
