### ISSUE TITLE
Even when Default Terminal Application is Windows Terminal, Open Windows PowerShell (Administrator) as Windows Console Host.

### ISSUE THREAD

**Issue by akihironagai** [microsoft/terminal#10420]
### Windows Terminal version (or Windows build number)

10.0.21390.0, 1.9.1523.0

### Steps to reproduce

1. Win + X to show System Menu
2. Click Windows PowerShell (Administrator)
3. Allow UAC (Dialog icon is PowerShell icon)

### Expected Behavior

Open Windows PowerShell (Administrator) in Windows Terminal.

### Actual Behavior

Open Windows PowerShell (Administrator) as Windows Console Host.

**Comment by WSLUser** [comment]
Better option: Show both options as sub-entries for the "Open Powershell here".  I think this is something the Powershell will have to address as they are the ones to create the entries in Start Menu, Explorer, etc Best bet is to migrate this issue to their repo.

**Comment by zadjii-msft** [comment]
> Unfortunately, this is by design right now. Due to a limitation in the app platform it is impossible for Terminal to be "discovered" as the handler when the application that needs a terminal is running elevated.

/dup #10276
