### ISSUE TITLE
Open another window but keep the previous window's process directory

### ISSUE THREAD

**Issue by joutvhu** [microsoft/terminal#10425]
Currently, I can open **Windows Terminal** in a folder through the `Context Menu` &#8594; `Open in Windows Terminal`, but it only works with _default profile_.
When I want to open with another profile there is no way to keep the old _process directory_.

I think we can add a new feature are where holding down a certain key (maybe `Ctrl`) while opening a new window, then using the previous window's _process directory_ for new window.

![image](https://user-images.githubusercontent.com/9401202/121940225-0cd53100-cd78-11eb-8ba7-9bc008181f0b.png)

Thanks 😄

**Comment by DHowett** [comment]
Suspect you could just run `wt -d .`, but perhaps we _should_ support this.

**Comment by zadjii-msft** [comment]
this is already on the Shell-Extension backlog as "subsequent tabs...." something or other FYI

**Comment by joutvhu** [comment]
> Suspect you could just run `wt -d .`, but perhaps we _should_ support this.

I think it would be more helpful if there was a way to open it quickly. This is as complicated as using `cd <directory>`

**Comment by DHowett** [comment]
This looks distinct from #8933, so I've tagged it up for the backlog.

**Comment by zadjii-msft** [comment]
Ooh this sounds a like like a combo of:
* #10232
* #6111
* #4637

@joutvhu you think any of the above three would fill this gap for you?

**Comment by joutvhu** [comment]
I think the case #6111 seems to be more used.

**Comment by zadjii-msft** [comment]
Great! I'm gonna close this out as a dupe then, for janitorial purposes. Thanks!

/dup #6111
