### ISSUE TITLE
Ctrl-click: support FS paths such as `C:\` and `C:/`

### ISSUE THREAD

**Issue by mitranim** [microsoft/terminal#10429]
# Description of the new feature/enhancement

As of `1.8.1521.0`, Windows Terminal supports some file URLs:

    file://C:/<path>
    file:///C:/<path>

But support for regular FS paths seems to be lacking:

    C:\<path>
    C:/<path>

Being able to Ctrl-click into files and folders would be extremely convenient.

The reason I'm also asking for `/` support, in addition to `\`, is because certain CLI tools may output these partially "unixified" paths. For example, Go stacktraces have paths that look like this:

    C:/<path>:<row>:<col>

(Support for row/col is a separate issue: #10428. This is about FS paths which may use both slash styles.)

**Comment by skyline75489** [comment]
I think #2671 covers this.

**Comment by mitranim** [comment]
Should I add examples to that issue?

**Comment by skyline75489** [comment]
Feel free to do so if you want to. We know what the feature is about. Just lack a solution that handles all scenarios (cmd, powershell, WSL & possible other shells). See https://github.com/microsoft/terminal/issues/9793#issuecomment-818736920 .

**Comment by mitranim** [comment]
Closing as duplicate, apologies for your time.
