### ISSUE TITLE
Ctrl-click: consider supporting `:<row>:<col>` in FS URLs and paths

### ISSUE THREAD

**Issue by mitranim** [microsoft/terminal#10428]
# Description of the new feature/enhancement

In many languages, stacktraces include `:<row>:<col>` into paths. The convention is strong and supported by many code editors. Being able to click directly into the offending code is extremely convenient!

Working example: MacOS + iTerm2 + generate an exception in Node/Deno, or a panic in Go. Click any FS path in the stacktrace.

# Proposed technical implementation details (optional)

iTerm2 supports this feature at a high cost. The source code has a lot of special-case editor detection. Hopefully there's a simpler solution for WT.

**Comment by skyline75489** [comment]
I love this in iTerm2. I'd also like to see this when #2671 is implemented. As for editor detection, I think first-party VSCode support can be a good first step.

**Comment by DHowett** [comment]
Thanks for the request! We're looking at solving this issue all-up in /dup #8849.
