### ISSUE TITLE
Option to run as admin as default

### ISSUE THREAD

**Issue by Joe1921567817** [microsoft/terminal#10439]
# Description of the new feature/enhancement

Please add an option to run as admin as default, instead of having to right click on it and choose _Run as Admin_ everytime.
# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
I think you're looking for #632?

**Comment by Joe1921567817** [comment]
> I think you're looking for #632?

Yeah that's just what I'm looking for!
thanks bro :)
