### ISSUE TITLE
Be able to set an initial position for the terminal

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#1043]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.86]
Windows Terminal version (if applicable): commit bbbd3e0323a82548416f40ddba
```

# Steps to reproduce

1. Start Windows Terminal
2. Move the Windows Terminal window
3. Close Windows Terminal
4. Start Windows Terminal

# Expected behavior

Window position is restored to were it was in step 3 above.

# Actual behavior

Window is opened at a default location.

**Comment by DHowett-MSFT** [comment]
What if you have more than one window?

**Comment by patriksvensson** [comment]
@DHowett-MSFT Good question and I realize my expectations what somewhat flawed. Currently the Windows Terminal window is opened so that half the terminal is outside of my screen bounds (I've changed the `initialRows` and `initialCols`)

When I think about it, I would want a way of setting the default window position somehow (like I can with the old fashion terminal).

**Comment by zadjii-msft** [comment]
There's already #766, which deals with restoring general state from the previous session. I'd say much of this issue fits under that umbrella, save for:

> I would want a way of setting the default window position somehow (like I can with the old fashion terminal).

Shockingly, I don't think we have an issue tracking that particular feature request quite yet. This is now the thread tracking that feature request.

**Comment by UweKeim** [comment]
Personally, I prefer even having multiple instances being restored to the very same pixel position and size rather than stacking them pseudo-randomly over my desktop.

Tastes are different, so why not add an option like:

```json
{
    "windowRestoreMode": "lastPositionAndSize"
}
```

With `windowRestoreMode` being an enum of values like:

- `none` — Do nothing, let Windows place automatically.
- `lastPositionAndSize` — Restore pixel-perfect both in position and size, no matter whether docked before (just like I described in #1420)
- Possibly more modes…

**Comment by lllopo** [comment]
> Personally, I prefer even having multiple instances being restored to the very same pixel position and size rather than stacking them pseudo-randomly over my desktop.
> 
> Tastes are different, so why not add an option like:
> 
> ```json
> {
>     "windowRestoreMode": "lastPositionAndSize"
> }
> ```
> 
> With `windowRestoreMode` being an enum of values like:
> 
> * `none` — Do nothing, let Windows place automatically.
> * `lastPositionAndSize` — Restore pixel-perfect both in position and size, no matter whether docked before (just like I described in #1420)
> * Possibly more modes…

"Possibly more modes" should also include a predefined position on screen in pixels, imho.

**Comment by UweKeim** [comment]
Sounds very good, @lllopo.

For your `defindedPositionAndSize` mode, one could enhance this like e.g.:

```json
{
    "windowRestoreMode": "definedPositionAndSize",
    "windowPos": 
    {
        "x": 100,
        "y": 120,
        "width": 400,
        "height": 800
    }
}
```

One could even enhance this for multiple intances of Terminal to each use another set of positions/sizes like:

```json
{
    "windowRestoreMode": "definedPositionAndSize",
    "windowPos": 
    [
        {
            "isDefault": true,
            "x": 100,
            "y": 120,
            "width": 400,
            "height": 800
        },
        {
            "x": 500,
            "y": 120,
            "width": 400,
            "height": 800
        },
        {
            "x": 900,
            "y": 120,
            "width": 400,
            "height": 800
        }
    ]
}
```

**Comment by UweKeim** [comment]
Just one more discovery: 

**Visual Studio Code** starts the first instance pixel-perfect as it was closed before. When starting a second instance, it starts it as some default position and size.

Not as advanced as my suggestion, but way better than Termin doing now.

**Comment by Seefer** [comment]
> What if you have more than one window?

More than one window is great in multiple monitor arrangements and I'd still like to have control over where they open and the their size. For multiple terminals on one display I'd prefer to have a tab feature in one window or use WTs splitPane function rather than individual windows.

**Comment by escalonn** [comment]
this is still an issue in the present released version.

**Comment by zadjii-msft** [comment]
@escalonn This feature was merged two years ago, can you file a new issue to track whatever you're seeing? Please make sure to include your `settings.json`, your Terminal version, etc.

There's also #766 which merged into 1.12, which will restore the window positions automatically, which is part of what this thread was discussion originally.

**Comment by UweKeim** [comment]
For me, it is still not working pixel-perfect, too, when being docked to either side of the screen.

I gave up, bought [DisplayFusion Pro](https://www.displayfusion.com) and created [a trigger](https://www.displayfusion.com/Features/Triggers/) therein to position the Terminal window correctly after it start.

**Comment by patriksvensson** [comment]
@zadjii-msft I think you should lock this issue.
