### ISSUE TITLE
"Quake Mode" launch animation

### ISSUE THREAD

**Issue by markski1** [microsoft/terminal#10437]
# Description of the new feature/enhancement

A simple sliding animation for the quake mode when it is launched and dismissed. Ideally it would have a linear speed (as opposed to any fancy acceleration or bounce) to bring that "quake console" feel a bit more legitimately.

# Proposed technical implementation details (optional)

I'm not sure how this would be implemented. But if you managed to make the quake mode possible in the first place I imagine an animation should also be in the realm of possible too

Nothing else. You guys are doing a fantastic job with the new Terminal. I've been using it for the past few months and having tabs alone is already an incredible QoL improvement. And I'm already very excited with this new way to summon and dismiss it with a key combo.

**Comment by markski1** [comment]
It should also ideally be optional and disabled by default. As I imagine most users would appreciate quick access through that method

**Comment by LuanVSO** [comment]
there's already an animation, docs:
[quake-mode](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#open-the-quake-mode-window-preview)
[global-summon](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon-preview)

**Comment by skyline75489** [comment]
Yeah I don't know what version you're using but it has support for animation (and disabling it).

**Comment by markski1** [comment]
Thanks for the replies. I've tried what the documentation says on my settings.json and it seems to straight up ignore the dropdownDuration parameter. Maybe this could use also being in the proper settings

**Comment by LuanVSO** [comment]
did you disable animations on windows accessibility settings?

**Comment by markski1** [comment]
That seems to have been the problem, I didn't assume that setting would affect this but I guess that makes sense.

Now my problem is that the animation seems quite glitchy and stuttery. But I guess that's a different issue, so I consider this closed. Thanks for your help.

![k2rMd74O2a](https://user-images.githubusercontent.com/22557859/122414159-4fa42e00-cf5d-11eb-9328-7a878df3078c.gif)
