### ISSUE TITLE
Background color gets broken on large command output

### ISSUE THREAD

**Issue by willeccles** [microsoft/terminal#10444]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

WSL2 + Void Linux
zsh shell (5.8)
Seems most frequent when using Neovim (not during, but maybe after?), GCC, clang, etc.

My configs for zsh, nvim, vim, etc. can be found [here](https://github.com/willeccles/dotfiles). My WT settings are attached (zipped because GitHub; note that I am almost always using my Void config, I don't use the others frequently enough to know if this happens there).

[settings.zip](https://github.com/microsoft/terminal/files/6670632/settings.zip)

### Steps to reproduce

Simply run a command which produces a lot of output. It's not consistent, but I can reproduce it frequently when a program's output is very long and all comes out at once (or extremely quickly, anyway). This often includes things like C++ compilers giving lots of notes, my own programs dumping a lot of debug logs (at the moment, a C++ program parsing a large JSON file and printing the parsed data), etc.

### Expected Behavior

The program's output should just be there as you'd normally expect:
![image](https://user-images.githubusercontent.com/3360049/122406159-a0605a80-cf4e-11eb-9223-c170d3603a13.png)
I have added the output line count for reference, though it's likely not super useful here.

### Actual Behavior

Ironically I'm struggling to reproduce it at the moment, but what happens is that the background color after a newline character (i.e. at the end of each line, all the way to the right of the window, but not during the line's content itself) changes to a lighter one. I will see if I can figure out what actual steps seem to make this happen the most. Additionally, resizing the window seems to fix it (although it causes other issues with my shell's output, but that seems likely to be more related to the shell, or at the very least out of the scope of this issue). I normally use one window maximized (not fullscreen) with multiple tabs.

I will update with a screenshot the next time it happens (which should be about 10 seconds after I click "Submit", knowing how software works).

**Comment by DHowett** [comment]
Let us know if you can reproduce it and what led to that state! Some of this is likely by design -- the terminal is supposed to take on the background color that was present at the end of the line at the bottom of the viewport, but it may not do so consistently.

**Comment by willeccles** [comment]
Absolutely will! I'll see if I can't get it to happen tomorrow--had to work on other stuff today, so I didn't get to do as much testing as I wanted.

**Comment by j4james** [comment]
This might be related to #8823. That issue also had the background color changing on end of the line (and it doesn't happen all the time).

**Comment by willeccles** [comment]
Yes, I think that this is most definitely related. That seems to be about the behavior I'm seeing.

**Comment by willeccles** [comment]
I have been unable to reproduce the issue (unsurprisingly, because nothing ever goes wrong when you need it to), and I am almost certain that #8823 is the same issue. I will close this issue for now, and if I can find some evidence to suggest they are different issues, I will reopen. For the time being, it's probably best to avoid the duplicate issue.

**Comment by DHowett** [comment]
Thanks for following up :smile: If it ends up being different, feel free to reopen or open anew!
