### ISSUE TITLE
Chinese Localization for ShellExtension

### ISSUE THREAD

**Issue by Joe1921567817** [microsoft/terminal#10440]
# Description of the new feature/enhancement

Please add Chinese translation for the shell extension
for Chinese Traditional:"在此處開啟 Windows Terminal"
for Chinese Simplified:"在此处打开 Windows Terminal"
# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Thanks for the request! This is a /duplicate of #6112.
