### ISSUE TITLE
Open terminal in quake mode then close it let Edge/Chrome lose focus

### ISSUE THREAD

**Issue by roachsinai** [microsoft/terminal#10450]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

Windows Terminal Preview 1.9.1523.0
Chrome 91.0.4472.114
Edge 91.0.864.48
Chrome extension: Vimium

### Steps to reproduce

Open a webpage like https://www.reddit.com/t/windows_terminal/ .
For now the mapping of Vimium works, like press `f` you could open links.
Then trigger windows terminal quake by shortcut, default is win+backquote. And repress win+backquote to roll up windows terminal.
For now Vimium not works, have to use mouse point application to let them get focus again. The Vimium works.

### Expected Behavior

Application can auto get focus after oll up windows terminal.

### Actual Behavior

Application lose focus after oll up windows terminal as I posted in steps to reproduce.

**Comment by skyline75489** [comment]
Can you still use `Ctrl+t` and `Ctrl+w`? I'm using Edge and I can still use those hotkeys so Edge has the focus.

**Comment by roachsinai** [comment]
Yeah bot Edge and Chrome can use `Ctrl+t` and `Ctrl+w` even the extension not works.

**Comment by skyline75489** [comment]
Then I guess this is issue between the browser & the extension. The terminal has handled over the focus as it should. I don't know if there's anything else the terminal should do.

**Comment by roachsinai** [comment]
Yes, thanks for reply!

**Comment by roachsinai** [comment]
Hi @skyline75489 I get reply from author of vimium-c,

> 那就是浏览器的“键盘焦点”跑到窗口框架上去了。你可以按几次tab，或者点一下。

So how you guys handle the focus? As in Linux when I use other dropdown terminal, guake and yakuake, no this bug, is it possible that windows terminal didn't do it in a right way?

**Comment by roachsinai** [comment]
I found after roll up windows terminal, the foucs is at the right up corner of Edge:

![image](https://user-images.githubusercontent.com/9500049/122523884-1bf30200-d04a-11eb-9375-0d41bf2e933f.png)

**Comment by skyline75489** [comment]
Do you use <kbd>Win + `</kbd> to summon the quake window?

 I'm using <kbd>Ctrl + `</kbd> and I'm not seeing the issue.

**Comment by skyline75489** [comment]
Also do you have other applications running in the background that could potentially move focus around? I don't see any unusual thing related to focus and I use quake mode a lot.

**Comment by roachsinai** [comment]
I actually use `Alt + a`, yeah can't reproduce it by win+backquote.

I said win+backquote as it is the default key for quake mode.

Maybe I know the reason of it...

As the author of vimium posted, press just alt key will let Edge focus at the rightup corner. So, seems the producing of combination of `Alt` leads to this issue.

**Comment by skyline75489** [comment]
Yep, that seem to be the issue. Glad you find it out!

**Comment by roachsinai** [comment]
But it didn't happened when I use yakuake on Linux...

**Comment by skyline75489** [comment]
You do realize that you're talking about two entirely different OSes, right? 😄 

A lot of things are different between Windows & Linux. And be honest, a lot of things are different even between KDE and GNOME. Yeah it's not a perfect world, I know. I guess we just have to live with it.

**Comment by skyline75489** [comment]
I added a comment in #8888 to track this. Thanks for the report, anyway. And have fun using Windows Terminal!

**Comment by roachsinai** [comment]
Thanks for that!!!

**Comment by jantari** [comment]
@roachsinai The Alt key is used to navigate menu bars with the keyboard in Windows, e.g. open a file explorer Windows and press and hold ALT - you'll see keys overlayed on the menu bar items at the top (in some programs they're underlined instead, same thing) - then when you press that key the menu item gets activated. It's very useful and has been in Windows for decades which is why `Alt` is a bad choice for keybindings.
