### ISSUE TITLE
Build tools bug: `nuget restore` fails with "Illegal characters on path" if you already have NuGet 5 or later on your PATH

### ISSUE THREAD

**Issue by metathinker** [microsoft/terminal#1045]
### Environment

Terminal repo commit: 8baba4b46c39999038582345ff63d0adb341b1a2
NuGet installed from Chocolatey:
- C:\ProgramData\chocolatey\bin on PATH
- Running `nuget` in a fresh command prompt yields `NuGet Version: 5.0.2.5988`

### Reproduction steps

1. Open a cmd.exe command prompt and use `cd` to go to your Terminal repo working copy.
1. Run this command: `tools\razzle.cmd & nuget restore`

### Results
_Expected results:_ NuGet should tell you all the packages are installed already
_Actual results:_ NuGet fails with the error message `Illegal characters on path`

The run of NuGet by `razzle.cmd` itself is not affected by this issue, but it could be a problem if you need to run NuGet again after a `git clean` or similar, especially if and when the checked-in NuGet 4 binary in the repo is removed!

**Comment by DHowett-MSFT** [comment]
This sounds like a NuGet bug?

**Comment by metathinker** [comment]
> This sounds like a NuGet bug?

Yeah, but the workaround is so simple that I made a PR in this repo ^ to fix it. I'll also file a bug against NuGet.

**Comment by metathinker** [comment]
... and here's the NuGet bug: https://github.com/NuGet/Home/issues/8168

**Comment by DHowett-MSFT** [comment]
Thanks for the report and the timely fix!
