### ISSUE TITLE
Move delete button theme resources into CommonResources.xaml

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#10454]
There's a few places in the Settings UI where we have a "delete button":
- [Actions Page](https://github.com/microsoft/terminal/blob/b6593216f2f10c6e2b9922c22bcd22e4618020c5/src/cascadia/TerminalSettingsEditor/Actions.xaml#L317-L364)
- [Color Schemes Page](https://github.com/microsoft/terminal/blob/b6593216f2f10c6e2b9922c22bcd22e4618020c5/src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml#L290-L337)
- [Profiles Page - Delete Profile](https://github.com/microsoft/terminal/blob/b6593216f2f10c6e2b9922c22bcd22e4618020c5/src/cascadia/TerminalSettingsEditor/Profiles.xaml#L161-L208)
- (PR #10317) Profiles Page - Delete Appearance: (just look up "Firebrick")

We should move these over to [CommonResources.xaml](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsEditor/CommonResources.xaml).

Examples of what this would look like:
- https://github.com/microsoft/terminal/blob/b6593216f2f10c6e2b9922c22bcd22e4618020c5/src/cascadia/TerminalSettingsEditor/CommonResources.xaml#L14-L32
- https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Common_themeresources.xaml

If we have any other theme resources that we use in a few places, we should do the same. I'm also open to the idea of having a separate file named something like `CommonThemeResources.xaml` if we wanted to take that route.

**Comment by sourabh112** [comment]
Hi @miniksa @carlos-zamora, Can I work on this issue? As I'm quite new to open-source, I might need your guidance.

**Comment by zadjii-msft** [comment]
@sourabh112 Go right ahead!

**Comment by sourabh112** [comment]
Thanks @zadjii-msft , for the opportunity and sorry for late reply. I'm starting with making myself familiar with the code, so that my changes won't affect anything else.

**Comment by jelonmusk** [comment]
Hi
I would also like to work on this issue.
p.s. I'm a first-time contributor!

**Comment by jelonmusk** [comment]
https://github.com/jelonmusk/terminal/blob/main/src/cascadia/TerminalSettingsEditor/CommonResources.xaml

Here's the link to changes made in CommonResource.xaml file.
@miniksa Could you please review it?

**Comment by miniksa** [comment]
I will look at the PR.
