### ISSUE TITLE
Add option to Keep the last position when the terminal was opened

### ISSUE THREAD

**Issue by crar01** [microsoft/terminal#10452]
# Description of the new feature/enhancement
When the terminal is opened, usually it is started in a random position(it seems). An option is to add a config to keep the last position when the terminal was opened.

**Comment by j4james** [comment]
I think this is probably covered by issue #766. Note the last line of the description:
> This also includes restoring things like previous window positions.

**Comment by zadjii-msft** [comment]
Sure does 

/dup #766
