### ISSUE TITLE
Terminal doesn't start with non-informative error message "THE service had not been started"

### ISSUE THREAD

**Issue by LtqxWYEG** [microsoft/terminal#10458]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

I guess; have a Microsoft Store that is unable to download apps for some reason (Error 0x800706d9), download the msixbundle and install via powershell

### Expected Behavior

Normal start

### Actual Behavior

Error message with path to WindowsTerminal.exe and "The service had not been started".
Please tell me what THE service is. -.-

Note: It isn't the touchscreen service and I can't find one with "terminal" in the name.

**Comment by lhecker** [comment]
What version of Windows are you using? Did you already run dism and sfc as per the usual Windows repair guidelines?
The services Windows Terminal (WT) depends on are, what I would consider, "system critical". If they're stopped something's wrong with your Windows installation entirely and not just WT in particular.

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://github.com/microsoft/terminal/issues/7442#issuecomment-682342432>, `appxsvc` or `wlidsvc` may be required.

**Comment by LtqxWYEG** [comment]
> `appxsvc and wlidsvc`

Oh my god. I can't believe it was this easy. I've had this issue for more than a year and even asked tier 2 Microsoft Support for help... WTH??!?! Why is nobody writing that the Store login stuff needs this service? I can't even... Thank you SO much ^^
BTW I deactivated this service myself at some point, so I myself am entirely responsible for my misery.

For Google'in ppl: Microsoft Store error 0x800706d9 when trying to log in or download app. MS store app error 0x800706d9 bla bla god I can't believe it

**Comment by DHowett** [comment]
Interesting. If you go to the "All Apps" page, then select Terminal and click Repair, does it work?

If not: have you changed the permissions on `C:\Program Files\WindowsApps`?

**Comment by LtqxWYEG** [comment]
> 
> 
> Interesting. If you go to the "All Apps" page, then select Terminal and click Repair, does it work?
> 
> If not: have you changed the permissions on `C:\Program Files\WindowsApps`?

No :(
I uninstalled it and tried installing it via the Store, but I get Error 0x80072EE7 while it says "Aquiring license". What license? Just a general software license? How is this aquired? Maybe I blocked something somewhere. Apps update fine, but I can't install new ones. :(

Firewall is off, VPN is off, the troubleshooter can't find the issue... I don't know

**Comment by lhecker** [comment]
@LtqxWYEG `0x80072EE7` means it failed to find the given server address. Basically something's off with your DNS, or your firewall.

There are probably people who know how to fix this issue. Maybe even in this thread!
But if no one comes up with anything later, I think it might be a good idea for you to consider to run ["Refresh your PC"](https://support.microsoft.com/en-us/windows/how-to-refresh-reset-or-restore-your-pc-51391d9a-eb0a-84a7-69e4-c2c1fbceb8dd). You can also use "Reset your PC" to be absolutely sure (it'll delete all your files though). But if you do any of those options you should backup all your files just in case.

Either way it's possible that someone has an idea how to fix it, but I personally consider it somewhat unlikely.
You can try waiting a bit until someone writes here, finding a solution using Google, or Refresh/Reset your PC.

**Comment by LtqxWYEG** [comment]
I use either VPNs DNS, which never gave me issues, or 1.1.1.1. That should not be the issue
Hosts file is empty.
I try a in-place upgrade first. I've got hundreds of programs installed...
I'll edit this or create a new comment when I'm done

However the current issue is still that I get the error "File system error (12007)" when i start terminal - if installed manually via msixbundle. I don't think both issues are connected

**Comment by lhecker** [comment]
@LtqxWYEG It's unknown how complex the cause for your issue was. For all we know it could have even been an incredibly corrupt Windows installation for instance. Windows has a lot of moving parts and is a large OS; it's not unthinkable that diagnosing the issue takes much longer than reinstalling the OS.

Or in other words: If I had your PC in front of me it might be trivial to diagnose the cause, but diagnosing it over GitHub is much much harder, just like how it's hard to diagnose PC issues over the phone.

I'm glad that your issue was resolved!
