### ISSUE TITLE
"Default Profile" drop down in the Settings window goes out of window when scrolling (Video included)

### ISSUE THREAD

**Issue by verndrade** [microsoft/terminal#10469]
### Windows Terminal version (or Windows build number)

Microsoft Windows NT 10.0.19043.0

### Steps to reproduce

Open Windows Terminal
Open the Settings (Ctrl + ,)
Be on the Startup tab
Click on the Default Profile dropdown 
Scroll down with trackpad / scroll bar

https://user-images.githubusercontent.com/43098333/122693874-96b64b80-d209-11eb-819d-96fa505c29e6.mp4

### Expected Behavior

Dropdown should either close or go out of view (stay in the Windows Terminal window) when the user scrolls.

### Actual Behavior

Dropdown flies out of the window 
https://user-images.githubusercontent.com/43098333/122693874-96b64b80-d209-11eb-819d-96fa505c29e6.mp4

**Comment by skyline75489** [comment]
Thanks for the report & nice video you made. This is actually already being tracked by another issue on our repo - please refer to #9320 for more discussion.
