### ISSUE TITLE
terminal 中的 WpfTerminalTestNetCore 类是不是没有用到

### ISSUE THREAD

**Issue by a48625a** [microsoft/terminal#10468]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

terminal 中的 WpfTerminalTestNetCore 类是不是没有用到，我几乎下了所有断点，但都没有命中。

**Comment by a48625a** [comment]
我要怎样才能调试和修改里面的代码

**Comment by skyline75489** [comment]
Translation: Is the `WpfTerminalTestNetCore` currently unused by anything? No breakpoint works. How do I debug & motify it's code?

**Comment by toto6038** [comment]
Just a friendly reminder, it would be helpful to have your problem in English as well to help others understand your issue better.

> 
> # Description of the new feature/enhancement
> # Proposed technical implementation details (optional)
> 
> terminal 中的 WpfTerminalTestNetCore 类是不是没有用到，我几乎下了所有断点，但都没有命中。

**Comment by DHowett** [comment]
Configuration = "Debug"
Platform = "DotNet_x86Test"

This will let you test WpfTerminalTestNetCore.

It is a project we use to test changes to the WPF Terminal, which is used by Visual Studio.
