### ISSUE TITLE
Missing specific character when pasting into powershell

### ISSUE THREAD

**Issue by ddarfantasy** [microsoft/terminal#10467]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

Powershell

### Steps to reproduce

Paste this in a powershell dialog: `这是（括号）`

### Expected Behavior

`这是（括号）` shows up exactly

### Actual Behavior

There's only `这是括号`

**Comment by skyline75489** [comment]
I believe this is fixed in 1.9-preview. See #9052.

**Comment by DHowett** [comment]
Thanks! This is a /dupe of #9052.
