### ISSUE TITLE
Identify when PowerShell is running within Windows Terminal

### ISSUE THREAD

**Issue by mileso** [microsoft/terminal#10475]
There is, by design, no reliable way. We have been hoping for someone to come along and explain what their use case would be for being able to determine that 😄

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/issues/5523#issuecomment-618809182_

I'm your huckleberry 😀

Here is my use case:

Set a different window title when running PowerShell within Windows Terminal.  Windows Terminal has less real estate because the title is displayed on a tab so I'd like to set a shorter title only when running under Windows Terminal.

Simple example: Add the path to the title only when not running within Windows Terminal.

**Comment by mileso** [comment]
Here is my current work-around (I placed thes into my profile script):

$parentProcess = (Get-Process -Id (gwmi win32_process -Filter "processid='$PID'").ParentProcessId)
$isWT = ($parentProcess.Name -like "Win*Term*")

**Comment by skyline75489** [comment]
how does this https://github.com/microsoft/terminal/issues/1040#issuecomment-496691842 sounds to you?

**Comment by mileso** [comment]
> how does this [#1040 (comment)](https://github.com/microsoft/terminal/issues/1040#issuecomment-496691842) sounds to you?

If you open spawn a shell from within a Windows Terminal session it will inherit the WT environment variables so that is not a solution:

https://github.com/microsoft/terminal/issues/5523#issuecomment-619289717

**Comment by MartinGC94** [comment]
He also made a suggestion to check the parent process: `(Get-Process -Id $PID).Parent.Name -eq "WindowsTerminal"` this should never have false positives but it may have false negatives if you open up a nested process inside the terminal.

**Comment by zadjii-msft** [comment]
I mean, you can always just make the tabs wider too. See [`"tabWidthMode": "titleLength"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/appearance#tab-width-mode). If you're the kind of person who wants to put info into the terminal title, then you probably what the whole tab to be visible 😄
