### ISSUE TITLE
Chinese Traditional (Taiwan) l10n improvement

### ISSUE THREAD

**Issue by toto6038** [microsoft/terminal#10473]
Inspired from #10174 

# Description of the new feature/enhancement

- Fix the inconsistent translation of the same term
- Provide some recommendations

---

**src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw**

| Key | Recommended | Comment|
| --- | --- | --- |
|`SetColorSchemeParentCommandName`|選擇色彩組合 |The current translation for "Color Scheme" is inconsistent with the one in `TerminalSettingsEditor`|

**src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw**

| Key | Recommended | Comment|
| --- | --- | --- |
|`Globals_TabWidthModeEqual.Content`|等寬|The term "Equal" here describes that the width of every tab is the same. The current translation doesn't deliver the correct semantics.|
|`Globals_TabWidthModeCompact.Content`|精簡|The current translation is just a little weird.|
|`Nav_ColorSchemes.Content`|色彩組合|Just a recommendation 😄 |
|`Profile_CloseOnExitAlways.Content`|處理程序結束、失敗或當機時才關閉|The current translation for the term "process" in computer science is inconsistent with other parts in Windows such as Task Manager.|
|`Profile_CloseOnExitGraceful.Content`|只在處理程序正常結束後才關閉|The current translation for the term "process" in computer science is inconsistent with other parts in Windows such as Task Manager.|
|`Profile_UseAcrylic.HelpText`|在視窗的背景套用 Fluent Design 的半透明視覺效果|To help user better understand this option is to toggle the acrylic effect of Fluent Design.|
|`Profile_StartingDirectory.Header`|啟動時載入的目錄|The current translation doesn't provide correct semantics.|
|`Globals_KeybindingsDisclaimer.Text`|以下是目前繫結的按鍵組合，可透過編輯 JSON 設定檔加以修改|Fix the wrong translation for the word "key" in Chinese.|

**Comment by skyline75489** [comment]
#9328 might also be helpful 😃

**Comment by skyline75489** [comment]
Thanks for reporting all these! Please understand the localization is currently handled inside MS and it takes a process to find and ship changes. So it might not be fixed very soon.

**Comment by lhecker** [comment]
@toto6038 I've edited your comment to allow me to more easily copy your suggestions into an internal form in certain format. 🙂 I've split the table into the two file paths they belong to and changed the alignment.

**Comment by lhecker** [comment]
This is tracked as MSFT:33937478.

**Comment by toto6038** [comment]
@skyline75489 @lhecker Thanks for your efforts to make it better!

**Comment by skyline75489** [comment]
This should be fixed in 1.10 Preview.

@toto6038 can you check if it's fixed?

**Comment by toto6038** [comment]
A few strings still didn't get fixed.

**src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw**
| Key | Recommended | Comment|
| --- | --- | --- |
|`SetColorSchemeParentCommandName`|選取色彩配置...|"色彩配置" is the used for "Color Schemes" in `TerminalSettingsEditor`, so they should be consistent.|

![圖片](https://user-images.githubusercontent.com/50100922/126765374-cd5f92d4-c82d-4a42-b703-bed5ad115b29.png)

**src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw**
| Key | Recommended | Comment|
| --- | --- | --- |
|`Profile_CloseOnExitAlways.Content`|處理程序結束、失敗或當機時才關閉||
|`Profile_CloseOnExitGraceful.Content`|只在處理程序正常結束後才關閉||

According to Terminology Search of Microsoft Language Portal "處理序" is the translation for process, the definition of which is the virtual address space and the control information necessary for the execution of a program. However the same term is translated to "處理程序" in Windows Task Manager and some parts of Windows 10 Creator Update. In my opinion "處理程序" is better.

**Comment by toto6038** [comment]
Moreover I want to add some suggestion.

**src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw**
| Key |Current Translation|Recommended | Comment|
| --- | --- | --- | --- |
|`Globals_DetectURLs.Header`|自動偵測 Url 並讓它們可進行點選|自動偵測 URL 並讓它們可被點選|"URL" should be uppercase, and word usage is enhanced.|

**src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw**
| Key |Current Translation|Recommended | Comment|
| --- | --- | --- | --- |
|`SplitHorizontalCommandKey`|分割窗格, split: horizontal|水平分割窗格|Fix the unfinished translation.|
|`SplitVerticalCommandKey`|分割窗格, split: vertical|垂直分割窗格|Fix the unfinished translation.|

**Comment by skyline75489** [comment]
Thanks for the feedback! I think all your recommendations were sent to the localization team inside MS. Maybe they think some of them are better left as it is. To me '色彩配置' and '處理程序' seem to be better choices.

Note that `split: horizontal` actually can't be localized for now. Details can be found at https://github.com/microsoft/terminal/issues/10174#issuecomment-847777677

Also isn't "正在呈现..." strange to you? I think it should be just "呈现". 😅 

Please feel free to add suggestions here. I'll just summon @lhecker for future follow-up works.

**Comment by toto6038** [comment]
Thanks for reminding of "正在呈現...". It's definitely weird. Will add the suggestion for it in last comment.

**Comment by skyline75489** [comment]
Yeah, just by looking carefully and you may find more weird translations. To be very honest, the initial version of translations are really not so good. 

Let's eliminate them before the product hit 2.0 :)

**Comment by toto6038** [comment]
Sadly that on Windows Terminal Preview 1.11.2421.0 the problems mentioned [here](https://github.com/microsoft/terminal/issues/10473#issuecomment-885538969) are still there. Unlike the little difference in word usage such as 處理序 vs 處理程序, which doesn't make confusion, the problems reported this time are translation errors that can be noticed easily.
@lhecker Please handle that, thanks.

Error list:

**src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw**
| Key |Original Text|Current Translation|Recommended| Comment|
| --- | --- | --- | --- |--- |
|`Globals_DetectURLs.Header`|Automatically detect URLs and make them clickable|自動偵測 Url 並讓它們可進行點選|自動偵測 URL 並讓它們可被點選|"URL" should be uppercase.|
|`Globals_FocusFollowMouse.Header`|Automatically focus pane on mouse hover|滑鼠暫留時自動焦點窗格|滑鼠暫留時自動聚焦窗格|"Focus" here is a verb(聚焦) instead of noun(焦點).|
|`Nav_Rendering.Content`|Rendering|正在呈現...|呈現, 繪製|Wrong semantics and confusing|

**Comment by lhecker** [comment]
Tracked as MSFT:36323162.

**Comment by toto6038** [comment]
Fixed on Windows Terminal Preview 1.11.2731.0 🎉 Thanks for the localization team and your effort.
