### ISSUE TITLE
Profiles completely reset

### ISSUE THREAD

**Issue by tracker1** [microsoft/terminal#10476]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

- Terminal 1.8.1521.0
- Windows 10.0.19043.0
- WSL2
- Ubuntu LTS
- Docker Desktop (WSL2)

### Steps to reproduce

- Set "Ubuntu" to a startup directory under \\wsl$\... (Ubuntu user's home directory) - save
- Set "Ubuntu" as Default profile - save
- Reboot

### Expected Behavior

I would expect that my profile settings should remain intact until whatever process is checking for subsystems available to terminal to complete.  I would expect that my starting directory for my WSL2 Ubuntu profile to not get reset.

### Actual Behavior

About 1 in 5 reboots, I see a "There was a problem with your settings..." or some such result.  The list of Profiles is reset, the default is now Powershell, and all the customizations are gone.  There's no WSL profiles for several; minutes, only Powershell and CMD.  Several minutes later "Ubuntu" shows up again, but customizations also gone, namely the starting directory, and it's no longer my default profile.

I've had similar issues on my personal desktop.  It's very annoying to say the least since 90% of my desktop time is in development, under the WSL environment.

NOTE: I also created a custom profile for WSL, not just the detected one, and that disappears as well.

**Comment by lhecker** [comment]
Does your error look like this by any chance? https://github.com/microsoft/terminal/issues/6160

**Comment by tracker1** [comment]
@lhecker yes, it does, thank you...  With so many issues, it's hard to find if something is a dupe via GH search...
