### ISSUE TITLE
Start quake mode on boot

### ISSUE THREAD

**Issue by Devnol** [microsoft/terminal#10481]
# Description of the new feature/enhancement
Add an option to start quake mode on system startup in the background, so it is always available from the get-go. Currently setting Windows Terminal to open on startup just opens an ordinary window of it, something that some people, including myself do not want. To start quake mode, I have to wait until the ordinary window fully loads, then press Win+` and then close the ordinary Terminal window. 

# Proposed technical implementation details
I would like to be able to have Windows Terminal start in the background on boot, so that it has Quake Mode available and so that it doesn't start a normal window that I do not want. This could potentially be a checkbox as something like "Start in Background " below "Launch on Machine Startup" and be dependent on it so that it's grayed out when the latter is off.

**Comment by Devnol** [comment]
Oh, this appears to be a dupe of #9996

**Comment by DHowett** [comment]
Thanks for finding that! Sorry we took so long to get to it -- it's a good feature request.


/dup #9996
