### ISSUE TITLE
Find binding cannot be removed

### ISSUE THREAD

**Issue by LuisPeregrinaPSL** [microsoft/terminal#10487]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Change the binding for Search (default: ctrl+shift+f) to ctrl+shift+g.
Save.
Reopen Windows Terminal.

### Expected Behavior

ctrl+shift+f: Nothing, as that combination is not bound.
ctrl+shift+g: Search box appears.

### Actual Behavior

ctrl+shift+f: Search box appears.
ctrl+shift+g: Search box appears.

**Comment by lhecker** [comment]
Did you change this setting in the settings UI, or directly in your `settings.json`?

**Comment by LuisPeregrinaPSL** [comment]
Actions can only be changed in JSON

**Comment by lhecker** [comment]
@LuisPeregrinaPSL There's actually a UI to change actions inside the settings UI now. I just forgot whether 1.8 or 1.9 was the first version to ship that UI (it's 1.9). 🙂
Anyways: You have to explicitly unbind like so:
```json
{ "command": "unbound", "keys": "ctrl+shift+f" },
```

Please let me know if this fixes your issue.

**Comment by LuisPeregrinaPSL** [comment]
Yes, thx, that was it.
