### ISSUE TITLE
terminal: Need option to save session for active systems based on protocol

### ISSUE THREAD

**Issue by Udayendu** [microsoft/terminal#10483]
# Description of the new feature/enhancement
Currently there is no option to save the system's session like SSH or RDP that we are using on daily basis.

# Proposed technical implementation details (optional)
Having folder view based option to save session would be really nice and will make life easier as we should be able to save the login and name it as per our requirement.

Take a look at the below images that mobaxterm is offering as of today.

![image](https://user-images.githubusercontent.com/1809177/122930484-a8266180-d389-11eb-9e3f-1c08476bfe16.png)

![image](https://user-images.githubusercontent.com/1809177/122930793-ea4fa300-d389-11eb-8add-beb5568a1bd8.png)

**Comment by skyline75489** [comment]
See #10193

**Comment by Udayendu** [comment]
Okay. Closing this as it cant be implemented.
