### ISSUE TITLE
Invalid handling emoji with zero-width-space and \u200b zero-width-space character.

### ISSUE THREAD

**Issue by zagura** [microsoft/terminal#10495]
### Windows Terminal version (or Windows build number)

10.0.18363.1556, 1.8.1521.0

### Other Software

OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, (inside WSL)

### Steps to reproduce

1) echo Some$'\u200b'Text
2) echo "🖼"and https://example.com
Second symbol is framed-picture emoji: https://emojipedia.org/framed-picture/

### Expected Behavior

1) Some​Text (without visible space)
2) No additional space after emoji and link https://example.com is clickable, so Ctrl + LPM would open https://example.com URL.

### Actual Behavior

1) Some Text (encoded correctly, but displayed space between words)
2) Displayed text has additional space between emoji and "and" word. When mouse hoover, underline is moved one character to right, so here it would underline ttps://example.com (and empty character after URL). Ctrl + LPM would try to open invalid URL ttps://example.com.

**Comment by DHowett** [comment]
Thanks! This is a huge class of issue that we're tracking in /dupe #1472 and #3546 :smile:
