### ISSUE TITLE
startingDirectory in wsl profile is causing windows terminal to hang with DesktopWindowXamlSource symbol

### ISSUE THREAD

**Issue by mguptawork** [microsoft/terminal#10491]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

WSL Ubuntu 18.04

### Steps to reproduce

In the wsl profile add a startingDirectory parameter:
`"startingDirectory" : "//wsl$/Ubuntu-18.04/home/<username>"`

Replace username with your wsl username

### Expected Behavior

Successfully open the terminal

### Actual Behavior

Terminal did not open, task bar icon shows DesktopWindowXamlSource

**Comment by alanaasmaa** [comment]
Can confirm, same issue.

**Comment by skyline75489** [comment]
Did you try to open the terminal at system startup? What's the Windows version you're using?

I can't seem to repro this locally.

**Comment by DHowett** [comment]
We've addressed this in the 1.9 preview, which will be moving to stable soon. People haven't universally loved our resolution, but it _is_ at least self-consistent.

The backlash will be loud and swift, but at least we will not hang on startup any longer.
