### ISSUE TITLE
Update to WinUI 2.6 (prerelease)

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10508]
As title.

_migrie note:_
* If https://github.com/microsoft/microsoft-ui-xaml/pull/3769 is fixed before we ingest the latest MUX, check if #7133 and #8948 are fixed
* https://github.com/microsoft/microsoft-ui-xaml/pull/5145 may have also fixed #7133, but I think that's only in 2.7

**Comment by WSLUser** [comment]
Any chance of spinning up a branch testing out WinUI3? I would assume stuff like Mica would also be included with WinUI3 as it makes little sense to offer features in a lower version without first having it in the latest.

**Comment by DHowett** [comment]
It would have been very easy for you to find in many issues across our repo the reasons WinUI3 is unsuitable for Terminal :smile:

**Comment by WSLUser** [comment]
They just had another release today. https://github.com/microsoft/microsoft-ui-xaml/issues/5260

**Comment by DHowett** [comment]
Trust when I say that we are in nearly constant contact with them about our requirements. _WinUI 3 is not suitable for Terminal, and will likely remain unsuitable for Terminal for some time._
