### ISSUE TITLE
Split pane copy current path 

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#10500]
Now , new split pane would start at  user home . It would be ideal to have an option

1. go to same path if not in ssh
2. duplicate ssh connection if base pane is on ssh

**Comment by skyline75489** [comment]
The first scenario is possible. See https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033

The second scenario I believe is not possible at the moment.

**Comment by zadjii-msft** [comment]
Yea, you can totally duplicate a pane today. As mentioned above, you'll need to make sure your shell is configured correctly. 

The second part is a **H**ard/impossible problem. I'm pretty sure there's not a good way of duplicating an arbitrary SSH connection. The best way to do that would be to create a profile for that `ssh` commandline, and then just duplicate that profile.
