### ISSUE TITLE
Colored Italic letter rendering issue

### ISSUE THREAD

**Issue by chrisdcao** [microsoft/terminal#10503]
### Windows Terminal version (or Windows build number)

10.0.19042.1052

### Other Software

Ubuntu WSL, using Vim inside the terminal

### Steps to reproduce

Use either Fira Code, Monaco, or Ubuntu Mono at any size, and use a theme that has italic highlight in type (monokai.vim with italic turned on or dark_plus.vim) will successfully render the issue.

But the issue does not occur in italicized comment..

### Expected Behavior

The letter 'd' will not be cut off part of it (like in the comment)

### Actual Behavior

The letter 'd' being cut off part of it (the highlighted type above)
![Screenshot_31](https://user-images.githubusercontent.com/68319923/123159786-9df28900-d497-11eb-95b0-8298eca5520f.png)

**Comment by chrisdcao** [comment]
The smaller the font, the worse the problem, but the issue's not happening in the comment area. My guess is the bright colors are being rendered differently to fit the pixel grid?

![Screenshot_32](https://user-images.githubusercontent.com/68319923/123160073-f590f480-d497-11eb-94a0-63a7a8110efc.png)

**Comment by norcalli** [comment]
The color transition between words is probably the culprit, being a different scissor area, would be my guess. The comment is all the same color.

**Comment by j4james** [comment]
See also #9381, which is essentially the same issue.

**Comment by chrisdcao** [comment]
yea I would close this one then! Any track would be moved to #9381
