### ISSUE TITLE
Starting Terminal from File Explorer Adressbar

### ISSUE THREAD

**Issue by Postlagerkarte** [microsoft/terminal#10504]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

Using the File Explorer to start the Terminal from the adressbar:

![image](https://user-images.githubusercontent.com/8482283/123250357-416c8980-d4ea-11eb-9401-c33e853381d9.png)

I can type WT in the adressbar to start the terminal. This works.

However, I expect the working directory to match the adress bar. This works when I type cmd in the adress bar. Typing wt always starts with the same working directoy regardless of the location of file explorer.

Please advise!

### Expected Behavior

Starting a terminal with the correct working directory taken from the adressbar. Same as cmd does.

### Actual Behavior

Terminal ignores file explorer addressbar location.

**Comment by jack775544** [comment]
This has been discussed a great deal in the past but the solution that has been landed on is to either type `wt -d .` into the address bar or to tick 'Use parent process directory' in your profile settings.

**Comment by Postlagerkarte** [comment]
Thx!
