### ISSUE TITLE
A proper Unicode Font setting

### ISSUE THREAD

**Issue by ndrogers** [microsoft/terminal#10510]
# Description of the new feature/enhancement

I often work with unicode, and as anyone who uses unicode can attest, there aren't many fonts that support really nice unicode glyphs. I have seen the feature request for supporting multiple fonts, as Visual Studio Code does, which allows the user to specify a list of fonts. When a glyph is missing from the first font, VSCode allows missing characters to be rendered using subsequent fonts in the font-family. This feature request has been sitting around for a good few years without movement. 

**Instead of waiting for that feature to never be implemented**, I had an alternative idea that might be an easier fix. I want a second font property in the settings. When there is no glyph available in the `primaryFont`, the `unicodeFont` will be used to render the missing glyph. 

```js
//settings.json
{

    ...,
    "PrimaryFont": "My Favorite Monospace Font",
    "UnicodeFont": "My Nice Unicode Font",
    ...
}
```

# Alternative approach
You could very well just give me a hotkey to toggle between a `primaryFont` and `secondaryFont` so that I can switch when I need to, instead of constantly having to keep my settings file open and manually switch between them.

**Comment by SamHasler** [comment]
I think it would be better if Windows made configuring [font linking](https://docs.microsoft.com/en-us/globalization/input/font-technology#font-linking) easier. Then these fonts would be available to all editors / terminals.

>  in font linking (also called “composite fonts”) it is possible to link one or more fonts (called "linked fonts") to another font (called the "base font"). Once you link fonts, you can use the base font to display code points that do not exist in the base font, but that do exist in one of the linked fonts. 

I've created an issue for it in Microsoft Power Toys repo:
https://github.com/microsoft/PowerToys/issues/11933

**Comment by WSLUser** [comment]
You may enjoy https://github.com/microsoft/terminal/pull/10525 when it's merged.

**Comment by zadjii-msft** [comment]
This sounds like

/dup #1790
/dup #2664
