### ISSUE TITLE
Terminal Breaks Mouse Behavior and Keeps Text Editor In Same Pane as History

### ISSUE THREAD

**Issue by ducksoverip** [microsoft/terminal#10514]
I recently installed Windows Terminal and added Git Bash as my main profile.  I've noticed that when opening a file in a command-line text editor like nano or Micro, Terminal opens the text editor in line with previous file opens like so:
![image](https://user-images.githubusercontent.com/72049336/123454440-2e1ef400-d5a6-11eb-805e-d957314c29e0.png)
As can be seen above, the current session of the Micro editor displays directly underneath the previous (now-closed) session of the editor, letting you scroll up to see screen it was on when it was last closed.  This behavior breaks mouse-scroll functionality, since instead of moving the cursor through the text in the current session, it simply scrolls the screen up to show what the last session looked like, which is very annoying.  Furthermore, it further breaks mouse functionality in the Micro editor specifically.  Micro normally lets you click text to place the cursor there like modern GUI text editors.  However, when using Micro in Windows Terminal, this behavior is gone completely.  These issues do not arise when using Git Bash by itself, so the issue appears to be unique to Windows Terminal.

Additionally, when scrolling up the history in the main pane for Git Bash, Windows Terminal displays the last visible screens of my text-editor sessions at the top, which is very distracting.

**Comment by zadjii** [comment]
This sounds like a side effect of /dup #381 to me
