### ISSUE TITLE
Command line arg `-w` minimizes the active window when run from windows terminal preview

### ISSUE THREAD

**Issue by onerandomusername** [microsoft/terminal#10519]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Other Software

Tested with Powershell 7.2.preview, 
Powershell 7.1
Command: 10.0.19043.1081

### Steps to reproduce

- if windows terminal 1.8 is also installed: 
 set the wt execution alias to be for windows terminal
- open up a powershell or command profile in windows terminal preview
- run `wt -w 0 nt`

### Expected Behavior

Windows Terminal Preview stays unminimized and focused and opens a new tab and focus is switched to it.

### Actual Behavior

windows terminal preview minimizes the current window.

**Comment by lhecker** [comment]
I'm not sure which PR exactly fixed it, but this issue has definitely been fixed for the upcoming preview version.
I believe this is a dupe of https://github.com/microsoft/terminal/issues/10386

**Comment by DHowett** [comment]
I think you're right! This is a /duplicate of #10292. Thanks!

**Comment by DHowett** [comment]
Wait, that tag doesn't work? /dup #10292
