### ISSUE TITLE
Option to disable the error sound blasting in my ears whenever pressing backspace in an empty terminal window.

### ISSUE THREAD

**Issue by notbluu** [microsoft/terminal#10517]
# Description of the new feature/enhancement

An option that allows us to disable the error sound to play whenever we press backspace on an empty terminal session.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
If you want to disable the bell sound in general, you can configure the [_Bell Notification Style_](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#bell-notification-style) in Windows Terminal.

If you just want the bell disabled when pressing backspace, that's typically a feature of your shell. For example, in bash I think you can disable it by setting the `bell-style` option in `/etc/inputrc`, although that'll probably also disable the bell for other error conditions on the command line. If you need finer control than that, you'd best consult the documentation for whichever shell you're using.

**Comment by j4james** [comment]
It's also worth mentioning that you can control the volume in Windows on a per-application basis. So if you like having other sounds blasting in your ears, but not sounds from the terminal, you can use the Windows volume mixer to set the relative volume of the terminal to a fraction of the system volume.

**Comment by DHowett** [comment]
All of the above is correct :smile: Thanks!
