### ISSUE TITLE
focus and tabbing on split panes is unintuitive 

### ISSUE THREAD

**Issue by onerandomusername** [microsoft/terminal#10524]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Open up four split panes, in a 2 by 2 fashion. For ease of use, and to ensure everyone has the same set up, use the command below.
` Start-Process wt "nt ; sp -V ; mf left ; sp -H ; mf right ; sp -H"`
Should look like this: 
![image](https://user-images.githubusercontent.com/71233171/123697507-0096ac80-d82b-11eb-9670-6272825f4f0d.png)

Now, move focus to the bottom left pane. This can be done by mousing over the bottom left pane.
With the default action configured, press alt + right arrow. 
If you have reconfigured your actions, press the keybind to move pane focus to the right. `{ "action": "moveFocus", "direction": "right" }`

### Expected Behavior

The active pane is now the one on the bottom right.

### Actual Behavior

The active pane is the one on the upper right.

**Comment by PankajBhojwani** [comment]
Yep, currently we move focus to the first pane on the other side of the separator. We are tracking the issue over at /dup #2398
