### ISSUE TITLE
Run on other OS

### ISSUE THREAD

**Issue by Emojigit** [microsoft/terminal#10527]
# Description of the new feature/enhancement

I love the UI of Windows Terminal, but I am currently using Linux Ubuntu. There are no way to compile it in linux (at least in the doc). Please add the support (or docs) of compiling it on other OS such as MacOS and Linux.

# Proposed technical implementation details (optional)

N/A

**Comment by skyline75489** [comment]
Glad you like Windows Terminal! But sadly there's no plan to port the application to other platforms.

/dup #2331 #504 #563 #624 #2466 #699 #498 #6074 #4235
