### ISSUE TITLE
In Win11 first beta and con-host set as terminal Preview, .bat scripts in Windows startup folder results in error

### ISSUE THREAD

**Issue by vaualbus** [microsoft/terminal#10523]
### Windows Terminal version (or Windows build number)

10.0.22000.51

### Steps to reproduce

First in a updated build, open cmd.exe and select  Terminal preview as a host,  than when reboot If you have some .bat files in the windows startup folder  the following error occur when you login: the application as unable to  start  (0xc0000142).
(Oh and the error box have the Ok button not rounded, but that is another bug).

The problem was not occurring when the cmd.exe was not changed.

### Expected Behavior

No error occur and the .bat script is execute with no issues.

### Actual Behavior

the following error occur when you login: the application as unable to to start  (0xc0000142).
(Oh and the error box have the Ok button not rounded, but that is another big).

**Comment by DHowett** [comment]
Thanks! /dup #10453

**Comment by vaualbus** [comment]
> Thanks! /dup #10453

You are welcome!
