### ISSUE TITLE
Open terminal via context menu doesn't pickup PATH variable

### ISSUE THREAD

**Issue by chungweileong94** [microsoft/terminal#10526]
### Windows Terminal version (or Windows build number)

10.0.22000.0,  1.8.1521.0

### Steps to reproduce

- Open a target folder
- Right-click and open "Windows Terminal"
- Then run commands like `yarn` (the `yarn` is installed via `npm i -g yarn`)

### Expected Behavior

It should able to run the `yarn` as the global node_modules is defined in PATH settings on Windows.

### Actual Behavior

The terminal doesn't recognize the command.
![image](https://user-images.githubusercontent.com/15154097/123735315-95ec7c00-d8d1-11eb-9bcf-a6530aee1bdc.png)

However, it works fine if I open the Windows Terminal via the start menu, and navigate to the targeted folder

**Comment by DHowett** [comment]
Terminal inherits the `PATH` from its parent process... which in the case of the shell extension should be Explorer. Hm.

**Comment by chungweileong94** [comment]
After playing with the Windows 11 insider build, it did happen occasionally.

**Comment by DHowett** [comment]
This will probably go away when we properly handle regenerating the environment block. We try to do it in Preview with mixed success. The stable builds don't do it, which causes the behavior you're seeing here.

We're tracking completion in /dup #1125.
