### ISSUE TITLE
Snap Groups doesn't work with Windows Terminal on Windows 11

### ISSUE THREAD

**Issue by itsme-alan** [microsoft/terminal#10529]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.9.1523.0, Windows 11 10.0.22000.0

### Steps to reproduce

- Install Windows 11
- Try to use the snap groups feature by hovering on the maximize button in Windows Terminal

### Expected Behavior

Snap groups should pop up

### Actual Behavior

Tooltip pops up instead

![screenshot of the actual behavior](https://user-images.githubusercontent.com/75578443/123792747-9818ff80-d8fe-11eb-96ca-8dc61ef120dc.png)

**Comment by NicTanghe** [comment]
I don't think the feature in on already in the entire os,
At least 4 me it doesn't work anywhere.

**Comment by sean-was-taken** [comment]
It seems to be the "Hide the title bar" setting causing the issue. Disabling that fixes the issue. 
![2021-06-29](https://user-images.githubusercontent.com/86674443/123824424-e2748f00-d8b2-11eb-9445-24a892c8ee7d.png)

**Comment by itsme-alan** [comment]
But I don't want that hideous title bar

**Comment by itsme-alan** [comment]
There is no way I could have figured out this was a dup of #9443

**Comment by itsme-alan** [comment]
Bot is not working or something? I will close it myself I guess

**Comment by DHowett** [comment]
Thanks :smile:

**Comment by NicTanghe** [comment]
Why close if the issue is not resolved?

Just because there is a workaround doesn't mean the issue is solved.

Op di 29 jun. 2021 om 17:30 schreef Dustin L. Howett <
***@***.***>:
