### ISSUE TITLE
[error 0x800700c1 when launching `C:\Program Files\PowerShell\7\pwsh.exe']

### ISSUE THREAD

**Issue by darrenjrobinson** [microsoft/terminal#10536]
### Windows Terminal version (or Windows build number)

1.8.1521.0, 1.9.1523.0

### Other Software

Windows 10 Pro
Version 2004 (OS Build 19041.1052)

![Windows Terminal Version 1 8 1521 0](https://user-images.githubusercontent.com/384733/123900256-167fab00-d9ac-11eb-8bf8-e79f136fb1ca.png)

![Windows Terminal Version 1 9 1523 0](https://user-images.githubusercontent.com/384733/123900451-71b19d80-d9ac-11eb-9159-162a8fd05874.png)

### Steps to reproduce

Windows Terminal
* PowerShell installed in C:\Program Files\PowerShell\7 
* PowerShell the default windows terminal profile
* Open Windows Terminal with PowerShell as the default profile.

![error 0x800700c1 when launching pwsh exe](https://user-images.githubusercontent.com/384733/123900339-3d3de180-d9ac-11eb-8f6a-f5e71a6abd7d.png)

### Expected Behavior

Windows Terminal open PowerShell console.

![PowerShell Opening as Default in Windows Terminal](https://user-images.githubusercontent.com/384733/123900354-429b2c00-d9ac-11eb-9ecd-df656c58e1ab.png)

### Actual Behavior

![error 0x800700c1 when launching pwsh exe](https://user-images.githubusercontent.com/384733/123900162-e2a48580-d9ab-11eb-9175-25511322fcaa.png)

**Workaround**
Find the 8.3 path to the directory with the space (dir /x)
Update the Windows Terminal Profile for PowerShell to use the 8.3 Path

![Updated Path for PWSH in Windows Terminal Default Profile PowerShell](https://user-images.githubusercontent.com/384733/123900232-0bc51600-d9ac-11eb-8ebb-042a75f6e6b7.png)

Success

**Comment by DHowett** [comment]
You have a file or folder called "C:\Program".

**Comment by darrenjrobinson** [comment]
WWDYK. The damn Citrix Receiver Application installer update has generated an install log to a file named **program** in the root of C:\ 😡
Thx, closed.

**Comment by vakkalanka123** [comment]
![image](https://user-images.githubusercontent.com/100380463/164273214-2ede83b0-7ce5-4d54-86d2-2798027a2c44.png)
Can anybody help me with this error
