### ISSUE TITLE
the power of WT 

### ISSUE THREAD

**Issue by velocirraptor5** [microsoft/terminal#10532]
is just an image of my daily view of WT, i liked so much so I want to share it whit you
![Captura de pantalla 2021-06-17 165703](https://user-images.githubusercontent.com/48321345/123871657-8bde7380-d8f9-11eb-9e44-26e2c95b532d.png)

**Comment by PankajBhojwani** [comment]
Thank you! Great to hear that you enjoy using it :)

**Comment by skyline75489** [comment]
This would make a nice reddit post. Just saying 😄 

https://www.reddit.com/t/windows_terminal/
