### ISSUE TITLE
Using tmux long text overwrites other pane

### ISSUE THREAD

**Issue by pcause** [microsoft/terminal#10538]
### Windows Terminal version (or Windows build number)

Version: 1.9.1523.0

### Other Software

tmux
fedora container under wsl
win11

### Steps to reproduce

I start tmux and have 2 panes.  I am in the right pain.  An app runs and has an error output and the line is long and it overflows into the left pane.

Didn't happen with previous version

### Expected Behavior

Text is wrapped or truncated

### Actual Behavior

text flows into other pane

**Comment by skyline75489** [comment]
Can you post a screenshot? Does it always repro for you?

**Comment by pcause** [comment]
![image](https://user-images.githubusercontent.com/1071479/124106678-f6a3c200-da53-11eb-8ea6-13ddc845d14d.png)

yes, this always happens to some degree.  two panes both enpty.  went to right pane. launched cairo dock and you can see the text flowing over left pane.

**Comment by skyline75489** [comment]
Seem to me you have some resize happening in your screenshot? Do you resize the Terminal window, or the pane in tmux?

**Comment by pcause** [comment]
I opened windows terminal and then resized.  i then opened tmux and panes, but didn't resize the panes or terminal at all after the initial resize

**Comment by skyline75489** [comment]
If you don’t resize anything, does it still happen?

**Comment by zadjii-msft** [comment]
This looks exactly like 

/dup #6987
