### ISSUE TITLE
Midnight commander with mouse in screen

### ISSUE THREAD

**Issue by CyrusJoudieh** [microsoft/terminal#10530]
Running mc in ssh without the screen app the mouse works as expected without issues in small window, maximized window and full screen.

When running mc inside the screen app the mouse is responsive only in half of the Windows Terminal window from left to middle. 
If resizing the Windows Terminal window to half of the monitor screen the mouse works on the entire Windows Terminal window.
If resizing the font when pressing [ctrl - +] to the maximum in a maximized window the mouse works on the entire Windows Terminal window.

The mouse works fine in screen with Putty.

Windows Terminal Preview 1.9.1523.0
Remote OS: Centos 8 stream

Screen environment variables:
TERM="screen.xterm-256color"
DISPLAY="xterm" or DISPLAY="_"

**Comment by DHowett** [comment]
This is likely due to screen requesting legacy mouse mode, which only supports coordinates up to 93 or something small (perhaps with additional limitations because of UTF-8...).

What is `TERM` _outside_ of screen?

**Comment by cyrusjoudieh** [comment]
Its TERM="xterm-256color"

**Comment by j4james** [comment]
Also check what version of screen you're using. I believe that support for SGR mouse mode was added in version 4.7.0, so anything after that should be fine. That said, I couldn't get the mouse in mc to work at all unless I changed the TERM in screen to xterm-256color, so I suppose another explanation may be that the term info is just out of date.

**Comment by cyrusjoudieh** [comment]
The screen version installed is: 4.06.02 (GNU) 23-Oct-17

Will try to get the latest version of screen and test it.

I had to add an environment variable DISPLAY="_" or DISPLAY="xterm" to enable the mouse in mc or use the command line "mc -x".

**Comment by cyrusjoudieh** [comment]
Can confirm that its working fine under Screen version 4.08.00 (GNU) 05-Feb-20

Thank you!
