### ISSUE TITLE
Inline visualization of images

### ISSUE THREAD

**Issue by montyvesselinov** [microsoft/terminal#10541]
Is it possible to produce incline visualization of images? If not is it possible to develop these capabilities?

Currently i use mac os x + iterm2 + TerminalExtensions.jl to produce this:

<img width="581" alt="Screen Shot 2021-07-01 at 7 45 39 AM" src="https://user-images.githubusercontent.com/5632376/124134853-7e7fd100-da40-11eb-9b8d-48d1fd6affd4.png">

Can i replicate this in your terminal?

**Comment by j4james** [comment]
There are existing issues for image support. See #5746 and #448.

However, note that the `TerminalExtensions` module is designed specifically for use with iTerm2, so even if we supported the iTerm2 image format it probably wouldn't work as is. If you want cross-platform image support, you're probably better off using one of the Julia sixel modules, which are more likely to work on a variety of terminals.

**Comment by montyvesselinov** [comment]
TerminalExtensions is a ripoff of an alternative python package. I know it is designed for iterm2. 

Note that there are several other packages:

https://github.com/JuliaImages/ImageShow.jl

https://github.com/JuliaImages/ImageShow.jl

There is also Sixel.jl

**Comment by j4james** [comment]
If you're happy with the sixel packages, then that should be covered by issue #448.
