### ISSUE TITLE
Windows terminal stays in task manager after closing

### ISSUE THREAD

**Issue by peach-lasagna** [microsoft/terminal#10542]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

1. Open multiple tabs
2. Click here
![изображение](https://user-images.githubusercontent.com/59787538/124175045-48d9f700-dad7-11eb-8f07-d21169e1ed58.png)

### Expected Behavior

windows terminal closed completely

### Actual Behavior

![изображение](https://user-images.githubusercontent.com/59787538/124174654-d701ad80-dad6-11eb-8731-770ac18921c6.png)

**Comment by peach-lasagna** [comment]
This does not always happen, I still do not understand what it depends on.

**Comment by skyline75489** [comment]
This is similar to what's seen in #10491

**Comment by peach-lasagna** [comment]
> This is similar to what's seen in #10491

sorry, bad looking
