### ISSUE TITLE
ConPTY does not pass cursor blinking VT sequence (`DECSET/DECRST 12`)

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#10543]
### Windows Terminal version (or Windows build number)

1.8

### Steps to reproduce

In powershell, enter:

"`e[?12l"

### Expected Behavior

Cursor should stop blinking

### Actual Behavior

Cursor continues to blink

**Comment by skyline75489** [comment]
Quick question: how about https://github.com/microsoft/terminal/issues/1379#issuecomment-735371952 ?

**Comment by DHowett** [comment]
That's just a workaround. We should also pass DECSET 12 through ConPTY!

**Comment by DHowett** [comment]
@PankajBhojwani yours if you want! (Do you want it?)

**Comment by PankajBhojwani** [comment]
> (Do you want it?)

I'll take it!
