### ISSUE TITLE
Hard exit (sometimes?) when changing to Windows High Contrast theme

### ISSUE THREAD

**Issue by Uxorious** [microsoft/terminal#10548]
### Windows Terminal version (or Windows build number)

10.0.19043.1081, slightly newer than 1.8.1444.0 (store updated, but nothing shows the new version which was 1521 or 1523 I think)

### Steps to reproduce

Change Windows High Contrast theme on/off.

### Expected Behavior

Only the contrast scheme should change.

### Actual Behavior

Terminal disappeared.
It happened to me 2 times ... when I turned the High Contrast mode on, and later when I turned it off again.
Haven't tried since that.

**Comment by zadjii-msft** [comment]
A feedback hub crash dump would be helpful in narrowing down the root cause:

/feedback

**Comment by Uxorious** [comment]
Hmm it so happens that this laptop had Feedback Hub uninstalled :-(
I looked for dump files but didn't find any.
Guess I'll try reproducing again.
