### ISSUE TITLE
F2 Shortcut key for renaming focused tab

### ISSUE THREAD

**Issue by sheharyarshahid** [microsoft/terminal#10540]
# Description of the new feature/enhancement
A shortcut key for renaming the currently focused tab most probably the **F2** key

Currently, users have to right-click the tab to rename it, and renaming a large number of tabs can be frustrating especially by using a mouse. This enhancement can let users rename the tab without leaving the keyboard.

# Proposed technical implementation details (optional)

**Comment by zadjii** [comment]
There's already the [`renameTab`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#rename-tab) action

**Comment by DHowett** [comment]
Yep!

If you add the following action/key binding to your settings.json, it will work:

```
{ "command": "openTabRenamer", "keys": "f2" },
```

**Comment by sheharyarshahid** [comment]
Worked 😊
