### ISSUE TITLE
Make it possible to choose between a font's stylistic sets

### ISSUE THREAD

**Issue by JakobBruenker** [microsoft/terminal#10557]
# Description of the new feature/enhancement

OpenType fonts often have stylistic sets that allow users to choose specific alternate characters - for example, old-style numerals instead of lining figures. However, this requires support by the software the font is used with, which is already the case with many editors and terminal emulators.

It would be great if such support were added to Windows Terminal.

This could be a comma-separated option for `"profiles"` in `settings.json`, e.g.

```
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "fontFace":"Fira Code Retina"
            "stylisticSets":"ss01,ss03,zero,onum"
        },
<...>
    }
```

**Comment by DHowett** [comment]
You are really going to like #10525!

**Comment by JakobBruenker** [comment]
@DHowett Oh, nice, thank you
