### ISSUE TITLE
Extremely slow performance when processing virtual terminal sequences, continued

### ISSUE THREAD

**Issue by procedural** [microsoft/terminal#10555]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

https://github.com/cmuratori/termbench/releases/tag/V1

### Expected Behavior

[<img src="https://img.youtube.com/vi/hxM8QmyZXtg/maxresdefault.jpg" width="100%">](https://youtu.be/hxM8QmyZXtg)

### Actual Behavior

https://github.com/microsoft/terminal/issues/10362

**Comment by procedural** [comment]
https://github.com/microsoft/terminal/issues/10362

**Comment by procedural** [comment]
To prevent a Microsoft intern from passively-aggressively labeling this issue as off topic, please stay on topic.

**Comment by skyline75489** [comment]
Hi! We have #10462 for this. Do you mind redirecting the discussion to that thread?

**Comment by skyline75489** [comment]
> To prevent a Microsoft intern from passively-aggressively labeling this issue as off topic, please stay on topic.


Rest assured, only very limited number of people have the authority to do that.

**Comment by procedural** [comment]
> Hi! We have #10462 for this. Do you mind redirecting the discussion to that thread?

Sure, I was not aware of it. Closing as a duplicate.
