### ISSUE TITLE
Processes still active after closing the tab

### ISSUE THREAD

**Issue by gonzalologorg** [microsoft/terminal#10558]
### Windows Terminal version (or Windows build number)

Terminal Version: 1.9.1523.0  - Windows 11: 10.0.22000.0

### Other Software

NodeJS v16.4.0
MySQL (Xampp)
VSCode

### Steps to reproduce

-Open a bat file running a nodejs project
node init.js
-Attempt to close the tab (closing the tab/ctrl+c)

### Expected Behavior

-Close the tab
-The process it's finished
-Pressing CTRL+C
-Are you sure do you want to exit this process?

### Actual Behavior

When closing the tab, the process it's still active
When pressing ctrl+c the console attempts to copy the content

**Comment by zadjii-msft** [comment]
> When pressing ctrl+c the console attempts to copy the content

That should only happen when you have text selected in the Terminal - what happens when you press ctrl+c _without_ text selected?
