### ISSUE TITLE
Wrong characters when typing emoji from Windows touch keyboard

### ISSUE THREAD

**Issue by z-rui** [microsoft/terminal#10551]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

1. Open a Linux shell in Windows Terminal.
2. Open Touch Keyboard
3. Choose emoji keyboard and type 😁, or some other emoji.

(Note: the problem does not exist if the emoji is typed from the "Win+." panel, but only from the touch keyboard.)

![Screenshot 2021-07-02 183205](https://user-images.githubusercontent.com/7368209/124339537-fa266e80-db63-11eb-8327-cae9d617a978.png)

### Expected Behavior

See 😁 on the command line.

### Actual Behavior

Saw 翿翿 on the command line
![Screenshot 2021-07-02 183234](https://user-images.githubusercontent.com/7368209/124339540-04e10380-db64-11eb-8ea6-95eec0c704d1.png)

**Comment by Poopooracoocoo** [comment]
@zadjii-msft but it doesn't sound right for this to only be fixed in a version of Windows that cannot run on many devices. :/

**Comment by j4james** [comment]
FYI, this looks like the same bug as #12977, which was fixed in PR #13667. As long as you have Windows Terminal version 1.15 or later it should also be working correctly in Windows 10. I'm also still on Windows 10 and it definitely works for me.
