### ISSUE TITLE
Tab title changes to `C:\WINDOWS\system32\cmd.exe` once I do `npm run dev`

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/terminal#10554]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Just install a new Next.js project using https://nextjs.org/docs/getting-started#setup & run `npm run dev` in Terminal.

You'll see the terminal name changes to `C:\WINDOWS\system32\cmd.exe`

### Expected Behavior

I want the terminal name to be the folder name just like it is in all the other terminals. Even Git Bash has the `cwd` as the terminal name.

### Actual Behavior

Terminal name is `C:\WINDOWS\system32\cmd.exe`

**Comment by skyline75489** [comment]
Does #8448 helps explaining this?

**Comment by deadcoder0904** [comment]
It explains that it is not possible & says that `npm` should fix it but I'm really not sure if it's an `npm` issue as rest of the terminals work fine.

**Comment by DHowett** [comment]
Thanks for the report! If you don't want the application to be able to control (or reset!) the title, you may want to enable this setting:

![image](https://user-images.githubusercontent.com/189190/124981373-1b230f80-dffb-11eb-9fe5-c1b72cd86a6b.png)

**Comment by deadcoder0904** [comment]
@DHowett is there a way to set the folder name on the title? There is a `Tab Title` property but I can't get it to point to `cwd` or `pwd`. I tried using `%__CD__%` & `%__CURRENT_DIRECTORY__%` which I found online but it doesn't work. Google doesn't help much.

![image](https://user-images.githubusercontent.com/16436270/125025808-f4b7af80-e0a0-11eb-81de-9d595c3a4776.png)

**Comment by deadcoder0904** [comment]
It seems like [this is the solution](https://devblogs.microsoft.com/powershell/setting-the-console-title-to-be-your-current-working-directory/).

```
function Prompt
{
  $host.ui.RawUI.WindowTitle = $(get-location)
  “PS> “
}
```

But idk where do I put it?

**Comment by skyline75489** [comment]
@deadcoder0904 Try put it in where `echo $PROFILE` shows you.

**Comment by deadcoder0904** [comment]
Thanks, @skyline75489 that works but the solution is incorrect. Mind pointing me out to setting Tab title to `cwd` or `pwd`? Again, Googling leads to useless results.
