### ISSUE TITLE
Feature Request: Save current config as Initial

### ISSUE THREAD

**Issue by Kryptryx** [microsoft/terminal#1056]
# Summary of the new feature/enhancement

An option on the drop-down menu to save the current config as the initial config. In particular, the overall window position and size, and which tabs are open, and the current font size/rows/columns since it may be zoomed in/out.

I move the main window around. I resize it. I do the ctrl-scroll to get the font size where I need it. I open my preferred tabs in the preferred order. Then I want to say 'save this, and start here next time'. Not quite the same as 'restore how it was when I exited' (another fine feature).

I see there is an 'export settings' feature. This would be more of an 'export' followed by immediate import, presumably skipping the exported file.

**Comment by binarycrusader** [comment]
This feels strongly related to #766 and #1043.

**Comment by fishzle** [comment]
I think there are too many options and not one clear path through this wood.
KISS.

wt must not become a swiss-army knife of terminals. XTerm grew to have a billion options, so people wanted to have something lightweight and simple.

Please stay true to purpose. "a better cmd / console" (or whatever it was when you started).

**Comment by jamietre** [comment]
There should be at least a way to restore the open tabs/window split state, and current directories of each terminal. This feature is found on popular terminals for other platforms, e.g. iTerm2 on OSX and Guake on Linux. Since this is a very small amount of data, it could easily just be stored in the config file, allowing users to self manage it.

**Comment by zadjii-msft** [comment]
Looking over this issue again, and I think we may want to just close this out. We've got [`"firstWindowPreference": "persistedWindowLayout"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session) which pretty much covers this use case. There are additional follow ups in #9800, and might be a good thread for more discussions.

#11526 is gonna track "add support for creating a command that can reopen this specific set of tabs&panes", which is similar to this (if you don't want to just _always_ restore the existing layout).
