### ISSUE TITLE
Disable "Touch keyboard and Handwriting Panel Service" warning

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#10571]
How I can disable "Touch keyboard and Handwriting Panel Service" warning?
![image](https://user-images.githubusercontent.com/23485114/124705396-7691b800-deaa-11eb-8941-af9f9f89aacc.png)

**Comment by skyline75489** [comment]
Thanks for the report! We currently have #8699 to track this.

**Comment by zadjii-msft** [comment]
Yep, /dup #8699.

You can also just [_enable that service_](https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#keyboard-service-warning).

There's also the `inputServiceWarning` property, added in #9015
