### ISSUE TITLE
Add a setting for disabling "intense is bold"

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#10576]
A follow up to #10498

As discussed at length in other threads, esp #109.

Most recently, from @j4james in #10498:

> I mean choose if you want SGR 1 to select a bold font face or not (basically a way to disable this PR). I suppose you could potentially implement that by allowing users to choose which font weight is bold, and expect them to select the normal font weight, but that seems a bit obscure. For example, in XTerm you can just uncheck the "Bold Fonts" menu, and in Konsole you uncheck the option "Draw intense colors in bold font".
> 
> There are a whole bunch of other variations people may want to configure, e.g. disabling bold-as-bright, or only enabling a bold font when used with the extended colors (i.e. the aix bright colors and the ITU 256/RGB colors). Personally I think the latter is the best default config, since it gives you the standard behaviour for the original 8 SGR colors, while still allowing bold fonts when used with extended colors, but I'd be happy with a simple option to turn this off.

**Comment by DHowett** [comment]
This is a requirement for us to ship 1.10 to stable.

**Comment by skyline75489** [comment]
I'm gonna be honest with you guys. I have no idea how settings work nowadays, and all those XAML things scare the s out of me.  Someone who knows more about how settings work, please take this and I'll thank you personally (over the Internet), I promise.
