### ISSUE TITLE
Round corners on Windows 11 cause blank edges on Windows Terminal

### ISSUE THREAD

**Issue by flsantos01** [microsoft/terminal#10575]
### Windows Terminal version (or Windows build number)

10.0.22000.0

### Steps to reproduce

Just open up the Windows Terminal app.
![Untitled](https://user-images.githubusercontent.com/83983611/124779291-0ae63400-df18-11eb-9155-0af7b690e09a.png)

### Expected Behavior

No blank edges.

### Actual Behavior

The window corner resizing to make it rounder doesn't actually work well on this particular app.

**Comment by flsantos01** [comment]
This problem doesn't happen when executing the Windows Terminal app on dark mode.

**Comment by zadjii-msft** [comment]
Thanks for the feedback! I've made sure to pass this along to the DWM team. They're still hard at work rounding out <sup>heh</sup> the kinks in this feature before the official release.
