### ISSUE TITLE
Integrate ideas to improve performance

### ISSUE THREAD

**Issue by komawoyo** [microsoft/terminal#10579]
https://github.com/cmuratori/refterm/blob/main/faq.md

video of unoptimized terminal being orders of magnitude faster than windows terminal.
https://youtu.be/hxM8QmyZXtg

**Comment by vannomad** [comment]
This is already being handled in #10462 and #10461

**Comment by DHowett** [comment]
Thank you.

We are tracking this feedback and any improvements we make in /dup #10462.
