### ISSUE TITLE
Loading/progress Icon on tab cut off

### ISSUE THREAD

**Issue by josh-65** [microsoft/terminal#10570]
### Windows Terminal version (or Windows build number)

10.0.19043.1081

### Other Software

Using winget install

### Steps to reproduce

1) Install a program using winget
2) Look at icon being cut off half way

### Expected Behavior

The icon shouldn't be cut off

### Actual Behavior

The icon is cut off

![image](https://user-images.githubusercontent.com/26977075/124676152-dcd00800-deb5-11eb-979d-3cdc1a0206a2.png)

**Comment by DHowett** [comment]
Interesting. Can you share a copy of your settings file?

**Comment by josh-65** [comment]
[Windows terminal.txt](https://github.com/microsoft/terminal/files/6773219/Windows.terminal.txt)

**Comment by skyline75489** [comment]
This is #8910, I think.

**Comment by josh-65** [comment]
yeah seems so
