### ISSUE TITLE
Tab disables keyboard input

### ISSUE THREAD

**Issue by rayzchen** [microsoft/terminal#10585]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Other Software

Git Bash (git version 2.31.1.windows.1)

### Steps to reproduce

Open windows terminal
Press tab (on empty line)
Try to type

### Expected Behavior

Tab shouldn't do anything on an empty line

### Actual Behavior

Keyboard input gets disabled

**Comment by zadjii-msft** [comment]
That's certainly unexpected. Is the cursor still blinking after pressing tab? Does pressing something like Space or Enter cause some button to be pressed? Do subsequent <kbd>tab</kbd> keypresses move focus around the various UI elements?

If you type something first, then press <kbd>tab</kbd>, does keyboard input still work?


I have two theories here: 
* the <kbd>tab</kbd> is moving keyboard focus out of the Terminal control, into _something_
* The <kbd>tab</kbd> is triggering completion in `bash`, but bash is hanging when that happens with a blank line (though, I think it should just BEL)

**Comment by rayzchen** [comment]
Cursor still blinks like normal: pauses when pressing keys, blinking when there is no input. (the error happens in plain git bash, so i dont think its because of microsoft terminal though)

**Comment by rayzchen** [comment]
Ok now I am very confused, sometimes if I spam ctrl and alt keys then the keyboard gets "unfrozen" and all keys i typed are displayed.

**Comment by DHowett** [comment]
> the error happens in plain git bash

Interesting. It seems like they're trying to do _something_ when you hit tab . . . but if it happens outside of Terminal, I don't think there's anything we can do about it.

**Comment by rayzchen** [comment]
Where can I find support for this issue?
