### ISSUE TITLE
Progress ring is clipped when tab title is too long

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#10584]
### Windows Terminal version (or Windows build number)

10.0.18363.1500, 1.9.1523.0

### Steps to reproduce

1. Open a `cmd` shell in Windows Terminal.
2. Set the title to something too long to fit in the tab, e.g. `title This is a long title that doesn't fit`.
3. Set the progress indicator, e.g. `echo ^[]9;4;1;100^[\` (where `^[` is entered as <kbd>Ctrl</kbd>+<kbd>[</kbd>).

### Expected Behavior

You should see a full progress ring in the tab indicating 100%.

### Actual Behavior

The left half of the progress ring is chopped off, so it looks like it's only at 50%.

![image](https://user-images.githubusercontent.com/4181424/124919262-e9f01280-dfed-11eb-8809-defdcc4e8d6e.png)

**Comment by skyline75489** [comment]
Thanks James for the report! We have #8910 for this.

**Comment by j4james** [comment]
Sorry, I'm blind as a bat. I looked at all the followup issues in #6700 and somehow completely missed #8910.

**Comment by zadjii-msft** [comment]
lol don't worry about it. Thanks for the detailed report regardless!
