### ISSUE TITLE
"initialPosition" doesn't respect window frame size

### ISSUE THREAD

**Issue by SirHesti** [microsoft/terminal#10583]
### Windows Terminal version (or Windows build number)

Version: 1.9.1523.0

### Steps to reproduce

start wt with "initialPosition": "-1920,0", in the json.

### Expected Behavior

start wt with position on the left Screen of 4

### Actual Behavior

The Window appears ~8 Pixel left from the left side of the Screen

I have 4 Screens attached to my PC

1 2 3 4

3 is the main screen; the wt should appear on screen 2 Top Left.
If you reduce the value from -1920 to -1927, wt will be positioned on screen 1. the position -1927.0 is actually actually there. I have the feeling that the frame of the Windows is included in the calculation, but it is not there: ((

**Comment by zadjii-msft** [comment]
Okay that's a fair complaint. Kinda shocked that no one else has noticed this yet. Thanks!

**Comment by ondrix** [comment]
I'm not sure this is the same issue but with `initialPosition = "0,0"` the terminal window opens like this
![image](https://user-images.githubusercontent.com/10441393/127971120-86253e56-6cd0-47f0-80f2-f2cf75f46b2f.png)

**Comment by DHowett** [comment]
That is indeed the same problem!

**Comment by zadjii-msft** [comment]
This is dangerously close to #10199 so I'm just gonna pull this into 1.11 while I've been looking at these
