### ISSUE TITLE
Screen flashing in vim

### ISSUE THREAD

**Issue by rayzchen** [microsoft/terminal#10586]
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Other Software

vim 8.2 inside git bash (GNU bash, version 4.4.23(1)-release (x86_64-pc-msys))

### Steps to reproduce

Open vim
Press down arrow

### Expected Behavior

Nothing

### Actual Behavior

Whole screen flickers

I have disabled the bell-style in `/etc/inputrc` (`set bell-style none`) which fixes pressing backspace on an empty prompt. But it doesnt disable vim flashing when pressing backspace on an empty line, or pressing down on the last line.

**Comment by zadjii-msft** [comment]
This sounds like just how vim works. See https://stackoverflow.com/questions/5933568/disable-blinking-at-the-first-last-line-of-the-file
