### ISSUE TITLE
Windows 11 Win+X Terminal entries don't work with Terminal Preview

### ISSUE THREAD

**Issue by obrobrio2000** [microsoft/terminal#10595]
### Windows Terminal version (or Windows build number)

10.0.22000.65 (happened also on 10.0.22000.51), 1.9.1523.0

### Steps to reproduce

1) Update to Windows 11 22000.65
2) Uninstall Windows Terminal (stable) and install Windows Terminal Preview
3) Use Win+X entries to open Terminal Preview.

### Expected Behavior

If I have only Terminal Preview installed (and not stable Terminal) Win+X entries ("Windows Terminal" and "Windows Terminal (admin)") should detect that stable Terminal is not installed and open Terminal Preview.

### Actual Behavior

If I have only Terminal Preview installed (and not stable Terminal) Win+X entries ("Windows Terminal" and "Windows Terminal (admin)") don't do nothing.
Feedback Hub link: https://aka.ms/AAd5bx7

**Comment by DHowett** [comment]
We're already working this out with the team that owns Win+X :smile:

Thanks!

**Comment by MartinGC94** [comment]
IMO they should bring back the cmd/powershell shortcuts and simply let the "Default terminal application" setting decide which terminal you would end up in. Or if we can dream a little bigger: Full customization of the Win+X shortcuts without third party programs.

**Comment by obrobrio2000** [comment]
> IMO they should bring back the cmd/powershell shortcuts and simply let the "Default terminal application" setting decide which terminal you would end up in. Or if we can dream a little bigger: Full customization of the Win+X shortcuts without third party programs.

I completely agree with you, that would be a lot better. It can already be done manually with third-party tools (as you mentioned), in fact when I was on Windows 10 I had those two shortcuts (cmd and ps) customized to open the corresponding Windows Terminal profiles (wt.exe -p "Command Prompt" and wt.exe -p "Windows PowerShell"). Can be done also on Windows 11 but I don't want to waste time because every Win+X modification gets reset to default after every update.

However, words aside, I made a suggestion on Feedback Hub about this (hoping Microsoft will take this into consideration): https://aka.ms/AAd5o2p

**Comment by zadjii-msft** [comment]
this might be MSFT:34139006 internally, though there's still discussion about if that's really the right thread or not.

**Comment by dylumian** [comment]
The matter is still unresolved

**Comment by zadjii-msft** [comment]
Yep. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️


Internally I think this was fixed in a recent PR, but I don't believe that'll be in the version of Windows 11 shipping today. I honestly have no idea what the ship cadence is like for Windows 11, so it should be out "eventually". `10.0.22469` does seem like it has the fix.

**Comment by Dhyfer1** [comment]
is there any progress with this issue? I have the same problem and need to know if there is any other way to launch Windows Terminal Preview as administrator in Windows 11?

**Comment by zadjii-msft** [comment]
@Dhyfer1 Yea, this is actually fixed on internal builds. Not sure if that's flowed out to an Insider's release yet.

**Comment by Dhyfer1** [comment]
> @Dhyfer1 Yea, this is actually fixed on internal builds. Not sure if that's flowed out to an Insider's release yet.

Are you saying that Win+X is already working correctly with Windows Terminal Preview? and that we don't know in which Windows Insider channel it is working that way?

**Comment by maicol07** [comment]
@Dhyfer1 I confirm it works in the Insider channel. Don't know in other ones

**Comment by Dhyfer1** [comment]
> @maicol07 I confirm it works in the Insider channel. Don't know in other ones

Thank you for your response. I didn't think the preview version of Windows Terminal would release updates the way Windows does (dev and beta channel users first). 
Then I will have to keep waiting for the Windows+X feature to come to the stable channel.

**Comment by zadjii-msft** [comment]
Yep. FWIW, this was an OS-side fix, not something we could fix in the Terminal itself. Hence why the fix is tied to the OS versions and the OS Insiders channels. 

I'm gonna close this one out, since we've got confirmation that the fix is available in at least some external builds now. Thanks all!
