### ISSUE TITLE
Making the tab feature in Windows Terminal more Chrome like

### ISSUE THREAD

**Issue by erikthegamer1242** [microsoft/terminal#10599]
# Description of the new feature/enhancement

I would like the ability to move tabs across multiple Windows Terminal instances, and if I move a tab out of the instance to create a new window, exactly like Google Chrome does. This would make its that if I log into a machine using ssh and also log into another machine in the same instance and need to view them a the same time I could just drag the tab and it would create a new windows

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+drag+tab) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
