### ISSUE TITLE
restore previous session

### ISSUE THREAD

**Issue by Wobbegong3** [microsoft/terminal#10598]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by Wobbegong3** [comment]
I usually have about a dozen tabs open in Windows Terminal (each with a different profile, name, tab color, directory, etc.).  When I have to reboot (e.g., to install a Windows update) I have to re-open each of these all over again.  I would be great if there was a "restore previous session" option (similar to History -> Restore Previous Session for Firefox or Ctrl+H for Edge or Ctrl+Shift+T for Chrome).

**Comment by lhecker** [comment]
This is a popular request we already have on our backlog. 🙂

/dup #961

**Comment by Wobbegong3** [comment]
My feature request (#10598) would (I expect) be a *LOT* simpler to
implement than what the alleged duplicate (#961) describes.  The latter
talks about restoring the complete state of a previously closed session
(with possibly several layers of CMD and Powershell processes).  I don't
particularly care about a tab's state -- all I'd like is to be able to
easily restore all previously open tabs to their normal initial states.
10598 would of course be necessary as a prerequisite for implementing 961,
but perhaps it could be a first step, and released earlier than the full
961.

**Comment by lhecker** [comment]
I should've maybe marked it as a duplicate of https://github.com/microsoft/terminal/issues/766. 🙂
In either case, what you suggest is exactly what we intend to do: In an initial version we'll only restore the state of the window and its tabs in their initial states, without restoring the exact state in particular. Later on we'll add features like persisting the buffer.

**Comment by Wobbegong3** [comment]
Excellent!!  Thank you.
