### ISSUE TITLE
powershell dose not work

### ISSUE THREAD

**Issue by yachtman74** [microsoft/terminal#10604]
Hi maybe someone help ? please

When I start Terminal app 
[error 0x80070002 when launching `powershell.exe']

When I start PowerShell normal from menu start, working normal
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1023

Damian

**Comment by yachtman74** [comment]
ok :)
I have
fixed
tnx

**Comment by matogih-boop** [comment]
Don't forget to restart your machine after adding powershell to the environment variable
