### ISSUE TITLE
Close settings UI when in focus mode?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10608]
I can get to the settings UI while in focus mode (Shift+F11) with Ctrl+Shift+,

Is there a keystroke to close the settings UI in this situation?

**Comment by vefatica** [comment]
Never mind.  Ctrl+F4 does it.  Could Ctrl+Shift+, be made a toggle?

**Comment by vefatica** [comment]
Maybe even a three-way toggle ...

- If it's not open, open it and switch to it.
- If it's open and you're in it, close it.
- If it's open and you're not in it, switch to it.

Except for the settings UI, I have no (other) use for Ctrl+F4.  All my shells have an "exit" command, and exit<enter> is a single keystroke here.

**Comment by zadjii-msft** [comment]
I mean, all the keybindings now work in the SUI. So you could just close the tab with <kbd>ctrl+shift+w</kbd> (or whatever you have `closePane`/`closeTab` bound to). 

> Maybe even a three-way toggle ...

Meh, I don't really love that. I think it's fine to leave `openSettings` as "open the settings" (which is just a no-op if you're already in the settings). It's not "`toggleSettings`". @DHowett can override my veto though if he so chooses.
