### ISSUE TITLE
Default keybinding for Settings UI and json changed

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#10600]
### Windows Terminal version (or Windows build number)

19042, Master branch

### Steps to reproduce

Build the master branch and launch Windows Terminal. Then also launch Windows Terminal 1.9 Preview.  Open the drop down menu for both and notice the keybinding shown is different. Now open both Settings UI and settings.json. Notice the keybindings have been switched. Not sure what change caused this but as I noticed this, I thought it could get switched back prior to release of 1.9 and 1.10 Preview.

### Expected Behavior

I expected the keybindings to remain the same.

### Actual Behavior

Keybindings were switched around, breaking user habits and expectation of how to open both settings.json and Settings UI.

**Comment by DHowett** [comment]
What bindings are you seeing, and what are you expecting?

We haven't changed the bindings to open the settings UI or settings.json since 1.6, and my terminal still shows <kbd>Ctrl+,</kbd> in the dropdown (open Settings) and <kbd>Ctrl+Shift+,</kbd> in the command palette (open Settings JSON)

**Comment by WSLUser** [comment]
Maybe it's due to my settings.json in Preview having it switched. Before Settings UI. the keybindings were Ctrl+, for settings.json and Ctrl+Shift+, for Settings UI and left it defined after it was made stable. I did rather prefer this way from keyboard memory but maybe others have gotten used to the switch by now.

**Comment by DHowett** [comment]
If you had those bindings in your settings file, they will not be changed. That's how the user settings works -- whatever you specify overrides whatever we specify.

We switched the default bindings around December 2020, but all user bindings have been (and always will be) kept.
