### ISSUE TITLE
Lost synchronization between keyboard controls and visual rendering during UTF-8 MATH SYMBOLS processing

### ISSUE THREAD

**Issue by 5HT** [microsoft/terminal#10613]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19042.1083]

### Other Software

GNU Midnight Commander 4.8.25 (WSL 2)

### Steps to reproduce

Copy math unicode (UTF-8) symbols (e.g. `𝟙`, ) into some text file, run e.g. `mcedit`:

![зображення](https://user-images.githubusercontent.com/144776/125190220-ba871300-e244-11eb-8bdb-a28cca8a832b.png)

### Expected Behavior

No artefacts.

### Actual Behavior

No synchronizion between keyboard controls and visual rendering.

**Comment by j4james** [comment]
I think this might be the same as thing as #6555. Note that `𝟙` is `U+1D7D9`

**Comment by KalleOlaviNiemitalo** [comment]
U+1D7D9 MATHEMATICAL DOUBLE-STRUCK DIGIT ONE is higher than U+FFFF but not fullwidth according to <https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c>, so the problem might be caused by the "Surrogate Pairs" part of <https://github.com/microsoft/terminal/issues/8000>.

**Comment by zadjii-msft** [comment]
Yea, this does sound to be the confluence of those two issues. 

/dup #6555
/dup #8000

thanks!
