### ISSUE TITLE
Windows Terminal doesn't have a RC/RES file or an IDI_APPLICATION

### ISSUE THREAD

**Issue by wbsdty331** [microsoft/terminal#1061]
![image](https://user-images.githubusercontent.com/4280572/58609006-9e2ff280-82d8-11e9-8f82-ad2eb3538c65.png)

Why?

**Comment by DHowett-MSFT** [comment]
Windows Terminal doesn't actually set an icon on the executable. We should fix that!

**Comment by DHowett-MSFT** [comment]
I have repurposed this issue to be the main task tracking adding a resource file.

**Comment by wbsdty331** [comment]
So Should we create a RES file?

**Comment by DHowett-MSFT** [comment]
> So Should we create a RES file?

Yes.

**Comment by DHowett-MSFT** [comment]
Since we're trying to land a reasonable icon for v0.2, I'm taking this on myself and moving it.

**Comment by tacticalmelonfarmer** [comment]
I don't know what  you're looking for, but here's something i threw together: 
![winterm](https://user-images.githubusercontent.com/5360652/59634611-0b7aba80-9104-11e9-8c8b-9fd481ef724a.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the contribution! We have an icon coming down from Microsoft design that we’ll be landing soon. Sorry for the lack of communication here!

**Comment by tacticalmelonfarmer** [comment]
it's all good i was bored and it took 5 minutes at the most
