### ISSUE TITLE
Opening new Terminal in same directory as current terminal

### ISSUE THREAD

**Issue by ShivKJ** [microsoft/terminal#10614]
Hi,

I am currently using Windows Terminal and have added Ubuntu 20.04 in it.

Now suppose I have opened a Ubuntu terminal and want to open a new tab in the terminal such that the current dir on the created tab is the same as that of the current tab.

Let me know how can we do that?

Have tried setting _startingDirectory_ value (in settings.py) to `null`, `"."` etc. but nothing works.

**Comment by LuanVSO** [comment]
there's a lot of guides on how to do it on #3158.
put this on a file and then source it from .bashrc or .zshrc:
https://gist.github.com/LuanVSO/5fa3a7f0df339d8dc5166865df18527f
after that restart your shell and if you press ctrl+shift+D to duplicate the tab it will keep the same directory.

**Comment by skyline75489** [comment]
See https://github.com/microsoft/terminal/issues/10105#issuecomment-842231981
