### ISSUE TITLE
Cannot stand by for a long time with Linux

### ISSUE THREAD

**Issue by Zz-886** [microsoft/terminal#10616]
Cannot stand by for a long time with Linux
Long-term standby requires reconnection, resulting in reduced productivity.
![image](https://user-images.githubusercontent.com/55978588/125194040-17ed8500-e282-11eb-92d3-d8b61a261b10.png)

**Comment by LuanVSO** [comment]
you mean the connection is dropped when the computer goes to sleep and there's a ssh connection open?

**Comment by Zz-886** [comment]
Problem has been solved
![image](https://user-images.githubusercontent.com/55978588/125207305-2bb6dc80-e2be-11eb-9478-8d54af2cb69b.png)

**Comment by skyline75489** [comment]
Glad you solved it! This is more of a SSH issue, rather than a terminal one, though.
