### ISSUE TITLE
Is it possible to use enter keyto relaunch the configured command again after process exiting for exception?

### ISSUE THREAD

**Issue by sshxmz** [microsoft/terminal#10611]
Windows Terminal version:  1.8.1521.0

I use Windows Terminal with ssh.exe to connect my Linux host. I add a profile with specified command ("ssh.exe hostname") .

When connection to the host is closed, ssh process exits. I have to clone or launch a new tab to reconnect. Is it possible to add a feature: when process specified exits, 'enter' key can relaunch the command in the old tab?

Thank you very much.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/4379> may cover this.

**Comment by sshxmz** [comment]
> #4379 may cover this.

Yes, I will follow that request. Thank you.
