### ISSUE TITLE
Certain screen layouts leave a 1-pixel gap between the window top and tabs

### ISSUE THREAD

**Issue by MartinGC94** [microsoft/terminal#10626]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Rearrange your monitors in Windows so that they are offset from each other on the Y axis.
![MonitorLayout](https://user-images.githubusercontent.com/42123497/125269980-8590c400-e309-11eb-9ff9-e750d05487b8.PNG)
Maximize the Terminal on the offset monitor and try dragging the tabs by clicking at the very top of the screen. At certain Y-offsets it will work but at others it won't work.  
I have tried a few different Y offsets on my laptop screen (monitor 1):

- 358: Doesn't work
- 366: Works
- 374: Doesn't work

You can check the monitor positions with this snippet in Powershell:
```
Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Screen]::AllScreens
```

### Expected Behavior

Being able to drag tabs around while clicking at the very top of them.

### Actual Behavior

Clicking in the 1-pixel gap area above the tabs doesn't let you move the tabs around.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7422 for more discussion.

/dup #7422
