### ISSUE TITLE
Size of newly started Quake mode window?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10622]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations 10.0.19042.1083 (2009, 20H2) WindowsTerminal: 1.9.1445.0

### Steps to reproduce

Press Win+` to open the Quake window.

### Expected Behavior

I have two 1920x1080 monitors side by side.  Given that the quake window is on one monitor, I expect NOT to see parts of it on the other monitor.

### Actual Behavior

The Quake mode window is wider than the monitor.  If it's on the left monitor, it's left edge is off the screen and it's right edge (windows highlight/shadow) is on the right monitor ... if it's on the right monitor, it's the reverse of that.  Here's what Windows reports about its positon when it's on the left monitor (1920x1080).

`LTRB:    -8 0 1928 545`

**Comment by vefatica** [comment]
This seems to be a duplicate of #10201.

**Comment by zadjii-msft** [comment]
Yep, sure looks like it. Thanks!

/dup #10201
