### ISSUE TITLE
Animations when Opening New Tab

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10629]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Click to open a new tab

### Expected Behavior

The animation should be smooth, not jarring, and it should not take more than 2 seconds to show the actual tab and the title.

### Actual Behavior

Tab displayed after 2 seconds, when it should be instant. The new tab button moving out of the way is too jarring.

https://user-images.githubusercontent.com/4098042/125301924-15764400-e2f1-11eb-8105-e9417e8572fb.mp4

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8435for more discussion.

From that thread:

Unfortunately, we're just using the TabView as shipped by the Xaml controls team. I found a couple issues on their tracker that we're already subscribed to 😄 so we should get fixes for them when they're available.
> 
> * Opening animation, repaint: [TabView: Tab opening animation not as good as Chromium Edge microsoft-ui-xaml#1999](https://github.com/microsoft/microsoft-ui-xaml/issues/1999)
> * Closing snap/animation (which is partially by-design: the tab strip doesn't resize while you're hovering because it doesn't want to put an unexpected control under your cursor): [Animate TabView tab resizing microsoft-ui-xaml#2588](https://github.com/microsoft/microsoft-ui-xaml/issues/2588)
> 

/dup microsoft/microsoft-ui-xaml#1511
/dup microsoft/microsoft-ui-xaml#1999
/dup microsoft/microsoft-ui-xaml#2588
