### ISSUE TITLE
About Dialog Shows Weird Transparent Square in top-left

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10634]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Open About Dialog

### Actual Behavior

![image](https://user-images.githubusercontent.com/4098042/125312700-1fe90b80-e2fa-11eb-9053-f2ef69d44aed.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion.

/dup #2380
