### ISSUE TITLE
RGB Dropdown In Color Selector Sometimes Makes Color Picker Disappear

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10636]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

1.) Go to Color Schemes in Settings
2.) Click one of the colors so the Color Picker shows up
3.) Click the "RGB" dropdown
4.) Click off of the dropdown, but on the gray of the Color Picker so that it still remains open
5.) Click the "RGB" dropdown again - The whole Color Picker disappears

### Expected Behavior

The Color Picker shouldn't disappear. Instead, the dropdown should show up again.

### Actual Behavior

> 5.) Click the "RGB" dropdown again - The whole Color Picker disappears

https://user-images.githubusercontent.com/4098042/125319071-11055780-e300-11eb-8d63-105f248e8c1c.mp4

**Comment by j4james** [comment]
I suspect this is the same problem as issue #7092 - just in a different dialog.

**Comment by krixano** [comment]
Yeah, it is. I'll close this then. Thanks.
