### ISSUE TITLE
Odd behavior of setting menu's selected blue bar animation

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10630]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Click anything from the left menu on the settings page, and as the blue bar is animating to what you selected, click on something else. Notice that instead of stopping the current animation and interpolating from the current position to the new position, it just jumps directly to the new position without any animation.

### Expected Behavior

It should be stopping the current animation, and interpolating from the *current* position that it stopped at to the new position to give a smooth animation.

### Actual Behavior

> Notice that instead of stopping the current animation and interpolating from the current position to the new position, it just jumps directly to the new position without any animation.

https://user-images.githubusercontent.com/4098042/125303063-23789480-e2f2-11eb-8f6e-fef2f52a1d25.mp4

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue - please refer to #9556 for more discussion.

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/4613

**Comment by krixano** [comment]
@zadjii-msft I've found a separate problem with that blue bar animation when deleting a profile. I don't know if this needs to be in a new issue or not, but here it is:

When you click to delete a profile, the blue bar jumps far above where it's supposed to be, and then starts animating downward. This is potentially because when it calculated where it should begin, it still thought the menu item for the profile that was deleted was still there, idk.


https://user-images.githubusercontent.com/4098042/125304594-57a08500-e2f3-11eb-88dc-0e724fef717c.mp4

**Comment by zadjii-msft** [comment]
Okay, that does look like a separate issue. Mind copy-pasting that into a [new issue](https://github.com/microsoft/terminal/issues/new) so we can track that separately? Thanks!
