### ISSUE TITLE
Settings Page Width Doesn't Animate Smoothly with Sidebar Collapsing and Expanding

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10633]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Ok, so the problem here is that when you click the hamburger menu to collapse or expand the side bar, four things happen:
1.) The sidebar's width smoothly animates.
2.) The *x position* of the page smoothly animates along with the sidebar width
3.) Right at the start of the animation, the width *of the page* instantly jumps to the size it will be at the end of the animation. This means everything that is right aligned or spans the width of the page also jumps.
4.) Because the x position is animating smoothly, the right aligned stuff jumps oddly. This is due to the fact that the width instantly shrinks (or expands) to the size it will be at the end of the animation *before* the end of the animation, *while* the x position is still moving toward where it needs to be.

### Expected Behavior

Animate the width of the page at the same time as the sidebar by interpolating between the initial width and the new width.

### Actual Behavior

The right aligned visual items (and items that span the entire width) appear to jump oddly.

https://user-images.githubusercontent.com/4098042/125309455-6721cd00-e2f7-11eb-98f8-7876a811b917.mp4

**Comment by krixano** [comment]
So, here's something that I found interesting... the correct behavior shows up when you make the window small enough that the sidebar collapses by itself, and the width appears to do the correct animation so that there's no jump in right-aligned items.
(However, expanding the window so the sidebar expands does have the same issue as previously described)


https://user-images.githubusercontent.com/4098042/125313402-d220d300-e2fa-11eb-906b-b0fb03fcc0d2.mp4

**Comment by krixano** [comment]
As an unrelated issue, this also does show that the resizing of the context is laggy compared to the window border, which produces that gray border on the right and bottom during resizes that you can see in the video.

**Comment by krixano** [comment]
Turns out some other apps on Windows 10/11 that uses the sidebar collapse/expand animation has this problem, including Feedback Hub, the Get Help app, the "Weather" app, and Windows Security.

The new Windows 11 Xbox app doesn't have this problem, aside from the fact that the animation is extremely choppy that it appears to not even really animate much (certainly not even close to smoothly), lmao.

I guess I should make this an issue on the ui repo.

**Comment by zadjii-msft** [comment]
> Turns out some other apps on Windows 10/11 that uses the sidebar collapse/expand animation has this problem, including Feedback Hub, the "Weather" app, and Windows Security.
> ...
> I guess I should make this an issue on the ui repo.

Yea, this is better off at https://github.com/microsoft/microsoft-ui-xaml/ then. Thanks for the investigation!
