### ISSUE TITLE
Clicking out of Color Scheme Dropdown is too Picky

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10637]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Go to Settings, Color Schemes. Click on Color Scheme Dropdown, then try clicking anywhere else to close the dropdown. It is very picky about where you try to click to click off of the dropdown.

### Actual Behavior

Clicking off of the dropdown seems to only work when clicking on the sidebar, or just above the buttons next to the dropdown, or the tabs. It doesn't work anywhere else.

https://user-images.githubusercontent.com/4098042/125321359-37c48d80-e302-11eb-85b7-b037c702c2be.mp4

**Comment by krixano** [comment]
@zadjii-msft Looks like the msftbot didn't add the Needs-Triage label to this one.

**Comment by zadjii-msft** [comment]
Yea, this is unfortunately due to a bug in WinUI itself. We're tracking this on our side in #8769, and the upstream bug is microsoft/microsoft-ui-xaml#3961.

> Appearance -> Open 'Color scheme' dropdown -> Cannot dismiss the dropdown by clicking somewhere else
> * Moved to Light-dismiss doesn't work on ComboBox in XAML Islands [microsoft/microsoft-ui-xaml#3961](https://github.com/microsoft/microsoft-ui-xaml/issues/3961)



/dup #8769 #8938
/dup https://github.com/microsoft/microsoft-ui-xaml/issues/3961
