### ISSUE TITLE
"Open in Windows Terminal" only appears after PC restart

### ISSUE THREAD

**Issue by mssutomo** [microsoft/terminal#10644]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

Microsoft Windows [Version 10.0.19042.1083]
Microsoft Store [Version 12104.1001.1.0]

### Steps to reproduce

1. Install **Windows Terminal** from **Microsoft Store**.
2. Right-click on the **Desktop** or **File Explorer**  to show **Context Menu**.
3. Observe that **Open in Windows Terminal** is not in the **Context Menu** list.
4. **Restart PC**.
5. Right-click on the **Desktop** or **File Explorer**  to show **Context Menu**.
6. Observe that **Open in Windows Terminal** is now in the **Context Menu** list.
7. [Further testing] Uninstall **Windows Terminal**.
8. [Further testing] Repeat steps 1 to 6.
9. [Further testing] Observe similar results.

### Expected Behavior

1. Install **Windows Terminal** from **Microsoft Store**.
2. Right-click on the **Desktop** or **File Explorer**  to show **Context Menu**.
3. **Open in Windows Terminal** appears in the **Context Menu** list.

### Actual Behavior

Similar/refer to:

> **Steps to reproduce**

**Comment by zadjii-msft** [comment]
Yep, that's unfortunately just how shell extensions work. I believe that `explorer.exe` has a cache of the registered extensions for the right-click menu, and it only rebuilds that cache when it's restarted.
