### ISSUE TITLE
Ctrl+A does not select text in WT (in cmd)

### ISSUE THREAD

**Issue by asklar** [microsoft/terminal#10645]
### Windows Terminal version (or Windows build number)

10.0.22141.0, 1.9.1523.0

### Steps to reproduce

If you run cmd (using conhost), you can type and then press Ctrl+A to select the whole line
If you run cmd inside Windows Terminal, you get a ^A control code

### Expected Behavior

ctrl+A should select the whole line of input

### Actual Behavior

Ctrl+A issues a control code `^A`

**Comment by asklar** [comment]
actually, none of the keyboard selection/navigation shortcuts seem to work: ctrl+shift+left/right arrow don't work either 😔

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #715 for more discussion.

/dup #715

also see #4993

**Comment by dxgldotorg** [comment]
Due to leaks about Windows build numbers would it be prudent for OP not to disclose exact build numbers if they are not available to Windows Insiders?

**Comment by zadjii-msft** [comment]
Lol I'm not too worried about that - we (normally) work down the hall from @asklar. This isn't something that's particularly impacted by OS version either. He could have put 12.0.0.0 there and it would have been the same thing 😝

**Comment by asklar** [comment]
I'm on build 0xffff 🙃
