### ISSUE TITLE
Split Panes causing Rendering Issues in Powershell 7

### ISSUE THREAD

**Issue by DarylGraves** [microsoft/terminal#10649]
### Windows Terminal version (or Windows build number)

Terminal: 1.8.1521.0, Windows: 10.0.18363.0

### Other Software

Powershell 7.2.0-preview.7

### Steps to reproduce

Opening/closing Split Panes 

### Expected Behavior

I would expect my typing to appear on the same line as the prompt and not overwrite existing rows.

### Actual Behavior

The output sometimes goes to the wrong line and overwrites text.

![image](https://user-images.githubusercontent.com/46203429/125483875-225b1756-b666-4d0a-8916-43274be60da5.png)

Note in the above example how what I typed is appearing on a different row to my current working directory.

**Comment by zadjii-msft** [comment]
Do you have more specific repro steps? Like is the viewport full of text before the resize, or only partially full? Are you increasing the height of the pane where the artifact appears, or decreasing it? 

I'm thinking of #7253, and more specifically #2432

**Comment by DarylGraves** [comment]
I'm sorry I didn't really have more specific steps when I raised this, it just seemed to happen when I was in the middle of something. I can replicate by following #2432 so please feel free to merge with that.

**Comment by zadjii-msft** [comment]
okay great, thanks for following up!

/dup #2432
