### ISSUE TITLE
When launching the new terminal from address bar, it does not open in the current directory

### ISSUE THREAD

**Issue by umerf52** [microsoft/terminal#1065]
Microsoft Windows [Version 10.0.18362.116]
Windows Terminal version (if applicable): Don't know how to get this

# Steps to reproduce
Type `wtd.exe` in the address bar of Windows Explorer

# Expected behavior
New terminal should open in the current directory

# Actual behavior
New terminal opens in `C:\Users\username`

The issue was discussed earlier in #620 but that solution is not working anymore.

**Comment by zadjii-msft** [comment]
This is a dupe of #878
