### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Zz-886** [microsoft/terminal#10656]
Hello, I am from China and I am using Linux to create a game server.
I hope to provide us with the function of customizing English to replace Chinese, which will help us view server messages more intuitively.
![image](https://user-images.githubusercontent.com/55978588/125599862-cbc7a5b2-3867-4911-9cee-54b07be41425.png)

**Comment by KalleOlaviNiemitalo** [comment]
I don't see why this kind of replacement should be part of the Terminal, or even a plug-in. Instead, the game server software could be localised to Chinese, or you could pipe the output to a `sed` command that replaces the strings.

**Comment by skyline75489** [comment]
Yea I agree with @KalleOlaviNiemitalo . I see no point in implementing something like this in a terminal application.

**Comment by zadjii-msft** [comment]
Yea, this isn't something the Terminal itself should handle. You should reach out to whoever maintains that server software.
