### ISSUE TITLE
Funky scroll bars in 1.10's settings UI

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10664]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations 10.0.19042.1110 (2009, 20H2) WindowsTerminal: 1.10.1933.0

### Steps to reproduce

Start Windows Terminal 1.10.1933.0 ... open the settings UI ... go to "Defaults" or any profile ... observe the scroll bar

### Expected Behavior

Not what's pictured below

### Actual Behavior

![image](https://user-images.githubusercontent.com/61856645/125675604-a62614b3-cd51-4138-8680-4b3cafddf7ff.png)

**Comment by DHowett** [comment]
This seems familiar. @mimvdm Suspect that this might be related to the ScrollViewer? :smile:

**Comment by zadjii-msft** [comment]
(looks like Dustin typo'd - @mimvdb as an fyi)

This is easier to repro when you disable the auto-hiding scrollbars systemwide. You can still repro it without it though, if you navigate to the appearances page, then hover just to the left of the scrollbar and scroll the page. The other "hidden" scrollbar will reveal itself. 

The easy fix would be to revert #10619, but maybe there's another easier way to fix that part of #10609.

**Comment by DHowett** [comment]
Whoops. Thanks.
