### ISSUE TITLE
The ability to toggle the split direction of a pane

### ISSUE THREAD

**Issue by Rosefield** [microsoft/terminal#10665]
# Description of the new feature/enhancement
Once a pane was split, it would be nice to change the orientation of that split. Having a hotkey to toggle the split orientation of the currently active pane would allow changing how the terminal looks without needing to close and recreate a terminal.
E.G.
Create two panes

![image](https://user-images.githubusercontent.com/6185249/125710656-995258d2-a8fc-4495-ab45-ac3dc29594ca.png)

and then swap them to look like 

![image](https://user-images.githubusercontent.com/6185249/125710709-3105a776-5be6-482c-a3a0-acdbdd950245.png)

and vice versa.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Oh huh, I suppose we don't have a issue for this one in #1000 yet. This doesn't seem too hard, wire up a keybinding, and just toggle the orientation of the split on the parent of the active pane. Easy enough!

**Comment by NishantChandla** [comment]
@zadjii-msft I  would like to take up this issue. What hotkey should be set to toggle split direction?

**Comment by jelonmusk** [comment]
Hi
I am a rookie contributor. This might sound silly but should the feature be developed in a specific language only or any programming language can be used?

**Comment by zadjii-msft** [comment]
@NishantChandla / @jelonmusk go right ahead! 

I don't think we really want to have this bound to a key by default right now. If you create an action like `togglePaneOrientation`, once it's all wired up, you should be able to execute the action through the Command Palette without needing to bind a dedicated key for it. 

> This might sound silly but should the feature be developed in a specific language only or any programming language can be used?

The entire Terminal is written in C++, so you'll have to use that.

**Comment by Rosefield** [comment]
@NishantChandla @jelonmusk if you two choose not to do this task I was also planning on doing it, just let me know.

**Comment by NishantChandla** [comment]
@Rosefield As you have created the issue, you can work on this!
