### ISSUE TITLE
[Windows 11 22000.65] : launching cmd or powershell uses wrong terminal theme

### ISSUE THREAD

**Issue by JeromeHXP** [microsoft/terminal#10668]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Steps to reproduce

Set Windows Terminal with Ubuntu with custom theme ad default profile.
Launch Command Prompt or Windows Powershell from windows start menu. 

### Expected Behavior

Command Prompt should use the command prompt theme defined in Windows Terminal. Same for Windows Powershell.

### Actual Behavior

They will use the Ubuntu theme instead of their respective themes defined in Windows Terminal. It looks like they will use the theme defined for the default Windows Terminal profile.

**Comment by zadjii-msft** [comment]
Oh jeez. I guess this issue was technically first, but I've already made #10669 the tracking bug for this issue. 

Thanks anyways!

/dup #10669
