### ISSUE TITLE
Unfocused Appearance editor doesn't appear on +, disappear on Deletion

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10673]
### Windows Terminal version (or Windows build number)

1.11

### Steps to reproduce

Add or remove an unfocused appearance.

### Actual Behavior

On add, the + changes to a [trash] icon, but I cannot scroll to reveal an unfocused appearance. It appears if i navigate away and back.

On delete, the [trash] icon changes to a +, but the UI doesn't disappear.

**Comment by PankajBhojwani** [comment]
Ah yes I didn't update the notifications we send to xaml when I added the til::feature, thanks for catching this!
