### ISSUE TITLE
Quake Mode window size after Win+Arrow keys

### ISSUE THREAD

**Issue by JeremyGNJ** [microsoft/terminal#10671]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Steps to reproduce

While using Quake Mode use Win+Arrow keys to move the Quake Mode window to another screen.    

### Expected Behavior

Some way to move the quake-mode window to anther screen.

### Actual Behavior

The quake mode window uses the snap-to areas like a normal window, but there's no way to get it back to the original position.

**Comment by WSLUser** [comment]
Having you tried using PowerToys FancyZones to see if that meets your needs? This would be a work-around.

**Comment by JeremyGNJ** [comment]
Actually yes, I do use it and it can be a reasonable substitute.  However I posted the issue because it happened to me on-accident....so it could happen to others who dont use powertoys.

**Comment by zadjii-msft** [comment]
Wait so, the behavior I see today with 1.10 is 

* <kbd>win+right</kbd> 1: window snaps to the right half of the monitor the quake window is on
* <kbd>win+right</kbd> 2: window snaps to the left half of the monitor to the right of the current monitor
* <kbd>win+right</kbd> 3: window snaps to the "quake" sizing

if I go back left from there, then I eventually run into #10274 (but I don't think that's really what's being reported here).

Is that not working for you?
