### ISSUE TITLE
Is it possible to disable Bold fonts?

### ISSUE THREAD

**Issue by 5alidz** [microsoft/terminal#10679]
# Description of the new feature/enhancement
I'm currently using the Preview edition of windows terminal and I noticed everything is bold now.
The new bold fonts do not look good on my monitor, it would be awesome if there's a switch to disable bold fonts

**Comment by DHowett** [comment]
Thanks for the request! This is a /duplicate of #10576, which we will make sure gets into 1.10 before 1.10 becomes Stable.

**Comment by DHowett** [comment]
The only bold text you should be seeing is where an application (wsl, powershell, ...) _requested_ bold.

**Comment by 5alidz** [comment]
> The only bold text you should be seeing is where an application (wsl, powershell, ...) _requested_ bold.

Correct, I may be exaggerated a little bit when I said "everything" my bad
