### ISSUE TITLE
Quake mode not rendering full screen on secondary monitors

### ISSUE THREAD

**Issue by denelon** [microsoft/terminal#10677]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Launch quake mode with a secondary monitor in focus. Quake mode doesn't run full width on the monitor. Here is an example from an ultra-wide monitor as secondary to the Surface device.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61799811/125875270-b1017994-799f-4f15-be0d-9ea02a8a14e3.png)

### Expected Behavior

I expected Quake mode to fill the width of the secondary monitor.

### Actual Behavior

Quake mode rendered only the top left portion of the monitor.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10182 for more discussion.

/dup #10182
