### ISSUE TITLE
Windows Terminal does not upgrade

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#10670]
### Windows Terminal version (or Windows build number)

19043.1083

### Steps to reproduce

.

### Expected Behavior

After about 20 hours, only the WT preview version upgraded to current on MS Store while WT is at 1.8.1444.1.

My installation reports WT-1.8.1521.0.

I had installed WT from the store about 2 year (ore more?) ago. Here Windows is at: Windows 10 Pro 21H1-19043.1083.

Usually WT updates a few minutes after your announce...

### Actual Behavior

See above

All the fields to fill are annoying

**Comment by zadjii-msft** [comment]
Yea, sometimes the Store is just slow to roll out updates throughout the CDN. Unfortunately, there's not much we can do about it on our end, you'll just have to be patient ☺️

**Comment by angelog0** [comment]
The strange thing is that the new preview version was soon upgraded on the Store... In any case thanks..

**Comment by DHowett** [comment]
Per the [release notes here](https://github.com/microsoft/terminal/releases/tag/v1.9.1942.0) and kayla's [blog post on the commandline blog](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-10-release/), we're using a ring-based rollout system for 1.9. We need to be more cautious with the stable build, given how many users it could potentially impact if something were to be wrong with it.

**Comment by DHowett** [comment]
Sorry, it looks like the language we used in the blog post was not particularly clear. @cinnamon-msft is that something you can fix?

**Comment by angelog0** [comment]
Sorry, also these answers are not clear to me. Do they mean 1.9 is only for insider users of Windows? not standard, official users??

**Comment by Astrophizz** [comment]
Hmm I'm the Beta channel but don't see the update. Is there anywhere we can look to see which versions are in which channels?

**Comment by DHowett** [comment]
> Sorry, also these answers are not clear to me. Do they mean 1.9 is only for insider users of Windows? not standard, official users??

We're just rolling 1.9 out more slowly. When we released 1.8 to the Stable channel, we got about 30,000 crash reports in the first two days for an issue we probably could have avoided.

1.9 is available in the "Dev" channel this week, and will be moving to the Beta channel and then full release some time next week.

**Comment by angelog0** [comment]
> we got about 30,000 crash reports 

From many bug reports it seems you are developing this app mainly for insider users filling it of many many new features. The risk is that the app becomes buggy and out of control.. I would refrain from adding new features and would concentrate to fix bugs.. adding a feature at the time and adding the next only when the previous is stable.. But this is only my opinion..
