### ISSUE TITLE
X forwarding for SSH connection

### ISSUE THREAD

**Issue by Y-Grigoriy** [microsoft/terminal#10683]
I try to perform X forwarding for SSH connection, using Windows terminal. I want to connect to remote machine with Red Hat operation system. Following the [instructions](https://stackoverflow.com/questions/57363597/how-to-use-a-new-windows-terminal-app-for-ssh) and using `ssh user_name@my-server` I can connect to remote machine.  However, when after connection I use command `export DISPLAY=localhost:0.0` and `xhost +local:user_name`, I get the following message:  `xhost:  unable to open display "localhost:0.0"`. Also I tried to use following advice: https://github.com/microsoft/terminal/issues/2785#issuecomment-761020305, but I got the following error:
```
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
Permission denied, please try again.
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
Permission denied, please try again.
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
user_name@my-server: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

[process exited with code 255]
```
UPDATED:
This problem was solved as follows:
1. It is necessary to modify **config** file (_C:\Users\username\ .ssh_):
```
Host host_name
  HostName my-server 
  User user_name 
  XAuthLocation "C:/Program Files/VcXsrv/xauth.exe"
  ForwardX11 yes
  ForwardX11Trusted yes
```
2. Check or/and add environment variables (_This Computer -> Properties -> Advanced System Settings -> Environment Variables_):
```
DISPLAY=localhost:0.0
HOME=C:\Users\username
TMPDIR=%USERPROFILE%\AppData\Local\Temp
PATH=C:\Program Files\VcXsrv
```
3. Write command in **cmd**:
`xauth generate localhost:0.0 . trusted`
4. Checking the previous command:
`xauth list`
5. In settings of Windows terminal:
`"commandline": "ssh host_name",`

But now I have problem with the key combination _**ctrl+С**_. It terminates ssh-connection. Could someone help me with it?

**Comment by WSLUser** [comment]
You can disable the keybinding ctrl+c if you want but by default, Linux kills programs with that keybinding and Windows by default uses it for copying. Are you using Win32-OpenSSH or some other binary like from Cygwin or WSL?

**Comment by Y-Grigoriy** [comment]
Sorry, may be you not clearly understand me. Initially, I checked ssh-connection to remote station with **red hat** and I don't have problem with **ctrl + C**. After configuration of X-forwarding (as it is written after UPDATED in my first comment) I got problem with **ctrl + C**. And of cause I need to use this combination at least for killing program at Linux. Thus the question could change after configuration of X-forwarding?
Also I don't understand your question, but I am sure that I do not use Cygwin. But I have installed WSL on my computer.

**Comment by zadjii-msft** [comment]
@Y-Grigoriy Which version of `ssh` are you using? Does this repro in the vintage console window (`cmd.exe`), or does it only repro in the Windows Terminal?

**Comment by Y-Grigoriy** [comment]
@zadjii-msft, I used cmd.exe, version: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Comment by zadjii-msft** [comment]
If this repros in just a `cmd.exe` window, without the Terminal involved at all, then I'm betting that this is an OpenSSH issue, not a Terminal one. https://github.com/PowerShell/Win32-OpenSSH/issues/1803 looks fairly related

**Comment by Y-Grigoriy** [comment]
@zadjii-msft, Should I close this issue or can we leave it open until the question on your link to be answered?

**Comment by zadjii-msft** [comment]
Lost this one in the triage queue. Yea, let's call this /dup  https://github.com/PowerShell/Win32-OpenSSH/issues/1803 until proven otherwise.
