### ISSUE TITLE
Quake window doesn't know it was minimized

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10689]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations 10.0.19042.1110 (2009, 20H2) WindowsTerminal: 1.10.1933.0

### Other Software

TCC.EXE

### Steps to reproduce

From TCC.EXE (JPSoft) running in the Quake terminal, issue `activate "%_wintitle" min` (_wintitle would be the console's caption if I were in a console; WindowsTerminal uses it as the tab caption).

### Expected Behavior

I expect the quake window to be minimized and the taskbar icon to disappear.

### Actual Behavior

Either of these give the expected behavior:

- SendMessage, WM_SYSCOMMAND, SC_MINIMIZE
- ShowWindow, SW_MINIMIZE

But in response to TCC's ACTIVATE command, the quake window is minimized but the taskbar icon doesn't disappear.  

I don't know exactly how TCC's ACTIVATE command works but I've attached a log (plain text) from Spy++ showing what the CASCADIA_HOSTING_WINDOW_CLASS class window sees after that command is issued.

[messages.txt](https://github.com/microsoft/terminal/files/6833672/messages.txt)

**Comment by zadjii-msft** [comment]
> the quake window is minimized but the taskbar icon doesn't disappear.

This is by design. The `_quake` window doesn't show up in the taskbar, so it needs to have the tray icon be visible when it's minimized, so that it's still accessible. This was added in #10179, and is going to get some additional flexibility in #10368.

**Comment by vefatica** [comment]
> This is by design. The _quake window doesn't show up in the taskbar, so it needs to have the tray icon be visible when it's minimized, so that it's still accessible.

Yes, I know that's how it should work, but when minimized with TCC's `ACTIVATE` command , the window itself disappears, GetWindowPlacement says it's minimized, but the TASKBAR icon is still there (in addition to the tray icon).

**Comment by DHowett** [comment]
@zadjii-msft we probably need to detect when weird software tries to minimize the quake window and trigger a disappear instead of a minimize.
