### ISSUE TITLE
'Open in Windows Terminal' context menu Doesn't open as a new tab in current instance. I am so disappointed that this is not still fixed, its been a decade now.

### ISSUE THREAD

**Issue by BroJenuel** [microsoft/terminal#10686]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. Go to **any directory**, and then right-click to show the `Context Menu` and then click `Open in Windows Terminal`.
In this image, you can see that I open a windows terminal in folder 1.
![image](https://user-images.githubusercontent.com/31676163/125952845-665c8d5e-1956-4c27-92bb-a88e0d761d12.png)

2. Go to **another directory,** and then right-click to show the `Context Menu` and then click `Open in Windows Terminal`.
In this image, as you can see, If I open a new terminal it opens in a new windows, which is very very sucks,, what is the point of having tabs. I don't know if this is a bug, **_but it should open in the same windows as a new tab_**.
![image](https://user-images.githubusercontent.com/31676163/125953275-4384c9a8-6069-4737-91f8-4cd3b65d2c3a.png)

### Expected Behavior

If opening a new windows terminal window, it should open as a new tab, if there is an existing window.

### Actual Behavior

It's opening in a new window.

**Comment by KalleOlaviNiemitalo** [comment]
How have you configured the "New instance behavior" setting? <https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#new-instance-behavior>

**Comment by vefatica** [comment]
I think @KalleOlaviNiemitalo is talking about this (below. from the settings UI) it works OK here.

![image](https://user-images.githubusercontent.com/61856645/125973989-d1805dbf-b795-4eaf-b45b-0beaca6a072a.png)

**Comment by BroJenuel** [comment]
@vefatica @KalleOlaviNiemitalo Oh, my bad, I haven't seen these settings... But I saw it now.. both of your answers are correct... thanks thanks
