### ISSUE TITLE
Running any cli app as admin opens it in Windows Console Host.

### ISSUE THREAD

**Issue by rounk-ctrl** [microsoft/terminal#10682]
### Windows Terminal version (or Windows build number)

10.0.22000.71, 1.10.1933.0

### Steps to reproduce

Set default terminal application as Windows Terminal.
Open any cli app(cmd, powershell, wsl) as admin.
See that it launches in conhost not windows terminal.

### Expected Behavior

Opens the app in Windows Terminal.

### Actual Behavior

Opens in Windows Console Host.

**Comment by zadjii-msft** [comment]
Unfortunately, this is by design right now. Due to a limitation in the app platform it is impossible for Terminal to be "discovered" as the handler when the application that needs a terminal is running elevated.

/dup #10276
