### ISSUE TITLE
Remove deserialization of legacy json keys

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1069]
I'm thinking primarily of:
* Globals in the root of the json object (which changed with #1005)
* the `table` in a colorscheme as an array, not names
* the entirely missing keybindings key (maybe we want to leave this however, or it could be fixed by #754 )
* The legacy `colorscheme` key (changed to `colorScheme` with #1054 )
* remove `colorTable` (#4091)

**Comment by bitcrazed** [comment]
No longer required.

**Comment by zadjii-msft** [comment]
Hey so I'm re-activating this to make sure we pull the old keybindings that we're not going to support in >=1.0. These were changed in #3391

**Comment by DHowett-MSFT** [comment]
I've begun work on a bunch of facets of this (i guess as indicated by the commits above!)
