### ISSUE TITLE
Profile Folders

### ISSUE THREAD

**Issue by Real-Luke-James** [microsoft/terminal#10692]
# Description
I have a lot of Distros installed with WSL, so I have a lot of terminal profiles for each distro, and some with custom settings for some distros. So, folders can make the profile dropdown less cluttered and easier to navigate.

# Checklist
- [ ] Add the ability to create folders and add profiles inside folders    
- [ ] Add the ability to put folders inside folders
- [ ] Add the ability to remove folders and make profiles that were inside the deleted folder move back into the dropdown
     // If the deleted folder is inside another folder, move profiles inside the deleted folder up one folder
- [ ] Add the ability to rename folders

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
