### ISSUE TITLE
python scripts doesnt accept input

### ISSUE THREAD

**Issue by abdoi94** [microsoft/terminal#10696]
### Windows Terminal version (or Windows build number)

10.0.22000.0

### Other Software

Python 3.9.6 within terminal

### Steps to reproduce

when i do anything gerrit related for the first time on a fresh install, i get a question to allow this device to connect to gerrit host or not, so just answer with yes or no to finish the scipt, this is [the script](https://gist.github.com/abdoi94/b0670565f31f51ca66a867943f82da8c)

### Expected Behavior

terminal allows me to input an answer to procced with the script

### Actual Behavior

terminal just freezes at that input field and wont let me enter anything

![Screenshot 2021-07-17 135731](https://user-images.githubusercontent.com/5349989/126034756-17794f6e-46f3-47d0-9904-29bd4b88769b.png)

**Comment by zadjii-msft** [comment]
Thanks for linking the script! That makes debugging much easier. That looks like your `ssh` client isn't accepting the input, not python. Which `ssh` are you using? `ssh.exe` that ships with Windows? `ssh` from a WSL distro? Or some other `ssh`? And which version of `ssh`?

**Comment by abdoi94** [comment]
Hello there, this happned only when i ran it within windows, i have latest OpenSSH installed from Settings

```
ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

on the other hand Ubuntu running within WSL accepted input when i ran the same script
![Screenshot 2021-07-19 182852](https://user-images.githubusercontent.com/5349989/126185939-0a7c86e5-d333-4676-a84f-05812061a5cb.png)

**Comment by zadjii-msft** [comment]
That's what I thought. This sounds like an issue with `ssh.exe` itself, you should report this over at https://github.com/PowerShell/Win32-OpenSSH/issues

**Comment by abdoi94** [comment]
Thanks @zadjii-msft, i just open an issue in there 

Have a nice day
