### ISSUE TITLE
Starting terminal on boot not configurable.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/terminal#10699]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Windows Settings -> Apps -> Startup -> Scroll down to "Windows Terminal"

The option is greyed out.
![image](https://user-images.githubusercontent.com/31551546/126053019-11405c8c-0961-4d4f-aa41-a0170e36d8be.png)

Task Manager -> Startup -> Windows Terminal -> Enable -> Close and reopen Task Manager -> See that enabling it didn't persist.

https://user-images.githubusercontent.com/31551546/126053068-31a7e10c-2b42-40dc-a19e-a22824c784f7.mp4

### Expected Behavior

I expect to be able to control whether or not windows terminal opens on boot.

### Actual Behavior

Windows Terminal forcibly opens itself on startup, and I (as shown above) cannot change it.

**Comment by sarahkittyy** [comment]
Oh, and yes, the internal "Launch on machine startup" setting is disabled, too.

**Comment by DHowett** [comment]
Thanks for the report! We can't figure out why this would happen; we're not locking the state of the task, and Terminal's code [here](https://github.com/microsoft/terminal/blob/335f69e099179d533ffa3a1376035f1a63637de0/src/cascadia/TerminalApp/AppLogic.cpp#L960-L967) tries to turn it off if your settings say that it should be off.

**Comment by sarahkittyy** [comment]
I actually fixed this a while ago with a full reinstall of windows. I tried all over to fix my issue, to no avail. I finally just gave up and bit the bullet after that. It happened on other apps too, and I couldn't find any regedit key / group policy key that would lock the startup state like that.

You're free to close this, unless someone else is having it too :)

**Comment by zadjii-msft** [comment]
Weird. Something must have been messed up on your system, but I guess it'll be impossible to know for sure what now. We'll keep our ears open for this if anyone else ever reports it.

Thanks for following up!
