### ISSUE TITLE
Spanish localization of "Summon Quake window" is weird (English original not too great)

### ISSUE THREAD

**Issue by OscarL** [microsoft/terminal#10691]
This is on Windows Terminal Preview v1.10.1933.0

The Spanish localization of "Summon Quake window" appears as "Citación de la ventana de Quake".

That reads like a bad machine translation.

"Citación" (Citation) is a noun, and not a verb like "Summon" (that would be "Citar", and it still feels wrong in this context. "Invocar" (Invoke) feels better in my opinion.

As a minimum, I would suggest for the Spanish translation of "Summon Quake window" to be: "Invocar ventana tipo Quake".

But..., I think even the English original is unoptimal, because:

1. It "summon" a "quake-like" window, and not a window for Quake. (even if the implementation is called that, the UI should be clearer).

2. It does not "summons" but alternates said window's visibility.

So... I suggest either "Show/Hide Quake-like window" or "Toggle Quake-Style window visibility" for the English original, and the corresponding suggestions for Spanish would then be: "Mostrar/Ocultar ventana tipo Quake" and "Alternar visibilidad de la ventana estilo Quake".

BTW... shouldn't be there an issue type for localization issues? or is this "free-form" OK?

Thanks for your work, guys, and please excuse the self-taught "English" :-)

**Comment by DHowett** [comment]
>But..., I think even the English original is unoptimal, because:

You're totally right. This is a somewhat poor phrasing.

> Thanks for your work, guys, and please excuse the self-taught "English" :-)

No way--Thank *you*! This is an excellent insight.

**Comment by cinnamon-msft** [comment]
I like "Invoke Quake Window"! I think that's more clear. :)

**Comment by lhecker** [comment]
@cinnamon-msft And what about "_Open_ quake window"?

**Comment by OscarL** [comment]
> @cinnamon-msft And what about "_Open_ quake window"?

See point 2 in the original text.

The action that shortcut/action performs is toggling the "quake-style window", neither "summon", "open", or "invoke", are 100% correct, IMO.

I still think that something along the lines of "Toggle Quake-Style window visibility" is more accurate, and allow for a better translation, (my original point).

Just my last 2 cents on the matter :-)

Thanks for your work, guys.

**Comment by lhecker** [comment]
@OscarL If you don't mind I hope they're not your last 2 cents on the matter. 😅 Our team only speaks a very limited amount of languages so any input from non-English speakers is extremely valuable actually!

The reason I'm not in favor is because "Toggle Quake-Style window visibility" is rather wordy and I feel like people are going to be confused about what a "Quake-style window" is no matter what. However I am concerned about the quality of translations that can be created from the English original string. So if we have to make it longer in order to provide an improved internationalization I'm all for it.

As such: Is there a middle-ground between "Invoke Quake Window" (which is succinct and easy to remember) and "Toggle Quake-Style window visibility" (which is arguably easier to translate)?

**Comment by cinnamon-msft** [comment]
What about "Display Quake Window" or "Reveal Quake Window"? These are similar to "open" though 🤔

**Comment by OscarL** [comment]
@lhecker, Oh! I don't mind given away more cents! :-D (I was just trying to not become too annoying reiterating myself as a simple user!)

I understand your point in trying to keep that string short (that was what I was thinking yesterday while double checking the English spelling on the "Actions" settings).

In Spanish, the longest string there is the following: "Abrir el archivo de configuración predeterminada". Quite a mouthful for what I guess is "Open default config file" in English. That's the way Spanish works, it IS verbose most of the time :-).

Regarding your point on a middle ground option.... what about:

    "Toggle Quake-style window" (Spanish: "Alternar visibilidad de la ventana tipo Quake")

or

    "Toggle Quake window visibility" ? (Spanish: "Alternar visibilidad de la ventana Quake")

or even just

    "Toggle Quake window" ? (Spanish: "Alternar visibilidad de la ventana Quake")

I can't stress enough the issue about the action being a visibility TOGGLE, not just Open/Invoke/Display/Show. It also HIDES the window if one is actually visible!

Note: you see that I translated "Toggle" as "Alternar visibilidad" instead of just "Alternar". That's because... toogle... toggle what? I've seen it used in English software many times, thus my suggestion, but in Spanish is not clear enough.

An alternative to "toggle visibility" would be "Show/Hide", as in:

    "Show/Hid Quake window" (Spanish: "Mostrar/Ocultar ventana Quake"

or

    "Show/Hid Quake-style window" (Spanish: "Mostrar/Ocultar ventana estilo Quake") 

("estilo" and "tipo" imply the same in this context)

I don't like calling that window just "Quake window" because... you know... I'm not about to get a shotgun and start blasting deamons after I hit that key combo... BUT...

I guess I could live with it. A correct Spanish translation would barely be any different in any case.

(at least it wont be "Citación de la ventana Quake", that is just laughable :-D)

**Comment by zadjii-msft** [comment]
We voted, "Show/Hide Quake window" (Spanish: "Mostrar/Ocultar ventana Quake" won. Thanks for the feedback!
