### ISSUE TITLE
WT and WTP won't start.

### ISSUE THREAD

**Issue by rudironsonijr** [microsoft/terminal#10698]
### Windows Terminal version (or Windows build number)

 10.0.19043.0

### Other Software

Windows Terminal (1.9.1942.0)
Windows Terminal Preview (1.10.1933.0)
Docker Desktop 3.5.2 (66501)

### Steps to reproduce

Whenever I try to run both versions of WT, I see a gray screen and the application suddenly closes.

![2021-07-17 15_39_23-Window](https://user-images.githubusercontent.com/6081613/126046628-e9315c4a-249e-45a5-b8e4-ec7d9eee8c6c.png)

### Expected Behavior

Is expected that the WT open.

### Actual Behavior

Both applications suddenly crashes after the gray screen appears.
Event log:

Faulting application name: WindowsTerminal.exe, version: 1.9.2107.13002, time stamp: 0x60edf3e3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process id: 0x245c
Faulting application start time: 0x01d77b37ab14e3d4
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 129e3b15-6699-4c43-bf9a-6bb37766e03b
Faulting package full name: Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by rudironsonijr** [comment]
Just formatted my entire machine and reinstalled W10 and the behavior still the same.

**Comment by zadjii-msft** [comment]
Looks like from https://github.com/microsoft/terminal/issues/4540#issuecomment-882122566 you got this figured out. 

/dup #4540
