### ISSUE TITLE
Add a switch to start _quake mode with focus mode off.

### ISSUE THREAD

**Issue by abitofmaya** [microsoft/terminal#10695]
In the current implementation, the quake mode will ignore the launchMode setting and always launch in focus mode. This is fine for most users. But for the users who also want the tabs to be visible, the only way I think we can do that is to toggle focus mode from the command palette. I think starting the quake mode with an explicit switch should launch it in non focus mode. It should also respect the launchMode setting if this is defined in the configuration for the global summon action.

Maybe like this:
```
wt -w _quake --nonfocus
```
or 
```
{
"keys": "win+`",
"launchMode": "default",
"command": {
"action": "globalSummon",
"name": "_quake",
"dropdownDuration": 200,
"toggleVisibility": true,
"monitor": "toMouse",
"desktop": "toCurrent"
}
}
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9992 for more discussion.

/dup #9992
