### ISSUE TITLE
URL detection: False positive for links where port number contains non-numeric characters

### ISSUE THREAD

**Issue by Sominemo** [microsoft/terminal#10701]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. Make a terminal display a described link, for example `https://example.com:test`
2. Hover on link

### Expected Behavior

Only the `https://example.com` part is being underlined, since it's correct

### Actual Behavior

The whole `https://example.com:test` is being underlined, despite it being a non-valid URL.
![image](https://user-images.githubusercontent.com/19842935/126072922-fd36fe97-0b89-4e4d-b99b-9802c48226ce.png)

**Comment by orcmid** [comment]
> ### Steps to reproduce
> 1. Make a terminal display a described link, for example `https://example.com:test`
> 2. Hover on link
> 
> ### Expected Behavior
> Only the `https://example.com` part is being underlined, since it's correct
> 
> ### Actual Behavior
> The whole `https://example.com:test` is being underlined, despite it being a non-valid URL.
> ![image](https://user-images.githubusercontent.com/19842935/126072922-fd36fe97-0b89-4e4d-b99b-9802c48226ce.png)

I doubted that Terminal is the source of this until I reproduced it and I could not get it with cmd.exe outside of Terminal.  In any any case, the "press ctrl-click" to follow the URL does provoke a response that it is not valid.

With regard to the underlining of a URL detection, there are conventions for unambiguosly delimiting URLs in texts or URLs and IRLs in the IETF specifications.  This is demonstrated with `<https://example.com>:test`  although `( ... )` is probably sufficient, just as in Markdown, and one will also have to provide escaping of any spaces and maybe other characters in the URL as well.

I don't think we should expect Terminal to do much about detecting something that might be intended to be followable or not.    You can tell from the hover-underline whether it got all of it, too little, or too much.   (I can't imagine how this works with respect to accessibility either.)

**Comment by zadjii-msft** [comment]
The regex we're currently using is here:
https://github.com/microsoft/terminal/blob/f68324cd099f2d76321f1889f8de504e67a7c797/src/cascadia/TerminalCore/Terminal.hpp#L23

We've got more discussion over in #8321, so I'm gonna redirect this thread there

/dup #8321
