### ISSUE TITLE
WSL starting directory not Linux home for fresh WSL instance

### ISSUE THREAD

**Issue by ednl** [microsoft/terminal#10704]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

* Windows 10 Pro (21H1, 19043.1147)
* Ubuntu-20.04 (Linux amd 5.4.72-microsoft-standard-WSL2 # 1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

### Steps to reproduce

Ubuntu-20.04 is the default distro. Windows Terminal is set to start up at boot. Settings:

* Command Line = wsl.exe -d Ubuntu-20.04
* Starting Directory = //wsl$/Ubuntu-20.04/home/username

### Expected Behavior

Ubuntu WSL starts up in the Linux home directory ~ (= /home/username)

### Actual Behavior

For fresh WSL instances, Ubuntu WSL starts up in the Windows home directory: /mnt/c/Users/username

This is true for every WSL instance in Windows Terminal at boot, and every other time it has to start a fresh WSL instance (after closing it and waiting a while until the WSL instance is killed). When the WSL instance is already running, it does work as expected. I do not see a way to *always* start up WSL in the Linux home directory. This is especially important since WSL2 and its greater performance difference between Linux and Windows file systems.

There have been numerous issues regarding the Starting Directory that have now all been closed. I cannot find a reference to this specific issue, though: that it would be a bug or unexpected result to not have the //wsl$ path available for fresh WSL instances. I think it is. It is definitely unexpected to me. There is one comment describing the behaviour: https://github.com/microsoft/terminal/issues/592#issuecomment-629223710

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #7197 for more discussion.

/dup #7197
