### ISSUE TITLE
Wrong font for bold text in WSL

### ISSUE THREAD

**Issue by brneor** [microsoft/terminal#10709]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

WSL2

### Steps to reproduce

Get any output that should be displayed in bold.

### Expected Behavior

Bold text is displayed in same font which normal text is displayed.

![image](https://user-images.githubusercontent.com/5962898/126200483-93cbb648-eaaa-439f-b250-f4fe1abf202d.png)

### Actual Behavior

Bold text is displayed in different font.

![image](https://user-images.githubusercontent.com/5962898/126200519-af5aa4d9-7351-4b54-979f-397b5b7efa3c.png)

**Comment by zadjii-msft** [comment]
Looks to me like that's the same font, just being displayed as **bold**, as requested. This was added in #109, #10498, and there's a setting to disable it in progress in #10648.

**Comment by brneor** [comment]
> 
> 
> Looks to me like that's the same font, just being displayed as **bold**, as requested. This was added in #109, #10498, and there's a setting to disable it in progress in #10648.

I have attached screenshots showing the difference from actual Fira Code Bold and the bold displayed when in WSL. I'm sorry if it was't clear enough:

Windows Terminal Preview Version 1.10.1933.0, Powershell:
![image](https://user-images.githubusercontent.com/5962898/126200483-93cbb648-eaaa-439f-b250-f4fe1abf202d.png)

Windows Terminal Preview Version 1.10.1933.0, WSL2 (Fedora, Ubuntu):
![image](https://user-images.githubusercontent.com/5962898/126200519-af5aa4d9-7351-4b54-979f-397b5b7efa3c.png)

**Comment by zadjii-msft** [comment]
Wait but the point I'm trying to make is that those two screenshots are showing the same font - just with different font weights. For example, here's the same output, but with Ubuntu Mono:

```
printf "\e[97mthis text is bright \e[mthis text isn't\n\e[1mthis text is bold   \e[mthis text isn't\n\n"
```

![image](https://user-images.githubusercontent.com/18356694/126228455-e5dcf03b-a02c-47c3-ae69-b502804890e9.png)

maybe with a better scheme:
![image](https://user-images.githubusercontent.com/18356694/126228593-3db0ff5b-60d0-4e11-a9a2-483c2ea91536.png)


The first line, the text is rendered like it was in 1.9 - without the bolding in response to `1m`. The second line is the 1.10 variant. It's the same font for both, just, **bold**.

Which _specific_ font are you using, and how are you emitting those lines of text?

**Comment by brneor** [comment]
I'm using the font "Fira Code" and the bold text in my screenshot was generated using `tput`. I tried running your snippet and result text for 'bold' is still the same:

![image](https://user-images.githubusercontent.com/5962898/126230151-6d794810-5d9a-43fa-810a-2c94add6f0d7.png)

I can assure you, although I can provide visual proof right now, that I'm getting correct bold variants for Fira Code in Gnome Terminal running natively on Fedora.

**Comment by Luvjeet** [comment]
> 

what font variant did you used?
