### ISSUE TITLE
incorprate git bash to tertminal 

### ISSUE THREAD

**Issue by badushaebrahim** [microsoft/terminal#10700]
so what am proposing that in current version only git cmd is  working properly and i would like to better working of seamless look of git bash 
### **currently**
![image](https://user-images.githubusercontent.com/63869474/126064456-6a6ae07a-f226-45c6-816f-5a6a150a5a95.png)
**and while doing so**
![image](https://user-images.githubusercontent.com/63869474/126064480-5191cb58-7f3c-4b44-8ee4-c7c612b5c9fe.png)
**and would like it to be like:**
![image](https://user-images.githubusercontent.com/63869474/126064498-0bea5ef9-4384-4036-bd5a-4f0ceced1890.png)
**like so** 

hope to make this a reality
and sorry for any mistakes in advance

**Comment by acrispin** [comment]
In command line put this:
**_C:/Program Files/Git/bin/bash.exe -login -i_**
![image](https://user-images.githubusercontent.com/9753795/126065481-addaa0e5-09f6-479b-b470-9674e25c61d4.png)
![image](https://user-images.githubusercontent.com/9753795/126065552-ed353c84-f28c-4a7c-9cf5-2b1d2131f921.png)

**Comment by KaranKad** [comment]
You can set up git bash in windows terminal as mentioned in above. Also, git's installer also provides you with an option to add this into windows terminal for you.
![image](https://user-images.githubusercontent.com/71691514/126069110-8f929e4c-8893-4a8a-a10d-60ee47dfe26b.png)

**Comment by zadjii-msft** [comment]
Yep, as @KaranKad mentioned, git can already do this for you.
