### ISSUE TITLE
Add syntax highlighting for Python interpreter

### ISSUE THREAD

**Issue by Cyfine** [microsoft/terminal#10706]
# Description: 
I am recently using python, and sometimes I would like to use the terminal to run some python scripts. It would be handy and user-friendly if the Windows Terminal could support python syntax highlighting in the terminal interpreter mode.

**Comment by skyline75489** [comment]
Maybe https://ipython.org/ is what you want?

**Comment by zadjii-msft** [comment]
Yea, this isn't something that the Terminal can do automatically - this is something that python would specifically have to do itself. This is something that's better requested on their feature tracker (wherever that may be).
