### ISSUE TITLE
Bug Report: Menu detaches when window moved

### ISSUE THREAD

**Issue by Kryptryx** [microsoft/terminal#1070]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version (if applicable): Latest commit c3e32eb  2 hours ago

Any other software? VS2019 x64 Release
```

# Steps to reproduce
1. Activate the drop down.
2. Move the terminal window.

# Expected behavior
The dropdown should track the moving window.

# Actual behavior
Sometimes the drop down does not move.
Sometimes the drop down moves to the new position in a jerky manner after some lag.
![Annotation 2019-05-30 150807](https://user-images.githubusercontent.com/10785370/58654309-f9b8ab00-82ed-11e9-88b2-9ff451672517.png)

**Comment by zadjii-msft** [comment]
This is a dupe of #769

**Comment by Kryptryx** [comment]
Ha. I searched first and didn't spot the duplicate.
