### ISSUE TITLE
Feature Request: Save panes layout as a profile which can be opened via the open tab menu

### ISSUE THREAD

**Issue by BenjaminNolan** [microsoft/terminal#10717]
# Description of the new feature/enhancement

Currently, it's possible to open a layout by creating a shortcut which opens the Terminal with a bunch of CLI options, which is great, however it'd be much nicer and more user-friendly to be able to create a layout directly in the interface by splitting panes and setting their heights and widths with the various keyboard shortcuts, and then clicking a Save as Profile option in the Open Tab drop-down menu which will add it to that drop-down as a future option when opening a new tab.

# Proposed technical implementation details (optional)

On the `settings.json` front, you could do something like this?
```json
{
  "profiles": {
    "list": [
      {
        "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}", // The profile I want to use for the actual panes themselves
        "hidden": false,
        "name": "Ubuntu-20.04",
        "source": "Windows.Terminal.Wsl"
      },
      {
        "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}", // The new profile added by saving the custom layout
        "hidden": false,
        "name": "My Custom Layout",
        "source": "Windows.Terminal.Layout"
      }
    ]
  },
  "layouts": {
    "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}": { // Same GUID as the profile, perhaps?
      "panes": [
        {
          "width": 50, // A vertical split pane with three children. I've assumed percentages here rather than columns and rows so everything resizes correctly.
          "children": [
            {
              "height": 50,
              "profile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}" // The id of the profile to open in this pane. In this example, they're all the same, but there's no reason why they couldn't be different.
            },
            {
              "height": 25,
              "profile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}"
            },
            {
              "height": 25,
              "profile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}"
            }
          ]
        },
        {
          "width": 50, // A vertical split pane with two children
          "children": [
            {
              "height": 75,
              "profile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}"
            },
            {
              "height": 25,
              "profile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}"
            }
          ]
        }
      ]
    }
  }
}
```

That would create this, for example:
![Example Windows Terminal multi-pane layout](https://i.imgur.com/JlDnXOD.png)

Apologies if this is a duplicate, I did look through before creating it!

**Comment by zadjii-msft** [comment]
So for reference, I like to do like the following each time I boot up the Terminal in the morning:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571.

More specifically though, I think this is roughly /dup #756

**Comment by BenjaminNolan** [comment]
@zadjii-msft Not sure this is a _true_ duplicate of #756, as it was intended more to be about the ability to create a layout using the split pane commands in an existing tab and then save them as a profile that can be opened later via the commands in the tab dropdown that are mentioned in #1571 (prime number, nice ^^), so that's on me for not really explaining the thought properly, but there is definitely a lot of cross-over between them.

Do you think it's worth mentioning the ability to save the current pane layout in a comment on #1571?

**Comment by rajhlinux** [comment]
How are you actually able to do this? I also would like to have a preset settings which will open multiple tabs in certain order where multiple terminals are stacked vertically and horizontally.
