### ISSUE TITLE
Force Quake mode window to a certain monitor (Multi-Monitor setup)

### ISSUE THREAD

**Issue by hensz** [microsoft/terminal#10719]
Hi there!

Currently on my setup (I'm using two screens with the same screen resolution) when I hide the Quake mode window and summon it again, it's displayed on the screen of the currently active window. For my workflow it would be better if the window would appear at the same position where I hid it before.

Is this already possible, if yes, with which setting? If not, then it would be great to have such a feature/setting.

Thanks!
Torsten

**Comment by zadjii-msft** [comment]
So the "quake mode" window is just a special type of window, with a specialization of the `globalSummon` action. It's not all that configurable by itself. The `quakeMode` action will always summon the window named `_quake`, and will always open on the monitor where the mouse is. 

What you _can_ do, though, is rebind <kbd>win+\`</kbd> to a different `globalSummon` action. The following will be equivalent to the `quakeMode` action, but without the requirement that the window's name is `_quake`:

```json
{ "keys": "win+`", "command": { "action": "globalSummon", "dropdownDuration": 200, "toggleVisibility": true, "monitor": "any", "desktop": "toCurrent" } }
```

Granted, that won't have the same "snap to the top" behavior, nor will it do the "minimize to tray" thing that `_quake` does in 1.10, but we're tracking improvements to allow other windows to do those things in #8888 and #9992.
