### ISSUE TITLE
file with special characters breaks terminal output

### ISSUE THREAD

**Issue by pgilsonmsft** [microsoft/terminal#10710]
I have a file on disk named â€œGroupMembers.csvâ€  (where the last 3 chars are e2 80 9d in hex), when I list the directory contents with dir this stops terminal output and waits for input. Happens with powershell, command prompt. Ubuntu ls behaves slightly differently, lists the file as â€œGroupMembers.csvâ€\302\235, but completes successfully.

 A regular cmd.exe dir works fine in this directory.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #10310 for more discussion.

/dup #10310
