### ISSUE TITLE
Failed to load settings on startup on windows 10 build 10.0.19043.1110

### ISSUE THREAD

**Issue by Vistaking** [microsoft/terminal#10712]
### Windows Terminal version (or Windows build number)

10.0.19043.1110

### Steps to reproduce

Launching Windows Terminal after the update of Windows 10 to build 19043.1110 I get the error failed to load settings . I didn't touch the settings.json file . I've also downloaded Windows Terminal Preview Version: 1.10.1933.0 same error 
[settings.json.txt](https://github.com/microsoft/terminal/files/6844021/settings.json.txt)
![image](https://user-images.githubusercontent.com/26915656/126229986-27b96232-26ca-4af4-8757-fbadd4d416cc.png)

### Actual Behavior

If I click on Ok it just shows the default settings not the settings that should be from settings.json file.

**Comment by DHowett** [comment]
Thanks for the report!

You'll want to delete the `}` on line 7.

![image](https://user-images.githubusercontent.com/189190/126701616-aa868ccb-3938-4924-8de4-460cfd8b7e79.png)

**Comment by DHowett** [comment]
And add the comma at the end of line 6 :smile:

**Comment by Vistaking** [comment]
thank you , https://github.com/DHowett

That was weird cause I don't remember adding } on  line 7 and removing the comma on line 6
