### ISSUE TITLE
Reload locale specific data when the input language or method changes

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#10729]
`VkKeyScanW` as well as `MapVirtualKeyW` are widely used throughout the project, but are locale sensitive functions. For instance `VkKeyScanW(0)` will return different values for "English (United States)" and "English (United Kingdom)". See #8871.

This issue occurs primarily in two areas:
* The settings model maps characters to virtual keys when deserializing key bindings.
  For instance using the following locale / keyboard layout `ctrl+<` will deserialize to:
  * German: `ctrl+vk(0xE2)` (there's a dedicated `<` key where the `\` key is on the US English keyboard)
  * US English: `ctrl+shift+vk(0xBC)` (`<` is `shift+,`)
* After #10666 has been merged it'll map the scan code in the quake mode key binding `win+sc(41)` to a virtual key in order to call `RegisterHotKey`. This scan code to virtual key mappings are highly dependent on the locale, the quake mode key binding will fail to work once the input language was changed.

**Comment by zadjii-msft** [comment]
(notes for posterity, from teams)

> (Leonard) tried:
> * `WM_INPUTLANGCHANGE` -- not being sent to our UWP app (nor any other event when pressing Win+Space)
> * `CoreTextServicesManager.InputLanguageChanged` -- gets only triggered for input language but not method (aka layout) changes	
> * `ITfActiveLanguageProfileNotifySink::OnActivated` -- not getting called at all	
> * XAML's `ResourceContext.QualifierValues` -- not getting updated
