### ISSUE TITLE
Lost ssh connection => mouse clicks cause garbage

### ISSUE THREAD

**Issue by hensz** [microsoft/terminal#10728]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

OpenSSH for WSL 1
tmux

### Steps to reproduce

I'm using the wsl terminal to connect via ssh to a Linux box, there I'm using tmux to have a persistent session. When the connection terminates, e.g. due to a network outage, the terminal stays open and functional, but every mouse click inside the terminal window causes garbage input to appear.
If I only use ssh to connect to Linux and connection breaks, the ssh connection end and the terminal is still fully functional. So it's a combination of terminal, ssh and tmux.
With a different terminal I don't see this issue, so Windows Terminal has something to do with this behavior.

### Actual Behavior

In the screenshot you can see what happens if I simply left-click inside the terminal window several times.
![terminal](https://user-images.githubusercontent.com/1984979/126353390-db6f8079-1c29-48fd-bc85-5bd84ff4fd1e.jpg)

**Comment by DHowett** [comment]
Unfortunately, this is by design. Terminals have always had this trouble -- applications are expected to assert the state they want before they want it (in this case: mouse mode) and deassert the state _after they're done with it_. Terminating a connection to an application that requested mouse mode or even just killing the app before it turns off mouse mode will always leave the terminal in an inconsistent state.

You can recover by using the `reset` command (in WSL) or printing "\`ec" in PowerShell (Core).

**Comment by DHowett** [comment]
FWIW: Here's what happens in putty...

![mouse-mode-putty](https://user-images.githubusercontent.com/189190/126358519-fbdedf9f-fa72-474f-8962-884b6d1a8415.gif)

and here's what happens in gnome-terminal...

![mouse-mode-gnome-terminal](https://user-images.githubusercontent.com/189190/126358462-3868a90e-4932-41f1-b544-60bb45f72684.gif)

**Comment by hensz** [comment]
Great, thanks for your reply. I'll try using reset.

Up to now I was using terminator on WSL with a direct ssh connection
terminator -x bash -ic 'ssh -X myhost'

If the connection is lost, the terminal window is closed. I wanted to also have this behavior with Windows Terminal, but I haven't found a way to start the terminal with WSL and directly launch an ssh connection.

For terminator I'm using vbs:
args = "-c" & " -l " & """terminator -x bash -ic 'ssh -X myhost'"""
WScript.CreateObject("Shell.Application").ShellExecute "bash", args, "", "open", 0
