### ISSUE TITLE
Paste without warning about newline

### ISSUE THREAD

**Issue by hensz** [microsoft/terminal#10720]
Hi!

While it's great that Terminal warns if I paste something that contains newlines, in some cases this is done intentionally, and in these cases the warning is a bit annoying.

Is there a way, e.g. a custom action, to paste without this warning?

**Comment by zadjii-msft** [comment]
Good news, there is, please [check out the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#warn-when-the-text-to-paste-contains-multiple-lines).

**Comment by hensz** [comment]
Sorry for bothering again. This feature is helpful, but for my usecase it would be better if I could have the warning enabled, but also have the possibility to disable it on demand, e.g. with a certain keyboard shortcut bound to some action. Do you think this is feasible?
