### ISSUE TITLE
Launching in Focus mode doesn't start at the correct size

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10730]
Is there any plan to make focus mode respect the number of rows and padding settings, especially at startup?

**Comment by DHowett** [comment]
Given that nobody's ever told us that it didn't do so, there was no plan to. After all, we can't plan for something we don't know needs to be done.

**Comment by vefatica** [comment]
OK, it doesn't.  My preference would be that focus mode (startup too) remove the tab portion of the window, making it smaller but respecting the rows and paddings settings (as opposed to converting the tab portion to output).

**Comment by zadjii-msft** [comment]
This may also be related to the fact that FOMO starts at the wrong size after a session restore. Fixing this might be the easiest way of fixing that, honestly.
