### ISSUE TITLE
Increase user efficiency on return from reboot/closing terminal

### ISSUE THREAD

**Issue by Zalmez** [microsoft/terminal#10739]
# Description of the new feature/enhancement

When closing, or rebooting I would love to have the windows terminal return to the same state as it was in before the close or reboot. Not necessarily fully the same state, but being able to return to having all the tabs I had open from earlier could speed up the working speed and efficiency 

How I would imagine this work (2 options):
1. In a way pretty equal to a browser it would return to having the same tabs open.
2. If the first option is not viable how about being able to create sets of tabs, example I often use powershell and a few linux shell tabs if I could chose a set of tabs i want to open from the dropdown that could help

**Comment by Poopooracoocoo** [comment]
also see #961

**Comment by zadjii-msft** [comment]
Yea, this is: 

/dup #766 
/dup #961
