### ISSUE TITLE
conhost memory usage stays elevated after writing large buffers

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#10731]
The `_CONSOLE_API_MSG` buffer is resized to encompass the entire message size:
https://github.com/microsoft/terminal/blob/5f2ac4e3e774b87b982d6a665aa6bdc52c589753/src/server/ApiMessage.cpp#L107-L109

Later on any UTF-8 data is cached in a separate temporary buffer inside `til::u8state` to prevent lone surrogate pairs:
https://github.com/microsoft/terminal/blob/9c1331ab2ec517e832cf8fd4e0c88275103acc9f/src/host/_stream.cpp#L1140-L1147

Both cases are problematic as neither buffer is freed after the read has finished.
Passing a 100MB buffer to conhost once will cause it to continue using ~220MB of physical memory until the conhost process exits.

# Proposed technical implementation details

* `API_MSG` buffer: Eagerly release any buffers over 16MB.
* `til::u8state`: Replace with a class that doesn't require the input string to be cached.

**Comment by DHowett** [comment]
We should be able to do [1] for the inbox ingestion during Ask mode, but we need to constrain the fix for [2] if we want to get it in as well. What do you think?

**Comment by lhecker** [comment]
@DHowett Releasing large buffers early would half the memory usage of conhost. But in case of `CP_UTF8` output it would still retain at least one maximum sized buffer for the lifetime of the process.
In my _personal_ opinion we should be able to just limit `CONSOLE_IO_RAW_WRITE` messages. As far as I can see it's exclusively sent for `NtWriteFile` calls, and those can be read with short reads. If we did that, we could ignore the fix for [2].
I can't estimate how important either of these fixes are, so I'm uncertain how we would want to approach this issue.

**Comment by DHowett** [comment]
Given how close we are to the checking deadline, I would rather not risk the `CONSOLE_IO_RAW_WRITE` change 😕

**Comment by lhecker** [comment]
In that case the only thing we can do is a half-fix by reducing the memory usage down to 120MB after printing a 100MB buffer (as an example).

**Comment by DHowett** [comment]
Can we hack it by forcing u8state to `shrink_to_fit` when it clears? So if we `shrink_to_fit` both the small_vector for the message buffer and the string state for the utf-8 parser... we might be able to win back some of our losses?

**Comment by DHowett** [comment]
Like... what if there's a heuristic we could use to guess when to shrink.

```
// at the end of the conversion, sot hat we know how much space we used
if ((buffer.capacity() >> 1) > buffer.size()) {
    buffer.shrink_to_fit();
}
```

an application that consistently passes large buffers will make us hold our allocation, because we won't need it. an application that dumps text of varying lengths will eventually cause us to return that allocation and make a new, smaller one. It allows a poorly-behaved application to make us make a lot of transient allocations and discard them (write a large string, a small one, a large one, ...)... but _they're only making themselves suffer_ if they do that.

**Comment by DHowett** [comment]
Downside: if an application writes one giant blob of text once and then never writes anything else, we'll hold on to that memory. But an application that does that isn't terrifically common, I'd guess.
