### ISSUE TITLE
Can't type on Windows Terminal

### ISSUE THREAD

**Issue by brunnolira** [microsoft/terminal#10736]
When I open the Terminal the cursor is blinking but keyboard input does not work.

Already tried the thread https://github.com/microsoft/terminal/issues/4448 and it did not worked for me.
Service "Touch Keyboard and Handwriting Service" is not disabled and I don't have MSI Afterburner installed.

Windows Terminal Version - 1.8.1444.0
Windows Version - Windows 10 Pro - 21H1 - 19043.1110

**Comment by zadjii-msft** [comment]
There's a bunch of help from **@&zwj;ebadger** in #9890 - could you try following the steps in that thread, and see if that resolves the issue?

(sorry for the runaround, we really need to turn that thread into a guide on the troubleshooting page of the docs)

(see also #10095)

**Comment by brunnolira** [comment]
Thanks a lot @zadjii-msft, both threads help me.

I had the same situation as #9890, just killing the process returned by the command "tasklist /m msctfmonitor.dll" and starting "ctfmon.exe" made the Terminal work again.

Shame that I have to do this every time I restart the PC, and that I wasn't able to find this tread before asking for help, maybe because of it's title.

But anyway, thanks again.

**Comment by brunnolira** [comment]
Made this powershell script to help.


if((Get-Process -Module msctfmonitor.dll -ea SilentlyContinue) -ne $Null){ 
    Stop-Process -ErrorAction SilentlyContinue
}

if((Get-Process -Module msctfmonitor.dll -ea SilentlyContinue) -eq $Null){ 
    ctfmon.exe
}
wt
