### ISSUE TITLE
Windows Terminal can install but no open

### ISSUE THREAD

**Issue by MahefaAbel** [microsoft/terminal#10747]
### Windows Terminal version (or Windows build number)

10.0.19043.928

### Steps to reproduce

1. Download Microsoft.WindowsTerminal_1.9.1942.0_8wekyb3d8bbwe.msixbundle
2. Install Microsoft.WindowsTerminal_1.9.1942.0_8wekyb3d8bbwe.msixbundle
3. Launch "Windows Terminal" installed
4. Got error on attacheds images

<img width="415" alt="Windows terminal" src="https://user-images.githubusercontent.com/21125831/126525778-af89d695-59e8-4c16-8e4b-ab00180622a3.png">

<img width="341" alt="winver" src="https://user-images.githubusercontent.com/21125831/126525782-f3ef0eb1-a030-43e3-89b9-d3e6b6b22b2a.png">

<img width="413" alt="Windows terminal 2" src="https://user-images.githubusercontent.com/21125831/126525774-ed09dd47-c5b3-4693-844f-75aca535092a.png">

### Expected Behavior

Terminal launch/open normally (I don't need to dscribe how windows terminal normally launch I think)

### Actual Behavior

Got error on attacheds images

<img width="415" alt="Windows terminal" src="https://user-images.githubusercontent.com/21125831/126525778-af89d695-59e8-4c16-8e4b-ab00180622a3.png">

<img width="341" alt="winver" src="https://user-images.githubusercontent.com/21125831/126525782-f3ef0eb1-a030-43e3-89b9-d3e6b6b22b2a.png">

<img width="413" alt="Windows terminal 2" src="https://user-images.githubusercontent.com/21125831/126525774-ed09dd47-c5b3-4693-844f-75aca535092a.png">

**Comment by zadjii-msft** [comment]
Okay so a rudimentary internet thanslation of those messages is 

"The network location cannot be reached. For information on resolving network problems, see Windows Help"

"Quick Cache data not found"

Which looks like we've seen a few times before: https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22The+network+location+cannot+be+reached%22

> /dup #6010 this looks like the issue we're already tracking and trying to resolve, but nobody knows what causes it and none of our machines seem to reproduce it.
