### ISSUE TITLE
in the profile pages of the settings there are scrollbars that don't actually scroll

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/terminal#10743]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. ![image](https://user-images.githubusercontent.com/51363864/126473088-fec3b3b0-5802-4554-8ed1-1a6f8e094408.png)
2. navigate to profile settings

### Actual Behavior

![image](https://user-images.githubusercontent.com/51363864/126473141-783f281c-f87e-435d-8740-6edc22c3ea56.png)
as above

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to  #10664 for more discussion.

/dup #10664

**Comment by Poopooracoocoo** [comment]
thanks mate. i see tons of these empty scrollbars across windows lol
