### ISSUE TITLE
Single-instance mode is not working in some cases

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#10740]
### Windows Terminal version (or Windows build number)

10.0.19042.1110 1.8.1521.0

### Other Software

Visual Studio Code

Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

### Steps to reproduce

1. Open `Windows Terminal` via the shortcut in `Start › All apps › Windows Terminal`
2. Set `"windowingBehavior"` to `"useExisting"` or `"useAnyExisting"`
3. Open Visual Studio Code
4. Change next VSC settings
	```js
	"terminal.explorerKind": "external",
	"terminal.external.windowsExec": "wt.exe",
	```
5. Open folder in VSC
6. Right-click on folder item in VSC Explorer
7. Then context menu item `Open in Windows Terminal`
8. New Windows Terminal window is opened instead of using the first one

Thanks! Let me know if you need more details.

### Expected Behavior

The single-instance mode should work in all cases.

### Actual Behavior

I'm getting a new window when opening the folder via the Visual Studio Code context menu.

**Comment by DHowett** [comment]
Are either of your instances running elevated? We've seen a report of this before, but only when mixing admin and non-admin sessions.

**Comment by ihodex** [comment]
> Are either of your instances running elevated? We've seen a report of this before, but only when mixing admin and non-admin sessions.

Nope. Also noticed the same situation when trying to open folder from Sublime Text via [Terminal](https://packagecontrol.io/packages/Terminal)

**Comment by zadjii-msft** [comment]
FWIW, I'm not seeing this anymore, and OP deleted their account. I'm closing this since we can't lock down a repro w/o more feedback here.
