### ISSUE TITLE
Vim leaves text in the terminal

### ISSUE THREAD

**Issue by vivekananthrp** [microsoft/terminal#10745]
### Windows Terminal version (or Windows build number)

Windows Terminal 1.8.1521.0

### Other Software

Windows 10 (Version 10.0.19042 Build 19042) with WSL2 Ubuntu 20.04.
Vim (8.1.2269)

### Steps to reproduce

When I open text files using Vim (8.1.2269) inside WSL2 Ubuntu 20.04, it leaves behind chunks of text from the text file in the terminal.

Steps to reproduce the issue:
1. Open windows terminal and open a tab with Ubuntu 20.04
2. Open a text file with enough lines for scrolling
3. Use keys pg-up / pg-down / g (to reach top) / G (to reach bottom) / scroll through the file using trackpad
4. Close Vim (using :q)
5. Scroll up the terminal
6. Chunks of text from the file appears in the terminal

The above issue doesn't happen if I just use the up-arrow or the down-arrow for navigating through the file inside Vim.

Attaching a screen recording of the above-described issue.

https://user-images.githubusercontent.com/11735154/126499082-819fa070-10b5-49be-b76e-517df478a73d.mp4

### Expected Behavior

Text from Vim should not be seen in the terminal.

### Actual Behavior

Text from Vim appears in the terminal, when you scroll-up after closing Vim.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #381 for more discussion.

/dup #381
