### ISSUE TITLE
Implement dynamic support for VSDevCmd profiles

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#10752]
I see a lot of developers adding entries to start the Visual Studio Developer Command Prompt, but its location can vary from machine to machine and multiple instances may be installed.

You can use the [`ISetupConfiguration` COM server](https://docs.microsoft.com/dotnet/api/microsoft.visualstudio.setup.configuration.isetupconfiguration) (the server is actually native, which is what we use in https://github.com/microsoft/vswhere) to find instances, which populate instances automatically if 1) installed, and 2) any instances are present.

A profile `source` could be something like `VisualStudio_<InstanceId>`. If the COM server can be created - ignoring `REGDB_E_CLASSNOTREG` - instances can be enumerated and command lines inferred from `Common7\Tools\VSDevCmd.bat`. As with any other dynamically discovered profile any number of profiles could be disabled.

The COM server supports Visual Studio 2017 and newer, but [as with vswhere](https://github.com/microsoft/vswhere/blob/5d250b95a2c4d312961ed4e811fe240db197c404/src/vswhere.lib/InstanceSelector.cpp#L125-L142), older versions could be supported, though, IIRC, the actual batch file name and perhaps where it is located is different.

**Comment by skyline75489** [comment]
You may find #7774 interesting.

**Comment by zadjii-msft** [comment]
Yea, this is /dup #3821

**Comment by heaths** [comment]
Thanks. I searched for existing issues but didn't see anything obvious. I'll review it as well as the original author of the setup configuration server and vswhere.
