### ISSUE TITLE
Enable a background image on top of an acrylic brush

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1075]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18908.1000]
Windows Terminal version (if applicable): commit id d24d647 and 71e19cd tested.

```

# Steps to reproduce

add "backgroundImage" to profiles.

# Expected behavior

Backgroung Image changes to what I have selected.

# Actual behavior

Only Powershell works as expected, cmd, ubuntu, ... doesn't work like image I've pasted. (Just stays as normal)
![image](https://user-images.githubusercontent.com/29011440/58688033-4bc90180-83be-11e9-91f4-a964fee27345.png)

**Comment by Summon528** [comment]
The current implementation of background image requires you to disable acrylic

**Comment by mdtauk** [comment]
When a background image is set, the acrylic should not be disabled.  Instead the acrylic brush should change from a **backdrop** host one, to an **in app** one.  This will then blur the background image and not show what is behind the window

**Comment by Summon528** [comment]
> 
> 
> When a background image is set, the acrylic should not be disabled. Instead the acrylic brush should change from a **backdrop** host one, to an **in app** one. This will then blur the background image and not show what is behind the window

Yeah that is the ideal solution. However this is an unimplemented feature, rather than a bug for now. Core dev did mention to file a follow-up issue for this feature https://github.com/microsoft/terminal/pull/853#pullrequestreview-241953563 but apparently that has not been done yet

**Comment by zadjii-msft** [comment]
Congratulations, this is now that follow-up

**Comment by DHowett-MSFT** [comment]
Thought: to make this a little better, we might want to implement something like "background stacks" -- so you can specify:

```
background: [
  { ... acrylic host backdrop ... }
  { ... image tux.exe ... }
  { ... acrylic app-backdrop ... }
]
```

Marking this as Issue-Feature?

**Comment by isaac2004** [comment]
If I am following this, the following experience is not supported. 

- Image with transparent background over a solid background

I have tried a few combinations of settings to no avail

**Comment by DHowett-MSFT** [comment]
Indeed. This will hopefully fix that issue as well.

**Comment by mdtauk** [comment]
On top of acrylic, it is more of a watermark.  It would also need a placement option.

**Comment by Jaykul** [comment]
We definitely need a placement option
