### ISSUE TITLE
[Req] Mac/Linux Release

### ISSUE THREAD

**Issue by imthiachulu** [microsoft/terminal#10766]
# Description of the new feature/enhancement

# Windows Terminal for Mac/Linux, I know this topic is going on for a while but do we have anything into consideration. Is it a work in progress or can we expect this for MAC/Linux distributions?

Old ref: https://github.com/microsoft/terminal/issues/563

**Comment by Wagnerp** [comment]
Not possible, as Windows Terminal uses underlying Windows components (CMD) that MacOS & Linux does not have.

**Comment by imthiachulu** [comment]
Thank you for the quick response, Peter.

I was just wondering if Windows Terminal team has this in their future plans like we never had MAC versions for VScode, MS office etc. I understand they are electron applications and have developed it over long years, but replacement of it with open-source components would be awesome.

**Comment by Wagnerp** [comment]
Hi @imthiachulu 

The difference between Windows Terminal and VSCode is that VSCode and MS Office are independent applications. Windows Terminal is kind of a evolution of CMD `conhost.exe` in Windows, so the source code in this repository finally ends up in the main Windows OS source tree somewhere down the line. Plus I think the team are planning to change the release schedule, as it's being baked into Windows 11 as the default terminal.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22linux+support%22+is%3Aclosed+) when filing new issues. I've also made sure to update the FAQ with this question. 

Windows Terminal requires a good number of Windows-specific technologies. We unfortunately won't be supporting it on Mac or anywhere else any time soon. There are some really good terminals on OS X, including iTerm and Hyper, and an uncountable number of good terminals on Linux.


/dup #2331 #504 #563 #624 #2466 #699 #498 #6074 #4235 #6255
