### ISSUE TITLE
code in Cloud Shell launches vscode

### ISSUE THREAD

**Issue by richeney** [microsoft/terminal#10769]
# Description of the new feature/enhancement

Typing code in the browser version of [Cloud Shell](https://shell.azure.com) opens up the Monaco editor. And the toolbar offers upload / download icons.

Using the Cloud Shell profile in Windows Terminal is far better as a CLI experience - especially with the cached connection settings. But it does miss out on any integration with vscode (Cloud Shell outwards) and any drag and drop type upload capability.

The suggestion is that typing `code .` would open the current Cloud Shell folder in vscode through a Remote Development extension, and that the Explorer would allow easy file upload / download. 

I have no idea if the current Remote - SSH or Remote - Container vscode extensions could be leveraged, or if it would require a new extension (which could then also be added to the vscode Remote Development extension pack).

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5636 for more discussion.

/dup #5636
