### ISSUE TITLE
Quake Mode - Working Directory on Launch

### ISSUE THREAD

**Issue by DGamer007** [microsoft/terminal#10764]
# Description of the new feature/enhancement

I was hoping if Windows Terminal has this feature...

Suppose, I am working in VSCode and I have a need of terminal so I will open up Windows Terminal in Quake Mode but it is opening it in **System32** and instead I can open it in VSCode working directory...

and I have already setup Windows Terminal for VSCode as an External Terminal but I dont know how to do it for Quake Mode.

**Comment by zadjii-msft** [comment]
You can manually launch into the quake window with the commandline `wt -w _quake`. So something like `wt -w _quake -d .` probably _should_ open in the appropriate directory. I'm not really sure how exactly VsCode passes the working directory information to the terminal it launches, so you might need to adjust the `-d` param accordingly. 

See also the docs:
* https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows
* https://docs.microsoft.com/en-us/windows/terminal/tips-and-tricks#quake-mode

**Comment by DGamer007** [comment]
Yeah, I'll look into it but I kinda did a trick in order to achieve it ....
So, I will open Windows Terminal from VSCode (External Terminal) so VSCode will open it into my project directory and then If I open Quake Window using `Win` + ``` ` ``` then I will be able to use Quake windows untill I open it in some other directory or I restart my device.
