### ISSUE TITLE
When adding a variable to PATH, restarting tab with terminal doesn't help

### ISSUE THREAD

**Issue by rakleed** [microsoft/terminal#10768]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

1. Open Windows Terminal with two tabs - Command Prompt and PowerShell Core
2. Add a new variable to PATH
3. Close tab with PowerShell Core
4. Open a new tab with PowerShell Core
5. Enter the command added as a variable to PATH

### Expected Behavior

The command is recognized as a variable and works.

### Actual Behavior

The command is not recognized as a variable and does not work.

In order for it to work, you need to completely restart Windows Terminal, and not just a separate tab with the terminal.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1125 for more discussion.

/dup #1125
