### ISSUE TITLE
CD command can't excute when path contains space

### ISSUE THREAD

**Issue by hupo376787** [microsoft/terminal#10765]
### Windows Terminal version (or Windows build number)

19041.1110, 1.8.1521.0

### Steps to reproduce

Cd to a directory contains space, such as `C:\Program Files\`.

### Expected Behavior

Cd to `C:\Program Files\`

### Actual Behavior

![image](https://user-images.githubusercontent.com/14960168/126750206-48cfc323-b3c7-4ff1-bc25-9c01d904e200.png)

**Comment by zadjii-msft** [comment]
You need to wrap paths with spaces in quotes. Try:

```
cd "C:\Program Files\"
```
