### ISSUE TITLE
Feature Request: Expose option to use a specific font for unicode range.

### ISSUE THREAD

**Issue by dstanberry** [microsoft/terminal#10775]
I couldn't find another issue where this was suggested/discussed (_forgive me if the topic has already been brought up_), but it would be great if terminal supported something like the `symbol_map` option in [kitty](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map).

For some, it would be an alternative to nerd fonts (if your preferred font does not have the extra glyphs).

**Comment by j4james** [comment]
I think issue #2664 is what you're asking for.

**Comment by dstanberry** [comment]
It is. Thanks for pointing it out.

Duplicate of #2664.
