### ISSUE TITLE
Wrong opacity in menus and right context menus in Windows Build 22000.100

### ISSUE THREAD

**Issue by hmartinez82** [microsoft/terminal#10773]
### Windows Terminal version (or Windows build number)

Version 10.0.22000.100, 1.8.1521.0

### Steps to reproduce

Activate any menu or right click menu in Windows Terminal

### Expected Behavior

The new transparency from Windows 11 build 22000.100 should not affect the menu foreground colors.

### Actual Behavior

The new transparency from Windows 11 build 22000.100 is affecting the whole menu
![Untitled](https://user-images.githubusercontent.com/1100440/126843071-607a2816-8961-49c0-9c90-2125f7280679.png)
![Untitled2](https://user-images.githubusercontent.com/1100440/126843077-b0a57813-b810-494c-9ef2-9953a2148906.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! We (the Windows OS team) are actually tracking this one internally and hope to have a fix "soon".

@DHowett Might be able to find the root issue - I can't seem to.

I think this is also tracked over in /dup https://github.com/microsoft/microsoft-ui-xaml/issues/5133.

**Comment by zadjii-msft** [comment]
it might be MSFT:33929740 but that is pretty localized to the Action Center, so I don't think that's the one that's affecting the Terminal

**Comment by zadjii-msft** [comment]
He did find it, it's MSFT:33411893

**Comment by zadjii-msft** [comment]
FWIW I _think_ this is fixed in 22000.130, but Windows 11 build numbers are a lot trickier to decipher than win10 was
