### ISSUE TITLE
Command Prompt Color is reset when zooming

### ISSUE THREAD

**Issue by ScaryBandana** [microsoft/terminal#10771]
Windows-Terminal Version: 1.19.1942.0

Description: If you change the color of the prompt with "color a" and then zoom with CTRL + mouse wheel, the color resets itself to the standard value.

Steps to reproduce:
1. Open Windows Terminal with cmd.exe configuration.
2. Type "color a".
3. Zoom with CTRL + mouse wheel.
4. Type something, the typed text not in the set color but in the standard color.

If you change the background with "color fc" and then zoom in, the problem also occurs.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #32 for more discussion.

/dup #32
