### ISSUE TITLE
Feature Request: Undercurl support (dotted and dashed as well I guess)

### ISSUE THREAD

**Issue by markhagemann** [microsoft/terminal#10783]
# Description of the new feature/enhancement
Example:

![folke trouble undercurl (2)](https://user-images.githubusercontent.com/21050889/126869462-77120cdc-b1b6-47b5-b595-3d5bc7e9a8d2.png)

Apologies if this is already working somehow but I've followed a few guides and haven't had any luck on Windows 10 with WSL2 using Windows Terminal along with [WezTerm](https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines) but as soon as I used the same dotfiles within a VirtualBox for Garuda OS it worked for undercurls. 

Existing Behavior:
![missing undercurl support](https://user-images.githubusercontent.com/21050889/126869098-41edc40f-cb94-4b0e-800a-b3ff8d7c9f6e.PNG)

Expected Behavior:
<img width="649" alt="wez printf (2)" src="https://user-images.githubusercontent.com/21050889/126869460-d16ffd45-7598-4662-9a91-8801c0a28f27.png">

# Proposed technical implementation details (optional)
I have very limited knowledge on this but it seems the main thing to support this for tmux is `Smulx` if that helps

```
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
```

**Comment by j4james** [comment]
This is not supported, but there is an issue for it: #7228.

**Comment by markhagemann** [comment]
Closing in favor of https://github.com/microsoft/terminal/issues/10783
