### ISSUE TITLE
wt.exe help messagebox icon change

### ISSUE THREAD

**Issue by MrDFLL** [microsoft/terminal#10785]
# Description of the new feature/enhancement
When you write in command line wt.exe --help it opens a messagebox with a warning icon it should be changed into info icon
(blue with i symbol)

![old](https://user-images.githubusercontent.com/55166553/126880944-cf255287-b5fe-48b1-9417-a8e649bdded3.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! You know, it might not seem like it, but I think this will get fixed by #4134. We'll be using that issue to track "improve that UI entirely". We probably won't even be using `MessageBox` at all anymore, so this'll just be fixed by that.

/dup #4134
