### ISSUE TITLE
[Feature Request] Warn if there is a program running before a tab is closed

### ISSUE THREAD

**Issue by dingwen07** [microsoft/terminal#10784]
# Description of the new feature/enhancement

When closing a tab, if there are programs other than shell running in the terminal, killing them may cause problems. A warning, just like when closing multiple tabs, is suggested.

# Proposed technical implementation details (optional)

It may be possible to determine whether there is a program running in the terminal through the process tree.

**Comment by j4james** [comment]
I think this would probably be covered by issue #6549.

**Comment by zadjii-msft** [comment]
Yep, this is definitely /dup #6549. Thanks!
