### ISSUE TITLE
Settings editor erases the symbolic link rather than following it

### ISSUE THREAD

**Issue by roflolilolmao** [microsoft/terminal#10787]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.10.1933.0

### Other Software

Symbolic link created from my configuration repository with this command:

```powershell
New-Item `
 -ItemType SymbolicLink `
 -Force `
 -Path "$env:LOCALAPPDATA\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json" `
 -Target ./terminal/settings.json
```

### Steps to reproduce

1. Create a symlink to the settings file;
2. open the settings in the terminal and hit the save button.

State after 1.:

![image](https://user-images.githubusercontent.com/9419517/126890858-95c9f7ed-3cfc-472e-9ead-15bbda7f94f2.png)

State after 2.:

![image](https://user-images.githubusercontent.com/9419517/126890825-0bba6e1d-2f07-49a3-917b-c9e54f2f4b83.png)

### Expected Behavior

The settings editor follows the symbolic link and saves the file in my configuration repository.

### Actual Behavior

The settings editor erases the symbolic link.

**Comment by Diablo-D3** [comment]
This breaks any use case that involves a typical dotfiles repo setup; ergo, I've been bitten by this at least once.
