### ISSUE TITLE
"One Half Light" theme vim visual line can't be seen as it blends with the background.

### ISSUE THREAD

**Issue by smitbarmase** [microsoft/terminal#10782]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

vim in WSL 2

### Steps to reproduce

Use `shift + v` to go in visual line mode in vim. Set "one half light" as your theme. The visual line can't be seen.

![image](https://user-images.githubusercontent.com/37347831/126865595-ea2d7723-cff7-4dec-8e86-d21a9ec1b7f4.png)

### Expected Behavior

It should have greyish color, like it is in tango theme.

### Actual Behavior

Visual line color bends in with the background.blends

**Comment by j4james** [comment]
If you're using a light theme like "One Half Light", I believe you need to set the vim color scheme to match. For example, try using `:colorscheme peachpuff` in vim. That should make the visual line visible.

That said, I think vim might be able to do this automatically if it detects the terminal is using a light theme, but it probably relies on color querying sequences which we don't yet support (see #3718).

**Comment by zadjii-msft** [comment]
Yea, this just sounds like you need to configure `vim` theme to work with your color scheme. Every scheme's got it's own quirks. There's quite a few combos of colors in One Half Light that aren't all that readable:

![image](https://user-images.githubusercontent.com/18356694/127011381-93167c64-a1d4-42fa-a9db-ca188c496748.png)
