### ISSUE TITLE
How do I start the terminal as an administrator

### ISSUE THREAD

**Issue by Zz-886** [microsoft/terminal#10781]
How do I start the terminal as an administrator

**Comment by Haleymiranda79** [comment]
Right click and choose run as admin when opening.

**Comment by Zz-886** [comment]
Without this option

**Comment by zadjii-msft** [comment]
If the taskbar context menu doesn't work for you:

![image](https://user-images.githubusercontent.com/18356694/127002071-8407d06b-6e70-48bf-9d07-15499f9694d0.png)


Then you'll probably be wanting #632, with a spec in progress at #8455 and a draft PR over in #8514.

/dup #632
