### ISSUE TITLE
Could the icons in taskbar be changed according to the icon in the actived tab?

### ISSUE THREAD

**Issue by sshxmz** [microsoft/terminal#10792]
Windows Terminal version: 1.8.1521.0
Windows Version: windows 10 20H2

Steps to reproduce:
1) open the windows terminal with two tabs: cmd.exe and wsl.exe;
2) switch between the cmd.exe and the wsl.exe;
3) the icon in the taskbar is always the default '>_';

Expect:
The icon can be changed when the actived tab changed. For example, when I click the tab of wsl.exe, the icon in taskbar should be changed to a penguin (🐧) rather than the '>_'.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6556 for more discussion.

/dup #1871
/dup #6556
