### ISSUE TITLE
Windows Terminal with WSL Default profile errors when set to default terminal app during startup

### ISSUE THREAD

**Issue by VibroAxe** [microsoft/terminal#10793]
### Windows Terminal version (or Windows build number)

1.10.1933.0 / 10.0.22000.65

### Other Software

Windows Subsystem for Linux as Default Profile

### Steps to reproduce

* Set a wsl distro (automatically detected) as default profile 
* Set windows terminal to be default terminal application
* Add a console app (cmd/powershell) to windows startup
* Reboot
* ...
* Receive error on unable to find default profile (because wsl provider hasn't inited fully presumably)

### Expected Behavior

* Windows terminal is able to correctly run startup apps

### Actual Behavior

* Error message - unable to find default profile
* Closing the terminal window and restarting WT after startup has complete correctly finds the wsl profile

**Comment by zadjii-msft** [comment]
As weird as it seems, this is actually going to be fixed when we finish #10669. /dup #10669
