### ISSUE TITLE
Add option to launch every Terminal session as administrator

### ISSUE THREAD

**Issue by timonsku** [microsoft/terminal#10791]
# Description of the new feature/enhancement

Motivation:
Most of the time I want my terminal to be elevated/run as administrator. I close and open the app many times a day, so always needing to go through the shortcut first is cumbersome. Also I can not do that if I want to open a terminal window via the right click menu in Explorer which is what I do most of the time so I always need to have an elevated session and a non-elevated session running which becomes really annoying and hard to keep track off.

Solution:
I want a setting that forces every Terminal window to be run as administrator, no matter how or where I start it from.

# Proposed technical implementation details (optional)

Afaik an app can request to be launched as admin if it can't function without elevated rights. I'm not sure if that behaviour is part of the Win32 API or somehow baked into a binary but if it is switchable then I would love to have that as an option in the Terminal settings.

**Comment by zadjii-msft** [comment]
You'll probably be wanting #632, with a spec in progress at #8455 and a draft PR over in #8514.

/dup #632

**Comment by timonsku** [comment]
ah thanks! I searched but didn't find that one
