### ISSUE TITLE
Inconsistent Color in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#108]
_From @computersarecool on May 12, 2017 4:8_

I am using `Microsoft Windows [Version 10.0.16188.1000`

There is a very strange color issue. I am using `Emacs` and for one of my themes, the colors are not being displayed at all.  I am using the [Cyberpunk Emacs theme](https://github.com/n3mo/cyberpunk-theme.el) which is normally very colorful but basically no colors are rendered.

Here is a picture:

![color issues in Bash for windows](https://cloud.githubusercontent.com/assets/5414692/25981965/75f7a2fc-368d-11e7-874a-b1345db8a56b.png)

What is strange is that, when I Alt-Tab (and the many smaller windows appear) you can actually see the colors.

I know that the other colors work because  other colors work and when I preview colors within Emacs, I see all other 256 colors
![all colors in emacs](https://cloud.githubusercontent.com/assets/5414692/25981987/a49ea358-368d-11e7-9f9a-2d7bc793f210.png)

The above image was taken on the same machine.

I know that this theme works because on my Linux partition, all colors are shown. 

Thanks for any insight

_Copied from original issue: Microsoft/WSL#2089_

**Comment by bitcrazed** [comment]
_From @Line117 on May 13, 2017 10:47_

Sorry for the answer is not to the point.
Try using this (http://conemu.github.io/ Preview Version) console emulator. It's solves many problems.

**Comment by miniksa** [comment]
Does this still happen?

**Comment by computersarecool** [comment]
Yep.

**Comment by apolopena** [comment]
Yes

**Comment by zadjii-msft** [comment]
@apolopena That unfortunately doesn't really give us anything to help diagnose and debug this bug. Would you mind helping provide:
* What version of windows are you running?
* Are you using the Windows Terminal? If so, what version?
* Are you seeing this with the same emacs theme mentioned above, or some other one?
* What's the output of `echo $TERM` from within WSL?

**Comment by zadjii-msft** [comment]
This hasn't had any movement in years, or any other similar issues. Likely was fixed by some other bugfix in the last 4 years since this was filed. Closing for housekeeping.
