### ISSUE TITLE
UI Issue with Default Profile dropdown in settings page

### ISSUE THREAD

**Issue by gopkumr** [microsoft/terminal#10800]
### Windows Terminal version (or Windows build number)

10.0.19043.1110, 1.9.1942.0

### Steps to reproduce

- Open settings tab
- Expand the default profile dropdown
- Keeping the dropdown open, scroll the page using the scroll wheel on the mouse
- The gif below shows the behavior

![2021-07-27-09-33-47](https://user-images.githubusercontent.com/1662197/127073342-4d89359f-b6ea-4b1d-b5b6-92bac60bf030.gif)

### Expected Behavior

The dropdown should stay within the screen

### Actual Behavior

The dropdown scrolls to outside of the window.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+profile+dropdown) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
