### ISSUE TITLE
Launch powershell.exe error  0x8007010b

### ISSUE THREAD

**Issue by hupo376787** [microsoft/terminal#10804]
### Windows Terminal version (or Windows build number)

19041.1110, 1.9.1942.0

### Steps to reproduce

I update from ms store, 1.8 ----> 1.9

this happens.

![image](https://user-images.githubusercontent.com/14960168/127104647-4338de46-155c-4db6-a44d-741c069f8264.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/14960168/127104619-f2f8225c-414d-4f3d-a636-e028a7aa0a9a.png)

**Comment by zadjii-msft** [comment]
Could you share your `settings.json` file? Also, what's the `%Workspaces%` environment variable set to?

**Comment by hupo376787** [comment]
Hi, I just uninstall the terminal and reinstall it.
So the JSON file is gone.
Thanks.
