### ISSUE TITLE
Quake window location with Windows Magnifier

### ISSUE THREAD

**Issue by Dimension4** [microsoft/terminal#10805]
### Windows Terminal version (or Windows build number)

Windows 10.0.19043.0 Terminal Previw 1.10.1933.0

### Steps to reproduce

1. Make sure quake mode is running (but minimized)
2. Launch Windows Magnifier (Win+Plus)
3. Change view to docked (Ctrl+Alt+D or Settings->Ease of Access->Magnifier->Change Magnifier View)
4. Close Magnifier
5. Show quake window

### Expected Behavior

Quake window shows normally at the top of the screen.

### Actual Behavior

Quake window shows below the previously closed Magnifier view. Closing and opening a new quake instance fixes the issue.

![0610](https://user-images.githubusercontent.com/11558535/127128476-d874b583-5bf9-4cb6-94c0-38566e0d698c.png)

**Comment by WSLUser** [comment]
If you add the "AlwaysonTop" setting to "yes", does it still exhibit same behavior?

**Comment by zadjii-msft** [comment]
This might be fixed in one of my recent QM PRs, but I'm gonna leave this open to follow up and make sure. Thanks!

**Comment by Dimension4** [comment]
@WSLUser yes also happens if _always on top_ is enabled. @zadjii-msft Sounds good, thank you!

**Comment by zadjii-msft** [comment]
Okay yea I just ran through this with a recent build, looks like it was fixed (most likely by #10674). Thanks for the report though!

/dup #10182
