### ISSUE TITLE
Cant write brackets [] and a few other symbols in the new windows terminal in any of the shells

### ISSUE THREAD

**Issue by leet0rz** [microsoft/terminal#10809]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19043.1110]

### Other Software

Nothing

### Steps to reproduce

Just type

### Expected Behavior

To be able to type brackets

### Actual Behavior

Not typing brackets

**Comment by zadjii-msft** [comment]
What keyboard layout are you using? What version of the Terminal?

**Comment by leet0rz** [comment]
Norwegian.
Version: 1.9.1942.0

I am trying to press ctrl + alt + 8 or 9 which are the bracket keys for me.

**Comment by zakius** [comment]
these default to "switch to tab" with respective numbers, you'll need (at least for now) to add `{ "command": null, "keys": ctrl+alt+8" }` and `{ "command": null, "keys": ctrl+alt+9" }` to your settings

when talking about defaults key bindings the `moveFocus` actions are poorly bound making it impossible to pass `alt+cursors` to apps and hopefully that can be fixed

out of curiosity: is that `AltGr` actually or you have to hold both these modifiers at the same time? that feels unusual

**Comment by leet0rz** [comment]
The AltGr works but not ctrl + alt + 8 or 9. That is how most of
Scandinavia with our keyboard layout write those brackets. You should
probably consider changing it to not being ctrl + alt, that is how we type
most symbols.

**Comment by zadjii-msft** [comment]
You know, we have a dupe for this somewhere in the history. 

* It's not #5525
* It's kinda the same thing as #9909
* Ah, /dup #7177 is the one I was thinking of

We definitely goofed when we bound <kbd>ctrl+alt</kbd> keybindings in the first place. Unfortunately, the Terminal's shipped far to many releases with those keys bound by default, and we can't go removing them from the defaults without also blowing them away from anyone who might currently be using them 😕. Alas. We certainly won't be shipping any more on <kbd>ctrl+alt</kbd> in the future.

You can remove the keybindings with:

```json
        { "command": "unbound", "keys": "ctrl+alt+1" },
        { "command": "unbound", "keys": "ctrl+alt+2" },
        { "command": "unbound", "keys": "ctrl+alt+3" },
        { "command": "unbound", "keys": "ctrl+alt+4" },
        { "command": "unbound", "keys": "ctrl+alt+5" },
        { "command": "unbound", "keys": "ctrl+alt+6" },
        { "command": "unbound", "keys": "ctrl+alt+7" },
        { "command": "unbound", "keys": "ctrl+alt+8" },
        { "command": "unbound", "keys": "ctrl+alt+9" }
```

**Comment by zakius** [comment]
> we can't go removing them from the defaults without also blowing them away from anyone who might currently be using them

you can at the first run ask if user wants to keep these I guess? it's hard to discover how to un-break it

and of course don't forget about alt+arrows that also overload terminal input

I think you may consider using super key in all often used shortcuts and some activation/layer switching shortcut using super first for others in future release (next major version so with breaking changes)
