### ISSUE TITLE
We want to add a Chinese name "Windows 终端" to the Windows Terminal application, as well as the corresponding name for the other language display

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#10807]
希望可以为Windows Terminal应用添加一个中文名称“Windows 终端”，以及其他语言显示所对应的名称。
We want to add a Chinese name "Windows Terminal" to the Windows Terminal application, as well as the corresponding name for the other language display.

目前Windows 11已经在Win+X右键菜单和桌面右键菜单将Windows Terminal翻译成了
“Windows 终端”，希望应用磁贴名称也可以显示”终端“和“Windows 终端”，甚至是其他语言所对应的信息，而不是"Windows Terminal"。
At present, Windows 11 has translated Windows Terminal into Windows +X right menu and desktop right menu "Windows Terminal", you want to use the tiled name to also display "Terminal" and "Windows Terminal", even the corresponding information in other languages, rather than "Windows Terminal".
![image](https://user-images.githubusercontent.com/49179966/127188158-ae4f83b8-52c3-4087-b285-ebe5c1953d12.png)
![image](https://user-images.githubusercontent.com/49179966/127188236-ac426dc2-d617-4bde-a5b0-9c09420412fe.png)

**Comment by skyline75489** [comment]
See #5898

**Comment by zadjii-msft** [comment]
h okay, thanks for helping clear that up @skyline75489!

/dup #5898
