### ISSUE TITLE
Save / use the tab color in the profile

### ISSUE THREAD

**Issue by millsoft** [microsoft/terminal#10816]
# Description of the new feature/enhancement

I use the tab color feature a lot. Eg I have green for development server, red for production and so on.
The first thing I do after I open a stored profile I change the color for the tab.

Can the color for the profile be stored so it gets applied automatically? It can still be changed later as usual but it would be great to not needing to set this color all over again.

**Comment by zadjii-msft** [comment]
You can already set this in your profile with [`tabColor`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#tab-color)

**Comment by millsoft** [comment]
cool - very useful! Thanks. this can be closed. Or add a color picker in the profile editor if you like :)
