### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dgilmour77** [microsoft/terminal#1081]
# Environment

```none
Windows build number: Version 10.0.18362.116
Windows Terminal version (if applicable): 

Any other software?

1. Ubuntu/WSL:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

2. VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Note: problem appeared after installing May 2019 Windows update

```

# Steps to reproduce

1. Open Ubuntu terminal by clicking on Ubuntu icon.
2. Set terminal colors via preferences dialog to background gray, text black
3. Open a text file with vim:
4. Scroll down a screen or two
5. Navigate up with cursor until it causes upward scrolling
6. Observe background color of repainted area behind text at top of screen

Also: 
Occasionally happens when scrolling downward with rapid cursor down keystrokes at the bottom of the screen

# Expected behavior

Background color should be uniform

# Actual behavior

Background fills with black background, not the gray background that was set in preferences.

![scroll problem](https://user-images.githubusercontent.com/6298982/58718411-4b127a00-8382-11e9-9757-9976bd7b6d76.jpg)
The color is temporarily corrected by pressing Control-L, forcing a repaint.

I understand this seems similar to other reported bugs, but workarounds suggested elsewhere have no effect, including:

`:set t_ut=""/t_ut=y`
`:set lazyredraw/nolazyredraw`
`:set ttyfast/nottyfast`

Loading other vim color schemes, disabling .bashrc, did not help.  Neovim shows the same problem. I can find no workaround that allows me to use a light grey background and edit files.

**Comment by DHowett-MSFT** [comment]
Workarounds aside, this definitely seems to be #832 #375. Thanks for the report!
There was another workaround in these threads, but I wasn't able to find it.
