### ISSUE TITLE
Cannot handle space in file path when using multiple profiles 

### ISSUE THREAD

**Issue by jordankittle** [microsoft/terminal#10815]
### Windows Terminal version (or Windows build number)

10.0.19041.1052

### Steps to reproduce

Try to open wt with muliple tabs and multiple profiles wt new-tab when there are spaces in the folder names.

### Expected Behavior

Multiple tabs will be opened with multiple profiles

### Actual Behavior

 I can open multiple tabs with multiple profiles just fine when there are no spaces ion the folder names, but when I have spaces in the folder names and I have to enclose the path in quotes, I can only use a single profile in the beginning.

**Comment by zadjii-msft** [comment]
Can you give some example commandlines? `wt -d "c:\program files" ; -d "c:\program files"` seems to work just fine over here...

**Comment by jordankittle** [comment]
Thank you for looking into this. The problem must be that I have a dash in my user name.  This results in the error: 
```wt -d "C:\Users\Jordan - Regular\Files\Web\Pixelmatic\Projects\web-auth-backend" `; new-tab -p "Windows Powershell" -d "C:\Users\Jordan - Regular\Files\Web\Pixelmatic\Projects\web-auth-backend" `; new-tab -p "Windows Powershell" -d "C:\Users\Jordan - Regular\Files\Web\Pixelmatic\Projects\exo-auth"```

**Comment by jordankittle** [comment]
Thank you for looking into this. The problem must be that I have a dash in my user name. This results in the error:
```wt -d "C:\Users\Jordan - Regular\Files\Web\Company\Projects\web-auth-backend" `; new-tab -p "Windows Powershell" -d "C:\Users\Jordan - Regular\Files\Web\Company\Projects\web-auth-backend" `; new-tab -p "Windows Powershell" -d "C:\Users\Jordan - Regular\Files\Web\Company\Projects\back-auth"```

**Comment by vefatica** [comment]
Spaces and hyphens in the directory name seem OK.  These work fine at a CMD prompt and a PowerShell prompt, respectively,

```
wt -d "v:\a - b" ; new-tab -p "Windows Powershell" -d "v:\a - b" ; new-tab -p "Windows Powershell" -d "v:\a - b"
wt -d "v:\a - b" `; new-tab -p "Windows Powershell" -d "v:\a - b" `; new-tab -p "Windows Powershell" -d "v:\a - b"
```

What is "the error"?

**Comment by jordankittle** [comment]
The error is ```[error 0x8007010b when launching `powershell.exe']```

**Comment by zadjii-msft** [comment]
@jordankittle what version of the Terminal are you on? Somewhere in the 1.8-1.9 timeframe, we improved the messaging for that specific error (see #9114, #10045), which might help clarify

**Comment by vefatica** [comment]
That's ERROR_DIRECTORY (the directory name is invalid).  I get it if I use "-d" with the name of a non-existent directory.  I can only suggest you check those names:

```
"C:\Users\Jordan - Regular\Files\Web\Company\Projects\web-auth-backend"
"C:\Users\Jordan - Regular\Files\Web\Company\Projects\back-auth"
```

**Comment by jordankittle** [comment]
They are valid names. I have double and triple checked. The first one works fine, the second errors, even when using the same exact -d name.

**Comment by jordankittle** [comment]
I have verified that this error does not happen when I use the same exact script without the Jordan - Regular folder.  It is only when using this folder that I get the error. And it is always the second instance of new-tab, not the first, even when using the exact same directory name.

**Comment by jordankittle** [comment]
What I am trying to do is build a shortcut that opens tabs to all my working directories for a project. After chasing this for hours, I am very sure there is a bug here.

**Comment by vefatica** [comment]
I had also tried it in the Run dialog (Win+R).  Just now I tried it as the target of a shortcut.  Both worked!  So ... beats me!  I'll be glad to hear what's going on.

**Comment by jordankittle** [comment]
I wish I could give you more information.  If anybody from Microsoft wants to have a meeting where I share my screen let's do it .

**Comment by vefatica** [comment]
@jordankittle, fooling around with this, I just ran into an apparent 260 (MAX_PATH) character limit in a shortcut's command line.  You're command line exceeds 260 characters also.  And if cut off at 260, you're would be right in the middle of a (now bad) directory name.  That's exactly what happened to me (and I got the same error as you).  Did you try your command line at an actual command line (CMD ot PowerShell)?  I wouldn't be surprised if it works there.

If that's the problem, it may be with the shortcut dialog (and not with shortcuts, per se).  Maybe PowerShell or VBScript offers a way to create a shortcut that's not subject to that limitation.

**Comment by jordankittle** [comment]
Wow, I feel a little silly now. Sorry for wasting your time! In my shortcut I have been using it was indeed cut off! Thank you very much and again I'm sorry I didn't catch this. In my shortcut I was using it was the very end that was cut off so that's why when I switched from  "C:\Users\Jordan - Regular" to  "C:\Users" it would work.

**Comment by vefatica** [comment]
FYI, the limitation is with the shortcut dialog, and not with shortcuts, per se.  My shell has a SHORTCUT command.  With it I made a working shortcut with a target well over 300 characters.  AS I said before, you might be able to do that with VBScript, PowerShell, or some other tool.
