### ISSUE TITLE
Better wording for tooltips on settings page

### ISSUE THREAD

**Issue by Lo0oG** [microsoft/terminal#10814]
# Better wording for tooltips on settings page

Some of the tooltips that appear when hovering over the On/Off buttons on the settings page start with "When checked ..." or "When unchecked ..."

![image](https://user-images.githubusercontent.com/50969206/127347083-6539f9bb-cc62-42d0-9e69-a7feffa168a3.png)

Would a better option for these be to say  "When set to On ..." or "When set to Off ..." instead?

**Comment by zadjii-msft** [comment]
Yea that makes sense to me.

**Comment by zadjii-msft** [comment]
"When enabled...."
