### ISSUE TITLE
Restarting Microsoft Edge to install Update killed all Open Windows Teminals

### ISSUE THREAD

**Issue by satya-marigold** [microsoft/terminal#10813]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Have a running windows Terminal Session. I was using a WSL 2 terminal. Then restart edge when it prompts for the update

### Expected Behavior

Windows Terminals remain open

### Actual Behavior

All the terminals shutdown

**Comment by zadjii-msft** [comment]
Huh, that's certainly weird. Are you sure you were on 1.9.1942.0 before you updated Edge? It might be possible that the OS took that opportunity to check for updates to the Terminal and update that as well. We often get reports of "the terminal just crashed randomly" a little while after a Terminal update is shipped, when the OS decides to force-update the app. 

Can you look through the Event Viewer to see if there are any logged events for the Terminal?

**Comment by satya-marigold** [comment]
Apologies, but is there a tip for filtering through event viewer for identifying Windows Terminal Logs? I haven't used it before

**Comment by satya-marigold** [comment]
I looked through the errors and I could find a WindowsUpdateClient error that lists > Installation Failure: Windows failed to install the following update with error 0x80073D02: 9N0DX20HK701-Microsoft.WindowsTerminal.

It is a bit troubling that restarting Edge for installing an update triggers an attempt to update the terminal as well.

**Comment by shuffle2** [comment]
Unfortunately this behavior forced me to disable the Store auto-updating apps globally. It's not acceptable to get all content of terminal sessions blown away unexpectedly, ever.

**Comment by zakius** [comment]
> when the OS decides to force-update the app

is there any way to prevent that? cause that's pretty destructive behavior that may cause data loss

well, I guess if I sideload store should leave me alone?

**Comment by zadjii-msft** [comment]
After looking through other threads, we're all pretty sure that this is just a variation on:
* /dup #6726
* /dup #3915
* /dup https://github.com/microsoft/WindowsAppSDK/issues/300
