### ISSUE TITLE
utf-8 is not working in terminal 

### ISSUE THREAD

**Issue by dongleiw** [microsoft/terminal#10818]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

tmux-1.8-4.el7.x86_64

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  9 2019 03:17:15)

### Steps to reproduce

1. create a file with content '# 哈哈'
2. open it with vim out of tmux.  displayed with '# �~S~H�~S~H'
3. open it with vim in tmux. displayed with '# 哈哈'

### Expected Behavior

open file `a` out of tmux . display with '# 哈哈'

### Actual Behavior

open it with vim out of tmux.  displayed with '# �~S~H�~S~H'

**Comment by zadjii-msft** [comment]
Just to be sure, you're running `vim` in WSL, correct? 

Can you do a `hexdump` on the file and share the output, so we can see what the raw bytes are?

**Comment by dongleiw** [comment]
> Just to be sure, you're running `vim` in WSL, correct?
> 
> Can you do a `hexdump` on the file and share the output, so we can see what the raw bytes are?

Yes in WSL2.  It shows correctly If I use virtrualbox instead
hexdump
------------
0000000 2023 93e5 e588 8893 000a
0000009
------------

**Comment by zadjii-msft** [comment]
Thanks for that. Out of curiousity, what do you have `LANG`, `LC_ALL` set to? Does launching tmux with [`tmux -u`](https://askubuntu.com/questions/410048/utf-8-character-not-showing-properly-in-tmux) (after closing all sessions) resolve the issue?
