### ISSUE TITLE
White Spaces in Oh-My-Posh Rendering

### ISSUE THREAD

**Issue by luisfernandomoraes** [microsoft/terminal#10812]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

 oh-my-posh 3.169.2

### Steps to reproduce

![Untitled](https://user-images.githubusercontent.com/10232389/127250845-bb492318-2c11-46d1-80da-b9d8e6405cf0.png)

After installing and configuring oh-my-posh the Windows Terminal shows these white spaces on starting.

### Expected Behavior

No white spaces.

### Actual Behavior

Rendering with white spaces.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #8341 for more discussion.

/dup #8341
