### ISSUE TITLE
Bug Report - Terminal flashes significantly on New Tab and may trigger visual impairments

### ISSUE THREAD

**Issue by shanselman** [microsoft/terminal#1082]
# Environment

```none
Windows build number: 18908.1000
Windows Terminal version (if applicable): 0.1.1502.0
```

# Steps to reproduce

Open a new tab, it flashes and fades

# Expected behavior

Fade is nice ,but a less aggressive flash.

# Actual behavior

See attached zip with VIDEO
[20190531_170117000_iOS.zip](https://github.com/microsoft/terminal/files/3242224/20190531_170117000_iOS.zip)

**Comment by DHowett-MSFT** [comment]
This may have come in with @d-bingham’s background image brush conservation change.

**Comment by DHowett-MSFT** [comment]
I’m yanking the Triage tag on this and marking it Help-Wanted. It’s good and righteous and definitely incorrect the way it is.

**Comment by d-bingham** [comment]
Yep, this was introduced in #853.  Tracking it down.

**Comment by d-bingham** [comment]
The irony is I _wrote_ the background imaging support because the acrylic flash/fade was happening on desktop switches and it annoyed me.
