### ISSUE TITLE
Slow terminal rendering, bad utf support and a few other things.

### ISSUE THREAD

**Issue by Simbaclaws** [microsoft/terminal#10825]
Has anyone at microsoft watched this github page?

https://github.com/cmuratori/refterm

And this guys video?

https://youtu.be/hxM8QmyZXtg

If it is as simple as this guy claims. And he has reference code up on github that shows how to fix these issues.

Then why hasn't anybody taken the time to implement this into the windows terminal project?

Heck, I'd like to give it a go myself if I can find the time.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10462 and #10461 for more discussion.

/dup #10461 
/dup #10462
