### ISSUE TITLE
Azure Cloud Shell after remove will auto add back to the list

### ISSUE THREAD

**Issue by lordzpipo** [microsoft/terminal#10826]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. open `settings.json`
2. comment / remove `Azure cloud shell` block from the list

### Expected Behavior

Azure Cloud Shell should remove without problem

### Actual Behavior

`Azure Cloud Shell` automatic add back to the list

**Comment by peach-lasagna** [comment]
```json
    "disabledProfileSources":
    [
        "Windows.Terminal.Azure"
    ],
``` 
can fix it

**Comment by lordzpipo** [comment]
hi @peach-lasagna , will test it later

thanks for advices

**Comment by zadjii-msft** [comment]
Yep, the azure shell is a [Dynamic Profile](https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles). You'll need to either disable the profile source, or add 

```json
"hidden": true
``` 

to the profile to remove it from the dropdown.
