### ISSUE TITLE
Windows.Terminal.Wsl stopped working in update 1.9.1942.0 ?

### ISSUE THREAD

**Issue by peach-lasagna** [microsoft/terminal#10828]
### Windows Terminal version (or Windows build number)

 1.9.1942.0

### Steps to reproduce

here is my settings.json:
```json
{
  "profiles": {
    "list" : [
        {
            "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl"
        }
    ]
  }
}
```
I went to the terminal this morning and found that the wsl profile was missing from the list. What happened? Yesterday he was on the list

### Expected Behavior

Windows.Terminal.Wsl profile will be displayed

### Actual Behavior

does not appear in the profile list

**Comment by zadjii-msft** [comment]
If you manually start `wsl.exe` outside of the Terminal first, then open the Terminal, does it come back? WSL has a pretty hard time of starting promptly when we want to ask it what distros are installed, and that's lead to a variety of issues like this.

**Comment by peach-lasagna** [comment]
Yes. I solved this problem by rebooting. Sorry, I forgot to close the issue.
