### ISSUE TITLE
Terminal locks itself when pressing TAB after a semicolon

### ISSUE THREAD

**Issue by luigimannoni** [microsoft/terminal#10838]
### Windows Terminal version (or Windows build number)

Windows 10.0.19043.1110, Terminal v1.9.1942.0

### Other Software

- Ubuntu on WSL
- MINGW64 Git Bash

### Steps to reproduce

1. Open a WSL terminal
2. Write `cd;` or `ls;` then press the `tab` on keyboard

1. Open a Windows Git Bash (MINGW64)
2. Write `cd;` or `ls;` then press the `tab` on keyboard

### Expected Behavior

When pressing the tab the shell should display to me all the commands/possibilities:

```
$
Display all 5112 possibilities? (y or n)
```

### Actual Behavior

The terminal hangs itself for an undefined amount of time, sometimes indefinitely when run on WSL. The Windows Git bash suffer the same problem although sometimes it will recover itself.

Hitting CTRL+C won't work

```
$ cd;^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by zadjii-msft** [comment]
Does this repro for you in the vintage console host, i.e. `conhost.exe`?

**Comment by luigimannoni** [comment]
No, only happens with the bash tabs/sessions. If I open a new conhost or powershell tab they work as intended, the tab after the semicolon immediately auto-fills/completes the first folder/file it can find.

Also opening both powershell and cmd.exe/conhost.exe independently won't display this issue.

**Comment by luigimannoni** [comment]
Ok, sorry for the false positive report.

I've just found out that I can open the WSL standalone shell from the installed Ubuntu app and it is showing the same issue there as well, so I think this isn't a problem related with Microsoft Terminal but perhaps with the Bash process itself on Windows.
