### ISSUE TITLE
multi-pane split line in dark mode is too shine

### ISSUE THREAD

**Issue by plainee** [microsoft/terminal#10836]
1、multi-pane split line in dark mode is too shine (white line)
2、The split line is two lines next to each other, perhaps one is more elegant（or not high contrast）.

![image](https://user-images.githubusercontent.com/54027179/127727311-13e6a59d-e191-4ca3-bbf8-afeab8f1495c.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3917 for more discussion.

/dup #3917
