### ISSUE TITLE
Win+V on a linux based console pastes the arrow key presses to get to the clip and not the clip

### ISSUE THREAD

**Issue by dougheeren** [microsoft/terminal#10830]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

Windows Terminal Commit 4b45bb8df1f90e6fc463172cb861bf968e162e77
Built X64, Release
WSL 2 Ubuntu 20.04 4.19.128-microsoft-standard
joe/nano 

### Steps to reproduce

Open a terminal on any WSL 2
Type nano
press enter multiple times
arrow the cursor back to the top of the editor
press win-v
select any clip by arrowing down to it

### Expected Behavior

The clip should be pasted into the editor

### Actual Behavior

The cursor moves down in the editor approximately equal to the number of key presses to get to the clip

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #322 for more discussion.

/dup #322
