### ISSUE TITLE
The development board cannot be opened by the administrator

### ISSUE THREAD

**Issue by Zz-886** [microsoft/terminal#10837]
### Windows Terminal version (or Windows build number)

Win32NT             10.0.22000.0 Microsoft Windows NT 10.0.22000.0

### Steps to reproduce

The stable version has been uninstalled, and the installation of the development board cannot be opened by the administrator
![image](https://user-images.githubusercontent.com/55978588/127739469-b11e1d6c-0ed7-4744-b0f3-c885a93b30e6.png)

### Actual Behavior

Nothing happened

**Comment by skyline75489** [comment]
To help people who speak English: replace “broad” with “version”.
