### ISSUE TITLE
Scroll wheel does not work in Terminal when app "X Button Mouse Control" is running

### ISSUE THREAD

**Issue by koblue** [microsoft/terminal#10831]
### Windows Terminal version (or Windows build number)

any terminal version (prev or release) on Win10 and now Win11 insiders.

### Other Software

X-Button Mouse Control (https://www.highrez.co.uk/downloads/XMouseButtonControl.htm)

### Steps to reproduce

I use this app to re-map 2 buttons on my oddball mouse as "wheel up" and "wheel down".

When running, neither these buttons or the actual scrollwheel work in Terminal.

When I close it, it instantly works again. 

Yes, I understand this is likely an XB-MC issue, but every other app works except terminal.  

### Expected Behavior

Mouse scroll wheel to work as normal. 

### Actual Behavior

No scrolling, either by remapped buttons or physical wheel.

**Comment by zadjii-msft** [comment]
I would guess that this is a problem with any applications that use XAML Islands. IIRC, the [PowerToys](https://github.com/microsoft/PowerToys) settings app is also using XAML Islands, could you check if scrolling works in that?

**Comment by koblue** [comment]
Update: Resolved

Cause: "Make scroll wheel scroll window under cursor" feature in XMBC was enabled - my guess is that this clashed with Windows own implementation of this feature. 

@zadjii-msft any UWP or modern application was affected, including PowerToys and all now work as expected when this setting is turned off in XMBC

Bonus Derp: the application is "X-Mouse Button Control" not "X-Button Mouse Control" >_<
