### ISSUE TITLE
Selection doesn't update when cursor moves outside window

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#1083]
## Environment
Windows build number: 10.0.18362.145

## Steps to reproduce
While selecting e.g. first line, move cursor outside terminal window (or even client area).
## Expected behavior
Selection should stiil be responding to cursor movement. This is how it works on conhost.
## Actual behavior
Selection 'freezes' when cursor moves outside window.

This seems quite obviuos but I couldn't find issue describing it so sorry if it's dupe.

**Comment by miniksa** [comment]
It's quite probable we're not doing `[SetCapture](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setcapture)` like we do in conhost.exe...

**Comment by mcpiroman** [comment]
Resolved by #1248
