### ISSUE TITLE
error: bad fsmonitor version 2

### ISSUE THREAD

**Issue by RatakondalaArun** [microsoft/terminal#10839]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Git
WT Git Bash(Profile)

### Steps to reproduce

Occurs every time I open a terminal in git repo

### Actual Behavior

Some git commands does not work(`git log`, `git branch`)

**Comment by zadjii-msft** [comment]
Does this repro in a vintage console window (`conhost.exe`)? If so, then I'm guessing that this is more of an underlying issue that would be better off reported at https://github.com/microsoft/WSL

**Comment by DHowett** [comment]
I believe that this isn't a WSL issue but a git issue or a Cygwin/MSYS2 Runtime issue. Support for fsmonitor 2 was added in https://github.com/git/git/commit/8da2c57629a16e148b0f94282ac787c1503e4779, which looks like it shipped in Git v2.26.

What version of Git are you running?

**Comment by RatakondalaArun** [comment]
```bash
$ git --version
git version 2.32.0.windows.2
```

**Comment by jadiaz** [comment]
I've noticed this only happens on my end when a PowerShell tab is open. When I close the powershell tab and use git in bash no error is generated.

**Comment by matthargett** [comment]
I'm also hitting this. I have no powershell open, just WSL2. I *do* have Git Bash installed, but that hasn't changed in months.
in WSL2 Ubuntu 20.04:
```
matt@Surface2:/mnt/c/Users/matt/src/roact-alignment$ git --version
git version 2.25.1
```

in cmd:
```
C:\Users\matt>git --version
git version 2.33.0.windows.1
```

**Comment by matthargett** [comment]
I think I figured it out. VS Code seems to be running the git in win32 `PATH`, which starts up an LFS server (or something). When the WSL2 `/usr/bin/git`  runs, it seems to try to connect to the win32 git's LFS server instance. since my win32 git revision is 2.33 and the wsl2 linux version is 2.25, there seems to be a protocol incompatibility of some kind.

my solution was to update the wsl2 git by using the Ubuntu PPA listed here:
https://git-scm.com/download/linux

now that both the wsl2 and win32 git versions are aligned, no more error messages.

**Comment by RatakondalaArun** [comment]
And some commands aren't working

https://user-images.githubusercontent.com/47482264/134451926-4b5b6bb9-1ade-49a4-9c2c-f0f511f3d5f5.mp4

**Comment by zadjii-msft** [comment]
@RatakondalaArun that looks like a totally different issue than the one that you originally opened this thread for. Do git bash commands work outside the Windows Terminal (i.e. in a `conhost.exe` window)? If @matthargett's suggestion fixes the fsmonitor issues, then we should probably close this and open a new issue to track the new problem.

**Comment by RatakondalaArun** [comment]
@zadjii-msft Yes git bash commands work outside **wt**. I tested them on `git bash` and `cmd`
It looks like this only effects _git bash_ profile in **wt**. All other profiles work fine with git commands

**Comment by RatakondalaArun** [comment]
![image](https://user-images.githubusercontent.com/47482264/135756788-2f488753-98e6-46fa-a694-bd474286eed4.png)
This thing still pops up in `windows terminal@v1.10.2383.0` and `git@v2.17.1`

**Comment by DimasInchidi** [comment]
> I think I figured it out. VS Code seems to be running the git in win32 `PATH`, which starts up an LFS server (or something). When the WSL2 `/usr/bin/git` runs, it seems to try to connect to the win32 git's LFS server instance. since my win32 git revision is 2.33 and the wsl2 linux version is 2.25, there seems to be a protocol incompatibility of some kind.
> 
> my solution was to update the wsl2 git by using the Ubuntu PPA listed here: https://git-scm.com/download/linux
> 
> now that both the wsl2 and win32 git versions are aligned, no more error messages.

got the same issue and fixed with this also. thanks @matthargett

**Comment by zadjii-msft** [comment]
@RatakondalaArun You ever figure this out/? Was it the LFS server as mentioned in: https://github.com/microsoft/terminal/issues/10839#issuecomment-925467068?

I firmly suspect this is just a `git` issue (perhaps complicated by a different PATH when running in the Terminal vs conhost), but I'm not sure where the right repo to move this discussion to.

**Comment by RatakondalaArun** [comment]
@zadjii-msft As you mentioned it must have been a git issue. I updated wt to `v1.14.2282.0` and everything works fine now.
