### ISSUE TITLE
Add "Ambiguous-width character <Narrow|Wide>" Setting

### ISSUE THREAD

**Issue by omar2205** [microsoft/terminal#10844]
# Description of the new feature/enhancement
Add an Ambiguous-width character setting which can be set to either narrow or wide.

A problem with the width of characters causes tmux to keep inserting newlines. It doesn't affect the gnome-terminal.

![image](https://user-images.githubusercontent.com/1373867/127786011-c024e525-2d24-4888-9fa1-0f9cc27bea2a.png)
_note: the emoji next to 27 is a hack_

# Proposed technical implementation details (optional)
In the settings, there should be an option to how to treat ambiguous width characters.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #153 for more discussion.

/dup #153
