### ISSUE TITLE
Quake mode visible in Alt+Tab

### ISSUE THREAD

**Issue by d0rf3n** [microsoft/terminal#10845]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Steps to reproduce

1. Open Quake window.
2. Alt+Tab.
3. Quake window is visible among other windows.

### Expected Behavior

Accoring to this: https://docs.microsoft.com/en-us/windows/terminal/tips-and-tricks#quake-mode

Quake mode: "The window will be hidden from the taskbar and from Alt+Tab."

### Actual Behavior

Quake window is visible among other windows.

Same on Win10 and Win11.

**Comment by zadjii-msft** [comment]
Sorry, that should more correctly read 

> "**When minimized**, the window will be hidden from the taskbar and from Alt+Tab."


When the window is open, it's definitely still going to appear in alt+tab - not sure there's any way to disable that behavior.

**Comment by zadjii-msft** [comment]
#10197 may also be related

**Comment by zadjii-msft** [comment]
Closed in https://github.com/MicrosoftDocs/terminal/pull/454

**Comment by zakius** [comment]
> When the window is open, it's definitely still going to appear in alt+tab - not sure there's any way to disable that behavior.

I'm using ` WinSet, ExStyle, % +0x80` in AHK to achieve that and it seems to not have any side effects
