### ISSUE TITLE
Titlebar loses modern styling for min/max/close buttons after Terminal has been open for a while

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/terminal#1085]
# Environment

```none
Windows build number: 1903 18362.145
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

I've noticed this after I've had Terminal open for days across several sleep/restore cycles.  Otherwise, not sure how to repro it.

# Expected behavior

Modern styling should not go away.

# Actual behavior

Modern style does go away for part of the titlebar:

![image](https://user-images.githubusercontent.com/5177512/58732267-3ea41680-83ae-11e9-8b52-075316e2f824.png)

**Comment by zadjii-msft** [comment]
Well that's insane. If we could get more minimal repro steps, that'd certainly be helpful. Maybe there's some rogue window message that we're not handling correctly.

**Comment by rkeithhill** [comment]
It seems to happen after the app has run for a few days.  If I maximize and restore the app, the original (modern) titlebar buttons re-appear.

**Comment by DHowett-MSFT** [comment]
@rkeithhill hey, what sort of monitor do you have connected? DisplayPort? HDMI? Let's get some confirmation bias up in here. :smile:

**Comment by rkeithhill** [comment]
It's an old monitor - uses DVI.

**Comment by dkter** [comment]
Could be a [soft error](https://en.wikipedia.org/wiki/Soft_error)?

**Comment by DHowett-MSFT** [comment]
I believe @bitcrazed has an answer for this one.

**Comment by DHowett-MSFT** [comment]
I _believed_ that @bitcrazed had an answer for this one 8 days ago. Now, I just think it'll be either helped or harmed by #872 #929. I'm going to close this and cross my fingers?
Thanks for the report.
