### ISSUE TITLE
Guidance using visual studio 2019 preview

### ISSUE THREAD

**Issue by jainthedestroyer** [microsoft/terminal#1086]
While opening the openConsole.sln in visual studio 2019 preview it automatically prompts to use 
Window SDK 10.0.17763.0 version instead of 10.0.18362.0 ...
Help me with that....

**Comment by DHowett-MSFT** [comment]
This doesn't seem like a problem? You will have to compile the project with the 17763 SDK. #587 #565.

**Comment by stagedataloss1** [comment]
test123

**Comment by DHowett-MSFT** [comment]
@stagedataloss1 why are you posting “test” and “hello world” issues and comments? We can hear you :smile:

**Comment by jainthedestroyer** [comment]
With 10.0.17763.0 version the build fails every time...

**Comment by stagedataloss1** [comment]
test123HelloWorld
