### ISSUE TITLE
Missing "Default terminal application" option

### ISSUE THREAD

**Issue by GHKazza** [microsoft/terminal#10869]
### Windows Terminal version (or Windows build number)

10.0.19043.1151, 1.10.1933.0

### Steps to reproduce

Missing "**Default terminal application**" option in **CMD** and **Windows Terminal (1.9.1942.0)** and **Windows Terminal Preview (1.10.1933.0)**, I can't change the default terminal.

Operative System: **Windows 10 Pro**
Version: **21H1** 
Build: **19043.1151**

### Expected Behavior

(Screenshots from Google)

![image](https://user-images.githubusercontent.com/45432294/128135903-6a23cda4-7f50-4441-bd72-cbe80652f77b.png)

![image](https://user-images.githubusercontent.com/45432294/128135960-05c947ee-ba19-48cf-bd45-f6b41ba8bf55.png)

### Actual Behavior

(Screenshots from my PC)

![image](https://user-images.githubusercontent.com/45432294/128136103-1acfff66-32a0-45c3-b70c-e02266e71382.png)

![image](https://user-images.githubusercontent.com/45432294/128136159-85422386-cd58-4e28-8f3e-c92ba75210e6.png)

**Comment by DHowett** [comment]
This feature is not supported on 21H1. Sorry!

**Comment by zcysxy** [comment]
> This feature is not supported on 21H1. Sorry!

@DHowett May I ask what versions on which this feature is supported? newer or older?

BTW @GHKazza may I ask how you get such fantastic UI that makes the properties window black? (I'll delete this line as soon as I get the answer or it's too off-topic, sorry!)

**Comment by DHowett** [comment]
> > This feature is not supported on 21H1. Sorry!
> 
> 
> 
> @DHowett May I ask what versions on which this feature is supported? newer or older?
> 

So far, just Windows 11. Stay tuned. :)

**Comment by GHKazza** [comment]
> BTW @GHKazza may I ask how you get such fantastic UI that makes the properties window black?

Hi @zcysxy

I'm using **[this theme from DeviantArt](https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521)** with **[UltraUXThemePatcher](https://mhoefs.eu/software_uxtheme.php?lang=en)** (without the icons and without the taskbar seen in the image, only the colors)

![image](https://user-images.githubusercontent.com/45432294/130368472-c559145d-d1dc-4d23-825f-6fc180cc9d8c.png)

First you need to **download and install** **[UltraUXThemePatcher](https://mhoefs.eu/software_uxtheme.php?lang=en)** (When you finish, you must first restart your computer)
![image](https://user-images.githubusercontent.com/45432294/130369180-9210af8c-2f4c-4bf6-9df0-899b22fab605.png)

Now you **[download](https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521)** the **.zip** file from this button: 
![1](https://user-images.githubusercontent.com/45432294/130368640-2e44ad6c-1ba9-4b99-bf6c-4603ed00008f.png)

You are going to **extract it** and you will see these folders:
![image](https://user-images.githubusercontent.com/45432294/130368677-8fb77781-df51-4d18-952b-3480ba09e2e2.png)

Enter the folder "**Windows 10 Themes**" and you will **copy** the content in "**C:\Windows\Resources\Themes**" (I only use the "**Dracula 2**" theme which is the one you saw in my screenshot of the **CMD properties**)
![image](https://user-images.githubusercontent.com/45432294/130368830-720c7e06-8be6-4841-9297-8eaeedbc6d6a.png)

Then go to the **Personalization > Themes** options in **Windows Settings** and select any theme you want (You can delete the theme files that you are not going to use, remember that they are located in "**C:\Windows\Resources\Themes**")

That's it 👌

**Comment by zcysxy** [comment]
@DHowett Thanks for the info!

@GHKazza Thank you so much for the detailed reply too!

**Comment by creed-us** [comment]
Is this feature planned to come to Windows 10?

**Comment by zadjii-msft** [comment]
> Is this feature planned to come to Windows 10?

Nope. I understand the desire, but unfortunately we can't really "service" this fairly large feature set as a "bugfix" to earlier Windows versions.

**Comment by viktor-svub** [comment]
Actively reducing features of Win10 Pro version does _not_ get you more Win11 adoption, it gets you _loss of trust_.

**Comment by DHowett** [comment]
> Actively reducing features of Win10 Pro version does _not_ get you more Win11 adoption, it gets you _loss of trust_. 

What? We added a new feature during the Windows 11 development cycle. We didn't put it in Windows 10 and then _take it away from you._

By default, in almost all software shops, features get put into the upcoming version. If you're upset that we didn't finish Default Terminal support in 2019 (which is when the operating system that Windows 10 21H2 is based on was completed), then I don't know what to tell you. Sorry.

We're actively doing the paperwork required to get this feature backported to Windows 10, because we think that it's a good, necessary and important thing for Windows 10 users to have. But let me be clear: we didn't take it away from you in the past so that we could swoop in and save you from a problem of our own creation next year.

**Comment by viktor-svub** [comment]
I'm sorry if it came out offensive, but customers/users neither exactly know or care for multiple-year development cycles, nor should they. 

As a matter of fact, the feature _was_ accessible and usable well enough as preview in Win10, and it's not accessible in more recent version (from consumers point of view) hence, the additional value seems to have been removed. 

This is the first answer in this case which even hints at the possibility of Win10 "backport" - again, of a fully working feature, from customers point of view.

As for my personal take on the reasoning - while I know Microsoft is big and parts may not be interacting at all, considering the recent pushes towards non-reassignable default browser and protocol handlers, and ongoing debates of Win10 updates/supportability, it sure looks suspicious to an outsider.

**Comment by zadjii-msft** [comment]
> As a matter of fact, the feature was accessible and usable well enough as preview in Win10

Pretty confident that the OS half of this work was never in any Windows 10 builds. That landed earlier this year, when we were far past the Windows 11 fork... 🤔

**Comment by viktor-svub** [comment]
I may be confused/mistaken after playing with one too many configurations, but as far I know, this worked in the past (but I have no record of the exact previews/versions to repro it), which is not the case nowadays https://pureinfotech.com/set-windows-terminal-default-app-command-prompt-powershell/

**Comment by piomis** [comment]
By my knowledge it is possible also in Windows 10  but unfortunately not the one from main channel but only in Windows 10 Preview build 21390.
So looks that there are no technical obstacles which would limit availability of that feature only to Windows 11.

**Comment by DHowett** [comment]
Truthfully, _this is available in Windows 10 with build numbers >= 21390¹_. The problem with insider builds is that they don't always represent what's going to be shipped as the final product². To give Terminal support as a solid example: we developed it in a branch of Windows that was _already Windows 11_, it's just that the Windows 11 branding wasn't turned on yet.

At the end of the day: this is a feature that was developed on a development version of Windows, which Microsoft allows users to access, that has not been released with Windows 10 branding.

It's not my team's purview which builds of Windows receive which branding. If we want to ship to what they're calling "Windows 10," we need to get their approval to backport Default Terminal support from build 21390 to build 19043³. If we didn't care about users on Windows 10, we would not be pursuing that approval.

¹ The only available Windows 10 builds with a build number greater than anything in the `19000` range are insider builds.
² The insider program states that the product "may be substantially different from released versions."
³ This is the currently-shipping version of Windows 10.

**Comment by piomis** [comment]
@DHowett thank you for detailed explanation.
Hope that pursuit will end up with success - I totally agree that this is very useful also for Win10 users (especially that corps do not tend to adopt new OS versions very quick).
Do you by chance know any timeframe for at least approval response?

Looking forward to see it done ;)

**Comment by viktor-svub** [comment]
@DHowett Thanks for the thorough answers, especially given to an annoyed user like myself. 

I understand the logic and issues of preview features & early forks, and the management decisions involved in that -- it still "looks and feels" wrong to the users having a usable feature at hand, and losing it in "visually more recent" version of what seems to be the same product. 

And thanks for any effort involved in "backporting" this to the "real" Windows 10, regardless of its success :)

**Comment by jasoncollege24** [comment]
I know this is an old issue, but I'd like to chime in saying that I too agree that this feature should be added to Windows 10, and any push in that direction is much appreciated. Us Windows 10 users shouldn't be left behind, just because we don't much like the new Windows 11.

**Comment by ItsSunnyMonster** [comment]
Or because our PCs does not meet the minimum, to that matter

**Comment by Archie-2021** [comment]
Please make this available in Windows 10. It is really annoying.

**Comment by nhantr** [comment]
> This feature is not supported on 21H1. Sorry!

oh f*ck your bitch, who said that is on 21390 and now ??

**Comment by chuacw** [comment]
[You can use App Paths to make Windows Terminal launch when you run cmd.exe on Windows 10 / Server 2022].(https://chuacw.ath.cx/development/b/chuacw/archive/2022/11/17/how-to-make-windows-terminal-the-default-terminal-on-windows-10-2022.aspx)

**Comment by zadjii-msft** [comment]
Was a feature on _a Windows 10 **Insiders** build, a build which later became a Windows 11 build_. The Win10 Insiders -> Win11 transition was a little messy, admittedly. But it was definitely only committed to the OS _after_ the Windows 11 fork had already started.

**Comment by bingzhangdai** [comment]
This wasn't the first time Microsoft removed the already implemented feature based on their business plan.

**Comment by DHowett** [comment]
Speaking authoritatively...

This is the workitem we were using internally to track actually implementing "default terminal."

<img width="505" alt="image" src="https://user-images.githubusercontent.com/189190/211111505-d0dd3bda-cd54-456e-9bd6-a0a1cb84ebb1.png">

The _absolute earliest build_ in which this task is available is **number 21348**.

The Windows builds released to the insider channel around that era were eventually released as Windows 11.
To rephrase: the feature was fully functional on a version of Windows that was released to the Insider channel that was eventually branded as Windows 11.

The Terminal team has no control over the branding and release cycle decisions made by Windows. I'm sorry.
