### ISSUE TITLE
Cursor position is lost when resizing the window horizontally

### ISSUE THREAD

**Issue by daanx** [microsoft/terminal#10868]
### Windows Terminal version (or Windows build number)

10.0.19042.1110 (windows terminal 1.9.1942.0)

### Steps to reproduce

When the windows is horizontally resized the cursor position is lost; on the narrowing the cursor wraps to the next line, but on widening again the cursor goes incorrectly to the _start_ of the previous line. 
(Extra heisenbug: if you quickly resize narrow again the cursor will go randomly in the text :-)

To reproduce run the following batch file: 
```bat
@echo off
set /p "ANSWER=prompt prompt prompt prompt prompt prompt prompt>"
```

### Expected Behavior

On the old cmd terminal the batch file works as intended.

### Actual Behavior

Here is what happens in Windows terminal (I colored the cursor in red):

![cursor-bug](https://user-images.githubusercontent.com/2171100/128130465-6b28c428-d9ee-4172-87c2-be9ba8f183ce.png)

**Comment by daanx** [comment]
perhaps this is related to the earlier bug I filed #10848 ?

**Comment by zadjii-msft** [comment]
This probably is closely related, maybe even the same root cause, but I like having lots of test cases, and these are great repro steps. Thanks!

**Comment by lhecker** [comment]
I'm trying to reproduce this bug to test if #15701 fixed it but couldn't do manage to reproduce it. Does this bug still happen in 1.17/1.18?
