### ISSUE TITLE
mouse input not working in the terminal

### ISSUE THREAD

**Issue by KavyanshJain** [microsoft/terminal#10860]
Hey! there is a problem in my terminal, mouse response it not working cannot select or change any settings because mouse input is not working and but I can use keyboard of the work.
But after some try I come to know that mouse input responses on the right side of the windows terminal only
Cannot able to resolve it

![image](https://user-images.githubusercontent.com/69588134/127966381-b0ba8788-4e1f-43d4-be60-83bd04a1ce9a.png)

And at the time of editing this screenshot I came to know that snip & sketch mouse input is also only working in right side please help

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2606 for more discussion.

/dup #2606
