### ISSUE TITLE
A toggle button on main UI to set acrylic opacity to on and off.

### ISSUE THREAD

**Issue by priyanshu-shubham** [microsoft/terminal#10862]
# Description of the new feature/enhancement
When using terminal over an app, if acrylic opacity is turned on, many a times this happens that the background color matches the font color of terminal which in turn makes the font unreadable. So if possible, we can have a quick toggle on the left side of minimize button that will toggle the acrylic opacity from true to false or vice versa. This will help in the above issue.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2531 for more discussion.

/dup #2531
