### ISSUE TITLE
Default bold color is no longer working as expected

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#10866]
### Windows Terminal version (or Windows build number)

Commit e7108332f72a3c14c72a65484d091c4e79ab28b2

### Steps to reproduce

1. Build a recent version of the code.
2. Open a bash shell.
3. Set the color scheme to _Campbell_.
4. Execute ```printf "\e[mNORMAL \e[1mBOLD\n"```

### Expected Behavior

I'd expect the bold text to be displayed in bright white. This is the way is used to work.

![image](https://user-images.githubusercontent.com/4181424/128100958-6d42c29f-cf19-4df5-86fc-6da50e2c2f41.png)

### Actual Behavior

The bold text is now displayed in bright yellow.

![image](https://user-images.githubusercontent.com/4181424/128100979-bc075954-8d22-4262-b5c6-65f6af3bc17c.png)

I think this was caused by PR #10779, because if I switch back to the old loop version of the code it fixes the issue.

**Comment by j4james** [comment]
I should add that my build is using the `_M_AMD64` branch of the vectorized code in case that's relevant.

**Comment by DHowett** [comment]
@lhecker all yours!
