### ISSUE TITLE
comand prompt does not open !?!?

### ISSUE THREAD

**Issue by marioegghead2** [microsoft/terminal#10879]
### Windows Terminal version (or Windows build number)

idk

### Steps to reproduce

ok i started using win+x
and suddenly I received this error from command prompt:

This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default apps Settings page.

### Expected Behavior

![Screenshot (3)](https://user-images.githubusercontent.com/82485570/128303505-ac5a62fa-4990-49e2-9436-c7afa2e4f92c.png)
thats the error from command prompt

### Actual Behavior

idk

**Comment by DHowett** [comment]
You closed this issue; did you resolve your issue?
