### ISSUE TITLE
ResourceUnavailable: Program 'wt.exe' failed to run. When using "over the shoulder elevation" admin account.

### ISSUE THREAD

**Issue by geek2point0** [microsoft/terminal#10873]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. Login to Windows with user account
2. Open Windows PowerShell or PowerShell using "Run as Different User"
3. Login with admin account
4. Run "wt.exe"

### Expected Behavior

Windows Terminal should open under same account running PowerShell or Windows PowerShell.

### Actual Behavior

![881imeYy98](https://user-images.githubusercontent.com/5618739/128232739-a6b6800d-76d5-4a4b-8d18-023fd85f7129.png)

**Comment by geek2point0** [comment]
Also created a Feedback Hub report. https://aka.ms/AAdc35g

**Comment by zadjii-msft** [comment]
Is the Terminal installed for this other user you're running powershell as? And what version of Windows are you on?

**Comment by geek2point0** [comment]
@zadjii-msft I'm sorry I should have included that. I have Terminal installed for both accounts. I'm on Windows 10 Enterprise. Version 20H2.

**Comment by zadjii-msft** [comment]
You know, this probably just falls under the bucket of /dup #4217
