### ISSUE TITLE
Quake Mode - Always Available

### ISSUE THREAD

**Issue by liamfoneill** [microsoft/terminal#10872]
How can I configure Terminal so that I can launch quake mode no matter what? Currently the only way I can do it is by configuring Windows Terminal to run at startup and then I need to launch Quake mode once (this creates the little Windows Terminal sys tray icon). Once I have launched Quake Mode once I can then close Quake mode and the Windows terminal window that was created on startup and because the system tray icon persists Quake mode can then be launched anytime.

Surely, it isn't supposed to work like this? I just want the system tray icon to load at startup so I can launch quake mode anytime. I do not want an actual Windows Terminal window to be open when I boot windows - just the tray icon.

I am missing something here?

**Comment by Michaelvsk** [comment]
There is a pretty nice workaround to get it working until there is native support:

1. Create a new shortcut inside ` %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`
2. Set its target to `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe -w _quake`
3. Set that the launched program should start minimized:
![image](https://user-images.githubusercontent.com/13169777/138091631-93a7f4b0-e4bc-4322-81c8-2ee872a424d5.png)

**Comment by Michaelvsk** [comment]
@mmelnic
I noticed this behavior recently, too but depends on the screen size. Some code change must have caused it. 
On my 5120x1440 screen at home I do only get the very small window at  top left corner. At work, on a 2560x1440 screen it is working as expected.
I tried to delay the execution of the command by using Task Scheduler but that didn't fix it.
For now I switched back to open the quake console non-minimized. :(

**Comment by oameye** [comment]
I had the same problem with the very small window at top left corner. What solved it for me is setting the target of the shortcut to `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` instead of `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe -w _quake`. In that way it will open a terminal and quak mode, however, both are minimized.

**Comment by brad-jones** [comment]
Cool side effect this keeps my WSL instance running all day :)

**Comment by eggbean** [comment]
Nice thanks. I have got a command which will automate it for setup scripts. You need [NirCmd](https://www.nirsoft.net/utils/nircmd.html) in your `%PATH%`. I use scoop to install it.

    nircmd shortcut "%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup" "Quake Terminal" "-w _quake" "%USERPROFILE%\winfiles\icons\app_icon
s\terminal.ico"

The last part is a path to the icon you want to use or just replace it with `""` for a blank icon. You can also add `"" min` at the end if you want it to start minimised.

    nircmd shortcut "%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup" "Quake Terminal" "-w _quake" "%USERPROFILE%\winfiles\icons\app_icon
s\terminal.ico" "" min

**Comment by jerrygreen** [comment]
I love the startup hack to make it available right away from windows start. Thanks for sharing the hack!

Although, I sometimes need to close the connection <kbd>Ctrl+D</kbd>, which closes the program, and then this Quake Mode hotkey doesn't work anymore, – until I manually start Terminal again.

That's a little inconvenient. «Just don't disconnect» isn't really a solution. I need that sometimes. But I want Quake Mode hotkey to always work, and if there's no current connection, so it creates one.

Is there a fix for that?
