### ISSUE TITLE
Inconsistent handling of built-in color schemes

### ISSUE THREAD

**Issue by mrjoel** [microsoft/terminal#10888]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

* Edit a built-in color scheme through the UI
* Save settings

### Expected Behavior

I would expect that built-in color schemes are protected/invariant/read-only. Further, I store my settings.json in a dotfiles git repo and the built-in color schemes are a) just fine for my needs, but b) amount to nothing but litter in the config file.

In my mind, ideally the following changes would address this apparent inconsistency.
* Don't save the built-in color schemes to settings.json (they're built-in, why pollute the user config file?)
* Don't allow editing of a built-in color scheme.
* Provide an option to save a copy of a built-in (or any) color scheme as a different user name.

At the very least an option should be provided to revert a modified built-in color scheme back to the built-in defaults (i.e. reset to match the original), but that seems odd because all of the potential time using a derivative built-in.

### Actual Behavior

The color scheme settings UI section indicates that "This color scheme cannot be deleted or renamed because it is included by default.". However the schemes are saved out to the settings.json, and editing of the scheme is allowed. However once a built-in color scheme is edited, it a) doesn't match the expected colors and yet still proclaims the same built-in name, and b) there is no way to reset the color scheme to the originals expect removing the named color scheme from the array in settings.json.

**Comment by zadjii-msft** [comment]
Okay after re-reading this, I actually think this is just going to get fixed by #8100. I know it doesn't _sound_ like it, but with 8100, we won't need to keep reserializing builtin schemes back out. Sorry for the delay getting back here!

/dup #8100
