### ISSUE TITLE
Retain existing comments in JSON

### ISSUE THREAD

**Issue by mrjoel** [microsoft/terminal#10889]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

* Run Windows Terminal using an existing settings.json with `//` line comments
* Open Settings UI and save (without changing anything)
* Note that the settings.json line comments are removed

### Expected Behavior

I expect that existing comments are retained. The parsing clearly supports them, and defaults.json includes several comments as well. As noted in #9861, comments are (were?) intentionally retained at least in the `actions` array as part of migration. I'd expect them to be retained always.

If the plan is to deprecate comments, then a preferable alternative would be to support a `settings.yaml` in order to retain comments in an official syntax manner.

### Actual Behavior

All `//` line comments are stripped when rewriting settings.json

**Comment by j4james** [comment]
I believe this will be covered by #8991. See also #9167.

**Comment by zadjii-msft** [comment]
Yea, this is gonna be covered by /dup #8991. Thanks!
