### ISSUE TITLE
When Terminal has focus, shift+drag on title bar does not trigger FancyZones

### ISSUE THREAD

**Issue by jdmarch** [microsoft/terminal#10880]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

PowerToys 0.43.0

### Steps to reproduce

On a laptop+monitor setup using virtual desktops.
With FancyZones defined for a desktop.

1) Give the Terminal window focus (by opening it, or click or Alt+Tab on existing Terminal window)

2) Shift+Left-click+drag on Terminal title.  FancyZone borders / highlighted regions do not appear on screen as expected. Window does not move during drag as would be expected with NO shift modifier, but when drag is released, Terminal window moves to new position as if shift had not been pressed (i.e. normal window drag).

3) Same attempt (shift+drag to FancyZone) on any other (non-Terminal) window. This window snaps to FancyZone as expected.

4) Same attempt on Terminal window (which no longer has focus). This time, snaps to FancyZone as expected.

5) Without losing Terminal focus, try again. Fails again.

6) Give focus to any non-Terminal window. 

7) Without giving Terminal focus, try again on Terminal. Succeeds.

### Expected Behavior

Show FancyZone during shift+drag, snap to FancyZone on drag release.

### Actual Behavior

Terminal window  is unresponsive during shift+drag, moves on drag [release.](url)

**Comment by zadjii-msft** [comment]
~~This is a dupe of #2905, which is actually a dupe of microsoft/PowerToys#209.~~



WAIT but that was fixed in 2019. So this must be some new regression. I'd follow up with PowerToys on their repo: https://github.com/microsoft/PowerToys/issues

**Comment by jdmarch** [comment]
Thanks @zadjii-msft -- While that was indeed fixed / closed, there were subsequent reports on that issue, which were referred to https://github.com/microsoft/PowerToys/issues/1466, which was labeled as `Resolution-External`. So `¯\_(ツ)_/¯`

**Comment by zadjii-msft** [comment]
@crutkas can we get more context on this from the PowerToys side? I thought y'all took a fix for PT for the Terminal, but both microsoft/PowerToys#1466 and microsoft/PowerToys#209 are just kind of black hole issues right now, without any real guidance on why the Terminal doesn't work in this case. Is this a XAML Islands thing?

I'd rather get to the root cause of the issue (even if it's unsolvable) than just [spiderman.png](https://i.kym-cdn.com/entries/icons/original/000/023/397/C-658VsXoAo3ovC.jpg) all day.

**Comment by crutkas** [comment]
@zadjii-msft Ive gone into depth how to recreate the issue without FZ/ PT even installed in other bugs here. We amplify the issue since the behavior required for FZ. 

Best of my knowledge we did not do a fix for it. I'd sync internal as I'm OOF until September 1 also.

**Comment by xg5-simon** [comment]
Exact same behavior still happening on v0.92.1

**Comment by SeaRedm** [comment]
Still an issue on the latest version for me also / windows 11 enterprise Release v0.96.1 / powershell 7
