### ISSUE TITLE
Window in Quake mode does not fit width of external display

### ISSUE THREAD

**Issue by inoyakaigor** [microsoft/terminal#10881]
### Windows Terminal version (or Windows build number)

Win 10.0.19043.1110, Terminal 1.9.1942.0

### Steps to reproduce

I have laptop with HiDPI display (1920*1080, 150% scale factor in Win settings) and external display (1920*1080, 100% scale factor and main display in Win settings)

When I open terminal in Quakemode on external display it fit ~66% of width

![image](https://user-images.githubusercontent.com/1235286/128351009-57b67e0c-930a-4a31-b2ad-61ac01c8fe85.png)

### Expected Behavior

I expect terminal will fit full width of display

### Actual Behavior

Terminal does not fit full width

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10182 for more discussion.

/dup #10182
