### ISSUE TITLE
Batch files end up picking up incorrect window sizes

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/terminal#10892]
### Windows Terminal version (or Windows build number)

10.0.22000.0, 1.10.1933.0

### Other Software

Not sure if related, but I am running latest Windows 11 Dev build as of this post

### Steps to reproduce

Launch a .bat script while Terminal is snapped to the side of a monitor

### Expected Behavior

New tabs related to batch files are given and respect the correct length of the window and text and scrolling works as expected

### Actual Behavior

New tab will fail to have the correct length reported to the batch script, causing any input to be cut off seemingly around the size of a normal unsnapped window. Unsnapping the window or otherwise manipulating the size of the window in any way other than maximizing or minimizing the window seems to have the correct size finally reported and honored

**Comment by zadjii-msft** [comment]
This sounds a lot like the symptoms of #9811, which should be fixed in #10772. I don't _think_ this needs an OS update to get the fix, so I think this will be fixed in 1.11. /cc @miniksa to confirm what I've said here.

**Comment by Masamune3210** [comment]
Sorry, tried searching first but must of just not been up on my search-fu

**Comment by zadjii-msft** [comment]
No worries, this is the kind of issue you'd need to know existed to be able to find 😄
