### ISSUE TITLE
Thread starving?

### ISSUE THREAD

**Issue by were** [microsoft/terminal#10898]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

WSL or SSH. Run on Linux. I did not try to replicate it on pure PowerShell but I think it should be very similar.

### Steps to reproduce

Writing a code that dumps excessive logs to `stdout`.

```C
int main() {
  while (true) {
    std::cout << "Hellow world" << std::endl;
  }
}
```

### Expected Behavior

If I type `Ctrl-C`, it should stop immediately.

### Actual Behavior

If need to type `Ctrl-C` repeatedly until it stops. It seems the thread that listens the keyboard signal is starving.
This issue is not happening in PowerShell terminal (I mean just run PowerShell from Start menu, not from Windows Terminal tab).

**Comment by j4james** [comment]
I think this might be related to issue #2141.

**Comment by zadjii-msft** [comment]
#2141 might be the root cause, but at the very least this is definitely a /dup of #6258. Thanks!
