### ISSUE TITLE
Progress indicator in tab not working properly

### ISSUE THREAD

**Issue by xlm13x** [microsoft/terminal#10900]
The progress indicator in the tab's title bar is not rendering properly. It always draws half indicator.
![image](https://user-images.githubusercontent.com/1693053/128666300-4de8af3e-a612-4125-bfa6-bd5514c20633.png)
![image](https://user-images.githubusercontent.com/1693053/128666322-83a2c177-234f-4e02-a2ef-b2021e908d79.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8910 for more discussion.

/dup #8910
