### ISSUE TITLE
process exited with code 255

### ISSUE THREAD

**Issue by wengm** [microsoft/terminal#10903]
### Windows Terminal version (or Windows build number)

10.0.18363, 1.9.1942.0

### Other Software

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

### Steps to reproduce

SSH to remote host
No action to SSH session for 10 mins or longer

### Expected Behavior

SSH session is alive

### Actual Behavior

[process exited with code 255]

**Comment by zadjii-msft** [comment]
`[process exited with code {whatever}]` is just the message that the Terminal prints when the client application closes unexpectedly. In this case, `ssh.exe` is closing with an exit code of 255.

Sounds like you can configure `ssh` to have a different timeout:

https://superuser.com/questions/699676/how-to-prevent-ssh-from-disconnecting-if-its-been-idle-for-a-while

Or you can just configure the Terminal to always close when the process exits: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior
