### ISSUE TITLE
Ctrl+C Terminated Whole SSH Session Rather Than The Executing Command Inside SSH Session

### ISSUE THREAD

**Issue by wengm** [microsoft/terminal#10904]
### Windows Terminal version (or Windows build number)

10.0.18363, 1.9.1942.0

### Other Software

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

### Steps to reproduce

SSH to remote server (E.g. Command line of the profile: ssh NAME@HOST)
Run command which could last for long time, for example "tree" under one big directory.
Ctrl+C

### Expected Behavior

The command in SSH session is terminated

### Actual Behavior

SSH session is terminated

**Comment by DHowett** [comment]
Terminal just sends the `^C` over to ssh.exe, which handles it directly. I don't believe we're doing anything strange here.

If you use ssh.exe _outside_ Terminal (same version!), how does it handle this case?

**Comment by wengm** [comment]
@DHowett 

You are right. We can close this. Thanks
