### ISSUE TITLE
Terminal can't access/go back to text that has scrolled off screen.

### ISSUE THREAD

**Issue by Panzerbjrn** [microsoft/terminal#10905]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

Write code that has more lines than is displayed on screen, or bring the code back in PowerShell by using up arrow to return to code that has previously been executed.

### Expected Behavior

I would expect to go back to the code by using the arrow keys, or PowerShell's CTRL+r functionality.
This works as expected in CMD, but not in Windows Terminal.
Here we can see it working in CMD, I can go back and forth between the top and the bottom of the text:
![image](https://user-images.githubusercontent.com/10132417/128700991-634465df-6567-4a3a-b86c-94ce4ea133b5.png)
![image](https://user-images.githubusercontent.com/10132417/128700932-3e53b25f-8876-4e54-82ec-54c58f81423d.png)

### Actual Behavior

And here it isn't working in Windows Terminal:
![image](https://user-images.githubusercontent.com/10132417/128701202-0ff24252-5d4c-4c9f-8eaf-62bd3953feb5.png)
![image](https://user-images.githubusercontent.com/10132417/128701254-508969cc-d61c-4bc9-8154-182bbab1e3b2.png)

Once the top line has scrolled off the screen, I can't return to it.

**Comment by zadjii-msft** [comment]
You know, I'm almost positive that we've seen this before, but I can't seem to find it. I think this has to do with how PSReadline renders a multiline prompt to the Terminal.

I'll leave this open to track it for now. Thanks!

**Comment by DHowett** [comment]
The symptoms here look largely the same as https://github.com/PowerShell/PSReadLine/issues/724, and I believe that version of windows (10.0.19041) has the impacted version of PSReadline.

The first build that had the fixed version of PSReadline was 10.0.19544.

**Comment by zadjii-msft** [comment]
@DHowett Does that mean we can close this one out as external?

@Panzerbjrn Can you try [installing an updated PsReadline version](https://github.com/PowerShell/PSReadLine#installation)/? Admittedly, I don't know how to check which version you currently have.
