### ISSUE TITLE
Rapid Cyrillic keyboard input renders characters as questions marks

### ISSUE THREAD

**Issue by synner88** [microsoft/terminal#10918]
### Windows Terminal version (or Windows build number)

10.0.19042.0, 1.9.1942.0

### Other Software

Cygwin 3.2.0
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)

settings.json snippet:
```
            {
                "acrylicOpacity": 0.90000000000000002,
                "antialiasingMode": "cleartype",
                "bellStyle": 
                [
                    "window",
                    "taskbar"
                ],
                "closeOnExit": "always",
                "commandline": "C:/cygwin64/bin/bash.exe -i -l",
                "cursorShape": "filledBox",
                "experimental.retroTerminalEffect": false,
                "fontFace": "Cascadia Code",
                "fontSize": 12,
                "fontWeight": "normal",
                "guid": "{ff3d2c15-5fce-4569-bc80-b635ba6fd059}",
                "hidden": false,
                "icon": "D:\\Dropbox\\Icons\\Dakirby309-Simply-Styled-OS-Linux.ico",
                "name": "Cygwin Bash",
                "padding": "10",
                "useAcrylic": true
            },
```

### Steps to reproduce

1. Add "Bulgarian (Phonetic Traditional)" keyboard layout from Windows 10 Language options.
2. Setup Cygwin bash inside Windows Terminal via above JSON config.
3. Open Windows Terminal
4. Alt+Shift to select "Bulgarian (Phonetic Traditional)" keyboard layout.
5. **Rapidly** type on the keyboard.

Issue occurs even inside vim!
Saved files even contain the "?" instead of the typed Cyrillic chars, so it's not just a rendering issue, but an input one!
Can it be font-related? But slow typing renders/inputs correct chars!

### Expected Behavior

Cyrillic letters are properly rendered at the command prompt.

### Actual Behavior

Some characters are rendered as questions marks "?".
Refer to screenshot.
![Cygwin bash](https://user-images.githubusercontent.com/29090601/129000396-eef9fcd2-ad1e-4610-8a9f-53b3551879b1.png)

**Comment by carlos-zamora** [comment]
Hi @synner88. Sorry for the radio silence here. It's been quite some time. Is this still happening? If so, does it happen with shells that do not use the cygwin runtime at all?

**Comment by synner88** [comment]
Hello, @carlos-zamora, thank you for your concern!
Issue disappeared long time ago but I don't know at what release version.
I am always using the latest stable release.
Cheers!

**Comment by DHowett** [comment]
Thank you for following up! Glad it's been fixed!
