### ISSUE TITLE
Interfacial separation

### ISSUE THREAD

**Issue by TSaltedfishKing** [microsoft/terminal#10913]
### Windows Terminal version (or Windows build number)

10.0.19042.985

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/60768370/128817713-e1bc9344-5492-4a87-bbd7-f3e3d88e60d1.png)
![图片](https://user-images.githubusercontent.com/60768370/128817759-67ca1a38-a403-4106-ad64-a03903a2b9a7.png)
![图片](https://user-images.githubusercontent.com/60768370/128817826-8684baf7-3336-40c7-85fb-a925d8fbcb1e.png)
![图片](https://user-images.githubusercontent.com/60768370/128817988-79c3c30e-8f3d-443c-800f-ddf7afa66adf.png)

### Expected Behavior

![1](https://user-images.githubusercontent.com/60768370/128817537-dd605a8a-5448-4e1a-8642-2eeafb78d91a.gif)

### Actual Behavior

![图片](https://user-images.githubusercontent.com/60768370/128818127-45f8ec96-351b-4a0c-a3d1-726d46500212.png)

**Comment by TSaltedfishKing** [comment]
One more thing
![2](https://user-images.githubusercontent.com/60768370/128819222-6d59f758-6700-4b32-8f66-24991dac4fc7.gif)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22default+profile%22+scroll+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
