### ISSUE TITLE
"Default Profile" dropdown menu goes out of the window when scrolling

### ISSUE THREAD

**Issue by Cikappa2904** [microsoft/terminal#10912]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Windows Version 19043.928

### Steps to reproduce

Open Windows Terminal, go to Settings, open the Default profile dropdown menu and then scroll using either the scroll bar or the mouse wheel

### Expected Behavior

The dropdown menu to hide when going over the window border

### Actual Behavior

The dropdown menu goes over the window borders

![immagine](https://user-images.githubusercontent.com/49496033/128812833-a2033de5-d69e-4d44-b9a7-b01bfdfad706.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22default+profile%22+scroll+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
