### ISSUE TITLE
Installing versson 1.9.1942.0 via Scoop results in wt not starting at all

### ISSUE THREAD

**Issue by TheLeftMoose** [microsoft/terminal#10929]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

run 
>scoop install windows-terminal
> wt

### Expected Behavior

wt to start as usuall

### Actual Behavior

Windows terminal do not start.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #10662 for more discussion.

/dup #10662
