### ISSUE TITLE
Opening 'Quake mode' does not work until another instance of Windows Terminal is running

### ISSUE THREAD

**Issue by NinovanderMark** [microsoft/terminal#10920]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Powershell 7.1.3

### Steps to reproduce

Pressing ```win``` + ```tilde``` after a clean reboot.

Entering 'exit' in the existing Windows Terminal that has been triggered by ```win``` + ```tilde``` then attempting to reopen it by using ```win``` + ```tilde```

This is my settings.json:
[settings.zip](https://github.com/microsoft/terminal/files/6967803/settings.zip)

### Expected Behavior

I expected the Windows Terminal to be opened, regardless if another instance was running, or I had opened it prior.

### Actual Behavior

Windows Terminal is not dropped down from the top, nothing else appears to happen.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9996 for more discussion.

/dup #9996
