### ISSUE TITLE
ssh disconnect automaticlly after a period of time.

### ISSUE THREAD

**Issue by coby-wang** [microsoft/terminal#10928]
### Windows Terminal version (or Windows build number)

Microsoft Windows NT 10.0.19043.0

### Other Software

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

### Steps to reproduce

1.  open ssh connection, and then execute a few ssh commands.
2.  do other things and keep the ssh connection.
3.  get back the ssh connection and execute ssh command

### Actual Behavior

windows terminal response slowly, disconnect ssh automaticlly.
![image](https://user-images.githubusercontent.com/73372253/129134049-3c99e3a2-a2fd-4d09-8320-a4dcf0d29b32.png)

**Comment by zadjii-msft** [comment]
Does this repro in a vintage console window (i.e. `conhost.exe`, like by launching `cmd.exe` directly)? If so, then I'm expecting that this isn't a Terminal-specific issue and is something that should be reported over at https://github.com/powershell/win32-openssh/

**Comment by WSLUser** [comment]
This got alittle better a few releases ago or something like that but I suspect it's a bit of both win32 openssh and wt. cmd doesn't do it for as long as wt though certainly still a delay. I'll do another comparison to see how long each takes. I constantly use ssh and it's easy to repro this if you have a low ssh timeout period set in the ssh config on the remote host. I will note, it has always seemed to be a bit faster in response with ssh used in WSL but still not immediate like Mintty or Putty are.

**Comment by DHowett** [comment]
> This got alittle better a few releases ago or something like that but I suspect ... wt.

WT knows nothing about the SSH protocol and makes no endeavour to implement a process timeout of any kind. Speculation that WT is involved is specious.

**Comment by coby-wang** [comment]
OK, thanks for your attention. I'll keep watching.
