### ISSUE TITLE
Exposing LVB Grid through VT

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#10932]
# Description of the new feature/enhancement

When `ENABLE_LVB_GRID_WORLDWIDE` mode is set, it's possible to use `COMMON_LVB_*` flags to emphasize portions of output.
It's a neat feature (thank you), but it only works with `WriteConsoleOutput` API, which is now considered legacy and doesn't support extended colours and attributes.

It would be nice to have the grid attributes accessible through ESC sequences.

**Comment by DHowett** [comment]
Funny enough, we're tracking this one in  /dup #8037!
