### ISSUE TITLE
VKey assertion failure

### ISSUE THREAD

**Issue by Rosefield** [microsoft/terminal#10933]
### Windows Terminal version (or Windows build number)

dev origin/main

### Other Software

I use the colemak keyboard layout primarily, but it also seems to happen with regular qwerty too.

### Steps to reproduce

Launch the application, assert at line https://github.com/microsoft/terminal/pull/10917/files#diff-ac308dd6d23797c02f8be4591060500c2474856a7c3f483ac5cff219b3fc16a2R720 fails

### Expected Behavior

terminal actually loads

### Actual Behavior

exception thrown.

**Comment by Rosefield** [comment]
@lhecker sorry :(

**Comment by DHowett** [comment]
Ha! Never apologize for that. It's an excellent catch. :smile:

@lhecker will def. need to take a look at this one.

**Comment by lhecker** [comment]
@Rosefield Can you post the "actions" array from your settings.json? While I know exactly what I forgot to keep in mind (not all scan-codes have virtual keys), I'm unfortunately unable to reproduce this and thus can't test if my fix is correct.

**Comment by Rosefield** [comment]
This is my settings.json
https://gist.github.com/Rosefield/b7765da9fb8aa6aee7518b4d59d329cb

**Comment by lhecker** [comment]
You can fix the crash by removing this invalid action:
```json
{
    "command": "unbound",
    "keys": ""
},
```

I find it a bit puzzling that we don't check for such mistakes. 😯

**Comment by Rosefield** [comment]
Interesting, I definitely didn't add that myself so there might be a bug in the settings UI that set it?
