### ISSUE TITLE
alt+space displays system menu *and* sends key binding to Terminal

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10935]
### Windows Terminal version (or Windows build number)

1.11

### Steps to reproduce

Press alt-space!

### Actual Behavior

![image](https://user-images.githubusercontent.com/189190/129275589-56034f87-b95a-4158-9450-bddb0fb89c02.png)

/cc @FWest98 possible fallout from #10799?

**Comment by FWest98** [comment]
That’s very strange, that shouldn’t happen. I don’t see how my code can produce this behaviour:

https://github.com/microsoft/terminal/pull/10799/files#diff-c10bb023995e88dac6c1d786129284c454c2df739ea547ce462129dc86dc2697R812

In this line and the following, alt+space will only be sent to the terminal when it is explicitly unbound, but then handled will be true always so it shouldn’t trigger the system menu.

So maybe this is somewhere further up, in the main eventhandler loop?
