### ISSUE TITLE
vertical tabs (like edge chromium browser)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/terminal#10939]
# Description of the new feature/enhancement
When I opened a lot of tabs in windows terminal, I can't view all the tabs at once, and have to scroll on the tabview.
![image](https://user-images.githubusercontent.com/54425948/129291593-74903efb-2c9b-4631-8287-e39cdd47f696.png)

I hope that wt can have the "vertical tabs" feature like edge chromium browser
![image](https://user-images.githubusercontent.com/54425948/129291765-b9202b41-0aa0-4814-97ad-fb734347d3e3.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22vertical+tabs%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #835 for more discussion.

/dup #835
