### ISSUE TITLE
Support for Polish language in Windows Terminal

### ISSUE THREAD

**Issue by Daxxxis** [microsoft/terminal#10931]
# Description of the new feature/enhancement

Because Windows Terminal will be available bundled with Windows 11, support for the Polish language would make it possible to reach a wider audience.

# Proposed technical implementation details (optional)

If possible, I can be responsible for the translation of the application to Polish.

**Comment by skyline75489** [comment]
I think the translation is meant to be done inside MS by the internal localization team. /cc @lhecker for some idea.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think we're gonna track these sorts of requests all in one place, in #10667.

/dup #10667
