### ISSUE TITLE
right-clicking the tray icon focuses terminal *and* opens menu

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10936]
### Windows Terminal version (or Windows build number)

1.11

### Steps to reproduce

as in title

### Actual Behavior

as in title

**Comment by leonMSFT** [comment]
Yeah I really wanted to find a workaround even if bodgy around this 😢 - 
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#remarks
![image](https://user-images.githubusercontent.com/57155886/129436170-9e57c396-49e0-4daf-9217-fcd816c9b5c9.png)

**Comment by DHowett** [comment]
_oh no_. I wonder how other applications get around it. Have an invisible window "hosting" the tray icon?

**Comment by zadjii-msft** [comment]
I guess we should check what PowerToys does. Theirs works the way we want 🤔
