### ISSUE TITLE
Get rid of buffering in the partials handling of `u8u16` and `u16u8`

### ISSUE THREAD

**Issue by german-one** [microsoft/terminal#10946]
# Description of the new feature/enhancement
The `state` classes used for the partials handling contain a buffer which is used to provide a preprocessed string that contains only complete code points for the conversion. This means that each and every incoming string is copied to the buffer first. And this buffer exists for the life time of the `state` instance. @lhecker already implemented a check in order to shrink the buffer if it grows too much. However, a few days later a facepalm moment appeared to me because buffering of the whole string is not necessary at all. We just need to complete the partial code point in the cache and convert it separately.
It's
currently: _copying the whole string in a persistent buffer every time the function is called_
vs.
proposed: _no buffering, but possibly calling `MB2WC` or `WC2MB` twice (only if partials have been cached)_

# Proposed technical implementation details (optional)
Something about like that for `u8u16` (would be quite similar for `u16u8` using an array of 2 `wchar_t`)
<img width="721" alt="nobuffer" src="https://user-images.githubusercontent.com/46659645/129393515-5d75dfd8-9cf2-4c55-b106-8ab812833a19.png">

**Comment by lhecker** [comment]
I've already prototyped a buffer-free converter a while ago: https://github.com/microsoft/terminal/blob/e7d00cab8e84f6afde00951f8f6c6320308318a0/src/inc/til/u8u16convert.h
I simply do the utf8/utf16 -> utf32 -> utf16/utf8 encoding for a single codepoint myself. But I never got around to finish it completely. I could do that sooner rather than later if we want to...

**Comment by german-one** [comment]
Looks good. Just one side note: Simplified conversion of the single code point has the risk of getting crap for invalid UTF-8. The API functions would shift in a replacement character, which is the reason why I'd prefer using them. You could c\p the checked implementation out of the U8U16Test project though. However, I'm not sure if it's even worth to think too much about it ... 😊

**Comment by lhecker** [comment]
@german-one Yeah we can use the win32 functions for that... Since they aren't actual syscalls (but just regular DLL functions) the call overhead is only a few nanoseconds anyways. 🙂

**Comment by german-one** [comment]
@lhecker I had same free time over the weekend. So I tried to work on my proposal and already have something that passed the unit tests locally. If you don't mind I'll file a draft PR somewhen within this week in order to get some feedback if I'm heading in the right direction. I just want to update the templatization of all overloads beforehand. I very much like your's that only allows string_views for the incoming data.

**Comment by lhecker** [comment]
@german-one Of course! Please feel free to submit a draft PR, if you'd like. 🙂
