### ISSUE TITLE
open new tab not support use same cwd from start

### ISSUE THREAD

**Issue by bluelovers** [microsoft/terminal#10940]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Steps to reproduce

1. open Windows Terminal at some where `G:\Users\The Project\nodejs-yarn\ws-regexp\packages\cjk-conv\test`

![image](https://user-images.githubusercontent.com/167966/129295448-baa0d0d7-887a-4a22-a21c-9e16d2effa07.png)

2. add new tab

3. cwd of new tab should same as `G:\Users\The Project\nodejs-yarn\ws-regexp\packages\cjk-conv\test`

### Expected Behavior

cwd of new tab should same as `G:\Users\The Project\nodejs-yarn\ws-regexp\packages\cjk-conv\test`

### Actual Behavior

`C:\Users\User`

**Comment by skyline75489** [comment]
Hi! I think https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033 could be helpful. It's like a hidden feature that is not really well-documented.

**Comment by zadjii-msft** [comment]
Huh, I thought this was tracked by #8933 and fixed in #10546.

Out of curiosity, what's your `settings.json` look like?
