### ISSUE TITLE
Split Starting config and default config

### ISSUE THREAD

**Issue by jfheins** [microsoft/terminal#10942]
# Description of the new feature/enhancement

As a user, I would like to configure separate configurations for the first tab and for the context menu.

When I start Windows Terminal, I want the git bash to be the first tab. However, If I use the explorer context manu to open this folder in Windows Terminal, I usually want a new Powershell.

Currently, the default profile applies to the first tab as well as to any tabs opened using the explorer.

# Proposed technical implementation details (optional)

In the settings, there could be a second dropdown for Startup profile below or above the default profile:
![image](https://user-images.githubusercontent.com/5293502/129322026-b94d62b7-0116-4822-9b56-111d6eb57a43.png)

I am currently using Windows Terminal Preview, Version: 1.10.1933.0

**Comment by zadjii-msft** [comment]
This actually sounds a lot like /dup #6111
