### ISSUE TITLE
Crash on input after text resize

### ISSUE THREAD

**Issue by d-bingham** [microsoft/terminal#1095]
Terminal crashes on input after a text resize.

# Environment

```none
Windows build number: [Version 10.0.18362.145]
Windows Terminal version (if applicable): 71e19cd82528d66a0a7867cbed85990cfc1685f1

```

# Steps to reproduce

1) Start up WSL bash in Terminal (this bug does not appear to happen in powershell or cmd)
2) Fill the console to get the cursor at the bottom of the window

![image](https://user-images.githubusercontent.com/26487560/58743272-f7407900-83f3-11e9-988e-44fc0282d4d8.png)

3) Increase font size vi Control+MouseWheelUp

![image](https://user-images.githubusercontent.com/26487560/58743279-1b9c5580-83f4-11e9-90dc-bc6f34e3a236.png)

(note: while increasing font size, sometimes the bottom line is off the end of the terminal, which seems like it's the likely culprit...)

4) Hit enter

![image](https://user-images.githubusercontent.com/26487560/58743288-3e2e6e80-83f4-11e9-89b3-024b2d6262d0.png)

# Expected behavior

It doesn't crash.

# Actual behavior

It crashes.

**Comment by zadjii-msft** [comment]
Good find here. Seems easily repro-able, so debugging and fixing shouldn't be _that_ hard...

**Comment by DHowett-MSFT** [comment]
Mind pressing "retry" and grabbing the stack from VS? Thanks!

**Comment by d-bingham** [comment]
Stack trace of the exception thrown:

![image](https://user-images.githubusercontent.com/26487560/58838915-ac0dac80-8625-11e9-8abe-be20095b235d.png)

**Comment by d-bingham** [comment]
![image](https://user-images.githubusercontent.com/26487560/58838956-c5165d80-8625-11e9-9445-d2d24fdf2e16.png)

****
![image](https://user-images.githubusercontent.com/26487560/58838986-e1b29580-8625-11e9-85de-0fac34976a68.png)

**Comment by zadjii-msft** [comment]
I'm almost 100% certain #2149 did end up fixing this. Hooray!
