### ISSUE TITLE
Make it possible to use an existing profile if an app is launched via defterm

### ISSUE THREAD

**Issue by dhrdlicka** [microsoft/terminal#10952]
# Description of the new feature/enhancement

There should be an option to check whether there is a profile that would match the command line of a console app launched when Terminal is set as default and use that profile.

This would be a nice alternative to using the conhost configuration (#9458) as some people might prefer to use their already defined profiles rather than what's defined in the registry or shortcuts.

# Proposed technical implementation details (optional)

Some extra thought should be given to handling command line arguments in both the profile's `commandLine` and the launched app's command line. A sane compromise could be that a launched app's command line would only match `commandLine` with either the exact same arguments or none at all to make sure that `cmd.exe` doesn't get launched with a profile defined for some batch file.

**Comment by WSLUser** [comment]
I'm pretty part of "what's defined in registry or shortcuts" would include the existing profiles. When that feature is added, passing those existing profiles off to the registry would almost certainly be a hard requirement for precisely the use-case you bring up here.

**Comment by zadjii-msft** [comment]
@miniksa has thoughts on this. (also related: #10669)

**Comment by miniksa** [comment]
I did think that I had a feature logged for this but I cannot find it. It might have just been a feature in my head. I would like to perform some sort of matching against the profiles and left provisions in for passing this sort of information around in at least a few places.
