### ISSUE TITLE
Windows Terminal for Windows Server editions.

### ISSUE THREAD

**Issue by amitsrivastava-frontline** [microsoft/terminal#10954]
### Windows Terminal for Windows Server editions is not available.

Please provide a Windows terminal installer which can install terminal on servers. All tricks to install this on server failed. A lot of console work done on server machines as servers are for professionals who like to work on console. Terminal has more usefulness for servers rather then desktop OS.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22windows+server%22+in%3Atitle) when filing new issues, and [read the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version).
