### ISSUE TITLE
initialPosition in Settings UI?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10959]
# Description of the new feature/enhancement

Implement setting initialPosition in the Settings UI .  As it is, it's a chore to change it.

If feasible, it (and Launch Size, too) might (also) have "use current" and "use last" options.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9075 for more discussion.

/dup #9075
