### ISSUE TITLE
Rendering bugs when NVIDIA ShadowPlay is enabled

### ISSUE THREAD

**Issue by bnb** [microsoft/terminal#10956]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Nvidia GeForce Experience 3.23.0.74

### Steps to reproduce

- Open Terminal
- Run a few commands to make the window scroll any amount
- Old ShadowPlay UI rendering is attached to where it rendered

Examples:
![image](https://user-images.githubusercontent.com/502396/129592134-a6110122-7507-4c1a-bc40-2a67baa83603.png)

![image](https://user-images.githubusercontent.com/502396/129592148-6172cc0f-4014-4fa7-8e56-8ec5d2231060.png)

### Expected Behavior

- ShadowPlay UI shouldn't be rendered a bunch of times

### Actual Behavior

- ShaodwPlay UI is rendered a bunch of times.

**Comment by bnb** [comment]
I don't totally believe this is a problem that is sqaurely on the Terminal team's shoulders, but if you use Nvidia GeForce Experience - which is how Nvidia manages their driver updates for their GPUs - this will be enabled by default and thus will be something a lot of users who have an Nvidia GPU experience.

**Comment by WSLUser** [comment]
Probably best filed with the WinUI folks since the UI is inherited by them.

**Comment by zadjii-msft** [comment]
> Probably best filed with the WinUI folks since the UI is inherited by them.

That's pretty unlikely - I'd reckon that the element of the Terminal that this Nvidia UI is attaching to is probably our SwapChainPanel, and we're responsible for rendering the content of that. However, nvidia's software does seem to have an immense amount of difficulty with the Terminal (#649, [reddit thread](https://www.reddit.com/r/techsupport/comments/lwqwrj/geforce_experience_detecting_applications_as_games/)).

I'd recommend reporting this upstream at _wherever nvidia bugs go_. They're definitely doing something weird in how they try to determine what is or isn't a game.

**Comment by zadjii-msft** [comment]
I'm closing this out on our side. If Nvidia wants to come back and tell us what we can do to opt out of this, I'm all for it. At the time though, this seems like something they'll need to fix on their end.

(feel free to continue discussion of workarounds below)
