### ISSUE TITLE
[1.11] Terminal opens behind everything else from the Run dialog

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#10965]
### Windows Terminal version (or Windows build number)

1.11; 10.0.22440

### Steps to reproduce

I do not know whether this is a Windows version change or a Terminal change. Given that there's no other centennial apps that _exist_, I can't really check that part. 😀 

### Actual Behavior

-

**Comment by DHowett** [comment]
Oh no. It reproduces in unpackaged launch, but only via wt.exe. It doesn't repro via WindowsTerminal.exe.

**Comment by DHowett** [comment]
It reproduces on WT 1.9. Suspecting a Windows regression.

**Comment by zadjii-msft** [comment]
FWIW I'm not seeing this on 22434.rs_wdx_dxp. That's a fairly narrow range of builds.

**Comment by zadjii-msft** [comment]
Also, isn't `notepad` centennial now these days 🙃

**Comment by zadjii-msft** [comment]
tracking MSFT:35378923

**Comment by zadjii-msft** [comment]
This is fixed in the OS as of `22471.1000.rs_prerelease`
