### ISSUE TITLE
Clarity on Running Commands

### ISSUE THREAD

**Issue by hl2guide** [microsoft/terminal#10968]
### Windows Terminal version (or Windows build number)

Windows Terminal 1.9.1942.0

### Steps to reproduce

- Have a .ps1 file at a location
- open up the command line (cmd.exe)
- run: `wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN% -c "create_combined_list.ps1"`

%GHGEN% = Environment Variable of location

### Expected Behavior

PowerShell script runs.

Please try to improve the documentation about this.

### Actual Behavior

this error is shown:
`[error 0x80070002 when launching 'create_combined_list.ps1']`

this works to go to a directory:

`wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN%`

but these don't run a PS1 file:

```
wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN% -c "create_combined_list.ps1"

wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN% -c ".\create_combined_list.ps1"
```

**Comment by zadjii-msft** [comment]
The `commandline `parameter of the `new-tab` command isn't _appended_ to the profile's `commandline`, it _replaces_ it. So the Terminal is trying to literally `CreateProcess("create_combined_list.ps1", ...); `, which isn't a valid commandline. You probably want `powershell create_combined_list.ps1` (or whatever the commandline for running a `ps1` in powershell is).


```
wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN% -- powershell create_combined_list.ps1
```

Should work just fine

**Comment by hl2guide** [comment]
> The `commandline `parameter of the `new-tab` command isn't _appended_ to the profile's `commandline`, it _replaces_ it. So the Terminal is trying to literally `CreateProcess("create_combined_list.ps1", ...); `, which isn't a valid commandline. You probably want `powershell create_combined_list.ps1` (or whatever the commandline for running a `ps1` in powershell is).
> 
> ```
> wt.exe new-tab --profile "PowerShell" --title "Generating the AIO List" -d %GHGEN% -- powershell create_combined_list.ps1
> ```
> 
> Should work just fine

nope, maybe the syntax needs a look over to make it less clunky, limited and rigid.
