### ISSUE TITLE
How to disable QuickEdit in Windows Terminal?

### ISSUE THREAD

**Issue by Nicholaz99** [microsoft/terminal#10962]
I'm sorry, but I wonder how to disable QuickEdit in Windows Terminal? I didn't see the option in the settings... I've tried to disable quick edit in each available shell, yet it doesn't work in windows terminal..

**Comment by Nicholaz99** [comment]
Ah, I don't like the right-click paste feature. So I want to disable it. Before I use windows terminal, I can simply disable this via the wsl/cmd/powershell properties by uncheck the QuickEdit. But there isn't the checkbox for QuickEdit in the windows terminal. I wonder How should I turn off this right-click paste feature.

**Comment by zadjii-msft** [comment]
Oh, okay. We're tracking that in /dup #1553. Thanks for following up!
