### ISSUE TITLE
在Release里加入已经编译完成的安装包如何？

### ISSUE THREAD

**Issue by Red-Error404** [microsoft/terminal#1097]

**Comment by quank123wip** [comment]
Please use English plz,not all the people here such as you and me are Chinese.

In my opinion, you should change the title into "Add the binary files into the Release"

**Comment by xa0082249956** [comment]
> Dupe of #468.

> There are no binaries to download quite yet.
> The Windows Terminal is in the very early alpha stage, and not ready for the general public quite yet. If you want to jump in early, you can try building it yourself from source.
> 
> Otherwise, you'll need to wait until Mid-June for an official preview build to drop

.
