### ISSUE TITLE
Debian/WSL Distros are not starting on Windows Terminal Stable 1.9.1942.0

### ISSUE THREAD

**Issue by Pedro1234-code** [microsoft/terminal#10977]
### Windows Terminal version (or Windows build number)

10.0.22000.132

### Steps to reproduce

Windows 11 22000.132/ Windows Terminal Stable 1.9.1942.0. 

When I open Windows Terminal, it encounters an error saying that the profile placed in the "default profile" within settings.json does not exist, but when I restart the Windows 11 Default Terminal, it works perfectly. The profile is Debian 10 Buster in Windows Subsystem for Linux (WSL).

### Expected Behavior

no

### Actual Behavior

no

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #6160 for more discussion.

* /dup #6160
* /dup #7199
* /dup #9905
