### ISSUE TITLE
Font size setting does not work

### ISSUE THREAD

**Issue by leonarduschen** [microsoft/terminal#10973]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Change font size directly JSON settings file

Below is what my "profiles" section looks like

```json
    "profiles": {
        "defaults": {
            "font": {
                "size": 40,
                "weight": "normal"
            }
        },
        "list": [
            {
                "commandline": "powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\leonarduschen",
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
```

### Expected Behavior

Font size gets smaller

### Actual Behavior

No font size changes in any of the profiles

![image](https://user-images.githubusercontent.com/65842583/129855780-cec13d35-b060-4fda-aa0d-acdd830d70e4.png)

**Comment by DHowett** [comment]
Thanks for the report! @PankajBhojwani, do you know if the new modern font syntax is in 1.9? I suspect that it might be 1.10 only and this is a documentation issue.

**Comment by zadjii-msft** [comment]
Judging by https://github.com/microsoft/terminal/pull/10433#issuecomment-880062939, and the lack of a paired comment for 1.9, I'm thinking that this is 1.10 only.

**Comment by leonarduschen** [comment]
Right, using `fontSize` works !

So am I correct to say the documentation here https://docs.microsoft.com/en-us/windows/terminal/ is in general always more up to date then latest release (i.e., currently 1.9) ?

**Comment by zadjii-msft** [comment]
The docs are usually updated in tandem with features getting merged, but something like this should have had a little "Notes" section to indicate that this feature was only in 1.10+, and what to do in <=1.9. I'll go update those now.

**Comment by PankajBhojwani** [comment]
> I suspect that it might be 1.10 only and this is a documentation issue.

My thoughts as well!
