### ISSUE TITLE
Can't send CTRL+,

### ISSUE THREAD

**Issue by robertutterback** [microsoft/terminal#10989]
### Windows Terminal version (or Windows build number)

1.9.1942.0 (also 1.10.1933.0)

### Steps to reproduce

1. Put 
`       {
            "command": "unbound",
            "keys": "ctrl+,"
        }
`
into settings.json.

2. Type "Ctrl+," e.g., in Emacs or `showkey -a`

### Expected Behavior

Emacs or `showkey -a` will receive "Ctrl+,".

### Actual Behavior

Emacs and `showkey -a` receive "Ctrl+l" instead.

**Comment by DHowett** [comment]
I believe there is no encoding for <kbd>Ctrl+,</kbd> in VT; confirming with a couple other terminal emulators:

In all below instances, I pressed <kbd>Ctrl+A</kbd> <kbd>Ctrl+,</kbd>

## gnome-terminal

![image](https://user-images.githubusercontent.com/189190/130154875-91678cb5-995b-4714-85e5-ee1ebbcd3114.png)

## xterm

![image](https://user-images.githubusercontent.com/189190/130154807-17f35b48-8174-4ab2-91d1-a1c5ee008334.png)

## konsole

![image](https://user-images.githubusercontent.com/189190/130154861-c2287364-6f42-43a9-86a3-a22bb69fe3b6.png)


What are you expecting to see?

**Comment by robertutterback** [comment]
Oops, sorry, I didn't check in anything else. I guess I assumed something was wrong because Terminal chooses to send ctrl+l here, which seemed odd to me. I have used this keybinding in the past in Emacs, but I guess it was only ever Emacs in a graphical window.
