### ISSUE TITLE
Drag feature lack HiDPI & mixed DPI support

### ISSUE THREAD

**Issue by JeffersonQin** [microsoft/terminal#10983]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

- Monitor DPI higher than 100%
- (Maybe): with different DPIs across different monitors
- Drag a file into the terminal

### Expected Behavior

The file should be to be dropped **anywhere** in the window

### Actual Behavior

The file could only be dropped in **a limited area** of the window:

![image](https://user-images.githubusercontent.com/30655701/129996381-7bb34a7f-8941-46df-baeb-af89a53d8b2c.png)

![image](https://user-images.githubusercontent.com/30655701/129996422-6c1d59e6-f07d-43d2-9d86-e1bc284253d2.png)

![image](https://user-images.githubusercontent.com/30655701/129996508-c22c9f36-1d50-44e2-93e6-9b798e1faa6c.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+drop+dpi+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #2606 for more discussion.

/dup #2606
