### ISSUE TITLE
Allow a "no tabs open" state

### ISSUE THREAD

**Issue by Convincible** [microsoft/terminal#10987]
# Description of the new feature/enhancement

1. Allow me to close ALL tabs while keeping Terminal open as a program.
2. Allow this to be the default state for the app.
3. On the "no tab open" screen, offer large buttons to launch a particular terminal.

This would improve usability for users who want to use Windows Terminal but need to use a different terminal each time. Some days I need to launch Ubuntu constantly. Other days it's PowerShell. It's annoying to always launch with a particular terminal, then load another one, then close the first one.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3586 for more discussion.

/dup #3586
