### ISSUE TITLE
The about dialog does not resize correctly

### ISSUE THREAD

**Issue by nereu-ls** [microsoft/terminal#10995]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

![1](https://user-images.githubusercontent.com/17891137/130241540-66910426-d6e4-449d-b53b-e87510c68687.png)
![2](https://user-images.githubusercontent.com/17891137/130241552-254f45e7-1b99-41e6-a02c-2a20018437ea.png)
![3](https://user-images.githubusercontent.com/17891137/130241564-91d543ab-5288-4744-b62b-542ae9f4e625.png)

### Actual Behavior

The transparency area dos not resize

**Comment by Lo0oG** [comment]
Duplicate of #2380

**Comment by DHowett** [comment]
Thanks all!
