### ISSUE TITLE
Missing weight configuration for bold text, matching "general" weight configuration

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/terminal#10992]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

PowerShell 7.1.4
starship-rs 0.56.0

### Steps to reproduce

Bold font face text as emitted by some advanced command-prompt rendering schemes (e.g. https://starship.rs/) may be rendered with a disproportionate weight.

This will happen whenever the user configures a non-standard "normal" text font weight - in my case, this is Cascadia Code PL *SemiLight*, i.e. a significantly reduced weight for normal text. This will apply to any static font with custom weights, or a dynamic font with the weight reduced.

In such scenarios, normal text is rendered to taste, but the bold text is _too bold_. The Microsoft Visual Studio Code embedded terminal gets this right - it allows configuring the weight for both normal text and bold text-

The below screenshot demonstrates the disproportionate weight of bold text vs normal next. This is not specific to starship or powershell; anything that renders bold text will demonstrate this.

![image](https://user-images.githubusercontent.com/3868036/130193517-1911d122-745c-4faf-903a-b6920cc2b1d7.png)

### Expected Behavior

Properly looking bold text (bold text font weight aesthetically matching normal text font weight)

This implies either of
* the ability to configure font weight for bold text; 
* "correct" font weights for bold text automagically computed - which will be a challenge

### Actual Behavior

Bold text rendition unpleasantly disproportionate relative to normal text rendition.

**Comment by skyline75489** [comment]
#10577

**Comment by zadjii-msft** [comment]
/dup #10577

thanks!
