### ISSUE TITLE
Random lines of text missing from terminal

### ISSUE THREAD

**Issue by iMoD1998** [microsoft/terminal#10990]
### Windows Terminal version (or Windows build number)

22000.160, 1.10.1933.0

### Steps to reproduce

Unsure how to reproduce.

### Expected Behavior

Display all text output.

### Actual Behavior

Large amount of lines just randomly dont appear in the terminal from apps that print alot of text.

Take a simple C++ app that does this:
```cpp
int main( )
{
	for ( int i = 0; i < 300; ++i )
	{
		printf( "Num: %i\n", i );
	}

	return 0;
}
```
Produces this output:

![image](https://user-images.githubusercontent.com/16210252/130155316-4ef672eb-b0f7-4ae3-b43f-8f5660182927.png)
![image](https://user-images.githubusercontent.com/16210252/130155334-48188d3f-a111-4d82-a4f8-5608e81732c8.png)

**Comment by DHowett** [comment]
Thanks for the report! This sounds suspiciously similar to /dup https://github.com/PowerShell/PSReadLine/issues/724

The old version of PSReadline that came with Windows PowerShell uses a "hard scroll" operation when the prompt is displayed. This "hard scroll" deletes the content that was scrolled off the screen.

If you can update PSReadline -- or perhaps even better -- upgrade to PowerShell 7, this issue should be thoroughly defeated. :smile:

**Comment by DHowett** [comment]
You know what, I misread this. Sorry! Reopening for reevaluation.

**Comment by zadjii-msft** [comment]
I think I've got an idea. 
![image](https://user-images.githubusercontent.com/18356694/130474072-25992ec2-3ae3-4bb3-b84a-586678111b3a.png)
How are you running your program here? Are you launching it from Visual Studio, and relying on the "default terminal" functionality to automatically create a Windows Terminal window, instead of a vintage console window?

**Comment by iMoD1998** [comment]
It happens regardless of how it was launched. This was just a quick example. This also happens when using ssh and doing apt upgrades as alot of text is printed fast.

**Comment by iMoD1998** [comment]
![image](https://user-images.githubusercontent.com/16210252/131209724-9884eefa-d4b9-42ee-a209-80fe0cdced8b.png)

**Comment by iMoD1998** [comment]
I think I've managed to narrow it down to powershell/cmd windows only being the root issue. 

For example: 
Launch powershell or cmd window
Print a lot of lines fast
It will break terminal by not showing blocks of text
Anything else spawned in that terminal will now also be broken including WSL

So it seems WSL wont break it on its own.

**Comment by zadjii-msft** [comment]
Hmm. This is me going out on a limb, but do you have anything in you PowerShell profile? I think it's `profile.ps1` (but I'm not very fluent in PowerShell, so that might be wrong)

**Comment by iMoD1998** [comment]
I haven't changed anything in my PowerShell profile and I've reinstalled terminal multiple times and deleted configs to see if it was something to do with that but no luck.

The only thing that has been constant is apps running in cmd or PowerShell that print a lot of text fast seem to cause the issue.

I don't think its a rendering bug as the "invisible text" when copied to clipboard is just a bunch of newlines.

Might try reinstall Windows 11 to so if its just oddly specific bug with my install.

**Comment by zadjii-msft** [comment]
That's so peculiar. My theory is that the conpty buffer and the Terminal buffer aren't the same size, but there's seemingly nothing causing that (especially if it repros in `cmd` profiles, not only powershell ones). 

In a powershell profile where this is happening, could you run `$Host.UI.RawUI.BufferSize`?

And just to be absolutely sure, you're not running this via the Default Terminal setting
![image](https://user-images.githubusercontent.com/18356694/131690145-382d820b-f439-4c64-81fd-970d388afd48.png)

correct? You're launching `wt.exe`, then that's spawning `cmd.exe`, not the other way around?

**Comment by iMoD1998** [comment]
Uhhhhm...

Just updated to latest windows 11 build 22449.1000 also updated terminal to 1.11.24210 and the issue seems to resolved itself as far as I have tested.

Can keep this issue open for a few days to see if its actually fixed, so far its persisted across reboots.

Also, when I was having the issue I tried launching it both with cmd and wt.

**Comment by iMoD1998** [comment]
Seems issue has resolved itself.

**Comment by DHowett** [comment]
Wild! Thank you for closing the loop here :smile:
