### ISSUE TITLE
Is there any reason to not use tabView.SelectedIndex()?

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#1100]
https://github.com/microsoft/terminal/blob/880272c7483a3bb6893dbec3725d0eb7375ab78a/src/cascadia/TerminalApp/App.cpp#L632-L639

Upon investigating #1074 & #1038, I was wondering if there is any reason that we are going through all the hassle of finding the correct `tabViewItem` from `vector tabs` instead of just something like
```cpp
    void App::_SetFocusedTabIndex(int tabIndex)
    {
        _tabView.SelectedIndex(tabIndex);
    }
```
I guess the diffrence is that I use the index from `_tabView.Item()` instead, but does `tabs` and `_tabView.Items()` ever get out of sync?

**Comment by zadjii-msft** [comment]
I honestly don't know if there's a reason. Does kinda seem to me like this would be easier...

**Comment by Summon528** [comment]
I also use the terminal with this piece of code for two days or so with no issue. Guess I'll make a PR.
