### ISSUE TITLE
tenant error

### ISSUE THREAD

**Issue by marioegghead2** [microsoft/terminal#11015]
### Windows Terminal version (or Windows build number)

i submitted a tenant issue so no need to fill this ;)

### Other Software

Tenant

Issue details:

Request Id: 9c99a6eb-033d-4b37-af29-d98e58ab7000
Correlation Id: f5dc65b6-9582-42a5-a8f0-c36134204060
Timestamp: 2021-08-23T10:51:59Z
Message: AADSTS50020: User account 'abel.sengkey2021@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '3b511579-5e00-46e1-a89e-a6f0870e2f5a'(Windows 365 Portal) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

### Steps to reproduce

trying to sign in to windows 365
selected account
then received message
you can find the message below

Request Id: 9c99a6eb-033d-4b37-af29-d98e58ab7000
Correlation Id: f5dc65b6-9582-42a5-a8f0-c36134204060
Timestamp: 2021-08-23T10:51:59Z
Message: AADSTS50020: User account 'abel.sengkey2021@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '3b511579-5e00-46e1-a89e-a6f0870e2f5a'(Windows 365 Portal) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

### Actual Behavior

Request Id: 9c99a6eb-033d-4b37-af29-d98e58ab7000
Correlation Id: f5dc65b6-9582-42a5-a8f0-c36134204060
Timestamp: 2021-08-23T10:51:59Z
Message: AADSTS50020: User account 'abel.sengkey2021@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '3b511579-5e00-46e1-a89e-a6f0870e2f5a'(Windows 365 Portal) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by zadjii-msft** [comment]
I don't think this is the right place for this bug report. This is the repro for the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and the Windows Console, and I'm not sure we have anything to do with Windows 365. Are you trying to use the Azure Cloud Shell to connect to Windows 365 or something? I'm just grasping at straws to see how this is related.

**Comment by marioegghead2** [comment]
> I don't think this is the right place for this bug report. This is the repro for the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and the Windows Console, and I'm not sure we have anything to do with Windows 365. Are you trying to use the Azure Cloud Shell to connect to Windows 365 or something? I'm just grasping at straws to see how this is related.

Yes! I am trying to go to windows 365.

**Comment by zadjii-msft** [comment]
Okay sorry, you just quoted the whole post. Are you:
1. Trying to use the Terminal's Azure Cloud Shell to connect to Windows 365? Or are you
2. Trying to report a Windows 365 bug?

**Comment by marioegghead2** [comment]
> Okay sorry, you just quoted the whole post. Are you:
> 
> 1. Trying to use the Terminal's Azure Cloud Shell to connect to Windows 365? Or are you
> 2. Trying to report a Windows 365 bug?
Number 2.

**Comment by marioegghead2** [comment]
I chose number 2.

**Comment by zadjii-msft** [comment]
Thanks for following up! Since this is the _Terminal_ repo, we can't really help you with Windows 365 issues ourselves. From [their FAQ](https://www.microsoft.com/en-us/windows-365/faq)

> Support is available in several ways, depending on how you purchased your Windows 365 subscription. For self-service purchases, request support through the Microsoft 365 Admin Center. If you purchased your Windows 365 subscription through volume licensing, contact your Microsoft account manager for help. If you purchased through a Microsoft Cloud Solution Provider (CSP), your CSP partner can submit support requests for nontechnical issues such as enrollment, membership, billing, subscription, and user management in the Microsoft Partner Center.

**Comment by dmatora** [comment]
I'm having same issue (getting `User account 'dmitry.matora@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services'` when trying to login into windows 365 site)
I can't request support from windows 365 site, since I can't login.
I understand this is not a proper place to file request but since I don't have a choice I just hopу if enough people report the issue here, responsible Microsoft team will notice it.

**Comment by anamax59** [comment]
Same here ! 

We are many to have this problem ...
