### ISSUE TITLE
Boost hashing performance with Robin Hood

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#11016]
# Description of the new feature/enhancement
Use MIT-licensed https://github.com/martinus/robin-hood-hashing to improve performance  and increase memory efficiency.  It does come with a custom allocator but it won't win any medals and can be ignored. Instead mimalloc should be compiled in instead and is even recommended by maintainer to use a dedicated allocator instead. This is filed under another issue.  Idea for adding this stems from https://github.com/microsoft/terminal/pull/10521#issuecomment-873255814. Also see https://github.com/microsoft/terminal/pull/10341 which addressed a bug with hashing that likely will need to be refactored slightly when adopting this library.

# Proposed technical implementation details (optional)
Replace use of `std::unordered_map` and/or `std::unordered_set` with Robin Hood equivalent among other changes.

**Comment by lhecker** [comment]
I already have a branch for this: https://github.com/microsoft/terminal/tree/dev/lhecker%2Frobin-hood-hashing
It results in a rather significant binary size increase and doesn't make any noticeable performance differences. It does however improve memory usage significantly under certain conditions.

I'm expecting to introduce that project in a later PR for a purpose were it has a true impact.

**Comment by lhecker** [comment]
I ended up writing my own purpose built hashmap and won't need `martinus/robin-hood-hashing` anymore. In other areas of this application hashmaps aren't used much.
