### ISSUE TITLE
The promotional video is on copyright strike.

### ISSUE THREAD

**Issue by sarunint** [microsoft/terminal#1101]
Earlier today, I wanted to show the promotional video of the new terminal to my friend. But it looks like that [the video](https://www.youtube.com/watch?v=8gw0rXPMMPE) is on copyright strike?

# Environment

```none
none
```

# Steps to reproduce

Visit https://www.youtube.com/watch?v=8gw0rXPMMPE

# Expected behavior

The video should play.

# Actual behavior

![image](https://user-images.githubusercontent.com/3850197/58749170-8b6e1700-84ac-11e9-9852-bcd70dbf2c70.png)

**Comment by zadjii-msft** [comment]
@cinnamon-msft is working on it :)

**Comment by sarunint** [comment]
Good to know :D

**Comment by DHowett-MSFT** [comment]
This seems to have been fixed
