### ISSUE TITLE
The ability to either give each pane a custom title, or view multiple tabs in a split way

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/terminal#11011]
# Description of the new feature/enhancement

I want to be able to give custom names to panes.

**Why:** For example, I have multiple `localhost` or `--watch` or `daemon` process running in split panes. I want to stop one of them, but can't remember which one it is.  Or, I want to start one, but can't remember if I've already started it.

# Proposed technical implementation details (optional)
I propose 2 different approaches to solve the problem:
1. maybe give user the option to "name" a pane, displayed as something like a floating title near the top right corner of the pane.
2. maybe provide such an option: "a new tab is created for each split pane". This is implemented by ConEmu:

![conemu](https://user-images.githubusercontent.com/32368482/130372445-bf618299-69c9-4d86-9bbd-77fb663a850b.gif)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4717 for more discussion.

/dup #4717

**Comment by ZYinMD** [comment]
Thanks @zadjii-msft. I summited a new issue with a narrower focus.
