### ISSUE TITLE
Crash immediately on launch if Fraps running

### ISSUE THREAD

**Issue by lietu** [microsoft/terminal#11010]
### Windows Terminal version (or Windows build number)

10.0.19042.1083, 1.9.1942.0

### Other Software

Fraps 3.5.99

### Steps to reproduce

1. Start Fraps (not sure if these are important so full list of settings I've got: Start Fraps minimized, Fraps window always on top, Run Fraps when Windows Starts, Minimize to system tray only, FPS counter enabled on top right corner)
2. Start Windows Terminal to Nu Shell, CMD, or Power Shell
3. Windows Terminal shows up for about a second and then instantly quits

![winterm](https://user-images.githubusercontent.com/1296558/130367895-dd7c9e39-fb2d-46d6-bac8-b80b6f2a2474.gif)

Starting Windows Terminal first and Fraps afterwards does not seem to affect Windows Terminal and I can e.g. open new tabs. Fraps does not affect conhost.

### Expected Behavior

Windows Terminal starts whether or not Fraps is running in the background.

### Actual Behavior

Windows Terminal for some reason crashes on launch if Fraps is running.

**Comment by lietu** [comment]
Fraps download at https://fraps.com/download.php

**Comment by lietu** [comment]
Just because you don't want to do anything with it does not mean the issue is resolved.

**Comment by zadjii-msft** [comment]
We're not suggesting that it is - but we can't really investigate this more on our end without a stack trace or a dump. The easiest way to get that to us would be to reproduce the issue with the feedback hub, as mentioned above. If you can get us that, then we can reopen and try to investigate.

**Comment by DHowett** [comment]
We should see if we can reproduce this; however, we may not be able to. Helping us out with a crash report from the feedback hub can make the source of a bug more obvious or otherwise help us investigate. Things like this -- crashes on launch -- are pretty rare for us to come across un-aided.

I'm going to reopen this bug for now and mark it "Needs-Repro" until we manage to reproduce it.

**Comment by lietu** [comment]
I don't see any obvious way to provide a stack trace or a dump in Feedback hub. Please do let me know if I'm missing something, but I'm not interested in sending any random unknown amounts of data from my PC to a 3rd party system and then hoping that you both 1) get what you need, 2) get nothing else.

![image](https://user-images.githubusercontent.com/1296558/132514034-cd99acf9-b704-458f-9880-db891e3a23f6.png)

**Comment by lietu** [comment]
Either way the reproduction steps should be pretty simple

1. Install and run Fraps - seems enabling the FPS indicator is not necessary, just having it running is enough
2. Try to launch Windows Terminal
3. Crash

**Comment by lietu** [comment]
Looks like this has been fixed.

**Comment by lietu** [comment]
And after what I guess is a reboot it's back.
