### ISSUE TITLE
Unify pane splitting and new tab creation

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#11021]
In my eyes, spawning a new tab is a special case of splitting a nonexistent window into one pane.

Right now, we have a lot of divergence between opening a tab (1) and opening a pane (2); in both cases we spawn a new control, but the way it gets propagated into the tree is vastly different. The same applies for duplicating an active pane; ~the code in pane splitting suggests that duplicating a pane keeps the working directory but a tab does not (!) (see 3)~ EDIT: No, we accounted for it. Double the code, double the places to look 😉

### 1

https://github.com/microsoft/terminal/blob/10992b77a0aafdaf1166493df3d0c044bf8975ea/src/cascadia/TerminalApp/TabManagement.cpp#L242-L272

### 2

https://github.com/microsoft/terminal/blob/10992b77a0aafdaf1166493df3d0c044bf8975ea/src/cascadia/TerminalApp/TerminalPage.cpp#L1391-L1416

<details>
<summary>Collapsed note 3</summary>

### 3

https://github.com/microsoft/terminal/blob/10992b77a0aafdaf1166493df3d0c044bf8975ea/src/cascadia/TerminalApp/TerminalPage.cpp#L1359-L1370

</details>

**Comment by PankajBhojwani** [comment]
Ah I like this

**Comment by zadjii-msft** [comment]
I've meant to do this for so long. The `TabManagement.cpp` PR really highlighted how bad this one is

**Comment by Rosefield** [comment]
The `CreateNewTabFromPane` function that I added as part of move pane to tab could probably be used for this. If you look at `_SplitPane`, you create the profile/control, then in one branch you do the `PreCalculate*` and then `tab.SplitPane` and on the other you just `CreateNewTabFromPane`. That should get you most of the way there, I think.
