### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by hoo29** [microsoft/terminal#11025]
### Windows Terminal version (or Windows build number)

1.9.2107.13002

### Other Software

ubuntu 20.04 LTS on WSL2
nvidia 471.68 drivers
windows 10 education 21h1

### Steps to reproduce

Open Windows Terminal

### Expected Behavior

It Opens

### Actual Behavior

A window very briefly appears (but doesn't seem to render) and then it crashes. The following is in the event log

```
Faulting application name: WindowsTerminal.exe, version: 1.9.2107.13002, time stamp: 0x60edf3e3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process ID: 0xed0
Faulting application start time: 0x01d798dffb5a7eb6
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: ac419911-ee2b-4ffe-a588-009d02877944
Faulting package full name: Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

I have tried:
* Uninstall and reinstall
* Deleting settings.json
* Repair and Reset
* Setting default font to consolas
* everyone's favourite sfc /scannow

Other issues I have found suggest it's a problem with systems that have integrated and nvidia GPUs but I only have a dedicated NVIDIA GPU, no integrated graphics.

This has been a problem for months but never got round to creating an issue!

Windows feedback link https://aka.ms/AAdl7c0

**Comment by zadjii-msft** [comment]
> Windows Terminal version: **1.9.2107.13002**

> Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal\_**1.9.1942.0**\_x64\_\_8wekyb3d8bbwe\WindowsTerminal.exe

Huh, one of these things is not like the other! What's the output of `wt -v`? It should look like 
![image](https://user-images.githubusercontent.com/18356694/130617550-6721afda-22f8-486c-9271-a467b1fe3d6b.png)
(more or less)


Curiously, the feedback hub dumps also show dumps from a **1.8.1521.0** version of _conhost_, but no `windowsterminal.exe` dumps, which is kinda useless.

I'm thinking that this is a variant of "the app state got torn by the Store" issue. You might have some luck downloading a Preview build off of our Github Releases page. Since you've got the Stable version installed, and that's the one that's seemingly corrupted, then I'd guess that the Preview version wouldn't have the same issue.

**Comment by hoo29** [comment]
I wasn't sure where to get my WT version from so copied it from the log, didn't notice the mismatch! `wt -v` gives 
![image](https://user-images.githubusercontent.com/15928164/130619827-72c15be4-634a-4d5f-b691-c5bea25fcc9e.png)

Uninstalled from the microsoft store and got the latest preview from github releases but it gives a similar log:
```
Faulting application name: WindowsTerminal.exe, version: 1.10.2107.12003, time stamp: 0x60ecd68c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process ID: 0x1604
Faulting application start time: 0x01d798e808b930ad
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.10.1933.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: b52f59fc-263f-4b2a-8a0f-37358c88ffa4
Faulting package full name: Microsoft.WindowsTerminalPreview_1.10.1933.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Is there something I can do differently to make the feedback dump more useful?

**Comment by zadjii-msft** [comment]
Huh. Now that's even weirder. @DHowett any ideas?

**Comment by hoo29** [comment]
Some further investigation, Microsoft PowerToys gives me the exact same error when I try to open the settings page
```
Faulting application name: PowerToys.Settings.exe, version: 0.43.0.0, time stamp: 0x5e222541
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process ID: 0xdbc
Faulting application start time: 0x01d799b68eb0cd0d
Faulting application path: C:\Program Files\PowerToys\Settings\PowerToys.Settings.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: c419a60a-bf62-47c4-b429-801ff1665c6b
Faulting package full name: 
Faulting package-relative application ID: 
```

It runs happily in the background and only produces an error when I try to open settings. Other UWP like Microsoft Store, Mail, and Calculator all work fine though. I did a repair install of `.NET Core 3.1 Desktop Runtime (v3.1.15) - Windows x64` just in case but no difference.

Appreciate this now seems more like a system problem than a Windows Terminal issue but would welcome any suggestions.

**Comment by hoo29** [comment]
Shall do - hopefully they respond!

**Comment by MrM40** [comment]
You might try to Windows 11 version of Window Terminal on Windows 10!
See https://github.com/microsoft/microsoft-ui-xaml/issues/5766
