### ISSUE TITLE
Mouse actions are not forwarded to git bash

### ISSUE THREAD

**Issue by numEricL** [microsoft/terminal#11038]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Git bash, mintty 3.5.0 (x86_64-pc-msys) [Windows 18363]

### Steps to reproduce

Add git bash to wt  and launch (command line is  `"%PROGRAMFILES%\git\bin\bash.exe" --login -i -l`)
Open vim and enable mouse `vim -u NONE -c "set mouse=a"`
Attempt to scroll

### Expected Behavior

Vim to capture mouse inputs

### Actual Behavior

Mouse inputs are handled by wt, e.g. scrolling affects the wt buffer.

**Comment by zadjii-msft** [comment]
@DHowett wait, does this mean this one is in fact a dupe, or not?

**Comment by DHowett** [comment]
I believe it is! Thanks!

/dup #10321
