### ISSUE TITLE
W and M letters have fonts sizes changed whenever scoop is typed

### ISSUE THREAD

**Issue by scorchgid** [microsoft/terminal#11041]
### Windows Terminal version (or Windows build number)

 10.0.19043.0

### Other Software

https://scoop.sh/ 
Version is unknown.

### Steps to reproduce

Install scoop 
Open terminal in powershell
Type scoop {any scoop command} any other letters and include an 'm' or a 'w'

Steps to reproduce are unknown if this causes the issue.

### Expected Behavior

Text font should all be displayed correctly with correct sizes

### Actual Behavior

'm' and 'w' are out of alignment with other fonts
Please see the image to see a preview. You'll see when I don't type scoop letters are perfectly fine
[Image linl](https://imgur.com/a/kYqxs2W)

**Comment by scorchgid** [comment]
Hi @zadjii-msft apologise I lost the link to this issue but found it again/ 
To answer your question the font is set to Campbell
Please see uploaded image. Any suggestions on a fix?

![image](https://user-images.githubusercontent.com/6419740/132251214-efb4d3b5-5c11-4057-8ac2-eb605247c4fa.png)

**Comment by zadjii-msft** [comment]
@scorchgid There's more info in #11032 - looks like this might be a busted MSIX install, where it didn't deploy the font correctly. I'm betting that repairing the app might just do the trick, or worst case setting the font to something else.
