### ISSUE TITLE
Color scheme preview via command palette and settings reload resets zoom level

### ISSUE THREAD

**Issue by fran-f** [microsoft/terminal#11067]
### Windows Terminal version (or Windows build number)

Terminal 1.9.1942.0, Windows 10.0.19043.1165

### Steps to reproduce

- Open Terminal
- Increase the font size with `Ctrl-+`
- Open the command palette with `Ctrl-Shift-P`
- Find "Select color scheme" and hit `Enter` to show the scheme list

As soon as the first color scheme is previewed, the zoom level is reset.

### Expected Behavior

I would expect the zoom level to be indipendent from color schemes. Previewing or applying a new scheme should not reduce or increase the font size.

### Actual Behavior

The color scheme preview affects the zoom level. Backing out of the menu will not revert this change.

**Comment by zadjii-msft** [comment]
I don't think I ever filed anything like that. Turns out I'm probably gonna blow this all up anyways while working through an element of #5000, so I'm just gonna throw this on me for 1.12.
