### ISSUE TITLE
Allow terminal to be integrated in IDE

### ISSUE THREAD

**Issue by tblaudez** [microsoft/terminal#1106]
# Integration in IDE
cmd.exe and other terminals can be integrated in IDE like Visual Studio Code or JetBrains distribution.
However it looks like the new terminal does not support that feature. 

# Expected result
The terminal is fully integrated in the application
![image3](https://user-images.githubusercontent.com/39059500/58761291-eeaa8880-8542-11e9-9dbf-e9bf2faf0101.png)

# Actual results (Jetbrains' Pycharm)
At least in Jetbrains' Pycharm, the terminal just open in a new terminal window after I set **wtd** to be the integrated application. Plus, said window opens in default directory and not the directory I'm  working on
![image1](https://user-images.githubusercontent.com/39059500/58761214-fc134300-8541-11e9-8e2b-57c909a0d3bd.png)
![image2](https://user-images.githubusercontent.com/39059500/58761215-003f6080-8542-11e9-82a6-510455f8edd1.png)

**Comment by karliss** [comment]
Please read about difference between a terminal emulator and shell.

**Comment by phuclv90** [comment]
cmd and powershell are shells that will connect to some terminals while running. The default terminal in Windows is conhost.exe (or csrss.exe in older Windows). The command window in IDEs are also terminals. Similarly Windows terminal itself is a terminal, too. It's not a shell so you can't use it in other apps

- [What is the difference between shell, console, and terminal?](https://superuser.com/q/144666/241386)
- [What is the difference between Terminal, Console, Shell, and Command Line?](https://askubuntu.com/q/506510/253474)

**Comment by tblaudez** [comment]
Well, I thought it was possible to integrate a terminal in an application (like nested windows).
If I understood correctly, IDEs have their own built-in terminal and wait for a shell to be called, is that it  @phuclv90 ?
Guess I can close the issue now...

**Comment by DHowett-MSFT** [comment]
It's part of our long-term strategy to offer the terminal as an embeddable component, but this isn't the way it's going to work. Additionally, JetBrains can take a dependency on the [pseudoconsole API](https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session) and in so doing host a terminal in the same way we do.
