### ISSUE TITLE
Setting Buffer Size to Windows Size will crash console in extreme cases.

### ISSUE THREAD

**Issue by cmcmarrow** [microsoft/terminal#11072]
### Windows Terminal version (or Windows build number)

10.0.19043.1165

### Other Software

NA

### Steps to reproduce

Have a simple app that will set the buffer size to window size right after any resize. Then use the cursor to grow and shrink the window constantly for 15 - 30s. Holding F11 does the trick too.

### Expected Behavior

Console should not crash if someone resizes window in a playful way with cursor. 

### Actual Behavior

When you use the cursor to grow and shrink the window constantly for 15 - 30s console will crash.

**Comment by j4james** [comment]
This sounds like something that could have been fixed by PR #8309, but that fix may not be included in the main release of Windows yet. Can you provide the actual code for the test app that you're using to reproduce this?

**Comment by zadjii-msft** [comment]
A feedback hub dump might be useful in figuring out the stack trace that's the root cause here. /feedback

**Comment by cmcmarrow** [comment]
@j4james 

Garbing and resize the window from any side can result in a crash but the crash seems to favor the left side of the window.
```
#include <Windows.h>


int main(){
    while (true) {
		HANDLE handle = GetStdHandle(STD_OUTPUT_HANDLE);
		CONSOLE_SCREEN_BUFFER_INFOEX console_info;
		console_info.cbSize = sizeof(console_info);
		SHORT w, h;
		//Sleep(1);
		if (GetConsoleScreenBufferInfoEx(handle, &console_info)) {
			w = console_info.srWindow.Right - console_info.srWindow.Left + 1;
			h = console_info.srWindow.Bottom - (console_info.srWindow.Top - 1);
			if (w != console_info.dwSize.X || h != console_info.dwSize.Y) {
				SetConsoleScreenBufferSize(handle, COORD{ w, h });
			}
		}
    }
}
```
I found this bug when I was extending Python with C which causes python to crash with no stack trace. But in visual studio the console crashes and the program just hangs. When I kill the program and try to run it again I get this V. Which I need restart VS to get the program to start again.
```
The application was unable to start correctly (0xc0000142).
Click Ok to close the application.
```
Also adding a `Sleep(1)` in the loop greatly lowers the odds of a crash.

**Comment by j4james** [comment]
@cmcmarrow Thanks for the test case. I can now reproduce the crash fairly easily in the conhost build that comes with my Windows (version 10.0.18363.1500). However, if I run that test in a recent build of OpenConsole it works fine. So I think it's safe to assume that this bug has already been fixed.

**Comment by cmcmarrow** [comment]
@j4james thanks
