### ISSUE TITLE
[Terminal] Settings select panels do not conform to pane when scrolling

### ISSUE THREAD

**Issue by DiamondMiner88** [microsoft/terminal#11079]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

- Open settings
- Click Default Profile/Launch Size/Rows
- Scroll either up or down

### Expected Behavior

Conform to the window boundaries or close when going past.

### Actual Behavior

Panel will go outside the entire window and continue until clicked

![ddddfdd](https://user-images.githubusercontent.com/33725716/131267294-664a4716-0ec8-43b4-8818-721e85989cee.gif)

**Comment by j4james** [comment]
I think this is already being tracked in issue #9320.
