### ISSUE TITLE
Distros should use their Microsoft Store/Appx icon by default

### ISSUE THREAD

**Issue by MatiasLGonzalez** [microsoft/terminal#11089]
# Description of the new feature/enhancement

The Windows terminal should grab the icon that distro Microsoft Store app or appx/appxbundle provides to better identify it on the tabs, i.e:

![imagen](https://user-images.githubusercontent.com/48534497/131529359-715f8268-6d0f-4ea5-8074-f290c8abe7c9.png)
I can't tell which distro is which at a glance, this would be also helpful in WSLg to identify on which distro the application is running.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
That's a great idea! However, we can't get at the icon for a distro all by ourselves. Fortunately though, distro maintainers are free to customize the settings of the profiles for their distros however they like. They can use [fragment extensions](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions) to change the icon, the color scheme, the font, whatever they want! 

See also: https://github.com/microsoft/terminal/issues?q=is%3Aissue+distro+icon

/dup #8604
/dup #1690
