### ISSUE TITLE
"App Paths" keys, "WT" app alias, Win+R dialog?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#11098]
Today I updated Windows Terminal (both release and preview).  At least one of those installations wrote a "wt.exe" subkey in "App Paths" (both in HKCU amd HKLM).  And now I find what I have found in the past, namely, that the app alias "wt" only works in the Win+R dialog if target of the alias matches what's in the "App Paths\wt.exe" key  (i.e., both release or both preview); if they don't match I get a "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

Can anything be done about that?

Things work well here (Win+R included) if I just delete the "App Paths\wt.exe" keys altogether.  Does anything actually need those keys?  The app alias mechanism together with the PATH entry for AppData\Local\Microsoft\WindowsApps seems to be sufficient

**Comment by zadjii-msft** [comment]
This is basically the whole bucket of work that's being tracked by https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3ACulprit-Centennial. I know that's not really anything specific. We need to do some work de-duping those issues. 

We're pretty actively engaged with the MSIX team about trying to remedy issues on this front.

**Comment by vefatica** [comment]
Does anything **need** the App Paths mechanism?  I fare quite OK without it.

**Comment by DHowett** [comment]
We didn't opt in to having an App Paths key set for us. Unfortunately, this was given to us "for free" thanks to the MSIX platform, and we cannot opt _out_ of it.

**Comment by vefatica** [comment]
> and we cannot opt out of it.

Do you mean it's just part of the (software) system and the system doesn't offer a "don't do it" option, or are you forbidden from deleting those registry keys at some later time?

**Comment by zadjii-msft** [comment]
That's correct, this is just part of the OS behavior. I'd rather not go messing with undocumented parts of the MSIX infrastructure, in case those reg keys actually are important for something we don't fully understand, or are used in the future for something.

**Comment by zadjii-msft** [comment]
Hey so I reached out to the app execution alias team - they suggested:

> they could try disabling and then re-enabling the app execution alias from Settings->Apps>Apps & Features>More settings>App execution alias page for the app. I think this should solve their problem.

There was also a fix recently in this area, which Windows build are you on again?

**Comment by vefatica** [comment]
I'm on 10.0.19043.1288 (2009, 21H1).

I gave up on it for a while.  I uninstalled both and have two unzipped only installations with my own AppPaths entries "WTHere" context menu entries.  I know I'm missing some features but since I don't know what they are I'm not missing them much.

**Comment by zadjii-msft** [comment]
Alrighty then.
