### ISSUE TITLE
Add support for Acrylic and Opacity in "Unfocused Appearance"

### ISSUE THREAD

**Issue by jolsen71** [microsoft/terminal#11092]
Please add "Acrylic" setting support to unfocused appearance options being introduced in PR #10317 

I'd really like to make my unfocused windows to have transparency instead of opaque. Ideally, I could make my unfocused windows more transparent than my focused window.

Right now, since unfocused windows are opaque, they appear more predominant on the desktop than the focused window appears when configured with acrylic enabled and semi-transparent.

**Comment by zadjii-msft** [comment]
You know, we don't have an issue tracking this specific task, so congratulations, _this is now that thread_.

We need to first do #7158 to allow unfocused windows to have acrylic at all. Once that's done, we can add it back to the `Appearance` object and the `unfocusedAppearance` settings.

**Comment by LoneDev6** [comment]
This is the only reason why I keep using the old-school cmd and powershell, they don't offer acrylic transparency but their transparency is better because it's always enabled.
I really hope this feature will be added, thanks everyone.

![immagine](https://user-images.githubusercontent.com/27242001/141379571-45c5c150-fd1f-4d84-8883-7600da0d4d7d.png)

**Comment by DHowett** [comment]
@LoneDev6 you're probably interested in https://github.com/microsoft/terminal/issues/1753#issuecomment-950277817.

**Comment by zadjii-msft** [comment]
And just #603, #11180 in general

**Comment by plastikfan** [comment]
Yeah, I much agree with this issue. I love the transparency functionality, but seems to have been implemented the wrong way around. When the window loses focus, then I would expect transparency to become effective, becoming opaque when the window gains focus so you can see text more clearly. And perhaps we could have define different opacity levels depending on focus state; so typically one would set a higher opacity level when the window gains focus.

**Comment by ZeChArtiahSaher** [comment]
UI devs at MS I think I just don't understand digital design to this day

**Comment by zadjii-msft** [comment]
x-linking https://github.com/microsoft/terminal/issues/7158#issuecomment-1162080143

**Comment by Jaswir** [comment]
This is also not working for normal transparency (not acrylic) 
![Focussed-Unfocussed-Opacity-NotAcrylic](https://github.com/microsoft/terminal/assets/15957528/55342018-c2b4-412e-8531-ec16977fd717)

![image](https://github.com/microsoft/terminal/assets/15957528/2fe1833c-471b-4c57-bfaf-5535e1b24ed1)

**Comment by Jaswir** [comment]
A hero has arrived 😎
![image](https://github.com/microsoft/terminal/assets/15957528/3f6868f1-d261-4b84-8066-1b81ea6c2808)

**Comment by Jaswir** [comment]
Will keep you up to date with the progress!

**Comment by radonn24** [comment]
Yes!

# 🥳

**Comment by Jaswir** [comment]
Unfocused windows more transparent than focused window: 
![unfocused_opacity](https://github.com/microsoft/terminal/assets/15957528/19e4cdfe-53d8-4f8d-9870-219fd16f7231)

Code is buggy though, working through some bugs.

**Comment by Jaswir** [comment]
@zadjii-msft @users 
Also, with unfocused Opacity, this brings some new questions to the table:

What should happen when one Adjusts the Opacity through CTRL+SHIFT+Mouse Scroll Wheel 
or through "Set background Opacity" in Command Pallete.
And then makes the window unfocused and focused again.

Should it use the focused opacity in settings and revert to that?
Should it keep the adjusted opacity when it becomes focused again? 

If it keeps the adjusted opacity how should that work? It could use a separate focused value while that terminal window is open and once the terminal restarts the focused opacity in settings becomes active again. 

Or there could be alternative solutions.

**Comment by Jaswir** [comment]
@jolsen71 

> I'd really like to make my unfocused windows to have transparency instead of opaque. Ideally, I could make my unfocused windows more transparent than my focused window.

I think this one about covers it: 
![jolsen](https://github.com/microsoft/terminal/assets/15957528/811191fe-c3bd-4dbf-b44e-c4c2ce577c47)
