### ISSUE TITLE
SSH Timeout?

### ISSUE THREAD

**Issue by markolbert** [microsoft/terminal#11099]
I keep running into a situation where I have successfully logged into a remote shell via SSH, used it for a while, stepped away for a couple of minutes...only to find the Terminal window unresponsive to the keyboard. The only thing I can do is close the window (not via exit, the keyboard doesn't "work") via a mouse click and then start a new window. 

Needless to say, this is extremely annoying :).

Is there some kind of timeout setting in Terminal that I need to adjust? If so, where is it?

**Comment by zadjii-msft** [comment]
> unresponsive to the keyboard. The only thing I can do is close the window (not via exit, the keyboard doesn't "work")

Out of curiosity, does <kbd>ctrl+shift+w</kbd> to close the tab still work?

I believe you can configure `ssh` to have a timeout itself. [This post](https://unix.stackexchange.com/questions/150402/what-is-the-default-idle-timeout-for-openssh) looks relevant.

**Comment by markolbert** [comment]
Thanx, that helped. Kind of confusing to not be able to set the timeout on the client but so it goes.
