### ISSUE TITLE
Command Palette should filter out duplicates (and perhaps move the new dupe to the top of the list)

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#11093]
This is somewhat long:

![image](https://user-images.githubusercontent.com/189190/131558778-14ea909d-f073-4c0d-82d8-43b4f7844d98.png)

In the future, we can weight them by frecency, but that'll be a separate workitem :smile:

**Comment by Don-Vito** [comment]
@DHowett - I will do it.

**Comment by DHowett** [comment]
> @DHowett - I will do it.

Yay!
