### ISSUE TITLE
Windows Terminal does not support inline images

### ISSUE THREAD

**Issue by tsafin** [microsoft/terminal#11104]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

Windows 10 10.0.19043.1200,
WSl2 4.19.84-microsoft-standard
curl

### Steps to reproduce

```
curl v3.wttr.in/Moscow.sxl
```

Doesn't show much in Windows Terminal:

![image](https://user-images.githubusercontent.com/4956130/131638780-4634861e-69f2-4373-9c25-926f7df70c38.png)

while it's showing meteo map using inline images generated by v3.wttr.in if terminal supports inline images (e.g. in uxterm, mlterm, kitty, wezterm, aminal, yaft, iterm2, mintty etc.)

![image](https://user-images.githubusercontent.com/4956130/131639006-1d6f3cdc-2006-47b6-823e-21c380ca048f.png)

### Expected Behavior

Inline images supported by Windows Terminal

### Actual Behavior

Inline images skipped and not rendered at all.

**Comment by tsafin** [comment]
Also, even if there is no inline images used, cloud emojis rendered incorrectly. I see in Windows TErminal:

![image](https://user-images.githubusercontent.com/4956130/131641034-a01b9d87-950c-49fd-8861-21a0cfd1ca4a.png)

while it should all fit to the box as:

![image](https://user-images.githubusercontent.com/4956130/131641115-0904af66-b1a9-47d3-b3d2-e81c1bbf3b12.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22inline+images%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #448 for more discussion.

/dup #448

The weather glyph issue is a combo of /dup #1472 and #8000
