### ISSUE TITLE
Opening new instance of CLI apps opens new window in Windows terminal instead of opening a new tab in the existing window

### ISSUE THREAD

**Issue by rounk-ctrl** [microsoft/terminal#11102]
### Windows Terminal version (or Windows build number)

10.0.22000.168, 1.11.2421

### Steps to reproduce

Open a new instance of Windows Terminal
Set default terminal application as Windows Terminal
Open CLI app (like command prompt, powershell) from start 
See that it opens a new window instead of new tab

### Expected Behavior

Open the specific app in a new tab of the existing instance

### Actual Behavior

Opens in a new window

**Comment by DHowett** [comment]
This is controlled by the following setting:

![image](https://user-images.githubusercontent.com/189190/131718860-ad29a0db-3e74-48cb-9b90-d47979c49d68.png)


It is on the "Startup" page!

**Comment by rounk-ctrl** [comment]
Oh Ok but IMHO by default it should open a new tab
