### ISSUE TITLE
Settings should refer to Notification Area by correct name (not ‘tray’)

### ISSUE THREAD

**Issue by idg10** [microsoft/terminal#11101]
# Description of the new feature/enhancement

Settings that use the word 'tray' to refer to the notification area of the Windows taskbar should use the correct name (i.e. 'notification area'.)

As Raymond Chen pointed out almost 2 decades ago:

> One of the most common errors is to refer to the Taskbar Notification Area as the “tray” or the “system tray”. This has never been correct. If you find any documentation that refers to it as the “tray” then you found a bug.

See his blog for details:
https://devblogs.microsoft.com/oldnewthing/20030910-00/?p=42583

# Proposed technical implementation details (optional)

Preview 1.11 has introduced new settings called `minimizeToTray` and `alwaysShowTrayIcon`. These should be renamed to `minimizeToNotificationArea` and `alwaysShowNotificationIcon` respectively before this feature ships. Documentation for related features should replace all mention of the 'tray' with the correct term: 'notification area'.

**Comment by zadjii-msft** [comment]
You're technically correct, the best kind of correct. That being said, the time for this comment was _before_ we shipped the setting. We can't really change the name of the setting without breaking folks now. Fortunately, the way it's been exposed in the Settings UI (see https://github.com/microsoft/terminal/pull/11070/files#diff-8dc8472b6467fd19c90a98b3a80ef6d300516ebcb09c43ad38a8ddfc3da74aaf) has already been updated to say "Notification Area"

**Comment by idg10** [comment]
>the time for this comment was before we shipped the setting

I posted this comment 1 day after Preview 1.11 was announced. Just how short is your window between announcing a preview the relevant feature shipping?

Or are these settings not as new as the blog at https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-11-release/ suggested?

**Comment by DHowett** [comment]
> Just how short is your window...

There's a 6-week delay (usually) between features shipping in preview and them showing up in stable. In this case, I do believe that there's no need for setting portability between stable and preview... especially because the notification area icon is gated to be in preview only.

That having been said, letting slip a colloquialism once in a while hasn't always killed a project. :smile:

**Comment by zadjii-msft** [comment]
This was merged in #11219, but the bot decided not to close it?
