### ISSUE TITLE
newTab with out-of-range profile index uses the default profile

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#11114]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

1. Uninstall and reinstall Windows Terminal, to delete any custom settings.
2. Start Windows Terminal.  It opens a tab with the PowerShell profile.
3. Open the new-tab dropdown list and note it lists five profiles
   | | |
   |---|---|
   |Windows PowerShell|Ctrl+Shift+1|
   |Command Prompt|Ctrl+Shift+2|
   |**PowerShell**|Ctrl+Shift+3|
   |Debian|Ctrl+Shift+4|
   |Azure Cloud Shell|Ctrl+Shift+5|
4. Close the new-tab dropdown list.
5. Press Ctrl+Shift+9.

### Expected Behavior

No tab opens, because there are fewer than nine active profiles.  Perhaps it beeps instead.

### Actual Behavior

A new tab opens with the PowerShell profile.

**Comment by DHowett** [comment]
Hmm. I likely regressed this in the change to profile resolution...

**Comment by zadjii-msft** [comment]
Oh wait, this isn't a regression. Even in #10982 this worked this way. OP is reporting this in 1.9, and the profile resolution changes only started in v1.11.2421.0. 

I'm un-blocking this one, and tossing into 2.0, discussion. 

* How breaking do we think it is if  
  ```json
  { "command": { "action": "newTab", "index": 999 } },
  ```
  does nothing instead? 
* Is there someone out there relying on <kbd>ctrl+shift+9</kbd> to launch their default profile (despite only having two profiles)
* This is kinda like "pass through move-focus keys when there aren't any panes"

It's easy enough to change this, but we'll need to think for a second about this.
