### ISSUE TITLE
Search in Git/mingw nano mangles text ("←[?1h")

### ISSUE THREAD

**Issue by xnoreq** [microsoft/terminal#11110]
### Windows Terminal version (or Windows build number)

10.0.19043.0, 1.11.2421.0

### Other Software

Git-2.33.0.2-64-bit with support for pseudo-consoles enabled

### Steps to reproduce

```
echo asdf > test.txt
nano test.txt
```

Now press Ctrl+W (search), enter "asdf" (without quotes), press return.

### Expected Behavior

No change to text in nano.

### Actual Behavior

"asdf" is replaced by "←[?1h". After a second, the text automatically changes to "←[?1hasdf". Pressing right reveals "asdf" character by character.

Pressing right once before the second has passed results in "a[?1h←[?1h←[?1h←[?1hasdf".

**Comment by DHowett** [comment]
This is the classic behavior of an application that has told us to _stop handling escape sequences_. I'm guessing it's either nano or the MSYS2 runtime (Cygwin)...

**Comment by zadjii-msft** [comment]
Oh look, the dupe from the backlog: /dup #9312

**Comment by zadjii-msft** [comment]
Which might also be #4921
