### ISSUE TITLE
Profiles missing after resetting config

### ISSUE THREAD

**Issue by ktremain** [microsoft/terminal#11119]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

1. have terminal ver 1.9 with default profiles including powershell/WSL/Azure shell
2. upgrade to v1.10
3. open settings.json
4. delete contents of file and save
5. reload terminal

as per notes at top of config file, i wanted to ensure that i had any new defaults now that v1.10 has been released
  "..It should still be usable in newer versions, but newer versions might have additional
  settings, help text, or changes that you will not see unless you clear this file
  and let us generate a new one for you."

### Expected Behavior

expected that all default profiles get regenerated

### Actual Behavior

only "windows powershell" and "Command prompt" appear. 

Also note that terminal did infact launch "powershell" (v7.1.4) and had an empty dropdown in the "default profile" box in settings as what was launched did not have any profile.

I had to reset the app to restore all my profiles

**Comment by zadjii-msft** [comment]
HMMMMMM This is a good point. In 1.11 (and backported to 1.10), we added the ability to just delete dynamic profiles from the settings, and have them not auto-regenerate. But if you totally blow away the settings file, that's kinda a different case now. 

@DHowett @lhecker for discussion: if `settings.json` is _totally empty_, or missing, should we clear out `state.json` too? Or is that just a bad heuristic? Is there a reason we would want to keep `state.json` even if they blow away their settings?

**Comment by lhecker** [comment]
> @DHowett @lhecker for discussion: if settings.json is totally empty, or missing, should we clear out state.json too?

Sounds good to me actually.
