### ISSUE TITLE
Windows Terminal is missing in Default Terminal Host dropdown

### ISSUE THREAD

**Issue by Mr1008** [microsoft/terminal#11120]
### Windows Terminal version (or Windows build number)

10.0.22000.0 - Build 168

### Steps to reproduce

1. Go to Settings and open `Default terminal application` dropdown.
2. See there is no `Windows terminal` to select and only `Windows Console Host` is available

### Expected Behavior

I should be able to select Windows Terminal as default terminal application

### Actual Behavior

After recent update I can find option to select default terminal in Settings page. Unfortunately there is no Windows Terminal option available. The only option is `Windows Console Host` (See screenshot below).

I tried repairing and resetting app but no luck.

Also, I cannot see Windows Terminal option in dropdown available in old conhost settings. Only `Windows Console Host` is available.

![image](https://user-images.githubusercontent.com/1630067/131825118-2244a315-5a44-4675-8ed8-05c6ab9062cc.png)

![image](https://user-images.githubusercontent.com/1630067/131825170-e04b82c7-f5f4-40bb-94a4-13741634407d.png)

**Comment by zadjii-msft** [comment]
That's correct, you'll need to use the Preview version of the Windows Terminal in order to be able to set it as the default Terminal application.
