### ISSUE TITLE
Be nice if quake mode shorcut launched the app.

### ISSUE THREAD

**Issue by b-hayes** [microsoft/terminal#11129]
# Description of the new feature/enhancement
Would be nice if the quake shortcut launched the app if it wasn't running.
OR if the app could start in quake mode when start with windows is enabled.

I started liking quake mode on my small laptop its the best way to have it.
However, to get it working I have to open an instance of the terminal first, hit the quake mode shortcut and then close the first terminal instance.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
You could technically create your own shortcut that runs the commandline args to summon a quake window. Just make a cmd batch or powershell ps1 script that executes the command and then exits itself.

**Comment by j4james** [comment]
I believe this is already being tracked in issue #9996.

**Comment by b-hayes** [comment]
> You could technically create your own shortcut that runs the commandline args to summon a quake window. Just make a cmd batch or powershell ps1 script that executes the command and then exits itself.

Good idea, if you know the command to launch a new instance in quake mode that would be great.

**Comment by zadjii-msft** [comment]
Yep, this is /dup #9996.

The command you're looking for is `wt -w _quake`
