### ISSUE TITLE
Settings syncing with OneDrive

### ISSUE THREAD

**Issue by josh-65** [microsoft/terminal#11132]
# Description of the new feature/enhancement
It's possible to do it manually but it takes time and can have missing settings if the user doesn't remember to update/restore them. Syncing with One Drive like Power Automate does would be quite helpful for me.

# Proposed technical implementation details (optional)

Use OneDrive apps folder sync upload and restore the settings.json file terminal uses like power automate.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
