### ISSUE TITLE
Behavior change when call wt

### ISSUE THREAD

**Issue by zimbres** [microsoft/terminal#11136]
### Windows Terminal version (or Windows build number)

1.11.2421.0

### Other Software

KeePass
SSH

### Steps to reproduce

At URL Overrides of KeePass I use this command:

cmd://wt -w 0 nt ssh {USERNAME}@{URL:RMVSCM}

### Expected Behavior

An wt PowerShell window or a new PowerShell table if a windows is already open executing the command ssh to defined host.

### Actual Behavior

An wt SSH window or a new SSH table if a windows is already open executing the command ssh to defined host.

**Comment by WSLUser** [comment]
If you establish a SSH profile, it's expected to run ssh.exe directly and bypass w shell as it will open a shell in the remote environment (such as bash). You could create a powershell profile with the commandline option of ssh if you want but that's just unnecessary overhead. This behavior hasn't changed so likely something in your settings changed.

**Comment by DHowett** [comment]
@WSLUser I believe the report is, "`wt -w 0` no longer uses the existing window" :smile:

**Comment by WSLUser** [comment]
I saw SSH and see description regarding SSH and didn't realize it had nothing to do with SSH. A simpler repro would have been nice.

**Comment by zimbres** [comment]
I dont have any SSH profile.
Befere, calling "wt -w 0 nt ssh" opens a PS windows e execute ssh in PS, now opens a ssh window...

**Comment by zimbres** [comment]
I realize now a "Defaults" Profile, is this existing before? My command is now calling this profile instead of Windows Power Shell Profile.

**Comment by DHowett** [comment]
**OH**. So it _does_ open in a new tab in the same window.

In 1.11, we changed the behavior of "nt" so that it uses a base profile that doesn't have any special customizations -- this is because it was confusing for users. In 1.10, if you run "wt cmd" you get a Command Prompt window, but the title says PowerShell and the icon is PowerShell.

**Comment by zimbres** [comment]
Got it. Tks.
