### ISSUE TITLE
v1.10.2383.0 update missing on Microsoft Store on Windows 10

### ISSUE THREAD

**Issue by dckface** [microsoft/terminal#11131]
### Windows Terminal version (or Windows build number)

Terminal v1.9.1942.0, Windows 10 Pro 21H2 (build 19044.1202)

### Other Software

Microsoft Store (version 12107.1001.15.0)

### Steps to reproduce

1. Open Microsoft Store.
2. Check for updates.
3. Observer no update for Windows Terminal to version v1.10.2383.0.
4. Verify that running "winget upgrade" correctly shows that new Windows Terminal version is available.

### Expected Behavior

The WT is expected to be updated by Store on given Windows 10 version.

### Actual Behavior

The Store version is stuck on 1.9.1942.0, while all other apps update correctly, and on my Windows 11 device the Terminal also updates correctly. 

Also, after searching Terminal in Store, it also shows old version.
![image](https://user-images.githubusercontent.com/3797371/132009175-0fd00eb9-d10d-4dfb-a3e1-a86605836106.png)
The version reported by winget is correctly v1.10.2383.0.

**Comment by DHowett** [comment]
Because the stable version is now a component of Windows, we've started rolling out updates to it more slowly. Folks in the dev and beta channels will see the new stable updates first, and those in normal channels will see the update after approximately a week. 😄

**Comment by DHowett** [comment]
(Thanks for the report!)

**Comment by dckface** [comment]
Ah, alright, I wasn't aware of that :) My main PC was forced from beta channel into release preview, since I lack the TPM chip on my main machine, so I guess that's why I still don't have it. Anyway, thanks for clarification :)

**Comment by Uxorious** [comment]
Is there no way to get individual apps from the store without switching the whole PC into one of the early release streams?
I would like to update Terminal, but I don't feel like being on the bleeding edge for the rest of Windows.

**Comment by DHowett** [comment]
You can download any version of Terminal -- past, present and future -- on our [releases page](https://github.com/microsoft/terminal/releases) :smile:

**Comment by Uxorious** [comment]
That was much easier than expected.
Thanks!
