### ISSUE TITLE
Text input fields in Settings have autocorrect enabled (oops)

### ISSUE THREAD

**Issue by joslinpr** [microsoft/terminal#11133]
### Windows Terminal version (or Windows build number)

Windows 10 ECB 9.0 SAC 20H2 / Windows Feature Experience Pack 120.2212.551.0

### Other Software

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

#### Under General,  type into command line:
```C:\Windows\System32\OpenSSH\ssh.exe -A -i C:\Users\username\.ssh\id_rsa user@hostname``` 
#### What you get is:
``` C:\Windows\System32\OpenSSH\ssh.exe -A ```**-I**``` C:\Users\username\.ssh\id_rsa username@hostname```

Note the capital I.  This does not occur when you cut and paste, but will if you remove the "I" and type "i".

If you use the new profile, you get the unexpected error "no support for PKCS#11." from ```ssh.exe```.

### Expected Behavior

What you type is what you get.

### Actual Behavior

Autocorrect changes -i to -I, leading to an error message.

**Comment by DHowett** [comment]
Jeez-o, we should not have autocorrect enabled on our input fields!

**Comment by ianjoneill** [comment]
This looks easy to fix - I assume you'd like to keep autocorrect enabled in text-boxes for names (e.g. profile name, tab title), but not for paths/command lines etc.

**Comment by elsaco** [comment]
Why is only "-i" being capitalized? The first option "-A" won't be autocorrected if type "-a".
