### ISSUE TITLE
SSH Profiles

### ISSUE THREAD

**Issue by iAmG-r00t** [microsoft/terminal#11141]
Quick question, can we have a feature that allows one to add SSH profiles, where the profile can have an option for either password auth or public-key authentication.

I just thought this will be an amazing feature because the OS has ssh protocol.

**Comment by WSLUser** [comment]
See https://docs.microsoft.com/en-us/windows/terminal/tutorials/ssh

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. 

We're focusing on making a great local terminal experience first and foremost -- and I think that anything we do internally would naturally play second fiddle to that. You're absolutely free to make profiles for ssh connections yourself, though we're not going to be building in password management or other authentication management to the Terminal itself. 

/dup #4653

**Comment by iAmG-r00t** [comment]
Okay, that makes sense thank you
