### ISSUE TITLE
Open terminal here fail to open in the right directory if it contains specific characters

### ISSUE THREAD

**Issue by notagainbutyeah** [microsoft/terminal#11149]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Try to right click - open in terminal - in a directory that contains as example "[" in their name.

### Actual Behavior

It opens to C:\> instead of the current directory.

**Comment by notagainbutyeah** [comment]
I manually updated to 1.10.2383.0 but the issue is still there.

**Comment by zadjii-msft** [comment]
![gh-11149](https://user-images.githubusercontent.com/18356694/132345562-490c038d-3e4b-446c-88ae-557ded1515e8.gif)
weird.

What OS version are you on? What shell are you using? What's the exact path you're trying to open in? Could you share your `settings.json`?

**Comment by DHowett** [comment]
This is a bug in Windows PowerShell (5.1) -- sorry! There's nothing that can be done about that. It does not handle directories with special characters in them properly.

**Comment by regs01** [comment]
> This is a bug in Windows PowerShell (5.1) -- sorry! There's nothing that can be done about that. It does not handle directories with special characters in them properly.

Something should be done about it. [] are not illegal path characters in Windows.
