### ISSUE TITLE
Why has the 2019 issue not been fixed so far?

### ISSUE THREAD

**Issue by DemoorBug** [microsoft/terminal#11140]
#603 Why has the 2019 issue not been fixed so far? 

I like the transparency:
![Snipaste_2021-09-04_18-33-57](https://user-images.githubusercontent.com/18387615/132091606-a2f188d0-f9a2-4817-a6e7-a756bcc99907.png)

Don't like "useAcrylic":
![Snipaste_2021-09-04_18-34-09](https://user-images.githubusercontent.com/18387615/132091627-04acbb87-87ab-445d-9a8f-473ec27e745b.png)

**Comment by zadjii-msft** [comment]
If you'd read the thread, you'll find the answer you're looking for: https://github.com/microsoft/terminal/issues/603#issuecomment-644130120

/dup #603
