### ISSUE TITLE
Secondary language always shown as GUI language even with language selection

### ISSUE THREAD

**Issue by Truckland** [microsoft/terminal#11157]
### Windows Terminal version (or Windows build number)

1.11.2421.0

### Steps to reproduce

Install primary language Dutch - NLD
Install secondary language Russian - Rus
Start Terminal - Gui is in Russian, Select Dutch, no change.
Remove Russian, Gui in English again

### Expected Behavior

Expected with primary language Dutch to have English UI

MAYBE: Because Dutch is not a standard language in Windows Terminal and Russian is, it skips Dutch and goes to Russian because that's the next language on the system that IS recognized.

### Actual Behavior

Primary language Dutch gave Russian UI.

**Comment by zadjii-msft** [comment]
Sounds to me like this is just a variation on #10667. The Terminal will pick the first language that it's actually available in, and that set might need to be bigger. 


You can manually set the language with the following setting
![image](https://user-images.githubusercontent.com/18356694/132524612-d2542421-47a8-4ad6-9aeb-e94e8159e739.png)

but that only lets you pick from the languages the Terminal is actually available in.

/dup #10667
