### ISSUE TITLE
Package Building Guide

### ISSUE THREAD

**Issue by LanceaKing** [microsoft/terminal#1115]
### Step 1: Clone the repository from github
To clone the repository, you just need to run the following commands.
```cmd
git clone https://github.com/microsoft/terminal.git
cd terminal
git submodule update --init --recursive
```
Then install the prerequisites written in `README.md` .

### Step 2: Find the publisher name
Check `Package-Dev.appxmanifest` which located in `src\cascadia\CascadiaPackage`, and you can find something like this:
```xml
<Identity
  Name="WindowsTerminalDev"
  Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
  Version="0.0.1.0" />
```
Copy the "Publisher" attribute `CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US` .

### Step 3: Create a package signing certificate
Open the "Developer Command Prompt for VS 2019" in start menu, and run following commands with the publisher name:
```cmd
MakeCert -n "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" -r -h 0 -eku "1.3.6.1.5.5.7.3.3,1.3.6.1.4.1.311.10.3.13" -sv CascadiaPackage_TemporaryKey.pvk CascadiaPackage_TemporaryKey.cer
Pvk2Pfx -pvk CascadiaPackage_TemporaryKey.pvk -spc CascadiaPackage_TemporaryKey.cer -pfx CascadiaPackage_TemporaryKey.pfx
```
If asking for password, click "None".  
Then install "CascadiaPackage_TemporaryKey.cer", and store the certificate in Trusted People.

### Step 4: Build
Copy "CascadiaPackage_TemporaryKey.pfx" to `src\cascadia\CascadiaPackage` .  
Open "OpenConsole.sln" (Don't need to retarget), right click the "CascadiaPackage" under "Terminal" in solution explorer, and then click "Store->Create App Packages...".  
Select "Sideloading" and uncheck "Enable automatic updates", and then click "Next".  
Change settings if you like, and click "Create".  

### Step 5: Install
When package building finished, the package and certificate are under `src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_0.0.1.0_Test`.  
And then you can double click to install it. :thumbsup:

**Comment by DHowett-MSFT** [comment]
Thanks for taking the time to produce this guide. We'll be evaluating our deployment strategy in the coming weeks. @bitcrazed
