### ISSUE TITLE
[Settings]: The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#11155]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

**Test Environment:**
OS: Windows 11 Version 21H2 (OS Build 22000.168)
Screen Reader: Narrator
Tool: Accessibility Insights for Windows Version 1.1.1689.01

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Settings page using "Ctrl + ',' ".
3. Run Accessibility insights for Window on Settings 'Startup', 'General', 'Appearance' and 'Advance' tab page and observe the issue for Columns, Rows, Command line, Starting directory, Icon, Font face and Font size controls

**User Experience: -> Priority 1**
Screen Reader user are impacted here as name is announced for control as result, they will not be able to know the purpose of control.

**Guideline Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value

**Attachments:**
[The Name property of a focusable element must not be null..zip](https://github.com/microsoft/terminal/files/7119989/The.Name.property.of.a.focusable.element.must.not.be.null.zip)

### Expected Behavior

The Name property of a focusable element must not be null.

### Actual Behavior

The Name property of a Columns, Rows, Command line, Starting directory, Icon, Font face, Font size and History size focusable element must not be null.

**Comment by zadjii-msft** [comment]
* [ ] Columns, 
   - Startup, Launch Size
 * [ ] Rows, 
   - Startup, Launch Size
 * [ ] Command line, 
   - Profile, General Pivot
 * [ ] Starting directory, 
   - Profile, General Pivot
 * [ ] Icon, 
   - Profile, General Pivot
 * [ ] Font face and 
   - Profile, Appearance pivot
 * [ ] Font size controls
   - Profile, Appearance pivot
 * [ ] History size controls
   - Profile, Advanced pivot

**Comment by zadjii-msft** [comment]
@v-rpundir Can you confirm that this is fixed in 1.12 builds of the Terminal?

**Comment by v-rpundir** [comment]
@zadjii-msft The latest build available our side is **Windows Terminal
Version: 1.11.2921.0** so it repro myside.
When your mentioned build present our side then we will verify and let you the status of this bug.

**Comment by v-rpundir** [comment]
@zadjii-msft @DHowett 

All above mentioned issue are fixed now on Version: 1.12.2931.0 but now the same issue is observed for other controls as per below Error Screenshots. Let me know if you want us to log a separate bug for these issue.

![image](https://user-images.githubusercontent.com/86412703/145666933-2168f42c-71f1-4f3c-86e6-0be6587a0bf4.png)

![image](https://user-images.githubusercontent.com/86412703/145666982-147f678d-64af-4811-988c-c520b1ce5549.png)

![image](https://user-images.githubusercontent.com/86412703/145667112-814d2207-9dbe-4c3f-87b5-67d2f9f7e400.png)

![image](https://user-images.githubusercontent.com/86412703/145667151-c5efa9fa-e5ec-4cd1-9fc4-589232d66d53.png)

![image](https://user-images.githubusercontent.com/86412703/145667189-39b4ae04-3dee-4186-a3e3-55b0a0240477.png)

**Comment by DHowett** [comment]
@v-rpundir because of the issue SLA, it would be best if you file a new issue and close this one. Thanks!

**Comment by v-rpundir** [comment]
Closing this bug and As per Discussion logged new issue https://github.com/microsoft/terminal/issues/11996
