### ISSUE TITLE
Scrolling in WSL vim will scroll the terminal up rather than the text file up

### ISSUE THREAD

**Issue by vincha04** [microsoft/terminal#11169]
When I try to scroll up on a log file (one that is long as well as ones that are short) in vim using a mouse or trackpad, I'm used to the scroll wheel scrolling the cursor in vim. However, in windows terminal, it seems to scroll the terminal history instead. PgUp and PgDn seems to work in regards to scrolling the vim log, but not scroll wheel.

![log1](https://user-images.githubusercontent.com/44007494/132395120-71c74aca-3816-46e9-85ef-37e0d81e4c38.png)
![log2](https://user-images.githubusercontent.com/44007494/132395126-6e6a2d60-a8a4-429e-9c9f-a23d589f27c4.png)

Not sure if this is a setting I'm not setting, or something about windows terminal that I am not setting. May a kind soul help me regain my productivity? :(

Thanks for the help

**Comment by elsaco** [comment]
Add "set mouse=a" to your vim configuration.

**Comment by vincha04** [comment]
> 
> 
> Add "set mouse=a" to your .vimrc file.

Thank you so much. I obviously didnt have strong enough google-fu. This seems so obvious in retrospect.

**Comment by Cricktom** [comment]
I have the same issue and setting the above doesn't help.
