### ISSUE TITLE
The location of settings.json should be configurable so that it can be place in .dotfiles or a soft-link to it

### ISSUE THREAD

**Issue by kasajian** [microsoft/terminal#11167]
I had been putting it off, but now I'm attempting to move from ConsoleZ to Windows Terminal.  One feature that I feel is essential is the ability for me to share my settings across my computers and also share my settings with others, the way .dotfiles are often shared publicly on github.  I have other settings there such as my vim plugins, etc.

So I would like to have a well-known location for settings.json that Windows Terminal uses.  On my computer it's located here: C:\Users\...\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json

The name WindowsTerminal_8wekyb3d8bbwe looks sus.   That seems like it might be a version and/or installation specific.    ConsoleZ's setting had to be in it's own location, but I could use a soft-link to it from my .dotfiles folder. 

My suggestion is to use a common convention of putting such settings in a well known location such as %userprofile%\.windowsterminal\...
or something like that.

If there's another way to solve this, I'd love to know about it.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933

**Comment by DHowett** [comment]
Couple notes before I close this out as a duplicate!

1. The path is based on an intrinsic property of our application package, and is constant for every user and every install (separated by Preview or Stable version)!
2. You can replace settings.json with a symbolic link, and Terminal will keep working just fine. This has worked pretty well for people in the past.
