### ISSUE TITLE
Can't launch Windows Terminal in the Safe Mode of Windows 11

### ISSUE THREAD

**Issue by MouriNaruto** [microsoft/terminal#11164]
### Windows Terminal version (or Windows build number)

Windows 11 (10.0.22000.176) with Windows Terminal 1.10.2383.0

### Other Software

N/A

### Steps to reproduce

The tutorial of Safe Mode: https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234

When you launch your Windows 11 instance to the Safe Mode, you can try to launch Windows Terminal by Win+X menu, Start menu, "wt" in the Command Prompt or "wt" in the Run Dialog and found the issue.

### Expected Behavior

I hope I can use Windows Terminal properly in the Safe Mode like the normal mode.

![NormalMode](https://user-images.githubusercontent.com/10867563/132275853-3551f22f-a55b-4548-8042-6c070c8b67f1.png)

### Actual Behavior

No response when I try to launch Windows Terminal via Win+X menu or Start menu in the Safe Mode.

When I try to launch Windows Terminal via "wt" in the Command Prompt, you will notice "The System cannot execute the specified program." (I have use "chcp 437 before for getting the English translation of the error message in the Command Prompt")

![SafeModeCommandPrompt](https://user-images.githubusercontent.com/10867563/132275884-2612370e-fb7c-4a07-a12e-ba625fe9c773.png)

When I try to launch Windows Terminal via "wt" in the Run Dialog,  it will pop up a window with the content "The media is write protected.".  (I know the error message in the screenshot is Chinese, so I lookup it via the `winerror.h` in Windows SDK, so I know the error code is `ERROR_WRITE_PROTECT` and the error message is `The media is write protected.`.)

![SafeModeRunDialog](https://user-images.githubusercontent.com/10867563/132275899-a0474506-1202-4098-a558-60b0c8665918.png)

Kenji Mouri

**Comment by zadjii-msft** [comment]
Huh. This is a good observation, one I don't think we thought of. I'm gonna bring this up with the rest of the team. Thanks!

**Comment by elsaco** [comment]
This happens on Windows 10 also:

![wt_safemode_launch_error](https://user-images.githubusercontent.com/3933920/132406097-4222f5e8-ea78-4088-93e1-5c7f713a4fd9.png)

When trying to launch WT form a PS prompt it show:
```
PS C:\Users\tux> wt.exe
Program 'wt.exe' failed to run: The media is write protectedAt line:1 char:1
+ wt.exe
+ ~~~~~~.
At line:1 char:1
+ wt.exe
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by DHowett** [comment]
(I've begun the discussion with the MSIX folks!)

**Comment by carlos-zamora** [comment]
Sorry for the radio silence here. After some research and discussion, packaged applications (that includes Windows Terminal) cannot be launched in Safe Mode.

**Comment by SuibianP** [comment]
Hi @carlos-zamora, would you mind sharing more about the discovered root cause of the `ERROR_NO_ASSOCIATION` and `ERROR_WRITE_PROTECT`?
