### ISSUE TITLE
Error 0x800702e4 after installing from Microsoft Store

### ISSUE THREAD

**Issue by superbonaci** [microsoft/terminal#11163]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

Interacts with PowerShell 7

### Steps to reproduce

Install windows Terminal from Microsoft Store.

Launch it, this error appears:
````
[error 0x800702e4 when launching `C:\Program Files\PowerShell\7\pwsh.exe']
````

### Expected Behavior

work as intended.

### Actual Behavior

error when launching.

**Comment by j4james** [comment]
See issue #4272 for a possible explanation.

**Comment by zadjii-msft** [comment]
@superbonaci could you check if this is the same thing as #4272?

**Comment by superbonaci** [comment]
Yeah that's the issue. Launching Windows Terminal from Start menu throws that error, but if I right click -> Run as administrator works as intended.
