### ISSUE TITLE
Snap Layouts on Windows 11

### ISSUE THREAD

**Issue by morethanyell** [microsoft/terminal#11161]
# Windows Terminal version (or Windows build number)
1.10.2383.0

# Other Software
### Test Environment:
OS: Windows 11 Version 21H2 (OS Build 22000.176)

# Steps to reproduce
 - Hover mouse pointer on the maximize button

# Expected Behavior
New Windows 11 Snap Layouts feature to appear as clickable options

# Actual Behavior
No Windows 11 Snap Layouts appearing

**Comment by electronic-dk** [comment]
Duplicate of #9443

**Comment by morethanyell** [comment]
Closing because of #9443
