### ISSUE TITLE
Tab or pane preview when hovering on taskbar (plus activation on clicking) and separation into different taskbar items

### ISSUE THREAD

**Issue by soundnotation** [microsoft/terminal#11166]
# Description of the new feature/enhancement

I'm considering moving from [ConEmu](https://github.com/Maximus5/ConEmu) to WT. A cool feature of ConEmu is that it shows the minimized content of the tabs (or panes) open in one window, upon clicking or hovering on the window icon on the taskbar. If you hover on a subsequent taskbar tab (or pane), a preview of it appears on the screen. If you click on it, the item will be activated.
See the gifs below. I made two examples: one with 4 tabs and one with 4 panes.
The two examples are separated in two different taskbar windows (![image](https://user-images.githubusercontent.com/23723634/132353309-d750d590-e23e-4f73-b140-90b22bc76470.png)), unlike WT which groups every window into one (![image](https://user-images.githubusercontent.com/23723634/132352442-7d16471f-744f-4a6d-a0fb-3abda5a8641b.png)).
Is it possible to have the same behavior in WT, or at least to mimick it?
Sure this is related to [#687](https://github.com/microsoft/terminal/issues/687), but I'm not sure if it's the same request.
# Proposed technical implementation details (optional)

4 tabs example:
&nbsp;
<img src="https://user-images.githubusercontent.com/23723634/132346533-3b23f8dd-7a95-462a-b1e7-226e62f220aa.gif" width="600" />
&nbsp;
4 panes example:
&nbsp;
<img src="https://user-images.githubusercontent.com/23723634/132346575-af2e45b8-2026-422c-8954-5dde1c7dd325.gif" width="600" />
&nbsp;

**Comment by zadjii-msft** [comment]
Yep, this looks like /dup #687 to me
