### ISSUE TITLE
TermControl does not receive enough `_CursorPositionChanged` events

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#11170]
### Windows Terminal version (or Windows build number)

1.12

### Steps to reproduce

1. Start Terminal in debug mode
2. Set a breakpoint at `TermControl::_CursorPositionChanged`
3. Enter some input (without any newlines)

### Expected Behavior

The breakpoint at `TermControl::_CursorPositionChanged` should get hit

### Actual Behavior

The breakpoint does not get hit, it only gets hit when the input contains a newline

**Comment by PankajBhojwani** [comment]
I believe @DHowett had a suspicion for when this may have regressed

**Comment by DHowett** [comment]
Indeed! We stopped doing it when we added position deferral. This results in the IME not tracking the cursor position when it changes within a line.

**Comment by zadjii-msft** [comment]
> This results in the IME not tracking the cursor position when it changes within a line

That sounds... pretty bad actually. Should this be fixed for 1.12 Stable?

**Comment by DHowett** [comment]
Yes, we should. Good catch!
