### ISSUE TITLE
Prompt file system error when starting (12002)

### ISSUE THREAD

**Issue by Smoker2604** [microsoft/terminal#11176]
### Windows Terminal version (or Windows build number)

Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

### Other Software

Domain Computer with Proxy

### Steps to reproduce

Start the Windows Terminal

### Expected Behavior

![2021-09-08 14_13_48-Microsoft Powershell - 06 09 21 bis 09 09 21 - Vinko Grubišić _ Microsoft Teams](https://user-images.githubusercontent.com/29926685/132507372-7a418f6c-4cce-498a-85a1-3378948f130c.png)

### Actual Behavior

Can not start the Windows Terminal.

**Comment by j4james** [comment]
I believe 12002 is an internet timeout error, which makes me think this is probably related to issue #6010.

**Comment by zadjii-msft** [comment]
/dup #6010 this looks like the issue we're already tracking and trying to resolve, but nobody knows what causes it and none of our machines seem to reproduce it.
