### ISSUE TITLE
How to install Unbuntu in WSL with no access to Store?

### ISSUE THREAD

**Issue by jtpryan** [microsoft/terminal#1118]
I don't have access to the MS Store at work.  I have the .deb file for Ubuntu and I enabled the Linux subsystem,  How do I get to it to install Ubuntu?

**Comment by zadjii-msft** [comment]
This is a question that's better suited for the [Microsoft/WSL](https://github.com/Microsoft/WSL) repo. I believe there are instructions in that repo for manually installing a distro locally.
