### ISSUE TITLE
Tab title not updating after closing ssh connection

### ISSUE THREAD

**Issue by MrEmanuel** [microsoft/terminal#11186]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

WSL 2
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020 

### Steps to reproduce

1. Open a new tab or instance of windows terminal. Notice the tab says "Ubuntu" (I'm using Ubuntu with WSL2)
2. ssh to a remote machine 
`ssh my_user@machine_ip_address`
3. Notice the tab title updates to "my_user@machine_ip_address"
4. Exit ssh
`ctrl-d`
5. Notice the tab title is still displaying the remote machine address. "my_user@machine_ip_address"

### Expected Behavior

Expected behavior is that the tab title should update when closing an ssh tunnel to a remote machine. 

### Actual Behavior

The tab title stays locked as the remote machine address, i.e `my_user@machine_ip_address`.

**Comment by MrEmanuel** [comment]
I almost had a heart attack after (correctly) removing a database on my local machine and looking at the Windows Terminal tab (erroneously) telling me I'm still ssh'ed in to the production machine.

**Comment by zadjii-msft** [comment]
> Open a new tab or instance of windows terminal. Notice the tab says "Ubuntu" (I'm using Ubuntu with WSL2)


That would seem to suggest that your local shell in WSL isn't configured to set the tab title. What shell are you using in WSL locally? `bash`, `zsh`, `fish`? 

I know in the stock `.bashrc`, there's the following snippet to set the tab title:

```bash
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```

So if you've modified your PS1 at all, that might not be present anymore.
