### ISSUE TITLE
Non default profiles always opening in home directory

### ISSUE THREAD

**Issue by tanuj-05** [microsoft/terminal#11198]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

Right-click and open windows terminal in a particular directory, for eg D drive and open new tabs of different profiles

### Expected Behavior

Default profiles, as well as other profiles, should open with current working directory set to D:\

### Actual Behavior

Default profile(Powershell in my case) opens in D:\ but **other profiles when opened using new tabs open in the User home directory. i.e., C:\Users\<Username**>

Default profile opens in D drive
![image](https://user-images.githubusercontent.com/36896851/132936822-c9ff1091-e1d5-4c0f-85bb-e5d5f9381d20.png)

New profiles opened using the + button open in C:\Users\<Username>
![image](https://user-images.githubusercontent.com/36896851/132936856-1656a7cb-c521-46d7-8e5f-26ffe7e9a41c.png)

**Comment by elsaco** [comment]
Your answer might be in #11196
