### ISSUE TITLE
[GB18030] Windows Console fails to display double-byte and 4-byte characters

### ISSUE THREAD

**Issue by javierdlg** [microsoft/terminal#11195]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

Visual Studio 2022 integrated terminal

### Steps to reproduce

1. Open a terminal window
2. Type in `①Ⅻㄨㄩ 啊阿鼾齄丂丄狚狛狜狝﨨﨩ˊˋ˙–⿻〇㐀㐁㐃㐄䶴䶵U1[]U2[]U3[]`

### Expected Behavior

Characters are shown correctly

### Actual Behavior

Characters show up as `?` characters but can still be processed by the back-end process:
![image](https://user-images.githubusercontent.com/2334756/132895332-e8271c1c-c74a-4bc6-be9d-ec0709af281f.png)

**Comment by javierdlg** [comment]
Worth noting that this only happens when using the powershell profile (even non-developer flavor) and not with the command prompt so it might be a powershell-specific issue.

**Comment by DHowett** [comment]
This is for sure a powershell issue! The fact that the characters are coming back out in the error message and being displayed properly fully indicates that they can be displayed.

**Comment by javierdlg** [comment]
Thanks Dan, I've forwarded the issue to the powershell team via the feedback hub.
