### ISSUE TITLE
Default copyOnSelect to true

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#11199]
# Description of the new feature/enhancement

Copy on select is very useful, could it be enabled by default?
It's quite weird when you select something and try to paste it somewhere else to find it doesn't work, because you're on a new machine with this setting disabled.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! While `copyOnSelect` is a handy feature that many users like, I don't think this is something we can change. If we changed this to the default behavior, then it'd apply to all our users, and I'm sure there are plenty who'd rather _not_ have this behavior silently enabled for them on an update. 

Thanks though!
