### ISSUE TITLE
Stay in same path when create a new window

### ISSUE THREAD

**Issue by felps-dev** [microsoft/terminal#11196]
# Description of the new feature/enhancement

I didn't found any settings to stay on same path after create a new window. It would be awesome, because when you open many terminals you need to put "cd..." to choose the path again.

# Proposed technical implementation details (optional)

Put an option like "Persistent path" or a shortcut when clicking on "+" to add tabs, then the next tab will open with the actual tab path.

**Comment by elsaco** [comment]
@felps-dev there's a setting in "General" called "Starting directory". Check "Use parent process directory" to spawn terminals in the directory from which WT was launched. Just a suggestion in case you didn't try this option yet.

![path_setting](https://user-images.githubusercontent.com/3933920/132931251-9dbadc96-9612-47cb-b171-f6d6dfcc7851.png)

**Comment by felps-dev** [comment]
Exactly what i want! Thank so much. Sorry for opened an issue.
