### ISSUE TITLE
Package to install on older Windows versions

### ISSUE THREAD

**Issue by Rundik** [microsoft/terminal#11192]
# Description of the new feature/enhancement

I could only find a msixbundle file to install the terminal and it couldn't get it installed because my windows version is too old (I'm using windows 10 with disabled updates). I don't think such a simple application could use something as bleeding edge to run, so it would be a good thing to make a prebuild exe version to run on older Windows versions I think. Otherwise it kind of looks like some move to force me to update my Windows.

If someone reading this knows such fork, please let me know

**Comment by zadjii-msft** [comment]
[Please read the FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version)
