### ISSUE TITLE
enable acrylic not working

### ISSUE THREAD

**Issue by infusionproximity** [microsoft/terminal#11193]
Hi! The enable arcylic option in the settings is not working, it worked once in between but not before that nor after that, could you tell what went wrong 😅?

**Comment by infusionproximity** [comment]
also i am using hp laptop 15-eg0 with i5 11th gen and iris and mx450 graphics.

**Comment by zadjii-msft** [comment]
[Please read the FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-does-acrylic-not-work)

**Comment by infusionproximity** [comment]
Hi there! The application is focused and no other applications are opened i even tried restarting after applying the setting, am not seeing any effect.

**Comment by elsaco** [comment]
@infusionproximity:  What version of OS ant WT are you using?

On Windows 10 Version 21H1 (OS Build 19043.1165) and WT Version 1.9.1942.0 enabling acrylic works as expected.

Sample screenshot with on tab running PS and 2nd running NU:
![wt_acrylic_screenshot](https://user-images.githubusercontent.com/3933920/132929625-2f57f4b6-09f2-448c-b3fd-a058b2a9c75c.png)

**Comment by infusionproximity** [comment]
i am running 20h2 os build 19042.1202

**Comment by infusionproximity** [comment]
[demo.zip](https://github.com/microsoft/terminal/files/7147236/demo.zip)
i have used step recorder to show what i see

**Comment by infusionproximity** [comment]
also latest version of windows terminal

**Comment by infusionproximity** [comment]
After using it for a few days, the enable acrylic features works 10 percent of the times i start my laptop

**Comment by zadjii-msft** [comment]
* Is your laptop plugged in?
* Does acrylic work in other apps, like Calculator?

**Comment by infusionproximity** [comment]
Yes that was the issue! acrylic in calc worked nonetheless, it seems that it is dependent on the power mode!
