### ISSUE TITLE
The total windows terminal freezed once one tab is busy

### ISSUE THREAD

**Issue by durd07** [microsoft/terminal#11191]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

1. open multi tabs 
2. make one tab busy, such as print much to stdout and the screen scroll for a long time
3. switch to other tabs, the whole windows terminal almost freezed, act very solwly.

suppose the windows terminal use the single process to handle all tabs?

### Expected Behavior

even one tab is busy, other tabs shouldn't be affected.

### Actual Behavior

the whole windows terminal almost freezed, act very solwly.

**Comment by zadjii-msft** [comment]
Out of curiosity, how specifically are you printing the text to the Terminal that causes this freezing? Like, which application are you using? This certainly shouldn't be happening, but there are lots of different ways of printing to the Terminal, so knowing the specific cause might help diagnose the issue.

**Comment by durd07** [comment]
I sshed to another remote server from WSL Ubuntu, then run the command docker logs, docker logs will begin to print to stdout from this tab, at the same time, other tabs will be freezed.

**Comment by durd07** [comment]
Hi @lhecker , thanks for your quick fix. I run the same scenario at 1.11.2921.0, seems there is no freezing now.
