### ISSUE TITLE
Action for adjusting opacity at runtime

### ISSUE THREAD

**Issue by bcosden** [microsoft/terminal#11205]
# Description of the new feature/enhancement
I love the pane of glass look for Terminal. However, when using a dark theme for example in Terminal and the window is in front-of a light colored windows (i.e. Browser with a white page), the text is unreadable  in terminal. And when the Terminal is in front of a dark background the text color in Terminal is nice and crisp. What would be great is if the Terminal can detect the underlying window color and dynamically adjust the opacity to ensure the text of the Terminal window remains readable regardless of the window that Terminal is in front of.

Can't read text in Terminal with transparency in front of a light window when using a dark theme. In order to keep the pane of glass look, I need to keep adjusting the transparency setting based on the background colors (background theme and/or window the Terminal is overlaying). New functionality would automatically adjust this or at a minimum provide a hot key to adjust transparency on demand

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Wow, someone who wants a transparency feature that's not #11180, what a pleasant surprise 😅 

I'm pretty sure there's not a good way for the Terminal to be able to know what the contents of the screen are underneath our window. However:

>  or at a minimum provide a hot key to adjust transparency on demand

Now that's something I can get behind, and something I was already planning for landing once #11180 merged and once I did the control settings refactor for #5000, so I'll leave this open to track that. Thanks!

**Comment by zadjii-msft** [comment]
![adjust-opacity-preview-001](https://user-images.githubusercontent.com/18356694/140785805-5eecf6ec-0933-40e4-bcba-41b88d25b6a8.gif)


`dev/migrie/f/11205-adjustOpacity` is ready to go, but it's targeting #11619 so I need that reviewed first
