### ISSUE TITLE
Trim paste data to avoid multiple lines warning

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#11200]
# Description of the new feature/enhancement

When I copy a single line from a text editor, it might include the newline character and Terminal shows the multiple lines warning. Could it trim the trailing newlines and thus avoid the warning?

![image](https://user-images.githubusercontent.com/2218936/132941099-a3f08433-a2b9-4402-bd66-b4aec010edff.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9400 for more discussion.

/dup #9400
