### ISSUE TITLE
Resizing window to small results in broken tab

### ISSUE THREAD

**Issue by arjun-msft** [microsoft/terminal#1120]
If the terminal window with text on the line the is resized to very small and then later resized to a normal size, the tab that is in focus will be in a broken/unusable state.  This happened to me when I remoted in from a different machine and there were some DPI changes, the terminal window was resized.

# Environment

```none
Version 10.0.18362.113
Windows Terminal version: 0.1.1502.0
I am on a high dpi monitor, 200%.
Any other software? No
```

# Steps to reproduce

1. open new terminal window
2. type in some long text in the window, gibberish is fine
3. resize the window to be really small, minimum size
4. wait a few seconds
5. resize to normal size
-- observe tab is unusable, typing in it does nothing

# Expected behavior

Tab to be usable

# Actual behavior

observe tab is unusable, typing in it does nothing

**Comment by DHowett-MSFT** [comment]
Looks like it could be #1095?
