### ISSUE TITLE
Ctrl+Shift should open Terminal with elevated rights

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#11201]
### Windows Terminal version and OS Version

Windows Terminal 1.10.2383.0
Windows OS 10.0.22000.0

### Other Software

PowerShell 7.1.4

Affected releases: any
Affected OS: Windows 10 (any), Windows 11 (any branch)

### Steps to reproduce

applies to 
1. Windows Terminal run via Win+X > Windows Terminal (may not be intended)
2. Windows Terminal via Windows Search in Start

works as intended
Windows Terminal run pinned on taskbar 
Windows Terminal run pinned via Start

for 1. press Win+X > press Ctrl+Shift Left mouse button >Windows Terminal
for 2. press Win Key > search terminal > press Ctrl+Shift and left click on Terminal in the search results

### Expected Behavior

Pressing Ctrl+Shift should open Terminal and default shell with elevated rights

### Actual Behavior

starts with user rights

**Comment by Karl-WE** [comment]
notes: I believe this needs to be assigned to Windows Team as PowerShell 7, and cmd do behave the same in Windows 11. 
In Windows 10 I remember this to be ok with cmd and PowerShell but Windows Terminal

**Comment by zadjii-msft** [comment]
> Windows Terminal run via Win+X > Windows Terminal (may not be intended)

I'm sitting on `10.0.22454.1000`, and that looks fixed to me. I'm guessing that's going to be fixed either by the official Win11 release, or in an Insiders update shortly thereafter.

> press Win Key > search terminal > press Ctrl+Shift and left click on Terminal in the search results 

This definitely doesn't work with the Terminal in Windows 10, nor does it work with any shell in `conhost` either.
