### ISSUE TITLE
git-bash not launching inside WT tab

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11207]
### Windows Terminal version (or Windows build number)

10.0.19043.0 1.10.2383.0

### Other Software

git version 2.30.1.windows.1

### Steps to reproduce

- create a new profile to start git-bash.exe
- launch the profile

### Expected Behavior

git-bash to run inside WT

### Actual Behavior

git-bash opens a new window, not a WT tab.

Note: bash.exe runs inside a WT tab.

**Comment by zadjii-msft** [comment]
What _exactly_ are you using as your `commandline`? If it's literally `start git-bash.exe`, then yea, a new window is going to open, because `start` is basically `ShellExecute`.

**Comment by elsaco** [comment]
git-bash is launched using a WT profile:

```
            {
                "antialiasingMode": "cleartype",
                "commandline": "C:\\Program Files\\Git\\git-bash.exe",
                "guid": "{a3b32005-1a7f-4d48-b025-90f21d6afa1c}",
                "name": "Git Bash",
                "tabTitle": "Git Bash"
            }
```

And this is the result:

![git-bash_wt_profile](https://user-images.githubusercontent.com/3933920/133105834-d22a6b67-de52-4218-af9e-ee3efd3372af.png)

**Comment by zadjii-msft** [comment]
Ah yep. That's not the vintage console window, that's mintty. You might want to follow this instead: https://github.com/microsoft/terminal/blob/main/doc/user-docs/ThirdPartyToolProfiles.md#git-bash
