### ISSUE TITLE
Update WT help to be in sync with docs.microsoft.com

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11208]
### Windows Terminal version (or Windows build number)

10.0.19043.0 1.10.2383.0

### Other Software

This issue was inspired by #11206 

### Steps to reproduce

- run "wt -h" to display help

### Expected Behavior

- help to be in sync with https://docs.microsoft.com/en-us/windows/terminal/

### Actual Behavior

Sample help output:

![wt_help](https://user-images.githubusercontent.com/3933920/133001284-76f30440-8297-4585-a2ba-42b05761cf2a.png)

There's a lot more help online.

**Comment by DHowett** [comment]
There is a bit of confusion here. The -p argument is an argument to the `new-tab` subcommand. To see all subcommand help, use `wt new-tab --help` (repeat with `split-pane`, etc.)
