### ISSUE TITLE
When the name of a folder have "[" , then "open with terminal" (use the right mouse button) in Explorer , wrong !

### ISSUE THREAD

**Issue by k9fvm** [microsoft/terminal#11203]
### Windows Terminal version (or Windows build number)

10.0.19043.0, 1.10.2383.0

### Steps to reproduce

The Terminal's Default : "Windows PowerShell"

Create 4 folders:
"D:\a[bc]"
"D:\a[bc"
"D:\abc"
"D:\abc]"

Click them one by one, "open with terminal" (use the right mouse button) in Explorer

Then you well see the problem.

If holding "Shift" ,click the right mouse button ,and "open with PowerShell" ,it is no problem.
If the Terminal's Default is "CMD" , it is no problem.

### Actual Behavior

PS C:\windows\System32\WindowsPowerShell\v1.0>
PS C:\>
PS D:\abc>
PS D:\abc]>

**Comment by janeusz2000** [comment]
Does symbol ']' is even allowed to be inside the windows directory?

**Comment by k9fvm** [comment]
> 
> 
> Does symbol ']' is even allowed to be inside the windows directory path? As far as I am concerned this symbol is invalid :)

It is allowed in Windows10 . Just click the right mouse button in Explorer , and create a  folder , then name it "[abc]".
![abc](https://user-images.githubusercontent.com/90003417/132990985-f1dfb37d-3e10-4ddf-ac6f-f409ca5d5c51.PNG)

**Comment by elsaco** [comment]
Could be related to #11149

**Comment by zadjii-msft** [comment]
Yep, this is /dup #11149. This is a bug in Windows PowerShell (5.1) -- sorry! There's nothing that can be done about that. It does not handle directories with special characters in them properly.
