### ISSUE TITLE
Make the icon in the task bar more visible in some cases

### ISSUE THREAD

**Issue by CWempe** [microsoft/terminal#11216]
# Description of the new feature/enhancement

I have dark mode enabled on my Win10.
As some might know the task bar is some kind of translucent, so the desktop wallpaper influences the exact shade of "black" for the task bar.

If I have a black wallpaper, the taskbar is very dark and the grey terminal icon is visible.

![image](https://user-images.githubusercontent.com/1270359/133138218-f95bae99-f2f4-415b-8200-c1a979c0d368.png)

But if the wallpaper is bright grey, the task bar becomes a little brighter and makes the terminal icon hard to see.

![image](https://user-images.githubusercontent.com/1270359/133138329-91c63c23-71d1-4844-93f8-465589d84eb9.png)

# Proposed technical implementation details (optional)

Add some kind of board to the application icon

**Comment by WSLUser** [comment]
Maybe the HC icon can be used in this situation. But I think a user would need to manually choose this in a setting (easiest way to fix the issue.)

**Comment by elsaco** [comment]
Changing "accent color" and showing on/off accent colors in "start, taskbar, and action center" might help your issue. Check Settings->Colors in the control panel, please.

**Comment by cinnamon-msft** [comment]
I don't believe changing the icon in this way follows design guidelines. I'd recommend playing with the high contrast settings and the accent colors, as mentioned above. 🙂 I'll close out this issue since we won't be changing the taskbar icon.
