### ISSUE TITLE
Terminal bottom hidden by taskbar when spawning in portrait layout

### ISSUE THREAD

**Issue by 3N4N** [microsoft/terminal#11218]
<sub>*I don't know if it's a bug, cause the reproduction steps are uncommon. That's why I used a blank issue template.*</sub>

The default layout, something like 120x30, works perfectly.

![image](https://user-images.githubusercontent.com/32037751/133144311-a3b80b32-8ebf-4cd5-acff-bc893ccc341f.png)

For personal taste, I decided to change it to 90x40. But if I do that, the bottom part of the window is hidden by the taskbar and I have to manually drag it to it's proper place.

![image](https://user-images.githubusercontent.com/32037751/133144782-a4021693-70cb-422f-8fe0-88558030eacd.png)

&nbsp;

By the way, it also happens with `pwsh` windows in similar, portrait layouts. I worked around it by manually setting the window position in properties. No such option is visible for Windows Terminal.

<sub>**P.S.** And that tab isn't open at where you think it's open at. I promise.</sub>

**Comment by zadjii-msft** [comment]
> No such option is visible for Windows Terminal.

Have you tried setting [`initialPosition`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#launch-position)?

**Comment by 3N4N** [comment]
@zadjii-msft, thanks. `initialPosition` worked.

Is there any reason why Windows desktop manager decides to put the terminal window partially behind the taskbar? Just curious. Probably not related to this repository, though.

**Comment by zadjii-msft** [comment]
Honestly, no idea. When you don't give it an initial position, it just picks some value automatically. There actually was a PR for this a while back - #5671. Looks like we must have lost track of it. /dup #3187
