### ISSUE TITLE
Snapping terminal to/from display with different scale causes terminal to render incorrectly

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#1121]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18908.1000]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
![imgur](https://i.imgur.com/JRC88Ei.png)
This is my display setup
- 1 is the smaller laptop display with 125% scale.
- 2 is the bigger main display with 100% scale.

1. Open Terminal in the main display
2. Press `win + right`  (This will snap the terminal to the right side of the main display)
3. Press `win + right` again  (This will snap the terminal to the left side of the laptop monitor)
4. Press `win + left`  (This will again snap the terminal to the right side of the main display)

# Expected behavior

# Actual behavior
![imgur](https://i.imgur.com/Q7hde7r.png)

**Comment by DHowett-MSFT** [comment]
This screenshot is from 0.2. I'm gonna say we fixed this -- if we haven't, can you let me know?
