### ISSUE TITLE
PSEUDOCONSOLE_INHERIT_CURSOR sends DSR CPR to terminal, if the process is closed before a response is received, conhost will max out a core

### ISSUE THREAD

**Issue by Tyriar** [microsoft/terminal#11213]
### Windows Terminal version (or Windows build number)

19042.1165

### Other Software

VS Code/node-pty based on `main`

### Steps to reproduce

1. Use PSEUDOCONSOLE_INHERIT_CURSOR to when using conpty
2. Don't respond to CSI 6 n in terminal
3. Close the terminal program

### Expected Behavior

Conpty should handle this more gracefully, perhaps a timeout should be used when the CPR response isn't received and continue on ignoring PSEUDOCONSOLE_INHERIT_CURSOR ?

### Actual Behavior

The conhost process maxes out a CPU core

---

FWIW I worked around the issue by making sure a terminal is available to respond to the sequence on Windows (I'm in the process of building terminal buffer restoration/process revive after restarts).

**Comment by zadjii-msft** [comment]
> Conpty should handle this more gracefully, perhaps a timeout should be used when the CPR response isn't received and continue on ignoring PSEUDOCONSOLE_INHERIT_CURSOR ?

Alternatively, since the end terminal's closed, then presumably the conpty is getting closed, yea? It should probably close gracefully even in this case.

**Comment by zadjii-msft** [comment]
@miniksa fyi, you're in this bit of the code recently. You may want to be aware of this
