### ISSUE TITLE
add a tabColor field in the Settings for each profile

### ISSUE THREAD

**Issue by Wobbegong3** [microsoft/terminal#11212]
# Description of the new feature/enhancement

It would be really nice if there was a way to set the tabColor for a profile within the Settings menu (probably within the Appearance tab).  As things are now, the only way I find to set or change the tabColor for a profile is by editing the JSON file (e.g., the "tabColor": "#FFFF00" entry). 

Also, guessing what hex code is needed to represent a desired color is challenging, so it would be great if there was an option to choose a color by clicking on a color wheel display (which would then insert the appropriate hex code in the tabColor field.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9189 for more discussion.

/dup #9189
