### ISSUE TITLE
New features are unavailable

### ISSUE THREAD

**Issue by joca-bt** [microsoft/terminal#11226]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

Installed from the Microsoft Store. Window Terminal package (regular one, not PRE).

Windows version: Windows 10 Pro 19043.1165.

### Steps to reproduce

Two of the new features released in version https://github.com/microsoft/terminal/releases/tag/v1.10.2383.0 are unavailable:

> We've reintroduced the UI that allows you to edit default settings that apply to all profiles, as well as arrow buttons that let you revert individual settings (#10588)

Can't edit the default settings and no arrows are shown anywhere.

<img width="1280" alt="settings" src="https://user-images.githubusercontent.com/1297942/133314212-16ed68eb-83e6-4171-9eaa-1e9e54a95d41.png">

- > On the Actions page, you can now edit existing actions and add new ones (#10550) (#10220)

No such option. Clicking on an action doesn't do anything.

<img width="1280" alt="actions" src="https://user-images.githubusercontent.com/1297942/133314324-d743d3d6-2d1b-4ef5-8133-131b97a6cd38.png">

Both features are originally from https://github.com/microsoft/terminal/releases/tag/v1.10.1933.0.

### Actual Behavior

See steps to reproduce.

**Comment by zadjii-msft** [comment]
That's correct. From the [1.11 blog post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-11-release/):

> All of the features from our previous release are now in Windows Terminal, except for the default terminal setting, the editable actions page, and the Defaults page of the settings UI.

These particular features are being held in only the Preview builds until we can polish them off for the Stable audience.
