### ISSUE TITLE
Pasting does not clear the rendered selection

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#11227]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

None

### Steps to reproduce

1. Create a selection
2. execute `paste` keybinding

### Expected Behavior

Paste should clear the selection and inject the pasted text.

### Actual Behavior

The text is pasted, but the selection is not cleared.

Interestingly, executing the copy action (with <kbd>ctrl+c</kbd>, for example) passes the keybinding through. This suggests that the selection was cleared, but we're not telling the renderer to `TriggerSelection()` on a paste operation.

**Comment by carlos-zamora** [comment]
NOTE: This affects Stable and Preview so we should make sure to apply the fix to both.

**Comment by fischerdouglas** [comment]
Hello @carlos-zamora !

I'm using 1.11.2421.0

I tried to reproduce the issue, and I wasn't able to...

I tried with CTR+V , CTR+SHFT+V , SHIFT+INSERT
I also tried with tabs of Powershell7, Powershell5, WSL Ubuntu.

**Comment by carlos-zamora** [comment]
I'm still able to repro the issue on 1.11.2421.
I have `paste` bound to <kbd>ctrl+v</kbd>
![bug demo](https://user-images.githubusercontent.com/11050425/133851607-aaa952e6-15aa-444d-8f20-0603337abfbe.gif)
.

**Comment by DHowett** [comment]
I'd like to be totally clear on this. How are you pasting, @carlos-zamora?

**Comment by carlos-zamora** [comment]
> I'd like to be totally clear on this. How are you pasting, @carlos-zamora?

<kbd>ctrl+v</kbd> which is bound to the `paste` action.

**Comment by fischerdouglas** [comment]
![image](https://user-images.githubusercontent.com/7989601/133990595-0ccb3426-2a73-4234-a4ea-b2ca39395608.png)

![WindowsTerminalActionPasteRemovingSelection](https://user-images.githubusercontent.com/7989601/133990556-e6ae85ff-84a8-40f2-9ddd-84a7bbcc1e40.gif)

Same is reproduced Powershell 5, Command Prompt, WSL Ubuntu.

**Comment by zadjii-msft** [comment]
![gh-11227](https://user-images.githubusercontent.com/18356694/134003536-a66df915-872c-4a43-8a4e-96093b620eac.gif)

I can definitely repro this on 1.12
