### ISSUE TITLE
Disable GPU accelerated text rendering

### ISSUE THREAD

**Issue by mariozar** [microsoft/terminal#11230]
NVIDIA overlay for video games shows windows terminal as a video game so it also enables the overlay while windows terminal is in use. This is documented here: https://github.com/microsoft/terminal/issues/7816. I don't see NVIDIA implementing a better game detection algorithm anytime soon so disabling GPU accelerated text rendering would be useful. I am not sure if this is already supposed to be a feature on windows terminal since the rendering tab shows "use software rendering". NVIDIA overlay still starts even though I checked "use software rendering", which might mean that that feature is not functioning properly if it is already implemented.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
You literally are asking for one of the major features that Terminal came out with when first released to intentionally speed up text rendering. There is a use software rendering setting for Windows Terminal if you don't want to use DirectX. That's mostly intended to troubleshoot issues though such as what you describe here but it'll suit your purpose.

**Comment by zadjii-msft** [comment]
> There is a use software rendering setting for Windows Terminal if you don't want to use DirectX. That's mostly intended to troubleshoot issues though such as what you describe here but it'll suit your purpose.

OP literally said

> NVIDIA overlay still starts even though I checked "use software rendering", which might mean that that feature is not functioning properly if it is already implemented.

@mariozar Just to be absolutely sure, you rebooted the Terminal after checking that box, yea?

**Comment by miniksa** [comment]
Software rendering still uses DirectX, it just uses the Microsoft WARP renderer. https://docs.microsoft.com/windows/win32/direct3darticles/directx-warp

I will try to reach out to NVIDIA and ask if there's anything we can do here.

**Comment by miniksa** [comment]
NVIDIA has acknowledged this and told me they will add the Windows Terminal binaries to the list of applications excluded for overlay. 

It will likely take some months for that to happen and trickle out to driver packages in your hands, so please be patient with NVIDIA on this one.

**Comment by Zingam** [comment]
@miniksa This popup appears in all sorts of UWP applications. So I'd say MS needs to find a better solution and provide API so that apps can disable such behavior. I'd say it is not NVIDIA's fault or business to ban every non-game application in the world.

**Comment by zadjii-msft** [comment]
We literally had an email thread with NVIDIA where they were working on fixing it. Do you have a list of those apps? We can forward the list along and see what they have to say about it.

**Comment by miniksa** [comment]
We did also talk to NVIDIA about the meta-aspect of detecting what is and is not a game. It is perhaps time for an update in the overall heuristic and/or the APIs and flags available between DX and the driver to help that negotiation process. One of their folks even said they wanted a shirt for the office that said "DX: not just for games".
