### ISSUE TITLE
[UX] Adopt Windows 11 Fluent styling for Settings

### ISSUE THREAD

**Issue by niels9001** [microsoft/terminal#11231]
With Terminal pre-installed with Windows 11, it would be nice if it would adhere to the same styling other Windows 11 inbox app uses. 

For example, OS Settings, Snip and Sketch and Alarm include the updated visual refresh for Settings. This brings multiple advantages:
- Consistency
- Distinguishing settings is easier now (a.k.a. "glanceability").
- With the introduction of these cards, more descriptive information can be added easily.
- Accessibility improvements.
- Just feels more polished :).

![image](https://user-images.githubusercontent.com/9866362/133399857-b33bd805-ed76-43d2-a9b9-b04f67c14395.png)

We have done a similar action for PowerToys:

![image](https://user-images.githubusercontent.com/9866362/133400732-93c746de-7fef-4dd0-abe4-bf166d4317a4.png)

For PowerToys, I have created a [custom control to easily create "grouped" settings](https://github.com/microsoft/PowerToys/tree/master/src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/SettingsGroup) and [a SettingCard control](https://github.com/microsoft/PowerToys/tree/master/src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/Setting) for the cards itself (that allows for setting an icon, action content, header and description) that is 1:1 inline the Windows 11 Settings UI specs.

@DHowett @DHowett-MSFT @cinnamon-msft I'm happy to work on this if there's a green-light!

**Comment by zadjii-msft** [comment]
This is something we were already planning on, but just haven't had a chance to get to quite yet 😝 We're kinda blocked on updating to WinUI 2.6 at the moment, but I've got a drop of 2.7 that I'm actually planning on trying to ingest today. Once I've got that working, then ABSOLUTELY feel free to help out. I believe @cinnamon-msft has some mocks of what we've been planning with the design team that we can share.

**Comment by WSLUser** [comment]
I really don't like any of the Win11 UI at all. I hope people will have a choice to keep the Win10 UI if you're on Win10. I don't plan on ever touching Win11 unless the UI is fixed.

**Comment by DHowett** [comment]
> I really don't like any of the Win11 UI at all. I hope people will have a choice to keep the Win10 UI if you're on Win10. I don't plan on ever touching Win11 unless the UI is fixed.

We will be updating our settings UI to the new style and *do not* intend to maintain two UI stacks.

You are always welcome to edit your settings in the most terminal-friendly way possible: via JSON.

**Comment by Tropix126** [comment]
Might as well post one of my design concepts from #1375 since it's relevant.
https://user-images.githubusercontent.com/42101043/132434814-0110c890-c4c7-4820-a599-701ab41dcf05.png

**Comment by floh96** [comment]
see https://github.com/microsoft/terminal/pull/11720 for first draft
