### ISSUE TITLE
Bug Report - Foreground text has become black in some cases, in powershell

### ISSUE THREAD

**Issue by palenshus** [microsoft/terminal#1123]
# Environment

```none
Windows build number: 18362.145
Windows Terminal version (if applicable): 0.1.1431.0

Any other software?
```

# Steps to reproduce

Had terminal up for a few days on remote machine, locked machine and when I came back after weekend and logged in, parts of the command text is now black

# Expected behavior

All foreground text should be white

# Actual behavior

Some text is white, some is black. It looks like command _output_ is white, but commands I type are usually black, as well as error text.
![image](https://user-images.githubusercontent.com/7907848/58828513-7b644d80-85fa-11e9-8cc1-98885f7764fd.png)

Weird nuances though:
![image](https://user-images.githubusercontent.com/7907848/58828670-cda56e80-85fa-11e9-88db-2ba058420058.png)
![image](https://user-images.githubusercontent.com/7907848/58828680-d433e600-85fa-11e9-8083-3ad1cf9703db.png)

**Comment by DHowett-MSFT** [comment]
I saw this when I upgraded from 0.1.1431.0 to 0.1.1502.0, actually. Everything _with a color_ becomes black, and everything with the _default color_ stays correct.

**Comment by palenshus** [comment]
Ah, Dustin I didn't figure out that correlation, but now that you say it yes, that appears to be the behaviour I'm seeing, thanks for clarifying it :)

**Comment by zadjii-msft** [comment]
This may be related to #742. I thought we had a migration in place, but maybe it's not not working?

**Comment by DHowett** [comment]
Haven't seen reports of this in quite a long time, so I'm gonna close it out. Let me know if it's still happening!
