### ISSUE TITLE
resetFontSize not working when using ctrl+numpad_zero

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11239]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.11.2421.0

### Steps to reproduce

1. increase font size with ctrl+numpad_plus or crtl+=
2. reset font size with crtl+numbpad_zero

### Expected Behavior

1. font size reset

### Actual Behavior

1. ctrl+numpad_zero won't reset font size
2. it works only with crtl+0 from upper numkey row

Settings from defaults.json:
```
        // Visual Adjustments
        { "command": { "action": "adjustFontSize", "delta": 1 }, "keys": "ctrl+plus" },
        { "command": { "action": "adjustFontSize", "delta": -1 }, "keys": "ctrl+minus" },
        { "command": { "action": "adjustFontSize", "delta": 1 }, "keys": "ctrl+numpad_plus" },
        { "command": { "action": "adjustFontSize", "delta": -1 }, "keys": "ctrl+numpad_minus" },
        { "command": "resetFontSize", "keys": "ctrl+0" },
```

**Comment by zadjii-msft** [comment]
Yep, looks like `numpad_0` isn't in the defaults:
https://github.com/microsoft/terminal/blob/844d46a132b2e142d98efb7a28d940caa5096b3e/src/cascadia/TerminalSettingsModel/defaults.json#L390-L396

Should be easy enough to add though.
