### ISSUE TITLE
CTRL+ combos brake with cyrillic in PowerShell 7.1.4

### ISSUE THREAD

**Issue by 243083df** [microsoft/terminal#11232]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

PowerShell 7.1.4

### Steps to reproduce

Open powershell 7.1.4 in windows terminal.
In cyrillic keymap press CTRL+С (C cyrillic)
CTRL not working and terminal show C
CTRL+A and CTRL+C not working after it in both keymaps

There is also another cases but it hard to reproduce.

### Actual Behavior

CTRL+C working correctly

**Comment by zadjii-msft** [comment]
Does this work in the vintage console window (`conhost.exe`)? Does this work if you `Remove-Module PSReadline`?

**Comment by 243083df** [comment]
Remove-Module PSReadline fix issue, "ctrl+" commands start working, but not show ^C in "CTRL+C"

**Comment by zadjii-msft** [comment]
Sounds like this is a PsReadline issue then, which should be filed upstream at https://github.com/PowerShell/PSReadLine
