### ISSUE TITLE
Windows Terminal crashes when opened

### ISSUE THREAD

**Issue by hicksjacobp** [microsoft/terminal#11241]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Windows 10 Version 21H1 OS Build 19043.1165

### Steps to reproduce

I was initially having some crashing issues with Windows Terminal after installing the latest release (1.10.2383.0). I missed that a newer Windows version is necessary to use that release, so then I uninstalled what I had and installed 1.9.1942.0.

However, I still can't start Windows Terminal.

For some reason, I also cannot open the Feedback Hub in order to provide any diagnostic data...

### Expected Behavior

Windows Terminal should start.

### Actual Behavior

Windows Terminal stops working with never showing a window. Windows shows Windows Terminal stopped working and only gives me the options to debug or close.

![image](https://user-images.githubusercontent.com/832739/133487450-0a3b8598-182a-475d-b92a-724e0f33fb5a.png)

**Comment by DHowett** [comment]
> I missed that a newer Windows version is necessary to use that release

Whoa whoa whoa what? Where'd you hear that?

**Comment by DHowett** [comment]
If you leave that dialog up, and then go to Task Manager, is `WindowsTerminal.exe` still present in the Details tab? If so, would you mind using `Create Dump` and mailing that to me (or placing it on your favourite cloud storage provider (OneDrive)?)

**Comment by hicksjacobp** [comment]
> > I missed that a newer Windows version is necessary to use that release
> 
> Whoa whoa whoa what? Where'd you hear that?

Perhaps I misunderstood the description here while I was quickly skimming? Perhaps Windows Terminal 1.10+ is required if using Windows 22000.65+?

https://github.com/microsoft/terminal/releases/tag/v1.10.1933.0

> Due to the change, 1.10+ is required with Windows 22000.65 and above.

Regardless, I was having the same symptoms of Windows Terminal failing to start.

----

Since I was having issues with Feedback Hub, I also attempted a couple fixes from searching around:

- Resetting Feedback Hub
- Running the following as admin:

  ```powershell
  Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
  ```

After doing these, it noted I needed to restart Windows, so I did. After restarting, Windows Terminal 1.9.1942.0 now appears to start 😕.

Since it appears I misunderstood the Windows version requirement with 1.10+, I've now installed 1.10.2383.0, which also appears to start fine.

So I'll chalk this up to my machine being in some weird state! I apologize for the unnecessary issue.

**Comment by zadjii-msft** [comment]
> Due to the change, 1.10+ is required with Windows 22000.65 and above.

That's a perhaps confusingly worded sentence. More correctly: If you're using Windows 22000.65 or greater, you'll need to update to 1.10 or above. And that's really only for the "default terminal" feature. 

Since the issue went away on it's own, I'm guessing this is one of those font issues we were seeing earlier on in 1.9.
