### ISSUE TITLE
[Settings]: Tooltip is not dismissed with 'Esc' key throughout the settings page.

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#11249]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

**Test Environment:**
OS: Windows 11 Version 21H2 (OS Build 22000.168)
Screen Reader: Narrator
Tool: Accessibility Insight for Windows

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Settings page using "Ctrl + ',' ".
3. Navigate to all control where tooltip is appearing and try to dismiss tooltip with 'ESC' key.
4. Observe the issue.

**User Experience:**
Keyboard user will impact here as no way is provided to them to close the additional content which is covering other informative content without moving their focus away.

**Guideline Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus

**Attachments:**
[Tooltip is not dismissed with 'Esc' key throughout the settings page..zip](https://github.com/microsoft/terminal/files/7176570/Tooltip.is.not.dismissed.with.Esc.key.throughout.the.settings.page.zip)

### Expected Behavior

Tooltip should dismissed with 'Esc' key throughout the settings page. 

### Actual Behavior

Tooltip is not dismissed with 'Esc' key throughout the settings page.

**Comment by DHowett** [comment]
This is true anywhere that XAML is being used. Try it in Feedback Hub, it has the same behavior.

@v-rpundir Can you re-evaluate this as a platform bug?

**Comment by v-rpundir** [comment]
we are tracking this external bug here https://github.com/microsoft/microsoft-ui-xaml/issues/3494

**Comment by DHowett** [comment]
Thank you!

**Comment by DHowett** [comment]
@v-rpundir That seems to be a different, unrelated NavigationView bug.

**Comment by v-rpundir** [comment]
Reopening as by Mistake commented on wrong bug.

**Comment by v-rpundir** [comment]
Closing the bug as 'CTRL' is standard key to dismiss the tooltip is Windows Platform. Tooltip is dismissed with 'CTRL' key in Terminal app.

**Comment by Priyanka-Chauhan123** [comment]
Closing the bug as UI has been changed.
