### ISSUE TITLE
Add keyboard access to settings.json file from settings menu

### ISSUE THREAD

**Issue by miwojc** [microsoft/terminal#11254]
# Description of the new feature/enhancement

Add keyboard shortuct to settings.json file from settings menu.

Currently i can press CTRL+ , to open settings menu, but if i want to modify settings.json i have to use mouse to open it.

Would be great to provide keyboard shortcut to open settins.json

**Comment by elsaco** [comment]
@miwojc "ctrl+alt+comma" key cord opens default.json file. "ctrl+shift+comma" opens settings.json file.

**Comment by miwojc** [comment]
Thank you for explaining this. I should have looked in docs in the first place. 😅

**Comment by miniksa** [comment]
Thanks for popping in here, @elsaco!
