### ISSUE TITLE
Grey screen on launch, terminal doesn't respond

### ISSUE THREAD

**Issue by Sankgreall** [microsoft/terminal#11252]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

- Install Windows Terminal (either through Store or through .msixbundle

- Try to launch Windows Terminal

Note: Execution environment is a AVD host pool using a Windows 10 build 2004 base image 

### Expected Behavior

Windows Terminal launches

### Actual Behavior

Windows Terminal does not load. Instead, it is completely grey and eventually stops responding and must be forcibly stopped.

<img width="902" alt="wsl" src="https://user-images.githubusercontent.com/53608489/133659903-9f03d844-1f08-4db4-b89d-13393c67afb9.png">

**Comment by Sankgreall** [comment]
Following on from this, if I execute the Windows Terminal **twice**, then the first window will open grey and unresponsive as above. However, once this is forcibly quit then the second execution will open **as intended**.

I.e., two or more executions in a row work fine, once the first windows has been destroyed.

**Comment by zadjii-msft** [comment]
Hmm interesting. I've got a question that might help sort out the root cause here. If you install PowerToys, and try and open the PowerToys settings, do you get the same behavior?

**Comment by Sankgreall** [comment]
Thanks for your reply. PowerTools was not on the original run environment, but have installed it now to test.

Does appear to work. No grey screen on the settings page, and PowerToys Run works as expected.

<img width="1658" alt="powertoys" src="https://user-images.githubusercontent.com/53608489/133894697-b179a54b-c362-40ae-8752-52471ee951b6.png">

**Comment by Sankgreall** [comment]
Weirdly, after closing PowerToys Settings and the failing Windows Terminal, my next attempt at opening Windows Terminal succeeded. Subsequent attempts failed and went back to grey screen.

I uninstalled and reinstalled PowerToys, but wasn't able to replicate - so it could have been a coincidence. However, on the first time I tried this I did notice a PowerToys error message (which I'm sorry I didn't take a screenshot of), which didn't happen upon reinstallation.

**Comment by Falco20019** [comment]
I have the same problem. I just cleanly reinstalled the latest release but it's not working. I have Windows 10 v1909 (Build 18363.1734) and can't update since it's a company machine maintained by our IT.

**Comment by zadjii-msft** [comment]
Sorry, didn't realize this was Windows Server. Yep, that sounds just like /dup #11135

**Comment by Falco20019** [comment]
@Sankgreall I also have the same issue on 1909 (non server), but I assume the cause is the same or at least related.
