### ISSUE TITLE
Logitech Keyboard is not recognized at Windows Terminal 1.10.2383.0

### ISSUE THREAD

**Issue by rafamss** [microsoft/terminal#11268]
I've installed Windows Terminal through the Windows Store, but I can't use any terminal tab (PowerShell, CMD, or Linux) because it seems the keyboard isn't recognized by it. I'm using a Logitech MX Keys keyboard with a unifying stick. Is there anything I need to install as a pre-requisite to windows terminal works, or is it a bug?

**Comment by zadjii-msft** [comment]
Is the "Touch, Keyboard and Handwriting Panel" service running?
