### ISSUE TITLE
Copying text from the command window behaves differently than previous versions

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1126]
Ported from internal bug
>When I select some text from a window using Vim.exe and paste to another window, the text is badly formatted.
>Also, if double-click text from a command window, it copies/pastes the extra white-space at the end which was not the case in earlier releases.
>I also see the problem when copy/pasting to an excel spreadsheel

Tried to repro: space bug does not repro, vim bug does since 19H1

**Comment by DHowett-MSFT** [comment]
To clarify, this is not #1091 because 1091 is in Terminal and this is in Conhost

**Comment by JeremyTBradshaw** [comment]
Just commenting to add that I see this behavior when it's PowerShell.exe in the terminal.  Doesn't behave on the paste into other apps like it does with cmd.exe and PowerShell.exe natively.  I assume it's the trailing whitespace on each line as the internal bug's description states.

**Comment by nyuszika7h** [comment]
Copying text does not trim the trailing whitespace for me in WSL unless I hold down the Alt key while selecting. No issues with PowerShell or cmd.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/1073

https://github.com/microsoft/terminal/issues/1126
https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275
https://github.com/microsoft/terminal/issues/2278
https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395
https://github.com/microsoft/terminal/issues/2717
https://github.com/microsoft/terminal/issues/52
