### ISSUE TITLE
Add Run as Administrator to menu 

### ISSUE THREAD

**Issue by cnmade** [microsoft/terminal#11269]
I am using windows 10, I like the Win+X menu, It let us to run Powershell or Powershell  Run as administrator.

Some task need administrator permission on windows. I often do the operations daily. 
Would you please add menu to let us quick create a new terminal with the Administrator permission.

**Comment by zadjii-msft** [comment]
There's a bunch of threads that discuss this already. Please make sure to search before filing new issues:
* #9903
* #5000
* #632

You can always run the terminal elevated from the taskbar:
![image](https://user-images.githubusercontent.com/18356694/133892459-8eae4414-83d5-4022-944f-96efa0aa814a.png)


And on Windows 11, the Win+X menu will also have this option:
![image](https://user-images.githubusercontent.com/18356694/133892444-962c1b39-8a10-4fca-bbc5-e02207482703.png)

/dup #632
/dup #9903
