### ISSUE TITLE
Commands not working if ">" is deleted from input box

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11262]
### Windows Terminal version (or Windows build number)

WT version  1.11.2421.0

### Steps to reproduce

1. launch command palette with "ctrl+shift+p"
2. delete ">" prompt
3. type a command, "new tab" used in this case

Sample screenshot:
![wt_new_tab_command](https://user-images.githubusercontent.com/3933920/133817544-a0f8419a-7d88-4e5b-bb03-1ed46d114158.png)

### Expected Behavior

1. command executed successfully 

### Actual Behavior

1. command execution error

Sample screenshot
![wt_new_tab_command_error](https://user-images.githubusercontent.com/3933920/133817700-3e97f504-c73c-4cf8-bfc3-5a25002ea331.png)
:

**Comment by miniksa** [comment]
This is by design. The box works in multiple modes. The > is there by default to symbolize a command to the terminal itself. Deleting the > implies that you want to execute a new tab with whatever you typed in.
