### ISSUE TITLE
Conpty needs to render the on/off state of the cursor

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1127]
This is a followup from #1087. I don't render the right state out through conpty, and that means that for tools like `apt`, the cursor is always on, even when they want it off.

**Comment by utybo** [comment]
I'm experiencing the same issue as #1461, which redirects to here.

Any update on this?

Here is an example C# code:

```
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Now you see me!");
            Console.CursorVisible = true;
            Console.ReadLine();
            
            Console.CursorVisible = false;
            Console.WriteLine("Now you don't!");
            Console.ReadLine();
        }
    }
```
![image](https://user-images.githubusercontent.com/5175705/64894794-fb2e9900-d67a-11e9-9d2b-99d2e81df616.png)
![image](https://user-images.githubusercontent.com/5175705/64894807-0386d400-d67b-11e9-88ed-422dbe63980e.png)
In the second image, the cursor is at the very end of the line

**Comment by zadjii-msft** [comment]
Good catch, this we incorrectly marked for _Terminal v1.0_ when it's really a 20H1 fix.
