### ISSUE TITLE
Opening a folder from ctx menu which has ";" in it's file name fails to open

### ISSUE THREAD

**Issue by pozm** [microsoft/terminal#11273]
### Windows Terminal version (or Windows build number)

Windows Terminal 1.10.2383.0; Microsoft Windows 10.0.19043

### Steps to reproduce

1. Have a folder which contains ";" in it's name
2. Right click the folder and click "Open in Windows Terminal"

### Expected Behavior

Windows Terminal to open at the specified directory 

### Actual Behavior

Two tabs open saying 
```
tab1
[error 0x8007010b when launching `cmd.exe']
Could not access starting directory "<directory up to ;>"

tab2
[error 0x80070002 when launching `<after;>\.']
```
this happens regardless if im using powershell or cmd as default start up.

**Comment by elsaco** [comment]
@pozm semicolon is part of "Word delimiters" defined in the "Interaction" settings:

`     "wordDelimiters": " /\\()\"'-.,:;<>~!@#$%^&*|+=[]{}~?\u2502",`

**Comment by pozm** [comment]
> 
> 
> @pozm semicolon is part of "Word delimiters" defined in the "Interaction" settings:
> 
> ` "wordDelimiters": " /\\()\"'-.,:;<>~!@#$%^&*|+=[]{}~?\u2502",`

Even after removing it from there, the same issue still persists.

**Comment by elsaco** [comment]
@pozm for fun try the other way around, drop the folder name over the "+" tab.  After creating a "C:\temp\wt;test" folder this is the result with drag-and-drop:

![wt_semicolon_in_folder_name](https://user-images.githubusercontent.com/3933920/133943130-a75aca2e-cd90-4106-bb67-6ac086e88d5c.png)

**Comment by zadjii-msft** [comment]
I'm not quite sure what **@&zwj;elasco** is on about here. This looks like a legit bug, we're not escaping semicolons in the shell extension. Good catch!
