### ISSUE TITLE
Underlining not showing for tabs

### ISSUE THREAD

**Issue by LeCyberDucky** [microsoft/terminal#11277]
### Windows Terminal version (or Windows build number)

10.0.19043.1237, 1.10.2383.0

### Steps to reproduce

I am trying to print tabs with an underline. Please see this comment for a more detailed investigation: https://github.com/LukasKalbertodt/bunt/issues/25#issuecomment-922509889

### Expected Behavior

I expect the tab characters to display with an underline. 

### Actual Behavior

The tab characters are not underlined: 

![image](https://user-images.githubusercontent.com/19520383/133937814-5ae9f732-16ff-4791-949b-b1e4f5023924.png)

**Comment by j4james** [comment]
This is the way it's intended to work. `TAB` is a control character which moves the cursor position to the next defined tab stop. It doesn't actually output anything, and thus can't add underlines to the cells that it has skipped over. If you want an underline in those cells you'll need to output a printable character there, like a space.

**Comment by LeCyberDucky** [comment]
Alright, thanks for the explanation and for getting back to me so quickly. I'll close the issue then. Have a nice evening!

**Comment by DHowett** [comment]
Thanks @j4james!
