### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by tomochomo** [microsoft/terminal#11275]
I use the Windows Terminal for WSL with a customized terminal prompt.
But after I updated the app the other day, only the first line of the prompt got a somewhat strange display.

I put the following code in bashrc and use the font "Menlo for Powershell" by the way.
export PS1='\[\e[30;47m\] \d \t \[\e[37;44m\]\[\e[30;44m\] \u@\h \[\e[34;42m\]\[\e[30;42m\] \w \[\e[32;49m\]\[\e[39m\]'
(Sorry if the rightward triangles above may get garbled.)
The problem is that some spaces are not colored such as between the current time and rightward triangle, between rightward triangle and username "tomoyuki," and so on.

Is there any way to avoid this display error?
(Here's the screenshot of the terminal display.)
![2021-09-19 221713](https://user-images.githubusercontent.com/72292257/133928980-2ff300a2-8572-454b-9162-3a271444cc20.png)

**Comment by elsaco** [comment]
@tomochomo looks like there are some escape sequences missing. Please try this prompt:

` export PS1='\[\e[30;47m\] \d \t \[\e[37;44m\]\[\e[30;44m\] \u@\h \[\e[34;42m\]\[\e[30;42m\] \w \[\e[32;49m\]\[\e[39m\]'`

**Comment by tomochomo** [comment]
Thanks for the quick response and comment. I appreciate it.
I modified the bashrc file as proposed, but there seems no change so far.

I just realized that this error occurs only for the first line in every tab.
But, when I opened a new terminal in VSCode using a remote connection, this display error didn't happen.
So, maybe Windows Terminal itself, not a code of bash, has a bug or something.

**Comment by elsaco** [comment]
@tomochomo you're correct, the prompt should look like that. And it does!

Here is a sample screenshot. The first prompt is mine. The 2nd prompt is using your export statement resulting in a broken prompt:

![powerline_prompt](https://user-images.githubusercontent.com/3933920/133949080-4925b6b7-b60a-4ce8-9a5f-c54cb2dd7990.png)

Don't mind the color scheme please.

**Comment by tomochomo** [comment]
@elsaco Thanks again for your advice!
I'm now using the following code which you taught me in your first reply, but still, the display of the first prompt is broken (after 2nd prompt, there seems no problem).
`export PS1='\[\e[30;47m\] \d \t \[\e[37;44m\]\[\e[30;44m\] \u@\h \[\e[34;42m\]\[\e[30;42m\] \w \[\e[32;49m\]\[\e[39m\]'`

![2021-09-20 150421](https://user-images.githubusercontent.com/72292257/133962299-e8f650a2-fcb4-44c0-8046-356f5faf3826.png)

Should I re-install the Windows Terminal?

**Comment by zadjii-msft** [comment]
Nah, this is a known bug. See /dup #8341 for more info
