### ISSUE TITLE
Japanese Localization issue in Font face, Appearance

### ISSUE THREAD

**Issue by akihironagai** [microsoft/terminal#11278]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

1. Change to Japanese
2. Open Font face on Appearance

### Actual Behavior

仮想 (original: Thin) means virtual.
Normal and Medium are same text (中).
黒 (Black) means black of color, not weight.

![Japanese](https://user-images.githubusercontent.com/77012577/133938717-1600af6e-164f-4166-bb06-8c2965807b2b.PNG)
![English](https://user-images.githubusercontent.com/77012577/133938719-4ecff905-2a49-4d4f-9f32-ad9bd0091b54.PNG)

**Comment by zadjii-msft** [comment]
Thanks! We'll forward this along to the localization team ☺️

**Comment by lhecker** [comment]
Tracked as MSFT:36323577.
