### ISSUE TITLE
A panel for saved commands

### ISSUE THREAD

**Issue by MrGolden1** [microsoft/terminal#11270]
# Description of the new feature/enhancement

Hello to terminal developer team!

I think this is very useful that there would be an option for saved commands/scripts in windows terminal. 

for instance I need to ssh to a server several times a day or set a vpn at beginning of my work. or there is maybe many commands that we use hardly and we don't memorize them, such as resting database, special git command, changing an option in OS and many other things ....
It would be great if we could pick the command we want from an easy accessible place inside of windows terminal. Add, remove, titling, editing before run, pin, most recent and most used commands can be good options for it too. 

# Proposed technical implementation details (optional)

This picture is just for visualize my idea. (I found nothing better than windows clipboard :))
![image](https://user-images.githubusercontent.com/41590281/133887525-6bfb8bce-d8f4-4093-9e72-1aa8c09fa3d5.png)

There is a panel such this that commands are listed in. 

Thanks in advanced.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1595 for more discussion.

/dup #1595
