### ISSUE TITLE
Creating a new Pane in a custom terminal with makes the previous one unresponsive

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/terminal#11284]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19043.1237]

### Other Software

https://www.msys2.org/

### Steps to reproduce

1. Install latest msys2 from https://www.msys2.org/
2. Add the msys2 terminal to windows terminal list
```json
      {
        "commandline": "C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64",
        "guid": "{17da3cac-b318-431e-8a3e-7fcdefe6d114}",
        "name": "msys2",
        "startingDirectory": "%USERPROFILE%"
      }
```
3. Open the msys2 terminal and install zsh `pacman -S zsh` (zsh is required since with bash this bug doesn't appear)
4. Update the `commandline` argument to open the zsh console by default
```json
"commandline": "C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c /usr/bin/zsh",
```
5. Restart the windows terminal
6. Create a new pane
8. Try to write something on the orginal pane, here you will see the console becomes unresponsive for the first pane, though the new one works fine.

### Expected Behavior

I think this is a bug in windows terminal because if I open a new tab the msys2 terminal works fine so, so creating a new pane is affecting to previous panes inside the same tab. I will expect panes are completely independent process from each other.

### Actual Behavior

When using the msys2 console with zsh in the windows terminal, and then creating a new pane, it will make the previous pane to become unresponsive

**Comment by ellipticaldoor** [comment]
I found that starting zsh like this solves the issue

```json
"commandline": "cmd.exe /c \"set MSYSTEM=MINGW64 && set MSYS=winsymlinks:nativestrict && set MSYS2_PATH_TYPE=inherit && C:/msys64/usr/bin/zsh.exe --login -i\"",
```

I'm not sure if I should close this issue though, this seems like a Windows Terminal bug right?

**Comment by carlos-zamora** [comment]
Hi @dortamiguel. It's been a while. Are you still experiencing this issue?
