### ISSUE TITLE
Grouping profiles in drop-down menu

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#11280]
# Description of the new feature/enhancement
Ability to combine profiles in the drop-down menu into groups. For example - I have a VPN cluster. If I add all the servers to the drop-down menu, it will be very inconvenient because with the rest of the profiles it will not fit into the height of the screen. It would be cool if you could make a submenu in a dropdown menu.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
