### ISSUE TITLE
"Ctrl+@" opens a new tab instead of MenuComplete

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11296]
### Windows Terminal version (or Windows build number)

Windows Server 2022 version 10.0.20348.0

### Other Software

Windows Terminal Preview version 1.11.2421.0

### Steps to reproduce

In a terminal window invoke MenuComplete with "ctrl+@"

### Expected Behavior

Complete the input if there is a single completion, otherwise complete the input by selecting from a menu of possible completions.

### Actual Behavior

- When using "ctrl+@" a new tab is being opened, the one assigned to "ctrl+shift+2"

- When using "ctrl+spacebar" key cord MenuComplete works as expected

From help:

```
Completion functions
====================

Key           Function            Description
---           --------            -----------
Ctrl+@        MenuComplete        Complete the input if there is a single completion, otherwise complete the input by
                                  selecting from a menu of possible completions.
Ctrl+Spacebar MenuComplete        Complete the input if there is a single completion, otherwise complete the input by
                                  selecting from a menu of possible completions.
```

Both key cords work as expected in a PowerShell session outside Terminal.

**Comment by DHowett** [comment]
Go into your settings and delete the key binding for Ctrl+Shift+2 to "New Tab, Profile 2".

**Comment by elsaco** [comment]
@DHowett after deleting all profiles but the first one, and restarting the terminal, when pressing Ctrl+Shift+@ opens a new tab.  Here's a sample screenshot with one profile only:

![wt_single_profile](https://user-images.githubusercontent.com/3933920/134228666-90986821-8110-4785-ac6e-cf2301f12134.png)


The only place to change Crtl+Shift+2 is in defaults.json, but there's a warning at the top:

`// THIS IS AN AUTO-GENERATED FILE! Changes to this file will be ignored.`

Do you mean I should edit defautls.json?
