### ISSUE TITLE
MUX 2.7: TerminalTab tabs don't respond to clicks on background

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#11294]
(WHAT)

I noticed that I couldn't click on my PowerShell tab as effectively as I used to, and it looked like I had to mouse over the text or the icon.

I was about to file a bug upstream, but then this GIF showed that the settings tab _does_ respond to clicks on the background. 

![wt-1 12-bug-tab-view](https://user-images.githubusercontent.com/189190/134203090-58619caa-0337-422e-9eea-bbd7d565620d.gif)

Perhaps there's something about how we're setting the background?

**Comment by serd2011** [comment]
Once you hover over the title it starts to register it

![Композиция 1](https://user-images.githubusercontent.com/45919738/134218577-bb342a27-1541-4386-9983-7ee6aad8cae3.gif)

**Comment by serd2011** [comment]
Reverting https://github.com/microsoft/terminal/commit/cfe14e87118b2bd11c5f732afa0d336227fac5ce seem to fix it

**Comment by DHowett** [comment]
Thanks! Unfortunately, we can't stay on MUX 2.5 forever!

**Comment by gabrielconl** [comment]
Wouldn't it be better if Terminal instead used a fork of TabView? You could allow only small changes and fixes, but this way you wouldn't have to wait on MUX.

**Comment by zadjii-msft** [comment]
@gabrielconl Since we work in the same (virtual) hallway as the WinUI team, we'd rather ingest the whole of MUX so that we can be guniea pigs for them and help drive up their quality for all their users 😄

**Comment by zadjii-msft** [comment]
Oh man. Let's play "can you figure out the root cause just from a gif":
![gh-11294-color](https://user-images.githubusercontent.com/18356694/135281495-55cb5b3f-b4d9-4c90-aa92-3f11615bd96d.gif)
