### ISSUE TITLE
Normal right click context menu option

### ISSUE THREAD

**Issue by Zingam** [microsoft/terminal#11304]
Normal right click context menu option with Copy & Paste menu items like in a normal Windows context, etc. which replaces the current right click direct actions.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+context+menu+copy+paste+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #3337 for more discussion.

/dup #3337
