### ISSUE TITLE
Black is not actually black

### ISSUE THREAD

**Issue by MarzaElise** [microsoft/terminal#11302]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.10.2383.0

### Steps to reproduce

- Set a dark image as the background. I used [this](https://i.pinimg.com/originals/09/44/cf/0944cf5784c710241cfe97ea237222d9.jpg)
- Set this for "defaults" key in the profiles section settings.json 
```
{
        "acrylicOpacity": 1.0,
        "backgroundImage": "path/to/the/pic",
        "backgroundImageAlignment": "center",
        "backgroundImageOpacity": 1.0,
        "backgroundImageStretchMode": "uniform",
        "colorScheme": "Custom Theme",
        "cursorShape": "filledBox",
        "experimental.retroTerminalEffect": false,
        "font": 
        {
            "face": "Cascadia Code",
            "size": 11
        },
        "hidden": false,
        "useAcrylic": true
},
```
- Set the "Custom Theme" colorScheme to this
```
{
      "background": "#000000",
      "black": "#000000",
      "blue": "#00B0FF",
      "brightBlack": "#686868",
      "brightBlue": "#6871FF",
      "brightCyan": "#60FDFF",
      "brightGreen": "#06C02E",
      "brightPurple": "#D682EC",
      "brightRed": "#FF6E67",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#E5F323",
      "cursorColor": "#FFFFFF",
      "cyan": "#76C1FF",
      "foreground": "#FF0000",
      "green": "#00FF9C",
      "name": "Custom Theme",
      "purple": "#D57BFF",
      "red": "#FF1044",
      "selectionBackground": "#0004F7",
      "white": "#C7C7C7",
      "yellow": "#C5C21D"
},
```

### Expected Behavior

The Borders to be invisible like this

![screenshot](https://media.discordapp.net/attachments/855060255443779604/890202950163660840/unknown.png?width=792&height=406)

Note: The borders become invisible like this when I'm focusing on another window

### Actual Behavior

- Borders are clearly visible

![screenshot](https://media.discordapp.net/attachments/855060255443779604/890202886825467914/unknown.png?width=788&height=406)

- Note: It becomes *almost* invisible when setting "background" to `#000001` like this

![another screenshot](https://media.discordapp.net/attachments/845739412867514442/890253735580803112/unknown.png?width=802&height=406)

**Comment by DHowett** [comment]
In your "actual behavior" screenshot, it looks like that's the acrylic background material. Your settings seem to contain `"useAcrylic": true`, which turns on the acrylic material... which adds a little bit of light-colored noise.

If you turn acrylic off, does the background become actually-black?

**Comment by zadjii-msft** [comment]
Curious about `"useAcrylic": true, "acrylicOpacity": 1.0`. That should be effectively off though...

**Comment by DHowett** [comment]
Admittedly, though, this suggests a purpose for "fully opaque acrylic" for people who really do want that textured background...

**Comment by MarzaElise** [comment]
> Thanks for filing!
> 
> In your "actual behavior" screenshot, it looks like that's the acrylic background material. Your settings seem to contain `"useAcrylic": true`, which turns on the acrylic material... which adds a little bit of light-colored noise.
> 
> If you turn acrylic off, does the background become actually-black?

That fixed the problem! Thanks for quick response. I didnt actually know what useAcrylic did 😁
