### ISSUE TITLE
Can't send Ctrl-C to terminal to stop Docker container

### ISSUE THREAD

**Issue by hongooi73** [microsoft/terminal#11301]
### Windows Terminal version (or Windows build number)

1.10.2383.0, Windows version 10.0.18363.1734

### Other Software

Docker version 20.10.8, build 3967b7d

### Steps to reproduce

1. Run a docker container with `docker run`
2. Try to stop it by pressing Ctrl-C

My use case was a Jupyter notebook image, but presumably this happens with any image that you run in the foreground.

```
docker pull jupyter/base-notebook
docker run -p 8888:8888 jupyter/base-notebook
```

### Expected Behavior

It should stop the container

### Actual Behavior

The Ctrl-C is ignored, container keeps running

**Comment by DHowett** [comment]
Is this Docker for Windows, Docker for WSL 2, or traditional Docker Desktop with the legacy "Docker Container" VM?

Does this happen outside of the Terminal?

**Comment by hongooi73** [comment]
This is Docker for Windows, using WSL2 as the backend.

**Comment by DHowett** [comment]
If you use Docker outside of the Windows Terminal (just using the traditional console), does it still happen?

**Comment by hongooi73** [comment]
Hm, the same thing happens with cmd.exe, so it must be a problem with docker.

**Comment by DHowett** [comment]
Curious. Given that it happens in the traditional console, I'm going to guess that this is an issue in `docker.exe`; they may be suppressing the console ^C handler on Windows erroneously when they should only do that for an interactive/tty connection.

It may be worth filing at https://github.com/docker/for-win :smile:
