### ISSUE TITLE
Activates the NVIDIA overlay like a game

### ISSUE THREAD

**Issue by Zingam** [microsoft/terminal#11303]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

Start the application.

### Expected Behavior

Shouldn't display the overlay like a game. Maybe you need some sort of API.

### Actual Behavior

Activates the NVIDIA overlay

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+nvidia+overlay) when filing new issues. This is already being tracked by another issue on our repo - please refer to #11230 for more discussion.

/dup #11230
