### ISSUE TITLE
Text display area does not scale correctly

### ISSUE THREAD

**Issue by zdavidsen** [microsoft/terminal#11317]
### Windows Terminal version (or Windows build number)

Windows Terminal version 1.10.2383.0

### Steps to reproduce

1. Open Windows terminal (spawns on primary/1080p monitor)
2. Execute commands till text reaches the bottom of the window
3. Move window to secondary monitor (4k, 125% scaling)
4. Text at bottom and right is cut off, and scrolling does not update the bottom of the window
5. Input is also cut off at the bottom, so I can't see what I'm typing

### Expected Behavior

The text display area should scale correctly 

### Actual Behavior

Window on 1080p monitor:
![image](https://user-images.githubusercontent.com/22267435/134522778-3e56b99c-2a47-4b93-b7a0-3b892d28db36.png)

Window on 4k monitor:
![image](https://user-images.githubusercontent.com/22267435/134522820-7496b03d-42c7-4e86-a1d2-93cfefdaca12.png)

Scrolling also seems to only affect the top 3 lines while on the 4k display?
![image](https://user-images.githubusercontent.com/22267435/134523101-64418b9b-7cc0-46ec-af7a-5d861622806c.png)

And there's also something about cutting off the output of commands above the fold, which seems to apply regardless of monitor:
![image](https://user-images.githubusercontent.com/22267435/134523538-a066b8b4-9dda-486e-8789-94eb5d2217f8.png)

I also just accidentally discovered that resizing the window fixes both the text display area and the scrolling issue on the 4k monitor

**Comment by zadjii-msft** [comment]
From _@itsamemarkus_ in 11659


> ### Windows Terminal version (or Windows build number)
> 1.11.2921.0
> 
> ### Steps to reproduce
> Use 4k and lower resolution monitor. **Start new terminal session on lower resolution monitor.** Drag window from lower resolution monitor to 4k monitor.
> 
>  https://user-images.githubusercontent.com/34944988/139568896-2e4caeda-0e05-4632-a86e-1195f2e68a17.mp4
>
> Windows Terminal 1.11.2921.0 Windows 21H1 19043.1320
> 
> ```
> BitsPerPixel : 32
> Bounds       : {X=3840,Y=1,Width=1680,Height=1050}
> DeviceName   : \\.\DISPLAY1
> Primary      : False
> WorkingArea  : {X=3840,Y=1,Width=1680,Height=1010}
> 
> BitsPerPixel : 32
> Bounds       : {X=0,Y=0,Width=1920,Height=1080}
> DeviceName   : \\.\DISPLAY2
> Primary      : True
> WorkingArea  : {X=0,Y=0,Width=1920,Height=1040}
> 
> BitsPerPixel : 32
> Bounds       : {X=-1680,Y=0,Width=1680,Height=1050}
> DeviceName   : \\.\DISPLAY3
> Primary      : False
> WorkingArea  : {X=-1680,Y=0,Width=1680,Height=1010}
> ```

**Comment by lhecker** [comment]
I have two 4k monitors and set one to 100% and the other to 300% scale.
With that setup I can't replicate this issue in Windows Terminal 1.12.10393.0.

**Comment by zadjii-msft** [comment]
See, I dunno about that. I feel like the root cause has got to be somewhere in the `TermControl` / `Renderer` area. Look at the screenshot [above](https://github.com/microsoft/terminal/issues/11317#issuecomment-945676588). The scrollbar is positioned correctly, but seemingly the DX surface isn't? Either the `SpawChainPanel` didn't get resized up, or the `Control` didn't resize the actual swapchain to the new size. 

It's just annoying that we seemingly can't get a local repro even with a bunch of reports of this 😕 Even if we did have a psychic debugging theory why this happened, we'd have no way to confirm the fix.

**Comment by itsamemarkus** [comment]
I haven't changed my setup except regular updates and the bug appears to be gone.

**Version where I experienced the bug**
Windows Terminal 1.11.3471.0 Windows 21H2 19044.1526

**Current version where I don't have the bug**
Windows Terminal 1.11.2921.0 Windows 21H1 19043.1320

**Comment by zadjii-msft** [comment]
Hey anyone who's still hitting this: (@zdavidsen, @flcdrg, @itsamemarkus, I think @oising was as well) - any chance you're using the `font` object in your profile settings somewhere? The fix in #12492 just has me curious.

**Comment by zdavidsen** [comment]
Huh, changing the `font` seems to do it.  Default is 12, I have all of my profiles set to 10.  If I change them back to 12, then the scaling issue goes away.

**Comment by zadjii-msft** [comment]
WHAT

**Comment by flcdrg** [comment]
@zadjii-msft my profile is [here](https://gist.github.com/flcdrg/db52f72b9e63d01d15c36840e4175d2f)

The only reference to font is for PowershellCore

```json
               "font": 
                {
                    "face": "CaskaydiaCove NF"
                },
```

though that is my default profile. I have not changed the font size

**Comment by lhecker** [comment]
Alright so for some weird reason I can only consistently reproduce it if I do these exact steps:
* use Cascadia Code 10pt
* print text (`Get-Help Get-ChildItem`)
* _then_ resize the window to be smaller
* _then_ scroll up slightly
* and only then move the window to the higher DPI one

**Comment by oising** [comment]
I'm not sure if this is related, but if I have terminal on my external monitor, then undock, I *always* get a screwed up/clipped window. Maximize/restore fixes it. I just got used to it. Example:

![image](https://user-images.githubusercontent.com/1844001/154185593-bd1bc25d-bdf5-4266-9fd1-ed2b3278cb1c.png)

**Comment by oising** [comment]
And yes, I use a one of the nerdfonts modified Cascadia fonts, I think (for oh-my-posh)

**Comment by zdavidsen** [comment]
Just in case this helps at all, here's my [full profile](https://github.com/microsoft/terminal/files/8080335/settings.txt)
