### ISSUE TITLE
tab support

### ISSUE THREAD

**Issue by tonycody** [microsoft/terminal#11316]
now tab is top window.
![image](https://user-images.githubusercontent.com/6773121/134521680-07f0533f-4918-4171-8e1a-2924962466da.png)
It is recommended to support the left and right columns

Can I port Windows Terminal to MacOS again?
Iterm2 on MacOS is ugly

**Comment by zadjii-msft** [comment]
Please search when filing new issues, and [refer to the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#what-about-porting-the-windows-terminal-to-macos-or-linux).

/dup #835
