### ISSUE TITLE
Easy command for opening Windows Terminal.

### ISSUE THREAD

**Issue by TechStudent11** [microsoft/terminal#11311]
# Description of the new feature/enhancement

I feel like a command to access Windows Terminal would be helpful. Instead of having to search for Windows Terminal or having to pin it (to the taskbar), you could just press `Win + R` to open the Run box and then type a simple command like "winterm" or something like that.

# Proposed technical implementation details (optional)
Press `Win + R` to open the Run box and then type a simple command like "winterm" or something like that.

I'm not sure if this exists, though.

**Comment by franky920920** [comment]
@TechStudent11  The command is `wt`

**Comment by zadjii-msft** [comment]
Yep, please [read the docs](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows).

**Comment by TechStudent11** [comment]
Ah, thanks!
