### ISSUE TITLE
Rename window command should automatically focus the new name textbox

### ISSUE THREAD

**Issue by Rosefield** [microsoft/terminal#11322]
### Windows Terminal version (or Windows build number)

1.11.2421

### Steps to reproduce

Run the `Rename window...` command from command palette, focus is lost from the window until something is clicked.

### Expected Behavior

The new name textbox should be focused.

### Actual Behavior

Nothing in the window is focused until I click into it with my mouse.

**Comment by zadjii-msft** [comment]
So, yes I suppose we should track this on our side too. From the window renamer code:

https://github.com/microsoft/terminal/blob/2be394f421b9b23a15e5573fb02b9c7a25768941/src/cascadia/TerminalApp/AppActionHandlers.cpp#L835-L846

So, we'll also need microsoft/microsoft-ui-xaml#1607
