### ISSUE TITLE
wt.exe does nothing within WSL Ubuntu

### ISSUE THREAD

**Issue by cseitz** [microsoft/terminal#11321]
### Windows Terminal version (or Windows build number)

10.0.19043.1237

### Other Software

Windows Terminal and Windows Subsystem for Linux

### Steps to reproduce

Run `wt.exe` within WSL bash. Nothing happens, yet no error.

### Expected Behavior

Running many different windows executables within WSL bash works fine:
- `cmd.exe` swaps to windows cmd
- `explorer.exe .` opens windows explorer from within WSL bash's current directory.
- `notepad.exe file` opens notepad for that file on windows, yet triggered within WSL bash

But `wt.exe` does nothing..?

I know Windows Terminal is for windows and not linux; but the interoperability between many things in windows and WSL is very nice, yet Windows Terminal is lacking it. 

I imagine it wouldn't be too difficult to implement a Linux executable that just does pass-through via `cmd.exe` to `wt.exe` or just adjust Windows Terminal's cli input to work with linux.

I'm not saying WT should be installable on linux; just able to open a new WT window or tab from within WSL bash. You can literally run `cmd.exe /c 'wt.exe'` and it works; so why not properly implement it and have it be built-in to Windows Terminal?

### Actual Behavior

When running `wt.exe` within WSL bash, nothing happens. No error; just nothing.

This is not on par with many other commands listed in the `Expected Behavior` section.

**Comment by zadjii-msft** [comment]
This is unfortunately by design. `wt.exe` is an execution alias, and these to not work in WSL.

See [the docs](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=linux): 
> Execution aliases do not work in WSL distributions. If you want to use `wt.exe` from a WSL command line, you can spawn it from CMD directly by running `cmd.exe`. The `/c` option tells CMD to terminate after running.

I believe the issue is being tracked by /dup https://github.com/microsoft/WSL/issues/7303
