### ISSUE TITLE
How can I set the terminal proxy for the firebase login? "export http_proxy = "x.x.x.x:xx"" cannot work 

### ISSUE THREAD

**Issue by nocsg** [microsoft/terminal#11333]
### Windows Terminal version (or Windows build number)

the lastet win10

### Steps to reproduce

firebase login failed

### Actual Behavior

cannot access account.google.com

**Comment by zadjii-msft** [comment]
What makes you think that this is a Terminal issue? Does this work in a vintage console window (`conhost.exe`)? What shell are you using? Are you using WSL, git bash, something else? You have to give us more info.
