### ISSUE TITLE
Multiple failing unit tests

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#11339]
### Windows Terminal version (or Windows build number)

10.0.18363.1500, Commit 2be394f421b9b23a15e5573fb02b9c7a25768941

### Steps to reproduce

1. Checkout a recent version of the Terminal.
2. Build the code.
3. Execute `runut` in the tools directory.

### Expected Behavior

The unit tests should all pass.

### Actual Behavior

I'm getting quite a lot of failures.

    TerminalAppLocalTests::CommandlineTest::ParseFocusTabArgs#metadataSet0 [Failed]
    TerminalAppLocalTests::CommandlineTest::ParseFocusTabArgs#metadataSet1 [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnGeneratedNamedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnBadJson [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInIterableCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterableInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestMixedNestedAndIterableCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterableColorSchemeCommands [Failed]
    TerminalAppLocalTests::TabTests::MoveFocusFromZoomedPane [Failed]
    SettingsModelLocalTests::ProfileTests::TestGenGuidsForProfiles [Failed]
    SettingsModelLocalTests::DeserializationTests::TestLayerUserDefaultsOnDynamics [Failed]
    SettingsModelLocalTests::SerializationTests::Profile [Failed]

I haven't actually looked to see what's going wrong, so it's possible it's just me.

**Comment by zadjii-msft** [comment]
Yep, I've got a similar set of errors over here. I'm gonna tap in @lhecker for his settings refactor work.

**Comment by lhecker** [comment]
Oh... We don't run those as part of CI, right? I forgot about that...

**Comment by Rosefield** [comment]
I added a fix to the `MoveFocusFromZoomedPane` test (to make it confirm that we are still zoomed instead of not zoomed) to #11153
