### ISSUE TITLE
Feature Request: Ability to Setup Custom Tasks/Startup scripts for New Tabs

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [microsoft/terminal#1133]
# Summary of the new feature/enhancement

Other terminals, like ConEmu, allow users to setup custom startup script (known as tasks in ConEmu). This would be quite handy in some scenarios requesting running a startup script, like Anaconda PowerShell Prompt.

![ConEmu running Anaconda PowerShell Prompt](https://user-images.githubusercontent.com/32929636/58846179-dbb5c680-86b0-11e9-9c25-95bcb8da7e25.png)

**Comment by Summon528** [comment]
This is also an easy way to have a SSH profile

**Comment by zadjii-msft** [comment]
You mean like setting a custom commandline?

For example, my profile for doing Terminal development:
![image](https://user-images.githubusercontent.com/18356694/58880972-c899fb00-869e-11e9-9c56-95cbb5665434.png)

where `#work 1` is a script that basically just calls `cd <path to Terminal repo> && tools\razzle.bat`

**Comment by Aster-the-Med-Stu** [comment]
Oh never noticed that in the config setting... Hoping that in the future the GUI settings would include this.

**Comment by fredrikaverpil** [comment]
Anyone know how to achieve this but with Powershell Core instead?

I have this, but it doesn't work, as the `pwd` command doesn't seem to be executed at all:

```
"commandline" : "C:\\Program Files\\PowerShell\\6\\pwsh.exe -noexit -c pwd",
```

**Comment by remcolam** [comment]
So how do I get I the visual studio developer commandline batch file to execute?

`"commandline" : "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\"",`

The above isn't working, I get: 'C:\Progam'  is not recognized as an internal or external command, operable program or batch file.

I think I am correctly escaping the quotes to get the full path to the batch file in there
