### ISSUE TITLE
Schema type in "backgroundImage" property needs proper formatting

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11349]
### Windows Terminal version (or Windows build number)

1.11.2421.0

### Steps to reproduce

- open "doc/cascadia/profiles.schema.json"
- inspect property beginning at line 1441
- check type on line 1445

### Actual Behavior

- type on line 1445 need fixing, see arrow

        "backgroundImage": {
          "description": "Sets the file location of the image to draw over the window background.",
          "oneOf": [
            {
              "type": ["string", null]  <-- null needs to be double quoted
            },
            {
              "enum": [
                "desktopWallpaper"
              ]
            }

**Comment by zadjii-msft** [comment]
Huh, I suppose it does: http://json-schema.org/understanding-json-schema/reference/null.html#null

I'd bet that's not the only one.
