### ISSUE TITLE
History size autoincrementing

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11342]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.11.2421.0

### Steps to reproduce

- in a profile set max history size to 2147483647 (max signed int)
- use mouse to increment by one

### Expected Behavior

- increment by one, in this case it should rollover to zero

### Actual Behavior

- the counter keeps autoincrementing without anymore user input (no more mouse clicks)

Short demo:

https://user-images.githubusercontent.com/3933920/134912073-f3b307df-3e36-40d3-9980-b23290be0b4e.mp4

Note: this doesn't happen if the keyboard is used to navigate, tab and arrow-key.

**Comment by carlos-zamora** [comment]
Hi @elsaco! We've completely redesigned the settings UI so the XAML controls in question have been replaced/updated. Are you still experiencing this issue?
