### ISSUE TITLE
startupActions don't trigger on launching from context menu

### ISSUE THREAD

**Issue by TheHussein** [microsoft/terminal#11348]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Steps to reproduce

I've added the following line to my `settings.json`:
`"startupActions": "split-pane -V; move-focus left; split-pane -H; move-focus right; split-pane -H;move-focus left;move-focus up"`

This is to open 4 panes. I would like this to always happen. However this does not happen when I open from the context menu in a folder, I just get one in that case.

### Expected Behavior

To get 4 panes when I launch from the context menu.

### Actual Behavior

I get 1 pane when I launch from the context menu.

**Comment by zadjii-msft** [comment]
Hmm. Good point. This is sorta like "I want the _terminal_ to set it's working directory when invoked from the shell context menu, not just the `startingDirectory` for the profile". Kinda like the `wt --cwd C:\foo new-tab` I mentioned in #9991.

In the past we've marked this request (see #9749) as /dup #6111 So I've gone and added notes there. Thanks!
