### ISSUE TITLE
"Close Tab" shortcut doesn't work

### ISSUE THREAD

**Issue by mangkoran** [microsoft/terminal#11347]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

- `PowerShell` 7.1.4
- [ArchWSL](https://github.com/yuk7/ArchWSL), running WSL2
- `fish` 3.3.1 inside Arch

### Steps to reproduce

1. Open `wt.exe`
2. Hover on the "X" beside the tab name
3. It will say "Close Tab (Ctrl + F4)
4. Hit `<Ctrl-f4>`
![image](https://user-images.githubusercontent.com/57625126/135065615-8fc035be-349d-4660-88e6-ad4d1bf671c4.png)

### Expected Behavior

Focused tab will be closed

### Actual Behavior

Focused tab is not closed

**Comment by mangkoran** [comment]
For the time being, I use "Close Pane" shortcut (`<Ctrl-Shift-w>`).

**Comment by zadjii-msft** [comment]
This is actually more correctly /dup #10109. WinUI is providing that tooltip for us, and we need to override it somehow.

**Comment by mangkoran** [comment]
![image](https://user-images.githubusercontent.com/57625126/135090757-989d48c8-f8d4-49d2-97dd-7384ba657d72.png)
Here said "Close Pane". Are "Pane" and "Tab" the same?

**Comment by zadjii-msft** [comment]
Nope. A "tab" can host many "panes". Fortunately though, if you try to close the only pane in a tab, it'll also close the tab, so `closePane` is a more general-purpose action than `closeTab`. For more reading, see the docs:
* [Panes](https://docs.microsoft.com/en-us/windows/terminal/panes)
* [`closeTab`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-tab)
* [`closePane`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-pane)

**Comment by mangkoran** [comment]
Ah I see. However, when I search the "Command Palette", there is no Close Pane. Is it unset by default?
![image](https://user-images.githubusercontent.com/57625126/135092050-963c412d-df9e-42f2-ba12-e152b3795664.png)

**Comment by zadjii-msft** [comment]
That's correct. "Close Tab" isn't bound by default because "Close Pane" does the job for most people.
