### ISSUE TITLE
Miscellaneous Settings UI nits

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#11353]
_discovered in the 1.12 bug bash on 9/28, but these aren't 1.12 blocking issues_

* [x] Navigation View Sidebar] the names of the new VS names don't fit (nor do they get a tooltip) 
  -  Proposal: add tooltips? Don't just crop? 
  - Fixed in #12448
* [x] [Actions page] there's an unnamed action (appears as `Microsoft.Terminal.Settings.Editor.KeyBinding`). After adding it, when clicking "Add new" again or saving, it disappears. Saving it also doesn't appear in the JSON. 
* [x] [Appearance tab of a profile] Background image path does not appear in the text box
* [x] [Appearance tab of a profile] "Reset to inherited value" button for the padding slider needs to be hit twice to make the button go away
* [x] ![image](https://user-images.githubusercontent.com/18356694/135151407-431423ed-4a61-4e19-b00c-45cb2691ec45.png) Needs padding under it, 
  * [x] ... should be lowercase a on appearance, 
  * [x] ... should probably have "Add" after the plus button 
  * [x] ... and scoot the button to the left (same distance that the rename button has with the color scheme dropdown)
  * fixed in #12451
* [x] ![image](https://user-images.githubusercontent.com/18356694/135151440-ddb6b3c4-a9e8-42c3-8685-05554e1acc15.png) Button should have "Delete" after the icon
* [x]  "Intense Text Style" Also lowercase t and s on text style
* [ ] The settings icon in the tab should be updated to the new gear icon (used in the Open JSON file nav item) 
![image](https://user-images.githubusercontent.com/48369326/153055317-da8ec0b7-b476-4f36-af89-09d614a947af.png)
  - Mike note: I'm on this. There's a lot of places we use the wrong font
  - in #12469

<hr>

The following were noted after #12241 merged
* [x] The commandline box could be wider. It takes up a fairly low percent of the expander, esp. when the terminal is maximized 
![image](https://user-images.githubusercontent.com/18356694/151963472-72673386-979a-44ab-bfd7-81e14e2fb0a7.png)
  - Fixed in #12326
* [x] #12328
* [x] #12335
* [x] #12350
* [ ] #12359
* [ ] more...

**Comment by StanzillaManticore** [comment]
Imo, the hamburger menu in the settings should be removed, it's really not doing any good for UX and just takes space.

**Comment by zadjii-msft** [comment]
@StanzillaManticore Fair point! How do you propose expanding the nav view when the window is relatively narrow, without the hamburger?

![image](https://user-images.githubusercontent.com/18356694/152407988-46e3a7d3-c1d4-402f-a7d9-738181ef226c.png)

![image](https://user-images.githubusercontent.com/18356694/152408012-ea2ce900-cafb-4968-a80a-9549b8925fb5.png)

**Comment by Stanzilla** [comment]
Oh accidently used my work account, so, I would do the same thing that it does currently where it hides the label when the window gets too small but otherwise always display them.

**Comment by Tropix126** [comment]
One thing that might look better would be making the settings backdrop a single color. From what I've seen, NavigationView isn't really designed to look right with TabView above it, which results in these sort of cut-off corners, rather than the NavigationView blending in the the window's titlebar.

![image](https://user-images.githubusercontent.com/42101043/152550003-cfa825f0-5f7a-406a-8c24-972a18c13412.png)
