### ISSUE TITLE
Unexpected focus when closes tab.

### ISSUE THREAD

**Issue by therealchiendat** [microsoft/terminal#1136]
# Environment

```
Windows build number: Windows 10 Education 1903

```

I noticed tab focus issue when three or more tabs opened. If a tab different from the latest opened tab is closed, the terminal app will show two tabs as "active".

The two active tabs will not be gone until the wrong active tab is clicked on.

![image](https://user-images.githubusercontent.com/44085158/58896814-2c3b1d00-86cd-11e9-8738-71b9e7e1b800.png)

**Comment by zadjii-msft** [comment]
More specific repro steps:

1. open 3 tabs. (Screenshots are done with 4 tabs, to make the issue more apparent, but repros with 3 tabs)
![image](https://user-images.githubusercontent.com/18356694/58916208-9c0ad100-86e8-11e9-8c51-9615c900a785.png)
2. with the 3rd selected, middle click the first, to close it.
3. Now, the 3rd tab is the second, and is focused. The old second tab is now the first tab.
![image](https://user-images.githubusercontent.com/18356694/58916224-a7f69300-86e8-11e9-91e2-e35dd9117f31.png)

4. click on the first tab to focus it. Both the first and second tabs will highlighted as if they're focused. 
![image](https://user-images.githubusercontent.com/18356694/58916179-82698980-86e8-11e9-86e0-e72c7b918c0d.png)

**Comment by zadjii-msft** [comment]
It's possible this is fixed by #1117

**Comment by Summon528** [comment]
Unfortunately, #1117 does not fix this

**Comment by cinnamon-msft** [comment]
I can't seem to repro this anymore?

**Comment by therealchiendat** [comment]
This issue seems to be fixed the last time I checked.
