### ISSUE TITLE
Typing in an invalid background image path IN THE SUI will send the Terminal to a farm upstate

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#11361]
Presumably we try to load the image, fail, but don't catch the exception.

Only happens in the SUI, presumably on load we pre-validate the path and ignore bad ones.

I bet it happens for any images... no, that's the only one that live previews, so that's the one.

Happens in 1.10 Stable too 🤦

**Comment by WSLUser** [comment]
This bug has existed for awhile, and for offline installations, the solution is to simply replace the path with a valid one (copy/paste the file url). I figured it was only related to offline and wouldn't get resolved but if Store installations also have this problem, it would be great to see this fixed.
