### ISSUE TITLE
In a coming Terminal version, we'll be bumping the MinVersion to 10.0.19041.0 / 2004 / Vb

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#11371]
_(for MSFT folks, this is bumping the min version from 19H1 to Vb)_

There's a couple big reasons why:
* Vintage opacity only works on Windows 11, and the bug fix will only be serviceable to 19041. 
  * Work was done in #11285 to mitigate this, which can be reverted when we bump the min version
* The OS-side fix to #8238, https://github.com/microsoft/microsoft-ui-xaml/issues/3953, which we need for #1571, will similarly only be able to make it back to 19041
* 18362 (our current min version) "reached end of service after the release of build 18362.1256 on December 8, 2020"<sup>[1](https://support.microsoft.com/en-us/topic/december-8-2020-kb4592449-os-builds-18362-1256-and-18363-1256-expired-c448f3df-a5f1-1d55-aa31-0e1cf7a440a9)</sup> so it's high time y'all updated

When we do this, we should make sure to revert the changes that fixed #11285

**Comment by LoganDark** [comment]
I have 19041.928, is that covered or do you really only support 20H1 now?

**Comment by zadjii-msft** [comment]
@LoganDark I'm under the impression that 20H1 is build number 19041, so that should work.
