### ISSUE TITLE
Some characters are not rendered at small font sizes

### ISSUE THREAD

**Issue by boltronics** [microsoft/terminal#11376]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

tree v1.8.0 (inside a Debian WSL2 environment)

### Steps to reproduce

Set the Font size to 8, and Font face to something like Consolas, or Liberation Mono.

Alternatively, set Font size to 9 and set Font face to [Terminus (TTF) For Windows](https://files.ax86.net/terminus-ttf/) (my personal preference).

Run `tree`

(or run `pass` or any other software that relies on it).

### Expected Behavior

You should see something like:
```
~$ tree dir
dir/
├── file1.txt
└── file2.txt
```

### Actual Behavior

Instead, you'll see something like:
```
~$ tree dir
dir/
    file1.txt
    file2.txt
```

It took me a lot of testing to figure out that I needed to bump my font size up for these characters to render, since every font I tried wouldn't show it (although that was apparently just luck since some fonts do render the lines with varying degrees of success). I initially thought the colour was somehow matching the background, since the characters were present since I could copy them. Unfortunately, I find that increasing the font size to the required degree is not acceptable.

A more acceptable work-around is to define a shell function like so:
```
~$ tree() { TREE_CHARSET='C' /usr/bin/tree "${@}" ; }
~$ tree testdir/
testdir/
|-- file1.txt
`-- file2.txt

0 directories, 1 file
~$
```
Of course it still looks more ugly than it should, but at least it shows something without affecting everything else.

If I `apt install terminator` and the Terminus fonts and run it under VcXsrv, it works perfectly.

![image](https://user-images.githubusercontent.com/250531/135379139-cbf42e61-b8dd-449f-90b9-f7185767f7f6.png)
(Windows Terminal on the left, [Terminator](https://gnome-terminator.org/) on the right)

**Comment by elsaco** [comment]
@boltronics  "tree -A" turns on ANSI line graphics hack. Works every time!

**Comment by boltronics** [comment]
@elsaco Thanks for the suggestion. Unfortunately that made no difference for me.
![image](https://user-images.githubusercontent.com/250531/135384562-7ed97d39-717c-4e96-a601-cfd911c96fae.png)
Also, when pressing Ctrl+C because I accidentally ran `tree -A` across a large directory, I got the corruption you see in the top pane. I've never seen that happen before (although that'll be unrelated).

**Comment by boltronics** [comment]
FWIW, corruption was fixed with `echo ^N` (that's ctrl+v, ctrl+n) although I could have just reopened a new window I guess.

**Comment by j4james** [comment]
I think this is probably covered by #7927 or #5897 (see for example https://github.com/microsoft/terminal/issues/5897#issuecomment-803492674). Possibly also #6161.

**Comment by boltronics** [comment]
Thanks @j4james you are right, it's a dupe of #7927 I'd say. Closing.
