### ISSUE TITLE
Windows Terminal Universal (Dev Build)

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11377]
### Windows Terminal version (or Windows build number)

10.0.22463.0

### Steps to reproduce

clone latest WT repo and build solution

### Actual Behavior

A new WT terminal showed in Apps. Upon opening ...don't have a clue what this is!

Every keyboard key press is echoed twice in the terminal. "\appdata\local\temp" does exist and it's a folder.

Demo:

https://user-images.githubusercontent.com/3933920/135382935-146d28f5-5ab8-4843-a6de-e4fc49791531.mp4

**Comment by zadjii-msft** [comment]
The Universal build of the Terminal is an internal-only tool, that frankly isn't really supported or used anymore. It's just hanging around in case we ever need to resurrect it for some new internal project. You can ignore it.
