### ISSUE TITLE
Tab focus issue

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11375]
### Windows Terminal version (or Windows build number)

main 3b3b72e

### Other Software

Windows 10.0.22463.0

### Steps to reproduce

- open multiple tabs
- switch tab using mouse pointer

### Expected Behavior

- tab focus when mouse pointer over entire tab width

### Actual Behavior

- tab focus only when mouse pointer is above icon + tab title

Demo:

https://user-images.githubusercontent.com/3933920/135363757-f69240d2-6131-475e-9c1a-29926bb91b9e.mp4

**Comment by Rosefield** [comment]
This was probably fixed in https://github.com/microsoft/terminal/pull/11369

**Comment by elsaco** [comment]
@Rosefield that's correct, sir! Here's short demo with build from 37e8769b

https://user-images.githubusercontent.com/3933920/135372117-66370bd9-7335-4704-aa52-e8d099bee405.mp4
