### ISSUE TITLE
Navigation scrollbar covering icons

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11370]
### Windows Terminal version (or Windows build number)

local build from 3b3b72e9

### Steps to reproduce

- open navigation in minimized mode
- observe scrollbar

### Expected Behavior

- scrollbar not covering icons

### Actual Behavior

Sample screenshot:

![navigation_scrollbar](https://user-images.githubusercontent.com/3933920/135295602-5af0e036-95c8-4d23-ac74-e3cc41b08c77.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+navigation+scrollbar+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9346 for more discussion.

/dup #8894
