### ISSUE TITLE
Allow grouping profiles

### ISSUE THREAD

**Issue by Andret2344** [microsoft/terminal#11388]
# Description of the new feature/enhancement

When creatimg multiple profiles, the list start to becoming longer and longer. Frequently, some profiles are similar (e.g. multiple VPS login profiles). In my case, as I'm developing plugins for Spigot, I use multiple versions (see screenshoot).
![image](https://user-images.githubusercontent.com/40674613/135611744-59ca3f7d-3ccd-4cf0-a47a-0b8f069e96e7.png)

It would be great if I could create a group named "Spigot" and add multiple profiles there and then see the cascade in the dropdown menu when opening a new tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+group+profiles) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
