### ISSUE TITLE
Attaching of externally existing terminal

### ISSUE THREAD

**Issue by SebastianSolidwork** [microsoft/terminal#11387]
I want to be able to attach terminals which exist outside of WT.
Examples: log terminals from an application or terminals started through a file from the explorer

Examples of other software: ConEmu and Cmder are having such a function

**Comment by carlos-zamora** [comment]
Hi @SebastianSolidwork. Thanks for the feature request. We've discussed it as a team and we feel that tab tearout and default terminal are two features that are more relevant for day to day use cases. They don't necessarily fulfill all the requirements you specified, but they meet most of them.

**Comment by SebastianSolidwork** [comment]
Thanks for the clarification!
I guess you are referring to this by the default Terminal? https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/
That would be sufficient for me.
But I have to wait until our IT rolls out Windows 11, we are still on 10.

**Comment by SebastianSolidwork** [comment]
I got informed that our IT just now uninstalled all existing Windows 11 and replaced them by to Windows 10.
Therefore I will not get access to this feature soon. :-(
