### ISSUE TITLE
Feature Request: The Terminal window's resize border is too small

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/terminal#1138]
# Summary of the new feature/enhancement

You have to have good precision with your mouse to drag resize the window because the resize area is only a couple of pixels wide. This makes for a frustrating experience when you attempt to drag resize the window.

# Proposed technical implementation details (optional)

Do what the current conshost window does. It provides somewhere between a 6-8 pixel width drag resize area.

**Comment by zadjii-msft** [comment]
:laughing_crying:

We've just had a two hour meeting about window styling and input, and this came up quite a bit during it. I think we have a plan to solve this though, so that's good!

**Comment by zadjii-msft** [comment]
@bitcrazed assures me he's notified the right people to help us get this fixed :)

**Comment by cinnamon-msft** [comment]
#929 Fixes this!

**Comment by glen-84** [comment]
@cinnamon-msft Shouldn't this issue remain open until there's a release?

**Comment by DHowett-MSFT** [comment]
Our policy is that bugs are closed when the change that fixes them reaches `master`. We use the “fix available” and “fix committed” tags to track a fixed bug’s progress to release.

**Comment by glen-84** [comment]
If they have the latest release, and there are no open issues regarding a bug, users may submit duplicates.

Anyway, just a thought. 🙂

**Comment by DHowett-MSFT** [comment]
People do that regardless of whether we close bugs or leave them open. Or even pin them!

**Comment by DHowett-MSFT** [comment]
(Also, thanks for the feedback! We appreciate it. We may want to think a bit more on how we communicate upcoming features and fixes.)
