### ISSUE TITLE
Feature-Request: Add a profile to open "Tab Sets" instead of one-by-one

### ISSUE THREAD

**Issue by AdrianoCahete** [microsoft/terminal#11398]
# Description of the new feature/enhancement

Tried to search in the issues, but cannot find anything with "tab sets" or something like that... :/

The idea is to open a set of tabs, in a panel, for example. Today I'm using cmder and it has that feature: Save a profile with multiple consoles, and when opening, it is self-arranged in sets like panels.

It needed to run projects that work as micro-frontends/micro-services and manage their states.

# Proposed technical implementation details (optional)
Give the ability to save multiple profiles and summon the set/multiple profiles with a shortcut, maybe?

**Comment by Rosefield** [comment]
I'm not sure if it is exactly what you are asking for, but https://github.com/microsoft/terminal/issues/3992 will be added to 1.12 and gives the ability to save an action that runs multiple commands at once, e.g. make an action in your `settings.json` file called "Create My Layout" that will show up in the command palette / as a hotkey

```
{ "name": "Create My Layout", "command": { 
    "action": "multipleActions",
    "actions": [
        // Create a new tab with 3 panes
        { "action": "newTab", "tabTitle": "Work", "colorScheme": "One Half Dark" },
        { "action": "splitPane", "split": "vertical", "profile": "Windows PowerShell", "tabTitle": "Work", "colorScheme": "Campbell Powershell", },
        { "action": "splitPane", "split": "horizontal", "profile": "Windows PowerShell", "tabTitle": "Work", "colorScheme": "Campbell Powershell", },
        // Create a second tab
        { "action": "newTab", "tabTitle": "Misc"},
        // Go back to the first tab and zoom the first pane
        { "action": "prevTab", "tabSwitcherMode": "disabled" },
        { "action": "moveFocus", "direction": "first"},
        "togglePaneZoom"
        ]
}}
```

**Comment by AdrianoCahete** [comment]
The final idea is the same! Thanks!

Do I close this issue now or wait for that issue to be released?

**Comment by Rosefield** [comment]
I'm not a maintainer, I just happened to implement that feature. If you're happy you can close the issue whenever, otherwise I'm sure someone will come along on Monday and do whatever is appropriate.

**Comment by zadjii-msft** [comment]
Yea, this is kinda covered by #3992, a bit covered by #756, and we'll finally let you put these action in the dropdown in #1571. So until then,

/dup #756
/dup #3992
