### ISSUE TITLE
Give user an opportunity to disable a built-in shortcut

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [microsoft/terminal#11403]
# Description of the new feature/enhancement

The built-in shortcut conflicts to my own cli program and I want to disable it. I tried to add an entry to settings.json to assign a new shortcut, but the old built-in one still works. There seems no way to disable a built-in shortcut. Please add a method for users to disable them if necessary. Thanks.

**Comment by j4james** [comment]
If you're using the preview version of Windows Terminal, you should already be able to delete the built-in shortcuts from the actions page. If not, this can also be done in the _settings.json_ file by setting the action command to "unbound". See the documentation here:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#unbind-keys

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks.
