### ISSUE TITLE
Able to launch elevated cmd.exe in new tab

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#11409]
# Description of the new feature/enhancement
Able to launch elevated cmd.exe in new tab, so regular and elevated cmd.exe tabs can coexist in the same WT window

# Proposed technical implementation details (optional)
![image](https://user-images.githubusercontent.com/2054302/135841880-306c78c3-0578-417f-b648-d18677bacdef.png)

![image](https://user-images.githubusercontent.com/2054302/135841917-4ae221d4-efa1-4372-af09-2414f40b7595.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #632 for more discussion.

/dup #632
