### ISSUE TITLE
Shortcut for opening profile by name

### ISSUE THREAD

**Issue by soundnotation** [microsoft/terminal#11410]
# Description of the new feature/enhancement
The same way wt offers a `ctrl+shift+a` to search for open tabs, I'd like a shortcut that lets me open a profile in a new tab by typing (part of) its name.
Kinda like a mix of `ctrl+shift+a` and the profiles list taken from the dropdown menu with the down arrow, but with search functionality on profiles.
I couldn't find any related coverage of this through existing issues/features.

# Proposed technical implementation details (optional)

When typing a shortcut, a list of names of existing profiles (possibly with icons?) with search bar on top should appear. If you type something in the search bar, the list will be filtered and the first item is selected. On typing enter, the profile (if exists) should be opened in a new tab.

**Comment by zadjii-msft** [comment]
Perhaps something like the [command palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette)?

![gh-11410](https://user-images.githubusercontent.com/18356694/135859980-663e88f2-e355-4a84-81fa-dd647e082599.gif)


You probably want #10209 for binding a key directly to "New Tab...", though you could always add actions for "New Tab, Profile {profile.name}" to the root of the palette manually.

/dup #5400
/dup #10209
