### ISSUE TITLE
No cursor (randomly) on profile startup

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#11411]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations 10.0.19043.1237 (2009, 21H1) Windows Terminal Preview 1.11.2421.0

### Steps to reproduce

Do these four steps repeatedly:

1. Open the dropdown menu
2. Click Powershell (or any profile, see below)
3. Without supplying any input, observe whether the cursor appears or not
4. Exit the shell

In case it matters, I use the Vintage, blinking cursor.

### Expected Behavior

The cursor will always show.

### Actual Behavior

The cursor shows (or not) randomly.  The probability of it showing is about .8.

This affects all profiles.  I've tested with Powershell, CMD, TCC, PWSH, Ubuntu, and SSH.  When the cursor fails to show for an SSH profile, it fails to show at the password prompt.

When the cursor has failed to show, any keystroke, or WT losing/regaining the foreground will cause the cursor to become visible.

**Comment by ffes** [comment]
I am experiencing exactly the same problem. For me the cursor is gone more often then it is shown. It indeed seems to be related to using the dropdown menu to open a new profile. When I use a keyboard shortcut or the command panel to start a new profile the cursor seems to be shown always.

It is funny to see when I open a Dev CMD for Visual Studio the cursor is shown before the batch file is executed that initializes the Dev CMD. As soon as the prompt is shown, the cursor is not shown anymore.

FYI, this are my cursor settings (it's a snippet obviously):
 
```json
"profiles": 
{
     "defaults": 
     {
         "cursorColor": "#048322",
         "cursorShape": "filledBox"
     }
},
```

**Comment by zamadatix** [comment]
In `v1.13.10336.0` I now don't see the cursor at all:

![image](https://user-images.githubusercontent.com/343550/152667170-799f7138-d2a1-48b2-98d8-c61c4ed31c11.png)

It also doesn't show in the settings preview:
![image](https://user-images.githubusercontent.com/343550/152667178-fd2ff7d7-6187-41bd-b0c5-34339e5ffe21.png)
