### ISSUE TITLE
Current git source fails to build on 20H2 and VS Community 2019 16.11.2

### ISSUE THREAD

**Issue by darthpale** [microsoft/terminal#11417]
git clone https://github.com/microsoft/Terminal.git
cd Terminal
git submodule update --init --recursive
nuget restore OpenConsole.sln

VS Set to 
Release x64  Cascadia Package

Are the updated build requirements?

That process worked though 9/4/2021.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "pwsh.exe -NoProfile –ExecutionPolicy Unrestricted C:\Users\apd\devel\WT2\Terminal\\tools\GenerateHeaderForJson.ps1 -JsonFile defaults.json -OutPath "Generated Files\defaults.h" -VariableName DefaultJson" exited with code 9009.	Microsoft.Terminal.Settings.Model.Lib	C:\Users\apd\devel\WT2\Terminal\src\cascadia\TerminalSettingsModel\Microsoft.Terminal.Settings.ModelLib.vcxproj	258	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'C:\Users\apd\devel\WT2\Terminal\bin\x64\Release\Microsoft.Terminal.Settings.Model.Lib\Microsoft.Terminal.Settings.Model.Lib.lib'	Microsoft.Terminal.Settings.Model	C:\Users\apd\devel\WT2\Terminal\src\cascadia\TerminalSettingsModel\dll\LINK	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'winrt/base.h': No such file or directory	LocalTests_SettingsModel	C:\Users\apd\devel\WT2\Terminal\dep\wil\include\wil\cppwinrt.h	98	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Profile.g.h': No such file or directory (compiling source file ColorHelperTests.cpp)	UnitTests_TerminalApp	C:\Users\apd\devel\WT2\Terminal\src\cascadia\TerminalSettingsModel\Profile.h	47	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80070002 - Processing Resources failed with error: The system cannot find the file specified.	WindowsTerminalUniversal	C:\Users\apd\devel\WT2\Terminal\src\cascadia\WindowsTerminalUniversal\GENERATEPROJECTPRIFILE	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI252: 0xdef00071 - File C:\Users\apd\devel\WT2\Terminal\bin\x64\Release\Microsoft.Terminal.Settings.Model\Microsoft.Terminal.Settings.Model.pri not found.	WindowsTerminalUniversal	C:\Users\apd\devel\WT2\Terminal\src\cascadia\WindowsTerminalUniversal\GENERATEPROJECTPRIFILE	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80070002 - Processing Resources failed with error: The system cannot find the file specified.	CascadiaPackage	C:\Users\apd\devel\WT2\Terminal\src\cascadia\CascadiaPackage\GENERATEPROJECTPRIFILE	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI252: 0xdef00071 - File C:\Users\apd\devel\WT2\Terminal\bin\x64\Release\Microsoft.Terminal.Settings.Model\Microsoft.Terminal.Settings.Model.pri not found.	CascadiaPackage	C:\Users\apd\devel\WT2\Terminal\src\cascadia\CascadiaPackage\GENERATEPROJECTPRIFILE	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80070002 - Processing Resources failed with error: The system cannot find the file specified.	TestHostApp	C:\Users\apd\devel\WT2\Terminal\src\cascadia\LocalTests_TerminalApp\TestHostApp\GENERATEPROJECTPRIFILE	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI252: 0xdef00071 - File C:\Users\apd\devel\WT2\Terminal\bin\x64\Release\Microsoft.Terminal.Settings.Model\Microsoft.Terminal.Settings.Model.pri not found.	TestHostApp	C:\Users\apd\devel\WT2\Terminal\src\cascadia\LocalTests_TerminalApp\TestHostApp\GENERATEPROJECTPRIFILE	1

**Comment by j4james** [comment]
Have you got PowerShell 7 or later installed? I believe that was a recent change to the build requirements.
See here: https://github.com/microsoft/terminal#prerequisites

**Comment by darthpale** [comment]
Sorry somehow I missed that.  PS7.
