### ISSUE TITLE
Cannot close tab with neither Ctrl-W nor Ctrl-F4 

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#11419]
### Windows Terminal version (or Windows build number)

1.11.2731.0 on 10.0.19042.1237]

### Steps to reproduce

press ctrl-w or ctrl-f4 to close the active tab

### Expected Behavior

close current tab

### Actual Behavior

keys are ignored, tab remains open

**Comment by zadjii-msft** [comment]
Did you add either of those keys to your keybindings in the settings?

**Comment by mailinglists35** [comment]
no, only shift-pgup/phdown because defaults ctrl-shift-pgup/down are not what linux terminal users expect

**Comment by zadjii-msft** [comment]
Well, that'd explain it. Those keys aren't bound by default. You can find a full list of the default keybindings [here](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json#L282-L455). Notably,

```json
{ "command": "closePane", "keys": "ctrl+shift+w" },
```

and "closePane" will close a tab, it it's the only pane in the tab.
