### ISSUE TITLE
Key to request for administrator privileges

### ISSUE THREAD

**Issue by albertopasqualetto** [microsoft/terminal#11418]
# Description of the new feature/enhancement
It would be good having a feature which requests for administrator privileges without opening a new window of the terminal.

# Proposed technical implementation details (optional)
With a button and also a keyboard shortcut to change all the current tab in administrator mode.
Or with a command like sudo.

**Comment by j4james** [comment]
I think what you're suggesting is already being tracked in other issues. See #146, #632, #1032, and #5000.

**Comment by zadjii-msft** [comment]
Yep. Please search before filing new issues. 

/dup #146
/dup #632
