### ISSUE TITLE
Moving the window after opening a dialog will make the window weird

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#11425]
_found in 1.12.2781.0 Bug Bash on 10/5/2021_

REPRO:
	1. Open the Terminal
	2. Edit the json so it's invalid (delete a comma in the settings)
	3. Move the window, so the warning dialog dismisses itself.
	4. Edit the settings again. Leave it invalid. Add a newline
	5. Notice, no dialog (ooooooooooh)
    6. Now try to close the window, that won't work

This certainly regressed when I added support for dismissing that dialog when the window moved.

**Comment by serd2011** [comment]
I think its because it get dismissed as a popup, not as a ContentDialog and the problem is upstream. What do you think?
