### ISSUE TITLE
"singleLine=true" copy/paste issue

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11429]
### Windows Terminal version (or Windows build number)

main 0b552e1a

### Other Software

Windows version 10.0.22471.0

### Steps to reproduce

- open settings.json
- set copy "singleLine" to true
- copy lots of data (a signature block from Install.ps1 in this case)

### Actual Behavior

- multiple inserts after crtl+v
- shell prompt not coming back
- buffer corruption after ctrl+c

Example:

https://user-images.githubusercontent.com/3933920/136127584-36084422-7dac-4a4e-8a9f-37756ee73138.mp4

**Comment by zadjii-msft** [comment]
Does the same behavior repro if you copy the text from somewhere else, like a text editor? My guess is the PSReadline is trying to do something helpful with the leading spaces at the prompt here. How does this behave in other shells?
