### ISSUE TITLE
Default font (Cascadia Mono) no longer available after (PowerShell) crash made Terminal window disapear

### ISSUE THREAD

**Issue by matjojo** [microsoft/terminal#11431]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Steps to reproduce

1. Have a PowerShell and cmd tab open
2. PowerShell crashes
3. Windows Terminal window disappears
4. Launch Windows Terminal again (Using the context menu open here option via explorer)

### Expected Behavior

5. I can open a new cmd tab without a font file no longer being readable
6. I can open a new PowerShell tab without a font file no longer being readable

### Actual Behavior

5. Warning about the font (Cascadia Mono) not being found for the cmd tab (And Consolas being used as fallback)
6. Open a new Powershell tab
6. Warning about the font (Cascadia Mono) not being found for the PowerShell tab (And Consolas being used as fallback)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Unable+to+find+the+selected+font+%22Cascadia+Mono%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9375 for more discussion.

/dup #9375

There is a bug in the application deployment platform on recent versions of Windows that results in the Cascadia Mono font (the default font) being unreadable.

Unfortunately, that means that through no fault of your own, you'll get a dialog that says we can't find Cascadia Mono or Cascadia Code.

### KNOWN SOLUTIONS

* Either reboot or
* choose to "Repair" the Terminal application in the "All apps" list in Settings.
