### ISSUE TITLE
~ not work as startingDirectory for WSL

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#11432]
### Windows Terminal version (or Windows build number)

1.11.2731.0

### Other Software

WSL on Windows 11 version 10.0.22000.194

### Steps to reproduce

Put `~` as `startingDirectory` for a WSL Distro

### Expected Behavior

Start the profile at the `$HOME` directory exactly like when I manualy run the command `wsl.exe --cd "~" ` in PowerShell

### Actual Behavior

In my machine the terminal output say:
Le fichier spécifié est introuvable.

[processus terminé avec le code 4294967295]

**Comment by elsaco** [comment]
@mveril @zadjii-msft  does WT understands Linux user's home path? This is from WSL help:

```
If ~ is used the Linux user's home path will be used. If the path begins
with a / character, it will be interpreted as an absolute Linux path.
Otherwise, the value must be an absolute Windows path.
```

If set to:

` "startingDirectory": "/home/~"` 

it works as expected. One advantage of this is having the WSL debug console launched too, if enabled in .wslconfig. Using %USERPROFILE% as starting directory won't launch the debug console.

**Comment by zadjii-msft** [comment]
> any chance that the patch will be applied before the stable version ?

Considering 1.12 is coming out (likely) tomorrow, and with it 1.11 is getting promoted to stable, I'm gonna guess _no_ 😄

**Comment by mveril** [comment]
Thank you!
I can confirm that it works now! 🎉
