### ISSUE TITLE
Cascadia Mono font missing

### ISSUE THREAD

**Issue by Simran-B** [microsoft/terminal#11433]
### Windows Terminal version (or Windows build number)

10.0.19043.0, 1.10.2714.0

### Steps to reproduce

1. Start Windows Terminal / open a new tab

### Expected Behavior

Window Terminal to start without warning about a missing font, because Cascadia should be included according to the [microsoft/cascadia-code project](https://github.com/microsoft/cascadia-code):

> Cascadia is a fun new coding font that comes bundled with Windows Terminal …

### Actual Behavior

Every time I start Windows Terminal or open a new tab, it shows a message box about not being able to find Cascadia Mono and that it falls back to Consolas:

![image](https://user-images.githubusercontent.com/7819991/136174806-8f36d349-c2a8-48b8-9b10-4d8e23eee919.png)

FWIW, Windows Store had just updated Windows Terminal to 1.10.2714.0 ("changed a few minutes ago"):

![image](https://user-images.githubusercontent.com/7819991/136175689-f05786bc-271c-4663-91e7-a452ad2d04e9.png)

The font family does show up in the system settings (with some delay and only if I hover the area where the fonts should be listed?!)

https://user-images.githubusercontent.com/7819991/136177196-5cc13564-6b16-4165-9ff0-d2d7608a4bde.mp4

It is not listed in Explorer, however:

![image](https://user-images.githubusercontent.com/7819991/136176809-d33a3128-c053-4475-a666-1504c9784bac.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Unable+to+find+the+selected+font+%22Cascadia+Mono%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9375 for more discussion.

/dup #9375

There is a bug in the application deployment platform on recent versions of Windows that results in the Cascadia Mono font (the default font) being unreadable.

Unfortunately, that means that through no fault of your own, you'll get a dialog that says we can't find Cascadia Mono or Cascadia Code.

### KNOWN SOLUTIONS

* Either reboot or
* choose to "Repair" the Terminal application in the "All apps" list in Settings.
