### ISSUE TITLE
initialCols (and initialRows) have an off-by-padding error

### ISSUE THREAD

**Issue by notlaforge** [microsoft/terminal#1143]
# Environment

```
Windows build number: 10.0.18908.1000
Windows Terminal version (if applicable): 880272c7483a3bb6893dbec3725d0eb7375ab78a
```

# Steps to reproduce

0. Set `initialCols` to `16`
0. Launch a new Terminal
0. `echo 0123456789abcdef`

# Expected behavior

`echo`'s output oughtta fit in one line

# Actual behavior

```
0123456789abcde
f
```

**Comment by zadjii-msft** [comment]
Yea this is definitely wrong:
![image](https://user-images.githubusercontent.com/18356694/58961505-e040b480-876e-11e9-9172-4ecd4ebde10c.png)

**Comment by Summon528** [comment]
I think this one is a pretty easy one, I'll try to fix it

**Comment by Summon528** [comment]
The problem here is: what's the intended behavior for the hidden scroll bar. Is it intended to cover some text when expanded or is it intended to always have a reserved space? If it is (2) then the fix will be pretty easy, if it's (1) then we might need to modify the view tree

**Comment by zadjii-msft** [comment]
I think the scrollbar space is always supposed to be reserved (ie case number 2). We tried implementing a alwaysShowScrollbar option before we released as open-source, however, the UWP ScrollBar doesn't actually support a scrollbar styled like that. We'd have to roll our own implementation if we wanted that.

**Comment by Summon528** [comment]
Weird enough I can't repro this anymore, although I think I did nothing. ( I can repro with padding set but I think that is intended? )

**Comment by zadjii-msft** [comment]
Ahhh, that's probably it. I have 2 padding on all sides set too. That's definitely not by design - we should be accounting for the amount of padding when calculating the initial window size.

**Comment by notlaforge** [comment]
Yep, padding here too: `"padding": "2, 2, 2, 2"`
