### ISSUE TITLE
Open with WT fails to open folders with semicolon in name - slight variation of #11273

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11449]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview version 1.11.2731.0

### Other Software

Windows version 10.0.19043.0

### Steps to reproduce

1. select a folder with semicolon in name
2. open  with "Open in Windows Terminal" action

### Expected Behavior

no errors

### Actual Behavior

error 0x80070002, same as #11273 , fixed in 9708a751

This is the directory structure used for testing:

```
PS C:\tmp> tree
Folder PATH listing for volume Windows
Volume serial number is A2A2-41FB
C:.
├───wt
└───wt;test
```

When right-clicking on "C:\tmp\wt;test" the first tab opens "C:\tmp\wt":

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\tmp\wt>
```

and 2nd tab shows: [error 0x80070002 when launching `test\.']

If "C:\tmp\wt" is renamed/remove the first tab shows:

```
[error 0x8007010b when launching `powershell.exe']
Could not access starting directory "C:\tmp\wt"
```

and the 2nd tab: [error 0x80070002 when launching `test\.']

**Comment by zadjii-msft** [comment]
I'm pretty sure  #11273 isn't fixed in 1.11.2731.0

In 1.12:

![gh-11449](https://user-images.githubusercontent.com/18356694/136431059-3393a013-dbdc-4c9a-971e-5b126625dae8.gif)


/dup #11273
