### ISSUE TITLE
"Magenta" is called "Purple" in WT

### ISSUE THREAD

**Issue by Diablo-D3** [microsoft/terminal#11456]
### Windows Terminal version (or Windows build number)

All versions

### Steps to reproduce

Terminal calls "Magenta" by the wrong name, instead it is called "Purple".

### Expected Behavior

The expected behavior is calling it "Magenta" instead of "Purple".

### Actual Behavior

Terminal calls the color in question "Purple", instead of "Magenta".

**Comment by Diablo-D3** [comment]
I apologize for the simplicity of this report, but the form submission really doesn't cover trivial issues.

I also understand that it is possible nobody on the team wants to handle the GUI implications of handling non-English translations, but I would accept the settings.json parser to also accept "Magenta" as a string, since it will now always have to also accept "Purple" to not break legacy configurations.

**Comment by zadjii-msft** [comment]
Huh. No one else has complained about this since we shipped the Terminal more than 2 years ago now. I suppose we _could_ also accept magenta as a key. Probably no harm in that.

**Comment by elsaco** [comment]
@Diablo-D3 magenta is a lighter shade of purple, and I don't wanna go into arguments how magenta is ...scientifically defined. If you really want magenta in your themes just set "purple": "#ff00ff". No need to pollute the schema with more keys.

**Comment by samjones00** [comment]
Hi, first timer here. Can I assign myself and get started, I didn't see anything about assignment in contributing. Md?

**Comment by Diablo-D3** [comment]
@matthewd673 Thanks for the fix.
