### ISSUE TITLE
Bug Report: Cursor Shape setting is not persistent and reverts to legacy style

### ISSUE THREAD

**Issue by fgimian** [microsoft/terminal#1145]
# Environment

```none
Microsoft Windows [Version 10.0.18362.116]
```

# Steps to reproduce

1. Right click on a console window and select Properties / Terminal
2. Set the Cursor Shape to anything other than "Use Legacy Style"
3. Notice that the cursor shows up correctly but after hitting enter and typing a few characters, it returns to the default style
4. Repeat step 1 and notice that your setting has been reverted

# Expected behavior

The new cursor shape should continue to work in the terminal and stay ticked in Properties.

# Actual behavior

Step by step screenshots:

We start with a normal PowerShell window:

![image](https://user-images.githubusercontent.com/1811813/58919251-bb4d4100-8770-11e9-8f5f-0d1174a72bc5.png)

Change cursor to vertical:

![image](https://user-images.githubusercontent.com/1811813/58919259-c7d19980-8770-11e9-94cb-1b850f6b6f07.png)

Vertical cursor shows up, yay:

![image](https://user-images.githubusercontent.com/1811813/58919273-d0c26b00-8770-11e9-80c2-a5a4f802e24d.png)

Hit Enter and type some text, then notice the cursor changes back to the default:

![image](https://user-images.githubusercontent.com/1811813/58919306-efc0fd00-8770-11e9-9bcc-70e41f706e9d.png)

Popping back into Properties reveals our selection has been reverted too;

![image](https://user-images.githubusercontent.com/1811813/58919320-fbacbf00-8770-11e9-8f86-f350c901d15e.png)

**Comment by DHowett-MSFT** [comment]
Yeah, unfortunately PSReadline resets the cursor style constantly, mid-way through the line and everything.

**Comment by DHowett-MSFT** [comment]
We'll follow up with PSReadline and link the bug here. Thanks for the detailed report.

**Comment by fgimian** [comment]
Thank you so much @DHowett-MSFT, yeah it seems really broken at the moment.

Really appreciate your help!
Fotis

**Comment by DHowett-MSFT** [comment]
Hey @fgimian! Just wanted to let you know that I did finally follow up and move the issue to PowerShell/PSReadLine#964.

**Comment by fgimian** [comment]
Thank you so much @DHowett-MSFT 😄

**Comment by fgimian** [comment]
Thanks a lot @DHowett-MSFT 😄
