### ISSUE TITLE
Spellcheck Linting

### ISSUE THREAD

**Issue by ZeroCoolGOS** [microsoft/terminal#11455]
# Description of the new feature/enhancement

It would be nice to have spellcheck linting in terminal. I have had way to many times miss spelled something in terminal, an I have to do spellcheck in Word just to make sure I did not spell something incorrect. Mainly with GIT commits. 

# Proposed technical implementation details (optional)

Just how Word or Edge flags spelling with the underscore squiggle.  If it's possible to have right click correction that would be a bonus.

**Comment by WSLUser** [comment]
I just did also just have idea of wondering if there's perhaps a VT sequence that could also address this. A terminal application would need to opt in of course but then git, vim, etc. could enable spell-checking and do whatever it wants as far as UI goes. I could see this as being a particularly useful sequence.
