### ISSUE TITLE
Mixed language input breaks line wrap

### ISSUE THREAD

**Issue by Kein** [microsoft/terminal#11459]
### Windows Terminal version (or Windows build number)

1.10.210826003-release1.10

### Other Software

Windows 10 20H2 19402.685
OpenSSH for Windows (7.7.2.1), default that comes with Windows 10

### Steps to reproduce

1. Login into remote linux shell with `ssh`
2. Start typing very long input that does not fit into single screen line
3. At this point, if you switch to 2nd input language (Russian in my example), then delete typed non-english symbols and continue extending the input line - it will break word wrap

### Expected Behavior

Line wrapping/break behaving as expected - wrap to the next line when reached screen's or window's horizontal end.

### Actual Behavior

https://user-images.githubusercontent.com/623756/136473615-7645b153-97ff-4e77-b707-29e754744160.mp4

**Comment by Kein** [comment]
For the record, I reproduced same issue locally without SSH, when using `wget` and very long fetch URLs - it is exactly the same issue and behaves the same, however, this time without using any other input languages.

**Comment by zadjii-msft** [comment]
@Kein sorry to leave this untriaged for so long. Do you have a gif/video of that minimal repro without ssh, with `wget`? Which shell are you using? (bash/zsh/fish/sh)? Are you running this in WSL / MinGW / cygwin / Pwsh/?
