### ISSUE TITLE
Crashes when scrolling down from the top of a long scrollback buffer

### ISSUE THREAD

**Issue by tovine** [microsoft/terminal#11460]
### Windows Terminal version (or Windows build number)

Version: 1.10.2714.0

### Steps to reproduce

Hard to say definitely because it's only the second time it's happened, but it happened after doing similar things so I guess it's somehow related to too much scrollback data or something?

Anyway, I had multiple terminal tabs open - all running SSH sessions inside WSL (Debian), there were significant amounts of scrollback text in most of them, and when I used the scroll wheel of the mouse to get back down to the bottom the entire window just crashed and disappeared.

The mouse is a Logitech one with the free running wheel, so maybe it got a lot of scroll events too fast to handle or something?

### Actual Behavior

The whole window just disappeared, killing all my active sessions.

**Comment by tovine** [comment]
Sorry about the slightly vague issue description, I don't really know exactly what caused it - if you can point me to where I can find some detailed logs I can try to dig them up.

I'll attach my config file here in case that helps
[settings.json.txt](https://github.com/microsoft/terminal/files/7307456/settings.json.txt)
.

**Comment by tovine** [comment]
Sorry about the late reply, I was sure I had already posted one but must have forgotten to do it 😅 

> This is crazy - have you been able to repro it since? My theory is that the Terminal just so happened to get updated in exactly that window. Often when we push a new release to the Store, we get a few reports like this where the Terminal seemingly crashed for no sensible reason. It's not actually the Terminal crashing, it's the Terminal being force-quit by the Store. I'm not sure where exactly the Store logs are though, to see if the update took place at about the same time as this report. You would have been on v1.10.2383.0 prior, and now 1.10.2714.0 after the update.

Hi, I haven't reproduced it since because I've simply switched to a different terminal for such long jobs to avoid losing work again...
And the theory of updates is a reasonable assumption, that has also happened to me several times - however I've explicitly disabled automatic updates of store applications for this exact reason, so it shouldn't be the case here.

**Comment by zadjii-msft** [comment]
> I've explicitly disabled automatic updates of store applications for this exact reason

lol I'm not sure the Store actually obeys that. I'll look into that more, but boy would that be a useful workaround.

Alas, without a repro there's not much else we can do here, so I'll keep my ears open. If you ever come back to the Terminal and hit this again, we can re-open and investigate more.

**Comment by tovine** [comment]
Ok.
Are there any logs or other stuff I can collect if it happens again, so I'm more prepared with useful diagnostic info for you?
I guess it isn't really helpful with just a message that "it did it again today" without more details to go on...

Terminal is still version 1.10.2714.0 and when I opened store to look for updates now, there was a new available version of Terminal, so it seems it's actually doing something.

**Comment by zadjii-msft** [comment]
If it's something that's trivially reproducible, then the bot has some tips for filing a trace using the Feedback Hub, which should capture a dump: /feedback

Otherwise, if it's not easily reproducible, there's something else we could try. I think you should be able to follow the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps. If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, you could zip that dump up and send it to us. A dump of what caused the Terminal to crash is certainly a good place to start!

**Comment by tovine** [comment]
Thanks for the tip about automatic crash dumps, will use that if/when it happens again!
I guess that dump should then be submitted via Feedback Hub and not attached here?

**Comment by zadjii-msft** [comment]
Meh, emailing it to me would make sure it gets to me, but feedback hub is probably more secure (though admittedly, not always 100% reliable)
