### ISSUE TITLE
Feature Request: HTML Copy

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#1146]
# Summary of the new feature/enhancement
Copy RTF data from selection. Useful for pasting text over to MS Word (or something similar).
Copy HTML data from selection.

Resources:
- [Copy and Paste Docs](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/copy-and-paste)
- [DataPackage Docs](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.DataTransfer.DataPackage) (how to actually save the stuff. This is probably the more important doc)

# Proposed technical implementation details

So, looking at `Clipboard.cpp` under ConHost's InteractivityWin32 project, should cover most of what is done. We're just slightly different in that we're using the UWP Clipboard API but that should actually make a lot of it much easier.

The data should already be saved in `data` in `Terminal::RetrieveSelectedTextFromBuffer(bool)`. We just need to actually save it properly.

**Comment by 0xabu** [comment]
I just came here to note that HTML copy is useful for "modern" apps like the inbox Mail and OneNote apps that support pasting HTML but not RTF.

**Comment by RichardSlater** [comment]
HTML and RTF would be invaluable to quickly producing examples, my current workflow involves pasting it into a text editor and using syntax highlighting and extensions to copy it back out again.

**Comment by carlos-zamora** [comment]
Splitting off RTF copy to another issue. This issue now just focuses on HTML Copy and can now be closed.
