### ISSUE TITLE
Window scaling issue moving between monitors of different scaling

### ISSUE THREAD

**Issue by lukem** [microsoft/terminal#11462]
### Windows Terminal version (or Windows build number)

1.11.2731.0

### Other Software

tcsh (inside WSL2, Fedora 34)

### Steps to reproduce

System with two monitors of different scaling. In my case:
- Laptop with 15" screen, 1920x1080 resolution, 125% scaling
- 34" monitor, 3440x1440 resolution, 100% scaling. Set as main display.

Resize example 1:
- Start Terminal, set to 80x24, on 34" main display (100% scaling)
- Move window to 15" display (125%) scaling
- Observe that the terminal now reports 82x25
- Move window back to 34" display (100% scaling)
- Terminal now reports 80x24 (original layout on this display)

Resize example 2:
- At a larger window of 112x44 @ 100%, the window increases to 114x46 @ 125%
- If the window is resized to 112x44 @ 125%, then when moving back it shrinks to 110x42 @ 100%.

(This issue is similar to bug #10515, except that seems to be when the window is minimized and resumed, rather than moving between different scaling).

### Expected Behavior

The window should stay the same number of rows & columns when moving between monitors, even with different scaling.

### Actual Behavior

Output of running "echo" then "stty" at different times when the window is on the different monitors with different scaling:

**Starting on 3440x1440 34" at 100% scaling - window is 80x24**
```
lukem@andromeda 13> stty -a | head -1
speed 38400 baud; rows 24; columns 80; line = 0;
```

**Now on 1920x1080 15" laptop at 125% scaling - window increased to 82x25**
```
lukem@andromeda 15> stty -a | head -1
speed 38400 baud; rows 25; columns 82; line = 0;
```

**Back on 34" 100% - back to 80x24**
```
lukem@andromeda 17> stty -a | head -1
speed 38400 baud; rows 24; columns 80; line = 0;
```

**Comment by zadjii-msft** [comment]
Hey, looking through the backlog, I found a dupe for this

/dup #6210
