### ISSUE TITLE
Save and Resume

### ISSUE THREAD

**Issue by perneky** [microsoft/terminal#11476]
# Description of the new feature/enhancement

I'd like to be able to continue working after I closed and reopened the Terminal. Keep the tabs, histories, tab labels, etc. Just the way I left it. Many times during work, I use several tabs to issue commands from different folders. I label them on what they do, and I can quickly find where I need to go. After restarting the machine (at the end of the day) all this is gone.

I'd like to be able to save the tabs with history and everything, so I could continue working just how I left it.

It could even support "presets" with labeled tabs and folders, histories, so if I have multiple projects for instance, I could just open all the command lines I need to work on a specific project.

# Proposed technical implementation details (optional)

By default, if the terminal is closed, just do as like Microsoft Edge does, and when I open it next time, open as I left it.
Optionally I could save a layout using some command from the pallette, and later just restore it back.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #961, #766, #9800 for more discussion.

/dup #961
/dup #766
/dup #9800
