### ISSUE TITLE
Windows 11: Unable to unpin windows terminal from taskbar

### ISSUE THREAD

**Issue by nitinjs** [microsoft/terminal#11470]
### Windows Terminal version (or Windows build number)

22000.194

### Steps to reproduce

Open windows terminal
In the taskbar right click on windows terminal
Select `Pin to Taskbar`

Now close the windows terminal
You will see blank kind of icon in windows taskbar -> that is windows terminal

![image](https://user-images.githubusercontent.com/298479/136670703-b4cb30a2-5ad0-4352-ba89-e06e42ae8a74.png)

Right click that blank icon 
Select Unpin from taskbar

you will notice that Windows terminal is not going from taskbar

### Expected Behavior

Windows terminal shound be removed from taskbar when `Unpin from taskbar` is selected

### Actual Behavior

Icon does not get removed

**Comment by zadjii-msft** [comment]
@nitinjs Can you share the link here, so I can make sure it gets promoted to the right folks?

**Comment by mikrause** [comment]
Thank you for reporting.  Can you please submit this via Feedback Hub, under Desktop Environment\Taskbar for the category?  This'll help ensure the right logs are collected.

**Comment by ravensorrow** [comment]
I've been suffering from this problem for a few days now. I resolved this issue by going to the Recent Items list in my Start Menu, right-click that, clicking unpin, then closing all open copies of wt.exe and the problem disappeared. I am now leary though of re-pinning it to my taskbar, for fear of it happening again. I don't know how this is going to contribute to finding a permanent solution, but it was a fix for me.
