### ISSUE TITLE
Quake mode hotkey does not toggle window visibility

### ISSUE THREAD

**Issue by Rosefield** [microsoft/terminal#11478]
### Windows Terminal version (or Windows build number)

1.11.2421

### Other Software

W10 19042.1237

### Steps to reproduce

- press the quake mode hotkey "win+`" to summon the quake window, 
- while the quake window is open press again and observe that a new tab is created instead of toggling visibility.

### Expected Behavior

The quake window should be summoned, but a new tab should not be created. Additionally if the window is already open it should be hidden on the next press.

### Actual Behavior

Each time `win+sc(41)` is pressed a new tab is added to the quake window instead of toggling visibility.

My settings are here: https://gist.github.com/Rosefield/b89372ee1fbd48c10dd1b3586525e18b although I haven't made any modification to the quake default hotkey.

**Comment by Rosefield** [comment]
Looks like my terminal updated to 1.11.2731 and I am no longer seeing this, although I don't see a fix mentioned in the release notes :shrug:. It is still broken on my other computer that hasn't updated yet.

**Comment by Rosefield** [comment]
I notice that on the computer where this is still broken the quake window has id `1`, and even after closing all of the tabs on the quake window and then pressing the hotkey again the new window still has id `1`.

**Comment by FaustinCarter** [comment]
I'm having the same exact issue on 1.10.2714.0

**Comment by zadjii-msft** [comment]
Sorry I didn't see this one sooner!

> I notice that on the computer where this is still broken the quake window has id `1`, and even after closing all of the tabs on the quake window and then pressing the hotkey again the new window still has id `1`. Perhaps the monarch got into some corrupted state?

That's the best guess I'd have.

@Rosefield any chance you're still seeing this? (I know the chances are probably slim). If it's still happening then maybe we can try debugging what's going on. Otherwise I think we just have to leave our ears open to hear if this happens again, and what we can do to try and repro it.

**Comment by Rosefield** [comment]
"Unfortunately" I am not. It was curious that it happened on both of my computers at the same time before. Quake mode isn't a feature I normally use, but if I see it again I'll try to capture more diagnostics.

**Comment by mave-panda** [comment]
This behaviour seems to be back in Windows Terminal Preview
Version: 1.16.3463.0

**Comment by cypherfunc** [comment]
Seems to be back again? I'm running Windows Terminal v1.17.11461.0

(Also, clicking outside the quake terminal doesn't collapse it either, but I'm not sure whether that's intended behavior.)

**Comment by cypherfunc** [comment]
Not sure how or why, but this seems to be fixed. I have gotten a Windows update, but I'm still on Terminal v1.17.11461.0 🤷‍♂️

**Comment by EmperorShade** [comment]
I had the same issue (v1.19.2628.0). It got fixed when I repaired the app using the default Windows tool:

**Settings>Apps>Apps and Features> Windows Terminal Preview > Repair**

No clue why the issue was occuring though, but this fixed it for me.
