### ISSUE TITLE
Thin white line or thin blue line at the bottom of the screen on Windows 11 when clicking on the Maximize button

### ISSUE THREAD

**Issue by csdvrx** [microsoft/terminal#11474]
### Windows Terminal version (or Windows build number)

1.10.2714.0 to 1.11.2731.0 (both Windows Terminal and Windows Terminal Preview)

### Other Software

default Windows 11 installation with WSL2

### Steps to reproduce

Start 2 terminals, put one slightly over the other: there is no white line as can be seen here on the corner

![image](https://user-images.githubusercontent.com/49044530/136706739-ee8531e5-c62d-450f-b65a-b3667e1168cc.png)

Click on the maximize button, the taskbar is present at the bottom, which is something someone using a maximized terminal may not want, given the strong contrast and eye strain it creates (a terminal with black background and white text with a white taskbar at the bottom and a white titlebar on top)

The next logical step for this user is to attempt a basic configuration, simply using the available menu options that are shown or known to this user: in Windows Terminal, select the dark theme, and in settings, configure the taskbar to auto hide.

![image](https://user-images.githubusercontent.com/49044530/136707152-a0801d56-0480-4323-b5b9-2395c818e572.png)

![image](https://user-images.githubusercontent.com/49044530/136707162-491f7fbc-eeb2-4387-a519-2cfbdf09b17e.png)

However, this results in a thin line at the bottom:

![image](https://user-images.githubusercontent.com/49044530/136707238-d086c32c-627b-4e0d-b881-797b7270c118.png)

### Expected Behavior

Pressing on maximize should maximize the window, and never leave any thin line at the bottom, regardless of the thin line color: this can be a issue with OLED displays, where the screen may get a "burn in" of any persistent element, like this thin line.

If a thin line must be left for impervious reasons (ex: as a visual reminder), the thin line color should be configurable by the user, to match the theme or to be less distracting. 

Alternatively, if a strong visual reminder of the taskbar must always be left in fullscreen mode, there should be another mode grossly equivalent to "full screen" mode, maybe called differently to avoid confusion with the default fullscreen mode, but offering the option to have no thin lines at the bottom (something irrelevant with the current workflow), while still offering the list of tabs opened (something highly relevant with the current workflow).

### Actual Behavior

After these 2 settings, there is now a thin white line at the bottom. Unless reverting the taskbar autohide, any further setting will only make the situation worse.

For example, the user may at this point attempt configuring shortcuts (a more advanced approach, but desperate times call for desperate moves...), where the only 2 choices available (focus mode and fullscreen mode) will not work:
 - focus mode will remove the tabs and the title bar (which the user may want to keep, as it's not the theme consistent titlebar that's breaking the focus, but the thin line!)
 - fullscreen mode will also leave a thin line, except this time it will be a thin blue line:

![image](https://user-images.githubusercontent.com/49044530/136707344-95da7c0d-8794-4eba-8027-d3145a6cf7ee.png)

It may not be easily visible outside fullscreen mode, but you can download the image and show it in Paint/fullscreen if you want check the bottom for the precise color:
![image](https://user-images.githubusercontent.com/49044530/136708359-fa74f12b-e997-4348-88fb-27b6b35e4b6e.png)

![image](https://user-images.githubusercontent.com/49044530/136708503-2d26343f-9738-4284-adbb-295abbe678d5.png)

This behavior of fullscreen mode is possibly due to how DWM works with full screen applications when the taskbar is set to autohide, as there is no such thin line when the titlebar is not set to autohide and using the same shortcut and Terminal configuation.

However, this DWM behavior means there is no way to:
 - keep the default Windows theme system wide ("light", with a whitish background)
 - while also using Terminal default theme ("dark", with a black background)
 - without either introducing visual inconsistencies (whitish elements on the top and bottom of the screen) or sacrificing the titlebar and tabs (the list of tabs being extremely useful when several remote sessions are opened, far more than a visual reminder the taskbar still exist, as it can be easily brought back when pressing the windows key)

Even worse: users who followed a "reasonable escalation" approach will be left with the worst of both worlds, with no tabs in fullscreen mode, yet the thin blue line due to setting the titlebar to autohide - a thin blue line that wouldn't be present otherwise!

Maybe there should be a "third mode" that would:
 - maximize the Terminal
 - while preserving the display of Terminal tabs (important for the work flow!)
 - while preventing other clutter/visual inconsistencies not important for the work flow (ex: thin lines at the bottom), or at least offering the user to fully control them

A reasonable setting would be to at least let the user control the color of the thin blue line acting as a visual reminder there is a taskbar: a better color could be configured, matching the background if necessary, whether dark (for OLED) or light (for eInk).

While colors identical to the background color may be considered "less readable" and therefore less favorable settings, user preferences should be allowed to override such concerns, for example in these specific situation due to the display technology used.

Regardless of the root causes (DWM?), some users may also object to displaying a mandatory "thin blue line" on their display, for political reasons: a bing search on "thin blue line" reveals the connotation with law enforcement in North America, and a newer but potentially more problematic political connotations as noted in wikipedia ('The "thin blue line" has also been associated with white nationalists in the US, particularly after the Unite the Right rally in 2017.[7][8]')

This issue may be related to #4837, #3064 or #3425 which was closed because "this is the issue for terminal has white borders in dark mode, which is 100% fixed. If you want to discuss changing the default for light mode, please file a separate issue"

It may have been short-sighted to ignore the separate issue for light mode, as light mode is now the default Windows-11 theme.

**Comment by csdvrx** [comment]
NB: I realize the thin white line may not be visible without a zoom, so there it is after zooming on the bottom of the picture and filling the background in a darkish red

![image](https://user-images.githubusercontent.com/49044530/136709391-ec0449b4-d775-4c48-8230-298f0d1e04d4.png)

It is slightly offwhite/grey, so here is the precise color from the pipette tool in paint:

![image](https://user-images.githubusercontent.com/49044530/136709418-9fb8758a-714c-4bdc-8d07-0d80178ff2a8.png)

Also, when start 2 terminals, and putting one slightly over the other: there is no white line but there is a different dark dark grey line, which could be an issue for some users?

It may benefit from being a behavior that can be tweaked by an configuration option with a similar name, due to the similar appearance of these 2 issues (thin lines, except this one is a dark grey line, and not just on the bottom but on the sides too...)

**Comment by csdvrx** [comment]
This was on a fresh Windows 11 with the default settings. To mitigate the issue, indeed I tried different accent colors, one of which may have been blue. This could explain this precise color code? I will check this test installation again to confirm that.

It may not be a pure Terminal issue, but it impacts the Terminal use: this test install was to check how possible it would be to replace existing terminals by dedicated laptops running Windows Terminal in full screen.

For such use cases, ideally the "full screen" mode of the Terminal should have an option to override all mousing targets, similar to how web browsers in kiosk mode fully occupy the screen.

If such an option isn't possible or if the indicator for the taskbar presence can't be hidden, could the color be at least made configurable? 

This would achieve the same result visually if only a keyboard is connected (or by disabling the mouse)

**Comment by codefist** [comment]
It's years later now and I'm running into this exact problem.
I've discovered that if I have my taskbar set to auto hide, then my fullscreen windows terminal has the gray line at the bottom, lame.
