### ISSUE TITLE
Missing font that I didn't choose nor have a way to change in the settings

### ISSUE THREAD

**Issue by rodiaza** [microsoft/terminal#11499]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Steps to reproduce

Open Windows Terminal (it opens powershell), and be greeted by this Warning:

```
Unable to find the selected font "Cascadia Mono".
"Consolas" has been selected instead.
Please either install the missing font or choose another one.
```

I never selected any custom font, and there is no place in the settings window to change the font

### Expected Behavior

no warning for a setting I didn't touch

### Actual Behavior

warning appears everytime

**Comment by zadjii-msft** [comment]
Please [search](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aclosed+font) and [read the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#unable-to-find-the-selected-font-cascadia-mono) before filing new issues.

/dup #9375 #11484 #11451 #11433 #11431
