### ISSUE TITLE
The output of powershell cannot adapt to the change of window size

### ISSUE THREAD

**Issue by fuzhengqu** [microsoft/terminal#11494]
### Windows Terminal version (or Windows build number)

22000.194

### Steps to reproduce

Use the Windows terminal to remotely log in to the Centos7 system. In the case of half a window, that is, when the window is not maximized, execute the ps aux command. At this time, the display is normal and organized. Click the maximize button at this time, after the maximized, the content is displayed disorderly and unorganized
![2](https://user-images.githubusercontent.com/5155534/137103959-0d8ff958-5e83-4ec5-bf49-c9a6589454f4.png)
![3](https://user-images.githubusercontent.com/5155534/137103967-75f9ab8c-5e65-4e3e-842e-157be8527793.png)
![3](https://user-images.githubusercontent.com/5155534/137103988-99ea28d7-af6f-4d8c-adbf-952760e25055.png)
![2](https://user-images.githubusercontent.com/5155534/137103990-8bd18351-d07d-4446-b2aa-7865db06ee88.png)

### Actual Behavior

Use the Windows terminal to remotely log in to the Centos7 system. In the case of half a window, that is, when the window is not maximized, execute the ps aux command. At this time, the display is normal and organized. Click the maximize button at this time, after the maximized, the content is displayed disorderly and unorganized

**Comment by zadjii-msft** [comment]
Okeydokey yea this sounds like /dup #3088
