### ISSUE TITLE
Windows terminal as default is missing

### ISSUE THREAD

**Issue by AleTheTwin** [microsoft/terminal#11496]
When I try to set Windows Terminal as my default terminal for my system there is no way to do that 
![image](https://user-images.githubusercontent.com/71783206/137150989-1b78be21-c85e-46da-9afa-e5a5f478b072.png)

**Comment by DHowett** [comment]
What version of Terminal are you using?

**Comment by sherif-elmetainy** [comment]
I have the same issue.
Windows 11 Pro Version 10.0.22000.258
Windows Terminal Version 1.10.2714.0
