### ISSUE TITLE
Windows Terminal crashes when I log in via Remote Desktop

### ISSUE THREAD

**Issue by paulelong** [microsoft/terminal#11508]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Other Software

na

### Steps to reproduce

From the event log it happens when I use remote desktop to connect to my desktop each morning.  It's not %100 reproducible, but it happens at least 3 times a week.  The steps seem to be:

Windows Terminal is running already
Remote desktop in remotely from Surface 7
Disconnect
Remote desktop in from HP laptop
I find the Windows Terminal has disappeared
Restart Window Terminal

Here's the event logged:
Faulting application name: WindowsTerminal.exe, version: 1.10.2109.28004, time stamp: 0x615383aa
Faulting module name: Microsoft.UI.Xaml.dll, version: 2.5.2012.2003, time stamp: 0x5fc87886
Exception code: 0xc000041d
Fault offset: 0x00000000000df4af
Faulting process id: 0x7d2c
Faulting application start time: 0x01d7c0358e14e2dc
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.10.2714.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.10.2714.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 3036bb9b-a770-4aae-a0d2-fabd234a139e
Faulting package full name: Microsoft.WindowsTerminal_1.10.2714.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### Expected Behavior

Windows Terminal should not fault

### Actual Behavior

3 times out of 7 Windows Terminal has exited unexpectedly.

**Comment by zadjii-msft** [comment]
Hmm. This is a tricky one - this is a scenario that'd be hard to capture in Feedback hub. 

Can you try following the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps? If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, can you zip that dump up and send it to us, so we can investigate? Thanks!
