### ISSUE TITLE
Microsoft Store lists Windows Terminal Preview 1.11.2421.0 but installs 1.11.2731.0

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#11504]
The [Microsoft Store listing for Windows Terminal Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3) shows:

> ### What's new in this version
>
> Version 1.11.2421.0
>
> Please see our GitHub releases page for additional details.

However, when I install the software from there, I actually get version 1.11.2731.0. The version number in the "What's new" section is out of date.

**Comment by zadjii-msft** [comment]
Huh, thanks. Must've forgot that in the latest hotfix release. We're getting 1.12 ready now so we'll make sure to bump that too.

**Comment by KalleOlaviNiemitalo** [comment]
Isn't it automated?
