### ISSUE TITLE
Unable to find the selected font "Cascadia Code"

### ISSUE THREAD

**Issue by LeeThompson** [microsoft/terminal#11500]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Other Software

None

### Steps to reproduce

Run Windows Terminal with _Cascadia Code_ selected for appearance.

### Expected Behavior

Windows Terminal to load _Cascadia Code_.  

### Actual Behavior

Error message appears and it defaults to _Consolas_.

NOTE: If you set Terminal to use _Cascadia Code PL_ it works as expected.

**Comment by Pike** [comment]
> NOTE: If you set Terminal to use _Cascadia Code PL_ it works as expected.

That font is also not available for me in the settings GUI, and setting it in the json settings also didn't work either.

**Comment by LeeThompson** [comment]
For the record, I did search but didn't find any duplicates, so apparently not well enough.   Sorry about that but hopefully this will still get fixed.
