### ISSUE TITLE
Could the repo have a CODE_OWNERS.TXT?

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1151]
Could the repo have a [CODE_OWNERS.TXT](https://github.com/dotnet/coreclr/blob/master/CODE_OWNERS.TXT) as the CoreClr has?  This might be helpful.   I'm not 100% sold on people looking at this, but it is one way for people to know who they should ask.

_Originally posted by @dlong11 in https://github.com/microsoft/terminal/issues/890#issuecomment-498915936_

**Comment by DHowett-MSFT** [comment]
In theory, I like this, but I think of the _four whole people_ who are on the console team, they all collectively own everything. I dunno.

**Comment by dlong11** [comment]
I thought that might be the answer. 😄  Like I said I am not sure how effective this is.  Maybe when we have a public channel of communication this won't be needed.

**Comment by mdtauk** [comment]
Surely a *.md file, rather than *.txt.

But why not include this info in the README.md file, the list of code owners, and what their role is.  So contributors have an idea who to aim comments to.

**Comment by zadjii-msft** [comment]
We discussed this in triage today - since we triage all new issues once a week, we can usually put the right person on an issue in a pretty reasonable timeframe. Especially considering there's only 4 of us, we're never more than one hop away from the right person to answer a question.
