### ISSUE TITLE
(Right Click Start Button) -> Windows Terminal should open the default terminal instead of hardcoding wt stable

### ISSUE THREAD

**Issue by nc-x** [microsoft/terminal#11513]
I recently installed Windows 11 and straightaway installed Windows Terminal "Preview" and uninstalled the stable version. And now right clicking start button and clicking on Windows Terminal does nothing.
I very rarely open the terminal from there so it is not a big issue but either the stable windows terminal should be uninstallable, or ideally the entry on the start button should not be hardcoded to Windows Terminal but should point to defterm.
I don't think this is something for the terminal team to fix, but hopefully you guys can refer it to the right team. (i don't use microsoft account on windows so using feedback hub is not possible)

**Comment by zadjii-msft** [comment]
That's unfortunately true today. We're tracking this in /dup #10595
