### ISSUE TITLE
It isn't letting me to make MS Terminal the default terminal

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#11527]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.22000.258]

### Steps to reproduce

It isn't letting me to make MS Terminal the default terminal
![image](https://user-images.githubusercontent.com/84385465/137742673-11179c70-3a51-4a55-a437-82f0d9066b1f.png)

### Expected Behavior

I thought I can make it the default terminal

### Actual Behavior

It has not the option to make MS terminal the default terminal

**Comment by jtnord** [comment]
same here  `1.10.2714.0`  windows 11.

Note I installed terminal preview `1.11` and I could set that as the default (showed as the preview version) uninstalled that, and just the old console host remains.  UNinstalled Terminal and re-installed (lost all my profiles 😱 ) and it is still not present.

**Comment by jtnord** [comment]
> how to see the version

select the down arrow in the tile bar and choose "about"

**Comment by zadjii-msft** [comment]
Actually, I can tell just by looking at the screenshot. You're running the stable version, not the preview. 

/dup #11415
