### ISSUE TITLE
paste long text cause terminal stuck when use a ssh profile

### ISSUE THREAD

**Issue by QCU266** [microsoft/terminal#11523]
### Windows Terminal version (or Windows build number)

1.10.2714.0, 1.11.2731.0

### Other Software

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

### Steps to reproduce

profile config to ssh remote linux

command line:
```
ssh ubuntu@x.x.x.x
```

### Expected Behavior

paste long text normally.

### Actual Behavior

terminal stuck, no response.

-----
but set profile command use ssh inside wsl, everything is ok.

```
wsl -- ssh ubuntu@x.x.x.x
```

------
open cmd or powershell first, then excute ssh to remote is also stucking when paste long text.

------
set profile command use powershell is still the problem
```
powershell ssh ubuntu@x.x.x.x
```

**Comment by zadjii-msft** [comment]
This sounds like the issue is only reproducing with the _Windows_ `ssh.exe`, correct? When you do `wsl -- ssh ubuntu@x.x.x.x`, that's using the linux build of `ssh`. Since this seems to work fine with the linux ssh but not ssh.exe, this should probably be reported over at https://github.com/PowerShell/Win32-OpenSSH/issues

**Comment by QCU266** [comment]
I retested it。

> **open cmd in Terminal first, then excute ssh to remote is ok when paste long text.**

so , i use profile with command：
```
cmd /c "ssh ubuntu@x.x.x.x"
```
It's OK.

----
@zadjii-msft maybe you are right that ssh.exe is the cause of the problem.
so, I download the latest Win32-OpenSSH, and use the latest ssh.exe to set profile. However, when paste long text , it's  exit with error 
```
client_loop: ssh_packet_write_poll: Connection to 10.1.0.5 port 22: eother

[process exited with code 255]      
```
