### ISSUE TITLE
custom shortcut keys for switch tabs

### ISSUE THREAD

**Issue by jiachao2130** [microsoft/terminal#11532]
I'd like to set the switch tabs shortcut keys as Linux or Mac style, just press Alt + Num,  but now I dont know how to set it, in the profile file I do not found the scope to do this, not support yet?

**Comment by KalleOlaviNiemitalo** [comment]
Adapt from these:
<https://github.com/microsoft/terminal/blob/0d5af3fedcb8d23986ae75a014bc65e46fefd2a2/src/cascadia/TerminalSettingsModel/defaults.json#L329-L337>

I think you can also do this in the settings UI nowadays.

**Comment by CC2130** [comment]
settings can't do this, 
![image](https://user-images.githubusercontent.com/13617710/137848909-8563e3ff-c885-40ba-9177-5b4e25e4fc0f.png)
click "open the json" , it's not defaults.json

so where is the localtion of default.json , c:\??? ? I want to edit it manually
