### ISSUE TITLE
unfocusedAppearance.opacity doesn't work, even with vintage opacity

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#11538]
### Windows Terminal version (or Windows build number)

1.12

### Steps to reproduce

Set an unfocused appearance to have an opacity!

### Expected Behavior

The opacity applies.

### Actual Behavior

The opacity does not apply. Other settings seem to, so it appears to be working.

**Comment by zadjii-msft** [comment]
Right now this is by design - I stuck opacity in Appearance because obviously, that's where we'd like to have it in the future, but only ever use the `FocusedAppearance`'s `Opactity`. Didn't want folks thinking that acrylic worked when unfocused yet

**Comment by zadjii-msft** [comment]
You know what, this is easier to just track in one place in /dup #11092
