### ISSUE TITLE
Hyperscrolling changes terminal font size

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11533]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.11.2731.0

### Other Software

Windows 10.0.19043
PowerShell 7.1.5

### Steps to reproduce

1. open pwsh tab
2. cat large text file
3. scroll back using free spinning mouse wheel
4. enter ctrl+c to cancel action

### Expected Behavior

1. scroll action being cancelled

### Actual Behavior

Terminal window changes font size. Same behavior when back scrolling in a WSL tab. 

Sample video:

https://user-images.githubusercontent.com/3933920/137836932-9b714a9c-f9a4-47bf-8376-0d1a29ce5c97.mp4

**Comment by KalleOlaviNiemitalo** [comment]
If you press Ctrl+C while the wheel is still spinning, then that's Ctrl+wheel and changes the font size by design. I don't remember whether one can rebind it in the settings.
