### ISSUE TITLE
Code Health: duplicate end of statement semicolon 

### ISSUE THREAD

**Issue by dlong11** [microsoft/terminal#1154]
Very Minor cleanup.  duplicate end of statement semicolon 

* [x] `src\host\conareainfo.cpp(187)`:
  ```c++
  SMALL_RECT OldRegion = _caInfo.rcViewCaWindow;;
  ```
* [x] `src\host\consoleInformation.cpp(388)`:
  ```c++
  ci.Attributes = GenerateLegacyAttributes(attr);;
  ```
* [x] `src\interactivity\base\InteractivityFactory.cpp(349)`:
  ```c++
  NTSTATUS status = ApiDetector::DetectNtUserWindow(&level);;
  ```
* [x] `src\interactivity\win32\screenInfoUiaProvider.cpp(534)`:
  ```c++
  HRESULT hr = S_OK;;
  ```
* [x] `src\interactivity\win32\UiaTextRange.cpp(151)`:
  ```c++
  UiaTextRange* range = nullptr;;
  ```

src\host\conareainfo.cpp(187):        SMALL_RECT OldRegion = _caInfo.rcViewCaWindow;;
src\host\consoleInformation.cpp(388):    ci.Attributes = GenerateLegacyAttributes(attr);;
src\interactivity\base\InteractivityFactory.cpp(349):    NTSTATUS status = ApiDetector::DetectNtUserWindow(&level);;
src\interactivity\win32\screenInfoUiaProvider.cpp(534):    HRESULT hr = S_OK;;
src\interactivity\win32\UiaTextRange.cpp(151):    UiaTextRange* range = nullptr;;

Found in the clang-format PR #1141

**Comment by zadjii-msft** [comment]
Hey look, these have all been cleaned up already. Neat! Probably by clang-format.
