### ISSUE TITLE
Drag and drop the file to the Windows Terminal can not automatically fill in the file address of the file.

### ISSUE THREAD

**Issue by DevilSpiderX** [microsoft/terminal#11548]
# Description of the new feature/enhancement
Drag and drop the file to the Windows Terminal can not automatically fill in the file address of the file, but you can directly do that when you use cmd or powershell.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Are you trying to drag/drop onto the top left corner of the Terminal, or the bottom/right? What DPI is your display set to?

**Comment by DevilSpiderX** [comment]
When I drag and drop the file to the Windows Terminal, it will appear.
![1634737941132](https://user-images.githubusercontent.com/62919058/138106832-1f3fa474-e2c5-4739-b96a-dec1667b3ef6.jpg)
