### ISSUE TITLE
Background image path not appearing in SUI

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#11541]
### Windows Terminal version (or Windows build number)

1.12.2861.0

### Steps to reproduce

Set a background image for a profile.

### Expected Behavior

The path should be in the text field.

### Actual Behavior

The path doesn't appear in the text field but the background image is still applied.

![image](https://user-images.githubusercontent.com/48369326/138002334-cfbabc92-a4f2-4b0f-a98c-89b4d13191c5.png)

**Comment by elsaco** [comment]
@cinnamon-msft you could also add that when selecting desktop wallpaper as background image it is not being applied, even after save and WT restart:

![wt_bg_desktopWallpaper](https://user-images.githubusercontent.com/3933920/138021344-cfc16e4e-9fec-4dde-bd78-be52a6228e7c.png)
