### ISSUE TITLE
My PC doesn't like this app

### ISSUE THREAD

**Issue by KirkH420** [microsoft/terminal#11546]
### Windows Terminal version (or Windows build number)

Version 10.0.19042.928

### Summary
I've attempted to install this on a couple different occasions, having seen some screenshots that looked promising. Originally I wanted to look at the source just for fun, but it became clear pretty quick that building it wasn't gonna be an 'on my lunch break' type of task. At that point I realized it's on the Winstore. Here's where it gets confusing because if the app were going to work, surely this would be the place to install it from. Winstore will not move past the 'you own this app.' I can sit there clicking 'Install' all day, not a thing happens. That's the first occasion. I figured "eff-it" I was only impressed by some screenshots anyway. Wont miss what I don't know, right?

A few days later, I'm doing something totally unrelated yet here I am again, having been directed here by some Blog that was calling this ‘Colortool‘ but it links to Microsoft/console. It took me to your releases page, where I read a bit about the several different releases. Cool, there's a stable! So I downloaded the .msixbundle, it launched it's self as soon as it completed and the result was a new shortcut.ink added to my Start Applist. Success! I think....

but.... I can click this shortcut all day and not a thing happens. Seriously, usually you'd at least expect the start menu to close once an app has been clicked... just sits there. So, I refer you to the title of this post and wish you guys luck. I'll probably end up back here eventually.

### Steps to reproduce

Download stable release, format=msixbundle, install=succeded, AppLaunch=failed

Locate stable on Windows Store, Owned a copy, Install=button does nothing

### Expected Behavior

Launch app

### Actual Behavior

Not launch app

**Comment by zadjii-msft** [comment]
> I can sit there clicking 'Install' all day, not a thing happens.

Curious, did you try sending feedback via the Feedback Hub? If you record the problem with the Feedback Hub, it should capture some helpful diagnostics that the store team might be able to use.

>  some Blog that was calling this ‘Colortool‘ but it links to Microsoft/console

Ah yes, colortool was the first thing we had on this repo long before it was the Terminal repo. Colortool is totally different from the Terminal, it's a tool for running inside your commandline session. You can find it nowadays at https://github.com/microsoft/terminal/tree/main/src/tools/ColorTool. (When we released the Terminal, we renamed the repo from Microsoft/Console -> microsoft/terminal. Some older links probably still point at the old place).

>  I downloaded the .msixbundle, it launched it's self as soon as it completed and the result was a new shortcut.ink added to my Start Applist. Success! I think....
> 
> but.... I can click this shortcut all day and not a thing happens

Interesting. 
* Does anything show up in Event Viewer when you do this? 
* Do you have any antivirus software installed? 
* Are you running an activated copy of Windows? 
* Does a WindowsTerminal process show up in TaskManager, but running "suspended" by any chance?

I'm kinda grasping at straws here. Usually when the Terminal fails to launch, there's some feedback of some sort.
