### ISSUE TITLE
cppwinrt.build.pre.props vs common.build.pre.props differs with regards to warnings

### ISSUE THREAD

**Issue by dlong11** [microsoft/terminal#1155]
Currently the common.build.pre.props warning settings differ from cppwinrt.build.pre.props.  

common.build.pre.props 
TreatWarningsAsErrors = true
TreatSpecificWarningsAsErrors = 4189;4100;4242;4389;4244
DisableSpecificWarnings = 4201;4312;4467

cppwinrt.build.pre.props
TreatWarningsAsErrors = Not Set
TreatSpecificWarningsAsErrors = Not Set
DisableSpecificWarnings = 28204

Is there a consistent set of warnings that should always be errors?   
Is there a consistent set of warnings that should always be disabled?   

These may not be identical but I would expect all projects would have a common subset of warnings that cause build failures.

**Comment by DHowett-MSFT** [comment]
We may want to tackle this at the same time as #922 honestly. I can repurpose that as "make the build rules better/match more/etc."?

**Comment by dlong11** [comment]
Sounds great.   I will close this one.

**Comment by zadjii-msft** [comment]
.... eh, I'd say that this is a much more manageable change that someone could help us with. Sure it's a subset of the work that could be done in #922, but this is still goodness to have, even if it's duplicated in the two files temporarily. I'd say we leave this open and mark it Help-Wanted, and possibly make a note in #922 that it should also include fixing this.

**Comment by dlong11** [comment]
@DHowett-MSFT @zadjii-msft I will reopen for now.  When you triage you can close if you decide to do it in #922.   I jumped the gun and didn't let you guys triage it.  Sorry about that.

**Comment by DHowett-MSFT** [comment]
I'm deciding that #2660 (@miniksa) fixes this -- if all warnings are errors, "specific warnings" doesn't mean much, and we can tackle the rest with the build property unification.
