### ISSUE TITLE
Error codes should show unsigned

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#11556]
Missed this in #11123...

![image](https://user-images.githubusercontent.com/18221333/138168320-58797ebc-d584-45c1-9946-431cfd0e1f05.png)

That should be an unsigned value. Not a signed one.

**Comment by zadjii-msft** [comment]
🤣

**Comment by zadjii-msft** [comment]
wait how the dickens do I get the negative return code?

![image](https://user-images.githubusercontent.com/18356694/139667989-4f06f7f8-1e99-45f6-911f-a9a77e7980a8.png)

**Comment by DHowett** [comment]
I think you need a negative return from _CreateProcess or CreatePseudoConsole_ (an early HRESULT-out, not a late one)

Set a commandline to `"`"cmd.exe"` or something?

**Comment by zadjii-msft** [comment]
yea that'll do
![image](https://user-images.githubusercontent.com/18356694/139710195-115f2032-db57-4d76-95e3-ee43ab0d6424.png)
