### ISSUE TITLE
Italian translation "Delimitatori di Word"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#11566]
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Steps to reproduce

1. Start Windows Terminal Preview.
2. Open the settings UI.
3. Select the "Appearance" tab.
4. Under "Language (requires relaunch)", choose "italiano (Italia)".
5. Click "Save".
6. Close Windows Terminal Preview.
7. Start Windows Terminal Preview again.
8. Open the settings UI.
9. Select the "Interazione" tab.
10. Look at the title of the word delimiters setting.

### Expected Behavior

"Delimitatori delle parole", I think. It's not my first language.

### Actual Behavior

"Delimitatori di Word", as if this setting referred to the Microsoft Office Word software.

**Comment by lhecker** [comment]
Tracked as MSFT:38108953.

**Comment by lhecker** [comment]
This issue has been resolved internally and will ship with the next release.
