### ISSUE TITLE
Run as different user

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#11568]
# Description of the new feature/enhancement

I miss the feature to run wt as different user from
- start menu.
- context menu in task bar.
- context menu of wt.exe in explorer.

For me this is a must have when using it in our company. Because of some reasons the uac is disabled.

# Proposed technical implementation details (optional)

./.

**Comment by zadjii-msft** [comment]
Okay, sorry for late reply. This is more specifically tracked in /dup #4217. There's also more discussion in:

* #1032
* #1053
* #2200
