### ISSUE TITLE
Starting WT momentarily shows a black titlebar

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#11561]
### Windows Terminal version (or Windows build number)

10.0.19043.1288 1.12.2922.0

### Steps to reproduce

Start WT.

### Expected Behavior

The GUI should start without showing a glitched black title bar, just as it did in v1.11.

### Actual Behavior

It shows a black title bar for a few milliseconds. See below:

![2](https://user-images.githubusercontent.com/46838874/138241520-f668f835-239c-45d9-a11d-409b016137c3.gif)

![1](https://user-images.githubusercontent.com/46838874/138241542-a7ec130a-2087-47e6-b34f-2f09a6642243.gif)

My [settings.json](https://github.com/rashil2000/dotfiles/blob/master/wt/settings.json) is the same as before I upgraded (through Store).

**Comment by zadjii-msft** [comment]
showerthought: we could have a solid BG for the `TerminalPage` until initialization is completed, and _then_ drop out the bg. That might obscure the titlebar until the rest of the content initializes.

**Comment by zadjii-msft** [comment]
Some gifs recorded this morning of the issue. No progress to report. 

![transparent-frame-on-launch-000](https://user-images.githubusercontent.com/18356694/142231718-05b95699-ea9b-4212-bb87-b2f690e368da.gif)
![transparent-frame-resizing-000](https://user-images.githubusercontent.com/18356694/142232692-2882b083-3142-405b-9323-e07e803dc893.gif)

**Comment by zadjii-msft** [comment]
Note to self: maybe we can DWM_CLOAK the window until it's initialized

**Comment by zadjii-msft** [comment]
note to self: tried just setting a BG for the TerminalPage then yanking that after we're initialized. There's still a few frames before the XAML content loads at all. I'd say the cloaking thing felt more polished comparatively.

**Comment by zadjii-msft** [comment]
Whoops, we reverted this and never reopened

**Comment by zadjii-msft** [comment]
From teams:

> This is the "empty terminal" animating in thing I mentioned
> 
> you likely want to hookup a solid color brush via DComp/WinComp that paints everything some opaque color to avoid this
> 
> your swapchain effectively "does not exist" until the first present is finished so this is why you get this behavior
