### ISSUE TITLE
Contextual menu Open with Windows Terminal should open in a new tab

### ISSUE THREAD

**Issue by scls19fr** [microsoft/terminal#11560]
# Description of the new feature/enhancement

Currently contextual menu "Open with Windows Terminal" open a new window (even if an existing Windows Terminal window is opened)

it should open in a new tab in the ever opened window

Fluent terminal behave like this and that's very convenient.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You can get this behavior if you enable `"windowingBehavior": "useAnyExisting"`

![image](https://user-images.githubusercontent.com/18356694/138277599-e6a857b8-03a3-44c2-b77f-9a53a65735f4.png)
