### ISSUE TITLE
Add support for attaching to existing console applications

### ISSUE THREAD

**Issue by mjcarman** [microsoft/terminal#11569]
# Description of the new feature/enhancement
I migrated to Windows Terminal from ConEmu and one feature I miss is its "Attach to" function that captures an existing console window and moves it into the terminal as a tab. It's useful for managing windows that weren't — or more importantly, can't be — opened in the terminal.

Example 1: The launcher for the LynxOS development environment opens a bash console in the appropriate working directory and runs some setup commands it. I'd like to be able to move that console into Windows Terminal. (Replicating this via a WT profile is only partially possible, and even that much required a fair bit of sleuthing around to figure out.)

Example 2: Eclipse-based GUI applications can be launched with the console visible. Being able to move that console into WT would allow me to declutter my workspace.

I don't know if setting Windows Terminal as the default console host would alleviate these use cases. It might, but that feature is only available on Windows 11. This feature should work on any OS.

# Proposed technical implementation details (optional)
The context menu for the title bar should have an "attach to" (or similarly named) option that opens a dialog of existing windows that may be captured and moved into Windows Terminal.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11387 for more discussion.

/dup #11387
