### ISSUE TITLE
When a pane reports [process exited with code ...] the GUI should let you close it without closing the entire tab

### ISSUE THREAD

**Issue by FabioTurati-NTT** [microsoft/terminal#11570]
# Description of the new feature/enhancement

When you use multiple panes in a single tab, and one of them exits with an error code, the pane is "stuck" displaying it. There are only 2 ways to dismiss the error message and close that pane:
1. Closing the entire tab, which forces the user to also close the other panes. Reopening them can be long and boring (several SSH connections/ADB shells, scripts that must be sourced...)
2. Using the keyboard shortcut `Ctrl + Shift + W`, which I can never remember

I have read in your FAQs [why that message is kept](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#user-content-why-am-i-seeing-process-exited-with-code-), and I understand it, but this behaviour ("closeOnExit": "graceful") works fine only if you are using an entire tab, because you can easily close it by clicking on its X, but the GUI doesn't provide a way for closing a single pane.

# Proposed technical implementation details (optional)

When the pane is "stuck" on the message displaying the error code, a graphical "X" should appear in its top-right corner. Clicking on it closes the pane.

**Comment by zadjii-msft** [comment]
idea: TermControl could listen for the connection state to change and then send a bunch of newlines and then add a button to the TermControl underneath the message.

all the related discussions here:
* #11570
* #4379
* #3726
* #12849
