### ISSUE TITLE
Own command list

### ISSUE THREAD

**Issue by ManPython** [microsoft/terminal#11573]
# Description of the new feature/enhancement
Want have Own command list, eg. for own env https://github.com/microsoft/terminal/issues/11572
- python manage.py runserver
- python manage.py runserver -host=1.2.3.4
- python manage.py runserver -host:1.2.3.4 port:12
- python manage.py runserver -host=1.2.3.4 port=12
- ..etc

# Proposed technical implementation details (optional)
- it be nice to see navigator for commands (explorer like scripts)
- run these commands by shortcuts per custom tab with special env (eg. each env can have own scripts and shortcuts, in manage can select for which tab/env this commands pallete/shortcuts can work)
- easy select last used commands, favorites
- commands can be runed by ctr+shift+p from list where commands can have own names/descriptions

- inspired cmder ;p

**Comment by zadjii-msft** [comment]
In the `actions` in your settings file: https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/userDefaults.json#L24.

For more info, check out [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions).
