### ISSUE TITLE
Why are my profile icons blurry

### ISSUE THREAD

**Issue by isaac2004** [microsoft/terminal#1158]
# Environment

```none
Windows build number: 10.0.18362.145
```

# Steps to reproduce

Add icon to profile

# Expected behavior

Icon is not blurry

# Actual behavior

Icon is blurry

![image](https://user-images.githubusercontent.com/8878502/59036400-3845ec80-883d-11e9-9e2c-a96721816331.png)

**Comment by zadjii-msft** [comment]
Could you share the images you're trying to use as icons? My guess is that they're just really big, and when UWP tries to scale them down to the icon size, they're getting resampled poorly.

**Comment by isaac2004** [comment]
![cloud-32](https://user-images.githubusercontent.com/8878502/59038453-0c2c6a80-8841-11e9-94e5-0193e4fd7878.png)
![cmd-32](https://user-images.githubusercontent.com/8878502/59038454-0cc50100-8841-11e9-9c99-4af87e471f7b.png)
![pwsh-32](https://user-images.githubusercontent.com/8878502/59038456-0cc50100-8841-11e9-8644-e8f98cc90b80.png)
![ubuntu-32](https://user-images.githubusercontent.com/8878502/59038457-0cc50100-8841-11e9-8aad-60bd734f31fd.png)

**Comment by isaac2004** [comment]
They aren't big, but they are bigger than what gets painted

**Comment by benc-uk** [comment]
Same when using remote URL
![image](https://user-images.githubusercontent.com/14982936/59052212-787d8d00-8886-11e9-9463-fdcc28f05db3.png)

Looks terrible

I'm using the 64x64 version of this icon https://www.iconfinder.com/icons/395254/ubuntu_icon

**Comment by zadjii-msft** [comment]
During triage today we measured the actual icon size as about 24px. There's a good chance this is just UWP sampling your icons poorly, and I'm not sure there's too much we can do about that. Does using a smaller icon (like 24x24) look as blurry?

**Comment by bitcrazed** [comment]
To follow-up, You'll likely want to size your icons at no more than 24px tall. If your icons are larger, they'll get scaled down to ~24px tall which will likely result in significant degradation.

To test this, I created 24px tall icons for my own Terminal profile which avoided the need to scale the icons down, and resulted in much crisper icons in the Terminal's new-tab menu:

![image](https://user-images.githubusercontent.com/961950/59069859-68a57f00-886d-11e9-97ee-1e8ef20ca0cd.png)

Please confirm that you see similar improvements by resizing your icons to 24px tall using a tool like [Paint.NET](https://www.getpaint.net/).

In the meantime, we'll be sure to update the profile configuration instructions we're working on to clearly state the recommended image sizes.

**Comment by isaac2004** [comment]
Thanks @bitcrazed but they are still kinda blurry, can you provide the ones you have?

**Comment by DHowett** [comment]
Hey @isaac2004 - what is your screen scaling set to? We've actually been instructed (by the XAML guidelines) to use 16x16 icons at 100% scale. If you're on a "150%" display, that'll be 24x24... and if you're on a "200%" display (surface, etc.) they'll be 32x32.

*Either way*, we should set the scaling method to make it look better when we have to render icons at the wrong size.

**Comment by isaac2004** [comment]
Totally forgot to circle back, lowering the resolution per @DHowett fixed my issue, closing
