### ISSUE TITLE
"Open in Windows Terminal" Explorer context menu doesn't show up on left treeview pane in Windows 11

### ISSUE THREAD

**Issue by johnburnett** [microsoft/terminal#11587]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Other Software

Windows 11 (10.0.22000.258)

### Steps to reproduce

Right-click on a folder in the left side treeview pane of Explorer

![image](https://user-images.githubusercontent.com/945935/138530797-f9c1badb-9ffc-46da-9743-e44e18d88862.png)

### Expected Behavior

Have the "Open Terminal" menu available like it is on the right side Explorer pane:

![image](https://user-images.githubusercontent.com/945935/138530902-9bf91c42-3945-4a66-84f0-d97162f46651.png)

### Actual Behavior

"Open Terminal" menu doesn't show up

**Comment by johnburnett** [comment]
Great, thanks!

**Comment by zadjii-msft** [comment]
(this was actually tracked with MSFT:36416534 which should be serviced with KB5007262 but heck if I know when that's actually coming out. Soon<sup>tm</sup>
