### ISSUE TITLE
Auto-generated Developer Command Prompt/PowerShell profiles don't really work

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#11582]
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Other Software

I have VS 2019 and 2022 (preview) installed.

### Steps to reproduce

Install Windows Terminal so it auto-generates profiles for Developer Command Prompt and Developer PowerShell for the installed versions of Visual Studio.
Open Windows Terminal and open a tab with the Developer Command Prompt profile.
Execute the command:  where MSBuild

### Expected Behavior

MSBuild should be in the path, but it's not so the command can't be found

### Actual Behavior

The auto-generated profile just starts cmd.exe or pwsh.exe in a specific folder, but it doesn't actually run the script to start the developer session like the installed shortcut does.
I also noticed that the Developer Command Prompt profile is set to use pwsh.exe instead of cmd.exe.  That seems wrong.  Is that because my default profile uses pwsh.exe?

**Comment by carlos-zamora** [comment]
Fixed by #12906

/dup #12842

**Comment by DHowett** [comment]
You know, it _isn't_ fixed by that PR... Sorry about that. However: we've removed the footgun from the UI. Whether the JSON model allows for that flexibility is more of an academic discussion :smile:
