### ISSUE TITLE
Clear terminal with keyboard shortcut rather than a command

### ISSUE THREAD

**Issue by sdegutis** [microsoft/terminal#11584]
# Description of the new feature/enhancement

In Apple Terminal, I'm used to pressing Cmd-K to clear the terminal. This is quicker and easier than typing `clear`, and doesn't clutter my command history either. I'm aware of binding a keyboard shortcut to do this, but that doesn't have the advantage of keeping my command history uncluttered.

# Proposed technical implementation details (optional)

**Comment by jcrben** [comment]
Does `ctrl+k` do anything that would make it conflict? I'm considering using that myself. At the very least, perhaps a recommendation could be provided that wouldn't conflict with other Windows features? See also: https://en.wikipedia.org/wiki/Control-K

+1 for a default keyboard shortcut - I'd like to be able to easily tell a teammate "punch <shortcut>". Granted, I could set that up in the team's automated installer with fragments, but it would be nice to have a global standard across the world😄
