### ISSUE TITLE
HKCU\Console\CodePage ... does it do anything?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#11591]
Microsoft Windows 10 Pro for Workstations
10.0.19043.1288 (2009, 21H1)

I thought that HKCU\Console\CodePage set the default output code page for consoles (and I'm pretty sure that, at least once upon a time, it did).  But it does not now.  Although I have

```
hkcu\console
  CodePage : REG_DWORD : 1252
```

all console apps which don't have another specification start with CP 437 (CP_OEMCP).

But if, for example, I have

```
hkcu\console\SystemRoot_system32_cmd.exe
    CodePage : REG_DWORD : 1252
```

then CMD will start with CP 1252.

Shouldn't HKCU\Console\CodePage be setting the default?

And (apparently unrelated to the above) how do I get all shells to use output code page 1252 when running in WindowsTerminal?  They all seem to get 437.

**Comment by zadjii-msft** [comment]
You know, I thought our plan of record was to actually kinda go in the opposite direction, and have conpty force itself into utf-8 mode by default - #1802. Of course, we never really achieved consensus on that one, and I don't think any of us thought it was a terribly high-priority issue.

**Comment by carlos-zamora** [comment]
Thanks for filing. We think the right solution to this is going to be allow the user to set the codepage in a compatibility page of the settings UI. This work spans several issues: #10870, #9174, #15678, and #1802. So we're going to mark this as a /dup of #1802, even though it's not necessarily the perfect solution to this question, but we'll use it to do the right thing.
