### ISSUE TITLE
ColorTool does not set the default background color

### ISSUE THREAD

**Issue by jmoyers** [microsoft/terminal#1160]
# Environment

Microsoft Windows [Version 10.0.18362.145]
Windows Terminal built off master today, with ColorTool built off master today

I've built them both using release, Windows Terminal is deployed (Windows Terminal (Dev Build) launched from Start Menu).

# Steps to reproduce

ColorTool.exe -c
ColorTool.exe {any iterm scheme}

![bug_report_1](https://user-images.githubusercontent.com/235505/59067428-7a375880-8866-11e9-8610-0d362b559409.PNG)
![bug_report_2](https://user-images.githubusercontent.com/235505/59067429-7acfef00-8866-11e9-9e30-15755f5547a2.PNG)

# Expected behavior

Color scheme should be set in local Windows Terminal instance.

# Actual behavior

Its not getting set.

Note that I tried this out in a regular PowerShell instance launched from Start Menu and it seems to do what it's supposed to (at least from what I can tell), in that it sets the color scheme. I noted that the background color doesn't appear to be correct, which when I searched for ColorTool bug reports, I found #1150 which seems to be consistent with the behavior that I was seeing.

**Comment by zadjii-msft** [comment]
Try `colortool -x`. Colortool needs that flag to be able to set the colors in a way a terminal (via conpty) can understand.

**Comment by jmoyers** [comment]
No change. When I read the documentation, I thought -x was for WSL.

![bug_report_4](https://user-images.githubusercontent.com/235505/59071423-68a87d80-8873-11e9-9206-ee5148d50fce.PNG)

By the way, when running colortool directly in a PowerShell window, then running WSL (Ubuntu in this case) using "wsl," colors seem nicely preserved.
![bug_report_5](https://user-images.githubusercontent.com/235505/59071480-aefddc80-8873-11e9-8fd7-7e93494401e7.PNG)

Sorry, I'm not a windows terminal guru so I might be missing something obvious here.

**Comment by zadjii-msft** [comment]
Ohhhhh, I see what's wrong here - colortool isn't setting the _default_ background color in the `-x` scenario. We only just added support for the needed VT sequence to do that (#891), so colortool should be updated too.

**Comment by 9527KGG** [comment]
+1, 
ColorTool.exe can change the background color of normal/default Windows console windows, but not Windows Terminal Preview.

**Comment by DHowett-MSFT** [comment]
> +1

Incidentally, you can detect this state by the issue still being open. :smile:

**Comment by rofrol** [comment]
@zadjii-msft This

`/mnt/c/Users/roman/installed/ColorTool$ ./ColorTool.exe -x schemes/solarized_light.itermcolors`

changes background color in bash.exe.

This does not changes background color

`/mnt/c/Users/roman/installed/ColorTool$ ./ColorTool.exe -x iTerm2-Color-Schemes/schemes/Terminal\ Basic.itermcolors

**Comment by powzer** [comment]
I think I'm running into this issue.  Attempting to use ColorTool to change the background of the 'One Half Dark' color scheme to black instead of grey, and nothing is happening.

**Comment by robertwt7** [comment]
Yeah this one does not work in Windows Terminal Preview...

**Comment by zadjii-msft** [comment]
> Yeah this one does not work in Windows Terminal Preview...

Incidentally, you can detect this state by the issue still being open. 😄

**Comment by KdB13** [comment]
I think Windows Terminal's **JSON color schemes** are overriding the **Windows Console** color schemes which are set by `ColorTool`.

**Comment by LuanVSO** [comment]
i would like to work on this

**Comment by zadjii-msft** [comment]
Sure, go for it! Feel free to reach out if you need any pointers. I believe colortool will need to be updated to:
* be able to read defaultForeground / defaultBackground colors from schemes (.itermcolors should already include them, but I think the colortool ini's won't necessarily)
* If one is found, set it with the OSC sequence for setting the default* color

**Comment by LuanVSO** [comment]
now, to set the fg, bg and cursor color for the current window you will have to use the vt mode (ie. pass `-x` in the command-line)

**Comment by itsmeboy0** [comment]
When will we expect this change to be released?

**Comment by itsmeboy0** [comment]
@LuanVSO I have built colortool from source and tried applying https://github.com/catppuccin/iterm in cmd via `colortool -b -x catppuccin.itermcolors` and the foreground color is not being applied in the defaults.
Defaults:
![image](https://user-images.githubusercontent.com/75471378/159100957-d4627b53-ee00-4396-a89f-0d918e749321.png)
Properties:
![image](https://user-images.githubusercontent.com/75471378/159100964-178d7e31-ab81-4a13-a160-3fc847681286.png)

**Comment by LuanVSO** [comment]
the default console target doesn't set the separate foreground if one of the indexed colors is exactly the same as the foreground value here's the code:
https://github.com/microsoft/terminal/blob/6bc2b4af09cf3032e2fccd405302ffac70fd348c/src/tools/ColorTool/ColorTool/ConsoleTargets/DefaultConsoleTarget.cs#L39
I'd recon this behavior is desirable since there is no visual diference between the two and indexed color fg/bg is supported by a wider range of aplications.
if you really want the separate foreground you can do just
```poweshell
colortool -x catppuccin.itermcolors
```
and then click on the property option here:
![image](https://user-images.githubusercontent.com/43626415/159102225-eef408eb-7cd6-484b-a249-7e9c93e523b1.png)
and just press ok on the window that pops up(although this will only apply to the current shell/app )
