### ISSUE TITLE
Powershell not accepting Ctrl+R for command history search

### ISSUE THREAD

**Issue by HuAaron** [microsoft/terminal#11626]
### Windows Terminal version (or Windows build number)

10.0.22000.258

### Steps to reproduce

Usually in VSCode integrated terminal or directly in the Powershell I press Ctrl+R to get the fuzzy search over previously typed commands. But this time it writes ^R.
The same issue with https://github.com/microsoft/Terminal/issues/350.
I even create a fresh install of Windows 11. At the beginning, it works, press Ctrl+R show the history. I double confirmed this.
But after some while, press Ctrl+R it only writes ^R. Things changed as I can remeber:
Git installed. 
Powershell 7.1 installed. 
kb5005537 Installed and os restarted. -- This is the clear timeline I am sure that it didn't work since.
I tried in vscode Ctrl+R still works( show the history).  

PSReadLine:

 Get-Module PSReadline

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.1.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS..

Get-PSReadLineOption output works:

EditMode                               : Windows
AddToHistoryHandler                    : System.Func`2[System.String,System.Object]
HistoryNoDuplicates                    : True
HistorySavePath                        : C:\Users\UserA\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\Console
                                         Host_history.txt
HistorySaveStyle                       : SaveIncrementally
HistorySearchCaseSensitive             : False
HistorySearchCursorMovesToEnd          : False
MaximumHistoryCount                    : 0
ContinuationPrompt                     : >>
ExtraPromptLineCount                   : 0
PromptText                             :
BellStyle                              : Audible
DingDuration                           : 50
DingTone                               : 1221
CommandsToValidateScriptBlockArguments : {ForEach-Object, %, Invoke-Command, icm...}
CommandValidationHandler               :
CompletionQueryItems                   : 100
MaximumKillRingCount                   : 10
ShowToolTips                           : True
ViModeIndicator                        : None
WordDelimiters                         : ;:,.[]{}()/\|^&*-=+'"–—―
AnsiEscapeTimeout                      : 100
PredictionSource                       : None
CommandColor                           :
CommentColor                           :
ContinuationPromptColor                :
DefaultTokenColor                      :
EmphasisColor                          :
ErrorColor                             :
KeywordColor                           :
MemberColor                            :
NumberColor                            :
OperatorColor                          :
ParameterColor                         :
InlinePredictionColor                  :
SelectionColor                         :
StringColor                            :
TypeColor                              :
VariableColor                          :

### Expected Behavior

press Ctrl+R to get the fuzzy search over previously typed commands. 

### Actual Behavior

press Ctrl+R writes ^R.

**Comment by HuAaron** [comment]
I found that the env $Env:__PSLockdownPolicy (value 4) was added by group policy. Remove that get it works. 
Thanks.

**Comment by DHowett** [comment]
Thanks for following up!
