### ISSUE TITLE
The tab titles of Windows Terminal need truncating

### ISSUE THREAD

**Issue by SmartPolarBear** [microsoft/terminal#1162]
# Summary of the new feature/enhancement

The tabs being convenient, their appearance isn't as pretty. The title of tabs are sometimes too long, making it really hard to switch between them. The title of a Windows Powershell tab is especially too long as it displays the full path.

I suggest the title be truncated. For example, the tab title of a Powershell tab should only be "Powershell", rather than its full path to the excutable.
# Proposed technical implementation details (optional)

The tab title will be good to only display the exact name of the terminal. A tool-tip of the tab on mouse hover can display the full excutable path, or a context menu for copying the path can also be better than displaying a full long path in the tab title

**Comment by Summon528** [comment]
Probably duplicate of #608

**Comment by DHowett-MSFT** [comment]
Yep, that’s a dupe. Thanks!
