### ISSUE TITLE
"Open with Windows Terminal" context menu option not available

### ISSUE THREAD

**Issue by drk-mtr** [microsoft/terminal#11638]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Steps to reproduce

Install Windows Terminal via the Microsoft Store
Right click in a folder in Explorer

### Expected Behavior

Open with Windows Terminal context menu option appears

### Actual Behavior

No context menu option appears

**Comment by ashfaqnisar** [comment]
I am having the same issue, with this 22000.376 build. Was this fixed for you @drk-mtr  ?

**Comment by drk-mtr** [comment]
@ashfaqnisar I still have no context menu unfortunately, however I haven't tried uninstalling / reinstalling since raising this. I suspect no progress has been made just yet, as the issue hasn't been updated, so it's probably a "watch this space".

**Comment by KeenRivals** [comment]
Same issue here. It worked for a long time but disappeared a few days ago. I really miss it! Windows Terminal 1.11.3471.0. Windows 11 (Build 22000.376)

**Comment by ashfaqnisar** [comment]
@KeenRivals, I think this build(22000.376) removed that option from the context menu ?

**Comment by KeenRivals** [comment]
I've actually had this issue on Windows 10 some time ago. It looks like people are complaining about the same thing since June 22 in #10496

**Comment by codgician** [comment]
Having the same issue as @KeenRivals also on `22000.376`. The strange thing is, it only happens on a new device I've recently purchased (which upgrades from `22000.9` directly to `22000.376`). Another device, also on `22000.376`, does not have this issue.

**Comment by alexradocole** [comment]
Same issue as @codgician here, 22000.376 build on a new machine has no context menu in blank area or on selected files, only available when a folder is selected. Old machine that was upgraded to 22000.376 seems to work fine.

**Comment by brybalicious** [comment]
This repo is great for this. Highly recommend. I think they should pull this into the official build

https://github.com/kerol2r20/Windows-terminal-context-menu

**Comment by adrianghc** [comment]
I have the same problem on 22000.527. I should note that I have two user accounts, one is an admin and the other isn't. There are no issues on the admin account, but I don't get the context menu on the non-admin account unless I right-click a folder specifically.

**Comment by ShyDuan** [comment]
> Same issue as @codgician here, 22000.376 build on a new machine has no context menu in blank area or on selected files, only available when a folder is selected. Old machine that was upgraded to 22000.376 seems to work fine.

I have the same problem with you.

**Comment by zadjii-msft** [comment]
Hey sorry all, this fell out of the triage queue somehow. From the reports here this does sound like a /duplicate of #11839, thanks!
