### ISSUE TITLE
child bash processes are left running after Windows Store updates Terminal and closes it

### ISSUE THREAD

**Issue by chrisan** [microsoft/terminal#11651]
### Windows Terminal version (or Windows build number)

10.0.19043.1288

### Other Software

Ubuntu 20.04.2 LTS
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Steps to reproduce

1. Launch the most recent Windows Store version of Microsoft Terminal
2. Use Ubuntu 20 LTS
3. Start a bash process such as a local development server (in php or node)
4. Begin your normal work
5. Each end of day after work leave your terminal running but allow computer to go to sleep
6. Each morning wake up your computer resume work with Terminal behaving as expect
4. Wait for the next Windows Store update to Terminal
5. Observe your Terminal has been closed randomly one morning after waking the computer but your local dev servers are still accessible in the browser and the only way to shut down these servers is to open Task manager and kill instances of bash

### Expected Behavior

I expect when Terminal is shutdown by Windows Store automatic updates that all child processes are also shutdown

### Actual Behavior

Child processes are not shutdown when Terminal is shutdown for a Windows Store update

This is not a new issue to the latest Windows Terminal, it's been happening for probably as long as I've been using Terminal > 1yr

**Comment by j4james** [comment]
See issues #3915 and #6726.

**Comment by chrisan** [comment]
Hi @j4james these seem to be about preventing auto updates entirely?  I don't mind the auto update (even if it does mean I have to restart any processes) this was more specifically about all those processes are just detached and left running when the Store performs the update

For example when I close Terminal, all child processes are killed.  When Store closes Terminal for an update, no child processes are killed - just detached

**Comment by zadjii-msft** [comment]
This sounds like the discussion in #9914 which actually didn't end up getting triaged before (my bad). @chrisan can you follow up in that thread? Specifically, I'm interested if this consistently happens with the children of one particular type of shell? For example, does this always happen with WSL processes, or does it happen with children running in `powershell.exe` too?

Thanks!

/dup #9914
