### ISSUE TITLE
Inner terminal text not fully visible when dragging terminal from lower resolution monitor

### ISSUE THREAD

**Issue by itsamemarkus** [microsoft/terminal#11659]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Steps to reproduce

Use 4k and lower resolution monitor. **Start new terminal session on lower resolution monitor.** Drag window from lower resolution monitor to 4k monitor.

### Expected Behavior

Seeing the same terminal output on both screens.

### Actual Behavior

When I drag a Terminal window from one lower resolution screen to a 4k screen the inner size of the terminal window isn't shown correctly. I recorded this video to show what I mean.

https://user-images.githubusercontent.com/34944988/139568896-2e4caeda-0e05-4632-a86e-1195f2e68a17.mp4

Windows Terminal 1.11.2921.0
Windows 21H1 19043.1320

```
BitsPerPixel : 32
Bounds       : {X=3840,Y=1,Width=1680,Height=1050}
DeviceName   : \\.\DISPLAY1
Primary      : False
WorkingArea  : {X=3840,Y=1,Width=1680,Height=1010}

BitsPerPixel : 32
Bounds       : {X=0,Y=0,Width=1920,Height=1080}
DeviceName   : \\.\DISPLAY2
Primary      : True
WorkingArea  : {X=0,Y=0,Width=1920,Height=1040}

BitsPerPixel : 32
Bounds       : {X=-1680,Y=0,Width=1680,Height=1050}
DeviceName   : \\.\DISPLAY3
Primary      : False
WorkingArea  : {X=-1680,Y=0,Width=1680,Height=1010}
```

**Comment by j4james** [comment]
I'm not sure if this is the same thing, but it sounds very similar to issue #6210.

**Comment by zadjii-msft** [comment]
I think this might be more correctly /dup #11317. For some reason, the TermControl? Or the DxEngine? Or something is getting resized to the wrong size.
