### ISSUE TITLE
profile icons in windows 11 "start menu" are often missing or wrong

### ISSUE THREAD

**Issue by jtnord** [microsoft/terminal#11650]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

Windows 11 Pro 21H2

(IIRC this also occurred in 1.10)

### Steps to reproduce

I have a custom profile (java Dev) which adds an icon from a png on the file system, and the other default profiles which use the defailt (embedded icons?) icons in the form `ms-appx:///ProfileIcons/...`

The icons always display correctly in Terminal (in the settings sidebar and the tab)

However if you use the "start menu" in windows 11 to launch terminal with a specific icon, sometimes the icons are missing, or the incorrect icons are used

### Expected Behavior

the icons displayed in windows 11 start menu for launching profiles match the profile icon configured in settings.

### Actual Behavior

* the icons are not displayed at all profiles
* some icons are not displayed and some are not for the profiles
* icons are displayed for all profiles but the incorrect icon is used for some profiles

e.g. 

wrong icons displayed for everythign except java-dev (but everything has an icon)
![image](https://user-images.githubusercontent.com/494726/139430224-fe73209f-7403-48c4-af77-97a0f8d323c6.png)

correct icon shown for java-dev but icons not shown for anything else
![image](https://user-images.githubusercontent.com/494726/139431021-cdcf33df-59b5-4ae1-a23a-cad82f50f4df.png)

This happens intermittently, but once it gets into a funny state it seems to persist in this funny state until a restart of Windows.

**Comment by zadjii-msft** [comment]
Weird. In the first case, they're all falling back to the Terminal's app icon, which I wouldn't expect. In the second case they're just nothing at all, which is perhaps even weirder. 

Would you mind filing feedback on the Start Menu using the Feedback Hub? And make sure to click the "recreate my issue" button, to try and grab whatever logs would be useful. 

I'm not sure there's anything else for us to be doing on our side, this seems firmly like a Start Menu thread, but I'll leave this open so I can make sure to take the feedback item you file and promote it to the right area path ☺️

**Comment by jtnord** [comment]
https://aka.ms/AAepg2m

**Comment by zadjii-msft** [comment]
Cool, this got promoted to MSFT:36905524 internally.

**Comment by zadjii-msft** [comment]
I'm going to close this particular issue since I don't _believe_ there's anything left for us to do, but if anything changes that we can always re-open it. I'm following the internal bug too, so I can post here with whatever the resolution is. Thanks!
