### ISSUE TITLE
Can't set Windows Terminal as the default on Windows 10

### ISSUE THREAD

**Issue by ramonsantana** [microsoft/terminal#11656]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Steps to reproduce

Installed it and it will let me change the default launch to command prompt but it won't replace the command prompt on Windows 10 with the new Windows terminal.
If i run a bat file it will open the command prompt and not this app

### Expected Behavior

Terminal to run when i click terminal related files

### Actual Behavior

Doesn't default as the main terminal on Windows 10

**Comment by j4james** [comment]
I don't think this functionality is supported on Windows 10. Here's what it says in the [blog post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-12-release/#default-terminal) from the last Windows Terminal release:

> You can now set the Windows Terminal stable build as your default terminal emulator if you’re on the Windows Insider Program Dev Channel or Windows 11!
