### ISSUE TITLE
Session Logging

### ISSUE THREAD

**Issue by GitSheru** [microsoft/terminal#11663]
# Description of the new feature/enhancement

Option to enable **session logging**, by which all everything being displayed on the terminal will be saved to a test file. Putty, SecureCRT and other ssh clients normally have this feature and it is extremely useful for network admins who work with switches and firewalls.

# Proposed technical implementation details (optional)

Right click the tab to have option to enable/disable session logging. once clicked, it should ask where the log file should be saved. and once enabled, everything on that terminal tab should be saved to the text file until the session ends or tab closed
![image](https://user-images.githubusercontent.com/58210837/139636374-28476ec9-aa41-4f11-aefb-2fcfa9e16edd.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9700 for more discussion.

/dup #9700
