### ISSUE TITLE
Windows Terminal not working properly with Visual Studio

### ISSUE THREAD

**Issue by maple0xA8F** [microsoft/terminal#11664]
### Windows Terminal version (or Windows build number)

10.0.22000.282

### Other Software

Microsoft Visual Studio Professional 2019
Version 16.11.4

### Steps to reproduce

I open VS2019, select my project, and run a debug. Well it work. But after I exit the program and run the debug again, a error occur.

### Expected Behavior

https://user-images.githubusercontent.com/29698029/139640372-d21741f9-744c-4acd-beb6-3eda9557c072.mp4

### Actual Behavior

No

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10974 for more discussion.

/dup #10974
