### ISSUE TITLE
Unable to find the selected font "Cascadia Mono"

### ISSUE THREAD

**Issue by JGrant-Mastrin** [microsoft/terminal#11660]
### Windows build number

10.0.19043.1288

### Windows Terminal version

1.11.2921.0

### Steps to reproduce

Hard to reproduce, just happened for no discernable reason

### Expected Behavior

Expected behaviour is that no error about font happens and it continue to function as normal

### Actual Behavior

At a random point in time the app will present with an error that does not go away saying 'Unable to find the selected font "Cascadia Mono"'.

Only way to resolve the issue is to reset the app from windows settings, this is a duplicate however the related ticket is locked and closed.

**Related Ticket**
https://github.com/microsoft/terminal/issues/9375

**Comment by whfuyn** [comment]
I have the same problem recently, on two of my laptops.
I've been using Windows Terminal for a long time, and it's the first time I saw this.

One of the laptop's version info:
Windows Terminal version 1.11.2921.0
Windows 20H2 19042.1288
