### ISSUE TITLE
Weird Character Width And Height

### ISSUE THREAD

**Issue by dumb-stuff** [microsoft/terminal#11661]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Steps to reproduce

1. Use windows 11
2. Open windows terminal
3. There's problem

### Expected Behavior

Normal font looking like in windows cmd
![image](https://user-images.githubusercontent.com/59832159/139607968-f8bddcc5-969a-4626-be92-c0981676f198.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/59832159/139607874-cf28f2ce-b28d-4d49-8502-eaa6c53d9ea8.png)

**Comment by j4james** [comment]
This looks like #11032.

**Comment by zadjii-msft** [comment]
Yep, sure is thanks for finding that one 😄 /dup #11032
