### ISSUE TITLE
wsl profile cannot have startingDirectory set to folder whose contents are unreadable

### ISSUE THREAD

**Issue by jsb19gh** [microsoft/terminal#11672]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Steps to reproduce

Create a profile with
```
"commandline": "wsl -u root"
"startingDirectory": "\\\\wsl$\\Distro\\root"
```
Open a tab from that profile. Assumption is that /root is only readable by root in the Linux distribution.

### Expected Behavior

A root prompt in Distro, with `/root` as the current directory.

### Actual Behavior

No interactive prompt, and terminal tab has the text:

```
Access is denied.

[process exited with code 4294967295]
```
More info:
This worked in earlier Windows Terminal versions.
If I set that startingDirectory for a powershell tab, it works fine.
If I set the startingDirectory to `"\\\\wsl$\\Distro"`, it works fine

**Comment by zadjii-msft** [comment]
`4294967295` is `ERROR_UNHANDLED_ERROR`, cool, that's useless. 

Seems to work just fine from the commandline,

![image](https://user-images.githubusercontent.com/18356694/139856418-9cab353d-71ff-4a18-be07-f3834b047173.png)

So this _should_ work. huh.

**Comment by DHowett** [comment]
This is an interesting outcome from promoting the starting directory to `--cd`, actually.

Terminal ends up calling `wsl --cd \\wsl$\Distro\root`, _not_ `wsl --cd /root`. `wsl.exe` attempts to open `\\wsl$\Distro\root`, fails because the Plan9 server throws it an access error, and then just aborts.

The thing is... at this point, Terminal is fully out of the equation. It doesn't control whether `wsl` aborts when it encounters this issue.

My only question is ...

> This worked in earlier Windows Terminal versions.

_What did it do?_ Where did it put you? That directory is illegal to access :smile:

**Comment by jsb19gh** [comment]
It did what I wanted, I had a root prompt and the working directory was `/root`. You may not be able to access anything in the directory, but apparently you can still set it as your current folder. If you set that path as `startingDirectory` for a powershell instance instead, it will happily give you a powershell prompt. Get-ChildItem will give access denied of course, but it has no objections to making it the current folder.

**Comment by elsaco** [comment]
WSL Ubuntu has `/root` permission set to `700`. Relaxing it a bit (like `755`) it will allow `/root` access. 

Here's sample output from pwsh prompt after changing permission:
```
PS C:\Users\tux> ls '\\wsl$\Ubuntu-20.04\root'

    Directory: \\wsl$\Ubuntu-20.04\root

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            5/3/2021  8:38 AM                .cache
-----           11/4/2021  6:26 PM            346 .bash_history
-----           12/5/2019  6:39 AM           3106 .bashrc
-----           11/4/2021  6:06 PM              0 .motd_shown
-----           12/5/2019  6:39 AM            161 .profile

PS C:\Users\tux>
```

Profile setting:
```
            {
                "colorScheme": "Campbell",
                "commandline": "C:\\Windows\\system32\\wsl.exe -d Ubuntu-20.04 -u root",
                "guid": "{ddd8505c-b727-4659-8496-a060f860cb7b}",
                "hidden": false,
                "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
                "name": "Ubuntu-Test",
                "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\root"
            }
```

However, relaxing `/root` file permissions might become a security issue.

**Comment by yangliuly1** [comment]
I have the same problems. l fixed it:
First, for terminal command
```bash
$ wsl
$ cd /
$ sudo chmod 755 root
````
Then, for terminal settings:
```json
"commandline": "wsl.exe -d Ubuntu-16.04 -u root",  
"startingDirectory": "\\\\wsl$\\Ubuntu-16.04/root",  
```

**Comment by carlos-zamora** [comment]
Is this still happening? Nowadays, we're recommending linux style paths for these kinds of scenarios.
