### ISSUE TITLE
Terrible Text Rendering

### ISSUE THREAD

**Issue by kXborg** [microsoft/terminal#11679]
### Windows Terminal version (or Windows build number)

10.0.22000.0

### Steps to reproduce

Just Open Windows Terminal and change the font to 'courier new
![Poweshell_text_issue](https://user-images.githubusercontent.com/55614432/140057394-fa56890e-8341-4454-aea1-222bd5a038eb.jpg)
'.
Same issue with default text as well. Please fix it.

### Expected Behavior

Clearly rendered text. That's All.

### Actual Behavior

Showed truncated text as shown in the image.

**Comment by zadjii-msft** [comment]
Hmmm. That's definitely weird, but I can't seem to repro that exactly with Courier New myself. It's like, it's being aliased weirdly? Or clipped?

Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

What DPI scaling is your display set to?

**Comment by kXborg** [comment]
**The display is set at custom factor 118%.**
![display-info](https://user-images.githubusercontent.com/55614432/140084749-da1e9f7f-aa6c-43a2-a8ae-42fb063cef8b.jpg)
I am attaching settings.json here.
[settings.txt](https://github.com/microsoft/terminal/files/7468488/settings.txt)

**Comment by zadjii-msft** [comment]
Ah well, that'll do it. /dup #4591
