### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#1167]
![image](https://user-images.githubusercontent.com/4319522/59127618-22682280-8936-11e9-9cf2-1d6f04540782.png)

VS2019

**Comment by boldcronie** [comment]
Re-target from the projects from 141 to 142. The last one in the window (WinRT) might mean you need to update the submodules (check the command line / PowerShell options). Maybe. Actually, I think it literally is indicating that one or more of the pre-req's isn't being met, but I think it actually gets cleared up with a re-target.

**Comment by musm** [comment]
I've done all that, yet I still see build failures

**Comment by zadjii-msft** [comment]
Please keep all build-failure related discussion to #489.
