### ISSUE TITLE
Duplicate Tabs & Panes are not Duplicates

### ISSUE THREAD

**Issue by stephenmartindale** [microsoft/terminal#11678]
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Steps to reproduce

1. Open *Windows Terminal* with a starting-directory and command-line set, for example:
    ```
    %localappdata%\Microsoft\WindowsApps\wt.exe new-tab --commandline %SystemRoot%\System32\cmd.exe /c "path/to/python-environment.bat && python.exe path/to/interactive/program.py"
    ```

2. Press the keyboard shortcut to *duplicate* the current tab: `ctrl+shift+d`
    - Alternatively, split the pane.

3. Observe that the duplicated tab does not invoke the command-line given in `--commandline`
    - Starting directory (`-d`) is also not applied.

### Expected Behavior

I expect that the *duplicate* tab (or pane) should be a true duplicate. I.e. it should be created with precisely the initialization parameters of the original tab (or pane), including *at least* the following most important ones:

- Profile
- Starting Directory
- Command Line

### Actual Behavior

- The duplicated tab does not invoke the command-line given in `--commandline`
- Starting directory (`-d`) is also not applied.

**Comment by zadjii-msft** [comment]
... this is what we're tracking with #5047. When https://github.com/microsoft/terminal/issues/5047#issuecomment-934547500 mentions `NewTerminalArgs`, that's the bundle of things like `startingDirectory`, `commandline`, etc.

/dup #5047
