### ISSUE TITLE
Terminal + Neovim: FocusLost/Gained events don't fire.

### ISSUE THREAD

**Issue by mikatpt** [microsoft/terminal#11682]
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Other Software

Neovim 0.5+

### Steps to reproduce

Steps to reproduce:
1) Run Neovim 0.5 or higher using the following `min.vim` file, with the command `nvim -u min.vim --clean`
```vimL
" min.vim
autocmd FocusLost * echo "Focus Lost"
autocmd FocusGained * echo "Focus Gained"
```
2) Click away from terminal. Click to.
3) Vim command line output at the bottom of the screen should update with the echoed text.

### Expected Behavior

See title and steps to reproduce. This works in all Linux/MacOS terminals I've used, including Alacritty, Kitty, and iTerm2, as well as in tmux sessions if focus-events are enabled.

The Vim/Neovim release is not particularly important unless you would also like to test in tmux; in that case, choose a release any time after April 2021 and put `set -g focus-events on` in your `.tmux.conf`

### Actual Behavior

Nothing happens.

**Comment by j4james** [comment]
I suspect this is because we don't support XTerm's focus event mode (private mode 1004). I thought there might have been an issue for it already, but I haven't been able find one.

**Comment by zadjii-msft** [comment]
Well cool, I would have suspected there was an issue already for this. Plumbing through conpty shouldn't be too hard, if a bit annoying.

**Comment by zadjii-msft** [comment]
Oh boy I sure did go overboard on my branch off #12799. We may just have to do this whole thing, so, here it is:

![gh-11682-works](https://user-images.githubusercontent.com/18356694/162237799-3f982ffb-db09-4294-bb45-a1b6bcb4f1c8.gif)


[`dev/migrie/b/2988-focus-fg-with-owner`...`dev/migrie/f/11682-vt-focus-events`](https://github.com/microsoft/terminal/compare/72e3ed48093e2ffcd0985a9792cb47f5c619a105...dev/migrie/f/11682-vt-focus-events)
