### ISSUE TITLE
WSL profile generator inserts carriage returns into the distribution names

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1168]
![image](https://user-images.githubusercontent.com/14316954/59139146-f2c11680-8945-11e9-951f-fd1926ee02dc.png)

This is also carried forward into the commandline, `wsl.exe -d <distro>`, as such:

```json
{
    "commandline" : "wsl.exe -d Alpine\r\r"
}
```

**Comment by DHowett-MSFT** [comment]
As a note: this does prevent the distribution from being launched.

**Comment by DHowett-MSFT** [comment]
> ![image](https://user-images.githubusercontent.com/29011440/59155310-72bfbb80-8ac1-11e9-95ca-77bb001f4917.png)
> 
> so I saw the settings (profiles.json), it looked crazy.
> 
> ```
>         {
>             "acrylicOpacity" : 0.5,
>             "closeOnExit" : true,
>             "colorScheme" : "Campbell",
>             "commandline" : "wsl.exe -d Ubuntu(\uae30\ubcf8\uac12)\r\r",
>             "cursorColor" : "#FFFFFF",
>             "cursorShape" : "bar",
>             "fontFace" : "Consolas",
>             "fontSize" : 10,
>             "guid" : "{6408c1b2-1145-55cb-b519-64a858cb4495}",
>             "historySize" : 9001,
>             "icon" : "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
>             "name" : "Ubuntu(\uae30\ubcf8\uac12)\r\r",
>             "padding" : "0, 0, 0, 0",
>             "snapOnInput" : true,
>             "useAcrylic" : false
>         }
> ```
> 
> So that, I have tried to open the WSL(ubuntu) profile with no changes with profiles, it closes right after open it. I couldn't even see the command line.
> 
> I have decoded \uae30\ubcf8\uac12 to UTF-8, 기본값 as Korean, which it is **Default** for English. (I am using windows as Korean, KO-KR)
> Seems it runs (Default)\r\r at commandline so wsl couldn't run. BTW name should not have \r\r too.

_from @Sjang1_

**Comment by JBanks** [comment]
@benhillis Can you tell me that the left parenthesis is a disallowed character in WSL Profile names?  I couldn't see any restrictions here: https://github.com/Microsoft/WSL-DistroLauncher#getting-started

If so, I'll rework the code to stop at the parenthesis and then remove any spaces or carriage returns from the remaining string.  I can also have this thrown into #1169 by Monday

If parenthesis are allowed, I could do a search for the localized default string with parenthesis wrapped around it and remove that from the line.  This will require a bit more research as I haven't done localizations before.  If this is the case, I'd like to merge #1169 to solve the /r problem and get it out of the way while I try to solve this.

@SJang1 When you decoded the string, did you place the decoded string back into profiles.json in order for it to show up properly in the flyout menu, or did that work well on it's own?

**Comment by benhillis** [comment]
Parentheses and spaces are not allowed.

**Comment by SJang1** [comment]
@JBanks for encoding of UTF-8-BOM which is vs setting, it doesn't load and does not show up properly, changing to UTF-8 (no BOM) shows up well.

**Comment by JBanks** [comment]
@SJang1 Everything from #1169 should fix your issue for now.  It will end the line on spaces or parenthesis.
