### ISSUE TITLE
How to disable character rendering like from '>=' to '≥', from '!=' to '≠'

### ISSUE THREAD

**Issue by luooofan** [microsoft/terminal#11683]
Actually this is just my question about wt,  maybe it can become a feature.

# Description of the new feature/enhancement
Provide an option which controls the character rendering like from '>=' to '≥', from '!=' to '≠'
To be honest, it's a wonderful feature, but there are some unsuitable situations.
e.g. 'expr<...,...>=[...]' 

# Proposed technical implementation details (optional)
None

**Comment by KalleOlaviNiemitalo** [comment]
AFAIK, this is can be configured in [Font features](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#font-features). Or choose a font that does not define those ligatures.

**Comment by KalleOlaviNiemitalo** [comment]
See also <https://github.com/microsoft/terminal/issues/10525> and <https://github.com/microsoft/terminal/issues/759> and ["Font features and axes of variation" spec](https://github.com/microsoft/terminal/blob/39b72f78c3d10d0ef1d745608e67f69c28adfe6d/doc/specs/%231790%20-%20Font%20features%20and%20axes-spec.md).

**Comment by luooofan** [comment]
Thanks for your reply.
That's exactly what I want.
