### ISSUE TITLE
Cannot open Terminal by clicking Win11 start menu

### ISSUE THREAD

**Issue by quanljh** [microsoft/terminal#11696]
### Windows Terminal version (or Windows build number)

OS Version: Win 11 22000.282,  Terminal Version: 1.12.2931.0

### Steps to reproduce

1. Right click start icon in task bar
2. Click Windows Terminal or Windows Terminal(Administrator)

### Expected Behavior

Can open Windows Terminal Preview successfully.

### Actual Behavior

Nothing happened.
I can open Windows Terminal Preview by right clicking desktop and click "Open in Windows Terminal Preview" option. But cannot open it from the start menu.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10595 for more discussion.

/dup #10595

**Comment by quanljh** [comment]
Thanks @zadjii-msft
