### ISSUE TITLE
Windows Terminal maximize icon should give an option to tiling arrangement like other windows in Windows 11.

### ISSUE THREAD

**Issue by anurag2361** [microsoft/terminal#11698]
# Description of the new feature/enhancement

 Whenever we hover over the maximize icon in windows in Windows 11, we get 4 options of different window arrangements. This isn't the case with Terminal. For someone who has many windows open, Terminal arrangement will be important. Also, it should adhere to Windows 11 design guidelines for coherence.

# Proposed technical implementation details (optional)

When cursor is hovered over Maximize icon in Terminal, we should get 4 options for window arrangement.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9443 for more discussion.

/dup #9443
