### ISSUE TITLE
Support extensions a la VS Code

### ISSUE THREAD

**Issue by gbritton1** [microsoft/terminal#11695]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Please add support for community-built extensions, perhaps something similar to that found in VS Code and Azure Data Studio.  

One extension that I would love to see is a way to save remote hosts for SSH, telnet etc.  You can start simple, with a menu for hostnames and login usernames.

**Comment by DHowett** [comment]
Thanks for the request! We're tracking the need for extensions (and a WHOLE bunch of extension ideas!) over in /dup #4000.
