### ISSUE TITLE
autoexec.bat

### ISSUE THREAD

**Issue by jim-tyson** [microsoft/terminal#11702]
# Description of the new feature/enhancement

Remember in the DOS days, the c:\autoexec.bat file would run on machine startup?  It would be really cool if I could add a reference to an 'autoexec.cmd' file in a profile configuration, which would execute automatically whenever I start up that profile.  I could put echo statements, run any cmd shell commands or set environment variables that I want, etc. 

This would take a lot of burden off the settings you have to store, since I can set up the environment how I want in the batch file.

**Comment by PhMajerus** [comment]
This is already possible, simply change the Command line of the profile to call the .cmd file you want when launched, for example:
`cmd.exe /K call %USERPROFILE%\autoexec1.cmd`
You can duplicate the profile with different command files to easily get different environments.

**Comment by zadjii-msft** [comment]
Yep, not sure I have anything else to add here. Thanks!
