### ISSUE TITLE
Add useAcrylic for title bar too

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/terminal#11705]
# Description of the new feature/enhancement

Add `useAcrylic` settings for terminal `tab`

![image](https://user-images.githubusercontent.com/77537933/140662822-4e7c292f-f5cb-4623-a46b-c7f0307f27bd.png)

The difference between below window and tab looks ugly.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is already a setting, please see [`useAcrylicInTabRow`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/appearance#show-acrylic-in-tab-row).

For other theming asks, we're tracking those in /dup #3327, including matching the tab to the background of the Terminal, as well as matching the titlebar to the terminal content.
