### ISSUE TITLE
Tab bar should better indicate that the window is active without needing the extra title bar

### ISSUE THREAD

**Issue by markusjevringsesame** [microsoft/terminal#11709]
# Description of the new feature/enhancement

In at least Windows 11, there's very little visual distinction between active and inactive windows. Since the tab bar is also the title bar by default, it would be nice if it did a better job of indicating whether the window is active or not. Right now I have resorted to enabling the title bar for the window just to see the accent color, but this makes it unnecessarily tall. It would be nice if the tab bar could, in some way, display the active highlight color when focused. Today all we have is a slight accented outline, and it would be nice to at least have the option of indicating more strongly that the window is active. Preferably in the tab bar.

# Proposed technical implementation details (optional)

Change the color of the tab bar when active, potentially. Obey the accent color.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4862 for more discussion.

/dup #4862
