### ISSUE TITLE
Add option to completely disable scrollbar.

### ISSUE THREAD

**Issue by rkitover** [microsoft/terminal#11701]
# Description of the new feature/enhancement

With `scrollBarState: "hidden"` set in the profile settings, there is still a white line in the lower right of the terminal indicating the presence of scrollback. I would like to be able to completely disable the scrollbar, and not just put it in the hidden state.

# Proposed technical implementation details (optional)

Perhaps allow setting `scrollBarState: "none"` to completely disable scrollbar functionality.

**Comment by zadjii-msft** [comment]
@rkitover Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

**Comment by rkitover** [comment]
This is what it looks like:

![window screenshot](https://lh3.googleusercontent.com/pw/AM-JKLW238MkrICH9ReojVPcd0UIrn6M6Eci8dhR8hiavHnthiUcsyEot-rQu3ajrqWiMMFzY_7c20c0uWUvf-D-7b-2wL8OvbpolP51_9O--j-hx-GD2Itz_RB_NYeItqUEvp-Gzua39ERdRxMKkdmmrswD=w1026-h962-no?authuser=0)

Here's my settings.json

https://gist.github.com/rkitover/267a6d84fb2cf80343b1737de32b363d

This is Terminal Preview version 1.12.2931.0

**Comment by zadjii-msft** [comment]
The property is [`scrollbarState`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#scrollbar-visibility)

you have `scrollBarState`.

The properties are case-sensitive 😄

**Comment by rkitover** [comment]
That does fix it, thank you, sorry about that.

Also I wanted to mention that this property is not on the documentation page currently.

**Comment by zadjii-msft** [comment]
> Also I wanted to mention that this property is not on the documentation page currently.

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#scrollbar-visibility

**Comment by rkitover** [comment]
My apologies again, for some reason I did not see it, and I looked through all the sections.
