### ISSUE TITLE
Terminal/CMD became weird after exiting nslookup in WSL

### ISSUE THREAD

**Issue by jamiephan** [microsoft/terminal#11708]
### Windows Terminal version (or Windows build number)

10.0.19043.1288, 1.11.2921.0

### Other Software

`nslookup` in WSL (Ubuntu, `dnsutils`)

### Steps to reproduce

1. Start up Terminal
2. Enter WSL with `wsl`
3. Enter `nslookup`'s interactive mode, with `nslookup` command in WSL
4. Exit `nslookup` with `Ctrl + C`

### Expected Behavior

After exiting, the bash should behave normal:

 - Enter = new line
 - Type in charatcer should show characters 

### Actual Behavior

`Enter` key does not make the text new line:

![image](https://user-images.githubusercontent.com/9488815/140720250-7231f5ab-6fd2-40e3-a81c-57523bd1f8f1.png)

Typing in characters will not show up, but able to execute it:

(Example of typing in `whoami` and invalid command `hello`, which returns the result but not showing my typed text)

![image](https://user-images.githubusercontent.com/9488815/140720590-3c31a0e8-8446-4afe-b8c1-973e7102e4b0.png)

**Comment by zadjii-msft** [comment]
Does `reset` fix the prompt? This sounds like `nslookup` did something to either the terminal modes, or did something to the `stty` modes (which might be fixed with a `stty sane`)

**Comment by jamiephan** [comment]
Yes, both `reset` and `stty sane` fixed the issue!

I guess its `nslookup`'s problem then. 

Thanks for the help.

(I'll also close this issue since the problem is not related to wt)
