### ISSUE TITLE
Italic text is cutted off

### ISSUE THREAD

**Issue by gdnathan** [microsoft/terminal#11715]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

neovim 6.0 (inside wsl)
nvim-treesitter

### Steps to reproduce

install wsl and neovim.
install "nvim-treesitter" (nvim plugin), turn on hightlightig
open a jsx file, write "<Container id={someid}>"

### Actual Behavior

the "d" of "id" is in italic (treesitter behavior), and cutted of (windows terminal related, i tracked the issue on nvim-treesitter [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/1992)

images:
![image](https://user-images.githubusercontent.com/53536851/140782814-34030750-71e7-46a6-b926-d794a97f156d.png)
and even with a space after: 
![image](https://user-images.githubusercontent.com/53536851/140782888-de5548b1-48ee-4761-95de-84075c469024.png)

it mean on a big block of code:
![image](https://user-images.githubusercontent.com/53536851/140783671-506017e2-473e-4723-8664-426625556cd6.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9381 for more discussion.

/dup #9381
