### ISSUE TITLE
Crash when using ssh and output long line when using magnifier

### ISSUE THREAD

**Issue by ganlvtech** [microsoft/terminal#11713]
### Windows Terminal version (or Windows build number)

10.0.19043.0, 1.11.2921.0

### Other Software

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
PowerShell 5.1.19041.1237

### Steps to reproduce

Open a PowerShell tab in Windows Terminal.
ssh to some host and cat a text file with more than 20k chars (eg. 20k `a`s) in the first line.

```
ssh.exe -t username@hostname cat ~/longtext.txt
```

I found this issue when I compile some program. I got a very long compile error. It displays the cmdline `cc` + many `.o` filef in the same line. And then, terminal crashed.

```
   Compiling .... v0.1.0 (/home/....)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/.... very very lone line
```

### Expected Behavior

Output a long line.

### Actual Behavior

Windows Terminal crashed and all tab closed. If it doesn't happend, repeat 1 to 3 times.

It maybe need to repeat 4 ~ 6 times when using `ssh` without `-t`.

If I open a standalone PowerShell window. It's OK.

## Summary

| tools                       | result    |
| --------------------------- | --------- |
| wt + powershell + ssh + cat | crash     |
| wt + cmd + ssh + cat        | crash     |
| wt + git-bash + ssh + cat   | crash     |
| wt + powershell + cat       | not crash |
| wt + git-bash + cat         | not crash |
| powershell + ssh + cat      | not crash |
| cmd + ssh + cat             | not crash |
| git-bash + ssh + cat        | not crash |

**Comment by zadjii-msft** [comment]
Huh. Could have swore we had an open discussion for this one. Any chance you're running narrator or Windows Magnifier?

If this repros fairly consistently, could you reproduce it with the Feedback Hub? That should give us a crash dump with a stack we can investigate. /feedback

**Comment by ganlvtech** [comment]
Yes. I'm running Windows Magnifier. I usually use 100% zoom level and `Ctrl + Alt + I` to invert color at night.

It won't crash if I close the magnifier.

**Comment by zadjii-msft** [comment]
> Yes. I'm running Windows Magnifier

oh ho ho, thanks for confirming! I'd bet that this is /dup #8730
