### ISSUE TITLE
Terminal not showing option for wsl and powershell core.

### ISSUE THREAD

**Issue by aadarshashutosh** [microsoft/terminal#1171]
Hi, I'm Currently running Windows 10 Home v1903 (OS Build 18362.145)

I downloaded the Windows Terminal Preview appx package from [geekermag](https://geekermag.com/download-windows-terminal-app-windows-10/) and after installing, The Terminal doesn't detect my Linux Distro on windows as well as Powershell Core.
I'm fairly new to such "programming", how do I add the options through setting or do I need to wait for some fix (in case this is a bug)?
![Screenshot (62)](https://user-images.githubusercontent.com/34771316/59143218-2fdce580-89e6-11e9-9518-ac2a57bdab57.png)
![Screenshot (63)](https://user-images.githubusercontent.com/34771316/59143182-bc3ad880-89e5-11e9-94d2-11c4a5ced6c2.png)
![Screenshot (64)](https://user-images.githubusercontent.com/34771316/59143181-bba24200-89e5-11e9-80bf-002e15e50860.png)

**Comment by DHowett-MSFT** [comment]
Hey look, this is one of the biggest reasons you shouldn’t use random copies of applications produced by random people! All of these complaints have been fixed; some for days, some for weeks.

Please either wait for an official release or compile the project yourself to make sure you have the latest version!

**Comment by DHowett-MSFT** [comment]
Thanks for your interest, as always. :smile:

**Comment by aadarshashutosh** [comment]
I tried to build myself, and it almost cost me my entire windows partition free space, expanding up to 24 GB!! and then failed to launch. Is there any way I can get a binary or appx package of Terminal Preview??

Also, I thought when they said they are making a terminal, so are they like making a terminal which has it's own commands or like a launcher for installed shells like Powershell, cmd etc...

**Comment by zadjii-msft** [comment]
We're building a _terminal_, which like terminals on every other platform, acts as a UI for your commandline applications. We're _not_ building a new _shell_, like Powershell or cmd.exe. 

When the Terminal is in a state that's ready for release, I'm sure you'll hear about it. We'll publish a package to the store. If you want to try it early, that's what this repo is for. 

I'd take a look at #489, which has lots of tips for helping get the terminal building.

**Comment by MarkfriedFellensiek** [comment]
to be fair to the original poster, the fully released and stable versions still do it to this day (September 2020).

**Comment by zadjii-msft** [comment]
@MarkfriedFellensiek If this is still happening to you on the stable release version, then you probably should file a new bug so we can help debug this 😉
