### ISSUE TITLE
MSYS2 Vim buffer is stuck in the terminal window when scrolling back

### ISSUE THREAD

**Issue by matteocoder** [microsoft/terminal#11726]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.12.2931.0

### Other Software

vim 8.2.3441 (MSYS2 version, from Git Bash),
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys).

### Steps to reproduce

Prerequisite:
Create a new profile with the following command line command:
```
C:\Program Files\Git\bin\bash.exe --norc --noprofile -i -l
```
and start a new terminal tab using that profile.

1. Invoke a program, such as `yes`, whose output scrolls the terminal window, allowing you to scroll back, then press `ctrl-c` to stop it;
2. invoke `vim`, and then  issue the command `:version`;
3. quit Vim

### Expected Behavior

When scrolling back, only the output from `yes` should be visible.

### Actual Behavior

Vim's  interface remains "stuck" on the terminal window and mixes with the output of `yes`. The screenshot shows the issue.

![vim stuck](https://user-images.githubusercontent.com/22897138/141172987-7fcd56fe-cdbf-4bbe-a017-4b7b662c1106.JPG)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #381 for more discussion.

/dup #381
