### ISSUE TITLE
WT command option parsing error

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11729]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

Windows  10.0.22000.0

### Steps to reproduce

run `wt -version` command, single hyphen

### Actual Behavior

![wt_version](https://user-images.githubusercontent.com/3933920/141243436-27aeab4b-6441-40a4-8234-eca2901ca817.png)

**Comment by zadjii-msft** [comment]
So, that's definitely _weird_, but I suspect that's just an artifact of the way CLI11 parses flags. It's treating `-version` similar to `-v -e -r -s -i -o -n`. The `-v` it recognizes, but the rest are not.
