### ISSUE TITLE
WT picks an incorrect profile icon

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#11732]
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Steps to reproduce

1. Open WT.
2. Go to Settings, add a new profile or edit an existing one.
3. Set the profile icon to this: [size_test.zip](https://github.com/microsoft/terminal/files/7521109/size_test.zip)

### Expected Behavior

A pixel-perfect 16x16 green-black icon with a chess pattern, loaded from the icon file **as is**:

![image](https://user-images.githubusercontent.com/11453922/141315329-eef0a637-d642-4f22-9081-14ebb191b9c7.png)

### Actual Behavior

A 24x24 yellow-black icon, loaded from the icon file and **downscaled** to 16x16:

![image](https://user-images.githubusercontent.com/11453922/141315391-41b6501d-d159-4ce5-bfc3-8799a6c5faba.png)

## Details

The test icon file above contains icons of 5 different sizes (256, 48, 32, 24, 16 px). Each icon has distinct contrast colors to make it obvious which exactly size is used and whether it's rescaled or not:

![image](https://user-images.githubusercontent.com/11453922/141318773-1b2d201c-7643-4123-a5b9-d97fc2f24881.png)

WT uses 16x16 icons for profiles tabs, so I expect it to pick a 16x16 icon if it's **already available**, not pick something else and downscale it. Such downscaling breaks the initial intention and leads to ugly and blurry results.

A real world example:

![image](https://user-images.githubusercontent.com/11453922/141317038-673d5e53-f99a-4443-970a-299d84392b15.png)
![image](https://user-images.githubusercontent.com/11453922/141317215-d240638a-8a15-4113-95e6-ad3c53e3b54a.png)

**Comment by zadjii-msft** [comment]
I honestly did not know that XAML supported `.ico` files _at all_ 😅 

This kinda sounds like a bug for the WinUI repo - I'm not sure we can control which resolution of an icon that `BitmapIcon` picks...

**Comment by alabuzhev** [comment]
> This kinda sounds like a bug for the WinUI repo

Interesting, that kinda explains why Windows Taskbar has exactly the same issue - it downscales 32x32 to 24x24 instead of using native 24x24...
If it's outside of your control it would be great if someone could transfer this to the proper repo.

**Comment by zadjii-msft** [comment]
I've moved this discussion over to /dup https://github.com/microsoft/microsoft-ui-xaml/issues/6307. If there's anything actionable for us to do as a follow-up to that discussion, we can reopen this thread. Thanks!
