### ISSUE TITLE
Sync settings.json to gist (same as in Visual Studio Code)

### ISSUE THREAD

**Issue by ob1-sc** [microsoft/terminal#11747]
# Description of the new feature/enhancement

Please can we have an option to sync our terminal settings to a public gist in the same way that we can with Visual Studio Code? This would give users an easy to use backup/restore option for settings, particularly across multiple development machines and would follow an already well accepted approach to backing up personalised settings in Visual Studio code.

Many thanks.

**Comment by zadjii-msft** [comment]
Sounds like you're talking about this 3rd party extension? [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

This totally sounds like something a third party tool could implement! Heck, they could store your settings as [Fragments](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions), and just stash all the changes to your settings in a json file that the Terminal loads on top of your `settings.json`.

It's a cool extension (#4000) idea, but not one I think we need to do any more on our side to support!
