### ISSUE TITLE
Changing Console Host breaks Win 11 boot

### ISSUE THREAD

**Issue by pwasiewicz** [microsoft/terminal#11749]
### Windows Terminal version (or Windows build number)

10.0.22000.0

### Other Software

Oh My Posh

### Steps to reproduce

1. On Windows 11 (newest non-insider version)
2. Install PowerShell Core 7.2
3. Set as PowerShell as default shell
4. Change Console Host to Windows Terminal 
5. Install and setup oh-my-posh
6. After restart, win 11 goes into recovery loop - autofix not working (event safe mode!)

### Expected Behavior

System should restart properly.

### Actual Behavior

1. Unable to start Windows
2. Unable to boot with SafeMode
3. No Srt logs created. 

Reproduced twice on clean win install. Unfortunately I have no more time to test it - PC reset was required to make Windows boot again, everytime. 

No issues on win 10

**Comment by zadjii-msft** [comment]
HUH, that's bad. Might be similar to #11676. I'd suspect that the PowerShell Core bits don't necessarily have anything to do with the root cause... If they do that would raise _more questions_. Also maybe related: #11164

**Comment by DHowett** [comment]
We've not seen any other reports of this on any other channels; I'm going to bump it from 1.14 for now.

**Comment by miniksa** [comment]
I've been unable to find a repro scenario of this even with all the other defapp issues I've seen recently. I'll have to resolve it for now.
