### ISSUE TITLE
Is there a way to shrink this command?

### ISSUE THREAD

**Issue by Dosx001** [microsoft/terminal#11740]
```json
{ "command": { "action": "multipleActions",
    "actions": [
        { "action": "splitPane", "split": "vertical" },
        { "action": "resizePane", "direction": "left" },
        { "action": "resizePane", "direction": "left" },
        { "action": "resizePane", "direction": "left" },
        { "action": "resizePane", "direction": "left" },
        { "action": "resizePane", "direction": "left" }
    ]},
    "keys": "ctrl+shift+s"
}
```
Something like this?
```json
{ "command": { "action": "multipleActions",
    "actions": [
        { "action": "splitPane", "split": "vertical" },
        { "action": "resizePane", "direction": "left", "amount" : 5 },
    ]},
    "keys": "ctrl+shift+s"
}
```

**Comment by zadjii-msft** [comment]
[`splitPane`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#split-a-pane) already accepts a `size` parameter, to configure what percent of the parent you want the new pane to take. So you probably want something like 

```json
{ 
    "command": { "action": "splitPane", "split": "vertical", "size": 0.75 },
    "keys": "ctrl+shift+s"
}
```

**Comment by Dosx001** [comment]
@zadjii-msft Thank you!!! I can't find it in the documentation or anywhere. Might wanna update the documentation to include this. https://docs.microsoft.com/en-us/windows/terminal/panes

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/141817459-2bbea521-8c6d-4ac8-9e8e-7ccee28488f2.png)

**Comment by Dosx001** [comment]
@zadjii-msft huh, I never check out this page. I will read it later, thank you. But it would have been really nice if was in was in this page https://docs.microsoft.com/en-us/windows/terminal/panes or maybe some redirection to the page you show me.

**Comment by zadjii-msft** [comment]
The Panes page actually does have a link to the keybindings in it:
![image](https://user-images.githubusercontent.com/18356694/141820840-972e164b-b4c5-4b7b-8fbc-5a0233780b5d.png)
