### ISSUE TITLE
Cursor position moves into the content when Terminal window is maximized

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#11745]
### Windows Terminal version (or Windows build number)

Terminal: 1.11.2921.0
Windows: 10.0.22000.318

### Steps to reproduce

Open the Windows Terminal in the default-sized window and run any command which returns a good amount of content as its output like `dotnet new blazorwasm --help` so that it takes up some screen space.

Run the command and then maximize the Terminal window, the cursor position jumps into somewhere in the output content of the previous command rather than in a new blank line.

Refer to the below screenshot for visual representation, the current cursor position is highlighted.

<img width="960" alt="Windows-Terminal-Window-Resize-Cursor-Issue" src="https://user-images.githubusercontent.com/81947404/141455920-051ac2f5-e9de-4499-aefc-196a122f5f4c.png">

### Expected Behavior

The cursor position should stay in the current blank line even when windows get resized (maximize, manul resizing).

### Actual Behavior

The cursor position moves into the output content of the previous command.

**Comment by zadjii-msft** [comment]
THAT IS A VERY CONSISTENT REPRO FOR THIS BUG!

THANK GOD!

I've been looking for a consistent repro for _months_. This is a great thing to have. The bugger picture is #5800, but I think #7253 is specifically the same root cause as this. I'm gonna move this repro there. Thanks!

/dup #7253

**Comment by egvijayanand** [comment]
Glad to know at least it helped to repro the issue in a consistent way.

Hope a fix will be made available at the earliest.
