### ISSUE TITLE
Launching pwsh using `runas` doesn't inherit profile's theme

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11741]
### Windows Terminal version (or Windows build number)

WT 1.11.2921.0

### Other Software

Windows 11 build 22000.318

### Steps to reproduce

1. set PS7 as default profile
2. set `Default terminal application` to `Windows Terminal`
3. change `Campbell` color scheme to a different one, `Solarized Light` in this case
4. start a new WT as admin: `start-process -filepath "pwsh" -verb runas`

### Expected Behavior

A new WT window with elevated privileges

### Actual Behavior

A non-WT window is being launched, font is Consolas:

![wt_pwsh_runas](https://user-images.githubusercontent.com/3933920/141388414-c19522ab-8bc3-4dc2-8bf8-d1dbc7019813.png)

**Comment by DHowett** [comment]
Thanks for the report! Though the steps may be different, this is the same as /dup #10276 (which we should document and/or pin!)
