### ISSUE TITLE
Can't move window (no, for real)

### ISSUE THREAD

**Issue by seanofw** [microsoft/terminal#11746]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

WSL 2

### Steps to reproduce

Open Terminal.  It mysteriously spawns behind every other window for some reason.  Try to drag its around, or close it, or minimize it, or maximize it.  None of those actions work unless I click _outside_ its window afterward, and then they happen instantly.

### Expected Behavior

Normal window behavior?  I can drag it, and it drags.  I can close it, and it closes.

### Actual Behavior

I turned on my computer this morning (Windows 10.0.19043.1288), and opened a couple of Firefox windows and Discord, and then opened Terminal.  Several very strange things happened:

- First, its window spawns _behind_ every other window.  I have to click it to bring it to the foreground, every time.  If I close and reopen it, it spawns _behind_ every other window again.
- Second, I can't drag it.  I discovered, though, that in some cases if I clicked outside the tab area to drag it, it would eventually "move," but only _after_ it lost focus -- i.e., after I finished the drag, if I clicked on _another_ window, or the Start Menu, then suddenly it would jump to approximately where I'd dragged it).  This only works about half the time, though.
- Third (and this is super-weird) I started poking at its settings to see if something had changed in it.  Opening other tabs (WSL, Powershell, cmd) has no effect on its behavior, but if a _Settings_ tab is open, and _only_ if a Settings tab is open, suddenly the window can be dragged normally!  The moment the Settings tab is closed, though, it reverts back to the same non-dragging behavior.  Or if I simply click back to the WSL tab, leaving Settings "open" in the background, it stops working again as well.
- The lack of normal nonclient behavior extends beyond just dragging.  If I click the "X" to close it, for example, it doesn't actually close until it loses focus to another window.  Same for minimizing or maximizing.

When it spawns, it has only one WSL bash prompt in it.  No Powershell, no cmd, nothing else.

I really don't know quite what's going on here:  It's as though all nonclient messages are getting batched up when they occur, and then only get delivered when the window loses focus.

It happens really consistently right now.  I'm not sure if it'll happen after I reboot Windows, but it started happening on a fresh boot this morning, so it might continue happening after a reboot.

That's all I have.  My current workaround for making it usable is to leave a Settings tab open and switch to it whenever I want to drag the window.  ¯\_(ツ)_/¯

**Comment by seanofw** [comment]
**Update:**  So after a reboot, the bad behavior went away, but having messed around to try to reproduce it, I _think_ I can still make it happen:  If I hold down the Ctrl key on my keyboard while using the mouse, Windows Terminal seems to have the same weird glitchy behavior in the tab bar.  So it's possible that Windows (or my keyboard driver?) got confused and thought the Ctrl key was stuck down, and a reboot reset the key state.  I can't say why it is that I could still type normally, though, even if Windows was confused about that key's state.

So is the tab area's behavior somehow dependent on the state of the Ctrl key when the mouse button is clicked?

**Comment by zadjii-msft** [comment]
> If I hold down the Ctrl key on my keyboard while using the mouse, Windows Terminal seems to have the same weird glitchy behavior in the tab bar.

Weird. I can't seem to repro that at all. Any chance you're using any accessibility software, something like Magnifier or Narrator? Maybe you've got PowerToys installed, with FancyZones enabled? 



> So it's possible that Windows (or my keyboard driver?) got confused and thought the Ctrl key was stuck down, and a reboot reset the key state

I've definitely seen this consistently over the last 6 years of working here, so that's entirely possible. Especially seems to happen with the Mail and OneNote apps. Usually, when I find I'm in that state, just hitting the Ctrl key resets it ☺️

**Comment by BestDigital22** [comment]
I just started experiencing this too. I question whether its a bug or just new functionality that is being rolled out to different users at different times.

**Comment by zadjii-msft** [comment]
Oh this might be an interesting data point: Which OS version are you on? There seems to be a _recent_ regression in insiders builds, but this issue predates that (at least, to my knowledge)

**Comment by seanofw** [comment]
I still see this from time to time, and it's very weird, and slightly unpredictable.  Here's some updated info.

I can occasionally still trigger it by just unplugging my keyboard and plugging it back in:  Eventually, Terminal (or my keyboard driver, or Windows itself?) somehow seems to get confused about which keys are down, and I think it somehow concludes that one of the Ctrl or Shift keys is pressed even when neither is.  Tapping those keys repeatedly doesn't seem to fix it; whatever internal state gets screwed up stays that way, and only goes back to normal if I unplug the keyboard and plug it back in again.  I will _sometimes_ see behavior in other programs that suggests that Ctrl or Shift or something is stuck; but it's very inconsistent:  I can type `c` and `x` and `v` and they're lowercase and don't cause Copy/Cut/Paste to happen.  Typing Shift+C/Shift+X/Shift+V produces capital letters.  Typing Ctrl+C/Ctrl+X/Ctrl+V causes clipboard actions.  But occasionally something will still act as though Ctrl or Shift is stuck, even though most things work as expected.

I'm not quite sure where the bug truly is, but I'm leaning away from Terminal itself.  My current best guess is that either Windows or the keyboard driver are returning the wrong answer for Ctrl or Shift in calls like `GetKeyboardState()` but still including the _right_ answer in the `WM_KEY*` and `WM_MOUSE*` messages, which is why most programs respond correctly most of the time even if the state is screwy.

How it gets _into_ that state I have no idea, but that _seems_ to be what's happening:  It's at least a hypothesis that's consistent with the evidence.  I feel like I need to someday hack up a program to test whether there's a disagreement in the responses from the various different input APIs and messages in Windows and then run that program when everything starts acting weird, which might help answer this a little more definitively.

Also, I'm at present on Windows `10.0.19044.1586` and still seeing it from time to time, so it hasn't gone away in newer versions.

**Comment by zadjii-msft** [comment]
At this point, you might need to file feedback on the Feedback Hub, under 	
![image](https://user-images.githubusercontent.com/18356694/166479552-438d6dc0-995b-42a9-9afd-bf0d831ec0b4.png)

to get some traces to the input team. I'd agree with your assessment - I cannot imagine how plugging/unplugging the keyboard would affect Terminal's ability to move the window - we're certainly not doing anything to check the keyboard state ourselves. 

If you share the aka.ms link here, I can make sure it finds its way to the right folks, but I'm not sure what else we'd be able to do here 😕

**Comment by gr3yknigh1** [comment]
What the hell? I have the same problem. When are you guys going to start working for real? When will Microsoft do good windows again? . 

This is a BUG. You, Microsoft developers, doesn't need to know the "author feedback" to start working on bug fixes. Very sorry.

I'm switching from "Windows Terminal" to "Cmder".

**Comment by lhecker** [comment]
You do realize that we asked for a feedback hub report precisely because we wanted to send the issue to the "Microsoft developers" most likely responsible for this bug, right? Or are you saying that our small team is somehow responsible for all bugs at all of Microsoft?

If you can reproduce the issue, please file a feedback hub item as explained above. We'll then forward it to the right folks.

**Comment by xparq** [comment]
FTR, this just happened to me today (regularly updated Win10 Pro).

- But only for one Terminal window (with an MSVC CLI shell).
- The title bar does react to _certain_ messages: I can open new tabs with [+] etc.  
- I can also resize the window by dragging the edges (including top one).
- But e.g. no right-click context menu on the title bar...
- Right-click _inside_ the window seems fine, the other popup menu there does appear.
- I can move the window with the keyboard (the usual Alt + Space menu -> Move, then the arrows).

Never seen this before. Note: I _did_ also unplug and replug a keyboard beforehand, just like the OP said, but I'd be shocked if this would indeed be somehow related.

Weird, nonetheless.
