### ISSUE TITLE
Can't start app from VS 2022 when WT is set as the default terminal

### ISSUE THREAD

**Issue by sebastienros** [microsoft/terminal#11748]
An error box is display anytime I start a console application from VS 2022 after an app was closed (clicking on the cross) before it's finished. Unsetting WT as the default terminal fixes the issue.

Repro:

- Set WT as the default terminal in the settings
- Create a console application in VS with a `Console.ReadLine()`
- Start the application from VS (CTRL+F5), and close it to terminate it
- Start the application from VS, the following message is displayed

```
---------------------------
My.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000142). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

Version tested:  

WT 1.12.2931.0
VS 2022 17.1.0 Preview 1.0

Mitigations:
- After restarting VS the issue disappears.
- After setting Windows Console host as the default terminal application the issue disappears.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10974 for more discussion.

/dup #10974
