### ISSUE TITLE
Do not bundle Cascadia Code

### ISSUE THREAD

**Issue by SharakPL** [microsoft/terminal#11758]
# Description of the new feature/enhancement

I have a hard time managing Cascadia Code on Windows 10. I install all new fonts with [Scoop](https://scoop.sh/) eg. `scoop install Cascadia-Code` and I keep it up to date. I've installed v.2110.31 almost 2 weeks ago when it was released, but now I see I have only powerline (Code PL and Mono PL) versions updated. Somehow Code and Mono remained at v.2108. I thought it's maybe because I updated Terminal recently which is bundled with this older versions and doesn't include PL variants so I reinstalled whole package through Scoop but the effect is still the same - only PL are new. Looks like the Windows Terminal is blocking font update.

### Updated whole package (CC, CC PL, CM, CM PL):
![obraz](https://user-images.githubusercontent.com/5007456/141661986-847f1045-f027-4ed1-acd6-8c3267ea0bec.png)

### Terminal font doesn't udpate:
![obraz](https://user-images.githubusercontent.com/5007456/141661969-8d67af67-a641-4148-98e7-0e79a4e25e4c.png)

# Proposed technical implementation details (optional)

Let users handle font installation or at least make it installed in default way so it could be updated anytime by the admin and not only by Windows Terminal update.

**Comment by j4james** [comment]
I think this may be the same problem described in issue #2979.

**Comment by zadjii-msft** [comment]
Yea, this is basically /dup #2979. I believe we're actually going to do something about this _very_ soon, so I'm gonna go move that one up to 1.13. Thanks!
