### ISSUE TITLE
Lunch mode focus tabs panel disappeared 

### ISSUE THREAD

**Issue by sinfulcapacity** [microsoft/terminal#11754]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

Windows Feature Experience Pack 1000.22000.318.0

### Steps to reproduce

- Open terminal
- Go to settings
- Find Launch mode in Startup
- Choose Focus 
- Restart terminal

### Expected Behavior

Terminal with a tabs panel

### Actual Behavior

Terminal focus tabs panel disappeared

**Comment by DHowett** [comment]
Thanks for the report! Removing the tab view is the _purpose_ of focus mode. To get back to settings to disable it, press <kbd>Ctrl+,</kbd>

To open up the menu, press <kbd>Ctrl+Shift+Space</kbd>.

To temporarily turn focus mode off (or on!), press <kbd>Ctrl+Shift+P</kbd> or choose "Command Palette" from the menu and then search for "focus".
