### ISSUE TITLE
Problems in setting it as Default Terminal

### ISSUE THREAD

**Issue by Martexz** [microsoft/terminal#11755]
I'm using win10 21H1 Pro, but I cannnot set windows terminal as the default terminal.
teminal version: Windows Terminal Preview  1.12.2931.0

**Comment by j4james** [comment]
I'm afraid this is by design. That functionality is not supported on Windows 10. See #11656.

**Comment by DHowett** [comment]
Yep, right now default terminal support is limited to Windows 11. Thanks!
