### ISSUE TITLE
switch colorScheme at sunrise/sunset

### ISSUE THREAD

**Issue by ewhitesides** [microsoft/terminal#11757]
# Description of the new feature/enhancement

switch colorScheme at sunrise/sunset

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I think the first thing needed for this is the ability to switch the color scheme to match the operating system's light and dark modes, which is covered by issue #4066.

Once we have that working, there are utilities you can use to switch the light/dark mode automatically (e.g. [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)), or you could set something up yourself [using the Windows Task Scheduler](https://www.windowscentral.com/how-automatically-switch-dark-mode-night-time-windows-10).

**Comment by zadjii-msft** [comment]
Yea, I'll agree with calling this a /duplicate of #4066. Thanks!
