### ISSUE TITLE
How to uninstall windows terminal?

### ISSUE THREAD

**Issue by citravebriany** [microsoft/terminal#1176]
How can i uninstall this windows terminal?, my terminal is working very slow and i don't like it.

**Comment by Summon528** [comment]
Right click on the entry in Start menu, there should be an option to uninstall it.   
However, I think it would be better if you can file a performance issue here with more details.

**Comment by citravebriany** [comment]
> Right click on the entry in Start menu, there should be an option to uninstall it.
> However, I think it would be better if you can file a performance issue here with more details. 😄

I Also delete the terminal folder that i clone from this repo, isn't it right?
The performance is very slow compared to the regular linux shell. I need terminal that can be faster than any program installed in my pc, because i use vim to edit my code. Thanks for the response

**Comment by DHowett-MSFT** [comment]
You need to uninstall it from the Start menu. Then you can delete whatever folders you want.
