### ISSUE TITLE
Atlas engine does not fill the "gutters"

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#11773]
### Windows Terminal version

1.13

### Steps to reproduce

Run at 150% scale with a fully opaque background.

### Actual Behavior

![image](https://user-images.githubusercontent.com/189190/142285549-8e948e7d-725a-48ac-ab1a-6ed954943f81.png)

**Comment by lhecker** [comment]
I can't replicate this issue:
![image](https://user-images.githubusercontent.com/2256941/151204843-bd81a675-e137-41e1-bae3-dbf06020a8c7.png)

**Comment by DHowett** [comment]
Perhaps it is a fractional scaling issue! Try 150% or 175%.
________________________________

**Comment by lhecker** [comment]
The screenshot is at 150% and it doesn't happen for neither 125% nor 175%.
You know... I kinda suspect this might've been fixed with my `SMALL_RECT` PR, because that one removed `til::math::truncate`...

**Comment by DHowett** [comment]
Yeah, I definitely haven't seen this in a while!
