### ISSUE TITLE
Feature Request:  Friendly Names For Tabs

### ISSUE THREAD

**Issue by michelforget** [microsoft/terminal#1177]
It would be really nice if we could show the name of the shell in the tab title instead of the full path to it.  It would make the tab titles shorter, and allow for easier visual recognition of which tabs are what.  Ideally, if there is more than one tab with the same name it should append "-1", "-2", etc. to the tab name.

**Comment by Summon528** [comment]
Probably duplicate of #608

**Comment by DHowett-MSFT** [comment]
Yep, that’s a duplicate. Thanks!

**Comment by keserwan** [comment]
it is still not friendly name on my side.
Windows OS
Windows Terminal (Preview)
Version: 0.3.2171.0

**Comment by zadjii-msft** [comment]
@keserwan Try adding a `tabTitle` to your profile, with whatever friendly name you'd like.
