### ISSUE TITLE
Blocking ux.console.azure.com does not block Cloud Shell access via Windows Terminal

### ISSUE THREAD

**Issue by dsmithcloud** [microsoft/terminal#11775]
### Windows Terminal version

1.11.2921.0

### Windows build number

11.22000.346

### Steps to reproduce

Following the guidance from https://github.com/MicrosoftDocs/azure-docs/issues/55489
I've blocked access on my local machine to ux.console.azure.com by adding a hosts file record that points to 0.0.0.0
Connecting to Cloud Shell via a browser becomes blocked afterwards.
Connecting to Cloud Shell via Windows Terminal still works.

### Expected Behavior

I expected that Cloud Shell access would not work after adding the hosts file record.

How do we block access to Cloud Shell via Windows Terminal?

### Actual Behavior

Windows Terminal asks me to choose a stored login to cloud shell or directs me to microsoft.com/devicelogin and successfully connects to cloud shell afterwards.

**Comment by DHowett** [comment]
Ah, interesting. That guidance seems to disable access to the _browser UI_ for Azure Cloud Shell. Given that we (and other non-browser Azure Cloud Shell clients!) do not use the browser UX endpoint, that guidance is unfortunately incomplete.

**Comment by zadjii-msft** [comment]
I promoted this to https://github.com/MicrosoftDocs/azure-docs/issues/84061. That'd be the place to follow for updates. Thanks!

/dup https://github.com/MicrosoftDocs/azure-docs/issues/84061
