### ISSUE TITLE
I can't write into the terminal

### ISSUE THREAD

**Issue by fcmircea** [microsoft/terminal#11779]
Touch keyboard service is up and MSI Afterburner is not running.

I fire a wt window and I can't *type* input, but I can *paste* input.

LE: My bad, it needed a restart even though I had started the “touch keyboard” service manually.

**Comment by zadjii-msft** [comment]
* What version of the Terminal? 
* What version of the OS?
* What shell are you using (and what version of that)?
* Are you using `ssh`? (again, if so, which version?)
* Do you have PowerToys installed?
* Are you using any accessibility software, like Narrator, Magnifier, NVDA, JAWS?

**Comment by tajetaje** [comment]
> Touch keyboard service is up and MSI Afterburner is not running.
> 
> I fire a wt window and I can't _type_ input, but I can _paste_ input.
> 
> LE: My bad, it needed a restart even though I had started the “touch keyboard” service manually.

If you solved it then you might close the issue, unless you still need support.
