### ISSUE TITLE
Window Terminal unable to start in the specified directory when starting from command prompt with . (dot notation)

### ISSUE THREAD

**Issue by aungthanlwin** [microsoft/terminal#11778]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.1348

### Other Software

![image](https://user-images.githubusercontent.com/13598164/142297595-f4c10ba8-f1de-4cd0-a838-8efc5763a62f.png)

### Steps to reproduce

Start command prompt.
Type command "wt ."

### Expected Behavior

Window Terminal start in the current directory same as command prompt

### Actual Behavior

[error 0x80070005 when launching `.']

**Comment by DHowett** [comment]
You will want to use `wt -d .` The primary argument to wt is an _application_ to run. `-d` lets you specify the directory!
