### ISSUE TITLE
Windows terminal path is different if launched with wt.exe

### ISSUE THREAD

**Issue by tajetaje** [microsoft/terminal#11777]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.21390.0

### Other Software

adb --version
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as C:\source\android\sdk\platform-tools\adb.exe

### Steps to reproduce

1. Install Android Studio and add a virtual device
2. Add C:\source\android\sdk\platform-tools\ to path
3. Run 'adb' in windows terminal

### Expected Behavior

I expect windows terminal to be able to see and execute adb.exe like powershell and cmd can

### Actual Behavior

Instead I get an error that it is not recognized (this issue strangely does not extend to other programs that I can tell (see below)
![image](https://user-images.githubusercontent.com/29828269/142294754-ae2d9fb8-4904-424c-9baf-03eb7aa67117.png)

The issue also persits across opening new tabs in the wt-spawned process
![image](https://user-images.githubusercontent.com/29828269/142294815-d6c0338f-93be-421d-89aa-fde6f3ea6a6a.png)

**Comment by zadjii-msft** [comment]
Sounds like you opened the Terminal before you updated the PATH? If so then this is probably #1125

**Comment by tajetaje** [comment]
I have a sneaking suspicion this is related to #7204 as I have had issues with a long PATH in the past, but I think I solved that issue, and even if i were: the android sdk is not at the end of my path string

This is what running in wt.exe does to my path (and yes, my pc has been restarted many times since i updated the path):
![image](https://user-images.githubusercontent.com/29828269/142296629-e6c14c73-4e26-49b7-aaf0-d66f7993e097.png)

**Comment by elsaco** [comment]
@tajetaje where do you add the adb dir to the path, user or system? Any location should be fine. After starting a WT session type `$env:path` and you should see adb in the $PATH. Looking at your above diff your adb location is missing from the $PATH. The terminal does prepends `C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe` but is not removing any entries.

Adding adb location to system $PATH will be resolved faster since user $PATH is appended to system $PATH variable and your $PATH looks long. To see how many chars are in your $PATH measure it and count the chars:

`$env:path | measure-object -character`

however you're still a long way from the upper limit (is that 32,767 or more?)

**Comment by tajetaje** [comment]
> @tajetaje where do you add the adb dir to the path, user or system? Any location should be fine. After starting a WT session type `$env:path` and you should see adb in the $PATH. Looking at your above diff your adb location is missing from the $PATH. The terminal does prepends `C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe` but is not removing any entries.
> 
> Adding adb location to system $PATH will be resolved faster since user $PATH is appended to system $PATH variable and your $PATH looks long. To see how many chars are in your $PATH measure it and count the chars:
> 
> `$env:path | measure-object -character`
> 
> however you're still a long way from the upper limit (is that 32,767 or more?)

I want to be clear: THIS IS NOT AN ISSUE WITH MY PATH
See the above image for the actual difference in my path variable. In getting those values I ended ALL conhost sessions and ended all windows terminal processes and then launched windows terminal normally and via wt immediately after each other. My android sdk path is in the system path and works just fine everywhere except windows terminal when launched from wt.exe (vscode, windows terminal normally, pwsh.exe, etc.)

**Comment by tajetaje** [comment]
Pardon the side monitor, sharex did a weird thing:
https://user-images.githubusercontent.com/29828269/142345866-4c9f8f37-28d7-4ad6-b619-c4b128c87899.mp4

**Comment by thewh1teagle** [comment]
I'm facing this weird bug too.
I updated user variables to point to cygwin64 instead of cygwin32
cmd.exe window got it.
but windows terminal no
I tried to kill all windows terminal processes and reopen but I still got the same result
![image](https://user-images.githubusercontent.com/61390950/143724840-88bdd113-d8f9-485d-b647-8273ecfb1a3e.png)

**Comment by tajetaje** [comment]
> I'm facing this weird bug too.
> 
> I updated user variables to point to cygwin64 instead of cygwin32
> 
> cmd.exe window got it.
> 
> but windows terminal no
> 
> I tried to kill all windows terminal processes and reopen but I still got the same result
> 
> ![image](https://user-images.githubusercontent.com/61390950/143724840-88bdd113-d8f9-485d-b647-8273ecfb1a3e.png)
> 
> 

It seems almost like wt is remembering old path variables

**Comment by tajetaje** [comment]
I will note that I have recently clean installed windows 11, so everything in this issue is about all I can give (though if need be I can salvage configs and whatnot from my old windows 10 backup)

**Comment by lenraven** [comment]
I have same issue with fresh install of windows 11.

When I run the terminal with wt.exe, after I add something to the PATH, my changes are not in the environment variable.
But if I run the Windows terminal from the context menu of the Start icon, than my changes are visible.

Otherwise when I restarted the windows, then my changes are visible in wt.exe also.

**Comment by tajetaje** [comment]
> I have same issue with fresh install of windows 11.
> 
> 
> 
> When I run the terminal with wt.exe, after I add something to the PATH, my changes are not in the environment variable.
> 
> But if I run the Windows terminal from the context menu of the Start icon, than my changes are visible.
> 
> 
> 
> Otherwise when I restarted the windows, then my changes are visible in wt.exe also.

This seems more like #1125

**Comment by zadjii-msft** [comment]
To try and close the loop on this: This seems like a variation on many of the other env var issues we've been investigating this month. At face value, this seems unique from the others, so I'll leave it open. I'm tracking the rest in https://github.com/microsoft/terminal/issues/1125#issuecomment-1005171748. Hopefully the changes we're working on should fix this too. I'm not sure there's a good way of reproing this original issue though 😕

**Comment by mariozski** [comment]
I'm having the same issue with AWS SAM CLI. After installation, "sam" command is not accessible from Windows Terminal, but I can successfully run it from "Windows PowerShell" session.

**Comment by zadjii-msft** [comment]
Hey wild question - did you happen to install the Terminal from `scoop`, or are otherwise running the Terminal unpackaged? #12545 seems to describe a similar behavior, specifically for the `scoop` install, so I'm just trying to find a common thread.

**Comment by tajetaje** [comment]
> Hey wild question - did you happen to install the Terminal from `scoop`, or are otherwise running the Terminal unpackaged? #12545 seems to describe a similar behavior, specifically for the `scoop` install, so I'm just trying to find a common thread. 

No, iirc that install was either msstore or from GitHub's msix originally.

**Comment by zadjii-msft** [comment]
thought, not fleshed out: the "attach to current window" setting for `windowingBehavior` - that's gonna lose environment variables. Probably not what's at play here though.

**Comment by tajetaje** [comment]
In Windows 11 the only path difference I am now seeing is the addition of "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe" to path in wt.exe but not in Windows Terminal

**Comment by zadjii-msft** [comment]
Y'know, after rereading some of these, I'm gonna merge this with #7204. The prepending of `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal*` seems like a consistent signal here of _something_ messing with the path, and whoever's doing it is doing it the same way in all these. Thanks!

/dupe #7204
