### ISSUE TITLE
Why is OneNote such a horrible and buggy, frustrating awful piece of software?

### ISSUE THREAD

**Issue by vividfrog9892** [microsoft/terminal#11772]
### Steps to reproduce

Everywhere I look, across all platforms I try, OneNote is consistently awful and buggy and extremely frustrating.

People have been hating on OneNote since at least 5 years ago, and absolutely nothing has been done to solve these problems.

https://old.reddit.com/r/OneNote/search?q=Quick+Notes

OneNote and Microsoft are literally Hitler.

As a Software Developer, I literally hate microsoft because of all microsoft products, they are awful and broken. It is painful to be forced to depend on microsoft tools. 

### Actual Behavior

https://old.reddit.com/r/OneNote/search?q=Quick+Notes

**Comment by vividfrog9892** [comment]
Terminal is Strongly related to the quality of microsoft products, chief among microsoft products is Office, of which Onenote is a part of.

**Comment by skyline75489** [comment]
I don't quite follow. How is OneNote related to Windows terminal, again?
