### ISSUE TITLE
ExchangeOnlineMangement module authentication window opening under Windows PowerShell Terminal

### ISSUE THREAD

**Issue by JakeMoe** [microsoft/terminal#11776]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.0

### Other Software

Windows PowerShell - 5.1.22000.282
ExchangeOnlineManagement - 2.0.5

### Steps to reproduce

Open Windows PowerShell tab in Windows Terminal
Run commands:
```
Import-Module -Name ExchangeOnlineManagement
Connect-ExchangeOnline
```
Wait a while before you realise the authentication prompt opened under Terminal, then switch to it and move on with your life

### Expected Behavior

The authentication pop-up should, well, pop up.  It should open on top of Terminal, not under it.

### Actual Behavior

It behaves like a pop-under, and it's easy to miss that it's already opened but underneath.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2988 for more discussion.

/dup #2988

**Comment by JakeMoe** [comment]
Hi @zadjii-msft , sorry for the dupe, I did search for it but obviously my search-fu is not up to scratch.  I'll track that ticket.  Thanks!
