### ISSUE TITLE
Add "New Window" option to "Open a new tab" menu

### ISSUE THREAD

**Issue by AzureZeng** [microsoft/terminal#11782]
# Description of the new feature/enhancement

When "Attach to the most recently used window" or related setting is enabled, it is hard to find a way to open a new window for new Windows Terminal user.

Actually Windows Terminal supports opening a new window, just by opening Command Palette, then enter "New window" to find related command. However finding the "New window" command by such way is difficult if nobody tell new user about this feature.

![image](https://user-images.githubusercontent.com/19504193/142458625-82f41f70-683d-47e4-9c46-621c6d644044.png)

I found a good idea to make searching this command more easier, because I rely on it. Yes, just add this command to "Open a new tab"
 menu.

![image](https://user-images.githubusercontent.com/19504193/142458559-6a157da3-23b7-45ce-b08a-ad8b3fef4cdf.png)

# Proposed technical implementation details (optional)

None.

**Comment by zadjii-msft** [comment]
If you shift+click on those entries, they'll already bring up a new window with that profile 😉 

We're not likely to add too many more entries to that menu as-is. We're tracking adding the ability to customize that menu in #1571, and the ability to tear-out tabs into new windows in #1256. 

/dup #9395
