### ISSUE TITLE
Not possible to type dollar sign in settings

### ISSUE THREAD

**Issue by pgerell** [microsoft/terminal#11788]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19044.1379

### Steps to reproduce

Open settings tab.
Try to type a $ in the Starting Directory field.
E.g. `\\wsl$\Ubuntu-18.04\home\user`

This happens with Swedish keyboard where you type $ by pressing AltGr+4.
This used to work with previous versions.

### Expected Behavior

A $ should be inserted at the cursor position.

### Actual Behavior

The right-most tab becomes active.
If the Settings tab is the right-most tab, nothing happens.

**Comment by zadjii-msft** [comment]
Interesting. This is probably caused by us looking in the keybindings even in the SUI now. I think this is the roughly same thing as #10349, which has a workaround in https://github.com/microsoft/terminal/issues/10349#issuecomment-855963803. 

@lhecker double check me on that?
