### ISSUE TITLE
Windows Terminal blocks the Taskbar when auto-hide mode enabled

### ISSUE THREAD

**Issue by AmRo045** [microsoft/terminal#11789]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19042.0

### Steps to reproduce

- Enable Taskbar auto-hide mode on Windows
- Open Windows Terminal
- Maximize Windows Terminal window
- Move your mouse to the bottom of the screen to bring up the hidden Taskbar

### Expected Behavior

The Taskbar to become visible.

### Actual Behavior

The Taskbar stays hidden.

**Comment by AmRo045** [comment]
Maybe helpful: I had the same issue in WPF, and I solved it by removing one pixel from the window height.
https://github.com/SourceSara/WpfCustomWindow/blob/752fa1f81886867ec4967011c984ef59ebe10332/Source/CustomControls/CustomWindow.cs#L137

**Comment by alexandruchircu** [comment]
Why was this closed? I can confirm the same behaviour with Windows 11 and Terminal 1.11.3471.0 .

**Comment by AmRo045** [comment]
I saw this behavior and created this issue, but when I wanted to show that to my friend, I couldn't reproduce it. Then I closed the issue :)

**Comment by zadjii-msft** [comment]
See also: #4857

> Note to future code archeologists: This doesn't seem to work for fullscreen on the primary display. However, testing a bunch of other apps with fullscreen modes and an auto-hiding taskbar has shown that _none_ of them reveal the taskbar from fullscreen mode. This includes Edge, Firefox, Chrome, Sublime Text, Powerpoint - none seemed to support this.
> 
> This does however work fine for maximized

**Comment by alexandruchircu** [comment]
> 

In my case, it's when maximized (not fullscreen) that the taskbar doesn't reveal, and only with Terminal, all other programs behave as intended regarding taskbar auto-hide.

**Comment by nwillems94** [comment]
I also have this issue when windows terminal is maximized. Running Windows 11 (22000.652) with terminal version 1.12.10983.0
