### ISSUE TITLE
Option to remember starting directory from the last tab/session

### ISSUE THREAD

**Issue by working-name** [microsoft/terminal#11783]
# Description of the new feature/enhancement

Hello, I come from iTerm2 on macOS and several linux distros where the most useful part about starting a new tab or window or splitting the current view horizontally or vertically is to be able to be right back where you were in the previous session.

I don't know if this use case is all that unique given the ubiquitous availability of this behavior on other terminal emulators, so I think it would be a step forward.

https://user-images.githubusercontent.com/16505052/142466163-574d807d-f6ee-49c4-9b56-061cfb1516ec.mp4

**Comment by zadjii-msft** [comment]
This has been discussed numerous times across the repo. 
* #3158 
* #8166
* #766 
* There's the [`duplicateTab` action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#duplicate-tab)
* the [duplicatePane action](https://docs.microsoft.com/en-us/windows/terminal/panes#duplicating-a-pane)
* There's the duplicate tab and split pane menu items which will duplicate by default: 
![image](https://user-images.githubusercontent.com/18356694/142469359-47309c1b-e1d9-4d18-9f3b-74e50f93295a.png)


Generally, this is /dup #3158

**Comment by working-name** [comment]
> This has been discussed numerous times across the repo.
> 
> * [Open new terminal tab in same directory as existing tab (OSC 7?) #3158](https://github.com/microsoft/terminal/issues/3158)

No resolution here, other than what seems like a bunch of workarounds, among which using a different terminal emulator altogether :)

> * [Consider using OSC 9;9 to inform Windows Terminal about CWD #8166](https://github.com/microsoft/terminal/issues/8166)

Again, more workarounds, no solution.

> * [Enable Terminal to persist / restore instance settings #766](https://github.com/microsoft/terminal/issues/766)

Apparently available in beta releases but this is not a similar issue to what I'm asking at all.

> * There's the [`duplicateTab` action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#duplicate-tab)

This does not duplicate CWD as well, but does duplicate title and such. Running 1.11.2921.0 which is your latest official release.

> * the [duplicatePane action](https://docs.microsoft.com/en-us/windows/terminal/panes#duplicating-a-pane)

Settings JSON contains the code as described, however, when using the shortcut I get the same behavior as above: something is duplicated but CWD is not part of it.

> * There's the duplicate tab and split pane menu items which will duplicate by default:
>   ![image](https://user-images.githubusercontent.com/18356694/142469359-47309c1b-e1d9-4d18-9f3b-74e50f93295a.png)

This does the same thing as above - fails to duplicate CWD.

> 
> Generally, this is /dup #3158

**Comment by working-name** [comment]
Tested `1.12.2931.0`, same behavior - no CWD duplication through any of the aforementioned methods.

The "start where we left off" functionality also fails to maintain each tab's prior CWD, it just loads whatever is set as the default. Pretty useless for now.

**Comment by zadjii-msft** [comment]
Those threads go into quite a lot of detail - **you need to configure your shell to emit information to the Terminal about what the working directory is**. You can use the `OSC9;9` sequence to emit a Windows path, and then all the duplicate actions will be able to use that path. 

The Terminal can't just magically determine the path of the commandline application for a variety of reasons that are detailed in #3158. Most significantly - PowerShell doesn't even change its own CWD, so trying to get the CWD from the attached application automagically will _not_ work more often than it _does_ 😅.

**Comment by working-name** [comment]
Oh I see, sorry, I come from macOS and linux which seems to "magically" have that part figured out without me adding stuff to .bashrc. My bad.

So I tried [this thing](https://github.com/microsoft/terminal/issues/3158#issuecomment-907201734) and that won't do. If I simply try to export the variable in bash and change -m to -u to get the linux path which is what I'm trying to preserve, not SMB path to the directory shared from the VM controlled by wsl2... ( 🙄 ) - it just exits windows terminal. All of it.🤣

Also no idea what "ctrl +d" is supposed to do by default if not duplicate tab. I did not override the shortcut and it doesn't appear in the settings JSON but it closes the current tab when pressed.

So in your [comment from 2020 ](https://github.com/microsoft/terminal/issues/3158#issuecomment-727026693) you expressed dissatisfaction with people who are not willing to read through hundreds of comments across several threads - it's just A LOT to go through, and if you have no clue what OSC is, that's not helpful 😞. I skimmed through the links you posted above, and stopped where there was some code block. But that's about it, the rest of the conversation about OSC and different implementations in others OSes are well above my head.

You also mentioned that the team had then found a solution that you were happy with. Would you happen to know if that's the same as the stuff above? Is it posted anywhere?

**Comment by zadjii-msft** [comment]
Sorry, we've been meaning to write a tutorial on that for a while now, just never had the time. I wrote up a guide over at https://github.com/MicrosoftDocs/terminal/pull/449/files. That might help explain what's all needed to get this to work.

**Comment by kudorgyozo** [comment]
This application is pretty much useless without this feature. I will still need to use ConEmu it seems.

**Comment by DHowett** [comment]
You are welcome to use whatever terminal emulator you would like on Windows.
