### ISSUE TITLE
[feature request] Be able to move/disconnect/attach tabs independently i.e Chrome-style

### ISSUE THREAD

**Issue by cloudrootab** [microsoft/terminal#11791]
# Description of the new feature/enhancement
Sometimes I'll acctually use the tabs function. And I'll find it handy. However, not being able to drag-n-drop one tab into its own window. Or into and attach it to another one. Is kind of annoying. Being used to how you can move, disconnect, attach tabs in Chrome without any effort. This functionality would be so great when reorganizing SSH-sessions as an example.

When you've expanded the number of tabs into a few too many, And you'd like to see a couple of them side-by-side. Then the current way is to create a new one. But then you'd loose the progress/history you've built up in the current tab. There are several use cases, where being able to use tabs independently of their spawning parent window. Would be beneficial. 

# Proposed technical implementation details (optional)

Being able to use tabs in more of a Chrome-manner. In terms of how they're semi-independent of the parent window.
Where I can drag on tab out from parent window. Into either its own new window, or into another already existing one.

**Comment by j4james** [comment]
This sounds like the tab tearoff feature described in #1256.

**Comment by cloudrootab** [comment]
> This sounds like the tab tearoff feature described in #1256.

Indeed it does. Merge/tearoff wasn't search terms that I used, when trying to see if there was anything already open. So I'm guessing that this would be considered a duplicate then. :)

Thanks!

**Comment by zadjii-msft** [comment]
/dup #1256

thanks!
