### ISSUE TITLE
Feature Request：Consider Supporting quick start shortcut key

### ISSUE THREAD

**Issue by cjp715711877** [microsoft/terminal#1179]
like cmder or other terminal,can set a shortcut key,this shortcut key can hide or show terminal window.
and if enable this setting ,the terminal do not show in taskbar.
: )

**Comment by DHowett-MSFT** [comment]
Thanks for suggesting a feature! This is a duplicate of #653. Please make sure you’re searching for existing issues when you submit a new one!
