### ISSUE TITLE
Bad display of bold mathcar symbols.

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/terminal#11792]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22504.0

### Other Software

vim 8.2 inside wsl2/ssh.
vimtex plugin of vim.

### Steps to reproduce

1. Clone https://github.com/lervag/vimtex into `~/.vim/plugged/vimtex`.
2. `vim -u minimal.vim minimal.tex`.
4. Move cursor to see conceal effect.

minimal.vim:
```
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
let g:tex_conceal = 'abdmg'
set conceallevel=2
filetype plugin indent on
syntax enable
```

minimal.tex:
```
\documentclass{minimal}
\begin{document}
We prove \(V\mathcal{T}_w\) is not.
We prove \(V\mathcal{T}_w\) is not.
\end{document}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/998898/142728502-164cc0d4-28c7-4b34-83da-5ef0eb3043cc.png)

I don't know is this actually a bug of terminal, or should you solve this, but as I tested in https://github.com/lervag/vimtex/issues/2254, the bug only occur in windows terminal through ssh or in wsl2, and will not occur when using native vim or using X server. So I decided to post this issue here.

### Actual Behavior

![image](https://user-images.githubusercontent.com/17513581/142723869-b834a39a-3051-4f7b-ad23-f51c1d717b1b.png)

**Comment by PhyX-Meow** [comment]
Found reason of this: Terminal has bug displaying char `𝓣` -- bold mathcal characters, and possibly the whole family. Just paste the char into terminal you'll see the bug effect. One can get a list of such symbols at https://www.wikiwand.com/en/Mathematical_Alphanumeric_Symbols

**Comment by PhyX-Meow** [comment]
I use font Fira Code NF, bug same issue will occur also in Consolas, JuliaMono, Cascadia Code, etc.

**Comment by zadjii-msft** [comment]
I'm sure this is some subset of #8000, but I don't know exactly which...

**Comment by zadjii-msft** [comment]
Probably the #11756 bit so I'm just gonna call this a dupe. Thanks!

/dup #8000
