### ISSUE TITLE
Windows Terminal breaks remapped key by windows powertoys

### ISSUE THREAD

**Issue by sajiddotm** [microsoft/terminal#11798]
### Windows Terminal version

1.11.2921.0

### Windows build number

22000.318

### Other Software

Powertoys v0.49.1

### Steps to reproduce

I have remapped `capslock` to `esc` and vice versa.
By simply opening `Windows terminal` the remapped keys stopped working and start showing their actual behavior.

### Expected Behavior

Remapped keys should work.
`CapsLock` as `esc` and vice versa

### Actual Behavior

Remapped mapped doesn't work, instead their actual behavior is shown.

**Comment by sajiddotm** [comment]
Installing and changing the font to `MesloLGM Nerd Font`, corrected the issue.

Using any other font didn't work, so for now the issue is solved, so I'm closing it.

**Comment by sajiddotm** [comment]
I don't know what's happening, but sometimes the remapped keys start working, and other time don't.

**Comment by zadjii-msft** [comment]
That's weird. I don't think the Terminal should be messing with that at all. 

When you say:
> By simply opening `Windows terminal` the remapped keys stopped working and start showing their actual behavior.


Do you mean the key stops being remapped for _the Terminal_, or for _all applications_?


@crutkas any ideas what's going on here?

**Comment by sajiddotm** [comment]
> 
> Do you mean the key stops being remapped for _the Terminal_, or for _all applications_?
> 

I meant, as long as the focus is on the terminal window, it doesn't work, when I change the focus to something else or open another program, it starts working

**Comment by sajiddotm** [comment]
>
>When I said, sometimes remapped keys starts >working and sometimes don't.
>

 I also meant inside WT, as everywhere else remapping totally works fine.

**Comment by crutkas** [comment]
is terminal run as admin and Powertoys isn't?

**Comment by sajiddotm** [comment]
> is terminal run as admin and Powertoys isn't?

You're right, found the exact reason, it only happens when `WT` is running as an admin but `PowerToys` isn't.

`Running PowerToys always in an admin mode solved the problem.`

So, closing the issue. Thanks a lot @crutkas.

**Comment by crutkas** [comment]
While we can detect this, it is hard.  FancyZones is able to since you interact with the window.  Keyboard manager is a bit harder to catch this.
