### ISSUE TITLE
Strange hint when using Simplified Chinese (American keyboard) input method

### ISSUE THREAD

**Issue by DevDengChao** [microsoft/terminal#11801]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.1348

### Other Software

I'm using [搜狗拼音输入法 Sogou Pinyin](https://pinyin.sogou.com/) ver 10.1.0.4428 , 
![image](https://user-images.githubusercontent.com/16363180/142867584-a6832557-befa-4bcc-9836-77626e9d99d9.png)
 along with Simplified Chinese (American keyboard) (Added using Sogou Pinyin)
![image](https://user-images.githubusercontent.com/16363180/142867354-2ade237c-04d3-4d29-b454-8203e4cfab1d.png)
 and English (American keyboard) 
![image](https://user-images.githubusercontent.com/16363180/142867540-8bb5010f-64ba-4fca-9f27-d7b9e8631b8e.png)

### Steps to reproduce

![reproduce](https://user-images.githubusercontent.com/16363180/142868699-a3b38d68-26fc-44c4-8fa1-991b85cbd957.gif)

When I try to input with Chinese Simplified (American keyboard), there will be a hint before actually input into the terminal, I need to  press enter twice to input into the terminal (like inputing with Sogou Pinyin Chinese mode).

![reproduce](https://user-images.githubusercontent.com/16363180/142875211-841cfc25-ea28-48cd-9d38-21872170093e.gif)
While switch to other terminals like PowerShell, there will not be a hint.

### Expected Behavior

When using Chinese (American keyboard), behave like PowerShell.

### Actual Behavior

There is a hint.

**Comment by zadjii-msft** [comment]
@skyline75489 This isn't the same as #1304, is it?

**Comment by DevDengChao** [comment]
> @skyline75489 This isn't the same as #1304, is it?

Yes, they are saying the same thing.

Sorry for not found an existing issue.

**Comment by zadjii-msft** [comment]
No worries, that's a tricky one to find. I only found it because I was confident that I had seen the sogou pinyin icon somewhere else on the repo before 😅 

/dup #1304
