### ISSUE TITLE
WSL profile just after build have a problem.

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1181]
![image](https://user-images.githubusercontent.com/29011440/59155310-72bfbb80-8ac1-11e9-95ca-77bb001f4917.png)

so I saw the settings (profiles.json), it looked crazy.

```
        {
            "acrylicOpacity" : 0.5,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "wsl.exe -d Ubuntu(\uae30\ubcf8\uac12)\r\r",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{6408c1b2-1145-55cb-b519-64a858cb4495}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
            "name" : "Ubuntu(\uae30\ubcf8\uac12)\r\r",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : false
        }
```

So that, I have tried to open the WSL(ubuntu) profile with no changes with profiles, it closes right after open it. I couldn't even see the command line.

I have decoded \uae30\ubcf8\uac12 to UTF-8, 기본값 as Korean, which it is **Default** for English. (I am using windows as Korean, KO-KR)
Seems it runs (Default)\r\r at commandline so wsl couldn't run. BTW name should not have \r\r too.

**Comment by DHowett-MSFT** [comment]
I’m going to merge this with #1168, with a note about the language. @benhillis I am moderately sad about the text parsing requirement and how that leads us astray in light of system locale changes ☹️

**Comment by benhillis** [comment]
Agreed. Recently I added a "quiet list" option which only prints the distro names and no localized strings or headers.

**Comment by Biswa96** [comment]
But that doesn't show in `wsl.exe --help` command. Also there is a `--verbose` oprion.

**Comment by benhillis** [comment]
@biswa96 - quiet and verbose should both be there. Could you share help output, something might have gotten left on the cutting room floor.

**Comment by Biswa96** [comment]
I think we should discuss this in a new issue. What you think? I thought it may be in upcoming releases.
