### ISSUE TITLE
Cannot use ssh after updating windows

### ISSUE THREAD

**Issue by zhangnix2** [microsoft/terminal#11817]
### Windows Terminal version

1.11.2921.0

### Windows build number

19043.985

### Steps to reproduce

When I upload files using `scp`，like 
```
 scp .\xxx xxx@xxx.xxx:/usr/local/xxx
```

### Actual Behavior

I got the following error
```
SASendCB - ERROR: broken assumption, io:000001AE85D2F8A0, sent:71680, remaining:0
```

**Comment by zadjii-msft** [comment]
This doesn't sound like a Terminal-specific issue, you should probably file this with wherever your `ssh` is from. If it's the one that comes with Windows, then that would be over at https://github.com/PowerShell/Win32-OpenSSH/issues
