### ISSUE TITLE
clicking Launch after install complete " File System Error (12002) "

### ISSUE THREAD

**Issue by AkooRedline** [microsoft/terminal#11813]
### Windows Terminal version

Microsoft.WindowsTerminalPreview_1.12.2931.0_8wekyb3d8bbwe.msixbundle

### Windows build number

10.0.19043.1348

### Steps to reproduce

1-modify visuale studio community 2022 added .NET desktop development
2- restart VS update ML.NET Model Builder 2022
3- install Power Shell 7.2 via windows power shell using Winget " winget install --id Microsoft.Powershell --source winget "
4- download the windows Terminal Preview from assets by clicking on it.
5- after download right click the file select install, when finnished you get Launch i clicked it and nothing happend.
closed the installation window went back to browse internet and after some time the error window popped up.
so far no pc reboot yet...i rebooted pc at this stage and tried to launch windows Terminal i see it is installed but it refuses to RUN or bugged no clue.

### Expected Behavior

after rebooting pc i expected that error be gone but no.

### Actual Behavior

![Screenshot 2021-11-23 205833](https://user-images.githubusercontent.com/94634853/143088939-87a253fa-93bd-4b5b-93c8-2344e684aa53.jpg)

i opend cmd and typed wt hit enter 
![Screenshot 2021-11-23 210957](https://user-images.githubusercontent.com/94634853/143089111-2cbfde9c-8758-472a-a4e7-5c2bcb30df92.jpg)

while trying to post this issue i stumpled upon wierd behavior, first my network activity as i noticed during installation that windows terminal require access to my bandwidth connection
![Screenshot 2021-11-23 213451](https://user-images.githubusercontent.com/94634853/143089568-377fd830-b18f-411b-afc4-1444550cce5b.jpg)
.

second wierd behavior is when i browse my HDD folders when i open File explorer clicking on a Drive or A folder the mouse pointer turns to undless blue circle loop cant click anywhere in file explorer window  i lose control over it cant even move the window a round.

while everything else in windows normal i presume!!
someone posted last year same error but hence he didnt add anymore input about it you couldnt do much about it which is understandable..IF he only did i may not have been here posting it a year later, Thats why i will hang on to the steps i did so far waiting if you have any questions or steps i do on my end so we resolve this issue for the sake of everyone else for now and FUTURE.

**Comment by AkooRedline** [comment]
zadjii-msft what feedback you want ?

**Comment by zadjii-msft** [comment]
`12002` is `ERROR_INTERNET_TIMEOUT`. Is your machine connected to the internet? I'm guessing that the store is trying to validate the license for the Terminal package, and failing to do so, as described in #6010. 

Can you install the Terminal from the Store directly? (not using the `msixbundle`)?

Can you run the Terminal unpackaged, following the steps in [this comment](https://github.com/microsoft/terminal/issues/6010#issuecomment-632381385)?

#11176, #7351 are related.

**Comment by zadjii-msft** [comment]
(that was weird, I swear I posted that, glad the tab was still available in recently closed tabs 😅)

**Comment by AkooRedline** [comment]
i cant install it via the web store nor anything else it opens store i click on get and install but i keep getting erros tickets .thats why used the winget  when i used it it asked for yes or no to store terms of transaction typed Y hit enter and installed power shell 7.2..and thats was the first time i manage to install anything from store.maybe it helps you understand .but your reply helped me understand what is going on " my issue is with the store as it seems " 
alsoo no clue if it is related to store or windows terminal preview " but i manage to get access back to my file explorer once i disable the network adaptor " hope this helps too.
if thats the case you want me to uninstall windows terminal preview as it wont be of any use to me as long the STORE is controlling it ?i am here willing to help with what ever i can so we walk this issue to the limits for extra info sake . will be reading your links and try do what you asked me to do and get back to you with results. 
Thank you for the speedy reply    On Tuesday, November 23, 2021, 11:27:48 PM GMT+3, Mike Griese ***@***.***> wrote:  
 
 


(that was weird, I swear I posted that, glad the tab was still available in recently closed tabs 😅 )

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AkooRedline** [comment]
![Screenshot 2021-11-24 012138](https://user-images.githubusercontent.com/94634853/143138793-f9bd6cb0-f23d-4321-a3e4-25f38815e154.jpg)

the way i installed windows terminal preview is valid as Store recognize it which adds more confusing STORE behaviour. really MR store whats your problem ?!?!?!?!

**Comment by AkooRedline** [comment]
2 diffrent screenshots  is Terminal installed or ready for install ???  Clicking Launch from inside microsoft store same result nothing happens and after some time the same error msg appears.
![Screenshot 2021-11-24 014311](https://user-images.githubusercontent.com/94634853/143141229-25de9bee-9504-41fe-9ff9-5acc949fe95e.jpg)
![Screenshot 2021-11-24 014406](https://user-images.githubusercontent.com/94634853/143141246-66179e92-12f3-4a97-b8b6-51f68b093bee.jpg)

**Comment by zadjii-msft** [comment]
"Windows Terminal" and "Windows Terminal Preview" are two separate apps in the store. They're each slightly different versions of the Terminal. Everything in here makes me think this is #6010. You hadn't connected to the internet yet, so the OS couldn't validate the signature of the msix when you installed it. Now that you have connected to the internet, the Store can complete the lookup, and knows that the certificate is good, and will let you launch it. The `msixbundle` you get from the GitHub releases page is the same thing you install from the Store - same signing, same ID, everything, but the OS still needs to make sure it's legit (since it's signed with a Microsoft cert).

**Comment by AkooRedline** [comment]
Thats the confusing part... i understand all what you said but all i did was while direct connection to internet .
the store is connecting to internet EXCEPT this " completing the lookup " which is not happening .
i have the most stupid ISP, i tried vpn and clicked Launch from microsoft store AND IT LAUNCHED.
why a direct connection  to microsoft store be considerd PORN policy by my ISP that needs to be partially blocked either block it entirly so i can know or whitelist it. imagin the turn of events as all this trouble coz of ISP Throttling.
Thank you Mike been alot of help i dont imagin i would think of using vpn for such thing which really un related issue and should be a problem cause not a problem solver, IF you warent involving with me in this conversation MANY THANKS.
