### ISSUE TITLE
App does not change appearance when window is inactive

### ISSUE THREAD

**Issue by zonidjan** [microsoft/terminal#11818]
### Windows Terminal version

1.11.2921.0

### Windows build number

19042.1348

### Steps to reproduce

- Open Windows Terminal
- Switch to another active window

### Expected Behavior

- Windows Terminal window decorations and/or cursor indicate that the window is inactive

### Actual Behavior

- Windows Terminal completely ignores the established behavior of LITERALLY EVERY GUI OS EVER, including YOUR OWN OS, to make sure you can't tell whether or not the window is active.

**Comment by zonidjan** [comment]
Window active:
![image](https://user-images.githubusercontent.com/5210004/143232109-d325c780-40b6-4f86-9d27-f03f5d79bb48.png)


Window inactive:
![image](https://user-images.githubusercontent.com/5210004/143232155-133c5f11-e6f2-4c23-99f4-1c9a16beb959.png)

Can you see a difference? I sure can't. How anti-accessible can you possible be?

**Comment by zonidjan** [comment]
Window active:
![image](https://user-images.githubusercontent.com/5210004/143232299-56c75999-55d3-4fc2-8605-439b996195d2.png)

Window inactive:
![image](https://user-images.githubusercontent.com/5210004/143232416-84326171-289b-4e56-a5fe-d578c419b406.png)

How could you possibly have thought that this was a good idea or ready for release when it doesn't have quite literally the single most basic accessibility feature in existence?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4862 for more discussion.

/dup #4862

**Comment by zonidjan** [comment]
Not a dupe. That issue is regarding customizability while this issue is
regarding basic usability which is literally provided for you by your own
OS but you choose not to use.

Being able to distinguish active and inactive windows is just about the one
thing that Microsoft has never screwed up with all your UI changes but you
managed it, so congratulations.

**Comment by zadjii-msft** [comment]
It's a long weekend so I'll have a longer reply Monday, but you might want [`"showTabsInTitlebar": false`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/appearance#hide-the-title-bar), that'll bring bag the standard titlebar, and that'll still change appearance based on window focus. Or take a look at [unfocusedAppearance](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#unfocused-appearance-settings).
