### ISSUE TITLE
an option to toggle the quick edit mode

### ISSUE THREAD

**Issue by zli94** [microsoft/terminal#11815]
# Description of the new feature/enhancement
In PowerShell, there is an option to enable/disable quick edit mode, however, in Windows Terminal, there is no way to disable quick edit mode. I would like an option in the setting to toggle quick edit mode.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Quick edit is a collection of many features. Which ones do you find annoying, and why?

For example: we made a conscious decision to make selection always available in Terminal, but to never pause an application's output. This is in line with the behavior of all other terminal emulators.

**Comment by j4james** [comment]
Changing the behavior of the right-click operation should be covered by #1553. See also #10962.

**Comment by zli94** [comment]
> Changing the behavior of the right-click operation should be covered by #1553. See also #10962.

OK, that didn't show up on my previous search... thank you! I'll close this myself.

**Comment by wbt** [comment]
> Quick edit is a collection of many features. Which ones do you find annoying, and why?
> 
> For example: we made a conscious decision to make selection always available in Terminal, but to never pause an application's output. This is in line with the behavior of all other terminal emulators.

Having that as an option would still be useful...I'm still using PowerShell outside Terminal for that convenience.
