### ISSUE TITLE
Terminal Core: Whenever we scroll the buffer, we RepaintAll

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1182]
In `Terminal::_WriteBuffer`, when we scroll the buffer, we tell the renderer to `TriggerRedrawAll`. This isn't necessary, we should probably just be telling the renderer to scroll the lines on screen. 

The RedrawAll call was just a kludge while we were getting the Terminal stood up. Now that everything's working a bit better, we should make sure that RedrawAll is only called when absolutely necessary.

**Comment by DHowett-MSFT** [comment]
Related to #778.

**Comment by miniksa** [comment]
This was resolved in #5185
