### ISSUE TITLE
Tmux split windows but isn't aware of them

### ISSUE THREAD

**Issue by tomaszstachera** [microsoft/terminal#11825]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19044.1348

### Other Software

WSL2 Ubuntu 20.04 + tmux 3.0a
WSL2 Debian + tmux 3.0a

### Steps to reproduce

Open tmux and split window using any way - there is only one window instead of multiple windows.
The same behavior is no matter how you enter tmux (Windows Terminal, Powershell, CMD, Hyper).

![image](https://user-images.githubusercontent.com/61825692/143458700-af7330d6-8bea-4651-8d07-723e1b9e351e.png)

### Expected Behavior

There should be two tmux windows.

### Actual Behavior

There is only one window.

**Comment by elsaco** [comment]
@tomaszstachera you split a tmux window into multiple panes, just like you did above one window with 3 panes. To create a new window use `ctrl+b c`

**Comment by tomaszstachera** [comment]
omg what a noob :)
thanks a lot @elsaco
