### ISSUE TITLE
Cannot open WT while exec wt.exec

### ISSUE THREAD

**Issue by Force1ess** [microsoft/terminal#11827]
### Windows build number

10.0.22000.0

### Other Software

Basically nothing.
Win11 21H2 22000.348

### Steps to reproduce

I want to set a shortcut key for WT
But it went run when I open wt.exe or open 'wt' in windows run ( Win + R )

### Expected Behavior

regularly open

### Actual Behavior

After a loading animation, nothing happend
And I tried many old versions, some of them report "cannot open , error code is 0x0000000022C"

**Comment by zadjii-msft** [comment]
Can you share the entire error message, as a screenshot perhaps? `0x0000000022C` looks like it's only a SQL error, which wouldn't make any sense. I'm guessing the error you're actually seeing is `0xc0000022`, which has a decent amount of existing discussion on this repo.

Does this happen the same for both the "stable" and "preview" builds of the Terminal?

How did you install the Terminal? From github releases, from winget? scoop? From the Store?

**Comment by Force1ess** [comment]
Thank you @zadjii-msft 
I hope I can, but I can't give the entire message.
After several clicks, it doesn't report any error code and just shows me a loading state, and nothing happened at all.

I installed and tried both 'stable' and 'preview' versions, from MicrosoftStore and releases.

I can only remember it was ended with '22'

Your conjecture might be right. I'll concern about this error code.

**Comment by Force1ess** [comment]
@zadjii-msft 
I checked related question  #7081
I reset the folder's permission and owners, it was fixed.
