### ISSUE TITLE
Terminal not reading updated environment variables

### ISSUE THREAD

**Issue by AaronLayton** [microsoft/terminal#11829]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.348

### Other Software

Powershell 7.2.0
NodeJS 16.13.0

### Steps to reproduce

https://user-images.githubusercontent.com/694964/143573699-23c42e1e-20c0-416a-af61-5129e092ecda.mp4

### Expected Behavior

After installing NodeJS and opening a new Terminal instance, all the env variables should be updated.

The only way I managed to get this working if a restart of windows

### Actual Behavior

No updates are being pulled through. It's like WT is keeping the processes running and not updating when I create a new instance.

**Comment by AaronLayton** [comment]
Looks like when I quite Terminal it still leaves child processes running. If I manually quit these processes and reopen then I get refreshed ENV 

![2021-11-26_11h45_19](https://user-images.githubusercontent.com/694964/143576225-f81c13a7-5ec1-459c-a55b-2a698c8fc9b0.png)

**Comment by rkeithhill** [comment]
Related to (or dupe of) #1125

**Comment by AaronLayton** [comment]
Perfect @rkeithhill looks to be the issue!!
