### ISSUE TITLE
Windows Terminal scroll back isn't working in Windows 10

### ISSUE THREAD

**Issue by jerryasher** [microsoft/terminal#11826]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19044.1348

### Steps to reproduce

1. Open a new windows terminal with a shell (powershell, cmd.exe, ubuntu, yori)
2. fill the terminal window with many more lines than the window can display, (`dir` or `ls` of a very large directory)
3. using the mouse wheel, scroll back (up), or ctrl-shift-home or ctrl-shift-up or ctrl-shift-pgup

### Expected Behavior

The terminal should scroll through the earlier lines, display them, and keeping them displayed until there is "typing" at which point the scroll should snap back to the newest command prompt awaiting input

### Actual Behavior

I have Windows Terminal running on both Windows 10 and Windows 11, with identical `settings.json` (modulo any changes I've made this evening as I try to pinpoint this issue)  The behavior I am seeing only occurs on Windows 10, Windows 11 behaves as expected.

Testing with any of the following shells

+ Powershell Core
+ CMD.exe
+ Yori
+ Ubuntu

When I
+ fill the terminal window with many more lines than would be visible, (`dir` or `ls` of a very large directory)
+ use the mouse wheel to scroll back (up) through the earlier lines of output

I can see the window scrolling its contents, but as soon as soon as I stop scrolling, the window snaps back to the bottom, the newest lines of output, the line with the newest command prompt.

This is with

+ scroll to input white typing on
+ scroll bars visible or hidden
+ seemingly regardless of history size

This seems similar to #11771

**Comment by jerryasher** [comment]
My settings are here: [settings.json](https://github.com/microsoft/terminal/files/7606904/settings.json.txt)

**Comment by zadjii-msft** [comment]
> I can see the window scrolling its contents, but as soon as soon as I stop scrolling, the window snaps back to the bottom, the newest lines of output, the line with the newest command prompt.

Curious. Sounds like some sort of other dead key is coming through and causing us to snap back down. Throwing `"snapOnInput": false` in the defaults _should_ fix that, but you've already got that set for the Yori profile...

Can you try reproing this with the [debug tap](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap) to get a trace of all the input and output. Once the bug starts occurring, send us a screenshot and we might be able to figure out what the Terminal thinks it's getting here.
