### ISSUE TITLE
WSL startingDirectory Problem

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1183]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18912.1001]
Windows Terminal version (if applicable): commit 2da5b0b
```

# Steps to reproduce

Build a terminal, open WSL profile.
1. If setting(profiles.json) has startingDirectory, erase it.
**At commit 2da5b0b, there is no startingDirectory for WSL**

2. Set "startingDirectory" : "%USERPROFILE%"

# Expected behavior

Both WSL starts at home directory as user. (/home/username/)

# Actual behavior

1. if there is no startingDirectory, WSL starts at **/mnt/c/WINDOWS/System32**
2. if startingDirectory is %USERPROFILE%, WSL starts at **/mnt/c/Users/Windows-Username**

**Comment by Summon528** [comment]
Duplicate of #592. At the meantime, set `startingDirectory` to `//wsl$/Ubuntu/home/username`

**Comment by SJang1** [comment]
found that starting with `"commandline" : "wsl.exe"` make this problem, `"commandline" : "ubuntu"` does fine.
