### ISSUE TITLE
unexpected behavior with `commandline` parameter for new profile

### ISSUE THREAD

**Issue by awa5114** [microsoft/terminal#11833]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.0

### Steps to reproduce

 - Create new profile as follows:
 ```
           {
                "commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command '& echo hello'",
                "guid": "{75549856-2f4b-4e71-842a-48288c8f7250}",
                "hidden": false,
                "name": "Anaconda powershell prompt",
                "font": {
                  "size": 10
                }
            }
```
 - Open new tab with this profile

### Expected Behavior

I was expecting for the string `hello` to appear before the prompt starts as specified in the `commandline` parameter

### Actual Behavior

Instead, I get the string `& echo hello`

**Comment by zadjii-msft** [comment]
I think the ampersand is wrong - removing that, seems to work the way you'd expect.

Alternatively:
```
"powershell.exe -ExecutionPolicy ByPass -NoExit -Command &'Write-Output' 'hello'"
```

which will escape `Write-Output` as the command name, and `hello` as the arg(s)
