### ISSUE TITLE
Font resize lost after re-focusing the terminal window 

### ISSUE THREAD

**Issue by globalistas** [microsoft/terminal#11837]
### Windows Terminal version

1.11.2921.0

### Steps to reproduce

Ctrl+mouse scroll up or down can resize the fonts in the terminal window.

### Expected Behavior

In previous versions, the fonts stayed resized when the focus was returned to the terminal window.

### Actual Behavior

When the focus is returned to the terminal window after some time has passed, the font size reverts to default. Doesn't happen EVERY time, which makes this undesired change all the more weird. Possibly there's now a condition that I haven't been able to spot when this actually happens.

**Comment by zadjii-msft** [comment]
Are you using any sort of IME? Or do you have an `unfocusedAppearance` set? 

I suspect that this is related to #11522

**Comment by globalistas** [comment]
> Are you using any sort of IME? Or do you have an `unfocusedAppearance` set?

No.

> I suspect that this is related to #11522

Indeed it is, thanks! I realized this only happens after I switch the keyboard language (Alt+Shift).

**Comment by globalistas** [comment]
@zadjii-msft I've now installed this version and it doesn't have this issue so I'll stick with that until this bug is resolved.

https://github.com/microsoft/terminal/releases/tag/v1.9.1942.0

**Comment by zadjii-msft** [comment]
Okay super, thanks for confirming! /dup #11522
