### ISSUE TITLE
Open WT in selected directory by default (e.g. User Homd directory)

### ISSUE THREAD

**Issue by Zingam** [microsoft/terminal#11834]
If WT is opened from a shortcut I would prefer if the default directory is set to user's desktop directory or user's home directory and in any other case to the process directory, like when opening it via right click on a folder or by typing WT in Explorer.
Currently with this setting (Use process directory) WT opens by default: C:/Windows/System32 which is probably the last place I need it to open. So I think in this case it would be much more useful if by default WT opens C:/Users/<User's home> or some other preset location.

Currently I don't see how I can achieve that. If I set %USERPROFILE% then I loose the ability to open WT directly in any other location.

**Comment by zadjii-msft** [comment]
This is an unfortunately complicated problem, with a lot more details in
* https://github.com/microsoft/terminal/issues/878#issuecomment-538511693
* https://github.com/microsoft/terminal/pull/3547
* https://github.com/microsoft/terminal/issues/878#issuecomment-579508860

So, I'd recommend leaving `startingDirectory` set to `%USERPROFILE%`, and manually adding `-d .` to the commandline for your shortcuts. That'll get you the behavior you want:
* shortcuts will open up in the surrent directory
* right-click in explorer will open up in explorer's CWD
* launching from the Start Menu, Taskbar, etc, will launch in `%USERPROFILE%`

**Comment by Zingam** [comment]
This doesn't solve the issue to open a terminal via File Explorer's (address bar??) that I learned to use instead of adding Command Prompt to the right click menu via the registry a long time ago. Yet the proposed solutions sound like a good start. Why don't you create this configuration and short cuts by default during installation? At least this wasn't the case when I installed WT.

**Comment by Zingam** [comment]
> So, I'd recommend leaving `startingDirectory` set to `%USERPROFILE%`, and manually adding `-d .` to the commandline for 

OK. I guess -d . is meand for File Explorer bar. What about introducing an alternative alias for that like 'wtd', which will do what wt -d . It may not look that much shorter but in the long term it save the planet from overheating.
