### ISSUE TITLE
Resize bug with htop and win32-openssh

### ISSUE THREAD

**Issue by Tarocch1** [microsoft/terminal#1184]
# Environment

Windows build number: 18362.145
Windows Terminal version (if applicable): [0.0.1906.0716 Terminal CI](https://dev.azure.com/ms/Terminal/_build/results?buildId=19062)
Windows 10 OpenSSH

# Steps to reproduce

1. Connect to a linux server with ssh
2. Run htop on server
3. Maximize window
4. Recovery window
5. Exit htop

# Expected behavior

![image](https://user-images.githubusercontent.com/15124068/59156314-a6074800-8acb-11e9-8c26-72262395cff1.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/15124068/59156319-c6370700-8acb-11e9-8887-952e5b1b3872.png)

**Comment by zadjii-msft** [comment]
@Tarocch1 Does this repro with ssh from within WSL? Or only with the OpenSSH built in to Windows?

**Comment by Tarocch1** [comment]
@zadjii-msft OpenSSH built in to Windows

**Comment by zadjii-msft** [comment]
That's what I thought. This is more likely than not an issue that actually belongs in [PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/issues)
