### ISSUE TITLE
context menu do not work when launched from the taskbar

### ISSUE THREAD

**Issue by sp4d1n0** [microsoft/terminal#11845]
### Windows Terminal version

1.11.2921.0

### Windows build number

22000,348

### Steps to reproduce

Right click and select a profile from the taskbar icon. 

### Expected Behavior

I expect the profile to be opened, as it did

### Actual Behavior

It say that "the item you selected is unavailable. It might be moved, renamed or removed. etc..."

**Comment by zadjii-msft** [comment]
Can I get a screenshot of the error message? Does launching the Terminal from the taskbar work normally? Do _any_ profiles work, or are they all broken?
