### ISSUE TITLE
"Open in Windows Terminal" and "Windows Terminal" context menu is gone in Windows 11 22000.348

### ISSUE THREAD

**Issue by EdiWang** [microsoft/terminal#11840]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.348

### Steps to reproduce

1. Install KB5007262 on Windows 11
2. Right click Start button
3. Right click in any folder in Explorer

### Expected Behavior

- For step 2, "Windows Terminal" and "Windows Terminal (Admin)" should appear in the menu.
- For step 3, "Open in Windows Terminal" should appear in context menu.

### Actual Behavior

No "Windows Terminal" and "Windows Terminal (Admin)" is displayed.

![image](https://user-images.githubusercontent.com/3304703/143820542-9717c3d5-3c83-476c-a29c-09feaeb72d7b.png)

No "Open in Windows Terminal" is there in context menu.

![image](https://user-images.githubusercontent.com/3304703/143820664-aaa053c9-8f44-4cac-bb90-5944f1ee8791.png)

**Comment by EdiWang** [comment]
Update: Not all Windows 11 with KB5007262 will encounter this issue. Some machine is just missing the explorer context menu but win+x menu for Windows Terminal is still there.

**Comment by TarunavBA** [comment]
Related to or dupe of #11839

~ 🤖

**Comment by EdiWang** [comment]
I manually fixed the win+x menu by copying good entries from a new local user. Explorer context menu is still gone.

`C:\Users\<username>\AppData\Local\Microsoft\Windows\WinX\Group3`

![image](https://user-images.githubusercontent.com/3304703/143823819-cd6e72c0-41db-41be-8c8a-44cbc7fc5050.png)

**Comment by zadjii-msft** [comment]
I reached out to someone on the explorer team, and they told me how to get some advanced diagnostics that might help.

You should be able to take an advanced trace on in the Feedback Hub, on the bottom page:
![image](https://user-images.githubusercontent.com/18356694/143950454-cb16798d-808d-40b6-bd33-440f6ab22695.png)

then, file feedback on the File Explorer path as usual, and make sure to include the zip file from the advanced diagnostics trace. Add the "Share my feedback" link here, and I can make sure it gets promoted to the right folks.

Of course, if this isn't an issue anymore, we can just close this out without the trace ☺️

**Comment by EdiWang** [comment]
Close as a Microsoft internal ticket https://task.ms/37214068 is created under #11839
