### ISSUE TITLE
Korean translation error in the "Starting Directory" setting

### ISSUE THREAD

**Issue by yyoon** [microsoft/terminal#11846]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Open the settings -> general tab for any profile in Korean mode.

![image](https://user-images.githubusercontent.com/1309817/144075023-cde6e151-d71e-47ad-8637-d03116d95c79.png)

The Korean label saying "디렉터리를 시작하는 중" (which is probably an incorrect translation from "starting directory") doesn't make sense, as it sounds more like "[something] is starting a directory".

### Expected Behavior

The Korean label of the starting directory setting should be "시작 디렉터리".

### Actual Behavior

The setting label actually says "디렉터리를 시작하는 중"

**Comment by lhecker** [comment]
Unfortunately I must've forgotten to post the internal tracking issue here.
This mistranslation has been fixed. The starting directory field is now labeled "시작 디렉터리" in the latest Windows Terminal version. 🙂
