### ISSUE TITLE
No keyboard input

### ISSUE THREAD

**Issue by weldermarcosxd** [microsoft/terminal#11841]
I know thats an old problem, but the solutions like enabling and starting "Touch Keyboard and Handwriting Service" didnt help me.
![image](https://user-images.githubusercontent.com/10182883/143872608-859f865a-c0ec-48be-aacd-9aac263b776c.png)

Still I can't type:
![image](https://user-images.githubusercontent.com/10182883/143872405-490fdd55-097f-4a03-9f4e-69b848a64f83.png)

Tried reinstalling and updating windows to its latest.

Any tips?

**Comment by zadjii-msft** [comment]
* What version of the Terminal? 
* Do you have PowerToys installed?
* Are you using any accessibility software, like Narrator, Magnifier, NVDA, JAWS?
* Are you using any sort of IME to type into the Terminal?
* Did you restart after setting the service to start automatically?

There's a bunch of help from **@&zwj;ebadger** in #9890 - could you try following the steps in that thread, and see if that resolves the issue?

(sorry for the runaround, we really need to turn that thread into a guide on the troubleshooting page of the docs)

(see also #10095, #10736, #11779)

**Comment by weldermarcosxd** [comment]
* What version of the Terminal?
![image](https://user-images.githubusercontent.com/10182883/143886372-2f53a871-9343-4892-b440-48d17727cc4a.png)
but tried some released in then later 2020 as well with the same results

*Do you have PowerToys installed?
No

*Are you using any accessibility software, like Narrator, Magnifier, NVDA, JAWS?
I have Narrator installed, but never used it

*Are you using any sort of IME to type into the Terminal?
No

*Did you restart after setting the service to start automatically?
Yes

I apreciate the help, I'll look these threads as well

Any updates I'll shout it here

**Comment by weldermarcosxd** [comment]
#9890 did indeed the trick.

killing msctfmonitor does resolve the problem. Thanks for your time.

#4448 is the first issue that returns when I google for the problem. Maybe leaving a hint there will guide the others.
