### ISSUE TITLE
Windows Terminal does not pad correctly pad vertically. 

### ISSUE THREAD

**Issue by nosed1ve** [microsoft/terminal#11843]
### Windows Terminal version

latest stable

### Windows build number

latest stable Windows 10

### Other Software

WSL, neovim, tmux etc.

### Steps to reproduce

Launch terminal with padding set to "5" for all sides, centerOnLaunch and initialCols: 90, initialRows: 30

![image](https://user-images.githubusercontent.com/67145097/143938085-093dc280-80d5-436d-8469-633aee95edbf.png)

first thing to note: the actual initialRows are 31, it is 30 because of tmux, but if tput lines is run outside of tmux, the output is 31.  I am assuming this is intentional so the terminal can be centered properly etc.

However, notice the padding on the bottom, it is not 5 pixels, it is a lot more. I saw an issue from earlier where it was stated this is intended, BUT when you hover over the bottom part of the window, the cursor changes to the "resize" shape, and if you simply just click and try dragging, the padding becames fine, BUT the size of the terminal window is not changed

after simply clicking and attempting to resize when the resize cursor appears:

![image](https://user-images.githubusercontent.com/67145097/143938644-0629445f-9701-4191-bdcf-4292ea7d3095.png)

### Expected Behavior

Padding is fine upon launch

### Actual Behavior

Padding is more than what is set in the config

**Comment by zadjii-msft** [comment]
Are you launching in focus mode? If so, then I'd suspect this is #10730

**Comment by nosed1ve** [comment]
Yes I am launching in focus mode, after looking at #10733 , it does seem like my problems are the same as the ones in that issue

**Comment by zadjii-msft** [comment]
Cool, thanks for confirming!

/dup #10730
