### ISSUE TITLE
Zero width space characters should not show up as visible spaces

### ISSUE THREAD

**Issue by pragma-** [microsoft/terminal#11850]
### Windows Terminal version

1.1129.1.0

### Windows build number

10.0.19043

### Other Software

Any software

### Steps to reproduce

Any console application printing a zero-width space (ZWSP, U+200B) intends for them to not be visible.

### Expected Behavior

Text with ZWSP characters invisible, having no width.

### Actual Behavior

Text with visible space characters.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1472 for more discussion.

/dup #1472
/dup #8000

**Comment by juliannoble** [comment]
Testing with latest canary.

For ZWSP (\U200B) there appears to be no way to have it non-printing while using the 'Grapheme clusters' mode.
You have to use wcswidth to fix the behaviour this issue describes and then forgo grapheme clusters.

If grapheme clusters is intended to be (as described) the 'modern' way - then this bug would still seem to be present.

It's unclear to me how

/dup https://github.com/microsoft/terminal/issues/1472
/dup https://github.com/microsoft/terminal/issues/8000

address this specific issue.
