### ISSUE TITLE
Put the x64 feature tests in a separate build phase that downloads the x64 build artifacts

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#11858]
It's driving me nuts that the machine sometimes goes LOL no and goes away on a rerun. Let's not waste time with all the other compile phases and such.

**Comment by zadjii-msft** [comment]
This is a good enough solution to #11289

**Comment by miniksa** [comment]
> This is a good enough solution to #11289

If I can make it work... sorry I didn't see that one.

**Comment by DHowett** [comment]
I'm testing this in #12141
