### ISSUE TITLE
Failed to build the terminal due to CL.exe under visual 2019

### ISSUE THREAD

**Issue by MikeLing** [microsoft/terminal#1185]
# Environment
Window 10 + Visual Studio 2019

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
> .\tools\razzle.cmd
> bcz rel

# Expected behavior
Everything works well 

# Actual behavior
       "C:\code\terminal\OpenConsole.sln" (Clean;Build target) (1) ->
       "C:\code\terminal\src\interactivity\win32\ut_interactivity_win32\Interactivity.Win32.UnitTests.vcxproj.metaproj"
        (default target) (7:2) ->
       "C:\code\terminal\src\interactivity\win32\ut_interactivity_win32\Interactivity.Win32.UnitTests.vcxproj" (default
        target) (44:2) ->
       (ClCompile target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta
       rgets(429,5): error MSB6006: "CL.exe" exited with code 2. [C:\code\terminal\src\interactivity\win32\ut_interacti
       vity_win32\Interactivity.Win32.UnitTests.vcxproj]

       "C:\code\terminal\OpenConsole.sln" (Clean;Build target) (1) ->
       "C:\code\terminal\src\host\ut_host\Host.UnitTests.vcxproj.metaproj" (default target) (13:2) ->
       "C:\code\terminal\src\host\ut_host\Host.UnitTests.vcxproj" (default target) (33:2) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta
       rgets(429,5): error MSB6006: "CL.exe" exited with code 2. [C:\code\terminal\src\host\ut_host\Host.UnitTests.vcxp
       roj]

**Comment by zadjii-msft** [comment]
Could you check out #489 or #565? Both of those threads are megathreads for all build related issues.
