### ISSUE TITLE
Changing keyboard layouts via Win+Space causes the font size to reset

### ISSUE THREAD

**Issue by vivivienne** [microsoft/terminal#11854]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19041.0

### Steps to reproduce

Pressing win+space at literally any time the terminal is open, it doesn't even need to be focused.

### Expected Behavior

Nothing to happen

### Actual Behavior

Font size resets (in all tabs).

**Comment by zadjii-msft** [comment]
Hey look, we saw something just like this in #11837

/dup #11522
