### ISSUE TITLE
Why not add session management and file transfer functions?

### ISSUE THREAD

**Issue by b1tkeeper** [microsoft/terminal#11855]
When I connect ssh server in Windows, the best tools to do it is Mobaxterm, but It's too complex and ugly. I really like Microsoft Terminal, Why not add session management and file transfer features to it. It will be more popular.

**Comment by zadjii-msft** [comment]
File transfer is probably best left for something like `scp`, a tool that's actually dedicated to it. 

Could you elaborate more on what you mean by "session management"?

**Comment by j4james** [comment]
I suspect by "session management" they mean something along the lines of #1280. In apps like MobaXterm and PuTTY you can setup a session (like Windows Terminal profile) with your SSH connection parameters preconfigured, and the same concept can be used for file protocols like FTP and SFTP. I think it was decided that this would best be implemented as a plugin though.
