### ISSUE TITLE
emacs shortcut keys are not available

### ISSUE THREAD

**Issue by cndeng** [microsoft/terminal#11864]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043

### Other Software

GNU Emacs 27.2 (in wsl)

### Steps to reproduce

In org-mode, the following two shortcut keys are not available
alt-shift-LEFT (org-promote-subtree)  Promote the current subtree by one level.
alt-shift-RIGHT (org-demote-subtree)  Demote the current subtree by one level.

### Actual Behavior

In org-mode, the following two shortcut keys are not available
alt-shift-LEFT (org-promote-subtree)  Promote the current subtree by one level.
alt-shift-RIGHT (org-demote-subtree)  Demote the current subtree by one level.

**Comment by zadjii-msft** [comment]
the default settings have those keys bound to `resizePane`:
https://github.com/microsoft/terminal/blob/52235b0fb6b3476bedf573d5f7fc5624e1bdbd3f/src/cascadia/TerminalSettingsModel/defaults.json#L346-L349

So you'll need to unbind them if you'd like to use those keys in emacs. You can do that with:
```json
        { "command": unbound, "keys": "alt+shift+down" },
        { "command": unbound, "keys": "alt+shift+left" },
        { "command": unbound, "keys": "alt+shift+right" },
        { "command": unbound, "keys": "alt+shift+up" },

```
