### ISSUE TITLE
[Discussion] Windows Terminal without PowerShell for corporation in reference to #6010

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/terminal#11869]
Hello,

I was reading the discussion of the issue #6010, that it is possible to install an offline and unregistered version of Windows Terminal with an offline licence. 

But our case is different.

The company, where we work as software analysts, developers and engineers, allow us to demand the addition of software to their own software central **since they do not depend on PowerShell and on winget**. 

The company disables PowerShell and does not allow us to re-enable it. It does not allow us to install software that set PowerShell as default (except VSCode, in which we can change manually from PowerShell to Command Prompt or Git Bash). For this reason, Windows Terminal can not be approved, although we can change manually the default shell of Windows Terminal. The problem is PowerShell. 

I was reading the README, that PowerShell is one prerequisites, but I saw the issue #6010, that they could install offline and unregistered version of Windows Terminal without depending on PowerShell. 

Is there how the company install Windows Terminal without PowerShell and without winget?

**Comment by zadjii-msft** [comment]
PowerShell absolutely isn't a pre-requisite for installing the Terminal. You can use the Terminal with PowerShell, but if your company is dead set on blocking PowerShell, then you can always change the default shell to Command Prompt<sup>[1]</sup>. The Terminal will automatically default to powershell, but it doesn't _need_ powershell, and it doesn't ship _with_ powershell.

If you can't use winget, or the Store, then you can always download the msix from the https://github.com/microsoft/terminal/releases page, and unzip that. If the msix doesn't install, then you can always just run the `windowsterminal.exe` in that zip file "unpackaged", and it should work totally fine.

<sup>[1]</sup>: lmao that they block powershell but not `cmd.exe`, I'm sure you can do just as much with command prompt as you can with powershell, but hey, silly IT departments gonna silly IT.
