### ISSUE TITLE
Changing volume via keyboard scrolls me to bottom

### ISSUE THREAD

**Issue by sdegutis** [microsoft/terminal#11876]
### Windows Terminal version

1.11.2129.0

### Windows build number

10.0.22000.348

### Other Software

git-bash and tail -f

### Steps to reproduce

1. Tail something
2. Scroll up
3. Press volume-up/down on keyboard

### Expected Behavior

Stay where you are, Terminal

### Actual Behavior

Wait Terminal, come back!

**Comment by zadjii-msft** [comment]
This was harder to find than expected, and I _knew_ it was on the backlog somewhere: /dup #5366

Thanks!
