### ISSUE TITLE
Feature Request: Titlebar's theme isn't complete

### ISSUE THREAD

**Issue by SmartPolarBear** [microsoft/terminal#1187]
# Summary of the new feature/enhancement

The latest terminal, when running under Dark theme, still has a white region  under the window's control buttons while other regions are rightly applied to the Dark theme.

# Proposed technical implementation details (optional)
In dark mode, all the title bar is supposed to be dark.

**Comment by zadjii-msft** [comment]
This is a subset of the work that needs to be done in #872
