### ISSUE TITLE
The sizeof(wistd::function) has grown too large for the reserved buffer (12 pointers). Refactor to reduce size of the capture.

### ISSUE THREAD

**Issue by Zachary-Rude** [microsoft/terminal#11882]
I'm trying to build Windows Terminal from source to use it as the basis for the upcoming Zach Inc. Terminal.

However, when I try to build it, I get this issue's namesake error.

## Expected Behavior

I'm expecting the terminal to build and run successfully.

## Actual Behavior

Instead, I get this error:

![error](https://user-images.githubusercontent.com/84681078/144721619-d833a28a-f924-40da-a36d-4e27e65747b5.png)

**Comment by zadjii-msft** [comment]
Have you changed anything? I'm assuming that's the settings reload lambda in `AppLogic::_RegisterSettingsChange`? Maybe you're compiling with an older toolset version, or an older compiler version? I know I recently tried expanding that lamba and got a similar warning. 

The CI seems to build [perfectly well](https://github.com/microsoft/terminal/runs/4404178720) on `main`, so I'm guessing that this is related to some local change you've made.
