### ISSUE TITLE
When windows terminal is inactive, it resets transparency settings

### ISSUE THREAD

**Issue by DenisSermyagin** [microsoft/terminal#11898]
### Windows Terminal version

latest

### Steps to reproduce

1. Change opacity to 0.5, 0.25, etc
2. Look how that work (first screenshot)
3. Change your active window (second screenshot)

![image](https://user-images.githubusercontent.com/57506602/145111458-1cb4182a-8476-4316-83c1-497550377a05.png)
![image](https://user-images.githubusercontent.com/57506602/145111493-cb3d73e3-f466-43bf-a0bf-56057770a040.png)

Json settings here:
![image](https://user-images.githubusercontent.com/57506602/145111567-3afa0cbc-437c-4a3f-9f62-722274bc7966.png)

### Actual Behavior

Transparency does not change when switching windows.

**Comment by zadjii-msft** [comment]
Please check [the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-does-acrylic-not-work). This is by design. Acrylic only works on the foreground window. You may be interested in /dup #7158
