### ISSUE TITLE
CLS doesn't work in the VT alternate buffer

### ISSUE THREAD

**Issue by lesleyxyz** [microsoft/terminal#1189]
# Environment

```none
Windows build number: [Version 10.0.18362.145]

Windows Terminal version (if applicable): n/a

Any other software? wsl, nano
```

# Steps to reproduce
1) In either powershell or cmd in terminal, type `wsl nano`
2) Execute `taskkill -im wsl.exe -f` to kill wsl
3) Type `cls` in the terminal where wsl was open

# Expected behavior
`cls` should clear the screen and make the terminal behave like it used to before `wsl nano`

# Actual behavior
after killing `wsl` powershell/cmd is in a bugged state because nano takes up the whole screen
cmd: cls won't clear the screen (first screenshot)
powershell: cls will clear screen BUT if the user inputs e.g. "cls", terminal will print "cclcls", yet still interpret it as "cls" (second screenshot)

![L0030755](https://user-images.githubusercontent.com/5853564/59160360-47df6280-8ad5-11e9-8d15-6ee4f756ef15.png)

![L0030807](https://user-images.githubusercontent.com/5853564/59160417-013e3800-8ad6-11e9-986a-ee5621c97d8f.png)

This issue is also present in the original cmd/powershell.

**Comment by zadjii-msft** [comment]
Well this isn't a terminal-specific problem, this totally repros in conhost too. 

There's a lot more bugged here too, like the fact that backspace will delete the entire word, and the arrow keys don't work - they're stuck in VT input mode. Presumably for each of cmd.exe and powershell, if the attached process exits uncleanly, they don't restore the input mode. At least for cmd.exe, this will 100% not get fixed.

I'm kinda curious that `cls` doesn't work from cmd in this state, but I'd be scared to find out why.

**Comment by DHowett-MSFT** [comment]
Two things here.
1. `cls` doesn't work in the alternate buffer. When you run `cls` it actually goes and clears the _main buffer_. That shouldn't be happening.
2. Killing any application in _any terminal emulator_ after it has entered a non-default mode (alt screen buffer, SGR mouse mode, margins, scroll regions, etc.) always ends poorly. It's just not a supportable scenario.

**Comment by lesleyxyz** [comment]
Thank you for your replies, these are some new interesting things that I get to learn.
If this is not a supportable scenario, shall I close this issue?

**Comment by DHowett-MSFT** [comment]
Nah, we'll take the first bullet point here as a bug, which it well and truly is :smile: Thanks for reporting!
