### ISSUE TITLE
Warnings found while parsing your keybindings

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#11895]
### Windows Terminal version

Commit 81d92975372a48469faac7423d8c3d74d5a5b500

### Windows build number

10.0.19041.1348

### Steps to reproduce

1. Checkout commit 81d92975372a48469faac7423d8c3d74d5a5b500 or later.
2. Build the solution.
3. Run the _CascadiaPackage_ project.

### Expected Behavior

The terminal should open without any warnings.

### Actual Behavior

A dialog pops up with the following warning message:
```
Encountered errors while loading users settings

Warnings were found while parsing your keybindings:
* Found a keybinding that was missing a required parameter value. This keybinding will be ignored.
```
The latter bullet point is repeated about a dozen times.

I've tried deleting the settings.json file in case there was something weird there, but that made no difference. According to git bisect, the issue was likely introduced in commit 81d92975372a48469faac7423d8c3d74d5a5b500.

**Comment by zadjii-msft** [comment]
Yep, that's on me, the fix is already in #11892
