### ISSUE TITLE
`Encountered errors while loading user settings` with 3606c3d

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11896]
### Windows Terminal version

main 3606c3d

### Windows build number

10.0.22000.0

### Steps to reproduce

- remove any previous WT packages and use settings
- clone and build latest Cascadia Package ( 3606c3d used for testing )

### Expected Behavior

- no errors on terminal launch

### Actual Behavior

- multiple `encountered errors while loading user settings`  warnings:

![wt_main-3606c3d_error](https://user-images.githubusercontent.com/3933920/145063580-9e9d5828-481b-4acf-a5a3-cce74482d5dc.png)

**Comment by zadjii-msft** [comment]
Fix is already in #11892
