### ISSUE TITLE
Add an option to clear the scroll-back buffer

### ISSUE THREAD

**Issue by xlnxminusx** [microsoft/terminal#11907]
Please add a bindable action to clear the scrollback buffer (i.e. clear all previous text and reset to a new terminal window).  On the mac terminal, this is bound to cmd-k.

**Comment by DHowett** [comment]
This is available in Terminal preview 1.12 under the name `clearBuffer`:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/189190/145302904-4bde0bdb-b1ae-4f2e-a1bb-fb1cccb24ccd.png">

**Comment by DHowett** [comment]
/dup #1882 :smile:

You can install the preview from https://aka.ms/terminal-preview if you'd like. It runs side by side with the stable terminal and won't impact your settings. You can use them simultaneously as long as you wish.

We try to keep preview pretty stable in terms of reliability!
