### ISSUE TITLE
CTRL+F4 not working

### ISSUE THREAD

**Issue by abhinavsatheesh** [microsoft/terminal#11909]
### Windows Terminal version

1.11.2921.0

### Windows build number

22000.348

### Steps to reproduce

When I am using Command Prompt or PowerShell within Windows Terminal, the CTRL+F4 shortcut to close the tab is not working

### Expected Behavior

When I press CTRL+F4, the current tab in Windows Terminal must close, which is what the documentation states.

### Actual Behavior

The tab didnt close. It just remained still just like that

**Comment by zadjii-msft** [comment]
Please search when filing new issues. Namely, #11419 and #8585. Ctrl+F4 is not a keybinding that's bound by default. You can find a full list of the default keybindings [here](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json#L282-L455). Notably,

```json
{ "command": "closePane", "keys": "ctrl+shift+w" },
```

and "closePane" will close a tab, it it's the only pane in the tab.

the Ctrl+F4 that's on the tab is provided by XAML itself, and we need to do some work to get rid of it / replace it with the actual keybinding. (see #10109)

/dup #11419
