### ISSUE TITLE
Can't set keyboard shortcuts with non-printable characters

### ISSUE THREAD

**Issue by VedresDavid** [microsoft/terminal#11921]
### Windows Terminal version

1.11.2921.0

### Windows build number

22000.318

### Steps to reproduce

go to the actions tab and try to change one of the shortcuts to something else. for example i tried to set the quake mode to win + 0 but i can't record the win/alt/ctrl and other non-printable keys.

### Expected Behavior

i want to be able to create shortcuts that contain special characters in them. (win/alt/ctrl...)

### Actual Behavior

i can't

**Comment by zadjii-msft** [comment]
> win/alt/ctrl and other non-printable keys.

That's weird - are you just pressing the keybinding in the editor, or are you trying to type the key out? Might be related to #11341

FWIW, <kbd>Win+1</kbd>-<kbd>Win+0</kbd> _won't_ work as keybindings, since those are reserved by the OS.

**Comment by VedresDavid** [comment]
i tried both typing it out and pressing the keys. neither of them worked. though the ctrl key started working so i just set the quake mode to ctrl + 0. the other keys still won't work. my guess is that the os is capturing the win key from the application.

**Comment by zadjii-msft** [comment]
> my guess is that the os is capturing the win key from the application.

Could be. Depends on what key chord you're pressing - most of them are reserved by the OS. You could always edit the [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file) by hand, to add the chord you want. I suspect, however, if it's not reaching the Terminal in the Settings UI, then something's already hooked that keybinding, and setting that keybinding manually won't work either 😉
