### ISSUE TITLE
can windows terminal set group for profiles list

### ISSUE THREAD

**Issue by kailingxiong** [microsoft/terminal#11926]
I need manage 20+ centos server by ssh, the profiles list is too long to manage

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+group+profiles) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
