### ISSUE TITLE
wsl start slowly

### ISSUE THREAD

**Issue by Angel0726** [microsoft/terminal#11922]
wal start slowly with Windows terminal

**Comment by lhecker** [comment]
Two questions:
* Does Windows Terminal launch automatically after boot?
* After restarting your PC, does wsl.exe from the start menu start slowly?

**Comment by Angel0726** [comment]
terminal launch fast,but wsl launch slowly with terminal. i didn't test it with start menu

**Comment by lhecker** [comment]
I suspect you'll see that it also starts slowly if you start WSL from the start menu without Windows Terminal.
WSL is slow to start on the first launch after a while (or after a reboot) because WSL runs in a virtual machine which first needs to boot in the background. I suspect that you should notice that WSL launches a lot faster after you open it a second time.

**Comment by Angel0726** [comment]
> I suspect you'll see that it also starts slowly if you start WSL from the start menu without Windows Terminal.
> WSL is slow to start on the first launch after a while (or after a reboot) because WSL runs in a virtual machine which first needs to boot in the background. I suspect that you should notice that WSL launches a lot faster after you open it a second time.

i test it.  WSL start slowly from the start menu, but WSL is also slow to start on the first launch after a while. what's more , when wsl is open, i start another wsl is slow too

**Comment by zadjii-msft** [comment]
> WSL start slowly from the start menu, but WSL is also slow to start on the first launch after a while. what's more , when wsl is open, i start another wsl is slow too

Huh. That sounds like a WSL problem, not a Terminal one. You should probably report this over at https://github.com/microsoft/WSL/issues, thanks!

**Comment by Angel0726** [comment]
> > WSL start slowly from the start menu, but WSL is also slow to start on the first launch after a while. what's more , when wsl is open, i start another wsl is slow too
> 
> Huh. That sounds like a WSL problem, not a Terminal one. You should probably report this over at https://github.com/microsoft/WSL/issues, thanks!

thank you
