### ISSUE TITLE
Terminal Team's Holiday 2021 ☃️❄️🎄🎁💤💻🎮📖🍺🧩

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#11923]
Hey everyone!

The Terminal team will be out for the holidays at the end of December this year.

Thank you for being patient with us as our activity winds down this month and we all go on break to spend time relaxing and recharging. The "Engineering Improvement Month" you've seen us work through the last few weeks also includes improving the health and wellness of our engineering team too. It's not _just_ the code! 😜

We should resume normal levels of responsiveness in early January. Feel free to continue participating here in issues, pull requests, and discussions. We'll pick them up when we return!
You may also see a random post or two from us over the break as we love what we do so much that sometimes we check in when we're on vacation anyway! But please don't expect full engagement until after everyone returns.

Thank you for understanding! We hope you have a wonderful holiday season. Thanks for hanging with us through 2021 and we look forward to seeing you all in 2022!

(For extra credit: share something you're excited about for this holiday season or your favorite part of 2021 in the thread below and we will as well!)

|Person|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|1|2|3|4|5|6|7|8|9|10|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|Carlos (@carlos-zamora)|💻|💤|💤|💻|💻|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Dustin (@DHowett)|💻|💤|💤|💻|💻|💻|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Kayla (@cinnamon-msft)|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Leon (@leonMSFT)|💻|💤|💤|💻|💻|💻|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Leonard (@lhecker)|💻|💤|💤|💻|💻|💻|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|
|Michael (@miniksa)|💻|💤|💤|💻|💻|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Mike (@zadjii-msft)|💤|💤|💤|❔|❔|❔|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|
|Pankaj (@PankajBhojwani)|💻|💤|💤|💻|💻|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💤|💻|💻|💻|💻|💻|💤|💤|💻|

**Comment by miniksa** [comment]
@miniksa's Holiday Recharge To-Do List:
- Install some sort of Zigbee/Zwave controller into the sleep sounds machine so I don't have to get out of bed to turn it on and off
- Build out https://niksa.dev so I can start writing blog posts about all sorts of topics on my mind
- Play a bunch of Forza Horizon 5 and Animal Crossing Happy Home Paradise
- Scan all the paperwork that is on my desk at home and file it
- Try out https://photoprism.app to hopefully make our family photos less of a mess
- Figure out if https://obsidian.md is for me after @DHowett was talking about it
- Finish the [Costco Puzzle](https://www.costco.com/dowdle-costco-puzzle-500-piece.product.100773422.html)
- Read a bunch under a warm blanket and a pile of Squishmallows
- And more, I'm sure!

**Comment by PankajBhojwani** [comment]
I'll be going skiing for the first time ever :)

**Comment by carlos-zamora** [comment]
Spending some time with my family in Mexico. Excited to catch up on my backlog of games. Hopefully I'll be good enough to beat @miniksa at Forza Horizon 5 when I get back 😉 haha

**Comment by lhecker** [comment]
I like Cocoa. So I'm gonna build my own WinUI from scratch with a Cocoa-like API.
Otherwise it's time to do a lot of nothing I guess. Finally finishing Zelda Breath of the Wild would be a good start. 😄

**Comment by WSLUser** [comment]
> I like Cocoa. So I'm gonna build my own WinUI with a Cocoa-like API.

Do this, and the Iterm2 devs will love you. This is what they say is their main blocker for not porting to Windows.

**Comment by skyline75489** [comment]
It's not a holiday for me but I'm feeling the warmth of it in this issue.  Hope you all have a wonderful holiday season 😸

**Comment by lhecker** [comment]
> Do this, and the Iterm2 devs will love you. This is what they say is their main blocker for not porting to Windows.

This will never happen. 😄 Neither have I the free time to actually replicate the Cocoa API, nor to make it anything but a toy project. I only build it to learn more about the various Windows API and to improve my programming skills. Any serious project on Windows will always be better served with WinUI.

**Comment by zadjii-msft** [comment]
I apparently never posted my own plans - in contrast to some other members of the team, I had absolutely no plans to be productive at all in my off time 😆 I saw some family, finally beat the Halo Infinite campaign (one 45 minute nap at a time), and made it to my fantasy football playoffs 🎉🎉.

<hr>

Most of the team's back this week, so I'm gonna close this out and unpin it.  We'll be slowly working through triaging the **87** new issues since we left, so bear with us. Thanks!

**Comment by DHowett** [comment]
Ah, I never posted mine either! I spent my holiday...

1. In front of Ghidra, documenting [how the embedded controller in the Framework Laptop works](https://www.howett.net/posts/2021-12-framework-ec/)
2. Trying, and ultimately failing, to complete Metroid Dread
3. Doing "First Christmas in the new house" stuff!

Happy new year, everyone! 🎆
