### ISSUE TITLE
Plus symbol at top overlaps tabs and does not allow the last tab to close

### ISSUE THREAD

**Issue by Srijan1214** [microsoft/terminal#1192]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by Srijan1214** [comment]
Plus symbol at top overlaps tabs and does not allow the last tab to close.

**Comment by DHowett-MSFT** [comment]
Thanks for reporting this!
Please make sure you fill out the bug template when you make the bug; otherwise, we all get an e-mail saying "there is a bug report" with no info in it.

**Comment by zadjii-msft** [comment]
@Srijan1214 Could you be more specific? Possibly post a screenshot of the issue you're describing?

As a workaround, you could always just close the window to close the last tab...

**Comment by DHowett-MSFT** [comment]
This is almost certainly a duplicate of #651

**Comment by DHowett-MSFT** [comment]
I meant #444
