### ISSUE TITLE
windows terminal‘s  environment variables are inconsistent

### ISSUE THREAD

**Issue by WUYANGHAO** [microsoft/terminal#11927]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.348

### Steps to reproduce

1. Open windows terminal directly from the taskbar

2. right-click in the specified directory to open windows terminal

### Actual Behavior

Use the right button to open the windows terminal and open the windows terminal  directly, and the environment variables are inconsistent。
![image](https://user-images.githubusercontent.com/25316996/145708354-19c70687-65a0-4f5f-a9cb-187640330c95.png)

**Comment by zadjii-msft** [comment]
Could you clarify, which terminal in the screenshot is from the taskbar vs the one from File Explorer?

We've heard intermittent reports of this before in #11829. Making sure to force-quit all the Terminal processes in Task Manager might help here.
