### ISSUE TITLE
Settings doesn't show background image path

### ISSUE THREAD

**Issue by HashemLovesYou** [microsoft/terminal#11940]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Open settings > (any profile) > Appearance > Background Image
`Background image path` box is empty, even though it has an image (to be clear, the background setting works just fine

### Expected Behavior

the box should have the image path in it

### Actual Behavior

the box is empty
![image](https://user-images.githubusercontent.com/78832113/146111717-14bcd837-acd2-4316-a41f-9de55313fdc0.png)

**Comment by ianjoneill** [comment]
This was fixed in #11580, which was released in [v1.11.3471.0](https://github.com/microsoft/terminal/releases/tag/v1.11.3471.0) yesterday (2021-12-14). It could take a couple of days before the update is pushed to your PC.

**Comment by zadjii-msft** [comment]
Yep, thanks!

/dup #11541
