### ISSUE TITLE
OpenConsole/WindowsTerminal keep handles on directory after closing tab, when terminal is opened through context menu.

### ISSUE THREAD

**Issue by JornVernee** [microsoft/terminal#11944]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.0

### Steps to reproduce

1. Create a test directory, e.g. `test`
2. Open the directory in Windows `explorer`,
3. Use the right-click context menu to "Open in Windows terminal". This should open a powershell instance with the working directory set to the `test` directory. (Note that opening the terminal somewhere else, and `cd`'ing to the `test` directory will not create the problematic file handles).
4. Open a new Windows Terminal tab (e.g. I'm using Ubuntu to test). Make sure that this shell is not using the `test` directory as a working directory.
5. Close the original (powershell) tab that has the `test` directory as working directory.
6. Try to delete the `test` directory. This should fail because the directory is still in use by another process.

At this point, you could use e.g. Resource Monitor to see that OpenConsole.exe and WindowsTerminal.exe still have open handles on the test directory. 
![image](https://user-images.githubusercontent.com/5962029/146224510-d96d0039-0eaa-4469-a5b4-b3fa2611465f.png)

The workaround for this is to close the Windows terminal instance, which will release the handles.

### Expected Behavior

After closing the original tab in Windows terminal, it should be possible to delete the `test` directory.

This feels like a resource leak, since I am no longer using the `test` directory through Windows Terminal, and (AFAIK) there is nothing I can do in Windows Terminal to release those file handles.

### Actual Behavior

Deleting the `test` directory failes, because there are still open handles on it.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5506 for more discussion.

/dup #5506

**Comment by JornVernee** [comment]
Thanks! I couldn't find it when searching.
