### ISSUE TITLE
Acrylic doesn`t work

### ISSUE THREAD

**Issue by bakashigure** [microsoft/terminal#11943]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22509.1011

### Steps to reproduce

`install windows terminal from microsoft store`
`enable arcylic in wt settings`

### Expected Behavior

The window should have acrylic effect, just like the exmaple on microsoft.com,

### Actual Behavior

When the window gets focus, the windows just change the color from black to grey, instead of arcylicy effect,
now it looks like this,
![image](https://user-images.githubusercontent.com/33803916/146202985-f9b36703-8eca-4ec2-b279-7cf383ea4e2d.png)

my settings.json
```
        "defaults": 
        {
            "acrylicOpacity": 0.52000000000000002,
            "useAcrylic": true
        },
```
I've been using it since windows 10, I don't know which day the arcylic effect stopped working. I've tried re-installing it, tried the preview version, and it still doesn't work :(

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #11880 for more discussion.

/dup #11880
