### ISSUE TITLE
Fonts : VictorMono & FiraCode incorrect & overlap italic style.

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [microsoft/terminal#11954]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1415

### Other Software

_Terminal itself_ , Vi, Vim & Neovim.

**VictorMono :** Terminal display incorrect italic [VictorMono](https://rubjo.github.io/victor-mono/) fonts  _in_ and _outside_ text editor. 
> * Font size : 14 (all)
> * Font Weight : normal or medium

**FiraCode/FuraCode :** same as above.
> * Font size : 14 (all)
> * Font Weight : maybe all.

Actually it already happened before the [latest release](https://github.com/microsoft/terminal/releases/tag/v1.11.3471.0) . 

### Steps to reproduce

**VictorMono**
![VictorMono](https://user-images.githubusercontent.com/73665622/146295615-c7e9a112-e53e-4844-ba74-d26dba9859bc.png)

**FiraCode/FuraCode**
![FiraCode](https://user-images.githubusercontent.com/73665622/146295689-a723d998-0480-43e0-8a2b-841dba09252b.png)

### Actual Behavior

As you expect ...

**Comment by j4james** [comment]
This is essentially the same bug as #9381. If the italic characters don't fit within a cell, they're likely to get truncated on rendering boundaries where the color or style needs to change.

**Comment by zadjii-msft** [comment]
Thanks! /dup #9381
