### ISSUE TITLE
Windows terminal only render 1/4 area of the window 

### ISSUE THREAD

**Issue by Po-wei** [microsoft/terminal#11953]
### Windows Terminal version

1.12.3472.0

### Windows build number

win10 21H2 19044

### Other Software

I do not have other software, but I think these config may help you reproduce.
My test OH-MY-ZSH profile with a right prompt:

```
PROMPT='%n@%m:
%(!.#.$)'
RPROMPT='[%*]'
```
My windows temineral setting.json: http://codepad.org/s1wjnl0Y

Only one 4K monitor **SCALE : 200%**

### Steps to reproduce

Launch the terminal.
That's it

### Expected Behavior

With full windows render area.

### Actual Behavior

As you can see only 1/4 has text.
https://user-images.githubusercontent.com/17596021/146294950-fb444060-b9cf-4197-a730-13a1296a3dfd.mp4

After resizing, it becomes normal.

**Comment by zadjii-msft** [comment]
This is either a dup of #11317 or #11336 - haven't quite untangled those two yet. 

/dup #11336
/dup #11317

**Comment by Po-wei** [comment]
@zadjii-msft  those issues seem relative to resolution change.
I have only **one monitor** btw.
