### ISSUE TITLE
Can't use Emojis in Windows Terminal or Windows terminal preview.

### ISSUE THREAD

**Issue by Yush08** [microsoft/terminal#11955]
### Windows Terminal version

1.11.3471.0

### Windows build number

Version 10.0.19043.1348

### Other Software

PSVersion                      5.1.19041.1320

### Steps to reproduce

Install Windows terminal
Open it
Use `Windows + .` to bring the emoji menu
Try to insert a crab emoji
Failure

### Expected Behavior

The crab emoji should be there

### Actual Behavior

![image](https://user-images.githubusercontent.com/93856041/146298272-8fb2c3f3-e2e9-494b-b422-6a3b092d8193.png)
![image](https://user-images.githubusercontent.com/93856041/146298324-ef933fd0-81ca-44d9-b14d-8bcf21e379ed.png)
First is my personal terminal, wt stable. Second is wt preview. Both aren't having emojis support.

**Comment by elsaco** [comment]
@Yush08 it might not be wt's fault. On Win 10 it works with `PowerShell 7` but not with `PowerShell 5`.

PS7 output:
![pwsh7_crab](https://user-images.githubusercontent.com/3933920/146307027-a46ed989-f888-4f97-ae97-be7fb19107f2.PNG)

PS5 output:
![pwsh5_crab](https://user-images.githubusercontent.com/3933920/146307056-e02e6910-0c89-4834-b4e0-cdd73a03098c.PNG)

**Comment by Yush08** [comment]
> @Yush08 it might not be wt's fault. On Win 10 it works with `PowerShell 7` but not with `PowerShell 5`.
> 
> PS7 output: ![pwsh7_crab](https://user-images.githubusercontent.com/3933920/146307027-a46ed989-f888-4f97-ae97-be7fb19107f2.PNG)
> 
> PS5 output: ![pwsh5_crab](https://user-images.githubusercontent.com/3933920/146307056-e02e6910-0c89-4834-b4e0-cdd73a03098c.PNG)

I will test this out, anyway I can upgrade to Powershell 7? I've just been using the version Windows came with

**Comment by zadjii-msft** [comment]
This is either #1503 or #190, or something else related to those two. Updating PowerShell (or maybe even just PSReadline) is likely your best bet here.

/dup #190
/dup #1503
