### ISSUE TITLE
Launch size doesn't have a sensible max value

### ISSUE THREAD

**Issue by f1WN356Uh51a1W6cn** [microsoft/terminal#11957]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.376

### Steps to reproduce

Setting the max columns or rows visible on start to a crazy value like 900000000 doesn't make any sense. I also got an error.

### Actual Behavior

![](https://user-images.githubusercontent.com/62265474/146324749-4f648a82-d686-4e48-ace8-98d3d23716de.png)

**Comment by zadjii-msft** [comment]
That's a good point, thanks!

**Comment by marcelwgn** [comment]
@zadjii-msft Mind if I take my shot at this? Would probably just add a max value to the NumberBoxes and also clamp the read sizes from the settings file to something like 1000

**Comment by zadjii-msft** [comment]
@marcelwgn you're always free to just take a shot at anything around these parts 😝 

Technically, there's code somewhere in screenInfo.cpp that conhost uses to try and figure out the max size of a window for the display it's currently on. But I think using that here would probably be overkill. I'm sure 1000 columns is more than enough, even for like a 8k ultrawide or something ridiculous.
