### ISSUE TITLE
Terminal in Microsoft store and WinGet has different identifiers

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/terminal#11960]
### Windows Terminal version

1.11.3471.0

### Windows build number

19044.1348

### Steps to reproduce

Now the terminal can be installed twice, because the terminal in Microsoft Store and WinGet has different ID.

![image](https://user-images.githubusercontent.com/50652041/146368758-c3158c82-0712-44fd-ac13-0c3a86247847.png)

### Expected Behavior

I've got confused, because I had installed two different terminals.
When I'm launching the terminal from the icon - MS Store terminal starts.
But when I'm launching it from the command line, with command `wt` - winget terminal starts.

I really want to see one single instance of the terminal.

### Actual Behavior

And what's the problem - they have different settings.

![image](https://user-images.githubusercontent.com/50652041/146369253-3e4162a8-95a9-44a5-a3ab-ee70a28c1fb7.png)

**Comment by DHowett** [comment]
This is a WinGet issue -- it is not able to merge the two entries even though they do actually point to the same thing.

The `Microsoft.WindowsTerminal` moniker from the `winget` source installs the store package. The store ID `9N0...` installs the same package.

This is not the source of your two different copies of Terminal...
are you using Scoop or some other third-party package manager?

If your "two" copies of Terminal both live under `\Program Files\WindowsApps`, you are probably seeing #9452.

**Comment by elsaco** [comment]
@DHowett when using `winget install --source=winget` the package URL points to your GitHub releases:

```
Installer:
  Type: Msix
  Download Url: https://github.com/microsoft/terminal/releases/download/v1.11.3471.0/Microsoft.WindowsTerminal_1.11.3471.0_8wekyb3d8bbwe.msixbundle

```
When installing from the store is the URL the same as above?  `winget show 'Windows Terminal' --source=msstore` won't reveal the download link. Thx!

**Comment by DHowett** [comment]
Yes.

That msixbundle is the package we *download* from the store after uploading it for distribution!

When they're installed on the system, they are registered through the same mechanism. The system treats them identically.

**Comment by LeftTwixWand** [comment]
This screenshot shows, that there are two absolutely different Terminals exist. 
![image](https://user-images.githubusercontent.com/50652041/146369253-3e4162a8-95a9-44a5-a3ab-ee70a28c1fb7.png)

The first one stores its state in
`AppData\Local\Microsoft`
And another one - like all the other apps from Microsoft Store in the Packages folder.
`AppData\Local\Packages`

When I'm running the Terminal from the Start Menu - it runs the terminal from the Packages folder, like downloaded from the Microsoft Store:
![image](https://user-images.githubusercontent.com/50652041/146896776-5c81c250-34fa-42f2-b51a-099b9cdc0bfb.png)
![image](https://user-images.githubusercontent.com/50652041/146896506-3ec3420d-abd3-4dfd-bb4b-ce46bdffa9f1.png)
And the setting file loaded from the `Packages\LocalState` folder.
![image](https://user-images.githubusercontent.com/50652041/146897087-37185b4d-c4ff-4c8b-8d7d-51639488fa58.png)

But then I'm running the terminal through the command:
![image](https://user-images.githubusercontent.com/50652041/146897209-ef311041-592e-411f-ae62-0174b70a6c5a.png)
It opens absolutely other terminal with my custom configuration:
![image](https://user-images.githubusercontent.com/50652041/146897323-b33050f1-a6e1-4321-8ab3-9029d0788453.png)
And the setting file had been read from the `Local\Microsoft\Windows Terminal` Folder
![image](https://user-images.githubusercontent.com/50652041/146897573-0192bfa1-0a5c-4fe9-a6cd-ae069fa9bc33.png)

**Comment by DHowett** [comment]
Can you please report the _actual path to WindowsTerminal.exe_ when you're in this state? You can get it by running, from PowerShell:

```powershell
Get-Process WindowsTerminal | Select -Expand Path
```

As I mentioned in https://github.com/microsoft/terminal/issues/11960#issuecomment-996178368:

> If your "two" copies of Terminal both live under \Program Files\WindowsApps, you are probably seeing #9452.

If you have two copies running, and you run that command, _and they both point to the same EXE_: go read #9452.

I promise you that WinGet and the Microsoft Store install identical bits on your computer. :smile:

**Comment by LeftTwixWand** [comment]
I've run the terminals from the Start menu and through the `wt` command.
The running processes are the same. But they have different styles....

![image](https://user-images.githubusercontent.com/50652041/148977350-06c9605b-ef16-43d6-978c-e49ef75879a6.png)

**Comment by zadjii-msft** [comment]
Presumably, that means they're running with different identities. I'd reckon that the one run via `wt.exe` is running packaged, and the Start Menu one is unpackaged. You should be able to confirm this by opening the About dialog.

**Comment by DHowett** [comment]
Thanks for the report! This is a clear case of /dup #9452, as mentioned before. Please follow the remediation steps in #9452. Again, that's #9452.
