### ISSUE TITLE
[Settings] : User have to navigate through 'Open JSON file' control every time, While navigating in the 'Settings' window.

### ISSUE THREAD

**Issue by Saiteja341** [microsoft/terminal#11964]
### Windows Terminal version

1.12.3472.0

### Windows build number

22509.1011

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22509.1011)
App: Windows Terminal Preview

### Steps to reproduce

**Repro Steps: **

1.Open Windows Terminal.
2.Open Settings page using 'Ctr+,'
3.Select any 'list-item' from left pane.
4.Now Navigate in the page via tab key.
5.Observe the issue.

**User Experience: **
Users will get irritated here, if  User have to navigate through 'Open JSON file' control un-necessarily every time, While navigating in the 'Settings' window.

**Guideline reference**
https://www.w3.org/TR/WCAG21/#focus-order

Attachment : 
[User have to navigate to 'Open JSON file' everytime.zip](https://github.com/microsoft/terminal/files/7743354/User.have.to.navigate.to.Open.JSON.file.everytime.zip)

### Expected Behavior

  User should not have to navigate through 'Open JSON file' control every time, While navigating in the 'Settings' window.
-->On activating any 'Tab-item' , focus should land on first interactive element present in the right pane(Selected tab).

### Actual Behavior

User have to navigate through 'Open JSON file' control every time, While navigating in the 'Settings' window.
-->On activating any tab-item, focus is landing on 'Open JSON File' instead of moving on to 'First interactive' element present in the selected tab.

**Comment by zadjii-msft** [comment]
https://user-images.githubusercontent.com/18356694/153243392-f76748eb-735d-4409-acb0-c392a29a86dc.mp4

**Comment by Priyanka-Chauhan123** [comment]
Closing the bug as issue has been fixed.
