### ISSUE TITLE
No key stroke for AltGr + space (and other AltGr combinations)

### ISSUE THREAD

**Issue by EtienneSafa** [microsoft/terminal#11968]
Hi :-)

There is a whole community in France using Bépo keyboards both for dev and writing (https://bepo.fr/wiki/Accueil) and we identified an incompatibility with the AltGr layer in Windows Terminal (and some other softwares it seems). More specifically with '_' (underscore) which is placed in <AltGr + space>. A fex other combinations don't work but are not as critical as the underscore for use in terminal.

The Bépo driver is however able to send '_' with <AltGr + space> in the command line utility, powershell and ubuntu WSL when open independently. It's also working in the VSCode terminal sub-window.

**Comment by DHowett** [comment]
This sounds like /dup #11649, which is fixed in the coming release (should be out today!)
