### ISSUE TITLE
[Settings>Action] : Narrator is reading in-correct information as 'Read-only' for 'Shortcut' edit field.

### ISSUE THREAD

**Issue by Saiteja341** [microsoft/terminal#11962]
### Windows Terminal version

1.12.3472.0

### Windows build number

22509.1011

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22509.1011)
App: Windows Terminal Preview
Screen Reader: Narrator

### Steps to reproduce

**Repro Steps: **

1.Open Windows Terminal.
2.Open Settings page using 'Ctr+,'
3.Navigate to 'actions' list-item via 'Up/down' arrow keys & press enter.
4.Now Navigate to Actions present in the right pane via down arrow key.
5.Navigate to 'Edit' button present for any 'Action' via tab key & press enter.
6.A pop-up will gets open & navigate to 'Shortcut' edit field via tab key.
7.Observe the issue.

**User Experience: **
Users who rely on screen readers will get impacted here & gets disoriented, if Narrator reads in-correct information as 'Read-only' for 'Shortcut' edit field.

**Guideline Reference: **
https://www.w3.org/TR/WCAG21/#info-and-relationships

Attachments : 
[Narrator is reading in-correct information as 'Read-only' for 'Shortcut' edit field..zip](https://github.com/microsoft/terminal/files/7727262/Narrator.is.reading.in-correct.information.as.Read-only.for.Shortcut.edit.field.zip)

### Expected Behavior

As 'Shortcut' edit field is editable, Narrator should not read 'Shortcut' edit field as 'Read-only'.

### Actual Behavior

 Narrator is reading in-correct information as 'Read-only' for editable 'Shortcut' edit field.

**Comment by Priyanka-Chauhan123** [comment]
Closing the bug as issue has been fixed.
