### ISSUE TITLE
Support fractional font sizes.

### ISSUE THREAD

**Issue by rkitover** [microsoft/terminal#11972]
# Description of the new feature/enhancement

I would like to be able to use a fractional font size. With my current DPI scaling settings, setting the size to `10` makes it too small and `11` makes it too big. The configuration does not allow me to use a value such as `10.5` etc..

# Proposed technical implementation details (optional)

No idea, sorry.

**Comment by j4james** [comment]
I think what you're requesting is essentially the same thing as #6678.

**Comment by rkitover** [comment]
Yes, sorry I did not see that.
