### ISSUE TITLE
Transparency with custom background 

### ISSUE THREAD

**Issue by Zewwy** [microsoft/terminal#11979]
# Description of the new feature/enhancement

    As Title states, the Transparency feature doesn't seem to work when choosing a custom background. Is this possible? 

# Proposed technical implementation details (optional)
   
     I honestly wish I could provide coding solution here, however my dev skills are weeeeeeeak.

**Comment by zadjii-msft** [comment]
Some other discussion in #11558, you may be interested in the `backgroundImageOpacity` setting, which controls the opacity of the background image. So if you want the Terminal to have a 50% transparent background image, you probably want to set the `opacity` to `0` and the `backgroundImageOpacity` to .5
