### ISSUE TITLE
Conhost window padding is filled with the wrong color

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#11976]
### Windows Terminal version

Commit 8dfdfc4d6178baca8cd966167fbe6bc78b1fe7b7

### Windows build number

10.0.19041.1348

### Steps to reproduce

1. Open a cmd shell in conhost.
2. Execute the following command: `echo ^[[41m` (where `^[` is <kbd>Ctrl</kbd>+<kbd>[</kbd>).
3. Resize the window, making it just a few pixels wider and higher, but not enough to extend the number of columns or rows (we don't want to trigger a reflow of the buffer).

### Expected Behavior

I'd expect the additional window padding to be filled with the default background color (black in this case).

### Actual Behavior

The window padding is filled with the current background color (red in this case).

![image](https://user-images.githubusercontent.com/4181424/146431097-16b2ddda-f1a4-45aa-b871-6591202c91c1.png)

On my inbox version of conhost, only the bottom padding is filled in red - the screenshot above is from a recent OpenConsole build. But in my opinion, none of that padding area should be red, so both of them are wrong.

The problem, as I understand it, is that the implementation of the `GetDefaultBrushColors` method, which in conhost returns the active attributes rather than the default attributes.

https://github.com/microsoft/terminal/blob/bb71179a24ff186eab999676732afff8a345cc12/src/host/renderData.cpp#L110-L114

These attributes are then used in the renderer when initializing the default brushes in the `_UpdateDrawingBrushes` call.

https://github.com/microsoft/terminal/blob/dacff61f8862fa7c28f0244e74555cb2658455ad/src/renderer/base/renderer.cpp#L145

And in the GDI render engine, the default brushes are used to set the DC brush color and the hung app painting color.

https://github.com/microsoft/terminal/blob/95cc7d96257c4e7fb81fadee1e4a8e434a690be0/src/renderer/gdi/state.cpp#L300-L307

I'm almost certain that this is a mistake, though, and we should just be using the default attributes (i.e. `TextAttribute{}`). This is already the case in the Windows Terminal implementation of `GetDefaultBrushColors`.

https://github.com/microsoft/terminal/blob/bb71179a24ff186eab999676732afff8a345cc12/src/cascadia/TerminalCore/terminalrenderdata.cpp#L45-L48

And if we're going to be doing that everywhere, we could actually just get rid of the `GetDefaultBrushColors` method altogether.

**Comment by DHowett** [comment]
Wow, we definitely shouldn't do that. I wonder when we regressed...

**Comment by j4james** [comment]
It looks to me like it's been this way since the first open source release. I think the only change has been the red now showing on the right hand side as well as the bottom, I suspect because the renderer wasn't clipping correctly at one point.

You likely wouldn't have noticed the issue in the legacy v1 console because it only sized on exact character boundaries, so the margin area probably never showed.

Are there any objections to me submitting a PR to nuke the `GetDefaultBrushColors` method?

**Comment by DHowett** [comment]
Please do! No objections at all to the removal of code that reminds us of The Bad Old Days ™️
