### ISSUE TITLE
[Command prompt>Find] : Screen Reader users are not getting any information about 'Search results'.

### ISSUE THREAD

**Issue by Saiteja341** [microsoft/terminal#11973]
### Windows Terminal version

1.12.3472.0

### Windows build number

22509.1011

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22509.1011)
App: Windows Terminal Preview
Screen Reader : Narrator

### Steps to reproduce

**Repro Steps: **

1.Open Windows Terminal.
2.Open 'Command prompt' using 'Ctrl + shift + 2'.
3.Now open 'Find' pop-up using 'Ctrl + Shift + F'.
4.Type any keyword in 'Find' edit field & press enter.
4.Verify whether screen reader is narrating any information regarding available 'Search results' or not.

**User Experience: **
Users who rely on screen readers will get impacted here & may not know any information regarding search results, if screen reader stays silent on typing any keyword.

Guideline reference
https://www.w3.org/TR/WCAG21/#info-and-relationships

Attachment : 
[Narrator not reading any information reg search results.zip](https://github.com/microsoft/terminal/files/7743234/Narrator.not.reading.any.information.reg.search.results.zip)

### Expected Behavior

Screen reader should narrate information of  available 'Search results', on typing any keyword on 'Find' edit field.

### Actual Behavior

Screen reader is staying silent & not narrating any information regarding 'Search results'.

**Comment by zadjii-msft** [comment]
Admittedly, neither are visual users 🤣 The Terminal currently doesn't know how many results there are in the buffer. #8588 had a draft implementation for this nearly a year ago, but never got driven down. Once that (or #6319) is resolved, we can loop back on this and make sure that we add this as well.

**Comment by zadjii-msft** [comment]
Alternatively, we could just announce "yes there are results" or "no results found". That's probably the best we'll be able to do in the near term.

**Comment by zadjii-msft** [comment]
See also #12266 which did the same thing for the CmdPal

**Comment by v-rpundir** [comment]
Closing this bug as screen reader is announcing 'Results found' and 'No Results found' now.
