### ISSUE TITLE
Save/Load - Import/Export state of terminal

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/terminal#11986]
# Description of the new feature/enhancement
 - Able to save the current state of the terminal, restart doesn't require creating all those tabs with all those details.
 - Able to export state as JSON or some format, import them whenever wanted

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
Restoring the state (at least the open tabs and panes) should already be supported in preview version 1.12:
https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-12-release/#window-restoration

For other state-related features that are still in development, see issue #9800.

**Comment by zadjii-msft** [comment]
Yea, I'm gonna call this /dup #9800, thanks!
