### ISSUE TITLE
Wrong window focused after running batch file

### ISSUE THREAD

**Issue by RichardD2** [microsoft/terminal#11987]
### Windows Terminal version

1.11.2921.0

### Windows build number

22000.376

### Other Software

Windows Explorer

### Steps to reproduce

Set Terminal as the default terminal app in Windows 11.

Ensure there are no open Terminal windows.

Open any application - eg: Notepad.

Open Windows Explorer, and locate a batch file.

Double-click the batch file to execute it.

### Expected Behavior

The batch file executes, the Terminal window closes, and focus returns to the Windows Explorer window.

### Actual Behavior

The batch file executes, the Terminal window closes, and focus returns to the window which had the focus before the Windows Explorer window (eg: Notepad).

This is particularly noticeable if the windows involved are maximized.

**Comment by j4james** [comment]
It's possible this might be related to #10965 and/or #11601.

**Comment by zadjii-msft** [comment]
WOW that's wild. Okay this isn't actually a dupe, and this repros as recently as `10.0.22540.1000`

**Comment by zadjii-msft** [comment]
Hmm. I was just trying to repro this on 1.18.1041 and seemingly couldn't even get it to repro on 1.16.10262.0. Is this still broken for you? Or did this get fixed along the way/?

**Comment by RichardD2** [comment]
Looks like this got fixed - I can't reproduce it in 1.16.10262.0 on Windows 11 22H2 (22621.1555).
