### ISSUE TITLE
Background color looks different in powershell and standalone command prompt

### ISSUE THREAD

**Issue by dotnetshadow** [microsoft/terminal#11997]
### Windows Terminal version

1.11.34710

### Windows build number

10.0.19044.1415

### Other Software

.net core 6.0

### Steps to reproduce

1. Create a .net core 6 console application
2. Use the following snippet
```csharp
static void Main(string[] args)
        {

            Console.BackgroundColor = ConsoleColor.Blue;
            Console.Clear();
            Console.WriteLine("Hello World!");
}
```
3. The colors look different
![image](https://user-images.githubusercontent.com/296247/146765683-fc99f639-7712-430b-a21f-cec6af42a416.png)

### Expected Behavior

I expect the colors to match 

### Actual Behavior

The colors look different
![image](https://user-images.githubusercontent.com/296247/146765683-fc99f639-7712-430b-a21f-cec6af42a416.png)

**Comment by 237dmitry** [comment]
In my opinion it depends on the settings of the 16 base colors of the console.

**Comment by 237dmitry** [comment]
```
0..15 | Foreach-Object { Write-Host $([consoleColor] $_) -ForegroundColor $_ }
```

**Comment by dotnetshadow** [comment]
@237dmitry Thanks, I think you are right it somehow chooses the bright color in the colorscheme. It must map the color

**Comment by zadjii-msft** [comment]
Yep, this is due to the Terminal and Conhost using different color schemes by default. When you're using `ConsoleColor.Blue`, you're merely telling the console/terminal "please draw this text in whatever color you think blue is"
