### ISSUE TITLE
Feature to update itself

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/terminal#11993]
# Description of the new feature/enhancement
Some commands like, might be helpful:
 - `wt --update`(to download the lastest version) 
 - `wt --upgrade`(install the latest version available, may require internet, else from disk)
 - `wt --update --upgrade`(download and install the latest version)

# Proposed technical implementation details (optional)
Not technical details, but maybe I can help with its implementation.

**Comment by LuanVSO** [comment]
terminal is updated through the store automatically; it can also be done manually by clicking the "get updates" on the store.
 you can also run this command to update windows terminal from the command line using the [windows package manager](https://github.com/microsoft/winget-cli) [docs](https://docs.microsoft.com/windows/package-manager/)
```Powershell
 winget upgrade "Windows Terminal"
```

**Comment by zadjii-msft** [comment]
Yea, this is something that's already provided by the Store, and not something we're likely to ever roll ourselves. If there are any shortcomings (there are) I'd rather push on the Store team to help drive improvements for all Windows apps rather than roll our own one-off solution.
