### ISSUE TITLE
output from ColorTool broken on pwsh 7.2 + conpty

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#11992]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19044.1415

### Other Software

PowerShell 7.2.1
ColorTool

### Steps to reproduce

run
```pwsh
.\ColorTool.exe -c -x
```
in a powershell 7.2 windows terminal session

### Expected Behavior

![image](https://user-images.githubusercontent.com/43626415/146658030-fc8e458e-bf55-4c35-92f8-46cb55ee4e16.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/43626415/146658051-5b8b43f3-e5bf-42d7-9c19-762adbb12edb.png)

**Comment by j4james** [comment]
This just looks like the tab stops have been set to 6 rather than 8. Does it work any better if you reset the terminal with ```echo "`ec"``` before running ColorTool?

**Comment by LuanVSO** [comment]
> This just looks like the tab stops have been set to 6 rather than 8. Does it work any better if you reset the terminal with `` echo "`ec" `` before running ColorTool?

yep, just remembered that, sorry
