### ISSUE TITLE
Sinhala Language characters doesn't render correctly

### ISSUE THREAD

**Issue by ashen92** [microsoft/terminal#11998]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

Windows Package Manager v1.1.13405

### Steps to reproduce

Install Sinhala language pack.
Run the command "winget list"

### Actual Behavior

Sinhala Language characters doesn't render correctly

![image](https://user-images.githubusercontent.com/59907222/146809858-97dbe100-e329-4642-807e-617ea38e538c.png)

**Comment by zadjii-msft** [comment]
I suspect this is just another aspect of /dup #1472, or more broadly #8000
