### ISSUE TITLE
[Settings]: The Name property of a focusable element (Font Weight, Background image path, Background opacity, Padding, Delete) must not be null.

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#11996]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22504.1010

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22504.1010)
App: Windows Terminal Preview
Screen Reader: Narrator
Tool: Accessibility Insights for Windows Version 1.1.1741.1

### Steps to reproduce

**Repro Steps: **
1. Open Windows Terminal.
2. Open Settings page using 'Ctr+,'.
3. Run Accessibility Insights for Window on Command Prompt/PowerShell or other Profiles Appearance tab page, 

**User Experience: **
Screen Reader users will be impacted here as control name is not defined as result Screen Reader user will not be able to know the purpose of the control.

**Guideline Reference: **
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value

**Attachments:**
[The Name property of a focusable element is null.zip](https://github.com/microsoft/terminal/files/7743332/The.Name.property.of.a.focusable.element.is.null.zip)

### Expected Behavior

The Name property of a focusable element (Font Weight, Background image path, Background opacity, Padding, Delete) must not be null.

### Actual Behavior

The Name property of a focusable element (Font Weight, Background image path, Background opacity, Padding, Delete) is null.

**Comment by carlos-zamora** [comment]
@v-rpundir  This is now fixed in v1.12.10334.0. Can you please confirm?

**Comment by v-rpundir** [comment]
Hi @carlos-zamora The latest build I have is Terminal Preview 1.12.3472.0 so I will keep this work in my To-Do list for now and will check when the mentioned build is available here.

It will be better if you can provide us mentioned build us to verify the same.

**Comment by v-rpundir** [comment]
Closing as issue does not repro with AI now on Windows Terminal Preview Version: 1.13.10336.0
