### ISSUE TITLE
Context menu text in Spanish is too long,

### ISSUE THREAD

**Issue by crar01** [microsoft/terminal#11999]
Into folders, the context menu text in Spanish is too long,
is **"Abrir en Terminal de Windows en vista previa"**, perhaps it could be shorter, 
something like: "Abrir en Terminal de Windows" or other **shorter text.**

As the text is very long, it increases the size of the context menu horribly.

**Comment by zadjii-msft** [comment]
Presumably the "en vista previa" bit is to indicate that you've got the _Preview_ version of the Terminal installed, vs the stable version. I'd assume that the Release version is already "Abrir en Terminal de Windows". I'm open to suggestions here, but we'd need an idea for some string that's different than the one already being used by the stable version 😄

**Comment by DHowett** [comment]
This was fixed by #12090 :) (we shortened it, and it's getting re-localized!)
