### ISSUE TITLE
Keyboard bindings for terminal escape sequences.

### ISSUE THREAD

**Issue by Chaz6** [microsoft/terminal#12007]
# Description of the new feature/enhancement

I would like to be able to create key bindings for terminal escape sequences. For example, I would like to bind `ctrl+tab` to `\x1B[27;5;9~` and `ctrl+shift+tab` to `\x1B[27;6;9~`.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
You can already achieve this with a `sendInput` action (see PR #7249). For example, try adding the following comands in the _actions_ section of you _settings.json_ file:

```
{ "command": { "action": "sendInput", "input": "\u001b[27;5;9~" }, "keys": "ctrl+tab" },
{ "command": { "action": "sendInput", "input": "\u001b[27;6;9~" }, "keys": "ctrl+shift+tab" }
```

**Comment by Chaz6** [comment]
Thank you! Sorry if I missed it in the documentation.

**Comment by j4james** [comment]
No worries. I also originally thought it wasn't documented, but I see now there are actually some docs here:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#send-input

**Comment by Chaz6** [comment]
Thanks very much 😊
