### ISSUE TITLE
Install issue  error Code: 0x80070005

### ISSUE THREAD

**Issue by puskyer** [microsoft/terminal#12001]
Windows version 21H2 Build 19044.1415

having issues installing from Windows store getting  Code: 0x80070005

have tried
sfc /scannow
dism.exe /Online /Clenup-Image /RestoreHealth /StartComponentCleanup
wsreset

any help would be appreciated
thank you

**Comment by zadjii-msft** [comment]
These threads might be helpful: #4686, #7193

**Comment by puskyer** [comment]
Spent four hours trouble shooting, found that it was somewhere in the User registry, also had an issue installing pengwin wsl, even though Ubuntu wsl would install. Finally removed my profile and recreated it and all is working. Thank you

**Comment by DHowett** [comment]
Thanks for confirming!
