### ISSUE TITLE
Git Bash profile is flickering by clicking backspace

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/terminal#12018]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22523.1000

### Other Software

Git Bash version 2.33.0.windows.2

### Steps to reproduce

1. Add git bash

<details>
<summary>Configuration</summary>

```
{
    "colorScheme": "Solarized Dark",
    "commandline": "%PROGRAMFILES%/git/usr/bin/bash.exe -i -l",
    "guid": "{b9a64789-7265-438a-b009-754e4230cc91}",
    "hidden": false,
    "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
    "name": "Git Bash"
}
```

</details>

2. Click backspace

### Actual Behavior

It's flickers one time for every time I click backspace, when there's no character to delete:

https://user-images.githubusercontent.com/58633848/147131877-082e5ac2-6a48-415a-b3bb-e60653c49667.mp4

**Comment by ianjoneill** [comment]
This is expected behaviour, see #7200.

**Comment by DHowett** [comment]
Unfortunately, this is by design- git bash uses a hardcoded "visual bell" which flickers the screen. More info in /dup #7200

(Thanks @ianjoneill!)

**Comment by Aaron-Junker** [comment]
Thanks for pointing out the original issue.
