### ISSUE TITLE
SSH version problem

### ISSUE THREAD

**Issue by tsoftware-tedu** [microsoft/terminal#12011]
### Windows Terminal version

 1.11.2921.0

### Windows build number

10.0.19043.1288

### Steps to reproduce

If you use SSH protocol to connect to Alibaba cloud fortress, you will be prompted with the wrong version of the client

### Actual Behavior

(SSH-2.0-OpenSSH_for_Windows_8.1) SSH key-exchange error: Invalid major version number: SSH-2.0-OpenSSH_for_Windows_8.1

**Comment by zadjii-msft** [comment]
This doesn't necessarily sound related to the Windows Terminal - I'd suggest filing this over at https://github.com/PowerShell/Win32-OpenSSH/issues
