### ISSUE TITLE
Mouse is kept hidden if user switches to an other desktop

### ISSUE THREAD

**Issue by MPeti1** [microsoft/terminal#12015]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.18363.1316

### Steps to reproduce

0. Make sure that you have at least two virtual desktops in the task view windows menu
1. Open Windows Terminal
2. Type something into the terminal (at this point the mouse disappears)
3. Switch to an other virtual desktop with the key combination (usually Ctrl+Win+(Left|Right))

### Expected Behavior

Deactivation of the Windows Terminal window unhides the mouse

### Actual Behavior

Deactivation of the Windows Terminal window keeps the mouse hidden

**Comment by MPeti1** [comment]
Also, it might help you in finding the cause that I have been experiencing this since at least the last stable 1.8 version (1444?), but also I updated directly from that to the current version above

**Comment by j4james** [comment]
This sounds like issue #8958.

**Comment by MPeti1** [comment]
Oh, sorry. Duplicate.
