### ISSUE TITLE
"bellStyle": "none" does not always work

### ISSUE THREAD

**Issue by rkitover** [microsoft/terminal#12019]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22523.0

### Other Software

less 590 (Spencer V8 regular expressions)
native version from Chocolatey

### Steps to reproduce

Run less, e.g.:

```powershell
help -full select-string | less
```

### Expected Behavior

With `"bellStyle": "none"` in your profile settings, `less` should not make any beeps.

### Actual Behavior

`less` produces beeps. E.g., press `k` at the top of the document.

Other things do work as expected, for example:

```powershell
write "`a"
```

will produce beeps without `"bellStyle": "none"` but not with it.

**Comment by 237dmitry** [comment]
I added to `$profile` two environment variable for default pager (no need pipes for `Get-Help`) and its configuration. Parameter `Q` in `$env:LESS` turn off bell. 

```powershell
$Env:PAGER = 'less.exe'                                                        # works only in PowerShell 7+
$Env:LESS = '-QDs0.6$-Dd15$-Ps Page %db\: Press H for help or Q to quit '      # works in Windows PowerShell too.
```

**Comment by j4james** [comment]
This is probably because the native Windows version of less is using a Win32 API call to produce that sound ([MessageBeep](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebeep)), rather than a terminal bell, so it's not something that the terminal has any control over.

**Comment by rkitover** [comment]
@237dmitry

Thank you for this info, I too have `$env:PAGER` set in my `$profile`, that was just an example.

Unrelated, but I also have:

```powershell
$PSDefaultParameterValues = @{"help:Full"=$true}
```

to make `-full` a default parameter for `help`.

I completely forgot about `$env:LESS`, thank you very much for that.

@j4james

Your theory is correct, from the less source code:

```c
/*
 * Make a noise.
 */
        static void
beep(VOID_PARAM)
{
#if !MSDOS_COMPILER
        putchr(CONTROL('G'));
#else
#if MSDOS_COMPILER==WIN32C
        MessageBeep(0);
#else
        write(1, "\7", 1);
#endif
#endif
}
```

How common is it for a Win32 console application to produce a beep that way?

It is possible to override such API calls with a trampoline, and things of that nature. Whether that's worthwhile or not is a different question.

Unrelated, but does anyone know why `less -r` on Windows does not display ANSI colors?

**Comment by DHowett** [comment]
> How common is it for a Win32 console application to produce a beep that way?

Unfortunately, it is relatively common. 

I'd rather Terminal not get in the business of detouring functions in its spawned processes--it's detrimental to system security _and_ likely to cause trouble.

I'm gonna close this one out as Won't Fix, with my apologies, since there's little we can safely do to help processes along here. ☹️

As for the `less -r` question ... that's a good one, and I have no idea!

**Comment by rkitover** [comment]
One more question, what would be the right way to patch something like `less` to detect the newer terminal capabilities that can actually recognize a bell character?

As for the trampoline stuff, I could theoretically write a utility to launch the shell, e.g. `nobeeps pwsh ...`.

**Comment by j4james** [comment]
> One more question, what would be the right way to patch something like `less` to detect the newer terminal capabilities that can actually recognize a bell character?

I don't think there's an easy answer to that. Historically I think the Windows console has always supported the bell character, but Windows Terminal itself didn't support it prior to version 1.5.

Personally I would just assume it was always supported rather than trying to optimise for a specific range of WT versions where it didn't work at the expense of making things worse for everyone else.

**Comment by rkitover** [comment]
Is the "beep" system service related to the `MessageBeep()` Win32 API?

I have seen some instructions like [these](https://errorfixer.co/disable-cmd-powershell-beep-sounds/) that recommend running:

```powershell
set-service beep -startuptype disabled
```

, this does not work for me on win 11 dev channel preview, the service re-enables itself.

**Comment by rkitover** [comment]
@237dmitry 

I was studying the `less` man page, and I found some other very nice options, all of these work in the terminal:

```powershell
# Turn on these options for less:
#    -Q,--QUIET             # No bells.
#    -r,--raw-control-chars # Show ANSI colors.
#    -X,--no-init           # No term init, does not use alt screen.
#    -F,--quit-if-one-screen
#    -K,--quit-on-intr      # Quit on CTRL-C immediately.
#    --mouse                # Scroll with mouse wheel.
$env:LESS = '-Q$-r$-X$-F$-K$--mouse'
```

You might also like `-e` (quit on second scroll past EOF) or `-E` (quit on EOF).
