### ISSUE TITLE
[Settings] Window transparent without applying acrylic

### ISSUE THREAD

**Issue by alminisl** [microsoft/terminal#12014]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22000 

### Steps to reproduce

Settings > Default > Appearence > Transperancy

### Expected Behavior

Changing the Transparency toggles acrylic to enabled.

### Actual Behavior

![image](https://user-images.githubusercontent.com/6343910/146931378-266c7985-603f-4e6c-828f-7ea9a76a91e5.png)
Does not change to acrylic my window is transparent. 

On my work pc (with windows 10 and no dedicated GPU) everytime I change the transparency it does toggle the acrylic also. There is no way to have the terminal transparent in that case.  

Not 100% sure if that is intended, could not find a changelog about it.

**Comment by 237dmitry** [comment]
Acrylic depends on windows theme transparency (enabled or not). I don't use "Settings Page" because it changes formatting of settings.json. I prefer to make changes directly to the file.
```
....
    "profiles":
    {
        "defaults":
        {
            "closeOnExit": "always",
            "fontFace": "3270Narrow Nerd Font",
            "fontSize": 13,
            "fontWeight": "medium",
            "scrollbarState": "hidden",
            "useAcrylic": false,            //  "true" to enable acrylic
            "acrylicOpacity": 0.8,          //  Set opacity of acrylic 0..1.0
            "opacity": 100,                 //  Set opacity without acrilyc 0..100
            "padding": "8,8,8,8"
        },
....
```

**Comment by alminisl** [comment]
> Acrylic depends on windows theme transparency (enabled or not). I don't use "Settings Page" because it changes formatting of settings.json. I prefer to make changes directly to the file.
> 
> ```
> ....
>     "profiles":
>     {
>         "defaults":
>         {
>             "closeOnExit": "always",
>             "fontFace": "3270Narrow Nerd Font",
>             "fontSize": 13,
>             "fontWeight": "medium",
>             "scrollbarState": "hidden",
>             "useAcrylic": false,            //  "true" to enable acrylic
>             "acrylicOpacity": 0.8,          //  Set opacity of acrylic 0..1.0
>             "opacity": 100,                 //  Set opacity without acrilyc 0..100
>             "padding": "8,8,8,8"
>         },
> ....
> ```

How can I enable theme transparency on windows10? 

The one example above is from win 11 and it works fine, but for windows 10 I'm yet to figure out how to enable transparency without acrylic.

**Comment by 237dmitry** [comment]
> for windows 10

I have no way to check. `Ctrl+Shift + Mouse wheel` does not work too?

**Comment by alminisl** [comment]
> I have no way to check. Ctrl+Shift + Mouse wheel does not work too?

Nope, does not work.

**Comment by j4james** [comment]
Pure transparency (i.e. without acrylic) is currently only supported in Windows 11 because of a bug in XAML Islands. However there are plans to backport the fix to Windows 10. For more details, see https://github.com/microsoft/terminal/pull/11180#issuecomment-934259980.

**Comment by alminisl** [comment]
> Pure transparency (i.e. without acrylic) is currently only supported in Windows 11 because of a bug in XAML Islands. However there are plans to backport the fix to Windows 10. For more details, see [#11180 (comment)](https://github.com/microsoft/terminal/pull/11180#issuecomment-934259980).

Thank you, this answers my qustion!

**Comment by zadjii-msft** [comment]
Looks like what you're seeing is /dup #11555, which should be fixed in the next build ☺️
