### ISSUE TITLE
Cannot move tabs when Terminal is running as Administrator

### ISSUE THREAD

**Issue by mfogliatto** [microsoft/terminal#12017]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.318

### Steps to reproduce

1. Run Terminal as Administrator
2. Open a new tab so that the number of tabs opened is more than 1 (one)
3. Attempt to move tabs around the tab area

Doing the aforementioned steps in a regular Terminal (i.e. non administator) works as expected.

### Expected Behavior

Tabs should be moving around the tab area as desired (as shown in "Terminal - Non Admin.gif")

![Terminal - Non Admin](https://user-images.githubusercontent.com/2962955/147104478-ff9b4a5d-c941-4b11-905f-ff1918b2b3bf.gif)

### Actual Behavior

Tabs just don't move (as shown in "Terminal - Admin.gif")

![Terminal - Admin](https://user-images.githubusercontent.com/2962955/147104705-dbe6047e-7c89-435c-badb-e0c21ce5baf6.gif)

**Comment by 237dmitry** [comment]
This works if another tab also has elevated privileges and provided that it is launched from the terminal menu, i.e. a separate profile is configured in a special way (using third party utilities).

In other cases, the tab can be moved only using hotkeys (if configured) or from the "Command Palette"
`Ctrl+Shift+P` and `moveTab forward/backward`

**Comment by ZhaoMJ** [comment]
This is due to a known external bug. See /dup #3581

**Comment by zadjii-msft** [comment]
This is by design. Please make sure to [search for duplicates ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+reorder+tabs+administrator+)when filing new issues.  This is something that we can't support right now due to some platform limitations. Turns out, even if we tried to support reordering tabs while elevated, the application would actually just crash 😨. See #4874, #5564 and others for more details.

/dup #6893

**Comment by avraam-inside** [comment]
Hi!

I am an active user of a very cool third-party application - windows terminal. But this application has a bug, and the developers sent me here to support the topic at the request of the function.

The bug: https://github.com/microsoft/terminal/issues/12017 (Cannot move tabs when Terminal is running as Administrator)

Apparently, developers need to allow "dragging & dropping XAML elements in elevated applications". There is not and cannot be a single reason to prevent me, the user, from simply taking and moving the application tabs with the mouse.

Please implement this functionality for developers. As a last resort, make a warning return - it's bad to do that, etc., I'll calmly forget about this message, say "still give the opportunity to move tabs with the mouse" and I'll feel safe.

Don't push security policies to the point of absurdity, please.
