### ISSUE TITLE
Reload fails if profiles.json saved as UTF-8-BOM

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1201]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18912.1001]
Windows Terminal version (if applicable): commit b9d83ba, happened after commit 8a69be0
```

# Steps to reproduce

Save with Visual Studio IDE with utf-8 needed chars, or save as UTF-8-BOM with any kind of text editor.
Both make encode UTF-8-BOM.

# Expected behavior

Reloads correctly, works fine.

# Actual behavior

![image](https://user-images.githubusercontent.com/29011440/59274416-4361a800-8c95-11e9-83b7-7998fc5c6ac9.png)
And doesn't reload profiles. 

At commit id 2da5b0b, It actually reloaded it, and those utf-8 needed chars looked crazy..

**Comment by Summon528** [comment]
Related upstream issue https://github.com/open-source-parsers/jsoncpp/issues/842

**Comment by DHowett-MSFT** [comment]
This seems relatively easy for us to detect.
