### ISSUE TITLE
How to short the file path before the command ?The command line prefix or the file path is too long.

### ISSUE THREAD

**Issue by caesarding07** [microsoft/terminal#12036]
![image](https://user-images.githubusercontent.com/48940492/147400228-aa613e73-0777-4db2-8ea3-1153ad06f97f.png)
As you can see, the file path before my command is **too long**. So I can't put any of my commands **on a line** in my little window. Can someone help me solve this problem?

**Comment by 237dmitry** [comment]
Imho, the best way is write your own prompt function in `$profile`. Something like:
```
function prompt
{
   "$([char]27)[38;5;31m$($PWD.Path)`n$([char]27)[0m PS $([char]27)[38;5;41m> $([char]27)[0m"
}
```
This is a very simple example
