### ISSUE TITLE
[Question] - Font isn't rendered entirely (line chopped off at top)

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/terminal#12037]
### Steps to reproduce

Originally reported [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1401).
Regardless of the font used, @romanlarrosa is always seeing the font chopped off a bit at the top. Can someone give him some pointers on how to resolve this?

![](https://user-images.githubusercontent.com/58295696/145565237-dc9c4748-d921-4b69-9716-6de41c99cb7e.png)

### Expected Behavior

A fully rendered font

### Actual Behavior

 A non-fully visible font (line height is lower than the font height)

**Comment by JanDeDobbeleer** [comment]
@romanlarrosa can you provide some more details when asked?

**Comment by 237dmitry** [comment]
This is a font problem or rather characters `[char[]] (57524,57526)`. Try other nerd fonts.

**Comment by romanlarrosa** [comment]
Using "Cascadia Code PL" fixes the problem. Thank you! 
![image](https://user-images.githubusercontent.com/58295696/147467270-1521d966-256a-4bbd-8001-e5e758823cc5.png)
