### ISSUE TITLE
Multiple artifacts in font rendering

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#12035]
### Windows Terminal version

1.11.3471.0

### Steps to reproduce

Open Terminal.

### Expected Behavior

Clear font rendering with no artifacts.

### Actual Behavior

![Artifacts](https://user-images.githubusercontent.com/61304281/147388801-ab172689-189e-4200-aaf0-0cf884d2667a.png)

Do I need to explain this further? Functionality should come hand in hand with design.

**Comment by DHowett** [comment]
Looks like the account that originated this post has been deleted. These issues are tracked elsewhere.
