### ISSUE TITLE
I can't set Windows Terminal to be my default console because I can't find `Default Terminal Application`.

### ISSUE THREAD

**Issue by timelessnesses** [microsoft/terminal#12034]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Install Windows Terminal on Windows 10 and go to settings and try to find default terminal application.  
(I can't find it anywhere)
![image](https://user-images.githubusercontent.com/59832159/147382032-28dc2c31-3e95-4858-920c-745a0db20338.png)

### Expected Behavior

When enter settings in Windows Terminal and enter Startup tab there should be a default terminal application or something to set my windows terminal to default terminal

### Actual Behavior

![image](https://user-images.githubusercontent.com/59832159/147382047-fe98f149-f044-440b-a0fa-02c8eee8ac0b.png)
It isn't there

**Comment by 237dmitry** [comment]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup

> This feature is only available when running Windows 10 Insider Program Dev Channel or Windows 11

**Comment by DHowett** [comment]
Correct. This setting only exists on Windows 11 right now.
