### ISSUE TITLE
Global keyboard shortcut for launching Terminal

### ISSUE THREAD

**Issue by amzon-ex** [microsoft/terminal#12047]
# Description of the new feature/enhancement

The right-click context menu now already includes a 'Open in Windows Terminal' option by default, which is super handy. Is it possible to attach a global keybind to this action which does the same? I use AutoHotkey to (patchily) achieve a similar behaviour, but an integrated keybind would be nice...

# Proposed technical implementation details (optional)

(If this is possible...)
The keybind respects the context as well:
  - If pressed from a window which doesn't have a 'path' per se, or the path is irrelevant (like a CLSID location) then open at default starting directory.
  - If pressed in a window with a natural 'path', open at that location. 
  - If terminal already active, bring it to focus.
  - If in focus, minimize.

Thanks for considering!

**Comment by zadjii-msft** [comment]
The Terminal actually already _does_ have a global hotkey setting - check out the [`globalSummon` action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands)

The other half of you request is presumably tracked over in #10202

/dup #10202
/dup #653

and there's other related issues tracked in #8888

**Comment by Chealer** [comment]
Thanks @zadjii-msft 
`globalSummon` ("Show/Hide the Terminal window") does allow most of what this requests, but as its label indicates, it does not respect the first 2 points. The first is tracked in issue #9996. The second is indeed at least related to #10202.
