### ISSUE TITLE
vim Background Color Not Always Displaying Correctly (but works in conhost.exe)

### ISSUE THREAD

**Issue by matrdr** [microsoft/terminal#12049]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

vim 8.1 (inside WSL)

### Steps to reproduce

Open `vim` in WSL. A background color different to the terminal's background color shall be set (e.g. by using a colorscheme).
When trying the command `:ls` or `:hi` it is visible that the terminal's background color is visible in places where it should not be.

When trying to reproduce this using `conhost.exe` (the good old terminal) instead of Windows Terminal you may notice that the background works as expected there. Therefore it seems that something is handled differently in Windows Terminal. 

### Expected Behavior

![image](https://user-images.githubusercontent.com/45005058/147497687-fc67d7c1-b7e4-4bde-b64c-bf41a92b441d.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/45005058/147497707-b1d47d28-7c7e-445f-988b-b29d3e23256f.png)

**Comment by zadjii-msft** [comment]
Hmmmm. I'm guessing that you've got the background color in conhost set to the white color scheme entry, right? Conhost (traditionally) only allowed users to set the background color to one of the 16 colors of the color scheme. The Terminal however, more correctly emulates a real terminal, and has a separate color entry for the "default background color", which is defaulted to a black color. 

You can probably get the Terminal to look like you're old conhost window by setting `defaultBackground` to `#ffffff` or something similar. Either set it just for your WSL profile, or in the `profiles.defaults` block

**Comment by matrdr** [comment]
In both cases the default background color is black. It is overridden by an option in vim, which seems to be interpreted differently in both terminals.

**Comment by zadjii-msft** [comment]
> It is overridden by an option in vim, which seems to be interpreted differently in both terminals.

which option exactly?

**Comment by matrdr** [comment]
For this example I used the `colorscheme morning` command in vim to change its colorscheme. I do not exactly know, what this sets in the terminal.

**Comment by j4james** [comment]
I think the is because the Windows Terminal VT implementation doesn't handle bce (background color erase) correctly for line feeds at the bottom of the screen.

If you look at the debug tap for this, it's outputting newlines to make space for the two lines after `ls`, expecting them to be filled with the default background color. But Windows Terminal doesn't do that.

I'm almost sure we already have an issue for this somewhere.

**Comment by j4james** [comment]
The issue I was thinking of is #11867, but I suspect there are others as well. I just tried hacking an update to `Terminal::_AdjustCursorPosition` which fills the new line when scrolling, and that seemed to fix both #11867 and this issue.

**Comment by DHowett** [comment]
I owe y'all going back and deduplicating all these bugs. Thanks @j4james :smile:

**Comment by zadjii-msft** [comment]
We believe this was fixed in Terminal v1.13, in #11982. @matrdr would you mind confirming?

**Comment by matrdr** [comment]
> We believe this was fixed in Terminal v1.13, in #11982. @matrdr would you mind confirming?

Seems fixed! Good job, guys!
