### ISSUE TITLE
Separate MRU tab switching and previous/next tab

### ISSUE THREAD

**Issue by paveldvorak5** [microsoft/terminal#12059]
# Description of the new feature/enhancement
I'd like to have separate MRU tab switching using Ctrl + Tab and previous / next tab commands using for ex. shift + left/right.
If you enable MRU tab switching in the settings, next tab command (for ex. shift + right) will choose a "random" tab, not the next tab in the tab strip I was expecting.

# Proposed technical implementation details (optional)
Separate settings for next/previous tab in the tab strip and separate MRU tab switching controls using Ctrl + Tab by default.

**Comment by zadjii-msft** [comment]
I'm pretty sure you can achieve this today with the `tabSwitcherMode` param for [`nextTab `and `prevTab`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#open-next-tab)

```jsonc

        { "command": { "action": "nextTab", "tabSwitcherMode": "mru" }, "keys": "ctrl+tab" },
        { "command": { "action": "nextTab", "tabSwitcherMode": "disabled" }, "keys": "shift+right" },
        { "command": { "action": "prevTab", "tabSwitcherMode": "disabled" }, "keys": "shift+left" },
```

should get what you want

**Comment by paveldvorak5** [comment]
Yes, it works. Thanks
