### ISSUE TITLE
When running As Administrator write to some files fails with access is denied error

### ISSUE THREAD

**Issue by yudindm** [microsoft/terminal#12058]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.18362.0

### Steps to reproduce

1. Log In to Windows using account wich is a member of the built in Administrators group

2. Start Windows Terminal As Administrator
    Window Terminal default shell is PowerShell 7 (version 7.1.0)

3. Run command
    ~~~
    "`r`n# xxx" | Out-File "C:\windows\System32\drivers\etc\hosts" -Append
    ~~~

### Expected Behavior

A new line will be added to _hosts_ file withot any error

### Actual Behavior

Command returns error
`Out-File: Access to the path 'C:\windows\System32\drivers\etc\hosts' is denied.`

Note:
If I run the same command but in pwsh without Windows Terminal it completes successfully.

**UPDATE**
After upgrading Windows to version 10.0.19042 behavior did not change.

**UPDATE 2**
I installed Windows Terminal Preview 1.12.3472.0 - behavior did not change.

**Comment by 237dmitry** [comment]
![11](https://user-images.githubusercontent.com/78153320/147567303-4867f4b7-cf00-457a-8582-9adf124f0ecb.png)

**Comment by yudindm** [comment]
It doesn`t work for me in Windows Terminal. 

![image](https://user-images.githubusercontent.com/8970838/147573161-f19a8fd7-734f-434c-9278-b38749a5ffbf.png)

**Comment by elsaco** [comment]
@yudindm there is no security shield displayed in your terminal when running as admin. Usually there's an icon in upper left corner indicating this is an elevated session. Did you disable it? Couldn't replicate your issue on my system:


![hosts_append_test](https://user-images.githubusercontent.com/3933920/147584661-c9538cd0-ae0b-4238-b942-ed8375cf6f0c.png)

**Comment by eryksun** [comment]
There's no UAC shield if UAC is disabled by setting "EnableLUA" to 0 in  "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System", but in that case an admin should have full access to the "hosts" file.  

@yudindm, check the available and enabled groups via `whoami.exe /groups` to ensure that the administrators group (S-1-5-32-544) is present and enabled for granting access. It should be, else PowerShell shouldn't be displaying "Administrator: " in the session title.

**Comment by 237dmitry** [comment]
> There's no UAC shield if UAC is disabled by setting "EnableLUA" to 0

This is not quite true. Elevated rights with the help of third-party utilities can be obtained for one tab, while the terminal itself remains as before and remains without a shield, but the title of an elevated tab has "Administrator: " prefix.

![gsudo](https://user-images.githubusercontent.com/78153320/147592045-497dc1e1-a8f9-40cf-85ba-54943c2796ab.png)

**Comment by eryksun** [comment]
> This is not quite true. Elevated rights with the help of third-party utilities can be obtained for one tab, while the terminal itself remains as before and remains without the shield icon, but the title of an elevated tab has "Administrator: " prefix.

Maybe you read too much into my statement. Your point doesn't make what I said "not quite true". I didn't say that disabling UAC was the only way that the UAC shield might be missing even though the terminal or a tab has administrator access. Your point is generally interesting, but it isn't relevant here because the issue states "Start Windows Terminal As Administrator".

**Comment by 237dmitry** [comment]
>  because the issue states "Start Windows Terminal As Administrator"

Ok

**Comment by zadjii-msft** [comment]
Also, the shield icon was only added in 1.12, so it's totally reasonable that it's not present for OP on a 1.11 build. 

> If I run the same command but in pwsh without Windows Terminal it completes successfully.

That's the bit that confuses me here - the only thing that would be different about these scenarios is the Terminal running with package identity, in addition to being elevated. But that _shouldn't_ affect the ability to write that file... especially since it Works On My Machine<sup>tm</sup>.

**Comment by yudindm** [comment]
@eryksun
> There's no UAC shield if UAC is disabled by setting "EnableLUA" to 0 in "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", but in that case an admin should have full access to the "hosts" file.

```
PS C:\Users\yudindm> (Get-ItemProperty HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System).EnableLUA
1
```
> check the available and enabled groups via whoami.exe /groups to ensure that the administrators group (S-1-5-32-544) is present and enabled for granting access

![image](https://user-images.githubusercontent.com/8970838/148177816-ff55e74d-8d91-4bf4-9d8d-5d854ba05cf1.png)

I'm using Russian Windows edition and to prevent localized output here I'm using commands that don't have localized output

```
PS C:\Users\yudindm> ([Security.Principal.WindowsIdentity]::GetCurrent()).Claims | ?{ $_.Value -eq 'S-1-5-32-544' }

Issuer         : AD AUTHORITY
OriginalIssuer : AD AUTHORITY
Properties     : {[http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority, NTAuthority]}
Subject        : System.Security.Principal.WindowsIdentity
Type           : http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid
Value          : S-1-5-32-544
ValueType      : http://www.w3.org/2001/XMLSchema#string


PS C:\Users\yudindm> $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
PS C:\Users\yudindm> $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
True
```


@zadjii-msft 
> the only thing that would be different about these scenarios is the Terminal running with package identity, in addition to being elevated But that shouldn't affect the ability to write that file... especially since it Works On My Machinetm.

It shurely work**ed** on My Machine also some time ago.
Since then I probaby installed a Windows update or a Windows Terminal update wich broke expected behavior.

**Comment by eryksun** [comment]
The administrators group is enabled in the current access token. That should be enough. By default, the "hosts" file doesn't have a mandatory label that restricts write access to high integrity level. To be extra certain, check to make sure the current security context has the high mandatory level group "S-1-16-12288" using `whoami.exe /groups` or Sysinternals Process Explorer. UAC shouldn't create a token with the administrators group enabled that's not elevated, but weird things happen. (The opposite is possible, i.e. high integrity level without administrator access.) Also check the discretionary and mandatory security of the "hosts" file via `icacls.exe "%SystemRoot%\System32\drivers\etc\hosts"`. The latter includes the mandatory label and policy, if any. I don't know how to inspect the mandatory label in PowerShell.

**Comment by yudindm** [comment]
@eryksun 
> high mandatory level group "S-1-16-12288"

Yes. It's present.

> Also check the discretionary and mandatory security of the "hosts" file
![image](https://user-images.githubusercontent.com/8970838/148740303-3b4ca5a3-2982-4cfe-b7c1-a90a38e932ff.png)

Because all group names in the output are in Russian below I translated them in English:
NT AUTHORITY\SYSTEM:(I)(F)
BUILTIN\Administrators:(I)(F)
BUILTIN\Users:(I)(RX)
APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES:(I)(RX)

**Comment by eryksun** [comment]
Everything looks normal. Maybe some entry is a conditional access control entry, which icacls doesn't dupport. SDDL does. Try `(get-acl "$env:SystemRoot\System32\drivers\etc\hosts").Sddl`.

If you have access to a debugger, such as the WinDbg store app, attach to the affected PowerShell instance and run `!token` to display the contents of the process access token.

**Comment by yudindm** [comment]
@eryksun 

> Try (get-acl "$env:SystemRoot\System32\drivers\etc\hosts").Sddl.

```
PS C:\Users\yudindm> (get-acl "$env:SystemRoot\System32\drivers\etc\hosts").Sddl
O:SYG:SYD:AI(A;ID;FA;;;SY)(A;ID;FA;;;BA)(A;ID;0x1200a9;;;BU)(A;ID;0x1200a9;;;AC)(A;ID;0x1200a9;;;S-1-15-2-2)
```

> attach to the affected PowerShell instance and run !token to display the contents of the process access token.

```
0:021> !token
Thread is not impersonating. Using process token...
TS Session ID: 0x2
User: S-1-5-21-596323086-39334571-915851860-1198
User Groups:
 00 S-1-5-21-596323086-39334571-915851860-513
    Attributes - Mandatory Default Enabled 
 01 S-1-1-0
    Attributes - Mandatory Default Enabled 
 02 S-1-5-21-1209789062-3569530313-330599132-1006
    Attributes - Mandatory Default Enabled 
 03 S-1-5-21-1209789062-3569530313-330599132-1008
    Attributes - Mandatory Default Enabled 
 04 S-1-5-32-544
    Attributes - Mandatory Default Enabled Owner 
 05 S-1-5-32-559
    Attributes - Mandatory Default Enabled 
 06 S-1-5-32-545
    Attributes - Mandatory Default Enabled 
 07 S-1-5-14
    Attributes - Mandatory Default Enabled 
 08 S-1-5-4
    Attributes - Mandatory Default Enabled 
 09 S-1-5-11
    Attributes - Mandatory Default Enabled 
 10 S-1-5-15
    Attributes - Mandatory Default Enabled 
 11 S-1-5-5-0-2388438
    Attributes - Mandatory Default Enabled LogonId 
 12 S-1-2-0
    Attributes - Mandatory Default Enabled 
 13 S-1-5-21-596323086-39334571-915851860-4543
    Attributes - Mandatory Default Enabled 
 14 S-1-5-21-596323086-39334571-915851860-3204
    Attributes - Mandatory Default Enabled 
 15 S-1-18-1
    Attributes - Mandatory Default Enabled 
 16 S-1-5-21-596323086-39334571-915851860-4602
    Attributes - Mandatory Default Enabled GroupResource 
 17 S-1-5-21-596323086-39334571-915851860-5113
    Attributes - Mandatory Default Enabled GroupResource 
 18 S-1-5-21-596323086-39334571-915851860-4190
    Attributes - Mandatory Default Enabled GroupResource 
 19 S-1-5-21-596323086-39334571-915851860-5105
    Attributes - Mandatory Default Enabled GroupResource 
 20 S-1-5-21-596323086-39334571-915851860-1399
    Attributes - Mandatory Default Enabled GroupResource 
 21 S-1-5-21-596323086-39334571-915851860-3210
    Attributes - Mandatory Default Enabled GroupResource 
 22 S-1-5-21-596323086-39334571-915851860-2841
    Attributes - Mandatory Default Enabled GroupResource 
 23 S-1-5-21-596323086-39334571-915851860-2843
    Attributes - Mandatory Default Enabled GroupResource 
 24 S-1-5-21-596323086-39334571-915851860-3213
    Attributes - Mandatory Default Enabled GroupResource 
 25 S-1-5-21-596323086-39334571-915851860-3179
    Attributes - Mandatory Default Enabled GroupResource 
 26 S-1-5-21-596323086-39334571-915851860-3219
    Attributes - Mandatory Default Enabled GroupResource 
 27 S-1-5-21-596323086-39334571-915851860-4379
    Attributes - Mandatory Default Enabled GroupResource 
 28 S-1-5-21-596323086-39334571-915851860-4561
    Attributes - Mandatory Default Enabled GroupResource 
 29 S-1-5-21-596323086-39334571-915851860-1396
    Attributes - Mandatory Default Enabled GroupResource 
 30 S-1-5-21-596323086-39334571-915851860-5146
    Attributes - Mandatory Default Enabled GroupResource 
 31 S-1-5-21-596323086-39334571-915851860-4196
    Attributes - Mandatory Default Enabled GroupResource 
 32 S-1-5-21-596323086-39334571-915851860-4220
    Attributes - Mandatory Default Enabled GroupResource 
 33 S-1-5-21-596323086-39334571-915851860-4130
    Attributes - Mandatory Default Enabled GroupResource 
 34 S-1-5-21-596323086-39334571-915851860-4549
    Attributes - Mandatory Default Enabled GroupResource 
 35 S-1-5-21-596323086-39334571-915851860-3310
    Attributes - Mandatory Default Enabled GroupResource 
 36 S-1-5-21-596323086-39334571-915851860-4565
    Attributes - Mandatory Default Enabled GroupResource 
 37 S-1-16-12288
    Attributes - GroupIntegrity GroupIntegrityEnabled 
Primary Group: S-1-5-21-596323086-39334571-915851860-513
Privs: 
 00 0x000000005 SeIncreaseQuotaPrivilege          Attributes - 
 01 0x000000008 SeSecurityPrivilege               Attributes - 
 02 0x000000009 SeTakeOwnershipPrivilege          Attributes - 
 03 0x00000000a SeLoadDriverPrivilege             Attributes - 
 04 0x00000000b SeSystemProfilePrivilege          Attributes - 
 05 0x00000000c SeSystemtimePrivilege             Attributes - 
 06 0x00000000d SeProfileSingleProcessPrivilege   Attributes - 
 07 0x00000000e SeIncreaseBasePriorityPrivilege   Attributes - 
 08 0x00000000f SeCreatePagefilePrivilege         Attributes - 
 09 0x000000011 SeBackupPrivilege                 Attributes - 
 10 0x000000012 SeRestorePrivilege                Attributes - 
 11 0x000000013 SeShutdownPrivilege               Attributes - 
 12 0x000000014 SeDebugPrivilege                  Attributes - Enabled 
 13 0x000000016 SeSystemEnvironmentPrivilege      Attributes - 
 14 0x000000017 SeChangeNotifyPrivilege           Attributes - Enabled Default 
 15 0x000000018 SeRemoteShutdownPrivilege         Attributes - 
 16 0x000000019 SeUndockPrivilege                 Attributes - 
 17 0x00000001c SeManageVolumePrivilege           Attributes - 
 18 0x00000001d SeImpersonatePrivilege            Attributes - Enabled Default 
 19 0x00000001e SeCreateGlobalPrivilege           Attributes - Enabled Default 
 20 0x000000021 SeIncreaseWorkingSetPrivilege     Attributes - 
 21 0x000000022 SeTimeZonePrivilege               Attributes - 
 22 0x000000023 SeCreateSymbolicLinkPrivilege     Attributes - 
 23 0x000000024 SeDelegateSessionUserImpersonatePrivilege  Attributes - 
Auth ID: 0:247237
Impersonation Level: Anonymous
TokenType: Primary
Is restricted token: no.
SandBoxInert: 0
Elevation Type: 2 (Full)
Mandatory Policy: TOKEN_MANDATORY_POLICY_NO_WRITE_UP
Integrity Level: S-1-16-12288
    Attributes - GroupIntegrity GroupIntegrityEnabled 
Process Trust Level:   LocalDumpSid failed to dump Sid at addr 00000083aaa7aa68, 0xC0000078; try own SID dump.
s-1-0
    Attributes - 
Token Virtualized: Disabled
UIAccess: 0
IsAppContainer: 0
Security Attributes Information:
 00 Attribute Name: TSA://ProcUnique
    Value Type	: TOKEN_SECURITY_ATTRIBUTE_TYPE_UINT64
    Value[0]	: 806
    Value[1]	: 116736319
Device Groups:
```

**Comment by yudindm** [comment]
I don't have any clue for what could have happend but now it works as expected again.
