### ISSUE TITLE
Exiting Windows Terminal Triggers System Error

### ISSUE THREAD

**Issue by JuliusDegesys** [microsoft/terminal#12068]
Relatively consistently (although not 100% of the time), exiting the windows terminal from WSL2 - Ubuntu 20.04 triggers the following popup:
Exception Processing Message - 0xc0000005 - Unexpected Parameters:
![image](https://user-images.githubusercontent.com/3232103/147705481-e38e923d-8a04-4e1a-9ba2-0804c80d0c32.png)

This happens when I type in `exit` or when I click on the top right X

I'm happy to help troubleshoot; however, I'm not really a power Windows user. Any guidance would be appreciated. Thanks!

I'm running Windows Terminal version 1.11.34710.0.

Windows specifications:
Edition: Windows 10 Pro
Version: 20H2
OS Build: 19042.1415
Experience: Windows Feature Experience Pack 120.2212.3920.0

**Comment by zadjii-msft** [comment]
That's... wild. Never seen a MessageBox that looks quite like that in my time. Maybe we'd be able to capture whatever's causing this with a Feedback Hub trace: /feedback

**Comment by JuliusDegesys** [comment]
https://aka.ms/AAfdpbh

**Comment by zadjii-msft** [comment]
Hey there was a whole bunch of crash-on-exit fixes that we did in the last few months. Are you still seeing this on 1.15/? If so, an fresh Feedback hub dump might be needed (considering the volume of teardown code that changed)
