### ISSUE TITLE
Display last used command as tab name

### ISSUE THREAD

**Issue by Timsonrobl** [microsoft/terminal#12060]
# Description of the new feature/enhancement

When running multiple tabs of Windows Terminal with long running tasks with extensive console output it's easy to forget which tab is running which task. Sometimes you can scroll all the way up to see the command but sometimes it's already gone, and if terminal is reused for next task you have to find it in the middle of thousand lines of output. You can currently manually change tab name to reduce confusion, but it can quickly become a bother if you need to run many tasks and monitor output.
Adding profile option for tab names to automatically reflect last used command in each tab would greatly improve user expirience in such cases.

# Proposed technical implementation details (optional)

Add profile option for tab names to reflect last used command  in each tab by default instead of profile name.

**Comment by Timsonrobl** [comment]
Also another implementation option, probably harder to implement but even better: option to change tab name at runtime to a reflect last used command in the tab rename interface (maybe a button in a text field, next to the cross icon that cancels rename operation).

**Comment by ysc3839** [comment]
So what is "last used command"?
The "Command line" option in profile setting page?
![image](https://user-images.githubusercontent.com/12028138/147648938-a8be0aaa-04ce-4808-b0de-52409a42549a.png)

**Comment by Timsonrobl** [comment]
@ysc3839 no, I mean last command used inside shell
![image](https://user-images.githubusercontent.com/9917883/147656594-74256995-ed40-426c-b54a-718a937aac43.png)

**Comment by eryksun** [comment]
A feature such as this would best addressed in the shell, maybe with some hook for GNU Readline in bash or PSReadLine in PowerShell. Bear in mind that in many cases the console's command history doesn't even have the last line of input that was read because many console applications and shells read low-level key presses or characters, with line-input mode disabled.

**Comment by ysc3839** [comment]
This should provided by the shell instead of terminal.
I would suggest using [Oh My Zsh](https://ohmyz.sh/). It has this feature out of box.

**Comment by Timsonrobl** [comment]
> This should provided by the shell instead of terminal. I would suggest using [Oh My Zsh](https://ohmyz.sh/). It has this feature out of box.

Thank you, I'll try that. But that would only apply when working in WSL, what are the options in Windows shells like cmd and PowerShell?

**Comment by KalleOlaviNiemitalo** [comment]
Doesn't cmd already change the title when you run a command? Although it also restores the title after the command finishes, and I suppose you don't want that.

For PowerShell, you could do one of:

* Set the window title when each command finishes.
  ```PowerShell
  function prompt() {
      $Host.UI.RawUI.WindowTitle =  (get-history)[-1].CommandLine
      "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
  }
  ```
* Set the window title whenever PSReadLine reads a line.
  ```PowerShell
  function PSConsoleHostReadLine {
      Microsoft.PowerShell.Core\Set-StrictMode -Off
      ($Host.UI.RawUI.WindowTitle = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext))
  }
  ```
* Wait for <https://github.com/PowerShell/PowerShell/issues/14484>.

**Comment by Timsonrobl** [comment]
> * Set the window title whenever PSReadLine reads a line.
>   ```powershell
>   function PSConsoleHostReadLine {
>       Microsoft.PowerShell.Core\Set-StrictMode -Off
>       ($Host.UI.RawUI.WindowTitle = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext))
>   }
>   ```

@KalleOlaviNiemitalo thank you so much, option 2 for PowerShell was exactly what I was looking for!

**Comment by zadjii-msft** [comment]
Yea, as others have noted, this is something that should ideally be handled by your shell, since the Terminal itself doesn't really know the difference between you "running a command" or just typing a _new line in vim_ 😄
