### ISSUE TITLE
oh my posh renders incorrectly the 1st line

### ISSUE THREAD

**Issue by siferati** [microsoft/terminal#12063]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22000.0

### Other Software

Oh My Posh inside WSL

### Steps to reproduce

Install some oh my posh theme inside wsl

### Expected Behavior

oh my posh theme displays corretly

### Actual Behavior

oh my posh theme is broken for the first line. But the next lines display correctly.

Notice in the image how the first line displays incorrectly, but all the next lines are correct:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/15384781/147616731-f761c28b-ae33-450a-a51b-eb37610aeacd.png">

**Comment by j4james** [comment]
I suspect this is same problem as #8341.

**Comment by siferati** [comment]
> I suspect this is the same problem as #8341.

Thanks, it's the same problem. Installing WSL from the MS Store as per https://github.com/microsoft/terminal/issues/8341#issuecomment-940657032 fixed it for me.
