### ISSUE TITLE
Feature Request for Drop Shadows and other Character Edge style options for text to contrast bright backgrounds

### ISSUE THREAD

**Issue by deonizm** [microsoft/terminal#12066]
# Description of the new feature/enhancement
Option for Character Edge styles, like None, **Drop Shadow**, Raised, Depressed, and Outline for text as an alternative appearance effect which would enhance readability on bright backgrounds. A subtle, but noticeable feature that adds flexibility.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I think most of these effects can probably be achieved with a custom pixel shader. For example, see the sample outline pixel shader that was added in PR #9646.

**Comment by zadjii-msft** [comment]
Yea, I'd recommend playing around with the shaders to achieve the specific effect you desire. If you come up with a decent implementation for any of those effects, we'd love a PR to add them to our list of [sample shaders](https://github.com/microsoft/terminal/tree/main/samples/PixelShaders)!
