### ISSUE TITLE
Missing license header in a few files

### ISSUE THREAD

**Issue by Keno** [microsoft/terminal#12062]
The repository contains a few files that are missing indications as to their license status.
In particular:

- `dep/Console/*.h`
- `dep/NT/ntioapi_x.h`
- `dep/Win32K/winuserp.h`

It would help to have an explicit indication that the MIT license applies to these files to pacify overly sensitive legal departments :).

**Comment by zadjii-msft** [comment]
This is an interesting case, since those couple files are actually just stubs of internal files that we need to compile in the OS repo.

**Comment by zadjii-msft** [comment]
conclusion: _meh_ we might as well. At this point they're just more MIT files that we've been publishing for the last few years, even if they are just snippets from bigger files that aren't MIT.
