### ISSUE TITLE
Windows Terminal does not find font on start

### ISSUE THREAD

**Issue by Alexciao** [microsoft/terminal#12079]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Open Windows Terminal.

### Expected Behavior

The expected behavior is that WT would load just fine without any errors.

### Actual Behavior

WT loads and shows a "Can't find font" error.
![image](https://user-images.githubusercontent.com/63351498/147920469-51932557-fdab-4383-bba9-73073c4636d9.png)

This **can** be fixed by going to Settings and hitting "Save" without modifying anything, but it is rather annoying, especially because I use a custom prompt that makes use of a "Nerd Font", and displays incorrectly without that.

**Comment by 237dmitry** [comment]
Maybe wrong font face? Try `Nerd Font` instead of `NF`

**Comment by zadjii-msft** [comment]
Oh interesting. This isn't #11648 then. If you're trying to use the nerd fonts version, the Terminal probably should be able to load this without any issues. What string did you enter in the settings file to set the font to CaskaydiaCove NF? 

Curious that the initial load gets it wrong, but then apparently the subsequent load of the SUI falls back to the font you expected. We probably need to align those two code paths.

**Comment by zadjii-msft** [comment]
After looking through the backlog, I found #11583 which looks like the same thing, so I'm gonna merge these threads. /dup #11583

Thanks!

**Comment by Alexciao** [comment]
> Oh interesting. This isn't #11648 then. If you're trying to use the nerd fonts version, the Terminal probably should be able to load this without any issues. What string did you enter in the settings file to set the font to CaskaydiaCove NF?

I just changed it via settings UI.

**Comment by mattdkerr** [comment]
I wasn't able to resolve this with any suggestions here. I had to remove the font choice in the settings.json from Default to be duplicated into each separate profile. Then the errors went away.
