### ISSUE TITLE
Save last commands when app is restarted (command history)

### ISSUE THREAD

**Issue by WebTiger89** [microsoft/terminal#12071]
Hi,
maybe this feature already exists but it would be great if last commands would be saved, e.g. when I drop some powershell commands, exit terminal and reopen it, last commands can be restored by pressing down key. Something like a command history.

Or does this already exist. Currently neither powershell profile nor command line profile saves the commands.

**Comment by zadjii-msft** [comment]
PowerShell already does this, if you hit the up key, right? I believe that's provided by the PSReadline module. As much as I'd love to add that to `cmd.exe`, [we won't be updating `cmd.exe` anytime soon](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#cmd). If you want a modern, updated shell on Windows, you should try out [PowerShell 7](https://github.com/PowerShell/PowerShell).

**Comment by WebTiger89** [comment]
ah ok this is a feature of the shell and not the console? If yes, iam fine. You can close this issue :)

**Comment by 237dmitry** [comment]
You can adjust the UP and DOWN keys to search the history by entering characters. For example, you entered 'c' and pressed the UP key, then you will be offered the most recent command starting with this character. As the search continues to be typed, it will be specified.
Add this to your `$profile`:
```
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
```

**Comment by zadjii-msft** [comment]
Yep, this is a feature of the shell.
