### ISSUE TITLE
automatically switch input methods

### ISSUE THREAD

**Issue by zaunist** [microsoft/terminal#12070]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Other Software

wsl2

### Steps to reproduce

Open ubuntu 20.04 terminal in windows terminal

### Expected Behavior

Will not automatically switch input methods

### Actual Behavior

Sometimes, when I use windows terminal to open the wsl2 terminal, the input method will continuously switch between Chinese and English.

**Comment by zaunist** [comment]
Maybe the windows 11 system bug

**Comment by zadjii-msft** [comment]
can you check if disabling Linux GUI support by adding the below to `.wslconfig` (refer docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)

```ini
[wsl2]
guiapplications=false

```

For linking:
* https://github.com/microsoft/WSLg/issues/443
* https://github.com/microsoft/WSL/issues/7511

**Comment by zaunist** [comment]
> 

Thanks, I will try it after go home.

**Comment by zaunist** [comment]
When I update wslg to 1.0.28, this problem have been solved.
