### ISSUE TITLE
The problem of switching tabs on the terminal.

### ISSUE THREAD

**Issue by jujimeizuo** [microsoft/terminal#12076]
## now
ctrl + alt + number can switch tabs.

## my suggestion
ctrl + number
or
alt + number

**Comment by zadjii-msft** [comment]
You're free to rebind the keys to whatever you'd like. Check out the [`nextTab` and `prevTab` actions](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#open-next-tab)
