### ISSUE TITLE
Tab don't Work in cmd. (Powershell is fine)

### ISSUE THREAD

**Issue by biswasmoheshwar** [microsoft/terminal#12080]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1415

### Other Software

cmd.exe

### Steps to reproduce

Open windows terminal.
Open cmd inside terminal.
Input something and press tab.

### Expected Behavior

Pressing tab will complete the filename.

### Actual Behavior

Adding some spaces like Microsoft word.

**Comment by zadjii-msft** [comment]
Do you have a specific example of a path that doesn't work? "Input something and press tab... Adding some spaces like Microsoft word" isn't _really_ specific enough. Usually when you're in a directory that's got a child file/dir with spaces, cmd should automatically wrap it in spaces, like so:

![image](https://user-images.githubusercontent.com/18356694/147943629-5c0e909b-89c8-4314-a493-2f882f5601d7.png)

**Comment by biswasmoheshwar** [comment]
> Do you have a specific example of a path that doesn't work? "Input something and press tab... Adding some spaces like Microsoft word" isn't _really_ specific enough. Usually when you're in a directory that's got a child file/dir with spaces, cmd should automatically wrap it in spaces, like so:
> 
> ![image](https://user-images.githubusercontent.com/18356694/147943629-5c0e909b-89c8-4314-a493-2f882f5601d7.png)

Example: i wanna change directory from C:\ to C:\Windows
Expected Behavior: cd W then Tab it will become cd Windows
Actual Behavior: cd W
Note: It's happening on all directories. and in only cmd inside terminal. nor powershell inside terminal nor cmd inside conhost

**Comment by zadjii-msft** [comment]
Is there anything in the following two reg keys?

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
```

it should look something like:

![image](https://user-images.githubusercontent.com/18356694/147947772-b78b77ba-6a5b-43c9-b9b7-fbcad740deca.png)

**Comment by biswasmoheshwar** [comment]
> Is there anything in the following two reg keys?
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor
> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
> ```
> 
> it should look something like:
> 
> ![image](https://user-images.githubusercontent.com/18356694/147947772-b78b77ba-6a5b-43c9-b9b7-fbcad740deca.png)

The registry is broken what is the full PathCompletion it seems like Something is hidden

**Comment by zadjii-msft** [comment]
My bad, that should be `PathCompletionChar`.

**Comment by biswasmoheshwar** [comment]
Thanks. fixed
