### ISSUE TITLE
Updates to Terminal repo milestones, 2022 edition

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12082]
The Terminal repo right now consists of a collection of various different "milestones" that have evolved organically over the years. We've got Console milestones, we've got Terminal milestones, we have milestones that vaguely align with OS releases, and then we've got like, four different milestones that are all the "backlog" in one way or another ("Console Backlog", "Terminal Backlog", "Windows vNext", and "Icebox"). All together, they don't create a very clear picture of what's going on in the Terminal land. To try and clear this up, we're going to de-duplicate some of these, and try something new for 2022. 

* The "Console Backlog" and the "Terminal Backlog" are both getting deprecated. They'll be collectively replaced with just a unified **"Backlog"** milestone, which will track things we'd like to get to, but we don't have any time planned for. 
* "Windows vNext" is also being deprecated. Originally, it was a rolling milestone to track things that should be in "the next version of Windows". Unfortunately, it wasn't tracked super well, so it's effectively become a second Console Backlog.
* We're going to use four milestones for tracking bits of the next _year_ of planning. These are separated into two "release" milestones, and two "semester" milestones.
  - **"Terminal v1.{n}"** (as of when this was written, this is v1.13): Shots we're calling for the upcoming release. Features & tasks we expect to land, blocking bugfixes, or other high-pri fixes
  - **"Terminal v1.{n+1}"** (currently, v1.14): Same as above, for the following release. With two 6-week release milestones, this is about 3 months of planning. This is a useful buffer for "we really should do this SOON, but not ASAP. 
  - **"22H1"** will represent the first 6 months of 2022. This will help align internally with the OS release cadence. 
    - If there are `conhost` bugs that need to get fixed in the upcoming release of Windows, then they go here. 
    - Accessibility bugs will also go here, or into the current semester. 
  - **"22H2"** is the same idea. A planning buffer for the second half of 2022. This includes Terminal features we expect to land in the second half. 
    - Terminal P2+ bugs will go here. 
* Terminal v2, Console Backlog, Terminal Backlog, Windows vNext are all going to be emptied into "22H1", "22H2", and the "Backlog", based on current priority labels. 
* We're also going to rename "Terminal v3" to **Up Next"**. This is for features, we think are highest on the backlog. The next big set of features we want to work on. Things that should be at the top of our list to fill up the upcoming semester.
* We're leaving the **""Icebox"** as-is right now, albeit, possibly workshopping the name in the near future. This will remain for features that we think are cool, valid feature requests for the Console&Terminal. However, we'll admit we're never going get to these features.   We'd likely accept PRs from the community for things in here. 
* We had a really successful **"Engineering Improvements"** milestone over the last few weeks, so we'll probably try that again next year. At the end of each year, I'll just move the closed issues in the EIM milestone to a specific "Engineering Improvements {current_year}" milestone. 

We're intentionally not planning out more specifically that 1.n and 1.n+1 - we're generally a fairly responsive team, where priorities can shift quickly during the course of the year. Trying to lick cookies for specific milestones more than 3 months out has generally been an exercise in futility. 

As always, as priorities shift, and resourcing changes, issues can move between these milestones fluidly. 

Hopefully, by grouping bugs into semester-sized milestones, we can address some of them in a timelier fashion. Currently, they just get stuck into "Terminal v2", which we've been pulling features and tasks into as well, which has only created a longer bug backlog 😄.

I'll be going through and moving our issues into this new structure likely sometime early in 2022. 

If this doesn't end up working, we'll take our learnings and try something else for 2023 😄

**Comment by floh96** [comment]
fyi the old milestones are also mentioned in https://github.com/microsoft/terminal/blob/main/doc/terminal-v2-roadmap.md
