### ISSUE TITLE
We broke `\\wsl$` paths with osc 9;9?

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12085]
> this change makes osc 9;9 work with linux paths but breaks `\\wsl$` ones 
> docs at https://docs.microsoft.com/windows/terminal/tutorials/new-tab-same-directory will need to be updated

_Originally posted by @LuanVSO in https://github.com/microsoft/terminal/issues/9223#issuecomment-1001721456_

**Comment by LuanVSO** [comment]
The new behavior is kind of better because it accepts untranslated Linux paths, you just need to remove the call to `wslpath` from the script to make it work again

**Comment by DHowett** [comment]
FWIW, launching WSL with `\\wsl$` itself does not have an issue. I can't see how #9223 broke it, unless for some reason the OSC 9;9 it generates is using `/` instead of `\`. That's going to burn some folks, but not nearly as many as the other behavior did!

<img width="349" alt="image" src="https://user-images.githubusercontent.com/189190/147979705-365a5928-854d-4131-985e-48226f4c34d8.png">

**Comment by DHowett** [comment]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/189190/147979900-d6a6f298-1b7d-4668-bd1b-139dc5370e8f.png">

Another victim of our path absoluting code.

**Comment by LuanVSO** [comment]
oh, so it's already fixed by #12050

**Comment by DHowett** [comment]
I'm not sure actually- didn't that only fix instances where the directory was one character long?

**Comment by LuanVSO** [comment]
i tested it on my build of terminal from that branch and it worked fine.
![image](https://user-images.githubusercontent.com/43626415/147995948-3555fabe-30e0-4851-b2d5-ff212652a418.png)
![image](https://user-images.githubusercontent.com/43626415/147995980-2a4a9d1c-b6c4-4af4-b9cd-c95359f52559.png)

tested with a windows path too.
got any more whacky path to test?

**Comment by DHowett** [comment]
Naw, this looks great! Thanks!

**Comment by zadjii-msft** [comment]
Thanks for fixing that for us! 😄
