### ISSUE TITLE
usbpid wsl version error

### ISSUE THREAD

**Issue by elkimek** [microsoft/terminal#12083]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.376

### Other Software

usbipd inside Ubuntu 20.04 WSL2

### Steps to reproduce

```usbipd wsl attach --busid 2-1```
usbipd: error: The specified WSL distribution is using WSL 1, but WSL 2 is required. Learn how to upgrade at https://docs.microsoft.com/windows/wsl/basic-commands#set-wsl-version-to-1-or-2.

```wsl --list --all --verbose```
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  Ubuntu-20.04    Running         2

### Expected Behavior

Prompting user password and attaching the USB device.

### Actual Behavior

Throwing an error that WSL 2 is required when the the running distro is actually on WSL2.

**Comment by zadjii-msft** [comment]
This sounds like an issue that's better suited for https://github.com/microsoft/wsl

**Comment by elkimek** [comment]
Solved here: https://github.com/microsoft/WSL/issues/7888
