### ISSUE TITLE
multiple profiles with the same GUID error even on fresh install

### ISSUE THREAD

**Issue by theusf** [microsoft/terminal#12084]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.376]

### Steps to reproduce

Just make a fresh Install of the app from microsoft store 

I have 2 accounts on my Windows with Terminal installed, maybe it has a relation?

### Expected Behavior

fresh install resolves the error

### Actual Behavior

The error started to appear in the last few days, tired of trying to solve it, I uninstalled the app and installed it again from MS Store but the error persists even with the default settings.json

![image](https://user-images.githubusercontent.com/29910542/147976510-18096b20-1602-4166-a729-f95aab82c301.png)

Just the default settings.json 

![image](https://user-images.githubusercontent.com/29910542/147976398-ba5ec815-e607-4ddb-8e9f-b656c5bc0dcf.png)

**Comment by zadjii-msft** [comment]
Can you share the contents of the `state.json` file that should be next to the `settings.json` file? This is _certainly_ unexpected 😅

**Comment by theusf** [comment]
![image](https://user-images.githubusercontent.com/29910542/147979343-194109e6-9f71-4853-a1cc-828db8d086d7.png)

**Comment by zadjii-msft** [comment]
Huh. Similar, but not really: #11752, which was more about powershell core, but the same error.

Maybe this is the "We run duplicate GUID detection without checking whether the profile has been deleted" element?

**Comment by theusf** [comment]
Sorry I don't understand really well, here is the error message in English

![image](https://user-images.githubusercontent.com/29910542/147981174-993f0018-f72f-400e-bd0e-9c88714dae19.png)

Yes is very similar to the mentioned issue, I even consulted it before, but discarded it because I think I didn't make big changes in my system or Powershell

Tried to update my PowerShell to 7.2 but does not solve it.

**Comment by elsaco** [comment]
@theusf could you try changing the name for the 2nd profile `Prompt de comando` to `Command Prompt`? You have the same GUID with two different names. CMD profile is part of `defaults.json`. You can generate a new GUID for your `Prompt de comando` profile if you want to keep the name.

**Comment by theusf** [comment]
@elsaco  The name Prompt de comando is the default name of Command Prompt in Brazilian Portuguese, tried change the name like you said but doesn't worked , remembering its the default setting.json right after download the app from ms store.

![image](https://user-images.githubusercontent.com/29910542/148064205-a3009292-c06c-44a3-88c9-3c59eeaaab81.png)

**BUT I finally resolve it!** It was something relationed with my Git version, i tried uninstall and install again the Git and the error stopped, unfortunately i dont payed attention to what version of git was installed before i reinstalled it, now im with the git version  2.34.1.windows.1 and everthing works well again.

**Comment by StefanoBoccuti** [comment]
> **BUT I finally resolve it!** It was something relationed with my Git version, i tried uninstall and install again the Git and the error stopped, unfortunately i dont payed attention to what version of git was installed before i reinstalled it, now im with the git version 2.34.1.windows.1 and everthing works well again.

Reinstalling Git worked for me too. I also had two users on the same machine.

**Comment by zadjii-msft** [comment]
Oh hey, glad this got figured out!
