### ISSUE TITLE
About box background overlay is incorrectly sized

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#12098]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19041.1415

### Steps to reproduce

1. Start Windows Terminal.
2. Resize the window so it's fairly small.
3. Open the _About_ box, and then close it again.
4. Maximize the window so it's full screen.
5. Open the _About_ box again.

### Expected Behavior

The darkened background overlay behind the _About_ box should cover the entire window.

### Actual Behavior

Only the top left corner is covered, occupying an area equivalent to the window size when the _About_ box was first opened.

![image](https://user-images.githubusercontent.com/4181424/148306947-d1725478-784d-4cae-b53f-6b290a65987d.png)

I'm using a light color scheme in the screenshot above because it's a lot easier to see the problem that way, but it can still be reproduced with a dark scheme.

**Comment by zadjii-msft** [comment]
Yea, this is a known issue with XAML `ContentDialogs`. /dup microsoft/microsoft-ui-xaml#3577.
