### ISSUE TITLE
Ability to install/build on Linux machines

### ISSUE THREAD

**Issue by bckelley** [microsoft/terminal#12105]
# Description of the new feature/enhancement
packages for linux based distros like what was done for VSCode, and the ability make terminal from source on linux bash machines.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Please refer to [the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#what-about-porting-the-windows-terminal-to-macos-or-linux). 

> Windows Terminal requires a good number of Windows-specific technologies. We unfortunately won't be supporting it on Mac or anywhere else any time soon
