### ISSUE TITLE
crash if change terminal icon to webp format picture

### ISSUE THREAD

**Issue by sangshuduo** [microsoft/terminal#12101]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. select settings from top bar menu
2. select a profile
3. change icon and pick up a webp format image

### Expected Behavior

support webp picture as the icon or report it's not supported

### Actual Behavior

windows terminal crashed and exit

**Comment by j4james** [comment]
I've just tried to reproduce this using an [example webp image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Johnrogershousemay2020.webp/320px-Johnrogershousemay2020.webp) from Wikipedia and couldn't get it to crash. Could you provide a link to an example webp image that is actually failing for you? Or does the example I linked already crash on your system?

**Comment by sangshuduo** [comment]
I use the the Ubuntu logo from https://www.windowscentral.com/youll-soon-be-able-run-ubuntu-windows-10. I tried again and see it does work. Sorry I can't reproduce the issue now.
