### ISSUE TITLE
When default profile is set to Command Prompt, "Open in Windows Terminal" uses cmd.exe in current folder

### ISSUE THREAD

**Issue by XenoPanther** [microsoft/terminal#12126]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22526.1000

### Steps to reproduce

1. Ensure that cmd.exe from another version of Windows is in the current folder
2. Right-click a black space in Explorer and then click Open in Windows Terminal

### Expected Behavior

Ideally, the system's command prompt should be used as opposed to the one in the current 

### Actual Behavior

The command prompt in the folder is used as opposed to the one from the system

https://user-images.githubusercontent.com/81916167/148704076-bc05a3e8-f018-47e7-bab8-38fceacecd5b.mp4

**Comment by zadjii-msft** [comment]
\<idea for later>:

We look for profiles that have the default command prompt guid, and the commandline set to `cmd.exe`. If we find that, we should replace that with the full path to the system32 `cmd.exe`. We'll discuss Monday

**Comment by zadjii-msft** [comment]
From discussion: We should also do this with Windows Powershell.
