### ISSUE TITLE
Screen is not complety cleared soetimes after a cls command. (Command prompt and Powershell, too)

### ISSUE THREAD

**Issue by zgabi** [microsoft/terminal#12133]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1415

### Other Software

Far Manager 3.0.5888 x64.

### Steps to reproduce

1. Open new Command Promt or PowerShell tab.
2. Start Far Manager
3. Resize the window to bigger.
4. Exit Far manager.
5. (Some trash still remains on the screen)
6. cls

### Expected Behavior

"Empty" screen (only the current prompt & cursor)

### Actual Behavior

Some old characters remains:
![image](https://user-images.githubusercontent.com/3104253/148907791-0932f083-6a35-428f-bc13-c2b6828ac773.png)

after a dir command:
![image](https://user-images.githubusercontent.com/3104253/148907838-2e3d6c9e-7a63-4453-8c9c-375416748f01.png)

Probably Far manager is not clearing something. This is why in step 5 the screen is not empty, but a cls should clear it anyway.

**Comment by zadjii-msft** [comment]
Leaving this here for future self: #4389

I think there are actually other dupes on the issue tracker too.

**Comment by zadjii-msft** [comment]
Yea okay, that's the dupe for these. 

/dup #4389
