### ISSUE TITLE
PM2 Monit feature not working with Windows Terminal.

### ISSUE THREAD

**Issue by lennycode** [microsoft/terminal#12146]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

PM2 Monit
Windows SSH

### Steps to reproduce

Run PM2 monit command in a WT **using WIN SSH** running on a windows 10 or 2019 server machine. The process will be on the remote SSH machine.

This is a problem with both POWERSHELL AND CMD

### Expected Behavior

Should have an interactive console display. PM2 monit dynamically updates the console with a running log.
**Since this works fine in the VS CODE terminals with SSH, it could be a Windows Terminal issue.**

### Actual Behavior

Blank screen. WHen Ctrl+C is hit, the program terminates and you get a complete but final snapshot of the output.

**Comment by zadjii-msft** [comment]
Which version of `ssh.exe`? Does this repro with another ssh, like from a WSL distro?

Does typing any other key when `pm2 monit` is running refresh the display? 

Do you have this setting enabled in VsCode?
![image](https://user-images.githubusercontent.com/18356694/149168576-7fc840f4-17ec-457d-a8c7-e4cecfdb7d47.png)

**Comment by lennycode** [comment]
Thanks for the quick reply.

- Remote SSH INFO: (was Just installed in powershell yesterday)

```
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
```

- Yes, that setting **is** checked in VS Code

- Terminal is completely blank and dead until CTRL+C

-Will try later on Linux

**Comment by elsaco** [comment]
@lennycode this is sample `pm2 monit` on an AWS Linux AMI, using Windows SSH client and Windows Terminal Preview version 1.12.3472.0:

![pm2_monit_sample](https://user-images.githubusercontent.com/3933920/149208321-bdff8c01-4e6e-41b9-83a5-3efd198889e6.png)

Apps just started so there isn't  data to display, yet.

**Comment by lennycode** [comment]
@elsaco here is mine with the issue.  I tried it with Linux too - works great. I usually work with Linux and ssh/ PM2. I would always remote in to to a Windows machine and run it as an admin.
![image](https://user-images.githubusercontent.com/845855/149210121-8ed640b6-60e2-4e75-b0ee-43c7e5f0769b.png)

I also tested it in regular terminals - no go. So it may not be fully a Windows term issue (I barely use cmd and ps anymore :lol:)

**ONLY works in VS code**.  Maybe there is some component on the server VS code uses to make it work. PM2 has to run in elevated mode on Windows.  But, still, there is some output.

**Comment by zadjii-msft** [comment]
Weird. I'd maybe try updating the openssh client you have, and if at all possible, updating the server side sshd as well. 

The fact that this doesn't work in other Terminals would seem to suggest that this is an SSH bug somewhere, but the fact that it works in VsCode is troubling. Is the `ssh` that's being used by VsCode the same `ssh`?
