### ISSUE TITLE
Delay when terminal bell sound is triggered

### ISSUE THREAD

**Issue by jseba** [microsoft/terminal#12152]
This is extremely minor, so unless someone knows this off the top of their head, feel free to put this off indefinitely!

I've noticed after upgrading my laptop to Windows 11 that when the bell is triggered while I'm ssh'd into a server, the sound is delayed by a solid second, which is ever-so-slightly annoying when I've already determined that my tab-completion didn't resolve the way I wanted it to and I've started typing the next couple of characters to start narrowing the list of matches or double-tabbed to get bash to list all the potential matches. The same issue persists when I checked using WSL locally.

My Terminal configuration is basically the default, minus a colorscheme or two, and is version 1.11.3471.0.  I've not checked against a Windows 10 machine, as I have none left at this point, so I can't say if this is a Windows 11 specific issue. If this is a Windows 11 issue, let me know and I'll file feedback over there, as I haven't observed the same issue yet in other applications.

**Comment by fishstik** [comment]
I've noticed that the bell does not trigger if a previous bell is being played back. This is different from e.g. mintty where it will cut off any previous bell to play a new one. Is this what you're observing, or does it still delay after a period of inactivity?

**Comment by DHowett** [comment]
You know, circling back to this... in May 2021 we switched the bell to be a "leading" delayed call, where it would fire the bell off immediately and then suppress bell messages for a second _afterwards_. That was long before this issue, so it doesn't explain the behavior.

I wonder if something about the media system is constraining us here. Are you still seeing it, even on newer versions of Terminal?

**Comment by jseba** [comment]
As of 1.16.10262.0 and winver 22621.1555 I don't seem to be hitting this issue but I could not tell you when it might have been resolved. Feel free to chalk it up as an unsolved mystery unless it's really bugging you!

**Comment by zadjii-msft** [comment]
I'm cool calling this an unresolved mystery. Thanks for following up!

**Comment by eliotbaez** [comment]
It appears this issue is still present in Windows Terminal 1.23.12811.0 on 22H2 19045.6456.

**Comment by Ruberoid** [comment]
Version: 1.24.10921.0
Still this annoying delay! Is it possible to add some kind of option for delayed or immediate bell playback?
