### ISSUE TITLE
Crash when using Magnifier

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#12155]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19044.1415

### Other Software

git version 2.33.0.windows.2

### Steps to reproduce

Preparation: Clone <https://github.com/jenkinsci/bitbucket-branch-source-plugin/> and check out commit 9fa69fddd2e1d07df457a47185817b3f70fb6447.

Start Magnifier and Windows Terminal Preview 1.12.3472.0. Start a Git Bash session and a PowerShell session. In the Git Bash session, change to the directory where you cloned the repo. Run `git grep PullRequestHookProcessor` and press <kbd>q</kbd> to exit `less`. Repeat the command a few times.

### Expected Behavior

No crash.

### Actual Behavior

Windows Terminal crashes, taking out the PowerShell session as well.

Diagnostic data at <https://aka.ms/AAfh2jt>.

**Comment by KalleOlaviNiemitalo** [comment]
May be a duplicate of <https://github.com/microsoft/terminal/issues/8730>.

**Comment by zadjii-msft** [comment]
Definitely, /dup #8730
