### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED BSOD when clicking on URL links in output

### ISSUE THREAD

**Issue by tomhoad** [microsoft/terminal#12153]
### Windows Terminal version

1.11.3471.0

### Windows build number

19042.1415

### Steps to reproduce

1. Ctrl + Click on a URL (any URL in the terminal output)
2. See BSOD

Example:
![image](https://user-images.githubusercontent.com/1664032/149315528-d71f9912-76a3-4535-8895-29b5ea3a15a0.png)

### Expected Behavior

The link to open in the default browser

### Actual Behavior

![IMG_20220111_143058](https://user-images.githubusercontent.com/1664032/149315559-2c53d0ed-a82f-40cb-b4ff-cdd5b30b8f50.jpg)

**Comment by zadjii-msft** [comment]
WOW That's mental. I don't know why that would be happening for the Terminal... WE're tho really doing anything special with the way we open links, we're just calling ShellExecute:

https://github.com/microsoft/terminal/blob/1a62f473ad12bd96da2dd1c22815870f7652b5ce/src/cascadia/TerminalApp/TerminalPage.cpp#L2028-L2035

I'd assume that there are other apps that call `ShellExecute` would react in a similar way, or heck, even just a simple minimla exe that just calls 

```c++
ShellExecute(nullptr, L"open", L"https://github.com/microsoft/terminal/issues/12153", nullptr, nullptr, SW_SHOWNORMAL); 
```

would repro the  same crash.

Did this ever work for you on this machine? Is the Sophos driver fully updated? Kindda grasping at straws here... 😕

**Comment by tomhoad** [comment]
Our internal IT folks have discussed with Sophos and it appears to the same issue as [https://support.sophos.com/support/s/article/KB-000043479?language=en_US&name=KB-000043479](https://support.sophos.com/support/s/article/KB-000043479?language=en_US&name=KB-000043479). 

Specifically affecting apps downloaded from the App Store. In which case, I think we can close this, and let the Sophos folks deal with it, as it's not specific to Microsoft Terminal.

Thanks for taking a look!

**Comment by DHowett** [comment]
*Ah!* Thanks for closing the loop on this!
