### ISSUE TITLE
TerminalAppLocalTests::TabTests are failing

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#12158]
### Windows Terminal version

Commit c3fd26a393bd00664a3527f3c973e2cec2344e06

### Windows build number

10.0.19041.1415

### Steps to reproduce

1. Checkout the latest code.
2. Build. 
3. Run the `TerminalAppLocalTests` unit tests.

### Expected Behavior

Tests should pass.

### Actual Behavior

Two tests are failing:

    TerminalAppLocalTests::TabTests::TestPreviewCommitScheme [Failed]
    TerminalAppLocalTests::TabTests::TestPreviewDismissScheme [Failed]

As far as I can tell, these first stopped working in commit c3fd26a393bd00664a3527f3c973e2cec2344e06.

**Comment by zadjii-msft** [comment]
That sounds like something I screwed up. Welp. I'll take a look. Thanks ~CI~ @j4james!

**Comment by lhecker** [comment]
3 tests failing for me:
```
TerminalAppLocalTests::TabTests::VerifyCommandPaletteTabSwitcherOrder [Failed]
TerminalAppLocalTests::TabTests::TestPreviewCommitScheme [Failed]
TerminalAppLocalTests::TabTests::TestPreviewDismissScheme [Failed]
```
