### ISSUE TITLE
Terminal doesn't handle dots in a correct way

### ISSUE THREAD

**Issue by qhr-slava** [microsoft/terminal#12159]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.0

### Other Software

Maven 3.8.1
JDK latest 1.8 available (1.8.0.312 in my case)
PowerShell 7.2.1

### Steps to reproduce

1.Have java and maven installed.
2.Create new maven project.
3.Try to add maven wrapper for the project with `mvn wrapper:wrapper -Dmaven=3.8.4`

### Expected Behavior

I'm expecting maven wrapper to configure maven with version 3.8.4 for further use.
I should get ` --- maven-wrapper-plugin:3.1.0:wrapper (default-cli) @ directory-admin ---
[INFO] Unpacked bin type wrapper distribution org.apache.maven.wrapper:maven-wrapper-distribution:zip:bin:3.1.0
[INFO] Configuring .mvn/wrapper/maven-wrapper.properties to use Maven 3.8.4 and download from https://qhrtech.jfrog.io/artifactory/qhr-maven-legacy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS` as a result.

### Actual Behavior

Terminal only parse `-Dmaven=3` as version and counts rest `.8.4` as a next parameter instead of just version of maven I'm trying to install. 
![image](https://user-images.githubusercontent.com/59942112/149391919-7630f289-b28d-4a26-81a4-f20abaf330e1.png)

**Comment by ianjoneill** [comment]
This is a PowerShell thing - you need to quote the parameter.

![image](https://user-images.githubusercontent.com/5821575/149406344-a62b475d-2cad-44c0-a06d-57efed406721.png)

It works in cmd without the quotes.

![image](https://user-images.githubusercontent.com/5821575/149406846-a00ba0df-353c-46f9-9e18-5b68907a5e22.png)

**Comment by zadjii-msft** [comment]
Yep, that looks like it's by design to me. Thanks for the quick answer @ianjoneill!

**Comment by qhr-slava** [comment]
Huh, didn't know that. Thank you for the answer!
