### ISSUE TITLE
Missing Azure profile

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12151]
### Windows Terminal version

main c3fd26a

### Windows build number

10.0.22000.0

### Steps to reproduce

Build latest GitHub release (HEAD=c3fd26a39 in this case)

### Expected Behavior

Azure profile present

### Actual Behavior

Missing Azure profile:

![wt_dev_no_azure_profile](https://user-images.githubusercontent.com/3933920/149230928-81bca3ec-643c-4552-8246-7b44473cea2e.png)

**Comment by zadjii-msft** [comment]
The Azure Cloud Shell is not included in dev builds intentionally. It requires a secret key to enable that we can't have in the public repo. There _might_ be ways of generating a suitable key for local testing, but I don't know for sure.
