### ISSUE TITLE
"Open in Windows Terminal" Explorer context menu on left pane opens to wrong location

### ISSUE THREAD

**Issue by johnburnett** [microsoft/terminal#12161]
### Windows Terminal version

1.11.3471.0

### Windows build number

22000.434

### Steps to reproduce

Assume a directory tree that looks like this:
```
parentDir/
  childDirA/
  childDirB/
```
1. Navigate to the `childDirA` subdir so that the contents shows in the right pane of explorer
2. right-click on `childDirB` in the *left* (treeview) pane of explorer (the contents of `childDirA` will continue to show in the right pane)
3. Choose "Open in Windows Terminal"

### Expected Behavior

A terminal to open with `childDirB` as the current dir.

### Actual Behavior

The terminal opens to `childDirA`.  Might be related to #11587 (which references internal issues MSFT:36795851 and MSFT:36416534.

**Comment by elsaco** [comment]
@johnburnett if you open `childDirB` (content shown in the right pane) then right-click directory `childDirA` the terminal will open in `childDirB`. I tried with more subfolders and the terminal opens to whatever folder has been selected in the left pane to have its contend shown.

**Comment by zadjii-msft** [comment]
Thanks for filing this! I've moved this upstream to the File Explorer folks, in MSFT:37779037.

**Comment by zadjii-msft** [comment]
Unfortunately not really. On the bright side, my experience with the File Explorer team has been pretty positive overall, and they've been fairly good about getting on top of the context menu bugs we've thrown their way.

**Comment by johnburnett** [comment]
Ok, no worries - I'll keep an eye on this ticket as a proxy for what the
fix might look like.

**Comment by zadjii-msft** [comment]
This got duped to MSFT:36889296, which was just fixed internally and should be flowing out to an Insiders build sometime soon.

**Comment by zadjii-msft** [comment]
I believe this was either fixed in `22570` or `25071` - build numbers are confusing these days, but both those builds date back to March. Thanks all!
