### ISSUE TITLE
Feature Request: Make Release Notes easily available possibly using new About section

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#1216]
# Summary of the new feature/enhancement

Piggy backing off of https://github.com/microsoft/terminal/issues/867, I noticed the PR adding an About section in the menu. Now I'd like for a summary of Release Notes (could be a "What's New?" for each build once published to the Store. This could either be it's own clickable option in the menu or you could include a link on the bottom of the About section. But ideally it would act like VS Code. Since pictures are worth a thousand words, here's an example of how the About section could look if we aren't adding the Release Notes there (but note it does show the commit number and has a copy/paste option which would be helpful for filing issues):

![image](https://user-images.githubusercontent.com/33032910/59354024-c4f81b00-8d13-11e9-8d70-2098fec69d31.png)

Obviously some software shown isn't applicable, but the idea of it would be nice. For Release Notes itself, it could open up a json or html file showing the major changes and bug fixes similar to how extensions for VS Code work (Gitlens in particular comes to mind). (Sixel support here would go a long way if we want to display in the terminal itself). A helper link that went to the Github page showing all the applicable Pull requests that are associated with the release at the end of the Release Notes would be nice as well.

**A clear and concise description of what the problem is that the new feature would solve.
Describe why and how a user would use this new functionality (if applicable).**

Creates transparency for users to know what's changed and makes it easier for filing issues. Ideally the Release Notes would be available to the local host so that Internet connection isn't required for users in Internet-restricted environments.

**Proposed technical implementation details (optional)**

Recommend using https://github.com/microsoft/terminal/pull/1196 as a base point/reference for the changes.

**Comment by DHowett-MSFT** [comment]
Depends-on: Settings UI

**Comment by cinnamon-msft** [comment]
#1887 fixes this!
