### ISSUE TITLE
Terminal causes hard disk to spin up

### ISSUE THREAD

**Issue by petershh** [microsoft/terminal#12172]
### Windows Terminal version

1.11.3471.0

### Windows build number

19044.1466

### Steps to reproduce

1) Have a setup like Windows on SSD and HDD for data
2) Wait when Windows spins down HDD
3) Launch Terminal
4) Hear HDD spinning up

### Expected Behavior

HDD remains standby

### Actual Behavior

HDD spins up. Besides making PC louder, this issue introduces delay to the terminal startup

**Comment by zadjii-msft** [comment]
What shell are you running in the Terminal? Is there anything in that shell's startup that might be kicked off just by launching the shell? Does this repro in a vintage console window? Is the HDD you're `C:\` drive?

**Comment by petershh** [comment]
> What shell are you running in the Terminal?
By default it runs PowerShell.

> Is there anything in that shell's startup that might be kicked off just by launching the shell?
I think no. I didn't modify the defaults.

> Does this repro in a vintage console window?
No with cmd.exe, yes with powershell.exe.

> Is the HDD you're `C:\` drive?
C: is SSD, and D: is HDD.

**Comment by zadjii-msft** [comment]
> yes with powershell.exe.

Great, then this sounds like an issue with PowerShell, not the Terminal. I'd suggest filing this over at https://github.com/PowerShell/PowerShell, they'll be more able to help figure this one out. Thanks!
