### ISSUE TITLE
Typing >= is auto-magically replaced with the math symbol for greater-equals

### ISSUE THREAD

**Issue by doug-rosser** [microsoft/terminal#12179]
![image](https://user-images.githubusercontent.com/6701351/149674898-8c87cf60-6c8e-4839-ad1d-8ead920486c8.png)

This type of "delight the user" user-interface enhancement is annoying. Please let me know how to turn this off UNIVERSALLY!

I'm trying to code and I can't figure out how to turn this off!

**Comment by doug-rosser** [comment]
I have tried turning off autocorrect universally in "Settings->Devices->Typing" but this is still happening.

**Comment by doug-rosser** [comment]
Forgot to note, this is happening in WSL Ubuntu 20.04

**Comment by j4james** [comment]
This is a feature of the font called "ligatures". If your font is set to _Cascadia Code_, try changing it to _Cascadia Mono_ (which is the version without ligatures). You may also be able to disable that option for a font via the [Font Features](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#font-features) setting.

**Comment by doug-rosser** [comment]
Confirmed fix. Who knew a font with "code" in the name could contain such a mis-feature?

**Comment by lhecker** [comment]
@doug-rosser I'm assuming your question has been answered? Feel free to reopen this issue if you'd like. 🙂

**Comment by doug-rosser** [comment]
Closing. But if "Cascadia Code" is a default for Windows Terminal, it's asking for more trouble. Just my opinion.

**Comment by lhecker** [comment]
The default font is Cascadia Mono actually. [This is the value for it.](https://github.com/microsoft/terminal/blob/7061c54ac59c8469a00a6ce36334ba379ff704e9/src/inc/DefaultSettings.h#L29)
