### ISSUE TITLE
Windows wt shortcut in run, start menu, and search (run command) does not work

### ISSUE THREAD

**Issue by AyraHikari** [microsoft/terminal#12175]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.466

### Steps to reproduce

- Right click on Windows start, click Windows Terminal or Windows Terminal (Admin)
![image](https://user-images.githubusercontent.com/36266025/149642239-3dddf415-3a47-4b25-a066-27cf83c77ed0.png)

- Search, type 'wt' and run
![image](https://user-images.githubusercontent.com/36266025/149642241-a84c79c4-e106-460f-a1c6-fa0c5ae0c0ed.png)

- Windows + R, write 'wt' and enter
![image](https://user-images.githubusercontent.com/36266025/149642243-7926c0b0-8522-4702-8067-8823824d2e5f.png)

### Expected Behavior

It should open WindowsTerminal.exe
It works when typing 'wt' from command prompt or 'Windows Terminal' app from search, just does not work from what i said above

### Actual Behavior

Does nothing, and not showing anything

**Comment by AyraHikari** [comment]
Also when i run `wt.exe` and `WindowsTerminal.exe` from `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe`, it does not work.
Tried reinstalling, repairing, and resetting does not work too

**Comment by AyraHikari** [comment]
Update:
I tried downgrading to `1.10.210826003-release1.10`, and wt.exe fully working in these all issues.
Probably i'll stay in these version and waiting for fix in next release

**Comment by zadjii-msft** [comment]
> I tried downgrading to `1.10.210826003-release1.10`, and wt.exe fully working and have no that all issues.
> Probably i'll stay in these version and waiting for fix in next release

There's no reason that 1.11 would have broke this, so if 1.10 is working for you, I'd suspect that's just coincidence 😅. 

Have you possibly changed the permissions on the `WindowsApps` directory at all? This sounds a lot like #12139 which was a dup of #9452

**Comment by AyraHikari** [comment]
> > I tried downgrading to `1.10.210826003-release1.10`, and wt.exe fully working and have no that all issues.
> > Probably i'll stay in these version and waiting for fix in next release
> 
> There's no reason that 1.11 would have broke this, so if 1.10 is working for you, I'd suspect that's just coincidence 😅.
> 
> Have you possibly changed the permissions on the `WindowsApps` directory at all? This sounds a lot like #12139 which was a dup of #9452

Perhaps yes, it may coincidence. I tried updating from `1.10.210826003-release1.10` to `1.11.3471.0` with github release msixbundle, and i didn't encounter that issues.

Sadly i can't check if it was actually permission issue or not, so i'll close this issue because the issues solved
