### ISSUE TITLE
Option to paste without the final newline

### ISSUE THREAD

**Issue by AsafMah** [microsoft/terminal#12185]
# Description of the new feature/enhancement

When pasting something that includes multiple lines I get this useful screen:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/6424271/149906847-ba48cb57-5bb9-47ce-a296-e50faed5c1ab.png">

But what happens very often, is that I copy the command from another source, but I want to edit it before sending.

And it seems that copying from many places automatically adds a newline at the end (websites, chat programs)
So what I do currently is carefully copy it without the last character, and then I can edit the command.

What I think would be a useful feature is either:
1.  If the pasted text ends in a new line, there will be an additional button in the dialogue which will be "paste without the trailing new line"
2. Or, maybe a new settable keybinding to paste and trim the final newline.

Thanks!

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9400 for more discussion.

/dup #9400


#11473 should be coming in 1.13 with a fix for this ☺️
