### ISSUE TITLE
Guake resize the window horizontally (dynamic and/or fixed)

### ISSUE THREAD

**Issue by g33k247** [microsoft/terminal#12184]
# Description of the new feature/enhancement

Make the Guake window resizable for those of us on widescreen monitors. The setting could be dynamic (drag and resize) or fixed (percentage of resolution). Resizing horizontally would make the dropdown terminal much more useable.

# Proposed technical implementation details (optional)

Linux terminals with dropdown features allow setting a fixed width and height in the settings panel.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+quake+resize+horizontally) when filing new issues. This is already being tracked by another issue on our repo - please refer to #11125 for more discussion.

/dup #11125
