### ISSUE TITLE
print error for git-bash using oh-my-zsh  with autosuggestions

### ISSUE THREAD

**Issue by Ancho5515** [microsoft/terminal#12187]
### Windows Terminal version

1.11.3471.1

### Windows build number

10.0.19042.0

### Other Software

git-bash
zsh(with [msys2pack](https://packages.msys2.org/package/zsh?repo=msys&variant=x86_64) unpacked to git root)
oh-my-zsh(for zsh)
autosuggestions(for zsh)

### Steps to reproduce

add git-bash to terminal
launch a git-bash tab
launch zsh
input some long word

### Expected Behavior

![image](https://user-images.githubusercontent.com/30588293/149966910-e67bc3c0-7122-44bb-a112-4f810a517d5d.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/30588293/149966878-f29096cd-5de1-4557-a5be-730e569f5389.png)

**Comment by zadjii-msft** [comment]
Wow that is wild. That _kinda_ looks like the newline/autoreturn bug that we see in mingw with some frequency, but it's... different.

> it works fine with ... WSL

By "WSL" I'm assuming you mean in the vintage console, instead of in the Terminal? That would be extra curious. I would expect this to be broken in the same way in both...

**Comment by Ancho5515** [comment]
You can see the image under "Expected Behavior" which use the origin git-bash console instead of in the Terminal , it works fine
I install the oh-my-zsh with autosuggestions under wsl, and launch it with the Terminal, it works fine too

but for the image shown blow "Actual Behavior", I launch git-bash with the Terminal, and tap some word, it gets wrong outprint

Anyway, this problem is solved by switch zsh-autosuggestions verison from v0.7.0 to v0.6.4, and I guess it has nothing related to the Terminal
