### ISSUE TITLE
German translation for FOR /F command description is incorrect

### ISSUE THREAD

**Issue by german-one** [microsoft/terminal#12183]
### Steps to reproduce

<img width="476" alt="for_bug" src="https://user-images.githubusercontent.com/46659645/152648897-98534ea2-f4c4-4d46-964e-e7920b41033f.png">

Run `FOR /?`
1. The description of how to use a FOR /F loop for commands and _without_ using option USEBACKQ shows no quotes around the command. However, single quotes would have been correct here.
2. The description of how to use a FOR /F loop for strings _and_ using option USEBACKQ shows double quotes around the string. However, single quotes would have been correct here.

### Expected Behavior

1. `FOR /F ["Optionen"] %variable IN ('Befehl') DO Befehl [Parameter]`
2. `FOR /F ["Optionen"] %variable IN ('Zeichenfolge') DO Befehl [Parameter]`

### Actual Behavior

1. `FOR /F ["Optionen"] %variable IN (Befehl) DO Befehl [Parameter]`
2. `FOR /F ["Optionen"] %variable IN ("Zeichenfolge") DO Befehl [Parameter]`

**Comment by german-one** [comment]
@lhecker Do you want to fix this along with your's? IIRC I've seen this on XP already 😄

**Comment by german-one** [comment]
Sorry for the late update. How did I miss the other bug ... ? 😳

**Comment by lhecker** [comment]
Tracked as MSFT:38199007.

**Comment by lhecker** [comment]
This issue has been resolved internally and will be part of the next release.
