### ISSUE TITLE
I have problems highlighting text when console buffer is full

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#12197]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Steps to reproduce

Fill console log completely.
`for example by 
:loop
echo "test"
goto loop
`
stop scrolling by scrolling mouse wheel upwards
try to highlight some text.

[bandicam 2022-01-19 02-58-35-628.zip](https://github.com/microsoft/terminal/files/7893136/bandicam.2022-01-19.02-58-35-628.zip)

### Expected Behavior

To be able to highlight what i need

### Actual Behavior

Windows terminal  highlights whole half of the screen

**Comment by zadjii-msft** [comment]
You know what, this looks a lot like #7524 to me. This should help us get a solid repro for that one. Thanks!

/dup #7524
