### ISSUE TITLE
Win+up/down shortcuts don't work after toggling Fullscreen from Focus Maximized mode

### ISSUE THREAD

**Issue by Eythaann** [microsoft/terminal#12192]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.434

### Steps to reproduce

Just need to toggle to **Focus Maximized Mode** and later toggle to **FullScreen Mode**, when you exit of FullScreen the window is bug and you **can`t minimized or maximized with the shortcuts("windows+down" and "windows+up")** 

### Expected Behavior

The shortcuts works

### Actual Behavior

The shortcuts don't work

**Comment by zadjii-msft** [comment]
Woah what. That's weird. I'd have thought that would be fixed by #11653, but that's already in stable.

I wonder if in this scenario, the caption buttons aren't being displayed, so the window messages we're sending just get ignored. That's conjecture, but probably where I'd start.

**Comment by Eythaann** [comment]
and I can still replicate this bug [#11653](https://github.com/microsoft/terminal/pull/11653)

**Comment by serd2011** [comment]
#11653 was added in 1.11.3471.0 while you specified that your version is 1.11.2921.0
