### ISSUE TITLE
WSL `--cd` promotion doesn't work for ARM or something?

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12195]
Kayla has a weird thing with `//wsl$/Ubuntu/home/cinnamon`. Forward slashes were interpreted as root, and backslashes failed with 0xffffffffff
![08e4b29c-8bf0-4e87-8d62-942bc55f65ab](https://user-images.githubusercontent.com/18356694/150029995-868a99f8-dd41-49e1-a2f1-1707cfb49aec.jpg)

Run dialog `wt -- wsl --cd foo` seemed to repro it

**Comment by zadjii-msft** [comment]
@craigloewen-msft Can you get someone from the WSL side to help investigate this? It repros consistently on @cinnamon-msft's machine so we do have a live repro

**Comment by DHowett** [comment]
Promoted to https://github.com/microsoft/WSL/issues/8007
