### ISSUE TITLE
File selection dialog shows up in Japanese instead

### ISSUE THREAD

**Issue by parkel42** [microsoft/terminal#12198]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.0

### Other Software

N/A

### Steps to reproduce

1. Open up settings for Windows Terminal
2. Go to any profile, click on Browse for anything (can be Command Line, Starting Directory, Icon or even Appearance > Background Image).
3. Dialog box shows up in Japanese instead of English.

### Expected Behavior

Dialog box is supposed to appear according to the system language (en-SG in my case).

### Actual Behavior

See the following screenshot:

![image](https://user-images.githubusercontent.com/50959479/150062632-2fc6681c-fc91-480c-9d5b-1cc130ce963a.png)

**Comment by parkel42** [comment]
Yes, I have the Japanese language pack installed as well as the Chinese language pack. 

Here's the screenshot of the language list in settings: 

![image](https://user-images.githubusercontent.com/50959479/150240369-4d651cb2-c26b-4d8d-8bf7-9cdcaaf59536.png)

**Comment by parkel42** [comment]
Ok, so after posting the screenshot, I realised that I didn't actually have the en-sg language pack installed so I went ahead and installed that. 

It seems to be working properly after installing the language pack:

![image](https://user-images.githubusercontent.com/50959479/150241097-cc954e56-955b-4581-9c77-f38ad75549d2.png)

I assume Windows Terminal was defaulting to Japanese because it's the next one in the list with a language pack installed, but I didn't have similar issues with other applications.

**Comment by zadjii-msft** [comment]
@axelandrejs any ideas what's going on in this one? 

I suppose it makes sense that the picker would show up in Japanese if the first language in the list didn't actually have the language pack installed. That being said, I would have expected the rest of the OS to be in Japanese too, so idk. 

This does seem like it's got a known resolution, so I'm tempted to close it. I think I'll leave this open for a while longer to see if anyone's got any ideas why this works the way it does, but I'm not sure there's much else for the Terminal to do here.

**Comment by axelandrejs** [comment]
We do support partial localization for high-value strings without the need for a full language pack being installed. Though it is odd that this UI wouldn't fall under that bucket. I can see about finding out, but yes without the language pack installed the experience is going to be torn.

**Comment by zadjii-msft** [comment]
Huh. Well, sounds like enough of an answer to me. Thanks Axel!
