### ISSUE TITLE
Allow aliasing parent process directories

### ISSUE THREAD

**Issue by UmbralReaper** [microsoft/terminal#12200]
# Description of the new feature/enhancement

I like to start windows terminal through the search function in the taskbar, or through PowerToys Run. However, both of these end up in undesirable starting locations when windows terminal inherits the parent process (`C:\Windows\System32` and `~\AppData\Local\Microsoft\WindowsApps`, respectively). However, setting a more desirable default start location (such as `%USERPROFILE`) prevents inheriting the location when it is useful.

I propose that you allow setting aliases for start locations in settings.
```json
{
    "start_aliases": {
        "C:\\Windows\\System32": "%USERPROFILE%",
        "%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps": "%USERPROFILE%"
    }
}
```

**Comment by 237dmitry** [comment]
You can add `startupActions`. For example:
```
"startupActions" : "--startingDirectory D:\\",
```

**Comment by zadjii-msft** [comment]
> You can add `startupActions`. For example:
> 

I don't think that'll work at all for what this user's asking for...

<hr>

In general, we're tracking improvements to `startingDirectory` in #4637. That thread has a couple ideas in it already, I'm gonna move yours in there too, because it's a good idea. Thanks!

/dup #4637
