### ISSUE TITLE
Where are PDB files for public builds?

### ISSUE THREAD

**Issue by dmchurch** [microsoft/terminal#12203]
I've been experiencing occasional hangs in the latest WT (1.11.3471.0 from the Store, on Windows 10.0.22000). I started to debug one myself, partly to help out and partly because it would have been nice to get those six or seven terminal sessions back, but I ran into an issue when VS2022 couldn't find the PDB files for the WT modules. I can see a number of issues here relating to how the PDBs are produced, but I couldn't find anywhere that said where to actually find them. Help? If they aren't getting added to the Microsoft public symbol servers, can someone add something to the docs or the wiki here on where they _can_ be found? Thanks!

**Comment by elsaco** [comment]
@dmchurch the easiest way to get the PDBs is to build WT locally.

**Comment by dmchurch** [comment]
@elsaco Wait, does that work? Can the PDBs from a local build be used to debug the official binaries? I was under the impression you need PDBs created during the build that made your executable.

**Comment by zadjii-msft** [comment]
I know that @DHowett knows the answer to this, I just can't find it by searching the repo for whatever reason ¯\\\_(ツ)_/¯

**Comment by zadjii-msft** [comment]
#2857 and #3138 implies we link them somehow... Maybe only WinDBG can figure out where the symbols are...

**Comment by DHowett** [comment]
This one is on me -- we should certainly be publishing symbols publicly to let folks diagnose in the wild. Thanks for bringing it up :)

**Comment by zadjii-msft** [comment]
Didn't we do this in https://github.com/microsoft/terminal/pull/11852? Not sure where those go though...

**Comment by DHowett** [comment]
Nah, that was something slightly different. I've engaged the folks who own the public symbol server and gotten clearance to push there! Today or Monday, I'll upload some historical symbols and make sure the build does so on its own in the future.

**Comment by DHowett** [comment]
Got a PR out to make sure we publish these :)
