### ISSUE TITLE
Escape sequences are not stripped from the tab title

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#12206]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19041.1415

### Steps to reproduce

1. Edit the settings.json file.
2. Set the default tab title with an escape sequence like this: `"tabTitle": "\u001b[41m"`
3. Start a cmd shell

### Expected Behavior

The escape character should be stripped from the title.

### Actual Behavior

The escape character is left in the title when propagated over conpty, so it ends up being interpreted as a background color change in the terminal.

![image](https://user-images.githubusercontent.com/4181424/150380055-929963d1-dbb2-469c-9c4f-d8914c5cb626.png)

We do already sanitize the title in `DoSrvSetConsoleTitleW`, which covers title changes via the console API, but in this case the `CONSOLE_INFORMATION::SetTitle` method is being called directly from the `AllocateConsole` method on startup:

https://github.com/microsoft/terminal/blob/7061c54ac59c8469a00a6ce36334ba379ff704e9/src/host/consoleInformation.cpp#L130

My suggestion is we move the sanitization from `DoSrvSetConsoleTitleW` into the `CONSOLE_INFORMATION::SetTitle` method, so we can be sure it's applied in all cases.

**Comment by zadjii-msft** [comment]
That's a great catch, and the suggestion sounds fine to me!


\> inb4 some enterprise has been intentionally putting an escape char in their titles for god knows what reason
🤣

**Comment by j4james** [comment]
> inb4 some enterprise has been intentionally putting an escape char in their titles for god knows what reason

I did actually wonder about that, but the current sanitization code only runs when we're in pty mode, and I was planning to retain that condition, so crazy enterprise code should still work as usual on conhost if it comes to that.
