### ISSUE TITLE
How to disable character auto convert？

### ISSUE THREAD

**Issue by gitsang** [microsoft/terminal#12213]
Version: Windows Terminal Preview 1.12.3472.0

For example, if I type `!=` it will be auto convert to `≠`. I don't want this. How can is disable it?

![image](https://user-images.githubusercontent.com/49085035/150474964-87163f62-bdf8-4e64-acb9-3e27ee1fed29.png)

**Comment by 237dmitry** [comment]
Disable ligatures in [font features](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance). Or choose font without ligatures. As a rule, the name of the font contains the word Mono.

**Comment by zadjii-msft** [comment]
Yea, those are called ligatures. You can change the font from "Cascadia Code" to "Cascadia Mono" as an easy solution. Otherwise yes, the font features is another way to disable them. See: https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-11-release/#font-features-and-axes

/dup #759

**Comment by gitsang** [comment]
https://docs.microsoft.com/zh-cn/typography/opentype/spec/featurelist

```json
"font": {
    "face": "Iosevka",
    "size": 11,
    "features": {
        "calt": 0
    }
},
```

diable `calt` can solve this

**Comment by lukebakken** [comment]
@gitsang FINALLY I found the correct way to disable ligatures. Everything else I read suggests `"liga": 0` will do it but it does not. `"calt": 0` disables them. Thank you!

**Comment by ClaireCJS** [comment]
I only want to disable one specific ligature: ***

Any hints on that, anyone who happened to have read this far?

**Comment by DHowett** [comment]
Unless the font allows you to customize individual glyphs (with specific OpenType features,) it's not going to be possible to turn off just one ligature. Sorry!

**Comment by ClaireCJS** [comment]
> Unless the font allows you to customize individual glyphs (with specific OpenType features,) it's not going to be possible to turn off just one ligature. Sorry!

Hmm, okay...
Is there some easy tool i can use to edit the font, remove that 1 ligature, and use that in WT instead?

Heck, if i'm at that level i might want to add or modify even more than that one, just for fun.

**Comment by o-sdn-o** [comment]
> Is there some easy tool i can use to edit the font

You could try [FontForge](https://fontforge.org/en-US/).

1. Run FontForge
2. Open ttf-file: `File->Open->Ok`
3. `Element->Font Info...->Lookups->GSUB->`  delete what you want
4. Change   `Element->Font Info...->PS Names`   to avoid interference with original ttf
5. `File->Generate Fonts...`  to save modified .ttf file
6. Locate modified ttf-file using desktop explorer and click to install it.
7. Restart WindowsTerminal and select modified font.

**Comment by ClaireCJS** [comment]
Holy cow. I never dreamed of having that much control over console. This sounds like a good product for temporary hyperfocus. 

For instance, I think the commas after the right brackets in a situation like this:

```[1, 2, 3], [4, 5, 6], []```

should be tucked a little closer to the right-bracket than they are.

I'll try it out, thank you so much for the guide!

**Comment by ClaireCJS** [comment]
I think in the end, I've decided to just clone the font from your github, and simply remove the raising of the asterisk:

![image](https://github.com/user-attachments/assets/c25b1e7d-5bd8-46ac-99f7-530ed2938cec)

Tempted to delete the whole file, but the angel of unintended consequences says "change as little as possible".

**Comment by brunobmello25** [comment]
Is there any explanation as to why this is not just a "enable font ligatures" configuration option on the appearance settings?

**Comment by lhecker** [comment]
Since "liga" is just one of the many potential axes on a font, I think it makes sense to first implement the generic option that covers all use cases before adding a simpler shortcut (like your suggested on/off setting). I do think it would help discoverability if we had such a shortcut setting though, so it may be worth adding.
