### ISSUE TITLE
Add "Close All Other Panes" Action to Settings/Actions

### ISSUE THREAD

**Issue by erhanalankus** [microsoft/terminal#12216]
# Description of the new feature/enhancement

Add "Close All Other Panes" action to settings/actions.

There is an action for "Close All Other Tabs", so I can close all other tabs with a keyboard shortcut. There is not an action for "Close All Other Panes", so I can't close all other panes with a keyboard shortcut. If added, this would enable users to close all other panes with a keyboard shortcut, making the app more pleasant to use.

# Proposed technical implementation details (optional)

I want to see an action for "Close All Other Tabs" in settings/actions so I can assign a keyboard shortcut to that action.

**Comment by zadjii-msft** [comment]
Sure, I don't see why not.
