### ISSUE TITLE
How to install terminal in windows server 2019?

### ISSUE THREAD

**Issue by yulonghua** [microsoft/terminal#12222]
### Windows build number

Microsoft Windows NT 10.0.17763.0

### Steps to reproduce

Does terminal support windows server 2019 system?
Windows server 2019 neither support install Microsoft Store nor support install .msixbundle package，so is there any other way to install terminal?

### Actual Behavior

try to  install terminal

**Comment by zadjii-msft** [comment]
Please make sure to search for duplicates and [read the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version) when filing new issues.
