### ISSUE TITLE
Make Startup Quicker

### ISSUE THREAD

**Issue by XiaoLeCN** [microsoft/terminal#12221]
# Description of the new feature/enhancement
make terminal startup quicker
now terminal starts much slower than console, i can't see the window quickly

# Proposed technical implementation details (optional)
just like console host
![屏幕截图(96)](https://user-images.githubusercontent.com/74437699/150663231-af1a0d8c-0642-425c-81a5-427b31df2946.png)

**Comment by zadjii-msft** [comment]
Do you have any specific recommendations? Any traces of particular hot paths in startup?

Otherwise, I think this is best tracked in /dup #5907, thanks!
