### ISSUE TITLE
Run as Admin in Context Menu

### ISSUE THREAD

**Issue by Rc-Cookie** [microsoft/terminal#12231]
# Description of the new feature/enhancement

Add an option `Run as Administrator` to the right-click menu on the task bar. It is of course possible to do this via the start menu, but for a console host this seems like essential functionality.

# Proposed technical implementation details

May do the same as Start > Windows Terminal > Run as Administrator.

**Comment by zadjii-msft** [comment]
You can already launch the Terminal elevated from the taskbar, it just requires a second right-click.

![image](https://user-images.githubusercontent.com/18356694/150791531-d2ce99dd-e0b5-4d68-bf50-d642dbeff6fb.png)

**Comment by Rc-Cookie** [comment]
Thanks for that advice, I did not know about this feature!

**Comment by davea1** [comment]
Hint: You can also simply hold `ctrl` + `shift` when clicking on a taskbar icon to launch elevated.
