### ISSUE TITLE
start Checkpoint VPN - windows session network stop working

### ISSUE THREAD

**Issue by fmsilva** [microsoft/terminal#12233]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.18363.2037

### Other Software

ssh to host on vpn network

### Steps to reproduce

open cmd
connect to checkpoint vpn
try ssh to host on vpn network

### Expected Behavior

connect to host with ssh 

### Actual Behavior

cannot resolve host name

**Comment by zadjii-msft** [comment]
I'm not sure that this is really a Terminal issue. Does the issue repro the same way in both the Terminal and the vintage console host, `conhost.exe`?

This might better belong at https://github.com/PowerShell/Win32-OpenSSH/issues. They'd be better equipped to debug any ssh issues you're having.

**Comment by fmsilva** [comment]
Problem related with Microsoft wsl 2
