### ISSUE TITLE
wsl Terminal repeatly display work directory after resize

### ISSUE THREAD

**Issue by Tracker647** [microsoft/terminal#12230]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1466

### Steps to reproduce

1.open wsl terminal either directly or in windows Terminal

2. resize the terminal smaller and scale back

### Actual Behavior

Actual Behavior as gif shows(sorry have problems for recording but it's not affect the problem reproduce):
![GIF](https://s2.loli.net/2022/01/24/IR5XOi7KBHG3ot1.gif)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3088 for more discussion.

/dup #3088
