### ISSUE TITLE
A way to configure the bell sound

### ISSUE THREAD

**Issue by rbanffy** [microsoft/terminal#12235]
# Description of the new feature/enhancement

There doesn't seem to be a way to specify a sound for the terminal bell (ASCII 7). It'd be nice to specify one that's different from the system sound, which gets a bit confusing, as well as getting a different one as the default (so it's not as easy to confuse an Outlook warning to a terminal bell).

# Proposed technical implementation details (optional)

A file selector should be added to the "Advanced" tab for each profile. Selecting a sound for a given profile would make that sound when an ASCII 7 character is output to the terminal.

**Comment by zadjii-msft** [comment]
You'll be happy to know this was added in #11511, which should be in 1.13. 

/dup #8366
