### ISSUE TITLE
[feature request] Command / tab context menu item "Reset a tab"

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#12232]
When ssh hangs in WSLv1 (usually because of network issues or after laptop sleep / hibernate), somehow it doesn't react to any Ctrl+C, Ctrl+Z. Then it's impossible to kill the ssh process, and it can take a few minutes for it to bail out by itself.

Current workaround: kill the whole tab (as it's impossible to kill the current process), open a new tab

Feature request: "reset a tab" command that will restart the tab (and preserve the tab's place in the tab bar).

Alternative feature request: somehow detecting the current process in the bash session and providing a command to kill it

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3726 for more discussion.

/dup #3726
