### ISSUE TITLE
windows terminal don't open from Win + X menù

### ISSUE THREAD

**Issue by ThemisterNaim** [microsoft/terminal#12249]
### Windows Terminal version

1.12.10334.0

### Windows build number

1000.22000.526.0

### Other Software

nothing more than windows terminal

### Steps to reproduce

1: unistall windows terminal
2: reinstall windows terminal from app store
3: open win + X menu
4: select windows terminal / windows terminal (admin)

### Expected Behavior

windows terminal will open

### Actual Behavior

windows terminal don't open, even if you search wt.exe in the start menu (but if you search windows terminal it works)

**Comment by zadjii-msft** [comment]
Is the `wt.exe` "App Execution Alias" enabled in the Settings app?

**Comment by ThemisterNaim** [comment]
yes

**Comment by ThemisterNaim** [comment]
nice bot by the way

**Comment by zadjii-msft** [comment]
Huh. That's definitely unexpected. Have you tried rebooting since re-installing the Terminal? Maybe there's some package catalog data stuck in the cache that might just go away with a reboot.

By any chance, have you messed with the permissions on `C:\Program Files\WindowsApps`? This sounds like #12204 et. al.

**Comment by ThemisterNaim** [comment]
no, i haven't messed windows apps (at least i haven't messed with windowsapps\windowsTerminal😂).
tomorrow i will try to reinstall agan.

**Comment by ThemisterNaim** [comment]
nope, like before, it won't open, and (like before) if you wan't to open wt by win + x like an admin, the security request appear; but than it doesn't do anithing

**Comment by ThemisterNaim** [comment]
even after the update, it doesn't change anithing

**Comment by zadjii-msft** [comment]
If I knew, I'd tell you 😉 

I'm gonna try reaching out to the App Execution Alias team to see if they have more guidance here. If the Terminal can be launched just fine from the Start Menu, but specifically `wt.exe` doesn't work<sup>[1]</sup>, then there's something outside our control that's going wrong that we'll need some help figuring out.

Usually toggling the app execution alias in the Settings app should fix this. Worst case, repairing the app via the settings app should also help. But for some reason those don't seem to help everyone, so we need to figure out what's wrong when those don't work. 

In the meantime, can you share the output of `icacls "C:\Program Files\WindowsApps"` (from an admin shell?) Filing feedback on "Developer Platform > Desktop Bridge" might also help get some traces to the folks that own this.

![image](https://user-images.githubusercontent.com/18356694/151219053-b5a4b199-9c15-42f6-bedc-8bfa86ca888a.png)


<details>
<summary>Correct WindowsApps permissions</summary>

```
\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                           NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(GR,GE)
                           NT AUTHORITY\SYSTEM:(F)
                           NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                           BUILTIN\Administrators:(CI)(RX)
                           NT AUTHORITY\LOCAL SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\NETWORK SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\RESTRICTED:(OI)(CI)(RX)
                           BUILTIN\Users:(Rc,S,RD,REA,X,RA)
```

</details>

As a matter of cross-linking:
* #9452 is our bucket for "the permissions are wrong on WindowsApps, and that will break `wt.exe`
* #10149, #12249 and #12204 all seem to be the same "none of the above fixed it" issues. VERY good chance I de-dupe these all.

<sup>[1]</sup>: The Win+X menu is also powered by `wt.exe`.

**Comment by ThemisterNaim** [comment]
here you go
C:\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                             NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                             S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                             S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(RX)
                             NT AUTHORITY\SYSTEM:(F)
                             NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                             BUILTIN\Administrators:(CI)(RX)
                             NT AUTHORITY\SERVIZIO LOCALE:(OI)(CI)(RX)
                             NT AUTHORITY\SERVIZIO DI RETE:(OI)(CI)(RX)
                             NT AUTHORITY\RESTRIZIONI:(OI)(CI)(RX)
                             BUILTIN\Users:(Rc,S,RD,REA,X,RA)

**Comment by ThemisterNaim** [comment]
> If I knew, I'd tell you 😉
> 
> I'm gonna try reaching out to the App Execution Alias team to see if they have more guidance here. If the Terminal can be launched just fine from the Start Menu, but specifically `wt.exe` doesn't work[1], then there's something outside our control that's going wrong that we'll need some help figuring out.
> 
> Usually toggling the app execution alias in the Settings app should fix this. Worst case, repairing the app via the settings app should also help. But for some reason those don't seem to help everyone, so we need to figure out what's wrong when those don't work.
> 
> In the meantime, can you share the output of `icacls "C:\Program Files\WindowsApps"` (from an admin shell?) Filing feedback on "Developer Platform > Desktop Bridge" might also help get some traces to the folks that own this.
> 
> ![image](https://user-images.githubusercontent.com/18356694/151219053-b5a4b199-9c15-42f6-bedc-8bfa86ca888a.png)
> 
> Correct WindowsApps permissions
> As a matter of cross-linking:
> 
> * [[MSIX Bucket] Launch issues caused by bad permissions on WindowsApps, and others #9452](https://github.com/microsoft/terminal/issues/9452) is our bucket for "the permissions are wrong on WindowsApps, and that will break `wt.exe`
> * [Running wt from "Run" dialog box doesn't work #10149](https://github.com/microsoft/terminal/issues/10149), [windows terminal don't open from Win + X menù #12249](https://github.com/microsoft/terminal/issues/12249) and [Unable to launch Windows Terminal Preview from Windows + X #12204](https://github.com/microsoft/terminal/issues/12204) all seem to be the same "none of the above fixed it" issues. VERY good chance I de-dupe these all.
> 
> [1]: The Win+X menu is also powered by `wt.exe`.

here you go

**Comment by zadjii-msft** [comment]
Hmm. You're on https://github.com/microsoft/terminal/releases/tag/v1.11.3471.0, which should be a stable build, so you're not hitting the same thing as #12204...

**Comment by ThemisterNaim** [comment]
if this information could help you; if I try to run `wt.exe` by `win + R` it don't work, but, if I open windows terminal or powershell or cmd, and i write `wt.exe`, those programs will open windows terminal

**Comment by ThemisterNaim** [comment]
is there anything I can to for help?

**Comment by zadjii-msft** [comment]
> if this information could help you; if I try to run wt.exe by win + R it don't work, but, if I open windows terminal or powershell or cmd, and i write wt.exe, those programs will open windows terminal

That sure is weird. I feel like there was one recently where the Run PATH was different than the one that's used by the Start Menu for some reason. 
If you open Command Prompt (cmd.exe) from Start Menu and from run, what's the output of `echo %PATH%` in each?

I am at a bit of a loss here 😕

**Comment by ThemisterNaim** [comment]
from cmd:
`C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files\dotnet\;C:\Program Files (x86)\PowerShell\7\;C:\Users\Naim\AppData\Local\Microsoft\WindowsApps;`

**Comment by zadjii-msft** [comment]
Sorry, more specifically:
* what's the output when starting cmd from the start menu?
* what's the output when starting cmd from the run dialog?

**Comment by zadjii-msft** [comment]
MSFT:37730421, MSFT:38299191 internally

**Comment by ThemisterNaim** [comment]
> [MSFT:37730421](https://task.ms/37730421), [MSFT:38299191](https://task.ms/38299191) internally

what?

**Comment by zadjii-msft** [comment]
Sorry, you're seeing a bit of a "how the sausage is made" 😅 Those are some internal bug numbers for _what appears to be_ the same issue. I was just leaving them here as notes. MSFT:38143400 too was another one I found, which I've got assigned to the Taskbar team right now to help investigate.

**Comment by hedw1gP** [comment]
Won't open. My version is 1.12.10983.0. Clicking on "Windows Terminal", nothing; Clicking on "Windows Terminal (Admin)", a UAC pops up, click Yes, nothing appears.

And by the way, now it tells me wt.exe is an unsigned application. It doesn't show "Verified Publisher: Microsoft Corporation".

![image](https://user-images.githubusercontent.com/11908157/165116045-0ff64de0-ae0d-4865-a367-9512a985770d.png)

**Comment by reyan1357** [comment]
even i'm facing the same problem as @ThemisterNaim , after upgrading to win 11 the terminal option in win+X menu is not opening terminal, plus running wt from win+R is also not working, 
i tried reset and repair in the settings>apps>Terminal 
i even tried uninstalling and then installing

nothing seems to work in this case

**Comment by hedw1gP** [comment]
@reyan1357 take a shot at this, it works for me 

https://github.com/microsoft/terminal/issues/7081#issuecomment-1065833836

**Comment by reyan1357** [comment]
> @reyan1357 take a shot at this, it works for me
> 
> [#7081 (comment)](https://github.com/microsoft/terminal/issues/7081#issuecomment-1065833836)

yeahh, it workedd after so many months, thanks a lot mann <3

**Comment by DanTheMan827** [comment]
I'm experiencing the same issue, but this is on a fresh windows reset with no files kept.

I'm hesitant on messing with the Windows Store ACLs because that's the reason that I re-installed in the first place.

**Comment by zadjii-msft** [comment]
Internal bugs show that this was fixed in build number 22591, or maybe 25091. Hard to tell how those numbers line up with the 22000.xyz series of releases. I suspect this is fixed in Insiders builds of Windows, but I have no idea how long before this rolls out more broadly.

**Comment by maxwowpow** [comment]
- from other terminal (clink/ps) 
  - admin+nonadmin: `wt.exe` - crashing.

- win+x/win+r: 
  - admin OK 1 tab 
  - admin more tabs -> crash
  - non admin -> crash

- uac active, without background darkening

**Comment by zadjii-msft** [comment]
@maxwowpow you may want to file a new issue. This one was covering a specific OS-side bug that seems like it's been resolved for a while now. 

(I'd also recommend including a Feedback Hub link ala https://github.com/microsoft/terminal/issues/12249#issuecomment-1022446222 in the new report - that'll help us track down the crashing stack)

-----

I'll close this one out, since the actual root issue was resolved a while back.
