### ISSUE TITLE
Add cursorTextColor to scheme

### ISSUE THREAD

**Issue by MrStrik3** [microsoft/terminal#12244]
Please, Add a "cursorTextColor" property in scheme definition. With a filled-box cursor, the color rendering is not great when the cursorColor is similar to the text color.

![image](https://user-images.githubusercontent.com/11462170/150992731-1d4cfaad-6558-46a5-8ca1-edc2992c6f7f.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9610 for more discussion.

/dup #9610
