### ISSUE TITLE
The terminal window resizing doesn't work when I select the image as the background

### ISSUE THREAD

**Issue by ZengIan** [microsoft/terminal#12256]
### Windows Terminal version

1.11.3471.0

### Windows build number

windows 11

### Steps to reproduce

![image](https://user-images.githubusercontent.com/41040520/151117598-70557137-3ca2-48b4-9fac-11bf51540a45.png)
lunch size
<img width="695" alt="image" src="https://user-images.githubusercontent.com/41040520/151117432-f222be76-541a-407d-b722-b72878a8651c.png">

### Actual Behavior

The terminal window resizing doesn't work when I select the image as the background.

**Comment by zadjii-msft** [comment]
I'm sorry, what do you expect to happen here? It's not really clear from your issue here what isn't working as expected. 

Changing launch size doesn't resize the current Terminal window size...

**Comment by ZengIan** [comment]
For example, I want to set the launch size: Columns 130, Rows 40, and background image is my local image, It's not the window size(Columns 130, Rows 40) I expected when I  reload the Terminal, Terminal window size display is  what I expected if I select use desktop wallpaper

**Comment by zadjii-msft** [comment]
What size is the Terminal when you've got a BG image selected? Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

**Comment by ZengIan** [comment]
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
    "alwaysShowTabs": true,
    "copyFormatting": "none",
    "copyOnSelect": true,
    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "disableAnimations": false,
    "experimental.rendering.forceFullRepaint": true,
    "experimental.rendering.software": true,
    "focusFollowMouse": true,
    "initialCols": 130,
    "initialRows": 39,
    "language": "en-US",
    "launchMode": "default",
    "profiles": 
    {
        "defaults": 
        {
            "backgroundImage": "C:\\Users\\zengc\\Pictures\\found.jpg",
            "backgroundImageOpacity": 0.35999999999999999,
            "colorScheme": "Color Scheme 10",
            "experimental.retroTerminalEffect": false,
            "font": 
            {
                "face": "JetBrainsMono NF",
                "size": 12
            },
            "padding": "8",
            "useAcrylic": true
        },
        "list": 
        [
            {
                "commandline": "powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "\u547d\u4ee4\u63d0\u793a\u7b26"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "acrylicOpacity": 1.0,
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.82999999999999996,
                "closeOnExit": "graceful",
                "colorScheme": "Color Scheme 10",
                "commandline": "powershell.exe ssh -i F:\\Key\\kubeflow-demo root@172.20.100.4",
                "cursorShape": "bar",
                "font": 
                {
                    "weight": "normal"
                },
                "guid": "{643a9f23-ee12-43c4-ad35-715db0026ec0}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-ks-master01",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.33000000000000002,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kubeflow-demo root@172.20.100.8",
                "cursorShape": "bar",
                "guid": "{16ea8f2c-a58d-4816-b260-e970d93b2e72}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-harbor",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.33000000000000002,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kubeflow-demo root@172.20.100.7",
                "cursorShape": "bar",
                "guid": "{67fc1bcc-f95b-4b7f-adc9-b704a56d3dff}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-jenkins",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.33000000000000002,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kubeflow-demo root@172.20.100.10",
                "cursorShape": "bar",
                "guid": "{152d6de5-330c-4930-8880-f20d1baf944e}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-gitlab",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.33000000000000002,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kubeflow-demo root@172.20.100.11",
                "cursorShape": "bar",
                "guid": "{560173c1-1eeb-4e62-9c6a-8a0f753ccd69}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-kubeEdge",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 0.33000000000000002,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kubeflow-demo root@172.20.201.2",
                "cursorShape": "bar",
                "guid": "{9dc2095c-e0c7-452c-9342-2447871b3498}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "peking-kube-ovn",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "backgroundImageOpacity": 1.0,
                "closeOnExit": "graceful",
                "commandline": "ssh.exe -i F:\\Key\\kp-sutb8d62 root@192.168.10.5",
                "cursorShape": "bar",
                "guid": "{500411f4-dd22-4e25-874b-aa23a3ce0c41}",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
                "name": "qy-harbor-test",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#000000",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#13A10E",
            "name": "Color Scheme 10",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#000000",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#13A10E",
            "name": "Color Scheme 11",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        }
    ],
    "showTabsInTitlebar": true,
    "showTerminalTitleInTitlebar": true,
    "useAcrylicInTabRow": true
}

**Comment by ZengIan** [comment]
I tried to use desktop wallpaper as terminal BG, and adjust windows size I expected, the dispaly is normal, Then I use local image as terminal BG, the terminal windows is also the size I expect. Thank you, it's works.
