### ISSUE TITLE
Text is too big in windows terminal.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#12250]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Steps to reproduce

Set font to Lucida Console and set font size to 14 in conhost 
look at text size
run wt
Set font to Lucida Console and set font to Lucida Console in  in windows terminal 
look at text size
see differences in text size

### Expected Behavior

Text size in window terminal is as small as text in conhost

### Actual Behavior

Text size in windows terminal is bigger than text in conhost
![Снимок экрана (120)](https://user-images.githubusercontent.com/8822292/151042621-8abf5974-4424-4f99-ac97-ef597c12db84.png)
![Снимок экрана (121)](https://user-images.githubusercontent.com/8822292/151042863-3c84d383-cba5-4d01-9b3b-ad3f931fad65.png)

**Comment by zadjii-msft** [comment]
See also #6797

> The traditional win32 console host measures fonts in pixel sizes. Unfortunately, we're not going to be changing either system to align with the other. The one the console host used was old and wrong and bad, and the one WT uses is in line with all other applications.
> Somebody recently asked for fractional font sizes, so I'm going to close this one out as a /dupe of #6678. That would help with the issue where 10 is too small and 11 is too large.
