### ISSUE TITLE
[Proposal] Add (or improve) auto-update functionality of windows-terminal

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/terminal#12251]
# Description of the new feature/enhancement

It is herein proposed to add an "auto-update" functionality to windows terminal.

If this is already enabled then please excuse my ignorance - I last
updated this two years ago.

But even if it is available, I would like to propose that this is easier
to access/find, e. g. in settings or something like that.

What would the benefit of easy auto-update be?

Well - we can get the latest features without having to manually go
to the github page and download the latest release. I am currently
doing so, so it is not a big deal for me. I actually download
on my Linux system (all binaries for windows go into a separate
directory here), then I transfer stuff to my windows system which
is elsewhere in the room.

Via auto-update I could just update to the latest windows terminal
and it would work, without me having to do manual update. (I could
perhaps enable some auto-updater, such as custom scripts, but I
want to know when I update something e. g. I want to click on
something "do update down" or so - that way my brain remembers
that this has been updated now. With an automatic auto-update
I don't really know when it was last updated really.)

I believe other users may also benefit from this. Many other
software, such as browsers, have auto-update.

# Proposed technical implementation details (optional)

Well - time is finite, and I am not suggesting that this
functionality gets too much developer time. I think a simple
menu-entry, perhaps an additional one, in settings, or a 
tab, should suffice, e. g. "update to the latest stable
windows terminal" (with a hover tip perhaps) and that's
it really. Nothing fancy, keep it simple.

IF this is already possible then perhaps it could be
put more prominently. I will have to update it manually
first, then I can check whether there is an auto-update
functionality. (My windows terminal release is from 
2020 to no idea what has changed in the last 2 
years. 95% of my time I tend to use my Linux
main machine, but I want to have windows as well
to test tons of things, including java-related binaries.)

At any rate, I will end this issue request here - I believe
you folks can decide whether this may be useful/beneficial
to enable. (I only suggest this to stable releases; while
one could do so for all releases, I think focusing on 
stable is the simplest solution here.)

**Comment by zadjii-msft** [comment]
If you install the Terminal from the Store, then that'll auto-update for you. That's our auto-updating solution 😉
