### ISSUE TITLE
Pressing Media keys in terminal after changing bell sound replays the bell

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12258]
Regressed in #11511

#### Repro steps
1. change the bell sound to honk, 
2. Emit a bell (tab in `bash` with an empty cmdline is easy)
3. press the media Play button with the Terminal focused

#### Expected
Media toggles play/pause

#### Actual
get honk

**Comment by DHowett** [comment]
HAHAHAHAHA does it also show up in the media play flyout provided by the OS?
