### ISSUE TITLE
Why does terminal installation require firewall running?

### ISSUE THREAD

**Issue by chenwng** [microsoft/terminal#12269]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1288

### Steps to reproduce

Disable firewall and install the release bundle downloaded from github.

### Expected Behavior

The installation can complete successfully

### Actual Behavior

Installation failed with error:

```text
App installation failed with error message: error 0x80073D0A: Failed to update package Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe because the firewall service is not running. Ensure that the firewall service is enabled and started. (0x80073d0a)
```

My question is why the installation requires firewall running?

**Comment by zadjii-msft** [comment]
I honestly don't know - that must just be something that the Store / package catalog require to install packages. I doubt that'd be unique to the Terminal - that's likely required for _any_ package.

**Comment by chenwng** [comment]
Thanks for response. Installation of wget-cli msixbundle gave me the same error with firewall off. I really don't understand why the packaging would require such a thing.

I had to turn off Windows Firewall, because it consumes 100% CPU after one update and I cannot solve the issue. Now I have to enable it temporally to install the terminal :(
