### ISSUE TITLE
'"C:"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by raspy313** [microsoft/terminal#12268]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.985

### Other Software

When running cmd.exe through windows terminal or otherwise, terminal spits out

Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. All rights reserved.
'"C:"' is not recognized as an internal or external command,
operable program or batch file.

I haven't found a fix for this yet.

My shortcut to Command Prompt in the Windows System folder has been modified to start in [ c:\ ] . Changing this back to the default starting location does not fix the issue. I also noticed windows terminal automatically point to the %HomeDrive%%HomePath% directory when a new page is opened, so I see this terminal application as an advanced shortcut or even GUI for cmd.exe.
This being said both methods (and some others ) for booting command prompt all show the same error being : 
" '"C:"' is not recognized as an internal or external command,
operable program or batch file. "

This obviously points to the issue being something to do with the version calling command , or something further from the shell , which I am not versed in dealing with .. Otherwise this error causes no real issues , it's just sort of annoying to see every time I open the shell . Any solutions for getting rid of this junk text would be super appreciated :)

### Steps to reproduce

null

### Expected Behavior

To not see the error
'"C:"' is not recognized as an internal or external command,
operable program or batch file.

### Actual Behavior

Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. All rights reserved.
'"C:"' is not recognized as an internal or external command,
operable program or batch file.

c:\>

**Comment by 237dmitry** [comment]
> My shortcut to Command Prompt in the Windows System folder has been modified to start in [ c:\ ]

Try to set or change `startingDirectory` in `Command Prompt` profile

![Screenshot 2022-01-27 144453](https://user-images.githubusercontent.com/78153320/151353016-fabc8293-e8b9-487e-9b1a-18de71e8b910.png)

**Comment by zadjii-msft** [comment]
@raspy313 What's the output of the following two commands?

```cmd
reg query "HKCU\Software\Microsoft\Command Processor"
reg query "HKLM\Software\Microsoft\Command Processor"
```

**Comment by raspy313** [comment]
![image](https://user-images.githubusercontent.com/79676086/151456226-cd49283a-2099-4db8-b859-0af46a3696d9.png)


> @raspy313 What's the output of the following two commands?
> 
> ```batchfile
> reg query "HKCU\Software\Microsoft\Command Processor"
> reg query "HKLM\Software\Microsoft\Command Processor"
> ```
![image](https://user-images.githubusercontent.com/79676086/151456243-9c3e037a-1f59-46ef-8505-b6cbe788f06b.png)

**Comment by zadjii-msft** [comment]
Well that'll do it. Delete that regkey. I'd be suspicious of anything that did write to that reg key 👀

**Comment by raspy313** [comment]
deleting the AutoRun Value data fixed the issue. Default starting directory is still c:\ . thank you
