### ISSUE TITLE
Terminal redraw OSC cursor color

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#12263]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.1.2

### Steps to reproduce

1. Change cursor color by osc sequence ```"`e]12;#ff0000`a"```
2. Change keyboard layout `Win+Space` when window of terminal is active.

### Expected Behavior

After pressing the keyboard shortcut, the cursor color will remain the same.

### Actual Behavior

The cursor color changes to the one specified in the color scheme in settings.json

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11522 for more discussion.

/dup #11522
