### ISSUE TITLE
A bunch of settings don't get duplicated

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12265]
> How did the X macros for settings not help this?

Apparently we didnt use the macro for `CascadiaSettings::DuplicateProfile`!

`UseAtlasEngine`, `BellSound`, and `Elevate` are all missing from the duplicate. Connection type too, but that one's... tricky maybe. `Opacity` is duplicated, but it's not otherwise in the appearance macro. Uh oh.

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/pull/12257#issuecomment-1022657199_

**Comment by zadjii-msft** [comment]
We should really use the macros for these. `MTSM_PROFILE_SETTINGS` et. al.

**Comment by ianjoneill** [comment]
So I've done a quick comparison between the macros and the duplicate method. Given the number of differences, I think I'm going to have to pass up on my offer of fixing this - I don't know the consequence of some of the properties not currently existing in the macro!

## Profile settings
### Missing from duplicate but in `MTSM_PROFILE_SETTINGS`
* `BellSound`
* `Elevate`
* `UseAtlasEngine`

### Missing from `MTSM_PROFILE_SETTINGS` but duplicated
* `Padding`
* `TabColor`

`ConnectionType` is duplicated, but special cased at the end (#12120)

## Font settings
All good 🎉 

## Appearance settings
### Missing from `MTSM_APPEARANCE_SETTINGS` but duplicated
* `Background`
* `CursorColor`
* `Foreground`
* `Opacity`
* `SelectionBackground`

**Comment by zadjii-msft** [comment]
@ianjoneill that's perfectly reasonable. As soon as I saw how the two had diverged I was a little worried about asking an external contributor to help with that mess 😅 

Thanks for the great write-up! This should make our lives a lot easier
