### ISSUE TITLE
Can't override bell sound?

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12276]
1. put the honks in `profiles.defaults`
2. set a profile to `bellSound: null`
3. bell Terminal

expected:

No honks, normal bell

actual:

N O T H I N G

**Comment by miniksa** [comment]
NO HONKS?! THIS IS SHIP BLOCKING, @zadjii-msft!

**Comment by miniksa** [comment]
![image](https://user-images.githubusercontent.com/18221333/151455555-dd403a6f-00ad-4565-9de0-b5aaf1642798.png)

**Comment by zadjii-msft** [comment]
fixed in bcc2ca04f, i'll file the PR tomorrow morning
