### ISSUE TITLE
Defaults directory not working

### ISSUE THREAD

**Issue by sheeneric** [microsoft/terminal#12274]
### Steps to reproduce

1. Click the "Defaults" tab on setting
2. Set the "starting directory" to D drive
3. Check "Use parent process directory" for the rest of tabs (e.g. powershell tab)
4. The start directory led to system32 folder

### Expected Behavior

If I checked "Use parent process directory", then it should follow the rule on "Defaults" tab

### Actual Behavior

When I set the defaults "starting directory" on D drive, it does not suppress the directory but sets the directory as null. This led to start directory to system32

**Comment by zadjii-msft** [comment]
What Terminal version?  Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?
