### ISSUE TITLE
I can't personalize my terminal with oh my posh

### ISSUE THREAD

**Issue by Toovil** [microsoft/terminal#12279]
Hi! I'm having this trouble when I tried to use Oh My posh to personalize my terminal:
![Captura de pantalla 2022-01-27 233645](https://user-images.githubusercontent.com/28720267/151489021-190c4870-cefa-4b1e-af53-e22cf0ff61a3.png)

"Get-PoshThemes: The term 'Get-PoshThemes' is not recognized as a cmdlet name,
function, script file, or executable program. Check if you typed correctly
name or, if a path is included, check that the path is correct and try
again
Online: 1 Character: 1"

help pls :(

**Comment by 237dmitry** [comment]
As an assumption, since I have never used oh-my-posh.
If `oh-my-posh` is a module, and `Get-PoshThemes` is its cmdlet or function, then try loading it.
```
Import-Module oh-my-posh
```
If `Get-PoshThemes` is a standalone script then check where it is and launch it with full or relative path or add its path to `$env:PATH`
```
$env:PATH += ";C:\Path\To\Folder"
Get-PoshThemes
```

**Comment by zadjii-msft** [comment]
How did you try to add oh-my-posh? What version of oh-my-posh are you using? Did you follow [this guide](https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#customize-your-powershell-prompt-with-oh-my-posh), or something else?
