### ISSUE TITLE
Bottom part of SUI has a giant black bar on it

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12271]
### Windows Terminal version

main a13b207

### Windows build number

10.0.22000.0

### Steps to reproduce

Build a13b207

### Expected Behavior

Windows 11 style applied to each SUI element.

### Actual Behavior

`Discard charges` almost indistinguishable from the black background:

![wt_dev_settings](https://user-images.githubusercontent.com/3933920/151399070-3e6244f3-9f74-4734-b8d7-1b46582465be.png)

Non-Win11 style:

![wt_pre_settings](https://user-images.githubusercontent.com/3933920/151399175-35a7fcfd-f3bc-4ec4-849c-c6c401b115e0.png)

**Comment by zadjii-msft** [comment]
We're already working on that over in #11720 and #12144

**Comment by PankajBhojwani** [comment]
Yep, this was fixed in #11720

**Comment by zadjii-msft** [comment]
Nice
