### ISSUE TITLE
[VT Render] Investigate not breaking lines for node-pty

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1227]
From MSFT:19012792

-----------

I didn't have any details in here. I presume that this was to track trying to not render a `\r\n` at the end of a line, so that a terminal would wrap the line itself. IIRC I tried that in RS5, but it broke something else, and there wasn't time to get it working for that release, so we reverted it.

**Comment by JDTX** [comment]
Related: https://github.com/microsoft/terminal/issues/405

**Comment by zadjii-msft** [comment]
I've been up and down the internal PRs around this time, and I can't find where this originally came from. The original bug has no details in it other than "it was a revert of something in the RS5 timeframe". I recall making some change to wrapping and having to revert it, but I can't find it, or the original bug.

Chances are, we've already fixed this along the way. I'm closing this.
