### ISSUE TITLE
set terminal-type for SSH session

### ISSUE THREAD

**Issue by theking2** [microsoft/terminal#12288]
Is it possible to specify the terminal-type (for instance vt100 for vi) in Terminal or ssh?

**Comment by zadjii-msft** [comment]
You mean like, setting `TERM`? I believe that WSL sets TERM to `xterm-256color` by default. I dunno about `ssh.exe`, but I imagine it sets the same value. I think some additional details on your scenario might help me help you 😉

**Comment by theking2** [comment]
I mean exactly that. on a remote (linux) system I connected to ssh I use vi. vi seems to work only with vt100 or vt220. The ssh I use is the one in Windows.

**Comment by zadjii-msft** [comment]
> vi seems to work only with vt100 or vt220

That's certainly not what I'd expect. Can you add more details? What's not working as expected? If we're not working properly under `xterm-256color` we need to fix that 😉

**Comment by theking2** [comment]
easy:
connect to archlinux box 
open a file with vi
type i to insert and type text. existing text appears overwritten but actually is not
close vi :wq
type export TERM vt220
open a file with vi
type i to insert and type text. existing text is pushed to the right.

**Comment by zadjii-msft** [comment]
> type i to insert and type text. existing text appears overwritten but actually is not


Hmm. That sounds like #1947. What's the output of infocmp when connected to that machine?

**Comment by kingma-sbw** [comment]
display: flex;
  align-items: center;
  justify-content: right;

**Comment by zadjii-msft** [comment]
```
smir=\E[4h
rmir=\E[4l
```

Yep, those are the IRM sequences. Sounds like /dup #1947 to me. Thanks!
