### ISSUE TITLE
[WSL2] Oh My Posh Themes broken on new tab startup

### ISSUE THREAD

**Issue by IsaacLf** [microsoft/terminal#12280]
### Windows Terminal version

Windows Terminal Preview Version: 1.12.3472.0

### Windows build number

19043.1469

### Other Software

- on-my-posh v7.5.1 (in WSL2, Ubuntu 20.04)
- CaskaydiaCove NF (Cascadia Code Nerd Font) installed on Windows

### Steps to reproduce

Once you configured your bash with Oh-My-Posh theme (the theme I'm using is: `powerlevel10k_rainbow`) and your Nerd Font.

1. Open a new instance of Windows Terminal or a new tab of WSL2 (Ubuntu in this case).

### Expected Behavior

1. The terminal should render the theme correctly, from startup:
![image](https://user-images.githubusercontent.com/36938997/151510178-d1d62635-f888-4ccd-aa4e-bb70c5a8a47f.png)

As example, in vscode terminal, when you open a new WSL terminal, will load correctly (that's the expected behavior from Windows Terminal as well):
![image](https://user-images.githubusercontent.com/36938997/151510423-86132f2c-917b-4507-9cb5-776ef3fc289a.png)

### Actual Behavior

1. The terminal shows _broken_ (not as expected), as following:
![image](https://user-images.githubusercontent.com/36938997/151509945-3437384d-93b6-43c1-881e-371a30ea1419.png)

You can clear the console with `clear` command and the console will look as expected, but it's broken from startup (new terminal instance or new tab)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8341 for more discussion.

/dup #8341
