### ISSUE TITLE
Bad german translation

### ISSUE THREAD

**Issue by jfheins** [microsoft/terminal#12297]
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19042.0

### Steps to reproduce

I run a command in Azure cli and it terminated with an error code > 0

### Expected Behavior

The settings translate termination as "Profilbeendigung" which is ok
So the translated sentence would be better as:

> Das Verhalten bei Beendigung kann in den erweiterten Profileinstellungen konfiguriert werden.

### Actual Behavior

Somethimes there is an info bar shown, informing about abnormal termination of the shell:
![image](https://user-images.githubusercontent.com/5293502/151789752-33b24570-aba9-4441-8dd6-587fef9f1fa0.png)
"Kündigung" would be "termination of a contract" like when a lease ends unilaterally or you terminate a mobile phone contract.

**Comment by lhecker** [comment]
Tracked as MSFT:38109276.

I've submitted the request for translation as:
> Das Beendigungsverhalten kann in den erweiterten Profileinstellungen konfiguriert werden.

Do you agree with that translation?

**Comment by jfheins** [comment]
Yes, sounds good to me 👍

**Comment by lhecker** [comment]
This issue has been resolved internally and will be part of the next release.
