### ISSUE TITLE
nothing happens, then "access denied" after 2 minutes

### ISSUE THREAD

**Issue by audetto** [microsoft/terminal#12295]
Hi,

unfortunately I am on a corporate network with lock down versions of Windows 10.
I managed to download and install the msixbundle from github, and Windows Terminal even shows up in settings, start etc...

But when I click on it via Start Menu nothing happens, and after a while I get a dialog box telling me the application had an error.
If I execute wt.exe in a console, after the same amount of time, I get a singe line printed "access denied".

I know, there is very little in this issue, but does this ring any bell?

I am trying to compile it with VS2019 (to look at it in debug), but this is proving harder than expected.

**Comment by j4james** [comment]
This sounds like #6010.

**Comment by zadjii-msft** [comment]
It very well might be. @audetto if you can download the msixbundle, then I might recommend taking that `.msixbundle`, renaming the extension to `.zip`, then unzipping that, and inside you'll find three `msix` files. Again, rename the one for your architecture to `.zip` and unzip that. Inside there should be a `windowsterminal.exe` which you should be able to run directly. WE call this "running unpackaged". That migh work around whatever corporate IT policy they have in place.

**Comment by audetto** [comment]
Yes.
Works!

thank you
