### ISSUE TITLE
Action error

### ISSUE THREAD

**Issue by h7ml** [microsoft/terminal#12291]
[linter](https://github.com/microsoft/terminal/actions/workflows/linter.yml)
![image](https://user-images.githubusercontent.com/55233292/151686447-7eff4d3d-03d3-4697-bb90-3fc9719175e8.png)
``<html>
<body>
<div class="application-main " data-commit-hovercards-enabled="" data-discussion-hovercards-enabled="" data-issue-and-pr-hovercards-enabled="" style="box-sizing: border-box; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div itemscope="" itemtype="http://schema.org/SoftwareSourceCode" class="" style="box-sizing: border-box;"><main style="box-sizing: border-box; display: block;"><div class="clearfix new-discussion-timeline container-xl px-3 px-md-4 px-lg-5" style="box-sizing: border-box; max-width: none; margin-right: auto; margin-left: auto; padding: 0px !important; width: 1920px;"><div class="repository-content " style="box-sizing: border-box; width: 1920px;"><div class="px-3" style="box-sizing: border-box; padding-right: 16px !important; padding-left: 16px !important;"><div class="d-flex flex-column flex-md-row" style="box-sizing: border-box; flex-direction: row !important; display: flex !important;"><div class="flex-auto ml-md-4 min-width-0 " style="box-sizing: border-box; flex: 1 1 auto !important; min-width: 0px !important; margin-left: 24px !important;"><div class="flex-auto pb-5" style="box-sizing: border-box; flex: 1 1 auto !important; padding-bottom: 32px !important;"><div class="js-updatable-content js-socket-channel" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjQxNjc4MjQyNjciLCJ0IjoxNjQzNTE2MzA3fQ==--07f72a147cf53b3b18e58645bc2bf31dc9be293db979d2c1556be15c7a95f303" data-url="/microsoft/terminal/actions/runs/1386792412/annotations_partial" style="box-sizing: border-box;"><div class="actions-fullwidth-module color-bg-default color-shadow-small mb-3 pt-3 pb-1 border rounded" style="box-sizing: border-box; border: 1px solid var(--color-border-default)  !important; border-radius: 6px !important; box-shadow: var(--color-shadow-small)  !important; background-color: var(--color-canvas-default)  !important; margin-bottom: 16px !important; padding-bottom: 4px !important; padding-top: 16px !important;">

No event triggers defined in `on`
--

</div></div><div id="artifacts" class="js-updatable-content js-socket-channel" data-channel="eyJjIjoid29ya2Zsb3dfcnVuOjEzODY3OTI0MTI6ZXhlY3V0aW9uIiwidCI6MTY0MzUxNjMwN30=--e7a5605fda2be5d99718b9ffa88dc8c46348216634872b51cae87ff9d20125c3 eyJjIjoid29ya2Zsb3dfcnVuOjEzODY3OTI0MTI6YXJ0aWZhY3RzIiwidCI6MTY0MzUxNjMwN30=--477400fd374421554db6bcabee293ad7a9058d0794359e6e9fb7ffccfeaa8aec" data-url="/microsoft/terminal/actions/runs/1386792412/artifacts_partial" style="box-sizing: border-box;"></div></div></div></div></div></div></div></main></div></div><br class="Apple-interchange-newline">
</body>
</html>``

**Comment by zadjii-msft** [comment]
We turned the linter off like a year ago: #8152, #8162. So any runs that are left in there are from branches that haven't merged with main since then. Nothing to see here.
