### ISSUE TITLE
New terminal does not handle theme change event.

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1230]
From MSFT:21424988
I have to restart the new terminal to see the effects of changing between light and dark windows theme.
You can see at the attached screenshot that the tabs haven't changed it's colors after I changed from Dark to Light theme. UWP apps are supposed to do that by default.

**Comment by DHowett-MSFT** [comment]
This one is interesting. We could probably tackle it as part of #1125, but maybe we want to keep it separate?

**Comment by Aarklendoia** [comment]
The window border as well as the area with the Minimize, Maximize and Close buttons does not take the color of the theme (remains white despite the dark theme).

**Comment by Aarklendoia** [comment]
![image](https://user-images.githubusercontent.com/1765298/59417205-17464400-8dc7-11e9-80df-c29687f7f076.png)

**Comment by Mercurial** [comment]
same here , anyone know how to fix this?

**Comment by DHowett-MSFT** [comment]
To be blunt: somebody needs to write the code to do this. If we do it, it will come out whenever we are done. If we don’t, we will get back to it eventually.

**Comment by AnuthaDev** [comment]
@DHowett May I work on it??

**Comment by DHowett** [comment]
@AnuthaDev you certainly may :smile:

**Comment by StefanScherer** [comment]
Yes please change the window title according to the dark/light theme in Windows. I also have to close and re-open the terminal to fully switch. The theme itself I change the settings.json at the moment, configuring two themes, one for dark, another for light and let it auto-switch according to Windows theme would be even better.

![wt-toggle-theme-title-bar-issue](https://user-images.githubusercontent.com/207759/89029374-99c4f680-d32e-11ea-8cda-cb5b95b98905.gif)

**Comment by mdtauk** [comment]
Not sure if this is a XAML Island thing, but if you are using Xaml ThemeResources - they should update and refresh as the RequestedTheme changes.

**Comment by zadjii-msft** [comment]
This is almost _certainly_ Islands related. I'm not sure what window message is sent when the theme changes, but there almost certainly should be one...

**Comment by AnuthaDev** [comment]
@zadjii-msft I think it's this one: WM_SETTINGCHANGE

**Comment by Robinzon100** [comment]
> Yes please change the window title according to the dark/light theme in Windows. I also have to close and re-open the terminal to fully switch. The theme itself I change the settings.json at the moment, configuring two themes, one for dark, another for light and let it auto-switch according to Windows theme would be even better.
> 
> ![wt-toggle-theme-title-bar-issue](https://user-images.githubusercontent.com/207759/89029374-99c4f680-d32e-11ea-8cda-cb5b95b98905.gif)

can you share how you did this?

**Comment by StefanScherer** [comment]
@Robinzon100 my theme switching is done in this [bash script `t`](), it changes the `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize` -> `SystemUsesLightTheme` and `AppsUseLightTheme` and updates the `$WINHOME/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json`

I would prefer to just configure a dark and light theme in the terminal and let it update automatically depending on the  system theme setting in the registry.

**Comment by TBBle** [comment]
I would guess the `t` command is doing something like
```
New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0 -Type Dword -Force
```
(but using 1 if the current value is 0) and also JSON-editing settings.json for Terminal to change the theme, which WT will immediately apply when it notices the file change.

**Comment by olegKusov** [comment]
Hi , is there any update on fix? How can we get theme auto switching and config for default light and default dark themes ?

**Comment by zadjii-msft** [comment]
Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by olegKusov** [comment]
> Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
> ![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
> That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

Hi, thanks for feedback. Is there any dificulties? How can we help? Because for me automatic theme switching is now the basic OS feature. After MacOS where I use automatic dark theme in terminal, Windows start to look very outdated. And issue created 3 years ago.  Are you need some help?

**Comment by j4james** [comment]
> Do you need some help?

Given that the issue is labelled "Help Wanted", I think it's safe to assume that's a yes. 😉

If you'd like to help, let the team know that you want to work on the feature, and explain briefly how you intend to implement it. You can find more information in the [Contributor's Guide](https://github.com/microsoft/terminal/blob/main/CONTRIBUTING.md#contributing-fixes--features).

**Comment by zadjii-msft** [comment]
Yep, there's no real reason we haven't done this other than simply resourcing. We've only got so many devs, and something like 10,000 issues that have been active since the Terminal was first released 😄

**Comment by JasonWei512** [comment]
https://user-images.githubusercontent.com/16899918/122917658-d52a4280-d390-11eb-91b6-5d2dd96942ae.mp4

For some mysteries reason, Windows Terminal 1.8.1521.0 follows system theme on Windows 11, but not on Windows 10.

**Comment by zadjii-msft** [comment]
Huh, that's totally right, this did seemingly get fixed in Windows 11. That seems to me to imply that there was actually just an OS bug that was the actual root cause for this one. I'm gonna close this one out as external - there's _maybe_ something that we could do to fix this on Windows 10, but the fact that an OS fix remedied this makes me think that would be a futile effort.

**Comment by j4james** [comment]
@zadjii-msft I actually have a fix for this on Windows 10 which is not that complicated. Is it worth submitting a PR, or would you rather just leave it as is?
