### ISSUE TITLE
Font doesn't render properly

### ISSUE THREAD

**Issue by bryant-the-coder** [microsoft/terminal#12310]
I have installed fonts that supports italics. But when i use neovim, the fonts are not render correctly. Please tell me what is wrong. It does not face this problem before.

**INCLUDING CASCADIA CODE**

**Comment by bryant-the-coder** [comment]
![unknown.png](https://user-images.githubusercontent.com/92417638/151964681-3c4af380-3d39-42b2-8ae9-feb8943be5f6.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9381 for more discussion.

/dup #9381
