### ISSUE TITLE
Maximizing Terminal after enabling tabs in title bar cuts off the first column of text on some resolutions

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1231]
From MSFT:21408490

If I enable the setting `experimental_showTabsInTitlebar` then maximize the window on a vertical monitor (1080x1920), the first column of text is cut off. Screenshot attached.
![image](https://user-images.githubusercontent.com/18356694/59379370-08ef1e00-8d1c-11e9-827f-a28b7f119632.png)

**Comment by DHowett-MSFT** [comment]
I believe this to be a duplicate of #1055. Confirm?

**Comment by zadjii-msft** [comment]
Yep totally is.
