### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by KineticTheory** [microsoft/terminal#12316]
### Windows Terminal version

1.11.3471.0

### Windows build number

Microsoft Windows [Version 10.0.19043.1466]

### Steps to reproduce

1. Reboot the computer
2. Start WindowsTerminal and Open a tab for Ubuntu 20.04 (WSL2).
3. Monitor "Windows Terminal" in Task Manager.
4. CPU utilization starts at 2-4% and then slowly climbs to exceed 90% even though the terminal is idle and acrylic features are disabled.
5. This behavior started after installing the January Windows 10 patches.
6. I only see this behavior when running WSL2 tabs.  No processes are using CPU (checked with `ps -aux`). No other Windows process are consuming significant CPU.

### Expected Behavior

CPU utilization for an idle terminal should be very low (certainly less than 5%).

### Actual Behavior

If left overnight CPU utilization will exceed 90% of the CPU.  Killing WindowsTerminal and restarting it resets CPU utilization to 2-4%, but it will grow over time back to very high values.  

![wt-about](https://user-images.githubusercontent.com/17579601/152021074-77c61268-d5d4-432b-9462-372a26e84027.jpg)

![taskman](https://user-images.githubusercontent.com/17579601/152021094-03fed545-edb1-411e-907e-b71e09e59b91.jpg)

In this screenshot, cpu utilization is 28% on a machine with 12 cores (24 hw threads) and the terminal is idle (no running processes).

**Comment by zadjii-msft** [comment]
Can you expando that Terminal entry? It shows there are 10 processes attached to the Terminal, so I can't be sure which process is the one using the CPU:

![image](https://user-images.githubusercontent.com/18356694/152022655-1b1db187-c82c-408a-b54d-471c4b8eb8cd.png)

If it's either a OpenConsole.exe or a WindowsTerminal.exe that's using up the CPU, a dump might be helpful:

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)

**Comment by KineticTheory** [comment]
Here's my current session (3 Ubuntu tabs and one powershell):

![image](https://user-images.githubusercontent.com/17579601/152024427-c34fa79f-c9a6-4d36-b403-1cff3fbb4b24.png)
