### ISSUE TITLE
⠋  character not rendering

### ISSUE THREAD

**Issue by python-coding-404** [microsoft/terminal#12314]
### Windows Terminal version

1.7.3651.0 WSL 1

### Windows build number

19043.1466

### Other Software

Nanospinner

### Steps to reproduce

run a program that uses nanospinner.js 
the issue lays with in the characters that it uses like ⠋
![Screenshot (24)](https://user-images.githubusercontent.com/79223364/151990188-18762f41-b4c6-47fd-a3de-651ab2124a30.png)

### Expected Behavior

a spinner character

### Actual Behavior

it gave the question mark symble

**Comment by zadjii-msft** [comment]
FWIW That looks like conhost, the vintage console host, not the Windows Terminal. Also, 1.7 is almost 5 releases out of date - you might want to consider updating the Terminal 😉 

Which font are you using? I don't believe that Consolas has the braille characters in it, and conhost doesn't do font fallback (at least, not the version in Windows 10)

**Comment by j4james** [comment]
> I don't believe that Consolas has the braille characters in it, and conhost doesn't do font fallback (at least, not the version in Windows 10)

Yeah. I'm still on Windows 10 and can confirm that _Consolas_ doesn't have braille, but _Cascadia Code_ does, so switching fonts would be one option.
