### ISSUE TITLE
Allow start on login option to launch a hidden quake window

### ISSUE THREAD

**Issue by Kytech** [microsoft/terminal#12327]
# Description of the new feature/enhancement

Enable Windows Terminal to prepare a hidden quake window on machine startup, preventing the need to first issue the quake mode command from a regular window. Presently, enabling the "launch on machine startup" option only launches a regular window at startup, when it would be nice if the startup behavior prepared a quake window for easy access after startup. Ideally, Windows Terminal should be able to listen to the quake command at machine startup/user login without needing to first start a regular terminal window. Additionally, exiting the shell in the quake terminal (ex via the `exit` command) requires repeating this process to have a quake terminal available. Ideally, the quake mode command would spawn a new quake window if one doesn't exist.

# Proposed technical implementation details (optional)'

Ideally, the Windows Terminal application could be configured so that it's "launch on machine startup" behavior can either A: Launch a regular terminal window as presently implemented, or B: Start a background process that listens to the quake command shortcut, showing the quake window if it already exists, or launching a new one if it does not exist. This process could either be implemented as a service or, probably more ideally, as a user-level background process that creates a tray icon, similar to how PowerToys works to allow it's features to run on startup/login. The system tray icon method is also the same technique that KDE uses for Yakuake on Linux for another project to reference that implements this well.

The use case of this feature, when enabled, would be something like the following: User logs on -> Windows terminal background process/tray process starts on login without showing anything to the screen -> User activates quake command via keyboard -> If quake window currently exists, show it. If not, create the new quake window.

Might be related to #7374, but this feature seems to be a bit larger in scope.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We've been using #9996 to track this request (more or less), so please refer to that thread for more discussion.

/dup #9996
