### ISSUE TITLE
WSL instances won't display the tab title set in SUI

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12323]
### Windows Terminal version

main fbe0416

### Windows build number

10.0.19044.0

### Other Software

WSL Ubuntu, Arch & Fedora

### Steps to reproduce

- set `Tab title` in SUI

### Expected Behavior

- new WSL tab to have defined `Tab title`

### Actual Behavior

- WSL instances won't show `Tab title` from `settings.json`, instead it shows `user@host`
- it does show correct tab title for `Powershell` and `Command Prompt`

Sample setting for WSL Ubuntu:

```
           {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "~",
                "tabTitle": "Ubuntu"
            },
```

and terminal:

![wt_tab_title_no_update](https://user-images.githubusercontent.com/3933920/152067062-c19f61c8-dc2b-4a76-b3c0-dcf91011245f.png)

**Comment by DHowett** [comment]
you probably want this setting too:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/189190/152071335-ab808895-8643-4c07-af70-327405d70b3d.png">
