### ISSUE TITLE
Focused `Color schemes` not showing top border

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12328]
### Windows Terminal version

main d07c536

### Windows build number

10.0.22000.0

### Steps to reproduce

select `Color schemes` and tab to focus drop-down options

### Expected Behavior

focus border all around

### Actual Behavior

top focus border not shown:

![color_not_aligned](https://user-images.githubusercontent.com/3933920/152089272-840447da-2ccd-427c-8e4e-afb8cbf0fca0.png)

**Comment by zadjii-msft** [comment]
Yep, that's real, even on #12326. Linking to #11353
