### ISSUE TITLE
Can this be installed on win server 2k19?

### ISSUE THREAD

**Issue by eliassal** [microsoft/terminal#12339]
### Windows build number

 0.0.17763.0 Microsoft Windows NT 10.0.17763.0

### Steps to reproduce

I am trying to install windows terminal on win2k19 with choco, I get 

`choco install microsoft-windows-terminal`
I get

> This package requires at least Windows 10 version 1903/OS build 18362.x

What is this OS build 18362.x, and to which windoes it is refering? is it refering to win server 2022 or 20H!!!

Thanks for your help

### Expected Behavior

Install windows terminal on win2k19

### Actual Behavior

No going thrugh with Choco

**Comment by zadjii-msft** [comment]
[Please read the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version). 

This chart might be useful: https://en.wikipedia.org/wiki/Windows_10_version_history, or this one: https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions

I'm under the impression that the next Server Release after Server 2019 was Server 2022, which should support the Terminal.

**Comment by eliassal** [comment]
I upgraded to win 2022 and setup went through. Thanks
