### ISSUE TITLE
Windows freezes on ultrawide.

### ISSUE THREAD

**Issue by dragonifnotifiswat** [microsoft/terminal#12338]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Other Software

None

### Steps to reproduce

Using ultrawide 34 inch 144hz samsung.
Resolution 3440x 1440

125% scaling 

### Expected Behavior

Trying to run processes as django, redis etc etc for debugging. 

### Actual Behavior

Im using WSL2 and cmd and my tabs keeps freezing, processes remains active but the terminal tab is frozen.
I can still close and open new tabs and scroll, when I am scrolling the scroll bar to the right movies but the text is frozen.
I suspect this has to do with my ultrawide resolution. 
Its keep happening over and over again, sometimes a window will work for an hour sometimes for 20min.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

Do you have a non-ultrawide monitor you could compare with, to try and narrow down that element of the root cause here?

**Comment by dragonifnotifiswat** [comment]
Uploaded the settings file 

I have a 2nd 25 inch regular monitor horizontally, it also freezes when I place the terminal on that screen. My main monitor is connected with DP and the 2nd with hdmi
This has been happening on and off for a couple of months.



Here is the settings file 


[settings.odp](https://github.com/microsoft/terminal/files/7995384/settings.odp)

**Comment by dragonifnotifiswat** [comment]
Uploaded short video if the issue
https://user-images.githubusercontent.com/97830593/152365855-991d0ffd-0e18-46dc-b6fe-25825d04e4e1.mov

**Comment by dragonifnotifiswat** [comment]
created a short video of the issue 

https://user-images.githubusercontent.com/97830593/152366401-d93da7d0-f79e-43a3-9dcd-89bc7afeab52.mov

**Comment by zadjii-msft** [comment]
Curious. At least we've ruled out the "ultrawide" aspect of this bug! I wonder if selecting text might trick the renderer into repainting the screen. 

Do either of [these settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/rendering) mitigate the issue? Maybe there's a graphics driver issue.
