### ISSUE TITLE
Bundle ColorTool with WT release

### ISSUE THREAD

**Issue by eabase** [microsoft/terminal#12330]
It would be excellent to be able to find a pre-compiled latest version of `ColorTool.exe` as part of the WT release package, especially since it also seem to be regularly updated.

Atm. and AFAICT, there is no link to to that binary anywhere. 
(Did I miss something?)

**Comment by 237dmitry** [comment]
> Atm. and AFAICT, there is no link to to that binary anywhere.

 https://github.com/microsoft/terminal/releases/tag/1904.29002

**Comment by zadjii-msft** [comment]
> especially since it also seem to be regularly updated

that's not strictly true:

![image](https://user-images.githubusercontent.com/18356694/152151406-801066a2-f65a-4f28-b70d-6e2945ad6c64.png)

It just so happens to have gotten a couple bugfixes recently. We probably should push a new release of that alongside this next WT release.

**Comment by zadjii-msft** [comment]
There's a couple of factors at play here, but the most important one is: Terminal ships in box with the Windows OS now, so every component that goes into the Terminal package ships to everyone on all versions of Windows. And frankly, colortool doesn't really have the usage numbers to merit being included in the OS. It's a nice tool absolutely, and one we should probably cut a fresh release of sometime soon. But we're not gonna ship this _with_ the Terminal any time soon. Sorry about that!

Maybe if there was a "Console PowerToys" package, we'd consider putting ColorTool there 😆

**Comment by rollingmoai** [comment]
Updates on this? ColorTool seems to have new features which haven't been released yet.

**Comment by GazerGirl49** [comment]
The "allcolors" option does not work, and when I went to see the "README" page for the version of ColorTool I installed (2019), it does not exist. The fact that current "README" page still links to this outdated version is quite sad.
