### ISSUE TITLE
Split Terminal (Alt + Shift + D) to open on the same exact path as the Parent

### ISSUE THREAD

**Issue by j0nimost** [microsoft/terminal#12331]
# Description of the new feature/enhancement
I would like it if we could have a feature where splitting the terminal window opens on the same exact path. 
Most of the time when I use the Split feature is because I am working on the same path and I am comparing changes, between the two windows.

A user who uses the split feature most likely is using it for:
- accessing subfolders
- Comparing changes
- Running multiple commands

This feature would especially be powerful for **Windows Powershell** since it's native to the Windows ecosystem.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Maybe something like: [Tutorial: Opening a tab/pane in the same directory in Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory)?

**Comment by j0nimost** [comment]
Exactly, can we have this natively implemented?

**Comment by zadjii-msft** [comment]
I'm pretty confident that Windows PowerShell (v5) is not getting any more updates, but PowerShell Core is, so you might be able to ask them. Or even add it by default to [PsReadline](https://github.com/PowerShell/PSReadLine/issues), which handles many of the niceties of the PS prompt. We can't do anymore on our side; we need to let the shell tell us what the path is.
