### ISSUE TITLE
Feature Request: Azure cloud shell connector

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#1235]
# Summary of the new feature/enhancement

 Allow Windows Terminal users to connect to the Azure cloud shell, giving them access to their Azure resources and services through Windows Terminal itself. Azure users can then much more conveniently use the Azure technologies available to them without needing to use a browser to access them. 

# Proposed technical implementation details (optional)

 Authentication to Azure can be done through device code flow (at least, until Windows Terminal allows pop-up windows). Once authentication is complete, a terminal in a cloud shell instance could be requested (via HTTP) and a websocket connection can be established to the resulting URI. User commands to the cloud shell can then be sent over the websocket connection.

**Comment by isaac2004** [comment]
I assume that you are taking inspiration from this?

https://github.com/yangl900/azshell

I have been using this for a while and it has been working great

**Comment by PankajBhojwani** [comment]
Yes I am!
