### ISSUE TITLE
Localization gone since 1.13.10336.0

### ISSUE THREAD

**Issue by adrianghc** [microsoft/terminal#12351]
### Windows Terminal version

1.13.10336.0

### Windows build number

22000.469

### Steps to reproduce

Install Windows Terminal Preview 1.13.10336.0.

### Expected Behavior

Previously available localizations remain.

### Actual Behavior

The entire UI has lost its localization and switched to English. I can also see under Settings -> Appearance -> Language that English is the only option available apart from the "system default" option. My system locale is de-DE.

**Comment by DHowett** [comment]
Holy shit.

**Comment by DHowett** [comment]
This is bad.

**Comment by jfcherng** [comment]
Fwiw, I have the same issue with [Windows Terminal v1.12.10334.0](https://github.com/microsoft/terminal/releases/tag/v1.12.10334.0) downloaded from the github release page.

**Comment by fxzxmic** [comment]
Will this be fixed in 1.12?

**Comment by lhecker** [comment]
@fxzxmic Yes, we'll release a fix for this very soon. 🙂
