### ISSUE TITLE
As of latest preview version (1.13.10336.0), homedir alias (~) no longer recognized.

### ISSUE THREAD

**Issue by akulbe** [microsoft/terminal#12353]
### Windows Terminal version

1.13.10336.0

### Windows build number

22000.466

### Steps to reproduce

Open up Terminal Preview, drop down arrow to start a WSL distro session.

### Expected Behavior

Session would open normally.

### Actual Behavior

[error 2147942667 (0x8007010b) when launching `ubuntu.exe']
Could not access starting directory "~"

**Comment by DHowett** [comment]
This was never supported; the starting directory was simply _ignored_ for profiles like this.

Can you change the commandline from `ubuntu.exe` to `wsl -d Ubuntu` (or whatever the name of your Ubuntu distribution is?)

**Comment by akulbe** [comment]
![terminal_preview_bugreport](https://user-images.githubusercontent.com/123279/152424132-13cadff8-ee60-4deb-92b2-9ef847c6488f.png)

**Comment by akulbe** [comment]
> This was never supported; the starting directory was simply _ignored_ for profiles like this.
> 
> Can you change the commandline from `ubuntu.exe` to `wsl -d Ubuntu` (or whatever the name of your Ubuntu distribution is?)

I didn't specifically _set_ it to that, that I recall. I've only ever messed with those settings to set fonts, and to change the distro name.

**Comment by DHowett** [comment]
AUGH! I think I know what's up. That's not gonna be great.

We changed the base WSL profile, and Ubuntu customizes it to set a different EXE. We try to detect which EXE is being launched, because if it's WSL we want to tell it about the special `~` starting directory.

_Hmm._ This needs some thought...

> Go ahead and close this in favor of the bigger fish to fry. (I saw the localization bug. Thank you for your work on this, man! 🙏🏻)

Aw, thanks. :smile:

I'll keep this one open regardless.. it's gonna bite us, especially since this feature/misfeature is in stable.

**Comment by DHowett** [comment]
@zadjii-msft should we `BODGE` in our own check that the starting directory is a literal `~` and .... just clear it? These distro launchers are being fragment-customized on top of their WSL profiles ...

**Comment by zadjii-msft** [comment]
Okay so team discussion:

If the `startingDirectory` is `~`, and the commandline isn't wsl.exe, then drop the user in `%userprofile%`. Do this logic in `ConptyConnection`.
