### ISSUE TITLE
Scrolling in the settings does not work on Windows 10

### ISSUE THREAD

**Issue by Brawl345** [microsoft/terminal#12352]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Open settings of Windows Terminal (Preview)
2. Try scrolling with the mouse wheel or a laptop touchpad	

### Expected Behavior

It should scroll

### Actual Behavior

It does not scroll. I can only scroll when dragging the scrollbar manually. Scrolling in the terminal (powershell, cmd, etc.) does work though.

**Comment by zadjii-msft** [comment]
Are you by any chance using X Mouse Button Control? Case in point: #9340

**Comment by Brawl345** [comment]
Wow you are right, it IS X Mouse Button Control! I disabled the "scroll window under cursor" option (which Windows 10 already does by default) and it works now. I searched through the issues but didn't saw this one sorry! Thank you for your time and the quick response.

**Comment by zadjii-msft** [comment]
No worries, I just so happen to remember that one _distinctly_. I had a hard time finding it in the GH search myself 😅
