### ISSUE TITLE
Latest Version of Windows Terminal (now recognized as Terminal) is identified as Unknown Program in UAC Prompt.

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/terminal#12357]
When escalating Windows Terminal Version 1.12.10334.0 (Latest Stable) to Administrator the program name is Unknown Program but with a Windows Terminal logo. Still the app is still digitally signed. Some places like open with, Microsoft Store and start menu recognizes it as Terminal but Windows Search and the app itself still recognizes it as Windows Terminal. I Upgrade through winget on Windows 11 (NT10.22000.469 - 21H2).

**Comment by thedoggybrad** [comment]
![Uploading IMG_20220204_065434.jpg…]()
![Uploading IMG_20220204_065446.jpg…]()

**Comment by thedoggybrad** [comment]
![IMG_20220204_065434](https://user-images.githubusercontent.com/94173621/152443149-bc4be59a-e57d-4821-88f1-5d28f3e1c31d.jpg)
Proof

**Comment by thedoggybrad** [comment]
![IMG_20220204_065446](https://user-images.githubusercontent.com/94173621/152443197-db7c46cc-0343-4fda-b260-d894a8a0d0a3.jpg)
Version using right now that having that bug/issue

**Comment by zadjii-msft** [comment]
Is this when launching an auto-elevated profile, or just _always_?

**Comment by zadjii-msft** [comment]
Wait nevermind me, you're on 1.12 which doesn't have that. Crap.

**Comment by thedoggybrad** [comment]
Always when launching terminal using Admin rights.

**Comment by thedoggybrad** [comment]
Always when launching terminal using Admin rights.

**Comment by zadjii-msft** [comment]
Probably related: 
* #12351
* #12344

**Comment by thedoggybrad** [comment]
![IMG_20220204_065940](https://user-images.githubusercontent.com/94173621/152443600-f300f4a5-f691-4e76-8961-3dcde257a789.jpg)
![IMG_20220204_065926](https://user-images.githubusercontent.com/94173621/152443619-0ad46615-3163-4a71-90ff-3184c77e4390.jpg)
![IMG_20220204_065911](https://user-images.githubusercontent.com/94173621/152443637-df2614b4-207a-4a62-adb6-858b8568b2c6.jpg)
Different Names

**Comment by thedoggybrad** [comment]
Hope that you fixed it on the next update.

**Comment by ericbrownz** [comment]
same issue.
@zadjii-msft 
and is that a bug or feature when opening the terminal, the UI frame (tilte bar and frame lines) firstly appers then the content. Closing is opposite, content disappear firstly then the UI frame.

**Comment by rashil2000** [comment]
Facing the same issue here. Windows Terminal Preview 1.12 was recognized correctly in UAC, but 1.13 shows "Unknown Program" (I couldn't take a screen snip while UAC was popped up).

**Comment by DHowett** [comment]
So, this is due to a Windows bug! We had implemented a workaround for it, but that workaround was to not localize the name of the application.

The Windows bug is fixed in the insider program (and we will be pursuing getting the fix to older versions of Windows.)

On the whole, it is more important for our software to be _translated_ than for it to say the right name in the UAC consent display.

**Comment by thedoggybrad** [comment]
@DHowett @zadjii-msft The issue Unknown Program in Terminal in Windows 11 is still happening on a recent update 1.12.10393.0

**Comment by DHowett** [comment]
> @DHowett @zadjii-msft The issue Unknown Program in Terminal (UAC Prompt) in Windows 11 is still happening on a recent update 1.12.10393.0

https://github.com/microsoft/terminal/issues/12357#issuecomment-1030882535

**Comment by DHowett** [comment]
For linking purposes: this is tracked by

MSFT-37598784
MSFT-37675411
MSFT-37675413
MSFT-37675408
MSFT-37540496

**Comment by sba923** [comment]
> For linking purposes: this is tracked by
> 
> [MSFT-37598784](https://task.ms/37598784) [MSFT-37675411](https://task.ms/37675411) [MSFT-37675413](https://task.ms/37675413) [MSFT-37675408](https://task.ms/37675408) [MSFT-37540496](https://task.ms/37540496)

only accessible by Microsoft staff?

**Comment by sba923** [comment]
FWIW, this is also present on Windows Terminal Preview Version: 1.13.10395.0 running on Windows 10.0.19044.1586.amd64fre.vb_release.191206-1406

**Comment by zadjii-msft** [comment]
> only accessible by Microsoft staff?

Yea, those are internal bugs for my own reference. Looks like this is due to be serviced out to Windows 10, 19044 _soon_. Unfortunately, specific dates are harder to find.
