### ISSUE TITLE
Let us change the location of the settings.json file

### ISSUE THREAD

**Issue by NoniDOTio** [microsoft/terminal#12361]
# Description of the new feature/enhancement

It would be awesome to be able to change the location of the `settings.json` file. Individual users could put it on their OneDrive, small teams might throw the file onto an FTP server or Sharepoint. This would allow syncing look and feel, as well as profiles across multiple devices. 

# Proposed technical implementation details (optional)

Simple input that opens the file picker dialog if you click on it, but should also be able to accept URLs so you could specify a gist or whatever.

**Comment by 237dmitry** [comment]
Good idea. I am using environment variable for settings.json. Symbolic or hard link are variants too.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
