### ISSUE TITLE
No Linux\ubuntu tab present in new build

### ISSUE THREAD

**Issue by sahil315** [microsoft/terminal#1236]
![C__Windows_System32_WindowsPowerShell_v1 0_powershell exe 6_13_2019 2_11_28 AM](https://user-images.githubusercontent.com/40673232/59384889-e04d3f80-8d80-11e9-88d6-78b56e3d7c60.png)

**Comment by DHowett-MSFT** [comment]
Can you provide a bit more information?

* please run `wsl -l`

**Comment by aadarshashutosh** [comment]
You can add wsl to the drop-down by editing and adding the following lines in the setting (profiles.json) file, along other options...
{
"guid":"{09dc5eef-6840-4050-ae69-21e55e6a2e62}",
"name":"WSL",
"colorscheme":"Campbell",
"historySize":9001,
"snapOnInput":true,
"cursorColor":"#FFFFFF",
"cursorShape":"bar",
"commandline":"wsl.exe",
"fontFace":"Consolas",
"fontSize":12,
"acrylicOpacity":0.75,
"useAcrylic":true,
"closeOnExit":false,
"padding":"0, 0, 0, 0"
}

**Comment by DHowett-MSFT** [comment]
I'm guessing that WSL isn't installed or you have no distributions. If neither of these are true, please reopen the issue and provide the output of `wsl -l`

Thanks!
