### ISSUE TITLE
Fedora Remix cannot be open

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#12365]
### Windows Terminal version

1.12.10334.0

### Windows build number

Microsoft Windows [Version 10.0.22000.434]

### Other Software

Fedora Remix

### Steps to reproduce

Open Fedora Remix

### Expected Behavior

It should work
Example `Kali Linux`
```
rgyrbu@vrnnb-prc480:/windir/c/Users/rodgyrbu$
```

### Actual Behavior

```
[error 2147942667 (0x8007010b) when launching `%LOCALAPPDATA%\Microsoft\WindowsApps\fedoraremix.exe']
Could not access starting directory "~"
```

**Comment by lego963** [comment]
Changed to this and it worked
![image](https://user-images.githubusercontent.com/17201690/152492685-c780e540-3d16-481f-b48f-92463a6a9620.png)

**Comment by zadjii-msft** [comment]
Yea this looks like #12353. Clearly, we broke something here 🙃 

/dup #12353
