### ISSUE TITLE
Code Points with 0 width occupies one column

### ISSUE THREAD

**Issue by eiximenis** [microsoft/terminal#12373]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19043.1466

### Steps to reproduce

Running following NET6 code in Windows Terminal:

```cs
using System.Globalization;
using System.Text;

var s = "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67*";
var graphemes = StringInfo.GetTextElementEnumerator(s);
while (graphemes.MoveNext()) {
    Console.WriteLine("Grapheme:" + graphemes.Current);
    var runes = graphemes.Current.ToString().EnumerateRunes();
    foreach (var rune in runes) {
        Console.WriteLine($"\tRune [{rune}] is {rune.Value} (0x{rune.Value:x}) - {string.Join('\0', rune.ToString().Select(c => $"\\u{(int)c:x}"))}");
    }
}

Console.WriteLine("123456789|123456789|123456789|123456789|123456789|123456789|");
Console.WriteLine(s);
```

### Expected Behavior

This code creates a string named `s` with one grapheme cluster (👩‍👩‍👧‍👧 and one asterisk). Iterates over both graphemes, printing its code points individually. When the code point U+200d is printed it occupies one column even thought is a 0-width code point.
That has the consequence that the grapheme is 11 columns wide (4 * 2+3) instead of 8 columns wide (4 * 2).
Here is a screenshot of the program running in WT:
![image](https://user-images.githubusercontent.com/5191049/152582908-55c67aea-32ff-45c3-b4d5-f8b203e0e4c1.png)
As you can see, the * starts in column 12, and the individual U+200d printed have one column width.

Default Ubuntu terminal seems to handle this a little bit better: although the grapheme cluster is not shown as a single character but a sequence of its individual code points, the U+200d does not have any width, and the overall width of the grapheme is 8:
![image](https://user-images.githubusercontent.com/5191049/152583246-01ca442b-8f6b-4df5-b404-9b00f7620bd6.png)
As you can see, the * starts in column 9 and the U+200d does not have any width

### Actual Behavior

Zero width code points seems to occupy one column

**Comment by j4james** [comment]
I believe this is a known limitation of the current buffer implementation. I think it's probably covered by issue #1472, or more broadly #8000.

**Comment by zadjii-msft** [comment]
Yeah, I'd reckon those are the same thing. Thanks!

/dup #1472 
/dup #8000
