### ISSUE TITLE
Allow dragging files or folders into Terminal's Command Prompt window to display their path

### ISSUE THREAD

**Issue by TheWox** [microsoft/terminal#12377]
# Description of the new feature/enhancement

It would be great if one could drag files or folders into Terminal's command prompt window and have their path appear there. This is existing functionality in the old CMD prompt and its super useful. If any file/folder path has spaces, cmd automatically wraps it in quotation marks.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
You can definitely do this today! Is it not working for you?

![](https://drop.howett.net/share/explorer_QnKfrDJQ5a.gif)

**Comment by TheWox** [comment]
Strange, on my personal pc which I am now using, the drag and drop does work, however on my work pc, it is blocked. I get a little no-entry/blocked icon next to the file being dragged in. Apologies I just assumed that the functionality was missing at work earlier! Both Terminals are 1.11.3471.0 on my work and home Windows pcs.

Any case, you can probably close off this request!

**Comment by DHowett** [comment]
If I had to guess, you're using a high-DPI display? There's a really annoying issue where dragging only works over the top left corner of the window... but only on a high DPI display. The UI framework is sorta broken in this regard, and we don't know if we can fix it. :(

**Comment by TheWox** [comment]
Dragging into the top left worked, thank you! I use a 4k monitor on both my machines, but the work pc is on a version of Windows 10, while my home pc is the latest 11.

**Comment by fuweichin** [comment]
For me, drag and drop file is not-allowed anyway.

Windows Terminal 1.11.3471.0
Windows 10.0.19044

Note: I disabled UAC completely.

**Comment by zadjii-msft** [comment]
> Note: I disabled UAC completely.

Yep, that'll do it. Drag/drop doesn't work for elevated windows at all, even when UAC is entirely disabled.

**Comment by htcfreek** [comment]
> > Note: I disabled UAC completely.
> 
> Yep, that'll do it. Drag/drop doesn't work for elevated windows at all, even when UAC is entirely disabled. 

@zadjii-msft 
Does this mean even if I only logged-in as administrative user with uac disabled?
