### ISSUE TITLE
Terminal with PowerShell prompt crashes on input after maximizing and restoring window

### ISSUE THREAD

**Issue by nlebeck** [microsoft/terminal#1238]
This bug might be related to #175, #1095, or #1206. The specific conditions causing the bug here are different enough from the conditions described in those issues that I thought it might be worth filing a separate issue.

# Environment

```none
Windows build number: 10.0.18362.145
Windows Terminal version (if applicable): built from source at commit e20dfb8

Visual Studio Community 2019 (Version 16.1.3)

Dell Precision T5810
CPU: Xeon E5-1650 v3 @3.50GHz
RAM: 16GB
```

# Steps to reproduce

1. Launch CascadiaPackage (x64 configuration) from Visual Studio. A PowerShell prompt will appear.
2. Type `ls` into the prompt and hit enter.
3. Maximize the window.
4. Type `ls` and hit enter again.
5. Restore the window.
6. Type `ls` and hit enter a third time.

# Expected behavior

`ls` works correctly the third time.

# Actual behavior

The terminal crashes after entering `ls` the third time. I've seen two different types of error message. In one case, the terminal prints the following text in red and then exits right afterwards:

    out-lineoutput : The Win32 internal error "The parameter is incorrect" 0x57 occurred while writing to the console

In another case, Visual Studio displays a dialog box with the following text (identical to the dialog box from #1095):

    Debug Error!
    
    Program:
    ...l\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\conhost.exe
    
    abort() has been called
    
    (Press Retry to debug the application)

Furthermore, after encountering the second error case, the solution sometimes ends up in a state where I can no longer successfully launch CascadiaPackage. Every time I try to start it, I get the same dialog box with the same error message. This has happened to me twice now, and the only solution I've found is to delete the repo and re-clone it. (Even `git clean -dix` didn't get it working again.)

I first encountered this bug when running with multiple PowerShell tabs open, and in that case, only the active tab would crash (with the first type of error message).

**Comment by zadjii-msft** [comment]
I'd rather leave this open to make sure this scenario is fixed than prematurely resolving as a dupe. It feels different enough from the others, and has great repro steps.

I have _no idea_ why the second error case would totally break your Terminal install though...

**Comment by nlebeck** [comment]
FYI, it looks like this bug is fixed in the latest Windows Store build (version 0.3.2171.0).

**Comment by zadjii-msft** [comment]
@nlebeck thanks for confirming! I believe #2149 was the fix for this one.
