### ISSUE TITLE
Bracketed paste doesn't send wrapper escape codes

### ISSUE THREAD

**Issue by schungx** [microsoft/terminal#12385]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Steps to reproduce

1) Send `"\x1b[?2004h"` to Windows Terminal to turn on bracketed paste mode.

2) Copy sections of text with `\n`

3) Paste into terminal

4) Notice that the multi-line paste warning does **NOT** appear.  This confirms bracketed paste mode.

5) In app, read from `stdin`.

6) Confirm that `"\x1b[200~"` does not precede the pasted text.

### Expected Behavior

The pasted text should be wrapped with `"\x1b[200~"` and `"\x1b[201~"`

### Actual Behavior

No wrapping escape sequences.

**Comment by elsaco** [comment]
@schungx with `debugFeatures` enabled  the paste does look wrapped by `\x1b[200~` and `\x1b[201~`. Here's sample screenshot with the pasted text highlighted:

![wt_12385](https://user-images.githubusercontent.com/3933920/152654420-119938fc-0341-47e6-a22b-6f003c26ca5b.png)

```
test
test
test
```

was used for input.

**Comment by DHowett** [comment]
So, there's a bit of nuance here depending on what application is requesting bracketed paste mode.

For a Win32 application, you will only receive the bracketing sequences *if you have the console mode `ENABLE_VIRTUAL_TERMINAL_INPUT` set._ Without that mode, you are telling the console subsystem that you can't understand VT. . . so we don't send you any!

**Comment by schungx** [comment]
> For a Win32 application, you will only receive the bracketing sequences _if you have the console mode `ENABLE_VIRTUAL_TERMINAL_INPUT` set._

Ah.  Makes sense.  Let me figure out how to set that mode...

**Comment by schungx** [comment]
OK, turning on `ENABLE_VIRTUAL_TERMINAL_INPUT` makes it work.  Thanks a lot!

This probably should be in the docs!

**Comment by DHowett** [comment]
That's an excellent point. We haven't updated our documentation to encompass "enlightened terminals" since we started supporting them. I'll file this as a followup when I'm in the office!
