### ISSUE TITLE
Top right buttons can click even when opening About

### ISSUE THREAD

**Issue by akihironagai** [microsoft/terminal#12396]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.22000.469

### Steps to reproduce

1. Open About in down-arrow button
2. Click top right buttons

### Expected Behavior

Top right buttons can click even when opening About

### Actual Behavior

Top right buttons cannot click when opening About

![image](https://user-images.githubusercontent.com/77012577/152671031-f5edbf35-a281-407b-abf8-aac3e4f8c075.png)

**Comment by lhecker** [comment]
But... that's good isn't it? I don't want to sound stereotypical but that looks like a feature to me. 😅

**Comment by zadjii-msft** [comment]
Yea, I'm gonna agree. Even if this wasn't totally intentional, it's definitely better to have this work than not.

**Comment by akihironagai** [comment]
I forgot to report a bug related to this.

If I open Settings and then also About, and then click the Close button, part of the screen is shifted.

So I thought this behavior was a bug, not a feature.
