### ISSUE TITLE
Update changed tab colors so I can no longer figure out which one is active 🤬

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#12398]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.1466

### Steps to reproduce

use terminal

wake up the next day

running terminal instance is gone from taskbar

open it again

open multiple tabs

### Expected Behavior

able to figure out easily and quickly which tab is active

### Actual Behavior

I can't figure out which tab is active, the colors of active and other tabs are messed by design of this update 🤬

**Comment by mailinglists35** [comment]
>Features
Terminal now follows the Windows 11 UI guidelines (https://github.com/microsoft/terminal/pull/12241) (https://github.com/microsoft/terminal/pull/12144) (https://github.com/microsoft/terminal/pull/12208) (https://github.com/microsoft/terminal/pull/12287) (https://github.com/microsoft/terminal/pull/12326) (https://github.com/microsoft/terminal/pull/11720) (https://github.com/microsoft/terminal/pull/12321)
This will make it look a little out of place on Windows 10; we're sorry

excuse the language, but FUCK YOU who decided that and FUCK WINDOWS 11 with it's total fuckup of taskbar features 🤬

**Comment by fitojb** [comment]
And how is that related to the Windows TERMINAL team? Please keep your insults to yourself, especially when they are totally misdirected.

**Comment by mailinglists35** [comment]
you can follow stupid orders from stupid windows 11 management or quit your job.

**Comment by mailinglists35** [comment]
delivering a total fucked up release is not something make you proud

**Comment by DHowett** [comment]
@mailinglists35 this is your first and final warning. Cut it out.

**Comment by rgwood** [comment]
@zadjii-msft Thank you for fixing this in light mode! I think it also needs a fix in dark mode.

Dark mode before the WinUI change:

![image](https://user-images.githubusercontent.com/26268125/155657656-8a7e8569-9626-4e99-9849-0852be13ec36.png)

Dark mode now:

![image](https://user-images.githubusercontent.com/26268125/155657712-b0fa7428-efca-4dc0-a287-95eadc10c990.png)

I find it nearly impossible to tell which tab is active in most lighting conditions.
