### ISSUE TITLE
Update has closed running instance of Terminal 🤬

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#12397]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.1466

### Steps to reproduce

use Windows Terminal Preview

wake up the next day

Terminal preview is no longer in taskbar, all my tabs gone, work lost 🤬

### Expected Behavior

wait until I voluntarily restart or close the terminal

### Actual Behavior

Terminal preview is no longer in taskbar, all my tabs gone, work lost 🤬

**Comment by j4james** [comment]
As I understand it, it's the app store that shuts down the terminal whenever there is an update. For more info, and suggestions on how you can workaround this, see issue #3915 and #6726.

**Comment by mailinglists35** [comment]
>tovine opened this issue on Dec 11, 2019

so I guess I was just lucky to never occur on me until now.

i'm facepalming when I think since issue first reported you have never managed to take the issue to ms store team and make the store simply add an exception for the terminal

**Comment by zadjii-msft** [comment]
Yea, this is tracked elsewhere. 

/dup #3915
/dup #6726

**Comment by mailinglists35** [comment]
I wonder if unchecking "Terminate" permission to SYSTEM and LogonSessionID* users would prevent MS Store from killing Terminal. This would save us from altering MS Store behaviour or running Terminal from a manually downloaded file.

We'll see on the next update, I have unchecked it for both, using Process Hacker

![image](https://user-images.githubusercontent.com/2054302/152845083-51153901-047f-460e-8fe4-10e3ab0279be.png)
