### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by aadarshashutosh** [microsoft/terminal#1239]
In the windows terminal, when I open new tabs, i expect the other existing tabs to squeeze and adjust depending on available desktop space, but it doesn't seem to happen, neither am I able to scroll horizontally to switch to required tab.
![Screenshot (69)](https://user-images.githubusercontent.com/34771316/59392115-2233b100-8d94-11e9-95d0-75164c9d04d1.png)

In the above screenshot, the 4th tab is not visible, and neither am I able to scroll to it.
In tabbed apps like _Google Chrome_ I can switch to tabs using Ctrl + 'Num keys', but that combination doesn't seem to work here either.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! I think this is a copy of #597 ("Tab Sizing") and #444.
