### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aadarshashutosh** [microsoft/terminal#1240]
# Title for Tabs
There is no clear distinction between open tabs. So the user should be able to change the title of tabs from command syntax to name. (for ex. Title for a WSL tab without the feature is "_user@computer_name:~/path_to_active_directory_", the requested feature should enable us to use the title for tab simply as "WSL")
The feature should be customizable through profiles.json.

When we browse into a long folder name, the length of the tab keeps getting bigger and bigger since, as of today, the title of the tab is command syntax (PS), and there is now very less or even not that for the new tab and it's inconvenient to switch to that tab. If we are able to rename the title of the tab simply to the name of Shell it won't be affected by what folder are we in and it'll be easier to switch within tabs.
![Screenshot (69)](https://user-images.githubusercontent.com/34771316/59392884-e221fd80-8d96-11e9-991e-99138d6b0b5e.png)
As you can observe in the screenshot, the title of the tab takes too much space and therefore we are not able to accommodate the third tab in the title bar.

**Comment by DHowett-MSFT** [comment]
#608 
Thanks

**Comment by DHowett-MSFT** [comment]
Please search for existing issues before adding new ones.
Also, when you do file new issues, _please set the title to something reasonable_. Otherwise, we get a bunch of e-mails titled "Feature Request" that don't tell us what the request is.

**Comment by DHowett-MSFT** [comment]
I'd also like to thank you for taking the time to write out a great and robust description of your request. Sorry for the instant dismissal! I'd love to consolidate the discussion over in 608.
