### ISSUE TITLE
Windows Terminal latest stable release is v1.12.10334.0 but on the Windows Store it is v1.11.3471.0

### ISSUE THREAD

**Issue by jeansagi** [microsoft/terminal#12403]
### Windows Terminal version

v1.11.3471.0

### Windows build number

10.0.22000.469

### Other Software

N/A

### Steps to reproduce

Microsoft Store updates "Windows Termina Preview" but not "Windows Terminal"

### Expected Behavior

Microsoft Store updates should be in sync with the lates update. It is true for "Windows Terminal Preview" but not for "Windows Terminal"

### Actual Behavior

No update is available for Windows Terminal which in the Windows Store is a release behind the current github one.

**Comment by zadjii-msft** [comment]
This happens literally every release - the store doesn't necessarily roll out the updates uniformly. If you install the msix off our releases page, then it'll stay linked to the Store version and still auto-update in the future, if you manually want to hop to the next version without waiting for the Store

#12362, #11622 et. al.

**Comment by grawity** [comment]
> This happens literally every release - the store doesn't necessarily roll out the updates uniformly. If you install the msix off our releases page, then it'll stay linked to the Store version and still auto-update in the future, if you manually want to hop to the next version without waiting for the Store

Thanks, this was really unclear from the README – I've already been manually upgrading to the latest releases from msixbundle anyway, but still wished I could keep the auto-update in case I miss an announcement.

**Comment by kczx3** [comment]
> This happens literally every release - the store doesn't necessarily roll out the updates uniformly. If you install the msix off our releases page, then it'll stay linked to the Store version and still auto-update in the future, if you manually want to hop to the next version without waiting for the Store
> 
> #12362, #11622 et. al.

You may want to update the main README then.  It states this under the manual install of the .msixbundle:

> Note: If you install Terminal manually:
> 
> Terminal will not auto-update when new builds are released so you will need to regularly install the latest Terminal release to receive all the latest fixes and improvements!
