### ISSUE TITLE
Scroll to input on non-relevant input

### ISSUE THREAD

**Issue by tfiers** [microsoft/terminal#12405]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1466

### Steps to reproduce

- Run a command generating lots of output
- Scroll up
- Press a function key, like volume up or down.
  (Or in my case, scroll an extra mouse-wheel that is mapped to volume up/down).

### Expected Behavior

For nothing to happen to Terminal.

### Actual Behavior

Terminal scrolls to the input line.

Just a slightly annoying behaviour, where what you were reading jumps away if you change the music volume.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5366 for more discussion.

/dup #5366

**Comment by tfiers** [comment]
My bad! I searched the issues but hadn't found that one. Thanks
