### ISSUE TITLE
could "persistedWindowLayout" store the contents of those panes？

### ISSUE THREAD

**Issue by tcsecchen** [microsoft/terminal#12407]
# Description of the new feature/enhancement
I know now “firstWindowPreference - persistedWindowLayout” can save the tab layout of each window, including the layout and profile of each pane, but not any contents of those panes
Actuallay,the layout is useless for me,the contents is more impotant,is there a plan for this?

# Proposed technical implementation details (optional)
maybe it can like the .bash_history in linux

**Comment by Rosefield** [comment]
Yes, the issue is #961
