### ISSUE TITLE
Block selection within new CMD/Terminal has gone?

### ISSUE THREAD

**Issue by hasuino** [microsoft/terminal#12408]
Hi everybody,

for me the main important feature of the CMD tool was that I was able to copy/paste blocks instead of line based selections. In my case the example is: When using SQL*Plus (or any other tool with a special prompt) I encounter these kind of command input:

```
SQL> select * from my_table
  2  where column1 = 'value1'
  3  and column2 = 'value2'
  4  and column3 not in (3, 6, 9)
  5  order by value2, value1
  6  /
```

You see: When I try to copy this SQL block in a line selection I get in trouble because all following prompts are selected, too!

Block selection is the only acceptable way to handle that. Why is this gone in the new console? Please bring is back, please!

Regards,
Martin
![CMD_new](https://user-images.githubusercontent.com/14343848/152761785-5340bd20-a9a1-4e52-9e11-c06066c43d9c.png)

**Comment by hasuino** [comment]
Wow, now, only minutes later, I've found the new tag to toggle (in this case in German):
![CMD_new2](https://user-images.githubusercontent.com/14343848/152762351-651e891d-6893-425c-a6fb-8403b95df620.png)

I've to leave this tag open so terminal is able to select blocks as it should. Thanks :)

**Comment by hasuino** [comment]
I had been looking for something like "Enable block selection" in place of "Enable selection of line breaks" or similar, that's what confused me. Sorry for any inconvenience.

**Comment by zadjii-msft** [comment]
FWIW, you can immediately block select text in both conhost and the Terminal just by holding alt:

![image](https://user-images.githubusercontent.com/18356694/152811471-3ac03a4b-2f92-45f1-9996-665ecd5a898e.png)
