### ISSUE TITLE
Terminal can't be indexed by powertoys

### ISSUE THREAD

**Issue by DH-Illidan** [microsoft/terminal#12406]
### Windows Terminal version

1.12.10334.0

### Windows build number

10.0.19043.0

### Steps to reproduce

press `alt + space`.
enter `terminal`

### Expected Behavior

I can see *Terminal* in the list as early release.

### Actual Behavior

I can't see *Terminal* in the list.

**Comment by DHowett** [comment]
This is a /duplicate of https://github.com/microsoft/PowerToys/issues/16118

**Comment by DHowett** [comment]
(Thanks got the report!)
