### ISSUE TITLE
Add suport for Ctrl+A to select all text

### ISSUE THREAD

**Issue by Josh-65** [microsoft/terminal#12418]
# Description of the new feature/enhancement
Currently ctrl + A wont do anything but sometimes makes ^A rather than selecting all entered text

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22select+all%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1469 for more discussion.

/dup #1469
