### ISSUE TITLE
Cursor shape: underScore shows bar

### ISSUE THREAD

**Issue by rcopelan** [microsoft/terminal#1241]
# Environment
Microsoft Windows [Version 10.0.18362.113]
 
Windows Terminal version (if applicable): Unknown (is there a way to see this?). Cloned from repository on 10 June
Any other software? None that affects Terminal

# Steps to reproduce
- in profile.json  change the cursorShape property to "vintage". Save the file.  Result is the vintage thick underscore cursor immediately if the profile is active
-  change the cursorShape property to "underScore" and the vertical bar is shown.  
All other cursor shapes work as expected. 

# Expected behavior
A thin underscore cursor. 

# Actual behavior

The vertical bar cursor is used.

**Comment by DHowett-MSFT** [comment]
I think you need to use `underscore` (all lowercase); point taken, though, that settings should generally be case-insensitive.

**Comment by rcopelan** [comment]
That was it!  Thanks for the quick answer.  As emptyBox and filledBox were cap for the 2nd word I thought the underScore was right on the website where I found it.  Makes since since underscore is one word and the other 2 normally are 2 words.
