### ISSUE TITLE
Will Win7 be able to build or install later?

### ISSUE THREAD

**Issue by ShaocongRen** [microsoft/terminal#1242]
There is only window 7 working laptop rather than windows 10, and  may I ask will win7 be able to build or install later?

**Comment by ysc3839** [comment]
No. Because Windows Terminal uses XamlIsland, which is not available on Windows 7.

**Comment by zadjii-msft** [comment]
@ysc3839 is correct. We depend on a whole bunch of tech that's not making it back to Win7 anytime soon.

**Comment by ShaocongRen** [comment]
Thanks for getting back @ysc3839 and @zadjii-msft , got it. :)
