### ISSUE TITLE
Maximize icon should be rounded

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#12433]
### Windows Terminal version

1.13.10333.0

### Steps to reproduce

In our latest update to Preview, we added the snap assist functionality to the min/max/close control. Along with this and moving towards the Windows 11 styling, we should also make the maximize icon a rounded square.

### Expected Behavior

It should look something like this (taken from PowerPoint):
![image](https://user-images.githubusercontent.com/48369326/153053503-30c2fc38-570b-4853-a2e3-9736ead839ce.png)

### Actual Behavior

Currently it looks like this:
![image](https://user-images.githubusercontent.com/48369326/153053404-0d31e5ef-951a-460a-a180-ac3ead478d86.png)

**Comment by zamadatix** [comment]
Looks fixed in 1.13.10395.0

![image](https://user-images.githubusercontent.com/343550/153776265-479bfbb5-b6af-421c-98d1-3c8f2c5c3029.png)

(top is Windows Terminal, bottom is PowerPoint)

**Comment by zadjii-msft** [comment]
👀 

I'm pretty sure we didn't actually do anything to fix this yet:
![image](https://user-images.githubusercontent.com/18356694/153863849-d739a2c8-0b80-4d4e-9ef8-6b9019c1f4bd.png)
