### ISSUE TITLE
Starting directory only respected for first tab instance

### ISSUE THREAD

**Issue by pgerell** [microsoft/terminal#1243]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version: Built using https://github.com/microsoft/terminal/commit/d82eab44d076e441f0b630d9b53a19dfa884c3ab

# Steps to reproduce
Set the following profile as default profile:
```js
{
    "closeOnExit" : true,
    "colorScheme" : "Solarized Dark",
    "commandline" : "wsl.exe -d Ubuntu-18.04",
    "cursorColor" : "#FFFFFF",
    "cursorShape" : "underscore",
    "fontFace" : "Consolas",
    "fontSize" : 10,
    "guid" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
    "historySize" : 9001,
    "icon" : "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
    "name" : "Ubuntu-18.04",
    "padding" : "0, 0, 0, 0",
    "snapOnInput" : true,
    "startingDirectory" : "//wsl$/Ubuntu-18.04/home/xxx",
    "useAcrylic" : false
}
```

Start Windows terminal
Press "+" to open a second tab.

# Expected behavior

Both tabs should be started in /home/xxx

# Actual behavior

First tab is started in /home/xxx
Second tab is started in /mnt/c/Users/xxx

**Comment by pgerell** [comment]
When trying to attach to the process to debug this issue I noticed that I had many stray init and fish processes running. Probably left behind from crashing terminals.
After killing these processes, the unexpected behaviour is gone.

**Comment by zadjii-msft** [comment]
I can't get this to repro locally - @pgerell what's your default shell on your ubuntu instance?

**Comment by pgerell** [comment]
After killing those stray processes I cannot reproduce it either. I use fish as my default shell.
I've had many crashes lately but that is a different issue.

**Comment by DHowett-MSFT** [comment]
#970 should help with process orphaning. For the rest of it, though, it looks like it doesn't repro?
