### ISSUE TITLE
Terminal Start Menu Pin doesn't have a title

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1244]
When you pin the Windows Terminal app to the start menu, it doesn't have any title text, unlike most other apps.

Compare with VS, Sticky Notes, News, etc.
![image](https://user-images.githubusercontent.com/18356694/59448209-46aa8000-8dca-11e9-9292-577d42b0ab02.png)

**Comment by DHowett-MSFT** [comment]
It is, in fact, a bug.
