### ISSUE TITLE
render/display area shinked vertically

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#12455]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. copy a bunch of text from another where
2. paste into vim in Terminal
3. a paste prompt pop out, asking me really going to pasting these bunch texts, and bug happens now.

### Actual Behavior

about one quarter parts above there in the window "client area" disappeared, and that area becomes totally transparent , but mouse actions cannot go through, i.e. cannot click items back there.

the active area of terminal also shrinked, if I'm trying to `cls`, the prompt line will be in the top of the shrinked area, not disappeared instead.

the screenshot:
![scrnshot3](https://user-images.githubusercontent.com/1884240/153390457-1acafee3-1906-4242-b261-13bd4a0ea36e.png)
![scrnshot](https://user-images.githubusercontent.com/1884240/153388637-58459e58-d467-44bc-a3ef-d424f7d5900c.png)

what I've tried but no help:
* "restore window" and "maximize window"
* resizing Terminal window
* create split pane (e.g. Alt+Shift+'+'/'-') 
* create new tabs, all tabs suffering same situation.

**Comment by epiciskandar** [comment]
but I feel this is pretty cool BTW🤣, can we possible making this as a feature?

![scrnshot2](https://user-images.githubusercontent.com/1884240/153390084-7ed511d1-f3da-48dc-8d39-52787b41497c.png)

**Comment by zadjii-msft** [comment]
Ah jeez, another one. What the heck is up with these dialogs?

I'm gonna track this in #12447 since there's clearly something wrong with all these dialogs. 

/dup #12447
