### ISSUE TITLE
Setting title of a split-pane tab via cli only sets title when pane is active

### ISSUE THREAD

**Issue by joshuacookdev** [microsoft/terminal#12459]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.493

### Other Software

Using PowerShell Core (7.2.1) as default profile.

### Steps to reproduce

Run the following command in PS (any directory will work):
```
wt -w 0 nt --title Test -d C:/Users `; sp -d C:/Windows
```` 
(with or without the `; will work afaik)

### Expected Behavior

The tab to have the title "Test" regardless of which pane is focused in that tab, the same behavior as if I manually named the tab by double-clicking and typing the name.

I skimmed [the MS Docs page](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=powershell#tab-title) again to confirm that this *should* set the tab title. I also tried adding a split pane in a few places to the command example and am seeing the same behavior. If there's a different syntax for setting the Tab title (and the --title flag is meant to be pane title), then this should *maybe* be a documentation issue instead of a bug?

I'm not sure what "right" looks like for this (whether it's a behavior change or a syntax/documentation change), so I went with issue-bug rather than another option for the issue type. Feel free to rescope if needed, this isn't necessarily a show-stopper issue for me.

### Actual Behavior

When you focus on the left pane (`Users` directory), the tab has the "Test" title. When you focus on the right pane (`Windows` directory) the tab title changes to PowerShell.

Placement of the `--title` command doesn't seem to impact the behavior, unless I'm missing something in the command formatting.

**Comment by zadjii-msft** [comment]
I'm gonna move this to a docs bug over at /dup https://github.com/MicrosoftDocs/terminal/issues/499. Sorry for the confusion!

**Comment by joshuacookdev** [comment]
@zadjii-msft thanks for the clarification - part of me had thought the "per pane tab title" was intentional, but the docs weren't super clear on the matter.

Question: Is there currently an option to set the tab title via the cli (that behaves the same as manually setting the tab title)? If not, would it be possible to convert this issue-bug into a feature request (maybe saying `--tab-title` sets title for entire tab)? I'd be willing to attempt the work if it's something the team would be interested in having as a cli flag. I'm good with the behavior as-is, though - I'll just duplicate the --title flag in my shortcuts.
