### ISSUE TITLE
Rejuvenated UI doesn’t pick up Segoe UI Variable on Windows 11

### ISSUE THREAD

**Issue by fitojb** [microsoft/terminal#12452]
What it says on the tin.

**Comment by DHowett** [comment]
*Huh.* That's... unexpected. I wonder how we broke that! Thanks for the report.

**Comment by DHowett** [comment]
We might need to add another version of Windows into `maxversiontested` in our manifest to indicate compatibility.

```
    // After version 10.0.21251.0, Variable fonts will be used by default
```

**Comment by fitojb** [comment]
Yup, that’s it! Sloped letter ends for the win!
