### ISSUE TITLE
when using telnet in windows terminal, the mouse wheel can not work

### ISSUE THREAD

**Issue by baalchina** [microsoft/terminal#12456]
### Windows Terminal version

1.12.10334.0

### Windows build number

 10.0.22000.0

### Steps to reproduce

Hi, when I using telnet connect to a switch, in windows terminal , after the page scroll down, I can not using mouse wheel to scroll up, so many output I can not see because they disappear.
But when I using telnet in cmd.exe , the wheel can work.
So, it this a bug or a config issue? Thanks.

### Actual Behavior

Hi, when I using telnet connect to a switch, in windows terminal , after the page scroll down, I can not using mouse wheel to scroll up, so many output I can not see because they disappear.
But when I using telnet in cmd.exe , the wheel can work.
So, it this a bug or a config issue? Thanks.

**Comment by j4james** [comment]
This sounds like it might be the same thing as #6056.
