### ISSUE TITLE
Feature to ssh to a windows terminal profile

### ISSUE THREAD

**Issue by s-nil** [microsoft/terminal#12468]
# Description of the new feature/enhancement
A feature where I ssh to a system and the cli is a windows terminal profile.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Can you give us more details? Like, are you trying to create a Terminal profile with a commandline like `ssh foo@bar.com`? Or are you trying to remotely log in to a machine, and then once you're logged in, run a process that just so happens to be a Terminal profile that's set up on that machine?

**Comment by phil-blain** [comment]
Hi @s-nil, this is not something that can be configured on the Windows Terminal side, but rather on the OpenSSH side. Take a look at https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell. Basically, what you seem to want is to set OpenSSH's default shell to what you have in the `commandline` field of your default Terminal profile.

**Comment by zadjii-msft** [comment]
Yea, that's my understanding of how SSH works. This is something that can already be configured on the SSH side, albeit a bit manually. If you don't want to have to set up the commandline manually each time (and instead keep it in sync with the settings in the Terminal), I'd recommend filing a new feature request on OpenSSH to support that.
