### ISSUE TITLE
Provide capability to re-order tabs by dragging with cursor

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/terminal#12466]
# Description of the new feature/enhancement

Provide capability to re-order tabs by dragging with cursor instead of only through the available actions/commands.

# Proposed technical implementation details (optional)

N/A

**Comment by tomkerkhove** [comment]
Yes and I run as admin:


This is for v1.13.10336.0.

**Comment by zadjii-msft** [comment]
Out of curiosity, how did you disable UAC? I want to make sure to do the same thing you did for the sake of testing.

**Comment by tomkerkhove** [comment]
This is how I've disabled it, unless UAC means something else.

![image](https://user-images.githubusercontent.com/4345663/153592891-b057d5b0-0026-49b7-b1cc-fad0a209cf3a.png)

**Comment by Glitterinn** [comment]
Are you running WT as admin? You can drag&drop to re-order tabs only when you start WT not as an admin.

See similar issues:
https://github.com/microsoft/terminal/issues/11681

**Comment by tomkerkhove** [comment]
Even when I run it as non-admin I can't move them around but it's ok.

Closing as it's a duplicate.
