### ISSUE TITLE
After updating to V1.12 restore on restart is missing

### ISSUE THREAD

**Issue by richardcox13** [microsoft/terminal#12465]
### Windows Terminal version

1.12.10334.0

### Windows build number

10.0.19044.1466

### Steps to reproduce

Approach 1:
Open settings; startup: no UI for "When terminal starts... open windows from new session"

Approach 2:
Adding `"firstWindowPreference": "persistedWindowLayout"` to settings.json, exit terminal with multiple tabs open, start terminal: get default layout

### Expected Behavior

Have options in settings as described in the 1.12 blog and release notes.

And can restore on restart.

### Actual Behavior

Like V1.11: on restoration.

(This applies to both of the two systems I have updated.)

**Comment by zadjii-msft** [comment]
Ah, that's confusing for sure. The feature is still only enabled for Preview builds of the Terminal for now. See #12422 - we need to enable it always :)

/dup #12422

**Comment by richardcox13** [comment]
OK.

It would help if the released notes/blog entry made this clear it s still preview.
