### ISSUE TITLE
Cannot get trimPaste to work (I am running preview)

### ISSUE THREAD

**Issue by MrM40** [microsoft/terminal#12467]
### Windows Terminal version

1.12.10334.0

### Windows build number

19043.1348

### Steps to reproduce

I added the option to settings.json

![Clipboard01](https://user-images.githubusercontent.com/16258063/153586164-5d594895-650e-405a-ac3b-954bc34a0766.jpg)

If I try to paste a string like "Hello            " with or without trailing LF nothing is trimmed.

Also if I paste a multi-line string like
![multiliine](https://user-images.githubusercontent.com/16258063/153587024-cee56f48-54d2-4897-864b-859174a43680.jpg)
_From notepad++, UTF-8_

I get a warning about multi-line pasting and if I say OK all whitespaces and LF's are pasted too?

### Actual Behavior

That all whitespaces and/or CRs and/or LFs will be trimmed away before pasting into WT

**Comment by zadjii-msft** [comment]
`trimPaste` was only added in 1.13. https://github.com/microsoft/terminal/pull/11473#issuecomment-1029277464
