### ISSUE TITLE
Feature Request: Scroll from selection dragging out of window

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#1247]
# Summary of the new feature/enhancement

prereq: make sure you can scroll in the instance you're on
1. begin making a selection
2. As you move your mouse and expand the selection, move it towards a scrollable part of the buffer (so, up or down)

As of now, the selection "stops" at the end of the window.

The feature is that it should act like regular ConHost instances where it starts scrolling for you so that you can keep expanding the selection.

# Proposed technical implementation details (optional)

I'm hoping this isn't too difficult. We would have to detect when the mouse gets close/past the edge of the window. Then, when that actually occurs, communicate with the scrollBar and move it.

**Comment by Summon528** [comment]
Is this #1083?

**Comment by carlos-zamora** [comment]
> Is this #1083?

To my understanding, #1083 is more about the selection updating its y-position when the cursor goes off of the right/left side. This one is goes into effect when moving the cursor off of the top/bottom side.

E.g.: If the terminal can be scrolled up, begin making a selection and move the cursor over the top of the terminal. The terminal should start scrolling for you to continue making a selection.

**Comment by carlos-zamora** [comment]
> Is this #1083?

To my understanding, #1083 is more about the selection updating its y-position when the cursor goes off of the right/left side. This one is goes into effect when moving the cursor off of the top/bottom side.

E.g.: If the terminal can be scrolled up, begin making a selection and move the cursor over the top of the terminal. The terminal should start scrolling for you to continue making a selection.

**Comment by hmiglani-work** [comment]
For impact this also affects the PSReadline CaptureScreen function, which is really useful.
