### ISSUE TITLE
After Windows 11 Wake, Brief Window Pops Up

### ISSUE THREAD

**Issue by MikeMcCollister** [microsoft/terminal#12472]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.022000.0

### Steps to reproduce

This started happening 2+ months ago for me.

1. Bring the computer out of sleep and unlock the screen.
2. Watch the screen for up to 5 minutes.

Wait Unlock After logging in or unlocking after sleep, within 1-2 minutes a window will briefly show up. If I am working on something when that happens, my focus will 

### Expected Behavior

I expected a clean screen an no window pop ups.

### Actual Behavior

Within those first 5 minutes a window will briefly pop up. If I am working on something, then the focus sometimes goes away from what I am doing.

I had a PowerShell up and running ready to see the events that ran. As soon as I saw the window pop up, I hit enter. This way I can see what happend over the last second. It looks like Windows Terminal has something to do with this.

Here is the result of the last second of Get-WinEvent

-------------------------------------------------

PS C:\Users\Mike> date ; Get-WinEvent

Friday, February 11, 2022 2:04:36 PM

TimeCreated  : 2/11/2022 2:04:35 PM
ProviderName : Microsoft-Windows-AppModel-Runtime
Id           : 211
Message      : Added process 16368 to Desktop AppX container aca013a7-8915-11ec-9e11-a4c3f0e59146 for package
               Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe.

TimeCreated  : 2/11/2022 2:04:35 PM
ProviderName : Microsoft-Windows-Store
Id           : 8001
Message      : Skipping license manager: PFN Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe
               Function: InvokeLicenseManagerRequired
               Source: onecoreuap\enduser\winstore\licensemanager\apisethost\activationapis.cpp (373)

TimeCreated  : 2/11/2022 2:04:35 PM
ProviderName : Microsoft-Windows-AppModel-Runtime
Id           : 211
Message      : Added process 7356 to Desktop AppX container aca013a7-8915-11ec-9e11-a4c3f0e59146 for package
               Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe.

TimeCreated  : 2/11/2022 2:04:35 PM
ProviderName : Microsoft-Windows-Store
Id           : 8001
Message      : Skipping license manager: PFN Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe
               Function: InvokeLicenseManagerRequired
               Source: onecoreuap\enduser\winstore\licensemanager\apisethost\activationapis.cpp (373)

TimeCreated  : 2/11/2022 2:04:35 PM
ProviderName : Microsoft-Windows-WMI-Activity
Id           : 5857
Message      : CIMWin32 provider started with result code 0x0. HostProcess = wmiprvse.exe; ProcessID = 7968; ProviderPath =
               %systemroot%\system32\wbem\cimwin32.dll

**Comment by DHowett** [comment]
Do you have Terminal set as your default console host application? If so, Terminal will pop up in the same circumstances as an old console window would. This includes instances where login/unlock scheduled tasks would present a console window.

**Comment by MikeMcCollister** [comment]
This might have something to do with setting the default terminal application to Windows Terminal. If I set it to Windows Console Host then I don't get the pop up.

**Comment by MikeMcCollister** [comment]
> Do you have Terminal set as your default console host application? If so, Terminal will pop up in the same circumstances as an old console window would. This includes instances where login/unlock scheduled tasks would present a console window.

Yes, I do have the default terminal application set to Windows Terminal.

Is there a way to list all login/unlock scheduled tasks?

**Comment by DHowett** [comment]
There's a pretty solid write-up [over here on StackOverflow](https://superuser.com/questions/1052541/how-can-i-get-a-history-of-running-processes). All told, you'll need to enable process logging and then come back after the issue reproduces to see whose fault it is that a console window was spawned.

Alternatively, you can change the "close on exit" behavior in Terminal (Profiles > Defaults > Advanced > Termination Behavior) to "always close" so that the window goes away when the process exits.

Terminal defaults to "only if the process exited successfully" so that in case of a misconfiguration it doesn't just flicker open and closed. 🙂

**Comment by MikeMcCollister** [comment]
> There's a pretty solid write-up [over here on StackOverflow](https://superuser.com/questions/1052541/how-can-i-get-a-history-of-running-processes). All told, you'll need to enable process logging and then come back after the issue reproduces to see whose fault it is that a console window was spawned.
> 
> Alternatively, you can change the "close on exit" behavior in Terminal (Profiles > Defaults > Advanced > Termination Behavior) to "always close" so that the window goes away when the process exits.
> 
> Terminal defaults to "only if the process exited successfully" so that in case of a misconfiguration it doesn't just flicker open and closed. 🙂

Thanks for the link. Unfortunately, the computer that I am running Windows 11 on is the Home edition and gpedit.msc is not included. I know that this is a way to install gpedit but I am not comfortable doing that on that machine.

Knowing that this is not a Windows Terminal issue is good to know.

Thanks all for the help.

Mike

**Comment by DHowett** [comment]
Thanks for following up; sorry we couldn't be of better help!
