### ISSUE TITLE
Context menu not shown in 'This PC -> Devices and drives'

### ISSUE THREAD

**Issue by aybe** [microsoft/terminal#12478]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1526

### Steps to reproduce

1. open Explorer
2. in the navigation pane, right-click a disk, context menu entry is visible
3. in the main pane, ensure you're in This PC, right-click a disk, context menu entry is not visible

### Expected Behavior

The context menu entry for a drive should be visible no matter where you right-click that drive from.

### Actual Behavior

The context menu entry for a drive is not visible when it's right-clicked from This PC in Explorer main pane.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6654 for more discussion.

/dup #6654
