### ISSUE TITLE
Support for USB Serial COM Port

### ISSUE THREAD

**Issue by 7217043955** [microsoft/terminal#12470]
# Description of the new feature/enhancement
Hello everyone, I'm currently doing embedded device programing like U-Boot; OpenWrt; STM32, and as you may know, these devices use the UART port to output some debug info and/or implement command line interface, I'd like to use Windows Terminal as the terminal program to deal with these thing. I'm sure this will help me and many other embedded developers a lot.

# Proposed technical implementation details (optional)
The UART port from the device will be connected to the PC's USB port through a "USB to TTL converter", then it will show up in the Device Manager as a COM port device, what I want is, from here, I can create a new profile in the Windows Terminal, configure it to connect to the dedicated COM port, set Baud Rate; Data Bits; Stop Bits; Parity; Flow Control, then use the device's command line in the Windows Terminal.

**Comment by zamadatix** [comment]
I think Windows Terminal has all of the plumbing for this today in regards to the profile and display, what's missing is a built in program to open the serial device and pipe it to the terminal much like `ssh` which I'm not sure is part of what this repo covers or not.

I currently use `plink` from Putty for this myself, `screen` or `tmux` via cygwin  might be more full-featured but I haven't tried them. I'm in full support of a built in Windows utility to connect to serial devices out of the box though.

**Comment by zadjii-msft** [comment]
Yea, if you have a commandline client that can handle all the serial port interaction, then you can just add that as a profile in the Terminal settings. In general, we've got a longer thread about this over in #1280 so I'm gonna move this discussion there. Thanks!

/dup #1280

**Comment by blgram** [comment]
> I think Windows Terminal has all of the plumbing for this today in regards to the profile and display, what's missing is a built in Windows program to open the serial device and pipe it to the terminal much like `ssh` is built in now. I'm not sure if this kind of tool is part of what this repo covers or not though.
> 
> I currently use `plink` from Putty for this myself, `screen` or `tmux` via cygwin might be more full-featured but I haven't tried them. It would definitely be nice to have some more full featured built in tool that could handle escape codes and whatnot for arrow keys and such.

I'm Network Engineer, I prefer to keep my hands on keyboard as much as possible. That's why I tried using for different purposes, SSHing, nvim and plink for serial connections, but as you mentioned it just hurts me to that I can't use arrow keys. I kinda want to use Linux, instead of Windows.

**Comment by zamadatix** [comment]
@blgram take a look at SimplySerial. It's like plink but supports arrow keys in the newer versions. You can even make Terminal profiles for it directly if you want (the GitHub page has a guide).

**Comment by hatran3e** [comment]
You can use SimpleCom from winget package manager on window, they gave a readme file to instruct how to add it into window terminal profile also.
