### ISSUE TITLE
no longer loading at start up, despite being configured correctly in GUI

### ISSUE THREAD

**Issue by J-HS-L** [microsoft/terminal#12480]
### Steps to reproduce

reboot, doesn't load at startup

### Expected Behavior

load

### Actual Behavior

doesn't

**Comment by zadjii-msft** [comment]
You gotta give us more to work with. Terminal version numbers, or maybe your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)? The template isn't there to just ignore 😉

**Comment by J-HS-L** [comment]
![Screenshot 2022-02-13 201219](https://user-images.githubusercontent.com/49305869/153748484-d848f9ae-83e0-4474-ab11-b90b9749131d.png)
[state & settings.zip](https://github.com/microsoft/terminal/files/8055320/state.settings.zip)

**Comment by J-HS-L** [comment]
Didn't see anything else in the template -was late 
And nothing in the GUI to capture logs etc.
Here you go.....

**Comment by J-HS-L** [comment]
final..
![Screenshot 2022-02-13 202001](https://user-images.githubusercontent.com/49305869/153748729-ff6520bb-ff38-4686-94cf-7cb02769f1ff.png)
.

**Comment by J-HS-L** [comment]
Glad I checked, 

for some reason not getting damn push notifications for stuff I sub to on Github, 

thanks, will sub to that thread.
