### ISSUE TITLE
Add send-input as Command-Line Argument

### ISSUE THREAD

**Issue by joswr1ght** [microsoft/terminal#12487]
# Description of the new feature/enhancement

Without specifying a custom profile, it is not possible to send a startup command in the default pane when starting Windows terminal. While the Windows Terminal command-line argument `split-pane` accepts a `commandline` argument to run a command, the default pane cannot run a command unless it is specified in the profile. This limits the flexibility of starting Windows Terminal with specific configurations defined at the command line.

For example, I can use command line arguments to customize panes and change the focus pane:

```
wt -M split-pane -s 0.1 -H -p "Command Prompt" ping -t www.google.com ; move-focus up ; split-pane -s 0.85 -H -p "Windows PowerShell"
```

![Capture](https://user-images.githubusercontent.com/1318817/153871848-c1fb9f38-adef-41ea-babc-0e68b39e23ac.PNG)

The combination of `split-pane` and `move-focus` allows for tremendous flexibility in creating specific layouts for tasks. However, the default pane (top most in this screenshot) cannot accept a command line or any other input. The new panes through `split-pane` can accept input as a command-line argument, but the top-most pane cannot.

# Proposed technical implementation details (optional)

Adding `send-input` as a command-line argument allows the user to have great flexibility in how commands are sent to different panes. Using `move-focus`, the user can send input into any pane to run startup commands as needed to meet specific Windows Terminal startup requirements.

With `send-input` as a command-line argument, the default pane could accept commands and other input without changing the Windows Terminal profile settings:

```
wt -M split-pane -s 0.1 -H -p "Command Prompt" ping -t www.google.com ; move-focus up ; split-pane -s 0.85 -H -p "Windows PowerShell" ; move-focus up ; send-input ping www.microsoft.com
```

Submitted for your review, thank you!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9368 for more discussion.

/dup #9368

**Comment by joswr1ght** [comment]
Thank you @zadjii-msft !
