### ISSUE TITLE
Control+Space (aka C-@ aka NUL) is not being sent

### ISSUE THREAD

**Issue by eej71** [microsoft/terminal#12481]
**Windows Terminal Preview Version**: 1.13.10395.0

**Windows Version**: [Version 10.0.19043.1466]

**User Action**:
Connect to a bash prompt. Run od -c to see the exact characters that are received. 
Type in Control '@' (Control Shift 2 on a US keyboard)

**Expected Result**:
The `od -c` invocation should look like this.

```
od -c
^@^@^@^@^@^@
0000000  \0  \0  \0  \0  \0  \0  \n
```
That's the output that I receive when I do the test through putty.

**Actual Result**:
Nothing. The invocation of `od -c` is unaware that anything has been sent.

**Comments**:
I know this issue has some history so I can appreciate if its something that is not easily resolved.

**Comment by j4james** [comment]
Ctrl+Space works for me, but it seems that's not the case for everyone. I think this is probably covered by issue #11721.

**Comment by LaDyRAW** [comment]
Don't know how to enter in Windows terminal, where to go and when I tipe @ when i am tipping apt-get and other. I'm not sure what to do. Want to learn more about security and terminal services security but I need help from someone who understands all staff about it. Thank you for your time.

Get Outlook za Android<https://aka.ms/AAb9ysg>
________________________________
From: Eric Johnson ***@***.***>
Sent: Saturday, February 12, 2022 7:08:56 PM
To: microsoft/terminal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/terminal] Control+Space (aka C-@ aka NUL) is not being sent (Issue #12481)


Windows Terminal Preview Version: 1.13.10395.0

Windows Version: [Version 10.0.19043.1466]

User Action:
Connect to a bash prompt. Run od -c to see the exact characters that are received.
Type in Control '@' (Control Shift 2 on a US keyboard)

Expected Result:
The od -c invocation should look like this.

od -c
^@^@^@^@^@^@
0000000  \0  \0  \0  \0  \0  \0  \n


That's the output that I receive when I do the test through putty.

Actual Result:
Nothing. The invocation of od -c is unaware that anything has been sent.

Comments:
I know this issue has some history so I can appreciate if its something that is not easily resolved.

**Comment by eej71** [comment]
I wonder if there's a difference in the particular ssh binaries that we are running from within the Windows Terminal powershell environment that is getting in the way. My hand wavy thought process is - I wonder if the Windows Terminal is handling it, but hands it over to the ssh process which then properly drops it on the floor.

**Comment by zadjii-msft** [comment]
Yea, I'd suspect that this is a problem with your particular SSH client / server. We're definitely capable of sending NULs on Ctrl+Space, but NULs are hard and there's a lot of pieces in the system. We should continue the discussion in /dup #11721
