### ISSUE TITLE
Unnecessary 1px gap above tabs when maximized

### ISSUE THREAD

**Issue by kzshantonu** [microsoft/terminal#12485]
Makes it harder to switch tabs

<img width="185" alt="EX5x5Ry2Tq" src="https://user-images.githubusercontent.com/7745374/153803264-3b611721-3f48-4122-8f38-2387b33166b6.png">
<img width="185" alt="WindowsTerminal_xDMY92PRLK" src="https://user-images.githubusercontent.com/7745374/153803265-47f2c1af-622b-4c90-b5ed-782d95aedc73.png">

**Comment by zadjii-msft** [comment]
Can you follow up in #11309? Thanks!

/dup #11309
