### ISSUE TITLE
Can't use command "CD" in terminal

### ISSUE THREAD

**Issue by SoulGateKey** [microsoft/terminal#12482]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.493

### Steps to reproduce

use "cd" in terminal
but it cant open the folder in it.

### Actual Behavior

cant get in the folder

**Comment by zadjii-msft** [comment]
Yea we're gonna need to know which shell you're using. Is there any error message printed? Can you open that directory in File Explorer?
