### ISSUE TITLE
[error 2147958031 (0x80073d0f) when launching `%SystemRoot%\System32\cmd.exe']

### ISSUE THREAD

**Issue by Darkster1** [microsoft/terminal#12493]
### Windows Terminal version

1.13.10336.0

### Windows build number

22543.1000

### Steps to reproduce

Use the terminal for a few days, at lest leave it running for quite some time.
At some random point open a new tab/pane using control+shift+2 or alt+shift -.

This error appears:
[error 2147958031 (0x80073d0f) when launching `%SystemRoot%\System32\cmd.exe']
for cmd.
Or powershell:
[error 2147958031 (0x80073d0f) when launching `%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe']

At the moment of that error when you try control+shift+n for a new instance, the question raises "Do youy  want to close all tabs" NOO I DON"T click cancel and.... of cource, the thing goes down entirely anyways! :(

(and there I say goodby to all my running scrips again...)
Sadly, the windows event viewer shows NOTHING about it, it just looks like the terminal knows it needs a restart and opening a new instance will solve it but it takes the running instance with it.

### Expected Behavior

Opening a new tab/pane launches the associated program.

### Actual Behavior

No new tabs/panes can be opened.
A new instance *can* be opened but it takes down the running instance.
Scripts terminals apps whatever running in the bad instance work(ed) fine though, it's just impossible to open new panes.

I haven't seen this in any other earlier build.

**Comment by zadjii-msft** [comment]
`0x80073d0f` is `ERROR_NEEDS_REGISTRATION`. That's a super weird error code, so I'd bet that you just so happened to open a tab right in the split moment where the Store decided to complete the update to the latest version of the Terminal (whether you asked it to update or not).

That also explains the dialog warning for the "Do you want to close all tabs". There's no reason that would have opened in response to just trying to open a new tab. But it _does_ happen when the Store closes the terminal window (again, so it can install updates). 

This has been a persistent thorn in our side: /dup #6726. Sorry you got caught right in the middle of one 😕 If this repros frequently, then my guess is totally off base and we can reopen this. (do note though we did push another update as a hotfix last week, so you'll probably need another update before long)
