### ISSUE TITLE
[WT PRE] The icon of the taskbar under dual screen is incorrect

### ISSUE THREAD

**Issue by hunjipo** [microsoft/terminal#12494]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19042.1526

### Steps to reproduce

The information on my two screens is as follows.
![image](https://user-images.githubusercontent.com/52900961/154009137-c9dd8743-1e21-4709-9c24-360d2499a62f.png)
![image](https://user-images.githubusercontent.com/52900961/154009202-61cf4417-07f2-4092-9963-133d38d9ed43.png)
Then taskbar Icon.
screen 2:
![image](https://user-images.githubusercontent.com/52900961/154009930-67a58cec-6360-453a-828d-b45770932403.png)
screen 1:
![image](https://user-images.githubusercontent.com/52900961/154009975-e7d25acb-f13c-44cd-8859-192bd3c52817.png)

So the icon of screen 2 is wrong.

### Expected Behavior

The icon of screen 2 is the same as that of screen 1.

### Actual Behavior

The icon of screen 2 is wrong.

**Comment by zadjii-msft** [comment]
That seems like working as intended to me. There are different icon in the Terminal package for different sizes. On the 125% scaling monitor it's probably choosing a smaller icon, which doesn't have the "PRE" text.
