### ISSUE TITLE
Cannot select a wrapped line in a single step

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#12496]
On WT 1.11.3471.0 (Win 10 10.0.19044.1526) I still cannot select (for copy/paste, for example) with a double click of the mouse a line of text which is wrapped (line break) on the next line; it selects only the first part. One has to do this, at least, with two steps.

Don't add new features if you, first, do not fix this: having each tab with its own color or name or the terminal with transparencies and so on is of no usefulness it one cannot select a wrapped long line...

**Comment by zadjii-msft** [comment]
/dup #6178

You're welcome to submit a PR if you'd like to see it fixed sooner!
