### ISSUE TITLE
Update Windows to 18917 and problem wsl

### ISSUE THREAD

**Issue by sieja** [microsoft/terminal#1249]
![git](https://user-images.githubusercontent.com/9884618/59461186-16da9700-8e21-11e9-9c00-b71788de4c47.png)

**Comment by DHowett-MSFT** [comment]
This is not a console or terminal issue. Please file it at https://github.com/microsoft/wsl.

**Comment by zadjii-msft** [comment]
This is the repo for Terminal and Console issues - this belongs in [Microsoft/WSL](https://github.com/Microsoft/WSL).

As an off the cuff guess, I'm presuming this is because the update somehow uninstalled the WSL optional feature.
