### ISSUE TITLE
Frequent crash in Microsoft.Terminal.Control.dll Exception code: 0xc0000409

### ISSUE THREAD

**Issue by halr9000** [microsoft/terminal#12497]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Other Software

[Glassbrick](https://sierraasher.gumroad.com/l/glassbrick), a vision assistive a11y software

### Steps to reproduce

Three easily repeatable scenarios observed so far, same exact outcomes and fatal exception thrown. The easiest is as follows:

1. Open terminal (default powershell)
2. Paste anything multiple times until line length is exceeded, moving cursor to next line
3. Backspace until it crashes

Fault also seen by running longer running processes, suspicion that it writes to the host in a way that might trigger some cursor movement bug, harder to expalin.

### Expected Behavior

Not crash

### Actual Behavior

Crash with the following in event log:

```
Log Name:      Application
Source:        Application Error
Date:          2/15/2022 7:37:19 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      mando
Description:
Faulting application name: WindowsTerminal.exe, version: 1.11.2112.13011, time stamp: 0x61b80d0f
Faulting module name: Microsoft.Terminal.Control.dll, version: 1.11.2112.13011, time stamp: 0x61b80b7f
Exception code: 0xc0000409
Fault offset: 0x00000000000a92b9
Faulting process id: 0x37a8
Faulting application start time: 0x01d8226773f2ec80
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
Report Id: 714421e2-7079-4166-b5cc-67340637d943
Faulting package full name: Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-02-15T12:37:19.9783387Z" />
    <EventRecordID>16703</EventRecordID>
    <Correlation />
    <Execution ProcessID="21164" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>mando</Computer>
    <Security />
  </System>
  <EventData>
    <Data>WindowsTerminal.exe</Data>
    <Data>1.11.2112.13011</Data>
    <Data>61b80d0f</Data>
    <Data>Microsoft.Terminal.Control.dll</Data>
    <Data>1.11.2112.13011</Data>
    <Data>61b80b7f</Data>
    <Data>c0000409</Data>
    <Data>00000000000a92b9</Data>
    <Data>37a8</Data>
    <Data>01d8226773f2ec80</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll</Data>
    <Data>714421e2-7079-4166-b5cc-67340637d943</Data>
    <Data>Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>
```

**Comment by zadjii-msft** [comment]
Any chance you're running Magnifier or any other Accessibil

**Comment by halr9000** [comment]
@zadjii-msft why yes, yes I am! I did not think it was relevant. Running [Glassbrick ](https://sierraasher.gumroad.com/l/glassbrick) to aid in vision a11y. Want me to try to repro with it off? 


P.S. if you know anyone on the a11y team, please put in a good word for me and ask them to check how smoothly screen magnification is in macOS as compared to the equivalent native features in Windows Magnifier. It's one of those very simple things that seems alright when you use it once, but when you need to use it constantly, just works much better on my macbook.

**Comment by halr9000** [comment]
- Updated description at the top to add glassbrick.
- Tried to crash conemu with similar steps with glassbrick still enabled, no crashes.

**Comment by zadjii-msft** [comment]
Okay then this should definitely be https://github.com/microsoft/terminal/issues/8730. Can you download https://github.com/microsoft/terminal/releases/tag/v1.12.10393.0 and see if that's fixed the issue for you?

**Comment by halr9000** [comment]
@zadjii-msft you are, as they say, "the man". Ten points to your house, thank you, and good night. Do please let me know if you have a good accessibility or magnifier contact or project?
