### ISSUE TITLE
Console bash incorrectly shows characters as overwritten after using arrow keys

### ISSUE THREAD

**Issue by cgerdes1** [microsoft/terminal#125]
Windows version is 10.0.16299.248
Bash is using locale en_US.UTF-8

When i use the Arrow keys to go back on the command line, and start typing, what has previously been written will be overwritten IF I have passed over a space character using the right Arrow key (not expected). If I do not pass over a space character, the new entered characters are instead inserted as new characters and the rest of the existing line is moved forward (expected behaviour).

The buffer itself is not overwritten, so executin the modified command line will actually execute something else than what I see as the command line.

I have no idea why this occurs. Restarting bash does not help. I tested on Another machine, with the same version of Windows and Bash, but without having the same issues.

![2018-03-03 19_51_44-uranus__home](https://user-images.githubusercontent.com/27770842/36938055-5489b52e-1f1c-11e8-83d3-9885d1d0a755.png)

Example above:
I write the line "wordbeforespace wordafterspace" and hit enter
Using the up Arrow key I get the line back, I edit the lite using the left Arrow key, inserting the number 1 expecting the line "word1before1space word1after1space" however as the screenshot shows, the first Word instead is shown as "word1efore1pace". However, when I hit enter, the command being executed indeed is the expected "word1before1space".

This almost breaks the entire use of bash for me right now, since I very fast get unsure what command will actually be executed.

**Comment by cgerdes1** [comment]
After some additional investigation, I found one difference between the 2 boxes I have, were only one of them shows the above behaviour. The one that does not have this issue, was originally installed using lxrun and the bash command in powershell and later upgraded to Fall Creator, the other machine was installed using the "new" way of installing the app from the store after Fall Creators update.
I guess lxrun should not be used anymore, at least it says so, how can I force a Clean install without using lxrun /uninstall?

**Comment by cgerdes1** [comment]
After even more investigation I found what is causing this. After re-installing the app I no longer had the problem. It did not re-occur until I copied back my original .profile which changed the TERM env variable to be "xterm-color" in order to use the color prompt in .bashrc. This TERM emulation causes the odd behaviour originally described above. The original app after Clean install uses "xterm-256color" as the TERM emulation, which does not have this bug. My second machine uses TERM=xterm and does have this behaviour either.

**Comment by cyraid** [comment]
This is happening to me currently. SSHing into my web server, then trying to use nano and use the arrow keys (go ahead and hold left for a bit and it'll look like it's overwriting characters and such).

**Comment by austinv11** [comment]
I can replicate @cyraid's issue despite my TERM variable being set to `xterm-256color`

**Comment by j4james** [comment]
I was able to reproduce this by setting TERM to xterm-color, and can see in the debugger that it's trying to use Insert-Replace Mode (IRM) to insert the character, and that's something we don't yet support. So this is essentially a dup of #1947 (or vice versa).

**Comment by zsbolyoczki** [comment]
and #6652 also

**Comment by DHowett** [comment]
Oh hey! I never realized we had this duplicate... even though James totally called it out.

/dup #1947.
