### ISSUE TITLE
Auto save settings

### ISSUE THREAD

**Issue by Josh-65** [microsoft/terminal#12508]
# Description of the new feature/enhancement
Terminal settings are the only app i have found that wont auto save and apply settings as there changed. Is there a reason for this?

# Proposed technical implementation details (optional)
Remove the save/discard bar and auto save settings when there changed

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10627 for more discussion.

/dup #10627
