### ISSUE TITLE
WSL2 starting directory doesn't work on Windows 11 ARM64

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/terminal#12500]
### Windows Terminal version

1.11.3471.0

### Windows build number

22000.527

### Steps to reproduce

On Windows 11 ARM64 computer with Windows Terminal:

1. With a distribution of Linux installed in WSL2 (Ubuntu-20.04 for my case here)
2. Set starting directory in setting to something like //wsl$/Ubuntu-20.04/home/myusername. ---> Start a new Ubuntu tab will always start at root directory
3. Set starting directory in setting to something like \\wsl$\Ubuntu-20.04/home/myusername. ---> Start a new Ubuntu tab will receive an error message say parameters are incorrect.
PLEASE NOTE above configuration are done in Setting pane, the '\' is properly escaped in json.

### Expected Behavior

When starting directory is set, start a new linux tab would lead me to the directory I sat.

### Actual Behavior

Both settings does not work in this case. One throw an error, the other always start at root directory.

**Comment by zadjii-msft** [comment]
Thanks for the report! We actually noticed this a little while back in #12195. There seems to be a bug in WSL that caused this. It should be fixed now, bit I don't know if that's flowed up and out of the OS to Insiders quite yet. 

I don't actually know if there's a good workaround - @cinnamon-msft what have you been using for your WSL profiles in the meantime?

/dup #12195
