### ISSUE TITLE
Text user interface looks distorted when run from PowerShell or Cmd

### ISSUE THREAD

**Issue by thorstenkampe** [microsoft/terminal#12518]
### Windows Terminal version

 1.12.220208003-release1.12

### Windows build number

10.0.22000.0

### Other Software

Python 3.10.2
npyscreen 4.10.5

### Steps to reproduce

Run the following code to create a simple text user interface with Npyscreen from PowerShell or cmd:
```python
import sys
from npyscreen import *

class DbApp(NPSAppManaged):
    def onStart(self):
        self.registerForm('MAIN', DbParams())

class DbParams(ActionForm):
    def create(self):
        self.host   = self.add(TitleText, name='- Host:')
        self.port   = self.add(TitleText, name='- Port:')
        self.db     = self.add(TitleText, name='- Database:')
        self.user   = self.add(TitleText, name='- User:')
        self.passwd = self.add(TitlePassword, name='- Password:')

    def on_cancel(self):
        sys.exit()

DbApp().run()
```

### Expected Behavior

This is how it should look like - and actually does in Windows Terminal if I run the code from Cygwin bash (also looks fine in ConEmu or Conhost):
![image](https://user-images.githubusercontent.com/475462/154568875-eaeabb57-abab-4bde-b592-3f3159d083ac.png)

### Actual Behavior

This is how it looks like when run from Windows PowerShell or Cmd:
![image](https://user-images.githubusercontent.com/475462/154569045-31011365-e1f2-4f1e-acf9-e48358de0696.png)

**Comment by zadjii-msft** [comment]
This looks to me like a bug that should be filed upstream. I suspect whatever library you're using is detecting it's running on Windows and just not doing the right thing. It's probably not setting the right console flags.

However, https://github.com/npcole/npyscreen does look fairly abandoned...

**Comment by thorstenkampe** [comment]
The user interface looks perfectly fine on any Windows terminal (ConEmu, Cmd/Conhost). It's really just Windows Terminal that has this issue:
![image](https://user-images.githubusercontent.com/475462/154572503-7b618999-a2cd-452f-b1bd-1c762aa67367.png)

**Comment by elsaco** [comment]
This is with Windows Terminal Preview Version: 1.13.10395.0 and PowerShell 7.2.1:

![wt_12518_pwsh](https://user-images.githubusercontent.com/3933920/154613163-635ec31b-1646-457c-9649-7cc966e4e839.png)

PowerShell 5:

![wt_12518_powershell](https://user-images.githubusercontent.com/3933920/154613229-6429ba94-7112-4921-b662-40030fa68a25.png)

**Comment by thorstenkampe** [comment]
@elsaco is correct. I had started Windows Terminal from ConEmu (which is still my main terminal application and from which the demo works fine). Starting Windows Terminal from the desktop shows no issue with the text user interface (Npyscreen).

Sorry for the noise, I'm closing the issue.

**Comment by thorstenkampe** [comment]
@DHowett yes, `ConEmuHK.dll` was also my first thought. I disabled the option but no change.
