### ISSUE TITLE
Open a new tab in the same path but in a different terminal

### ISSUE THREAD

**Issue by 0xdw** [microsoft/terminal#12514]
# Description of the new feature/enhancement
When opening new tabs. It would be great if it can have an option where we can add the new tab in the same path but in a different terminal application.

**For example,**
Assume I have opened a folder in the CMD (with a large path) and I want to open that path in WSL. In that case, I would click the new tab and it opens a new window in a different path.

This can really help when we have to open a new tab in a different terminal where the current opened folder path is difficult to type quickly.

### Actual Behaviour when opening a new tab
![windows-terminal-actual-behaviour](https://user-images.githubusercontent.com/12568779/154538616-92284e6a-b29a-4427-9c25-e778f3b438d7.jpg)

### Expected Behaviour when opening a new tab
![windows-terminal-expected-behaviour](https://user-images.githubusercontent.com/12568779/154538723-ef9b8aed-4a12-499e-bfee-01e2b214a6cc.jpg)

# Proposed technical implementation details (optional)
When we duplicate a tab, is it possible to duplicate it to a different terminal application like below?

![Proposed option](https://user-images.githubusercontent.com/12568779/154539658-de1a1aba-7c72-46b5-a195-66740c38b9ce.jpg)

**Comment by 237dmitry** [comment]
This available from command line:
```
wt -w 0 nt --startingDirectory %cd% -p "<Profile name>"     # cmd
wt -w 0 nt --startingDirectory $pwd -p "<Profile name>"     # powershell
wt -w 0 nt --startingDirectory $(pwd) -p "<Profile name>"   # bash
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10232 for more discussion.

/dup #10232
