### ISSUE TITLE
With fragments extension, refer an icon/asset from another appx. (reference: ubuntu WSL icon)

### ISSUE THREAD

**Issue by didrocks** [microsoft/terminal#12511]
# Description of the new feature/enhancement
As part of customizing the Ubuntu autogenerated WSL profile via fragments, we want to be able to replace the default tux icon by our Ubuntu one.

However, we don’t really know where this assets will be placed on disk and when using ms-appx:/// schema, it logically refers to Windows Terminal itself and not the WSL appx.

We can’t really use \\wsl$\ either as it’s only available once the WSL VM is active.

Is there any hint on how this could be done with the current code or do you need to develop something for this?

# Proposed technical implementation details

We can imagine that if Windows Terminal knows from which appx a fragment is coming, then ms-appx:/// might refer to it.

# Other informations

A similar issue will occur with fonts: ideally, the font shipped from the WSL package (like our ubuntu fonts) would be easily referenced. However, we can’t make it a sharedFonts, as there are multiple ubuntu applications in the store for different versions, which would conflict system-wide.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10359 for more discussion.

/dup #10359

**Comment by didrocks** [comment]
@zadjii-msft Thanks, sorry for not finding the duplicate first. Should I open another bug for the font part?
