### ISSUE TITLE
[MSVC][std:c++latest] terminal failed to build with /std:c++latest on MSVC

### ISSUE THREAD

**Issue by xiaoxiao-Xu** [microsoft/terminal#12510]
### Windows build number

10.0.19041.0

### Steps to reproduce

The MSVC team recently added terminal as part of RWC testing. But we found some errors when building terminal with '/std:c++latest'.

**repro steps:**
1. `git clone https://github.com/microsoft/terminal.git F:\gitP\microsoft\terminal`
2. `cd F:\gitP\microsoft\terminal`
3. `set _CL_= /std:c++latest`
4. `set _CL_=/wd4189 %_CL_%`
5. `msbuild /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.20348.0 OpenConsole.sln /t:Restore /t:Rebuild`

### Expected Behavior

Terminal could build successfully with '/std:c++latest'.

### Actual Behavior

precomp.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt\wrl\module.h(1275,10): error C2220: the following warning is treated as an error
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt\wrl\module.h(1275,10): warning C5104: found 'L#serverName' in macro replacement list, did you mean 'L""#serverName'?
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt\wrl\module.h(1275,10): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
F:\gitP\microsoft\terminal\src\inc\til\bit.h(12,1): fatal error C1021: invalid preprocessor command 'warning'
[build.log](https://github.com/microsoft/terminal/files/8086582/build.log)

**Comment by xiaoxiao-Xu** [comment]
Note: It's lucky that the warning C5104 disappeared with Windows SDK 10.0.20348.0.

**Comment by zadjii-msft** [comment]
> The MSVC team recently added terminal as part of RWC testing

Thanks!

> `winrt\wrl\module.h(1275,10): warning C5104`

welp, we'll have to just suppress that one, since we don't own WRL


> `src\inc\til\bit.h(12,1): fatal error C1021`

okay yea that one's on us 😅
