### ISSUE TITLE
Build fails on non-432/1252 codepages 

### ISSUE THREAD

**Issue by chenjianxin** [microsoft/terminal#1251]
win10 1903 
vs2019 (but I have follow this : https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/)
result:
_GenerateProjectPriFileCore:
  C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\MakePri.exe New -ProjectRoot C:\Users\a5566\terminal\src\
  cascadia\TerminalConnection\ -ConfigXml x64\Debug\priconfig.xml -OutputFile C:\Users\a5566\terminal\x64\Debug\Termina
  lConnection\Microsoft.Terminal.TerminalConnection.pri -IndexName Microsoft.Terminal.TerminalConnection -Verbose -Over
  write
  TerminalConnection -> Microsoft.Terminal.TerminalConnection.pri
PostBuildEvent:

          echo OutDir=C:\Users\a5566\terminal\x64\Debug\TerminalConnection\
          (xcopy /Y "C:\Users\a5566\terminal\x64\Debug\TerminalConnection\TerminalConnection.dll" "C:\Users\a5566\termi
  nal\x64\Debug\TerminalConnection.dll*" )
          (xcopy /Y "C:\Users\a5566\terminal\x64\Debug\TerminalConnection\TerminalConnection.pdb" "C:\Users\a5566\termi
  nal\x64\Debug\TerminalConnection.pdb*" )

  :VCEnd
  OutDir=C:\Users\a5566\terminal\x64\Debug\TerminalConnection\
  C:\Users\a5566\terminal\x64\Debug\TerminalConnection\TerminalConnection.dll
  1 File(s) copied
  C:\Users\a5566\terminal\x64\Debug\TerminalConnection\TerminalConnection.pdb
  1 File(s) copied
FinalizeBuildStatus:
  Deleting file "x64\Debug\Terminal.CA5CAD1A.tlog\unsuccessfulbuild".
  Touching "x64\Debug\Terminal.CA5CAD1A.tlog\TerminalConnection.lastbuildstate".
Done Building Project "C:\Users\a5566\terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj" (default tar
gets).

Done Building Project "C:\Users\a5566\terminal\src\cascadia\TerminalControl\TerminalControl.vcxproj.metaproj" (default
targets) -- FAILED.

Done Building Project "C:\Users\a5566\terminal\OpenConsole.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\a5566\terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\a5566\terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"C:\Users\a5566\terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"C:\Users\a5566\terminal\src\interactivity\win32\lib\win32.LIB.vcxproj" (default target) (6) ->
"C:\Users\a5566\terminal\src\renderer\base\lib\base.vcxproj" (default target) (9) ->
(ClCompile target) ->
  C:\Users\a5566\terminal\src\renderer\base\thread.cpp(1): warning C4819: The file contains a character that cannot be
represented in the current code page (950). Save the file in Unicode format to prevent data loss [C:\Users\a5566\termin
al\src\renderer\base\lib\base.vcxproj]

"C:\Users\a5566\terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\a5566\terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"C:\Users\a5566\terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"C:\Users\a5566\terminal\src\interactivity\win32\lib\win32.LIB.vcxproj" (default target) (6) ->
"C:\Users\a5566\terminal\src\renderer\base\lib\base.vcxproj" (default target) (9) ->
(ClCompile target) ->
  C:\Users\a5566\terminal\src\renderer\base\thread.cpp(1): error C2220: warning treated as error - no 'object' file gen
erated [C:\Users\a5566\terminal\src\renderer\base\lib\base.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:04:07.43

**Comment by DHowett-MSFT** [comment]
We should drive the #458 discussion to a close. That'll fix this.

**Comment by DHowett-MSFT** [comment]
I think @miniksa fixed this in #1929.
