### ISSUE TITLE
Terminal should support restart/resume

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#1252]
# Summary

Terminal should be restartable:
* When closed, Terminal should persist it's visual state to a file
* When opened, if the Terminal state file exists and contains state data, the TErminal should restore its state from the state data, restoring its visual appearance, text content, etc. mirroring its visual state at the point that the Terminal was closed

> Notes: 
> * This does not mean that terminal tabs/panes should re-attach to the connections they were connected to when the Terminal was closed - this may be impossible in some cases - but the user should be able to see the content within each tab/pane, as it was when the Terminal was closed
> * It _may_ be possible to query the attached shell for environment data, inc. cwd before closing. In which case, Terminal should attempt to `cd` to the last recorded `cwd`, restore env-vars, and **resume** in some cases (e.g. when restoring connection to in-box shells.

When displaying restored content, the text should indicate that it is in read-only state, perhaps by dimming the text's luminance by some visible percentage.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is a combo of #766 and #961
