### ISSUE TITLE
Feature Request: Clear screen while running a process

### ISSUE THREAD

**Issue by jrobber** [microsoft/terminal#12527]
# Description of the new feature/enhancement

As a user I would like to be have a keyboard shortcut or action that will clear the terminal.

This is useful when I'm running a local development server and want to clear my terminal history without shutting down my local dev server.

# Proposed technical implementation details (optional)

Add an action called "Clear Terminal" that will clear the terminal history.
On Bash this is done via Cmd+k.
In VSCode you can type `terminal:clear` into the command palette.

**Comment by zadjii-msft** [comment]
This is something the Terminal already supports: [Clear buffer](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#clear-buffer). /dup #1882
