### ISSUE TITLE
Uppercase not rendering [Sometime]

### ISSUE THREAD

**Issue by ArmanFeyzi** [microsoft/terminal#12532]
### Windows Terminal version

1.12.10393.0

### Steps to reproduce

Sometimes, after updating the Terminal to a new version, I am unable to type Uppercase characters.

### Actual Behavior

Occasionally, after updating to the new version of Terminal, sometimes when I try to type an UPPERCASE letter, the terminal ignores it. This happens even when I paste text from the clipboard.
The terminal replaces uppercase characters with whitespace characters.
This can be fixed by restarting the terminal application. I have experienced it randomly on occasion.

**Comment by zadjii-msft** [comment]
Are you using PowerShell as your shell? We've had a few reports of this in the past:
* https://github.com/microsoft/terminal/issues/7087
* https://github.com/microsoft/terminal/issues/8450. 
* #9450

From that thread: https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this https://github.com/PowerShell/PowerShell/issues/10794 and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

@ArmanFeyzi Could you try that, and see if that resolves the issue?

**Comment by ArmanFeyzi** [comment]
Thanks' @zadjii-msft 
I updated PSReadLine and now the problem is resolved
