### ISSUE TITLE
trimBlockSelection default should be true

### ISSUE THREAD

**Issue by 89z** [microsoft/terminal#12536]
### Windows Terminal version

1.10.2383.0

### Windows build number

10.0.18363

### Steps to reproduce

Current Windows Terminal adds spaces with block select, while ConHost does not. I think Windows Terminal should match ConHost behavior.

### Actual Behavior

Trailing spaces added with block selection in Windows Terminal

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/pull/9807

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/9706

**Comment by zadjii-msft** [comment]
Team consensus: Yea, makes sense. Setting was only added less than a year ago, and probably should have been true then.
