### ISSUE TITLE
WT command open a different version terminal

### ISSUE THREAD

**Issue by 0resan** [microsoft/terminal#12534]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.19044.1469

### Steps to reproduce

![Screenshot 2022-02-19 233637](https://user-images.githubusercontent.com/30792262/154809107-a37e309b-6f51-44a1-814e-24c44852a128.png)
Click start menu open the terminal ,it will open 'Windows Terminal Version: 1.12.10393.0 '.
 But when i use run window input 'wt',it will open 'Terminal (Unpackaged)Version: 1.12.220208003-release1.12'. 
![Screenshot 2022-02-19 233748](https://user-images.githubusercontent.com/30792262/154809136-78682808-aeba-4d9d-a5bf-f1881c2877b0.png)

### Actual Behavior

I use thirdparty software everything to search settings.json,and I get two result:
![Screenshot 2022-02-20 000447](https://user-images.githubusercontent.com/30792262/154809196-93a156c2-7df8-4b06-ba20-bb07a2df7287.png)
So I have to copy one of them to another folder. It realy make me confuse.

**Comment by DHowett** [comment]
This could also be due to a permission issue on the `WindowsApps` directory. Can you follow the remediation steps in #9452?

**Comment by 0resan** [comment]
@zadjii-msft I just get them from Windows Store (Lastest version download from Github releases).  
Here is the `echo %path%` and `where wt` output .
![1](https://user-images.githubusercontent.com/30792262/155263703-e79e6d8b-92eb-4c03-8658-5f7f94fbf0b6.png)

**Comment by 0resan** [comment]
@DHowett Here ie the output .
![Screenshot 2022-02-23 125954](https://user-images.githubusercontent.com/30792262/155265132-2eedf2fb-0d88-4dd9-82b5-5ef7fbc52f85.png)

**Comment by zadjii-msft** [comment]
Well yep that'll do it. Something messed with the permissions on the WindowsApps folder, which it should ABSOLUTELY NEVER DO. The output should have looked something like:

```
\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                           NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(GR,GE)
                           NT AUTHORITY\SYSTEM:(F)
                           NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                           BUILTIN\Administrators:(CI)(RX)
                           NT AUTHORITY\LOCAL SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\NETWORK SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\RESTRICTED:(OI)(CI)(RX)
                           BUILTIN\Users:(Rc,S,RD,REA,X,RA)
```

but those extra permissions are what's breaking the alias here. Did you do something to change the permissions on `WindowsApps`?

**Comment by 0resan** [comment]
I am so regret did that . Maybe I should try to  re-install OS . :(
Anyway thank you for your support . I will never realizing what happened with my terminal without your help .

**Comment by DHowett** [comment]
@0resan you may be able to restore the permissions using `cacls` like this

Admin Command Prompt

```
takeown "C:\Program Files\WindowsApps"
cacls "C:\Program Files\WindowsApps" /S:"D:PAI(A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;OICIIO;GA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)(A;OICIIO;GXGR;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)(A;;FA;;;SY)(A;OICIIO;GA;;;SY)(A;CI;0x1200a9;;;BA)(A;OICI;0x1200a9;;;LS)(A;OICI;0x1200a9;;;NS)(A;OICI;0x1200a9;;;RC)(XA;;0x1200a9;;;BU;(Exists WIN://SYSAPPID))"
```

This will replace all of the ACLs on WindowsApps with the "default" ones that I just pulled from a working system.

I cannot guarantee that it solves your problem... but it might :)

**Comment by 0resan** [comment]
@DHowett  Yeah，it worked.  Thank you for this command ！
