### ISSUE TITLE
Terminal crashes on `wt .`

### ISSUE THREAD

**Issue by hello-smile6** [microsoft/terminal#12535]
### Windows Terminal version

1.12.10393.0

### Windows build number

19043.1469

### Other Software

- Command Prompt
- Windows Explorer
![screenshot](https://user-images.githubusercontent.com/73048226/154818813-a4be2ab0-e3ab-48c7-b7ed-1bf98a84acac.png)

### Steps to reproduce

1. Open Windows Terminal.
2. Open Command Prompt using a non-Windows Terminal context.
3. Execute `wt .` in Command Prompt.
    (May also happen with Git Bash)

### Expected Behavior

I was expecting to have Windows Terminal open in the current directory.

### Actual Behavior

Windows Terminal crashed and I lost about 30 minutes of work.

**Comment by hello-smile6** [comment]
Just got another error.
```
[error 2147942402 (0x80070002) when launching `%cd%']
```

**Comment by 237dmitry** [comment]
> I was expecting to have Windows Terminal open in the current directory.

```
wt --startingDirectory .
```

**Comment by DHowett** [comment]
Yes, the argument after `wt` is a command to run (as in, `wt powershell`.)

You need to use `wt -d xxx` to set the starting directory.

**Comment by hello-smile6** [comment]
> Yes, the argument after `wt` is a command to run (as in, `wt powershell`.)
> 
> You need to use `wt -d xxx` to set the starting directory.

If that is the case, then what about programs that use Windows Terminal without making sure the target binary exists?

**Comment by DHowett** [comment]
It should always display an error (as you noted in your second comment) in a new terminal tab/window/pane. If it crashes, that is a bug we should fix.

**Comment by AdrX003** [comment]
> Yes, the argument after `wt` is a command to run (as in, `wt powershell`.)
> 
> You need to use `wt -d xxx` to set the starting directory.

ive made it work by using %~dp0 , been trying different things for this for hours yesterday! 🥳
