### ISSUE TITLE
Escape Characters not Rendered

### ISSUE THREAD

**Issue by davidribyrne** [microsoft/terminal#12531]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.1526

### Steps to reproduce

Run  `echo -e "\x01\x1b[1;39m\x02test\x01\x1b[0m\x02"`

### Expected Behavior

It should display "test" with formatting.

### Actual Behavior

Windows Terminal displays placeholder boxes instead of \x01 and \x02. I'm not sure what those escape codes are for, but they display correctly in Cygwin's mintty terminal and default terminals on Mac & Linux.

![image](https://user-images.githubusercontent.com/532248/154765793-76ee02b7-078e-41f3-af68-2c2df10dae32.png)

**Comment by davidribyrne** [comment]
The escape codes are not common. I only stumbled across them recently with bluetoothctl.

**Comment by DHowett** [comment]
What do they display as in those applications?

DDG officially reports that they _have no visual representation_

> U+0001 <control>, decimal: 1, HTML: No visual representation, UTF-8: 0x01, block: Basic Latin
> U+0002 <control>, decimal: 2, HTML: No visual representation, UTF-8: 0x02, block: Basic Latin

As SOH (start of heading) and STX (start of text), they have no defined meaning to a terminal emulator.

Based on the way they're wrapping other control sequences, it looks like they are being used to suppress those sequences from being counted as visible text. If they're making it out to the screen, that suggests that some intermediate application is not properly stripping them out.

**Comment by davidribyrne** [comment]
I did more experimenting and you're correct, they do not affect the format. The other terminal emulator appears to just ignore them.

**Comment by j4james** [comment]
FYI, we've discussed these controls before in #10786.

**Comment by zadjii-msft** [comment]
Yea, this looks like /dup #10786 to me.
