### ISSUE TITLE
Difficult to exit fullscreen (impossible without keyboard input)

### ISSUE THREAD

**Issue by hello-smile6** [microsoft/terminal#12544]
### Windows Terminal version

1.12.10393.0

### Windows build number

19043.1469

### Steps to reproduce

1. Light your keyboard on fire. (Or, unplug it)
2. Open Windows Terminal and set it to open in fullscreen on startup.
3. Restart your computer.

### Expected Behavior

I was expecting to simply press Esc and exit fullscreen, like with websites. Or, at least, I thought there would be a tab bar which would show when I moved my mouse close to the top of the screen.

### Actual Behavior

I was locked in fullscreen and had to open Task Manager to exit.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5677 for more discussion.

/dup #5677
