### ISSUE TITLE
1.12 and 1.13 running unpackaged: Failed to load settings.

### ISSUE THREAD

**Issue by audetto** [microsoft/terminal#12547]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.18363.2037

### Steps to reproduce

Unzip msixbundle, extract x64 bin and double click `wt.exe`

### Expected Behavior

Should just run, ideally reusing previous settings.

### Actual Behavior

It works, but it repeats this error every single time it starts, and when saving settings.

![image](https://user-images.githubusercontent.com/212523/154970672-53aff24a-cc16-428b-9450-35a716c3d9dc.png)

**Comment by audetto** [comment]
1.13.10395.0 has the exact same issue.

**Comment by audetto** [comment]
Another difference is that 1.11.3471.0 is able to recognise my WSL Ubuntu 20.04 even if I delete the settings file.

**Comment by zadjii-msft** [comment]
Hmm. Interesting that this is happening to you unpackaged as well. We've actually already got a thread on this one - mind following up over in /dup #12305? Thanks!
