### ISSUE TITLE
Unable to set Command while running a cmd script

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#12541]
I want to open 1 of the windows with ssh login automatically, and hence I wrote a file abc.cmd with the following content, but it is giving errors:

`wt.exe -p Bash -d "c:/test/folder1"; -p Bash -c "ssh test@192.168.0.10"; -p Bash -d "C:/Projects/test"; focus-tab -t 0`

![image](https://user-images.githubusercontent.com/7592502/154863809-495ed993-9e2c-48d3-8965-afc46f3f6f63.png)

Also tried:
`wt.exe -p Bash -d "c:/test/folder1"; -p Bash /c "ssh test@192.168.0.10"; -p Bash -d "C:/Projects/test"; focus-tab -t 0`

but again got the similar error:
![image](https://user-images.githubusercontent.com/7592502/154863856-6577f059-86e7-440b-8926-c36d74bcc65c.png)

Is there any way I can set the commands as mentioned here:
![image](https://user-images.githubusercontent.com/7592502/154863942-f63dda5c-c552-4f5e-8837-4d37414262ef.png)

**Comment by jiveshwar** [comment]
I think the syntax is something else. This is not working
`wt.exe -p Bash -- -c ssh test@192.168.0.10`
AND
`wt.exe -p Bash -- ssh test@192.168.0.10`

both are giving errors like:
![image](https://user-images.githubusercontent.com/7592502/155170919-47143687-0ca2-4241-89f8-a62d3f34c57b.png)

**Comment by zadjii-msft** [comment]
That's exactly what I'd expect to happen there. You need to make sure to add the Bash profile's `commandline` to the start. What's the commandline of your Bash profile? Something like `c:\path\to\bash.exe --some -args`? Then your command would need to be 

```
new-tab -p Bash -- c:\path\to\bash.exe --some -args -c ssh test@192.168.0.10
```

**Comment by 237dmitry** [comment]
Why explicitly use the `--profile` parameter if the profile picks up the command anyway? For example I set `micro` in profiles, when I launch this editor from script  the terminal opens this editor according to its profile settings:
```powershell
param (
    [Parameter(Mandatory)]
    [string] $file
)

$Env:MICRO_TRUECOLOR = 1

$file = Get-Item $file
wt --window 0 new-tab --startingDirectory $file.Directory micro $file.Name
```

**Comment by zadjii-msft** [comment]
A Profile is a lot more than just a commandline, perhaps OP want's to make sure to use the colorscheme, font, etc. from their "Bash" profile rather than their default settings.
