### ISSUE TITLE
Open alias "wt" have unexpected behavior.

### ISSUE THREAD

**Issue by hungpham3112** [microsoft/terminal#12545]
### Windows Terminal version

1.12.220208003-release1.12

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Using `scoop` to add `windows-terminal` from `extras` bucket
2. install python use scoop install python
2. run `windows terminal` and "wt.exe" in 2 instances.
3. type python in `window terminal` and see result
3. type python in `wt.exe` and see result

### Expected Behavior

Path in `wt.exe` same like `windows terminal`. 

### Actual Behavior

[bandicam 2022-02-21 11-54-25-458.zip](https://github.com/microsoft/terminal/files/8106327/bandicam.2022-02-21.11-54-25-458.zip)

You can see in here, because it took 20 mb

**Comment by hello-smile6** [comment]
#12535 may be related (Crash due to directory being provided as first parameter)

**Comment by hungpham3112** [comment]
> #12535 may be related (Crash due to directory being provided as first parameter)

I don't know but `wt.exe` and `Window Terminal` seems use the difference `$env:path`

![image](https://user-images.githubusercontent.com/75968004/155080926-11596af3-701e-4f79-842c-e277f219a824.png)


On the left `wt.exe', on the right `Windows Terminal`. So magic

**Comment by zadjii-msft** [comment]
Hmm. So, the path is different when launched via the alias or via the actual start menu shortcut. Tha's quite unexpected. They both seem to have the same settings, so it's not like one launched the unpackaged version and the other launched the packaged version. 

I suppose I don't totally know how `scoop` sets up the app execution alias. Presumably, it doesn't actually set up an alias the same way as the Store install would. Hmm. There's another thread floating around here that's a bit similar. Lemme look that up.

**Comment by zadjii-msft** [comment]
#11777 was the thread I was thinking of. That doesn't mention installing from scoop though, so that might not be the only cause.

**Comment by hungpham3112** [comment]
#1125  was the thread I was thinking of. I can confirm to you that `wt.exe` used my old path in 2 month ago, it's not updated. I believe scoop quite clean and not related to this issue. Both `wt.exe`  and `Window Terminal` share same directory 

![image](https://user-images.githubusercontent.com/75968004/155242996-410b983d-6232-4998-a4a9-fe35a29dde0c.png)

This morning, I checked `wt.exe` and it worked. Is there any update?

**Comment by zadjii-msft** [comment]
I'm pretty sure #1125 only applies if you change the environment variables while the Terminal is running. From a cold launch (which it looks like this is), then it should always get a fresh set of variables. And I wouldn't expect different launch mechanisms to have different results. Kinda interesting that the `scoop/apps/windows-terminal/current` directory isn't on the path... 

What happens when you launch `wt` from the Run Dialog? Do you get the working path, or the broken one?

**Comment by hungpham3112** [comment]
> I'm pretty sure #1125 only applies if you change the environment variables while the Terminal is running. From a cold launch (which it looks like this is), then it should always get a fresh set of variables. And I wouldn't expect different launch mechanisms to have different results. Kinda interesting that the `scoop/apps/windows-terminal/current` directory isn't on the path...
> 
> What happens when you launch `wt` from the Run Dialog? Do you get the working path, or the broken one?

It said: 
![image](https://user-images.githubusercontent.com/75968004/155345574-fb4ed2cc-6e32-43ba-af5b-d96051a1112e.png)

**Comment by zadjii-msft** [comment]
This might have been fixed by #14999

**Comment by zadjii-msft** [comment]
Hey we pretty aggressively changed how env vars are loaded in 1.18. Could you check if this is fixed in Terminal Preview/?

**Comment by hungpham3112** [comment]
I will take a look and response as soon as I can.

**Comment by hungpham3112** [comment]
I tested, version 1.18 fixed PATH in `wt.exe`. Thanks for the hard work.
