### ISSUE TITLE
Able to scroll contents when reading manual pages

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#12540]
# Description of the new feature/enhancement
When I open xfce4-terminal on Linux or MobaXterm on windows, type "man ps" and use the mouse wheel to scroll up and down, magic happens, I am navigating down and up inside the manual page.

When I type "man ps" in WSL MS Terminal then use the mouse wheel, I am scrolled up to the contents of the screen that was before typing "man ps"

# Proposed technical implementation details (optional)
I have no idea what magic is behind the scenes in Linux and MobaXterm, so I don't know what to technically propose. Try and reproduce for yourself and you'll understand what I describe.
I don't even know if this belongs here or to microsoft WSL. or need fixing in both :)

**Comment by zadjii-msft** [comment]
Sure is!

/dup #3321
