### ISSUE TITLE
new instance behaviour - create a new window - looks strange

### ISSUE THREAD

**Issue by julie777** [microsoft/terminal#12542]
### Windows Terminal version

1.13

### Windows build number

10.0.19043.1526

### Steps to reproduce

BTW, I haven't managed to run wt.exe from the commandline. Either it can't be found or it can be executed.

I have 1.11 installed and have been using it. I have it set to open a new instance in a new window. Each new window has a normal appearance with a title bar, tabs, sidebar, etc.

I installed 1.13 current preview from today and when I ran it it didn't see the settings from 1.11 version. I copied the settings file because that it I I like it. Now I can only create a new instance in a new window. I can't access anything related to WT because my window looks like this

![image](https://user-images.githubusercontent.com/5090005/154868043-1cc9e378-5d1d-4959-8ed5-ca2405088fd8.png)
I can resize the window, but I can't even move it with the bar across the top.

When I look at the settings.json, I don't see any setting that looks like it controls each instance in a new window.

### Expected Behavior

I expected normal windows with tabs and settings just like 1.11

### Actual Behavior

I get this

![image](https://user-images.githubusercontent.com/5090005/154868092-f7c52634-8af8-4798-969c-2f509cd013cd.png)

**Comment by julie777** [comment]
I already found part of the problem. I had launch mode focus. I misinterpreted this as when the window opens make it the active window. (I have problems with apps starting and not being the active window.)

And I remembered the shortcut to open settings and that worked to allow me to undo it.

So a little bit of user error, but I see some issues that could be addressed.
- in focus mode there is no title bar with the x to close, and you can't reposition the window unless you use windows key shortcuts
- I don't see an keyboard shortcut to toggle focus mode. 
- the little strip at the top that looks like part of a title bar is puzzling. It doesn't appear that I can use it for anything.

**Comment by 237dmitry** [comment]
Look in settings.json, maybe there is `"launchMode": "focus",`. This mode hides titlebar. Remove this parameter or set other value:

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup

**Comment by zadjii-msft** [comment]
There are getting to be a lot of these, I should go update the FAQ. Leaving this open as a reminder to myself.

* #10094
* #11754
* #12542
* #12742

**Comment by zadjii-msft** [comment]
Added note to [FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#the-terminal-launched-without-any-tabs-or-a-close-button).
