### ISSUE TITLE
TerminalApp.Unit.Tests.manifest gets updated when building

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#12543]
### Windows Terminal version

Commit 09e99156727a92f84b309f18aee59ea7293b1264

### Windows build number

10.0.19041.1415

### Steps to reproduce

1. Checkout the latest source (commit 09e99156727a92f84b309f18aee59ea7293b1264 or later).
2. Build the solution.
3. Look for any modified files in git status.

### Expected Behavior

There shouldn't be any modified files.

### Actual Behavior

The [TerminalApp.Unit.Tests.manifest](https://github.com/microsoft/terminal/blob/main/src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest) file is being updated with the same changes that were made to the [WindowsTerminal.manifest](https://github.com/microsoft/terminal/blob/main/src/cascadia/WindowsTerminal/WindowsTerminal.manifest) file in PR #12462.

Shouldn't those changes have been committed at the same time as the WindowsTerminal manifest? Or if the unit test manifest is generated automatically, then maybe it shouldn't be committed at all.

Or am I the only one that's getting this?

**Comment by zadjii-msft** [comment]
What, no, I always build the unit tests.... 😅 

I think there's at least one open PR that's got a similar update in it snuck in, but if you'd like to submit a PR just for this tiny bit then that's fine. 

Frankly those tests should probably be reworked into the broader localtests or fixed so they don't need to do that anymore, but 🤷
