### ISSUE TITLE
Can wt auto change current path to the opening folder ?

### ISSUE THREAD

**Issue by zjxpcyc** [microsoft/terminal#12550]
# Description of the new feature/enhancement

Input wt to the win file explorer address bar . Then wt can auto change path to the folder .

# Proposed technical implementation details (optional)

For example, In windows, I open the file folder , and change to `e:\foo` .  Then I input `cmd` to the explorer address bar , the cmd window will be open , and the path is `e:\foo`.

Can wt support the same function ?

**Comment by zadjii-msft** [comment]
yep, it already does. However, you need to type 
```
wt -d .
``` 
to specifically tell the Terminal the working directory (`-d`) is the current directory of explorer (`.`)

For more details on `wt.exe`'s commandline args, see [Using command line arguments for Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows)
