### ISSUE TITLE
Appx file from project Azure develops is said to have IDP.ARES.Generic virus

### ISSUE THREAD

**Issue by asfernandes** [microsoft/terminal#1255]
I've downloaded the artifacts from the official azure devops (https://dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_apis/build/builds/19951/artifacts?artifactName=appx-Release&api-version=5.1-preview.5&%24format=zip) and installed it.

When I run the Windows Terminal Avast says it has the virus IDP.ARES.Generic virus.

Should I be worried? Are these downloads (articats from that repository) safe?

**Comment by asfernandes** [comment]
It also reports IDP.ALEXA.51...

**Comment by DHowett-MSFT** [comment]
Artifacts from this repository are safe. Please use a better antivirus solution that doesn't bark at shadows.
