### ISSUE TITLE
No update yet

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#12556]
After 20 days you have released WT 12, no update yet...

**Comment by zadjii-msft** [comment]
As we've discussed before (#10670), we're using a ring-based rollout system for the Terminal. We need to be more cautious with the stable build, given how many users it could potentially impact if something were to be wrong with it. For example, [our CI absolutely blew up all localization in the first 1.12 release](https://github.com/microsoft/terminal/issues/12351).



 If you install the msix off our releases page, then it'll stay linked to the Store version and still auto-update in the future, if you manually want to hop to the next version without waiting for the Store

#12403, #12362, #11622 et. al.

**Comment by vibonacci** [comment]
> If you install the msix off our releases page, then it'll stay linked to the Store version and still auto-update in the future, if you manually want to hop to the next version without waiting for the Store

I didn't know it would stay linked to the update system of the Store if you use the msix files. Thanks!
