### ISSUE TITLE
ctrl-alt-\ is ignored in WSL

### ISSUE THREAD

**Issue by jeffchase** [microsoft/terminal#12555]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1526

### Other Software

WSL Debian GNU/Linux 11 (bullseye)

Emacs 27.1

### Steps to reproduce

ncurses:
1) Install ncurses-examples: `sudo apt install ncurses-examples`
2) Run demo_altkeys: `/usr/lib/ncurses/examples/demo_altkeys`
3) Type `ctrl-alt-\`

emacs:
1) Run emacs
2) Type `C-h k` (describe-key)
3) Type `ctrl-alt-\`

### Expected Behavior

ncurses:
Something like: `0.259 Keycode ???, name ESC-^\`

emacs:
Open a new window pane that says: `C-M-\ runs the command indent-region`

### Actual Behavior

Nothing

**Comment by jeffchase** [comment]
I filed https://github.com/microsoft/WSL/issues/8069 with WSL and was told to file here.

**Comment by zadjii-msft** [comment]
Huh. Well, I thought this might be related to #3483, but maybe not. You might be able to work around this by binding `ctrl+alt+\` to a `sendInput` action for `\x1b\x1c` temporarily, while we work on a fix.
