### ISSUE TITLE
Make 65001 the default codepage

### ISSUE THREAD

**Issue by axelfontaine** [microsoft/terminal#12557]
# Description of the new feature/enhancement

While there is progress on various fronts towards correct emoji rendering, one currently still has to issue `chcp 65001` to ensure a program will print them out correctly on the terminal.

As UTF-8 is well on its way to cement its place as the default encoding in the industry, it would be great if the terminal could default to it as well, allowing more applications to render correctly out of the box.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1802 for more discussion.

/dup #1802
