### ISSUE TITLE
panes question

### ISSUE THREAD

**Issue by luobozz** [microsoft/terminal#12563]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.0

### Other Software

none

### Steps to reproduce

Split some panes

### Expected Behavior

![微信图片_20220224183231](https://user-images.githubusercontent.com/50447466/155507997-77f42246-6b30-4ed7-9647-15cdd1341a78.png)
![微信截图_20220224183523](https://user-images.githubusercontent.com/50447466/155508065-9224f5fe-7c3b-4ce4-bd53-b8d46046bda7.png)

### Actual Behavior

I split some panes
However, the color of the dividing line of my pane can not be adjusted, which is different from the official picture. Why?

**Comment by zadjii-msft** [comment]
The pane separator uses your Windows Accent color to indicate the focused pane. What is your accent color set to? 

That unfortunately can't be changed right now - we're tracking adding that in #3327 and #3061.

**Comment by luobozz** [comment]
@zadjii-msft thanks a lot.
I see what the problem is.
