### ISSUE TITLE
Create a profile with by default admin rights

### ISSUE THREAD

**Issue by Ayfri** [microsoft/terminal#12562]
# Description of the new feature/enhancement

Hi, I want to create a profile that only opens in admin rights, and if I don't have them right now it will ask for permission of course. I tried to do that in multiple ways, like opening a powershell prompt with admin rights in another wt tab but I didn't found anything working. I also tried to change the `commandLine` option in profile so that it uses `runas` cmd command to run as an admin user, but it also didn't work.

**Comment by zadjii-msft** [comment]
This is something that we've already implemented in the Preview builds of the Terminal: [Automatically run as Administrator](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-general#automatically-run-as-administrator-preview)

/dup #632

**Comment by Ayfri** [comment]
Ah okay thanks, waiting for release then :)

**Comment by DHowett** [comment]
You can install the preview version right now and use it as your main terminal! Lots of folks do it 😄 and it gives you early access to features.

We care about keeping it from crashing, so we try to make sure Preview is still very reliable.

**Comment by Ayfri** [comment]
Oh I didn't knew it, I might install it then ^^
