### ISSUE TITLE
The key shortcut does not work for the Korean version of Windows+X menu.

### ISSUE THREAD

**Issue by dh377** [microsoft/terminal#12572]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.0

### Other Software

Windows display language setting should be `Korean`, `ko` or `ko-KR`.

### Steps to reproduce

1. Pressing on **`[Windows Key]` + `X`**
2. Pressing on **`I`** (It does not respond)

### Expected Behavior

It launches "Windows Terminal".

### Actual Behavior

The translation should be `Windows 터미널(&I)` instead of `Windows 터미널` (Shortcut key "(`I`)" is missing). It is not only missing but also not usable. The terminal is not launched by pressing on the key `I` on the "Windows+X" menu.

**Comment by zadjii-msft** [comment]
Moved upstream to MSFT:38299837. #11793 was already fixed, but we'll make sure they get Korean fixed too.

**Comment by lychichem** [comment]
Chinese version of terminal also need this fix. And I think you need to fully check all the translation if they ignored shortcuts. This always happens if the translators are not familiar to how shortcut works.

**Comment by zadjii-msft** [comment]
Don't worry, the internal bug is tracking the Chinese string as well ☺️

**Comment by bzzrak** [comment]
Hi, the non-admin terminal in Serbian Cyrillic (sr-cyrl-RS) is underlined, but it doesn't work because Disk Management uses the same letter (the letter И, cyrillic for i). Also File Explorer uses the same letter, that one doesn't work either. I'd appreciate if you could get someone to take a look.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/77467869/166128226-4c6a70e0-81c3-4166-8225-450c64e3dd2d.png">

**Comment by lychichem** [comment]
The admin terminal in Simplified Chinese has a underline, but it will never work, as it marks "管". It should be "A"
![image](https://user-images.githubusercontent.com/9316590/166146868-0ed76de2-1225-4c02-8768-e89f4d434b62.png)
@zadjii-msft

**Comment by zadjii-msft** [comment]
Looking through the comments on various internal threads, 
* Korean seems to be fixed (MSFT:39393763 tracked the upstream bug that claimed it was fixed by the loc team)
* Chinese is tracked by MSFT:39146564
* Serbian Cyrillic is tracked in MSFT:39426135

**Comment by lychichem** [comment]
> Looking through the comments on various internal threads,
> 
> * Korean seems to be fixed ([MSFT:39393763](https://task.ms/39393763) tracked the upstream bug that claimed it was fixed by the loc team)
> * Chinese is tracked by [MSFT:39146564](https://task.ms/39146564) (Which, through a chain of bugs, lead me to [MSFT:39167826](https://task.ms/39167826). This claims that the string is already fixed in the latest build, but I'm not sure if that shipped yet.)
> * Serbian Cyrillic is tracked in [MSFT:39426135](https://task.ms/39426135)

Sadly, after waiting for 2 months, the issue I mentioned are still not fixed on windows 11 zh-CN 22622.290 with terminal 1.14.1862.0 and language pack 22621.1.1.0. @zadjii-msft

**Comment by zadjii-msft** [comment]
Coincidentally, the localization team reopened those bugs earlier last week. Apparently the loc files didn't get updated or something. Ultimately, we don't control those resources - we just have to wait until the loc team fixes them 😕

**Comment by zadjii-msft** [comment]
Apparently, this was only fixed in "Win11 build 25159". I have no idea when that'll be available for insiders, or what it's build number will look like in its final form.

**Comment by zadjii-msft** [comment]
For bookkeeping purposes, I'm gonna close this out, since there's nothing else for us to do here. If anyone sees this regress past 25159, then just ping me here and I'll repoen the internal bug with that info. Thanks!

**Comment by bzzrak** [comment]
I just want to confirm that the issue with Serbian was fixed in a recent update of the language pack (on build 22621). It took a while but thanks!

**Comment by lychichem** [comment]
> I just want to confirm that the issue with Serbian was fixed in a recent update of the language pack (on build 22621). It took a while but thanks!

+1, the issue was fixed for Simplified Chinese too.

**Comment by zadjii-msft** [comment]
Looks like MSFT:39428724 is still open for ko-kr, but that might be out of date.
