### ISSUE TITLE
prompt and inputs not aligned after restoring minimized window

### ISSUE THREAD

**Issue by heruji** [microsoft/terminal#12577]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.22000.527

### Steps to reproduce

1. Launch Windows Teminal Preview and maximize the window
2. Press <kbd>Enter</kbd> until the prompt reach the bottom of the window
3. Mimize the window and restore it
4. Input something (see screenshots below)

### Actual Behavior

![屏幕截图 2022-02-25 182459](https://user-images.githubusercontent.com/5276960/155700437-30bf8073-ccb6-415c-a311-bed3dfd7d4c1.png)

![屏幕截图 2022-02-25 191316](https://user-images.githubusercontent.com/5276960/155705806-6ad18b99-d35b-45c4-89df-7d62e860597d.png)

I used to experience the same issue on some version last year, when scale is set to 125%. But the issue was fixed after I upgraded to latest stable version. Now it happens again on 1.13 (I have scale set to 100% and I don't have this issue on 1.11).

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2432 for more discussion.

/dup #2432

This might be fixed by updating PsReadline to the latest beta version

**Comment by heruji** [comment]
After upgrading PSReadline to 2.2.2, the cursor is now properly aligned with the prompt.

But it still gave me an extra blank line after restoring the minimized window, which looks like #6495

So I tried different padding values. By setting it to 5, this issue is now completely fixed. Thanks!
