### ISSUE TITLE
Bold text on active tab causes the tab size to "jiggle" when focused/unfocused

### ISSUE THREAD

**Issue by Piroro-hs** [microsoft/terminal#12574]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.1526

### Steps to reproduce

1. Open 2 or more tabs in Terminal
2. Repeat `Ctrl` + `Tab`

### Expected Behavior

Things stay on same position

### Actual Behavior

PowerShell vibration

https://user-images.githubusercontent.com/22536104/155642108-3ea58d2b-a9cf-4fc2-8d8b-9172fdbedbbc.mp4

**Comment by zadjii-msft** [comment]
@gabbybilka as an FYI. 

I'll link this up to #12400. We'll probably need to track this upstream too. I'm not sure there's immediately any way for us to control the styling of the focused tab such that we can prevent it from getting bolded like that.

**Comment by zadjii-msft** [comment]
I'm gonna tag this up for discussion - honestly, we've been shipping with this for a year now, and there hasn't been an overwhelming amount of complaints. I didn't love it at first, but the bold text does add a little bit more emphasis to help ID the active tab. We may as well just leave this.

**Comment by zadjii-msft** [comment]
Yea our consensus was that if anything, this should be filed upstream over at https://github.com/microsoft/microsoft-ui-xaml.
