### ISSUE TITLE
INSTALL ERROR: winget install Microsoft.WindowsTerminal

### ISSUE THREAD

**Issue by ChristianRRL** [microsoft/terminal#12579]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.19042.1466

### Other Software

Command Prompt
winget install

### Steps to reproduce

1. Open Command Prompt
2. winget install Microsoft.WindowsTerminal
3. ERROR: Installer failed with exit code: 0x80070002 : The system cannot find the file specified.
4. Cry

![winget_install_WindowsTerminal](https://user-images.githubusercontent.com/6551085/155749235-b2c3a62f-5de2-413b-9eb9-068f78b4a567.PNG)

### Expected Behavior

The app should install normally

### Actual Behavior

The app does not install normally

**Comment by zadjii-msft** [comment]
This seems like a winget issue to me - this should be reported on their repo over at https://github.com/microsoft/winget-cli/issues

Actually looks like they've already got /dup https://github.com/microsoft/winget-cli/issues/1705
