### ISSUE TITLE
Not able to connect SSH in windows terminal

### ISSUE THREAD

**Issue by Rajeshsahoo12** [microsoft/terminal#12585]
Have installed windows terminal from microsoft market place. And tried using **ssh ubuntu@ip**.

But it gives me error mentioned below :-

**ubuntu@ip: Permission denied (publickey).**

But for same ip I am able to use SSH connection using termius application & WINSCP which uses putty converted .ppk file for authentication.

As I have generated ssh keys for my server ssh connection.

**Comment by zadjii-msft** [comment]
Is the path to `ssh.exe` the same in the Windows Terminal as it is when you run it in termius?

**Comment by Rajeshsahoo12** [comment]
Not sure about that. How to check path for both..? Termius & windows terminal..?

**Comment by zadjii-msft** [comment]
That kinda depends on the shell you're using:
* for Command Prompt (`cmd.exe`): `where ssh.exe`
* For PowerShell (`powershell.exe`, `pwsh.exe`): `Get-command ssh`

**Comment by Rajeshsahoo12** [comment]
On windows terminal I am using command prompt. And when I run **where ssh.exe**. Its gives below location path :-

**C:\Windows\System32\OpenSSH\ssh.exe**

**Comment by zadjii-msft** [comment]
Ah okay yea, Termius isn't a general-purpose terminal emulator, it's a dedicated SSH client. I'd reckon that they're probably shipping their own copy of SSH. 

I'd follow up with https://github.com/PowerShell/Win32-OpenSSH/issues, who owns ssh.exe.

**Comment by Rajeshsahoo12** [comment]
@zadjii-msft Thanks alot. I made it worked. With the help of below youtube tutorial.

**https://www.youtube.com/watch?v=ORks4JXxJp0**

Have made my ssh connection as default profile for new tab open & windows terminal open at first.




![image](https://user-images.githubusercontent.com/54216637/155803323-bcb7e3a0-d83b-4670-b30f-184a30c7da92.png)
