### ISSUE TITLE
Set default http proxy in settings.json

### ISSUE THREAD

**Issue by XHXIAIEIN** [microsoft/terminal#12595]
# Description of the new feature/enhancement

You know, it's hard for Chinese users to link because of the GWF. So every time I run `pip install xxx`, I have to set up a proxy first.

```
set http_proxy=http://127.0.0.1:port
set https_proxy=http://127.0.0.1:port
```

Can you allow the user to set the default proxy in settings.json. That way I don't have to enter it once every time.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2785 for more discussion.

/dup #2785

**Comment by mtgq** [comment]
When can I support it
