### ISSUE TITLE
F6 should move focus to another UI element

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#12596]
Similar to how users can press <kbd>Tab</kbd> to navigate the UI tree, <kbd>F6</kbd> is expected to work the same way.

We should use this as a way to explicitly move focus into the tab bar. I think generally F6 is used to move "up" the UI tree so that would make sense.

**Comment by carlos-zamora** [comment]
Similar to Tab, using the Shift modifier reverses the direction of navigation. So Shift+F6 goes "down"

**Comment by zadjii-msft** [comment]
What about the fact that commandline applications might want to use F6 themselves?

Even COOKED_READ uses it:
```c++
    case VK_F6:
    {
        _insertCtrlZ(cookedReadData);
        break;
    }
```

**Comment by carlos-zamora** [comment]
Closing. It's really important that we don't interfere with the underlying client app, and this behavior seems to be inconsistent across other tabbed applications.
