### ISSUE TITLE
Inconsistency between 'opacity' and 'transparency' in settings UI

### ISSUE THREAD

**Issue by dmezh** [microsoft/terminal#12592]
There's inconsistent help text for opacity/transparency:

https://github.com/microsoft/terminal/blob/788d33ce94d28e2903bc49f841ce279211b7f557/src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw#L530-L531

https://github.com/microsoft/terminal/blob/788d33ce94d28e2903bc49f841ce279211b7f557/src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw#L650-L651

The setting controls opacity, but the help text that appears when dragging the slider says transparency. Can we change these occurences of 'transparency' to 'opacity'? I can make a PR if needed 👍🏼

**Comment by lhecker** [comment]
I think in these two cases "opacity" would be a good choice.
