### ISSUE TITLE
Tab title not set for Ubuntu windows

### ISSUE THREAD

**Issue by jonathanbyrne** [microsoft/terminal#12591]
### Windows Terminal version

1.6.10571.0

### Windows build number

10.0.22000.527

### Other Software

Ubuntu 20.04.3 LTS

### Steps to reproduce

- Renamed Ubuntu profile from the default name to just "Ubuntu"
- Executed `wt new-tab --profile "Ubuntu" --title "My Title" --suppressApplicationTitle` from a command prompt

### Expected Behavior

I expected to see the tab title as "My Title"

### Actual Behavior

The tab title was "My Title" for a fraction of a second and then switched to "jonathanbyrne@DESKTOP-2N2UM3V: /mnt/c/Users/Jonathan Byrne"

**Comment by j4james** [comment]
This is something that's controlled by the bash `PS1` environment variable. The default value is setup in your `~/.bashrc` file. Regarding the title in particular, look for a line that is something like this:

    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"

That's what changes the title to show the current directory and user/host name.

Alternatively, there's is an option in the terminal's advanced profile section to [suppress title changes](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#suppress-title-changes). That will prevent all applications from altering the title.

**Comment by jonathanbyrne** [comment]
Thank you!  Suppressing the title change int he advanced profile section fixed it for me.

**Comment by ianjoneill** [comment]
The `--suppressApplicationTitle` command line argument was added in Terminal 1.8. If you upgrade your terminal version (the latest is 1.12) the command line argument should start working.

**Comment by jonathanbyrne** [comment]
That explains it.  Thank you!
