### ISSUE TITLE
Microsoft File Lister (list.exe) in the SDK crashes when run from cmd.exe

### ISSUE THREAD

**Issue by HarjitSi** [microsoft/terminal#12593]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.527

### Other Software

Windows SDK 10.0.22000.194 <- installed with VS2022 Community Edition

List.exe from above SDK. On my machine, it is located at: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\list.exe

![image](https://user-images.githubusercontent.com/45951076/155901622-3a46856c-1d61-4725-a440-ced26a3fde4b.png)

### Steps to reproduce

Install SDK.
win-r cmd

C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\list.exe <SOME_TEXT_FILE>

### Expected Behavior

The <SOME_TEXT_FILE> will open in the console application list.exe. 

This worked on Win 10 and Win 8. 

### Actual Behavior

cmd.exe window will close and disappear. A minute later, the processor fan goes to full speed and there is a powershell.exe running and consuming a CPU core.

**Comment by zadjii-msft** [comment]
This seems to be working fine for me on both the Terminal and conhost:


![image](https://user-images.githubusercontent.com/18356694/155977542-25f9a4fb-6ee3-44ca-9504-15eabfc590ed.png)
![image](https://user-images.githubusercontent.com/18356694/155977578-67fdd850-3412-4aa3-853e-3373be895df5.png)

If conhost is crashing, then we might be able to get a dump out of it: /feedback

FWIW I was using the list.exe that came with WinDbgX, since I couldn't seem to find the Debuggers directory in the SDK, nor the checkbox to install it in the VS installer. It _should_ be the same version..._

**Comment by malxau** [comment]
Sorry, I hadn't understood the powershell process pegging a core before.  Is there an entry for list.exe in ImageFileExecutionOptions? Running powershell in response to list, or in response to a crash, seems like it has to be a customization or policy of some sort - this isn't what a regular install would do.  Is there any more information about the powershell process, like the command line that invoked it?

(Also, I'm a bit confused by the version number, since that's not a Win11 build number.  I think what's happening is the most recently installed SDK overwrites the debugger files because the directory is not versioned correctly.  In this particular case that doesn't seem problematic though, because list doesn't depend on any non-OS DLLs.)

**Comment by HarjitSi** [comment]
Thanks for trying to repro.

Please do win-r and then cmd.exe and in the cmd.exe run list.exe and you must give it an existing file to open. This sequence worked on Windows 10 and 8.

It does not fall within Windows terminal.

On another Microsoftee list I had asked for help with this and they had suggested filling a bug report here because apparently this team owns conhost and Windows terminal.

Apparently, the version number for list.exe wasn't changed in the SDK I previously mentioned.



On Feb 28, 2022 12:09 PM, Malcolm Smith ***@***.***> wrote:

Sorry, I hadn't understood the powershell process pegging a core before. Is there an entry for list.exe in ImageFileExecutionOptions? Running powershell in response to list, or in response to a crash, seems like it has to be a customization or policy of some sort - this isn't what a regular install would do. Is there any more information about the powershell process, like the command line that invoked it?

(Also, I'm a bit confused by the version number, since that's not a Win11 build number. I think what's happening is the most recently installed SDK overwrites the debugger files because the directory is not versioned correctly. In this particular case that doesn't seem problematic though, because list doesn't depend on any non-OS DLLs.)

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fterminal%2Fissues%2F12593%23issuecomment-1054619191&data=04%7C01%7C%7Ca2477af4b1c84102f56108d9faf62e53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637816757532504442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u8eVYNWJqzDDSZ%2FTeCZ%2B9BFvF2AkptCz7kPa%2BoP4%2BqI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK6SQZAQW4H7CZ77MZ5WOJTU5PI6JANCNFSM5PPQBETQ&data=04%7C01%7C%7Ca2477af4b1c84102f56108d9faf62e53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637816757532504442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=F4CF%2B2ooFrWGBTxAFONM5S%2FfvCRnZGD3A4SynSi3%2BvA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca2477af4b1c84102f56108d9faf62e53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637816757532660650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hgCb2QqyzBrfdTUY5bw8rQ9mfETuXOrjKJqYRtKdx6k%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca2477af4b1c84102f56108d9faf62e53%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637816757532660650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2wJt7XLXA7URTAMo455GOlPCGffJnUwFxjT9guVPl40%3D&reserved=0>.

**Comment by zadjii-msft** [comment]
Like I showed [in the screenshots above](https://github.com/microsoft/terminal/issues/12593#issuecomment-1054173355), this doesn't repro for me. Please try capturing the scenario with the Feedback Hub, so it can try and capture the stack of the crash.

**Comment by malxau** [comment]
> On another Microsoftee list I had asked for help with this and they had suggested filling a bug report here because apparently this team owns conhost and Windows terminal. Apparently, the version number for list.exe wasn't changed in the SDK I previously mentioned.

I'm the one who suggested that.  In my install of the Windows 11 SDK the version of list is 10.0.22000.194, which is the Windows 11 build number.  It would be very unexpected if the Windows 11 SDK bundled the Server 2019 version of these tools.

**Comment by HarjitSi** [comment]
I submitted a problem report using Feedback hub. Just in case, here are some screen shots.

![image](https://user-images.githubusercontent.com/45951076/156896075-edf78708-8284-490c-931a-70be8e31d4d5.png)

![image](https://user-images.githubusercontent.com/45951076/156896166-2a31643b-838c-4b6c-80a5-a83c808ea912.png)

![image](https://user-images.githubusercontent.com/45951076/156896126-c4d8a22f-0401-49ac-8a41-7e94c57481af.png)

Thanks for working this.

**Comment by HarjitSi** [comment]
Not sure why Feedback hub is not working. 

So, I did Win-r cmd

In Resource manager, I saw a cmd.exe and a conhost.exe. 

I then ran WinDbg and did attach to a process (F6) and used the conhost.exe PID.

I noticed that the cmd.exe was frozen since the attach broke into the process. I went ahead and did a 'g' in WinDbg.

Then in the cmd window ran the command: list c:\bat\dirlist.txt

and it broke into WinDbg. The WinDbg session is in file: ListCrash.txt
[ListCrash.TXT](https://github.com/microsoft/terminal/files/8241189/ListCrash.TXT)

I then did a ".dump /mfh /u" and have the crash dump. Not sure if I should upload it here. It is 38MB in size.

As previously mentioned that after some time, I see an entry in Resource Manager that takes a full core. So, I connected WinDbg to that and the session is also attached: ListExe.txt
[ListExe.txt](https://github.com/microsoft/terminal/files/8241198/ListExe.txt)

I have the crash dump for this also and it is 11MB in size. Again not sure if I should upload it here.

If it helps, I can try different debug commands or we can do a call and do a debug session or?

**Comment by malxau** [comment]
For the conhost crash, can you get the stack trace on the thread that crashed? In the output here it looks like thread 0 crashed but the stack is from thread 3, which doesn't show the interesting state.

Also, does this have the "legacy console" option selected? I'm a bit surprised to see conhostv1.dll in the loaded modules.

**Comment by HarjitSi** [comment]
Please find attached the thread 0 stack before I did the shenanigans below.
[ListThread0Stack.TXT](https://github.com/microsoft/terminal/files/8241560/ListThread0Stack.TXT)

I checked properties and "Use legacy" is checked. This is my baseline configuration. To be honest, I do not know why "Use legacy" is checked.

I re-ran cmd.exe and **cleared** the "Use legacy" checkbox. Exited cmd.exe. Reran cmd.exe and this time it opened in a Windows Terminal tab and not the standalone window type I showed in an earlier message.

I used Windows terminal's settings to change the Default terminal application to Windows Console Host. Ran cmd.exe and it opened in the window type shown in an earlier message and list.exe worked fine. I checked the state of "Use legacy" and it was **cleared**.

I then checked "Use legacy" and exited and reran cmd.exe and now list.exe crashes.

**Summary** List.exe fails with cmd.exe with Use Legacy checked. Good sleuthing - @malxau!

![image](https://user-images.githubusercontent.com/45951076/158102072-5eaf07a0-4c2d-4fab-bb8b-f654e642d4cc.png)

**Comment by malxau** [comment]
Okay, this is why nobody else could repro it, even though it's very serious.  Using the legacy console makes the crash happen immediately.

From poking around, Peb->OemCodePageData is NULL which means ConhostV1!GlyphCP is never initialized.  This is used by OEMCP (the default) when converting to Unicode. List crashes just by calling `WriteConsoleOutputCharacterA` - not even with extended characters, just characters that require ASCII-to-Unicode conversion.  Messing around with this shows it crashes in many other ways too.

**Comment by HarjitSi** [comment]
Great! Please let me know if there is anything else I can do to help.

I reread the thread and I now better understand the confusion around version numbers mentioned earlier.

You are right that the VS 2022 installer no longer asks about installing the debuggers when installing the SDK. I think this is a bug and the VS installer team needs to know...

I'm reasonably sure that the debuggers were installed previously. And I mistakenly assumed that the Win 11 SDK install had updated them.

**Comment by zadjii-msft** [comment]
I'm tagging this one up for discussion - since this only repros with Conhostv1, and likely _always_ did, I'm tempted to close this out, since that's not actively maintained.

**Comment by DHowett** [comment]
This is actually MSFT-26378124, which I've had a fix stashed for for a while. Target got rid of their implementation of process-local OEM codepages. :smile:

**Comment by DHowett** [comment]
@zadjii-msft: Discussion outcome: we have a fix in hand for conhostv1, so we might as well fix it.

**Comment by carlos-zamora** [comment]
The fix for this went out in version 22621. Closing as fixed!
