### ISSUE TITLE
Pasting Tab character leads to Tab Completion

### ISSUE THREAD

**Issue by st0le** [microsoft/terminal#12600]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Copy the command below. The command is `echo<space><tab><space>test`. 

`echo 	 test`
(I now realize github strips the tab character, but you can write this in your text editor and copy it to your clipboard)

If you are adventurous,

`rm 	 thisfiledoesntexist` (this will delete the first file in your directory!!)

### Expected Behavior

It should paste

`echo 	 test` verbatim.

### Actual Behavior

`echo <first-file-in-current-directory> test`

The Tab completion is invoked which replaces the tab with the first entry in tab completion.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8993 for more discussion.

/dup #8993

**Comment by j4james** [comment]
@zadjii-msft I think maybe you meant #6134.

**Comment by zadjii-msft** [comment]
oh my god I so did, I even had that tab open and everything. How... ugh. Thanks.
