### ISSUE TITLE
some ligature rendered abnormally

### ISSUE THREAD

**Issue by stark-zhang** [microsoft/terminal#12601]
### Windows Terminal version

1.13.10395.0(preview)

### Windows build number

10.0.19042.1466

### Other Software

Something over SSH to CentOS 7.9:
+ neovim 0.6.1
+ tmux 3.1a

Fonts:
[FiraCode NF(with windows compatible)](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip)

### Steps to reproduce

1. install FiraCode NF follow above link
2. terminal configuration:
    ```json
    {
        "protiles": {
             "lists": [
                {
                    "adjustIndistinguishableColors": true,
                    "antialiasingMode": "cleartype",
                    "backgroundImage": null,
                    "closeOnExit": "always",
                    "colorScheme": "Campbell",
                    "commandline": "ssh <username>@<hostname>",
                    "name": "<remoteHost>",
                    "cursorShape": "underscore",
                    "experimental.useAtlasEngine": true,
                    "font": {
                        "face": "FiraCode NF",
                        "size": 11
                    },
                    "guid": "{6c5275a4-b63e-46ce-a2eb-e3ea1f73666f}",
                    "hidden": false,
                    "historySize": 100001,
                    "opacity": 85,
                    "padding": "8",
                    "useAcrylic": true
                }
            ]
        }
    }
    ```
3. print this text on terminal(the logo of neovim in following screenshots):
[test.txt](https://github.com/microsoft/terminal/files/8159332/test.txt)

4. it could be reproduced under powershell 7 on Windows

### Expected Behavior

the true rendering in other terminal:

![image](https://user-images.githubusercontent.com/17326718/156116977-a91c3b3e-fad1-49a4-97ed-e3ebdfd00292.png)
![image](https://user-images.githubusercontent.com/17326718/156117002-2b2afd14-5b6d-4133-9250-5e848be84416.png)

### Actual Behavior

you can find ligatures not effective in screenshots:

![image](https://user-images.githubusercontent.com/17326718/156116802-7bd54f2e-8791-4b73-9bb3-e5895c40275d.png)
![image](https://user-images.githubusercontent.com/17326718/156116898-bbf7cf40-938b-4961-bc2d-611231573ead.png)

screenshot of Powershell 7:
![image](https://user-images.githubusercontent.com/17326718/156120184-b5f1a4e6-7d31-472d-b185-a6ebacc3654b.png)

**Comment by Finii** [comment]
I believe this is no bug of `Windows Terminal` but is related to the used font. The linked font is a rather old variant and there have been several fixes in the glyph sizes in the meanwhile. Will check with a HEAD release of that font.

**Comment by Finii** [comment]
With the HEAD font I can not reproduce the issue (no breaks in horizontal box lines).
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf

But then I have not the Powershell window?
Maybe you can give us the NeoVim Ascii Art for a test.

![image](https://user-images.githubusercontent.com/16012374/156155626-aa40f659-34cf-40d9-b6f2-485b24a27ad3.png)

**Comment by zadjii-msft** [comment]
This might just be the same thing as #12566. Switch to grayscale antialiasing.

**Comment by zadjii-msft** [comment]
Okay, sorry for the brief reply earlier. Looking more carefully, I'm gonna say this is definitely a /dup of #8993. This isn't an issue with _ligatures_, but rather the way cleartype antialiasing interacts with box drawing characters.

**Comment by stark-zhang** [comment]
> With the HEAD font I can not reproduce the issue (no breaks in horizontal box lines). https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf
> 
> But then I have not the Powershell window? Maybe you can give us the NeoVim Ascii Art for a test.
> 
> ![image](https://user-images.githubusercontent.com/16012374/156155626-aa40f659-34cf-40d9-b6f2-485b24a27ad3.png)

I uploaded the test.txt, includes NeoVim Ascii Art.

**Comment by stark-zhang** [comment]
> Okay, sorry for the brief reply earlier. Looking more carefully, I'm gonna say this is definitely a /dup of #8993. This isn't an issue with _ligatures_, but rather the way cleartype antialiasing interacts with box drawing characters.

I cannot find effective solution in #8993, any suggestions? I came back to the stable release in MS store right now.

**Comment by zadjii-msft** [comment]
Set `"antialiasingMode": "grayscale",` in your profile. See https://github.com/microsoft/terminal/issues/8993#issuecomment-903904116

**Comment by stark-zhang** [comment]
> Set `"antialiasingMode": "grayscale",` in your profile. See [#8993 (comment)](https://github.com/microsoft/terminal/issues/8993#issuecomment-903904116)

![image](https://user-images.githubusercontent.com/17326718/156200775-c7656924-20d8-4071-9c5b-4f2e2e35e3a3.png)

thanks for your reply but it is not effective.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?
