### ISSUE TITLE
The environment variables of "Open in Windows Terminal" and "Manually Start Windows Terminal" are inconsistent.

### ISSUE THREAD

**Issue by TigerBeanst** [microsoft/terminal#12602]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Steps to reproduce

First, add `D:\DHYProjects\Las2Osgt\osg;` to `Path` in environment variable.

![image](https://user-images.githubusercontent.com/3889846/156134200-66fd385e-0c03-4156-ac0b-80677fea856c.png)

1. Right click in Explorer, then click "Open in Windows Terminal"（Chinese: `在 Windows 终端中打开`）

Mark as **_WT1_**:
![image](https://user-images.githubusercontent.com/3889846/156132135-5be7ac4e-3774-4cf3-bbbb-011868533392.png)

and Manually Start Windows Terminal, mark as **_WT2_**:

![image](https://user-images.githubusercontent.com/3889846/156133665-c74792ed-6102-4b90-a022-f3212a048c20.png)

2. Check `Path` environment variable:

![image](https://user-images.githubusercontent.com/3889846/156134351-63964d45-6b0c-4f91-9fc3-7aaa8f4865bf.png)

### Expected Behavior

Their values should be exactly the same.

### Actual Behavior

I can't find `D:\DHYProjects\Las2Osgt\osg` in **_WT1_**, which is started by right-click in explorer.

I have trid to kill explorer.exe and restart it in Task Manager. It doesn't work.

_It looks like I'll have to reboot my computer to get it work._

**Comment by wkl007** [comment]
I have the same issue

**Comment by TigerBeanst** [comment]
> * Is the Terminal already running when you open a new tab via the Explorer context menu? (If so, this is probably a riff on [Feature Request: Terminal should listen for the WM_SETTINGCHANGE for environment variable updates #1125](https://github.com/microsoft/terminal/issues/1125)).
> * If this is a "cold launch" (there aren't any other running Terminal windows), then this is something else. [Windows terminal path is different if launched with wt.exe #11777](https://github.com/microsoft/terminal/issues/11777) looks a bit related, so does [Open alias "wt" have unexpected behavior. #12545](https://github.com/microsoft/terminal/issues/12545)

**Is the Terminal already running when you open a new tab via the Explorer context menu?**
No. I closed all Terminal windows and try it.

**Comment by bugproof** [comment]
Any workaround for this? It became kinda annoying.

**Comment by stzb321** [comment]
the issue still not been fixed

**Comment by MrDach** [comment]
Any updates on this? It's slightly annoying having to open Terminal via the start menu and having to navigate to the folder every time.

**Comment by madmax91** [comment]
This is what worked for me to fix this issue:
Go to Settings > Apps > Apps & Features > Terminal and click on Terminate, this will kill all the Terminal processes and related processes and will refresh the cached variables I suppose. After this even if I launch the Terminal from context menu it has the correct variables loaded

**Comment by bestK** [comment]
If you use autohotkey, see https://github.com/microsoft/terminal/issues/8862#issuecomment-1294499276

**Comment by TheComputerM** [comment]
Having the same problem with pnpm. Opening the terminal from the start menu works properly but opening the terminal from the right click context menu will not have `PNPM_HOME` environment variable set correctly.

**Comment by zadjii-msft** [comment]
This almost certainly was resolved by #14999
