### ISSUE TITLE
Weird blank space after pasting from clipboard

### ISSUE THREAD

**Issue by wiznia** [microsoft/terminal#12604]
Each time I paste something large from the clipboard, this white large background appears in front of the terminal and there's no way of removing it if not by closing the terminal.

![image](https://user-images.githubusercontent.com/5522820/156205911-3815790d-f9df-46ad-9065-6f25cfd84488.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #12447 for more discussion.

/dup #12447
