### ISSUE TITLE
wsl  bash color layer goes unwell, it's against my eyes....

### ISSUE THREAD

**Issue by charlesld** [microsoft/terminal#1261]
* Your Windows build number:

> Microsoft Windows [版本 10.0.18362.116]

* bash version

```shell
C:\WINDOWS\system32>bash
charles@DESKTOP-3DSSNKC:/mnt/c/WINDOWS/system32$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
charles@DESKTOP-3DSSNKC:/mnt/c/WINDOWS/system32$
```

* What you're doing and what's happening:

> just use wsl shell in **jetbrain** IDE(`Idea` `pycharm` `goland`..) 

* What's wrong / what should be happening instead:

after upgrade win10 to current version. then  
**strange color config** when typed `bash` in the console.
![image](https://user-images.githubusercontent.com/23304239/59496729-a7b67e80-8ec4-11e9-8826-d6b912b052cf.png)

**can you see what I typed in the bash console?????????**
but is works well in `win+r -> cmd -> bash` or`win+r -> bash` 
what I can do , or where I can restore the config?   
ide just conf like this ,and no more conf can be set.
![image](https://user-images.githubusercontent.com/23304239/59497717-8bb3dc80-8ec6-11e9-9327-ded513cc85f1.png)

**Comment by charlesld** [comment]
another PC at home running in win10 `[版本 10.0.18362.145]` get same problem, which newly reinstalled os , and new jetbrain version.  
Two computers are using same login id, and I wonder that , had I changed some termial color configs , and they were synced by the account?

**Comment by zadjii-msft** [comment]
@charlesld Does this repro in any environment on your PC other than the jetbrains IDE you're using? Does it happen in a normal conhost window (like the one created by cmd.exe, wsl.exe, powershell)? What about ConEmu/Hyper? VsCode's integrated terminal?

We don't _really_ control what's displayed by the jetbrains terminal - IIRC they're using winpty as a backend for their terminal window.

If I had to guess, the "default background" color for the IDE's terminal is set to cyan, not black
