### ISSUE TITLE
"Full width" option for tabs size

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#12611]
# Description of the new feature/enhancement
I wish there was an option for tabs to have all the `same size` but also expand so that they cover the `whole window width`.

# Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/199648/156389395-4b119acc-9175-48cc-9ef8-735053c08341.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I'm gonna move the body of this to #597 though, to track these all in one place. Thanks!

/dup #597
