### ISSUE TITLE
Pressing Ctrl + K does not color it like other combinations Ctrl + something

### ISSUE THREAD

**Issue by PetitPotiron** [microsoft/terminal#12619]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.0

### Steps to reproduce

Press the keys `Ctrl` and `K` simultaneously in the terminal (windows powershell).

### Expected Behavior

The `^K` text which appears on the screen should be colored in yellow, as below.

![Ctrl+E colored](https://user-images.githubusercontent.com/70655051/156644467-e4f2d382-b271-457c-8847-15a3ded67719.png)

### Actual Behavior

The `^K` text which appears on the screen is not colored (it keeps white), as below.

![Ctrl+K not colored](https://user-images.githubusercontent.com/70655051/156644649-fab97329-e3f0-404e-9fa5-582ddf358c3e.png)

You can see the difference beetween `Ctrl+K` (not colored) and `Ctrl+E` (colored) below.

![Ctrl+E and Ctrl+K](https://user-images.githubusercontent.com/70655051/156644822-5a53452a-ed22-4799-96b9-426edf8f4c5e.png)

**Comment by zadjii-msft** [comment]
This sounds like something that should be reported over at https://github.com/PowerShell/PSReadLine/. But, I'm guessing they don't colorize various printable whitespace characters, like CR(`^M`), VT(`^K`), HT(`^I`):

![image](https://user-images.githubusercontent.com/18356694/156645714-f9e04c1b-4c2e-4eac-b679-0d5e6904a316.png)
