### ISSUE TITLE
Consider remember terminal height in quake mode

### ISSUE THREAD

**Issue by 0xcaffebabe** [microsoft/terminal#12617]
# Description of the new feature/enhancement

In current implements, if resize the terminal height in quake mode, and quake it(use shortcut key to make it disappear), when it back(quake again), it still back to origin state before resize(height state lose).

![image](https://user-images.githubusercontent.com/34188127/156532781-17174093-8e27-4577-adf9-aac6b661b32e.png)
![image](https://user-images.githubusercontent.com/34188127/156532800-97ca02b5-a446-4742-9d8c-b148cff66149.png)
![image](https://user-images.githubusercontent.com/34188127/156532813-475da789-7e2c-4e74-99e5-bdd27231c960.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #12594 for more discussion.

/dup #12594
