### ISSUE TITLE
Detect and Add `GitBash` as a profile, if Git is installed in a particular machine

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#12620]
# Description of the new feature/enhancement

Detect and Add `GitBash` as a profile, if Git is installed in a particular machine, this is similar to that of the Visual Studio Developer Command Prompt feature

# Proposed technical implementation details (optional)

GitBash will be made available as a profile in the context of Windows Terminal.

**Comment by zadjii-msft** [comment]
This is something they already support!

> Git for Windows v2.32.0-rc1 (or the next [snapshot](https://wingit.blob.core.windows.net/files/index.html)) will have this option.

/dup #1394
/dup https://github.com/git-for-windows/git/issues/3183
/dup https://github.com/git-for-windows/build-extra/pull/339
