### ISSUE TITLE
"Open with Windows Terminal" Broken Path

### ISSUE THREAD

**Issue by RealBlueta** [microsoft/terminal#12629]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.527]

### Steps to reproduce

Right click in a folder and click "Open With Windows Terminal" and try running a program that you exported in PATH.

### Expected Behavior

The application or command to run.
I exported a program in PATH and it works just fine if you run cmd manually, but if ran when opening the terminal using "Open With Terminal", it is not found.

### Actual Behavior

'...' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zadjii-msft** [comment]
Is the Terminal already running when you open a new tab via the Explorer context menu? (If so, this is probably a riff on #1125).
If this is a "cold launch" (there aren't any other running Terminal windows), then this is at the very least #12602. (Maybe #11777 is related? but that seems less likely)
