### ISSUE TITLE
Scroll to previous command (snap point)

### ISSUE THREAD

**Issue by carlocardella** [microsoft/terminal#12628]
# Description of the new feature/enhancement

It would be useful to be able to scroll back (and forward) to the position of the previous command: I mean not just scroll up one page or a few lines at a time (already possible) but jump directly to the line of the previous command, similarly to other terminals in Ubuntu and maxOS (e.g. https://stackoverflow.com/questions/17212643/how-to-scroll-back-the-terminal-to-where-the-last-command-was-given).

Visual Studio Code has an implementation here:
- https://code.visualstudio.com/updates/v1_22#_command-tracking
- [scrollToPreviousCommand](https://github.com/microsoft/vscode/blob/eb87968766f00edb208bb31fda677a9670472856/src/vs/workbench/contrib/terminal/browser/xterm/commandTrackerAddon.ts#L68)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This is being tracked in issue #6232.

**Comment by zadjii-msft** [comment]
/dup  #6232

Thanks!
