### ISSUE TITLE
Adding Windows Terminal Transparent without being blurred.

### ISSUE THREAD

**Issue by ayush-tiwari26** [microsoft/terminal#12623]
I wish to view my background while using windows terminal, i.e. I wish to have something like a transparent windows terminal, from which I can view the background tasks. But Windows Terminal restricts me that I can have transparency but only with blurred effect.
If possible kindly add this feature so developers like me can work more productively.

**Comment by lhecker** [comment]
We already support this. 🙂
On Windows 11 you can disable "acrylic" (blurred) background transparency in your profile settings:

![image](https://user-images.githubusercontent.com/2256941/156670700-bbb06112-5a5f-4574-96bb-bad3a11c6bc1.png)

/dup #603

**Comment by ayush-tiwari26** [comment]
Disabling this makes my terminal completely solid. I wish to have my
terminal clear as mirror so I may look at the background tasks happening.

**Comment by zadjii-msft** [comment]
@ayush-tiwari26 That setting only works on Windows 11. On windows 10, when you disable acrylic, you're gonna get a solid background. See also: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#opacity

**Comment by lhecker** [comment]
And to add to this:
> As I mentioned above, we're working on servicing the necessary OS side fixes to Windows 10 to make it work, but those take a lot longer than Terminal releases.
