### ISSUE TITLE
Trailing commas in profiles schema

### ISSUE THREAD

**Issue by aeschli** [microsoft/terminal#12639]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1526]

### Other Software

VIsual Studio Code 1.64.2

### Steps to reproduce

- Open the Windows Terminal Setting
- Click on `Open JSON File`
- Opens in VS Code with an error on the schema:

`Unable to parse content from 'https://aka.ms/terminal-profiles-schema': Parse error at offset 14830`

The problem is 
https://github.com/microsoft/terminal/blob/main/doc%2Fcascadia%2Fprofiles.schema.json#L488
See the trailing comma.

Schema file are JSON and trailing commas are a syntax error.

### Expected Behavior

No error when opening in VS Code

### Actual Behavior

The error comes from trailing commas in the schema file: https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L488

Also:
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L864
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L884
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L904

**Comment by zadjii-msft** [comment]
Well, that wouldn't be hard to fix. Thanks for pointing that out!

**Comment by marceljsh** [comment]
hi i have the same problem but when i remove the comma, an error occurs and it expected a comma. how do I fix this?
![image](https://user-images.githubusercontent.com/70991948/157300525-ccdf3139-7e8d-43e6-8d13-f34f9aeec5e9.png)

**Comment by zadjii-msft** [comment]
.... how did you remove the comma? That `$schema` line is telling VsCode to load the schema from a URL (which I think points at this repo). Removing the comma locally isn't going to fix the error itself, you'd have to try and change the `$schema` line to point at your local copy of the file.

**Comment by marceljsh** [comment]
I'm sorry but I'm new in this thing and I still don't understand how do I fix the problem.
I have copied the raw text from "https://aka.ms/terminal-profiles-schema" and save it to a new local json file. Then I redirect the $schema to my new json file and I remain can't parse the file. How do I fix this?
