### ISSUE TITLE
An updated ConsoleColor enum is needed to enumerate all possible color choices

### ISSUE THREAD

**Issue by RonWright** [microsoft/terminal#12636]
The current ConsoleColor enum enumerates the standard 4-bit colors.  However, if I Console.Write("\u001b[38;5;93m"); or an RGB SGR of "\u001b[48;2;12;34;56m", I would like to have Console.BackgroundColor and Console.ForegroundColor return the exact color that I just sent to the console.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Honestly this sounds like a discussion for dotnet, since they own the `System.Console` APIs. 

For example, /dup https://github.com/dotnet/runtime/issues/52374 looks like the discussion you're looking for ☺️
