### ISSUE TITLE
Reload System Variable when opening a new TAB instead of reload the entire application

### ISSUE THREAD

**Issue by Raffaello** [microsoft/terminal#12634]
# Description of the new feature/enhancement
When installing something, for eg using `winget`, that changes the system path.
Windows terminal must be reloaded.
Instead would be more interesting, if it was enough to open a new tab for that.

# Proposed technical implementation details (optional)
I guess when opening a new tab, is loading the user environmental settings and merge with the system settings.
The system settings are only loaded when windows terminal is opened the first time and "cached".

It might be interesting to have a way to reload them in a new tab.
It could be possible, i think, because at least once are read. So if those are changed should be possible to re-fresh them.
 
Ignoring for now the split screen.

if i am installing with winget github cli for instance. 
that package add an environment system path to the `gh.exe`

that forces to close windows terminal and re open it again to apply that changes. 
That is not a "big issue" but is just annoying.
Having something that could refresh the system variables and make them available to the next shell to open (just considering a new tab at the moment, but it could be in a split screen too), it would increase the productivity.

NOTE:
I am not sure neither honestly if it is related to the windows terminal or the shell in use or winget itself that should trigger something as a post install.
MY best guess is that is related to windows terminal as those system environmental variable looks like are loaded when loading the first time the app and then ignored after that, independently of the guest shell in use.

**Comment by j4james** [comment]
If I've understood you correctly, there's already an issue open for this. See #1125.

**Comment by Raffaello** [comment]
@j4james it looks like it is the same kind of issue, so yes, this can be a duplicate of it. 
thanks.

**Comment by zadjii-msft** [comment]
/dup #1125

Thanks all!
