### ISSUE TITLE
Administrator tabs with non-administrator tabs in the same window

### ISSUE THREAD

**Issue by Carolina2k22** [microsoft/terminal#12646]
# Description of the new feature/enhancement

The feature would allow you to have terminal tabs running in either administrator or non-administrator within the same window, with the tabs denoted by the current shield you see in an administrator window. Unsure of any technical implications or security risks of this, but it would make things far more convenient. If it's an issue it could possibly have specific settings required?

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Sorry, this isn't something that's going to be possible for the Terminal. See [this post](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#elevation) for more details. There's more summary in #5000 as well. 

/dup #1032

**Comment by Carolina2k22** [comment]
> Sorry, this isn't something that's going to be possible for the Terminal. See [this post](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#elevation) for more details. There's more summary in #5000 as well.
> 
> /dup #1032

Thanks for clarifying! Makes sense.

**Comment by dehghani-mehdi** [comment]
You can use [gsudo](https://github.com/gerardog/gsudo)
