### ISSUE TITLE
Guidance: git submodule update --init --recursive (Resource temporarily unavailable)

### ISSUE THREAD

**Issue by phfbfc** [microsoft/terminal#1264]
Followed README and build instructions from issue 489.  
Got stuck at:
`git submodule update --init --recursive`
Which yielded:
`0 [main] sh 6324 fork: child 1504 - died waiting for dll loading, errno 11`
`/mingw64/libexec/git-core/git-sh-setup: fork: retry: resource temporarily unavailable`
To fix this, I attempted the following recommendation mentioned [here,](https://stackoverflow.com/questions/39803268/npm-install-error-receiving-fork-errors-died-waiting-for-dll-loading-errno-1) and modified the input like so:
`npm uninstall -g submodule`
`npm cache clean`
`npm install -g submodule@latest`
Taking this step provided output that looked promising, so I attempted the build, which failed because of the missing wil/Common.h

I'm looking to get past build, and based on other issues, it sounds like the `git submodule update --init --recursive` is my roadblock.  Any help would be appreciated - thanks for your consideration.

**Comment by zadjii-msft** [comment]
This sounds like a `git` issue. Is it unique to the Terminal repo, or can you not init submodules for _any_ git repo?

I'd look in #489, and follow up in the issue tracker for wherever you got `git` from.

**Comment by DHowett-MSFT** [comment]
Also, would you mind trying _actual git for windows_? It looks like this is mingw64's git, and I don't know how npm is getting involved here ...

**Comment by burhan** [comment]
Try using the [github desktop](https://help.github.com/en/desktop/getting-started-with-github-desktop/installing-github-desktop), cloning the repository there and then following the steps.

**Comment by squeeter** [comment]
> Also, would you mind trying _actual git for windows_? It looks like this is mingw64's git, and I don't know how npm is getting involved here ...

@DHowett-MSFT:  Good call on git for windows - I overlooked that this machine was running a different setup.  As for npm, I was looking for solutions based on similar errors.  At the time, I thought it was a git built-in.

**Comment by squeeter** [comment]
Uninstalled/Reinstalled git solved this issue.

**Comment by DHowett-MSFT** [comment]
Thanks for testing.
