### ISSUE TITLE
Does not restart on correct monitor

### ISSUE THREAD

**Issue by SteveALee** [microsoft/terminal#12647]
### Windows Terminal version

1.11.3471.0

### Windows build number

21H2 (there is no ver in WSL or cmd)

### Other Software

Windows 11 - running terminal from a task bar icon but windows 11 seems to have removed ability to see what the properties are (yet another win 11 fail)

### Steps to reproduce

1) have multiple monitors attached to PC.
2) open Terminal.
3) move to another monitor rather than default
4) close terminal 
5) open again 

### Expected Behavior

Opens on same monitor it was last on

### Actual Behavior

Opens on default monitor

**Comment by zadjii-msft** [comment]
On Terminal Preview, there's a setting to enable restoring your open windows (including tabs and position) when you relaunch the Terminal: [Behavior when starting a new terminal session](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session) 

If you just want the ability to restore the window position, we're tracking that in /dup #12633

**Comment by SteveALee** [comment]
OK, sorry, I did search but a lot of irrelevant bugs.

Thanks
