### ISSUE TITLE
Add support for SSH sessions based on hosts defined in ~/.ssh/config

### ISSUE THREAD

**Issue by tracker1** [microsoft/terminal#12651]
# Description of the new feature/enhancement

It would be a nice feature, if one could select an "ssh app" or if the ssh client is installed that Terminal can detect, that it will then import the hosts defined in ~/.ssh/config and present them below the Profiles in the dropdown.  Also, being able to (re)define the detected ssh application, and directory for the ssh config (such as using a WSL environment).

This would allow for easy/transparent support to create tabs as effectively SSH sessions, without having to first open a console and execute the ssh command.  Just a nicety.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22ssh+config%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9031 for more discussion.

/dup #9031
