### ISSUE TITLE
Opening wt.exe from WindowsApps in Program Files Causing Error 22

### ISSUE THREAD

**Issue by pc-v2** [microsoft/terminal#12654]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.556

### Other Software

oh my posh

### Steps to reproduce

Open Windows Terminal Installation folder (in c:\program files\WindowsApps)
Run wt.exe from that folder
WT returns error 22
Now I can't run wt.exe from Win+R or search and open wt.exe

(I know its stupid)

### Actual Behavior

wt.exe returns error 22

**Comment by zadjii-msft** [comment]
Why are you trying to run the things in `WindowsApps` directly? There's a pile of permissions on those files that are designed to stop you from doing that, and changing those also can randomly break other things. See #9452 and https://github.com/microsoft/terminal/issues?q=is%3Aissue+label%3ACulprit-Centennial+ in general.

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/158046120-3f7c05be-6c66-406e-b17c-f74cb4b06724.png)
the culprit are this, retoggling Windows terminal causing certain registry to C:\Program Files\WindowsApp folder, not C:\Users\<username>\AppData\Local\Microsoft\Windows\WindowsApp

**Comment by pc-v2** [comment]
i already create new local account and then retoggling it caused registry value to wrong address

**Comment by pc-v2** [comment]
here's the video showcasing the bug?
https://youtu.be/6yyqAJv8lQA

**Comment by pc-v2** [comment]
oh, i am wrong, running `icacls "C:\Program Files\WindowsApps" /reset /t /c /q` with powershell in SYSTEM user fix it
