### ISSUE TITLE
Shell context menu needs to escape semicolons in the path

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12650]
From an internal thread: 

> Repro is very simple, create a folder named “Open_me_in_Windows_Terminal;calc.exe;”, copy “calc.exe” inside the folder and then, from within the folder, Right Click -> Open in Windows Terminal. You should see calc starting.

> It even works without the exe ext, you can rename to folder `foo;calc` and rename calc.exe to only calc. Works with any name

There's a mail thread about this.

**Comment by ianjoneill** [comment]
I fixed this in #11314 I think. I can't repro it in Terminal preview (1.13.10395.0)

**Comment by DHowett** [comment]
OMG, you're right! Yay!

/dup #11273
