### ISSUE TITLE
Scrolling using trackpad when editing a file in vim/nano should move cursor up/down

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#12657]
# Description of the new feature/enhancement
Using the trackpad to scroll up/down by default scrolls terminal buffer. When editing a file in vim, doing the same thing should send cursor up/down to the terminal so that it scrolls within vim/nano's context rather than scrolling the terminal buffer.

This is what VSCode or iTerm do for example.

Here is what happens in Windows Terminal when using the trackpad in nano:

![terminal-trackpad](https://user-images.githubusercontent.com/199648/157679028-c3752ec9-e4be-4ec7-b35d-a5f4dd9ec2d4.gif)

# Proposed technical implementation details (optional)
Here is what happens in VSCode (and I suggest should happen in Windows Terminal too):

https://user-images.githubusercontent.com/199648/157679351-5679492f-c843-4458-b6c0-00f9d0df90c8.mov

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3321 for more discussion.

/dup #3321
