### ISSUE TITLE
Terminal's height changed when pasting text longer than 5KB in WT 1.13

### ISSUE THREAD

**Issue by emon100** [microsoft/terminal#12668]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.2.1
vim 8.2 in ArchLinux WSL

### Steps to reproduce

1. Open Windows terminal.
2. Open vim in WSL
3. Enter vim insert mode.
4. Press shift-insert to paste text.

https://user-images.githubusercontent.com/12141326/157854058-4861e78c-306a-4f6f-82e5-a489f583ab4a.mp4

Edit: The video can't play in Chrome but can play in iOS Safari. Very strange.

### Expected Behavior

Terminal shouldn't resize.

### Actual Behavior

Terminal's height reduces to half of the original height.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #12447 for more discussion.

/dup #12447
