### ISSUE TITLE
persistedWindowLayout does not work as expected on 1.12.10393.0

### ISSUE THREAD

**Issue by scaramushe** [microsoft/terminal#12684]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Following guidelines in 
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session  :

Add the following line to the settings file:
    `"firstWindowPreference": "persistedWindowLayout",`
Settings file: ` C:\Users\[User
 Name]\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json` - attached at txt
[settings.txt](https://github.com/microsoft/terminal/files/8239228/settings.txt)

- Create some custom window state (multiple tabs and panes with different names) 
- Close the app using the  "X" button or "Alt-F4" combination
- Open the app again

### Expected Behavior

Open last set of panes and tabs as before closing

### Actual Behavior

Open single tab and pane

**Comment by Rosefield** [comment]
One guess, do you use the quake window? The logic is that on first start (i.e. no terminals running) it will load the saved state, but of course if you have a hidden quake window open it won't reload state. If you want to make sure that all of the windows are closed there is the `quit` action that will close all open terminal windows and save all of their layouts.

**Comment by Rosefield** [comment]
On second thought, it is probably that this feature is not enabled on stable builds yet (just terminal preview). A future release will enable for stable builds. https://github.com/microsoft/terminal/issues/12422

**Comment by scaramushe** [comment]
Thanks for the reply!
Indeed this is available only in preview, verified that it works with 1.13.10395.0 - current preview version available on winget
Thanks a lot, closing.

**Comment by scaramushe** [comment]
One thought - perhaps the documentation should state that this is available only in preview 
Opened https://github.com/MicrosoftDocs/terminal/issues/521 to reflect that
