### ISSUE TITLE
Add option to confirm close tab on close button clicks

### ISSUE THREAD

**Issue by working-name** [microsoft/terminal#12686]
# Description of the new feature/enhancement

Running on a 4k screen with lots of tabs open, and it gets crowded. But the same can be easily reproduced by having a tab title that's very short like 2 characters. When you try to activate a tab, you inadvertently click the close button. And that it's it, game over. Doesn't matter what you were running inside, it's gone. I can't tell you how many times I wanted to reproduce the youtube guy who was bashing his monitor with the keyboard.

# Proposed technical implementation details (optional)

- Add an option to confirm closing a tab
- make the closing button area smaller
- make the tabs HUGE
- let me place tabs on the side of a window rather than top (you know, more width than height in all modern monitors...)
- just do away with the close button altogether, I wouldn't mind that either.

I don't know what's useful but probably the least annoying to everyone might be to just add an option to confirm closing a tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestions! These are actually already being tracked by other issues on our repo - please refer to:


* /dup #2976 / /dup  #6549
* Not specifically tracked anywhere, but sorta sounds like a #3327 kind of thing
* /dup #597
* /dup #835
* /dup #3335
