### ISSUE TITLE
Rendering inaccuracy while loading tabs

### ISSUE THREAD

**Issue by Shantanu66** [microsoft/terminal#12683]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.19044.1586

### Steps to reproduce

Running  the terminal for 4 to 5 time after closing each time

### Actual Behavior

Running  the terminal sometimes renders blurry software

**Comment by zadjii-msft** [comment]
Can you maybe send a screenshot? There's any number of things this could be, but I'm not really sure what specific issue you're having just based on your description.
