### ISSUE TITLE
Ubuntu not present on new terminal build

### ISSUE THREAD

**Issue by Sorikal** [microsoft/terminal#1268]
![90ad0b1459f1dc27c655ab3a0456e9d6](https://user-images.githubusercontent.com/47671438/59528564-52d82f80-8ee7-11e9-812d-c921414ce118.png)

Ubuntu not present on new build

wsl -l Result:

Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

**Comment by DHowett-MSFT** [comment]
Reading this message:

> Windows Subsystem for Linux has no installed distributions.

Windows Terminal cannot detect Ubuntu **if you do not have Ubuntu installed.**

If you believe you have Ubuntu installed, you might need to file an issue at [Microsoft/WSL](https://github.com/microsoft/wsl) to get help troubleshooting that problem.
