### ISSUE TITLE
Open in windows terminal option gone

### ISSUE THREAD

**Issue by shashwata27** [microsoft/terminal#12680]
### Windows Terminal version

1.11.3471.0

### Windows build number

Microsoft Windows [Version 10.0.22000.556]

### Steps to reproduce

I literally restored my lappy using the windows resort pc option and opted in for cloud restore. My PC was running slow before that's why. I had this option before when I install win 11 for 1st time. But now it's just plain gone. Went to the registry there was no blocked folder there also under shellextensions.

### Expected Behavior

should be able to get the option of Open in windows terminal when I right-click anywhere.

### Actual Behavior

the terminal is working fine when I launch from start menu and can add gitbash to the terminal also. But that option to open in windows terminal when we right click on desktop or anywhere is goneright-click.

![image](https://user-images.githubusercontent.com/60866496/158019782-b0f9b50e-c267-4ef0-a942-23276ddf48d2.png)
![image](https://user-images.githubusercontent.com/60866496/158019792-d67916f9-a8e7-4504-b526-7f330ca3982d.png)

**Comment by zadjii-msft** [comment]
Does this work if you right click on and actual folder within File Explorer? (not like, on the background of a directory, but on a folder itself)? If so, this might be #11839

**Comment by shashwata27** [comment]
> Does this work if you right click on and actual folder within File Explorer? (not like, on the background of a directory, but on a folder itself)? If so, this might be #11839

No it was not coming even then. You can see the 1st screenshot I posted in the same issue. I was aware of that issue. I thought this is diff.

https://github.com/microsoft/terminal/issues/11839#issuecomment-1065856908

**Comment by zadjii-msft** [comment]
Hey we made some changes to the way the shell extension tries to find the active directory in the last couple builds - does this work on 1.16 / 1.17 for you/?

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
