### ISSUE TITLE
Windos Terminal Stopped working during Windows 11 startup

### ISSUE THREAD

**Issue by yooakim** [microsoft/terminal#12688]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Power on my latop (Lenovo ThinkPad X1 Carbon Gen 9)
2. See in eventlog that Windows Terminal app "stopped working" - I did not try to start the Terminal app, so its something during startup (I have it set as the default terminal for Windows)

### Expected Behavior

No error messages 

### Actual Behavior

The following error is recorded in the Windows reliability and problem history:

```
Source
WindowsTerminal.exe

Summary
Stopped working

Date
‎2022-‎03-‎14 07:19

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.12.10393.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

Problem signature
Problem Event Name:	MoBEX
Package Full Name:	Microsoft.WindowsTerminal_1.12.10393.0_x64__8wekyb3d8bbwe
Application Name:	praid:App
Application Version:	1.12.2202.8003
Application Timestamp:	62031757
Fault Module Name:	ucrtbase.dll
Fault Module Version:	10.0.22000.1
Fault Module Timestamp:	00e78ce9
Exception Offset:	000000000007dd7e
Exception Code:	c0000409
Exception Data:	0000000000000007
OS Version:	10.0.22000.2.0.0.256.48
Locale ID:	1053
Additional Information 1:	8cab
Additional Information 2:	8cabaa4743c8cd545d2e3b1a8e50c7c7
Additional Information 3:	605f
Additional Information 4:	605f219ea142079dbe14390730209d1a

Extra information about the problem
Bucket ID:	5b0ecaf1e95eb17ef05c08df0dcc9692 (1178826956566468242)

```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #12384 for more discussion.

/dup #12384
