### ISSUE TITLE
Documentation issue with Acrylic

### ISSUE THREAD

**Issue by PTracana** [microsoft/terminal#12692]
While turning on Acrylic on the windows terminal if the windows setting Transparancy effects is not turned on (Windows Settings -> Customize -> Colors -> Transparancy effects) the acrylic effect will not take effect.
Feedback about this feature should be given to the user while trying to turn acrylic on without this setting on.

**Comment by Aadv1k** [comment]
This happened with me too, but maybe acrylic requires transparency effects to be turned on(?),

**Comment by zadjii-msft** [comment]
You know, we're tracking something similar in /dup #8901. I'll update that to include this. Thanks!
