### ISSUE TITLE
OpenConsoleProxy.dll not code signed

### ISSUE THREAD

**Issue by illumiN8i** [microsoft/terminal#12695]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.0

### Steps to reproduce

View properties on file "C:\ProgramData\Microsoft\Windows\AppRepository\Packages\Microsoft.WindowsTerminal_1.12.10393.0_x64__8wekyb3d8bbwe\PackagedCom\OpenConsoleProxy.dll"
Notice that Digital Signatures tab does not appear in the properties.

Virus total also confirms the file is not digitally signed:
https://www.virustotal.com/gui/file/320addd674045f097f85da27a88d0b0cf935adb8f1301b7af52c4c8f0a9145e5/details

### Expected Behavior

File should be digitally signed like other official Microsoft files.

### Actual Behavior

File is not digitally signed. This can cause the file to be blocked by application allow listing software.

**Comment by zadjii-msft** [comment]
Yea I'm gonna tap @DHowett in on this one. My memory serves poorly but I thought that the files themselves weren't codesigned but the entire msix (or msix bundle) was? That could entirely be wrong though.

**Comment by DHowett** [comment]
Correct, this file is _catalog signed._ An application integrity framework should support catalog signing.

**Comment by illumiN8i** [comment]
I'll forward this to our application control product vendor. Thanks!

**Comment by joeltuckwell** [comment]
I just wanted to jump on this issue @DHowett - I've run this file against sigcheck (with the flags to check catalog signing) and it's returning n/a for publisher. Are you seeing something different on your system? If so could you please provide what you are seeing on your system and the hash for the version of OpenConsoleProxy.dll that you are checking?

Thank you!

![image](https://user-images.githubusercontent.com/15152712/169977992-790efe68-fd1b-4b36-b527-186ff9de2db8.png)
