### ISSUE TITLE
Pasting link containing capital letters in the terminal is dropping the capital letters

### ISSUE THREAD

**Issue by Mutahhar** [microsoft/terminal#12704]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19043.0

### Steps to reproduce

I am trying to clone a git repo.
Here is the URL git clone `https://MutahharNaseer@bitbucket.org/...`

When I paste this URL in the windows terminal having `Windows PowerShell` it just drops the capital letters of the URL. So upon pasting the above URL becomes `https://utahharaseer@bitbucket.org/...`
Notice the missing M and N 

### Expected Behavior

On pasting it should paste the whole copied string.

### Actual Behavior

When I paste this URL `https://MutahharNaseer@bitbucket.org/...` in the windows terminal having `Windows PowerShell` it just drops the capital letters of the URL.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+capital+letters+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #7087 for more discussion.


From that thread: https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this https://github.com/PowerShell/PowerShell/issues/10794 and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

/dup https://github.com/PowerShell/PowerShell/issues/10794

**Comment by Mutahhar** [comment]
Thankyou @zadjii-msft for pointing me to the solution. The issue was with `PowerShell/PSReadLine`.

Here is how I resolved this

1. Running the following commands from an elevated (Run as Administrator) Windows PowerShell session:
```
Install-Module -Name PowerShellGet -Force
Exit
```

2. After installing `PowerShellGet`, get the latest prerelease version of `PSReadLine` by running
```
Install-Module PSReadLine -AllowPrerelease -Force
```
