### ISSUE TITLE
VSC-like recent used command in command plate (search result)

### ISSUE THREAD

**Issue by Civon** [microsoft/terminal#12709]
# Description of the new feature/enhancement
A VSCode-like recently used (history) command in the command plate is very helpful by doing repeated jobs.
Scenarios:
1. executing a command that does not have a shortcut, like "rename tab title" or "toggle always on top mode". With this feature on, you can save time to type at least two keywords to do so. You can switch tab than re-do it with "ctrl + shift + p" + enter.

2. skip unwanted alike command. You want to new a tab that you can not tell it is profile 7 or 8. Without a mouse, you will be willing to use the nested command "new tab... with >", but, as image, you may need too press tons of down arrow to reach that command instead of the one without nested command.
![image](https://user-images.githubusercontent.com/24861096/158698693-808c8fa6-8e5c-4267-899d-0c2e6e08ccd5.png)
Maybe you will later find out: you can do this by ⌨"ctrl + shift + space" or adding "..." in search.
But, I think the command plate's purpose is to ease the pain/gives hint before you learnt the shortcut.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
In general, I think you're looking for the same thing as #6647.

FWIW, the command palette does do "fuzzy" matching, so typing `nt.` will probably automatically filter to `New Tab...` for you. 

Thanks!

/dup #6647
