### ISSUE TITLE
Windows Terminal font does not render smooth when connected to external 4K monitor

### ISSUE THREAD

**Issue by N0AGI** [microsoft/terminal#12718]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1586

### Other Software

running fish shell, version 3.3.1 with omf agnoster.

here's the screenshot when connected to the external 4K monitor
![1](https://user-images.githubusercontent.com/74984418/159008022-87b5c983-7634-49be-9201-afede46690cb.png)

here's the screenshot of the same visual when not connected to the external 4K monitor
![4](https://user-images.githubusercontent.com/74984418/159015766-12cae6fe-321f-4977-83aa-62aa76ab26b6.png)

settings page
![2](https://user-images.githubusercontent.com/74984418/159008031-2010f94c-9b74-45fb-a3b9-363d03ec395b.png)

### Steps to reproduce
When connected to an external 4K monitor, fonts don't render smoothly.  Without the external 4K monitor, they look just fine.

### Expected Behavior
expected to see smoother font rendering

### Actual Behavior
distorted rendering

**Comment by lhecker** [comment]
@N0AGI Sorry! This seems to have fallen off our radar. Does this issue still occur for you?

**Comment by N0AGI** [comment]
Yes, the last time I checked 2 weeks ago.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lhecker** [comment]
Which version are you using? What GPU is the 4K monitor connected to?
Could you try to enable "AtlasEngine" in the "Rendering" settings if it isn't enabled yet?

**Comment by carlos-zamora** [comment]
Hi @N0AGI. Have you tried the suggestions @lhecker proposed above? Also, what's your display scaling set to for this monitor?

**Comment by jithu7432** [comment]
Resolution: Native
Scaling: 100%

[alacritty](https://github.com/alacritty/alacritty) renders fonts smoothly, its a windows terminal problem.

**Comment by lhecker** [comment]
This issue has been closed for a while. If you'd like to report that this hasn't been resolved, can you please include more details about your system? For instance, Windows Terminal version, whether AtlasEngine is disabled in the Rendering settings, your GPU model, your driver version, etc.
