### ISSUE TITLE
in File Explorer, typing "wt" in the Address Bar doesn't launch to active folder

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/terminal#12715]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Open a folder in Windows File Explorer
2. click in the address bar (or type Alt+D)
3. type "wt" and Enter 

### Expected Behavior

Windows Terminal launches to the folder that was active in File Explorer

### Actual Behavior

Windows Terminal launches to system32 or user profile

this behavior works when launching Command Prompt (cmd) and Powershell (powershell) from the address bar.

**Comment by burtonrodman** [comment]
btw, tested with different Default Profiles (Command Prompt, Windows PowerShell) ... all behave the same

**Comment by zadjii-msft** [comment]
Please make sure to [read the FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#wt-from-the-file-explorer-address-bar-doesnt-work).

/dup #878
