### ISSUE TITLE
I can't paste "！"

### ISSUE THREAD

**Issue by CRC32EX** [microsoft/terminal#12710]
### Windows Terminal version

1.6.10571.0

### Windows build number

10.0.22000.469

### Steps to reproduce

![1](https://user-images.githubusercontent.com/25629617/158719833-b9985fa0-573f-4cba-bb7d-6c374d3e11cf.gif)

```
abcdefg
abcd!efg
abcd！efg
```

### Expected Behavior

I want paste `abcd！efg`

### Actual Behavior

`abcdefg`

**Comment by LuanVSO** [comment]
in an administrator cmd prompt run:
```powershell
powershell -nop -c install-module psreadline -force
```
this will update the component that reads the text in PowerShell.
