### ISSUE TITLE
"open in terminal" context menu shows in "This PC" and does nothing

### ISSUE THREAD

**Issue by bzzrak** [microsoft/terminal#12717]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.588

### Steps to reproduce

Open this PC, right click the empty space

### Expected Behavior

No "open in terminal" button since This PC isn't a file folder

### Actual Behavior

"Open in terminal" option present, clicking it does nothing
![image](https://user-images.githubusercontent.com/77467869/158968476-ed7ccade-3179-400e-bd70-2b45e71e8a8d.png)

**Comment by Nazar78** [comment]
I have a different but similar problem. From the context menu it works, launching directly from the menu also works. But on the latest Windows 11 it doesn't work: Start -> right-click -> Windows Terminal or with Admin.

In app log:

> Faulting application name: WindowsTerminal.exe, version: 1.11.2112.13011, time stamp: 0x61b80d0f
> Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
> Exception code: 0xc0000409
> Fault offset: 0x000000000007dd7e
> Faulting process id: 0x1254
> Faulting application start time: 0x01d83ac5748f887a
> Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
> Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
> Report Id: 21cedaa7-4728-41fa-bc59-cc7472a07b08
> Faulting package full name: 
> Faulting package-relative application ID: 

> Fault bucket 1680181983093725199, type 5
> Event Name: BEX64
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: WindowsTerminal.exe
> P2: 1.11.2112.13011
> P3: 61b80d0f
> P4: ucrtbase.dll
> P5: 10.0.22000.1
> P6: 00e78ce9
> P7: 000000000007dd7e
> P8: c0000409
> P9: 0000000000000007
> P10:

**Comment by zadjii-msft** [comment]
@Nazar78 that's a totally different issue, you should file a new issue rather than dillute this one with multiple problems. 

@bzzrak Thanks for the report! Pretty sure this should be covered by /dup #12578
