### ISSUE TITLE
inconsistent capitalization in Italian profile menu tooltip

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#12712]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.1586

### Steps to reproduce

Configure Windows Terminal Preview to display in the Italian language.
Press Ctrl+Shift+Space to open the profile menu.
Wait a second and look at the tool tip that pops up.

### Expected Behavior

Consistent capitalization and spacing.

### Actual Behavior

The tool tip has inconsistent capitalization and spacing:

> Apri nuova scheda\
> _ALT + clic per dividere la finestra corrente_
> _MAIUSC+clic per aprire una nuova finestra_
> _CTRL+Clic per aprire come amministratore_

"Alt + clic" has spaces around the plus sign, but "MAIUSC+clic" and "CTRL+Clic" don't.

"CTRL+Clic" capitalizes "Clic", but "Alt + clic" and "MAIUSC+clic" don't.

**Comment by ritikBhandari** [comment]
hi,
Can i resolve this issue?

**Comment by zadjii-msft** [comment]
I wish we had a story for allowing people to contribute to our localization directly - that would save so much headache. Unfortunately, I don't think our CI is really set up to support that at the moment. We'll need to submit a request to our localization team to get these strings updated manually.

(kind of wild that it was already localized like this 🙃)

Thanks for the offer!

**Comment by ritikBhandari** [comment]
No worries. Thank u :)

**Comment by lhecker** [comment]
Filed internally as 553414 in the `GlobalCollaborationService` project.

**Comment by DHowett** [comment]
Thanks for confirming!
