### ISSUE TITLE
Windows Terminal still run in background even I turned it off

### ISSUE THREAD

**Issue by hungpham3112** [microsoft/terminal#12721]
### Windows Terminal version

1.12.220208003-release1.12

### Windows build number

10.0.22000.556

### Other Software

I installed windows-terminal with scoop

### Steps to reproduce

1. scoop bucket add extras
2. scoop install windows-terminal
3. open wt in terminal
4. turn off wt
5. scoop uninstall windows-terminal and see error 

### Expected Behavior

It can uninstall like normal.

### Actual Behavior

In screen record below, I have only 3 tabs and none of them are windows-terminal. I closed it but still can't uninstall, there's still something running in background. I opened an issue in scoop repo https://github.com/ScoopInstaller/Scoop/issues/4701

![bandicam 2022-03-18 21-53-19-630](https://user-images.githubusercontent.com/75968004/159027289-145177ec-d073-459a-ad88-aff214402a99.gif)

**Comment by hungpham3112** [comment]
> Did you set up the Terminal as your Default Terminal application? It's possible that there's a leftover RuntimeBroker hanging around keeping the Terminal process alive, even after the window exited.
> 
> You might be able to find that process with
> 
> ```
> tasklist /FI "IMAGENAME eq WindowsTerminal.exe"
> ```
> 
> And then Task Manager should show the a RuntimeBroker.exe associated with it. (if my theory is correct).
> 
> I don't believe that the remoting code's COM registration should leave the RuntimeBroker around after we exit, but that might be another place for me to look.

For some reasons, I don't want to set up the Terminal as Default.

Here is output of `tasklist /FI "IMAGENAME eq WindowsTerminal.exe"`:

![image](https://user-images.githubusercontent.com/75968004/159097420-c41324cd-d016-4fcd-9720-a3e505926791.png)

I didn't see the app named RuntimeBroker.exe.

**Comment by zadjii-msft** [comment]
Hey sorry for the late reply, stuff gets lost in the triage queue. 

I'm not sure there's a better way to kill off RuntimBroker instances, if that indeed is the process hanging around. Could be something else too - try double checking in Task Manager (sort by name) if there's a Terminal entry, and check if there's anything else the OS thinks is running in the Terminal package.

RuntimeBroker is supposed to clean itself up after a few seconds to minutes though...

This might just be an ask on `scoop`. There's definitely ways to force update packages even if they're in use (hell, the Store does it all the time 😅 )

**Comment by hungpham3112** [comment]
Thanks for your information, I will take a look at this issue and give you feedback in near future, right now I'm quite busy at work. Just let it opened. Thank you.
