### ISSUE TITLE
Can't find default terminal setting in Win 10

### ISSUE THREAD

**Issue by netheril96** [microsoft/terminal#12729]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1586

### Steps to reproduce

Opening the settings of Windows Terminal

### Expected Behavior

I should be seeing an option for default terminal setting, like in [this article](https://www.kunal-chowdhury.com/2021/05/set-default-terminal-application-in-windows-10.html) or [this article](https://winaero.com/change-default-terminal-application-in-windows-10/).

### Actual Behavior

None of such option is listed at the settings page.

![image](https://user-images.githubusercontent.com/836839/159173415-8a427b28-7036-49bf-b257-e61f8a097289.png)

**Comment by j4james** [comment]
The default terminal functionality is only available in Windows 11. This is explained in the FAQ entry:
[Will the default terminal functionality be coming to Windows 10?](
https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#will-the-default-terminal-functionality-be-coming-to-windows-10)

**Comment by netheril96** [comment]
So those articles are simply lying.
