### ISSUE TITLE
Improve ColorTool to see different schemes in Terminal

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#12736]
As a tool for being able to see these schemes applied in a terminal, I wrote this cmd script, [ansi-colors.cmd](https://gist.github.com/rbeesley/411609adbedeaa5b4dcce54921852310), which can be used to put all the SGR parameters together. It is currently configured for showing 1, 4, 7, 30-37, 40-47, and 100-107, and the combinations of those which make sense.

![ansi-color cmd](https://user-images.githubusercontent.com/3703112/84349159-92be0b00-ab6b-11ea-9882-c446050acf13.gif)

While not written for creating this specific color scheme, I think this might be a tool worth adding to the repo to make it easier to see the different color combinations. It is all self-contained in one .cmd file with no necessary external dependencies. There is an option to use PowerShell to generate the ESC non-printable character, but in this gist it just uses one saved in the file. There is also an optional dependency on CHCP if the output is going to show Unicode, but it does not need to be required. It uses a data segment embedded in the file itself, so the definition of what is shown can quickly and easily be changed to something else.

_Originally posted by @rbeesley in https://github.com/microsoft/terminal/issues/6176#issuecomment-642422924_

**Comment by rbeesley** [comment]
If you want to keep this open to do more work in ColorTool, be my guest. The script I mentioned in the original comment was turned into issue #6470. And resolved in preview 1.13.10336.0, merging #11932. I also started documenting how it works in more depth in a series on Medium (https://link.medium.com/rfc9rux6Aob).

**Comment by zadjii-msft** [comment]
This was a bit of a miscommunication - sorry for the confusion folks!

/dup #6470
