### ISSUE TITLE
Developer Guidance - please mention .NET Framework 4.8 targeting pack

### ISSUE THREAD

**Issue by tahir-hassan** [microsoft/terminal#12733]
The Developer Guidance section in the README.md (https://github.com/microsoft/terminal#developer-guidance) should mention that .NET Framework 4.8 targeting pack is required as a prerequisite.

Because it takes long to compile, might annoy someone to realize quite late in the process that they should have installed it.

Thank you `:)`

**Comment by zadjii-msft** [comment]
Did VS not prompt you to install it automatically? We may have missed updating our vsconfig. 

FWIW though, I think that's only used for some test projects. Building `Host.EXE` (conhost) or `CascadiaPackage` (the Terminal) shouldn't depend on any .NET _anything_.

**Comment by tahir-hassan** [comment]
@zadjii-msft I followed the section on [building it it using PowerShell](https://github.com/microsoft/terminal#building-in-powershell), so I did not open Visual Studio to built it.   It is only much later in the build process does it tell you that you need 4.8.

**Comment by zadjii-msft** [comment]
If you'd like, feel free to open a PR to add the note to the docs yourself ☺️
