### ISSUE TITLE
Win+X menu (also wt.exe) and Windows Terminal from Start Menus Windows Terminal Have Different Version

### ISSUE THREAD

**Issue by pc-v2** [microsoft/terminal#12738]
### Windows Terminal version

Terminal (Unpackaged) Version: 1.12.220208003-release1.12 and Windows Terminal Version: 1.12.10393.0

### Windows build number

Microsoft Windows NT 10.0.22000.588 (Release Preview)

### Steps to reproduce

create new local windows account
sign into new local account
open wt.exe or from Win+X and open Windows Terminal from Windows search or start menu,
then see version info from about in terminal's dropdown menu
![image](https://user-images.githubusercontent.com/58063311/159421488-dbb9cbcf-35a4-4d16-a2df-33df7171040a.png)

### Expected Behavior

both terminal have same version

### Actual Behavior

I got two different terminal

**Comment by SainoNamkho** [comment]
You can change `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe`'s `(Default)` to `%LocalAppData%\Microsoft\WindowsApps\wt.exe`

**Comment by zadjii-msft** [comment]
Sorry just to be clear, which one opened as the "unpackaged" one for you? The Start Menu, or the Win+X menu?

Does running `wt.exe` from the Run Dialog (<kbd>win+r</kbd>) open the unpackaged or the packaged version?

One of these things lost its package identity, I just wanna know which team I have to go bother 😝 

#9452 may have useful remediation steps

**Comment by pc-v2** [comment]
I haven't touch WindowsApps when creating, log new account and delete old account
before creating new account, I already do
`icacls "C:\Program Files\WindowsApps" /reset /t /c /q`

**Comment by pc-v2** [comment]
the error fixes itself after updating windows to 22581.1
