### ISSUE TITLE
Remove the "x" (close tab) simbol on tabs

### ISSUE THREAD

**Issue by zohozer** [microsoft/terminal#12743]
I would like to see a more cleaner look for tabs without the "x" clossing button on every tab. I can accidentaly press them and close tabs by mistake.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+remove+%22x%22+on+tabs) when filing new issues. This is already being tracked by another issue on our repo - please refer to #3335 for more discussion.

/dup #3335
