### ISSUE TITLE
Text color changes when scrolling PS v5.1 using the MSOnline module

### ISSUE THREAD

**Issue by ITNinja01** [microsoft/terminal#12747]
When using PS v5.1 using the MSOnline module the color of the text will be come lighter when scrolling up or down.

**Comment by zadjii-msft** [comment]
Thanks for filing a bug! Can you make sure to actually use the bug template? For example:
* are you using the Terminal or the vintage console host?
* What OS build are you on?
* If you're using the Terminal, which version?
* Can you maybe share a screenshot? (protip, you can just paste an image from the clipboard into the comment box on github and it'll just upload it for you)
