### ISSUE TITLE
Microsoft.Terminal.Settings.ModelLib.vcxproj fails to build due to missing $quote; in <Exec Command= ...> 

### ISSUE THREAD

**Issue by RonWright** [microsoft/terminal#12745]
### Other Software

VisualStudio 2022.

### Steps to reproduce

Microsoft.Terminal.Settings.ModelLib.vcxproj fails to build when the source directory path contains spaces (as in "P:\GitHub Projects\...").
Microsoft.Terminal.Settings.ModelLib.vcxproj has three <Exec Command=pwsh.exe ...> nodes which do not have double-quotes (&quot;) around the file spec for the GenerateHeaderForJson.ps1 file.  Without the double-quotes the execution of pwsh.exe fails.

### Expected Behavior

Modify the section of Microsoft.Terminal.Settings.ModelLib.vcxproj containing the Commands to be executed.  Following is the changed section:

  
  <Target Name="_TerminalAppGenerateDefaultsH" Inputs="defaults.json" Outputs="Generated Files\defaults.h" BeforeTargets="BeforeClCompile">
    <Exec Command="pwsh.exe -NoProfile â€“ExecutionPolicy Unrestricted &quot;$(OpenConsoleDir)\tools\GenerateHeaderForJson.ps1&quot; -JsonFile defaults.json -OutPath &quot;Generated Files\defaults.h&quot; -VariableName DefaultJson" />
  </Target>
  
  <Target Name="_TerminalAppGenerateDefaultsUniversalH" Inputs="defaults-universal.json" Outputs="Generated Files\defaults-universal.h" BeforeTargets="BeforeClCompile">
    <Exec Command="pwsh.exe -NoProfile â€“ExecutionPolicy Unrestricted &quot;$(OpenConsoleDir)\tools\GenerateHeaderForJson.ps1&quot; -JsonFile defaults-universal.json -OutPath &quot;Generated Files\defaults-universal.h&quot; -VariableName DefaultUniversalJson" />
  </Target>
  
  <Target Name="_TerminalAppGenerateUserSettingsH" Inputs="userDefaults.json" Outputs="Generated Files\userDefaults.h" BeforeTargets="BeforeClCompile">
    <Exec Command="pwsh.exe -NoProfile â€“ExecutionPolicy Unrestricted &quot;$(OpenConsoleDir)\tools\GenerateHeaderForJson.ps1&quot; -JsonFile userDefaults.json -OutPath &quot;Generated Files\userDefaults.h&quot; -VariableName UserSettingsJson" />
  </Target>

[Changes.txt](https://github.com/microsoft/terminal/files/8338413/Changes.txt)

### Actual Behavior

Without the additional &quot;'s in the project file, the Microsoft.Terminal.Settings.ModelLib project fails to build.

**Comment by zadjii-msft** [comment]
Good catch! Someone should fix that. Feel free to open a PR if you'd like ☺️
