### ISSUE TITLE
Minimize Maximize Issue on Windows Terminal

### ISSUE THREAD

**Issue by Prem-DevEloper** [microsoft/terminal#12742]
I cannot able to see the minimize and all the stuff and I cannot able to exit app with the **"X"** Button 

Please Help Me Out

**Comment by zadjii-msft** [comment]
Did you turn on "Focus Mode"?

![image](https://user-images.githubusercontent.com/18356694/159726493-7062a8f8-66d0-4c70-b5b2-ecf314ee2284.png)


linking #12542, but there's a better thread somewhere...
