### ISSUE TITLE
`ms-settings:` for default terminal 

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12759]
> It would be nice if the "set your default terminal" settings page had an `ms-settings:` protocol to launch it. That would make it easier to share a "here's how to change it" link

**Comment by dmachaj** [comment]
Fortunately there is already `ms-settings:developers` that takes you to the page that has this setting.  It just doesn't have the "pre-select the setting so it is really easy" ability that searching for a setting withing Settings does.

**Comment by zadjii-msft** [comment]
As discussed on Teams - `ms-settings:developers` is as good as we're gonna be able to do here 😄
