### ISSUE TITLE
Escape sequence inserted around prompt when starting tmux in an ssh session

### ISSUE THREAD

**Issue by gurka** [microsoft/terminal#12752]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

OpenSSH_8.1p1 for Windows,
Hyper-V VM running Debian testing/bookworm
GNU bash, version 5.1.16
tmux 3.2a

### Steps to reproduce

Start Windows Terminal
Connect to Linux VM using ssh.exe
In bash, start tmux

### Expected Behavior

First line / prompt displays:
```
simon@debian:~$
```

### Actual Behavior

First line / prompt displays:
```
^[[>0;10;1csimon@debian:~$ 0;10;1c
```

**Comment by gurka** [comment]
Note: this works OK with Powershell instead of Windows Terminal. Haven't verified any other terminal emulators, but I'm pretty sure that it works OK in PuTTY as well.

There are few bug tickets in other projects, like https://github.com/microsoft/WSL/issues/5931, but in my scenario it seems Windows Terminal is the culprit - hence the ticket here

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11204 for more discussion.

/dup #11204
