### ISSUE TITLE
Feature Request: Vertical Tabs

### ISSUE THREAD

**Issue by linusic** [microsoft/terminal#12756]
### Feature Request: 
- [ ] Vertical Tabs

> 👆Like `Edge Vertical Tabs`
> In addition, I hope that `Vertical Tabs` can also be used in `FullScreen Mode` (whether or `Terminal` or 😂`Edge`)

> Although Now I'm accustomed to `FullScreen Mode`  and  👉 use `Ctrl`+`~`  to switch tabs

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22vertical+tabs%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #835 for more discussion.

/dup #835

**Comment by linusic** [comment]
Thanks, I see

**Comment by linusic** [comment]
Thanks

> Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22vertical+tabs%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #835 for more discussion.
> 
> /dup #835

Thanks I see!
