### ISSUE TITLE
Prompt before throwing away a user's hotkey changes.

### ISSUE THREAD

**Issue by muchcharles** [microsoft/terminal#12750]
# Description of the new feature/enhancement

Prompt the user before throwing away their hotkey changes.  Right now when editing hotkeys there is an "are you sure?" type prompt on every hotkey change, but once finished if the user closes the settings tab all changes are discarded.  A user could spend a lot of time manually entering in hotkey changes only to have them thrown away.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10627 for more discussion.

/dup #10627
