### ISSUE TITLE
Launching "wsl" from search, or "ubuntu" from the run dialog doesn't launch with profile customisations

### ISSUE THREAD

**Issue by NewtonChutney** [microsoft/terminal#12755]
I don't seem to find a similar issue elsewhere, but do merge this issue with an existing one if there is any..

Whenever I launch WSL by searching from start, or by entering "wsl" or "ubuntu" in the run dialog, windows terminal launches it without the profile customisations. I seem to think this is a supported scenario, as many people would be launching from Win+r as it is very handy..?<br></br>

### **Desired Behaviour:**
Desired behaviour when launching "Ubuntu on Windows" app or the profile from WT:
![Desired behaviour when launching _Ubuntu on Windows_ app or the profile from WT](https://user-images.githubusercontent.com/70827815/160057859-3e820b1e-35b8-4aff-acfd-9ddda8238d55.png)<br></br>

### What is being seen:
What I get when "wsl" or "ubuntu" is launched from win+run dialog:
![what i get when launched from win+run dialog](https://user-images.githubusercontent.com/70827815/160057868-6623fe58-e357-48f2-af99-fcad5adb6b1e.png)

### Steps to reproduce:
1. **Desired:** Opening a new tab after launching Windows terminal or directly launching the "Ubuntu on Windows" app
2. **What I expect to work, but doesn't:**  Launching "wsl" from start search, or from the run dialog, and launching "ubuntu" from the run dialog

### Other Data:
**What device you're running (inc. CPU type, memory, disk, etc.):**
> Intel 8th gen i7, 12 gigs of RAM [HP is the one to blame, this laptop was configured this way when my dad bought it, and  it got passed down to me..🥲]

**What build of Windows your device is running**
> Windows 11 [Version 10.0.22000.588]

**What tools and apps you're using (e.g. VS 2019, VSCode, etc.)**
> VSCode and Docker Desktop for now

**Your Environment**
> Just the default WSL distro from the Store, Ubuntu on Windows 🙃

**Comment by NewtonChutney** [comment]
Same as the WSL launching issue from #12582

But is launching Ubuntu, and not having it profile matched, a problem that will be fixed with the above?

**Comment by zadjii-msft** [comment]
Yea, this looks like /dup #12582 to me. @lhecker can correct me (_when he's back_) if I'm wrong. Fixing #12582 should fix this too.

**Comment by maisondasilva** [comment]
@NewtonChutney The temporary solution for me was to create a desktop shortcut for Ubuntu and so it works

wt -p "Ubuntu"

Icon https://www.iconspedia.com/icon/ubuntu-flat-circle-icon-41194.html

![image](https://user-images.githubusercontent.com/11423362/177809467-09b0b89d-1ccd-43e3-9191-000b7fa59703.png)

**Comment by NewtonChutney** [comment]
@maisondasilva thanks mate!

But I'd rather reserve the precious real estate for other things.. 🥲 😅
I've got tons of icon groups, and usually won't have space for app icons! 😂

And if people have quite a few WSL profiles.. This isn't that elegant of a workaround.. It's gonna be better if the WSL team changes those executables (eg Ubuntu.exe) to point to WT profiles somehow.. 😂

But everything lies in that _"somehow"_.. It's the devs' magic!
