### ISSUE TITLE
Feature Request: Background Image Padding setting option

### ISSUE THREAD

**Issue by Dominik-H** [microsoft/terminal#12771]
# Description of the new feature/enhancement

I propose adding an option to set padding for background image in settings. While "backgroundImageAlignment" is awesome and works fine for basic image placement adding an option for user to pad their image by requested amount of pixels would allow the user to place the image in any spot in the terminal window.

I am NOT proposing removal of backgroundImageAlignment but an extension option to add padding to image position.

# Proposed technical implementation details (optional)

Of course this is up to the implementation team but my proposal is to add parameter similar to the "padding" that positions the text in the terminal.

- Name of the parameter could be "backgroundImagePadding"
- It would accept similar options as mentioned "padding" parameter: "#", "#, #" and "#, #, #, #"
- Default value would be "0, 0, 0, 0"
- When both "backgroundImageAlignment" parameter and new "backgroundImagePadding" are set, the Alignment position would be taken as origin and added to the padding values which would yield new position of the image e.g.: "bottomRight" option is bottom right corner and together with padding of "0, 10, 0, 10" it would calculate position offseting the image by 10 pixels from bottom right corner in both directions.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2620 for more discussion.

/dup #2620
