### ISSUE TITLE
quake mode window doesn't resize when screen width changes in `mstsc` remote desktop

### ISSUE THREAD

**Issue by Fan-iX** [microsoft/terminal#12785]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22581.0

### Other Software

`mstsc.exe` remote desktop

### Steps to reproduce

0. One local PC with two monitors, and one remote PC
1. Connect to the remote PC using `mstsc.exe` (full screen)
2. start `wt` in quake mode in the remote desktop
3. move the `mstsc.exe` window to another monitor and maximize (full screen) it

### Expected Behavior

Quake mode window width adjusted to the new screen width

### Actual Behavior

Quake mode window width doesn't change, even after hiding and re-showing the window

![quake_window](https://user-images.githubusercontent.com/61686936/160635595-e025952d-805d-45da-a87e-4138bfbf7191.png)

monitor information:
`mstsc.exe` window moved form [3000×2000, 200% scale]
to [1920×1200, 100% scale] (the screenshot)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11125 for more discussion.

/dup #11125
