### ISSUE TITLE
Crash on `exit` after previously closing a pane with non-leaf sibling

### ISSUE THREAD

**Issue by peterdn** [microsoft/terminal#1278]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): master
```

# Steps to reproduce

Open terminal and split the main pane vertically. Then split the left-hand pane horizontally. You should now have 3 panes, named A, B, C shown in the configuration and tree structure below:

```none
+---+---+   1: parent
| A |   |   ├── 2: parent
+---+ B |   |   ├── 3: A
| C |   |   |   └── 4: C
+---+---+   └── 5: B
```

Now `exit` pane B, then `exit` either of panes A or C.

# Expected behavior

The second exited pane will close, leaving one pane open.

# Actual behavior

Terminal crashes.

# More information

I believe this is due to a bug in Pane::_CloseChild where close event handlers are not correctly revoked when the remaining child pane is non-leaf. Proposed fix: #1279

**Comment by DHowett-MSFT** [comment]
Hey, thanks for identifying and fixing this bug. This was just submitted to the store with the v0.2.1831.0 servicing release. It may take some time for the store to process it.
