### ISSUE TITLE
Acrylic Effect Not Working

### ISSUE THREAD

**Issue by anishre** [microsoft/terminal#12783]
### Windows Terminal version

1.12.10732.0

### Windows build number

10.0.19044.1620

### Steps to reproduce

- Leave default profile setting as is
- Go to individual settings for CMD and PowerShell
- Change acrylic toggle to on and set transparency from 0 to 70 %.
- Save changes and observe

### Expected Behavior

- Window should have some transparency effect

### Actual Behavior

-No change at all.

- When window background set to desktop background, change is successful.

**Comment by zadjii-msft** [comment]
Have you [read the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#transparency)?

> As a system-wide policy, acrylic is only enabled for the foreground window. So if you activate any other window than the Terminal, the Terminal's acrylic will turn off.
> 
> There are other system policies that control when acrylic is or isn't enabled. For example, if your laptop is in power saver mode, or you're accessing your machine through RDP, then acrylic will be disabled. Before filing a bug, make sure that acrylic works in other apps, like Calculator, or the Start Menu. Furthermore, if the Windows OS setting "Transparency effects" is not turned on (Windows Settings -> Customize -> Colors -> Transparency effects), then acrylic will not take effect.

**Comment by anishre** [comment]
Yeah, the issue I have is with terminal running in the foreground and not showing the acrylic effect. Windows transparency mode is on.

**Comment by zadjii-msft** [comment]
Is your laptop in power saver mode? 

Are you accessing the machine via RDP?

Does acrylic work elsewhere in the OS? (the start menu, Calculator, the Settings app)

(there are other things that affect it as well, those are just the common ones)

**Comment by anishre** [comment]
> Is your laptop in power saver mode?
> No
> Are you accessing the machine via RDP?
> No
> Does acrylic work elsewhere in the OS? (the start menu, Calculator, the Settings app)
> no, i just noticed this.
> (there are other things that affect it as well, those are just the common ones)

**Comment by zadjii-msft** [comment]
> > Does acrylic work elsewhere in the OS? (the start menu, Calculator, the Settings app)
>
> no, i just noticed this.

Well, at least we can be reasonably sure it's not a Terminal issue then! I'd maybe try reporting this in the Feedback Hub - I unfortunately don't know how precisely acrylic works.
