### ISSUE TITLE
Enormous page file usage

### ISSUE THREAD

**Issue by Forinil** [microsoft/terminal#12791]
### Windows Terminal version

1.11.3471.0 and 1.13.10733.0

### Windows build number

10.0.19044.0

### Other Software

PowerShell 7.2.2
Gradle 6.4.1

### Steps to reproduce

I'm using Windows Terminal at work to open several tabs, one of which is always a PowerShell tab in which I run my Gradle builds.

Two days ago I run out of SSD space and checked if I had any huge files on the drive. To my suprise _pagefile.sys_ was over 20 GB in size and when I checked the Resource Monitor, it showed that Windows Terminal has committed over 16 GB of memory.

The next day I used the Resource Monitor to monitor the Terminal's committed memory and it seems every build added several GB.

I installed the Terminal Preview and used it - instead of the stable version - the day after that to see if it has the same problem. It has.

### Expected Behavior

A reasonable amount of committed memory used. Committed memory released after a while - when it's presumably no longer needed.

### Actual Behavior

A huge amount of commit memory (measured in GB) used. Several GB added with every build. No - or virtually no - committed memory ever released.

**Comment by zadjii-msft** [comment]
This seems impossibly bad - Like, I don't know how we'd possibly commit that much memory before just hitting an out of memory error.

Is the committed memory attributed to `windowsterminal.exe`, or is it possible there's some other process in the tree that's holding that memory? 

I know we have a guide somewhere for debugging what's actually allocating memory. Lemme see if I can dig it up.

**Comment by Forinil** [comment]
All I can tell you at the moment is that if I use ConEmu instead of Windows Terminal, leaving everything else the same, I don't see any processes that use that amount of memory.

Let me know if there's anything more I can do.

**Comment by DHowett** [comment]
QQ: What graphics card do you have?

**Comment by Forinil** [comment]
@DHowett Intel UHD Graphics 620 and AMD Radeon 520. I'm using Dell Inspiron 3576 laptop.

**Comment by zadjii-msft** [comment]
🤷

Weird. We'll keep our eyes out for other reports, but very glad the issue seems to have gone away!
