### ISSUE TITLE
Color goes default while printring tree command

### ISSUE THREAD

**Issue by 2p31-1** [microsoft/terminal#12797]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000556

### Other Software

cmd on wt

### Steps to reproduce

1. color c
2. tree c:\
3. press F11 to toggle fullscreen while printing tree.
4. When it goes to window screen from fullscreen, the default color comes back.

### Expected Behavior

No color change while toggling fullscreen.

### Actual Behavior

 When it goes to window screen from fullscreen, the default color comes back.

**Comment by zadjii-msft** [comment]
Hey wadda ya know, we just fixed this! /dup #12567, /dup #32.

#12637 should be in the _next_ servicing update to 1.12/1.13
