### ISSUE TITLE
Invisible command output in second monitor scaled differently

### ISSUE THREAD

**Issue by servel333** [microsoft/terminal#12793]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1526

### Steps to reproduce

- Have a computer with two different scaling factors (for example, 4k laptop and old monitor)
  - My setup is a Microsoft Surface Book 3 with an old monitor connected through a hub and adapter
- Enable WSL2
- Install Ubuntu in WSL2
- Open Windows Terminal
- Move the terminal window to the lower-ratio monitor
- try `ls` and other commands a few times
  - It's possible there must be colored output for this to reproduce. I often use `git status` with colors enabled and see this issue.

### Expected Behavior

Command output (stdout) is visible and colored as expected.

### Actual Behavior

Command output (stdout) is sometimes invisible.

### Some additional notes

- Selecting the invisible space with the mouse makes the text visible one line at a time
- Moving the Windows Terminal window across the monitor boundary causes the text to become visible.
- Changing the scaling factor on the external monitor to different than back will temporarily resolve this issue.
- Resizing the Windows Terminal window (click and drag edge) will temporarily resolve this issue.
- The issue returns if the Windows Terminal window is dragged across monitor boundaries and more output is generated.
- See also [This superuser.com Question](https://superuser.com/questions/1713554/how-do-i-fix-command-output-in-terminal-is-invisible-on-external-monitor) for details and screenshots. Also not comments under the main question.
- It's possible this is related to https://github.com/microsoft/terminal/issues/6210

**Comment by zadjii-msft** [comment]
This might be better in 1.12 or 1.13, there was a weird scaling issue that was solved in the latest release. I'd doubt it, I think that had more to do with the resizing of the swapchainpanel itself (not invalidating), but worth a shot to check out. 

#11317

Ah shiz, we didn't backport that one.

**Comment by servel333** [comment]
I'll see if I can grab a newer version and test, if one is publicly available.

It's definitely a weird bug. I wouldn't expect screen scaling to matter to the terminal.

**Comment by DHowett** [comment]
The fix is unfortunately not yet out -- however, screen scaling matters to the Terminal because it's gotta get that good good grid of text into pixels _somehow_ :smile:

**Comment by servel333** [comment]
I guess I assumed the operating system would handle application scaling?

Regardless, when the new version comes out, I will test it. I can't guarantee I will remember, so if you happen to, your welcome to @mention me here again.

**Comment by jessey-git** [comment]
There is also #11214 that is still active that deals with moving between monitors at different scale (and when remoting into other machines with different resolutions)

**Comment by zadjii-msft** [comment]
Yea, this does look just like #11214. Let's combine discussion in there.

/dup #11214
