### ISSUE TITLE
Large spacing between characters and bottom border in focus mode

### ISSUE THREAD

**Issue by xQmQ** [microsoft/terminal#12804]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

Windows terminal in focus mode

OS: Arch Linux on Windows 10 x86_64
Kernel: 5.10.102.1-microsoft-standard-WSL2

vim 8.2
tmux
ranger 1.9.3

### Steps to reproduce

Set the startup mode to focus mode and compare the focus mode with the default mode

### Expected Behavior

This doesn't interfere with use, but it is very hard for OCD sufferers. I wish the focus mode had the same interval size as the default mode

### Actual Behavior

When opening some programs in focus mode, the bottom border of the terminal has a larger distance from the characters

Take tmux status bar as an example, you can see that the status bar has a larger distance from the bottom border (the distance between the status bar and the left and right borders is normal); in default mode, it is normal
![1](https://user-images.githubusercontent.com/56010105/161204519-e57ac093-56a3-40af-a0a2-3eb94b5d9a06.png)

Similarly, take vim and ranger for example, this problem exists, but it is normal in default mode
![4](https://user-images.githubusercontent.com/56010105/161204595-2df2fef9-a48a-49ef-a211-329bd7a5ea06.png)
![2-false](https://user-images.githubusercontent.com/56010105/161204619-231f726a-f1ae-4817-83ae-abe3da812c78.png)

I had changed the size of the window border spacing, but it didn't work. Still using tmux as an example, in focus mode, changing the value of the window border spacing changes the distance between the status bar and the left and right borders, but there is still a large distance between the status bar and the lower border
![5](https://user-images.githubusercontent.com/56010105/161205402-4d124682-cc18-40e2-9b05-5b774a95eee7.png)
![6](https://user-images.githubusercontent.com/56010105/161205419-76a40fdf-ca26-4426-a7ba-34d9a97b845c.png)

**Comment by zadjii-msft** [comment]
This looks like a riff on #13155, but with focus mode instead. I suppose focus mode doesn't cause the window to snap to the character boundaries immediately, so entering it would cause the gutters to appear.

**Comment by xQmQ** [comment]
> This looks like a riff on #13155, but with focus mode instead. I suppose focus mode doesn't cause the window to snap to the character boundaries immediately, so entering it would cause the gutters to appear.

I do not know much about this, but recently in the use of the process, this problem has rarely appeared

Thank you!
