### ISSUE TITLE
Generated profiles of "Developer cmd/pwsh for VS" have different guid for even same distribution

### ISSUE THREAD

**Issue by hsupu** [microsoft/terminal#12807]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.19044.0 or 10.0.22000.0

### Steps to reproduce

I want to sync the settings of wt between PCs, hit this issue.

I installed VS 2022 Community and VSSetup (pwsh module). `Get-VSSetupInstance` reported different `InstanceId`.

I read the code and found wt uses VS InstanceId to generate guid.

### Expected Behavior

Either VS InstanceId becomes identical for same distribution or WT generates profiles uses a independent way.

### Actual Behavior

WT generates profiles from VS InstanceId which is different between PCs.

**Comment by hsupu** [comment]
Ohh.. I'm sorry for not checking the discussions first. I searched issues and found no related so opened this one.

Yes I want a roaming settings, but I think another issue here is that there is NO chance (inline json or another file) to define custom guid mapping. I found `states.json` just marked generated one.

**Comment by zadjii-msft** [comment]
Oh don't worry about it. We're only jsut dipping our feet into discussions, so not sure we've even got the habit down yet 😛 

>  I think another issue here is that there is NO chance (inline json or another file) to define custom guid mapping

Sorry, could you elaborate? Like, do you want to be able to mark one profile as inheriting the settings from another maybe? I think we've got something on the backlog like that, but I want to be sure that's what you mean

**Comment by hsupu** [comment]
For example, we have at least two predefined guid (hardcoded in code)

```json
{
    "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "name": "Command Prompt"
},
{
    "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "name": "Windows PowerShell",
    "hidden": true
},
```

I want to add an alias to point one of them, as a solution for this issue, but not ideally.

```js
"guid-mapping": {
    "{94c94f69-f7a9-5065-9368-56efcd5bd9e6}": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
}

{
    "guid": "{94c94f69-f7a9-5065-9368-56efcd5bd9e6}",
    "name": "Windows PowerShell (2)",
    "hidden": false // extend the idea, override settings
}
```

VS Developer profiles aren't hardcoded, but almost same.

**Comment by zadjii-msft** [comment]
Okay yea, that sounds just like /dup #3818. Thanks!
