### ISSUE TITLE
ConPTY VS Code Issue - ANSI escape sequences don't display correctly

### ISSUE THREAD

**Issue by rewrking** [microsoft/terminal#12806]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19041.1415

### Other Software

VS Code 1.66.0

### Steps to reproduce

1. Open VS Code and set `"terminal.integrated.minimumContrastRatio": 1`:
2. Get this file: https://gist.github.com/rewrking/f797bd19e9ecc44fa1c646b3f7b795c0

Steps for Git Bash inside of VS Code:

4. Run `cat print_term.txt` where the file in step 3 was saved

Steps for Powershell inside of VS Code:

4. Run `Get-Content -Path .\print_term.txt` where the file in step 3 was saved

### Expected Behavior

All terminal colors and most ansi sequences would be expected, but this is not the case.

### Actual Behavior

Right now, my VS Code and Windows Terminal setup use the same color scheme. Both Git Bash and Powershell display the same way in each. In order to test this correctly, all 16 colors need to be unique.

This is what displays in VS Code on Windows:

![ansi_vscode](https://user-images.githubusercontent.com/4885461/161136824-b49f1d8e-218b-4827-870f-af953cc390d0.png)

This is what displays in Windows Terminal:

![ansi_windows_terminal](https://user-images.githubusercontent.com/4885461/161136874-33c45530-5394-4e5f-92cd-9fdae033590c.png)

I originally opened up this issue with the vscode team, but they closed the issue and told me to take it up with you folks, due to the problem being related to conPTY:
https://github.com/microsoft/vscode/issues/146474

Let me know if there's a way to fix this. Thanks.

**Comment by rewrking** [comment]
Is that an insiders version of Windows 10? Mine is supposedly up to date.

**Comment by zadjii-msft** [comment]
Nah, 22000+ builds are all Windows 11

**Comment by rewrking** [comment]
Hahaha understood. Ugh. Thanks.

**Comment by rewrking** [comment]
Okay, so one more thing: What does Windows Terminal do differently? Link those conhost changes as a static library somewhere?

**Comment by rewrking** [comment]
> # HERE BE DRAGONS


Yep. This worked (also made sure `ConhostV1.dll` was copied just in case). Thanks!

**Comment by zadjii-msft** [comment]
> Okay, so one more thing: What does Windows Terminal do differently? Does it link those conhost changes from a static library during its build or something?

Sorta - Terminal actually just includes a whole conhost in its package, and doesn't directly call the conpty apis - it calls a slightly different version that calls into the conhost shipped in the package rather than the one in the OS.

**Comment by Mingun** [comment]
> ConPTY is actually just something that's built into `conhost.exe` itself.
> 
> You might be able to copy-paste a conhost from a Windows 11 machine onto a Windows 10 one, and it _probably_ would work fine. That being said, there was another thread just this week about someone who was tying to move a conhost.exe between machines and experiencing quite a bit of difficulty. I wouldn't recommend it. If you try replacing your `c:\windows\system32\conhost.exe` and it DOESNT work, then you'll be totally unable to run _any commandline applications_. Big ol
> # HERE BE DRAGONS

Whats happens if I copy `conhost.exe` from Windows 11 to Windows 7 and it will not work? Will I able to return Windows 7 conhost.exe back from backup? Or system will be broken and I cannot run any application?

**Comment by DHowett** [comment]
> Whats happens if I copy conhost.exe from Windows 11 to Windows 7 and it will not work? 

It will not work, and you risk breaking your system. I wouldn't even try it. The version of conhost on Windows 7 uses a different communication protocol.

We used to verify conhost.exe down to Windows 8.1. That was the first version that used the new communication protocol.

It technically still works, but there are some minor DLL incompatibilities that would need to be worked around.
