### ISSUE TITLE
Please add Portuguese Portugal to Windows Terminal

### ISSUE THREAD

**Issue by moonlightz** [microsoft/terminal#12809]
In the past, I complained about this. Either selecting Portuguese Brazillian or Portuguese Portugal, it would default to the first even if "System Standard" is selected. My system is pt-PT locale and I do not wish to see brazillian anywhere. Since Windows Terminal is out, I switched to English.
I have today installed build 22581 and gone to check Windows Store apps and launched Windows Terminal and .... yack brazillian.
![ps](https://user-images.githubusercontent.com/34037569/161339778-120aeff5-6beb-4aa4-83bc-d5bb03207e63.png)

Either add the language or lead me to the file service for translation.

**Comment by zadjii-msft** [comment]
You don't need to file additional threads for the same topic, we can continue discussing in the original. /dup #10667
