### ISSUE TITLE
Add the ability to create profile groups

### ISSUE THREAD

**Issue by EranGon** [microsoft/terminal#12814]
# Description of the new feature/enhancement
I have multiple repos on my computer, and I'm creating a dedicated profile for each one - allowing me to distinguish the repo I'm working on by the tab's title and background color.
Since I have many repos, the new tab drop down is getting way too long - it would be amazing to be able to group them like I do in my browser's favorites

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
