### ISSUE TITLE
Fonts getting cut off/jaggy when Windows custom scaling is turned on

### ISSUE THREAD

**Issue by saihv** [microsoft/terminal#12810]
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Set custom scaling in Windows display settings to a non-standard number (between 100-125)

### Expected Behavior

Fonts to scale accordingly within Windows Terminal

### Actual Behavior

Font letters are getting cut off either vertically or horizontally when custom scaling is on, or sometimes they get rendered jaggily.

100 percent (standard) scaling, WSL (Ubuntu), Font - Consolas: 
![100percent](https://user-images.githubusercontent.com/2274262/161393676-86b36c20-f748-4ae1-83ca-aaa165b4665e.png)

125 percent (standard) scaling, WSL (Ubuntu), Font - Consolas:
![125percent](https://user-images.githubusercontent.com/2274262/161393683-555d5a39-137f-41ec-89a9-7195236081fa.png)

110 percent (custom) scaling, WSL (Ubuntu), Font - Consolas:
![110percent](https://user-images.githubusercontent.com/2274262/161393698-41ea3ff0-18b6-41df-9788-38d3f469b7aa.png)
(notice the m's, l's and o's in "command")

110 percent (custom) scaling, WSL (Ubuntu), Font - Cascadia Cove Nerd: 
![110_cascadia](https://user-images.githubusercontent.com/2274262/161393714-f89e88ee-7605-40d6-8279-b1ce94c7fbd1.png)

110 percent (custom) scaling, Powershell, Font - Cascadia Cove Nerd: 
![110_powershell](https://user-images.githubusercontent.com/2274262/161393725-b5c00175-1068-4e6b-91a1-da1208b4a238.png)

110 percent, another example:

![image](https://user-images.githubusercontent.com/2274262/161394161-d4436729-fe36-4368-9f38-845050f25e79.png)

Issue persists with both grayscale and Cleartype antialiasing, with and without AltGr antialiasing.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+custom+scaling) when filing new issues. This is already being tracked by another issue on our repo - please refer to #4591 for more discussion.

/dup #4591
