### ISSUE TITLE
Terminal freeze after typing

### ISSUE THREAD

**Issue by SkyEmie** [microsoft/terminal#12813]
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22581.200

### Steps to reproduce

- Start Terminal. (cmd or powershell) You can interact with it (move windows, create new tab, go to settings)
- Start to type. Terminal is now freeze, you cant interact with it
- alt+tab
- You can now intaract with it
- Type again in the console. Terminal is again stuck

### Expected Behavior

No gui freeze

### Actual Behavior

Terminal freeze after typing

**Comment by K900** [comment]
Might be related to Windows version in some way? The same Terminal build works fine on my desktop with 22000 stable, but not laptop with 22581 dev.

**Comment by K900** [comment]
Update: also reproduces on Terminal 1.13 preview.

**Comment by agentmerlot1412** [comment]
Same issue on both Terminal and Terminal Preview on 22581.200

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #12746 for more discussion.

/dup #12746
