### ISSUE TITLE
Terminal writes over previous text when it reaches bottom

### ISSUE THREAD

**Issue by spazer5** [microsoft/terminal#12817]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1586

### Other Software

Ruby 3.1.1
Installed via [RubyInstaller](https://rubyinstaller.org/downloads/)

### Steps to reproduce

1. Launch ruby interperter via `irb`
2. Start typing text until you reach the bottom of the view port
3. WT will wind back to the top and start printing over previous output in a very buggy manner.

### Expected Behavior

Able to scroll through previous output and maintain history.

### Actual Behavior

WT will start printing over previous output in a very buggy manner.

WT seems to be unable to create a scrolling history larger than the window's height.

Behavior present on both PowerShell and CMD on WT, however regular CMD works just fine.

Here's a video: [https://imgur.com/a/lKWMHMX](https://imgur.com/a/lKWMHMX)

**Comment by zadjii-msft** [comment]
Looks like we saw this once before in #12283, which then got moved upstream to https://github.com/ruby/irb/issues/343, where the resolution was 

> Reline 0.3.0 contains wrong code that misidentifies the cursor position. Would you try reline 0.3.1?
> [ruby/reline](https://github.com/ruby/reline)
> 
> ```
> gem outdated
> gem update reline
> ```

/dup #12283
/dup https://github.com/ruby/irb/issues/343
