### ISSUE TITLE
If "Automatically hide scroll bars in Windows" is Off, the Settings UI is very hard to use when collapsed

### ISSUE THREAD

**Issue by ameltzerMSFT** [microsoft/terminal#12824]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.10941.0

### Steps to reproduce

In Settings, change "Automatically hide scroll bars in Windows" to "Off". Open the Settings UI in Windows Terminal.

### Expected Behavior

Collapsed settings area should not be largely invisible due to the scrollbar using all the space

### Actual Behavior

This:
![image](https://user-images.githubusercontent.com/26661268/161631459-350884f0-0a0d-4cfd-95f3-c33119a45241.png)

**Comment by ameltzerMSFT** [comment]
This may be related to #10664, but this problem is occurring on a newer build than the one that purports to have these fixes (#12296)

**Comment by ameltzerMSFT** [comment]
For reference, this same UX with "Automatically hide scroll bars in Windows" set to "On" (and scrolling has been initiated):
![image](https://user-images.githubusercontent.com/26661268/161632043-df0be0cf-b50f-4c1f-8ed0-9fa072cce5fb.png)

**Comment by zadjii-msft** [comment]
This is actually tracked in #8894. That thread has a little more context, as well as ideas on how we might be able to fix this. Thanks!

/dup #8894

**Comment by ameltzerMSFT** [comment]
@zadjii-msft thanks -- I figured there _had_ to be a bug on this but I wasn't find it when searching.
