### ISSUE TITLE
Settings for notification on window close / system shutdown

### ISSUE THREAD

**Issue by H1MSK** [microsoft/terminal#12827]
# Description of the new feature/enhancement

I wish there be a reminder mechanism on a tab so that when it's about to close, it would require the user to confirm.

Yesterday I was training a network in the background, and at the end of the day, I totally forgot it and closed the computer without any hesitation. Today I finally realized it, only to find that it didn't reach the first checkpoint, and nothing has been saved. As a result, I have to rerun the training from the begining... :cry:

# Proposed technical implementation details (optional)

Maybe a checkbox or so in the tab menu would help. When I check it, this tab will stop me from closing it or shutting down the computer until I uncheck it.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6549 for more discussion.

/dup #6549
