### ISSUE TITLE
Windows terminal pane is non-responsive after long idle git log 

### ISSUE THREAD

**Issue by scaramushe** [microsoft/terminal#12828]
### Windows Terminal version

 1.13.10734.0

### Windows build number

10.0.22000.556

### Other Software

git - git version 2.35.0.windows.1
profile is powershell, PSVersion  5.1.22000.282 

### Steps to reproduce

Working via RDP, 
Opening a terminal pane with git repo,
Run git log and leave it "alive"
Return after a few hours and try to send any keyboard command in this pane

### Expected Behavior

Response to the keyboard command

### Actual Behavior

nothing - no keyboard command is received. Then pane next to it works fine.
Also mouse scrolling works as expected. Only keyboard input is the issue.
Recovery - Alt+Pause to exit the state
The issue is seen occasionally, not easily reproduced

After hitting this once, and recovering - got issue https://github.com/PowerShell/PSReadLine/issues/3260

**Comment by zadjii-msft** [comment]
Does this happen if you run the same git log command with a different shell? Command Prompt, or even a 7.x version of `pwsh` instead/?

This gives me vibes of #13386 and #12607, but at least in the latter case, there's not usually a way to break out of it
