### ISSUE TITLE
PowerShell module cannot be loaded unless the execution policy is less restrictive

### ISSUE THREAD

**Issue by Prabhakar-17** [microsoft/terminal#1282]
README.md

By default running scripts (in this case: Import-Module .\tools\OpenConsole.psm1) are disabled. In order to run the script we have to set the execution policy using  `Set-ExecutionPolicy RemoteSigned command`.
It would be nice to have this thing documented as well.
Happy to create a PR for this, it's a small thing but can save time of new contributors joining the project :)

**Comment by zadjii-msft** [comment]
@adiviness may be interested in this

**Comment by DHowett-MSFT** [comment]
Thanks for the report!
It's generally expected that developers who want to do powershell things will have set their execution policies to something more amenable to local development. We'll consider documenting that, but there's a bunch of "early start" things that our guides shouldn't have to cover.

**Comment by adiviness** [comment]
Also, we already require that developer mode is enabled in the settings app, one of the default settings it'll change is the powershell execution policy.
