### ISSUE TITLE
Alt+w doesn't map correctly to the action in settings.json

### ISSUE THREAD

**Issue by fransoaardi** [microsoft/terminal#12836]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1586

### Steps to reproduce

Most of the parts are omitted. 
When setting like below, any commands with `alt+w` doesn't work. 

```json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": "closeTab",
            "keys": "alt+w"
        }
    ]
}
```

### Expected Behavior

Expect keymap actions to be mapped correctly and work as expected.
When pressing `alt+w` it should close the tab on the terminal.

### Actual Behavior

`alt+w` doesn't work. Mapping `alt+w` to other commands also doesn't work. However, setting `ctrl+w` to `closeTab` just works.

**Comment by zadjii-msft** [comment]
Any chance you're using any sort of IME? I just tried adding this in the SUI locally and it seemed to work. Does <kbd>alt+{any other key}</kbd> work either?

**Comment by fransoaardi** [comment]
@zadjii-msft Hi, I'm mainly using Korean Microsoft IME, I also use English(United States) US Keyboard, but both don't work. 
My keyboard layout is QWERTY. It's weird that alt+{any other key} works, but not `alt + w`.

**Comment by fransoaardi** [comment]
@zadjii-msft Hi, gentle ping. Any updates?

**Comment by zadjii-msft** [comment]
Sorry, I have no idea. I can't get this to repro, even with the Korean IME installed. At this point I'd suspect that some other app is hooking that key, but which one? I'd have no idea. Does `alt+w` work in any other app?

At this point all I've got is internet searches to help you - any chance you have "QQ" installed? Some random forum post from 2014 mentioned that.

**Comment by fransoaardi** [comment]
@zadjii-msft 
I tested again on my local and it now suddenly works. It's really weird. I haven't installed "QQ", FYI.
I think it is resolved now. Thanks for your help. 

Closing.
