### ISSUE TITLE
strange window behavior

### ISSUE THREAD

**Issue by DemonXD** [microsoft/terminal#12834]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19042.1586

### Steps to reproduce

1. open the windows terminal preview
2. paste the code into terminal
3. things happened

### Expected Behavior

window behavior normally

### Actual Behavior

half window is gray
![tm-err](https://user-images.githubusercontent.com/12723424/161878855-e9f9950a-6427-4427-bb80-3824517702ee.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #12775 for more discussion.

/dup #12775
