### ISSUE TITLE
Cannot rename/delete the folder that the Terminal was initially opened in

### ISSUE THREAD

**Issue by mariusgreuel** [microsoft/terminal#12831]
### Windows Terminal version

1.12.10732.0

### Windows build number

10.0.19044.1620

### Steps to reproduce

- Use Windows Explorer to create a new empty folder.
- Open a terminal by typing `wt` in the address bar of Windows Explorer (here inside D:\test).
```
Microsoft Windows [Version 10.0.19044.1620]
(c) Microsoft Corporation. All rights reserved.

D:\test>cd ..

D:\>rmdir test
The process cannot access the file because it is being used by another process.
```

### Expected Behavior

When I do the same thing using `cmd.exe`, I can delete the folder:

```
Microsoft Windows [Version 10.0.19044.1620]
(c) Microsoft Corporation. All rights reserved.

D:\test>cd ..

D:\>rmdir test

D:\>
```

### Actual Behavior

It seems that Windows Terminal permanently keeps an open handle to the **initial** directory the terminal was opened in. This prevents one from renaming/deleting/... the directory from within the terminal. My expectation is that the terminal only has an open handle to the directory it is currently at.

Process Explorer confirms that after changing directories, there are still two open handles in `WindowsTerminal.exe` and `OpenConsole.exe`.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5506 for more discussion.

/dup #5506
