### ISSUE TITLE
profiles.defaults should be default values, not override values, or make a new section for overridable defaults

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#12842]
The current implementation of Terminal applies the settings found in profiles.default to all profiles, regardless of whether the individual profile has its own value for any of those settings.  Unfortunately, this behavior is unexpected and confusing.  The only reasoning I can come up with is that profiles.default was meant to override settings from automatic profiles that aren't defined in settings.json at all.  For profiles defined in settings.json, the expectation for profiles.default would be that any setting not defined in an individual profile would get its value from profiles.default, but if a setting *is* provided in the individual profile the corresponding setting in profiles.default would be ignored.

Please change Terminal so profiles.default behaves in an expected way, providing default values and not override values.  If an overriding section is really needed, then create a new profiles.overrides section for this.  With the current implementation, it is not possible to define several profiles and have most of them use a common value for some settings, while one or two exception profiles do something different without copying that setting to every individual profile.  profiles.default has very little value when it forces itself onto every profile.
If profiles.default can't change for some reason, then consider creating a new section (maybe profiles.fallback) for overridable defaults or fallback values that individual profiles can override if they provide a value for that setting in the profile.

**Comment by zadjii-msft** [comment]
What version are you on? Could you share a settings snippet that repros what you're seeing?

In general, settings from `profiles.defaults` should override ones from dynamic profiles (e.g. WSL distros) and fragments (like, customizations that Canonical does to their WSL distro), but not ones from the rest of your settings file (the rest of the profiles in `profiles.list`)

**Comment by DHowett** [comment]
Agree on the above^
The thing you've described as the expected behavior _is how `profiles.defaults` works_:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/189190/162022748-2b6c1bbd-54fd-4a1d-bd9c-31436ab27505.png">

**Comment by DJackman123** [comment]
Is that true for all settings?  It sure doesn't seem to be how commandLine behaves.

**Comment by DHowett** [comment]
Settings are case-sensitive; are you overriding `commandline` with `commandLine`?

<img width="742" alt="image" src="https://user-images.githubusercontent.com/189190/162023340-ee6b116d-6642-4d56-8302-95068e3ef063.png">

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/162023304-9efedb5e-33c0-4488-9b45-f96c655e309d.png)


did you set `commandline` or `commandLine` (with a capital `L`)?

**Comment by DJackman123** [comment]
No, that was just a typo in this issue.  My settings are correct.
Now join me on the path to weirdness...
Did some experimentation with this and found that it isn't working for me because I am referencing cmd.exe and powershell.exe without a path (since they are in the system path).  If I change the commandline value to include the path, then it works.  It doesn't matter if the commandline value under defaults has a path or not.

This profile definition will use pwsh.exe for both profiles, but if you switch to the commented-out commandline values, it will work.
```
    "profiles": 
    {
        "defaults":
        {
            "commandline": "pwsh.exe"
        },
        "list": 
        [
            {
                // "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "commandline": "powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                // "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "commandline": "cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            }
     }
```

So this is sounding more like a bug to me.

**Comment by DHowett** [comment]
Frick. I might have been the killer -- through @zadjii-msft's hands. https://github.com/microsoft/terminal/pull/12149/files/ba37cd0259bff7585eae1b1161657750d4629de8#diff-00c4cab1589ce4b52be3a6d069d917bcf01e6983ecc312f0befaa1c6cd6f6efc

**Comment by DJackman123** [comment]
oh, you were trying to be clever?  That always gets me into trouble...

**Comment by DHowett** [comment]
Thanks for catching this, @DJackman123!
