### ISSUE TITLE
Selfhosting machine

### ISSUE THREAD

**Issue by SreeramSathya2014** [microsoft/terminal#12854]
Welcome to my issue!
## The selfhosting machine
If you change the build number using the Registry Editor, then you will _selfhost_ builds.
<br/>
_What_ build number would you want?
- [ ] Recommended: 22601
- [ ] Nickel builds at Microsoft.UI.Xaml Issue: 22596, 22574
- [ ] The only build that is on the conhost on the closed issue: 22590

**Comment by SreeramSathya2014** [comment]
You are grumpy at closing!

**Comment by zadjii-msft** [comment]
What? I honestly have no idea what you're asking here. If you can clarify, we can reopen. You also don't need to keep filing multiple issues for what seems to be the same topic of discussion. 

Just changing the build number in the registry isn't going to actually change anything about the actual binaries you're running. I would highly recommend not doing that.

**Comment by SreeramSathya2014** [comment]
No, you stop CLOSING!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SreeramSathya2014** [comment]
I can _clarify_ it.

**Comment by SreeramSathya2014** [comment]
I must create software from Visual Studio 2022, and you will _selfhost_ the builds.

**Comment by SreeramSathya2014** [comment]
> What? I honestly have no idea what you're asking here. If you can clarify, we can reopen. You also don't need to keep filing multiple issues for what seems to be the same topic of discussion.
> 
> Just changing the build number in the registry isn't going to actually change anything about the actual binaries you're running. I would highly recommend not doing that.

I must create Microsoft software from **Visual Studio 2022**, and you will _selfhost_ the builds.
