### ISSUE TITLE
"startupActions":  with quake mode are not behaving correctly 

### ISSUE THREAD

**Issue by mullcom** [microsoft/terminal#12858]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19044.1586]

### Steps to reproduce

Run command in a sinel terminal
wt -w _quake ;sp -H;sp;sp 

Then test add this now to settings json file
"startupActions": "wt -w _quake sp -H;sp;sp", 

### Expected Behavior

All sp i add in startupActions wt command  should release on quake mode window.

### Actual Behavior

i have try to get several sp in but only manage get one sp in quake mode the rest adds to startup terminal.

**Comment by zadjii-msft** [comment]
I don't think `wt -w` is supported in `startupActions` _at all_... Hmm.

**Comment by mullcom** [comment]
it working with two SP so but failing when i add more. yast test it for your self and you find out. 

[zadjii-msft](https://github.com/zadjii-msft) commented [on Jul 26, 2021](https://github.com/microsoft/terminal/issues/10796#issuecomment-886814545)
At the moment, not really.

You could do something like wt -w _quake -p {your profile name} - that'll launch the Terminal into quake mode with the profile of your choice.
You could always rebind quakeMode to a generic [globalSummon](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands) action. That'd let you just summon any Terminal window, not just the quake one.
Otherwise, you could wait for https://github.com/microsoft/terminal/issues/9992 to be able to change the defaultProfile of the _quake window separately from the normal default

**Comment by zadjii-msft** [comment]
Okay I see what's going on here. 

When you put `wt -w _quake sp ; sp ; sp` into startup actions, here's what happens:

* the terminal parses this into three subcommands: [`wt -w _quake sp`, `sp`, `sp`]
* The first one doesn't parse as an action. `wt` isnt a subcommand, so we treat it as a commandline. We run a tab with the commandline `wt -w _quake sp`. 
  * THIS CREATES A NEW WINDOW, the quake window, with a commandline of `sp`
  * The quake window defaults to creating a tab. Then it processes the `sp`, splitting the pane.
* The original terminal window then parses a `sp`, and creates a new split for this `sp`.
* The original terminal window then parses a `sp`, and creates a new split for this `sp`.

So, you end up with two terminal windows, a `_quake` window and a normal one, each with two panes. 


Putting `-w` in the `startupActions` is definitely _not_ recommended. What I was talking about above was running `wt -w _quake sp ; sp ; sp` from like, the run dialog, or a shortcut, or another Terminal window. Putting the above into `startupActions` will cause the \_quake window to create a new split each and every launch, which would be weird.
