### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jewsh-S** [microsoft/terminal#1285]
# Summary of the new feature/enhancement

Need to be able to search within the terminal window.  When using bash inside of windows terminal, I am unable to search for a text string inside of the output windo.
# Proposed technical implementation details (optional)

I want to be able to press something like ctrl+f and be prompted for a search string.  I should type in a string and press a "search" button that will search for the string within the output text area and bring me to the next found instance.

**Comment by DHowett-MSFT** [comment]
Thanks! This is a duplicate of #605. Please make sure you search for existing feature requests before filing a new one!

**Comment by DHowett-MSFT** [comment]
Also, please make sure you fill out the _title_ field.

**Comment by Jewsh-S** [comment]
I actually did search for it and for some reason I didn't see it there.  I appreciate the quick response and thanks for doing so much on this project.  I am loving it so far!  Windows has needed this for so long and this has been the only thing keeping me on MacOS is the lack of a decent terminal in windows.

Josh

________________________________
