### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by Alan-chenhx** [microsoft/terminal#1286]
![image](https://user-images.githubusercontent.com/34334055/59558933-78705080-902f-11e9-8860-7b28d247cf08.png)
The terminal is not displaying and can  figure out why

**Comment by DHowett-MSFT** [comment]
@Alan-chenhx, what architecture are you building and running from Visual Studio?

**Comment by Alan-chenhx** [comment]
x86 and release from vs2019

**Comment by DHowett-MSFT** [comment]
If you are on a 64-bit machine, you must build and run the 64-bit version of Windows Terminal.
