### ISSUE TITLE
"New tab..." iterable command should iterate over all profiles (not just active ones)

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#12864]
### Windows Terminal version

1.14.892.0

### Windows build number

10.0.22596.0

### Steps to reproduce

1. hide some profiles from the dropdown using `"hidden": "true"` (or Settings UI)
2. Open the command palette
3. Invoke the "New tab..." iterable command

### Expected Behavior

The hidden profiles should be in the list.

### Actual Behavior

The hidden profiles are _omitted_ from the list

**Comment by carlos-zamora** [comment]
I think the change would be fairly simple. We would just need to pass `CascadiaSettings::_allProfiles` into `Command::ExpandCommands()` (as opposed to `CascadiaSettings::_activeProfiles`).

**Comment by DHowett** [comment]
I dunno about this one -- I just added an iterable to my _root command palette_ that goes over profiles as well, and I sure would be surprised if hidden ones popped up.

**Comment by carlos-zamora** [comment]
Yeah, the part I'm conflicted on is this: what does it mean for a profile to be "hidden"? In SUI, we say "Hide profile from dropdown", so that means hiding it should still make it appear in the command palette, right? (granted, historically we've just used "hidden" as a way to fake-delete profiles from SUI).

**Comment by DHowett** [comment]
This one requires discussion rather than triage!

**Comment by DHowett** [comment]
FYI, some developers use fragment extensions to customize how their applications are displayed _without_ adding a profile to the list by using `hidden: true`. It would be more surprising IMO if those ones showed up, but they're not different from user-hidden profiles.

**Comment by lhecker** [comment]
Long-term we'd like to treat hidden profiles as if they were deleted, because hidden used to be a workaround to "delete" generated profiles. In the future we'd additionally prefer if generated profiles don't get added to the visible list of profiles anymore by default. Instead users have to explicitly add them in the settings.
