### ISSUE TITLE
Cut-Off Text Display Area

### ISSUE THREAD

**Issue by numericaseth** [microsoft/terminal#12868]
### Windows Terminal version

1.12.10733.0, 1.13.10734.0

### Windows build number

10.0.22000.593

### Other Software

Command Prompt (cmd)

### Steps to reproduce

Thanks for all the work on Terminal.

I had previously been seeing the text display area scaling problem in issue #11317. It seems like it's gotten better, but I found a repeatable way to trigger it today with the newest store versions (1.12 and 1.13).

Let me know if you need more information.

This is my setup:
Laptop display with 3840x2160 resolution, scale = 250% (physically located on the left)
Monitor 1 with 3840x2160 resolution, scale = 150% (middle)
Monitor 2 with 3840x2160 resolution, scale = 150% (right)

Terminal set to open on laptop screen
Default profile = Command Prompt
Consolas font @ size = 11

1. Open Terminal
2. Do a "dir" command -- the directory display fills the window
3. Move the window from the laptop screen to the middle monitor -- the window changes scale without distortion
4. Resize the window by dragging the bottom right corner down and to the right a bit
5. Move the window back to the laptop screen -- when it changes scale again, the bottom part of the text area goes missing (about 1/3)
6. Resizing the window vertically restores the text

### Expected Behavior

No missing text on display scale changes.

### Actual Behavior

Part of the text area in the window disappears.

**Comment by DHowett** [comment]
I think this might have been fixed in #12749, which is slated for release in 1.12.1098 and 1.13.1098. If you're in the Insider program on the Dev channel, you should be receiving that build soon!

**Comment by numericaseth** [comment]
Ok, thanks -- I'll look for them and try it again.

**Comment by DHowett** [comment]
If you want to give it a shot, I just uploaded 1.12.1098 for somebody else -- it's the `msixbundle` inside this archive:

https://terminalnuget.blob.core.windows.net/packages/Microsoft.WindowsTerminal_Win11_1.12.10983.0_8wekyb3d8bbwe_Windows10_PreinstallKit.zip

**Comment by numericaseth** [comment]
That version works for me -- my steps no longer trigger the issue. Thank you!

**Comment by DHowett** [comment]
Thanks!
