### ISSUE TITLE
`sendInput` should be previewable

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12861]
See #9818, 60f63b09cc59f1a46d142952f49dbf7599bc4cf8, #3121. I literally have this prototyped, just need to check it in. It's important for future issues...

**Comment by zadjii-msft** [comment]
More cleanly pulled to its own branch: https://github.com/microsoft/terminal/pull/new/dev/migrie/f/12861-preview-input

**Comment by DHowett** [comment]
Curious how this will handle `sendInput`d escape sequences!

**Comment by zadjii-msft** [comment]
Punting out of 1.19. This was wacky as-is. We may want to come back to re-try this with more runway.
