### ISSUE TITLE
winget installer for terminal pkg runs into error

### ISSUE THREAD

**Issue by kushal-93** [microsoft/terminal#12878]
### Steps to reproduce

> winget install --id=Microsoft.WindowsTerminal -e
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

### Expected Behavior

> winget install --id=Microsoft.WindowsTerminal -e
should install the pkg

### Actual Behavior

> winget install --id=Microsoft.WindowsTerminal -e gives following error
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

**Comment by zadjii-msft** [comment]
Thanks for the report! This looks like it is actually already being tracked by another issue on the winget repo - please refer to https://github.com/microsoft/winget-cli/issues/1705 for more discussion.

/dup https://github.com/microsoft/winget-cli/issues/1705
