### ISSUE TITLE
Simple way to go to Settings if "Hide the title bar" is disabled

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#12872]
I haven't found a simple way to go to Settings to re-enable "Hide the title bar" after disabling it. Could a simple way be added, for example by adding it as a task?

![image](https://user-images.githubusercontent.com/2218936/162564569-b8dad95b-184f-4438-a704-cbc14aef3f5d.png)

**Comment by DHowett** [comment]
You can get to settings by any of the following methods:

* <kbd>Ctrl+P</kbd> to open the command palette and search for it.
* <kbd>Ctrl+,</kbd> to open Settings directly
* <kbd>Alt+Space</kbd> to open the system menu available to all Win32 applications

Does that help? 😃

**Comment by DHowett** [comment]
Oh, you can also get to the system menu by right-clicking the titlebar (also true of any Win32 application!)

**Comment by OlafvdSpek** [comment]
> You can get to settings by any of the following methods:
> 
> * Ctrl+P to open the command palette and search for it.
> * Ctrl+, to open Settings directly
> * Alt+Space to open the system menu available to all Win32 applications
> 
> Does that help? 😃

The system menu doesn't contain an entry for Settings. I used Ctrl-Shift-T to open a second tab, which allowed me to use the dropdown menu to open Settings.
The point is that this isn't (easily) discover-able and users might get stuck.

**Comment by DHowett** [comment]
Ah heck. It's been so long that 1.12 was in flighting that I forgot what changes went into which build.

I am pretty sure that 1.12 (now generally available!) offers Settings in the system menu. Would that address your concern?

**Comment by OlafvdSpek** [comment]
I installed Terminal through the MS Store.. doesn't it get updated automatically?
I've now got 1.12.10732.0 but I see no Settings in the menu:

![image](https://user-images.githubusercontent.com/2218936/162583140-cb534160-50ba-478e-8401-5f67593db2b1.png)

**Comment by OlafvdSpek** [comment]
Ah, it's 1.13 that has Settings in the menu.

**Comment by zadjii-msft** [comment]
Yep, this was added in #11404, in v1.13.10336.0

/dup #9666
