### ISSUE TITLE
When will the initial build released?

### ISSUE THREAD

**Issue by AnikHasibul** [microsoft/terminal#1287]
README says 

> The Windows Terminal is in the very early alpha stage, and not ready for the general public quite yet. If you want to jump in early, you can try building it yourself from source. Otherwise, you'll need to wait until **Mid-June** for an official preview build to drop.

When will we get it? Mid June is here!

**Comment by egigoka** [comment]
Get what? Source code are available

**Comment by AnikHasibul** [comment]
> Get what?

We expect the app on App store!

**Comment by Renha** [comment]
> Get what?

"an official preview build"

**Comment by jliu666** [comment]
Yes, I am not a C/C++/C# developer and don't know how to build it. I expect it too.

**Comment by jliu666** [comment]
![image](https://user-images.githubusercontent.com/14869749/59562530-5642f680-9060-11e9-9963-9fd5813bc0ec.png)

**Comment by lhutyra** [comment]
According FAQ;
> Otherwise, you'll need to wait until **Mid-June** for an official preview build to drop.

Maybe today? :)

**Comment by ZzzhaoGZ** [comment]
> 根据FAQ;
> 
> > 否则，您需要等到**6月中旬**才能正式预览构建。
> 
> 可能是今天？:)

不可能是今天了 ### ****。。。。。。。。。。。。。。。

**Comment by DHowett-MSFT** [comment]
Since Mid-June is a range of days, I'll implore you to please stay tuned. Thanks for being excited!
