### ISSUE TITLE
Scrolling issue using tmux on 4k monitor

### ISSUE THREAD

**Issue by xy9485** [microsoft/terminal#12874]
### Windows Terminal version

1.12.10732.0

### Windows build number

19044.1586

### Other Software

tmux 3.0a

### Steps to reproduce

active `set -g mouse on`

### Expected Behavior

Mouse scrolling as expected

### Actual Behavior

Scrolling only works when mouse is located in certain area of the display, clicking works well in contrast.
I notice this on my 4k monitor, it looks fine on a 1080p monitor. Looks like there is a mismatching betweeen the actual monitor resolution and resolution interpreted by Windows Terminal or by Tmux?

**Comment by zadjii-msft** [comment]
we've heard some variations of this in the past, so I just want to try and narrow it down.

1. Are you using a trackpad/touchpad to scroll, or an actual mouse wheel?
2. Does the mouse not work at a specific _column_ in the window? Like, if you change the font size, is it the same column that doesn't work for scrolling, or is more about the actual pixel location on the screen?

2 I'm thinking is less likely, considering that "clicking works well". I cannot for the life of me find the original issue though....

**Comment by xy9485** [comment]
1. I'm using laptop with monitor, using touchpad looks good, but actual mouse wheel doesn't work.
2. I tried and I think it has nothing to do with _column_, it's more about pixel location(or area) within the window, not matter in which size the window is scaled, full screen or not.

**Comment by zadjii-msft** [comment]
> using touchpad looks good, but actual mouse wheel doesn't work.

That's actually the opposite of what I'd expect. #2606 was the issue I was thinking of. Do you have anything like X Mouse Button Control, or some other custom mouse wheel software installed?

**Comment by xy9485** [comment]
> That's actually the opposite of what I'd expect. #2606 was the issue I was thinking of. Do you have anything like X Mouse Button Control, or some other custom mouse wheel software installed?

I don't install any mouse related software

> Does changing the DPI change the region of the window that works for scrolling?

Since I don't use any mouse control software, there is no way to change DPI, I just plugin usb and use the mouse.

> Is this _only_ an issue in tmux?

So far yes

**Comment by xy9485** [comment]
Thanks, I'll try this when I set in front of my computer. However, to my experience, 100% scaling on 4k display might not friendly to eyes, things are just too small.

**Comment by xy9485** [comment]
Yeah, could be a temporary solution, but still looking forward to a real fix in the future ;)
