### ISSUE TITLE
Starting WSL Ubuntu20.04 from Windows Terminal will cause high CPU usage of init process

### ISSUE THREAD

**Issue by moyrne** [microsoft/terminal#12870]
### Windows Terminal version

1.11.3471.0

### Windows build number

21H2 19044.1586

### Other Software

Starting WSL Ubuntu20.04 from Windows Terminal will cause high CPU usage of init process. Starting from WSL with the command `wsl -d Ubuntu-20.04` will not have this problem

WSL1 
Ubuntu-20.04 

$ unmae -a
Linux DESKTOP-Q3G0PTO 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

- config: command line: `wsl.exe -d Ubuntu-20.04`

- Start Windows Terminal and open Ubuntu-20.04

### Expected Behavior

The CPU usage of the init process is less than 10%

### Actual Behavior

The init process continues to occupy 100%

**Comment by zadjii-msft** [comment]
What is the `startingDirectory` for your WSL profile set to? This sounds a lot like #12343

**Comment by moyrne** [comment]
> What is the `startingDirectory` for your WSL profile set to? This sounds a lot like #12343

After I set the `"startingdirectory":"\\\\wsl$\\ubuntu-20.04\\home\\username"` according to #12343, the init process dose not have 100%. There is `usename/dir1` in my directory, which is a soft link. After setting `\\\\wsl$\\ubuntu-20.04\\home\\username\\dir1`, you will be prompted that the directory name is invalid 
~~~
目录名称无效。

[已退出进程，代码为 4294967295 (0xffffffff)]）
~~~
How can I set the default to enter this directory?

**Comment by zadjii-msft** [comment]
Presumably, the soft link in WSL isn't an actual path on the Windows OS side, so creating a process at that path is gonna fail, since the Windows side can't resolve that. 

I'd try manually passing in the resolved path for that soft link. Like, if `/home/username/dir1 -> /etc/foo/bar`, then set the `startingDirectory` to `\\\\wsl$\\ubuntu-20.04\\etc\\foo\\bar`

/dup #12343
