### ISSUE TITLE
"Always show tabs" doesn't (seem to) do anything when "Hide the title bar" is enabled (the default)

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#12873]
### Windows Terminal version

1.11.3471.0

### Windows build number

10

### Steps to reproduce

"Always show tabs" doesn't (seem to) do anything when "Hide the title bar" is enabled (the default), so maybe the option should be grayed out.

![image](https://user-images.githubusercontent.com/2218936/162564818-d61941ef-4646-4de0-865c-cc8d842dde83.png)

### Expected Behavior

"Always show tabs" should be grayed out

### Actual Behavior

"Always show tabs" not grayed out

**Comment by zadjii-msft** [comment]
Thats... probably a good point yea. And probably put it underneath Hide the title bar too, to help show the cause and effect more. Thanks!

**Comment by zadjii-msft** [comment]
Meh, some people really like that vintage console look. I'm not one of them, but they do exist 😝
