### ISSUE TITLE
Unable to use backslash on any shell

### ISSUE THREAD

**Issue by Eliaxs1900** [microsoft/terminal#1288]
# Environment

```none
Windows build number: [10.0.18917.1000]
Windows Terminal version: 2.2.182.4985
```

# Steps to reproduce
Open someone shell and type "Ctrl + \\" in cmd return 'º'
![imagen](https://user-images.githubusercontent.com/12803951/59562732-a3a76f80-9030-11e9-901b-989e73a2e298.png)

**Comment by eloy-salamanca** [comment]
Same behavior in my case

**Comment by zadjii-msft** [comment]
What keyboard layout are you using? Are you using a keyboard with AltGr? #521 may be a dupe here.

**Comment by eloy-salamanca** [comment]
Spanish keyb. Yep, it seems like same issue as dupe #521

**Comment by Eliaxs1900** [comment]
Yes @zadjii-msft, my keyboard has AltGr key and it is Spanish Version.

**Comment by zadjii-msft** [comment]
Yep, then that's definitely the other issue. Closing as a dupe.
