### ISSUE TITLE
Run a profile as administrator without re-launching Terminal app as admin

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#12885]
This likely has been discussed before, but I didn't find an existing issue.

If Windows/PowerShell sudo is implemented (https://github.com/microsoft/terminal/issues/146), the need for this is less pertinent. My usecase was opening terminal and hitting `wsl --install` only to find that I need to re-launch Terminal as admin. It would be nice to allow to re-launch an existing/opened tab as admin without figuring out how to re-launch the whole terminal as admin

Another way may be a button Re-launch as admin (as offered by Process Explorer) - but this is worse compared to launching a specific profile as admin

**Comment by zadjii-msft** [comment]
Sorry, but we won't be allowing mixed tabs at different elevation levels. There's more details in https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#elevation, as well as in [Elevation Quality of Life Improvements](https://github.com/microsoft/terminal/blob/main/doc/specs/%235000%20-%20Process%20Model%202.0/%231032%20-%20Elevation%20Quality%20of%20Life%20Improvements.md#background). 

In 1.13, you can ctrl+click on a profile to launch it in a new elevated window automatically:
![image](https://user-images.githubusercontent.com/18356694/162817072-e2399cf5-1228-46db-8a1e-0398edab3a2c.png)

/dup #632

**Comment by vadimkantorov** [comment]
My main issue is discoverability / UX here.
1. First-time run of Win11
2. Open Terminal+PowerShell, run `wsl --install`, get a "not elevated enough" error argh need to remember how to run Terminal in elevated mode. Maybe the error message could remind of this e.g. say press Win+X and select Windows Terminal +Admin. Or maybe Terminal could detect this error message and highlight it (like it does with links) and allow clicking on it for re-launch as admin. Or maybe the error message could include a special hyper link https://ms-terminal/relauch-as-admin that could be highlighted and actionable
3. Tooltips are not solving discoverability in full (especially if you're not knowing beforehand where to hover for this message to appear). Maybe worth to have a fully-fledged item in the New-Tab that would in fact launch the profile as admin, but in a new Terminal

**Comment by vadimkantorov** [comment]
Related: https://github.com/microsoft/terminal/issues/12985#issuecomment-1110868052

**Comment by zadjii-msft** [comment]
Ah. To clarify, we're not mixing different permission levels in the same window. I was under the impression that this thread was asking for "I want an admin version of {current profile} in the same window". I'm using that one for "I want an admin version of {current profile} in a new window". Maybe it just took my brain two weeks to tease out the marginal difference between the two 😅
