### ISSUE TITLE
Wraped output contains new line character when copy/paste

### ISSUE THREAD

**Issue by b-hayes** [microsoft/terminal#12889]
### Windows Terminal version

1.12.10733.0

### Windows build number

22000.556

### Other Software

WSLv2 with Ubuntu

### Steps to reproduce

run any command that outputs a single line too long to fit in the terminal width
copy the wrapped output
paste into an IDE/editor and see that newlines are injected into the output newlines

FYI: I had no problem with this before until I just upgraded to windows 11 from win10 and then updated the Windows terminal app via MS store to the latest version.

Previously I had abandoned other terminals and stopped using built-in ones in IDE's. I relied on Windows terminal because it was the only one that didn't inject newline chars.
But now it does, so I'll have to abandon the windows terminal as well 😢

### Expected Behavior

the output to be copied as-is without newlines added.

### Actual Behavior

output contains new lines

**Comment by b-hayes** [comment]
it was not windows terminal causing this

**Comment by thenger** [comment]
@b-hayes can you explain what was the problem for me and for future users please ?

**Comment by thenger** [comment]
Okay for some reasons, my settings.json was set like this:

```
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": "unbound",
            "keys": "ctrl+v"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "copy",
                "singleLine": true
            },
            "keys": "ctrl+c"
        },
```

And that copy shortcut seems to apply when selecting for copy

I changed to this:

```
       {
            "command": 
            {
                "action": "copy",
                "singleLine": true
            },
            "keys": "ctrl+c"
        },
```

According to this https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#clipboard-integration-commands

hth

**Comment by b-hayes** [comment]
I honestly can not remember now. Ended up going back to windows 10 for several reasons and never looked back.
