### ISSUE TITLE
Ctrl+Shift+Scrollwheel can no longer fully disable transparency when using Acrylic

### ISSUE THREAD

**Issue by kevinmyexp** [microsoft/terminal#12880]
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000.593

### Steps to reproduce

"useAcrylic": true
"opacity": 100 / "acrylicOpacity": 1.0

### Expected Behavior

Terminal window with fully opaque, solid color background

### Actual Behavior

![image](https://user-images.githubusercontent.com/17904156/162637785-4622852d-0881-4d03-bd50-6e0abd756358.png)

Terminal window still presents minor Acrylic effect, 
thus making switch between Acrylic% and Opaque with C+S+Wheel impossible.

**Comment by zadjii-msft** [comment]
we discussed this some weeks back but never noted it down: I did this intentionally so people could have fully opaque acrylic. Turns out though, no one really likes that, and wants 100% opacity to always mean "acrylic off". That's fine by me. We just need to revert that bit of logic.

**Comment by ofek** [comment]
> We just need to revert that bit of logic.

Would that be easy enough to include in the next release?
