### ISSUE TITLE
Windows Terminal grabs mouse forward/back buttons even though they can't be bound to anything

### ISSUE THREAD

**Issue by fluffynuts** [microsoft/terminal#12891]
### Windows Terminal version

1.12.220314002-release1.12

### Windows build number

10.0.22000.0

### Steps to reproduce

When Windows Terminal has focus, the side buttons on a mouse ("forward" and "back") are grabbed even though Windows Terminal allows for no binding of these buttons.
This presents an issue when using other third-party software to bind these buttons globally (eg XMouseButtonControl) - in my case, I've bound these buttons for volume up/down for many years, but those bindings don't work if WindowsTerminal has focus ):

### Expected Behavior

If I can't manipulate the bindings within Windows Terminal, they shouldn't be grabbed. I know there are ongoing discussions around handling these buttons within WT - those should probably also allow the user some way to disengage, for the same scenarios as outlined above.

### Actual Behavior

WT grabs the mouse inputs and does nothing with them.

**Comment by zadjii-msft** [comment]
Interesting. I bet this isn't a problem that's unique to the Terminal, but probably would repro for any XAML Islands application. We're definitely not getting those keys as KeyDown events (we might still get them as mouse events). Regardless, I don't think we're handling them... I'd suspect that the XAML Island's CoreInputSite prevents XMBC from using those inputs for whatever reason.

Does this repro in the PowerToys settings app? Or perhaps the new Windows 11 version of notepad/? (not sure if that version of notepad ships on 22000, but worth a shot)

**Comment by crutkas** [comment]
@fluffynuts the reset issue with PowerToys was due to a change in behavior from the .NEt installer we believe that didn't show up in our testing.  https://github.com/microsoft/PowerToys/pull/17255 from builds greater than 0.57 this should be effect with PowerToys and we directly pass in a noreset flag.

**Comment by fluffynuts** [comment]
@crutkas I had the arb reboot, saw the issue, saw the "fix", had it again later (about 1-2 weeks later). I give up. There are some neat things in that package, but none of them are worth losing work over a forced, uninterruptible, unexpected reboot. And when I raised the issue, I got the "powertoys is an alpha, deal with it" speech. That's a 100% nope from me.

**Comment by crutkas** [comment]
I don’t think we said deal with it but it is not a 1.0 nor did we ever claim it to be.

**Comment by DHowett** [comment]
I'm going to minimize y'all as off topic now, to make sure we can focus on the Terminal issue at hand. Thanks for understanding!

**Comment by carlos-zamora** [comment]
Hi @fluffynuts. Sorry for the radio silence. We suspect this is a XAML Islands bug. Can you confirm if you have the same issue occur with c:\windows\system32\PerceptionSimulation\PerceptionSimulationInput.exe (another XAML Islands bug)? Thanks in advance!

**Comment by fluffynuts** [comment]
@carlos-zamora is there some fancy way to run PerceptionSimulationInput? When I run from the console, it appears to exit immediately, and I get the same double-clicking the .exe

**Comment by carlos-zamora** [comment]
Honestly, sorry, but I have no idea. There aren't many XAML Islands apps out there. Thanks for trying this out. Marking as Needs-Repro and Help Wanted. Throwing it in the backlog.

**Comment by fluffynuts** [comment]
fwiw, I've just tested on WT 1.16.10262.0 right now, after seeing this in my GH notifications, and it doesn't seem to be grabbing those buttons any more. Closing as can't repro any more (perhaps fixed along the way)
