### ISSUE TITLE
Re-Scan WSL distros at launch

### ISSUE THREAD

**Issue by haydennyyy** [microsoft/terminal#1289]
# Summary of the new feature/enhancement

I think it could be useful to have Cascadia re-scan the WSL distros every time it launches, so that installing a new WSL distro will reflect on the profiles menu.

# Proposed technical implementation details (optional)

It would just run `CascadiaSettings::_AppendWslProfiles` every time the app loads up, so it gets them all and adds any _new_ profiles necessary,

**Comment by DHowett-MSFT** [comment]
Hey, weird enough, this’ll be fixed by #754. There’s a spec review in progress for that feature at #1258.
