### ISSUE TITLE
Windows Terminal becomes unusable after running gradle in WSL

### ISSUE THREAD

**Issue by mjsztainbok** [microsoft/terminal#12897]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19043.0

### Other Software

gradle 7.4

### Steps to reproduce

Do a gradle build which produces errors

### Expected Behavior

The terminal window operates correctly and can accept keyboard input

### Actual Behavior

Sometimes after the gradle build the tab stops responding and it doesn't respond to keypresses. You can still scroll the tab though.
It also shows still shows the cursor on focus. Pressing Ctrl-L to reset the UI in the shell doesn't do anything.

This is how the window looks:
![image](https://user-images.githubusercontent.com/67809434/163069656-dbb9e34c-db3f-48fe-8750-53e4ac8b65b9.png)

**Comment by mjsztainbok** [comment]
Actually it's not just gradle where this happens. It seems to occur after any failing commands in the shell in WSL

**Comment by zadjii-msft** [comment]
Honestly, I have no idea what's going on here. Does this repro in a vintage console window, as well as in a Terminal window? Do you have a minimal repro of a command that causes this (smaller than just "sometimes after a gradle build"/? Does the content of the tab "reflow" if you resize the terminal window to be a smaller width? (that might help ID if the Terminal control itself is hung, or it's something else behind the scenes that's hung.
