### ISSUE TITLE
Setting launch mode to full screen also applies to Quake mode

### ISSUE THREAD

**Issue by nathpete-msft** [microsoft/terminal#12894]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19043.0

### Steps to reproduce

1. In Terminal settings, set: Startup > Launch Mode > Full Screen
2. Summon the Quake window

### Expected Behavior

I wouldn't expect Quake mode sizing to be affected by the Terminal launch mode.

### Actual Behavior

Quake mode opens in full screen.

Apologies if this is a duplicate, I didn't see it mentioned in #8888 and it's different than #10199.

**Comment by zadjii-msft** [comment]
Yep this is a real bug we should fix. Thanks!
