### ISSUE TITLE
[geopolitical] language names should be region agnostic.

### ISSUE THREAD

**Issue by tigerinus** [microsoft/terminal#12895]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/7172560/163047900-b32dff45-d578-44b4-927d-d58484f77af2.png)

This is indeed a dup of https://github.com/microsoft/terminal/issues/8984 - which has been open but hasn't been resolved in more than a year. Opening a new issue just to bring the awareness back.

### Expected Behavior

中文（简体）
中文（繁体）

### Actual Behavior

中文（中华人民共和国）
中文（台湾）

**Comment by DHowett** [comment]
Thanks for raising this again. Unfortunately, the Windows language team doesn't agree that this needs to be fixed.

/dup #8984

**Comment by tigerinus** [comment]
> Thanks for raising this again. Unfortunately, the Windows Store team doesn't agree that this needs to be fixed.
> 
> /dup #8984

Not sure about the guideline behind Windows Store team when making the Won't Fix decision, but per https://docs.microsoft.com/en-us/globalization/localization/overview - _Avoiding sensitive geopolitical issues is one important consideration in making sure a product is well received in the international market._
