### ISSUE TITLE
Black screen in legacy mode

### ISSUE THREAD

**Issue by eElor** [microsoft/terminal#1290]
Today Ubuntu (WSL) opened just a black window.

I re-installed it and tried different things to get it to work properly again. I noticed that using the legacy mode caused that black/blank window. However, by turning it off, all the other windows consoles (cmd, powershell) became black as well.

Re-installing Ubuntu and using it seems to require the legacy mode to be off, but cmd and powershell on... That wasn't the case not long ago.

my WSL was always up to date. I wrote this issue after it completely stopped working. I still do not know the reason. But after playing around, I discovered the issue with the legacy mode. I just tried it again: I updated and upgraded WSL and turned on legacy mode (was off before, since WSL won’t work otherwise).

WSL stopped working altogether. It won’t even start... However, CMD and Powershell are working now (were before only black windows). And they only do in legacy mode ( `right click on any console > properties > Options >Use legacy console (requires relaunch...) `). As soon as I turn legacy mode off in cmd/powershell, WSL starts working again, but the other two appear just as black windows.

![image](https://user-images.githubusercontent.com/39239890/59568421-c3638580-907a-11e9-80c2-8bd33c988e8f.png)

![image](https://user-images.githubusercontent.com/39239890/59568416-b6469680-907a-11e9-8221-33390a43b6f8.png)

**Comment by zadjii-msft** [comment]
You're gonna want to look at the "Terminal" tab in your propsheet. I'm gonna go out on a limb and guess that the "Default Foreground" and "Default background" colors somehow got set to 0,0,0 for each of them. You could probably just uncheck those boxes to fix powershell and cmd.

**Comment by eElor** [comment]
Thanks @zadjii-msft, that was it. Unchecking "Use Separate Background / Foreground" solved the problem. However I don't remember having checking them...

**Comment by zadjii-msft** [comment]
That's a good point. It seems to happen sometimes on updates to the latest Windows build, but we've never been able to get a solid repro case.

**Comment by Richard004** [comment]
Same for me. I had the default value of 0,0,0 for both Terminal Colors and Use Separate Foreground was on. The same scenario happened on both my machines. 
I did not explicitly mess with this part of settings.
I was lost also.
But I've installed the experimental Terminal before, so I 'kind-of' took the blame on my experimenting there.
