### ISSUE TITLE
ubuntu 22.04 copy and paste is unusual 

### ISSUE THREAD

**Issue by kybom** [microsoft/terminal#12905]
### Windows Terminal version

1.12.10733.0

### Windows build number

windows 11  22000.613

### Other Software

ubuntu 22.04

### Steps to reproduce

try to copy text by selecting text

### Expected Behavior

Expected that the text is copied and can paste as usual from windows clipboard.
![QQ20220414091504](https://user-images.githubusercontent.com/24692485/163295468-d2d3694b-815b-4aab-b55a-3598420c89d6.png)

### Actual Behavior

when pasted ,the text has a white background.
![QQ20220414091355](https://user-images.githubusercontent.com/24692485/163295675-c1d31c9a-a985-4b94-9c58-58210749d8da.png)

**Comment by zadjii-msft** [comment]
Huh. Any chance this might be relevant? 

https://askubuntu.com/questions/1334205/pasted-text-in-gnome-terminal-in-21-04-is-always-highlighted

**Comment by kybom** [comment]
Thanks. 

I do not like the new  bash "feature".

"set enable-bracketed-paste off" works for me.

**Comment by zadjii-msft** [comment]
Glad to hear this one wasn't us!
