### ISSUE TITLE
The window colors are all broken

### ISSUE THREAD

**Issue by krlinus** [microsoft/terminal#12901]
Overnight, my PC underwent some windows updates and now my WSL window shows washed out colors
![image](https://user-images.githubusercontent.com/984391/163244394-83c71b4a-821f-4d8a-b68e-970379bb4608.png)

![image](https://user-images.githubusercontent.com/984391/163244664-ac47af76-37de-4e4f-88f7-e751b7771cea.png)

**Comment by krlinus** [comment]
Edition	Windows 10 Pro
Version	21H1
Installed on	‎7/‎27/‎2020
OS build	19043.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by Rasmus-123** [comment]
I have the same/a similar issue.

Suddenly when the window is focused everything looks grey-ish.  
If it's not focused it has it's normal full colours.

Transparency is at 100% and Acrylic is turned off, so it's not that.

WT-Version: 1.12.10732.0

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

@krlinus I'd also be interested in which version of Terminal you're using.

**Comment by DHowett** [comment]
@zadjii-msft if I had to guess . . . these users have set `acrylicOpacity: x` and _did not set `useAcrylic`. We promoted `acrylicOpacity` to `opacity`, and now it "wins" and enables acrylic. On Windows 10.

**Comment by krlinus** [comment]
@DHowett While I must say the terms like acrylicOpacity etc doesn't make a lot of sense to me, your explanation about opacity helps in my context, because when I turned opacity closer to 100% it improved by a good margin

![image](https://user-images.githubusercontent.com/984391/163271268-92077ad5-1e2f-4a24-8a9a-21d181bb6422.png)

I don't face the issue anymore, and you may close the case if you deem fit.

**Comment by zadjii-msft** [comment]
Uh oh. Well, that definitely has be afraid that 1.12 on win10 with acrylicOpacity set doesn't actually set acrylic like it should...

I'm even more worried that you never set the opacity and now we're doing something even more unexpected 😨

**Comment by tjhowse** [comment]
Can confirm: I've never (knowingly) set acrylic mode, or changed opacity. I am a boring person and would like my terminals black :D

This morning I found my terminal slightly translucent. I went into the settings and toggled acrylic on and off and played with the slider, but I was unable to get my terminal fully opaque unless I gave focus to another window, at which point windows terminal went fully opaque.

I read #12880 and learned about the ctrl+shift+scrollwheel key combo. Using that I was able to make the background fully opaque. I had assumed, until I found this issue, that I had accidentally performed that key combo at some point and hadn't noticed until now.

**Comment by felix5572** [comment]
same situation as @tjhowse  .  Sovled after use  ctrl+shift+scrollwheel key combo.

**Comment by dl4mmers** [comment]
Same here after windows update to Windows 10 Enterprise 20H2 19042.1645

Thanks for the ctrl+shift+scrollwheel workaround.

**Comment by krlinus** [comment]
ctrl+shift+scrollwheel -- what a delightful workaround!

**Comment by zadjii-msft** [comment]
Hey this may have just been a fluke during upgrade, during the introduction of vintage opacity. We haven't seen fresh reports of this in months, so I'm assuming there was a small window where either the setting got migrated wrong, or some super old defaults filled this in wrong.

If we more dramatically broke this, then I' would have heard about it to kingdom come. 

If anyone's still seeing this, double check your [`opacity` and `useAcrylic` settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#opacity).
