### ISSUE TITLE
Feature Request: Move tabs between two Windows Terminal windows

### ISSUE THREAD

**Issue by DoctorSclero** [microsoft/terminal#12919]
# Description of the new feature/enhancement
Add the ability for the user to move a tab from one window to another as you would do in the browser.

**Comment by skyline75489** [comment]
I think #1256 covers this.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
