### ISSUE TITLE
Drag and drop does not work properly if monitor set to not 100% scale

### ISSUE THREAD

**Issue by PetSerAl** [microsoft/terminal#12915]
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000.613

### Steps to reproduce

Set monitor scaling to not 100%

Drag and drop file to down or right part of window. (indication changes saying you can not paste here)
or
Split window with pane.
Drag and drop file just left (or up) of splitter. (file name got pasted to different pane)

### Expected Behavior

It should be possible to drag file to any part of window.
File name should be inserted in the pane you drag it to.

### Actual Behavior

<img width="867" alt="1" src="https://user-images.githubusercontent.com/17184058/163671395-566a5591-e500-48b6-ab11-17dadd0ce38f.png">
<img width="867" alt="2" src="https://user-images.githubusercontent.com/17184058/163671396-7f16e262-180c-43e7-b328-7f5053fa2294.png">
<img width="867" alt="3" src="https://user-images.githubusercontent.com/17184058/163671397-bc2e39b3-96eb-4842-b2a8-5b8134a7d281.png">
<img width="867" alt="4" src="https://user-images.githubusercontent.com/17184058/163671398-1c637f88-14b0-4848-9f14-f35140f92a91.png">

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2606 for more discussion.

/dup #2606
