### ISSUE TITLE
On-screen keyboard opens on windows unlock

### ISSUE THREAD

**Issue by Foosec** [microsoft/terminal#12912]
### Windows Terminal version

1.12.10732.0

### Windows build number

10.0.19044.0

### Other Software

May be related to wacom tablet, since windows no shows windows ink workspace, however this happens when its not plugged in aswell.

### Steps to reproduce

Leave terminal open and focused, lock windows and unlock windows. 

### Expected Behavior

Nothing

### Actual Behavior

The terminal gets squished to the top half of the screen and the on screen keyboard gets displayed.

**Comment by zadjii-msft** [comment]
What kind of device are you on/? The relevant issues I'm thinking of:
* #3639
* #8529

**Comment by Foosec** [comment]
This was caused by Wacom drivers or rather Windows' incredibly hidden settings 
![image](https://user-images.githubusercontent.com/31885466/163985980-8dc9a3e6-709f-42e8-ba22-c5190291dff8.png)
Relevant setting is "Show the touch keyboard when there's no keyboard attached" (There is a keyboard attached, both a USB and a laptop one, but thats an issue for another day)

You can find these settings if you search for tablet settings, they are not inside keyboard settings, ease of access settings, or Windows ink settings as one might assume. (For others possibly facing the same issues)

**Comment by zadjii-msft** [comment]
Well, glad you got it sorted out, and I absolutely adore you for actually sharing the resolution for future readers ❤️
