### ISSUE TITLE
Certain text editors cause settings auto-reload to crash

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#1292]
Certain text editors use an atomic write to update files on disk to avoid torn state. The `Windows.Storage` API we are using _throws an exception_ if the file briefly doesn't exist.

To reproduce: edit profiles.json in vim, save it twice.

**Comment by zadjii-msft** [comment]
Please add a description when filing new issues

**Comment by DHowett-MSFT** [comment]
I deserve that. I've edited to add a description 😉
