### ISSUE TITLE
Quake mode from the launch

### ISSUE THREAD

**Issue by NSurtsev** [microsoft/terminal#12928]
### Windows Terminal version

1.12.10732.0

### Windows build number

19044.1645

### Steps to reproduce

Launch Terminal

### Expected Behavior

When we have "Quake mode" ability, I expect to have option to have Quake window when I launch Terminal or at least autoreplace the default window If I use Win+~

### Actual Behavior

I launch Terminal, get default Terminal window and I have to press Win+` to get Quake ( window #2), then to system tray and close default Terminal window #1.
And only then it becomes as it should be (but still, name #2 remains for Quake for whatever reason).

**Comment by zadjii-msft** [comment]
This sounds like you're looking for #9996.

You can immediately launch the quake window with `wt -w _quake`. Or, you should be able to convert an existing window to be the quake window by renaming the window to `_quake` (with the "Rename window" action in the Command Palette). That of course assumes there isn't an already running quake window, of course.

Does that make sense?

**Comment by NSurtsev** [comment]
> This sounds like you're looking for #9996.
> 
> You can immediately launch the quake window with `wt -w _quake`. Or, you should be able to convert an existing window to be the quake window by renaming the window to `_quake` (with the "Rename window" action in the Command Palette). That of course assumes there isn't an already running quake window, of course.
> 
> Does that make sense?

Ok, these options are interesting, but that doesn't actually solve the main issue.
Why should I right commands or doing renames when I should launch Terminal and Quake window should meet me immediately?
(Btw, there should be option in settings to make Quake mode default for launching)
And even if I do not check this potential future option and there is default window opened, I should just press Win+` and this window should become Quake, because I checked "make new instance add to existing window" option in settings (if you do not check it, then it should create separate Quake window like it already does now)

**Comment by markusdd** [comment]
I wish to second that.

We simply need an option to launch in quake mode as default (as there are options for maximized etc.).

Also, quake mode should NOT launch in Focus mode by default, that does not make sense. (at least it should be configurable).

Currently I always need 4 steps to get my windows terminal: 
- launch it from taskbar
- then launch quake mode
- close the other window
- take quake window out of focus mode

This is annoying xD

**Comment by zadjii-msft** [comment]
Okay yea, between the two of you, it sounds like you're looking for 

/dup #9996
/dup #9992

FYI you don't need to use the `quakeMode` action to summon the window - you could always just rebind <kbd>win+\`</kbd> to a plain old [`globalSummon`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon) action. Then you'd summon whatever terminal window you were already using, without the focus mode baggage attached. You can even use globalSummon with a dropdownDuration if that's really important (though, you can't currently dock the window to the top of the monitor outside the `_quake` window).

**Comment by markusdd** [comment]
Sorry, I do not seem to understand this. I have now put this globalSummon stuff in my JSON settings, still I have to perform the same steps to get my quaske window, also the focus mode is still on on first launch.

I just want this terminal to launch in quake mode without focus mode, why is that so difficult? xD
