### ISSUE TITLE
Enable sending input to terminal instance by wt.exe

### ISSUE THREAD

**Issue by ZhiruiLi** [microsoft/terminal#12925]
# Description of the new feature/enhancement

Some times we need to control windows terminal through command line. For example: switch dir to a given path. Now the only way to do that is to open a new pane or tab through `wt.exe`. However, open a new pane or tab is very slow when using powershell, it will be faster if we can just send input to a existing terminal, like:

```bash
wt.exe -w 0 -S "cd ~/project/MyProj; git pull"
```

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Okay this might seem silly, but `wt -w 0 send-input {whatever}` seems a lot harder than just typing `{whatever}` at the commandline in the current window, right?

This sounds a lot like #9368, but I might need more context on your actual use case here

**Comment by ZhiruiLi** [comment]
> Okay this might seem silly, but `wt -w 0 send-input {whatever}` seems a lot harder than just typing `{whatever}` at the commandline in the current window, right?
> 
> 
> 
> This sounds a lot like #9368, but I might need more context on your actual use case here

There are many case that we can't type in current window, for example: implement a plugin in vscode to let current terminal cd to current file location.

**Comment by zadjii-msft** [comment]
Okay yea that's on me. Must not have had enough coffee - I read "commandline" and automatically assumed you were already sitting at the Terminal window and wanted to run that commandline _in the Terminal window_ 😝 

/dup #9368
