### ISSUE TITLE
A Blank Box Appears while launching or closing the app

### ISSUE THREAD

**Issue by garv-7** [microsoft/terminal#12922]
### Windows Terminal version

1.13.10734.0

### Windows build number

10.0.22000.0

### Steps to reproduce

To Reproduce this: 

- either launch the app or close the app

Screenshot:
![image](https://user-images.githubusercontent.com/95747355/163765654-bbd8fd52-0a55-4fb9-8f10-291ad6da0a39.png)

### Expected Behavior

Expected behavior for the app is to launch normally to the command line without anything else showing up in the process of launching or closing the app. 

### Actual Behavior

Actual Behavior: While launching or closing the app there's a transparent box showing up for a short period of time.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11561 for more discussion.

/dup #11561
