### ISSUE TITLE
break is missing here?

### ISSUE THREAD

**Issue by jmelas** [microsoft/terminal#12923]
https://github.com/microsoft/terminal/blob/41ef5554f5cb946c4a48e2b8db791265c7217fce/src/cascadia/WindowsTerminal/IslandWindow.cpp#L597

**Comment by zadjii-msft** [comment]
Yes, there absolutely is. Good eye! would you like to open a PR for that?

**Comment by jmelas** [comment]
> Yes, there absolutely is. Good eye! would you like to open a PR for that?

OK I will do!
