### ISSUE TITLE
Some way to exit out of focused mode

### ISSUE THREAD

**Issue by win21H2** [microsoft/terminal#12921]
# Description of the new feature/enhancement
I have noticed when I wanted to go into focused mode for Terminal, I could not find any way to exit out of focused mode. Instead I had to uninstall it and install it back via Powershell and that can get a bit fustrating if you constantly have to uninstall/install Terminal every time you go into focused mode.

# Proposed technical implementation details (optional)
I was thinking that maybe a keyboard shortcut such as the below to switch out of focused mode so that when the user presses them, the "taskbar" at the top of the Terminal application shows up
`alt+x`
or 
`alt+shift+x`

Please tell me if I need to include any more details :)

**Comment by 237dmitry** [comment]
You can set keyboard shortcut by yourself. Like this:
```
  "actions": [
    {
       ....
    },
    {
      "command": "toggleFocusMode",
      "keys": "alt+t"
    }
  ],
```

**Comment by zadjii-msft** [comment]
Yea there's already an action to toggle focus mode. You can open the command palette with <kbd>ctrl+shift+p</kbd>, then type "fomo", and that should give you the "toggle focus mode" action. 

![toggle-fomo](https://user-images.githubusercontent.com/18356694/163797472-b35b33a7-1f92-4294-8ae2-e9c2571d0922.gif)

Sorry that you've had to uninstall the terminal to get out of it 😨
