### ISSUE TITLE
Accented characters take up extra space

### ISSUE THREAD

**Issue by DoubleStrike** [microsoft/terminal#12940]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Show an accented character in the window, either in Command Prompt or Powershell.  The character takes extra space.

This occurs both with and without Experimental Text Rendering turned on.

### Expected Behavior

The character should only take a single column.

### Actual Behavior

The character is centered across two columns with empty space on each side.

Here is an example from a git log pull from the Blender repository.  You can see Clément's name gets screwed up:

Experimental Rendering on:
![Bug-ExperimentalRenderingOn](https://user-images.githubusercontent.com/17889466/164109754-5e526bd7-2de5-4bdd-8f45-34a2e242b84d.png)

Experimental Rendering off:
![Bug-ExperimentalRenderingOff](https://user-images.githubusercontent.com/17889466/164109766-3e360a4d-c21c-4242-ab1c-22b2947d3fba.png)

Note that git is outputting these by using a punctuation character suffixed to the letter.  In good old CMD.EXE, it looks like this:
![Bug-Cmd](https://user-images.githubusercontent.com/17889466/164110052-0782a639-2327-43cb-9bff-ea4538645070.png)

**Comment by DHowett** [comment]
Right, so this is one of the things that's part of #8000 / #1472. There are two characters there, and they are therefore afforded two cells :smile:

Once we land something a little smarter for the text buffer, we'll be able to do something about that.

One of the critical issues here is determining the application's intent. For better or worse, the Windows console allows you to read back the screen contents. If we combine those into _one cell,_ the application's measurements could be all wrong, or it could fail to read back the data that it wrote (should it so choose.) It's delicate.

/dup #8000
