### ISSUE TITLE
How I do change cursor shape?

### ISSUE THREAD

**Issue by KiYugadgeter** [microsoft/terminal#1294]
How do I change cursor shape?
I have tried change cursor setting in settings json file to "solid",it does not react.

**Comment by DHowett-MSFT** [comment]
You've gotten far enough as to find the code, build the code, and find out that there's a `cursorShape` setting, and that's all fine and well...

The cursor shapes are `filledBox`, `emptyBox`, `bar`, `underscore`, and `vintage`.

**Comment by KiYugadgeter** [comment]
@DHowett-MSFT Which file should I see to list of values of settings?

**Comment by oising** [comment]
@KiYugadgeter I'm sure you could figure out how to search some text files for the words that Dustin listed above, no/ :)

**Comment by yu-soong** [comment]
Can I change the thickness of cursor if I set the cursorShape as "bar"?

**Comment by SanePai** [comment]
Is there a way I can change the thickness of the cursor? I like it a bit thicker than "bar" and less than "filledBox".

**Comment by zadjii-msft** [comment]
@SanePai Check out the [`cursorHeight`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#cursor-height) setting

**Comment by SanePai** [comment]
> @SanePai Check out the [`cursorHeight`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#cursor-height) setting

I tried that. It works only with the "vintage" shape and a height of 100 is just the same as the "filledBox" shape.

**Comment by zadjii-msft** [comment]
Okay did you try other cursor heights? Like, 25 will be smaller than a filled box...

**Comment by SanePai** [comment]
> Okay did you try other cursor heights? Like, 25 will be smaller than a filled box...

Yeah. I did.
But that reduces the vertical dimension. I prefer mine full-sized vertically. I wanted to change the width of the cursor.

**Comment by zadjii-msft** [comment]
Ah, that's where the miscommunication was. I read "thickness" as "height". My bad!

We're tracking that feature request over in #3167

**Comment by SanePai** [comment]
Oh okay. np.
Thanks. Ill keep an eye on that.
