### ISSUE TITLE
does this have to be 2 different colors?

### ISSUE THREAD

**Issue by RYDB3RG** [microsoft/terminal#12941]
Hi,

does the active tab background color and the actual tabcontent have to be 2 different colors?

![image](https://user-images.githubusercontent.com/7002848/164171756-0c2f709e-42d6-4a6c-9e0e-1d788063c192.png)

**Comment by zadjii-msft** [comment]
Nope! You can always set [`tabColor`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#tab-color) in the profile to match the `background` of the tab.

![015-tabColor-in-profile](https://user-images.githubusercontent.com/18356694/164205668-28f0be07-0b73-49e6-939d-ce10cb2ad2b1.gif)


Doing this automagically is tracked in /dup #702
