### ISSUE TITLE
The background of hidden icon panel on the task bar doesn't work good

### ISSUE THREAD

**Issue by MineCreeper86** [microsoft/terminal#12945]
### Windows build number

10.0.18363.0

### Other Software

WeChat (ver. 3.6.0.18)

### Steps to reproduce

Come (or return) to the desktop
Open the hidden icon panel
Click an item in the panel to make it show a fullscreen UI

### Expected Behavior

The background of the panel will become the blurred version of the opened application rather than the wallpaper.
Or you can just close the panel, it also makes sense.

### Actual Behavior

The started application's UI was partly covered with the hidden icon panel, but the background of the panel wasn't the blurred version of the UI of application but still the wallpaper.
(some of them work correctly, but for wechat in my case did't behave well)

**Comment by zadjii-msft** [comment]
Can you share some screenshots of what you're describing? Maybe a screen recording/? Possibly with [ScreenToGif](https://www.screentogif.com/)? I'm really not sure that this is a Terminal issue...

**Comment by DHowett** [comment]
This sounds like the same thing as #4774! @MineCreeper86 does your bug look like this?

![image](https://user-images.githubusercontent.com/35339647/75679194-201ad500-5cca-11ea-8d95-0f2bfbabb944.JPG)

**Comment by MineCreeper86** [comment]
> This sounds like the same thing as #4774! @MineCreeper86 does your bug look like this?
> 
> ![image](https://user-images.githubusercontent.com/35339647/75679194-201ad500-5cca-11ea-8d95-0f2bfbabb944.JPG)

No, it's not like this. Wait a minute.

**Comment by MineCreeper86** [comment]
![animation](https://user-images.githubusercontent.com/61276297/164642340-5f798f35-64d3-4ac7-a3c7-62f095eb6ef5.gif)
You can see that the background of the panel didn't change while the UI of a new program displayed.
**Clue:** The UI started like an existing invisible window became visible. The application which behaved like reload the UI didn't cause such problem.
That is to say:
`frame  = new Frame(...)` wouldn't cause the problem.
`frame.setVisible(true)` would cause it.
However, it's not serious :D

**Comment by zadjii-msft** [comment]
Ah, okay. I'm not really sure how this is a _terminal_ issue. Probably best to file that as feedback through the Feedback Hub. But it looks to me like that's already fixed in Windows 11:



![gh-12945](https://user-images.githubusercontent.com/18356694/164704809-a5f54dc6-4463-4ac3-92fd-946869b87e84.gif)
