### ISSUE TITLE
Add admin and non-admin Terminal Tabs

### ISSUE THREAD

**Issue by jonasprechtl** [microsoft/terminal#12956]
# Description of the new feature/enhancement

When working with the Terminal, I usually work with no admin privileges because I would have to take the extra step to right-click and run as administrator. Sometimes, however, I need an admin terminal for a Task. It would be nice if it was possible to mix admin and non Admin Terminal Tabs in one window, so when I have to run as administrator, I wouldn't have to work with two terminal instances at once and remember which instance is which.
I suggest a setting to enable this feature for individual Consoles (e.g. only PowerShell or PowerShell and cmd, ...).
The User should be able to add normal and Admin Terminal Tabs to the Window by just clicking on the Add Tab Symbol and selecting Admin or non-Admin consoles. 
The Terminal Tabs with admin Privileges should be clearly marked as Admin, maybe with a red color or a Symbol to make it easier for the User to navigate and tell them Apart.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Alas, as much as we'd like to do this, it's simply not going to be possible. 

See [this doc](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#elevation) for a bit more of the reasoning, as well as [Elevation Quality of Life Improvements](https://github.com/microsoft/terminal/blob/main/doc/specs/%235000%20-%20Process%20Model%202.0/%231032%20-%20Elevation%20Quality%20of%20Life%20Improvements.md#background). 

In 1.13, you can ctrl+click on a profile to launch it in a new elevated window automatically:
![image](https://user-images.githubusercontent.com/18356694/162817072-e2399cf5-1228-46db-8a1e-0398edab3a2c.png)

That's not really the same as putting the same window, but it's a little more convenient. /dup #1032
