### ISSUE TITLE
Dragging tabs results in MPC-BE playing

### ISSUE THREAD

**Issue by mbartlett21** [microsoft/terminal#12954]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.613

### Other Software

MPC-BE 1.6.1.6845 (https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.6.1/)

### Steps to reproduce

1. Open up an audio file with MPC-BE
2. Pause MPC-BE
3. Open up Terminal
4. Drag a tab in Terminal (it doesn't have to actually be dragged anywhere, just detached from its original position).

### Expected Behavior

MPC-BE to stay paused.

### Actual Behavior

MPC-BE starts playing again.

**Comment by zadjii-msft** [comment]
Hey sorry, this got lost in the triage queue. Does this repro with any of the tabs in the [WinUI 2 Gallery](https://www.microsoft.com/store/productId/9MSVH128X2ZT) app/? That app is a testbed for all the XAML controls, and it hasa  TabView page that should have some test tabs to play with:

![image](https://user-images.githubusercontent.com/18356694/213548109-7045a371-02f1-4b71-a2d8-3f57e599ad65.png)


I'm trying to rule out if this is a Terminal-specific thing, or a TabView-generic one.

**Comment by mbartlett21** [comment]
What appears to cause it is:
- dragging the tabs in Notepad or Explorer
- reordering the icons in the Control Centre / Quick Panel

However, these don't always reliably reproduce the bug (possibly one in MPC-HC)

I haven't yet installed the WinUI 2 app, but I suspect it would also cause it to play.

**Comment by kotenok2000** [comment]
Winui 2 does it too.
