### ISSUE TITLE
Open new tab next to the current one

### ISSUE THREAD

**Issue by liuerfire** [microsoft/terminal#12955]
# Description of the new feature/enhancement

Create a new tab to the be placed next the current tab instead of at the end.

# Proposed technical implementation details (optional)

the Kitty terminal: https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-location

Konsole:
![image](https://user-images.githubusercontent.com/745867/164386924-9c337b74-e9d8-4671-8324-b1053020ae5b.png)

**Comment by zadjii-msft** [comment]
* [x] Reasonable, well-defined behavior
* [x] simple enough setting design
* [x] existing precedent in other terminals

I don't think I could ask for a better feature request 😄

**Comment by BenConstable9** [comment]
@zadjii-msft can I try and tackle this one?

**Comment by zadjii-msft** [comment]
@BenConstable9 Go right ahead!
