### ISSUE TITLE
Since update 1.12.1098: unable to find font 'Cascadia Code'

### ISSUE THREAD

**Issue by sberthouzoz** [microsoft/terminal#12958]
### Windows Terminal version

1.12.10982.0 

### Windows build number

10.0.19044.1586

### Steps to reproduce

Start the application
Error message appears on startup

### Expected Behavior

no errors

### Actual Behavior

Error:
![image](https://user-images.githubusercontent.com/953741/164421314-174c7252-d72c-4fbc-8c56-5e8547042af7.png)

**Comment by j4james** [comment]
I suspect this might be the same bug as #12420, for which there is a pending fix (PR #12904).

**Comment by zadjii-msft** [comment]
Yea I'd be almost sure of it. I coulda swore we had already cherry-picked that one, but seems I was mistaken. Casual reminder for @DHowett to do the cherry-pick this morning when he wakes up.

/dup #12420

**Comment by sberthouzoz** [comment]
Thanks for your feedback.
As suggested in the root issue (following th duplicates) #11648 (following th duplicates), I could get rid of the warning by 'repairing' the app:

> Try "Repairing" the Terminal app, by going to "Settings > Apps > {whatever Terminal Install you have} > Advanced Options > Repair". This shouldn't delete your settings. (But "Reset" will, so be careful!)
