### ISSUE TITLE
The colors taken from the config are too bright for what they actually are

### ISSUE THREAD

**Issue by nlguerra2003** [microsoft/terminal#12957]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22598.0

### Other Software

No other programs are used

### Steps to reproduce

I have this colour scheme (based on the Brave Contrast VScode theme)
   ```
{
    "background": "#050607",
    "black": "#1B1E25",
    "blue": "#63A5A5",
    "brightBlack": "#3B4251",
    "brightBlue": "#8db6c9",
    "brightCyan": "#C3BCFF",
    "brightGreen": "#FF8C41",
    "brightPurple": "#C3BCFF",
    "brightRed": "#FF8C41",
    "brightWhite": "#FFFFFF",
    "brightYellow": "#C3BCFF",
    "cursorColor": "#F8F8F0",
    "cyan": "#908BBC",
    "foreground": "#D6DBDB",
    "green": "#BC4331",
    "name": "My Brave Contrast",
    "purple": "#908BBC",
    "red": "#BA0E2E",
    "selectionBackground": "#FFFFFF",
    "white": "#E4E7E7",
    "yellow": "#908BBC"
}
```
Working with this Powershell $PROFILE1 file:
```
function Check-IsElevated
{
  $id = [System.Security.Principal.WindowsIdentity]::GetCurrent()
  $p = New-Object System.Security.Principal.WindowsPrincipal($id)
  if ($p.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator))
    { Write-Output $true }      
  else
    { Write-Output $false }   
}

$curUser= (Get-ChildItem Env:\USERNAME).Value
$curComp= (Get-ChildItem Env:\COMPUTERNAME).Value

function prompt {
	if(Check-IsElevated)
	{Write-Host "┌" -nonewline -foreground red}
	else
	{Write-Host "┌" -nonewline}
	Write-Host " $curUser@$curComp" -nonewline -foreground blue
	Write-Host " $(Get-Location)" -foreground cyan
	if(Check-IsElevated)
	{
		Write-Host "└ PS " -foreground red -nonewline
		return "# "
	}
	return "└ PS $ "
}
```

### Expected Behavior

Since the outputted username and location are coded to be represented in blue and cyan, repectively, once they're printed the colors we see in the terminal should be #63A5A5 and #908BBC (again, respectively), looking at what is configured in the scheme.

### Actual Behavior

Instead of using the colors that are configured, (remember, #63A5A5 and #908BBC for blue and cyan respectively), if I use PowerToys' color picker I can see the colors used are #8db6c9 and #C3BCFF, just brighter variants of the coded colors.

I don't think I've configured anything that could change the color representation/perception, but any heads-up is appreciated.

**Comment by j4james** [comment]
The problem is that the colors in PowerShell are named in a backwards kind of way. `Blue` is actually bright blue, while `DarkBlue` is the regular blue.

**Comment by nlguerra2003** [comment]
Replacing every colour with their Dark variant made it work as intended. Thanks for such brief solution.
