### ISSUE TITLE
Using git bash in windows terminal can't cd into a git project folder!!!

### ISSUE THREAD

**Issue by NotGeekAtAll** [microsoft/terminal#12953]
### Windows Terminal version

1.13.10983.0(windows terminal preview)

### Windows build number

21H2(19044.1645)

### Other Software

- git version 2.35.1.windows.2，git bash
- zsh 5.8 (x86_64-pc-msys)

### Steps to reproduce

1. git clone some project
2. window termial use git bash
3. cd the project you just cloned

### Expected Behavior

cd into the project folder correctly

### Actual Behavior

- As you can see, bizplat-ui is a project using git version control,but I can't cd into the project folder,and terminal has no responding.

![image](https://user-images.githubusercontent.com/16792509/164364861-772131a1-537a-4166-b903-3e0a717fa88d.png)

- But when I just use git bash, I can cd into project folder correctly.

![image](https://user-images.githubusercontent.com/16792509/164365805-a856d34f-d5a6-4986-b62f-0228c1f30969.png)

- my windows terminal git bash config

![image](https://user-images.githubusercontent.com/16792509/164365416-84398f1a-c21a-4e91-87ac-852d24ff541c.png)

**Comment by zadjii-msft** [comment]
Does the `cd` work in an unelevated (not admin) window?

Can you `cd` into that directory in other shells (`cmd`, `powershell`, etc)/?

**Comment by NotGeekAtAll** [comment]
@zadjii-msft 

1. I can't `cd` whether is admit or not
2. I can  `cd` into the directory by powershell

**Comment by zadjii-msft** [comment]
> 2\. I can  `cd` into the directory by powershell

Well that's bizarre. That sure doesn't make sense. I wonder if there's some difference between just running git bash directly, and the `commandline` you have set for that profile. Does the same thing occur if you run `c:\Program Files\Git\bin\bash.exe -l -i` from the Run Dialog (<kbd>win+r</kbd>)/?

**Comment by NotGeekAtAll** [comment]
@zadjii-msft I've tried running c:\Program Files\Git\bin\bash.exe -l -i from the Run Dialog (win+r).It turns out that I can open it successfully. But still, I can't `cd` into `bizplat-ui` directory, and terminal has no responding.
![image](https://user-images.githubusercontent.com/16792509/165418053-f4316e4f-017c-47c3-8563-e2527d3a86f8.png)

**Comment by DHowett** [comment]
This is probably due to Git Prompt Integration. It is trying to read the git repository, and it cannot do that. So the prompt hangs.

This issue is outside of Terminal or Console's control. You may need to debug this with the Git For Windows project.

**Comment by Gluups** [comment]
Hello,
I had the problem just a moment ago.
I realized that `cd` is accepted in lowercase letters, and changes the current folder to the path given, whereas it is unknown in uppercase letters.

> User@UC00009 MINGW64 /c/Projects Visual Studio/WinForm
> $ CD ..
> bash: CD: command not found
> 
> User@UC00009 MINGW64 /c/Projects Visual Studio/WinForm
> $ cd ..
> 
> User@UC00009 MINGW64 /c/Projects Visual Studio
> $
>
