### ISSUE TITLE
Rainbow Frame

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12950]
Posted here so that we don't totally forget about this.

![rainbow-FRAME](https://user-images.githubusercontent.com/18356694/164307822-e4267965-2ce0-4294-8499-59c3ba7edbae.gif)

[`dev/migrie/fhl/rgb-rainbow-window-frame`](https://github.com/microsoft/terminal/compare/dev/migrie/fhl/rgb-rainbow-window-frame). I've got it hooked up to moving the window, obviously, that's contrived, so a 1/60th second timer somewhere would work well enough. 

I dunno what exactly this is, but we need it in the Terminal. Probably a special case of `window.frameColor` in #3327?

**Comment by Jayonics** [comment]
Important? 👎
Cool? 💯🌟🌈😲

**Comment by dansmor7** [comment]
Maybe you could make the window frame *be* anything: color, acrylic, image, composed image (corners, edges).

**Comment by 6H075T2** [comment]
how to do this?

**Comment by zadjii-msft** [comment]
@6H075T2 See: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#experimental-rainbow-window-border

**Comment by 6H075T2** [comment]
![image](https://github.com/microsoft/terminal/assets/79183240/035ed152-a2cb-456c-b497-3d41d3a246ec)
It doesn't work for me can you enlighten me please?

**Comment by zadjii-msft** [comment]
Ah, the rainbow frame setting isn't a global, it's a _theme_ setting. You need to make a new theme, and enable it for the theme. 

Try adding the following to the globals:

```jsonc

{
    // "profiles": { ... }
    // "schemes": [ ... ] 
    // "defaultProfile": ...
    // etc
    // etc
    
    "theme": "rainbow",
    "themes":
    [
        {
            "name": "rainbow",
            "window": 
            {
                "experimental.rainbowFrame": true,
            },
            "tab": {
                "background": "terminalBackground",
                "unfocusedBackground": "#00000000"
            },
        },
    ]
}

```
