### ISSUE TITLE
Unclear description, how to "Repair" in https://github.com/microsoft/terminal/issues/9375

### ISSUE THREAD

**Issue by turbanoff** [microsoft/terminal#12962]
There is wonderful known solution for font problem, described in the first post in #9375:

>choose to "Repair" the Terminal application in the "All apps" list in Settings.

I spent 15 minutes trying to find "Repair" button or "All apps" in application settings.
![image](https://user-images.githubusercontent.com/741251/164484337-ebd6e09e-8f3c-4338-93a6-1bf5aab26a70.png)

It would be nice to describe a bit more detailed, where to find this "Repair" button.

**Comment by zadjii-msft** [comment]
It's in the Settings app, not the Terminal settings UI. 

![repair-terminal-windows-11](https://user-images.githubusercontent.com/18356694/164486352-1f5e8288-605a-4f29-ac46-7621c30735a9.gif)


(the headers may have changed names slightly in Windows 11)
