### ISSUE TITLE
No obvious way to close full-screen after [process exited with code 1 (0x00000001)]

### ISSUE THREAD

**Issue by miklevin** [microsoft/terminal#12966]
### Windows Terminal version

1.13.10983.0

### Windows build number

Version	10.0.19043 Build 19043

### Steps to reproduce

Open Windows Terminal. Be in full-screen no-tabs mode because of user preferences in Settings (a good focused mode for working).

Connect to remote machine through PowerShell ssh program.

Allow to timeout with [process exited with code 1 (0x00000001)] error.

Now there is no obvious way to close the screen.

It is possible to close the screen by hitting Windows+Tab to get the Virtual Desktop view and then hit the "X" gadget from that user interface. But that is not obvious nor optimal.

### Expected Behavior

For there to be present some immediately obvious way to close a locked-up screen without using Virtual Desktop tricks or hitting Ctrl+F11 to exit full-screen mode manually just to close it. Maybe turning tabs back on or throwing up a close-gadget when [process exited with code 1 (0x00000001)] even in full-screen mode.

### Actual Behavior

One must hit Ctrl+F11 to get out of full-screen mode or Windows+Tab to get the Virtual Desktop interface in order to close a locked-up terminal as a result of a [process exited with code 1 (0x00000001)] error.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is probably best served by either /dup #11570 or /dup #5677
