### ISSUE TITLE
Excessive memory usage 

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/terminal#12964]
### Windows Terminal version

1.13.10984.0

### Windows build number

10.0.22000.0

### Other Software

rclone 1.57.0

### Steps to reproduce

Run rclone or something else that spews a bunch of things to the terminal, I caused it by having very verbose mode (-vvvv) turned on in rclone while scanning through a mounted cloud drive
Watch as Terminal grows its memory usage until Windows reaps it due to Resource Exhaustion 

### Expected Behavior

Nominal memory usage, maybe a bit higher than normal

### Actual Behavior

![image](https://user-images.githubusercontent.com/1053504/164485715-c14515a9-6e8c-41d8-89bb-6b39d6cb291a.png)
![image](https://user-images.githubusercontent.com/1053504/164485750-607ebdf6-17c7-4c49-9271-87940f7b8fb8.png)

**Comment by Masamune3210** [comment]
Maybe its a issue with the scroll buffer not getting pruned after a certain amount? 
![image](https://user-images.githubusercontent.com/1053504/164486975-3d71f923-fee0-4eeb-a71e-1ce74ed72c95.png)

**Comment by zadjii-msft** [comment]
Even if the Terminal had a SHRT_MAX sized buffer, it seems impossible that the memory usage would be in the _gigabytes_.....

Can you expando that "Terminal Preview" entry in the task manager to see the breakdown of how much memory each child process is using/?

**Comment by Masamune3210** [comment]
Also, not sure if Task Manager borked up or if something went wrong but rclone is no longer under the Terminal Preview split, its off floating in its own like a normal process would be instead of as a console app that would normally be under the Terminal

**Comment by zadjii-msft** [comment]
... how are there only three processes - yea there should be a shell somewhere under there.

**Comment by zadjii-msft** [comment]
Anywho, that doesn't look right. What the heck is leaking?

Can you take a dump of the terminal by right-clicking on the `windowsterminal` process in Task Manager?

**Comment by Masamune3210** [comment]
The memory usage isnt going back down, resource reaper will likely kick in soon and kill it
![image](https://user-images.githubusercontent.com/1053504/164490254-5833bf55-1202-483c-b2d9-3683398dec73.png)

**Comment by zadjii-msft** [comment]
ah hell well that's maybe problematically large to upload somewhere. NOt even sure that could get uploaded via feedback hub.

Does `rclone` output like, a LOT of hyperlinks? I'm trying to mentally figure out what could possibly leak memory like that 😨 Maybe a ton of emoji?

**Comment by Masamune3210** [comment]
I know its log can contain hyperlinks, usually whenever a hitch or error occurs because it prints the link it was trying to access when very verbose is turned on

**Comment by Masamune3210** [comment]
No accessibility features are enabled, no emoji. Would post a pic of the output but its private unfortunately since it deals with cloud syncing and has file names and paths

**Comment by zadjii-msft** [comment]
That's fine.

I'm just trying to isolate out the root cause here - in a fresh Terminal window, does `gci -recurse` (just print out enough text to saturate the buffer) cause the same kind of leak/? Just to try and isolate this to something that is `rclone`-specific or not

**Comment by Masamune3210** [comment]
Memory usage before 62.2MB
Memory usage after    81.7MB

**Comment by Masamune3210** [comment]
Thats after one run of the command

**Comment by Masamune3210** [comment]
If you can tell me what to look for in the dump I can try to take a look

**Comment by Masamune3210** [comment]
17 Threads
Not sure how to look at the TextBuffer unfortunately 
If needed I can chunk up the dmp using 7z and upload it somewhere, just might take a while given the file size

**Comment by lhecker** [comment]
I believe debugging a memory leak under Windows is usually done by enabling heap traces with gflags.exe. Here's a tutorial with screenshots I found: https://bugslasher.net/2011/08/09/how-to-troubleshot-native-memory-leaks-on-windows-gflags-and-umdh/
This is necessary as allocations won't be tracked with stack traces otherwise.

If you don't mind could you post your config file here?

**Comment by Masamune3210** [comment]
I will set a reminder but likely won't be able to get to it until tomorrow, I am at work currently. 

I'm still trying to nail down a cause or at least reproducible path to the bug, but I know it regularly comes up while mounting a Google drive account in rclone in very verbose mode and iterating through the file tree with another program which causes lots of log spew

I will try cmd tomorrow as well and see if I can reproduce anything. If it helps at all, I regularly leave terminal open for multiple days as I hibernate my computer instead of shutting down more often than not

You mean my terminal config file? If so yeah I'll try to post it tonight if I have time or tomorrow if I dont

**Comment by Masamune3210** [comment]
> I believe debugging a memory leak under Windows is usually done by enabling heap traces with gflags.exe. Here's a tutorial with screenshots I found: https://bugslasher.net/2011/08/09/how-to-troubleshot-native-memory-leaks-on-windows-gflags-and-umdh/ This is necessary as allocations won't be tracked with stack traces otherwise.

> Would you say that this command should reproduce the issue on my end?
> ```
> rclone.exe copy ./some/directory ./some_other/directory -vvvv
> ```
> 
> Is the issue reproducible if you use cmd.exe instead of PowerShell? Otherwise, if you don't mind, could you post your config file here?



> I believe debugging a memory leak under Windows is usually done by enabling heap traces with gflags.exe. Here's a tutorial with screenshots I found: https://bugslasher.net/2011/08/09/how-to-troubleshot-native-memory-leaks-on-windows-gflags-and-umdh/ This is necessary as allocations won't be tracked with stack traces otherwise.
> 
> Would you say that this command should reproduce the issue on my end?
> 
> ```
> rclone.exe copy ./some/directory ./some_other/directory -vvvv
> ```
> 
> Is the issue reproducible if you use cmd.exe instead of PowerShell? Otherwise, if you don't mind, could you post your config file here?

What process should I enable heap tracing on, the WindowsTerminal.exe?

This is the command I am using  
```
rclone mount "somegoogledriveaccount:" X: -vvvvvvvv --vfs-cache-mode full --cache-dir Z:\rclone --vfs-read-chunk-size 200M --vfs-cache-max-age 30m --vfs-cache-poll-interval 35m --attr-timeout 1h --drive-skip-gdocs --drive-skip-shortcuts --dir-cache-time 5h --transfers 2 --order-by 'size,ascending'
```

I will try this in a second as the leak is actually happening right now, hibernate maybe involved somehow as I couldn't get it to trigger yesterday after the report, but immediately triggered this morning after resume, but that could be a red herring 

[settings.zip](https://github.com/microsoft/terminal/files/8541181/settings.zip)
Here is my settings.json from Terminal

**Comment by lhecker** [comment]
> What process should I enable heap tracing on, the WindowsTerminal.exe?

Yep, WindowsTerminal.exe!

**Comment by elsaco** [comment]
@Masamune3210 using `rclone mount` with `Dropbox` there were no huge memory use spikes observed. Did not test against `Google Drive` or coming out of hibernation.

Here's rclone info:

```
PS C:\Tools\rclone> .\rclone.exe --version
rclone v1.58.0
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.1645 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount
```


Mount command with `--drive-skip-gdocs` option remove:

`PS C:\Tools\rclone> .\rclone.exe mount remote: X: -vvvvvvvv --vfs-cache-mode full --cache-dir C:\rclone --vfs-read-chunk -size 200M --vfs-cache-max-age 30m --vfs-cache-poll-interval 35m --attr-timeout 1h  --drive-skip-shortcuts --dir-cache-time 5h --transfers 2 --order-by 'size,ascending'`



And `Task Manager` sample reading:

![rclone_running](https://user-images.githubusercontent.com/3933920/164749813-9ad9498e-1829-4cf7-97ec-63748114726d.png)

**Comment by Masamune3210** [comment]
Debugging these seldom bugs is always frustrating, I'll see if I can't figure out more over the weekend

**Comment by lhecker** [comment]
What I don't quite understand why your WindowsTerminal.exe process is titled "PowerShell". It should look like this:
![image](https://user-images.githubusercontent.com/2256941/164769106-53d44393-cb5d-4b12-bbfb-2c857fbf9f8b.png)

**Comment by Masamune3210** [comment]
That's what I can't figure out either, and I'm wondering if these two things are somehow related. Somehow something is getting mangled causing something else to go haywire

**Comment by Masamune3210** [comment]
You can see in the config file, I'm just using PowerShell, maybe a bug in that particular version? But even then that shouldn't cause Terminal to go haywire like that would it?

**Comment by Masamune3210** [comment]
Got the weird Task Manager missing process thing again, seems to be related to keeping the Terminal open for a long period. Was fine before I left for work, left my computer on to process some things, when I got home it was like this
![image](https://user-images.githubusercontent.com/1053504/164885176-89d9f962-727f-431d-b6b8-2f6768c9c266.png)

**Comment by ianjoneill** [comment]
> What I don't quite understand why your WindowsTerminal.exe process is titled "PowerShell". It should look like this: ![image](https://user-images.githubusercontent.com/2256941/164769106-53d44393-cb5d-4b12-bbfb-2c857fbf9f8b.png)

I've just opened Terminal Preview 30 times. 8 times I saw "PowerShell", 2 times I saw "Windows Terminal" and the remaining 20 times I saw "WindowsTerminal.exe".

This would maybe suggest it could be a timing thing?

**Comment by elsaco** [comment]
@ianjoneill is the window title same as tab title? With two terminal windows, one elevated and the other one with two tabs, what's shown in the Task Manager is not quiet the same with what tab titles show:

![tm_wt_tabs_title](https://user-images.githubusercontent.com/3933920/164915793-14c12e3f-eb0e-4ab2-baf9-7d26ec4670cc.png)

I did use settings early, but there was no Settings tab opened when I took the screenshot. Manually selecting `View/Refresh now` in Task Manger did not change anything, or restarting Task Manager.

**Comment by Masamune3210** [comment]
Its seemingly just whatever window happens to be open at a certain time, opening a new window will cause the new process to have the correct name of WindowsTerminal.exe, but as far as I can tell nothing will cause the old process to have the correct name again

**Comment by zadjii-msft** [comment]
Yea, FWIW, I've seen the "Terminal has the wrong name sometimes in Task Manager" thing since the earliest days of the Terminal. That's likely just a red herring here. I'm gonna go through and collapse that part of the discussion, since that doesn't seem relevant to the bigger picture "wtf is causing this leak and why can't we repro this" issue.

**Comment by DHowett** [comment]
Alright, so this is a long shot. Since you seem to be reproducing this consistently, I wonder if you'd help me tell whether the 
"segment heap" (Windows' new heap implementation) helps with your outlandish memory usage.

As an Administrator:

```cmd
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\WindowsTerminal.exe" /v FrontEndHeapDebugOptions /t REG_DWORD /d 8
```

Restart all instances of Terminal.

If it helps, or even if it doesn't, I am considering enabling this for all Terminal users all the time.

**Comment by Masamune3210** [comment]
Will test tonight and over the weekend and let you know!

**Comment by Masamune3210** [comment]
Oops my bad, got busy with real life™ and haven't had a chance to test this yet. I'll try to test soon though

**Comment by Masamune3210** [comment]
I haven't seen the issue again since I added the new heap style, if I have the issue again I'll be sure to let everybody know
