### ISSUE TITLE
Acrilico / Transparencia no funciona 

### ISSUE THREAD

**Issue by JeronimoMr11** [microsoft/terminal#12976]
No se porque no funciona el acrílico en Windows Terminal si esta activado y la otra terminal que viene de por defecto si se activa la transparencia, ayuda.

**Comment by zadjii-msft** [comment]
Lo siento, no hablo español. Mis palabras pueden confundirse en la traducción automática. @carlos-zamora podría ayudar más.

"Acrílico" tiene su propia sección en nuestras preguntas frecuentes: https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#transparency

> Como política de todo el sistema, el acrílico solo está habilitado para la ventana de primer plano. Entonces, si activa cualquier otra ventana que no sea la Terminal, el acrílico de la Terminal se apagará.

¿Tiene eso algún sentido/?

**Comment by carlos-zamora** [comment]
> No se porque no funciona el acrílico en Windows Terminal si esta activado y la otra terminal que viene de por defecto si se activa la transparencia, ayuda.

@JeronimoMr11 Primero, recomiendo que leas esta seccion de la documentacion: https://docs.microsoft.com/es-mx/windows/terminal/customize-settings/profile-appearance#transparency. Eso debe de incluir detalles sobre el acrilico.

Si eso no resuelve el problema, necessitamos mas detalles por favor...
- Que version de Windows estas usando? Para checkar, usa `winver` en un terminal, y ahi debe de aparecer algo como esto...
<img width="163" alt="image" src="https://user-images.githubusercontent.com/11050425/165143431-22cf508b-b296-44b9-b609-58ffe369bcf6.png">
- Que version de Windows Terminal? Para checkar, abre el dropdown y preziona el boton que dice "Acerca de":
<img width="448" alt="image" src="https://user-images.githubusercontent.com/11050425/165144176-9787ecf0-b561-41a7-afae-20e4abb77fc6.png">
- Especificamente, a que te refieres cuando dices "la otra terminal"? Esta en otra ventanilla o un panel?
