### ISSUE TITLE
powershell instructions in README don't include deploying build

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1297]
OK so I've ran `Invoke-OpenConsoleBuild` and the build is done:
 
```
Build succeeded.

"C:\Users\mikem\Code\terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\mikem\Code\terminal\src\host\ft_uia\Host.Tests.UIA.csproj.metaproj" (default target) (34) ->
"C:\Users\mikem\Code\terminal\src\host\ft_uia\Host.Tests.UIA.csproj" (default target) (37) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Microsoft.Common.CurrentV
ersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "M
icrosoft.VisualStudio.QualityTools.UnitTestFramework". Check to make sure the assembly exists on disk. If t
his reference is required by your code, you may get compilation errors. [C:\Users\mikem\Code\terminal\src\h
ost\ft_uia\Host.Tests.UIA.csproj]

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:02:02.23
```

What do I run? I'm not familiar with .net, or VS solutions and the README doesn't say.

**Comment by mikemaccana** [comment]
Note the README *does* say 

> make sure you're building & deploying CascadiaPackage in Visual Studio

But I (and many others) have no idea how to do this (or why, since we already just built the app in powershell per the instructions).

It seems like there's a command missing in the powershell instructions, which tells us how to either a) install or b) run the Terminal.

**Comment by nntantidakis** [comment]
Right click on CascadiaPackage from Solution explorer and click Deploy. Then you will find Windows Terminal(Dev Build) in your Start Recently Added apps

**Comment by mikemaccana** [comment]
@nntantidakis Thanks. But that seems to do an unnecessary second build - we've already followed the powershell instructions which built the app, per the README. Is there a way I can install the app from powershell?

**Comment by zadjii-msft** [comment]
There's a bit more discussion on the topic in #855 - let's keep the discussion to that thread.
