### ISSUE TITLE
#Include statements for single file containing themes

### ISSUE THREAD

**Issue by vaskark** [microsoft/terminal#12989]
# Description of the new feature/enhancement

Not really to solve a problem, but having the ability to use #include statements for referencing another file i.e. a huge theme file. Just a thought :)

# Proposed technical implementation details (optional)

See above.

Unless it's already possible. If so, please delete.
Thanks. And thanks for the great app.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933

There was more discussion in #2303 as well, but that was effectively merged into #2933.
