### ISSUE TITLE
Give administrator privileges to tab

### ISSUE THREAD

**Issue by Fischchen** [microsoft/terminal#12985]
# Description of the new feature/enhancement

A possibility to change certain tabs to administrator rights.
Useful when you have to deal with package managers and similar.
# Proposed technical implementation details (optional)

An entry for that functionality in the CTL+SHIFT+P menu, which changes the current tab to administrator, or if that's not possible, creates a new one with administrator privileges.

**Comment by zadjii-msft** [comment]
This is something you can kinda already do today, but maybe not _that_ conveniently. As of 1.13, you can mark a profile as requiring elevation (admin rights), with `elevate:true`. You can also use that in a newTab action to open that profile elevated. So you could add something like:

```
        { "icon": "\uEA18", "command": { "action": "newTab", "elevate": true, "profile": "foo" } },
```

to open your foo profile as admin. Or just Ctrl+Click on the entry in the dropdown.

However, what you really want is "duplicate the current tab, with admin permission", and that's not tracked right now, I don't think. #10232 is sorta like it, but not exactly what I'm looking for. `splitPane` has `splitMode: duplicate`, maybe we need a flag like that for `newTab` (or just let `duplicateTab` accept the rest of a `NewTerminalArgs`

**Comment by ohenryx2** [comment]
If you put elevate:true in the settings.json file for a new tab definition, then that will cause a new Windows Terminal window to launch.  However, if you instead use sudo from the gsudo package, then you just get a new tab as expected.
`            {
                "commandline": "sudo %SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35ce-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "CMD Admin"
            },
`
The above will cause a new tab, with CMD elevated.

While this:
`            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35ce-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "elevate":true,
                "name": "CMD Admin"
            },
`
will instead launch a new Windows Terminal window, with an elevated command prompt.  Not an additional tab.  Neither method is wrong, just a matter of preference.  I like a new tab, not a new window, but YMMV.

**Comment by zadjii-msft** [comment]
_obliged to add:_ as awesome as `gsudo` is, there is a fairly trivial escalation of privilege attack that's possible with it, so use with caution. I'm gonna collapse both these as off topic to keep focused on the implementation of the original ask here. Thanks ☺️

**Comment by vertigo220** [comment]
Would it be possible to add a Terminal-specific command "sudo" so the user could type that, which would instruct Terminal to duplicate the tab as admin?

**Comment by zadjii-msft** [comment]
You know, I might just close this as /dup https://github.com/microsoft/sudo. Honestly, that's just the easiest user experience over all. 

(we'll work on shipping that out-of-band from the OS: https://github.com/microsoft/sudo/issues/57)
