### ISSUE TITLE
Fix common "wall of text" issue when commands generate lots of output

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#12983]
# Description of the new feature/enhancement

A common issue of many terminal is 'wall of text'. For example, the user runs a command, the command generates 4000 lines of text, and it's difficult to scroll, say, exactly to the beginning of the previous command to begin reading the output.

[Warp](https://www.warp.dev/) is a new terminal that purports to solve this issue ![image](https://user-images.githubusercontent.com/172594/165341634-d11a9d78-66c7-43ab-b7a0-161a6713347f.png). Windows Terminal should solve it too.  

# Proposed technical implementation details (optional)

I can't use Warp (it doesn't have a Windows version yet) but I propose a simple implementation would be to allow the user to specify their prompt, so pressing (some shortcut key) will return to the previous instance of that prompt.

```
______________________________________________________
$: ls /dir

(5000 lines of text)
______________________________________________________
$: (pressing somekeyboard combo goes to last instance of `$:`
```

There may be a better way though. Shell prompt could signal the terminal somehow (like the shell beep does).

**Comment by zadjii-msft** [comment]
Boy would you be interested in #12948 😉 

> ![gh-12948-scroll-between-marks](https://user-images.githubusercontent.com/18356694/164290677-ffaafe09-81c4-4181-a4b8-db79a8aed235.gif)
> _fig 4: scrolling between marks_


/dup #11000

**Comment by mikemaccana** [comment]
@zadjii-msft Yes, yes I would 💯
