### ISSUE TITLE
Path letters case is read from user input instead of real directory name

### ISSUE THREAD

**Issue by innomaxx** [microsoft/terminal#12991]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1645

### Steps to reproduce

- Open terminal in `%USERPROFILE%` directory
- Execute `cd dEsKTop` (or any other `Desktop` directory name variant except exact match)

  ![image](https://user-images.githubusercontent.com/40697586/165593895-ef31c32a-5892-493b-95c2-ce8977e754d5.png)

### Expected Behavior

The app shows real FS directory name instead of user input for `cd` command

### Actual Behavior

The app shows directory name from user input

**Comment by DHowett** [comment]
Thanks for the report! This looks like a PowerShell issue. Would you mind searching on [their repository](https://github.com/powershell/powershell)?
