### ISSUE TITLE
Shortcut to wt

### ISSUE THREAD

**Issue by tfiers** [microsoft/terminal#12996]
I used to be able to make shortcuts to open wt.
This was useful as you could give these shortcuts arguments (like launching a certain profile, `wt -p ..`), and put them wherever, like in the Startup directory of Windows. One use case: open a wt instance running a Jupyter Notebook server on boot.

Now all I can do is open this generic looking 'App' without icon, and I cannot make shortcuts to it:
<img src="https://user-images.githubusercontent.com/3773558/165789885-9d2552a9-71d4-4626-93ea-b0e96bc9c978.png" width=500px>

wt version 1.12.10982.0, win build 10.0.19043.0

**Comment by tfiers** [comment]
There doesn't seem to be an option to create a shortcut (eg desktop shortcut):
<img src="https://user-images.githubusercontent.com/3773558/165832065-93c741ac-018d-4103-9807-2789eb7b6561.png" width=600px>
("Share" is just for copying a link to wt in Microsoft Store).

this "Packaged application" thing is a regrettable move away from file-based computing and end-user customizability

**Comment by zadjii-msft** [comment]
_Editorialization aside_, you can always just make a plain old shortcut to `wt.exe` manually:

![image](https://user-images.githubusercontent.com/18356694/165833708-7b28f6ed-fb30-4301-a74c-1091bc6b0bb7.png)

That's a shortcut on my desktop that runs `wt` with a whole pile of subcommands to open a bunch of profiles. And sure enough, PT Run can find it:

![image](https://user-images.githubusercontent.com/18356694/165833941-9eebb575-4057-4594-a9e3-2be5e405fc8a.png)

**Comment by tfiers** [comment]
awesome, thanks for the prompt replies and solution!

**Comment by tfiers** [comment]
And yeah my apologies, I'll try to stick to facts and no opinions :p

**Comment by tfiers** [comment]
Trying to find wt.exe, found something interesting:
- The background explorer window is the actual location and version of wt (what I find if I search Start for `wt.exe`).
- The foreground explorer window is what I get if I click "open containing folder" on Windows Terminal in PowerTools Run.
![image](https://user-images.githubusercontent.com/3773558/165840231-7b5a1b0f-280b-4f73-87e4-b1d58c2766b7.png)
..but interestingly, just clicking that entry in PT Run does open the correct/newest version (1.12).
So yeah might indeed be a PT Run issue.
Also possibly related to https://github.com/microsoft/terminal/issues/12344#issuecomment-1029293183 indeed.

**Comment by jacob-pro** [comment]
Unfortunately manually creating a shortcut also leads to a bug, when you pin the shortcut to taskbar, and open it, for some reason Windows associates it as a separate entry on the taskbar

(Left is the created shortcut to wt.exe, Right is what opens when you click it)

![image](https://user-images.githubusercontent.com/16433349/172268084-3afd631d-f9d7-4452-a281-3ecd3544c919.png)

I would really like to be able to create shortcuts with custom starting directories, in order to fix this: https://github.com/microsoft/terminal/issues/13195
