### ISSUE TITLE
Default background image setting do not take effect after cancel profile's background

### ISSUE THREAD

**Issue by nidbCN** [microsoft/terminal#12990]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.2.3

### Steps to reproduce

Set background of a specific profile (such cmd), save.
Unset profile's background, save.
![image](https://user-images.githubusercontent.com/36162655/165584758-10e6ee90-f9eb-40d9-8199-14efa69bd46c.png)
Configure background image of default profile, this profile's background img doesn't take effect to specific profile. 
![image](https://user-images.githubusercontent.com/36162655/165584838-da953921-a11b-469e-838c-4957b682cb35.png)
![image](https://user-images.githubusercontent.com/36162655/165584859-a1513ad4-f405-4f4b-b749-c99834ec692e.png)

### Expected Behavior

Configure default should take effect to all profiles which has no background image configured. 

Actually windows terminal remain a `null background image` prop (`"backgroundImage": null,`) which cause default cannot cover this empty configuration.

Windows Terminal should delete this prop instead of simply assign it to null

### Actual Behavior

Configure default profile's background image take no effect to profile which has been configured before.

**Comment by DHowett** [comment]
To properly reset this setting, you will need to click the ↩️ button. This is intentional, because we want to offer the ability for a profile to *delete* the background image that it inherited.

**Comment by nidbCN** [comment]
Thanks for your reply. It confuse me for a long time.
In my option, this design is not directly enough
