### ISSUE TITLE
Unable to autostart terminal in quake mode.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/terminal#12994]
# Description of the new feature/enhancement

IN settings i unable to set quake mode for autostart. 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/801951/165733045-0fb3168a-fc8f-4e75-a0b1-fc5e1fa40a34.png">
All of them are open real terminal. But I need to launch terminal in quake mode which will be hidded by default.

Currently terminal launched in open state. But I need to open it by hotkey only.

# Proposed technical implementation details (optional)

1 windows start
2 terminal launched in quake mode, in hidden state
3 when I need - I press hotkey (Win + ~) and quake terminal appears.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9996 for more discussion.

/dup #9996
