### ISSUE TITLE
Issues with experimental.useBackgroundImageForWindow

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#13002]
* [x] When the background is set on `profiles.defaults`, it does not apply (the entire window is transparent and all backgrounds are dropped)
* [x] Closing/opening panes of the same type causes the background image to flicker
* [x] The settings preview control no longer displays a background; we might want to ensure that it _overrides_ the setting that drops out the background
* [x] `desktopWallpaper` doesn't work at all 
* [x] Switching between two profiles with the same bg image flashes at you

**Comment by zadjii-msft** [comment]
* That was probably me - I think I recommended just looking it up out of the profile instead of building a whole ControlSettings
* This should be easy enough to cache the value of the path and only change if different. I think the control already does something similar (or is that tab icon paths?)
* good catch

**Comment by rashil2000** [comment]
> * [x]  When the background is set on `profiles.defaults`, it does not apply (the entire window is transparent and all backgrounds are dropped)

I just updated to 1.14 today (Windows 11 Build 10.0.22621.1) and I'm still facing this issue. Could this be reopened? Or should I create a new issue?

![image](https://user-images.githubusercontent.com/46838874/172036715-c6c4a531-9351-4efb-84d7-e02bbdf56b2b.png)

<details>
<summary>
My settings.json file:
</summary>
<pre>
{
  "$help": "https://aka.ms/terminal-documentation",
  "$schema": "https://aka.ms/terminal-profiles-schema",
  "actions": [
    {
      "command": "toggleFocusMode",
      "keys": "shift+f11"
    },
    {
      "command": "toggleShaderEffects",
      "keys": "shift+f10"
    }
  ],
  "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
  "initialCols": 90,
  "useAcrylicInTabRow": true,
  "theme": "light",
  "tabSwitcherMode": "mru",
  "experimental.useBackgroundImageForWindow": true,
  "profiles": {
    "defaults": {
      // "acrylicOpacity": 0.8,
      // "useAcrylic": true,
      // "experimental.pixelShaderPath": "%UserProfile%\\Pictures\\crt.hlsl",
      "antialiasingMode": "cleartype",
      "bellStyle": "none",
      "intenseTextStyle": "bold",
      "colorScheme": "some-light",
      "backgroundImage": "%UserProfile%\\Documents\\Wallpapers\\light.jpg",
      "backgroundImageOpacity": 0.2,
      "fontFace": "Consolas NF",
      "padding": "16, 16, 0, 16",
      "cursorShape": "filledBox"
    },
    "list": [
      {
        "colorScheme": "Bluloco Light",
        "font": {
          "face": "Delugia",
          "features": { "salt": 1 }
        },
        "tabColor": "#f9f9f9",
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}"
      },
      {
        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "startingDirectory": ".",
        "name": "Command"
      },
      {
        "colorScheme": "Tango Light",
        "commandline": "fish",
        "guid": "{17da3cac-b318-431e-8a3e-7fcdefe6d114}",
        "fontFace": "ClincherCode NF",
        "fontSize": 11,
        "icon": "%UserProfile%\\Pictures\\Icons\\fish.ico",
        "name": "Fish"
      },
      {
        "commandline": "nvim",
        "fontFace": "RecMonoSemicasual NF",
        "fontSize": 11,
        "colorScheme": "Tango Light",
        "padding": "16, 16, 16, 16",
        "scrollbarState": "hidden",
        "guid": "{9f80d682-c62b-40a3-a8f3-40996da15ef2}",
        "icon": "%UserProfile%\\Pictures\\Icons\\neovim.ico",
        "name": "Neovim"
      },
      {
        "commandline": "vifm .",
        "fontFace": "VictorMono NF",
        "fontSize": 11,
        "fontWeight": "semi-bold",
        "colorScheme": "Tango Light",
        "padding": "16, 16, 16, 16",
        "scrollbarState": "hidden",
        "guid": "{9f44d682-c62b-40a3-a8f3-40996da15ef2}",
        "icon": "%UserProfile%\\Pictures\\Icons\\vifm.ico",
        "name": "Vifm"
      },
      {
        "commandline": "gsudo btm",
        "fontFace": "OperatorMono NF",
        "fontSize": 11,
        "fontWeight": "semi-bold",
        "padding": "16, 16, 16, 16",
        "scrollbarState": "hidden",
        "guid": "{9f80d682-c78b-40a3-a8f3-40996da15ef2}",
        "icon": "%UserProfile%\\Pictures\\Icons\\top.ico",
        "name": "Bottom"
      },
      {
        "commandline": "spt",
        "fontFace": "FantasqueSansMono NF",
        "fontSize": 13,
        "colorScheme": "Bluloco Light",
        "tabColor": "#f9f9f9",
        "padding": "16, 16, 16, 16",
        "scrollbarState": "hidden",
        "guid": "{9f80d682-c62b-12a3-a8f3-40996da15ef2}",
        "icon": "%UserProfile%\\Pictures\\Icons\\spotify.ico",
        "name": "Spotify TUI"
      }
    ]
  },
  "schemes": [
    {
      "name": "Bluloco Dark",
      "background": "#0D1117",
      "black": "#4A505D",
      "blue": "#285BFF",
      "brightBlack": "#61697A",
      "brightBlue": "#199FFD",
      "brightCyan": "#50ACAE",
      "brightGreen": "#37BD58",
      "brightPurple": "#FC58F6",
      "brightRed": "#FC4A6D",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#F6BE48",
      "cursorColor": "#FFFFFF",
      "cyan": "#366F9A",
      "foreground": "#ABB2BF",
      "green": "#23974A",
      "purple": "#8C62FD",
      "red": "#F81141",
      "selectionBackground": "#FFFFFF",
      "white": "#A1B8DF",
      "yellow": "#FD7E57"
    },
    {
      "name": "Bluloco Light",
      "background": "#f9f9f9",
      "black": "#373a41",
      "blue": "#275fe4",
      "brightBlack": "#676a77",
      "brightBlue": "#0099e1",
      "brightCyan": "#6d93bb",
      "brightGreen": "#3cbc66",
      "brightPurple": "#ce33c0",
      "brightRed": "#ff6480",
      "brightWhite": "#d3d3d3",
      "brightYellow": "#c5a332",
      "cursorColor": "#f32759",
      "cyan": "#27618d",
      "foreground": "#373a41",
      "green": "#23974a",
      "purple": "#823ff1",
      "red": "#d52753",
      "selectionBackground": "#111111",
      "white": "#babbc2",
      "yellow": "#df631c"
    },
    {
      "name": "some-light",
      "background": "#FFFFFF",
      "black": "#FFFFFF",
      "blue": "#3971ED",
      "brightBlack": "#B4B7B4",
      "brightBlue": "#969896",
      "brightCyan": "#E013D0",
      "brightGreen": "#E0E0E0",
      "brightPurple": "#282A2E",
      "brightRed": "#F96A38",
      "brightWhite": "#1D1F21",
      "brightYellow": "#C5C332",
      "cursorColor": "#000000",
      "cyan": "#149BDA",
      "foreground": "#373B41",
      "green": "#198844",
      "purple": "#A36AC7",
      "red": "#CC342B",
      "selectionBackground": "#000000",
      "white": "#373B41",
      "yellow": "#FBA922"
    }
  ]
}
</pre>
</details>

**Comment by DHowett** [comment]
@rashil2000 hmmmmm just a hunch, but what happens if you replace the environment variable with the actual path?

**Comment by rashil2000** [comment]
The `"%UserProfile%\\Documents\\Wallpapers\\light.jpg"` is actually a symlink. So far all of these produce the same result
```
    "%UserProfile%\\Documents\\Wallpapers\\light.jpg"
"C:\\Users\\<user>\\Documents\\Wallpapers\\light.jpg"
               "E:\\Documents\\Wallpapers\\light.jpg"                              // actual path
```

**Comment by zadjii-msft** [comment]
I'm still not sure that we need to re-open this one, I suspect that #13090 still hasn't actually been pushed to the Store builds yet. (I have been OOF for the past week so I may be totally wrong there)

**Comment by lhecker** [comment]
I tested this again with `desktopWallpaper`, normalized paths and paths with environment variables and all of them worked in 1.14.1433.0.
