### ISSUE TITLE
Add --shell-arguments to Windows Terminal CLI

### ISSUE THREAD

**Issue by exo-pla-net** [microsoft/terminal#13004]
Currently, using the Windows Terminal CLI, you can easily send launch arguments to PowerShell or cmd.exe.

For example,  you can pass the command "pause" to PowerShell or cmd.exe as so:
`wt PowerShell -c pause`
or
`wt cmd /k pause`

However, for shells that don't exist in the PATH, you have to write out the full path of the shell's .exe, like this:
`wt "C:/Program Files/Git/bin/bash.exe" -c nano`

To make launch arguments more convenient, I suggest the new CLI feature:
`wt --shell-arguments [yourLaunchArguments]`

Now we can send arguments to any given profile, without having to dredge up the shell's file path:
`wt -p "Git Bash" --shell-arguments "-c nano"`

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5528 for more discussion.

/dup #5528
