### ISSUE TITLE
nerd font(inconsolata NF) issues

### ISSUE THREAD

**Issue by RedemptionC** [microsoft/terminal#13009]
### Windows Terminal version

1.12.10982.0

### Windows build number

 10.0.19044.1645

### Steps to reproduce

input `fi`

### Expected Behavior

shows `fi`

### Actual Behavior

shows telephone glyph like this
![image](https://user-images.githubusercontent.com/17563754/166132863-35cc2eff-72c4-4418-a140-af6457e45e68.png)

**Comment by DHowett** [comment]
Thanks for the report! This is a well known issue in that font. 

/dup https://github.com/ryanoasis/nerd-fonts/issues/509
