### ISSUE TITLE
version "1.12.10983.0" will appear in winget upgrade but can`t be installed (Win10)

### ISSUE THREAD

**Issue by ali50m** [microsoft/terminal#13008]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.0

### Steps to reproduce

precondition: winget installed.

1. installed the latest version (1.12.10982.0) for win10.
2. run "winget upgrade" in WindowsTerminal, you will see the avaiable "1.12.10983.0" for Microsoft.WindowsTerminal. But you can`t upgrade to this version, seems it`s the only for Win11.

### Expected Behavior

Please don`t display this upgrade on Win10 terminal, if it can`t be installed. I always keep my "winget upgrade" clean. But this upgrade of unsupported is annoying.

### Actual Behavior

The un-supported version "1.12.10983.0" displayed when running "winget upgrade" in Win10 terminal.

**Comment by DHowett** [comment]
I'm sorry, we do not control how WinGet displays updates. You will have to take this up on their repository.
