### ISSUE TITLE
Active/passive tab contrast is very low by default

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1301]
Using today's git master:

![image](https://user-images.githubusercontent.com/172594/59627319-d8511f00-9135-11e9-88eb-671ffab23fb3.png)

The contrast between the advice and passive tabs is very low which makes it hard to find the active tab. Compare to Edge insiders:

![image](https://user-images.githubusercontent.com/172594/59627355-f028a300-9135-11e9-82d8-ab9a03d5e5ad.png)

Fluent Terminal is a UWP app that does a good job, using the accent color from the Windows UI:

![image](https://user-images.githubusercontent.com/172594/59627545-6200ec80-9136-11e9-9649-2d420a6510be.png)

**Comment by zadjii-msft** [comment]
Didn't you file _the exact same issue_ in #771?
