### ISSUE TITLE
Deleting a (last?) profile in the SUI sends the Terminal to a farm upstate

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13017]
1. Make a new blank profile
2. Save the settings
3. Head over to	that "delete profile" button and hit it
4. [**ZOOP**](https://www.oocities.org/~robink/zoop.jpg), no Terminal

Stack was useless - something above a `DispatcherLoop` with a `ReportUnhandledError` about a "The application attempted to access data outside the valid range" but I apparently don't have `!xamlstowed` installed anymore.

**Comment by PankajBhojwani** [comment]
I cannot repro this on current main nor on preview (1.14.891.0). Do you consistently hit this or only sometimes?

**Comment by zadjii-msft** [comment]
Okay, got it to hit the _second_ time I tried this. First time, no repro. Second time, I made the Terminal wide enough that the nav view was in its expanded state, and then the terminal died on the delete.

**Comment by zadjii-msft** [comment]
Gosh I can't find it now, but we had some crash in the past about changing the elements of a nav view. Something about the vector of items.... @carlos-zamora  do you remember what I'm thinking of?

**Comment by zadjii-msft** [comment]
```c++
        // Add an event handler for when the user wants to delete a profile.
        profile.DeleteProfile({ this, &MainPage::_DeleteProfile });
```


I'd bet we're adding the delete handler TWICE. Stepping through `MainPage::_DeleteProfile`, the first time it succeeds, but then there's a SECOND call to that handler. Why is there a second call? That's not right.


It might mean that the repro is
1. Make a new blank profile
2. Save the settings
3. Click on the profile ABOVE the new profile
4. Click back to the new profile
5. Head over to	that "delete profile" button and hit it
6. [**ZOOP**](https://www.oocities.org/~robink/zoop.jpg), no Terminal
