### ISSUE TITLE
make the cross black when the tab is colored with a light color

### ISSUE THREAD

**Issue by d4rckh** [microsoft/terminal#13010]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. create a new tab
2. color it to cyan 
![image](https://user-images.githubusercontent.com/35298550/166144699-fe870c15-1fc1-476c-98cc-70a69722bd2f.png)

### Expected Behavior

the cross in the tab should be black, same as the tab name

### Actual Behavior

the cross is white
![image](https://user-images.githubusercontent.com/35298550/166144719-98987edf-90ea-4ddd-b8b5-440e44151daf.png)

**Comment by zadjii-msft** [comment]
Good catch! I bet this regressed when we moved to Controlsv2.
