### ISSUE TITLE
misalignment when using Lucida console with tmux 

### ISSUE THREAD

**Issue by hillysong** [microsoft/terminal#13011]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1645

### Other Software

wsl + ubuntu 20.04
tmux 3.0a

### Steps to reproduce

run ubuntu on wsl
set font as Lucida console
run tmux and split vertically

### Actual Behavior

![screenshot](https://user-images.githubusercontent.com/7812284/166146704-4a7d3b60-d8e4-45e6-94dd-3ef48506ec66.png)

**Comment by zadjii-msft** [comment]
Hmm, I can't get this to repro on 1.14 or on 1.12.10983.0....

![image](https://user-images.githubusercontent.com/18356694/166221170-df510141-460b-4e40-b6d0-c664d6e527fb.png)

Admittedly though, I've got tmux 2.6 cause I've got a 18.04 installed. I can try again with 3.0 later, but I'm thinking it's probably not a tmux issue.

Does this repro with any other fonts?
What shell are you using?
DO you have anything in your tmux config/?

**Comment by pupasong** [comment]
> Hmm, I can't get this to repro on 1.14 or on 1.12.10983.0....
> 
> ![image](https://user-images.githubusercontent.com/18356694/166221170-df510141-460b-4e40-b6d0-c664d6e527fb.png)
> 
> Admittedly though, I've got tmux 2.6 cause I've got a 18.04 installed. I can try again with 3.0 later, but I'm thinking it's probably not a tmux issue.
> 
> Does this repro with any other fonts? What shell are you using? Do you have anything in your tmux config/?

As far as I know, you can only experience it on the lucida console.
I'm using bash.
It reproduces even without .tmux.conf.

**Comment by zadjii-msft** [comment]
Which font size are you using? Actually, it might be easiest if you could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by pupasong** [comment]
> Which font size are you using? Actually, it might be easiest if you could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

9 or 10, both can see the misalignment. If you cannot see it on tmux 3.0a and ubunut 20.04, I'll share my json.

**Comment by zadjii-msft** [comment]
Crazy - on my 100% dpi monitor, I get no lines at all, ala #9235. On my 125% monitor, everything looks fine.

I'm betting this is ultimately the same root cause - gridlines getting stretched and shrank and eventually disappearing altogether. I'm gonna close as a dupe and make that thread a bit more generic. Thanks!

/dup #9235
