### ISSUE TITLE
Can not Set installed Font for Terminal Profile

### ISSUE THREAD

**Issue by meehr** [microsoft/terminal#13021]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22610.1

### Other Software

VS Code 1.66.2

### Steps to reproduce

open WT 
press CTRL + ,  for Setting
select default profile
select appearance
select fontface
select font ( i want use hack nerd font mono from https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip )
save

### Expected Behavior

Use Font Settings

### Actual Behavior

Restart and then i become Error 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1917698/166305175-cea0d476-c9e3-4f6c-9de0-db08d5746fd5.png">

**Comment by meehr** [comment]
I have tested with 10 ore more diffrent Fonts all the same.
In other Application  Word, VSCode etc... 
i can use them

**Comment by zadjii-msft** [comment]
Have you installed the font(s) for all users/? This reminds me of https://github.com/microsoft/terminal/issues/12587, which pointed at #3257

**Comment by meehr** [comment]
Thank You for help
i forget install fonts for all User and started Terminal as Admin. 
Excuse this
