### ISSUE TITLE
Powerline glyph does not fill whole 'cell' / 'box' height

### ISSUE THREAD

**Issue by Finii** [microsoft/terminal#13029]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1645

### Other Software

Cascadia Code 2111.01

### Steps to reproduce

* Install static `Cascadia Code PL Regular` [1]:
  * `ttf/static/CascadiaCodePL-Regular.ttf` or
  * `otf/static/CascadiaCodePL-Regular.otf`
* Use it as font with 12 pt
* Utilize the powerline glyphs like so (copy and paste into command prompt terminal window):
  `set prompt=$E[0;33;40m$E[7;33;40m Manuel $E[0;33;40m$E[7;32;40m  ~ $E[0;32;40m$E[7;34;40m  $E[0;34;40m$E[0;37;40m $g`

[1] https://github.com/microsoft/cascadia-code/releases/tag/v2111.01

### Expected Behavior

The upper and lower 'border' of the powerline glyphs shall line up with the 'cell' top and bottom.
Cell top and bottom can be seen if insert a blank with reverse colors (like done in the prompt command above).

This is how it should look like, roughly (magnified 400%):

![image](https://user-images.githubusercontent.com/16012374/166445737-77ba0a2d-1d9a-4c89-b511-1afcdf598234.png)

### Actual Behavior

The glyphs are about 1 pixel to small vertically; here with the `otf` one pixel at the bottom seems to be missing:

![image](https://user-images.githubusercontent.com/16012374/166445966-9c06e4aa-56a2-43df-aa43-320bcce82eb8.png)

This is most notable with the rounded D shape powerline symbols, but in fact are present in all.

![image](https://user-images.githubusercontent.com/16012374/166446192-519be1ba-74de-4d61-8ea0-d6c92805f921.png)

The static `ttf` seem to have the missing pixel in the top.
I did not try the VF.

Origin of issue: Bottom (after closing) https://github.com/ryanoasis/nerd-fonts/issues/828

I believe this is not a Cascadia Code issue, because the original issue came up with a Nerd Font patched version of that font (Caskaydia Cove); and in the process of that issue I tried a lot like ascent and descent changing (all of them OS/2, typo, Win etc ;), PPEM modification, etc pp, all to no avail.
I do not really know how `Windows Terminal` finds out its cell size. If one understands that maybe the font can be beat into function. But I fear that it is a rendering issue, as this is always 1 px big, regardless of font size in point.

_Edit: Fix typo_

**Comment by zadjii-msft** [comment]
Admittedly, you're probably using the default DX renderer, but I wonder if we fixed this for the Atlas engine in #13549, /cc @lhecker

**Comment by lhecker** [comment]
@zadjii-msft It looks terrible!

![image](https://user-images.githubusercontent.com/2256941/182234716-65f97c15-3dcc-4cd9-8c54-b7d74d88ed0e.png)

The lines occur because I subtract an extra 1px when downsizing glyphs and I did that in response to https://github.com/microsoft/terminal/pull/13549#issuecomment-1191466896
This situation is definitely a bit annoying! 😅
