### ISSUE TITLE
Quake mode renders drop shadow in final destination, even when expanding

### ISSUE THREAD

**Issue by theNailz** [microsoft/terminal#13027]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Steps to reproduce

* Summon a quake terminal, preferrably on a light background
* The shadow appears halfway down your screen while the terminal is still expanding.

I can't make a screen recording right now and slow it down, but it might also be more obvious if you set the dropdown timer to something like a few seconds.

### Expected Behavior

See the drop shadow under the terminal window.

### Actual Behavior

The drop shadow is rendered in the final position, even when the terminal is still expanding.

**Comment by zadjii-msft** [comment]
Yea, kinda a known issue. The animation could be better, for sure. We're tracking this generally in two parts of #8888, but mainly in /dup #12293. Thanks!
