### ISSUE TITLE
Drag is not working in wsl vim

### ISSUE THREAD

**Issue by brainos233** [microsoft/terminal#13030]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.0

### Other Software

vim 8.2.4827 (Arch Wsl)

### Steps to reproduce

1. Start Vim 
```
vim --clean +'set mouse=a' +'call popup_create("test", #{drag: 2, border: [2,2,2,2]})' +'split'
```
2. Try dragging the statusline and the popup

### Expected Behavior

In wsltty:
![aa1](https://user-images.githubusercontent.com/36539925/166448656-a36ae18f-8c6c-4569-ad11-003e3196b029.gif)

### Actual Behavior

In wt:
![aa2](https://user-images.githubusercontent.com/36539925/166449020-6cd3ba75-ae5f-49ab-b992-454022ebc469.gif)

**Comment by zadjii-msft** [comment]
Hmm. I wonder which mouse sequence this is using that we don't support. It's not supported in conhost either, but tmux mouse dragging does seem to still work.
