### ISSUE TITLE
Taskbar Entry is not associated to Terminal Preview

### ISSUE THREAD

**Issue by neersighted** [microsoft/terminal#13042]
### Windows Terminal version

1.13.10984.0

### Windows build number

120.0.22000.652

### Steps to reproduce

Launch Terminal Preview (installed from the Microsoft Store) on Windows 11. Pin it to the taskbar, and then restart explorer or reboot.

### Actual Behavior

The Terminal loses its icon in the taskbar, and the taskbar entry for both a pinned-but-not-running and an unpinned-and-running terminal is no longer associated with Terminal Preview -- instead it becomes a generic shortcut to 'App'.

![image](https://user-images.githubusercontent.com/1049222/166930982-62db9949-dfac-40fb-90d6-038ed6c9033a.png)

![image](https://user-images.githubusercontent.com/1049222/166931191-5c4f4a9c-4adc-4f1b-ba6c-24ad15d438ff.png)

![image](https://user-images.githubusercontent.com/1049222/166931219-bb9b3c41-f15c-4b5e-8d18-164e90d58f2a.png)

**Comment by zadjii-msft** [comment]
Well, that's sure weird. I don't even think a Feedback Hub trace could repro that, cause you'd have to restart during the trace. That obviously wouldn't work.

I've filed MSFT:39428529 upstream to track this. I don't think there's anything more we can do here terminal-side, but I'm following the internal bug and can report back here if we learn anything!
