### ISSUE TITLE
The problem of font render 

### ISSUE THREAD

**Issue by aleigood** [microsoft/terminal#13040]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.652

### Steps to reproduce

1. Change font (select "Source Cascadia", download from :https://github.com/aleigood/Hybrid-Font/blob/main/Source%20Cascadia%20Medium.ttf)
2. Type: "file"

### Actual Behavior

![动画](https://user-images.githubusercontent.com/3367999/166868646-fd201157-2aef-4b57-bfd2-29a76d565307.gif)

if "i" is not after of "f", it's mormal:

![image](https://user-images.githubusercontent.com/3367999/166868861-53005afb-904f-4e07-ac31-0140822a2ea4.png)

**Comment by zadjii-msft** [comment]
Looks like your font has a `fi` ligature configured, which the Terminal is dutifully rendering as a single glyph (despite taking up two columns). You should probably file this upstream on the font itself.
