### ISSUE TITLE
use new Windows Store link

### ISSUE THREAD

**Issue by wbsdty331** [microsoft/terminal#13056]
Microsoft has announced a new website for Windows Store (https://apps.microsoft.com), but https://aka.ms/terminal still use old link : `https://www.microsoft.com/p/windows-terminal/9n0dx20hk701`

![image](https://user-images.githubusercontent.com/4280572/167278135-75601d61-f31a-42da-a54a-ba14d1393d3f.png)

Now It's time to change it:
`https://aka.ms/terminal` should redirect to `https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701`

![image](https://user-images.githubusercontent.com/4280572/167278156-b8a9fe6d-e1ce-47a8-87c2-525352704fdc.png)

**Comment by zadjii-msft** [comment]
Huh, I hadn't heard of that. These are surprisingly different sites... For example, the `apps.microsoft` one doesn't have the whole banner video at the header. It kinda seems like the `apps.microsoft` URL has a little less information immediately presented to the user. 

Is there a specific reason to use the new URL over the old one/? 

@cinnamon-msft as an FYI

**Comment by zadjii-msft** [comment]
So, I reached out to the Store team - looks like in the near future the old URLs will automatically start redirecting to the new site, but the official recommendation currently is to leave the URL as-is. Thanks for the heads up - TIL about that new site.
