### ISSUE TITLE
Cross compilation to Linux

### ISSUE THREAD

**Issue by Pika-Pool** [microsoft/terminal#13057]
# Description of the new feature/enhancement

Huge fan of **Windows Terminal**. My job needs me to use Linux(Ubuntu) though. Is there any way to cross compile to run on Linux? Maybe provide a release asset for Linux too?

Would be huge if Windows terminal could be run on a linux distro!! Thanks

**Comment by j4james** [comment]
This is answered in [the FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#what-about-porting-the-windows-terminal-to-macos-or-linux):

> ### What about porting the Windows Terminal to MacOS or Linux?
> Windows Terminal requires a good number of Windows-specific technologies. We unfortunately won't be supporting it on Mac or anywhere else any time soon.

**Comment by Pika-Pool** [comment]
Thanks for pointing that out
