### ISSUE TITLE
[High Contrast] Actions page actions should probably be rendered in a little container

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#13068]
<img width="295" alt="GetImage" src="https://user-images.githubusercontent.com/11050425/167471721-b7f4d353-bb99-4960-a74c-799a4f8417d1.png">

**Comment by zadjii-msft** [comment]
Should this just get rolled in to #13065 and #12388?

**Comment by carlos-zamora** [comment]
> Should this just get rolled in to #13065 and #12388?

Eh. Yeah, probably #12388

**Comment by zadjii-msft** [comment]
Alrighty,  #13065 was merged, so we're just gonna use /dup #12388 for the rest.
