### ISSUE TITLE
Show (previous) history of commands at the top of the Command palette 

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/terminal#13060]
# Description of the new feature/enhancement

When using the command palette, I most often want to re-run a similar set of commands over and over.

- it would be ideal if the previous, lets say top 5 commands were at the top of the list of commands
- a history view

# Proposed technical implementation details (optional)

Perhaps have a configurable number of history to show e.g. 3 or 5 commands.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6647 for more discussion.

/dup #6647
