### ISSUE TITLE
Add a switch to disable closing a tab if it is not active

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#13062]
# Description of the new feature/enhancement

Sometimes when switching tabs, I accidentally hit the close button when I am expecting to switch tabs.  I am asking if we can add a switch that is disabled by default to disable closing the tab if is it not presently active, as such if I want to close an inactive tab I have to press the close button twice.

# Proposed technical implementation details (optional)

Assuming the setting is present.  It's a matter of

```
on close tab
  if not active
    return or just set tab to foreground
  else 
   close the tab
  endif
```

**Comment by zadjii-msft** [comment]
Huh. This seems like a variation on #3335. In addition to the proposed 

```
"tab.showCloseButton": "always"|"hover"|"never"
```

maybe something like `"tab.showCloseButton": "active"` to make it only visible when the tab is the active tab? That has the added complication though - is there a `activeAndHover` version? `inactiveAndHover`? `activeNoHover`? That might be too complicated.

Maybe the better solution is just some version of the warnings proposed in https://github.com/microsoft/terminal/issues/6549#issuecomment-675494526. Does that seem like a viable solution to this workflow/?

**Comment by trajano** [comment]
I think we can merge this into one user story that collects all of the scenarios and lists it out like https://github.com/microsoft/terminal/issues/6549#issuecomment-675494526

**Comment by trajano** [comment]
merge with #3335  and #6549  please
