### ISSUE TITLE
"Open In Terminal" doesn't have a letter selector or hot key

### ISSUE THREAD

**Issue by keithn** [microsoft/terminal#13061]
### Steps to reproduce

Open in Terminal when in Explorer is handicapped for keyboard users as there is no direct way to trigger opening a terminal with the keyboard,  and if you use your "menu" key on the keyboard, it opens the right click menu, but "Open in Terminal" has no hotkey associated with it, so the only way to select it is to arrow down, which is too fiddly.

![image](https://user-images.githubusercontent.com/86080/167333171-375430fb-de69-4e65-908e-17e150c8af07.png)

### Expected Behavior

Hotkey and Letter select should be enabled

### Actual Behavior

I cried.

**Comment by keithn** [comment]
Yes, should be trivial, not sure what the translations are like, but definitely T in the English version.

**Comment by zadjii-msft** [comment]
Oh man I can't believe we never thought of that! Yes, we should totally do that. I'm cool with `T` as the key. A hot take might be to do `T` for stable, `P` for the preview version, and `D` for the dev build, but I'll let that get sorted out in review.

**Comment by keithn** [comment]
> Oh man I can't believe we never thought of that! Yes, we should totally do that. I'm cool with `T` as the key. A hot take might be to do `T` for stable, `P` for the preview version, and `D` for the dev build, but I'll let that get sorted out in review.

just a note, P is used already for "Group by" and "Paste"   the letter choices for some of the standard stuff are a bit odd, ideally it matches a unique single letter so it opens straightaway.

**Comment by ianjoneill** [comment]
With the English (UK) language variant Group by is `G`. It's a bit odd that it's different to whatever English variant you're using!

I went with `I` for preview as I can't see anything in your context menu or mine with that allocation.

**Comment by keithn** [comment]
None of the windows functions use I,  but that's what visual studio code has hooked
![image](https://user-images.githubusercontent.com/86080/167832461-1c42003d-047d-4152-a859-c563e90951c8.png)
