### ISSUE TITLE
Can't update from Windows Terminal 1.7 to 1.12 - "Windows Terminal is already installed"

### ISSUE THREAD

**Issue by LoganDark** [microsoft/terminal#13074]
### Windows Terminal version

1.7.1033.0

### Windows build number

10.0.19041.0

### Other Software

I'm trying to update to Windows Terminal `1.12.10733.0` (Win10 version: `Microsoft.WindowsTerminal_Win10_1.12.10733.0_8wekyb3d8bbwe.msixbundle`, from [this release](https://github.com/microsoft/terminal/releases/tag/v1.12.10732.0))

### Steps to reproduce

1. Install Windows Terminal 1.7.1033.0
2. Try to install Windows Terminal 1.12.10733.0

### Expected Behavior

I should be able to update Windows Terminal

### Actual Behavior

Windows won't let me update Windows Terminal:

![image](https://user-images.githubusercontent.com/4723091/167651479-e381f3be-ee8f-444f-a310-9504c6d9a910.png)

It says "A newer version of Windows Terminal is already installed." (which is false).

### Notes

In this case I'm not sure how this could be solved other than uninstalling the current version of Windows Terminal and installing the newer version fresh. I'm not sure how to keep my configuration intact if I uninstall the app though which is why I haven't tried it yet.

**Comment by zadjii-msft** [comment]
Hmm. This is a crazy theory, so hear me out. I think there's an even newer version of terminal than 1.12.10733 in the Store. I'm wondering if secretly, the Store downloaded that version, has got it all staged, but is patiently waiting for you to stop using the Terminal before it installs it. 

I know this is annoying, but does restarting your machine help? That might close out any running Terminal instances, make room for the store to do it's thing, and maybe when you boot back up you'll have the new one? It's a crazy theory, for sure.

**Comment by LoganDark** [comment]
> secretly, the Store downloaded that version, has got it all staged, but is patiently waiting for you to stop using the Terminal before it installs it.

That would be funny considering my Store can't connect to the Internet. Also Windows Terminal isn't running.

> does restarting your machine help?

I'll try anyway, since Windows routinely gets all sorts of insane issues that only restarting can fix.

> FWIW, the only state the Terminal keeps around (on version 1.7) is the [`settings.json` file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file). If you want to go the manual uninstall route, just copy that file out somewhere before you uninstall 😉

Thanks, I'll keep that in mind!

**Comment by LoganDark** [comment]
Looks like my version of Windows is not supported after all (#11371): `Ask the developer for a new app package. This package may conflict with a package already installed, or it depends on things not installed here (package dependencies), or is made for a different architecture (0x80073CF3)`

Oh well, I'll just go back a release. Installing 1.11 worked!

**Comment by DHowett** [comment]
This is pretty surprising, though! 1.12 should continue to work on your version of windows (as should 1.13! You're on 10.0.19041+, which is the latest public version of Windows 10).

I'm gonna reopen this to track it, since it might be a more widespread issue. :)

**Comment by LoganDark** [comment]
> Before installing Terminal 1.12, can you try installing the Microsoft.VCLibs package for your architecture?

Looks like that was the problem!

![chrome_75fRaCljuP](https://user-images.githubusercontent.com/4723091/167671437-f438ae66-a9ca-4a1b-8dd8-3ea0e06260c0.png)

**Comment by DHowett** [comment]
> Isn't 20H2 / 22H2 or something the latest version

Something like that! 20H1 is "The version of Windows released in the first half of 2020". It's been "updated" (via service packs) a couple times to 20H2, 21H1, ... but that part doesn't truly matter. I always get my marketing names mixed up, so all we usually care about is build numbers. You're on build number 10.0.**19041** or higher, which is the "baseline" build number[1] of the most recent actual version of Windows 10 that we care about.

[1]: The service packs update it to 19042, 19043 and beyond but those are actually a trick. The binaries on-disk are still numbered 19041. It's all sorts of strange!

I'll close this out as I think we've understood/addressed the main issue. Thanks!

**Comment by LoganDark** [comment]
> I think we've understood/addressed the main issue.

Just to verify, the installer thinking that the older version was newer was caused by the dependency issue, right? That seems totally weird, but I guess on Windows anything can happen.

**Comment by DHowett** [comment]
I believe so! That thing isn't really _great_ at error messages... :D
