### ISSUE TITLE
OSC 9;9 with semicolon as PWD crashes WT

### ISSUE THREAD

**Issue by mqudsi** [microsoft/terminal#13077]
### Windows Terminal version

1.12.10984.0

### Windows build number

10.0.18363.1556

### Steps to reproduce

[As reported by @faho](https://github.com/fish-shell/fish-shell/issues/8805):

Use OSC 9;9 to set the PWD value to a single semicolon. Under bash:

```
printf "\e]9;9;;\e\\"
```

### Expected Behavior

No crash. 

### Actual Behavior

Windows Terminal crashes.

**Comment by DHowett** [comment]
Thanks for the report! This was fixed as part of #12432, which will be coming out to the stable channel shortly :smile:
Due to some refactoring, it wasn't a straightforward backport so we did not seek to include it in 1.12.

I'm gonna close this in favor of tracking issue /dup #12378.
