### ISSUE TITLE
Paste warning inconsistencies

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13072]
### Windows Terminal version

1.13.10984.0

### Windows build number

10.0.2200.652

### Other Software

bash (inside WSL)

### Steps to reproduce

copy large text data and paste into terminal

### Expected Behavior

consistent paste warning message

### Actual Behavior

bash paste:

![paste_wsl](https://user-images.githubusercontent.com/3933920/167522196-321866c1-cabe-4cf7-997a-973a2a06085f.png)

pwsh paste:

![pwsh_paste](https://user-images.githubusercontent.com/3933920/167522211-43190430-c507-4743-b58d-624ff8185b72.png)

**Comment by skyline75489** [comment]
I got the feeling that this is because Bash activates bracketed paste.
