### ISSUE TITLE
vim alt key behaviour

### ISSUE THREAD

**Issue by seongbin** [microsoft/terminal#13076]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.613

### Other Software

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)

### Steps to reproduce

Windows Terminal JSON config
```
        {
            "command": "unbound",
            "keys": "alt+j"
        },
        {
            "command": "unbound",
            "keys": "alt+k"
        },
```

Vim key bindings
```
  1 nnoremap <A-k> :m .-2<CR>==
  2 inoremap <A-j> <Esc>:m .+1<CR>==gi
  3 inoremap <A-k> <Esc>:m .-2<CR>==gi
  4 vnoremap <A-j> :m '>+1<CR>gv=gv
  5 vnoremap <A-k> :m '<-2<CR>gv=gv
```

### Expected Behavior

I tried to unbound ALT key in Windows Terminal by adding json config to move lines up or down in vim. Unfortunatlly, unbound feature looks like not working for me.

### Actual Behavior

Normal j/k cursor move

**Comment by seongbin** [comment]
In this PC, I have installed us-en and c/j/k input
![image](https://user-images.githubusercontent.com/1720769/167756053-80d18a2e-0a74-4c67-ae9a-f107cd6e4d62.png)
And tried with en-us keyboard
![Animation](https://user-images.githubusercontent.com/1720769/167756675-ed994dbd-4a3d-4999-b526-b1488165f36c.gif)

**Comment by seongbin** [comment]
NVM, after I unbind all unnecessary ALT key in Windows Terminal, it works.

**Comment by CervEdin** [comment]
@seongbin what do you mean by "unbind all unnecessary ALT key"? Did you remove all Actions involving ALT?

**Comment by GTonehour** [comment]
@CervEdin In Windows Terminal "Actions" settings, `alt+shift+down`  is mapped to `resize panel down` (respectively up). Removing that keybinding solves the problem.
