### ISSUE TITLE
文件夹下右键在终端打开，希望从当前目录下打开wsl，Ubuntu

### ISSUE THREAD

**Issue by shuohao** [microsoft/terminal#13081]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1682

### Steps to reproduce

![image](https://user-images.githubusercontent.com/4637107/167821898-58b3c199-235d-4374-a29c-40bc953000c2.png)
比如我在D:\test目录下右键点击在终端打开，
![image](https://user-images.githubusercontent.com/4637107/167822257-e21f92fe-8165-4721-ba15-a84919e61063.png)
打开wsl Ubuntu后，是根目录，并非windows下的目录

### Actual Behavior

请问该怎么设置才能是当前目录下打开

**Comment by zadjii-msft** [comment]
Could you share your [`settings.json` file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?


I suspect this is because you're using the Ubuntu profile that ships with the Ubuntu app, which uses `ubuntu.exe` as the `commandline`, rather than the profile that the Terminal auto-generates, which uses `wsl.exe`.

**Comment by shuohao** [comment]
> Could you share your [`settings.json` file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?
> 
> I suspect this is because you're using the Ubuntu profile that ships with the Ubuntu app, which uses `ubuntu.exe` as the `commandline`, rather than the profile that the Terminal auto-generates, which uses `wsl.exe`.

{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{51855cb2-8cce-5362-8f54-464b92b32386}",
    "profiles": 
    {
        "defaults": {},
        "list": 
        [
            {
                "backgroundImage": "E:/shuohao/Pictures/frame.jpg",
                "backgroundImageOpacity": 0.5,
                "colorScheme": "One Half Dark",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell",
                "opacity": 80,
                "useAcrylic": true
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": true,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{e636fd95-8db6-56fc-969f-5647553fa92b}",
                "hidden": false,
                "name": "wsl-vpnkit",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "backgroundImage": "E:\\shuohao\\Pictures\\ubuntu-logo32.png",
                "backgroundImageAlignment": "bottomRight",
                "backgroundImageOpacity": 0.20000000000000001,
                "backgroundImageStretchMode": "none",
                "colorScheme": "Ubuntu [Dark]",
                "cursorShape": "bar",
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "opacity": 100,
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc",
                "useAcrylic": true
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#3C0315",
            "black": "#282A2E",
            "blue": "#0170C5",
            "brightBlack": "#676E7A",
            "brightBlue": "#80C8FF",
            "brightCyan": "#8ABEB7",
            "brightGreen": "#B5D680",
            "brightPurple": "#AC79BB",
            "brightRed": "#BD6D85",
            "brightWhite": "#FFFFFD",
            "brightYellow": "#FFFD76",
            "cursorColor": "#FFFFFF",
            "cyan": "#3F8D83",
            "foreground": "#FFFFFD",
            "green": "#76AB23",
            "name": "Raspberry",
            "purple": "#7D498F",
            "red": "#BD0940",
            "selectionBackground": "#FFFFFF",
            "white": "#FFFFFD",
            "yellow": "#E0DE48"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#2E3436",
            "black": "#2E3436",
            "blue": "#3465A4",
            "brightBlack": "#696B67",
            "brightBlue": "#729FCF",
            "brightCyan": "#2EC3C3",
            "brightGreen": "#79C32E",
            "brightPurple": "#AD7FA8",
            "brightRed": "#F49797",
            "brightWhite": "#EEEEEE",
            "brightYellow": "#C4A000",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#B5BBAE",
            "green": "#4E9A06",
            "name": "Ubuntu [Dark]",
            "purple": "#75507B",
            "red": "#AE5E5E",
            "selectionBackground": "#FFFFFF",
            "white": "#B5BBAE",
            "yellow": "#8A7000"
        },
        {
            "background": "#EEEEEE",
            "black": "#EEEEEE",
            "blue": "#729FCF",
            "brightBlack": "#B5BBAE",
            "brightBlue": "#3465A4",
            "brightCyan": "#06989A",
            "brightGreen": "#3B7505",
            "brightPurple": "#75507B",
            "brightRed": "#AE5E5E",
            "brightWhite": "#2E3436",
            "brightYellow": "#8A7000",
            "cursorColor": "#2E3436",
            "cyan": "#2EC3C3",
            "foreground": "#696B67",
            "green": "#79C32E",
            "name": "Ubuntu [Light]",
            "purple": "#AD7FA8",
            "red": "#F49797",
            "selectionBackground": "#B5BBAE",
            "white": "#696B67",
            "yellow": "#C4A000"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        }
    ],
    "theme": "dark",
    "useAcrylicInTabRow": false,
    "windowingBehavior": "useExisting"
}

**Comment by shuohao** [comment]
> Could you share your [`settings.json` file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?
> 
> I suspect this is because you're using the Ubuntu profile that ships with the Ubuntu app, which uses `ubuntu.exe` as the `commandline`, rather than the profile that the Terminal auto-generates, which uses `wsl.exe`.

![image](https://user-images.githubusercontent.com/4637107/168512217-fb16302d-f50a-4f2e-b0c7-224edf68863b.png)
Another problem is I didn't find this option in regedit

**Comment by zadjii-msft** [comment]
Okay yep, this is because the Ubuntu profile from Canonical doesn't actually respect the `startingDirectory` setting. We're tracking that in #12961. Sorry about that!

/dup #12961

**Comment by shuohao** [comment]
I use this "C:\Windows\system32\wsl.exe -d Ubuntu "  it's worked
![image](https://user-images.githubusercontent.com/4637107/169564599-fdbdbd08-f842-4e9a-8869-d6f3de5d8d09.png)

**Comment by YanqingWu** [comment]
this works forme： C:\Windows\system32\wsl.exe -d Ubuntu-18.04

**Comment by YanqingWu** [comment]
this works for me： 
`C:\Windows\system32\wsl.exe -d Ubuntu-18.04`
