### ISSUE TITLE
Launching with CreateProcess function

### ISSUE THREAD

**Issue by squealingpaprika** [microsoft/terminal#1308]
# Summary of the new feature/enhancement
Add the ability to launch using the Windows CreateProcess function https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa so that the terminal can be launched programmatically. Ideally this would mean it would also be possible to launch via command line, with arguments to specify which shell(s) should open in the tabs etc. I'm not sure if this will at all be possible as in the current state I am only able to launch via the start menu, with no launch time parameters available. The only settings I can change are in profiles.json.

**Comment by DHowett-MSFT** [comment]
This already exists. `wt.exe` or `wtd.exe` should be in your `PATH`, and we have #607 tracking command line arguments.
