### ISSUE TITLE
Settings file being reformatted when the Terminal opens

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#1309]
# Environment

Built as `release` from latest commit on master: 440bee0e4abd0a778cbdff5b86f73fb34a92f3ed
Windows build number: `Microsoft Windows [Version 10.0.18362.175]`

# Steps to reproduce

When the Terminal opens the settings file gets reformatted.

And (what is really, really annoying) the new format adds trailing white spaces to every JSON key and the new format is not tasteful (what are those spaces before every colon?).

# Expected behavior

Settings file is left untouched when the Terminal opens.

# Actual behavior

File is reformatted every time the Terminal opens.

**Comment by DHowett-MSFT** [comment]
Huh. We try to only save the file if it's logically different from the one you saved. I'll retitle this a bit.

**Comment by DHowett-MSFT** [comment]
We were thinking that this might have been #1325. @zadjii-msft do you agree?

**Comment by giggio** [comment]
I just pulled the latest from `master` which contains the fix for #1325 and the issue still happens. The difference is that now the file is reformatted when the Terminal opens, not when you save it. I'll update the description.

**Comment by giggio** [comment]
Just as history, this is the previous description:

# Environment

Built as `release` from latest commit on master: 5f07f58fdaec89bfe30737f4f7f30723b2dae90e
Windows build number: `Microsoft Windows [Version 10.0.18362.175]`

# Steps to reproduce

If you save the settings file, it gets reformated.

And (what is really, really annoying) the new format adds trailing white spaces to every JSON key and the new format is not tasteful (what are those spaces before every colon?).

See it happening:

![wt-reformat](https://user-images.githubusercontent.com/334958/59720980-94721e80-91f6-11e9-9574-a2644cee99f9.gif)

# Expected behavior

Settings file is saved and left untouched.

# Actual behavior

File is reformatted.

**Comment by cinnamon-msft** [comment]
I believe #1326 fixed this

**Comment by giggio** [comment]
@cinnamon-msft 	ok, but the problem still happens on some situations. I opened a more comprehensive issue on #2411
