### ISSUE TITLE
Different results in npm audit 

### ISSUE THREAD

**Issue by Nirgranth** [microsoft/terminal#13094]
### Windows Terminal version

1.12.19083.0

### Windows build number

10.0.22000.318

### Steps to reproduce

recently upgraded for win 10 to 11
running npm audit in cmd, cant even fix it with npm audit fix, 

idk if this is the right place for this i cant seem to find the cmd/cli repo

### Expected Behavior

Everyting matches

### Actual Behavior

![Uploading image.png…]()

**Comment by DHowett** [comment]
I'm sorry, it looks like the image you uploaded didn't work out. Can you re-send it?

**Comment by Nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/168225747-8ceb404f-441e-49c1-9fbe-1f499d765113.png)

**Comment by zadjii-msft** [comment]
If you run `where npm` in each, do you get the same NPM/? I suspect this might have to do with the two windows having different `PATH`s.

**Comment by Nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/168405285-b15c8dda-6fa6-45a8-a7db-1a2bba6bc7de.png)

npm help-
![image](https://user-images.githubusercontent.com/48947296/168405311-a35e9578-6169-45fb-ab68-37d30b99ae66.png)

**Comment by elsaco** [comment]
@Nirgranth when using admin, find where your packages are located with `npm root` and `npm root -g`. Also, check if `C:\Windows\System32\node_modules` is present. Looks like you have vulnerable node packages installed in `C:\Windows\System32\node_modules`.

**Comment by Nirgranth** [comment]
> @Nirgranth when using admin, find where your packages are located with `npm root` and `npm root -g`. Also, check if `C:\Windows\System32\node_modules` is present. Looks like you have vulnerable node packages installed in `C:\Windows\System32\node_modules`.

yup you are correct, how do i fix it

**Comment by zadjii-msft** [comment]
> > find where your packages are located with `npm root` and `npm root -g`. Also, check if `C:\Windows\System32\node_modules` is present. Looks like you have vulnerable node packages installed in `C:\Windows\System32\node_modules`.
> 
> yup you are correct, how do i fix it

Honestly I don't know - you might be able to find more help on StackOverflow or the npm repo itself. Since this doesn't seem like a Terminal-specific issue, I'm gonna close this out. Thanks!

**Comment by Nirgranth** [comment]
> Honestly I don't know - you might be able to find more help on StackOverflow or the npm repo itself. Since this doesn't seem like a Terminal-specific issue, I'm gonna close this out. Thanks!
okay thanks
