### ISSUE TITLE
"Run this profile as an administrator" item is missing

### ISSUE THREAD

**Issue by eooeo** [microsoft/terminal#13104]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.675

### Steps to reproduce

1. open settings
2. profiles
3. defaults or command prompt
4. "Run this profile as an administrator" item is missing

### Expected Behavior

![wt-cmd-run-profile-admin-always](https://user-images.githubusercontent.com/69471730/168457848-3ac23c0a-f51e-40f1-9eb3-bbf917119d98.jpg)

### Actual Behavior

![Screenshot 2022-05-15 072145](https://user-images.githubusercontent.com/69471730/168457414-fc63e0c5-2930-4dbe-a7f4-08696633f20d.png)
![Screenshot 2022-05-15 072217](https://user-images.githubusercontent.com/69471730/168457415-a5981078-c0cc-4133-b5c0-594e724e3bc0.png)

**Comment by zadjii-msft** [comment]
Yep, that feature only landed in 1.13.

**Comment by tikg** [comment]
Got it, it's a version fix

**Comment by harsha-bharadwaj100** [comment]
> Got it, it's a version fix. Had Microsoft Store initially not show the "update" button then after it showed. Thanks!

Hello! I also have this exact old version and I wanna update it to latest version, but microsoft store is not showing the update button... how did you make it show? Any idea? I will highly appreciate your reply.

**Comment by harsha-bharadwaj100** [comment]
Holy shit lol! It finally showed xd. Fixed it myself. Thing is it only shows the update button only after you click on the terminal icon in microsoft store.

**Comment by Hunanbean-Collective** [comment]
> Holy shit lol! It finally showed xd. Fixed it myself. Thing is it only shows the update button only after you click on the terminal icon in microsoft store.

You're exactly right. for some strange reason, unlike any other apps, i had to actually click in to the Store Page for Terminal. it did not register in the usual Update check.   Thanks!
