### ISSUE TITLE
I have changed my user folder's name and Oh My Posh's path bar did not change to the same

### ISSUE THREAD

**Issue by kimthien175** [microsoft/terminal#13107]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

oh-my-posh

### Steps to reproduce

I changed my user folder's name like this video: https://www.youtube.com/watch?v=Y5_Q2BmTx3Y&ab_channel=SandeepSingh
But Oh My Posh path bar stills show the old user name.

### Expected Behavior

I expected Oh My Posh path bar to show the new name, not the old name.

### Actual Behavior

My old user folder name is [`Tom], and the new one is [Tom].

![image](https://user-images.githubusercontent.com/55306297/168472018-09eaeda1-6b30-4fbc-8917-d5edad66aa16.png)

**Comment by zadjii-msft** [comment]
~This is gonna sound like a dumb question, but did you actually reboot your PC after changing your username? I could easily see the shell caching that value. I forget if Windows forces a reboot or not.~



Wait, did you change your _username_, or just the name of your `%userprofile%` folder/? Cause I'd suspect that Oh-My-Posh is using your user_name_, not the name of the directory.

**Comment by kimthien175** [comment]
Thanks very much for the answers, I got that the above tutorial just help me to change the display name of user and the mapping to its folder. I just changed user account's name by going to [Run->control userpasswords2]

![image](https://user-images.githubusercontent.com/55306297/168653014-edf01d1a-ee06-4571-ab2a-65944bcd9e94.png)
