### ISSUE TITLE
Could not disable transparency, transparency only in effect when active

### ISSUE THREAD

**Issue by JasonGoemaat** [microsoft/terminal#13103]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19043.0

### Steps to reproduce

Open windows terminal

### Expected Behavior

Window is opaque

### Actual Behavior

Window is transparent when active, opaque when not.

This is so annoying.  I probably spent hours over multiple occasions trying different combinations of running terminal as administrator or not and fiddling with appearance settings to get rid of the transparency, saving, and restarting, but nothing worked.  Finally searching for transparency bugs here I found one mentioning CTRL+SHIFT+MOUSEWHEEL saying it no longer worked.  That actually DOES work for me, however it resets to transparent every time I start a new instance of windows terminal.  Now that's one more thing cluttering up my mind.

Ok, I found looking at the JSON file that I had my default terminal's useAcrylic set to true.  I had no idea what that setting was for and still don't understand it.   I don't know why I ever would have set it myself.

Playing around with it more it looks like setting any level of 'Background opacity' other than 100%, it enables acrylic.  I suppose I might have done that in the past.  But when I change the opacity back to 100%, useAcrylic remains checked and the window remains transparent.  If you set opacity to 100% I think it should disable useAcrylic.

**Comment by zadjii-msft** [comment]
Sorry this got lost in the triage queue. As a part of #7158, we have a mind to fully detach acrylic from opacity. Alas, on older Windows 10 versions, the API we needed to support non-acrylic opacity was simply broken. Now that it's fixed, we can remove the automatic enabling of acrylic when trying to turn on transparency on Windows 10. 

All that'll be fixed whenever we get to /dup #7158. Thanks for the report!
