### ISSUE TITLE
ANSI escape codes in output using git for windows

### ISSUE THREAD

**Issue by jcrben** [microsoft/terminal#13101]
NOTE: I've seen some reports which suggest that this would be fixed by later Windows versions, so I'm on the Windows Insider preview... I've seen this with another application (https://github.com/go-task/task); I've also used ansicon to get around it but that cuts out some of the scrollback

### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Download https://search.maven.org/search?q=a:junit-platform-console-standalone by clicking the Download link 
![image](https://user-images.githubusercontent.com/5614134/168408615-55ddcd5d-b422-4eb3-a11a-f4e3489b04d9.png)

Install java: `winget install Microsoft.OpenJDK.11`
Install Git for Windows interactively: `winget install Git.Git -i`

When installing Git for Windows, enable the option to add it to the Microsoft Terminal

Open a Git Bash tab:

Execute the following:
`cd ~/Downloads; 'C:\Program Files\Microsoft\jdk-11.0.15.10-hotspot\bin\java.exe' -jar ./junit-platform-console-standalone-1.8.2.jar;
 
The output contains ANSI escape codes: 
![image](https://user-images.githubusercontent.com/5614134/168409124-65f06f2a-8d74-46b1-98db-2623b7615fea.png)

### Expected Behavior

Colored output (or bolded, underlined - not sure what the codes map over to)

### Actual Behavior

ANSI escape codes

**Comment by ianjoneill** [comment]
I believe this is the same issue as #6634 - see over there for more information.

**Comment by zadjii-msft** [comment]
This does look like the same thing as /dup #6634 to me. See https://github.com/microsoft/terminal/issues/6634#issuecomment-647726408 specifically.

**Comment by jcrben** [comment]
That closed issue doesn't really explain things very well for the average user who isn't intimately familiar with the architecture. Is there a TL;DR as to why you can't just fix this by tracking and making PRs against these upstream clients? Why not keep things like this open and track these legacy applications, especially when it's something as huge as java? This team is going to be the most motivated to add flags which specifically target your Windows architecture.

Note that just using the terminal which ships with Git for Windows, ANSI escape codes are displayed properly.

I'm willing to make a PR against the jdk I suppose but it's going to take me far longer and I'd be flying pretty blind in doing so.
