### ISSUE TITLE
The Windows SDK version 10.0 was not found

### ISSUE THREAD

**Issue by a-gn** [microsoft/terminal#1310]
# Environment
```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): pulled it from git minutes ago
```

# Steps to reproduce

1. `git clone git@github.com:microsoft/terminal.git`
2. `cd terminal` and `git submodule update --init`
3. Open OpenConsole.sln in Visual Studio 2019
4. Select Release, x64
5. Build solution

# Expected behavior

The build finishes successfully and I can launch Terminal.

# Actual behavior

I get errors saying the Windows SDK 10.0 cannot be found, even though I have installed all requirements: `error MSB8036: The Windows SDK version 10.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".`

[...]

`========== Build: 4 succeeded, 44 failed, 0 up-to-date, 0 skipped ==========`

# Details

I checked in Visual Studio Installer that the following components are installed:

- Universal Windows platform development
- Desktop development with C++
- Windows 10 SDK (10.0.17763.0)
- Windows 10 SDK (10.0.18362.0)
- MSVC v141 x64/x86 build tools (v14.16)
- MSVC v142 x64/x86 build tools (v14.21)

When opening the solution, I was given the choice to use either of these Windows SDKs, and to convert the solution to build tools v142. I chose to use the latest available SDK and to not convert the solution.

The full build output can be found [there](https://pastebin.com/a7CFC4Ax).

**Comment by DHowett-MSFT** [comment]
When you retargeted your solution, did you choose `10.0` or `10.0.18362.0`? Choosing the former will superexplode the project.

**Comment by a-gn** [comment]
I did choose 10.0; re-cloning and choosing 10.0.18362.0 fixed it, thank you.

**Comment by Chase817** [comment]
> When you retargeted your solution, did you choose `10.0` or `10.0.18362.0`? Choosing the former will superexplode the project.

@DHowett-MSFT Apologies for bumping this issue, but can you explain why using v142 along with WindowsTargetPlatformVersion "10.0" doesn't cause this problem? Why is it that using v141 alongside "10.0" shows different behavior?

**Comment by DHowett** [comment]
The "platform toolset" value dictates which of the exact set of a hundred XML files VS/MSBuild use for the project.

It looks like the v141 and v142 toolsets differ vastly in configuration, so it is difficult to speculate:

```
125 files changed, 4710 insertions(+), 1706 deletions(-)
```
