### ISSUE TITLE
Windows Terminal crashes immmediately when launched from Win+X menu

### ISSUE THREAD

**Issue by notis58** [microsoft/terminal#13108]
Windows Terminal  and Windows Terminal (Admin) crash immmediately when launched from Win+X menu.
It will also crash if wt.exe is started from the Win+R menu.

It starts normally from the Explorer context menu and from the Start menu/All apps.
wt.exe starts also form the Task Manager, but only as administrator.

I have tried all fixes I found: Repair, Reset in settings, Uninstall and reinstall from Microsoft Store, toggle the App execution aliases.

Nothing worked.

My Windows specification:

Edition	Windows 11 Pro
Version	21H2
Installed on	‎5/‎13/‎2022
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0

Windows Terninal Version: 1.12.10983.0

**Comment by zadjii-msft** [comment]
Does it open and then exit immediately, or does it straight up just not launch at all? Could you repro this with the Feedback Hub? That _might_ catch whatever error is happening on launch.

/feedback

**Comment by notis58** [comment]
Here ist the link from the recording in th e feedback hub:
https://aka.ms/AAgxcoo

@zadjii-msft: It opens and exits immediately. I see it does open in the task manager

**Comment by notis58** [comment]
Any update on this?

**Comment by AlifianK** [comment]
Hi, I have the same issue with this.

https://aka.ms/AAh47m0

**Comment by zadjii-msft** [comment]
* registry seems to have the right guids for defterm to work with terminal stable.
* dmp only included three conhosts, which had nothing useful in them. Three threads, but no crashes in there. 
* etl log had nothing interesting. Two TerminalApp launches, that both hit three `0x80070005` access denied's, but those had no line number, or anything else interesting. They seemed to bubble up to the windowsterminal.exe layer, as well. 
* two different conhost buckets: `15cdd140-8a18-37f0-9565-7514747b3463` and `ffe8b5db-bcc5-7941-75b1-ed66cb4bbdbe`, these are both useless `conhost!unknown` buckets that don't actually capture that something went wrong. 
* actually all three conhosts look like they were started to service some other commandline application, and not related to the Terminal at all.


There's unfortunately basically nothing to go on here 😕 

Did Terminal 1.12 / 1.11 / 1.10 work? Does manually uninstalling the Terminal, and manually installing an older version like 1.11 seem to fix it? 

We don't really own the win+x menu shortcut, so you might need to file feedback on 
![image](https://user-images.githubusercontent.com/18356694/174822391-648ef4e9-e98d-4d02-a774-9a810c70ea3c.png)

to try and sort out what's going on here.

**Comment by notis58** [comment]
It’s not just the Win+X menu.

The terminal (wt.exe) starts and crashes when run form the Task Manager.

It only starts from there if run with administrator privileges.

**Comment by zadjii-msft** [comment]
Hmm, that sounds like a riff on #13197

**Comment by notis58** [comment]
Well, not quite.

 

In my case:

From the Start menu the Terminal runs both without and with admin privileges

From the Win+X menu it runs but crashes immediately both without and with admin privileges (immediately after the UAC prompt in the admin case)

From The Task Manager it runs with  admin privileges but crashes immediately without

 

Crazy?

**Comment by notis58** [comment]
Well, it was not fixed!!!

And even worse

I downloaded and installed the preview version, which supposedly solved the issue and it messed everything up!!!

 

Now Windows Terminal runs only if I navigate to “C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe" or "C:\Users\Notis\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe" and double click on wt.exe. Both versions, old and preview, work this way

 

If I try to run wt.exe from Run or the task manager or the Win+X menu it returns an error: 0xc0000022

 

This happens with any of the aliases enabled

 

 

This mentioned in #7081 <https://github.com/microsoft/terminal/issues/7081> 

 

 

Now that I’ve checked #13193 <https://github.com/microsoft/terminal/issues/13193> , https://github.com/microsoft/terminal/issues/13193#issuecomment-1177510405 is asking if it resolves my issue and some others.

 

How did you come up with the idea that this would resolve my issue in the first place?

 

Your comment instead of resolving my issue made things worse

**Comment by notis58** [comment]
After lhecker's comment my issue was closed
I had the (obviously wrong) impression that an issue is closed after the solution is checked. Apparently not.

I checked  #13193 and installed Windows Terminal Preview v1.15.186

Now everything is messed up 

Windows Terminal will not start and returns an error

![image](https://user-images.githubusercontent.com/102928102/178056232-e8146852-fc2a-4094-aa94-2668383669e5.png)

This is mentioned in #7081 but there seems to be no solution there

I uninstalled the preview version but the issue persists

How do I fix the new issue now?

**Comment by DHowett** [comment]
Can you try to "Repair" the installation of Windows Terminal in the "Apps and Features" control panel? `0xC0000022` is an error originating from the application platform, which is unfortunately just as mystifying to us as it is to the general public.

**Comment by notis58** [comment]
I have already tried repairing and resetting Windows Terminal
Nothing worked

**Comment by AlifianK** [comment]
Updated to [v1.14.186](https://github.com/microsoft/terminal/releases/tag/v1.14.1861.0) fixed the Win+X problem for me, but still the same with Win+R. Terminal refuses to open with no crash dialogue.

**Comment by notis58** [comment]
> Can you run:
> 
> * `conhost -- cmd.exe /k where wt & path`
> 
> for me, from the run dialog (win+r)/? Try it both as admin and not, that should get a read on what's diffent between the two. I'm hoping that you're just missing `%localappdata%\Microsoft\WindowsApps` from your `PATH`, which is why it seems like it won't launch.
It's not missing:
run as admin

`C:\Users\Notis\AppData\Local\Microsoft\WindowsApps\wt.exe
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Notis\AppData\Local\Microsoft\WindowsApps`

run not admin

`C:\Users\Notis\AppData\Local\Microsoft\WindowsApps\wt.exe
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Notis\AppData\Local\Microsoft\WindowsApps`


The Win+X issue is resolved after the last Windows update, but the Win+R issue remains. If run as admin, it asks for confirmation and thesn nothing. Strangely enough, when started from Win+R it tries to open wt.exe in `%programfiles%\WindowsApps\Microsoft.WindowsTerminal_1.14.1963.0_x64__8wekyb3d8bbwe`, which is not in my `PATH`

**Comment by saifsiddiquee** [comment]
`Go to Settings->Apps->Installed Apps->Terminal>Advanced option.`
Then repair and reset. It worked for me.

![terminal](https://user-images.githubusercontent.com/34885954/199197137-8ab7e163-7ad4-4aea-ad39-ecd71705dfe4.png)

_If it does not work, you can uninstall terminal and install again from the windows store.

**Comment by zadjii-msft** [comment]
Any chance this is fixed in https://github.com/microsoft/terminal/releases/tag/v1.16.10261.0/? This might have been the `elevate:true` crash, in retrospect.

**Comment by notis58** [comment]
> Any chance this is fixed in https://github.com/microsoft/terminal/releases/tag/v1.16.10261.0/? This might have been the `elevate:true` crash, in retrospect.

It's fixed!
Terminal starts normally using Win+X and running wt.exe from Win+R
Both as admin and normal user
