### ISSUE TITLE
Navigate to hyperlinks using the keyboard

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#13115]
# Description of the new feature/enhancement
Windows Terminal supports automatic detection of hyperlinks and allows you to open the hyperlink using your mouse (specifically ctrl+clicking the link). I've realized that there's no way to do this using only the keyboard.

Once mark mode lands, the solution is a little better, but still far from perfect and on par. The user would be able to navigate to the text with the hyperlink, create a selection that encompasses it, copy the URL, then manually open it in their preferred web browser.

What if we could make this a nicer experience? Consider this...
1. enter mark mode
2. <kbd>tab</kbd> (or <kbd>shift+tab</kbd>) to navigate to these hyperlinks
3. when you've navigated to the hyperlink, a selection is created that encompasses the relevant hyperlink.
4. <kbd>enter</kbd> can be used to invoke the hyperlink directly

Some corner cases...
- what if <kbd>enter</kbd> is bound to an action (like "copy")? --> prefer the action
- what if we add more bookmark-like things like "prompt position" or user-configured bookmarks --> might as well navigate to them too? I'm thinking these can be tab stops.

**Comment by zadjii-msft** [comment]
> what if we add more bookmark-like things like "prompt position" or user-configured bookmarks --> might as well navigate to them too? I'm thinking these can be tab stops.

Oh man do I have thoughts in #11000.

(I think we do have this somewhere else on the backlog already, but it's 5pm here)

**Comment by zadjii-msft** [comment]
#6649

**Comment by carlos-zamora** [comment]
#6649

**Comment by carlos-zamora** [comment]
welp, you beat me by 2 seconds hahaha. Closing and moving this over.

Mainly doing these to add them to the inclusive feature backlog fyi
