### ISSUE TITLE
Fira Code ligatures are used eventhough ligatures are disabled in the settings.json file.

### ISSUE THREAD

**Issue by litesam** [microsoft/terminal#13116]
### Windows Terminal version

1.12.10982.0

### Windows build number

Microsoft Windows [Version 10.0.19044.1706]

### Steps to reproduce

1. Install Fira Code from their Git repository [Link to repository](https://github.com/tonsky/FiraCode)
2. In the settings.json file add the font configuration settings as:
```json
"font": {
    "face": "Fira Code",
    "features": {
        "liga": 0
    }
}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/34811358/168729592-b18acbb6-589b-4905-8a21-d20ff7cf8ec1.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/34811358/168729649-65789802-b4b9-4fa4-a36b-6cd21e6be3eb.png)

**Comment by zadjii-msft** [comment]
I was just testing this out locally. Apparently, to disable ligatures, you need

```jsonc

"font": {
    "face": "Fira Code",
    "features": {
        "liga": 0,
        "calt": 0
    }
},
```

Both `"liga": 0` and `"calt": 0` are apparently needed for Fira Code. Does that work for you/?

**Comment by blueberrycarrot** [comment]
> Both `"liga": 0` and `"calt": 0` are apparently needed for Fira Code. Does that work for you/?

I wish this ligatures toggle was in proper settings UI, this was a pain to find and activate. But I'm glad it's doable, thank you.

**Comment by DHowett** [comment]
> I wish ...

Good news! In Terminal 1.21 (which is currently in [Preview](https://aka.ms/terminal-preview)), you can now configure these things through the settings UI.



![Image](https://github.com/microsoft/terminal/assets/189190/fc15e535-cc1d-48a3-9235-8d9a398a3bb9)
