### ISSUE TITLE
Conda virtual environment doesn't work

### ISSUE THREAD

**Issue by nirajkale** [microsoft/terminal#13112]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.0

### Other Software

Software: conda 4.10.3
I am trying to activate conda environment on Windows terminal using below command:
conda activate env_name
but it doesn't work nor it gives any error.

### Steps to reproduce

install conda & try to activate any existing env (I created it using command prompt)
& then try activating it on terminal.

### Expected Behavior

![conda](https://user-images.githubusercontent.com/40765055/168591829-e3e3be48-2197-48a6-ad2a-c555c348bfb6.PNG)

It should activate that env & show it as a prefix 

### Actual Behavior

Nothing happens

**Comment by nirajkale** [comment]
FYI, I also tried creating a new env from within the new terminal & couldn't activate that also!

**Comment by zadjii-msft** [comment]
Does `conda activate --verbose tf23` log anything? (or similar - I couldn't find the `conda` docs for `activate` but I assumed it was just `--verbose`)

Are you using Command Prompt in the Terminal, or PowerShell/? I wouldn't expect different shells to make a difference here, but I wanted to be sure.

**Comment by nirajkale** [comment]
I think you meant 
`conda init powershell ` ?
But yes, after doing this, I'm able to use the terminal with conda.
Thanks a lot :-)
