### ISSUE TITLE
Use GitHub's auto merge rather than Microsoft's.

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/terminal#13127]
# Description of the new feature/enhancement

Switch to GitHub's auto merge.

# Proposed technical implementation details (optional)

No longer use Microsoft's Internal Auto merge.

**Comment by DHowett** [comment]
Hey @ChaseKnowlden! Thanks for the request! For right now, we actually prefer Microsoft's automerge for two key reasons:

* We can add somebody as a "required" reviewer by asking the bot to "make sure xxx signs off"
* We can set a time limit before the automatic merge happens, to give reviewers a "last chance" to air any grievances by asking the bot to "merge this in xxx minutes/hours/days"

Until GitHub's automatic merge feature supports required/optional reviewers at a minimum, we're not likely to switch. But don't worry -- we've been asking them for that feature!
