### ISSUE TITLE
Crashes on console text selection from bottom to top if mouse reaches window's titlebar

### ISSUE THREAD

**Issue by vhanla** [microsoft/terminal#1312]
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.18362.175]
Windows Terminal version (if applicable): 0.0.1.0

Any other software?
```

# Steps to reproduce

Select text from bottom to top and reach to the window title while still holding the mouse.

# Expected behavior

Not to crash.

# Actual behavior

Crashes and closes the terminal.

![2019-06-18 19-28-11](https://user-images.githubusercontent.com/1015823/59728762-e9b32d80-9200-11e9-8911-36cdb386e874.gif)

**Comment by DHowett-MSFT** [comment]
@carlos-zamora oh no
