### ISSUE TITLE
Ctrl-A followed by Ctrl-E moves to wrong position when command prompt is on same line as JSON output from curl

### ISSUE THREAD

**Issue by hkskoglund** [microsoft/terminal#13120]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

curl 7.81.0 (WSL 2)

### Steps to reproduce

1. curl 'https://frost.met.no/observations/v0.jsonld?sources=SN90450&referenceTime=2022-05-11T00:00:00Z/2022-05-17T23:59:59Z&elements=sum(precipitation_amount%20P1D)&timeResolution=days'
2. Notice } before prompt "}henning@ideapadpro:~$"
3. Press up arrow (cursor right of  ' )
4. Press Ctrl-A, Press Ctrl-E (cursor before ')
5. Press Ctrl-Left until start of line
6. Notice } removed at front of line

### Expected Behavior

Ctrl-E moves to same position (end of line) after Ctrl-A.

### Actual Behavior

Ctrl-E moves one character less than expected after Ctrl-A. "}" removed at start of line when multiple Ctrl-Left until start of line is pressed.

This makes it hard to edit the command, characters are inserted in the wrong position.

Workaround: press return and let the command prompt start on a new line

**Comment by DHowett** [comment]
I believe this is a common problem in any terminal emulator. It originates from the fact that `bash` tries to guess the location of the prompt, and when there is other output on the screen before the prompt it is incapable of accurately doing so.

Here's a gif of the same kind of cursor positioning issue happening with bash in gnome-terminal:

![bash-cursor-issue](https://user-images.githubusercontent.com/189190/169102760-e76a0be4-6485-425e-84e8-72e14358eb08.gif)

This is why zsh forces the prompt onto a new line whenever possible:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/189190/169102124-8ce8f485-01ba-43aa-afb0-0ce38308c22c.png">
