### ISSUE TITLE
Open-source Command Prompt

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/terminal#13126]
# Description of the new feature/enhancement

Open source the Command Prompt Application.

# Proposed technical implementation details (optional)

**Comment by leejy12** [comment]
What you're referring to is `conhost.exe` and its source is already in this repository.

**Comment by ChaseKnowlden** [comment]
I looked at it wrong.

**Comment by DHowett** [comment]
leejy12 is partially correct. The "console window" that CMD runs inside (and powershell, and ping.exe, ...) is `conhost.exe`. We are not planning on open sourcing `CMD` itself (the actual shell, which prints out `C:\>` and says `Microsoft Windows 10.xxx.yyyy` at the top).
