### ISSUE TITLE
Terminal Doesn't Start With Focus When Launched From Search

### ISSUE THREAD

**Issue by Nosamdaman** [microsoft/terminal#13130]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.675

### Steps to reproduce

1. Be on Windows 11 and configure Windows Terminal to be the default console host
2. Click on the desktop so that your active "window" is the desktop
3. Press the Windows key, type "wt", and press enter

### Expected Behavior

Terminal should launch and have focus

### Actual Behavior

Terminal launches, but is not the active window

**Comment by zadjii-msft** [comment]
By any chance, is your default profile a WSL one/? This sounds like #12134

**Comment by Nosamdaman** [comment]
> By any chance, is your default profile a WSL one/? This sounds like #12134

While that does sound awfully familiar, my default profile is Powershell Core

**Comment by Nosamdaman** [comment]
Yeah I think this is a windows issue, not a terminal one, as I've seen it happen with other apps. I'll close it for now

**Comment by Wiikend92** [comment]
I am experiencing this on Windows 11 with Windows Terminal 1.18.2822.0. My default profile is PowerShell 7.3.8.0. The first time this happened to me was today.

**Comment by sjanssens1977** [comment]
Same focus issue

### Windows Terminal Version 
1.18.3181.0

### Windows Version
Edition	Windows 10 Enterprise
Version	22H2
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Specifics:
Windows Terminal is pinned to the taskbar

### Steps to reproduce:
1. Press <ALT>+<Win>+<Rank number of the Terminal icon in the taskbar>
2. Use arrow keypad to select the profile and press enter
3. Windows Terminal opens but window is not activated

**Comment by ljredux** [comment]
Not sure if this is helpful to any of you, but I discovered it was happening to me due to [Quake Mode](https://learn.microsoft.com/en-us/windows/terminal/tips-and-tricks#quake-mode).   As soon I activate it that way (and I do use Quake Mode a lot), new Windows terminal instances will not have focus upon launch.

If I type exit in Quake Mode, further launches of Windows Terminal have focus again as expected.

**Comment by KristofKuli** [comment]
Workaround:
Once you have opened the terminal, press Alt + F4 and the focus will appear. No joke!
