### ISSUE TITLE
Terminal sometimes crashes when deleting a profile

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#13138]
### Windows Terminal version

1.12.10982

### Windows build number

10.0.19044.1706

### Steps to reproduce

Delete two profiles (not sure if it happens all the time)

![image](https://user-images.githubusercontent.com/2218936/169646859-02d034c6-97cc-473c-b1e0-b9f25a3c7d1f.png)

### Expected Behavior

No crash

### Actual Behavior

Crash

**Comment by j4james** [comment]
This might be the same thing as #13017.

**Comment by zadjii-msft** [comment]
Hard to say _for sure_ without a dump or stack trace, but I'd reckon there's a very high chance this is #13017, yea. Thanks!

/dup #13017
