### ISSUE TITLE
Add option to switch tabs in mru but without separate window

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/terminal#13131]
# Description of the new feature/enhancement
When configuring the behavior of `ctrl-tab`, one option seems to be missing:
1. tab strip order with separate window ✔
2. tab strip order without separate window ✔
3. mru with separate window ✔
4. mru without separate window ❌

4 actually feels very nice. It's the default behavior in sublime text. You could try `ctrl-tab` in sublime text to get a feeling. The idea is, when people `ctrl-tab`, their eyes actually focus on the tab content (looking for the content they seek), not on titles in the separate window. In that case the separate window becomes intrusive.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9390 for more discussion.

/dup #9390
