### ISSUE TITLE
When side-by-side builds of Visual Studio are installed, build is picking the wrong one

### ISSUE THREAD

**Issue by davkean** [microsoft/terminal#1313]
Unsure if this a build.exe issue or a Razzle issue. Based on experiments, Razzle appears to be okay.

# Environment
Visual Studio 16.2.0 Preview 4.0 [29018.107.d16.2stg] (installed to C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\)
Visual Studio 16.1 (installed to C:\Program Files (x86)\Microsoft Visual Studio\2019\RTM\)

# Steps to reproduce

1. From a _Developer Command Prompt For VS 2019 Preview_, run: 

```
> .\tools\razzle.cmd
> bcz
```

# Expected behavior

Build to succeed.

# Actual behavior

Build fails with:

```
Starting build...
MSBuild auto-detection: using msbuild version '16.200.19.31001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\16.2\MSBuild\Current\bin'.
All packages listed in packages.config are already installed.
Skipping building appx...
"C:\Program Files (x86)\Microsoft Visual Studio\2019\16.1\MSBuild\Current\Bin\MSBuild.exe" E:\terminal\OpenConsole.sln /t:Clean,Build /m /p:Configuration=Debug /p:Platform=x64 /p:AppxBundle=false
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/19/2019 10:58:30 AM.
     1>Project "E:\terminal\OpenConsole.sln" on node 1 (Clean;Build target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|x64".
     1>Project "E:\terminal\OpenConsole.sln" (1) is building "E:\terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj.
       metaproj" (2) on node 1 (Clean target(s)).
     2>Project "E:\terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj.metaproj" (2) is building "E:\terminal\src\cas
       cadia\TerminalSettings\TerminalSettings.vcxproj" (6) on node 2 (Clean target(s)).
     6>E:\terminal\src\cppwinrt.build.pre.props(45,3): error MSB4019: The imported project "C:\Program Files (x86)\Micr
       osoft Visual Studio\2019\16.1\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that
       the path in the <Import> declaration is correct, and that the file exists on disk. [E:\terminal\src\cascadia\Ter
       minalSettings\TerminalSettings.vcxproj]
```

The build is failing because its using/looking in the wrong location for these targets files. 

The first line says that its picked up the correct MSBuild ("16.2"):

```
MSBuild auto-detection: using msbuild version '16.200.19.31001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\16.2\MSBuild\Current\bin'.
```

But a few lines down, you can see that its picking up MSBuild from the 16.1 folder:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\16.1\MSBuild\Current\Bin\MSBuild.exe" E:\terminal\OpenConsole.sln /t:Clean,Build /m /p:Configuration=Debug /p:Platform=x64 /p:AppxBundle=false
```

**Comment by davkean** [comment]
Actually, I think that build.exe isn't respecting any of the Developer Command Prompt environment _at all_ if I run from 16.1:

```
Starting build...
MSBuild auto-detection: using msbuild version '16.200.19.31001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\16.2\MSBuild\Current\bin'.
```

This should say:

```
MSBuild auto-detection: using msbuild version '16.200.19.31001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\16.1\MSBuild\Current\bin'.
```

**Comment by zadjii-msft** [comment]
If you look at bcz.cmd, you'll see there are two steps here that are picking up different msbuild versions. There's a `nuget.exe` call, to restore dependencies, which is the one that's auto-detecting msbuild `16.200.19.31001`. Then, there's a second step that actually builds the solution, which uses the msbuild that was found by `vswhere` in `razzle.cmd`. 

Presumably, changes could be made to `razzle.cmd` that could enable it to _not_ lookup msbuild if it can tell it's already running in a developer command prompt.

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, an issue thatseems to have always existed in NuGet. There isn't terribly much we can do about it without tying our hands unnecessarily. I know `nuget` supports `-msbuildversion`, but producing the right value to supply to that argument is challenging.

**Comment by davkean** [comment]
@DHowett-MSFT Can you help me dig into "there isn't terrible much we can do about it  without tying our hands unnecessarily."? Lots of teams have solved this, so trying to understand that statement.

**Comment by DHowett-MSFT** [comment]
@davkean I almost certainly spoke before thinking :smile: Sorry about that.
I'm honestly not sure how best to solve this. I feel like we should not be depending too heavily on trying to detect the actual VS version in use and string-splitting that to pop it into `-msbuildversion` for NuGet's sake... especially since it doesn't support three-part versions (it fails for `-msbuildversion 15.9.11` but succeeds for `15.9`. I think it fails for `15.0`).

I can't find an environment variable present in devcmd that specifies the minor version in use (`%VisualStudioVersion%` reports 15.0, but i think that fails as above)

**Comment by zadjii-msft** [comment]
You know, maybe our guidance should just be "If you want to build the Terminal from 'Developer Command Prompt', just don't use `tools\razzle" but then I went ahead and just did the msbuild detection because that's easier
