### ISSUE TITLE
Please change language settings for Chinese ( Taiwan ) to Chinese (Traditional)

### ISSUE THREAD

**Issue by sg552** [microsoft/terminal#13140]
# Please change the language option from Chinese(Taiwan) to Chinese(Traditional)

![图片](https://user-images.githubusercontent.com/234533/169721065-f3bfa605-9cae-474d-8283-a4755dca6fa2.png)

Because there are many other areas using Traditional Chinese, such as:  Hongkong, Macau, Singapore.  

so please change it to: 

- Chinese (Simplified ) 
- Chinese (Traditional )

**Comment by skyline75489** [comment]
#8984

**Comment by zadjii-msft** [comment]
Ultimately, yea. This is gonna have the same resolution as #8984. We've got some info from the Store team on that one, but I anna double-check with another team before posting a response there. Thanks!

/dup #8984
