### ISSUE TITLE
windows terminal no response when rdp dissconnect and reconnect

### ISSUE THREAD

**Issue by SquallATF** [microsoft/terminal#13152]
### Windows Terminal version

1.1210983.0

### Windows build number

10.0.22621.0

### Steps to reproduce

run some long text out put program with remote desktop(I'm run visual studio layout here), and disconnect remote desktop, and reconnect. The windows terminal window will no response.

### Actual Behavior

![图片](https://user-images.githubusercontent.com/1386803/170049874-a285ec6b-34e2-4d84-aeec-3ea5118e4c66.png)

**Comment by zadjii-msft** [comment]
This looks like #12607 to me. Do you happen to have an Nvidia graphics card/?

**Comment by SquallATF** [comment]
yes, I have an  Nvidia graphics card, I think it is same to https://github.com/microsoft/terminal/issues/12607

**Comment by zadjii-msft** [comment]
Cool, thanks for following up!

/dup  #12607
