### ISSUE TITLE
[1.14.1433*] Opening a tab can cause the Terminal window to change size

### ISSUE THREAD

**Issue by ellgramar** [microsoft/terminal#13158]
### Windows Terminal version

1.14.1433.0

### Windows build number

 10.0.22000.0

### Steps to reproduce

Open Terminal and snap the window to your choice of left, right, or top. One may also snap another app to the right or left (opposite the terminal). Then open a new tab. 

Uploading ellgramar-WinTermPrev-SnapBehaviour.mp4…

### Expected Behavior

When opening a new tab, The window was expected to stay snapped to where it was placed.

https://user-images.githubusercontent.com/5509462/170111340-15b6e919-3d93-4262-b2e3-0a62a70e320a.mp4

### Actual Behavior

When a new tab was opened, the window de-snapped, resized to the default launch dimensions and returned to the last free floating location it had been.

**Comment by zadjii-msft** [comment]
Oh I know _exactly_ what regressed this. 

I bet this has to do with the Show/Hide work from #12515 / #12570. I'm betting that either showing the pty window, or showing the Terminal window in response to the PTY window opening is causing the terminal window to un-snap. Great.

**Comment by gurnec** [comment]
This can also be reproduced from a maximized Terminal window. Specifically:

1. Set the Launch mode to Default.
2. Start Windows Terminal, it opens in a non-maximized window.
3. Maximize the window.
4. Open a new tab, Windows Terminal "restores" / becomes non-maximized.
