### ISSUE TITLE
SUI missing passthrough option

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13169]
### Windows Terminal version

 1.14.1432.0

### Windows build number

10.0.19044.0

### Steps to reproduce

look for `passthrough` option in SUI

### Actual Behavior

![missing_pt_option](https://user-images.githubusercontent.com/3933920/170177737-f6a0b574-3734-48fc-b965-d23005dd6ca7.PNG)

**Comment by zadjii-msft** [comment]
Yep, that's by design. Right now, the feature is SO experimental that we didn't want to actively promote it in the SUI like that. We don't want anyone turning it on without knowing what they're getting themselves into.
