### ISSUE TITLE
When selecting a background, if you press the key to search, the program will get stuck

### ISSUE THREAD

**Issue by ssccinng** [microsoft/terminal#13167]
### Windows Terminal version

1.12.109

### Windows build number

10.0.19044.0

### Steps to reproduce

When selecting a background， then press any key to search

### Actual Behavior

program will get stuck

**Comment by zadjii-msft** [comment]
What path do you have in the background image field to start with? Are you running unpackaged/? This sounds like... well, some issue that's somewhere on the repo. Can't seem to find it right now 😕

**Comment by ssccinng** [comment]
https://user-images.githubusercontent.com/22047352/170395902-295ed2cb-d1fe-4dbe-99f9-f20f855feece.mp4

If you try to enter the path manually, wt seems to get stuck，

**Comment by zadjii-msft** [comment]
@ssccinng I'm not sure what happened, but whatever video got attached to your last post seems busted. Mind try uploading again/?

**Comment by ssccinng** [comment]
[2022-05-27 08-56-32.zip](https://github.com/microsoft/terminal/files/8783119/2022-05-27.08-56-32.zip)

**Comment by ssccinng** [comment]
This bug does not appear on win11, but it does appear on  win10（2 pc）. Looks like I need more tests
