### ISSUE TITLE
Setting Launch mode to Maximized doesn't maximize

### ISSUE THREAD

**Issue by gurnec** [microsoft/terminal#13161]
### Windows Terminal version

1.14.1432.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Set the Launch mode to Maximized.
2. Close Windows Terminal.
3. Start Windows Terminal.

### Expected Behavior

The window starts in a maximized state.

### Actual Behavior

The window fills the entire screen, but it isn't actually maximized, instead it's in "restored" state. Note in the screenshot below, the system menu has `Restore` grayed out, but `Maximize` is available. Likewise in the upper right, the maximize button is visible instead of the restore button.

![image](https://user-images.githubusercontent.com/2966862/170121714-6ef6d8a1-c0c0-45f8-90df-2751be424423.png)

Just a guess without any basis, but I wonder if this is related to #13158....

**Comment by zadjii-msft** [comment]
I'd bet on this being the same root cause as /dup #13158.
