### ISSUE TITLE
Opening a new tab when the window is maximized causes it to restore down

### ISSUE THREAD

**Issue by tmercswims** [microsoft/terminal#13162]
### Windows Terminal version

1.14.1433.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Open Terminal.
2. Maximize the window.
3. Open a new tab.
    - It doesn't matter how; `Ctrl+T`, new tab button, new tab from profile selector menu, etc.

### Expected Behavior

A new tab is opened, and the Terminal window stays maximized.

### Actual Behavior

A new tab is opened, but the window is restored down.

**Comment by tmercswims** [comment]
Just realized this is likely a duplicate of #13158. Thought I had looked for it in recent bug reports, but missed the one right under my nose 🤦. If so, please close this, thanks! 😅

**Comment by zadjii-msft** [comment]
Definitely is, thanks! 

/dup #13158
