### ISSUE TITLE
Windows Terminal's new windows is not at foreground.

### ISSUE THREAD

**Issue by nanoric** [microsoft/terminal#13168]
If there is a background windows terminal instance. A new instance of Windows Terminal run by Win+R as "wt" does not come to the foreground.
So we have to use ALT+Tab multiple times or use the mouse to see which one is new.
This action is really annoying.

So I suggest adding a new launch mode "default foreground" which will start in default mode and then focus (bring to foreground, not meaning WT's Focus mode!) immediately.

**Comment by zadjii-msft** [comment]
* Which version of Terminal/? 
* Which version of the OS? 
* How are you launching the Terminal? 
* What app is in the foreground when you notice this behavior? 


This is generally supposed to work by default.

**Comment by nanoric** [comment]
### Which version of Terminal/?
I have just uninstalled it, so i'm not able to find it out. But because wt is updated with windows update, it should always be the newest version.

### Which version of the OS?
Edition	Windows Server 2022 Standard
Version	21H2
Installed on	‎11/‎30/‎2021
OS build	20348.740

### How are you launching the Terminal?
Win+R : wt


### What app is in the foreground when you notice this behavior?
**This might be the problem**
I'm face this problem usually when I'm coding, which means i'm running Visual Stuio or Clion, maximumed windowed(not fullscreen). And I have two screen. Visual Studio use both of them, Clion uses only the primary screen.

**Comment by zadjii-msft** [comment]
Well, if you ever re-install the Terminal and would like to help further debug, we can always reopen this in the future. I certainly haven't seen this behavior while using VS, and I don't believe my colleague @lhecker has seen this when using CLion either. It also could be an OS version issue - I know there were some quirks with how the OS would launch packaged applications on Windows 10 (that are seemingly resolved in Windows 11).

**Comment by IT-CASADO** [comment]
Same for me.

Window 11 24H2 (fresh install), but I had this also with my old installation.
