### ISSUE TITLE
when add (shift + alt + - ) spli terminal then  window terminal restore down

### ISSUE THREAD

**Issue by jacol84** [microsoft/terminal#13170]
### Windows Terminal version

Podgląd Terminalu Windows Version: 1.14.1432.0

### Windows build number

10.0.19044.0

### Other Software

PowerShellPreview_7.3.4.0_x64

### Steps to reproduce

# Windows terminal Maximization
![image](https://user-images.githubusercontent.com/11667049/170189932-47ee899f-b775-4cfe-bd9e-fc0d372c0ded.png)
# split window pres key "shift + alt + -"

then Windows terminal "restore down" :(

### Expected Behavior

not "restore down" as in the older version

### Actual Behavior

result Windows terminal "restore down"

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13158 for more discussion.

/dup #13158

**Comment by jacol84** [comment]
Thanks i waiting for fix BUG ;)
