### ISSUE TITLE
Unable to launch with custom profile

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13175]
# Description of the new feature/enhancement
I want to have a dynamic profile which windows terminal can execute from command line. `wt -p "<pathToProfile.json>"` instead of giving it a set profile name and it only looking for the global settings.json. I am making a command line program and really don't want to have to edit a global settings.json every time a new background color / icon gets changed as editing that file may not be possible if it's already running in another instance. 

# Proposed technical implementation details (optional)
I want to have a custom profile json on command line boot which I looked for hours and it doesn't exist.

**Comment by zadjii-msft** [comment]
Could you maybe elaborate more on what you're trying to do with 

> I am making a command line program and really don't want to have to edit a global settings.json every time a new background color / icon gets changed

[Fragments ](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions) might fit the bill for what you're doing here. FWIW, the terminal's `settings.json` file can totally be written to while the Terminal is running. The Terminal should even be able to pick up those changes and hot-reload them. This has been used before [to hilarious extent](https://www.hanselman.com/blog/adding-reaction-gifs-for-your-build-system-and-the-windows-terminal)

**Comment by jredfox** [comment]
I need to dynamically detect the terminal exe icon it's executing and other settings as a custom profile. For example cmd as the terminal Java as the icon.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jredfox** [comment]
basically I launch it check if my custom json profile exists if not create it. Then I launch it using `wt -p "directory/to/my/CustomProfile.json`

**Comment by zadjii-msft** [comment]
Wait that's not how the commandline arguments for the Terminal work at all. You can't specify the path to another file of settings to use. 

For your scenario, you definitely want to create the profile as a fragment profile, stick it in one of the fragments paths (whatever's more relevant for your type of application), and then you should be able to invoke that profile with `wt -p {name of the profile you generated}`

**Comment by jredfox** [comment]
I know it's not in there yet that's why I wanted to specify a path or directory of paths to search for profile jsons and color jsons

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zadjii-msft** [comment]
We're tracking that specific request in /dup #6687. I suspect that fragment profiles will work for your use case today though.
