### ISSUE TITLE
Screen flicker after any input with new renderer enabled

### ISSUE THREAD

**Issue by ChrHorn** [microsoft/terminal#13173]
### Windows Terminal version

1.14.1432.0

### Windows build number

10.0.19043.0

### Other Software

GPU: Intel® HD Graphics 520 (Driver Version: 30.0.101.1340)

### Steps to reproduce

1. Enable experimental text rendering engine
2. Disable acrylic material
3. Choose Campbell colorscheme
4. Place the terminal windows in front of a dark background
5. Observe delayed flickering after typing a character

### Expected Behavior

No flickering

### Actual Behavior

This might be related to https://github.com/microsoft/terminal/issues/4528 but is also a bit different.

I only have this issue with the new renderer and **disabled** acrylic material. Enabling acrylic, even with the slider set to 100, fixes the issue.

The flickering is only visible with certain scheme/background combinations.

**Comment by thoellrich** [comment]
I'm seeing exactly the same behavior: with AtlasEngine enabled, there is a some serious flickering. Disabling AtlasEngine fixes the problem. 

Windows Terminal Version: 1.16.2524.0

Edition	Windows 11 Pro
Version	21H2
OS build	22000.978
Experience	Windows Feature Experience Pack 1000.22000.978.0

**Comment by lhecker** [comment]
I get the feeling that this is an MPO bug in the driver, but we'll see if #14959 fixes this, because it handles swap chains a bit differently.
