### ISSUE TITLE
The parameters are not executed correctly

### ISSUE THREAD

**Issue by jackyking-cn** [microsoft/terminal#13188]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19042.0

### Other Software

node v16.14.0
npm 8.3.1

### Steps to reproduce

run command:
npm config set @scope:registry https://npmmirror.com/

### Expected Behavior

![image](https://user-images.githubusercontent.com/1309499/170659837-665c8758-e5f2-4170-bc57-ac83d4a50ac2.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1309499/170659774-4a4ef0bc-5287-415e-8d8c-12855619e869.png)

**Comment by zadjii-msft** [comment]
What happens if you run that command in a "Command Prompt" tab in the Terminal/?

I'm guessing that because `@` is a special character in PowerShell, the command is being parsed differently by PowerShell than it is in Command Prompt.

**Comment by jackyking-cn** [comment]
It's right in cmd, so it's bug of PowerShell? 

![image](https://user-images.githubusercontent.com/1309499/170947707-f45904b2-8853-462c-adcd-d84426d823cd.png)



> What happens if you run that command in a "Command Prompt" tab in the Terminal/?
> 
> I'm guessing that because is a special character in PowerShell, the command is being parsed differently by PowerShell than it is in Command Prompt.`@`
