### ISSUE TITLE
Open with Terminal context menu item should've a submenu with all the profiles

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/terminal#13198]
# Description of the new feature/enhancement
Sometimes you want to open the current directory with a different profile than the default profile. It's not possible to use the "Open with Terminal" shell context menu for that and you need to manually copy the path and paste it or run the respective commands for the profile (eg: cmd.exe to use Command Prompt).

# Proposed technical implementation details
Add a submenu with a list of all the profiles which open the directory directly.

**Comment by j4james** [comment]
This sounds to me like issue #6111.

**Comment by Jaiganeshkumaran** [comment]
Oh I didn’t see that.
