### ISSUE TITLE
Ability to exit Fullscreen mode using mouse

### ISSUE THREAD

**Issue by hichemfantar** [microsoft/terminal#13196]
# Description of the new feature/enhancement

Currently, the only way to exit fullscreen mode is to use the keyboard shortcut, It would be nice to have the ability to exit fullscreen using the mouse

# Proposed technical implementation details (optional)

A good implementation would be one similar to google chrome, pushing the cursor to the top of the screen brings down an exit fullscreen button.
example: 
![image](https://user-images.githubusercontent.com/34947993/170839701-63817b0e-5575-4977-a4c1-e073d5cd0d17.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5677 for more discussion.

/dup #5677
