### ISSUE TITLE
Strange page redraws occur when resizing the window

### ISSUE THREAD

**Issue by reflyable** [microsoft/terminal#13207]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22598.200

### Steps to reproduce

adjust the window width

### Expected Behavior

![image](https://user-images.githubusercontent.com/71587404/171119275-334ab4f7-fa65-4c63-9766-5c8d51ce4929.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/71587404/171119355-77813d4b-7609-4cdd-a7fb-b108e8f48694.png)

**Comment by zadjii-msft** [comment]
This looks like #3088 to me, thanks!

/dup #3088
