### ISSUE TITLE
HDR "SDR Brightness" With Multiple Monitors Can Cause Acrylic Flicker

### ISSUE THREAD

**Issue by zamadatix** [microsoft/terminal#13200]
### Windows Terminal version

1.14.1452.0

### Windows build number

10.0.22621.0

### Steps to reproduce

2 (or more) HDR monitors in "Extend" configuration bordering each other with differing "SDR content brightness" values set:

![image](https://user-images.githubusercontent.com/343550/170904684-013f5f1d-3803-4cb7-a136-8ea15f001afe.png)

In my scenario I have 4 HDR displays in the following arrangement:

![image](https://user-images.githubusercontent.com/343550/170904712-acd5cf0a-f35b-40b5-a10c-be8234e346dd.png)

Monitors 1,3,4 are HDR with SDR brightness set to 20% while monitor 1 is HDR with SDR brightness set to 100%.

Once the monitor conditions are met make sure the Acrylic background is enabled. I haven't checked if the experimental renderer either snap the terminal window to be adjacent to monitors that have different SDR brightness values or wholesale span the WT window over multiple monitors. Now inside a single monitor move the cursor around and the WT window may flicker.

!!! Assumption Zone !!!
Suspected/Assumed cause of flicker: 1) The Acrylic effect strength seems to depend on the SDR brightness value. 2) For some reason having the WT window snapped causes it to think it's on the adjacent monitors 3) WT has some sort of race condition/selection issue with picking which monitor it is on (and therefore which SDR brightness value will be used) even though the mouse is just moving around inside of 1 monitor, sometimes not even over the WT window.
!!! Assumption Zone !!!

The easiest way for me to trigger the flicker is to snap WT to the left of monitor 2 and some other window (such as Settings) to the right of monitor 2. At this point any time I click on WT (to activate the Acrylic effect) then move my mouse to hover over Settings and back I will get flicker as it renders the Acrylic with different opaqueness (sometimes very gray, sometimes less gray).

As a note it does not matter if I use the experimental renderer or not, though the experimental renderer is enabled in this video.

### Expected Behavior

No flicker to occur as the mouse is moved inside the monitor.

### Actual Behavior

I have a demo video of both the effect below, it also shows how it doesn't matter what the SDR sliders are just that they not be the same across the bordering monitors at play:

https://user-images.githubusercontent.com/343550/170905952-1c10aec0-1e03-4c2c-891a-49829037fd20.mp4

**Comment by zadjii-msft** [comment]
Wow that looks really annoying. Does that repro with any other apps that use Acrylic? The [WinUI Controls Gallery](https://apps.microsoft.com/store/detail/winui-2-gallery/9MSVH128X2ZT) app is a good example of one that has some different acrylic surfaces.

I'm not sure how much we can do on our side with this - would you mind posting Feedback via the Feedback Hub, under "Display and Graphics > Windows HD Color (HDR and WCG)"/? If you share the link here, I can make sure it gets routed to the right folks ☺️

**Comment by zamadatix** [comment]
Hey Zadjii,

Thanks for the response! I can notice some very very slight redraw issues I think are related to this in certain apps but nothing quite as flashy. Unfortunately the Arcylic samples in the WinUI controls gallery wouldn't trigger it, I think because they didn't have layering on their examples. I wonder if there are almost 2 layers of interaction going on here, one with the root issue in Acrylic and another related to the automatic focusing and some race it has with the redraw issue.

What I'll do is start with the more base issue like you suggest since I was at least able to notice something in another app. Then once that's fixed I'll see if there is still any weird behavior left in WT or if that fixes it all. Appreciate you directing this to the right folks - feedback created as https://aka.ms/AAh5pmz

**Comment by zadjii-msft** [comment]
This got promoted internally to MSFT:39958690. Looks like they're investigating on the DWM side. I don't think there's anything else for us to be able to do here on the Terminal side of things. I've followed the internal thread for updates, I'll make sure to post here if there's anything to share. 

Thanks!

/dup https://task.ms/39958690
