### ISSUE TITLE
colortool utility sets foreground color to bright white upon exiting if ran with -c

### ISSUE THREAD

**Issue by george-tsiros** [microsoft/terminal#13214]
### Windows Terminal version

none

### Windows build number

10.0.22000.675

### Other Software

cmd.exe

### Steps to reproduce

run cmd
`color 70`
`colortool -c`

### Expected Behavior

foreground color is gray ("7")

### Actual Behavior

foreground color is white ("f")

**Comment by george-tsiros** [comment]
in program.cs, insert a copy of the lines 152 and 153 between lines 172 and 173

**Comment by zadjii-msft** [comment]
> in program.cs, insert a copy of the lines 152 and 153 between lines 172 and 173

Are we looking at the same file/? In the current `main`, these are the sections you called out

https://github.com/microsoft/terminal/blob/ed27737233714dea77877624d1beeb49e2ccd36e/src/tools/ColorTool/ColorTool/Program.cs#L151-L155
https://github.com/microsoft/terminal/blob/ed27737233714dea77877624d1beeb49e2ccd36e/src/tools/ColorTool/ColorTool/Program.cs#L168-L174

I don't really think that ~L172 is the right place to be restoring the console mode (and I don't think that would really work for this either...)


I'm also pretty sure that `-c` is _supposed_ to restore the previous attributes:
https://github.com/microsoft/terminal/blob/ed27737233714dea77877624d1beeb49e2ccd36e/src/tools/ColorTool/ColorTool/ColorTable.cs#L146-L149

**Comment by george-tsiros** [comment]
i had v1.0.0.0

**Comment by george-tsiros** [comment]
please close this issue completely, it was my mistake

**Comment by zadjii-msft** [comment]
No worries, glad you figured it out!
