### ISSUE TITLE
Option to start Terminal at Windows startup minimized to tray, ready for summon / quake mode

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#13210]
This will offset / hide some time spent at Terminal initialization and avoid big icon of Terminal at the app bar and instead put it into tray.

I looked for other requests, a related one is https://github.com/microsoft/terminal/issues/12928, https://github.com/microsoft/terminal/issues/5907, https://github.com/microsoft/terminal/issues/12887

Also exactly this request was first proposed in the comment https://github.com/microsoft/terminal/issues/5907#issuecomment-875802210

Please feel free to close if duplicate

**Comment by j4james** [comment]
I think what you're trying to achieve could probably be covered by issue #7374. If we had a `-minimized` command line option, you could just create a shortcut with that set, and dump it in the Windows startup folder.

**Comment by vadimkantorov** [comment]
I am proposing minimizing to tray (and thus a tray icon), not just minimized. Having a tray icon mode probably would incur some other changes...

It would be best to enable this as an option in settings (as it exists in many other apps). In 20 years of using Windows I haven't manually used the Windows startup folder, so I guess many users would just abandon it if it's not available in settings...

**Comment by j4james** [comment]
> It would be best to enable this as an option in settings

Fair enough. It's worth mentioning, though, that there is already a setting to make the terminal minimize to the system tray ([`minimizeToNotificationArea`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#minimize-to-notification-area)), and there is also a setting to launch on Windows startup ([`startOnUserLogin`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#launch-on-machine-startup)). It's really just the minimized launch mode that you're missing - although maybe that's something you'd only want for a startup launch.

See also issue #10448.

**Comment by naikrovek** [comment]
Seems like a shortcut in the user Startup menu folder could set it to start minimized:

![image](https://user-images.githubusercontent.com/284498/171442017-e76c8785-ac18-4cf3-8e85-ec216c884bad.png)

**Comment by zadjii-msft** [comment]
I think the thread you're _really_ looking for is #9996. That's the generic "have the terminal run silently at startup, waiting for a `globalSummon` invocation". 

I'd continue the discussion there, thanks alll!

/dup #9996

**Comment by ImGGAAVVIINN** [comment]
> Seems like a shortcut in the user Startup menu folder could set it to start minimized:
> 
> ![image](https://user-images.githubusercontent.com/284498/171442017-e76c8785-ac18-4cf3-8e85-ec216c884bad.png)

He wants to minimise the terminal **TO TRAY** not just minimised

**Comment by naikrovek** [comment]
> He wants to minimise the terminal **TO TRAY** not just minimised

yep i'm a moron

**Comment by winchestercanal** [comment]
> Seems like a shortcut in the user Startup menu folder could set it to start minimized:
> 
> ![image](https://user-images.githubusercontent.com/284498/171442017-e76c8785-ac18-4cf3-8e85-ec216c884bad.png)

Hello, I was using this suggested solution until a few weeks ago, but recently this has stopped working, and the terminal is opening in a normal window, instead of starting minimized! Did you have any change in the system that is preventing this?

**Comment by ghost** [comment]
> > Seems like a shortcut in the user Startup menu folder could set it to start minimized:
> > ![image](https://user-images.githubusercontent.com/284498/171442017-e76c8785-ac18-4cf3-8e85-ec216c884bad.png)
> 
> Hello, I was using this suggested solution until a few weeks ago, but recently this has stopped working, and the terminal is opening in a normal window, instead of starting minimized! Did you have any change in the system that is preventing this?

I make a batch file
```
wt -w _quake
wt -w 0 pwsh -Command "(New-Object -ComObject Shell.Application).MinimizeAll()"
```
and set add it to start-up with a shortcut in the start-up folder (you can also use task scheduler).
