### ISSUE TITLE
tab-title

### ISSUE THREAD

**Issue by JoeABCDEF** [microsoft/terminal#13213]
### Windows Terminal version

1.14.1451.0

### Windows build number

10.0.19044.0

### Steps to reproduce

![image](https://user-images.githubusercontent.com/39638510/171312230-57c2cc69-d7d5-4550-a30c-55ecbc113dca.png)
When enabled, any command executed with PowerShell will replace the tab-title

### Actual Behavior

Only want PowerShell to use the Modify tab-title command to make changes

**Comment by zadjii-msft** [comment]
Sorry for the delay, we've got quite the backlog to get through. 

I just tested this locally and I can't repro this. 

Did you make sure to save the settings, and open a new PowerShell tab after changing that setting/? I'm not sure if that setting will hot-reload...
