### ISSUE TITLE
Add font-fallback

### ISSUE THREAD

**Issue by r-hoogenboom** [microsoft/terminal#13215]
# Description of the new feature/enhancement

Currently the console(terminal) seems to have no support for fallback of glyphs missing from the currently selected font to other installed font that does have the glyph, like firefox does. It would be nice if that could be added.

# Proposed technical implementation details (optional)

For instance, the [unicode code block for legacy computing](https://www.unicode.org/charts/nameslist/c_1FB00.html) is very poorly supported in almost all fonts. There is a [font on github](https://github.com/dokutan/legacy_computing-font) that provides support for that block, which can be selected in the console when installed. The thing is that you select that font, you don't see the normal character glyphs, you select a regular console font, you don't see the glyphs from the legacy computing block. I would like to see that when a code point is output to the terminal that doesn't have a glyph in the current font, a glyph is taken from another font as a fallback instead of showing a square.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2664 for more discussion.

/dup #2664
