### ISSUE TITLE
README.md link to roadmap-2022.md and update roadmap

### ISSUE THREAD

**Issue by CypherAus** [microsoft/terminal#13222]
G'day
Love this product.  Please update the main README.md  to link direct to the new roadmap-2022.md  and also update the roadmap.

Also: Q: When will Terminal be bundled into Windows by default?
Thanks!

**Comment by zadjii-msft** [comment]
Meh, sure, we should probably update the roadmap. Thanks for the reminder!

> When will Terminal be bundled into Windows by default?

It already is in Windows 11 😉

**Comment by CypherAus** [comment]
> It already is in Windows 11 😉
But that is NOT production ready (it's the modern Vista/Win 8).  Win 10 is where the action is
