### ISSUE TITLE
Terminal window usually opens with last few lines offscreen, requiring dragging window up

### ISSUE THREAD

**Issue by tomviolin** [microsoft/terminal#13228]
# Description of the new feature/enhancement
There needs to be an option (or possibly default behavior) in which a new Terminal window's position automatically adjusts so that the entire Terminal character display is onscreen.  

When the Terminal window opens with the last few lines offscreen, after a few commands the current prompt is not visible, requiring the user to stop typing, grab the mouse, and drag the window up.  Worst case, the vertical size of the Terminal character display area exceeds the height of the screen, thus requiring both a resize downward of the window size using the top edge followed by dragging a part of the top tab area up to reveal the last few lines of the Terminal display.  People who use Terminal are likely to be mostly typing commands and code, and it is very disruptive to have to stop typing and resize and move the Terminal window, every. single. time. a. new. terminal. window. is. opened.

# Proposed technical implementation details (optional)

Append an adjustment calculation to the end of the current routine that calculates the position of a new Terminal window to move it and/or resize it such that the entire character display is visible on-screen and above any non-autohiding taskbar.

This could be an option, in case there are users who like the way it works now.  But there probably aren't many.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #11781 for more discussion.

/dup #11781
