### ISSUE TITLE
Passing doskey alias file to commandline not working

### ISSUE THREAD

**Issue by nearcatch** [microsoft/terminal#13224]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19044.1645

### Steps to reproduce

Trying to use an alias.cmd file as mentioned in [this issue](https://github.com/microsoft/terminal/issues/4019#issuecomment-567427024).

Profile in settings.json:
```json
            {
                "altGrAliasing": true,
                "antialiasingMode": "grayscale",
                "closeOnExit": "graceful",
                "commandline": "cmd.exe /K \"C:\\Users\\Jason\\alias.cmd\"",
                "elevate": false,
                "guid": "{7a1c5dd6-779d-4b81-9599-8cbe559fc419}",
                "hidden": false,
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
                "name": "Command Prompt",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
            }
```
alias.cmd:
```batch
@echo off
doskey s=ssh $*
```

### Actual Behavior

Commands are not available when I open Terminal, but they become available after I manually run alias.cmd from the Terminal window.

**Comment by vefatica** [comment]
It's only a workaround, but I have my DOSKEY macros defined in CMD's "autorun" file, specified here:

```
regdir /v /d "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor"
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
  Autorun : REG_SZ : d:\uty\cmdstart.bat
```

It works.

**Comment by vefatica** [comment]
I misspoke.  My "autorun" file looks like this.

```
v:\> type u:\cmdstart.bat
@echo off
doskey /macrofile=d:\uty\doskey.txt
chcp 1252 > NUL
```

**Comment by vefatica** [comment]
FWIW, this works here, that is, the CMD file is executed.

`"commandline": "%SystemRoot%\\System32\\cmd.exe /K \"v:\\foo.cmd\""`

**Comment by nearcatch** [comment]
> FWIW, this works here, that is, the CMD file is executed.
> 
> `"commandline": "%SystemRoot%\\System32\\cmd.exe /K \"v:\\foo.cmd\""`

doesn't work for me, unfortunately. I've tried adding the `%SystemRoot%\\System32\\` portion and also using `/` instead of `\\`. No joy 🙁
