### ISSUE TITLE
Make Open JSON file easier to discover

### ISSUE THREAD

**Issue by a5hk** [microsoft/terminal#13225]
# Description of the new feature/enhancement
Once in a while I want to change something in the JSON settings file, and many times I spend several minutes to find that option. It mostly happens when the window is maximized. The button is too far away from the rest of the options.

![image](https://user-images.githubusercontent.com/5412540/171995491-4ba53e72-d9aa-4cbc-b407-ec2c32908517.png)

# Proposed technical implementation details (optional)
I think it can be added to this menu:

![image](https://user-images.githubusercontent.com/5412540/171995636-1c4a5959-adf2-4c5c-a6d9-9405af17cf70.png)

**Comment by 237dmitry** [comment]
As a variant you can create environment variable or shell variable. I create in pwsh's profile `$WT_SETTINGS` var:

![Screenshot 2022-06-04 140059](https://user-images.githubusercontent.com/78153320/171996189-bbc97b45-648b-419e-8c5a-335267c2f743.png)

And edit file in your favorite editor, for example:
```powershell
> notepad $WT_SETTINGS
```

**Comment by DHowett** [comment]
You can also get to the JSON file by holding down <kbd>Shift</kbd> and clicking on the "Settings" menu item, my pressing <kbd>Ctrl+Shift+,</kbd>, or by opening the command palette with <kbd>Ctrl+Shift+P</kbd> and searching for `JSON`.

Are any of those sufficient?

**Comment by a5hk** [comment]
> Are any of those sufficient?

I first learned about the settings file through UI. Now that I know a JSON settings file exists, the last option is sufficient for me, I won't forget that one. However, the command is "Open settings file", searching `JSON` didn't work for me. I have version `1.12.10982.0` installed.

**Comment by a5hk** [comment]
> Looks like that string doesn't actually have "JSON" in it - should it?

IMO having JSON in that string would make the command more discoverable, at least for VS Code users:

![image](https://user-images.githubusercontent.com/5412540/172194668-5da330b0-0ac7-4877-8fa3-2fcb12ec57db.png)

**Comment by zadjii-msft** [comment]
Discussion:
* Yes we should change the string to "Open settings file (JSON)" with json locked
* We should also probably add a tooltip to the New Tab dropdown entry as well

**Comment by vadimkantorov** [comment]
> Discussion:
> 
> * Yes we should change the string to "Open settings file (JSON)" with json locked
> * We should also probably add a tooltip to the New Tab dropdown entry as well

Related: https://github.com/microsoft/terminal/issues/10354, sometimes "settings file" is clearer, sometimes "json", but consistency is even more important IMO
