### ISSUE TITLE
Too many tabs will be greater than tab windows - truncate titles?

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1322]
Using git master as of today. Opening a bunch of tabs will quickly fill the tab bar:

![image](https://user-images.githubusercontent.com/172594/59772798-5f240a00-92a4-11e9-9b9b-274cc27cae63.png)

Other terminals would shorten `C:\Program Files\PowerShell\6\pwsh.exe` to just `pwsh.exe` or `pwsh` - this would make more room (also, in many cases, `pwsh` is more relevant than the full path).

**Comment by DHowett-MSFT** [comment]
This will almost certainly be #597 and #608. Please make sure to search for existing issues!
