### ISSUE TITLE
Feature request: default profile colors should follow system theme and toggle as needed

### ISSUE THREAD

**Issue by csdvrx** [microsoft/terminal#13226]
# Default profile colors follows system theme and toggles as needed

Most apps are getting a dark profile (ex: Notepad) with 3 options for the app theme:
 - use system setting
 - dark mode
 - light mode

Windows Terminal should do the same, and have a default setting to "use system setting", with a definition of which one of the color schemes is to be considered as the "default light" and which is "default dark", yet with a possibility of a user override to customize the defaults as explained below

The feature could easily start with themes having both a light and a dark mode (if so, populate both the default light and default dark fields) 

For example:
 - default= Tango
 - default light = Tango Light
 - default dark = Tango Dark

It is already possible to partially emulate this feature, by defining a shortcut for color themes, then manually changing the theme of each tab as needed, but it is cumbersome.

# Proposed technical implementation details

The feature could also easily be extended to themes having only one mode: selecting Campbell as the default could either have a default light empty and therefore prevent the toggle (maybe a bad idea, as the default choice may then not follow the user wishes if the user goes to system preferences to set a system wide light theme) or a "best guess" based on the profiles self-identifying as light (One Half Light, Solarized Light, Tango Light) which would preserve the functionality.

This would mean for example:
 - default= Campbell (custom)
 - default light = One Half White
 - default dark = Campbell

The self-identification of profiles as light or dark could be a checkbox or automated as a regex based on matches within the names.

A new key action definition might be added to complement that feature in case the user does not want to follow the system theme yet toggle on demand between light and dark mode with a scope limited to the Windows Terminal

# Possible controversy

It might be argued that this would cause the default profile of Windows Terminal becoming light instead of dark, which could be disconcerting to users.

However, it would also match the large-scale change between Windows 10 and Windows 11 towards a light theme, now being the default for both the taskbar and start menu.

This means Windows Terminal would be "in line" with this change and match Windows 11 visual identity.

# Environmental impact

OLED screens power consumption is increased by light theme and decreased by dark themes.

Therefore, the change may cause a slight increase of power consumption for computers 1) having a OLED screen 2) using Windows Terminal in full screen 3) having disabled any screensaver / locker / power saving / sleep / suspend feature

However, such computers would already do that with every other software in a light theme (ex: text editors...) and the additive requirements of point 1+2+3 means only a very small number of computers is likely to really be impacted.

# Health impact

This change might be desirable if only for public health reasons.

For example, while there is to the best of my knowledge no large scale randomized controlled trial, light mode starts being recommended in case of astigmatism.

Check the following examples, case reports or discussions:

 - What is astigmatism https://www.visioncenter.org/blog/astigmatism-lights/

 - Why you may want to avoid dark mode https://www.androidauthority.com/dark-mode-1046425/

- A case report of dark mode having worsened eyesight https://medium.com/geekculture/dark-mode-has-worsened-my-sight-de54b8fe0455 

 - A discussion of whether dark mode is a good idea https://news.ycombinator.com/item?id=23496286

Regarding the balancing of environmental impact and health impact, by leaving the choice to the user, with an easy possibility of override, the feature should not be controversial

**Comment by j4james** [comment]
See issue #4066.

**Comment by zadjii-msft** [comment]
This is a great write up, for sure. It's basically a whole spec onto itself. We did recently just accept a spec for #4066 in #12613, so go check that out. If you feel that spec doesn't adequately address everything you've got here, feel free to follow up in that thread. Thanks!

/dup #4066

**Comment by csdvrx** [comment]
@zadjii-msft Thanks for the information! I wish I had known it was already done, I wouldn't have written the whole spec then :) My fault for not checking on WT news recently!

In the #12613 writeup for #4066, you do not include the ESG pros and cons (health benefits, power savings concerns) which may play against the feature: most terminal users prefer a "white text on dark background", and may want this tradition to remain as the default even if it conflicts with the Windows 11 theme and health benefits for people with astigmatism.

I would suggest you copy-paste the last 3 paragraphs (Controversy, Environmental impact, Health impact) to address in advance the vocal traditionalist who may decry the use of a light theme by default.

In case there's any licensing issue, I release everything I wrote in this ticket in the public domain.

Unrelated- do you have any idea when we might see the feature? It seems like a very simple addition!

Thanks!
