### ISSUE TITLE
[Settings UI] Adding an action with no key chord hits an assert

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#13221]
### Windows Terminal version

main @ 9dca6c2

### Windows build number

doesn't matter

### Other Software

none

### Steps to reproduce

1. Go to Settings > Actions
2. Add a new keybinding with an empty key chord	
3. hit save

### Expected Behavior

We should require a key chord before adding the action.

### Actual Behavior

[Debug mode] hit an assert in `KeyChord`: `assert(_vkey || _scanCode);`
[Otherwise]
- nothing happens
- if you try to add another keybinding like this, it detects a conflict with another action that has that "key chord"

**Comment by zadjii-msft** [comment]
Putting this in 1.15 cause _how did this ever work_. I suppose it was always just the "keybindings" page, not the "actions" page so much.
