### ISSUE TITLE
Icon tweak: `>' is in two parts - connect it and fold it?

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1323]
# Summary of the new feature/enhancement

After the [new icon was announced on twitter](https://twitter.com/cinnamon_msft/status/1141040460716134401) with the '>' character in two parts...

![image](https://user-images.githubusercontent.com/172594/59773914-5cc2af80-92a6-11e9-8793-9779e2100f26.png)

[Quite a few people liked a suggestion to connect the '>' character](https://twitter.com/mikemaccana/status/1141097460443602946), maybe like the vscode icon:

![image](https://user-images.githubusercontent.com/172594/59773688-f3db3780-92a5-11e9-8f37-93de9f813de0.png)

[Smallfox mocked up this, which looks better](https://twitter.com/smallfoxx/status/1141335873067331584):

![image](https://user-images.githubusercontent.com/172594/59773655-e32ac180-92a5-11e9-8492-8ad84183d041.png)

Or, with a [more realistic curve](https://twitter.com/P_Jaschkowske/status/1141358112605134851):

![image](https://user-images.githubusercontent.com/172594/59778630-c5ae2580-92ae-11e9-85e6-188e6baddf56.png)

@cinnamon-msft what do you think?

**Comment by DHowett-MSFT** [comment]
I'm not Kayla, but I'd like to ask that we get a chance to flight the new icon before we go and change it to match somebody else's design language because it "looks better that way". Thanks! 😄

**Comment by mikemaccana** [comment]
@DHowett-MSFT it's a small tweak not a big change

> because it "looks better that way".

That's a mischaracterization of this issue 😕. If you're unsure of the reason for the change, please read the title of this issue.

**Comment by cinnamon-msft** [comment]
Love all the contributions you have been making! I understand modifying the icon to align more closely with VS. However, I'm in agreement with @DHowett-MSFT that we should get a chance to flight the new icon before making alterations. I'm happy to revisit this if a large amount of the community is in agreement 😊

**Comment by mikemaccana** [comment]
@cinnamon-msft Totally understood re: wanting to wait. Why close the issue though?
