### ISSUE TITLE
Terminal introduces weird behavior when changing window/buffer size using C# code.

### ISSUE THREAD

**Issue by tizu69** [microsoft/terminal#13232]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

Visual Studio 2022 (IDE)

My application with following code:
```
Console.SetWindowSize(
  Math.Min(150, Console.LargestWindowWidth),
  Math.Min(60, Console.LargestWindowHeight));
```
While not mentioned here, changing the buffer size using `Console.SetBufferSize(...);` also has this behavior. 

### Steps to reproduce

Run a C# console application with the above-mentioned lines of code.

### Expected Behavior

The window or buffer should resize.

### Actual Behavior

I haven't quite found everything out yet, but it seems like it

- adds a scrollbar (I checked, has nothing to do with buffer)
- keeps the original window size
- places the actual content randomly inside the scroll area
- clearing the screen (`Console.Clear();`) seems to do nothing, attaching text written after that will just append below

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5094 for more discussion.

/dup #5094
