### ISSUE TITLE
Unexpected ANSI sequence behavior in cmd.exe

### ISSUE THREAD

**Issue by Zeek05** [microsoft/terminal#13231]
### Windows build number

Microsoft Windows [Version 10.0.22000.675]

### Other Software

cmd.exe

### Steps to reproduce

Apply any SGR sequence that affects character attributes in cmd.

### Expected Behavior

![IMG_9665](https://user-images.githubusercontent.com/61340927/172073492-c08616b5-00cb-41bd-a573-899bc12ea869.png)

 **LEFT:** You can see that the ANSI escape sequences in Windows Terminal are working as intended.

### Actual Behavior

**RIGHT**: These changes are not propagating to CMD.exe, resizing the screen creates this bleeding effect.

This issue is related to #32

**Comment by Zeek05** [comment]
I had contacted MS support for this issue and they redirected me to this GitHub. I am not sure how this is relevant to Terminal but, I am using cmd.exe and this place seems the most relevant.

**Comment by DHowett** [comment]
> I am not sure how this is relevant to Terminal 

Good news! The code for Windows Terminal *and* the legacy console window are both here in this repository.

I bet you're seeing an issue we've since fixed, where attributes get extended across the screen when the window is resized. That was #32, and it applied to any text styling (color, underline, hyperlink, ...)

What is `tat`?

**Comment by Zeek05** [comment]
> > I am not sure how this is relevant to Terminal
> 
> Good news! The code for Windows Terminal _and_ the legacy console window are both here in this repository.
> 
> I bet you're seeing an issue we've since fixed, where attributes get extended across the screen when the window is resized. That was #32, and it applied to any text styling (color, underline, hyperlink, ...)
> 
> What is `tat`?

tat is an application I am developing.

Shortest explanation is, it simply sends the escape sequences to STDOUT.
So, when I do `tat underline` it's just emitting the underline escape sequence to stdout

I have the latest version of windows and conhost, I am not sure why the bug is persisting then? This was screenshot yesterday..

**Comment by 237dmitry** [comment]
Resizing terminal window works as `%esc%[0m`

![Screenshot 2022-06-06 130742](https://user-images.githubusercontent.com/78153320/172141005-54be4a3d-39ec-4c7b-a33c-22fff6fb79b8.png)
