### ISSUE TITLE
Using 'left' in shortcuts produces an unreadable settings file

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1324]
Using SVN master as of today, modifying the inbuilt shortcuts to use `left` or `right` produces a syntax error:

```json
            {
                "command" : "prevTab",
                "keys" : 
                [
                    "ctrl+shift+left"
                ]
            },
```
![image](https://user-images.githubusercontent.com/172594/59782017-f8f3b300-92b4-11e9-99d9-5114ac2ca928.png)

As the other arrow keys are referred to as `up` and `down` I presume `left` and `right` should work too.

**Comment by DHowett-MSFT** [comment]
Alas! We might have missed that when we switched from git to subversion. I'll tag this one for `0.3` :wink:

**Comment by DHowett-MSFT** [comment]
Related: #1212

**Comment by mikemaccana** [comment]
Thanks Dustin!

**Comment by zadjii-msft** [comment]
@mikemaccana I'm gonna psychic debug and guess that you're trying to add the `left` keybinding while the terminal is open, right?

Something seems to have regressed hot-reloading the settings file, _really badly_ in the last couple days. We're investigating in #1325

**Comment by mikemaccana** [comment]
@zadjii-msft Please stop reading my mind, I have a lot of private thoughts I'd like to keep that way. 😁 Yep that's correct, terminal open.

**Comment by zadjii-msft** [comment]
Yep, that's the one. I'll close this as #1325 is the real problem here
