### ISSUE TITLE
Light tab color causes unreadably dark foreground (text) color when the tab is not focused

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/terminal#13246]
### Windows Terminal version

1.12.10982.0

### Windows build number

Microsoft Windows [Version 10.0.19043.1706]

### Other Software

None

### Steps to reproduce

1. Start MS terminal
2. Open a total of 2+ tabs
3. Make sure that you're running a 'Dark' theme
4. Set the color of a tab to be bright enough that the foreground text switches to black (the 'Teal' option seems to work well - it's custom color is `#05FFEE`)
5. Focus a tab (let's call it "Tab A") and bask in the readable text.  The tab color is that nice, bright teal and the text has automatically been made black, an easy-to-read, high contrast color.
6. Switch to a different tab.  Notice that Tab A's tab color is now very dark / dim (which is a very reasonable way to convey to the user that the tab isn't currently focused).  Notice also that the text color is still black, and thus unreadable.
7. Look upon incredibly low contrast, unfocused Tab A and weep, for there is no possible way to read that text.

### Expected Behavior

I'd love to be able to read the text on my unfocused tabs, even if I choose a light tab color for them.

I *think* what might solve this is: when a tab becomes unfocused and you dim the tab go back and adjust the foreground (text) color to be white.

### Actual Behavior

Foreground color remains black.

I can't read black text on a really, really dark tab.

Oh boy is it hard to see what 

Cue the weeping :)

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/172600385-0eca6d48-26ac-410c-b7dc-1a5784646ee7.png)


Shouldn't be too hard to set the unfocused text color based on the contrast with the unfocused color. Tricks will be:
* Do we actually control the unfocused color in this scenario? Or are we just letting WinUI apply some default amount of transparency on top of the tab view item
* Does the TabViewItem actually have a resource for it's unfocused text color, separate from the focused tab text color?
