### ISSUE TITLE
AWS/GCP Cloud Shell Connector

### ISSUE THREAD

**Issue by ampacheco-kubtec** [microsoft/terminal#13245]
# Description of the new feature/enhancement

One of my preferred features of Terminal and WSL is the possibility to manage in the terminal Azure Subscriptions.

I'd really appreciate it if you can extend that functionality to other cloud providers like [AWS](https://docs.aws.amazon.com/cloudshell/latest/userguide/getting-started.html) and [GCP](https://cloud.google.com/shell).

![azureCloudShell](https://user-images.githubusercontent.com/66849132/172516978-8ecc3e1c-d170-4968-8c1d-6d6b46f22c26.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This seems like a perfectly reasonable request for an extension, along the lines of the other connection types mentioned in #4000. I'll add this to that list, to keep in mind when designing that functionality. For work tracking purposes, I'd say it's pretty unlikely that we'll ship this ourselves. A perfectly fine idea for us to enable, and someone else to ship 😉
