### ISSUE TITLE
Wild behavior from ANSI esq in batch variables

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13255]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1706

### Other Software

java

### Steps to reproduce

`wt new-tab --focus --title "Test App 1.0.0" -d "C:\Users\jredfox\Documents\dev\OpenTerminal" -p "Command Prompt" cmd /c call "C:\Users\jredfox\AppData\Roaming\OpenTerminal\scripts\boot\boot.bat" "[48;2;0;255;255m[38;2;255;255;255m" "Test App 1.0.0" ",C:\Program Files\Java\jre1.8.0_333/bin/java, -Dot.l -cp ,C:\Users\jredfox\Documents\dev\OpenTerminal\bin, jml.ot.OTMain" "true"`

the batch file
```batch
@ECHO OFF
IF NOT "%~1%" == "" (
   echo "%~1%"
   cls ::hotfix for Windows Terminal
)
title %~2%
set boot=%~3
set boot=%boot:,=^"% ::RE-MAP the boot command to double quotes
call %boot%
IF "%~4%" == "true" (
set /p DUMMY=Press ENTER to continue...
)
exit 0 ::Work around from a command prompt bug
```

It opens up like 20 tabs instead of one. with the ansi escape sequence in the batch variable string. 

### Expected Behavior

it opens up the my java program in wt with the colored output. 

### Actual Behavior

instead it opens up 20 tabs. it's having some wild behavior. switching to conhost.exe and cmd fixes the issue. I am going to work around this by changing the ansi escape to another character but this is just very silly

**Comment by DHowett** [comment]
This may be because wt treats `;` as a subcommand separator. It's intended for use in composite commands, such as `wt new-tab ; split-tab`, but it can also be used to launch a number of programs side by side (`wt cmd ; pwsh ; wsl`).

Your best bet would be to escape them, or use `--` as a WT command terminator (which may not work, honestly, I don't remember if it applies before or after `;` splitting.)

**Comment by jredfox** [comment]
but it's inside of the scripts `""` is this not a bug?

**Comment by DHowett** [comment]
We should probably leave things in quotes alone. I suspect that we do, *if* the quote is sent to us. Quoted string parsing is one of the inconsistencies in shell command line handling across all of Windows, so I bet you'll get different results depending on what shell you call wt from.

**Comment by jredfox** [comment]
@DHowett like this it has the same result `wt new-tab --focus --title "Test App 1.0.0" -d "C:\Users\jredfox\Documents\dev\OpenTerminal" -p "Command Prompt" -- cmd /c call "C:\Users\jredfox\AppData\Roaming\OpenTerminal\scripts\boot\boot.bat" "[48;2;0;255;255m[38;2;255;255;255m" "Test App 1.0.0" ",C:\Program Files\Java\jre1.8.0_333/bin/java, -Dot.l -cp ,C:\Users\jredfox\Documents\dev\OpenTerminal\bin, jml.ot.OTMain" "true" 
`

**Comment by jredfox** [comment]
Also replacing the `;` to `,` resulted in windows terminal instantly closing upon open. changing the `;` to a non special character fixes it. nothing like this happens with batch files I think the issue is caused by not only `�` but also `;` and it's ignoring the fact that it's inside a parameter

**Comment by zadjii-msft** [comment]
IIRC we had to do the subcommand splitting on `;` before the `--` parsing. The `--` is handled by CLI11, but we hand each "subcommand" to CLI11 separately. This is definitely a tricky edge case. Case in point

```
wt nt -- foo.exe "bar;baz" "nt;nt ; nt"
```

Should that get split into subcommands? Probably, right? I know there are folks just doing `wt nt;nt;sp` in the wild, so we can't rely on spaces by the `;`.

I'm not sure this could be fixed without some sort of slightly breaking change, but if anyone's got a good idea I'm open to it.

**Comment by jredfox** [comment]
Linux has -e then a string command. Since you have the ability for multiple commands what about only slices it into new commands if the meta chars are outside of the quotes to begin with. It would work regardless of a single parameters or multiple called by a program. This includes but not limited to :;,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zadjii-msft** [comment]
#13264 is a little closer to the target here, so we're gonna use that one here. Thanks!

/dup #13264
