### ISSUE TITLE
Option to mute terminal which is remembered between sessions

### ISSUE THREAD

**Issue by debeshmandal** [microsoft/terminal#13274]
# Description of the new feature/enhancement

A button/option/field in the settings file/keyboard shortcut/command that allows for quick muting of the entire terminal window.

## Current behaviour:
  - Everytime I open the terminal, I use Ubuntu via WSL2, and inevitably type something like `cd` and then hit the TAB key many times to view my directory
  - This smashing of the TAB key throws the terminal error sound
  - To prevent the sound, I open up Volume Mixer and manually mute Windows Terminal, which mutes the current window
  - For each new window, repeat the above step

## Example Desired Behaviour (e.g. from drop-down command palette menu)
  - When I open Terminal, I click on the small arrow next to the new tab button (a ➕ sign)
  - In between `Move tab forward` and `New tab` there is a button called `Mute Window`
  - I click it and it mutes the window
  - Next time I open a Terminal, this mute is remembered so I can smash my tab key in peace
  - If I want to unmute the window, in the same command palette at the end of `Toggle terminal visual effects` there is a new option called `Unmute Window` which reverses the mute and is remembered between sessions.

This should summarise the idea of the desired behaviour, although I appreciate there may be a better way than using a `Mute`/`Unmute` setting regarding UI/UX for users to mute the window, so am open to suggestions.

# Proposed technical implementation details (optional)

I unfortunately have no idea how you control system sounds via applications in Windows but would be interested in learning from an experienced user 😄

**Comment by zadjii-msft** [comment]
Sounds like you're looking for the [`"bellStyle": "none"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#bell-notification-style) setting/?

**Comment by debeshmandal** [comment]
Thanks! That was what I was looking for 👍
