### ISSUE TITLE
terminal open twice

### ISSUE THREAD

**Issue by hmz22** [microsoft/terminal#13272]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.708

### Steps to reproduce

when open terminal run twice window and one have old session and other new terminal and so when right click on folder and open with window terminal .

### Actual Behavior

why any new update have new bug? my last post have lag issue https://github.com/microsoft/terminal/issues/13105 
and this version new bug.

**Comment by hmz22** [comment]
u can see in this video:


https://user-images.githubusercontent.com/36853974/173300287-de083a6e-f202-48f2-b578-f33a9a480cd9.mp4

**Comment by zadjii-msft** [comment]
Do you have the [`"firstWindowPreference": "persistedWindowLayout"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session) setting enabled/? This sounds by-design to me. It's like if you have the (similar) setting enabled in chrome/edge, and type `MicrosoftEdge.exe github.com` at the commandline. Edge will open with your previous tabs, _and_ the new thing you reqeusted.

**Comment by naikrovek** [comment]
You have two things selected when you choose that context menu item, so both open.

neither opens with enough time to fully launch before the second opens, so there is no window for the other “Open in Terminal” action to grab on to.

There may be an argument for the shell to open one, pause, the open all others for this particular context menu item, but that isn’t something this project has control over, to my knowledge.

**Comment by hmz22** [comment]
Yes I Have in setting and remove it. I think solved.
thx
