### ISSUE TITLE
Start menu broken behavior because of Microsoft terminal

### ISSUE THREAD

**Issue by Ruslancheg11** [microsoft/terminal#13273]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.0

### Steps to reproduce

 1) Install windows terminal
 2) Open start menu
 3) Click on Documents/Downloads/Music/Pictures/Videos/Personal folder in the start menu
![image](https://user-images.githubusercontent.com/88016602/173180001-a3c37530-4fef-42d6-9476-7b089b930181.png)

### Expected Behavior

 After click on any of these folders, usually start menu does hide and focus is turning onto just opened folder

### Actual Behavior

 Start menu doesn't hide, and focus doesn't turn onto just opened folder

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #7122 for more discussion.

/dup #7122
