### ISSUE TITLE
copying text for CLI program kills program

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13279]
### Other Software

java or any cli program

### Steps to reproduce

steps to reproduce. create a simple java program a dummy program for testing
```java
public static void main(String[] args)
{
   while(true);
}
````
run
```
wt new-tab java -jar myprogram.jar
```
hit control+c

notice the app is dead. the user was simply trying to copy and paste previous output and the program died. right clicking to copy something in wt isn't possible and most people are use to using control+c for copy as it is everywhere else in windows.

### Expected Behavior

app stays alive and text is copied to the clipboard

### Actual Behavior

app dies

### Solution
use a different keybind to close the process like control+fn+c or control+alt+c

**Comment by zadjii-msft** [comment]
* Do you have <kbd>Ctrl+C</kbd> bound to `copy` in your settings/?
* Did you select text before hitting <kbd>Ctrl+C</kbd>?
* > right clicking to copy something in wt isn't possible 
  
  It uh, very much should be. Does that not work with text selected?
* > use a different keybind to close the process

  Ctrl+C is a pretty standard signal for interrupting the current commandline process across platforms. We've also shipped <kbd>Ctrl+Shift+C</kbd> as a standard `copy` keybinding for this reason. 



This sounds by-design to me. When there's no text selected, then pressing the `copy` action's keybinding will fail to copy (because there was nothing to copy), and fall through the to the CLI application running in the Terminal to be able to process it.

**Comment by zadjii-msft** [comment]
Sure, but every _commandline_ application in history _does_. Hence why we've predicated the behavior on having a selection. It's a relatively graceful way to support both copying and terminating on <kbd>Ctrl+C</kbd>. So long as you've actually made a selection, <kbd>Ctrl+C</kbd> won't send the `^C` to the running app.

**Comment by jredfox** [comment]
Well I suggest changing it it's the opposite over user friendly. If people actually started to use cli programs again people would quit because of this issue. Imagine a person who barley knows control c and control c because of Minecraft tries to run a Java jar or exe file through win terminal and it keeps randomly closing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by naikrovek** [comment]
@jredfox the current behavior is correct.  In command-line applications, CTRL+C kills the running process, and doesn’t copy highlighted text.  Highlighting with the mouse alone is what copies to the clipboard (right-clicking will copy and deselect in cmd.exe as it always has.)

experienced users will definitely not be surprised with this behavior.

**Comment by jredfox** [comment]
Everyone disagrees with you ask any user that uses other apps if control+c should shutdown their program instead of copy because text wasn't "highlighted" and it's the "users" fault on why you have presses the key twice and the keybind conflicts with copy. This is exactly the opposite of what user friend

**Comment by naikrovek** [comment]
every other capable command line user I know understands what CTRL+C does and doesn't do.

none of them want what you are asking for.

they aren't going to accommodate your *unique* expectation when there is an editor built in to Terminal that lets you customize what keystrokes do, and when they do it.

the rest of us will continue using terminals exactly as we have for 20+ years.

**Comment by jredfox** [comment]
Just because it's been a bug for windows users for 20 years does not mean it's not a bug. It's nothing to do with accommodate me it's wt itself.

As suggested by officials here they can change the keybind to control + shift + c.

**Comment by zadjii-msft** [comment]
Yea, Ctrl+C as SIGINT is something that long predates the Terminal, and we're not going to be able to change. I remember first learning the commandline and thinking it was a little weird myself. Ten years later now, and it feels like second nature to expect commandline keybindings to just be a little different. At least the "<kbd>Ctrl+C</kbd> with a selection is still copy" seems like a pretty successful middle ground.

At least we don't have copy/paste bound to something insane like <kbd>y</kbd><kbd>y</kbd> / <kbd>p</kbd><kbd>p</kbd> or <kbd>Alt+w</kbd>/<kbd>Ctrl+y</kbd>😄

**Comment by jredfox** [comment]
I will say this though you guys will change your mind though in the coming months. the main reason why I pointed this as a valid issue is I am making a library that is cross platform and supports alot of terminals. in one line you will be able to create a new UI with profiling native support and also things like ANSI colors

**Comment by naikrovek** [comment]
Ok.

**Comment by DHowett** [comment]
@jredfox You're right -- this is a valid concern -- but it's unfortunately just too late. The default interrupt character on every Windows device and Linux, macOS, BSD and any UNIX derivative produced in the past 35 years is <kbd>Ctrl+C</kbd>. That Windows has elected to use <kbd>Ctrl+C</kbd> in other graphical applications to indicate _Copy_ for an equivalent amount of time is likewise unfortunate, but is also an immovable historical choice.

> Other terminals do not terminate with control c as they realize they don't want this behavior like Linux they make you right click then copy or paste.

Unfortunately, they all do. <kbd>Ctrl+C</kbd> isn't handled by the terminal in any specific way, it's passed through to the line discipline driver and processed by the kernel. It can be rebound on a tty-by-tty basis using `stty intr`, but it generally is not.

If you're producing a cross-platform TUI library, you can switch the terminal or console host into raw input mode and handle <kbd>Ctrl+C</kbd> yourself and avoid termination, but that won't make it act as Copy unless you write some platform- and display-server-specific glue code.

We're bound by the choices of our forebears here. Sorry.
