### ISSUE TITLE
Revisit TerminalSelection to add tests, clean up, proper selection mechanics

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#1327]
More of a mental note of all the misc. selection stuff I need to do. Hopefully I can get this in very soon so that we can verify that nothing was broken.

- [x] Add testing for the following scenarios:
  - [x] `endSelectionPosition` being located out of bounds
- [ ] `_GetSelectionRects()` clean up
  - the pre-processing part is just a bit nasty now. There should be a way to simplify it. Need to be careful with testing this though.
- [x] Proper selection mechanics
  - when your `endSelectionPosition` is out of bounds **vertically**, the x-position should still update, but the y-position should be at the boundary
  -  when your `endSelectionPosition` is out of bounds **horizontally**, the y-position should still update, but the y-position should be at the **buffer** boundary
  - this is particularly important for #1247. As the y-position must be detected to be out of the bounds, so that's still valid. But it should be displayed as updating the x-position.

**Comment by DHowett-MSFT** [comment]
* [ ] no need for us to track the start and end Y-offsets separately; they are generally the same (?)
* [ ] concern about the logic being fragmented into a few different functions: chunk selections are expanded during _GetSelectionRects_ instead of during selection (?)

**Comment by carlos-zamora** [comment]
- [ ] `IsAreaSelected` and `IsSelectionActive` are the SAME THING

**Comment by carlos-zamora** [comment]
> * [ ]  `IsAreaSelected` and `IsSelectionActive` are the SAME THING

So, this one's on me. I created `IsAreaSelected()` in #1691 when I made some changes to `IRenderData`. This can actually get resolved in #2296 since I'm already touching that area of the code.

**Comment by carlos-zamora** [comment]
> * [ ]  concern about the logic being fragmented into a few different functions: chunk selections are expanded during _GetSelectionRects_ instead of during selection (?)

I'm thinking now that this might be OK. Keyboard selection would just set the anchors to whatever these functions return. That'll allow us to reuse the same function for the weird box selections that cover wide glyphs and words (on double click selections).
