### ISSUE TITLE
--profile: 1 required TEST missing

### ISSUE THREAD

**Issue by Andrew1988123123** [microsoft/terminal#13277]
### Windows Terminal version

Windows Terminal Version: 1.13.11432.0

### Windows build number

Microsoft Windows [Version 10.0.22000.708]

### Steps to reproduce

1. Create profile named "u"
2. Run wt -p "u"; nt -p "u"
3. Error appear.
4. "--profile: 1 required TEST missing"

### Expected Behavior

New windows terminal is created with two tabs

### Actual Behavior

The error pops up and Windows Terminal never opens.
Screenshot of the error  https://prnt.sc/y4Hi3Uir5as9
I think profile name is too short(one sign). Profile name with more than one sign works like a charm.

**Comment by elsaco** [comment]
@Andrew1988123123 that's an interesting find! If you add a space between first profile name and semicolon then it works.

Sample output with `wt -p "u"; nt -p "u"`

![wt_error](https://user-images.githubusercontent.com/3933920/173211316-d881b262-57c0-49f1-a4be-7a186852b3fb.png)

and `wt -p "u" ; nt -p "u"`

![image](https://user-images.githubusercontent.com/3933920/173211276-06b28cec-5bb1-4289-a432-7a6a67bff184.png)

**Comment by Andrew1988123123** [comment]
> @Andrew1988123123 that's an interesting find! If you add a space between first profile name and semicolon then it works.
> 
> Sample output with `wt -p "u"; nt -p "u"`
> 
> ![wt_error](https://user-images.githubusercontent.com/3933920/173211316-d881b262-57c0-49f1-a4be-7a186852b3fb.png)
> 
> and `wt -p "u" ; nt -p "u"`
> 
> ![image](https://user-images.githubusercontent.com/3933920/173211276-06b28cec-5bb1-4289-a432-7a6a67bff184.png)

It works but there is another issue. For some reason it always opened default profile(which is powershell for me). Profile name "u" is an abbreviation of Ubuntu.

**Comment by zadjii-msft** [comment]
Huh. Maybe I'm splitting things poorly on the `;`, it's really weird that adding a space would fix this. Command-line parsing is hard 🙃

**Comment by Andrew1988123123** [comment]
No big deal. I just have to remember adding space before **;** . Even documentation say so.
