### ISSUE TITLE
Add the ability to reorder the Terminal profiles

### ISSUE THREAD

**Issue by trparky** [microsoft/terminal#13281]
# Description of the new feature/enhancement
When you click on the drop-down button to choose a Terminal profile to load be it PowerShell, Ubuntu, or Command Prompt, there's no way to re-order them in custom order. For instance, by default the first profile in the drop-down list is Command Prompt.

I had to go into the JSON file itself to re-order them, but I'd like to see the ability to re-order them in the program's GUI instead.

**Comment by paradokx** [comment]
I have had to rearrange the order manually as well. Fully concur with @trparky this would surely be a sweet quality-of-life feature.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8914 for more discussion.

/dup #8914

**Comment by Nikhil-Software-Cartel** [comment]
@trparky @paradokx if problem is severe and ur managing lot of profiles,
you may want to have a look at https://github.com/Nikhil-Software-Cartel/TerminalProfileManager 
feel free to open PRs for roadmaps/improvements. 

https://github.com/microsoft/terminal/assets/54004431/92367991-720f-4a18-9d15-fba71a029c79
