### ISSUE TITLE
No longer launched from win 10 search `WT`

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13286]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.1706

### Steps to reproduce
- search in the windows 10 search bar wt
- ![Capture](https://user-images.githubusercontent.com/9736369/173471529-e6bba328-c469-460a-9597-6044682ef0cb.PNG)
- click enter once it's highlighted
- nothing happens
- search wt using `where.exe`
```
C:\Users\jredfox>where wt
C:\Users\jredfox\AppData\Local\Microsoft\WindowsApps\wt.exe
```

I also tried:
- repairing the app from apps and features
- resetting the app data from apps and features
- unintstalling and re-installing the app from the windows store
- double clicking wt.exe found in this path. the path was determined by clicking open file location of wt from the start menu `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe\wt.exe` and the same result happens
- running in cmd `start "" "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe\wt.exe" -p "Command Prompt" w -1`
- running in cmd `start "" "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe\wt.exe" -p "Command Prompt" new-tab`

### Expected Behavior

it opens up WT UI

### Actual Behavior

it either runs in the background then closes or doesn't open at all.

**Comment by zadjii-msft** [comment]
I'm pretty confident that `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_...` isn't actually supposed to be used. There's an "app execution alias" for the Terminal at `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` which should probably be used instead. Is there a `wt.exe` your PATH/? (an easy way to check this is `where wt` in Command Prompt)

If there isn't, but `%LOCALAPPDATA%\Microsoft\WindowsApps` is on the PATH, then you might need to re-enable the `wt` execution alias:

![image](https://user-images.githubusercontent.com/18356694/173403444-6e49275c-f116-49ab-9e42-9c446787cb6d.png)

**Comment by jredfox** [comment]
Idk it appeared in the search bar after reinstalling the app if it's suppose to only be terminal or windows terminal shortcut which does work then the original needs to be removed

**Comment by jkyndir** [comment]
@jredfox 

Hi, there.

I had the exact same problem where I cannot open windows terminal in the start menu or in windows explorer's address bar.

HELP! 
Would appreciate your help so much.

Literally begging on my knees...

**Comment by zadjii-msft** [comment]
@jkyndir Can you file a new issue? Make sure to include build numbers, Terminal version numbers, specific repro steps, etc. Also make sure to try toggling the `wt.exe` "app execution alias", and make sure that there's a `wt.exe` on your `PATH` (`where wt` in a Command Prompt window may be enlightening)

**Comment by zamadatix** [comment]
I came to this issue because I was having the same troubles recently. The alias was still enabled but "where wt" wasn't returning anything. Sure enough checking my PATH no longer had the entry for some reason. Manually adding %LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe resulted in "wt" finding the terminal from the Start menu again.

Thanks for the tips @zadjii-msft. I'm not sure why it suddenly disappeared but it's definitely working as expected now!
