### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by PrelevatedInsider22581** [microsoft/terminal#13280]
# Description of the new feature/enhancement

Acrylic titlebar, Remove all tabs, Mica Console.

# Proposed technical implementation details (optional)

* I need the Acrylic titlebar.
* I need Remove all tabs item (closes app).
* I need the Mica console.

**Comment by PrelevatedInsider22581** [comment]
:) We need the acrylic titlebar.

**Comment by PrelevatedInsider22581** [comment]
Even the Mica Console!

**Comment by zadjii-msft** [comment]
Please make sure to search when filing new issues, and avoid filing multiple requests all in one thread. It makes it really hard for us to track requests when they're all piled in one thread. 

I believe these requests are tracked in:
* /dup #4744, merged in #10864, with the setting [`useAcrylicInTabRow`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/appearance#show-acrylic-in-tab-row)
* I think you mean like, ["Quit Terminal"](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#quit)?
* /dup #10509
