### ISSUE TITLE
ANSI ESC 39 and 49 seems to misbehave

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13297]
### Windows Terminal version
1.13.11431.0

### Windows build number
10.0.19044 N/A Build 19044

### Steps to reproduce

create a batch file
```bat
@Echo off
echo [49;5;45m
cls
pause
echo [0mHello world
cls
pause
```
run this in windows terminal using the command prompt profile

### Expected Behavior

the background stays BLUE because 0m resets shouldn't reset the default BG and FG values. ANSI ESC 39 and 49 are to set the default bg and fg which should stay after 0m which is needed to clear alot of other ANSI escape codes
https://en.wikipedia.org/wiki/ANSI_escape_code

### Actual Behavior

it goes purple then black. instead of staying the color it was previously

**Comment by zadjii-msft** [comment]
Which Terminal version are you using? We've[1] been doing a lot of work to improve our VT support over the years, so knowing the exact build numbers matters here. 

To me, that script looks like
* set the active attributes to "default BG"
* set the active attributes to have blinking text
* set the active attributes to have a purple BG
* clear the buffer (with the _default_ attributes, not the _active_ ones)
* reset the active attributes to (default FG, default BG)
* print "hello world"
* clear the buffer (with the _default_ attributes, which are the _active_ ones)

[1]: and by we, I mean @j4james 😝

**Comment by jredfox** [comment]
@zadjii-msft `1.13.11431.0`

**Comment by zadjii-msft** [comment]
That makes sense to me. `49;5;45m` is
* switch to the default BG
* enable blinking text
* switch to a dark magenta BG

While `48;5;45m` is "set the BG to the color at index 45 in the 256 color table"

**Comment by zadjii-msft** [comment]
I'd refer to https://invisible-island.net/xterm/ctlseqs/ctlseqs.html, it's definitely the definitive guide. 

In this case, [Operating System Commands](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) for `OSC 10` and `OSC 11`, which can be used to change the RGB values of the default FG/BG (respectively). 

As an example, this is a python script I have for changing the Terminal BG color 
```py
import colorsys

for i in range(0, 2560):
    h = i / 256.0
    (r, g, b) = tuple(round(j * 255) for j in colorsys.hsv_to_rgb(h,1.0,1.0))
    sys.stdout.write(f'\x1b]11;rgb:{r:x}/{g:x}/{b:x}\x1b\\')
    sys.stdout.write(f'\rrgb:{r:x}/{g:x}/{b:x}')
    sys.stdout.flush()
    time.sleep(.01)
```

which looks more or less like:
![themes-tab-background-001](https://user-images.githubusercontent.com/18356694/173596090-2d2fbc2d-9027-4704-86c6-cbee758eb9cd.gif)

**Comment by DHowett** [comment]
Right, SGR `49` means "set the active background color for newly written text or cleared lines to the default background color." SGRs have no affordance for redefining what a color index means.

In Terminal 1.14+, you'll be able to set the default background color to one of the palette indices using `DECAC`. In Terminal <1.14, you can set the background color in RGB using `OSC 11` (I think it's 11...). However, both of those will change the background in perpetuity, and will reassign what SGR `49` means.

**Comment by jredfox** [comment]
No it won't be the exact color but generally they will be the same color as defined by xterm256 color or ansi 4 bit color. Like purple won't be blue or black or white on different terminals. It just happens that 39 and 49 behaved differently then 38 and 48 by requiring no parameters that's why I closed the issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
