### ISSUE TITLE
Flickering icon & app will not launch

### ISSUE THREAD

**Issue by ygwarggis** [microsoft/terminal#13290]
### Windows Terminal version

Windows 10 Pro for Workstations, version: 21H2

### Windows build number

19044.1706

### Steps to reproduce

Download, install, and open Windows Terminal from MS Store;
Change setting to open in Command Prompt as default and default directory;
Save and close the application;
Click to open from Windows start menu to launch application again.

### Expected Behavior

Windows Terminal application to open normally.

### Actual Behavior

Windows Terminal application icon continuously flickers, mouse pointer stuck on loading status (loading/busy circle mouse pointer), and the application will not launch.

I have to reinstall it for it to work.  But after I close it and try to re-open it the second time, it will not launch and stays on the flickering icon and flickering "busy" mouse pointer.

Cannot End Task from windows task manager either.  It would just come back in the task list again and the issue persists.

[settings.txt](https://github.com/microsoft/terminal/files/8892964/settings.txt)

https://user-images.githubusercontent.com/42976831/173408404-28aec0fe-ed48-43d6-bc91-e0244f64a0a4.mp4

**Comment by zadjii-msft** [comment]
hmm. For whatever reason, github seems like it doesn't like the video you uploaded. Can you try again/?

**Comment by ygwarggis** [comment]
I'm using WT 1.13.11431.0 freshly installed every time.  

It's weird.  So I changed one setting value, saved, and relaunched for EVERY setting preference I want to change individually (i.e. changed starting directory to C:\, saved, relaunched. Then changed startup profile to Command Prompt, saved, relaunched...etc.)  instead of making all the changes at once before saving and relaunching and it worked.  I was able to launch it successfully every time.  Even after Windows restart.

To test that theory, I uninstalled my "working" WT, at this point, and reinstalled it; opened it, changed ALL my preferred setting at once, saved, and relaunched....and..yup...it started flickering again and won't open.

**Comment by zadjii-msft** [comment]
QQ: does deleting `state.json` fix it? (back it up first, just in case) Maybe there's something there, with your combination of settings, that's triggering this.

**Comment by ygwarggis** [comment]
Nope.  That didn't work.  I deleted state.json, replaced settings.json with a copy that's included with the app by default, made all the changes at once, saved, restarted the app.  Wouldn't launch and still flickering icon.  Can't even stop it in the task manager.  Uninstalling it is the only way to kill it :/

Regardless, it's a great app.  I'll just change my settings one at a time (thankfully, not too many.)  I only have to do it once, so not too bothered by it.

**Comment by zadjii-msft** [comment]
Hmm. 1.13 predates the focus/fg work, so this isn't a side effect of that - at least I don't think it is. 


I'm still trying to get a read on whatever's going on here. If you look at the Terminal in Task Manager, does it exit and reopen with a new PID each time/? Or is this just a single process, flashing its window uncontrollably? 

There was some horrific flashing circa #13066, but again that should have only been on internal builds of 1.14 and should have been fixed before it shipped. 


The `profiles.defaults.elevate: true` is maybe a little sus. Maybe that's what's happening? We are trying to relaunch as elevated, but then just... launching unelevated again in a loop? Or, or - oh. If the defaults are set to `elevate:true`, but also `"firstWindowPreference": "persistedWindowLayout"`, then we'd load the layout, discover the profile wants to be elevated, then try to launch an elevated instance instead. yikes. That might be the interaction at play here. 

But why would that flash in a loop then? 

Theoretically, there'd be no unelevated window state to restore out of `state.json`. You'd open the terminal, we'd discover nothing/at most one tab, then try to open it, punt it to an elevated terminal instance, and that would open.... {the previous elevated windows' state, a window for the default profile}
