### ISSUE TITLE
Can't move tabs around up top?

### ISSUE THREAD

**Issue by leet0rz** [microsoft/terminal#13303]
### Windows Terminal version

1.13.11431.0

### Windows build number

[Version 10.0.19044.1706]

### Steps to reproduce

Try to move the last tab as the first tab

### Expected Behavior

To be able to have the last tab move to be the first tab

### Actual Behavior

You cant move it.

Is this intended or a bug?

**Comment by zadjii-msft** [comment]
Are you running as administrator/? (alternatively, did you disable UAC?)

(this should work, except when running elevated)

**Comment by zadjii-msft** [comment]
The TL;DR is that the modern drag-drop service throws an exception we can't catch when trying to drop something onto an elevated window, so dragging an elevated tab effectively crashes the Terminal. Hence why it's disabled in elevated windows. I think the oldest thread on this topic is #3581.

/dup #6661
