### ISSUE TITLE
Startup lag when using a preset to open multiple terminal tabs/panes

### ISSUE THREAD

**Issue by CC007** [microsoft/terminal#13304]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.1706

### Other Software

kubectl v1.18.5
WSL (version 2) running Ubuntu (kernel version: 4.19.128)

### Steps to reproduce

1. Setup config file so that WT starts with 2 tabs: 
   - first tab contains 5 panes with powershell (1 big on left, 4 vertically small on right)
   - second tab contains 5 panes with bash  (1 big on left, 4 vertically small on right)
   - top right pane of powershell runs a kubectl proxy on startup

2. Open WT

### Expected Behavior

It used to open the terminal in less than a second WT to open and for the tabs to be visible, with maybe only the individual panes not being responsive yet until half a second later.

### Actual Behavior

Nowadays it takes 3-4 seconds before even the first pane is visible. The pane area is see-through and the top bar is black, rather than white and without any of the tabs showing until after the 3-4 seconds (see image) 
![afbeelding](https://user-images.githubusercontent.com/5381337/173827922-939ec9c1-46a1-426e-9428-aa69a29efea8.png)

What it looks like after it is done loading: 
![afbeelding](https://user-images.githubusercontent.com/5381337/173829520-8ce73e77-66a4-4c3f-913f-4caab363de0b.png)

**Comment by zadjii-msft** [comment]
Sounds a lot like #13105 to me

**Comment by CC007** [comment]
Yup. This seems to be a duplicate of #13105. They used different keywords, so my search for similar issues didn't find it. Closing this one
