### ISSUE TITLE
Broadcast multiple terminal

### ISSUE THREAD

**Issue by mrafols** [microsoft/terminal#13302]
# Description of the new feature/enhancement

 It would be great to have the option to broadcast on multiple terminals the same command like terminator in Linux.

# Proposed technical implementation details (optional)

Using shortcut you can broadcast on multiple terminals.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+broadcast) when filing new issues. This is already being tracked by another issue on our repo - please refer to #2634 for more discussion.

/dup #2634
