### ISSUE TITLE
Git Bash opening in separate window in Windows Terminal

### ISSUE THREAD

**Issue by iKausik** [microsoft/terminal#13317]
### Windows Terminal version

1.13.11432.0

### Windows build number

 10.0.22000.0

### Other Software

When I try to open Git Bash as a Tab inside Windows Terminal instead it's opening the actual Git Bash window separately.

### Steps to reproduce

![Screenshot 2022-06-18 005345](https://user-images.githubusercontent.com/32932853/174389299-e713e786-0454-4aa4-8d1b-cffa59134e7d.png)

### Expected Behavior

Shows above

### Actual Behavior

Show above

**Comment by DHowett** [comment]
How have you configured our `git bash` profile? Is it set to launch in mintty? That window is mintty.

**Comment by iKausik** [comment]
I'm adding every profile there, ubuntu WSL, PowerShell, cmd, etc., and those are working fine by default but only git bash behaving like this.

**Comment by elsaco** [comment]
@iKausik `Git-for-Windows` has it's own terminal profile fragment located at `C:\ProgramData\Windows Terminal\Fragments\Git\git-bash.json` which is added to the terminal.

`git-bash.json` content, use it for inspiration:

```
{
  "profiles": [
  { "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
  "name": "Git Bash",
  "commandline": "C:/Program Files/Git/bin/bash.exe -i -l",
  "icon": "C:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
  "startingDirectory": "%USERPROFILE%"
  }]
}
```

**Comment by DHowett** [comment]
I do not want to seem like a broken record, but we need to know _how you have configured your git bash profile_ to help you.

There are many programs inside the `git` folder. Some of them launch "mintty," that separate terminal window that you are seeing.
We need to figure out if you are using one of those programs.

**Comment by FLUENTYAN** [comment]
> I'm adding every profile there, ubuntu WSL, PowerShell, cmd, etc., and those are working fine by default but only git bash behaving like this.
`{
  "profiles": [
  { "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
  "name": "Git Bash",
  "commandline": "C:/Program Files/Git/bin/bash.exe -i -l",
  "icon": "C:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
  "startingDirectory": "%USERPROFILE%"
  }]
}`

**Comment by FLUENTYAN** [comment]
> I'm adding every profile there, ubuntu WSL, PowerShell, cmd, etc., and those are working fine by default but only git bash behaving like this.

My terminal went the same as yours after i adding the  line "commandline": "C:/Program Files/Git/bin/bash.exe -i -l", so, i think maybe you can solve it by removing this line.

```
{
  "profiles": [
  { "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
  "name": "Git Bash",
  "commandline": "C:/Program Files/Git/bin/bash.exe -i -l",
  "icon": "C:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
  "startingDirectory": "%USERPROFILE%"
  }]
}
```

**Comment by iKausik** [comment]
![MINGW64__c_WINDOWS_System32 20-06-2022 03_07_31 PM](https://user-images.githubusercontent.com/32932853/174573248-c5411e19-6a50-4723-8334-6d4a88b1d566.png)

**Comment by susanaSeres** [comment]
In my case 

 "commandline": "C:/.......    your directory installation /git/bin/bash.exe",
