### ISSUE TITLE
Taskbar icon is blank

### ISSUE THREAD

**Issue by darkmuck** [microsoft/terminal#13315]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Install Windows Terminal
Launch Windows Terminal
Notice missing app icon in taskbar

### Expected Behavior

App icon appears in taskbar

### Actual Behavior

App icon is not visible in taskbar

![image](https://user-images.githubusercontent.com/77098/174302041-2c3f17d9-cb83-40ab-99c6-ba059ca4735b.png)

**Comment by DHowett** [comment]
Do other packaged apps (like _Feedback Hub_ and _Clock_) have icons? Does this persist if you reboot? What is that other application that is missing an icon?

**Comment by darkmuck** [comment]
It appears as if it does happen with other packaged apps, but only that type. Traditionally installed apps seem to be fine. Also, it does persist after reboot. The  other missing icon is "Notepads" from the Microsoft Store. Even the Microsoft Store icon itself is missing. So I presume this is not a Windows Terminal related bug and this should be closed?

**Comment by zadjii-msft** [comment]
Yep, this sounds like a broader OS issue. I'd file feedback via Feedback Hub, presumably on the "Desktop Environment > Taskbar" area path. Thanks!

**Comment by daveorourke** [comment]
I had this problem too.  I tried reboot, reinstall, repin, etc. but the issue persisted.  Steps 1-6 in this [reddit post](https://www.reddit.com/r/Windows11/comments/16v3rqk/comment/kpjxfgg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) worked for me, and I **finally** have the Terminal icon showing in the Taskbar.
