### ISSUE TITLE
After clearing the screen (cls command) and then scrolling up, results in the last line of the previous screen still visible

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#13320]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.739

### Steps to reproduce

1. Open Terminal
2. Navigate to `C:\Windows\System32`, a folder where files are available in large numbers so that results occupy an almost available screen space
3. First run the `dir` command so that Terminal is made use of
4. Now clear the screen using the `cls` command
5. Now try to scroll up, the last line of the previous screen is still visible

### Expected Behavior

When cleared nothing should be visible from the previous result.

### Actual Behavior

When scrolled upwards, the last line is still visible even after clearing the results.

**Comment by j4james** [comment]
I suspect this might be the same problem as #5770.

**Comment by egvijayanand** [comment]
Same behavior in PowerShell tab too.
