### ISSUE TITLE
Feature Request - X like copy / paste

### ISSUE THREAD

**Issue by timriker** [microsoft/terminal#1332]
# Summary of the new feature/enhancement

I really hope to see X style copy/paste support in Windows Terminal.

# Proposed technical implementation details (optional)

Dragging should highlight like console, but automatically put the hightlighted text into the clipboard and leave it hightlighted.

Selection should NOT include trailing spaces as the current terminal incorrectly does with ctrl-shift-c, It should post multiple lines to the clipboard.
The selection should look for characters are actual spaces, and not blanks and not replace blanks with spaces.

Dragging with alt or control held down should select a block instead of rolling lines.

Clicking the middle mouse button should paste the clipboard.

Mouse wheel should scroll, perhaps 3 lines at a time.

This functionality can be compared with xfce4-terminal or gnome-terminal on a Linux box, or on WSL under X servers like VcXsrv. Also compare to MoboXterm support. XTerm is similar but lacks the block select feature.

**Comment by zadjii-msft** [comment]
This is #524
