### ISSUE TITLE
Please migrate from exe and msi files to microsoft store applications

### ISSUE THREAD

**Issue by apy7hst** [microsoft/terminal#13326]
I know very well that this issue is not related to the app. But there are hundreds of repositories in this organization, and I am unsure where to open this issue, but security vulnerabilities in windows are increasing, and the main reason for that is the usage of exe and msi files still exist. Please provide me any microsoft support/development email if it exists so that I can inform them about this issue and close this issue.

**Comment by j4james** [comment]
The application is already available from the Microsoft Store here:
https://aka.ms/terminal

And that's the recommended installation method which you'll find at the top of the `README` file here:
https://github.com/microsoft/terminal#installing-and-running-windows-terminal

**Comment by apy7hst** [comment]
I am talking about migration of windows apps to microsoft store but you are telling about the terminal application. Carefully read what I requested and then edit your reply.

**Comment by j4james** [comment]
If your complaint is that some Microsoft applications are not hosted in the Microsoft Store, I would think the best place to raise that issue would be with the application or applications that actually have that problem.

**Comment by apy7hst** [comment]
I am saying this fact as a security-related concern. exe files are becoming more unsafe to use as they contain hidden malware and windows users already have another source of a more secure app installation which is microsoft store. Therefore, put an end to exe and msi files by converting them into microsoft store package and make more secure installations take place

**Comment by hello-smile6** [comment]
> I am saying this fact as a security-related concern. exe files are becoming more unsafe to use as they contain hidden malware and windows users already have another source of a more secure app installation which is microsoft store. Therefore, put an end to exe and msi files by converting them into microsoft store package and make more secure installations take place.

Even .appx files have .exe files inside. Open the TranslucentTB .appx with 7-zip.

**Comment by zadjii-msft** [comment]
This thread is off-topic for this repo. I'm gonna lock this before it spirals more, but I'll be back in the office to give a longer reply monday.
