### ISSUE TITLE
Terminal inserts [O characters after nvim exits

### ISSUE THREAD

**Issue by ket-rivers** [microsoft/terminal#13330]
### Windows Terminal version

1.14.1451.0

### Windows build number

10.0.19044.1766

### Other Software

PowerShell 7.3.0-preview4
nvim v0.7.0 (NOT inside WSL)

### Steps to reproduce

*I don't know how anyone else can reproduce this bug.*

In windows terminal type ```nvim```
In nvim type ```:q```

### Expected Behavior

After nvim quits, the prompt should be empty, no characters typed

### Actual Behavior

After nvim quits, the prompt has ```[O``` typed in. I have to delete them to use a new command.

This doesn't hapen in PowerShell, CommandPrompt or WindowsTerminal (not the preview version)
I have reinstalled nvim, also WindowsTerminal.

Also i have deleted all the configurations done to nvim and WindowsTerminal and the issue persists.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #13238 for more discussion.

/dup #13238
