### ISSUE TITLE
windows lock.

### ISSUE THREAD

**Issue by Im-JimmyHu** [microsoft/terminal#13332]
# Description of the new feature/enhancement

sometime we  run a project for a long time, which comes with a running tabs.but if we close the all tabs uncarefully, we maybe close the running tabs too.

# Proposed technical implementation details (optional)

In linux,for running tabs,if you try to close it ,it will not close the tab directly but  give a warning.maybe a solution.or can you give a function to lock the program that it will not be closed unexpectedly.

**Comment by zadjii-msft** [comment]
> give a function to lock the program that it will not be closed unexpectedly

That sounds like ["read-only mode"](https://docs.microsoft.com/en-us/windows/terminal/panes#marking-a-pane-as-read-only)

> it will not close the tab directly but give a warning

We're tracking this in #6549 (et. al). Thanks!

/dup #6549
