### ISSUE TITLE
Icons flash for a frame when switching tabs

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1333]
Every time we change the focus of a tab/pane, we attempt to update the icon and titlebar of the tab. Since we're only storing a _path_ to the icon in memory, every time you change focus, we need to reload the icon from disk to create the `Icon`. 

This is obviously bad. we should instead be caching the icon once, and just updating the `Icon` with that pre-loaded one. Or at the very least, we should cache what the path to the last icon we set was, and only reload the icon if the path is different.

**Comment by DHowett-MSFT** [comment]
This will also be helped by #1205, but not totally fixed by it.
