### ISSUE TITLE
Preview version installed via WinGet doesn't allow setting as default terminal application.

### ISSUE THREAD

**Issue by kruug** [microsoft/terminal#13349]
### Windows Terminal version

1.14.1432.0

### Windows build number

19042.1706

### Steps to reproduce

Open PowerShell
Run `winget install --id=Microsoft.WindowsTerminal.Preview -e`
Open Terminal Preview
Open Settings
Note lack of "Default terminal application" prompt

### Actual Behavior

The Settings does not have the "Default terminal application" prompt.

**Comment by zadjii-msft** [comment]
Yep, this is by design. The Default Terminal feature is only available on Windows 11.

**Comment by zadjii-msft** [comment]
Good catch, fixed in https://github.com/MicrosoftDocs/terminal/pull/551
