### ISSUE TITLE
Unable to activate tabs by clicking top pixel row on display.

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/terminal#13346]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Open the terminal
2. Open 2 tabs
3. Maximize the terminal window
4. Move the mouse cursor the the top of the screen and click a tab

### Expected Behavior

The clicked tab is activated.

### Actual Behavior

The clicked tab is not activated. I claim that this used to work fine previously.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+click+top+pixel) when filing new issues. This is already being tracked by another issue on our repo - please refer to #11309 for more discussion.

/dup #11309

**Comment by oliversalzburg** [comment]
Okay. Next time I will definitely search for duplicates before posting new issues. Thanks for explaining the system to me.
