### ISSUE TITLE
Cannot upgrade from v1.12.10393.0 to v1.13.11431.0 with chocolately due to Microsoft.VCLibs.140.00.UWPDesktop

### ISSUE THREAD

**Issue by rklec** [microsoft/terminal#13345]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.19044.0

### Other Software

N/A

### Steps to reproduce

`choco upgrade -y microsoft-windows-terminal`

### Expected Behavior

Upgrade suceeds.

### Actual Behavior

```
>  choco upgrade -y vcredist140
Chocolatey v1.1.0
Upgrading the following packages:
vcredist140
By upgrading, you accept licenses for the packages.
vcredist140 v14.32.31326 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> choco upgrade -y microsoft-windows-terminal
Chocolatey v1.1.0
Upgrading the following packages:
microsoft-windows-terminal
By upgrading, you accept licenses for the packages.

You have microsoft-windows-terminal v1.12.10393.0 installed. Version 1.13.11431.0 is available based on your source(s).
Progress: Downloading microsoft-windows-terminal 1.13.11431.0... 100%

microsoft-windows-terminal v1.13.11431.0 [Approved]
microsoft-windows-terminal package files upgrade completed. Performing other installation steps.
Progress: 0% - Processing                                                                                              ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CF3, Fehler bei Updates des Pakets (Abhängigkeits- oder Konfliktüberprüfung).

Das Paket Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe kann von Windows nicht installiert werden, da es von einem Framework abhängig ist, das nicht gefunden wurde. Stellen Sie das von CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US veröffentlichte Framework Microsoft.VCLibs.140.00.UWPDesktop mit einer neutralen oder x64-Prozessorarchitektur und Mindestversion 14.0.30035.0 zusammen mit dem zu installierenden Paket bereit. Die derzeit installierten Frameworks mit
Das Paket Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe kann von Windows nicht installiert werden, da es von einem Framework abhängig ist, das nicht gefunden wurde. Stellen Sie das von CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US veröffentlichte Framework Microsoft.VCLibs.140.00.UWPDesktop mit einer neutralen oder x64-Prozessorarchitektur und Mindestversion 14.0.30035.0 zusammen mit dem zu installierenden Paket bereit. Die derzeit installierten Frameworks mit dem Namen Microsoft.VCLibs.140.00.UWPDesktop sind: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe}

NOTE: For additional information, look for [ActivityId] 59f0e28b-853c-0008-5a62-f4593c85d801 in the Event Log or use the command line Get-AppPackageLog -ActivityID 59f0e28b-853c-0008-5a62-f4593c85d801

The upgrade of microsoft-windows-terminal was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-windows-terminal\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-windows-terminal (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-windows-terminal\tools\chocolateyInstall.ps1'.
 See log for details.

```

This looks very similar to https://github.com/microsoft/terminal/issues/3097, however this seems solved long ago and all dependencies should be shipped with the app.

**Comment by zadjii-msft** [comment]
Thanks for the report! We don't actually maintain the choco package for the Terminal ourselves (as discussed in #2044). As noted in the README:

> If you have any issues when installing/upgrading the package please go to the [Windows Terminal package page](https://chocolatey.org/packages/microsoft-windows-terminal) and follow the [Chocolatey triage process](https://chocolatey.org/docs/package-triage-process)

I suspect whoever does maintain the choco package needs to use the Windows 10 versions of the Terminal package, instead of the Windows 11 versions. Sorry about that!

**Comment by rklec** [comment]
Okay, reported downstream to the maintainer(s) at https://github.com/mkevenaar/chocolatey-packages/issues/136

**Comment by theperm** [comment]
> Thanks for the report! We don't actually maintain the choco package for the Terminal ourselves (as discussed in #2044). As noted in the README:
> 
> > If you have any issues when installing/upgrading the package please go to the [Windows Terminal package page](https://chocolatey.org/packages/microsoft-windows-terminal) and follow the [Chocolatey triage process](https://chocolatey.org/docs/package-triage-process)
> 
> I suspect whoever does maintain the choco package needs to use the Windows 10 versions of the Terminal package, instead of the Windows 11 versions. Sorry about that!

I checked and its using this file Microsoft.WindowsTerminalPreview_Win10_1.14.1451.0_8wekyb3d8bbwe.msixbundl

**Comment by rklec** [comment]
This script here finally made it work: https://github.com/microsoft/terminal/issues/3097#issuecomment-1345242698
