### ISSUE TITLE
Restore previous directories when using "Open windows from a previous session"

### ISSUE THREAD

**Issue by alexgeek** [microsoft/terminal#13367]
# Description of the new feature/enhancement

I generally have about 5 powershell tabs open that are coloured and named for different projects I between. 
When I restart my PC windows terminal opens back up with the same tab names / colours due to the "Open windows from a previous session" setting but I then have to CD into all the directories. It would be a great improvement to automatically CD into the last used directory per tab.

# Proposed technical implementation details (optional)

I'm not sure myself as not familiar with the codebase but I imagine could be something like:
- on close for each tab
- cache `pwd`
- on open for each tab
- `cd` to cached `pwd`

Would likely need to be enabled per profile as some may not even have these commands.

**Comment by zadjii-msft** [comment]
The Terminal should already do this, assuming that you've [configured your shell to tell the Terminal what the CWD is](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

**Comment by alexgeek** [comment]
> The Terminal should already do this, assuming that you've [configured your shell to tell the Terminal what the CWD is](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

Thanks I'll look at that. I tried it and it works buts overriding posh-git / oh-my-posh so I'll need to do some fiddling.
