### ISSUE TITLE
The vertical scrollbar thumb does not expand to full size

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#13361]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Write enough text to display a vertical scrollbar e.g. `tree /f %windir%`
2. Hover mouse over scrollbar or even the thumb specifically

### Expected Behavior

Thumb expands to a larger size as it does in Notepad (new Windows 11 version).

### Actual Behavior

Thumb stays tiny as shown in screen grab below:

![Terminal Scrollbar Issue](https://user-images.githubusercontent.com/1532486/175144468-63b1b81b-b3ca-4f6a-a7a1-9020f4319a65.gif)

**Comment by zadjii-msft** [comment]
Huh.

![gh-13361](https://user-images.githubusercontent.com/18356694/175281127-c87d2393-79ac-4911-81a5-73ccea8f5396.gif)

any chance you have animations disabled in the OS? I honestly have no idea what could possibly cause this 😕

**Comment by heaths** [comment]
> Maybe #12608?

Animations are enabled. It could be related to that issue, though. I should've also mentioned I'm running 4K resolution. Assuming new notepad is using WinUI (I'm pretty sure it is), you can see the scrollbar works as I'd expect with modern UI.

**Comment by zadjii-msft** [comment]
If I had to guess, this regressed in #12608, but I have no idea why. We're just copy-pasting the scrollbar XAML in its entirety. 

Do the scrollbars in the Settings UI work as expected? That might help narrow this down.

**Comment by heaths** [comment]
> Do the scrollbars in the Settings UI work as expected? That might help narrow this down.

@zadjii-msft no, they exhibit the same always-narrow behavior as shown in my screenvid.

**Comment by zadjii-msft** [comment]
Sticking Leonard on this since he's got a live repro. Presumably this is sure to our manual re-template of the scrollbar control, but I wouldn't begin to know what we broke.

**Comment by lhecker** [comment]
I used to have this issue and it doesn't occur in the internal 1.16.2352.0 preview build anymore. Closing, because it'll be (hopefully - if I'm right) fixed in the upcoming 1.16 build.
