### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by MuhammetEminCakir** [microsoft/terminal#13364]
# Description of the new feature/enhancement
Can you add Turkish translation to the app? That would be very useful. Also, there are very few applications that do not support Turkish language on Windows.

# Proposed technical implementation details
Windows 11 Pro 22621.160
Windows Terminal (UWP) 1.13.11432.0

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think we're gonna track these sorts of requests all in one place, in https://github.com/microsoft/terminal/issues/10667.

/dup https://github.com/microsoft/terminal/issues/10667
