### ISSUE TITLE
No GitHub/Feedback link in About box.

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/terminal#13371]
# Description of the new feature/enhancement
The current about dialog is pretty simple:

![image](https://user-images.githubusercontent.com/24302614/175428885-762497a4-4711-4085-b6bf-08b27f856c82.png)

It'd be nice to see:
- Terminal Icon
- A link to GitHub (maybe w/ GitHub Icon)
- A 'Send Feedback' link which leads here or Feedback Hub:
![image](https://user-images.githubusercontent.com/24302614/175429094-41542cd5-aadf-4d76-9716-433c4cb209ee.png)

**Comment by zadjii-msft** [comment]
FWIW We used to have this in the top level dropdown, but it was just generating noise. 

In #789 we made it point at our GitHub issues, but at some point after that we redirected that to the `FeedbackUriValue` resource, which redirects to feedback hub now. 

We've discussed offline the idea of putting this back _somewhere_, once again pointing at GitHub, and again with the `in-app-feedback` label (or something like that). Of course, we can just change the `fwlink` on our side to point at whatever, so just adding a link back should be easy enough.

**Comment by AdamSotak** [comment]
Hello, I would like to work on this.

I have already implemented these buttons:

![WindowsTerminalAboutDialog](https://user-images.githubusercontent.com/92621643/179002517-a3f4bf3a-dde8-45ad-b066-80875fa75d43.png)

The buttons link directly to:
- Source Code -> https://github.com/microsoft/terminal
- Send Feedback -> https://github.com/microsoft/terminal/issues 
**(Change to Feedback Hub?)**


I would appreciate your feedback.

**Comment by zadjii-msft** [comment]
I think that would be perfect! Honestly, GitHub is a way better place for feedback than Feedback Hub 😄

**Comment by DHowett** [comment]
This might be one of those things where the stable version should direct users to the feedback hub, and the preview/dev versions should direct users to GitHub . . . @zadjii-msft, WDYT?

Motivation: I don't know if, when we become "DxD", we can rely on the large population of Stable users to _have GitHub accounts._

**Comment by zadjii-msft** [comment]
That's a good idea, but let's start small. Let's just start with the links as @AdamSotak has it now for now, and we can sort out the fwlinks on our side in post.
