### ISSUE TITLE
"Show/Hide the Terminal window" buggy between displays (another one bug)

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#13374]
### Windows Terminal version

1.14.1452.0

### Windows build number

10.0.22621.0

### Steps to reproduce

*related to #13373, but a minor one.*
1. Setup a key combination to "Show/Hide the Terminal window".
2. Maximize Terminal window in a smaller display.
3. Move cursor to a bigger display, press keystroke to "summon" Terminal to this display

### Expected Behavior

Terminal window moves to the bigger display, and maximized

### Actual Behavior

Terminal window moved to the bigger display, and "maximized" according to the window button, but actually not maximized.

*Notice the buttons on the upper right corner*
![image](https://user-images.githubusercontent.com/1884240/175452679-22bfbc14-e326-4e27-9c53-0ba93d2feec3.png)

**Comment by zadjii-msft** [comment]
You know what, I'm gonna just merge this in with #13373. They're slightly different, but ultimately they're both "I maximized on one screen, and summoned to another (at a different size), and it did the wrong thing". Thanks for the detailed reports!

/dup #13373
