### ISSUE TITLE
Pressing shift while a key is repeating terminates the repeat. Although this is consistent with Windows key event behavior, requesting a compatibility option

### ISSUE THREAD

**Issue by unphased** [microsoft/terminal#13380]
### Windows Terminal version

Windows Terminal Preview Version: 1.14.1451.0

### Windows build number

Microsoft Windows NT 10.0.19044.0

### Other Software

N/A

### Steps to reproduce

1. Hold down an alphanumeric key such as `a`. It begins to repeat. 
2. while holding that key down, depress a Shift key

### Expected Behavior

To be consistent with behavior in macOS and Linux, the input from the alphanumeric key should continue: `aaaaaaAAAA`

### Actual Behavior

Input stops when the Shift key comes down: `aaaaaa`

To get back the desired input one has to re-type the first key, *and* wait past the initial key repeat delay. 

This is seen to be standard windows input event behavior, nevertheless, I would prefer to have independently generated key repeat events to replicate the behavior observed in the terminal on any other operating system.

**Comment by lhecker** [comment]
I can only speak for myself, but I don't think this is something we can easily implement. We don't generate those character input events - Windows does. Adding such a compatibility feature might be quite difficult to do correctly (with respect to Unicode, etc.) and not be worth the effort, considering that other Windows applications don't support this either.

**Comment by zadjii-msft** [comment]
Yea I'm inclined to agree here. If someone wants to correct me, I'm all ears, but I suspect it'll be quite a bit more than trivial to get repeated keypresses in this scenario. Sorry about that!
