### ISSUE TITLE
[~100% IMPACT] When you close a powershell tab, powershell *crashes*

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1338]
Powershell doesn't like its conhost being terminated, so it crashes.
The job object change made it more likely that we terminate its conhost without allowing it to exit normally. Yeah.

**Comment by carlos-zamora** [comment]
Performed a `git bisect`. Issue caused by PR #970.

**Comment by DHowett-MSFT** [comment]
Yep. Powershell doesn’t like its console host being terminated without it. I’m working on a fix for process rundown.

**Comment by DHowett-MSFT** [comment]
Of note: CMD doesn’t care. Technically this is a powershell issue. We should still not break existing workflows :)
