### ISSUE TITLE
Auto-scrolling stops working after a while when using panes

### ISSUE THREAD

**Issue by 2-5** [microsoft/terminal#13393]
When running scripts in multiple panes, after a while some of the panes stop auto-scrolling. Using the mouse wheel to scroll the stuck ones to the bottom temporarily fixes the problem, but after a while the auto-scrolling stops working again. Clicking into the stuck pane (focusing it) also sometimes fixes the issue.

I can reproduce with default settings (deleted settings.json)

Windows Terminal 1.13.11431.0
Windows x64 10.0.19044.1766

I encountered the issue running Python scripts with `cmd /c python.exe script.py`. The scripts output one line each 10 seconds, so it can be reproduced with very low output rate, but it will take tens of minutes.

The following PowerShell test cases with high output rate reproduce the issue much more quickly. The more panes, the quicker the auto-scrolling stops for some panes.

16 panes test case (most reliable reproduce):

wt pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf left; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf right; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf left; mf left; mf left; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf up; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf down; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf right; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf up; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf down; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf right; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf up; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf down; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf right; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf up; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"; mf down; sp -H pwsh -c "while ($true) { Get-Date && Start-Sleep 0.2 }"

4 panes test case:

wt pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"; mf left; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"; mf right; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"

2 panes test case (not very reliable reproduce):

wt pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"; sp -V pwsh -c "while ($true) { Get-Date && Start-Sleep 0.1 }"

**Comment by 2-5** [comment]
Works correctly in 1.14

**Comment by DHowett** [comment]
Thanks for the confirmation! Sorry we let this one linger for a while.
