### ISSUE TITLE
Open from windows explorer fails on paths containing certain symbols on older PowerShell versions

### ISSUE THREAD

**Issue by CptWesley** [microsoft/terminal#13395]
### Windows Terminal version

1.14.1451.0

### Windows build number

10.0.19043.1766

### Other Software

PowerShell 5.1.19041.1682 (might be the actual culprit)

### Steps to reproduce

Set default terminal to PowerShell 5

Create directory on desktop named `test`
Open directory `test` in explorer
Right click and select `Open in Terminal` (A)

Create directory on desktop named `test]`
Open directory `test]` in explorer
Right click and select `Open in Terminal` (B)

Create directory on desktop named `[test`
Open directory `[test` in explorer
Right click and select `Open in Terminal` (C)

Create directory on desktop named `[test]`
Open directory `[test]` in explorer
Right click and select `Open in Terminal` (D)

### Expected Behavior

(A): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\test`
(B): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\test]`
(C): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\[test`
(D): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\[test]`

**NB:** This is the actual behaviour when selecting `Open PowerShell window here` (thus not using Windows Terminal) and also the behaviour when using newer PowerShell versions in Windows Terminal.

### Actual Behavior

(A): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\test`
(B): Powershell 5 tab in Windows Terminal opens in `%UserProfile%\Desktop\test]`
(C): Powershell 5 tab in Windows Terminal opens in `C:\`
(D): Powershell 5 tab in Windows Terminal opens in `C:\WINDOWS\System32\WindowsPowerShell\v1.0`

**Comment by DHowett** [comment]
Unfortunately, this is a known issue in PowerShell 5.1 and below -- they cannot handle starting in a directory that contains special characters. This can be observed even in launching PowerShell from cmd:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/189190/176253537-d6a881d1-a0fe-4c2c-aada-12b40f204171.png">
