### ISSUE TITLE
[~75% IMPACT] Crash on natural app exit because of composition class issue (XamlApplication)

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1339]
The "correct" fix for this is to make our `XamlApplication` `AddRef` its `outer`. C++/WinRT generates bad code here. Long term, we need to fix our XamlApplication stack.

_Bug 22116519: C++/WinRT composable+composing types don't delegate calls during construction_

**Comment by mdtauk** [comment]
Is this one of many problems which goes away when WinUI Desktop comes into existence.  Mixing of XAML and Win32 lifecycle.

**Comment by DHowett-MSFT** [comment]
Completely honest: _XAML islands is WinUI desktop for right now, and this is an issue they have had to tackle in their bringup as well_. Yes, it will go away, but for a while we're trailblazing and feeding our learnings back to them. You're not wrong, though.

**Comment by mdtauk** [comment]
> Completely honest: _XAML islands is WinUI desktop for right now, and this is an issue they have had to tackle in their bringup as well_. Yes, it will go away, but for a while we're trailblazing and feeding our learnings back to them. You're not wrong, though.

It makes sense to continue with the structure as it is now, but every problem you come across, should be "fixed" as WinUI Desktop comes to the fore.

ExtendTitleBar, and naming an element to stand in for the TitleBar dragging - should be in WinUI with Win32 :D
