### ISSUE TITLE
Exchange Online CmdLets not working 

### ISSUE THREAD

**Issue by KJLogic** [microsoft/terminal#13400]
### Windows Terminal version

 1.14.1451.0 and 1.13.11431.0

### Windows build number

Windows 10 Version 21H2 19044.1766

### Steps to reproduce

Start Windows Terminal (Preview or "Normal" version)
connect to Exchange Online (module version 2.0.5 or 2.0.6-preview6) with Connect-ExchangeOnline
can't get "Set-UnifiedGroup" as CmdLet

### Expected Behavior

Set-UnifiedGroup CmdLet working (this was working last week)

Starting a normal PowerShell instance gives me the Set-UnifiedGroup CmdLet.

### Actual Behavior

Set-UnifiedGroup is not available

**Comment by zadjii-msft** [comment]
What's the specific error you're seeing? Honestly this doesn't sound like something we'd be able to investigate properly here - you'd likely have more success on the Excahnge Online issue tracker (wherever that may be). However, it's very suspicious that this isn't working in the Terminal but is in the vintage console....

Which version of PowerShell are you using/?

**Comment by zadjii-msft** [comment]
Glad to hear it isn't us 😅 feel free to follow up with a resolution, if they ever get back to you with one.
