### ISSUE TITLE
Incorrect appearnce for non-bash terminals

### ISSUE THREAD

**Issue by ehosaini** [microsoft/terminal#13402]
### Steps to reproduce

- Go to settings 
- In the Profiles section notice that all the appearance previews have Command-Line's preview

### Expected Behavior

Preview to change for each terminal

### Actual Behavior

Appearance preview doesn't match the terminal e.g. shows the Command Lines preview for Bash and others

**Comment by DHowett** [comment]
Thanks for the report!
The appearance preview is supposed to be representative of general text output, not the active shell :)
