### ISSUE TITLE
Add command palette item to restart the window

### ISSUE THREAD

**Issue by wmstack** [microsoft/terminal#13416]
# Description of the new feature/enhancement
A simple option to reload configuration variables (e.g. `PATH`), or to restart the window. It can save us a few clicks if we can refresh the terminal when installing a new app, for example, from Winget. The issue is that when installing new apps, the PATH is not updated for the application so refreshing the environment variables could be useful.

# Proposed technical implementation details (optional)
Add a command in the palette for restarting the window, and add a command for refreshing the environment variables so that newly installed binaries work directly.

**Comment by zadjii-msft** [comment]
#1125 Seems like it'd be more straightforward - just reload the env vars for new tabs, etc. 

There's also #3726, which is per pane (not per-window), but is probably good enough here, yea/?
