### ISSUE TITLE
[1.15] switchSelectionEndpoint doesn't work

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#13413]
### Windows Terminal version

1.15

### Steps to reproduce

I entered mark mode (or just started with a mouse selection), and `switchSelectionEndpoint` doesn't do anything.

It might be important to note that I'm using it from the command palette.

### Actual Behavior

![gif](https://drop.howett.net/share/WindowsTerminal_qtKLVUVA97.gif)

**Comment by carlos-zamora** [comment]
(putting this here for if somebody comes by before I do)
The weirdest thing! This doesn't repro on a Debug or Release build of `main`, but it 100% repros on the WT Preview build we're selfhosting! I'll take a closer look after the holidays!
