### ISSUE TITLE
PATH Environment Variables cannot be accessed by the terminal when opened via the context menu

### ISSUE THREAD

**Issue by UwUeeb** [microsoft/terminal#13423]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Install an application (eg: git) or set an already existing application to PATH
2. Open File Explorer -> Any Folder -> Right Click -> Windows Terminal
3. Type the application name which has been set to PATH recently in the windows terminal

### Expected Behavior

The application should execute as usual from anywhere as it has been set to the PATH Environment variable like the following screenshot
![image](https://user-images.githubusercontent.com/106700035/177040264-08f44fd8-4e3a-4431-b75f-92dbfa395e74.png)

### Actual Behavior

The application could not be found when opened windows terminal via the context menu 
![image](https://user-images.githubusercontent.com/106700035/177040307-d8a65dd9-0894-4a16-b67f-c831e7cb9d50.png)
but when opened via the windows search or pinned taskbar it actually works as usual 
![image](https://user-images.githubusercontent.com/106700035/177040366-79045906-b0fa-4436-8b75-c5f26d60324b.png)

**Comment by j4james** [comment]
This sounds similar to #12602.

**Comment by UwUeeb** [comment]
yep seems about right, should i close this?
