### ISSUE TITLE
Navigation panel is visible and placed on top if settings editor opened when terminal window is really narrow

### ISSUE THREAD

**Issue by serd2011** [microsoft/terminal#13428]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19043.1706]

### Steps to reproduce

1. Resize terminal window to have small width (then navigation panel is not visible at all and only 3-lines button is present)
2. Open settings editor

This present in terminal 1.13.11431.0 from store, terminal preview 1.14.1451.0 from store, and in compiled 478c2c3613dc7f626474369987ae16a684574c6e

### Expected Behavior

navigation panel is not shown and only button is present

### Actual Behavior

navigation panel is visible and placed on top of the settings

https://user-images.githubusercontent.com/45919738/177596302-140f2be3-bbeb-40e1-b591-02a48a9425a8.mp4

It fixes itself if 3-lines button is pressed. It then opens navigation panel with animation, displays is properly and after closing everything works as expected.
Or if terminal window is resized beyond the point when navigation panel is permanently shown as a narrow bar.

**Comment by zadjii-msft** [comment]
Huh, that's sus, we saw this before in #9337. Maybe after the rejuv, we forgot to give it a fallback color (again)

**Comment by serd2011** [comment]
It shouldn't be visible at all at this point. This happens after SUI is oppened and nav panel should not be shown.

**Comment by zadjii-msft** [comment]
Y'know what, I can only repro this in a Windows 10 VM. I'd bet that this is just something fixed in Windows 11/? 

I can't get the nav view to open expanded, in a small window, anywhere else. This is on a variety of 1.16 builds. I'm gonna let the bot close this one out in a week, unless someone's got a win11 repro.
