### ISSUE TITLE
An error occurred while mounting one of the filesystems. For details, run 'dmesg'.

### ISSUE THREAD

**Issue by John-zhan** [microsoft/terminal#13425]
### Windows build number

1.13.11432.0

### Steps to reproduce

click to start the wsl 

### Expected Behavior

start the wsl release

### Actual Behavior

An error occurred while mounting one of the filesystems. For details, run 'dmesg'.

**Comment by John-zhan** [comment]
Windows Terminal version is 1.13.11432.0
Windows build number 1000.22000.739.0

**Comment by lhecker** [comment]
Does this error occur when you start `wsl` from the start menu outside of Windows Terminal?

**Comment by zadjii-msft** [comment]
This is a WSL issue. See: https://github.com/microsoft/WSL/issues?q=is%3Aissue+%22For+details%2C+run+%27dmesg%27%22
