### ISSUE TITLE
Suggestion: Copy without dismissing selection

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13438]
> Suggestion/question: in ConEmu mark mode `ctrl+c`/copy keybinding copies only but `Enter` copies and exits mark mode. Is that how ours works?

_Originally posted by @ofek in https://github.com/microsoft/terminal/issues/13369#issuecomment-1175483079_

**Comment by carlos-zamora** [comment]
Found it! You were looking for #3884

/dup #3884
