### ISSUE TITLE
Feature Request:  Double height + legacy block drawing characters.

### ISSUE THREAD

**Issue by stuaxo** [microsoft/terminal#1344]
# Summary of the new feature/enhancement

Legacy block drawing characters (as used in PETSCII on C64 / Amiga ) are being added to unicode [1], along with double height / width (as used on VT220 [2], and and teletext).

It would be great if these could be added to Terminal, as it would mean teletext art viewers, PETSCII viewers etc could terminal apps.

Resources:

[1] Unicode proposal to add legacy block drawing characters
https://www.unicode.org/L2/L2019/19025-terminals-prop.pdf

[2] Tests for double height / width characters:
https://invisible-island.net/vttest/vttest.html

Last time I tested xterm / kterm double height characters worked, though it's been a while.

**Comment by DHowett-MSFT** [comment]
We'll look at this when/if Unicode accepts this proposal. Thanks for the heads up!

**Comment by stuaxo** [comment]
It looked like the proposal was accepted, I couldn't view this site at work due to the firewall there:

http://teletextart.co.uk/teletext-graphics-characters-among-those-added-to-unicode

However, this lists them as included in a future version so we will need to wait for that.
