### ISSUE TITLE
Scrollbar area is not hidden

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#13446]
### Windows Terminal version

1.15.1863.0

### Windows build number

10.0.22000.0

### Other Software

any application

### Steps to reproduce

set `scrollbarState` value to `hidden`

### Expected Behavior

Scrollbar and scrollbar's area must to be hidden

### Actual Behavior

Scrollbar is hidden but its area is not.

![Screenshot 2022-07-07 050340](https://user-images.githubusercontent.com/78153320/177675523-8159f821-0cfa-4a0e-971f-ea6f848b5970.png)

**Comment by zadjii-msft** [comment]
I 100% bet I forgot to collapse the marks rectangle when that setting is enabled. 🤦

**Comment by ev-dev** [comment]
Can confirm this issue in preview (v1.15.1863.0), for two same sized windows open in preview & stable versions, the literal value of `$Host.UI.RawUI.WindowSize.Width` becomes -2 off in term preview compared to that value in stable (v1.14.1862.0)
