### ISSUE TITLE
Keyboard layout changes it self.

### ISSUE THREAD

**Issue by warshell** [microsoft/terminal#13459]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0 Microsoft Windows NT 10.0.22000.0

### Steps to reproduce

launching a python script

### Expected Behavior

When i try to luch a python application inside the CLI
it add me a United States English Qwerty to the windows keyboard layouts.

Currently i have  2 layouts
```
English United States French
German German
```

### Actual Behavior

add a english layout

**Comment by zadjii-msft** [comment]
* What shell are you launching your python script from/?
* Does this happen for _all_ python scripts?
* Does this happen when you launch other child processes from that shell? (e.g. running `pwsh` from `cmd` or something)

**Comment by warshell** [comment]
> * What shell are you launching your python script from/?
> * Does this happen for _all_ python scripts?
> * Does this happen when you launch other child processes from that shell? (e.g. running `pwsh` from `cmd` or something)

1.  Windows Powershell
2. Just tested, yes
3.  No


ps: forget to say. The new English US Qwerty is hidden in the windows Language and region, i must manually add it and delete again .

**Comment by zadjii-msft** [comment]
> Does this happen for all python scripts

> Just tested, no, only my script, so i need to dig inside and its nothing related to terminal

Yea, I'd reckon that's the root cause here. Either something you're doing, or something one of your dependencies is doing. Not sure there's anything more I know to try and help debug. Sorry about that!
