### ISSUE TITLE
Command palette  goes to the top when you go back (<) from a submenu

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#13457]
As the subject says, if I open a submenu of the command palette (e.g., "New tab") and go back via the <-button, I'm back at the top of the command palette.  I'd prefer to be back where I was.  It's not a bug, but the bahavior could be made more friendly.

**Comment by zadjii-msft** [comment]
Hmm this is in #5400, I'm pretty sure it's a full issue somewhere too

> The "go back" button should pop only one layer of the stack, not go all the way back to the root (https://github.com/microsoft/terminal/pull/8051#issuecomment-722045813)

**Comment by vefatica** [comment]
I guess that's a matter of terminology.  The actual behavior and my desired behavior both go back to the command palette.  It's the position in the command palette after going back that concerns me ... back to the beginning of the command palette or back to where I was.

**Comment by JerBast** [comment]
@zadjii-msft, I would be happy to work on this as my first contribution to this repo (if possible). I assume the desired result is to focus the filtered view to the previously selected item when returning from a nested collection?

![image](https://user-images.githubusercontent.com/27634653/178750016-6adf00ba-6cc2-4558-b9ba-4ccfcce37115.png)

**Comment by zadjii-msft** [comment]
That's what I would do, yea! Lemme know if you have any questions. This line: https://github.com/microsoft/terminal/blob/574a72b505a682a09ea9d533295d3d576556e6c0/src/cascadia/TerminalApp/CommandPalette.cpp#L539 is where I'd start ☺️

**Comment by vefatica** [comment]
I just got this one:

`"Microsoft.WindowsTerminalPreview_Win10_1.16.2523.0_8wekyb3d8bbwe.msixbundle"`

or maybe it's this one:

`WindowsTerminalPreview 1.16.2209.09003`

Is that one Windows Terminal Preview v1.16.252?

It has too many version descriptions!

The back button works as desired.  I didn't mention it earlier but I'd expect Esc to do the same thing (i.e., go back) but it just  closes the command palette.
