### ISSUE TITLE
Flash the pane dark when BEL is emitted and pane's appearance has a light background

### ISSUE THREAD

**Issue by yunruse** [microsoft/terminal#13450]
# Description of the new feature/enhancement

Pull request [Add a setting to flash the pane when BEL is emitted #9270](https://github.com/microsoft/terminal/pull/9270) implemented a visual BEL indictor on the working terminal pane. It's currently a white flash, which works well against a traditional dark-mode background. However, on a light appearance this basically only lightly flashes the text, making it a little hard to notice!
Is there a possibility this could be modified to work with higher contrast light-mode users? Thank you!

# Proposed technical implementation details (optional)

I'd probably set (and store?) an `isBackgroundLight` bool somewhere iff the background color of the pane is "light". If it is, and the BEL handler has the `window` flag set, the pane would flash _dark_ on a BEL instead of light. 

A quick way to find `isBackgroundLight` may be to just see if the average of `r`, `g` and `b` is higher than `127`. I can't imagine enough people have `#888888`-ish terminals for this to warrant being a manually-defined setting.

**Comment by zadjii-msft** [comment]
That seems sensible to me!

**Comment by carlos-zamora** [comment]
> (@carlos-zamora you think this is something that counts as an a11y bug?)

Yeah. It's basically a high-contrast bug, when you think about it (just not limited to high contrast mode itself). Similar to how we are expected to have a good enough contrast for text in SUI.
