### ISSUE TITLE
Windows Terminal folder on path, causes problems with wt.exe

### ISSUE THREAD

**Issue by ashbob999** [microsoft/terminal#13460]
### Windows Terminal version

1.15.1862.0 (Preview from windows store)

### Windows build number

10.0.19044.1806

### Steps to reproduce

Open Windows Terminal to a Ubuntu (wsl) tab.
Then open a new Command Prompt tab.
Run `wt.exe -h`.

### Expected Behavior

Running `wt.exe` in any windows terminal window should work as expected.

### Actual Behavior

`wt.exe` does not work, it finds `wt.exe` but does not produce any output.
Running `where wt.exe` produces:
```
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.15.1862.0_x64__8wekyb3d8bbwe\wt.exe
C:\Users\ashbo\AppData\Local\Microsoft\WindowsApps\wt.exe
```

I have tested that both of these work correctly when run from the regular command prompt.
Also it seems like it only affects windows terminal instances that were created with an Ubuntu (wsl) tab, because if i run `where wt.exe` in a second windows terminal instance it produces:
```
C:\Users\ashbo\AppData\Local\Microsoft\WindowsApps\wt.exe
```

From looking at the %Path% variable, it seems like it's a problem if 
```C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.15.1862.0_x64__8wekyb3d8bbwe```
is in the path.

If i temporarily remove it from the Path, using:
`set PATH=%PATH:C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.15.1862.0_x64__8wekyb3d8bbwe;=%`
then it sees to work correctly, but only on that specific tab (where the Path has been modified).

So it seems like whenever a new terminal window is created, with the start tab being Ubuntu (wsl). Then whenever a command prompt is created within that window, either by a new tab, or through `cmd.exe` in wsl. The Path is updated to include the windows terminal folder. Which then breaks the `wt.exe` command.

**Comment by zadjii-msft** [comment]
So yes - having `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal*` on the path will definitely break things. The stuff in there is all ACL'd up so that only the OS can read/write it, by design. 

What's highly unusual is having that path get added to the PATH. Is there something in your WSL config that's adding anything to the path/? Unfortunately, I'm not super familiar with how stuff like WSLENV works these days. Maybe @craigloewen-msft can help triage. 

The goal here is to figure out whatever is inserting that `WindowsApps` path into the PATH, cause that just ain't right

**Comment by zadjii-msft** [comment]
oh ho ho, that's a great repro. Thanks for that. We can definitely forward that to the platform team. 

This does look a lot like #7204 but I'm gonna keep this open for a sec so I'll remember to dedupe the others too.

**Comment by ashbob999** [comment]
I see there is a problem with the PATH being added to, which stops it working inside certain windows terminal instances.
But I think the main cause of the issue, it that the `wt.exe` in `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal*` doesn't work.
> So yes - having `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal*` on the path will definitely break things. The stuff in there is all ACL'd up so that only the OS can read/write it, by design.

Maybe it's not meant to be run manually, but if I search for `wt` in the start menu, it shows the path as being `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal*\wt.exe`. But also I cannot run `wt` or `wt.exe` from `Win+R`.

This is similar to #7188 but instead I get nothing happen (no error messages).
@KalleOlaviNiemitalo mentions about registry keys.
> When I install Windows Terminal Preview, AppXSvc creates the following Registry keys:
> - HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe
> - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe

Both of mine point to the same folder/`wt.exe` file as above.
If I rename both of these, then `wt` works from both start menu and `Win+R`. Although the `wt` shown in start menu loses it's icon.

**Comment by zadjii-msft** [comment]
(never came back to dedupe)

/dup #7204
