### ISSUE TITLE
Lots of local unit tests are failing again

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#13474]
### Windows Terminal version

Commit bbc570d107b6b67b68454355e04724ecea9c9796

### Windows build number

10.0.19044.1706

### Steps to reproduce

1. Checkout the latest code.
2. Build.
3. Run the unit tests.

### Expected Behavior

All tests should pass.

### Actual Behavior

I'm seeing 38 failures. I couldn't capture the full list, but this is some of them:

    SettingsModelLocalTests::DeserializationTests::ValidateDefaultProfileExists [Failed]
    SettingsModelLocalTests::DeserializationTests::ValidateDuplicateProfiles [Failed]
    SettingsModelLocalTests::DeserializationTests::ValidateManyWarnings [Failed]
    SettingsModelLocalTests::DeserializationTests::TestInvalidColorSchemeName [Failed]
    SettingsModelLocalTests::DeserializationTests::ValidateKeybindingsWarnings [Failed]
    SettingsModelLocalTests::DeserializationTests::ValidateColorSchemeInCommands [Failed]
    SettingsModelLocalTests::DeserializationTests::ValidateExecuteCommandlineWarning [Failed]
    SettingsModelLocalTests::DeserializationTests::TestNestedCommandWithoutName [Failed]
    SettingsModelLocalTests::DeserializationTests::TestNestedCommandWithBadSubCommands [Failed]
    SettingsModelLocalTests::SerializationTests::Actions [Failed]
    SettingsModelLocalTests::SerializationTests::CascadiaSettings [Failed]
    SettingsModelLocalTests::TerminalSettingsTests::MakeSettingsForDefaultProfileThatDoesntExist [Failed]
    SettingsModelLocalTests::ThemeTests::ParseSimpleTheme [Failed]
    SettingsModelLocalTests::ThemeTests::ParseNoWindowTheme [Failed]
    SettingsModelLocalTests::ThemeTests::ParseNullWindowTheme [Failed]

    TerminalAppLocalTests::SettingsTests::TestIterateCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnGeneratedNamedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnBadJson [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInIterableCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterableInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestMixedNestedAndIterableCommand [Failed]
    TerminalAppLocalTests::TabTests::TryInitializePage [Failed]
    TerminalAppLocalTests::TabTests::TryDuplicateBadTab [Failed]
    TerminalAppLocalTests::TabTests::TryDuplicateBadPane [Failed]
    TerminalAppLocalTests::TabTests::TryZoomPane [Failed]
    TerminalAppLocalTests::TabTests::MoveFocusFromZoomedPane [Failed]
    TerminalAppLocalTests::TabTests::CloseZoomedPane [Failed]
    TerminalAppLocalTests::TabTests::SwapPanes [Failed]
    TerminalAppLocalTests::TabTests::NextMRUTab [Failed]
    TerminalAppLocalTests::TabTests::VerifyCommandPaletteTabSwitcherOrder [Failed]
    TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful [Failed]
    TerminalAppLocalTests::TabTests::TestWindowRenameFailure [Failed]
    TerminalAppLocalTests::TabTests::TestPreviewCommitScheme [Failed]

**Comment by zadjii-msft** [comment]
I sure bet I busted this with the themes PR. I'll dig in more.
