### ISSUE TITLE
Window loses focus when clicking on taskbar icon to minimize/maximize

### ISSUE THREAD

**Issue by LukeDearden** [microsoft/terminal#13479]
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19044.0

### Steps to reproduce

open terminal
click the taskbar icon to minimize
click the taskbar icon to maximize

### Expected Behavior

Expecting the Terminal Window to come into focus

### Actual Behavior

The Terminal Window doesn't come into focus.

As a work around I enabled the "Always display an icon in notification area" which allows me to regain focus on the Terminal Window

**Comment by zadjii-msft** [comment]
Hmm, I can't repro this (on 22XYZ builds, but that _shouldn't_ affect this...). 
* Are you doing this with the `_quake` windo w by any chance/?
* Do you mave multiple tabs, or panes, in the window?
* What profile are you running in the window?


I'm guessing this is related to the focus/foreground work, but I really can't be sure.

**Comment by LukeDearden** [comment]
> 

- Not sure what _quake window is so probs not
- Single tab to start with but by default I run it as admin
- PowerShell 7.2.5

Also I tested with v1.14.186 and didn't have this problem.

**Comment by zadjii-msft** [comment]
> •	Single tab to start with but by default I run it as admin

Ooh, good observation. Are you using `elevate: true` in the settings to have the profile automatically launch elevated? (it may be easiest if you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?)

This is gonna maybe sound crazy, but when this happens, what application is focused before you switch to the Terminal? Like, when you minimize the Terminal, does Task Manager get focused, and then you're trying to restore Terminal from minimized while Task Manager is active/?

**Comment by valepu** [comment]
Hi, just wanted to let you know I found another workaround to this issue (I didn't like having to use show all icons on the taskbar):
1. Shift + right-click on the terminal in the taskbar
2. Click "Restore" (Maximize works too, then you can safely return it to the previous size)

Hope it will be of help until it gets fixed :)

**Comment by zadjii-msft** [comment]
HO BOY I bet this is related to #13589

**Comment by zadjii-msft** [comment]
Actually, yea this is definitely /dup #13589. You got here first, but that thread has more centralized info on the root cause.
