### ISSUE TITLE
selecting current screen instead of selecting current line in PowerShell PSReadLine

### ISSUE THREAD

**Issue by lost4git** [microsoft/terminal#13470]
### Windows Terminal version

1.14.220705001

### Windows build number

10.0.22000.0

### Other Software

|app/module|version|
|--|--|
|PowerShell|7.2.5|
|PSReadLine|2.2.6|

### selecting current screen in powershell core in wt (unexpected)

![image](https://user-images.githubusercontent.com/65008815/178097090-20a6c489-cf4a-41ea-8b3f-24601d5e77ee.png)

### selecting current line in single powershell core (expected)

![image](https://user-images.githubusercontent.com/65008815/178097156-0d1fd204-e8dc-407e-8b50-a44ae2be9036.png)

### Expected Behavior

selecting current line

### Actual Behavior

selecting current screen

**Comment by zadjii-msft** [comment]
How exactly are you starting the selection here? With the mouse? With a keyboard shortcut? If you're pressing something like `Ctrl+A`, is there already a selection present/?

**Comment by lost4git** [comment]
@zadjii-msft  I bind the `<c-s-a>` to select all in PSReadLine module

![image](https://user-images.githubusercontent.com/65008815/178409140-f38747d0-25b2-4078-bc72-546e76e880b5.png)

**Comment by lost4git** [comment]
maybe i shoud remove this in wt

![image](https://user-images.githubusercontent.com/65008815/178409497-bd32c094-c3a5-4967-b99f-5d67974ecb20.png)

**Comment by zadjii-msft** [comment]
Yep that's exactly the issue then! We introduced `selectAll` as a keybinding in 1.14 ☺️
