### ISSUE TITLE
`Open system menu` doesn't work from the command palette

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13472]
### Windows Terminal version

1.15.1863.0

### Windows build number

10.0.22000.778

### Steps to reproduce

`ctrl + shift + p` to open command palette
select `Open system menu` command

### Actual Behavior

nothing happens

**Comment by zadjii-msft** [comment]
Huh. It totally doesn't. Thanks for the heads up!

**Comment by zadjii-msft** [comment]
Actually, y'know what, I'm gonna use #11970 to track this. Thanks!

/dup #11970
