### ISSUE TITLE
Settings.json file not opening

### ISSUE THREAD

**Issue by RiteshChepuri** [microsoft/terminal#13482]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Settings.json file from the settings of terminal

### Expected Behavior

To Open the Settings.json file

### Actual Behavior

When I clicked on the settings,json to open it is prompting to open vs code but it is not showing any file

**Comment by zadjii-msft** [comment]
Could you share a screenshot of what it looks like in VsCode when this happens? 

If you try manually opening [the settings file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file) in notepad, is the file empty/?

**Comment by RiteshChepuri** [comment]
I think there has been some issue with vs code it is working now. Thank you
