### ISSUE TITLE
[1.16] `wt nt ; nt ; nt` might be different now

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13480]
A note from a Teams discussion I don't want to lose. #13421 might have changed the behavior here. We'll spin a 1.16 selfhost soon we can use to check.

**Comment by zadjii-msft** [comment]
This seems okay to me. With the new `afterCurrentTab` setting:

`wt -w 3 nt -p HONK ; nt -- pwsh ; nt ; nt -p HONK`

With the first cmd and settings tab opened, this created:
![image](https://user-images.githubusercontent.com/18356694/181801064-9df07fc0-780b-4925-9fe7-11ebe01a2832.png)
(HONK is green)

Again with `pwsh` selected:

![image](https://user-images.githubusercontent.com/18356694/181801236-00f7bdce-94d6-4427-b2d2-fff3cda90773.png)
The blue tabs were added on the first run, the red on the second. This seems fine to me.

**Comment by DHowett** [comment]
How about from a clean launch with no tabs open? Do we get the order right?

**Comment by zadjii-msft** [comment]
> How about from a clean launch with no tabs open? Do we get the order right?

Seems right to me. 
![image](https://user-images.githubusercontent.com/18356694/181820185-b8158cf9-3c65-45d0-9e8a-edce1ebc3860.png)

* The first tab is created at the end, so after current == at end
* the N'th tab is created at the end -> the current tab becomes the Nth -> the end is also the Nth

**Comment by DHowett** [comment]
Thanks!
