### ISSUE TITLE
Dropping over Terminal releases IDataObject

### ISSUE THREAD

**Issue by knopp** [microsoft/terminal#13498]
Easiest way to reproduce is to drag over the tab bar. `IDataObject` passed to `DoDragDrop` will be released while `DoDragDrop` is still in progress. The `IDataObject` contains `CFSTR_FILEDESCRIPTOR` and `CFSTR_FILECONTENTS` entries, though I'm not sure the payload is relevant.

Another issue is that terminal will request the `IStream` for `CFSTR_FILECONTENTS` while dragging over but never reads from it or releases it.

Version: 1.13.11432.0.

**Comment by knopp** [comment]
It also seems that sometimes the `IDataObject` reference is held by the terminal until next drop.

**Comment by zadjii-msft** [comment]
> The `IDataSource` object being held until next drop only happens when dragging over the tab row, not the term control.

Hmm, sounds like something that needs to go upstream to https://github.com/microsoft/microsoft-ui-xaml.


> The `IStream` being received not being released might perhaps be a problem in `DataPackageView`?

Could be. I honestly don't know where that kind of bug would go. If you have a minimal repro, they might be interested over in https://github.com/microsoft/WindowsAppSDK

**Comment by zadjii-msft** [comment]
Since wherever this bug lies, it's ultimately upstream from the Terminal, I'm gonna close this out to clean up our issue tracker. Feel free to link back to this thread for context. If we need to ingest some change to fix this on our side, I'll be happy to reopen it. 

Thanks!
