### ISSUE TITLE
Update to WinUI 2.8 (was: History size overlaps with widget controls)

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13495]
### Windows Terminal version

1.15.1863.0

### Windows build number

10.0.22000.778

### Steps to reproduce

Enter a large history size, INT_MAX used for testing

### Expected Behavior

No overlapping

### Actual Behavior

![max_history_size](https://user-images.githubusercontent.com/3933920/178622277-6827ea18-30c7-44de-b0c4-c243b8149d9f.png)

## _maintainer note_

Also:
* [ ] #9822

**Comment by serd2011** [comment]
isn't this it https://github.com/microsoft/microsoft-ui-xaml/issues/5983 ?

**Comment by zadjii-msft** [comment]
Sure looks like it to me, thanks! We haven't had an opportunity to move to WinUI 2.8 yet, but I'm gonna tentatively use this to track upgrading. We also need to do this to fix the crashes associated with #12413 in downlevel OS versions.

**Comment by zadjii-msft** [comment]
Taking this out of 1.16, cause it seems like there's a lot of issues with 2.8 and we don't have the runway to sort them all out. The important bit, the #12413 crash, we're gonna fix with a minor hotfix to 2.7.
