### ISSUE TITLE
Can't type inside Windows Terminal git bash/zsh

### ISSUE THREAD

**Issue by wangzhichao1990** [microsoft/terminal#13497]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Other Software

Git-2.37.1-64-bit
zsh : 5.8-5, https://packages.msys2.org/package/zsh?repo=msys&variant=x86_64

### Steps to reproduce

Zsh installation: https://dominikrys.com/posts/zsh-in-git-bash-on-windows/
Open the Git bash tab in Windows terminal,  maximize the window or wait a moment. You should no longer be able to type on the terminal.

### Expected Behavior

git bash / zsh work well

### Actual Behavior

Can't type inside Windows Terminal git bash/zsh

**Comment by zadjii-msft** [comment]
Does this happen with any other shells/? (cmd, pwsh, zsh on WSL?)

**Comment by zadjii-msft** [comment]
Well, that sounds like a oh-my-zsh bug then, something that should probably be filed downstream. 

Thanks for following up!
