### ISSUE TITLE
Wrong terminal content redrawing after some time of inactivity... 

### ISSUE THREAD

**Issue by igorkuzuro** [microsoft/terminal#13490]
### Windows Terminal version

Bulded from source... Last commit fd74d59c6c87a1ac49ffea11142ce273e07f95f0

### Windows build number

10.0.25151.0

### Other Software

PowerShell
Far Manager

### Steps to reproduce

After some time of inactivity we lost content redrawing... some parts still visible, links still exists and works as expected (click works and url under link is still right, underlined on hoover), background also seems ok for example... we can copy content of terminal and copy is fine. All tabs in same (wrong) state after some time... new ones is ok.

clear in powershell for example make some differences... but not solve problem: 3rd attached screenshot

On attached screenshots first tab with PowerShell after some time of inactivity and second tab in same terminal - new - with PowerShell in same scroll position.

### Expected Behavior

![image](https://user-images.githubusercontent.com/1778999/178478620-5e4475e1-cfc8-4755-900c-0eafa465cd52.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1778999/178478532-9fc017aa-9e68-4e68-8c8f-53500b3d4357.png)
![image](https://user-images.githubusercontent.com/1778999/178481548-1628040d-213f-40a9-aeaa-2600d7ceb847.png)

**Comment by igorkuzuro** [comment]
> Huh. Are you using the experimental atlas engine?
> 
> /cc @lhecker

Yes - Atlas

**Comment by zadjii-msft** [comment]
Welp, there's a couple fresh commits here that might have caused this. 

If you'd be willing to help with debugging - does this repro on either of:
* 32379c29f025ffdede0c56884ec5a30871c2a8c2
* bbc570d107b6b67b68454355e04724ecea9c9796

Those are the commits before a couple PRs in this area recently.

(thanks for selfhosting the bleeding edge here ☺️)

**Comment by igorkuzuro** [comment]
> Welp, there's a couple fresh commits here that might have caused this.
> 
> If you'd be willing to help with debugging - does this repro on either of:
> 
> * [32379c2](https://github.com/microsoft/terminal/commit/32379c29f025ffdede0c56884ec5a30871c2a8c2)
> * [bbc570d](https://github.com/microsoft/terminal/commit/bbc570d107b6b67b68454355e04724ecea9c9796)
> 
> Those are the commits before a couple PRs in this area recently.
> 
> (thanks for selfhosting the bleeding edge here ☺️)

Will check...

**Comment by lhecker** [comment]
So this issue consists of two bugs:
* Rows outside of the `_api.dirtyRect` (i.e. rows that haven't changed) need to be pushed to the head of the LRU queue so that they don't get invalidated. For instance if you use `tmux` and only scroll the bottom half, the glyphs of the top half need to be retained in the texture atlas of course. I actually planned for that, but forgot to add it in my PR so this was easy to fix. I'm sure this is what causes most of the above issues.
* Hard problem: https://github.com/microsoft/terminal/commit/d74b66a0a7955de529f02fd394d6f6536a96e88c has a bug where just opening OpenConsole's Properties dialog and clicking Ok without changing anything causes the texture atlas to go all black. I checked it in QRenderDoc and the texture is absolutely blank (no alpha, no nothing).
  * Puzzling part 1: Reverting the changes to `AtlasEngine::_drawGlyph` doesn't work. No text is produced.
  * Puzzling part 2: The `ID2D1RenderTarget` must work in principle however, because it _does_ produce the cursor texture correctly. Only the text is gone. It can't be the `_r.brush` either because I'm recreating it whenever I recreate the `ID2D1RenderTarget`.

**Comment by igorkuzuro** [comment]
> So this issue consists of two bugs:
> 
> * Rows outside of the `_api.dirtyRect` (i.e. rows that haven't changed) need to be pushed to the head of the LRU queue so that they don't get invalidated. For instance if you use `tmux` and only scroll the bottom half, the glyphs of the top half need to be retained in the texture atlas of course. I actually planned for that, but forgot to add it in my PR so this was easy to fix. I'm sure this is what causes most of the above issues.
> * Hard problem: [d74b66a](https://github.com/microsoft/terminal/commit/d74b66a0a7955de529f02fd394d6f6536a96e88c) has a bug where just opening OpenConsole's Properties dialog and clicking Ok without changing anything causes the texture atlas to go all black. I checked it in QRenderDoc and the texture is absolutely blank (no alpha, no nothing).
>   
>   * Puzzling part 1: Reverting the changes to `AtlasEngine::_drawGlyph` doesn't work. No text is produced.
>   * Puzzling part 2: The `ID2D1RenderTarget` must work in principle however, because it _does_ produce the cursor texture correctly. Only the text is gone. It can't be the `_r.brush` either because I'm recreating it whenever I recreate the `ID2D1RenderTarget`.

And... not all text is gone... some glyphs still visible some not... if it matters

For example...

C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 0A20-79B9

 Directory of C:\

18.01.2019  14:36             1 024 .rnd
16.06.2022  12:53            12 288 DumpStack.log
21.03.2022  13:52    <DIR>          Intel
12.07.2022  15:35    <DIR>          opt
26.06.2022  15:25    <DIR>          PerfLogs
06.07.2022  16:38    <DIR>          Program Files
01.07.2022  10:37    <DIR>          Program Files (x86)
30.06.2022  23:41    <DIR>          Users
06.07.2022  03:41    <DIR>          Windows
               2 File(s)         13 312 bytes
               7 Dir(s)  15 891 099 648 bytes free

![image](https://user-images.githubusercontent.com/1778999/178523372-e61d7bdc-2e0d-41e0-895a-5a56fef84a68.png)

**Comment by lhecker** [comment]
If you'd like to, please feel free to test out my PR! I'm confident that it should fix these issues. 🙂

**Comment by igorkuzuro** [comment]
> If you'd like to, please feel free to test out my PR! I'm confident that it should fix these issues. 🙂

Compiled and deployed... in release configuration.

Everything seems ok. At least in my usual usage... powershell (with oh-my-posh), ssh, tmux, far manager, etc.

My manual tests are not so extensive at this time, but don't see any problems.
