### ISSUE TITLE
Request: Add command line arguments to the "Open in Terminal" context menu option

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/terminal#13507]
# Description of the new feature/enhancement

I would like to use the option "Open in Terminal" in the context menu (accessed by right click) with some additional [command line arguments](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows).

Specifically, I would like to use this option adding the argument [`-w 0`](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#target-a-specific-window), which opens the terminal as a new tab in the same opened current  window instance, instead of creating a new window.

But this feature could be used for any choice of command line arguments (profile, title, etc).

# Proposed technical implementation details (optional)

This could be set on the settings of the software, as an additional field in the `settings.json`, nothing very complicated for the user point of view.

**Comment by DHowett** [comment]
Thanks! Unless I'm misreading or misunderstanding your request, you can get that behavior with this guy in Settings:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/189190/179060820-5ecf4604-7838-478b-8baf-506e9f07a18a.png">

Whether we should break it down by origin (ala "when opened via wt, attach; when opened via taskbar, new window; when opened via taskbar flyout menu, attach")
