### ISSUE TITLE
Ctrl+c doesn't work after have used `ssh` in Powershell in the same terminal session

### ISSUE THREAD

**Issue by jacobrastad** [microsoft/terminal#13503]
### Windows Terminal version

1.13.11432.0

### Windows build number

 10.0.22000.0

### Other Software

Using `ssh.exe`
```
ssh.exe -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

```
### Steps to reproduce

1. Login/try to login with SSH on any remote host that accepts ssh connections. Then exit that.
2. Run ping 8.8.8.8 -t
3. Try to exit with ctrl+c

**Update**
The issue only appears if the ssh-session ends with some sort of error (like pressing ctrl+c when trying to connect). If I connect successfully and exits the ssh-session with `exit` command. Everything works as normal.

### Expected Behavior

The ping-action should stop

### Actual Behavior

Nothing happens, the continuous ping keeps going.

Tried ctrl+break which prints out a new empty line briefly. But it doesn't exit the running operation and the pingin keeps going.

### Other info
Other possibly related issues
- https://github.com/microsoft/terminal/issues/6258
- https://github.com/microsoft/terminal/issues/8034

#### Print screen of repro steps
<img width="813" alt="image" src="https://user-images.githubusercontent.com/6196028/178973951-0b22ece7-fbe7-40ca-ad31-9e019180ae41.png">

**Comment by zadjii-msft** [comment]
Which `ssh` are you using? `ssh.exe` that ships with Windows? `ssh` from a WSL distro? Or some other `ssh`? And which version of `ssh`?

**Comment by jacobrastad** [comment]
@zadjii-msft I've updated the description with the info
```
ssh.exe -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

**Comment by zadjii-msft** [comment]
This looks a bit like
https://github.com/PowerShell/Win32-OpenSSH/issues/1699

but 

> No issue using `conhost.exe` , there it works as expected

scares me, for sure.

**Comment by zadjii-msft** [comment]
Okay great, thanks. All that would have me think that this is, in fact, https://github.com/PowerShell/Win32-OpenSSH/issues/1699, so I'm gonna close this to track the downstream issue. Thanks!

/dup https://github.com/PowerShell/Win32-OpenSSH/issues/1699
