### ISSUE TITLE
Top-Level Accessibility: Set Up UIA Tree

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#1350]
# Summary of the new feature/enhancement

Set up the Windows Terminal to have and return a UIA tree.

# Proposed technical implementation details (optional)

- [ ] Create UIA tree
- [ ] Hook it up properly

**Comment by zadjii-msft** [comment]
Wait isn't this #634?

**Comment by carlos-zamora** [comment]
> Wait isn't this #634?

Sorta? I'm closing this as a duplicate and moving this info over to that.
