### ISSUE TITLE
Fundamental Accessibility: Modify conhost accessibility model

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#1352]
# Summary of the new feature/enhancement

Modify the current conhost accessibility model for Windows Terminal usage and integration.

# Proposed technical implementation details (optional)

- [ ] Find where obsolete objects are used in accessibility model
- [ ] Modify method signatures to take in what they specifically use, rather than entire obsolete objects
- [ ] Hook up this UIA tree to top-level (#1350)

**Comment by oising** [comment]
Is this an opportunity to improve #410 ? In particular the accessibility broadcasts that slow down all consoles when node is running.

**Comment by DHowett-MSFT** [comment]
@oising probably not, sorry!
