### ISSUE TITLE
Windows Terminal not 100% shown in context menu

### ISSUE THREAD

**Issue by lychichem** [microsoft/terminal#13523]
### Windows Terminal version

1.14.1861.0

### Windows build number

10.0.22622.290

### Steps to reproduce

1. Install windows terminal 1.14.1861.0
2. Right click in some folder
3.  The bug happens.

### Expected Behavior

The "open in terminal" should display every time.

### Actual Behavior

The "open in terminal" don't display every time. I can see it 1 time when I right click every around 6 times.

**Comment by lychichem** [comment]
Maybe related to powertoys as it happens just after powertoys updated to 0.60.x

**Comment by zadjii-msft** [comment]
Hmm, that sure is weird. Can you file feedback using the Feedback Hub, under the "Desktop Environment > Right Click Context Menu" area/?

![image](https://user-images.githubusercontent.com/18356694/179498580-8c24c5bf-b740-4bab-943a-a88ca40ffbfa.png)

I'm not sure there's much we can do to investigate here, but getting this to the team that owns the context menus might help the investigation. If you "Share" the `aka.ms` link to that feedback here, I can make sure to follow the internal bug that gets generated. Thanks!

**Comment by lychichem** [comment]
Now I uninstalled powertoys, things looks ok. Will test again by reinstall powertoys.

**Comment by lychichem** [comment]
> I am very sure this problem is related to the latest version powertoys. If you want to fix it, you just need turn off Power Rename and Image Resizer. 

2 of 3 reasons I use powertoys are power rename and image resizer. So your fix seems painful for me...

**Comment by zadjii-msft** [comment]
I'm gonna tentatively say that this is tracking upstream. If this comes back as not a PowerToys AND not an OS issue, then we can reopen if there's something for us to fix here. Thanks for following up!

**Comment by zadjii-msft** [comment]
I'm actually gonna reopen this. We've got like, a LOT of crashes in `OpenTerminalHere::GetState`

There's no internal bug for this yet (weird), but it is in `33573326-3f07-2517-b549-6f77533ee596`. 

https://github.com/microsoft/terminal/blob/4e5a0c137b045d9f1f34114d12bc3b0ed0a03800/src/cascadia/ShellExtension/OpenTerminalHere.cpp#L100-L129

Maybe there's a way for the array to be non-null but have 0 items in it?

**Comment by zadjii-msft** [comment]
Promoted to MSFT:40872815

probably regressed in #13206

**Comment by zadjii-msft** [comment]
I'm pretty sure that we fixed this in https://github.com/microsoft/terminal/releases/tag/v1.15.2282.0 by reverting #13206. Thanks all!
