### ISSUE TITLE
Unicode Box drawings characters not rendered correctly (disappear) with Japanese fonts

### ISSUE THREAD

**Issue by kissge** [microsoft/terminal#13527]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Other Software

MyricaM https://github.com/tomokuni/Myrica/raw/master/product/MyricaM.7z
Ricty Diminished https://github.com/mzyy94/RictyDiminished-for-Powerline/blob/master/RictyDiminished-Regular.ttf

### Steps to reproduce

1. Set font face to e.g. MyricaM M.
2. Print characters like `U+2500  BOX DRAWINGS LIGHT HORIZONTAL` and `U+2502  BOX DRAWINGS LIGHT VERTICAL` by running e.g. `tree`.

```
/tmp/test
├── bar
│   └── baz
└── foo

1 directory, 2 files
```

### Expected Behavior

`─` and `│` are printed.

### Actual Behavior

Those characters are rendered improperly.

MyricaM M ... vertical bars are **missing**, and horizontal bars have **wrong width**

![myricam](https://user-images.githubusercontent.com/4177010/179435110-221c5b46-6461-4ca0-83d6-efd10314b497.png)

Ricty Diminished ... horizontal bars are **missing**

![ricty](https://user-images.githubusercontent.com/4177010/179435113-b00833fa-0346-4927-8369-87fcbe3a0bda.png)

Lucida Console ... OK _(though Japanese characters fall back to another font (I can't tell which font), causing weird spacing between letters)_

![lucida_console](https://user-images.githubusercontent.com/4177010/179435115-2a83294c-7cd8-4158-912e-fe5afced26f7.png)

**Comment by zadjii-msft** [comment]
Huh. Thanks for the report! Dunno why this would be happening. Hopefully this gets fixed with the new experimental text renderer, we'll see.

**Comment by lhecker** [comment]
That font is Yu Gothic UI Regular.
![Yu Gothic UI Regular](https://user-images.githubusercontent.com/2256941/179556735-660a219d-cae7-42e6-a128-0ca099ddf63e.png)

Yu Gothic is a proportional font according to Wikipedia and if that's correct we should probably pick MS Gothic instead:
![MS Gothic Regular](https://user-images.githubusercontent.com/2256941/179556547-0c54cb99-b8a4-4763-80d2-96818cf4c054.png)

In either case, the good news is that this issue doesn't occur with the experimental text rendering engine ("AtlasEngine"):
![image](https://user-images.githubusercontent.com/2256941/179558030-70420b5b-8b31-4348-b1aa-3367250d8123.png)

The line drawings have significant gaps now unfortunately, but at least they're visible and it's an issue that I'm currently planning to improve on in the near-ish future.

**Comment by kissge** [comment]
> In either case, the good news is that this issue doesn't occur with the experimental text rendering engine ("AtlasEngine"):

Great to hear that!

I've confirmed that too, with Preview 1.15.1863.0.

![myricam-altas](https://user-images.githubusercontent.com/4177010/179639424-dcc46cae-e6be-4fa1-a89f-d61216ada410.png)

![ricty-atlas](https://user-images.githubusercontent.com/4177010/179639426-f2fdc9bc-db81-4f68-990a-bc6179b044fe.png)

![lucida_console-atlas](https://user-images.githubusercontent.com/4177010/179639429-79bc8d32-3393-472c-a457-9e3640f84629.png)


> Yu Gothic is a proportional font according to Wikipedia

Seemingly, yes, that's true.

![yugothic](https://user-images.githubusercontent.com/4177010/179640226-a5900151-3a84-4e27-bead-964cc7434d86.png)

> and if that's correct we should probably pick MS Gothic instead:

Or I'd rather suggest that if a user can explicitly set "fallback" font faces, just like CSS `font-family`, that'd be even better. I think this is already possible e.g. in Visual Studio Code, which has different rendering mechanism, so it may not be straightforward how to introduce such capability to Terminal.

**Comment by lhecker** [comment]
@zadjii-msft We improved box drawing rendering for AtlasEngine in #13549. Should we close this issue now?

**Comment by tats-u** [comment]
> Yu Gothic is a proportional font according to Wikipedia and if that's correct we should probably pick MS Gothic instead:

Note: all Japanese and Chinese (full-width) characters in Yu Gothic have the same width. Only European-specific (and some ambiguous) characters have various proportional widths.

European characters in BIZ UDGothic have a width that is exactly half the width of Japanese characters like those in MS Gothic. However, its bold variant is too light compared to Cascadia Code.

**Comment by tats-u** [comment]
| Fonts | Japanese hiragana/katakana | Other full-width Japanese | European |
| -- | -- | --- | -- |
| MS Gothic / BIZ UDGothic | Monospace (1) | Monospace (1) | Monospace (0.5) |
| MS PGothic / BIZ UDPGothic | Proportional | Monospace (1) | Proportional |
| MS UI Gothic / Yu Gothic UI | Proportional (Condensed) | Monospace (1) | Proportional |
| Yu Gothic / Noto Sans JP | Monospace (1)[^palt] | Monospace (1) | Proportional |
| Meiryo | Monospace (~1.05) | Monospace (~1.05) | Proportional |

[^palt]: except when you apply some OpenType features like `palt`, `pkna`, `pwid`
