### ISSUE TITLE
`clear` leaves the first line currently displayed over

### ISSUE THREAD

**Issue by leduyquang753** [microsoft/terminal#13529]
### Windows terminal version

1.13.11432.0

### Windows build number

10.0.22000.795

### Other software

None.

### Steps to reproduce

1. Open PowerShell or Command prompt.
2. Make the text span more than one screen.
3. Run `clear` or `cls`.
4. Use the mouse wheel to scroll up.

### Expected behavior

The scroll isn't possible as there is no longer any text above the currently displayed screen section.

### Actual behavior

There is one line left over that is shown when scrolling up, which is the first line in the currently displayed screen section before the `clear` command is executed. When typing the scrolling snaps back to the line with the prompt, hiding the leftover line.

![image](https://user-images.githubusercontent.com/26449060/179484502-01f67599-e9bd-4291-89bb-3979777c9abd.png)

**Comment by zadjii-msft** [comment]
I fully suspect that this is the same issue we fixed in #13324, which we were originally tracking in /dup #5770
