### ISSUE TITLE
Warning when pasting multiple lines could offer to merge text into a single line

### ISSUE THREAD

**Issue by divega** [microsoft/terminal#13537]
I usually get this warning because I need to copy a full path of a file that has been broken down into multiple lines on the terminal into a new command. 

When I get the warning, I know that the path of the file won't work as is, and I need to cancel the paste action and fix the text using another program like VS code or notepad before I can paste it back into the terminal. 

# Proposed solution

I think it would be a great time saver for users like me if the terminal could do this fixup (remove all the line breaks) itself as an option alongside `Paste anyway`.

**Comment by carlos-zamora** [comment]
Hi @divega. Thank you for the request.

> I need to copy a full path of a file that has been broken down into multiple lines on the terminal

This sounds like an issue with a wrapping bug in our terminal (see https://github.com/microsoft/terminal/issues/6901#issuecomment-1307781312). It doesn't feel right to add features to work around bugs in our own project. We'd rather fix the bug. Thus, we'll be closing this feature request.
