### ISSUE TITLE
Mark Mode should preempt key bindings, and work with anything that causes scrolling...

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#13533]
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19042.0

### Steps to reproduce

I know the mark mode keyboard selection is still very early days. I just wanted to make sure the expected behaviors are all covered, and I didn't see this called out.

Any hotkey that pre-exists the mark mode currently interfere with selection. That is, currently:

- Mark mode seems to only works with the default windows text navigation keys: the arrows, PgUp/PgDn, home/end.
- **Selecting** requires turning on mark mode and then holding shift while pressing those keys.

If the user has an "Action" configured for `Ctrl+Shift+Home` or `Ctrl+Shift+PgUp` or whatever, that action will trigger **instead of** the selection.

Additionally, nothing else that scrolls the buffer causes the mark to move or select:

- Scrolling with the mouse
- Scrolling with scrollToMark
- Scrolling via the command palette (Ctrl+Shift+P)

On top of that, we can't **usefully** turn on mark mode _after_ scrolling, because it always appears at the bottom.

### Expected Behavior

Mark mode should probably be called "selection" mode, to disambiguate with the new "marks" ...

Mark mode should disregard actions that consume Arrows/PgUp/PgDn/Home/End  -- or possibly, should ignore all actions except selection-specific actions or Esc to cancel, changing all the hotkeys like a `vi` mode does.

The "mark" should follow the scroll buffer if the buffer is scrolled via other actions. Ideally, it should select when that happens with SHIFT pressed. 

The mark should always appear _within the visible buffer_ when it's invoked, **not** only at the bottom/prompt.

### Actual Behavior

The mark only ever appears at the prompt, and can only be used if you haven't configured actions over the default text selection keys.

**Comment by zadjii-msft** [comment]
There's a lot to unpack here, I'll make sure this is at the top of the discussion order this afternoon. Thanks!

**Comment by zadjii-msft** [comment]
quick discussion notes:

* meh, I think we're more attached to calling this "Mark Mode" than we are to calling the scrollbar marks "marks".
* yes - we think we have an issue for this. This gets more complicated with things like nextMatch/prevMatch, find in general. We'll noodle on this one. 
* maybe not? 
* for sure


over to @carlos-zamora

**Comment by carlos-zamora** [comment]
> Mark mode should probably be called "selection" mode, to disambiguate with the new "marks" ...

* For now, scrollbar marks are in experimental so we'll rename them as a part of the polishing process. Added a comment in #11000 to track this

> Mark mode should disregard actions that consume Arrows/PgUp/PgDn/Home/End -- or possibly, should ignore all actions except selection-specific actions or Esc to cancel, changing all the hotkeys like a vi mode does.

Fixed by #13659 

> The mark should always appear within the visible buffer when it's invoked, not only at the bottom/prompt.

Fixed by #13405. I need to backport that change still.

**Comment by carlocardella** [comment]
> quick discussion notes:
> 
> > Mark mode should probably be called "selection" mode, to disambiguate with the new "marks" ...
> 
> * meh, I think we're more attached to calling this "Mark Mode" than we are to calling the scrollbar marks "marks".

Uhm... seems counterintuitive to me... "mark mode" allows to select some text, make a selection. Also, most (all) tools/editors I am aware of call this "selection", why do we want to call it "mark"?

**Comment by zadjii-msft** [comment]
> why do we want to call it "mark"?

Kinda just because that's what the vintage console called it:
![image](https://user-images.githubusercontent.com/18356694/182599207-0bd76204-566f-4625-8803-38919ade7e35.png)

We've used "mark mode" internally to refer to "the editing mode in which the keyboard input modifies the selection region" for _years_.


That being said, "Selection mode" is pretty obvious what it's doing. And, calling it "selection mode" would immediately disambiguate it from the implementation in conhost. Idk, back to the discussion board it goes.
