### ISSUE TITLE
weird window padding bug

### ISSUE THREAD

**Issue by seanmamasde** [microsoft/terminal#13545]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22622.290

### Other Software

oh-my-posh

### Steps to reproduce

apply one of those themes whose got segments aligned to the right and you'll see

### Expected Behavior

the right side of the terminal window should have the same amount of padding as the left hand side. Not only appears in oh-my-posh, can also reproduce in command prompt (simply type in lots of chars)
<img width="747" alt="image" src="https://user-images.githubusercontent.com/85484530/179903611-59fdbba4-422c-4456-84e3-dc91c90e9d6a.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/85484530/179903636-701fabf5-82a2-4950-9f82-fd5eae494ef0.png">

### Actual Behavior

not having same amount of padding (set to 8 in the settings)

**Comment by 237dmitry** [comment]
[#13446](https://github.com/microsoft/terminal/issues/13446#issue-1296698581)
