### ISSUE TITLE
After tab close, tabs width does not restore automatically unless hovered by mouse

### ISSUE THREAD

**Issue by Avi0** [microsoft/terminal#13546]
### Windows Terminal version

1.14.1861.0

### Windows build number

10.0.22000.795

### Steps to reproduce

1. Set tab width mode to equal.
2. Open a number of tabs so that tab width starts to shrink.
3. Start closing tabs without using a mouse, for example, with Ctrl+D or by typing "exit". Close tabs so that only a few tabs left.

### Expected Behavior

Tab width restores to the default.

### Actual Behavior

Tabs stay small. If you hover a mouse over the tab bar, tab width restores.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9822 for more discussion.

/dup #9822
