### ISSUE TITLE
Select multiple panes under a tab to support simultaneous input

### ISSUE THREAD

**Issue by aliuq** [microsoft/terminal#13550]
# Description of the new feature/enhancement

Hi

Simultaneous input can help us reduce input time, it likes select multiple cursors in vscode, for myself, I used ssh connects remote server. sometimes I want to excute a little same commands, I have to retyping these each one in multple panes

![image](https://user-images.githubusercontent.com/11707934/180048684-43571e6b-c308-4255-8ae0-c3e22ab42852.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2634 for more discussion.

/dup #2634
