### ISSUE TITLE
[1.16] Default theme updates

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13554]
From discussion with @cinnamon-msft et. al.

* [ ] Dark theme by default (was `system`)
* [ ] `tab.background: terminalBackground` 
* [ ] Change the tab row colors back to what they were pre-Controlsv2
  - This point I might be mis-remembering. I think the crux was "make the colors better", and we had freedom to do whatever we wanted. 
  - The current dark tabRow.background is basically the same as the default scheme BG, and maybe that's good, maybe that's bad. 
* [ ] `tabRow.unfocusedBackground` set to something sensible in the default themes as well.

_The 🌶️ rejected ides:_
* Default to mica on
  * Rejected cause this would disable vintage opacity
  * Rejected cause our Mica story isn't fleshed out yet
  * Rejected cause dark tabs in light OS theme with Mica titlebars has pretty low contrast overall.
* ... with a non-acrylic, transparent control, so that you'd get the mica termcontrol body.
  * see all the above.

**Comment by AndromedaMelody** [comment]
Immersive experience is the  best. I hope Windows Terminal can change color scheme when theme changed.
For example, like this feature in VS Code.
![Screenshot 2022-07-24 112923](https://user-images.githubusercontent.com/57533055/180630959-d8083d51-3b28-43da-bedb-74d20116fec8.png)

Thanks a lot.

**Comment by zadjii-msft** [comment]
_🏗️ Work in progress 🏗️_ 

<table>

<tr>
<td>origin</td><td>screenshot</td><td>tab.background</td><td>tabRow.background</td><td>tabRow.unfocusedBackground</td>
</tr>

<tr>
<td>Edge Dark</td>
<td>

![image](https://user-images.githubusercontent.com/18356694/183107109-d181736c-0643-4c60-8288-d465737f392a.png)
![image](https://user-images.githubusercontent.com/18356694/183107151-1f354592-951f-443b-bceb-e9d54cdeeb40.png)

</td>
<td>#3b3b3b</td>
<td>#202020</td>
<td>#202020</td>

</tr>

<tr>
<td>Terminal (Controlsv1)</td>
<td>

</td>
<td>#</td>
<td>#</td>
<td>#</td>

</tr>

<tr>
<td>Terminal (Controlsv2)</td>
<td>

</td>
<td>#</td>
<td>#</td>
<td>#</td>

</tr>
</table>
