### ISSUE TITLE
snapping cmd.exe window from full screen to right half of screen results in view error

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1355]
>run cmd.exe
>win + up arrow
>win + right arrow
>
>expected: console snapped to right half of screen, ready to go
>
>actual: console window appears blank.

_Migrated from MSFT:22289519_

**Comment by sircompo** [comment]
In case it helps identify the root cause, if you Ctrl-MouseWheelUp/Down in the blank window to adjust the zoom, it resizes the window to a 1px vertical line in the middle of the screen with the window controls + icon oddly rendered at the top.

**Comment by zadjii-msft** [comment]
This looks like it doesn't repro for conhost any more. Either this got solved in Windows 11, or one of the more recent fullscreen fixes.
