### ISSUE TITLE
Execute wt.exe without response or error

### ISSUE THREAD

**Issue by JoeABCDEF** [microsoft/terminal#13557]
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Execute wt.exe

### Expected Behavior

Can open the application normally

### Actual Behavior

Execute wt.exe without response or error.Uninstalling and reinstalling doesn't work either

**Comment by zadjii-msft** [comment]
Are you running it from the Start Menu, the Run Dialog, or some other commandline shell/? 

Can you share the output of `where wt` from a Command Prompt? I just want to first sanity check that it's on the PATH. 

Is the "app execution alias" enabled (in the settings app)?

**Comment by JoeABCDEF** [comment]
@zadjii-msft  
* where wt
![image](https://user-images.githubusercontent.com/39638510/180241091-9acbb8bc-e8b1-4441-a2f5-8fc4c1db0bf8.png)
***
* It's okay to start
![image](https://user-images.githubusercontent.com/39638510/180242040-37475534-cac7-4fc2-a482-cc5d417d632b.png)

**Comment by zadjii-msft** [comment]
Not `where path`, but `where wt`. 

It should look like:
![image](https://user-images.githubusercontent.com/18356694/180245218-77696f8b-4868-43a9-a00d-01f3047d0961.png)

`where` should search the path to see where the exe is on the current path. If nothing shows up, then `wt` isn't on the path _anywhere_.

**Comment by JoeABCDEF** [comment]
@zadjii-msft I have some in this path, but there is no return when executing where wt, how to deal with this

**Comment by zadjii-msft** [comment]
Is `C:\Users\{username}\AppData\Local\Microsoft\WindowsApps` in your path? If it isn't, then add it back. (and restart your commandline shells).

If it is, and this still doesn't work, then make sure the app execution alias is enabled in the settings app. [This post](https://stackoverflow.com/questions/58296925/what-is-zero-byte-executable-files-in-windows/66539884#66539884) should help you find where that setting is.

**Comment by JoeABCDEF** [comment]
@zadjii-msft  Thanks, this still doesn't work for me, but I made a shortcut to the address under this path ( `C:\Users\{username}\AppData\Local\Microsoft\WindowsApps\wt.exe`) and put it in the start menu

**Comment by zadjii-msft** [comment]
Alrighty well, sounds like you got this figured out. Otherwise, someone else was seeing basically the same thing in #13590, so I'm just gonna link these two up for future people searching.

/dup #13590

**Comment by Bilibili-toast** [comment]
Hello, I also have the same problem. There is wt.exe on my path, but it does not run when I double-click it. When I double-click it, the windows terminal icon flashes across the taskbar and then disappears. It will only be displayed when you right-click and shift to open the command window here, and even after it is opened, you cannot create a new page.
