### ISSUE TITLE
App installer failed to install package dependencies. Ask the developer for package

### ISSUE THREAD

**Issue by GauravSahare1993** [microsoft/terminal#13558]
### Windows Terminal version

1.14.1862.0

### Windows build number

10.0.22000.318.0

### Steps to reproduce

App installer failed to install package dependencies. Ask the developer for package, 1st it requires installation of "Microsoft.UI.Xaml.2.7" , after successful installation of this Xaml, still shows package dependencies error.
![Screenshot (4)](https://user-images.githubusercontent.com/109745579/180238864-15aed993-4252-4bea-9ddc-fb1794b18465.png)

### Expected Behavior

No issue should appear during installation.

### Actual Behavior

Still I am facing this error.

**Comment by zadjii-msft** [comment]
I think the [Microsoft.WindowsTerminal_Win10_1.14.1861.0_8wekyb3d8bbwe.msixbundle](https://github.com/microsoft/terminal/releases/download/v1.14.1861.0/Microsoft.WindowsTerminal_Win10_1.14.1861.0_8wekyb3d8bbwe.msixbundle) bundle might work better for you. (note 1.14.186**1**, not 1862)That's got some extra dependencies bundled in.


From the release notes:

> ### Why are there so many packages? How do I choose?
> This version of Windows Terminal is distributed in two bundles, one of which works on Windows 10-11 and the other of
> which only works on Windows 11. The Windows 11 version is much smaller because we no longer need to work around a
> platform issue related to our dependencies.
> 
> If you intend on using Terminal as an unpackaged application--that is, extracting the `msix` file--we recommend that
> you use the `Win10` bundle. You will need the [Visual C++ runtime redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist).
> 
> In addition, if you install the _packaged_ version on either Windows 10 or Windows 11, it now depends on [the Visual C++ Universal Runtime Package](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge?msclkid=3e1dd82aac8b11ec8f9dbd86d5979ca8#how-to-install-and-update-desktop-framework-packages).
> 
> Despite these distributions having different version numbers, they are built from the same code and there is no
> functional difference between them.
> 
> If you install the Windows 10 verison on Windows 11, it will probably automatically upgrade itself to the Windows 11
> version. It turns out that it is impossible to have two bundles with _the same version number_, so it has to be this
> way.

**Comment by GauravSahare1993** [comment]
My thanks for reply, but problem was still present, I investigated more and now I found that this problem exactly happens due to missing package **"VCLibs.x64.14.00.Desktop"** and **"Microsoft.UI.Xaml.2.7"** , so I installed both, then I installed the version of terminal app you provided, finally I am no longer facing this issue.
Kindly update this information if someone facing this problem.

**Comment by zadjii-msft** [comment]
Thanks for following up!

**Comment by mhadinj** [comment]
Hi

for ms Ui Xaml
run powershell as admin
`
Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx -OutFile $env:TEMP\Microsoft.UI.Xaml.2.8.x64.appx
Add-AppxPackage $env:TEMP\Microsoft.UI.Xaml.2.8.x64.appx
`
