### ISSUE TITLE
[ARM64] App crash on changing settings 

### ISSUE THREAD

**Issue by Indresh10** [microsoft/terminal#13559]

**Comment by zadjii-msft** [comment]
Sorry, you gotta provide some information. Version numbers, what setting you're changing, anything.

**Comment by DHowett** [comment]
Actually, I just hit this on 1.16, ARM64, and all I did was press Save in the settings UI.

**Comment by zadjii-msft** [comment]
Dustin I'm assigning you cause you're the only one with ARM hardware

**Comment by zadjii-msft** [comment]
Closing this since Dustin never saw it again, and OP left this blank.
