### ISSUE TITLE
Store version of wt updated from 1.13 to 1.15

### ISSUE THREAD

**Issue by vbyrd** [microsoft/terminal#13566]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22621.0

### Other Software

PowerShell 7 Preview

### Steps to reproduce

Went to store and clicked "Update All". It installed a new version of Windows Terminal on 7/20. I checked the about dialog and it showed 1.15.2002.0. My previously installed version was 1.13. I thought it was odd that it skipped over 1.14 as the next non-preview build.

### Expected Behavior

I thought I'd be bumped up to 1.14. 
![image](https://user-images.githubusercontent.com/619450/180371092-c3fcfba3-d15f-4542-a660-4f8780baae12.png)

### Actual Behavior

It updated straight to Windows Terminal 1.15.2002.0 without any mention of being a preview build or having installed a preview build prior. I am running the Beta channel of the windows insider program if that plays into this at all.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎16/‎2022
OS build	22622.436
Experience	Windows Feature Experience Pack 1000.22632.1000.0

**Comment by zadjii-msft** [comment]
FWIW, this is expected, although a little unusual compared to most releases. 

@cinnamon-msft Do we have a good blog post somewhere explaining what is happening here? If not, we should at least type up a release notes or something we can point folks at.

**Comment by cinnamon-msft** [comment]
We released 1.15 to the Windows Inside Program Beta channel in order to enable Windows Terminal as the default terminal, by default. Seeing as 1.14 was already released to Stable without the bits needed to make Terminal the default automatically, we needed to ship out 1.15 instead. Hope this helps clear up any confusion. :)
