### ISSUE TITLE
`mode` command no longer resizes the window.

### ISSUE THREAD

**Issue by KcrPL** [microsoft/terminal#13564]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22621.436

### Steps to reproduce

Type in `mode 128,37`.

### Expected Behavior

The window size should change like it did in native `cmd`.

### Actual Behavior

Nothing happens, the window size stays the same.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5094 for more discussion.

/dup #5094
