### ISSUE TITLE
When re-arranging tabs nvidia's shadowplay keep asking me to enable recording of desktop

### ISSUE THREAD

**Issue by RexTheCapt** [microsoft/terminal#13574]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Other Software

NVIDIA GeForce Experience : 3.25.1.27
GeForce Game Ready Driver : 516.59

### Steps to reproduce

Launch Windows Terminal.
Open an new tab.
Drag the new tab to slot 1.
Profit (only happens sometimes).

### Expected Behavior

To not touch NVIDIA's stuff and move the tab as normal.

### Actual Behavior

NVIDIA asks me to enable desktop recording and still able to move the tab like nothing happened. Have to manually close the NVIDIA popup.

**Comment by DHowett** [comment]
I'm sorry, we cannot control what NVIDIA's software does when you are dragging and dropping an object. The UI framework we use implements drag/drop using the standard Windows API for drag/drop. It may be worth bringing this up with NVIDIA.

**Comment by zadjii-msft** [comment]
I know this is largely a different issue than #10956, but I'm gonna de-duplicate them because ultimately, the answer is the same. 

/dup #10956
