### ISSUE TITLE
After minimizing, unable to restore window with Alt-Tab 

### ISSUE THREAD

**Issue by vertigo220** [microsoft/terminal#13589]
### Windows Terminal version

1.14.1962.0

### Windows build number

Version 21H2 (OS Build 19044.1826)

### Steps to reproduce

Open and minimize terminal
Press Alt+Tab to switch back to it
Previous app loses focus, but Terminal doesn't show and remains minimized

NB: When this happened, I tested it multiple times, and it happened every time. I then restored the window and Alt+Tab worked normally, then minimized it and it didn't. _However_, now it's working fine, so I'm not sure if it was some weird Windows issue (W10 continues, to this day, to be _extremely_ broken WRT focus issues, constantly leaving windows I click on _behind_ other windows and requiring me to click on the foreground, unfocused window then click back in the other one to force it to come to the front). Still, I'm reporting just in case it is actually an issue, and maybe somebody else can reproduce it or will have it happen to them to confirm.

### Actual Behavior

See above

**Comment by babico** [comment]
I have same issue I tried change preview to stable version but it didn't change anything, still happening this bug.

**Comment by zadjii-msft** [comment]
Does this only happen when running elevated (as Administrator)? this looks similar to #13592 which was just filed. I can't repro this here on Windows 11, but maybe the focus/foreground work attached to #2988 regressed this in Windows 10 😨

**Comment by vertigo220** [comment]
Sorry, I forgot to mention this in my OP, but it was NOT running as admin at the time. And, if it matters, I had about four or five tabs open, with a mix of PS and cmd.

**Comment by zadjii-msft** [comment]
Alright, I'm deduping here, this will be the master tracking thread. 

* Doesn't seem limited to Windows 10 (at least, I can repro this on win11 in an elevated window _sometimes_)
* Only occurs when minimizing to the taskbar, using the taskbar icon itself.
* Doesn't seem limited to elevated windows (but seems more frequent)
* If you're stuck in this state, you should be able to hover the icon in the taskbar till you get a preview of the window, and then you can right click -> "Restore" the window that way

There's also MSFT:40530963 tracking internally.

**Comment by vertigo220** [comment]
> * Only occurs when minimizing to the taskbar, using the taskbar icon itself.

Ah, and there it is. Kinda surprised I didn't think to try this, but yeah, if I minimize this way, it happens every time, with a non-admin window. Doesn't get stuck though, just have to click the taskbar button again.

**Comment by lhecker** [comment]
@zadjii-msft I narrowed it down to 6b936d9a74a5d677387f3edc9a68e6b33d566606. Commenting out this line fixes the issue:
https://github.com/microsoft/terminal/blob/feabe41a08604345a1eeb4b38fd1c99b811f8ecd/src/cascadia/TerminalControl/ControlCore.cpp#L1929

I tried various ways to debug this further and fix the issue, but failed at it so far. 😥

**Comment by zadjii** [comment]
I wonder if it's because that results in a xproc call (sending a message to OpenConsole.exe via a pipe) on the main thread. I wonder if user32 doesn't like us doing that... A resume_background right before that would be an interesting experiment

**Comment by gradyalexis** [comment]
I have the same issue. when run as Administrator, is not restored if it was minimized

**Comment by Shdwfx** [comment]
i can always reproduce if i double click terminal icon on taskbar when its minimized. (in administrator mode)

**Comment by zadjii-msft** [comment]
Notes (_ongoing_)

* I was able to get an unelevated dev build of the Terminal into this state, on Windows 11.
* In that state, we only get a few messages when alt-tabbing to the window:
  - `0x7f`
  - `WM_WINDOWPOSCHANGING`
    - the flags are: `0x13` = `SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOMOVE`
    - `hwndInsertAfter` is not a special value.
  - `WM_WINDOWPOSCHANGED`
  - and that's it. There's nothing else, no ShowWindow or anything...
* We don't even get into `ControlCore::_focusChanged` even remotely. Checks out, the window never gets shown so no duh it's not getting focused.
* The current window styles are... `34CF0000` -> `WS_VISIBLE | WS_MINIMIZE` _is_ set...
* The ConPty HWND seems to be owned correctly, and `WS_VISIBLE | WS_MINIMIZE` are both set
* ....

**Comment by zadjii-msft** [comment]
In the 10 VM, the taskbar icon is not immediately highlighted when launching the Terminal. As if it doesn't know that the terminal is in the FG. That would explain the initial SwitchToWindow

![gh-13589-000](https://user-images.githubusercontent.com/18356694/181360423-7716a04d-6e37-4144-9ec0-1d813e0c443e.gif)


But then after the "restore", the terminal is indicated as being active. Hmm.

**Comment by zadjii-msft** [comment]
#13158

```c++
    // BODGY
    //
    // GH#13158 - At least temporarily, only allow the PTY to HIDE the terminal
    // window. There seem to be many issues with this so far, and the quickest
    // route to mitigate them seems to be limiting the interaction here to
    // allowing ConPTY to minimize the terminal only. This will still allow
    // applications to hide the Terminal via GetConsoleWindow(), but should
    // broadly prevent any other impact of this feature.
    //
    // Should we need to restore this functionality in the future, we should
    // only do so with great caution.
```

Oh hey look, that came back to bite 😠

**Comment by YueLu0116** [comment]
Same problem here, windows 10 (20H2), elevated terminal.
This afternoon, every time after I built a project in vs2019, the terminal suddenly disappear.

**Comment by satyapramodh** [comment]
@zadjii-msft  **If you're stuck in this state, you should be able to hover the icon in the taskbar till you get a preview of the window, and then you can right click -> "Restore" the window that way**

- this doesnt work for me on windows 11

**Comment by vertigo220** [comment]
@satyapramodh Your screenshot only shows you hovering over the thumbnail. Did you actually right-click _on the thumbnail_ and select restore from the menu that pops up? Granted, I'm on W10, but that _does_ work for me and others, and it looks like zadjii is on Win11, like you, so it seems it should work for you as well.

**Comment by onepushupman** [comment]
Ok - restoring the window does actually work, but is quite annoying. Shouldn't have updated the terminal at all, the old version was working quite fine. 😅

**Comment by rpodric** [comment]
Just to chime in that it happens on 22H2, too, though making it happen is tricky. It just seems to happen when you don't want it to.

I'll have to try the "right-click on the thumbnail and select restore" trick, which may be the only thing I haven't tried to get access to it once it's happened.

**Comment by pimpace** [comment]
@zadjii-msft said:
**If you're stuck in this state, you should be able to hover the icon in the taskbar till you get a preview of the window, and then you can right click -> "Restore" the window that way**


No need to wait for preview of the window, for this "hover thing", simply shift-rightclick on the Terminal taskbar button and
click restore. A little bit simpler. :)

**Comment by vertigo220** [comment]
Those "handy" links are 404. They're missing the ".0" on the end.

**Comment by pheu** [comment]
> Those "handy" links are 404. They're missing the ".0" on the end.

Yup, both links are very "handy". One misses .0 and another points to the store where they still keep older buggy version (200). 😁

**Comment by rpodric** [comment]
The Store just got 1.14.2282.0.

**Comment by onepushupman** [comment]
> The Store just got 1.14.2282.0.

thanks for letting us know

**Comment by badjuice** [comment]
> @zadjii-msft said: **If you're stuck in this state, you should be able to hover the icon in the taskbar till you get a preview of the window, and then you can right click -> "Restore" the window that way**
> 
> No need to wait for preview of the window, for this "hover thing", simply shift-rightclick on the Terminal taskbar button and click restore. A little bit simpler. :)

This is not an option on Windows 10 :(

**Comment by Bartizan** [comment]
> > @zadjii-msft said: **If you're stuck in this state, you should be able to hover the icon in the taskbar till you get a preview of the window, and then you can right click -> "Restore" the window that way**
> > No need to wait for preview of the window, for this "hover thing", simply shift-rightclick on the Terminal taskbar button and click restore. A little bit simpler. :)
> 
> This is not an option on Windows 10 :(

it works for Win10, also see the same workaround here  https://github.com/microsoft/terminal/issues/13592#issue-1316837614
But now it seems to  work as it should at least for me.
