### ISSUE TITLE
Add close pane to the tab context menu (when there are multiple panes)

### ISSUE THREAD

**Issue by vertigo220** [microsoft/terminal#13580]
# Description of the new feature/enhancement

Once a tab is split, there's no way to return it to normal, meaning either having to continue working in half the space or starting a new tab and losing everything from the current one. It should allow for either closing one half or splitting them into two tabs.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You mean like the [`closePane` action](https://docs.microsoft.com/en-us/windows/terminal/panes#closing-a-pane)/?  Or maybe [moving panes to their own tabs](https://docs.microsoft.com/en-us/windows/terminal/panes#moving-panes)? Or heck even [zooming a pane](https://docs.microsoft.com/en-us/windows/terminal/panes#zooming-a-pane), to make it take the full size of the tab again?

**Comment by vertigo220** [comment]
I guess all three options would be nice, though I was mainly talking about the first. I didn't realize it was even an option since I didn't think to check the actions, and it's something I feel should be available via a menu and not just a shortcut, both to make it more obvious that it _is_ an option, and to make it easier to do without having to remember the shortcut, especially since it's likely not something most would use very often.

I see three ways of handling this. The cleanest, most space-efficient, and probably most obvious would be to add the actions to the tab's right-click menu, e.g. "Close active pane," "Move active pane to new tab," "Make active pane full-size" (zoom it), and "Close all non-active panes" (though this one could be dangerous and would probably benefit from a confirmation dialog). Then whichever pane is active when right-clicking the tab and selecting one of the options would be the one acted on.

The second possibility would be to add a small title bar to each pane that could be right-clicked, which would bring up a menu with the previous options, minus the word active or replacing it with "other" in the case of closing the other panes, of course.

The third option would be to add a few small buttons at the top-right of each pane, an x to close it, a square to maximize it or double square to restore it, and something like a square with an arrow for separating it out into a new tab.

**Comment by zadjii-msft** [comment]
FWIW, the general pattern the Terminal uses is that all the actions for the Terminal are in the Command Palette. We don't have a whole lot of UI space, so the command palette is a great way for us to have LOTS of actions while also making sure most menus aren't excessively cluttered. That being said

* Sure, okay, we can use this to track "Add close pane to the tab context menu (when there are multiple panes)"
* see: #4717
* This will probably also fit under the same feature set as above

**Comment by rismoney** [comment]
how is this on the backlog?  How do people even use this half-baked capability?

**Comment by zadjii-msft** [comment]
@rismoney Probably because most people just close panes with the keyboard (<kbd>ctrl+shift+w</kbd>), or the Command Palette <kbd>ctrl+shift+p</kbd>. If you're passionate about the feature, I can try and help provide a roadmap of where the code changes would need to go.

**Comment by rismoney** [comment]
keyboard shortcuts ftw!

**Comment by Smeyer025** [comment]
> @rismoney Probably because most people just close panes with the keyboard (ctrl+shift+w), or the Command Palette ctrl+shift+p. If you're passionate about the feature, I can try and help provide a roadmap of where the code changes would need to go.

I don't know if the offer is still on the table (or open to outside help), but I would love to take a crack at this and a roadmap would be extremely helpful!

**Comment by joadoumie** [comment]
![Image](https://user-images.githubusercontent.com/98557455/232645653-d1a09c90-5c90-4c59-ae40-52860ec73dee.gif)

I decided to take a crack at this one and I think I have the functionality working. What should we use for the icon in the context menu?
