### ISSUE TITLE
Experimental "marks" settings are documented as global, but are per-profile

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#13583]
#13414 added `experimental.autoMarkPrompts` and `experimental.showMarksOnScrollbar` to the `Globals` section of [_doc/cascadia/profiles.schema.json_](https://github.com/microsoft/terminal/blob/main/doc/cascadia/profiles.schema.json) (and they were also described as such in the [relevant release notes](https://github.com/microsoft/terminal/releases/tag/v1.15.1862.0)), but these settings are per-profile (as you'd expect such settings to be, and as documented in #11000).

Confirmed both because that's where they actually _work_ in the profile, and by [their presence in the `MTSM_PROFILE_SETTINGS` macro](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/MTSMSettings.h#L84-L85).

At least in VS Code's case, there's also an issue that even with the `$schema` pointing at [the correct JSON schema](https://raw.githubusercontent.com/microsoft/terminal/v1.15.2002.0/doc/cascadia/profiles.schema.json), validation does not like the new `scrollToMark` action, or in fact any of the new marks, but I suspect that is more of a VSCode JSON editor issue, since it's also rejecting `intenseTextStyle` as a profile setting. >_<

**Comment by TBBle** [comment]
Also, [the current JSON schema in main is probably invalid JSON](https://github.com/microsoft/terminal/pull/13469#discussion_r928138496), but that doesn't seem worth a separate bug report since fixing this will have to touch that file anyway.

**Comment by zadjii-msft** [comment]
Huh. Thanks for the heads up!
