### ISSUE TITLE
Windows terminal doesn't start from command line, but will start if executed from Start menu

### ISSUE THREAD

**Issue by eblis** [microsoft/terminal#13590]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044 Build 19044

### Steps to reproduce

Trying to start Windows terminal from a command prompt results in an error.

```
Faulting application name: WindowsTerminal.exe, version: 1.14.2207.15002, time stamp: 0x62d1f0dc
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x77e8
Faulting application start time: 0x01d89ff96485caf2
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.14.1962.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: bb86db60-2ffc-4156-a74c-a1c4b9e1a6ec
Faulting package full name: 
Faulting package-relative application ID: 
```

But if I start the application from the start menu then Windows Terminal starts successfully.
I've read #1364 a bit and tried some of the ideas there, installed PowerShell 7, forced terminal to use my integrated Intel display driver but none of them worked. I'm not sure it's the same issue because in that issue people couldn't get terminal to work in any scenario, but for me it works if I start from start menu.

Not sure if relevant but I don't have `wt.exe` and `WindowsTerminal.exe` in my path.
If I browse to the folder with windows terminal and try to run the command they do nothing, even `wt -h` or `wt --version` don't work.

I've installed Windows Terminal from the GitHub releases, but then updated it via Windows Update.

Also, my Windows Terminal icon is broken and I can't figure out how to fix it.
![image](https://user-images.githubusercontent.com/540188/180724259-8448eee5-4cea-418c-97d0-596a460169e9.png)

### Expected Behavior

Windows terminal should be able to start from a command prompt as well.

### Actual Behavior

Windows terminal crashes if started from a command prompt, but works if started from Start menu.

**Comment by zadjii-msft** [comment]
> Not sure if relevant but I don't have `wt.exe` and `WindowsTerminal.exe` in my path.
> If I browse to the folder with windows terminal and try to run the command they do nothing, even `wt -h` or `wt --version` don't work.

Which directory specifically/? The `WindowsApps` directory is special and isn't supposed to be accessed directly by the user. The App Execution Alias for Terminal, `wt.exe`, is a special type of link that the OS uses to do some extra validation before starting the Terminal. The OS won't let you run the app directly out of `WindowsApps`.

**Comment by eblis** [comment]
This is the folder: `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.14.1861.0_x64__8wekyb3d8bbwe` (it used to be `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.14.1962.0_x64__8wekyb3d8bbwe` but I uninstalled Windows Terminal and then installed the latest version available in GitHub releases again)
But if I type `wt` in a normal command prompt it's not recognized, there's nothing in the `%PATH%` variable pointing to Windows Terminal. How is it finding the executable to run in that case ?

**Comment by zadjii-msft** [comment]
You need to enable the App Execution Alias for the Terminal in the Settings app

![image](https://user-images.githubusercontent.com/18356694/180803232-3a4904a2-016a-4377-9ce9-9da40b5d76b7.png)


That'll place a `wt.exe` "execution alias" onto the path, which will effectively do the same thing as launching the app from the Start Menu

**Comment by eblis** [comment]
![image](https://user-images.githubusercontent.com/540188/180808615-aeace917-47b5-43b5-81b2-8927b567a785.png)

**Comment by zadjii-msft** [comment]
After enabling the execution alias, did you start a fresh Command Prompt window/? Is `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\` on your `%PATH%`? (I'm suspecting the latter isn't true, if `winget` wasn't there either)

**Comment by eblis** [comment]
Thanks for the input.
I was just searching online for this issue and found [this](https://superuser.com/a/1569403).
The `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\` entry was not in my `PATH` variable.

I added it and now everything is working (including winget).

That's why I added winget in the screenshot as well, none of the aliases were working.

Thanks for your help

**Comment by zadjii-msft** [comment]
No problem, glad we could get it sorted out 😄
