### ISSUE TITLE
The window of WindowsTerminal v. 1.14.x, 1.15, run as Admin, is not restored if it was minimized 

### ISSUE THREAD

**Issue by Bartizan** [microsoft/terminal#13592]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1826

### Steps to reproduce

- run Windows Terminal (v.1.14, v.1.15) as administrator;
- minimize the window;
- try to restore the Window Terminal again (clicking on its button in taskbar, using Window manager (Alt+Tab));

There are _workarounds_ to bring the window back. 
1) @gabbymouth suggests to click Shift+Right mouse button on WT button in taskbar and then select the Restore option in small menu. 
2) If WT were configured to attach the new WT to recent one, then run the new WT as Admin, it would be restored again.

First, I faced the problem on Preview WT v1.15, it was very annoying so I downgraded to v1.13 and it worked as I think until it has automatically been upgraded to v1.14. 

### Expected Behavior

The window of WindowsTerminal must to be restored/open

### Actual Behavior

The window of WindowsTerminal stays minimized.

**Comment by Trard** [comment]
same

**Comment by Shdwfx** [comment]
same. i can reproduce this issue if i double-click terminal icon on taskbar.

**Comment by zadjii-msft** [comment]
I tentatively suspect that this is a duplicate of #13589. I'm gonna wait for confirmation in that thread that they're seeing this when elevated before deduping. (although, supposedly if it happens regardless of elevated or not, then I guess that issue's just a superset of this issue...)

**Comment by gabbymouth** [comment]
I have the same issue. Another workaround is to move the mouse cursor over the taskbar icon, hold down the shift key and right-click on the taskbar icon and you should get a small menu with Restore as an option. Click on Restore and it will pop up where it was.

**Comment by JergenRoss** [comment]
same

**Comment by lupinitylabs** [comment]
> same, when you can't restore window while command is running with run as admin like `dism /online` , `winget` etc. and command is done then you can restore window. weird bug.

Running `dism /online` or any other app as admin does not change anything for me. The window still cannot be restored afterwards.

**Comment by zadjii-msft** [comment]
Yep, that's right. This is a known bug unrelated to what's running in the terminal. The fix for https://github.com/microsoft/terminal/issues/13589 is just waiting to be serviced at the moment.
