### ISSUE TITLE
Keycode wrong for MSKLC layout

### ISSUE THREAD

**Issue by rolandschulz** [microsoft/terminal#13595]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.0

### Other Software

Ubuntu 20.04.4 LTS
Microsoft Keyboard Layout Creator (MSKLC) Version 1.4

### Steps to reproduce

Create US Custom layout which is identical to normal US layout:
- https://www.microsoft.com/en-us/download/details.aspx?id=102134
- File->Load Existing Keyboard->US
- Build DLL and Setup package

Observe the keycode in WSL (I'm using /usr/lib/ncurses/examples/demo_altkeys from ncurses-examples) when pressing ctrl+shift+-
  

### Expected Behavior

^_

### Actual Behavior

^J

**Comment by rolandschulz** [comment]
Yes with 1.16.10262.0 and 1.18.1462.0 I'm still experiencing the same incorrect behavior.

**Comment by zadjii-msft** [comment]
Can you try repro'ing this with the [debug tap](https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#enabling-the-debug-tap) to get a trace of all the input and output/? Once the bug starts occurring, send us a screenshot and we might be able to figure out what the Terminal thinks it's getting here.
