### ISSUE TITLE
Rename the `newTabPosition` strings

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#13597]
Follow-up from #13421

### Settings UI
Position of the new tab --> Position of newly created tabs
Specifies position of the new tab --> Specifies where new tabs appear in the tab row
At the end --> After the last tab
After current tab	--> After the current tab

### JSON
atTheEnd --> afterLastTab
afterCurrentTab --> afterCurrentTab

No need for legacy converter

### Code
we _should_ rename the enums to match the new names

**Comment by serd2011** [comment]
Is this a legacy converter? It doesn't compile for me without it. https://github.com/microsoft/terminal/blob/6c2316df44779deb9480c769e3354187660e6736/src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h#L240-L246

**Comment by DHowett** [comment]
Sorry, we didn't make that super clear. A legacy converter is one that includes support for the old data that might be in a user's settings file :smile:
