### ISSUE TITLE
Multi window batch command just like “electerm”

### ISSUE THREAD

**Issue by address2018** [microsoft/terminal#13609]
![bcb4f8a59930a76e7c320e5ae7ba3bd](https://user-images.githubusercontent.com/27394602/181152781-a7aa4787-64a1-4a73-a0ea-a18e637428fb.jpg)

**Comment by zadjii-msft** [comment]
Are you talking about something like "sending input to multiple tabs", as in #2634/? Pardon me for not really being familiar with Electerm - it's not immediately clear to me what exactly the thing in the screenshot you've got highlighted there is.
