### ISSUE TITLE
Add terminal as default Windows+X shortcut (instead of powershell)

### ISSUE THREAD

**Issue by softyoda** [microsoft/terminal#13618]
# Description of the new feature/enhancement

Like default in Windows 11, it would be neat to have the option to add it to Windows 10!

**Comment by zadjii-msft** [comment]
Unfortunately, the team that owns the Win+X menu isn't going to be looking to backport that feature any time soon. 

_addenda_: An earlier thread of this was #1421, which got duped to the default Terminal work in #492, which all wholly predates the concept of Windows 11, despite defterm only landing in Windows 11. I could've swore we had a thread about this before...
