### ISSUE TITLE
Larger column count with Acrylic enabled causes input lag

### ISSUE THREAD

**Issue by bhatasaka** [microsoft/terminal#1361]
# Environment
```
Windows build number:[Version 10.0.18922.1000]
Windows Terminal version: 0.0.1.0 (Commit 66cb7c4b 6/20/2019 12:20:49 PM)
Built with VS 2019 (latest version as of June 20, 2019)

Dell Inspiron 7559
4K display with scaling at 200%
i7-6700HQ
Intel HD 530
GTX 960m (with Nvidia Optimus)
```

# Steps to reproduce

Make sure acrylic is enabled for your profile. Resize with window to more than ~160-180 columns.
Type.

# Expected behavior

The window is larger and imputing text acts the same.

# Actual behavior

Input lag increases significantly. Before resizing the window, there is minimal input lag, barely or not noticeable. After resizing (or starting with a column count > ~160-180), it is easy to type faster than the characters will appear on screen. This happens for WSL Ubuntu 18.04, 18.10, 19.04, CMD and Powershell. I'm not sure if this is specific to using a 4k display with integrated graphics or if this is a Windows bug with acrylic.

**Comment by vasekboch** [comment]
Can confirm this on Surface Book 2 13 with enabled acrylic and fullscreen window. There is noticable lag.
Version 0.2.1715

**Comment by DHowett-MSFT** [comment]
This should be helped by #778
