### ISSUE TITLE
Emacs menu bar color inversion truncated

### ISSUE THREAD

**Issue by donpellegrino** [microsoft/terminal#13613]
### Windows Terminal version

1.14.1963.0

### Windows build number

10.0.22000.0

### Other Software

OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
GNU Emacs 25.2.2
GNU Emacs 26.3

### Steps to reproduce

When running Emacs from a remote system over SSH or from WSL2 Ubuntu 20, the first row of the display no longer shows the menu bar all the way across. I tested this with GNU Emacs 26.3 on WSL2/Ubuntu 20, GNU Emacs 25.2.2 over SSH, and GNU Emacs 26.3 over SSH. All three instances of Emacs exhibit the same behavior when rendered by Windows Terminal.

### Expected Behavior

Emacs menu bar shows all the way across the first line.

### Actual Behavior

Emacs menu bar gets truncated. The first line of the terminal output of Emacs showed the menu bar all the way across the terminal as of a few days ago. I don't know why the rendering suddenly changed. Perhaps a defective version of Windows Terminal was pushed to devices via Microsoft Store recently?

**Comment by donpellegrino** [comment]
![Windows Terminal Emacs Menu Rendering](https://user-images.githubusercontent.com/4835457/181272884-30334839-00c5-46d0-8e87-5c5d34f7cd08.png)

**Comment by FractalBoy** [comment]
This happens to me as well, but it seems to only happen within tmux. To reproduce:

1. `width=$(tput cols); printf "\033[7m%-${width}s\033[27m" text`
2. Resize tmux window or create pane

**Comment by FractalBoy** [comment]
I take that back - this also seems to happen outside of tmux:

1. In a small window, run `width=$(tput cols); printf "\033[7m%-${width}s\033[27m" text`
![image](https://user-images.githubusercontent.com/2024233/181280320-b266119b-eed0-474f-b323-333f1767075c.png)

2. Expand the window - the text disappears
![image](https://user-images.githubusercontent.com/2024233/181280388-f7235564-83be-4d0a-a9c3-2f6f9d3f252f.png)

**Comment by zadjii-msft** [comment]
Pretty sure this is /dup #13229

**Comment by elsaco** [comment]
This seems to be a non-Windows Emacs issue. Windows version is not affected when running `emacs -nw`:

![emac_menu-bar_win_version](https://user-images.githubusercontent.com/3933920/181290654-2530c178-4095-4ff5-81bf-97d0329a2089.png)
