### ISSUE TITLE
Tab name appends the currently executing batch file, and when terminated, it remains as part of the name

### ISSUE THREAD

**Issue by rbeesley** [microsoft/terminal#1362]
# Environment

```none
Windows build number: 18362.175
Windows Terminal version: 0.2.1703.0
```

# Steps to reproduce

1. Run a batch file in a cmd shell.
2. While it is running use ctrl+c to break and then terminate the batch job.
3. Repeat to continue growing the tab name.

# Expected behavior

The tab text will return to just the shell executable name, like C:\WINDOWS\system32\cmd.exe

# Actual behavior

The name appends the name of the batch file it is running, but when you terminate and break that process, it doesn't remove the name of the batch file. This causes it to keep appending with each execution.
![image](https://user-images.githubusercontent.com/3703112/59892495-24969c00-938e-11e9-8ca7-698c65bdbfe3.png)

**Comment by DHowett-MSFT** [comment]
Does this happen when you do the same thing in traditional conhost?

**Comment by rbeesley** [comment]
It does... Should I log a bug against that through Feedback Hub?

**Comment by DHowett-MSFT** [comment]
I think there’s one in the CMD backlog for that. I’ll warn you, though, that CMD is probably not going to be changed unless you’ve managed to find something of _significant, stop-the-world_ business impact.

**Comment by rbeesley** [comment]
Understandable.
