### ISSUE TITLE
Prevent Terminal from Auto Upgrading When Terminal is Open and In Use

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/terminal#13620]
# Description of the new feature/enhancement

Windows Terminal Updates Itself through **Microsoft Store** or **Other Update Mechanisms** when the Terminal is Open or In Use, This Could Make the users to lose Operation that were currently running in Terminal

# Proposed technical implementation details (optional)

Implement a Feature that Detects, If the Terminal is Open and In Use, If that's true pause the Auto Update Until the **Windows Terminal** Gets Closed and Not in Use

**Comment by j4james** [comment]
See issue #3915.

**Comment by zadjii-msft** [comment]
Yep. Also see https://github.com/microsoft/terminal/issues/6726#issuecomment-1147358557 - the Store team is actively working on rolling this out. 

/dup #3915
/dup #6726
