### ISSUE TITLE
Having this same issue in macOS as of today. Per @meganrogge recommendation on #156668, I set `terminal.integrated.enablePersistentSessions: false`, but am still having this issue. It's persisted through a complete wipe of settings and a fresh install.

### ISSUE THREAD

**Issue by Drerootz1** [microsoft/terminal#13628]
Having this same issue in macOS as of today. Per @meganrogge recommendation on #156668, I set `terminal.integrated.enablePersistentSessions: false`, but am still having this issue. It's persisted through a complete wipe of settings and a fresh install.

_Originally posted by @drenze-athene in https://github.com/microsoft/vscode/issues/130320#issuecomment-1199733729_

**Comment by DHowett** [comment]
Hi there -- sorry, I can't quite understand what your bug report is. This repository only contains software for Windows :smile:

**Comment by drenze-athene** [comment]
> Hi there -- sorry, I can't quite understand what your bug report is. This repository only contains software for Windows 😄

I'm not certain how this got opened here. I initially submitted a VSCode bug report for macOS, got referred to another open issue for the same thing that was initially opened by a Windows user, and then this got opened. I'm not certain how this got opened here.

**Comment by DHowett** [comment]
_Huh!_ No problem. If it turns out this was an important thing to end up on our repo, I'll reopen it. Thanks!
