### ISSUE TITLE
Pasting into vim appears to send escape character.  

### ISSUE THREAD

**Issue by jeffpkamp** [microsoft/terminal#13648]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19043.1826

### Other Software

Vim version 8.0 (2016 Sep 12, compiled Jun 19 2022 10:00:27)

When I copy and paste there are two unusual behaviors. When I paste into vim while it is in edit mode, It exits edit mode as if the ESC key has been pressed before the insert begins.  

### Steps to reproduce

open vim

press a to go into append mode.

copy and paste 
`echo hello world`

### Expected Behavior

I expected it to paste
`echo hello world`

### Actual Behavior

It pasted 
`O hello world`

**Comment by DHowett** [comment]
Are you using Linux vim within WSL? Over SSH? Are you using Windows vim?

**Comment by zadjii-msft** [comment]
Welp, let us know if it comes back!
