### ISSUE TITLE
Neovim often freezes when pasting in Windows Terminal

### ISSUE THREAD

**Issue by eggbean** [microsoft/terminal#13645]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22621.436

### Other Software

WSL version: 0.64.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.40
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.436

NVIM v0.7.0
tmux 3.3

### Steps to reproduce

(I'm not sure if this only happens on neovim, as it probably happens in vim as well - it's just that I am nearly always using neovim instead when I am on WSL)

(I'm not sure if this only happens within tmux, as I am nearly always in tmux)

I do think that this is a problem with Windows Terminal specifically.

When I paste using Shift-Insert, it often freezes Windows Terminal for 20 seconds or so and sometimes for longer. Sometimes if it keeps hanging I close the terminal and restart it. Thankfully the tmux session remains intact.

Most of the time it pastes fine with no problems, but it happens often enough to make it very irritating.

### Expected Behavior

No hanging after attempting to paste in nvim.

### Actual Behavior

Freezing/hanging for 30 seconds or so to indefinitely.

**Comment by zadjii-msft** [comment]
This was discussed previously at length in #11945

> Neovim tries using `win32yank.exe` if it's available

and I suspect this is due to a bug in `win32yank.exe` that locks the clipboard (and then eventually, the Terminal). I'd try disabling that, and if that doesn't work, follow up in that thread. Thanks!

/dup #11945
