### ISSUE TITLE
Scrollbar is inset by padding and probably shouldn't be

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#1365]
# Environment
commit 08464648
# Steps to reproduce

In settings, set padding upper, lower or right to be > 0

# Expected behavior
Only text should be padded (I think)
# Actual behavior
Scrollbar is padded too

**Comment by yodurr** [comment]
Shouldn't the scrollbar match the text it scrolls?  Do something extreme like 100 vertical padding and it looks pretty clear to me the scrollbar should match the padding settings the way it does now.

**Comment by mdtauk** [comment]
I would have thought the ScrollBar should always align to the edge of the view, and the padding is for the content within it.

**Comment by Stanzilla** [comment]
Yeah it should always align to the edge. Currently it also gets moved off-screen when you set a left padding
