### ISSUE TITLE
Font features break line drawing

### ISSUE THREAD

**Issue by registerGen** [microsoft/terminal#13662]
### Windows Terminal version

1.15.2003.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Modify the config file as below:

![image](https://user-images.githubusercontent.com/62944333/182560636-d2f91f11-65dd-4f39-bdc8-bb42f578acca.png)

### Expected Behavior

Unicode isn't broken.

![image](https://user-images.githubusercontent.com/62944333/182561910-17b39bb3-e083-4dad-a218-2f156c40c882.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/62944333/182561653-0c5fb3b6-62c6-40aa-9566-86facbc2bc13.png)

**Comment by registerGen** [comment]
The font can be downloaded from [here](https://github.com/adam7/delugia-code/releases/download/v2111.01/delugia-complete.zip).

**Comment by registerGen** [comment]
I tried many stylistic sets of Cascadia Code and Delugia, this all repro-ed.

But if Fira Code is used, this won't happen.

**Comment by lhecker** [comment]
Unless I'm testing incorrectly, this issue doesn't seem to occur with AtlasEngine, after #13549.

**Comment by registerGen** [comment]
Well this issue still occurs in the latest release yesterday, but the "gap" is much unnoticeable now.

![image](https://user-images.githubusercontent.com/62944333/190161073-415c50bb-0ae9-44c0-8937-ea9c1c1ab9d4.png)

**Comment by lhecker** [comment]
I'm glad it's much better! Very slight gaps are something I've also noticed myself for fonts that aren't particularly pixel-perfect, but I haven't had time to investigate it further yet. This is the worst that I could produce myself (magnified 400%):
![image](https://user-images.githubusercontent.com/2256941/190162240-8caa16df-6175-4ca4-ae35-f39e278a32ed.png)

Yours seem to be the exact same kind, which means I can reproduce and thus hopefully fix it.
