### ISSUE TITLE
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

### ISSUE THREAD

**Issue by payn-git** [microsoft/terminal#13676]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19042.1706

### Steps to reproduce

run "winget install --id=Microsoft.WindowsTerminal -e" in admin command line

### Expected Behavior

WT will install correctly :)

### Actual Behavior

![WTInstallFail](https://user-images.githubusercontent.com/4748314/182935831-8c12ed5a-96e7-4df7-ab27-f2ccafa1a470.PNG)

**Comment by zadjii-msft** [comment]
@denelon any ideas here? Anything we can do to get more verbose info?

**Comment by denelon** [comment]
I'd start with `winget --info` to see were logs go, then I'd run `winget install Microsoft.WindowsTerminal --verbose-logs`.

It could be the Windows 10 version is one older than the Windows 11 version:

* https://github.com/microsoft/winget-cli/issues/2134

**Comment by zadjii-msft** [comment]
Also, you're apparently on 1.14, but `winget` tried to install 1.13? That doesn't make sense...

If anything, the latest stable release was `1.14.1861.0`. I think the `1.14.1962` release is the one we shipped as a hotfix (but never got around to publishing release notes due to some unexpected OOFages). 

Regardless, I'd try the commands suggested above, to get more details.

**Comment by denelon** [comment]
> unexpected OOFages

😂

**Comment by ashemedai** [comment]
FYI, on my Windows 10 system I think I see something similar:

![image](https://user-images.githubusercontent.com/610865/183243620-0f16e6ed-fd32-4f87-b237-9a2125477223.png)

So it seems something upstream for Winget is looking at the wrong version.

**Comment by ashemedai** [comment]
Ah, it looks there are no manifests in https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsTerminal after 1.13.11431.0. That would explain much.

**Comment by payn-git** [comment]
I guess no more info required from me than :).

**Comment by zadjii-msft** [comment]
Oh derp yea, this is /dup #13542
