### ISSUE TITLE
Sometimes the WT window is hidden (I can see it in taskbar), but I can't get the window back

### ISSUE THREAD

**Issue by dracan** [microsoft/terminal#13683]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Not sure - it just happens randomly.

### Expected Behavior

To be able to bring WT to the foreground and interact with it.

### Actual Behavior

Sometimes WT window just disappears, but I can still see it in the taskbar...

![image](https://user-images.githubusercontent.com/567988/183064438-b57b09f8-e879-46d4-b737-dec9b4c3febe.png)

Nothing happens if I click on it.

Sometimes I get a system tray icon that will allow me to get focus back (with right-click->focus) - but sometimes it's not there either.

Might be unrelated, but I've been using quake mode a lot recently. It's not the quake window I'm having trouble with - but it might be that it happens to the main window sometimes if I use the quake window.

**Comment by zadjii-msft** [comment]
Did you minimize it by clicking on the taskbar/? Good chance this is #13589

**Comment by dracan** [comment]
Ah yes! That seems to be doing it! And your workaround [here](https://github.com/microsoft/terminal/issues/13589#issuecomment-1194634061) successfully gets me out of it too :) Now at least I don't have to kill the process 😆

**Comment by zadjii-msft** [comment]
Perfect, glad it wasn't something else 😅 We'll probably have a hotfix out for that Soon<sup>TM</sup>

/dup #13589
