### ISSUE TITLE
Inactive tab BG color (`tab.inactiveBackground`)

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13684]
Important, because when unset, the tab will use the active Background color to create an inactive BG, which maybe isn't what we want. Consider - a bright cyan active BG, transparent `inactiveBG`, and `terminalBG` for the `tabRow` bg.

See also #13554. If we want to make the default theme `tab.background: terminalBackground`, we should make this transparent by default.

**Comment by dansmor7** [comment]
Here is an idea: what if you could set the opacity for a referenced color?
It could look something like this:
```
tab.unfocusedBackground: tab.background,
tab.unfocusedBackground.opacity: 0.5
```
It would also make sense to allow customizing the tab color on hover.

And it would be useful if you could distinguish between tabs with set colors and default tabs.
`coloredTab.unfocusedBackground` would still show the color, but `tab.unfocusedBackground` would be Transparent.
