### ISSUE TITLE
Set `COLORTERM` environment variable to `truecolor` in linux

### ISSUE THREAD

**Issue by XenoBino** [microsoft/terminal#13687]
# Description of the new feature/enhancement

_#2785 Might be relevant_

Many programs check if `COLORTERM` environment variable is set to `truecolor` to determine whether the terminal supports true colors. And since this terminal supports true colors, it would make sense for `COLORTERM` to be set to `truecolor` automatically for linux profiles.

# Proposed technical implementation details (optional)

I suppose this would require the feature proposed by #2785.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+COLORTERM+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #11057 for more discussion.

/dup #11057
