### ISSUE TITLE
Build doesn't show in new GUI

### ISSUE THREAD

**Issue by phishfi** [microsoft/terminal#1369]
Whenever I build WinTerminal (using any of the half-dozen available walkthoughs, it always comes out looking like this... Any idea what I'm doing wrong that's keeping it from looking like it does for everyone else?

[Image](https://imgur.com/TuVbOuB)

**Comment by oising** [comment]
That attached image looks correct. Other people have customized theirs by changing settings, colors and fonts etc, so that's why you're probably feeling confused.

**Comment by phishfi** [comment]
> 
> 
> That attached image looks correct. Other people have customized theirs by changing settings, colors and fonts etc, so that's why you're probably feeling confused.

Is there a template that allows it to look more acrylic/fluent design?

**Comment by DHowett-MSFT** [comment]
Please look at the settings file. Everything you can change is listed in that file.
