### ISSUE TITLE
command palette should support both setting language and English search

### ISSUE THREAD

**Issue by qijizh** [microsoft/terminal#13696]
# Description of the new feature/enhancement
command palette should support both setting language and English search
## Current behaviour
when language is English , type `toggle` and it works perfectly
![image](https://user-images.githubusercontent.com/59334350/183259458-cfa0ab63-d1e2-4723-b5a5-1ad1137b028f.png)
when language is Chinese, type `toggle` and I get nothing:
![image](https://user-images.githubusercontent.com/59334350/183259517-a598c9d5-c8af-4c10-b9d6-614bb9b78954.png)
I have to type `切换` to get a match
![image](https://user-images.githubusercontent.com/59334350/183259567-ab2afec4-f027-4a50-a1e3-86bcacee90c6.png)
However, toggle is a verb, so the translation is relatively uniform. When I want to search by nouns, there may be several translations of a term, so I have to try them all
## Expected behavior
VSCode's command palette works as expected, supporting both setting language and English search and displaying them
![image](https://user-images.githubusercontent.com/59334350/183259988-df6d5e16-004a-4ac7-9c77-be8054bbf08a.png)

**Comment by j4james** [comment]
This sounds like a duplicate of #7039.

**Comment by qijizh** [comment]
Sorry, I failed to retrieve the relevant issue when I checked it before, I will close mine
