### ISSUE TITLE
Windows Terminal doesn't process keyboard input?

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/terminal#13701]
### Windows Terminal version

1.14.1963.0

### Windows build number

10.0.22000.795

### Steps to reproduce

Launched Windows terminal for a few minutes, suddenly, it doesn't accept any keyboard input, which means there is no response in Windows Terminal no matter what I type into its window.

### Expected Behavior

The keyboard input should to go as the command line input.

### Actual Behavior

Windows Terminal shows/does nothing no matter what I typed there. Other apps and cmd.exe works fine.

**Comment by zadjii-msft** [comment]
Does this only happen to one tab, or when this happens, do all tabs stop responding to keyboard input? Can you open the command palette in this state, via the new tab dropdown, and type in there/?

**Comment by ThomsonTan** [comment]
> Does this only happen to one tab, or when this happens, do all tabs stop responding to keyboard input?

This happens to all tabs, even for the new tab I opened when the issue happened. Will try open command palette if I get the repro again.

**Comment by zadjii-msft** [comment]
I'd also be curious in what you're actually running in the tab that becomes unresponsive. I vaguely recall an issue from a few months ago where a bad `ssh` version could result in the tab seemingly hanging, when really it was just `ssh` that stopped responding to input.

**Comment by ThomsonTan** [comment]
Cannot remember I was running the inbox ssh.exe or not. I think in my case it is not single app doesn't respond to input as there are multiple tabs (more than 3) and all hang on input.

**Comment by zadjii-msft** [comment]
Okay. I'd definitely be curious what the solid repro is here. "after a few minutes it stops responding to input" doesn't really give a lot to work off of. If there was a DPI change, or the window resized, or you executed something specifically that caused it to hang, that'd be much more interesting. If it just stops responding to keyboard input, but _not_ mouse input, that too would be interesting (heck, that'd be crazy surprising).

**Comment by Klosw** [comment]
> 

但是 win自带的 终端是没有出现这种情况的呀
