### ISSUE TITLE
App-level keybindings are routed through the control, this causes some weirdness

### ISSUE THREAD

**Issue by vhanla** [microsoft/terminal#1370]
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.18362.175]
Windows Terminal version (if applicable): 0.0.10

Any other software?
```

# Steps to reproduce

Click any tab, you'll notice that the console's blinking cursor will stop, then hit `Ctrl`+`Shift`+`1` to start another PowerShell console tab.

# Expected behavior
Launch another PowerShell console tab

# Actual behavior
It doesn't do anything. Until you click the current console area (not tab) in order to see the blinking cursor again, then the hotkey will work.

**Comment by zadjii-msft** [comment]
This frankly seems like #528

**Comment by zadjii-msft** [comment]
This has been largely resolved in past releases. #6680 was tracking most of them.
