### ISSUE TITLE
Rendering bug with icons wider than one column (gap in background)

### ISSUE THREAD

**Issue by ghillb** [microsoft/terminal#13700]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1826

### Other Software

- WSL Ubuntu 22.04
- nvim 0.7.2, 
- FiraCode Retina NerdFont.
- lualine nvim plugin (example appears anywhere where an icon is rendered in front of solid background)

### Steps to reproduce

- Install FiraCode NF (https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)
- Install nvim 0.7.2 in ubuntu WSL
- Install lualine plugin (https://github.com/nvim-lualine/lualine.nvim)
- Open test xml file with `nvim test.xml` and observe rendering bug, where icon is rendered

### Expected Behavior

No gap in rendering 

alacritty (windows) or kitty (ubuntu), do not have this issue with the same font:
![image](https://user-images.githubusercontent.com/35503959/183420053-56048fa8-7260-433e-9a6e-2a3c7408b39c.png)

### Actual Behavior

Gap in background highlight rendering, when icons wider than 1 column (e.g., xml file icon in nerd fonts) are rendered.

ms-terminal:
![image](https://user-images.githubusercontent.com/35503959/183419485-0eb37461-0c54-4486-98ba-049e816139c0.png)

more info:
https://github.com/nvim-lualine/lualine.nvim/issues/790

**Comment by zadjii-msft** [comment]
This might be fixed by the new experimental renderer. I think we've got some fixes in the works for 1.16 that might just address this. /cc @lhecker
