### ISSUE TITLE
Press any key to reconnect

### ISSUE THREAD

**Issue by DemoerDuan** [microsoft/terminal#13713]
# Description of the new feature/enhancement
we want a function like "Press any key to reconnect“.
# Proposed technical implementation details (optional)

**Comment by lhecker** [comment]
Reconnect to where with what? Are you talking about SSH? 🙂

**Comment by DemoerDuan** [comment]
> Reconnect to where with what? Are you perhaps talking about SSH? 🙂

Yes，I opened a tab to connect a host by ssh,  After a while, the host will auto disconnect, and I want to  reconnet this host in original tab quickly,  but I didn't find this function.

**Comment by lhecker** [comment]
Is this existing issue what you were thinking of? https://github.com/microsoft/terminal/issues/4379

**Comment by DemoerDuan** [comment]
> Is this existing issue what you were thinking of? #4379

Yes,
