### ISSUE TITLE
Quake Mode: Unable to exit Settings UI

### ISSUE THREAD

**Issue by marcolongol** [microsoft/terminal#13718]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22622.0

### Steps to reproduce

1. Open terminal in `Quake Mode` with `` 🪟+` ``
2. Open the Settings UI with `ctrl+,`

### Expected Behavior

A Close button to exit the Settings UI should be provided.

### Actual Behavior

There is no way to exit the Settings UI from there. A close button should be provided in the UI.

**Comment by zadjii-msft** [comment]
As discussed in #13518: 

/dup #7210 (short term)
/dup #5677 (long term)
