### ISSUE TITLE
Feature Request: improve default profile padding

### ISSUE THREAD

**Issue by yodurr** [microsoft/terminal#1371]
The default profiles have a 0,0,0,0 padding and it doesn't look good pinned against so tight against the window frame.

Recommend changing the default to indent to 4,2,0,0.  Curious what others use for their preferred padding.

I'll submit the PR (along with potentially other default profile changes that seem like forward progress)

**Comment by mdtauk** [comment]
Padding will depend on the font size of course.  I set my fontsize to 14, and padding to 12, 8, 12, 8

**Comment by yodurr** [comment]
How about increase the default font size from 10 to 11, then 4,2,4,2 padding

**Comment by zadjii-msft** [comment]
@DHowett-MSFT This might be something that we want to research, if people are setting padding or not. 

Frankly I'm using `2` as my padding personally, but I thought that people would prefer `0` padding by default.
