### ISSUE TITLE
Windows Terminal Window isn't able to be brought to forefront sporadically after switching to a different window

### ISSUE THREAD

**Issue by erikumhoefer** [microsoft/terminal#13729]
### Windows Terminal version

1.14.1962.0

### Windows build number

 10.0.19044.0

### Steps to reproduce

* Have windows terminal open
* Switch to other windows
* Try to reopen Terminal again by clicking on icon in task bar, or attempting to ALT + Tab to window
* Realize Windows terminal window will not pull back up
* Close Windows Terminal Instance and reopen
* Terminal will work as expected for some time but then issue reappears

### Expected Behavior

I am able to bring the window for the terminal back into view so I can use it, as expected when bringing up windows for any other application.

### Actual Behavior

Unable to bring windows terminal back to forefront, despite the icon still showing an instance of terminal is running.

When using windows terminal, when switching to different windows (FireFox, VSCode, Outlook, etc. haven't been able to get a correlation between what application is interfering (if it is only one)), occasionally I am unable to bring back the Terminal window back into forefront. So, in order to use Terminal again, even though the icon is on the taskbar showing that the instance is running, I will have to close the "running" instance, and reopen to use it. This has recently started happening and occurs almost daily.

How to reproduce:
* Use terminal with other applications open (doesn't matter if in full screen or windowed)
* switch between terminal and other apps
* Eventually, won't be able to switch back to Terminal and will need to restart it in order to use it.

Development environment: Laptop with screen closed connected to two monitors. Only using two monitors. Alt+Tabbing to try and bring window back does not work.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13589 for more discussion.

/dup #13589
