### ISSUE TITLE
Use Terminal for Help and Version Output

### ISSUE THREAD

**Issue by StefanGreve** [microsoft/terminal#13728]
# Description of the new feature/enhancement

If you run the help or version command for `wt`, a new window appears to display this information. I think it would make much more sense to write this information directly to terminal since this information (e.g. the version number) cannot be easily processed by other scripts.

![image](https://user-images.githubusercontent.com/32100623/184329819-1c77db17-0e9a-46b5-b31c-7f8c5ebb6d15.png)

Affected commands:

1. `wt --version`
2. `wt --help`

# Proposed technical implementation details (optional)

In my opinion it would be better if the output of these commands would be displayed in the terminal directly. Frankly speaking, it is irritating that there are windows popping up every time I want to check which version of Windows Terminal I am on.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7258 for more discussion. That thread covers more of why this is a **H**ard problem

/dup #7258
