### ISSUE TITLE
程序无法中断 ^C

### ISSUE THREAD

**Issue by Klosw** [microsoft/terminal#13722]
### Windows Terminal version

1.14.1962.0

### Windows build number

Microsoft Windows [版本 10.0.19044.1889]

### Steps to reproduce

使用 git log 后  

### Expected Behavior

中断程序 

### Actual Behavior

使用 Ctrl+C 无法中断程序, 使用 Ctrl+ Pause 后 能进入输入命令 ,但是按 Ctrl+C  还是会显示 git log 的日志

**Comment by zadjii-msft** [comment]
How did you set up and run `git log`? Mingw? WSL? Via ssh/? 

Sounds vaguely like:
* #8034
* #13503

**Comment by Klosw** [comment]
> 

就是 win 版本的 git

**Comment by Klosw** [comment]
![image](https://user-images.githubusercontent.com/13143959/184493282-627f12b4-a725-4c4a-b618-030376845272.png)


> How did you set up and run `git log`? Mingw? WSL? Via ssh/?
> 
> Sounds vaguely like:
> 
> * [CTRL C doesn't work properly on gitbash #8034](https://github.com/microsoft/terminal/issues/8034)
> * [Ctrl+c doesn't work after have used `ssh` in Powershell in the same terminal session #13503](https://github.com/microsoft/terminal/issues/13503)

类似这样 的 但是 log必须超过屏幕

**Comment by Klosw** [comment]
坏了   cmd 也不响应

**Comment by zadjii-msft** [comment]
Okay, another test. Can you run:

```
git --version
where git
```

In a CMD tab/?

Your settings file might also be interesting, if only to confirm that nothing is bound to `ctrl+c`. (You might have `ctrl+c` bound to `copy`, but that should still send a ^C when there's no text selected)

**Comment by Klosw** [comment]
> Okay, another test. Can you run:
> 
> ```
> git --version
> where git
> ```
> 
> In a CMD tab/?
> 
> Your settings file might also be interesting, if only to confirm that nothing is bound to `ctrl+c`. (You might have `ctrl+c` bound to `copy`, but that should still send a ^C when there's no text selected)

**Comment by Klosw** [comment]
> Okay, another test. Can you run:
> 
> ```
> git --version
> where git
> ```
> 
> In a CMD tab/?
> 
> Your settings file might also be interesting, if only to confirm that nothing is bound to `ctrl+c`. (You might have `ctrl+c` bound to `copy`, but that should still send a ^C when there's no text selected)

It's the same question

[CTRL C doesn't work properly on gitbash #8034](https://github.com/microsoft/terminal/issues/8034)
