### ISSUE TITLE
when I minimize the terminal screen, then open other program in full screen, and click the terminal icon in taskbar finally? that's wrong ?

### ISSUE THREAD

**Issue by FxPixels** [microsoft/terminal#13723]
### Windows Terminal version

1.14.1962.0

### Windows build number

Windows 10 企业版 LTSC     21H2     19044.1826

### Steps to reproduce

![动画](https://user-images.githubusercontent.com/25996313/184136139-06081882-ee00-49fa-9ae6-005f5f4d2a78.gif)

### Actual Behavior

show in the image

**Comment by zadjii-msft** [comment]
Please search before posting new issues. The issue you've described is literally pinned to the top of the repo.

/dup #13589
