### ISSUE TITLE
Buttons not rendering correctly when using Ultrawide monitors

### ISSUE THREAD

**Issue by ptedeschi** [microsoft/terminal#13732]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1826

### Steps to reproduce

- Open Terminal in a Ultrawide monitors
- Open About screen

### Expected Behavior

The modal button should display the text "Ok"

### Actual Behavior

The modal button only displays a blue rectangle:
![image](https://user-images.githubusercontent.com/6684508/184428335-36f8f10b-b13c-4729-8a72-94104e6c3aeb.png)

**Comment by zadjii-msft** [comment]
I'd be shocked if this actually had anything to do with the screen resolution.... Do you have a non-ultrawide monitor that this does/does not repro on/?

What does the color schemes page of the settings UI look like? (There's another bug floating around here this reminds me of)

**Comment by ptedeschi** [comment]
@zadjii-msft The monitor resolution definitely plays a role in this. My setup is a notebook with a resolution of `1920x1080` and an UltraWide monitor `2560x1080` connected to this notebook. When I open the Terminal on the notebook screen, everything is normal. When I open it in Ultrawide monitor, the button has this issue. And I just realized that it's not just the Terminal that gets away with this. The Microsoft Store suffers from the same behavior

**Comment by J0F3** [comment]
I have the same problem. On a monitor with the resolution 5120x1440 the blue buttons do not show the text (like in the screen shot above). But in the internal laptop screen with 3840x2160 every thing is normal. 

For me also the background opacity doe not work correctly and is basically unusable on the screen with 5120x1440 resolution:

![image](https://user-images.githubusercontent.com/12759579/215041415-f7f35671-60ed-4860-8d1d-9f00086b13d6.png)
![image](https://user-images.githubusercontent.com/12759579/215041475-58545e92-fe38-4ebe-95d2-15360608ad7a.png)

I noticed also that it affects not only the Windows Terminal but for example also the Microsoft Store App has show the same issue. So it seems more to be a Window (10?) wide problem that a Windows Terminal specific.

**Comment by carlos-zamora** [comment]
Hi @J0F3 (or @ptedeschi if you're still seeing this). Circling back around to this. Could you file some feedback using feedback hub? Please file this under Desktop Environment > DWM.

**Comment by J0F3** [comment]
@carlos-zamora Unfortunately  I can not use Feedback Hub because it is blocked (company device). But anyway, the issue is gone for me . Since I had connected the device once to a Display Link Docking station the problem was magically gone. So maybe it was more a side effect of the Display Link driver or something...

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
