### ISSUE TITLE
The default style of the Terminal should follow basic Windows 10 design principles. 

### ISSUE THREAD

**Issue by Borkason** [microsoft/terminal#1373]
I want to suggest that the _default style_ of the Terminal should follow [basic Windows 10 design principles](https://docs.microsoft.com/en-us/windows/uwp/design/). Customizability is great, but by default it should foremost look like it's part of Windows and not like a 3rd party app.

The Terminal has a thick white border. Other native Windows apps (Edge, Settings, Calculator, ...) have a very slim and black border.

![grafik](https://user-images.githubusercontent.com/2971735/59955981-a28d9c80-948d-11e9-8e93-b8727acf4b23.png)

Terminal has Chrome-like tabs that look different than those from Windows native apps like e.g. Edge.

![grafik](https://user-images.githubusercontent.com/2971735/59956008-ce108700-948d-11e9-8fbf-93d332ec8d3d.png)

The 'new tab' button looks different than in Windows native apps like e.g. Edge.

![grafik](https://user-images.githubusercontent.com/2971735/59956019-e54f7480-948d-11e9-83f3-ffb73146ff91.png)

The X-background is smaller than on other native Windows apps and has a white space underneath it, where native Windows apps don't have one.

![grafik](https://user-images.githubusercontent.com/2971735/59956367-1d57b700-9490-11e9-820f-9ab49ec4b9f0.png)

The top window frame is not yet acrylic. Comparison with the Snip & Sketch app.

![grafik](https://user-images.githubusercontent.com/2971735/59956416-7cb5c700-9490-11e9-93e5-c2c1502e9726.png)

**Comment by DHowett-MSFT** [comment]
This is #872 #929

**Comment by DHowett-MSFT** [comment]
@Borkason I moved your images into the design mega-issue; feel free to subscribe to that one!
