### ISSUE TITLE
Windows Terminal sets its own color without my permission

### ISSUE THREAD

**Issue by SsNiPeR1** [microsoft/terminal#13737]
### Windows Terminal version

1.14.1963.0

### Windows build number

10.0.22000.0

### Other Software

OpenSSH client and xtermcontrol

### Steps to reproduce

 - Set any color with xtermcontrol
 - Alt-tab on any other window and be there ~10-15 seconds
 - Return back to the terminal
 - See black screen instead of previously set color

### Expected Behavior

I was expecting windows terminal to preserve that color

### Actual Behavior

Windows terminal changed its color

**Comment by SsNiPeR1** [comment]
Some update: it changes its color when I change language and this language menu pops up

**Comment by j4james** [comment]
This sounds similar to #11522.

**Comment by zadjii-msft** [comment]
Yep!

/dup  #11522
