### ISSUE TITLE
Batch files do not seem to respect windowingBehavior

### ISSUE THREAD

**Issue by Bladehawke** [microsoft/terminal#13733]
### Windows Terminal version

1.14.1963.0

### Windows build number

10.0.22000.0

### Other Software

cmd.exe
expl;orer.exe

### Steps to reproduce

* Set windowingBehavior to "useAnyExisting"
* close all wt windows
* Open a new instance of wt with PoweShell as the default profile
* launch a bat file from Windows Explorer
* launch another bat file from Explorer

### Expected Behavior

two New tabs in existing window running the batch file(s)

### Actual Behavior

New window opens which subsequent bat files will also target

**Comment by carlos-zamora** [comment]
Thanks for the report! Is this still happening?

**Comment by Bladehawke** [comment]
This appears to be fixed in 1.16.10262.0

**Comment by zadjii-msft** [comment]
Cool, thanks for confirming! We must've fixed it somewhere along the way 😄
