### ISSUE TITLE
[1.14.1962.0] The window of wt disappeared after some window switch operations and can not restore normally

### ISSUE THREAD

**Issue by GitPopcorn** [microsoft/terminal#13742]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19042.1706

### Other Software

A pomodoro timer widget built with Electron pinned at the top of all windows. In fact I don't know if that affected.

### Steps to reproduce

**Unstable**
1. Start wt, keep only one wt process alive.
2. Switch window from wt to others, click taskbar icon to minimise it and restore, as a simulation of regular situation to use wt with other tools, until the window of wt disappeared. This might take from a few minutes to almost half an hour.

### Expected Behavior

The window of wt showed normally.

### Actual Behavior

The window of wt disappeared and can not be recovered.
1. **Press Win + Tab to switch to the wt**: nothing happened.
2. **Left-click on the taskbar icon**: nothing happened.
3. **Right-click on the taskbar icon**: the right-click menu popped.
4. **Hover on the taskbar icon**: the preview window popped.
5. **Hover on the preview window**: the window menu poped, but the `Restore` item is disabled, other operation like `Move`, `Maximise` does not work neither.
6. **Left-click on the taskbar icon and the press Alt + Space**: the window menu poped, but the `Restore` item is disabled, other operation like `Move`, `Maximise` does not work neither.
7. **_KEY POINT_** Start another wt process, with shortcuts or right-click menu or any other ways, then we got two window of wt. We can see two preview window when hover on the taskbar, but the old one still closed while the new one works fine.
    1. Close the new one, the old one might restore.
    2. Keep the new one and hover on the preview window of old one and right-click, choose `Restore`, the old one will be certain to recovered.
    3. But there are still other issues after we restore wt as above, such as we can only restore the wt window but not minimise it by left-click taskbar icon.

**Comment by Psyveira** [comment]
I can confirm this bug, I had to close the Terminal several times every day last week.
Hope this can be fixed soon since it's annoying if you need to close a terminal with a running process in it.

**Comment by zadjii-msft** [comment]
Please refer to the pinned issues at the top of the repo.

/dup #13589
