### ISSUE TITLE
After exporting WSL from C: drive to D: drive, WT logs in as root, but it has nothing inside of it. 

### ISSUE THREAD

**Issue by dddictionary** [microsoft/terminal#13747]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044

### Steps to reproduce

Used [this](https://blog.iany.me/2020/06/move-wsl-to-another-drive/) website to export/import wsl from C: drive to D: drive. Doing this led to WT not recognizing Ubuntu/logging me in a root. 

```
cd D:\
mkdir WSL
cd WSL
wsl --export Ubuntu ubuntu.tar
wsl --unregister Ubuntu
mkdir Ubuntu
wsl --import Ubuntu Ubuntu ubuntu.tar 
```
Went into `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` to change the `DefaultUid` value from 0 to 1000 (decimal). 

If I go into powershell and run `wsl -d Ubuntu` everything launches fine and my files/data is all there. 

### Actual Behavior

After all of this, launching WT throws me into this
![wetweatget](https://user-images.githubusercontent.com/86024593/184726918-28a4a4f9-28e4-412b-bef5-a725b39fe6f5.png)
which has no files inside of it. Essentially, it does not log in as my user and direct me to `/home/<user>` as it did before.

**Comment by DHowett** [comment]
I'm sorry, this repository can only help you with Windows Terminal issues. For WSL help, I'll have to direct you to [the WSL repository](https://github.com/microsoft/wsl).

Thanks.
