### ISSUE TITLE
 Customized font for Chinese characters like VS Code

### ISSUE THREAD

**Issue by garymaxallen** [microsoft/terminal#13755]
# Description of the new feature/enhancement

This is my Windows Terminal font setting
![image](https://user-images.githubusercontent.com/10022333/184823278-88c5e2c7-e757-43f7-a1fb-3c99ed201700.png)

This is how it displays Chinese characters. (very ugly)
![image](https://user-images.githubusercontent.com/10022333/184823405-71c8fc90-9a3a-4ab0-830a-48fda7e98e7d.png)

This is my VS Code font setting
![image](https://user-images.githubusercontent.com/10022333/184823667-e7a6c384-02e9-4cce-aaec-c7a6e3d9a329.png)

This is how it displays Chinese characters
![image](https://user-images.githubusercontent.com/10022333/184824188-32474612-d99d-4d0a-a7e7-82adcf49b9b9.png)

So, is there a hidden setting in Windows Terminal that can do the same as VS Code or not?

# Proposed technical implementation details (optional)
 Customized font for Chinese characters like VS Code

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2664 for more discussion.

/dup #2664
