### ISSUE TITLE
"清除缓存区"后光标位置异常

### ISSUE THREAD

**Issue by ejums** [microsoft/terminal#13764]
### Windows Terminal version

1.14.1963

### Windows build number

10.0.22000.0

### Other Software

nothing

### Steps to reproduce

step1:  Add hot key 'F7' map to "clear cache area"
![image](https://user-images.githubusercontent.com/49144229/185076239-e37dd783-7d13-4039-b1e3-58cfc3b2db99.png)
step2: Type command "netstat -ano" 
![image](https://user-images.githubusercontent.com/49144229/185076197-04d2e40c-3de7-43ab-a861-7b15454148ac.png)
step3: Press F7 to clear cache area
![image](https://user-images.githubusercontent.com/49144229/185076325-a9914fc1-91ea-4b6a-bbd0-8d9daf8035ee.png)
step4:  type any, the cursor position isn't right
![image](https://user-images.githubusercontent.com/49144229/185076426-16955aac-3a04-476c-8f00-729fb671c3e4.png)

### Expected Behavior

the cursor isn't right when clear cache area
![image](https://user-images.githubusercontent.com/49144229/185076709-3b719814-ea41-4fc4-a3cd-6f891245d568.png)

### Actual Behavior

Hope the cursor is normal after clearing the cache

**Comment by zadjii-msft** [comment]
Thanks for the report! As noted in #11592: 

> PowerShell caches the cursor position every time it displays the prompt, and then after we reset the screen it _moves the cursor back_. This is effectively a /duplicate of https://github.com/PowerShell/PSReadLine/issues/964
