### ISSUE TITLE
Windows Terminal cannot open after install last update ("not designed to run on Windows", `0xc0000045`)

### ISSUE THREAD

**Issue by javlaks** [microsoft/terminal#13774]
### Windows Terminal version

Win11_1.14.2282.0

### Windows build number

Microsoft Windows [Version 10.0.22000.856]

### Steps to reproduce

Install the lastest version (Win11_1.14.2282.0) in a windows 11 machine

### Expected Behavior

Install successfully the Microsoft.WindowsTerminal_Win11_1.14.2282.0_8wekyb3d8bbwe.msixbundle in a Windows 11 machine and open the Terminal

### Actual Behavior

The installation completes well, but when I try to open the Terminal, I see the following error:
![image](https://user-images.githubusercontent.com/513351/185434715-105d16dd-ae0e-46c2-b618-aa3e760de1f7.png)

**Comment by zadjii-msft** [comment]
um _what_. @DHowett ‼️ I've never seen anything like this. 

Is it cause we have a dependency on 2.7.3, but that's not rolled out yet? I literally have no idea.

**Comment by DHowett** [comment]
UH WHAT

MUX isn't linked by ordinal (or at all actually... it's all loaded at runtime)

**Comment by zadjii-msft** [comment]
OKAY WHAT DOES THIS MEAN


@javlaks I know this sounds stupid, but can you back up your settings and reinstall? Maybe it just botched the install?

**Comment by DHowett** [comment]
Do you happen to have any higher security features enabled?

**Comment by javlaks** [comment]
> Do you happen to have any higher security features enabled?

Yes, the computer have some security options enabled by the company, but the weird thing is that previous versions work fine in the same computer, only the latest gives me this error

**Comment by zadjii-msft** [comment]
Note: Presumably there are weird bits set on a page in the DLL giving it invalid permissions (like, write+execute), but _what_, that should never happen. 

If we did ship a binary that got compiled wrong, I'm sure we'll hear a _lot_ more about in this thread soon 😨

**Comment by DHowett** [comment]
No significant difference in DLL headers:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/189190/185455279-6df1251f-6d18-4ed9-9e80-492ea9e59489.png">

I wonder if it _could_ be an error coming out of loading MUX.dll...

**Comment by DHowett** [comment]
@jvlaks do you happen to know which settings they've enabled?

Would you be able to check this one in the Advanced System Properties?

<img width="617" alt="image" src="https://user-images.githubusercontent.com/189190/185459107-ae4387ec-45e6-4c72-a3f8-19e2e82aa2ab.png">

**Comment by javlaks** [comment]
This is why I see, @DHowett 
![image](https://user-images.githubusercontent.com/513351/185460689-83305d23-98e1-4940-8ffa-a0a875e3f653.png)

**Comment by DHowett** [comment]
_Crap._

How about this, from PowerShell?

```
get-ciminstance win32_operatingsystem | fl DataExecution*
```

**Comment by javlaks** [comment]
Here is it 
![image](https://user-images.githubusercontent.com/513351/185464645-91ec241b-780c-4c9b-b7b3-31bfc74ae4b1.png)

**Comment by zadjii-msft** [comment]
Huh, that's what I'd expect there. Any chance this just went away/? I don't know if we had any leads left, to be honest. And we haven't heard any other similar reports since. I legit have no idea what this could be other than cosmic bit flip.

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
