### ISSUE TITLE
TODO: [MSFT:4586207] Clean up CommandLine::ProcessCommandLine -- needs helpers.

### ISSUE THREAD

**Issue by ChristophePichaud** [microsoft/terminal#1377]
# Summary of the new feature/enhancement
This code requires functions (helpers) and better wrtiting style.
Issue idea comes from source code of cmdline.cpp line 582 and a TODO MSFT comment.

# Proposed technical implementation details (optional)
../..
    switch (wch)
    {
    case VK_ESCAPE:
        OnKeyEscape(cookedReadData, true);
        break;
    case VK_DOWN:
        OnKeyDown(cookedReadData);
        break;
../..

MSFT:4586207

**Comment by DHowett-MSFT** [comment]
Please be careful when looking at this area. It's one of the more difficult areas in conhost, and it can impact application compatibility pretty heavily.

**Comment by ChristophePichaud** [comment]
Does it means I can try on a dedicated branch or I need to explain more things ?
Looking at the code is not so tremendous difficult. It's a central and nervous point yes, but not so difficult to handle. Correct me if I'm wrong.
