### ISSUE TITLE
Terminal update from store closes terminal and detaches all consoles

### ISSUE THREAD

**Issue by ukdocCT** [microsoft/terminal#13770]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Other Software

No other software, issue is with terminal itself.

### Steps to reproduce

Terminal has been installed on my laptop from the Microsoft store.
When an update flows through the store it appears to close off my running terminal, will several tabs open, and then installs.
The running consoles become detached.

When i start the terminal again the consoles are not reattached.

I then have to kill all the consoles i was running and relaunch them. This sometimes means code that i have been running in powershell or WSL needs to be rerun.

### Expected Behavior

Prompt to close the terminal app for the install, or install in the background and switch to the new version on next launch of terminal (dont know if this is even possible with store delivered apps), or reattach to the consoles (i know that this one is likely to be near impossible as you will not be able identify the old consoles).

### Actual Behavior

terminal closes and all running consoles are detached from the terminal meaning they have to be killed from taskmgr.

**Comment by zadjii-msft** [comment]
What _precisely_ were you running that got detached/? I'm under the impression that anything running in the foreground should still act as though the running console window was closed and shut down accordingly [1]. 

Largely, we're tracking this in #3915 and more specifical to the "orphaning" you're seeing here, #9914. I believe we have a fix for the orphaning that went out in https://github.com/microsoft/terminal/releases/tag/v1.15.2282.0 (though, that won't really work until 1.16 comes out).

I think I'm gonna leave this open for now, to try and get at whatever is being orphaned here, but I'll probably dupe this to #9914.

[1]: The caveat of course, is anything running in the BG of that console, isn't gonna get a detach message.

**Comment by ukdocCT** [comment]
The comments on #9914 is exactly the problem i am having with orphaned consoles. 

I have read the comments on #9914 and #13614 and am not sure that having all the open consoles closed out rather than orphaned is any better than the current situation.

Although this is only one crash per user, and for home users perhaps not too important, for those of us that find terminal invaluable in their work situation, coming back to my laptop overnight and finding all my sessions unusable is more than inconvenient, it has broken several of our long running processes, so much so that i now have to run them in separate powershell or WSL sessions outside terminal. A situation i'm not happy with as i love using terminal, but i don't have a choice if i want to ensure that i can check my scripts the following day.

I have added a comment on #9914 so am happy for this one to be closed and i will track it on that issue.

**Comment by zadjii-msft** [comment]
We're still really trying to work with the Store team here to let us request not being killed for an update. Alas, there's still a lot of work to do here. I think that's the resolution really everyone wants 😓
