### ISSUE TITLE
Can't display tab character, tabs auto convert to spaces.

### ISSUE THREAD

**Issue by RaoTianlong** [microsoft/terminal#13783]
### Windows Terminal version

1.12.10982.0

### Steps to reproduce

echo -e "a\tb"

### Expected Behavior

display a tab character between 'a' and 'b'.

### Actual Behavior

display 7 spaces between 'a' and 'b'.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7810  for more discussion.

/dup #7810
