### ISSUE TITLE
Spawn a new tab in same directory as previous directory.

### ISSUE THREAD

**Issue by lencil** [microsoft/terminal#13780]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
* Please search before filing new issues
* Please don't file blank issues
* This is already possible today, here are the docs: [Tutorial: Opening a tab or pane in the same directory in Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory)
