### ISSUE TITLE
Provide API to access Console name (e.g. /dev/cons1) from a PseudoConsole handle

### ISSUE THREAD

**Issue by sullivan-sean** [microsoft/terminal#13788]
# Description of the new feature/enhancement

It would be convenient to provide an API to access the name of a console from a handle (e.g. `/dev/cons1`) similar to the `ttyname` function on unix (https://linux.die.net/man/3/ttyname_r) for cross-platform applications that reference tty name.

I couldn't find any documented way of doing this or any similar issues, but apologies if there is an existing solution or duplicate issue.

**Comment by zadjii-msft** [comment]
ConPTY instances don't really have unique names at the moment. We'd have to come up with something arbitrary to have them return. 

Do you have a specific example in mind/? If we're gonna design something similar, I'd love to have a reference bit of e2e code so we can actually design appropriately for the scenario.
