### ISSUE TITLE
[quake mode/full screen window] automatically showing tabs row and window title bar

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#13798]
# Description of the new feature/enhancement

Showing the tabs row and window title bar automatically on hovering the top border of the quake window/full screen window for a small time of seconds.  (Like in ms edge full screen windows.)

_Alternatively you can show the command palette/input._

# Proposed technical implementation details (optional)

_nothing_

**Comment by 237dmitry** [comment]
These modes are designed to hide the controls. You can use hotkeys to open the menu, switch between tabs, or open the command palette.

![Screenshot 2022-08-21 093655](https://user-images.githubusercontent.com/78153320/185779876-59488eb6-b47f-45fd-be0e-e15bceabd11d.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #5677 for more discussion.

/dup #5677

There's more focus mode follow ups in #3486
