### ISSUE TITLE
Weird Black Dot Appearing in Upper Left Corner

### ISSUE THREAD

**Issue by lvlzyro** [microsoft/terminal#13790]
### Windows Terminal version

1.14.2282

### Windows build number

22621.382

### Steps to reproduce

I only open the app and there it is. I restarted the app, computer itself but nothing helped.

### Actual Behavior

There is a weird black dot in the upper left corner when I open the app. Here is a screenshot of it.

![terminal_bug](https://user-images.githubusercontent.com/45663782/185742581-b9397f8f-eef2-4357-9da0-d2cd97349877.png)

ps: this only happens in windows terminal.

**Comment by lvlzyro** [comment]
Apparently it was just MicaForEveryone. Fixed it by playing in it's config files.

**Comment by lvlzyro** [comment]
Yeah, sadly did not fixed my problem too. I've set all to false but MFE crashed after a while and I had to change settings to what you did which made the punch hole come back. I created an issue in MFE repo, can you follow that and add a message, maybe they'll respond faster?

**Comment by zadjii-msft** [comment]
FWIW I think this is just a variant of #13640
