### ISSUE TITLE
Difference between full screen, focus mode and quake window

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#13799]
What is the difference and correct usage of the follwoing window types:
- full screen window
- focus window
- quake mode window

For me the full screen window looks the same as an fokus window except that a fokus window is not on the full screen. Both have not tab row, title bar and window border. Here is a screenshot of wt after enabling the "focus mode":
![image](https://user-images.githubusercontent.com/61519853/185761509-12bf294e-dfcb-4738-8663-0da01dfd356e.png)

If I choose "Show/hide quake window" in the command palette on a normal window, nothing happens. Same on a quake window.
![wt-quake-command](https://user-images.githubusercontent.com/61519853/185761724-b5a42da4-f715-4540-9e8c-8bf478b441ee.gif)

**Comment by zadjii-msft** [comment]
Moved to https://github.com/MicrosoftDocs/terminal/issues/573
