### ISSUE TITLE
"wt -v" creates empty DesktopWindowXamlSource window

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#13797]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044

### Steps to reproduce

type `wt -v` in windows terminal window.

### Expected Behavior

No empty `DesktopWindowXamlSource` window.

### Actual Behavior

Having an empty `DesktopWindowXamlSource` window.

![image](https://user-images.githubusercontent.com/61519853/185760663-dc58cc09-5193-48cf-8c2d-380f24a4823d.png)

**Comment by htcfreek** [comment]
Maybe similar to #11706.

**Comment by zadjii-msft** [comment]
You know what, the root cause for both these is /dup #6507, thanks!
