### ISSUE TITLE
Supported ANSI escapes - authoritative list

### ISSUE THREAD

**Issue by parkovski** [microsoft/terminal#138]
I wrote ANSI escape handling for PSReadLine on Windows and it involved a good amount of `showkey -a`. Currently adding `^[[Z` because I know that’s supported now, but I’m not sure if there have been any other changes. Can we either get updated docs with all supported escapes or a terminfo page?

**Comment by zadjii-msft** [comment]
Are we talking about as input to a client, or as output from a client application?

There is [This MSDN page](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences), but I don't know if I've updated it since Creator's Update.

I can add a backlog item to myself to update that page. We're pretty quickly building up a documentation backlog (*cough* @bitcrazed )

**Comment by parkovski** [comment]
For the purpose of PSReadLine, input is all that matters (what escape does it generate for a given key?), but I imagine other people would be interested in the rest, especially with upcoming PTY support.

I think the main things the list left out were around which keys supported Alt/Shift and their sequences (the F keys, PgUp, etc, but not Delete, for example), can't remember if there was anything else.

**Comment by miniksa** [comment]
Now that the code is opened, I would love to have someone help us update the documentation here.

If someone can help update the documentation and build a beautiful table of what we support, I can provide assistance by spelunking the history that you all cannot see to find when each sequence showed up as being supported.

**Comment by oising** [comment]
I was talking with @jaykul about this the other day -- building a nice excel style table of support ops. Assign to me and I'll take a crack at it this weekend (I'm nearly done the other issue for install doc - its been a long week for me)

**Comment by zadjii-msft** [comment]
Hey so this has been open for some time now. I think we made this a lot better with #1884. We're tracking further updates to these docs in https://github.com/MicrosoftDocs/terminal/issues/350, https://github.com/MicrosoftDocs/Console-Docs/issues/91 and https://github.com/MicrosoftDocs/Console-Docs/issues/243. (some of those should also be de-duped)

Thanks all!
