### ISSUE TITLE
latest stable channel windows terminal creates weird black rectangle when starts up, changes location when minimized.

### ISSUE THREAD

**Issue by seanmamasde** [microsoft/terminal#13800]
### Windows Terminal version

1.15.2284.0

### Windows build number

10.0.22622.0

### Other Software

As of now, only windows terminal makes this weird thing. A list of what I have tried / noticed (could be potential reasons for the issue):

1. tried toggle on/off acrylic tab row
2. tried toggle on/off always show tabs
3. tried toggle on/off hide the title bar
4. since I am using [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone), I though it might be where this bug came from, I set up a specific process rule for it, and it does not help.
5. I am on Windows insider beta channel, latest build.
6. I haven't tried terminal preview yet, will try if someone wants to see it in action (not sure whether it will solve or not)

Here's a screen recording for better understanding (black rectangles appears at left-top amd left-bottom of the screen):

https://user-images.githubusercontent.com/85484530/185779074-1cb38732-826b-415b-973a-3481eb4639bf.mp4

### Steps to reproduce

Just fire up your windows terminal.

### Expected Behavior

Don't make those black rectangles.

### Actual Behavior

It creates black rectangles.

**Comment by j4james** [comment]
Are you using [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone) by any chance? Because someone raised a issue recently that sounds very similar to this, and they fixed the problem by changing something in their MicaForEveryone config (see #13790).
