### ISSUE TITLE
Can't Reopen minimized Terminal from the Taskbar

### ISSUE THREAD

**Issue by StefanGreve** [microsoft/terminal#13803]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Other Software

PowerShell 7.2.5

### Steps to reproduce

1. Open WT and pin app to task bar
2. Minimize WT with the buttons on the top-right corner of the window
3. Confirm that WT still opens up (not necessary for step 4 and 5, just to acknowledge that this error occurs only in a very specific way)
4. Now, this time click on the icon in the taskbar to minimize WT
5. Click on the WT icon again to bring back focus to WT

### Expected Behavior

WT should be able to minimize and maximize from the taskbar.

### Actual Behavior

WT is still running in the background, and hovering over the icon in the taskbar reveals the window preview indicating that the application is still alive but after running through step 4 and step 5 it's impossible to use WT without restarting the application. I noticed this error first in the preview version of 1.14 (which is now mature), and it didn't happen to me in any prior versions of WT.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #13589 for more discussion.

/dup #13589

This is fixed in https://github.com/microsoft/terminal/releases/tag/v1.14.2281.0
