### ISSUE TITLE
[New tab]: Voice Access users are not able to access 'New Tab' dropdown icon control using 'Show Numbers' command. 

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#13804]
### Windows Terminal version

1.15.2003.0

### Windows build number

10.0.25179.1000

### Other Software

**Test Environment:**
OS: Window 11 22H2 OS Build 25179.1000
App: Windows Terminal Preview
AT: Voice Access

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Voice Access AT.
3. Use 'Show numbers' command on command area and observe the issue.

**User Experience:**
People with limited mobility who use Voice Access will have bad UX as they have to use mouse grid to access buggy control which take more time to access as show numbers are not working.

**Guideline Reference:**
EN 301 549 V3.2.1: 11.06.02 No disruption of accessibility features

**Attachments:**
[Voice Access users are not able to access 'More Options' dropdown icon control using 'Show Numbers' command.zip](https://github.com/microsoft/terminal/files/9393841/Voice.Access.users.are.not.able.to.access.More.Options.dropdown.icon.control.using.Show.Numbers.command.zip)

Attachment Note: Not able to inspect Terminal Preview app with AI and Inspector tool. 

### Expected Behavior

Numbers should appear on 'New Tab' dropdown icon control using 'Show Numbers' command. 

### Actual Behavior

Voice Access users are not able to access 'New Tab' dropdown icon control using 'Show Numbers' command. 

Observation:
1. Voice Access users can access buggy control using 'Show Grid' or keyboard shortcut commands.

To learn more about Voice Access and how an application can support its different modes, Refer https://www.osgwiki.com/wiki/VoiceAccess_Testing

Voice Access Commands page: https://sway.office.com/Q5JvoIGBI5glyoKw?ref=Link

**Comment by zadjii-msft** [comment]
_who wants to bet that this is a WinUI issue and `SplitButton` just won't work with Show Numbers_

**Comment by carlos-zamora** [comment]
Yup, this is a XAML bug. Filed it here: https://github.com/microsoft/microsoft-ui-xaml/issues/7818

Tagging this bug as an external bug.

CC @v-rpundir

**Comment by v-rpundir** [comment]
VSO Tracking ID: [Bug 41849634](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/41849634): [XAML Controls Gallery -> TabView]: Voice Access users are not able to access 'New Tab' dropdown icon control using 'Show Numbers' command.

**Comment by carlos-zamora** [comment]
Closing now that the bug has been accepted.
