### ISSUE TITLE
[Settings]: Voice Access users are not able to activate 'Launch Size' dropdown control and other similar controls throughout Terminal app using 'Show Numbers' command.

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#13807]
### Windows Terminal version

1.15.2003.0

### Windows build number

10.0.25179.1000

### Other Software

**Test Environment:**
OS: Window 11 22H2 OS Build 25179.1000
App: Windows Terminal Preview
AT: Voice Access

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Voice Access AT.
3. Open Terminal Settings page.
4. Inside Startup page, Use 'Show numbers' and 'Click <control name>' command and observe the issue.

**User Experience:**
People with limited mobility who use Voice Access will have bad UX as they are not able to use expandable control using 'click' and 'show numbers' commands.

**Guideline Reference:**
EN 301 549 V3.2.1: 11.06.02 No disruption of accessibility features

**Attachments:**
[Actual and Note Issue.zip](https://github.com/microsoft/terminal/files/9394127/Actual.and.Note.Issue.zip)

Attachment Note: Not attached Code Snippet as not able to inspect Terminal Preview app with AI and Inspector tool.

### Expected Behavior

Numbers should appear for 'Launch Size' dropdown control and other similar controls throughout Terminal app using 'Show Numbers' command.

**Note Issue Expected: ** 'Click control name' Commands should work with 'Launch Size' dropdown control and other similar controls throughout Terminal app

### Actual Behavior

Voice Access users are not able to activate 'Launch Size' dropdown control and other similar controls throughout Terminal app using 'Show Numbers' command.

**Note Issue:** 'Click control name' Commands is not working with 'Launch Size' dropdown control and other similar controls throughout Terminal app

**Observation:** Voice Access users can access buggy control using 'Expand', 'Show Grid' and keyboard shortcut commands.

To learn more about Voice Access and how an application can support its different modes, Refer https://www.osgwiki.com/wiki/VoiceAccess_Testing

Voice Access Commands page: https://sway.office.com/Q5JvoIGBI5glyoKw?ref=Link

**Comment by carlos-zamora** [comment]
This is a XAML bug as it repros in the WinUI 2 Gallery. I've filed the following bug on their repo: https://github.com/microsoft/microsoft-ui-xaml/issues/7817

Tagging as tracking external.

**Comment by carlos-zamora** [comment]
Closing now that the bug has been accepted.
