### ISSUE TITLE
Terminal crashes when settings.json is blanked.

### ISSUE THREAD

**Issue by marekr** [microsoft/terminal#13802]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Click the Settings page option in Terminal
2. Click Open JSON file button
3. Delete the contents of the json file in your text editor
4. Save the file in your text editor

### Expected Behavior

Not sure, just not a crash

### Actual Behavior

Terminal crashes with the following event viewer entry

```
Faulting application name: WindowsTerminal.exe, version: 1.14.2207.15002, time stamp: 0x62d1f0dc
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1889, time stamp: 0xe9ede6d6
Exception code: 0xc000027b
Fault offset: 0x000000000010fb62
Faulting process id: 0xc6d4
Faulting application start time: 0x01d8b5b854bf6c02
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.14.1962.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8b10e7e1-43e3-40bd-8b32-f34a5385e55a
Faulting package full name: Microsoft.WindowsTerminal_1.14.1962.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #13673 for more discussion.

/dup #13673
