### ISSUE TITLE
Blank screen for any profile

### ISSUE THREAD

**Issue by RadoslawT** [microsoft/terminal#13809]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

Open Windows Terminal, or new tab with any profile.

### Expected Behavior

To see a content of a shell.

### Actual Behavior

![terminal](https://user-images.githubusercontent.com/594534/185929757-f06c360d-c4bc-49c3-9575-0a90aa715004.jpg)

Content is invisible. I've tried to use legacy consol option in Windows PowerShell/CMD, but it didn't work. The preview in Settings > Defaults > Appearence is blank as well no matter what appearence settings are. I've tried to switch both Rendering settings, without result. This happens for Terminal appliaction and Terminal Preview application. When I execute some commands in such tab I can export text from the tab and the text file contains correct content of the tab and shows that everything was executed correctly.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

I'm betting that the color scheme is set to all black (for some reason)

**Comment by RadoslawT** [comment]
@zadjii-msft thank you for your response, here is the settings.json file: https://gist.github.com/RadoslawT/2a636b788b8f0f07fa23d55321591c7a
Path file: `C:\Users\*****\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`

**Comment by RadoslawT** [comment]
Yeah, these odd settings are due to my expriments to make this work. I've reinstalled the application but with no result and here is the settings file with just default settings: https://gist.github.com/RadoslawT/a36627f1ea36208c235165903aabb7af 
I've tried to change rendering settings testing every combination and restart the application each time after, but also without a result, screen is still black. Another interesting thing is that when I blindly select the whole text from the screen with the cursor I don't see any change, it's all black but when I copy it, it copies just fine.

**Comment by zadjii-msft** [comment]
Huh, even with software rendering? That's wild. That pretty much rules out GPU issues. 
 
Did this happen in previous versions of the Terminal/? Maybe we can try and narrow it to a recent regression, at least.

**Comment by RadoslawT** [comment]
Bingo, it was about my GPU. I have 2 GPUs Intel HD Graphics 3000 and Nvidia Quadro 1000M. I've played with BIOS settings, disabling Nvidia Optimus and enforcing to use Intel card only, and it worked. Performance is low and fonts look poor but it obviously shows that there is something wrong with my GPU drivers. Thank you for helping me @zadjii-msft
