### ISSUE TITLE
IME still has some issues

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13805]
I'm sorry for bringing this up again.
Thanks to the commit https://github.com/microsoft/terminal/pull/13678, the original issue is fixed in the latest version.
But recently, I've found that the new behavior is not very desirable. At least for me.
For example, when I'm in the middle of editing something in Hiragara mode then switch to a different application or make the Terminal lose focus. Then when the Terminal get focus again, the IME's input mode will be switched to Half-width alphanumeric.
It's not a bug, but kind of inconvenience. So may I request a setting to disable the new behavior?

v1.13.10983.0
![terminal-1 13](https://user-images.githubusercontent.com/76022206/185726935-88a09809-1710-45eb-a311-5b9c220a9e4f.gif)

v1.15.2282.0
![terminal-1 15](https://user-images.githubusercontent.com/76022206/185726945-13742f1e-477e-4b17-ba23-9863ec6f042f.gif)

I don't have other CJK languages installed, so it might happen with the Japanese MS IME only.

Also, I believe that the new behavior is causing ```alt + shift``` to not retaining the last used input mode as mentioned in https://github.com/microsoft/terminal/issues/13681.

v1.13.10983.0
![terminal-1 13-2](https://user-images.githubusercontent.com/76022206/185727113-e2acfac7-738d-4646-be60-540a4f3f093e.gif)

v1.15.2282.0
![terminal-1 15-2](https://user-images.githubusercontent.com/76022206/185727124-c701fece-719c-4983-9167-65072e2face0.gif)

_Originally posted by @rabianr in https://github.com/microsoft/terminal/issues/13398#issuecomment-1221222305_

**Comment by rabianr** [comment]
Thank you for creating a new issue for this. I thought it's related to the original issue so I didn't create a new one.

I just checked the discussion at https://github.com/microsoft/terminal/issues/12731. If I understand correctly, the intention of the patch is to switch IME input mode to Direct Input when user opens a new Terminal.
But this is already the default behavior of the Japanese IME before the patch. When I switch to Hiragana mode, then open a new Terminal, the input mode is switch to Direct Input immediately. Only when I switch to Hiragana mode in the Terminal then open a new Tab in the same window, then the new Tab will retain the Hiragara mode. But I think this should be expected.
I also couldn't find any setting to change the default input mode. So I think for the Japanese MS IME, Direct Input mode is set by default?
This behavior is the same with other applications too. E.g. Nodepad, Firefox, ...

Here is the demo with v1.13.10983.0
![terminal-1 13](https://user-images.githubusercontent.com/76022206/185928665-98ff601e-9231-4627-9eab-500fa2b55a35.gif)

**Comment by zadjii-msft** [comment]
For reference: we've now been monkey-patching our IME support for... probably too long. We're gonna follow up with some folks more directly involved with the IME implementation, and seek out a more holistic design here. They'll likely have a set of best practices we should actually follow that'll work across different languages and IMEs. Hopefully, we can stop trying to whack-a-mole these issues.

**Comment by SubaruArai** [comment]
For a short-term solution, having a option to turn off IME related things might be enough.
I mean, we've got thousands of languages across the globe - there will be certainly some that will cause issues.

**Comment by weiqi-chen** [comment]
![issue](https://user-images.githubusercontent.com/6562920/202912595-15286068-cbc0-464e-bc11-84eeeb79e88b.gif)

Microsoft never test before releasing its software...

**Comment by lhecker** [comment]
I think it's best to address this issue together with #14349, by unifying our two IME implementations.

**Comment by ccc-aaa** [comment]
I'm using Microsoft Chinese IME.
Adding my experience, the behavior that automatically switches to alphanumeric mode on focus bugs me because it would activate the IME even if I switched it off by using the old version of the IME.
It's annoying that when you accidentally pressed the shift key and your flow just broke because of the suddenly composition mode.
Let user decide whether to use this behavior or not would be better IMHO.

**Comment by lhecker** [comment]
We just published a major update to our IME implementation in the nightly Canary branch. It was rewritten from the ground up and has tons of improvements! If you're interested in trying it out, you can get it here: https://aka.ms/terminal-canary-installer
If you already have the Canary build installed, you can use this link to force an update.

If you encounter any issues or have any suggestions, or if you simply like/dislike the changes, please let us know! Thank you for bearing with us. 😊
