### ISSUE TITLE
No longer accepts input after resize when running commands that pause for input.

### ISSUE THREAD

**Issue by AHoran** [microsoft/terminal#13819]
### Windows Terminal version

 1.14.1963.0

### Windows build number

10.0.22000.0

### Other Software

git version 2.37.1.windows.1
PowerShell 7.2.6

### Steps to reproduce

Within a git repository run a command such as `git log` that will return more than 1 page of data and pause.
`git log` will pause with a `:` prompt. 
Now resize the window, either maximise it, or if already maximised then shrink it.
You now cannot exit the git command, neither CTRL-C nor Q will let you exit.

### Expected Behavior

Expected to exit the git command and return to the powershell prompt.

### Actual Behavior

Stuck in git and cannot exit with any key-combo that I can think of.

**Comment by AHoran** [comment]
I did wonder if it was `oh-my-posh` or `posh-git` which I have installed. However I can replicate the behaviour even when starting with `pwsh -noprofile`

**Comment by zadjii-msft** [comment]
Did you change your git pager config at all/? Did you recently update git? Is the whole Terminal application hung in this state, or just that one tab? (i.e. can you open new tabs?) Are you by any chance connecting to this computer over RDP?

Can you send a screenshot while the Terminal is in this state? Maybe there's something I can see there.

**Comment by AHoran** [comment]
My git install is out of the box, whatever Visual Studio installed, and then upgraded.
It happens for me on 2 different laptops, one win 10 and one win 11.

Only the one tab is impacted, and the tab remains responsive to resizing etc. ie text will flow.
But the cursor changes, and you can't type anything or exit from git.

Before:
![image](https://user-images.githubusercontent.com/3496701/186144683-e4d43fc4-b7e7-4317-a393-604feb970927.png)

Resize Window, then type `q`:
![image](https://user-images.githubusercontent.com/3496701/186144762-541ec5c4-6756-427b-b8ea-9a11a6d1d478.png)

The only visible change I can see is the cursor/prompt. I can close the tab (via the 'x' in the title bar), and I can open new tabs.

**Comment by AHoran** [comment]
```
❯ git config --global -l
user.name=Adam 
user.email=user@domain
❯ git config --system -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
❯ git config --local -l
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://zzz
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.power-automate.remote=origin
branch.power-automate.merge=refs/heads/power-automate
branch.power-apps-custom-connector.remote=origin
branch.power-apps-custom-connector.merge=refs/heads/power-apps-custom-connector
```

**Comment by elsaco** [comment]
This issue is reproduced with `alacritty` and `nu` shell also. It might be a `git` bug. However, `alacritty` is using `conhost` and the issue is the same when running `c:\Windows\system32\conhost.exe` directly. `git version 2.37.2.windows.2` used for testing.

**Comment by AHoran** [comment]
I've now read those reports in the git repo, and they do seem to describe the same problem.
Also https://github.com/git-for-windows/git/issues/3683 

I've also reproduced it on my machine outside of Terminal.

Happy to close this here as not a bug in Terminal and something to do with git.
Thanks for checking.

**Comment by TTT-3** [comment]
I'm using Git for Windows 2.37.1.windows.1 and have this exact problem. I realize this is closed but I just want to point out that when this happens, I can get my console back if I go kill less.exe. This may be a problem with less.exe specifically, which is my pager, instead of a Git issue.
