### ISSUE TITLE
Unable to open settings (profiles.json): ShellExecute in LaunchSettings returns ERROR_ACCESS_DENIED

### ISSUE THREAD

**Issue by brettfo** [microsoft/terminal#1381]
# Environment

```none
Windows build number: 10.0.18362.175 (1903)
Windows Terminal version (if applicable): 0.2.1715.0

Any other software? No
```

# Steps to reproduce

Open the settings file, either through the UI or via Ctrl+,

# Expected behavior

The settings file to open.

# Actual behavior

Nothing visible happens.

I built and debugged locally from the 0.2.1715.0 sources (66cb7c4b58b0e41ffaeb952ef27f1a8c67e90db8) and found that [ShellExecute in LaunchSettings](https://github.com/microsoft/terminal/blob/66cb7c4b58b0e41ffaeb952ef27f1a8c67e90db8/src/cascadia/TerminalApp/App.cpp#L440) was returning 5 (ERROR_ACCESS_DENIED according to winerror.h, line 265).  The value of `settingsPath` was properly formed (`C:\Users\brettfo\AppData\Local\Packages\WindowsTerminalDev_<some-garbage-characters>\RoamingState\profiles.json`) and the file exists on disk with the expected contents.

I also found the settings file corresponding to the app installed from the Store at `C:\Users\brettfo\AppData\Local\Packages\Microsoft.WindowsTerminal_<some-garbage-characters>\RoamingState\profiles.json` which is also correct and changed settings are appropriately reflected in the app.

**Comment by mithunshanbhag** [comment]
I too am facing the same issue. Please take a look at the attached screen capture gif below. 

Some additional details: 
1. Windows Terminal (preview) version 0.2.1715.0. Downloaded from the Microsoft Store. 
2. This issue also repro'es for me when I build the microsoft's terminal's github sources locally and launch the CascadiaPackage.
3. Window Insider Build: 10.0.18922.1000 (fast-ring)
4. I'm running Windows 10 on Macbook Air (4 proc, 8 GB RAM)

Please let me know if I can provide any additional details. 

![microsoft-terminal-issue](https://user-images.githubusercontent.com/2327905/59960789-33469580-94eb-11e9-8db0-469cbf6d7d72.gif)

**Comment by DHowett-MSFT** [comment]
I accidentally made #1460 the master issue for this, so.. here goes!
