### ISSUE TITLE
I can't change red color. Is this bug?

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#13828]
### Windows Terminal version

1.14.1962.0

### Windows build number

19044.1889

### Other Software

![demsg](https://user-images.githubusercontent.com/23658192/186140511-ce1c398a-ab28-45f2-84e3-bc0feb65406f.png)
I can't change red color in Windows Terminal.
As you can see, segmention fault error message is red color in Windows Terminal.
This red color is too dark. So, I chaged json file "red":"#FF0000" to "red":"#FFFFFF".

![white](https://user-images.githubusercontent.com/23658192/186141079-f14a13a6-b0c5-4269-a88b-bf87abfe0887.png)
I can't change more light colors like this.

### Steps to reproduce

I chaged json file "red":"#FF0000" to "red":"#FFFFFF" or "red":"#FFF000" or "red":"#FF1000" or "red":"#FF5000".

### Actual Behavior

Must change more light red.

**Comment by zadjii-msft** [comment]
I suspect they're printing text with the "faint" attribute set (see #6703). Which shell are you using/? I can whip up a quick test script to compare.

**Comment by zadjii-msft** [comment]
A very simple test:

```bash
printf "\x1b[31m_NORMAL_\x1b[m\n\x1b[2;31m_FAINT_\x1bm\n"
```

![image](https://user-images.githubusercontent.com/18356694/186142577-cf9d816e-fb39-4fa8-8467-0feeb8311e82.png)

(on a better background)
![image](https://user-images.githubusercontent.com/18356694/186142732-f7f7d85e-d94d-454e-b740-86494048d0d8.png)


So the application itself is likely just emitting text and specifically telling the Terminal "make this text fainter".

**Comment by CatCatCatDog** [comment]
> A very simple test:
> 
> ```shell
> printf "\x1b[31m_NORMAL_\x1b[m\n\x1b[2;31m_FAINT_\x1bm\n"
> ```
> 
> ![image](https://user-images.githubusercontent.com/18356694/186142577-cf9d816e-fb39-4fa8-8467-0feeb8311e82.png)
> 
> (on a better background) ![image](https://user-images.githubusercontent.com/18356694/186142732-f7f7d85e-d94d-454e-b740-86494048d0d8.png)
> 
> So the application itself is likely just emitting text and specifically telling the Terminal "make this text fainter".
> 
> EDIT: I see my typo now, it should be `\x1b[m\n` at the end but I'm gonna leave it instead of just taking new screenshots

Yeah, I think, This is faint text problem.
![제목 없음](https://user-images.githubusercontent.com/23658192/186149597-257cc866-b2cc-421b-8e65-8f901e4bd8e9.png)

**Comment by zadjii-msft** [comment]
There is no problem - we're obeying what the application told us to render to the screen. They wanted faint, we gave them faint. If you don't want that application to emit faint text to the terminal, you should probably file an issue/request with them 😉

**Comment by CatCatCatDog** [comment]
Okay :)
