### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ridiculousfish** [microsoft/terminal#1382]
Windows version 10.0.18362.175

Some early feedback. To set the tone, this is obviously a massive improvement and I am very excited for this new software. I'm making a monolithic issue since I am a first time filer, I am happy to break this out as you like.

Stuff that made me jump for joy:

1. ANSI escapes apparently work great, awesome.

2. Soft wrapping! Kudos, this is an important and painful thing to implement.

3. Soft wrapping + resizing? That's fantastic.

Stuff that can be better:

1. This was very hard to install. For a long time clicking the "Get" button on the Microsoft Store would depress and release, with no apparent progress. Windows Update claimed I was up to date. Eventually I found a different way to update (not sure what?) and then it installed correctly.

2. The window is too difficult to move. The drag area is not obvious, it appears to be only to the right of the tab +/arrow. Large parts of the titlebar are not draggable.

3. The window is difficult to resize from sides, and nearly impossible to resize from corners. The diagonal corner resize area is ~1 px which is far too small to hit reliably. 

4. The inactive appearance is too difficult to distinguish from the active appearance. For example Notepad dims the titles of inactive windows; Terminal looks almost the same in background and foreground.

4. Customization doesn't work for me. I choose Settings and it asks me "How do you want to open this file?"

5. Tabs with long titles have the close button obscured, and can't be closed.

6. The mouse doesn't work well. The cursor continues blinking even during mouse selection, there's no double click for word selection, no right click context menu.

7. Basic text selection operations don't work. There's no menu items for cut/copy/paste. Text selection drag and drop doesn't work. I cannot double click to control selection granularity.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the excitement here. We have a policy against “bucket” issues; would you mind upvoting existing issues covering your reports? Thanks.

**Comment by DHowett-MSFT** [comment]
(Oh, and, here’s the issues for your reports:)

Acquisition: yeah, we have had a lot of trouble with the store. That’s a story for another day. 

Window management: #929 #872 #564 we can get inactive state in there as well actually

Settings: probably #1381 

Tab titles: #608 #1320 

Selection: #1197 #988 #1273 we should file one for the cursor blinking (bonus: #1087)

I’ve seen drag and drop used in a word processor for moving blocks of text but never in a read-only scrollback buffer. Hmm..

**Comment by DHowett-MSFT** [comment]
(Also, the fish shell is awesome, and thanks for stopping by :))
