### ISSUE TITLE
[Settings]: Voice Access users are not able to activate 'Columns' and other similar controls throughout Terminal app using 'Click control name' and 'Show numbers' commands.

### ISSUE THREAD

**Issue by v-rpundir** [microsoft/terminal#13823]
### Windows Terminal version

1.15.2003.0

### Windows build number

10.0.25179.1000

### Other Software

**Test Environment:**
OS: Window 11 22H2 OS Build 25179.1000
App: Windows Terminal Preview
AT: Voice Access

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Voice Access AT.
3. Inside Settings> Startup page, Expand Launch Size control.
4. Then use 'Click control name' and 'Show numbers' commands and observe the issue.

**User Experience:**
People with limited mobility who use Voice Access will have bad UX as they have to use mouse grid to access buggy control which take more time to access as 'Click', 'show numbers' are not working.

**Guideline Reference:**
EN 301 549 V3.2.1: 11.06.02 No disruption of accessibility features

### Expected Behavior

When user give command 'Click Columns', 'Columns' edit field should get activated. 
When user give command 'Show numbers', 3 numbers should appear for each control and on saying each number respective control should get activated.

### Actual Behavior

When user give command 'Click Columns', 'Increase' icon control gets activated. 
When user give command 'Show numbers', 4 number is appearing on control instead of 3 and on saying first 3 numbers only 'Increase' icon button get activated.

**Observation:**
Voice Access users can access buggy control using 'Show Grid' or keyboard shortcut commands.

To learn more about Voice Access and how an application can support its different modes, Refer https://www.osgwiki.com/wiki/VoiceAccess_Testing

Voice Access Commands page: https://sway.office.com/Q5JvoIGBI5glyoKw?ref=Link

**Comment by v-rpundir** [comment]
**Bug Attachment:**
[Columns and rows.zip](https://github.com/microsoft/terminal/files/9400441/Columns.and.rows.zip)

Attachment Note: Not able to inspect Terminal Preview app with AI and Inspector tool.

**Comment by carlos-zamora** [comment]
This is a WinUI issue as the bug can be reproduced in the WinUI 2 Gallery.
I've filed this issue upstream here: https://github.com/microsoft/microsoft-ui-xaml/issues/7814

**Comment by carlos-zamora** [comment]
Closing now that the bug has been accepted.
