### ISSUE TITLE
NVDA reports selection changes when moving by character or line in mark mode

### ISSUE THREAD

**Issue by leonardder** [microsoft/terminal#13836]
### Windows Terminal version

1.15.2003.0

### Windows build number

22621.105

### Other Software

NVDA 2022.2.1

### Steps to reproduce

1. Open terminal
2. Press Ctrl+Shift+M
3. press left arrow

### Expected Behavior

NVDA says: `>`

### Actual Behavior

Nvda says: `>, > selected, space unselected`

**Comment by leonardder** [comment]
In Narrator the behavior is even worse, mark mode with up/down arrow is basically unusable

The underlying issue is likely as follows. When moving through a normal text editor with an UIA implementation, that impl only fires selection events when selecting with shift+arrows, with the mouse or something else that involves text selection. On the contrary, Terminal seems to fire selection events for cursor movement as well. IMO mark mode in Terminal should behave similar to conhost in that it *does not* fire selection events for cursor movement.

**Comment by leonardder** [comment]
CC @codeofdusk  @carlos-zamora

**Comment by zadjii-msft** [comment]
Pretty sure this is #13447?

**Comment by leonardder** [comment]
Yes, it is. Sorry for the duplicate. I should change my searching heuristics probably.
I will use the area accessibility label in the future.
