### ISSUE TITLE
Need a way to name each tab

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#1383]
# Summary of the new feature/enhancement

As of now, it shows title for each tab as something like `C:\...\powershell.exe` It will be useful to have a way to name each tab so that it becomes easy to recognize.

**Comment by blazejhanzel** [comment]
I think, the current names are to long too. I can display about 1,5 card tabs in small (default size) window. Custom will be great, but maybe cutting names will be good too? F.e. in, Ubuntu Terminal, displaying only last folder name, e.g. "System32" instead of "/mnt/c/WINDOWS/System32" 🤔

**Comment by DHowett-MSFT** [comment]
*please* search for existing issues. This one is #608
