### ISSUE TITLE
Vim status line should be redrawn

### ISSUE THREAD

**Issue by Mcbeany** [microsoft/terminal#13830]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Other Software

Neovim v0.7.2 (with PowerShell Core)

### Steps to reproduce

0. Open Neovim
1. Split the screen with `Ctrl + w`, followed by the letter `v`
2. Enter the second screen with `Ctrl + w` and `l`
3. Close that screen

### Expected Behavior

The status line should be redrawn

### Actual Behavior

![image](https://user-images.githubusercontent.com/77101686/186171021-3bcecff6-64be-4e4f-ae09-e7a12fc4f164.png)
A small part of the status line is not drawn

**Comment by zadjii-msft** [comment]
This is /dup #13229 which is fixed in https://github.com/microsoft/terminal/releases/tag/v1.14.2281.0
