### ISSUE TITLE
Cannot set a starting directory using linux subenv

### ISSUE THREAD

**Issue by NouaaTW** [microsoft/terminal#13834]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Steps to reproduce

just setting a starting directory doesn't work, it doesnt do anything and i'm still in the home folder

### Expected Behavior

i was just expecting it to works

### Actual Behavior

it doesn't work

**Comment by NouaaTW** [comment]
it does that with linux subenv

**Comment by zadjii-msft** [comment]
What profile are you using? Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

(I'm betting this is the `ubuntu.exe` issue, where `ubuntu.exe` always ignores `startingDirectory`)

**Comment by NouaaTW** [comment]
> What profile are you using? Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?
> 
> (I'm betting this is the `ubuntu.exe` issue, where `ubuntu.exe` always ignores `startingDirectory`)


here is the settings.json
https://pastebin.com/i9TfU88R

**Comment by NouaaTW** [comment]
i fixed it by editing the .bashrc file in home/user/ so it works know, but still ugly fix

**Comment by zadjii-msft** [comment]
Yep, okay, this is #12961. Change the `commandline` of that profile to `wsl -d Ubuntu-22.04` (or whatever `wsl -l` lists as the name of that distro). `ubuntu.exe` has a bug in it currently. 	

I'd take out the changes to `.bashrc` too, cause like you said, it's pretty ugly 😝 

/dup #12961
