### ISSUE TITLE
Right-click on File Explorer on Windows system to launch, the new environment variable is invalid

### ISSUE THREAD

**Issue by with-zeal** [microsoft/terminal#13835]
### Other Software

Windows 11

### Steps to reproduce

Create a new environment variable, right-click in file explorer on windows system to start Windows Terminal, try to execute the environment variable, but it is not valid.

### Actual Behavior

Right-click to start Windows Terminal in File Explorer on Windows systems, and the new environment variable is invalid, and the other way I know it works. After the computer restarts, file explorer right-clicks to start Windows Terminal.

**Comment by zadjii-msft** [comment]
Was another Terminal already running when you tried to launch the terminal that ultimately didn't have the new environment variable? I'm betting we bounced through the old instance, which didn't have the env var, and lost the updated value. 

I think this'll ultimately be fixed by #1125...
