### ISSUE TITLE
Command Snippets

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/terminal#13844]
# Description of the new feature/enhancement
Command Snippets to Make the Terminal Experience Seamless to Use, This feature works exactly same as Visual Studio Snippets or Other IDE's, In this Case We Have Shortcut to access a snippets flyout toolbar on Any Terminal or We can have different Snippets for Different Terminals.

This Feature Would Make Users More Productive Instead Typing the Same Terminal Commands Again and Again Since the Terminal History Keeps Executed Commands at least amount

https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets?view=vs-2022

# Proposed technical implementation details (optional)
Create a Local Data Store and Keeps the Snippets in Check and When User Access the Snippets via Shortcut, We can launch small flyout based WinUI to Shows the Snippets Title and When user selects the Snippets, Terminal would automatically paste the command for that snippets

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1595 for more discussion.

/dup #1595
