### ISSUE TITLE
Terminal Preview: No longer able to launch (Admin) profile tab from non-admin Terminal

### ISSUE THREAD

**Issue by tbakrf** [microsoft/terminal#13849]
### Windows Terminal version

1.15.2283.0

### Windows build number

10.0.22000.0

### Steps to reproduce

When Terminal Preview was first released you could go into settings, copy a profile (e.g. Windows Terminal) and click the "run as administrator" toggle.  At that point if you launch Terminal Preview, then choose the (admin) version, UAC comes up, and you authenticate and the admin version appears (separate instance).   Recently this has started failing - no Admin version comes up and/or you get a WindowsTerminal.exe application error: "The application was unable to start correctly (0xc0000142)"

### Expected Behavior

Expecting the option to chose the cloned profile with just the "run as administrator" toggle to launch UAC / launch a UAC instance of [profiles]

### Actual Behavior

After UAC elevation nothing happens or 0xc0000142 application error (for new tab/ existing Terminal launches fine)

**Comment by zadjii-msft** [comment]
Is your admin account the same as your regular user account? 

Can you share a screenshot of the `0xc0000142` error dialog? That might enlighten as to which process in this whole setup is actually the one that's failing to start. 

Does launching the Terminal elevated via the taskbar
![image](https://user-images.githubusercontent.com/18356694/186685557-445355ff-bc58-416d-a6c7-f29a0f79c42e.png)
still work/?

**Comment by tbakrf** [comment]
Background: I had originally installed the preview version because non-preview originally lacked the run as admin setting for the profiles.
I have both apps now.

On Non-Preview:
New profile based on (ex.) PowerShell, just modify the profile name, toggle the "Run this profile as Administrator"
[cid:15499c25-15fa-4f11-8cef-7993fab5fef1]
Launch Terminal (not elevated), when you need an elevated session, call a new tab for the admin version of the profile you just made:
[cid:c597bca0-3dea-498d-9374-286a4d12e637]
UAC prompt appears (I have a separate admin account) - after filling in, 0xc0000142 error comes up:
[cid:383f3a67-1b25-43f2-b387-f66fe26c9cb0]

Terminal Preview:
All the exact same steps as above - this worked fine until recently:
After the UAC prompt, a new, separate Windows of Terminal Preview would come up under the [UAC elevated account used] on same local desktop.
Now (within the past couple weeks max) no new instance launches (but also no error comes up telling you why it's not launching)


Both versions:
I can bypass this issue by launching (either) app itself directly as an admin (while under my non-admin Windows account):

[cid:8dee3d04-2cc3-4d18-b510-013697dfe837]
[go through UAC as my separate admin account creds]
[cid:23bd8b36-612b-4858-a2b7-ae1893c695ff]

It's not the end of the world to launch a totally separate instance of Terminal to get elevated session tabs versus calling the admin version from a non-Admin Terminal; I'm just reporting because it was working under Preview before within the profiles for whatever reason.  Maybe how Windows store handles the users separately...


Thanks!





Todd Biggins
Applications Management

***@***.******@***.***> | www.akrf.com<https://www.akrf.com/> <https://www.akrf.com/>
440 Park Avenue South, 7th Floor, New York, NY 10016



________________________________

**Comment by zadjii-msft** [comment]
(@tbakrf I think you may have tried to reply via email, with some images in the body of the mail, but I think GH stripped those out)

**Comment by tbakrf** [comment]
> (@tbakrf I think you may have tried to reply via email, with some images in the body of the mail, but I think GH stripped those out)

My bad - hopefully edited version now works!

**Comment by tbakrf** [comment]
*In the end I can still call a separate standalone Terminal elevated, so if you see this as a non-issue I'm fine.  I'm not sure if the run as administrator was originally / only intended for elevating under same user - just reporting that it did launch the separate one until recently.  Thanks folks for reviewing!

**Comment by tbakrf** [comment]
Circling back - testing from another machine, it looks like you have to manually have signed in as the other admin account user's desktop profile to install it under that desktop, prior to being able to UAC launch that other user instance.  Must be a Microsoft Store limitation?  If there's a way to install for all users on same workstation it would be a big help.

**Comment by zadjii-msft** [comment]
Ah alrighty okay, this is /dup #4217. Thanks for all the details!

**Comment by BriceJamin** [comment]
Hello, I have the same issue.

I am a normal (non root) user, launch terminal, click here
![image](https://user-images.githubusercontent.com/3600741/187640159-84af68da-a427-459b-acbe-0bc3d5389a19.png)
Then by right cliking on a profile I see I can launch it as admin
![image](https://user-images.githubusercontent.com/3600741/187641797-4ee41baf-9cef-4673-9480-27b0c5c1834e.png)
I try it
A new window ask me for admin password
![image](https://user-images.githubusercontent.com/3600741/187641545-d99e0ed2-fb33-461d-927e-1e8a85a5342b.png)
Then I get that error
![image](https://user-images.githubusercontent.com/3600741/187641652-81891d82-57b6-45cd-be7c-8d7cb439ec0a.png)
`---------------------------
WindowsTerminal.exe - Erreur d’application
---------------------------
L’application n’a pas réussi à démarrer correctement (0xc0000142). Cliquez sur OK pour fermer l’application. 
---------------------------
OK   
---------------------------
`

To answer to @zadjii-msft 

> Does launching the Terminal elevated via the taskbar still work/?

I can't do that, I only can click on "Open" :
![image](https://user-images.githubusercontent.com/3600741/187642467-0eb80adc-d148-4cc6-afb5-21eb6a24048e.png)

**Comment by BriceJamin** [comment]
If this is not an issue, I think than removing the message "Ctrl + Click" and removing this feature when you are not admin can be proper than raising an error.
