### ISSUE TITLE
Open new shells in new tab.

### ISSUE THREAD

**Issue by fluentmoheshwar** [microsoft/terminal#13843]
# Description of the new feature/enhancement

I start PowerShell from Start Menu then start cmd from start menu.

## What I want

CMD opens a new tab then opens in there.

## What happens

CMD starts a new terminal.

**Comment by zadjii-msft** [comment]
You'd be interested in: [`windowingBehavior`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#new-instance-behavior)
