### ISSUE TITLE
windows terminal does not focus on input after launch

### ISSUE THREAD

**Issue by volksvagen** [microsoft/terminal#13846]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

1. Win + Run, enter
2. Type 'wt.exe', enter
3. Try typing some characters in the launched wt window

### Expected Behavior

wt should focus at input after launch.

### Actual Behavior

i need to click mouse on the wt window (or press Alt + F4 once) to retrieve input focus, which is very weird.

**Comment by zadjii-msft** [comment]
What's your default profile set to?

This is probably (subtly) also related to #13640.

#13388 goes all the way back to 1.14.1451.0, I should double check that that build had the phwnd changes. I'll probably end up just deduping this with that one honestly
