### ISSUE TITLE
Anything related to Command Prompt crashes after some time

### ISSUE THREAD

**Issue by PossibleReference** [microsoft/terminal#13856]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000 Build 22000

### Steps to reproduce

Unknown, randomly started happening

### Expected Behavior

The Terminal to be usable for long amounts of time

### Actual Behavior

Command Prompt crashes whenever it is open for too long (a short amount of time)

**Comment by zadjii-msft** [comment]
Can you give us anything else to work with/? Is there any sort of consistency in the repro? Does it happen with other shells? Did you happen to get updated by the Store recently? (The Store is known to force-kill the Terminal when it's in the background, even if it's running).

As is, this doesn't really seem actionable...

**Comment by zadjii-msft** [comment]
> I think the Store force-kills the terminal in the background.

_does it ever 🤣_ Thanks for following up!
