### ISSUE TITLE
Hotkey for opening windows terminal

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#1385]
# Summary of the new feature/enhancement

I have been using `ConEmu` for couple of years and one particular feature I like is the [Quake style](https://conemu.github.io/en/SettingsQuake.html) slide down. Pressing a global hotkey `Ctrl+~` opens up console which is very handy.

**Comment by DHowett-MSFT** [comment]
Please search for existing issues before filing a new one. This is #653
