### ISSUE TITLE
Terminal Preview: wt -v reports non-preview version

### ISSUE THREAD

**Issue by tbakrf** [microsoft/terminal#13850]
### Windows Terminal version

1.15.2283.0

### Windows build number

10.0.22000.0

### Steps to reproduce

[This may fall under documentation vs bug]

In your Issue: Bug report you say:
You can find the version in the about dialog, or by running wt -v at the commandline.

Running "wt -v" reports the Windows Terminal version, but not the Windows Terminal Preview version.  Maybe in the form you can update the command for how to report the preview version or have a separate form for Preview?

### Expected Behavior

report the correct version from within a PS window within Windows Terminal Preview or see updated helper text to clarify PS command for reporting Windows Terminal Preview

### Actual Behavior

just seeing text to pull non-preview version

**Comment by zadjii-msft** [comment]
Which version of the app do you have the `wt` app execution alias set to? That might explain #13849, actually. 
![image](https://user-images.githubusercontent.com/18356694/186685905-7dbe858e-a9a8-4c99-9c28-82ce118d6715.png)
![image](https://user-images.githubusercontent.com/18356694/186686058-8ed70b09-814a-473e-ae1d-e2fbbb6c5d52.png)

Terminal Stable and Terminal Preview both use the same alias, so you can only set one at a time.

**Comment by tbakrf** [comment]
Well that's it then! :D

All I did was install the Windows Terminal Preview after hearing about the run as admin feature - I did not go under the hood to modify any alias.
[cid:4b1a4e2a-0c4f-4c3b-aa86-a28eedc8e669]

I did set Windows Terminal Preview to be my default terminal application though.
Not sure if it would help or hurt, but perhaps if you choose the "Default terminal application" to be the preview, it could guide you to update the exe alias?
[cid:5a80f6a4-b2a1-488a-adba-b2ad2f9da223]




Todd Biggins
Applications Management

***@***.******@***.***> | www.akrf.com<https://www.akrf.com/> <https://www.akrf.com/>
440 Park Avenue South, 7th Floor, New York, NY 10016



________________________________

**Comment by DHowett** [comment]
Thanks for confirming!

> Not sure if it would help or hurt, but perhaps if you choose the "Default terminal application" to be the preview, it could guide you to update the exe alias?

This is a good idea. I wonder... I don't know if there's a way for us to detect this without relying on a private API. I _DO_ know that there's no way for us to deep-link into the "app execution aliases" page in Settings ☹️
