### ISSUE TITLE
The terminal cannot enter any text during use

### ISSUE THREAD

**Issue by chinaZoulx** [microsoft/terminal#13855]
### Windows Terminal version

1.15.2284.0

### Windows build number

10.0.22000.0

### Other Software

open ssh service(ubuntu20.0.4)  from wsl2(ubuntu20.0.4)

### Steps to reproduce

random

### Actual Behavior

The terminal cannot enter any text during use。
This window is jammed, but other window normal.
try CTRL + Q doesn't work
![image](https://user-images.githubusercontent.com/13808842/186808261-68af80b7-6012-4160-a79e-f28ed8b4822b.png)

**Comment by zadjii-msft** [comment]
Is there a consistent repro for this, or does it just happen "after some time"/?

Was there was a DPI change?  Did you resize the window? Or execute something specifically that caused it to hang? If it just stops responding to keyboard input, but not mouse input, that too would be interesting (heck, that'd be crazy surprising).

I vaguely recall an issue from a few months ago where a bad `ssh` version could result in the tab seemingly hanging, when really it was just `ssh` that stopped responding to input. I thought that was just `ssh.exe` though. 
 
Recently, see also #13701

**Comment by chinaZoulx** [comment]
After running for a period of time, there is no change to the window, before the problem using remote SSH. 
 
In the diagram I provided, the adb shell is also stuck

**Comment by chinaZoulx** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/13808842/187888101-3f58fc8c-a9f2-4482-84d4-246dfae91bbe.png">

I encountered a non-response problem again, while using ADB shell

**Comment by carlos-zamora** [comment]
Since you said SSH is hanging up, we'd like to test that out. Can you press the following keys: Enter, '~', '?'.

After doing so, it might print out a help message.
If it does, terminal is hung.
If it doesn't, then the SSH connection is unstable.
