### ISSUE TITLE
All tabs path resets to %system32% on restore

### ISSUE THREAD

**Issue by QuAzI** [microsoft/terminal#13862]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Run PowerShell 7, PowerShell 5, cmd, bash... whatever... Choose their own paths...
Close wt (it shows "Do you want to close all tabs")
Ok. Close all. Than run wt again

### Expected Behavior

It restores all tabs with their own paths. 
Or opens only one default tab because we had "Do you want to close all tabs"

### Actual Behavior

It restores all tabs but resets paths

**Comment by zadjii-msft** [comment]
Did you [configure the shell to tell the Terminal about the CWD](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory)/? Otherwise yea, the Terminal won't know what path the client application is in, and will default to your `startingDirectory`.

**Comment by QuAzI** [comment]
It was %USERPROFILE% but anyway there is no sense to restore tabs if they lost
