### ISSUE TITLE
Translation issue in German translation for the duplicate of a profile

### ISSUE THREAD

**Issue by paulober** [microsoft/terminal#13864]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Open a new terminal window with the German translation enabled.
2. Then go to settings and duplicate any profile.

### Expected Behavior

The profile name gets an extension like "(Kopie)"

### Actual Behavior

The profile name gets the extension: "(Kopieren)" <- this is not the equivalent to the English "(Copy)" it means something like "(copying)"

**Comment by paulober** [comment]
I would like to fix this if someone could tell me where to find the other translation files....

**Comment by zadjii-msft** [comment]
@lhecker how could you let this happen 🤣 

I LOVE the willingness to help with a fix here, but I unfortunately don't think we can accept community loc fixes right now. #10667 has some of the reasoning on why that's _hard_ for us right now 😕 Still something we'd love to fix in the future though!

For now, we'll have to go through and file a loc bug on the internal loc team, so this can get fixed.

**Comment by lhecker** [comment]
I'm sorry for the long wait! This is now tracked at MSFT-44562118.

**Comment by paulober** [comment]
Any update on MSFT-44562118?

**Comment by zadjii-msft** [comment]
Comments internally suggest this was resolved Sept 23, so I'd guess this is fixed in 1.19?

**Comment by paulober** [comment]
I'll test, but i think so.
