### ISSUE TITLE
Terminal prevents other apps from being fullscreen on main monitor on multi-monitors desktops.

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#13868]
### Windows Terminal version

1.15.2283.0 (current preview build from MS Store)

### Windows build number

10.0.22621.382 (current Win11 Release Preview channel)

### Other Software

Movies & TV or other UWP app with fullscreen mode (also confirmed with Giana Sisters Twisted Dreams, which is still a Win8 UWP app).

### Steps to reproduce

On a multi-monitor system, when an app is running fullscreen on the primary monitor and Terminal is on another one, giving the focus to Terminal hides the fullscreen app (as if it was minimized to the taskbar).

I couldn't find any other app that breaks the fullscreen mode of the app running on the primary monitor. Note some apps can keep running fullscreen, but it seems to me those are not real fullscreen mode apps but instead maximized over the taskbar and without window chrome, as apposed to DirectX fullscreen mode. Not sure if it's DX in UWP only or if Win32 DX fullscreen apps are also affected.

To test this, start Terminal and place it on a secondary monitor, then play a video in the Movie & TV app and switch it to fullscreen, then click the Terminal window again. The Movie & TV app will get hidden, as if it got minimized.

### Expected Behavior

Terminal shouldn't prevent an app running fullscreen on another monitor, and no other app I could find does this.

### Actual Behavior

If Terminal is running on a secondary monitor and receives the focus, it prevents another app from running fullscreen on the primary monitor and hides it.

**Comment by zadjii-msft** [comment]
So, I spoke with a colleague over in the Shell team, and he gave me the lowdown. Basically, UWP applications have all sorts of special behaviors baked into them by the OS. Including the assumption that there can only be one fullscreen application at a time. This obviously isn't _really_ true, but alas, that's how it is. This includes the observed behavior, where focusing certain apps causes UWP fullscreen apps to just _minimize themselves_. 

You can try filing feedback on the Movies and TV app, or on the UWP platform itself? Maybe this'll be something that Windows App SDK fixes?

He assured me this is something they hear quite a bit, but there's nothing we can do as the Terminal to try and avoid this behavior. 

Sorry that this isn't a more satisfying conclusion 😕
