### ISSUE TITLE
Do not show close button for inactive tabs in Compact mode

### ISSUE THREAD

**Issue by dehghani-mehdi** [microsoft/terminal#13865]
Compact mode is great, but the click area for inactive/unfocused tabs is too small and there is a good chance to close the tab accidentally when selecting tabs. (I do it every day :D)
The good approach is how Firefox/Chrome handle pinned tabs. as you know they show only the favicon, not the close button.

**Comment by zadjii-msft** [comment]
You know, you'll probably be interested in #3335, which is coming in 1.16 😉 

There's also #5969 for proper tab pinning, but that alas requires a lot more platform support than we're likely to get anytime soon. 

/dup #3335
