### ISSUE TITLE
Feature Request: Pop out Tabs and List Tabs on Taskbar

### ISSUE THREAD

**Issue by coconut2015** [microsoft/terminal#13879]
The complete idea is the following.

1. Allow tabs to be popped out into separate WT windows and allows the tabs to be drag-n-dropped much like Edge browser tabs.  This allows tabs to be more easily organized.  For instance, I could have multiple consoles connecting to a docker instance, and a separate set of consoles connecting to a different docker instance.
2. List the tabs in the taskbar vertical list when the user left-click the Windows Terminal icon on taskbar.  The title of the tab is listed as well along with possible notification (visual BEL).   Then the user can select the tab based on the title and notification.
3. Allow script to launch cmd.exe in named WT window, much like Window.name for setting hyperlink target.

Take this frequent use-case scenario.  Usually, I have 10+ command line tabs open investigating multiple issues.  I could run a build script in one tab that could take 5-10 minutes, and then run another test script that could take 25 minutes in a different tab, and so on.  Many of my scripts have BEL notification generated at the end of the script to indicate that it is done.  Then after a coffee break / 1-hr meeting, I would check the tabs with visual BEL to see which tasks have been completed and needs to be inspected etc.

Right now, as a workaround, I am basically running multiple WT windows, each with a single cmd.exe tab running.  I am not running cmd.exe by itself since it does not support visual BEL.  WT has visual BEL, but it lacks a good way of listing tabs when there are a lot of tabs.  However, this workaround defeats the purpose of tab support in WT.

**Comment by zadjii-msft** [comment]
* /dup #1256
* /dup #687
* /dup #4472 - this you can do today with window names and `wt -w`.
