### ISSUE TITLE
Feature Request: Remember window position/size

### ISSUE THREAD

**Issue by noinkling** [microsoft/terminal#1387]
# Summary of the new feature/enhancement

When the window is closed, remember its position/size for next time, either automatically or with some sort of explicit "remember" option.

Alternatively, as a minimal implementation, be able to manually specify initial position (similar to how you already can with column and row size). Already covered by #1043.

**Comment by DHowett-MSFT** [comment]
We should just track all position bugs in #1043. Thanks!
