### ISSUE TITLE
Dropdown menu button has the same tooltip as new tab button

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#13889]
The dropdown menu button (˅) shows the same tooltip as the new tab button (+).  That seems odd.

And (I've mentioned this before)  the "˅" on the dropdown menu button looks oddly puny compared to the "+" on the new tab button.

Microsoft Windows 10 Pro for Workstations
10.0.19044.1889 (2009, 21H2)
WindowsTerminalPreview 1.15.2208.16002

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6078 for more discussion.

/dup #6078
/dup https://github.com/microsoft/microsoft-ui-xaml/issues/2064 (related)

**Comment by vefatica** [comment]
Hmmm!  I did search but figuring it was an easy fix I didn't go back that far in time.  :-)
