### ISSUE TITLE
Add support for DECBKM (Backarrow Key Mode)

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#13884]
# Description of the new feature/enhancement

Backarrow Key mode controls whether the backspace key should produces a `BS` or `DEL` control sequence. This was a mode supported by the VT320 and later terminals.

I initially thought this would be useful for people that were complaining about the backspace key not sending what they expected it to, but having reread some of those issues I don't think they're actually using the VT input mode, so I'm having my doubts about that now.

Someone might still find it useful, though, and if nothing else it improves our VT conformance, so I'm happy to create a PR for it if you want it.

# Proposed technical implementation details (optional)

I've currently implemented it as another section in the `TerminalInput::HandleKey` method, treating `VK_BACK` (and the various modifier combinations) as a special case. Previously the `VK_BACK` key was handled in a number of different mapping tables.

This would also fix the `Alt`+`Shift` combos which aren't currently correct.

**Comment by zadjii-msft** [comment]
Sems sensible to me. 


How weird that we were just having a discussion about the "compatibility" tab in the gnome-terminal settings, which this seems slightly relevant to.

**Comment by DHowett** [comment]
I'm definitely in favor of this. Thanks @j4james :smile:
