### ISSUE TITLE
Display problems, color Settings and some interactive buttons

### ISSUE THREAD

**Issue by nianjiuhuiyi** [microsoft/terminal#13895]
### Windows Terminal version

1.15.2282.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

That's how it started. There's something wrong with the interface

### Actual Behavior

When I configure the new theme color, the interface looks like this, and the system interaction button is not visible
![image](https://user-images.githubusercontent.com/64776403/187823245-4be6df00-0e8b-4559-a817-72a120c4b934.png)
---
When I hit Close, the confirm button does the same thing
![image](https://user-images.githubusercontent.com/64776403/187823403-20a8f758-2ecd-4840-b40c-d91c2eb3f7de.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #13382 for more discussion.

/dup #13382
