### ISSUE TITLE
Windows Terminal Keyboard Focus Problem with Magnifier

### ISSUE THREAD

**Issue by muhammedogz** [microsoft/terminal#13905]
### Windows Terminal version

1.14.2282.0

### Windows build number

OS Name	Microsoft Windows 11 Home Single Language
Version	10.0.22000 Build 22000

### Other Software

I am using WSL2 Ubuntu

### Steps to reproduce

Install windows terminal
Open windows default magnifier tool
Write something to terminal, It should follow your cursor. In some cases it is not following.
Mostly happens when changing the focus to another app and re open the termial again with alt+tab combination.

### Expected Behavior

In earlier versions, there was a issue like this. Sometime focus were working sometimes not. But last preview build it is not working correctly. Alltough working fine when you use with default Ubuntu Terminal that comes with WSL2 installation.

### Actual Behavior

There is no focus when typing. After changing app and re opening terminal works but not works for all the time.

**Comment by zadjii-msft** [comment]
Terminal versions and OS versions area actually really helpful 😉 

I'm betting this is correlated with #13388.

**Comment by muhammedogz** [comment]
> Terminal versions and OS versions are actually really helpful 😉
> 
> I'm betting this is correlated with #13388.

Yes you are right :)
I add reqired information.

**Comment by zadjii-msft** [comment]
Hey folks who are hitting this - can I ask for some debugging help? 

See: https://github.com/microsoft/terminal/issues/13388#issuecomment-1379117011 

I can't repro this myself. But I do think it's related to another thread, and I've got a theoretical fix for that thread. Can I get someone in here to try the build I linked in #13388, and see if that build resolves this? It's technically an unsigned package, so you might need developer mode enabled.

**Comment by zadjii-msft** [comment]
Here's a couple questions:
* What's your default profile? Is it a WSL profile by any chance?
* What are you running in that tab where this repros? WSL, cmd.exe, pwsh?
* Do you have Docker for Windows installed? (if so, which version?)

**Comment by RandomDSdevel** [comment]
> Here's a couple questions:
> 
> * What's your default profile? Is it a WSL profile by any chance?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My default profile's a Microsoft Store PowerShell profile.  For the record, I see this issue in any of the profiles I use frequently.  The profiles I use most often are that Microsoft Store PowerShell one and a partly ad-hoc WSL 2 one for a custom, non–Microsoft-Store Gentoo instance.  I have other profiles, but I don't really use them.  I can dump my configuration if needed on request.  

> * What are you running in that tab where this repros? WSL, cmd.exe, pwsh?  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;What's running is usually either PowerShell from the Microsoft Store in a PowerShell profile or WSL 2, hosting my custom Gentoo instance, in a WSL 2 profile for said instance.  

> * Do you have Docker for Windows installed? (if so, which version?)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No, I don't have Docker for Windows installed.  

---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I should say that I sometimes also see the issue, with about the same frequency, even when Alt-tabbing between open programs on the _same_ virtual desktop.

**Comment by zadjii-msft** [comment]
Is this still happening on [Terminal Preview v1.19](https://aka.ms/terminal-preview)/?

**Comment by RandomDSdevel** [comment]
@zadjii-msft:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm still seeing this issue quite frequently, actually.  This is now under:  

**OS version:**  Windows 11 Pro 22H2 (64-bit,) build 22621.2361
**Experience version:**  Windows Feature Experience Pack 1000.22674.1000.0
**Windows Temrinal app version:**  Windows Terminal v1.17.11461.0

in:

 - PowerShell (Microsoft Store edition) v7.3.7.0
 - A WSL 2 Gentoo Linux instance (installed [manually](https://wiki.gentoo.org/wiki/Gentoo_in_WSL) without the Microsoft Store's help in the form of an official package.)  (Linux kernel version:  v5.15.123.1-microsoft-standard-WSL2)
