### ISSUE TITLE
If you rename the tab and then click on Export Text, the filename is the previous title of the tab

### ISSUE THREAD

**Issue by MontecaE** [microsoft/terminal#13909]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Title of a tab is _Administrator: PowerShell_
- rename it to _asd_
- click on Export Text
- (default) filename is _Administrator: PowerShell.txt_

### Expected Behavior

The (default) filename exported is the tab name (so, in this example _asd.txt_)

### Actual Behavior

The filename is not aligned to the tab title

**Comment by zadjii-msft** [comment]
Should be easy enough to fix:
https://github.com/microsoft/terminal/blob/fe0d57071edee4ceb650990d3acd2838fec2ee7f/src/cascadia/TerminalApp/TabManagement.cpp#L399-L439

Just use the `tab`'s Title, rather than the `control`'s Title, on line 437.
