### ISSUE TITLE
Pipe symbol not available in terminal app with "swiss french" keyboard

### ISSUE THREAD

**Issue by didwi** [microsoft/terminal#1390]
Hi,
Tried terminal preview version: 0.2.1715.0 on windows: 1903 (build 18362.175).

Unfortunately it seems the pipe symbol is not available, which makes it pretty useless for powershell.

Normally, keyboard combination for the pipe symbol on a "swiss french" keyboard is the following key combination "AltGr + 7", but in Windows Terminal Preview you get the following 2 characters instead:
^_

![pipe-symbol-international-keyboard](https://user-images.githubusercontent.com/37713131/59961140-ab08c600-94d3-11e9-83f9-feb2dbc1a96f.jpg)

Didier

**Comment by hangar18rip** [comment]
Hi there,
same kind of issue with french (France) keyboard. | symbol generates this :
![image](https://user-images.githubusercontent.com/6670531/59962844-190cb780-94eb-11e9-85de-5932166c268a.png)
and AltGr + 8 (\ on french keyboard), generates _ (the key without modifier), not \ and it is the same for all the AltGr dependent symbols

it seems the AltGr key modifier is not handled

**Comment by MarkusMichalski** [comment]
Same here with German layout (DE-DE), can't type @ as well.

To be precise, any char that requires [AltGr] to be pressed, will not be typed corretly.

**Comment by onomatopellan** [comment]
Same here with Spanish ES-ES layout.

**Comment by DHowett-MSFT** [comment]
Correct, please use 521 to discuss this
