### ISSUE TITLE
Open a new Administrator instance by pressing the '+' in the tab bar while pressing the Ctrl key is not working

### ISSUE THREAD

**Issue by okibcn** [microsoft/terminal#13908]
### Windows Terminal version

1.15.2283.0

### Windows build number

10.0.25193

### Steps to reproduce

After a clean install of Windows 11 Dev preview 10.0.25193 and using an administrator account:

1. install Windows Terminal Preview from the MS Store.
2. Open Windows Terminal
3. Press the '+' in the tab bar while pressing the Ctrl key
4. Press yes button to the elevated prompt dialog window

### Expected Behavior

A new window with administrator level shows up with the default profile

### Actual Behavior

Nothing happens after accepting the elevated prompt.

**Comment by okibcn** [comment]
This issue can be related to issues #12369 and #13675

**Comment by zadjii-msft** [comment]
I'm just gonna go out on a limb and say this is /dup #13675. Thanks!
