### ISSUE TITLE
Don't constantly repaint if a pixel shader doesn't reference `time`

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13901]
![image](https://user-images.githubusercontent.com/18356694/187975473-e71e870a-9390-4353-834c-343e8b03ed24.png)
![image](https://user-images.githubusercontent.com/18356694/187975497-30509c32-0aca-4aa9-92dc-3df49e7a9d7e.png)

> technically it could be `time` ,`Time`, `tiempo` or anything, right? in the shader, its just the 0th float in `PixelShaderSettings` yea?

> right we'd use it by index instead of name

**Comment by DHowett** [comment]
I figured I'd take a crack at this for Atlas today
