### ISSUE TITLE
When the input line reaches the bottom of the window, the character string of the IME conversion candidate in the input line is not displayed in the input line.

### ISSUE THREAD

**Issue by t32ak1** [microsoft/terminal#13918]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Open a terminal window.
2. Display something until a scroll bar appears. (ex. Repeat echo until the line reaches the bottom of the Window.)
3. Turn on IME and display IME candidates.

### Expected Behavior

Characters in the IME input state are displayed in the input line.

### Actual Behavior

Characters in the IME mode are output outside the input line (probably outside the window).
![IME Candidate appears Incorrectly](https://user-images.githubusercontent.com/51771015/188265163-96ced641-0fd9-47ee-9609-4e4145afd0d4.gif)

**Comment by j4james** [comment]
I think this is probably the same issue as #13769. There's a fix committed which should be available in the next servicing release.

**Comment by t32ak1** [comment]
Thank you for your confirmation.

It certainly looks similar to the phenomenon reported in #13785.
Sorry for the lack of confirmation.

Thank you for your response.

**Comment by DHowett** [comment]
Thanks for confirming! /dup #13769
