### ISSUE TITLE
conhost headless mode is broken

### ISSUE THREAD

**Issue by AveYo** [microsoft/terminal#13914]
### Windows Terminal version

1.15.2203.0

### Windows build number

10.0.25193.1000

### Steps to reproduce

`conhost --headless cmd /c "echo;%date% %time%>>%userprofile%\desktop\test.log"`

### Expected Behavior

test.log with date and time on desktop sans brief ui, like it worked so far up to build 25179

### Actual Behavior

_cmd.exe - Application Error_ **dialog**
_The application was unable to start correctly (0xc0000142).
Click OK to close the application._

**Comment by AveYo** [comment]
Briefly checked commit history and #13832 or #13570 stand out.

**Comment by DHowett** [comment]
Thanks for the report!

The direct invocation of `conhost` with its (admittedly undocumented) arguments isn't exactly "officially" supported.
`conhost --headless` primarily exists to support the `CreatePseudoConsole` API. We've got some automated tests for those APIs and they haven't flagged anything as being amiss.

Despite that, I'm not inclined to close this issue because it probably represents an under-served need... and because we didn't intentionally break it.

What was the use case for which you were using `--headless`? I'd love for us to brainstorm ways to do that which are fully supported and that we can guarantee will continue to work or back up with APIs.

**Comment by AveYo** [comment]
Use case:  

<details><summary>shortcuts launching various powershell-based GUI front-ends in plain-text scripts,</summary>

sans annoying / ocd-inducing flashing console window
I like to think of these as Progressive Script Apps - very mouse & touch friendly, and can't get more "open-source" than that, trivial to audit vs. compiled programs 
</details>

<details><summary>command-line scripting of various brief and simple tasks,</summary>

sans annoying / ocd-inducing flashing console window  
sans 3rd party tools fauna representing this under-served need these past.. decades
sans annoying / ocd-inducing false-positive harassment if using higher-scripting languages stubs via wscript, mshta & co. (introducing complexity to otherwise a simple need)
I extensively use it for admin / monitoring / intercepting programs via Image File Execution Options, and under user session the amount of console flashing can be quite overwhelming 

</details>

<details><summary>parity with terminals on *nix</summary>
multiple ways of running headless scripts, by design
</details>

Start /min was never a solution since it requires non-headless cmd - same for Run Minimized for shortcuts.
When the system is busy console flashes regardless, plus it makes going back to foreground even more difficult in the focus-deficient 11 taskbar _(like, even UAC prompts don't pop-up often)_. 
And even that has regressed with 11: sometimes window flashes, other times taskbar icon appears briefly, or not appear at all; it's worse under virtualization / modest hardware / busy system; uninstalling Terminal gives a more consistent taskbar icon appearance _(and speaking of that, Win + X is broken again, does not revert to Powershell)_.

Compiled programs obviously have access to window creation parameters, but that's outside the scope of Command Prompt / Powershell / Terminal and scripts. 

So maybe restore OS conhost behavior and do what's needed with Terminal's own OpenConsole? 
Or outright deprecate this undocumented behavior across all windows versions and silently ignore headless mode.
Crashing cmd / powershell is definitely not nice.

**Comment by zadjii-msft** [comment]
```
0:002> k
 # Child-SP          RetAddr               Call Site
00 00000083`b78ffd10 00007ff6`f128b097     OpenConsole!std::optional<Microsoft::Console::PtySignalInputThread::SetParentData>::has_value+0x1b [C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\include\optional @ 416] 
01 00000083`b78ffd40 00007ff6`f1294f71     OpenConsole!Microsoft::Console::PtySignalInputThread::CreatePseudoWindow+0x27 [D:\dev\public\terminal\src\host\PtySignalInputThread.cpp @ 90] 
02 00000083`b78ffd80 00007ff6`f116a854     OpenConsole!Microsoft::Console::VirtualTerminal::VtIo::CreatePseudoWindow+0x31 [D:\dev\public\terminal\src\host\VtIo.cpp @ 329] 
03 00000083`b78ffdb0 00007ffa`f085458d     OpenConsole!ConsoleInputThreadProcWin32+0xa4 [D:\dev\public\terminal\src\interactivity\win32\WindowIo.cpp @ 1053] 
04 00000083`b78ffe60 00007ffa`f1297558     KERNEL32!BaseThreadInitThunk+0x1d [clientcore\base\win32\client\thread.c @ 75] 
05 00000083`b78ffe90 00000000`00000000     ntdll!RtlUserThreadStart+0x28 [minkernel\ntdll\rtlstrt.c @ 1192] 

```

oh boy

**Comment by zadjii-msft** [comment]
Easiest delta to fix this is probably just


```diff
void VtIo::CreatePseudoWindow()
{
+    if (_pPtySignalInputThread) {
        _pPtySignalInputThread->CreatePseudoWindow();
+    else {
+        ServiceLocator::LocatePseudoWindow(owner);
+    }
}
```

**Comment by AveYo** [comment]
This did not trickle down in Windows 11 latest builds and that's where it's most daring.

**Comment by DHowett** [comment]
> This did not trickle down in Windows 11 latest builds and that's where it's most daring.

Unfortunately, it's not very likely that we will fix this for existing Windows 11 install, either in the coming 22621 update or in a servicing update. It doesn't impact any previously supported user scenarios, and there's no strong business justification for bringing the fix into the coming version of Windows since that version of Windows has already been signed-off-on and sealed.

**Comment by AveYo** [comment]
@DHowett thankfully this only got broken in 11 Dev builds above 25179, so no objective reason not to expect the fix in upcoming 11 Dev builds.

**Comment by AveYo** [comment]
Close to a year later and this crap is still not fixed.
