### ISSUE TITLE
Make the documentation accessible to people who don't search GitHub on their own

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1391]
# Summary of the new feature/enhancement

There is lots of things that can be modify for end-users for terminal(like colors, background image, icon, ....etc), I think is there should have some sort of documentation in windows terminal, like **How to modify terminal** on the tab or inside About tab on the terminal.

**Comment by noinkling** [comment]
There's currently a reference for the settings here: https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md

It should probably be easier to find - I'd say you could add a link to it at the top of the settings file, but we all know JSON doesn't support comments so...

I expect that eventually there will probably be some sort of UI for settings, manually editing JSON seems like a stopgap measure.

**Comment by SJang1** [comment]
https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md is not up-to-date for even now.
and after new commits of terminal, Schema can be changed or added, deleted but terminal can be old to use that.
For that reason, I think making a doc in the terminal or some txt file? will be better than linking to that link.

**Comment by cinnamon-msft** [comment]
#1887 fixes this
