### ISSUE TITLE
A command to run a script (.bat/.cmd) in a normal cmd.exe window instead of Windows Terminal.

### ISSUE THREAD

**Issue by KcrPL** [microsoft/terminal#13911]
# Description of the new feature/enhancement
A command to run a script (.bat/.cmd) in a normal cmd.exe window instead of Windows Terminal.

Some things are still handled differently in the Windows Terminal. I'm talking especially about the `mode` command not working which changes the window size. Is there already a way to do that?

**Comment by zadjii-msft** [comment]
`conhost.exe -- cmd.exe <the batch file>`

![image](https://user-images.githubusercontent.com/18356694/188194582-760f0a9b-3abc-44aa-becc-455867ff2048.png)

But also go upvote #5094

**Comment by KcrPL** [comment]
Thanks! That's exactly what I needed.
