### ISSUE TITLE
Guidance: Open terminal with commands

### ISSUE THREAD

**Issue by Morgy93** [microsoft/terminal#1392]
I'd love to know how I can fire up the terminal with commands.
I just found out that `wt.exe` works, but I am not yet able to figure out how to pass commands to the terminal. (If that's even possible)

Just something like: `wt.exe ssh user@host.com -t 'cd /whatever'`

I already set wsl to default, so that doesn't matter, but I could even imagine choosing a shell, besides using the default one `wt.exe --shell wsl --commands ...`

**Comment by Morgy93** [comment]
Seems not be possible as of #607

**Comment by Morgy93** [comment]
For README:
> Currently supported command line options:
> - none
> - see #607

Maybe that helps for people like me 😁

**Comment by DHowett-MSFT** [comment]
Yeah this will be #607

**Comment by DHowett-MSFT** [comment]
We should add it to the docs. Thanks!
