### ISSUE TITLE
Text box cursor after NVim

### ISSUE THREAD

**Issue by Trard** [microsoft/terminal#13921]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Other Software

Neovim:
    NVIM v0.8.0-dev
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3

### Steps to reproduce

1. Install pure neovim (or open already installed);
2. Open neovim.
3. Close neovim.

### Expected Behavior

I text cursor after closing.

### Actual Behavior

▊ text cursor after closing.

https://user-images.githubusercontent.com/68790724/188283244-a52dfd3b-5103-4964-a889-0691729aeb98.mp4

**Comment by Trard** [comment]
Neovim bug.

https://github.com/alacritty/alacritty/issues/5450#issuecomment-904917605

**Comment by DHowett** [comment]
Thanks for following up!
