### ISSUE TITLE
Copy out of terminal does not include linebreaks

### ISSUE THREAD

**Issue by benjaminlostandfound** [microsoft/terminal#13934]
### Windows Terminal version

1.14.2281.0

### Windows build number

Microsoft Windows NT 10.0.19044.0

### Other Software

WSL 2:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

### Steps to reproduce

Copy text out of windows terminal when running wsl/ssh

### Expected Behavior

Just copy text in the terminal and paste it somewhere else

### Actual Behavior

Copied text will does not line breaks

**Comment by zadjii-msft** [comment]
What text did you specifically output and try to copy/? (if you have a [debug tap](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap) trace, that might be helpful) Were you running in tmux? Was ssh actually involved? These are all things that might dupe this to one of the related issues on the backlog

**Comment by benjaminlostandfound** [comment]
Going back to putty as i saw there is allready an issue in the backlog.
