### ISSUE TITLE
Bug Report: ctrl + w always crashes

### ISSUE THREAD

**Issue by Morgy93** [microsoft/terminal#1393]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

1. Open wt.exe
2. Press Ctrl + W 

# Expected behavior

The program just closes

# Actual behavior

It crashes

```
Unhandled exception at 0x00007FFF9E97A539 (TerminalApp.dll) in WindowsTerminal.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred
```

I am really just opening it up and pressing ctrl + w
![wt](https://user-images.githubusercontent.com/7961978/59961568-d4c4eb80-94d9-11e9-8c9d-8fd9ccfc17b2.gif)
Closing it via the X works just fine by the way.

Not quite sure if it helps:

![image](https://user-images.githubusercontent.com/7961978/59961526-4badb480-94d9-11e9-98f7-c669a548ea6f.png)

**Comment by cherichy** [comment]
Ctrl+W is the command to close current tab, you can see the keybindings in the Setting with filename "profile.json". Since you only have one tab, the program will close once you press Ctrl+W

**Comment by Morgy93** [comment]
@cherichy That's right, the program SHOULD close, but instead it crashes.

**Comment by DHowett-MSFT** [comment]
This is #1380 #1339
