### ISSUE TITLE
SUI elements unclickable after tab reorder

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#13945]
### Windows Terminal version

1.16.2352.0

### Windows build number

10.0.22973.0

### Steps to reproduce

1. Launch Terminal with a profile tab and an _unfocused_ settings UI tab
2. Reorder the tabs
3. Open settings UI tab
4. Settings UI page elements are unclickable, but nav view items are

### Expected Behavior

Should be able to click items on the settings UI after reordering.

### Actual Behavior

Nav view is clickable, but content in the page and the save buttons aren't. Looks like it's because the page isn't initialized properly if the elements aren't loaded before reordering tabs?

**Comment by zadjii-msft** [comment]
This looks like a consistent repro for #13415 - that look right to you/?

**Comment by cinnamon-msft** [comment]
Ah yep, looks like that's likely caused by the same bug. Nice catch :)
