### ISSUE TITLE
Close button doesnt send a sigint to running process

### ISSUE THREAD

**Issue by Ricardonacif** [microsoft/terminal#13941]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Open any process on Windows Terminal that listens for a SIGINT and waits 5 seconds before closing
Click on the close (X) button on Windows Terminal

### Expected Behavior

This should send the SIGINT signal to the process, and let it handle it.

### Actual Behavior

It insta closes the Windows Terminal and the underlying process

**Comment by DHowett** [comment]
Thanks for the report! This may need to be moved over to the [WSL repository](https://github.com/microsoft/wsl), since they own what happens when they get a "Console Closing" event. Whether they translate it into `SIGINT` or terminate the process is up to the subsystem host.

**Comment by zadjii-msft** [comment]
Does the process get a SIGINT if you're running the process in the vintage console/?

**Comment by Ricardonacif** [comment]
Actually, I thought this was the default behavior on Powershell, but it's not actually. It's actually the option -Wait on Start-Process command that makes the process receive the SIGINT and the terminal waits for the process. Do you guys think there's a way of achieving the same behavior on WT?

**Comment by carlos-zamora** [comment]
Hi @Ricardonacif. I'm curious, why do you want this?

We implemented it this way to make sure the UI updates as quickly as possible and create a "snappy" feeling.
