### ISSUE TITLE
Selected tab title not used for `Export Text` file name

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13948]
### Windows Terminal version

main 1ef4a4276

### Windows build number

10.0.19044.0

### Steps to reproduce

- build WT with `Use the tab's active title for "Export Text"` patch applied, commit 2c341c8de
- rename some tabs
- export text from a tab other than active one

`Foo` was the active tab and `Bar` was used for export:
![wt_export_text](https://user-images.githubusercontent.com/3933920/189212775-956220d7-7607-43b3-bd62-a78d51fae0ea.PNG)

### Expected Behavior

- tab's title used for filename

### Actual Behavior

- the active's tab title is being used instead

**Comment by DHowett** [comment]
Thanks for the report! @serd2011  just fixed this in a recent PR :)

**Comment by DHowett** [comment]
I was super wrong, and didn't read the issue well! Sorry!

**Comment by DHowett** [comment]
It's much worse than that: it actually only exports the active tab. It can't export a non-active tab.

How? It takes `tab` in as an action argument...! Did we really mess something up?

**Comment by ianjoneill** [comment]
So this and #13942 are somewhat related.

Of the tab related context menu items "Duplicate Tab", "Split Tab", "Export Text" and "Find", the only one that does what you expect on an unfocused tab is "Split Tab".

The callbacks are all set up in `TabManagement.cpp`:

https://github.com/microsoft/terminal/blob/95a9d8c31b3f4e27fb10ccefa525d66eacf26f96/src/cascadia/TerminalApp/TabManagement.cpp#L193-L233

They delegate to:

* `TerminalPage::_DuplicateTab()`: duplicates the currently focused tab
* `TerminalPage::_SplitTab()`: works as expected, as it focuses the selected tab and then splits it
* `TerminalPage::_HandleExportBuffer()`: exports the currently focused tab's content
* `TerminalPage::_Find()`: searches the currently focused tab's control

I guess the quick win would be to replicate what `SplitTab()` does - i.e. focus the selected tab and then do the duplicate/export/find. Is that reasonable?

**Comment by zadjii-msft** [comment]
That seems like a reasonable solution to me. Think that'll knock out all of this issue, #13942 and #13579 all in one go?

**Comment by JerBast** [comment]
> Think that'll knock out all of this issue, #13942 and #13579 all in one go?

I think that #13942 requires a slightly different approach since it relies on `_MakePane`, which uses the tab that is currently focused. Did some small work on that issue this morning.

**Comment by ianjoneill** [comment]
Hmm doesn't look like it's that straight forward - `_SetFocusedTab()` is async. As @JerBast suggests - `_DuplicateTab()` and `_SplitTab()` delegate to `_MakePane()`, which won't necessarily get the focused tab due it's async nature.

**Comment by DHowett** [comment]
Generally speaking, I'd rather us fix the event plumbing so that things that come out of (1) the pane, (2) the tab and (3) the terminal control are tagged up appropriately so we know their origination chain. Is that something doable on a reasonable time horizon?

**Comment by serd2011** [comment]
maybe `_MakePane(newTerminalArgs, bool duplicate, existingConnection)` should accept something like `const TerminalTab& sourceTab` instead of `bool duplicate`?

**Comment by ianjoneill** [comment]
I'd come to the same conclusions. There's no point 3 people working on it though, so I'll leave it to you 🙂
