### ISSUE TITLE
Feature Request: dragable window on full window header

### ISSUE THREAD

**Issue by Morgy93** [microsoft/terminal#1395]
# Summary of the new feature/enhancement

I'd expect the terminal window to be dragable on the full window header, but it doesn't work on the tabs pane:

![wt2](https://user-images.githubusercontent.com/7961978/59961618-73e9e300-94da-11e9-94f4-1aa82f966fec.gif)

**Comment by SJang1** [comment]
Seems duplicate of #564 .

**Comment by Morgy93** [comment]
Yes, it is. Couldn't find one, but thanks! Closed~

**Comment by HBelusca** [comment]
Issue encompassed in #1375.
