### ISSUE TITLE
Batch file opens old CMD terminal

### ISSUE THREAD

**Issue by xIUPITERx** [microsoft/terminal#13954]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.0

### Steps to reproduce

If you want to open a batch file via a shortcut which has the properties of open with admin right, maximized or minimized window, the old command Prompt opens instead of the new Windows Terminal.

### Expected Behavior

The new Windows Terminal should open.

### Actual Behavior

The old command Prompt opens.

**Comment by zadjii-msft** [comment]
Alas, this is /dup #10276

> Unfortunately, this is by design right now. Due to a limitation in the app platform it is impossible for Terminal to be "discovered" as the handler when the application that needs a terminal is running elevated.
> 
> This is tracked internally at MSFT:39500755. There's a decent amount of platform work that will be needed for this.
