### ISSUE TITLE
[1.16] Pressing enter with a selection no longer sends Enter

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#13953]
Possibly worth calling out in a relnote. I just stumbled over this because our default key binding for Enter is now Copy, and I didn't realize I had relied on Enter to send Enter even with a selection active.

**Comment by carlos-zamora** [comment]
- `copyOnSelect` should make `Enter` be ignored? Unbind it?
- if `copyOnSelect`, `copy` keybindings should be passed through?
- ctrl+c and Enter behave differently
	- see how we handle ctrl+c (used to be in TermControl, probably Interactivity now?), and make sure Enter (or really all kbds) are handled similarly (see `_selectionNeedsToBeCopied`)

- compare Mark Mode to mouse selection with `copyOnSelect`

**Comment by zadjii-msft** [comment]
We cool just moving this one to a docs bug/? Haven't had complaints about this in the 1.16 preview timeframe yet. 

See https://github.com/MicrosoftDocs/terminal/issues/618

**Comment by DHowett** [comment]
Preview is pretty small, so we should be careful about drawing non-crash conclusions. But, yes.
