### ISSUE TITLE
Zoom level is dropped when switching to Terminal window with non-ENG keyboard layout

### ISSUE THREAD

**Issue by vient** [microsoft/terminal#13960]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

1. Have English keyboard layout as well as non-English (in my case it is [en_US Colemak](https://colemak.com/Windows) + ru_RU)
2. Zoom in or out any terminal pane, I used Ctrl+mouse wheel (checked with WSL pane and CMD)
3.1. Switch to layout which is not English
3.2. Focus any other app (these two steps are interchangeable)
4. Focus back to terminal

### Expected Behavior

Zoom level is intact.

### Actual Behavior

Zoom is dropped to default level with a small delay, less than a second, but only when keyboard layout is not English.

P.S. wat 🤯

**Comment by vient** [comment]
Also, sanity check: zoom is not changed when I switch keyboard layout to non-English and back before returning to Terminal.

**Comment by lhecker** [comment]
Unfortunately this is an issue we simply haven't gotten around to fixing it yet. It's caused by us reloading the settings file when the input language changes, so that any potential localizable settings are re-localized.

/dup 11522

**Comment by ExpatUK** [comment]
This is still happening in 2026 when switching keyboard layouts (I use English UK for office admin work and English US for terminal work). 

As this seems to be the top hit on google when searching for this issue, my workaround for it is just to default my fontSize (zoom level) in `settings.json` down three steps (default fontsize is 12):
```
{
    "profiles":
    {
        "defaults":
        {
            "fontSize": 9
        }
    }
}
```

**Comment by vient** [comment]
OMG it really is still happening. Forgot about it because I usually
1. Have font size permanently changed in `settings.json`, as ExpatUK said above
2. Enable "Let me use a different input method for each app window" setting so switching keyboard layout in browser does not affect keyboard layout in terminal

Which I did not on a new machine

#11522 is still open so I guess it is how it is...
