### ISSUE TITLE
Settings navigation bar is expanded and overlaps settings window after reopening terminal

### ISSUE THREAD

**Issue by KeterSCP** [microsoft/terminal#13967]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

1. Make sure you have `Open windows from a previous session` option set in the terminal Startup settings.
2. Open settings tab.
3. Select some other tab
4. Close the terminal window
5. Open terminal again
6. Switch to the settings tab

### Expected Behavior

Navigation bar is not expanded

OR

Navigation bar is expanded but does not overlap the settings window

### Actual Behavior

Navigation bar is expanded and overlaps settings window. You cannot change any settings

[terminal-settings-overlapping.webm](https://user-images.githubusercontent.com/38229504/189537764-536cf295-8a46-450e-a93a-db37f55cbef9.webm)

**Comment by j4james** [comment]
Not sure if this is related, but we've had similar problems with that navigation panel a couple of times before (see #13428 and #9337).

**Comment by KeterSCP** [comment]
Yeah, seems like I just found another way to break it
