### ISSUE TITLE
Could you make switch ctrl and alt key function for signal, or vim shortcut key?

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#13970]
# Description of the new feature/enhancement
Please, Could you make change ctrl to alt key function for signal, or vim shortcut key?

# Proposed technical implementation details (optional)
Windows is almost use ctrl key Such as Ctrl+1, Ctrl+2, ctrl+c, ctrl+v, ctrl+l, ctrl+r.
This makes my little finger hurt for keep press ctrl key.
So, I used replace ctrl and alt keys on Windows.
Could you make switch ctrl and alt key function for signal, or vim shortcut key?
In Mac, iterm2 terminal is almost use cmd key for window function.
But, In order to signal, or vim shortcut key almost use control key.
This is very efficient.
If you make this function, Many people possible for string copy with ctrl + c key.
![aa](https://user-images.githubusercontent.com/23658192/189564382-a3992e40-672a-408d-8557-f94b80c5feb4.png)

**Comment by DHowett** [comment]
Thanks for posting! I'm not sure I understand the request. If you are asking us to allow you to change Ctrl to Alt inside Terminal, you can already do that today by changing the key bindings. They are in the JSON file and in the settings UI.

**Comment by CatCatCatDog** [comment]
Yeah, I knew that. But, one key bindings impossible.
Or, If I'm wrong my configuration, Please tell me.

{ "command": { "action": "ctrl"}, "keys": "alt"},
{ "command": { "action": "alt"}, "keys": "ctl"},

**Comment by CatCatCatDog** [comment]
Yeah, I think, You don't understand.
How about this?

{"command":{"action":"sendInput","input":"\u0003"},"keys":"alt+c"},
{"command":"copy","keys":"ctrl+c"},

If you use this json, You can string copy with ctrl + c.
If you want to interrupt, You can use interrupt with alt + c.
This means, ctrl and alt keys switched.
But, Actually, I want to only switch ctrl and alt keys.

**Comment by carlos-zamora** [comment]
Hi @CatCatCatDog. Maybe PowerToys may be of interest to you! It has a keyboard manager that lets you do exactly this (and much more). Here's a link to the relevant docs: https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager

**Comment by rds** [comment]
> Are you looking for a setting to change the way the Terminal encodes ctrl/alt, so that pressing ctrl+key would instead send `alt+key` to the connected commandline application? (e.g. you'd need to press alt+z to send a `^Z` to the client application)?

Being able to remap modifier keys is exactly the feature I would love to see. For example, I would like to swap `ctrl` and `alt` in Windows (via PowerToys, etc) but _swap them back_ in Terminal for Linux use.
