### ISSUE TITLE
Pressing ```Alt + Shift + -``` on a WSL tab opens a powershell instance

### ISSUE THREAD

**Issue by danielh2942** [microsoft/terminal#13974]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Other Software

WSL2 running Ubuntu 20.04 LTS

### Steps to reproduce

Open a WSL Tab
Perform a horizontal split ```Alt + Shift + -```

### Expected Behavior

Another bash prompt in the lower area

### Actual Behavior

A Powershell prompt appeared.
If I perform a vertical split, it has the correct behavior.

**Comment by 237dmitry** [comment]
This keyboard shortcut opens the default profile in new split pane. I think you have to duplicate pane `Alt-Shift-d`

**Comment by zadjii-msft** [comment]
Yep, that's correct!
