### ISSUE TITLE
Settings does not open

### ISSUE THREAD

**Issue by benbrackenbury** [microsoft/terminal#1397]
# Environment

```none
Windows build number: 18922
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

Clicking on the Settings item in the menu, or pressing Ctrl+,

# Expected behavior

Settings.json should open
# Actual behavior

Settings.json does not open

**Comment by cherichy** [comment]
Same with you, but I can open it if I click the Setting, but not for Ctrl+,

**Comment by benbrackenbury** [comment]
Never mind, I found a solution. Turn out I didn't have any application set as the default for opening json files. After I set VS Code as the default, it worked as expected

**Comment by doterik** [comment]
Experienced exactly the same problem as @benbrackenbury.
After the same solution, it worked as expected.

**Comment by laolusrael** [comment]
I had the same experience

**Comment by ahmed4star** [comment]
the same here, but after i set Atom in default and then i uninstall it

**Comment by adiviness** [comment]
#1460
