### ISSUE TITLE
Add subtext to why `Always show tabs` is not toggleable in SUI

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13984]
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Open `Appearance` in SUI and select `Always show tabs`

### Expected Behavior

`Always show tabs` option to be toggleable 

### Actual Behavior

Control is grayed out and set to `On`:

![alwasy_show_tabs](https://user-images.githubusercontent.com/3933920/190029900-cf79af06-81b2-486f-8efd-328728ec9075.PNG)

**Comment by DHowett** [comment]
You cannot turn off the display of tabs while "show tabs in titlebar" is turned on.

**Comment by zadjii-msft** [comment]
We probably should have some sub-text that appears when in this case to indicate why it's forced on. Or at least additional text that clarifies "This setting cannot be disabled while 'Hide the titlebar' is enabled."

**Comment by elsaco** [comment]
Thank you @DHowett. I wouldn't have guessed that `Hide the title bar` needs to be off before `Always show tabs` control becomes active. Some clue in the SUI would be helpful, as suggested by @zadjii-msft

**Comment by BenConstable9** [comment]
Looking at how PowerToys handles a scenario like this:

![image](https://user-images.githubusercontent.com/15877083/196692876-e5e9cd7f-73ec-4f87-82cd-d4ddac862bda.png)

Would this be acceptable? If so, happy to make PR.

**Comment by DHowett** [comment]
@BenConstable9 I love your suggestion - sorry, I never said that and let this thread go dark - and it fits in with how we're going to pivot title bar appearance into the theming UI in the future.

I'd love to see how it turns out if you do choose to PR it.

**Comment by jamespack** [comment]
Adding text is easy enough.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/2086722/230632282-29d5f2a0-b780-4b71-863e-0ba4c0b0cb8d.png">

**Comment by jamespack** [comment]
Happy to PR it if you are good with that verbiage

**Comment by DHowett** [comment]
Works for me!

We may want to note in the `<comment>` for that translation that it is referring to another setting (and include the localization key for that setting too)

**Comment by jamespack** [comment]
Ok PR opened.
