### ISSUE TITLE
Cannot have maximum opacity by default if acrylic is enabled

### ISSUE THREAD

**Issue by ofek** [microsoft/terminal#13986]
### Windows Terminal version

1.16.252

### Windows build number

10.0.19044.0

### Steps to reproduce

This has been bugged but I thought this release might've fixed it

```json
    "profiles":
    {
        "defaults": {
            "opacity": 100,
            "useAcrylic": true,
```

1. Open a window with colors
2. Open Terminal
3. Observe bleed-through
4. Hold down key binding that increases opacity
5. Notice nothing
6. Press key binding that decreases opacity once
7. Press key binding that increases opacity once
8. Notice actual maximum opacity

### Expected Behavior

Maximum opacity by default

### Actual Behavior

Near-maximum opacity by default

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #12880 for more discussion.

/dup #12880
