### ISSUE TITLE
Support for Unicode 15.0

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#13999]
# Description of the new feature/enhancement

With the new version of Unicode having been released, do we need to regenerate the tables for our width detector class?

See https://home.unicode.org/announcing-the-unicode-standard-version-15-0/

# Proposed technical implementation details (optional)

Not sure how this is done, but I'm assuming it'll be the same basic process as PR #13292.

**Comment by DHowett** [comment]
Thanks! I didn't realize this dropped :)
