### ISSUE TITLE
Adjustable split area sizes

### ISSUE THREAD

**Issue by Richard7129** [microsoft/terminal#13993]
# Description of the new feature/enhancement

As a user that creates mutiple splits on a tab I want to be able to adjust the split size so that I can have the optimum amount of screen area for the tasks that I am performing in each split area.

# Proposed technical implementation details (optional)

- After selecting "split tab", I would like to be able to adjust the size of the area
- I would like to be able to resize those areas by using either the mouse or keyboard shortcut(s).
- For vertical splits, I want to be able to move the plit bar to the left or right
- For horizontal splits, I want to be able to move the split bar up or down

**Comment by Richard7129** [comment]
Sorry, I've just found that it already can do this, and I didn't know.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #992 for more discussion.

/dup #992

See also: 
https://github.com/microsoft/terminal/blob/71fc4b1b0aee812bc7368c0b62a96018cb9fce86/src/cascadia/TerminalSettingsModel/defaults.json#L386-L389
