### ISSUE TITLE
Windows Terminal crashes with Powershell 7

### ISSUE THREAD

**Issue by teobugslayer** [microsoft/terminal#1399]
Windows Terminal crashes when it starts if **only** Windows Powershell 7 Preview 1 is installed on the machine.

# Environment

```none
Windows build number: [Version 10.0.18362.175]
Windows Terminal version (if applicable): the first preview version from Microsoft Store
Windows Powershell 7 Preview 1
```

# Steps to reproduce

I have installed Powershell 7 preview 1 and uninstalled Powershell core 6.2.1

# Expected behavior

I expect that Terminal would open with Powershell 7

# Actual behavior

Windows Terminal crashes on startup. Only the border of the window is shown and then the process terminates. The following entry is recorded in Event Viewer:

```
Faulting application name: WindowsTerminal.exe, version: 1.0.1906.20005, time stamp: 0x5d0c1459
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000007ffdd79422
Faulting process id: 0x2fac
Faulting application start time: 0x01d528e182a35ce7
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: unknown
Report Id: 85dd7eae-24e6-4dcf-bf38-6172a5dd7710
Faulting package full name: Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by magiblot** [comment]
Shares similarities with #1364.
Here's my `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by DHowett-MSFT** [comment]
Are either of you able to use Visual Studio to deploy the developer build? We can't reproduce this on our end. :(

**Comment by teobugslayer** [comment]
The sequence to get the crash is:

1. install PS Core 6
1. install PS Core 7
1. install WT
1. launch WT. It should pick PS Core 6 as default shell
1. uninstall PS Core 6
1. launch WT. it should crash.

**Comment by Forinil** [comment]
You do not need to install and then uninstall Ps Core 6 at all. Windows Terminal will pick it up as a default shell, even if it was never installed. See #1673.

**Comment by vivaladan** [comment]
I've been having this error on an almost fresh install of Windows. No PS Core installed.
The terminal window opens and for a fraction of a second I see a flash of black which disappears showing the desktop behind and just the frame chrome.

I installed PS Core 7 and it didn't fix it. 
I then installed PS Core 6 and it did fix it. 

Does terminal require PS Core 6 to be installed?

```
Faulting application name: WindowsTerminal.exe, version: 1.0.1906.20005, time stamp: 0x5d0c1459
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process ID: 0x10fc
Faulting application start time: 0x01d531ccc606f71e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: unknown
Report ID: 1a066192-0dd5-4d78-80d9-3c4c1435e009
Faulting package full name: Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment]
@vivaladan have you installed Windows Terminal on another computer, perhaps one where PSCore 6 _is_ installed?

**Comment by vivaladan** [comment]
Yea, previous install had PSCore 6 installed, and not 7. I'm not on a domain, no roaming profile or such. I do use OneDrive so are you thinking something has synced through it?

**Comment by DHowett-MSFT** [comment]
Yes, we've got an open issue about settings roaming breaking people's configurations. We chose to use the "Roaming" application data folder, which _will_ apparently roam between computers with the same Store account. #1770

**Comment by DHowett-MSFT** [comment]
Also, the issue where removing powershell 6 crashes the terminal is #1458 :smile:

**Comment by DHowett-MSFT** [comment]
When I said 1458, I meant #982.
