### ISSUE TITLE
The results of the find are obscured by find view

### ISSUE THREAD

**Issue by julee** [microsoft/terminal#13990]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.19044.0

### Other Software

When I try to find some text, such as the word: target,

I got the result:
![image](https://user-images.githubusercontent.com/1493342/190113240-416e115a-73b1-4583-8ffd-76386ce6f63b.png)

The word is obscured  by the search view:
![image](https://user-images.githubusercontent.com/1493342/190113493-5e97c974-ce01-4013-a2f9-4cba17fd4606.png)

It's very troublesome because when we known the text have found, we always want to see the content near the result. 

### Steps to reproduce

Enough content output to windows terminal, make sure conent have more than one page.

They try to use the find view to find some text.

### Expected Behavior

The result not hidden by the text finding view

### Actual Behavior

The result obscured

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4407 for more discussion.

/dup #4407
