### ISSUE TITLE
Terminus TTF Font not rendering properly at certain sizes

### ISSUE THREAD

**Issue by fizz125** [microsoft/terminal#14006]
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.1826

### Other Software

Terminus TTF font installed from https://files.ax86.net/terminus-ttf/

WSL, running Ubuntu 20.04.1 LTS, SSHing into an Arch Linux machine

### Steps to reproduce

In the Font configuration menu, select "Terminus (TTF) for Windows"
Select a font size that doesn't correspond to a native bitmap size (eg. 14 pt)

### Expected Behavior

Terminus TTF Font renders as it does at a size corresponding to a native bitmap size

See example from Windows Terminal 1.14.2281.0
![terminus_14pt_1 14](https://user-images.githubusercontent.com/1494294/190281968-5fb90a45-4cca-4c90-95a1-cea31ddd8df2.png)

### Actual Behavior

Font renders with visible artifacting
![terminus_14pt_1 16](https://user-images.githubusercontent.com/1494294/190282018-922ad24f-0974-4806-b0ce-354ca35f3c41.png)

**Comment by elsaco** [comment]
@fizz125 the latest terminal release has the `AtlasEngine` enabled by default. If you turn if off `Terminus` will look better.

Size 14 with AtlasEngine on:

![atlas_engine_on_terminus](https://user-images.githubusercontent.com/3933920/190317316-b696367b-f004-4eb8-b21a-2f1f2dfecb11.png)

and with AtlasEngine off:

![atlas_engine_off_terminus](https://user-images.githubusercontent.com/3933920/190317377-81ac0240-cc59-455c-afa6-575d1047e888.png)

**Comment by jedieaston** [comment]
I'm noticing similarly weird rendering with CaskaydiaCove Nerd Font. 

New engine: 
![image](https://user-images.githubusercontent.com/21368066/190403747-04ee36a8-56eb-4b47-8e50-897a64e064b1.png)

Old engine:
![image](https://user-images.githubusercontent.com/21368066/190403981-334f8f68-4907-4d48-82bb-51260082b274.png)

The old engine makes the letters look rounder, fuller.

**Comment by lhecker** [comment]
@elsaco Thanks for the comparison!

The old text renderer rounds the font size to match the column width in pixel which appears to just so happened to have worked with Terminus TTF. The new text renderer doesn't do that anymore - if you specify 14pt you'll get _exactly_ 14pt. But Terminus TTF doesn't support 14pt. It only supports 13.5pt.

As such the solution to me seems like we should simply allow users to specify fractional font sizes. To test this idea I ran AtlasEngine with Terminus TTF at 13pt and 100% display scale. Then I replaced the `requestedSize.Y` with the fractional font size `13.5f` here:
https://github.com/microsoft/terminal/blob/e2b2d9b92cf75d7841c80b222be9100eabe093ac/src/renderer/atlas/AtlasEngine.api.cpp#L617-L618

Et voilà (`Old` = Windows Terminal 1.16, `New` = patched AtlasEngine)!

![fractional_font_size](https://user-images.githubusercontent.com/2256941/190433927-22517e3d-9a8c-481c-bea9-73f858374b71.gif)

---

@jedieaston I'm not convinced that the old version is better (`Old` = Windows Terminal 1.15, `New` = 1.16):

![CaskaydiaCove_AtlasEngine_comparison](https://user-images.githubusercontent.com/2256941/190409404-abd9657b-b90b-4cfa-bb53-aec6b5790f6b.gif)

**Comment by fizz125** [comment]
@elsaco Sure, that's the obvious workaround. But since this behavior isn't the same in the old engine, I wasn't sure if this was a regression or not.

@lhecker The documentation for the TTF font calls out that there may be issues with using the font at sizes for which there aren't bitmaps available, so if the answer is "Don't use Terminus TTF at non-bitmap-available sizes" then that's fine with me and this bug can be closed. But I wanted to make sure it wasn't a regression or an issue with the new engine

Thanks!

**Comment by zadjii-msft** [comment]
FWIW #6678 does have a lot of traction, so if it's "trivial" to just fix that, then maybe we should.

**Comment by lhecker** [comment]
> I wasn't sure if this was a regression or not.

I personally would consider it a regression, because even if it just randomly happened to have worked before, it definitely doesn't work now. I'm currently finishing a PR that will close #6678. Additionally it'll also fix some other issues in respect to your issue which will then definitely remove those gaps and draw pixel-perfect bitmap line drawings.

**Comment by jedieaston** [comment]
> @jedieaston I'm not convinced that the old version is better (Old = Windows Terminal 1.15, New = 1.16):

Yeah, I just started looking into it because it was different. My eyes have adjusted now though, thanks for looking into it!

**Comment by lhecker** [comment]
An upcoming version of Windows Terminal Preview will break the rendering for Terminus again. Instead you need to add a "cellHeight" override. Something like this for instance:
```cpp
{
    "profiles": {
        "defaults": {
            "font": {
                "face": "Terminus (TTF) for Windows",
                "size": 10,
                "cellHeight": "14px"
            }
        }
    }
}
```
