### ISSUE TITLE
Windows Terminal Preview v1.16.252 can not launch

### ISSUE THREAD

**Issue by zcg** [microsoft/terminal#14007]
### Windows Terminal version

1.16.252

### Windows build number

22000.978

### Steps to reproduce

1. download from github release
2. double click msix and install 
3. double click terminal preview bug in this ,there is no reaction
4. The right mouse on the desktop becomes stuck, and it becomes smooth again when it deleted

### Expected Behavior

it launch and the right mouse on the desktop becomes smooth 

### Actual Behavior

1. double click terminal preview bug in this ,there is no reaction
2. The right mouse on the desktop becomes stuck, and it becomes smooth again when it deleted

**Comment by zadjii-msft** [comment]
* Does anything show up in Event Viewer when you try running the Terminal/? 
* Is it _crashing_, or just failing to launch entirely? 
* Does `wt.exe` work? 
* Are you on an N sku PC by any chance?
* Did you disable UAC by any chance?
