### ISSUE TITLE
How to restore the last opened directories?

### ISSUE THREAD

**Issue by haquocviet** [microsoft/terminal#14004]
I am using WT 1.16 on Windows 10.0.19044.1889.
Though I choose "Open windows from a previous session" in settings, after restarting the WT, the tabs (of Command Prompt) are restored all to the same starting directory but not the previous opened directories. 
Do I miss something in the setting?

**Comment by zadjii-msft** [comment]
Did you configure your shell to tell the Terminal what the CWD is/?

Refer to: [Opening a tab or pane in the same directory in Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory)

**Comment by haquocviet** [comment]
Oh it works after I followed the link.
Thank you @zadjii-msft
