### ISSUE TITLE
The behaviour when the window loses focus is the opposite of what should happen

### ISSUE THREAD

**Issue by stibinator** [microsoft/terminal#14016]
### Windows build number

1.15.2524.0

### Steps to reproduce

Enable Acrylic blur for the terminal windows. Switch focus between the Terminal and another ap

### Expected Behavior

When gaining focus the window should become more opaque, when losing focus the window should become more transparent

### Actual Behavior

The inverse of the expected behaviour—when gaining focus the window becomes more transparent, when losing focus the window becomes completely opaque.

The issue is not necessarily the blur. A non-focussed window would be fine if it wasn't blurred, but it shouldn't be more opaque than a focussed window. If GPU resources are really that precious you could give the user the option to turn off blur for non-focussed windows (or just trust the user not to turn on the acrylic blur feature at all if their GPU is a potato).

**Comment by j4james** [comment]
See #7158 and #11092.

**Comment by zadjii-msft** [comment]
Yep.

/dup #7158 
/dup #11092
