### ISSUE TITLE
url not recognized fully

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#14010]
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.2006

### Other Software

![image](https://user-images.githubusercontent.com/2054302/190427106-210cae19-2a36-4db1-bfe3-a9a7839a878a.png)

### Steps to reproduce

ctrl click this url in powershell or WSL or cmd

https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpade/thinkpad-e14-gen-3-(14”-amd)/22tpe14e4a3

### Expected Behavior

recognize full length url

### Actual Behavior

recognizes only part of the url

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8321 for more discussion.

/dup #8321
