### ISSUE TITLE
After a period of inactivity, SSH will have no respond

### ISSUE THREAD

**Issue by jayagami** [microsoft/terminal#14019]
### Windows Terminal version

 1.14.2281.0

### Windows build number

10.0.19044.0

### Other Software

Thanks for your great works.
Honestly, Termianl is my favorite ssh client 😀 The connection is stored in the config file, so I can just open terminal and fire.

But the problem is , the SSH connection will be disconnected after a period of inactive. And the terminal doesn't give any information, it just can't do anything in the current tab unless you press ctrl+c to return to powershell.

I am not sure if it is a terminal problem, but other ssh client keeps connecting server.

### Steps to reproduce

1. start a ssh connection
2. do something
3. keep it backgroud for a while
4. return to this tab
5. There is no response until you press ctrl+s

### Expected Behavior

ssh connections are constantly open

### Actual Behavior

ssh have no respond

**Comment by lhecker** [comment]
> I am not sure if it is a terminal problem, but other ssh client keeps connecting server.

What is the other SSH client that works for you?

Is this maybe relevant to your issue? https://superuser.com/questions/468584/ssh-connected-terminal-windows-hang-in-vm-after-waking-host-from-sleep

As described here: http://manpages.ubuntu.com/manpages/jammy/en/man1/ssh.1.html#escape%20characters

I think it's not really that the Terminal is freezing, but rather that ssh doesn't realize it's disconnected and the remote host not responding to the TCP packets. I believe this requires setting keep-alive values to fix and is not specifically an issue with the terminal.

**Comment by jayagami** [comment]
> > 我不确定这是否是终端问题，但其他 ssh 客户端一直在连接服务器。
> 
> 其他适合您的 SSH 客户端是什么？
> 
> 这可能与您的问题有关吗？https://superuser.com/questions/468584/ssh-connected-terminal-windows-hang-in-vm-after-waking-host-from-sleep 如此处所述：http: [//manpages.ubuntu.com/manpages /jammy/en/man1/ssh.1.html#escape%20characters](http://manpages.ubuntu.com/manpages/jammy/en/man1/ssh.1.html#escape%20characters)
> 
> 我认为终端并不是真的冻结了，而是 ssh 没有意识到它已断开连接并且远程主机没有响应 TCP 数据包。我相信这需要设置 keep-alive 值来修复，这并不是终端的具体问题。


Thanks for your replying.
I think you are right, I missed the paramters

> > I am not sure if it is a terminal problem, but other ssh client keeps connecting server.
> 
> What is the other SSH client that works for you?
> 
> Is this maybe relevant to your issue? https://superuser.com/questions/468584/ssh-connected-terminal-windows-hang-in-vm-after-waking-host-from-sleep As described here: http://manpages.ubuntu.com/manpages/jammy/en/man1/ssh.1.html#escape%20characters
> 
> I think it's not really that the Terminal is freezing, but rather that ssh doesn't realize it's disconnected and the remote host not responding to the TCP packets. I believe this requires setting keep-alive values to fix and is not specifically an issue with the terminal.


Thanks for your answer.
I think you are right, I missed some SSH parameters
```
    ServerAliveInterval 300
    ServerAliveCountMax 2
```
Now I'll add it to my ssh config file and see if it's working.
