### ISSUE TITLE
Can't run Windows Terminal without changing the UAC (reset and reboot)

### ISSUE THREAD

**Issue by danishzubari** [microsoft/terminal#14011]
### Steps to reproduce

How can I fix this:
Via Change my UAC but the issue is why we have to change the UAC because its for our system Security.

### Expected Behavior

It should run fine without changing anything.

### Actual Behavior

Can't run Windows Terminal without changing the UAC (reset and rebot)

**Comment by DHowett** [comment]
Can you share what version of Terminal and what version of Windows you are using? You seem to have removed it from the template.

If you are getting an error message, can you also share what that message is?

We are not aware of any issues that would impact Terminal launch relating to UAC.
