### ISSUE TITLE
Closing terminal that was launched from another terminal instance minimizes the parent terminal

### ISSUE THREAD

**Issue by SaadAhmedGit** [microsoft/terminal#14012]
### Windows Terminal version

1.15.2525.0

### Windows build number

10.0.22000.0 (21H2)

### Steps to reproduce

1. Have anyother program opened up (a web browser in my case).
2. Launch terminal (any terminal app can be used here since I have tested it with VSCode's built-in terminal too)
3. Click on the icon of the other app that you opened in step 1 **from the taskbar**. The program should now be on top.
4. Click on the terminal program that you opened in step 2 **from taskbar**. The terminal should now be on top.
5. Type `start cmd` and hit enter (**make sure windows terminal is set as the default terminal**)
6. When the child terminal instance spawns, close it.

### Expected Behavior

After closing the child instance, the parent instance should be the one to stay on top.

### Actual Behavior

The parent terminal minimizes when we close the child instance and the program that we opened up in step 1 is now on top.

**Comment by carlos-zamora** [comment]
Hi @SaadAhmedGit. Sorry for the delay. Is this still happening for you on the latest Windows Terminal version?

**Comment by SaadAhmedGit** [comment]
No problem @carlos-zamora. Unfortunately, I have switched to Linux so I can't test this out on Windows but, iirc, it used to happen on multiple devices and not just on my laptop so if the above steps don't reproduce it, it might have been fixed.
