### ISSUE TITLE
Pop-up when using --version or --help

### ISSUE THREAD

**Issue by mverbaas** [microsoft/terminal#14017]
# Description of the new feature/enhancement

When using wt.exe --help or wt.exe --version you receive a nice pop-up window with the info. Wouldn't it be the more Windows Terminal way of working to send the output to the Terminal (just like git --version or others)?

# Proposed technical implementation details (optional)

Send the output of the commands to the terminal, instead of new windows that pops-up.

**Comment by JerBast** [comment]
This sounds similar to the issue being tracked in #7258

**Comment by mverbaas** [comment]
@JerBast , it is a duplicate. I'm. sorry I wasn't able to find the earlier mention. This can be closed (maybe with a link to the other?).
