### ISSUE TITLE
Atlas Engine: The cursor leaves artifacts when you delete a long line

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#14028]
### Windows Terminal version

1.16.2524.0

### Windows build number

10.0.22000.0

### Other Software

pwsh 7.2.6, PSReadLine 2.2.6
cmd.exe

### Steps to reproduce

Type long string and delete they by holding Backspace key pressed. 
This behavior is only then `"useAtlasEngine": true` 

![01](https://user-images.githubusercontent.com/78153320/190914018-ea9ad1b5-c8f3-4d22-a706-ef214f987a96.png)
![02](https://user-images.githubusercontent.com/78153320/190914030-cecc28cf-f948-45ee-a6d9-a49e544c85a7.png)
![03](https://user-images.githubusercontent.com/78153320/190914037-e2c06f41-90a2-445a-9bf6-0caca17190ac.png)

### Expected Behavior

No artifacts

### Actual Behavior

Deleting long line leaves artifacts.

**Comment by lhecker** [comment]
Actually I'm not entirely sure if this is an AtlasEngine issue... Cursor wrap around is just weird right now and my cursor vanishes / stops blinking when I wrap to the previous line with backspace.

**Comment by lhecker** [comment]
Figured it out: There's a different behavior regarding cursors between conhost and Windows Terminal. In case of the latter we don't necessarily call `PaintCursor` during cursor movement, because the cursor blinker never stops "blinking".
