### ISSUE TITLE
Wired behavior when insert characters using ALT+ASCII CODE in CMD

### ISSUE THREAD

**Issue by leoniDEV** [microsoft/terminal#1402]
# Environment

```
Windows build number: 10.0.18922.1000 and 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
cmd
```

# Steps to reproduce
 - Open CMD (whatever version listed above) session in the Terminal
 - try to insert an ascii key by:
   - press and hold  `ALT` key
   - digit whatever number (for example 126 corresponding to `~`)

# Expected behavior
a tilde (`~`) is inserted
![WinTerCMDok](https://user-images.githubusercontent.com/11667486/59962930-5756a680-94ec-11e9-956d-406008584227.png)

# Actual behavior

the ascii code (126) and a tilde is inserged
![WinTerCMD](https://user-images.githubusercontent.com/11667486/59962935-676e8600-94ec-11e9-9064-60154b122d9b.png)

**Comment by DHowett-MSFT** [comment]
Probably the same root cause as #1401
