### ISSUE TITLE
Tab color opacity

### ISSUE THREAD

**Issue by prodarma** [microsoft/terminal#14026]
I couldn't find any duplicates.

I've been messing around with the themes for a minute now and I've come to realize that there is no way to change the tab opacity? It's kinda bugging me.

Would be sick if that was implemented.

**Comment by zadjii-msft** [comment]
You should be able to set an opacity for the tab color just by using `#rrggbbaa` notation, where the `aa` is the alpha channel. Does that work for you? It's been a few months, but I think I did that in #13689?
