### ISSUE TITLE
Closing tab hangs when using VS Dev tools and Powershell Core

### ISSUE THREAD

**Issue by phil-scott-78** [microsoft/terminal#14032]
### Windows Terminal version

1.16.2524.0

### Windows build number

 10.0.25201.0

### Other Software

* Visual Studio 2022
* Powershell Core 7.2.6

### Steps to reproduce

1. Create a profile using `pwsh.exe` in Windows Terminal Preview
2. Execute the following lines to add the VS dev tools
```powershell
Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Enter-VsDevShell 8ee891c5 -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64"
```
3. Close the tab

### Expected Behavior

Tab closes quickly.

### Actual Behavior

wt locks up entirely doing...something. 

![Animation](https://user-images.githubusercontent.com/2447331/190947485-bf79b9ca-82a6-4de5-bb15-7987e7b4dc3d.gif)

I've tested this with the release version of Windows Terminal and also regular powershell.exe. Both of those don't exhibit the behavior. It is only with Powershell Core, the most recent release of wt.exe and the Visual Studio dev tools

**Comment by phil-scott-78** [comment]
I suspect you are right, I did a few heap dumps to see if I could spot anything of note and I noticed they were both hung on the same line related to the conpty connect, specifically this line https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalConnection/ConptyConnection.cpp#L557

**Comment by lhecker** [comment]
I debugged this just and and it's actually hung somewhere else for me:
(It's hung in `WaitForSingleObject(pPty->hConPtyProcess, INFINITE);`)

![image](https://user-images.githubusercontent.com/2256941/191125460-f1f9cf53-ab4d-4845-9959-942837b134d4.png)

**Comment by lhecker** [comment]
Ah right... The old version used to close the connection in the background only, so it didn't matter how long it took and it wasn't visually apparent either:
https://github.com/microsoft/terminal/commit/666c446bc38f741a7fc17b481ea1c665a4f31d13#diff-baa2e4fc26af1b8722a4eec13221622ef4ae566e4f7a8658bc58806f96b7e9b8L1525-L1526

But as mentioned in the PR, that's not viable at all, because that's a pretty nasty race condition.

**Comment by phil-scott-78** [comment]
@lhecker, I just double checked - I'm hung on the same line. The one I posted earlier was down further in the stack.
