### ISSUE TITLE
Option to disable dialog "Do you want to close all tabs?" like a checkbox in the dialog

### ISSUE THREAD

**Issue by nk54** [microsoft/terminal#14033]
Hello, I know it's possible to edit the json to add 
`"confirmCloseAllTabs": false,`

But it should be possible without having to search on the github issues to find there is a json setting available to do that.

It should be intuitive and easy to configure. Something like a checkbox in the dialog "never show this dialog again".

It's an issue from the UX point of view in my opinion.
Not hard to implement.

Anyway, thanks a lot. I lot Windows Terminal soooo much.

**Comment by OlafvdSpek** [comment]
An option to close the current tab when you click the button to (accidentally) close the window might be handy too.

**Comment by zadjii-msft** [comment]
This is getting added to the SUI in #14419, and the checkbox is tracked by #6641
