### ISSUE TITLE
Alt+Tab to Terminal adds an unwanted keyboard layout to Windows

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#14030]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.978

### Steps to reproduce

Alt+Tab to Terminal sometimes causes an unwanted keyboard layout appear in Windows. I'm having a WSLv1+python+selenium+chromedriver to headless Windows Chrome running inside Terminal.

I'm not 100% sure that it's Terminal causing this, since this bug reappears in Windows for at least 10 years. But when I'm running this workload in WT, this happens significantly more frequent -> sometimes a few times per minute.

### Actual Behavior

A US (qwerty) keyboard layout appears by itself in layout switcher after an Alt+Tab. This keyboard layout cannot be found in Windows Settings, and cannot be removed. Screenshot: https://twitter.com/vadimkantorov/status/1567715655092150280

**Comment by vadimkantorov** [comment]
This may coincide with launching a headless chrome.exe within WT in fact...

**Comment by zadjii-msft** [comment]
If you have a link to the feedback item you've filed, we can try and make sure it gets promoted to the right folks internally. But this does seem firmly outside the realm of "things the Terminal can fix".

**Comment by vadimkantorov** [comment]
> But this does seem firmly outside the realm of "things the Terminal can fix".

sure thing :(

> If you have a link to the feedback item you've filed,

One of mine is: https://aka.ms/AAi69jh , but there are a lot by other people, e.g. https://answers.microsoft.com/en-us/windows/forum/all/windows-keeps-automatically-adding-en-us-keyboard/69aaea0d-f588-4d54-89fa-a632ae7bced3 I think, this problem is there at least since Win10. But this chromedriver launch is the first time I got a stable repro. Unfortunately, no-one contacted me about any of my feedback issues. GitHub is so much better for providing feedback.

**Comment by lhecker** [comment]
As Mike already said, this does seem firmly outside the realm of "things the Terminal can fix". Because of this I'm going to close this issue.

Something similar to this does happen to me from time to time. As far as I know this happens when the keyboard related entries in the registry go out of sync and the state gets broken. You can find various (short term) bug fixes across the internet like this one: https://superuser.com/questions/1092246/how-to-prevent-windows-10-from-automatically-adding-keyboard-layouts-i-e-us-ke
But a proper fix is outside of this issue tracker's realm unfortunately.

**Comment by vadimkantorov** [comment]
I agree, it seemed more about selenium chrome driver + python script + launched from within Terminal than about Terminal.

This bug has been around for > 10 years, and it was impossible to get even any acknowledgement (including Feedback Hub). Just today it happened again, so I twitted - no response as usual: https://twitter.com/vadimkantorov/status/1636290415941808128

It would be so much better if MS opened a public GitHub repo and issues for Windows and other apps. IMO Feedback hub is too clumsy and it kills engagement (e.g. I never saw anyone posting links to Feedback Hub issues for discussion).

**Comment by pavel-stupka** [comment]
I've been fighting this annoying bug for years and finally got fed up enough to write my own fix. Built it with Claude Code running Claude Opus 4.6 driven by the GitHub Spec Kit workflow.

Repo: https://github.com/pavel-stupka/windows-keyboard-layout-fix

**Comment by vadimkantorov** [comment]
@zadjii-msft I reported the related Windows Update bug in Feedback Hub: https://aka.ms/AA10j44u

It got fused into a collection https://aka.ms/AAm8j0a. The collection has a "posted solution", but the solution is not relevant and does not solve anything. @zadjii-msft Could you please signal this internally? Unfortunately there is no way in Feedback Hub to signal "no, the posted solution is deflecting/bogus, the bug is still present"

The bug is present for 15 years.
