### ISSUE TITLE
Blue Screen

### ISSUE THREAD

**Issue by jl1998** [microsoft/terminal#1403]
# Environment

Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): Windows Terminal Preview (0.2.1715.0 / date: 22.06.2019) (and versions befor)

# Steps to reproduce

Every time I click on the Settings button. (I don't know why, but only on my laptop)

# Expected behavior

Open the Settings File

# Actual behavior

Windows Blue Screen.
[
![IMG_20190622_123948](https://user-images.githubusercontent.com/19290969/59962936-6fc6c100-94ec-11e9-9b24-cc2ae7e32ac6.jpg)
](url)

**Comment by Gnbrkm41** [comment]
What's your default file association app for .json files? Just wondering.

**Comment by jl1998** [comment]
I use Visual Studio Code as default. I can start with other Programms .json files.

**Comment by jl1998** [comment]
I thought maybe the installation failed. But reinstalling never helped (for weeks on). Hardly after I have opened a report and reinstalled again, it seems that it works (mysterious).
Maybe it can be closed? (strange)
