### ISSUE TITLE
Can we reenable the spelling bot

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#14037]
# Description of the new feature/enhancement

I'm not entirely sure if this is intentional, but we haven't been running the spelling check on PRs for a while now, and the spelling mistakes are starting to accumulate. I'm aware of PR #13616, but I didn't think that would mean we'd stop checking spelling altogether.

# Proposed technical implementation details (optional)

I'm not sure, but I'd be perfectly fine with just reverting #13616 if that's what it takes.

**Comment by zadjii-msft** [comment]
This was actually disabled because of https://github.com/check-spelling/check-spelling/security/advisories/GHSA-p8r9-69g4-jwqq. We can reenable this when there's a v0.0.21 (doesn't look like it yet: https://github.com/check-spelling/check-spelling/releases)

**Comment by zadjii-msft** [comment]
(that might not be a publicly visible link, in retrospect. in short: there's a security issue with v0.0.20.)

**Comment by DHowett** [comment]
BOOM! W
e're back in business!
