### ISSUE TITLE
Capability to set a alternative default profile when launchen the terminal over the windows explorer context menu

### ISSUE THREAD

**Issue by dfoxg** [microsoft/terminal#14043]
# Description of the new feature/enhancement

At the moment we can specify the default profile when the windows terminal is getting started. Under Windows 11 I miss the option, to specify which profile should be getting used when i start the terminal over the windows explorer context menu.

At least in my setup i´m normaly using `WSL` so thats my standard profile. But when I´m starting the terminal over the context menu, i want to use `cmd`. Of course i can manually open the `cmd` but then i´m losing the directory context and have to manually `cd` into the right path.

I would love to see an option where i can specifiy, which profile should be used when the terminal is getting started over the explorer context menu.

# Proposed technical implementation details (optional)

Maybe a second dropdown in the settings?

**Comment by zadjii-msft** [comment]
Alternatively, would #6111 work for you/? Instead of specifying a different default profile for the context menu, just changing the menu to allow you to pick whichever profile you want?

**Comment by dfoxg** [comment]
@zadjii-msft yes, that would be working too. Looks like a more straight forward solution! I will close this issue in preference for #6111
