### ISSUE TITLE
Unable to find selected font bug is BACK

### ISSUE THREAD

**Issue by cmdshft** [microsoft/terminal#14049]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.22621.0

### Other Software

Oh My Posh!

### Steps to reproduce

Open Terminal

### Expected Behavior

No popup warning saying unable to locate the font.

### Actual Behavior

When opening the terminal, a new popup says:

`Warning
Unable to find the selected font "<font>"
"Consolas" has been selected instead.
Please either install the missing font or choose another one.`

![image](https://user-images.githubusercontent.com/8571823/191371951-bdf62528-492a-4af9-9549-63f32e8bc544.png)

**Comment by lhecker** [comment]
That particular font bug actually never went away. You have to install fonts system-wide, because user-fonts seem to be broken since forever. Their existence seems to simply vanish for some reason after rebooting. And yeah, this is _extremely_ annoying for me as well. 😕

/dup #3257
