### ISSUE TITLE
[Feature Request] Add an Option to Set Windows Terminal as Default Terminal in Windows 10

### ISSUE THREAD

**Issue by RoyiAvital** [microsoft/terminal#14044]
# Description of the new feature/enhancement

Add the option to make Windows Terminal the default terminal for Windows 10.

# Proposed technical implementation details (optional)

Copy the feature from Windows 11.

**Comment by zadjii-msft** [comment]
Please [read the FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#will-the-default-terminal-functionality-be-coming-to-windows-10).

> ### Will the default terminal functionality be coming to Windows 10?
> Nope. That feature is going to remain a Windows 11-only feature. It's powered by a fairly large feature change to the OS, which is unlikely to be serviced as a "bugfix" to earlier OS versions.

**Comment by RoyiAvital** [comment]
@zadjii-msft , But you used to have that feature in preview build of the terminal. So what happened?

**Comment by zadjii-msft** [comment]
The Default Terminal feature requires cooperation between the Terminal and the OS. Official Windows 10 OS builds never had support. There was one or two insiders builds of Windows 10 that might have had parts of the code, but ultimately those build numbers turned into Windows 11 by the time they were stable. It was just a quirk of the Windows 10 -> 11 transition. Those builds might have originally been pushed as "windows 10 insiders", but they were _really_ preview builds of Windows 11 code.
