### ISSUE TITLE
SettingsModelLocalTests failures are on the rise

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#14050]
### Windows Terminal version

Commit 1ce22a87e6fc204b5fd98642723aa0a51a503749

### Windows build number

10.0.19044.1889

### Steps to reproduce

!. Check out a recent version of the project.
2. Build it.
3. Run the unit tests.

### Expected Behavior

All tests should pass.

### Actual Behavior

A number of `SettingsModelLocalTests` are failing:

    SettingsModelLocalTests::DeserializationTests::TestCloseOnExitParsing [Failed]
    SettingsModelLocalTests::SerializationTests::Profile [Failed]
    SettingsModelLocalTests::SerializationTests::Actions [Failed]
    SettingsModelLocalTests::SerializationTests::LegacyFontSettings [Failed]

If I remember correctly, the first one has been around for a while now. I'm afraid I've just been ignoring it and hoping somebody else would notice. The others I think are fairly recent. Although I may be misremembering which are old and which are new.

**Comment by j4james** [comment]
Looking at the test logs for those last three, it seems the failures are a result of a change in serialization of the font size from int to float (I suspect PR #14013).

The older one I suspect is the result of the new `Automatic` mode for `CloseOnExit` (PR  #13560).

**Comment by lhecker** [comment]
I keep forgetting that we don't run them in the CI... 😞
