### ISSUE TITLE
Applications behind transparent and full sceen mode not re-rendered

### ISSUE THREAD

**Issue by pecorarista** [microsoft/terminal#14059]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.0

### Other Software

Google Chrome 105.0.5195.127
Firefox Browser 105.0

### Steps to reproduce

Case 1
1. Open a terminal window and set `Background opacity` < 100%, for example 80%.
2. Set full screen mode.
3. Play a video on the browser.

Case 2
1. Open a terminal window and set `Background opacity` < 100%, for example 80%.
2. Set full screen mode.
3. Run a continuous build system on your web application code.
4. Make a change on the code and make the system re-render the window.

### Expected Behavior

The contents behind the terminal is re-rendered.

### Actual Behavior

Case 1
Google Chrome: The video soon becomes black screen while the sound is being still played.
Firefox: The video stops after a while, showing the shot at the point and playing the sound.

Case 2
Google Chrome: The content is not rendered. For example, if the background of a web page is white, the screen gets white.
Firefox: The window looks the same.

**Comment by pecorarista** [comment]
This is a screenshot of Case 1.

![video-behind-transparent-terminal](https://user-images.githubusercontent.com/8929103/191664516-31a5e6e4-4eba-4e05-943c-ced73bc8348f.png)

**Comment by DHowett** [comment]
Thanks for the report!

I believe these applications can detect that there is a window in front of them and will not waste resources when that is the case. I have successfully conducted a Zoom and Teams call behind a Terminal, which suggests that it is _possible_.

I don't know if there is anything we can do about this. Hmm.

**Comment by pecorarista** [comment]
@DHowett Thank you.
I started doubting that the problem is not a bug of Windows Terminal.
This is because I found a solution for Google Chrome:

Set `chrome://flags/#calculate-native-win-occlusion` Disabled.
https://support.google.com/chrome/thread/77201393/videos-turn-black-when-a-full-screen-window-is-on-top-of-the-window-playing-the-video?hl=en

I confirmed it worked.

**Comment by pecorarista** [comment]
I also found a solution for FireFox:
Open `about:config`, search for `widget.windows.window_occlusion_tracking.enabled` , and set it false.

I'm sorry that I reported a problem not caused by Windows Terminal and solved myself.
I hope this issue helps people having the same problem.

**Comment by DHowett** [comment]
> I'm sorry that I reported a problem not caused by Windows Terminal and solved myself.

You do not need to apologize! This is great information we can share with other users! 😄

**Comment by p0lyMth** [comment]
> @DHowett Thank you. I started doubting that the problem is not a bug of Windows Terminal. This is because I found a solution for Google Chrome:
> 
> Set `chrome://flags/#calculate-native-win-occlusion` Disabled. https://support.google.com/chrome/thread/77201393/videos-turn-black-when-a-full-screen-window-is-on-top-of-the-window-playing-the-video?hl=en
> 
> I confirmed it worked.

I have verified this solution works for firefox.

**Comment by pecorarista** [comment]
In recent versions of Chrome, the above option has been removed, so you need to launch it with `--disable-features=CalculateNativeWinOcclusion` instead.
In other words, add this to the end of the shortcut's target.
