### ISSUE TITLE
Right click a folder named "test[", choose open in Windows Terminal, open Terminal in C:\

### ISSUE THREAD

**Issue by sheuronazxe** [microsoft/terminal#14065]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Right click and choose Open in Windows Terminal any folder with character [ in name

### Actual Behavior

Windows Terminal opens in C:\

**Comment by zadjii-msft** [comment]
This is /dup #11149. This is a bug in Windows PowerShell (5.1) -- sorry! There's nothing that can be done about that. It does not handle directories with special characters in them properly.
