### ISSUE TITLE
Terminal looks completely incorrect.

### ISSUE THREAD

**Issue by githubcatw** [microsoft/terminal#1406]
Hello.
I downloaded Terminal from Windows Store, and it looks different from the promos and other screenshots.
![t1](https://user-images.githubusercontent.com/17374742/59964573-803e6200-9513-11e9-9e05-02d10d77a007.png)
The window color is white, even though I have dark mode.
And also: I set my theme to "One Half Dark" (ColorTool has it), but all 3 environments (cmd, PowerShell and Ubuntu) have different styles from each other and my set theme.
![t2](https://user-images.githubusercontent.com/17374742/59964605-d14e5600-9513-11e9-9752-9b6c0276cced.png)

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

**Comment by JushBJJ** [comment]
Maybe try to customise it more. I know, default designs suck.

**Comment by githubcatw** [comment]
I was able to make the styles the same for all shells. It now looks like this:
![tbetter](https://user-images.githubusercontent.com/17374742/59964744-d6140980-9515-11e9-8d35-aa7d22141e40.png)
But the border is still white.

**Comment by zadjii-msft** [comment]
This is largely #1375

**Comment by JushBJJ** [comment]
Was about to say that, you beat me into it!
