### ISSUE TITLE
Allow more modal editor support

### ISSUE THREAD

**Issue by jakegallow** [microsoft/terminal#14067]
# Description of the new feature/enhancement

Windows terminal already supports a "mark mode", I think the user should be allowed to define different actions for this mode and rebind their keys to whatever seems nessecary. For example, if I go into "markmode" i should be able to navigate in any direction with keys of my choosing, or search for text with a key of my choosing. For instance, instead of using the "up" key to navigate upwards lines i should be able to rebind that to 'k' once i'm in this mode. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Oh hey look, I found the dupe on the backlog: /dup #11868
