### ISSUE TITLE
Disappering window after curl command

### ISSUE THREAD

**Issue by lbaiao** [microsoft/terminal#14062]
### Windows Terminal version

1.14.2282

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.2.6

### Steps to reproduce

Run `wt curl microsoft.com && ping microsoft.com -t` in Windows Terminal in a PowerShell shell.

### Expected Behavior

The Terminal should open a new Terminal window. Following, in the newly open window, it should run the `curl` command. After the `curl` command finishes, it should run the `ping` command, all in the same window.

### Actual Behavior

The Terminal opens a new window and runs the `curl` command in this newly open window. After the `curl` command completion, it closes the new window and runs the `ping` command in the original window, where the whole command was input originally.

**Comment by lhecker** [comment]
`&&` has a special meaning to PowerShell and separates two commands. It's like writing `;` in C-like languages. For instance try running this:
```pwsh
echo 1 && sleep 1 && echo 2
```

Furthermore, `wt` expects a command-line as the argument, which means that the first argument is interpreted as an executable name and all remaining arguments are passed to that executable. `curl` doesn't know what `ping` is. You have to launch a shell first, like `pwsh`, to make such concepts work.

So to make your command work try running this:
```pwsh
wt pwsh -c "curl microsoft.com && ping microsoft.com -t"
```

It instructs `wt` to spawn the executable named `pwsh` and passes it 2 parameters: `-c` which is short for `-Command` and the long string is the command argument. It tells `pwsh` to run the string as if it were a command.

**Comment by lbaiao** [comment]
Thanks a lot. Sorry for raising this issue, since it was not a bug after all. I read the documentation [here](https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=powershell), but I could not find this `pwsh -c` command in there. I thought it was a bit confusing. Maybe this documentation could be improved.

Also, thanks for the PowerShell explanation.

**Comment by lhecker** [comment]
That's not a problem. I'm glad I could help!
