### ISSUE TITLE
error 2147943140 (0x800702e4) after Windows 11 22H2 Upgrade

### ISSUE THREAD

**Issue by hl2guide** [microsoft/terminal#14063]
### Windows Terminal version

1.15.2525.0

### Windows build number

Microsoft Windows [Version 10.0.22621.521]

### Steps to reproduce

1. Upgrade Windows 11 to Windows 11 22H2
2. Run Terminal

### Expected Behavior

PowerShell 7 tab loads up.

### Actual Behavior

```
[error 2147943140 (0x800702e4) when launching `"C:\Program Files\PowerShell\7\pwsh.exe"']
```

**Comment by lhecker** [comment]
`0x800702e4` is `ERROR_ELEVATION_REQUIRED`. Can you check whether you have marked `pwsh.exe` as requiring elevation ("Run as Administrator")? If you keep that flag turned on, terminal will not be able to launch it.

**Comment by hl2guide** [comment]
@lhecker ah that fixed it.
