### ISSUE TITLE
Bad rendering of icons (nerd fonts) with atlas rendering

### ISSUE THREAD

**Issue by stephc-int13** [microsoft/terminal#14074]
### Windows Terminal version

1.16.2524.0

### Windows build number

build 25206.1000 (rs-prerelease)

### Steps to reproduce

Simply use nerdfont icons in terminal

### Expected Behavior

Most icons use wider spacing for icons, which was correctly recognized and rendered by the previous renderer.
Now that the optimized atlas rendered is used by default there is no way to display icons properly.

### Actual Behavior

Nerdfont Icons are rendered at the same cell size as character, they should be rendered almost 2x wider.

I noticed this issues previously when I tried the experimental font renderer, and now it is by default.

**Comment by lhecker** [comment]
Thanks for the bug report! If you don't mind, I'm going to continue tracking the issue with nerd font glyphs in #14022, which was the first issue to report it.

/dup #14022
