### ISSUE TITLE
Firacode Minimized Text - Bug Report

### ISSUE THREAD

**Issue by NickITGuy** [microsoft/terminal#1407]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

Download and Install Firacode,
Download and Install Windows Terminal Preview
Open Settings and set fontfamily to Firacode

# Expected behavior

Font switches to Firacode

# Actual behavior

Text goes supper minimized increasing font size only makes it smaller.
Also it will crash on launch, needing a revert to consolas to launch.
![Annotation 2019-06-22 231820](https://user-images.githubusercontent.com/4210158/59964755-1be7c680-9544-11e9-96b5-12deb2cdd3da.png)

**Comment by NickITGuy** [comment]
This persists across all different profiles to.
![Annotation 2019-06-22 233141](https://user-images.githubusercontent.com/4210158/59964886-11c6c780-9546-11e9-89aa-e0aeed7ca9f8.png)
![Annotation 2019-06-22 233225](https://user-images.githubusercontent.com/4210158/59964887-125f5e00-9546-11e9-9576-3e834aaec919.png)

**Comment by walshg3** [comment]
@NickITGuy In the future its important to attach your profiles.json file as well for debugging. I was able to reproduce the issue and the issue would happen if you made the "fontFace" tag anything but an actual font (Try leaving the font blank). 

The solution is typing the name Fira Code correctly. 
"fontFace" : "Fira Code",
Worked with no issues and Ligatures work as well. 

Good Luck!

**Comment by DHowett-MSFT** [comment]
This will happen if you spell the name of the font wrong. It’s a duplicate, but I don’t know the number right now.
