### ISSUE TITLE
backspace breaks apart multibyte characters

### ISSUE THREAD

**Issue by aetonsi** [microsoft/terminal#14084]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.978

### Other Software

powershell core

```
Name             : ConsoleHost
Version          : 7.2.6
InstanceId       : 098117ae-601b-414f-851f-2c7afccd06c4
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : it-IT
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Steps to reproduce

1. copy multibyte character to clipboard, for example 🙂
2. paste it in the terminal
3. press backspace

### Expected Behavior

The backspace should delete the entire multibyte character, so typing `echo "🙂<backspace>" <enter>` in `pwsh` would be the same as typing `echo "" <enter>` (should print an empty string).

### Actual Behavior

When pressing backspace, the character is instead broken in a couple of � � characters, and the backspace deletes the second �, leaving the first one, which, if sent to `pwsh`, breaks everything (see here: https://github.com/PowerShell/PSReadLine/issues/2358#issuecomment-1258562344)

**Comment by aetonsi** [comment]
might be related to #12537 or #1802

**Comment by DHowett** [comment]
Thanks for the report! Unfortunately, the handling of multi-byte sequences at a shell's "input line" is up to that shell. You may need to reopen this issue over on the PowerShell or PSReadline repository. Sorry!

**Comment by aetonsi** [comment]
FYI and future reference see here: https://github.com/PowerShell/PSReadLine/issues/2358#issuecomment-1258562344

**Comment by DHowett** [comment]
Thank you! :smile:
