### ISSUE TITLE
Clear to end of line doesn't work correctly with reverse mode

### ISSUE THREAD

**Issue by RadAd** [microsoft/terminal#14087]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.19044.2006

### Steps to reproduce

Clear to end of line `\x1b[0K` not behaving correctly in combination with reverse mode `\x1b[7m`.

```
#include <cstdio>

int main()
{
    printf("\x1b[34;43mLine 1\x1b[0K\n");
    printf("\x1b[7mLine 2\x1b[0K\n");
    printf("\x1b[0m\x1b[0K\n");
}
```

### Expected Behavior

Under the old console I get this:
![image](https://user-images.githubusercontent.com/2518689/192430291-e4d28796-a17f-4b90-a61f-db4059b7b5b4.png)

### Actual Behavior

In the new terminal I get this:
![image](https://user-images.githubusercontent.com/2518689/192430364-abc913ab-1d4e-42e1-9419-f9ac3c14c0ec.png)

**Comment by 237dmitry** [comment]
Try `\x1b[k` instead of `\x1b[0K`

![Screenshot 2022-09-27 100021](https://user-images.githubusercontent.com/78153320/192455874-24b05e63-abe1-4130-9a0b-88ae92b63a78.png)

**Comment by RadAd** [comment]
Your test should have been 
```
"`e[34;43mLine 1`e[K`n`e[7mLine 2`e[K`n`e[0m`n"` to match my test.
```
Also, your screenshot doesn't look correct. It should be cleared out to the end of the line. I think it's because you used the lowercase K. I believe these CSI sequences are case-sensitive.
In any case, your suggestion didn't change my results.

**Comment by j4james** [comment]
@RadAd The behavior you were seeing in the old console was a bug that has since been fixed. The erase operations (like `EL`, `ED`, and `ECH`) are meant to fill the affected area with empty rendition attributes (i.e. thing like underline and reverse video aren't meant to be applied).

**Comment by RadAd** [comment]
Is the fix going to be applied to Windows 10?

**Comment by DHowett** [comment]
Unlikely. For Windows 10, the fix will be distributed via Windows Terminal.

**Comment by RadAd** [comment]
Does updating Windows Terminal fix the issue in the old console?

**Comment by DHowett** [comment]
Unfortunately, it won't. ☹️
