### ISSUE TITLE
The "!=" character sequence (et.al.) is forcibly translated to "≠" and thus not a faithful representation

### ISSUE THREAD

**Issue by ethzero** [microsoft/terminal#14083]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1) Launch any command interpreter
2) Type or display the following ascii sequence: "!=" (without quotes) anywhere in the terminal window
3) Window Terminal performs a unwarranted translation to the "≠" character, and thus not a true reproduction of, for example a file's content.

In a nutshell: "!=" != "≠"!

### Expected Behavior

For Windows Terminal not to translate any character sequences allowing users to view file contents in particular, faithfully.

### Actual Behavior

"≠"

**Comment by ethzero** [comment]
UPDATE: It just struck me, fonts can technically re-render when presented an compound sequences, i.e. unicode.
The issue above was using _CaskaydiaCove Nerd Font Mono_ (typically used with PoSH).
Simply reverting the font to _Cascadia Mono_ restores the expected behavior.
To my surprise, _Cascadia Code_ also exhibits this "translating" behavior but in a slightly different manner.

Apologies as this is not likely an issue with Windows Terminal but a bafflingly side-effect of using a "fancy" font for the terminal.

**Comment by DHowett** [comment]
Thanks for the report! Fonts with "coding ligatures" will be rendered using coding ligatures. This part is expected :smile:
