### ISSUE TITLE
Terminal failed to build with error MSB8020 on MSVC

### ISSUE THREAD

**Issue by nnfdnkns** [microsoft/terminal#14096]
### Steps to reproduce

Terminal failed to build with error MSB8020:The build tools for v143 (Platform Toolset = 'v143') cannot be found.  add /p:PlatformToolset=v142, It also failed.

**repro steps:**
1.git -C "F:\gitP" clone https://github.com/microsoft/terminal microsoft\terminal
2.cd F:\gitP\microsoft\terminal
3.set path=F:\gitP\microsoft\terminal\dep\nuget;%PATH%
4.nuget restore OpenConsole.sln 2>&1
5.set _CL_=/wd4189 /wd5104 /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS %_CL_%
6.msbuild /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22000.0 /p:PlatformToolset=v142 OpenConsole.sln /t:Restore /t:Rebuild 2>&1

### Expected Behavior

Terminal could build successfully

### Actual Behavior

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(331,5): error MSB4036: The "GetFrameworkSdkPackages" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin" directory. [F:\gitP\microsoft\terminal\src\cascadia\CascadiaPackage\CascadiaPackage.wapproj]

**Comment by j4james** [comment]
I think the problem is that you're using Visual Studio 2019, while Terminal requires Visual Studio 2022. See the prerequisites here: https://github.com/microsoft/terminal#prerequisites

**Comment by zadjii-msft** [comment]
@nnfdnkns can you confirm which version of VS you're using to build/?

**Comment by duggi-9977** [comment]
I guess you should upgrade the project to use the current Visual Studio toolset, or use the Visual Studio Installer to install the specified build toolset. Check this link to modify your VS: https://learn.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2022.

Additionally: In Visual Studio, in Solution Explorer:
(1) open the shortcut menu for your project (not for your solution) and then choose Properties to open your project Property 
      Pages dialog box.
(2) In the Property Pages dialog box, open the Configuration drop-down list and then select All Configurations.
(3) In the left pane of the dialog box, expand Configuration Properties and then select General.
(4) In the right pane, select Platform Toolset and then select the toolset you want from the drop-down list (2022_
(5) Click OK

**Comment by nnfdnkns** [comment]
@zadjii-msft version of VS is vs2019
