### ISSUE TITLE
Strange behaviour of Delete Line and Insert Line when used above the top margin

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#141]
* Your Windows build number:

Microsoft Windows [Version 10.0.16299.309]

* What you're doing and what's happening:

I was curious to see how the _Delete Line_ (`\033[M`) and _Insert Line_ (`\033[L`) escape sequences would behave when applied above the top margin of the scrolling region. So as a test, I labelled the first 8 lines of the screen with the numbers 1 to 8, set the top margin to line 4, then attempted to delete line 1.

This was the command I used:

    printf "\033c1\n2\n3\n4\n5\n6\n7\n8\033[4r\033[H\033[M\033[r" && read -n 1

And this was the output I saw:

    1
    2
    3
    8

Instead of 1 row being deleted from line 1, I got 4 rows deleted from line 4.

I then tried the same thing with the _Insert Line_ sequence:

    printf "\033c1\n2\n3\n4\n5\n6\n7\n8\033[4r\033[H\033[L\033[r" && read -n 1

And the output this time was:

    1
    2
    3
    6
    7
    8

Instead of 1 row being inserted at line 1, I got 2 rows **deleted** from line 4!

* What's wrong / what should be happening instead:

I don't think there is necessarily a "correct" behaviour in this situation, but I do think the current Windows behaviour is probably a bug.

One possible option would be to ignore these commands when used outside the defined margins (which I think is what XTerm does). Another option would be to handle the insert and delete as if the top margin had not been set, but still constrain the scrolling region within the bottom margin (which is how the Linux console behaves). Either choice would be preferable to the current behaviour.

**Comment by zadjii-msft** [comment]
Boy I do love bugs with great straightforward repros. I also really love x forwarding working in WSL, because this becomes a really easy question to answer:

![image](https://user-images.githubusercontent.com/18356694/38047838-82d09bf4-3278-11e8-8d11-957e0bf9079f.png)

Clearly, we're not doing the right thing here. Even if there isn't a documented "right" way to do something, we're treating whatever xterm does as the right way

Filing a bug to address this.

**Comment by zadjii-msft** [comment]
@j4james You're kinda going wild on the scrolling margins style bugs right now, you want me to give you this one too?

**Comment by j4james** [comment]
Ah yes, I've been meaning to come back to this. I think what we have now is actually the correct behaviour and we can close this issue.

Here's what the DEC STD 070 manual has to say about the _Insert Line_ command:

> Only that portion of the display between the top, bottom, left, and right margins is affected. IL is ignored if the Active Position is outside the Scroll Area. 

Similarly for the _Delete Line_ command:

> Only that portion of the display between the top, bottom, left, and right margins is affected. DL is ignored if the active position is outside the scroll area. 

So both of the test cases above should leave the numbers unchanged after the IL or DL since the cursor position is above the top margin. And that's how XTerm interprets it too:

![image](https://user-images.githubusercontent.com/4181424/64282441-565ede00-cf4d-11e9-93a2-a0915d9e794a.png)

So I think putty has probably got this wrong, and if we're matching XTerm then we've got it right.

**Comment by DHowett-MSFT** [comment]
Really happy to hear that. Thank you!
