### ISSUE TITLE
Shortcut for toggling always on top

### ISSUE THREAD

**Issue by RiteshChepuri** [microsoft/terminal#14103]
# Shortcut for toggling always on top from the dropdown menu

# Proposed technical implementation details (optional)

**Comment by carlos-zamora** [comment]
An action for toggling "always on top" mode already exists via the `toggleAlwaysOnTop` JSON action ([docs](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#toggle-always-on-top-mode)). You can bind this to any key chord you want to make a keyboard shortcut. It should also already be accessible in the Command Palette.

On the other hand, if what you're specifically asking for is to be able to add this action to the dropdown menu, we're tracking Dropdown Menu Customization here: https://github.com/microsoft/terminal/issues/1571. At the moment, there's a PR open for adding nested profiles and introducing the new JSON structure, but I would bet once that merges, the actions part won't be that difficult to add.
