### ISSUE TITLE
Can't find the release for the currently installed version (v1.15.2713.0)

### ISSUE THREAD

**Issue by gaia** [microsoft/terminal#14101]
running v1.15.2713.0

![image](https://user-images.githubusercontent.com/87547/193125198-b7a143fa-4d6f-444b-9b7f-cb41a7109938.png)

installed from the store

![image](https://user-images.githubusercontent.com/87547/193125376-8846684f-f58f-4965-8651-8855d6a153ee.png)

but there is no release or tag for this version here. where can I see the release notes for THIS version?

**Comment by zadjii-msft** [comment]
That's a good question. I bet that's the version that comes with the OS. Those commits are technically built from the Windows OS source tree, separate from Github, but we really _should_ be pushing those tags publicly (or, at very least, tagging the equivalent commit)

**Comment by gaia** [comment]
indeed, it would make bug reporting (none from my POV ATM) easier to track. feel free to close. thanks!
