### ISSUE TITLE
reconnect to terminal

### ISSUE THREAD

**Issue by sreekanth-yalachigere** [microsoft/terminal#14108]
I lose ssh connection if my vpn disconnects for some reason. Is there a way to use the same tab to reconnect? like you press "r" to reconnect?

Thank you

**Comment by j4james** [comment]
I don't think there is a way to do this yet. But assuming you've configure your SSH connection as part of your profile, then all that is missing is the ability to force the profile to reload, which is issue #3726. Or possibly have it reload automatically, which is issue #4379.

**Comment by carlos-zamora** [comment]
Thanks for the request, we're already tracking this over in #4379

FYI: I think there's also already a PR out for this ;)

/dup #4379
