### ISSUE TITLE
Support random background image

### ISSUE THREAD

**Issue by MarcusMors** [microsoft/terminal#14111]
# Description of the new feature/enhancement

I love that windows terminal let's me set my fav images as backgrounds, but I wish I could pick more bgs or let the terminal pick a **random** one (your fav bg will get boring after some months).

I would like that every time I open a new terminal (or session, i mean the whole app), I see a new image as background, or the terminal picks an image_path from a list.

there is a similar feature request: #9422 

# Proposed technical implementation details (optional)

Introduce a keyword like `random` or a `setting` for your settings.json
or a `"pickBackgroundImage": [ "foo", "bar", "baz"]`

**Comment by j4james** [comment]
This sounds like it would probably be covered by issue #3900 (assuming that includes the "shuffle" option).

**Comment by carlos-zamora** [comment]
Thanks for the feature request. I'm going to consolidate this with #3900 and make that a whole issue for how to handle multiple background images.

/dup #3900
