### ISSUE TITLE
Declaration of the keybinding is lost after saving

### ISSUE THREAD

**Issue by mrmlnc** [microsoft/terminal#1411]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

* Open settings
* Change keys for the `nextTab` action: `ctrl+tab` → `alt+}`.
* Save settings
* Reload terminal
* Open settings

# Expected behavior

* I can use `alt+}` as keybinding for the `nextTab` action.
* Or at least I can find my declaration for the `nextTab` action.

# Actual behavior

I cannot find a declaration for the `nextTab` action in the `profiles.json` file.

**Comment by DHowett-MSFT** [comment]
I bet we delete key bindings that cannot be deserialized. Thanks!

**Comment by DHowett-MSFT** [comment]
We do.

**Comment by zadjii-msft** [comment]
I'd say this is actually more accurately #1212
