### ISSUE TITLE
Add support for Windows clipboard history (Win+V) in bash

### ISSUE THREAD

**Issue by happylynx** [microsoft/terminal#14115]
Add support for Windows clipboard history activated by Win+V in bash.

* When running PowerShell, paste from clipboard history works ok.
* When running bash in its own window (i.e. not using Window Terminal, from MSYS2 project or Git), paste from clipboard history works ok.
* When running bash in Windows Terminal window (in any way - `C:\Windows\System32\bash.exe`, from Windows Subsystem for Linux, executable from Msys2, ssh connection to a Linux machine) and paste from clipboard history is activated, it does nothing for the first time and it prints `^V` for the second time.

#### Version 
Windows Terminal Preview, Version: 1.16.2642.0

**Comment by zadjii-msft** [comment]
Do you have `ctrl+v` bound to paste in your settings/? Clipboard History works by just sending a literal ctrl+v key to the window, so if that's not bound to paste, then it won't work for pasting.

**Comment by SaltyChiang** [comment]
@zadjii-msft It is annoying to bind `ctrl+v` to paste while using vim. Vim default bind `ctrl+v` to toggle visual block mode which is very useful. Is there any workaround to make clipboard history work without editing the default key binding in vim?

**Comment by zadjii-msft** [comment]
This is just a quick thought, but you might be able to bind ctrl+v to `multipleActions([paste, sendInput('^V')])`, so that when Terminal recieves a Ctrl+V, it both pastes, and sends a literal ^V to the client application (that vim can read).

**Comment by SaltyChiang** [comment]
Thank you for your advice.
It seems that everything is fine if I bind `ctrl+v` to send `\u0016` (which is the corresponding Unicode of `^V`). Vim and clipboard history work well under Windows terminal.
But still don't know why I have to do such binging.
