### ISSUE TITLE
Windows Terminal is unable to start in windows 11

### ISSUE THREAD

**Issue by MahmoudKanbar** [microsoft/terminal#14110]
### Windows build number

10.0.22000.0

### Steps to reproduce

It's just the terminal won't load at all, I tried everything form resetting to reinstalling the application throw the store but nothing works at all. 
I tried to see the terminal version in the cmd but nothing happens.

### Actual Behavior

It's just the terminal won't load at all, I tried everything form resetting to reinstalling the application throw the store but nothing works at all. 
I tried to see the terminal version in the cmd but nothing happens.

**Comment by DarrenClevenger** [comment]
I have the same issue on Windows 11. Terminal will not start. I have repaired, reset, uninstalled, reinstalled and even did a Windows repair. I get this for both the stable version and the preview version.

I find this in the Event Viewer after each attempt to start it:

```
Faulting application name: WindowsTerminal.exe, version: 1.16.2209.21002, time stamp: 0x632b96b9
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.978, time stamp: 0x82655b66
Exception code: 0xc000027b
Fault offset: 0x00000000004a3e02
Faulting process id: 0x46e8
Faulting application start time: 0x01d8d5967861fefb
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.16.2642.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 04b9d3d7-3fcb-47c6-98da-2b88b39f89b3
Faulting package full name: Microsoft.WindowsTerminalPreview_1.16.2642.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

```

**Comment by developeer** [comment]
I have experienced the same issues as DarrenClevenger with the same results.  Difference is I am running in a VM in hyperv.

**Comment by felipec84** [comment]
I have the same problems since 1.15, I need to downgrade to 1.14 in order to keep using WindowsTerminal, but since windows 11 always update the program when I reboot I need to downgrade very often.

The logged event is (in Spanish since that is my Windows language, somebody knows if I can get the log event in English, from another windows version):
```
Nombre de la aplicación con errores: WindowsTerminal.exe, versión: 1.15.2209.28003, marca de tiempo: 0x6334cd9b
Nombre del módulo con errores: Windows.UI.Xaml.dll, versión: 10.0.22000.978, marca de tiempo: 0x82655b66
Código de excepción: 0xc000027b
Desplazamiento de errores: 0x00000000004a3e02
Identificador del proceso con errores: 0x3294
Hora de inicio de la aplicación con errores: 0x01d8d71c66870e91
Ruta de acceso de la aplicación con errores: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.2713.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\Windows.UI.Xaml.dll
Identificador del informe: 12e9ba8b-e598-4ab6-987d-82fb8f83004b
Nombre completo del paquete con errores: Microsoft.WindowsTerminal_1.15.2713.0_x64__8wekyb3d8bbwe
Identificador de aplicación relativa del paquete con errores: App
```

PD: To downgrade WindowsTerminal I donwloaded it from github releases https://github.com/microsoft/terminal/releases, donwload the version 1.14. Then I uninstall WindowsTerminal (using winget) and install it with Add-AppxPackage from PowerShell
```
winget uninstall Microsoft.WindowsTerminal
Add-AppxPackage .\Microsoft.WindowsTerminal_Win11_1.14.2282.0_8wekyb3d8bbwe.msixbundle
```

**Comment by zadjii-msft** [comment]
Can you submit feedback via the feedback hub? Make sure to start a recording then try to launch the Terminal. That should get us a stack trace for whatever the root cause is here. 

As an aside, are you running the N SKU of Windows by any chance?

Thanks!

/feedback

**Comment by relcodedev** [comment]
I am using Windows Pro N edition. I summitted a feedback through eventhub.

**Comment by relcodedev** [comment]
from #14104 - Install the Media feature Pack could fix but it fails to install on Windows Pro N for me.

**Comment by felipec84** [comment]
Thanks, installing Media feature Pack fixed it for me:

https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a

Thanks @relcodedev

**Comment by DarrenClevenger** [comment]
Installing the media feature pack fixed the issue for me. Thanks.

**Comment by DHowett** [comment]
Thanks for all the reports. I'm going to publish a hotfix for this!
We're going to track this issue in /dup #14104.
