### ISSUE TITLE
Terminal from Microsoft Store Repeat Opening and Closing in Taskbar and Window doesn't Appear

### ISSUE THREAD

**Issue by OrbitGW** [microsoft/terminal#14127]
### Windows Terminal version

1.15.2712.0

### Windows build number

10.0.19044.2006

### Other Software

nmake.exe & cl.exe (MSVC 14.33.31629)
openssl.exe

### Steps to reproduce

I built the source of openssl from github using MSVC in Windows Terminal.

### Expected Behavior

run in a normal way.

### Actual Behavior

I used to learn about the line buffer is 9001 and I'm sure the logs is out  of range.
When I opned it again,it repeat opening and closing in taskbar and window doesn't appear.
**Anyway,I tried to reinstall it, but it didn't work. So how to deal with it.**

https://user-images.githubusercontent.com/57557582/193597549-2af89581-0b5f-4814-be63-21f21b50db8b.mp4

**Anyway,I tried to reinstall it, but it didn't work.**

**Comment by carlos-zamora** [comment]
Hi @OrbitGW. We tried building openssl and it worked just fine. Are there any other steps that you're missing above? Could you also upload a copy of your settings.json file?. As a reminder, it's located here:
`%LocalAppData%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`

Your comment on the buffer size is why we ask.
Thanks.
