### ISSUE TITLE
WT just disappeared from 2 win 10 machines

### ISSUE THREAD

**Issue by eliassal** [microsoft/terminal#14128]
### Windows Terminal version

Disappeared

### Windows build number

10.0.19044.0

### Steps to reproduce

All of a sudden, I type windows terminal in win search box, it finds nothing on 2 win 10 machines in spite of the fact it used to work like a charm and it is customized

### Expected Behavior

Not sure what to say, maybe a after a recent update of win 10

### Actual Behavior

No Windows terminal anymore, just disappeared from 2 machines

**Comment by zadjii-msft** [comment]
Can you find the Terminal in the Start Menu manually? What about by searching for "Terminal" rather than "Windows Terminal". Does running `wt` work? Is it listed in the Settings app under Installed Apps/?
