### ISSUE TITLE
background is changed to wired black when pressing (back)space or delete in PowerShell, same as issue #6767

### ISSUE THREAD

**Issue by LqkUWp** [microsoft/terminal#14125]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.19044.0

### Other Software

PowerShell 7.2.6

### Steps to reproduce

+ launch wt with pwsh running in it
+ press `space`, `backspace`, or `delete`

### Expected Behavior

background color/transparency doesn't change. 

### Actual Behavior

background color changes to black. 

https://user-images.githubusercontent.com/28478572/193557240-bf253e72-74f7-4968-b8f5-474a2feb1db8.mp4

### And ...

Just after microsoft store auto updated windows terminal from 1.10 (or 1.14, I forget the actual version) to 1.15.2524.0, I encounter this problem. 

I just confirmed that wt 1.14.2281.0 works fine.

**Comment by 237dmitry** [comment]
What if you test it without a custom prompt? Which may be incorrect.

**Comment by LqkUWp** [comment]
> What if you test it without a custom prompt? Which may be incorrect.

the same problem is still there.

**Comment by LqkUWp** [comment]
BTW, the wired prompt in the video results from that I delete the customized settings.json and use the default one.

**Comment by carlos-zamora** [comment]
Hi @LqkUWp.
We actually get this question a lot. Check out the relevant FAQ here for how to fix it: https://learn.microsoft.com/en-us/windows/terminal/troubleshooting#my-colors-look-strange-there-are-black-bars-on-my-screen

Thanks!
