### ISSUE TITLE
OpenConsole.exe will not quit if start with `msys2` profile and click `close window button`

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/terminal#14132]
### Windows Terminal version

1.16.22...

### Steps to reproduce

 start WT  with `msys2` profile and click `close window button`.

### Expected Behavior

OpenConsole.exe should quit after click close button even if WT start with msys2 profile.

### Actual Behavior

 I have to type `exit` to make OpenConsole.exe quit everytime or it will become a zombie process.

**Comment by lhecker** [comment]
This is reproducible without installing msys2 by running:
```
"C:\Program Files\Git\usr\bin\bash.exe" --login
```

(Assuming git-for-windows has been installed at the default location.)

**Comment by lbfuvab** [comment]
The same issue occurs to "Git/bin/bash.exe" (git bash) contained in Git for Windows.
Moreover, the issue for git bash seems not fixed in v1.15.2874.

**Comment by lhecker** [comment]
Hmm you're right. There seems to be at least one more race condition left in the code. The change works in a debug build _and_ my local release build. But it fails to work consistently in the more optimized store version. There I get 3 behaviors from least often to most often (I tested it about 40 times):
* OpenConsole exits but pwsh/bash remain running
* everything works correctly as expected
* bash exits instantly, but pwsh takes 5-10 seconds and OpenConsole never exits

**Comment by lhecker** [comment]
Oh right we haven't released this in Windows Terminal Preview yet.
In Windows Terminal 1.15 I can only reproduce the first point and only about 1 out of 10 times: "OpenConsole exits but pwsh/bash remain running".
