### ISSUE TITLE
Acrylic transparency not working

### ISSUE THREAD

**Issue by leptr** [microsoft/terminal#1414]
I have set the useAcrylic to true and I changed the acrylicOpacity to 0.2, but it is still a solid color. Has anyone run into this issue before? Have I done something wrong?
![Untitled](https://user-images.githubusercontent.com/25707449/59964961-72371400-9508-11e9-8f0b-e7e674d7f36f.png)

**Comment by onomatopellan** [comment]
what's your gpu?

**Comment by leptr** [comment]
> what's your gpu?

Intel HD Graphics, integrated in the laptop

**Comment by onomatopellan** [comment]
My old PC has intel G33 and had same problem with acrylic. I had to buy a cheap nvidia G710 to see transparency effects.

**Comment by DHowett-MSFT** [comment]
@leptr do you get acrylic transparency in _any_ modern windows application? Try Calculator, its entire window is acrylic!

**Comment by leptr** [comment]
> @leptr do you get acrylic transparency in _any_ modern windows application? Try Calculator, its entire window is acrylic!

No I do not! I didn't even know calculator was like that. How's it different from the transparency on Linux? I have dual boot and terminal in linux is transparent, do those two have anything to do with each other?

**Comment by DHowett-MSFT** [comment]
Windows has some policies about when it will turn on blurred transparency—it prefers to save battery, to not overly tax the GPU, etc. Unfortunately, since we are trying to be good citizens we aren’t trying to override that ... and I don’t think it’s possible, anyway :)

**Comment by onomatopellan** [comment]
@leptr Linux transparency is often done in OpenGL while the new Fluent Design in Windows 10 uses DirectX. If the gpu is old then you won't get transparencies on your laptop.

**Comment by leptr** [comment]
So while you are correct and transparency isn't supported by my GPU, I have also found that it can be turned off in the settings. If you right click onto the Desktop and click Personalize and then go to Colors, you will find a button called Transparency effects. It can enable/disable the transparency throughout your system and while it still hasn't enabled the acrylic for me, some parts of the UI have become transparent now. So maybe this will help anyone who has the same problem as me.

**Comment by shuffle2** [comment]
I've found that the app installed from the Store does not have working acrylic, but the app compiled from github has working acrylic (my build is a bit older, and not sure what commit the Store version is generated from...). Should I file a new issue?

**Comment by iamkentleom** [comment]
@leptr try turning on transparency effects on windows at Settings>Personalization>Colors. Should probably show the acrylicOpacity. I was also wondering for the same thing for days and it turns out my windows settings is preventing it 🙂

**Comment by goonmax** [comment]
> So while you are correct and transparency isn't supported by my GPU, I have also found that it can be turned off in the settings. If you right click onto the Desktop and click Personalize and then go to Colors, you will find a button called Transparency effects. It can enable/disable the transparency throughout your system and while it still hasn't enabled the acrylic for me, some parts of the UI have become transparent now. So maybe this will help anyone who has the same problem as me.

THANK YOU!

**Comment by KorbinianK** [comment]
I have the same issue. 
Version: 0.5.2762.0

CPU: AMD 3900x
GPU: Nvidia 2080
Powersettings: Ryzen High Performance
Transparency in Windows: on
Opacity in settings: 0.5

Any suggestions?
 @DHowett-MSFT

**Comment by lebesnec** [comment]
if your using a laptop and it's not plugged in, acrylic is turn off (probably to save battery).

**Comment by nerdybeast** [comment]
Similar to @iamkentleom I had "Transparency effects" turned off in Settings => Personalization => Colors, turning that back on I had to close/re-open Windows Terminal to see the transparency take effect.

**Comment by Lombra** [comment]
Is it not possible to use this without enabling the option globally in Windows? I don't want acrylic for the rest of my system.

**Comment by DHowett-MSFT** [comment]
Nope, sorry.

**Comment by toomding** [comment]
you need to put the acrylic configuration in global setting, not in each terminal setting area.
![image](https://user-images.githubusercontent.com/52145538/78526404-808ebc00-780c-11ea-8ecf-1ee49cce094b.png)

**Comment by nerdybeast** [comment]
@toomding not a great suggestion as it doesn't solve the underlying problem the user is having. Using the acrylic option in the global settings will not make it work as opposed to using it in a specific terminal setup.

**Comment by Congee** [comment]
@toomding it's not working for me :(

**Comment by toomding** [comment]
> @toomding it's not working for me :(

Try turn on personalization's transparent setting, or just copy your setting file to another computer see will it work, try to pinpoint the problems from config or windows. 
and if maybe try go to app store update windows teminal preview . 
if all of that didn't help. i recommend you to use alacritty . it is the emulator what i am using now.the windows's blur effect isn't that attractive to me . so i changed to alacritty for transparent effect.

**Comment by toomding** [comment]
> @toomding it's not working for me :(

sorry for that.

**Comment by Congee** [comment]
> 
> 
> > @toomding it's not working for me :(
> 
> sorry for that.

Thank you for your kind help. To give you more context, the problem does not seem to lie in the config of windows terminal but Windows. There used to be translucency effect, but it disappeared after a recent Windows Insider Update. I'm using 10.0.19603.1000 currently.

I use both Alacritty for WSL2 and Windows Terminal for some Windows specific jobs :D

**Comment by Congee** [comment]
It works again after upgrading to 10.0.19608.1006 (Windows is not really easy to debug except for Windows systems developers)

**Comment by railjty** [comment]
19613.1005 not working
![image](https://user-images.githubusercontent.com/30927889/80479117-22737580-8981-11ea-998b-0fad67306762.png)

**Comment by robertoandrade** [comment]
Same exact thing as @railjty but with 19631.1 still nothing.

**Comment by iS6F** [comment]
i fixed it , go to windows costumize settings , colors , switch trans effect to on , done :)

**Comment by robertoandrade** [comment]
Still doesn't work for me.

**Comment by kgfathur** [comment]
I got same problem,

but done by enabling **Transparancy effects**
![image](https://user-images.githubusercontent.com/18443757/83955530-03b8a680-a87e-11ea-82cf-0c62d9f72a1a.png)

it works!
![image](https://user-images.githubusercontent.com/18443757/83955555-3498db80-a87e-11ea-986d-0ab81f357d68.png)

**Comment by robertoandrade** [comment]
tried that too @kgfathur and nothing yet :( wonder if it has to do with anything related to RDP/terminal services on Windows since I'm trying this on an Azure VM.

**Comment by revoltingblob** [comment]
i'm having this problem as well. i just updated to 19041 from 18063 though. not sure what's different when it comes to transparency between the two but none of these solutions work for me. i've had the option in personalization on already, and i have transparency on everything else.

**Comment by zadjii-msft** [comment]
Hey I've got totally crazy idea - for the people who acrylic absolutely just isn't working for, does it work in [Notepads](https://github.com/JasonStein/Notepads)? They're using a custom acrylic implementation which might help debug this situation further.

**Comment by chriswoelfel** [comment]
@zadjii-msft No. No transparency whatsoever. I using a Surface Studio 2 and this has been an issue i've noticed for the past month. I'm running the May 2020 update as well  (19041.329). I've already did an entire reinstall of the OS and still nothing. I figured it was something with maybe a "battery" but as you know this is a desktop so I'm really confused. I can get transparency in the taskbar but for anything else (calculator, settings, etc...). And yes, I've tried both of the transparency buttons in the settings (even tried some registry edits and that didn't do anything but reverted back)

**Comment by zadjii-msft** [comment]
Huh. That's really peculiar. I honestly don't have any idea why even the Notepads version of acrylic wouldn't work, they're just using the Composition effects directly, without the battery (and others) policy applied.

**Comment by chriswoelfel** [comment]
Yea, there's a bug somewhere (seems rare) as doing a system restore (full wipe) should have fixed it for me but I don't know what to do at this point. I left feedback through the feedback app (or maybe +1 someone else who had the same issue.

**Comment by zadjii-msft** [comment]
We get reports of this pretty constantly (#5698 was one of the more recent ones with plenty of details), so I've reached out to the Composition team to see if they have any ideas what might be going on here. No promises, but they'll probably be better at debugging this than I will.

**Comment by zadjii-msft** [comment]
Okay, the initial feedback was:
* Acrylic doesn't work if there's not the GPU hardware for it. A Surface Studio probably has the hardware, but it won't work if you're running the app in a VM or over remote desktop (for example).
* If you wanted to help investigate, could you run `dxdiag` ([instructions here](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe)), and send the output to the email in @DHowett's profile? He'll be able to share that with the Composition team so they can investigate exactly _why_ it's not working.

**Comment by chriswoelfel** [comment]
Thanks @zadjii-msft ...I'll do that. (and no vm or rdp usage but thanks for that info)

**Comment by zadjii-msft** [comment]
@chriswoelfel as a sanity check, is there Acrylic in the Start Menu? 
I get a very faint amount using the host backdrop on the main body of the Start Menu:
![image](https://user-images.githubusercontent.com/18356694/84410645-aa30de80-abd3-11ea-8bba-9a7c567b1ce1.png)

and a little bit of in-app as well with the sidebar:
![image](https://user-images.githubusercontent.com/18356694/84409927-71910500-abd3-11ea-9d93-7bfa8f446e0f.png)

**Comment by chriswoelfel** [comment]
Nope, which is why I said it's a system level thing. I have transparency in the taskbar (and transparency works within apps like terminal ONLY if I have a background image...). There's no acrylic throughout the entire system (like settings). All of it is opaque. 
![image](https://user-images.githubusercontent.com/26769769/84415090-41039800-abe0-11ea-80b6-b360fa1e8438.png)

**Comment by robertoandrade** [comment]
![image](https://user-images.githubusercontent.com/318969/84502896-8fbc3b00-ac8f-11ea-91f7-11851279e3ca.png)
@zadjii-msft nothing yet, but as I mentioned I am on an Azure VM over RDP so that may explain why. Gonna try `dxdiag` and provide output just for the sake of it. Thanks for clarifying that.

**Comment by revoltingblob** [comment]
hmm. well in my instance i'm not using RDP or an azure vm, which is understandable as to why it wouldn't produce acrylic effects over those connections. start menu and notepads produces a transparent effect so i am still seeing it, just having problems with terminal. i emailed the above my dxdiag info, but i'll post some more stuff here shortly.

**Comment by stevezxc** [comment]
The windows terminal lost transparency after I updated the system, but the start menu still have. I have changed the json but it does not work. After I turn off and on the transparency effects in the system settings, the terminal had an acrylic effect again.

**Comment by wrightadrian** [comment]
Setting the [useAcrylic](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#acrylic-settings) property to true, got things working for me.

**Comment by revoltingblob** [comment]
turns out for me this was a antialiasingMode and cursorShape conflict. these two cant seem to be enabled with each other and it produces the black box effect for me as I posted in the picture above.

**Comment by DavidZhang73** [comment]
I might got a solution from microsoft/microsoft-ui-xaml repo.

https://github.com/microsoft/microsoft-ui-xaml/issues/2737#issuecomment-650471950

**Comment by alanxptm** [comment]
I have the latest windows update and just installed the Terminal, transparency setting is "on" and it doesn't work, maybe because of hardware as already said but thing is.. Powershell has transparency, then what!?

![Captura de pantalla (48)](https://user-images.githubusercontent.com/67605052/86278083-6a8b6000-bb9d-11ea-805e-e21d5d67a6ff.png)

**Comment by syd619** [comment]
After 19041.388 I lost taskbar transparency also. On PC with Gigabyte GTX 2070 super

**Comment by w4rlock999** [comment]
For those who can't, it is on system level not specific windows terminal issue, when you enable transparency on windows settings it work for me (after restart the windows terminal).

The question now is how could i enable acrylic without enabling windows 10 transparency settings ??

**Comment by no-sssweat** [comment]
As mentioned here https://github.com/microsoft/terminal/issues/1414#issuecomment-640125263 turn on transparency and then **re-start** Windows Terminal

**Comment by railjty** [comment]
![image](https://user-images.githubusercontent.com/30927889/89603439-bb2c6200-d89b-11ea-8bb4-33c3c73c4644.png)
When I enable this, the acrylic opacity is not working. When I disable this, it works

**Comment by heyuhang0** [comment]
Having the same issue on Thinkpad X1 carbon 6th gen with Windows 2004. There is also no acrylic effect on start menu with the transparency effect on.

Processor: i7-8550u
GPU: UHD620
OS Build 19041.423

In my case, the issue is related to Intel GPU's DPP feature, which is an OEM enabled feature that loads a 3D LUT colour mapping profile to GPU. My laptop needs that feature to map screen colour gamut to sRGB otherwise everything will be oversaturated. If I disable that (by deleting `HKEY_LOCAL_MACHINE\SOFTWARE\Intel\IGFX` key in the registry and restart), the acrylic effect can work again.

**Comment by damien122** [comment]
I could fix this problem by first disable the transparency mode in windows and then turn it on again. (Windows Settings -> Customize -> Colors -> "Transparancy effects")
Afterwards start new Windows Terminal.

**Comment by AkgunFatih** [comment]
> Setting the [useAcrylic](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#acrylic-settings) property to true, got things working for me.

Well that's how you enable it you smartass
but it does not work for some of us

**Comment by DHowett** [comment]
@AkgunFatih if you don’t have anything nice to say, you are welcome to not leave a comment on this repository.
