### ISSUE TITLE
regression: since about an update or two, copied lines are split into multiple lines when they span multiple lines. it used to copy all multiple lines into one, and it was good. now is counter productive.

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#14145]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2075

### Steps to reproduce

select continuous multiple lines
paste

expect: paste a single line
result: copied text is broken into multiple lines (cr/lf inserted) so when I paste I am actually pasting multiple lines, breaking a long command

see attached video

### Expected Behavior

paste a single line

### Actual Behavior

https://user-images.githubusercontent.com/2054302/194303751-bfa98948-0a88-446d-ac0b-d960fedcd680.mp4

**Comment by mailinglists35** [comment]
oddly it does seem to work in the local wsl1 shell. 

but it also used to work when doing ssh to remotes from local wsl1 shell. now it doesn't anymore.

**Comment by lhecker** [comment]
We've had a recent bug filed on us which covers the same issue. Please check out /dup #14035 🙂
