### ISSUE TITLE
regression: U+0219 and U+021B (ș and ț) are displayed in lower size with FantasqueSansMono-NoLoopK font

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#14144]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2075

### Steps to reproduce

since about last one or two terminal preview updates, I noticed the ș and ț letters are displayed in about half size than the rest of other letters, when using font FantasqueSansMono-NoLoopK from https://github.com/belluzj/fantasque-sans/releases/tag/v1.8.0 

otherwise the font works okay in all other native windows apps as well in other third party terminals such as MobaXterm and Putty and even plain old cmd.exe (wait what, how does it even appear there? cmd.exe didn't see those many monospaced fonts last time I checked!)
![image](https://user-images.githubusercontent.com/2054302/194300574-af286113-0a88-4f42-a840-92bfd2d02128.png)

### Expected Behavior

same size all characters

### Actual Behavior

șț are smaller than the rest

![image](https://user-images.githubusercontent.com/2054302/194300702-e63b22dc-bd0a-4a17-b098-95b19a9cbf84.png)

**Comment by mailinglists35** [comment]
or maybe since the last windows restart of updates? did both updates (os + terminal) at the same time.

**Comment by lhecker** [comment]
Thanks for the report! I'll deduplicate with another related issue, because even if it has a different description the underlying problem is the same. /dup #14094

In the meantime, until I can get a fix out, you can disable "AtlasEngine" in your rendering settings.
