### ISSUE TITLE
%path% not filled when starting the command prompt

### ISSUE THREAD

**Issue by sergiodomingo** [microsoft/terminal#14157]
### Windows Terminal version

1.15.2712.0

### Windows build number

10.0.19044.2075

### Steps to reproduce

`echo %path%`

### Expected Behavior

![image](https://user-images.githubusercontent.com/2834223/194531755-0f184ba3-18a1-4271-95ed-72d9cf321264.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/2834223/194531786-50b0853f-2402-489a-b46a-6fd22fd43cb0.png)

**Comment by 237dmitry** [comment]
Strange behavior. I've never seen the same. My advice is to reinstall WT and it would be better to install the latest preview version.

**Comment by sergiodomingo** [comment]
It solved itself, somehow.
