### ISSUE TITLE
JAWS virtualization shows UI elements instead of terminal content

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14150]
### Windows Terminal version

1.16.2642

### Other Software

JAWS

### Steps to reproduce

1. Open terminal
2. press <kbd>JAWS+ALT+W</kbd> (note: JAWS = Caps lock key)

### Expected Behavior

works in 1.15.2713

A window should pop up with the text from the terminal

### Actual Behavior

The window shows all of the ui elements and no terminal content

**Comment by carlos-zamora** [comment]
Looked at this today. Tested out a few versions and found a lot of broken versions:
- main (b7e537e5e) - broken
- 1.15.1862.0 - broken
- 1.15.2713.0 - broken
- 1.14.1432.0 - broken

I'll follow up with Alex Benoit (the one who reported these to me).

**Comment by carlos-zamora** [comment]
Alex said he is no longer experiencing this issue in...
- stable Version: 1.15.3466.0
- preview Version: 1.17.2852.0

**Comment by carlos-zamora** [comment]
Alex is also using JAWS Version 2023.2212.23 ILM

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/212189847-95812096-2587-40d2-8d9a-7243df4603ac.png)


https://support.freedomscientific.com/Downloads/JAWS/JAWSWhatsNew?version=2022

2022.2110.60 literally didn't support the Terminal
