### ISSUE TITLE
Auto-updater/Check for updates

### ISSUE THREAD

**Issue by u84six** [microsoft/terminal#14158]
# Description of the new feature/enhancement
I searched and didn't see a request for this, but I'd like to see an auto-updater/check for updates feature in the Terminal app. I don't use Microsoft Store to download this, so it would be great if the feature was built in. This would be good for security fixes, etc., for people who don't use Microsoft Store

If there are any major security issues, it would be convenient to be able to quickly update, particularly if not using MS Store.

# Proposed technical implementation details (optional)
Maybe a Settings checkbox that has "Auto-update: enable" and if this is checked off, have a button that will check for updates and then give the option to update now.

**Comment by WSLUser** [comment]
Would something like Winget or Chocolately suffice for you?

**Comment by u84six** [comment]
> Would something like Winget or Chocolately suffice for you? (The README does list official and unofficial ways to install outside of the MS Store.)

Not everyone uses package managers. I'd think that someone like Chocolately should work for the people who use them, but I think most people feel more comfortable when the app itself has it built in (for the sake of security)

**Comment by WSLUser** [comment]
I don't think what you're asking will ever officially occur. Also realize that Chocolately offers an enterprise option as does MS Store and eventually Winget too that allows for no outside connections but simply a private repository for Windows applications.

**Comment by zadjii-msft** [comment]
Yea, I'm gonna reject this one. The Store is our preferred method for installing the Terminal in a way that it'll auto-update. We've also got a WIP PR for adding a button to the Terminal to manually check for updates, but that'll again backend off the package catalog AKA the Store. Also, winget is great. That's the package manager to use, and it's built-in to Windows. Much love for our coworkers over on winget. 

If you install the msixbundle off Github, then that'll still hook into the package catalog in the same way. But I don't think we're gonna add any extra code to make this work for unpackaged installs, to check if there's a new package on github or something.

**Comment by u84six** [comment]
Yeah, I don't think relying on the store is a good decision because many companies block it for security reasons. I can't access MS Store from my company's laptop.
