### ISSUE TITLE
[JAWS] Keybinding entry in actions page should read out key chord

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14152]
### Windows Terminal version

1.16.2642

### Other Software

JAWS

### Steps to reproduce

1. Open terminal
2. Open settings UI > actions
3. tab to "close pane"

### Expected Behavior

JAWS should read "close pane, ctrl+w"

### Actual Behavior

JAWS reads "close pane"

**Comment by carlos-zamora** [comment]
This is a regression from 1.15.2713

**Comment by DHowett** [comment]
This page didn't change between 1.15 and 1.16...!

```
% git diff origin/release-1.15:src/cascadia/TerminalSettingsEditor/Actions.xaml origin/release-1.16:src/cascadia/TerminalSettingsEditor/Actions.xaml
<no output>
% git diff origin/release-1.15:src/cascadia/TerminalSettingsEditor/Actions.cpp origin/release-1.16:src/cascadia/TerminalSettingsEditor/Actions.cpp
<no output>
```

**Comment by carlos-zamora** [comment]
Found out that this issue repros in the WinUI 2 and WinUI 3 gallery. This is either a bug on WinUI or JAWS. Closing as such.

**Comment by carlos-zamora** [comment]
To make things even more confusing, the Terminal bug repros on JAWS 2022, but not on JAWS 2023. But the WinUI gallery bug repros regardless.
