### ISSUE TITLE
Zoom in/out on the windows terminal perview doesn't work

### ISSUE THREAD

**Issue by nishp77** [microsoft/terminal#1416]
When either using the ctrl += for zooming or with the mouse scroll, there is no effect on the window. When clicked on the tab e.g of powershell the zoom doesn't work but then when clicked within the area of typing the commands it works

**Comment by JushBJJ** [comment]
Not sure if it's a feature or bug, but using the trackpad/mouse, you can do ctrl+scroll to zoom in or out.

**Comment by DHowett-MSFT** [comment]
This is actually probably the same as #1370.

**Comment by pengu10** [comment]
anybody knows the zoom in/out shortcut syntax for settings.json ? 
i cant zoom in only out..  
windows 10, 2004 wsl2
windows terminal Version: 1.0.1401.0

**Comment by zadjii-msft** [comment]
@pengu10 These are the default keybindings:

https://github.com/microsoft/terminal/blob/c0ffc9b6dce9b632c868b6584a0f1c8c9dd1df93/src/cascadia/TerminalApp/defaults.json#L336-L339

**Comment by jfernandz** [comment]
You can overwrite the default config shown by @zadjii-msft with

`{ "command": { "action": "adjustFontSize", "delta": 1 }, "keys": "ctrl+plus" }, `

so you will have `Ctrl` + `+` to increase the fontsize.

**Comment by ilan-schemoul** [comment]
Ctrl+= works but ctrl+- doesn't work except if I copy paste " { "command": { "action": "adjustFontSize", "delta": -1 }, "keys": "ctrl+-" }, " into my config. Weird.
