### ISSUE TITLE
Windows Terminal Preview input very slow compared to Stable version

### ISSUE THREAD

**Issue by akulbe** [microsoft/terminal#14169]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22623.0

### Steps to reproduce

Open up Windows Terminal Preview start typing. It takes, I would say, up to a full second for some text to appear. There's a lagging feel to it.

Open up the stable Windows Terminal, and the text shows up immediately upon typing, as you would expect.

### Expected Behavior

Text would render as fast as it's typed.

### Actual Behavior

Text is very slow to render.

**Comment by lhecker** [comment]
Can you tell me more about the hardware you're using (CPU and GPU model, which you can find in the Performance tab of Task Manager for instance)? Are you using Windows Terminal over RDP or from inside a VM?

**Comment by akulbe** [comment]
ThinkPad P1, gen1
6-core Xeon
64GB of RAM
Nvidia P2000

no slouch, for sure

buuuuuuuuuut.... I think it's environmental. I had a
newer-than-Lenovo's-release Intel video driver installed. I roll back to
the Lenovo version, and the issue is gone. (I have a second Lenovo much
beefier than this one, where I could not reproduce this issue with the same
set of software)

Feel free to close this one.

**Comment by akulbe** [comment]
I was trying to run the latest stable Intel drivers for both GPU and Wifi/Bluetooth, and was using Intel Driver & Support Assistant to get the latest and greatest from them. Once I rolled back to the ancient version of the Intel video driver that came from Lenovo, the issue went away. #sigh
