### ISSUE TITLE
Pure blackness not displayed correctly unless black PNG is selected as background.

### ISSUE THREAD

**Issue by m4r1vs** [microsoft/terminal#14168]
### Windows Terminal version

1.15.2712.0

### Windows build number

10.0.19042.0

### Other Software

Does not matter as this also happens with the terminal being freshly installed and independent of the selected shell (WSL, PowerShell, etc.).

### Steps to reproduce

Change a theme's background colour to RGB(0,0,0) or create a new theme with pure black as the background colour.

### Expected Behavior

I expected the colour of the background to be pure black.

### Actual Behavior

the colour of the background being RGB(34, 34, 35). I had to create a pure black PNG and select that as my background image to achieve the blackness I wanted my terminal to be. It makes a HUGE difference, especially on OLED screens.

**Comment by DHowett** [comment]
Thanks for the report! Can you share your `settings.json` file?

**Comment by m4r1vs** [comment]
sure, here you go: [https://gist.github.com/m4r1vs/9a97b4581dade3568a9c27925d74980d](https://gist.github.com/m4r1vs/9a97b4581dade3568a9c27925d74980d)

**Comment by 237dmitry** [comment]
What will be if you change background to '#000000' in an other profile? Also check `~/.bashrc` (.zshrc) and `~/.Xresources`. Maybe there are some host settings, esc, osc sequences and so on.

**Comment by elsaco** [comment]
@m4r1vs you have `"useAcrylic": true` in your `"defaults"`. Does it make any difference if you disable acrylic material?

**Comment by m4r1vs** [comment]
@elsaco Good idea, but it seems like it only changes what the title bar looks like :/

**Comment by m4r1vs** [comment]
@237dmitry Yes, also the case when using PowerShell or CMD. It being influenced by WSL was my first thought as well though - and I spent too much time digging through my zsh's and prompt's configuration files before trying anything else haha. Happens both when setting the background of the default theme and also when changing the background of a newly created theme to anything darker than rgb(34,34,34). 

Just tried it on my work computer and even though it's on Windows 11, it still has the same "issue"... As long as my little image-as-background workaround works though, I'm a happy Win Terminal user :)

**Comment by 237dmitry** [comment]
https://user-images.githubusercontent.com/78153320/194816975-8be0254f-96c3-4de0-88cd-86910e6974bb.mp4

**Comment by DHowett** [comment]
> @elsaco Good idea, but it seems like it only changes what the title bar looks like :/

_Huh_, this shouldn't be the case! The `useAcrylic` on line 45, inside `profiles.defaults`, applies to the background of the terminal pane. When it is enabled, you should see a somewhat fuzzy non-perfectly-black texture in the background of your terminal window.

That is separate from the `useAcrylicInTabRow` setting at the bottom (line 363 in the document you shared).

**Comment by m4r1vs** [comment]
@DHowett THANK YOU! Somehow I managed to have a different theme selected when trying to disable acrylic. I now disabled acrylic and chose a theme with a black background (it works as intended)... Closing now since there is no bug but only my own clumsiness to complain about.

**Comment by DHowett** [comment]
Hah! I'm glad we could help :smile:
