### ISSUE TITLE
Terminal Crashes with side-by-side windows in same tab after resize

### ISSUE THREAD

**Issue by milt0r** [microsoft/terminal#14164]
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22623.0

### Other Software

Using Windows SSH client

### Steps to reproduce

1. Open Terminal to default PowerShell tab
2. Click profiles dropdown and select a tab that runs: SSH user@hostname
3. Click dropdown again and alt-click on the same profile. It opens side-by-side.
4. Resize the window. 

Crashes. 

### Expected Behavior

No crash :)

### Actual Behavior

It crashes upon dragging the corner and resizing.

**Comment by milt0r** [comment]
This looks like an issue on my machine. I looked at the crash message and see this:

Faulting application name: WindowsTerminal.exe, version: 1.15.2209.28003, time stamp: 0x6334cd9b
Faulting module name: NahimicOSD.dll, version: 2.2.23.0, time stamp: 0x61b7fd89
Exception code: 0xc0000005
Fault offset: 0x00000000000169a2
Faulting process id: 0x0x9304
Faulting application start time: 0x0x1D8DCD793C7D50A
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.2713.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
**Faulting module path: C:\ProgramData\A-Volute\A-Volute.28054DF1F58B4\Modules\ScheduledModules\x64\NahimicOSD.dll**
Report Id: c1433188-ca40-43db-bde9-6f9abc722e69
Faulting package full name: Microsoft.WindowsTerminal_1.15.2713.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Will also submit feedback.

**Comment by DHowett** [comment]
Hey, we've actually seen crashes with A-Volute before! They are injecting a DLL into every application, and it seems like it is _not stable_.

I've gotta close this one out since it's not on our end; the best way to get support is unfortunately to go bother A-Volute. We've also done the same :smile: so we're approaching it from both angles.
