### ISSUE TITLE
Renderer encountered an unexpected error: -2005270527

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#14171]
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22621.521

### Other Software

ssh'ed to AWS machine, used `vim` inside there

### Steps to reproduce

No idea. I had three terminals in one window arranged in a "pi" pattern:
```
--------
content
--------
p1 | p2
```

I had made p1 bigger using ctrl-alt-up/right. I noticed when I hovered over the pane and exited, the bell tripped. everytime i entered the pane, it was fine, but when exiting the pane the bell would trigger

### Expected Behavior

No error and no bell firing

### Actual Behavior

When I went to vim, the renderer error triggered: Renderer encountered an unexpected error: -2005270527

Strangely when I made the p2 pane bigger again (see above for pane diagram) the error cleared and things worked fine. every key stroke triggered the error and exiting vim was "hard/impossible". Only after making the pane bigger, did the error go away and I could exit vim.

**Comment by lhecker** [comment]
I'll deduplicate this issue with another report that we got a while ago. /dup #14082
