### ISSUE TITLE
Issue with `Open windows from a previous session` & WSL

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#14177]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22623.0

### Other Software

WSL v2

### Steps to reproduce

- Have a few tabs open that point to paths on the WSL VM
- Restart your PC
- Open Windows Terminal

### Expected Behavior

Tabs restored to their previous folder / path

### Actual Behavior

Tabs restored to system32

I assume this happened because the VM was not running yet when I launched Terminal? Is there maybe a way to let terminal "wait" for it to be up and then restore the correct path?

**Comment by lhecker** [comment]
Hey! Did you configure your shell to emit OSC 9;9 sequences to inform the terminal about the shell's working directory?

**Comment by Stanzilla** [comment]
I did not know that I have to do that, will try now, thank you!

**Comment by Stanzilla** [comment]
Yup, that fixes it!
