### ISSUE TITLE
Terminal icon is broken in Windows Search menu

### ISSUE THREAD

**Issue by claudioweiler** [microsoft/terminal#14175]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.19044.2006

### Steps to reproduce

Hit search control in Windows, or hit <kbd>Windows</kbd> key, and type "terminal".

Obs. Windows terminal installed through winget.

### Expected Behavior

Icon shows correctly

### Actual Behavior

Broken icon:

![image](https://user-images.githubusercontent.com/15875077/194940315-d4f6ebd6-6a49-476f-b9a6-f15f3c1198cb.png)

Correct icon on start menu:

![image](https://user-images.githubusercontent.com/15875077/194940373-a02fbbfa-06a8-4a06-9c39-0454a942e874.png)

**Comment by lhecker** [comment]
Do you happen to have Google Drive installed?

**Comment by claudioweiler** [comment]
Yeah! I do, @lhecker !

**Comment by lhecker** [comment]
@claudioweiler It's a known bug caused by Google Drive unfortunately. See here for instance: https://superuser.com/a/1441161
You can find out a lot more about it when you search for "google drive start menu missing icons" or similar on the internet. It's definitely not caused by anything Windows Terminal does.

**Comment by claudioweiler** [comment]
Oh, I see @lhecker!

Sorry for wrong issue open. I assumed wrong this is an Terminal issue because it's the only broken icon.

Following your link I got this one, to other people that find this thread: https://issuetracker.google.com/issues/173912342
_**Obs.** This issue has been "internally filled" by Google, but if you find this one, please vote on issue!_
