### ISSUE TITLE
Explorer crash from jumplist

### ISSUE THREAD

**Issue by fitch22** [microsoft/terminal#14172]
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22621

### Steps to reproduce

I pinned Windows Terminal to the task bar.  If I try to open a profile from the jumplist (right click), I get a momentary flash of a box that says "The item you selected is unavailable.  It might have been moved, renamed, or removed.  Do you want to remove it from the list?" and then explorer crashes.

I am able to run terminal and it opens the default profile just fine.  I can set all the items as default and they all open fine.  Once terminal is running, I can open any of the items fine.

The same thing happens when I try to open one of the profiles from the start menu.

All other items pinned to the taskbar that have jumplists work just fine.

I have 3 other machines here with same version of Windows 11 (22H2) and all behave as I would expect.  Any ideas on how to track this down would be appreciated.

### Expected Behavior

Was expecting terminal to open the selected profile.

### Actual Behavior

Explorer crashes.  Event viewer shows:

Faulting application name: Explorer.EXE, version: 10.0.22621.608, time stamp: 0xe1524e94
Faulting module name: KERNELBASE.dll, version: 10.0.22621.608, time stamp: 0x4769d08d
Exception code: 0x0eedfade
Fault offset: 0x000000000008fb0c
Faulting process id: 0x0x2064
Faulting application start time: 0x0x1D8DCB67D82EEEE
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5df7ce1a-548f-440c-bb33-b0a098fbab70
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fitch22** [comment]
I recorded the crash with Feedback Hub and submitted the bug report.  Here is a link to the URL:
https://aka.ms/AAij3x1

I realize this would not appear to be a Windows Terminal bug, but it only happens with Windows Terminal.  None of my other apps in my taskbar (or in the start menu) cause this to happen.

Thanks.

**Comment by DHowett** [comment]
Oh, I remember looking at this one! Sorry, responding to it got pushed down my to-do list a little bit.

The exception code `0x0eedfade` comes from the "Delphi" programming language. That's the weirdest thing about this: Terminal and Explorer don't use Delphi! Nothing that comes with the OS does, actually...

Do you know if you have any shell extensions installed? The sort that add a context menu, a toolbar, a taskbar plugin, etc.?

**Comment by fitch22** [comment]
I have a few programs with shell extensions.  Adobe Acrobat XI, Beyond Compare 4.4.3, Notepad++, and PowerArchiver 2022.  I also have a program called Altium Designer 22 which at one point was definitely written either mostly or entirely in Delphi.  I don't know if it installed any shell extensions, I don't really see any.  Is there something in the registry I could look for that would indicate a shell extension?  If there is, is there a way to disable it maybe temporarily?

How would I determine whether or not a piece of software was written in Delphi?

Thanks.

**Comment by fitch22** [comment]
Just a bit more info.  I used a utility called ShellExView to disable every non-microsoft shell extension and the problem remained.  Would not appear to be a shell extension unless it is a Microsoft shell extension.

**Comment by DHowett** [comment]
_Huh._ I'm running out of troubleshooting avenues! Thanks for testing all my wacky theories.

When you filed the feedback item above, did you crash explorer while it was in "collecting..." or "recreate my problem" mode? I couldn't find a crash dump in there, only a "live" dump from a running instance of Explorer.

(If you did, there may be something afoot with the Feedback system I don't fully understand on how it captures crash dumps.)

**Comment by fitch22** [comment]
I am not all that familiar with Feedback Hub.  What I did was start the recording, then I right clicked on the Terminal icon and selected Powershell, explorer then crashed and restarted.  I then ended the recording from Feedback Hub and sent the recording to MS.  If there is a better way to do this let me know and I can try again.

Thanks.

**Comment by fitch22** [comment]
When or how can I get some sort of resolution to this?

**Comment by DHowett** [comment]
Sorry, I'm going to need to dig up a File Explorer expert :smile:

**Comment by fitch22** [comment]
Any progress at all?

**Comment by DHowett** [comment]
Thanks for your patience, and I'm sorry for the radio silence.

_With those shell extension applicatiosn uninstalled_ (not just disabled; I don't know how ShellExtView works, and I'm sorry[^1]), can you reproduce the issue and send a new copy of the event in your event log?

I would love to see if the exception code changes... because that could point to a different culprit.

We've noticed that Beyond Compare and PowerArchiver both have a tendency to crash with Delphi exceptions. There's also "UninstallExplorer" and "TeraCopy", but I don't know whether you are using them. I can't point to any others in your list that both have shell extensions and tend to crash.

[^1]: It is very likely that you disabled all the non-Microsoft extensions properly; but I can't discharge myself of my duty as triager without trying to eliminate more variables. :(

**Comment by fitch22** [comment]
@DHowett,
OK, uninstalling all of the software with extensions on my main computer is not really practical.  However since you mentioned Beyond Compare and PowerArchiver, I figured I can take a fresh install and install that software and see what happens.  Well, Beyond Compare has no effect.  By itself, terminal can be opened without issue.  However, after installing PowerArchiver, the problem appeared.  It behaves exactly like on my main machine.  I can open terminal just fine by left clicking on the taskbar icon.  I can open any of the terminal types like command prompt or powershell.  But if I right click on the taskbar icon and try to open any of the profiles, explorer crashes and restarts.

So it appears the culprit is Power Archiver.

Is this a bug in terminal, or a bug in Power Archiver?  And who might be able to fix this?

Thanks!

**Comment by zadjii-msft** [comment]
> appears the culprit is Power Archiver

Sure sounds like a Power Archiver bug to me! Shell extensions are weird like that and can kinda just mess with each other. I'd file a bug on them, they'd be the best ones to investigate how their extension is crashing (when there's also a Terminal jumplist). Feel free to link the bug report here, so anyone else who stumbles on this can go follow it on their side ☺️ 

Thanks for following up!

**Comment by zadjii-msft** [comment]
Oh hey:

* #7702
* #8234

> I had a chance to do a bit more testing today, including against my work PC which is on 20H2 rather than Dev ring.
> Same issue, and it looks like only one shell extension in common between the two PCs.
> Disabling/removing that extension solved the crash, and I've reached out to the vendor of the app in question (PowerArchiver 2019).
> **Their beta/RC version of the extensions doesn't seem to have the issue.**

_emph. added_
