### ISSUE TITLE
“Default Terminal application” setting is not shown

### ISSUE THREAD

**Issue by ElitePheonix2009** [microsoft/terminal#14170]
### Windows Terminal version

1.15.2712.0

### Windows build number

10.0.19044.2006

### Steps to reproduce

1) Open settings.
2) Go to the startup tab.
3) See that the “Default Terminal application” setting is not shown.

![image](https://user-images.githubusercontent.com/114980232/194856674-793d2ac5-a9af-4e57-8491-e69472031642.png)

### Expected Behavior

The setting “Default Terminal application” should be shown.

![image](https://user-images.githubusercontent.com/114980232/194856751-79865c5f-26d7-47e2-ac44-9fe097d04906.png)

### Actual Behavior

The setting “Default Terminal application” is not shown.

![image](https://user-images.githubusercontent.com/114980232/194856818-dcfd1c4b-9f13-4e51-a8f8-0d87a33c22c0.png)

**Comment by lhecker** [comment]
This is part of our FAQ 🙂 https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-is-the-default-terminal-setting-on-windows-10

**Comment by treysis** [comment]
Works now:
https://github.com/microsoft/terminal/discussions/15505
