### ISSUE TITLE
"name" defined for profiles in profiles.json do not matches with tab title

### ISSUE THREAD

**Issue by BipulRaman** [microsoft/terminal#1418]
# Environment

```none
Windows build number: 18362.175
Windows Terminal version (if applicable): 0.2.1715

```

# Steps to reproduce

- Open tabs for PowerShell and CMD
- Take a look at Tab Title and compare with `name` in `profiles` in `profiles.json`

# Expected behavior

- Tab Title should match with `name` in `profiles` in `profiles.json`

# Actual behavior

- Tab Title is not matching with `name` in `profiles` in `profiles.json`

# Screenshot
![image](https://user-images.githubusercontent.com/8312486/59965702-4ed38f80-952f-11e9-837e-23afe11ae023.png)

![image](https://user-images.githubusercontent.com/8312486/59965727-9528ee80-952f-11e9-8af4-9241718c9a74.png)

**Comment by DHowett-MSFT** [comment]
This is #608. **please make sure you search for existing issues before filing a new one**
