### ISSUE TITLE
SUI color palettes alignment

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#14187]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Open `Color schemes` in `Settings`

### Expected Behavior

Color palettes vertically alligned

### Actual Behavior

![wt_colors](https://user-images.githubusercontent.com/3933920/195167086-45f3c6f4-ef77-4852-a127-cacd37d18683.png)

Two columns, with color palettes in the 2nd column, might  look better.   Something like the `Command Palette`

**Comment by DHowett** [comment]
_Uhh_..?!

<img width="859" alt="image" src="https://user-images.githubusercontent.com/189190/195170471-338fdfae-b2df-4ec1-a6da-ca90f96afd61.png">

I might need a bit more info from you on what you've got going on... 😁

**Comment by j4james** [comment]
FYI I'm seeing the same thing. I'm sorry I meant to raise this before, but I completely forgot about it. Is it possibly a Windows 10 vs Windows 11 thing? I'm on version 10.0.19044.2006.

Also, in case it's relevant, I see a boat load of exceptions being logged if I'm running from within the debugger and I navigate to the _Color schemes_ page. Mostly something like this:

```
Microsoft.Terminal.Settings.Editor.dll!00007FFA279C6689: LogHr(339) tid(430c) 80004002 No such interface supported
Exception thrown at 0x00007FFAE3F54FD9 (KernelBase.dll) in WindowsTerminal.exe: WinRT originate error - 0x80004002 : 'No such interface supported'.
Exception thrown at 0x00007FFAE3F54FD9 in WindowsTerminal.exe: Microsoft C++ exception: winrt::hresult_no_interface at memory location 0x000000C21A356CB0.
Exception thrown at 0x00007FFAE3F54FD9 in WindowsTerminal.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Microsoft.Terminal.Settings.Editor.dll!00007FFA27A11AF6: ReturnHr(321) tid(430c) 80004002 No such interface supported
    Msg:[winrt::hresult_error: No such interface supported] 
```

**Comment by DHowett** [comment]
Ohhhh no. That's not good.

/cc @PankajBhojwani

**Comment by PankajBhojwani** [comment]
Interestingly I get those types of exceptions no matter which page of the SUI I navigate to (though it does seem that _more_ of those get emitted for the ColorSchemes page) - perhaps it has something to do with our settingContainerStyle?

As for the misalignment, I'm going to need to try it on Windows 10 to see what's going on

**Comment by DHowett** [comment]
Go away, stale bot! We're fixing this one. :smile:
