### ISSUE TITLE
The execution file seems not signed, it keeps being marked as virus by my antivirus.

### ISSUE THREAD

**Issue by jimchen5209** [microsoft/terminal#1419]
# Environment

```none
Windows build number: 18917
Windows Terminal version (if applicable): 0.2.1715.0

AntiVirus: Trend Micro PC-Cillin 2019 15.0.1231
```

# Steps to reproduce
Open up Windows Terminal

# Expected behavior
Nothing happened, just as normal terminal.

# Actual behavior
conhost.exe was marked as `HEU_FALCONTroj.Win32.Gen.XXBM100FF005R0001` and got removed by antivirus.
WindowsTerminal.exe and conhost.exe were stopped becase of unauthorized change.

**Comment by DHowett-MSFT** [comment]
Get a better AV. Our application bundle is code-signed

**Comment by DHowett-MSFT** [comment]
I think #1204 is a duplicate of this!
