### ISSUE TITLE
Configuration Change Issue

### ISSUE THREAD

**Issue by ForbiddenEra** [microsoft/terminal#14191]
Edit: I'm an idiot and totally dyslexia'd a version number.

**Comment by DHowett** [comment]
Oh, thanks for following up! I'm guessing that was, "I thought `1.7` was `1.17`, which would have been newer than `1.16`?"

Point taken about updating the bug template, though... just to make it a little bit clearer, we should probably do that. Trust and usability is won by inches. :smile:
