### ISSUE TITLE
Leftover image of cursor after ESC[?25l (DECTCEM)

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#14194]
### Windows Terminal version

WindowsTerminalPreview 1.16.2209.09003

### Windows build number

10.0.19044.2130 (2009, 21H2)

### Steps to reproduce

With `ESC = <escape character>` in CMD's environment, I did this (below).  The cursor is off, but there is a leftover image of it.

![image](https://user-images.githubusercontent.com/61856645/195390517-8abcc2e8-c932-48ca-883a-f5e62832dba6.png)

### Actual Behavior

See above.

**Comment by DHowett** [comment]
I'm pretty sure this is fixed in `1.16.2209.21002`.

One of the benefits of running unpackaged is that you are in control of your own updates.
One of the downsides of running unpackaged is that you are in control of your own updates.

**Comment by vefatica** [comment]
That's pretty close to my version.  If it's available, I'll update and report back.

**Comment by DHowett** [comment]
Thanks! /dup #14028
