### ISSUE TITLE
Profiles with long names can cause a crash in breadcrumb bar

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14197]
### Windows Terminal version

 1.17.2842.0

### Steps to reproduce

1. Open settings UI
2. create a profile with a really long name
3. click on the breadcrumb button at beginning of that page (you probably have to re-navigate to it to get the profile name to propagate)

### Expected Behavior

Honestly, that button shouldn't be there, probably?

### Actual Behavior

<img width="733" alt="image" src="https://user-images.githubusercontent.com/11050425/195451166-760d38a0-8803-479c-9683-b10866278d2c.png">

Clicking that button at the top left crashes the app

**Comment by PankajBhojwani** [comment]
This no longer repros on main (tried on my machine and on @carlos-zamora's). Which is funky because I don't think the breadcrumb bar has been meaningfully changed since. 

Closing as no-repro for now.

**Comment by DHowett** [comment]
Current thinking is that this is a difference between the framework package version of XAML (used by Terminal-Win11) and the sxs-deployed version (used by Terminal-Win10).
That makes it look very **Resolution-External**.
