### ISSUE TITLE
Font size different in different terminals even though the same in points

### ISSUE THREAD

**Issue by mobluse** [microsoft/terminal#142]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17128.1] (Swedish). I use most updated (using apt-get update and dist-upgrade) Ubuntu from Store.

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
![wsltty9cmdexe14](https://user-images.githubusercontent.com/5777329/38132219-7691c23a-340a-11e8-82de-e5804425f643.png)
[WSLtty](https://github.com/mintty/wsltty) version 1.8.4 has font size 9 pt and Cmd.exe has font size 14, but they look the same size on screen.

* What's wrong / what should be happening instead:
I don't know if WSLtty or Cmd.exe is right about font sizes, but I think a font size in points should be the same on screen in different programs.

**Comment by mobluse** [comment]
I learned that the font-size in Cmd.exe is measured in pixels -- not points, but it doesn't say that in the GUI.

**Comment by DHowett-MSFT** [comment]
Pixels is right! This is by design, but look for changes in font handling for Windows Terminal.

**Comment by Lombra** [comment]
Were there ever any changes done to this? For ages I've been using Consolas size 10 (for things like Notepad) which almost perfectly matches size 14 in the Windows console. Lately though, console size 16 has started to grow on me, but in Windows Terminal it's simply not possible to achieve the equivalent appearance. Especially in bold it looks entirely different.

**Comment by Dioarya** [comment]
is there a way to do the old "by pixel" font sizes like in cmd but in windows terminal?
