### ISSUE TITLE
Should WT allow me to launch Ubuntu commands from Windows?

### ISSUE THREAD

**Issue by aruku** [microsoft/terminal#14203]
I want to use WT to launch the Ubuntu shell and immediately run a command on it. Is this possible or am I wrong?
For example, on CMD:
`wt -d /home/edu/projects/company make serve`
The `make` command works fine when I enter it on the terminal, but when doing it like that I get:
`[error 2147942402 (0x80070002) when launching `make']`

Just launching the Ubuntu shell and changing the directory also works fine.

Thank you in advance.

**Comment by zadjii** [comment]
This is basically the `--appendCommandline` request - add the command line to the profile's, rather than replacing it

**Comment by aruku** [comment]
Like this? `wt -d /home/edu/projects/company --appendCommandline make up`

It says the --appendCommandline was not expected. I'm using version 1.15.2713.0.

**Comment by zadjii-msft** [comment]
Sorry, I was making a quick note on my phone. This is /dup #5528
