### ISSUE TITLE
Refactor the VT DSR handler to support both ANSI and private options

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#14206]
# Description of the new feature/enhancement

Our current implementation for the _Device Status Report_ sequence is only setup to accept ANSI status options. But eventually we'll also need a way to support private DEC options. In particularly, I'm hoping to support a couple of DEC macro status reports as part of issue #14205, so I'd like to get the framework in place for that in advance.

# Proposed technical implementation details (optional)

I figured we could follow the exact same pattern that was introduced to support both ANSI and DEC modes in PR #8469.

**Comment by DHowett** [comment]
Sounds good to me! Thanks!
