### ISSUE TITLE
Provide option to add terminal in explorer

### ISSUE THREAD

**Issue by twoco** [microsoft/terminal#14220]
It would be great if I can just right click on a folder (its background) and choose "Open in Terminal". Which simply opens the Windows Terminal with the path. Keep it simple. Just one context menu entry with the icon and text. No complex menu or additional options. I could add my own shell entry in regedit. But this should not the solution. The idea is to provide this option in the Terminal settings (add and remove; maybe just in user scope which requires no admin). Another problem is that the new Windows Terminal folder path (apps) has a dynamic folder (path) name. The app version is included. This makes it hard to add a custom shell entry. Even when using just the "wt" command instead of the path. I get an error (0x80070005). Anyway, it would be great if you provide an official solution.

**Comment by twoco** [comment]
Workaround: My current reg file:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\psterminal]
@="Terminal"
"icon"="C:\\Windows\\System32\\cmd.exe"

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\psterminal\command]
@="wt -d ."
```

Icon is still set to cmd because the path to this Windows Terminal contains the version in name like:

`C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.2712.0_x64__ect`

**Comment by DHowett** [comment]
This should work today; we offer a right-click option on all folders, selected items that _are_ folders, and the desktop background.

I suspect you're seeing an issue where it's just not working properly?

What version of Windows are you running? What other shell extensions do you have installed?

(I'm gonna move this discussion over to /dup #14185)

**Comment by twoco** [comment]
Ok, it seems that the explorer needs to be restarted (e.g. by killing process in task manager and run again or just reboot PC). I had weird behavior. Two instances of explorer was in task manager. In some paths it worked in other not. Anyway, sorry. A PC reboot (explorer restart) is the solution for everything. The IT Crowd didn't lie. ^^

**Comment by DHowett** [comment]
Ha! Glad it helped!
