### ISSUE TITLE
Open Windows Terminal in current working directory when launched from Explorer

### ISSUE THREAD

**Issue by just-ero** [microsoft/terminal#14235]
# Description of the new feature/enhancement
Currently, executing `wt` in Explorer's path starts Windows Terminal, and defaults to %UserProfile%.  
It would be nice if instead, like with using `cmd`, WT would instead automatically navigate to the directory it was executed in.

**Comment by DHowett** [comment]
Since you closed this bug, I'm guessing that you figured it out?
