### ISSUE TITLE
Cannot use any font besides Consolas

### ISSUE THREAD

**Issue by derekslenk** [microsoft/terminal#14231]
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22621.0

### Other Software

oh-my-posh

### Steps to reproduce

Install oh-my-posh with any of the available ways.
Install a Nerd Font in any available way.
Select the nerd font as your default font in terminal and it won't work. 

### Expected Behavior

Be able to use a different font that I install besides Consolas

### Actual Behavior

````
Unable to find the selected font "ANYTHING NF".

"Consolas" has been selected instead.

Please either install the missing font or choose another one
````

**Comment by derekslenk** [comment]
This worked until the 22H2 update

**Comment by j4james** [comment]
I suspect this might be the same issue as #3257.

**Comment by rozbo** [comment]
tried many nerd fonts...same

**Comment by FDUZS** [comment]
Same here. It seems to be system-wide, not just windows terminal. And, only nerd fonts are affected?

https://github.com/matthewjberger/scoop-nerd-fonts/issues/198

**Comment by lhecker** [comment]
If I'm guessing right (and if j4james is right) this is the old font caching bug.

That one affects anyone who tries to install via any of the regular install methods. In other words, all of those:
<img src="https://user-images.githubusercontent.com/2256941/196180769-53ec56ff-f633-4691-af05-76a2a7036a45.png" width="589" height="260" />
<img src="https://user-images.githubusercontent.com/2256941/196180864-8953e17f-69ee-4fd6-aa80-b7e8305cd948.png" width="319" height="201" />
<img src="https://user-images.githubusercontent.com/2256941/196180806-b50be8be-ef8d-45c9-91fd-ab4b049437e8.png" width="231" height="93" />
...don't work correctly in any recent Windows version and you can't use them without encountering this bug. This includes versions before 22H2 btw, see #12587 for instance.

Instead what you have to do is:
* clean your `%LOCALAPPDATA%\Microsoft\Windows\Fonts` directory of your previously installed, broken fonts
* hold Shift and Right-Click the font file and click this:
  <img src="https://user-images.githubusercontent.com/2256941/196180305-fc0fcd81-bea2-4059-bccc-85b7ad64123d.png" width="327" height="215" />

I don't know in what Windows version this bug will be fixed but I'm personally hoping for it to be resolved next year.

**Comment by FDUZS** [comment]
> Same here. It seems to be system-wide, not just windows terminal. And, only nerd fonts are affected?
> 
> [matthewjberger/scoop-nerd-fonts#198](https://github.com/matthewjberger/scoop-nerd-fonts/issues/198)

the workaround offered by [Dabombber](https://github.com/Dabombber) in the issue above is to restart the font cache service via `Restart-Service -Name FontCache`, which does temporarily solve the problem. I guess I have to run it after every reboot, though.

**Comment by carlos-zamora** [comment]
Marking this as /dup #3257
