### ISSUE TITLE
windows store update of terminal breaks running instance

### ISSUE THREAD

**Issue by jtnord** [microsoft/terminal#14239]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.1098

### Other Software

[clink ](https://github.com/chrisant996/clink) 1.3.46.d6fdd0

### Steps to reproduce

Not fully steps to reproduce... (and would need to force an update somehow via windows store?)

Have a terminal window open with several cmd.exe sessions running (clink is injected into these although I do not believe it changes the outcome, however you would not obviously see it)

When Terminal is updated by windows store the terminal UI is gone, however the sessions running within it are not. (it also appears as though the terminal process is still present but without the UI)

this was noticed as clink will perform and update the console prompt in the background (e.g. git status and other things) and from these cmd.exe session that have no windows anymore clink will try and run some more commands (and these tasks which are run every minute or so fail with 0xc000...145)

### Expected Behavior

Windows store upgrade should not break running sessions.

### Actual Behavior

it appears as though the windows store update of terminal breaks running sessions.

**Comment by carlos-zamora** [comment]
Yeah, unfortunately it's a known issue that the store updating windows terminal ends up closing Windows Terminal itself. We're tracking that over in #3915. As for the ophaning, we're tracking that over in #9914.

We're still trying to work with the Store team to let us request not being killed for an update. Sorry, closing this as a /dup of #9914
