### ISSUE TITLE
Duplicated tab should retain the context of the source tab such as current folder path

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#14245]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.674

### Steps to reproduce

Experiencing this issue in both Command Prompt and Windows PowerShell.

1. Launch Windows Terminal
2. Open a Command Prompt
3. Navigate to any folder apart from the one configured in the launch profile
4. Now duplicate this tab
5. Go to the duplicated tab, and check the context of this tab, it is defaulting to the launch profile rather than the source tab

### Expected Behavior

The duplicated tab should retain the source context. That's what duplication is (the same as how web browsers do).

### Actual Behavior

Defaults to the launch profile rather than retaining the source context.

**Comment by zadjii** [comment]
Did you configure your shell to set the CWD? See: https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#i-tried-to-duplicate-a-tabpane-and-it-didnt-duplicate-the-cwd-what-gives

**Comment by egvijayanand** [comment]
To answer your query, yes, have configured a starting directory for Command Prompt profile. This is for any tabs created newly using the `Open a new tab` action (or its shortcut key combination).

But how does that affect the Tab duplication feature? If the starting directory influences here, then the Duplicate loses its meaning.

Though the configured starting directory will be applied on creating a new tab, if it's duplicate tab action, the current context in the source tab should be applied on top of it.

As that is not the actual behavior, so this is an issue that is to be addressed.

**Comment by DHowett** [comment]
Sorry, I believe Mike's query was whether you have configured Command Prompt to tell Terminal its most recent CWD. The FAQ page he linked further links out to [Tutorial: Opening a tab or pane in the same directory in Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

It loosk like this tutorial makes a couple suggestions about how to fix this issue.
