### ISSUE TITLE
Copy-pasting `foo` results in `0~foo1~` being pasted

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#14246]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Other Software

software on the client:
* PowerShell 7.2.6
* OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

software on the remote host:
* nano 3.2
* OpenSSH_7.9p1 Raspbian-10+deb10u2+rpt1, OpenSSL 1.1.1n  15 Mar 2022

### Steps to reproduce

* ssh into the remote host
* open `nano`
* copy `foo` in Windows
* paste it inside nano

This also occurs when copy-pasting passphrases when using SSH on the remote host.
This doesn't occur when using PowerShell directly (i.e. without Windows Terminal).

### Expected Behavior

`foo` is pasted

### Actual Behavior

`0~foo1~` is pasted

**Comment by zadjii-msft** [comment]
Hmm. We've got a lot of these on the rise:
* #14129
* #14234

I wonder if there's something else that's changed

**Comment by lhecker** [comment]
@zadjii-msft j4james posted a likely cause for those 2 bugs here: https://github.com/microsoft/terminal/issues/14129#issuecomment-1276784394

**Comment by zadjii-msft** [comment]
I'm just gonna combine these discussions. /dup #14129
