### ISSUE TITLE
Automatically add Profiles

### ISSUE THREAD

**Issue by ArtexJay** [microsoft/terminal#1424]
# Summary of the new feature/enhancement

 It would solve the hassle of going into the settings, finding the directory of the new console or linux terminal and figuring out how to add it to Windows Terminal

# Proposed technical implementation details (optional)

I want the Windows Terminal to auto detect when a new Linux Terminal, Console, or powershell is installed on the system and for Windows Terminal to automatically add its profiles and dropdown.

**Comment by DHowett-MSFT** [comment]
This is a part of the spec in #754
