### ISSUE TITLE
Maximized Windows Terminal crashes after exiting a tab

### ISSUE THREAD

**Issue by vbrozik** [microsoft/terminal#14247]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2006

### Other Software

WSL2 with Ubuntu 22.04

### Steps to reproduce

1. Start Windows Terminal.
2. Maximize the window.
3. Open a new tab with Ubuntu.
4. Exit the shell inside the tab (Ctrl+d or logout or exit)
5. Terminal closes the tab, switches back to the first tab and after a while it crashes.

Sometimes you have to repeat from the step 3 few times. I was unable to reproduce the crash by exiting a tab with Windows PowerShell or Command Prompt.

### Expected Behavior

Windows Terminal continuing running without a crash.

### Actual Behavior

Windows Terminal crashes.

Feedback Hub: https://aka.ms/AAignhy

I have found this in Event Viewer > Windows Logs > Application:
```
Faulting application name: WindowsTerminal.exe, version: 1.16.2209.21001, time stamp: 0x632b96ad
Faulting module name: ntdll.dll, version: 10.0.19041.1949, time stamp: 0xfe96c48e
Exception code: 0xc000000d
Fault offset: 0x0000000000112664
Faulting process id: 0x744
Faulting application start time: 0x01d8e2edb0ba0364
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.16.2641.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c6955e69-d4ae-47a8-9faa-6762570e8f90
Faulting package full name: Microsoft.WindowsTerminalPreview_1.16.2641.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

`C:\WINDOWS\SYSTEM32\ntdll.dll` shows a valid Microsoft's signature, file version: `10.0.19041.1949`

This bug might be the same problem: https://github.com/microsoft/terminal/issues/14025

In fact I am almost sure that I encountered the crashes in one or two previous versions.

**Comment by carlos-zamora** [comment]
I'm going to close this as a /dup of #14025 and respond there. Thanks!

**Comment by vbrozik** [comment]
@carlos-zamora I think this ticket has much more relevant data while the older ticket has no history, no attention. Are you sure this should not be closed the other way around?

**Comment by DHowett** [comment]
(I've copied the data into the older ticket. Thanks!)
