### ISSUE TITLE
terminal auto update from Microsoft Store kills running process

### ISSUE THREAD

**Issue by xarthurx** [microsoft/terminal#14251]
### Steps to reproduce

OK, this might not be a bug but an issue that happens to me several times.

I run a process for weeks from terminal.
When using windows terminal, the auto-update from Microsoft Store will always kill the process during the night.
It is possible to make WT only update when no WT process is running?

### Expected Behavior

make WT only update when no WT process is running

### Actual Behavior

WT is updated when the terminal is running some processes.

**Comment by carlos-zamora** [comment]
Yeah, unfortunately it's a known issue that the store updating windows terminal ends up closing Windows Terminal itself. We're tracking that over in #3915.

We're still trying to work with the Store team to let us request not being killed for an update. Sorry, closing this as a /dup of #3915
