### ISSUE TITLE
Run as Admin shortcut + elevate:true -> crash loop

### ISSUE THREAD

**Issue by githubblcb** [microsoft/terminal#14259]
Latest WT release as of today.  

If a shortcut properties are set to run wt.exe as Admin
AND
Run as Admin is also set in wt app settings, new tab or the app will not start, and DesktopWindowXamlSource continuously flashes in taskbar.

**Comment by zadjii-msft** [comment]
> Latest WT release as of today.

Could you give us the actual version number? You could be on preview or on stable, on the Windows 10 build or the Windows 11 one, the Store might not have rolled out the latest build to you or not...

**Comment by githubblcb** [comment]
Annoyingly, version number unavailable within app or even MS Store.

Figured out you have to schlep to  Start > Settings > Apps > Terminal

Terminal ver = 1.15.2874.0
Windows ver = 10.0.19044

**Comment by zadjii-msft** [comment]
> Annoyingly, version number unavailable within app 

![image](https://user-images.githubusercontent.com/18356694/197606684-54a15839-c0dd-408f-8e71-13081955d547.png)

![image](https://user-images.githubusercontent.com/18356694/197606586-b9089d2c-b99f-49b0-8b96-559162e71c02.png)

🙃 

<hr>

on-topic: This looks like it's actually the same as /dup #13928

**Comment by githubblcb** [comment]
@zadjii-msft — Please reveal the secret path to "About" dialog so I can move on with my life.  I swear I looked _everywhere_!

Afa the main issue.. I work around it just fine of course, but since it shouldn't happen reporting seemed Good For the Cause.  Terminal is super clean clever snappy well-behaved like god intended tools to be.  Grandes props to the team. 

I do (cursory) issue scans beforehand, but spotted only similar ones that were closed, oops.
