### ISSUE TITLE
Can not type in square brackets when using Apple/Swedish keyboard layout on Windows 10.

### ISSUE THREAD

**Issue by geoaxis** [microsoft/terminal#1425]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):

Apple bootcamp 6.1
```

# Steps to reproduce
Open windows terminal and try to type `[` or `]`

# Expected behaviour
One is able to type the characters

# Actual behaviour
In PowerShell one gets 
`digit-argument : 8`

in ubuntu one gets 
`(arg: 8)`
 instead of the actual characters

Typing the characters in CMD.exe works fine.

**Comment by DHowett-MSFT** [comment]
Probably a duplicate of #521

**Comment by geoaxis** [comment]
it sure is.
