### ISSUE TITLE
Windows Terminal crashing when resizing panes

### ISSUE THREAD

**Issue by VanVan** [microsoft/terminal#14254]
### Windows Terminal version

1.16.2642.0 ( and tested also on 1.15.2875.0)

### Windows build number

Windows 11 22H2 22621.674  (Windows Feature Experience Pack 1000.22634.1000.0)

### Other Software

Powershell not required, the same occur with command line

### Steps to reproduce

- Open Windows Terminal
- Maximize window to have more space for resizing (optional but makes it easier to reproduce)
- Split the terminal horizontally (2 pans is enough)
- Resize right and left pane repeatedly using keyboard shortcuts Alt + Shift + Left and Alt + Shift + Right holding down the right and left keys sometimes.
- Crash of the app and lost all pans

### Expected Behavior

The panes should resize without issues

### Actual Behavior

Windows Terminal crashes
We lost all pans at once

**Comment by VanVan** [comment]
This bug is not new and has been reported before but closed for lack of additional information :
https://github.com/microsoft/terminal/issues/8287

**Comment by VanVan** [comment]
Here is a short video example of a quick crash, sometimes it's slower, and you have to move more, it's random.
https://user-images.githubusercontent.com/388581/196766716-542b6801-41e6-4ca3-a1b2-c458c5b0c2aa.mp4

**Comment by VanVan** [comment]
Here is a short video example of a quick crash, sometimes it's slower, and you have to move more, it's random.

https://user-images.githubusercontent.com/388581/196767243-c24c24fa-50f9-4aa9-8695-e94c4f3211cb.mp4

**Comment by carlos-zamora** [comment]
We're having trouble getting a repro. Could you file feedback using the steps above to help us out? That'll give us more insights as to what's going on.

**Comment by VanVan** [comment]
Hi,
Here is the information requested.

[FeedBack Hub Link](https://aka.ms/AAifhfi)

[events_viewer.zip](https://github.com/microsoft/terminal/files/9824989/events_viewer.zip)

Note that this problem does not occur on another of my computers, so there is probably some related configuration.

**Comment by yurizabiyaka** [comment]
same issue Windows Terminal Preview
Version: 1.19.2682.0
Windows 10 pro 22H2/nvidia driver 522.06

**Comment by nathan130200** [comment]
Same issue, crashing when resizinh the window itself:

https://github.com/microsoft/terminal/assets/14365254/363ae500-4ca0-4b4e-9fe2-528e75b5f11e

**Comment by nathan130200** [comment]
Same issue, crashing when resizing the window:

OS Version: Windows 22H2 (Build: 10.0.19045.4170)
Version: 1.19.10573.0

```cs
Descrição
Nome do aplicativo com falha: WindowsTerminal.exe, versão: 1.19.2402.26003, carimbo de data/hora: 0x65dce3ea
Nome do módulo com falha: ntdll.dll, versão: 10.0.19041.3996, carimbo de data/hora: 0x39215800
Código de exceção: 0xc0000374
Deslocamento da falha: 0x00000000000ff349
ID do processo com falha: 0x3544
Hora de início do aplicativo com falha: 0x01da7870c0465653
Caminho do aplicativo com falha: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Caminho do módulo com falha: C:\Windows\SYSTEM32\ntdll.dll
ID do Relatório: cdeb4853-6962-4f42-baeb-4a07a0969f15
Nome completo do pacote com falha: Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe
ID do aplicativo relativo ao pacote com falha: App

```

**Comment by mer30hamid** [comment]
> Same issue, crashing when resizing the window:
> 
> OS Version: Windows 22H2 (Build: 10.0.19045.4170) Version: 1.19.10573.0
> 
> ```cs
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
> 	<System>
> 		<Provider Name="Application Error" /> 
> 		<EventID Qualifiers="0">1000</EventID> 
> 		<Version>0</Version> 
> 		<Level>2</Level> 
> 		<Task>100</Task> 
> 		<Opcode>0</Opcode> 
> 		<Keywords>0x80000000000000</Keywords> 
> 		<TimeCreated SystemTime="2024-03-17T15:15:02.4093899Z" /> 
> 		<EventRecordID>36968</EventRecordID> 
> 		<Correlation /> 
> 		<Execution ProcessID="0" ThreadID="0" /> 
> 		<Channel>Application</Channel> 
> 		<Computer>DESKTOP-75JEN6A</Computer> 
> 		<Security /> 
> 	</System>
> 	<EventData>
> 		<Data>WindowsTerminal.exe</Data> 
> 		<Data>1.19.2402.26003</Data> 
> 		<Data>65dce3ea</Data> 
> 		<Data>ntdll.dll</Data> 
> 		<Data>10.0.19041.3996</Data> 
> 		<Data>39215800</Data> 
> 		<Data>c0000409</Data> 
> 		<Data>00000000000a4ff8</Data> 
> 		<Data>1c20</Data> 
> 		<Data>01da787de07e564e</Data> 
> 		<Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
> 		<Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
> 		<Data>8e65b1a0-ba1e-4ba4-9e59-697701a82c32</Data> 
> 		<Data>Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe</Data> 
> 		<Data>App</Data> 
> 	</EventData>
> </Event>
> ```

I have disabled `Use the new text renderer ("AtlasEngine")` and this fixed this problem !
![image](https://github.com/microsoft/terminal/assets/1561497/7f194fb0-d33c-4c1b-afde-fd258e27ab8a)

**Comment by lhecker** [comment]
@mer30hamid The option to disable AtlasEngine will go away in the future. Could you please assist me in figuring out why it crashes? To do so, please enable AtlasEngine again and send me a crash dump. You can find my email address in my GitHub profile. Here's how to enable crash dumps: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically

**Comment by mer30hamid** [comment]
> @mer30hamid The option to disable AtlasEngine will go away in the future. Could you please assist me in figuring out why it crashes? To do so, please enable AtlasEngine again and send me a crash dump. You can find my email address in my GitHub profile. Here's how to enable crash dumps: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically

Done.

**Comment by nathan130200** [comment]
@mer30hamid wow thanks! The windows terminal stopped to crashing.

**Comment by nathan130200** [comment]
@mer30hamid I've tried didn't worked. I can fix this when i enabled software rendering instead of hardware rendering.

**Comment by lhecker** [comment]
@mer30hamid Thanks! Your terminal is crashing due to a heap corruption. Unfortunately I can't tell what's corrupting your heap. Would you be willing to help me test it further?

If so, one thing I'd like to test if Windows Terminal Canary crashes. You can install it here: https://aka.ms/terminal-canary-installer
After installing it, make sure it has imported all your settings from your regular Windows Terminal. (Otherwise open the settings file with Ctrl+Shift+, in both applications and copy it over.)
Does Canary also crash for you?

**Comment by lhecker** [comment]
@nathan130200 Your crash is super interesting! Would it be possible to share that crashdump with me? You can find my email address in my GitHub profile. Otherwise, could you tell me what the value of the `size` parameter is?

**Comment by mer30hamid** [comment]
> @mer30hamid Thanks! Your terminal is crashing due to a heap corruption. Unfortunately I can't tell what's corrupting your heap. Would you be willing to help me further test this?
> 
> If so, one thing I'd like to test is whether Windows Terminal Canary crashes for you. You can install it here: https://aka.ms/terminal-canary-installer After installing it, make sure it has imported all your settings from your regular Windows Terminal. (Otherwise open the settings file with Ctrl+Shift+, in both applications and copy it over.)

I can't install it because my windows version is: `windows 10 22H2 Build 19045.4170` and I get this error:
```
App installation failed with error message: Windows cannot install package Microsoft.WindowsTerminalCanary_1.21.803.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.22000.0 or higher on the Windows.Desktop device family. The device is currently running OS version 10.0.19045.4170. (0x80073cfd)
```
p.s: When I enable `use software rendering ` the crash does not accur

**Comment by lhecker** [comment]
@mer30hamid Ah sorry, I forgot that the appinstaller had this limitation. I believe the portable .zip should work though. You can get it here: https://aka.ms/terminal-canary-zip-x64

**Comment by mer30hamid** [comment]
> @mer30hamid Ah sorry, I forgot that the appinstaller had this limitation. I believe the portable .zip should work though. You can get it here: https://aka.ms/terminal-canary-zip-x64

I sent you the crash dump for this version, turning the "Use software rendering" option to "on" , solved the problem again!

**Comment by nathan130200** [comment]
@lhecker the `size` param value is 331, combined with `sizeof(DWRITE_GLYPH_OFFSET) + size` value is 339 (+8 bytes). I will send a crashdump.

**Comment by nathan130200** [comment]
@lhecker the `size` param value is 331, combined with `sizeof(DWRITE_GLYPH_OFFSET) * size` value is 2648. ~~I will send a crashdump~~.

Update: I've checked here and if i let windows choose prefered GPU for Terminal, then will use my onboard-gpu and will trigger the crash if `Enable software rendering` is not enabled while resizing the window. While i manually set to windows use my offboard gpu, don't crash Terminal. 

I will sent you the crash dump.

**Comment by lhecker** [comment]
@nathan130200 Thanks for the dump! It's very helpful, since it contains a reference to the entire AtlasEngine instance at the time of the crash. I've written a response here: https://github.com/microsoft/terminal/issues/16747#issuecomment-2017980996
In your case, I would recommend to continue using your Nvidia GPU.

By the way, since you say "onboard-gpu", are you sure your have your monitor plugged into your Nvidia GPU? Because if you did, Windows Terminal should've been using your Nvidia GPU by default. I would suggest checking that. 🙂

**Comment by nathan130200** [comment]
I've said "on-board GPU" because its a laptop GPU, then windows keep switing between HD Graphics (default for non 3d/2d/graphics related) and GeForce 710M (when using directx/opengl stuff).

**Comment by lhecker** [comment]
I have another idea why this may occur and will add a bunch of settings to the Rendering tab to give users more control over this. 🙂
