### ISSUE TITLE
Add horizontal scroll indicators for occluded tabs

### ISSUE THREAD

**Issue by compnerd** [microsoft/terminal#1426]
# Summary of the new feature/enhancement

Currently, the tab bar is limited to a certain percentage of the window.  With PowerShell showing the full path to the image, you quickly fill up the bar and additional terminals being opened are occluded.  It would be nice to have a horizontal scroll bar to indicate that there are hidden tabs.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Oh @compnerd, I hoped I’d never have to say: please search for existing issues before filing a new one :)
#608 #1320 #597 #857 

You can also override the title with a VT sequence, like in xterm.

**Comment by compnerd** [comment]
I tried to search and failed miserably.  Seems that #857 is the closest to what I was looking for.  I guess this is tracked.  Sorry about the noise.
