### ISSUE TITLE
[W11] Windows Terminal has broken SSH key perms for me

### ISSUE THREAD

**Issue by Turbine1991** [microsoft/terminal#14269]
### Windows Terminal version

0

### Windows build number

11.22621.675

### Other Software

Unfortunately wt or ver does not work in this buggy new windows terminal now apart of W11. I'm really annoyed as I went away to make some food from working, it restarted and automatically updated my PC and crippled me from accessing any device through SSH. Surely there must be a better way. None of the usual alternative workarounds are working right now.

- ssh provided through wsys2
- Directory access (which is accessible through file manager)

### Steps to reproduce

- Update Windows 11 to the latest version which replaces CMD.
- Try to connect SSH in using a key

### Expected Behavior

- Logs in using the existing directory permissions, as Windows ignores and doesn't properly implement POSIX ACL permissions. (Can't 700 the directory)

### Actual Behavior

```
Load key "C:/ssh/orangepi4_id_rsa": Permission denied
asr@192.168.1.10: Permission denied (publickey).
```

This worked perfectly fine an hour ago in CMD.

**Comment by DHowett** [comment]
I'm guessing based on the history of this issue that you solved your permissions issue? I'm glad!

Is it something that may help other people?
