### ISSUE TITLE
A black block appears in my desktop when I launch and minimize Terminal.

### ISSUE THREAD

**Issue by Briar-CatHei** [microsoft/terminal#14261]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.754

### Steps to reproduce

Open the Terminal and minimize it.

### Actual Behavior

A small black square appears in the upper left corner when I open Terminal.
![屏幕截图_20221020_150149](https://user-images.githubusercontent.com/82100581/196879969-7a5ec298-bb35-4142-8363-156649ecb906.png)

Then, when I minimize that, a small black rectangle appears in the bottom left corner.
![屏幕截图_20221020_150157](https://user-images.githubusercontent.com/82100581/196880662-46eba637-ae69-461e-a913-abf0dde4fb54.png)

**Comment by DHowett** [comment]
Since you closed this issue, I'm guessing that the problem went away? Thanks!

**Comment by Briar-CatHei** [comment]
> Since you closed this issue, I'm guessing that the problem went away? Thanks!

I realized that a application called "Mica For Everyone" which changeed forms in Acrylic or Mica appearance globally was running in the background after I reported this issue.
![屏幕截图_20221021_093109](https://user-images.githubusercontent.com/82100581/197090651-5533b762-242f-473b-8e54-d933eb3f632a.png)

In default, nothing appear.
![屏幕截图_20221021_093925](https://user-images.githubusercontent.com/82100581/197091158-c89cc608-b023-4d39-9b3f-3a65c5f5204f.png)
![屏幕截图_20221021_094014](https://user-images.githubusercontent.com/82100581/197091204-8bcac8b5-d03a-4532-9fa2-2ad3c9aa9e19.png)

But when I set the Backdrop Type of Mica For Everyone to "Mica", the black block appears.
(Set to "Acrylic", the block is gray.)
![屏幕截图_20221021_094248](https://user-images.githubusercontent.com/82100581/197091557-ef0e72c5-fde7-4be4-8dd5-e3c9a95f27ee.png)
![屏幕截图_20221021_094552](https://user-images.githubusercontent.com/82100581/197091893-adb2f128-94bd-4eac-a52b-831aa0a901ef.png)

Then I use "Pop-up blocking" in Huorong Security application, I found it may cause by openconsole.exe of Terminal.
![屏幕截图_20221021_095151](https://user-images.githubusercontent.com/82100581/197092570-e936b715-fb44-48a0-8c14-dd61b2293499.png)
![屏幕截图_20221021_095501](https://user-images.githubusercontent.com/82100581/197093928-e8c38eeb-2f2e-4c77-99bf-1929cfa693bc.png)

And then, I terminate Mica For Everyone and restart Terminal, the block disappears, but it still can be found by Pop-up blocking.
![屏幕截图_20221021_101115](https://user-images.githubusercontent.com/82100581/197095055-92e0256c-ac54-4ece-b1e0-2403fc3e15ef.png)
![屏幕截图_20221021_101434](https://user-images.githubusercontent.com/82100581/197095419-4c3b6d39-27bd-47e8-8d88-7dc2bd28d89e.png)

I don't know this block was caused by Mica For Everyone or openconsole.exe of Terminal, or why openconsole.exe ran in the desktop invisibly in default. But it can be hidden by Mica For Everyone setting, so I closed this issue.
