### ISSUE TITLE
Crash when selecting non-bitmap image in background selector for Windows PowerShell

### ISSUE THREAD

**Issue by bunniico** [microsoft/terminal#14265]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621

### Steps to reproduce

1. Go to **settings.**
2. Go to **Windows PowerShell**
3. Go to **Appearance**
4. Background Image -> Background Image Path -> Browse...
5. Change from **"All Supported Bitmap Types"** to **"All Files"**
6. Select a non-bitmap type image. (I used a .webp to cause the crash)

### Expected Behavior

I expected an error asking me to input a valid bitmap image.

### Actual Behavior

The program crashed silently (no error pop-up or warning)

**Comment by PankajBhojwani** [comment]
I can't seem to repro this in WT Stable or in our selfhost Preview build, can you post the `.webp` file you're using? It might be a problem with that file specifically

**Comment by bunniico** [comment]
Between the posting of this issue and now I've had to reset my computer so I don't have the exact file. When trying to reproduce this issue now on Windows 10, it does not crash but it also allows me to select invalid file types such as .midi, .mp4, .sm, .webp, etc. I'm not sure if it only crashes on Windows 11 or what, and I can't really test since my machine isn't set up the same way anymore.

**Comment by PankajBhojwani** [comment]
We have tried it on Win 11 and can't get a crash either. In that case, I'm going to close this as no-repro. Please feel free to reopen this if it starts repro-ing again for you!
