### ISSUE TITLE
Ask: Publish Releases to Chocolatey

### ISSUE THREAD

**Issue by SeanKilleen** [microsoft/terminal#1427]
# Summary of the new feature/enhancement
I love that the Terminal is now published to the windows store -- congrats on that great step!

To keep applications synced up across multiple machines and to ensure I can recreate machines quickly as needed, I'm a big fan of [Chocolatey](http://chocolatey.org).

I'd love to be able to run `choco install terminal`, as I currently can for other terminal applications such as `Cmder`. 

# Proposed technical implementation details (optional)

Because a release pipeline already exists and appears to be published in `yml` (thank you for that, too!) I believe I could submit a pull request to add a release push to Chocolatey as well. I should be able to test locally.

I would be happy to publish this under my chocolatey account, but it seems like an opportunity to help Microsoft publish it in an official way as well. 

Let me know if you are open to this idea and I will begin to explore it.

**Comment by pilcherd** [comment]
I think alternative paths for install other than the Store are important.

E.g. I couldn't get WinDbg Preview installed the other day as it was needed on an isolated server and needs the Store to install.

The Store is great.  When it's available.  But please make offline installers for tools available too.

Thanks

**Comment by SeanKilleen** [comment]
@pilcherd if you're interested in offline installers, you may wish to add that as a separate GitHub issue. I'd like to scope this purely to publishing to a Chocolatey feed, to ensure it doesn't grow in scope.

**Comment by DHowett-MSFT** [comment]
I'm going to make #1386 the master issue for alternate distribution mechanisms. Thanks!
