### ISSUE TITLE
Terminal does not get focused properly

### ISSUE THREAD

**Issue by vikke1234** [microsoft/terminal#14276]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.2130

### Other Software

Autohotkey example keybind for opening terminal (keybind is super + enter)
`#Enter::Run, wt.exe`

### Steps to reproduce

1. Press keybind to open terminal
2. Start typing

### Expected Behavior

I should either start buffering the input, similar to how the linux terminals do it. You don't need to open it with ahk, similar behavior is seen with just typing `wt.exe` in your faviourite console and begin typing. Although it's harder to reproduce.

### Actual Behavior

Typing in previous window

**Comment by hkjels** [comment]
This is extremely annoying for a recent "convert" from MacOS/Linux.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13388 for more discussion.

/dup #13388
