### ISSUE TITLE
Cursor stops blinking with Cygwin

### ISSUE THREAD

**Issue by carlescufi** [microsoft/terminal#14271]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.675

### Other Software

Cygwin 3.3.6-1

### Steps to reproduce

1. Open a new tab with a Cygwin profile.
2. Play around for a while (`ls -la`, open and close `vim`)
3. Cursor stops blinking

### Expected Behavior

Cursor continues blinking no matter what I do on my terminal
Note: `mintty` behaves as expected on the same machine, running the same Cygwin instance

### Actual Behavior

Cursor stops blinking.

**Comment by lhecker** [comment]
I believe this is an approximate duplicate of #10754. Would you agree with this?

**Comment by carlescufi** [comment]
> I believe this is an approximate duplicate of #10754. Would you agree with this?

I think it's more similar to #13996, I have left a comment there.

**Comment by carlescufi** [comment]
I am reopening this because https://github.com/microsoft/terminal/issues/13996 has been closed. FYI @lhecker.

**Comment by lhecker** [comment]
> I have the same problem but it happens even without sshing into a Linux host, it also happens in my case with Cygwin running locally: I load `vim`, the cursor stops blinking (no artifacts).

This doesn't really matter to us, as a terminal, as `vim` over SSH behaves largely identical to `vim` via cygwin. I don't mean to antagonize you by closing this issue on you again, but just like with the other issue (#13996), I'm extremely confident that this is a duplicate of #10754.
@DHowett @zadjii-msft Would you agree with this?

**Comment by carlescufi** [comment]
@lhecker you're the expert. If you feel this is a dup of #10754 I have no reason to doubt that. Let me close this as a dup then.
