### ISSUE TITLE
Windows Terminal Titlebug separated from the tab row.

### ISSUE THREAD

**Issue by A-Lamia** [microsoft/terminal#1428]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): First preview version.
```

# Steps to reproduce

Happens when i start the application, was fine on first install only showed up after PC restart.

# Expected behavior

Title bar should be on the same row as the tabs.

# Actual behavior

Title bar has separated from the tab row creating some rendering issues in the terminal.

![Windows Terminal Bug](https://imgur.com/Dh0gV5V.png?raw=true)

**Comment by DHowett-MSFT** [comment]
This is a setting in your `profiles.json`. Please toggle it.
