### ISSUE TITLE
Provide git status if the current folder is a git repo

### ISSUE THREAD

**Issue by savornicesei** [microsoft/terminal#14286]
Hi all,

# Description of the new feature/enhancement
I have been spoiled by [Cmder](https://github.com/cmderdev/cmder) which, at least for pwsh consoles, shows a small git status. This helps me a lot to figure out on what branch I am, if I am still in the middle of a merge or rebase without entering git commands.

![image](https://user-images.githubusercontent.com/917232/197415414-86864695-3b3e-415d-a449-a385855bd314.png)

I guess this is the only feature that's keeping me on Cmder.

# Proposed technical implementation details (optional)
For pwsh consoles, [posh-git](https://www.powershellgallery.com/packages/posh-git) is used under the hood.
Integration with git should be optional, as it is implemented in Cmder, see [here](https://github.com/cmderdev/cmder#git-status-opt-out) the flags.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I don't really want to be in the business of manually trying to change user's prompts for them. Users are more than welcome to customize their prompt on their own (we've even got [a guide in our docs](https://learn.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup)). But us doing this automatically just runs the risk that we'll stomp on customizations that the user already set up.

**Comment by savornicesei** [comment]
@zadjii-msft I was not aware of customizations. Thank you, I'll look into it.
