### ISSUE TITLE
After maximizing terminal after `git log --oneline`, terminal tab hangs upon trying to quit

### ISSUE THREAD

**Issue by rzhao271** [microsoft/terminal#14288]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.0

### Other Software

git version 2.35.1.windows.2

### Steps to reproduce

1. Make sure the terminal isn't maximized.
2. Run `git log --oneline` in a git repo.
3. Maximize the terminal.
4. Press the `q` key to quit from the pager.

### Expected Behavior

I expect the prompt to show up again, so that I can input the next command.

### Actual Behavior

The terminal tab doesn't seem to respond. It doesn't crash, though.

**Comment by carlos-zamora** [comment]
Thanks for the feedback! I'm gonna mark this as /dup #11903 unless proven otherwise

**Comment by rzhao271** [comment]
Thanks for the issue ref. I took a look in the task manager and it seems that killing `less.exe`, which comes up as part of the git log command, brings back the prompt. But, I'm unable to repro the issue using Git Bash.
The CPU and memory usage seem normal as well. It's just that in step 4 above, I'm unable to quit from less after pressing q. Other keypresses don't work either after step 4, and I have to create a new tab to continue working.

![Screenshot showing the process tree. There are some processes like Git for Windows, less, pwsh, OpenConsole, and Windows Terminal](https://user-images.githubusercontent.com/7199958/198152064-a78fa11e-940c-4bfd-ada6-e25a3df9f9c0.png)

**Comment by NikoAri** [comment]
Confirmed that killing `Less.exe` process solves this problem.
