### ISSUE TITLE
How to add language, for example: Chinese。

### ISSUE THREAD

**Issue by a48625a** [microsoft/terminal#14281]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by a48625a** [comment]
How to add language, for example: Chinese。

**Comment by zadjii-msft** [comment]
I'm sorry, but I'm not sure I understand the question/? The Terminal is already translated into Chinese. It should automatically launch in your system locale, but if you'd like to change the language manually, you can do so via the settings:

![image](https://user-images.githubusercontent.com/18356694/197506757-3a650637-9dc4-4b34-9c98-3fdd169ebec5.png)

**Comment by a48625a** [comment]
34/5000 
I mean I compile my own code how to add languages. The dev version I compiled myself is only in English.

**Comment by a48625a** [comment]
I mean how do I add language when I compile the codes. The dev version I compiled myself is only in English.

**Comment by zadjii-msft** [comment]
I'm not sure the final localization files are published anywhere other than in the package itself. The translated resources all come from an internal loc service, and aren't part of the repo itself. I suspect if you're running dev builds, you might just be out of luck here 😕

**Comment by a48625a** [comment]
Thank you for your answer。
