### ISSUE TITLE
Incorrect type in settings schema for `startingDirectory` property

### ISSUE THREAD

**Issue by PetSerAl** [microsoft/terminal#14299]
In settings schema (https://aka.ms/terminal-profiles-schema) type of `startingDirectory` property described as `string`. But when you set inherit starting directory from parent process, the `null` value get saved to the property.

**Comment by zadjii-msft** [comment]
Huh. Didn't know that `null` wasn't a valid value for a string in json schema. See: https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema

**Comment by BenConstable9** [comment]
Happy to submit a PR for this simple fix.
