### ISSUE TITLE
installing Windows Terminal for all users

### ISSUE THREAD

**Issue by F3d0s** [microsoft/terminal#14294]
### Request
Make it possible for Windows Terminal to be installed for all users

Admin users use 2 different account to run some applications, standard user and admin user, Windows Terminal can't be installed for All Users and wouldn't run using a different user that the one who installed the app.

Please make it possible to install the application for All Users.

### Expected Behavior
Running the application using a different Windows account profile, such as an admin account.

### Actual Behavior
When running the application as Administrator, we get this error message "**The application cannot be started for the target user. Please login as the user and explicitly install this package**"

**Comment by carlos-zamora** [comment]
Hi @F3d0s. This should actually be a request on the Microsoft Store team. That way, you can install an app for all the users (regardless of it being Windows Terminal). Please go ahead and file this feedback via feedback hub and make sure you select the Microsoft Store as the target there.
