### ISSUE TITLE
Ctrl-Shift-6 opens a new terminal tab. Instead, I expected this key combination to be sent to the remote Cisco switch I was connected to via WSL/ssh client

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#14297]
### Windows Terminal version

latest preview

### Windows build number

latest 10

### Other Software

WSL1

### Steps to reproduce

have more than 5 profiles defined
ctrl-shift-N is by default assigned to start a new tab for the Nth profile

### Expected Behavior

I need ctrl-shift-6 to be passed to terminal instead, since this is the key combination that stops the current comand, such a long running ping on a cisco switch

### Actual Behavior

opens a new tab with the 6th defined profile

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/198281213-1a48d669-82d9-4ee5-950b-294a59ed5c81.png)

**Comment by mailinglists35** [comment]
I've been scrolling through all 7 pages of 154 results for "ctrl shift" but haven't been able to identify a duplicate

**Comment by zadjii-msft** [comment]
You can just [unbind the key in your settings](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#unbind-keys-disable-keybindings).
