### ISSUE TITLE
Running Cygwin using context menu shows default directory

### ISSUE THREAD

**Issue by AarjavPatni** [microsoft/terminal#14296]
### Windows Terminal version

1.15.2875

### Windows build number

22000.1098

### Other Software

Cygwin

### Steps to reproduce

Run the terminal using the context menu in a folder

### Expected Behavior

![image](https://user-images.githubusercontent.com/68058926/198206699-894b6864-8ba2-47b0-be49-6384952156de.png)
![image](https://user-images.githubusercontent.com/68058926/198218273-09708840-9948-46a1-ae42-477d6b54907a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/68058926/198218064-a3f29e41-75aa-45ad-9aed-cc09415b927a.png)

**Comment by DHowett** [comment]
How is your Cygwin profile configured?

**Comment by AarjavPatni** [comment]
What do you mean? Is there a specific file I should show you?

**Comment by zadjii-msft** [comment]
Yea, the [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?
