### ISSUE TITLE
ctrl+plus as change font size messes with telnet

### ISSUE THREAD

**Issue by michael-r-elp** [microsoft/terminal#14305]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.0

### Other Software

Microsoft Telnet-Client
10.0.22000.708

### Steps to reproduce

With telnet installed and german keyboard layout or any that have ctrl+plus open a telnet session to an host
Try to press ctrl+plus

Change Settings in Windows Terminal and change default keybinding for setting a larger font size to something different than ctrl+plus or delete that keybind entirely and save
Attempt to start another telnet session and try to escape with ctrl+plus

### Expected Behavior

Having escape into the telnet prompt work with default windows terminal settings

### Actual Behavior

It seems windows terminal has a default keybinding for ctrl+plus, that changes the font size
It might be an better idea to have that as ctrl+numpad_plus or 
something that doesn't cause issues when using telnet with the default escape character

My options here were either change or remove the keybinding in windows terminal (I removed it once I found it) or 
start a telnet session with `-e` to specify a custom escape character

Maybe there could be a better default keybinding you could set in windows terminal that would not interfere with telnets default
It would probably also be fine to leave it as is? 
But it kinda caused a bit of confusion for me, maybe just having terminal forward ctrl+plus even with a keybinding set for it, might work, but could possibly cause issues in other situations.

I'll leave it up to you guys what you think could/should be done here

**Comment by zadjii-msft** [comment]
It looks like we've got it bound to both:

https://github.com/microsoft/terminal/blob/8ea3cb9972491dec322f53ad69525a431a1d8431/src/cascadia/TerminalSettingsModel/defaults.json#L444-L447

I honestly think the best recommendation here is just to unbind `ctrl+plus` if you're already using it for something in your client app (telnet). 

But thanks for bringing this up! I honestly didn't know `ctrl+plus` was used for that in telnet!
