### ISSUE TITLE
Vertical line not triggered by AltGr + W in hr-HR locale

### ISSUE THREAD

**Issue by ivfranji** [microsoft/terminal#1430]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

Change keyboard layout to hr-HR and try to write vertical line (char 124) '|' using combination AltGr + W

# Expected behavior

Have vertical line with AltGr + W combination

# Actual behavior

Prints nothing, completely ignores combination.

**Comment by DHowett-MSFT** [comment]
Please search before reporting new issues. #521
