### ISSUE TITLE
Options for a higher degree of control over the 'retro terminal effects'

### ISSUE THREAD

**Issue by konsoul** [microsoft/terminal#14308]
# Description of the new feature/enhancement

Implementation of the ability to further control the look of the 'retro terminal effects'. A good place to start would be controlling: 
* Size of 'scan lines'
* How far apart the lines are from each other
* Amount of glow on the text

![Untitled](https://user-images.githubusercontent.com/11434633/198851743-cc3286e3-2a37-49ec-995b-758c7154e2e4.png)

# Proposed technical implementation details (optional)

I am still a Jr. developer and unfortunately do not know much about the code base of this project, if this is something I could work on and learn from, that would be great.

**Comment by zadjii-msft** [comment]
Good news! The retro shader is just a specific example of [custom pixel shaders](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#pixel-shader-effects) for the Terminal. You can feel free to grab the source from [Retro.hlsl](https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Retro.hlsl), and modify it however you'd like!

**Comment by konsoul** [comment]
Very cool! Thank you zadjii-msft!
