### ISSUE TITLE
Unable to find the selected font "JetBrainsMono Nerd Font". "Consolas" has been selected instead.

### ISSUE THREAD

**Issue by EySwag** [microsoft/terminal#14302]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Change the font to jetbrainsmono nerd font.

### Expected Behavior

The font changing

### Actual Behavior

The font doesn't seem to be changing and every time I try to resize the text or save the settings it throws an error window:
![Screenshot_4](https://user-images.githubusercontent.com/54305329/198675419-148dd05b-ae62-4cf6-9a93-457aac43cb19.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Unable+to+find+the+selected+font%22) when filing new issues. This is actually already being tracked by another issue on our repo - please refer to https://github.com/microsoft/terminal/issues/3257 for more discussion.

/dup #3257

See also https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973
