### ISSUE TITLE
Custom fonts don't work

### ISSUE THREAD

**Issue by SeanDorff** [microsoft/terminal#14300]
I've installed a number of custom fonts and assigned them as standard in Windows Terminal Version 1.15.2875.0, installed from the Microsoft Store.

Windows-Terminal doesn't find the fonts after I've rebooted my machine and falls back to "Consolas".

An example font is this: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
It is usable, e.g. in MS Word.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3257 for more discussion.

/dup #3257

See also https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973
