### ISSUE TITLE
Stuck with high CPU

### ISSUE THREAD

**Issue by ShenHongFei** [microsoft/terminal#14309]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.755

### Steps to reproduce

After opening windows terminal and leaving it for a while

### Actual Behavior

![2022 10 30 11 58 04](https://user-images.githubusercontent.com/15074472/198861958-3cda96d5-426b-4a3a-9ab1-8685bc399c92.png)

**Comment by zadjii-msft** [comment]
Is the Terminal _hung_? Or just running at high CPU? Are you running the Terminal in a VM? Do you have a dedicated GPU/?

**Comment by ShenHongFei** [comment]
> Is the Terminal _hung_? Or just running at high CPU? Are you running the Terminal in a VM? Do you have a dedicated GPU/?

Yes, the therminal is hung. I am not running the Terminal in a VM. Yes i have a dedicated GPU Nvidia RTX 3080.

**Comment by lhecker** [comment]
@ShenHongFei Can you try to install the latest Nvidia drivers/?
* Chinese: https://www.nvidia.cn/download/driverResults.aspx/194116/cn/
* English: https://www.nvidia.com/download/driverResults.aspx/194112/en-us/

If that doesn't resolve the issue already, I'd be curious if this issue still happens to you if you use [Windows Terminal Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3) instead.

**Comment by ShenHongFei** [comment]
The driver version used when this issue was raised is the latest 526.47, which should not be a problem with the graphics card driver.
The same problem has not appeared in the past few days. I have been observing for a while, and the issue will be closed first.
When the same problem occurs, I will find a way to reproduce, thank you.
