### ISSUE TITLE
Open administrator shell in the same Windows Terminal session

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [microsoft/terminal#14304]
I don't always need to run  Windows Terminal as admin since I use WSL mostly.
But when I open admin PowerShell session in Windows Terminal, first of all, it shows me a GUI "User account control" window and secondly, it opens a new Windows Terminal session.

Is it possible to implement a feature to start admin shell the way Linux does it with password prompt and without any GUI pop-ups?
is it possible to implement a feature to start admin CMD/PowerShell session in the same non-admin Windows Terminal session?

**Comment by j4james** [comment]
If I've understood you correctly, what you're asking for is know as "mixed elevation" - you've got an unelevated Windows Terminal process from which you want to open an elevated tab. See issue #1032 for an explanation of why that's not supported.

**Comment by zadjii-msft** [comment]
Yep, /dup #1032.
