### ISSUE TITLE
Duplicated tab should be next to original tab

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#14313]
Currently the duplicated tab is added on the far right, IMO it should be next to the original tab.

**Comment by lhecker** [comment]
We have a setting for that! You can find it here:
![image](https://user-images.githubusercontent.com/2256941/199561893-4820d41d-fe35-4461-878b-45e1b3b73ecf.png)

Let me know if I misunderstood you. 🙂

**Comment by OlafvdSpek** [comment]
When was that setting added? My 1.15 doesn't have it.
Also, duplicated tabs should be created next to the one being duplicated, while new tabs should be created after the last tab. How would that work?
