### ISSUE TITLE
Powerline glyph's render incorrectly (sometimes)

### ISSUE THREAD

**Issue by A-Lamia** [microsoft/terminal#1431]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): First Preview version;

Font's used
Fira Code - (Ligature)
FuraCode NF - (Ligature)
Hack
Hack NF
```

# Steps to reproduce

~Happened after PC restart tested out other fonts to see if it would fix and restarted PC again.~

After more testing, this seems to be 2 bugs, the first is setting `"alwaysShowTabs" ` to true will cause Glyphs to break setting it to `false` fixes the issue. this bug only seems to happen if set to `true` on system restarts. It is about a 25% chance of reproducing it this number may change for some.

The Ligatures not rendering properly is only with the [Nerd Font](http://nerdfonts.com/) variant of the ligature fonts, standard versions work fine. This ended up being a separate issue from the one above after more testing.

# Expected behavior
~ligatures and glyph's rendering correctly~

Glyphs should render the same regardless of if  `"alwaysShowTabs"` is set to `true` or `false`.

# Actual behavior

~Glyphs are not connecting and ligatures are not working the first character typed will also be hidden by the triangle glyph.~

Glyphs not rendering correctly and  overlapping characters that come right after.
![Terminals](https://i.imgur.com/aTZRKGk.png?raw=true)

**Comment by DHowett-MSFT** [comment]
> The Ligatures not rendering properly is only with the [Nerd Font](http://nerdfonts.com/) variant of the ligature fonts,

I'm going to go out on a limb and say, "I'm going to go out on a limb and say it's the font."

**Comment by neo-clon** [comment]
Is'nt the font, you can reproduce with this steps
1. Open the terminal with Consolas font
2. Switch the profile font with any on Nerdfont (I try with, meslo, hack and Hasklug)
     (In this moment the terminal and fonts looks awesome)
3. Restart the terminal and see how loss the ligatures

**Comment by MikeBairdRocks** [comment]
Yes this is a bug IMO. Every other terminal I try on windows works with these fonts and wsl. Hyperjs, cmdr, Terminus...etc.

**Comment by zadjii-msft** [comment]
Oh yea those aren't ligatures. Those are _powerline_ characters.

It's curious to me that if you start with consolas, then switch to FuraCode NF it breaks. That's probably a bug.

**Comment by zadjii-msft** [comment]
Wait no this is already #633
