### ISSUE TITLE
Command Palette should include profile names

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#14314]
Ctrl-Shift-P - PowerShell returns "No matching commands". It'd be nice if it allowed you to open a new tab with the profile.

**Comment by zadjii-msft** [comment]
It totally can do this! For clarity, we've nested those commands in the "New Tab..." menu by default. You're totally free to change the structure of your command palette however you'd like! [The docs site ](https://learn.microsoft.com/en-us/windows/terminal/command-palette#iterable-commands)even has an example for how you might gget the structure you're looking for.

**Comment by OlafvdSpek** [comment]
It'd be nice if it did this by default.

**Comment by DHowett** [comment]
I definitely agree with @OlafvdSpek here. There's a disconnect between what the settings model stores for actions (like, they contain a profile index) and how the user thinks about those actions (they act on a profile).

If I may spin a tale for a second to illustrate the counterpoint... if we take the "index is primary" stance to its logical conclusion, Terminal would look like this:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/189190/199577455-c25b4d85-979a-41c8-b6f3-49d880d50b37.png">

**Comment by zadjii-msft** [comment]
There's been some debate about this in the past: [Unified keybindings and commands, and synthesized action names.md](https://github.com/microsoft/terminal/blob/main/doc/specs/%232046%20-%20Unified%20keybindings%20and%20commands,%20and%20synthesized%20action%20names.md#complete-defaults), https://github.com/microsoft/terminal/pull/6532#discussion_r441194248, #7016. Move this discussion to that thread?
