### ISSUE TITLE
Where does it install?

### ISSUE THREAD

**Issue by whyboris** [microsoft/terminal#14311]
🤯 absolutely insane 🤯 

I installed the terminal via [Release](https://github.com/microsoft/terminal/releases/tag/v1.15.2874.0)
- `Microsoft.WindowsTerminal_Win10_1.15.2874.0_8wekyb3d8bbwe.msixbundle`

but I cannot find it in the *Start* menu or anywhere on my computer.

How do I start it again!? Please 😭

**Comment by zadjii-msft** [comment]
Just to be sure - you double clicked the `.msixbundle` and installed it in that little wizard, right?

Does the Terminal show up under "Installed Apps" in the Settings app?

What version of Windows are you running? 

Does `wt.exe` from the Run Dialog (or any console window) work/?

**Comment by whyboris** [comment]
`Terminal` appears in the `Apps & features` in `Settings` ✅ 
It looks today like it _is_ appearing 🤯 - but with a messed up icon :trollface: 
<img width="551" alt="2022-11-01 09_31_57-Greenshot" src="https://user-images.githubusercontent.com/17264277/199245550-5ecc7c4d-5aee-4eb8-828d-2b8d5b4040f5.png">

*Importantly* I need a simple link `.lnk` file to put in another folder for quick access -- but I can't right-click and find it in the start menu.

# Where is the executable so I can link to it?

**Comment by zadjii-msft** [comment]
@whyboris You should be able to make a `lnk` to `wt.exe`, which is an "App Execution Alias" that points at the Terminal. Does that work for you/?

re: the icon - the following is from #14175

> It's a known bug caused by Google Drive unfortunately. See here for instance: [superuser.com/a/1323021](https://superuser.com/a/1323021) (Under "Issue 1: Third-party thumbnail handlers for .png")
> 
> You can find out a lot more about it when you search for "google drive start menu missing icons" or similar on the internet. It's definitely not caused by anything Windows Terminal does.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/199292397-f46dac5d-1d8f-4dda-9b43-8123569d7476.png)

`%localappdata%\Microsoft\WindowsApps\wt.exe`

You can always just add a `lnk` to `wt.exe` itself, no path, and if it's on the `%PATH%` (it should be), then Windows will just figure it out for you

**Comment by whyboris** [comment]
Thank you for resolving _my_ issue, but I suspect there are other people who may be bewildered about where the `terminal` installs. It may take only a single line in your documentation (or download page) but may save some people some trouble.

❤️ Cheers 🙇
