### ISSUE TITLE
wt -v doesn't show correct version number for Preview

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#14335]
### Windows Terminal version

1.16

### Windows build number

10

### Steps to reproduce

wt -v in Terminal Preview

### Expected Behavior

Shows version of Preview

### Actual Behavior

Shows regular version

In hindsight this could be expected, but the bug report template suggest to run wt -v to get the version..

**Comment by zadjii-msft** [comment]
If you've got both Terminal (stable) and Terminal Preview installed, `wt.exe` can unfortunately only point at one of them. Which one is determined by the OS, in the "App execution aliases" page of the settings app:

![image](https://user-images.githubusercontent.com/18356694/199968842-1a952acf-4f82-4964-878f-5fc3c9ec6b9f.png)

I bet that `wt` is set up to point at the Stable one, not the Preview one.

**Comment by OlafvdSpek** [comment]
Sure, so maybe the gh issue template should mention this.
