### ISSUE TITLE
Settings to change "popup text" and "popup background" on CMD profiles

### ISSUE THREAD

**Issue by ElNico56** [microsoft/terminal#14333]
# Description of the new feature/enhancement

Just some options on the color scheme tab to change the colors of popup text and popup background (like you can on the regular cmd), to make it clear i'm reffering to the color scheme of the window that appears when pressing F7 to view command history
![image](https://user-images.githubusercontent.com/18220871/199911546-8373a2b9-f80f-4968-b2ee-5d8d84f47e62.png)

**Comment by zadjii-msft** [comment]
So, this has come up in the past: /dup #7449

> Thanks for the request! This one we're probably not going to do. The popup code that CMD is using (which is unfortunately shared between cmd, python, powershell-without-psreadline, cdb, and every other traditional console application) is not something we're willing to change right now.
> 
> It's possible to set the colors using the SetConsoleScreenInformation API, however. A small application could be put together that allows for this customization, but it's going to have to come from somebody else.
> 
> Part of the issue is that it will never be able to support the rich color sequences that terminals written after 2005 tend to support. It's a legacy fixture, and we're going to have to treat it like one.

**Comment by khaled7172** [comment]
Hello,can you guys please tell me what was the initial setting for the popup text and popup background i played around with it a while back and now it's ruined
