### ISSUE TITLE
Last line of WSL console duplicated on horizontal resize

### ISSUE THREAD

**Issue by carlreinke** [microsoft/terminal#1433]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version: 0.2.1715
```

# Steps to reproduce

1. Open WSL tab.
1. Press enter until prompt/cursor are on last line.
1. Resize the window to be narrower.

# Actual behavior

![image](https://user-images.githubusercontent.com/11667451/59968266-33975e80-94f4-11e9-9bec-6e87de332c15.png)

![image](https://user-images.githubusercontent.com/11667451/59968272-49a51f00-94f4-11e9-84c1-41d26bfede48.png)

**Comment by JushBJJ** [comment]
I was able to reproduce.

**Comment by DHowett-MSFT** [comment]
Using #1465 as the master resizing issue.

**Comment by XsongyangX** [comment]
I am experiencing this problem right now. This seems to be WSL specific. The Windows Prompt that runs on Batch has no problem when resizing the window.

My version info:
```
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1413
```
![image](https://user-images.githubusercontent.com/10444460/228987159-d6e05eee-8bf5-43d7-90ff-c12957914b4d.png)
![image](https://user-images.githubusercontent.com/10444460/228987222-c1b142bd-6f7d-4b11-99b0-5c0cb3e1aac2.png)
