### ISSUE TITLE
Tab width doesn't revert to normal after closing tabs

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/terminal#14334]
### Windows Terminal version

1.16.2641

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Open a lot of tabs
2. Close all but two with keyboard shortcut

### Expected Behavior

Tab width reverts to normal.

### Actual Behavior

Tab width only reverts to normal on mouse over / mouse leaving.

![image](https://user-images.githubusercontent.com/2218936/199922213-03092115-0935-4292-ae56-312c67e438cd.png)

![image](https://user-images.githubusercontent.com/2218936/199922263-8c6662bd-c9c9-4bef-bc68-0e5c80e06f61.png)

**Comment by zadjii-msft** [comment]
How exactly did you close the tabs/? With the mouse (clicking on the 'X' or by middle-clicking)? By using a keyboard shortcut?

We've seen a few of these in the past that all rolled up to some WinUI bug...

**Comment by OlafvdSpek** [comment]
`Ctrl-Shift-W`

**Comment by zadjii-msft** [comment]
Yep, /dup #9822
