### ISSUE TITLE
Cannot copy content from GDB output window when in TUI mode running in Windows terminal

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/terminal#14336]
### Windows build number

10.0.22621.674

### Other Software

GDB 11

### Steps to reproduce

1. In Windows terminal, launch either WSL2 or connect to a remote Linux via ssh.
2. Install GDB and use it to debug an app.
3. Switch to TUI mode (`Ctrl-x a`).
4. Try to copy any text from the Window.

### Expected Behavior

I can use mouse to select text and copy it via `ctrl+c`.

### Actual Behavior

Cannot select any text and copy it to clipboard.

**Comment by zadjii-msft** [comment]
Can you select text when you hold shift and use the mouse to select text/? Sounds to me like gdb's TUI mode enabled mouse mode.

**Comment by ThomsonTan** [comment]
> Can you select text when you hold shift and use the mouse to select text/? Sounds to me like gdb's TUI mode enabled mouse mode.

I can select text w/ shift pressed, thanks! Is there other way to configure Windows terminal to disable this mouse mode to avoid pressing `shift`?

**Comment by zadjii-msft** [comment]
> Is there other way to configure Windows terminal to disable this mouse mode

I think we're tracking that in #4875

**Comment by DHowett** [comment]
> MobaXterm

This repository is for Windows Terminal. We cannot help with the MobaXterm terminal. Please contact the creators of that software.
