### ISSUE TITLE
`useAcrylic` messes bg color

### ISSUE THREAD

**Issue by ebarzilay-godaddy** [microsoft/terminal#14332]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Using "opacity": 100`, `"useAcrylic": false` with a black bg color, gets a grayish bg color which is way too light to be considered black.

I've seen #13986 and #603, but this is different from both: I *like* the acrylic option with some blurred opacity, but it's just making the background too bright right now.

### Expected Behavior

Some gray is expected, of course, but should be much closer to the black background color that I use.

### Actual Behavior

I get this background, which is close to `#222222`:

![image](https://user-images.githubusercontent.com/111393923/199846057-822be1bf-080d-4448-8afd-59b5a5c30bae.png)

This is with full opacity and shown on a black window behind it just to minimize color leaking.

**Comment by DHowett** [comment]
Thanks for the report!

Interesting that this happens with `"useAcrylic": false`... that should absolutely disable the acrylic material.

I wonder if this was solved by #14193. It sounds pretty darn similar...

**Comment by DHowett** [comment]
@zadjii-msft does this seem the same to you?

**Comment by zadjii-msft** [comment]
I'd reckon this is the same thing as #12880... That should ship in 1.17. If that doesn't fix this, we can always reopen. 

/dup #12880
