### ISSUE TITLE
Ctrl key can be stuck in Windows Terminal

### ISSUE THREAD

**Issue by devlie** [microsoft/terminal#14343]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.25231.1000

### Steps to reproduce

I don't have concrete repro steps. I'm just using running cmd.exe inside Windows Terminal Preview as usual.

### Expected Behavior

`Ctrl` key is not stuck.

### Actual Behavior

After some times, `Ctrl` key will be stuck for a particular tab. I usually find out when hitting `Backspace` would delete the whole word even though I'm not pressing down `Ctrl` key, or typing some alphabets would produce something like `^A`

I'm positive the problem is scoped to a Terminal tab:
* If I open a new tab, the issue doesn't persist.
* The problem doesn't repro on Windows Run dialog (WIN+R) while issue is happening.

**Comment by lhecker** [comment]
Wow that sounds eerily similar to #14338, which was submitted just hours ago.

**Comment by zadjii-msft** [comment]
I'm gonna go out on a limb and guess that this is the same root cause as #14345. We'll tentatively call this a dupe for now, push out a hotfix, and if that release doesn't fix this, we can reopen. Thanks!

/dup #14129

**Comment by devlie** [comment]
@zadjii-msft I'm still reproing this issue on WT Preview 1.17.1023. That build should have the fix for this issue, right?
