### ISSUE TITLE
Extra characters come along with a paste

### ISSUE THREAD

**Issue by szalapski** [microsoft/terminal#14340]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2130

### Other Software

ohmyposh
Powershell Core 7.2.6

### Steps to reproduce

1. I wrote a C# .NET 6 self-hosted web app that accepts interactive input from a `Console.ReadLine();` statement.  I run the app in Windows Terminal via Powershell Core.
2. When I come to that prompt, I paste in any string copied from notepad, such as `foo`

### Expected Behavior

It should paste exactly what was copied; in this example, `foo`.

### Actual Behavior

I notice that something has prepended and appended other characters in what I have pasted.  If I copy `foo` out of notepad and paste in Windows Terminal, I get `00~foo01~` actually pasted, which causes problems unless I manually fix it.

This only happens when running inside my web app **host** in **Windows Terminal** via **Powershell** Core.

- When I paste in Windows Terminal at a powershell prompt outside of this app, it does not happen (pastes `foo` properly).
- When I run this app in Windows Terminal via Command Prompt it does not happen (pastes `foo` properly). 
- When I run this app in Powershell in Windows outside of Windows Terminal, it doesn't happen (pastes `foo` properly).

**Comment by zadjii-msft** [comment]
Which powershell, PsReadline, and oh-my-posh version are you using/? This has all the same flavors of #14129 (et al), though it does rule out `ssh` as the source of the regression

**Comment by szalapski** [comment]
Powershell Core  7.2.6

What is PsReadline?  I don't think I am using that, as I am using a C# Kestrel-based web host here.

How do I get the version of oh-my-posh that I am using?

**Comment by zadjii-msft** [comment]
Hmm, I'm guessing this wasn't oh-my-posh: https://github.com/JanDeDobbeleer/oh-my-posh/issues?q=is%3Aissue+bracketed

I should probably just redirect this to /dup #14129
