### ISSUE TITLE
Font resize breaks selection

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#1434]
Commit ce4c6d61

When Ctrl+Mouse wheel, selected span changes. This seems related to #1368, but is different in that when returning to previous size, selection is invalid.

**Comment by Karl-WE** [comment]
repro:
select text in windows terminal
agree using ctrl+mousewheel up and down to resize text (it does likely happen if you scale it by more than 3 pt)
either selection moves up or it got deselected.

deselection happens more often than the selection move. it also depends whether you make multiline selection starting in the middle or from the top of the text or if you just make partly multiline selection that do not start from char 1 in a line.
hope this helps.

**Comment by DHowett-MSFT** [comment]
We should just tackle this as part of #1368.
