### ISSUE TITLE
"Open in Terminal" to start in existing terminal instances by default?

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#14347]
Right now, it always spawns a new Terminal instance / window which can be a tad slower than just spawning a new tab in existing instance. This can be compared as opening an HTML file from disk which usually would open it in existing Chrome instances and just open a new tab.

Propose to have a discussion to have the same behavior for Terminal by default (great that an option already exists in the config though! thanks to @237dmitry for pointing it out!)

**Comment by 237dmitry** [comment]
This option already [exists](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup)
```
"windowingBehavior": "useAnyExisting"
```

**Comment by vadimkantorov** [comment]
thank you! great to know! i'll then repurpose this issue to propose to make it default

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Until we've got tab tear-out sorted out, I've been reluctant to change any defaults to `useExisting`. That would just make the windows glom together and now you'd be stuck without it being able to tear into it's own window. Trust when I say, when tear-out is ready for stable releases, we'll be changing the default to `useExisting`. 

There's also /dup #7071 for adding a separate setting to control the shell context menu's behavior separate from the globals, but that's quite a bit farther out.

**Comment by vadimkantorov** [comment]
One nuance, in Chrome it would use last active window for opening disk files, not just "any existing window"

**Comment by zadjii-msft** [comment]
> One nuance, in Chrome it would use last active window for opening disk files, not just "any existing window"

That's literally exactly what [`useExisting`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#new-instance-behavior) does
