### ISSUE TITLE
Support moving terminal windows launched in "focus" mode freely

### ISSUE THREAD

**Issue by vkoukis** [microsoft/terminal#14351]
# Description of the new feature/enhancement

Provide a way to move a terminal window launched in "focus" mode, even though no there's no UI element to grab.
"Focus" mode is awesome because it allows the user to focus on the terminal, and nothing else.
But it's difficult to rearrange windows when using this mode.

Suggestion: Support moving with Win+click-drag anywhere on the terminal.
This would allow combining with existing PowerToys FancyZones functionality.

There has already been a similar request in the past, https://github.com/microsoft/terminal/issues/8540.
I understand it's possible to move the window around predefined locations using Win+arrow keys, but this lacks in interactivity, for example it's not possible to choose multiple zones dynamically using Shift + Ctrl when moving the window, like FancyZones supports.

**Workaround:**
Define a shortcut for the existing "Toggle focus mode" command [e.g., Ctrl-Shift-F12], to quickly drop out of focus mode, move the window around using the now-visible title bar, then re-enter focus mode, but it's a bit cumbersome.

# Proposed technical implementation details (optional)

One possible way to make this happen is treat the whole terminal itself as the UI element to grab on to when moving the window, combined with a modifier key. E.g., support Win+click-drag to move the window around in focus mode.

**Comment by 237dmitry** [comment]
`alt-space, m` is also workaround

**Comment by vkoukis** [comment]
> `alt-space, m` is also workaround

@237dmitry yes, thank you, this is one more workaround. It's a bit cumbersome because you have to use the arrow keys to move the window around. It definitely works when you need an off-screen window back into the screen, but it's not the natural thing to do when you need to move windows during your daily work.

**Comment by 237dmitry** [comment]
> but it's not the natural thing to do when you need to move windows during your daily work.

I agree, in my opinion, it would be nice to move the window, as it is done in Linux. `Alt+LeftMouseButton` in any point of window.

**Comment by zadjii-msft** [comment]
FWIW, if you <kbd>alt+space</kbd>, <kbd>m</kbd>, then tap any arrow key, you can start moving the window with the mouse. Again, a cumbersome keybinding, but better than using solely the arrow keys. 

I think this more or less boils down to #539, yea/? We cool if I close this as a dupe?

**Comment by vkoukis** [comment]
> I think this more or less boils down to #539, yea/? We cool if I close this as a dupe?

@zadjii-msft true! this is a dupe of #539, solving #539 will make using windows in "focus" mode much more useful, let's close this.

I hope #539 will get some love soon, it's funny it has a 3-digit issue number 🙂

**Comment by sfwnsft** [comment]
Thanks for the alt-space + m shortcut!
