### ISSUE TITLE
Add sub context menu to windows terminal context menu selection

### ISSUE THREAD

**Issue by johntws** [microsoft/terminal#14357]
# Description of the new feature/enhancement
Would it be possible to make the terminal selection in the context menu open a sub context menu containing my other terminal profiles? e.g. powershell, cmd, ubuntu, ssh, etc...

Currently the process is abit long-winded:
1. open with terminal (context menu)
2. open the profile that I wanted
3. cd into directory

![image](https://user-images.githubusercontent.com/58924021/200760322-9477001e-c317-4961-905a-84502886bf72.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6111 for more discussion.

/dup #6111
