### ISSUE TITLE
[Feature] Show current directory content in a UI panel above the terminal

### ISSUE THREAD

**Issue by rrmistry** [microsoft/terminal#14354]
# Description of the new feature/enhancement

As a user of Windows Terminal, I often need to change directory and then immediately list contents of this directory. It would be helpful if the Windows Terminal could display current directory contents upon changing current folder, and list contents in a user interface panel just above the terminal.

A good use-case is navigating a directory that you are not familiar with or have not visited in some time.

## Known Workarounds:

For PowerShell, this can be automated using an [`Alias`](https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/using-aliases?view=powershell-7.2), but it would be good to have this functionality out of box if possible. This would cover a generalized use-case for all terminal / shell types.

# Proposed technical implementation details (optional)

A very helpful implementation of this exists for Azure App Service Tools (Kudu) shown below:

![Terminal_With_Folder_Preview](https://user-images.githubusercontent.com/25514145/200608742-3b8cefc8-b387-4489-912b-0056413ed1ce.gif)

## Future Enhancements

It would be helpful to sort directory contents by default using user-defined sorting methods. For example: `DateModified Ascending/Descending`, `Name`, `Type`, `Extension`, etc.

**Comment by rrmistry** [comment]
> Great suggestion! I suspect this is the same as #5591, yea? I kinda co-opted that thread to mean "explorer in Terminal" since "terminal in explorer" was kinda impossible

Agree completely. Would be an easier implement explorer in this product (Windows Terminal) instead of having a dependency on another product (Windows Explorer)

I'm ok to mark this as a duplicate if needed. Just wanted to share the idea.

Thanks!

**Comment by zadjii-msft** [comment]
/dup #5591

thanks!

**Comment by 237dmitry** [comment]
It looks terrible.

**Comment by zadjii-msft** [comment]
![](https://media.tenor.com/CkASCfIfaWIAAAAd/the-dude-yeah-well-you-know-thats-just-like-your-opinion-man.gif)
😜 

I can totally see how it'd be useful to have a sidebar that automatically populates with the CWD's contents (for some version of that being possible)
