### ISSUE TITLE
Provide a setting to prevent the terminal from losing the cursor

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#14362]
# Description of the new feature/enhancement

There seems to be some escape sequence that may cause the cursor to be hidden.  I would like an option to ensure that does not happen

# Proposed technical implementation details (optional)

On Settings under default have a setting that goes

* prevent console from changing the cursor

**Comment by zadjii-msft** [comment]
Which shell/app (`vim`, `pwsh`, `bash`, `emacs`, etc) are you using/? That's usually something that's controlled by the client application.

**Comment by trajano** [comment]
just bash, sometimes it loses the cursor when I do `yarn build` where the cursor just moves around (and I press Ctrl-C to stop it) and the cursor sometimes disappears
It's quite random.

**Comment by zadjii-msft** [comment]
This might be #1379

**Comment by carlos-zamora** [comment]
Thanks for the request! We're gonna track this in /dup #1379.
