### ISSUE TITLE
Cygwin zsh freezes on resize (Cygwin bash is fine)

### ISSUE THREAD

**Issue by Slapbox** [microsoft/terminal#14363]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.0

### Other Software

Cygwin zsh instance inside Windows Terminal.  Every other shell seems to work fine.

### Steps to reproduce

Run a Cygwin zsh instance inside of Windows Terminal, then resize the window.

### Expected Behavior

Input can continue

### Actual Behavior

Terminal is frozen and useless. New terminal must be opened.

**Comment by Slapbox** [comment]
I found that this appears to be caused by using Git For Windows instead of the Cygwin Git. Quite unexpected. https://github.com/msys2/MSYS2-packages/issues/2820

I'm not sure if this should be opened or closed now.

**Comment by j4james** [comment]
I think this is the same issue that was reported in #13819. And the people in that thread also seemed to think it was a problem in Git For Windows, or at least the `less` pager that git is using.

**Comment by ixxiv** [comment]
Hey, @Slapbox. How were you able to map zsh to bash?

**Comment by Slapbox** [comment]
@ixxiv instead of running from `cygwin.bat`, create a `cygwin.zsh.bat` with the contents below, and run that instead:

```
@echo off
setlocal enableextensions
set TERM=
cd /d "%~dp0bin" && .\zsh --login -i
```

I'm working on a project to one-click install Zsh to Windows Terminal but it will be a few weeks before it's ready, optimistically.

**Comment by ixxiv** [comment]
@Slapbox, please let me know when the project is ready. Thank you.
