### ISSUE TITLE
Buffer exports only contain spaces

### ISSUE THREAD

**Issue by ianjoneill** [microsoft/terminal#14378]
### Windows Terminal version

main - a01500f

### Windows build number

10.0.22621.819

### Steps to reproduce

Open a PowerShell tab, right click on the tab and select Export Text.

### Expected Behavior

The tab content to be exported to a file.

### Actual Behavior

Lots of spaces are exported instead.

**Comment by 237dmitry** [comment]
The only problem I have when exporting text that contains a tab is its incorrect formatting, shifting each next line to the right of the previous one if the tab is running an application with TUI. Command shells, pwsh, cmd, are exported without errors.
