### ISSUE TITLE
Terminal keeps disappearing when laptop sleeps

### ISSUE THREAD

**Issue by AravindhKumarSivaramakrishnan** [microsoft/terminal#14377]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.1098

### Steps to reproduce

Open terminal and let the computer to sleep off and once woken up, the terminal will vanish.
Same behavior with battery and charger connected. 

Note: This issue has started with the recent windows update.

### Expected Behavior

Terminal should persist the state and behavior and not get closed.

### Actual Behavior

Terminal seems to be missing/vanished, process seems to be running sometime (few mins even when the Terminal is missing) in background but eventually stops in some time.

**Comment by lhecker** [comment]
Does the terminal disappear every single time you sleep or only sometimes? Does your device need to sleep for a long time for the terminal to disappear?

**Comment by zadjii-msft** [comment]
Do you see any events in Event Viewer ala "‎The power manager has not requested the deletion of all entries‎" / "‎The power manager has requested the deletion of all entries‎"/?

See also #12513.

Can you try setting [`"closeOnExit": "never"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior) in the settings? Maybe `pwsh.exe` is crashing, exiting, causing the Terminal to "crash".

It's also possible that the Store may have noticed that there was an update available for the Terminal, and chose to update it for you right as it was going to sleep / resuming from sleep. If this happens literally every sleep, then we can probably rule this out.

**Comment by AravindhKumarSivaramakrishnan** [comment]
> Does the terminal disappear every single time you sleep or only sometimes? Does your device need to sleep for a long time for the terminal to disappear?

It only happens when the sleep is longer then 4 to 5 mins, few mins in sleep does not kill the terminal

**Comment by AravindhKumarSivaramakrishnan** [comment]
> Do you see any events in Event Viewer ala "‎The power manager has not requested the deletion of all entries‎" / "‎The power manager has requested the deletion of all entries‎"/?
> 
> See also #12513.
> 
> Can you try setting [`"closeOnExit": "never"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior) in the settings? Maybe `pwsh.exe` is crashing, exiting, causing the Terminal to "crash".
> 
> It's also possible that the Store may have noticed that there was an update available for the Terminal, and chose to update it for you right as it was going to sleep / resuming from sleep. If this happens literally every sleep, then we can probably rule this out.

Tried `"closeOnExit": "never"`, there is no change in the behavior and also there is no update to Terminal available in store and the issue literally happens for every sleep but only when a process is running (let's say you run an angular app or any process that runs longer). When the terminal is open without any process running, it seems to remain alive. 

Checked the Event Logs, nothing related to Terminal or power manager.

**Comment by carlos-zamora** [comment]
We'd love to get some additional information. Would you mind filing this in feedback hub?

/feedback
