### ISSUE TITLE
font size setting doesn't affect all apps

### ISSUE THREAD

**Issue by gyorokpeter** [microsoft/terminal#14370]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Other Software

N/A

### Steps to reproduce

Go to settings -> Command Prompt -> Appearance, change Font size e.g. to 10 (from the default of 12)
Launch various console apps

### Expected Behavior

The font size setting should apply to *all* apps.

### Actual Behavior

The font size setting is selectively applied to various apps, with no way to change it for the apps where it doesn't work.
One thing that might be relevant that in apps where it doesn't work, the tab icon looks like a box showing `C:\` on a white background, while in apps where it does, the icon has `C:\_` (there is an extra underscore) and on a _black_ background.

**Comment by gyorokpeter** [comment]
Further experimentation reveals that the reason the font size setting doesn't work in all apps is that some are launched using the "Command Prompt" profile, while others are launched using the "Default" profile. Changing both is a workaround for now, but it still leaves open the question why there is a discrepancy in which profile is used.
It seems that "Command Prompt" gets used for batch files and "Default" for binaries. For me there is little functional difference between the two - I launch them from shortcuts anyway, and I try to make shortcuts with enough command line parameters if possible, and switch to using a batch file when that stops being enough, e.g. if changing PATH is necessary. However then it's still the same app, it just has a wrapper script around it, so from the user perspective it makes little sense to use a different profile for the two.

**Comment by 237dmitry** [comment]
I could not reproduce this issue on the latest `Preview`


https://user-images.githubusercontent.com/78153320/201370857-5ea008c7-afd3-4a36-8439-45814073f236.mp4

**Comment by zadjii-msft** [comment]
Yea, this is also by design. The Terminal attempts to "match" the commandline application to one of your existing profiles, when determining what settings to use. If it can't find a match, then it'll just use the "defaults" profile for that application's settings. 

When you change the settings for "Command Prompt", it's only going to change the settings for `cmd.exe` launches.
