### ISSUE TITLE
Windows Terminal session restore is not remembering the last directory that was set in each tab

### ISSUE THREAD

**Issue by cyclr-adrian** [microsoft/terminal#14386]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.0

### Other Software

I did have Oh-My-Posh module loading in via PowerShell profile, but I have since commented out that module from loading and running to eliminate it from this issue.

#### Pre-Requisites
In your  Windows Terminal Settings page set the following:
1. `Settings` => `Startup` => `When Terminal Starts` set value to `Open windows from previous session`.
2. The PowerShell profile you are using has a `startingDirectory` set e.g. `"startingDirectory": "%USERPROFILE%"`

#### Steps
1. Load 2 PowerShell tabs in Windows Terminal
3. Rename the tabs `Tab 1` and `Tab 2`
4. In `Tab 2` change the directory so that it is different to the directory in `Tab 1`.
5. Close Windows Terminal
6. Re-Open Windows Terminal

### Expected Behavior

When Re-Opening Windows Terminal `Tab 1` and `Tab 2` are restored with their tab names (`Tab 1` and `Tab 2`) plus the initial directory in each tab is the same as it was when the previous Windows Terminal session was closed.

### Actual Behavior

When Re-Opening Windows Terminal `Tab 1` and `Tab 2` are restored with their tab names (`Tab 1` and `Tab 2`) however the initial directory in each tab is NOT the same as it was when the previous Windows Terminal session was closed, but tabs appear to have the same directory set.

I have tried changing the `startingDirectory` for the profile I was using from `"startingDirectory": "%USERPROFILE%"` to `"startingDirectory": null` but it makes no difference.

**Comment by zadjii-msft** [comment]
Did you make sure you've actually configured your shell to tell the Terminal what the CWD is?

Refer to: [Opening a tab or pane in the same directory in Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

**Comment by cyclr-adrian** [comment]
I've just tried coping in the `prompt` function from [powershell-with-posh-git](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory#powershell-with-posh-git) to configure `CWD` on PowerShell with posh-git.

This does and doesn't work for my scenario.  It works to remember the previous `CWD` for each tab when `startingDirectory ` is set to `null`.

I am also using oh-my-posh to format the PowerShell prompt on top of posh-git and with the `prompt` function in my PowerShell profile I lose all of my oh-my-posh look and feel.

**Comment by cyclr-adrian** [comment]
I think I have it working now with oh-my-posh too.

I've set the `startingDirectory` to null and added `"pwd": "osc99"` to my on-my-posh config as stated [here](https://ohmyposh.dev/docs/configuration/overview#general-settings)

**Comment by tommai78101** [comment]
> I've set the `startingDirectory` to null and added `"pwd": "osc99"` to my on-my-posh config as stated [here](https://ohmyposh.dev/docs/configuration/overview#general-settings)

The link is down. Do you happen to have an alternate mirror?

**Comment by A7r-S6s** [comment]
> > I've set the `startingDirectory` to null and added `"pwd": "osc99"` to my on-my-posh config as stated [here](https://ohmyposh.dev/docs/configuration/overview#general-settings)
> 
> The link is down. Do you happen to have an alternate mirror?

The new link (as of now) to the Oh My Posh docs is https://ohmyposh.dev/docs/configuration/general#settings
"pwd" is among the settings parameters described there.

Add `"pwd": "osc99"` to your theme JSON and you're good to go.

For me it works like a charm.
