### ISSUE TITLE
Problems with displaying console-graphical apps that print certain characters

### ISSUE THREAD

**Issue by gyorokpeter** [microsoft/terminal#14383]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22621.819

### Other Software

FAR Manager

### Steps to reproduce

Start FAR Manager, select a binary file and press F3 to view it

### Expected Behavior

The screen should look "normal" even though the contents of the file are not human-readable:
![image](https://user-images.githubusercontent.com/1097079/201526969-d1b930f8-8476-4844-8d7b-58742607a19a.png)

### Actual Behavior

The screen is corrupted with the panel screen still showing through where it shouldn't:
![image](https://user-images.githubusercontent.com/1097079/201526985-b432a6c4-2cc3-42b0-866f-cd4f64f7aa12.png)

**Comment by 237dmitry** [comment]
In my case there are no problems

Win 11 22H2
Far Manager, version 3.0.6051.0 x64
WT 1.16.2642.0

F3:
![Screenshot 2022-11-13 181005](https://user-images.githubusercontent.com/78153320/201529542-596bbb08-7bf1-4d3a-897e-8f059082ed21.png)

Install latest Far. "The Far team" did much to adapt Far for Windows Terminal. I udate it very often by [this link](https://www.farmanager.com/nightly/update3.php?p=64) (replacing the last segment of `uri` with `arc` value)
