### ISSUE TITLE
Terminal loses custom font after PC restart

### ISSUE THREAD

**Issue by onsamyj** [microsoft/terminal#14382]
### Windows Terminal version

7.3.0

### Windows build number

22000.1219

### Steps to reproduce

Install custom font (typeface), for example "SauceCodePro Nerd Font Mono" (for use with Oh My Posh).
Set it as default in Terminal settings.
Everything works fine.

Restart the PC.
Terminal throws up an error message:

> Warning
> Unable to find the selected font "SauceCodePro Nerd Font Mono".
> "Consolas" has been selected instead.
> Please either install the missing font or choose another one.

Reinstall the font, everything works fine until the next reboot.

Same bug on two 22H1 laptops. Not sure if it is specifically a Terminal problem, but other apps, like WordPad, see the font fine. It was also fine in 21H2.

### Expected Behavior

Custom font is working after reboot.

### Actual Behavior

Error message.

**Comment by zadjii-msft** [comment]
Did you install the font for all users?

\<aside for the team>: Is there any way for us to detect if a font is only installed for the current user when the user picks it? So we can flash a InfoBar or something at them? Or at the very least, we need to update the help text for that warning, because we've gotten like five of these bugs reports in the last week.

**Comment by onsamyj** [comment]
Installing for all users fixed it. Thanks.

Behavior changed between 21H2 and 22H2? Then yes, you need a warning of some kind.

**Comment by zadjii-msft** [comment]
> Behavior changed between 21H2 and 22H2? 

By all accounts, it _shouldn't have_. We'll have to go darken some doorways and find out what happened.

**Comment by onsamyj** [comment]
Hm. Not sure that I can be of a help with that, but to be clear:
On 21H1 installing font for _a user_ works fine, even after reboot.
On 22H2 installing font for _a user_ also works, but only until reboot.
Installing font for _all users_ works fine for both 21H1 and 22H1.
