### ISSUE TITLE
Add prefix key for keybindings of Windows Terminal actions

### ISSUE THREAD

**Issue by leonasdev** [microsoft/terminal#14387]
# Description of the new feature/enhancement

Windows Terminal currently cannot set a **prefix key** (like tmux's `Ctrl+b`) that can trigger **actions**. In this case, terminal keystrokes may conflict with keystrokes from other applications inside the terminal.

Use case:
The user wants to move focus right by using the following keystrokes: Press `Ctrl+b` then press `}`.
# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1334 for more discussion.

/dup #1334
