### ISSUE TITLE
Alt-Space suppressed when Settings is the only tab

### ISSUE THREAD

**Issue by danmoseley** [microsoft/terminal#14397]
### Windows Terminal version

1.15.2875.0

### Windows build number

22621.819

### Steps to reproduce

Open settings and close all other tabs.
Close and reopen terminal (now settings should be the only tab)
Type Alt-Space

### Expected Behavior

The alt-space menu, which includes eg Close

### Actual Behavior

Nothing. When settings is the only tab on startup, alt-space seems to be ignored.

This is a fairly minor bug, except it's the quickest way to close the settings and terminal with the keyboard. The only other way I know is Alt-F4. And of cousre, the menu is useful for other things like moving with the keyboard.

When settings is not the only tab open, alt-space seems to (mostly?) work. And it works on other tabs.

**Comment by DHowett** [comment]
Thanks for the report! I think we actually fixed this in #14221, which should be in a coming servicing release.

/dup #14217

**Comment by DHowett** [comment]
Oh, I meant #11970. I'm sorry.

**Comment by DHowett** [comment]
Curious that it still repros for you...

**Comment by zadjii-msft** [comment]
> is the only tab 

is apparently doing a lot of work in this post

**Comment by zadjii-msft** [comment]
Oh I see. THIS IS WEIRD.

If an element in the SUI has focus, then this doesn't repro. Actually, this doesn't repro if _any_ element has focus. But in the specific case where you open the SUI, then close a terminal tab, then the focus is _somewhere_ where alt+space isn't hooked up.

**Comment by serd2011** [comment]
I also have a default profile open when I press alt+space after closing the tab and click on the titlebar.
https://user-images.githubusercontent.com/45919738/213252168-05a796c4-326b-4c81-95e3-0ac5c64411f4.mp4

**Comment by jamespack** [comment]
You can repro this by clicking in one of the two red lined areas. 

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/2086722/231022086-374d6d7b-4799-4f44-b153-f2ba7ea1a444.png">

**Comment by jamespack** [comment]
Scatch that.. Just the bottom area.

**Comment by jamespack** [comment]
for keyboard folks tabbing focus to anything on the page makes that key combo work
