### ISSUE TITLE
Use UAX#29 word boundary rules for selections by default

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#14392]
# Description of the new feature/enhancement

Source: https://github.com/microsoft/terminal/issues/14374#issuecomment-1315297524

> [...] I think I just now realized how "crazy" those ASCII word delimiters are in an international setting. For instance this:
> > ねこはかわいい。
> 
> It consists of 3 words and a delimiter (ねこ , は , かわいい ,  。) and your browser probably handles this correctly, whereas terminals are perpetually stuck in the "What do you mean there are people who don't speak English?". conhost's whitespace-only splitting doesn't feel any better in that regard. I feel like terminals are in a dire need of some [UAX #29, Section 4](https://unicode.org/reports/tr29/#Word_Boundaries).

# Proposed technical implementation details (optional)

* Use this by default: https://unicode.org/reports/tr29/#Word_Boundaries
* Use character-set splitting, if the user has configured `wordDelimiters`

**Comment by zadjii-msft** [comment]
#3077?

**Comment by lhecker** [comment]
Should we close this issue in favor of #3077 then? If we do that, I'd probably edit #3077 to include more specific references to UAX#29 in the title and description.

**Comment by zadjii-msft** [comment]
Moved a bunch of this to /dup #3077
