### ISSUE TITLE
Terminal takes 3.5s to load user data and be functional 

### ISSUE THREAD

**Issue by omonimus1** [microsoft/terminal#14409]
### Windows build number

 Win32NT  10.0.25236.0 Microsoft Windows NT 10.0.25236.0

### Steps to reproduce

Open your terminal
Few characteristics:
* I have a professional (work account) added into my system
<img width="372" alt="image" src="https://user-images.githubusercontent.com/23085146/202777721-d80423dd-d681-4c2e-8828-768769281f9b.png">

### Expected Behavior

Be usable within reasonable time, like any other useful terminal, with a loading time at least under 250ms. 

### Actual Behavior

It takes ALWAYS more than 2 seconds to be ready.

**Comment by DHowett** [comment]
It looks like this message is coming from PowerShell. If you switch your "Default Profile" to "Command Prompt," do you see the same delay?

**Comment by omonimus1** [comment]
Switching to Windows Console Host solves the loading time issue;
[https://support.microsoft.com/en-us/windows/command-prompt-and-windows-powershell-for-windows-11-6453ce98-da91-476f-8651-5c14d5777c20](https://support.microsoft.com/en-us/windows/command-prompt-and-windows-powershell-for-windows-11-6453ce98-da91-476f-8651-5c14d5777c20)
<img width="334" alt="image" src="https://user-images.githubusercontent.com/23085146/202840270-9bb0ebe3-eae7-4dc0-8a6a-54dc4546fb03.png">

**Comment by DHowett** [comment]
At the risk of sounding like a form letter...

You are reporting a message that came from PowerShell. If you change your **Default Profile** to **Command Prompt**, are you seeing the same delay?

If not: this is an issue with PowerShell.

If so: that is surprising, because Command Prompt does not produce a message indicating its startup duration.

**Comment by omonimus1** [comment]
@DHowett by changing the Default Profile to Command Prompt, I DO NOT see the same delay (as shown in the previous message);
Anyway, changing the default profile by the developer settings is a temporary fix, as I have restarted my machine, and the CMD started again to show the same delay. 

Could be also a bug from window settings side? 
How to replicate:
1. Go to privacy and security 
2. Click on 'For developers'
3. Set window console to: Windows terminal (this will produce the delay)
4. GO back to the same settings and set instead Windows Console host (**this will remove the delay**)
5. Restart your machine, and start-up delay message will appear again in your cmd.

**Comment by zadjii-msft** [comment]
Ah see, I think there's still a little miscommunication. There's two axes at play here:

* The default terminal ("Windows Console Host" (`conhost`) vs "Windows Terminal")
* The shell being launched (`cmd`, `powershell`, `pwsh`, `wsl`, whatever.)


PowerShell is the _shell_ that prints out that "loading profiles took forever" message. PowerShell consistently starts slower than CMD.

Then there's the Terminal vs conhost. Conhost definitely starts faster than Terminal, but typically not more than a few hundred ms. Terminal and conhost don't care which application is run inside them. Notably, however, if you just run the Terminal directly, it'll default to some version of PowerShell. This can be changed in the Terminal settings. 

Does that make more sense?
