### ISSUE TITLE
Modernize help dialog opened after typing wt -v in terminal

### ISSUE THREAD

**Issue by ElitePheonix2009** [microsoft/terminal#14406]
# Description of the new feature/enhancement

 The help dialog which opens when typing wt -v in terminal right now is looking very old stylish (not modern). It should be made modern so that it looks nice.

# Proposed technical implementation details (optional)

 
1) Support acrylic.
2) Use better themes, fonts, etc.
3) Support rounded corners (if possible).
4) Support dark theme.
How it looks right now -

![image](https://user-images.githubusercontent.com/114980232/202717143-b57600a9-bede-43c6-a86d-8beb5520ce91.png)

Example of how it should like is the about section -

![image](https://user-images.githubusercontent.com/114980232/202716958-c26c7161-1e61-472d-b234-6c9d8ee9fc68.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4134 for more discussion.

/dup #4134
