### ISSUE TITLE
Feature Request: option to move up/down cursor using mousewheel in some apps

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#1440]
# Summary of the new feature/enhancement
Some terminals (eg. iTerm on the Mac) automatically detect command line text editors/viewers, like nano or vim. When in nano, scrolling using the trackpad/mousewheel will move up/down the cursor instead of scrolling the terminal buffer.

When exiting the app (nano or vi,...), the mousewheel/trackpad behaves as usual, scrolling in the terminal's buffer.

Of course, this special behavior should be an option that's off by default.

**Comment by DHowett-MSFT** [comment]
This will be #376 then #545 😸
