### ISSUE TITLE
Add the setting "confirmCloseAllTabs" to the UI

### ISSUE THREAD

**Issue by ElitePheonix2009** [microsoft/terminal#14413]
# Description of the new feature/enhancement

 The setting "confirmCloseAllTabs" should be added to the ui so that it can be easily found.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Huh, we didn't have one for this one. Good catch!

There was some discussion about this in #10000

> - these might not make sense in SUI. I think we'd prefer to add a checkbox or something to the warning dialogs saying "don't show this again". So maybe we want to deprecate these settings?
>   -  largePasteWarning
>   -  multiLinePasteWarning
>   -  confirmCloseAllTabs (see also https://github.com/microsoft/terminal/issues/14413)
> - zadjii note: I think these do make sense in the SUI. We need to expose ways to reveal the state of the application, including if these warnings have been disabled. I'd put these under "Interaction"
