### ISSUE TITLE
Support a setting so that the dialog box "Do you want to close all tabs?" can be set to never show again can be set to never show again

### ISSUE THREAD

**Issue by ElitePheonix2009** [microsoft/terminal#14411]
# Description of the new feature/enhancement

 A dialog box pops up saying "Do you want to close all tabs?" when we have multiple tabs open. Pls add a setting so that we can set it to never show again. If a user does not want to see that dialog box again and again when having multiple tabs open and closing the terminal window, he/she can turn on the setting.

# Proposed technical implementation details (optional)

1. Support a setting so that the dialog box "Do you want to close all tabs?" can be set to never show again can be set to never show again
2. Make sure that when it is on, the dialog box does not shows up and when it is off, the dialog box shows up.

**Comment by ElitePheonix2009** [comment]
Screenshot of the dialog box -

![image](https://user-images.githubusercontent.com/114980232/202837345-b3a2fe3a-c430-496c-808d-ed4360781ae5.png)

**Comment by zadjii** [comment]
This already exists - search the docs for `"closeOnExit": "always"`

(On mobile, so I can't link this up nicely)

**Comment by ElitePheonix2009** [comment]
> This already exists - search the docs for `"closeOnExit": "always"`
> 
> (On mobile, so I can't link this up nicely)

Yes, i found it, but I do not see an option in the ui. Do I have to set it through the json file?

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/202855483-b4fd3a9a-0ca0-420a-a89c-3d9df631360c.png)

**Comment by 237dmitry** [comment]
> This already exists - search the docs for "closeOnExit": "always"

This does not work when you close console with close button.

![wt](https://user-images.githubusercontent.com/78153320/202860498-56eb1396-59a7-4daa-8f48-937e81172032.png)

**Comment by jovibor** [comment]
`"confirmCloseAllTabs": false`

**Comment by ElitePheonix2009** [comment]
> `"confirmCloseAllTabs": false`

Yes, this worked.

> This does not work.

You have this command to hide it:
`"confirmCloseAllTabs": false`

**Comment by ElitePheonix2009** [comment]
This should be added to the ui. My issue meant to add it and if this exists add it to the ui. Updating the title and the original post.

**Comment by ElitePheonix2009** [comment]
This should be added to the ui. Opening a new issue for this.

**Comment by 237dmitry** [comment]
> You have this command to hide it
> `"confirmCloseAllTabs": false`

What does this have to do with my post about another parameter?

**Comment by ElitePheonix2009** [comment]
> > You have this command to hide it
> > `"confirmCloseAllTabs": false`
> 
> What does this have to do with my post about another parameter?

I meant that that command is for something else, you have to use `"confirmCloseAllTabs": false` to hide the dialog box.

**Comment by zadjii-msft** [comment]
My apologies for leading everyone astray. That's what I get for trying to triage at 3am.

With a baby sleeping on me.

On a saturday.

😅 

Glad this got sorted out!
