### ISSUE TITLE
Full conformance Test pass of Windows Terminal - Nov 2022

### ISSUE THREAD

**Issue by Priyanka-Chauhan123** [microsoft/terminal#14424]
### Windows Terminal version

1.17.3052.0

### Windows build number

Windows 11 Version 22H2 (OS Build 25206.1000)

### Steps to reproduce

Full scope testing

### Actual Behavior

NA

**Comment by zadjii-msft** [comment]
Hey uh @Priyanka-Chauhan123, was this supposed to be filled out/?
