### ISSUE TITLE
Settings menu options does nothing when Terminal run as another user

### ISSUE THREAD

**Issue by conioh** [microsoft/terminal#1442]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

1. Make sure you have at least two Windows users - one which is an admin and one which isn't.
2.  Install [Windows Terminal (Preview) from the Microsoft Store](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) in both users.
3. Log on into the non-admin user.
4. Run Windows Terminal as the other user.
5. Click the down arrow and then "Settings"

# Expected behavior

Default editor for `.json` files should open the settings file.

# Actual behavior

Nothing.

# Notes

This is different from #1397 where the problems was a missing default editor and unrelated to running as a another user.

**Comment by conioh** [comment]
My bad. configuration error on my side.

**Comment by mcwidg3t** [comment]
How did you manage step 4? I don't have an option to "Run as a different user" on the start menu item?

**Comment by brentos99** [comment]
I have the same problem, it doesnt matter which users i am logging in. 

* install windows terminal from store (0.2.1831.0)
* Open Windows Terminal
* Click Down Icon -> Settings
* nothing happens.
