### ISSUE TITLE
"Let Windows Decide" prefers Conhost over Terminal Preview

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#14428]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22621.819

### Steps to reproduce

* In Settings -> Privacy & security -> For developers, given the pictured options, choose "Let Windows decide"
![image](https://user-images.githubusercontent.com/138397/203561423-b905d684-e855-40f3-9847-ab16437e4dba.png)
* Run cmd from the start menu

### Expected Behavior

Windows chose Windows Terminal Preview.

### Actual Behavior

Windows chose conhost.

**Comment by zadjii-msft** [comment]
Pretty sure this is by design, and Windows will only prefer the Stable version of the Terminal, not the Preview one.

**Comment by lhecker** [comment]
Yep that's correct. The "Let Windows decide" option only checks for the non-Preview variant at the moment. The code responsible for this can be found here: https://github.com/microsoft/terminal/blob/437b5ac595915830194498eca8825e6037e288c0/src/host/srvinit.cpp#L82-L89
