### ISSUE TITLE
GitBash profile fails when opened as 1st tab

### ISSUE THREAD

**Issue by alanlivio** [microsoft/terminal#14435]
### Windows Terminal version

1.15.2875.0

### Windows build number

 10.0.22623.891

### Other Software

git version 2.38.1.windows.1

### Steps to reproduce

use Git Bash as one available profile
```
    "defaultProfile": "{42477ca6-0c65-56ae-89ef-eec9b0802c9d}",
    "profiles": {
        "list": [
            {
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "guid": "{42477ca6-0c65-56ae-89ef-eec9b0802c9d}",
                "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "name": "GitBash",
                "startingDirectory": "%USERPROFILE%"
            },
```

### Expected Behavior

GitBash profile as 1st tab open normally

### Actual Behavior

GitBash profile fails when opened as 1st tab. But works when: 
- opened as 2nd/after; 
- outside wt calling directly "C:\\Program Files\\Git\\bin\\bash.exe"

![WindowsTerminal_726](https://user-images.githubusercontent.com/604808/203773085-e28ff2c3-077c-47af-9a54-77b114ca40bf.gif)

**Comment by PankajBhojwani** [comment]
What happens if the first tab is command prompt and the second tab is gitbash? Trying to figure out if the issue has something to do with the first invocation of gitbash in terminal.

**Comment by alanlivio** [comment]
I will close the issue. I didn't face it. I image that some terminal or gitforwindows update fix it.

**Comment by DHowett** [comment]
Thanks for following up!
