### ISSUE TITLE
Execute a code, or a binary as an input for SendInput command

### ISSUE THREAD

**Issue by Hixon10** [microsoft/terminal#14432]
# Description of the new feature/enhancement

I propose to extend [sendInput](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#send-input) command (https://github.com/microsoft/terminal/issues/3799) . At present, it allows to pass `String` input, which should be displayed on the terminal. I want to execute a code and display the result, instead of static text. 

For example, I want to insert a current `git` branch to the current terminal cursor position. I can get the name with help `git rev-parse --abbrev-ref HEAD`. So, I would like to have the following hotkey in the terminal:
```
{
  "command": {
    "action": "sendInput",
    "input": $(git rev-parse --abbrev-ref HEAD), or ./get-branch-name.exe
  },
  "keys": "ctrl+k"
}
```

At present, I cannot do it, because `input` accepts only strings. There are a few workarounds, like, `"input": "git rev-parse --abbrev-ref HEAD| Set-Clipboard\r`, but they don't allow to insert needed input in place.

**Comment by zadjii-msft** [comment]
I love this. I've sorta made similar notes in #12927 in the past, but this does seem... simpler? At least, this seems to make syntactic sense. 

Not sure how this would work with #12861

**Comment by zadjii-msft** [comment]
Though, admittedly, this is also probably never gonna work. 

* What would the execution model look like? 
* We almost never know the CWD that a shell is running in, so we're more than likely not going to be able to run this in the directory you wanted.

I'm gonna merge this into /dup #12927. Fun suggestion, but technically very challenging 😄

**Comment by Hixon10** [comment]
https://github.com/microsoft/terminal/issues/12927 is kinda similar, yes.

Thank you for the answer.
