### ISSUE TITLE
Consider rewording the new confirmCloseAllTabs SUI setting

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#14433]
For clarity this might be better stated as, "Confirm when closing more than one tab". We cannot always translate the JSON names directly to sentences :smile:

EDIT: or even, "Prompt for confirmation before closing more than one tab"?

_Originally posted by @DHowett in https://github.com/microsoft/terminal/issues/14419#issuecomment-1323882392_

**Comment by crazo7924** [comment]
How about this

_Warn on closing multiple tabs_
