### ISSUE TITLE
Windows Terminal not displaying pure black background, vim colorscheme

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/terminal#14437]
### Windows Terminal version

1.7.3651

### Windows build number

22H2 build 22621.819

### Other Software

WSL2 (Ubuntu & ZSH)

### Steps to reproduce

links to theme used
- [windows-terminal/settings.json scheme](https://github.com/whatyouhide/gotham-contrib/blob/master/windows-terminal/settings.json)
- [vim colorscheme](https://github.com/whatyouhide/vim-gotham)

1) load the theme in windows terminal & vim, login zsh
2) open vim
3) check the background colors

### Expected Behavior

![image](https://user-images.githubusercontent.com/1103336/203832500-9c0b8af9-71fa-4f77-bd90-753796933fe8.png)

Expecting vim in windows terminal to look like the above with pure black background and better colors 

### Actual Behavior

![image](https://user-images.githubusercontent.com/1103336/203832464-3cddcbe9-4db8-409a-8a5f-72219569b30c.png)

The same colorscheme is showing a gray background and black in the border areas. 

Would like to know what vim settings to use to fix it

Thanks

**Comment by elsaco** [comment]
@ridhwaans there are two `gotham` color schemes and looks like your're loading `gotham.vim`. To get the one with the black backgound load `gotham256.vim`.

`gotham.vim`:

![gotham](https://user-images.githubusercontent.com/3933920/203838004-587da95b-c544-44f8-8083-1d464b32d58d.PNG)


and `gotham256.vim`:


![gotham256](https://user-images.githubusercontent.com/3933920/203838056-6d5dd4d6-26e0-41bf-a685-c742a810aa65.PNG)

**Comment by ridhwaans** [comment]
thanks
