### ISSUE TITLE
Ctrl+i key combo not working in windows terminal or powershell

### ISSUE THREAD

**Issue by lesleyrs** [microsoft/terminal#14434]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19045.2251

### Other Software

helix 22.08.1

### Steps to reproduce

Pressing `Ctrl+i` doesn't work inside of windows terminal or powershell. It does work in command prompt but not while helix editor is active.

### Expected Behavior

Helix editor requires me to use ctrl+i and ctrl+o to move around the file after using ctrl+s. The latter two commands work but ctrl+i does not.

I don't know what ctrl+i function is supposed to be either as it's not printing ^I

### Actual Behavior

Nothing, please help

**Comment by DHowett** [comment]
Thanks!
Just for completeness' sake... are you using a US104 keyboard layout and is your machine in US English? That may help us narrow down what's going on. :)

**Comment by lesleyrs** [comment]
Yes normal US international qwerty keyboard layout, Windows itself is in Dutch though. But I don't think that makes a difference?

https://github.com/helix-editor/helix/issues/4864#issuecomment-1325598084 - Here is another person who had a problem with `Ctrl+i` although using a different terminal on windows.

**Comment by 237dmitry** [comment]
In 1.16.2642 works

https://user-images.githubusercontent.com/78153320/203712187-2a07bec4-6204-417f-be14-a28daaf84e49.mp4

**Comment by lesleyrs** [comment]
I was using windows powershell 5.1.19041.1682

After installing powershell 7.3 `Ctrl+i` now works in windows terminal but it still won't function in helix.

**Comment by DHowett** [comment]
Thanks for the report! Since PowerShell, Command Prompt and (my personal favorite text editor,) vim (both Linux and Windows vim) seem to be picking up <kbd>Ctrl</kbd> correctly, I'm inclined to call this one a bug on Helix.

We'd be happy to to help them out if it's a runtime, language or implementation issue! :smile:

**Comment by lesleyrs** [comment]
Ok sorry about this one, had nothing to do with windows terminal. C-i wasn't bound at all and for some reason tab works as both tab and ctrl-i on Linux while C-i has no effect there.

Still looking for a convenient way to disable dead keys on windows terminal though, might make a new issue for that.
