### ISSUE TITLE
WriteConsoleOutput() with 0s produces undefined results instead of clearing like on previous versions

### ISSUE THREAD

**Issue by Jimbly** [microsoft/terminal#14441]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Steps to reproduce

Run a legacy console app that uses WriteConsoleOutput to clear portions of the screen, instead of clearing, results are undefined / timing-dependent and never correct.

Example program:
```c
#include <Windows.h>
#include <stdio.h>

// Expected output:
///  If you can see      there is a bug
// Actual output:
///  If you can see THIS there is a bug
// Output without Sleep():
///  If you can see  there is a bug
int main() {
	HANDLE hConsoleOut = GetStdHandle(STD_OUTPUT_HANDLE);
	CHAR_INFO blank[4] = { 0 };
	// Workaround if you have access to the original code:
	// 	for (int ii = 0; ii < 4; ii++) {
	// 		blank[ii].Char.AsciiChar = ' ';
	// 	}
	printf("\nIf you can see THIS there is a bug\r");
	Sleep(100); // Without this, the bug is even weirder

	CONSOLE_SCREEN_BUFFER_INFO csbiInfo2;
	GetConsoleScreenBufferInfo(hConsoleOut, &csbiInfo2);
	COORD pos = csbiInfo2.dwCursorPosition;
	SHORT X = pos.X + sizeof("If you can see");
	SMALL_RECT region = { X, pos.Y, csbiInfo2.dwSize.X - 1, pos.Y };
	WriteConsoleOutput(hConsoleOut, blank, { 4, 1 }, { 0, 0 }, &region);
	printf("\n");
}
```

### Actual Behavior

Either nothing is written to the screen, or the characters to be overwritten are instead removed from the terminal buffer and everything else shifted over.

**Comment by j4james** [comment]
When you say "On Windows 11", do you just mean when using Windows Terminal, which is now the default terminal for Windows 11?

The reason I ask is because this sounds like #6265 (also #4363), which has always been a problem on Windows Terminal. However, if you switch the default terminal back to the old console, your test case should still work, even on Windows 11.

**Comment by Jimbly** [comment]
~Sorry, I do not know exactly where the problem lies, just that it is a problem on Windows 11, and does not happen on Windows 10.~

Ah, I found just now how to change the default terminal.  OMG, so much better, all of my old apps are working again =).  Yes, this appears to be only an issue with Windows Terminal, and this looks similar to those linked issues (although the fact that it behaves different depending on timing might mean this is something different - not just the wrong characters making it through, but something going wrong while buffering somewhere).

**Comment by PankajBhojwani** [comment]
Thank you for reporting this! We are tracking this over at #6265 and #4363, but don't have a good answer for it yet. If you'd like to see our progress on this, those linked issues would be a good place to check :)
