### ISSUE TITLE
"blink" graphic rendition fails when used via msrdp

### ISSUE THREAD

**Issue by andylizf** [microsoft/terminal#14443]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Connect a host through msrdp and open a terminal, type `python` and enter, then type `print('\033[5mHello\033[0m\n')`.

### Actual Behavior

Through msrdp, it outputs without blinking.
However, if there is no msrdp and the above code is executed directly on this host, it blinks normally.

**Comment by andylizf** [comment]
btw, the documentation may need some updates to the "blink" graphics rendering, i.e. the escape sequences "DEC 5", "DEC 6" and "DEC 25". As of now, there is no information about this on [the documentation.](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)

**Comment by j4james** [comment]
When you're starting an RDP connection, look in the _Options_ | _Experience_ tab, and see if there is an option labelled _Menu and window animation_. If that is unchecked, I suspect that may be the problem. The blink attribute only works when window animations are enabled.

> btw, the documentation may need some updates to the "blink" graphics rendering

Yeah. I'm afraid that documentation is very out of date. There is an outstanding issue for that in the Console-Docs repo (see https://github.com/MicrosoftDocs/Console-Docs/issues/91).

**Comment by elsaco** [comment]
This is a test using WSLg, it connects to the X server via msrdp:

https://user-images.githubusercontent.com/3933920/204098261-80ff825b-620a-40a9-b59b-b9e32f052fe4.mp4

@andylizf does the test needs to be done using a remote host or just anything connected by msrdp? Thx!

**Comment by andylizf** [comment]
@j4james You are right.
> When you're starting an RDP connection, look in the _Options_ | _Experience_ tab, and see if there is an option labelled _Menu and window animation_. If that is unchecked, I suspect that may be the problem. The blink attribute only works when window animations are enabled.
@elsaco thanks for testing
