### ISSUE TITLE
Opacity is not working; the terminal remains always opaque

### ISSUE THREAD

**Issue by TheBlueSky** [microsoft/terminal#1444]
Whatever value I set my terminal opacity to, it remains opaque.

On the other hand, I can set the opacity of the "normal" or the "bundled" Command Prompt and Powershell with no Windows issue.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

CPU
    Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz

GPU
    NVIDIA GeForce GT 710
    Driver version: 25.21.14.2531
    Driver date: 09/04/2019
    DirectX version: 12 (FL 11.0)
    Physical location: PCI bus 5, device 0, function 0
```
# Steps to reproduce

- Launch Windows Terminal on my machine :)
- Go to Settings; `Ctrl+,`
- Set `acrylicOpacity` to a value that is less than 1; e.g., 0.75 or 0.5

# Expected behaviour

The window becomes semi-transparent.

# Actual behaviour

The window is still opaque.

**Comment by Aulos** [comment]
Try setting `useAcrylic` to `true`

**Comment by TheBlueSky** [comment]
@Aulos, thanks; haven't noticed the `useAcrylic` setting.

**Comment by fde-capu** [comment]
Looking for simple transparency. Would it possible to implement parameter options for each Acrylic layer?

**Comment by MPeti1** [comment]
> 
> 
> Looking for simple transparency. Would it possible to implement parameter options for each Acrylic layer?

Well it seems at Microsoft they are not willing to have any kind of opacaity other than acrylic. As far as I know the old opacity effects can't be reactivated, not even with registry hacks

**Comment by DHowett-MSFT** [comment]
> not willing

If we weren’t willing, we would have closed #603 instead if leaving it open as the workitem tracking the request for traditional transparency.

**Comment by MPeti1** [comment]
@DHowett-MSFT I'm not speaking of just this project. It's in beta, so it's not I speak of Windows too. You (or probably an other team working on an other part of the OS) took out the traditional transparency to put in the acrylic one. Why did you do that?


Sorry for the late response, I'm in the middle of fixing my OS with dism after a rollupfix update stuck in install pending, because now multiple very basic system files are corrupted. Hopefully remove-package errors out with a logged STATUS_ACCESS_DENIED at a MoveFile at 9X%. It's an other topic so I don't want to litter with this much, but if you have a suggestion or know where to ask to have response from an expert I would appreciate it

**Comment by zadjii-msft** [comment]
>  took out the traditional transparency to put in the acrylic one. Why did you do that?

Uh, no, we never took out the traditional transparency option. That's left totally unchanged in the vintage console host. We just haven't had the time to implement traditional opacity in a good fashion in the Terminal quite yet. That's the whole point of #603 - we _want_ to add that functionality, but we'd rather not just do it in the janky "make the entire UI transparent like conhost did"

**Comment by MPeti1** [comment]
@zadjii-msft It seems I badly edited my comment.

In that sentence I asked about Windows 10, not Windows Terminal

**Comment by nathan-fiscaletti** [comment]
The issue with Acrylic is that the transparency seems to go away when the window loses focus. Is there a way to fix this?

**Comment by Gonkers** [comment]
The acrylic options seem partially broken and or lackluster. Acrylic only seems to work when the window is in focus. In addition there does not appear to be a blur intensity setting. I would prefer to have nearly crystal clear like the classic terminal 
![image](https://user-images.githubusercontent.com/8480646/82018242-e152b500-9652-11ea-9868-5b652f1e344d.png)

**Comment by DHowett-MSFT** [comment]
@Gonkers I believe these things were already covered in the thread above you. Thanks for your input!

**Comment by Gonkers** [comment]
Sure thanks for the acknowledgement, but I guess the other part of the issue is a #WontFix https://github.com/microsoft/terminal/issues/593

Clearly this is a hot button issue. Sorry for wasting your time, I should have worked more on my google fu. Keep up the good fight.

**Comment by DHowett-MSFT** [comment]
(We definitely want to support materials that don’t have the blur, or materials that stay visible when the window is inactive, but there’s only so many hours in a day. :smile:)
