### ISSUE TITLE
Terminal freezes when you try to keep only ubuntu terminal open.

### ISSUE THREAD

**Issue by renansj** [microsoft/terminal#1445]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version: 0.2.1715.0
```

# Steps to reproduce

Open the terminal and click to open a new ubuntu terminal:

![](https://i.ibb.co/Nm5jTjL/Open.png)

Until now ok, but when you try to close powershell it freezes:

![](https://i.ibb.co/M9c9QWX/Close-powershell.png)

# Expected behavior

Should keep only Ubuntu terminal opened.

# Actual behavior

It's freezing the terminal, you'll have to close terminal and open again to work with it.

**Comment by scottwmwork** [comment]
I can't even get the new Windows Terminal to recognize I have ubuntu installed. so ubuntu commands for me :(

**Comment by guibirow** [comment]
Same here, sometimes it freezes when I try to close power shell.

**Comment by Shorotshishir** [comment]
@renansj Downloaded the preview release from the store, as of now unable to reproduce your issue, tried all 3 combinations, using kali-linux as WSL.

**Comment by eyalengel-pagaya** [comment]
Hi guys, 
I had this problem (reproduced) but it is solved after a restart.
now when I follow the steps the app freezes for a couple of seconds with blank window, but then exits successfully. 

@scottwmwork Had the same prob, try to add "C:\Windows\System32\wsl.exe" to "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs" and then uninstall and reinstall windows terminal - solved the issue for me.
