### ISSUE TITLE
Certain output line missing.

### ISSUE THREAD

**Issue by Bluesbreaker45** [microsoft/terminal#14450]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Other Software

Python 3.9.12 (REPL inside powershell inside windows terminal)

### Steps to reproduce

![2022-11-28-10-04-56](https://user-images.githubusercontent.com/69466344/204176584-6accac24-aadb-4189-9957-cf3a5476ca26.gif)

### Expected Behavior

Print the line that just beyond the edge.

### Actual Behavior

The line just 1 above the size of windows terminal is missing.

**Comment by zadjii-msft** [comment]
Hmm, this is a bit like #12805 (I think there's an even better issue somewhere else on the repo too.)

Can you try repro'ing this with the [debug tap](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap) to get a trace of all the input and output? Once the bug starts occurring, send us a screenshot and we might be able to figure out what the Terminal thinks it's getting here.
