### ISSUE TITLE
Unable to select text correctly while new lines are printed and history buffer is full

### ISSUE THREAD

**Issue by xPaw** [microsoft/terminal#14462]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Steps to reproduce

See #10319 for the previous report, it was supposedly fixed in v1.11, but I still see this behaviour.

1. Set `"historySize": 100,` for the profile.
2. Run a script that echoes new lines
3. Try to select text

Example script to test the issue:
```powershell
Do {
	echo $(Get-Random)
	sleep 0.1
}
while ($true)
```

https://user-images.githubusercontent.com/613331/204636943-b8f8f4b5-e6da-4fdb-88cd-b59bc8e8ad17.mp4

### Expected Behavior

Correctly select text. It works when the history buffer is full.

### Actual Behavior

The selection scrolls away from you, selecting different text.

**Comment by zadjii-msft** [comment]
It's like, the viewport is staying at the same place relative to the first-in-order of the selection anchors, but the second anchor is moving... down? Like, it's in the same buffer-relative position.

Almost as if the first one is being adjusted as lines scroll off, but not the second.
