### ISSUE TITLE
[Feature Request] Global settings to overwrite per-profile ones

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#1448]
# Summary of the new feature/enhancement

I would love to be able to overwrite per profile settings with a global one, let's say I want to use the same color scheme everywhere, setting it in the global section should do that.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Absolutely do. #754 partially covers this, and is in spec review. Would you be willing to chip in your support over there?

**Comment by Stanzilla** [comment]
Done!

**Comment by Stanzilla** [comment]
@DHowett can we un-dupe this? I don't think it's really what #754 is about.

**Comment by DHowett-MSFT** [comment]
It is; we're still mulling over what goes into the spec, but there's a contingent of us in here saying that it should include an affordance for this.
Really, it would go the opposite way from how it's been suggested here. Baseline profiles would be loaded, global user defaults would be applied, and then profile-specific user configurations would be overlaid. The "most specific" category should always win.
