### ISSUE TITLE
CTRL-C of a batch file running in CMD prompt loses terminal focus

### ISSUE THREAD

**Issue by iwilliamson** [microsoft/terminal#14485]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2251

### Steps to reproduce

1. Create a batch file that takes some time
2. Hit CTRL-C to abort the batch file
3. Notice the "Cancel batch job C:\batch.bat ? (Y/N/A) :"
4. Try and press "A"
5. The window no longer has focus - nothing happens
6. Click the mouse in the CMD window
7. Press "A"

### Expected Behavior

1. Create a batch file that takes some time
2. Hit CTRL-C to abort the batch file
3. Notice the "Cancel batch job C:\batch.bat ? (Y/N/A) :"
4. Press "A"
5. The batch file aborts

No mouse usage necessary.

### Actual Behavior

See the steps to reproduce

**Comment by iwilliamson** [comment]
I stand slightly corrected.  This seems to be an interaction with the "TCC" command line replacement.  Not CMD.exe itself.

**Comment by zadjii-msft** [comment]
> I stand slightly corrected. This seems to be an interaction with the "TCC" command line replacement. Not CMD.exe itself

So, should we resolve this as an external bug/?

**Comment by iwilliamson** [comment]
I think so.  I also submitted it to JPSoft since it seems to only happen with their software.  I'll bring it back up if it comes back this way.

Sorry.

**Comment by DHowett** [comment]
> Sorry.

Hey, not a problem at all! We're one huge community of command line app users, at the end of the day. Happy we could get some closure (?) on this :
smile:
