### ISSUE TITLE
Terminal Preview suddenly not working when there are spaces in executables path

### ISSUE THREAD

**Issue by alex-sandro92** [microsoft/terminal#14493]
### Windows Terminal version

1.16.2642.0

### Windows build number

25252.1010

### Steps to reproduce

Open a profile whose executable contains spaces in its path. 
I was not having this issue until yesterday, when I installed latest Windows cumulative update (10.0.25252.1010).

### Expected Behavior

I expect to open a profile and launch its command line.

### Actual Behavior

I get the following error if the executable contains spaces in its path (PS7 is just an example):

`[error 2147942593 (0x800700c1) when launching `D:\Program Files\PowerShell\7\pwsh.exe']`

If the executable has no spaces in its path the command line starts correctly.

**Comment by DHowett** [comment]
Thanks for the report! Can you share your `settings.json` file?

**Comment by alex-sandro92** [comment]
> Thanks for the report! Can you share your `settings.json` file?

[settings.zip](https://github.com/microsoft/terminal/files/10175133/settings.zip)

**Comment by carlos-zamora** [comment]
Hi @alex-sandro92. Do you have a file `D:\Program`?

We've hit a few of these in the past, so I'm dupping this: \dup #11717

**Comment by alex-sandro92** [comment]
> Hi @alex-sandro92. Do you have a file `D:\Program`?
> 
> We've hit a few of these in the past, so I'm dupping this: /dup #11717

That was the problem, thanks! 
That file was created by a monitoring software for my ups
