### ISSUE TITLE
[1.17] Crash with Voice Access launch

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14504]
### Windows Terminal version

commit da2b80bc0

### Windows build number

10.0.25262.0

### Steps to reproduce

1. Open WT Dev build
2. Open voice access (must have been closed)
3. Crash!

### Expected Behavior

No crash

### Actual Behavior

Crash here:
https://github.com/microsoft/terminal/blob/da2b80bc0a38f5df49a4b987527decb302d16b7b/src/cascadia/WindowsTerminal/IslandWindow.cpp#L663

**Comment by tahaluindo** [comment]
Click [Follow Me](https://github.com/tahaluindo/Sofware-Tools)
