### ISSUE TITLE
Privacy URL (go.microsoft.com/fwlink/?LinklD=521839) without the https:// for the store app

### ISSUE THREAD

**Issue by akokolodim** [microsoft/terminal#14503]
### Steps to reproduce

Adding the app in Intune as a MS Store app (new) autopopulates the privacy URL field with go.microsoft.com/fwlink/?LinklD=521839
Same if the app is installed manually and you run the command winget show --id 9N0DX20K701
looking at the app in the store under Additional terms, not privacy link is present

### Expected Behavior

Privacy URL starting with https://

### Actual Behavior

Privacy URL go.microsoft.com/fwlink/?LinklD=521839

**Comment by zadjii-msft** [comment]
What version of the Terminal are you using/? 

https://github.com/microsoft/terminal/blob/da2b80bc0a38f5df49a4b987527decb302d16b7b/src/cascadia/TerminalApp/TerminalPage.xaml#L99-L122

Those links have always been https links, since they were added.

**Comment by akokolodim** [comment]
Hello, i get version unknown as below. Also you can see the privacy URL
![image](https://user-images.githubusercontent.com/120020019/206409886-7689eb34-8155-49bf-a4c1-f9c3b4186581.png)



> What version of the Terminal are you using/?
> 
> https://github.com/microsoft/terminal/blob/da2b80bc0a38f5df49a4b987527decb302d16b7b/src/cascadia/TerminalApp/TerminalPage.xaml#L99-L122
> 
> Those links have always been https links, since they were added.

**Comment by zadjii-msft** [comment]
Ah, I see, that's not the link in the app itself, it's the link in the Store PDP. 

@DHowett / @nguyen-dows - one of you want to update that?

**Comment by DHowett** [comment]
I'll do that. Thanks!

It'll be in the next store push.

**Comment by akokolodim** [comment]
thanks!!
