### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by gargar165** [microsoft/terminal#1450]
# Environment

Windows build number: 1903 (OS Build: 18362.175)
Windows Terminal version: 0.2.1715.0

# Steps to reproduce

Open enough tabs in a window with any horizontally sized window and open tabs until the tabs no longer show their close button ('X') in their tab.

# Expected behavior

When looking at tabs, normally the tabs would self-size themselves like my web browser here.

![image](https://user-images.githubusercontent.com/35781771/59970354-8b03f180-9529-11e9-8743-49817c8c2458.png)

However, because this isn't the case...

# Actual behavior

This occurs instead.

![image](https://user-images.githubusercontent.com/35781771/59970346-4e37fa80-9529-11e9-941c-ffa9de2a269a.png)

Note that the second tab appears not only be cut off, but it also does not show a close button. This might be due to some "self-sizing" tab feature that hasn't been implemented yet, but to a normal user, this is unexpected.

**Comment by DHowett-MSFT** [comment]
Hi there,
Two things:
1. please make sure you type in a title for your bug. otherwise, we get e-mails that say "BUG REPORT!" with no more info
2. please search for existing bugs when filing a new one. this one is #597
