### ISSUE TITLE
msteams:// and maito: links aren't clickable

### ISSUE THREAD

**Issue by mkanet** [microsoft/terminal#14505]
I notice that Terminal 1.5 now supports clickable hyperlinks.  I can't seem to make msteams:// and maito: links clickable.  Could someone please tell me the correct way to do this, for example, in PowerShell?

**Comment by tahaluindo** [comment]
Click [Follow Me](https://github.com/tahaluindo/Sofware-Tools)

**Comment by mkanet** [comment]
Thank you.  Clever!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7562 for more discussion.

/dup #7562
