### ISSUE TITLE
Python Autocomplete Enabled; Can't Disable

### ISSUE THREAD

**Issue by MarkMoretto** [microsoft/terminal#14510]
### Steps to reproduce

Use IPython and type part of a command that you've already run.

### Expected Behavior

The ability to type code without auto-complete being forced upon me.

I would like to disable this behavior.

### Actual Behavior

Auto-complete using recent history to suggest code.  See image.

![image](https://user-images.githubusercontent.com/25012707/206473493-50a01159-4b48-409d-8f96-f1f4b8e00a34.png)

**Comment by zadjii-msft** [comment]
This isn't something the Terminal is providing. This is something _probably_ coming from IPython itself. You might want to check their configuration options. 

I know that PSReadline has a similar auto-suggest feature, but based on the text there I wouldn't suspect that to be the PsReadline completion.

**Comment by zadjii-msft** [comment]
See: https://github.com/ipython/ipython/issues/12819#issuecomment-1344862304

/dup https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#autosuggestions
