### ISSUE TITLE
Launch elevated Terminal profile without a keyboard

### ISSUE THREAD

**Issue by nguyen-dows** [microsoft/terminal#14517]
# Description of the new feature/enhancement
Today, there is no way to launch an elevated Terminal profile end-to-end without the need to use a keyboard. 

Even without a physical keyboard, the user flow is still the same with a on-screen keyboard: 
1) Launch Terminal
2) Ctrl + Click the profile you want to open

This Feature Request proposes a way for a user to open an elevated Terminal profile without the need to use a keyboard. 
This is a very common Accessibility scenario. 
The user should be able to launch an elevated Terminal profile with just a touch screen and / or mouse. 

For more details see: https://twitter.com/SBarizien/status/1599769771666391042

**Comment by zadjii-msft** [comment]
Were there any suggestions for how to do that? 

The only thing I could think of was some default nested actions for opening a new elevated profile in the Command Palette. Trick here is the wording - we don't want to open a new window always, but we'll need to if the terminal isn't already elevated. 

Maybe just "Open Elevated > {profiles}"?

**Comment by 237dmitry** [comment]
As a workaround you can elevate current profile or execute command in elevated state with [gsudo](https://github.com/gerardog/gsudo/releases) via UAC confirmation.

**Comment by DHowett** [comment]
@zadjii-msft I thought of this, which is everyone's favorite UI:

![image](https://user-images.githubusercontent.com/189190/206790820-903e0b70-5d67-4053-a334-9250ea9ae9b0.png)

It's a right-click menu item _with a right-click menu_. It also works with touch (touch-hold-release!)

**Comment by DHowett** [comment]
If we did that, we could also put the splits in it...!

**Comment by zadjii-msft** [comment]
_can_ we add right click context menus to menu flyouts?

**Comment by DHowett** [comment]
I gave it a shot in XAML Studio!

![image](https://user-images.githubusercontent.com/189190/206792681-b2e54028-cbf6-4db6-8cef-d085652be01d.png)

```xaml
        <Rectangle Width="100" Height="100" Fill="Yellow">
            <Rectangle.ContextFlyout>
                <MenuFlyout>
                    <MenuFlyoutItem Text="First" />
                    <MenuFlyoutItem Text="Second">
                        <MenuFlyoutItem.ContextFlyout>
                            <MenuFlyout>
                                <MenuFlyoutItem Text="Well I'll Be..." />
                            </MenuFlyout>
                        </MenuFlyoutItem.ContextFlyout>
                    </MenuFlyoutItem>
                </MenuFlyout>
            </Rectangle.ContextFlyout>
        </Rectangle>
```

**Comment by zadjii-msft** [comment]
Damn, yea let's do that. ez.

**Comment by michalnpl** [comment]
I've got a kind of fix for it. The tasks in Jumplist do not support custom menus, AFAIK. But I added the context menu to the profiles flyout. However, the context menu is wrong-positioned, and I have trouble determining why. It works correctly with localization and elevation; just the positioning is off. I used **BottomEdgeAlignedLeft** on **profileMenuItem** and experimented with all combinations, always getting it off.

![runasoff](https://user-images.githubusercontent.com/25628581/231909244-8632a357-3426-480a-b7e4-bd1e93bf07e2.png)

**Comment by michalnpl** [comment]
Sure @zadjii-msft  here is the [branch](/michalnpl/terminal/tree/michalnpl/Launch_elevated_Terminal_profile_without_a_keyboard)

Interestingly Shift+F10 (shortcut to invoke context menu) opens the context menu in the right place while right-clicking on the item opens it completely misaligned. Don't forget to regenerate resources (added items to .resw).

**Comment by michalnpl** [comment]
@zadjii-msft No worries. I thought about it but abandoned the idea because it seems like this should be handled correctly by XAML, and I am also afraid I'll miss some edge cases, or it will not be future-proof if I handle it manually. The proposed code seems to be doing the correct thing but the framework is acting unexpectedly. Perhaps there is a way to have the XAML team look at this?

**Comment by jamespack** [comment]
I may take a stab at this if nobody is working it.

**Comment by jamespack** [comment]
<img width="345" alt="image" src="https://github.com/microsoft/terminal/assets/2086722/05f648d7-ab99-49b1-9b75-3a5b0d0f11e2">

<img width="542" alt="image" src="https://github.com/microsoft/terminal/assets/2086722/6377126d-f92d-47d1-8a94-c0ab783e73a4">


Which alignment do we want? I can show screenshots of all of them if you'd want to see them all

**Comment by jamespack** [comment]
I kinda like this one.

<img width="424" alt="image" src="https://github.com/microsoft/terminal/assets/2086722/5ad8584c-1803-430e-93b0-04b9f4f5cd8f">

**Comment by jamespack** [comment]
Do we have a preference on which Icon we use for the LUA shield?  
<img width="360" alt="image" src="https://github.com/microsoft/terminal/assets/2086722/e527a2a4-55b9-41bf-a695-256a51d5112d">

**Comment by jamespack** [comment]
Or this guy?

<img width="382" alt="image" src="https://github.com/microsoft/terminal/assets/2086722/25e5dac9-09b2-4f4d-a2d4-9d0e73d87d51">
