### ISSUE TITLE
Cannot scroll back more than 32K lines

### ISSUE THREAD

**Issue by ByteEnable** [microsoft/terminal#14523]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22621.0

### Other Software

power shell
bash
cmd.exe

### Steps to reproduce

Settings -> Profiles -> Defaults -> Advanced -> History Size

Change the setting to 2147483647 and save.

Output more than 32K lines by running a dir command:

dir c:\ -s

or

dir c:\ /s

### Expected Behavior

To be able to scroll back past 32K lines in the terminal via the scroll bar.

### Actual Behavior

Could only scroll back 32K lines or so.

**Comment by zadjii-msft** [comment]
Yep, sure can't. We need to update the documentation to clarify that. The docs update is tracked in /dup  https://github.com/MicrosoftDocs/terminal/issues/510.
