### ISSUE TITLE
Hope to upgrade Winui 2.8

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#14528]
# Description of the new feature/enhancement

At present, the Winui 2 version used by Windows terminal is 2.7, but the latest Winui2 version 2.8 has been released in the second half of this year, the lowest system version of Winui 2.8 is 17763, and the Windows terminal has met the minimum system version requirements of Winui 2.8, hoping to upgrade to Winui 2.8 as soon as possible.

# Proposed technical implementation details (optional)

Ask the team to quickly upgrade Microsoft.ui.xaml2.7 to Microsoft.ui.xam2.8 from Visual Studio's Nuget package manager

**Comment by zadjii-msft** [comment]
Is there a particular WinUI 2.8 feature you're missing in the Terminal? We've tried updating to 2.8 in the past, but there were a number of minor regressions that made the whole update unpalatable. Other than some minor bug fixes, there also didn't seem to be anything major we were missing from 2.8. 

In general, we're tracking that work in /dup #13495, but I'd love to know more why you'd like us to update!
