### ISSUE TITLE
Leaked terminal escape codes into shell text

### ISSUE THREAD

**Issue by jfpoirier-x2o** [microsoft/terminal#14537]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.20348.0

### Other Software

Client:
Windows 10.0.19045.0
Remote Desktop Client 10.0.19041

### Steps to reproduce

1. Connect to Windows Server 2022 over RDP
2. Launch Windows Terminal
3. Focus out of RDP session (to browse web on local station, for example)
4. Focus back into the Windows Terminal-over-RDP session by _clicking into the WT session_

### Expected Behavior

Nothing gets appended/written to shell.

### Actual Behavior

Partial-to-complete terminal emulation code are written out to shell.

Examples obtained by added "debugFeatures": true to settings.json and using the double-alt split-screen terminal debug, then focusing out of RDP and back into the terminal session:
![image](https://user-images.githubusercontent.com/55152957/207136122-22df0807-3bc2-45f5-80d0-efc26502d532.png)
![image](https://user-images.githubusercontent.com/55152957/207136498-2089abb2-8a07-49b5-9aaf-41841b433c5e.png)

**Comment by carlos-zamora** [comment]
This may have been floating around for a while. Thanks for the report. We'll look into it and appropriately triage this when someone does that.

**Comment by zadjii-msft** [comment]
Hey #15919 has quite a bit more details than this thread, so we'll combine with that one. Thanks! /dup #15919
