### ISSUE TITLE
Some previous output missing when scroll up in ubuntu

### ISSUE THREAD

**Issue by woshikid** [microsoft/terminal#14530]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19045.2251

### Other Software

apt (inside the WSL)

### Steps to reproduce

1. open a ubuntu tab or a "cmd" tab then run `bash`
2. the terminal window is about 20 lines in height
3. run `sudo apt autoremove -y vim`
4. run `sudo apt install vim`
5. scroll up to see the history output
6. you'll find some previous output has missing

### Expected Behavior

When the window is big enough, the output should like this:
![image](https://user-images.githubusercontent.com/29223368/206979812-57ae0803-0d4e-43e1-a88e-87dc572789ac.png)

### Actual Behavior

But when the window is 20 lines height, after scrolling up, the content is missing.
Some output of  `sudo apt autoremove -y vim` is missing
Some output of `sudo apt install vim` is missing even the command itself.
![image](https://user-images.githubusercontent.com/29223368/206978236-cb62e523-89a3-4ce5-a00a-174c2d5d272c.png)

and this is the screenshot after I make the window bigger.
![image](https://user-images.githubusercontent.com/29223368/206979158-5b9dbabd-6955-46b6-b601-d1bd7488cb57.png)

**Comment by zadjii-msft** [comment]
Hmm, this is different from #14512. In that one, the lines of text are missing, but the newlines are still there. Here, the row seems to be missing entirely. 

Was the `sudo apt install vim` line originally in the buffer/? If so, I'd reckon this is the same root cause as #12805

**Comment by j4james** [comment]
I think this is just because apt is using a scrolling region that starts at the top of the screen (issue #3673). See also #7687 and #9939.

**Comment by zadjii-msft** [comment]
Op, yea, that looks right to me. Thanks!

/dup #3673
