### ISSUE TITLE
emacs ctrl-comma 响应到ctrl-l 

### ISSUE THREAD

**Issue by 354651432** [microsoft/terminal#14531]
### Windows Terminal version

 1.15.2874.0

### Windows build number

19044。2130

### Other Software

wsl2 linux version :Ubuntu 22.04.1 LTS
emacs : GNU Emacs 27.1

### Steps to reproduce

install emacs in wsl2 and press ctrl-comma 

### Expected Behavior

ctrl-comma replay ctrl-comma 

### Actual Behavior

ctrl-comma replay ctrl-l

**Comment by carlos-zamora** [comment]
Thanks for the report! We think we have an issue that's already tracking this.

/dup #3483
