### ISSUE TITLE
Invaild font in Profiles.json causes text to go really small and crashes the terminal when new session is made with the profile

### ISSUE THREAD

**Issue by JushBJJ** [microsoft/terminal#1453]
# Environment

```none
Windows build number: [Version 10.0.18362.175]]
Windows Terminal version (if applicable):

Microsoft Terminal (Preview)

Any other software?

No.
```

# Steps to reproduce

Change the fontface in profiles.json on what ever profile you want into a invalid fontface/unsupported fontface.
Example: `"fontFace" : "ooga booga"`,
# Expected behavior

Default to config to the consolas font after a certain time. (Maybe in 5-10 seconds to avoid annoying live changes, especially when you're editing the file in VSCode.

# Actual behavior

![image](https://user-images.githubusercontent.com/36951064/59970630-a82ed380-95ae-11e9-9d8a-a4b9109e0f40.png)

**Comment by habitatm45** [comment]
I can confirm. I just ran into this issue with a valid installed font that has multiple spaces in the name.

**Comment by DHowett-MSFT** [comment]
Thanks for reporting. #550 contains the words “font” “not exist” and “crash”. #1017 as well. Please make sure you search before reporting a new issue.
I know we have an issue tracking the weird rendering for nonexistent fonts too, but I’m on my phone and GitHub mobile search is pretty bad.
