### ISSUE TITLE
OSC 12 "set cursor color" not working, in atlas engine

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#14533]
> ```
>     @DHowett @mattwojo sorry to dig this old thread up, but if I do a `printf %b '\e]12;red\a'`, should I expect the cursor color to change to red?  Using terminal preview version 1.16.2641.0, doing the above in wsl, I don't see the cursor color changing.  It retains the original color specified via the color theme in the settings.
> ```
> 
> ![image](https://user-images.githubusercontent.com/5184519/205766590-99ab3d79-f69a-4575-8ee0-78ed227fccf3.png)
> 
> _Originally posted by @damnskippy in [#184 (comment)](https://github.com/MicrosoftDocs/terminal/issues/184#issuecomment-1338354637)_

> Interestingly enough, if I lock my screen (Windows-L) and unlock it the cursor has then changed its color. ![image](https://user-images.githubusercontent.com/5184519/205782860-6366276a-a571-47b8-8fb9-4cb86ac82816.png)
> 
> after locking and unlocking: ![image](https://user-images.githubusercontent.com/5184519/205783118-b545c614-64b2-45b3-85f0-66f50fa682aa.png)

> ~I bet we don't do an invalidate of the screen.~
> 
> Nah I dunno what this is. We should move this over to the Terminal repo cause I see this too. Even with the `rgb:` specs too.

(from https://github.com/MicrosoftDocs/terminal/issues/620)

Version number unknown.

```
printf '\e]12;red\a Foo bar' ; sleep 3
printf '\e]12;rgb:ff/00/00\a Foo bar' ; sleep 3
```

```bat
@echo off
if (%1)==() (goto :usage)
if (%2)==() (goto :usage)
if (%3)==() (goto :usage)

@rem this is a literal ESC and BEL in this next line
echo ]12;rgb:%1/%2/%3
goto :EOF

:usage
echo Usage: cursor-color ^<red^> ^<green^> ^<blue^>
echo     where red, green, blue are color components in hex
echo     Ex: cursor-color FF 00 FF will set the cursor to [38;2;255;0;255mMagenta[0m
echo:

:EOF
```

**Comment by zadjii-msft** [comment]
I can confirm that the cursor changes did seem to reappear after a lock/unlock of my machine! That makes me think there's still an invalidation issue. Maybe in the Atlas engine? IDK if @damnskippy was on 1.15 or 1.16

**Comment by damnskippy** [comment]
Thank you for picking this up @zadjii-msft, and I'm glad/relieved this is reproducible on your end locally.  I don't know how to determine the version on Atlas Engine.  If there's a command or something that can be run that will produce this, I'd be happy to do so if it's of use.

**Comment by zadjii-msft** [comment]
@damnskippy oh _ don't mean the "atlas engine version", I more just meant the Terminal version, which you can find in the About dialog. The Atlas engine was added in 1.16, but isn't in 1.15.

**Comment by damnskippy** [comment]
Oh, Terminal (Preview) version is 1.16.2641.0.
