### ISSUE TITLE
Ctrl+F4 has to be bound manually

### ISSUE THREAD

**Issue by CouscousPie** [microsoft/terminal#14532]
Regarding the Ctrl+F4 shortcut in [another thread](https://github.com/microsoft/terminal/issues/8585#issuecomment-744618127) @DHowett made the following remark:

> That binding's not supposed to work unless you go into your settings and explicitly bind it yourself. That it _does_ work anywhere without it being bound explicitly is the bug I'd rather fix. :smile:

Indeed, I think that is a bug that should be fixed as it is confusing for the user that a mouseover on the tabs suggests to use a shortcut that doesn't work.

Possible solutions would be to either set Ctrl+F4 to the standard or just change the mouseover to a message that hints at the non-set shortcuts or/and advise to do so in settings.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10109 for more discussion.

/dup #10109
