### ISSUE TITLE
Unreadable console output on PowerShell

### ISSUE THREAD

**Issue by Manish-Giri** [microsoft/terminal#14545]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0

### Steps to reproduce

Just running Angular unit tests with `npm run test`, certain parts of the console output are always unreadable because the text is in a gray color against a dark background, while all the remaining text is readable. Screenshot below -

![image](https://user-images.githubusercontent.com/11348778/207228350-629e2aaa-776c-4285-a285-93a12246d75a.png)

Here is the color scheme currently applied for PowerShell -
```
       {
            "background": "#0F1419",
            "black": "#000000",
            "blue": "#36A3D9",
            "brightBlack": "#323232",
            "brightBlue": "#68D5FF",
            "brightCyan": "#C7FFFD",
            "brightGreen": "#EAFE84",
            "brightPurple": "#FFA3AA",
            "brightRed": "#FF6565",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFF779",
            "cursorColor": "#F29718",
            "cyan": "#95E6CB",
            "foreground": "#E6E1CF",
            "green": "#B8CC52",
            "name": "ayu",
            "purple": "#F07178",
            "red": "#FF3333",
            "selectionBackground": "#253340",
            "white": "#FFFFFF",
            "yellow": "#E7C547"
        }
```

What property can I change so that the unreadable text color can be changed? And it's not specific to just this particular color scheme, I've tried several, and the text is the same gray color across all color schemes.

### Expected Behavior

All text should be readable.

### Actual Behavior

Certain parts of text are not readable.

**Comment by zadjii-msft** [comment]
That looks to me like the `brightBlack` color in your color scheme. I'm not sure there's a way to control which colors from the scheme that your unit test framework emit's output in, but changing the value of `brightBlack` there should help.
