### ISSUE TITLE
Skipping lines when opening scripts by double click

### ISSUE THREAD

**Issue by VillaFX** [microsoft/terminal#14547]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.900

### Steps to reproduce

Using a very simple loop. in a .bat and opening by double click (it works properly, if open via command in terminal or by using cmd)
`ECHO OFF`
`CLS`
`FOR /L %%i IN (0,1,50) DO (ECHO %%i)`
`PAUSE`

### Expected Behavior

0
1
2
3
4
......

### Actual Behavior

![run](https://user-images.githubusercontent.com/120457437/207282637-403f2f71-3e73-434c-9f9e-ce1128444ccf.png)

**Comment by zadjii-msft** [comment]
This actually _super bad_.

There's clearly a race here in the window size in the defterm case. 

A note: adding a `mode` breaks the repro. 

We should investigate more.

**Comment by zadjii-msft** [comment]
Wait hold on, this might be /dup #14512. They're both fairly similar. I'm gonna call them dupes until proven otherwise.
