### ISSUE TITLE
 Ansi Escaping written to console in PowerShell

### ISSUE THREAD

**Issue by Herrmel** [microsoft/terminal#14554]
### Windows Terminal version

conhost

### Windows build number

Microsoft Windows [Version 10.0.19044.1889]

### Other Software

PowerShell 7.3

### Steps to reproduce

When piping input of an application to an Commandlet like Write-Error the written content contains the ansi escaping signs.
For example the command:

```ps1
dotnet --version | Write-Verbose -Verbose
```

### Expected Behavior

Printing the following output in yellow:

```
VERBOSE: 7.0.100
```

### Actual Behavior

The following Text is printed colorless:

�[33;1mVERBOSE: 7.0.100�[0m

**Comment by Herrmel** [comment]
I opened this Bug in the PowerShell repository first and was guided to this repository.
More Details here: [#18771](https://github.com/PowerShell/PowerShell/issues/18771)

**Comment by zadjii-msft** [comment]
Did you ever call [`SetConsoleMode`](https://learn.microsoft.com/en-us/windows/console/setconsolemode) with `ENABLE_VIRTUAL_TERMINAL_PROCESSING`/? That's needed to enable ANSI escape sequences.
