### ISSUE TITLE
[1.17] Setting app theme results in mismatched light/dark colors for SUI text

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14559]
Go to Appearance -> set theme to 'Light' 

Some settings have the header in black some have them in white (seems to be the different setting container styles) 
<img width="761" alt="GetImage (3)" src="https://user-images.githubusercontent.com/11050425/207741120-6d178b39-6d12-4161-838e-e72bacca916b.png">

**Comment by zadjii-msft** [comment]
Hmm. I don't know if I can repro this exactly. 

What I _can_ repro is the SUI BG not matching the app theme. That I think regressed in #14567, which I can't remember if it made it to the bug bash or not. 

Does this happen on launch when the theme is set to "light"? Or do you need to switch from some other theme?

I'll submit the mica fix, and then you try that out and tell me if this is gone

**Comment by carlos-zamora** [comment]
> Hmm. I don't know if I can repro this exactly.
> 
> What I _can_ repro is the SUI BG not matching the app theme. That I think regressed in #14567, which I can't remember if it made it to the bug bash or not.
> 
> Does this happen on launch when the theme is set to "light"? Or do you need to switch from some other theme?
> 
> I'll submit the mica fix, and then you try that out and tell me if this is gone

The way I got it to repro was...
1. OS theme = dark
1. In Terminal, start with theme=terminal
2. switch to theme=Light

```js
        {
            "name": "terminal",
            "tab": 
            {
                "background": "terminalBackground",
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "tabRow": 
            {
                "background": "terminalBackground",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "dark",
                "useMica": false
            }
        }
```
