### ISSUE TITLE
Taskbar icon status is blinking

### ISSUE THREAD

**Issue by eddiezato** [microsoft/terminal#14565]
### Windows Terminal version

1.16.3464.0

### Windows build number

10.0.22621.0

### Other Software

PowerShell 7.3.1

### Steps to reproduce

Open `pwsh` in the folder with many small files and run the command:
```PowerShell
ls '*.*' | % { Compress-Archive -Path $_ -DestinationPath ($_.BaseName + '.zip') }
```

### Actual Behavior

The taskbar icon will behave as follows:

![out](https://user-images.githubusercontent.com/11173476/207776960-c0a5d674-4b19-444b-b9b4-315cdbdeaa4e.gif)

**Comment by zadjii-msft** [comment]
Does this repro the same if you ran the same command in the vintage console? (`conhost pwsh` in the Run dialog should work). 

Oh, I wonder if powershell is setting the taskbar progress with VT, but because the files are _so_ small, they complete almost immediately, resetting the progress state back. @stevel-msft does that sound like something powershell would do?

**Comment by eddiezato** [comment]
@zadjii-msft Nope, it's ok in the old console.

I first saw this a couple of updates ago. But I'm not sure who is to blame, `wt` or `pwsh`. I have a script that runs `foreach` in parallel with each loop as a background job. In the loops, I run some file conversion tools. At the same time, I show overall progress of the script in the tab title and on the taskbar icon. This blinking thing keeps interrupting the progress display.

This command to compress a bunch of small files is just a quick example to show and reproduce what happens.

**Comment by zadjii-msft** [comment]
This might just end up by-design. Seems like `Compress-Archive` (or some other machination of powershell) is setting the taskbar progress, but it's setting the icon to the progress state for such a short period of time that it effectively just flashes the underline like that. 

I'd reckon there's probably a way to disable this in PowerShell, but alas, that I don't know. @stevel-msft might know better than myself. 

/aside: I do like the way you're wrapping up that `Compress-Archive` command with progress bar sequences in that above snippet. I might borrow that for some of my own scripts 😄
