### ISSUE TITLE
[1.17] `alwaysShowTabs: false` `showTabsInTitlebar: true` leads to an empty NCIW title bar 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14562]
![GetImage (5)](https://user-images.githubusercontent.com/11050425/207741861-51df9511-5d22-44a6-ba22-5b64751e3f18.png)

**Comment by zadjii-msft** [comment]
Yea I can't repro this anymore either. Closing this out. I bet this was a wacky 1.17 selfhost build.
