### ISSUE TITLE
[1.17] Setting the $theme.tabRow.background to `#00000000` results in double titlebar

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14563]
<img width="104" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/11050425/207742017-9d3412af-d59b-43ff-8f0e-43b8b2e984da.png">

**Comment by zadjii-msft** [comment]
GAH GOD I thought I fixed that. Regressed probably in the last few commits of #13935

**Comment by DHowett** [comment]
So, I've noticed that I only see this after a settings reload... or sometimes when locking/unlocking my workstation. There's some interplay between the different window styles we go through on the way to "no titlebar."

**Comment by zadjii-msft** [comment]
what settings tho

**Comment by DHowett** [comment]
This is all I've got in the themes department:

```json
    "theme": "Cool Things",
    "themes": 
    [
        {
            "name": "Cool Things",
            "tab": 
            {
                "background": "terminalBackground",
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "tabRow": 
            {
                "background": "#00000000",
                "unfocusedBackground": null
            }
        }
    ],
    "alwaysShowTabs": true,
    "showTabsInTitlebar": true,
```

**Comment by zadjii-msft** [comment]
FUDGE okay, that does repro for me, with 
![image](https://user-images.githubusercontent.com/18356694/213565417-44e8121d-01b2-477a-8a8a-18978b5e641c.png)

I'll figure that out. I bet there's a weird interaction between the `#00000000` and the `null`

**Comment by zadjii-msft** [comment]
Yep, that's what does it. 

If the window is inactive when the settings are changed, the NCIW will use the _current_ `TitlebarBrush` to determine if we need to totally obscure the titlebar or not. For this theme, the ThemeColor is null, so the NCIW evaluates that as opaque, so it decides it's fine to have a titlebar.

Easiest way to do this is probably expose another property out of applogic to make this easy.

**Comment by DHowett** [comment]
Thanks for digging through my bad bug reports haha
