### ISSUE TITLE
some touch pad gesture support unfriendly

### ISSUE THREAD

**Issue by vhwfif** [microsoft/terminal#14578]
### Steps to reproduce

I'am using four-finger to slide up to maximize the window and four-finger to slide down to minimize the window.I have found this all can't support.Besides,I found that my custom four-finger right swipe represents alt +F4, and I found it didn't work to close the window either.

### Actual Behavior

some touch pad gesture is unavailable.

!!!Oh,I realize that this only happens on pages that are opened as administrators.

**Comment by 237dmitry** [comment]
In my environment these gestures work like this:

| Four Fingers swipe |  Actions |
|----------------------|--------|
| Up | Rise Virtul Desktops screen or Restore a window if it was previously minimized  |
| Down | Minimize window |
| Left | Switch to the Next Virtual Desktop |
| Right | Switch to the Previous Virtual Desktop |

This is global behavior for any window. WT is no exception.

Win 11 (10.0.22621)
WT 1.16.3464.0

**Comment by vhwfif** [comment]
Yes.It's already working.Me env is win10.Yestartay had some updeted.May I didn't notice yestarday.

**Comment by vhwfif** [comment]
Oh,I realize that this only happens on pages that are opened as administrators.


> ### Windows Terminal version
> _No response_
> 
> ### Windows build number
> _No response_
> 
> ### Other Software
> _No response_
> 
> ### Steps to reproduce
> I'am using four-finger to slide up to maximize the window and four-finger to slide down to minimize the window.I have found this all can't support.Besides,I found that my custom four-finger right swipe represents alt +F4, and I found it didn't work to close the window either.
> 
> ### Expected Behavior
> _No response_
> 
> ### Actual Behavior
> some touch pad gesture is unavailable.

Oh,I realize that this only happens on pages that are opened as administrators.

**Comment by vhwfif** [comment]
Oh,I realize that this only happens on pages that are opened as administrators.

**Comment by vhwfif** [comment]
Oh,I realize that this only happens on pages that are opened as administrators.

**Comment by zadjii-msft** [comment]
>  my custom four-finger right swipe represents alt +F4

What did you use to set up the custom gestures/?
