### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by indrajithbandara** [microsoft/terminal#1457]
Use UTF-8 as source and executable encodings for C++ projects that
contain UTF-8 source files.

Tree 35229a7 fails to build where the
default code page is 936 (GBK), due to multiple files containing UTF-8
encoded strings and/or comments, and these projects set to
fail-on-warning mode. Additionally,
src/host/ut_host/UnicodeLiteral.hpp contains a Windows-1252 encoded
string. This commit adds the /utf-8 option to the affected projects,
and converts src/host/ut_host/UnicodeLiteral.hpp to UTF-8.

**Comment by DHowett-MSFT** [comment]
This is a duplicate of #1251. Thanks!
