### ISSUE TITLE
dock profiles on screen 

### ISSUE THREAD

**Issue by curewitz** [microsoft/terminal#14577]
It would be nice to be able to keep profiles docked to the left instead of having to click the drop down to show them. You already have this implemented when you open settings. Could it be added as an option to dock them permanently? 
example of request 
<img width="999" alt="examle" src="https://user-images.githubusercontent.com/9154167/208246915-303c6172-40f1-412d-a386-4bf03503ecba.png">

what you already have in settings
<img width="598" alt="example dock" src="https://user-images.githubusercontent.com/9154167/208246620-7444dc06-f29b-4f97-b770-59b21c1cb65b.png">
instead of 
<img width="834" alt="instead of" src="https://user-images.githubusercontent.com/9154167/208246728-b6fe9e43-2877-44c7-afdc-8ea4fb980b25.png">

**Comment by j4james** [comment]
Have a look at issue #14453. This sounds like a similar concept.

**Comment by zadjii-msft** [comment]
Yea, that sounds like the same request. Would the solutions I posed in that thread work for you/?
