### ISSUE TITLE
Bug Report: Terminal won't start if profile's commandline points to non-existing exe

### ISSUE THREAD

**Issue by garyng** [microsoft/terminal#1458]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.30]
Windows Terminal version: 0.2.1715.0
```

# Steps to reproduce

1. Install, launch and close Windows Terminal
1. Uninstall PowerShell Core
1. Launch Windows Terminal again

# Expected behavior

1. Windows Terminal should start

# Actual behavior

1. It crashes

# Workaround
Force Terminal to generate a new `profiles.json` by deleting it.

**Comment by DHowett-MSFT** [comment]
This's #982.
