### ISSUE TITLE
Always show scroll bar

### ISSUE THREAD

**Issue by Demiu** [microsoft/terminal#14589]
# Description of the new feature/enhancement

An ability to have the scroll bar always visible. Right now this is technically possible via the ease of use settings in windows, but that is a system-wide setting. It would be preferable to have a settings in the terminal so this config doesn't spill to every other program.

# Proposed technical implementation details (optional)

A toggle in the appearance settings that will cause the scroll bar to be always shown

**Comment by PankajBhojwani** [comment]
We have this setting in Windows Terminal! You can do this per-profile by going into Settings -> [Profile] -> Appearance -> Scrollbar visibility: Always. 

If you would like it to apply to all your profiles, you can set it in your [Defaults] profile -> Appearance.

**Comment by Demiu** [comment]
There is only Visible and Hidden. https://i.imgur.com/MQBpiM1.png

Visible fades out

**Comment by PankajBhojwani** [comment]
My bad! This feature will be coming in version 1.17 (I was on an internal version when I replied earlier). So, yes it will be coming soon! Thank you for the suggestion

**Comment by zadjii** [comment]
Pretty sure `always` was added in 1.17 which isn't out yet

**Comment by zadjii** [comment]
Lol thanks GitHub for not loading the most recent posts until _after_ I hit comment 🤦
