### ISSUE TITLE
Why in Spanish?

### ISSUE THREAD

**Issue by Snappvidar** [microsoft/terminal#14594]
When I Install Windows Terminal from Microsoft Store I always get it in Spanish! Why_

**Comment by j4james** [comment]
That's likely because Spanish is configured as one of your **Preferred Languages** in the Windows settings. Have a look at **Settings > Time & Language > Language**.

I believe it chooses the first language that is an exact match for one the supported translations, but you can always override that choice in the Windows Terminal settings. See the screenshot here: https://github.com/microsoft/terminal/issues/11157#issuecomment-915271804

**Comment by Snappvidar** [comment]
Thank you for responding.
I don’t belive this is the reason. I have my native language (Swedish) set in Language.
When I go to Microsoft Store to download Windows Terminal even the description is in Spanish! Maybe this is an European thing
Thank you.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: James ***@***.***>
Skickat: den 22 december 2022 23:33
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [microsoft/terminal] Why in Spanish? (Issue #14594)


That's likely because Spanish is configured as one of your Preferred Languages in the Windows settings. Have a look at Settings > Time & Language > Language.

I believe it chooses the first language that is an exact match for one the supported translations, but you can always override that choice in the Windows Terminal settings. See the screenshot here: #11157 (comment)<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fterminal%2Fissues%2F11157%23issuecomment-915271804&data=05%7C01%7C%7C32ef4121577d4befef1908dae46c9ae3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638073452356229844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BHIwIyobuq2%2B7CKPwcE1xYCtUSbuY%2BA1pXNeCa2PUNY%3D&reserved=0>

**Comment by j4james** [comment]
> I have my native language (Swedish) set in Language.

I don't think Swedish is one of the supported translations for Windows Terminal, so it's going to fallback to some other language. If you want that fallback language to be English, you can set that in the **Preferred Languages** section of the Windows Settings. See the screenshot below where I've got _Engelska_ set as a second preference to _Svenska_.

![Languages](https://user-images.githubusercontent.com/4181424/209472397-7e198201-af35-4cc0-a855-f46bc15485ae.png)

Alternatively, you can set that preference in Windows Terminal itself, as I mentioned above. See the screenshot here: https://github.com/microsoft/terminal/issues/11157#issuecomment-915271804

**Comment by Snappvidar** [comment]
Thank you.
After moving up English as the second language in Priority language I now get the app in English.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: James ***@***.***>
Skickat: den 25 december 2022 15:48
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [microsoft/terminal] Why in Spanish? (Issue #14594)


I have my native language (Swedish) set in Language.

I don't think Swedish is one of the supported translations for Windows Terminal, so it's going to fallback to some other language. If you want that fallback language to be English, you can set that in the Preferred Languages section of the Windows Settings. See the screenshot below where I've got Engelska set as a second preference to Svenska.

[Languages]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4181424%2F209472397-7e198201-af35-4cc0-a855-f46bc15485ae.png&data=05%7C01%7C%7C82d5a67ec1bd4e7f929208dae68718e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638075765153015692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0dkVVPxUQq2%2Fu77TjmMiG6rT%2FrXVndj5ZH46JoOBsY4%3D&reserved=0>

Alternatively, you can set that preference in Windows Terminal itself, as I mentioned above. See the screenshot here: #11157 (comment)<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fterminal%2Fissues%2F11157%23issuecomment-915271804&data=05%7C01%7C%7C82d5a67ec1bd4e7f929208dae68718e4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638075765153015692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zaf0QpfYlcJbingU%2Bq%2FrWwytAvT5Hm%2BQV95RFmct01s%3D&reserved=0>

**Comment by zadjii-msft** [comment]
Glad you were able to figure this out!
