### ISSUE TITLE
Environment variable loading exception

### ISSUE THREAD

**Issue by GuiXie-Null** [microsoft/terminal#14596]
### Windows Terminal version

1.15.2875.0

### Steps to reproduce

When I configured the JAVA_HOME environment variable, Windows Terminal loaded successfully when I opened it for the first time. Windows Terminal prompts me when I open the second window: 
'java' is not an internal or external command, nor is it a runnable program 
Or batch files.

### Expected Behavior

Under normal circumstances, environment variables should not be like this

### Actual Behavior

![EHUCGFRAT8119XG_$@4B5Y3](https://user-images.githubusercontent.com/49875020/209281769-62298d47-755c-4495-905d-65ca7f1a768f.png)

**Comment by zadjii-msft** [comment]
How exactly are you launching the Terminal each time? Through the Start Menu? The File Explorer context menu? The Run dialog? 

We've had some issues in the past (https://github.com/microsoft/terminal/issues/7204#issuecomment-1198228985) where the env vars are seemingly different depending on how the Terminal is launched.
