### ISSUE TITLE
Bug Report: Alt Gr/Option not working?

### ISSUE THREAD

**Issue by elwis** [microsoft/terminal#1459]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.116]
Windows Terminal version (if applicable): 0.2.1715.0

```

# Steps to reproduce

Running swedish Windows and Swedish keyboard, hitting "Alt Gr" to get {[]} characters will not produce it for you.

# Expected behavior

Get the expected charcters

# Actual behavior
Instead of "{", "[", "]", "}" I get "^_", "8","9","0".
However, if I copy them it is the actual charcters that I did expect, they just choose not to show up as it. Sneaky!

**Comment by DanielaE** [comment]
On my German keyboard, I am also missing '\" and '|' (and all other "Alt Gr" characters), rendering the terminal basically useless for many simple tasks.

**Comment by mveril** [comment]
Same problem with french keyboard

**Comment by DHowett-MSFT** [comment]
Please make sure you search before filing a new issue. This is #521.
