### ISSUE TITLE
Show all profiles/shells in 'Open in Terminal' context menu

### ISSUE THREAD

**Issue by tusharsnn** [microsoft/terminal#14597]
# Description of the new feature/enhancement

'Open in Terminal' should show all available profiles/shells using flyout. It only opens the default profile set in the Windows Terminal currently, and user has no way to choose between other profiles/shells from the context menu.

# Proposed technical implementation details (optional)

#### 'New'
![Screenshot_20221223_114519](https://user-images.githubusercontent.com/55626797/209284414-f5789b5e-8cd4-40f2-a901-ad525dd5568f.png)

#### 'Open in Terminal'
![Screenshot_20221223_114535](https://user-images.githubusercontent.com/55626797/209284468-e74aeb30-b058-472c-802d-b44e6ab38966.png)

As shown on the screenshot, adding a secondary flyout like one on the 'New' option to let the user choose which terminal shell they want to open 'here' will give additional flexibility while using the context menu. 
A thing to note here is that opening the default terminal from the context menu might take two clicks instead of just one but IMO it's worth it.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6111  for more discussion.

/dup #6111
