### ISSUE TITLE
Allow for different appearance when running as Administrator

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#14593]
# Description of the new feature/enhancement

Although we have that smallish icon on the top left to remind us that we're running at Admin (Win-X Terminal Admin).  It would be nice if we had the capability of having a different background, font, etc. to have a larger reminder that we're in Admin mode.

# Proposed technical implementation details (optional)

Doesn't have to be in the UI immediately, but I am thinking so that there's not too much duplication we'd have something like
```json
        "list": 
        [
            {
                "backgroundImage": "C:\\Users\\trajano\\Desktop\\terminal-3.jpg",
                "backgroundImageOpacity": 0.51000000000000001,
                "commandline": "C:/Program Files/Git/usr/bin/bash.exe -i -l",
                "guid": "{00000000-0000-0000-ba54-000000000001}",
                "icon": "C:\\Users\\trajano\\OneDrive\\Icons\\shebang.png",
                "name": "Bash",
                "startingDirectory": "%UserProfile%",
                "tabTitle": "..."
                "administratorOverride: {
                  "guid": "{00000000-0000-0000-ba54-000000000001}", // <-- THIS IS NOT ALLOWED

                  // this is an example of a change
                 "backgroundImage": "C:\\Users\\trajano\\Desktop\\terminal-admin.jpg",
                  "name": "Bash In ADMIN BE VERY CAREFUL",

                 // the rest are not needed if they're the same.  However I don't see a technical reason why 
                 // you won't allow changes to even the command line etc even though it will be silly for the user               
                  "backgroundImageOpacity": 0.51000000000000001,
                  "commandline": "C:/Program Files/Git/usr/bin/bash.exe -i -l",
                  "icon": "C:\\Users\\trajano\\OneDrive\\Icons\\shebang.png",
                  "startingDirectory": "%UserProfile%",
             }
            },
```

**Comment by PankajBhojwani** [comment]
Huh, we don't seem to have a pre-existing thread for this so this will be it then!

We have discussed this as a team before and it is something we really want to implement - the problem we are looking to solve is the potential combinatorial explosion of having too many appearance combinations. For example, we currently support a 'default' and an 'unfocused' appearance, if we also support admin appearance we will have 'admin-default' 'admin-unfocused' on top of that. 

And if we want to support even further appearance types in the future (say, 'high contrast mode') then we have 'unfocused-high contrast', 'admin-unfocused-high contrast' ... and so on. Until we figure out a clean solution to that problem we are holding off on adding more appearance config options.

**Comment by j4james** [comment]
See also #3246 and #8311.

**Comment by zadjii-msft** [comment]
Good find!

/dup #3246
/dup #8311
