### ISSUE TITLE
Terminal Crashes when trying to drag a tab

### ISSUE THREAD

**Issue by pain0486** [microsoft/terminal#14595]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Other Software

PowerShell 7.3.0

### Steps to reproduce

Open windows terminal click and drag a tab.

### Expected Behavior

Either 
A) the whole window moves (like when you drag a title bar) or 
B) just the tab moves and you can sort your tabs (potentially move them to their own windows terminal session like you can with browser tabs)

### Actual Behavior

Windows terminal closes

**Comment by zadjii-msft** [comment]
Are you running the Terminal as admin? Or as an admin with LUA disabled? 

We probably need a feedback hub dump to investigate here: /feedback
