### ISSUE TITLE
process exited with code 3221225786 (0xc000013a) after using Ping

### ISSUE THREAD

**Issue by gsly** [microsoft/terminal#14590]
### Windows Terminal version

1.16.3463.0

### Windows build number

10.0.19045.2364

### Other Software

Command Prompt exits with an error if you use the ping command and CTRL-C during it's run.

### Steps to reproduce

1. Open Command Prompt
2. Use Ping to a host
3. CTRL-C during the ping
4. Exit the command prompt

### Expected Behavior

Command Prompt exits

### Actual Behavior

Command Prompt throws error:

[process exited with code 3221225786 (0xc000013a)]

**Comment by elsaco** [comment]
@gsly when you cancel ping the `errorlevel` is set to some value that influences `Profile termination behavior`. Run `echo %errorleve%` after CTRL-C to display it. There are several option for termination and `Close when process exits, fails, or crashes` is the hammer approach!

**Comment by zadjii-msft** [comment]
Yep, this is by design and in the FAQs.
