### ISSUE TITLE
Profile specific actions / keybindings

### ISSUE THREAD

**Issue by ushuz** [microsoft/terminal#14599]
## Description of the new feature/enhancement

Support setting profile-specific actions / keybindings. For example, I only want to override certain keys for WSL, not Powershell.

## Proposed technical implementation details (optional)

Add an `action` section to profile settings.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5790 for more discussion.

/dup #5790
