### ISSUE TITLE
Settings doesn't open reliably when there's no association for .json files

### ISSUE THREAD

**Issue by Mustafa5040** [microsoft/terminal#1460]
When I press the settings on the Windows Terminal, it asks me how I want to open the .json file. So the settings won't open. Please help me

**Comment by Shorotshishir** [comment]
easy solution, u need a text editor. as simple as that. `notepad++` or` vs code` will be perfect for it. your plain old notepad can do the trick too, but it is easier to edit in smarter text editors as it shows the .json in a formated way.

**Comment by hosser** [comment]
Settings doesn't open for me either, but I don't get any kind of prompt. It just does nothing.

**Comment by karolberezicki** [comment]
Make sure that you have set default program for JSON file in Windows. 
I had the same problem, but setting VS Code as default editor for JSON files solved it.

**Comment by JushBJJ** [comment]
For settings, customise the terminal by editing the file "profiles.json" in
`C:\Users\Your_Username\AppData\Local\Packages\Microsoft.WindowsTerminal_<some random characters>\RoamingState\profiles.json`

**Comment by drk-mtr** [comment]
I was having the same issue - thanks for providing the solution.

Might be worth adding a prompt the first time someone attempts to use the `Settings` menu to advise them to check their file associations if it doesn't work? Or maybe as part of the install process if people don't want to clutter the program with these additional checks.

**Comment by hosser** [comment]
> I was having the same issue - thanks for providing the solution.
> 
> Might be worth adding a prompt the first time someone attempts to use the `Settings` menu to advise them to check their file associations if it doesn't work? Or maybe as part of the install process if people don't want to clutter the program with these additional checks.

Yeah - something needs to be done, as new users will have no idea the terminal is trying to open a .json file. I certainly didn't. So I had no reason to check the file handler for JSON files until I read others descriptions of what happens when they click Settings. Some kind of clue as to what the program is trying to do to enable basic troubleshooting would be nice.

**Comment by JushBJJ** [comment]
Agreed, I kinda suggest to automatically open notepad to edit `profiles.json` since its pre-installed in Windows systems and it would be uncommon for a normal user to uninstall it.

**Comment by mubeenpatel99** [comment]
### You can Find the settings manually in the folder:
```C:\Users\<YOUR_USERNAME>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState```

####  You can download these Icons and paste them in the same folder as profile.json for a better look:
[icons and profile.zip](https://github.com/microsoft/terminal/files/3318060/icons.and.profile.zip)

### Snapshot:
![Screenshot (42)](https://user-images.githubusercontent.com/42268754/59979063-4ac37280-9600-11e9-9834-02a10bbb040a.png)

**Comment by drk-mtr** [comment]
@mubeenpatel99 are you able to share the settings.json that you configured in order to get ubuntu to run as a shell please?

I've tried manually pointing at `ubuntu`, `ubuntu.exe` and `C:\Users\MyProfileName\AppData\Local\Microsoft\WindowsApps\ubuntu.exe` instead of `cmd.exe` but no luck so far...

**Comment by Shorotshishir** [comment]
@drk-mtr please refer to this issue #1449 
you will find the correct pattern for the WSL terminal command, for ubuntu it should look like this 
commandline parameter : `wsl.exe -d ubuntu-linux`

**Comment by mubeenpatel99** [comment]
> @mubeenpatel99 are you able to share the settings.json that you configured in order to get ubuntu to run as a shell please?
> 
> I've tried manually pointing at `ubuntu`, `ubuntu.exe` and `C:\Users\MyProfileName\AppData\Local\Microsoft\WindowsApps\ubuntu.exe` instead of `cmd.exe` but no luck so far...
> 
> **Edit:** Please ignore - I've reinstalled and found it's `"commandline" : "wsl.exe -d Ubuntu",`

Yeah great it's working now

**Comment by DHowett-MSFT** [comment]
Re-titled to make this a little more robust.

**Comment by levicki** [comment]
If you change `startingDirectory` value you must use either forward slashes (`/`) or escaped backslashes (`\\`) in the filesystem path or the Terminal will refuse to reload settings due to invalid Json format.

To a front-end developer this might be obvious, but not for regular users.

**Comment by HAWK-Soft** [comment]
> 
> 
> > @mubeenpatel99 are you able to share the settings.json that you configured in order to get ubuntu to run as a shell please?
> > I've tried manually pointing at `ubuntu`, `ubuntu.exe` and `C:\Users\MyProfileName\AppData\Local\Microsoft\WindowsApps\ubuntu.exe` instead of `cmd.exe` but no luck so far...
> > **Edit:** Please ignore - I've reinstalled and found it's `"commandline" : "wsl.exe -d Ubuntu",`
> 
> Yeah great it's working now

I think these links are useful before complete this config file (profiles.json). Thanks for your help guys! (: 

[https://docs.microsoft.com/en-gb/windows/wsl/install-win10](url)
[https://docs.microsoft.com/en-gb/windows/wsl/about](url)

**Comment by metathinker** [comment]
I believe https://github.com/microsoft/terminal/pull/1841 fixes this issue (no .json file editor registered prevents profiles.json from opening).

**Comment by DHowett-MSFT** [comment]
Hey, good catch! Thanks.
