### ISSUE TITLE
Windows 10 Terminal Transparency Not Working

### ISSUE THREAD

**Issue by CatOw** [microsoft/terminal#14602]
As the title suggests, the Windows Terminal Transparency doesn't work for me.

**I'm attaching `DxDiag.txt`**
if missing anything let me know

**What I tried and what I know:**
Transparency works in Windows. As a matter of fact, my taskbar is transparent and blends nicely with the background.
Windows is on Dark Mode for me.
I can change the transparency of PowerShell and CMD.
My start menu is not transparent and I don't know why actually, might be related.

**Certain Registry values that might be related**
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\EnableTransparency = 1`
Turning EnableTransparency to 0 disables transparency for taskbar and everything else.
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\UseOLEDTaskbarTransparency = 1`

**As for the settings.json**
I have default appearance set to acrylic enabled and transparency at 40.

**Important notes**
It actually started when the GPU changed.

[DxDiag.txt](https://github.com/microsoft/terminal/files/10299139/DxDiag.txt)

I couldn't come up with an idea for anything else to append. So once again, if any more data is needed let me know.

**Comment by zadjii-msft** [comment]
> My start menu is not transparent and I don't know why actually, might be related 

Yep I'd say that's definitely related. If Start isn't acrylic, then there's something more fundamental than just the Terminal preventing acrylic from being enabled. I'd file feedback using the Feedback hub, since this doesn't seem to be a Terminal-specific issue. 

Thanks!

**Comment by nappalm** [comment]
Same problem here 🐿️
