### ISSUE TITLE
Can't use win terminal without running it as admin

### ISSUE THREAD

**Issue by syncush** [microsoft/terminal#14608]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044

### Other Software

Git bash
Windows Powershell v1
Command Prompt

### Steps to reproduce

Open windows terminal without admin privileges.

be prompted with the following message

![image](https://user-images.githubusercontent.com/19842756/209553195-75d31ffd-640b-4192-8e89-33b2136ccc65.png)

![image](https://user-images.githubusercontent.com/19842756/209553222-d5dba70d-3f00-4738-b1b2-0838a326abac.png)

![image](https://user-images.githubusercontent.com/19842756/209553236-298a6094-39f9-4f2a-8732-4b0b5abda6e7.png)

### Expected Behavior

Windows terminal to work perfectly with the different terminals without admin privileges.

### Actual Behavior

When running with admin it works

![image](https://user-images.githubusercontent.com/19842756/209553402-3d706b21-7569-4946-8b87-0b63ad110706.png)

Is there any group policy that is preventing me from running the windows terminal without admin?

**Comment by drord9** [comment]
Same for me. 
I tried the solution in #6039 but the path of the power shell, cmd, etc. is already in the `path` environment variable.
I don't want to run as an administrator every time.

```
Edition	Windows 10 Enterprise
Version	22H2
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

Windows Terminal
Version: 1.15.3465.0
```

**Comment by carlos-zamora** [comment]
Do you have any enterprise endpoint protection software installed? The only time we've seen this in the past is when Terminal is impacted by corporate antivirus (especially Cylance and ForcePoint). We think that might be the case here as well.

For now, closing as /dup of #6862
