### ISSUE TITLE
Close Tab (Ctrl+F4)

### ISSUE THREAD

**Issue by theking2** [microsoft/terminal#14615]
# Description of the new feature/enhancement
There is the standard Alt+F4 to close the window and various other Tab manipulating commands but nothing to close the current tab (Ctrl+F4)
# Proposed technical implementation details (optional)
Add command to the palate and assign Ctrl+F4 as the standard key

**Comment by brupelo** [comment]
If you go to settings/actions you should be able to see some available close commands that should help

![image](https://user-images.githubusercontent.com/18058492/210119123-61a71db5-f3e5-46cd-8001-aa800ad09887.png)

Just make sure to assign `ctrl+f4` to the "Close Tab" action, save it and then you'll have the behaviour you're asking for.

Hope that helps.

**Comment by theking2** [comment]
In which version is there a Close Tab action? I wasn't able to locate it.

**Comment by brupelo** [comment]
Using `Version: 1.15.3465.0` over here

**Comment by theking2** [comment]
In the German language version this is missing. Should I file a bug here?

**Comment by theking2** [comment]
It would be called "Registrierkarte schliessen"

**Comment by mklement0** [comment]
@theking2, only _bound_ actions are shown by default in `Settings > Actions`.

`Close tab` / `Registerkarte schließen` is _not_ bound by default, so you need to click `+ Add new` / `Neu hinzufügen` and assign it the desired key chord.

However, note that `Close pane` / `Bereich schließen`  _is_ bound by default, namely to <kbd>Ctrl-Shift-W</kbd>, and for any tab that contains only _one_ pane (which is the default), closing that one pane also closes the entire tab.

**Comment by zadjii-msft** [comment]
Yep, this is all correct. Binding `closePane` is generally preferred over `closeTab`, because it's slightly more versatile like that. Feel free to rebind it to whatever you'd like!
