### ISSUE TITLE
Running Terminal as Administrator gives me this error: the code execution cannot proceed because msvcp140.dll was not found

### ISSUE THREAD

**Issue by siddjain** [microsoft/terminal#14617]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22000.1335

### Steps to reproduce

Simply try to run Terminal as Administrator. In my case I changed the default profile and turned on this option:

<img width="863" alt="run_terminal_as_administrator" src="https://user-images.githubusercontent.com/758321/210002054-08aecc50-f698-43fa-852c-f813bc6d3aac.png">

I then see this error:

<img width="320" alt="terminal_error" src="https://user-images.githubusercontent.com/758321/210002137-253bf648-ade1-4f46-89f9-862bd8928c8c.png">

### Expected Behavior

Either fix this issue or if Terminal cannot run as administrator then remove the option from the settings. **I do have admin privileges on the machine btw.**

### Actual Behavior

error

<img width="320" alt="terminal_error" src="https://user-images.githubusercontent.com/758321/210002394-7d960e8f-d7c4-4e7c-bb18-2440308dfd67.png">

i got more errors after this. it didn't stop there.

**Comment by j4james** [comment]
I think this is probably a duplicate of #14501.

**Comment by zadjii-msft** [comment]
Sure looks like it to me /dup #14501
