### ISSUE TITLE
Terminal tabs are not scrollable and resizable.

### ISSUE THREAD

**Issue by utkkarsh** [microsoft/terminal#1462]
# Environment

Microsoft Windows [Version 10.0.18362.30]

# Steps to reproduce

Click on the (+) button to add tabs to the terminal.

# Expected behaviour

If you have 10 tabs open in the terminal window and suppose you are on the 5th tab so you should be able to scroll to 10th tab to close it.
Tab bar should be able to resize if I open new tabs.
# Actual behavior

I opened 10 tabs in the terminal and being on the 5th tab I am not able to scroll to the 10th tab to close it.
Tab bar not able to shrink its size if I open new tabs.

**Comment by LeeChang-GitHub** [comment]
I also had the same problem. I needed the same effect as the browser. At the same time, the title of the terminal can be edited. Thanks.

**Comment by LeeChang-GitHub** [comment]
![Uploading image.png…]()

**Comment by DHowett-MSFT** [comment]
#857 #597 please search before filing a new issue
