### ISSUE TITLE
"<ctrl> + 'mouse middle button scroll' to scale font-size" configurable

### ISSUE THREAD

**Issue by clor09** [microsoft/terminal#14627]
# Description of the new feature/enhancement
a switch or configurable key for disable/enable `<ctrl> + "mouse middle button scroll"` to scale font size;

i searched through the doc but find no way to disable this action. sometimes this is really annoying on laptop with a touchpad. The ctrl key pressing state seems to keep a little longer after 'keyup', or i may just act too quick. When scroll on touchpad with two fingers after a <ctrl + "any key"> shortcut, it always miss behaving like to scale text when i mean to scroll the screen

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by a couple issues on our repo - please refer to:

/dup #1553 
/dup #11710
