### ISSUE TITLE
Dragging and dropping paths to terminal stops at 16 items

### ISSUE THREAD

**Issue by jiejasonliu** [microsoft/terminal#14628]
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Highlight more than 16 items from an archive (7zip, WinRAR, etc.)
2. Drag and drop highlighted items into terminal

### Expected Behavior

Should write paths equal to the amount of items highlighted

### Actual Behavior

Only writes up to 16 paths

**Comment by jiejasonliu** [comment]
This issue occurs in other UWP and other apps using WinAppSDK.
It appears that the culprit is that `GetStorageItemsAsync()` from the drag event only returns up to 16 items.

Perhaps this is a bug from WinRT?

**Comment by jiejasonliu** [comment]
Makes sense, I'll go ahead and file an issue over there.

> Sure _sounds_ like something outside our control.

Despite this being an external issue, is this something that we want to fix? 
I have a workaround solution that appears to work and can open a PR for.

**Comment by jiejasonliu** [comment]
Upon looking into a little further, it appears the issue only occurs when dragging and dropping from archives (7zip, WinRAR, and others). It works fine if you do it from the native file explorer though.

I can still open a pull request for this edge case unless you're on the side that it isn't worth fixing.

**Comment by DHowett** [comment]
I'd love to see the PR! If it's something we can work around, let's do it. Thanks @jiejasonliu

**Comment by KindDragon** [comment]
Related WindowsAppSDK just for reference https://github.com/microsoft/WindowsAppSDK/issues/3328
