### ISSUE TITLE
Option to set elevate is not available anymore on windows 11 install.

### ISSUE THREAD

**Issue by kurazsiosif** [microsoft/terminal#14624]
### Windows Terminal version

 1.12.10983.0

### Windows build number

10.0.22621.963

### Other Software

OS provisioned for kernel debugging

### Steps to reproduce

for kernel installing I need administrator terminal window and i found it is very difficult to open i this build.
The option to configure it from default profile is not showing up, if i manually edit the profile json file it is ignored.

### Expected Behavior

There should have been option in the default profile to enabled admin by default for all profiles. Or at least per profile, but that is also not available anymore.

### Actual Behavior

cant find any option to open elevated instance of power shell or cmd

**Comment by zadjii-msft** [comment]
Pretty sure that feature wasn't released in 1.12. That was first [released in 1.13](https://github.com/microsoft/terminal/pull/12137). You'll need a newer version of the Terminal 😉

**Comment by kurazsiosif** [comment]
How can i update my default installed WT from windows 11 (windows update says there is nothing to update) ?

    On Tuesday, January 3, 2023 at 01:56:07 PM GMT+2, Mike Griese ***@***.***> wrote:  
 
 


Pretty sure that feature wasn't released in 1.12. That was first released in 1.13. You'll need a newer version of the Terminal 😉

**Comment by zadjii-msft** [comment]
The Terminal is delivered via the Store. You'll need install the update via the store, or by grabbing the `msixbundle` off our Releases page and installing it manually.

**Comment by kurazsiosif** [comment]
Thank you that solved it ! 
Didn't know that the store update needs to be triggered manually and is not included in windows update.
make sense now !
