### ISSUE TITLE
Cannot install Windows Terminal without Windows Defender Firewall

### ISSUE THREAD

**Issue by SimonCahill** [microsoft/terminal#14641]
### Windows Terminal version

1.15.3465.0_x64

### Windows build number

10.0.19044.0

### Other Software

Windows Defender
Appx Installer

### Steps to reproduce

1. Double-click Microsoft.WindowsTerminal*.msixbundle with Windows Defender [Firewall] disabled/unavailable.
2. Wait for installer to reach 88 ~mph~ %
3. ~Profit?~ Receive the error in the *actual behaviour* section.

### Expected Behavior

I expect the installer to not require a firewall; or even if it does to have a fallback handler.
Unless some vital component of the operating system is missing (like the UI libraries or something), the application **should** install.

Instead, unzipping the .msixbundles and executing the Terminal application itself works. So this is an installer bug!

I realise this is (yet another) Windows issue and is only marginally related to Windows Terminal, but maybe you guys have a brainwave I haven't had yet and know a way around this.

### Actual Behavior

The application doesn't install, but instead the installer errors out with the following messages:

## German Error Msg (sorry, can't help that the IT did this):
```
App installation failed with error message: Fehler 0x80073D0A:
Fehler beim Installieren des Pakets "Microsoft.WindowsTerminal_1.15.3465.0_x64__8wekyb3d8bbwe",
da der Firewalldienst nicht ausgeführt wird. Stellen Sie sicher, dass der Firewalldienst aktiviert und gestartet ist. (0x80073d0a)
```

## English Error Translation:
```
App installation failed with error message: Error 0x80073D0A:
Error installing the package "Microsoft.WindowsTerminal.1.15.3465.0_x64__8wekyb3d8bbwe",
because the firewall service is not running. Ensure the firewall service is active and running. (0x80073d0a)
```

Unpacking the .msixbundles and calling the application directly **works**!

**Comment by j4james** [comment]
There's been a previous report of this in #12269. And if you do an internet search for that error number you'll find a bunch of people either complaining about it, or suggesting possible solutions. I'm not sure I'd trust advice from random sites on the internet, though.

But one thing that might be worth trying is `wsreset`, which is supposed to reset the Microsoft Store. That at least is something that's actually suggested on the [Microsoft Store Support](https://support.microsoft.com/en-us/account-billing/i-can-t-find-or-install-an-app-from-microsoft-store-ca530de4-cd19-f728-dae7-7368fab8df4d) site (although they don't mention this issue specifically - it's more like a general purpose fix for apps that fail to install).

**Comment by zadjii-msft** [comment]
Yea, I'm just gonna call this external / by-design. I don't understand why the package catalog would need the Defender service running to authenticate packages, but alas, it does. This isn't unique to the Terminal, this would likely hold for all Store-signed apps.

**Comment by DHowett** [comment]
You might be able to get Terminal installed by using the "preinstallation kit" -- it includes an offline license provisioning file that should obviate the need for the AppX installation service to have internet access.

**Comment by SimonCahill** [comment]
@j4james Thanks for the input. The actual culprit was a Windows update (because of course it was), which somehow managed to completely break/corrupt Defender in such a way that Windows couldn't even find the file/see it as executable.

A complete re-image was the solution.

@DHowett My temporary workaround was to extract the *.msixbundle and the *.appx* package for x64 and simply dump the contents to `%AppData%\windows_terminal` and add that to my `$PATH` variable/add a shortcut to Start.

@zadjii-msft That's fair enough. As long as I brought this to someone's attention I'm fine with that.
To be honest, considering all the data Microsoft is scraping from end-user devices - no matter the configuration - I'm not surprised the installer will phone home and let some obscure server know about it 😉

At least the packages are just .zip-files and can be uncompressed and extracted without the need for the installer. But as I mentioned above, Windows broke itself, so the core issue was that.

Thanks to everyone though!
