### ISSUE TITLE
Ability to select all text in the typable part of the buffer

### ISSUE THREAD

**Issue by Araxeus** [microsoft/terminal#14642]
# Description of the new feature/enhancement

In Powershell when you press <kbd>Ctrl</kbd>+<kbd>A</kbd> it selects the typable part of the buffer
Such a feature can be really useful
![image](https://user-images.githubusercontent.com/78568641/211050017-b994216c-5223-4708-83d5-49bd924a6e8d.png)

# Proposed technical implementation details (optional)

* Keybinding for action (name debatable)

----
Related to https://github.com/microsoft/terminal/issues/1469#issuecomment-1136247434

**Comment by zadjii-msft** [comment]
Hmm. The continuation prompt selection might be **H**ard. But the rest might be doable with the work I'm doing in #4588. I'll merge this in with that, so that I make sure to select the current prompt first.
