### ISSUE TITLE
Guidance: How to open terminal

### ISSUE THREAD

**Issue by bastiW** [microsoft/terminal#1464]
I have downloaded terminal from store https://www.microsoft.com/de-de/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:reviewstab. 

But I don't know how to start it. I tried:
- Win + R, terminal -> Windows cannot find 'terminal'. Make sure you typed the name correctly, and then try again.
- Win + R, conhost -> Opens old cmd
- Win + R, cmd -> opens old cmd

Could you please document on how to open it after installing it from store?

**Comment by bastiW** [comment]
opencon.cmd -> Windows cannot find 'opencon.cmd'. Make sure you typed the name correctly, and then try again.
openconsole.exe -> Windows cannot find 'openconsole.exe'. Make sure you typed the name correctly, and then try again.

**Comment by Kvanrooyen** [comment]
You can open it in the following ways:

• Win + R, wt
• Win + R, cmd, wt
• Click on it from app list in Start Menu

**Comment by bastiW** [comment]
Ok - found the problem. I was still runing Windows Build 1806 (run winver to check it). 

I updated to build 1903 

now it works

**Comment by DHowett-MSFT** [comment]
The store shouldn’t let you do that.
