### ISSUE TITLE
Having terminal open causes 3D applications to stutter

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/terminal#14649]
### Windows Terminal version

1.16.3464.0

### Windows build number

Microsoft Windows [Version 10.0.22621.963]

### Other Software

AMD Graphics Driver ver 22.11.2? I'm not sure who to blame here, Terminal, AMD, or both

### Steps to reproduce

Play a game or do any 3D rendering that is taxing

### Expected Behavior

No Stutter

### Actual Behavior

Stutter, seemingly linked up with any time Terminal refreshes its window contents

**Comment by Masamune3210** [comment]
Like I said in the main message, I am not sure who to blame here. I don't know if AMD has a swap issue in their driver when multiple applications are using acceleration at a time, or if Terminal has the blame due to some inefficiency in something like message handling or being too hasty when handling redraw

**Comment by Masamune3210** [comment]
Issue only seems to occur if Terminal currently is rapidly updating its window contents, having a blank command prompt window open is fine, but running something like rclone in verbose mode and having it spit out stuff causes the stutter to appear

**Comment by lhecker** [comment]
Are you perhaps using a display with variable refresh rate?

**Comment by Masamune3210** [comment]
Yes, but on the other monitor, terminal on one monitor, the game on another monitor. Both supporting FreeSync

**Comment by lhecker** [comment]
Just to be sure, this issue happens with any 3D application for you right?
Does the issue still happen if neither monitor is actively using VRR/FreeSync?

Do you have this setting enabled?
![image](https://user-images.githubusercontent.com/2256941/211207928-847c36e3-7590-42f1-a158-66ab2b3a8b70.png)

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/211209003-c41f6859-7039-4559-9e27-c3b6a073d2e2.png)
I havent tried with FreeSync off, let me check

**Comment by Masamune3210** [comment]
I do not seem to get the issue with FreeSync disabled

**Comment by Masamune3210** [comment]
Looks to be the case, sorry for not searching for dups. My only alternate to the existing issue is having a Terminal window that isn't changing (i.e. a blank Command Prompt window) actually allows things to run at the correct refresh rate, since the blinking cursor only draws when the Terminal is focused

**Comment by zadjii-msft** [comment]
No worries, /dup #649
