### ISSUE TITLE
Terminal crashes/closes/terminates after being idle for a while

### ISSUE THREAD

**Issue by ajhindle** [microsoft/terminal#14655]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22621.0

### Other Software

Ubuntu 20.04.5 LTS
Powershell  5.1.22621.963

### Steps to reproduce

Leave Terminal running idle for 1+ hours.
EDIT:  This can also involve putting the computer to sleep for 1+ hours.

### Expected Behavior

Terminal stays on for as long as I want it to

### Actual Behavior

It shuts down by itself after 1+ hours running idle.

This didn't happen when I first started using Terminal about 18 months ago.  I have upgraded to Windows 11 during that time - is it a coincidence?

The shutdown behaviour is annoying because I didn't tell it to shut down and I lose any work/environment I had running in Terminal.

**Comment by zadjii-msft** [comment]
This sounds a lot like #12513. Can you check your ["Background App Permissions" settings](https://github.com/microsoft/terminal/issues/12513#issuecomment-1369795207)/?

**Comment by clor09** [comment]
> This sounds a lot like #12513. Can you check your ["Background App Permissions" settings](https://github.com/microsoft/terminal/issues/12513#issuecomment-1369795207)/?
> 
> If that doesn't seem to fix it, can you try following the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps? (For more info, see [this link](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)) If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, can you zip that dump up and send it to us, so we can investigate? Thanks!

hello~ I'm facing the same issue, and tried sereval methods from #12513 , but no lucky. i also set up crash dumps and got some .dmp files. em, how can i send the zipped dmp file to you guys~

**Comment by j4james** [comment]
@clor09 There are some instructions on how to send the dmp files here: https://github.com/microsoft/terminal/issues/14025#issuecomment-1372929445.

**Comment by clor09** [comment]
@j4james @zadjii-msft  Thx, i uploaded the dmp file here: https://aka.ms/AAj7lag

**Comment by Skesov** [comment]
Have some problem with: 
Windows 11 22621.1105
Windows Terminal Version: 1.15.3466.0

**Comment by clor09** [comment]
this bug seems being fixed in the lastest update in 10.0.22623.1180 from insider preview(beta channel)

**Comment by ajhindle** [comment]
> This sounds a lot like #12513. Can you check your ["Background App Permissions" settings](https://github.com/microsoft/terminal/issues/12513#issuecomment-1369795207)/?
> 
> If that doesn't seem to fix it, can you try following the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps? (For more info, see [this link](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)) If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, can you zip that dump up and send it to us, so we can investigate? Thanks!

I tried background app permissions and "always on" - it was set to conserve power.
Unfortunately that didn't work.  I will get the dump files.

**Comment by carlos-zamora** [comment]
Thanks for the report. We're tracking this internally with MSFT-42831529.

**Comment by egvijayanand** [comment]
Terminal instance auto terminates when the system goes to sleep. Observed in ver. 1.16.10262.0 Kindly fix this issue at the earliest.

Windows version - 10.0.22621.1194

**Comment by zadjii-msft** [comment]
You know what, we've actually got a better dupe in /dup #12513. That's got links to a pile of internal bugs. Thanks!
