### ISSUE TITLE
Time to time the terminal powershell shows mac like taskbar at the bottom

### ISSUE THREAD

**Issue by Ulrich-Tonmoy** [microsoft/terminal#14659]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22621.0

### Other Software

Powershell 7.3.1
starship 1.11.0
![Terminal](https://user-images.githubusercontent.com/65508234/211635634-69f96825-3698-4cf5-9670-2a01d6d150d9.png)

### Steps to reproduce

just setup the starship config as powershell profile to customize the terminal powershell

### Expected Behavior

Whenever i open the terminal after few seconds macos like taskbar shows at the bottom side of the terminal from time to time
![Terminal](https://user-images.githubusercontent.com/65508234/211636245-b4d05693-76d3-4a06-b0c0-5105365cf58d.png)

### Actual Behavior

Whenever i open the terminal after few seconds macos like taskbar shows at the bottom side of the terminal from time to time

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by Ulrich-Tonmoy** [comment]
> Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

[settings.txt](https://github.com/microsoft/terminal/files/10386152/settings.txt)

**Comment by DHowett** [comment]
Would you mind sharing a copy of `D:\Wallpaper Gif\Matrix (3).gif` as well? Thanks!

**Comment by Ulrich-Tonmoy** [comment]
> Would you mind sharing a copy of `D:\Wallpaper Gif\Matrix (3).gif` as well? Thanks!

![Matrix (3)](https://user-images.githubusercontent.com/65508234/211652606-f84b2f08-a00a-4007-ae91-f50ec39c1c8d.gif)

**Comment by Ulrich-Tonmoy** [comment]
> Would you mind sharing a copy of `D:\Wallpaper Gif\Matrix (3).gif` as well? Thanks!

Sorry i didnt saw that it was the gif problem and i was also using similar gif of another pc so i got confused that it was caused by starship configuration

**Comment by DHowett** [comment]
Thanks for following up! 😄

**Comment by Ulrich-Tonmoy** [comment]
> Thanks for following up! 😄

I learned one thing for sure never use same background on more than one place.
Thanks for the quick Solution
