### ISSUE TITLE
0xc0000142 when launching as admin

### ISSUE THREAD

**Issue by lab313ru** [microsoft/terminal#14674]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22621.963

### Steps to reproduce

1. Open Terminal as usual
2. Click at the Command Prompt while holding Ctrl (to launch as Admin)
3. UAC will ask for user and password, enter its creds
4. `0xc0000142` error window will be shown

### Actual Behavior

No admin console will appear, `0xc0000142` error window will be shown

**Comment by zadjii-msft** [comment]
Are you running the Terminal elevated as the same user that you're currently logged in as? If not, is the Terminal installed for the other user? 

Does running the Terminal elevated "normally" (like by right clicking on the taskbar) work/?

**Comment by lab313ru** [comment]
Yes, I'm running the Terminal as a current user.
Launching the Terminal as Admin (by rightclicking) asks for creds, but relaunches and asks for creds again. After that it closes at all with the following message:
"_The application cannot be started for the target user.  Please login as the user and explicitly install this package."_

**Comment by zadjii-msft** [comment]
Well, that error message seems to answer the question - you'll need to make sure to install the Terminal for the other user as well.

**Comment by lab313ru** [comment]
How can I even install the Terminal for another user?

**Comment by bogdan-patraucean** [comment]
@zadjii-msft which other user?
