### ISSUE TITLE
Pressing alt+anything makes screen readers read the prompt, plus the current line.

### ISSUE THREAD

**Issue by TheQuinbox** [microsoft/terminal#14685]
Type: Accessibility, bug.
Screen reader: NVDA.
If I'm in Windows Terminal, and press, for example, Alt+B, my prompt gets reread, as well as the current line. This happens even if dynamic content change reporting is off in NVDA. One place where this comes up is when pressing Alt+B and Alt+F for previous and next word. I hear my prompt again before I hear the word spoken, which is horribly inefficient.

**Comment by zadjii-msft** [comment]
Which shell are you using in the Terminal? CMD, PowerShell, bash, zsh...?

Which version of NVDA are you using?

Which version of Terminal/?

**Comment by TheQuinbox** [comment]
HI,
It happens in both WSL and CMD (I haven't tried anything else).
NVDA version doesn't seem to matter. I've tried 2022.3, 2022.4, and the latest alpha, all of them do it.
Windows Terminal 1.15.3466.0

**Comment by TheQuinbox** [comment]
Hi,
After some further testing, this doesn't happen with Narrator or JAWS. Its possible this is a bug in NVDA, or perhaps JAWS and Narrator are doing something specific to work around it. It also happens in Powershell, to add onto my earlier comment.

**Comment by carlos-zamora** [comment]
@codeofdusk thoughts?

**Comment by zersiax** [comment]
I see this issue has been quiet for over 15 (?!) months. Does this still occur and are we any closer to a fix?

**Comment by lhecker** [comment]
I just tested this in cmd and it indeed doesn't seem to happen anymore. Thanks!
