### ISSUE TITLE
GDB's TUI mode changes Terminal's colors even after exiting GDB

### ISSUE THREAD

**Issue by phil-blain** [microsoft/terminal#14680]
### Windows Terminal version

1.15.3465.0 (also checked with Preview == 1.16.3463.0)

### Windows build number

Microsoft Windows [version 10.0.19042.2251]

### Other Software

- GDB: `GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1` (also happens with GDB 10.3 and above)
- Ubuntu (in WSL): `Ubuntu 22.04.1 LTS` (also happens with other distros, but this one has a recent enough version of GDB in their repositories)
- WSL: Inbox
- SSH: `OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3`

### Steps to reproduce

Hi ! While working on a very small patch to GDB's Pygments support for source code highlighting (see `set style sources` in [the GDB documentation](https://sourceware.org/gdb/onlinedocs/gdb/Output-Styling.html), this works with GDB 10.3 and newer), I came across what I _think_ might be a bug in the Terminal.

Basically, if I slightly modify GDB's initialization of Pygments' [`TerminalFormatter`](https://pygments.org/docs/formatters/#TerminalFormatter), so that its color theme is well suited to a black background, then upon opening and closing the [GDB TUI interface](https://sourceware.org/gdb/onlinedocs/gdb/TUI.html) (which uses `curses`), and exiting GDB, the colors of the terminal are changed, and this persists even when WSL is closed.

Here are complete reproduction steps, starting with installing a clean Ubuntu 22 WSL instance (I'm running this in Windows PowerShell in the Terminal):

~~~bash
# Download the WSL Ubuntu 22 image, import it and enter it
curl.exe -SsLO https://cloud-images.ubuntu.com/wsl/jammy/current/ubuntu-jammy-wsl-amd64-wsl.rootfs.tar.gz
wsl --import u22 ./u22 ./ubuntu-jammy-wsl-amd64-wsl.rootfs.tar.gz
wsl -d u22 --cd ~ # Notice with the 'Campbell' theme, 'wsl' is in yellow, '-d' and '--cd' are in grey
# install GDB, Pygments and GCC
apt update
apt install -y gdb python3-pygments gcc
# Create and compile an example executable
cat << EOF > hello.c
#include <stdio.h>
int main() {
   // printf() displays the string inside quotation
   printf("Hello, World!");
   return 0;
}
EOF
gcc -g -o hello hello.c
# Patch GDB's Pygments initialization
cat << EOF > styling.py.patch
--- /usr/share/gdb/python/gdb/styling-orig.py   2023-01-03 19:19:20.983004000 -0500
+++ /usr/share/gdb/python/gdb/styling.py        2023-01-03 19:19:45.743004000 -0500
@@ -25,7 +25,7 @@
         # Don't want any errors.
         try:
             lexer = lexers.get_lexer_for_filename(filename, stripnl=False)
-            formatter = formatters.TerminalFormatter()
+            formatter = formatters.TerminalFormatter(bg='dark')
             return highlight(contents, lexer, formatter).encode(
                 gdb.host_charset(), "backslashreplace"
             )
EOF
patch /usr/share/gdb/python/gdb/styling.py styling.py.patch
# Show some colors 
ls /
# Reproduce
gdb -q -ex  'maint set gnu-source-highlight enabled off' -ex 'tui enable' -ex exit hello
# notice the color of `/init` showed by the `ls` call above changed
# exit WSL
exit
# Back in PowerShell, notice the automatic coloring of the command line is also affected
PS C:\Users\me>  wsl -d u22 --cd ~   # notice now 'wsl' is in blue and '-d' and '--cd' in cyan
~~~

A few notes:
- This also reproduces in Conhost
- This also reproduces on remote Ubuntu/RHEL systems (not WSL) that I access from PowerShell running in the Terminal, via `OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3`
- When accessing these remote systems via a remote desktop software instead, none of the Linux terminal I tried have this issue (Konsole, gnome-terminal, xterm)
- This also happens with `/usr/bin/gdb` from the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases/latest) (but not with their `/mingw64/bin/gdb`), running in the Terminal (but not running in `git-bash.exe`, which uses Mintty). If ever you want to try that, the file to patch is `__init__.py` instead of `styling.py`, since this is GDB 11.1 / 11.2.
- This does not happen in MobaXterm (in a WSL session running the same steps as above)

### Expected Behavior

The colors of lines shown prior to executing GDB, and after exiting GDB, are not affected by my patch to GDB's Pygments initialization.

Here is what it looks like (Campbell theme) when I do not run the `gdb` invocation above, run `ls`, exit WSL and then type `wsl ...`:
![image](https://user-images.githubusercontent.com/44212482/212481065-1a73e119-66c3-4fbe-820b-8302cec1f9a3.png)

### Actual Behavior

Colors of lines shown prior to executing GDB, and after exiting GDB, are changed.

Here is what it looks like (Campbell theme) when I run the `gdb` invocation above, run `ls`, exit WSL and then type `wsl ...`:
![image](https://user-images.githubusercontent.com/44212482/212481197-40a0210e-58d2-43d7-a235-5058e11750db.png)

Note `/init` is a slightly different color, and the `wsl` command in PowerShell uses completely different colors.

---

P.S. I don't know the first thing about curses so I'm sorry if I couldn't come up with a more minimalistic reproducer...

**Comment by 237dmitry** [comment]
> and the wsl command in PowerShell uses completely different colors.

Configure as you want:
```
Get-PSReadlineOption
Set-PSReadlineOption

$PSStyle   # in 7+
$Host.PrivateData
```

**Comment by j4james** [comment]
This is just a guess, but if it's changing the palette, then I suspect it's using the `rs1` or `oc` capabilities to restore the palette on exit, and that relies on the `OSC 104` sequence which Windows Terminal doesn't yet support (see #3719).

**Comment by zadjii-msft** [comment]
Yea, that would be my gut feel too. Hard to say for sure, but I'd be inclined to mark this as a dupe. 

I dunno if you could just patch those entries out of your termcap manually, and have GDB fall back to using something else. My linux-fu is a little rusty in that regard. And I don't think we pass those sequenes through to the Terminal right now, so logging from the debug tap wouldn't be helpful either...

**Comment by DHowett** [comment]
@phil-blain Thanks for the report!

Can you run `script`, and then reproduce the issue? It should produce a document named `typescript` that contains the raw output from gdb that we're receiving in the Terminal. I'd be interested in seeing that document. That'll help us narrow down whether it's #3719 or another issue.

**Comment by phil-blain** [comment]
Sure! Here it is (I only ran the `gdb` command in my reproducer, after having patched `styling.py` as mentionned):
[typescript_bg-dark.txt](https://github.com/microsoft/terminal/files/10457968/typescript_bg-dark.txt)

I also removed my patch to `styling.py` and re-ran `script`, for comparison purposes: 
[typescript_orig.txt](https://github.com/microsoft/terminal/files/10457977/typescript_orig.txt)

Let me know if you'd like me to test other stuff, I'm really happy to help :)

**Comment by zadjii-msft** [comment]
Yep, that's PERFECT!

Near the end, there's a 
```
[47d[39;49m]104 [71;1H[?1049l[23;0;0t
```

which looks like it'd confirm the thesis here. Thanks!

/dup #3719

**Comment by phil-blain** [comment]
OK, thanks for confirming! I'll subscribe to #3719 then!

Just to further confirm, I learned I could use `teseq` to transform the `script` output to be human readable, and here is the diff of the output from the vanilla GDB (vanilla `styling.py`) vs GDB with my modification (patched `styling.py`):
~~~diff
--- /mnt/wsl/teseq_orig.txt	2023-01-19 20:17:04.006634900 -0500
+++ /mnt/wsl/teseq_bg-dark.txt	2023-01-19 20:17:04.006634900 -0500
@@ -1,4 +1,4 @@
-|Script started on 2023-01-19 10:00:51-05:00 [TERM="xterm-256color" TTY="/de|-
+|Script started on 2023-01-19 09:57:51-05:00 [TERM="xterm-256color" TTY="/de|-
 -|v/pts/1" COLUMNS="280" LINES="71"]|.
 : Esc [ ? 2004 h
 & SM: SET MODE (private params)
@@ -2437,6 +2437,26 @@
 : Esc [ 48 d
 & VPA: LINE POSITION ABSOLUTE
 " Move the cursor to line 48.
+: Esc ]
+& OSC: OPERATING SYSTEM COMMAND
+|4;8;rgb:00/FF/FF|
+: Esc \
+& ST: STRING TERMINATOR
+: Esc ]
+& OSC: OPERATING SYSTEM COMMAND
+|4;9;rgb:7E/7E/7E|
+: Esc \
+& ST: STRING TERMINATOR
+: Esc ]
+& OSC: OPERATING SYSTEM COMMAND
+|4;10;rgb:00/FF/00|
+: Esc \
+& ST: STRING TERMINATOR
+: Esc ]
+& OSC: OPERATING SYSTEM COMMAND
+|4;11;rgb:5B/5B/FF|
+: Esc \
+& ST: STRING TERMINATOR
 : Esc [ H
 & CUP: CURSOR POSITION
 " Move the cursor to line 1, column 1.
@@ -2538,17 +2558,17 @@
 : Esc [ 0 m
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
-: Esc [ 36 m
+: Esc [ 90 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color cyan.
+" (Xterm) Set foreground color gray.
 |int|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
-: Esc [ 32 m
+: Esc [ 92 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color green.
+" (Xterm) Set foreground color bright green.
 |main|
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -2560,9 +2580,9 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |()|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -2648,9 +2668,9 @@
 : Esc [ 0 m
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   // printf() displays the string inside quotation|
 : Esc [ 280 G
 & CHA: CURSOR CHARACTER ABSOLUTE
@@ -2726,9 +2746,9 @@
 : Esc [ 0 m
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   |
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -2828,21 +2848,21 @@
 : Esc [ 0 m
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   |
-: Esc [ 34 m
+: Esc [ 93 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color blue.
+" (Xterm) Set foreground color bright yellow.
 |return|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
-: Esc [ 34 m
+: Esc [ 93 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color blue.
+" (Xterm) Set foreground color bright yellow.
 |0|
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -5486,17 +5506,17 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |2  |
-: Esc [ 36 m
+: Esc [ 90 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color cyan.
+" (Xterm) Set foreground color gray.
 |int|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
-: Esc [ 32 m
+: Esc [ 92 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color green.
+" (Xterm) Set foreground color bright green.
 |main|
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -5508,9 +5528,9 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |()|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -5603,9 +5623,9 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |3  |
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   // printf() displays the string inside quotation|
 : Esc [ 280 G
 & CHA: CURSOR CHARACTER ABSOLUTE
@@ -5688,9 +5708,9 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |4  |
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   |
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -5797,21 +5817,21 @@
 & SGR: SELECT GRAPHIC RENDITION
 " Clear graphic rendition to defaults.
 |5  |
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 |   |
-: Esc [ 34 m
+: Esc [ 93 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color blue.
+" (Xterm) Set foreground color bright yellow.
 |return|
-: Esc [ 37 m
+: Esc [ 91 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color white.
+" (Xterm) Set foreground color bright red.
 | |
-: Esc [ 34 m
+: Esc [ 93 m
 & SGR: SELECT GRAPHIC RENDITION
-" Set foreground color blue.
+" (Xterm) Set foreground color bright yellow.
 |0|
 : Esc [ 39 m
 & SGR: SELECT GRAPHIC RENDITION
@@ -9161,6 +9181,14 @@
 : Esc [ 47 d
 & VPA: LINE POSITION ABSOLUTE
 " Move the cursor to line 47.
+: Esc [ 39 ; 49 m
+& SGR: SELECT GRAPHIC RENDITION
+" Set foreground color default.
+" Set background color default.
+: Esc ]
+& OSC: OPERATING SYSTEM COMMAND
+|104|
+. BEL/^G
 : Esc [ 71 ; 1 H
 & CUP: CURSOR POSITION
 " Move the cursor to line 71, column 1.
@@ -9184,4 +9212,4 @@
 . CR/^M CR/^M LF/^J
 |exit|
 . CR/^M LF/^J LF/^J
-|Script done on 2023-01-19 10:01:08-05:00 [COMMAND_EXIT_CODE="0"]|.
+|Script done on 2023-01-19 09:57:58-05:00 [COMMAND_EXIT_CODE="0"]|.
~~~
