### ISSUE TITLE
wt crashes when using Japanese characters

### ISSUE THREAD

**Issue by dogatana** [microsoft/terminal#14689]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19044.2251

### Steps to reproduce

This frequently happens in various situations, but you can reproduce 100% with the following steps.

1. open Windows Terminal with command prompt
2. enter "cd 評価機" and press enter
3. Windows closes in a few seconds

* I'm using wt on Japanese Windows
* code page is 932
* "評価機" is "\u8a55\u4fa1\u6a5f"
* This happens every time

![capture](https://user-images.githubusercontent.com/12756480/212806842-e27703df-23ff-4f33-8efa-eae22976ae43.png)

### Expected Behavior

wt does not crash.

### Actual Behavior

* wt window closes (with above stapes)
* wt window does not respond

**Comment by carlos-zamora** [comment]
Yeah, I'm gonna /dup #14349

**Comment by dogatana** [comment]
Hello.
Thank you for your reply.
I should have searched other issues well before posting a new issue.😅

Anyway, I installed 1.14.2281.0 and it works fine now.

**Comment by DHowett** [comment]
Hmmmmm that's a new data point! We should re-evaluate this.

**Comment by zadjii-msft** [comment]
@DHowett _is that though_? OP in the duped thread mentioned as much: https://github.com/microsoft/terminal/issues/14349#issuecomment-1320210063. So I'd be even _more_ inclined to call it a dupe, honestly
