### ISSUE TITLE
Bug Report: Invalid string for Icon in profile causes a crash

### ISSUE THREAD

**Issue by Cazzar** [microsoft/terminal#1468]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Create a profile in Terminals `profiles.json` with an empty string as the `icon` option.

Example profile:
```json
        {
            "closeOnExit" : true,
            "commandline" : "cmd",
            "cursorShape" : "bar",
            "guid" : "{3e9d9e33-52e5-496b-b999-178b0cdc0f86}",
            "icon" : null,
            "name" : "Example"
        }
```

# Expected behavior

When an empty string is provided, it should take the same path if the icon value was null or invalid falling back to no icon at all.

# Actual behavior

This will cause terminal to crash if open once `profiles.json` is saved, and subsequently crash on launch.

**Comment by DHowett-MSFT** [comment]
When we fix this, let's also expand environment variables.
