### ISSUE TITLE
brightBlack and black color values from Solarized Dark Color Scheme are swapped

### ISSUE THREAD

**Issue by nachopitt** [microsoft/terminal#14684]
### Windows Terminal version

1.15.3465.0

### Other Software

VSCode 1.74.2 with Solarized Dark Color Theme selected
vim 8.1.2262 (inside WSL2)
colortest-256

### Steps to reproduce

According to the colors table in https://en.wikipedia.org/wiki/Solarized

![image](https://user-images.githubusercontent.com/12923928/212559095-e05ff8f7-6954-4abe-abd9-c05ad49b1938.png)

the Solarized Dark Color Scheme default values should be
**black = #073642**
**brBlack = #002b36**

In VSCode Terminal running in WSL2: Ubuntu-20.04 the color schema seems to be correct. But running the same WSL2 Distro but this time in Windows Terminal, the black and brBlack colors are swapped.

You can visually confirm this by running the colortest-256 test application on both environments:

VSCode Terminal:
![image](https://user-images.githubusercontent.com/12923928/212560083-55c18a21-5bf5-4248-9802-f2bc8100acdd.png)

Windows Terminal:
![image](https://user-images.githubusercontent.com/12923928/212560124-d419e777-845f-4ba5-900a-3e9673750af0.png)

### Expected Behavior

Both VSCode and Windows Terminal should be able to reproduce the same colors when selecting the same Color Theme/Schema (In this case, Solarized Dark).

I know this can be easily solved at "user configuration" level, but it would be better to have the correct values by default.

### Actual Behavior

By using vim, the color swap effect is more noticeable 

VSCode Terminal
![image](https://user-images.githubusercontent.com/12923928/212560200-8f61f090-1413-459e-bb84-1202d926daf1.png)

Windows Terminal
![image](https://user-images.githubusercontent.com/12923928/212560170-e84ccee5-d7e5-4132-92b2-404610fa9fca.png)

**Comment by 237dmitry** [comment]
> the Solarized Dark Color Scheme default values should be
black = #073642
brBlack = #002b36

They are the same as you want:
![Screenshot 2023-01-15 231013](https://user-images.githubusercontent.com/78153320/212564797-29baf5d1-6e8e-4f1d-89f3-7652729d4c85.png)

**Comment by j4james** [comment]
The _black_ and _brightBlack_ colors were deliberately swapped in PR #6985 to try and cut down on the constant stream of bug reports we were receiving from people using the Solarized color schemes, because the default mapping tends to produce color combinations that are invisible.

**Comment by zadjii-msft** [comment]
### [DAYS SINCE I'VE REGRETTED SHIPPING SOLARIZED: ~~195~~ 0](https://github.com/microsoft/terminal/issues/13383#issuecomment-1174875973)


Thanks for the callback @j4james, I totally forgot about that PR. I'll concur, this is by design.
