### ISSUE TITLE
[1.17 Bug Bash] Color Schemes page rejuv bug bash feedback 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14693]
- [ ] Colors expander animates every time on navigation to the scheme page 
- [x] [Win10] when using keyboard to pick a list view item, the background becomes blue. Doesn't repro on Win11 though. 

commit SHA: https://github.com/microsoft/terminal/commit/3034d01c5bdcbfbf17493b6bed0e0db301ed4a0d

**Comment by zadjii-msft** [comment]
I would be inclined to call the second one blocking, but the first not blocking. Thoughts @PankajBhojwani?

**Comment by PankajBhojwani** [comment]
That works for me!

**Comment by layerkugou** [comment]
good  thankyou

**Comment by zadjii-msft** [comment]
> **Note**: discussion

All that's left in here is:

> Colors expander animates every time on navigation to the scheme page

An I'm tempted to say that's _not that bad_ and just close this. Either that, or punt to the backlog forever. Thoughts?

**Comment by zadjii-msft** [comment]
It is _not that bad_
