### ISSUE TITLE
[1.17 Bug Bash] Cannot close color scheme combo box by clicking outside of it

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14692]
In Profiles -> Appearance, open the color scheme selector dropdown. Cannot close the dropdown by clicking outside of it for some reason (the other combo boxes work though, so not sure what's going on with this one) 

commit SHA: https://github.com/microsoft/terminal/commit/3034d01c5bdcbfbf17493b6bed0e0db301ed4a0d

**Comment by carlos-zamora** [comment]
Probably introduced by https://github.com/microsoft/terminal/pull/14587

**Comment by DHowett** [comment]
This is just another manifestation of a xaml islands bug, honestly...

**Comment by zadjii-msft** [comment]
10000% this is. There's dupes all over the place for this. 


Yea, this is unfortunately due to a bug in WinUI itself. We're tracking this on our side in #8769, and the upstream bug is microsoft/microsoft-ui-xaml#3961.

> Appearance -> Open 'Color scheme' dropdown -> Cannot dismiss the dropdown by clicking somewhere else
> * Moved to Light-dismiss doesn't work on ComboBox in XAML Islands [microsoft/microsoft-ui-xaml#3961](https://github.com/microsoft/microsoft-ui-xaml/issues/3961)



/dup #8769
