### ISSUE TITLE
Ability to select/copy all the text in the session

### ISSUE THREAD

**Issue by mrmlnc** [microsoft/terminal#1469]
# Summary of the new feature/enhancement

Sometimes there are situations when you need to select/copy all the text in the session.

> ConEmu has such functionality (`Menu` → `Edit` → `Copy All`).

# Proposed technical implementation details (optional)

* Keybinding for action `Select All Text`.

May intersect with #715.

**Comment by carlos-zamora** [comment]
I should add this to the #4993 scenario.

**Comment by swinder0161** [comment]
@carlos-zamora what is the plan for this feature? Looks like an important feature.
Select by mouse/trackpad works. Adding by keyboard short cut would be easy to use.

**Comment by a8nJ** [comment]
https://github.com/microsoft/terminal/issues/5886

**Comment by theswordsmahin** [comment]
For what its worth and to whomever finds this useful, if you zoom out really far with ctrl + scroll wheel highlighting the complete buffer is much less painful even for relatively long histories. Not ideal of course, workable.

**Comment by sba923** [comment]
Make sure one can choose between plain text and formatted text e.g. with colors. MobaXterm supports saving as RTF, preserving formatting.

**Comment by DHowett** [comment]
We already support RTF and HTML copy, @sba923 :)

**Comment by sba923** [comment]
Typing my comment, on my phone, I kinda remembered reading about this somewhere... 😝 I promise I will check out the docs first thing in the morning 😜

**Comment by sba923** [comment]
> We already support RTF and HTML copy, @sba923 :)

I know, but you can't choose dynamically.

You have to define this in the settings. So it's either "always formatted" or "always plain text."

Being able to choose between formatted copy or unformatted copy e.g. by using two different key bindings would be nice.

Or maybe the choice should be at _paste_ time, not at _copy_ time. (I know, one day Win+V will allow pasting the plain-text version of whatever's on the clipboard. But this is not yet for corporate systems running non-Insider Windows 10 builds 😉).

**Comment by DHowett** [comment]
> Or maybe the choice should be at paste time, not at copy time. 

That's completely up to the app _reading_ the clipboard. Can't do anything about that.

> Being able to choose between formatted copy or unformatted copy e.g. by using two different key bindings would be nice.

You mean like...

```json
{ "command": { "action": "copy", "copyFormatting": "rtf" }, "keys": "ctrl+shift+r" },
{ "command": { "action": "copy", "copyFormatting": "html" }, "keys": "ctrl+shift+h" },
{ "command": { "action": "copy", "copyFormatting": ["html", "rtf"] }, "keys": "ctrl+win+alt+shift+h" },
```

? From the [docs for the copy action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#copy).

**Comment by sba923** [comment]
> > Or maybe the choice should be at paste time, not at copy time.
> 
> That's completely up to the app _reading_ the clipboard. Can't do anything about that.


I know. It's too bad too many apps don't provide a way to choose between _plain-text_ paste and _formatted_ paste.

I paste tons of stuff into Teams, from various sources like VScode and Windows Terminal, and I often don't get what I'd expect. 

My current workaround is to first rewrite the clipboard as plain-text-only with some one-liner, such as this running in a WSL2 tab in Windows Terminal 😉

```none
pwsh.exe -noprofile -c Get-ClipboardText | fold -w80 | clip.exe
```

(this also tackles a Teams issue with the lack of line-wrapping but that's another issue altogether)

> 
> > Being able to choose between formatted copy or unformatted copy e.g. by using two different key bindings would be nice.
> 
> You mean like...
> 
> ```json
> { "command": { "action": "copy", "copyFormatting": "rtf" }, "keys": "ctrl+shift+r" },
> { "command": { "action": "copy", "copyFormatting": "html" }, "keys": "ctrl+shift+h" },
> { "command": { "action": "copy", "copyFormatting": ["html", "rtf"] }, "keys": "ctrl+win+alt+shift+h" },
> ```
> 
> ? From the [docs for the copy action](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#copy).

Exactly. _[blushing mode on]_ My bad for not RTFM. _[blushing mode off]_. I'll try defining a "copy as plain text" keybinding and see whether my muscle memory can be trained to using _that_.

**Comment by gyorokpeter** [comment]
Leaving the text format aside, what is the status of being able to copy all text to the clipboard? Since we just got the ability to change the language to English, I can now actually read the menu options and in the "Command Palette" window there is nothing that is related to selecting text. Ctrl+A just inserts ```^A``` instead of selecting the text.
This is a major blocker because I might have a program that spits out dozens of screens worth of output and I want to search for the first error in the output (since usually a single error triggers a cascade of error messages, checking the last one is useless).

**Comment by mloskot** [comment]
@gyorokpeter 
> I might have a program that spits out dozens of screens worth of output and I want to search for the first error in the output

https://docs.microsoft.com/en-us/windows/terminal/search

**Comment by ohadschn** [comment]
> @gyorokpeter
> 
> > I might have a program that spits out dozens of screens worth of output and I want to search for the first error in the output
> 
> https://docs.microsoft.com/en-us/windows/terminal/search

Unless you want wildcard search, regular expression search, find all, count, match whole word, find and replace, mark line and a million other things you'll never have inside a terminal...

One common scenario is using a command that dumps a huge JSON on the screen and you want to copy it over for further processing and formatting (yes, you can use `stdout` redirect but sometimes you forget, maybe you want to see the output first before saving it, etc).

**Comment by PolarGoose** [comment]
I have found a workaround to select all text:
1. Scroll to the beginning of the console window `Ctrl+Shift+Home`
2. Start selecting text by holding left mouse button
3. While holding left mouse button press `Ctrl+Shift+End`, it will move the cursor to the bottom of the window and all console's text will be selected
4. Release left mouse button
5. Press `Ctrl+C` to copy the text

**Comment by Araxeus** [comment]
FYI `ctrl`+`a` works if the tab is powershell but not if its cmd

**Comment by MartinDevillers** [comment]
I probably have a silly workflow, but I just wanted to echo that for me "Select All" (<kbd>Ctrl</kbd>+<kbd>A</kbd>) and "Copy" (<kbd>Ctrl</kbd>+<kbd>C</kbd>) console output would be a pretty sweet feature to have.

**Comment by Menelion** [comment]
Dear devs, could you please implement this? As a blind developer I'm not able to use the mouse at all and, as it seems, there is no way of selecting text in Windows Terminal using the keyboard only. Otherwise, a great app, thank you.

**Comment by Araxeus** [comment]
Sorry but this is super unhelpful, it selects all the text in the prompt including the beginning
```
Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.
```

How about the ability to just select the current writable buffer??
