### ISSUE TITLE
TextBuffer::ResizeTraditional may leak stale pointers

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#14696]
The catch clause will allow `BufferAllocator` to be destroyed while the `ROW`s in `_storage` continue to reference its memory. The solution is to refactor `ROW::Resize` from being a mutating function over to allocating a new `_storage` vector and copying all rows over. That way the `TextBuffer` is only mutated once at the end, long after all throwing code has finished executing.

**Comment by zadjii-msft** [comment]
@lhecker was this closed in #15105?

**Comment by lhecker** [comment]
Oh, yes, thank you!
