### ISSUE TITLE
Bug:Windows Terminal hide into the taskbar incorrectly

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [microsoft/terminal#14703]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.25276.1000

### Other Software

none

### Steps to reproduce

Just minimize Windows Terminal (but **NOT elevated**, i don't know why...)

### Expected Behavior

Show nothing but Windows Terminal Window only

### Actual Behavior

a strange white point in the corner(not minimized)
<img width="982" alt="image" src="https://user-images.githubusercontent.com/62493399/213332245-d747e441-ebaf-43c4-af34-2031c636d21d.png">

white boxes(minimized)
![image](https://user-images.githubusercontent.com/62493399/213332646-8f36251c-1d4b-4bd8-93c7-e40a0f0d0544.png) 

and the white box is similar to this
![image](https://user-images.githubusercontent.com/62493399/213334936-b3972e16-7727-4520-ad17-eebb981f0c8f.png)

**Comment by zadjii-msft** [comment]
Are you using any other software to control the appearance of windows? Something like mica for everyone/?

**Comment by CommandPrompt-Wang** [comment]
@zadjii-msft
Ahh...Yes
thanks for reminding me. :-)

**Comment by zadjii-msft** [comment]
Thanks for confirming! We've had a couple issues like this posted in the past - they all seem to be caused by Mica for Everyone. On the bright side, we're adding official Mica support to the Terminal in 1.17, so look forward to that!
