### ISSUE TITLE
Moving tabs

### ISSUE THREAD

**Issue by KomarDL** [microsoft/terminal#14707]
# Description of the new feature/enhancement

Add functionality that will allow move opened tabs. I think it will useful for many users. Did i missed it or it doesn't implemented yet?

# Proposed technical implementation details (optional)

I'm new user of wt and i never saw it sources. If someone will help (points the right way) i can try to implement this feature if it doesn't implemented.

**Comment by zadjii-msft** [comment]
You already can move tabs _within_ a window.../? Did you mean dragging tabs to create a new window (tracked in #1256)? Or are you possibly running as Administrator, which also disables tab drag/drop (see #6661 for more details)?

**Comment by KomarDL** [comment]
Thanks for you fast feedback. Yes, my problem about #6661. I didn't know that this could take an affect
