### ISSUE TITLE
Quake Mode - Close on focus loss

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/terminal#14705]
# Description of the new feature/enhancement

Usually when I want to use quake mode i only want to open the terminal to type a short command or two. I don't want to rehit the key combination to close it. Any click outside the terminal should just close it (=when its losing focus) because when I am not actively working in the terminal it is in the way especially on small screens.
ConEmu has this feature and it really helps 

# Proposed technical implementation details (optional)

Setting: Close Quake window when it looses focus

**Comment by zadjii-msft** [comment]
Do you want _close_ on focus loss, or would _minimize_/_hide_ on focus loss accomplish the same thing for you/? There was #10660, which resulted in the `autoHideWindow` setting in 1.16. That'll apply to all windows, not just the quake window[1], but I bet that'll accomplish what you're looking for. 


[1]: making that only apply to the \_quake window is tracked in #9992

**Comment by Fuzzyma** [comment]
Hiding is what i need. So i guess #10660 is what i want :). I tried it and it seems to work. I couldnzt find the setting in the UI so I added it directly to the json.

Thank you!

**Comment by Fuzzyma** [comment]
// EDIT: It did not resolve my issue but thats because I am on 1.15. So I just have to be patient for a bit :)
