### ISSUE TITLE
Don't work Esc+key in WSL

### ISSUE THREAD

**Issue by Nill-R** [microsoft/terminal#1471]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

1. Launch Midnight Commander in WSL
2. Install mc(`sudo apt update; sudo apt -y install mc`) 
3. Run mc(type `mc` and press Enter)
4. On any file in mc press Esc+Enter and see nothing. In normal Esc+Enter type file name to subshell. Or press Esc+N(1…0) in normal it must work as F1…F10, but in Windows Terminal it type 1…0 to subshell

**Comment by DHowett-MSFT** [comment]
Probably same as #1295
