### ISSUE TITLE
"copy on select" doesn't work good

### ISSUE THREAD

**Issue by ozinka** [microsoft/terminal#14713]
### Windows Terminal version

1.16.3463.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Enable option in settings "copy on select" in settings.
Select something in terminalLet it be "some text 1".
![image](https://user-images.githubusercontent.com/34980479/213707130-79315f50-007f-484a-a244-1925d07dc3fa.png)
Switch to another application e.g. notepad.
Paste. 
Copy anything else in notepad and paste into terminal with right click. Let it be "some text 2".
![image](https://user-images.githubusercontent.com/34980479/213707296-c71d4b8c-e94f-482b-9423-41f508adf81f.png)
Switch to terminal and paste text with Mouse Right Click.
![image](https://user-images.githubusercontent.com/34980479/213707476-6120cc2d-73d0-4693-a8b9-925b9240c20d.png)

### Expected Behavior

Expecting to see pasted "some text 2"

### Actual Behavior

Selection from Terminal become not selected and pasted text is still "some text 1".
![image](https://user-images.githubusercontent.com/34980479/213707596-35f70d7a-873d-42ca-8534-78aba561e8bb.png)

I'm expecting to see copied new text. But when I paste with Mouse Right Click, it copies again selection from Terminal and paste it.
During work I often use copy/paste functions and this behavior brings significant inconvenience.

For example, putty keeps selection and data in clipboard till you copy anything else in other place. In that case selection (background highlighting) in putty just deselected.
It looks Mouse Right Click does two action copy selected+paste, but I expect to see only paste (maybe +deselect).
It seems in some previous versions of ms terminal it worked properly.
Thnx

**Comment by lhecker** [comment]
In other words, when copy-on-select is enabled we shouldn't bind right click to copy-selection. That makes sense to me! ...and seems easy to fix.

**Comment by carlos-zamora** [comment]
Thanks for the report. I'm going to mark this as a /dup of #14464. @zadjii-msft just be sure to keep an eye on this when working on #14635 please.
