### ISSUE TITLE
[GitHub releases] Preinstall Kit for Win11 has wromg name

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#14712]
The preinstall kit for Windows 11 is called `Microsoft.WindowsTerminal_Win11_..._Windows10_PreinstallKit.zip`.

But it must be `Microsoft.WindowsTerminal_Win11_..._Windows11_PreinstallKit.zip`.

This is a bit confusing.

**Comment by zadjii-msft** [comment]
Huh. That's an interesting artifact of the build system. I wonder if we could stamp "Windows11" into the win11 preinstall kit pipeline. 

I'm sure it's entirely aesthetic, and the actual filename has no bearing on the functionality. But I bet it could be done.
