### ISSUE TITLE
Feature Request: Finish full unicode support (M:N cell rendering, ZWJ?)

### ISSUE THREAD

**Issue by giosal** [microsoft/terminal#1472]
# Summary of the new feature/enhancement

When the Terminal came out, there was a mention of Unicode support, but I can see that it's still not there. There is no support for Georgian script yet.

**Comment by DHowett-MSFT** [comment]
This is now the master issue for all good good rendering efforts.

**Comment by giosal** [comment]
I apologize for not providing this detail previously, but I have just checked all three modes available on my laptop - PowerShell, CMD and Ubuntu WSL1 - it's not available in any of them.

**Comment by miniksa** [comment]
It's alright. We know that we're not done in this space and when we sat in triage, we couldn't believe we didn't file the issue yet. Congrats, yours is now the master tracking that we still have work to do to live up to our Unicode promise.

**Comment by francogp** [comment]
![image](https://user-images.githubusercontent.com/2739706/85194582-53e33000-b2a4-11ea-8f7d-3b9cd3a3fa79.png)
On the upper image, I use other terminals (in windows and linux), and they render the fonts OK,
But on the bottom, on Windows Terminal, lots of symbols are rendered in the wrong way.
I use this font: [JetBrainsMono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf)

**Comment by giosal** [comment]
I confirm that the feature is not implemented yet.
Here's the screenshot of Georgian:
![image](https://user-images.githubusercontent.com/25568030/85199215-10151880-b2ee-11ea-9738-e283e014873d.png)
I use stock fonts

**Comment by ofek** [comment]
Has there been any progress on this?

**Comment by JustinGrote** [comment]
Trying to use unicode still results in weird spaces that don't occur in other terminals
![image](https://user-images.githubusercontent.com/15258962/227419907-9928c6c1-c876-48af-b3ca-53a5a1957fb0.png)

**Comment by DHowett** [comment]
> still

That would be why this workitem is still open :smile:

**Comment by JustinGrote** [comment]
@DHowett whoops, I didn't fully flesh out that info, I should have made it a sub-issue, sorry for the bump notify, it wasn't my itent :)

**Comment by lhecker** [comment]
Similar to #190, this issue can now also be closed. #16916 added support for ZWJ and thus this work is now complete. There are some smaller issues left to clean up, but I expect them to be a rare encounter. As such I'll close this issue for now.

This will ship in Windows Terminal 1.22 this year. If you want to try it out right now, please feel free to download our Canary (nightly) build here: https://github.com/microsoft/terminal/discussions/16121

Please note that PowerShell does not have support for complex Unicode yet, but that's expected to change in the foreseeable future (no exact date yet).

**Comment by nasusonetrick** [comment]
im still facing the same issue even with latest version of Terminal, any update fix coming for this ?

**Comment by lhecker** [comment]
Please file a new issue in this case. If you can please attach a screenshot of the issue and steps to reproduce it.

Note that misaligned text in PowerShell is a PowerShell issue: it doesn't support modern Unicode very well.
