### ISSUE TITLE
Can't use Mica

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#14727]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1105

### Steps to reproduce

Apply this setting, per release notes:

```
To use Mica, set up a new theme with the following settings:

    {"window": {"useMica": true}, "tabRow": {"background": "#00000000"}}
```

### Actual Behavior

If `{"window": {"useMica": true}, "tabRow": {"background": "#00000000"}}` is added to a color scheme it results in an invalid color scheme. If applied to a profile it results in an invalid profile. If applied to `defaults` there are no complaints but `Mica` effect is not being applied.

Could dev(s) show an example how to apply Mica? Thx!

**Comment by zadjii-msft** [comment]
Hey wadda ya know, the docs are in PR now. Go look at: https://github.com/MicrosoftDocs/terminal/pull/634.
