### ISSUE TITLE
unexpected behavior after changing window height

### ISSUE THREAD

**Issue by BlueRain-debug** [microsoft/terminal#14738]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19044.2546

### Other Software

Font: Consolas

### Steps to reproduce

1. Run wt.exe.
2. Open a PowerShell Tab.
3. Execute some commands such as `dir` so that the output can fill the screen.
4. Change the height of current window.
5. Type something.

### Expected Behavior

![expected](https://user-images.githubusercontent.com/68976789/214872318-3f6159b4-2807-484c-af29-8b60122abcae.png)

### Actual Behavior

![unexpected](https://user-images.githubusercontent.com/68976789/214872418-9fe7699c-2828-4a34-b1c4-e046f360d597.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This was discussed before in /dup #2432, and ultimately was due to a psreadline bug. Updating to [PsReadline v2.2.0-beta5](https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta5) should fix this. Thanks!
