### ISSUE TITLE
Square tabs with full height

### ISSUE THREAD

**Issue by JakubBlaha** [microsoft/terminal#1473]
# Tabs should be squared and have the same height as the rest of the window head.

The tabs should be without the corner radius, so they fit the style of the rest of the system more. Also the tab "ceiling" should end right at the top of the window head (and not below like it is right now), so users can click on them without aiming. They would also have the same padding at the top as they have at the bottom, which would look even nicer.

I want the tabs to be resized to fit the whole window head and their corner radius to be removed.

**Comment by DHowett-MSFT** [comment]
Thanks for reporting this. Would you mind helping us out and keeping UI issues in the “ui mega thread”? #1375

**Comment by JakubBlaha** [comment]
Oh, I am sorry. Will watch out for that the next time.
