### ISSUE TITLE
[1.17] Dark titlebar in light theme

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#14732]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19045.2546

### Steps to reproduce

Start WT. it shows up as in the attachment, i.e. with a black background in the window title bar

![wt_start](https://user-images.githubusercontent.com/35931460/214687149-c091aea8-b139-4eb7-a7b7-d3164d3f4612.png)

### Expected Behavior

**After** I click on another window app or on the Desktop it shows up as in the attachment which I would expect and prefer , i.e. with a **white** background in the window title bar. Notice WT does not return to look as in the first start above (black background in window title bar)

![wt_after](https://user-images.githubusercontent.com/35931460/214688234-c43a6b65-5748-4ac0-abc7-58cebd4bd36b.png)

### Actual Behavior

See above.

**Comment by DHowett** [comment]
Would you mind sharing your `settings.json`?

**Comment by angelog0** [comment]
Now attached.

[wt-settings.tar.gz](https://github.com/microsoft/terminal/files/10503951/wt-settings.tar.gz)

**Comment by angelog0** [comment]
BTW, I had (just now uninstalled) WT-1.15 (no-preview) and it had changed my `settings.json` removing ALL my comments and adding some other stuff SILENTLY. Luckily I have a backup of that file... I often leave as comment old configurations and alternative to statements and references to WEB and other docs where I find suggestions etc..

**Comment by zadjii-msft** [comment]
@angelog0 Thet's tracked in #8991

**Comment by zadjii-msft** [comment]
```json
        {
            "name": "system2",
            "window": {
                "applicationTheme": "system"
            },
            "tab": {
                "background": "terminalBackground",
                "showCloseButton": "hover",
                "unfocusedBackground": "#00000000"
            }
        },
```

I'd reckon this is due to your OS being in dark theme, the Terminal being in `system`, and us finally obeying the app theme when it comes to the titlebar (#14536). 

If you change `system` to `light` in your `theme`, is that more what you're looking for/?

**Comment by angelog0** [comment]
@zadjii-msft I tried this:

```
{
            "name": "system2",
            "window": {
                "applicationTheme": "light"
            },
            "tab": {
                "background": "terminalBackground",
                "showCloseButton": "hover",
                "unfocusedBackground": "#00000000"
            }
        },
```

but it does not work: same result...

**Comment by zadjii-msft** [comment]
> 10.0.19045.2546

Hmmmmmmm the API we use to change the titlebar color might not _exist_ in Windows 10. Any chance you've got a Windows 11 machine you could test with?

**Comment by zadjii-msft** [comment]
> `DWMWA_USE_IMMERSIVE_DARK_MODE`
> Use with [DwmSetWindowAttribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute). Allows the window frame for this window to be drawn in dark mode colors when the dark mode system setting is enabled. For compatibility reasons, all windows default to light mode regardless of the system setting. The pvAttribute parameter points to a value of type BOOL. TRUE to honor dark mode for the window, FALSE to always use light mode.

> 
> **This value is supported starting with Windows 11 Build 22000.**

_emph. added_

I think I'm gonna have to call this one by-design. I can't repro this with your theme on Win11, and it looks like that API is only officially supported on Win 11.

**Comment by angelog0** [comment]
You mark off-topic all comments you don't like. This is an **hypocrisy**. 

Obviously even this will be marked off-topic if not worse...

**Comment by DHowett** [comment]
Your comment about the system requirements and the size of our heads _IS_ off-topic, @angelog0. The topic of this issue is the titlebar color, and the topic of this repository is the Windows Terminal and Windows Console Host. If you want a forum in which to air your grievances about things that are not Windows Terminal, the Windows Console Host, or the titlebar color of Windows Terminal or the Windows Console Host I will gladly redirect you to [Reddit](https://old.reddit.com).

**Comment by DHowett** [comment]
(This change you're asking about actually isn't version-specific. Your tab row is set to light theme, which suggests that your application is set to light theme. I think we should offer title bar customization alongside tab row customization probably. We found that out while triaging a later issue than this one.)
