### ISSUE TITLE
Add quick filter for New Tab -> Profiles drop down

### ISSUE THREAD

**Issue by andreihes** [microsoft/terminal#14741]
# Description of the new feature/enhancement
Add a quick filter for profile drop down. Picking a profile (when opening a new tab) with arrow up/down keys is a pain once profile count exceeds 20-30

# Proposed technical implementation details (optional)
- When profiles drop down is opened and user starts typing the whole profile list filtered by basic text match
- Filtered means only the profiles with `Name =~ *filtertext*` are displayed
- Current "filtertext" text to be shown / visible as well in any suitable way
- Pressing "Esc" removes / clears the filters and brings all the profiles back

**Comment by zadjii-msft** [comment]
You know, I think the [Command Palette](https://learn.microsoft.com/en-us/windows/terminal/command-palette) is _just_ the UI for this :wink:

![gh-14741-demo](https://user-images.githubusercontent.com/18356694/214931461-bd2c57e1-572c-4e08-b560-5e888eb52d36.gif)

/dup #2046
