### ISSUE TITLE
Execution alias `wt.exe` not working with Terminal Preview (in Windows Search)

### ISSUE THREAD

**Issue by FrzMtrsprt** [microsoft/terminal#14743]
### Windows Terminal version

1.17.10235.0

### Windows build number

10.0.22623.1245

### Other Software

N/A

### Steps to reproduce

1. Uninstall Terminal (if present)
2. Install Terminal Preview from Microsoft Store
3. Enable the execution alias `wt.exe` for Terminal Preview in Settings (if not enabled)
4. Search `wt` in start menu, and select `wt (run command)`

### Expected Behavior

Terminal Preview launches
>Running `wt` from cmd does work though, but not from Windows Search

### Actual Behavior

Nothing happens

**Comment by carlos-zamora** [comment]
Thanks for the report. Could you file feedback via feedback hub please? This sounds like an issue with Windows Search, so once you file that, we can go in and promote it.

/feedback

**Comment by FrzMtrsprt** [comment]
I have filed it in the Feedback Hub. https://aka.ms/AAjf4eo

**Comment by carlos-zamora** [comment]
Thanks for the report. We're taking this up with the app platform team. It looks like Terminal isn't even getting started, so we're handing this off.
