### ISSUE TITLE
cant install on corporate device due to: "windows.sharedFonts"

### ISSUE THREAD

**Issue by spotlight2001** [microsoft/terminal#14757]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19042.0

### Other Software

In Powershell I try to install downloaded Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle from github releases.

I get an error regarding: "windows.sharedFonts"

System:
corporate device
store is disabled
with admin i get this error
without admin i cannot install due to missing privilege

### Steps to reproduce

open powershell. try to install downloaded msixbundle:

 Add-AppxPackage -Path c:\temp\Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle

### Expected Behavior

windows terminal just installs fine

### Actual Behavior

Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x80073D19, Fehler aufgrund der Abmeldung eines Benutzers
Fehler 0x80070002: Beim Verarbeiten der Anforderung konnte die Erweiterung "windows.sharedFonts" aufgrund des folgenden Fehlers
nicht registriert werden: Das System kann die angegebene Datei nicht finden.
.
HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach [ActivityId]
5cb65b5e-347f-0008-7ca7-b65c7f34d901, oder verwenden Sie die Befehlszeile Get-AppxLog -ActivityID
5cb65b5e-347f-0008-7ca7-b65c7f34d901
In Zeile:1 Zeichen:1
+ Add-AppxPackage -Path c:\temp\Microsoft.WindowsTerminal_Win10_1.16.10 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\temp\Microso...bbwe.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by carlos-zamora** [comment]
Thank you. Sorry, there's nothing we can really do about this. A couple options forward include asking your IT department to unblock the windows.sharedFonts extension, or running the unpackaged version of Windows Terminal.
