### ISSUE TITLE
empty line after vim in ssh channel

### ISSUE THREAD

**Issue by jliu666** [microsoft/terminal#1475]
the terminal on the right is mac terminal.
1. open a ssh channel
2. use vim to open a text file
3. exit for many times

Different behaviors show.
No empty line like this:
![image](https://user-images.githubusercontent.com/14869749/59978690-8dda1180-9611-11e9-9a2f-79066638babd.png)

Too many empty line like this:
![image](https://user-images.githubusercontent.com/14869749/59978566-3ab38f00-9610-11e9-9208-3912f11c1485.png)

A bug of CentOS or ssh? I don't think so. I also test for many times on my mac terminal, only one behavior.

**Comment by DHowett-MSFT** [comment]
Are you using WSL SSH or Windows SSH?

**Comment by jliu666** [comment]
Yes, I use Windows SSH (built in PowerShell)

**Comment by DHowett-MSFT** [comment]
This might be an issue for [their repository](https://github.com/powershell/win32-openssh). I see this on conhost itself without Windows Terminal on occasion.
