### ISSUE TITLE
Small fonts on HTML format pasting

### ISSUE THREAD

**Issue by alfonskunk** [microsoft/terminal#14762]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19044.2486

### Steps to reproduce

Copying text with 10px font size on Windows Terminal Preview
With AltasEngine = true it pastes with 5px font size (mantain rest of text format like colors and font type)
With AtlasEngine = false it pastes with 1px font size (mantain rest of text format like colors and font type)

Copying text with 20px font size on Windows Terminal Preview
With AltasEngine = true it pastes with 9px font size (mantain rest of text format like colors and font type)
With AtlasEngine = false it pastes with 1px font size (mantain rest of text format like colors and font type)

RTF pastes right font size.

This issue is reproducible only since 1.17.1023 at 2023/01/25

### Expected Behavior

Pasting with same font size as source

### Actual Behavior

With AltasEngine = true it pastes with 5px font size (mantain rest of text format like colors and font type)
With AtlasEngine = false it pastes with 1px font size (mantain rest of text format like colors and font type)

**Comment by carlos-zamora** [comment]
The renderer hands the size of the font over when copying HTML text to the clipboard.

We should also check if this affects 1.16

**Comment by alfonskunk** [comment]
Hi,

1.16 is not affected.
And neither does Windows Terminal Stable (1.15.3465.0)
