### ISSUE TITLE
Mica material is too inconspicuous and not showing applications under terminal

### ISSUE THREAD

**Issue by leonasdev** [microsoft/terminal#14769]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1105

### Steps to reproduce

Enable Mica and disable acrylic, set `opacity` to `0`.
```json
"defaults": 
{
    "opacity": 0,
    "useAcrylic": false
},
"themes":
{
"window":
    {
        "useMica": true
    }
}
```

### Expected Behavior

1. The Mica effect in the window should look like the Start Menu of Windows 11.
    - Start Menu:
    ![image](https://user-images.githubusercontent.com/39915562/215994281-1f66f1b1-bbe7-4dcc-8cd0-4c5ab08c16df.png)

    - Windows Terminal:
    ![image](https://user-images.githubusercontent.com/39915562/215994091-bdf8a060-fa29-4824-a92c-2972f8d0e164.png)

2. When Mica enabled, applications should showing under the terminal. Not just shows the wallpaper.
    - Start Menu:
    ![image](https://user-images.githubusercontent.com/39915562/215995631-2e0446ed-40c6-40b4-9de5-64ccdc5bb096.png)

   -  Windows Terminal:
    ![image](https://user-images.githubusercontent.com/39915562/215995498-01442532-242b-45f1-bff2-253e4a274f1f.png)
is 

### Actual Behavior

1. The Mica effect in the window is too inconspicuous even though I have set the `opacity` to `0`.
2. When Mica is enabled, applications are no longer showing under the terminal. Instead, the Terminal just shows the wallpaper.

**Comment by TheDecryptor** [comment]
It looks like the start menu is using acrylic, not mica. The settings app uses mica and it should match terminal.

**Comment by zadjii-msft** [comment]
Yea, that all looks like mica to me in the Terminal, and Acrylic in the Start Menu. Mica is intended to be a bit more subtle than acrylic, and always uses the desktop wallpaper as the source it blurs from (ignoring windows beneath it). Another good example to compare with is the Calculator app.
