### ISSUE TITLE
Some records were missing when I scrolled to bottom with the modified "$prompt".

### ISSUE THREAD

**Issue by Briar-CatHei** [microsoft/terminal#14778]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1194

### Other Software

cmd.exe in Build 22621.1194
ansicon v1.89
oh my posh (installed by MSStore then uninstalled)
clink  v1.14.15(uninstalled)

### Steps to reproduce

Use "setx" command to set "$prompt"
Run commands as "ping -t" or long press Enter make commands records to scroll to bottom 

### Expected Behavior

Usually, the scroll bar should be appeared when a command runs to bottom, make sure the earlier records still exist when the history records was 9001 in default althougth the "$prompt" was set to other.
(Legacy cmd and WT v1.17.1023)
![image](https://user-images.githubusercontent.com/82100581/216524778-0a22dc7b-dd38-41d1-8085-e73e31569545.png)
![image](https://user-images.githubusercontent.com/82100581/216525975-c0a365b3-c55b-4625-b5f2-2618f942aaaa.png)

### Actual Behavior

The scroll bar didn't appear when the command records over to bottom although 9001 in default and fix or reset the WT application.
![屏幕截图 2023-02-03 141024](https://user-images.githubusercontent.com/82100581/216526703-78771840-69f9-4eb5-879e-62af7a5dedf1.png)
![屏幕截图 2023-02-03 140744](https://user-images.githubusercontent.com/82100581/216526688-67160709-0f28-41a5-8d33-5a260e4ea870.png)
![屏幕截图 2023-02-03 135806](https://user-images.githubusercontent.com/82100581/216527623-3bce5bf2-b322-4252-9891-1276f7eabbe4.png)

**Comment by zadjii-msft** [comment]
Haha that prompt looks _familiar_ 😉 
![image](https://user-images.githubusercontent.com/18356694/216587823-6c39c186-b7a4-48ab-a9b0-dd5297d43cc7.png)

Can you share what exactly you've set `%PROMPT%` to?

Also, could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by Briar-CatHei** [comment]
- This is %PROMPT%
```
[19:55:58.42]>C:\Users\Briar>
Briar@LXH-PC>echo %PROMPT%
$e[30;47m[$T]$G$e[37;46m$P$G$e[0m$_$e[34mBriar$e[0m@$e[32mLXH-PC$e[0m$G
```
The PC name(LXH-PC) and user name(Briar) were from %computername% and %username%
`setx prompt $e[30;47m[$T]$G$e[37;46m$P$G$e[0m$_$e[34m%username%$e[0m@$e[32m%computername%$e[0m$G`
![image](https://user-images.githubusercontent.com/82100581/216598670-d30566cf-7bc6-4585-aacd-17bb20c2e91c.png)


- And this is `settings.json`
[settings.json.txt](https://github.com/microsoft/terminal/files/10578756/settings.json.txt)


- Others
![image](https://user-images.githubusercontent.com/82100581/216601396-6f9543a9-8b07-4239-99a7-39227f104039.png)

The same WT version ,$PROMPT$ and settings.json in a Beta Build
![image](https://user-images.githubusercontent.com/82100581/216602522-617dc4de-f157-4789-abe1-e9c8679dd9e5.png)

**Comment by carlos-zamora** [comment]
Hi @Briar-CatHei. Are you launching CMD directly (i.e. cmd.exe from Run) or inside Terminal?

**Comment by Briar-CatHei** [comment]
Both, but I solved that by reinstalling the whole OS
I was wondering that how to cause that bug before...
![image](https://user-images.githubusercontent.com/82100581/217762315-ea1a1b72-2a58-4f8f-8733-87ca4eb633a9.png)

**Comment by carlos-zamora** [comment]
Great! Closing as no repro then. Thanks!
