### ISSUE TITLE
'Parameter is Incorrect' on Azure Virtual Desktop with FSLogix

### ISSUE THREAD

**Issue by lwilliams1990** [microsoft/terminal#14770]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22621.0

### Other Software

FSlogix 2.9.8171.14983

### Steps to reproduce

Create a session host pool based on Azure image which has Windows Terminal as the default shell:

publuisher = "MicrosoftWindowsDesktop"
offer = "windows-11"
sku = "win11-22h2-avd"

First login as a new user creates an FSLogix profile and Terminal works just fine.

Sign out and back in again, try to launch Terminal and we received a 'parameter is incorrect' error.

Signing out and back in again SOMETIMES allows the app to launch again, as does restarting the session host and signing in again. I've also observed this happen mid-session just by closing Terminal and trying to open it again.

I believe this is somehow related to the use of FSlogix profile containers, as deleting 'C:\Users\USERNAME\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe' when the issue is re-created and then re-launching allows the app to launch again, however we need to persist this directory I believe to maintain Terminal settings across AVD sessions.

Other Windows Store / APPx applications included with the OS like Calculator and Clock seem unaffected by the same issue, it seems to be limited to Terminal.

### Expected Behavior

Error free launch of Windows Terminal.

### Actual Behavior

![image](https://user-images.githubusercontent.com/51878981/215992872-11a3328e-19d6-425d-b502-e82df43aa11a.png)

**Comment by lwilliams1990** [comment]
I believe that FSLogix version 2.9.8361.52326 fixes this problem since the addition of the feature to include a new AppX process on sign-out detailed in the release notes:

https://learn.microsoft.com/en-us/fslogix/whats-new#fslogix-2210-29836152326

So far I've not been able to re-create the issue after updating FSlogix on a test session host.

**Comment by DHowett** [comment]
Thanks for following up! You beat us to finding the duplicate in our backlog. It'll be great to have this info in case somebody else asks. :smile:

**Comment by lwilliams1990** [comment]
I've since re-created the issue through normal

**Comment by lwilliams1990** [comment]
I've since managed to re-produce this issue on FSLogix version 2.9.8361.52326

It seems a lot less frequent than when we were using the previous FSLogix version, it seems to happen more when other users are logged into the AVD session host.

![image](https://user-images.githubusercontent.com/51878981/221827177-5badae33-1cdf-428f-a1bc-cdac204062cd.png)

Other inbox apps seem consistently ok so I'm not sure it's a specific interoperability issue between FSlogix and Terminal.

**Comment by msft-jasonparker** [comment]
We just released HF1 for 2210 which has some fixes for the InstallAppxPackages feature flag.

As Terminal is an inbox app, we expect it to work.  Not all AppX package and apps are equal and there could be an interop issue that we are unaware of.  We have not seen this issue in our test environments.

**Comment by zadjii-msft** [comment]
FWIW, I'm gonna close this out since this _seems_ like it's an external issue. If the investigation comes back pointing the finger at the Terminal, we'd be more than happy to re-open and take another look.

Thanks everyone!
