### ISSUE TITLE
Allow pasting multiple lines into terminal

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/terminal#14772]
# Description of the new feature/enhancement

When I want to paste a command that consists of multiple lines into the Windows terminal, each line gets executed as its own command and the command therefore doesn't work. Sometimes, however, I really need to break commands apart into multiple lines since otherwise, long commands can get very confusing.

# Proposed technical implementation details (optional)

**Comment by carlos-zamora** [comment]
Thanks for the request. This requires work in PowerShell.

/dup https://github.com/PowerShell/PSReadLine/issues/1471
