### ISSUE TITLE
Line height appears off in WT

### ISSUE THREAD

**Issue by igniscyan** [microsoft/terminal#14771]
### Windows Terminal version

 1.17.1023

### Windows build number

10.0.22000.1455

### Other Software

nvim 0.9.0 dev build

### Steps to reproduce

Use the mononoki font, set font size to 10.

### Expected Behavior

Sane default for line height (or a front facing option like in VSCode to automatically calculate line height) on the font

### Actual Behavior

Line spacing is _way_ too close on certain fonts. Mononoki is a great example, but I've found this issue on several I've tested. 

![image](https://user-images.githubusercontent.com/26984470/216010244-d3c832d0-cf5d-462c-8446-771309e0b30e.png)

This image shows the same font and same font size. Right is in VScode, left is in Windows terminal. The font is rendered useless in the latter.

**Comment by lhecker** [comment]
The font file specifies a line height of 1.2 which we respect:
![image](https://user-images.githubusercontent.com/2256941/216088099-603bb917-0d07-40c5-8d3f-ce27d5c924ef.png)

VS Code on the other hand ignores the font's line height and uses 1.35 by default. Here's the relevant code: https://github.com/microsoft/vscode/blob/0291e43350e922a7b6cdb0227f9dd01e6e7cb8e2/src/vs/editor/common/config/fontInfo.ts#L14

As such I'd expect a line height difference of +12.5% in your screenshot, but yours shows a difference of 40%:
![image](https://user-images.githubusercontent.com/2256941/216091249-db336331-ee53-4bcf-a1d3-6fe08e21e745.png)

In fact, I can't reproduce such a big difference in line heights either:
![image](https://user-images.githubusercontent.com/2256941/216089798-80cfd003-dd9e-4cb7-a08b-6fc3abb1a8be.png)

Can you please check the following?
* Did you perhaps override the line height in VS Code?
* Is your mononoki font up to date? It got an update just a few months ago.
* It's unlikely, but are you certain you're using the exact same font variant and font size in both applications?

**Comment by igniscyan** [comment]
@lhecker Embarrassingly, a reinstall seems to have solved the issue completely. Apologies for the redundant issue!
