### ISSUE TITLE
WT / WTP Fail to load properly after first launch

### ISSUE THREAD

**Issue by Wuhao1627003** [microsoft/terminal#14789]
### Windows Terminal version

1.16.10262, 10232, WTP 1.17.1023

### Windows build number

10.0.25290.0

### Steps to reproduce

Launch Terminal through either start menu or C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10232.0_x64__8wekyb3d8bbwe (normal & elevated) will show a window, then crash immediately.
<img width="867" alt="image" src="https://user-images.githubusercontent.com/25204397/216828247-e1c7c413-767c-4320-9191-8007bc126632.png">
After re-installing the software, the first launch works as expected, but all subsequent launches crash. Tasks I tried include pwsh, pwsh preview, command prompt, Az cloud shell.
In Task Manager, the process WindowsTerminal.exe also disappears.
This only happened in lastest Windows build, no problem before.

### Expected Behavior

Normal run of WT, loading my tasks like pwsh, waiting for user input

### Actual Behavior

Window shows up with no running of pwsh, can't input, and immediately crash.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

Does something like `wt sp ; sp -- cmd.exe` work? 

If WT is truly crashing, then grabbing a /feedback hub trace might help grab the stack...

**Comment by qdztxc** [comment]
same issue under 10.0.25290.0

**Comment by Wuhao1627003** [comment]
@zadjii-msft wt sp ; sp -- cmd.exe also displays window temporarily, then crashes.
Attaching my settings json files as txts
[settings.txt](https://github.com/microsoft/terminal/files/10681500/settings.txt)
[settings.txt](https://github.com/microsoft/terminal/files/10681501/settings.txt)
I will add to feedback hub now.

**Comment by Wuhao1627003** [comment]
Feedback hub link https://aka.ms/AAjkm13

**Comment by carlos-zamora** [comment]
Thanks for filing feedback. We've confirmed this is an instance of a bug impacting Windows Insiders on builds 25290 and similar. We're tracking it internally with MSFT:43105892.

**Comment by qdztxc** [comment]
same issue under 25295.1000, when will this be fixed?
