### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by JoeBrunsTR** [microsoft/terminal#14786]
MS store has 1.15

Git has 1.16 and 1.17 around the corner.

How do I upgrade to 1.16?

**Comment by zadjii-msft** [comment]
[Version XYZ was just released, why doesn't it show up as an update in the Store?](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#version-xyz-was-just-released-why-doesnt-it-show-up-as-an-update-in-the-store)
