### ISSUE TITLE
Feature Request: CMD as administrator

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#1478]
# Summary of the new feature/enhancement
 
Currently, to open Command Prompt with elevated privileges, you need to right click on CMD and click Run as Administrator.
Allowing the user to open Command Prompt, PowerShell, or WSL as Administrator in the Terminal itself would be a great feature.

# Proposed technical implementation details (optional)

Add a menu option to open CMD, PowerShell, or WSL as administrator.

**Comment by DHowett-MSFT** [comment]
Hi there. Please make sure you search for existing issues before filing a new one. #1032 has a bunch of keywords and is the right place.
