### ISSUE TITLE
Pasting from clipboard broken when running ssh-add.exe in WSL2 in Windows Terminal

### ISSUE THREAD

**Issue by OlJohnny** [microsoft/terminal#14790]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19045.0

### Other Software

* WSL2 with Ubuntu (<code>C:\WINDOWS\system32\wsl.exe -d Ubuntu-20.04</code>)
* ssh-add.exe (<code>OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2</code>)

### Steps to reproduce

* You need to have a passphrase protected ssh key in your windows <code>HOME/.ssh</code> directory (just execute ssh-keygen in a PowerShell Terminal)
* Start the Windows OpenSSH ssh-agent in an Administrator PowerShell Terminal <code>Start-Service ssh-agent</code>
* Start WSL2 distribution in Windows Terminal
* run <code>ssh-add.exe</code> and try to paste your passphrase

### Expected Behavior

The passphrase gets pasted (without seeing it) and the key is successfully loaded into the <code>ssh-agent</code>.
This actually works, when running the WSL2 VM by just starting it from the Windows Search (i <i>think</i> it is then running inside cmd.exe)

### Actual Behavior

The passphrase gets pasted so that you can see the text!
Also loading the key then fails, as ssh-add.exe seems to be unable to read the pasted passphrase.
NOTE: this may doesn't happen on the first try, but after running <code>ssh-add -D</code> and <code>ssh-add</code> again, it nearly always happens

**Comment by OlJohnny** [comment]
after further testing it seems to be a bug with wsl

**Comment by zadjii-msft** [comment]
This sounds like a broken interaction with bracketed paste mode. I'd bet you could manually disable bracketed paste mode, before running `ssh-add.exe`:

```printf '\e[?2004l' & ssh-add.exe```

(I'm making the assumption that bash/{your shell} wouldn't re-enable it before spawning `ssh-add.exe`)



OR 

I see now that I've typed this up you don't think it's a terminal issue after all.

**Comment by OlJohnny** [comment]
> I see now that I've typed this up you don't think it's a terminal issue after all.

Seems like it!

I have the culprit, although i don't quite understand why it happens, in a normal bash terminal it doesn't happen

<code>alias asd='ssh-add.exe 2> /dev/null'</code>

Now when running <code>asd</code>, the issue arises again
