### ISSUE TITLE
Feature Request - Easier means of launching Windows Terminal

### ISSUE THREAD

**Issue by JaimeStill** [microsoft/terminal#1479]
# Summary of the new feature/enhancement

Most of the time, when I open a command prompt, I either run `cmd` from the navbar of the directory I want to open in Windows Explorer, or I run `cmd` from the Run utility (<kbd>Win + R</kbd>).

It would be great if one of the solutions outlined below would allow better integration of Windows Terminal, making it a more viable shell for use in Windows.

# Proposed technical implementation details (optional)

**Default Shell**
In Windows 10, you have the option of setting application defaults. A **Shell** category could be added and linked to Windows Terminal. This way, any time you launch PowerShell, Command Prompt, or any other CLI, it will launch in Windows Terminal. I know OS-wide settings are outside of the scope of this project, but I think it is a good conversation to have regarding people who want to use this tool by default at the operating system level.

![terminal-settings](https://user-images.githubusercontent.com/14102723/59979059-a49c4c00-95b0-11e9-9eb1-8667f2ac276e.png)

**Alternative Solution**
Provide a way to launch Windows Terminal in the same way you can use `cmd` to launch Command Prompt (as specified above).

**Comment by Shorotshishir** [comment]
instead of `cmd`, type `wt`
> I either run cmd from the navbar of the directory I want to open in Windows Explorer, or I run cmd from the Run utility (Win + R).

**Comment by JaimeStill** [comment]
@Shorotshishir thanks, I didn't find any mention of this on my initial tinkering. This is definitely helpful! However, it does not work for resolving the current directory when launching from the navigation bar in Explorer.

**Comment by Shorotshishir** [comment]
@JaimeStill use "startingDirectory" : "%__CD__%". your issue will be resolved.
![image](https://user-images.githubusercontent.com/16465879/59979713-e65ae000-960c-11e9-9914-ae6b1cdd0bf0.png)

**Comment by ducaale** [comment]
@Shorotshishir is it possible to use %\_\_CD\_\_% only when launching from the navigation bar in Explorer and use %PROFILE% when launching from start menu?

**Comment by JaimeStill** [comment]
@ducaale @Shorotshishir having the ability to differentiate the two scenarios would definitely be ideal.

**Comment by Dinjoralo** [comment]
I'm guessing this will come later when the Terminal is out of preview, but a way to just have this popup whenever CMD/Powershell/WSL would open would be nice.

**Comment by DHowett-MSFT** [comment]
Right now, `wt` is the "easier" way to launch `wt.` If you're using a dev build, it's `wtd`. This'll be better served by #492.

**Comment by ledhed-jgh** [comment]
While this is actually the opposite of "Launching" Windows Terminal, it  would be great if you could close the current tab (Powershell or CMD) with CTRL+D. This is very common on Linux shells like Bash.
