### ISSUE TITLE
Provide APPX for Windows Terminal 

### ISSUE THREAD

**Issue by DeltaFiredash** [microsoft/terminal#1480]
So i no longer have Windows Store on my system anymore cause it got uninstalled. Any way i can obtain the APPX package for this? 

Thanks.

**Comment by Karl-WE** [comment]
so also #1484

**Comment by OranguTech** [comment]
@Karl-WE - think you linked to the wrong issue on accident.

Duplicate/see also #1483 

I too vote for this, similar to what is available for the Ubuntu package.

**Comment by DHowett-MSFT** [comment]
I'm going to make #1386 the master issue for alternate distribution mechanisms. Thanks!

**Comment by cup** [comment]
https://github.com/microsoft/terminal/issues/1386
https://github.com/microsoft/terminal/issues/1405

https://github.com/microsoft/terminal/issues/1480
https://github.com/microsoft/terminal/issues/1483
https://github.com/microsoft/terminal/issues/1541
