### ISSUE TITLE
Administrator and normal user tabs in the same window

### ISSUE THREAD

**Issue by WillPittenger** [microsoft/terminal#14800]
# Description of the new feature/enhancement
In a normal WT window, if you open a profile that requires Administrator privileges, WT opens a new window.  If you then try to open a non-Admin profile, it becomes Admin too.  Now contrast that with Konsole over in KDE.  It can have Super User and normal user tabs in the same window.  I'm guessing some of that is due to OS differences, but I still see improvements as needed.

(I debated creating this as a bug as the new profile might not have been a trusted program.)

# Proposed technical implementation details (optional)

**Comment by 237dmitry** [comment]
??

![Screenshot 2023-02-07 094620](https://user-images.githubusercontent.com/78153320/217168765-c89f6039-c76a-410a-85b5-95984c7ceb53.png)

**Comment by lhecker** [comment]
Hey! Unfortunately, this isn't something that's going to be possible any time soon. See [this post](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md?rgh-link-date=2022-03-09T11%3A04%3A02Z#elevation) for more details. There's more summary in #5000 as well. There's a slight chance that this might be possible one day, but it's far from trivial for us to add as a feature.

/dup #1032
