### ISSUE TITLE
Black bars on desktop when terminal is open

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/terminal#14809]
### Windows Terminal version

1.15.3466.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Open Windows Terminal

### Expected Behavior

No black bars

### Actual Behavior

Black bars appear with Terminal open.
Terminal maximized:
![image](https://user-images.githubusercontent.com/19240945/217459649-d8f9df0c-9f8f-41d4-9157-eb996aaa3ccd.png)
Terminal open on other monitor:
![image](https://user-images.githubusercontent.com/19240945/217462647-9a06e4b6-413d-477b-9511-806665c2f78f.png)
Terminal minimized and no other window open:
![image](https://user-images.githubusercontent.com/19240945/217459762-dd6eef45-3a86-4efd-9553-ba6d4be0bc8b.png)

These only appear on my main monitor

**Comment by zadjii-msft** [comment]
Do you have something like MicaForEveryone installed/? See #14571, #14181, #14008

**Comment by KuraiAndras** [comment]
Yeah, could not find the related issues. Please close this as duplicate.

**Comment by zadjii-msft** [comment]
/dup #14571, #14181, #14008

thanks!
