### ISSUE TITLE
SUI "Browse..." button crashes

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14808]
### Windows Terminal version

1.17.1023

### Windows build number

25294.1001

### Steps to reproduce

1. open WT
2. Open SUI
3. Click PowerShell profile
4. Open "Starting directory"
5. Click "Browse..."

### Expected Behavior

Not a crash

### Actual Behavior

Crash

**Comment by carlos-zamora** [comment]
FYI: does not repro on 1.16

**Comment by ashemedai** [comment]
@zadjii-msft Ah, sorry for the duplicate. I had search for icon and some other terms but couldn't find it.

In case you need it, here's a Feedback Hub recording: `feedback-hub:?contextid=1089&feedbackid=a2a4b407-a71a-4c15-98ab-f2ce8ff56c53&form=1&src=1` (share link didn't work at the moment).
