### ISSUE TITLE
Drop down menu shows only the shadow. And it is stuck on the screen

### ISSUE THREAD

**Issue by fireattack** [microsoft/terminal#14813]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.2486

### Steps to reproduce

1. Open WT
2. Open setting.
3. Click any drop down menu

### Expected Behavior

A proper looking drop down menu is shown.

### Actual Behavior

Only the shadow of the drop down menu is showing, which is pretty dark. 

Furthermore, if you alt+tab to another window when drop down menu is open, the shadow is stuck on your screen.

The title is kinda hard to explain so let me show it in a GIF:
![30fps](https://user-images.githubusercontent.com/4130991/217824698-401e3dc5-7a35-48c1-92c2-41dbbe0ff357.gif)

Note: sometimes the drop down menu just refused to show up. But I haven't found a good STR.

**Comment by DHowett** [comment]
This looks really similar to a bug we saw in XAML islands long before 10.0.19042 shipped! That's alarming.

**Comment by fireattack** [comment]
I can't seem to reproduce it anymore today.

**Comment by fireattack** [comment]
I'm seeing this bug again today:

![image](https://user-images.githubusercontent.com/4130991/226258080-61a91cb4-9d61-4436-8e0f-3f7feae2fbf0.png)
