### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by adiazcan** [microsoft/terminal#1481]
# Environment
Microsoft Windows [Version 10.0.18362.175]

Windows Terminal version (if applicable):
0.2.1715.0

# Steps to reproduce

With a Spanish keyboard, I cannot write down a Back Slash using ALT GR  on any default terminal, PowerShell 6, PowerShell, CMD or Ubuntu

# Expected behavior

Write a back slash on terminal

# Actual behavior

Don't write any character using ALT GR key like \ or @

**Comment by ts-ws** [comment]
Same problem for German Keyboard

**Comment by DHowett-MSFT** [comment]
Please search for existing issues before filing a new one, @adiazcan. This one literally has ALTGR in the title. #521

**Comment by adiazcan** [comment]
> Please search for existing issues before filing a new one, @adiazcan. This one literally has ALTGR in the title. #521

Sorry, I can't find it.
