### ISSUE TITLE
Terminal looses output when running command that uses progress indicator

### ISSUE THREAD

**Issue by mforkel** [microsoft/terminal#14819]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19045.2486

### Other Software

WSL-Version: 1.0.3.0
WSL distribution: Debian Bullseye

### Steps to reproduce

In a tab for the WSL distribtuion, run a command that uses a progress indicator and produces more lines of output than the terminal windows has, e.g. `apt-get install php`.

### Expected Behavior

All lines of output are available when scrolling back up after the command finishes.

### Actual Behavior

Most lines of output are lost except for some initial lines (probably not handled be the progress indicator) and the lines shown in the terminal when the command has finished.

The problem does no occur if the option `-q` (`--quiet`) is used with `apt-get`.

**Comment by j4james** [comment]
What's happening here is that apt-get is setting the scrolling margins ([`DECSTBM`](https://vt100.net/docs/vt510-rm/DECSTBM.html)) to keep the progress indicator line fixed, while the top part of the screen scrolls. Unfortunately Windows Terminal doesn't handle that situation very well, so the lines that scroll off the top end up being erased when they should be moved into the scrollback buffer. We're already tracking this problem in issue #3673.

**Comment by zadjii-msft** [comment]
/dup #3673

Thanks!
