### ISSUE TITLE
[IDEA] Make Windows Terminal uses modern Windows 11 design trends

### ISSUE THREAD

**Issue by RaphMar2021** [microsoft/terminal#14829]
# Description of the new feature/enhancement

Make the Windows Terminal app uses modern Windows 11 modern design trends like File Explorer, or recently Notepad...

![image](https://user-images.githubusercontent.com/81994075/218266981-e0562165-b5b8-4b88-ac8d-baf10777bb98.png)

# Proposed technical implementation details (optional)
Implement usage of Mica & Mica Alt in the tab bar & the terminal tabs.

**Comment by j4james** [comment]
I believe support for Mica was added in the 1.17 preview release as part of the new theme functionality. For now it needs to be enabled via the JSON settings file. See the release notes here:
https://github.com/microsoft/terminal/releases/tag/v1.17.1023

**Comment by RaphMar2021** [comment]
Yes, but implement real Windows 11 design trends (add Mica Alt as tab row background, Mica as tab button background)

Like this :
![image](https://user-images.githubusercontent.com/81994075/218276218-bdcffa18-d034-4651-9412-d63b05b00951.png)

**Comment by j4james** [comment]
As far as I understand, Windows Terminal can't use both Mica and Mica Alt, for reasons explained here: https://github.com/microsoft/terminal/issues/14785#issuecomment-1418234057

**Comment by driver1998** [comment]
I guess you can simulate Mica on top of Mica Alt by using Mica Alt as backdrop and add a layer with higher opacity up top.

**Comment by zadjii-msft** [comment]
> As far as I understand, Windows Terminal can't use both Mica and Mica Alt, for reasons explained here: https://github.com/microsoft/terminal/issues/14785#issuecomment-1418234057

Yep, that's the case. I'm gonna make the call that we should just move all discussion of Mica Alt to that thread. Thanks!

/dup #14785
