### ISSUE TITLE
Automatic convert window path into bash path

### ISSUE THREAD

**Issue by lawweiliang** [microsoft/terminal#14828]
Window Path: D:\Users\yesla\Desktop\workspace\testingRocky
Ubuntu Path: /mnt/d/Users/yesla/Desktop/workspace/testingRocky

If I copy the window path and paste it to ubuntu terminal, it should automatic convert the path from window path to ubuntu path.

Cmder terminal already have this feature.

---

### In window terminal
When you copy the path to bash terminal, it show the exact window path rather than ubuntu path. 
![image](https://user-images.githubusercontent.com/34936929/218265655-4735a6cf-677b-488a-9dfa-b01a41492a58.png)

---

### Feature Demonstration
Copy the window path then paste it to cmder gitbash terminal, you will see something like this. 'Auto path conversion'. 
![image](https://user-images.githubusercontent.com/34936929/218265416-d183b639-b19f-44cd-95a9-4bf7fb9ebc63.png)

**Comment by j4james** [comment]
I believe this feature is already being tracked in issue #1772.

**Comment by zadjii-msft** [comment]
Sure is, thanks!

/dup #1772
