### ISSUE TITLE
Windows Terminal Install through package manager gives error with exit code "Installer failed with exit code: 0x80070002 : The system cannot find the file specified."

### ISSUE THREAD

**Issue by eherrera1212** [microsoft/terminal#14823]
My laptop turned off and I had to go into repair mode and input my bitlocker key I already had installed windows terminal, but it would not open even after checking if it was open but not showing the gui after checking process explorer no instance of the application was open. I uninstalled it and tried reinstalling it on the microsoft store and got the same error. I switched to a Local Account instead of my microsoft account and got the same problem. I then tried troubleshooting the error by the instructions given in this forum post [https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-error-code-0x80070002-for-the-microsoft/368550a4-147f-44b9-aef0-6c6c070e369f](url), but still got the same error. I tried installing directly from the package manager thinking it was an error with the Microsoft store, but using winget on powershell I got the same error. I think it might be a bug, so I have deicded to report it.
![image](https://user-images.githubusercontent.com/90202949/218201306-d4a9897a-5912-426d-afb9-3c34151b7cc3.png)

**Comment by zadjii-msft** [comment]
This looks like a winget bug to me - mind filing this over at https://github.com/microsoft/winget-cli/issues? They'd be more equipped to investigate. Thanks!
