### ISSUE TITLE
"Launch on machine startup" on"Off" is being ignored

### ISSUE THREAD

**Issue by FluffyDiscord** [microsoft/terminal#14820]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.963

### Steps to reproduce

1. Tick off "Launch on machine startup"
2. Reboot machine

### Expected Behavior

Terminal does not start up

### Actual Behavior

Terminal starts up, even though it's disabled in Startup in Windows settings and has the mentioned option entry disabled.

**Comment by zadjii-msft** [comment]
I _suspect_ this is just /dup #12564

**Comment by vasi** [comment]
Hm, I'm seeing this too, and it seems new. The other ticket has been open for almost a year, can it really be the same thing?

**Comment by zadjii-msft** [comment]
Hmmmmm. A thought:

* Is Terminal set as the Default Terminal Emulator in the Windows Settings?
* Are you using `"firstWindowPreference": "persistedWindowLayout"`?

**Comment by vasi** [comment]
* Terminal is the default terminal emulator, yes
* I am using persistedWindowLayout, yes
* "Launch on machine startup" is off
* Windows' "Automatically save my restartable apps" setting is off

**Comment by vasi** [comment]
I did some testing, and it looks like both those settings need to be ON to manifest the problem.

Hypothesis: Some other startup item is trying to run something in a terminal, and that's causing Terminal to start up and restore its window, instead of exiting quickly.
