### ISSUE TITLE
Support Combo Key Actions

### ISSUE THREAD

**Issue by coffeebe4code** [microsoft/terminal#14835]
# Description of the new feature/enhancement

This command seemingly does not work for opening a new tab, in fact, all combinations like this one do not do what I would expect.
```
    {
      "command": {
        "action": "newTab",
        "keys": "ctrl+b+c"
      }
    }
```
I tried the following.

I pressed `ctrl + b` and released,
I pressed `c` and released,

I also tried pressing and holding `ctrl + b + c` in case that was how the format worked.

I am trying to get tmux like behavior with tabs, and pane splitting, for example with `ctrl + b + %`. 
If this is possible please show an example or provide documentation.

This is the last thing I need for adoption of replacing my linux workflow on windows. Everything else worked perfectly with windows terminal.

# Proposed technical implementation details (optional)
What I would expect.
Combination and Chaining of keys.

keys are wrapped in what combination must be held/released

```
    {
      "command": {
        "action": "newTab",
        "keys": "{ctrl+b}+{c}"
      }
    }
```

Since pressing and holding ctrl + b + c didn't cause the expected behavior it sounds like that first must be supported, before being able to parse {} {} cominations.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1334 for more discussion.

/dup #1334
