### ISSUE TITLE
Terminal only wants to open settings.json in Microsoft Visual Studio

### ISSUE THREAD

**Issue by caitp** [microsoft/terminal#14830]
### Windows Terminal version

whatever it is

### Windows build number

who cares

### Steps to reproduce

1) Click this
![image](https://user-images.githubusercontent.com/2294695/218270889-dd68d1b0-2b97-4e62-b770-d5b75817a0b3.png)

2) Encounter this
![image](https://user-images.githubusercontent.com/2294695/218270938-c9ee2385-9c6c-4362-8c1f-bb8d6746f68a.png)

3) See if the EDITOR environment variable is honoured

4) It isn't

5) Look for an option in the terminal settings

6) Can't find one

7) Use a search engine to figure out if there's supposed to be some registry key or something that you can alter

8) At this point, you quickly lose patience because finding anything online is pretty much hopeless because search engines have been getting consistently less useful every year for at least a decade if not longer.

9) Ask the chatbot, who tries to be helpful but kind of isn't
![image](https://user-images.githubusercontent.com/2294695/218271216-301d2c43-254e-4a25-9233-18e8379fb5e5.png)

10) Obviously this isn't where settings.json actually is, the file does not exist, it's probably somewhere around there but fuck man, why not just do things the normal and expected way so that stuff is less painful to use?

### Expected Behavior

Use an environment variable, or a consistent configuration mechanic that's greppable and possible to find things in, and have a user interface interaction that makes this easy to accomplish with instructions your grandma can figure out just by reading and following the visual direction of the window presentation.

### Actual Behavior

It's a mystery

**Comment by zcobol** [comment]
@caitp the chatbot is giving you onerous information. That looks like VSCode setting. ChatGPT needs more training!

Change file association and set the app that will open JSON files on your box.  If you add `terminal.integrated.shell.windows` to `settings.json` it is being remove when validating it, i.e. press `Save`

**Comment by zadjii-msft** [comment]
The Terminal is respecting your OS-wide setting for your default `.json` file editor. 

You can configure this in the Settings app:

![image](https://user-images.githubusercontent.com/18356694/218325042-0a99e780-f10e-4b67-a3a3-b88523724a35.png)

This was [discussed elsewhere](https://github.com/microsoft/terminal/issues?q=is%3Aissue+json+opens++visual+studio+) on this repo in: #1586 #2599 #9511 #9738
