### ISSUE TITLE
The cursor shows up ahead to where it types

### ISSUE THREAD

**Issue by mohittandon** [microsoft/terminal#14834]
windows terminal i am using to ssh to my ec2 instances, initially it worked very smoothly however it now shows the cursor almost 2 inches ahead to where it types
alos the text and commands shows too many spaces
tried all possible settings it did not worked, then I uninstalled the same so as to re-install it, but now ms-store shows me the option to click "open" instead of "get", as the terminal is no longer in my PC.
how to again install it, and get rid of the so many spaces, and the cursor which flashes almost 2 inches toowards the right from where I type.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

What version of the Terminal are you using?

**Comment by zadjii-msft** [comment]
A note from discussion: This might be due to picking a non mono-spaced font. As an example:

![image](https://user-images.githubusercontent.com/18356694/218770925-6cd16d9e-e851-4ab9-b4a0-8507d5531f2c.png)
