### ISSUE TITLE
Not able to type when launching with runas

### ISSUE THREAD

**Issue by bitsadmin** [microsoft/terminal#14831]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Launch a regular elevated cmd.exe prompt (Start menu -> search for `cmd.exe` -> **Run as administrator**)
2. Execute the following command: `runas.exe /netonly /user:testtest wt.exe` (username and password don't need to be valid)

### Expected Behavior

When launching Windows Terminal using `runas.exe` from an elevated `cmd.exe` prompt I expect a usable Windows Terminal application.

### Actual Behavior

**Not possible**
* Enter text in the console
* Press enter to go to a newline
* Any shortcuts like `Ctrl` + `Shift` + `1` to launch a new terminal

**Possible**
* Paste text in the console; when pasting multiple commands with newlines like [1], the commands are executed
* Click on any buttons in the interface, which then work as expected
* Only once using the mouse the *Settings* panel has been opened, shortcuts like `Ctrl` + `Shift` + `[digit]` or `Ctrl` + `Alt` + `[digit]` work sometimes (unclear under which conditions)

[1] Example of multiple commands which can be copy/pasted
```
Get-ChildItem
whoami.exe

```

**Comment by zadjii-msft** [comment]
This sounds like /dup #9971 to me, thanks!
