### ISSUE TITLE
Context menu not being shown after uninstalling one of the Terminal [IT NEEDS FIX!]

### ISSUE THREAD

**Issue by gbr000** [microsoft/terminal#14836]
### Windows Terminal version

Last one (from both versions)

### Steps to reproduce

1. Install Terminal Stable in Windows Store
2. Context Menu shows
3. Install Terminal Preview in Windows Store
4. Contex menu still there
5. Uninstall Terminal Stable
6. Context menu dissapear!

### Expected Behavior

1. Context menu not being uninstalled when Terminal Preview still there!

### Actual Behavior

1. Context menu being uninstalled even though I have another Terminal (Terminal Preview) installed!

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9857 for more discussion.

/dup #9857
