### ISSUE TITLE
Escape characters surround pasted text inside ssh sessions

### ISSUE THREAD

**Issue by yellowpattern** [microsoft/terminal#14838]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19045.2486

### Steps to reproduce

Through use of ssh sessions inside Windows Terminals (tab'd), the application is now inserting ^[[200~ before some text and ^[[200~ after some text in some Windows, just ^[[200~ in others and also ^[[200~^[[200~^[[201~. There is inconsistent behaviour among the tabs (with respect to the exact escape sequence inserted) except to say that paste is now broken in all of them.

### Expected Behavior

Plain text to be pasted.

### Actual Behavior

Escape characters before and after (in some tabs).

**Comment by yellowpattern** [comment]
A similar problem is sometimes seen in MacOS iTerm2. That application has the ability to "Reset" a window (command-R) which resolves the problem. There is no such per-tab function available with Windows Terminal. I tried running "reset" from the terminal window and a "right-click" paste after that prints the follwing in cat:

^[[200~^[[200~^[[200~^[[201~^[[201~

**Comment by yellowpattern** [comment]
If I were to guess, judging by the comments in other tickets the problem lays in whatever it is that sends the "paste-block-start" not being able to send the "paste-block-end", potentially due to WiFi connection being lost, etc. If the only way to fix this is to quit all my terminals, I'm not a particularly happy camper.

**Comment by 237dmitry** [comment]
This behavior is observed in some terminal emulators and without ssh if you paste text with `ctrl-v` instead of `ctrl-shift-v` or `shift-insert`

**Comment by carlos-zamora** [comment]
Looks like this is a /dup of #14258. At this point, this seems to be an incompatibility issue between shells. See https://askubuntu.com/a/991550.
