### ISSUE TITLE
How do I install Windows Terminal on a Windows Server 2019 system?

### ISSUE THREAD

**Issue by David-Noble-at-work** [microsoft/terminal#1483]
I don't have access to the Store app. Must I build or can I download an installer to try out Windows Terminal?

**Comment by VimalShekar** [comment]
+1  
Need the appx package so we can use this on Windows Server.

**Comment by alexrjs** [comment]
Yup, in some companies, Windows Store is simply disabled, so a download alternative would be excellent...

**Comment by DHowett-MSFT** [comment]
I'm going to make #1386 the master issue for alternate distribution mechanisms. Thanks!

**Comment by cup** [comment]
https://github.com/microsoft/terminal/issues/1386
https://github.com/microsoft/terminal/issues/1405
https://github.com/microsoft/terminal/issues/1480

https://github.com/microsoft/terminal/issues/1483
https://github.com/microsoft/terminal/issues/1541

**Comment by nnit-TroelsJensen** [comment]
I have not been able to install Windows Terminal on a Server 2019 machine!
![image](https://user-images.githubusercontent.com/11349349/92456514-51b5b100-f1c3-11ea-8138-1730c22f0257.png)

**Comment by DHowett** [comment]
That error message indicates that your build of Windows is too old.

**Comment by ReillyBrogan** [comment]
@DHowett Well, can the install requirement be reduced to 1809 instead? Or does it rely on APIs that aren't present in that version?

**Comment by DHowett** [comment]
It does rely on APIs that are only present in 1903 and above.

**Comment by DHowett** [comment]
If we did not have a technical limitation, we would not impose such an otherwise arbitrary restriction.

**Comment by David-Noble-at-work** [comment]
I just installed the latest Windows Server 2019, the September 2020 release, OS Version 10.0.17763.1457. Apparently that's not sufficient for Windows Terminal which requires 10.0.18362.0 or greater. Where does one get a copy of Windows Server 2019 that meets the requirements imposed by the current Windows Terminal?

**Comment by zadjii-msft** [comment]
@David-Noble-at-work I don't believe there's a Windows Server release at/above version 10.0.18362 yet, sorry 😞

**Comment by ReillyTevera** [comment]
@David-Noble-at-work @zadjii-msft That's not completely true. You are correct that there is not yet a full release (2019, 2016 etc) past that version however Windows Server is also available under the "Semi-Annual" release channel which follows the cadence of Windows 10 releases. You need to have volume licensing and active Software Assurance to use that channel however, and given that Microsoft has had some major QA issues around the Windows 10 feature releases (and Windows Server shares the same codebase) I wouldn't recommend using that for any workload that is something you care about, especially if your only reason for using those releases is for Windows Terminal.

**Comment by soundarmoorthy** [comment]
Why not have a simple installer that can be used to install it on windows server 2019 ? Does it require any dependencies that would complicate the installation in windows server 2019 ? I am reasonably sure that much of the IT Admin community would appreciate such an availability. Forget 2019, i am not able to install on 2016 as well, If that helps.

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/issues/1483#issuecomment-691566254

https://github.com/microsoft/terminal/issues/1483#issuecomment-691566330

Please consider reading a thread before you comment on it.
