### ISSUE TITLE
Disable rightclick-to-paste

### ISSUE THREAD

**Issue by DaMoksha** [microsoft/terminal#14849]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Steps to reproduce

rightclick in Windows terminal / cmd / powershell.
clipboard contents are pasted.

### Expected Behavior

Rightclick should open a context menu. It should not perform an action, it should not paste.

I can use shift+insert or ctrl+shift+v to paste. I do not need or want any other way to paste.

If some people really need rightclick-to-paste, it should be easy to disable it. In Windows 10 it was easy to disable QuickEdit mode. It should be easy to find help that gives instructions to disable rightclick-to-paste.

I have "automatically copy selection to clipboard" turned off, but no matter what I do, selection is still copied to clipboard.

### Actual Behavior

Paste on rightclick is dangerous, inappropriate, inexcusable behavior.

**Comment by j4james** [comment]
In the short term this will likely be covered by issue #3337 - you'll be able to choose to have a right click menu instead of the current paste behavior. In the longer term you'll be able to choose exactly which operation a right click performs - that's covered by issue #1553.

**Comment by zadjii-msft** [comment]
Yep, thanks!

/dup #3337
