### ISSUE TITLE
Have an option for quake mode to open in center of the screen

### ISSUE THREAD

**Issue by pcause** [microsoft/terminal#14842]
Add an option for the quake mode to open in the center of the current desktop/virtual desktop

<!-- 
Quake works imn a similar fashion to various Linux terminal that dropdown.  I use tmux a lot and can have a popup window appear in the middle of the screen/terminal window.  Personally, I find this is better for focus.

# Proposed technical implementation details (optional)

In settings for quake, perhaps in appearance or advanced, add an option to select whether quake opens at top of the screen or middle.

**Comment by zadjii-msft** [comment]
You don't need quakeMode for that, you could just do a [`globalSummon`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon) with a [`centerOnLaunch`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#center-on-launch). Does that work for you/?

**Comment by pcause** [comment]
thanks and yes, think that gets me close enough.  Hadn't plowed through all the terminal docs since early days.
