### ISSUE TITLE
Crash on browse for icon

### ISSUE THREAD

**Issue by JVimes** [microsoft/terminal#14848]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Add a new profile > New empty profile (or duplicate profile)
2. Icon > Browse...

### Expected Behavior

Browse for icon

### Actual Behavior

Crash (process disappears, no error message).

**Comment by j4james** [comment]
This looks like a duplicate of #14808.

**Comment by zadjii-msft** [comment]
Sure is, thanks! 

/dup #14808

**Comment by vexc77** [comment]
bro u gotta chill with all this shit bro, i mean come on do you do anything
besides github repos?

**Comment by vexc77** [comment]
sorry bro that wasnt me that was my..,. dead cat
