### ISSUE TITLE
Rendering improvment request: temporarily disable text layouting when window is doing maximizing and restoring from maximizing

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#14855]
# Description of the new feature/enhancement

When the Terminal window maximizing/restoring under Windows 11, Windows(maybe DWM?) will make that action animationized. This will make Terminal recalculating the width/height of the display area per frame, and eventually cause text re-layouting and rendering with different results. At the first few frame, it will looks unstable and flashing。

below is some frames while Terminal window is maximizing:

* the begining state: normal (***misplaced prompts is intentional***)
![image](https://user-images.githubusercontent.com/1884240/219036797-8d7f2732-7e2d-4b35-a21a-45b64ded7d67.png)
* the first few frames one by one:
![image](https://user-images.githubusercontent.com/1884240/219037371-54f4d7b9-0431-45a8-9f6d-fbf821b4b58a.png)
![image](https://user-images.githubusercontent.com/1884240/219037429-79f6644b-112c-4324-aa4f-0c0eb29756aa.png)
![image](https://user-images.githubusercontent.com/1884240/219037499-52b89938-dad7-4b80-a49d-e5a050fd1db4.png)
* nearly to the last frame:
![image](https://user-images.githubusercontent.com/1884240/219038956-e1de023a-0668-421e-be5c-45d1cf87633f.png)

The first one or two frame looks unstable, starting from the 3rd frame, it looks same to the final state.So, can the Terminal just shortly disable/ignore layout calculate works while it starts doing maximizing/restoring?

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
I'd definitely like to get more info on this. On my Windows 11 (builds 22000 and 25298!) machine, maximize and restore _do not commit the size to the application until they are complete._ There is no intermediate step during which the application is struggling under the weight of a thousand `WM_SIZE` messages. :smile:

**Comment by epiciskandar** [comment]
> I think I'm having a bit of a hard time understanding

Actually, it is what you understand, sorry but unfortunately(and luckily too?) I can not reproduce that again, and I have not save that recording video..

One thing I forgot to say is I disabled acrylic while transparent is on, that makes window animation a little different to when acrylic is on, but I too discovered other application windows have the same effect, so that is something another about Windows OS.

I'm closing this and will reopen if that occur again, thanks.
