### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by OmarAbuAbdullah69** [microsoft/terminal#14850]
### Windows Terminal version

7.3.2

### Windows build number

10.0.19045.0

### Other Software

neovim 0.8.2 for windows
there is sometimes in neovim we need to configre our neovim to our need with some shortcuts
but the windows terminal capture them and neovim does not detect it 

### Steps to reproduce

in neovim there is a shortcut "ctrl+v" and we can add a shortcut to neovim like "ctrl+tab"
and use them in neovim

### Expected Behavior

i expected windows terminal gonna send the input after capturing it and send it to the currently running app inside it

### Actual Behavior

windows terminal turned out to capture a lot of shortcuts but not sending them to the app running inside it
that's actually unexpected behavior from windows terminal because 
that is the main purpose of it

**Comment by zadjii-msft** [comment]
If there are any keybindings that you don't want the Terminal to use, you can always [unbind them in your settings](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#unbind-keys-disable-keybindings).

```json
{ "keys": "ctrl+v", "action": "unbound" }
```

**Comment by OmarAbuAbdullah69** [comment]
@zadjii-msft I know this trick
But there is a lot of shortcuts just reappear in the json settings like "ctrl+tab"
You can delete it but once you get back to the terminal and use it it just doesn't respond but the application still can't detect it to
The "ctrl+c" and "ctrl+v" worked for me
