### ISSUE TITLE
Bug Report - Jun 2019 Terminal Preview only draws window frame

### ISSUE THREAD

**Issue by bhunsaker** [microsoft/terminal#1486]
# Environment

Windows 10 32-bit Release 1903
Windows Terminal June 2019 Preview installed from the Windows Store

# Steps To Reproduce

When opening Windows Terminal, only the window frame is displayed.  The desktop background is visible within the frame.  I cannot drag the window using the mouse.
![WinTermHang20190623](https://user-images.githubusercontent.com/1426962/59979950-a4e21a80-95a3-11e9-9bb9-e6ee412ace96.png)

**Comment by dlhendry** [comment]
Same Issue as noted above.  Event log Application Error.  
Windows 10 Home
Version 1903
Installed on 6/23/2019
OS Build 18363.175

Log Name:      Application
Source:        Application Error
Date:          6/23/2019 5:17:53 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-xxxxxxxx
Description:
Faulting application name: WindowsTerminal.exe, version: 1.0.1906.20005, time stamp: 0x5d0c1459
Faulting module name: TerminalApp.dll, version: 1.0.1906.20005, time stamp: 0x5d0c140d
Exception code: 0xc0000005
Fault offset: 0x000000000003a539
Faulting process id: 0x2890
Faulting application start time: 0x01d52a091eb28586
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: d0296a46-7e2a-474b-a564-8f812c8b3e0c
Faulting package full name: Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-06-23T21:17:53.904081000Z" />
    <EventRecordID>162</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-2SV0D79</Computer>
    <Security />
  </System>
  <EventData>
    <Data>WindowsTerminal.exe</Data>
    <Data>1.0.1906.20005</Data>
    <Data>5d0c1459</Data>
    <Data>TerminalApp.dll</Data>
    <Data>1.0.1906.20005</Data>
    <Data>5d0c140d</Data>
    <Data>c0000005</Data>
    <Data>000000000003a539</Data>
    <Data>2890</Data>
    <Data>01d52a091eb28586</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\TerminalApp.dll</Data>
    <Data>d0296a46-7e2a-474b-a564-8f812c8b3e0c</Data>
    <Data>Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by DHowett-MSFT** [comment]
So you mean #1364? Thanks for reporting. Please search before filing a new issue!
