### ISSUE TITLE
After update, windows terminal settings.json overwritten to default

### ISSUE THREAD

**Issue by nairobi02** [microsoft/terminal#14862]
### Windows Terminal version

1.16.10261.0

### Windows build number

19045.2486

### Steps to reproduce

Update windows terminal on microsoft store
open windows terminal

### Expected Behavior

the old settings.json, prior to update should still be used, or atleast backed up.

### Actual Behavior

default configuration is showing up everywhere across the terminal. including appearance for each profile.
the settings.json has been overwritten, only default settings remain.

**Comment by zadjii-msft** [comment]
That's extremely unexpected. When you open the settings and hit "Open JSON File", what's the path of the file that opens? 

Do you have Terminal Preview installed as well/?

**Comment by nairobi02** [comment]
> That's extremely unexpected. When you open the settings and hit "Open JSON File", what's the path of the file that opens?
> 
> Do you have Terminal Preview installed as well/?

The path is C:\Users\Nair\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState

I don't know what terminal preview is, and so i don't think i have it installed. 
I'm not sure how this happened, all i know is, this happened after it got updated from microsoft store.

**Comment by zadjii-msft** [comment]
Huh. That's perfectly normal. Any chance you had the settings file open in an editor of any sort/? Something that might have locked the file, or done a swap-to-save sorta operation? 

Sorry this happened! But I really don't know how we'd be able to investigate if this isn't something that reproduces readily 😕 This might have even just been the appx/msix service botching the update, which would be terribly sad and entirely out of our control.
