### ISSUE TITLE
Terminal app is opening and closing rapidly when "Run as administrator" is enabled

### ISSUE THREAD

**Issue by StragaSevera** [microsoft/terminal#14879]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.2604

### Steps to reproduce

1. Open terminal application.
2. Go to Settings -> Defaults (or to a default profile).
3. Enable "Run this profile as Administrator".
4. Close application.
5. Open it again.

### Expected Behavior

Application is opening normally.

### Actual Behavior

The button on taskbar blinking, opening and closing the app, while the process is spawning and de-spawning in Process Manager.

**Comment by jamespack** [comment]
This happens to me at work where my user account is different from my administrator account. To fix it I have to login with my Admin account and run terminal. Then I can log back in to my standard user account and run as administrator. I used to be able to fix it by reregistering the appx as admin but that stopped working a while back

**Comment by cloud-66** [comment]
I have the same bug. Also all shells run as administrator despite that "Run this profile as Administrator" is disabled. And i don't know how to run shell as non administrator

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13928  for more discussion.

/dup #13928
