### ISSUE TITLE
Bug Report - Terminal not responding after closing

### ISSUE THREAD

**Issue by archie7652** [microsoft/terminal#1487]
# Environment

```none
Windows build number: 1903 (18362.175)
Windows Terminal (Preview) from Microsoft Store (current release)
```

# Steps to reproduce

When closing the unique tab or closing application.

# Expected behavior

Close application normally.

# Actual behavior

The terminal is not responding after closing.

**Comment by Tajmaha** [comment]
Closing by middle mouse button or CTRL+W will also cause the terminal to crash. It seems like whenever a powershell tab it crashes. Closing out a CMD tab (clicking the X, middle mouse, or CTRL+W) seems to work fine.

**Comment by DHowett-MSFT** [comment]
I believe this is #1380
