### ISSUE TITLE
Some glyphs do not display correctly until the settings are saved.

### ISSUE THREAD

**Issue by igorkuzuro** [microsoft/terminal#14875]
### Windows Terminal version

Build from current source code

### Windows build number

10.0.25295.0

### Other Software

PowerShell core 7.3.2
Oh My Posh version 14.7.0
Delugia font (https://github.com/adam7/delugia-code)

### Steps to reproduce

I use Oh My Posh segment which using character \uf199f (Timer Sand Complete or nf-md-timer_sand_complete from https://www.nerdfonts.com/cheat-sheet) This character did not display correctly until I just open settings and press Save...
After the terminal is restarted, the error reappears.

Terminal using Delugia font as default and for Powershell Core

See screenshots: upper part before Save settings, lower part - after.

![ss](https://user-images.githubusercontent.com/1778999/219884888-e93ccff8-d0cb-414f-bbf0-88eca63ca11f.jpg)

### Expected Behavior

Glyph rendered as Timer Sand Complete

### Actual Behavior

Glyph rendered as "placeholder" character

**Comment by lhecker** [comment]
Did you recently update your font? This could be a corruption in the font cache service. You could try restarting the service in PowerShell, as an Administrator, using this command:
```pwsh
Restart-Service FontCache
```

Did you install this font for your current user only or for all users (`%LocalAppData%\Microsoft\Windows\Fonts` vs. `C:\Windows\Fonts`)? Or does the font potentially exist in both directories in different versions? Using the latter exclusively might be more robust.

**Comment by igorkuzuro** [comment]
> Did you recently update your font? This could be a corruption in the font cache service. You could try restarting the service in PowerShell, as an Administrator, using this command:
> 
> ```powershell
> Restart-Service FontCache
> ```
> 
> Did you install this font for your current user only or for all users (`%LocalAppData%\Microsoft\Windows\Fonts` vs. `C:\Windows\Fonts`)? Or does the font potentially exist in both directories in different versions? Using the latter exclusively might be more robust.

Yes, after install the font for all users, the problem disappeared.

**Comment by carlos-zamora** [comment]
Awesome! We're gonna close this out and mark it as a /dup of #3257
