### ISSUE TITLE
How to set the linespace?

### ISSUE THREAD

**Issue by 1538379200** [microsoft/terminal#14882]
I needed to set up linespace for neovim, but I didn't find it.

**Comment by zadjii-msft** [comment]
I'm afraid you're going to need to be more specific. Is the line spacing too big? Too small? What font are you using? Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/? What version of the Terminal are you using? 

Sounds a lot like #3498 to me - is that what you're looking for?

**Comment by 1538379200** [comment]
I want to customize my spacing but not change my font size. Like:
```json
{
	"font": {
		"linespace": 8,
		"face": xxx,
		"size": 14,
	}
}
```
The configuration of cellHeight is not quite the same as I imagined.

**Comment by lhecker** [comment]
How is it not quite the same? If I understand you correctly, a `cellHeight` of `22pt` should achieve this. The pull request #14255 will only ship with the next preview version however (1.18).

**Comment by 1538379200** [comment]
Maybe I should wait for 1.18😢
![image](https://user-images.githubusercontent.com/42434762/220510585-6a8f67ce-85cc-43bd-b390-9f6c2f42cc06.png)
