### ISSUE TITLE
Consider options to not always tick shaders

### ISSUE THREAD

**Issue by Dan-Albrecht** [microsoft/terminal#14888]
# Description of the new feature/enhancement

I love running complicated shaders. It's not uncommon for my old laptop to sustain in excess of 25% GPU usage (I'm fine with that, this isn't a 'shader perf sucks' bug). It'd be beneficial to power, heating my lap, etc. if we didn't always have to tick them.

# Proposed technical implementation details (optional)

Couple ideas:
1. Stop rendering if Window/pane is not activated
1. Stop rendering if Window/pane is fully obscured
1. Stop rendering if Window is minimized

My immediate thought is there's no value to render what you cannot see, so I'd just make this the _new behavior,_ but I'm sure there's a [workflow](https://xkcd.com/1172/) that wants this, so 'smart ticking' can be config enabled. You can still see the animations in cases 1 & 2 through alt + tab preview and hover on the taskbar, but for 3 any previews are static so there'd be no loss there, but that would be my least preference as I never remember to minimize windows.

Seems like toggling `requiresContinuousRedraw` in `AtlasEngine` would be a straightforward path.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think overall, we're tracking this in /dup #1989. Checking if the window/pane is "fully obscured" might be a bit more tricky, but the other two are very doable. We might get a window message of some sort when the OS is preparing an alt-tab. That might be a good opportunity to force a repaint, so the thumbnail is at least close. 

Thanks!

**Comment by DHowett** [comment]
I believe we did some work (it might only be in the new renderer -- if so, we should backport it) to only tick shaders that require the `time` parameter as well. At the very least, we're not wasting time on static shaders :D
