### ISSUE TITLE
Retro terminal effects do not work while Software rendering is enabled

### ISSUE THREAD

**Issue by SubsTheTechnomancer** [microsoft/terminal#14880]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19044.0

### Steps to reproduce

- Open any terminal tab
- Ensure the tab has "Retro Terminal Effects" on in its Appearance settings
- Turn on Software Rendering

### Expected Behavior

Retro Terminal effects are displayed for tabs as normal

### Actual Behavior

Retro Terminal effects are missing or not being rendered

**Comment by SubsTheTechnomancer** [comment]
Images to illustrate follow.
With Software Rendering Enabled:
![image](https://user-images.githubusercontent.com/54163143/219956648-a8f05977-5908-4c62-941b-bd135ca15458.png)
With Software Rendering Disabled:
![image](https://user-images.githubusercontent.com/54163143/219956689-163cf9db-6c4f-44c1-9d18-9f5ffebd58b3.png)

**Comment by zadjii-msft** [comment]
I'm _pretty sure_ that's by design - using software rendering tells the Terminal to not use the GPU, while the retro effects are specifically a GPU shader effect. 

Do you have "Use the new text renderer" enabled (under profile > advanced in the settings)?

**Comment by lhecker** [comment]
Yep this is entirely intentional on my part. I made it like that, because if you reboot without graphics drivers installed and could only use WARP (= software rendering), it would still result in a somewhat useable and performant terminal. Shader effects like that would make the terminal significantly slower in that situation.

Is there a situation in which you'd want to use shader effects and software rendering simultaneously?

**Comment by SubsTheTechnomancer** [comment]
> Do you have "Use the new text renderer" enabled (under profile > advanced in the settings)?
No, AtlasEngine is off for all of my profiles. I'm a little surprised that this is meant to be intentional though, because I also use the non-preview version of Terminal and this setup works fine there.
> Is there a situation in which you'd want to use shader effects and software rendering simultaneously?
There isn't any important requirement to use this per se, it is just more convenient for me (and maybe others in my situation) whose GPU performs much better than the hardware renderer.

**Comment by lhecker** [comment]
> There isn't any important requirement to use this per se, it is just more convenient for me (and maybe others in my situation) whose GPU performs much better than the hardware renderer.

The hardware renderer is using the GPU for text rendering. Did you mean to write CPU? Or is the GPU based hardware renderer actually performing worse than the CPU based software renderer for you?

**Comment by SubsTheTechnomancer** [comment]
> The hardware renderer is using the GPU for text rendering. Did you mean to write CPU? Or is the GPU based hardware renderer actually performing worse than the CPU based software renderer for you?

Yeah, oops, sorry I did mean CPU. It's a work laptop 🤷🏼 
Maybe the intentionality of this design could be highlighted somewhere next to the options? It really wasn't clear to me that it was intentional. I get that this is really a non-issue, would just make it a little clearer.
