### ISSUE TITLE
Windows Terminal Preview not showing settings

### ISSUE THREAD

**Issue by spectrumcomputing** [microsoft/terminal#1488]
<!--
This bug tracker is monitored by Windows Terminal development team and other technical folks.

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.
Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible.

Which I launch settings in Windows Terminal Preview and it asks to open Windows Store

# Environment

```none
Windows build number: [run "ver" at a command prompt] Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): 0.2.1715.0 - Installed via Windows Store.

Any other software?
```

# Steps to reproduce

Click on the down arrow next to the '+' on the top bar, select 'Settings'

# Expected behavior

Go to settings menu

# Actual behavior

Brings up a prompt - How to you want to open this file.  Default option is Windows Store, tick box below says always use this to handle JSON files.

**Comment by Shorotshishir** [comment]
please refer to this issue #1460

**Comment by DHowett-MSFT** [comment]
Thanks for linking the duplicate. PLEASE search before reporting new issues.

**Comment by spectrumcomputing** [comment]
Apologies, I did search but obviously not well enough :-)
