### ISSUE TITLE
new linux features for windows 11

### ISSUE THREAD

**Issue by DuckyProgrammer5** [microsoft/terminal#14899]
we all know that the new windows terminal has cool features that includes Linux running on the terminal right.
but it only supports for windows 10 systems, and I am running a windows 11 and I am sending this issue for Microsoft to fix the windows 11 terminal so it can have the Linux features.

**Comment by zadjii-msft** [comment]
> it only supports for windows 10 systems

Uh, no? The Windows Terminal is fully supported on Windows 11 - it even ships preinstalled with the Windows 11 OS!

What "linux features" in particular are you talking about/?

**Comment by DuckyProgrammer5** [comment]
it shows you can run ubuntu on the terminal and im going to reinstall it

**Comment by zadjii-msft** [comment]
You're gonna have to add more details. Maybe some screenshots. 

You can absolutely install WSL & WSL distros on Windows 11. The Terminal should detect those automatically and generate Terminal profiles for you. That's all the same on both Windows 10 and Windows 11.

**Comment by DuckyProgrammer5** [comment]
i did not got the updates right here
![Windows term problem](https://user-images.githubusercontent.com/123731854/220944438-b8b78c1f-2f03-4465-981e-c63953de449b.png)

**Comment by DuckyProgrammer5** [comment]
and how do i do that?

**Comment by zadjii-msft** [comment]
[Install Linux on Windows with WSL](https://learn.microsoft.com/en-us/windows/wsl/install).

You'll need to restart the Terminal after installing a WSL distro, for the Terminal to pick up the freshly-installed WSL distro's profiles.

**Comment by DuckyProgrammer5** [comment]
got it now ive got to wait for the wsl.exe to do its job

**Comment by DuckyProgrammer5** [comment]
ok i will reboot my system as the terminal says : The requested operation is successful. Changes will not be effective until the system is rebooted.

**Comment by DuckyProgrammer5** [comment]
ok now the system is freshly rebooted

**Comment by DuckyProgrammer5** [comment]
ok it says adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
Enter new UNIX username:, when i type a username

**Comment by DuckyProgrammer5** [comment]
oh wait i get it

**Comment by DuckyProgrammer5** [comment]
Yes! im in and thank you
