### ISSUE TITLE
Cascadia Code static vs variable (VF) rendering

### ISSUE THREAD

**Issue by Finii** [microsoft/terminal#14891]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22000.1574

### Other Software

Cascadia Code release 2111.01

### Steps to reproduce

* Remove Cascadia Cove that comes bundled with Windows Terminal [1]
* Note that the bundled version is Cascadia Cove 2111.01 VF TrueType outlines
* Manually install Cascadia Cove 2111.01 static Regular TrueType outlines
* Start Windows Terminal
* Take screenshot of text with capitals and small-letter `i` at some bigger size (effect is not size dependent though)
* Close Windows Terminal, remove Cascadia Cove font
* Install Cascadia Cove 2111.01 VF TrueType ourlines
* Start Windows Terminal and repeat previous steps
* Compare screenshots

[1] For people like me that is hard, here is a manual:
<details>

<summary>MAINTAINER EDIT: DO NOT FOLLOW THESE STEPS. Changing the permissions on WindowsApps is a one-way street to pain.</summary>

* Gain access to C:/Programs/WindowsApps
* Set youself as owner for C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.3466.0_x64__8wekyb3d8bbwe
* Set youself as owner for all 4 font files in that folder
* Add full access right for everyone on the 4 fonts
* Move the 4 fonts to another location (e.g. desktop) - deleting is impossible
* Reboot
* Enjoy to be able to install whichever Cascadia Code you like and use Windows Terminal with that

Note that a Windows Terminal update reinstalls the bundled font, of course.
</details>

I'm not entirely sure if this should be reported here or at Cascadia Code. But the issue can not be seen on WordPad and also not in terminals on other platforms, so I guess it is something specific to Windows Terminal.

I tried `experimental.rendering.software` true and false (and also `experimental.useAtlasEngine`) but the outcome is unchanged.

Related issues, that as far as I can see all are due to the effect described in this issue.
* https://github.com/microsoft/cascadia-code/issues/371
* https://github.com/ryanoasis/nerd-fonts/issues/998
* https://github.com/ryanoasis/nerd-fonts/issues/519
* https://github.com/adam7/delugia-code/pull/79

The problem with the issues above was that they all compare the VF to the static ones and the VF is hard to get rid of.

### Expected Behavior

Both fonts should look the same. With maybe a very slight weight difference because one is interpolated on the fly.

### Actual Behavior

* The heights (capital and x) is visibly different
* The dot on the small letter `i` is noticable down (or stays in place while the dotless-i glyph resizes)

The effect is even visible in the font preview window.
For easier visual comparison I use a renamed copy of `Cascadia Cove Regular ttf` with the name `Delugia`.

The first image shows that `Delugia` and `Cascadia Cove static` render the same (at least no really noticable differences):

![static](https://user-images.githubusercontent.com/16012374/220341419-fc602f6f-f98f-4b05-a0e8-5a3515b3b558.gif)

The second image now compares `Delugia` and `Cascadia Cove VF ttf`. Because of the comparison above this is equivalent to comparing `Cascadia Cove static` to `Cascadia Cove VF`:

![VF](https://user-images.githubusercontent.com/16012374/220341449-68aa49a0-1187-4e3c-a971-dd819cfa8bab.gif)

**Comment by Finii** [comment]
Ok, then please advice me how I can get rid of the bundled font?

The steps described above are done in order to be able to bugfix (or rather triage) a problem, not for any 'normal' user.

**Comment by lhecker** [comment]
Couldn't you just install the 12 variants of "CascadiaCodePL" and then compare "Cascadia Code PL" with the builtin "Cascadia Code"? That way you wouldn't have to delete any fonts to reproduce the issue.

According to Visual TrueType we're rendering the text correctly.

@DHowett there seems to be something strange going on with the static variants of Cascadia Code. If I load them into VTT they look identical to the VF variant, but once I load the GASP table, I get warnings in VTT and the glyphs are suddenly 1px taller. With the lowercase "w" character at 12pt and 144dpi for instance, both initially load as 12px tall, but once the GASP table has loaded for the static variants its suddenly 13px tall.

**Comment by Finii** [comment]
> Couldn't you just install the 12 variants of "CascadiaCodePL" and then compare

In principle I could, but whatever the result I would never know if that is a difference between the vanilla and the PL version.
But thanks, that is still a good idea :+1:

> According to Visual TrueType we're rendering the text correctly.

I do not know that tool. But WordPad renders both fonts also identical. And Glyphs' TextPreview tool (used to check fonts after creation) also renders both identical :thinking: So far Windows is the only platform where I witnessed the problem.

One thing lingers still in the back of by head, I believe I had a discussion with aaronbell about the static fonts and that they are different in some way; unfortunately I can not find that thread anymore.

**Comment by Finii** [comment]
After re-reading the issue I linked myself for the 3rd time:

* https://github.com/microsoft/cascadia-code/issues/371

I guess this is the exact effect we see here. So it might be the autohinting that 'breaks' the static fonts; and has nothing to do with Windows Terminal per se.
I also have a user comment who sees the problem with Visual Studio on Windows.

So I guess this Issue is wrong **here** (as speculated in the beginning).

Thank you so much for looking into it!

I close this now, sorry for raising a red-herring.

**Comment by DHowett** [comment]
That's alright, thanks for following up!
