### ISSUE TITLE
Rendering suggestions and some questions!!!

### ISSUE THREAD

**Issue by xiaoyxue** [microsoft/terminal#14890]
# Add the FPS enable/disable button, remove the "Using software rendering"

1. About "Using software rendering", software rendering only cost the CPU performance, if a low-level CPU, this options totally reduce the computer's performance, if a high-level CPU whose GPU or standalone GPU totally can hold the rendering cost. So, I think this option is unnecessary.
2. Add the FPS display which can help if need the "Redraw entire screen when display updates", and another question: here the entire "screen" is the terminal window or the whole display monitor screen? From my understanding, it should mean the editor space in the window.
3. I want to how do you implement the cursor blinking in fixed frequency? Swap the frame and force vertical synchronization? Since this is related to ***point 2***. Does the cursor blinking belong to the "display updates"? I just guess that when only cursor blinking, fix a low frequency, when texts are being written, fix a high frequency and if keyboard is active, no frame swapping happen. Is my guess correct?
4. The same as #14888, he is totally correct
# Proposed technical implementation details (optional)
Just add an FPS button

## A clear and concise description of what you want to happen.
Just want to see the FPS and answer my questions, thanks!

**Comment by j4james** [comment]
1. The software rendering option is a debugging aid and workaround for hardware issues and display driver bugs (see the comments in commit d01317c9db7bdf43713d1641f13ab4b795bdb26b).
2. There's already an issue for this (see #6025).
3. As I understand it, cursor blinking is typically treated like any other screen update. The cursor cell is added to the set of screen coordinates that need refreshing, and it'll then be rendered on the next frame update. It might be more complicated in the new Atlas render engine though. But if you have further questions like this, the [Discussions](https://github.com/microsoft/terminal/discussions) area is the best place to ask.
4. If you want to indicate your support for an existing feature request, I'd recommend clicking on the 👍 button on that issue.
