### ISSUE TITLE
Auto Save Log

### ISSUE THREAD

**Issue by Window-YANG** [microsoft/terminal#14893]
# What device you're running (inc. CPU type, memory, disk, etc.)

设备名称	LAPTOP-112
处理器	11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz   2.50 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器

# What build of Windows your device is running
Microsoft Windows [版本 10.0.22000.1574]

# What tools and apps you're using (e.g. VS 2022, VSCode, etc.)
VS2022, VSCode

# Description of the new feature/enhancement
Needs：The output logs are saved automatically and continuously in the background each time a new terminal/pane is reopened.
Problem：I'm developing on linux, and sometimes I print a lot of logs, which I need to save automatically to txt, so I can open them later to check

# Proposed technical implementation details (optional)
1. Support for defining save file name format
2. terminal/pane log records are “automatically ” closed after disconnection

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #14018 for more discussion.

/dup #14018
