### ISSUE TITLE
Terminal hangs when exiting a debug tap session

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#14898]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19044.2364

### Steps to reproduce

1. Make sure the `debugFeatures` option is enabled in the settings.
2. Open a bash shell with a debug tab.
3. Exit the shell with `exit`.

### Expected Behavior

You should be left with the debug tab pane which you can then close.

### Actual Behavior

The terminal hangs.

Running from within the debugger, the main thread appears to be blocked on the `_createCloseLock` in `_ControlConnectionStateChangedHandler`, but there didn't appear to be any other threads holding that lock. I didn't spend that much time investigating, though, so it's quite likely I missed something.

**Comment by zadjii-msft** [comment]
idly: I wonder if #14548 helps / hurts

**Comment by zadjii-msft** [comment]
You know, I bet this was fixed by #15335. I can't repro this anymore, and the `_createCloseLock` was removed.
