### ISSUE TITLE
Unicode characters become ? at input but ok at output

### ISSUE THREAD

**Issue by Immueggpain** [microsoft/terminal#14894]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Other Software

PSVersion                      5.1.19041.2364

### Steps to reproduce

![termie](https://user-images.githubusercontent.com/13107071/220733957-30a60f37-bd02-45aa-a55a-630b3bff3f36.gif)

### Expected Behavior

Display actual characters, just like echo output.

### Actual Behavior

Display '?'

**Comment by DHowett** [comment]
Unfortunately, PowerShell 5.1 uses quite an old version of PSReadline, the "text editor" for your prompt line. If you use the new version of Powershell (7.3 at the time of this message), does it still reproduce your problem?

**Comment by Immueggpain** [comment]
> Unfortunately, PowerShell 5.1 uses quite an old version of PSReadline, the "text editor" for your prompt line. If you use the new version of Powershell (7.3 at the time of this message), does it still reproduce your problem?

I installed the Powershell 7.3.2 and it's working now. Thanks!

**Comment by DHowett** [comment]
That's great news! Thank you for following up.
