### ISSUE TITLE
Ctrl key can be stuck in Windows Terminal

### ISSUE THREAD

**Issue by devlie** [microsoft/terminal#14904]
### Windows Terminal version

1.17.1023

### Windows build number

 10.0.25300.1000

### Steps to reproduce

Not sure. Most of the time I'm just typing typical stuffs.

### Expected Behavior

`Ctrl` key is not stuck.

### Actual Behavior

I'm reopening #14343, which was suspected to be dupe of #14345/#14129, but those are supposedly fixed on the build I'm on.

After some times, Ctrl key will be stuck for a particular tab. I usually find out when hitting Backspace would delete the whole word even though I'm not pressing down Ctrl key, or typing some alphabets would produce something like ^A

I'm positive the problem is scoped to a Terminal tab:
- If I open a new tab, the issue doesn't persist.
- The problem doesn't repro on Windows Run dialog (WIN+R) while issue is happening.

**Comment by lhecker** [comment]
Can you try the solution of the other issue that was linked (#14338)? In other words, if you're using PowerShell, try running this:
```pwsh
echo "`e[?67;9999l"
```

**Comment by devlie** [comment]
@lhecker / @j4james  what's the command for cmd.exe? I'm reproing this issue in regular cmd, not just powershell.

**Comment by zadjii-msft** [comment]
(OP responded to us on an internal mail thread - we're waiting for another repro to get the text of a debug tap. I didn't see any `?67h`'s in the output of the tap, but I was just scanning a screenshot. There were a couple git commands around the time of the repro, maybe there's some other API that triggers it?)

**Comment by j4james** [comment]
Bear in mind that the issue reported by the OP was that the <kbd>Ctrl</kbd> key was stuck in general, e.g. seeing `^A` when typing an <kbd>A</kbd>, so it's not just <kbd>BkSp</kbd> becoming <kbd>Ctrl</kbd>+<kbd>BkSp</kbd>. That makes me think it's unlikely to be related to `DECBKM`.

**Comment by zadjii-msft** [comment]
OP replied in email and this issue hasn't come back since they recently paved their machine. We'll close till it comes back (if it ever does)
