### ISSUE TITLE
'Open as Admin' at the dropdown list

### ISSUE THREAD

**Issue by thomassth** [microsoft/terminal#1490]
# Problem

- Many of us want open a sudo/elevated/root/admin session easily
- MS seems reluctant to allow root tabs mixing with non-root tabs, citing security issues

# Proposed implementation

- "Learning" from File Explorer (and several Linux file manager software), add a "Open Terminal as administrator" within the dropdown menu.
  - Allows keyboard shortcut binding = shorter time
  - Separate root and non-root tabs into different windows = less security issues(?)
- "Open as administrator" = Open current environment & location as administrator
- Allow config to open specific root powershell/cmd/WSL location with keyboard shortcuts
- Tint the whole root window to red color or something to aesthetically separate root and non-root windows

**Comment by richardszalay** [comment]
To add my 2c: I feel like "CTRL+SHIFT+(num)" should actually be the shortcut to run as Administrator. CTRL+SHIFT is the shortcut to run as Admin in both the start menu and in the run dialog, so it would feel more consistent if it did so here.

**Comment by DHowett-MSFT** [comment]
**please make sure you search before adding a new issue** #1032 covers all of these

**Comment by thomassth** [comment]
#1032 does not cover all of these nor the problem is completely unsolvable. But since that's the megathread I would continue the discussion over there.
