### ISSUE TITLE
Acrylic title does not work completely

### ISSUE THREAD

**Issue by SnowMeteors** [microsoft/terminal#14916]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.2604

### Steps to reproduce

![image](https://user-images.githubusercontent.com/47601098/221486493-68db6af3-1a61-4d40-80bf-0d95efb3db23.png)
acrylic tab row open

### Expected Behavior

I want the acrylic background to be covered with headlines

### Actual Behavior

![image](https://user-images.githubusercontent.com/47601098/221486739-c2a2442e-1c2e-4c1b-9e99-4be324473f4d.png)
the title and Tab function bar not working，It's too uncoordinated and looks ugly

**Comment by zadjii-msft** [comment]
This is something that should work better in 1.17 (and maybe 1.16?) by editing the [theme](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes). At the very least, in 1.17, you can set the tab.background to something like `#00000000` and get transparent tabs, or (for example) `#ff000044` for semi-transparent red tabs:

![image](https://user-images.githubusercontent.com/18356694/222417686-c44b83b5-8ce0-43fe-8d83-3368bcad1021.png)
