### ISSUE TITLE
Opportunity to change current tab color programmatically. 

### ISSUE THREAD

**Issue by rutexd** [microsoft/terminal#14910]
# Description of the new feature/enhancement

Windows-Terminal needs an api/way to allow change current tab color. This should allow more flexibe behaviour of a Terminal.
For example, this would make possible using any custom shell (like nushell) change color on any command or path, like red color tab on ssh or green color tab on specific project path.

# Proposed technical implementation details (optional)

There basically two ideas. 
1. Modify wt.exe to allow wt.exe to change current tab state.
2. Adding env variable like wt-color (or something) that contols current tab color, if desired behaviour of wt.exe isnt possible.

**Comment by j4james** [comment]
There are already escape sequences you can use to change the tab color. For more information, see the discussion thread here: https://github.com/microsoft/terminal/discussions/14903#discussioncomment-5104434.

**Comment by rutexd** [comment]
I dont sure i actually get it. 
I tried to repeat of all commands from thread above and none worked for me, they just being printed with no effect. I tried powershell and in in classical command line (ofc both inside of a Windows Terminal)

My terminal version is 1.16.10261.0 , so if i understand versionning of wt right, this should work.

**Comment by j4james** [comment]
I believe this functionality was added in version 1.15, so 1.16 should work. But if you're using Windows PowerShell (as opposed to PowerShell 7), you can't use the `` `e `` escape character, so you'd need to do something like this:

    echo "$([char]27)[2;15;1,|"

Does that work for you?

**Comment by rutexd** [comment]
Hell yeah, this works. 
Thanks! :)
