### ISSUE TITLE
Feature Request: Grid system

### ISSUE THREAD

**Issue by reinaldorauch** [microsoft/terminal#1491]
# Summary of the new feature/enhancement

A grid system like in the [Terminator](https://gnometerminator.blogspot.com/p/introduction.html) app or in [tmux](https://github.com/tmux/tmux/wiki)

It helps to leverage of large screens of modern computers splitting the screen in half verticaly and/or horizontally to acomodate many shells in a tab or window.

**Comment by DHowett-MSFT** [comment]
So, #1000?

**Comment by reinaldorauch** [comment]
@DHowett-MSFT Sorry, I didn't knew about panes as synonym to grid. English is not my mother language. Thanks to your time to explain that, very appreciated.

**Comment by DHowett-MSFT** [comment]
Sure thing! Sorry about being terse. We've got a huge number of feature requests to get through. :smile:

**Comment by reinaldorauch** [comment]
No problem, didn't wanted to be ironic :(

> We've got a huge number of feature requests to get through

I see, keep up the good work! Awsome initiative from Microsoft o/
