### ISSUE TITLE
Neovim/tmux rendering glitches after resize

### ISSUE THREAD

**Issue by parkovski** [microsoft/terminal#1492]
# Environment
- Windows 10.0.18362.175
- tmux
- Neovim 0.3.7

# Steps to reproduce

Open Neovim (Windows version) inside of tmux and resize the window. If it's not glitching yet, try scrolling around with Ctrl-D/Ctrl-U. Making the window smaller seems to be ok sometimes, but I see glitches if I maximize, restore, resize the window to be larger, or resize a tmux pane. Interestingly, regular vim has problems with maximize/restore, but not resizing by dragging the window edge. I think there is a separate bug there but I'll keep that to a separate issue.

Now for the really strange part. Open a second console window. Tmux and neovim are fixed now. Resize the first window to make it glitchy again, and then resize the second window. Fixed again.

Somehow resizing a regular console window makes unrelated PTY buffers set the correct size.

# Expected behavior

For one, resizing should not make programs glitchy, but I certainly didn't expect the sort of "fix" I found either.

# Actual behavior

[Probably better to just show what's going on.](https://vimeo.com/343970593)

**Comment by ibuioli** [comment]
This is a common error on Terminals that working on Windows and the WSL (Hyper has the same bugs). However it must be fixed. This happend on tmux, vim, neovim and even nano. Here is a screenshot of Nano, when resize Terminal to fullscreen and then window size again:

![nano_on_wt](https://user-images.githubusercontent.com/7343538/60036023-a0d9f980-9684-11e9-8744-ef40d6841eb3.png)

The "bottom tools" broken, and the format of space is incorrect.

**Comment by andrp92** [comment]
This same behavior also happens when using powershell, windows terminal, or cmd to connect through ssh to any linux like enviroment and trying to edit a file using nano, vi, vim or any other editor. git-bash handles this properly. It would be great if we can have this messy issue fix.

**Comment by DHowett-MSFT** [comment]
Using #1465 as the main issue tracking resize.
