### ISSUE TITLE
Quake Mode:  Open top/right corner of desktop

### ISSUE THREAD

**Issue by mkanet** [microsoft/terminal#14924]
Is there a way yet to specify which part of the screen Quake Mode will open?  For the last couple of years, I've been using the below utility to add this feature to MS Terminal: https://github.com/flyingpie/windows-terminal-quake which does this perfectly.

Anyway, I'm curious if there's a way to do it natively instead of relying on a 3rd party utility.

**PS:**  I also noticed that native Quake Mode in MS Terminal still draws the acrylic blur effect too slow.  Windows-terminal-quake fixes this issue too.

**Comment by mkanet** [comment]
Thanks for your help.  Yes, I think those links are what I'm asking.

The problem is that MS Terminal Quake mode doesn't honor the below settings.  Also, native MS Terminal Quake mode seems to be **super clunky when using Acryllic Blur effect**; even on a fast PC.

```
    "initialCols": 134,
    "initialPosition": "962,0",
    "initialRows": 26,
```

The expected behavior is _exactly_ as shown in the video below.  It opens in the correct part of the screen and animates VERY smoothly with Acryllic Blur effect.  I'm currently relying on https://github.com/flyingpie/windows-terminal-quake to handle Quake Mode for MS Terminal since it looks like both issues are still present with MS Terminal.  

I uploaded the video clip to youtube so you can see just how smoothly quake mode _could_ be natively.

https://youtu.be/OFrvWorrzBc

**Comment by zadjii-msft** [comment]
Okay yea that sounds like 

> * [ ] The animation is _wonky_:  
>   * [ ] #12293: The dropdown animation could be better. It would be better if it animated the whole window frame, but it's gotta look good. #9977 has notes on what I tried and didn't work for me.
>   * [ ] #12121

In general, I'd honestly just recommend [`globalSummon`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon) over `quakeMode`. You can achieve all the same results, but in a more flexible way.

I'm just gonna bulk call this /dup #888 since this incorporates a bunch of related feedback. Thanks!
