### ISSUE TITLE
Some of the deleted profiles still appear in the context menu of the Start menu tile.

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/terminal#14945]
Some of the deleted profiles still appear in the context menu of the Start menu tile.
![无标题](https://user-images.githubusercontent.com/13523412/222629292-30078b37-8bf8-4def-b9e7-7af55cc116f0.jpg)

**Comment by zadjii-msft** [comment]
Huh. I wonder if the Start Menu caches those results at a different interval than the taskbar. Does this persist after a reboot/?
