### ISSUE TITLE
Bug Report: Every time immediately after resizing the window, the scrollbar does not work

### ISSUE THREAD

**Issue by jantari** [microsoft/terminal#1494]
# Environment

```none
Windows build number: 10.0.18922.1000
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

1. Open up Windows Terminal
2. In whatever shell you like, produce lenghty output so we have something to scroll (e.g. `1..100` in PowerShell)
3. Resize the window by dragging any of its borders or corners
4. Immediately afterwards, hover the mouse cursor over the scrollbar until it visually enlarges and drag it. The scrollbar will move but the terminal content won't. After releasing the scrollbar and re-dragging it, it works as expected.

# Expected behavior

When dragging the scrollbar with the mouse it should scroll back up in the terminal output buffer - always, independent of recent window size changes

# Actual behavior

When resizing the window and trying to drag the scrollbar immediately afterwards, the scrollbar will not scroll the terminal contents despite moving up and down just fine.

**Comment by DHowett-MSFT** [comment]
Well that shouldn't happen.

**Comment by wolf99** [comment]
I have same issue. Noticed it using the window restore and maximize buttons
````
OS: Microsoft Windows [Version 10.0.18362.295]
WT: Version: 0.3.2171.0
````

**Comment by bgolinvaux** [comment]
I noticed the same behaviour : the mouse wheel works but the scrollbar does not work on the first time after resize. And as soon as I even wheel-scroll one line, the scrollbar works again. 

OS: Win10 x64 2004 (19041.21)
Terminal Version: 0.8.10261.0
