### ISSUE TITLE
Some user-installed fonts not found at startup

### ISSUE THREAD

**Issue by LeGuipo** [microsoft/terminal#14941]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1265

### Other Software

DejaVu font V2.37 in my case.

### Steps to reproduce

DejaVu fonts are not bundled with Windows 11, so they have to be downloaded [separately](https://dejavu-fonts.github.io/Download.html)
Installation is done by right-clicking on the selected .ttf files then _Install_. No admin account is needed.

In Terminal settings, DejaVu Sans Mono should appear in the font selection listbox. It can be applied to any profile including the default one. The preview area should display the font correctly.

Restart Terminal. A warning message should appear.

**Note :** tried also with [Inconsolata font](https://levien.com/type/myfonts/inconsolata.html) (single .otf file), installed in the exact same way as DejaVu, but no issue with that one.

### Expected Behavior

No warning, font displayed correctly in Terminal

### Actual Behavior

Upon Terminal restart, a warning message appears :

![bugdejavusansmono](https://user-images.githubusercontent.com/66889737/222383885-5382391e-f3c1-43c6-a970-af202929cda9.png)
**Translation :**
_Sorry # C0 we can’t find the selected font "DejaVu Sans Mono". "Consolas" has been selected instead. Install the missing font or choose another one._

**Workaround :** by just opening the terminal settings, the font seems to be found again (no need to click on apply), then opening a new tab should display the font without warning.

**Comment by lhecker** [comment]
Thanks for the report! This is a known issue with installing fonts into the user font directory. It's a bug that's unfortunately outside of our control and we're all patiently waiting for a fix for this as well. It's one of the most common bug reports we get. Here's how you fix it: https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973

/dup #3257
