### ISSUE TITLE
New tabs should re-read environment variable list.

### ISSUE THREAD

**Issue by GarThor** [microsoft/terminal#14948]
# Description of the new feature/enhancement

I'm not really sure if this should be filed as an issue or not, but I'm changing projects, and thusly environment variables all the time.  Unfortunately, the terminal app runs as a single app, and never re-reads environment variables from the windows environment, which means I have to remember to close and re-open terminal if I want to see those changes.  It would be nice if there was a button that would let me explicitly refresh the environment for a specific tab... at the very least closing and re-opening a tab should re-read the environment variables into the new shell for use.

# Proposed technical implementation details (optional)

When I open a new terminal tab, it should have the most up-to-date version of all environment variables and other settings that I've set.  This should be done in a predictable way, such that any process running in other tabs should retain the previous version of the environment variables, so that any processes running in those tabs doesn't get confused.

**Comment by DHowett** [comment]
Thanks for the report! This is the topic of pull request #14839, which is associated with bug #1125. I've got good news: it looks like it's trending towards merging!

I'd suggest following /dup #1125 for a little longer, and jumping on the Preview channel when 1.18 is released. :smile:

**Comment by GarThor** [comment]
Thanks so much @DHowett , I did search for the issue, and didn't immediately find anything that resembled this issue, but I suppose I just needed to dig a little deeper.  I'll go ahead and take a look at the issues you posted, and then wait eagerly for the  latest version! =D

**Comment by DHowett** [comment]
Oh, yeah, they're totally cryptic. We have a (bad?) habit of naming issues after the engineering work needed to do them rather than the observable _bug_. Sometimes. 😁
