### ISSUE TITLE
Terminal doesn't do Transparency on WSL.

### ISSUE THREAD

**Issue by iDm0nz** [microsoft/terminal#1495]
I don't really know if it's an issue, but here it is anyway.

# Expected:
(https://i.ibb.co/xhLGH5f/normal.png)

# Issue:
(https://i.ibb.co/smKrH3w/weird.png)

**Comment by JaimeStill** [comment]
Did you set `useAcrylic` to `true` in the settings?

**Comment by iDm0nz** [comment]
It worked, thanks.

Le lun. 24 juin 2019 à 01:03, Jaime Still <notifications@github.com> a
écrit :
