### ISSUE TITLE
Cross-Platform Support (Linux, MacOS)

### ISSUE THREAD

**Issue by tomoum** [microsoft/terminal#14956]
🚀Great respect for the developers of this application it is fantastic. 

It would be great if its cross-platform though so I don't have to play mental games back and forth with other emulators on the other platforms. I am sure there are others in the same place as me. 

Thanks

**Comment by j4james** [comment]
This is answered in the [FAQ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#what-about-porting-the-windows-terminal-to-macos-or-linux):
> Windows Terminal requires a good number of Windows-specific technologies. We unfortunately won't be supporting it on Mac or anywhere else any time soon. There are some really good terminals on OS X, including iTerm and Hyper, and an uncountable number of good terminals on Linux.

See also #498, #504, #563, #624, #698, #2331, #2466, #4235, #6074, #6255, #8350, #10527, and #10766 (it really is a frequently asked question).

**Comment by zadjii-msft** [comment]
Yep, that's exactly right.

**Comment by DHowett** [comment]
s/exactly right/_utterly comprehensive_/. Dang, James, you rock!
