### ISSUE TITLE
Queries for the currently activated requests for Mouse and/or Focus events via VT sequences

### ISSUE THREAD

**Issue by ShrykeWindgrace** [microsoft/terminal#14955]
# Description of the new feature/enhancement

I am writing a CLI app that would like to track mouse focus events, buttons events, and discard mouse move events. I can achieve that by sending to `stdout` the sequence `\ESC[?1004h\ESC[?1003l\ESC[?1002h` (source of inspiration: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking). The app then would reset these modes by emitting appropriate sequences and the end of its lifetime: `\ESC[?1004l\ESC[?1003h\ESC[?1002l`.

The `stdin` is configured as `ENABLE_VIRTUAL_TERMINAL_INPUT | ENABLE_WINDOW_INPUT | ENABLE_MOUSE_INPUT |  ENABLE_EXTENDED_FLAGS` if that's relevant.

However, the approach above presumes the initial state of requested modes - and I'd rather have (in pseudocode)
```
let s = getRequestedEvents(stdout);
setRequestedEvents( (MOUSE_BUTTON | FOCUS) & ~MOUSE_MOVE, stdout);
app();
setRequestedEvents(s, stdout);
```
I wonder if it is possible to achieve that via a VT sequence (I found only https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#query-state) or via a console API?

Cheers!

**Comment by j4james** [comment]
@ShrykeWindgrace You should be able to read the initial state of any of the modes with a [`DECRQM`](https://vt100.net/docs/vt510-rm/DECRQM.html) query. But be aware that that has only recently been added to Windows Terminal (preview version [1.17.1023](https://github.com/microsoft/terminal/releases/tag/v1.17.1023)).

**Comment by ShrykeWindgrace** [comment]
@j4james that's great news, thank you!

Just a little bit of clarification, if you don't mind. When we query for a mode `N` via `\ESC [ ? N $ p`, the response format is `\ESC [ ? N ; z y`. What are possible values for `z` here? `0..4` or `0..2`?

(I took https://terminalguide.namepad.de/seq/csi_sp__p_t_dollar/ as reference)

**Comment by j4james** [comment]
> What are possible values for `z` here? `0..4` or `0..2`?

The possible values are `0..4`. Quoting the [`DECRPM`](https://vt100.net/docs/vt510-rm/DECRPM.html) documentation:
```
0 	Mode not recognized
1 	Set
2 	Reset
3 	Permanently set
4 	Permanently reset
```

**Comment by j4james** [comment]
I should also mention that the terminalguide documentation is a bit misleading. The `?` isn't part of the query sequence - it's part of the mode. DEC modes and XTerm modes have a `?` prefix, while ANSI modes do not. You could also potentially have modes with other prefix characters.

**Comment by ShrykeWindgrace** [comment]
Great, thanks for the detailed answer!
