### ISSUE TITLE
Quake Mode doesn't render sample Outlines.hlsl Pixel Shader correctly

### ISSUE THREAD

**Issue by HoloWise** [microsoft/terminal#14953]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1325

### Steps to reproduce

Apply sample [Outlines.hlsl Pixel Shader](https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Outlines.hlsl) using [experimental.pixelShaderPath setting](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#pixel-shader-effects)
Open regular Terminal window
Open Terminal in Quake mode
Observe the issue 

### Expected Behavior

Sample pixel shader is drawn the same way in both windows

### Actual Behavior

Pixel Shader breaks in Quake mode

Regular Terminal window:
![image](https://user-images.githubusercontent.com/36460595/222972671-ec693acf-5e0d-4775-8b2c-a4079a2b49d6.png)

Quake Mode view
![image](https://user-images.githubusercontent.com/36460595/222972722-6f1576b0-7557-4ce2-9a66-ff8bdd650971.png)

**Comment by carlos-zamora** [comment]
Hi @HoloWise! This seems to be an issue with our implementation of the Outlines.hlsl shader, so we'd be happy to update our demo with one that works better. If you have any expertise in HLSL, we would love your help.

**Comment by lhecker** [comment]
I gave it a shot, but the result might not be exactly what you're looking for. If you could try out the new Outlines.hlsl from my PR (https://github.com/microsoft/terminal/pull/14971) and leave a comment, that'd be great!

**Comment by HoloWise** [comment]
@lhecker This is looking great. Just gave it a go and it renders as expected in Quake mode. 

![obraz](https://user-images.githubusercontent.com/36460595/224091451-bcb3b7b8-e03a-405f-89c3-1279ac16c0b4.png)

If you go pixel peeping it seems to be missing some of the outline around sharper edges of letters due to +2 offset increments. Incrementing y offset by 1 seems to eliminate most instances while incrementing both by 1 seems to get rid of those completely. (but obviously requires more processing and makes outline more pronounced)

![obraz](https://user-images.githubusercontent.com/36460595/224105678-6766e4a1-78fd-4be5-af16-004ab7778eba.png)
