### ISSUE TITLE
Screen buffer size settings.

### ISSUE THREAD

**Issue by Funtime60** [microsoft/terminal#14969]
# Description of the new feature/enhancement

Both PowerShell and Command Prompt support having a buffer with a height much larger than the window. This allows for the user to scroll such that the prompt is not stuck at the bottom of the window. Could WT either get a similar setting or something else that allows the user to scroll past the end bottom of the prompt?

![image](https://user-images.githubusercontent.com/24595923/223648667-25aa8f25-fc46-4081-add7-278518ec57f9.png)
vs
![image](https://user-images.githubusercontent.com/24595923/223648884-3e778384-58e1-453a-8faa-324a17eb3e5e.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think what you're asking for is going to be best served by /dup #8623. It won't let you scroll the whole length of the buffer, but it'll let you scroll ~one screenful forward, so that the last line of text is on the first row of the viewport. 

Thanks!
