### ISSUE TITLE
Windows Terminal (wt.exe) fails to launch from Run dialog, or right-click menu

### ISSUE THREAD

**Issue by LimeHunter7** [microsoft/terminal#14961]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22624.0

#### via Run dialog
Open Run dialog with Win+R, enter either `wt` or `wt.exe`
#### via right-click menu
I have custom registry keys to launch Windows Terminal from File Explorer in the current directory with a particular profile, that have previously worked on this machine and work fine on a different machine. A brief excerpt:
```
[HKEY_CURRENT_USER\Software\Classes\Directory\shell\0WT]
"MUIVerb"="Open in Windows Terminal with..."
"SubCommands"=""

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\0WT\shell\000flyout]
"MUIVerb"="Windows PowerShell"

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\0WT\shell\000flyout\command]
@="wt.exe -w 0 nt -d \"%V\" -p \"Windows PowerShell\""
```

### Actual Behavior

Windows Terminal does not open, silently crashing without popping up an error dialog. Checking "View all problem reports" gives the following report:
```
Source
WindowsTerminal.exe

Summary
Stopped working

Date
‎2023-‎03-‎06 13:12

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10262.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	WindowsTerminal.exe
Application Version:	1.16.2301.26002
Application Timestamp:	63d332f5
Fault Module Name:	combase.dll
Fault Module Version:	10.0.22621.1325
Fault Module Timestamp:	ac089364
Exception Code:	802b000a
Exception Offset:	000000000009200b
OS Version:	10.0.22624.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	0a7f
Additional Information 2:	0a7fe4c20d7184a9bbab2d1fc0238e67
Additional Information 3:	03ba
Additional Information 4:	03ba7b19bedd3a02cef1a92511a98c7c

Extra information about the problem
Bucket ID:	8238290b464ba84fe78b7046220e0e8c (1696573131156491916)
```

### Additional information
Windows Terminal launches fine from:
* the Search dialog
* the default "Open in Terminal" right-click option in File Explorer
* The Windows Terminal "Command Prompt" and "Windows PowerShell" profiles as current user
* The Win+X menu "Terminal" and "Terminal (Admin)" options

I have tried toggling the Windows Terminal "app execution alias" twice, with no changes.

I have uninstalled and reinstalled Windows Terminal from the Windows App Store, with no changes.

Output of `where wt.exe`:
```
C:\Users\bobmc\AppData\Local\Microsoft\WindowsApps\wt.exe

```

Output of `icacls "C:\Program Files\WindowsApps"`:
```
C:\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                             NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                             S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                             S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(RX)
                             NT AUTHORITY\SYSTEM:(F)
                             NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                             BUILTIN\Administrators:(CI)(RX)
                             NT AUTHORITY\LOCAL SERVICE:(OI)(CI)(RX)
                             NT AUTHORITY\NETWORK SERVICE:(OI)(CI)(RX)
                             NT AUTHORITY\RESTRICTED:(OI)(CI)(RX)
                             BUILTIN\Users:(Rc,S,RD,REA,X,RA)
                             DESKTOP-4P31ASQ\bobmc:(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files

```

**Comment by zadjii-msft** [comment]
Huh, that bucket number was useful!

`BucketDetails?BucketIdentifier=8238290b-464b-a84f-e78b-7046220e0e8c`

MSFT:43084860, MSFT:43083421

65 hits in the last 90d

"STOWED_EXCEPTION_XAML_TEXT_Cannot_create_instance_of_type__Microsoft.UI.Xaml.Controls.XamlControlsResources"

"STOWED_EXCEPTION_802b000a_TerminalApp.dll!_winrt::Windows::UI::Xaml::Hosting::WindowsXamlManager::InitializeForCurrentThread_::_2_::_lambda_1_::operator"

Hmm. Looks like the terminal is beefing it trying to... load XAML?

@DHowett is this that one bug you were talking about that broke everyone?

**Comment by DHowett** [comment]
This seems like another instance of "can't load Microsoft.UI.Xaml.dll", which might be down to what parts of the runtime are available to be loaded. Idly, I also wonder if you have a permissions issue on `C:\Program Files\WindowsApps`!

**Comment by LimeHunter7** [comment]
Hi Dustin,

I put the output of `icacls "C:\Program Files\WindowsApps"` in my initial report. Can you diagnose a permissions issue based on that?

Thanks.

**Comment by DHowett** [comment]
Oh, jeez, I'm sorry I missed that.

So, it does look like the ACLs on that folder are wrong; your user shouldn't show up in that list at all. Oh boy.

This is the kind of thing that usually warrants a quick and easy "reinstall Windows" (or, upgrading from the version you have to _the same version_ might work)... but it might also be possible to _fix._ Might.

Anything that follows is done without warranty, express or implied.

This command will restore the ACLs of `WindowsApps` to the ones shipped with Windows.

```cmd
CACLS "C:\Program Files\WindowsApps" /S:"D:PAI(A;OICI;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;OICI;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)(A;OICI;FA;;;SY)(A;CI;0x1200a9;;;BA)(A;OICI;0x1200a9;;;LS)(A;OICI;0x1200a9;;;NS)(A;OICI;0x1200a9;;;RC)(XA;;0x1200a9;;;BU;(Exists WIN://SYSAPPID))"
```

The one thing that _icacls_ can't do that cacls (deprecated) can is apply that last SDDL particle that indicates any token with an App ID can access it.

Never apply this recursively. Never apply any permission changes to WindowsApps recursively! We've learned that doing so is nearly unrecoverable.

**Comment by LimeHunter7** [comment]
Running that CACLS command seems to have fixed the issue; and it still works after a reboot. Thanks!
