### ISSUE TITLE
No way to disable "WIN + V" or related shortcuts?

### ISSUE THREAD

**Issue by willxie** [microsoft/terminal#14978]
### Windows Terminal version

1.16.10262.0

### Windows build number

Windows 11 22H2 (22621.1344)

### Other Software

I am using AutoHotKey with Terminal. I noticed that compared to Powershell and Command prompt, Windows Terminal implicitly overrides "WIN + V" shortcuts, with V being any key. I use AutoHotKey to remap "WIN+C" + "WIN+V" to "CTRL+C" and "CTRL+V" respectively.  It works well in most applications such as chrome and other terminals. In Windows Terminal, it does not respect these overrides.

I don't see a way to change this behavior in settings as it is not one of the shortcuts. 

### Steps to reproduce

Create AutoHotkey with simple overrides for WIN key shortcuts. 
```
#SingleInstance, Force
SendMode Input

; Copy, paste, cut
#c::
Send, ^c
Return

#v::
Send, ^v
Return
```

### Expected Behavior

It should behavior like other terminal apps and respect the overridden behavior from AHK. In this example, WIN+C and WIN+V should do copy and paste. 

### Actual Behavior

WIN+C opens microsoft teams
WIN+V opens clipboard history menu.

**Comment by zadjii-msft** [comment]
Huh, that's really interesting! We're surely not doing anything with <kbd>win</kbd> ourselves. Perhaps this is a AHK bug with the way they send keys to XAML Islands applications like the Terminal/?

**Comment by zadjii-msft** [comment]
This thread: https://www.autohotkey.com/boards/viewtopic.php?t=68681 seemed to report a similar issue with Firefox, a few years back. I'm not sure that AHK has a proper issue tracker that we can use to try and pin this down though...

**Comment by bzzrak** [comment]
Works fine for me. Are you sure you're not running terminal as admin or something like that?

**Comment by willxie** [comment]
Oh yes I am running terminal as admin and usually with WSL2. Are the specific behaviors related to this?

**Comment by willxie** [comment]
After disabling admin privilege from ubuntu shell, I can confirm that this behavior is fixed and behaved as normal. Though, I am still wondering why enabling admin privilege terminal shell does not allow AHK shortcuts to be used.

**Comment by zadjii-msft** [comment]
> I am still wondering why enabling admin privilege terminal shell does not allow AHK shortcuts to be used.

I suspect that is because AHK itself is not running as admin. Processes cannot send window messages (keystrokes) to windows that are running at a different elevation level. Otherwise, an unelevated `malicious.exe` could just send keystrokes to any elevated console/terminal window, which would be a trivial escalation of privilege. 

Glad we figured this one out!
