### ISSUE TITLE
Terminal flickers on rapid print

### ISSUE THREAD

**Issue by janausis** [microsoft/terminal#14972]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1344

### Other Software

Python 3.10

### Steps to reproduce

Run this script in windows terminal:

```
i = 0
from time import sleep
print("\n\n\n")

while True:
    sleep(0.1)
    print("progress made progress made progress made\n\n\n" + str(i) + '\033[1A\033[2K\033[1A\033[2K\033[1A')
    i += 1
    if i > 100:
        i = 0
```

### Expected Behavior

No flickering like on linux terminals. 

Behavior:
**Text**

**Progress Bar**

### Actual Behavior

The print command gets rendered by character so old states before new line cause a flickering effect.

Behavior:
**Text**
_flickering Text_
**Progress Bar**

**Comment by zadjii-msft** [comment]
Found it!

/dup #12336

Thanks again!
