### ISSUE TITLE
Add support for Erase Color Mode (DECECM)

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#14983]
# Description of the new feature/enhancement

There are a number of operations that fill the background with "standard erase attributes", which means all characters attributes are reset, but the active background color is still applied.

However, on the VT525 you can control whether that background color is used with the _Erase Color Mode_ (`DECECM`). If `DECECM` is set, those operations fill with the default colors, rather than the active colors.

This is useful when writing text with a background color that may wrap onto the next line. If that happens at the bottom of the page, the new line is completely filled with the active background color, which is usually not what you want. Setting `DECECM` can fix that.

# Proposed technical implementation details (optional)

I was thinking we could possibly just add a flag to the `TextAttribute::SetStandardErase` method that specifies whether the rendition colors should be reset along with the character attributes. Then wherever we're calling `SetStandardErase`, we lookup the `DECECM` mode and pass that as the parameter.

**Comment by j4james** [comment]
@al20878 I've created another test which I'm hoping will confirm the way this mode is intended to work. This is strictly for the VT525.

https://gist.github.com/j4james/cac2cec7fe0df78e59eb52f9c8201599

This script renders a test pattern using the various scrolling and erasing operations which I think are likely to be affected. On the first pass the mode is set, and the second pass it's reset. I'd be grateful if you could take a photograph of the two renditions so I can see how they differ. The test pattern will remain visible until you press <kbd>Enter</kbd> (or whatever the VT525 equivalent).

**Comment by al20878** [comment]
@j4james I downloaded the script and am going to run it a bit later, will post the results. (Yeah, it's `Return` on the LK411 keyboard, while `Enter` is a keypad equivalent.)

**Comment by al20878** [comment]
![Set](https://user-images.githubusercontent.com/44822487/224577391-d472a45f-0e15-4235-807a-ec8335e3d432.png)
![Reset](https://user-images.githubusercontent.com/44822487/224577398-23e9b977-9571-4e4b-9d25-7d0fb2cf7a18.png)

**Comment by j4james** [comment]
This is brilliant! Thank you so much. This is exactly what I was hoping to see.
