### ISSUE TITLE
Renderer encountered an unexpected error: -2003283965 when upgrading font

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#14985]
### Windows Terminal version

1.17.1023 Preview

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Launch Windows Terminal where the default font is `CaskaydiaCove NF` (in my case the default profile is PowerShell 7.3.3, FWIW)
2. Upgrade the font using the standard "Install" mechanism on the files contained in https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/CascadiaCode.zip

### Expected Behavior

The renderer should pick up the updated font.

### Actual Behavior

![Screenshot of steph on 2023-03-13 09-13-24](https://user-images.githubusercontent.com/12860484/224644731-f8f0601b-e3f0-4ba1-b715-aa725bb2d228.png)
![Screenshot of steph on 2023-03-13 09-13-17](https://user-images.githubusercontent.com/12860484/224644736-d40b4904-c3c5-4792-971c-0c50c90d6b79.png)

**Comment by zadjii-msft** [comment]
Did the warning go away after restarting the Terminal/? I'm not sure there's gonna be any way for us to hot-reload the font itself. But it does also seem like upgrading a font while the Terminal is using it shouldn't break the Terminal...

**Comment by zadjii-msft** [comment]
> **DWRITE_E_FILENOTFOUND**
> 
> `0x88985003`
> 
> A font file could not be opened because the file, directory, network location, drive, or other storage location does not exist or is unavailable.

**Comment by sba923** [comment]
I forgot to mention that after closing and reopening Windows Terminal, everything worked fine.

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!

**Comment by sba923** [comment]
> Did the warning go away after restarting the Terminal/? I'm not sure there's gonna be any way for us to hot-reload the font itself. But it does also seem like upgrading a font while the Terminal is using it shouldn't break the Terminal...

No, it should not...
