### ISSUE TITLE
Active pane is not clearly visible

### ISSUE THREAD

**Issue by buckleyGI** [microsoft/terminal#14996]
### Windows Terminal version

1.16.10262.0

### Windows build number

Build 22000.co_release.210604-1628

### Steps to reproduce

Create a few panes

### Expected Behavior

Clearly see what pane is active/focused

### Actual Behavior

It's not clear what the active pane is

Please click on the full image as the thumbnail below is a bit clearer :)

The pane with a (1) inside is active

I know this is a subjective issue but is there a way to make the borders more clear, or better, give the pane a different background/shade or place an icon in the bottom right corner that signals it's the active one?
The main issue I have is that I can't see the active one even when I consciously cycle between the panes with the keyboard shortcuts.

Thank you.

![image](https://user-images.githubusercontent.com/2102864/225348422-17154c89-9bd8-4a30-b44c-9924848be6ad.png)

**Comment by zadjii-msft** [comment]
You'd probably be interested in [Unfocused appearance settings](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#unfocused-appearance-settings). You can add settings to your profile to configure what the control looks like when it's inactive. So you could set a different background color. Or you could add a background image to the profile's normal appearance, but not the `unfocusedAppearance` (resulting in only the active pane having that image).

I personally have the following in a couple of my profiles:

```jsonc
"unfocusedAppearance":
{
    // First, download https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Grayscale.hlsl to "C:\Grayscale.hlsl", or wherever
    "experimental.pixelShaderPath": "C:\\Grayscale.hlsl",
    "background": "#162029",
},
```

Another thing that'll probably help - in 1.17, we fixed the pane borders to actually use the dark theme when the app is in dark mode (#3917). 

Would that work for you/?

**Comment by buckleyGI** [comment]
It seems it is still a bit buggy though.
When I open up terminal I get the see the first screenshot which is incorrect. Only the first pane should be black AFAIK.
After hovering and clicking with the mouse a bit it is corrected.

Is this a known issue already? Otherwise I create a bug if you want.

![image](https://user-images.githubusercontent.com/2102864/225656835-af579cfa-86c8-48e6-be96-8ee47d329af6.png)

![image](https://user-images.githubusercontent.com/2102864/225656858-c9320ba2-1c78-4c13-a606-0941984953bf.png)

**Comment by zadjii-msft** [comment]
> I used winget to install Terminal and don't get presented the update to 1.17. Not sure if that is expected.

Yep - there's two different channels for "Terminal (stable)" vs "Terminal Preview". Stable's currently on 1.16, Preview's on 1.17. They're different apps in the app store & winget, and they both can be installed side-by-side. 

> It seems it is still a bit buggy though.
> When I open up terminal I get the see the first screenshot which is incorrect. Only the first pane should be black AFAIK.

I know that there _is_ an issue tracking this somewhere, but I can't find it immediately. Something about the cursor blinking when opening multiple panes.
