### ISSUE TITLE
crash after clicking on the browse file button

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/terminal#14997]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.25314.1010 and 10.0.23403.1001

### Steps to reproduce

Go to any of the profile page and click the browse... button

### Expected Behavior

open the explorer window to select a file

### Actual Behavior

application crash

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #14808 for more discussion.

/dup #14808
