### ISSUE TITLE
WT is relatively slow at executing cmd scripts at Windows startup

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#15001]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1413

### Steps to reproduce

My Windows system somehow has some `*.cmd` logon scripts: Terminal/cmd windows get spun up and closed several times at Windows login.

I could not find those scripts in Sysinternals `autoruns64.exe`, but they certainly get executed. My system is in a good shape, so it's not some virus etc.

These scripts do not require user input and typically do not even print anything, but the time to open a WT window, render it and then close is relatively slow. So WT startup/teardown time is a whole different beast when the usecase are the logon scripts and the OS/disk is bombarded by tons of apps/services starting up in parallel.

Some questions:
1. Is it possible to somehow ask WT to log to file its launches / closings with times (and hopefully with the argv)?
2. WT should be much faster for these cycles. Maybe it could somehow lazily render the Window or do only a minimal render (since the teardown is imminent faster than it could complete the rendering)? cmd.exe used to be much faster for these cycles. Ideally, WT would not be rendered at all for these scenarios. Maybe some "quiet" calls of cmd.exe did not show any window before, and started to show WT window now?

### Actual Behavior

N/A

**Comment by carlos-zamora** [comment]
Hi @vadimkantorov. Thanks for the feedback. 

> 2. WT should be much faster for these cycles. Maybe it could somehow lazily render the Window or do only a minimal render (since the teardown is imminent faster than it could complete the rendering)? cmd.exe used to be much faster for these cycles. Ideally, WT would not be rendered at all for these scenarios. Maybe some "quiet" calls of cmd.exe did not show any window before, and started to show WT window now?

Yes! We definitely need to improve our startup/teardown performance. We're tracking this over in #5907, so we're going to mark this as a /dup of #5907.


> 1. Is it possible to somehow ask WT to log to file its launches / closings with times (and hopefully with the argv)?

As of now, no. The console hosting process model precludes us from doing this. However, there is a windows system feature that you can enable to audit process execution. This section from our FAQs may help out: https://github.com/microsoft/terminal/wiki/What-is-causing-consoles-to-pop-up-on-me%3F

**Comment by vadimkantorov** [comment]
Is it possible to have some heuristics that delay full UI rendering specifically when it's running in unattended mode? Rendering of the UI / full Terminal systems bootstrapping is useless in these cases as the whole thing needs to exit in 500ms

**Comment by vadimkantorov** [comment]
I think that this specific usecase is not discussed in https://github.com/microsoft/terminal/issues/5907

**Comment by vadimkantorov** [comment]
hmm... and in my case, these scripts somehow don't appear in sysinternals autoruns. I wonder if Terminal/cmd.exe (or maybe Windows in general?) has any simple way of logging all process executions (along with args)? that way at least I can give you a concrete example

I agree that they shouldn't be displaying consoles, so probably some command line flags are missing to hide these windows. but if they show it anyway, i wonder if there's any way to speed up these UI's starting up / shutting down. Maybe Terminal launches first in headless mode, is it faster for all subsequent Terminals to start up / shut down?

**Comment by DHowett** [comment]
> simple way of logging all process executions

Sorry to give you a drive-by, but you _might_ be served well enough on this point by https://github.com/microsoft/terminal/wiki/What-is-causing-consoles-to-pop-up-on-me%3F :smile:

**Comment by vadimkantorov** [comment]
btw `gpedit.msc` is not included in Windows 11 Home... So hacks needed to install it https://answers.microsoft.com/en-us/windows/forum/all/how-to-enable-the-gpeditmsc-on-windows-10-and-11/dbc76919-f2b5-4dec-a2b7-bcf545c34d00

**Comment by vadimkantorov** [comment]
@DHowett btw how can I filter the Process Creation events in the Event Viewer? What should I select as `Event Sources`? Without selecting `Event Sources`, the `Task Category` filter drop down is disabled so I can't choose `Process Creation` to filter only the relevant events

**Comment by DHowett** [comment]
That is an excellent question! Unfortunately, I am not particularly good with Event Viewer and I don't know how to filter those events adequately. ☹️

**Comment by vadimkantorov** [comment]
I wonder if Terminal could have an option for logging to its own topic in Event Viewer logging, including its startup arguments

**Comment by vadimkantorov** [comment]
This also leads to Terminal capturing focus for 1 second stealing it from wherever I'm typing and it steals keys I've typed

When there are multiple startup scripts, it gets quite nasty. In addition to them being displayed in the foreground.

At least I propose to somehow have these scripts not execute in a foreground window, it will remove the flicker. Maybe even execute these as minimized window somehow.

If these are executed as `cmd.exe` scripts - maybe there could be a hack to not show window in foreground if it completed execution in 1 second (e.g. start as minimized and draw the window in foreground only if the batch script hasn't completed execution in 1 second. this can also speed up execution of such scripts!)
