### ISSUE TITLE
Redundant space in German context menu entry (super-low priority)

### ISSUE THREAD

**Issue by PinkSerenity** [microsoft/terminal#15009]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22624.0

### Other Software

Windows Explorer

### Steps to reproduce

1. Set system language to German
2. Open Windows Explorer
3. Right-click in a directory

### Expected Behavior

The context menu entry says "In Terminal öffnen".

### Actual Behavior

The context menu entry says "In  Terminal öffnen" (GitHub automatically corrects that in preview, Markdown still has the double space).

New context menu:
![grafik](https://user-images.githubusercontent.com/41524896/225943676-db174c6b-bd4a-48ce-9e57-53961fe17eb3.png)

Old context menu:
![grafik](https://user-images.githubusercontent.com/41524896/225943783-4c0677ab-d6f6-4061-bf0a-2cffb90e98af.png)

**Comment by lhecker** [comment]
I'm sorry for the long wait! This is now tracked at MSFT-44562118.

**Comment by PinkSerenity** [comment]
This appears fixed now (probably for quite some time already). I think I can close this issue.

**Comment by DHowett** [comment]
Thanks for checking!
