### ISSUE TITLE
profiles.json could need a generator like config.office.com

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#1501]
# Summary of the new feature/enhancement
the way to customize profiles.json isn't very straight forward for non devs.

# Proposed technical implementation details (optional)

It would be cool if there was page like config.office.com to generate / load / save a profiles.json
based on UI / switches and WYSIWYG.

**Comment by DHowett-MSFT** [comment]
This will be addressed by having a comprehensive settings UI
