### ISSUE TITLE
Quickly jump to the location of the most recent command

### ISSUE THREAD

**Issue by lost22git** [microsoft/terminal#15015]
Record the location of the recently executed command, and provide a shortcut key to quickly jump to the command.

For some commands that output a lot of logs, it may be more convenient to view.

**Comment by j4james** [comment]
I think what you're looking for is the [Scroll Marks](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-15-release/#scroll-marks-experimental) feature.

See also #11000.
