### ISSUE TITLE
Terminal does not close...

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#15012]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1413

### Steps to reproduce

When, using Windows Terminl,
1) starting Notepad
2) then typing `exit` 
3) the terminal window will close.

When, using Windows Terminl,
1) starting code (to run "Visual Studio Code")
2) then typing `exit` 
3) the terminal window does not close,

![iNeSc](https://user-images.githubusercontent.com/7850737/226100235-3d356247-9b04-4310-b50f-4cd1d41e88e9.png)

### Expected Behavior

Expected will be the same behaviour.

### Actual Behavior

see: "steps to reproduce"

**Comment by Luuk34** [comment]
The relevant section from my settings.json
```
            {
                "closeOnExit": "always",
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt",
                "startingDirectory": "D:\\TEMP"
            },
```

**Comment by DHowett** [comment]
Unfortunately, this is working as expected! There is a long-standing bug in VSCode where they keep the console handle open after launching.

/dup https://github.com/microsoft/vscode/issues/66750
