### ISSUE TITLE
Currently, Windows Terminal only highlights one found result and users need to input Enter key to iterate all the results. However, there is a feature request on GitHub to highlight all results at once, like what Konsole and iTerm do. This feature can be useful in many ways, such as developers would like to monitor keywords like ERROR, FATAL in real-time output

### ISSUE THREAD

**Issue by jiangdongzi** [microsoft/terminal#15017]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
Thanks for the suggestion. The feature for highlighting all search results is tracked in issue #7561. Highlighting keywords like ERROR and FATAL should be covered by the pattern matching functionality tracked in #8294. For more information see also #3920 and #9965.
