### ISSUE TITLE
Tab in-/activity monitoring

### ISSUE THREAD

**Issue by iconoeugen** [microsoft/terminal#15021]
# Description of the new feature/enhancement

The Terminal application supports multiple tabs which makes difficult to track when a change happens in other tabs then the current one that is in focus.

The new feature should introduce the possibility to configure in-/activity monitoring for each tab individually, that would enable the user to skip switching between different tabs in order to observe if any change took place outside of the current tab that is in focus.

# Proposed technical implementation details (optional)

Add support to configure monitor for:
- **Silence**: Toggles the monitoring of the current tab for lack of activity
  By default, after 10 seconds of inactivity, an info icon will appear on the session’s tab.
- **Activity**: Toggles the monitoring of the current tab for activity
  Upon any activity, an info icon will appear on the session’s tab.
- **Process Finishing**: Toggles the monitoring of the current tab for the process finishing.
  If checked, upon finishing the current process, Terminal will show a notification The process ’name of the process’ has finished running in session ’name of the session’.

*Optional* the alarming of in-/activity can be accompanied by an acoustic bell that should be mutable by preference

**Comment by zadjii-msft** [comment]
Hmm, there's a lot of overlap between #1620, and more specifically #7955. 

* **silence**: you know, I don't think there's anything we have tracking "this tab _hasn't_ done anything in a while", though, to me, that sounds like the inverse of "display an icon when the tab _has_ done something", so maybe that would be good enough?
* **activity**: Yea that's the thing tracked in those threads
* **Process Finishing**: This is... harder. And might require more refinement of the request. Do you want to know when just the root process launched by the Terminal died? Any child of that process? (that wouldn't really work for WSL and certainly not as expected for SSH). What kind of notification are you looking for? An OS-level notification, ala #14425? An in-app toast? 

How does https://github.com/microsoft/terminal/issues/7955#issuecomment-1303740796 sound/?

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
