### ISSUE TITLE
Feature Request: An advanced tab switcher

### ISSUE THREAD

**Issue by keithn** [microsoft/terminal#1502]
"Another option would be to make a keyboard driven tab switcher that shows a dialog list of the tabs in a vertical list with their current active paths.  Horizontally expanding things don't work well with the terminal and most of the tabs are off the edge of the screen and effectively invisible.   At the moment the ALT key + number is a tab switcher.  It would be super cool if you pressed ALT this list of tabs would popup, you could see all your tabs, then complete your ALT chord with the number you are wanting."

**Comment by keithn** [comment]
something that makes things a little better for powershell, is that you can set the window title with $host.UI.RawUI.WindowTitle = ""    or  you can hook the prompt to set it to the current directory as per https://devblogs.microsoft.com/powershell/setting-the-console-title-to-be-your-current-working-directory/

**Comment by DHowett-MSFT** [comment]
Thanks for the request. _please_ make sure to search for existing issues! #597 #608 cover tab sizing and titling. We should repurpose this one to just be the request for an enhanced tab switcher.

**Comment by keithn** [comment]
yes, I did see those, it just didn't quite capture what I wanted. Horizontal tabs are going to be a huge UI problem hence why tab size  is a problem in those issues.   I don't mind the the exact solution, but any way to quickly see your tabs in a vertical list seems a big improvement.    At the moment I have a script that just sets my powershell titles to be my current path ( will need some work to trim it down for long paths) and I can fit a few, but I can't do that with my other shells ( that I know of)

**Comment by keithn** [comment]
just FYI for anyone else who wants nicer tabs for powershell,

in my %UserProfile%\My Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

I put

Function Prompt {
    $host.UI.RawUI.WindowTitle = Get-Location
    "$(Get-Location)> "
}

**Comment by DHowett-MSFT** [comment]
I'm switching this over to be the "advanced tab switcher" feature request and putting it on our backlog.

Thoughts: switch to tab by name. by search. by number. by shell. by content.

**Comment by zadjii-msft** [comment]
Moved discussion from #3389:


@zadjii-msft:
> From @srv-code in #3386:
> 
> > Tab switcher pop-up like in other editor applications (e.g. in Visual Studio Code editor when pressed Ctrl+TAB).
> 
> This kinda reminds me of the "window switcher" (not sure if that's the correct name) in `tmux`: (on the right)
> 
> ![image](https://user-images.githubusercontent.com/18356694/67951521-a955ba00-fbb9-11e9-9e61-ba514aef6c3d.png)
> ![image](https://user-images.githubusercontent.com/18356694/67951532-b4104f00-fbb9-11e9-9187-c54d1502a663.png)
> 
> which lets you not only switch tabs, but directly to a child pane, and can even give you a preview (when the window is big enough)


@jantari:  
> Visual Studio Code screenshot:
> 
> ![vscode_fileswitcher](https://user-images.githubusercontent.com/25607767/68248003-467e7b80-001c-11ea-9e3f-ab4967b6c1fd.png)
> 


@DHowett-MSFT:
> This was mentioned as part of #973, should we track it separately?


@zadjii-msft:
> @jantari thanks for the screenshots <3
> 
> Honestly maybe? I'm not sure that #973 _necessitates_ a UI.
> 
> IMO, this UI could be used in both MRU tab/pane switching order, but also in in-order (left/right) switching order. If we determine that MRU switching order is impossible w/o this dialog, then sure lets collapse the threads, but for now they seem like reasonable separate requests.
