### ISSUE TITLE
Corrupted terminal output after window resized

### ISSUE THREAD

**Issue by RoadToDream** [microsoft/terminal#15042]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Open Terminal from any folder such that primary prompt is longer than one line. 
2. Enter any command and click enter.
3. Maximize Terminal window so primary prompt is arranged within one line.
4. Cursor will be off-position and overwrite my primary prompt.
5. Video attached below:

https://user-images.githubusercontent.com/8088354/227605857-03718a23-b1c1-46a9-b8bc-17dff00f86a3.mp4

### Actual Behavior

Cursor will be off-position and overwrite my primary prompt.

**Comment by lhecker** [comment]
Do you have "AtlasEngine" enabled or disabled?

![image](https://user-images.githubusercontent.com/2256941/227272051-0bfb25f6-f39c-4359-8a6e-232c01d9fb60.png)

If you have it disabled, could you report what happens if you enable it?

**Comment by RoadToDream** [comment]
Hi @lhecker, yes I have tried enabling and disabling the new text renderer, also tested toggling Redraw entire screen and their combinations. All of them behaves the same. The issue seems to exist any program using ConPTY like VS Code.

**Comment by RoadToDream** [comment]
Seems like Terminal can't calculate the correct position of cursor but taking col position from last finished command. 
For example, if primary prompt breaks into two lines and the cursor is at col 10 after the ls command is executed, after resizing the window such that primary prompt is within one line, cursor will be positioned to col 10 disregarding the updated primary prompt.

**Comment by j4james** [comment]
Note that the terminal displays the cursor in the correct position immediately after the resize - it's only once you start typing that it moves to the wrong place. So I suspect this may be PowerShell or PSReadLine issue. Possibly the same underlying problem as https://github.com/PowerShell/PSReadLine/issues/1456.

Also note that you don't get this in the cmd shell, or a bash shell, which is another reason to believe that PowerShell may be the source of the problem.

**Comment by RoadToDream** [comment]
Hi @j4james, thank you for pointing this out. I have tested on an environment that does not have PSReadLine installed. But still you may be right, this seems to be a Powershell issue not a Terminal issue, as I have not observed it in a cmd shell. I will leave this issue open for now and reach out to Powershell support and wait for their response.

**Comment by zadjii-msft** [comment]
Yea, I'd be sure that this is a PowerShell issue. Does this repro in a `conhost.exe` window with the same PowerShell setup?

Looks like the downstream issue is being tracked in https://github.com/PowerShell/PowerShell/issues/19405

**Comment by RoadToDream** [comment]
Hi @zadjii-msft, yes for now I believe this is a PowerShell issue and I have submitted in their repo. I may close this ticket now. Thank you and everyone else helping analyze root cause for this issue.
