### ISSUE TITLE
Paste from terminal to outlook comes out at really small font size

### ISSUE THREAD

**Issue by anilruia** [microsoft/terminal#15043]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1413

### Other Software

cmd

### Steps to reproduce

Configure terminal with Cascadia Mono font size 10, cut-n-paste some text from a command window to outlook. The text shows up in Cascadio Mono font size 5 instad.

### Expected Behavior

Text should paste with formatting in the same font size.

### Actual Behavior

Text pastes with formatting with much smaller font size.

**Comment by j4james** [comment]
This sounds like a duplicate of #14762.
