### ISSUE TITLE
Terminal does not sync environment variable changes

### ISSUE THREAD

**Issue by Boilerplate4u** [microsoft/terminal#15041]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.20348 Build 20348

### Steps to reproduce

Terminal does not sync environment variable changes even if you close and open a new cmd/powershell session, ie you are forced close all sessions and restart Terminal before it takes effect.

### Expected Behavior

It should sync environment variable changes at least when closing/opening a new sessions but even better live. You really shouldn't have to close all sessions and restart the whole Terminal for this.

### Actual Behavior

It doesn't sync environment variable changes even if a cmd/powershell session is restarted (as a standalone cmd does)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1125 for more discussion.

/dup #1125
