### ISSUE TITLE
Focus starts on titlebar when opening a profile from a nested dropdown entry

### ISSUE THREAD

**Issue by kkostrzewa-coupa** [microsoft/terminal#15049]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19045.0

### Steps to reproduce

Adding a profile like this in wt 1.16.10261.0 starts the profile with keyboard focus on the command shell

When I use the preview version, focus is on the titlebar, so I have to tab 2x to switch to the command shell

```json
            {
                "commandline": "ssh -i \"%USERPROFILE%\\.ssh\\my-super-secret-key.pem\" ec2-user@10.161.0.101",
                "experimental.retroTerminalEffect": true,
                "guid": "{8e690e45-db6d-47c5-919a-68a86077f9dd}",
                "hidden": false,
                "name": "ec2:kpk-my-super-awesome-ec2-name",
                "suppressApplicationTitle": true
            }
```

I am using the fabulous new folders feature
```json
        {
            "type": "folder",
            "name": "ssh",
            "entries": [
                {
                    "profile": "ec2:kpk-my-super-awesome-ec2-name",
                    "type": "profile"
                }
            ]
        }
```

### Expected Behavior

focus in command shell

### Actual Behavior

focus in titlebar

**Comment by kkostrzewa-coupa** [comment]
This appears to be a side effect of using folders. When I remove the folder entry from newTabMenu, focus starts in the shell.

**Comment by zadjii-msft** [comment]
INTERESTING

I can totally repro this. That's wild!

Thanks for the report!

**Comment by kkostrzewa** [comment]
@zadjii-msft I think I fixed this with https://github.com/microsoft/terminal/compare/main...kkostrzewa:microsoft-terminal:bug/15049-folder-focus-problem. Will PR.
