### ISSUE TITLE
Start menu icons do not appear

### ISSUE THREAD

**Issue by tessharp** [microsoft/terminal#15044]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22622.0

### Steps to reproduce

1. Install Terminal
2. Install a Linux distribution with WSL (for showcasing multiple icons)
3. Search for "Terminal" in the Start Menu
4. See the icons for each profile missing

### Expected Behavior

Icons for all the different profiles showing up.

### Actual Behavior

No icons show up.
![image](https://user-images.githubusercontent.com/46544857/227674548-fd32d7eb-c580-44c3-ba27-94ff91157ed3.png)

**Comment by zadjii-msft** [comment]
Huh, interesting. Not sure there's anything for us to fix here. Probably a bug in the Start Menu. Mind filing feedback using the Feedback Hub/? If you hit "Share" and share the aka.ms link here, I can make sure to promote it to the right team internally. 

The Start menu team should be able to dig into this better than we can 😉 Thanks!

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!

**Comment by EDIflyer** [comment]
Not sure if related but the icon refuses to show up for WSL on my jump menu but is OK within the app!

![image](https://github.com/microsoft/terminal/assets/13610277/f9927ca6-7344-45cf-87fe-6c2ad43717a2)
![image](https://github.com/microsoft/terminal/assets/13610277/1ab77ec3-09d3-45f4-aaa7-ab9826311bda)
