### ISSUE TITLE
Support exe/dll paths in the 'icon' setting

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#1504]
# Support exe/icon paths in the 'icon' setting of a profile

The icon setting of a profile should allow the path to an EXE or DLL to be specified, along with an optional ID for an icon resource in the file.

For example, I should be able to create a profile using icons from SHELL32:
```
    ...
    "icon": "c:\Windows\System32\SHELL32.dll,210",
    ...
```

Optionally, if the icon is missing and the executable from the command line has icons, pick the default icon, much like how the shell does.

**Comment by Karl-WE** [comment]
I agree. or things like "icon": "C:\Program Files\PowerShell\6-preview\pwsh.exe",

**Comment by DHowett-MSFT** [comment]
Yeah, it would be pretty cool if we did this.

**Comment by DHowett-MSFT** [comment]
Notes: Right now we're using the XAML resource loader to get at our icons. If we want to support EXE/other PE resources we'll need to fall back to a more win32-like resource loader. There are real benefits to the XAML one, such as _it choosing the right icon scale_ and supporting vector graphics and stuff like that. I've tagged it `help-wanted`.

**Comment by Karl-WE** [comment]
@DHowett-MSFT afaik not even the settings app in Windows uses SVG graphics but PNGs. I stumbled across them once. I see the point of having this more modern and getting rid of old ico restrictions.

**Comment by zadjii-msft** [comment]
This is highly related to #705 (but definitely different)

**Comment by gim913** [comment]
> Notes: (…) There are real benefits to the XAML one, such as _it choosing the right icon scale_ and supporting vector graphics and stuff like that. I've tagged it `help-wanted`.

Just FYI: technically single icon inside PE resources can contain multiple icons (with various color depths, sizes - up to 256x256 etc.), that is how you could have same but actually different icon for title bar and for application itself. (that is smaller one was used for title bar).

ofc, afaik vector graphics is/was not an option.

**Comment by zadjii-msft** [comment]
Notes from some tabs I had open for the last few weeks:
* dotnet uses `System.Windows.Interop.Imaging.CreateBitmapSourceFromHIcon`, which obv we can't use. 
* https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/Imaging.cs#L77
* https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/InteropBitmapSource.cs#L91-L96
* [`IWICImagingFactory_CreateBitmapFromHICON_Proxy`](https://docs.microsoft.com/en-us/windows/win32/wic/-wic-codec-iwicimagingfactory-createbitmapfromhicon-proxy)
* Data from that is accessed as in [`IWICBitmapLock::GetDataPointer`](https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicbitmaplock-getdatapointer)

Still not sure if that connects up to a `BitmapImage`. Maybe I should look in the BitmapImage source itself - it can apparently read from `.ico` files, so there's probably some overlap between reading an `.ico` and reading an `HICON`.

**Comment by zadjii-msft** [comment]
Note to self: [`dev/migrie/1504-prototype-2`](https://github.com/microsoft/terminal/compare/dev/migrie/1504-prototype-2)
