### ISSUE TITLE
Input freeze on heavy output

### ISSUE THREAD

**Issue by malchera** [microsoft/terminal#15055]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Produce heavy output (e.g. big compile job, `cat` on very long file). 

### Expected Behavior

Responsive Windows Terminal even when heavy output is in place.

### Actual Behavior

Windows Terminal becomes unresponsive while there is a heavy output. For example, I am unable to even abort a longer compile job that produces heavy output, i.e. CTRL+{C,D,...} don't work anymore and I have to wait for the output to stop.

Another example is Linux' `tmux`. If I have a split window open and start compiling on one side and working on the other, as soon as the output starts my session hangs and I am unable to interact with the terminal (till the end of compilation). I tried the same steps using PowerShell, where it works fine.

**Comment by carlos-zamora** [comment]
Thanks for the report! This is a part of a broader class of issues that we're tracking over in #6258. Marking as a /dup of #6258.
