### ISSUE TITLE
Not able to use reg add. Getting syntax error

### ISSUE THREAD

**Issue by dvein95** [microsoft/terminal#15068]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Try to add reg value but getting syntax error
reg add HKEY_CURRENT_USER\software\microsoft\office\16.0\outlook\search /t REG_DWORD /v test /d 1

### Expected Behavior

expected to add the reg value

### Actual Behavior

syntax error occur

**Comment by DHowett** [comment]
Can you share a screenshot?

This isn't exactly something Terminal is in control of, but we can still try to help.

**Comment by dvein95** [comment]
![terminal_error](https://user-images.githubusercontent.com/129334901/228673036-03e4c095-dd72-4662-9350-0565e7ac2249.PNG)
Pleasee see the screenshot.
If I run the command in PowerShell Terminal there is no issue.
If I run the command using normal cmd there is no issue

**Comment by zadjii-msft** [comment]
Huh. 

This might sound weird, but are you typing the command in, or copy-pasting it/? I wonder if there's a paste filter in conhost that might translate characters that _look_ like `.` or `/` into the ASCII ones.

**Comment by dvein95** [comment]
Hmm, I copy the command in NotePad then it works. Seems Terminal not able to automatic change the ASCII or otherway around

**Comment by carlos-zamora** [comment]
Note to team:
we should either...
- make this the epic for special character filtering for paste, or...
- find a dup (possibly #9380, #6134)
