### ISSUE TITLE
Implement "Reopen Current Directory in [different shell]" in Windows Terminal

### ISSUE THREAD

**Issue by AlgebraManiacABC** [microsoft/terminal#15069]
# Description of the new feature/enhancement

Problem: My default shell in Windows Terminal is Ubuntu (through WSL). When in a directory deep in subfolders, I sometimes would like to open that directory in PowerShell (not the console powershell, but Terminal powershell). The issue is that when I right click and open in Terminal, I am brought into WSL. There are currently no options to "reopen working directory in PowerShell." I would have to manually open a new tab in PowerShell, then copy the directory from File Explorer and paste into PowerShell after typing `cd `. On top of this, spaces are not automatically treated upon paste, so I would have to enclose the pasted directory in `'`s or manually escape each problematic character. This is unideal.
Proposed new feature: There should be an option when making a new tab to reopen the current working directory in said shell.

# Proposed technical implementation details (optional)

Shown is the current view when right-clicking a tab:
![image](https://user-images.githubusercontent.com/39248961/228667634-04673af9-0145-4dae-9704-64d7df6fc9bf.png)
Now, shown below is my proposed suggestion.
![image](https://user-images.githubusercontent.com/39248961/228669318-a468a286-57bd-454f-aaa9-63f5d0bbbffb.png)
This is one possible solution (right clicking current tab). This is likely the easiest to implement, since "duplicate" likely uses much of the code needed to implement this feature. The only wrinkle would be converting that directory into a PowerShell-accepted directory (i.e., not `/mnt/c/Users/` but `C:\Users`). Also, purely WSL directories (i.e., `/home/luke`) would have to be figured out (I know they are accessible, since I have done so by opening a WSL directory through Visual Studio Code).
In any case, this should provide a base idea on implementation. The icon is something I just scribbled in Paint.NET, so feel free to recreate it better or with a completely different icon idea.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10232 for more discussion.

/dup #10232
