### ISSUE TITLE
WT disappears after 3 days!?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#15067]
### Windows Terminal version

WindowsTerminalPreview: 1.17.2301.23004

### Windows build number

10.0.19045.2728 (2009, 22H2)

### Other Software

Using TCC shell as a testing platform.

### Steps to reproduce

Start WT and wait 3 days.

### Expected Behavior

It continues to run.

### Actual Behavior

It unceremomiously terminates with no local dump file.

In Fall 2022, I started to notice WT not running when I expected it to be running.  This happened several times during fall and winter and always seemed to happen after about 3 days.  Once, I witnessed WT disappearing while I was playing solitaire!  So finally I did a test.

With a TCC batch file running outside WT, I logged the start time of WT (from WMI) and I used MsgWaitForMultipleObjectsEx on a HANDLE to the WT process (and a wait_cancel_event HANDLE). Not having cancelled the wait, I logged the time (current local system time) when WT terminated.  Here's the log file.

WindowsTerminal.exe (PID 10460) started:    2023-03-26 03:00:51
WindowsTerminal.exe (PID 10460) terminated: 2023-03-29 03:00:54

Notes:  I'm pretty sure you can't blame the shell because in those 3 days, what shells were running in WT changed several times, and none were running for the whole 3 days.  And you can't blame me because I was in dreamland when the test ended.  As I said before, there was no local dump file (local dumps are enabled).

I'd be happy to test further but I can't think of any good tests.  I'm pretty confident the same test will produce the same result.

**Comment by carlos-zamora** [comment]
Hi @vefatica. Could you please [capture an ETL trace](https://github.com/microsoft/terminal/wiki/Capturing-a-Debug-ETL-Trace) of this occurring?

**Comment by vefatica** [comment]
I don't see anything downloadable there.  Please give precise downloading instructions.

I didn't mention earlier ... in my test, WT was (and is almost always) running elevated.   I'll bet the actual time was exactly 3 days.  I know where the extra 3 seconds came from (my own time-sync/clock-skew service).

**Comment by zadjii-msft** [comment]
1. Click on "[Terminal.wprp file from this repository](https://github.com/microsoft/terminal/blob/main/src/Terminal.wprp)"
2. Click on the download button: 
  ![image](https://user-images.githubusercontent.com/18356694/228677526-2aaeb88f-a93a-4fd3-8023-3b13660a331a.png)
  (This may look different depending on pace of GH feature rollout)

**Comment by vefatica** [comment]
If you mean this,

![image](https://user-images.githubusercontent.com/61856645/228678987-d442f682-5b16-4ed4-9d93-4709f03c7284.png)

"Terminal.wprp" not clickable.

**Comment by DHowett** [comment]
...

**Comment by DHowett** [comment]
CLICK THIS
<img width="33" alt="image" src="https://user-images.githubusercontent.com/189190/228689311-1579da64-fbe6-4c73-b110-2ef3a1b1be93.png">

It is the universally accepted icon for "download".

**Comment by vefatica** [comment]
Apparently I'm not seeing what you're seeing.

![image](https://user-images.githubusercontent.com/61856645/228699623-86c81411-7599-4254-91d4-62c829656c22.png)

**Comment by DHowett** [comment]
_What on earth?!_

Okay, for now, uh... click on "Raw", and use <kbd>Ctrl+S</kbd>

I think I'm going crazy! :)

**Comment by vefatica** [comment]
That just downloads Terminal.wprp.txt with the XML in it.

**Comment by DHowett** [comment]
Then rename it! You're the one who thought injecting a remote thread into Explorer to set environment variables was a good plan - I know you can handle a little XML file with the wrong extension! 😁

**Comment by vefatica** [comment]
I know epsilon about XML and obviously even less about exactly what's supposed to happen here.  Rename it what?  And then what?

**Comment by vefatica** [comment]
OK.  I think I have this figured out.  Will this (below) work?

Wait until the expected disappearance of WT is imminent That's now somewhat less than 3 days.

wpr -start v:\Terminal.wprp!Terminal.Verbose

After WT has disappeared ...

wpr -stop terminal-trace.etl

zip the ETL file and post/send it.

**Comment by DHowett** [comment]
That'll work for us! Thanks, and sorry about the download confusion.

**Comment by vefatica** [comment]
And I apologize for being slow to figure it out.  At first I thought I would be downloading the WPR tool.  Then I found it here already and figured out that I only needed the XML.

I'm also new to PerfView, just learned of it yesterday.  Should I be able to view a trace, made as described above, with PerfView?  I have symbols (maintained by WinDbg).

**Comment by vefatica** [comment]
Right on schedule, WT disappeared 3 days after it was started.  Here's a bit of a transcript.  The zipped ETL file is attached but, to be honest, it doesn't look very interesting.  I started the trace about 10 minutes before the disappearance.  In the last three days my w32tmsvc added 2.5 seconds to the system clock, explaining, I reckon, the difference between 3 days and the observation below.

```
v:\> wpr -start v:\Terminal.wprp!Terminal.Verbose

v:\> set pid=%@wmi[.,"select processid from Win32_Process where Caption='windowsterminal.exe'"] & echo Start: %@wmitcvt[%@wmi[.,
"select CreationDate from Win32_Process where ProcessId=%pid"],T] & wait /p %pid & echo Stop:  %_date %_t9
Start: 2023-03-29 11:42:42.788
Stop:  2023-04-01 11:42:45.373

v:\> wpr -stop terminal-trace.etl

v:\> zip disappear.zip terminal-trace.etl
<= V:\terminal-trace.etl
```
[disappear.zip](https://github.com/microsoft/terminal/files/11129977/disappear.zip)

**Comment by vefatica** [comment]
Solved!  "Stop the task if it runs longer than 3 days" is a default setting of Task Scheduler which I never paid much attention to.  I typically start WT via an AutoHotKey script executing `u:\schtasksw.exe /run /tn wtelevated`.  Schtasksw.exe is a GUI version of schtasks.exe (made with editbin.exe) and the "wtelevated" task is on-demand with highest privileges.  Starting WT in this way avoids the UAC prompt.  Sorry about the false alarm.

I'm still curious.  Did terminal-trace.etl work as expected? ... have anything in it about what WT was doing?

**Comment by zadjii-msft** [comment]
Well, that's wild, but a good new thing to learn about!

The .etl did work perfectly fine. From what's in there, it looks like the Terminal was doing... nothing. Not processing any data, not opening new tabs or anything, just hanging out. There was a few events for the regularly scheduled "let's make sure we persist all the window positions" thread, but really nothing else interesting. Nothing in there would indicate a crash, but that's cause it _didn't_, so neato!

Thanks for following up!

**Comment by vefatica** [comment]
Using PerfView, could I have learned from the .ETL file what you learned (however little there was to learn)?  Do you use PerfView or a different tool?

It's comforting to know that when Task Scheduler says "3 days" it means 3 days!  :-)

**Comment by zadjii-msft** [comment]
Probably, but I haven't ever learned to use that lmao. I use an internal tool just dumps the tracelogging events, which is what I was looking for. PerfView would probably have quite a bit more info than even that.
