### ISSUE TITLE
The left side of the label bar renders extra vertical lines

### ISSUE THREAD

**Issue by Curious-r** [microsoft/terminal#15063]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.25324.0

### Steps to reproduce

Open Windows Terminal, open any tab, and observe the left side of the tab header.

### Expected Behavior

No extra vertical lines are rendered.

### Actual Behavior

<img width="457" alt="image" src="https://user-images.githubusercontent.com/19733878/228475677-8a3b1073-4a63-4a34-999c-3eb0ba2e1985.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/19733878/228475812-67807021-09d2-4ec2-b333-2d3aa8e6536e.png">

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #14905 for more discussion.

/dup #14905
