### ISSUE TITLE
Wrong printed/parsed characters on Terminal

### ISSUE THREAD

**Issue by D3vil0p3r** [microsoft/terminal#15070]
### Windows Terminal version

1.16.10262.0

### Windows build number

Microsoft Windows NT 10.0.22621.0

### Other Software

python 3.10.10

### Steps to reproduce

By using Windows Terminal with WSL, the `\001` and `\002` Python characters are not parsed correctly.

Open WSL container of Ubuntu or Arch Linux. Run:

if Ubuntu:
```
python3
```

if Arch:
```
python
```
Once Python is run, type the following:
```python
MAIN = '\001\033[38;5;85m\002'
END = '\001\033[0m\002'
INFO = f'{MAIN}Info{END}'
print(f'\r[{INFO}] Core server started on')
```
The result will be:
![image](https://user-images.githubusercontent.com/83867734/228796299-c31d6307-6a2f-46bf-9de7-9a64f7f6ffdf.png)

The reason of using `\001` and `\002` when colors should be used is described in https://bugs.python.org/msg208948

This issue seems to appear only on Windows Terminal with and without WSL (with different displaying characters output).

Issue opened here as agreed in https://github.com/microsoft/WSL/issues/9870

### Expected Behavior

The result should be:
```
[Info] Core server started on
```
Note that the real output has `Info` string colored.

### Actual Behavior

The wrong result is:
![image](https://user-images.githubusercontent.com/83867734/228796392-6fb1a02a-9e5d-4a79-962a-cc53aa717ef3.png)

**Comment by j4james** [comment]
Thanks for the detailed report, but we do already have an issue for this. It's being tracked in #10786.

**Comment by D3vil0p3r** [comment]
> Thanks for the detailed report, but we do already have an issue for this. It's being tracked in #10786.

Thank you for the answer. I hope it will fix soon. The linked issue was opened on July 2021.
