### ISSUE TITLE
Error 0xffffffff starting WSL from WT

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#15072]
### Windows Terminal version

1.16.230126001

### Windows build number

Microsoft Windows [Versione 10.0.19045.2788]

### Steps to reproduce

I reported this also to WSL people [#9875](https://github.com/microsoft/WSL/issues/9875#issue-1648081978)

I used WSL since it was added to W10 and followed its evolution migrating from WSL1 to WSL2 when it was added. I enabled [systemd](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#set-the-systemd-flag-set-in-your-wsl-distro-settings) a few months ago and **all worked just fine until today**. 

Now when I start WSL fro Windows Terminal (WT) it prints

```
[processo terminato con codice 4294967295 (0xffffffff)]
```

and in WT prints the message `It is possible to configure termination... bla bla`

I upgraded `WT 1.16.230126001` on January from the msixbundle package and worked just fine 

Now I get the above error: **it occurs only when I start WSL from WT!!!** If I start it using MinTTY, with a link (lnk) whose target is 

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\user\.minttyrc -t "WSL Terminal" --position 20,450 /usr/bin/wslbridge2.exe -d Ubuntu -W "~"
```

**WSL starts without error.** As workaround, to start it from WT, I have to reboot but I can only start it once: if I close the Ubuntu tab and restart it the error reappears...

I did not change anything in the configuration: both in Windows and in WSL or WT. May be a Windows upgrade? there was one few days ago.. but until yesterday all worked.. I did also a windows cleaning (System - Archive - temp files etc..) but I worked with WSL up to March 29 21:47 (a timestamp of a file produced by TeXLive) so it is a mistery why now it does not work from WT but only with MinTTY...

### Expected Behavior

WSL should start

### Actual Behavior

WSL gives the above error

**Comment by lhecker** [comment]
(I've edited your comment to fix the link, which was previously pointing at just "url".)

**Comment by zadjii-msft** [comment]
Yea, I'm pretty sure there was a change in the way WSL is delivered recently. Can you confirm if `wsl --update` works/?

**Comment by angelog0** [comment]
It seems that something was corrupted in my system. Running

```
sfc /scannow
DISM /Online /Cleanup-Image /RestoreHealth
```

seems to have fixed the issue. 

`wsl --update` works..

I am going to close this...
