### ISSUE TITLE
key bindings increaseFontSize and decreaseFontSize are REMOVED from profile when Terminal is restarted

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#1508]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Add keybindings for increaseFontSize and decreaseFontSize in the profile settings.
Close and restart Windows Terminal.

# Expected behavior

For keybindings to be in the profile, as pre-configured.

# Actual behavior

Profile file is reformatted and the bindings for increaseFontSize and decreaseFontSize are lost.

**Comment by DHowett-MSFT** [comment]
Nonexistent bind commands are deleted, by design. We have workitems out to improve messaging there.

**Comment by DHowett-MSFT** [comment]
Unfortunately, you can’t just guess at binding names. Sorry about that.
