### ISSUE TITLE
copy singleLine does not work with block select

### ISSUE THREAD

**Issue by yellowtailfan** [microsoft/terminal#15085]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1413

### Steps to reproduce

I would like to be able to copy a column from a command listing output and feed it into another command as a sequence of command line arguments.

Here's a simple reproduction of the problem:
1. Run Ubuntu Bash via WSL2 in Windows Terminal
2. Type: `ls -l` and press Enter
3. Hold down Alt and drag the mouse to select a column from the listing
4. Command palette > Copy as single line (or use a keyboard shortcut assigned to copy singleLine=true)
5. Type: `echo ` but don't press Enter
6. Paste
7. Press Enter

### Expected Behavior

The column should be pasted as a single line, and then printed as a single line by `echo`.

### Actual Behavior

Only the first row in the column is pasted as a single line. `echo` prints the first row, then Bash receives the remaining rows as separate lines and tries to run each one.

If I use normal selection (not block selection) then Copy as single line does the expected behaviour.

The problem is not unique to pasting into Windows Terminal or Bash. The same behaviour happens if I paste into another app, e.g. into VS Code.

**Comment by yellowtailfan** [comment]
A work around after the _Copy as single line_ step above is to use the `paste` command:
1. Type `'`
2. Paste
3. Type '` | paste -sd " " -`
4. The column is output on a single line
5. Copy the single line
6. Type the actual command you want to run
7. Paste the single line as the arguments

**Comment by carlos-zamora** [comment]
Thanks! Marking this as a /dup of #15153. @lhecker said he was going to rewrite this section of the code sometime soon.
