### ISSUE TITLE
As soon as you open it, it will always flash

### ISSUE THREAD

**Issue by freedomspiritJohn** [microsoft/terminal#15099]
### Steps to reproduce

![GIF 2023-4-4 9-42-50](https://user-images.githubusercontent.com/129288685/229665295-ad2d5f77-b983-4068-9b63-657b487fa92f.gif)

### Actual Behavior

always flash

**Comment by zadjii-msft** [comment]
@freedomspiritJohn Did you set `elevate:true` in the `profiles.defaults` part of your settings/? This might be #13928

**Comment by freedomspiritJohn** [comment]
> @freedomspiritJohn Did you set `elevate:true` in the `profiles.defaults` part of your settings/? This might be #13928

I don't know，i cant open it。I reset this application in the settings，It's normal now。But I hope this can be avoided in the future

**Comment by zadjii-msft** [comment]
Welp. Since you can't repro this anymore, I'm just gonna assume it was that. #14946 which is the fix for #13928 should be coming out soon enough in a servicing release for 1.16 and 1.17.
