### ISSUE TITLE
vim，The word under the cursor is not visible

### ISSUE THREAD

**Issue by Tao-Wei** [microsoft/terminal#1510]
I added the code in .vimrc:
```
let &t_SI.="\e[5 q"
let &t_SR.="\e[4 q"
let &t_EI.="\e[1 q"
```
cursor style can be changed but the word under the cursor is not visible 
![image](https://user-images.githubusercontent.com/46256982/59994229-af74e080-9685-11e9-84d5-a99d2d25d410.png)

**Comment by JushBJJ** [comment]
That's just how terminal is I think, but you can change the cursor shape into a "emptyBox" (Referenced in https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)

**Comment by Tao-Wei** [comment]
It looks very uncomfortable. Is there any solution？

**Comment by benjif** [comment]
The only current solution I could find is setting `cursorShape` to something other than "filledBox" in your config file (e.g. emptyBox, underScore, bar, or vintage).

**Comment by benjif** [comment]
I believe the only current solution is changing cursorShape in your profiles.json,

**Comment by DHowett-MSFT** [comment]
We'll need to look at different cursor color styles like "invert". This is, however, how some terminals just work.

**Comment by zadjii-msft** [comment]
This seems related to #1356

**Comment by DHowett-MSFT** [comment]
We should just call this a duplicate of #1356. Having configurable cursor styles/making invert work would be part of the same workitem.
