### ISSUE TITLE
delete last word hotkey [Ctrl + Backspace]

### ISSUE THREAD

**Issue by bkngdcla** [microsoft/terminal#1511]
all other terminals (cmd, powershell, pwsh) allow ctrl + backspace to remove the word.
CTRL + SHIFT + Arrow should be able to select the word.
aka standard hotkeys that we are now used to.

Cheers

**Comment by DHowett-MSFT** [comment]
#755 has “ctrl backspace” in the title and probably came up in the suggestion box when you added this issue. Please make sure you search before reporting.

**Comment by lucky-wolf** [comment]
I hate that these things never actually get fixed or resolved.

WTF?
