### ISSUE TITLE
`more` command doesn't advance to the next screen of text if I press spacebar 

### ISSUE THREAD

**Issue by adrastogi** [microsoft/terminal#15116]
### Windows Terminal version

1.18.902.0

### Windows build number

10.0.23432.1000

### Other Software

I tested this in cmd and PowerShell (version info below):

```
Name              : Microsoft.PowerShell
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 7.3.3.0
```

### Steps to reproduce

1. Within cmd.exe or pwsh.exe, and with a file that has at least a 'screenful' of text (e.g., call it `foo.txt`), try using `more foo.txt` to view the file's contents, one screenful at a time.
2. After the first screenful is displayed, try pressing spacebar to advance to the next chunk. 

### Expected Behavior

The Terminal advances to the next page of text.

### Actual Behavior

The Terminal remains at the current screen; I see the cursor flashing as normal. I also can't Ctrl+C out of this. 

I don't see this behavior in retail Terminal (version 1.16.10262.0)- `more` behaves as I would expect there.

**Comment by DHowett** [comment]
Aahhhh. This could be an OpenConsole crash? Can you check to see whether there's still an OpenConsole instance running for that terminal tab?

(The renderer is still working, evidenced by the cursor flashing.)

/cc @lhecker for potential buffer impact

**Comment by adrastogi** [comment]
Thanks for taking a look! OpenConsole is still running per Task Manager.

**Comment by Treit** [comment]
I am hitting this issue as well, 100% consistent repro. Pressing ctrl+break gets me 'unstuck' but all other key presses seem to be ignored.

**Comment by zadjii-msft** [comment]
I wonder if this is from the linefeed changes in #14874

**Comment by DHowett** [comment]
This also happens in OpenConsole...!

**Comment by DHowett** [comment]
Broken in a build made on 2023 day 81.
Works on 2023 33.
Broken on 2023 62.

**Comment by DHowett** [comment]
@lhecker regressed in #14745 (`TranslateUnicodeToOem`)

I bet it's reading input with `ReadConsoleInputA`! 😉
