### ISSUE TITLE
Closing a pane with an open debug tap hangs terminal

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#15119]
### Windows Terminal version

1.18

### Steps to reproduce

Open a debug tap.
Close the left pane.

### Actual Behavior

It hangs.

**Comment by DHowett** [comment]
Fortunately, it only hangs the one window. If you kill that window, though... yeah.

**Comment by j4james** [comment]
Is this not the same thing as #14898?

**Comment by DHowett** [comment]
Sure does! Thanks!

/dup #14898
