### ISSUE TITLE
option for full width scrollbar

### ISSUE THREAD

**Issue by 4cq2** [microsoft/terminal#15113]
With Windows Terminal v1.12.1073, the scrollbar looks like this:

> ![good](https://user-images.githubusercontent.com/126826528/229935450-1a7d02f7-188c-4ce7-b2b5-bffd0aa07fdd.png)

however starting with the next version, Windows Terminal v1.12.1098, the scrollbar is narrow:

> ![bad](https://user-images.githubusercontent.com/126826528/229936342-104da105-fb39-486b-9046-90a3c1c5517e.png)

and in future versions even rounded at the corners. I find these changes distracting. Also, they are different from my browser Mozilla Firefox:

> ![firefox](https://user-images.githubusercontent.com/126826528/229936592-e2bb685a-5acc-423c-bbba-2c4e2604e5b8.png)

My editor Vim:

> ![vim](https://user-images.githubusercontent.com/126826528/229936708-a04a4bae-3502-4f43-9fdb-608a57744940.png)

and even Windows Explorer:

> ![explorer](https://user-images.githubusercontent.com/126826528/229936853-1f14d304-6b5f-4f11-a22b-ee80c9c73b18.png)

does Windows Terminal have some option to restore the scrollbar to full width? otherwise I will be forced to use the old version forever.

**Comment by 4cq2** [comment]
here is link for last "good" version for anyone who needs it:

https://github.com/microsoft/terminal/releases/tag/v1.12.10732.0

**Comment by j4james** [comment]
I believe this option is being tracked in #9218.

**Comment by carlos-zamora** [comment]
Thanks! Looks like a /dup of #9218
