### ISSUE TITLE
Reordering tabs messes up relation between tabs and panes

### ISSUE THREAD

**Issue by djdv** [microsoft/terminal#15121]
### Windows Terminal version

62448969b30325a75f35201427a052de0e4dbb7d

### Windows build number

10.0.25330.0

### Steps to reproduce

Open multiple tabs. Reorder them.

### Actual Behavior

The relation/index between tabs and panes is now broken.
Selecting a tab will select a pane which does not belong to that tab. Closing panes will close the wrong tab.
See: https://www.youtube.com/watch?v=Qa9jxFnvI8U

**Comment by zadjii-msft** [comment]
More concrete repro steps:

* Open two windows
* In one window, open two tabs. Pwsh and CMD are good, so they're clearly separate. 
* Reorder those two. 
* Drag the inactive one to the other window. 
* Experience having the active term core in both windows!

**Comment by zadjii-msft** [comment]
oh its so bad

Just reordering tabs, no tearout, just breaks the entire relationship of it. I wonder if adding these drag/drop handlers somehow broke the reorder events we get

**Comment by zadjii-msft** [comment]
Upstream: https://github.com/microsoft/microsoft-ui-xaml/issues/8388
