### ISSUE TITLE
Something _WinUI_ did made tabs "slide" when they resize

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#15139]
### Windows Terminal version

1.18.96

### Steps to reproduce

I don't think this happened on 1.16.93 (!) which also had MUX 2.8

Have a tab. TabWidthMode = TitleLength (the one true setting)

### Actual Behavior

![WindowsTerminal_20230407T102232_986](https://user-images.githubusercontent.com/189190/230634242-9d99255c-56ab-4cc2-886b-2e6d92f80002.gif)

**Comment by zadjii-msft** [comment]
Oh no I can't repro this on 1.18.931.0. I don't think that had MUX 2.8...

**Comment by zadjii-msft** [comment]
The easiest way to repro this: just add this line

```json
    "tabWidthMode": "titleLength",
```

and comment / uncomment

**Comment by zadjii-msft** [comment]
This is the upstream https://github.com/microsoft/microsoft-ui-xaml/issues/8384
