### ISSUE TITLE
SESSIONNAME not set during RDP operations

### ISSUE THREAD

**Issue by jmecosta** [microsoft/terminal#15134]
### Steps to reproduce

RDP to computer, and start windows terminal old and new. new one 
C:\Users\sds>echo %SESSIONNAME%
%SESSIONNAME%

### Expected Behavior

SESSIONNAME should be consistent across all terminals

### Actual Behavior

SESSIONNAME  not set in windows terminal in RDP sessions

**Comment by DHowett** [comment]
Thanks for the report! This is a /duplicate of #14711, and while `SESSIONNAME` is not intended to be _reliably present,_ we believe that the work done in #12516 and #14999 will fix it when they are released in 1.18.
