### ISSUE TITLE
Rethink settings grouping

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#1513]
Referencing #754 and #1448, I think it's best to abandon separation between global/profile settings. Instead each setting could go to anywhere, but with profile settings overwriting global ones. There still will need to be global-only settings like `showTabsInTitlebar` or `defaultProfile`, but others could be made available as per-profile (e.g. `keybindings` or `initialCols`).

Additionally, I suggest a 'property groups' - groups of settings that you can '`#include`' in profiles (like `include: ["guid1", "guid2"]`). E.g. you may want to have consistent settings between wsl distros and anothers between cmd/ps profiles. (I can easily imagine profiles that differ only in command line, starting path or something like this, but have other settings, mostly, shared.)

Issues:
- How should default settings look (what goes where?)
- Design of settings GUI that support this might be hard

**Comment by DHowett-MSFT** [comment]
This'll probably be helped out a lot by #754 -- i'd like to hold off on further settings discussions until that one lands. We'd be happy to hear your settings feedback in 754 or on the spec review #1258.
