### ISSUE TITLE
Tabs are still padded at the edge of the screen when Terminal is maximized and display scale is not 100%

### ISSUE THREAD

**Issue by JamesBulman** [microsoft/terminal#15138]
### Windows Terminal version

1.16.10262.0

### Windows build number

Microsoft Windows [Version 10.0.22621.1485]

### Steps to reproduce

Set Windows display scale to 150%
Open Terminal
Maximize Terminal
Open a second tab in Terminal
Click on inactive tab at the top edge of the screen to change between tabs.

### Expected Behavior

Inactive tab should activate when Terminal window is maximize and tab is clicked on at the edge of the screen.

### Actual Behavior

Inactive tab does not activate.

**Comment by JamesBulman** [comment]
This is related to issue [#2541](https://github.com/microsoft/terminal/issues/2541) and [#5881](https://github.com/microsoft/terminal/pull/5881)

This feature works correctly when the display scale is set to 100%, but if it is set to a different scale space is introduced between the edge of the screen and the tab. This makes it impossible to click on the tab when the mouse cursor is at the edge of the screen.

This is a video of it working correctly (display scale 100%):

[Correct Tab Behaviour](https://i.imgur.com/1bCZl5T.mp4)

This is a video of it not working (display scale 150%):

[Incorrect Tab Behaviour](https://i.imgur.com/1ry63fF.mp4)

**Comment by zadjii-msft** [comment]
I'm almost certain this is /dup #11309. Seems like it's somehow related to the layout of the monitors itself - I've had no luck in reproing it on my current setup, but I believe that @DHowett has had some luck in the past (if he wants to try and debug it)
