### ISSUE TITLE
There is a small gap under a maximized or full-screen window when "Automatically hide the taskbar" is enabled.

### ISSUE THREAD

**Issue by harenayo** [microsoft/terminal#15145]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1485

### Steps to reproduce

1. Enable "Automatically hide the taskbar".
2. Enter full-screen mode.

### Expected Behavior

![](https://user-images.githubusercontent.com/123649644/230726886-b2a659ea-6fc4-4613-b4d7-5d0bfffa1ea0.png)

### Actual Behavior

![](https://user-images.githubusercontent.com/123649644/230726907-e0dbcb55-10b1-4674-a975-e6ab0afc0e6c.png)

**Comment by j4james** [comment]
This sounds like it may be the same issue as #12959.

**Comment by carlos-zamora** [comment]
Thanks for the bug report! We'll mark this as a /dup of #12959.
