### ISSUE TITLE
Crash on debug

### ISSUE THREAD

**Issue by AmirulOm** [microsoft/terminal#1514]
I'm able to build the solution in my VS19 (Debug mode, X64), however running the debug crashed the app. 

Below is the error pop out:
![image](https://user-images.githubusercontent.com/6210597/59996788-e9e27b80-968d-11e9-82a0-f4893557a9dd.png)

Notes: i tried to install Terminal using Microsoft Store, it failed to start/crash as well. Release setting also behaving the same

**Comment by ervays** [comment]
Same issue here.

**Comment by adiviness** [comment]
What's the stack trace?

**Comment by AmirulOm** [comment]
I don't see any stack call on my VS, 

![image](https://user-images.githubusercontent.com/6210597/60064245-5b740580-9732-11e9-92a8-0cd29e4c179b.png)

**Comment by AmirulOm** [comment]
I just found the bug, it turns out if I were to DISCONNECT my external display/monitor and only use my laptop screen it can run without problem, if i were to connect it back the same crash happen.

Weird, 

![image](https://user-images.githubusercontent.com/6210597/60064534-4cda1e00-9733-11e9-86f4-4d588f93624d.png)

**Comment by adiviness** [comment]
You need to press the `Retry` button in that popup for the stack trace to appear. I'm thinking that this might be related to a bug we had with software rendering, try pulling/building the latest changes from `master` and let me know if it's still crashing.

**Comment by AmirulOm** [comment]
I've pulled the latest `master 54457e550a5cabb9b3de6fa7c31257e34aabee7b` , clean, and build (Release x64). Same crash issue.

> You need to press the `Retry` button in that popup for the stack trace to appear. I'm thinking that this might be related to a bug we had with software rendering, try pulling/building the latest changes from `master` and let me know if it's still crashing.

**Comment by DHowett-MSFT** [comment]
We can’t get the stack trace for the crash you are seeing unless you press RETRY to break into the debugger.

**Comment by AmirulOm** [comment]
After click the retry button on Debug mode, everything froze, no stack trace or whatsoever. the button is unresponsive.

**Comment by DHowett-MSFT** [comment]
When you launch the terminal in Debug mode, and then press Retry, *visual studio* will catch the crash in the background and give you a stack trace. If you're not finding that, you might not be the target audience for the development builod.
