### ISSUE TITLE
Input randomly gets ignored when applications wait for input

### ISSUE THREAD

**Issue by Gnbrkm41** [microsoft/terminal#15143]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.25330.0

### Other Software

Powershell 7.4.0-preview.2

### Steps to reproduce

Using Powershell, execute a program that waits for a user input (e.g. C#'s `Console.ReadLine()`).

There is no reliable reproduction steps, unfortunately (at least I haven't found any reliable way to do so) It *really* seems to happen randomly, and it has happened for... not exactly sure how long, the last 2 months or so?

### Expected Behavior

Application should accept user inputs from keyboard just fine.

### Actual Behavior

Any input made to that tab is ignored. This includes any sort of text input, and attempts to close the program using Ctrl+C is also ignored. If I open a new tab in the same terminal instance, that new tab would accept inputs just fine. There is no way to do anything about the seemingly frozen app; I need to close the offending tab and start all over again. (at least I haven't had it happen in a row, *yet*)

Some additional context:
I am using insider builds of Windows 11 Pro (Canary). Currently it's at 25330.
I am not using Remote Desktop.
I am using Windows' built-in Korean IME, the layout being Korean 101 key type 1 keyboard.

Regarding the TabletInputService service, I actually cannot locate the service under the name of 'Touch keyboard and handwriting service'; I found 'Text Input Management Service' instead which says it has to do with text inputs and touch keyboard so maybe it has changed its name in Windows 11? I haven't touched anything regarding that service, haven't ran any 'debloating' tools, do not have MSI Afterburner installed, and Terminal does not show any warnings about it (from what I've found it should show warnings when the service is not running? although I got Terminal from MS Store so maybe it wouldn't show that anyway). I think it's highly unlikely that this is the issue. ctfmon seems to be running just fine, which seems to be what really matters at the end. Plus, as I said above, it's only the offending tab that ignores inputs; if I open a new tab, I can type in just fine in that new tab, so it's not like inputs are not working all the time. I was able to type in the command to start executing that program in the first place!

There are three possible failure points I can see, one being the program itself, one being Powershell which I ran the command through, and the last one being the terminal. It's probably very unlikely that there is a problem with the program itself; I've had it happen with a program I wrote on my own, but also with well-known programs like FFMpeg. Not sure about Powershell and Terminal though. I am also not sure if this happens only when it's run through Powershell.

I understand this kind of problems are near impossible to diagnose on your side with no extra info. Is there any other useful debugging info I can provide (e.g. minidumps or full memory dumps)? I can try gathering extra info if someone could tell me what kind of stuffs I can do next time this happens.

**Comment by lhecker** [comment]
The way you describe the issue it sounds like the window isn't frozen right? Because of this, I suspect that a minidump won't be of help, since the application is still running and you'd have to capture the exact moment you press a key for us to see the stack traces. As such I fear, the only way to debug this is if we either find a repro and we can run this interactively in a debugger, or for you to debug it yourself.

Although I'm concerned about you using the IME. None of us on the team actively use the IME in our daily lives, so it's not as well tested as the rest of the application and Korean is a notoriously very very difficult language (from an IME / Unicode standpoint). So I'm wondering: If you switch to a keyboard layout that doesn't require the IME (like US English), does the issue still occur? Is there maybe a specific sequence of characters that triggers the issue?

**Comment by hex-developer** [comment]
Can this issue please be reopened? I have a similar problem too. I am running a Python program in the terminal. It takes user input through the input() function. Unlike the original issue, I am using a US English keyboard and git bash as my shell. Usually after running the program once, when I run it again, I can successfully type once. When I type after that, I see my cursor blinking, but no text is being shown.

System: Windows 10 build 19045.2913
Windows terminal version: 1.16.10261.0

**Comment by hex-developer** [comment]
My program is for using GPT with the API:
```
import openai
openai.api_key = "my api key"
c = "Human: Hello\nAI: How can I help you" # start conversation
while True:
    c += "Human: " + input("Human: ") + "\nAI: "
    response = openai.Completion.create(model="text-davinci-003", prompt=c, temperature=0, max_tokens=2048)["choices"][0]["text"]
    print("AI: ", response)
    c += response + "\n"
# stop with ctrl-c
```

From a programming aspect, it has quite a few problems (as the conversation size increases, less tokens are left). Basically it was a quick test for the API, no serious code.

However, checking the code, there is no error. It is all correct Python, so I think there shouldn't be any problem. I tried to reproduce the error with Git Bash without using Windows Terminal and the program works fine. There must be some problem with Windows Terminal.
