### ISSUE TITLE
Holding a specific area at the top of the window does not achieve dragging

### ISSUE THREAD

**Issue by freewangba** [microsoft/terminal#1516]
![image](https://user-images.githubusercontent.com/37213113/59999479-a93a3080-9694-11e9-900f-ee5f3b111cf0.png)

**Comment by Shorotshishir** [comment]
please refer to issue  #1375 
thank you

**Comment by merlinfrombelgium** [comment]
+1

**Comment by HBelusca** [comment]
Duplicate of #1500, #1412, #1395 ; issue encompassed in #1375.

**Comment by DHowett-MSFT** [comment]
That's right. Thanks @HBelusca!
