### ISSUE TITLE
GUI progress bar when Deleting a folder in CMD

### ISSUE THREAD

**Issue by jeeveshlodhi** [microsoft/terminal#15163]
It would be good to have a slider of some GUI element when using the command rmdir /s <directory_name>.
I was trying to delete a directory from the terminal and it does not show how much the process is done or how much time it will take to complete.

If we have this feature it would be more convenient to delete a file as we would know its progress.

I want a symbol based slider as which will let me know the progress of the file I am trying to delete.

**Comment by zadjii-msft** [comment]
Thanks for the request! Unfortunately, `rmdir` is a part of `cmd.exe` itself, and [we're not about to take any changes to cmd.exe itself](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#cmd) any time soon. This seems like a great feature request for https://github.com/PowerShell/PowerShell though!
