### ISSUE TITLE
Terminal size changes when dragging window to another monitor

### ISSUE THREAD

**Issue by stevensmedia** [microsoft/terminal#15168]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Other Software

Anonymous Pro font face, 12.0 font size.

### Steps to reproduce

Open a new Terminal on my main monitor (3840x2160, 150% scaling)

Its size is 132 columns by 60 rows, which is exactly what my initialCols and initialRows defaults are.

Drag the window over to my second monitor (2560x1440, 100% scaling)

### Expected Behavior

The terminal should remain 132x60

### Actual Behavior

The terminal is now 127x56

Thank you for your time,

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6210 for more discussion.

/dup #6210
