### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zhqqing3** [microsoft/terminal#1517]
# Advice :add it in right click

I am a deep windows user, 
hope it can be put in right click

forgive my worse english !~ 
thanks

**Comment by JushBJJ** [comment]
![image](https://user-images.githubusercontent.com/36951064/60025316-bc70ee80-96dc-11e9-919c-499b4a2c1854.png)
Like this?

**Comment by zhqqing3** [comment]
No  ，Thank you for your reply !

**Comment by zhqqing3** [comment]
No  ，Thank you for your reply !
