### ISSUE TITLE
Enter-PSSession as a profile spins perpetually

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [microsoft/terminal#15172]
### Windows Terminal version

1.16.10262.0

### Windows build number

Microsoft Windows NT 10.0.22621.0

### Other Software

Powershell 7 and Enter-PSSession, New-PSSession (` Microsoft.PowerShell.Commands.[New|Enter]PSSessionCommand`)
```
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Steps to reproduce

<ol>
<li>Manually Enter a PSSession in a reproducable way, ie to a remote AD server like below

```PowerShell
Enter-PSSession (New-PSSession -ComputerName 'ADSERVER2016' -Credential $(Import-Clixml C:\Users\Jonathan\ADServer2016.cred))
```

<details><summary>quick gif</summary>
<ul>

![WindowsTerminal_zU9CxBamRK](https://user-images.githubusercontent.com/62955101/231534446-d460eedd-8959-46d4-8f24-cf0f2878c594.gif)
</ul></details>

<li> Emulate this same command in a new WT profile.
<ol> <li>Copy functioning powershell profile
<li> Append new command with a `-Command` flag
<ul>

##### (I've added newlines to make it easier to read, there aren't newlines in the command)
```PowerShell
"C:\Program Files\PowerShell\7\pwsh.exe" 
    -NoLogo 
    -Command 
        Enter-PSSession $(New-PSSession -ComputerName 'ADSERVER2016' -Credential $(
            Import-Clixml C:\Users\Jonathan\ADServer2016.cred))
```
OR with quotes
```PowerShell
"C:\Program Files\PowerShell\7\pwsh.exe" 
    -NoLogo 
    -Command 
        "Enter-PSSession $(New-PSSession -ComputerName 'ADSERVER2016' -Credential $(
            Import-Clixml C:\Users\Jonathan\ADServer2016.cred))"
```
</ul></ol></ol>

### Expected Behavior

the new profile would connect to the remote ps session, just as the manual ps remote connection is established. 

### Actual Behavior

the profile simply sits there. see below. 

![WindowsTerminal_7Lohg58OTD](https://user-images.githubusercontent.com/62955101/231537222-3e0ae731-a370-4f2c-929b-c115fee94560.gif)

**Comment by DHowett** [comment]
Huh, that's curious!

If you run it through conhost (`conhost pwsh -x -y -z`), or change your "default terminal" to Windows Console Host and run that exact command though the Run dialog, does it repro?

**Comment by Jonathan-Zollinger** [comment]
> ... and run that exact command through the Run dialog

sorry if I'm being thick - are you asking I toss the `Enter-PSSession (New-PSSession -ComputerName 'ADSERVER2016' -Credential $(Import-Clixml C:\Users\Jonathan\ADServer2016.cred))` command in the run box after I've set my default terminal to windows console host? 

if I've understood properly, then this behavior continues with windows console host as well and I would presume this doesn't actually involve Windows Terminal, huh? 

![mPptpJBor9](https://user-images.githubusercontent.com/62955101/231581962-6cb0838c-d2cf-40f7-8045-41c83f23dbf5.gif)

**Comment by DHowett** [comment]
Ah, that's exactly what I was asking for. Thanks for testing!

Indeed -- if it happens with PowerShell without Terminal, it's probably going to be an issue better suited for [the PowerShell repo](https://github.com/powershell/powershell).

_As an aside: what window manager is that? It reminds me of komorebi..._

**Comment by Jonathan-Zollinger** [comment]
ok cool - I'll bring the discussion over there after I make sure it's not already resolved in a previous discussion over there.

ya, it's [Glaze windows manager](https://github.com/lars-berger/GlazeWM) - I was looking for an i3 esque wm for windows when I found it. lars actively maintains it, I've been really happy as a consumer of the software. it has its quirks / is def in its infancy, but it's def helped my productivity on windows, which is real nice to have. 

also it's nice to have all the config in one file instead one config for i3, another for polybar, another for rofi, etc. definitely give it a shot! 

the [wallpaper's my own](https://github.com/Jonathan-Zollinger/wallpapers/blob/main/elephant_pattern.png) - elephants are sort of my daughter's thing, so it's my sneaky way of keeping a pic of her on my desktop
