### ISSUE TITLE
Split Place command key-binding ignore current profile and open default profile

### ISSUE THREAD

**Issue by sarvex** [microsoft/terminal#15174]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.0

### Steps to reproduce

- Open Windows Terminal in non-default Profile such as VS Command Prompt
- Hit <Shift-Alt-+> a new terminal pane is opened on right
- The new split is opened in **Default Profile**
- However if I right click on tab and select "Split Tab" the split pane is opened in the current profile

### Expected Behavior

<Shift-Alt-+> a new terminal pane is opened on right with the **Current Profile**

### Actual Behavior

<Shift-Alt-+> a new terminal pane is opened on right with the **Default Profile**

**Comment by zadjii-msft** [comment]
Yep, the `splitPane` action has another arg for behaving in the duplicating way which the default keybindings don't have. You can add `"splitMode":"duplicate"` to the actions to get that behavior, like so:


```jsonc
{ "command": { "action": "splitPane", "split": "down", "splitMode":"duplicate" }, "keys": "alt+shift+-" },
{ "command": { "action": "splitPane", "split": "right", "splitMode":"duplicate" }, "keys": "alt+shift+plus" },
```

We probably won't be able to change this though, as we've shipped that keybinding without the duplicate for a few years now, and we don't want to break everyone who _does_ like it opening the default profile.

Thanks!

**Comment by sarvex** [comment]
Then a better option will be to add update the default settings.json file. And there is no way a bug fix can break expectations. 

If people love **Default Profile** then the behaviour should be same in the UI menu options as well. Currently there is no way to duplicate **Default Profile** using the mouse. 

A bug is a bug, not a feature in disguise, there will be no love lost for having a consistent behaviour in UI and KeyBindings
