### ISSUE TITLE
Feature Request: Allow users to re-scan for profiles

### ISSUE THREAD

**Issue by beforan** [microsoft/terminal#1518]
# Summary of the new feature/enhancement

Currently when you install/first run (?) the Windows Terminal, it adds profiles for the various shells you have installed (e.g. Command Prompt, Powershell 5, WSL Debian).

If you later install further shells on your system (e.g. Powershell Core (6 or later), Ubuntu or other WSL distros) you have to manually configure profiles for these, even though Terminal is capable of detecting them.

Could there be an item in the profiles/settings dropdown menu to scan for profiles on demand? It would just run the same scan as is currently performed at install/first run.

That way after installing additional shells, it would be one click (or maybe 2 if there was a confirmation dialog of which found profiles to add) to get profiles for them.

**Comment by anon176** [comment]
For now, you can delete the profiles.json file and it will refresh the next time you launch the terminal

**Comment by DHowett-MSFT** [comment]
#1321 #754 #1258 thanks for lpaying!

**Comment by DHowett-MSFT** [comment]
(Sorry to be terse: we have hundreds of new issues, and I'm trying to reduce repository noise. This one is less discoverable than most.)
