### ISSUE TITLE
Tab title text sometimes becomes invisible when using the Light theme

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#15184]
### Windows Terminal version

Commit 72d0566fa6d681291799e59a69168fc0483d8277

### Windows build number

10.0.19045.2728

### Steps to reproduce

1. Build Windows Terminal from a recent commit.
2. Start with all default settings (just to confirm that nothing else is a factor).
3. Switch the application Theme to _Light_.
4. Open a couple of cmd tabs (any shell will probably suffice).
5. Click on the tab titles to switch between the tabs.

### Expected Behavior

The tab title should remain visible when switching tabs.

### Actual Behavior

As soon as the mouse button is released (after clicking on a tab), the tab title becomes invisible, possibly just rendered as black on black.

![image](https://user-images.githubusercontent.com/4181424/232168351-7c39a15e-54dd-4d9d-b7b4-ddba6024d6ca.png)

If you move the mouse, it should become visible again. But if you move the mouse off the tab fast enough, while it's still invisible, it can remain stuck in that invisible state.

Switching focus to another application also seems make the active tab title invisible.

I don't have this issue in the 1.17.1023 preview build.

**Comment by zadjii-msft** [comment]
I can't help but think this is somehow related to #15150. Somehow.

**Comment by zadjii-msft** [comment]
Theory 2: Something fucky with tab colors post 2.8. Maybe a new resource key. Maybe a different order of application of the `.Foreground()` property on the tab.

It does look like
* deselected pointer over: black ✅
* pointer pressed: white ✅
* selected, Pointer over: black ❌
* selected (no pointer over): white ✅

Interesting that this isn't applying to the close button. Interesting.

**Comment by zadjii-msft** [comment]
![](https://user-images.githubusercontent.com/18356694/233431020-f998879d-5a0d-4de4-8d65-75064ecbf830.png)

that ain't right. There's no... Children? for the TabViewItem? That can't possibly be right.
