### ISSUE TITLE
Environment variable references in environment variables are not resolved with wt.exe

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#15191]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Steps to reproduce

* open PowerShell and run the following 2 commands:
```powershell
[Environment]::SetEnvironmentVariable('TEST_VAR1', 'foo', 'User')
[Environment]::SetEnvironmentVariable('TEST_VAR2', '%TEST_VAR1%', 'User')
```
* open Windows Terminal via the start menu and run:
```powershell
echo $Env:TEST_VAR2
```
* open Windows Terminal via `wt.exe` (or `Open in Terminal` in File Explorer, but I assume that's the same thing) and run:
```powershell
echo $Env:TEST_VAR2
```

### Expected Behavior

The result is the same: `foo`.

### Actual Behavior

The result is different: the first time it prints `foo`, the second `%TEST_VAR1%`.

Note there are similar open (#12545) and resolved (#12602, #11777) issues.

**Comment by developerA24** [comment]
The result is different: the first time it.

**Comment by zadjii-msft** [comment]
This does sound a lot like /dup #12602. After #14999, we've made the behavior consistent with the `explorer.exe` launch (the "open Windows Terminal via the start menu" case) always.
