### ISSUE TITLE
Open with Terminal option when inside a Zip on Explorer

### ISSUE THREAD

**Issue by SoulPancake** [microsoft/terminal#15190]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22624.0

### Steps to reproduce

On windows 11
If you open a zip file directly and you're within the folder of the extracted zip via explorer
then on right clicking you get the Open With Terminal option but clicking that doesn't do anything

### Expected Behavior

It should either eliminate the option itself or return an alert or an error 
Or it should somehow trace the directory of the actual temporary folder where it extracts the zip and open that up via the terminal on clicking the option

### Actual Behavior

Clicking on it does nothing but the option remains so it feels like bug

**Comment by jamespack** [comment]
I think this is fairly easy to fix. We can check if an item is both a folder and a stream and if so disable the command.

https://learn.microsoft.com/en-us/windows/win32/shell/sfgao?redirectedfrom=MSDN&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(SHOBJIDL_CORE%252FSFGAO_FILESYSTEM)%3Bk(SFGAO_FILESYSTEM)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue

Happy to PR it.

**Comment by SoulPancake** [comment]
@jamespack This sounds good for me

**Comment by zadjii-msft** [comment]
Yep, we're cool just disabling it in this case. Really seems like this is something that the modern file explorer extensions should have caught for us, but 🤷
