### ISSUE TITLE
Feature Request - Tab renaming

### ISSUE THREAD

**Issue by ppharry** [microsoft/terminal#1519]
# Summary of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by J00MZ** [comment]
Duplicate #608 ?

**Comment by DHowett-MSFT** [comment]
Yes, thanks

**Comment by danield137** [comment]
Not sure why this was closed, #608 talks about naming based on shell type, how about the ability to manually edit a a tab instance? something like iTerm allows? similar to https://superuser.com/questions/292652/change-iterm2-window-and-tab-titles-in-zsh?

**Comment by zadjii-msft** [comment]
Frankly this was closed because it was a totally blank issue. There's no way to know what someone really wants if they don't give us at least a _little_ information.

What you're looking for is #1079.
