### ISSUE TITLE
"Open Terminal here" doesn't show a window on 1.18

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15193]
Probably regressed in #13838, though following up with Leonard on which build he's on specifically. 

On my `dev/lhecker/14957-fix-resize-glitch` current dev build, I can't repro it

**Comment by Window-YANG** [comment]
> Probably regressed in #13838, though following up with Leonard on which build he's on specifically.
> 
> On my `dev/lhecker/14957-fix-resize-glitch` current dev build, I can't repro it

I have another question, please answer it for me if you can：
Why can't I change the display language of the windows terminal compiled with visual studio 2022, even though I have chosen another language and restarted windows terminal, it is still in the same language

**Comment by zadjii-msft** [comment]
I'm not sure the Dev builds of the Terminal have all the localization infrastructure built in. The different translations all come from another service and get stitched in in the actual Release CI, if I recall correctly

**Comment by Window-YANG** [comment]
> I'm not sure the Dev builds of the Terminal have all the localization infrastructure built in. The different translations all come from another service and get stitched in in the actual Release CI, if I recall correctly

Well, it looks like I've learned something new, thanks!
