### ISSUE TITLE
Terminal profile icon not shown in Jump List when icon is from an EXE

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15205]
I provided an EXE for the icon of two of my terminal profiles. It shows correctly in the in-app drop down and in the tabs. However the icon is not displayed in the TaskBar JumpList. See attached image.

![image](https://user-images.githubusercontent.com/18356694/232858917-980b265e-2739-46a5-bc93-311863dc7266.png)

_From MSFT:44188999_

**Comment by jamespack** [comment]
Is this one up for grabs? I think I found a possible solution.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/2086722/233224376-a0234704-637a-499a-8580-adb2401580fb.png">

**Comment by DHowett** [comment]
@jamespack oh heck yeah!

**Comment by jamespack** [comment]
Is this the best place to post some code and ask questions? Or is there a better mechanism?

**Comment by jamespack** [comment]
Ohh. I lied. This is not ready yet.

**Comment by jamespack** [comment]
Ok. Now I think its ready for review. Not sure if your team has a preference for converting strings to signed numbers.
