### ISSUE TITLE
Bug Report : cannot get an back-slash on AZERTY keyboards

### ISSUE THREAD

**Issue by Toreben** [microsoft/terminal#1520]
# Environment

```none
Windows build number: [10.0.18362.175]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Open the new terminal on a french machine, using AZERTY keyboard
Type Alt Gr + 8 to get the back-slash

# Expected behavior

A back-slash should print on the window

# Actual behavior

An underscore prints

**Comment by squasta** [comment]
Same issue on Windows 10 Enterprise build 1903 US (Build 18362.175) + Azerty (French keyboard)

**Comment by LeNouveau** [comment]
Same issue here. 

But it is not only for backslash. 
Almost all Alt-Gr combination is broken.
For example, "~" (Alt-Gr 2) and "@" (Alt-Gr 0) give nothing. 

Windows 10 Pro, v1903, Build 18362.175. 
Keyboard : FRA FR, Azerty

**Comment by odric88** [comment]
Same Issue here.
The ALT+GR key is not reconized

Win10 Enterprise 1903 (18362.175)

**Comment by kbalint** [comment]
Hungarian keyboard - which uses the Alt+Gr is broken. AltGr +V  (@) pastes V in the cmd, and does nothing in bash and powershell. windows 10 build 18362.175

**Comment by cmerkel-eitco** [comment]
Same here on german QWERTZ keyboard.

**Comment by juergsteiger** [comment]
Same on the Swiss German QWERTZ keyboard.

**Comment by Tb0b** [comment]
same in french azerty alt-gr + |

**Comment by erwanh1112** [comment]
Same issue on Windows 10 20H1 insider build 18912.1002. AltGr is simply ignored

**Comment by arnederuwe** [comment]
Same issue on Dutch Belgian (Period) Azerty keyboard, unfortunately this makes the terminal unusable, backslashes are kind of a big deal :)

**Comment by vniklas** [comment]
same on my swedish keyboard

**Comment by silencesys** [comment]
There are some solutions #521

**Comment by DHowett-MSFT** [comment]
Duplicate 521
