### ISSUE TITLE
Fluent background flickering when resizing

### ISSUE THREAD

**Issue by FricoRico** [microsoft/terminal#1521]
# Environment
```
Windows build number: [Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce
In default settings:

~~- Removed `background` key from a profile~~
~~- Add `"useAcrylic": true` to the same profile~~
- Resize window

EDIT: It turns out the window always flashes on resize

# Expected behavior
Expect smooth reflow and resizing of both background and window

# Actual behavior
Smooth reflowing of text works, but the background flashes (becomes invisible), as does the titlebar

**Comment by JushBJJ** [comment]
#1375

**Comment by FricoRico** [comment]
Right I found that it has already been reported in that thread. Thanks!

Link to the report: https://github.com/microsoft/terminal/issues/1375#issuecomment-504638912

**Comment by DHowett-MSFT** [comment]
Thanks!
