### ISSUE TITLE
Settings Actions list is not showing quake mode activation key correctly.

### ISSUE THREAD

**Issue by alienBear** [microsoft/terminal#15214]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Other Software

N/A

### Steps to reproduce

Open Settings>Actions and look at the activation key for Show/Hide Quake mode.  It shows `Win + sc(41)` instead of ``Win + ` ``.
![image](https://user-images.githubusercontent.com/54277839/233422747-6f0e46a9-ed6d-456f-9fba-4b88d2ce1c98.png)

### Expected Behavior

Key combination should be rendered as the backtick character instead of sc(41).

### Actual Behavior

Backtick key shows as sc(41) in the Actions as shown on the attached screenshot.

**Comment by carlos-zamora** [comment]
Thanks for filing this! We're going to mark this as a /dup of #12123.
