### ISSUE TITLE
Ability to drag tabs out and move them to a new instance

### ISSUE THREAD

**Issue by sur1v** [microsoft/terminal#15227]
Hey thanks for this product, I'm enjoying it a lot. Below affirmations based on version 1.16.10262.0.

# Description of the new feature/enhancement

I would like to suggest the addition of a new feature in Windows Terminal that would allow users to drag a terminal tab out of the main instance and create a new one, similar to how we do it in web browsers. This feature would be very useful for users who want to compare two terminals side by side.

Currently, it is only possible to reorder tabs within the same Windows Terminal instance. By implementing a new right-click context menu option, such as 'Move tab to new window', users would have the ability to easily create new instances and compare multiple terminals at the same time.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256

It's also done, and shipping in 1.18, which is coming out once we sort out the last blocking issues (in #14957)
