### ISSUE TITLE
Browsing for icon crashes Terminal

### ISSUE THREAD

**Issue by Real-Luke-James** [microsoft/terminal#15226]
### Windows Terminal version

1.17.1023.0

### Windows build number

10.0.23440.1000

### Other Software

None

### Steps to reproduce

Open Settings
Click any profile
Click Icon
Click Browse

### Expected Behavior

An explorer window should open with the option to select images.

### Actual Behavior

Terminal Crashes.

**Comment by j4james** [comment]
Thanks for the report, but this is already being tracked in issue #14808. There is a fix in PR #14816, but that has not been released yet.
