### ISSUE TITLE
Italic characters stripped down in neovim (other terminals do not have this issue)

### ISSUE THREAD

**Issue by gwjulian** [microsoft/terminal#15246]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19044.0

### Other Software

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Steps to reproduce

With Cascadia code or Recursive type mono open a neovim session with an italic-support theme/colorscheme

### Expected Behavior

Italic characters should not be stripped or shown incomplete

### Actual Behavior

Italic letters are cut/stripped or 
![image](https://user-images.githubusercontent.com/102186778/234736718-0a1da451-b59c-4930-bf41-165ea760bd06.png)

**Comment by gwjulian** [comment]
@zadjii-msft I still see text being cut despite changing text aliasing like the dup suggest.
But, I don't know, do I need to update my terminal? or rather wait for the update to come?
thanks by the way

**Comment by lhecker** [comment]
You'll likely have to wait for the update to be released. It'll first ship in Windows Terminal Preview 1.18. We are nearing a release, but we don't have an exact release timeline yet, because 1.18 will contain a massive overhaul of a lot of fundamental components (the entire UI setup to facilitate tab tear-out & text rendering being rewritten from scratch).

**Comment by lhecker** [comment]
> With Cascadia code or Recursive type mono open a neovim session with an italic-support theme/colorscheme

Although I should mention that both you and #9381 are wrong about this, if I may be so frank. 😅 Yes, the issue does happen for Recursive Mono and FiraCode, but it will not happen for Cascadia Code. Unless you forgot to install its italic variant. This is how Cascadia Code with the proper italic variant looks like in 1.16.10262.0, for reference:
![image](https://user-images.githubusercontent.com/2256941/234860979-b9c9b50d-3b0d-41ef-b12c-e54008130255.png)

**Comment by gwjulian** [comment]
@lhecker I actually prefer using Recursive Duotone (for the mix of casual and semicasual styles), but Deludia seems to be good, I'm gonna be trying it out.
Thanks again!
