### ISSUE TITLE
Drag problem

### ISSUE THREAD

**Issue by amm-uit-2017** [microsoft/terminal#1524]
Dragging should be efficient in anywhere in the menu bar like all other text editors. The tab window should be dragged out to create a new window.

**Comment by yuri-wisestamp** [comment]
Experiencing this as well. Not cool.

**Comment by HBelusca** [comment]
Duplicate of #1516, #1500, #1412, #1395 ; issue encompassed in #1375.

**Comment by DHowett-MSFT** [comment]
That's right. Thanks @HBelusca!
