### ISSUE TITLE
Browsing for profile icon crashes application

### ISSUE THREAD

**Issue by ashemedai** [microsoft/terminal#15247]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Start Windows Terminal
2. Click `Settings` from the drop-down menu
3. Select a profile
4. Go to `Icon`
5. Click `Browse`
6. Observe crash

### Expected Behavior

After clicking Browse a file explorer should appear.

### Actual Behavior

Windows Terminal crashes the moment `Browse` is clicked.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #14808 for more discussion.

/dup #14808
