### ISSUE TITLE
Subset of Ligatures not working when using Powershell

### ISSUE THREAD

**Issue by LoZeno** [microsoft/terminal#1525]
Some ligatures don't work when using Powershell or Powershell 6, they do work correctly when using WSL Ubuntu instead.

# Environment
Microsoft Windows 10
```none
Windows build number: [run "ver" at a command prompt]
[Version 10.0.18362.175]
Windows Terminal version (if applicable):
0.2.1715.0
Any other software?
Fira Code fonts
```

# Steps to reproduce
Start Windows Terminal with a Powershell prompt;
type this sequence of characters:
<= <> >= != => <==  

Open a tab with WSL Ubuntu, and type the same sequence of characters:
<= <> >= != => <==  

# Expected behavior

all the ligatures should work the same way in powershell and WSL ubuntu .

# Actual behavior
In the powershell tab, the ligatures of <= and >= do not work, the rest does.
![image](https://user-images.githubusercontent.com/3267561/60011640-1f796b80-9672-11e9-9d9b-30b2e9f6a3d5.png)

In the WSL Ubuntu tab, all the ligatures work
![image](https://user-images.githubusercontent.com/3267561/60011661-31f3a500-9672-11e9-862e-bce795d97464.png)

**Comment by DHowett-MSFT** [comment]
Ligature runs are split in half when the color changes in the middle, which is what powershell is doing. How would you propose this be fixed? The behavior here seems correct.
