### ISSUE TITLE
Inconsistent language selection in SUI

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#15260]
### Windows Terminal version

main fc90045c

### Windows build number

10.0.19045.2486

### Steps to reproduce

Build latest terminal
Open SUI and select Language

### Actual Behavior

![wt_language_selection](https://user-images.githubusercontent.com/3933920/235217628-b450ef56-da12-4bea-8dba-38c0acdc415b.png)

**Comment by DHowett** [comment]
Thanks for the report! These are the names officially reported by the Windows Globalization APIs. I will raise your concern with them, but there isn't much we can do about it on the Terminal side so I'll mark this as Closed/External :)
