### ISSUE TITLE
Settings documentation

### ISSUE THREAD

**Issue by yuri-wisestamp** [microsoft/terminal#1526]
Could not find documentation for the settings json. Either non existent or hard to find.

**Comment by mwiora** [comment]
1+

**Comment by mcpiroman** [comment]
It's at [/doc/cascadia/SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md), but should be more visible.

**Comment by DHowett-MSFT** [comment]
@mwiora don't add comments that just say +1. please use the "reactions" feature, ![image](https://user-images.githubusercontent.com/14316954/60036094-3cf30900-9663-11e9-9366-cd5823785a82.png), which adds voting buttons: ![image](https://user-images.githubusercontent.com/14316954/60036103-42e8ea00-9663-11e9-9579-6246aa874588.png)

Also, the docs will be improving -- especially once we have an actual settings UI. I'm going to consolidate all of the "settings docs" and "settings UI" bugs.
