### ISSUE TITLE
Windows Terminal and Windows Terminal Preview will restart all the time when enable "Run as the Administrator"

### ISSUE THREAD

**Issue by klyjm** [microsoft/terminal#15275]
### Windows Terminal version

1.16.10261.0 & 1.17.10234.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Set the "Run as Adiministrator" in setting
2. Restart the app.

### Expected Behavior

It should run without restart and can be run as administrator.

### Actual Behavior

When I run as administrator by right button, it is no different with not. When I set the option in setting that "Run as the Administrator", the app wil restart all the time without stop untill I uninstall it. It is same for the Windows Terminal or Windows Terminal Preview.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13928 for more discussion.

/dup #13928
