### ISSUE TITLE
Allow word selection across lines

### ISSUE THREAD

**Issue by simonleary-umass-edu** [microsoft/terminal#15272]
When I double click a word in my terminal, it selects a word based on the `wordDelimiters` config option. If the word I want to select happens to occur on the right edge of my terminal, it will get wrapped onto the next line and now I can't select it with a double click. I thought I would find `\n` or `\r\n` in `wordDelimiters`, but it's not. It seems that there are other word delimiters hard-coded under the hood which cannot be configured.

Can this become configurable?

My workaround is to set ctrl+shift+c to copy as "singleLine", but I still have to manually click and drag.
```json
{
    [
        {
            "command":
            {
                "action": "copy",
                "singleLine": true
            },
            "keys": "ctrl+shift+c"
        },
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4009 for more discussion.

/dup #4009
