### ISSUE TITLE
Unbind all default shortcuts

### ISSUE THREAD

**Issue by KMPrg** [microsoft/terminal#15277]
# Description of the new feature/enhancement
Provides settings for unbinding all default shortcuts at once

Windows terminal is good software,
but it has too many keyboard shortcuts by default,
when using an editor like VIM, there are a lot of shortcut key conflicts,
want to give the user custom keyboard options, so there will not be a lot of inexplicable keyboard shortcuts conflict.
# Proposed technical implementation details (optional)

In setting. JSON file, provide a set of all the default keyboard shortcuts can be disabled at one time, 
so that users can easily customize the keyboard shortcuts, the need to manually configure their own keyboard shortcuts, 
avoid confusing keyboard shortcuts

**Comment by zadjii-msft** [comment]
I think our plan has been to add support for "keymaps". This would follow the work for #6899. Then, `keymaps` would contain objects which bind keys to various actions. The user could then just specify `keymap: "foo"` to replace _all_ their `keybindings` with the ones in `foo`, no layering involved. Adding keys to actions directly would just update the "default" keymap, which is used when no `keymap` is specified. Unbinding everything would be something like `"keymap": null`

I think for tracking purposes, it's best to just merge this with that thread. Thanks!

/dup #2205

**Comment by KMPrg** [comment]
@zadjii-msft   @microsoft-github-policy-service
Thank you very much for your answers. I carefully read the issue you provided and #3483 .
I think I may have misunderstood, the main problem does not seem to be the keybindings, but something more complex.

For example, the behavior of ctrl+., even if I use unbund or null to unbind in .json, it will still play the role of moving the cursor to the next line in vim or Emacs. I am sure I have not set this shortcut key, and If you don't use vim or Emacs in the Windows terminal, you don't have these weird default keybindings.

**Comment by hvesalai** [comment]
Having the same problem. Just installed Ubuntu-22 and I use emacs.

I would need to have a way to remove all WIndows Terminal bindings so that emacs would receive the keycodes. I don't need much from Windows Terminal, so I'm happy not having any bindings for it. For me it is important that all keycodes go through.
