### ISSUE TITLE
Background image for terminal

### ISSUE THREAD

**Issue by TitanRtx** [microsoft/terminal#1528]
# Summary of the new feature/enhancement
Hi , i like watching animic , so if i can put my favorite animic person as background image ,it's good.

# Proposed technical implementation details (optional)

**Comment by JushBJJ** [comment]
In profiles.json, you can have either a image or a gif in your profile.
For example: `"backgroundImage" : "https://media.giphy.com/media/TZf4ZyXb0lXXi/giphy.gif",`
But for this to show, you must disable the acrylic.

**Comment by DHowett-MSFT** [comment]
This has been answered. Thanks!

**Comment by TitanRtx** [comment]
oh,amazing ! haha , now i can use my image as the bgimage , thanks !
