### ISSUE TITLE
closing for no reason

### ISSUE THREAD

**Issue by JesusTouchMe** [microsoft/terminal#15284]
### Windows Terminal version

1.16.10261.0

### Windows build number

Version 10.0.19045.2846

### Steps to reproduce

When the terminal window is in focus, click it in the task bar and it fully closes

### Expected Behavior

The window will get minimized

### Actual Behavior

The window closes

**Comment by zadjii-msft** [comment]
Is it still running in task manager? or did it actually crash/? My theory is that it's just minimizing to the tray icon.

Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)? 

If it's not still running, and the terminal _is_ crashing, mind submitting feedback with Feedback hub?

/feedback

**Comment by JesusTouchMe** [comment]
> Is it still running in task manager? or did it actually crash/? My theory is that it's just minimizing to the tray icon.
> 
> Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?
> 
> If it's not still running, and the terminal _is_ crashing, mind submitting feedback with Feedback hub?
> 
> /feedback

Turns out that it was just minimizing to the tray icon. I noticed the setting `minimizeToNotificationArea` in the settings file was set to true. Thanks for the help!
