### ISSUE TITLE
Suspicious German translation in tray icon context menu

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#15289]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045 Build 19045

### Steps to reproduce

Right-click the tray icon

### Actual Behavior

In German localization the first entry is "Fokusterminal".
This means "[the] focus terminal".
I guess it should be the imperative "[do] focus [the] terminal", so it should probably be "Terminal fokussieren".
It still sounds a bit bulky in German, but at least is the probably intended imperative.
Maybe some fellow German can even come up with something nicer.
"Terminal in den Vordergrund bringen" is probably most correct, just a bit lenghty. :-/

**Comment by lhecker** [comment]
I'm sorry for the long wait! This is now tracked at MSFT-44562118.
