### ISSUE TITLE
Support other url protocols or patterns for clickable links

### ISSUE THREAD

**Issue by alexlehm** [microsoft/terminal#15299]
# Description of the new feature/enhancement

I would like to be able to have clickable links for gopher or gemini links, maybe also for xmpp links in the terminal text

# Proposed technical implementation details (optional)

The pattern what links are clickable currently matches http and https links and is hardcoded into the code, it would be better if this were settable in the json file so that one can define other url patterns to be matched.

**Comment by zadjii-msft** [comment]
Hey wadda ya know, we did this in #14993. 

/dupe #7562
