### ISSUE TITLE
Windows Terminal closes several seconds after opening

### ISSUE THREAD

**Issue by MrR0bert** [microsoft/terminal#1529]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
Any other software? No

# Steps to reproduce
Install preview from store and start app

# Expected behavior
I would expect Windows Terminal to just start

# Actual behavior
A transparent and titleless window opens for a few seconds and closes again:
![afbeelding](https://user-images.githubusercontent.com/20636874/60015657-48a2f780-9684-11e9-87a2-27633e595998.png)

The error event that is generated shows:
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1906.20005, time stamp: 0x5d0c1459
Faulting module name: ucrtbase.dll, version: 10.0.18362.1, time stamp: 0x5cbddb81
Exception code: 0xc0000409
Fault offset: 0x000000000006d3be
Faulting process id: 0x3174
Faulting application start time: 0x01d52a80889ca60a
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 2673831f-2b82-417b-bffe-1e1bac2732be
Faulting package full name: Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment]
#1364
