### ISSUE TITLE
Opening a second powershell and immediately closing it crashes terminal 

### ISSUE THREAD

**Issue by riskysciolism** [microsoft/terminal#1530]
# Environment

```none
Windows build number: Version 10.0.18362.175
Terminal Version: 0.2.1715.0
```

# Steps to reproduce

Open Windows Terminal which defaults to an open tab with powershell.
Open a second tab with powershell, and immediately close it.
Terminal crashes/freezes.

# Expected behavior

The recently opened tab simply closes

# Actual behavior

Tab and the complete Terminal freezes. Need to ALT + Ctrl + Delete.

**Comment by mcpiroman** [comment]
I had similar issue when I set `"commandline" : "powershell -c dir"` (which caused terminal to run `dir` and then close), but after a while it stoped crashing..

**Comment by JushBJJ** [comment]
That seems like an issue within the terminal itself depending on how fast your computer is. But the issue really is visible when you open powershell.

**Comment by DHowett-MSFT** [comment]
Probably the same as #1445
