### ISSUE TITLE
Opening command palette from new tab dropdown dismisses immediately

### ISSUE THREAD

**Issue by ianjoneill** [microsoft/terminal#15305]
### Windows Terminal version

main 10c6206

### Windows build number

10.0.22621.1555

### Steps to reproduce

1. Open terminal
2. Click new tab dropdown
3. Select Command Palette

### Expected Behavior

The command palette opens and is usable.

### Actual Behavior

The command palette opens and then disappears. Opening the command palette via the keyboard shortcut works fine.

https://user-images.githubusercontent.com/5821575/236624660-9ac34063-5d99-4faf-85c0-880fd6adc2d5.mp4

**Comment by zadjii-msft** [comment]
psychic debug: was #15077
