### ISSUE TITLE
Something happened on our end. Here’s the error code, in case you need it: 0x87E10BC6

### ISSUE THREAD

**Issue by edgardojs** [microsoft/terminal#15304]
When I try to open the app I get this error

**Comment by j4james** [comment]
If you're doing an offline install on a machine that isn't connected to the internet, or blocked from the Microsoft Store, I think you'll need to use the preinstall kit as described in issue #9009.

**Comment by zadjii-msft** [comment]
Yea, i think we're gonna need some additional context on how you got into that state. Cause that error code is... nonsense

-- | -- | -- | -- | --
-- | -- | -- | -- | --
0x87e10bc6 | -2015294522 | LM_E_CONTENT_NOT_IN_CATALOG | N/A | durangolicensemanagererrors.h
0x87e10bc6 | -2015294522 | LM_E_SATISFACTION_CONTENTIDNOTINCATALOG | The requested content id could not be found in the catalog. | licensemanagererrors.h
0xbc6 | 3014 | ERROR_PRINTER_DRIVER_BLOCKED | The printer driver is known to harm the system. | winerror.h
0xbc6 | 3014 | SQL_3014_severity_10 | %hs successfully processed %d pages in %d.%03d seconds (%d.%03d MB/sec). | sql_err
0xbc6 | 3014 | FssHttpInvalidSerialiation14 |   | Error.cs
0xbc6 | 3014 | AG_E_NO_SAMPLE_TIMESTAMP | N/A | xcperrorresource.h
