### ISSUE TITLE
AltGr not working on linux terminal ubuntu18.04

### ISSUE THREAD

**Issue by melihhsarica** [microsoft/terminal#1531]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): windows terminal (Preview) 0.2.1715.0

Any other software?
```

# Steps to reproduce
Create a Ubuntu 18 tab
type $ or any sign that can be created with AltGr 

# Expected behavior

we must see $ sign with AltGr+4 

# Actual behavior

nothing happens

**Comment by AlexanderViken** [comment]
The same happens in PowerShell tabs

**Comment by matswi** [comment]
Same behavior in all tabs (Pwsh, Powershell, Cmd and Ubuntu) with Swedish keyboard layout.
Valid for all characters that need "Alt Gr"

**Comment by silencesys** [comment]
Seems to me like duplicate of #521
