### ISSUE TITLE
Tab titles (specified via command line arguments) are lost 

### ISSUE THREAD

**Issue by reaching-for-libra** [microsoft/terminal#15316]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19044.0

### Steps to reproduce

Not entirely sure which actions are relevant, and i have a hard time reproducing with explicit actions, so i'll outline my flow

- Plug laptop into dock
- Start windows terminal (pwsh profile). (suppressApplicationTitle  is set to "true" in the settings.json file)
- Launch new tab(s) in a new window, specifying titles for tabs

`wt.exe -w 2 --title 6000 -p cmd cmd /c "cd \"c:\projectdirectory\" &\"C:\Program Files\dotnet\dotnet.exe\" run --urls \"http://*:6000\" &pause"`

- Some time later, unplug laptop from dock and close
- Take laptop elsewhere (some amount of commute time), and plug into new dock. 
- Most likely, wait until the following day before opening the laptop again

### Expected Behavior

Tab titles should be retained

### Actual Behavior

Tab titles revert to the command. In the example, tab title changes to "cmd"

**Comment by zadjii-msft** [comment]
_note to self_: this isn't just the "language change causes runtime settings to be lost" issue. I think there's some other issue floating around for "a settings update causes commandline settings to be lost". Probably something about NewTerminalArgs. 

I'll need to go dedupe later.

**Comment by zadjii-msft** [comment]
I'm pretty sure this is ultimately #5047. Really hard to tell just by reading, but that's my read of the situation. Thanks for a more concrete example!

/dup #5047
