### ISSUE TITLE
ls: cannot read symbolic link (on windows folders)

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/terminal#1532]
![Capturar001](https://user-images.githubusercontent.com/13587928/60017950-59417680-9660-11e9-98f3-ba5bc3cb3b5f.PNG)

# Environment

 ```
Windows build number: 1903 build 18362.175
Windows Terminal version 0.2.1715.0
Debian GNU/Linux through wsl version: 1.16.0
```

# Steps to reproduce
Enter in windows terminal open debian environment go to my folder in `/mnt/c/Users/ulc` type `ls`.

# Expected behavior
have access to my folders.

# Actual behavior
without access to my folder.

**Comment by JushBJJ** [comment]
I had this issue as well, just type in `sudo ls`

**Comment by DHowett-MSFT** [comment]
Please report this on the WSL repository. This is not the WSL repository.
