### ISSUE TITLE
Bad german translation for "Switch selection marker"

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#15322]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045 Build 19045

### Steps to reproduce

Open the command palette and search for "Switchauswahlendpunkt"

### Expected Behavior

"Switch selection marker" should be translated better, for example as "Auswahlendpunkt wechseln"

### Actual Behavior

"Switch selection marker" is translated as "Switchauswahlendpunkt"

**Comment by lhecker** [comment]
I also put this into MSFT-44562118.

**Comment by DHowett** [comment]
It looks like this was fixed in #17767! Thanks!
