### ISSUE TITLE
Shortcut to adjust background opacity level

### ISSUE THREAD

**Issue by u84six** [microsoft/terminal#15331]
Many times when I need to type something in the terminal, I need information from another window, so I find myself switching windows and then typing, over and over. What I would like is a way to adjust the background opacity of the Terminal window so that I can see through it while I type. I know there's a way to adjust this in settings, but it's more of a static solution. What I'd like is something similar to the cmd prompt where you can adjust on the fly like holding down a key combo and then using the mouse wheel or +/- keys. This way will allow me to set it when I need to, and then go back to full opacity when I'm done. I'm not sure if this can happen for all types of command prompts (powershell, gitbash, cmd, etc) in Terminal, but it would great if you could figure it out :)

The implementation for cmd isn't very good because it doesn't just do the background, it also does the foreground, so it can be tough to see the text I'm typing. It would be ideal for the settings to just affect the background

**Comment by DHowett** [comment]
If you hold down <kbd>Ctrl</kbd> and <kbd>Shift</kbd>, you should be able to "scroll" the opacity up and down with the mouse wheel or trackpad!

**Comment by DHowett** [comment]
FWIW, it looks like this when it's working.

![WindowsTerminal_Ao2LSWVC4B](https://github.com/microsoft/terminal/assets/189190/088c914a-e207-4053-aeea-c8fd525478b5)

**Comment by zadjii-msft** [comment]
You can also use the `setOpacity` action:

![ed1825ed-354f-4958-8327-bfd5a9f0bf4c](https://github.com/microsoft/terminal/assets/18356694/47a2ea1b-888a-484f-aedf-e8aac41564f4)

**Comment by u84six** [comment]
> If you hold down Ctrl and Shift, you should be able to "scroll" the opacity up and down with the mouse wheel or trackpad!

Thanks for the demo! I was using a trackpad but it wasn't setup correctly so couldn't adjust it. This is working now. Thanks again
