### ISSUE TITLE
Hang while switching between tabs

### ISSUE THREAD

**Issue by effolkronium** [microsoft/terminal#1533]
Dump was sent to
secure@microsoft.com
# Environment

Windows 10 pro 1903 (x64)

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version 0.2.1715.0

Any other software? chrome
```

# Steps to reproduce

frequently switching between two tabs by alt+NUMBER

# Expected behavior

Hang not occur

# Actual behavior
Hang occurs (and does not end)

**Comment by miniksa** [comment]
I'm not able to reproduce this issue and we don't seem to have the dump on the back-end.

Can you share it with me another way? Or if it's an actual crash, can you get the Windows Error Reporting information from the Event Viewer so I can try to find it on the backend?

**Comment by miniksa** [comment]
You might also be able to use Feedback Hub to submit the dump that way and it would come to us...
