### ISSUE TITLE
Per-user fonts don't load

### ISSUE THREAD

**Issue by ostrich** [microsoft/terminal#15344]
### Windows Terminal version

1.16.10262.0, 1.17.1023 (Preview)

### Windows build number

10.0.22621.0

### Other Software

[CaskaydiaCove Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode)
[SF Mono Nerd Font](https://github.com/epk/SF-Mono-Nerd-Font)

### Steps to reproduce

1. Install a font on a per-user basis (not system-wide)
2. In Windows Terminal, navigate to Settings, Profiles, Defaults, Appearance, select a per-user font, click Save
3. Different behaviors depending on application version, but neither works
    - Windows Terminal stable will not load the font at all
        - ![image](https://github.com/microsoft/terminal/assets/570911/f545e319-b22e-4dd8-99b3-7a8d425ab559)
    - Windows Terminal Preview loads the font to the current session but upon closing and reopening Terminal, the same message as above is displayed

Notes:
1. Windows Terminal handles fonts correctly when they are installed system-wide.
2. The fonts I used for this test work correctly in other applications. 

### Expected Behavior

Windows Terminal should load the selected font to the current session and continue to load it in new sessions.

### Actual Behavior

Windows Terminal stable is unable to load per-user fonts at all. Windows Terminal Preview can load them to the current session but not to subsequent sessions.

**Comment by j4james** [comment]
I believe this issue is being tracked in #3257, although I think it's an OS problem, so it'll likely be fixed by an OS update.

**Comment by lhecker** [comment]
Thanks for the report! @j4james is absolutely right. This is a known issue with installing fonts into the user font directory. It's a bug that's unfortunately outside of our control and we're all patiently waiting for a fix for this as well. It's one of the most common bug reports we get. Here's how you fix it: https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973

/dup #3257

**Comment by ostrich** [comment]
> Thanks for the report! @j4james is absolutely right. This is a known issue with installing fonts into the user font directory. It's a bug that's unfortunately outside of our control and we're all patiently waiting for a fix for this as well. It's one of the most common bug reports we get. Here's how you fix it: [#14231 (comment)](https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973)
> 
> /dup #3257

Thanks. I figured it was already reported and tried searching but didn't come up with anything.
