### ISSUE TITLE
Terminal settings sync with an email account

### ISSUE THREAD

**Issue by iamkartiknayak** [microsoft/terminal#15342]
# Description of the new feature/enhancement

Ability to sync settings when connected to a mail account would be handy. It could be the account windows account used while install by home users or a custom email to be used by a windows pro user. Options to keep local or remote settings each time user makes changes to default settings of terminal and then sync the settings.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
