### ISSUE TITLE
Feature Request: black terminal window

### ISSUE THREAD

**Issue by Rictava** [microsoft/terminal#1534]
Having the possibility of switching the color scheme of the terminal window itself from white to black.

![image](https://user-images.githubusercontent.com/33431325/60023907-ac322280-968e-11e9-83ea-85191a738767.png)

**Comment by JushBJJ** [comment]
#1375 
If this is showing when the terminal is selected, you can change the color of the titlebars in settings.
`Settings -> Personalization ->  Colors`

**Comment by Rictava** [comment]
> #1375
> If the white titlebar shows up when the terminal is selected, you can change the color of the titlebars in settings.
> Settings -> Personalization ->  Colors

Question here is that I am already using Dark theme in Windows 10, so title bar should be already black I believe.
![image](https://user-images.githubusercontent.com/33431325/60025372-63c83400-9691-11e9-8962-0ce41397fa34.png)

**Comment by JushBJJ** [comment]
Not really the case...
![image](https://user-images.githubusercontent.com/36951064/60026200-803e8d80-96de-11e9-8b1d-0581960364a4.png)
![image](https://user-images.githubusercontent.com/36951064/60026225-8a608c00-96de-11e9-99d9-9af3a9f52b32.png)

**Comment by alefranz** [comment]
However when the window loose focus (or always If you don't check the "title bars and windows borders" option) the title bar and border are white when using a dark theme, instead or dark grey (like explorer for example)
![image](https://user-images.githubusercontent.com/348793/60039101-d6dfa380-96ad-11e9-9018-045e2b33e2f1.png)

**Comment by DHowett-MSFT** [comment]
This will be fixed by #872 #929
