### ISSUE TITLE
Bug Report - Malicious activity detected - Windows process wrong location

### ISSUE THREAD

**Issue by cypherstream** [microsoft/terminal#1535]
After installind and runnign the Microsoft Terminal Preview, Dell Secureworks opened a ticket with the following informaiton below.  Is this safe to run?

We've observed potentially malicious activity, Windows process wrong location, (process: conhost.exe, process MD5: 7a8c227929a1047e2120422da75d231b) for user (redacted) on host (redacted). The detection was performed by SecureWorks CTU threat indicators and we are escalating this activity to you based on our default event handling policies.

Process Name: conhost.exe
Process MD5: 7a8c227929a1047e2120422da75d231b
Command Line: conhost.exe --headless --width 120 --height 30 --signal 0x840 -- powershell.exe
Parent Process Name: windowsterminal.exe
Process Start Time: 2019-06-24T13:51:34.357Z
Last Process Activity Time: 2019-06-24T13:53:06.034Z

----------------------------------------------
Threat Intel Feed Information
----------------------------------------------
Threat Intel Feed Report: Windows process wrong location
Threat Intel Feed Update Time: 2018-09-30T22:43:59.000Z
Classification: opportunistic trojan
Description: A process with a common Windows process name was identified running from a non-standard location on the system. This is considered unusual behavior because a process by this name is expected to be run from the %system% directory. It is common for malware to use the same name as legitimate Windows processes in an attempt to blend in when running processes are inspected.

Examples:
> c:\windows\csrss.exe
> %temp%\lsass.exe

Targeted threat actors may also use this technique to hide their malware on the compromised system.

**Comment by DHowett-MSFT** [comment]
Dell Secureworks is too trigger-happy here. We have an executable named `conhost.exe`, which SecureWorks has detected as being a system application _based on name alone_. That's never going to be a winning strategy.
