### ISSUE TITLE
Custom build show `An update is available` when selecting `About`

### ISSUE THREAD

**Issue by zcobol** [microsoft/terminal#15350]
### Windows Terminal version

main 3d737214

### Windows build number

10.0.22621.1702

### Steps to reproduce

Build latest code, 3d737214 was used for testing on aarch64.
Select `About` from drop-down menu
Observe the blue rotating circle and  `Checking for updates...` message

### Expected Behavior

No updates available since it's a local build

### Actual Behavior

![wtd_update_available](https://github.com/microsoft/terminal/assets/104515072/e6e2ef1f-eff4-4c7d-8756-1b53d3eeea49)

**Comment by zadjii-msft** [comment]
Thanks for helping selfhost the latest bits! That's actually a debugging string that we put in there. Obviously, there aren't any updates available from the Store for a Dev build of the Terminal. The About dialog will still display that message though, as a bit of a debugging test for that UX. 

You can safely ignore that message 😉
