### ISSUE TITLE
Opening quakeMode via shortcut/touchpad gesture messes with input / caps lock stuck

### ISSUE THREAD

**Issue by jonaskuske** [microsoft/terminal#15356]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Map 4-finger tap to `ctrl+shift+alt+t` in Windows Settings
2. Map `ctrl+shift+alt+t` to action `quakeMode` in Terminal settings
3. Open and close quake window using 4 finger taps

Happens to me both with PowerShell and WSL+zsh, so I don't think it's shell related. I'm using the oh-my-posh prompt in both though, so that is something both shells have in common

### Expected Behavior

Opening or closing the window should not change input behavior

### Actual Behavior

Sometimes after opening the quakeMode window using a 4-finger tap, I can only input uppercase letters (and pressing the capslock key changes nothing). The behavior of arrow keys is changed, too. The input behavior is stuck and the Terminal basically unusable.

Then, I have to open and close the window a few times using the 4-finger tap until suddenly the input behavior is normal again, seemingly randomly. I haven't found another way to switch to normal input behavior again, leading to a weird open-close dance every time this happens.

I've not yet tried if the same happens with out the touchpad gesture, just using the shortcut. Will update later.

**Comment by carlos-zamora** [comment]
Hi @jonaskuske! Thanks for the report. We have a few questions for you:
- If you individually tap shift, ctrl, and alt, does this issue fix itself?
- Does it work for other actions that aren't `globalSummon` or `quakeMode`?
- Does this issue repro if you bound the gesture to something like the "underline" hotkey in MS Word?

**Comment by jonaskuske** [comment]
> If you individually tap shift, ctrl, and alt, does this issue fix itself?

No, had no success with this

> Does it work for other actions that aren't `globalSummon` or `quakeMode`?

Will try and report back :)

> Does this issue repro if you bound the gesture to something like the "underline" hotkey in MS Word?

How can I do that? Or do you mean just mapping 4-finger tap to `Ctrl+U`?

**Comment by carlos-zamora** [comment]
> ...do you mean just mapping 4-finger tap to `Ctrl+U`?
Yup! Exactly that
