### ISSUE TITLE
Nerd font icons with 5 digit hex codes are not displayed correctly

### ISSUE THREAD

**Issue by bmo-at** [microsoft/terminal#15369]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.0

### Other Software

fish 3.6 on WSL2 ArchLinux
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

### Steps to reproduce

1. Install the latest version of nerdfonts (any will do, I prefer CaskaydiaCove Nerd Font), at least 3.0.0.
2. Install windows terminal, wsl2 and fish as well as fisher and tide (The following instructions are for Ubuntu 22.04)
  - download fish 3.6 `wget https://launchpad.net/~fish-shell/+archive/ubuntu/release-3/+files/fish_3.6.1-1~jammy_amd64.deb && sudo dpkg --install fish_3.6.1-1~jammy_amd64.deb`
  - start fish `fish`
  - install fisher `curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher`
  - install tide `fisher install IlanCosman/tide@v5`
  - configure the prompt with:
     3 1 3 1 1 1 2 1 1 1 2 y 
  - set the icon for a segment, e.g. the time, to an offending 5 digit code icon, e.g. 󰁹 (f0079) (https://www.nerdfonts.com/cheat-sheet, search for nf-md-battery): `set --universal tide_time_format "󰁹 %r"`

### Expected Behavior

The prompt should look like before, except there should be a battery icon in front of the time.

### Actual Behavior

The battery icon still shows up, but the prompt has an additional newline character and sometimes the previous prompt doesn't clear out. This happens both on wsl and with openssh for windows when connected to a linux server running this set up.

Previously, this did not happen when the nerdfonts used 4 digit codes for the nf-md-* symbols. My assumption is, that the 5 digit codes are somehow messing with the terminal.
But this also occurs when using alacritty or any other terminal on windows.
Or as said before, using openssh to access a linux machine.

This does not occure when using nerd fonts natively in powershell on windows or bash/zsh/fish on linux.
It seems to be related to running a linux shell on windows.

**Comment by bmo-at** [comment]
I also opened an issue on the nerdfonts repo with some screenshots from my setup:
https://github.com/ryanoasis/nerd-fonts/issues/1246

**Comment by carlos-zamora** [comment]
Thanks for the report! We think this should be fixed with 1.18 (coming soon!). If not, /dup #8000
