### ISSUE TITLE
Repo can't build in a directory with a space

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15370]
> Reverted all changes to OpenConsole.sln by removing and recloning the project.
> 
> Picked: ![image](https://user-images.githubusercontent.com/15957528/237941072-ca89bc94-5d40-44a2-90ec-b8788920fa89.png)
> 
> Restored and updated submodules `git submodule update --init --recursive`
> 
> Ignored warning about incorrect configurations. In the Debug menu, I changed "Application process" and "Background task process" to "Native Only".
> 
> Build it, had an issue with nuget packages:
> 
> ![Nuget Package Restore 2023-05-12 114632](https://user-images.githubusercontent.com/15957528/237942452-bb571cc4-d0e2-4dc8-af4f-a2bdbaa517f3.png)
> 
> Solved that by building with Powershell. This installed the packages, but this time build ended with errors. Afterwards I deleted the Obj and Bin folder of the project and build it with visual studio, getting the same erros as before, but getting similar errors with PowerShell now as well:
> 
> ![Same Errors ](https://user-images.githubusercontent.com/15957528/237943674-756c0f6f-9c8f-4a97-a0cb-4a8826c9b832.png)
> 
> ![image](https://user-images.githubusercontent.com/15957528/237947321-86c86eb9-a103-4084-8717-b56e4724855f.png)
> 
> ![image](https://user-images.githubusercontent.com/15957528/237948278-181aca8a-fd23-40a9-b211-b2b3726711a4.png)

Btw, the software not being able to be build when someone has a username that contains a space.  This may be a new issue? If so, I could make a new issue for it. 
Can't help but being bugged by not having the project in my preferable location.

_Originally posted by @Jaswir in https://github.com/microsoft/terminal/issues/15127#issuecomment-1547609968_

**Comment by zadjii-msft** [comment]
Almost certainly the issue is in: https://github.com/microsoft/terminal/blob/main/build/rules/GenerateSxsManifestsFromWinmds.targets

**Comment by nchetan** [comment]
Trying to look into this. As described in the original post, I don't see the "Application process" and "Background Task process" as projects. Are they, by any chance referring to "TestHostApp (Universal Windows)"? If not, what should be my setting?
![TerminalProjectsSnapshot](https://github.com/microsoft/terminal/assets/105251813/f8c25ec0-6e51-409c-95b8-c29f5e1de304)

**Comment by nchetan** [comment]
Taking a look to see if I can be of help.
