### ISSUE TITLE
msbuild.exe is not recognized as the name of a cmdlet, function, script file, or operable program. 

### ISSUE THREAD

**Issue by Pcoric** [microsoft/terminal#1537]
# Environment

```none
Windows build number: [run "ver" at a command prompt] Microsoft Windows [Version 10.0.17763.557]
Windows Terminal version (if applicable): v0.2.1715.0

Any other software?
```

# Steps to reproduce

Running the installation commands from vs 2019 preview. I am doing it in PowerShell, although I also tried in CMD and got errors at the bcz step. Import-Module .\tools\OpenConsole.psm1 & 
Set-MsBuildDevEnvironment both worked for me. 

NOTE: Found what seemed like a similar issue at #930 but I am using the merged update. I think I may just need to give up trying to do it with 2019, but I'm still filing this as a bug hoping someone will explain to me why the version is causing this issue if I'm just running PowerShell commands. 
# Expected behavior

I'd expect the Invoke-OpenConsoleBuild command to complete successfully, it's giving me an error. 
# Actual behavior

Build is failing: msbuild.exe : The term 'msbuild.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\pacoric\source\repos\terminal\tools\OpenConsole.psm1:251 char:5
+     msbuild.exe "$env:OpenConsoleRoot\OpenConsole.sln" @args
+     ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (msbuild.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by adiviness** [comment]
it sounds like msbuild isn't getting added to your path correctly, what's your path look like after running `Set-MsBuildDevEnvironment`?

**Comment by jpandersen87** [comment]
I also ran into this issue. You need to run Set-MsBuildDevEnvironment with the Prerelease parameter set to $true for the script to find VS2019.

**Comment by 0x11DFE** [comment]
I am having the same issue, DEV's bump?
