### ISSUE TITLE
Exiting terminal while running `npm` in a pane does not terminate processes from terminal

### ISSUE THREAD

**Issue by fisher60** [microsoft/terminal#15373]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Other Software

Node.js v16.14.2

### Steps to reproduce

1. Open Windows Terminal
2. Split panes
3. Start a process in one pane (I was using `npm run start` to run a local website with React)
4. Observe website running in web browser
5. Use the `x` button on the windows terminal window to exit windows terminal
6. Background process is still running and website is still working in web browser

### Expected Behavior

When quitting windows terminal, background processes should be stopped. The local server running the React website should also be terminated when windows terminal exits.

### Actual Behavior

Background process continues running indefinitely. Task manager does not indicate any windows terminal tasks running in the background. The background task appears to be buried and is difficult to discover so the easiest way to terminate the process is to restart the machine. Restarting the machine terminates the background process and website is no longer hosted.

**Comment by fisher60** [comment]
This issue seems very similar to #541

**Comment by zadjii-msft** [comment]
Pretty confident that this isn't #541 - that was a specific bug from like, almost 4 years ago now. 

If anything, I'd think that #14544 would have helped here. Can you try this with Terminal Preview (v1.17), and see if that fixes this/?

**Comment by fisher60** [comment]
This issue is still reproducible for me on preview version 1.17.1023

**Comment by jsoldi** [comment]
Here having the exact same issue. using the latest version 1.17.11461.0. To repro, just write a small nodejs script like this:

```
import express from 'express';
const port = process.argv[2] || 3000;
const app = express();
app.get('/', (req, res) => res.send(`Hello from port ${port}`))
app.listen(port, () => console.log('Server is running at http://localhost:' + port));
```

Then open two terminal tabs and do `npm start 3000` and `npm start 3001`. Then close the first tab and visit `http://localhost:3000/` and the process will still be running. 

This is making the whole terminal useless as I need to relog the whole user just to stop a process.

**Comment by carlos-zamora** [comment]
Repro steps from #15708

1. Create a folder and clone my sample repro: `npx degit https://github.com/jsoldi/windows-terminal-bug`. It's just a plain server that does nothing.
2. Do `npm install`
3. Open the Windows Terminal on the project folder and run `npm start 3000` and then visit `localhost:3000` on a browser.
4. Close the terminal.
5. Reload `localhost:3000` and the server should still be running

If the process actually stops, try repeating steps 3-5 one more time.

**Comment by zadjii-msft** [comment]
Another repro:

> 1.17.11461.0, 10.0.19044.3086, node v18.15.0
> 
> ### Steps to reproduce
> 
> 1. open terminal
> 2. split pane (shift+alt+-)
> 3. run node (npm run dev)
> 4. close terminal (alt+f4 or `X` button)

**Comment by AdamLeMmon01** [comment]
If I run npm in a PS command, I observe this same behavior:
`wt new-tab pwsh -c "& {npm run start}"` 

If I run npm in a PS job, the background job is terminated correctly when I close the pane/tab/window
`wt new-tab pwsh -c "& {Start-Job {npm run start}}"`

**Comment by Rusinas** [comment]
Same here with the PS command. I was debugging a ps1 script and noticed that each time I run it the port number increments. Then I had to go to the task manager and manually kill 20+ node processes... .__. This is weird.

**Comment by jsoldi** [comment]
Why is this bug not getting more attention? It makes the terminal completely useless for anything other than very specific toy projects and people unaware of the bug will get their system resources slowly eaten up until things start failing.

**Comment by Jimmaphy** [comment]
Tried to recreate the bug with different methods. As both #15708 and #15801 mentioned, running the provided repo through `node` directly doesn't trigger the behavior. Using `yarn`, instead of `npm`, also doesn't trigger this behavior.

**Comment by luidera22** [comment]
This bug is kind of scary, to be honest. I started a project and then when I thought the server was closed it was still running (after 7h that I first closed the terminal). I checked everything and found nothing. But then the last shot was looking into the Process Explorer and bang: node.js still running initialized by command line npm start.

**Comment by zadjii-msft** [comment]
Hey can anyone check if this still repros on 1.22 Preview/? We did some improvements to the way we generate CTRL_CLOSE events over the last couple of releases, and we're pretty confident we're doing it right now. Thanks!

**Comment by wesleyzloza** [comment]
I am still experiencing this issue on the 1.22 preview (specifically v1.22.2362.0). In my case I am running a local server for a Angular website. The development server will persist after the terminal is exited.

**Comment by jsoldi** [comment]
This is still happening on version 1.22. Run run an node project with the code below like `npm run start` where `package.json` contains `"scripts": { "start": "node ./dist/index.js" }`

```
import express from 'express';

const app = express();
const port = 3000;
app.get('/', (req, res) => { res.send('Hello World'); });
app.listen(port, () => { console.log(`Server is running at http://localhost:${port}`); });
```

**Comment by Filyus** [comment]
Temporary solution for Windows:
```shell
taskkill /IM "node.exe" /F
```
Mac and Linux:
```bash
#!/bin/bash
pkill -f "node"
```

**Comment by AssetKid** [comment]
This issue is marked as completed but it was never fixed.

https://github.com/user-attachments/assets/5f29753c-5531-41ae-9b33-5d3adab6e45c

Using CTRL+C kills the node process as expected. However, when you close the terminal tab/window, the process is not stopped.

```
// index.js
import express from "express";

const app = express();
const port = 5555;

app.get("/", (req, res) => {
  res.send("Hello World");
});

app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}`);
});

```

```
// package.json
{
  "name": "wt-bug",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "start": "nodemon index.js"
  },
  "dependencies": {
    "express": "^4.19.2"
  },
  "devDependencies": {
    "nodemon": "^3.1.5"
  }
}
```

**Comment by jsoldi** [comment]
@AssetKid Have you tried using the [preview version](https://apps.microsoft.com/detail/9n8g5rfz9xk3?hl=en-US&gl=US)? The normal version is older than the fixing commit but the preview version is newer and it works for me, both when closing just the tab and when closing the whole application.

**Comment by AssetKid** [comment]
@jsoldi Oh yeah! The bug is not there on the preview version. I figured the stable build would have the fix by now.

Thanks.
