### ISSUE TITLE
Copy text without dismissing the selection

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15371]
> In Notepad, if there is a selection, pressing Ctrl+C, the text will be copied to the clipboard, otherwise nothing happens. This is the same in other edit boxes and controls
> ... 
> I would like Terminal/PowerShell to behave exactly like Notepad

This seems like a reasonable property to add to the `copy` action. 

```ts
class CopyActionArgs {
  singleLine: bool = false;
  copyFormatting = false;
  dismissSelection: bool = false;
}
```

_Originally suggested by @gaberiel44 in https://github.com/microsoft/terminal/discussions/15349_

> **Note**
> ## Walkthrough 

* Add a `Boolean DismissSelection` to `CopyTextArgs` in `src\cascadia\TerminalSettingsModel\ActionArgs.idl`
* Add `DismissSelection` to `COPY_TEXT_ARGS` in `ActionArgs.h`
* The actual copy args are retrieved in `TerminalPage::_HandleCopyText` (in `AppActionHandlers.cpp`), and passed to `TerminalPage::_CopyText`, which calls down to `TermControl::CopySelectionToClipboard`. 
  * In `CopySelectionToClipboard`, just don't `ClearSelection`.
* This arg will also need localization, in `ActionArgs.cpp`, `CopyTextArgs::GenerateName`, and `src\cascadia\TerminalSettingsModel\Resources\en-US\Resources.resw`

**Comment by horrificCoder** [comment]
@zadjii-msft Can I work on this?

**Comment by zadjii-msft** [comment]
Absolutely!

**Comment by Sayan505** [comment]
I've got a fix working. I've removed `_core.ClearSelection();` from `TermControl.cpp` which leads to the intended behaviour. Is this correct?
Looking for feedback on my first ever PR on GitHub. https://github.com/microsoft/terminal/pull/15383

**Comment by lata-michal** [comment]
Hi @Sayan505 
I'm working on the solution too and removing `_core.ClearSelection();` leads to the intended behaviour as you mentioned, but it is also necessary to add the 'DismissSeleciton' arg to the 'copy' action :) Otherwise I think it doesn't properly solve this issue.

**Comment by Sayan505** [comment]
@zadjii-msft Hi, could you please explain me the point of  `bool dismissSelection`?

**Comment by zadjii-msft** [comment]
> could you please explain me the point of `bool dismissSelection`?

Sure - by making this a setting, then users can choose which behavior they want. They could even have both! Like, a user could have the following settings:

```json
"actions":
[
    { "keys": "ctrl+c", "command": { "action": "copy", "dismissSelection": "true" }, },
    { "keys": "ctrl+d", "command": { "action": "copy", "dismissSelection": "false" }, },
]
```

And then 
* <kbd>ctrl+c</kbd> would copy and dismiss the selection (as it currently does)
* <kbd>ctrl+d</kbd> would copy and leave the selection unchanged (as in Notepad et al.)

Or a user could just rebind <kbd>ctrl+c</kbd> to `"action": "copy", "dismissSelection": "false"`, or whatever! 

Does that make sense?

**Comment by code-krishna** [comment]
@zadjii-msft can I kindly work on this issue?

**Comment by mnicol93** [comment]
> ## Walkthrough
> * The actual copy args are retrieved in `TerminalPage::_HandleCopyText` (in `AppActionHandlers.cpp`), and passed to `TerminalPage::_CopyText`, which calls down to `TermControl::CopySelectionToClipboard`.


Hi @zadjii-msft I am trying to fix this issue. I am in the above step, I just wanted to double check with you if I am following along:

- Do I need to change the function declaration of TermControl::CopySelectionToClipboard to add a third parameter `bool dismissSelection`?
- If so, instead of deleting `_core.ClearSelection()` should I change the code to `if(dismissSelection) _core.ClearSelection()`

>This arg will also need localization, in ActionArgs.cpp, CopyTextArgs::GenerateName, and src\cascadia\TerminalSettingsModel\Resources\en-US\Resources.resw

- In `CopyeTextArgs::GenerateName` do I need to do something similar to the previous? `if(DismissSelection()) _core.ClearSelection()`
- For the .resw file, something along the lines of:

**Comment by raavanan77** [comment]
Can I work on this issue?

**Comment by Delano5000** [comment]
@/class CopyActionArgs {
  singleLine: bool = false;
  copyFormatting = false;
  dismissSelection: bool = false;
}

**Comment by rifat01mahmud** [comment]
function copyText() {
  var selectedText = window.getSelection().toString();
  var tempInput = document.createElement("textarea");
  tempInput.value = selectedText;
  document.body.appendChild(tempInput);
  tempInput.select();
  document.execCommand("copy");
  document.body.removeChild(tempInput);
}

// Call the function when the copy button or any trigger event is activated
copyText();

Rifat Mahmud (Ovronormal)
