### ISSUE TITLE
Portable Mode should have a consistent way to refer to the root of the portable install

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#15379]
# Description of the new feature/enhancement

In order to pass in a portable powershell profile to `"commandline"`, we need a way to refer to the root of the portable install. We got around this issue in `"backgroundImage"` by using `ms-appx:///`, however, here, we're just passing the string straight over to PowerShell so it can be resolved there.

# Proposed technical implementation details (optional)

It seems like it has to be an environment variable, because that's the only way shells are going to know about it. Perhaps something like `%WT_PORTABLE_ROOT%`.

**Comment by zadjii-msft** [comment]
@DHowett, our portable mode czar: Motion to dupe this to #16295?

**Comment by carlos-zamora** [comment]
> @DHowett, our portable mode czar: Motion to dupe this to #16295?

Seconded \dup #16295
