### ISSUE TITLE
Shader file on a flash drive won't 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#15377]
### Windows Terminal version

1.18.230516002-preview

### Windows build number

N?A

### Steps to reproduce

1. have terminal in portable mode on a flash drive
2. add a shader.hlsl to `settings` folder
3. link the shader to a profile in the terminal settings

NOTE: the shader works if terminal is not in portable mode. This might be an issue with the shader being stored on a flash drive?

### Expected Behavior

the shader should be applied successfully to the profile

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/11050425/657e9845-e943-4e5b-b462-4f92c0690490)

**Comment by DHowett** [comment]
@carlos-zamora does it work if you are using _packaged Terminal_ (normal mode) with the shader on the flash drive?

**Comment by DHowett** [comment]
Reopening. Carlos was helping get the BUILD conference organized and didn't have time to reply.
