### ISSUE TITLE
Bug Report - Immediate crash with message "Windows cannot access the specified device, path or file" after running as administrator

### ISSUE THREAD

**Issue by amoerie** [microsoft/terminal#1538]
Launching the app immediately produces an error, seemingly related to file permissions.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.116]
Windows Terminal version (if applicable): 0.2.1715.0_x64
This is a work computer inside an Active Directory domain, if that's relevant at all. I am administrator on my local machine though.
```

# Steps to reproduce

Install Windows Terminal (Preview) from the Microsoft Store.
Launch the app as administrator.

# Expected behavior

The application starts.

# Actual behavior

The application immediately throws an error: "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

# Extra notes

I previously built the source code and had it working fine by deploying the CascadiaPackage from within Visual Studio. Then I tried running the app as administrator, which broke it and has caused the aforementioned error to appear whenever I try to launch it now.

I was hoping that the "official" release via the Microsoft Store would fix the problem, but it didn't. (I completely uninstalled the beta version and removed my local copy of the source code beforehand).

Is there any place (logs, event log, ..) where I can see which file it's failing to find? That would help a lot.  Thanks!

**Comment by MajDogbyte** [comment]
same symptoms for me, and i suspected that it started to break after i tried to run as Admin, because i wanted it to pickup my network admin $profile along with its scripts.   It ran fine as the default user until i tried to run it as admin.

**Comment by jbolduan** [comment]
I'm also experiencing this issue.  It runs fine if I run it as my normal non-admin account but when I try to launch using elevated credentials it prompts twice then gives and error saying it cannot find the C:\Program Files\WindowsApps\.........\WindowsTerminal.exe file.

**Comment by JakeMoe** [comment]
I've got the same as @jbolduan , it launches fine as my user account, but when I right click and run as admin, I get two UAC prompts, dropping back to desktop in between each for a moment or two, and then this error:
![image](https://user-images.githubusercontent.com/2450407/60229198-72545c80-98d8-11e9-806e-27e72b247510.png)

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, a Windows issue. We've escalated as appropriate.

**Comment by amoerie** [comment]
Sorry to comment on a closed issue, but is there a manual workaround so we can use the new terminal as a regular user again? Right now it's completely unusable for me..

**Comment by SHDMBelangerAlexandre** [comment]
> I've got the same as @jbolduan , it launches fine as my user account, but when I right click and run as admin, I get two UAC prompts, dropping back to desktop in between each for a moment or two, and then this error:
> ![image](https://user-images.githubusercontent.com/2450407/60229198-72545c80-98d8-11e9-806e-27e72b247510.png)

The only way to fix this i found, is to open your admin session and download the app through the store. But the problem return every time a new version is uploaded. i find it kinda not straight forward.

![image](https://user-images.githubusercontent.com/52332100/60605341-57c22d80-9d87-11e9-826e-0c00a54ea69b.png)

**Comment by rtruss** [comment]
I am running WIN 10 1903 (6.3.18362) and terminal preview installed via the store, this is still an issue.  I log on with my low rights user and right click to run elevated.

![wintermadinerror](https://user-images.githubusercontent.com/39066353/62644910-dbd07d80-b910-11e9-8a7e-4ac1e92a49db.png)

If I try to access the folder, after entering my admin creds I get:
![windowsappserror](https://user-images.githubusercontent.com/39066353/62645080-218d4600-b911-11e9-89b3-6c7bd5194854.png)

I really am interested in getting this tool to work, having it all in one is perfect, if I can use it as an admin logged on as my low rights user, like I can with cmd and powershell.exe now.

**Comment by amoerie** [comment]
I'm still completely unable to use the Windows Terminal due to this issue, even in regular user mode.

**Comment by wushuzh** [comment]
I guess this is related to Windows upgrade and the permission with folder `C:\Program Files\WindowsApp\`

In order to install microsoft terminal, I have to manually download the windows upgrader to get the version 1903 as ms-terminal required. I saw there is a `windows` and `windows.old` on C disks after upgrading. So I guess some internal setting for my useraccount is done. Maybe some internal ID is re-generated during windows upgrading, so someting needs to be done with the folder WindowsApp permission correspondingly ?

But without an official procedure from microsoft, I don't want to do experiments with folder like `Program Files`.  It's too risky.

**Comment by wushuzh** [comment]
Yesterday, windows notices me there are two windows updates available.
After installation, I installed ms-terminal with choco. This time, there is no more crash message and terminal started successfully.

**Comment by raShMan777** [comment]
In case someone wants to investitage I can bring in some additional facts.
On my company notebook i have to users: one without administrator privileges and one without. The normal user can start Terminal without problems. The admin user cannot start it except when i start it elevated…!?
So it's not a common non-admin user problem. When i look into the rights of the folder C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.1.1812.0_x64__8wekyb3d8bbwe I see some special permissions and I suspect that these are going awry.
![grafik](https://user-images.githubusercontent.com/54718892/86457107-6e48ef00-bd23-11ea-8f95-8fdd9e4277f6.png)
