### ISSUE TITLE
Path cannot be traversed because it contains an untrusted mount point

### ISSUE THREAD

**Issue by membranophone** [microsoft/terminal#15399]
### Windows Terminal version

Microsoft.WindowsTerminal_Win10_1.16.10261.0

### Windows build number

Microsoft Windows [Version 10.0.19045.2965]

### Steps to reproduce

Can not start the app. It worked fine until I messed with (what I thought) was safe changes to the registry following this article. https://answers.microsoft.com/en-us/windows/forum/all/how-to-move-the-cusersusernameappdata-folder-to/35e0e881-6e66-4905-9f63-bd99477586b4

Fully aware that this is with 99% certainty not Windows Terminals fault, but that I messed with things that should not have been messed with. But when you are in desperate need of disk space you do weird stuff. Thought I should report it just in case.

### Actual Behavior

The app doesn't start normally. Starting as administrator brings up the UAC twice and then this popup
![image](https://github.com/microsoft/terminal/assets/47756927/f6a8f461-82d2-496d-8040-57b77dbae8cd)

**Comment by zadjii-msft** [comment]
Holy butts I cannot believe that post is still live, there's absolutely no way that should work. 

Yea, everything I know would lead me to think that was deep magic that you should not have messed with 😕 


_maybe_ this is a regression from us switching to the `shell:Appsfolder` thing, but I cannot IMAGINE that moving `%LOCALAPPDATA%` would have ever worked.
