### ISSUE TITLE
Run this Profile as Admin starts Windows Powershell instead of Powershell7

### ISSUE THREAD

**Issue by leoniDEV** [microsoft/terminal#15391]
### Windows Terminal version

1.17.1023

### Windows build number

10.0.25352.0

### Steps to reproduce

Create and account of type administrator;
Create a Windows Terminal's profile for `Powershell7`
In Windows Terminal set a profile for `Windows Powershell` as default profile;

Create an account of type standard;
login with this standard account;
Create a Windows Terminal's profile for `Powershel7` an set `Run this profile as Administrator` to `on`
Try to open this `Pwsh7` profile;
enter credential of the account of type administrator

### Expected Behavior

Open a new elevated instance of Windows Terminal running Powershell 7

### Actual Behavior

A new elevated instance of Windows Terminal is opened with the default profile loaded

**Comment by leoniDEV** [comment]
I think I understand what happen, when open a new tab, `wt` use the command `new-tab --profile {GUID}`, this `GUID` is the one of the profile in the settings of the standard account, but when try to open a profile as admin (when the admin is another account) it load the settings from the admin account which doesn't contains the `GUID` that `wt` try to load and then the default profile is loaded.

As a workaround I copied the `GUID` of the Powershell profile from the standard account to the Powershell profile in the setting file of the admin account.

**Comment by zadjii-msft** [comment]
Ho boy this is a good edge case here. I don't think any of us considered that "Run as Admin" (where the admin account != your current user account) **uses the settings from the admin account**, not your own.

**Comment by carlos-zamora** [comment]
Hey @leoniDEV! Thanks for filing, we're going to mark this as a dup of #11111.

/dup #11111
