### ISSUE TITLE
Displaying image is not working anymore

### ISSUE THREAD

**Issue by koszeggy** [microsoft/terminal#15398]
### Windows Terminal version

All versions

### Windows build number

Not relevant

### Steps to reproduce

**Remark:** I'm not requesting a new feature here. Though displaying images in Windows Console never has been supported officially, it was definitely [possible](https://stackoverflow.com/a/33652557/5114784) and it was working since Windows XP until up to Windows 10 and even [ConEmu](https://conemu.github.io/en/Screenshots.html) emulates this behavior. This issue has been created from my [comment](https://github.com/microsoft/terminal/issues/5746#issuecomment-1356367205) originally posted under #5746, which is a new feature request to support displaying images.

To reproduce the issue you can use the code snippet in a .NET Console application from [here](https://stackoverflow.com/a/33652557/5114784) or execute a [Far Manager](https://www.farmanager.com/download.php?l=en) console application with [Image Viewer](https://plugring.farmanager.com/plugin.php?pid=874&l=en) plugin.

### Expected Behavior

The [linked example](https://stackoverflow.com/a/33652557/5114784) for .NET should produce a result like this:
![Image in Windows Console](https://i.stack.imgur.com/oXH3y.png)

And the aforementioned Far Manager application with the Image Viewer plugin used to work like this:
![Image in pre-Windows 11 console window](https://farplugs.sourceforge.io/img/imageview.png)

### Actual Behavior

The new Windows 11 Terminal apparently does not support this anymore, the images are simply not appearing.

I don't know what's missing to make it work again because [`GetConsoleWindow`](https://learn.microsoft.com/en-us/windows/console/getconsolewindow) still returns the console handle as a Win32 HWND and even the [Graphics::FromHWND](https://learn.microsoft.com/en-us/windows/win32/api/gdiplusgraphics/nf-gdiplusgraphics-graphics-fromhwnd) method returns a seemingly valid instance, it's just its [VisibleClipBounds](https://learn.microsoft.com/en-us/windows/win32/api/gdiplusgraphics/nf-gdiplusgraphics-graphics-getvisibleclipbounds(rect)) is always an empty rectangle.

**Comment by zadjii-msft** [comment]
This is absolutely not going to work in the Terminal - I'd rather not give a bodgy workaround to make it work. As mentioned, the `GetConsoleWindow` thing was never _really_ supported, and I _really_ want to discourage folks from trying that. 

I'd rather just add native support to the Terminal for displaying images - either through `sixel` (#448) or a good image protocol (#5746)

**Comment by koszeggy** [comment]
> I'd rather just add native support to the Terminal for displaying images - either through sixel (https://github.com/microsoft/terminal/issues/448) or a good image protocol (https://github.com/microsoft/terminal/issues/5746)

Whereas a well designed image handling protocol is indeed the recommended and cleanest way for the future it will not help the already existing applications that remain broken.

And also the new projects will have to maintain multiple image handling approaches if they want to be compatible both with the original Windows Console on older Windows versions and the new Windows 11 Terminal.

> This is absolutely not going to work in the Terminal

I really hope there is still some room for discussion about it. It could be at least considered how big effort would it be to provide support for this undocumented feature. [ConEmu](https://conemu.github.io/en/Screenshots.html) solved it somehow too, which is also a multi-tab console emulator, just like the new Terminal. And since Terminal already solved the hardest part (`GetConsoleWindow` returns different handles for the individual tabs, so for example [`SetConsoleTitle`](https://learn.microsoft.com/en-us/windows/console/setconsoletitle) could be also tricked to change the text on the tabs that originally meant to be the title on the legacy Win32 console window), I think this would be just some small(?) additional step. Well, at least in my imagination, without seeing any code. 😁 Maybe you could consult with the ConEmu guys how they managed to solve it.

I hope it will not be closed immediately and even if you don't have enough time for this you are willing to accept pull requests from someone who has the courage/knowledge to include this feature.
