### ISSUE TITLE
Pasting large text from clipboard results in error

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/terminal#1540]
# Environment
Microsoft Windows [Version 10.0.18922.1000]
```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

1. copy (for me 336 lines of json) a large text file
2. select
3. paste into terminal
# Expected behavior
just dump into the console in the same fashion pasting large text data into powershell works

# Actual behavior
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------                                                                                                                                         Last 200 Keys:
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space " R e s o u r c e G r o u p N a m e " : Space " R e s o u r c e G r o u p " , Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space " w e b s i t e " : Space " w w w . c o m p a n y . c o m " Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space Space Space ] Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space ] Enter
 Ctrl+Enter Space Space } Enter
 Ctrl+Enter } Escape

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1134.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
# jeff0372@FSTNQL1 | 11:00:56 | 06-24-2019 | [0.09GB] D:\CODE\projects\mod-posh\powershell\production $  [master ≡]

**Comment by DHowett-MSFT** [comment]
This is actually an issue with https://github.com/lzybkr/PSReadline -- it even directs you to file it over there.
Thanks!
