### ISSUE TITLE
The WPF nuget package isn't signed by our CI

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15404]
From Teams with @javierdlg 

> We hit a snag with out insertion process and we found out that the Microsoft.Terminal.Wpf package does not contain signed files
> Is there a reason for this? Or is the sign step just not part of the release pipeline?

> I honestly don't know... I bet we just forgot it 😅

**Comment by DHowett** [comment]
This actually is known! VS used to re-sign our binaries before deployment.

I was dismayed to learn that signing the `nupkg` does not sign the inner DLLs. Then again, neither did the `MSIX`.

**Comment by javierdlg** [comment]
Not a pressing issue atm, we are currently signing the dlls ourselves but it would be best if they came already signed since we get security warnings about signing 3rd party dlls.

Thanks for looking into this!
