### ISSUE TITLE
Feature request "execute on paste with trailing line feed". 

### ISSUE THREAD

**Issue by big-edd** [microsoft/terminal#15400]
Please consider a setting "execute on paste with trailing line feed". 

Currently a command will not execute when pasting text with a trailing LF (or CRLF). 
This is a good feature for preventing unintentional execution, however there are times when this is desired. 
When many commands are being pasted into the console, and pressing "Enter" is needed for each, it becomes cumbersome. 

Any chance the setting "execute on paste with trailing line feed" (or similar) might be considered? 

When pasting a command (text) with a trailing line feed, that command should be executed immediately.

**Comment by lhecker** [comment]
Thanks for the feature request! However, I believe you can already do this:
* Open settings (Ctrl+,)
* Click "Open JSON file" in the bottom left
* Add the following lines to the outer-most JSON object:
  ```json
  "trimPaste": false,
  "multiLinePasteWarning": true,
  ```

Let me know if that doesn't work for you.

**Comment by big-edd** [comment]
Before: 
"trimPaste": false,
"multiLinePasteWarning": false,

Since this was in the email notification of this request being updated, I tried: 
"trimPaste": false,
"multiLinePasteWarning": true,

Then I thought "no I do not want that warning". 
Back to: 
"trimPaste": false,
"multiLinePasteWarning": false,

..  ..  and now it works..  ..  What the..???  

Seems that me flipping multiLinePasteWarning has given it a kick along, and now it is behaving as expected. 
Originally: false
Then: true
Then: false

No other changes. That's very strange behavior.

**Comment by lhecker** [comment]
> That's very strange behavior.

I hope we can fix that soon! But that aside, I'm happy to hear that it's now working for you. I'll close the issue then. 🙂
