### ISSUE TITLE
Using a soft font causes the Atlas engine to crash

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#15409]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2913

### Steps to reproduce

1. Make sure the Atlas engine is activated in the Advanced profile settings.
2. Open a bash shell.
3. Execute `printf "\eP0;1;1;4;2;1{B~~~~~~~~/~~~~~~~~\e\\"`

### Expected Behavior

Most characters output at this point should be reverse question marks, except for `!` which should map to a solid block.

### Actual Behavior

The terminal crashes. This is caused by a null pointer reference when accessing the `fontFaceEntry.fontFace` field in `BackendD3D::_initializeFontFaceEntry`.

https://github.com/microsoft/terminal/blob/c589784b54d46187289651fa6c04c49fe05826aa/src/renderer/atlas/BackendD3D.cpp#L1158

Just based on a brief scan of the code, I got the impression that it's expected for the `fontFace` to be null when you have a soft font, so it may just be that this method hasn't allowed for that case. This appears to be a regression introduced in PR #15343.

**Comment by lhecker** [comment]
Ah dang I didn't test it again after the PR. 😟 Sorry for breaking it, and thank you so much for noticing it!

**Comment by lhecker** [comment]
FYI the link I distributed in some other comments ([click](https://blob.hecker.io/sharex/Microsoft.WindowsTerminalPreview_1.18.1443.0_8wekyb3d8bbwe.msixbundle)) is a build that also contains the PR that fixes this. If you're eager to test it out, you could consider installing that build. 🙂

**Comment by j4james** [comment]
I've patched my local build with the changes in your PR and it's working great now. Thanks!
