### ISSUE TITLE
Unbound profile shortcuts `ctrl+shift+<n>` still shows on new tab menu

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#15418]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Unbind one of the profiles actions.
In the settings.json:

```json
{
    "actions": [
        {
            "command": "unbound",
            "keys": "ctrl+shift+7"
        }
    ]
}
```

The shortcut will no longer work, but will still show on the new tab menu.

### Expected Behavior

Shortcut does not show on new tab menu.

### Actual Behavior

Shortcut shows on new tab menu.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #13943 for more discussion.

/dup #13943
