### ISSUE TITLE
Crashes when using in multi monitor setup (Terminal Preview)

### ISSUE THREAD

**Issue by damchey** [microsoft/terminal#15414]
Have a multi monitor (1080p & 4k) setup. When opening terminal preview on the 4K monitor, it is buggy, the typed texts do not appear immediately and only see a cursor. It appears after multiple carriage returns. When I move the window to the 1080p monitor, it starts working properly. Then when I move the window back to the 4k monitor, it crashes with the below error:

Renderer encountered an unexpected error: -2005270527

Terminal Preview Version: 1.18.1421.0
Windows 11 (22H2)
Build: 22621.1776 (release preview)
Machine: Dell XPS 9510 (Intel i7 11800H)

**Comment by zadjii-msft** [comment]
> the typed texts do not appear immediately and only see a cursor

What font are you using? I bet this is the #15403 thing

**Comment by damchey** [comment]
> > the typed texts do not appear immediately and only see a cursor
> 
> What font are you using? I bet this is the #15403 thing

Source Code Pro for Powerline

**Comment by carlos-zamora** [comment]
Hi @damchey. We serviced #15403. It should be available in version 1.18.1462.0. Mind trying it out and letting us know if you're still experiencing this issue? Thanks!

**Comment by damchey** [comment]
> Hi @damchey. We serviced #15403. It should be available in version 1.18.1462.0. Mind trying it out and letting us know if you're still experiencing this issue? Thanks!

Downloaded the latest release. Seems to have fixed my issue. Thank you.

**Comment by zadjii-msft** [comment]
Great, thanks for confirming!
