### ISSUE TITLE
Please provide offline package for side-loading

### ISSUE THREAD

**Issue by sharpninja** [microsoft/terminal#1541]
# Need offline package for side-loading

My employer has the MS Store blocked at the firewall, so downloading anything through it is impossible.  

# Proposed technical implementation details (optional)

Please provide an appx download that I can side-load.

**Comment by DHowett-MSFT** [comment]
We're already talking about this at #1480 #1483 please make sure you search first

**Comment by cup** [comment]
https://github.com/microsoft/terminal/issues/1386
https://github.com/microsoft/terminal/issues/1405
https://github.com/microsoft/terminal/issues/1480
https://github.com/microsoft/terminal/issues/1483

https://github.com/microsoft/terminal/issues/1541
