### ISSUE TITLE
Scrollbar marks for shell integration do not clear when you use clear/cls commands

### ISSUE THREAD

**Issue by The-MAZZTer** [microsoft/terminal#15426]
### Windows Terminal version

1.18.1421.0

### Windows build number

Version 10.0.22621.1702

### Other Software

PowerShell 7.3.4

### Steps to reproduce

1. Enable shell integration as documented here: https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration
2. Enable PWSH and CMD support (for PWSH I added it to my Documents\PowerShell\Profile.ps1)
3. Open new PWSH and CMD shells and press enter a bunch of times to generate a bunch of marks.
4. Type clear in PWSH or cls in CMD
6. Type commands that generate output like dir 
7. Press Ctrl+Up/Down a bunch

### Expected Behavior

The scrollbar marks should disappear on clear/cls and the Ctrl+Up/Down should navigate only through the visible commands

### Actual Behavior

The marks remain on the scrollbar and they will still be jumped to even though they are in the middle of command output.

**Comment by zadjii-msft** [comment]
Sure don't. I think this is noted in #11000 but I'll make sure #15057 links this specifically. Thanks!
