### ISSUE TITLE
Terminal crashes after splitting panes - all profiles, orientations affected

### ISSUE THREAD

**Issue by killshot13** [microsoft/terminal#15431]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22624.0

### Other Software

**PowerShell** 7.3.4
**WSL2**: 1.2.5.0
**Ubuntu** 22.04 LTS
**Git for Windows** v2.40.1

_These are the underlying profiles from which I am attempting to generate the split-pane view._

### Steps to reproduce

**Easiest Steps:**
1. Open a Windows Terminal Preview tab. 
2. Right-click the tab and select `Split Pane` from the menu. 
3. Attempt to interact with the terminal or simply wait a few seconds, and it crashes.

**Alternative Steps:**
1. Open a Windows Terminal Preview tab.
2. Use the `CTRL`-`SHIFT`-`P` shortcut to focus the command menu dropdown.
3. Type `Split` into the search to populate the relevant commands.
4. Navigate to the `Split Pane` option and hit the `Enter` key.
5. Attempt to interact with the terminal or simply wait a few seconds, and it crashes.

### Expected Behavior

I expected to successfully [create multiple panes](https://learn.microsoft.com/en-us/windows/terminal/panes#creating-a-new-pane) within the terminal view, and for them to be swappable, movable, and able to be reoriented without affecting the performance of the interface or the shell.

### Actual Behavior

I'm not entirely sure my if bug is the same as referenced in #14254 or #14247. But it's extremely similar. However this issue is distinctively broader, because it occurs regardless of which profile is being split and in what orientation. I've attached a short video so you can take a look, and the link to the Feedback Hub submission is down below. 👇

---

https://github.com/microsoft/terminal/assets/47695475/d980f7fc-600e-445f-8b8c-1625cab41d93

---

[Feedback Hub submission link](https://aka.ms/AAkxzib)

**Comment by zadjii-msft** [comment]
Do you have `focusFollowMouse` enabled by any chance? Does disabling that setting fix this? (see #15412)

**Comment by evanjs** [comment]
Disabling `focusFollowMouse` appears to resolve the issue for me

**Comment by sephiroth-j** [comment]
> Do you have `focusFollowMouse` enabled by any chance? Does disabling that setting fix this? (see #15412)

Disabling  `focusFollowMouse` resolves the crash when splitting panes but not when starting another Terminal instance.

**Comment by zadjii-msft** [comment]
@sephiroth-j You're on Windows 10, yea? My psychic debugging tells me that the crash when starting a second instance is #15410. That's based solely on the observation that the _second_ `windowsterminal.exe` process crashes, but the first keeps running happily. I don't think there's a workaround for that one currently - though, we should have a hotfix for that soon<sup>tm

**Comment by sephiroth-j** [comment]
> @sephiroth-j You're on Windows 10, yea? My psychic debugging tells me that the crash when starting a second instance is #15410. That's based solely on the observation that the _second_ `windowsterminal.exe` process crashes, but the first keeps running happily. I don't think there's a workaround for that one currently - though, we should have a hotfix for that soontm

Yes, version 10.0.19045.3031 to be precise. Thanks for pointing out issue #15410, I must have missed that. 🤷

**Comment by killshot13** [comment]
> Do you have `focusFollowMouse` enabled by any chance? Does disabling that setting fix this? (see #15412)

Yes, I did, and yes, that resolved the issue. I am closing this issue since the root cause is already being tracked in #15420. Thank you, @sephiroth-j.
