### ISSUE TITLE
Keyboard Scrolling

### ISSUE THREAD

**Issue by codefoster** [microsoft/terminal#1543]
After executing a command that results in more than one screen of standard output, I would like to be able to use PAGE UP and PAGE DOWN to navigate the results. Currently, hitting PAGE UP just sends `5~`.

**Comment by Shorotshishir** [comment]
try using `ctrl+shift+pgup` and `ctrl+shift+pgdn`

**Comment by codefoster** [comment]
That works great! Thanks.
