### ISSUE TITLE
tab row is 100% transparent when enable Mica in Windows 11 21H2 (22000.1936)

### ISSUE THREAD

**Issue by scott-xu** [microsoft/terminal#15435]
### Windows Terminal version

1.17.11391

### Windows build number

10.0.22000.1936

### Steps to reproduce

create a custom them and enable Mica:
```
        {
            "name": "Mica",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "tabRow": 
            {
                "background": "#00000000",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "system",
                "useMica": true
            }
        }
```

### Expected Behavior

Show Mica effect in tab row

### Actual Behavior

The tab row is 100% transparent

**Comment by zadjii-msft** [comment]
Hmm. I wonder if there's anything that can prevent Mica from being enabled somehow? Like, at the OS level? 

Presumably Mica is working in `calc.exe`?

**Comment by scott-xu** [comment]
Yes, Mica is working in calc.exe
![image](https://github.com/microsoft/terminal/assets/1913505/1aef9fec-5616-4704-b227-67e12689f1c9)
![image](https://github.com/microsoft/terminal/assets/1913505/fba184f8-2b43-46a6-b4a0-2e22a25d755b)

**Comment by zadjii-msft** [comment]
Actually, can you file feedback using the Feedback Hub, on the category "Developer Platform > UI Frameworks and controls (XAML)"? I'm not sure there's much else we'll be able to do on our side to investigate this, but they might have more complete diagnostics to share. If you share the aka.ms link that the "Share" button generates in this thread, I can make sure it gets promoted internally and follow it. 

Thanks!

**Comment by scott-xu** [comment]
Unfortunately, I have upgraded the  OS to Windows 11 22H2 and the issue disappeared.

**Comment by zadjii-msft** [comment]
Hey that's better than nothing! Thanks for following up ☺️
