### ISSUE TITLE
Does not dismiss dropdown options when click left side

### ISSUE THREAD

**Issue by scott-xu** [microsoft/terminal#15437]
### Windows Terminal version

1.17.11391

### Windows build number

10.0.22621.1778

### Steps to reproduce

Open Settings, choose Default profile, do not select any profile from the dropdown options, click left side (the red circle areas).
![image](https://github.com/microsoft/terminal/assets/1913505/2cae3051-bd33-414f-9637-dcfc817bfb7f)

### Expected Behavior

The dropdown options should dismiss

### Actual Behavior

The dropdown options do not dismiss

**Comment by lhecker** [comment]
As far as I can tell we can't fix this. I even tried a couple tricks just now and couldn't do it. The bug has been reported to WinUI: https://github.com/microsoft/microsoft-ui-xaml/issues/3961
