### ISSUE TITLE
Latest Windows Terminal Preview version breaks Visual Studio profiles

### ISSUE THREAD

**Issue by huguesv** [microsoft/terminal#15448]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2965

### Other Software

Visual Studio 2022 (multiple versions)

### Steps to reproduce

Install Visual Studio 2022 (any version should do it, I have community 17.5.4)
Upgrade to Windows Terminal 1.18.1421.0
In Terminal, Open the "Developer Command Prompt for VS 2022" profile

### Expected Behavior

No errors, various VS 2022 environment variables are set.

### Actual Behavior

'C:\Program' is not recognized as an internal or external command, operable program or batch file.

**Comment by zadjii-msft** [comment]
/dup #15436 

We should be pushing a hotfix for this soon<sup>tm
