### ISSUE TITLE
Crash when opening a new tab or window, or any non-default profile

### ISSUE THREAD

**Issue by sboukortt** [microsoft/terminal#15446]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Open two tabs or two windows.

### Expected Behavior

Two tabs are opened and can be used.

### Actual Behavior

Opening the second tab or window triggers a crash of the entire application, taking both tabs/windows with it.

Windows Terminal 1.16.10261.0 with the same configuration works as expected.

**Comment by sboukortt** [comment]
I saw an open issue that I thought might be related but the discussion suggests that that other issue is specific to when `focusFollowMouse` is enabled, and I have it disabled.

**Comment by lhecker** [comment]
Yesterday, when running a debug build off of main, I also had it crashing, and it was due to `GetRootPane()` returning `nullptr` right here:
https://github.com/microsoft/terminal/blob/3c3b1aac02320f49f6887f08e6d6d1d56132b1ef/src/cascadia/TerminalApp/TerminalPage.cpp#L3355-L3360

Curiously this issue has never occurred before on my PC.

**Comment by zadjii-msft** [comment]
Yea, we'll need a stack or something to investigate here. 

If you file /feedback with the Feedback Hub, we _might_ be able to reverse engineer that in the backend and find crashes that have already happened. Unlikely, but worth a shot. 

If it repros consistently though, then just trying to repro it with the feedback hub's "Recreate my problem" recorder _should_ grab the dump. 
![image](https://github.com/microsoft/terminal/assets/18356694/035365d2-8c0c-4782-8331-d20e52ef2256)

**Comment by dziban303** [comment]
Same thing is happening for me. Normally it's intermittent—usually, I can open a new tab without issue. I'd say that the issue manifests maybe 20% of the time. Luckily, it happened every single time when recording it with Feedback Hub, a Vorführeffekt in my favor for a change 😂

**Comment by zadjii-msft** [comment]
@dziban303 can you share the Feedback Hub link here?

**Comment by dziban303** [comment]
Hey @zadjii-msft sorry. Here's the link https://aka.ms/AAkzyij

**Comment by zadjii-msft** [comment]
I won't be able to take a look till tomorrow at the earliest, but as a sanity check, does https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0 work? That has some hotfixes for... kinda a lot of bugs...

**Comment by dziban303** [comment]
Thanks, it was literally installing via the Store when you sent that. I'll give it a whirl later tonight. Cheers

**Comment by sboukortt** [comment]
Sadly, it still reproduces for me. It also seems not to always respect the window transparency I have set, and it crashes when going to “Settings” -> (“Profiles” ->) “Defaults” -> “Appearance” where one would set it. Could that be related?

I tried to file feedback with the Feedback Hub but couldn’t quite figure out whether it would record crash data for Terminal _Preview_ if I select “Terminal” as the app (Terminal Preview isn’t offered as a choice). Does it?

**Comment by zadjii-msft** [comment]
Okay so ai was able to find a dump from @dziban303's machine (even if Feedback Hub wasn't the _most_ cooperative). It looks like you're hitting the `"focusFollowMouse": true` crash. That was tracked in #15412, and should be fixed in https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0.


@sboukortt - you've got that setting disabled, so presumably you're seeing something new. Can you file the same Feedback Hub steps above/? That should help us find the dump on the backend.

**Comment by sboukortt** [comment]
I am not sure what changed but it doesn’t seem to be happening anymore? That’s still with v1.18.1462.0.

The main change I can think of that could possibly have to do with this is that I upgraded my graphics driver (NVIDIA) to 535.98, from the previous “studio” driver (I don’t remember which version that was).

**Comment by sboukortt** [comment]
For some reason, it seems to be happening again since my last reboot. (I usually use hybrid shutdown / “fast startup” rather than a full reboot.) The version of Terminal Preview is still v1.18.1462.0.

I am getting the impression that there is something that causes it to either happen reliably or not at all after every reboot, which is rather mysterious. Thankfully, if that is the case, it means I have until my next reboot to figure out how to get a proper stacktrace.

**Comment by sboukortt** [comment]
I still haven’t got around to doing that, but for what it’s worth, the other day, I updated my GPU driver and it seems to have crashed Terminal Preview but not Terminal.

**Comment by zhangjy859** [comment]
Hi @sboukortt，

I also have the same issue after a system reboot, Could you please give me some suggestions? I have feedback with feedback hub

**Comment by zadjii-msft** [comment]
@zhangjy859 Do you have MacType installed by any chance? If so, go update it. Older versions of that will crash the Terminal. 

If not, could you share the link to your feedback in Feedback Hub here in this thread? Thanks!
