### ISSUE TITLE
wt --help process never exits

### ISSUE THREAD

**Issue by gurnec** [microsoft/terminal#15443]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Run `wt --help` or `wt -v` and then close the resulting window. (The `compatibility.allowHeadless` setting doesn't appear to change anything.)

### Expected Behavior

The `WindowsTerminal.exe` process exits.

### Actual Behavior

The help/version window closes, but the process remains running.

**Comment by zadjii-msft** [comment]
oh my god I did `ExitThread` instead of `ExitProcess` 🤦

**Comment by gurnec** [comment]
Hey, at least it was an easy fix! Thanks!
