### ISSUE TITLE
Support Alt+Enter (proper full screen)

### ISSUE THREAD

**Issue by terrajobst** [microsoft/terminal#1544]
In the old conhost I was able to use use Alt+Enter to enter full screen mode (i.e. no title bar, no task bar, just the entire screen real-estate devoted to my console window). Thew new Cascadia window doesn't seem to support this yet.

**Comment by DHowett-MSFT** [comment]
@terrajobst thanks for requesting. I found #531 with a cursory search.

**Comment by terrajobst** [comment]
I searched. I swear I did. Maybe that was because missing morning coffee or GitHub search wasn't helpful.

**Comment by odytrice** [comment]
Was about to ask for the same thing
