### ISSUE TITLE
Rendering Issues within Preview v1.18.1421.0

### ISSUE THREAD

**Issue by sthurston99** [microsoft/terminal#15456]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22624.0

### Other Software

PowerShell 7.3.4.0 x64
Oh My Posh version 16.9.0
mononoki NF (https://www.nerdfonts.com/font-downloads)

### Steps to reproduce

Opening the terminal application and typing text in the window.

### Expected Behavior

Text to render as soon as it was typed

### Actual Behavior

Text rendering delayed by multiple seconds. When capturing with screentogif, the rendering is faster but does not capture the delay between proper rendering on the monitor.

Confirmed that rendering works properly when the font is swapped from mononoki NF to Cascadia Code or Lucida Console.

Not sure what specifically is causing this, as rendering works perfectly fine on my previously installed version (1.16.10261.0, have not updated because for some reason it's not in winget yet).

**Comment by sthurston99** [comment]
Also just tested- disabling Atlas makes the text rendering with mononoki NF return to normal and expected behavior, which isolates the bug.

**Comment by zadjii-msft** [comment]
> Also just tested- disabling Atlas makes the text rendering with mononoki NF return to normal and expected behavior, which isolates the bug.

Great, based on everything in this report I'll call this a /dup of #15416
