### ISSUE TITLE
Moving the window with title bar tabs is hard

### ISSUE THREAD

**Issue by terrajobst** [microsoft/terminal#1545]
I like the tabs in the title bar. However, the area where I can move the window is too small:

![image](https://user-images.githubusercontent.com/5169960/60040483-f5be4580-966d-11e9-8e34-2a17f26e0759.png)

Compare this with Edge/Chrome where the entire area not used for tabs can be used to move the window around:

![image](https://user-images.githubusercontent.com/5169960/60040586-36b65a00-966e-11e9-9ba9-779a62e03d08.png)

**Comment by The-Noah** [comment]
Yes, this is a major issue for me.

**Comment by JushBJJ** [comment]
#1375

**Comment by JushBJJ** [comment]
Duplicate of #564?
