### ISSUE TITLE
Hard reset disables win32-input-mode

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#15461]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2913

### Steps to reproduce

1. Start Windows Terminal.
2. Open up a WSL bash shell with the debug tap enabled.
3. Press some keys and note the escape sequences that are generated in the debug pane.
4. Execute `reset`.
5. Press some more keys and note what is generated in the debug pane now.

### Expected Behavior

I'd expected to see win32-input-mode escape sequences for every key press.

### Actual Behavior

After the reset, win32-input-mode is disabled, and the key presses are just passed through as ASCII, or basic VT100 escape for things like arrow keys.

I think this was a regression introduced in PR #14444 when I made the `RIS` operation fully reset all input modes. Technically that was the right thing to do, but for conpty to work correctly, it would now also need to re-request any non-default modes it needs from the conpty client.

I'm not sure how best to fix this. The `HardReset` implementation can't just return false to pass through the `RIS` sequence anymore. It would probably need to call a new "reset" method in the renderer that the VT engine would pass on as an `RIS` with additional mode requests. It must also then return true to prevent the state machine trying to pass through the `RIS` a second time.

I don't know if anyone has any better ideas.

**Comment by j4james** [comment]
Having looked at the `VtEngine::RequestWin32Input` implementation here:

https://github.com/microsoft/terminal/blob/c9e993a38ec04833e15edac230300948a0fab83b/src/renderer/vt/state.cpp#L542-L548

it appears we also need to request the focus event mode. Otherwise that's also something that'll stop working after a hard reset.

**Comment by j4james** [comment]
I realised there's an easier way of handling this which doesn't require any new render APIs. We already have access to the `StateMachine` instance from within `AdaptDispatch`, and that gives us the ability pass through sequences directly to the conpty client. 

So a simple fix would be to add something like this to the end of the `HardReset` method.

```cpp
if (_api.IsConsolePty())
{
    auto& stateMachine = _api.GetStateMachine();
    if (stateMachine.FlushToTerminal())
    {
        auto& engine = stateMachine.Engine();
        engine.ActionPassThroughString(L"\033[?9001;1004h");
    }
}
```

The `FlushToTerminal` call should pass through the pending `RIS` sequence, and then we follow that up with mode requests to enable win32 input and focus events.

The only downside I can see is that we're essentially duplicating the code from `VtEngine::RequestWin32Input`, which runs the risk of the two getting out of sync, but that could be mitigated with a couple of comments. It's not as clean as I'd like, but it's probably the simplest option.

**Comment by DHowett** [comment]
I'm alright with "duplicate with comment", until we get to 3 places that need to do it. Then we can figure it out 🙂 

Excellent catch!
