### ISSUE TITLE
Behavior of acrylic is not intuitive

### ISSUE THREAD

**Issue by terrajobst** [microsoft/terminal#1546]
I love the acrylic. But it seems odd that it's only active when the window has the focus. If anything, the reverse would make more sense to me (i.e. disabling it when the window isn't in use). Is it possible to make this configurable?

* Off
* On
* On when focused
* On when not focused

**Comment by JushBJJ** [comment]
Seems like a #1375

**Comment by DHowett-MSFT** [comment]
Sorry, man, this is the official Windows stance on Acrylic. This is a systemwide policy applied to the acryilc brush. :smile:

**Comment by terrajobst** [comment]
> Sorry, man, this is the official Windows stance on Acrylic. This is a systemwide policy applied to the acrylic brush. 😄

😟

Makes sense though.
