### ISSUE TITLE
1.18 - PowerShell clear command results in non-rendered prompt using Atlas Engine

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/terminal#15460]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22000.0

### Other Software

Oh My Posh v16.9.0

### Steps to reproduce

Oh My Posh recently added support for FTCS marks which seems to work really well with the latest preview release of Terminal, VSCode and iTerm. However, when typing clear, the entire prompt disappears and you can see the multiple cursors when typing (seems that way). Waiting a few seconds, or removing focus from Windows Terminal, it renders the prompt again. This behaviour wasn't there in 1.17.

https://github.com/microsoft/terminal/assets/2492783/00c657d5-42b7-4113-a1ff-07837c4b4937

This seems to be an issue with the new Atlas Engine as I can't reproduce it when it's not enabled.

EDIT: even without printing the marks, the behaviour is there.

### Expected Behavior

It displays the prompt correctly.

### Actual Behavior

There's an invisible prompt at the top (and consequent prompts as well for a few seconds).

**Comment by elbertcastaneda** [comment]
I have the same problem, but when I recorded my screen with ScreenToGif to show the error, the error is not captured but in my screen I am seeing the error,

Here the result with ScreenToGif:

![terminal-bugfix](https://github.com/microsoft/terminal/assets/3514681/7800cb8a-c209-442f-8896-ce161618a428)

Here the error recorded my phone because as I mentioned is record my screen with software the error is not showed

https://github.com/microsoft/terminal/assets/3514681/313b7128-3e2d-4bfc-8e03-b801b6b635f6

and also we have this error sometimes:

![Screenshot 2023-05-27 022843](https://github.com/microsoft/terminal/assets/3514681/166fb343-19f2-45c2-999d-0bb856a8bac1)

**Comment by zadjii-msft** [comment]
What font is that? this might be #15416 or one of the other few rendering glitches we hotfixed

**Comment by floh96** [comment]
@zadjii-msft i have the same problem and I'm using the following font CaskaydiaCove Nerd Font

**Comment by JanDeDobbeleer** [comment]
> What font is that?

In my case that's Victor Mono Nerd Font.

**Comment by elbertcastaneda** [comment]
> What font is that? this might be #15416 or one of the other few rendering glitches we hotfixed

In my case it is Fira Nerd Font.

**Comment by rkeithhill-keysight** [comment]
I see the issue. I also cannot capture a screenshot of the problem since that causes the problem to go away. And I'm also using CaskaydiaCove Nerd Font.

**Comment by JanDeDobbeleer** [comment]
@rkeithhill-keysight true, I noticed the video I posted above also doesn't show the issue clearly and you can't screenshot either because I'm too slow 😂

**Comment by lhecker** [comment]
Once again, I'm sorry for causing this issue! It was fixed by #15403 which has shipped in [v1.18.1462.0](https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0). It should also already be available via the app store. I hope it works now!

**Comment by elbertcastaneda** [comment]
@lhecker no problem at all, in fact thanks to you for solving the issue, you are the best. I will do feedback if I find something new regarding this.

**Comment by elbertcastaneda** [comment]
Yeah it is working right now, thanks a lot for your help @lhecker
