### ISSUE TITLE
Only works on first launch

### ISSUE THREAD

**Issue by chd-trifork** [microsoft/terminal#1547]
# Environment

Windows build number: Version 10.0.18362.175

# Steps to reproduce

Installed Windows terminal from the store. Pressed start, and it works fine. Then i close it and try to start it from the shortcut in the start menu.

Have reproduced it 3 times, with the same behaviour.

# Expected behavior

I expect windows terminal to open.

# Actual behavior

Nothing happens

**Comment by JushBJJ** [comment]
Is the process at least running in the background?

**Comment by chd-trifork** [comment]
?No, I can't find it in the joblist...

---
Christian Holm Diget
Backend Tech Lead
Trifork eHealth<http://ehealth.trifork.com/>?
Prags Boulevard 80, 2300 Copenhagen S.
Mobile +45 51 94 15 51
________________________________
Fra: JushBJJ <notifications@github.com>
Sendt: 24. juni 2019 20:13
Til: microsoft/terminal
Cc: Christian Holm Diget; Author
Emne: Re: [microsoft/terminal] Only works in first run (#1547)


Is the process at least running in the background?

-

**Comment by chd-trifork** [comment]
I just looked further and I actually found it in the app overview... But I can't find it in the Processes tab.


[cid:80c87836-e328-4b03-8173-93f51490bc20]

---
Christian Holm Diget
Backend Tech Lead
Trifork eHealth<http://ehealth.trifork.com/>?
Prags Boulevard 80, 2300 Copenhagen S.
Mobile +45 51 94 15 51
________________________________
Fra: JushBJJ <notifications@github.com>
Sendt: 24. juni 2019 20:13
Til: microsoft/terminal
Cc: Christian Holm Diget; Author
Emne: Re: [microsoft/terminal] Only works in first run (#1547)


Is the process at least running in the background?

-

**Comment by DHowett-MSFT** [comment]
We have no idea how to reproduce this. If you delete `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json`, does it start up again?

**Comment by mcs-sss** [comment]
I might be having something similar happening.  Maybe it's not related to the first launch per se, but the nightly build (https://terminalunofficial.z13.web.core.windows.net/nightly) worked for me earlier today and then has stopped working.  I've tried removing it and reinstalling it with no luck.  I see a border but no window, then it goes away.  I'm on Windows 18362.145.

Event log is as follows:

Faulting application name: WindowsTerminal.exe, version: 0.0.0.0, time stamp: 0x5d1319f7
Faulting module name: ucrtbase.dll, version: 10.0.18362.1, time stamp: 0x5cbddb81
Exception code: 0xc0000409
Fault offset: 0x000000000006d3be
Faulting process id: 0x2b04
Faulting application start time: 0x01d52d486d9c9150
Faulting application path: C:\Program Files\WindowsApps\WindowsTerminalDev_0.0.2034.0_x64__8tnac03rdnr9a\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 79b94be9-4a2c-4fcc-91d2-ca7554f29b69
Faulting package full name: WindowsTerminalDev_0.0.2034.0_x64__8tnac03rdnr9a
Faulting package-relative application ID: App

**Comment by DHowett-MSFT** [comment]
We do not produce that "nightly build." It even says `terminalunofficial` in the URL.

**Comment by chd-trifork** [comment]
?Yes, that worked!

---
Christian Holm Diget
Backend Tech Lead
Trifork eHealth<http://ehealth.trifork.com/>?
Prags Boulevard 80, 2300 Copenhagen S.
Mobile +45 51 94 15 51
________________________________
Fra: Dustin L. Howett (MSFT) <notifications@github.com>
Sendt: 28. juni 2019 00:27
Til: microsoft/terminal
Cc: Christian Holm Diget; Author
Emne: Re: [microsoft/terminal] Only works in first run (#1547)


We have no idea how to reproduce this. If you delete %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json, does it start up again?

-

**Comment by chd-trifork** [comment]
Bonus question...


Is it possible (yet) to have Visual Studio use Windows terminal (with a specific profile) when running an application I am working on (in this case Azure Functions, when run locally for testing)? I would love to test that, and it is important for me to actually be able to move to Windoes terminal.

---
Christian Holm Diget
Backend Tech Lead
Trifork eHealth<http://ehealth.trifork.com/>?
Prags Boulevard 80, 2300 Copenhagen S.
Mobile +45 51 94 15 51
________________________________
Fra: Dustin L. Howett (MSFT) <notifications@github.com>
Sendt: 28. juni 2019 00:27
Til: microsoft/terminal
Cc: Christian Holm Diget; Author
Emne: Re: [microsoft/terminal] Only works in first run (#1547)


We have no idea how to reproduce this. If you delete %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json, does it start up again?

-

**Comment by zadjii-msft** [comment]
@chd-trifork At the time, that's not a currently supported scenario, though hopefully that should be fixed by #492.

Considering your original problem has been resolved, I'll close this issue.
