### ISSUE TITLE
Exiting python 3.10.x interactive shell leads to render glitches, or renderer crash

### ISSUE THREAD

**Issue by oising** [microsoft/terminal#15472]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22631.1825

### Other Software

Python 3.10.4

### Steps to reproduce

I cannot repro this renderer crash, but I was using interactive python 3.10.4 (py) and trying to edit the current line with the arrow keys and the last line became glitchy with characters missing. I exited the cli, attempted to clear screen with ctrl+L (default powershell binding) and got the effect shown in "actual behaviour" below.

I _can_ repro glitchy rendering though by running "py", moving the cursor around a bit, then "ctrl+z,<enter>" to exit. The terminal then fails to render the text correctly and acts _very_ weird. I cannot screenshot the rendering as when I do, the screen refreshes and the glitches disappear.

### Expected Behavior

Expected to clear the screen :)

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/1844001/a85f1488-bfb0-4d1f-9429-ef057aafe999)

clicking "ok" results in the same dialog popping up. it's a loop.

**Comment by DHowett** [comment]
Does this still repro with the recently-release `v1.18.1462.0`?

**Comment by DHowett** [comment]
(There was an issue with the renderer displaying glyphs outside of the screen bounds.)

**Comment by oising** [comment]
> Does this still repro with the recently-release `v1.18.1462.0`?

Just updated and cannot reproduce on 1462, closing. Thank you! @DHowett
