### ISSUE TITLE
About dialog version update check shows current version

### ISSUE THREAD

**Issue by gregsskyles** [microsoft/terminal#15475]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.3031

### Other Software

n/a

### Steps to reproduce

Launch WT
Click v to open menu, choose About ?
If check for update is showing, click it

### Expected Behavior

I would have expected:

Windows Terminal Preview
Version: 1.18.1421.0
An update is available.
Version: **1.18.1462**

### Actual Behavior

The current version is shown as the update version:

Windows Terminal Preview
Version: 1.18.1421.0
An update is available.
Version: 1.18.1421

![2023-05-29_18h47_52](https://github.com/microsoft/terminal/assets/13614644/279395ef-574a-43f6-99db-472bf876d8e5)

**Comment by DHowett** [comment]
Ahhh, heck. I forgot to service this to the 1.18 branch. Thanks :)

**Comment by DHowett** [comment]
So, I figured out what happened! This change made it into the 1.18 servicing pipeline, but got marked as "already cherry picked" (somehow(?)). The servicing script rightly ignored it. I wonder if we can do any validation on those cards...

I wonder. Is this a change that I cherry picked on one of my dev machines and didn't push? What else have I missed?
