### ISSUE TITLE
Can we drop the telemetry for VT sequences?

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#15482]
# Description of the new feature/enhancement

We've now reached the point that if we add another VT sequence to the telemetry tracker, the `TraceLoggingWriteActivity` call will fail to compile. I'm not exactly sure what the problem is, but the initial warning/error is: `pasting '_tlg_FOR_imp' and '(' does not result in a valid preprocessing token`, after which there are another 20 or so lines of errors.

It's possible there is a way to work around that, but if we don't really need this telemetry, it would be nicer if we could just drop it altogether. And maybe that will save a bit of parsing overhead in the process.

# Proposed technical implementation details (optional)

Drop the `TermTelemetry` class, and then remove all code that was making calls to it.

**Comment by zadjii-msft** [comment]
I'm all for it. This was more valuable when we like, hardly implemented any sequences. I don't think this is even hooked up to anything at this point.

**Comment by DHowett** [comment]
YES. PLEASE. Thank you!

**Comment by DHowett** [comment]
The way we implemented this telemetry is wrong, anyway - `TraceLogging` is supposed to be zero-cost if it is not enabled, so every time we put the log behind a function call we're wasting a branch and likely cache fault to determine we aren't supposed to be doing anything.

**Comment by bishalkar10** [comment]
I am very new to programming. I am confused how can I contribute to open source. I am proficient in html, css, javascript and learning react now.  Can I contribute somehow?
