### ISSUE TITLE
Bug Report - Magnifier causes the terminal menu to disproportionately enlarge

### ISSUE THREAD

**Issue by Sirmentio** [microsoft/terminal#1548]
# Environment
Running Microsoft Windows [Version 10.0.18362.175], Windows terminal version 0.2.1715.0 while using Windows Magnifier.

# Steps to reproduce

Run Windows Magnifier from any means of doing so, and launch Windows Terminal. Zoom in to any percent beyond 100% and press the main menu button on the top of the window.
# Expected behavior
The menu should scale well with Windows Magnifier and should fit the rest of the desktop.

# Actual behavior
The menu becomes overgrown disproportionately to the zoom level of the desktop itself to the point of usability issues.

![image](https://user-images.githubusercontent.com/42724159/60041650-f06ef400-9689-11e9-92df-ce977af19708.png)

**Comment by DHowett-MSFT** [comment]
This is _amazing_!

**Comment by DHowett-MSFT** [comment]
Lucky us, this is a XAML bug! Unlucky for this repository, it's an external tracking issue. :smile:

**Comment by zadjii-msft** [comment]
Is there an actual issue on [microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml) for people to track this issue? Or is it an internal issue number?

**Comment by ron442** [comment]
Just updated to v0.3.2171.0 and while the display of the menu is improved when magnifier is running compared to the previous version, the problem is still there.
