### ISSUE TITLE
Unable to drag tabs when Windows Terminal is opened in Administrator mode

### ISSUE THREAD

**Issue by tapadeep** [microsoft/terminal#15492]
### Steps to reproduce

1. Run Windows Terminal Preview as Administrator
2. Open multiple tabs in one window
3. Try to drag the tabs back and forth

### Expected Behavior

Users should be able to bring certain tabs back and forth even when running Terminal Preview in Admin mode.

### Actual Behavior

All tabs are locked in their places.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6661 for more discussion.

/dup #6661
