### ISSUE TITLE
Some icons are not rendered correctly even after using Oh My Posh and Terminal-Icons

### ISSUE THREAD

**Issue by tapadeep** [microsoft/terminal#15493]
### Windows Terminal version

1.18.1462.0

### Steps to reproduce

1. Follow the steps mentioned in [Tutorial: Set up a custom prompt for PowerShell or WSL with Oh My Posh](https://learn.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup)
2. Run Windows Terminal Preview as Administrator

### Expected Behavior

All icons should be properly rendered

### Actual Behavior

The prompt has some <?>-like icons
![undetected](https://github.com/microsoft/terminal/assets/72414672/5e508277-3bbd-43fe-b0ce-bd9359854263)

**Comment by lhecker** [comment]
Hey! If you don't mind, could you please be more precise when filing issues? 😟
oh-my-posh ships with a ton of different themes and it's not always obvious which one you chose. I believe it's the "montys" theme? In any case it looks like this for me:
![image](https://github.com/microsoft/terminal/assets/2256941/c0a0aead-9919-4d36-a620-7e8e087db1f1)

It looks identical in other terminals I've tried. Which font are you using? 🤔

**Comment by tapadeep** [comment]
> 

Yes, I'm using 'montys.omp.json,' and the font is 'CaskaydiaCoveNerdFontMono-Regular'

On changing the Windows Terminal Preview >> Defaults >> Font Face to >> 'CaskaydiaCove Nerd Font Mono,' I was able to fix one of the right-arrow icons. But the downside is that the hourglass icon is still not rendering and some of the other icons have gotten disproportionately smaller!

![better](https://github.com/microsoft/terminal/assets/72414672/02dfd6b7-d44b-4d4d-82b5-9b8100ed9847)

**Comment by lhecker** [comment]
Hmm that's kind of weird. The tiny icon issue should not occur if you're using the latest version (1.18.1462.0). You can check you version here:
![image](https://github.com/microsoft/terminal/assets/2256941/517a563c-4f9e-4303-8e30-373fe68aed49)

I'm not sure what's happening with the hourglass icon. You could try out [Delugia](https://github.com/adam7/delugia-code) which is sort of the original CaskaydiaCove font. I find that it works better than CaskaydiaCove.

**Comment by tapadeep** [comment]
> Hmm that's kind of weird. The tiny icon issue should not occur if you're using the latest version (1.18.1462.0). You can check your version here: ![image](https://user-images.githubusercontent.com/2256941/242575433-517a563c-4f9e-4303-8e30-373fe68aed49.png)
> 
> I'm not sure what's happening with the hourglass icon. You could try out [Delugia](https://github.com/adam7/delugia-code) which is sort of the original CaskaydiaCove font. I find that it works better than CaskaydiaCove in general.

I'm on Version: 1.18.1462.0 only.

**Comment by lhecker** [comment]
When I install the latest "CaskaydiaCove Nerd Font Mono" from the releases page ([v3.0.2](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2)) my result doesn't look anywhere close to your screenshot:
![image](https://github.com/microsoft/terminal/assets/2256941/50668680-81ea-421a-9fb1-79c5312ced74)

Did you get a chance to try out Delugia yet?

**Comment by tapadeep** [comment]
Few things:
1. Can you try opening your terminal in admin mode?
2. Sanity check: Have you changed the terminal font? Windows Terminal Preview >> Defaults >> Font Face >> 'CaskaydiaCove Nerd Font Mono'
3. I can still see some icons are rendered as <?>, which is still not expected.
4. Is Delugia a nerd font?

**Comment by tapadeep** [comment]
> Few things:
> 
> 1. Can you try opening your terminal in admin mode?
> 2. Sanity check: Have you changed the terminal font? Windows Terminal Preview >> Defaults >> Font Face >> 'CaskaydiaCove Nerd Font Mono'
> 3. I can still see some icons are rendered as <?>, which is still not expected.
> 4. Will try out Delugia as well.

Delugia Mono fixed the size of the icons but the hour glass symbol for time is still not rendering.

**Comment by carlos-zamora** [comment]
Hi @tapadeep. We're going to close this as a /dup of https://github.com/JanDeDobbeleer/oh-my-posh/issues/3818

It looks like there's an ongoing discussion on the oh-my-posh repo about this bug.

**Comment by j4james** [comment]
In case it's not obvious from that linked issue, the hourglass icon is no longer used in the montys theme. Since v16.2.1 it has been replaced with the nf-cod-server_process icon (U+EBA2). That's the square with two little cogs that you're seeing in https://github.com/microsoft/terminal/issues/15493#issuecomment-1571811069.

The reason for the change is kind of complicated, but the gist of it is that Nerd Fonts mistakenly assigned a bunch of icons to Unicode codepoints that were reserved for real languages, and the hourglass in the montys theme was part of that set. Nerd Fonts finally removed those erroneous icons a month ago, and oh-my-posh had to be updated to account for that change.

So if your font version and oh-my-posh version are out of sync, you can expect some icons to be missing. And if you've got the latest version of everything, you can expect some of the icons to look different. So if you were hoping to get the originally hourglass icon back, you'll either need to get old versions of both the font and oh-my-posh, or possibly just create your own theme.

**Comment by Risyandi** [comment]
If you open powershell in mode "administrator" you can solved this problems with changes font available in your themes to for example default "MesloLGM Nerd Font"
