### ISSUE TITLE
Terminal crashes when clicking or dragging over full-width characters in the scrollback buffer

### ISSUE THREAD

**Issue by tc21** [microsoft/terminal#1549]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): latest store build (0.2.1715.0) and github build
```

# Steps to reproduce

1. Type in one or many full-width unicode characters or emoji. For example, ｔｈｉｓ or ⚡.
2. Press enter enough times to put the characters into the scrollback buffer.
3. Scroll up and click on one of the full-width characters. Or start a selection from elsewhere and drag your mouse over one of the full-width characters. Basically (LMB down + mouse over a full width character in the scrollback buffer).

# Expected behavior

Nothing special should happen.

# Actual behavior

Terminal crashes.

**Comment by carlos-zamora** [comment]
Surprised this is occurring. My guess is that this is related to #1317. The call stack sounds like it's from `Terminal::_ExpandWideGlyphSelectionRight()` or `Terminal::_ExpandWideGlyphSelectionLeft()`.

To fix this, we need to modify `Terminal::_GetSelectionRects()` to prevent selecting a part of the buffer that doesn't exist.

Adding "Help-Wanted" tag for anybody to hop on this.
