### ISSUE TITLE
Win10 UAC off,terminal couldn't accept drop file

### ISSUE THREAD

**Issue by flylinfan** [microsoft/terminal#15502]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.2965

### Steps to reproduce

turn off UAC,open terminal,drop file from explorer to terminal failed.  

### Actual Behavior

can't drop file to terminal

**Comment by DHowett** [comment]
Can you recall if this was working in a previous version of Windows Terminal?

**Comment by flylinfan** [comment]
> Can you recall if this was working in a previous version of Windows Terminal?

After verifying that the old version also has this problem, is it caused by the system’s metro app security mechanism?

**Comment by carlos-zamora** [comment]
Hi @flylinfan. Could you test this on WT preview and let us know if this repros? Thanks in advance!

**Comment by flylinfan** [comment]
> Hi @flylinfan. Could you test this on WT preview and let us know if this repros? Thanks in advance!
test WT preview 1.18 is is the same result

**Comment by zadjii-msft** [comment]
To be very specific - Are you running the Terminal as your local user account, but with admin permissions, or do you have UAC disabled entirely/? These are two similar sounding but totally different scenarios.

What's the output of `reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ /v enablelua`?

This sounds a lot like #11668, which is closed, tracking an upstream platform one. But I thought there was a fix in 1.18 that should have mitigated this...

**Comment by flylinfan** [comment]
> To be very specific - Are you running the Terminal as your local user account, but with admin permissions, or do you have UAC disabled entirely/? These are two similar sounding but totally different scenarios.
> 
> What's the output of `reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ /v enablelua`?
> 
> This sounds a lot like #11668, which is closed, tracking an upstream platform one. But I thought there was a fix in 1.18 that should have mitigated this... This one: #14946
enablelua    REG_DWORD    0x1
