### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by davidayalagt** [microsoft/terminal#1550]
Windows build number: [Version 10.0.18362.30]
Windows Terminal version: 0.2.1715.0
Windows Language: English
Keyboard Layout: Latinamerica

# Steps to reproduce

Open a terminal window (PowerShell, CMD or WSL - Ubuntu 18.04 in my case)
Try enter any character that requires ALT-GR (\\, ¬, @)

# Expected behavior

The character should appear in terminal.

# Actual behavior

The character doesn't appear.

**Comment by DHowett-MSFT** [comment]
1. Please enter a real title
2. Please search for existing issues. #521 literally contains the word “alt gr”
