### ISSUE TITLE
Soft line breaks option when pasting from clipboard

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#15508]
# Description of the new feature/enhancement

Consider adding a soft line break option for pasting from the clipboard when ENABLE_PROCESSED_INPUT is disabled (e.g. `pwsh -Interactive`). This will allow users to paste multi-line text from the clipboard into a powershell-like shell as a single blob without line-by-line execution.

# Proposed technical implementation details (optional)

In my opinion, this is enough to add a Shift modifier to the generated Return key when converting a text string into keypress events.

When the Shift key is pressed in shells like powershell, a soft line break is added instead of executing the current line.

Related to #3449
x-link https://github.com/PowerShell/PSReadLine/issues/579

Current behavior

https://github.com/microsoft/terminal/assets/11535558/29a74316-1e77-437a-ac52-7f2f094242b8

Behavior with Shift modifier added to Return key event

https://github.com/microsoft/terminal/assets/11535558/9313c3c8-87c2-430a-9b69-6538a0f47b07

**Comment by carlos-zamora** [comment]
The proper implementation of this feature (imo) would include:
- a setting on the "paste" action
- a setting on right clicking
- updating the multi-line paste warning

**Comment by DHowett** [comment]
FWIW, I think it is _strictly better_ for PowerShell to implement support for bracketed paste, which will also give it support for soft paste in other terminal emulators.

I am somewhat worried about us committing to a niche feature when the _right_ one is on the table. :smile:

**Comment by j4james** [comment]
For reference, the PSReadLine bracketed paste issue is here: https://github.com/PowerShell/PSReadLine/issues/1471

**Comment by o-sdn-o** [comment]
> I think it is strictly better for PowerShell to implement support for bracketed paste

It is never happens because it would definitely be a breaking change for them. 

This will only be done when powershell/PSReadLine/.Net completely moves from the practice of using ReadConsoleInputW to ReadConsole to read input. That is, it will never happen.

You support this approach from the very beginning. You are converting raw text strings to pressed keys. I think it makes sense to keep this practice until the end, as long as it is used by dependent projects.

**Comment by o-sdn-o** [comment]
The reason why this will never happen is that `ReadConsoleInput` is an almost perfect (almost bcz it is [codepoint based](https://en.wikipedia.org/wiki/Code_point) only) keyboard protocol. This is literally a keyboard protocol, not a binary stream reading function. Until an alternative and completely perfect ([grapheme cluster based](https://unicode.org/reports/tr29/)) keyboard protocol is provided, no one will stop using `ReadConsoleInput`. So it's more likely that the Unix world will come up with an analogue of `ReadConsoleInput` than switch to using raw `ReadFile`.

PS: I apologize for using `you` instead of `WT` in my past and future posts, because in Slavic languages `you` may not be considered impolite as it is in English.

**Comment by o-sdn-o** [comment]
I have nothing against bracketed paste, but here it's just about setting only one bit (Shift modifier) for only one keyboard event associated with the `Return` key in the stream of generated keyboard events. It is not supposed to change or substitute characters or anything like that here. Setting only one flag, which is only looked at by those who are waiting for soft breaks. What will it affect? Or what could it break? Powershell maintainers invent a heuristic for detecting the paste action from the clipboard by measuring the time between keyboard events, and here WT only needs to insert one bit in one place and the long-standing question is closed.

**Comment by j4james** [comment]
How would this work on other platforms, though, since PowerShell also runs on Linux and macOS? Like if you've got two panes open in Windows Terminal, one side with Windows PowerShell and the other a Linux version of PowerShell under WSL, would soft line breaks only be expected to work in one pane?

**Comment by o-sdn-o** [comment]
> How would this work on other platforms, though, since PowerShell also runs on Linux and macOS? Like if you've got two panes open in Windows Terminal, one side with Windows PowerShell and the other a Linux version of PowerShell under WSL, would soft line breaks only be expected to work in one pane?

My guess is that the Shift modifier of the Enter key event will be ignored when translating the event stream to a text string. Something like `INPUT_RECORD{ Shift+Enter }` => `\r` or `\n`.

**Comment by o-sdn-o** [comment]
In my setup the behavior of pwsh in WSL does not depend on the presence of the Shift modifier
- Left pane: pwsh on Windows
- Right pane: pwsh on WSL+Ubuntu 22.04

Test with `powershell amd64 7.3.4-1.deb` on `WSL Ubuntu 22.04`

https://github.com/microsoft/terminal/assets/11535558/d65cd3d8-39ca-4fc8-9ca7-45c85992dbcf

**Comment by DHowett** [comment]
> Perhaps this solution will be only for Windows.

See, this is the thing I have an issue with! Yeah, `INPUT_EVENT` records are great, but they just don't remote well and they are not cross-platform. I don't think that means we shouldn't _use_ them! I just think: there is a standard for terminals to emit unmodified pasted text _that works across the entire ecosystem_, over ssh, on other platforms, etc.; why should we be the odd ones out and do something that only works properly when you're running a shell directly on Windows with no intermediary?

**Comment by o-sdn-o** [comment]
> PowerShell on macOS with iTerm2, Linux with foot and Konsole and libvte-based terminals, FreeBSD, etc. anywhere it runs

Thirst of all they need a keyboard protocol to provide Shift+Enter multiline user experience. The bracketed paste support is just a small addon.

> why should we be the odd ones out and do something that only works properly when you're running a shell directly on Windows

I think because others lack of keyboard protocol and they must invent it.

**Comment by o-sdn-o** [comment]
WT already owns the almost general keyboard protocol - [Win32 Input Mode](https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md). Just extend it to allow an arbitrary number of code points contained at the end of the vt-sequence to be grapheme cluster aware. And allow the stream of these sequences to be interleaved with the raw text stream. An application that expects WIN32_INPUT_MODE will simply ignore the raw text stream.

**Comment by o-sdn-o** [comment]
Ок. It is just another nice #8343 try to rise the cli interactivity level up.

**Comment by o-sdn-o** [comment]
My idea disproof: Far Manager Editor treats `Shift+Enter` as its own macro, not as a soft line break

![image](https://github.com/microsoft/terminal/assets/11535558/7b743e6d-0bea-43c0-8ef1-78ce7db901b3)
