### ISSUE TITLE
Changed behavior of keyboard context menu

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#15514]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22621

### Other Software

Far.exe

### Steps to reproduce

Try to open context menu with keyboard button 'Menu'. The split pane menu is poped up:

![nomenu](https://github.com/microsoft/terminal/assets/78153320/52df2088-26a4-453a-9a29-ad806ed37358)

### Expected Behavior

The context menu of application should be rised:

![menu](https://github.com/microsoft/terminal/assets/78153320/47b3ed3c-c85c-40b2-8521-846a616bea4e)

### Actual Behavior

The split pane menu of terminal is unexpectedly poped.
In the previous WT Preview it worked as expected.

**Comment by j4james** [comment]
Open the _Settings_ and go to the _Actions_ page. There should be an entry there for _Show Context Menu_ which by default is mapped to the <kbd>menu</kbd> key. If you don't like that mapping you can change it to something else or just delete it completely.

**Comment by 237dmitry** [comment]
Thank you, this solved problem.
