### ISSUE TITLE
Shortcut to directly select the hint commands 

### ISSUE THREAD

**Issue by xenkuo** [microsoft/terminal#15516]
# Description of the new feature/enhancement
The terminal could automatically show the possible command when you typing it, but seems there's no shortcut could directly select it. I have tried to google or bing(😄 )it a lot, still no any clues.

The hint command is just below commands in red rectangle:
![image](https://github.com/microsoft/terminal/assets/59609423/f8e90ace-3840-4ea2-a3d1-f63bd34ca562)

# Proposed technical implementation details (optional)

I want to confirm is there such a shortcut to select it? If yes, please tell me, thank you in advance; if no, any plan for it?

**Comment by zadjii-msft** [comment]
1. This is technically a PsReadline feature, not a Terminal one. For more reading, see: [Using predictors in PSReadLine](https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/using-predictors?view=powershell-7.3)
2. Press the right arrow key to fill in the suggestion

**Comment by xenkuo** [comment]
@zadjii-msft , thanks for the response, at least there's a key to directly select it now.

**Comment by xenkuo** [comment]
For anyone want to remap the key bind to shift+tab, paste below line to $PROFILE
`Set-PSReadLineKeyHandler -Chord "Shift+Tab" -Function AcceptSuggestion`
