### ISSUE TITLE
VS Developer Prompts do not attach to window, conflict with `allowHeadless`

### ISSUE THREAD

**Issue by JVimes** [microsoft/terminal#15518]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.0

### Other Software

Visual Studio 17.7.0 Preview 1.0

### Steps to reproduce

1. Select "Windows Terminal" for "Default terminal application" under Startup.
1. Set `"windowingBehavior": "useAnyExisting"` and open a terminal.
1. From Start, run "Developer PowerShell for VS 2022" or "Developer Command Prompt for VS 2022" from Visual Studio.

### Expected Behavior

The developer prompt is new tab in the existing terminal window.

### Actual Behavior

The developer prompt opens in a second instance of Windows Terminal. This creates another problem with `alwaysShowNotificationIcon` and the new `compatibility.allowHeadless`, where the extra notification area icon can't be closed without killing WindowsTerminal.exe.

![2023-06-06_11h22_45](https://github.com/microsoft/terminal/assets/6148201/1f8f0f21-1407-4463-bc79-73907f2fd143)

**Comment by JVimes** [comment]
CC @zadjii-msft 🙂

**Comment by zadjii-msft** [comment]
This sounds exactly like the same thing as /dup #15509. Thanks!
