### ISSUE TITLE
Save the window position between restarts

### ISSUE THREAD

**Issue by milen-prg** [microsoft/terminal#15529]
# Description of the new feature/enhancement

The software must save its window's position and at next start to open on the same place.
It is extremely inconvenient to open at random place, frequently partially out of the display!

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
It can already do this, see: [Behavior when starting a new terminal session](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session)

**Comment by milen-prg** [comment]
> It can already do this, see: [Behavior when starting a new terminal session](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session)

OK, this is useful.
