### ISSUE TITLE
[Enhancement] add profile change after boot cmd

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#15520]
# Description of the new feature/enhancement
add a command to change the profile after initial boot. for example if your running a bat file and it wants the profile while running to change the foreground text color to green and the background image to nature.png it should be able to do so. Just an example default bg color and other properties would also be nice.

The user would be able to launch multiple batch files in one window without having a newTab for every batch file to get the proper profile up.

# Proposed technical implementation details (optional)
`profile "My Awesome Profile"`
where the profile is already imported into the profiles json

**Comment by zadjii-msft** [comment]
kinda like #4176

**Comment by carlos-zamora** [comment]
@jredfox So, just to be clear, our interpretation of the feature request is: if you run a batch script, you should be able to interact with and customize the settings of the session (i.e. background image, colors, etc...).

Is that right?

**Comment by offiub** [comment]
Okay it can’t approved now because of the errors and issues . Could you
like us to rectify it sir On Thu, Jun 15, 2023 at 12:32 AM

**Comment by offiub** [comment]
Yes it has errors and it needs to be fixed . Do you want our help and
support On Thu, Jun 15, 2023 at 1:02 AM roy hub offi <
