### ISSUE TITLE
wt.exe always show information in a new popup window

### ISSUE THREAD

**Issue by xudyang1** [microsoft/terminal#15521]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.0

### Other Software

powershell 7.3.4
ubuntu 20.04 in WSL2

### Steps to reproduce

1. Open powershell or ubuntu in WSL2
2. type `wt.exe -v` or `wt.exe --help`
3. see the output message in a new popup window

### Expected Behavior

I'm not sure if it's by design, maybe redirecting messages to stdout (terminal) would be better?

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/61672396/5ca5a7d5-0ccd-482b-83ec-d198738e3bb2)

**Comment by DHowett** [comment]
Thanks for the request! This is much harder than it might appear; I've explained in this comment: https://github.com/microsoft/terminal/issues/4570#issuecomment-586551445

We'll improve it to the best of our ability, and we're tracking that in /duplicate #7258. Sorry!
