### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by pizzacrystal** [microsoft/terminal#15526]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19044.0

### Steps to reproduce

- double click " C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe"
or
- single click the icon that is pinned to taskbar

**however**, it is normal if it is launched from icon in Start Menu or shortcut under "..\Start Menu\Programs\System Tools".

### Expected Behavior

normal startup, either double click directly or single click on taskbar icon.

### Actual Behavior

crashed immediately

---
feedback link: https://aka.ms/AAl3dtt

---
** More Info **

错误应用程序名称: WindowsTerminal.exe，版本: 1.17.2305.26001，时间戳: 0x647122fe
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.2913，时间戳: 0xa1c3e870
异常代码: 0xc000027b
错误偏移量: 0x000000000012d862
错误进程 ID: 0xe64
错误应用程序启动时间: 0x01d999b746d3a23e
错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 8f566e1a-cf35-4105-b9f9-7074fec0209e
错误程序包全名: 
错误程序包相对应用程序 ID: 

故障存储段 1495973896281467734，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: WindowsTerminal.exe
P2: 1.17.2305.26001
P3: 647122fe
P4: combase.dll
P5: 10.0.19041.2788
P6: 03e7e147
P7: 802b000a
P8: 000000000001ccfa
P9: 
P10:

**Comment by pizzacrystal** [comment]
update:
- pretty sure that v1.16.1026 worked normally therefore this issue is introduced in after automatically updating via MS store
- has updated Win10 to latest (22H2, 19045.2965) but no help

**Comment by thomas-berg** [comment]
I'm experiencing a similar issue, however only when starting Windows Terminal with 'Run as administrator'. Curiously the UAC displays 'Unknown program' instead of Window Terminal.

Error details:

Faulting application name: WindowsTerminal.exe, version: 1.17.2305.26001, time stamp: 0x647122fe
Faulting module name: KERNELBASE.dll, version: 10.0.19041.964, time stamp: 0x812662a7
Exception code: 0xc000027b
Fault offset: 0x000000000010b39c
Faulting process ID: 0x18dc
Faulting application start time: 0x01d99cf6ec8159a5
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 87ddfae3-6979-41f8-bdbd-457d8fee45ab
Faulting package full name: Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Fault bucket 1862083693364119841, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.17.2305.26001
P4: 647122fe
P5: combase.dll
P6: 10.0.19041.928
P7: c94441ae
P8: 802b000a
P9: 0000000000086256
P10:

**Comment by z3nn13** [comment]
I can also confirm. I have the exact same Terminal & Windows version, and this issue started happening recently.
It seems that running either "wt.exe" or "WindowsTerminal.exe" directly from "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe" does not work anymore.

However, as pizzacrystal said, both clicking the Start Menu shortcut and opening via MS Store still functions. 
I have attached a screen record showing this issue.

https://github.com/microsoft/terminal/assets/74445896/c964c7dc-3b97-44f7-a6e4-513e0b1f1e8b

**Comment by DHowett** [comment]
You are not supposed to launch those files directly out of that directory.

**Comment by z3nn13** [comment]
I see, but the problem still persists. Before, I was able to run wt from the search bar or windows run command. Now, it loads for a bit and nothing shows up (as in the video above).

**Comment by offiub** [comment]
Yes it has errors and it needs to be fixed . Do you want our help and
support On Thu, Jun 15, 2023 at 3:24 AM Zen Akenobe | Paul <

**Comment by offiub** [comment]
All you need to do is to deposit 400 because of the errors and rectified
sir

**Comment by offiub** [comment]
Yes sir . How do you make your payment so we can clear the errors and
rectify it sir

**Comment by DHowett** [comment]
This may not lead anywhere, but can you share the output of running `cacls "C:\Program Files\WindowsApps" /s` as admin?

**Comment by z3nn13** [comment]
> This may not lead anywhere, but can you share the output of running `cacls "C:\Program Files\WindowsApps" /s` as admin?
Sure,
C:\Program Files\WindowsApps "D:PAI(A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;OICIIO;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)(A;OICIIO;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)(A;;FA;;;SY)(A;OICIIO;FA;;;SY)(A;CI;0x1200a9;;;BA)(A;OICI;0x1200a9;;;LS)(A;OICI;0x1200a9;;;NS)(A;OICI;0x1200a9;;;RC)(XA;;0x1200a9;;;BU;(Exists WIN://SYSAPPID))(A;OICI;FA;;;S-1-5-21-757397538-3420403896-3795204366-1001)"

**Comment by lhecker** [comment]
That doesn't quite look correct does it? Compared to mine:
```diff
diff --git a/z3nn13.txt b/lhecker.txt
index 8e308da98..502dcdb55 100644
--- a/z3nn13.txt
+++ b/lhecker.txt
@@ -1,13 +1,12 @@
 D:PAI
 (A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
-(A;OICIIO;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
+(A;OICIIO;GA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
 (A;;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)
-(A;OICIIO;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)
+(A;OICIIO;GXGR;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)
 (A;;FA;;;SY)
-(A;OICIIO;FA;;;SY)
+(A;OICIIO;GA;;;SY)
 (A;CI;0x1200a9;;;BA)
 (A;OICI;0x1200a9;;;LS)
 (A;OICI;0x1200a9;;;NS)
 (A;OICI;0x1200a9;;;RC)
 (XA;;0x1200a9;;;BU;(Exists WIN://SYSAPPID))
-(A;OICI;FA;;;S-1-5-21-757397538-3420403896-3795204366-1001)
```

**Comment by pizzacrystal** [comment]
my ACLs of "WindowsApps" folder is exactly the same as z3nn13's.

```
D:PAI
(A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
(A;OICIIO;**FA**;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
(A;;0x1200a9;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)
(A;OICIIO;**0x1200a9**;;;S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204)
(A;;FA;;;SY)
(A;OICIIO;**FA**;;;SY)
(A;CI;0x1200a9;;;BA)
(A;OICI;0x1200a9;;;LS)
(A;OICI;0x1200a9;;;NS)
(A;OICI;0x1200a9;;;RC)
(XA;;0x1200a9;;;BU;(Exists WIN://SYSAPPID))
(A;OICI;FA;;;S-1-5-21-491703059-3840752500-854807576-1001)
```

it seems that all "GA"(SDDL_GENERIC_ALL) access rights are changed to "FA"(SDDL_FILE_ALL), on the other hand, "GXGR"(SDDL_GENERIC_EXECUTE + SDDL_GENERIC_READ) is replaced by unknown right "0x1200a9", and finally there is an 'extra' line in the end.

Is access right the essential cause of this issue? and why did it occur?

**Comment by carlos-zamora** [comment]
There are a couple of remediation steps over in #9452. If you're looking for a solution to this bug, please avoid anything that resets the ACLs or taking ownership of the WindowsApps folder. In the meantime, you might be able to get by with the unpackaged or portable mode install.

/dup #9452

**Comment by zadjii-msft** [comment]
> Report ID: 87ddfae3-6979-41f8-bdbd-457d8fee45ab Faulting package full name: Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe Faulting package-relative application ID: App
> 
> Fault bucket 1862083693364119841, type 5

To link up here:
* 1862083693364119841 is bucket `BucketDetails?BucketIdentifier=af4b9a31-2316-635d-79d7-7340dd040921`
* which is MSFT:44764509
* same as #15745

---



> 错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe 
> 错误模块路径: C:\Windows\System32\KERNELBASE.dll 
> 报告 ID: 8f566e1a-cf35-4105-b9f9-7074fec0209e 
> 错误程序包全名: 
> 错误程序包相对应用程序 ID:
> 
> 故障存储段 1495973896281467734，类型 4 
> 事件名称: APPCRASH 响应: 不可用 Cab ID: 0

This is:
* bucket `BucketDetails?BucketIdentifier=5270cee1-6b8d-d951-f4c2-c455291d2b56`
* which is _both_:
  * MSFT:44764509
  * MSFT:44828510 also tracked in #15583
