### ISSUE TITLE
Lines always wrapped

### ISSUE THREAD

**Issue by jm903** [microsoft/terminal#15527]
### Windows Terminal version

1.18.1462.0

### Windows build number

Microsoft Windows [Version 10.0.22621.1702]

### Steps to reproduce

Type long line that exceeds the current pane width.

### Expected Behavior

In cmd.exe, one can choose whether the lines are wrapped or not. If not wrapped, then a horizontal scroll-bar is used to pan.

### Actual Behavior

All lines are wrapped.
![image](https://github.com/microsoft/terminal/assets/135974064/d70ca424-7030-44a2-83ac-5ba638d2c44d)

**Comment by jm903** [comment]
You're right, I searched for _wrap_. I guess this can be closed then. :(

**Comment by zadjii-msft** [comment]
/dup #1860

Thanks!
