### ISSUE TITLE
Closing last tab crashes WindowsTerminal.exe

### ISSUE THREAD

**Issue by camilo86** [microsoft/terminal#1552]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version: 0.2.1715.0
```

# Steps to reproduce

1. Open terminal window
2. Close tab with shortcut (CTR+W) or click on the tab's 'X' button to close

# Expected behavior

Closing the last tab should close the whole terminal window.

# Actual behavior

Terminal freezes and crashes

**Comment by b3u** [comment]
> # Expected behavior
> Closing the last tab should close the whole terminal window.
Or, display a minimal splash screen. (personal preference)

**Comment by DHowett-MSFT** [comment]
#1380

**Comment by cdokolas** [comment]
I get a freeze when closing any PowerShell tab ("cmd" tabs don't have this problem)
