### ISSUE TITLE
ctrl+arrow keys doesn't stop on word delimiter @

### ISSUE THREAD

**Issue by clopnaz** [microsoft/terminal#15528]
### Windows Terminal version

1.16.10261.0

### Windows build number

Version 10.0.19045.3031

### Other Software

PowerShell 7.3.4 tab

### Steps to reproduce

1. type `word@word` 
2. press `ctrl`+`left arrow`

### Expected Behavior

cursor stops at @ 

### Actual Behavior

cursor moves to beginning of line

**Comment by j4james** [comment]
This is not something that the terminal controls, but you can configure this in PowerShell with the `-WordDelimiters` option. See the `Set-PSReadLineOption` documentation [here](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.3#-worddelimiters).

**Comment by carlos-zamora** [comment]
Thanks for filing! Yeah, as James said, this isn't controlled by Windows Terminal. It's a shell (specifically, PowerShell) feature. Closing!
