### ISSUE TITLE
Two styles of delimiter for ANSI control codes

### ISSUE THREAD

**Issue by the-moog** [microsoft/terminal#15530]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Other Software

Stock Ubuntu/WSL 23.04

### Steps to reproduce

I believe other terminals allow  `:` or semicolon `;` as field separators.  I tried that with WT and found it to be inconsistent.
Here is a link to a script that tries various colours, you can run it with a delimiter as a parameter to demonstrate this.
[https://gist.github.com/the-moog/0a6281dd284749331516dbfceb3fe5c0](https://gist.github.com/the-moog/0a6281dd284749331516dbfceb3fe5c0
)

Here is a link where somebody has tried to collate the relevant compliance of various terminals.
[https://github.com/termstandard/colors](https://github.com/termstandard/colors)

### Expected Behavior

Either form works

### Actual Behavior

Only ; is consistent

**Comment by lhecker** [comment]
Reading through the linked xterm issues and their reasoning about why `:` should be supported for these color sequences made a lot of sense to me. The tl;dr is that `;` should delimit parameters that can exist in any arbitrary order, but the parameters in a color sequence like `38;5;n` cannot be reordered and so `38:5:n` or `38:2:r:g:b` should've technically been used from the start. This was apparently even a concern when these sequences were first introduced in the 90s ([here](https://bugzilla.gnome.org/show_bug.cgi?id=685759)).

I'm all in favor of making such a compatibility change, especially given that xterm/libvte and many of the other most popular terminals accept it.

**Comment by zadjii-msft** [comment]
Pretty sure this is already tracked in #4321

**Comment by DHowett** [comment]
Absolutely is! Thanks Mike!

/dup #4321
