### ISSUE TITLE
VT Sequences rendered improperly in Far Manager

### ISSUE THREAD

**Issue by Zeroes1** [microsoft/terminal#15533]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.2965

### Other Software

Far Manager, version 3.0.6161.0 x64

### Steps to reproduce

Microsoft.WindowsTerminalPreview_1.18.1462.0_x64.zip
in portable mode, uac off, under Admin

use with FAR 100% times
work with FAR
[settings.zip](https://github.com/microsoft/terminal/files/11711587/settings.zip)

### Actual Behavior

sometime (sic!) in FAR console after some different actions i got strange codes:
ANSI?/ESC sequenced?
like:
5;67;18m
5;43;34m;29m
5;55;26m;37m                                                                                    
5;28;15m
35;69;9m;47;10m97;6m8m49;10m3m

probably when use Microsoft.WindowsTerminal_1.17.11461.0_x64.zip
this no have problem

I cant how reproduce.

**Comment by Zeroes1** [comment]
today i see this on version wt Microsoft.WindowsTerminal_1.17.11461.0_x64.zip

**Comment by zadjii-msft** [comment]
This looks very much like something disabling VT processing mode. Having exact repro steps would be helpful here. Perhaps there's some child process you're launching that's turning VT mode off (and FAR isn't turning it back on?)

**Comment by Zeroes1** [comment]
trouble present when i not run anything...
i see this may be when change focus app1/app2/app3 & when use event from mouse?

i dont know how reproduce this situation

i use windows 27 year
far manager 25 year
conemu 12 year

but never see this effects.

WT I try use ~week ( i dont like UWP)

**Comment by Zeroes1** [comment]
options on my FAR Manager:

 [x] Use Virtual Terminal for rendering
 [x] Fullwidth-aware rendering
 [ ] ClearType-friendly redraw (can be slow)

**Comment by carlos-zamora** [comment]
@alabuzhev have you seen reports of this recently?

**Comment by alabuzhev** [comment]
I saw something like this a few years ago. That time it was conemu hooking some functions and sending these sequences instead of expected input.

I suggest removing all conemu dlls from far\plugins first, if not yet. It could be that some hooks stay active even when you're not using it explicitly.

**Comment by Zeroes1** [comment]
if try record program Bandicam
 area: area around cursor -> full screen
[WT+Far+folow the mouse record in bandicam.mp4.zip](https://github.com/microsoft/terminal/files/11759688/WT%2BFar%2Bfolow.the.mouse.record.in.bandicam.mp4.zip)

 we can see many codes in far console

**Comment by Zeroes1** [comment]
i check fresh Far30b6164.x64.20230615.7z
problem still exist
i check process
Far.exe
OpenConsole.exe

**Comment by carlos-zamora** [comment]
Thanks for filing. We're going to mark this as a /dup of #15540.

**Comment by Zeroes1** [comment]
Supposedly the problem has gone away with Microsoft.WindowsTerminalCanary_latest_x64.zip terminal-1.20.3491.0
first day use after preview 1.19.2311.13002 where problem exist too...
