### ISSUE TITLE
Trying elevated WT does not open

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/terminal#15532]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19041.685

### Other Software

I've been opening WT elevated for quite some time and it has been working fine up until today. It was working just yesterday. Now it seems it will not open. Prompts me for the elevated, but no window is opening. Actually, it has also been prompting me _unknown program_ when I do, not sure why that is either, may or may not be related. Having scanned some of the tech forums as well, some suggest that, _this is the point of WT, that you need Administrator access to run it, so do not need to elevate it_, but this is inaccurate. Some processes you still need an elevated CL in order to do anything with them sometimes, especially if you are doing anything process level, which I sometimes do. So force of habit, I just generally open it that way.

### Steps to reproduce

Simply this, `CTRL+SHIFT` click the taskbar, or `CTRL+SHIFT+WIN+(pos)` depending on the position.

### Expected Behavior

I expect the WT to open elevated with the first configured CL.

### Actual Behavior

Apparently, nothing. Ghosted. No window whatsoever is being opened elevated.

**Comment by thomas-berg** [comment]
I experience the same thing, I added my crash report to this issue: https://github.com/microsoft/terminal/issues/15526

**Comment by carlos-zamora** [comment]
Hi @mwpowellhtx. Thanks for filing! We're going to mark this as a /dup of #15526. We'll revisit that one in a bit. Thanks again!

**Comment by mwpowellhtx** [comment]
Cautiously optimistic, sounds promising. Thanks!
