### ISSUE TITLE
Set the Windows Terminal as the “Default terminal applications" not work with administrator privileges.

### ISSUE THREAD

**Issue by fuchanghao** [microsoft/terminal#15546]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19044.3086

### Steps to reproduce

log in windows 10 as normal user account.

set the Windows Terminal as the “Default terminal applications" 

Test1:

  create a simple "test.cmd"

```
cd /d c:\
pause

```

right click "test.cmd" and choose: "Run as  administrator".

Test2:

double-click a cmd file which has “administrator elevation request” codes.

Test3:

log in as system build-in "Administrator" account and do the Test1 and Test2 again.

Test4:

1.log in as system build-in "Administrator" account.
2.open "Group Policy" and enable "User Account Control: Admin Approval Mode for the Built-in Administrator account" :  https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-admin-approval-mode-for-the-built-in-administrator-account
3.Do the Test1 and Test2 again.

### Expected Behavior

When I right click "test.cmd" and choose: "Run as  administrator" or run a cmd file which has “administrator elevation request” codes.

After the UAC pop-up, It will open an "Administrator: Command Prompt" Tab on Windows Terminal to run the codes.

### Actual Behavior

For Test1 and Test2:

It opens a conhost.exe and run the codes.

For Test3

It opens an "Administrator: Command Prompt" Tab on Windows Terminal to run the codes.

For Test4:

It opens a conhost.exe and run the codes again.

I don't know why the same  “Default terminal applications" setting cause different results.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10276 for more discussion.

/dup #10276
