### ISSUE TITLE
Dropdown menu Stuck

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/terminal#15545]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

![image](https://github.com/microsoft/terminal/assets/23334732/dff15a24-aef3-4e20-bdf1-6b5f5cad6037)
![image](https://github.com/microsoft/terminal/assets/23334732/02110b86-b311-4f96-82f4-8bda05e4842e)

### Steps to reproduce

1. Edit `settings.json`

```json
"newTabMenu": [
    { "type": "remainingProfiles" },
    {
      "type": "folder",
      "icon": "E:/photo/g4.ico",
      "name": "自建",
      "entries": [
        {
          "name": "阿里云",
          "type": "matchProfiles"
        },
        {
          "name": "dell",
          "type": "matchProfiles"
        },
        {
          "name": "树莓派",
          "type": "matchProfiles"
        },
        {
          "name": "NUC",
          "type": "matchProfiles"
        },
        {
          "name": "g4",
          "type": "matchProfiles"
        }
      ]
    },
    {
      "type": "folder",
      "icon": "E:/photo/jbr.png",
      "name": "lcy",
      "entries": [
        {
          "name": "assist-manage",
          "type": "matchProfiles"
        },
        {
          "name": "测试服",
          "type": "matchProfiles"
        }
      ]
    }
  ],
```

2. Open terminal.

https://github.com/microsoft/terminal/assets/23334732/0cfd9dec-b938-48d5-b9db-4f8cad5c6f02

### Actual Behavior

Silky~~~~~~~

**Comment by lhecker** [comment]
The video is really helpful! Unfortunately, I don't quite understand what you mean with "stuck" and "silky". Could you describe the problem in more detail?

**Comment by zadjii-msft** [comment]
Does this repro with any other WinUI-like dropdowns elsewhere in the OS/? The WinUI Controls Gallery app is a great example. Or when right-clicking on the History in `calc`:
![image](https://github.com/microsoft/terminal/assets/18356694/e40ffdd9-4c11-4877-b9b0-782b38a857f7)

**Comment by lengyuxuan** [comment]
> The video is really helpful! Unfortunately, I don't quite understand what you mean with "stuck" and "silky". Could you describe the problem in more detail?

The dropdown menu is slow response, I hope it can be smoother.

**Comment by lhecker** [comment]
> The dropdown menu is slow response, I hope it can be smoother.

I see! Thanks for the clarification. 🙂

Is the drop-down menu also slow in other applications, as @zadjii-msft mentioned?
And what happens if you remove the two `"icon"` keys from the setting?

**Comment by lengyuxuan** [comment]
> > The dropdown menu is slow response, I hope it can be smoother.
> 
> I see! Thanks for the clarification. 🙂
> 
> Is the drop-down menu also slow in other applications, as @zadjii-msft mentioned? And what happens if you remove the two `"icon"` keys from the setting?

Remove `"icon"` was ineffective，I try it as @zadjii-msft mentioned：

https://github.com/microsoft/terminal/assets/23334732/cb8520f0-0211-4f17-8dfd-d215cd5afe7a

**Comment by lhecker** [comment]
At least in your video recording, it looks about as "smooth" as the animation in Windows Terminal.

**Comment by carlos-zamora** [comment]
Hi @lengyuxuan. Thanks for filing. This issue would be better suited for the https://github.com/microsoft/microsoft-ui-xaml repo.

Thanks again, and closing as resolution-external.
