### ISSUE TITLE
Passing hotkeys to apps that use them

### ISSUE THREAD

**Issue by j-xella** [microsoft/terminal#15558]
# Description of the new feature/enhancement

ATM, action hotkeys are configured for the whole terminal window. There is a lot of  available actions, and a lot of hotkeys are used by default. Those hotkeys are useful, especially when I work with a command line only. 

However, there is a number of TUI programs that are designed to respond to multiple hotkeys. As an example, far manager on Windows; or, on Linux, we have Midnight Commander. They are designed to respond to multiple hotkeys, but if a hotkey is assigned to some terminal action, the program does not receive it any more.

As a result, it would be great to be able to control the available mappings in a quick and convenient way, depending on what I am doing at the moment.

# Proposed technical implementation details (optional)

Multiple solutions are possible. For example:

* an action to temporary disable/enable/toggle (almost?) all hotkeys.
* Action hotkeys could be configured on per-profile basis, like colour schemes. Then, depending on the profile of the active pane, different hotkeys are used.

Note that, even when most of the hotkeys are disabled, it would still be great to have an alternative way to access actions. For example via configurable context menu, or something like `wt.exe action {xxx}`

**Comment by lhecker** [comment]
This is somewhat similar to #11084.

**Comment by zadjii-msft** [comment]
or even:
* #9301
* #5790

**Comment by carlos-zamora** [comment]
Hi @j-xella. Thanks for filing and the details. A lot of this is covered over in #5790, so we're going to mark this as a /dup of #5790 and consolidate them. Thanks again!
