### ISSUE TITLE
Git Bash not added automatically

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/terminal#15559]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3086

### Other Software

Git 2.41.0

### Steps to reproduce

1. Install Terminal from Windows Store or via winget (winget repo)
2. Start Terminal
3. Look at list of profiles

### Expected Behavior

Git Bash profile is picked up automatically.

It did so on my other computers (Win11).

### Actual Behavior

No Git Bash on the list but it does have WSL distros.

**Comment by DHowett** [comment]
Thanks for reporting this!

Git for Windows has an option in the installer to enable automatic Terminal integration.

<img width="383" alt="image" src="https://github.com/microsoft/terminal/assets/189190/33731e41-c9df-4487-b2f2-76ba4e0e6ec3">

We have stopped adding new automatically-detected profiles for the time being, and Git is using one of our supported interfaces for adding new profiles :smile:

**Comment by mwisnicki** [comment]
I'm using winget so that's probably why I miss this.

Would it be safe for Git to always register even if terminal is not installed (i.e. have this on by default in git package)?

**Comment by DHowett** [comment]
Absolutely, it would be safe for them to register all the time.

Tech Details:

All it does is put a JSON file in a specific location, either `%ProgramData%\Microsoft\Windows Terminal` or `%LOCALAPPDATA%\Microsoft\Windows Terminal`.
