### ISSUE TITLE
Gitbash is taking forever to show promomt with the latest update (Version: 1.17.11461.0)

### ISSUE THREAD

**Issue by kasingal** [microsoft/terminal#15550]
### Windows Terminal version

Version: 1.17.11461.0

### Windows build number

Microsoft Windows [Version 10.0.22000.1936]

### Steps to reproduce

Install Git For Windows (git version 2.40.1.windows.1) and launch windows terminal -> open git bash tab

### Expected Behavior

It should show prompt with current directory or $

### Actual Behavior

It takes forever to show prompt.

**Comment by DHowett** [comment]
The latest update of Windows Terminal, or the latest update of "Git for Windows"?
