### ISSUE TITLE
Enhance text editing experience on WindowsTerminal

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/terminal#15555]
#### List of Issues/PRs that could further enhance text editing experience/rendering on Windows Terminal:

- #7228 : Support for styled underlines, Eg. undercurl, dashed-line.

  Left: Windows Terminal, Right: WezTerm(over ssh)

  ![Screenshot 2023-06-13 140152](https://github.com/microsoft/terminal/assets/55626797/c6cabf6f-0d74-4f12-8280-0273cda31ac7)

  *ssh'ing bypasses ConPty and avoids the stripping of `SGR 4:x` VT sequence*

- #5897 : After #14255, if you change the default line height you might see gaps between BoxDrawing and  BlockElement glyphs at the moment.

  Left: Windows Terminal, Right: WezTerm

  ![image](https://github.com/microsoft/terminal/assets/55626797/2af347ae-41eb-49c4-b100-078c8c9451fa)

- Support coloring underlines independent of foreground text color:  Currently same color is applied to both the text and the underline.
  *Haven't seen any open issue for this yet :/*. 

I'll add more if something's missing.

**Comment by zadjii-msft** [comment]
similar: #6879

Do you have any links to reference docs for

> Support coloring underlines independent of foreground text color: Currently same color is applied to both the text and the underline

**Comment by lhecker** [comment]
Kitty allows setting the underline color: https://sw.kovidgoyal.net/kitty/underlines/

**Comment by j4james** [comment]
FYI, we were already kind of tracking the underline color as part of #7228.

**Comment by carlos-zamora** [comment]
@tusharsnn Thanks for aggregating all of these into one place! 😊

**Comment by tusharsnx** [comment]
Happy to close this. It took us less than one year to get all three together 😄
