### ISSUE TITLE
Terminal failed to build on MSVC on Windows with error: error C3861: '_vsnwprintf_s': identifier not found

### ISSUE THREAD

**Issue by KawasakiNinjaH2R** [microsoft/terminal#15562]
### Windows Terminal version

v1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

VS2022 + Windows 10

### Steps to reproduce

1. Download the attachment file: main.zip and unzip it.
2. Open x64 Native Tools Command Prompt for VS 2022.
3. CL.exe /c /Zi /nologo /W4 /WX /diagnostics:column /sdl /MP /O2 /Oi /GL /Zc:preprocessor /Gm- /EHsc /MT /GS /guard:cf /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /std:c++20 /permissive- /external:W4 /Gd /TP /wd4201 /wd4312 /wd4467 /wd5105 /wd26445 /wd26813 /FC /errorReport:queue /we4189 /we4100 /we4242 /we4389 /we4244  /utf-8 /Zc:externConstexpr /Zc:lambda /Zc:throwingNew /fp:contract main.i

### Expected Behavior

build success

### Actual Behavior

F:\gitP\microsoft\terminal\src\tools\RenderingTests\main.cpp(69,25): error C3861: '_vsnwprintf_s': identifier not found [F:\gitP\microsoft\terminal\src\tools\RenderingTests\RenderingTests.vcxproj]
[main.zip](https://github.com/microsoft/terminal/files/11768388/main.zip)

**Comment by KawasakiNinjaH2R** [comment]
Thanks for your information! I add :

`#include <corecrt_wstdio.h>`

to main.cpp, it can be compiled successfully!

**Comment by lhecker** [comment]
I also hit this issue now after upgrading Visual Studio! I wonder if it's because the STL got updated? In any case I just added `<cstdio>` as an include and it works. I'll add it to a future PR.
