### ISSUE TITLE
cmd: Pressing tilde inserts unexpected character

### ISSUE THREAD

**Issue by thernstig** [microsoft/terminal#1556]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce
1. Using a Swedish QWERTY keyboard (not sure if it matters)
2. Open cmd
3. Pressing `AltGr + tilde key + s` gives this output: `C:\Users\foo>¨~s`

# Expected behavior
I expected it to give this output: `C:\Users\foo>~s`

# Actual behavior
It somehow adds `¨` inbetween which should only happen if I press `Shift + same button`

Swedish QWERTY reference: https://upload.wikimedia.org/wikipedia/commons/e/e0/KB_Sweden.svg

**Comment by DHowett-MSFT** [comment]
Okay, you have opened three bugs about AltGr
