### ISSUE TITLE
Make large numbers easier to read

### ISSUE THREAD

**Issue by mlongtin0** [microsoft/terminal#15563]
# Description of the new feature/enhancement

Large numbers like "16000000" are hard to read in a monitor. Is it 1.6, 16 or 160 millions? I end up trying to select groups of three to make sense of it.

I would like to propose to italicize or bold alternating groups, like this: 16<i>000</i>000 or 16<b>000</b>000
This would be enough to make it easier to read. The grouping should be customizable.

# Proposed technical implementation details (optional)

**Comment by mlongtin0** [comment]
I deal with large numbers all the time, the basic tools don't format, so I end up having to pipe through a number formatter. Even the default Excel is painful that way.

A less niche version would be some sort of regex transform that's applied to the display. It could be used to always put ERROR in bold and red, for example.

**Comment by zadjii-msft** [comment]
> A less niche version would be some sort of regex transform that's applied to the display. It could be used to always put ERROR in bold and red, for example

Thats in #5916. dunno if the spec I have in progress would adequately cover this tho

**Comment by mlongtin0** [comment]
Correct. Duplicate of https://github.com/microsoft/terminal/issues/6297.
