### ISSUE TITLE
Setting Terminal to default terminal app causes blank screen when running bat file

### ISSUE THREAD

**Issue by ToxicSmurf** [microsoft/terminal#15561]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Settings > Default terminal application > Windows Terminal Preview
Run (any) .bat file

### Expected Behavior

.bat file to run

### Actual Behavior

![error](https://github.com/microsoft/terminal/assets/97206988/664a7aad-4317-4a0c-b681-82efc59e9fe3)

![error 2](https://github.com/microsoft/terminal/assets/97206988/098bb10e-5309-481f-9d3c-af1a5bf8f3f7)

**Comment by lhecker** [comment]
I think it's unlikely that any .bat file would run into this issue. After all, your screenshot shows an application error in pwsh.exe and .bat files are for cmd.exe. Could you provide us with a .bat file that reproduces the issue?

**Comment by ToxicSmurf** [comment]
https://gist.github.com/ToxicSmurf/85923e79b8c2a9849bf6c525be504eec

**Comment by ToxicSmurf** [comment]
I added the second `updater.bat` file because the error was occurring when I tried to run it as well. You're right, though; it wasn't a Windows Terminal bug. My bad 😭 I had my `ComSpec` environment variable pointed to `pwsh.exe` for some reason. Reverting that fixed the issue. Sorry!
