### ISSUE TITLE
Strange "toolbar" appears when entering emoji using Win+.

### ISSUE THREAD

**Issue by davidwin** [microsoft/terminal#1557]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal 0.2.1715.0 (Store)
```

# Steps to reproduce

1. In a shell (WSL, CMD, or PowerShell), open the Emoji picker by pressing Win+(period).
2. Start typing to search for an emoji, or click an emoji.
3. In the upper left of the screen a Windows 2000-style "toolbar" appears with a squashed emoji in black-and-white and a green arrow.
![Anteckning 2019-06-24 215637](https://user-images.githubusercontent.com/9844625/60047843-ffc26180-96ca-11e9-8aa2-116d7d82a976.png)

# Expected behavior

3. Clicking the emoji or pressing Enter inserts the emoji in the terminal

# Actual behavior

3. Clicking the emoji or pressing Enter has no effect.
4. Clicking the green arrow to insert the emoji (?)

**Comment by DHowett-MSFT** [comment]
#459
