### ISSUE TITLE
[Building] settings.json also hides packages from intellisense's includePath

### ISSUE THREAD

**Issue by tusharsnn** [microsoft/terminal#15578]
### Windows Terminal version

Dev

### Windows build number

10.0.22621.0

### Steps to reproduce

1) Clone repo.
2) Install all dependencies. (*Ensure nuget `packages/` is populated*)
2) Open project dir in VScode

![image](https://github.com/microsoft/terminal/assets/55626797/782d341b-f3b8-4e43-83d7-639ed6a12497)

### Expected Behavior

All packages' headers are included automatically.

![image](https://github.com/microsoft/terminal/assets/55626797/e76c032e-b6c9-4057-a407-75ca64519e3e)

*reopen VSCode after making the changes for settings to take effect*

### Actual Behavior

Includes/headers under `packages/` are ignored by VSCode LSP.

**Comment by tusharsnn** [comment]
*`settings.json` is the one that comes with the source [here](https://github.com/microsoft/terminal/blob/b8f402f64bf50e75148da84e9c42404ad3bdbb87/.vscode/settings.json#L106).*

**Comment by lhecker** [comment]
If you'd like to submit a PR that improves the excludes, I'd be happy to merge it asap! 🙂

**Comment by tusharsnn** [comment]
> If you'd like to submit a PR that improves the excludes, I'd be happy to merge it asap! 🙂

sure, I'll do that.

**Comment by zadjii-msft** [comment]
Maybe we put it there when we had boost in our packages and didn't want that all getting parsed? I don't entirely remember.

IIRC @Jaswir was also looking at this, so this might be of interest to them. Dunno if they ever figured that out.
