### ISSUE TITLE
Alt+ key combinations not being registered

### ISSUE THREAD

**Issue by lszinv** [microsoft/terminal#15574]
### Windows Terminal version

 1.17.11461.0

### Windows build number

 10.0.22621.1848

### Steps to reproduce

All interactions using the Alt key are behaving as if the Alt key wasn't pressed. I was previously on Windows 10 and the version of Windows Terminal was behaving fine, but I just updated to Windows 11 and can no longer send the Alt key to the terminal. I've tried changing the AltGR aliasing option to no avail. 

I've also gone and removed all existing shortcuts that included Alt as a key from Settings>Actions

For example in bash:
alt+b / alt+f to move cursor backwards/forwards words

### Expected Behavior

Expected behaviour when passing in alt+b should move backwards by a word, and alt+f should move forwards by a word

### Actual Behavior

Alt+b just inputs b into the CLI
Alt+f does nothing. Seems to be getting captured elsewhere

The desired behaviour works if I use `ctrl+[` instead of Alt.

**Comment by lhecker** [comment]
This works fine for me on Windows 11 with Windows Terminal 1.17. What keyboard layout are you using? Can you install `showkey` and run it as `showkey -a`? If you press a key like Alt+B it should show this:
```
^[b      27 0033 0x1b
         98 0142 0x62
```

**Comment by lszinv** [comment]
Turns out my keyboard was faulty. I reflashed my fw on it and the issue went away.

**Comment by DHowett** [comment]
Thanks for letting us know!
