### ISSUE TITLE
Profile icons whose paths are remote URLs do not display their icons Windows taskbar

### ISSUE THREAD

**Issue by felipecrs** [microsoft/terminal#15581]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22631.1900

### Steps to reproduce

Set the profile icon to be https://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png.

### Expected Behavior

I believe Terminal should cache the icon internally and then work the same way when referring to local icons.

### Actual Behavior

Notice it works within the Terminal, but the icon doesn't show up in when right-clicking Terminal in the taskbar:

![WindowsTerminal_Yq0DUaOicj](https://github.com/microsoft/terminal/assets/29582865/5d699482-2867-40a1-917a-00d36b84559e)

**Comment by carlos-zamora** [comment]
Hi @felipecrs. Thanks for filing. We're going to mark this as a /dup of #15556.
