### ISSUE TITLE
wsl 1: Inserting | character does not work on Swedish QWERTY keyboard

### ISSUE THREAD

**Issue by thernstig** [microsoft/terminal#1558]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
wsl 1, Ubuntu 18.04
bash
```

# Steps to reproduce
1. Using a Swedish QWERTY keyboard (not sure if it matters)
2. Open wsl 1 (Ubuntu 18.04)
3. Pressing `AltGr + |` somehow adds the first thing I have in my bash history at the line.

# Expected behavior
I expected it to give me a `|` character.

# Actual behavior
I start with `mycomputer ~/codeA/ (master)$ asd` then press `AltGr + |` which replaces the entire line with `mycomputer ~/codeA/ (master)$ less .bashrc  `

Swedish QWERTY reference: https://upload.wikimedia.org/wikipedia/commons/e/e0/KB_Sweden.svg

**Comment by DHowett-MSFT** [comment]
#521 contains the name "altgr", and i bet it's literally this issue. Please search first!

**Comment by thernstig** [comment]
@DHowett Apologies, I did search for quite some keywords, but not for AltGr but rather tilde which was the first thing I had problem with, so my follow-up issues didn't make me consider searching again. My bad, but at least I spent time trying to write good issues :taco:

**Comment by DHowett-MSFT** [comment]
Nah, it's no big deal. It's just our most reported issue, so I've become a little snippy about responding to it. I went ahead and pinned the official altgr issue so that it's easier to find, and re-titled it :smile:
Thanks!
