### ISSUE TITLE
SkipCommand and SendSequence like vscode?

### ISSUE THREAD

**Issue by leolbyy** [microsoft/terminal#15585]
# Description of the new feature/enhancement

Currently Windows Terminal does not allow arbitrary keybindings when connecting to linux server or using WSL2 on Windows. For example, currently I don't see a way to set alt+d / win+d to logout when connecting to linux CLI. VSCode however can achieve that by SkipCommand and SendSequence (set alt+d to send sequence of text "\u0004"). Would be nice if Windows Terminal can do the same. (For SkipCommand, just let the system handle the keybindings)

**Comment by lhecker** [comment]
Both of these already exist. For SendSequence you can use:
```json
{
  "command": {
    "action": "sendInput",
    "input": "\u0004"
  },
  "keys": "alt+d"
}
```
For SkipCommand you can use:
```json
{
    "command": "unbound",
    "keys": "alt+d"
}
```

They're documented here: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions

**Comment by DHowett** [comment]
There is no concept of a "system" shortcut here. Everything is handled by either the terminal emulator or the console infrastructure underneath it :)

That means:

1. If something is bound, Terminal handles it. Always.
2. If something is `unbound`, Terminal passes it down to the console infrastructure. _Always._
   * The console infrastructure gets the first say in what happens after this.
   * It handles translating, e.g. turning a Right Arrow key into `VK_RIGHT` or `\e[C`
   * It handles the termination signal, _which cannot be changed_ from `0x03` (<kbd>Ctrl+C</kbd>)

Perhaps somewhat puzzlingly, I think you can effectively disable <kbd>Ctrl+C</kbd> by putting it in the first category... with an action that does nothing (such as `sendInput` with no input (!))

**Comment by leolbyy** [comment]
Yeah.. `sendInput` without input (null) is exactly the thing I tried but get rejected as input is a required parameter.

Actully "Ctrl+C" is bounded to copy in default setting.json but it still get passed down to WSL.

Seems like it's being handled both by terminal **and** WSL. (But maybe terminal only handle it when under text selection? I'm not sure just guessing)

**Comment by DHowett** [comment]
> If there isn't, maybe this should be converted into a request for one

Fair enough.

I would not be too inclined to have a "disable this key forever" key binding. I can't see a use case for it and I wouldn't necessarily take a pull request that added it. It would be a special case (we don't want to show it in the command palette, for example...) for little gain.

@leolbyy what specific thing are you trying to accomplish?

**Comment by leolbyy** [comment]
I want it just for customized keyboard shortcut. I grow up with Windows XP and ctrl+c is simply the shortcut the use the most. 

Therefore I want to change interruption to alt+c and disable ctrl+c and meantime it helps keep the layout roughly the same as Mac.

If there is such functionality, it will allow user to arbitrary keybindings.

**Comment by carlos-zamora** [comment]
Hi @leolbyy. Thanks for filing and the continued discussion. After a bit of discussion on the team, we're ok with the idea of making the keyboard shortcuts configurable, but not with the `SkipCommand` action aspect.

We're going to track making all of the line discipline keybindings configurable in a different issue. @lhecker will create it and post the link in this issue :)

**Comment by lhecker** [comment]
I opened #15629 now. 🙂
