### ISSUE TITLE
The "Find" window cannot be opened due to default shortcut key conflicts

### ISSUE THREAD

**Issue by BlueRain-debug** [microsoft/terminal#15598]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19045.3086 and 10.0.23486.1000

### Other Software

Microsoft Pinyin Input Method

### Steps to reproduce

Ctrl+Shift+F

### Expected Behavior

Open a "Find" window.

### Actual Behavior

The shortcut key to open the "Find" window used by Windows Terminal is "Ctrl+Shift+F", which is exactly the same as the default "Simplified/Traditional Switch" shortcut key of the Microsoft Pinyin input method for a long time, which will cause the shortcut key to be entered by the system cannot be captured and the Find window cannot be opened correctly.

**Comment by carlos-zamora** [comment]
Adding "Spec needed" for this. We want to make sure the solution we come up for this is done right.

In the meantime, you should be able to reconfigure the keybinding for "Find".

**Comment by carlos-zamora** [comment]
Circling back to this. It seems like it makes the most sense to keep this as Ctrl+Shift+F, but yeah, you're welcome to reconfigure the keybinding in your settings to prevent the conflict. Closing. Thanks!

**Comment by BlueRain-debug** [comment]
> Circling back to this. It seems like it makes the most sense to keep this as Ctrl+Shift+F, but yeah, you're welcome to reconfigure the keybinding in your settings to prevent the conflict. Closing. Thanks!

Is it possible to provide a notification when a conflict is detected? Otherwise, many users may not realize that a key combination conflict exists even in msft's default config.
