### ISSUE TITLE
wsl: Able to erase prompt characters one-by-one on Swedish QWERTY keyboard

### ISSUE THREAD

**Issue by thernstig** [microsoft/terminal#1560]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
wsl 1, Ubuntu 18.04
bash
```

# Steps to reproduce
1. Using a Swedish QWERTY keyboard (not sure if it matters)
2. Open wsl 1 (Ubuntu 18.04) using bash
3. Pressing `AltGr + ~` lets me later press backspace to erase one character from my prompt.

# Expected behavior
To only erase the last character

# Actual behavior
```bash
mycomputer ~/code/$
<pressing AltGr + ~ + s>
<pressing three backspaces>
mycomputer ~/code/
<pressing AltGr + ~ + s>
<pressing three backspaces>
mycomputer ~/code
<pressing AltGr + ~ + s>
<pressing three backspaces>
mycomputer ~/cod
<pressing AltGr + ~ + s>
<pressing three backspaces>
mycomputer ~/co
etc.
```

Swedish QWERTY reference: https://upload.wikimedia.org/wikipedia/commons/e/e0/KB_Sweden.svg

**Comment by DHowett-MSFT** [comment]
This is **also** #521
