### ISSUE TITLE
Restoring WT with Win-D does not restore input focus

### ISSUE THREAD

**Issue by geril2207** [microsoft/terminal#15609]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Open wt
2. Press `<Win-d>` to hide all windows
3. Again press `<Win-d>` to open all windows
4. Focus wt without mouse(Alt-tab) or it should be focused.
5. Make something(type, wt command).
6. Click on wt window by mouse
7. Type smth.

### Expected Behavior

Should execute typing/commands after 2-nd `<Win-d>`

### Actual Behavior

Doesn't execute anything untill you dont press on wt by mouse.

**Comment by lhecker** [comment]
In other words: After using Win+D twice the input focus is lost. I've updated the title to reflect that. 🙂

**Comment by geril2207** [comment]
@lhecker, yeah thanks, maybe this somehow related to #13388

**Comment by carlos-zamora** [comment]
Good catch! We'll mark this as a /dup of #13388 then. Thanks!
