### ISSUE TITLE
Feature Request: Restart/reload terminal via a new command name

### ISSUE THREAD

**Issue by thernstig** [microsoft/terminal#15617]
# Description of the new feature/enhancement

https://github.com/microsoft/terminal/pull/14060 implemented long-awaited support to press Enter to restart when a terminal process has exited. Yet sometimes, my terminal prompt is frozen after breaking internet connection, but it takes quite some time before the text prompt comes up (telling me to press Enter.

It would be nice if there was a terminal command to do the same thing. So that I can press ctrl+shift+P and select `Restart` which would be the same as pressing Enter in the other case.

**Comment by lhecker** [comment]
The way you sau "after breaking internet connection" makes me believe that you're talking about SSH. Is that correct? In that case check out the "official" way to break out of such a connection: https://superuser.com/a/1251011

**Comment by zadjii** [comment]
I'm pretty sure I also added a manual "restart this connection" action in 1.18

**Comment by thernstig** [comment]
If you added that @zadjii that is great and solves it. I am not using the preview version.

**Comment by zadjii-msft** [comment]
Alright yea this was added to 1.18 in #15241. Thanks!

/dup #3726
