### ISSUE TITLE
caps lock somehow 'on' yet keyboard shows it off

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#15610]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.1848

### Steps to reproduce

No clue. I'm just using the terminal, splitting the panes, running docker commands etc and sometimes this happens with this preview version

### Expected Behavior

i expect when my caps lock is off, that my caps lock is off... bug is self evident

### Actual Behavior

caps lock is on, when caps lock is NOT on.  I just went to make a screen capture and it somehow resolved itself... so that's fun... if i can record a gif I will.

**Comment by lhecker** [comment]
In which application and under which circumstances did this bug occur?
It's at least somewhat unlikely to be a bug in this project. While we do handle uppercase/lowercase flags in various parts of the code, we don't really convert the letter case of the actual text anywhere.

**Comment by dovholuknf** [comment]
Yeah it's really strange. It's just bash running. I'll run a docker command, ctrl-c, run another, switch panes, that sort of thing and then i'll start typing AND ALL CAPS POPS OUT. 

The ONLY reason I reported it is because it __seems__ to come around the strange "bell when changing windows" bug (if you recall that one) where when my mouse moves from one pane to another the "bell" dings audibly and visually when leaving the frame. After that I make a new pane (cause it never stops ding'ing) and that new pane seeeeems to have the caps locked on it? maybe? I wish I could just have a screen recorder on fulltime to capture that exact moment.... :/

Anyway, it's become kinda annoying and it seems to be a new issue I've not ever had before... Lots of "unhelpful" info here, I know... If i can narrow it down at all, i'll post back

**Comment by dovholuknf** [comment]
Actually, you can watch it happen to me. I was livestreaming yesterday and I was just reviewing that stream now for some information when i heard 'the bell' pop, and then i see my caps lock got toggled. You can see me look down at the keyboard and hit capslock once/twice to un-caps lock...

https://www.twitch.tv/videos/1856211857 you'll need to scrub over to 19:20... I did the following:

* docker run --rm crccheck/hello-world (a simple docker container that just lets you curl the 'docker whale'
* I used "shift-alt-minus" to make a new pane under the one i was just working on.
* I started typing 'curl' but you can see "URL" comes out
* I notice URL and try to hit ctrl-c to cancel what i was doing and just start typing again but you hear the bell and you see the screen flash (audible bell)
* i keep typing: `curl http://localhost` and at that very moment you see the caps lock togggle over and i type LOCAL
* I notice LOCAL and say "what is going on" and look down at my keyboard confused, and toggle the caps lock button a couple of times to clear/reset the caps lock....

**Comment by carlos-zamora** [comment]
Curious, can you get this to repro in the original windows console host?

**Comment by dovholuknf** [comment]
No. I don't even know what/how it happens in windows terminal. However, an interesting (maybe) bit of more information is that `docker` is somehow causing the "bell bug". I happened to be using docker in a VM (because sadly, WSL still doesn't have bridged networking) and was using `tilix` there with split windows, just like I do with windows terminal and i had "the bell bug" hit the VM too. That was entirely unexpected. I have __absolutely__ no idea how to reproduce the bell bug, nor how to reproduce the bizzare "caps lock suddenly comes on".  

I only filed this bug on a whim that someone else has the situation happen to them. Since I can't reproduce the bug, I'm sure this bug will just sit out here and go stale, but we'll see if anyone else hits this.

**Comment by j4james** [comment]
I wonder if this has something to do with the fact that you're using a keyboard shortcut with the <kbd>Shift</kbd> modifier, and there's a change of context happening at the same time, i.e. the keydown events are going to the initial pane, but the keyup events go to the new pane.

Maybe that results in the <kbd>Shift</kbd> key getting "stuck" somehow, which gives the impression that <kbd>CapsLock</kbd> is enabled. You can fix this temporarily by pressing <kbd>CapsLock</kbd>, since that will cancel out the <kbd>Shift</kbd>. However, the next time you press <kbd>Shift</kbd> (e.g. for the `:` in the URL), that's going to release the stuck key, and since you've now got <kbd>CapsLock</kbd> enabled, everything is going to be uppercase again.

Why it's getting stuck in the first place, I'm not sure. But the next time this happens I'd suggest hitting <kbd>Shift</kbd> a few times to try and reset it, rather than messing with <kbd>CapsLock</kbd>. I suspect that will work better.

**Comment by carlos-zamora** [comment]
Slapping Needs-Author-Feedback to hear back from your experience with j4james' suggestion

**Comment by dovholuknf** [comment]
I actually thought I had replied my bad. I've been trying to reproduce it and cannot. I like what @j4james is thinking, that could make sesne. I will close this issue for the timebeing and reopen it if I notice it happen again and I'm able to capture/reproduce. thanks

**Comment by dovholuknf** [comment]
This actually just happened to me again today. i tried to record a gif of it but apparently when terminal lost focus, or when i came back to a different pane in terminal it 'fixed itself'... it's the first time in a while this has happened...

**Comment by dovholuknf** [comment]
it's happened again. it's definitely tied to the "open a new window" shortcut key. i use "shift+alt+`-`" all the time to make a new windows. i recorded my experience from my phone this time. as soon as i leave the app and give the app the focus again the issue is fixed.

pressing caps lock does not fix the issues. `-` key comes out as "_", `=` key comes out as `+`. I can upload the video if you like but I'm not sure it matters. it's hard to reproduce

**Comment by j4james** [comment]
> pressing caps lock does not fix the issues

My suggestion was that you press the <kbd>Shift</kbd> key to try and fix it.
