### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by svecko** [microsoft/terminal#1561]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version: 0.2.1715.0
```

# Steps to reproduce

Press and hold Alt Gr + 1, 2, 3, 4, 5, 6, 7 (each number separately and in order).

# Expected behavior

Terminal should print some special characters depending on your keyboard layout.

# Actual behavior

Terminal prints: digit-argument: 1 when you press Alt Gr + 1, digit-argument: 12 when you press Alt Gr + 2, ..., digit-argument: 123456 when you press Alt Gr + 6, but when you press Alt Gr + 7 it starts printing "_^" symbols in infinity loop.

**Comment by DHowett-MSFT** [comment]
**please search for existing issues first** this is #521
