### ISSUE TITLE
Feature Request reaorganize tabs

### ISSUE THREAD

**Issue by julsburgs** [microsoft/terminal#1562]
I would like to be able to   reorganize the tabs and move one to  the left or right just like a browser

**Comment by DHowett-MSFT** [comment]
#1256  #443

**Comment by paradonym** [comment]
also to have a sort of way to manage many open tabs... If I have 3 WSL tabs 1 cmd and two powershells tabbed it get's out of the UI at the right side of the tab bar (so I can't close the last tabs unless I close the first ones).

**Comment by DHowett-MSFT** [comment]
@paradonym Okay, put that request into one of the bugs I linked above?
