### ISSUE TITLE
Using a separate config file or path to save ColorSchemes.json

### ISSUE THREAD

**Issue by kylinholmes** [microsoft/terminal#15627]
# Description of the new feature/enhancement

Many users like to change their preference of terminal, and the current way of setting and store `ColorSchemes.json` is a litte bit unconverience.

Now, if I wanna to try a **NewStyle**, I only need to copy content and paste it into the section of schemes in `settings.json`.
However, when I downloading a [collection of shcemes](https://github.com/mbadolato/iTerm2-Color-Scheme), the way above is unconfortable, cause I don't wanna to repeat it like 100 times.

Whats more, iTerm2 have a quicker way to get the preview of scheme.

# Proposed technical implementation details (optional)

My suggestion is using a specific dir like `~/.WindowsTeriminal/colors/` to save all `ColorSchemes.json`, which will more easier to download, to add.

When launching WindowsTerminal, reading all `*.json` in the above dir automaticlly.
which will also be easier to find or udpate content in each `*.json`

**Comment by carlos-zamora** [comment]
Thanks for filing! A few notes:
- Saving settings to a different location is something we've talked about in the past. I can't find an open issue on it though, so I'll just use this to track it for now.
- Fragments are a solution to this problem, actually! You can introduce new color schemes via JSON fragment extensions. Read more about it here: https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions
- Overall, we want to invest in the Settings UI to make this a non-issue. We're tracking all our major investments in the Settings UI here: #10000

**Comment by zadjii-msft** [comment]
> Saving settings to a different location is something we've talked about in the past. I can't find an open issue on it though

Ah, we're tracking this in #2933 actually. At least, that's the place I've duped this all to in the past - for both layering beyond just fragments, but also roaming the settings. We can consolidate this. 

/dup #2933
