### ISSUE TITLE
can't type any.

### ISSUE THREAD

**Issue by HppZ** [microsoft/terminal#15632]
### Windows Terminal version

1.17.11461.0

### Windows build number

22621.1848

### Steps to reproduce

1, git log, press enter
2, max the window
3, press q
![image](https://github.com/microsoft/terminal/assets/12285582/1e89e968-b55c-4bb2-a12d-de77cb38d52a)
![image](https://github.com/microsoft/terminal/assets/12285582/d58d5c7e-d7d3-4db1-aed3-3582d552f0dd)
![image](https://github.com/microsoft/terminal/assets/12285582/077d08a6-b94e-42f3-a11d-581b0cd76ad1)
![image](https://github.com/microsoft/terminal/assets/12285582/bb989a22-8699-490e-8517-82eb5ec4efbd)

### Actual Behavior

git bash is ok in this situation.

**Comment by lhecker** [comment]
Thanks for the report! This is a duplicate of #13819. /dup #13819
Reading through it, the solution seems to be for you to run `git update-git-for-windows` and update to the latest version (2.41.0).
