### ISSUE TITLE
Existing window restored when Terminal is opened as a default terminal

### ISSUE THREAD

**Issue by krzysdz** [microsoft/terminal#15636]
### Windows Terminal version

94e6b91c7892b9e2ec8244ab7990ecf50679b083

### Windows build number

10.0.19045.3086

### Other Software

`cmd.exe`, `powershell.exe` or any `.bat` file to start `cmd` - anything that opens a terminal.

### Steps to reproduce

1. Make Windows Terminal the *Default terminal application* in settings.
2. Make sure that *New instance behavior* is *Create a new window*.
3. Set `"firstWindowPreference": "persistedWindowLayout"` (*When Terminal starts: Open windows from a previous session*)
4. Open a few tabs.
5. Open a `.bat` file from explorer or start `cmd`/`powershell` from the start menu or Win+R.

If opening `.bat` files behaves as expected, close all Terminal windows, open it again and try running `.bat` once more. It makes the issue reappear if for some reason it starts working correctly.

### Expected Behavior

A new window opens, in which the file is executed.

### Actual Behavior

Two new windows open:
- one in which the file is executed
- one with the same tabs as in the existing window

https://github.com/microsoft/terminal/assets/12915102/69f12b60-295a-4039-9b1e-acf864d29cf3

**Comment by zadjii-msft** [comment]
_what_

**Comment by krzysdz** [comment]
I think it may have something to do with #15509, because process explorer shows two different Terminal process trees:

The *older* Terminal - under `explorer.exe` (1 window):
![Windows Terminal from explorer.exe](https://github.com/microsoft/terminal/assets/12915102/cfe13f0e-9663-4be8-8714-99f715a61995)

The reopened Terminal - under `wininit.exe` -> `services.exe` -> `svhost.exe` (2 windows - cmd and reopened):
![Windows Terminal from svchost.exe](https://github.com/microsoft/terminal/assets/12915102/c9945f33-d7e8-4d04-9dae-b0e35d7f5415)

The `cmd.exe` launched from Win+R, which caused Terminal to start again is under `explorer.exe`:
![cmd.exe](https://github.com/microsoft/terminal/assets/12915102/f3ca2c3b-a780-4b6f-b559-bc315c6c22d7)

**Comment by zadjii-msft** [comment]
Ah yep okay, hadn't seen that thread yet. That's definitely the same one. Thanks!

/dup #15509
