### ISSUE TITLE
The top tab items bar doesnt allow you to move the window, there's only a tiny area to move the window on the right.

### ISSUE THREAD

**Issue by AngryCarrot789** [microsoft/terminal#1563]
![image](https://user-images.githubusercontent.com/32274404/60052616-a1e34900-96cd-11e9-8092-567e3d0f11f6.png)
This is the top bar, on the left is obviously the tab for the console, to the right is a lighter colour where the tabs are stored and further right is the colour i have for the top of windows. There's only a tiny space for you to drag the window.

**Comment by cinnamon-msft** [comment]
#564
