### ISSUE TITLE
Drag & drop in WSL should use single quotes

### ISSUE THREAD

**Issue by MikeWang000000** [microsoft/terminal#15646]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1928

### Other Software

GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu) (inside WSL)

### Steps to reproduce

File drag & drop in WSL Bash:

```console
user@localhost~$ cat /mnt/c/Users/Admin/Desktop/$hello.txt
cat: /mnt/c/Users/Admin/Desktop/.txt: No such file or directory
user@localhost~$ cat "/mnt/c/Users/Admin/Desktop/$hello world.txt"
cat: '/mnt/c/Users/Admin/Desktop/ world.txt': No such file or directory
```

It does not work because `$hello` is recognized as a variable.

### Expected Behavior

```console
user@localhost~$ cat '/mnt/c/Users/Admin/Desktop/$hello.txt'
user@localhost~$ cat '/mnt/c/Users/Admin/Desktop/$hello world.txt'
```

or

```console
user@localhost~$ cat /mnt/c/Users/Admin/Desktop/\$hello.txt
user@localhost~$ cat /mnt/c/Users/Admin/Desktop/\$hello\ world.txt
```

### Actual Behavior

```console
user@localhost~$ cat /mnt/c/Users/Admin/Desktop/$hello.txt
cat: /mnt/c/Users/Admin/Desktop/.txt: No such file or directory
user@localhost~$ cat "/mnt/c/Users/Admin/Desktop/$hello world.txt"
cat: '/mnt/c/Users/Admin/Desktop/ world.txt': No such file or directory
```

：/

**Comment by lhecker** [comment]
FYI the code that does it is here: https://github.com/microsoft/terminal/blob/167819a8f407aac691da79e061af85a066ffcbc5/src/cascadia/TerminalControl/TermControl.cpp#L2800-L2804

The best course of action would be to use single quotes for WSL only, because cmd.exe doesn't get single quotes.

**Comment by zadjii-msft** [comment]
also x-ref #8109

**Comment by Darkace01** [comment]
Can someone help explain how I can locate the code that handles drag and drop for the terminal?
