### ISSUE TITLE
Getting an complete folder structure in terminal only(Different colour structure)

### ISSUE THREAD

**Issue by anuraghit** [microsoft/terminal#15641]
# Description of the new feature/enhancement

I am writing today to make a feature request that I believe would greatly enhance the user experience for developers working in the terminal. Currently, when navigating through repositories in the terminal, the folder structure is displayed in a uniform color, making it challenging to quickly identify different levels and subdirectories.

I would like to propose the implementation of a feature that allows for a complete folder structure to be displayed in the terminal, with each level of the structure assigned a distinct color. This visual differentiation would enable developers to easily grasp the hierarchy of their project and navigate through directories more efficiently.

I believe that this feature would be highly beneficial to developers who frequently work in the terminal, helping them save time and reduce errors. It would greatly enhance the productivity and user experience for GitHub users across the globe.

Thank you for considering my feature request. I appreciate the hard work and dedication of the GitHub team in continuously improving the platform. I look forward to seeing GitHub evolve and empower developers even further.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is usually something configurable based on the application that's emitting the directory structure. For example, `ls` uses `LS_COLORS` to change the colors of the output based on the file type. There's a similar way of [controlling the colors in PowerShell 7.2+](https://superuser.com/a/1761384).

Terminal is more than happy to listen to the colors emitted by an app, but we don't really control what the client application chooses to emit.
