### ISSUE TITLE
"$schema": "https://aka.ms/terminal-profiles-schema" leads to old (1.16) schema version

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/terminal#15647]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1928

### Steps to reproduce

1) Open `settings.json` in VS Code editor (or other editor/tool that supports validation with JSON Scheme)
2) Change `colorScheme` to new dark/light format
```json
"colorScheme": {
    "dark": "Campbell",
    "light": "One Half Light"
}
```
3) Observe error `Incorrect type. Expected "string".`

### Expected Behavior

Link https://aka.ms/terminal-profiles-schema points to scheme for 1.17 (https://raw.githubusercontent.com/microsoft/terminal/release-1.17/doc/cascadia/profiles.schema.json)
No validation error.

### Actual Behavior

Currently linked scheme links to 1.16 (https://raw.githubusercontent.com/microsoft/terminal/release-1.16/doc/cascadia/profiles.schema.json)
And therefore new value fails validation

**Comment by zadjii-msft** [comment]
@DHowett I don't have access to that one to update that, can you?

**Comment by giggio** [comment]
It is now pointing to 1.17, but I'm using preview, is there an aka.ms link for the preview schema?

**Comment by zadjii-msft** [comment]
> Is there an aka.ms link for the preview schema

Not really, that's a discussion we were having over in #6601. But I'm glad someone updated it? (Looks like Dustin might have in #15712)
