### ISSUE TITLE
Windows Terminal can't find nerd fonts...again

### ISSUE THREAD

**Issue by sh1nyfox** [microsoft/terminal#15644]
### Windows Terminal version

1.17.11461.0

### Steps to reproduce

Using a nerd font works fine when it's first set. But as soon as terminal closes, the error saying it can't be found comes up without fail the next boot. Closing and restarting doesn't seem to work, and it doesn't matter which nerd font is selected. 

Also happens in the latest terminal preview it seems. 

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/71068970/d435e794-bf41-488a-b217-fa7e4285e150)

**Comment by lhecker** [comment]
Did you install the font for all users or just for yourself?
