### ISSUE TITLE
Update roadmap documentation for 2023 and beyond

### ISSUE THREAD

**Issue by daverayment** [microsoft/terminal#15661]
The roadmap document, referenced prominently from the project's ReadMe file, has not been updated in more than a year:

https://github.com/microsoft/terminal/commits/main/doc/roadmap-2022.md

Please could the roadmap be updated with your plans for the future. If the roadmap is no longer being used, could the section in the ReadMe be removed, as it is no longer relevant.

**Comment by zadjii-msft** [comment]
as a note: we're not just leaving you on read. We've got some folks out for overlapping chunks of the summer, resulting in us not quite having put together the official Q3 plan yet. We're all working on _stuff_ that'll eventually be a part of it, but we don't have quorum to sign off on a real roadmap. 

When we do, we'll loop back on this ☺️

**Comment by daverayment** [comment]
Thanks, @zadjii-msft 👍

**Comment by maddes8cht** [comment]
The Roeadmap is again outdated.
It's 2024 now..
