### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by abhayraw1** [microsoft/terminal#1566]
Acrylic effect vanishes completely when the terminal looses focus.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): Preview 0.2.1715.0

Any other software? Nope
```

# Steps to reproduce

- Open terminal with Acrylic background set to true.
- Snap it to one of the sides and open some other app beside it,
- The acrylic effect will vanish as soon as you start working on the other app.
- Clicking on the terminal will bring back the effect again. 

# Expected behavior
I hope this is not intentional and the effect should not toggle whenever we switch to other apps. 

### When the terminal isn't selected
![Screenshot (2)](https://user-images.githubusercontent.com/14311538/60054940-a9b8e280-96f9-11e9-8577-56873c38aa84.png)

### When the terminal is selected
![Screenshot (1)](https://user-images.githubusercontent.com/14311538/60054876-78d8ad80-96f9-11e9-93bb-f9dabf59dec4.png)

# Actual behaviour

**Comment by DHowett-MSFT** [comment]
This is by design for _all_ acrylic applications on Windows.
