### ISSUE TITLE
remember the path of every panel  when restart

### ISSUE THREAD

**Issue by ilaipi** [microsoft/terminal#15668]
# Description of the new feature/enhancement

I am using the git-bash, and install zsh. and use split panel.
when I restart the terminal, every panel redirect to the default panel.
So I hope each panel can stay the same path when I restart the terminal.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is already possible today. See: [Tutorial: Opening a tab or pane in the same directory in Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

**Comment by ilaipi** [comment]
I am using zsh with git-bash, not wsl ,  while try :

```
keep_current_path() {
  printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"
}
precmd_functions+=(keep_current_path)
```

got : `keep_current_path:1: command not found: wslpath` when restart windows terminal.

@zadjii-msft
