### ISSUE TITLE
Zoom level resets after using windows lock screen

### ISSUE THREAD

**Issue by Davidsv** [microsoft/terminal#15670]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Open terminal
2. zoom using ctrl+mouse scroll wheel
3. lock windows (WIN + L)
4. unlock windows
5. observe that the zoom in terminal has been reset to the level it was at step 1

### Expected Behavior

I expected that the zoom level stays the same as I set it to before I unlocked windows. For me it's good if zoom level resets when terminal is closed, but I don't expect it to change after only locking windows.

### Actual Behavior

After returning from the windows lock screen, the zoom level did not stay where I set it before I locked windows.

**Comment by zadjii-msft** [comment]
I'm _fairly_ confident that this is the same root cause as /dup #11522. Thanks!
