### ISSUE TITLE
Feature Request - Move profiles.json to a more accessible location

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#1567]
# Summary of the new feature/enhancement

The profiles.json file is hard to find when you don't click the Settings button within the Terminal. Let's move the default location to somewhere more accessible.

**Comment by DHowett-MSFT** [comment]
When running unpackaged, WT saves profiles in `%APPDATA%\Microsoft\Windows Terminal`, which is a very windows-y place to put config files. Some people wish it would put files in your user folder ... and other people _hate_ tools that put files in the user folder . . .

**Comment by JushBJJ** [comment]
Maybe add the topic #1455 into here too.

**Comment by carlos-zamora** [comment]
@DHowett-MSFT @cinnamon-msft As we approach a post-v1 world, is this even feasible anymore? Should we just close this?

**Comment by DHowett-MSFT** [comment]
This was somewhat outmoded by /dup #2933.
