### ISSUE TITLE
Move pane to tab index crash

### ISSUE THREAD

**Issue by stanio** [microsoft/terminal#15683]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3086

### Other Software

Not sure if these make any difference:

-   [clink](/chrisant996/clink) 1.5.1 (with `cmd`)
-   [oh-my-posh](/JanDeDobbeleer/oh-my-posh) 17.9.0 (with both of `cmd` and Git Bash)

The problem happens with vanilla PowerShell tabs/sessions as well.

### Steps to reproduce

1. Open two shell sessions/tabs;
2. Press <kbd>Ctrl+Shift+P</kbd> to bring up the Command Palette;
3. Choose "Move pane, tab index:0" (given the second tab is focused).

### Expected Behavior

The tab session is moved to the target tab, resulting in a split session view.

### Actual Behavior

Windows Terminal crashes(?) and closes/exits completely.

See Feedback Hub submission: https://aka.ms/AAlhotv

**Comment by liamgui** [comment]
I have been having the same issue for at least a month. I left windows feedback in the feedback hub.
https://aka.ms/AAlhb2a

**Comment by PankajBhojwani** [comment]
We are _fairly_ certain that this is fixed in 1.18, marking that we should backport this. Thanks!

**Comment by zadjii-msft** [comment]
(We need to bisect the commits to find out which though)

**Comment by zadjii-msft** [comment]
With 1.18 about to go into stable, I reckon we're probably not about to backport the fix. Though, it'd be nice if we had confirmation from someone who was originally seeing this that 1.18 did in fact fix this. Someone double check that hypothesis/?

**Comment by stanio** [comment]
I have just tried Windows Terminal Preview v1.18.1462.0 and I don't observe the crash with it.  Thanks!

**Comment by lhecker** [comment]
Thanks for testing it!

**Comment by liamgui** [comment]
I know its a little late to the party, but I also tested with the same Preview version with the same results. No crash when `Move pane, tab index:0` is selected.

Great work guys! Looking forward to official 1.18 release 😄
