### ISSUE TITLE
[Powershell 5.1] Write-Progress text black

### ISSUE THREAD

**Issue by bozho** [microsoft/terminal#15684]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Run the following snippet in PowerShell 5.1:
```
for ($i = 1; $i -le 100; $i++ ) {
    Write-Progress -Activity "Search in Progress" -Status "$i% Complete:" -PercentComplete $i
    Start-Sleep -Milliseconds 250
}
```

### Expected Behavior

The progress text should be yellow by default.

### Actual Behavior

The progress text is black.

The problem started with the previous 18XX preview version. It does not appear in Terminal `v1.17.1023` or the old console.

**Comment by lhecker** [comment]
I must be doing something wrong... It works for me:
![image](https://github.com/microsoft/terminal/assets/2256941/0f2bca20-3cee-41f5-ae9b-617d0c52a79d)

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by lhecker** [comment]
Yep, the color adjustment in 1.18 is now stronger than before, turning it into an accessibility feature. It's also much closer now to how VS Code works, where the text is also black:
![image](https://github.com/microsoft/terminal/assets/2256941/6574df83-5cb6-49f0-b0ea-866a6ba646c7)
