### ISSUE TITLE
enhancement of the sticking warning board

### ISSUE THREAD

**Issue by forealmy** [microsoft/terminal#15696]
# Description of the new feature/enhancement
When the clipboard has code pasted into the terminal, a warning message will be prompted. However, copying from elsewhere, such as code snippets, needs to be modified and then pasted at runtime, which is not very convenient.

So I wondered if it was possible to modify the pasted warning panel so that what was going to be pasted could be modified by the user.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #14189 for more discussion.

/dup #14189
