### ISSUE TITLE
Defining environment variables in profiles

### ISSUE THREAD

**Issue by Marc05** [microsoft/terminal#15699]
I'm having difficulty defining environment variables, either for all profiles or per profile, I'm not able to get it working by modifying `settings.json`. I saw a [merged feature request](https://github.com/microsoft/terminal/pull/15082/files#diff-a29bc4f9ab52597cf0b513e9141424c2702ac88ae2d668db49a2cd77346ae9bf) which indicates there is support for it, but I have not found help in the documentation, hence this documentation issue report.

**Comment by lhecker** [comment]
Hey! Which version of Windows Terminal are you using?

**Comment by Marc05** [comment]
Apologies, I meant to include that. I'm on `1.17.11461.0`.
