### ISSUE TITLE
Mouse input doesn't work on primary display

### ISSUE THREAD

**Issue by atrich-ms** [microsoft/terminal#15704]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.23493.1000

### Steps to reproduce

After taking a windows update that moved me to win11 insider preview build 23493.ni_prerelease.230624-1828, my mouse is no longer able to interact with the windows terminal (neither interacting with the tab bar and menu icons, nor copy/paste on the terminal) on my primary screen. Scrolling still works for some reason.

### Expected Behavior

The mouse works.

### Actual Behavior

I cannot click any icons in the tab bar (aside from minimize/maximize/close) and I cannot use the mouse to select text. This only happens on one of my monitors. If I move the terminal window to the other monitor, I am able to use the mouse.

**Comment by zadjii-msft** [comment]
Huh. What's special about that monitor vs your other ones? Graphics driver maybe? 

My gut says this feels like a XAML islands bug, but we'd need another XI app to test with...

**Comment by atrich-ms** [comment]
Strangely, this is no longer reproducing for me. I'm going to close it for now and will reactivate if I can get the repro to come back again. Very strange; I tried relaunching terminal multiple times and the mouse behavior stuck around, but now I can't get it to happen again.
