### ISSUE TITLE
npm process won't exit when the terminal window is closed

### ISSUE THREAD

**Issue by jsoldi** [microsoft/terminal#15708]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Other Software

npm v9.6.7
node v18.15.0

### Steps to reproduce

1. Create a folder and clone my sample repro: `npx degit https://github.com/jsoldi/windows-terminal-bug`. It's just a plain server that does nothing.
2. Do `npm install`
3. Open the Windows Terminal on the project folder and run `npm start 3000` and then visit `localhost:3000` on a browser.
4. Close the terminal.
5. Reload `localhost:3000` and the server should still be running

If the process actually stops, try repeating steps 3-5 one more time.

### Expected Behavior

The process should stop.

### Actual Behavior

The process doesn't stop, and I don't know of any way to stop it other than restarting the machine or relogging the user. I've also tried closing the wt from the task manager but that doesn't seem to help.

### Notes

I've noticed that the process will actually stop either if I run the script directly with `node index.js`, or if I do `npm start` from CMD or PS, so somehow the combination of terminal and npm seems to cause the issue.

**Comment by cs-NET** [comment]
Experiencing the same issue, I ended up creating a script to kill all the node processes as a temp workaround as sometimes I have dozens of orphaned node.exe running, might not be the best workaround but beats manually trying to kill each process one at a time:

```
taskkill /f /im node.exe
```

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a \dup of #15373.

The repro steps are fantastic though, so I'll be sure to copy that over :)
