### ISSUE TITLE
Bug Report - crash after enter 'exit' command(when there is only one terminal tab)

### ISSUE THREAD

**Issue by matrixknight** [microsoft/terminal#1570]
# Environment
10.0.18362.175

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):
```
Any other software?
No

# Steps to reproduce
when there is only one terminal tab, type 'exit' command, the terminal window crashed.

# Expected behavior
when there is only one terminal tab, when 'exit' entered, the terminal window should close like CMD does.

# Actual behavior

**Comment by carlos-zamora** [comment]
I believe this is #1380.
