### ISSUE TITLE
settings.json schema aka.ms url points to previous version schema

### ISSUE THREAD

**Issue by arkthur** [microsoft/terminal#15712]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Steps to reproduce

1. Open Terminal.
2. Press Ctrl + ,.
3. Click on Open JSON file.
4. Open schema link in a web browser.

### Expected Behavior

Browser directs you to current terminal version settings JSON schema file, showing in address bar: https://raw.githubusercontent.com/microsoft/terminal/release-1.17/doc/cascadia/profiles.schema.json

### Actual Behavior

Browser directs you to previous terminal version settings JSON schema file, showing in address bar: https://raw.githubusercontent.com/microsoft/terminal/release-1.16/doc/cascadia/profiles.schema.json

**Comment by DHowett** [comment]
Thanks! Just pushed a fix for this. :smile:
