### ISSUE TITLE
why exit or exit /b in batch file in Windows Terminal The system cannot find the batch label specified - exit

### ISSUE THREAD

**Issue by candrapersada** [microsoft/terminal#15718]
why when using `Windows Terminal` + `batch file` there is an error when using `exit`?
```
The system cannot find the batch label specified - exit

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```
https://ss64.com/nt/exit.html

**Comment by candrapersada** [comment]
```
@ECHO OFF
ECHO ======================================================================================================================
ECHO.
SET /P URL="[Enter video URL] "
ECHO.
ECHO ======================================================================================================================
ECHO.
yt-dlp -o "Downloads/%%(title)s.%%(ext)s" -i --ignore-config "%URL%"
ECHO.
ECHO ======================================================================================================================
ECHO.
ECHO Done!
PAUSE
EXIT
```

**Comment by 237dmitry** [comment]
I think you have to set:
```
  "profiles": {
    "defaults": {
      "closeOnExit": "always",
    }
```

**Comment by DHowett** [comment]
`closeOnExit` is unrelated to the parsing of batch files. Changing it will not help with this issue.

**Comment by 237dmitry** [comment]
Maybe yt-dlp returns failure exit code.

From [documentation](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced)
```
In Windows Command Prompt (cmd.exe), exit will return the return code of the previous command.
```

**Comment by DHowett** [comment]
The text displayed on the screen clearly indicates that it is a specific error from the batch file parser.

> `The system cannot find the batch label specified - exit`

"The system cannot find the batch label specified" indicates that the system cannot find the batch label that has been specified. :smile:

**Comment by 237dmitry** [comment]
I tried the same batch (without yt-dlp) and no errors.

**Comment by lhecker** [comment]
@candrapersada I've just taken your .bat file and saved it with VS Code (UTF-8, LF) and it works fine. Are you sure that the file you've updated as Markdown matches your local file _exactly_?

**Comment by 237dmitry** [comment]
> This is 100% the linefeed/carriage return thing.

The example of batch-script is not full. Or perhaps yt-dlp invoke label syntax. This is error-message of cmd.exe that could not find label. Try and get the same error `The system cannot find the batch label specified -`

```
@echo off
pause
goto:
exit
```
