### ISSUE TITLE
Ability to group profiles

### ISSUE THREAD

**Issue by chadleywilson** [microsoft/terminal#15721]
I am not sure if this can already be done, but I could not find the correct search term for it, and apologise in advance if need be.

I have a lot of connection profiles (200+), MS Terminal makes it so much easier to manage them, but could use refinement, scrolling through the list can waste time some days.

Most of my connections are are ssh connections to docker swarms or kubernetes clusters.  see my example below.

It would be nice if I could group my connections by cluster or server purpose them and have "sub menus" to better organise these.

# Proposed technical implementation details (optional)
Here is sort of a summarized example, a typical cluster would have about 7  servers minimum. This is 3 server cluster example actually names changed and guids probably nonsense as I changed them slightly for the demonstration here , I was thinking something along these lines to group them.
```
       {
           "groupNameorTag": "Cluster A"
           "Description": "all Cluster A masters and nodes"
         {
                "colorScheme": "Raspberry",
                "commandline": "ssh ubuntu@mst-01",
                "guid": "{4268914b-3bba-5c19-be6f-42893bc5a277}",
                "hidden": false,
                "icon": "C:\\Scripts\\windows-terminal-icons\\icons\\ubuntu.png",
                "name": "ssh mst-01",
                "tabTitle": "mst-01"
            }'
             {
                "colorScheme": "Raspberry",
                "commandline": "ssh ubuntu@node-01",
                "guid": "{4268914b-3bba-5c19-be6f-42893bc5a278}",
                "hidden": false,
                "icon": "C:\\Scripts\\windows-terminal-icons\\icons\\ubuntu.png",
                "name": "ssh node-01",
                "tabTitle": "node-01"
            }'
             {
                "colorScheme": "Raspberry",
                "commandline": "ssh ubuntu@node-0",
                "guid": "{4268914b-3bba-5c19-be6f-42893bc5a279}",
                "hidden": false,
                "icon": "C:\\Scripts\\windows-terminal-icons\\icons\\ubuntu.png",
                "name": "ssh node-02",
                "tabTitle": "node-02"
            }
        }
```

When you click the drop down arrow, instead of only seeing PowerShell/ cmd / azure cloud shell / PowerShell 7 standard profiles, I would like to be able to have sub menus for docker swarms and Kubernetes clusters and categorize some of the stand alone servers that I connect to on a daily basis. 

I have shortened and redacted version attached as a pic, which I took from a older user profile, but it should be enough illustrate what my colleagues and I use on a daily basis.

![image](https://github.com/microsoft/terminal/assets/43165291/f60c7dd0-547c-4311-b47f-09cbff4f7efc)

**Comment by zadjii-msft** [comment]
quick note: we introduced `newTabMenu` in 1.17. See #1571. There's no docs for it yet though 😢 

I'll make a longer reply later

**Comment by zadjii-msft** [comment]
Alright, we've got a docs PR out now: https://github.com/MicrosoftDocs/terminal/pull/692

technically, this is a /dup of #1571, so I'll close it as such. 

Thanks for giving me the impetus to finally document that!
