### ISSUE TITLE
Error: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by TheBigBear** [microsoft/terminal#15728]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.20348.1787

### Steps to reproduce

double click the windowsterminal icon and this message comes up ( also see screenshot )
![Screenshot  2023-07-19 at 17 27 45](https://github.com/microsoft/terminal/assets/471105/03fedb67-3525-40f7-b38a-ca7cdb63e6f3)

### Expected Behavior

the WindowsTerminal application window should open instead.

### Actual Behavior

it gives me the error shown here
![Screenshot  2023-07-19 at 17 27 45](https://github.com/microsoft/terminal/assets/471105/fb60c124-8b29-40ba-94a6-811800cc7a54)

**Comment by zadjii-msft** [comment]
This may seem like a silly question, but did you manually disable any services/?

**Comment by TheBigBear** [comment]
@zadjii-msft not that I can remember. I have done a full comparison of any disabled services on this server and compared the list to the other servers where WindowsTerminal runs just fine. And even went as far as enabling them and seeing if that made a difference, but it did not. 
A good question though. ;-) Are there any services that come to mind that the WindowsTerminal would check and that might be a potential culprit?

**Comment by jamespack** [comment]
> @zadjii-msft not that I can remember. I have done a full comparison of any disabled services on this server and compared the list to the other servers where WindowsTerminal runs just fine. And even went as far as enabling them and seeing if that made a difference, but it did not. A good question though. ;-) Are there any services that come to mind that the WindowsTerminal would check and that might be a potential culprit?

Shooting from the hip here. but seclogon. (Assuming you are in a corporate environment and your corporate environment disables that service using GPO to prevent running things as a different user)

**Comment by carlos-zamora** [comment]
> Are there any services that come to mind that the WindowsTerminal would check and that might be a potential culprit?

Could you check if the Windows Update service is running?

**Comment by zadjii-msft** [comment]
As an aside, it also looks like this might be a Windows Server machine - how did you install the Terminal to that machine?

**Comment by TheBigBear** [comment]
> > @zadjii-msft not that I can remember. I have done a full comparison of any disabled services on this server and compared the list to the other servers where WindowsTerminal runs just fine. And even went as far as enabling them and seeing if that made a difference, but it did not. A good question though. ;-) Are there any services that come to mind that the WindowsTerminal would check and that might be a potential culprit?
> 
> Shooting from the hip here. but seclogon. (Assuming you are in a corporate environment and your corporate environment disables that service using GPO to prevent running things as a different user)

@jamespack no, secondary logon is on automatic - I even started it manually - just to be sure. but no change. thanks for the feedback.

**Comment by TheBigBear** [comment]
> > Are there any services that come to mind that the WindowsTerminal would check and that might be a potential culprit?
> 
> Could you check if the Windows Update service is running?

@carlos-zamora yes the windows update service is also running. thanks for the help.

**Comment by TheBigBear** [comment]
> As an aside, it also looks like this might be a Windows Server machine - how did you install the Terminal to that machine?

@zadjii-msft yes, that is the point it is on a server 2022. I installed winget or the desktopappinstaller which does install from github to a recent enough server even without any ms store on it. 
once winget was up and running I used it to install microsoft's windowsterminal. 
but I could have also used chocolatey to install windowsterminal on the server 2022 machine.
thanks for your help.

**Comment by zadjii-msft** [comment]
Huh, fascinating. @denelon You ever seen anything like this? I'm not sure how well winget works on Windows Server. I suspect it should just work fine, but maybe this is one of the edge cases?

Does an unpackaged install (straight from the .zip on our releases page) work?

**Comment by zadjii-msft** [comment]
oh lmao winget punted you to us https://github.com/microsoft/winget-cli/issues/3442
