### ISSUE TITLE
Suppressed application title overwritten after screen lock

### ISSUE THREAD

**Issue by geluk** [microsoft/terminal#15732]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22000.0

### Steps to reproduce

1. Open a new terminal, and override the application title:
  ```
  wt --suppressApplicationTitle --title example powershell
  ```
2. Observe that the terminal has a tab named `example` 
2. Lock your screen (`Windows` + `L`)
3. Sign back in
4. Observe that the tab name has changed from `example` to `Windows PowerShell`

### Expected Behavior

After unlocking, I would expect the tab name to be unchanged.

### Actual Behavior

After unlocking, the tab name is changed from `example` to `Windows PowerShell`.

Note: This only happens when using the commandline to set the tab title. If you manually override it by double-clicking the tab and entering something there, the tab will keep its name after locking and unlocking.

**Comment by zadjii-msft** [comment]
Another obvious way of triggering this is setting a fontFace to `garbage` or some other non-existent font, then opening a admin application. The UAC will trigger a "desktop change"[^1]. That'll do the same thing as a lock screen. 

Debugger shows that we get another "ImmersiveColorSet" message, with `wparam=0`. Great. We're using that as a signal that the OS theme changed. When we get that, we reload the whole settings.[^2] 

A stackoverflow post pointed me at maybe [`UISettings.ColorValuesChanged`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.colorvalueschanged?view=winrt-22621)

related, but not actually: #11522

[^1]: okay that's not exactly what's happening, on mobile so can't look up the right term. 
[^2]: reloading the settings overwrites the title from the NewTabArgs. That's not great, but I think that's _technically_ tracked in
