### ISSUE TITLE
Add UI to preview and install colorschemes like VSCode.

### ISSUE THREAD

**Issue by adityamwagh** [microsoft/terminal#15730]
# Description of the new feature/enhancement
I propose adding a theme installation standard to Windows Terminal, similar to VSCode's theme preview & installation functionality. This would enable users to easily search, preview, and install themes from within the application, reducing manual copy-paste work and enhancing the user experience.

The feature should include:

- A theme marketplace or repository within Windows Terminal for theme discovery.
- Theme preview option to assess appearance before installation.
- Simple one-click installation process for selected themes.
- Theme management interface for activation, deactivation, and uninstallation.

For example, like VSCode, I could open the theme picker dialog using a key board shortcut (`Ctrl + K Ctrl + T`) and preview themes and install them with the press of a button.

![image](https://github.com/microsoft/terminal/assets/25822972/1d371629-efec-4ab1-b102-ebbe4107d3d9)

**Comment by carlos-zamora** [comment]
Hi @adityamwagh. Thanks for filing! Setting up a server to act as a theme marketplace is probably out of scope for the team. However, we are interested in being able to import color schemes via #8639. So, we're going to close this as a /dup of #8639.

**Comment by zadjii-msft** [comment]
To add to this - the Terminal will let you preview all the schemes that you do have installed in the "Select color scheme..." command in the command palette:

![](https://user-images.githubusercontent.com/18356694/114557761-9a3cbd80-9c2f-11eb-987f-eb0c89ee1fa6.gif) 

(since #9794)
