### ISSUE TITLE
confusing version : "About dialog" vs Release

### ISSUE THREAD

**Issue by g-chauvel** [microsoft/terminal#15739]
### Windows Terminal version

1.17.230526001

### Windows build number

10.0.19045.0

### Steps to reproduce

- Download asset https://github.com/microsoft/terminal/releases/download/v1.17.11461.0/Microsoft.WindowsTerminal_1.17.11461.0_x64.zip
- Run and Open About dialog

### Expected Behavior

Displayed version should be `1.17.11461.0`

### Actual Behavior

Displayed version is `1.17.230526001`

**Comment by zadjii-msft** [comment]
Good catch. The unpackaged versions of the Terminal can't use the same versioning APIs that the packaged ones use, so they're just stamped with the build timestamp instead. We should update the [portable mode & unpackaged docs](https://learn.microsoft.com/en-us/windows/terminal/distributions) to explicitly call this out.

**Comment by zadjii-msft** [comment]
I've moved this over to https://github.com/MicrosoftDocs/terminal/issues/693. Thanks!

/dup https://github.com/MicrosoftDocs/terminal/issues/693
