### ISSUE TITLE
change font color

### ISSUE THREAD

**Issue by 17Edwin** [microsoft/terminal#1573]
i want to change font color when typing command in power shell,

**Comment by JushBJJ** [comment]
You can change the font color from your powershell profile in the settings file.

**Comment by antoineco** [comment]
Take a look at this article: https://dev.to/expertsinside/how-to-customize-the-new-windows-terminal-with-visual-studio-code-56b1
Each `profile` has a reference to a `colorScheme`, and some of those schemes are defined in the same file. [Full documentation](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) for reference.

**Comment by 17Edwin** [comment]
thanks @antoineco , i did it :D

**Comment by torms** [comment]
there is no reference to font color.. what is the specific setting to change it?

**Comment by antoineco** [comment]
@torms next time, instead of down voting, just mention that the referenced link is outdated, that could help other people. Thanks.

For reference, the new doc is here: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes

I updated my comment.

**Comment by torms** [comment]
> @torms next time, instead of down voting, just mention that the referenced link is outdated, that could help other people. Thanks.
> 
> For reference, the new doc is here: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes
> 
> I updated my comment.

hello
I already came across the official doc and there is no reference about font color. So for me this issue is not resolved.
Thanks

**Comment by antoineco** [comment]
It's right here in the example:
```
"foreground" : "#CCCCCC", 
``` 

A terminal emulator typically has
* A foreground color (color if the characters printed on the screen)
* A background color (color of what's behind the text)
* 8 accent colors for highlights

**Comment by SuperHarmony910** [comment]
Thanks for the `"foreground": #00000` tip!

**Comment by MdSalmanTd** [comment]
https://prnt.sc/1g04lu9

**Comment by zadjii-msft** [comment]
@MdSalmanTd That's because PSReadline automatically tries to syntax-highlight commands as you type them. You can read more about it:
* [here](https://www.google.com/search?q=psreadline+syntax+highlighting)
* or [check out the docs](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.1)
