### ISSUE TITLE
keys not working in the terminal

### ISSUE THREAD

**Issue by aesyntax** [microsoft/terminal#15741]
Please, kindly assist me on what to do.
After installing "Windows Terminal App" on my machine, I noticed my keyboard wasn't typing in the terminal.
Thank you

**Comment by Zeroes1** [comment]
i have same problem.
mouse work, key not.
alt+key = works

**Comment by zadjii-msft** [comment]
> TabletInputService off

Welp, yep, that'd do it. You need to have that turned on. 


---

From the FAQs: [Unable to type in the Terminal?](https://github.com/microsoft/terminal/wiki/Unable-to-type-in-the-Terminal%3F)

Did that help/?

**Comment by Zeroes1** [comment]
but if user is admin this in not nessasary? right? :)

**Comment by zadjii-msft** [comment]
Nope. Pretty sure it's still necessary. The "TabletInputService" is the poorly named modern input platform. Disabling it is likely to break things.

**Comment by Zeroes1** [comment]
Hmm. i work fine as admin and "TabletInputService" when OFF, trouble with FAR manager is different case.

**Comment by zadjii-msft** [comment]
@Zeroes1 That sounds kinda like a different issue. @aesyntax  here didn't mention anything about FAR, or the alt keys. Mind filing a separate bug report so we can triage the root cause of your issue separately?

**Comment by Zeroes1** [comment]
@zadjii-msft  I mean my other open issue:
https://github.com/microsoft/terminal/issues/15540
https://github.com/microsoft/terminal/issues/15533
