### ISSUE TITLE
Global Summon not functional on desktop

### ISSUE THREAD

**Issue by Phelsong** [microsoft/terminal#15742]
### Windows Terminal version

1.18.1462

### Windows build number

11.0.23506

### Steps to reproduce

Global Summon (Toggle Visibility) does not work when the desktop is focused.

```
{
    "command": 
    {
        "action": "globalSummon",
        "desktop": "onCurrent",
        "monitor": "any",
        "toggleVisibility": true
    },
    "keys": "ctrl+space"
},
```

(Works fine with any window, start menu, taskbar, etc... is in focus)

### Expected Behavior

Terminal window is summoned to the foreground and set to focus

### Actual Behavior

Nothing

**Comment by jamespack** [comment]
Does whether or not the terminal is maximized make a difference? Curious cause its related to something Im working on.

**Comment by zadjii-msft** [comment]
I'm assuming that 1.**8**.1462 is a typo and you meant **1.18** 😛 

I weirdly cannot get this to repro. Are you running like, an elevated Terminal window? There have been applications in the past known to interfere with the ability of the Terminal to summon itself (notably, task manager). But the desktop? That's surely not expected. Cause that's also just the same process as the taskbar, start menu, etc. 

Do you have anything else running that might have full screen invisible windows? I literally can't think of something like that, but like, FancyZones? Something that messes with the window manager? I dunno.

**Comment by zadjii-msft** [comment]
HUH! That's very interesting. Thanks for following up!
