### ISSUE TITLE
Redistribution Permissions for Windows Terminal Binaries

### ISSUE THREAD

**Issue by 0xbe7a** [microsoft/terminal#15740]
Hello,

I'm considering redistributing Windows Terminal binaries as part of conda-forge. Can you clarify if this is permissible under your license and if any conditions apply?

Thanks

**Comment by DHowett** [comment]
Hey, thanks for asking!
I think you'd be in the clear, but I'm gonna mark this one up for team discussion just so I'm sure we've talked it through.

As a passing curiosity (and you're free not to answer!): what's your goal?
If there's something we could do to better enable that, I would love to know what/how.

For example...

- If you want an embeddable terminal control that you can put in your own UI, it should work totally fine but I'd love to know so I can prioritize #6999
- If you are using OpenConsole and some of the ConPTY bits, that would help inform #15065
- If you want just `Terminal.Settings.Model`, etc. etc. etc

**Comment by 0xbe7a** [comment]
I find Windows Terminal to be an excellent software tool that provides all required functionality straight out of the box.

As for motivation we try to maintain a streamlined conda development environment for ease of use and consistency across machines and infrastructure.

Since our work often involves extensive terminal operations, having Windows Terminal integrated would be highly convenient and beneficial for us.

**Comment by lhecker** [comment]
Is there a reason why Windows Terminal couldn't be installed from the app store on the target machine when conda is installed / first used? Otherwise, this might result in user confusion when they use Windows Terminal bundled with conda and it has settings that don't exist in another (regular) Windows Terminal installation on the machine.

**Comment by lhecker** [comment]
To add, redistributing Windows Terminal is completely fine from a license standpoint.

**Comment by pavelzw** [comment]
> Is there a reason why Windows Terminal couldn't be installed from the app store on the target machine when conda is installed / first used? 

in some Windows Server instances (and also other contexts) there is no Microsoft App Store to download the terminal from.

**Comment by zadjii-msft** [comment]
Yea, this basically just seems like the same thing as shipping it on `chocolatey` or `scoop`.

**Comment by isuruf** [comment]
@lhecker, to clarify, redistributing the binary is allowed?

**Comment by lhecker** [comment]
Yep 👍
