### ISSUE TITLE
Optionally play a sound when a long running command completes

### ISSUE THREAD

**Issue by stravant** [microsoft/terminal#15749]
# Description of the new feature/enhancement

Often developers need to run long running command line tasks such as builds, and would like to know when they've completed.

If the windows terminal could play a sound after completing a command which ran for longer than some configurable cutoff, such as a 60 seconds, it would provide a lot of value.

It's possible to create a shim program to use for this writing something like `myCommand1 || myPlaySoundShim` but that's too manual to actually be convenient in practice. A builtin for this would be much better.

This could be as simple as playing the existing BEL sound.

**Comment by zadjii-msft** [comment]
Great idea! I think we're tracking some similar thoughts in #7955 - or, at least, I'm trying to agregate them there. 

/dup #7955
