### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 8thHalfHour** [microsoft/terminal#1574]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): Windows Store Terminal (Preview), v6.2.1

# Steps to reproduce

Try to open the app.

# Expected behavior

Terminal opens and functions.

# Actual behavior

Window looks like it will load, then flashes and disappears.

I have tried:

- uninstalling, rebooting, and reinstalling
- loading the terminal in another profile
- running DISM and SFC, no problems found, no other system weirdness

**Comment by cinnamon-msft** [comment]
#1364
