### ISSUE TITLE
Visual Studio 2022 Community build OpenConsole.sln failed 

### ISSUE THREAD

**Issue by snowuyl** [microsoft/terminal#15757]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Steps to reproduce

1. Opening OpenConsole.sln from Visual Studio 2022 Community.
2. Changing configuration to x64.
3. Selecting regenerating solution.
4. Visual Studio 2022 Community shows 70 building errors.

### Expected Behavior

Visual Studio 2022 Community shows 70 building successfully.

### Actual Behavior

Visual Studio 2022 Community shows 70 building errors.

**Comment by snowuyl** [comment]
<img width="960" alt="buildingerrors" src="https://github.com/microsoft/terminal/assets/8336439/18843334-a88a-428f-ad23-515e961c5e06">

**Comment by zadjii-msft** [comment]
I mean, I think that error message is pretty self explanatory:

> This project references git submodule(s) that are missing on this computer. Use `git submodule update --init --recursive` to download them.  For more information, see https://github.com/microsoft/terminal#building-the-code. 

Did you `git submodule update --init --recursive` before building?
