### ISSUE TITLE
Windows Terminal PowerShell | Unable to read Extended Properties 

### ISSUE THREAD

**Issue by D4-AzIdentity** [microsoft/terminal#15754]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

Graph PowerShell

### Steps to reproduce

Upon initial launch Terminal PowerShell is unable to query or expand properties. 

Ex. 
PS C:\Users\{PII}> Connect-MgGraph -Scopes directory.read.all
Welcome To Microsoft Graph!

Entering the following returns nothing.
PS C:\Users\{PII}> $device = Get-MgDevice -DeviceID 2dc239e4..........
PS C:\Users\{PII}> $device.additionalproperties

However entering the above in a normal PowerShell window, the Shell is able to read and expand the properties. 
![image](https://github.com/microsoft/terminal/assets/59093056/8a409f5b-f8ae-4a11-94b0-689614958397)

### Expected Behavior

Normal PowerShell Windows works fine. 
![image](https://github.com/microsoft/terminal/assets/59093056/fe10e6ba-f996-40c5-9f2d-ae94c2c428ed)

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/59093056/8a409f5b-f8ae-4a11-94b0-689614958397)

**Comment by DHowett** [comment]
In addition, could you share the output of `$PSVersionTable` in the working and non-working repro cases? Thanks!
