### ISSUE TITLE
ctrl + w sometimes crash 

### ISSUE THREAD

**Issue by 17Edwin** [microsoft/terminal#1575]
# Steps to reproduce

ctrl + w sometimes crash unnormally, ctrl + , is also

# Expected behavior

shortcut keyboard run proper

# Actual behavior

**Comment by yodurr** [comment]
Is there a particular shell you're using when ctrl+w crashes?
Is this with your local build or the Store version?

**Comment by 17Edwin** [comment]
both power shell & cmd prompt, sometimes it not responding and slow, and i have to close and reopen

**Comment by antoineco** [comment]
Happens to me in WSL2 (Ubuntu), consistently. CTRL+W is used to change splits in Vim, so this is particularly annoying.

**Comment by DHowett-MSFT** [comment]
You know you can edit the bindings in the settings file, right?

**Comment by carlos-zamora** [comment]
Probably a duplicate of #1380 since CTRL+W closes a tab. Closing and marking as duplicate.
