### ISSUE TITLE
Windows Terminal Preview v1.18.1462.0 doesn't start on Windows Server 2019

### ISSUE THREAD

**Issue by mhechthz** [microsoft/terminal#15765]
### Windows build number

Microsoft Windows [Version 10.0.17763.4645]

### Steps to reproduce

Just start WindowsTermina.exe or wt.exe

### Expected Behavior

should run

### Actual Behavior

doesn't run

I downloaded the zip File and extracted this to a local directory. On double-clicking WindowsTerminal.exe or wt.exe nothoing ahppens. Running on shell also doesn't work. Also not wt.exe --help.

Add-AppPackage -Path .\Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle says: `Das Paket erfordert auf der Gerätefamilie Windows.Mobile mindestens die Betriebssystemversion 10.0.19041.0.`

**Comment by lhecker** [comment]
Unfortunately, your Windows version is simply too old. As the message says, it requires at least build 19041, but your Windows is still on 17763. In short, you'll have to upgrade to Windows Server 2022 to use Windows Terminal.
For better or worse, Windows Terminal is built on top of XAML Islands which will not work right on anything older than build 18362. I forgot why we require 19041 now, but I'm pretty sure that 18362 vs 19041 doesn't really matter as the next newer version of Windows Server is 2022, which is build 20348. And the next newer still supported Windows 10 version is 19044.

**Comment by mhechthz** [comment]
So there is no chance to get any (older) version of WindowsTerminal to run on this system?

**Comment by lhecker** [comment]
I believe even the oldest version of Windows Terminal required 18362. You can use OpenConsole with the new text renderer if you'd like to at least get better Unicode support and performance. Doing that however is a bit complicated and/or cumbersome.

**Comment by zadjii-msft** [comment]
> So there is no chance to get any (older) version of WindowsTerminal to run on this system?

That's correct. This is an FAQ topic here: [Can I use the Terminal on (Windows 7, Windows Server 2019, any other down-level Windows version)
](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version)

**Comment by mhechthz** [comment]
Thank You!

**Comment by tsuyo** [comment]
@lhecker I have the exact issue even on Version 10.0.20348 Build 20348 (Windows Server 2022). wt.exe & WindowsTerminal.exe in the package don't work, but OpenConsole.exe only works. Which log should I check?

**Comment by lhecker** [comment]
@tsuyo Are you sure you have the _exact_ same issue? This issue is about the error message
> The package requires OS version 10.0.19041.0 or higher on the Windows.Mobile device
family.

You can read more about the issues that are specific to Windows Server here: https://github.com/microsoft/terminal/discussions/13983

As DHowett notes in a comment, the "preinstallation kit" contains all the dependencies you need to install it on Windows Server. If you use it (or the manual instructions in the discussion) and the issue still persists, please [create a new issue](https://github.com/microsoft/terminal/issues/new/choose). 🙂

**Comment by lhecker** [comment]
Oh right, I forgot to mention that you can find the preinstall kit on our release page: https://github.com/microsoft/terminal/releases
Each release has a preinstall kit under the assets section.

**Comment by tsuyo** [comment]
@lhecker Thanks for your reply. I referred to [#13983](https://github.com/microsoft/terminal/discussions/13983), but I can't still open the latest stable version with the same permission issue as #13983. However, I found I can do it with the 1.18 preview version for whatever reason. For now, it's OK, but I believe there might be some issues with the stable version on some environments.
