### ISSUE TITLE
WHen used with Visual Studio for debugging, screen doesnt clear

### ISSUE THREAD

**Issue by towel42-com** [microsoft/terminal#15768]
### Other Software

Visual Studio 2022 17.6.5

### Steps to reproduce

Create a C++ console application
Make sure the debugging option to "Automatically close the console when debugging stops" is unchecked
Run and exit an attached debugging session
Again Run and exit an attached debugging session

### Expected Behavior

With the old windows console, it was cleared every time.

This is what should happen

### Actual Behavior

When you run a second (or more) debugging session, 99% of the time it just starts at the top of the console screen overwriting existing text 

Sometimes it clears it.

This is largely due to VS 2022 (I skipped 2019 so it may be in 2019) ability to leave the console open when debugging ends.  If you turn off that option, this is not an issue.

**Comment by zadjii-msft** [comment]
Are you using the Windows Terminal, or the vintage windows console (`conhost.exe`)?

**Comment by towel42-com** [comment]
WT Multiple tabs and all :) Ive noticed this on a couple of machines

**Comment by zadjii-msft** [comment]
Which version of the Terminal/? There was something like this that was fixed in 1.18...

**Comment by towel42-com** [comment]
1.17.11461.0  Ill go to the windows store and update and see if that fixes it

**Comment by zadjii-msft** [comment]
1.17 is the latest version of Terminal _Stable_, 1.18 can be found here: https://aka.ms/terminal-preview. You can then set that as the "Default Terminal Application" in the settings app (or settings UI of the Terminal), and have VS launch that one instead.

**Comment by towel42-com** [comment]
I realized that once I went to the store.  I installed the preview, it appears to have fixed the issue.  However, so Im closing this issue.  If I see it again, Ill re-open

**Comment by zadjii-msft** [comment]
Great, I bet this was /dup #14512. Thanks for confirming!

**Comment by robbrink-rightware** [comment]
This is still happening for me with Windows Terminal 1.19.10573.0
