### ISSUE TITLE
Automatically switch color scheme file

### ISSUE THREAD

**Issue by Frozen-hc** [microsoft/terminal#15767]
# Description of the new feature/enhancement
Automatically switch color scheme files over time or windows theme configuration. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
> or windows theme configuration.

You mean like this: [Color scheme](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)/?

> In addition to a single color scheme name, this property can accept a pair of color scheme names as follows:
> 
> ```json
> "colorScheme":
> {
>     "light": "One Half Light",
>     "dark": "One Half Dark",
> },
> ```
> 
> When specified in this manner, the Terminal will automatically switch between the two given color schemes depending on the theme of the application. The Terminal will follow the [`theme.applicationTheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#application-theme) property of the Terminal's selected theme. If that `applicationTheme` is set to `system`, **then this will instead use the color scheme matching the OS theme**.

_emphasis added_

**Comment by Frozen-hc** [comment]
> > or windows theme configuration.
> 
> You mean like this: [Color scheme](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)/?
> 
> > In addition to a single color scheme name, this property can accept a pair of color scheme names as follows:
> > ```json
> > "colorScheme":
> > {
> >     "light": "One Half Light",
> >     "dark": "One Half Dark",
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When specified in this manner, the Terminal will automatically switch between the two given color schemes depending on the theme of the application. The Terminal will follow the [`theme.applicationTheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#application-theme) property of the Terminal's selected theme. If that `applicationTheme` is set to `system`, **then this will instead use the color scheme matching the OS theme**.
> 
> _emphasis added_

**Comment by Frozen-hc** [comment]
Thank you very much for your answer, I switched to the preview version and then changed the colorScheme settings as you said and my problem was solved perfectly, now I can see the text I'm typing clearly both day and night!

> > or windows theme configuration.
> 
> You mean like this: [Color scheme](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)/?
> 
> > In addition to a single color scheme name, this property can accept a pair of color scheme names as follows:
> > ```json
> > "colorScheme":
> > {
> >     "light": "One Half Light",
> >     "dark": "One Half Dark",
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When specified in this manner, the Terminal will automatically switch between the two given color schemes depending on the theme of the application. The Terminal will follow the [`theme.applicationTheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#application-theme) property of the Terminal's selected theme. If that `applicationTheme` is set to `system`, **then this will instead use the color scheme matching the OS theme**.
> 
> _emphasis added_

Thank you very much for your answer, I switched to the preview version and then changed the colorScheme settings as you said and my problem was solved perfectly, now I can see the text I'm typing clearly both day and night!
