### ISSUE TITLE
Introduce an option to configure where duplicated tabs open

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#15776]
> Hi, I know this issue is closed, but I actually find it annoying. I liked that duplicate tabs would open at the end... not next to the one that is duplicated. Can you please provide setting, where this can be changed between two options?

_Originally posted by @noheromen in https://github.com/microsoft/terminal/issues/14521#issuecomment-1654527281_

**Comment by carlos-zamora** [comment]
Discussed as a team. We should make duplicate tab respect the existing setting to open new tabs at the current index or at the end of the list.

**Comment by codecruisedor** [comment]
Hi @carlos-zamora, asking this just for my own clarity..we need to make the duplicate tab consider the existing setting called '**Position of newly created tabs**', right? If yes, then perhaps we can rename it to **'Position of newly created and duplicated tabs'** if that seems appropriate.
![Screenshot 2023-09-14 003444](https://github.com/microsoft/terminal/assets/25024714/00a10123-982f-4cb9-b5a1-ee1a411736ae)
