### ISSUE TITLE
"Enable acrylic material" is not working

### ISSUE THREAD

**Issue by ksio89** [microsoft/terminal#15774]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3271

### Steps to reproduce

Toggle on "Enable acrylic material" at Appearance>Transparency menu

### Expected Behavior

A translucent texture should be applied to the background of the window.

### Actual Behavior

The translucent texture is not applied to the background of the window, neither for Prompt command nor PowerShell, Azure Cloud Shell and VS 2022 windows . Tested pretty much everything by enabling it with diferent themes, tools, oppacity values, on both default and specific profiles and even edited settings.json and added a ``"useAcrylic": true`` line for different color schemes and still nothing. Does this feature actually work or is it a bug with the installation on my computer?

**Comment by msaic07** [comment]
Hey, for me the "Enable acrylic material" setting only worked while editing the settings on the specific profiles. Initially, the default profile didn't work but after messing with the values in the PowerShell profile and resetting it, the default profile only worked then. I don't know why that happened though because I have never changed the settings in the PowerShell profile before.

**Comment by ksio89** [comment]
Interesting, thanks for the feedback. For me the option is only applied after rebooting, maybe after logging off and in again, but I haven't tested it yet. No big deal, sooner or later it will work.

**Comment by ksio89** [comment]
Interesting, thanks for the feedback. For me the option is only applied after rebooting, maybe after logging off and in again, but I haven't tested it yet. No big deal, sooner or later it will work.

**Comment by m4ti4s1** [comment]
For me the problem was that I had the power saver on, I turn it off and it work again.

**Comment by Eronate** [comment]
> For me the problem was that I had the power saver on, I turn it off and it work again.

bless you

**Comment by MohabCodeX** [comment]
## **Enabling Transparency effects 100% fixes this issue.**

<img width="646" height="460" alt="Image" src="https://github.com/user-attachments/assets/311bc8c6-2313-4d53-9412-58c70d73dc63" />
