### ISSUE TITLE
Setting up shortcut key

### ISSUE THREAD

**Issue by m-abubakar** [microsoft/terminal#15778]
### Steps to reproduce

I have two questions. 
How can I set F12 as shortcut to toggle Quake window? it does not work. But when I set F9 key it works fine.
How can I set the quake window to full screen when launched.

### Expected Behavior

Setting F12 as shortcut key to toggle quake window works.

### Actual Behavior

Setting F12 as shortcut key to toggle quake window does not work.

**Comment by m-abubakar** [comment]
Hi, [ManuPer3z](https://github.com/ManuPer3z),

Thank you so much for taking time and providing such a detailed and comprehensive answer. unfortunately though, both of your suggestions did not work. Quake window height stays the same and f12 also doesn't toggle the quake window.

I am attaching my config below. May be I have been doing something really wrong.

`{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
				{
						"command": 
						{
								"action": "globalSummon",
								"dropdownDuration": 1,
								"toggleVisibility": true,
								"name": "QuakeMode"
						},
						"keys": "f12"
				},
        {
            "command": 
            {
                "action": "commandPalette"
            },
            "keys": "ctrl+shift+p"
        },
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 3
            },
            "keys": "alt+4"
        },
        {
            "command": "paste"
        },
        {
            "command": "toggleAlwaysOnTop",
            "keys": "alt+shift+f11"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 7
            },
            "keys": "alt+8"
        },
        {
            "command": "unbound",
            "keys": "ctrl+d"
        },
        {
            "command": "unbound",
            "keys": "win+sc(41)"
        },
        {
            "command": "unbound",
            "keys": "ctrl+w"
        },
        {
            "command": "unbound",
            "keys": "ctrl+t"
        },
        {
            "command": "unbound",
            "keys": "ctrl+v"
        },
        {
            "command": "unbound",
            "keys": "f10"
        },
        {
            "command": "unbound",
            "keys": "backspace"
        },
        {
            "command": "unbound",
            "keys": "f12"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+1"
        },
        {
            "command": "unbound",
            "keys": "ctrl+1"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+2"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+3"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+4"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+5"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+6"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+7"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+8"
        },
        {
            "command": "unbound",
            "keys": "ctrl+alt+9"
        },
        {
            "command": "unbound",
            "keys": "shift+1"
        },
        {
            "command": "unbound",
            "keys": "shift+2"
        },
        {
            "command": "unbound",
            "keys": "shift+3"
        },
        {
            "command": "unbound",
            "keys": "shift+4"
        },
        {
            "command": "unbound",
            "keys": "shift+5"
        },
        {
            "command": "unbound",
            "keys": "shift+6"
        },
        {
            "command": "unbound",
            "keys": "shift+7"
        },
        {
            "command": "unbound",
            "keys": "shift+8"
        },
        {
            "command": "unbound",
            "keys": "shift+9"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        },
        {
            "command": "closePane"
        },
        {
            "command": 
            {
                "action": "splitPane"
            },
            "keys": "ctrl+shift+minus"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 6
            },
            "keys": "alt+7"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 5
            },
            "keys": "alt+6"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 2
            },
            "keys": "alt+3"
        },
        {
            "command": 
            {
                "action": "newTab"
            }
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 1
            },
            "keys": "alt+2"
        },
        {
            "command": "toggleFocusMode",
            "keys": "shift+f11"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 0
            },
            "keys": "alt+1"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 4
            },
            "keys": "alt+5"
        },
        {
            "command": 
            {
                "action": "switchToTab",
                "index": 4294967295
            },
            "keys": "alt+9"
        }
    ],
		"defaultTabHeight": 100,
    "alwaysShowNotificationIcon": true,
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "experimental.rendering.software": true,
    "initialCols": 120,
    "initialRows": 30,
    "minimizeToNotificationArea": true,
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": 
        {
            "bellStyle": 
            [
                "audible",
                "window",
                "taskbar"
            ],
            "font": 
            {
                "face": "FiraCode Nerd Font",
                "size": 13.0
            },
            "opacity": 75
        },
        "list": 
        [
            {
                "cursorShape": "filledBox",
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{e58ba53f-c360-5e5c-b3c7-498d490b0751}",
                "hidden": false,
                "name": "Yori",
                "source": "Yori"
            },
            {
                "commandline": "C:/WINDOWS/SysWOW64/WindowsPowerShell/v1.0/powershell.exe -noe -c \"&{Import-Module \"\"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"\"\"; Enter-VsDevShell a179bff0}\"",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff45ce}",
                "hidden": false,
                "name": "VS2019 Dev Prompt",
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
                "hidden": false,
                "name": "Git Bash",
                "source": "Git"
            },
            {
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            },
            {
                "guid": "{232bfd8d-3015-5fc5-8179-7a7e01b7bcab}",
                "hidden": false,
                "name": "Developer Command Prompt for VS 2019",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "guid": "{ea98f48b-8140-5da7-8e77-f0d9391060b4}",
                "hidden": false,
                "name": "Developer PowerShell for VS 2019",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "guid": "{4dd1e689-b517-5f39-947d-78e8a8bdf958}",
                "hidden": false,
                "name": "Ubuntu 20.04.6 LTS",
                "source": "CanonicalGroupLimited.Ubuntu20.04LTS_79rhkp1fndgsc"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#212121",
            "black": "#151515",
            "blue": "#6C99BB",
            "brightBlack": "#505050",
            "brightBlue": "#6C99BB",
            "brightCyan": "#7DD6CF",
            "brightGreen": "#7E8E50",
            "brightPurple": "#9F4E85",
            "brightRed": "#AC4142",
            "brightWhite": "#F5F5F5",
            "brightYellow": "#E5B567",
            "cursorColor": "#D0D0D0",
            "cyan": "#7DD6CF",
            "foreground": "#D0D0D0",
            "green": "#7E8E50",
            "name": "Afterglow",
            "purple": "#9F4E85",
            "red": "#AC4142",
            "selectionBackground": "#303030",
            "white": "#D0D0D0",
            "yellow": "#E5B567"
        },
        {
            "background": "#0F1610",
            "black": "#112616",
            "blue": "#2F6A7F",
            "brightBlack": "#3C4812",
            "brightBlue": "#00AAE0",
            "brightCyan": "#00E0C4",
            "brightGreen": "#18E000",
            "brightPurple": "#0058E0",
            "brightRed": "#E08009",
            "brightWhite": "#73FA91",
            "brightYellow": "#BDE000",
            "cursorColor": "#73FA91",
            "cyan": "#327F77",
            "foreground": "#637D75",
            "green": "#2F7E25",
            "name": "AlienBlood",
            "purple": "#47587F",
            "red": "#7F2B27",
            "selectionBackground": "#1D4125",
            "white": "#647D75",
            "yellow": "#717F24"
        },
        {
            "background": "#1C1C1C",
            "black": "#3D352A",
            "blue": "#6495ED",
            "brightBlack": "#554444",
            "brightBlue": "#87CEEB",
            "brightCyan": "#B0C4DE",
            "brightGreen": "#88AA22",
            "brightPurple": "#996600",
            "brightRed": "#CC5533",
            "brightWhite": "#DDCCBB",
            "brightYellow": "#FFA75D",
            "cursorColor": "#E2BBEF",
            "cyan": "#B0C4DE",
            "foreground": "#DDEEDD",
            "green": "#86AF80",
            "name": "Arthur",
            "purple": "#DEB887",
            "red": "#CD5C5C",
            "selectionBackground": "#4D4D4D",
            "white": "#BBAA99",
            "yellow": "#E8AE5B"
        },
        {
            "background": "#20111B",
            "black": "#20111B",
            "blue": "#426A79",
            "brightBlack": "#5E5252",
            "brightBlue": "#426A79",
            "brightCyan": "#989A9C",
            "brightGreen": "#858162",
            "brightPurple": "#97522C",
            "brightRed": "#BE100E",
            "brightWhite": "#D5CCBA",
            "brightYellow": "#EAA549",
            "cursorColor": "#968C83",
            "cyan": "#989A9C",
            "foreground": "#968C83",
            "green": "#858162",
            "name": "Belafonte Night",
            "purple": "#97522C",
            "red": "#BE100E",
            "selectionBackground": "#45373C",
            "white": "#968C83",
            "yellow": "#EAA549"
        },
        {
            "background": "#2A1F1D",
            "black": "#573D26",
            "blue": "#5A86AD",
            "brightBlack": "#9B6C4A",
            "brightBlue": "#B8D3ED",
            "brightCyan": "#93CFD7",
            "brightGreen": "#95D8BA",
            "brightPurple": "#D19ECB",
            "brightRed": "#E84627",
            "brightWhite": "#FFF9D5",
            "brightYellow": "#D0D150",
            "cursorColor": "#573D26",
            "cyan": "#74A6AD",
            "foreground": "#E0DBB7",
            "green": "#6BA18A",
            "name": "BirdsOfParadise",
            "purple": "#AC80A6",
            "red": "#BE2D26",
            "selectionBackground": "#563C27",
            "white": "#E0DBB7",
            "yellow": "#E99D2A"
        },
        {
            "background": "#006984",
            "black": "#292D3E",
            "blue": "#82AAFF",
            "brightBlack": "#434758",
            "brightBlue": "#9CC4FF",
            "brightCyan": "#A3F7FF",
            "brightGreen": "#DDFFA7",
            "brightPurple": "#DDB0F6",
            "brightRed": "#FF8B92",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFE585",
            "cursorColor": "#FFCC00",
            "cyan": "#89EBFF",
            "foreground": "#C5F2FF",
            "green": "#B4E88D",
            "name": "BlueDolphin",
            "purple": "#E9C1FF",
            "red": "#FF8288",
            "selectionBackground": "#2BAECA",
            "white": "#D0D0D0",
            "yellow": "#F4D69F"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#0000AA",
            "brightBlack": "#555555",
            "brightBlue": "#5555FF",
            "brightCyan": "#55FFFF",
            "brightGreen": "#55FF55",
            "brightPurple": "#FF55FF",
            "brightRed": "#FF5555",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF55",
            "cursorColor": "#FFFFFF",
            "cyan": "#00AAAA",
            "foreground": "#AAAAAA",
            "green": "#00AA00",
            "name": "CGA",
            "purple": "#AA00AA",
            "red": "#AA0000",
            "selectionBackground": "#FFFFFF",
            "white": "#AAAAAA",
            "yellow": "#AA5500"
        },
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#191C27",
            "black": "#181818",
            "blue": "#576D8C",
            "brightBlack": "#555555",
            "brightBlue": "#3097C6",
            "brightCyan": "#F3DBB2",
            "brightGreen": "#A6A75D",
            "brightPurple": "#D33061",
            "brightRed": "#AC3835",
            "brightWhite": "#F4F4F4",
            "brightYellow": "#DCDF7C",
            "cursorColor": "#92805B",
            "cyan": "#5C4F4B",
            "foreground": "#AEA47A",
            "green": "#48513B",
            "name": "Ciapre",
            "purple": "#724D7C",
            "red": "#810009",
            "selectionBackground": "#172539",
            "white": "#AEA47F",
            "yellow": "#CC8B3F"
        },
        {
            "background": "#FBF1C7",
            "black": "#FBF1C7",
            "blue": "#076678",
            "brightBlack": "#9D8374",
            "brightBlue": "#458588",
            "brightCyan": "#689D69",
            "brightGreen": "#98971A",
            "brightPurple": "#B16186",
            "brightRed": "#CC241D",
            "brightWhite": "#7C6F64",
            "brightYellow": "#D79921",
            "cursorColor": "#282828",
            "cyan": "#427B58",
            "foreground": "#282828",
            "green": "#79740E",
            "name": "Gruvbox Light",
            "purple": "#8F3F71",
            "red": "#9D0006",
            "selectionBackground": "#D5C4A1",
            "white": "#3C3836",
            "yellow": "#B57614"
        },
        {
            "background": "#1B1B1B",
            "black": "#1B1B1B",
            "blue": "#458588",
            "brightBlack": "#928374",
            "brightBlue": "#83A598",
            "brightCyan": "#8EC07C",
            "brightGreen": "#B8BB26",
            "brightPurple": "#D3869B",
            "brightRed": "#FB4934",
            "brightWhite": "#EBDBB2",
            "brightYellow": "#FABD2F",
            "cursorColor": "#EBDBB2",
            "cyan": "#689D6A",
            "foreground": "#EBDBB2",
            "green": "#98971A",
            "name": "GruvboxDarkHard",
            "purple": "#B16286",
            "red": "#CC241D",
            "selectionBackground": "#665C54",
            "white": "#A89984",
            "yellow": "#D79921"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-20.04-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        },
        {
            "background": "#0F1419",
            "black": "#000000",
            "blue": "#36A3D9",
            "brightBlack": "#323232",
            "brightBlue": "#68D5FF",
            "brightCyan": "#C7FFFD",
            "brightGreen": "#EAFE84",
            "brightPurple": "#FFA3AA",
            "brightRed": "#FF6565",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFF779",
            "cursorColor": "#F29718",
            "cyan": "#95E6CB",
            "foreground": "#E6E1CF",
            "green": "#B8CC52",
            "name": "ayu",
            "purple": "#F07178",
            "red": "#FF3333",
            "selectionBackground": "#253340",
            "white": "#FFFFFF",
            "yellow": "#E7C547"
        }
    ],
    "startOnUserLogin": true,
    "theme": "dark",
    "themes": 
    [
        {
            "name": "legacyDark",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "dark",
                "useMica": false
            }
        },
        {
            "name": "legacyLight",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "light",
                "useMica": false
            }
        },
        {
            "name": "legacySystem",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "system",
                "useMica": false
            }
        }
    ]
}`

**Comment by ManuPer3z** [comment]
Hi @m-abubakar 


I see the section that contains your key bindings. Based on what you've shared, there are a few key points to note:

Your configuration for toggling the Quake mode with F12 seems correct:

```
{
    "command": {
        "dropdownDuration": 1,
        "toggleVisibility": true,
        "name": "QuakeMode"
    },
    "keys": "f12"
}
```
However, you also have another entry further below that unbinds the F12 key:

```
{
    "command": "unbound",
    "keys": "f12"
}
```

This would negate the binding to Quake mode. Remove this unbinding to make F12 work for toggling the Quake mode.

I noticed several key combinations that are "unbound". If these are intentional (to ensure certain combinations don't perform their default actions), that's okay. However, if they're unintentional, you might want to reconsider whether you need all of them.
If you've provided this segment accurately and it's sequential in your settings.json, then everything seems in order for the key bindings section

Quake window height stays the same:
Your config also has a setting for defaultTabHeight:

"defaultTabHeight": 100

The Quake mode usually utilizes the initialRows setting to determine its height. In your provided configuration, this is set to 30 rows:

"initialRows": 30

If you'd like to adjust the height of the Quake window, you can modify the initialRows setting. For instance, setting it to 15 will make the Quake window half as tall (assuming a standard full screen terminal is 30 rows tall).

I hope this helps ,

best regards.

**Comment by m-abubakar** [comment]
Nice catch of the "f12" entry in the config file. I completely forgot about it.
But unfortunately after removing it. I still have the same issue. "F12" don't work.

I am afraid there is a failure on quake window fullscreen end as well. "initialRows" only affects the Terminal window and have no affect on quake window. Same is the case if I set launch mode to fullscreen.

**Comment by ManuPer3z** [comment]
Confirm if the F12 key is working for other applications or functionalities to rule out a hardware or OS-level shortcut issue.

Check if you have any other software running that might be intercepting or using the F12 key. Some applications, especially development tools or screen capture tools, might have F12 bound to specific actions.

Make sure that the "keys": "f12" command is the only command associated with the toggleVisibility action. If you have other configurations using the same action, it might cause conflicts.

Try launching Windows Terminal from the command line or another terminal and see if there are any error messages displayed when you press F12. Sometimes, terminal outputs can give a clue about what's going wrong.

Reset your Windows Terminal configuration to the default settings to see if the issue persists. If the default configuration works, you can then incrementally apply your desired settings to pinpoint which one causes the problem.

Open Windows Terminal and then open the Feedback Hub app. Reproduce the issue with the F12 key and then check the Feedback Hub for any relevant events or error messages. This might give more insight.

As an alternative solution, you can try to assign another key or combination of keys for the toggleVisibility action, and see if that works.

I can't think of anything else and reviewing the code I see it is correct. I hope this helps you,

Best Regards.

**Comment by zadjii-msft** [comment]
Actually, this is unfortunately something by design. SPECIFICALLY for the F12 key. As we found out earlier:

> The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident.

(From the [`RegisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) docs)

I maintain that I don't think it's in our best interest to steal F12 away from debuggers. 

/dup #13775
