### ISSUE TITLE
Add a "search tab" feature

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#15772]
# Description of the new feature/enhancement

It would be useful to have a means to perform the equivalent to Ctrl+Shift+A in browsers such as Edge: pop-up a list of running tabs, with a search box so that it's easy to switch to another tab when 😜 you have (too 🙃?) many tabs open.

(Amazing, that Edge feature is not listed at https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad nor at https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/shortcuts/)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Something like [`tabSearch`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#tab-search)/?

![](https://learn.microsoft.com/en-us/windows/terminal/images/tab-search.gif)

**Comment by sba923** [comment]
What is this a duplicate of?

**Comment by zadjii-msft** [comment]
Some issue from like, 2 years ago when we added this. I was being lazy and not looking it up 😝

**Comment by zadjii-msft** [comment]
* #1502
* #3753
* #6732

**Comment by sba923** [comment]
Thanks for the pointers, and sorry for the duplicate.

For some reason I couldn't find the feature when searching for "search tabs" prior to creating my issue.

The Command Palette doesn't make that discoverable.

Once you know that this is an _action_ that can be bound to a key, *and* that it's name starts with the word "Search", you can use the feature.

😜

**Comment by sba923** [comment]
BTW, I have the feeling I'll be using this way more often than the "Switch to tab, index:N" actions. Probably 'cos the tab order is by no means guaranteed to be the same from one session to the next (as opposed to the Windows taskbar-pinned shortcuts)?

YMMV, of course.

**Comment by sba923** [comment]
BTW, just discovered that searching for "too" matches "new_paymen**t**_s**o**luti**o**n"

Quite unexpected if you ask me...
