### ISSUE TITLE
Tab Protection

### ISSUE THREAD

**Issue by majerus1223** [microsoft/terminal#15777]
# Description of the new feature/enhancement

Tab Protection to keep long running processes, development scripts from being accidently closed via close all button within the terminal. 

# Proposed technical implementation details (optional)

When you right click the tab, you have an option to "Protect" , "Pin", "Guard" or something like that to the specific tab you have open.
If you click the right most X, on the terminal app close all non "Protected" tabs
Pop up a toast or message asking if you would like to close the protected tab and or if multiple tabs . (I would have two buttons one for single tab, one for all)

![image](https://github.com/microsoft/terminal/assets/7389171/5818aa47-d1a7-4597-bd08-694015fe2038)

**Comment by zadjii-msft** [comment]
Would something like [read-only mode](https://learn.microsoft.com/en-us/windows/terminal/panes#marking-a-pane-as-read-only) work for you/? That's a bit more heavy handed - that disables closing AND input. 

If not, then this should probably be duped to #6549 (which is broadly tracking all the combinations of "prompt me before I close a {{thing}}")

**Comment by majerus1223** [comment]
The read only mode is interesting. I would say for now maybe #6549 makes some sense as its appear more like what I was shooting for.
