### ISSUE TITLE
Scroll doesn't work in less

### ISSUE THREAD

**Issue by IvoryJam** [microsoft/terminal#15785]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Other Software

less 590 (inside WSL)

### Steps to reproduce

run `less` inside WSL on a file larger than the window
try to use the scroll wheel

### Expected Behavior

`less` will scroll up/down 

### Actual Behavior

no scrolling happens

**Comment by IvoryJam** [comment]
Yes that works, sorry about opening a dup bug

**Comment by zadjii-msft** [comment]
Oh no worries, this is a _subtle_ one 😉 

/dup #13187
