### ISSUE TITLE
Launch Quake window in fullscreen

### ISSUE THREAD

**Issue by m-abubakar** [microsoft/terminal#15784]
### Steps to reproduce

How can I configure quake so that when I press a key to launch it, The window is launched in fullscreen.

I have tried "defaultTabHeight": 100 and "initialRows": 100 but unfortunately this is only applied to main Terminal window and not to quake window. 

I want something that will only affect quake window.

Also is there a way I can set the Terminal to launch in hidden mode ( only tray icon ), when set to launch on windows startup. Currently when the Terminal is launched, The main window is displayed.

Thanks.

### Expected Behavior

Quake window to launch in full screen mode.
Terminal to start in hidden mode on windows startup

### Actual Behavior

Quake window does not launch in full screen mode.
Terminal window is shown on windows startup

**Comment by zadjii-msft** [comment]
> How can I configure quake so that when I press a key to launch it, The window is launched in fullscreen.

Currently, that's not possible. That's more or less tracked in /dup #9992.

You could always configure the Terminal to normally open in fullscreen or maximized mode, and just use the `globalSummon` action to focus the terminal, rather using specifically the quake window. That's basically what I do. YMMV. 

> is there a way I can set the Terminal to launch in hidden mode

Not currently. That's tracked in /dup #9996, /dup #13630, and /dup #7374
