### ISSUE TITLE
Hidden window opens about 30 seconds after new tab/session, stealing focus

### ISSUE THREAD

**Issue by ryanmda** [microsoft/terminal#15786]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3208

### Steps to reproduce

Open a new tab

### Expected Behavior

Normal OS behaviour

### Actual Behavior

After 30 seconds of opening a new window or tab, the window loses focus and a hidden window appears to have focus. If Windows terminal did not have focus, it is brought to the front, then the additional hidden window still ends up with focus.

Using Alt + Space on the hidden window, I am able to pretend to move or restore/minimize/maximize it, but not clearly identify what it is for.

**Comment by ryanmda** [comment]
I tried searching for this issue and couldn't find it with the keywords I used. #15536 seems close-ish though.

**Comment by zadjii-msft** [comment]
Is there any chance you're in some sort of environment that's using BeyondTrust / CyberArk / Avecto or something like that/? This sounds a lot like what was in #13388 which mostly boiled down to that

**Comment by ryanmda** [comment]
Yeah, BeyondTrust. It's interesting that the other thread implies focus is taken right away, whereas here it's after a delay. It's also curious I didn't see it on an earlier version.

**Comment by ryanmda** [comment]
Okay, I did some version testing.
* Version 1.13 works perfectly. Never loses focus to a hidden window
* Version 1.14 loses focus once immediately on startup, but not with new tabs
* Versions 1.15 through 1.18 preview all manifest the behaviour on this ticket

**Comment by zadjii-msft** [comment]
Alrighty thanks for following up! Yea this one is _m y s t e r i o u s_ to say the least 😅 

/dup #13388
