### ISSUE TITLE
Windows Terminal Crashes on Startup

### ISSUE THREAD

**Issue by petlikarayan** [microsoft/terminal#15792]
### Windows Terminal version

1.18.1462.0

### Windows build number

22621.2070

### Steps to reproduce

Just opening the windows terminal.

From the event viewer:

Faulting application name: WindowsTerminal.exe, version: 1.18.2305.26002, time stamp: 0x64714178
Faulting module name: d2d1.dll, version: 10.0.22621.1635, time stamp: 0x265f3f6e
Exception code: 0xc0000005
Fault offset: 0x0000000000088898
Faulting process id: 0x0x3F88
Faulting application start time: 0x0x1D9C5C2F9F5BCAC
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.18.1462.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d2d1.dll
Report Id: 70635396-548b-4959-a569-620ef774f8dd
Faulting package full name: Microsoft.WindowsTerminalPreview_1.18.1462.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### Actual Behavior

Crashes the app

**Comment by zadjii-msft** [comment]
Ooh a D2D1 crash, fascinating. We might need an actual crash dump to look into this - that Report ID didn't show up on the backend. 

/feedback

or alternatively: https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#capturing-and-sending-dumps

**Comment by lhecker** [comment]
Do you use mactype? If so, please upgrade to 2023.5.31. It contains my bugfix: https://github.com/snowie2000/mactype/pull/938

**Comment by petlikarayan** [comment]
> Do you use mactype? If so, please upgrade to 2023.5.31. It contains my bugfix: https://github.com/snowie2000/mactype/pull/938

Yeah I do updated it works fine now thanks.
