### ISSUE TITLE
Add new language (Polish) as a new option in Settings -> Language (requires relauch)

### ISSUE THREAD

**Issue by AverageGHenjoyer** [microsoft/terminal#15790]
# Description of the new feature/enhancement
Hello. When I was on Microsoft Terminal's Microsoft Store website, I noticed a lot of Polish people's reviews about the application's demanding Polish language. My question is: is there a way to contribute to this kind of idea of translating? I would be happy to see an answer to that. Thank you.

**Comment by zadjii-msft** [comment]
Great idea! We're largely tracking this sort of thing in #10667. That thread has kinda evolved into "is it technically possible for us to accept partial translations for other languages (that we can't auto-translate)?". We're pretty sure that it _is_ possible, we just need someone to do the diligence of actually trying it!

I'm gonna close this thread in favor of merging discussion with that thread. Thanks!

/dup #10667
