### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by zhangjinbao3114** [microsoft/terminal#1579]
# Environment
Microsoft Windows [版本 10.0.18922.1000]

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):
0.2.1715.0
Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

1、Failed to find setup options to modify background（Requirements）
2、When multiple windows are used, the tab bar cannot be automatically expanded or retracted.
3、Cannot modify the behavior of the default + sign（Requirements）
4、Right click to copy text failed
5、Two different expected results occur when copying with ctrl + C characters（Hope to optimize）

**Comment by DHowett-MSFT** [comment]
Sorry, we can’t deal with bug reports that contain so many different things!

**Comment by DHowett-MSFT** [comment]
Please make sure your bug reports are as specific as possible.
