### ISSUE TITLE
Ability to Export Text from split tabs

### ISSUE THREAD

**Issue by stevenjudd** [microsoft/terminal#15804]
# Description of the new feature/enhancement

When using the Split Tab feature, there is no way to Export Text from the tab that is not the last tab opened. Highlighting a tab and choosing Export Text from the menu only exports text from the last tab opened. I was able to export the text of a previous tab by closing the console that was opened when I selected Split Tab, so I was back to the original console, and Export Text.

# Proposed technical implementation details (optional)

I would like a way to export the selected, highlighted, or specified in some way, tab's text without having to close the split console window.

**Comment by zadjii-msft** [comment]
What version are you on/? I'm pretty sure this was fixed in 1.17 in #14673
