### ISSUE TITLE
Bug Report - Windows Terminal Settings Window

### ISSUE THREAD

**Issue by ExoLightFR** [microsoft/terminal#1580]
# Environment

```none
Windows build number: [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

- Open the Windows Terminal
- Open the Setting menu, either by pressing Ctrl + , or clicking on the Settings button in the dropdown menu next to the new tab button

# Expected behavior

The Windows Terminal settings window showing up.

# Actual behavior

Windows asking me how do I want to open this file, specifying that it's a .json file in the "Always use this app to open .json files" ; see picture attached below.

![windows terminal settings bug](https://user-images.githubusercontent.com/40464519/60073139-ed264780-971f-11e9-9dc1-89078e013b2b.png)

**Comment by vhanla** [comment]
In my case, it doesn't even show that. It does nothing. I have to look for that file manually.

**Comment by DHowett-MSFT** [comment]
#1460

**Comment by ExoLightFR** [comment]
Update and solution : the Windows Terminal doesn't yet have a Settings window, but a .json file. Issue solved by associating Notepad++ with .json files. Duplicate of #1460, apologies.
