### ISSUE TITLE
Split-pane with --duplicate does not duplicate the previously set title

### ISSUE THREAD

**Issue by Bisdow** [microsoft/terminal#15821]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Steps to reproduce

Start the terminal via command line with the following command:
wt new-tab --title CHANGED_TITLE --suppressApplicationTitle ; split-pane --vertical --duplicate

### Expected Behavior

The terminal opens, the tab title shows "CHANGED_TITLE".
When changing the pane, the tab title does not change (because its a duplicate from the first)

### Actual Behavior

When switching to the second pane, the title switches back to the default.

**Comment by zadjii-msft** [comment]
Yea I'm gonna call this /dup #9817
