### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tisukk** [microsoft/terminal#1583]
i think you must put cmd.exe by deafault at the start.

**Comment by JushBJJ** [comment]
What does this have to do with the new Terminal? You're talking about the old command prompt.

**Comment by Shorotshishir** [comment]
@tisukk u can customize your app to set whichever terminal u want to be the default. It is already there.

**Comment by cinnamon-msft** [comment]
You can change your default profile to cmd by changing the `"defaultProfile"` field in your profiles.json to the GUID assigned to your cmd profile
