### ISSUE TITLE
Can we write and integrate plugins/extensions into the terminal, which add some properties in settings? 

### ISSUE THREAD

**Issue by Kwillson2** [microsoft/terminal#15833]
# Description of the new feature/enhancement

Is there a similar plugin/extension feature for the Terminal like there is in VS Code?  I would like to write a plugin, which has some properties that will be set in settings?  I have looked all over and can't seem to find anything, but its FOSS so I would think there would be.

Thanks for your time!

**Comment by Justice603-tech** [comment]
Well....Bad news...for now there is no plugin/extension manager for Windows terminal. but there is some _good news_!

The good news is: if you want to customize anything in the terminal open up the json file. to open it i have added a picture of a button telling you to open the JSON file. from there: you can customize and create anything! like:

- Creating a custom theme. in the `themes` section of the file
- Adding custom color schemes with the `schemes` part. ex: 
```json
          {
            "background": "#151718",
            "black": "#151718",
            "blue": "#9D65FF",
            "brightBlack": "#625E4C",
            "brightBlue": "#9D65FF",
            "brightCyan": "#58D1EB",
            "brightGreen": "#98F424",
            "brightPurple": "#F4005F",
            "brightRed": "#F4005F",
            "brightWhite": "#F6F6EF",
            "brightYellow": "#FA8419",
            "cursorColor": "#FFFFFF",
            "cyan": "#58D1EB",
            "foreground": "#E9C3F8",
            "green": "#98F424",
            "name": "Monokai Seti Dark",
            "purple": "#F4005F",
            "red": "#F4005F",
            "selectionBackground": "#FFFFFF",
          } 
  ```
- and More!

**Comment by zadjii-msft** [comment]
There are also ["Fragment extensions"](https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions), which sounds a bit like what you want. You can even package these up as an app to share with others, if that's what you're trying to do.

Does that sound like it'll work for what you need/?
