### ISSUE TITLE
Syncing Profile Themes with System Colors

### ISSUE THREAD

**Issue by MusaSSH** [microsoft/terminal#15834]
# Description of the new feature/enhancement

In the Terminal, we can change its look to be dark, light, or match Windows colors. Dark is good in the dark, and light is better in bright environments.
![image](https://github.com/microsoft/terminal/assets/97892949/e22244a8-ff2e-4b7c-bcf4-63d7c6a8a056)

However, in Terminal profiles, we can't choose colors for when the Terminal is light or dark, we only have one color scheme option. GitHub and VSCode do this well. They let you sync with the system and pick a theme for light and dark modes.
![image](https://github.com/microsoft/terminal/assets/97892949/e6f9b09b-ea71-4505-ba37-e1ddc937f2f2)
![image](https://github.com/microsoft/terminal/assets/97892949/7dc26c4b-9584-408a-9cc3-2327972bdf22)
![image](https://github.com/microsoft/terminal/assets/97892949/938525a6-6838-4410-9c80-4f89bd2b1b98)
![image](https://github.com/microsoft/terminal/assets/97892949/5bb4a840-b298-4ab3-ab8f-962aaf70bce8)

This would be handy in the Terminal too. Instead of manually changing, if the Terminal profile color schemes followed system colors, like in GitHub and VSCode, it'd be easier. I even use a tool to switch Windows colors based on day and night, except the Terminal color schemes, I no more involve in switching colors.

**Comment by zadjii-msft** [comment]
You actually can do this in the Terminal already:

```json
"colorScheme":
{
    "light": "One Half Light",
    "dark": "One Half Dark",
},
```

[docs link](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)

**Comment by zadjii-msft** [comment]
... and it's not supported in the Settings UI yet, but that's tracked in #14475

**Comment by MusaSSH** [comment]
Thanks!
