### ISSUE TITLE
Transparency automatically disables when changing OS language

### ISSUE THREAD

**Issue by levotiger** [microsoft/terminal#15830]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045

### Steps to reproduce

1. Open Windows Terminal.
2. Change Terminal's window opacity via `Ctrl` + `Shift` + rotate the mouse wheel down (any transparency level will work).
3. Change OS's language via `Alt` + `Shift` or via `Win` + `Space`.

### Expected Behavior

Transparency should stay as was configured and do not change after language switch.

### Actual Behavior

After language switch transparency is disabled automatically.

![image](https://github.com/microsoft/terminal/assets/120279405/8a1c41c1-c957-4d8b-baf7-fa4601f8b45a)

![image](https://github.com/microsoft/terminal/assets/120279405/c2bcaeea-028d-4fd0-b210-dba33ae9623e)

![image](https://github.com/microsoft/terminal/assets/120279405/39be6d4a-d3b9-48ac-bfca-0b3bc45a05d3)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #11522 for more discussion.

/dup #11522
