### ISSUE TITLE
When cmd starts, characters appear or the cursor moves down

### ISSUE THREAD

**Issue by tang-nn** [microsoft/terminal#15836]
### Other Software

![image](https://github.com/microsoft/terminal/assets/98725149/5e268d45-a672-4fdd-aa55-8a049141029d)
![image](https://github.com/microsoft/terminal/assets/98725149/d32f1957-8e57-4a29-9d32-15c8cea1230b)

### Steps to reproduce

Start cmd with Windows Terminal

### Actual Behavior

When cmd starts, characters appear or the cursor moves down

**Comment by zadjii-msft** [comment]
Does this repro with [Terminal Preview](https://aka.ms/terminal-preview), v1.18/? I bet this is #14512
