### ISSUE TITLE
Bug Report: Unable to close the tabs.

### ISSUE THREAD

**Issue by andreabac3** [microsoft/terminal#1585]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
```

# Steps to reproduce
1. I have installed the Windows Terminal (new) from Microsoft Store
2. Then I have launched the Windows Terminal

# Actual behavior

I tried to close the tab I had opened and the terminal crashes every time.

**Comment by carlos-zamora** [comment]
Sounds like #1380
