### ISSUE TITLE
Let users write the next command while the previous one is still being executed.

### ISSUE THREAD

**Issue by LucasDondo** [microsoft/terminal#15854]
The problem is that sometimes a command takes too long to execute (and in the meantime, we want to start writing the one that follows). For example, we run something like `python -m pip install --upgrade pip`. But during the installation, we remember we must also install Django. So, instead of waiting for the previous execution to end and just then being able to write `python -m pip install django`, this feature would let users start writing the following command even before the previous one has finished. This way, while pip gets updated, we can start writing `python -m install django`. If I press enter, that command should be run right after the previous finishes. If not, then at least we already have it written for the very moment the first command finishes.

_P.D.: While testing, I saw that this is a thing already. What is missing is what I describe in the next paragraph: somehow **show** what is being written._

https://github.com/microsoft/terminal/assets/59975541/a468a88d-f136-4007-8793-3d7480ea7616

What I want to happen is that instead of the keyboard cursor being positioned at the very end of the terminal and that whatever I write in it get overlaped with the text generated by the previous command, it was positioned also at the bottom of the terminal but in a different "section", after the command's output. Whatever you write there is persistent and once the command execution comes to an end, whatever you wrote gets in the "traditional input of commands" (what appears in the video after the `tree` command finished).

**Comment by 237dmitry** [comment]
Run this as job. `python -m pip install --upgrade pip &`

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10690 for more discussion.

/dup #10690
