### ISSUE TITLE
[FEATURE] Make the retro terminal mode more configurable

### ISSUE THREAD

**Issue by spudpiggy** [microsoft/terminal#15852]
# Description of the new feature/enhancement

Retro terminal mode looks cool, but it also makes text really hard to see on my secondary (which is a crappy old Dell) and doesn't do much of anything on my primary (a 1080p tv, idk size in inches)
I'd like if it were more configurable, so that I could tweak it to be more/less effective.

# Proposed technical implementation details (optional)

Allow the following to be changed:

- Width of scanlines
- Size of the gap between two scanlines
- How dark that gap is
- How much glow is added to text; 0% is none, 100% is current, and 200% is 2x the current amount.

These settings should be applied on a per-monitor basis, since different monitors will need different amounts of tweaking.

**Comment by zadjii-msft** [comment]
Good news! The retro shader is just a specific example of [custom pixel shaders](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#pixel-shader-effects) for the Terminal. You can feel free to grab the source from [Retro.hlsl](https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Retro.hlsl), and modify it however you'd like!

**Comment by AdreKiseque** [comment]
While it is cool we can customize this ourselves, I still think a more user-friendly way to adjust the retro terminal parameters would be good. Personally, I love the retro terminal in concept but find it a little hard on the eyes... but it's not something I use enough to justify the trouble of poking at these advanced configurations.
