### ISSUE TITLE
Confuse?

### ISSUE THREAD

**Issue by tang-nn** [microsoft/terminal#15853]
Why do I directly double-click the cmd.exe file in the System32 directory, it will also open in Windows Terminal? How is it achieved? Ask for answers

**Comment by 237dmitry** [comment]
What is your default terminal application? Check settings of Windows Terminal or conhost.exe. In my settings "Let Windows decide"

**Comment by tang-nn** [comment]
I want to know how it works

**Comment by 237dmitry** [comment]
> I deleted the registry key HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe

You deleted console host settings for Windows\System32\cmd.exe (color, size, font etc) This out of subject.

> It should be a bug when my cmd is opened in Terminal

In my environment all works as expected (win 11 22H2).

- set default terminal application
- relogin (maybe no need to do)

**Comment by tang-nn** [comment]
![image](https://github.com/microsoft/terminal/assets/98725149/e57d754e-2f1d-4efd-86b8-750e4e67a6b6)
![image](https://github.com/microsoft/terminal/assets/98725149/c5508f4f-09e6-4e43-85ad-91f6a3eef677)
![image](https://github.com/microsoft/terminal/assets/98725149/36ea4932-8e13-4e80-87c1-4c0a47ac2811)

**Comment by zadjii-msft** [comment]
What you're seeing is the "Default Terminal" feature in Windows 11, which lets you change which application is used as the default terminal emulator for command-line applications. That was previously always "conhost.exe", but now the Windows Terminal can be used as the default emulator too. 

_How_ it works is... complicated... and I believe we're tracking writing those docs in #9462. It was originally spec'd here: #7414

The other comment you have in this thread, about the leading spaces, looks like it's the same thing we're discussing with you in #15836, so I'm gonna collapse that as off-topic.
