### ISSUE TITLE
Need a clear doc page that shows which OS versions Terminal will run on

### ISSUE THREAD

**Issue by kilasuit** [microsoft/terminal#15864]
Coming from this [issue in the PowerShell Repo (that I created)](https://github.com/PowerShell/PowerShell/issues/18148) I found PowerShell has this nice easy to understand document section for [supported versions of windows](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#supported-versions-of-windows)

[This Doc](https://learn.microsoft.com/en-gb/windows/terminal/distributions) is the closest similar one & I think could be updated to show where you expect Terminal to actually run, like as show above would provide much needed clarity going forward.

**Comment by zadjii-msft** [comment]
I mean, it's pretty front and center at the top of the [README](https://github.com/microsoft/terminal#installing-and-running-windows-terminal)

> Windows Terminal requires Windows 10 2004 (build 19041) or later

But we can just add a note at the top of that docs page too. No need to have a whole matrix of options - it's just >10.0.19041 for all terminal versions.

**Comment by kilasuit** [comment]
Sorry but this is what I mean by it's not clear & why just using build numbers makes it unclear & would with a matrix with clearer notes as to why it's unsupportable on those os'es would likely have stopped you having ever had the support 2016/2019 issues being raised. 
It also does not help that Windows 11 still shows up as Windows 10 in many places
being crystal clear helps stop confusion, and your docs in this case aren't crystal clear, hence the ask for a matrix.
I know to you & others within & outside Microsoft that build numbers make a lot of sense, but the way they are right now is super confusing to many of us, especially if we are managing mixed estates.

Just trying to give some honest and useful feedback here that would definitely help many going forward for what isn't really a big ask in much needed clarity.

**Comment by zadjii-msft** [comment]
Moved to our docs repo: https://github.com/MicrosoftDocs/terminal/issues/701

**Comment by kilasuit** [comment]
sorry for raising in the wrong repo @zadjii-msft & thank you for raising in the right one!
