### ISSUE TITLE
Settings open Visual Studio 2017

### ISSUE THREAD

**Issue by StefanFriptu** [microsoft/terminal#1586]
# Environment

```none
Windows build number: winnt 10.0.18362 on x86_64
Windows Terminal version (if applicable): 0.2.1715.0

Any other software? Visual Studio 2017
```

# Steps to reproduce

1. open windows terminal
2. click on arrow down near the plus button -> settings or directly click ctrl + ,
3. Visual Studio 2017 pops up
# Expected behavior

I would expect to see a settings menu, definitely not vs2017 

# Actual behavior

vs2017 popus up

**Comment by Shorotshishir** [comment]
perhaps In our Computer the Default application for opening .json files is VS2017, thus it is popping up.  Try changing the default for .json to a text editor. 

Refer to #1460

**Comment by dxk3355** [comment]
> perhaps In your Computer the Default application for opening .json files is VS2017, thus it is popping up. Try changing the default for .json to a text editor.
> 
> Refer to #1460

Having a .json file for settings is not really user friendly, this is a Windows tool not Linux.

**Comment by DHowett-MSFT** [comment]
@dxk3355 #1564 

Others: this is currently by design. Get a better JSON editor if you don’t want it to launch VS.
