### ISSUE TITLE
Add an introduction to the terminal, and make it more known in Windows itself.

### ISSUE THREAD

**Issue by MaxGaming64** [microsoft/terminal#15868]
# Description of the new feature/enhancement
Despite us having a modern console host with lots of customizability, most people don't even know much about it, since everyone are used to write "cmd.exe" or "Command Prompt" in the start menu. Yes, it may redirect them to the Terminal, but I think there should be some kind of proper introduction, telling them what you can do with it. And also, this means that people will get to the old, outdated Command Prompt, not PowerShell.

# Proposed technical implementation details
I'd say remove the command prompt and PowerShell options completely from the start menu, and if typed, it would redirect them to the Windows Terminal.

**Comment by 237dmitry** [comment]
> I'd say remove the command prompt and PowerShell options completely from the start menu, and if typed, it would redirect them to the Windows Terminal.

What if I want an "old, outdated" Windows Console Host? If it were possible to disable scrollbars in conhost and it supported hyperlinks, then I would only use it.

Set Windows Terminal as your default terminal application and you'll get the results you want.

**Comment by MaxGaming64** [comment]
> > I'd say remove the command prompt and PowerShell options completely from the start menu, and if typed, it would redirect them to the Windows Terminal.
> 
> 
> 
> What if I want an "old, outdated" Windows Console Host? If it were possible to disable scrollbars in conhost and it supported hyperlinks, then I would only use it.
> 
> 
> 
> Set Windows Terminal as your default terminal application and you'll get the results you want.

Well, for that, you can simply set your default console host in the settings of the terminal. That's what I did at first when I wasn't used to it.

**Comment by zadjii-msft** [comment]
We may want to de-dupe this to #10213

**Comment by MaxGaming64** [comment]
> We may want to de-dupe this to #10213

Yep, that issue is exactly what I'm talking about. Introduce them to the modern PowerShell, and show around the features that the new terminal supports.

**Comment by zadjii-msft** [comment]
Thanks for the input here!

/dup #10213
