### ISSUE TITLE
Feature Request: Vertical and horizontal splitting of terminal

### ISSUE THREAD

**Issue by jagpreetstamber** [microsoft/terminal#1587]
# Summary of the new feature/enhancement

As a developer we are always working with multiple terminal windows at the moment, tabs make it easier, but makes it difficult in certain scenarios. If we have an ability to split the terminal screen vertically and horizontally just as ConEmu allow. It would be great.

Use Case: Some times in Platform IO IOT development the different tools run on different python version, we have to execute some commands (build. deploy) from same path but as the python version is different, we have to open two different terminals. It would be enhancing the productivity of developer if he's able to see the results on same window split to multiple terminals.

# Proposed technical implementation details (optional)

**Comment by BartXZX** [comment]
Is #1000 what you are looking for?

**Comment by JushBJJ** [comment]
Basically a duplicate of #1000

**Comment by jagpreetstamber** [comment]
Yes, it is duplicate, please close this request
