### ISSUE TITLE
Reload (restart) the current tab

### ISSUE THREAD

**Issue by cronhan** [microsoft/terminal#15872]
# Description of the new feature/enhancement
Some of my workflows necessitate essentially closing and re-opening the current tab, and it is not the default profile. While it is _technically_ possible using "duplicate" followed by closing the current tab, I feel a nicer flow in this case would be a "reload current tab" action. I could not find such an action in the current list using the command palette, hence this issue.

# Proposed technical implementation details (optional)
An action (command?) and right-click option on a tab that says "Reload tab" or similar (I don't think "Restart tab" makes sense). Selecting this option starts a new shell/whatever (e.g. pwsh) in the same tab, as if one had duplicated and closed the current one.

**Comment by lhecker** [comment]
Do you mean #3726? It has shipped in 1.18.

**Comment by cronhan** [comment]
Indeed, sorry for creating the duplicate, I think I missed it because the default search searches only open issues. I'm on the store version so will be looking out for the update!

**Comment by hi2u** [comment]
For anyone wanting to bind a key to the new `restartConnection` feature, this worked for me in my `settings.json`

```json
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": [
        {
            "command": "restartConnection",
            "keys": "alt+shift+r"
        }
    ]
}
```

The JSON schema seems to think it's invalid, but it works for me.

Looks like `"$schema": "https://aka.ms/terminal-profiles-schema"` needs to be updated to lint for it.
