### ISSUE TITLE
Addition of a buttons/button bar

### ISSUE THREAD

**Issue by tasosptl** [microsoft/terminal#15874]
# Description of the new feature/enhancement
This feature/improvement will allow the user the ability to create custom clickable button where he can specify the action that will be performed once clicked. This could be a group of commands that he/she uses for day to day work.

Programmable buttons is one of the reasons that me as a network engineer I choose the competitor (can't name) over MS Terminal. This will reduce the repetitive copy-paste of common troubleshooting commands from notepad/OneNote to the terminal.

# Proposed technical implementation details (optional)
The idea is to allow the user to add an additional bar (either on top or at the bottom of the terminal screen) similar to the picture where he or she will be able to add the buttons:

<img width="247" alt="image" src="https://github.com/microsoft/terminal/assets/53862819/b03101be-6773-492e-87ac-ef6987f93cbf">

The buttons should have a label (what is seen on the screen next to each button), a string that will be send and additional actionable commands such as "send carriage return" or "send a newline".

**Comment by zadjii-msft** [comment]
Amazingly enough, we had almost the exact same request earlier this week: #15851. To crib from that issue:

> A lot of that already seems possible today with the [`sendInput`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#send-input) action. That'll let you save an action to your settings that will send a string of characters to the Terminal. Those'll show up in the Command Palette today. 
> 
> To build on that:
> 
> * #3759
>   - "I want to customize the new tab dropdown with my own actions too"
> * #2934
>   - also, #3459 
>   - "I want a toolbar where I can put arbitrary buttons that do things"
>   - This would follow #3759
> * #1595
>   - Vaguely similar. Another way of using `sendInput` actions a little easier.
>   - "I want an easy UI for activating saved scripts"
>   - We'll almost certainly be doing more with "tasks" in the future, ala #12857
>

So, I'm guessing that there's a dupe somewhere in the nexus of all those - sound about right/?

**Comment by zadjii-msft** [comment]
> Is the sendInput a clickable item

Well, sorta? It'll show up in the Command Palette, and in 1.19 it'll be in the Suggestions UI (for `tasks` - added in #15664).

> will the user be able to create more than one different sendInput items

Yep - it's an action just like any other Terminal action, so you can create as many as you want and bind to whatever you feel like. 

/dup #3759
/dup #2934
