### ISSUE TITLE
Unable to mute sound effect for failed tab completion in CMD

### ISSUE THREAD

**Issue by rivy** [microsoft/terminal#15870]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3324

### Steps to reproduce

1 - Create a tab for a CMD shell.
2 - type `cd NonExistent<TAB>`, triggers the "asterisk" sound, unaffected by the pertinent settings in the Volume Mixer.

In the volume mixer, the sound is shown as a "System Sound", not as part of the WindowsTerminal.

This is unaffected by any/all "Bell notification" setting(s).

Same behavior is seen in the most recent preview version of WindowsTerminal.

### Expected Behavior

I expected "Bell notification" settings to be honored for the sound.

### Actual Behavior

"Asterisk" system sound is triggered.

**Comment by zadjii-msft** [comment]
What's your `bellStyle` and `bellSound` set to? IIRC the default `bellSStyle` is "audible", and that defaults to the system notification sound if no other sound was set manually.

**Comment by DHowett** [comment]
In addition, there are some shells that call the operating system functions `PlaySound` or `Beep` _directly_. We do not have an opportunity to stop them from doing so, because they are circumventing the terminal entirely.

**Comment by rivy** [comment]
@zadjii-msft @DHowett , thanks for the replies.

@zadjii-msft , it's the same for any combination of settings.

I guess the CMD is a shell that directly calls the `PlaySound` or `Beep` and, so, can't be blocked/modified?

**Comment by DHowett** [comment]
Unfortunately, it looks like it is! It calls `MessageBeep` (I had apparently gotten the name wrong).

We're going to triage this as an issue in CMD -- however, know that we are pretty hesitant to make changes there since CMD is "critical infrastructure".

**Comment by zadjii-msft** [comment]
@DHowett I'm tempted to just close this out - you know our policy on CMD.exe changes. Literally NEVER not burned by it. 

We also don't have a "Man if one day we could make cmd.exe changes" megathread (at least, not a public one I could find). I can make one and link this to it, but I don't want people to think this is something we can fix anytime soon.

**Comment by j4james** [comment]
My first thought was that this wouldn't be a risky change, but then I remembered https://xkcd.com/1172/. There's bound to be someone somewhere that has patched the user32 dll to hook the `MessageBeep` call so they can trigger some critical process when the cmd shell beeps. They won't be happy when that breaks.

**Comment by DHowett** [comment]
It also changes the visible (on `CONOUT$`) output of cmd (boo). You reminded me of [@]vefatica, who was setting user-wide environment variables by injecting into explorer and manipulating its environment rather than using the Environment registry key. . . so, yeah! :grin:

**Comment by rivy** [comment]
@zadjii-msft , @DHowett , @j4james , Thanks for your look at the issue and the entertaining conversation. 😄

I understand that this might be an overly risky change, especially since I can work around it by using the mute button or `clink`.

I have no issue if you want to close it. Maybe add a note somewhere about limitations of the bell settings.

Thanks!

**Comment by DHowett** [comment]
Thanks for the discussion -- and for being OK with us closing it. I'd love to fix it, but honestly I've been burned by CMD changes too many times. :laugh:
