### ISSUE TITLE
Windows 11 context menu

### ISSUE THREAD

**Issue by modz2014** [microsoft/terminal#15873]
### Steps to reproduce

Duplicate

### Actual Behavior

wanting to stop of it show up under show more options and only show in windows 11 default context menu only

**Comment by lhecker** [comment]
I don't think we can do anything about that. We just tell Explorer that we're a context menu entry and it does what it does (which is to add us to both the new and old context menu).

**Comment by modz2014** [comment]
is there a way to disable the old one need an example
