### ISSUE TITLE
Application terminates on wheel-clicking a tab

### ISSUE THREAD

**Issue by smdonoghue** [microsoft/terminal#1588]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Wheel-click a tab within Windows Terminal.

# Expected behavior

Close the tab or whatever the intending behaviour is by design.

# Actual behavior

Application becomes unresponsive for a matter of seconds and forcibly terminates.

**Comment by carlos-zamora** [comment]
Duplicate of #1380
