### ISSUE TITLE
[1.19 selfhost] URL autodetection is broken

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15891]
Version `1.19.2371.0`, which I believe has #15858 in it.

Don't have a narrow repro yet - writing down before I forget. 

I wrote a few screenfuls of text. Then did a git push. It gave me the handy:

```
Enumerating objects: 68, done.
Counting objects: 100% (68/68), done.
Delta compression using up to 8 threads
Compressing objects: 100% (41/41), done.
Writing objects: 100% (41/41), 4.62 KiB | 2.31 MiB/s, done.
Total 41 (delta 38), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (38/38), completed with 27 local objects.
remote:
remote: Create a pull request for 'dev/migrie/f/--inherit-env-vars' on GitHub by visiting:
remote:      https://github.com/microsoft/terminal/pull/new/dev/migrie/f/--inherit-env-vars
remote:
To https://github.com/microsoft/terminal
 * [new branch]          dev/migrie/f/--inherit-env-vars -> dev/migrie/f/--inherit-env-vars
Branch 'dev/migrie/f/--inherit-env-vars' set up to track remote branch 'dev/migrie/f/--inherit-env-vars' from 'origin'.
```

But alas, a <kbd>ctrl+shift+m</kbd>,  <kbd>shift+tab</kbd> did not highlight the URL. Instead, it higlighted some text that was way up near the start of the buffer (but not like, as the same viewport-relative position or anything like that). The selected text was very much _not_ a URL:

![image](https://github.com/microsoft/terminal/assets/18356694/4ba2c9d4-e7ec-43d8-b324-d7aa43f04949)

**Comment by lhecker** [comment]
I have a fix on the way. 🙂
