### ISSUE TITLE
Windows PowerShell (Admin) on some computers with Windows 10 only Windows PowerShell work

### ISSUE THREAD

**Issue by maisondasilva** [microsoft/terminal#15890]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3393

### Steps to reproduce

https://github.com/microsoft/terminal/assets/11423362/2be9454d-0b46-4baf-a4de-7a168b8536d4

### Expected Behavior

Windows PowerShell (Admin) open Terminal Admin

### Actual Behavior

Windows PowerShell (Admin) open poweshell admin

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #10276 for more discussion.

/dup #10276

**Comment by maisondasilva** [comment]
> 

Thanks for the warning, I'd looked for it but couldn't find it!

**Comment by zadjii-msft** [comment]
No worries - that's a wacky one that you'd have to _know_ existed to be able to find it. Heck I knew it existed and still took me 10 minutes to find it 😛

**Comment by maisondasilva** [comment]
> No worries - that's a wacky one that you'd have to _know_ existed to be able to find it. Heck I knew it existed and still took me 10 minutes to find it 😛

Are there any alternative solutions? The strange thing is that I have other computers just like it and it works as expected, same version all the same!

**Comment by zadjii-msft** [comment]
> The strange thing is that I have other computers just like it and it works as expected

excuse me what 👀 

The "default terminal" functionality definitely has never worked for elevated commandline applications. On Windows 11 the Win+X menu has "Terminal (Admin)" in it, which doesn't use the default terminal feature. Maybe that's what you've seen?

**Comment by maisondasilva** [comment]
> > The strange thing is that I have other computers just like it and it works as expected
> 
> excuse me what 👀
> 
> The "default terminal" functionality definitely has never worked for elevated commandline applications. On Windows 11 the Win+X menu has "Terminal (Admin)" in it, which doesn't use the default terminal feature. Maybe that's what you've seen?

See video

Win10

https://github.com/microsoft/terminal/assets/11423362/00484b43-8b5a-4826-b6ac-17ed678bd86b

**Comment by zadjii-msft** [comment]
wat 

Are you by any chance running with UAC entirely disabled?

`reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLua` should be able to tell us - `0` means UAC is disabled, anything else and it should be on.

**Comment by maisondasilva** [comment]
That's right, it seems that whoever maintains the system used on this server has deactivated it, and activating it won't work again!
