### ISSUE TITLE
Atlas engine does not render stylistic sets

### ISSUE THREAD

**Issue by scfrazer** [microsoft/terminal#15896]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.0

### Other Software

None

### Steps to reproduce

- Set the font to "Cascadia Mono"
- Open the JSON settings and add in the appropriate place `features: { "ss19": 1 }` (see Cascadia Code repo)
- This should choose the slashed zero variant of Cascadia Code
- In the Rendering settings, turn off use Atlas engine
- Slashed 0 is shown in terminal text
- Now turn on Atlas engine
- Slashed 0 is not shown

### Expected Behavior

Atlas engine should render stylistic sets

### Actual Behavior

Atlas engine does not render stylistic sets

**Comment by scfrazer** [comment]
Oh, you may need to restart terminal between switching Atlas engine settings

**Comment by DHowett** [comment]
@lhecker I've taken off triage since you touched this and I reproduced it. :)

**Comment by DHowett** [comment]
Thanks for filing @scfrazer!
