### ISSUE TITLE
New window is opened in background

### ISSUE THREAD

**Issue by oldium** [microsoft/terminal#15895]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Open File Explorer, place it on the screen so that new Windows Terminal window must open over it.
2. On address bar of File Explorer, write `wt` and press Enter.
3. New Windows Terminal window opens in front of other windows and gets focus.
4. Switch back to File Explorer's address bar, write `wt` and press Enter.
5. New Windows Terminal window opens in front of other windows and gets focus.
6. Click on the first Windows Terminal window's title bar.
7. Switch back to File Explorer's address bar, write `wt` and press Enter.
8. Observe that the Windows Terminal window is opened in background (not over File Explorer, but below it), has blinking cursor like it has focus, but it does not have focus.

### Expected Behavior

The new window is opened in foreground and gets focus.

### Actual Behavior

The new window is not a foreground window and does not have focus.

The new window is opened in foreground as long as you do _not_ click on any previously opened window. When you do, next Windows Terminal window (and any further) opens in background.

**Comment by lhecker** [comment]
Hey! Thanks for the report. This appears to be /duplicate of #15763. 🙂

**Comment by lhecker** [comment]
Oh you're right. (Although I do think they're related.)
But there are multiple other reports of this issue like for instance #13130. I think something's wrong with bringing packaged applications (AppX/MSIX) to the foreground in general. Internally Windows is littered with special handlings for packaged applications throughout the code base so it at least wouldn't be entirely surprising to me if it deviated from the behavior of regular applications.

**Comment by lhecker** [comment]
I didn't notice that this issue was closed again. I'll reopen it. I don't really think it's the exact same issue as the other one...

**Comment by zadjii-msft** [comment]
This is the "`wt.exe` should probably `AllowSetForeground` / `CoAllowSetForeground` on the monarch" thing.

**Comment by KerimG** [comment]
I ahve been having this issue for a couple weeks too now. I'm opening the Windows Terminal by pressing the Win button to open the start menu and type "Terminal". I think the problem occurs if the Windows Terminal app is pinned to the task bar.

**Comment by Cyanide0210** [comment]
Its always appearing on the background for me, I do not like that at all

**Comment by MaverickMartyn** [comment]
I too have this issue.
In my case I use PowerToys Keyboard Manager to launch C:\Users\USER\AppData\Local\Microsoft\WindowsApps\wt.exe
I do not have Terminal pinned to the taskbar, and it happens to the first create Window, not just any subsequent ones.
Here's my launch settings, in case that matters:
![image](https://github.com/microsoft/terminal/assets/2946618/99dc5ee4-1cfc-4407-9c9d-7a37ad908040)

**Comment by jacko-png** [comment]
I used to have this issue until I updated to 1.19.10821.0 via Winget. From memory, I used Microsoft Store to get WT at first. I open WT via the context menu (right click → t) and a shortcut on my desktop mapped to a keybind. I'm on Windows 10 22H2 build 19045.4170. I feel like this issue is either contextual (the fix seems to persist through restarts though) or resolved.

**Comment by McSneaky** [comment]
Have version 1.19.10821.0 installed thro Microsoft Store and it has been happening for months. Still happening

Doesn't matter how I open terminal, always goes to background

**Comment by zadjii-msft** [comment]
fwiw I can't repro this on `10.0.26282.5000` & ` 1.23.2391.0`. This may have been fixed by #17368 in 1.22 Preview - can anyone confirm/?

**Comment by oldium** [comment]
Yeah! I can confirm it works for me with version 1.21.1772.0 on Win 11 22631.4112.

**Comment by oldium** [comment]
> fwiw I can't repro this on `10.0.26282.5000` & ` 1.23.2391.0`. This may have been fixed by #17368 in 1.22 Preview - can anyone confirm/?

I am on version which you have not mentioned, which is really strange, but with 1.21.1772.0 it works for me. I tried exactly the repro steps and also my usual work flow, it works. It might be working for longer time, I just have not noticed it.

**Comment by oldium** [comment]
Works for me, closing.
