### ISSUE TITLE
Window is restored after each computer unlocking

### ISSUE THREAD

**Issue by ygoe** [microsoft/terminal#15907]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Enable the setting "New instance behaviour": "Add to most recently opened window on this desktop"
2. Open a terminal window
3. Minimise it
4. Lock the computer
5. Unlock the computer

### Expected Behavior

The minimised window doesn't move and stays where it is, minimised.

### Actual Behavior

The Terminal window is now restored and visible on my screen after unlocking. Every time.

I suspect the mentioned setting has something to do with it. I could only observe this after setting it. I did this to reduce the number of windows for multiple long-running background console applications. Other than that, it's a normal and fresh Windows 11 setup with all hardware drivers, including AMD.

I also suspected a scheduled task to be run as console application after locking or unlocking the computer. That might explain why the Terminal window gets restored. After disabling all of them the behaviour remains though. So even if it's caused by this or not, the behaviour is still undesired. The Terminal must be able to remember and keep its window state unless the user interacts with it.

**Comment by DHowett** [comment]
I have seen the AMD driver software attempting to spawn a console window on login or wake from sleep. I do not know whether it uses a scheduled task.

Unfortunately, this is not something we can ultimately control: if we provide a setting that suppresses all console application foreground requests, we will _invariably_ encounter users who turn it on and are then deeply confused or concerned that they don't get console windows any longer.

There is no way for us to determine that a given console application is _not,_ in fact, trying to be in the foreground.

Oh wait, there is. It's just that a bunch of driver developers choose not to use it! 😆
