### ISSUE TITLE
The size of the viewport margins (gutters) isn't uniform after a resize

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#15903]
### Windows Terminal version

1.19.2412.0

### Steps to reproduce:

Resize the window.

### Actual Behavior

It's fairly self-explanatory:

![image](https://github.com/microsoft/terminal/assets/2256941/e92e46a5-a490-468e-b02d-e45cca887908)

**Comment by zadjii-msft** [comment]
I don't think it ever has been...? Unless you have the snap to grid setting on

**Comment by lhecker** [comment]
But snap-to-grid is on default right?

re: "I don't think it ever has been...?"
When you launch Windows Terminal the margins are all uniform. Here's a 50x15 window with Ctrl+Shift+A:
![image](https://github.com/microsoft/terminal/assets/2256941/141f7b81-3fde-4fff-8b94-323dadb0c56b)

After resizing the window to 51x15:
![image](https://github.com/microsoft/terminal/assets/2256941/69a06f9d-f245-48bc-80fc-2718c293bb1d)

I don't think that's intentional. 😅

**Comment by zadjii** [comment]
#4175 maybe

**Comment by lhecker** [comment]
Ah, damn I knew I saw an issue for that, but couldn't find it when searching for "gutters" or "margins".
BTW on 96 DPI displays the margins are also not uniform, just in a different way... The right one is off by 1-2px after launch and only correct after a resize.
