### ISSUE TITLE
Pane movement breaks showCloseButton=never

### ISSUE THREAD

**Issue by regnaio** [microsoft/terminal#15902]
### Windows Terminal version

1.17.11461.0

### Windows build number

Version 10.0.19045.3324

### Steps to reproduce

Add the following to `settings.json` (in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`):
```json
"theme": "foo",
"themes": [
  {
    "name": "foo",
    "tab": {
      "showCloseButton": "never"
    }
  }
]
```

Run in Command Prompt:

```shell
wt -M -p "Ubuntu-20.04" ; ^
	split-pane -p "Ubuntu-20.04" ;
```

Observe that the first tab has an "X" on the right that you can click to close the tab. But, `tab.showCloseButton`: `never` should have hidden this "X". The `split-pane` line is causing this bug. If you remove it, i.e.

```shell
wt -M -p "Ubuntu-20.04" ;
```

then the tab no longer has the "X", as expected

For related discussion:
- https://github.com/microsoft/terminal/issues/3335
- https://github.com/microsoft/terminal/pull/13348

### Expected Behavior

The "X" icon should not be present on a Windows Terminal tab if `tab.showCloseButton`: `never`

### Actual Behavior

The "X" icon is present on a tab if using `split-pane` in `wt`

---

_Edit (lhecker)_: **Any movement between two panes makes the buttons reappear**.

**Comment by DHowett** [comment]
Thanks for filing! We found a more general issue with `showCloseButton` thanks to you :smile:

**Comment by zadjii-msft** [comment]
Oh well that'll do it:

* `TerminalPage::_updateAllTabCloseButtons` is where we apply `TabViewItem().IsClosable` based off the theme
* Presumably, `TerminalTab::_RecalculateAndApplyReadOnly` fires later, which then updates the tab's own item's `IsClosable` based on read-only state only.
