### ISSUE TITLE
Invoking wt starts two windows

### ISSUE THREAD

**Issue by kchiem** [microsoft/terminal#15910]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.3393

### Steps to reproduce

> wt

### Expected Behavior

Open a window.

### Actual Behavior

Opens two windows.

**Comment by DHowett** [comment]
Can you share your settings file?

**Comment by kchiem** [comment]
> Can you share your settings file?

[settings.zip](https://github.com/microsoft/terminal/files/12480876/settings.zip)

**Comment by kchiem** [comment]
Just rebooted and the problem is gone..
