### ISSUE TITLE
Is it possible to have elevated consoles follow default terminal setting?

### ISSUE THREAD

**Issue by zamadatix** [microsoft/terminal#15922]
This is more a question as I assume the problem comes down to my ignorance about voodoo done for launching elevated sessions.... but, given there is nowadays a way to set the default terminal application, why must elevated console sessions (e.g. running a .bat file as admin or launching diskpart from a non-elevated Terminal session) still default to the legacy Windows Console Host instead of follow the preference like non-elevated sessions do? I thought the reasoning may have to do with the setting being per user but even running Windows Terminal as admin the preference still shows as Windows Terminal.

**Comment by zadjii-msft** [comment]
Basically, we've been tracking this in #10276. The way the default terminal setting works is based off Packaged COM. Unfortunately, Packaged COM still doesn't work for our needs in an elevated context. 

Till then, follow /dup #10276
