### ISSUE TITLE
Windows Terminal freezes when running npm

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/terminal#15926]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.2134

### Steps to reproduce

Run Windows terminal.
Go to a project that uses npm.
Run npm ci.
Windows terminal freezes.

### Expected Behavior

To finish ok.

### Actual Behavior

Windows terminal freezes when it reaches a certain dependency.

**Comment by zadjii-msft** [comment]
Can you share a specific project that repros this/? This sounds pretty bad, so I'd be surprised that we'd never heard about it before if it was widespread.

When the Terminal freezes, _how_ does it freeze? Does the output stop, but the rest of the Terminal UI remain responsive? (i.e. can you open other tabs?) Or does the app become fully unresponsive, like when the OS fades the window out and forces you to force-kill it? If it's that second one, a [grabbing a dump](https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#capture-with-task-manager) while it's frozen might be enlightening.

Does this repro on [Terminal Preview](https://aka.ms/terminal-preview)? I think there were some changes in 1.18 that might help. Can't be sure.

**Comment by ChaseKnowlden** [comment]
It happens on the vscode-python project.

**Comment by ChaseKnowlden** [comment]
Duplicate of https://github.com/npm/cli/issues/4028.
