### ISSUE TITLE
System performance extremely poor when Windows Terminal is open during Teams screen sharing session

### ISSUE THREAD

**Issue by msherian** [microsoft/terminal#15928]
### Other Software

IdentifyingNumber : {A7AB73A3-CB10-4AA5-9D38-6AEFFBDE4C91}
Name              : Microsoft Teams Meeting Add-in for Microsoft Office
Vendor            : Microsoft
Version           : 1.23.22602
Caption           : Microsoft Teams Meeting Add-in for Microsoft Office

IdentifyingNumber : {731F6BAA-A986-45A4-8936-7C3AAAAA760B}
Name              : Teams Machine-Wide Installer
Vendor            : Microsoft Corporation
Version           : 1.2.0.10168
Caption           : Teams Machine-Wide Installer

IdentifyingNumber : {9F191CDC-6122-4376-A0CA-B98501C749AE}
Name              : VMware Horizon Media Redirection for Microsoft Teams
Vendor            : VMware, Inc.
Version           : 8.10.0
Caption           : VMware Horizon Media Redirection for Microsoft Teams

admsdub\msherian:msherian> winget show microsoft.windowsterminal
Found Windows Terminal [Microsoft.WindowsTerminal]
Version: 1.16.10261.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com
Publisher Support Url: https://github.com/microsoft/terminal/issues
Author: Microsoft
Moniker: terminal
Description: The new Windows Terminal, a tabbed command line experience for Windows.
Homepage: https://docs.microsoft.com/windows/terminal
License: MIT
License Url: https://github.com/microsoft/terminal/blob/master/LICENSE
Privacy Url: https://privacy.microsoft.com
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/terminal/blob/master/LICENSE
Release Notes:
  This release of Windows Terminal addresses a crash in self-elevation.

  Huge thanks to @jboelter for fixing it in 1.17 (#14637).
Release Notes Url: https://github.com/microsoft/terminal/releases/tag/v1.16.10261.0
Tags:
  cli
  cmd
  command-line
  command-prompt
  console
  developer-tools
  powershell
  ps
  shell
  terminal
  utilities
  wsl
Installer:
  Installer Type: msix
  Installer Url: https://github.com/microsoft/terminal/releases/download/v1.16.10261.0/Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle
  Installer SHA256: ba6fc6854e713094b4009cf2021e8b4887cff737ab4b9c4f9390462dd2708298
  Release Date: 2023-01-27

### Steps to reproduce

1 ) Open an instance of Windows Terminal
2 ) Enable transparency on the display profile
3 ) Initiate a Teams call 
4 ) Initiate whole screen sharing on an external monitor (laptops)

### Expected Behavior

The ability to interact  with applications and have the mouse respond normally

### Actual Behavior

Mouse tracking becomes jittery and sluggish, and applications take tens of seconds to respond to basic input; Windows Terminal, which is on a non-shared display, goes into a not responding state.

**Comment by msherian** [comment]
I've two adapters, an Intel 630 and an Nvidia Geforce GTX 1050.

**Comment by lhecker** [comment]
What about the variable refresh rate display? Do you use one (either G-Sync or FreeSync)?

**Comment by msherian** [comment]
No the displays I am using are pretty basic:  https://www.philips.ie/c-p/278B1_00/monitor-lcd-monitor-with-powersensor and the on-board XPS 9570 LCD panel. I don't even have the G-Sync option in my nVidia control panel

**Comment by lhecker** [comment]
Unfortunately I've never seen this issue happen on my end (and as far as I'm aware no one else on the team had this happen to them). Could you try these two things?

* `winget` shows the version that they provide, not what is actually installed. To get and check the version please follow these steps:
  * Open the About dialog: ![image](https://github.com/microsoft/terminal/assets/2256941/20561883-6d53-4a04-a0dc-b345ea8dd5af)
  * Check that you use version `1.17.12191.0`.¹
    If it's older than that, please open the Microsoft Store app, navigate to your Library in the bottom left corner and update your apps. It should then install `1.17.12191.0`.
* Enable AtlasEngine in the Rendering settings: 
![image](https://github.com/microsoft/terminal/assets/2256941/c082af6f-4208-4f84-a4ad-30dbc155645f)

---

¹ The issue template asks you to do this by the way 😅: 
![image](https://github.com/microsoft/terminal/assets/2256941/1edf8d56-1976-4a56-93f7-4bbe2ae41012)
