### ISSUE TITLE
Bug Report-Cant launch

### ISSUE THREAD

**Issue by perpiris** [microsoft/terminal#1593]
I installed it via the windows store and at first i could launch and use it just fine.I worked on an angular app for a couple of hours and i closed it.After a while i tried launching it again but nothing.Even after restarts and uninstalling and re-installing again still nothing happens

Version 1903
Build 18362.175

**Comment by JushBJJ** [comment]
have you modified anything? (like your profiles?)

**Comment by Shorotshishir** [comment]
please be specific about "not launching". Is it not opening or crashing?  Try going to its settings directory (i.e. where `package.json` resides) and if exists delete the file. and try re-launching the app.

**Comment by perpiris** [comment]
> have you modified anything? (like your profiles?)

yes i deleted the power shell one

**Comment by JushBJJ** [comment]
So what you do is to copy and paste the guid of what ever profile you want into the the default profile. (Like, replace it)

**Comment by JushBJJ** [comment]
^ In profiles.json

**Comment by perpiris** [comment]
> ^ In profiles.json

where is that located?
In C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe i can't find anything

**Comment by Shorotshishir** [comment]
@perpiris , if you open the Terminal app, the  `profile.json` file will be created instantly. keeping the windows terminal open go to the directory ( `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe` ) and delete the file. Close the App and re-launch it. This should create a brand new `profile .json` with new `GUID's`, in your case probably that was missing as terminal makes PowerShell default and u deleted the PowerShell profile which had its `GUID`.  Without the correct `GUID` terminal won't find the correct profile to load.

**Comment by perpiris** [comment]
> @perpiris , if you open the Terminal app, the `profile.json` file will be created instantly. keeping the windows terminal open go to the directory ( `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe` ) and delete the file. Close the App and re-launch it. This should create a brand new `profile .json` with new `GUID's`, in your case probably that was missing as terminal makes PowerShell default and u deleted the PowerShell profile which had its `GUID`. Without the correct `GUID` terminal won't find the correct profile to load.

i can't open the app that's the problem

**Comment by DHowett-MSFT** [comment]
This is probably #1364.
