### ISSUE TITLE
Certain terminal characters not rendering correctly

### ISSUE THREAD

**Issue by ajkessel** [microsoft/terminal#15934]
### Windows Terminal version

1.18.230526002-preview

### Windows build number

19045.2846

### Other Software

mutt and neomutt use "alternate-character-set" characters to display thread and attachment trees. These characters, which are supposed to be lines and arrows, don't render correctly in Windows Terminal, as shown in the attached screenshot. I suspect there are other apps (maybe ncurses?) that will exhibit similar behavior. Is there a setting that will fix this, a font change, or is it an underlying bug?
<img width="743" alt="2023-09-06_135959" src="https://github.com/microsoft/terminal/assets/3332524/caeb338f-6d67-40f2-94f4-ef58f67b6510">

### Steps to reproduce

Open Windows Terminal with cygwin
Run mutt or neomutt

### Expected Behavior

Visible lines/arrows

### Actual Behavior

Aberrant characters

**Comment by zadjii-msft** [comment]
How do you have your cygwin profile configured/?

Can you share the output of `locale`?

**Comment by ajkessel** [comment]
```
LANG=
LC_CTYPE="en_US"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```
I just noticed if I use the powershell profile rather than the cygwin profile, the arrows render correctly. Will dig a bit and see if I can figure out what setting that is and report back, unless you have an idea/suggestion.

**Comment by ajkessel** [comment]
Oddly enough, if I ssh from a powershell profile tab to a Linux Box and run mutt, characters render correctly. If I run cygwin bash from the powershell profile tab first, characters render incorrectly.

**Comment by ajkessel** [comment]
```
export TERM=linux
```
Fixes the issue. Is this a Windows Terminal problem, cygwin problem, mutt problem, or someting else?

**Comment by zadjii-msft** [comment]
This sounds a lot like https://github.com/microsoft/terminal/issues/14982#issuecomment-1615291201

Does the `commandline` for your cygwin profile include `-l -i`/?

**Comment by ajkessel** [comment]
> Does the commandline for your cygwin profile include -l -i/?

It didn't before, but I just tried adding it and it did not alter the behavior.

**Comment by ajkessel** [comment]
I took a look at that issue. term=linux and term=xterm both fix the rendering issue.

**Comment by elsaco** [comment]
@ajkessel the issue seems to be caused by the settings in `.minttyrc`. Look for the `Locale`, `Charset` and `Term` settings. Here's sample config I'm using:

```
$ cat .minttyrc
ThemeFile=nord
FontHeight=11
Locale=en_US
Charset=UTF-8
Columns=132
Rows=43
Scrollbar=none
Term=xterm-256color
```

Notice in your 2nd post how `LANG=` is not defined. I bet the `Term` is not defined either.

**Comment by ajkessel** [comment]
Yes, the issue was `term`. Setting it to something other than `cygwin` fixes the character rendering.

**Comment by DHowett** [comment]
Ah, thanks for following up!

Yes, `TERM=cygwin` engages a translation layer inside Cygwin that is only supposed to be used for old versions of Windows. Those older versions didn't support a lot of modern terminal features in the console, so Cygwin's translation layer is very limited.
