### ISSUE TITLE
Use Control W to close a terminal

### ISSUE THREAD

**Issue by vyoln** [microsoft/terminal#15947]
# Description of the new feature/enhancement
Using [Ctrl + W] to close a terminal tab. It'd be really useful as I'm used to it in browsers, and would like it to be in the terminal as well.

# Proposed technical implementation details (optional)

**Comment by zadjii** [comment]
You can always rebind the default keybindings. [`closePane`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-tab) is bound to `ctrl+shift+w` by default, but you can change that to Ctrl+w if you'd like

**Comment by Slapbox** [comment]
`ctrl+w` to close a window kills when you're in nano. I strongly advise getting used to `ctrl-shift-w`.
