### ISSUE TITLE
Feature Request: Please allow us to use this as the default terminal

### ISSUE THREAD

**Issue by Wagnerp** [microsoft/terminal#1594]
Can you add a option to set the new terminal as the default over CMD/PowerShell?

**Comment by mikemaccana** [comment]
+1, it'd be great to have this specified as the default terminal (like default web browser or default email client) so it shows up in Win X:

![image](https://user-images.githubusercontent.com/172594/60107251-82e0c780-975e-11e9-8d26-c1828eae9174.png)

**Comment by cneto17** [comment]
You can. Open setting.json with your JSON editor and create the profile of what you want. Then, edit the 5th line with the GUID of the profile you want to be the default.

Sure that this will be addressed after the UI development when they start working on the UI experience.

**Comment by mikemaccana** [comment]
@cneto17 Your comment is how to set the default profile used for Windows Terminal. 

This feature request is how to set the default **terminal** for Windows 10.

**Comment by Wagnerp** [comment]
@cneto17 

I think a single button would be better, like how you can replace task manager with process explorer.

**Comment by SJang1** [comment]
@mikemaccana check out #1421

**Comment by mikemaccana** [comment]
@SJang1 Thanks! #1421 is similar. but not the same:

 - #1421 is about adding any new items to Win+X,
 - This is about making the existing items (powershell, Powershell Admin, or if you prefer, cmd and cmd Admin)  open using Windows Terminal

**Comment by DHowett-MSFT** [comment]
This is actually #492. It'll require some OS changes to add support for _any_ third party terminal to register as a potential option, and some conhost and shell startup infrastructure changes to make that work, so it's pretty far down the backlog.

**Comment by mikemaccana** [comment]
Yep it's the same as #492. Thanks @DHowett-MSFT !
