### ISSUE TITLE
Resizing window lags when history buffer has lots of lines

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/terminal#15964]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.1848

### Steps to reproduce

Settings - Defaults - Advanced - History size - 999999
Open powershell tab
issue `ls -r` or similar to fill the history buffer (not necessarily fill up, just ensure there are plenty of lines)
Click and drag the lower edge of the window to resize it

### Expected Behavior

smooth movement

### Actual Behavior

laggy movement like I have a 486 computer

**Comment by lhecker** [comment]
Good news! I already opened a PR to fix it: #15701
