### ISSUE TITLE
Bug Report at-sign (@) does not work

### ISSUE THREAD

**Issue by fschlag** [microsoft/terminal#1596]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

German Windows installation and keyboard.
```

# Steps to reproduce

Try to type an at-sign by pressing `ALTGR+Q`. Doesn't matter if it's Cmd, Ubuntu or PowerShell

# Expected behavior
`@` sign is printed to console

# Actual behavior
Ubuntu: Clears part of the previous executed commands
Cmd: prints just a `q`
PowerShell: no output

**Comment by JushBJJ** [comment]
Duplicate of #521??

**Comment by fschlag** [comment]
Oh yes, didn't find this while searching for the at-sign issue. But yes, it's a duplicate if #521 I gonna close this one. After looking at #521 I noticed that other `ALTGR` combinations aren't working too, like `\` for `ALTGR+ß`.

Thanks @JushBJJ
