### ISSUE TITLE
code: '-2147483645'

### ISSUE THREAD

**Issue by cdwmhcc** [microsoft/terminal#15967]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Steps to reproduce

This error occurs at startup and reinstallation cannot resolve it.Cannot enter the main interface of code

### Actual Behavior

I synced after logging in using github and this error appeared.

**Comment by cdwmhcc** [comment]
![image](https://github.com/microsoft/terminal/assets/8030134/5cb250eb-d855-45a2-b0e4-063a3a00f992)

**Comment by zadjii-msft** [comment]
This looks like it's a VsCode issue, not a Terminal one. Might I recommend filing an issue over at their repo? This looks like something they've seen before: https://github.com/microsoft/vscode/issues?q=is%3Aissue+-2147483645+
