### ISSUE TITLE
VT/xterm mouse reporting not working at all outside of WSL

### ISSUE THREAD

**Issue by jhmaster2000** [microsoft/terminal#15977]
### Windows Terminal version

1.17.11461.0

### Windows build number

Microsoft Windows [Version 10.0.19045.3448]

### Other Software

PowerShell 7.4.0-preview.5
WSL version: 1.2.5.0

### Steps to reproduce

To reproduce the *expected* behavior inside WSL: `echo -e '\E[?1006h'` + `echo -e '\E[?1003h'`

To reproduce the *faulty* behavior outside WSL: `Write-Output "$([char]27)[?1006h"` + `Write-Output "$([char]27)[?1003h"`

### Extra info
According to https://github.com/microsoft/terminal/issues/545#issuecomment-509623410, #14958, [this article](https://www.zdnet.com/article/microsofts-windows-terminal-now-has-mouse-support-for-windows-subsystem-for-linux/) and lots of other sources everything seems to indicate this is supposed to be supported, even outside of WSL according to the last article.

I've already found references of some comments saying "QuickEdit" mode might interfere with VT mouse capture, but I already turned that off and it still doesn't work. I've also already tried the command: `Set-ItemProperty HKCU:\Console VirtualTerminalLevel -Type DWORD 1` but I'm pretty sure that was already set anyway.

I can also reproduce this outside of WT with pwsh.exe directly, and have looked through the PowerShell repository issues for this too, but found conflicting cases of people being redirected back and forth between that repository and this one for similar issues to mine (because apparently conhost issues are also tracked here?), so I'm not really sure which one this would fit better, feel free to move the issue to PowerShell if I guessed wrong.

### Expected Behavior

Inside WSL, I obtain the following:
```
jhmaster@Ubuntu:~$ echo -e '\E[?1006h'

jhmaster@Ubuntu:~$ echo -e '\E[?1003h'

jhmaster@Ubuntu:~$ 35;66;17m35;65;17m35;64;17m35;64;16m35;63;16m35;62;16m35;61;16m...
```
from moving the mouse around after the two inputs. I expected the same feedback outside of WSL.

### Actual Behavior

Outside of WSL:
```
PS C:\...> Write-Output "$([char]27)[?1006h"

PS C:\...> Write-Output "$([char]27)[?1003h"

PS C:\...>
```
No matter what is done with the mouse, move, drag, click, scroll, etc no feedback is given by the terminal.

**Comment by lhecker** [comment]
You cannot use the existence of visible output in the shell as an indication whether mouse mode is enabled or not.

When mouse mode is enabled, the terminal writes these sequences (`\e[35;66;17m`, etc.) to the shell / terminal application which then reads them via `stdin`. Whether the shell then writes this input to `stdout` is up to the shell. When you say "WSL" for instance, what you actually see is `bash` writing the `stdin` input to `stdout`. Other shells under WSL like zsh or fish don't do that. PowerShell under Windows doesn't do it either.

Do you have an application that runs outside of WSL where mouse mode doesn't work?

**Comment by lhecker** [comment]
> My intent there was to try to do a reproduction as close to the shells themselves as possible to cut out any possible middleman like a runtime

FYI The shell doesn't really sit in the middle between the terminal and the application it spawns. It's not like this:
```mermaid
flowchart TD
    Terminal --> Shell --> Application
```
but rather like this:
```mermaid
flowchart TD
    Terminal --> Shell
    Terminal --> Application
```

The "Shell" doesn't accidentally snatch away input from your "Application" simply because the shell waits for the application to exit before it continues reading from `stdin`.

> Additionally in the JS source I also tried adding an unconditional `console.log('seq:', seq);` before the `if (!seq.startsWith('\x1B[<')) return; // not a mouse event` check, incase it was some encoding issue that caused that check to fail or something of the sort, but negative, truly nothing is being sent from mouse actions.

If you do it like that you won't see any output since `seq` will contain an escape sequence, which aren't visible text (the terminal parses them away). Try this instead:
```js
console.log('seq: ', JSON.stringify(seq));
```

I currently don't have nodejs installed and haven't used it in a while. So if the above doesn't help you resolve the issue and if no one else comes along in the meantime, I might only come around to debug this in a little bit (after finishing up 1.19). 😥

**Comment by lhecker** [comment]
Oh right, I should've asked: Do you have `node` installed inside WSL? Because if you don't then `wsl node` will call the Windows `node.exe` through a compatibility shim (ConPTY) through WSL which goes through the shim again and back into Windows Terminal. If you do that, and if the above `JSON.stringify` didn't help resolve the issue, try installing `node` inside WSL. If _that_ finally resolves the issue it's probably a bug in system ConPTY (which we maintain).

**Comment by jhmaster2000** [comment]
> > My intent there was to try to do a reproduction as close to the shells themselves as possible to cut out any possible middleman like a runtime
> 
> FYI The shell doesn't really sit in the middle between the terminal and the application it spawns. It's not like this:
> 
> ```mermaid
> flowchart TD
>     Terminal --> Shell --> Application
> ```
> but rather like this:
> 
> ```mermaid
> flowchart TD
>     Terminal --> Shell
>     Terminal --> Application
> ```
> The "Shell" doesn't accidentally snatch away input from your "Application" simply because the shell waits for the application to exit before it continues reading from `stdin`.
> 
> > Additionally in the JS source I also tried adding an unconditional `console.log('seq:', seq);` before the `if (!seq.startsWith('\x1B[<')) return; // not a mouse event` check, incase it was some encoding issue that caused that check to fail or something of the sort, but negative, truly nothing is being sent from mouse actions.
> 
> If you do it like that you won't see any output since `seq` will contain an escape sequence, which aren't visible text (the terminal parses them away). Try this instead:
> 
> ```js
> console.log('seq: ', JSON.stringify(seq));
> ```
> 
> I currently don't have nodejs installed and haven't used it in a while. So if the above doesn't help you resolve the issue and if no one else comes along in the meantime, I might only come around to debug this in a little bit (after finishing up 1.19). 😥

Holy bonkers, quick offtopic here but I didn't know GitHub had support for fancy flowcharts like that, that's amazing. Thanks for showing me those (and the info itself of course)

Anyway, you're right about the `seq` value itself not showing with that, I actually originally did it with `console.dir(seq)` which showed the string's inspected value properly, that was just a bit of a poor recreation, my bad. But even with that poor recreation you can still tell whether something is being sent at all or not because the `'seq:'` string before the actual value would print :P (which I also tested it indeed doesn't)

> Oh right, I should've asked: Do you have `node` installed inside WSL? Because if you don't then `wsl node` will call the Windows `node.exe` through a compatibility shim (ConPTY) through WSL which goes through the shim again and back into Windows Terminal. If you do that, and if the above `JSON.stringify` didn't help resolve the issue, try installing `node` inside WSL. If _that_ finally resolves the issue it's probably a bug in system ConPTY (which we maintain).

Well oops again, I thought `wsl <cmd>` would just be a shortcut for `wsl` and then entering the command inside, which is just what I wanted to signal was happening in that snippet, I do have `node` installed inside WSL and get the same working-as-intended output from running `vt.mjs` inside WSL manually instead of `wsl <cmd>`.

**Comment by bcdev-com** [comment]
Isn't this just the console input mode not being set properly?

I wouldn't know how to do this with Node, but I believe adding the moral equivalent of this after the `process.stdin.setRawMode()` should fix things.  WSL and/or bash are likely doing this for you, but PowerShell does not.

```
HANDLE h = GetStdHandle(STD_INPUT_HANDLE);
SetConsoleMode(h, ENABLE_EXTENDED_FLAGS | ENABLE_MOUSE_INPUT | ENABLE_VIRTUAL_TERMINAL_INPUT);
```
Error handling and restoring the mode before you exit omitted for clarity.

**Comment by jhmaster2000** [comment]
That's what these lines are doing already:
```js
process.stdout.write('\x1B[?1006h'); // Enable SGR mouse mode
process.stdout.write('\x1B[?1003h'); // Enable any event mouse mode
```
It's PowerShell that isn't listening to them. Neither WSL/bash have mouse mode enabled by default so it couldn't just be on prior.

**Comment by bcdev-com** [comment]
No.  Those are acting at a very different level of abstraction.  

You still need the those 1006 & 1003 DECSET sequences to ask Terminal to start reporting mouse events, but first you need to tell the ConPTY through which you are talking to Terminal that you want VT style input rather than INPUT_RECORDs via ReadConsoleInput.

Also note that the lack of other flags there are as important as the ones I turned on.  Leaving out ENABLE_LINE_INPUT, ENABLE_ECHO_INPUT and ENABLE_QUICK_EDIT_MODE are important too for most this sort of scenario under Windows.  

(And for historical reasons you need that ENABLE_EXTENDED_FLAGS to make the lack of ENABLE_QUICK_EDIT_MODE mean anything.)

**Comment by jhmaster2000** [comment]
Ah well in this case I suppose it's still a lacking feature and parity issue with other shells that powershell is the one standing out that doesn't do this for you, ideally you'd want that code to work hassle-free on any shell/term. What exactly is SetConsoleMode under the hood though? Is it another but different kind of terminal sequence or is it a syscall? If its the latter thats pretty unusable for simple scripts too to have to FFI with native program linked with the windows console apis just for expected behavior from powershell...

**Comment by bcdev-com** [comment]
I got to thinking about the hackery in nodejs's tty.c and the implications of it.  If you look at the function [get_vt100_fn_key](https://github.com/nodejs/node/blob/main/deps/uv/src/win/tty.c#L626) you'll see that nodejs reading the input on Windows via ReadConsoleInput and then generating it's own VT sequences for a set of inputs it knows about, which notably does not include mouse inputs.  

As @lhecker point out up thread, the shell you are using isn't between you and the terminal when your code is running.  The runtime you are using, nodejs in this case, certainly is.  Hopefully in the future it will learn to either generate mouse input or enable VT input when you put it in raw mode, but right now it does neither.

You can work around it with the approach I mentioned above, and I've gone ahead and made sample code for that. 
Here is SetConsoleInputMode.c:

```c
#define UNICODE
#include<windows.h>
#include<stdio.h>
#define MAX_MESSAGE_SIZE 1024
wchar_t *LastErrorMessage() {
    static wchar_t message[MAX_MESSAGE_SIZE];
    FormatMessage(
        FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
        NULL, GetLastError(), 0, message, MAX_MESSAGE_SIZE, NULL);
    return message;
}
void fail(wchar_t *message, ...) {
    va_list args;
    va_start(args, message);
    vfwprintf_s(stderr, message, args);
    va_end(args);
    exit(1);
}
int wmain(int argc, wchar_t *argv[]) {
    wchar_t *endOfArg, *errorMessage;
    DWORD oldMode, newMode;
    HANDLE h;
    if (argc < 2)
        fail(L"usage: SetConsoleInputMode <hex-input-mode>\nThe current mode will be output as hex for restoring later.");
    else {
        newMode = wcstoul(argv[1], &endOfArg, 16);
        if (endOfArg != argv[1] + wcslen(argv[1]))
            fail(L"New input mode '%ls' did not parse as hex.\n", argv[1]);
        h = GetStdHandle(STD_INPUT_HANDLE);
        if (h == INVALID_HANDLE_VALUE) 
            fail(L"Unexpected error getting standard input: %ls\n", LastErrorMessage());
        if (!GetConsoleMode(h, &oldMode))
            fail(L"Unexpected error getting current console input mode: %ls\n", LastErrorMessage());
        fwprintf(stdout, L"%08lx", oldMode);
        if (!SetConsoleMode(h, newMode)) {
            errorMessage = LastErrorMessage();
            SetConsoleMode(h, oldMode); /* SetConsoleMode failures can leave some modes set so try and restore */
            fail(L"Unable to set console input mode: %ls\n", errorMessage);
        }
    }
    return 0;
}
```

And here is test.mjs that uses the above and displays mouse input:

```js
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const setConsoleInputModeBinary = join(process.cwd(), 'SetConsoleInputMode.exe');
const setConsoleInputMode = (mode) =>
    execFileSync(setConsoleInputModeBinary, [mode], { stdio: ['inherit', 'pipe', 'pipe'] });

process.stdin.on('data', (buf) => {
    const seq = buf.toString('utf8');
    if (seq == 'q') {
        process.stdout.write('\x1B[?1006l');
        process.stdout.write('\x1B[?1003l');
        setConsoleInputMode('0x01e7');
        process.exit(0);
    } else {
        console.log(JSON.stringify(seq));
    }
});

process.stdin.setRawMode(true);
setConsoleInputMode('0x0290');
process.stdout.write('\x1B[?1006h');
process.stdout.write('\x1B[?1003h');
```

**Comment by jhmaster2000** [comment]
Hey sorry for the late response, this was for a bit of a random coding side-quest which I ended up forgetting about for a while...!

I was definitely not expecting such in-depth response! Really appreciate all of the info and example code (which works perfectly!). I understand the semantics going on here all clearly now (the concrete code example really helped tons), and I can see it really has nothing to do with Windows Terminal or PowerShell, but rather Node getting in the way with the wrong console mode, so I'll close this here and maybe take up a new issue on Node's repo assuming there isn't already one for this. Thanks for all the detailed info and assistance 👍
