### ISSUE TITLE
Automatically dismiss "Failed to reload settings" modals when settings.json is valid

### ISSUE THREAD

**Issue by hi2u** [microsoft/terminal#15987]
# Current behavior 

This happens to me pretty much every time I edit my `settings.json` file:

1. I start making a minor edit
2. My editor's auto-save feature automatically saves (for any number of reasons)... or I accidently hit ctrl-s just out of habit
3. For this brief moment, my `settings.json` file is invalid
4. So all my currently running Terminal windows display the [`Failed to reload settings`](https://user-images.githubusercontent.com/10755858/71671836-147a6300-2d9a-11ea-9910-8aeb0845e952.png) modal immediately
5. A few seconds later I've already completed my minor edit, and saved the valid `settings.json` file
6. But I now have to click through like 20 windows, and manually click on all the `OK` buttons to dismiss all the modals, even though my `settings.json` file is already back in a valid state

# Suggested behavior

At point 5 above, assuming `settings.json` is now valid again: automatically dismiss all these modals, as they're no longer relevant, and can be disruptive when you've got lots of windows open.

**Comment by zadjii-msft** [comment]
this is a great idea why have we never done this

**Comment by DHowett** [comment]
Oh jeez, how DID we miss that?

**Comment by codecruisedor** [comment]
Hi @DHowett , @zadjii-msft , this is an interesting one; just a few observations to check my understanding:
--> `TerminalWindow::UpdateSettings` is used to validate the settings and display error or warning dialogs.
--> There are two condition checks for `args.Result()` based on which we fire the dialogs, so can I add a third one to check if `args.Result() == S_OK ` and if true, dismiss the dialog via `DismissDialog()`?
--> Any other way to close the dialog, from what I see `DismissDialog()` is the only way..

Any comments/suggestions?

**Comment by zadjii-msft** [comment]
@codecruisedor Sorry I missed this! Yep, I'd concur that `TerminalWindow::DismissDialog` seems like the right thing to call here. Seems like you've got the right fix in mind ☺️
