### ISSUE TITLE
Cannot install from window store

### ISSUE THREAD

**Issue by slier81** [microsoft/terminal#1598]
I open the microsoft store and search for `windows terminal`  
But when i click `Get`, nothing is happen.  
There is no indication that it is downloading or what so ever..It simply do nothing

**Comment by JushBJJ** [comment]
Check if you have the requirements.
Its in the requirements tab in the windows store.

**Comment by jefersonduwe** [comment]
OS Requirements: Windows 10 version 18362.0 or higher, Xbox One

**Comment by Wagnerp** [comment]
@jefersonduwe 

Xbox One? Never realised that a games console can have a terminal! :)

**Comment by slier81** [comment]
Updating window does fix it..Thx

**Comment by Alexmhack** [comment]
Not able to install from Store, "Get" button doesn't do anything. Windows version is 20H2

**Comment by bater53** [comment]
I am unable to install from the Store as well I get to the store can find WSL2, ubuntu, and Terminal, Click on blue button to install and it comes back with an error have been trying for over a week have left several messages every where including at the store. Is Microsoft going down hill now? Windows 10 Pro version 22H2.

**Comment by DHowett** [comment]
@bater53 This issue was closed four years ago. The last comment was on June 25th, 2021. In addition, you did not include the error message that the Store was giving you.

Please file a new issue with that information included, and we _might_ stand a chance at helping you.
