### ISSUE TITLE
Terminal and ColorTool

### ISSUE THREAD

**Issue by Babscoole** [microsoft/terminal#15995]
### Windows Terminal version

multiple

### Windows build number

multiple

### Steps to reproduce

We have a batch based console app.  Trying to use ColorTool to set a custom scheme for use when our batch runs.  When Windows Console host is set as the default console, ColorTool can read and display the colors we've set in the .ini just fine.  When default console is set to Terminal, it's ignored and not used.

### Expected Behavior

Specified .ini is used for Terminal

### Actual Behavior

Specified .ini is not used for Terminal

**Comment by Babscoole** [comment]
![When default console is set to Console Host](https://github.com/microsoft/terminal/assets/82686995/7adc8169-b356-4a73-9dd2-846160e4799c)
![When default console is set to Terminal](https://github.com/microsoft/terminal/assets/82686995/db1fc6f3-7fda-4035-9b4f-2db57bceaefa)

**Comment by lhecker** [comment]
This is due to #2985.

You need to run `colortool.exe` with either the `--xterm` or `-x` parameter. This works on Windows 10 build 17048 and later for both the old console window and the new Windows Terminal.
