### ISSUE TITLE
Bug Report: closing powershell tab (multiple opened) hangs the application

### ISSUE THREAD

**Issue by miaouPlop** [microsoft/terminal#1600]
# Environment

```none
Windows build number:  Microsoft Windows [version 10.0.18362.30]
Windows Terminal version (if applicable): preview (from the Store)
```

# Steps to reproduce

Launch the application. You have at least one tab. Now, open a new tab (any console type) and then close the first one (either by clicking the "close" button or by using the keyboard shortcut (mine is bind to ctrl+shift+w) or wheel-clicking).

# Expected behavior

The tab should close fine and not block the entire application.
It should be noted that the first tab closes normally if you type "exit" (and chose to "closeonexit").

# Actual behavior

The entire WindowsTerminal application is blocked and we have to close it with the processus manager.

This bug might be related to #1575, #1585, #1588 and #1530.

**Comment by miaouPlop** [comment]
After some more testing it appears more convoluted than that. The crash only happens when trying to close a powershell console so #1530 seems really connected to that bug.

```none
If I try to close any tab when I have three, the application hangs. 
If I try to close the last tab (when I have >= 3 tabs) then, the application hangs. 
If I now close a tab that is neither the first one nor the last one when I have >= 4 tabs, then it somehow "repairs" the index (to a certain extent) and I can close tabs rather randomly.
```

I can also reference this PR #892 that ended up by the fix [microsoft/microsoft-ui-xaml#629](https://github.com/microsoft/microsoft-ui-xaml/pull/629).

**Comment by JacomusP** [comment]
I was just about to open a new issue but I'm glad I found this one. Just wanted to say that I'm also experiencing this issue of closing the powershell tab that is opened by default.

**Comment by DHowett-MSFT** [comment]
Probably #1445.
