### ISSUE TITLE
elevate-shim.exe is  abnormal

### ISSUE THREAD

**Issue by yujiahan2018** [microsoft/terminal#16009]
### Windows Terminal version

terminal-1.17.11461.0

### Steps to reproduce

双击运行 elevate-shim.exe

### Actual Behavior

There is a constant "exit, run", an endless loop that will not terminate itself

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #13928 for more discussion.

/dup #13928

**Comment by zadjii-msft** [comment]
@NanCheng7 What version of the terminal are you running? The issue this was tracking (#13928) was theoretically fixed in 1.18. If you're seeing something new like this, it likely deserves it's own issue
