### ISSUE TITLE
Some file: OSC 8 URLs show up as "Invalid URI" because punycode/idn conversion blows up (?)

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#16017]
### Steps to reproduce

```
"`e]8;;file:D:\this\is\a\very\long\path\with\a\number\of\subdirectories\in\it\and\that\is\OKAY`e\Test URL`e]8;;`e\"
```

### Actual Behavior

Hover it! It shows up as an "invalid URI"!

**Comment by 237dmitry** [comment]
> Hover it! It shows up as an "invalid URI"!

Perhabs `file://` ?

In my environment I could not reproduce.

![Screenshot 2023-09-22 110555](https://github.com/microsoft/terminal/assets/78153320/4f3f2b53-c634-4190-ab1b-d7db371eda92)

**Comment by lhecker** [comment]
@237dmitry The issue only reproduced on a recent version off of main.

This happens because we use `IdnToAscii` incorrectly. It's designed for domain names, not for entire URLs, and so it fails to work for inputs >63 characters.
