### ISSUE TITLE
Too many consoles in use, max consoles is 32

### ISSUE THREAD

**Issue by leet0rz** [microsoft/terminal#16015]
### Windows Terminal version

1.17.11461.0

### Windows build number

Version	10.0.19044 Build 19044

### Other Software

Newest version of git-bash

### Steps to reproduce

Git-bash in new windows terminal, after some hours or day of use it will say the following: 

`      0 [main] bash 6802 C:\Program Files\Git\bin\..\usr\bin\bash.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    230 [main] bash 6802 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump

[process exited with code 256 (0x00000100)]
You can now close this terminal with Ctrl+D, or press Enter to restart.`

### Expected Behavior

For windows terminal to close the git-bash instances properly.

### Actual Behavior

It does not close git-bash properly after user or terminal closes down a git-bash tab and it keeps stacking up until it reaches 32.

**Comment by DHowett** [comment]
Do you have a lot of Cygwin processes that are still running, but without being attached to a console host?

**Comment by leet0rz** [comment]
> Do you have a lot of Cygwin processes that are still running, but without being attached to a console host?

No. Git-bash is only being used through the windows terminal and there is nothing else.

**Comment by DHowett** [comment]
I'm a bit concerned, then! If there are no processes running, we have shut them down or terminated their console connection. They are expected to handle their own resource cleanup. If the Cygwin runtime is not garbage-collecting things from their device abstraction layer, I do not know what we can do to help them.

**Comment by leet0rz** [comment]
> I'm a bit concerned, then! If there are no processes running, we have shut them down or terminated their console connection. They are expected to handle their own resource cleanup. If the Cygwin runtime is not garbage-collecting things from their device abstraction layer, I do not know what we can do to help them.

What the process looks like:

![bczRVkv 1](https://github.com/microsoft/terminal/assets/29175192/b1ffc734-5543-414c-b7bb-164399435e37)
![rKN36Nq 1](https://github.com/microsoft/terminal/assets/29175192/7682b9b2-c76d-47b4-8870-be11af8dada4)
![OMB90Z2 1](https://github.com/microsoft/terminal/assets/29175192/7c6088d5-def8-4bb2-88d0-0c74a2810a09)

I do close the windows but it seems they are still running in the background so windows terminal is not eliminating them properly.

**Comment by leet0rz** [comment]
> I'm a bit concerned, then! If there are no processes running, we have shut them down or terminated their console connection. They are expected to handle their own resource cleanup. If the Cygwin runtime is not garbage-collecting things from their device abstraction layer, I do not know what we can do to help them.

They do shut down by themselves and also in other similar applications to windows terminal.

**Comment by DHowett** [comment]
Thanks for all the info!

It looks like you're able to reproduce this pretty readily, which is great! We're not able to :smile:

Would you be able to grab a dump file from one of those instances of OpenConsole.exe? Hopefully one of the ones attached to a process you've _definitely_ closed.

Since you're using Process Explorer, you can right-click and select `Create Dump > Create Full Dump...`

Thanks!

**Comment by leet0rz** [comment]
> Thanks for all the info!
> 
> It looks like you're able to reproduce this pretty readily, which is great! We're not able to 😄
> 
> Would you be able to grab a dump file from one of those instances of OpenConsole.exe? Hopefully one of the ones attached to a process you've _definitely_ closed.
> 
> Since you're using Process Explorer, you can right-click and select `Create Dump > Create Full Dump...`
> 
> Thanks!

Thanks. I was not able to upload the file through github as it was too big, so I used dropbox instead:
[https://www.dropbox.com/scl/fi/6jct6hc28952aalm7cums/OpenConsole.rar](url)

I attached 2 files so that one of them should 100% be the file we are looking for.

**Comment by DHowett** [comment]
Thanks for following up! Unfortunately, I'm apparently unable to access your Dropbox share without an account...

<img width="688" alt="image" src="https://github.com/microsoft/terminal/assets/189190/56e5318d-87ad-44a4-b788-14e1312d292d">

**Comment by leet0rz** [comment]
Been messing around with a little more. It seems that if I run git-bash and have git-bash change to zsh it might be causing the leaking instance problem. I have been running zsh directly instead and it might have solved the problem, I will keep testing and see if that is the case. Hopefully there are no plugins in the picture as well that might be causing this, but I'll keep using this and see if I find any more cases of leakage and it not closing properly. Thanks for your work! Looking forward to 1.20 :)
