### ISSUE TITLE
Language setting is missing in zip release

### ISSUE THREAD

**Issue by Gyokur0** [microsoft/terminal#16018]
### Steps to reproduce

Download the zip release (https://github.com/microsoft/terminal/releases/latest) 
Microsoft.WindowsTerminal_1.17.11461.0_x64.zip 

Start the application and open the settings menu and go to appearance, the setting for language is missing.

### Expected Behavior

That the settings are identical to the msixbundle version.

### Actual Behavior

Language setting is missing.
Perhaps other settings are missing too?

**Comment by DHowett** [comment]
Thanks for filing this! Unfortunately, the localization API we're using requires a "package," and the ZIP release isn't compatible with it. I'll update the docs to note the deficiency.
