### ISSUE TITLE
Bug Report: Right Alt key modifier doesn't work with azerty french pc 

### ISSUE THREAD

**Issue by vlj** [microsoft/terminal#1601]
I cannot access character using the right alt key modifier. It looks like the right alt modifier is ignored.

Not accessible key are:
~#{[|`\^@]} 
Which makes typing path or writing powershell command not possible.

# Environment

```none
Windows build number: Microsoft Windows [version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

With Windows May 2019 and all updates, and terminal preview.
Using french defautl layout (azerty french)
Type "C:\"

# Expected behavior

"C:_" is displayed

# Actual behavior

"C:\" is displayed

**Comment by tomasr** [comment]
+1 from me. I use a keyboard with Latin American layout, and it's unusable currently.

Typing `AltGr+[+ key]` to try to type `~` doesn't work at all.

Typing `AltGr+[{ key]` to type `^` works but only in a clunky way (i.e it only works if you do a backspace immediately after).

**Comment by DHowett-MSFT** [comment]
There is an issue about AltGr pinned to the top of the issues list.
