### ISSUE TITLE
The current line height won't change the full-height characters' height such as indent character

### ISSUE THREAD

**Issue by vollowx** [microsoft/terminal#16025]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22631.0

### Other Software

NeoVim Nightly (inside WSL)

### Steps to reproduce

1. Get inside a WSL
2. Install NeoVim Nightly in your way (not only nightly can reproduce, but my config requires nightly)
3. `git clone git@github.com:vollowx/.nvim.git ~/.config/nvim`
4. `nvim`
5. Open a file that have indentations

### Expected Behavior

The indentation characters can be automatically set height and be a line.

### Actual Behavior

Their height is fixed.

![image](https://github.com/microsoft/terminal/assets/73375859/eb15fa64-5f8d-47ba-a26a-170f0a749547)

**Comment by lhecker** [comment]
Your indentation character is U+258F "▏" - a block elements glyph. Right now, we draw those the exact way the font designed them, which may be too short if you've customized your line height. (Previously we would stretch them but that would result in other issues, so we stopped doing that.)
What you want requires us to draw our own, custom block element glyphs that are always the perfect size. We track this over here: #5897

Right now we have no plans to work on that issue, but we loosely sort our backlog priorities by the number of 👍 on our issues. In other words, it'd be nice if you could leave an upvote over at #5897. 🙂
(We're also happy to accept any contributions working towards resolving that issue of course!)

/dup #5897
