### ISSUE TITLE
Rule based Tab Colors

### ISSUE THREAD

**Issue by domsch1988** [microsoft/terminal#16029]
# Description of the new feature/enhancement

I use Windows Terminal for a lot of SSH Sessions throughout the day. The Tab Title correctly shows the bash prompt after connection. It would be great if one could define rules based on which the tab color gets set.
Examples could be that all SSH Tags are blue. Or every Tab with "root" in it's title is red. With custom bash prompts a lot more could be done. Things like coloring tabs that are in a git repository.

A basic "contains" option would be great. Maybe this could be extended to some regex matching to allow for greater Flexibility.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7906 for more discussion.

/dup #7906
