### ISSUE TITLE
Feature Request: Zmodem/lrzsz support

### ISSUE THREAD

**Issue by littlef0x** [microsoft/terminal#1602]
# Summary of the new feature/enhancement

For terminals which support zmodem protocol (like Xshell), one can use lrzsz to upload and download files from remote server directly through ther terminal, or even drag and drop files to upload. It will be great if Windows Terminal can support this protocol.

# Proposed technical implementation details (optional)

Unfortunately I cannot provide technical details. But I'd like to say thants for your great work.

**Comment by littlef0x** [comment]
Well, I just realize maybe it should be a powershell issue rather than window terminal? :flushed:

**Comment by DHowett-MSFT** [comment]
This is probably something a plugin could do, but I'm not going to keep it on our backlog since we're probably not going to get to it this side of 2021. :smile:

**Comment by llanc** [comment]
Here is a nice tool called [trzsz](https://github.com/trzsz/trzsz) that can achieve lrzsz-like effect in windows terminal

**Comment by lonnywong** [comment]
https://trzsz.github.io/ssh supports [trzsz](https://github.com/trzsz/trzsz)  ( trz / tsz ), similar to rz / sz.
