### ISSUE TITLE
Weird Placement when first opening terminal on windows 11 

### ISSUE THREAD

**Issue by l-urk** [microsoft/terminal#16022]
### Steps to reproduce

Opening Windows Terminal for the first time on windows 11 on a 1920x1080 screen...

### Expected Behavior

Top left placement similar to CMD.exe.

### Actual Behavior

Bad placement.

**Comment by DHowett** [comment]
Thanks for filing!
Can you share the way in which the window placed poorly? For me, it launches in roughly the same place as CMD does.

<img width="444" alt="image" src="https://github.com/microsoft/terminal/assets/189190/57202004-e8ed-44e5-a351-541a78ed457e">

In addition -- sorry, I may have missed it in the template above -- what version of Terminal are you using?

**Comment by l-urk** [comment]
It's seemingly near random 
<img width="572" alt="Screenshot 2023-09-22 174433" src="https://github.com/microsoft/terminal/assets/112792604/eca69ad1-eed3-42e3-bf54-a990bd8661c6">

**Comment by zadjii-msft** [comment]
That looks like Windows default behavior when opening Win32 apps. They open as a little "cascade" along that diagonal (depending if there's already another app opened at that position).

From https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features#default-size-and-position: 

> An application can allow the system to calculate the initial size or position of a top-level window by specifying CW_USEDEFAULT in [CreateWindowEx](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa). If the application sets the window's coordinates to CW_USEDEFAULT and has created no other top-level windows, the system sets the new window's position relative to the upper left corner of the screen

You can of course set the [`initialPosition`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#launch-position) for the Terminal manually in the settings.
