### ISSUE TITLE
Can't change parameters 

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#16030]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

PowerShell (From Microsoft Store)

### Steps to reproduce

1. Open Terminal
2. Open the settings page
3. Open the PowerShell profile page
4. Try to change command line (I want to add "-nologo" switch) but it doesn't change on Microsoft Store version of PowerShell

### Expected Behavior

Change the command line to: `"C:\Users\Muhammadhussein\AppData\Local\Microsoft\WindowsApps\pwsh.exe" -nologo`

![image](https://github.com/microsoft/terminal/assets/23485114/cfc22350-c9fa-4707-8bff-d340c77a90e4)

### Actual Behavior

The command line does not change and is:
`"C:\Users\Muhammadhussein\AppData\Local\Microsoft\WindowsApps\pwsh.exe"`

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by 237dmitry** [comment]
Try without fullpath. Just `pwsh.exe -nologo`

```
      {
        "colorScheme": "Campbell",
        "commandline": "pwsh.exe -nologo",
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "hidden": false,
        "name": "PowerShell",
        "source": "Windows.Terminal.PowershellCore"
      },
```
