### ISSUE TITLE
Allow Color Schemes to be applied to open tabs.

### ISSUE THREAD

**Issue by 3SCadmin** [microsoft/terminal#16032]
# Description of the new feature/enhancement

Currently color schemes can be applied to profiles, and you can select a profile when opening a new tab.
But once you have an open tab... you can no longer adjust it's appearance.
We can change the color of the tab, but that's all.

Ideally some appear-related settings would remain closable on open tabs,
Let's start with "Color Scheme"

# Proposed technical implementation details (optional)

Right-click on existing tab, find new menu item "Color scheme"
Get a list of installed Color schemes
Select one
Existing tab now has a different Color scheme

**Comment by zadjii-msft** [comment]
You mean something like the [`setColorScheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#set-the-color-scheme) action/?


![preview-set-color-scheme](https://user-images.githubusercontent.com/18356694/114557761-9a3cbd80-9c2f-11eb-987f-eb0c89ee1fa6.gif)

**Comment by 3SCadmin** [comment]
Thank you, I was not aware of that command.
That does exactly what I need.
