### ISSUE TITLE
Default profile list scrolls infinitely when activated via touch

### ISSUE THREAD

**Issue by reynoldsa** [microsoft/terminal#16041]
### Windows Terminal version

1.17.12191.0, 1.18.1462.0, 1.20.2683.0, fresh build off of main (`74748394c17c168843b511dd837268445e5dfd6c`)

### Windows build number

10.0.23545.1000

### Steps to reproduce

1. Load up any of the reported versions of terminal on a machine with a touch screen
2. Open settings any way
3. Tap on the `Default profile` dropdown with touch
4. Scroll with touch or mouse/keyboard

### Expected Behavior

It only scrolls to end of lists

### Actual Behavior

It scrolls forever looping through the list.

Repro **failed** on release Windows `22621`, with both Terminal 1.12.10983.0 and 1.19, so this appears to be some interaction between Windows ~23545 and Terminal. It's also just this menu; haven't seen this in other WinUI dropdowns. I wasn't sure if this would be a bug on Windows or you, so erring on the side of caution.

This in action: https://www.dropbox.com/scl/fi/6hj4jcwo9d4rsrlul3x7d/ScrollMeToTheMoon.mp4?rlkey=23yd7umpgphdp9yjxa992ta9k&dl=0

**Comment by carlos-zamora** [comment]
Hi @reynoldsa. Thanks for the bug report. We think this is by design. In the WIP beta channel, this repros in the settings app in the display resolutions dropdown. You may want to bring this up in the OS bug tracker though.
