### ISSUE TITLE
Atlas Engine randomly scaling certain text

### ISSUE THREAD

**Issue by 035059** [microsoft/terminal#16042]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

NVIM w/ lunarvim v0.9.2 (running in side of WSL, but same behavior exhibited in Powershell)

### Steps to reproduce

write code detected as a comment inside of NVIM

### Expected Behavior

Text is properly rendered with the atlas engine off;
![image](https://github.com/microsoft/terminal/assets/11092249/c8f675a2-ef80-474c-b83f-3655d0ac040e)

### Actual Behavior

Improper scaling of certain letters with Atlas engine turned on;
![image](https://github.com/microsoft/terminal/assets/11092249/b8ed777b-a110-422b-b651-1bdbead0775f)

**Comment by zadjii-msft** [comment]
Can you try again with [Terminal 1.18](https://github.com/microsoft/terminal/releases/tag/v1.18.2681.0), or even [Terminal Preview 1.19](https://aka.ms/terminal-preview)/? I'm pretty sure this is a bug we saw before, and have already fixed.

**Comment by 035059** [comment]
Updating to 1.18 fixed the issue, thanks. Sorry if I missed the previous thread on this bug
