### ISSUE TITLE
Apache fails to bind

### ISSUE THREAD

**Issue by imacarthur741** [microsoft/terminal#16045]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.25381.0

### Other Software

Apache/2.4.52 (Ubuntu)

### Steps to reproduce

Reboot after updating to --experimantal apache2 cannot bind to port 80 any more.

### Actual Behavior

(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
[no listening sockets available, shutting down](apache2.service: Control process exited, code=exited, status=1/FAILURE)

root@ACER-Nitro:/usr/sbin# lsof -nP -iTCP -sTCP:LISTEN
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-r  308 systemd-resolve   14u  IPv4  22507      0t0  TCP 127.0.0.53:53 (LISTEN)
mysqld     385           mysql   21u  IPv4  32886      0t0  TCP 127.0.0.1:33060 (LISTEN)
mysqld     385           mysql   23u  IPv4  27396      0t0  TCP 127.0.0.1:3306 (LISTEN)
miniserv. 1867            root    5u  IPv4  52863      0t0  TCP *:10000 (LISTEN)

**Comment by DHowett** [comment]
Hey there! It looks like you've got a WSL issue. I can't move it over to [the WSL repository](https://github.com/microsoft/wsl) myself, so I'll need your help to do that.

**Comment by imacarthur741** [comment]
Sorry. I thought that was the wsl repository. I got the link from a wsl support page. I wondered why they asked for the terminal version.On Sep 27, 2023 1:42 PM, "Dustin L. Howett" ***@***.***> wrote:
Hey there! It looks like you've got a WSL issue. I can't move it over to the WSL repository myself, so I'll need your help to do that.

**Comment by DHowett** [comment]
No problem! We're all one big family (which makes it weirder that I can't just transfer issues over to them! Ha!)
