### ISSUE TITLE
v1.18.2681.0 breaks Powershell/WSL2/Commandline Shell (only tested on 23H2 (10.0.22631.2361)) (error 2147942487 (0x80070057))

### ISSUE THREAD

**Issue by sjansen1** [microsoft/terminal#16051]
<hr>

> [!IMPORTANT]  
> 📌 Pinned comment: **https://github.com/microsoft/terminal/issues/16051#issuecomment-1764546234**
> Are you seeing this issue? If you are, please go try the above comment to help debug. Thanks!

<hr>

### Windows Terminal version

1.18.2681.0

### Windows build number

10.0.22631.2361

### Other Software

N/A

### Steps to reproduce

Starting Terminal or Open Tabs with Powershell, WSL2 or Commandline.

### Expected Behavior

Starting the corosponding shell.

### Actual Behavior

Starting windows-terminal with powershell end in "error 8009001d loading managed Powershell" (translated from german error message).

Starting WSL tab end in error in RPC Call Error code: Wsl/Service/0x8007072c

Starting Commandline in terminal works, but has a PATH set to (NULL).

Deinstallation of Windows Terminal and downgrade to v1.17.11461.0 fixes this issues. The same happens with latest Preview version i tested after this issue arise.

**Comment by lhecker** [comment]
Does the issue happen if you use our portable version from our release page (the .zip files)? https://github.com/microsoft/terminal/releases/tag/v1.18.2681.0

**Comment by sjansen1** [comment]
@lhecker i uninstall windows-terminal and downloaded and unpacked https://github.com/microsoft/terminal/releases/download/v1.18.2681.0/Microsoft.WindowsTerminal_1.18.2681.0_x64.zip and started WindowsTerminal.exe

Same issue:

Powershell:
Interner Windows PowerShell-Fehler. Fehler 8009001d beim Laden der verwalteten Windows PowerShell.
[Verarbeitung des Prozesses mit Code 4294901760 (0xffff0000) beendet]

WSL:
Der RPC-Aufruf enthält ein Handle, das sich vom deklarierten Handletyp unterscheidet.
Error code: Wsl/Service/0x8007072c

Commandline:
Still missing a hugh amount of environment variables in comparison to a started cmd.exe

**Comment by lhecker** [comment]
Ah I think I have an idea what's going on. Your environment variables are broken.

Can you launch `regedit`, navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment` and make a screenshot of what you see?

**Comment by lhecker** [comment]
And what about the contents of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion`? Does it look like this?
![image](https://github.com/microsoft/terminal/assets/2256941/000440db-a9dc-474f-aff5-a87af3cd664e)

When you open the permissions dialog here:
![image](https://github.com/microsoft/terminal/assets/2256941/51edb1fb-09e1-4b07-8273-7b4e02c462b2)

and you select "Users" does it look like this?
![image](https://github.com/microsoft/terminal/assets/2256941/4d42d043-b539-4124-b75c-72765de53d34)

**Comment by sjansen1** [comment]
<img width="383" alt="image" src="https://github.com/microsoft/terminal/assets/8289580/2f92b1f5-82d7-440f-a33b-b150674257e3">

![image](https://github.com/microsoft/terminal/assets/8289580/24bd13d4-3e51-4087-a027-37151836b077)

So far it looks similar to your settings.

**Comment by DefectInsect** [comment]
I have the same issues with the recent release. PATH is Null for CMD and PSCore. PowerShell 5.1 won't start with the aformentioned error. Terminal's completely unusable.

Windows is also set to german over here.

**Comment by lhecker** [comment]
Does one of you feel comfortable to run a piece of C++ code under a debugger on your system?

**Comment by sjansen1** [comment]
> Does one of you feel comfortable to run a piece of C++ code under a debugger on your system?

MDE is a bit picky with unsigned code, but i can try.

**Comment by sjansen1** [comment]
My private machine show the same issue after the update, another machine with 23h2.

**Comment by sayandipdutta** [comment]
I am facing similar issue with preview version 1.19.2682.0, windows 25951.1010. Any idea on what's going on?

**Comment by zadjii-msft** [comment]
> Analyzing a bit, it seems to be that OpenConsole.exe never gets around to trying to start the exe (in procmon, there is no "pwsh" in the entire capture from OpenConsole.exe on a machine where this is broken).
> 
> Note that e.g. `./OpenConsole.exe pwsh.exe` or similar works ok.

From #16087

**Comment by zadjii-msft** [comment]
Here's a theory - y'all might be able to get unblocked by setting:

```json
"profiles":
{
    "defaults": 
    {
        "compatibility.reloadEnvironmentVariables": false
    },
    "list":
    [
        // ...
    ]
}
```

in your settings.json. Now, why that regressed, and seemingly only in `10.0.22631.2361` sure is curious.

If you're seeing this, is your `Path` under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment` a `REG_SZ` or a `REG_EXPAND_SZ`?

**Comment by sjansen1** [comment]
> If you're seeing this, is your `Path` under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment` a `REG_SZ` or a `REG_EXPAND_SZ`?

@zadjii-msft Path is a REG_SZ

**Setting "compatibility.reloadEnvironmentVariables": false** in settings.json has no effect.

**Comment by cyanite** [comment]
@zadjii-msft, the addition of `"compatibility.reloadEnvironmentVariables": false` has the effect that now every _new_ tab you open works fine, just not the initial one (which fails like before). So PowerShell also works, if you just press + after the initial one has failed. All of them do.

As for the registry, it's a REG_EXPAND_SZ key for the affected machine.

**Comment by lhecker** [comment]
Sorry for the delay, here's the C++ code: https://gist.github.com/lhecker/f0bd197c8aa8ecf1aeb6505115bb7646
It would be very helpful if someone could try to compile and run it under a debugger. It should pause at some point during the execution. A stack trace and maybe a screenshot of the local variables would be nice. 🙂

But yesterday we realized we can also just use a WPR trace to get a hold of the WIL error logs, so if the above doesn't work out (because it's rather cumbersome), there's still another way to go about this.

**Comment by zadjii-msft** [comment]
Also, squinting at the code:

https://github.com/microsoft/terminal/blob/6489f6b39daaef634dd0e56e50afa8866f0103c7/src/inc/til/env.h#L226-L232

That calls the string version of `wil::TryGetEnvironmentVariableW`

https://github.com/microsoft/wil/blob/be13859134711a1b1206da484f2f6b8b41feb883/include/wil/win32_helpers.h#L604-L609
```c++
    string_type TryGetEnvironmentVariableW(_In_ PCWSTR key)
    {
        string_type result{};
        THROW_IF_FAILED((wil::TryGetEnvironmentVariableW<string_type, initialBufferLength>(key, result)));
        return result;
    }
```

So that can throw if we don't find the env var. Then in `regenerate`, we do:

https://github.com/microsoft/terminal/blob/6489f6b39daaef634dd0e56e50afa8866f0103c7/src/inc/til/env.h#L537-L560

Huh, looks like we `get` a bunch of variables. I can't help but think one of those blows up in this scenario. The [aformentioned](https://github.com/microsoft/terminal/issues/16051#issuecomment-1744790570) script under a debugger might tell us which. But maybe all those need to be `try_get` or something.

**Comment by sjansen1** [comment]
I just run it and this is the result:

# .\Get-EnvsWithEmbeddedNull.ps1
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: Path
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: PSModulePath
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: PROCESSOR_REVISION
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: JAVA_HOME

I dont know what is wrong with this. I removeed PROCESSOR_REVISION and recreated it with the same value, it still show up in your script.

**Comment by lhecker** [comment]
Oh I see... That's because I tested my script on PowerShell 7 (`pwsh.exe`) and you probably use PowerShell 5 (`powershell.exe`). The fix is to use `Contains("`0")` instead of `Contains(0)`. I've updated the script I've linked above with the fix. Can you test it again?

**Comment by cyanite** [comment]
@lhecker bingo! That's the problem. The "lovely" tool Snow Inventory Manager, that my company uses, has this:

    C:\src # C:\Users\Z6SFG\check.ps1
    HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: SNOW_INVENTORY_HOME

With the value:

    C:\Program Files\INVENTORYCLIENT믃蔟℀退幠˕幠˕ etc. etc.

**Comment by lhecker** [comment]
Thanks for confirming this! I've been rewriting the environment-reload code the last few days (twice as fast, half the code 🎉) and I've got a patch ready to hotfix it in the already released 1.18 branch.

**Comment by JaredChilders** [comment]
I've been getting this same issue, only when I open Windows Terminal. For some reason the terminal is having trouble connecting to Ubuntu and Powershell instance. But if I open the standalone Powershell terminal and standalone Ubuntu terminal, things run fine.

Ubuntu in Windows Terminal
![image](https://github.com/microsoft/terminal/assets/9031951/cd4e981c-05fa-41cb-9340-bd7d25b9863d)

Powershell in Windows Terminal
![image](https://github.com/microsoft/terminal/assets/9031951/6b950667-a307-4196-8e73-cb346317a909)

**Comment by igshipilov** [comment]
> Here's a theory - y'all might be able to get unblocked by setting:
> 
> ```json
> "profiles":
> {
>     "defaults": 
>     {
>         "compatibility.reloadEnvironmentVariables": false
>     },
>     "list":
>     [
>         // ...
>     ]
> }
> ```
> 
> in your settings.json. Now, why that regressed, and seemingly only in `10.0.22631.2361` sure is curious.
> 
> If you're seeing this, is your `Path` under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment` a `REG_SZ` or a `REG_EXPAND_SZ`?

I have the same problem:
```
Error code: Wsl/Service/0x8007072c

[process exited with code 4294967295 (0xffffffff)]
```
If I have `REG_EXPAND_SZ`, what should I do then?
![path](https://github.com/microsoft/terminal/assets/57264879/12f95bc1-3f48-46ba-8d86-7af768c43fa9)
![WSL error](https://github.com/microsoft/terminal/assets/57264879/cf0d7df8-c783-4026-8da8-8d794e5d52e5)

**Comment by bjarne-gram** [comment]
> @lhecker bingo! That's the problem. The "lovely" tool Snow Inventory Manager, that my company uses, has a NUL:
> 
> ```
> C:\src # ~\check.ps1
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment: SNOW_INVENTORY_HOME
> ```
> 
> With the value:
> 
> ```
> C:\Program Files\INVENTORYCLIENT믃蔟℀退幠˕幠˕ etc. etc. 
> ```
> 
> Obviously only the part before the Hanzi makes it into the environment variable itself.

Same issue here, but no chinese charachters.

I just copied the value from the SNOW_INVENTORY_HOME variable into Notepad and copied and pasted it back into RegEdit, and voila - it worked - for me anyway...

**Comment by mutr87** [comment]
> > Based on this idea I've written this PowerShell script: https://gist.github.com/lhecker/393252fb1e95b3bc118d40ace802a505 If you run it, it should list all environment strings that contain embedded null bytes/characters.
> 
> This solved it for me.
> 
> In my case it was the Innovaphone MyApps SDK libraries that updated two env variables `LIBJABRA_TRACE_LEVEL` and `LIBYEALINK_TRACE_LEVEL` with null bytes

Same solution for me:
HKEY_CURRENT_USER\Environment: LIBJABRA_TRACE_LEVEL was causing the issue. (I also have innovaphone MyApps installed)
Opened it in regedit and just saved the value again - Terminal workl again without issues!

**Comment by lnorton89** [comment]
Can we get a fix for this? Running the above PowerShell script did nothing.

**Comment by bjarnegram** [comment]
> Can we get a fix for this? Running the above PowerShell script did nothing.

The script doesn't solve the problem, it lists Environment Variables with NULL values. As mentioned above, open the value in RegEdit and save it again, and you're good.

That said - I agree - we should have a fix!

**Comment by lnorton89** [comment]
Isn't Billy G paying ya'll? Jesus.

**Comment by wisewtf** [comment]
> [lnorton89](/lnorton89)

There's a commit to fix this error already, if you've bothered reading this issue, at all.

**Comment by lnorton89** [comment]
Great, when would production users see this?

**Comment by zadjii-msft** [comment]
Y'all are getting a little spicy in here. Too spicy for before the morning coffee pot. We're working on minting a fresh servicing build and rolling that out to the Store. Probably in the coming days. Thanks for your patience.
