### ISSUE TITLE
intellisense is not working with the new preview terminal

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/terminal#16053]
### Windows Terminal version

 v1.19.2682.0

### Steps to reproduce

use the settings.json and profile file and check the intellisense feature if it works

### Expected Behavior

intellisense should work

### Actual Behavior

intellisense does not work
[profile.txt](https://github.com/microsoft/terminal/files/12751890/profile.txt)

[settings.txt](https://github.com/microsoft/terminal/files/12751900/settings.txt)

**Comment by zadjii-msft** [comment]
Looks like you didn't add `"experimental.enableShellCompletionMenu": true,` or the `{ "command": { "action": "sendInput", "input": "\u001b[24~b" }, "keys": "ctrl+space", "name": "Trigger shell completions" }` action to your `settings.json`. Can you try adding those and try again/?

**Comment by sanket-bhalerao** [comment]
i ahve added it to the profiles list in the settings.json, is that the incorrect place?

**Comment by sanket-bhalerao** [comment]
i completely misunderstood  the config and did something wrong initially.
it is now working.
Thank you.
closing the ticket.
