### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by arebee** [microsoft/terminal#1605]
# Environment

```Windows 10 20H1 builds```

# Any other software?

```No```

# Steps to reproduce

1. Open Terminal.
1. Type any command string involving path or word boundaries.
1. Press Ctrl+Backspace to delete to separator or word boundary. Fails.

# Expected behavior
Pressing ctrl-backspace should delete through to word boundaries as it does using old conhost cmd.exe based console.

Open cmd.exe directly and repeat 2+3 for success.

# Actual behavior

Single character deletion.

**Comment by DHowett-MSFT** [comment]
#755

**Comment by arebee** [comment]
@DHowett-MSFT https://github.com/microsoft/terminal/search?utf8=%E2%9C%93&q=ctrl-backspace&type=
