### ISSUE TITLE
opens powershell

### ISSUE THREAD

**Issue by rocco7657** [microsoft/terminal#16064]
### Steps to reproduce

when i open the app it opens powershell instead

### Expected Behavior

i was expecting it to open terminal

### Actual Behavior

opened powershell

**Comment by DHowett** [comment]
PowerShell runs _inside_ Terminal.

Terminal is this part:

<img width="871" alt="image" src="https://github.com/microsoft/terminal/assets/189190/17858a9f-7bd9-4dee-be82-da2d84dc9fc6">

**Comment by rocco7657** [comment]
But there's no customisations on it?. It looks the same as.cmd

**Comment by zadjii-msft** [comment]
Can you clarify/? How did you launch the Terminal? Can you share a screenshot? (protip: Github lets you upload images just by pasting into the comment box)

**Comment by rocco7657** [comment]
I cant take a screen shot as I'm not near my computer. I launched it by
typing terminal in the Windows search bar, then it would just come up with
a default powershell window(powershell is my default thing, I can also
change it to cmd and stuff,but that made no difference)
I also then downloaded the preview terminal thing from Microsoft store but
that was no different.

**Comment by thecodereule** [comment]
Once you open the terminal, you have to click on this upside down caret sign.

![image](https://github.com/microsoft/terminal/assets/97162709/e0acb2ff-9009-47a0-907d-265925166d47)

Next, navigate to the Settings tab, and open the settings window.
Under "Default Terminal application" choose "Terminal".
And under "Default profile" choose which terminal profile you want to open when you run the terminal application.

![image](https://github.com/microsoft/terminal/assets/97162709/66e0a36a-8882-4be3-bc26-bf15d92b8f86)

I hope that has helped.

**Comment by rocco7657** [comment]
Thanks.

**Comment by zadjii-msft** [comment]
(That sounds like it answered your question - feel free to reply back here if it didn't)
