### ISSUE TITLE
[Question] How to send command line to the console of a profile

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#16062]
# Description of the new feature/enhancement

How can I start WT with a specified profile and send arguments to the console of this profile (e.g. use Powershell profile and ping host).

I tired `wt.exe new-tab -p "Powershell" -c "Get-Services"` which results in an error message:
```
[Fehler 2147942402 (0x80070002) beim Start von `{Get-Services}']
```

xref: https://learn.microsoft.com/de-de/windows/terminal/command-line-arguments?tabs=windows#passing-an-argument-to-the-default-shell

# Proposed technical implementation details (optional)

**Comment by htcfreek** [comment]
@zadjii-msft 
Is the problem I described a bug or simply not implemented?

**Comment by zadjii-msft** [comment]
Oh, I think you're just doing it wrong here. I _suspect_ what you're trying to do is the `--appendCommandline` thing, from #5528 / #15822.

When you call `wt -p "PowerShell" -c Get-Services`, `wt` treats `-c Get-Services` as the `command` parameter, and _replaces_ your PowerShell profile's `commandline` with that. And `CreateProcess("-c Get-Services",...)` clearly doesn't work 😝 

So, you'll either want 
* `wt -p PowerShell -- {path to powershell} -c Get-Services`
* `wt -p PowerShell --appendCommandline -- -c Get-Services` (starting in v1.19)

**Comment by htcfreek** [comment]
> So, you'll either want `wt -p PowerShell -- {path to powershell} -c Get-Services`

@zadjii-msft 
Does `{path to powershell}` respect the path variable? Or do I need to specify the full path?

**Comment by zadjii-msft** [comment]
Typically, yes, it'll respect the `PATH`. If you're just doing simple scripting, that's usually fine, though, BEST PRACTICE would be to specify the full path.

**Comment by htcfreek** [comment]
@zadjii-msft 
Thank you for your help. I think this is what I need. 
Unfortunately I can't test the v1.19 command line because `wt.exe` entered in run dialog brings me an `yaccess denied` error.
