### ISSUE TITLE
Some emoji, eg '😃' don't work, whereas others like '⏰' do

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1606]
Using app store preview build, with Win + x to send 😃 and then ⏰:

![image](https://user-images.githubusercontent.com/172594/60107029-149c0500-975e-11e9-81ab-a5475b746ac6.png)

Microsoft Windows 10.0.18362

**Comment by kierenj** [comment]
I would say that neither of those work for me, with Input Mono font. Should this be font-specific?

**Comment by DHowett-MSFT** [comment]
It shouldn't be font specific. What shell is that? It looks like it might be powershell.

Powershell has trouble with high unicode input ... and there's not much we can do to help that.

**Comment by mikemaccana** [comment]
@DHowett-MSFT Powershell 6.2.1. I'll pass it to powershell.
