### ISSUE TITLE
Terminal ignores Profile termination behavior setting

### ISSUE THREAD

**Issue by Avi0** [microsoft/terminal#16068]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.22621.0

### Other Software

WSL

### Steps to reproduce

Set Profile termination behavior to "Close when process exits, fails, or crashes". Make profile exit with non-zero exit code. I can reproduce this in WSL, for example, by listing a non-existing file `ls 123`, then `exit`.

### Expected Behavior

Tab closes silently. (Terminal 1.18 closes tab silently in this case).

### Actual Behavior

This message is displayed:

```
[process exited with code 2 (0x00000002)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by joaoricarte** [comment]
I am in the same terminal version and I can confirm this issue. In the previous version, this wouldn't happen.

**Comment by zadjii-msft** [comment]
notes:

https://github.com/microsoft/terminal/blob/1669036e595bcc8a100e7b8b679dc8f4748f2eb7/src/cascadia/TerminalApp/Pane.cpp#L1069-L1076

When we get there as we're exiting, `previousConnectionState` is evaluated as... `NotConnected`? So we never propogated up the `Connecting`, `Connected`? weird....
