### ISSUE TITLE
override fonts on a language by language basis

### ISSUE THREAD

**Issue by BPplays** [microsoft/terminal#16069]
# Description of the new feature/enhancement
an option to override fonts on a language by language basis, so i could have a main monospace font with extra symbols like from [nerd fonts](https://github.com/ryanoasis/nerd-fonts), and a seprate font for japanese.

also an option to select fallback fonts would be useful too

**Comment by zadjii-msft** [comment]
I'd bet this is just /dup #2664. Thanks!
