### ISSUE TITLE
Launch position negative X not working.

### ISSUE THREAD

**Issue by OMSmolina** [microsoft/terminal#16076]
### Windows Terminal version

1.17.11461.0

### Windows build number

Microsoft Windows [Version 10.0.19044.3086]

### Steps to reproduce

I have 3 x 1920x1080 monitors with landscape orientation.

![image](https://github.com/microsoft/terminal/assets/6513086/40c51674-a4f6-454d-bed9-ab28d112d8a4)

Monitor 2 (main display): X starts in 0
Monitor 3: X starts in +1920

_The problem_

Monitor 1: X starts in _**-1920**_

When I try to put a negative number it doesn't let me, it puts the number 1.

![image](https://github.com/microsoft/terminal/assets/6513086/1c51dcb1-b66a-49db-adac-ddbab7c400c0)

### Expected Behavior

The expected behavior is to be able to enter **negative** numbers **_-1920_**

![image](https://github.com/microsoft/terminal/assets/6513086/3566b1a1-a6d7-404b-a25d-00615555279d)

### Actual Behavior

The current behavior does **_NOT_** allow entering **negative** numbers

**Comment by Lo0oG** [comment]
Duplicate of #15832
Was fixed in v1.18.2681.0 & v1.19.2682.0

**Comment by OMSmolina** [comment]
> Duplicate of #15832 Was fixed in v1.18.2681.0 & v1.19.2682.0

I'm sorry, I should have looked better at the bugs and I'm using the Microsoft Store version too.🤦🏻‍♂️
