### ISSUE TITLE
Enhance visibility of tabs in dark mode

### ISSUE THREAD

**Issue by jabwd** [microsoft/terminal#16070]
Enhanced darkmode. I can't actually visibly easily tell which tab is active because of the lack of contrast.
I tried searching for issues related to this but it is possible I've done a poor job of that.

Increased visibility of the darkmode tabs, its a patch I'm willing to make but since its visual I think its unlikely that it'll be accepted at face value.

Darkmode users to have better visibility into what tabs they're actually in. Maybe very good screens are clearer on this, but it shouldn't be a pre-requisite on using Terminal.

**Comment by zadjii-msft** [comment]
You can probably just configure this yourself nowadays, with ["Themes"](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes). Maybe something like:

```json
"theme": "super dark"
"themes":
[
    {
    "name": "super dark",
    "window": {
        "applicationTheme": "dark"
    },
    "tab": {
        "background": "#000000ff",
        "unfocusedBackground": "#00000000"
    },
    "tabRow": {
        "background": "#555555ff",
        "unfocusedBackground": "#333333FF"
    }
},
]
```

so that the tabs would look like `#000000` on `#555555` by default/?

**Comment by jabwd** [comment]
I had no clue that was an option, thank you very much. I'll be closing the issue!
