### ISSUE TITLE
Is `mica` dead?

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#16074]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.22621

### Steps to reproduce

Windows Terminal does not start with `mica` theme:

```
  "theme": "mica",
  "themes": [
    {
      "name": "mica",
      "tabRow": {
        "background": "#00000000",
        "unfocusedBackground": null
      },
      "window": {
        "applicationTheme": "system",
        "useMica": true
      }
    }
  ],
```

### Expected Behavior

Correct working

### Actual Behavior

WT does not start at all. Is this theme no longer available?

**Comment by zadjii-msft** [comment]
yikes, this was #16046. We'll service this early next week. As a workaround, add a `tab` theme object:
```json
  "theme": "mica",
  "themes": [
    {
      "name": "mica",
      "tabRow": {
        "background": "#00000000",
        "unfocusedBackground": null
      },
      "tab": {},
      "window": {
        "applicationTheme": "system",
        "useMica": true
      }
    }
  ],
```

/dup #16046

**Comment by 237dmitry** [comment]
Thank you!
