### ISSUE TITLE
wt.exe (preview) brings access denied error in run dialog

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#16085]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.19045

### Other Software

Windows Terminal v1.18 (1.18.2681.0)

### Steps to reproduce

1. Install Windows Terminal v1.18 (stable) from the Store.
2. Install Windows Terminal v1.19 (preview) from the Store.
3. Change app alias `wt.exe` from Windows Terminal stable (v1.18) to Windows Terminal Preview (v1.19).
4. Open Run dialog and type `wt.exe`.

### Expected Behavior

Windows Terminal preview opens.

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/61519853/c5490aa6-67fa-4c72-b343-dcc80d417c17)

"Can't access the device, path or file. You don't have the required permissions to access this element."

**Comment by zadjii-msft** [comment]
Does just launching Terminal Preview directly from the Start Menu (not using the "App execution alias", `wt.exe`) work? 

This sounds like something that'll need to be filed internally using the /Feedback Hub. The bot should come through with some instructions. However, instead of filing feedback on the Terminal app, could you file it on "Developer Platform > App Launch"? 
![image](https://github.com/microsoft/terminal/assets/18356694/5ed4d2a2-91b6-45ef-aff9-da0766771d4f)

**Comment by htcfreek** [comment]
> Does just launching Terminal Preview directly from the Start Menu (not using the \"App execution alias\", wt.exe) work?

@zadjii-msft 
Yes it does.

Regarding the feedback hub: I will send it tomorrow. Should I reference this GH issue somehow?

**Comment by zadjii-msft** [comment]
> Should I reference this GH issue somehow

meh, probably no need. Just make sure to share the aka.ms link that it generates, so that I can make sure to promote it to the right team ☺️

**Comment by htcfreek** [comment]
@zadjii-msft 
I created the feedback. But I can't record as it failed to start recording and I didn't get an link to my report.

**Comment by carlos-zamora** [comment]
@htcfreek thanks! Mind trying again? Sometimes feedback recording can be wonky.

**Comment by htcfreek** [comment]
Will try again. Btw, ot doesn't happen in my Win11 VM.

**Comment by htcfreek** [comment]
@carlos-zamora 
I was able to do a recording.

But again I don't have a link for you. Hopefully the following information help you to find the feedback.
- Category: Developer Plattform > App commandline
- Title: When entering wt.exe (Windows Terminal Preview) in the Run dialog I get an access denied error
- Text:
```
Steps to reproduce:
1. Install Windows Terminal (v1.18)
2. Install Windows Terminal Preview (v1.19)
3. Change app alias for wt.exe from WT to WT Preview.
4. Open run prompt, enter wt.exe and press enter.

Expexted:
Windows Terminal Preview opens.

What has happened:
The error message "The specified device or path or file cannot be accessed. You may not have sufficient permissions to access the item." is shown.
```

**Comment by zadjii-msft** [comment]
I'm pretty sure the backend changed recently... kinda having a hard time finding this. Did you click the Share button? 
![image](https://github.com/microsoft/terminal/assets/18356694/887d0c06-c776-494f-a3a4-750d899d14d7)

**Comment by htcfreek** [comment]
I am not logged in so I can't access my recently added feedback. And as I couldn't find the first one usig the search I can't use a share button. Since the second feedback I am out of office for two weeks. I will try to find and "share" the second feedback when I am back on my computer.

**Comment by htcfreek** [comment]
@zadjii-msft 
I can't share you a link. I tried everything but I can't find my feedback even if I enter the exact title. My it is not visible to the public. (As I wasn't logged in when sending the feedback I don't have a "My Feedback" list.) Feel free to close this issue.
