### ISSUE TITLE
Tab tearout doesn't work with Run as administrator

### ISSUE THREAD

**Issue by lmgr1992** [microsoft/terminal#16082]
### Windows Terminal version

1.18.2681.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Run Windows Terminal as Admnistrator
Try move tabs from one terminal window into the other.

### Actual Behavior

The tabs cannot move no matter how much you press with the mouse. They can only be moved when you do not have administrator privileges.

**Comment by zadjii-msft** [comment]
Alas, this is a platform limitation currently. Dragging & dropping doesn't work for `TabView`s in elevated applications. See /dup #6661
