### ISSUE TITLE
Italic font cannot be displayed properly.

### ISSUE THREAD

**Issue by LittleNewton** [microsoft/terminal#16080]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

- NeoVim 0.9
- SSH (Windows provided)

### Steps to reproduce

1. Install font: [FiraCode Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip)
2. Set the font of a ssh profile as the following: `font='FiraCode Nerd Font Mono' `
3. Enable `Atlas Text Engine`

### Expected Behavior

The italic part should be rendered properly.

### Actual Behavior

The Italic font is rendered not properly. It is weird!

![image](https://github.com/microsoft/terminal/assets/17793356/6e25f103-00c4-49b0-baf6-33aa96dbfd26)

**Comment by lhecker** [comment]
Can you update to version 1.18 and see if it still happens? It has a new version of AtlasEngine.

**Comment by LittleNewton** [comment]
![未标题-1](https://github.com/microsoft/terminal/assets/17793356/e0d22ef6-9c58-423a-bfff-b81fe7b532e7)

I installed the latest version of WindowsTerminal. It looks pretty nice!

**The problem of italic font display has been solved by version 1.18.**
