### ISSUE TITLE
Make terminal beeps highlight Windows Terminal in the taskbar, to get user attention when backgrounded

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1608]
## Scenario

A long running task is running in the Terminal. The user is using another app. 

Something happens requiring attention from the user.

## What happens now

The terminal beeps, but the user doesn't know about it, and doesn't see the issue.

## What should happen

The taskbar item becomes highlighted, showing that the terminal needs attention (optionally this can be disabled).

**Comment by DHowett-MSFT** [comment]
Yep, we should have some bell support. This also requires us to push bells through the conpty layer. :smile:

**Comment by tstackhouse** [comment]
> Yep, we should have some bell support. This also requires us to push bells through the conpty layer. 😄

Does this include audible bells? Because I can't for the life of me get audible bells to work.

**Comment by zadjii-msft** [comment]
@tstackhouse yes it does.

**Comment by bobvandevijver** [comment]
Now that #7793 has been merged, I think this issue will be the main one for tracking the visual bell? 
Anyways, I would love to see both: the audible and visible notification combined, probably with a setting as suggested [here](https://github.com/microsoft/terminal/pull/7793#issuecomment-702232919).

**Comment by j4james** [comment]
FYI there is a system-wide option called _Show audio alerts visually_, which you can set to flash the window border (or even the whole screen), when the bell is triggered. It's probably not exactly what you want, but it may do as temporary solution.

**Comment by duaneking** [comment]
> FYI there is a system-wide option called _Show audio alerts visually_, which you can set to flash the window border (or even the whole screen), when the bell is triggered. It's probably not exactly what you want, but it may do as temporary solution.

And this blatantly discriminates against the blind, if its the only option.  I am requesting that the relevant leadership look at the reprioritization of this issue with that in mind. It's impossible for me to show others that Windows is accessible for the disabled if I have the disabled literally telling me this is one of the core issues because it doesn't respect accessibility the same way Linux does; This is a Linux compete issue for you guys and so I was hoping that you would actually put some effort into this.

**Comment by zadjii-msft** [comment]
@duaneking friend, I get that you're upset by this bug. You have every right to be! But the right way to deal with this is not necroing a bunch of semi-related threads on the topic. 

File a new issue. Include your terminal version, your settings, probably even your Windows SKU (I know there were issues with playing media on the "N" SKU in the past).

We'll try and help debug there ☺️
