### ISSUE TITLE
Terminal can't open any shells (error 2147942487 (0x80070057)); reinstall/local copy doesn't help

### ISSUE THREAD

**Issue by cyanite** [microsoft/terminal#16087]
### Windows Terminal version

1.18.2681.0

### Windows build number

10.0.22621.0

### Steps to reproduce

It broke after an older version, installed via chocolatey (package microsoft-windows-terminal) was attempted upgraded while running. It was originally installed on Windows 10, and the machine was later upgraded to Windows 11. After the failed upgrade, it's broken no matter if reinstalled, or even reinstalled and downloaded as zip and run directly.

Reproduction, then, is starting wt.exe or WindowsTerminal.exe.

### Expected Behavior

That it works :)

### Actual Behavior

When launching, it just displays:

    [error 2147942487 (0x80070057) when launching `"C:\Program Files\PowerShell\7\pwsh.exe"']

(or whatever shell you try; it can't start any.)

Reinstalltion doesn't help. Uninstalling, removing AppData\Local stuff and downloading and starting from unpacked zip doesn't help either.

Analyzing a bit, it seems to be that OpenConsole.exe never gets around to trying to start the exe (in procmon, there is no "pwsh" in the entire capture from OpenConsole.exe on a machine where this is broken).

Note that e.g. `./OpenConsole.exe pwsh.exe` or similar works ok.

**Comment by zadjii-msft** [comment]
This sounds exactly like #16051. You might want to hop in over on that thread. The OpenConsole observation is a good one, thanks ☺️ 

/dup #16051
