### ISSUE TITLE
closeOnExit seems not to work reliably on preview

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#16092]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.22621.2283

### Other Software

Ubuntu-22 WSL

### Steps to reproduce

I wish I could figure it out. I've been doing everything I always do, I have closeOnExit on but I'm routinely seeing the "process exited with code 130 windows terminal press ctrl-d" message

### Expected Behavior

I expect the terminal to 'just close'

### Actual Behavior

terminal doesn't actually close and i see: "process exited with code 130 windows terminal"

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #16068 for more discussion.

/dup #16068

**Comment by dovholuknf** [comment]
Thanks. I __did__ try to look for a duplicate before filing it and I can see why I didn't find it after reading that issue :)
