### ISSUE TITLE
Cannot Connect to Cloud Shell anymore

### ISSUE THREAD

**Issue by bferg317** [microsoft/terminal#16098]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.2283

### Steps to reproduce

1. Create Azure Cloud Shell Tab
2. Step through browser login
3. Select tenant

### Expected Behavior

Expecting a cloud shell terminal.

### Actual Behavior

Requesting a cloud shell instance...
Succeeded.
Requesting a terminal (this might take a while)...

[process exited with code 1 (0x00000001)]

**Comment by zadjii-msft** [comment]
Are you sure that's all the output that was displayed in the Terminal? We're pretty confident that there's supposed to be an exception handler in that path that should have written out the error message from Azure.....


The exception handler only handles `std::exceptions`. Maybe another type of exception was thrown. 
https://github.com/microsoft/terminal/blob/4145f18768772270da03f9ea56b5ec6f7157375c/src/cascadia/TerminalConnection/AzureConnection.cpp#L107-L107

**Comment by zadjii-msft** [comment]
A WPR trace of this would be helpful: [Capturing a Debug ETL Trace](https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#capturing-a-debug-etl-trace)

**Comment by bferg317** [comment]
> A WPR trace of this would be helpful: [Capturing a Debug ETL Trace](https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#capturing-a-debug-etl-trace)

I have uploaded the ETL to Feedback Hub but I'm still waiting for it to show up to link you.

**Comment by PankajBhojwani** [comment]
We've gotten a few of these reports recently so there's likely something here. I have collected traces of the login process from someone who was unable to connect and the current suspicion is that there was an API change on the Azure side that we aren't conforming to. We have set up a meeting with the Cloud Shell team, will update here once that's done.

**Comment by PankajBhojwani** [comment]
A few things - the Azure Cloud Shell team is undergoing some amount of migration regarding where they store the sessions, which could explain why only some users are facing this issue and why it seems to sometimes be intermittent. Other than that, there might be some post-handling of the URLs that Terminal needs to do to make sure our requests are going to the right place and are well formed. We are continuing to investigate this!

**Comment by gpugems** [comment]
same issue.

**Comment by shurick81** [comment]
Is not this happening again?

![image](https://github.com/microsoft/terminal/assets/11289124/b47bcc71-88ec-4784-a97c-5a16ec1c27a7)

But Azure health does not show any regression, so it did not show any issues back in October 2023: https://azure.status.microsoft/en-us/status/history/

**Comment by GraniteGolem** [comment]
> Is not this happening again?
> 
> ![image](https://private-user-images.githubusercontent.com/11289124/298156719-b47bcc71-88ec-4784-a97c-5a16ec1c27a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODgzOTEsIm5iZiI6MTcwNTY4ODA5MSwicGF0aCI6Ii8xMTI4OTEyNC8yOTgxNTY3MTktYjQ3YmNjNzEtODhlYy00Nzg0LWE5N2MtNWExNmVjMWMyN2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE4MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYWRmMmIxYjUyOTZhMjcyMzhkNjc3NGI1MDYzMzMwYjIyMmViYzU0NDAyNGQzOTI5ZDBhZTg3ZGViNzA0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeSMN_pS6xBW1eVDBsT8fxl6YS8obzucEQUOgySIYgE)
> 
> But Azure health does not show any regression, so it did not show any issues back in October 2023: https://azure.status.microsoft/en-us/status/history/

Yes, I am getting this as well. Luckily this is not urgent for me. Will check back tomorrow.

**Comment by brianbaldock** [comment]
Experiencing the same issue on my end.

**Comment by PankajBhojwani** [comment]
I am not able to access the cloud shell even through the azure portal in my browser, which leads me to believe this is an issue on the server side, not Terminal. Can you access the cloud shell in your browser?

**Comment by brianbaldock** [comment]
> I am not able to access the cloud shell even through the azure portal in my browser, which leads me to believe this is an issue on the server side, not Terminal. Can you access the cloud shell in your browser?
> 
> ![image](https://private-user-images.githubusercontent.com/26824113/298169451-42529209-0e2c-45e5-b440-92b8e25a9edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTA5NjAsIm5iZiI6MTcwNTY5MDY2MCwicGF0aCI6Ii8yNjgyNDExMy8yOTgxNjk0NTEtNDI1MjkyMDktMGUyYy00NWU1LWI0NDAtOTJiOGUyNWE5ZWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE4NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NmU1ZTVkZmE1ZTFkZGQ2MDYxNTBmMDI5ZDkyOGRhZDQxM2ZkNGE4MmQ5MDU1ZGMxNDlkMjdhMjA1MGRhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baEL9v52ZjgKebDccplTO4ZVDjYHZDGn0JhKFF9fOQs)

Nope, getting this as an error: 
![image](https://github.com/microsoft/terminal/assets/72090857/b8b92620-b73f-4144-aeda-a7d7b1c56c94)

**Comment by PankajBhojwani** [comment]
Yep so that pretty much confirms its a server side issue. We're going to have to wait on the Cloud Shell team to fix it on their end.

**Comment by brianbaldock** [comment]
Works now 👍 thanks @ team

**Comment by shurick81** [comment]
Shouldn't this be visible in the Azure status pages?

**Comment by DHowett** [comment]
> Shouldn't this be visible in the Azure status pages?

I'm sorry. The Windows Terminal team (as a client of Azure just like y'all) does not control whether anything--or what--shows up on the Azure status apge.

**Comment by donnykwitty** [comment]
This issue is fixed?
Why am I experiencing it now?

```
Requesting a cloud shell instance...
Succeeded.
Requesting a terminal (this might take a while)...

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

```

**Comment by zadjii-msft** [comment]
@donnykwitty Looks like the fix made it into [v1.18.3181.0](https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0) (Stable) / [v1.19.3172.0](https://github.com/microsoft/terminal/releases/tag/v1.19.3172.0) (Preview). Which version are you on?

There was also an incident upstream: https://azure.status.microsoft/en-us/status/history/

![image](https://github.com/microsoft/terminal/assets/18356694/9f3f5b6e-3561-4605-b3a9-9509bb4048fb)

**Comment by shurick81** [comment]
now I can see this too @zadjii-msft !

**Comment by donnykwitty** [comment]
@zadjii-msft Thanks! My bad. I thought Terminal had been updated via Windows update--it hadn't.
