### ISSUE TITLE
Screenfetch/Neofetch-like option on Terminal startup

### ISSUE THREAD

**Issue by Valtekken** [microsoft/terminal#16109]
# Description of the new feature/enhancement

Might not be a priority or anything important, but it would be very nice if users had an option within settings to have the Terminal show something like Screenfetch or Neofetch with an ASCII logo and some basic system information (result would be something like what the picture below shows).
There are some utilities that do this job, but I guess I'd like it to be doable with less effort.
![image](https://github.com/microsoft/terminal/assets/112526564/4975eb3d-c053-4734-97ff-93133491214e)

**Comment by 237dmitry** [comment]
Add "neofetch" to pwsh's `$profile`

**Comment by Valtekken** [comment]
> Add "neofetch" to pwsh's `$profile`

Apparently neofetch isn't a recognized or valid command. Do note that what I'm asking for is something like neofetch in a Windows environment, not WSL, so maybe that's the reason - AFAIK neofetch is a Linux thing

**Comment by zadjii-msft** [comment]
I mean, isn't `neofetch`, not even installed by default on linux?

You can always grab https://github.com/nepnep39/neofetch-win off of winget though 🤷

**Comment by Valtekken** [comment]
> I mean, isn't `neofetch`, not even installed by default on linux?
> 
> You can always grab https://github.com/nepnep39/neofetch-win off of winget though 🤷

I mean yeah, as I said I know that one's an option, but as I said I'd like it if it was a single click native option somewhere in the Terminal settings, you know?

**Comment by DHowett** [comment]
Thanks for the request! I've learned that people are really passionate about the `-fetch` tool they use, given that there's seven or so options. I'd rather keep us out of the fray there, and let folks choose which one they want by customizing their `commandline` settings. :smile:

For now, I'm gonna close this one out. We're not planning to enter the `fetch` fracas!
