### ISSUE TITLE
Ghostly 'Close' button hovering on my Desktop

### ISSUE THREAD

**Issue by strangebit** [microsoft/terminal#16100]
### Windows Terminal version

1.18.2681.0

### Windows build number

10.0.19045.0

### Steps to reproduce

I'm not sure what's triggering it unfortunately.

### Actual Behavior

Ever since `v1.18.2681.0`, I've been getting this issue every day. I never notice when it actually appears, but eventually I notice a ghostly 'Close' button hovering on my Desktop, and it appears to be something attached to Windows Terminal. In the taskbar, I can see it's attached to Windows Terminal and it has the title `Pop-upHost`. If I try to select it, I get a `WindowsTerminal.exe` is not responding, and closing it closes my Windows Terminal.

Windows Terminal appears to work fine if I just leave it alone though.

Taskbar:

![WT_Taskbar_Pop-upHost](https://github.com/microsoft/terminal/assets/11712728/88eec2e0-7f72-4f23-8655-2e520cf51428)

Button over desktop:

![Ghostly_Close](https://github.com/microsoft/terminal/assets/11712728/31d022d9-7d4e-40a6-af79-80f17f17dcc2)

Using NirSoft GUIPropView to inspect two different `Pop-upHost` handles (red sections redacted):

![GUIPropView_Pop-upHost_1](https://github.com/microsoft/terminal/assets/11712728/9301469a-d6a1-42fb-856a-a4beda01ebc3)

![GUIPropView_Pop-upHost_2](https://github.com/microsoft/terminal/assets/11712728/32f1cd34-005d-4fd8-9152-6f59730639f9)

The process (i.e. 13F0) for the second one is Desktop Window Manager (`dwm.exe`).

**Comment by strangebit** [comment]
It appears to be coming from the X button tooltip, as seen here:

![close_tooltip](https://github.com/microsoft/terminal/assets/11712728/5e989eba-8d65-45de-94f9-b4b94ee31df0)

They look the same, and I've verified that a new `PopUp-Host` handle appears in the GUIPropView list when I mouse over the X button, and then disappears when I move the mouse again. Somehow the handles are going rogue and sticking around?

Also I've noticed the ghost ones sometimes go away on their own when I launch a new terminal window, but not always.

**Comment by zadjii-msft** [comment]
Okay I've got a horrifying thought. This might be related to us refrigerating the old windows, stopping pumping their messages, but leaving them around. 

Can you go install this _old_ Terminal Preview version: https://github.com/microsoft/terminal/releases/tag/v1.18.1421.0/? This is the original Terminal 1.18 Preview that didn't have the window thread refrigeration code. If that doesn't repro this, then I'd bet we could narrow it down to that.

**Comment by strangebit** [comment]
As discussed, I've been using Terminal Preview v1.18.1421.0 for a few days now and I haven't experienced the issue on it yet.

**Comment by strangebit** [comment]
Yesterday, I switched back to v1.18.2822.0 to see if it was still happening on the latest version, and I did encounter it again, but only at the very end of a long day. I think it was after I closed one of the windows, which suggests you could be right @zadjii-msft , however it defintely doesn't happen every time I close a window with another window still open, and I had opened and closed many windows that day.

Managed to get a video of another bug I've been noticing too, since I've been paying attention: #16211. I'm not sure if that's related to this issue or not, but it feels like it crops up about as frequently, i.e. after opening and closing windows and using Terminal for a while, etc. I can't remember if I ever saw it when I was using Preview v1.18.1421.0 last week though. I'm going to switch back to Preview v1.18.1421.0 again now, and I'll keep and eye out again for if this issue or #16211 ever occurs on it.

**Comment by RKS-labs** [comment]
Also experienced this on v1.18.2822.0 (Windows 10) with three WT instances and two "PopupHost" close buttons. Attempting to close one of the buttons through the taskbar popped up a "not responding" dialog and killed all three instances of WT.

**Comment by acorderob** [comment]
I also got this "popuphost" window (with v1.18.2822.0 Win10). And it did happen after i closed a second terminal.

**Comment by RKS-labs** [comment]
I got around this by *keep opening* new WT instances until all buttons were gone, then exiting from the command line one by one.

**Comment by alesandroortiz** [comment]
I've had this occur for a few weeks, multiple times per day. I've also seen it occur with a Maximize tooltip. I have not changed my config recently, so it's not related to that. Currently running Terminal version 1.18.2822.0 on Windows 10 Version 22H2 (Build 19045.3570). I'm also using PowerToys v0.75.1, in case that matters. (I did update PowerToys in the past few weeks.)

**Comment by Kaexzr** [comment]
I have the same issue.
Version 1.18.2822.0
It seems to happen more often when I unplug my 2 external monitors from work to go home.
But it could be pure coincidence.
If I terminate that process, all instances of Windows Terminal close, therefore some times I end up with the frozen pop up for days, while I don't cant to close all terminals I have open.  

![image](https://github.com/microsoft/terminal/assets/148399599/da8e9974-c944-4506-b314-14095dd9f0d7)

![image](https://github.com/microsoft/terminal/assets/148399599/b56f618b-b31a-455f-a736-c0741018413f)

**Comment by PhilipMorrisJones** [comment]
Same here. I can get to the close button but if I do so it kills all my open tabs and I have a dozen open ssh sessions so I just accumulate these over time. 

![image](https://github.com/microsoft/terminal/assets/10975951/03f0c834-de06-489c-a864-90853b33ac6c)

![image](https://github.com/microsoft/terminal/assets/10975951/2f18834a-635d-4c1e-b4e5-533030f007b1)

![image](https://github.com/microsoft/terminal/assets/10975951/d631aa50-0765-45a3-9042-2fa24865928d)

**Comment by xLiWHOI** [comment]
Same issue here. Have to press "Ctrl+d" twice now to close tabs/windows.

**Comment by gabbymouth** [comment]
Same issue with both of my computers. This is a PITA because it makes it more difficult to minimize and un-minimize wt to the win 10 taskbar.

**Comment by zadjii-msft** [comment]
Hey we think this was fixed in the latest release - can someone try out the newest 1.19 / 1.20 builds and double check?

**Comment by PhilipMorrisJones** [comment]
Hi @zadjii-msft, do you have a commit ID or issue where the fix was made?

**Comment by zadjii-msft** [comment]
I'm guessing it was one of 
* #16588 
* #16587
* #16592

All of those improved the way window refrigeration was done, and I've got a hypothesis that together, they avoid the issue at the root of this thread.

**Comment by Kaexzr** [comment]
Just an update for anyone interested, 1.19.10302.0 did in fact solve the issue for me.
