### ISSUE TITLE
1.19: `"closeOnExit": "always"` does not work as expected

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#16110]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.22621

### Other Software

Any console app.

### Steps to reproduce

Kill the application from outside. The tab or panel that the app was running in should automatically close. But that's not true.

![Screenshot 2023-10-06 121252](https://github.com/microsoft/terminal/assets/78153320/8fba258e-bf73-4fc1-96e3-0524b45e9044)

### Expected Behavior

Because `closeOnExit` is set to `always`, tabs or panels that have terminated applications should always be closed.

_In 1.18 preview all worked fine_

### Actual Behavior

Tabs or panels do not close when the applications running in them are terminated by external commands or actions.

**Comment by lhecker** [comment]
Hey! We've recently already had a report for this issue at #16068. /dup #16068
It was fixed in #16090 and theoretically an update with this should ship next week or so if everything works out fine.

**Comment by 237dmitry** [comment]
> an update with this should ship next week or so if everything works out fine.

All will be fine
