### ISSUE TITLE
Error displaying specified character in "menlo for powerline" font

### ISSUE THREAD

**Issue by jarlor** [microsoft/terminal#16115]
### Steps to reproduce

I need to adjust the font to "menlo for powerline" for the Agnoster theme "oh my zsh" in my WSL terminal. When I type the characters "f" or "i" respectively I have no problem, but when I type "fi" they are distorted.

### Expected Behavior

![image](https://github.com/microsoft/terminal/assets/53697817/f9365105-3581-4018-ab63-1122d68eccf5)

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/53697817/aedf7022-b467-4faf-a593-770b1ef8cd2d)

**Comment by lhecker** [comment]
Please fill out the issue template. The version numbers aren't there just for fun, but (in this case) to know which font renderer you're using. 😟

The "fi" you're seeing there is a so called ligature. That ligature in particular is very common: https://en.wikipedia.org/wiki/Ligature_(writing)#Latin_alphabet

You can disable ligatures by opening your settings with Ctrl+Shift+, and adding this:
```
{
    "profiles":
    {
        "whatever your profile name is, for instance 'defaults'": {
            "font": {
                "features": {
                    "liga": 1
                }
            }
        }
    }
}
```
