### ISSUE TITLE
Feature Request - Middle mouse button copy/paste

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#1612]
Middle mouse button paste would be awesome too.

_Originally posted by @jberanek in https://github.com/microsoft/terminal/issues/524#issuecomment-502376962_

**Comment by DHowett-MSFT** [comment]
Let's .. just keep all of the mouse-related selection-related stuff in one place :smile:
#524 is a good candidate.

**Comment by DHowett-MSFT** [comment]
@carlos-zamora i'm leaving this one to you to triage. :smile:

**Comment by MattBianco** [comment]
> Let's .. just keep all of the mouse-related selection-related stuff in one place 😄
> #524 is a good candidate.

How can it be a good candidate when #524 is closed without addressing the important middle-click-to-paste?
