### ISSUE TITLE
CTRL + Shift + F Find should highlight all of the items as long as the search bar is open

### ISSUE THREAD

**Issue by HotCakeX** [microsoft/terminal#16128]
When we press CTRL + Shift + F to find something on the console, the results aren't all highlighted, only one result at a time is highlighted, the rest should be cycled through manually.

I need this to change to be just like search in browsers. When you press CTRL + F in Edge and type something, all of the results are highlighted without the need to cycle through them.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7561 for more discussion.

/dup #7561

**Comment by HotCakeX** [comment]
@zadjii-msft Thank you and sorry that I didn't find the duplicate issue.
