### ISSUE TITLE
Bug Report -  | sign does not work using a german language keyboard (QWERTZ)

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#1614]
-->

# Environment

Windows build number: Windows 1903
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
Tried different version of PSh (5.x / 6.2.1 / 7.0.0), and CMD

# Steps to reproduce

the sign | cannot by typed using a german keyboard in Windows 10.

# Expected behavior
I expected this sign to work as it is one of the most important commands in PoSh

# Actual behavior

the output is < instead of | 

**parent issues:**
#521 

**related duplicate issues:**
#1596,#940,#1027,#1010

**Comment by DHowett-MSFT** [comment]
If this issue isn’t different from its parent issue, please don’t file it. I don’t think we need a new issue for every single keyboard key that doesn’t work with AltGr
