### ISSUE TITLE
upgrade failed from 1.17.11461 to 1.18.2681.0

### ISSUE THREAD

**Issue by haishen121** [microsoft/terminal#16153]
### Windows Terminal version

1.17.11461

### Windows build number

10.0.19042.1766

### Steps to reproduce

cmd>winget upgrade Microsoft.WindowsTerminal
尝试更新源时失败： winget
已找到 Windows Terminal [Microsoft.WindowsTerminal] 版本 1.18.2681.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
已成功验证安装程序哈希
正在启动程序包安装...
安装程序失败，退出代码为： 0x80070002 : ϵͳҲָļ

or download and install [Microsoft.WindowsTerminal_1.18.2822.0_8wekyb3d8bbwe.msixbundle](https://github.com/microsoft/terminal/releases/download/v1.18.2822.0/Microsoft.WindowsTerminal_1.18.2822.0_8wekyb3d8bbwe.msixbundle)

### Actual Behavior

安装程序失败，退出代码为： 0x80070002 : ϵͳҲָļ

**Comment by haishen121** [comment]
I noticed a strange prompt on the Windows notification bar regarding the installation process of the UI, which seemed to be an issue

in the end, I try to use [Microsoft.WindowsTerminal_1.18.2822.0_8wekyb3d8bbwe.msixbundle_Windows10_PreinstallKi](https://github.com/microsoft/terminal/releases/download/v1.18.2822.0/Microsoft.WindowsTerminal_1.18.2822.0_8wekyb3d8bbwe.msixbundle_Windows10_PreinstallKit.zip)

Click on the executable files below in order and find that the upgrade was successful！

- Microsoft.UI.Xaml.2.8_8.2306.22001.0_x64__8wekyb3d8bbwe.appx
- 0ef1881c68144b78ad517d9e8e2aab5d.msixbundle

**Comment by zadjii-msft** [comment]
Here's an interesting question - what version of winget are you using/? This feels like that dependency bug, that winget just finally added support for.

**Comment by haishen121** [comment]
@zadjii-msft winget v1.3.2691

**Comment by zadjii-msft** [comment]
Oh, that's... pretty out of date it looks like. I think you'll want at least https://github.com/microsoft/winget-cli/releases/tag/v1.6.2721. Considering you were able to fix this by manually installing MUX 2.8, I'm 99% that was the cause of what you were seeing.
