### ISSUE TITLE
More than 14 profiles

### ISSUE THREAD

**Issue by zackmuc** [microsoft/terminal#16155]
# Description of the new feature/enhancement

I have more than 14 profiles but only see 14

# Proposed technical implementation details (optional)

I want to see all profiles

**Comment by zadjii-msft** [comment]
Could you share a screenshot? I'm pretty confident we display more than 14 profiles:
![image](https://github.com/microsoft/terminal/assets/18356694/4d147e9b-e12e-4269-8f85-500901bf5eec)

**Comment by zackmuc** [comment]
![image](https://github.com/microsoft/terminal/assets/4520343/54a07efd-100f-4e29-8c14-217ba58e2775)
[settings.json](https://github.com/microsoft/terminal/files/12883127/settings.json)
Attached screenshot with 14 and config file with more ..

**Comment by zackmuc** [comment]
Sorry replaced the config

**Comment by zadjii-msft** [comment]
Huh, the curious entries to me are:

```jsonc
            {
                "guid": "{d7b20cea-47a9-518c-95a4-c8bd91e2e1c6}",
                "hidden": false,
                "name": "Ubuntu 22.04.2 LTS",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
            },
            {
                "guid": "{d7b20cea-47a9-518c-95a4-c8bd91e2e1c7}",
                "hidden": false,
                "name": "Ubuntu 22.04.2 LTS",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
            },            {
                "guid": "{d7b20cea-47a9-518c-95a4-c8bd91e2e1c8}",
                "hidden": false,
                "name": "Ubuntu 22.04.2 LTS",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
            },            {
                "guid": "{d7b20cea-47a9-518c-95a4-c8bd91e2e1c9}",
                "hidden": false,
                "name": "Ubuntu 22.04.2 LTS",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
            },
```

Did you make all these? Surely one of them came from the Ubuntu 22.04.2 LTS app, but the others look like they were copy-pasted with only changing the guid. I don't think those'll work like that. 

The one that came from the Ubuntu app is a "fragment profile". Terminal knows that it's associated with the profile that app defined. But the other three - those have a `source`, but when Terminal looks at the actual Ubuntu app, it doesn't find those profiles. I believe in that case, we just discard those extra unmatched profiles. 

You'll want to:
* Make sure to remove the `source` from those profiles
* Make sure to set the `commandline` to `wsl -d Ubuntu-22.04` (where `Ubuntu-22.04` is one of the values from `wsl -l`)
* I don't _think_ they need unique names if you gave them unique guids


Does that fix it/?

**Comment by zackmuc** [comment]
this was just a test had previeously the 2 commandlines from vs 2019 and the also did not appear

**Comment by zadjii-msft** [comment]
> also if i manualy add profiles with the setting "add new profile" the do not appear

FWIW, they won't appear until you actually _save_ the settings.

**Comment by zackmuc** [comment]
Thx got it to work

**Comment by zadjii-msft** [comment]
> How did you create Folders

Go check out: [New tab dropdown](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#new-tab-dropdown)
