### ISSUE TITLE
Feature Request - Support for Powerline fonts

### ISSUE THREAD

**Issue by Lyndeno** [microsoft/terminal#1615]
# Summary of the new feature/enhancement

When SSHing into an ubuntu server with oh-my-bash installed, set up with the powerline theme, some of the symbols and shapes do not render properly, while they render fine if using the regular cmd.exe

**Comment by Jaykul** [comment]
Just switch your font to one that has powerline characters. They shipped with Consolas or something by default -- try using Fira Code, or one of the (NerdFonts)[/ryanoasis/nerd-fonts]

**Comment by DHowett-MSFT** [comment]
This is just #633 .
