### ISSUE TITLE
Bash-like shortcut keys

### ISSUE THREAD

**Issue by jimmycanosa** [microsoft/terminal#16157]
Does Microsoft Terminal team hate shortcut keys?

Can you copy the standard shortcut keys from bash?

I like ms terminal but this is a huge deal.

Shortcuts:

Action

Bash Navigation

Ctrl + A

Move to the start of the command line

Ctrl + E

Move to the end of the command line

Ctrl + F

Move one character forward

Ctrl + B

Move one character backward

Bash Control/Process

Ctrl + L

Similar to clear command, clears the terminal screen

Ctrl + S

Stops command output to the screen

Ctrl + Z

Suspends current command execution and moves it to the background

Ctrl + Q

Resumes suspended command

Ctrl + C

Sends SIGI signal and kills currently executing command

Ctrl + D

Closes the current terminal

Bash History

Ctrl + R

Incremental reverse search of bash history

Alt + P

Non-incremental reverse search of bash history

Ctrl + J

Ends history search at current command

Ctrl + P / Up arrow

Moves to previous command

Ctrl + N / Down arrow

Bash Editing

Ctrl + U

Deletes before the cursor until the start of the command

Ctrl + K

Deletes after the cursor until the end of the command

Ctrl + W

Removes the command/argument before the cursor

Ctrl + D

Removes the character under the cursor

Ctrl + H

Removes character before the cursor

Alt + D

Removes from the character until the end of the word

Moves to next command

Ctrl + S

Gets the next most recent command

Ctrl + O

Runs and re-enters the command found via Ctrl + S and Ctrl + R

Ctrl + G

Exits history search mode

And many more... 

Life will be so much easier and faster.

**Comment by zadjii-msft** [comment]
These are all things that are literally provided by the shell itself, not something the Terminal itself controls. I believe [PsReadline allows you to change the keys to whatever you'd like](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler?view=powershell-7.3). `cmd.exe` on the other hand, [is not actively maintained](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#cmd). If you want a modern, updated shell on Windows, you should try out [PowerShell 7](https://github.com/PowerShell/PowerShell).
