### ISSUE TITLE
Arrow up after restarting terminal

### ISSUE THREAD

**Issue by CrazyWolf13** [microsoft/terminal#16156]
### Windows Terminal version

1.18.2822.0

### Windows build number

version 22H2 (Build 22621.2283)

### Steps to reproduce

Enter some commands
 For examaple: 
- dir 
- winget install curl
- mkdir test
the restart windows terminal
arrow up

### Expected Behavior

The terminal should recall the last commands, mkdir test, winget install curl and dir .... however just nothing happens when I hit arrow up. On linux this works great

### Actual Behavior

The last commands were not recalled from the buffer.

**Comment by zadjii-msft** [comment]
This is a feature of the shell (`cmd.exe`), not the terminal (Windows Terminal). For example, PowerShell (`powershell.exe`, `pwsh.exe`) _does_ support cross-session history. Most modern shells do, but alas, CMD does not. As much as I'd love that, [we won't be updating `cmd.exe` anytime soon](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#cmd). If you want a modern, updated shell on Windows, you should try out [PowerShell 7](https://github.com/PowerShell/PowerShell).

Previous discussion in #10064 et al.

**Comment by CrazyWolf13** [comment]
> This is a feature of the shell (`cmd.exe`), not the terminal (Windows Terminal). For example, PowerShell (`powershell.exe`, `pwsh.exe`) _does_ support cross-session history. Most modern shells do, but alas, CMD does not. As much as I'd love that, [we won't be updating `cmd.exe` anytime soon](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#cmd). If you want a modern, updated shell on Windows, you should try out [PowerShell 7](https://github.com/PowerShell/PowerShell).
> 
> Previous discussion in #10064 et al.

Thanks for the explanation, this is really sad. I'd love to use powershell however cmd seems way more similar to linux terminal where powershell is more like a different thing, or can powershell be used with all the same functions including running batch instead of cmd?

**Comment by zadjii-msft** [comment]
Sure can:
![image](https://github.com/microsoft/terminal/assets/18356694/15f34945-cb8b-46ab-87fd-e0cf58971b54)

I definitely feel you - I'm a cmd user myself. Though I've been learning a bit more pwsh over the years, and lemme tell ya, when you start getting into more complicated scripts, I've definitely come to prefer powershell. Plumbing objects around takes a little getting used to, but it's way nicer than trying to do anything complicated in batch scripts.

**Comment by CrazyWolf13** [comment]
> Sure can: ![image](https://user-images.githubusercontent.com/18356694/274625858-15f34945-cb8b-46ab-87fd-e0cf58971b54.png)
> 
> I definitely feel you - I'm a cmd user myself. Though I've been learning a bit more pwsh over the years, and lemme tell ya, when you start getting into more complicated scripts, I've definitely come to prefer powershell. Plumbing objects around takes a little getting used to, but it's way nicer than trying to do anything complicated in batch scripts.

Thanks for your understanding, this recent microsoft goes linux and microsoft goes open-source heavily changed my image of this company in a good way.

Back to cmd, yeah I always used it and as I love linux cmd is just way more convenient to use than powershell, the syntax is just a bit different between linux and cmd where powershell is like a new level which I don't really like.

However in complex scripts I see powershell interest becoming bigger.

I've also noticed a lot of cmd problems including ANSI characters and color support....

Maybe I really have to think about switching, however I think for this step powershell would have to be made more compatibel with cmd for example allowing batch file and supporting all of cmd syntax

**Comment by NewtonChutney** [comment]
> Back to cmd, yeah I always used it and as I love linux cmd is just way more convenient to use than powershell, the syntax is just a bit different between linux and cmd where powershell is like a new level which I don't really like.

imo, powershell's aliases make it able to use bash cmds directly..
![image](https://github.com/microsoft/terminal/assets/70827815/9d0a7e10-4b06-4dde-8304-d572a287eefa)

The only place i feel it lacking is in the autocomplete system that I got soooo used to in zsh.. ψ(._. )>

**Comment by CrazyWolf13** [comment]
> > Back to cmd, yeah I always used it and as I love linux cmd is just way more convenient to use than powershell, the syntax is just a bit different between linux and cmd where powershell is like a new level which I don't really like.
> 
> imo, powershell's aliases make it able to use bash cmds directly and hence makes me feel pwsh is closer to bash than cmd
> ![image](https://github.com/microsoft/terminal/assets/70827815/9d0a7e10-4b06-4dde-8304-d572a287eefa)
> 
> The only place i feel it lacking is in the autocomplete system that I got soooo used to in zsh.. ψ(._. )>

I found clink which solves all my problems and with doskey command and auto inject command on startup from clink i have everything, a better visual cmd, auto complete, working history and so, have s look at it! It has soo many features!

https://github.com/chrisant996/clink

**Comment by NewtonChutney** [comment]
Yes I came across clink, when setting up starship prompt for zsh and pwsh..
Have you tried it?
starship.rs

**Comment by CrazyWolf13** [comment]
> Yes I came across clink, when setting up starship prompt for zsh and pwsh..
> Have you tried it?
> starship.rs

Starship and pwsh look also very definitely have to look a them.
