### ISSUE TITLE
Git Bash bold in One Half Light runs text together

### ISSUE THREAD

**Issue by garretwilson** [microsoft/terminal#16168]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

git version 2.42.0.windows.2

### Steps to reproduce

I'm using Git Bash with the "One Half Light" color scheme. I want to show something in bold, like this:

```bash
echo "Uploading $(tput bold)some-really-long-filename.zip$(tput sgr0) to the server ..."
```

At first the bold didn't show up any differently than the regular text. Then I went to "Text Formatting" and changed "Intense text style" to "Bold font". Now bold shows up. But often it runs the text together.

### Expected Behavior

I wanted bold text, without running the text together. Here is how it looks (as expected) in the terminal of VS Code.

![vs-code-bold](https://github.com/microsoft/terminal/assets/627125/5712ad73-f9c8-449c-aee3-1692236db3e3)

### Actual Behavior

Microsoft Terminal jams some of the words together. Note the space after `….zip` completely disappeared.

![microsoft-termina-bold](https://github.com/microsoft/terminal/assets/627125/05312e36-d0fe-4e1a-b2b1-ed4400190e28)

The point of using bold was to make certain things stand out, but this bug defeats the purpose by jumbling things together.

The output of Maven, for example, is a bit garbled, because many of the goal identifiers are shoved over, "eating" the space of the words after them.

This only seems to happen of the run of bold text is sufficiently long.

My guess off the top of my head is that the bold algorithm is calculating the space taken up based upon the non-bold text, and not taking into account that the bold text is wider. Over a few characters this per-letter error accumulates. Just a hunch.

Maybe you could just add an option to use the VS Code terminal renderer in Microsoft Terminal?

**Comment by garretwilson** [comment]
Unfortunately rendering bold as "Bright colors" (the default" doesn't seem to make any difference at all, looks like I'll have to abandon Microsoft Terminal and use VS Code termainl for almost everything. I guess if I need two directories open I can just add more terminal tabs in VS Code.

**Comment by zadjii-msft** [comment]
I _think_ this was fixed in 1.18 or 1.19 - Can you double check in [Terminal Preview](https://aka.ms/terminal-preview)/?

**Comment by garretwilson** [comment]
> I _think_ this was fixed in 1.18 or 1.19

Good news! Thanks for letting me know.

> Can you double check in [Terminal Preview](https://aka.ms/terminal-preview)/?

Unfortunately I just don't have the time at the moment, but I'll be happy to check and report back once those versions are released and my installation gets upgraded.

**Comment by zadjii-msft** [comment]
Good news! You can actually just immediatly install the update by downloading the `.msixbundle` from our releases page:
* Preview https://github.com/microsoft/terminal/releases/tag/v1.19.2831.0
* Stable https://github.com/microsoft/terminal/releases/tag/v1.18.2822.0

**Comment by garretwilson** [comment]
> I think this was fixed in 1.18 or 1.19

It's not fixed in v1.18.2822.0 at least.

**Comment by zadjii-msft** [comment]
Ah shoot - can you check again and make sure that the new text renderer is enabled? I forgot that it's disabled by default in the Stable builds (but is enabled by default in preview)

![image](https://github.com/microsoft/terminal/assets/18356694/49a165e6-9105-418d-af77-172a3c174e0c)

**Comment by garretwilson** [comment]
Woohoo! 🎉 That was it! I needed to turn on "Use the new text renderer".

Very nice to see a bug getting fixed. Thanks!

**Comment by DHowett** [comment]
Amazing, thanks for confirming! That new engine will eventually be made the default - we're currently collecting reliability (and bug fix!) data on it. Let us know if you find anything weird!
