### ISSUE TITLE
Feature Request - commandline in json should support paths

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#1617]
# Summary of the new feature/enhancement

currently profiles.json does not support paths for commandline

supported:
"commandline" : "pwsh.exe",
"commandline" : "cmd.exe",

not supported:
"commandline" : "C:\Program Files\PowerShell\6-preview\pwsh.exe",

This scenario expects the following:
the *.exe is available through system env path $env:path
the *.exe name is unique

# Proposed technical implementation details (optional)

please support absolute or relative paths / paths with environment variables like %appdata% or $env:appdata (don't know if this PoSh variable can be used outside PoSh) so better rely on legacy OS variables.

**Comment by DHowett-MSFT** [comment]
"does not support"

did you try it?

**Comment by Shorotshishir** [comment]
Probably Escaping Character Escaped your mind for a bit. 
`"C:\\Program Files\\PowerShell\\6-preview\\pwsh.exe"`
