### ISSUE TITLE
Last executed command pinned whenever your terminal window is using split panes

### ISSUE THREAD

**Issue by ItsNotMyFault** [microsoft/terminal#16178]
# Description of the new feature/enhancement
Add a "pinned message" in the top of a split terminal. 

I run multiple developments projects at the same time and I'm often forgetting which split terminal is for which project.
I often have my terminal window split in 4 to rapidly access the "npm watchers" of each of my projects. However sometimes I forget which split pane is for which project and it's annoying.
I would  like to know the last executed command in the terminal and from which directory this command has been executed from.
A pinned message in the top of the split pane would do very nicely.

# Proposed technical implementation details (optional)

Whenever I run a command in a split terminal' I would like for the last command to be pinned in the top of this specific split terminal.

**Comment by zadjii-msft** [comment]
FWIW, I think this is a great idea. We're actually already tracking this over at /dup #14754, though that one's hard to find. I thought I'd find it linked to #13445, I was wrong.

There's also similarly #4717 and #4800, for "pane titlebars" (similar, but also different).

**Comment by ItsNotMyFault** [comment]
Perfect, thanks!
