### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by aballway** [microsoft/terminal#1618]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18865.1000]
Windows Terminal version (if applicable): 0.2.1715.0
Default app for .json filetypes: gvim.exe
```

# Steps to reproduce

Click down-arrow **v** next to new tab button **+** and click **Settings** button.
Alternatively, while Terminal is in focus, press _Ctrl + ,_
# Expected behavior

Settings tab/window appears

# Actual behavior

Nothing. During one attempt I was able to get it to crash but that may be an unrelated issue because I'm unable to reproduce it.

**Comment by DHowett-MSFT** [comment]
Please make sure you (1) search for existing issues (this is probably #1460) and (2) fill out the title, otherwise we get a bunch of e-mails that just say "bug report!"
