### ISSUE TITLE
Windows Terminal as default terminal doesn't play well with existing windows

### ISSUE THREAD

**Issue by bracco23** [microsoft/terminal#16189]
### Windows Terminal version

1.18.2681.0

### Windows build number

 10.0.19045.3448

### Other Software

none

### Steps to reproduce

- open a new terminal window
- set "new instance behaviour" to "attach to the most recently used window"
- Set Windows terminal as default terminal
- create a bat on the desktop with just the pause command
- double click on the bat file

### Expected Behavior

a new tab in the opened window is created, and the tab behaves as a normal tab

### Actual Behavior

A new terminal window is created instead of using the existing one and it is not possible to drag tabs between the two Windows or between any windows spawned off the two (they basically seem to create two completely unrelated window groups.)

It might be included in the scope of #14900, but opening a new issue as it seems there is more to it that just the tab behaviour.

**Comment by PankajBhojwani** [comment]
Thank you for reporting this!

Just want to clarify - neither of the terminal windows in the repro steps you listed are elevated right?

**Comment by zadjii-msft** [comment]
(this may also be #15509, but I haven't been able to repro it, and neither can Dustin anymore)

**Comment by bracco23** [comment]
Neither the bat nor the standalone terminal is run elevated, at least not intentionally.

yeah #15509 sounds might be related.

**Comment by carlos-zamora** [comment]
Thanks again for filing! We're going to mark this as a /dup of #15509.

That said, we could definitely use some extra info to help debug this. Mind following [this guide](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capturing-a-debug-etl-trace) to get a trace and share it over in #15509? Thanks
