### ISSUE TITLE
Terminal doesen't show a clause cursor of Microsoft IME

### ISSUE THREAD

**Issue by dogatana** [microsoft/terminal#16180]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3570

### Other Software

Microsoft IME

### Steps to reproduce

1. invoke Microsoft IME
2. enter ro-maji that will be translated to Kanji.
3. IME show some clauses

## Expected Behavior

After step three 

- We can change the taget clause to the left or the right.
- We can enlarge or shorten the target clause

with shortcut keys.

## Bare Command Prompt

In the attached movie, the target clause's background color is blue.
You can see its move and the change of its size.

https://github.com/microsoft/terminal/assets/12756480/cc9b131f-6e21-4ada-8307-3ee7e1dd294f

## Terminal

There is no visual feed back, so we cannot see which part is the target clause.
It's very hard to use.

https://github.com/microsoft/terminal/assets/12756480/06ef369b-0b2c-45d8-9bca-68029ba60b92

**Comment by lhecker** [comment]
I expect this to be fixed if we replace the Windows Terminal IME with the TSF implementation from conhost.

**Comment by lhecker** [comment]
We just published a major update to our IME implementation in the nightly Canary branch. It was rewritten from the ground up and has tons of improvements! If you're interested in trying it out, you can get it here: https://aka.ms/terminal-canary-installer
If you already have the Canary build installed, you can use this link to force an update.

If you encounter any issues or have any suggestions, or if you simply like/dislike the changes, please let us know! Thank you for bearing with us. 😊
