### ISSUE TITLE
A setting to hide Terminal from Explorer window list

### ISSUE THREAD

**Issue by fishchev** [microsoft/terminal#16181]
### Description of the new feature/enhancement

A setting to disable Terminal from appearing in Explorer window management features (even if Terminal window exists at the moment) - Alt+Tab, Task bar, maybe Win+Tab as well

E.g. Summon a Terminal, focus some other window (Terminal stays on screen).  If you do a single alt-tab now, then it would switch back to Terminal - I have a global shortcut to summon/focus you, don't clutter and shuffle around my alt-tab index, _pretty please_

cmder/ConEmu can be set up that way (Task bar - Don't show ConEmu window on Taskbar + enabled always on top), I would love to have same experience.

**Comment by zadjii-msft** [comment]
Okay, so this is even stronger than [`minimizeToNotificationArea`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/interaction#minimize-to-notification-area). That only hides the windows from the taskbar/alt-tab when it is minimized. This would be something like that, but _always_. 

I _feel_ like we've heard this request before and rejected it... but I absolutely can't find the thread now. Something about messing with standard Windows UI paradigms or something. I dunno, maybe that was brash.

**Comment by fishchev** [comment]
> Something about messing with standard Windows UI paradigms

Programmatically there seems to be no messing - quickly looked at ConEmu and it seems that all it does is passes WS_EX_TOOLWINDOW flag during window creation to Windows API
https://github.com/Maximus5/ConEmu/blob/master/src/ConEmu/ConEmuApp.cpp#L646

> The window is intended to be used as a floating toolbar. A tool window has a title bar that is shorter than a normal title bar, and the window title is drawn using a smaller font. A tool window does not appear in the taskbar or in the dialog that appears when the user presses ALT+TAB. If a tool window has a system menu, its icon is not displayed on the title bar. However, you can display the system menu by right-clicking or by typing ALT+SPACE.

https://learn.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

If you mean paradigms as in some UX standard, then I think it's more or less fine, as it wouldn't be the default behavior (also it would be totally reasonable for that new setting to force [`minimizeToNotificationArea`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/interaction#minimize-to-notification-area) to be enabled).

**Comment by PankajBhojwani** [comment]
Thank you for submitting this feature request! 

We have talked about this as a team and this is not something we're inclined to include in the application itself - it seems like something that would fit better in a third party application (like PowerToys).

There might be third party window management tools that will allow you to customize your windows like this, if you want to look into that!
