### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [microsoft/terminal#16195]
# Description of the new feature/enhancement

I would like to propose the addition of a dark mode feature to our application. Currently, our application only supports a light mode interface. Adding a dark mode would provide users with an alternative color scheme that is easier on the eyes in low-light environments and can help reduce eye strain.

Users would be able to toggle between light mode and dark mode in the application settings. This feature would enhance the user experience, making our application more accessible and visually comfortable for a wider range of users.

# Proposed technical implementation details (optional)

The implementation of dark mode can be achieved through the following steps:

1. **User Settings**: Add an option in the user settings that allows users to switch between light mode and dark mode.

2. **Stylesheets**: Create a separate stylesheet for dark mode styles, including background colors, text colors, and other visual elements.

3. **Toggle Button**: Include a toggle button or switch in the application's user interface to allow users to switch between light and dark modes.

4. **Media Queries**: Use CSS media queries to detect the user's preference and load the appropriate stylesheet.

5. **Testing**: Thoroughly test the dark mode across various devices and browsers to ensure a consistent and user-friendly experience.

This enhancement would greatly improve the accessibility and usability of our application for users who prefer dark mode or have specific visual needs.

**Comment by j4james** [comment]
In case it's not obvious, this is a bot. It's kind of interesting when you look at their profile activity. There are like 20 or so issues across different repositories all with the same title. Sometimes no content in the issue, but sometimes with unrelated text like the example above. And when the issue is closed, the bot actually replies, arguing for it to be reopened. It's definitely a step up from the usual bots we see.

**Comment by bphd** [comment]
> In case it's not obvious, this is a bot. It's kind of interesting when you look at their profile activity. There are like 20 or so issues across different repositories all with the same title. Sometimes no content in the issue, but sometimes with unrelated text like the example above. And when the issue is closed, the bot actually replies, arguing for it to be reopened. It's definitely a step up from the usual bots we see.

I'm not a bot, you can't affirm such thing without proofs. I've created some issues to see which terminal support that function or is willing to work on it. If you check further then when you have wanted to, you'll see multitude of other activities. There is content on the issue only when it's mandatory to have some. But when it's not needed, the title suffice. It's not a step up from bots, it's a human. Bots would have same behaviour. Describing my behaviour don't suffice to transform me into a bot. Btw you're a bot, you're automatically following my posts, replying literally the same thing, definitively a step down from the usual bots we see

**Comment by bphd** [comment]
> Oh it's obvious alright. I've definitely read enough LLM output to know it when I see it.
> 
> * The title doesn't match the description at all.
> * The description literally doesn't apply to us at all
> * The terminal is already in dark mode by default.
> 
> ![image](https://user-images.githubusercontent.com/18356694/276580610-b050aea9-0c38-48f9-a68e-b3692abffb54.png) That's a pretty long history of spam right there friendo.

It's not because you read some LLM text that is was put by a bot. I think for now (without any statistics) that most AI users are human for now. So they generate and use LLM text while not being a bot

And the description is just some gibberish placeholder because description was mandatory, the issue is mainly about "Split terminal view in two-page layout". So Your 3 remarks has nothing to see with actual issue

It's not a "long story of spam". It's request on some terminal to develop that function or redirect to one

**Comment by zadjii-msft** [comment]
Buddy, if you're a human, please try harder. The description is mandatory, because issues should have helpful descriptions. Titles are not good enough. If a human can't be bothered to write it, then why should I be bothered to read it?

Also, split panes have been a feature of the Terminal since literally the first Terminal release.

**Comment by bphd** [comment]
> Buddy, if you're a human, please try harder. The description is mandatory, because issues should have helpful descriptions. Titles are not good enough. If a human can't be bothered to write it, then why should I be bothered to read it?
> 
> Also, split panes have been a feature of the Terminal since literally the first Terminal release.

I don't ask you to read the description, i put it because it was mandatory, it's really about the title

It's not about splitting to have two terminal. It's about having the view of one, on two pane, to have the same scrollback

**Comment by zadjii-msft** [comment]
> It's about having the view of one, on two pane, to have the same scrollback

See now, how could anyone, in literally any of the terminal repos you spammed, have _ever_ known that, _without a description_

**Comment by bphd** [comment]
> > It's about having the view of one, on two pane, to have the same scrollback
> 
> See now, how could anyone, in literally any of the terminal repos you spammed, have _ever_ known that, _without a description_

I don't know what people doesn't understand about my request unless it's told. For me it's clear. I'm okay about being not understood, thats why I reply to questions to be more precise. But I can't know what to explain if I don't know what's not understood

**Comment by j4james** [comment]
Here are some examples of the feature as you've proposed it in different places:

* I would like to request an enhanced search feature for our document management system. 
* I would like to propose the addition of a real-time collaboration feature in our project management tool.
* I would like to request the implementation of server folders or groups.
* I would like to propose the addition of a dark mode feature to our application.

This is apparently all the same feature request. If you are a real human, you still deserve to be banned for spamming nonsense like this.

**Comment by zadjii-msft** [comment]
For what it's worth, this request is already tracked in #2601. Next time, please just provide a real description of what you want. Like, two sentences. A tweet's worth of text was enough to describe what you really wanted. But spamming 50 other repos with the same request (and random garbage descriptions) is always gonna get you marked as spam pal.
