### ISSUE TITLE
Font variant ignored by copyFormatting

### ISSUE THREAD

**Issue by champignoom** [microsoft/terminal#16191]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Add `copyFormatting: "html"` to config,
open a markdown document in neovim, type `*asdf* **asdf** <u>asfd</u>`
![image](https://github.com/microsoft/terminal/assets/66909116/a0deae88-9e5c-4d0f-a756-1bd077cdf3db)
Then copy it to MS word.

### Expected Behavior

Italic, bold and underline should be preserved.

### Actual Behavior

The variants are ignored.

![image](https://github.com/microsoft/terminal/assets/66909116/a9aa545c-0b6b-4604-aed5-489f3380b332)

**Comment by zadjii-msft** [comment]
That probably makes sense. I think GenHTML predates our support for bold and italic. Good find!

Just about here is where we'd need to fix this:
https://github.com/microsoft/terminal/blob/174585740759f3e473c5a4efe3207a20d2c78511/src/buffer/out/textBuffer.cpp#L2124-L2141

That'll need to account for other `TextAttribute`s too, beyond just color.

**Comment by tusharsnx** [comment]
This issue should be repurposed to say "Use all TextAttribute properties during a copy"


> Italic, bold and underline should be preserved.

I tried this for underlines atleast, and already has something that works. Two problems though:
- Couldn't find clients that actually would use those css underline properties, so they're anyway getting ignored.
- Doesn't make sense to do it only for underlines. All TextAttributes should be read and copied.
