### ISSUE TITLE
Malformed condrv request on SetConsoleNumberOfCommands call

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#16198]
### Windows Terminal version

current main branch

### Windows build number

10.0.19045.3516

### Steps to reproduce

Openconsole.exe receives malformed request from condrv during dispatching Win32 API `SetConsoleNumberOfCommandsA/W` call. The length of the exe name is always equals 6 (bytes). It is independent of the exe name string specified in the SetConsoleNumberOfCommands call. Even if the exe name consists of one character.

Repro:
- Build WT in debug configuration.
- Run WT with any cmd profile.
- Attach openconsole.exe process to visual studio debugger and set breakpoint at `src\server\ApiDispatchers.cpp:1529`:
  https://github.com/microsoft/terminal/blob/08f30330d15e22adf23ee04164fc2474f290348a/src/server/ApiDispatchers.cpp#L1520-L1541
- Run the following C++20 code inside wt to trigger the breakpoint on SetConsoleNumberOfCommands call:
```c++
#include <iostream>
#include <windows.h>

using namespace std::literals;

int main()
{
	auto exe_a = "program_name.exe"s;
	auto exe_w = L"program_name.exe"s;
	using SetConsoleNumberOfCommandsA_ptr = std::decay<decltype(::SetConsoleNumberOfCommandsA)>::type;
	using SetConsoleNumberOfCommandsW_ptr = std::decay<decltype(::SetConsoleNumberOfCommandsW)>::type;
	auto kernel32_dll = ::LoadLibraryExA("kernel32.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
	auto NtSetConsoleNumberOfCommandsA = reinterpret_cast<SetConsoleNumberOfCommandsA_ptr>(::GetProcAddress(kernel32_dll, "SetConsoleNumberOfCommandsA"));
	auto NtSetConsoleNumberOfCommandsW = reinterpret_cast<SetConsoleNumberOfCommandsW_ptr>(::GetProcAddress(kernel32_dll, "SetConsoleNumberOfCommandsW"));
	auto rc_a = NtSetConsoleNumberOfCommandsA(10, exe_a.data());
	auto rc_w = NtSetConsoleNumberOfCommandsW(10, exe_w.data());
	std::cout << "rc_a="<< rc_a << " rc_w="<< rc_w << "\n";
}
```

### Expected Behavior

`ULONG cbExeNameLength` equals the exe name length in bytes.

### Actual Behavior

`ULONG cbExeNameLength` always equals 6.

**Comment by o-sdn-o** [comment]
The problem is not in the WT/openconsole source code, the problem is in the unknown condrv code.

**Comment by o-sdn-o** [comment]
Since this was fixed in Win11, this is no longer an issue at all. 😉

**Comment by o-sdn-o** [comment]
I confirm, this works fine on Win11.

**Comment by DHowett** [comment]
_Ugh,_ I remember this one. The issue was actually over in conclnt (static lib in kernelbase).

Here's the commit message:

> Merged PR 4435591: Fix two bugs with DOSKEY
> 
> The first issue is in the console host: when we erase a command history,
> we also clear its allocated flag. It's supposed to remain allocated
> but become "reset". When we later check that a command history that
> exists in the list is allocated, we fail loudly because allocated has
> been cleared.
> 
> The second is that in Windows Server 2003, we rewrote the console client
> APIs (in kernelbase!) regarding command history and changed one internal
> function from taking char** to taking char*. Since the signature was
> actually void** and that changed to void*, the compiler didn't notice
> when in only one single place we continued to pass a char** instead of a
> char*. This caused us to send the wrong filename length for the ExeName
> in SetConsoleNumberOfCommands.
> 
> Fixes MSFT-25265854

Aaaand here's the diff.

```diff
     InputBuffer.Buffer = ExeName;
-    InputBuffer.Size = GetExeName(&ExeName, Unicode);
+    InputBuffer.Size = GetExeName(ExeName, Unicode);
     if (InputBuffer.Size == 0) {
         SET_LAST_ERROR(ERROR_INVALID_PARAMETER);
```

The fix went out in Insider build `19611.1000.rs_prerelease.200415-1433`... and using my decoder ring I learn that this means it only shipped in Windows 11+ :smile:

**Comment by alexolog** [comment]
Will this be fixed for Win10?

**Comment by DHowett** [comment]
> Will this be fixed for Win10?

No.
