### ISSUE TITLE
Windows Terminal crashing when invoking a Console request from .NET

### ISSUE THREAD

**Issue by thetestgame** [microsoft/terminal#16204]
### Windows Terminal version

1.18.2310.9002

### Windows build number

10.0.22621.0

### Other Software

Eco (EcoServer.exe)

### Steps to reproduce

Run the application without Administrator privileges.

### Expected Behavior

It launches as expected.

### Actual Behavior

Windows Terminal crashes resulting in a closed pipe error within .NET

![image](https://github.com/microsoft/terminal/assets/2001527/020021ad-c214-4b44-96d0-0885bd5aaa88)

This also seems to happen with the legacy applications such as cmd.exe. The issue is not consistent. However, once it starts it does not go away. We have had a few users report uninstalling Windows update KB5030649 resolves their issues.

Attempting to investigate inside the Event Viewer turns up this error

```
Faulting application name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade

Faulting module name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade

Exception code: 0xc0000094

Fault offset: 0x0000000000002be2

Faulting process id: 0x0xBA2C

Faulting application start time: 0x0x1DA03867118B628

Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe

Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe

Report Id: 28615991-e11f-4142-acc6-7fcfde642147

Faulting package full name: Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe

Faulting package-relative application ID: App
```

**Comment by zadjii-msft** [comment]
Alas, that Report Id didn't show up on the backend. We might need a Feedback Hub dump or a post-mortem dump to definitively ID this. Can you try following [these steps](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically) to get us a dump/?

I'm guessing this is MSFT:44310564 which is #16199, but we don't really have a repro for that, just crash dumps.

**Comment by thetestgame** [comment]
> Alas, that Report Id didn't show up on the backend. We might need a Feedback Hub dump or a post-mortem dump to definitively ID this. Can you try following [these steps](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically) to get us a dump/?
> 
> I'm guessing this is [MSFT:44310564](https://task.ms/44310564) which is #16199, but we don't really have a repro for that, just crash dumps.

Here is the crash dump. Far as reproduction steps I wish I could be of more use. Our product is fairly sizable and the fact where it crashes vs. where Windows terminal crashes are not correlated doesn't help nailing it down. Doesn't seem to even be the same spot consistently.

What I can potentially offer and though I'd need to double check with my boss first. The game in question that is being plagued by this does offer what we call DevTier for modders which grants full source access here on Github. If its of use we can probably arrange access for the purposes of figuring this out. While its not every time, EcoServer seems to hit this issue consistently enough that is its a genuine problem.

**Comment by thetestgame** [comment]
> Alas, that Report Id didn't show up on the backend. We might need a Feedback Hub dump or a post-mortem dump to definitively ID this. Can you try following [these steps](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically) to get us a dump/?
> 
> I'm guessing this is [MSFT:44310564](https://task.ms/44310564) which is #16199, but we don't really have a repro for that, just crash dumps.

I've sent an email with the crash dump per the instructions. Far as reproduction unfortunately where EcoServer crashes vs when Windows Terminal crashes are not related so trying to pinpoint it is rather difficult. Only known constant is it doesn't fail in the same spot every time and running as Administrator seems to sometimes help.

What I can potentially offer though I'd need to check with my boss is giving someone on the team what we call DevTier. DevTier is normally for modders but it grants full source code access to the game on Github. While EcoServer doesn't get the issue every time, its consistent enough that its a genuine problem. If that is of interest let me know and I'll see what I can do.
