### ISSUE TITLE
Terminal lets itself get killed by Application Hang

### ISSUE THREAD

**Issue by binki** [microsoft/terminal#16216]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.2283

### Steps to reproduce

1. Have a Terminal open.
2. Access the system using Remote Desktop set to a different DPI so that things have to be rescaled upon connection.
3. Perhaps open many tabs with lots of history and run other programs to generate memory pressure and activity so that connecting to RDP takes a minute or two before the system is usable.
4. Leave the system running for a long time, letting it do power management things, such as over a weekend multiple times.

### Expected Behavior

Terminal to continue running, just like conhost would. Terminal should be immune to these subjective assumptions made by Windows about whether or not an application is responding when the system is simply under heavy load preventing the application from being able to be responsive. It seems like, by being a “modern” app, it opts into being auto-killed by Windows when it is “(Not Responding)” instead of being allowed to wait for whatever resource it is blocking on and allowed to continue living like conhost is.

Defaulting this as the default Terminal app in Windows and hiding conhost behind “Privacy & security / For developers” in Settings means that you intend for this to actually be as functional and reliable as conhost.

### Actual Behavior

All of my terminal instances were closed. It wasn’t even just one window or one tab; all unrelated Terminal windows were closed. I found these two entries in the Windows Event Log:

```
The program WindowsTerminal.exe version 1.17.2305.26001 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
```

```
Fault bucket 1632722192260213151, type 5
Event Name: MoAppHang
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.17.2305.26001
P4: 647122fe
P5: 0c21
P6: 2097152
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4363df2c-207e-4d28-af70-83dcbcda18b8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.49f2f45e-fef0-42a0-b2e2-5aaca38a5543.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c699f788-3e65-42f0-a497-a6b08c47c9ba.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f2f23b51-70a2-4425-a983-e999de1bb0c4.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Microsoft.Window_e72fc5e2ce25cf44cbc7da3e5ca2de47855cbe94_4fbd145a_921c5293-1263-484c-854d-4e9e567fb43f

Analysis symbol: 
Rechecking for solution: 0
Report Id: c659d0b0-b332-4256-bc27-18bd8d87ef84
Report Status: 268435456
Hashed bucket: 33e0e3ff5ea1cdbc26a8982eee91299f
Cab Guid: 0
```

This is a similar issue to #3915 in terms of the potential for work lost, state lost, and frustration caused. Personally, I am fine with Windows automatically rebooting for updates. But when I access the system and I can tell it didn’t reboot, I expect all of my applications to still be there. When all of my Terminal windows are mysteriously gone, that is just weird. There wasn’t a reboot, so it didn’t *need* to be killed. This is purely just a waste of time because a subjective test based on system performance determined that the application should be autokilled (I presume—unless if it is actually hung—but since it is autokilled I have no chance to tell if that is the case).

**Comment by binki** [comment]
Does store actually cause Application Hang? That seems weird.

**Comment by binki** [comment]
But it is true that now Terminal reports its version as 1.18.2822.0 whereas the crash is from 1.17.11461.0.

**Comment by zadjii-msft** [comment]
Yep, then this is definitely /dup #3915. Only in the latest Windows 11 builds (literally, the most recent release) did the Store add the ability to opt-out of that behavior.

Thanks!
