### ISSUE TITLE
[Feature] Option to Move/Remove the 'Close Tab' icon/btn.

### ISSUE THREAD

**Issue by nawlbergs** [microsoft/terminal#16218]
# Description of the new feature/enhancement
I find that I am often accidentally closing my terminal tabs.
This issue is worsened by the fact that I will often rename my tabs by the command that was run... eg:  `dcu`.  which is very short... and makes the click area to switch to the tab extremely small...

Option to either: 
 - remove the Close icon from all the tabs ( you can still right click etc)
 - move the Close to a different location (maybe floating top/right of actual terminal area)
 - make a min-width for tabs (might help issue)

# Proposed technical implementation details (optional)
Less accidental closing of tabs.

**Comment by zadjii-msft** [comment]
> remove the Close icon from all the tabs ( you can still right click etc)

You can totally do that today! You can already [hide the close button on the tabs](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#show-close-button) in the theme settings. Something like:

```jsonc
{
    "name": "Dark (no close button)",
    "tab": 
    {
        "background": "terminalBackground",
        "showCloseButton": "never",
        "unfocusedBackground": "#00000000"
    },
    "tabRow": 
    {
        "background": null,
        "unfocusedBackground": "#333333FF"
    },
    "window": 
    {
        "applicationTheme": "dark",
        "useMica": false
    }
}
```

---

> make a min-width for tabs (might help issue)

Well, there is already [`"tabWidthMode": "equal"`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#tab-width-mode) which does give them a min width. 

---

There's also ["read-only mode"](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#mark-a-pane-as-read-only). Then, of course, there's #6549

I think that about covers this problem space?

**Comment by nawlbergs** [comment]
great... no idea how to implement that.

**Comment by nawlbergs** [comment]
blah i figured it out.. thanks

**Comment by 4wk-** [comment]
See more detail for complete howTo: https://github.com/microsoft/terminal/issues/6549#issuecomment-2012931368
