### ISSUE TITLE
Terminal Hung and Crashed

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16215]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2428

### Steps to reproduce

Download and open this file: https://1drv.ms/u/s!Aqq-Je19xlrfhR-DZMD3v-q0uqvx?e=gdWnI5
Trust me it is safe. 

### Expected Behavior

It should load the file.

### Actual Behavior

It hung and crashed.

**Comment by zadjii-msft** [comment]
> Trust me it is safe.

That's gonna be a nah from me dawg. Got a better way of repro'ing the issue than having me download a file off your onedrive?

Also, the Feedback Hub can actually record dumps for us: /feedback

Lastly, there's always the following the steps in https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically to get a post-mortem dump, then send us that to look at. Take your pick!

**Comment by elsaco** [comment]
@skanda890 this is the content of the file `Print+.py` you posted on OneDrive:

```
print ("Hello, World")

o=9
i=9
p=98
p+i+o


```

and running it won't crash the terminal:

```
PS G:\Temp\onedrive> cat .\Print+.py
print ("Hello, World")

o=9
i=9
p=98
p+i+o

PS G:\Temp\onedrive> python .\Print+.py
Hello, World
PS G:\Temp\onedrive> python .\Print+.py
Hello, World
PS G:\Temp\onedrive> python .\Print+.py
Hello, World
```

Is this the file that hangs your terminal, or something is missing:

![print+py](https://github.com/microsoft/terminal/assets/3933920/35811da1-c580-4a68-b0d2-de63a72de9b0)

**Comment by zadjii-msft** [comment]
* That feedback points at `4edb0d16-d70b-43ec-9be0-cecf58752fa5`
* points to `g:6896174828363099`
* crashes:
  * MSFT:44758668 - looks like the same as the below:
  * MSFT:46783328 - APPLICATION_HANG_HungThreadIsIdle_cfffffff_WindowsTerminal.exe!WindowThread::_messagePump. This is usually the "the store killed us for an update"


Neither of those are what I'd expect here. 

When you're "opening this file" - are you just double clicking it, or running it from the command-line?

**Comment by skanda890** [comment]
You will need to have 7 more applications open. Or if that doesn't hang and crash the terminal. I have a computer, it is very very old. So that may be the reason why the terminal hanging and crashing. Probably because it doesn't have much resources.

**Comment by carlos-zamora** [comment]
Could you capture a dump of Windows Terminal while it's hung using Task Manager? This'll give us a bit more information than what generally gets uploaded.

**Comment by skanda890** [comment]
This only happened when I had 'Python' installed.

**Comment by zadjii-msft** [comment]
Okay - again, could you [grab a dump](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-with-task-manager) while it's hung/? That'll let us actually see the stack that it's hung at to further diagnose this.

**Comment by skanda890** [comment]
Now it doesn't crash somehow.

**Comment by skanda890** [comment]
Is it because it was downloaded from another provider?
