### ISSUE TITLE
Buggy title bar appears in focus mode after long uptime

### ISSUE THREAD

**Issue by PennRobotics** [microsoft/terminal#16221]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.19045.3570

### Steps to reproduce

1. Set up focus mode as the default for all sessions.
2. Run Windows a reasonably long time without restarting
3. Open a new terminal
4. Sometimes (even now, not always) a title bar will appear

### Expected Behavior

No title bar in focus mode

### Actual Behavior

Title bar appears in focus mode&mdash;sporadically and after a long system uptime and resource usage.

The window cannot be dragged using the title bar, but the buttons (min/max/close) still function as expected. There are no tabs or text in the title bar. 

Currently, I'm at 3:23:14:42 uptime after waking, _vmmem_ was at 5.5 GB. (After the first crash, it is at 3.8 GB.) If I run a handful of wasteful tasks to run up resource usage (e.g. multiple ripgreps in Win command prompt and WSL at the same time) I can exceed 6 GB usage but this doesn't cause the title bar to appear in newly opened terminal processes.

This seems to be a problem independent of profile and other processes. I can run `wt cmd` and a title bar is there, then `wt ubuntu` and it's there, then `wt powershell` and it's no longer there, even though the other terminal processes are still open.

Restarting Windows will restore the expected behavior: no title bar

(update: unrelated to PID stored in a 16-bit variable; problem exists while all PIDs are under 23000)

**Comment by zadjii-msft** [comment]
The settings thing is definitely separate bug from the focus mode ones. I'll try and narrow this thread down to just the focus mode ones.

I bet it's a pretty similar root cause though. Some sort of leftover state from the refrigeration/reheat.

**Comment by sim590** [comment]
I think that this happened after build 1.17.11461.0 and before 1.18.2681.0. I did try the following packages:

|State|Package|
|-|-|
|good| Microsoft.WindowsTerminal_1.17.11461.0_8wekyb3d8bbwe.msixbundle|
|bad| Microsoft.WindowsTerminal_1.18.2681.0_8wekyb3d8bbwe.msixbundle|

I can reproduce this issue by simply opening a couple of instances of the terminal repeatedly. At some point, I get this bugged title bar:
![image](https://github.com/microsoft/terminal/assets/4147254/7988e4d5-7fe0-4e6d-b9a3-163b12ee2eef)
It took me 4-5 tries here.

But on 1.17.11461.0, it never does that.

I would like to note also that I found a that version 1.18.2681.0 was significantly slower on startup compared to 1.17.11461.0 for some reason.

**Comment by zadjii-msft** [comment]
That would track with my refrigeration assumption. That was introduced in #15424

**Comment by exic** [comment]
FWIW, I'm experiencing this randomly with a uptime of <6,5 hours. I was trying to reproduce it with PowerShell and a clean settings.json, but couldn't get it. With WSL profile I have it every day and can reproduce more easily by opening a few instances. Windows 10 as well.
Any workarounds? Can I disable the refrigeration feature?
![image](https://github.com/microsoft/terminal/assets/242107/fff8426b-e806-4ad0-a263-fc8dfa14a87d)
