### ISSUE TITLE
Lost new line character when using ReadFile

### ISSUE THREAD

**Issue by confusedsushi** [microsoft/terminal#16223]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.2361

### Other Software

The problem was first noted in some other console application which is using ``ReadFile`` to read from the console. The problem was stripped down to a minimal program

````cpp
#include <assert.h>
#include <windows.h>

int __cdecl main() {
  char buf[2];
  DWORD read;

  ReadFile(GetStdHandle(STD_INPUT_HANDLE), buf, 2, &read, NULL);
  assert(read == 2);
  assert(buf[0] == '\r');
  assert(buf[1] == '\n');

  ReadFile(GetStdHandle(STD_INPUT_HANDLE), buf, 1, &read, NULL);
  assert(read == 1);
  assert(buf[0] == '\r');

  ReadFile(GetStdHandle(STD_INPUT_HANDLE), buf, 1, &read, NULL);
  assert(read == 1);
  assert(buf[0] == '\n');
}
````

It seems the unexpected behavior first occurred with https://github.com/microsoft/terminal/pull/14745.

### Steps to reproduce

Compile the program using your favorite C compiler and run it. Hit ``<ENTER>`` until the example exits.

### Expected Behavior

In the good case you have to hit ``<ENTER>`` twice and the program exits gracefully.

### Actual Behavior

 In the bad case you have to hit ``<ENTER>`` three times and the last assert fires an error.

**Comment by codesculpture** [comment]
Hey, is this being landed in release ? If yes, in which version

**Comment by DHowett** [comment]
This is staged for the next 1.18 servicing release! Sorry for the delay.

**Comment by Uvaistd24** [comment]
***@***.***
