### ISSUE TITLE
Terminal opens new windows which can not be closed

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/terminal#16234]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19044.0

### Other Software

nothing special I suppose
I have some custom script that run on logon, which might explain why there are more terminals opening. 

### Steps to reproduce

1. Open Terminal
2. Lock Windows
3. Unlock Windows
==> One Empty Terminal Window with no content

### Expected Behavior

Terminal does not open more windows (or if it is actually my script that opens the terminals it should display them like any other window)

### Actual Behavior

Each Lock/Unlock Cycle one (or more) Terminal windows are spawned. 
The new Terminal window is not closable via the close button, but have to be terminated via Task Manager. 
(or I just found another way: one has to open a new tab and then it can be closed like any other window) 

![image](https://github.com/microsoft/terminal/assets/13590797/a2312dc1-c9c7-4dcd-9acb-8e42f29d7960)

**Comment by zadjii-msft** [comment]
This is kinda like #15936... you know what this is most definitely close enough to that. 

/dup #15936

Thanks!

**Comment by DanielHabenicht** [comment]
Yes, that pretty close. 
Now I know why I was not finding it with my search keywords.
