### ISSUE TITLE
"exit" terminal doesn't respond for a while

### ISSUE THREAD

**Issue by zrebec** [microsoft/terminal#1623]
# Environment

Microsoft Windows [Version 10.0.18362.207]

# Steps to reproduce

type "exit" for close terminal (with one tab opened)

# Expected behavior

Close the terminal quickly (like when you're closing the tab)

# Actual behavior

Terminal doesn't respond for a while (second or two) with just window borders displayed and then exits.

**Comment by JushBJJ** [comment]
To me thats normal, but I'm sure it will be improved in the future.

**Comment by DHowett-MSFT** [comment]
#1380
