### ISSUE TITLE
Keyboard shortcut to open the terminal

### ISSUE THREAD

**Issue by aeiplatform** [microsoft/terminal#16239]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2506

### Steps to reproduce

I haven't found any workable solution for launching the terminal using a keyboard shortcut. (Ctrl + Alt + T).

I even tried to create an alias for `"C:\Users\XXX\AppData\Local\Microsoft\WindowsApps\wt.exe"` which can be assigned to the representative.

But this assignment does not work only if the presets are reopened and an assignment is attempted again.
Changing the assignment causes the key bindings box to be cleared and openning Terminal.

### Expected Behavior

Some option for keyboard shortcut assignment.

### Actual Behavior

There is none.

**Comment by zadjii-msft** [comment]
I suspect you're looking for some combination of #9996, #7374 and #13630. 

In 1.18, we added the ability to run the terminal in "headless mode", which allows `globalSummon` actions to continue working when you've closed all the Terminal windows. This of course does require that the Terminal is running already. The combo of those threads will add other means to start the terminal headless, so the keybindings will work automatically. 

/dup #9996 #7374 #13630
