### ISSUE TITLE
Ghost keystrokes being sent to terminal?

### ISSUE THREAD

**Issue by nathanieltagg** [microsoft/terminal#16248]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.3570

### Other Software

WSL2

### Steps to reproduce

Unknown

### Actual Behavior

Symptoms are that my window keeps scrolling to the end of the view, and when I try to drag-select text, the selection box keeps disappearing.  This appeared to be similar to #8047, so I tried the instructions listed there.   I can see repeated keystrokes appearing 
\[179;34;0;1;31;1_
but I have no idea what the symbol table for this is; I'm not a windows programmer.

![image](https://github.com/microsoft/terminal/assets/2135685/1efceea0-eeae-4303-9fd0-281877a7bba4)

This just started happening today; I've made no system changes or upgraded anything.  Any idea what is going on?

**Comment by lhecker** [comment]
The first digit in these `␛[blabla_` sequences is the virtual key code in decimal. You can find a list here: https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
179 is B3 which is the "Play/Pause Media key".

Is your play/pause key stuck on your keyboard? Or do you happen to use some software that might generate it constantly?

**Comment by nathanieltagg** [comment]
I found it.  Apparently these codes were being generated by my Sony WH-CH510 headphones over bluetooth, which explains why it went away for a short time after reboot.  Shutting down the headphones fixed the problem.

Leaving this here as google fodder to help the next person.

Thank you for your help.
