### ISSUE TITLE
Add the ability to customize the sound played for the terminal bell.

### ISSUE THREAD

**Issue by polygonnedpotato** [microsoft/terminal#16240]
Currently, the sound that plays when the terminal rings it's bell is the same default sound that Windows is configured to use. All the customization that can done for the bell is change whether it also flashes the window and the icon, or to turn off the sound. The ability to use a custom sound for the terminal bell can make it seem more unique, and all people to set the sound to an actual bell.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This is actually already possible, but it needs to be configured via the _settings.json_ file. There is a [`bellSound`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#bell-sound) property at the profile level which you can set to the path of the audio file that you want to use.

Issue #12103 is tracking the addition of this property to the settings UI.

**Comment by zadjii-msft** [comment]
Yep, that's all right!

/dup #8366
