### ISSUE TITLE
Use acrylic material in the tab row not working

### ISSUE THREAD

**Issue by yusuf-saydullayev** [microsoft/terminal#16256]
### Windows Terminal version

v1.18.2822.0

### Steps to reproduce

I have enabled use acrylic material in the tab row.
But not working

![image](https://github.com/microsoft/terminal/assets/59925798/d6af10c8-48be-4693-bfa0-1a8ee448e731)

### Actual Behavior

Tab row is black

**Comment by yusuf-saydullayev** [comment]
Ohh, I knew why is not working. I need to turn on windows transparency effects. 
Anyway I'm not close this issue. Acrylic material in the tab row should work without windows system transsparency transparency effect.

**Comment by yusuf-saydullayev** [comment]
Please fix it

**Comment by zadjii-msft** [comment]
Alas, there's nothing we can do if transparency effects are disabled. Acrylic is a system component, and it's ultimately controlled by that setting. We'd have to entirely re-implement acrylic in a way that intentionally ignored a user setting, to work around that. That's not something we're going to do.

**Comment by sajibcd34pro** [comment]
I had enabled Windows transparency effects too. but still, didn't see any change in the Tab row.
