### ISSUE TITLE
Windows Terminal hangs when typing.

### ISSUE THREAD

**Issue by xkww3n** [microsoft/terminal#16255]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.25987.1000

### Steps to reproduce

1. Open Windows Terminal with any profile (Command Prompt and Powershell 7 tested).
2. Type some text.

### Expected Behavior

It should respond my input.

### Actual Behavior

It hangs when typing.

**Comment by lhecker** [comment]
Unfortunately we'll need a ETW recording to debug this. To do so, follow these steps:
* Quit all irrelevant application, including applications that run minimized in the taskbar (like Slack, Discord, etc.)
* Download, extract and run `UIforETW.exe`: https://github.com/google/UIforETW/releases
  It's preconfigured to record your inputs, which will allow us to correlate them with any input lags
* Click "Start Tracing" in the top left
* Reproduce the issue
* Click "Save Trace Buffers"
* Share the trace file with us - my mail is `<my GitHub username>@microsoft.com`

**Comment by xkww3n** [comment]
Unfortunately I can't reproduce this issue now. It just worked after some hours.

**Comment by DHowett** [comment]
That's quite strange! Thanks for following up.
