### ISSUE TITLE
Terminal opens behind other windows

### ISSUE THREAD

**Issue by csdivad** [microsoft/terminal#16260]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2428
10.0.22631.2506

### Steps to reproduce

1. Launch Terminal.
2. Minimize it to the taskbar at least once. This is the key step.
3. Have some random windows open. You can even bring back the Terminal to focus.
4. Launch a second Terminal instance.

### Expected Behavior

The second Terminal window should appear in front of all other windows.

### Actual Behavior

It opens behind all other windows and the taskbar icon blinks.

**Comment by wreiske** [comment]
This is incredibly annoying on windows 11 since there is no way to ungroup taskbar items (or at least there wasn't, I haven't researched lately)... I feel like recently something has changed with how this works.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #15479.
