### ISSUE TITLE
Wrong Character of multiple-line paste in Linux server visited from Windows Terminal

### ISSUE THREAD

**Issue by huangwb8** [microsoft/terminal#16262]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19041.572

### Other Software

 Ubuntu 18.04.3 LTS (GNU/Linux 5.4.0-050400-generic x86_64)

### Steps to reproduce

1. Connect to the Ubuntu server via ssh from Windows Terminal. like:
```
ssh -i  -p 22 root@192.168.1.xxx
```
2. Paste a code like:
```
ws=/home/Test/abcde
nbin=$ws/bin
export PATH=$ws/bin:$PATH
cd $ws
```

### Expected Behavior

The code is just shown what it is.

### Actual Behavior

Like: 

![WindowsTerminal_OwVpO983m6](https://github.com/microsoft/terminal/assets/35643122/b76cf1ea-7ba2-4a7d-aaf4-676a7adfc496)

There are some strange errors. 

Other try:

1. This error would not appear in the local PowerShell.
2. This error would be a little bit different from Linux servers connected.
3. This error never happen if I use shell tools like MobaXterm or FinalShell.

**Comment by lhecker** [comment]
What happens if run this and then paste?
```sh
set enable-bracketed-paste on
```
What happens if you do this instead?
```sh
set enable-bracketed-paste off
```

**Comment by huangwb8** [comment]
@lhecker 

`set enable-bracketed-paste on`: 

![WindowsTerminal_nSsvaOWU13](https://github.com/microsoft/terminal/assets/35643122/7b5d0cdd-1e07-4af4-8118-c291522acde6)

`set enable-bracketed-paste off`:

![WindowsTerminal_2ebrPhbBBf](https://github.com/microsoft/terminal/assets/35643122/0b41e01f-27f6-4f37-9730-783781fa82cd)

There're some differences, but the problem still exists.

**Comment by carlos-zamora** [comment]
Hi @huangwb8. Can you capture a debug tap for us following this guide? Thank you!
https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#enabling-the-debug-tap

**Comment by carlos-zamora** [comment]
Also, does it repro if you run `ssh -t user@machine zsh -f`?

**Comment by huangwb8** [comment]
> Hi @huangwb8. Can you capture a debug tap for us following this guide? Thank you! https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#enabling-the-debug-tap

The debug tap could only be opened in local terminal:

![image](https://github.com/microsoft/terminal/assets/35643122/5ffe31fb-f59f-41dc-aaf0-e58910e47653)

![WindowsTerminal_ase4VVucH7](https://github.com/microsoft/terminal/assets/35643122/8677b04a-3f2a-46aa-9e23-7bbee01d7b02)

======

> Also, does it repro if you run `ssh -t user@machine zsh -f`?

It seems the right direction to solve the problem:

![WindowsTerminal_6mJjNyIhOB](https://github.com/microsoft/terminal/assets/35643122/f635b9ff-7f80-45ab-b186-ea1d63174d17)

I want to keep zsh in the Ubuntu sever connected. Is it possible?

**Comment by DHowett** [comment]
Thanks for testing that out! It looks like there is something in your `zsh` configuration (`.zshrc` or `oh-my-zsh`, depending on how you have configured it) that is causing this. It does not look like a Terminal issue.

I recommend you check your `prompt_command`, `precmd`, or any other "command" hooks you have enabled.


> I want to keep zsh in the Ubuntu sever connected. Is it possible?

I am sorry, I do not know how we can help you.
