### ISSUE TITLE
Terminal renders gaps in between some lines

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#1626]
# Environment
Windows 10 19H1

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable):

Any other software?
[ZtreeWin](http://www.ztree.com/html/ztreewin.htm)
```

# Steps to reproduce
1 - Install [ZtreeWin](http://www.ztree.com/html/ztreewin.htm), or PowerShell PowerTab
2 - Make Terminal Window large
3 - Execute ztw or [TAB] in PowerShell with PowerTab enabled

# Expected behavior

<img width="437" alt="PowerTab Good" src="https://user-images.githubusercontent.com/2091582/60294002-3f5c9980-98d5-11e9-9463-502baed71a5a.PNG">

<img width="607" alt="ZtwOLD" src="https://user-images.githubusercontent.com/2091582/60141398-2388b480-976a-11e9-8c5d-71e4fde9d7a5.png">

# Actual behavior

<img width="487" alt="PowerTab Bad" src="https://user-images.githubusercontent.com/2091582/60294013-44b9e400-98d5-11e9-9636-f62b2c2267c0.PNG">

<img width="891" alt="ZtwNEW" src="https://user-images.githubusercontent.com/2091582/60141401-27b4d200-976a-11e9-892b-cf53ecc0d84e.png">

There are multiple horizontal lines that should not be there.

**Comment by miniksa** [comment]
This is sort of like #404, but my psychic debugging says this is floating point measuring of lines going awry and it might be really smart to just wholesale move to GDI measuring like #1298 suggested.

**Comment by ocalvo** [comment]
I think there are 2 issues here, one that is dependent on DPI.

For example ZTW at 200 DPI shows like these:
<img width="823" alt="Ztw DPI200" src="https://user-images.githubusercontent.com/2091582/60309009-89a74000-9900-11e9-83a7-b6310cc51b48.PNG">
 - Notice the horizontal lines
 - Notice the vertical lines are not continuous

For ZTW at 100 DPI:
<img width="552" alt="Ztw DPI100" src="https://user-images.githubusercontent.com/2091582/60309026-aba0c280-9900-11e9-8692-7ec748afa212.PNG">
- Notice that the horizontal lines are fixed.
- But the vertical lines are still not continuous.

Baseline:
<img width="607" alt="ZtwOLD" src="https://user-images.githubusercontent.com/2091582/60309039-c5420a00-9900-11e9-97a2-d824aa0197a4.png">

**Comment by thomaslevesque** [comment]
I see the same thing with display scaling at 125% or 150%. Works fine at 100%.
Particularly annoying when using oh-my-posh, or anything that relies on fonts with Powerline glyphs

**Comment by wmcbrine** [comment]
Vertical gaps also sometimes occur. I am using 125% scaling.
