### ISSUE TITLE
Windows Terminal does not close when ran via Scheduled Tasks

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/terminal#16281]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Create a scheduled task that runs a `ps1` file with `pwsh.exe -f ....`

![image](https://github.com/microsoft/terminal/assets/2971735/bf22ad42-d5df-4d27-ad86-226f041ad0d3)

With a daily trigger like so

![image](https://github.com/microsoft/terminal/assets/2971735/b6245203-461c-49cb-8bf4-6976d63071c0)

### Expected Behavior

The script should run and after it is finished,  the Microsoft Terminal should be closed.

### Actual Behavior

Microsoft Terminal stays open. It has no active tab and the window is transparent. 

![image](https://github.com/microsoft/terminal/assets/2971735/ccfa4381-d03f-43f7-a95e-2b7210ecbd78)

It cannot be closed via the X. Instead, you must click the + to add any new tab and then you can close the terminal via the X.

The bug does not appear consistently, but very often.

**Comment by zadjii-msft** [comment]
I think this is more or less #15936. I'm betting your script spawns and exits real fast, SO fast that the Terminal doesn't even have the time to open a real tab for it. That thread has more details.

/dup #15936
