### ISSUE TITLE
Failed install without usable error message

### ISSUE THREAD

**Issue by cook-1229** [microsoft/terminal#16284]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.0

### Other Software

I currently have Terminal 1.15.2524.0 installed.  Versions after this have failed (can't promise that I tried all of them).

### Steps to reproduce

1. Download Microsoft.WindowsTerminal_1.18.2822.0_8wekyb3d8bbwe.msixbundle from GitHub.
2. Run installer.  Click "Update" button.

### Expected Behavior

Terminal installs, like previous versions.

OR

Terminal tells me exactly what is wrong.

### Actual Behavior

Installer reports, "App Installer failed to install package dependencies. Ask the developer for  package. "

What package?  Where would I look to find this information?  I couldn't find a log in the Event Viewer that told me.

**Comment by zadjii-msft** [comment]
I'd suspect (without investigating) that 1.16 was around the time we stopped shipping Microsoft.UI.Xaml directly in our package, and instead started relying more on the OS installing dependencies for us. I believe the store is supposed to be able to automatically pull down framework package dependencies. The PreinstallKit might have those dependencies still bundled inside it.

**Comment by zadjii-msft** [comment]
See also: 
* https://github.com/microsoft/terminal/issues/13558#issuecomment-1192184868
* https://github.com/microsoft/terminal/issues/15512#issuecomment-1577373361
* #13520, though, that Midi dependency should be long gone

**Comment by cook-1229** [comment]
Thanks for the quick reply, @zadjii-msft.
I installed Microsoft.UI.Xaml.2.8.x64.appx, and the Terminal installer worked without complaint.  I am working on a machine that cannot access the Microsoft Store, and I didn't even know that was the problem.

I would have been able to figure this out for myself if the error message had indicated that Xaml was the missing packing.  Note that there is a double space in "for  package."  I suspect that there is a bug in the installer that is preventing the name of the package from being displayed.

**Comment by zadjii-msft** [comment]
Well, glad you got that figured out! I think there were some enhancements to that installer in Windows 11 that made that a bit less of a problem, but alas, those fixes didn't make it downlevel.
