### ISSUE TITLE
Bug Report: winver 1903 acrylic not working

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#1628]
Acrylic does not work even though it's enabled and I'm on winver 1903, build 1836.175

**Comment by chrismetz** [comment]
I'm having the same problem on OS Build 18361.172 and WT Preview (v 0.2.1715.0)

Profile config
        {
            "acrylicOpacity" : 0.5,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "wsl.exe -d Debian",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 12,
            "guid" : "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
            "name" : "Debian",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : true
        }

**Comment by DHowett-MSFT** [comment]
Does _Calculator_ use Acrylic when you open it?

**Comment by musm** [comment]
No, doh, I have transparency disabled in appearance

**Comment by musm** [comment]
😝

**Comment by zunzun1** [comment]
I have a problem with transpatency in my Windows 10 1903. Here is screen from my settings.
<img width="1920" alt="Windows 10 1903 error" src="https://user-images.githubusercontent.com/23059826/62007216-0f5e1b80-b14b-11e9-8616-e5e34c8f1cb4.png">

**Comment by IvanBernatovic** [comment]
@chrismetz @zunzun1 You have to turn on trasnparency effects in Windows settings first (just type transparency effects in Start search). After you enable it you'll have transparency in Windows Terminal.
