### ISSUE TITLE
cannot move window to rightmost by dragging the top-left corner

### ISSUE THREAD

**Issue by baiwfg2** [microsoft/terminal#16296]
I open multiple terminal tabs, and the remaining size of the blank space gets smaller and smaller. See the green part. I know we can drag the blank space to move window further right, but not very further. Because when the mouse reach the rightmost point of the screen, the window will be stretched vertically.

So generally we can pull window further right by dragging the top-left corner, see the red part. But it cannot for the moment.

![image](https://github.com/microsoft/terminal/assets/5157680/b4df0fe5-2c43-4d74-8196-0a7ef1eb27fc)

Unlike the above window terminal, the pure linux GUI terminal has a big space on top to drag the window to left or right, even further.
![image](https://github.com/microsoft/terminal/assets/5157680/9bb4a36f-12f0-48ab-9cf5-b11f31e8e38e)

I search the history issue and found nothing similar to my problem. My version is: 1.17.11461.0

**Comment by baiwfg2** [comment]
Although we can use shortcut `Alt + space + M` to move to further right, but it's not natural. Can we do it with mouse dragging ?

**Comment by zadjii-msft** [comment]
More or less, we're tracking this in /dup #5493. Thanks!

FWIW: once you press <kbd>Alt+shift+m</kbd>, if you tap an arrow key, you should be able to them move the window with your mouse. Still not natural, but something.
