### ISSUE TITLE
Can't open in UNC directory with some special charactors

### ISSUE THREAD

**Issue by MerrickZ** [microsoft/terminal#16293]
### Windows Terminal version

1.18.2282.0

### Windows build number

10.0.23585.1001

### Steps to reproduce

Open a samba share, e.g. ```\\myshare\mydownload\[MV] BlackPink\```
Right click and select "Open Terminal Here"

### Expected Behavior

Should open a terminal window which path is at ```\\myshare\mydownload\[MV] BlackPink\```
just like "Open Powershell window here" menu item.

### Actual Behavior

Opens a new window but the path is ```PS C:\WINDOWS\System32\WindowsPowerShell\v1.0>```

**Comment by zadjii-msft** [comment]
I'm pretty sure this is a Windows Powershell (~v5) bug, that's solved in the latest versions (v7+). See also /dup #9476
