### ISSUE TITLE
The settings section in full screen has no option to close

### ISSUE THREAD

**Issue by berlintay** [microsoft/terminal#16308]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22635.0

### Steps to reproduce

- Press "Alt+Enter" to go into full screen.
- Press Ctrl+, To enter the settings tab.
- You will notice here is no option to leave the settings

Here is a screenschot 

![image](https://github.com/microsoft/terminal/assets/128968711/5aad45c1-8e99-43e2-afad-745d864c9afe)

### Expected Behavior

A button for Closing the settings window while in full screen.

### Actual Behavior

The settings is somewhat stuck , with no applicable options to exit the window.

**Comment by lhecker** [comment]
Couldn't you just press Alt+Enter again?
(BTW, just in case, Ctrl+Shift+W is the key bind to close any tab, including the settings tab.)

**Comment by zadjii-msft** [comment]
Yea I don't really see how this is different from "I fullscreen'd a terminal tab, and now there's no way to close that tab".

That being said, I'd guess that /dup #5677 would be a viable solution to this issue too.
