### ISSUE TITLE
Keyboard Shortcut to open terminal

### ISSUE THREAD

**Issue by DhananjayPorwal** [microsoft/terminal#16300]
# Description of the new feature/enhancement

"I would like to bring attention to a potential enhancement for the Windows Terminal app on Windows 11. Currently, Windows Terminal does not provide native support for creating keyboard shortcuts to open the terminal directly. While users can resort to alternative methods such as creating desktop shortcuts or using the Task Scheduler to achieve this, it would greatly improve user convenience and accessibility if the Windows Terminal application itself had a built-in feature to assign and manage custom keyboard shortcuts for launching the terminal. This enhancement would streamline the user experience, aligning with the user expectations and providing a more integrated and user-friendly approach to accessing the terminal on Windows 11. I believe this improvement would contribute to the overall usability of the Windows Terminal and enhance its functionality for users who prefer quick keyboard access to the terminal application."

# Proposed technical implementation details

1. **Shortcut Configuration UI:**
   - Introduce a new section in the Windows Terminal settings dedicated to keyboard shortcuts.
   - Within this section, provide a user-friendly interface allowing users to configure and customize keyboard shortcuts for opening the terminal.

2. **Configuration Storage:**
   - Implement a mechanism to store and manage user-defined keyboard shortcuts within the Windows Terminal's configuration settings.
   - Consider using a JSON or similar configuration file to store the key bindings and associated actions.

3. **Integration with Task Scheduler:**
   - Enhance the Windows Terminal application to dynamically register itself with the Task Scheduler during installation.
   - When a user defines a custom keyboard shortcut within the Windows Terminal settings, the application should register a corresponding task with the Task Scheduler.

4. **Task Execution:**
   - Ensure that the registered Task Scheduler tasks trigger the Windows Terminal application with the appropriate command-line arguments to launch the terminal window.

5. **Error Handling and Validation:**
   - Implement robust error handling mechanisms to address scenarios such as conflicting shortcuts or invalid configurations.
   - Provide informative error messages and log entries to assist users in resolving any configuration issues.

6. **User Feedback:**
   - Integrate user feedback mechanisms to collect information on the usage and effectiveness of the new keyboard shortcut feature.
   - Consider providing a feedback channel within the Windows Terminal application for users to report issues or suggest improvements related to this feature.

## Expected Benefits
The implementation of this feature would significantly enhance the usability of the Windows Terminal, providing users with a seamless and integrated method for configuring and utilizing custom keyboard shortcuts. This improvement aligns with user expectations for efficient and direct access to the terminal application on Windows 11.

**Comment by zadjii-msft** [comment]
This already exists for the Terminal. See the [`globalSummon` action](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands)
