### ISSUE TITLE
Please provide a way to run different tabs under different credentials

### ISSUE THREAD

**Issue by figueroadavid** [microsoft/terminal#1630]
# Summary of the new feature/enhancement

I need the ability to run different tabs under different credentials, and to create a "play list" of these tabs/credential combinations, so that I can open a series of tabs under those credentials.

Like many administrators/system engineers, I frequently have multiple cmd & powershell prompts open under different credentials and different security levels. 

# Proposed technical implementation details (optional)

**Comment by Jaykul** [comment]
Despite the security implications, I often do this in ConEmu, seems very useful.

**Comment by DHowett-MSFT** [comment]
#1032
