### ISSUE TITLE
Slidable Tabs

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16312]
Can you make tabs sliding like in Microsoft Edge.

**Comment by zadjii-msft** [comment]
You're gonna have to be more specific. Sliding in what way/?

**Comment by skanda890** [comment]
Imagine in Microsoft Edge, you have two tabs open you move one tab over another tab. What will happen that time? That is called Sliding Tabs. Do you get it now? Or not.

**Comment by zadjii-msft** [comment]
You can already reorder the tabs in the Terminal:

![a8b9d1f8-b1bf-4c81-b78b-b4d67f310d0c](https://github.com/microsoft/terminal/assets/18356694/96097455-07cf-4b05-9074-adac94a678d0)

That's been there since #3478 in v0.6

**Comment by skanda890** [comment]
Huh, I don't know how to screen-record can you tell me a software that allows the user to screen-record?

**Comment by skanda890** [comment]
For me, it doesn't work I will send the recording tomorrow. Now it is getting late.

**Comment by zadjii-msft** [comment]
If it's not working for you, I'm gonna guess that you're running the Terminal as Admin, where dragging & dropping tabs explicitly doesn't work. For more details, see #6661 and the many linked threads.
