### ISSUE TITLE
In Telnet there had been an error

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16311]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2506

### Other Software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce

Go to Terminal Windows Power Shell and type " curl gamin.gg "

### Expected Behavior

It should allow the user to access this page.

### Actual Behavior

A popup came and said " Will you allow a small file on your computer " or something like that. If I said Yes, then it said 

curl:

Please enable cookies.
Sorry, you have been blocked
You are unable to access gamin.gg

Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution.
There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray
ID found at the bottom of this page.

Cloudflare Ray ID: 825ce7282a4a4162 • Your IP: Click to reveal 171.76.81.149 •  Performance & security by Cloudflare
(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.rem
ove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var
a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();    window._cf_translation = {};
At line:1 char:1
+ curl gamin.gg
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand "

**Comment by lhecker** [comment]
I believe the error message is fairly clear. It tells you that your request got blocked. Also, just to be clear `curl` in PowerShell is an alias for `Invoke-WebRequest`. It's not the same as `curl.exe` which is not an alias and the actual curl executable that everyone knows.

Closing, as this is not a terminal issue.

**Comment by skanda890** [comment]
Then what kind of issue is this? Where should I report this then?

**Comment by skanda890** [comment]
Huh, I don't get it.

**Comment by lhecker** [comment]
Here's your response again - I've highlighted the relevant details for you:
> Please enable cookies.
> **Sorry, you have been blocked**
> You are unable to access gamin.gg
> 
> **Why have I been blocked?**
> This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution.
> There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
>
> **What can I do to resolve this?**
> **You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.**
> 
> Cloudflare Ray ID: 825ce7282a4a4162 • Your IP: Click to reveal 171.76.81.149 •  Performance & security by Cloudflare
> (function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.rem
> ove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var
> a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();    window._cf_translation = {};
> At line:1 char:1
> + curl gamin.gg
> + ~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand "

You have been blocked by Cloudflare. That's a Cloudflare issue, not a Windows Terminal issue.

**Comment by skanda890** [comment]
Oh, okay I understand now.
