### ISSUE TITLE
Make optional add-ons for Terminal

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16310]
Can you make optional add-ons for Terminal? Example: An add-on for Python or an add-on for any other programming language?

**Comment by zadjii-msft** [comment]
/dup #4000

Apps are already free to add their own profiles with fragment extensions. There's also some example profiles for various tools over at: https://github.com/microsoft/terminal/blob/main/doc/user-docs/ThirdPartyToolProfiles.md

**Comment by skanda890** [comment]
Re-open this issue. This is not a duplicate of #4000

**Comment by skanda890** [comment]
#4000 says to add support for 3rd party extensions. I want the add-ons through Windows optional features.

**Comment by skanda890** [comment]
Umm, I don't understand what you are talking. Can you simplify it?

**Comment by zadjii-msft** [comment]
* Windows Optional Features are features for Windows, made by Microsoft. 
* The Terminal is made by Microsoft[^1]. 
* If we wanted to add "Windows Optional Features" to the Terminal, we could just build them directly into the Terminal itself.

I think you've got to better explain your request here. Give us a concrete example. 

[^1]: and the community of course, but Microsoft ships it

**Comment by skanda890** [comment]
Okay, I understand.
