### ISSUE TITLE
Setting Canary as default terminal does not work

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#16316]
### Windows Terminal version

1.20.3171.0

### Windows build number

10.0.22621.2715

### Other Software

N/A

### Steps to reproduce

1. Set Windows Terminal Canary as default terminal.
2. Run any terminal application, for example: <kbd>Win</kbd>+<kbd>R</kbd>, then `cmd`.

Also working with `node`, `pwsh` etc.
VS actually opens `VsDebugConsole.exe`.

### Expected Behavior

Application opens under Windows Terminal Canary.

### Actual Behavior

Application opens on its own window, not under WT.

**Comment by DHowett** [comment]
Thanks!

**Comment by giggio** [comment]
Thanks @DHowett! Already updated today and it is working.
Love working with the canary build! :)
