### ISSUE TITLE
warning popup "Cascadia Mono font is not found" (unpackaged version)

### ISSUE THREAD

**Issue by g-chauvel** [microsoft/terminal#16322]
### Windows Terminal version

1.18.3181.0 (unpackaged 1.18.231114001)

### Windows build number

10.0.19045.0

### Steps to reproduce

It looks like the bug fix for "The regression where "Cascadia Mono" (or "... Code") would not be found on upgrade has been un-regressed (https://github.com/microsoft/terminal/pull/16196)" introduced a regression for the unpackaged version

Launch WindowsTerminal.exe from unpackaged version
- https://github.com/microsoft/terminal/releases/download/v1.18.3181.0/Microsoft.WindowsTerminal_1.18.3181.0_x64.zip
- https://github.com/microsoft/terminal/releases/download/v1.18.2822.0/Microsoft.WindowsTerminal_1.18.2822.0_x64.zip

### Expected Behavior

- no warning popup from WindowsTerminal.exe unpackaged version 1.18.3181.0 (unpackaged 1.18.231114001)
- no warning popup from WindowsTerminal.exe unpackaged version 1.18.2822.0 (unpackaged 1.18.231009002-preview)

### Actual Behavior

- a warning popup: "Cascadia Mono font is not found, Consolas is used instead" from WindowsTerminal.exe unpackaged version 1.18.3181.0 (unpackaged 1.18.231114001) is displayed 
- no warning popup from WindowsTerminal.exe unpackaged version 1.18.2822.0 (unpackaged 1.18.231009002-preview)

with the same default profile from C:\...\AppData\Local\Microsoft\Windows Terminal\settings.json settings
```json
{
    "altGrAliasing": true,
    "antialiasingMode": "grayscale",
    "closeOnExit": "automatic",
    "colorScheme": "Campbell",
    "commandline": "C:\\...\\PowerShell-7.3\\pwsh.exe",
    "cursorShape": "bar",
    "font":
    {
        "face": "Cascadia Mono",
        "size": 10.0
    },
    "guid": "....",
    "hidden": false,
    "historySize": 9001,
    "icon": "C:\\...\\PowerShell-7.3\\assets\\Square44x44Logo.png",
    "name": "Pwsh 7.3",
    "padding": "8, 8, 8, 8",
    "snapOnInput": true,
    "startingDirectory": "%USERPROFILE%",
    "useAcrylic": false
},

**Comment by zadjii-msft** [comment]
@lhecker did we somehow break this for unpackaged in #16196

**Comment by lhecker** [comment]
Yes. 🤦 You see, because DxEngine modifies the *only* copy of the chosen face name to do a variant search (i.e. "Arial Bold" -> "Arial", if the former doesn't exist). So by moving the nearby search after the variant search, I broke the lookup because now it searches for "Cascadia".

FYI the code for "AtlasEngine" works correctly. You can enable it in the "Rendering" settings and enable it, as it'll be the default in the near term anyways.

**Comment by g-chauvel** [comment]
> FYI the code for "AtlasEngine" works correctly. You can enable it in the "Rendering" settings and enable it, as it'll be the default in the near term anyways.

AtlasEngine enabled, no more warning popup

**Comment by 237dmitry** [comment]
The same problem if font installed in user's font directory. If font installed globally there is no issue.
