### ISSUE TITLE
Bug Report - Control panel button shows incorrectly

### ISSUE THREAD

**Issue by Chanakan5591** [microsoft/terminal#1632]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): Dev Build


```

# Steps to reproduce

just launch the application

# Expected behavior

It should be default control buttons.

# Actual behavior

The minimize and the Maximize button didn't show correctly it show like a small corrupted buttons.
(I don't know that is this an UI or a bug, and sorry for my English I'm Thai.)

**Comment by zhwghl** [comment]
@DHowett-MSFT has been working on it. Try build the branch dev>duhowett>minmaxcloseme

**Comment by Chanakan5591** [comment]
Thank you.
