### ISSUE TITLE
Feature Request - Improve micro-latency on CMD

### ISSUE THREAD

**Issue by compulim** [microsoft/terminal#1633]
# Summary of the new feature/enhancement

Without any load, running Command Prompt (cmd) under Windows Terminal, the micro-latency between the user press a key, and the character appears on Windows Terminal, is noticeable and slower than pure `cmd.exe`.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Probably part of #778

**Comment by DHowett-MSFT** [comment]
Without more performance traces we can't actually triage this.
