### ISSUE TITLE
Should references to markdown files point to the GitHub link or use relative paths?

### ISSUE THREAD

**Issue by chingucoding** [microsoft/terminal#16338]
Currently, README.md and other files point the GitHub.com link whenever referencing another markdown file that is part of this repository. Other repositories such as the WinUI repository have chosen to use relative links which would also allow browsing the files on your local machine without a browser opening. 

Would this be a welcome change to the documentation or should we keep things as is? 

If the former is the case, I would gladly contribute these changes.

**Comment by lhecker** [comment]
Yes, I believe that change would be fine.

**Comment by DHowett** [comment]
Relative would be great! Thank you for asking :smile:
