### ISSUE TITLE
Can't run PowerShell correctly from a path with square brackets

### ISSUE THREAD

**Issue by Fly252** [microsoft/terminal#16330]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.0

### Other Software

PSVersion: 5.1.22621.2506

### Steps to reproduce

1. Set Windows PowerShell as default profile of Windows Terminal
2. Run following command in PowerShell
```
wt -d 'D:\TEMP\[test]'
```
OR
1. Set Windows PowerShell as default profile
2. Go to the folder "D:\TEMP\\[test]" in Windows Explorer
3. Right click in Windows Explorer, and click "Open in Windows Terminal"

### Expected Behavior

Windows Terminal is launched and current working location is set to "D:\TEMP\\[test]"

### Actual Behavior

Current working location is set to "C:\WINDOWS\System32\WindowsPowerShell\v1.0"
![屏幕截图 2023-11-17 155805](https://github.com/microsoft/terminal/assets/62587815/67a0078f-376b-4e2e-aa2d-e8b8f36b7e56)

**Comment by zadjii-msft** [comment]
This is a known bug in Windows PowerShell 5.1. See https://github.com/microsoft/terminal/issues/11149#issuecomment-914397136. Sorry about that! I believe this is fixed in PowerShell 7+. 

/dup #11149
