### ISSUE TITLE
Terminal window "not responding"

### ISSUE THREAD

**Issue by cool-RR** [microsoft/terminal#16332]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.0

### Steps to reproduce

I'm using a terminal window, and then not using it for a while and doing other stuff.

### Actual Behavior

The terminal window becomes nonresponsive. The content is gone. The window title shows "not responding" and I can only kill the process at that point.

**Comment by zadjii-msft** [comment]
Does this happen consistently/? Or was this a on-off kinda thing? I'd guess that this is because we just pushed an update to the app on the Store, and the Store tried to kill the Terminal to install the update. 

If that's the case, the Terminal version should probably now be https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0

**Comment by cool-RR** [comment]
This happened at least 10 times in the last few weeks, but I can't make it happen at will. My version right now is 1.18.2822.0.

Is there any way to find logs or something on my machine that would give us information about what's happening?

**Comment by lhecker** [comment]
That sounds a bit like a deadlock, so log files probably won't be of help. You could try to capture a dump of a hung process before killing it: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capturing-and-sending-dumps

That way we can see what threads are currently stuck and what the UI thread is most likely waiting on.

**Comment by cool-RR** [comment]
Thank you, I'll give it a try.

**Comment by cool-RR** [comment]
Today this happened again. I opened Process Explorer and saw these processes:

![image](https://github.com/microsoft/terminal/assets/56778/c68eaf35-89b5-4bb9-ba48-3cae62489300)

I wasn't sure which process you wanted a dump of, and whether it should be a mini-dump or a full dump, so I just made both mini- and full dumps of each of the 4 processes. They're available for download here: https://www.dropbox.com/scl/fo/ngzixgtvl9b4gms1ya0bl/h?rlkey=00vm814nojext99o8agdwwzu3&dl=0

Does that help you figure out why it's hanging?

**Comment by cool-RR** [comment]
![i-know-some-of-these-words-mhmm](https://github.com/microsoft/terminal/assets/56778/ea5911b1-7431-4dad-b652-bf9a1a96dd90)

Thanks for the analysis. In that link were both mini-dumps and full dumps. Was the kernel-side stack trace missing also from the full dump?

**Comment by lhecker** [comment]
Yep! I'm unfortunately not experienced enough with dumps to know why that is and a quick ~Google~ Bing didn't bring any answers to that either...

**Comment by zadjii-msft** [comment]
I mean, maybe a dumb question is: are you changing the input language / method / something like that? 

If you send /feedback via the Feedback Hub, we might be able to see if there's something else crashing on your machine that's correlated here. That's a real long shot though.

**Comment by zadjii-msft** [comment]
We had a bit of a brain blast: Does this only occur after you've opened two simultaneous terminal windows, and closed one of them (but not both)? 

We suspect that this hang is due to the window refrigeration code in Terminal 1.18 that gets used on Windows 10. We're guessing the message gets sent to the closed, refrigerated window, which just doesn't pump it.

**Comment by cool-RR** [comment]
> Does this only occur after you've opened two simultaneous terminal windows, and closed one of them (but not both)?

I tried that now, it didn't make the problem happen. But I often have multiple terminal windows open, and I routinely open new ones and close existing ones.
