### ISSUE TITLE
Accept single word from auto-complete suggestion instead of whole line

### ISSUE THREAD

**Issue by Simran-B** [microsoft/terminal#16341]
# Description of the new feature/enhancement

I would like to be able to partially use auto-complete suggestions similar to what shells like fish offer.
Using <kbd>Alt</kbd>+<kbd>Right Arrow</kbd> or <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd>, I can add the next word to my input. The path separator character is considered a word boundary.

The command history with <kbd>F2</kbd> or (<kbd>Shift</kbd>+)<kbd>F8</kbd> is a better option if you used a command before, but if it's not in the list or you never entered it before, it would save time if you could use some of the auto-complete suggestions instead of typing everything or accepting the full suggestion and then having to delete several characters.

https://github.com/microsoft/terminal/assets/7819991/8a3111dc-8632-4db7-8d8f-1cdfec344f37

# Proposed technical implementation details (optional)

<kbd>Ctrl</kbd>+<kbd>Left/Right Arrow</kbd> can already be used to jump one word at a time, with the path separator being a word boundary. This feature could potentially be extended so that one word of the auto-complete suggestion is added to the input when the cursor is at the end of the current input and you hit the <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd> key combination instead of doing nothing.

**Comment by zadjii-msft** [comment]
I believe this is a request that would be better moved to the https://github.com/PowerShell/PsReadline repo. PsReadline is actually the module that provides the suggestion text in PowerShell, not the Terminal itself. 

I think they originally added this in https://github.com/PowerShell/PSReadLine/issues/687, that thread might have more details. 

Thanks!
