### ISSUE TITLE
Support for native CLI editor

### ISSUE THREAD

**Issue by plante-msft** [microsoft/terminal#16345]
# Description of idea

It would be helpful during everyday tasks to be able to view and edit files in Windows via CLI. Default support for `nano` for example. 

# Expected behavior

Using 'nano file.txt' opens up the file in the CLI for editing.
![image](https://github.com/microsoft/terminal/assets/150482134/de1dd5a4-6de8-4e49-80a1-f944726fe10e)

# Actual behavior

Error displayed.
![image](https://github.com/microsoft/terminal/assets/150482134/fe4a3217-abd1-448c-9832-90b0c58b7ab9)

**Comment by scanyard** [comment]
Just an outside observer here, but it looks to me like you just don't have `nano` installed on your system. It's on the `winget` package manager too, so if your Windows install is recent, you should be able to install from there. Left panel is Powershell in Terminal before installing, right panel is after.

<img width="1500" alt="Screenshot 2023-11-20 211134" src="https://github.com/microsoft/terminal/assets/122397995/79f0b880-05c6-4e75-b612-eac4a2c3b7af">

**Comment by plante-msft** [comment]
@scanyard @b-cpu apologies for the late response to these comments. I am trying to gauge community interest in having one or more CLI text editors installed inbox and immediately available to Windows users.  

Yes, nano is not a built-in command, but it does come installed by default on many distros - this is the behaviour I'm interested in gauging interest in for Windows. 

I have opened up a Feature Exploration issue, and will be closing this one as a duplicate of that issue. If you have more feedback, please comment on there! 

Closing as /dup #16438 .
