### ISSUE TITLE
Bug Report: clipboard bugs with some unicode characters or emoji

### ISSUE THREAD

**Issue by zhwghl** [microsoft/terminal#1634]
# Environment

```none
Windows build number:  10.0.18362.175
Windows Terminal version (if applicable): 04e808fd0a5e60821af02a6dcc284e816521abf9 [04e808f]
```

# Steps to reproduce
1. Using Windows File Explorer, create a file with filename "🀀🀁🀂🀃🀄🀅🀆🀇🀈🀉🀊🀋🀌🀍🀎🀏.docx" under a directory (e.g. D:\folder).
2. Launch Windows Terminal and run "cmd.exe" or "wsl.exe" command.
3. Change directory to the folder where the file you created locates, and type "dir" or "ll" command.
4. Check if the filename shows on the list correctly.  
5. Try to select and copy the filename from the Windows Terminal.
6. Paste the filename you copied in Notepad.exe and check if it is "🀀🀁🀂🀃🀄🀅🀆🀇🀈🀉🀊🀋🀌🀍🀎🀏.docx"

# Expected behavior
Expect to see the filename 🀀🀁🀂🀃🀄🀅🀆🀇🀈🀉🀊🀋🀌🀍🀎🀏.docx correctly displays itself with font 'Segoe UI Emoji' or 'Segoe UI Symbol' after type "dir" or "ll" command, and which should be able to be selected and copied correctly.

# Actual behavior
The filename will display as something like  🀀����������������docx.
You won't get 🀀🀁🀂🀃🀄🀅🀆🀇🀈🀉🀊🀋🀌🀍🀎🀏.docx in your clipboard after you try to copy it from the Windows Terminal.

Under a wsl.exe process in Windows Terminal, the app might crash when you try to select and copy it from the list given by the "ll" command.

**Comment by DHowett-MSFT** [comment]
@carlos-zamora we may have an issue copying these characters :smile:

**Comment by DHowett-MSFT** [comment]
I can't reproduce this any longer. Please let me know if it's still an issue.
