### ISSUE TITLE
Why can't the Windows Terminal tabs in elevated season drag and drop

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16342]
### The Question

Why can't the Windows Terminal tabs in elevated season drag and drop?

**Comment by zadjii-msft** [comment]
Thanks for the question! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+elevated+drag+drop) when filing new issues. This is already being tracked by another issue on our repo - please refer to #6661 for more discussion.

/dup #6661

**Comment by skanda890** [comment]
Can anybody label this as 'Issue-Question'?
