### ISSUE TITLE
Some character combinations render a "merged" character glyph when using fixed-width fonts

### ISSUE THREAD

**Issue by ccnly** [microsoft/terminal#16347]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.0

### Steps to reproduce

type `ping www.florida.gov` to see an example.

![2023-11-21_132421_UTC](https://github.com/microsoft/terminal/assets/53479999/d206cdab-ad01-4198-9628-20e5d1ca4bde)

### Expected Behavior

The `f` and `l` glyphs should remain in their respective columns.

### Actual Behavior

The `f` and `l` glyphs "merge" into a single glyph, adding additional padded space around them.  Each character does remain selectable.

**Comment by lhecker** [comment]
You're using a partially proportional font that contains ligatures for "fl", which is one of the most common ligatures: https://en.wikipedia.org/wiki/Ligature_(writing)#Stylistic_ligatures
You can continue using the same font if you disable ligatures. To do so, open your `settings.json` file using Ctrl+Shift+, and find your "font" settings. Then add a "liga" override like so:
```json
"font": {
    "face": "your font face",
    "features": {
        "liga": 0
    }
}
```
This will come with a slight performance cost, however (non-default font features require complex glyph shaping).

**Comment by USMA56795** [comment]
I'm using Cascadia Code, Aptos Mono, Consolas, and other fixed-width fonts.  I don't believe those are supposed to have ligatures such as this.  Am I incorrect?

**Comment by lhecker** [comment]
> I'm using Cascadia Code, Aptos Mono, Consolas, and other fixed-width fonts. I don't believe those are supposed to have ligatures such as this. Am I incorrect?

Cascadia Code does have ligatures for things like `==>`. Cascadia Mono is the one without such ligatures. Neither of the 3 fonts you mentioned however has a "fl" ligature, so I'm not sure what font it was that you used. I'm glad the setting worked for you though!

> I wonder if I should log an enhancement that the Appearance configuration should have a checkbox to allow/dis-allow ligatures.

Don't worry about it! It's been requested a number of times in the past and we recently opened a PR to address this 🙂: #16104
