### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by RJurjevic** [microsoft/terminal#16350]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.14393

### Steps to reproduce

Run WindowsTerminal.exe and it won't start.

### Expected Behavior

WindowsTerminal.exe should have started.

### Actual Behavior

WindowsTerminal.exe failed to start as it seems it did not find a function in a DLL. The error was "The procedure entry point SetThreadDescription could not be located in the dynamic link library."

**Comment by zadjii-msft** [comment]
Yep, it sure won't work on Server 2016!

The minimum required Windows version for the Terminal is 19041. See our [FAQ ](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#can-i-use-the-terminal-on-windows-7-windows-server-2019-any-other-down-level-windows-version)for more details.
