### ISSUE TITLE
These software always display the need for updates.

### ISSUE THREAD

**Issue by jerryc127** [microsoft/terminal#16353]
### Windows Terminal version

1.18.3181.0

### Windows build number

19045.3757

### Steps to reproduce

run `winget upgrade --all`

### Actual Behavior

I have already run `winget upgrade --all`  to update all my software, but every time I run it, these few still appear.
These software always display the need for updates.

Microsoft.VCRedist.2015+.x64
Microsoft.PowerShell
Microsoft.DotNet.DesktopRuntime.7

![image](https://github.com/microsoft/terminal/assets/16351105/d49c2bba-2198-4603-8132-43c6fa0e0b50)

**Comment by zadjii-msft** [comment]
This doesn't look like a Terminal problem - this looks like something to report on winget itself, over at https://github.com/microsoft/winget-cli. 

Thanks!
