### ISSUE TITLE
Crash on Exit (Reappeared)

### ISSUE THREAD

**Issue by StefPlue** [microsoft/terminal#1636]
Crash when quit WT with exit. 
Obviously not fixed with #457 or new crash reason.

# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable):  0.2.1715.0

Any other software? No
```

# Steps to reproduce

* Start Windows terminnal
* Enter "Exit" and <RETURN>

-> Crash.

# Expected behavior

No crash ;-)

# Actual behavior

**Comment by GamyGamer** [comment]
it looks like terminal crash when you are trying to close PowerShell (cmd works normally)

**Comment by DHowett-MSFT** [comment]
#1380
