### ISSUE TITLE
Developer Command Prompt for VS 2022 always starts in the wrong place

### ISSUE THREAD

**Issue by mikedice** [microsoft/terminal#16362]
### Windows Terminal version

1.18.2822.0

### Windows build number

 10.0.22631.2715

### Other Software

VS2022 Enterprise with latest updates installed. .Net Core profile

### Steps to reproduce

- Open Terminal
- in Terminal open new Developer Command Prompt for VS 2022

### Expected Behavior

I should be able to say where my command prompt starting directory is at. I would specify the root of my repos where all of my code is at

### Actual Behavior

The terminal starts in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'. This is totally useless because none of my code is in that directory so I always have to CD to the directory where my repos are at. If you look at the script C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\vsdevcmd\core\vsdevcmd_end.bat you see why this is happening. Terminal passes -startdir=none to the command and that causes all the logic in the vsdevcmd_end.bat file that lets users start in whatever directory they want to be skipped.

**Comment by mikedice** [comment]
For what it's worth this configuration gives me the behavior I want:
`            {
                "font": 
                {
                    "size": 16.0
                },
                "guid": "{90e266fb-84c9-445c-a7ff-0c367b8430d3}",
                "hidden": false,
                "name": "VS 2022 Command prompt",
                "commandline": "cmd /k \"set VSCMD_START_DIR=c:\\users\\mikedice\\source\\repos & \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\" -startdir=auto -arch=x64 -host_arch=x64\"",
            },`

**Comment by lhecker** [comment]
Actually, you can specify where the starting directory is! It's here in your profile settings:
![image](https://github.com/microsoft/terminal/assets/2256941/bde16b73-2313-44ca-8552-c0c0270fb1ba)

Let me know if that doesn't work for you! 🙂

**Comment by veeq7** [comment]
Hi, this issue still persists on the newest version. Seems like the command line loads before the project loads, so it fallbacks on the vs repos directory. After restart of the command line it works fine. Please fix, it wastes a lot of time.
