### ISSUE TITLE
Grouping, Tree Search menu, Sync  for profile [GUI]

### ISSUE THREAD

**Issue by locvnhub** [microsoft/terminal#16366]
# Description:
I currently work with many profiles,
So I suggest customizing the interface as follows to make searching faster

- Grouping
- Search by tree
- Sync profiles [gits, dropbox,onedrive .... ]
 
 
![WindowsTerminal_20231124-08-25-11_zJzUv2xGov](https://github.com/microsoft/terminal/assets/61675702/a6f1641c-86df-4a92-9184-2d9745e86348)

**Comment by j4james** [comment]
Grouping profiles was covered by issue #1571 (see also #15721), and has already been implemented. You should be able to create custom menu layout following the documentation here: [New tab dropdown](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#new-tab-dropdown).

Synchronization of profiles is covered by #2933 (see also #3893), but isn't supported yet.

I'm not aware of an existing issue for searching the menu tree though.

**Comment by zadjii-msft** [comment]
Yea, j4james has this mostly covered. 

As far as searching goes, I'd honestly just use the Command Palette for that. <kbd>Ctrl+Shift+P</kbd>, `nt.`, <kbd>enter</kbd> and you'll have a searchable list of all your profiles. Jumping straight to that menu with a keybinding is #10209

Thanks!

/dup #1571
