### ISSUE TITLE
File Explorer that responding to moved Windows Terminal tab

### ISSUE THREAD

**Issue by warquys** [microsoft/terminal#16365]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.0

### Steps to reproduce

1. Open Windows Terminal
2. Open Windows File Explorer
3. Try to add the Windows Terminal as an external Tab of the Explorer File
Like this:
![image](https://github.com/microsoft/terminal/assets/64769541/5bcdc4b5-1fc0-4ac5-a0da-c14bc0c4e650)

### Expected Behavior

File Explorer should ignore the Terminal:
The "+" of the File Explorer should not move and gives the illusion that the Terminal tab will be added to the File Explorer tab.

Or the File Explorerer sholld accept the Terminal as a new tab.
(What would be fun and usefull would be if tab of other applications could be added as tabs in other applications, What this bug portends)

### Actual Behavior

The "+" is moved giving the illusion that the tab will be added, but the tab is not added.

**Comment by zadjii-msft** [comment]
lol this is a good catch 🤣 

I've filed an internal bug on the XAML team (who's helping work on the File Explorer tabs) to get this fixed. That's tracked in MSFT:47906009. 

If there's any progress there, I can report it back here. Thanks!

**Comment by warquys** [comment]
I just noticed that this bug can also be reproduced with notepad. Notepad and the file explorer. @zadjii-msft
