### ISSUE TITLE
Option to prevent sleep if task is running

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/terminal#16376]
# Description of the new feature/enhancement

On my machine, I have set the sleep time to 15 minutes. Sometimes (eg. when running long builds) I would just step away from it and let it work, but then come back with it being on standby and with the work just paused, which is pretty annoying. It would be nice if Terminal had an option to make it automatically prevent the machine going to sleep if there's some operation running in any tabs. This is pretty common for other applications/websites as well (eg. if you have Spotify playing music in Edge, your computer won't go to sleep).

> [!NOTE]
> Tried searching for a similar issue and couldn't find one, so hopefully this is not a duplicate.

# Proposed technical implementation details

PowerToys is already doing this in their "awake" feature, we could probably just do the same here?
Ie. [`SetThreadExecutionState`](https://github.com/microsoft/PowerToys/blob/a090558aad7065b2cfb2892922048e74cb5f546d/src/modules/awake/Awake/Core/Manager.cs#L85)?

**Comment by zadjii-msft** [comment]
I... don't hate this. But knowing when to do this would be tricky. We wouldn't necessarily want to _always_ prevent sleep if the Terminal is running - we'd probably want to only do that if there's a child process running. That of course gets into weird edge cases - just running `ssh` from a shell (or heck, just cmd.exe from PowerShell) would then satisfy the heuristic here and would keep the PC alive. 


Terminal doesn't currently track the tree of processes. We'll need to do that for #6549 though

**Comment by Sergio0694** [comment]
To give a real world use case scenario, I hit this when building https://github.com/microsoft/CsWinRT locally, which takes like half an hour. Started `./build.cmd`, stepped away, came back after an hour and the PC had just gone to sleep after 10 minutes 🤦‍♂️

**Comment by DHowett** [comment]
This may be more suitable as a tool outside of Terminal, FWIW. I'm imagining something like macOS' `caffeinate`. You can `caffeinate`, and it will keep the machine awake until you press <kbd>Ctrl+C</kbd>, or you can `caffeinate foo` and it will keep the machine awake until `foo` exits.

**Comment by zadjii-msft** [comment]
that's actually really clever

**Comment by Sergio0694** [comment]
Would it perhaps make sense to have it just built-in into Terminal, so you can opt-in on a per-command basis?

**Comment by zadjii-msft** [comment]
> have it just built-in into Terminal ... ?

Eh, honestly, in the name of trying to keep things as minimal as possible, probably not. However, there is [PowerToys.Awake](https://learn.microsoft.com/en-us/windows/powertoys/awake#command-line-interface-cli), but I cannot for the life of me figure out how to get the CLI to work

@crutkas help me out

**Comment by crutkas** [comment]
as of now, you'd need to turn off awake PowerToys can do it all via CLI but you'll want to turn it off inside PowerToys.  We're working on improving this so the two can work side by side.

I grabbed the PID for Notepad in this example 

PS C:\Users\crutkas> cd C:\Users\crutkas\AppData\Local\PowerToys
PS C:\Users\crutkas\AppData\Local\PowerToys> .\PowerToys.Awake.exe --pid 24384 --display-on true
![image](https://github.com/microsoft/terminal/assets/1462282/9ea0a9ee-d2a2-4239-80b1-62e360bc278e)

soon as i closed out notepad, screen would turn off.

Good feedback for better documentation and see if we can't do CLI + PT open at same time work.

**Comment by crutkas** [comment]
@zadjii-msft  i believe we can close this out as PT would be the team for this
