### ISSUE TITLE
cannot open app package

### ISSUE THREAD

**Issue by 3052** [microsoft/terminal#16373]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.18363.1139

### Steps to reproduce

https://github.com/microsoft/terminal/releases/download/v1.18.3181.0/Microsoft.WindowsTerminal_1.18.3181.0_8wekyb3d8bbwe.msixbundle

### Actual Behavior

This app package is not supported for installation by App Installer because it uses certain restricted capabilities.

**Comment by zadjii-msft** [comment]
First off - The Terminal definitely isn't going to work on `10.0.18363.1139`. We bumped our min version to 19041 a year or two ago. 

Secondly - I hit this myself last week setting up a fresh machine. I believe that the version of the App Installer that ships with the OS it pretty out of date. If you go to the Microsoft Store and open up the App Installer page, you should be able to manually pull down an update that's got the latest bits in it.

**Comment by 3052** [comment]
better workaround:

1. rename to ZIP
2. extract using Windows
3. dont update anything

**Comment by zadjii-msft** [comment]
FWIW, I'd be careful doing that. There are some crashes in system XAML that were only fixed in the 1904x builds of windows. For example, any sort of nested dropdown menu will crash the Terminal on 18363.

**Comment by DHowett** [comment]
> better workaround:
> 
> 1. rename to ZIP
> 2. extract using Windows
> 3. dont update anything

It is much simpler to use the ZIP files we distribute - they contain the dependencies that would have automatically been resolved by the MSIX system.
