### ISSUE TITLE
Taskbar right click menu not showing custom icon

### ISSUE THREAD

**Issue by ZacharyZhang-NY** [microsoft/terminal#16372]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.2715

### Steps to reproduce

Open settings, go to profile, change the icon to a custom .ico file.

### Expected Behavior

The Taskbar right click menu should show the custom icon like this:
<img width="437" alt="Screenshot 2023-11-24 142418" src="https://github.com/microsoft/terminal/assets/18405598/3ea6d803-f8e7-4f61-9db3-a927a3397f7b">

### Actual Behavior

Now its all showing defaule icon with no custom icon:
<img width="178" alt="Screenshot 2023-11-24 142359" src="https://github.com/microsoft/terminal/assets/18405598/ac38075f-2c84-4ac0-8590-114d8f7a3431">

**Comment by ZacharyZhang-NY** [comment]
I already clear the windows icon cache, still not working.

**Comment by zadjii-msft** [comment]
Are these icons files on disk? Or are they URLs/? I believe the Taskbar doesn't support web URLs for its icons. 

If they're files on disk, then you may need to file feedback directly on the Taskbar, using the Feedback Hub.
