### ISSUE TITLE
Font settings lost on Terminal restart

### ISSUE THREAD

**Issue by fipachu** [microsoft/terminal#16374]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.0

### Other Software

font: JetBrains Mono 

### Steps to reproduce

- Install font JetBrains Mono according to [instructions](https://github.com/JetBrains/JetBrainsMono#manual-installation)
- Set `Defaults > Appearance > Font face` to JetBrains Mono
- Save settings 
- Close all terminal tabs
- Open terminal again

### Expected Behavior

Terminal displays text using JetBrains Mono after restart.

### Actual Behavior

Before restart Terminal uses JetBrains Mono.

After restart a warning appears and Terminal displays text in Consolas
```
Unable to find the selected font "JetBrains Mono".
"Consolas" has been selected instead.
Please either install the missing font or choose another one.
```

**Comment by fipachu** [comment]
Installing the font for all users like in #14382 fixes the issue, but it probably shouldn't happen in the first place. I don't know policy so I'm leaving it open.

**Comment by lhecker** [comment]
> [...] but it probably shouldn't happen in the first place.

Yep... Everyone on the team is patiently waiting for this issue to be fixed as well. 🥲 It's a general OS bug that affects any app like Windows Terminal and is not something that we can easily fix ourselves. I'll close this issue then since you already found the workaround. I'm glad to hear that it fixed your issue at least.

**Comment by Naramsim** [comment]
> > [...] but it probably shouldn't happen in the first place.
> 
> Yep... Everyone on the team is patiently waiting for this issue to be fixed as well. 🥲 It's a general OS bug that affects any app like Windows Terminal and is not something that we can easily fix ourselves. I'll close this issue then since you already found the workaround. I'm glad to hear that it fixed your issue at least.

Hi, is there a ticket or public discussion where we can see the status of the bug?

**Comment by lhecker** [comment]
No, but you can subscribe to #3257, which is the first issue that reported this bug here.
