### ISSUE TITLE
Allow prefix for actions

### ISSUE THREAD

**Issue by mrgharabaghi** [microsoft/terminal#16375]
# Description of the new feature/enhancement

At this time the only option for actions is pressing two or three keys at the same time.
For example: `ctrl+shift+1`

It's very handy to add a new feature like `tmux` prefix.
For example: `ctrl+b` `n` for create a new tab.

1. Press `ctrl+b` and release them.
2. Windows Terminal waiting for our next key.
3. Press `n` and release that.
4. And then Windows Terminal create another tab for us.

Useful link:
https://tmuxcheatsheet.com/

**Comment by j4james** [comment]
I suspect the functionality you're looking for will be covered by issue #1334.

**Comment by mrgharabaghi** [comment]
> I suspect the functionality you're looking for will be covered by issue #1334.

Wow, this issue was created on `Jun 19, 2019`.
I wonder why it has not been implemented yet.

**Comment by j4james** [comment]
It's tagged as https://github.com/microsoft/terminal/labels/Help%20Wanted if you're interested in working on this feature. And note the comment here: https://github.com/microsoft/terminal/issues/1334#issuecomment-1427139356.

**Comment by zadjii-msft** [comment]
Yep, this is definitely /dup #1334

We'd love any help! Our team can only really prioritize features based on 👍's, but we'd be happy to help with a community contribution here
