### ISSUE TITLE
Windows Terminal Crashs when debugging a program in Visual Studio 2022 Preview.

### ISSUE THREAD

**Issue by akr-akari** [microsoft/terminal#16383]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2715

### Other Software

Visual Studio 2022 Preview

### Steps to reproduce

Debugging a program in Visual Studio 2022 Preview.

### Actual Behavior

Windows Terminal crashes.

**Comment by akr-akari** [comment]
https://aka.ms/AAnsmjn

**Comment by lhecker** [comment]
Unfortunately your feedback submission doesn't seem to contain a crash dump. Did you not use "Recreate my problem"?

**Comment by zadjii-msft** [comment]
Just squinting and trying to psychic debug - we've had an uptick in crashes that get attributed to us, but are actually root caused to `wetype_tip_core.dll`. (MSFT:47492412 internally). That might be related? No idea if weType is in play here though.

**Comment by akr-akari** [comment]
> Unfortunately your feedback submission doesn't seem to contain a crash dump. Did you not use "Recreate my problem"?

Sorry, I have added and submitted a record of reproducing the issue now.
This is my first time using Feedback.

**Comment by zadjii-msft** [comment]
Can you include the link you your new feedback submission/? It's nearly impossible for us to find it in the backend without the direct link 🙃

**Comment by akr-akari** [comment]
> Can you include the link you your new feedback submission/? It's nearly impossible for us to find it in the backend without the direct link 🙃

Sorry，this：
https://aka.ms/AAnuoh2

**Comment by akr-akari** [comment]
> I'm not super familiar with analyzing feedback submissions, but I believe that one doesn't contain a crash dump either. It does however contain correlated feedback reports, which I've searched for crash events. You had 5 last week, all of them in `WindowsTerminal.exe` and all of them blame `d2d1.dll`. Looking through crash reports from other devices , one potential cause could be if you're using an outdated version of MacType. In your feedback submission I can see `MacTray.exe` there which is part of MacType.
> 
> In short: Please update MacType to this version: https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31 Let us know if that fixes your issue!

OK, I have updated mactype and the issue has been resolved. Thank you!
