### ISSUE TITLE
Feature Request: custom tab name

### ISSUE THREAD

**Issue by talbaumel** [microsoft/terminal#1638]
Hi, can you add an option to replace the tab name from the full path to a custom string the user can edit?

Thanks, great job

**Comment by DerekZA** [comment]
+1 great idea

**Comment by JushBJJ** [comment]
Duplicate of #608

**Comment by HiWilliam** [comment]
great idea!,the tab name is too long

**Comment by DHowett-MSFT** [comment]
Yeah that’s a dupe. Thanks @JushBJJ
