### ISSUE TITLE
Terminal putting ANSI Escape Code in terminal line when attaching tmux session

### ISSUE THREAD

**Issue by angadschawla** [microsoft/terminal#16384]
### Windows Terminal version

1.18.2822.0

### Windows build number

 10.0.22621.0

### Other Software

I am using Windows terminal to connect via SSH (openSSH on Windows) to Linux machine. Once connected I run tmux attach to connect to an already running tmux session. The shell on Linux is zsh. 

### Steps to reproduce

Whenever I run "tmux attach -t session_name".

### Expected Behavior

I should just be attaching to a detached session. 

### Actual Behavior

Whenever I connect to the detached session in Tmux, I get this input "61;6;7;22;23;24;28;32;42c" which seem line ANSI escape codes. This is annoying as if there is a process going in that tmux session this messes up the visual output of the script already running. 

I tried running the same command on a Mac Machine using terminal and iTerm 2, and this error does not happen. 

<img width="843" alt="Screenshot 2023-11-27 112934" src="https://github.com/microsoft/terminal/assets/70210887/ff1d0b43-5196-493d-aa09-e2f2ffe5129c">

**Comment by j4james** [comment]
This is quite likely the same issue as #7185. And it was suggested there that upgrading SSH might help. The other suggestion was to set a longer `escape-time` value in your tmux config.

**Comment by angadschawla** [comment]
Thank you, @j4james! That handled it. I used the `escape-time` suggestion.

**Comment by Noapoleon** [comment]
This does not fix it for me.
Also I get the exact same weird numbers
