### ISSUE TITLE
winget upgrade error

### ISSUE THREAD

**Issue by albertosantini** [microsoft/terminal#16381]
### Windows Terminal version

1.18.2822.0

### Windows build number

Windows 11 22H2 OS Build 22621.2715

### Steps to reproduce

winget upgrade -all

### Expected Behavior

Upgrade the terminal. 

### Actual Behavior

 winget upgrade --all
Name             Id                        Version     Available   Source
-------------------------------------------------------------------------
Windows Terminal Microsoft.WindowsTerminal 1.18.2822.0 1.18.3181.0 winget
1 upgrades available.

Installing dependencies:
This package requires the following dependencies:
  - Packages
      Microsoft.UI.Xaml.2.8 [>= 8.2306.22001.0]
(1/1) Found Windows Terminal [Microsoft.WindowsTerminal] Version 1.18.3181.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Installing dependencies:
(1/1) Found Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ████████████████████████████▌   95%
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

**Comment by albertosantini** [comment]
Starting context:

```
winget upgrade
Name             Id                        Version     Available   Source
-------------------------------------------------------------------------
Windows Terminal Microsoft.WindowsTerminal 1.18.2822.0 1.18.3181.0 winget
1 upgrades available.
```

The similar issues suggested above is not similar at all.

**Comment by MmDawN** [comment]
> ### Windows Terminal version
> 1.18.2822.0
> 
> ### Windows build number
> Windows 11 22H2 OS Build 22621.2715
> 
> ### Other Software
> _No response_
> 
> ### Steps to reproduce
> winget upgrade -all
> 
> ### Expected Behavior
> Upgrade the terminal.
> 
> ### Actual Behavior
> ## winget upgrade --all
> Name Id Version Available Source
> Windows Terminal Microsoft.WindowsTerminal 1.18.2822.0 1.18.3181.0 winget 1 upgrades available.
> 
> Installing dependencies: This package requires the following dependencies:
> 
> * Packages
>   Microsoft.UI.Xaml.2.8 [>= 8.2306.22001.0]
>   (1/1) Found Windows Terminal [Microsoft.WindowsTerminal] Version 1.18.3181.0
>   This application is licensed to you by its owner.
>   Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
>   Installing dependencies:
>   (1/1) Found Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
>   This application is licensed to you by its owner.
>   Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
>   Successfully verified installer hash
>   Starting package install...
>   ████████████████████████████▌   95%
>   Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

same issue

**Comment by albertosantini** [comment]
Maybe due to Microsoft.UI.Xaml.2.8

```
$ winget search Microsoft.UI.Xaml.2.8
Name              Id                    Version        Source
--------------------------------------------------------------
Microsoft.UI.Xaml Microsoft.UI.Xaml.2.8 8.2306.22001.0 winget

$ winget install Microsoft.UI.Xaml.2.8
Found Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ████████████████████████████▌   95%
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.
```

**Comment by zadjii-msft** [comment]
#16359 too was having issues with 1.18. 

https://github.com/microsoft/winget-cli/issues/3918

**Comment by zadjii-msft** [comment]
Thanks for double checking!

/dup https://github.com/microsoft/winget-cli/issues/3918
