### ISSUE TITLE
Acrylic Tab Bar Oddness

### ISSUE THREAD

**Issue by shieronymus-slingshot** [microsoft/terminal#16389]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.2715

### Steps to reproduce

The new stable version of Terminal is showing odd tab bar behavior when the "Appearance --> Use acrylic material in the tab row" is turned on.

1. Put Windows in dark mode, but apps in light mode
2. Put Terminal in dark application theme
3. Put up a white background (e.g. Word full-screen) so it shows better
4. Start up Terminal -- many times (not always) the tab bar shows partial acrylic, like a horizonal line dividing acrylic from plain black, or a block of black on one side of the tab bar
5. Clicking on the tab bar brings back the acrylic effect (repaint?) -- I can't seem to get a screenshot because that apparently forces an update also

Another effect I'm seeing is the tab bar going all black when clicking between multiple open tabs
1. Open another tab after the steps above
2. Click between the tabs
3. The tab bar shows solid black for me
4. Clicking on an empty space in the tab bar brings back the acrylic, or if that doesn't work, dragging the window

### Expected Behavior

The acrylic effect showing consistently and solidly.

### Actual Behavior

Partial tab bar acrylics, black tab bar when multiple tabs are open and you cycle through them by clicking.

**Comment by zadjii-msft** [comment]
Would you say it looks anything like: #14384

> ![](https://user-images.githubusercontent.com/9592210/201533459-31924762-03d8-4f63-a5cd-81d728953039.gif)

**Comment by shieronymus-slingshot** [comment]
Yes, it's somewhat similar, but in my case the black color overwriting the acrylic on the tab bar doesn't flicker -- it stays until I click on the tab bar, resize the window, move it, etc.

So for instance, I open Terminal, add a second tab, and click between them, which causes the acrylic to change to all black -- the tab bar stays all black until I click on an empty part of it (the space where there isn't a tab).

**Comment by shieronymus-slingshot** [comment]
Just an update... I tested this on my home laptop and that machine did not show the issue, but it seems like it's system-dependent (video driver?). 

If it helps, here are some more details about the problem laptop:
- OS Name	Microsoft Windows 11 Pro
- Version	10.0.22631 Build 22631
- Other OS Description 	Not Available
- OS Manufacturer	Microsoft Corporation
- System Name	DESKTOP-6S0R506
- System Manufacturer	Dell Inc.
- System Model	XPS 15 9520
- System Type	x64-based PC
- System SKU	0B19
- Processor	12th Gen Intel(R) Core(TM) i9-12900HK, 2500 Mhz, 14 Core(s), 20 Logical Processor(s)
- BIOS Version/Date	Dell Inc. 1.18.0, 9/12/2023
- SMBIOS Version	3.4
- Embedded Controller Version	255.255
- BIOS Mode	UEFI
- BaseBoard Manufacturer	Dell Inc.
- BaseBoard Product	0F6K9V
- BaseBoard Version	A00
- Platform Role	Mobile
- Secure Boot State	On
- PCR7 Configuration	Elevation Required to View
- Windows Directory	C:\Windows
- System Directory	C:\Windows\system32
- Boot Device	\Device\HarddiskVolume1
- Locale	United States
- Hardware Abstraction Layer	Version = "10.0.22621.2506"
- Time Zone	Mountain Standard Time
- Installed Physical Memory (RAM)	32.0 GB
- Total Physical Memory	31.7 GB
- Available Physical Memory	16.8 GB
- Total Virtual Memory	42.7 GB
- Available Virtual Memory	23.3 GB
- Page File Space	11.0 GB
- Page File	C:\pagefile.sys
- Kernel DMA Protection	On
- Virtualization-based security	Running
- Virtualization-based security Required Security Properties	
- Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
- Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
- Virtualization-based security Services Running	Credential Guard, Hypervisor enforced Code Integrity
- Windows Defender Application Control policy	Enforced
- Windows Defender Application Control user mode policy	Off
- Device Encryption Support	Elevation Required to View
- A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by zadjii-msft** [comment]
Trying to close the loop here: The internal thread came back and folks are pretty sure this is something that's fixed in internal OS builds. Folks on the thread report seeing something like what you report a few months back, but they don't see it anymore. They also have _no idea_ how it actually got fixed in the OS. 

I'm gonna close this out, since the internal bug came back as "resolved somehow". Alas, since we don't know what exactly fixed it, I'm not sure I can give a better estimate for when the fix will be available other than "Soon<sup>TM</sup>"
