### ISSUE TITLE
Add support for side panels

### ISSUE THREAD

**Issue by thernstig** [microsoft/terminal#16387]
# Description of the new feature/enhancement

Tools such as Visual Studio Code or even [MobaXterm](https://mobaxterm.mobatek.net/) support side panels. Imagine something like:

![image](https://github.com/microsoft/terminal/assets/30827238/c9f8b1ff-e275-4a74-beec-f422806a1fb2)

- The red lines showcase the various profile names
- The blue lines indicate the current open connections to each profile. Be that tabs or side panels. The UX for tabs vs. sidepanels needs to be figured out.

It would be neat if Windows Terminal had an optional side panel support. Suggested keyboard shortcut:
<kbd>ctrl+b</kvd>

# Proposed technical implementation details (optional)

No idea.

**Comment by zadjii-msft** [comment]
This kinda just seems like a case for #997 and #4000. 4000 has a _lot_ of linked threads to various UI elements that might be used in panes. I guess my question would be more specifically, what do you want surfaced in that pane? 
* A "List of Profiles" pane seems... just about as useful as the dropdown. 
* A "List of tabs/panes" pane doesn't seem like a terrible idea, though I think there's some overlap with the ideal form of the tab switcher there
* Something else/?

**Comment by thernstig** [comment]
I thought my original post answered your questions? I specifically mentioned that the blue lines should indicate **open connections** (be that tabs or panes). And that the red lines indicate to which profile the connection is open.

This is thus another view of the current tabbed and pane layout, which many users prefer, especially people coming from MobaXterm or similar tools.

The use case is a UX use case for a more advanced way of visualization all opens profiles+connections than what tabs can do.

We can also map this 1-to-1 with how VS Code has an [OPEN EDITORS](https://code.visualstudio.com/assets/docs/getstarted/userinterface/view-management.png) functionality. It is a more advanced form than tabs to visualize all open editors.

Aside: I used the term `Panel` on purpose, since it is the convention used by Visual Studo Code. Even though you render it in a "pane" (as described in https://github.com/microsoft/terminal/issues/997), I think the term `Panel` is better.

Imagine having 30 open tabs. Moving between these tabs is easier in a side panel like above, than trying to find the tabs. It is even harder if having panels within tabs, to find exactly where you are.

I am not an UX expert, but I am sure an UX expert could fill in even more why a side panel is in many ways superior to tabs.

**Comment by zadjii-msft** [comment]
Huh. So, basically just, vertical tabs (ala #835), but you _also_ want to group the list of tabs, by what profile is open in them/?

**Comment by zadjii-msft** [comment]
Wait is the more important thing the _grouping_? Or just the vertical list of open tabs/? 

Because if it's _grouping_, the new tab menu supports that as of #1571 merging in like, 1.17:
![image](https://github.com/microsoft/terminal/assets/18356694/74085cd0-7ab1-404e-b5f0-0bf84c463156)

 

That might be quick solution here.

**Comment by thernstig** [comment]
Your assumption is correct for the last time in your bullet list. It might be that https://github.com/microsoft/terminal/issues/835 could be used to solve this as well, I do not know.

I am honestly ok with closing this one completely, if you feel it is not worth to invest that time. It is not a huge deal to me, but I have seen some users in our enterprise that would prefer that kind of view proposed here.

**Comment by zadjii-msft** [comment]
Okay so we discussed a bit: we agree that this is a sensible feature request. It'd be a setting to configure how vertical tabs work, post-#835. 

However, we're pretty impossibly far away from being able to implement #835 ourselves. So we're gonna close this out. If someone wants to do #835, then this, we're here for it. Otherwise we'll mark it up as a neat idea for a 3p extension, whenever #4000 is implemented.
