### ISSUE TITLE
Keyboard typing problem in ABNT2

### ISSUE THREAD

**Issue by junalmeida** [microsoft/terminal#1639]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

Any other software? No
```

# Steps to reproduce

Using a brazillian ABNT2 keyboard, open any terminal and type `right alt + Q`.  

# Expected behavior

This should type `/` in any type of terminal.

# Actual behavior

When using `bash`, it deletes the rest of the typed line. When using `powershell` or `cmd`, it types `^_`

**Comment by tumik** [comment]
Probably a duplicate of #521 ?

**Comment by junalmeida** [comment]
Probably also a duplicate of #487

**Comment by DHowett-MSFT** [comment]
If right alt is “altGr” then it’s a dupe of 521
