### ISSUE TITLE
Windows terminal loose focus after 32 sec

### ISSUE THREAD

**Issue by nitrateag** [microsoft/terminal#16391]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Simply run (with Win+R shortcut) this command :
```
wt powershell -c pause
```

wait 32 sec.

---
yeah, 32 sec exactly... not 30 ! 
the focus is loose each time, and only on Windows Terminal !
if I use old blue Powershell console, he don't loose the focus
very weird ^^

it happen also with
```
wt powershell -c Read-Host
```
of course, that is a minimal example to reproduce, but that very painfull for the script I'm working on

### Expected Behavior

After 32 seconds, the terminal still have the focus. Hit ENTER stop the pause

### Actual Behavior

After 32 seconds, the terminal loose the focus. Hit ENTER do nothing because terminal don't catch the input until we click/set focus on terminal

**Comment by nitrateag** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> 
> ### Closed similar issues:
> * [Terminal window closes itself sometimes when losing focus (#9889)](https://github.com/microsoft/terminal/issues/9889),  similarity score: 0.84
> * [Terminal loses focus on launch (#12134)](https://github.com/microsoft/terminal/issues/12134),  similarity score: 0.83
> * [Terminal does not get focused properly (#14276)](https://github.com/microsoft/terminal/issues/14276),  similarity score: 0.82
> * [Active terminal does not get focus when window gets focus (#522)](https://github.com/microsoft/terminal/issues/522),  similarity score: 0.82
> * [windows terminal does not focus on input after launch (#13846)](https://github.com/microsoft/terminal/issues/13846),  similarity score: 0.81
> * [Weird behavior when terminal is focused (#11673)](https://github.com/microsoft/terminal/issues/11673),  similarity score: 0.80
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

sorry gentle bot, but my case is little different : Terminal have the focus when open, but loose it after 32 sec...
In example you show me they don't have the focus at start. And I don't use WSL.

**Comment by zadjii-msft** [comment]
Do you have something like BeyondSoft or CyberArk or anything like that/? Does this repro any time you open a new tab once the Terminal is already running?

What you're describing is highly similar to reports over in #13388

**Comment by zadjii-msft** [comment]
Welp yea, let's merge this into that other thread then. There's something wacky that BeyondTrust does that we don't fully understand. We have yet to come up with a clever fix 😕 

/dup #13388
