### ISSUE TITLE
Add a new environment variable to describe the way terminal is launched

### ISSUE THREAD

**Issue by steve02081504** [microsoft/terminal#16396]
# Description of the new feature/enhancement

I want my shell to use the folder path when I start it via open in terminal in the context menu
and when I open the shell in the other menus I want it to use the user path `~`.
In the current version of wt I have to do this in my profile.
```bash
if pwd=='C:\Windows\System32'
	cd ~
```
The obvious disadvantage of this is that if I actually start wt in C:\Windows\System32, inevitably the shell will jump back to `~`.

But if wt provides an environment variable that describes the way it is started, I can change the logic to something like this

```bash
if env:WT_FROM & env:WT_FROM!=('RightCheck' | 'Command')
	cd ~
```

# Proposed technical implementation details (optional)

Add a new environment variable that describes how wt is started.
Add a new environment variable that describes how many tabs the current tab is.
Add a new environment variable that describes wt's version

**Comment by zadjii-msft** [comment]
Wait hold on, all this sounds like overkill to me. 

How do you have your profile configured? I'd guess with `"startingDirectory": "."` or something, right? That would explain why starting it from the run dialog (or other menus) starts your shell in system32 - the `.` is evaluated relative to the CWD of Terminal itself (which is system32). 

The shell extension (read: the file explorer right-click context menu) already launches the Terminal with `wt -d <the current path>`. That should spawn your profile with a `startingDirectory` set to the CWD in explorer. 

Now, setting the default `startingDirectory` to `~` is a little tricky. I'm assuming you're using WSL here - if you are, then the following should work:
```json
"startingDirectory": "~",
```

Now, that may not work, depending on the profile's commandline. More reliable might be:

```json
"startingDirectory": "//wsl$/<distro name>/home/your WSL user/",
```

(e.g. `"startingDirectory": "//wsl$/Ubuntu-18.04/home/zadjii/"`)

Of course, if you're using PowerShell, I think just plain-old `%userprofile%` should get you what you're looking for.

Does that all help/?

**Comment by steve02081504** [comment]
> For that, run the Terminal with `wt -d .` That'll specifically tell the Terminal "run the profile in the current directory".
Oh! Thank you for your help. It looks like I did make a silly mistake. Sorry for the delay.
