### ISSUE TITLE
Certain font ligatures within Monaspace (possibly other fonts) don't work.

### ISSUE THREAD

**Issue by antonw51** [microsoft/terminal#16394]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22631.2715

### Other Software

Monaspace font v1.0.0

### Steps to reproduce

1. Use a monaspace font (Neon regular used here)
2. Type the following string “imi” to test that texture healing (ligatures) are working. (The “m” should stretch out)
3. Type any usual literature like “=>" or “->”

### Expected Behavior

As observed in VS Code, the ligatures do indeed work for both “texture healing” and the arrows as opposed to Windows Terminal.

![image](https://github.com/microsoft/terminal/assets/62518497/75fb45b5-908d-45b8-a340-52cff01e2c31)

### Actual Behavior

Here are the observed results within CMD:
![Animation1](https://github.com/microsoft/terminal/assets/62518497/cdce3716-323f-4047-ae14-691a305d18ab)
As visible, the “texture healing” ligatures are working, but the standard ones are not.

**Comment by lhecker** [comment]
Its documentation mentions that these ligatures are part of stylistic sets: https://github.com/githubnext/monaspace?tab=readme-ov-file#coding-ligatures

You can enable them like so:
```json
"font":
{
    "face": "Monaspace Neon Var",
    "features": {
        "ss01": 1,
        "ss02": 1,
        "ss03": 1,
        "ss04": 1,
        "ss05": 1,
        "ss06": 1,
        "ss07": 1,
        "ss08": 1
    }
}
```

But why does it work in VS Code out of the box?

**Comment by lhecker** [comment]
Actually, I didn't think to confirm what you wrote here:
> As observed in VS Code, the ligatures do indeed work for both “texture healing” and the arrows as opposed to Windows Terminal.

In my testing, VS Code doesn't show those ligatures either, unless you enable them manually via `"editor.fontLigatures"`. I'll close this issue then. Please reopen it if I'm incorrect. 🙂
