### ISSUE TITLE
Beep on Ctrl+Z regardless of bellStyle

### ISSUE THREAD

**Issue by JVimes** [microsoft/terminal#16393]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.19045.0

### Steps to reproduce

- Open Windows Terminal with default settings (shell is PowerShell 7.3.10, for me).
- Press Ctrl+Z

### Expected Behavior

It doesn't beep.

### Actual Behavior

It beeps.

**Comment by DHowett** [comment]
Unfortunately, in this case, PowerShell is going behind our backs and calling the Windows OS `Beep()` function directly. ☹️

**Comment by JVimes** [comment]
Ah, you're right!

Putting this in my profile seems to fix it:
```pwsh
Set-PSReadlineOption -BellStyle None
```
