### ISSUE TITLE
When pressing keys like NUM LOCK Terminal takes that as console input

### ISSUE THREAD

**Issue by IlleNilsson** [microsoft/terminal#16390]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19044

### Other Software

PowerShell 7.4.0

### Steps to reproduce

1. Open a Terminal Window with PowerShell

2. ls C:\ -r

3. Scroll up a couple of "pages"

4. Press NUM LOCK

Woops now you are at the prompt at the bottom of the console windows

### Expected Behavior

That one would stay at the position one scrolled to

### Actual Behavior

You are at the prompt at the bottom of the console windows

**Comment by lhecker** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5366 for more discussion.

/dup #5366
