### ISSUE TITLE
Prevent opening new tabs when clicking in taskbar pinned app on primary monitor with Windows Terminal opened in secondary monitor

### ISSUE THREAD

**Issue by cakira** [microsoft/terminal#16403]
# Description of the new feature/enhancement

I have a setup with 2 monitors. Also, I have Windows Terminal (WT) pinned to my taskbar.
Sometimes, I move WT to the secondary monitor and I forget it is open there. Then, I want to run a command in WT, so I click the WT icon in the taskbar in the primary monitor.
_Current behavior:_ Clicking the icon causes the Windows Terminal on the secondary monitor to pop up and open a new tab.  
_Desired behavior:_ Clicking the icon could make the Windows Terminal on the secondary monitor pop up without opening a new tab.

This request is related to #14130, but it has an opposite behavior. That ticket asks to open a new window instead of a new tab, this ticket asks to not open a new tab at all.

# Proposed technical implementation details (optional)

After reading the documentation and conducting tests, I found that calling `wt.exe` with the command line option "focus-tab" achieves the desired behavior. However, I'm unable to configure the taskbar-pinned app to run with command line options in Windows 11. A setting to make the option "focus-tab" implicit and automatic could address this.

**Comment by zadjii-msft** [comment]
Hmm. I've reached out to a contact on the Taskbar team. I believe this is just "by design" with the way the taskbar currently works. I think when taskbar is set to "taskbar where window is open", I think the taskbar breaks the connection between the pinned shortcut, and the open window. I think it might end up _weirder_ if we try and deviate from the rest of the system behavior... But who knows! Maybe this is something they're already tracking 🤷

**Comment by cakira** [comment]
Now, I've noticed that my browser behaves exactly as @zadjii-msft described: when pinned to my taskbar and positioned on the second monitor, clicking its icon in the taskbar opens a new browser window.

Though it's somewhat annoying to me, if this is intentional or "by design," I agree that Windows Terminal should not deviate from this pattern.
So, I'm closing this feature request.
