### ISSUE TITLE
Bug Report: @ not working with German keyboard

### ISSUE THREAD

**Issue by XanatosX** [microsoft/terminal#1640]
# Environment

Windows build number: **Microsoft Windows [Version 10.0.18362.175]**
Windows Terminal version (if applicable): **0.2.1715.0**

# Steps to reproduce

Open up a new powershell or cmd window and try to enter a @ with a German layout keyboard. I tried to type the @ char with `ctrl + alt + q` and I did try it with `AltGr + q` in both cases the behavior is identical.

Seems like the problem is present with the backslash '\' as well on a German keyboard you need to either use `ctrl + alt + ß` or `AltGr + ß` to get the char in any other application.

Since I can ctrl + c my command the alt key should be the problem or the combination.

It is possibly to copy the char if you type it into the editor and paste it with a click of the right mouse button. This is a workaround for the moment.

# Expected behavior

The correct char is getting displayed

# Actual behavior

In the powershell no char will be shown
in the command line the letter `q` or `ß` is getting displayed

**Comment by JushBJJ** [comment]
Duplicate of #521

**Comment by XanatosX** [comment]
You are totally right I will close this report than, thank you 👍
