### ISSUE TITLE
[Github] Similar issues bot failing 

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#16402]
The "Similar issues" bot is failing with the error "no similar issues found".

![Screenshot_20231130-214628_GitHub.jpg](https://github.com/microsoft/terminal/assets/61519853/94883e9e-dedb-49ee-bb21-b0b7c7affb45)

![Screenshot_20231130-214642_GitHub.jpg](https://github.com/microsoft/terminal/assets/61519853/9ecee432-4c05-4932-84d1-f94ad51111d4)

![Screenshot_20231130-214654_GitHub.jpg](https://github.com/microsoft/terminal/assets/61519853/a4581749-3f9e-4d3b-aa84-abf8c0d577be)

**Comment by htcfreek** [comment]
I agree that this is a success without finding a match. But the pipeline run is incorrectly listed as failed and github mobile showed a message about the failed run.

**Comment by zadjii-msft** [comment]
I moved this to the repo for the action over in /dup https://github.com/craigloewen-msft/GitGudSimilarIssues/issues/32. Thanks!
