### ISSUE TITLE
[Terminal Chat AI] Allow company wide disabling this feature 

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#16401]
# Description of the new feature/enhancement

Some companies don't allow the usage of AI features or software that has AI feature for privacy reasons. 

Please implement a way to centrally force disable this feature.

# Proposed technical implementation details (optional)

This can be a policy or HKLM registry value/setting that admins can use to easily disabled this feature for all users.

This setting should work for portable, store and manually installed versions and on all chanels.

**Comment by zadjii-msft** [comment]
Perfectly reasonable ask. I'll link it up to #15000, thanks!

My understanding of GPO is that it can be used to set a reg key, so we can easily query that regardless of what distribution method used.

**Comment by htcfreek** [comment]
@zadjii-msft 
I suggest you to implement a common class where you do the registry reading and that return standardized values like we did in PowerToys (https://github.com/microsoft/PowerToys/blob/main/src/common/utils/gpo.h).

Either you evaluate the Policy ones at application startup or every time the settings window and chat window gets opened.

The default expected behavior of policies is that computer scoope has a higher priority than user scoope.

I think the category in the ADMX file should be `Microsoft\Windows Components\Windows Terminal`.

**Comment by g0t4** [comment]
Given the current setup process requires custom azure resources, isn't that sufficient for an approval process at least short term?

**Comment by htcfreek** [comment]
> Given the current setup process requires custom azure resources, isn't that sufficient for an approval process at least short term?

I thought everyone is able to create such an required account including private persons. Is that wrong? Don't know about this.

If I require a special company account/license/configuration then it should be enough for short term.

**Comment by htcfreek** [comment]
@DHowett , @ilhacker
This is similar to #17964

**Comment by zadjii-msft** [comment]
@PankajBhojwani Double check me - this was resolved by #18095, but since that PR wasn't into `main`, GitHub just didn't auto-close the issue, yea?

**Comment by PankajBhojwani** [comment]
This was resolved by #18095 yep, not entirely sure why the bot didn't close it but I'll close it manually now
