### ISSUE TITLE
Weird glyph rendering issue with CaskaydiaCove NerdFont

### ISSUE THREAD

**Issue by harvastum** [microsoft/terminal#16413]
### Windows Terminal version

1.18.231114001

### Windows build number

10.0.19045.3570

### Steps to reproduce

Glyphs do a wavy thing when I type three lower case 'w' letters in a row with CascadiaCode-NF-Mono.

Steps:  
1. Set font to CascadiaCode-NF-Mono 
2. Type `www`

### Expected Behavior

Here's a comparison of what it looks like in VS Code integrated terminal, Windows Terminal and stock terminal:
![image](https://github.com/microsoft/terminal/assets/22124947/d38d37e4-8c8d-4e1c-98f8-477f493a8e13)

### Actual Behavior

As above.

**Comment by lhecker** [comment]
Windows Terminal enables ligatures by default and the "www" one is a ligature. You can see it here - it's the first one in the top-left: https://github.com/microsoft/cascadia-code#font-features

If you open your settings.json (Ctrl+Shift+,) you can edit your font features to disable that:
```jsonc
"font": {
    "face": "Cascadia Cove, etc.", // <-- you'll have to search this block
    "features": {
        "liga": 0                  // <-- this disables ligatures entirely
    }
}
```

**Comment by harvastum** [comment]
Thanks, I found some more documentation regarding this:

## Font features settings in different apps:
https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

## Settings in Windows Terminal more specifically
https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#font

## List of features that should be possible to set
https://learn.microsoft.com/en-us/typography/opentype/spec/featurelist

Interestingly though, the key you suggested ("liga") didn't have any effect. The settings for particular features seem not to react to any of the following: 
```
"ss01"
"ss02"
"ss03"
"ss04"
"ss05"
"ss06"
"zero"
"onum"
"liga"
```
They are all disabled when `"calt"` is set to 0 though.

So, for anyone who somehow lands here from google, here's a snippet that worked for me:

```json
{
  "font": {
      "face": "CaskaydiaCove Nerd Font Mono"
      "features": {
          "calt": 0
      }
}
```
