### ISSUE TITLE
No SSH authentication forwarding using smartcard

### ISSUE THREAD

**Issue by cmonty14** [microsoft/terminal#16418]
### Windows Terminal version

1.18.2822.0

### Windows build number

11.0.22621.2715

### Other Software

Gpg4win 4.2.0

### Steps to reproduce

I connect a Nitrokey security-token (that is comparable to Yubikey) with OpenPGP keys to my client.
And I want to use this Nitrokey for SSH login to remote servers.

For this I installed GPG4Win on my client and configured file gpg-agent.conf:

enable-ssh-support
To Enable support for PuTTY
enable-putty-support
To Enable support for the native Microsoft OpenSSH binaries (requires gpg 2.4.0 / Gpg4win 4.1.0 or higher)
enable-win32-openssh-support
use-standard-socket
default-cache-ttl 600
max-cache-ttl 7200
Then I (re-) start the gpg-agent and try to SSH into the Jumphost using command ssh (in Windows PowerShell profile).
Here I get a popup window where I must enter the PIN previously set on Nitrokey.
After this I'm connected to the jumphost shell (Linux).

Now I want to connect to the target server using command ssh .

### Expected Behavior

Public key authentication for SSH connection to any target server from jumphost (running Linux).

### Actual Behavior

I need to enter (user) password requested by target server. This means no public key is available.

No, this issue is **not** related to https://github.com/PowerShell/Win32-OpenSSH/issues/1461 because I'm using Windows SSH client.

**Comment by zadjii-msft** [comment]
Ah you know what? I see you already filed a thread about this over in /dup #16406. No need to file a second thread about this! That'll just confuse everyone and further muddle the discussion. Better if you follow up in the original thread you filed. 

Thanks!
