### ISSUE TITLE
Bug Report: Program shortcuts do not expose "Run as a different user"

### ISSUE THREAD

**Issue by PGomersall** [microsoft/terminal#1642]
Program shortcuts do not expose "Run as a different user" only "Run as administrator" on shift right-click.

# Environment
Windows 1903 18362.175 Education x64
Windows Terminal version (if applicable): 0.2.1715.0

# Expected behavior
"Run as a different user" is available on shift right-click

# Actual behavior
Only "Run as administrator" is available

**Comment by DHowett-MSFT** [comment]
This isn't possible with store-deployed applications, so I'm duping it to #1386
