### ISSUE TITLE
"Open in Terminal" does not focus new Terminal window when Ubuntu is running separately.

### ISSUE THREAD

**Issue by carodgers** [microsoft/terminal#16433]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631 N/A Build 22631

### Steps to reproduce

* Start Ubuntu in WSL.
* Open an Explorer folder window. Right click any white space and select "Open in Terminal" from right click menu.

### Expected Behavior

Terminal window opens on top of folder window and receives focus.

### Actual Behavior

Terminal window opens behind folder window and does not receive focus. No keystrokes reach Terminal window until it is focused manually.

Related to closed but unresolved issue https://github.com/microsoft/terminal/issues/6611

**Comment by DHowett** [comment]
@carlos-zamora I think we have a more recent "terminal doesn't come to the foreground" bug report
