### ISSUE TITLE
Terminal Window Don't stick with acrylic and transparece when is not selected

### ISSUE THREAD

**Issue by nerdevops** [microsoft/terminal#16430]
# Description of the new feature/enhancement
Maintain Terminal window "Theme" enabled when Terminal window is not seleceted.
TErminal Window selected bellow:
![image](https://github.com/microsoft/terminal/assets/91952246/4bcecf9e-bf1b-420e-912b-deaca6fafff7)

Terminal window not selected:
![image](https://github.com/microsoft/terminal/assets/91952246/814db459-aa20-4ebe-91f5-ff202d192aef)

# Proposed technical implementation details (optional)
Make an toggle button that will not change the window when is not selected.

**Comment by zadjii-msft** [comment]
/dup #7158

This was fixed in 1.19.

**Comment by nerdevops** [comment]
I've updated, it's working, thank you !
