### ISSUE TITLE
[feature request] Folders in the profiles dropdown

### ISSUE THREAD

**Issue by paulomanrique** [microsoft/terminal#16437]
# Description of the new feature/enhancement

I have a lot of profiles to remote servers I connect using SSH. It would help a lot my organization if we could organize our profiles into folders.

**Comment by zadjii-msft** [comment]
You can already do this. See [`newTabMenu`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#new-tab-dropdown)

/dup #1571
