### ISSUE TITLE
Unicode char 0x2597 (Quadrant lower right) et al. are not displayed correctly

### ISSUE THREAD

**Issue by marcIhm** [microsoft/terminal#16436]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22635.2841

### Other Software

WSL2

### Steps to reproduce

printf "\\u2597\n" # within wsl2

### Expected Behavior

The output should display a glyph with the lower right quadrant filled; just as shown in windows font selection (see screenshot).
<img width="960" alt="Screenshot 2023-12-07 074953" src="https://github.com/microsoft/terminal/assets/12209310/b8d79b6d-1cb1-4baa-bd41-016448fc8ab2">

### Actual Behavior

There is only a thin vertical line (1 pixel wide ?) in the lower right quadrant; most of the rest is unfilled. 
<img width="960" alt="Screenshot 2023-12-07 073806" src="https://github.com/microsoft/terminal/assets/12209310/7d78b182-c5b0-4921-9ff9-b0035151c969">

Some additional information:
- The behaviour above does not depend on the font chosen for wsl2 (ubuntu); in my case "Ubuntu Mono"; but it looks the same for "Lucida Console"
- The same glyph looks good in font "Segoe UI Symbol" (checked in: Windows Settings -> Fonts, see first screenshot)
- Other Unicode Block Characters are affected in a similar way
- This used to work two weeks ago (wsl2)
- In the meantime, some Windows-Updates happened and I played around with "chafa" (https://github.com/hpjansson/chafa) under wsl2; I assume that such a program should not be able to corrupt the glyph handling within "Windows Terminal" ...
- Background: The output of "figlet -f smblock 12345" within wsl2 looks ugly as a result of this issue (to try, you will need to install figlet first via "sudo apt install figlet toilet")
- Background: No such Problems (of course) when I boot Ubuntu directly and try the same in Gnome Terminal

**Comment by 237dmitry** [comment]
Maybe this is font problem?

![Screenshot 2023-12-07 101558](https://github.com/microsoft/terminal/assets/78153320/9a3b3e32-9080-471e-b8f6-e927c415a419)

**Comment by lhecker** [comment]
It is possible that this hasn't ever worked correctly in AtlasEngine. The fallback for "▗" comes from Segoe UI Symbol by default (as you've already shown), which doesn't have the same aspect ratio as your chosen font. Due to that the right half of it simply gets clipped off, which is something we currently do intentionally because of this (click play in the top right): https://github.com/microsoft/terminal/pull/15343#issuecomment-1548142384

#5897 would help a lot with this issue.

**Comment by marcIhm** [comment]
For my case it is the "new text rendering engine". If I switch it off, everything is Okay again (at least for my concerns). See:

<img width="960" alt="Screenshot 2023-12-07 213159" src="https://github.com/microsoft/terminal/assets/12209310/497e614a-9d72-492a-b6a5-5e1cbdfb1a96">

But interestingly this is only true for my favorite font "Lucida Console".
For other fonts (e.g. "Cascadia Code") things are a tiny bit more rough:

<img width="960" alt="Screenshot 2023-12-07 213431" src="https://github.com/microsoft/terminal/assets/12209310/190f815a-d73e-4a16-9400-d745ff5d04fe">

So I agree with lhecker: It does not work perfectly with AtlasEngine either, except from the "Lucida Console"-case (and maybe others), which fortunately applies to me :- )

So, yes, I agree, that #5897 would help a lot, as for example the GnomeTerminal does a very good job on this.
Therefore I hope, that you can fix #5897 before you remove the AtlasEngine.

Thanx a lot for your help !
I am closing this now, because (as you have shown to me), there are other relevant issues which describe the same problem already ...

P.s.: I cannot find this monofur font with "block chars", for that matter. Only some cropped (?) versions without block chars ...
