### ISSUE TITLE
Default CLI Editor - Feature Exploration!

### ISSUE THREAD

**Issue by plante-msft** [microsoft/terminal#16438]
# Windows Feature Exploration: Default CLI Text Editor 

## Please Provide Feedback! 
Please let us know what you think about this feature by commenting on this issue! We’d love to hear your ideas and feedback! 

Let us know:

•	Do you want to see a default CLI editor in Windows? How would it improve your experience?
•	Do you use a CLI editor today? If so, which do you use and why?
•	Are there alternative solutions or CLI editor-related features you’d like to see? 

## Overview
This issue is suggesting that Windows should once again ship with a CLI editor installed inbox by default. 32-bit versions of Windows ship with edit, but 64-bit versions of the OS have no CLI editor installed inbox. A CLI editor is a core tool for system admins, developers, and power users – providing an immediate viable option here is an important quality-of-life improvement. 

## Solution
There are countless available CLI editor options across operating systems today, each with their own sets of advantages and disadvantages. The goal would be to install the selected editor(s) by default such that their commands work out-of-the-box. Example editors include but are not limited to: 

•	Edit
•	Pico
•	Nano
•	Vim
•	Emacs
•	etc.

Installing one or more of these editors by default will offer immediate CLI text editor capabilities on all Windows machines, preventing the need for additional installs or workarounds when operating on local machines, remote connections, or Windows containers.  

**<ins>Alternative</ins>** 

Improve error handling such that the shell will recognize editor commands that fail due to missing package and recommend the proper install solution. See below for an example using Vim.

Actual:  

![image](https://github.com/microsoft/terminal/assets/150482134/9e5fec55-9a96-46b2-b393-5a8e7b4b85b2)

Alternative Solution:

![image](https://github.com/microsoft/terminal/assets/150482134/60fbdd09-58b0-488d-80a3-885d723b76b0)

**Comment by 237dmitry** [comment]
It’s a pity that Windows doesn’t have `edlin` or `edit` or any other console editor out of the box. I think this needs to be fixed.

On Windows I usually use the internal `Far` editor, much less often the `micro` editor.
For Linux, respectively, `mcedit` and also `micro` (works better than its Windows version)
