### ISSUE TITLE
Scroll up, click to select -> viewport moves down before starting the selection

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#16459]
noticed in v1.20.3401.0

0. I was using CMD
1. `dir` a couple times
2. scroll up
3. try to select some text 

expected: text is selected there in the scrollback

actual: viewport jumps back down to the bottom, _then_ the selection starts

**Comment by zadjii-msft** [comment]
Demo:
![c76137f7-a54a-46b3-8a01-c0ad608868f5](https://github.com/microsoft/terminal/assets/18356694/e2e5658a-7ca4-4ede-8ca8-4659c7175bde)


wat 
![5b66e171-04e0-4475-9ddb-e924d1761a9c](https://github.com/microsoft/terminal/assets/18356694/7a0d7898-646a-453e-9ee0-5693e51a321e)


wat

**Comment by DHowett** [comment]
_Wow_.

I wonder - if you use the debug tap, is your action generating any input that we might consider for input snapping?

**Comment by zadjii-msft** [comment]
![image](https://github.com/microsoft/terminal/assets/18356694/3af1bacc-ffab-47fd-b008-c2ea996c7223)

# 👀

```
␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_␛[37;75;0;1;0;1_␛[37;75;0;0;0;1_
```

Literally instantly filled the buffer with this.
