### ISSUE TITLE
Cannot connect to Cloud Shell.  

### ISSUE THREAD

**Issue by xDj4ng0x** [microsoft/terminal#16458]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22631

### Steps to reproduce

When I open Terminal, and try to connect Azure Cloud Shell, it no longer allows me to connect and prints an error. 

![tenant](https://github.com/microsoft/terminal/assets/12502958/61118d45-3c19-4f4d-b8c1-b8ad667b86b9)

### Expected Behavior

Connection to Cloud Shell

### Actual Behavior

Responds with [process now exited with code 1 (0x0000001)

**Comment by DHowett** [comment]
This was fixed in 1.18 -- I'd encourage you to upgrade!
