### ISSUE TITLE
need Terminal to change its window icon like CMD(or maybe Windows Console Host)!

### ISSUE THREAD

**Issue by Karlish-OMG** [microsoft/terminal#16455]
When I run an .exe program with no icon, it will call CMD on WIN10, and the cmd window's icon is cmd itself's icon. But if I create a shortcut of this program and change its icon, the cmd window's icon now become the icon I have just changed! Later, I do the same on Win11, but found to fail to see the same result. After a long time search and try, I finally found I should to change the option in Win11 Settings——Choose CMD in Terminal Setting! And finally I got what I expected.

I know Terminal is a newer and better one, and it can custom many things. But it seems that it can't or not convenient enough to change the icon for different single programs. And I hope Terminal can inherit the properties like cmd(or maybe Windows Console Host) do.

When I wrote here, I notice I may make a mistake for my lack of computer system's knowledge: It is Terminal vs Windows Console Host（conhost.exe） and cmd vs  Powershell, but what I hope and observe may do not change.
 
My OS is Windows 11 22H2 (PC's CPU  is Intel) , and I met up with such problem is when I run the .exe program in this github project: https://github.com/pandora-next/deploy 
CMD(or maybe Windows Console Host)'s screenshot:
<img width="480" alt="cmd" src="https://github.com/microsoft/terminal/assets/78194822/36014367-d42a-4562-9444-5eed6f8aea6d">

Terminal 's screenshot:
<img width="464" alt="terminal" src="https://github.com/microsoft/terminal/assets/78194822/8f256429-7d4b-4410-8cbe-844bad98175f">

Hope these information will help you to fix this problem, Thank you !!

**Comment by ShenHongFei** [comment]
I hope to dynamically set the tab icon in the new-tab command line. Please refer to the function of ConEmu.

**Comment by zadjii-msft** [comment]
Thanks for the request! There's a pretty good summary of this problem space over in https://github.com/microsoft/terminal/issues/4768#issuecomment-1527800607. Namely, I think this is a /dup #4768, which also is ultimately impossible for us to do.

 Conhost could successfully do this, but the taskbar basically ignores the icon of the HWND for _packaged applications_ (which terminal is), and always uses the icon from the package itself 😕
