### ISSUE TITLE
Bug Report: Write-Host -ForegroundColor Gray Outputs White Text

### ISSUE THREAD

**Issue by RatliffCam** [microsoft/terminal#1645]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]]
Windows Terminal version (if applicable): 0.2.1715.0

```

# Steps to reproduce

Write-Host -ForegroundColor Gray "Hello world!"

# Expected behavior

The console outputs "Hello world!" as gray text

# Actual behavior

The console is outputting "Hello world!" as white text

![image](https://user-images.githubusercontent.com/45764362/60197592-a7e04380-980d-11e9-99b6-b57195d1ace9.png)

**Comment by hanubeki** [comment]
May be #293 ?

**Comment by DHowett-MSFT** [comment]
Correct! #293.
