### ISSUE TITLE
Windows Terminal session log entires

### ISSUE THREAD

**Issue by matys1** [microsoft/terminal#16462]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Other Software

Some forum posts suggest that it's perhaps related to Visual Studio Code, but I wasn't able to find anything conclusive. VS Code version: 1.85.0.

### Steps to reproduce

Start my windows machine and launch Windows Terminal and these log entries will start appearing. I have VS Code installed but the log entries appear even when VS Code has not been launched.

### Expected Behavior

I don't want any automatic/random log entries littering my Windows Terminal session.

### Actual Behavior

```
09:55 C:\Users\myusername>
[main 2023-12-13T07:55:27.414Z] update#setState idle
[main 2023-12-13T07:55:30.670Z] WSL is not installed, so could not detect WSL profiles
[main 2023-12-13T07:55:57.439Z] update#setState checking for updates
[main 2023-12-13T07:55:57.631Z] update#setState idle
```

the last two log entries will keep getting re-logged every hour. this started happening a few weeks ago. before I never saw these log entries. I have never even used WSL. why do these log entries appear?

**Comment by DHowett** [comment]
Hey there! Thanks for filing.

It absolutely seems like this is a VS Code issue: https://github.com/Microsoft/vscode/issues/56833. They're looking for people who have the ability to reproduce it, so you may be able to help them out!

FWIW: If one of your startup scripts is launching code for any reason, even for checking the version number (or something), it could be attaching itself to whichever console session first interacted with it.

/dup https://github.com/Microsoft/vscode/issues/56833
