### ISSUE TITLE
New Feature Request: Be able to sort the Profiles list

### ISSUE THREAD

**Issue by Auto72** [microsoft/terminal#16464]
I would like to be able to sort the profiles list - in the Settings - using the drag and drop to move items, or using the arrows to move the items up and down in the profile list.

![1](https://github.com/microsoft/terminal/assets/52780377/19c0bee9-296a-4184-9747-0dea4bbaf176)

Thanks.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #8914.
