### ISSUE TITLE
Maximize window triggers "press any key" prompt

### ISSUE THREAD

**Issue by Vbgf** [microsoft/terminal#16473]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.3693

### Other Software

The command "timeout" embedded in windows.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/timeout

### Steps to reproduce

1. Open Windows Terminal
2. Type "timeout 30"
3. Maximize window (or Restore Down). Any method works - button, keyboard shortcut, etc.
4. Notice the timeout has stopped ticking and the command has exited

### Expected Behavior

Timeout timer should remain active and the program should continue operating.

### Actual Behavior

Timeout has stopped ticking and the command has exited.

**Comment by 237dmitry** [comment]
The same behavior also is in other terminal emulators, I tried in conhost.exe and alacritty.exe. This is rather issue of timeout.exe

**Comment by Vbgf** [comment]
> The same behavior also is in other terminal emulators, I tried in conhost.exe and alacritty.exe. This is rather issue of timeout.exe

Yeah, fair enough! I just tested it with cmd and powershell, the behaviour is the same. Weird how it works like that.

**Comment by ForNeVeR** [comment]
In the Windows Terminal (and generally ConPTY), it also gets terminated by any terminal resize event. That wasn't the case in conhost, but I assume it's because window resize in conhost isn't tied to the buffer resize.
