### ISSUE TITLE
Can't uninstall Console Host

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16483]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.2861

### Other Software

OS Build Version: 10.0.22621.2861.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce

Install Terminal.

### Expected Behavior

It should uninstall Console Host or at least give the option to uninstall Console Host.

### Actual Behavior

It didn't uninstall Console Host or at least give the option to uninstall Console Host.

**Comment by 237dmitry** [comment]
> It didn't uninstall Console Host or at least give the option to uninstall Console Host.

conhost.exe is the system console host and a part of Windows.

**Comment by skanda890** [comment]
But still, there should be a way to uninstall Console Host.

**Comment by DHowett** [comment]
Even when Windows Terminal is installed and enabled as the default console host, `conhost` still provides API support for all of the Windows Console APIs to applications running in service desktops, in other window stations, over SSH, over Telnet, and over the EMS serial console. It also provides API services to applications in detached sessions or with "hidden" consoles.

We are not going to remove it.

Why would you like to see it removed?

**Comment by 237dmitry** [comment]
> But still, there should be a way to uninstall Console Host.

What about tasks which are out of user's space? Set WT as default terminal application and forget about standard console.  Why does this app bother you so much? In my opinion it works pretty fine.

**Comment by skanda890** [comment]
> > But still, there should be a way to uninstall Console Host.
> 
> What about tasks which are out of user's space? Set WT as default terminal application and forget about standard console. Why does this app bother you so much? In my opinion it works pretty fine.

Because it is shown in this.

![image](https://github.com/microsoft/terminal/assets/99239826/e0ed4aeb-0cfe-4091-9457-c16c7229ab27)

**Comment by skanda890** [comment]
> Even when Windows Terminal is installed and enabled as the default console host, `conhost` still provides API support for all of the Windows Console APIs to applications running in service desktops, in other window stations, over SSH, over Telnet, and over the EMS serial console. It also provides API services to applications in detached sessions or with "hidden" consoles.
> 
> We are not going to remove it.
> 
> Why would you like to see it removed?

Because of that ( from a normal user ), it won't be used except as a terminal.

**Comment by DHowett** [comment]
Thanks for the input!

We won't be doing this. Sorry!
