### ISSUE TITLE
Request: Setting several font weights

### ISSUE THREAD

**Issue by SantosAlarcon** [microsoft/terminal#16481]
First of all, thank you for this amazing terminal. I really love it.

The topic is I want to have the possibility to **configure several font weights** at the same time on a profile, making possible to see text in *italic*, **bold**, and normal at the same time. 

Terminal emulators like Kitty, Alacritty and Wezterm have this feature. And I want to know when this feature will become possible.

**Comment by 237dmitry** [comment]
IMHO, this is the task of shells and applications. The terminal displays fonts the way you want.

![Screenshot 2023-12-17 143449](https://github.com/microsoft/terminal/assets/78153320/66511689-806a-40db-9f3d-597abc6f4ead)

**Comment by lhecker** [comment]
I'm not entirely sure what you mean. Could you link to documentation for any of the 3 terminals so I can check out what you meant?
