### ISSUE TITLE
Right clicking the Windows Terminal icon in the taskbar doesn't allow directly launching profiles like it used to.

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [microsoft/terminal#16491]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.3803

### Steps to reproduce

1. Open windows terminal
2. Right click it's icon in the task bar

### Expected Behavior

Previously there was a menu where you could launch any of your Windows Terminal profiles after right clicking the terminal icon in the taskbar. All of the options that were shown within windows terminal were shown in this menu:
![image](https://github.com/microsoft/terminal/assets/46269721/490af447-a12f-4c2b-9c4f-aa9fbe3259aa)

### Actual Behavior

But now, all I see is "Terminal"
![image](https://github.com/microsoft/terminal/assets/46269721/c9a3bad1-0866-4dc4-8017-eb8a4cfecb4f)

This feature was already implemented in previous versions of Windows Terminal, but it seems to have been reverted now, for some reason.

**Comment by zadjii-msft** [comment]
Here's a thought - does this happen on a cold launch of the Terminal/? (e.g. make sure to close all Terminal windows, then launch the terminal fresh) Or does this only happen after you've closed one terminal window, while the Terminal is still running? 

I bet this is a window refrigeration issue - it is on Windows 10, and jumplist code is in that part of the codebase

**Comment by ItsIgnacioPortal** [comment]
> does this only happen after you've closed one terminal window, while the Terminal is still running?

I've tested that now, and it doesn't seem to trigger the issue.

Oddly enough, the issue seems to be completely gone now. I'm still in the same Windows version, and the same Windows Terminal version (v1.18.3181.0). The only thing that's changed is that I upgraded some system dependencies:

- Microsoft Visual C++ 2021 Redistributable (x64) - v11.0.61030.0
- Microsoft Visual C++ 2021 Redistributable (x86) - v11.0.61030.0

- Microsoft Visual C++ 2015-2022 Redistributable (x64) - v14.38.33130.0
- Microsoft Visual C++ 2015-2022 Redistributable (x86) - v14.38.33130.0

- Microsoft Windows Desktop Runtime (x64) - v6.0.25.33020
- Microsoft Windows Desktop Runtime (x86) - v6.0.25.33020

- Microsoft Windows Desktop Runtime (x64) - v7.0.14.33020
- Microsoft Windows Desktop Runtime (x86) - v7.0.14.33020

- Microsoft Windows Desktop Runtime (x86) - v8.0.0.33101
- Microsoft Windows Desktop Runtime (x64) - v8.0.0.33101 

- Java 8 Update 391 (64-bit) - v8.0.3910.13
- Java 8 Update 391 - v8.0.3910.13

Now the launch options do show up correctly:
![2024-01-08 14_47_33-](https://github.com/microsoft/terminal/assets/46269721/84358d14-0837-4d90-b9d2-6b56a4952240)

**Comment by samlletas** [comment]
Leaving a comment here hoping to be useful in case someone faces this problem. In my case doing the following steps fixed it:

1. Open the terminal and add a new tab for each profile.
2. Go to the terminal settings and save (no need to change anything, just save).
3. Close the terminal.
4. The profiles should now be back in the taskbar right-click menu.

**Comment by jniggemann** [comment]
June 2026 and the issue is still present... luckily, samlletas has posted a workaround
