### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by khmakoto** [microsoft/terminal#1649]
# Environment

```none
Windows build number: 18912
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

1. Open the terminal in a profile that has acrylic background turn on.
2. Focus out of the app.
3. The acrylic background effect disappears.

# Expected behavior

The acrylic background effect should stay even when focused out of the terminal app.

# Actual behavior

The acrylic background effect disappears when focus is outside of the terminal app.

**Comment by DHowett-MSFT** [comment]
This is by design for how Acrylic works on windows. It's only allowed to be active on one toplevel window at a time. Sorry.
