### ISSUE TITLE
Line height input format didn't follow system locale

### ISSUE THREAD

**Issue by wicaksono** [microsoft/terminal#16499]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.2861

### Steps to reproduce

Open Terminal, go to Settings > Default > Appearance > Line height

### Expected Behavior

Decimal digit will separated by system locale (in my case is comma) and able to click up and down arrow.

### Actual Behavior

On my locale, the digits is separated by comma, but terminal is ignoring it and using dot. This is also makes me unable to click up and down arrow next to it.

**Comment by zadjii-msft** [comment]
Yep, we should fix that. Thanks!

**Comment by lhecker** [comment]
I was intending to change that input field to use a CSS line-height string so that it supports explicit "px" and "pt" suffixes. I wonder if it would be necessary to add an explicit unit selector as a GUI element... 🤔

**Comment by lhecker** [comment]
Oh I see now. The problem is that you're mistaking the placeholder string as a value. If you just type any number into the field you can use up/down perfectly fine:
![image](https://github.com/microsoft/terminal/assets/2256941/fc41e277-16ab-4f0a-ac5e-54a2c9feffe1)

**Comment by DHowett** [comment]
I suspect that it's not worth it to fix this as-is. Please feel to reopen it (or comment!) if you disagree.
