### ISSUE TITLE
`far` command doesn't launch Far Manager in PowerShell on Windows 10

### ISSUE THREAD

**Issue by jdrch** [microsoft/terminal#16496]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.19045.3803

### Steps to reproduce

1. Install Far Manager using the GUI .msi, selecting the `Path` features to be installed
2. Open Windows Terminal
3. Type `far`
4. Hit `Enter`

### Expected Behavior

Far Manager starts.

### Actual Behavior

Error message appears:

```
> far
far: The term 'far' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by o-sdn-o** [comment]
This may be related to #16226.

**Comment by jdrch** [comment]
> This may be related to #16226.

`cmd` throws an error message in response to `> far` too.

**Comment by 237dmitry** [comment]
I added alias for far.exe in powershell's profile:

```
Set-Alias -Name far  -Value "D:\bin\Far-3\.\far.exe"
```

**Comment by zcobol** [comment]
Installing `Far Manager` via `winget` doesn't add `far.exe` to user or system path variables:

```
PS C:\Users\zcobol> winget install --id FarManager.FarManager
Found Far Manager 3 [FarManager.FarManager] Version 3.0.6226
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.farmanager.com/files/Far30b6226.x64.20231214.msi
  ██████████████████████████████  12.9 MB / 12.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

Restart terminal and look for the command:

```
PS C:\Users\zcobol> gcm far.exe
Get-Command: The term 'far.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

This looks like a `Far Manager` installer bug!

**Comment by 237dmitry** [comment]
> This looks like a Far Manager installer bug!

I think it's more of a Windows tradition))
These directories were added to `%PATH%` automatically:

```powershell
PS >  $env:PATH.Split(';')
C:\Program Files\PowerShell\7
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\PowerShell\7\
C:\Users\<user>\AppData\Local\Microsoft\WindowsApps
```

**Comment by lexKaktus** [comment]
> I added alias for far.exe in powershell's profile:
> 
> ```
> Set-Alias -Name far  -Value "D:\bin\Far-3\.\far.exe"
> ```
Thanks a lot!!!
My version with the ability to open in the current directory and a fast text editor for the terminal

`#Open far  fix
function OpenFar {
    if ($args) {
        & "C:\Program Files\Far Manager\Far.exe" $args
    } else {
        & "C:\Program Files\Far Manager\Far.exe" $pwd $pwd
    }
}
function FarEdit{
    & "C:\Program Files\Far Manager\Far.exe" -e $args
}

Set-Alias -Name far -Value OpenFar
Set-Alias -Name edit -Value FarEdit`
