### ISSUE TITLE
Terminal Preview Icon doesn't show text "PRE" in the taskbar

### ISSUE THREAD

**Issue by Modern293** [microsoft/terminal#16500]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.22631.2861

### Steps to reproduce

Just open the terminal preview app

### Expected Behavior

![image](https://github.com/microsoft/terminal/assets/103506340/5d2a6348-e945-4ec7-bac4-ab138aa99908)

### Actual Behavior

It does nothing, only the app icon in the taskbar

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by zadjii-msft** [comment]
Previous discussion: https://github.com/microsoft/terminal/issues/15719#issuecomment-1637966094

> This is by design. Our icons don't have the text on them at smaller resolutions, because it ultimately made the icons too cluttered and hard to read.
> 
> I believe that 36px is the first size that includes the text: [`main`/res/terminal/images-Pre/Square44x44Logo.targetsize-36.png](https://github.com/microsoft/terminal/blob/main/res/terminal/images-Pre/Square44x44Logo.targetsize-36.png?rgh-link-date=2023-07-17T11%3A46%3A52Z)
> 
> Thanks!

/dup #6544
