### ISSUE TITLE
Scrollbar does not implement shift+click to jump to position

### ISSUE THREAD

**Issue by binki** [microsoft/terminal#16507]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.2283

### Steps to reproduce

1. Cause there to be many lines of output. For example, hold down the Enter key until the scrollbar handle is roughly 1/3 of the height of the terminal.
2. Shift-click on the scrollbar near the top of the scrollbar.

### Expected Behavior

The scrollbar handle should center itself where the mouse is (or go as close to it as possible if the mouse is too close to the top or bottom of the scrollbar for this to be possible). The scrolling should match this. Here is an example of the before and after from conhost:

conhost before: ![image](https://github.com/microsoft/terminal/assets/82626/d0118518-5f08-49a1-9a83-16f7c1f83dc9)

conhost after: 
![image](https://github.com/microsoft/terminal/assets/82626/868d336e-b585-49d5-93d0-ffe7c12624e2)

### Actual Behavior

The scrollbar acts as if I just clicked on it instead of shift-clicking on it. It goes up one page. See Terminal before/after:

Terminal before: 
![image](https://github.com/microsoft/terminal/assets/82626/8c2458b2-a6ec-4688-a9c8-4b0b28b78bb5)

Terminal after: 
![image](https://github.com/microsoft/terminal/assets/82626/34084316-2e9b-4871-9826-af0f52091773)

**Comment by zadjii-msft** [comment]
Huh, doesn't look like the new notepad does this either. I bet this is a XAML bug that needs to be filed upstream at https://github.com/microsoft/microsoft-ui-xaml/

I fully suspect this can be solved with like, custom templates or something, but it **should** be fixed upstream

**Comment by binki** [comment]
It works just fine in Explorer on 10.0.26016.1012, though. Isn’t that using the same toolkit these days?

**Comment by zadjii-msft** [comment]
Hey look at that, this is already on the WinUI repo: /dup https://github.com/microsoft/microsoft-ui-xaml/issues/2971
