### ISSUE TITLE
double command results when installing the oh-my-posh font

### ISSUE THREAD

**Issue by rifqiabd** [microsoft/terminal#16515]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Other Software

![image](https://github.com/microsoft/terminal/assets/47505440/38cdf7ee-45e4-4933-b1b4-4c5694b8a4c1)

### Steps to reproduce

when installing oh-my-posh font install

### Actual Behavior

result was multiplier

**Comment by zadjii-msft** [comment]
Windows doesn't ship a `sudo`. I'd suggest filing this on wherever you got sudo from - I suspect the bugged output is from however they're piping the output to the Terminal.
