### ISSUE TITLE
Windows Terminal rendering Cyrillic characters as (???) question marks in specific situations.

### ISSUE THREAD

**Issue by Vuizur** [microsoft/terminal#16519]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Other Software

Powershell Core 7.2.17
Powershell Locale (Get-WinSystemLocale): de-DE
Active code page: 850 (from chcp)

### Steps to reproduce

I have two simple programs, one in Python, one in Java, both encoded in Text files in UTF-8. 

Test.java contains:
```java
public class Test {
    public static void main(String[] args) {
        System.out.println("Hello!");
        System.out.println("Это тест");
    }
}
```

test.py contains:
```python
print("Это тест")
```

(Both are in a single folder with no other files.)
I execute the java file using `& "C:\Program Files\Java\jdk-21\bin\java.exe" Test.java`
I execute the Python file using `& C:/Python312/python.exe test.py`

### Expected Behavior

In both cases, I expect the string to be printed as it is in the source files. So 'Это тест'.

### Actual Behavior

However, executing the Python file prints:
```
Could not find platform independent libraries <prefix>
Это тест
```
So here it works flawlessly.

But executing the Java file gets the result:
```
Hello!
??? ????
```
For some reason, the Cyrillic characters get replaced by question marks here. When I use Intellij with its integrated console, the Cyrillic chars get printed correctly, so java should not be the source of error. (The java code can also print German umlauts like äö, but no Cyrillic chars.)
Both commands are executed in the same console, so it is a quite strange error.

**Comment by 237dmitry** [comment]
As a workaround, set system locale to utf8 (intl.cpl). All of console applications will be utf8.

pwsh 7.4.0
```powershell
PS > & {
          [console]::OutputEncoding.EncodingName
          [console]::InputEncoding.EncodingName
          cmd /c chcp
       }
Unicode (UTF-8)
Unicode (UTF-8)
Active code page: 65001
```
There are no problems at all. They can only occur in older applications from the times when developers used national text encodings to localize the GUI.

**Comment by Vuizur** [comment]
I used the official Windows settings https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8 to change it and it seems to work.

**Comment by Vuizur** [comment]
I see that you closed this, in my opinion it still would be nice to fix it, because for example people using Visual Studio code at schools or in workspaces won't be able to change the system encoding without admin rights, and changing the encoding is in beta and has been reportedly breaking some applications (for example some svn clients), so in some environments it might be impossible to change the encoding due to other software.

**Comment by zadjii-msft** [comment]
I mean, most correctly, apps should be calling [`SetConsoleCP`](https://learn.microsoft.com/en-us/windows/console/setconsolecp) if they're going to be writing text in a particular codepage to the console. Seems like python  just so happens to be doing the right thing here for you. Writing utf-8 bytes to a cp850 console is most certainly not going to just work 😄
