### ISSUE TITLE
Customization for "new tab" + button

### ISSUE THREAD

**Issue by arix00** [microsoft/terminal#16517]
# Description of the new feature/enhancement

I use duplicate tab alot and want to set the new tab button to use "duplicate tab" by default.

# Proposed technical implementation details (optional)
Add options in settings.json so we can change default behaviors for all 3(click/shift+click/alt+click). 

![snap1](https://github.com/microsoft/terminal/assets/15333224/22fe1131-8467-48aa-9d18-a2b877850df0)

**Comment by zadjii-msft** [comment]
note to self: you left the "spec" under https://github.com/microsoft/terminal/issues/445#issuecomment-1178864053
