### ISSUE TITLE
Ask Windows Terminal how to disable automatic update

### ISSUE THREAD

**Issue by thousmile** [microsoft/terminal#16523]
### Steps to reproduce

Ask Windows Terminal how to disable automatic updates, there are too many BUGs in the latest version. Can't use it at all! 1.18.x opened for the first time, and the air environment variable. Can't find a place to close

### Expected Behavior

aa

### Actual Behavior

aa

**Comment by zadjii-msft** [comment]
Can you please add the exact version number? We had a couple fixes for some environment variable issues earlier in 1.18 that we hotfixed in December. 

Could you elaborate on the exact issue you're seeing/? If you're seeing something we haven't seen before, I'd rather make sure the issue is tracked so we can fix it, rather than just disable updates entirely 😉

**Comment by thousmile** [comment]
@zadjii-msft 

This video is my operation Windows Terminal version 1.17.11461.0 and version 1.18.3181.0

When version 1.18.3181.0 is opened for the first time, it is a new environment, and the “go version” command configured in the environment variable cannot be executed. After passing the settings, in the new tab, you can execute the “go version” command

Version 1.17.11461.0 has no problems. You can also execute the “go version” command when opening it for the first time.

https://github.com/microsoft/terminal/assets/28520524/57abe296-5690-463d-8df9-51e4d2616b22

**Comment by zadjii-msft** [comment]
Huh. That's got shades of #16226 in it, but also, seems a bit different. In your case, you shouldn't really be _inheriting_ env vars from File Explorer. Very strange then that the first tab still uses a bad PATH, but the subsequent tabs get a working PATH. 

There might be a couple things at play here:
* Are you on Windows 10? If you are, does this repro if you make absolutely sure there are no other open Terminal windows or processes?
* What exactly is the difference in your PATH here? (e.g. share `$env:path` in both a broken tab and a working one)
* Does this repro if you launch `wt` from the Run dialog? (maybe there's something weird about the way the shell context menu entry invokes the Terminal)
