### ISSUE TITLE
deleting an mis-typed Ctrl-Char corrupts the prompt (minor issue, not really a bug)

### ISSUE THREAD

**Issue by Y0rg0** [microsoft/terminal#16526]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.19045.3803

### Steps to reproduce

I am used to close (Linux) terminals via Ctrl-D -- this does not work in Windows, so when I noticed this (my) error, I press backspace-key to delete this "^D" char from the input line.

### Expected Behavior

the original prompt gets restored, like:

C:\\>^D
(press backspace key)
C:\\>

### Actual Behavior

prompt shows:
C:

**Comment by j4james** [comment]
This sounds like issue #16356. I think it should already be fixed in the nightly build, [Windows Terminal Canary](https://github.com/microsoft/terminal#installing-windows-terminal-canary).
