### ISSUE TITLE
Open a profile from the command pallet (ctrl+shift+P).

### ISSUE THREAD

**Issue by alanlivio** [microsoft/terminal#16528]
# Description of the new feature/enhancement

In a scenario of a user has a long list of profiles, it is useful to search and open a profile name from the command pallet (ctrl+shift+P).

**Comment by zadjii-msft** [comment]
You can already do this - they're listed under the "New Tab..." command.

The docs also include a command you can add to the palette that will auto-expand to New Tab actions for each of your profiles: https://learn.microsoft.com/en-us/windows/terminal/command-palette#example

**Comment by alanlivio** [comment]
Hi @zadjii-msft. Thanks for your time and answer. 

Indeed It works but it requires two searches and one navigation: one search to find "New tab", nagitate and select and then search again. See the images below.

![Screenshot 2024-01-05 163742](https://github.com/microsoft/terminal/assets/604808/d60fb74a-b88b-4d1e-aca8-59ed4955a6dc)
![Screenshot 2024-01-05 163755](https://github.com/microsoft/terminal/assets/604808/e90b31b3-540e-4078-9bd6-69ff4a80b2cf)




It will be much more convenient a direct search. Something like below:

![image](https://github.com/microsoft/terminal/assets/604808/1ece3bf6-34c5-4b17-82e8-b6d834eb35ac)

**Comment by zadjii-msft** [comment]
Sure - you're free to add the aforementioned command to your own settings if that's your preference. We decided against including that originally, because for the folks with tons and tons of profiles, we didn't want a huge pile of profiles cluttering that list.
