### ISSUE TITLE
"clear" does not clear the terminal

### ISSUE THREAD

**Issue by Y0rg0** [microsoft/terminal#16524]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.19045-3803

### Steps to reproduce

1. open the Terminal
2. type any command that produces output in the terminal - e.g. a simple "dir" or "cd C:\" will do
3. type "clear" to clear the terminal

### Expected Behavior

"clear" to _always_ clear the previous output...

### Actual Behavior

cursor will be positioned at the top of the inner window, but the previous output still is visible below
(this does not happen all the time, but mostly)

**Comment by Y0rg0** [comment]
This problem only occurs when the mentioned output only fills the screen partly, e.g. by just typing "cd" -- which typically only produces one or two lines of output; if I do a "dir" instead which fills the whole terminal window, "clear" always works...This is for normal CMD shell.Gesendet von Outlook für Android

**Comment by Y0rg0** [comment]
see attached screen-recording (archive contains .mp4 video recorded by OBS). 
    
    
   
   
   
     Mike Griese ***@***.***> hat am 04.01.2024 15:51 CET geschrieben: 
    
   
       
    
   
       
    
     
   Hmm. I can't seem to repro this. Do you have any more detailed repro steps? How are you launching the Terminal? What shell are you using (PowerShell? CMD? Bash/zsh/fish/etc)? Do you have anything in your shell settings/profile that might be at play here? Something that attempts to resize the window perhaps?

**Comment by Y0rg0** [comment]
ok, that attachment didn't make it to the mailing list via e-mail it seems; retrying it from github directly...

[2024-01-04 16-15-41.zip](https://github.com/microsoft/terminal/files/13832042/2024-01-04.16-15-41.zip)

**Comment by zadjii-msft** [comment]
huh. Where did you get `clear` from/? That's not a built-in CMD intrinsic like `cls` is, and there isn't a `clear.exe` that ships inbox.

**Comment by 237dmitry** [comment]
What is `clear`? What about to use `cls` ?

```
 C:\> clear
'clear' is not recognized as an internal or external command,
operable program or batch file.

 C:\> where clear.*
INFO: Could not find files for the given pattern(s).


```

**Comment by Y0rg0** [comment]
C:\Users\uid65368>where clear
C:\Program Files\Git\usr\bin\clear.exe

excellent find - and "cls" works better -- thank you :)

**Comment by zadjii-msft** [comment]
Yep, that makes sense. Thanks for following up!

**Comment by Y0rg0** [comment]
to my defense :-)
I work in Windows and Linux, so I am used to use commands that work in both universes:
"clear" does this (normally...), but "cls" is not known in Linux...
