### ISSUE TITLE
save all console tabs and splits to text file so when re-run the app it will load all the content from previous session

### ISSUE THREAD

**Issue by or-katz** [microsoft/terminal#16527]
# Save all console tabs and splits to text file so when re-run the app it will load all the content from previous session

In addition to the feature "When Terminal starts -> Open windows from a previous session" add the option to save all the content and load it again on the next run of the Windows Terminal. the same as in Edge or Google Chrome.
🙏

**Comment by zadjii-msft** [comment]
> the same as in Edge or Google Chrome

Sorry, could you clarify what this setting/feature is called in Edge/Chrome? I was under the impression that the Terminal's "Open windows from a previous session" is basically the same as the feature in Edge/Chrome. Could you elaborate how that feature _doesn't_ already cover what you're looking for?

**Comment by j4james** [comment]
@zadjii-msft I suspect what they're wanting is for the buffer content of each tab to be restored (#961). What we do now is more like a web browser restoring the URLs for each tab, without reloading the page.

**Comment by zadjii-msft** [comment]
Oh welp yea that makes more sense 🤦 I suppose I still have holiday brain. That's much more obvious after re-reading it. Thanks for the clarification ☺️ 

/dup #961

**Comment by or-katz** [comment]
> @zadjii-msft I suspect what they're wanting is for the buffer content of each tab to be restored (#961). What we do now is more like a web browser restoring the URLs for each tab, without reloading the page.

exactly!
