### ISSUE TITLE
With terminal set to maximum, move to botton of terminal cann't bring-up auto hided taskbar

### ISSUE THREAD

**Issue by alvin08s** [microsoft/terminal#16538]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. set win11 taskbar wo auto hide
2. open window terminal, set to maximum
3. move mouse to the botton, the taskbar can not be bring up

### Actual Behavior

This leads very very very inconvenient to use

**Comment by lhecker** [comment]
This indeed seems very similar to #5782. I'll close this issue as a duplicate then.
/dup #5782

**Comment by alvin08s** [comment]
> This indeed seems very similar to #5782. I'll close this issue as a duplicate then. /dup #5782


? this issue is still exist, my display is EIZO

**Comment by alvin08s** [comment]
> This indeed seems very similar to #5782. I'll close this issue as a duplicate then. /dup #5782

This problem is particularly annoying. When working on multiple tasks, the terminal is always unable to wake up in full screen mode, which makes it impossible to switch to other tasks quickly.

**Comment by lhecker** [comment]
I also think it's annoying (although I'm not affected by it), it's just that I can't really argue with the explanation given [here](https://github.com/microsoft/terminal/issues/5782#issuecomment-625224968) and [here](https://github.com/microsoft/terminal/pull/4857#issue-578211070).
@zadjii-msft Do you have any additional input?
