### ISSUE TITLE
Add support for resetting tab stops (DECST8C)

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#16533]
# Description of the new feature/enhancement

[`DECST8C`](https://vt100.net/docs/vt510-rm/DECST8C.html) is an escape sequence which resets the tab stops to their default values, i.e. every 8 columns. It's especially useful for a modern terminal because it's the only practical way to restore the default values over an "infinite" width. Without this you'd have to set the positions manually, which limits you to the current screen width (technically you could also perform a hard reset with `RIS`, but that's not something an application should be doing).

# Proposed technical implementation details (optional)

We actually already have a method in `AdaptDispatch` that performs a tab reset (it's used in the hard reset implementation). We just need to make it public, and hook it up to the relevant escape sequence in the state machine.

It's a little bit more complicated than I'm making out, because the escape sequence takes a parameter value, and `DECST8C` is only applicable for one specific value, but that's easy enough to handle.

**Comment by ClaireCJS** [comment]
I have my own internal notation i use, but i just used tab stops today for the first time and they worked....

I basically cleared all tab stops, moved to column 7, set one there, and then the colortool.exe char aligned properly (column 1 waqs the only one with variable-width values in it to screw up tabbing)
![image](https://github.com/user-attachments/assets/7d65f694-b2fa-457f-8b53-9fe543af1510)

**Comment by j4james** [comment]
@ClaireCJS If you wanted to reset all the tab stops to the default 8 column spacing (which is what colortool is really expecting), you could also just use `echo %ESCAPE%[?W` (that's the `DECST8C` sequence that we added here).
