### ISSUE TITLE
Support local profile settings (non-roaming)

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#1654]
# Summary of the new feature/enhancement

Add support for two sets of profile settings:
- (existing) roaming
- (new) local, ie non-roaming

As it is today, Windows Terminal profile settings roam between machines, which can cause undesired profiles to show up in machines where their commands do not apply.

For example, I have a devbox and a laptop. I've created a command profile in my devbox that only apply to the devbox itself since it starts a particular batch file to configure the development environment; in my laptop I do not have the necessary files that are invoked by that profile. Yet, the profile replicated and shows up in the laptop.

# Proposed technical implementation details (optional)

A solution for this might be to support different sets of profiles.
In addition to the roaming profile we could add support for a local profile.
Windows Terminal would then merge the two files at runtime.
With this, common commands, such as cmd/powershell/bash would live in the roaming file and machine-specific commands would live in the local file.

While at this, we might want to allow this local profile to live in a place easier to remember, like the user's home directory.

**Comment by DHowett-MSFT** [comment]
We've got some settings changes in the works here, actually, as part of #754. Would youi mind adding your request there? There's a specification in review at #1258 that will be setting our settings plan for the future.
