### ISSUE TITLE
Incorrect font characters rendered after running simple terminal stress program for a long time

### ISSUE THREAD

**Issue by Treit** [microsoft/terminal#16543]
### Windows Terminal version

1.19.3172.0

### Windows build number

10.0.26020.0

### Steps to reproduce

Run the [TerminalStress](https://github.com/microsoft/terminal/blob/main/src/tools/TerminalStress/Program.cs) program in a pane and let it run for a long time (for instance, overnight.)

The next morning, press ctrl+C.

Type something like "cd c:\"

Notice that it is actually rendered in the terminal as:

```
cd c:Ö
```

### Expected Behavior

Running a program that prints lots of random stuff to the terminal should not affect how characters are rendered after the program quits.

### Actual Behavior

Certain characters are now rendered incorrectly. For instance, typing the following sequence:

```
~@|\[]{}
```

is now displayed as:

```
ß§ÄÜäüöÖ
```

**Comment by DHowett** [comment]
Honestly, this is probably VT character sets getting activated!

![image](https://github.com/microsoft/terminal/assets/189190/e3b316aa-b281-4e52-a408-8eabb05aefaf)

**Comment by DHowett** [comment]
There's a [whole bunch of them supported by `SCS`](https://vt100.net/docs/vt510-rm/SCS.html), FWIW, in case those glyphs don't look like the ones you're seeing.

Printing out unguarded escape sequences can always leave your terminal in a weird state!
