### ISSUE TITLE
Box cursor does not invert the foreground color of the character

### ISSUE THREAD

**Issue by nbjk667** [microsoft/terminal#16541]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Go to Settings -> Profiles -> Defaults -> Appearance -> Cursor
2. Switch "Cursor shape" to "Filled box"
3. Go back to the application and type any text
4. Move cursor back using arrow keys so that it appears over one of the entered characters

### Expected Behavior

I would expect the cursor to invert both Background and Foreground colors of the character so that the character is still readable when the cursor is over it.

### Actual Behavior

The background changes color to white but the character remains yellow, making it unreadable.

![image](https://github.com/microsoft/terminal/assets/8071945/a34f7e2b-98f0-4b3e-8f10-a49d65bd7c93)

**Comment by lhecker** [comment]
Enable "AtlasEngine" in your "Rendering" settings and restart Windows Terminal.
Please let me know if that fixes your issue. 😊

**Comment by nbjk667** [comment]
Hello! Enabling AtlasEngine fixes the issue!
