### ISSUE TITLE
Tab characater rendering doesn't align well.

### ISSUE THREAD

**Issue by yslib** [microsoft/terminal#16556]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.23612.1000

### Other Software

ArchWSL
Oh-My-Zsh Configure
Hack Nerd Font

### Steps to reproduce

Rendering some nerd glyphs or tab characters in WT. Both in default text engine and AtlasEngine

### Expected Behavior

These Hack Nerd Font glyph should be aligned in any scaling.

### Actual Behavior

When using small zooming scale in Windows Terminal, the corner tab character appears in the panel border (ohmyzsh powerline10k prompt, lazygit panel or neovim panel) seems not aligned well compared to the same glyph rendering in Alacritty.

At small scaling
![image](https://github.com/microsoft/terminal/assets/9605622/b0e6c9ae-0280-411f-97ad-3123861e2a67)
![image](https://github.com/microsoft/terminal/assets/9605622/21aa4cb9-45d1-47d2-ab5c-30a45359a8bf)

But at relatively large scaling, it's ok
![image](https://github.com/microsoft/terminal/assets/9605622/7f834c8a-c4ce-4eea-adc0-580ff1ee8d3d)

In Alacritty, the same glyph works well for any scaling
![image](https://github.com/microsoft/terminal/assets/9605622/90268e85-9d6d-4d71-ae94-8e10d78222b0)
![image](https://github.com/microsoft/terminal/assets/9605622/6922d9f9-7334-444c-8fac-1d274dc6f382)
![image](https://github.com/microsoft/terminal/assets/9605622/27f4ab63-04d2-44d0-a270-7bb78bdb8daa)

The p10k theme prompt rendering in alacritty is better than it in WT, but it still not as perfect as it in real Linux.

**Comment by lhecker** [comment]
Thanks for the report! We're already aware about this issue and are tracking it here: #5897
We haven't gotten to addressing it yet unfortunately. 😓 The shift at smaller sizes occurs due to hinting (to make the font crispier when it doesn't perfectly align with the pixels). Fixing it requires drawing our own custom box drawing glyphs.

/dup #5897
