### ISSUE TITLE
ctrl+shift+c and ctrl-d shortcuts do not work in WSL2

### ISSUE THREAD

**Issue by muellerst-hg** [microsoft/terminal#16551]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.3803

### Other Software

WSL Debian

### Steps to reproduce

Open WSL terminal
Selected text
Press `ctrl-shift-c`
Paste text into terminal
-> Result: no text is not copied

Using `ctrl-c works`

Same for `ctrl-d`:
Open WSL terminal
Press `ctrl-d`
-> Result: nothing happens

### Expected Behavior

`ctrl-shift-c` copies a selected text 
`ctrl-d` exits the terminal

### Actual Behavior

`ctrl-shift-c` does not copiy a selected text 
`ctrl-d` nothing happens

**Comment by muellerst-hg** [comment]
wsl --version
WSL-Version: 2.0.14.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.3803

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/? 

Are you running anything in WSL other than just your default shell? (bash/zsh/whatever)? Ultimately, that shell is supposed to be the one to handle Ctrl+D, but the Ctrl+Shift+C _should_ be handled by the Terminal.

Actually come to think of it... what shell are you using?

**Comment by muellerst-hg** [comment]
> Are you running anything in WSL other than just your default shell? (bash/zsh/whatever)? Ultimately, that shell is supposed to be the one to handle Ctrl+D, but the Ctrl+Shift+C _should_ be handled by the Terminal.
> 
> Actually come to think of it... what shell are you using?

bash.

I tried to use ctrl-shift-c in powershell: same issue

The shortcuts worked before, then suddenly vanished.

[settings.json](https://github.com/microsoft/terminal/files/13899262/settings.json)

**Comment by zadjii-msft** [comment]
Huh, curious. I'd usually expect the user settings to include at least

```json
    "actions":
    [
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },
        { "command": "find", "keys": "ctrl+shift+f" },
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
```

But yours doesn't have any `actions` at all. That's totally fine, so long as that was intentional. 

Maybe there's something else curious going on, where the Terminal thinks that <kbd>shift</kbd> is in the opposite of it's actual state. As if <kbd>caps lock</kbd> was pressed or something. 

Does adding the 

```json
    "actions":
    [
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" }
    ]
```

binding at least fix `ctrl+shift+c` to copy/?

**Comment by muellerst-hg** [comment]
> Does adding the
> 
> ```json
>     "actions":
>     [
>         { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" }
>     ]
> ```
> 
> binding at least fix `ctrl+shift+c` to copy/?

copying with `ctrl+c` works after adding the above lines. I also added `ctrl+shift+x` and it works. Tested on powershell as well as wsl bash.

Any idea what might interfere the shortcuts?

**Comment by muellerst-hg** [comment]
I used [debug-tap](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#enabling-the-debug-tap) to see if keystrokes are captured 

```
␛[16;42;0;1;16;1_␛[16;42;0;0;0;1_␛[O
* `␛[16;42;0;1;16;1_␛[16;42;0;0;0;1_␛[O`
  * `Vk`: VK_SHIFT
  * `Sc`: 42
  * `Uc`: 0
  * `Kd`: down`
  * `Cs`: 16
␛[17;29;0;1;8;1_␛[17;29;0;0;0;1_␛[O
* `␛[17;29;0;1;8;1_␛[17;29;0;0;0;1_␛[O`
  * `Vk`: VK_CONTROL
  * `Sc`: 29
  * `Uc`: 0
  * `Kd`: down`
  * `Cs`: 8
␛[67;46;99;1;0;1_c␛[67;46;99;0;0;1_␛[O
* `␛[67;46;99;1;0;1_c␛[67;46;99;0;0;1_␛[O`
  * `Vk`: C key
  * `Sc`: 46
  * `Uc`: 'c'
  * `Kd`: down`
  * `Cs`: 0
```

To me this reads as if all three keystrokes are received from the terminal

**Comment by muellerst-hg** [comment]
I found the reason and I cannot resist to blame Cisco Webex client for inappropriate behaviour, capturing keystroke combinations in a selfish way.

**Comment by DHowett** [comment]
_A-ha!_ Thanks - that'll also help future searchers stumble on this issue. :smile:
