### ISSUE TITLE
wt won't run elevated from the Run dialog via Ctrl+Shift+Enter

### ISSUE THREAD

**Issue by happybear88** [microsoft/terminal#1655]
# Environment
Windows build number:  [Version 10.0.18362.207] 
Windows Terminal version: latest from the store

# Steps to reproduce
1. Press Win+R -> enter **wt** -> press Ctrl+Shift+Enter

# Expected behavior
UAC prompt, if UAC is on. Otherwise, WT runs elevated (high integrity level).

# Actual behavior
WT runs non-elevated (medium integrity level)

# Notes
Other apps run elevated from Win+R, e.g. cmd
The Run dialog supports Ctrl+Shift+Enter starting with 1803

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, a shell bug. We're following this dependency internally.
