### ISSUE TITLE
Weird interaction with git add -p and Notepad++ (git hangs)

### ISSUE THREAD

**Issue by klylesatepic** [microsoft/terminal#16553]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19044.3803
10.0.22621.2861

### Other Software

Git (both versions 2.42.0.windows.2 and 2.43.0.windows.1)
Notepad++ (version 8.6)

### Steps to reproduce

1. Open Git Bash in Windows Terminal
2. Navigate to a git repository
3. Make changes in at least two separate places in a file
4. Run `GIT_EDITOR='"C:\Program Files\Notepad++\notepad++.exe" -multiInst -notabbar -nosession -noPlugin' git add -p` to interactively stage parts of the file
    - Obviously you will need Notepad++ installed, and you may need to adjust the path to it
6. Type e to edit the first hunk (Notepad++ will open)
7. Make whatever change you like within one of the new lines (starting with a plus)
8. Save and close Notepad++
9. See that git moves on and prompts for the next hunk
10. Try to type n to skip the next hunk (or anything else)
11. See that git is stuck (Ctrl+C won't interrupt it)

The same issue happens with `git add -i` instead of `git add -p`, but requires more steps between steps 4/5.

The issue does not happen if any of the following are true:

- You use vanilla Git Bash instead of Git Bash in Windows Terminal
- You only edit the last hunk
- You use a terminal editor instead of Notepad++ (I tried vim and nano)
- You use /c/Windows/System32/notepad.exe instead of Notepad++
  - The bug still happens if you just use 'notepad', which is a shell script in Git Bash located at /usr/bin/notepad

### Expected Behavior

Step 9 above would echo the character you typed, and git would not get stuck.

### Actual Behavior

The character(s) you type are not echoed, nothing happens even after also pressing Enter, and even Ctrl+C will not interrupt git.

If you kill the git process with Task Manager, you do come back to a seemingly-working terminal.

**Comment by carlos-zamora** [comment]
Thanks for filing! If you run `conhost -- c:\Program Files\Git\bin\bash.exe -l -i` from the Run dialog, does this reproduce the problem? Whether it reproduces in this scenario will help determine if this happens in the standard windows console vs WT.

**Comment by klylesatepic** [comment]
That does reproduce the issue.  Everything seemed to work exactly the same way as in (Git Bash in) Windows Terminal.

**Comment by DHowett** [comment]
_Excellent!_ Thanks for testing.

It looks like it's an msys2 (Cygwin) issue -- if it reproduces in the built-in Windows Console, it is likely to be something that they're doing differently in their mintty terminal integration versus their console integration. It may be worth filing a bug report on them. 🙂
