### ISSUE TITLE
Unexpected new window opening when trying to split the pane of a window in Administration mode

### ISSUE THREAD

**Issue by StevenBucher98** [microsoft/terminal#16562]
### Windows Terminal version

 1.20.10101.0 also in 1.18.3181.0

### Windows build number

10.0.22635.0

### Other Software

PowerShell 7.4.1

### Steps to reproduce

1. Open WT as administrator 
2. run `wt -w 0 sp`
3. New window opens instead of split pane in the same current window 

### Expected Behavior

After I run `wt -w 0 sp` a new split pane is opened in the same window

### Actual Behavior

New Window is opened
![screenshot](https://github.com/microsoft/terminal/assets/20605456/a6935b3a-c063-47c6-8d53-716778fe1a27)

**Comment by carlos-zamora** [comment]
Thanks for filing! We're actually going to mark this as a /dup of #9628
