### ISSUE TITLE
Duplicate Terminal window opens when the system reboots

### ISSUE THREAD

**Issue by forzafedor** [microsoft/terminal#16561]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Go to Settings
Set 'Launch on machine startup'
Reboot the system without closing Terminal window

### Expected Behavior

When the system starts, the previous session will be launched

### Actual Behavior

When the system starts, two duplicate Terminal of the previous session are launched

**Comment by zadjii-msft** [comment]
I need to go dedupe the set of  
* #16487
* #16557
* #16561

**Comment by zadjii-msft** [comment]
Just to double check here: Is "When terminal starts" set to "Open windows from a previous session" in the settings/? I'm guessing that there's a bug somewhere here with "Launch on machine startup" and restoring windows, but I just want to be totally sure

**Comment by zadjii-msft** [comment]
Actually also, do you have the Terminal set as the default terminal emulator?

**Comment by zadjii-msft** [comment]
You know what, this is sufficiently the same as #16487 so I'm gonna dedupe there. The other info I asked for though (default terminal emulator, session restore setting) would still be helpful info to add to that thread. Thanks! 

/dup #16487
