### ISSUE TITLE
Terminal session history

### ISSUE THREAD

**Issue by Soneji** [microsoft/terminal#16569]
# Description of the new feature/enhancement

As we all know, in windows, you have to restart often. When I restart my system, all my terminal panes and layout is maintained, however the content in those panes is lost. 

I am proposing a feature in windows terminal to maintain this terminal history, as a bonus the session state could also be saved, e.g. the path in which the shell is currently in. 

The retention of the terminal history can help me restore each pane to the correct place and easily pick up where I left off. 

Is it worth noting I am using WSL 2, I am not sure if some of these features already exist with powershell. 

# Proposed technical implementation details (optional)

I guess there are two ways this could be implemented 
1. Save the terminal history and shell session to a temp file on shutdown
2. Periodically save the terminal history and shell session to a temp file on the system

**Comment by j4james** [comment]
If by history you mean the buffer contents/scrollback, that feature request is tracked in issue #961.

As for saving the current directory, that should already be possible if you've configured your shell appropriately (there's a tutorial [here](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory#configure-your-shell)).

**Comment by zadjii-msft** [comment]
Yep, that's correct. There's also the [`firstWindowPreference`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/startup#behavior-when-starting-a-new-terminal-session) setting, to enable bringing your windows back to the right position, with the same tabs & panes. Of course, you'll also want to do the aforementioned shell integration, to let Terminal know about the CWD. 

![image](https://github.com/microsoft/terminal/assets/18356694/0c331656-c175-4ed7-ac95-899df3d9898e)


/dup #961 for the rest of "restore the buffer contents"
