### ISSUE TITLE
Windows terminal crash

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#16573]
### Windows Terminal version

 1.18.3181.0

### Windows build number

10.0.22631.0

### Other Software

Custom application

### Steps to reproduce

Unclear - still under investigation.  Possible that application is experiencing OOM exception or generating large amounts or console  output

### Expected Behavior

Application should be terminated but terminal should keep running

### Actual Behavior

We use Windows Terminal to spawn a number of powershell scripts in separate terminal processes.   (The "master" script that does this simply invokes...  `Start-Process -windowstyle normal powershell -ArgumentList $arglist`)

The poweshell scripts run some custom CLI commands periodically (i.e. they run the command then sleep for a few hours).  

This results in a  number of tiled windows....
![image](https://github.com/microsoft/terminal/assets/9131337/85a7800a-8a9a-4275-b4f7-77ab8711693c)

Recently we have found instances where Terminal appears to crash in a way that the entire process is killed - i.e,. all spawned windows disappear.  The trigger appears to be a fault in one of the CLI applications (possibly out-of-memory) but we would expect the behaviour in this case for the _application_ to be killed, not the entire Terminal process.   (Happy to close though if this is "expected" behaviour.)

Unfortunately we don't have a lot of post-mortem information at this time... EventLog shows an Application Error for Terminal...
```
Faulting application name: WindowsTerminal.exe, version: 1.18.2311.14001, time stamp: 0x6553b19e
Faulting module name: ntdll.dll, version: 10.0.22621.2506, time stamp: 0xbced4b82
Exception code: 0xc0000409
Fault offset: 0x00000000000a7d18
Faulting process ID: 0x0x5714
Faulting application start time: 0x0x1DA491FE3458FB2
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 2082cf3e-3952-4061-bfe1-e6bc7aa7bef6
Faulting package full name: Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by NeilMacMullen** [comment]
Hmm - I can't find a "bucketid" anywhere but in case it's helpful here are a couple more reports of what look like the problem....
```

Faulting application name: WindowsTerminal.exe, version: 1.18.2311.14001, time stamp: 0x6553b19e
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000c5d2eff8a8
Faulting process ID: 0x0x63D4
Faulting application start time: 0x0x1DA4ABDD38785BE
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: unknown
Report ID: 0cb28a16-b300-490e-84b2-69e2eacda35f
Faulting package full name: Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

```
Faulting application name: WindowsTerminal.exe, version: 1.18.2311.14001, time stamp: 0x6553b19e
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000005dd9cff238
Faulting process ID: 0x0x66C
Faulting application start time: 0x0x1DA485787FEEE27
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: unknown
Report ID: 53e775d3-23ed-4aab-ad06-2c591707647a
Faulting package full name: Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

```


Unfortunately I haven't yet found a way to reliably reproduce this on demand but will continue investigating.

**Comment by zadjii-msft** [comment]
We've got a theory here that this might be the same thing that #16575 is supposed to fix. We're planning on merging that and quickly pushing an updated build Soon<tm>. We should be able to give you a build with some fixes and tease out if that's the actual same root cause or not.

**Comment by NeilMacMullen** [comment]
Interesting.   In typical fashion the system has now been running fine for 4 days without re-exhibiting the problem after I added extra diagnostics to try and track down the precipitating event.   I couldn't quite follow the discussion in the referenced bug but looks like this is triggered by a (heavily multi-threaded ?) app crash?  That might well be consistent with what we're doing.

**Comment by zadjii-msft** [comment]
If this is cool with you, I'm gonna close this out for housekeeping. If you ever see it again, we can always reopen ☺️

**Comment by zadjii-msft** [comment]
Gotcha. Okay I'll reopen then. The 1.19 Stable release should have that fix in it - lmk if it comes back? (or, I'll have the bot re-close if it has just gone away ☺️ )

**Comment by NeilMacMullen** [comment]
Great - I've upgraded to Windows Terminal Preview Version: 1.20.10303.0.   Fingers crossed it's gone away but if not I'll dig in a bit further and let you know of any evidence I can collect.
