### ISSUE TITLE
Text copying does not work

### ISSUE THREAD

**Issue by Protey** [microsoft/terminal#16576]
### Windows Terminal version

1.18.3181.0

### Windows build number

22H2 19045.3930

### Steps to reproduce

In CMD, when selecting text, the selection is immediately reset, that is, there is no way to copy the text with the right mouse button, Shift+Ctrl+C, Ctrl+C do not work.
BUT, in the standard CMD everything works, even the selection via SHIFT + arrows on the keyboard works!!!

### Actual Behavior

In CMD, when selecting text, the selection is immediately reset, that is, there is no way to copy the text with the right mouse button, Shift+Ctrl+C, Ctrl+C do not work.
BUT, in the standard CMD everything works, even the selection via SHIFT + arrows on the keyboard works!!!

**Comment by zadjii-msft** [comment]
Could you maybe grab a screen recording of what you're describing? (ScreenToGif is excellent for this). 

Does this repro in tabs for other shells (e.g. powershell) in your Terminal?

Have you made any changes to your settings? If so, 
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by Protey** [comment]
> Не могли бы вы сделать запись экрана того, что вы описываете? (ScreenToGif отлично подходит для этого).

I apologize for creating a topic about the problem in vain, and maybe not in vain))
When recording the problem on video, I found out why I had this problem, the qTranslate program was to blame.
The problem can be solved by adding Windows Terminal to the qTranslate program exception

**Comment by zadjii-msft** [comment]
Thanks for following up! Hopefully someone else in the future is able to find this helpful 😄
