### ISSUE TITLE
Can not reset/reinstall Windows Terminal

### ISSUE THREAD

**Issue by ktzsolt** [microsoft/terminal#16571]
### Windows Terminal version

1.18.31.81.0

### Windows build number

10.0.19045.0

### Steps to reproduce

My profiles are not working I get only basic PS prompt, when I try to launch the wsl profile I even get
```
[process exited with code 3221225495 (0xc0000017)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

I tried to repair, reset and even reinstall Windows Terminal, even though with uninstall it's directory `C:\Users\myuser\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe` is deleted  but when I install it again the settings.json is recreated and it will miraculously contain my previous settings.json that I have no idea where it gets from. I even restarted the computer after uninstalling and before reinstalling, still the same.

I also did a `winget install --id Microsoft.Powershell --source winget` before today, maybe this messed up things somehow? Had no issues before with this.

### Actual Behavior

Not working as intended

**Comment by ktzsolt** [comment]
I started "C:\Program Files\PowerShell\7\pwsh.exe" from start run, and after that Terminal started to work again as it should. Strange.

**Comment by carlos-zamora** [comment]
That error code indicates that you might be out of memory. Glad the issue went away. Let us know if the issue comes back.

**Comment by ktzsolt** [comment]
I doubt, I have 32 GB RAM and also I restarted the computer multiple times. What finally solved is that I started pwsh.exe from start menu, run. Maybe it's installation/setup/bootstrap didn't finished until I started it manually?
