### ISSUE TITLE
"Run as administrator" on exe file doesn't open Windows Terminal

### ISSUE THREAD

**Issue by viocha** [microsoft/terminal#16583]
### Steps to reproduce

right click an exe file, then click "Run as administrator "
![run as admin](https://github.com/microsoft/terminal/assets/66580331/eb54bd2f-62a5-4abb-8afc-c26668c1d477)

### Expected Behavior

the console should be opened in Windows Terminal

### Actual Behavior

it would be opened in Windows Console Host

**Comment by slycordinator** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> 
> ### Open similar issues:
> * [Can't run Windows Terminal without Administrator (#13197)](https://github.com/microsoft/terminal/issues/13197),  similarity score: 0.85
> 
> ### Closed similar issues:
> * [Can't start Windows Terminal as administrator (#4693)](https://github.com/microsoft/terminal/issues/4693),  similarity score: 0.84
> * [Option to run administrator terminal on Windows Terminal (#8727)](https://github.com/microsoft/terminal/issues/8727),  similarity score: 0.82
> * [Can't use win terminal without running it as admin (#14608)](https://github.com/microsoft/terminal/issues/14608),  similarity score: 0.80
> * [Terminal crashes when trying to run it as administrator from a non administrator windows user (#9584)](https://github.com/microsoft/terminal/issues/9584),  similarity score: 0.79
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

None of those are related. This is about the action of running executables and whether they execute inside Windows Terminal vs the console host.

**Comment by zadjii-msft** [comment]
Yea you're right, the bot couldn't find /dup #10276.

> Due to a limitation in the app platform it is impossible for Terminal to be "discovered" as the handler when the application that needs a terminal is running elevated

**Comment by ewwink** [comment]
> Yea you're right, the bot couldn't find /dup #10276.
> 

3 (three) years and still not fixed, do we need 3 more years?
why still not fixed? 
Do you think Terminal are for "kids" so admin right not needed?
