### ISSUE TITLE
addiing support for undercurls.

### ISSUE THREAD

**Issue by chadjaa-sofiane** [microsoft/terminal#16580]
I currently use NeoVim and find it underwhelming that the Windows terminal has no support for **undercurls**. 
**Undercurl** is an essential part of any IDE or Editor that indicates the exact location of the error.
I spent too much time configuring and styling my terminal and so far I like it, I don't wanna switch to another one just for **undercurls**.
this is a small feature and I hope you can add it ASAP.
thanks.

**Comment by bogdan-calapod** [comment]
Isn't this already supported by https://github.com/microsoft/terminal/issues/7228 ? I see that the PR for this has been merged, so we're just waiting for a release (sometime in February from what I can gather from the roadmap)

**Comment by zadjii-msft** [comment]
Yep, this was /dup #7228 which was added in #15795, which looks like it's already in 1.19 [Preview](https://aka.ms/terminal-preview)
