### ISSUE TITLE
Can't have more than 5 profiles in the dropdown menu.

### ISSUE THREAD

**Issue by lancerts** [microsoft/terminal#16591]
### Other Software

The same [issue](https://github.com/microsoft/terminal/issues/6771) seems persist till now? On windows 11

### Steps to reproduce

NA

### Actual Behavior

NA

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

The last time we saw this, someone had the same `guid` for their profiles, so the Terminal treated all of them as the same.
