### ISSUE TITLE
Bug Report - Dropdown panel stays in the same position when the window is moved

### ISSUE THREAD

**Issue by JushBJJ** [microsoft/terminal#1659]
# Environment

```none
Windows build number: [10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
Chrome
```

# Steps to reproduce

Press the down arrow in the UI which will trigger the dropdown panel:
material. -->
![image](https://user-images.githubusercontent.com/36951064/60221613-a706ea80-98bd-11e9-9e13-0d67360d8df0.png)
Drag the window around the screen while the dropdown panel is open and you will see the panel staying in place. Instead of following the window.

# Expected behavior

The dropdown bar follows the window.

# Actual behavior

The dropdown panel stays in the same place.

**Comment by DHowett-MSFT** [comment]
This is known / something I don't think we can easily fix. #1070
