### ISSUE TITLE
New tab action use current working directory of current tab

### ISSUE THREAD

**Issue by ibuildthecloud** [microsoft/terminal#16590]
# Description of the new feature/enhancement

What I would like is that when I'm in a terminal and I initiate the "new tab" action the new tab that is launched is launched with the current working directory of the old tab.  More specifically the following should work:

1. Open Linux terminal
2. Run `cd /tmp`
3. Type `ctrl+shift+t` (this is my keybinding for "new tab" action)
4. New tab is launched and my prompt is at `/tmp`

I'm coming from linux and this is the default behavior of xfce4-terminal and I believe many other terminals. 

# Proposed technical implementation details (optional)

Sorry, don't know how the internals work.

**Comment by zadjii-msft** [comment]
Might I recommend: [Tutorial: Opening a tab or pane in the same directory in Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory)?

**Comment by ibuildthecloud** [comment]
Wow, hacky but works. Took me longer than I care to admit to understand what was going on, but I'll take it.  It does seem like WSL itself could emit this information itself and not require the prompt hack.

The difference between duplicate and new tab seems nuanced. I just rebound the new tab shortcut to duplicate. I didn't know duplicate existed and that's honestly what I want 99% of the time. If I'm in powershell I don't expect a new linux terminal (the default for me) so duplicate seems like a better default behavior for new tab anyhow.

**Comment by ibuildthecloud** [comment]
FWIW, I did try to google for a solution to this before I opened this issue and couldn't really find it, but that documentation was helpful. Thanks.

**Comment by notrealdev** [comment]
Hi @zadjii-msft 

I went to that link and I still don't understand how I can create a new tab with the current link
For example: I am on path `D:\Code>` when new tab opens it is another path `C:\Windows\system32>`
How can I configure it so that every time I open a new tab, it gets the correct current folder value?

Check my image:

![Image](https://i.imgur.com/X7kKg9o.png)
