### ISSUE TITLE
Bold text appears wider than regular text when using the Light and SemiLight variants

### ISSUE THREAD

**Issue by CutterXYZ** [microsoft/terminal#16609]
### Windows Terminal version
1.18.3181.0

### Windows build number
10.0.19045.3996

### Other Software

Tested in Eclipse IDE and Notepad++, with the latest version of Cascadia Code available (.ttf version).

### Steps to reproduce

1. Launch Eclipse
2. Go to Window > Preferences. Then General > Appearance > Colors and Fonts. Select category Basic > Text Font, click "Edit..." and set the font to Cascadia Code SemiLight.
3. Display text with mixed weights (for example with emphasized keywords).
4. Notice bold text is wider than regular text.

### Expected Behavior

Bold text and regular text should appear monospaced.

### Actual Behavior

Bold text is wider than regular text (see screenshot).
![image](https://github.com/microsoft/terminal/assets/29694177/173d959f-4762-4b8e-9758-64ba7d6d2c6a)

In MS Word, there is no difference in width, but bold SemiLight text is rendered strangely:
![image](https://github.com/microsoft/terminal/assets/29694177/17ff374f-b215-4bcf-921a-79971bbd9d69)

**Comment by lhecker** [comment]
Good news! If you open the "Rendering" settings you can enable "AtlasEngine". That is our new text renderer and it fixes issues like this one. It'll be enabled by default starting 1.19.

Please let me know if the new text renderer has any bugs, or if it fails to fix this issue.

**Comment by CutterXYZ** [comment]
Sorry this issue was meant to be posted in the Cascadia Code repo.

**Comment by lhecker** [comment]
Oh, I see now. I thought you accidentally wrote Eclipse in the "Steps to reproduce" to describe a way to see how it's supposed to look. But I realize now that "Actual Behavior" isn't `vim` or similar. Sorry about that. 😅 Yeah, the Cascadia Code repo will be a better place for this.
