### ISSUE TITLE
Colorful output with user defined tyext pattern

### ISSUE THREAD

**Issue by SigmaStar** [microsoft/terminal#16604]
# Description of the new feature/enhancement

I hope terminal can equipped with function that can colorized some text which user defined in settings.json. 
For example in settings.json user can write some PCRE2 pattern like "ERROR \b\w+\b" and set the text color to red. Then as soon as ERROR something appeared on terminal, the terminal output the text in red color.

# Proposed technical implementation details (optional)

maybe add some hooks on output? But will this cause performance impact for user?

**Comment by SigmaStar** [comment]
Maybe we can reuse the function " auto detect url"?

**Comment by lhecker** [comment]
We're tracking something like this over at #5916. Please let me know if your idea is different from what's described there. Otherwise, I believe we can close this issue as a duplicate. 🙂

**Comment by SigmaStar** [comment]
oh, yes! this is a duplicated issue.

**Comment by SigmaStar** [comment]
I've closed
