### ISSUE TITLE
Background image repeat tiling setting

### ISSUE THREAD

**Issue by naukatti** [microsoft/terminal#16614]
Would it be possible to get a background image repeating/tiling setting? I want to use an image that creates a pattern when repeated.

Maybe something like kitty's config setting [background_image_layout](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.background_image_layout)

Thanks <3

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3193 for more discussion.

/dup #3193
