### ISSUE TITLE
wrong order in right click context menu

### ISSUE THREAD

**Issue by PitchAbyss** [microsoft/terminal#16616]
even though i have placed profiles differently my right click context menu shows wrong order of profile please help

![Screenshot_3](https://github.com/microsoft/terminal/assets/13099434/55ece69a-b6d7-427f-9a8a-5144cd5af8c1)
![Screenshot_2](https://github.com/microsoft/terminal/assets/13099434/a25a8fc9-e412-48fd-99f3-094c54e00c1f)

**Comment by zadjii-msft** [comment]
How did you add profiles to your right click context menu/? I'd suggest filing this issue with them - Terminal's context menu doesn't have nested profiles in it yet 😉

**Comment by PitchAbyss** [comment]
> How did you add profiles to your right click context menu/? I'd suggest filing this issue with them - Terminal's context menu doesn't have nested profiles in it yet 😉 

My friend did it for me i dnt know how i think it was a script

**Comment by zadjii-msft** [comment]
Then I'd report this bug to your friend's script 😜
