### ISSUE TITLE
easy-rsa hangs on windows terminal, works in old cmd.exe

### ISSUE THREAD

**Issue by unchartedxx** [microsoft/terminal#16619]
### Windows Terminal version

1.18.3181.0 (stable)
1.19.3172.0 (preview)

### Windows build number

Windows 11  22631.3007 

### Other Software

Easy-RSA 3.1.7

### Steps to reproduce

1. Download and extract somewhere latest release: https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.7/EasyRSA-3.1.7-win64.zip  (NB: it didn't work even in some old release.)
2. Open a terminal into that folder
3. Call `EasyRSA-Start.bat`
4. Call `./easyrsa` (works on both terminal, WT and cmd.exe)
5. Call `./easy-rsa help renew`

### Expected Behavior

It shows the help related to the renew command. 

### Actual Behavior

WT is stuck and doesn't progress. 

### Additional notes

At the moment, the workaround is to go into settings and set to use the classic command line. Fortunately I got that from this issue on their tracker https://github.com/OpenVPN/easy-rsa/issues/1049 , where there are some additional info.

**Comment by Zeroes1** [comment]
under win10 and last canary build WT all ok for me...

**Comment by unchartedxx** [comment]
I tried the new preview release from few hours ago (1.20.10293.0) and it seems to work now. So, some recent commit fixed the issue. Great!

**Comment by JLJTGR** [comment]
Good to hear that it might be fixed on this side.  (soonish)
