### ISSUE TITLE
[1.19] Pasting a file from explorer into the Terminal no longer pastes the path (regression from 1.18)

### ISSUE THREAD

**Issue by 0017031** [microsoft/terminal#16627]
### Windows Terminal version

1.19.240129002

### Windows build number

10.0.19045.3930

### Other Software

no

### Steps to reproduce

copy a file from the File Explorer (a file object, not text), and then paste it into Windows Terminal

### Expected Behavior

In version 1.18.240129001 of Windows Terminal, it can display the path of the pasted file.

### Actual Behavior

In 1.19, and 1.20 of Windows Terminal, nothing is shown.
(copy/paste normal text is OK)

**Comment by 0017031** [comment]
This feature of paste is quite convenient. Could you please bring it back?

**Comment by zadjii-msft** [comment]
Huh, I never knew that worked! We'll look into it 😄

**Comment by lhecker** [comment]
We could also make it possible to paste multiple file paths in the future by unifying the code that handles drag & drop and the code that does Ctrl+V. Iterating through an `HDROP` with `DragQueryFileW` is quite simple thankfully. We should consider doing that in the future if we need to touch this code again!
