### ISSUE TITLE
Upgrade from 1.19.10292.0 to 1.20.10293.0  created new settings.json. Old settings lost !?

### ISSUE THREAD

**Issue by ato2** [microsoft/terminal#16630]
### Windows Terminal version

1.20.10293.0

### Windows build number

10.0.19045.0

### Steps to reproduce

winget install Microsoft.WindowsTerminal.Preview

### Expected Behavior

Config backup or preservation

### Actual Behavior

Old config missing in $HOME\AppData\Local\Packages\Microsoft.WindowsTerminalPreview*\LocalState\settings.json

**Comment by DHowett** [comment]
The preview version of Terminal stores settings in a different place than the stable version, because they may be incompatible and refer to preview-only features. 1.19 is the current Stable version. 1.20 is the current Preview version.

You can copy the settings from the Stable version yourself. They are stored at `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`.

**Comment by ato2** [comment]
Thx, but my 19 version was prewiev not stable.  Before upgrade:
  winget list Microsoft.WindowsTerminal
  Name                      Id                                Version     Available    Source
  -------------------------------------------------------------------------------------------
  Podgląd Terminalu Windows Microsoft.WindowsTerminal.Preview 1.19.3172.0 1.20.10293.0 winget

Installers should always preserve user modified config files (or backup them) as it is typical on Linux package managers.

**Comment by ato2** [comment]
My 19 version was prewiev not stable. Before upgrade:
      winget list Microsoft.WindowsTerminal 
      Name                                     Id                                                    Version         Available       Source
      -----------------------------------------------------------------------------------------------------
     Podgląd Terminalu Windows   Microsoft.WindowsTerminal.Preview 1.19.3172.0 1.20.10293.0 winget

IMHO Installers should always preserve user modified config files (or backup them) as it is typical on Linux package managers.
