### ISSUE TITLE
Bug Report : Crashing of Terminal

### ISSUE THREAD

**Issue by Rajat-Gupta-11605708** [microsoft/terminal#1663]
I started building the New Windows 10 Terminal via cloning it from Github, found some basic UI/UX bugs like **dragging the Terminal Windows doesn't works**.

Than I downloaded the Windows Terminal - Preview from Microsoft Store recently. 
and found some of these bugs

1. Dragging Terminal Window still doesn't works from it's head left to the drop down button, but it works from the right side of the drop down button.
2. Changed defaultProfile to that of "cmd" i.e "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}" in my case. **But when I close Terminal by it's close button, it closes immediately, but when I close it by closing the cmd window by clicking on the Close Button on cmd Tab, it crashes.**

![Screenshot (13)](https://user-images.githubusercontent.com/37516416/60235730-5e9ffa80-98c6-11e9-84f6-cc7cc82954a4.png)
![Screenshot (14)](https://user-images.githubusercontent.com/37516416/60235731-5f389100-98c6-11e9-834a-ff2740d33be8.png)
![Screenshot (15)](https://user-images.githubusercontent.com/37516416/60235732-5f389100-98c6-11e9-8a2f-cb03e4a534f6.png)

**Comment by miniksa** [comment]
1. This is a dupe to #564.
2. I cannot reproduce this issue.
