### ISSUE TITLE
Clicking on settings menu is not showing up settings.

### ISSUE THREAD

**Issue by puzits** [microsoft/terminal#1664]
# Environment
Windows 10

```none
Windows build number:  Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):  0.2.1715.0


# Steps to reproduce

Clicking on Settings menu not opening settings.

# Expected behavior

Settings window or tab or any action should happen to view the current settings. 

# Actual behavior

Nothing happens.
<!-- What's actually happening? -->

**Comment by markSmurphy** [comment]
I have this issue too, but on my machine choosing _Settings_ opens `profiles.json` in Visual Studio 2017

**Comment by schorrm** [comment]
Oh -- I had this, try opening any random JSON file -- once you have a default JSON editor, then it'll open

**Comment by zhou12315** [comment]
schorrm is right,
default application ----> specify the default application by file type--->find .json --->set default editor.

**Comment by JushBJJ** [comment]
The path of the file was referenced in #1460

**Comment by DHowett-MSFT** [comment]
This is also a duplicate _of_ #1460.
