### ISSUE TITLE
Dead keys + space bar not working through ssh or in wsl 2

### ISSUE THREAD

**Issue by Meryl** [microsoft/terminal#16642]
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.22631.0

### Other Software

Bash, either in WSL 2 or through SSH on debian-based OS's (tested on Debian, Ubuntu and RasberryPi OS Bookworm)

### Steps to reproduce

* Use a keyboard layout that uses dead keys (e.g. US International)
* Press a "dead key" (e.g. `'`)
* Press the space bar

### Expected Behavior

The corresponding character to appear (e.g. an apostrophe)

### Actual Behavior

Only a space character appears.

**Comment by Meryl** [comment]
I think this may be related to #16641

**Comment by j4james** [comment]
@Meryl Yeah, sorry about this. It's the same underlying cause.

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by para28711** [comment]
urueurrhhrjr
