### ISSUE TITLE
ComboBox menu does not obey to terminal theme settings

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/terminal#16640]
### Windows Terminal version

1.18.3181.0

### Windows build number

22621

### Steps to reproduce

1. Set windows theme to light theme
2. Set terminal theme to dark theme
3. Open any ComboBox in settings page, observe it's in light theme

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/42881734/e61ac423-40ed-47ae-b3a2-1665d4c69d7e)

**Comment by llxlr** [comment]
Try to update to version 1.19 ?

**Comment by HO-COOH** [comment]
> Try to update to version 1.19 ?

Nope
![image](https://github.com/microsoft/terminal/assets/42881734/67ea023e-1094-4738-9472-459708b7404d)

**Comment by llxlr** [comment]
You're right. Maybe wt has a bug in dark and legacyDark theme.

**Comment by zadjii-msft** [comment]
Yep this is pretty trivially reproducible. This is the same category of 100 bugs we've had before: anything that's a "popup" is technically not parented to our XAML root, so we need to _manually_ re-apply the theme to it. 

Oh look there actually is a dup on the backlog! /dup #15428
