### ISSUE TITLE
Caret (`^`) key on French (Canada) keyboard does not work in 1.20

### ISSUE THREAD

**Issue by phil-blain** [microsoft/terminal#16649]
### Windows Terminal version

1.20.10293.0

### Windows build number

10.0.19045.0

### Steps to reproduce

- Switch keyboard layout to ["French (Canada) - Canadian Multilingual Standard"](https://learn.microsoft.com/en-us/globalization/keyboards/kbdcan)
- Open Terminal Preview (1.20)
- Type the key to the right of the `P`, which is `^` on physical "French (Canada)  Canadian Multilingual Standard" -  keyboards, or `[` on US keyboards
- Type `Space`

### Expected Behavior

A caret (`^`) character appears on the command line.

### Actual Behavior

A space appears instead.

**Notes**: 
- It also happens with the older ["French (Canada) - Canadian French Keyboard"](https://learn.microsoft.com/en-us/globalization/keyboards/kbdca)
- It also happens with my custom layout based on "French (Canada) - Canadian Multilingual Standard"
- I did not find other keys that do not work correctly since I upgraded a couple days ago.

P.S. So glad to finally be able to double click long paths that wrap and have the whole thing selected !!

**Comment by lhecker** [comment]
Thanks for the report! I'll be closing this in favor of #16641 which describes the same underlying cause. /dup #16641

**Comment by phil-blain** [comment]
Thanks! I did read that issue but I was not sure it was related as in my case `AltGr` is not involved.
