### ISSUE TITLE
Window does not stay on top when "Always on top" is enabled

### ISSUE THREAD

**Issue by jessemaurais-seequent** [microsoft/terminal#16650]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.3007

### Steps to reproduce

Enable the "Always on top" setting.
Open a window to an application which is not supposed to stay on top.
Move the new window to overlap with Windows Terminal

### Expected Behavior

Terminal to stay on top

### Actual Behavior

Terminal goes under the other window.
![Screenshot 2024-02-01 125719](https://github.com/microsoft/terminal/assets/82827657/20ec5a64-3d5b-489b-b09d-699e5bda67e0)

**Comment by zadjii-msft** [comment]
Just so I'm absolutely clear - You enabled that setting, _then_ hit save, right/? 

Does the "Toggle always on top" action in the command palette keep the Terminal on top of other windows?

After enabling that toggle, then saving, does it immediately take effect (yes/no)? Does it take effect on a "cold" launch of the Terminal after enabling that setting?

**Comment by jessemaurais-seequent** [comment]
Not only did I save it, I had been using the app with the setting enabled successfully for some time. It just stopped working one day. It had been working on restart as well. When it stops working, if I disable & save, then enable & save, it begins working again.

**Comment by gerbuuu** [comment]
When you drag and drop the Tab, it starts working...
