### ISSUE TITLE
Preview_1.20.10303.0_x64, vim and nano, Keyboard Numeric keypad, not working.

### ISSUE THREAD

**Issue by k9fvm** [microsoft/terminal#16658]
### Windows Terminal version

WindowsTerminalPreview_1.20.10303.0_x64.zip

### Windows build number

10.0.22631.0

### Other Software

vim 9.1
nano 7.2

### Steps to reproduce

WindowsTerminalPreview_1.20.10303.0_x64.zip
Extract the file.
Create the file .portable in the folder.
Using ssh --> Linux, or Using msys2.
Open vim or nano.

### Actual Behavior

vim: 
Keyboard Numeric keypad , 'Numpad_3' and 'Numpad_9' , not working.
nano:
 Keyboard Numeric keypad ,  ALL Numpad , not working.

**Comment by k9fvm** [comment]
There are similar issues when using Putty to remotely connect to Linux.

However, Putty provides an option to solve the problem.

Putty Terminal ->Features ->**Disable application keypad mode**.

I couldn't find a similar option in WindowsTerminal.

**Comment by k9fvm** [comment]
There are similar issues when using Putty to remotely connect to Linux.

However, Putty provides an option to solve the problem.

Putty Terminal ->Features ->Disable application keypad mode.

I couldn't find a similar option in WindowsTerminal.

**Comment by dziban303** [comment]
This is happening to me too. I'm also on 1.20.10303.0_x64. In any linux session I start, the numeric keypad keys try to do functions instead of write numerals when in `nano`, but functions normally at the command line. Powershell or cmd sessions work normally.

**Comment by j4james** [comment]
See issue https://github.com/microsoft/terminal/issues/16654#issuecomment-1925438704.
