### ISSUE TITLE
Glitchy behavior of acrylic tabrow

### ISSUE THREAD

**Issue by eddiezato** [microsoft/terminal#16661]
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Click outside the terminal window to make it lose focus.
Then click on the terminal window again to regain focus.

### Actual Behavior

The acrylic tabrow can't remain transparent. Random glitches occur with opaque color.

[t.webm](https://github.com/microsoft/terminal/assets/11173476/695d070f-f2ca-46ef-a056-6128a7084bf2)

### In addition

v1.18.3181.0 worked fine.

**Comment by carlos-zamora** [comment]
Thanks for reporting this. Acrylic in the tab row has definitely caused us trouble in the past. We think this is fixed in the canary channel of the insider program, so the fix should be publicly available at some point soon. Thus, closing.
