### ISSUE TITLE
Running batch files as admin opens them in Windows Console Host instead of Windows Terminal even when Windows Terminal is selected as the default terminal application

### ISSUE THREAD

**Issue by parvinderandroid** [microsoft/terminal#16666]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.3085

### Steps to reproduce

Step 1. Create this batch file:

    @Echo off
    echo Hey
    pause

Step 2. Right click on batch file
Step 3. Click on "Run as administrator"
Step 4. Click "Yes" on the elevation prompt

### Expected Behavior

Batch file opens in Windows Terminal

### Actual Behavior

Batch file opens in Windows Console Host

**Comment by zadjii-msft** [comment]
Thanks for filing this! Basically, we've been tracking this in #10276. The way the default terminal setting works is based off Packaged COM. Unfortunately, Packaged COM still doesn't work for our needs in an elevated context.

Till then, follow /dup #10276
