### ISSUE TITLE
Hotkey profile signature does not disappear after unbinding

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#16662]
### Windows Terminal version

1.19.10302.0

### Windows build number

22631.3085

### Steps to reproduce

Remove the bind to the terminal profile and open tabmenu

### Expected Behavior

The signature next to the profile name disappears

### Actual Behavior

The signature next to the profile name does not disappear
![image](https://github.com/microsoft/terminal/assets/35394377/edd97bba-2e17-4008-b54d-fc08c3746db4)
![image](https://github.com/microsoft/terminal/assets/35394377/6d47dd0d-044e-4bcf-970f-fbced046e761)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13943 for more discussion.

/dup #13943

**Comment by Mystic8b** [comment]
Yes, but already 2 years)

**Comment by zadjii-msft** [comment]
You're very welcome to submit a PR to fix it if you'd like 😉
