### ISSUE TITLE
Resizing sometimes make links unclickable

### ISSUE THREAD

**Issue by applesarefum** [microsoft/terminal#16676]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22621.3007

### Other Software

PowerShell 7.4.1

### Steps to reproduce

Enter a command that contains or will output a link. 
Resize the terminal window.
Hover over the link.

### Expected Behavior

An underline should appear and the link should still be clickable.

### Actual Behavior

The underline may not appear and the link may not be clickable.
This behavior can be remedied easily by scrolling in the terminal or entering some input.

**Comment by timelmer-uw** [comment]
This also seems to be triggered by the terminal window losing focus.
