### ISSUE TITLE
Spaces in commandline path

### ISSUE THREAD

**Issue by taschemann** [microsoft/terminal#16674]
### Windows Terminal version

1.18.231114001

### Windows build number

10

### Steps to reproduce

I'm trying to load a custom PowerShell profile that is stored in %OneDrive%, but the path to OneDrive contains multiple spaces in it and I can't figure out how to escape the spaces, even when I spell the path out and explicitly escape them. This is my employer's setup, so the path can't be changed and I can't put the PowerShell profile in a different location. Is it possible to load the profile with Windows Terminal? Can I escape the spaces somehow?

### Expected Behavior

I want to use `powershell.exe -File %OneDrive%/path/to/profile.ps1` and have the profile load, whether there are spaces in the path or not.

### Actual Behavior

PowerShell doesn't start because the path can't be traversed properly.

**Comment by zadjii-msft** [comment]
What's the `commandline` set to in your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

I'd expect something like 

```json
"commandline": "powershell.exe -File \"%OneDrive%/path/to/profile.ps1\""
```

to work well enough. The inner quotes _should_ get stripped out as `CreateProcess` passes that arg to `powershell.exe`, so it should just receive that as a single arg

**Comment by zadjii-msft** [comment]
Huh. Weird. Admittedly, I don't have the same `%onedrive% env var set up, but I tried with 

```json
            {
                "name": "gh-16674",
                "commandline": "PowerShell.exe -File \"%userprofile%\\OneDrive - Microsoft\\Documents\\PowerShell\\gh-16674.ps1\""
            },
```

(where `%userprofile%` is set to `c:\users\migrie`)

and that works just fine. Maybe the %onedrive% variable has another set of quotes already inside it? That would be... kinda weird, but might explain this
