### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/terminal#16677]
# Description of the new feature/enhancement

Microsoft Windows operating systems have always had great l10n support for the Czech language. Sadly, it seems that the Czech translation is still completely missing in Windows Terminal. Please consider translating Windows Terminal into Czech. Thanks!

**Comment by para28711** [comment]
Stephen f Balogh

**Comment by para28711** [comment]
🖕🏿

Stephen Balogh reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by para28711** [comment]
🖕🏾

Stephen Balogh reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by para28711** [comment]
🖕🏽

Stephen Balogh reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by para28711** [comment]
🖕🏼

Stephen Balogh reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by para28711** [comment]
🤌🏿

Stephen Balogh reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by zadjii-msft** [comment]
I'm gonna dupe this out to #10667 - we're planning some work to allow community translations beyond the set of languages that we can get the Terminal automatically translated into. Thanks!

/dup #10667
