### ISSUE TITLE
Latest Windows Terminal Canary build installed via AppInstaller does not run on Windows 23620+

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/terminal#16689]
### Windows Terminal version

1.21.138.0

### Windows build number

10.0.23620.0

### Steps to reproduce

1. Install Windows Terminal Canary using AppInstaller from https://aka.ms/terminal-canary-installer on Windows build 23620
2. Attempt to launch Windows Terminal Canary

### Expected Behavior

Windows Terminal Canary runs

### Actual Behavior

When launched from the Taskbar or Start Menu, nothing happens.

When launched manually in Explorer from `C:\Program Files\WindowsApps\Microsoft.WindowsTerminalCanary_1.21.381.0_arm64__8wekyb3d8bbwe`, running `WindowsTerminal.exe` results in:

![image](https://github.com/microsoft/terminal/assets/33820650/a65bdf9e-2afc-4713-bb45-1fabafa8277c)

**Comment by sirredbeard** [comment]
Can confirm issue occurs in build 22635.3140 as well.

**Comment by elsaco** [comment]
The portable builds work:

![canary_portalbe_latest](https://github.com/microsoft/terminal/assets/3933920/46fb3433-365a-46ad-86d5-923d75b9b5db)

**Comment by sirredbeard** [comment]
Good to know, thank you @elsaco.

**Comment by carlos-zamora** [comment]
Thanks for filing. We're tracking this internally with MSFT:48456582.

**Comment by zadjii-msft** [comment]
We're pretty sure the fix for this went out in April. Thanks!
