### ISSUE TITLE
Caret becomes invisible when i "type" specific file

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#16697]
### Windows Terminal version

1.19.10292.0

### Windows build number

10.0.22631.3007

### Steps to reproduce

1. Run type docking_log.txt

[docking_log.txt](https://github.com/microsoft/terminal/files/14229075/docking_log.txt)

### Expected Behavior

caret is visible

### Actual Behavior

Caret disappears.
![image](https://github.com/microsoft/terminal/assets/8822292/b9ca29b7-d128-4b5b-b05a-38055a80b13a)

It happens in legacy console too.
![image](https://github.com/microsoft/terminal/assets/8822292/914d1a4b-3aae-40be-a96e-bcb96f267f1b)
Wsl too.
![image](https://github.com/microsoft/terminal/assets/8822292/c870f112-5590-483d-996c-127bebed6772)

**Comment by j4james** [comment]
On line 61, just after the text "Starting docking engine...", you can see the escape sequence `^[[?25l`. That is telling the terminal that it should hide the cursor, but there is no follow up escape sequence to make it visible again. So this is working as expected - the terminal is just doing what you've asked it to do.

**Comment by zadjii-msft** [comment]
Yep
