### ISSUE TITLE
Sleep and Windows Updates automatic restart hold

### ISSUE THREAD

**Issue by Sarisan** [microsoft/terminal#16692]
# Description of the new feature/enhancement

I have some server software in WSL that must always be running. I would like to have an option in Terminal that prevents my system from sleep and automatic restart for update. I can't always monitor my system to prevent those manually.

**Comment by zadjii-msft** [comment]
You'd probably be interested in [PowerToys Awake](https://learn.microsoft.com/en-us/windows/powertoys/awake) then!

**Comment by Sarisan** [comment]
> You'd probably be interested in [PowerToys Awake](https://learn.microsoft.com/en-us/windows/powertoys/awake) then!

I would if it was separated from PowerToys and had condition to be only enabled when Windows Terminal is running.
