### ISSUE TITLE
Issue in Open External Terminal

### ISSUE THREAD

**Issue by khadkasimon** [microsoft/terminal#16698]
### Steps to reproduce

Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

https://github.com/microsoft/terminal/assets/10781554/77ae888e-3068-4ef4-92f6-8cde49170e07

### Actual Behavior

Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

https://github.com/microsoft/terminal/assets/10781554/3b3d5cfb-76ed-404e-9536-64cdcf611def

**Comment by lhecker** [comment]
Hey! Can you please fill out the "Windows Terminal version" and "Windows build number" fields in the bug form?

Additionally, I'd need your `terminal.external.windowsExec` setting in VS Code (if it exists). If your Windows Terminal version is less than 1.19, please try updating it, rebooting your machine and trying it again.
