### ISSUE TITLE
conhost with raster fonts: chcp 65001 breaks rendering of box-drawing characters

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#16701]
### Windows Terminal version

d3a18b9

### Steps to reproduce

* Print box-drawing characters
* chcp 65001 -> It worky :)
* Ctrl+Scroll -> It no worky :(

### Expected Behavior

This behavior is sus and I feel like this may not be a limitation in GDI. The ASCII characters all still work and the font doesn't actually change at all when you Ctrl+Scroll. `LOGFONTW` has a code-page field and we probably do something wrong there, _or_ the .fon files have some weird logic that makes box-drawing glyphs code-page dependent. 🤔

In any case, we probably shouldn't treat 65001 as any old code page and instead use the CP_ACP instead.

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/2256941/e142721a-eb99-42f8-a3ab-3b29f2c7df28)

![image](https://github.com/microsoft/terminal/assets/2256941/f690cb3d-25ad-41ce-a10f-dee1d584fd2d)

**Comment by lhecker** [comment]
Weird... I can't reproduce this issue on my other machine that uses a public Windows build, even though I'm using the latest conhost from `main`.

**Comment by zadjii-msft** [comment]
![Image](https://github.com/microsoft/terminal/assets/18356694/d0264c1f-ade8-44cf-8706-ec3f8f8c5ed6)

Just tried this in the conhost straight off the current GE builds:

```
chcp 65001
type d:\dev\utf-8-test.txt
```

then ctrl+scroll, and it worked fine?

**Comment by lhecker** [comment]
It only happend with raster fonts. But I can't reproduce it anymore either so I'll close this.
