### ISSUE TITLE
Bug Report: Ctrl-W for cut not working in Emacs in Ubuntu-Terminal

### ISSUE THREAD

**Issue by utsavm9** [microsoft/terminal#1670]
# Environment

```none
Windows build number: Version 10.0.18362.175
Windows Terminal version (if applicable): Version 0.2.1715.0

Any other software?
Ubuntu 18.04.2 LTS in WSL
GNU Emacs 25.2.2
```

# Steps to reproduce

* I open a file with Emacs in Ubuntu from Windows Terminal.
* I select a block of text by setting a Mark with Ctrl-Space and then pressing Up arrow key.
* I press Ctrl-W to cut text.

# Expected behavior

The block of text to be cut, as it does in Ubuntu WSL.

# Actual behavior

- When WSL Ubuntu is the only tab open:
  - `DesktopWindowsXamlSource` window shows up in taskbar for a second, and then Terminal crashes and that window closes.
- When another tab is also open:
  - WSL Ubuntu tab just closes. The other tab remains open.

**Comment by WOo0W** [comment]
![image](https://user-images.githubusercontent.com/24245520/60275150-069bdf00-992c-11e9-9c4c-42335dfd1c15.png)
You can try to change this to another hotkey in config file. By default, ctrl+w means to close the tab.
