### ISSUE TITLE
maximize inserts extra empty lines

### ISSUE THREAD

**Issue by 3052** [microsoft/terminal#16703]
### Windows Terminal version

terminal-1.19.10302.0

### Windows build number

10.0.18363.0

### Steps to reproduce

take this file:

https://github.com/microsoft/terminal/files/14251165/hello.txt

open terminal, and move it to half the screen with Windows+Left or Windows+Right. print file:

~~~
Get-Content hello.txt
~~~

notice because of the line width, the rows wrap around:

> ![wrap](https://github.com/microsoft/terminal/assets/147215885/ef142ed1-a5f6-4e4c-b527-63f971557598)

you might need to reduce window width further depending on monitor/font size. the above is expected, but I would assume that maximizing the window fixes the problem, it does not:

> ![broken](https://github.com/microsoft/terminal/assets/147215885/4ae51f5c-324e-4878-a2f3-6f15cb0f4d7c)

### Actual Behavior

notice the random empty lines. note I also tested with:

terminal-1.20.10303.0

**Comment by o-sdn-o** [comment]
It appears that trailing whitespace characters carried to the next line during initial output are not considered printable characters and will not be returned to their line when the window is expanded.

![image](https://github.com/microsoft/terminal/assets/11535558/d3f4aabc-9dc1-430b-be52-1e3bb725298d)

**Comment by carlos-zamora** [comment]
Thanks for the repro. We'll take a look at this.

**Comment by zadjii-msft** [comment]
Is this fixed in Terminal 1.22/?

**Comment by 3052** [comment]
1.22 is not available that I can tell

**Comment by DHowett** [comment]
It is available in the [preview channel](https://aka.ms/terminal-preview) and on the [releases page for this repository](https://github.com/microsoft/terminal/releases)!

**Comment by 3052** [comment]
yeah 1.22 seems to have fixed it - all other current versions including 1.21.2361 fail the test described in the original post

**Comment by lhecker** [comment]
I'm glad to hear that 1.22 has fixed the issue. I don't think it'll be possible to backport the fixes to 1.21 unfortunately, because the fix was a large rewrite of our architecture.

I'll be closing this issue for now then. It'll be a few months until 1.22 becomes the next stable version.
