### ISSUE TITLE
terminal program can't accpet the folder name include [] in right button

### ISSUE THREAD

**Issue by wenbortsai** [microsoft/terminal#16706]
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.19045.0

### Steps to reproduce

File Manager open the folder name and use right button of the mouse 
then click terminal open, but it can't accept the folder name include [] and
will open in the default path of the user.
for example: The folder name is [test]

### Expected Behavior

Terminal should open in the focus folder's path

### Actual Behavior

Terminal open in the default path of the user(C:\WINDOWS\System32\WindowsPowerShell\v1.0).

**Comment by carlos-zamora** [comment]
Thanks for filing. This is a known bug in Windows PowerShell 5.1. See https://github.com/microsoft/terminal/issues/11149#issuecomment-914397136. Sorry about that! I believe this is fixed in PowerShell 7+. 

/dup #11149
