### ISSUE TITLE
terminal canary 21h2 not working

### ISSUE THREAD

**Issue by merunaaa** [microsoft/terminal#16707]
![image](https://github.com/microsoft/terminal/assets/102791469/8f75e774-ce30-466a-b699-b058be11fd3d)

### Windows Terminal version

canary

### Windows build number

10.0.22000~Lastet(Enterprise)

### Steps to reproduce

I can install appx but it won't start.
When I right click from the start menu and try to start terminal, it says license not found.

The appmanifest is configured to start from 21h2

### Expected Behavior

Install appx so that it can be activated

### Actual Behavior

not working

**Comment by carlos-zamora** [comment]
Thanks for filing. For now, we recommend using the portable zip distribution (https://github.com/microsoft/terminal#installing-windows-terminal-canary). Looks like we'll have to handle this internally.

**Comment by merunaaa** [comment]
No thankyou
Portable version is fine, just tell me how to set ISdevelopmode to true in appinstaller,
