### ISSUE TITLE
Hyperlink uses different underscore dots when not hover over it

### ISSUE THREAD

**Issue by noheromen** [microsoft/terminal#16712]
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.19045.0

### Other Software

powershell version 7.4.0

### Steps to reproduce

Try hyperlink in version 1.18.3181.0 vs 1.19.10302.0

### Expected Behavior

It would display it the same

### Actual Behavior

Shows with dots that are more closely spaced, and now it looks as if it was underscored
![image](https://github.com/microsoft/terminal/assets/97449446/c2984b7f-2c3f-4046-a5cc-d74a0182ef46)

**Comment by noheromen** [comment]
Just to note, in the picture, I have path output as hyperlink through modified prompt function.

**Comment by carlos-zamora** [comment]
Thanks for filing. This is a side effect of switching the rendering engine from the DxEngine to the AtlasEngine.
