### ISSUE TITLE
Running Windows on MacOS w/Parallels Desktop keys mapping issue

### ISSUE THREAD

**Issue by apetitjean** [microsoft/terminal#1671]
# Environment

```none
Windows Version 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

MacOS : 10.14.5
Parallels Desktop : v14.0.1
```

# Steps to reproduce

Using PowerShell console to display characters that are not natively on the Mac keyboard (like |, [, ], {, } ), it does not work. 

The keys Shift+Option+ <key> have no effect. 
This is weird because it works perfectly in the PowerShell console or CMD outside of Windows Terminal.

# Expected behavior

It should display the pipeline character and others.

# Actual behavior

If I press Shift+Option+ L to display the pipeline character, I get just "L" on the screen console.

**Comment by DHowett-MSFT** [comment]
Just going to guess this is like #521
