### ISSUE TITLE
Unable to install or update terminal from Win11 store

### ISSUE THREAD

**Issue by freedomspiritJohn** [microsoft/terminal#16714]
### Steps to reproduce

<img width="900" alt="PixPin_2024-02-14_22-55-37" src="https://github.com/microsoft/terminal/assets/129288685/279a1ee7-096a-4409-ba57-a898a552d1aa">
However, the preview version can be installed

### Actual Behavior

none

**Comment by carlos-zamora** [comment]
What build of windows are you on /?

**Comment by freedomspiritJohn** [comment]
> What build of windows are you on /?

![image](https://github.com/microsoft/terminal/assets/129288685/61b40080-4742-477e-9e8a-5cd358a7bb7c)

**Comment by zadjii-msft** [comment]
This honestly just sounds like a bug in the Store. I'd file feedback using the Feedback Hub app, on the Microsoft Store app. 

Additionally, you can always manually install the Terminal using the `.msixbundle` from our [Releases](https://github.com/microsoft/terminal/releases) page

**Comment by freedomspiritJohn** [comment]
> This honestly just sounds like a bug in the Store. I'd file feedback using the Feedback Hub app, on the Microsoft Store app.老实说，这听起来像是商店中的一个错误。我会使用 Microsoft Store 应用上的反馈中心应用提交反馈。
> 
> Additionally, you can always manually install the Terminal using the `.msixbundle` from our [Releases](https://github.com/microsoft/terminal/releases) page此外，您始终可以使用 `.msixbundle` 我们的“版本”页面手动安装终端

Ok thanks
