### ISSUE TITLE
French keyboard: tilde + space or backquote + space on WSL/Linux console broken

### ISSUE THREAD

**Issue by joknarf** [microsoft/terminal#16720]
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.22631.3155

### Other Software

wsl / ubuntu / windows ssh to linux (ubuntu 22 / centos 6 7 8 9 /...)

### Steps to reproduce

open console on wsl ubuntu/or ssh to linux, and type (French keyboard): tilde+space or backquote+space

### Expected Behavior

tilde+space gives tilde
backquote+space gives backquote
This is working on cmd/powershell but not anymore on Linux (was working in previous version)

### Actual Behavior

tilde+space gives space
backquote+space gives space

**Comment by j4james** [comment]
Sorry about this. It was a regression introduced in the last preview release. See issue #16642.

**Comment by zadjii-msft** [comment]
Yep, looks the same to me. Looks like we never cut a release build with that hotfix - we should do that!

/dup #16642
