### ISSUE TITLE
Launching multiple terminals with "elevate" : true throws exception

### ISSUE THREAD

**Issue by derekantrican** [microsoft/terminal#16721]
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.22621.3155

### Steps to reproduce

Add the following profiles:

```json
{
    "commandline": "%SystemRoot%\\System32\\cmd.exe",
    "guid": "{fb65b380-fe0c-471f-916d-014351e5ffc7}",
    "hidden": false,
    "name": "test1",
    "elevate": true,
    "suppressApplicationTitle": true
},
{
    "commandline": "%SystemRoot%\\System32\\cmd.exe",
    "guid": "{b2d0b88c-f804-4d47-b02e-2d441b66adba}",
    "hidden": false,
    "name": "test2",
    "elevate": true,
    "suppressApplicationTitle": true
},
{
    "commandline": "%SystemRoot%\\System32\\cmd.exe",
    "guid": "{1305f78a-e143-4dd5-8af8-30805c6a957b}",
    "hidden": false,
    "name": "test3",
    "elevate": true,
    "suppressApplicationTitle": true
}
```

Add the following `startupActions` setting:

```
"startupActions": "new-tab -p \"test1\" ; new-tab -p \"test2\" ; new-tab -p \"test3\"",
```

Launch Terminal

### Expected Behavior

Removing the `"elevate" : true,` from each profile will allow Terminal to launch successfully. I would expect the same resulting behavior (3 profile tabs in single Terminal window), but elevated.

### Actual Behavior

Instead, the following error message is displayed:

> shell:AppsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!App
> The group or resource is not in the correct state to perform the requested operation.

![image](https://github.com/microsoft/terminal/assets/1558019/6f6b1635-450d-492e-85e4-22bba9ffaa1a)

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #14442 because it's the same root cause.
