### ISSUE TITLE
"Open windows from a previous session" executes even if a window is open.

### ISSUE THREAD

**Issue by Tetrapak0** [microsoft/terminal#16732]
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.19045.4046

### Steps to reproduce

- Open Settings,
- Find "When Terminal starts" and set it to "Open windows from a previous session"
- Open a few tabs
- Open a console program like neovim from the start menu or desktop

### Expected Behavior

It should just launch the new window

### Actual Behavior

The current session duplicates.

https://github.com/microsoft/terminal/assets/112382253/6ee384d0-9b4f-407c-acc7-fa5f724f5712

**Comment by zadjii-msft** [comment]
I'm gonna dupe this into #16487, which I've been using for tracking everything like this. 

You do have a good observation though, about the way it reacts when you launch neovim. That definitely helps narrow down the search space here. Thanks!

/dup #16487
