### ISSUE TITLE
how to show c++ printf gb2312 world

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [microsoft/terminal#16735]
### Steps to reproduce

when i use this terminal show c++ printf function information about gb2312, is error

### Actual Behavior

when i use this terminal show c++ printf function information about gb2312, is error

**Comment by wangwenqiangGitHub** [comment]
Charecter encoding how set GB2312 like secureCRT

**Comment by wangwenqiangGitHub** [comment]
Charecter encoding how set GB2312 like secureCRT

**Comment by wangwenqiangGitHub** [comment]
![image](https://github.com/microsoft/terminal/assets/28779327/90d74e89-f4e3-4039-b07d-e57f60823b24)

**Comment by wangwenqiangGitHub** [comment]
> ![image](https://private-user-images.githubusercontent.com/28779327/305785844-90d74e89-f4e3-4039-b07d-e57f60823b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTU3NzEsIm5iZiI6MTcwODMxNTQ3MSwicGF0aCI6Ii8yODc3OTMyNy8zMDU3ODU4NDQtOTBkNzRlODktZjRlMy00MDM5LWIwN2QtZTU3ZjYwODIzYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjAwZGRiMGRlOWRkMDE0MTZjODZkMzRlZTY1MGQ3MzJiYzczYzk3YmJhMTJjMDYzNzJjMWIzY2RlZTU0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oYBZEx9paI64EKk5ycBEo1oYkJNPfNwTX9XWWPUeVv0)

this also can't correct show gb2312

**Comment by zadjii-msft** [comment]
Sorry could you explain a bit more about what you're trying to accomplish here? How you have your terminal set up/?

Only guessing from the bits here, I'm guessing that you didn't pass `-li` to the `bash` commandline in your profile's settings. But there's not a lot to work with here. I'm not really sure what is expected, and what you're actually seeing.

**Comment by lhecker** [comment]
In other words, please provide us with detailed "reproduction steps". For instance you can write about:
* Your Windows version
* Your Windows Terminal version
* What environment you're using (WSL, MSYS2, ...)
* What shell you're using (bash, zsh, fish, ...)
* How you customized your shell (oh-my-zsh, powerlevel10k, ...)
* An example C/C++ source code that shows the problem
* How you run your example

**Comment by wangwenqiangGitHub** [comment]
> In other words, please provide us with detailed "reproduction steps". For instance you can write about:
> 
> * Your Windows version
> * Your Windows Terminal version
> * What environment you're using (WSL, MSYS2, ...)
> * What shell you're using (bash, zsh, fish, ...)
> * How you customized your shell (oh-my-zsh, powerlevel10k, ...)
> * An example C/C++ source code that shows the problem
> * How you run your example

zsh + tmux
![Uploading iwEcAqNwbmcDAQTRAxoF0QFxBrBs5CFlmPuL0AXCrlK1-o4AB9IUsQSOCAAJomltCgAL0TkB.png_720x720q90.jpg…]()

**Comment by wangwenqiangGitHub** [comment]
![iwEdAqNwbmcDAQTRBJkF0QIpBrACwyHizpObBQXCrlK2GqYAB9IUsQSOCAAJomltCgAL0Vny png_720x720q90](https://github.com/microsoft/terminal/assets/28779327/b0c8d00d-a7ab-43b0-b742-9e023e9475c3)

terminal tmux zsh and show this:
![iwEcAqNwbmcDAQTRAxoF0QFxBrBs5CFlmPuL0AXCrlK1-o4AB9IUsQSOCAAJomltCgAL0TkB png_720x720q90](https://github.com/microsoft/terminal/assets/28779327/3b365e9c-6b66-4c9f-bc25-8d85c47b7641)

**Comment by wangwenqiangGitHub** [comment]
not tmux , only zsh terminal still not
![image](https://github.com/microsoft/terminal/assets/28779327/f4619c2f-710c-43e1-95ec-3b008bdc2e89)

**Comment by o-sdn-o** [comment]
A possible solution is to use UTF-8 (CP65001) code page everywhere instead of GB2312 (CP936).

![image](https://github.com/microsoft/terminal/assets/11535558/759f6ab9-0905-4a5a-b6f6-2661ec8823ee)

**Comment by carlos-zamora** [comment]
Yes, please use UTF-8. g++ doesn't support windows code pages.
