### ISSUE TITLE
Set proxy doesn't work in Terminal (PowerShell 7.2.3)

### ISSUE THREAD

**Issue by pilot513** [microsoft/terminal#16738]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.19044.3693

### Steps to reproduce

Open Terminal:
$Wcl=New-Object System.Net.WebClient
$Creds=Get-Credential
$Wcl.Proxy.Credentials=$Creds

cd c:\tmp
curl https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x64.msi -o PowerShell-7.2.3-win-x64.msi 

### Expected Behavior

![image](https://github.com/microsoft/terminal/assets/28645933/bc263131-0d25-492e-9dcc-7779f9c82879)

### Actual Behavior

The file must be downloaded. The file itself is available.

**Comment by zadjii-msft** [comment]
Actually, looking closer, that looks like you're calling `curl.exe`, and `-OutFile ...` is getting treated as the `-O` and `-u <user:password>` flags:

![image](https://github.com/microsoft/terminal/assets/18356694/c5ddd48e-b3c0-4946-a4e8-8d23a04926c8)


You probably want `invoke-webrequest`, to use `-OutFile`

**Comment by pilot513** [comment]
Sorry, I was inattentive to the 'curl' options.
![image](https://github.com/microsoft/terminal/assets/28645933/711c0832-be74-4e5e-b4b1-5b2f599f8656)

**Comment by pilot513** [comment]
Update Terminal to 1.15.2524.0 version did not help

**Comment by pilot513** [comment]
Doesn't work in powershell directly. So far I've decided this:

$env:http_proxy = "http://username:password@your_proxy_address:your_proxy_port"
$env:https_proxy = "http://username:password@your_proxy_address:your_proxy_port"

**Comment by carlos-zamora** [comment]
PowerShell respects your Windows proxy settings. Please refer to those to configure.
