### ISSUE TITLE
Drop-down context menu changes to inactive color scheme after right-click context menu is opened

### ISSUE THREAD

**Issue by digitalguy99** [microsoft/terminal#16736]
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Here are the steps I went through that triggered the bug:

1. I set `experimental.rightClickContextMenu` to true and saved the settings.json file
2. I restarted my Windows Terminal
3. I right clicked to open the right-click context menu
4. I then pressed the new tab dropdown to open the dropdown context menu

Here's a gif that illustrates what I did:
![202402191126](https://github.com/microsoft/terminal/assets/52367722/f22828ad-bb99-40e6-91a2-97eac2fd3ac6)

### Expected Behavior

The color of the dropdown context menu should not change to its inactive color scheme.

### Actual Behavior

The color of the dropdown context menu changed to its inactive color scheme.

**Comment by zadjii-msft** [comment]
This looks basically exactly the same as #7532. There was a bug in the OS that caused some shadows to be at the wrong z-order. I believe that's fixed in OS builds >=22000. Thanks!

/dup https://task.ms/33411893

**Comment by digitalguy99** [comment]
> This looks basically exactly the same as #7532. There was a bug in the OS that caused some shadows to be at the wrong z-order. I believe that's fixed in OS builds >=22000. Thanks!
> 
> /dup https://task.ms/33411893

@zadjii-msft I'm aware that for Win 11 users they can simply update to the newest build. But is there a solution for Windows 10 users?

**Comment by zadjii-msft** [comment]
Alas, not that I'm aware of. There was a huge pile of bugfixes for XAML in the Windows 10->11 era, but IIRC this one was more like a bug that got accidentally fixed by a new OS feature, and that feature would have a hard time getting backported. Sorry about that 😕
