### ISSUE TITLE
Tray icon remains with terminal terminated

### ISSUE THREAD

**Issue by serious-angel** [microsoft/terminal#16733]
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.19045.4046

### Steps to reproduce

1. Open a new single or multiple terminal windows;
2. Enable option (if disabled): `Settings -> Appearance -> "Always display an icon in the notification area"`;
3. Terminate all terminal windows.

### Expected Behavior

Tray icon should disappear with all terminal processes terminated.

### Actual Behavior

Tray icon remains, and only disappears with a mouse cursor hover on it.
With the icon remaining and new terminal process started, multiple icons appear in the taskbar:

<img alt="2024-02-18_00-52-23_Z_AHlop2Z7" src="https://github.com/microsoft/terminal/assets/25136754/6b574b02-c803-4012-bf9a-71cfa389ad19">

**Comment by zadjii-msft** [comment]
You know, I've definitely seen this before. I'm sure there's something we're not doing right on shutdown to manually remove ourselves. (you'd think if a process that added a tray icon exited, the icon would get removed automatically 🙃 )

**Comment by zQueal** [comment]
I also came here because I have this issue.

**Comment by Nsbx** [comment]
Same here, video for exemple :
https://github.com/user-attachments/assets/d71c9fd0-30f3-45a9-a7ef-c8e0d8dc7bce

**Comment by visitantz** [comment]
> > Same here, video for exemple...
> 
> Cheers! I heard some already got used to move mouse around tens of those icons in the taskbar. They said, "it evolved into a habit".

Or just stick to v1.17 🤣
