### ISSUE TITLE
Hyperlink to be available on format table

### ISSUE THREAD

**Issue by lr0217** [microsoft/terminal#16750]
# Description of the new feature/enhancement
Hyperlink feature is available in write-host and display list, but not in format table, would be nice to have

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This sounds like a request for the team that owns `Format-Table`, yea? 

Presumably, you're relying on auto-detected URLs here, right? Not sure there's anything we can do Terminal-side to detect a URL that's broken into an arbitrary rectangle in the buffer. But `Format-Table` absolutely could manually wrap URLs with `OSC 8`, such that the entire cell is treated as a singular hyperlink

**Comment by lr0217** [comment]
Yeah I am new to got hub
Can you share some info on how to send to the format-table team?


Thanks

**Comment by 237dmitry** [comment]
> This sounds like a request for the team that owns Format-Table, yea?

This works in other terminals:

```powershell
[pscustomobject] @{ Name = 'Google'; Address = 'https://google.com' } | Format-Table
```

**Comment by zadjii-msft** [comment]
And you know, this seems like it works "fine" for really long URLs too:

```ps
@([pscustomobject] @{ Name = 'Google'; Address = 'https://google.com' ; Whatever = 'you get the point' }, [pscustomobject] @{ Name = 'long url '; Address = 'https://github.com/microsoft/terminal/issues/16750#issuecomment-1961449890' ; Whatever = 'you get the point this one is really long and fills up a lot of space' } ) | Format-Table
```

![image](https://github.com/microsoft/terminal/assets/18356694/08ab4583-e97c-452f-881f-cf5438bbe08e)

Admittedly, they can get cut off if the table gets cut off, but that seems totally as expected. 

Can you share a screenshot of what's not working/? (github will let you upload an image by pasting it from your clipboard, into the text box)

**Comment by lr0217** [comment]
Maybe the issue is that I am using this approach 

https://lucyllewy.com/powershell-clickable-hyperlinks/

 "`e]8;;https://google.com`e\google`e]8;;`e\"

**Comment by carlos-zamora** [comment]
Thanks! This seems like a /dup of https://github.com/PowerShell/PowerShell/issues/7744
