### ISSUE TITLE
Broken Display when docked

### ISSUE THREAD

**Issue by IPdotSetAF** [microsoft/terminal#16758]
### Windows Terminal version

1.18.231114001

### Windows build number

19045.4046

### Other Software

npm -> nodeJS v18

### Steps to reproduce

- clone any nodeJS based repo
- inside the inside the folder run command `npm install`
- dock the terminal window to right or left side of the screen
- npm can not clear the last line and rewrite it anymore (it can only append lines).

### Expected Behavior

last line should be deleted and rewritten.

### Actual Behavior

when terminal is docked, lines can not be cleaned, lines will only append.

**Comment by zadjii-msft** [comment]
> npm can not clear the last line and rewrite it anymore (it can only append lines).

That _sounds_ like gutter turds are back?  I've got a couple questions to help ID the root cause here:
* Can you select the text in that last row, or is it not actually selectable? 
* Was there text in that row before you docked the Terminal? Or was it blank?
* Can you share a screenshot/?

Also, can you try [Windows Terminal v1.19.10302.0](https://github.com/microsoft/terminal/releases/tag/v1.19.10302.0)? Sharing your settings might also help here, to know which renderer is in use.

**Comment by IPdotSetAF** [comment]
Thanks for the reply @zadjii-msft 

> * Can you select the text in that last row, or is it not actually selectable?

yes the text is selectable (when its working as it should (terminal is not docked))

> * Can you share a screenshot/?

- Not Docked :
![Screenshot 2024-02-27 161839](https://github.com/microsoft/terminal/assets/60518834/c9d66bb2-86e2-4047-af51-d2fc4ce4c42d)

- Docked :
![Screenshot 2024-02-27 161902](https://github.com/microsoft/terminal/assets/60518834/11248cfc-e7ca-4edf-96cb-ec0a06024a94)

> * Was there text in that row before you docked the Terminal? Or was it blank?

I don't remember that, unfortunately.

> which renderer is in use.

I am using the default renderer (NOT AtlasEngine)

**Comment by lhecker** [comment]
So, what happens if you do use AtlasEngine?

**Comment by IPdotSetAF** [comment]
> So, what happens if you do use AtlasEngine?

same bug.

**Comment by carlos-zamora** [comment]
Thanks for testing that out. Got a few more questions for you:
- What if instead of docking, you resize the window?
- What if you dock the window first before running it?
- Does this repro in console host (conhost.exe)?

**Comment by IPdotSetAF** [comment]
> * What if instead of docking, you resize the window?

That works fine.

> * What if you dock the window first before running it?

This also works fine

> * Does this repro in console host (conhost.exe)?

IDK, I will try this out and let you know.

**Comment by IPdotSetAF** [comment]
> * Does this repro in console host (conhost.exe)?

No, it does not.

**Comment by carlos-zamora** [comment]
Thanks for your help. We're actually going to mark this as a /dup of #15976 so that we can track this all in one issue.
