### ISSUE TITLE
Terminal windows can be lost if "hide terminal in notification area" true and multiiple windows are minimized.

### ISSUE THREAD

**Issue by biggestsonicfan** [microsoft/terminal#16755]
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.19045.4046

### Steps to reproduce

- Open a terminal window
- In the settings turn "Hide Terminal in the notification area when it is minimized" to "On"
- Open a new Terminal tab and drag the tab to create a new window.
- Optional: Put text or a use a command in the new terminal window to differentiate it from others.
- Minimize the newly dragged out tab-window.
- The window will no longer be accessible. Minimizing the active Terminal window left and reactivating it from the notification area will only bring up the singular window.

### Expected Behavior

Clicking on the notification area should restore any minimized Terminal windows, regardless if a Terminal window is active and not minimized.

### Actual Behavior

The Terminal window can no longer be restored until the "Hide Terminal in the notification area when it is minimized" is turned "Off" and settings are saved.

**Comment by carlos-zamora** [comment]
Thanks for filing. You can actually right-click on the tray icon to bring up a list of windows instead of opening the most recent one. We'll use this issue to track making that more discoverable (idea: if multiple windows exist, rather than opening the most recent window, we should open the nested menu with the list of windows).

**Comment by Arc-2023** [comment]
the point is that there's nothing in notificaiton area even the "always show in notification" option is checked.
maybe there should be one more way to controll the minimized windows in case other wiered things happen
