### ISSUE TITLE
united states-international keyboard does NOT accept characters which need two keystrokes, e.g. " ' ".

### ISSUE THREAD

**Issue by ejprinz** [microsoft/terminal#16759]
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.22621.0

### Steps to reproduce

- Install "united states-international" input method.
- Open Windows Terminal Preview
- Start Ubuntu 22.04 in Windows Subsystem for Linux
- Type `Single Quote` followed by `Space`

Expected result (like in PowerShell):
- See `Single Quote` and `Space` (this happens in Powershell and also in Windows Terminal - not "Preview")

Observed result:
- See two `Space`, don't see `Single Quote`

This is also observed for `Double Quote`

### Expected Behavior

See Single Quote and Space (this happens in Powershell and also in Windows Terminal - not "Preview")

### Actual Behavior

See two `Space`, don't see `Single Quote`

**Comment by DanSM-5** [comment]
I'm having the same issue with Windows Terminal preview v1.20.10303.0.

It works fine under Stable Windows Terminal v1.18.10301.0

This can be triggered under powershell using a command line text editor like neovim (`winget install neovim` or `scoop install neovim`). Other shells like Bash from Git for windows are also affected.

**Comment by j4james** [comment]
Thanks for the report, but this is a duplicate #16641 and #16642. It should already be fixed in the nightly Canary build, and I believe the fix is going to be backported to v1.20 soon.

**Comment by DHowett** [comment]
Yep! This is rolling out via the store _now_. The GitHub release will be up tomorrow morning.

**Comment by carlos-zamora** [comment]
Thanks for filing. Marking this as a /dup of #16641
