### ISSUE TITLE
Open tabs also transparent

### ISSUE THREAD

**Issue by Fedox-die-Ente** [microsoft/terminal#16766]
# Description of the new feature/enhancement

The tab that is currently open should also get an acrylic color because it looks extremely strange when everything is nice and transparent, and then this tab with full color

![image](https://github.com/microsoft/terminal/assets/67076970/e2a81042-d297-45c1-a2b0-960f99a0b78c)

# Proposed technical implementation details (optional)

/

**Comment by zadjii-msft** [comment]
This looks awfully a lot like what we're tracking in /dup #14833. Thanks!
