### ISSUE TITLE
Tilde characters are screwed up

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/terminal#16761]
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.22631.3155

### Other Software

OpenSSH_for_Windows_8.6p1

### Steps to reproduce

1. Open VIM
2. Line numbers are screwed up

### Expected Behavior

All tilde characters should be nice and straight.

### Actual Behavior

Tilde charcters are misplaced

**Comment by zadjii-msft** [comment]
Can you try 1.19? 
Does this repro without ssh involved (like, with WSL, or ssh from within WSL)?
Can you share a screenshot/?

**Comment by ChaseKnowlden** [comment]
It's going crazy on ssh in Windows Terminal with text missing.
