### ISSUE TITLE
Context "Open in Terminal" disappeared 

### ISSUE THREAD

**Issue by Danipulok** [microsoft/terminal#16765]
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.19045.4046

### Steps to reproduce

I don't know unfortunately. Maybe I changed something in the registry myself, but I don't know what was the trigger exactly. Maybe some updates or something else.

### Expected Behavior

I get "Open in terminal" when clicking on folder background

![image](https://github.com/microsoft/terminal/assets/45077699/caaae794-4a29-41b7-96e8-671a7b5b3237)

### Actual Behavior

I don't see "Open in terminal" when I click on folder background
![image](https://github.com/microsoft/terminal/assets/45077699/3c612292-a1d0-4c62-9cec-431aa363cd38)

But when I click on folder exactly and not on the background, I see the "Open in terminal". 
![image](https://github.com/microsoft/terminal/assets/45077699/bb7ee002-ab5e-4182-850d-5d7568fb1f8c)

But before it was accessible via background too. 
Please tell me how to add it via registry and maybe add this option to the Windows Terminal settings?

**Comment by Danipulok** [comment]
Well, I added something via:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt]
@="Open in terminal"
"Icon"="%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wt.ico"

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt\command]
@="%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wt.exe"
```
Here's the result:
![image](https://github.com/microsoft/terminal/assets/45077699/95591741-c6f5-4fd4-83f0-7accd0b14118)


But when I try to click on it, I get:
`Explorer.exe - Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.`
![image](https://github.com/microsoft/terminal/assets/45077699/62a7b657-32ea-4b49-83b6-6f8cecb53c2c) 

PS: Icon from: https://raw.githubusercontent.com/microsoft/terminal/master/res/terminal.ico

**Comment by Danipulok** [comment]
Well, whatever I put in the 
```
[HKEY_CLASSES_ROOT\Directory\Background\shell\wt\command]
@="wt.exe"
```

It just doesn't open anything, even though it thinks about something.
But I don't get the previous error anywhere.

**Comment by carlos-zamora** [comment]
Thanks for filing. We're going to mark this as a /dup of #14185
