### ISSUE TITLE
Flushing FTCS sequences causes flickering in nushell (again; 1.20+)

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#16769]
### Windows Terminal version

1.20.10572.0

### Steps to reproduce

* Install nushell
* Open `$nu.config-path` in your favorite editor
* Find `shell_integration` and set it to `true`

### Expected Behavior

No flickering, as it was the case between 1.18 and 1.19.

### Actual Behavior

The prompt line flickers:

![596kHbpNFuSdsCC3](https://github.com/microsoft/terminal/assets/2256941/1aa813a8-6cba-44f1-b0c0-bfefa56e7b21)

See #13710 for the previous issue.

**Comment by dragove** [comment]
This can be reproduced with 1.19 when `the new text render ("AtlasEngine")` is enabled.

**Comment by rgwood** [comment]
I am able to reproduce it in 1.19.10573.0 even without AtlasEngine enabled.

**Comment by dragove** [comment]
Sorry, I've tested with previous version, seems not related to Atlas Engine (I've deleted that comment).

first 1.19 release version 1.19.10292.0 can also reproduce this problem. 1.18 works fine.

**Comment by panki27** [comment]
I am also seeing a lot of flicker with `python` programs using `curses`, running version `1.19.10573.0`.

**Comment by abhbh** [comment]
This issue can be reproduced again in 1.20.11781.0

Disabling `osc133 ` in shell_integration is a workaround.

**Comment by lhecker** [comment]
The fix has been released in v1.21.1272.0 which is currently in Windows Terminal Preview.
