### ISSUE TITLE
[error 2147942402 (0x80070002) when launching `pwsh.exe -NoLogo']

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/terminal#16786]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Use the following `settings.json`
```jsonc
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": [], // Removed for brevity
    "copyFormatting": "all",
    "copyOnSelect": false,
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": 
        {
            "antialiasingMode": "cleartype",
            "font": 
            {
                "size": 10.0
            },
            "opacity": 90,
            "useAcrylic": true
        },
        "list": 
        [
            {
                "commandline": "pwsh.exe -NoLogo",
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "colorScheme": "Campbell Powershell",
                "commandline": "powershell.exe -NoLogo",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell"
            },
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": true,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{e5a83caa-4c73-52b3-ae6b-bc438d721ef9}",
                "hidden": false,
                "name": "Ubuntu 22.04.3 LTS",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
            }
        ]
    },
    "schemes": [], // Removed for brevity
    "themes": []
}
```
2. Start Windows Terminal (which defaults to the PowerShell 7 profile with the guid  "{574e775e-4f2a-5b96-ac1e-a2962a402336}" and the name "PowerShell".

### Expected Behavior

Windows Terminal should start a PowerShell 7 terminal.

### Actual Behavior

It shows `[error 2147942402 (0x80070002) when launching ``pwsh.exe -NoLogo']`

![grafik](https://github.com/microsoft/terminal/assets/2971735/b5a81f78-7855-49c9-9fa6-59408a4af2e6)

I was migrating the `settings.json` from my Windows 10 computer to a new Windows 11 computer. It was working before.

pwsh.exe is also in the path

![grafik](https://github.com/microsoft/terminal/assets/2971735/80cdea20-56a2-4ae0-b2df-ec7e250d0525)

**Comment by zadjii-msft** [comment]
curious. Do other profiles work/? Especially the cmd.exe one - that should actually use the full path to cmd, whereas the other profiles are just relying on the `pwsh` that's found on the PATH. I'd mildly worried you caught our env var regeneration in a broken state. 

If the `cmd` profile works, the output of a `set PATH` might be enlightening

**Comment by danielniccoli** [comment]
> Do other profiles work?

Yes, you can see that also in the second screenshot I posted.

> If the cmd profile works, the output of a set PATH might be enlightening

I may be able to provide that next week as I do not have access to the computer in the meantime. However, the `where pwsh` should already proof that it is in the `PATH`, no?

**Comment by danielniccoli** [comment]
Issue was solved without interaction after returning to my computer this week. I'm closing this issue as finding the root cause now is impossible.

**Comment by DHowett** [comment]
Ah, thank you for following up!

**Comment by thrve** [comment]
так должно быть:
"C:\Users\thrv\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe" **"/nologo"**

**Comment by apaladi** [comment]
I have it like this:
`%localappdata%\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe`
