### ISSUE TITLE
Windows Terminal Preview v1.20.10293.0

### ISSUE THREAD

**Issue by NUSHA241** [microsoft/terminal#16805]
### Discussed in https://github.com/microsoft/terminal/discussions/16622

<div type='discussions-op-text'>

<sup>Originally posted by **DHowett** January 30, 2024</sup>
Welcome to Windows Terminal Preview 1.20! We've got a pretty small release this time, since we focused mostly on
backportable bug fixes (50% of all checkins were backported to 1.19!). We did land some excellent community
contributions this time, however, so take a peek at the notes below for more.

### Why are there so many assets? How do I choose?

Please visit our page documenting the different [Windows Terminal Distributions]!

## Features

* We can now display colored and curly, dashed, or dotted and doubled underlines, even in conhost! (#16097) (#16444) (thanks @tusharsnx!) with some help from the team (#16475)
* The new rendering engine is now enabled by default in all channels (#16277)
* Double-clicking a wrapped word will now select the entire thing. I know, it's 2024. (#16441) (thanks @js324!)
* We will now highlight all search results while the search box is open (#16227) (thanks @e82eric!)
* You can now set a different `opacity` value for unfocused panes (#15974) (thanks @Jaswir!)
* We've reimplemented resize with reflow; please be on the lookout for any bugs! (#15701)

## Changes

* The "Canary" ZIP distribution will now default to portable mode (#16048)
* We will now automatically clear any "Failed to reload settings" dialogs when you fix your `settings.json` (#16119) (thanks @codecruisedor!)
* Filenames and paths generated by dropping files/directories on a WSL instance will be wrapped in single quotes (rather than double quotes) (#16214) (thanks @js324!)
* The mouse wheel will now automatically scroll the application when the alternate buffer is in use ("Alternate Scroll Mode" is enabled by default) (#16535) (thanks @j4james!)
* The performance and correctness of HTML and RTF copy has been vastly improved (#16377) (#16480) (thanks @tusharsnx!)
* We have removed a whole bunch of outdated telemetry from the console, like "which VT sequences are in use?" and "did you use Search Backwards or Search Forwards more often in Find?" Check out the PRs for more details: (#16253) (#16467) (#16468)

### VT and terminal emulation

* We now support `DECST8C`, which will reset the tab stops to every 8 columns (#16534) (thanks @j4james!)
* We now support `DSR` queries for printer status, user-defined keys, keyboard status, locator status, locator identity, data integrity and multiple session status (#16525) (thanks @j4james!)

## Bug Fixes

* In cooked read clients, backspacing a control visualizer (e.g. `^X`) no longer messes up the display (#16400)
* `INPUT_RECORD`'s `KeyEvent.dwControlKeyState` will no longer contain `ENHANCED_KEY` when it shouldn't (#16335)
* <kbd>Ctrl+Space</kbd> now works properly (#16298) (thanks @lonnywong!)
* Mashing <kbd>Enter</kbd> will no longer disrupt CommandEnd scrollbar marks (in general, we now ignore back-to-back duplicate marks) (#16107)
* During RTF export, we will now use a background color directive that Microsoft Word understands (#16035) (thanks @tusharsnx!)
* _Once again,_ we've fixed another issue where Terminal will spontaneously fail to load Cascadia Mono (#16323)
* `ReadFile` with a too-small buffer size will no longer corrupt your input stream and drop events (#16313)
* We've fixed which glyph we use for the `SUB` control character (#16559) (thanks @j4james!)

### Accessibility

* Color buttons in the settings UI will now announce their RGB values for screen readers (#16544)

### VT and terminal emulation

* Terminal will no longer double-encode some inputs, like mouse mode, mangling them beyond comprehension (#16407)
* Toggling the alternate screen buffer in a `PROCESSED_INPUT` console application will no longer crash the console (#16187)
* `DRCS` soft fonts received in chunks are no longer corrupted (#16349)
* `ED2` (Erase in Display) will no longer emit a ton of blank lines (#16610)
* @j4james rewrote and fixed 11 bugs in VT input mode, vastly improving our compatibility with other terminals and applications (#16511) (thanks @j4james!)
   * Including...
      * `DECKPAM` (application keypad mode)
      * <kbd>Alt+Arrow Keys</kbd> generating extra characters
      * Mouse input when `DECARM` (auto-repeat mode) is disabled
      * <kbd>Ctrl+Anything</kbd> that didn't have a <kbd>Ctrl</kbd> not generating any input
      * <kbd>Ctrl+_</kbd> generating a `RET`
      * <kbd>Ctrl+:</kbd> on a JIS-106 keyboard generating a `^Z`
      * <kbd>Ctrl+Alt+\\</kbd> not working in WSL
      * <kbd>Ctrl</kbd> being misinterpreted under some custom keyboard layouts
      * <kbd>Alt</kbd> not working for non-alphabetic control characters
      * <kbd>AltGr</kbd> behaving improperly on some keyboards with some input

### Usability and UI

* The readability of our various settings disclaimers has been improved (and made more Roman) (#16272) (thanks @chausner!)
* ... and those disclaimers will no longer overlap the content sometimes (#16602) (thanks @tusharsnx!)
* The settings page will no longer forget how far you'd scrolled when it reloads (#16261) (thanks @radu-cernatescu!)

### Reliability

* Terminal should no longer crash after you close a couple windows on Windows 10 (#16588) (#16587)
* Two memory leaks in our screen reader integration have been stoppered (#16597) (thanks @glenrgordon!)
* We've eliminated an entire class of shutdown issues by just terminating the process directly when we think it's time (#16575)
* We've stamped out a crash that would occur when closing some tabs (#16412)
* The Azure Cloud Shell integration should no longer crash on a network timeout (#16364) (thanks @reynoldsa!)

### Schema

* We've fixed a number of issues in the JSON schema (#16103)

### conhost and Console hosting

* conhost: the performance of scrolling text has been improved, like, 10x (#16333)
* conhost: we un-broke rectangular copy via the Edit &gt; Mark menu item (#16197)
* conhost: "disable scroll forward" once again works (#16411)
* conhost: font preview is working again (#16324)
* conhost: `SetConsoleWindowInfo` no longer fails to refresh the display (#16334)
* conhost: we have removed all traces of EDP clipboard auditing (#16460)
* conhost: we now retry a few times to open the clipboard and put standards-compliant `CF_UNICODETEXT` on it (#16457)
* conpty: on exit, we will now deassert Win32 Input Mode (#16408)
* conpty: we now buffer more text input before deciding how to parse it (#16470)
* conpty: we've fixed a shutdown deadlock with WSL (#16340)
* conpty: we will no longer deadlock waiting for `DSR` `CPR` when Win32 Input Mode is enabled (#16445)
* conpty: we will no longer return to the VT parsing ground state when we are expecting win32 input sequences; this fixes a pasting issue in SSH and WSL interop (#16352) (#16466)

## Miscellaneous

* With special thanks to @marcelwgn, @jsoref, @RyanLua, @AtariDreams, @debghs, @mdanish-kh, and @Jvr2022 for
  code quality, documentation, repository management, dependency and spelling updates across the board. We couldn't do
  it without you!

[Windows Terminal Distributions]: https://learn.microsoft.com/windows/terminal/distributions

---

_Binary files inside the unpackaged distribution archive bear the version number `1.20.240129003-preview`._

### Asset Hashes

- Microsoft.WindowsTerminalPreview_1.20.10293.0_8wekyb3d8bbwe.msixbundle
   - SHA256 `390E4F33F5BEBAB1B33A4801E07A60B80ADDF7112B45C868AD4642138047A301`
- Microsoft.WindowsTerminalPreview_1.20.10293.0_arm64.zip
   - SHA256 `34E8091BB394DD70DD500BA5E280DCC5E170386732FC69687E2BC02E6375E2F4`
- Microsoft.WindowsTerminalPreview_1.20.10293.0_x64.zip
   - SHA256 `9FB289BBB58B0DA88D0565CEA58809B663D9BBEED146866FCF9ADA97490F33AC`
- Microsoft.WindowsTerminalPreview_1.20.10293.0_x86.zip
   - SHA256 `B4F1842EF943197292C162356033A637115C0802EDD22AF2265C643B6B55E521`

<hr /><em>This discussion was created from the release <a href='https://github.com/microsoft/terminal/releases/tag/v1.20.10293.0'>Windows Terminal Preview v1.20.10293.0</a>.</em></div>

**Comment by Jvr2022** [comment]
spam
