### ISSUE TITLE
docker stats flickers

### ISSUE THREAD

**Issue by ahmelsayed** [microsoft/terminal#1680]
# Environment

```none
Windows build number: 10.0.18922.1000
Windows Terminal version (if applicable): 0.2.1715.0

Any other software? WSL2, zsh, docker
```

# Steps to reproduce

```bash
docker run --rm -d alpine sleep 20s
docker run --rm -d alpine sleep 20s
docker stats
```

# Expected behavior
On GNOME Terminal the output is displayed without flickering.

# Actual behavior
On Windows Terminal it flickers.

I tried to record a GIF, but my screen recorder doesn't show the flickering. It only records at 10 fps though.

**Comment by JushBJJ** [comment]
Does it flicker with the old cmd? If it does still then report the issue at the WSL repo.

**Comment by miniksa** [comment]
Record with your smartphone and upload a video?

**Comment by ahmelsayed** [comment]
https://ahmelsayed.blob.core.windows.net/public/IMG_0144.mp4

**Comment by thorerik** [comment]
I wonder if this is related to the draw performance in general?
It can also be observed by running, e.g. `sudo yast2` on OpenSuSE Leap 15.1 in WSL:
In Terminal:
![ezgif-2-c671632045b9](https://user-images.githubusercontent.com/219796/60308350-99e30d80-9948-11e9-9fb8-2d0895b05bd6.gif)

In standard conhost:
![ezgif-2-a20ef2dbfce1](https://user-images.githubusercontent.com/219796/60308364-a6676600-9948-11e9-9510-da2d4fbe1fea.gif)

the issue becomes more apparent when running the terminal emulator in a larger size.

**Comment by JushBJJ** [comment]
That's quite weird. I think it has to do something with the rendering that makes it flicker.

**Comment by DHowett-MSFT** [comment]
Until proven otherwise, I'll dupe this to #778. Thanks for all the cool repro cases!

**Comment by skyline75489** [comment]
@miniksa I'm gonna comment here so it does not mess with the pile of comments in #5185.

I've also seen this with iTerm2 on macOS when I'm in a SSH session on remote machines and the network is slow. The routine of `docker stats` is basically repainting all the stats to the screen over and over again. Natually it should flicker if the duration between each painting is noticeably long. I begin to doubt that this is rendering-related. We can improve rendering performance for sure. But the `docker stats` may still be flickering, even in iTerm2.

**Comment by miniksa** [comment]
@skyline75489, OK. I might not worry that hard about it right now then and just get the differential work in and let a future issue be opened fresh if there is still a real problem. Thanks!

**Comment by tu-nv** [comment]
@miniksa In my case, New Terminal has a serious flickering issue that makes `docker stats` not usable, but the wsltty (https://github.com/mintty/wsltty) does not have that issue. I am running win 10, terminal preview Version: 1.4.2652.0. And yes, I do ssh to another machine and fire tmux there, open `docker stats` in one tmux panel.

**Comment by jherico** [comment]
I found this and after reading through the linked comments I think this is really a docker stats issue rather than a windows termainl issue.  I was able to reproduce it on ConEmu.

**Comment by ClassicDarkChocolate** [comment]
I found that when I right click on tab to open context menu. When the context menu is in open state, the terminal updates screen without flickering.
