### ISSUE TITLE
Any console in Terminal closes with with code 259 (0x00000103)

### ISSUE THREAD

**Issue by vevv** [microsoft/terminal#16807]
### Windows Terminal version

1.19.240226003

### Windows build number

10.0.19045.4046

### Other Software

N/A

### Steps to reproduce

Launch any console in Windows Terminal.

### Expected Behavior

Windows Terminal works as expected.

### Actual Behavior

Launching any terminal (Command Prompt, PowerShell, WSL, Git Bash) results in Windows Terminal erroring out with:
> [process exited with code 259 (0x00000103)]
> You can now close this terminal with Ctrl+D, or press Enter to restart.

There is next to no information available on either of the error codes online, with the only two results being [a deleted StackOverflow post about the same issue](https://cc.bingj.com/cache.aspx?q=https%3a%2f%2fstackoverflow.com%2fquestions%2f78084443%2fwindows-terminal-opens-and-closes-immediately&d=2863414540149&setlang=en-US&w=lHEwaXAS2Fuf6dLp94mVtRAxbBLYidC-) and [someone running into the same issue in their own software](https://github.com/moh-hassan/odata2poco/commit/a1a913287be25dff7b4900182d8119be3f8b8906).

The issue happens both on Windows Terminal installed from Store and the unpackaged version from here. Starting cmd directly, or using a different terminal (e.g. MobaXTerm) works fine.

**Comment by lhecker** [comment]
We call `GetExitCodeProcess` to show the exit code in that message. That API function returns `STILL_ACTIVE` to indicate that the process is still running. `STILL_ACTIVE` is `0x00000103`.

**Comment by zadjii-msft** [comment]
Why the heck would we be thinking that the connection closed, if the target process hasn't exited yet? The conpty died?

I wonder if this isn't just a different version of #16794

**Comment by zadjii-msft** [comment]
You know what, if you file feedback with feedback hub, we should be able to positively confirm that this is a dupe. 

/feedback

**Comment by YevheniiPokhvalii** [comment]
I have the same issue:

Windows Terminal version:
1.19.10573.0

Windows build number
Win 10 Pro
22H2
10.0.19045.4046

The terminal was downloaded from MS Store. It immediately crashes during a launch. I have only a split of second to click on settings to keep it's window open. Nonetheless, non of the applications work inside it (cmd, powershell, gitbash).

**Comment by Gudine** [comment]
I'm not the one who opened the issue, but the problem also affects me and I recorded the data through the Feedback Hub if it helps.

https://aka.ms/AApfkkv

**Comment by juanssilveira** [comment]
I was also having this problem, from what I understand the problem occurs in _v1.19.10573.0_. I downgraded to the latest stable version (**v1.19.10302.0**) and it worked again.

**Comment by monocodezz** [comment]
I can confirm the same issue with the 1.19.10573.0_x64 version on Win10 22H2 (OS build 19045.4170). The terminal seems to crash immediately upon opening any shell window. BTW, I'm also on the old CPU, Intel Core 2 Due E400.

v1.19.10302.0 seems to work fine.

**Comment by ITmsdnet** [comment]
Same issue .   Like the earlier issue from January affecting to native Windows apps  , when update to the last version  ,  now  seems affecting to  latest version of Windows Terminal and Terminal Preview .  I have Intel Core 2 Quad processor .

**Comment by a-usr** [comment]
> Same issue . Like the earlier issue from January affecting to native Windows apps , when update to the last version , now seems affecting to latest version of Windows Terminal and Terminal Preview . I have Intel Core 2 Quad processor .

Your CPU doesn't support the POPCNT instruction, which is required by the current WIndows Terminal Version. However i think the WT Team is currently working on a fix. For the time being try using an older version of Windows Terminal.

See #16794

**Comment by zadjii-msft** [comment]
Thanks all! We'll de-dupe this with /dup #16794

**Comment by ITmsdnet** [comment]
Windows 11 won't install or upgrade to version 24H2 if the processor does not support  POPCNT instruction  ( SSE 4.2 )  .  With these issues , it was a warning,   we could see it coming... how disgusting
 😩😡
