### ISSUE TITLE
Resize performance bad since pr #929

### ISSUE THREAD

**Issue by jmorrill** [microsoft/terminal#1681]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
```

# Steps to reproduce

Resize the Terminal Window using the latest checkin.

# Expected behavior

Expected performance was what was before [pr 929](https://github.com/microsoft/terminal/pull/929)

# Actual behavior

Very slow, resize performance.  It used to be very smooth.

**Comment by DHowett-MSFT** [comment]
Mentioned as part of #1625.
