### ISSUE TITLE
Hovering over a link with ctrl pressed should turn cursor into a hand to indicate clickability

### ISSUE THREAD

**Issue by axelfontaine** [microsoft/terminal#16813]
# Description of the new feature/enhancement

To make it clear that a link is clickable, when hovering over it with ctrl pressed, the mouse cursor should turn into a hand (like in a browser)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7563 for more discussion.

/dup #7563
