### ISSUE TITLE
WindowsTerminal.exe crashes with 0xc0000374 when specific japanese charactors entered

### ISSUE THREAD

**Issue by tarori** [microsoft/terminal#16817]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.19045.4123

### Steps to reproduce

- Open some window of windows terminal.
- Enter "動く" by Japanese IME.

https://github.com/microsoft/terminal/assets/60473743/75ab6763-0d2b-4a44-bf13-77c740e34783

### Expected Behavior

Entered charactors will be inserted.

### Actual Behavior

WindowsTerminal.exe will immediately crash with error code 0xc0000374.

**Comment by tarori** [comment]
In debug mode, it is crashing here.
![image](https://github.com/microsoft/terminal/assets/60473743/c86852f5-6c13-4456-b417-c0fa405ae4d9)

And I found that it crashes only when I select "use old Microcoft IME" checkbox.
![image](https://github.com/microsoft/terminal/assets/60473743/33a1310d-72c5-4164-9971-e3859c294778)

**Comment by lhecker** [comment]
We're planning to rewrite our IME for the next release (version 1.21) which should hopefully fix this issue.

**Comment by lhecker** [comment]
We just published a major update to our IME implementation in the nightly Canary branch. It was rewritten from the ground up and has tons of improvements! If you're interested in trying it out, you can get it here: https://aka.ms/terminal-canary-installer
If you already have the Canary build installed, you can use this link to force an update.

If you encounter any issues or have any suggestions, or if you simply like/dislike the changes, please let us know! Thank you for bearing with us. 😊

**Comment by tarori** [comment]
@lhecker Thanks!
I confirmed that the issue is solved in the Canary build 1.21.1094.0.
