### ISSUE TITLE
Localization - Typos/consistency errors in French in closing contextual menu

### ISSUE THREAD

**Issue by SphinxKnight** [microsoft/terminal#16819]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.19045.4046

### Steps to reproduce

Open the Terminal (splitting the tab helps discover one more string)

### Expected Behavior

The contextual menu should contain "Fermer" (infinitive) and not "Fermez" (imperative)
Submenu should contain "Fermer les onglets à droite" / "Fermer les autres onglets" / "Fermer le volet"

### Actual Behavior

Casing and conjugation are inconsistent 

Conjugation: a mix of infinitive and imperative while the rest of the UI is, correctly, using infinitive
![image](https://github.com/microsoft/terminal/assets/2413436/b1ba26a2-f55d-4a43-bb9a-59ab2940e21b)

Casing: those strings are using uppercase starting words while the rest of the UI is, correctly, using an uppercase letter only for the first letter of the text

**Comment by PhMajerus** [comment]
Just to clarify the expected behavior, the cascading menu item also needs to be fixed:
```
Fermer… >
     Fermer les onglets à droite
     Fermer les autres onglets
     Fermer le volet
Fermer l'onglet
```

Oh, and those … are not consistent with Windows UI guidelines and have to go, but I'll post that separately.

**Comment by lhecker** [comment]
The fermer vs. fermez issue does seem resolved now. I'm not entirely sure either whether capitalizing Pane in French is a good idea. It's a little weird even in the English original IMO.
