### ISSUE TITLE
Window resize does not resize footprint of powershell output

### ISSUE THREAD

**Issue by jackfoxy** [microsoft/terminal#1682]
# Environment

```
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

powershell
```

# Steps to reproduce

1) open powershell terminal from pinned taskbar shortcut
2) do something to create output, e.g ls
3) grab edge of terminal with mouse and increase size
4) create more terminal output. Note output only consumes original footprint
5) control-t to open new tab
6) note that in new tab the entire terminal window is used for output

# Expected behavior

the entire terminal window should be used for output after resize of window

# Actual behavior

window resize does not use full window for output

**Comment by DHowett-MSFT** [comment]
I believe this is the other side of #1465.
