### ISSUE TITLE
Renderer encountered an unexpected error: -2005270524

### ISSUE THREAD

**Issue by patridge** [microsoft/terminal#16842]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Open Windows Terminal

### Actual Behavior

Warning dialog: `Renderer encountered an unexpected error: -2005270524`
When I click OK, it drops to the Terminal window where it says "This terminal has encountered an issue with the graphics driver and it could not recover in time. It has been suspended." with a Resume button.
Clicking the Resume button brings back the Warning dialog.

**Comment by patridge** [comment]
I found a bunch of those similar issues, and maybe this is just another of the same with a different error number. Sorry in advance if so. I tried the [`dxcpl` approach](https://github.com/microsoft/terminal/issues/13985#issuecomment-1246111446), but it never seemed to do anything.

**Comment by patridge** [comment]
And just like that, it's gone. I restarted the machine and installed a new driver from Nvidia, and Terminal is working again. 🤷

No idea what caused the issue or how to get details about what the issue was, but it's gone now.

**Comment by lhecker** [comment]
The error is `DXGI_ERROR_UNSUPPORTED` and the description is:
> The specified device interface or feature level is not supported on this system.

I was already a bit worried that I forgot to do some feature checks somewhere and started investigating. I'm glad to hear that the issue was resolved after a restart. Maybe it was just an internal driver bug.
