### ISSUE TITLE
Windows Terminal v1.18.10291.0

### ISSUE THREAD

**Issue by fredswims** [microsoft/terminal#16843]
### Discussed in https://github.com/microsoft/terminal/discussions/16620

<div type='discussions-op-text'>

<sup>Originally posted by **DHowett** January 30, 2024</sup>
This is the last servicing update to Windows Terminal 1.18 (hopefully!), which is being released so that Windows
can integrate it without moving to 1.19.

> **Note**
> This version began rolling out to the Beta and Retail channels on 2024-01-30.

### Why are there so many assets? How do I choose?

Please visit our page documenting the different [Windows Terminal Distributions]!

## Bug Fixes

* During RTF export, we will now use a background color directive that Microsoft Word understands (#16035) (thanks @tusharsnx!)
* _Once again,_ we've fixed another issue where Terminal will spontaneously fail to load Cascadia Mono (#16323)
* `ReadFile` with a too-small buffer size will no longer corrupt your input stream and drop events (#16313)
* We've fixed which glyph we use for the `SUB` control character (#16559) (thanks @j4james!)

### Accessibility

* Color buttons in the settings UI will now announce their RGB values for screen readers (#16544)

### Reliability

* Terminal should no longer crash after you close a couple windows on Windows 10 (#16588) (#16587)
* Two memory leaks in our screen reader integration have been stoppered (#16597) (thanks @glenrgordon!)
* We've eliminated an entire class of shutdown issues by just terminating the process directly when we think it's time (#16575)
* We've stamped out a crash that would occur when closing some tabs (#16412)
* The Azure Cloud Shell integration should no longer crash on a network timeout (#16364) (thanks @reynoldsa!)

## Miscellaneous

* With special thanks to @marcelwgn, @jsoref, @RyanLua, @AtariDreams, @debghs, @mdanish-kh, and @Jvr2022 for
  code quality, documentation, repository management, dependency and spelling updates across the board. We couldn't do
  it without you!

[Windows Terminal Distributions]: https://learn.microsoft.com/windows/terminal/distributions

---

_Binary files inside the unpackaged distribution archive bear the version number `1.18.240129001`._

### Asset Hashes

- Microsoft.WindowsTerminal_1.18.10291.0_8wekyb3d8bbwe.msixbundle_Windows10_PreinstallKit.zip
   - SHA256 `553EBD73160B6053E017C5336889079867CBB182E0249D57A1B32D2344A70D9C`
- Microsoft.WindowsTerminal_1.18.10291.0_8wekyb3d8bbwe.msixbundle
   - SHA256 `C2D91EBB450CA5460C31FB97332240016C9AB33AA969F6A5BBA0A0F159F723A0`
- Microsoft.WindowsTerminal_1.18.10291.0_arm64.zip
   - SHA256 `6AB6073345AAF59E4AD67522767E35710292ADBCCC2026F2F880643B0D36C656`
- Microsoft.WindowsTerminal_1.18.10291.0_x64.zip
   - SHA256 `88EF923BFEDAB00228DDEABB20FA5C88AF6823B7C2910B034F1803336BE07E07`
- Microsoft.WindowsTerminal_1.18.10291.0_x86.zip
   - SHA256 `6D3F082072E068E006A7240A8396124FEA4144A32BCBAFAB3901EC4ECF5DB26A`

<hr /><em>This discussion was created from the release <a href='https://github.com/microsoft/terminal/releases/tag/v1.18.10291.0'>Windows Terminal v1.18.10291.0</a>.</em></div>

**Comment by fredswims** [comment]
Not savvy enough to know what to send you but the current preview ([Windows Terminal Preview v1.20.10572.0](https://github.com/microsoft/terminal/releases/tag/v1.20.10572.0)) and regular release ([Windows Terminal v1.19.10573.0](https://github.com/microsoft/terminal/releases/tag/v1.19.10573.0)) 
**crash immediately when invoked.**
Actually, the terminal window appears. 
I see a  **Powershell tab**, but there is no output from PWSH, and then the window closes.

**Curious enough,** from within PWSH I can run "wt -h" and a window (Help) appears with the options listed.

**Device Specifications:**
Device name	SuperComputer
Processor	Intel(R) Core(TM)2 Quad CPU    Q8200  @ 2.33GHz   2.34 GHz
Installed RAM	8.00 GB
Device ID	D793A681-DE71-4BCD-95AC-70BD2D2B9D2E
Product ID	00330-80000-00000-AA456
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display.

**Edition	Windows 10 Pro**
Version	22H2
Installed on	‎5/‎28/‎2020
OS build	19045.4123
Experience	Windows Feature Experience Pack 1000.19054.1000.0


Yeah, it is an old system but all versions of Terminal have been running with the exception of the current releases.

From Event Viewer 5 Errors appear in Windows Logs/Application. 
**1) Application Error**
Faulting application name: OpenConsole.exe, version: 1.20.2402.26002, time stamp: 0x65dcd575
Faulting module name: OpenConsole.exe, version: 1.20.2402.26002, time stamp: 0x65dcd575
Exception code: 0xc000001d
Fault offset: 0x000000000004f0b8
Faulting process id: 0x31c4
Faulting application start time: 0x01da70f41545b221
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Report Id: 432bf70e-91cb-438f-b782-8e52711ce83a
Faulting package full name: Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**2)Windows Error Reporting**
Fault bucket 2188750374954512994, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.20.2402.26002
P4: 65dcd575
P5: OpenConsole.exe
P6: 1.20.2402.26002
P7: 65dcd575
P8: c000001d
P9: 000000000004f0b8
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D24.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7DC1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7DF1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7DFF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7E5E.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_86e8eb2fb3d880b9e53180d2636482b5c296c18_cc2d9c3d_556ad122-34e5-4e80-8a80-13ec7be152db

Analysis symbol: 
Rechecking for solution: 0
Report Id: 432bf70e-91cb-438f-b782-8e52711ce83a
Report Status: 268435456
Hashed bucket: 99bbb804087177490e6000de992ab262
Cab Guid: 0

**3).Net Runtime**
Application: pwsh.exe
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The application requested process termination through System.Environment.FailFast.
Message: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
Description: The process was terminated due to an unhandled exception.System.Management.Automation.Host.HostException: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
 ---> System.ComponentModel.Win32Exception (233): No process is on the other end of the pipe.
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ConsoleControl.GetConsoleScreenBufferInfo(SafeFileHandle consoleHandle)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

**4)Application Error**
Faulting application name: pwsh.exe, version: 7.4.1.500, time stamp: 0x65680000
Faulting module name: Microsoft.PowerShell.ConsoleHost.dll, version: 7.4.1.500, time stamp: 0x80f778d3
Exception code: 0x80131623
Fault offset: 0x000000000004de0d
Faulting process id: 0x1144
Faulting application start time: 0x01da70f41546eb33
Faulting application path: C:\Program Files\PowerShell\7\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\7\Microsoft.PowerShell.ConsoleHost.dll
Report Id: 467014e9-06da-4edd-b680-ae641c07fe42
Faulting package full name: 
Faulting package-relative application ID: 

**5) Windows Error Reporting**
Fault bucket 1707751399001124455, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pwsh.exe
P2: 7.4.1.500
P3: 65680000
P4: Microsoft.PowerShell.ConsoleHost.dll
P5: 7.4.1.500
P6: 80f778d3
P7: 80131623
P8: 000000000004de0d
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A15.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8CE4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D14.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D24.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8D73.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pwsh.exe_19d5cc854e76e81451fff95645e4a5613fcc9e0_973253be_12495f45-8994-4921-8319-b0bfb080f990

Analysis symbol: 
Rechecking for solution: 0
Report Id: 467014e9-06da-4edd-b680-ae641c07fe42
Report Status: 268435456
Hashed bucket: 43b52180e48757ced7b326d96e236e67
Cab Guid: 0

**Comment by lhecker** [comment]
You've copied the release notes verbatim without any modifications, so I've assumed you were a bot. When you create a new issue, it asks you whether you want to file a "Bug report". If you click that, you'll reach a form which guides you into filling out all the data we need.

In this case however, I know exactly what your issue is: We're currently suffering from a compiler bug. This bug causes our application to crash on old CPUs. The last update we've posted about it is here:
https://github.com/microsoft/terminal/issues/16794#issuecomment-1977347725

To be notified when the issue is fixed, please go to #16794 and click this button:
![image](https://github.com/microsoft/terminal/assets/2256941/3c277561-5bd3-4854-ae4f-3db69db6572e)
