### ISSUE TITLE
Terminal confused after restarting script programmatically (Python)

### ISSUE THREAD

**Issue by sushantshah-dev** [microsoft/terminal#16857]
### Windows Terminal version

1.19.10573.0

### Windows build number

 10.0.22621.3235

### Other Software

Including but but not limited to VSCode terminal

### Steps to reproduce

1. Restart script using:
```
def check_file_changes(self):
        """
        Checks for file changes and reloads the server if any changes are detected.
        """
        for path, _, files in os.walk("."):
            for file in files:
                if file.endswith(".py") and os.path.getmtime(os.path.join(path, file)) > self.init_time:
                    self.logger.warning("File<%s> changed. Reloading server..." % file)
                    os.execv(sys.executable, [f'"{sys.executable}"'] + [f'"{arg}"' for arg in sys.argv])
```
2. Take multiple inputs at start of the script

![Screenshot 2024-03-06 170035](https://github.com/microsoft/vscode/assets/103421781/359c153a-ee23-43e7-98e6-41852042460d)

### Actual Behavior

Terminal confused about input

Another thing that happens when I reload is, I see the line for accepting commands (eg. "C:\Users\XXXX>") before my code output appears... Kind of like, the terminal hallucinates that the program is done running.

**Comment by DHowett** [comment]
So, the problem is that CMD (and PowerShell) only track one process before returning control to the shell. What happens is this...

```mermaid
sequenceDiagram
   create participant cmd
   create participant python as Python PID 1234
   cmd->>python: CreateProcess(python)
   note left of cmd: cmd waits for python to exit
   create participant python2 as Python PID 2345
   python->>python2: CreateProcess(python)
   destroy python
   python-->>cmd: exit()
   note left of cmd: cmd calls ReadInput()
   note right of python2: Python PID 2345 calls ReadInput()
   note left of cmd: cmd calls ReadInput()
   note right of python2: Python PID 2345 calls ReadInput()
```

When python calls `execve` on Windows, it spawns another separate python process to run the script. CMD and PowerShell do not know about it, and so they start to take control back.

This is just one of those really annoying Windows-isms. :/

**Comment by sushantshah-dev** [comment]
Can you suggest an alternative for my restart function?
