### ISSUE TITLE
Environment variables not updating when opened as `wt.exe`

### ISSUE THREAD

**Issue by SainoNamkho** [microsoft/terminal#16854]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22621.1848

### Steps to reproduce

1. Set system default terminal app to Windows Terminal.
2. Open terminal.
3. Change some environment variables
4. Open a new instance or terminal by the same method of opening the previous instance.

### Expected Behavior

The environment variables should be updated in the new windows.

### Actual Behavior

The result is
| Method to open Terminal | Environment variable changed |
|-----------------------------|-----------------------------------|
| win+r then `wt.exe`          | ✔️|
| `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.12.10983.0_x64__8wekyb3d8bbwe\wt.exe` | ❌|
| Press Win key to search `wt` | ❌|
| Win key search `cmd` | ✔️|
| Open Terminal in Win+X menu | ✔️|
| Open Terminal in `shell:appsfolder` | ✔️ |
| By click the item in start menu | ✔️ |

**Comment by zadjii-msft** [comment]
Can you try an updated version of the Terminal/? 1.12 came out _years_ ago, and we've done a lot of work in the 1.18-1.20 timeframe to redo how we handle environment variables.
