### ISSUE TITLE
Unclosable window and no window content rendering when launched with "-embedding"

### ISSUE THREAD

**Issue by gmckeown** [microsoft/terminal#16859]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22621.3155

### Other Software

McAfee/Trellix Endpoint Protection 5.8.0.161. Possibly others, but it was McAfee's SvcHost that was the parent of the Windows Terminal session when it occurred this morning.

### Steps to reproduce

Happens seemingly randomly; assume it's when McAfee agent performs functions that need a terminal. Same effect produced by running:

```"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe" -Embedding```

### Expected Behavior

Not sure what the calling app is trying to do, but I'd at least expect a default PowerShell tab and a blank terminal window (i.e. black background with cursor). Once the process completes, the window should close.

### Actual Behavior

The window frame and decorations render, but there are no tabs and the content area of the window is empty/transparent:

![Screenshot 2024-03-11 093608](https://github.com/microsoft/terminal/assets/22765233/9ca7e6bd-6e99-4e99-97b9-f7513d4eb545)

This window remains open indefinitely and can't be directly closed. If I manually open a tab within the window, I can then close the window.

**Comment by zadjii-msft** [comment]
This looks like /dup #15936 to me, thanks!
