### ISSUE TITLE
Feature Request - F11 for Fullscreen Mode

### ISSUE THREAD

**Issue by ramm32** [microsoft/terminal#1686]
# For productive workflow 
Most of programmers have lots of screens and I personally use it thanks to virtual desktop spaces<br>WIN + TAB
I know this is not critical but having the Fullscreen mode option will be apreciated, just for making lots of instances in every virtual desktop space or screen.

**Comment by DHowett-MSFT** [comment]
#531 please make sure you search before suggesting!
