### ISSUE TITLE
Inconsistent Korean translations in Font Weight settings

### ISSUE THREAD

**Issue by leejy12** [microsoft/terminal#16867]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.3235

### Steps to reproduce

Set Terminal's language to Korean.
Go to Settings > Profiles > Appearance.
Click on "Font Weight(글꼴 두께)" dropdown menu.

### Actual Behavior

Three items have incorrect/inconsistent translations.

|English|Korean|Suggestion|
|-|-|-|
|Thin|얇은|얇게|
|Extra-Light|아주 가늘게||
|Light|밝게|가늘게|
|Semi-Light|약간 가늘게||
|Normal|보통||
|Medium|중간||
|Semi-Bold|약간 굵은|약간 굵게|
|Bold|굵게||
|Extra-Bold|아주 굵게||
|Black|검정||
|Extra-Black|진한 검정||
|Custom|사용자 지정||

**Comment by leejy12** [comment]
Here are my suggestions reorganized using the structure from https://github.com/microsoft/terminal/issues/12665#issuecomment-1546089151.

| Key | Current | Recommendation |
|-|-|-|
|Profile_FontWeightThin.Content|얇은|얇게|
|Profile_FontWeightLight.Content|밝게|가늘|
|Profile_FontWeightSemi-bold.Content|약간 굵은|약간 굵게|

**Comment by lhecker** [comment]
Filed internally as 553104 in the `GlobalCollaborationService` project.
