### ISSUE TITLE
Provide better documentation and samples for default terminal application implementation.

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#16872]
Hello
I think it should be good to provide a better documentation for default application implementation. And it's  also important in order to continue in this philosophy of openness that this project has had since the beginning. It should be cool for some third party terminal to implement it. for example it's a subject already evoqued in felixse/FluentTerminal/issues/965.
It should be also good to have a C++ and C# sample for it.
I searched and I not found any third party default terminal implementation. I think the "problem" come from this pont.
I studed how to do it by reading the code of Windows Terminal and I think because the implementation use [AppExtension](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-an-extension) I think it's not possible to use it for a unpackaged app like [vscode](https://github.com/microsoft/vscode/issues/171102) or [wezterm](https://github.com/wez/wezterm) can you confirm it. So it should be good to have a packaged and also an unpackaged sample for it.

**Comment by zadjii-msft** [comment]
There's a bit more discussion of this over in #9462 - perhaps we should de-dupe these threads?

**Comment by zadjii-msft** [comment]
After thinking on it, yea we should fold this discussion into the thread over at /dup #9462. Thanks!
