### ISSUE TITLE
Windows PowerShell 5.1 profile.ps1 cannot be loaded. A required certificate is not within its validity period

### ISSUE THREAD

**Issue by longtimedeveloper** [microsoft/terminal#16878]
### Steps to reproduce

**This error started yesterday (14 March 2024) after the Windows Update.**

Open Windows 10, Windows PowerShell 5.1 using the start menu
Error immediately appears in console

### Expected Behavior

Windows PowerShell 5.1 to open normally

### Actual Behavior

This error is displayed, 

. : File C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1 cannot be loaded. A required certificate is not within its validity period when verifying against the current system clock or
the timestamp in the signed file.
At line:1 char:3
+ . 'C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by zadjii-msft** [comment]
Sounds like something that needs to be filed over on https://github.com/PowerShell/PowerShell/issues. That's the repo for PowerShell. Thanks!

**Comment by longtimedeveloper** [comment]
@zadjii-msft thank you.  Filed this issue [Windows PowerShell 5.1 profile.ps1 cannot be loaded.](https://github.com/PowerShell/PowerShell/issues/21346)
