### ISSUE TITLE
STILL Can't bypass DOSkey macro with leading space

### ISSUE THREAD

**Issue by cniggeler** [microsoft/terminal#16875]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22621.3296

### Steps to reproduce

Please see [#4189](https://github.com/microsoft/terminal/issues/4189). It is the exactly the same. This was merged with [#13476](https://github.com/microsoft/terminal/pull/13476) which was closed-fixed, but it is not fixed. Since I can't reopen 4189 I've created a new one here per github rules.

### Expected Behavior

If you put a space before a DOSKey macro that has the same name as a built-in command, the built-in command is supposed to run.

### Actual Behavior

The DOSKey macro runs.

**Comment by DHowett** [comment]
@lhecker did we regress this in the cooked read rewrite of 2023?

**Comment by DHowett** [comment]
@cniggeler _weird!_ I absolutely can bypass DOSkey macros with a leading space.

<img width="430" alt="image" src="https://github.com/microsoft/terminal/assets/189190/c6bacbf2-b6dd-4284-a144-cd72377031a5">

![image](https://github.com/microsoft/terminal/assets/189190/6a533094-7e62-4d81-9ef5-0b5dbe84d00e)

Can you share more information about your setup?

**Comment by DHowett** [comment]
FWIW, from the exact repro steps

![image](https://github.com/microsoft/terminal/assets/189190/9365ea28-2c95-44a6-b4ce-fe97a13d1558)

**Comment by cniggeler** [comment]
Here's what I get. Laptop, converted Win-11 S mode to Win 11 Home.
![doskey](https://github.com/microsoft/terminal/assets/16118897/5a0c7cd7-ef77-4f41-99f3-b1556f9bef48)

**Comment by lhecker** [comment]
That's not Windows Terminal though, so it can't have the fix. The older Windows Console Host that you're using only gets updates every couple years when there's a large Windows update. The next update will come out later this year and will have the fix.

**Comment by cniggeler** [comment]
My bad. I thought that conhost was a part of terminal. I have opened a wt.exe session with default Command Prompt and the space in front of the command does work as it should! Closing this ticket...

**Comment by iamqiz** [comment]
@DHowett   the first  "dir" is "dir /b"
the second "dir"  is original dir
they are not same

**Comment by DHowett** [comment]
@iamqiz you demonstrated bypassing the alias `abc` by putting a space in front of it. That is the intended behavior. The bug in this report was that it did not work. It works now. The `dir` example is the same premise.

If you are having an issue which is not “I cannot *bypass* an alias by adding a space in front of it”, please file a new issue.
