### ISSUE TITLE
Renderer encountered an unexpected error: -2147024809

### ISSUE THREAD

**Issue by amangit007** [microsoft/terminal#16882]
### Windows Terminal version

1.19.10573.0

### Windows build number

22631.3155

### Steps to reproduce

Just open the command prompt or Powershell

### Expected Behavior

It should open normally

### Actual Behavior

when I try to open a command prompt or Powershell, the Error message pops up as shown in ss attached.
![Screenshot (28)](https://github.com/microsoft/terminal/assets/65654655/13e6f668-cebe-41f3-a921-a25bae89afc4)
![Screenshot (29)](https://github.com/microsoft/terminal/assets/65654655/7b97c802-897a-4687-9d4d-f30d7c025e79)

**Comment by zadjii-msft** [comment]
What font are you using? Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by lhecker** [comment]
@zadjii-msft -2147024809 is 0x80070057 which is "The parameter is incorrect."
I suspect it's something similar to this: https://github.com/microsoft/terminal/issues/15601#issuecomment-1931021701

On top of sharing your settings.json file, could you please give us more information about your hardware, specifically what exact GPU you're using? Also, please check that you're using the latest graphics drivers.
