### ISSUE TITLE
Windows Terminal and wsl.exe broken

### ISSUE THREAD

**Issue by microwin7** [microsoft/terminal#16880]
### Windows Terminal version

1.20.10572.0

### Windows build number

10.0.19045.4046

### Other Software

wsl.exe 2.1.4.0

### Steps to reproduce

By default, Ubuntu 22.04 is set to open, I see an error, if I try to run cmd or powershell, it doesn’t show me anything, a blank window opens for a while and closes. I can no longer even open the CMD console and powershell. Ubuntu, through its standard package, the console opened yesterday. While I was trying to fix the system, applications from the Start panel could open separately from the Windows Terminal
Log:
```
Имя сбойного приложения: OpenConsole.exe, версия: 1.20.2402.26002, метка времени: 0x65dcd575
Имя сбойного модуля: OpenConsole.exe, версия: 1.20.2402.26002, метка времени: 0x65dcd575
Код исключения: 0xc000001d
Смещение ошибки: 0x000000000004f0b8
Идентификатор сбойного процесса: 0x1be8
Время запуска сбойного приложения: 0x01da77040821acc5
Путь сбойного приложения: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Путь сбойного модуля: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Идентификатор отчета: 6d0c1980-1f31-4492-970c-1cc4b9405d15
Полное имя сбойного пакета: Microsoft.WindowsTerminalPreview_1.20.10572.0_x64__8wekyb3d8bbwe
Код приложения, связанного со сбойным пакетом: App
```
![image](https://github.com/microsoft/terminal/assets/12544425/d4397b1d-d9e6-4cc1-a725-4fc2ab5d4782)
![image](https://github.com/microsoft/terminal/assets/12544425/cc17a65f-0719-4382-989e-61241ceae6ff)
I don’t know if this is related or not, but almost everything broke for me immediately after yesterday’s system and Visual Studio updates, so I’ll attach a log from them too
![image](https://github.com/microsoft/terminal/assets/12544425/a6014d96-e423-46fa-bb95-be9aa1e37898)
```
Имя сбойного приложения: ServiceHub.IdentityHost.exe, версия: 4.4.4171.58464, метка времени: 0x64767b7c
Имя сбойного модуля: coreclr.dll, версия: 8.0.324.11423, метка времени: 0x65cd500d
Код исключения: 0xc0000005
Смещение ошибки: 0x000000000018c5e4
Идентификатор сбойного процесса: 0x2b10
Время запуска сбойного приложения: 0x01da76def29f7755
Путь сбойного приложения: I:\Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.Dotnet.x64\ServiceHub.IdentityHost.exe
Путь сбойного модуля: I:\Visual Studio\2022\Community\dotnet\net8.0\runtime\shared\Microsoft.NETCore.App\8.0.3\coreclr.dll
Идентификатор отчета: bc4dbd8b-6d7b-4c2a-b967-d9f61c67ec31
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
```
```
Не удается найти описание для идентификатора события 1023 из источника .NET Runtime. Вызывающий данное событие компонент не установлен на этом локальном компьютере или поврежден. Установите или восстановите компонент на локальном компьютере.

Если событие возникло на другом компьютере, возможно, потребуется сохранить отображаемые сведения вместе с событием.

К событию были добавлены следующие сведения: 

Application: ServiceHub.IdentityHost.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FF8B515C5E4 (0x00007FF8B4FD0000) with exit code 0x80131506.


Элемент не найден
```

### Actual Behavior

[https://imgur.com/a/Ooguxrf](https://imgur.com/a/Ooguxrf)
[https://imgur.com/a/HPAhXDf](https://imgur.com/a/HPAhXDf)

**Comment by microwin7** [comment]
[settings.json](https://github.com/microsoft/terminal/files/14619602/settings.json)
[state.json](https://github.com/microsoft/terminal/files/14619603/state.json)
[elevated-state.json](https://github.com/microsoft/terminal/files/14619604/elevated-state.json)

**Comment by microwin7** [comment]
I tried to reinstall, still the same, now a window with powershell opens for a second and closes

**Comment by microwin7** [comment]
I tried the regular Windows Terminal from the Store, same thing

**Comment by microwin7** [comment]
![image](https://github.com/microsoft/terminal/assets/12544425/c3ab736e-a0f5-4c06-bbaf-f1de4b6a0559)
Now a separate CMD window, Ubuntu and the wsl command are executed

**Comment by a-usr** [comment]
It would be very helpful if you could translate your images.

**Comment by a-usr** [comment]
Basically youre saying that Windows Terminal Crashes directly upon startup?

**Comment by a-usr** [comment]
Additionally, could you tell me what cpu you are using? There is currently an issue that involves an incompatibility with older hardware.

**Comment by zadjii-msft** [comment]
Yea, this does sound a bit like #16794. Could you add what CPU you're using/?

**Comment by a-usr** [comment]
> Yea, this does sound a bit like #16794. Could you add what CPU you're using/?

I just compared the error code from the [windbg result](https://github.com/microsoft/terminal/issues/16794#issuecomment-1973822229) over there and the error code in the event [viewer output](https://private-user-images.githubusercontent.com/12544425/313299399-cc17a65f-0719-4382-989e-61241ceae6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzgzNTAsIm5iZiI6MTcxMDgzODA1MCwicGF0aCI6Ii8xMjU0NDQyNS8zMTMyOTkzOTktY2MxN2E2NWYtMDcxOS00MzgyLTk4OWUtNjEyNDFjZWFlNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4NDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NzU0YWRjMzY3OWI5MzhmN2U2YmFmMzA4MzNmNjkzNWNmYWNkMzFiZDEyOTA3NDYyZGU1NjcyMWE4NDgzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmRBHE44oGGHrVML7YIIJa-RJCe8e4eiMS4Oz-iWvSg) and they are the same

**Comment by microwin7** [comment]
> Basically youre saying that Windows Terminal Crashes directly upon startup?

Yes

**Comment by microwin7** [comment]
> Additionally, could you tell me what cpu you are using? There is currently an issue that involves incompatibility with older hardware.

Intel Core 2 Duo

**Comment by microwin7** [comment]
> Yea, this does sound a bit like #16794. Could you add what CPU you're using/?

up

**Comment by microwin7** [comment]
I will say that everything worked fine for me before, before updating WSL, which updated itself, but without Windows Terminal WSL continues to work fine

**Comment by microwin7** [comment]
And yes, I do not have second-level virtualization support for addresses, which for me is only a problem to install WSL 2 or Docker

**Comment by microwin7** [comment]
I use WSL 1 and just as easily connect to it via VS Code Server

**Comment by microwin7** [comment]
I don’t really want to back up my WSL for testing and delete it to check if Windows Terminal works after that

**Comment by microwin7** [comment]
https://github.com/microsoft/terminal/issues/16794#issuecomment-2010591275
Work for me!

**Comment by zadjii-msft** [comment]
Great! Thanks for following up!
