### ISSUE TITLE
Problem with pasting in broadcast mode

### ISSUE THREAD

**Issue by uestcgxh** [microsoft/terminal#16883]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.0

### Steps to reproduce

I opened 10 terminal windows in a tab and enabled broadcast mode. When I pressed Ctrl+V to paste some text, only two of them entered content, while the other windows did not paste content in.

### Expected Behavior

I hope the pasted content appears in all ten windows

### Actual Behavior

Only two windows show pasted content

**Comment by amnweb** [comment]
I also discovered that error today when I was setting up two identical servers, Ctrl+V sometimes paste text in both sometime in one in broadcast mode.

**Comment by zadjii-msft** [comment]
I believe we're tracking this over in /dup #16287, thanks!

**Comment by uestcgxh** [comment]
> I believe we're tracking this over in /dup #16287, thanks!

Thank you, The issue I raised is indeed similar to the one in #16287 . I hope you can fix it as soon as possible, because Windows Terminal is really useful
