### ISSUE TITLE
Issue with Non-interactive Behavior of Command Execution in Multi-tab Setup

### ISSUE THREAD

**Issue by brupelo** [microsoft/terminal#16896]
### Windows Terminal version

1.19.231113002-preview

### Windows build number

Microsoft Windows [Version 10.0.19045.4170]

### Steps to reproduce

Consider below run.cmd:

```
set COMMAND=cmd /k "vd && va venv && cls && python setup.py start"

wt -w %~n0 ^
nt --title="svc1:5000" --startingDirectory=%svc1% %COMMAND% ; ^
nt --title="svc2:5001" --startingDirectory=%svc2% %COMMAND% ; ^
nt --title="svc3:5002" --startingDirectory=%svc3% %COMMAND% ;
nt --title="svc4:5004" --startingDirectory=%svc4% %COMMAND%
```

I am writing to bring to your attention an issue I encountered while using a script to spin up multiple tabs in the terminal for running Python microservices.

The script I am utilizing successfully spins up multiple tabs, each intended to enable a virtual environment and launch a local server for a Python microservice. However, upon closer inspection, I noticed that the commands within each tab are not executed immediately upon opening the tab. Instead, they execute only when I manually click on each tab. This behavior suggests that the processes are non-interactive, which is not the desired functionality.

Could you please guide me on what might be causing this issue? I am eager to ensure that the script functions as intended, allowing for the automated deployment of the microservices without any delays or manual input.

Any insights or suggestions you can provide would be greatly appreciated.

Thank you for your attention to this matter.

### Expected Behavior

Ideally, I would like the commands within each tab to start executing immediately upon opening, without requiring any manual intervention. This would ensure that the microservices are up and running seamlessly without any human interaction.

### Actual Behavior

The commands within each tab are not executed immediately upon opening the tab

**Comment by brupelo** [comment]
The simpler way to reproduce this one is just using some sysadmin tool such as https://www.nirsoft.net/utils/cports.html or https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer . You can see how process are not forked until you click the tabs

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #13136 for more discussion.

/dup #13136
