### ISSUE TITLE
Windows Terminal not displaying ubuntu (from WSL) icon when right clicked in taskbar.

### ISSUE THREAD

**Issue by thisisRounakSingh** [microsoft/terminal#16890]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.3296

### Other Software

[Ubuntu With WSL](https://learn.microsoft.com/en-us/windows/wsl/about)

### Steps to reproduce

[Install WSL by following this guide](https://learn.microsoft.com/en-us/windows/wsl/install)

- Pin Windows Terminal in the taskbar
- Right click on it to see the icon of ubuntu (or Linux distro you installed) in the right click menu.

### Expected Behavior

Right click menu should display the ubuntu icon in the taskbar.

### Actual Behavior

When right clicked it does not display the ubuntu icon which I installed from WSL just mentions the name.

![image](https://github.com/microsoft/terminal/assets/136148024/f751638b-1237-401c-86bf-7d2a95442585)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #10552 for more discussion.

/dup #10552
