### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by yhw-miracle** [microsoft/terminal#1689]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18362.175]
Windows Terminal version (if applicable): Version 0.2.1715.0

Any other software?
```

# Actual behavior
Under window10 system, terminal cannot move window.

**Comment by yhw-miracle** [comment]
![image](https://user-images.githubusercontent.com/25102203/60309210-40e29c00-997f-11e9-80c2-f4712baea2c4.png)
Clicking the red arrow area can move the terminal's window. But there is no use in lagre area in front of the plus.

**Comment by DHowett-MSFT** [comment]
yes, please search for existing issues #1375 #564
