### ISSUE TITLE
Feature Request: Allow WSL distros and other shells to load metadata into terminal

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/terminal#1690]
The names of WSL distros in terminal are currently sourced from their names registered in the WSL API.

This is problematic for us in particular because we changed distro names and this leads to user confusion. See https://github.com/microsoft/WSL/issues/4241. Some of the other WSL distros have unfriendly names as their WSL API names, so this is not unique to us.

We would propose that Windows Terminal allow WSL distros and other Store packages, such as the Python package, to override their default WSL listing.

One option would be to include a .json in the [WSL distro template](https://github.com/microsoft/WSL-DistroLauncher) that is added to Windows Terminal on installation with a custom name, the distro executable name (e.g. Pengwin.exe), link to an icon file, and possibly a custom default color scheme.

Thank you for your consideration.

**Comment by zadjii-msft** [comment]
oh my gosh

@PankajBhojwani This is proto-extensions.

There was an issue this whole time
