### ISSUE TITLE
Terminal crashs after an error message 'There is no distribution with the supplied name'

### ISSUE THREAD

**Issue by zeyu203** [microsoft/terminal#1692]
# Environment

pc: thinkpad x1c
cpu: Intel i7-7500U
gpu: Intel HD Graphics 620
memory: 8GB
os: windows10 1832.175

# Steps to reproduce

I installed windows terminal(preview) in Microsoft Store, then I clicked the icon to start it. Surprisingly, it crashed.

# Actual behavior

It was so fast that I didn't see any word in it earlier, I think it is just like #1364 , I found the following info in system error log:
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-06-28T01:24:33.401096400Z" /> 
  <EventRecordID>2813</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-I4MNSMJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WindowsTerminal.exe</Data> 
  <Data>1.0.1906.20005</Data> 
  <Data>5d0c1459</Data> 
  <Data>TerminalApp.dll</Data> 
  <Data>1.0.1906.20005</Data> 
  <Data>5d0c140d</Data> 
  <Data>c0000005</Data> 
  <Data>000000000003a539</Data> 
  <Data>598</Data> 
  <Data>01d52d503b8fa64f</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\TerminalApp.dll</Data> 
  <Data>2068bb0f-9ffe-446c-b6a7-c0f52dcb737d</Data> 
  <Data>Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

After many attempts, I used the 'print screen' button to see the error message in windows terminal window:
![QQ截图20190628092434](https://user-images.githubusercontent.com/5253434/60311559-54dfcb00-998a-11e9-820c-5349f550c8b7.png)

It means: "There is no distribution with the supplied name"

I thought maybe it because that the profile of wsl was wrong, so I tried to look for the profile.json in whole my disks, but I could not find it anywhere.

Some useful imformation is that everytime, when I start my windows terminal, CPU load goes up immediately, and at same time GPU load goes 100%
My wsl is ubuntu 18.04 LTS, I think the error is because of  the space in it name, but I don't know how to deal with it.

Thanks

**Comment by zeyu203** [comment]
Just as I guessed, I tried to uninstall my wsl, it  seems to be right.

**Comment by Shorotshishir** [comment]
the error itself is self-explanatory. There wasn't a distribution with the supplied name. 
It means in your `profile.json` where you configured the path of the WSL i.e. the commandLine parameter, the name wasn't correct, probably a typo. `"wsl.exe -d <name-was-incorrect>"`

**Comment by zeyu203** [comment]
> the error itself is self-explanatory. There wasn't a distribution with the supplied name.
> It means in your `profile.json` where you configured the path of the WSL i.e. the commandLine parameter, the name wasn't correct, probably a typo. `"wsl.exe -d <name-was-incorrect>"`
> 
> _You can reproduce the error just by changing the name and trying to open the terminal WSL_

But I can't find profiles.json anywhere when the error happens, after I reinstalled it and all is right now, I find the profiles.json in directory: AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState
I don't know why, is it aways here but I didn't realize it? I don't think so.

**Comment by miniksa** [comment]
The profiles.json should always be at that location for right now.

We might move it to make it easier to find #1567 or make a UI for it #1564.

But for now, that's where it is.

It looks like this question is answered, so I'm resolving this issue.
