### ISSUE TITLE
The terminal cursor does not flash after using tmux

### ISSUE THREAD

**Issue by huenrong** [microsoft/terminal#16923]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.3296

### Other Software

tmux 3.0a
Linux ubuntu2004 6.2.16-19-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-19 (2023-10-24T12:07Z) x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. Use ssh to connect to the Ubuntu server through the configuration file in Windows Terminal
2. After connecting, the cursor will flash in the Ubuntu default terminal
3. Open tmux in Ubuntu
4. Cursor does not flash in tmux
5. Exit tmux and return to Ubuntu default terminal
6. The cursor does not flash either

### Expected Behavior

1. The cursor can flash when using tmux
2. The cursor can flash after exiting tmux

### Actual Behavior

The cursor does not flash after using tmux

There is no such problem in SecureCRT

**Comment by lhecker** [comment]
This sounds very similar to #10754 but I don't think I've seen this for tmux before.

**Comment by huenrong** [comment]
> This sounds very similar to #10754 but I don't think I've seen this for tmux before.

I remember that I didn't have this problem when I used Windows Terminal some time ago. Recently I found that it had this problem.

**Comment by j4james** [comment]
> I remember that I didn't have this problem when I used Windows Terminal some time ago.

@huenrong Windows Terminal didn't support the escape sequence for changing the cursor blinking state prior to version 1.9, so that's why you may not have had this problem in the past.

As a temporary solution, you can probably work around the issue by setting `TERM=vte-256color` before starting tmux, although that may have other unwanted side effects.

In the longer term, Windows Terminal could add an option to block applications from messing with the cursor blinking state, which was one of the ideas suggested in #10754.

**Comment by huenrong** [comment]
> > I remember that I didn't have this problem when I used Windows Terminal some time ago.
> 
> @huenrong Windows Terminal didn't support the escape sequence for changing the cursor blinking state prior to version 1.9, so that's why you may not have had this problem in the past.
> 
> As a temporary solution, you can probably work around the issue by setting `TERM=vte-256color` before starting tmux, although that may have other unwanted side effects.
> 
> In the longer term, Windows Terminal could add an option to block applications from messing with the cursor blinking state, which was one of the ideas suggested in #10754.

Thanks, after setting TERM, it is okay

**Comment by zadjii-msft** [comment]
Thanks for the discussion all. We'll consolidate this with /dup #10754
