### ISSUE TITLE
Terminal failing to run Powershell/CMD and crashing immediately after 

### ISSUE THREAD

**Issue by retr0cube** [microsoft/terminal#16928]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.19045.4170

### Steps to reproduce

- Open terminal

### Expected Behavior

For Terminal to open and invoke CMD/Powershell

### Actual Behavior

Fails to load CMD/Powershell and results in a crash. (oh-my-posh in pwsh 7 also throws an error)

More info from someone with the same issue and syptoms https://github.com/microsoft/terminal/issues/16843#issuecomment-1984880997

**Comment by lhecker** [comment]
I believe this is the same issue as #16794.
You can find a test build with the fix here: https://github.com/microsoft/terminal/issues/16794#issuecomment-2010591275
Unless anything goes wrong an update for the regular Windows Terminal should be released later today.

**Comment by DHowett** [comment]
Were you able to test this with 1.19.10821.0?

**Comment by retr0cube** [comment]
> Were you able to test this with 1.19.10821.0?

Yes, it does! thanks!

I think it has to do with #16907
