### ISSUE TITLE
Emoji  🕷 Spider cannot be correctlly rendered

### ISSUE THREAD

**Issue by terrywh** [microsoft/terminal#1693]
Emoji  🕷 Spider cannot be correctlly rendered： Store Version v0.2.1715.0

![image](https://user-images.githubusercontent.com/968222/60318128-6e8e0c00-99a4-11e9-83f8-e425d665370e.png)

maybe duplicate to #900 ?

**Comment by miniksa** [comment]
Yeah @terrywh, I'm just going to track this in #900 since that's already on me and will just be a batch processing of symbols we identify incorrectly. Thanks for your report.
