### ISSUE TITLE
Something wrong with keyboard modifiers processing?

### ISSUE THREAD

**Issue by igorkuzuro** [microsoft/terminal#1694]
Something wrong with keyboard modifiers processing?

We have wrong processing of keyboard input with modifiers... For example: 

```c#
using System;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			ConsoleKeyInfo cki;
			do
			{
				cki = Console.ReadKey();
				Console.Write(" --- You pressed ");
				if ((cki.Modifiers & ConsoleModifiers.Alt) != 0)
				{
					Console.Write("ALT+");
				}
				if ((cki.Modifiers & ConsoleModifiers.Shift) != 0)
				{
					Console.Write("SHIFT+");
				}
				if ((cki.Modifiers & ConsoleModifiers.Control) != 0)
				{
					Console.Write("CTL+");
				}
				Console.WriteLine(cki.Key.ToString());
			}
			while (cki.Key != ConsoleKey.Escape);
		}
	}
}
```

Same keys sequence is pressed... <kbd>1</kbd> <kbd>2</kbd> ... <kbd>0</kbd> <kbd>RCtrl</kbd>+<kbd>1</kbd> <kbd>RCtrl</kbd>+<kbd>2</kbd> <kbd>RCtrl</kbd>+<kbd>3</kbd>... <kbd>RCtrl</kbd>+<kbd>0</kbd>
<kbd>LCtrl</kbd>+<kbd>1</kbd> <kbd>LCtrl</kbd>+<kbd>2</kbd>  <kbd>LCtrl</kbd>+<kbd>3</kbd> <kbd>LCtrl</kbd>+<kbd>4</kbd>

We have some, but also wrong result only for <kbd>Ctrl</kbd>+<kbd>2</kbd>... Shift modifier added.

![image](https://user-images.githubusercontent.com/1778999/60325129-392af380-998f-11e9-962b-354f7c755531.png)

Same behaviour also with more complicated software -  "Far Manager" for example (in this situation problem not with simple Console.ReadKey but with keyboard events processing. In this example we don't see any reactions of software on pressing <kbd>Ctrl</kbd> like we can see in old console. So problems also with keyboard modifiers).

**Comment by DarthJahus** [comment]
I've got an issue with this. When I press `ALTGR+à` to write @ on French layout keyboard, it writes `à`. This makes it unusable with a French keyboard.

**Comment by DHowett-MSFT** [comment]
@DarthJahus that is the unrelated issue #521, which is fixed and will be released eventually.

**Comment by j4james** [comment]
There are a combination of issues here. First off, we don't correctly support the VT sequences for the number characters when combined with `Ctrl`. Only `Ctrl+2` works, and even then it's only on certain keyboards. This is discussed in issue #3507.

The bigger problem is that the standard VT sequences for transmitting keypresses are limited in what they can represent. So even if we were handling these keys perfectly, there's no difference between the left and right `Ctrl` keys, and something like `Ctrl+2` should show up as the same key as `Ctrl+SPACE` and `Ctrl+@` (which on a US keyboard is `Ctrl+Shift+2`). Potential solutions for this are discussed in issue #879.
