### ISSUE TITLE
Powershell and cmd close immediately

### ISSUE THREAD

**Issue by alpha454** [microsoft/terminal#16947]
### Windows Terminal version

1.19.10573.0

### Windows build number

22631.2861

### Other Software

Only windows

### Steps to reproduce

Hi,
I did a clean install of Windows 11, without any other apps. and everything seemed fine, I tried terminal and it worked with related built-in apps.
I only installed the updates and I immediately noticed that Terminal no longer worked as before, the windows opened, but closed immediately.
I uninstalled the latest possible updates, but it didn't work.
I uninstalled terminal and wps and cmd started working again.
What can be the cause?

[settings.txt](https://github.com/microsoft/terminal/files/14772444/settings.txt)

![Senza titolo](https://github.com/microsoft/terminal/assets/93675164/0be2dea8-bbfd-4090-bfcc-882f0ef61e01)

### Actual Behavior

The window closes immediately.

**Comment by zadjii-msft** [comment]
* Can you try [Windows Terminal v1.19.10821.0](https://github.com/microsoft/terminal/releases/tag/v1.19.10821.0)? 
* do you have MacType installed/?

**Comment by alpha454** [comment]
I installed the .msixbundle version.
For the moment it seems to work, now I'll try to install the latest updates and I'll see.
Thank you
