### ISSUE TITLE
Align "Run this profile as Administrator" Settings Description with Microsoft Style Guidelines

### ISSUE THREAD

**Issue by hellocharli** [microsoft/terminal#16946]
Apologies if this isn't the right tag for this issue.

The setting description for the "Run this profile as Administrator" contains the contraction `it'll`, which is specifically discouraged in the official [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/word-choice/use-contractions).

> Avoid ambiguous or awkward contractions, such as there’d, it’ll, and they’d.

The string in question is on line `982` of `main/src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw`

**Comment by zadjii-msft** [comment]
Yep, this should get fixed. Thanks for catching this!
