### ISSUE TITLE
Bug Report -RESIZE-

### ISSUE THREAD

**Issue by BannGames** [microsoft/terminal#1695]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

When I resize the terminal in ubuntu overlay the text is duplicated.

**Comment by Shorotshishir** [comment]
Please check the issue mentioned and please be a bit more elaborative while reporting a bug/issue. It helps.
Duplicate of #1465

**Comment by miniksa** [comment]
Per @Shorotshishir , dupe of #1465. Closing.
