### ISSUE TITLE
Terminal changes C: to c:

### ISSUE THREAD

**Issue by mikedice** [microsoft/terminal#16988]
### Windows Terminal version

1.19.10573.0

### Windows build number

Microsoft Windows [Version 10.0.22631.3296]

### Other Software

Visual Studio 2022 Developer Command Prompt v17.9.3

### Steps to reproduce

Just open the VS2022 Command prompt in terminal. I see, the root of the C drive (the only drive on the computer) is lower case 'c:\' instead of uppercase 'C:\'. This breaks an important script used by my team for website development. I have a bug for the JS package filed too here: https://github.com/vitejs/vite/issues/16324

While I understand that changing the case of the root of the drive is not technically wrong on Windows since c:\ and C:\ represent the same thing, it should be avoided if possible because some tools and scripts like Vite will be sensitive to that kind of change. What is the reason for the case change? Can it be avoided?

### Expected Behavior

Use the casing for the root drive that is assigned by the operating system.

### Actual Behavior

Terminal does not use the casing for the root drive that is assigned by the operating system and this can break tools that are sensitive to such changes.

**Comment by zadjii-msft** [comment]
* Does this repro if the vintage "Windows Console Host" is set as your default terminal in the settings app?
* In a VS prompt, what is the output of `set HOMEDRIVE & set SystemDrive`?
* Same question, but in a normal CMD tab?
* Does anything look eschew in the Environment Variables settings dialog/?

**Comment by mikedice** [comment]
In my Terminal app Windows Console Host is set as the Default Terminal Application

From VS2022 Command prompt in Terminal
c:\Users\mikedice\source\repos>set HOMEDRIVE
HOMEDRIVE=C:

c:\Users\mikedice\source\repos>set SystemDrive
SystemDrive=C:


From classic command prompt
C:\Users\mikedice>set systemdrive
SystemDrive=C:

C:\Users\mikedice>set homedrive
HOMEDRIVE=C:

I dumped all environment variables and I do see this:
VSCMD_START_DIR=c:\users\mikedice\source\repos 
In fact this is the only place lower case c: is shown

And then I saw that VSCMD_START_DIR=c:\users\mikedice\source\repos  was set in the terminal Command Line property: cmd /k "set VSCMD_START_DIR=C:\users\mikedice\source\repos & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -startdir=auto -arch=x64 -host_arch=x64"
I think I remember now setting that so the vsdevcmd prompt lands where i want it to and in that Command Line I used lower case c:

Guess this issue can be resolved by design

**Comment by DHowett** [comment]
Ah! Thanks for following up.

I usually work around this with the `-SkipAutomaticLocation` argument to `Enter-VsDevShell` or the `-startdir=none` argument to vsdevcmd. That puts Terminal in charge of the starting directory, so you can use the normal Starting Directory setting.

We haven't done this by default for consistency with the existing Developer Shell shortcuts in the start menu.

I'll close this one out! Thanks!
