### ISSUE TITLE
can't copy and paste anything

### ISSUE THREAD

**Issue by XuehaoSun** [microsoft/terminal#16982]
### Windows Terminal version

1.19.10821.0

### Windows build number

22631.3296

### Steps to reproduce

Use the right mouse button or CTRL+c or CTRL+v to copy and paste.

It will expire at random intervals.
During this period the copy and paste functionality of other software works fine.
The copy and paste function returns to normal after about ten minutes of inactivity.

Frequency of occurrence: Every few hours.

### Expected Behavior

copy paste behavior

### Actual Behavior

No response

**Comment by cosmolai** [comment]
I got the same issue. It happens sporadically. It's annoying.

**Comment by hteeyeoh** [comment]
I got the same issue on my side even i remove all the key bindings just remain ctrl + c/v for copy paste it still not working..
My current Windows Terminal Version: 1.19.10573.0

**Comment by hoesheng** [comment]
I'm facing the same issue as well with version 1.19.10573.0

**Comment by cmellazchy** [comment]
Exact same issue here and reproduction steps as mentioned in the original post. It severely affects my productivity. 

Windows Terminal version
1.19.10573.0

Windows build number
22631.3296

**Comment by cmellazchy** [comment]
@zadjii-msft My bad, just to clarify I see the same behavior as OP (quoted below). The VSCode part is not true in my case.

> Use the right mouse button or CTRL+c or CTRL+v to copy and paste.
> 
> It will expire at random intervals.
> During this period the copy and paste functionality of other software works fine.
> The copy and paste function returns to normal after about ten minutes of inactivity.
> 
> Frequency of occurrence: Every few hours.

I am sure that both copy and paste are affected. When I try to copy, the selection gets reset when I press CTRL + C but I do not see the text I've copied in Windows Clipboard history. This happens to me in both PowerShell and WSL from what I've observed. (PowerShell 7.4.1 and WSL 2 with Ubuntu)

**Comment by XuehaoSun** [comment]
> ### Windows Terminal version
> 1.19.10821.0
> 
> ### Windows build number
> 22631.3296
> 
> ### Other Software
> _No response_
> 
> ### Steps to reproduce
> Use the right mouse button or CTRL+c or CTRL+v to copy and paste.
> 
> It will expire at random intervals. During this period the copy and paste functionality of other software works fine. The copy and paste function returns to normal after about ten minutes of inactivity.
> 
> Frequency of occurrence: Every few hours.
> 
> When the bug appears, the following code may appear in the clipboard:
> 
> ```
> const activeEditor = vscode.window.visibleTextEditors;
>             console.log(activeEditor);
>             if (activeEditor) {
>                 const selection = activeEditor.selection;
>                 console.log(selection);
>                 // const selectedText = activeEditor.document.getText(selection);
>                 activeEditor.edit(editBuilder => {
>                     editBuilder.replace(selection, codeContent);
>                 });
>             }
> ```
> 
> I installed vscode but haven't opened and used it in the meantime.
> 
> ### Expected Behavior
> copy paste behavior
> 
> ### Actual Behavior
> No response

Hi guys, I need to update some information:

1. powershell v7.4.1, but when the bug occurs, all windows including cmd and powershell will have this issue.
2. Regarding the vscode part, I haven't been able to reproduce it recently. This may be an accident, or I accidentally copied it at work, but I have no impression. If no one else has encountered it then please ignore it.
3. This is a strange discovery: I noticed that all the people who commented here work at Intel, or at least use Intel's email address. Is this a coincidence? Maybe it's a problem with Intel's work computer environment?
I found that when the bug appeared, when I kept pressing ctrl+v, the task manager showed that the CPU usage of a process named it-agent would increase, but after I killed this process, the copy and paste function returned to normal immediately! I don’t know if this is a random event. **Can anyone help me verify this?**
![image](https://github.com/microsoft/terminal/assets/109065026/4f37e42d-ff4f-42c3-b631-b0fb70b31e35)

**Comment by cmellazchy** [comment]
@XuehaoSun Great find on the Intel work emails!
This bug happened to me twice in the last 30 minutes. I do not believe it's related to the `it-agent` process, at least in my case.
My observations were the same the both times. When the bug happened, I wasn't able to copy anything from the terminal or paste into it.

1. I was ready with my task manager, but I did not notice any CPU/Mem usage increase for the `it-agent` process.
2. I have tried ending the process by clicking on End task in the context menu, but it looks like the process gets restarted almost immediately.

I waited for a while the first time it happened and kept trying to paste every minute and finally after 5-10 mins, I was able to copy/paste. But then it happened again after 15 mins or so, and then again, I just waited, and it worked,

**Comment by kvietmeier** [comment]
I work for Intel - but my GitHub predates that and uses my personal email as the ID/Login.

**Comment by zadjii-msft** [comment]
# 👀

**Comment by atkassen** [comment]
> 3\. This is a strange discovery: I noticed that all the people who commented here work at Intel, or at least use Intel's email address. Is this a coincidence? Maybe it's a problem with Intel's work computer environment?
>     I found that when the bug appeared, I keep pressing ctrl+v multiple times quickly, the task manager showed that the CPU usage of a process named it-agent would increase, but after I killed this process, the copy and paste function returned to normal immediately! I don’t know if this is a random event. **Can anyone help me verify this?**
>     ![image](https://private-user-images.githubusercontent.com/109065026/318786685-4f37e42d-ff4f-42c3-b631-b0fb70b31e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODkxMjMsIm5iZiI6MTcxMjA4ODgyMywicGF0aCI6Ii8xMDkwNjUwMjYvMzE4Nzg2Njg1LTRmMzdlNDJkLWZmNGYtNDJjMy1iNjMxLWIwZmI3MGIzMWUzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQyMDEzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDI5MGVhYjc5YWVjNDU2ZWI3OWQxMTg4ZjZmOTgzN2M5MTNiOThlY2M4Zjg0ODAwYTBjZTE3Nzk5YmExM2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XrYUih_G1N4Ugp04x5IccZb2VGDeQGYPULc5ReiG874)

I have tried this and see the same thing.

**Comment by cmellazchy** [comment]
@atkassen, @XuehaoSun - So, just to confirm, are you saying that the copy/paste issue got resolved when you have killed this process? If so, can you please verify this again and also list the exact steps you've followed to kill it? I had the chance to try this multiple times today when the issue started happening but killing this process didn't work for me as described in my earlier comment https://github.com/microsoft/terminal/issues/16982#issuecomment-2032218201. 

---

I don't believe this is a coincidence now. I was digging just now and found another Intel internal discussion of an employee reporting exactly the same issue posted earlier this week.

Just to summarize the behavior for me:
1. Copy/paste in windows terminal starts getting affected.
2. Until the issue is resolved
    - Copying from a different application (eg: notepad, browser) and pasting in Windows terminal - WORKS
    - Copying from Windows terminal - DOES NOT WORK
3. Check back after some time to see that the issue is resolved, and all the actions work.
4. The same flow repeats after a couple of minutes.

So, I believe paste is still working since it looks like the issue is that when you try to copy from Windows terminal, it doesn't go to clipboard in the first place.

**Comment by murrayma-intel** [comment]
I also work for Intel, and I'm also seeing this on my work PC. If I kill `it-agent` through the task manager and quickly copy & paste something in the terminal, it works again very briefly until `it-agent` starts again. Once it's restarted, I can continue pasting the existing clipboard contents into the terminal, but once I copy a new selection it breaks again.

**Comment by hteeyeoh** [comment]
> Wait, just to clarify - when y'all are pasting, are you seeing the same, seemingly random text from VsCode? Or is that just a red herring?
> 
> We did some work recently around here - in preview 1.19 it looks like we started merging stuff:
> 
> * [Replace WinRT clipboard API with Win32 for pasting #15360](https://github.com/microsoft/terminal/pull/15360) - this should have only affected pasting into the terminal, not copying out of it
> * [Fix conhost clipboard handling bugs #16457](https://github.com/microsoft/terminal/pull/16457) (for 1.20, which was backported to 1.19 stable in [Fix conhost clipboard handling bugs #16618](https://github.com/microsoft/terminal/pull/16618)) - this should have only changed copy/paste for _conhost_, not the Terminal
> 
> For additional info: What are you running in the Terminal? CMD / PowerShell / WSL? Vim?

My issue also occurs on the windows terminal only. VSCode so far dont have any issue for me.

**Comment by XuehaoSun** [comment]
> @atkassen, @XuehaoSun - So, just to confirm, are you saying that the copy/paste issue got resolved when you have killed this process? If so, can you please verify this again and also list the exact steps you've followed to kill it? I had the chance to try this multiple times today when the issue started happening but killing this process didn't work for me as described in my earlier comment [#16982 (comment)](https://github.com/microsoft/terminal/issues/16982#issuecomment-2032218201).
> 
> I was digging just now and found another Intel internal discussion of an employee reporting exactly the same issue posted earlier this week. I don't believe this is a coincidence now.
> 
> Just to summarize the behavior for me:
> 
> 1. Copy/paste in windows terminal starts getting affected.
> 2. Until the issue is resolved
>    
>    * Copying from a different application (eg: notepad, browser) and pasting in Windows terminal - WORKS
>    * Copying from Windows terminal - DOES NOT WORK
> 3. Check back after some time to see that the issue is resolved, and all the actions work.
> 4. The same flow repeats after a couple of minutes.
> 
> So, I believe paste in terminal is still working fine because it looks like the issue is that when you try to copy from Windows terminal, it doesn't go to clipboard in the first place. Pasting from different applications works for me during the time the issue is in effect.

@cmellazchy 
My method of operation is the same as this, although it-agent will still start automatically after killing it, at least for a short period of time (about tens of seconds) I can copy and paste.
It is precisely because of the automatic startup of it-agent that I cannot completely avoid this issue.

**Comment by atkassen** [comment]
I've played around with #17006 for about 30 minutes without any issues copying. In the same time, copying failed, got restored, and failed again in my existing terminal.

**Comment by zadjii-msft** [comment]
We can work on merging #17006, but in the meantime: someone who works at Intel should probably raise this issue with your IT department, so they can figure out whatever is going on with `it-agent`

**Comment by akantak** [comment]
For any Intel IT guy who takes a look here, I've submitted an issue `RITM12576849`.

**Comment by atkassen** [comment]
(From IT) To disable the services that start `it-agent`:
1. Press Win+R and type in "msconfig"; hit enter
2. Go to the "Services" tab
3. Disable "IT Cloud Service" and "Updater Utility Service Components Controller"
4. Click apply, close the window, and reboot

**Comment by rjszuster** [comment]
Disabling "IT Cloud Service" is enough to get the "it-agent" process to not start.

**Comment by filefi** [comment]
facing the same issue as well with version 1.19.10573.0 and 1.20.10822.0. also tried the lastest release, still doesn't works.

**Comment by akantak** [comment]
I tried a workaround from @atkassen, for now, it looks promising. Not sure if it 100% help, so trying to escalate the issue.

**Comment by zadjii-msft** [comment]
@filefi If you're not an Intel employee, mind filing a new thread? I think at this point, we've got critical mass in this thread to suggest that everyone here was hitting the same issue with `it-agent`. (unless of course you have some other process like `it-agent` or "IT Cloud Service" messing with your clipboard as well. )

**Comment by Wee-Free-Scot** [comment]
> Disabling "IT Cloud Service" is enough to get the "it-agent" process to not start.

I can confirm this is a successful workaround for the copy/paste issues for me.

1. I used msconfig to disable "IT Cloud Service" but did not reboot like it wants.
2. I then used Task Manager -> Services to stop the "IT Cloud Service" service (which kills the it-agent process without restarting it).

If I understand correctly, step (2) fixes the issue up to the next reboot and step (1) makes the fix permanent even after reboot.

**Comment by cmellazchy** [comment]
For anyone working at Intel and visiting this thread, I **DO NOT** recommend disabling the `IT Cloud Service` or any other IT startup services without fully understanding its consequences. Relevant Teams at Intel were made aware of this issue, and they are working to get it resolved.

**Comment by XuehaoSun** [comment]
Hi, @zadjii-msft 
In view of the warning from IT, please delete this issue, thanks.

**Comment by murrayma-intel** [comment]
I don't think we should delete the entire issue because IT doesn't like the workaround. Until there's a resolution (either on the Intel IT side or on the Terminal side) we should keep this open so other Intel employees hitting this can find this issue and avoid opening duplicates.

**Comment by filefi** [comment]
copy and paste functionality works properly today since my computer updated to Win11 23H2 22631.3374 last night. I don't know if it is related to this issue.

**Comment by zadjii-msft** [comment]
Yea, I'm not going to be deleting this thread. It's been highly active - if we delete this, inevitably, another thread will get filed, and folks will once again come to the same conclusion. 

That being said, obviously, disabling services from your IT department will probably make them mad at you. They should probably fix their tool, so folks don't need to disable it to be productive any more 😉

**Comment by PhMajerus** [comment]
@zadjii-msft Just a wild guess, but does Terminal by any chance `OpenClipboard` + `CloseClipboard` for each type of data (text + HTML + RTF) when copying, instead of opening once, calling `SetClipboardData` several time and closing only when all clipboard formats are set?

My guess is Intel's tool registers itself as a clipboard format listener (`AddClipboardFormatListener` or `SetClipboardViewer`) to spy on the clipboard, for example to avoid people copying sensitive data by mistake.
So when you `CloseClipboard` after setting a first format, their process takes over the clipboard for inspection, takes a while to decide if the clipboard should be allowed or emptied, and Terminals's immediate next call to `OpenClipboard` to store the next format fails because the clipboard is still open by their watcher process.

**Comment by lhecker** [comment]
The current implementation uses the WinRT clipboard APIs and not those Win32 APIs.

As it turns out, the WinRT API does exactly what you suspected (I apologize for the low DPI):
![image](https://github.com/microsoft/terminal/assets/2256941/7e86c121-2f20-4d0d-a0f2-8720c037ceea)

#17006 on the other hand does what you'd actually expect:
![image](https://github.com/microsoft/terminal/assets/2256941/f222e32c-7ce6-434b-a479-79e027249e41)

I do feel once again validated in my previous statements when it comes to this overall topic. I think I'll spare myself any further comments, however...

---

FYI The above images where generated with an absolutely amazing tool that @wdscxsj showed me recently: [API Monitor](http://www.rohitab.com/apimonitor)

**Comment by murrayma-intel** [comment]
I'm no longer able to reproduce this issue, I think Intel IT must have pushed a fix.

Is anyone else from Intel still seeing this?

**Comment by cmellazchy** [comment]
I've received information that this issue has been resolved. I also haven't encountered this issue after a whole day of using the terminal.

**Comment by cosmolai** [comment]
I haven't encountered this issue couple days.

**Comment by sunwin123** [comment]
I encounter this issue for many days, still annoyed now.
What is the actual reason of this issue?

**Comment by m2021acct** [comment]
I'm reading this because i was experiencing the same issue. Reading this through made me smile a bit, being the guy in charge of installing "it-agent" for some folks certainly sparked my interest. For those with "it-agent" related issues, please know this software is part of the DLP Suite handling data loss prevention for your business, and there seem to be an issue with their agent inspecting copy/paste operations. Please ask your IT Security team to create a ticket and address this bug with the vendor, Proofpoint. Best Regards, the "it-agent" installer. =]
