### ISSUE TITLE
Feature Request - Be able to add others teminals app

### ISSUE THREAD

**Issue by TheMMcOfficial** [microsoft/terminal#1698]
# Summary of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by miniksa** [comment]
This contains no actual details. Resolving.

**Comment by TheMMcOfficial** [comment]
I'm sorry I'm not an expert with Github... My request was commented...

**Comment by zadjii-msft** [comment]
You can edit your `profiles.json` to add additional profiles. There's some documentation being worked on here:

https://github.com/microsoft/terminal/pull/1577/files?short_path=198bce6#diff-198bce656dbd5be314c08f0eeaf09ec4

Though that link will likely break when the PR is completed. The file _will_ live at doc/user-docs/UsingJsonSettings.md

**Comment by TheMMcOfficial** [comment]
Thanks for the hint @zadjii-msft but I can't add it because it needs to be started as Admin and finally it's a complete app and it doesn't use cmd...

**Comment by DHowett-MSFT** [comment]
There is no requirement that Windows Terminal use "cmd" either. Consider adding the "full app" as a profile in `profiles.json` and launching Windows Terminal as admin.

**Comment by TheMMcOfficial** [comment]
I begin to understand the way to write in the profile.json. We need to double the backslash in the path. But even if the terminal is run in admin the console that I try to run doesn't seem to run as admin but it open and automatically close in less than a second.

**Comment by TheMMcOfficial** [comment]
I got it we need to put this as the commandline "cmd.exe /k cd \"C:\\Program Files\\Tivoli\\TSM\\baclient\" & dsmadmc.exe -TCPS=$IPADDR -ID=$USER -PASSWORD=$PASS -CONSOLEMODE"

**Comment by TheMMcOfficial** [comment]
Ok I got it we need those setting:
``{
            "acrylicOpacity" : 0.5,
            "closeOnExit" : true,
            "colorTable" : 
            [
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000"
            ],
            "commandline" : "cmd.exe /k cd \"C:\\Program Files\\Tivoli\\TSM\\baclient\" & dsmadmc.exe -TCPS=$IPSERVER -ID=$USER -PASSWORD=$PASS",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{0caa0dad-35be-5f56-a8ff-afcfffbb6102}",
            "historySize" : 9001,
            "name" : "TSM",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : false
        }``
