### ISSUE TITLE
Tabs are scrolled by the wrong wheel

### ISSUE THREAD

**Issue by Renha** [microsoft/terminal#1699]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18917.1000]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

Horizontal scrolling doesn't work on tabs. For some reason (typo in the code maybe?) vertical wheel does horizontal scrolling instead.

# Expected behavior

1) Point mouse cursor over the scrollable amount of tabs.
2) Use horizontal scroll wheel (second wheel) on the mouse.
3) Tabs are scrolling.

# Actual behavior

1) Point mouse cursor over the scrollable amount of tabs.
2) Use horizontal scroll wheel (second wheel) on the mouse.
3) Tabs aren't scrolling.

**Comment by miniksa** [comment]
This might be an upstream issue to https://github.com/microsoft/microsoft-ui-xaml for the tab control

**Comment by driver1998** [comment]
We should support **BOTH** horizontal and vertical scroll wheel though... (Or are there any way to detect how many scroll wheel a mouse has?)

**Comment by DHowett-MSFT** [comment]
Yeah, this is going to be an upstream issue for microsoft-ui-xaml. Sorry!

**Comment by zadjii-msft** [comment]
Hey this was fixed by _some upstream XAML bug_, which we ingested in _some release before 0.8_. I don't know off the top of my head which PR fixed this, and I don't really want to bisect it, but it **is** fixed, so I'm closing this.
