### ISSUE TITLE
Clipboard not working properly with Windows Terminal Preview

### ISSUE THREAD

**Issue by kvietmeier** [microsoft/terminal#16994]
### Windows Terminal version

1.20.10822.0

### Windows build number

Win32NT   10.0.22631.0 Microsoft Windows NT 10.0.22631.0

### Other Software

Any text based utility or application.

### Steps to reproduce

Open Windows terminal, run commands, then try to copy text output of commands to another application. 

It works the first couple of times then stops.

For example - as soon as I run:
> ssh -vvv user@host
I can't copy any of the debug out from the terminal window.

### Expected Behavior

To be able to seamlessly cut and paste to-from a W T session.

### Actual Behavior

You can't.  Selected text isn't placed in the clipboard.

**Comment by zadjii-msft** [comment]
Looks like #16982 is a pretty active thread about the same recent regression - let's use that to track this issue. Thanks!

/dup #16982
