### ISSUE TITLE
Tab doesn't click in the window's topmost

### ISSUE THREAD

**Issue by tluanga34** [microsoft/terminal#1700]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): Early Preview Build
```

# Steps to reproduce
Put your mouse cursor on the window's topmost coordinate just above tabs and click.

# Expected behavior
I tried to cilck the tab by doing so. It's time consuming to accurately pointing at the tab area. Most of the time users including me just throw mouse cursor at the topmost and click.

# Actual behavior
Tab isn't being clicked because there are space on top of the tab. This is bad UX in my opinion. Space above tab should be removed and should be occupied by the tab all the way to the top.

**Comment by miniksa** [comment]
I'm just going to duplicate this to #1375 because we're very actively working on making the tab experience like what you expect in other applications that have advanced beyond an alpha preview.

Thanks for your feedback.
