### ISSUE TITLE
Missing translation in Settings menu

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#17003]
### Windows Terminal version

1.19.240322001

### Windows build number

10.0.19045.4170

### Steps to reproduce

1. Open the settings menu
2. Navigate to the "Rendering" section

### Expected Behavior

The sentence is displayed in Portuguese, like the rest of the Terminal:
`Use o novo renderizador de texto ("AtlasEngine")`

### Actual Behavior

The entire Terminal is in Brazilian Portuguese (pt-br), but the sentence about AtlasEngine is in English:
`Use the new text renderer ("AtlasEngine")`

![Sem título](https://github.com/microsoft/terminal/assets/165844345/42720855-14e9-4ad0-8d1d-69721657597b)

**Comment by lhecker** [comment]
I believe we may have ingested the wrong version of the .resw files in the release-1.19 branch as the ingestion was based off of `main`. None of the translations contain the `Profile_UseAtlasEngine` key. And the original predates the ingestion by 6 months.

**Comment by carlos-zamora** [comment]
Thanks for filing! We deleted this string so this should be handled once the new version comes out soon. So we're just gonna close this out.
