### ISSUE TITLE
Ability to set/change line-height on focus-mode toggle

### ISSUE THREAD

**Issue by yavorski** [microsoft/terminal#17018]
### Ability to set/change the `line-height`/`cellHeight` when you toggle `focus mode`.

---

When entering `focus mode` geometry is changed so neovim is receiving the unwanted/wasted/not used space on bottom.
In order to remove the neovim bottom unwanted space I want to be able to set/change the `line-height` on `focus mode` toggle.

## Suggestion 

Add `focus-mode-defaults` setting in `config.json` where we can specify the font `cellHeight` when `focus mode` is enabled.

Thank you!

**Comment by carlos-zamora** [comment]
Thanks for the feature request. We've discussed this as a team and we feel that it might be too niche.

Somewhat related: #11111
That issue refers to admin-specific customizations, but the team has discussed in the past the idea of extending that to "focus mode" customizations as well. It's really the same problem all around: how do we determine which appearance to use when there's an intersection of "unfocused", "admin", and (in this case) "focus mode".
