### ISSUE TITLE
Terminal does not remember session, opens with settings

### ISSUE THREAD

**Issue by krzysdz** [microsoft/terminal#17019]
### Windows Terminal version

67ae9f6c3e42e1ad3431ca02123fcfce57eef188

### Windows build number

10.0.19045.4170

### Steps to reproduce

1. Make sure that a default profile exists and Terminal is set up to open windows from previous sessions when started.
2. Open at least 1 non-settings tab
3. Close the window
4. Open Terminal again

### Expected Behavior

The Terminal opens with the same tabs that were open when the window was closed.

### Actual Behavior

Always only the settings tab is opened.

https://github.com/microsoft/terminal/assets/12915102/062ea134-10b5-45e4-af5c-1ea9250aeb54

~~Probably related to #16998. The version that previously worked for me was 9f3dbab7bf442a1d7702bef0058fa2f0ff5736cd.~~
2bcbe6b49208cb2040091b1cd2c9b3df8e69f5bd works fine, so the bug was introduced in #16172.

**Comment by krzysdz** [comment]
The session is correctly restored if an older version (2bcbe6b49208cb2040091b1cd2c9b3df8e69f5bd) is closed and opened in the latest one (67ae9f6c3e42e1ad3431ca02123fcfce57eef188), so the problem is with saving session on close.

**Comment by lhecker** [comment]
I apologize for the issue. We're currently hoping to fix this with #16914.

In the meantime you can hotfix it by commenting out these lines:
https://github.com/microsoft/terminal/blob/67ae9f6c3e42e1ad3431ca02123fcfce57eef188/src/cascadia/TerminalApp/TerminalTab.cpp#L461-L470

**Comment by krzysdz** [comment]
I've just built from dc4026d184df2489276d46de02a222131cd4d333 (#16914) and session restore works fine.
