### ISSUE TITLE
Fish Shell doesn't open in current directory

### ISSUE THREAD

**Issue by vaqxai** [microsoft/terminal#17017]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.0

### Other Software

fish shell v3.7.0

### Steps to reproduce

1. Add fish to windows terminal in a new profile
2. Do not set default starting directory (leave blank for it to be the parent process dir)
3. Launch terminal from explorer by right clicking -> Open Terminal Here

### Expected Behavior

Fish shell opening in the current directory

### Actual Behavior

Fish opens in the last used directory

**Comment by DHowett** [comment]
That sounds like a fish feature. We actually don’t remember starting directories across invocations 😄

**Comment by vaqxai** [comment]
The problem is it doesn't open in the current directory at all. Is there like a environment variable or something that gets set by windows terminal that i can read with e.g. fish config to `cd` into? I also need to `cygpath` that dir because fish runs from cygwin

**Comment by vaqxai** [comment]
Fixed, fish had a hidden config that restored last used dir, ignoring $PWD
