### ISSUE TITLE
New instance behavior: Attach to the most recently used window doesn't work

### ISSUE THREAD

**Issue by stanio** [microsoft/terminal#17015]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.4170

### Other Software

Using [Clink](https://github.com/chrisant996/clink) v1.6.10.d5dce0 with Command Prompt (cmd) – unsure if it makes any difference.

### Steps to reproduce

1. Open a new Windows Terminal window (close any previously opened)
2. Ensure _Settings / Startup / New instance behavior: Attach to the most recently used window_
3. Run a console app/command (f.e. <kbd>Win</kbd>+<kbd>R</kbd>: `cmd /c pause`)

### Expected Behavior

A new tab in the existing Windows Terminal window is opened to handle the console application.

### Actual Behavior

A new Windows Terminal window is opened to handle the console application.

**Comment by zadjii-msft** [comment]
At any point, is anything here running as admin? Or a quake mode window/?

(#15509 and #16487 both have instances where I think defterm plays weird with the remoting we need for glomming)

**Comment by stanio** [comment]
Not running as admin (elevated) and no quake-mode window – I've verified there's no "WindowsTerminal.exe" process in the Task Manager details, before launching the Terminal, and <kbd>Win</kbd>+<kbd>~</kbd> doesn't open a quake-mode window, at this point.

All console applications/commands open in the same new window, if I keep it open otherwise.

**Comment by stanio** [comment]
>   All console apps open in that same window, then.

Ah, and then other instances like "Open in Terminal" Explorer context menu start opening in a new window. 😕
