### ISSUE TITLE
Incorrect full-width char rendering

### ISSUE THREAD

**Issue by xiongnemo** [microsoft/terminal#17016]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.0

### Other Software

[SonicLair.Cli@1.2.0](https://github.com/xiongnemo/SonicLair.Cli) which uses:
[Terminal.Gui@1.6.4](https://github.com/gui-cs/Terminal.Gui/tree/v1.6.4)
Font is attached:
[Sarasa Term SC Light Nerd Font Complete.zip](https://github.com/microsoft/terminal/files/14871774/Sarasa.Term.SC.Light.Nerd.Font.Complete.zip)

### Steps to reproduce

Fire up an application with Terminal.GUI which renders full-width characters using a monospaced font.

I calculate what's the actual length the terminal should render, which shouldn't be the problem:

`SonicLair.Cli/Tools/StringExtension.cs`
```C#
namespace SonicLair.Cli.Tools
{
    public static class StringExtension
    {
        public static int StandardizedStringLength(this string input)
        {
            // each CJK rune is 2 letter width when using a monospaced font
            int length = 0;
            foreach (var c in input)
            {
                length += Rune.IsWideChar(c) ? 2 : 1;
            }
            return length;
        }
        public static string RunePadRight(this string stringToPad, int totalWidth, char paddingChar = ' ')
        {
            int standardizedStringLength = stringToPad.StandardizedStringLength();
            if (standardizedStringLength >= totalWidth)
            {
                return stringToPad;
            }
            return stringToPad.PadRight(totalWidth - (standardizedStringLength - stringToPad.Length), paddingChar);
        }
        public static string RunePadLeft(this string stringToPad, int totalWidth, char paddingChar = ' ')
        {
            int standardizedStringLength = stringToPad.StandardizedStringLength();
            if (standardizedStringLength >= totalWidth)
            {
                return stringToPad;
            }
            return stringToPad.PadLeft(totalWidth - (standardizedStringLength - stringToPad.Length), paddingChar);
        }
    }
}
```

### Expected Behavior

This is a screenshot at `1.19.10302.0`:
![image](https://github.com/microsoft/terminal/assets/38759782/0755c5c6-2f73-4db6-8b34-7ab06f36413a)

This is a screenshot using Windows's terminal:
![image](https://github.com/microsoft/terminal/assets/38759782/bdb2a549-3964-4971-847c-f9675665c6e8)

### Actual Behavior

This is a screenshot at `1.19.10821.0`:
![image](https://github.com/microsoft/terminal/assets/38759782/abd2355c-ff29-4324-832a-b53b6543655f)

It can be inferred that wt renders three instead of two single-char-width when rendering full-width characters.
Also, the first line is missing. I'm not quite sure whether this is related...
P.S. AtlasEngine is enabled for both versions

**Comment by lhecker** [comment]
> This is a screenshot using Windows's terminal:

That's the old "conhost", also known as "Console Window Host" or similar names. Windows Terminal is only the application with tabs.

However, that screenshot is excellent because it reveals what is going on. If you zoom in you can see how after each wide character you have a weird glyph:
![image](https://github.com/microsoft/terminal/assets/2256941/5f21e1a1-1f8a-458d-ae71-b6b4d4b8917c)

I believe you're accidentally writing "garbage" / invalid characters into your output. So far we just happened to ignore them but it seems that now we don't. I think this may be caused by #16825 which was an intentional change.

Could you check with a debugger what characters you're actually writing to the console / terminal? It'd be nice if you could post them here or send us a screenshot!

**Comment by j4james** [comment]
See also https://github.com/gui-cs/Terminal.Gui/issues/2928

**Comment by xiongnemo** [comment]
> That's the old "conhost", also known as "Console Window Host" or similar names. Windows Terminal is only the application with tabs.

Thanks for the clarify!

I created a demo project using [Terminal.GUI](https://github.com/gui-cs/Terminal.Gui/) and set one label to some CJK chars:

```powershell
dotnet new --install Terminal.Gui.templates
dotnet new tui -n myproj
cd myproj
```

`myproj/MyView.Designer.cs`:
```c#
...
this.label1.Text = "こんにちは";
...
```

```powershell
dotnet run
```

Here's the screenshot:
![image](https://github.com/microsoft/terminal/assets/38759782/d8685a87-5825-4c6d-8953-7bf083b94447)

As I dig into issues with that library I found [this](https://github.com/gui-cs/Terminal.Gui/issues/2943#issue-1968769662) and [this](https://github.com/gui-cs/Terminal.Gui/issues/2928). It seems this is an ongoing issue on their side.

Directly running their demo produces the same result:

![image](https://github.com/microsoft/terminal/assets/38759782/afe58bca-5f0e-42da-ba67-7b80c3146ca5)

> Could you check with a debugger what characters you're actually writing to the console / terminal?

I'm not quite familiar with that library's underlying mechanics, so I will open an issue in their repo and close this for now. If there's further issue addressed with wt I will reopen it and add new comments.

Thank you for your time and effort in helping me locate the real issue!

**Comment by xiongnemo** [comment]
> See also [gui-cs/Terminal.Gui#2928](https://github.com/gui-cs/Terminal.Gui/issues/2928)

Yes I'm looking into it

**Comment by tznind** [comment]
Windows drivers in Terminal.Gui (`WindowsDriver` and `v2win`) use 2 different apis in kernel32.dll to write outputs:

- 16 color mode uses `WriteConsoleOutputW`
- True color uses `WriteConsoleW` 

There is not a consistent way of outputting 2 column width characters like `你` using  `WriteConsoleOutputW`.

See: https://github.com/tznind/16-color-console-tests/tree/main

In #4195 I have made 16 color mode off by default.  Previously it was turned on for all terminals that are not Windows Terminal.


> When using `WriteConsoleOutputW` from `kernel32.dll` we are advised to use a 'skip' char after the wide one.

> The test cases are as follows

| Test Case | Written |
|:---------:|:--------:|
| `' '`| `['你', ' ', 'c','d']` |
| `'\0'`| `['你', '\0', 'c','d']` |
| &lt;none&gt; | `['你', 'c','d']` |

> Results:

|     Terminal     |    `' '`   | `'\0'`  | &lt;none&gt; |
|:----------------:|:----------:|-------------|-----|
| Alacritty        |    <img width="40" height="33" alt="image" src="https://github.com/user-attachments/assets/3b8e67c2-7c3e-445e-a55f-167b16e353a4" />    |    <img width="32" height="32" alt="image" src="https://github.com/user-attachments/assets/0f505417-13cd-4358-beaf-79c83bbd0243" /> | <img width="32" height="32" alt="image" src="https://github.com/user-attachments/assets/073f7d7f-701e-48f2-b806-43a96ee206a3" /> |
 | Windows Terminal | <img width="70" height="54" alt="image" src="https://github.com/user-attachments/assets/75836c98-d947-4919-9249-816ad7ed2db7" /> | <img width="70" height="52" alt="image" src="https://github.com/user-attachments/assets/f7ebec79-84eb-4195-adb3-1561fc0f672d" /> | <img width="56" height="53" alt="image" src="https://github.com/user-attachments/assets/f8189101-68ff-4c82-b936-814b5a51141a" />
| cmd.exe (NSimSun font) | <img width="52" height="52" alt="image" src="https://github.com/user-attachments/assets/0a83b395-bacf-4ef8-b2c5-124945e32789" /> | <img width="52" height="53" alt="image" src="https://github.com/user-attachments/assets/ac215526-4c06-4769-842a-659a0fbe895b" /> | <img width="39" height="52" alt="image" src="https://github.com/user-attachments/assets/3dd0b634-a08e-4603-ad6b-36c5a95a6535" /> |
