### ISSUE TITLE
Help page is incomplete

### ISSUE THREAD

**Issue by jacko-png** [microsoft/terminal#17021]
### Windows Terminal version

1.19.10821.0

### Windows build number

Microsoft Windows [Version 10.0.19045.4170]

### Steps to reproduce

1. Run commands such as `wt -h`, `wt --help`, `wt /?`
2. Compare output with Microsoft Learn documentation: https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments

### Expected Behavior

All available options and commands are printed to a dialogue or to the terminal.

### Actual Behavior

A selection of options and commands are printed to a dialogue. This means that information regarding options such as `-d`, the `;` operator and the fact that you can call wt.exe followed by a command to run that command, are not included with each copy of Windows Terminal and the Microsoft Learn page must be referenced.

<img width="557" alt="Windows Terminal Help" src="https://github.com/microsoft/terminal/assets/114323964/b6735369-712a-46d0-a070-6c9c2b039758">

**Comment by jacko-png** [comment]
So, each subcommands has context-specific options. Try `wt new-tab -h`!

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/issues/5560#issuecomment-619329670_
<img width="305" alt="Windows Terminal new-tab Help" src="https://github.com/microsoft/terminal/assets/114323964/148ed4fd-09f3-489a-bef1-07da4f3b7150">

The subcommands have their own pages. For example, `wt new-tab -h` shows the `-d` option. The help pages are not incomplete, I just didn't use -h on subcommands which is standard practice and not a bug.

**Comment by jacko-png** [comment]
So, each subcommands has context-specific options. Try `wt new-tab -h`!

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/issues/5560#issuecomment-619329670_
<img width="305" alt="Windows Terminal new-tab Help" src="https://github.com/microsoft/terminal/assets/114323964/148ed4fd-09f3-489a-bef1-07da4f3b7150">

The subcommands have their own pages. For example, `wt new-tab -h` shows the `-d` option. The help pages are not incomplete, I just didn't use -h on subcommands which is standard practice and not a bug.

**Comment by DHowett** [comment]
Thanks for following up! I wonder if there's a better way for us to surface these docs... 🤔

**Comment by zadjii-msft** [comment]
Yea at the very least, #4134

**Comment by zadjii-msft** [comment]
OR MAYBE A MARKDOWN DOCUMENT? 👀
