### ISSUE TITLE
Min/Max/Close buttons not drawing correctly

### ISSUE THREAD

**Issue by theterminator3000** [microsoft/terminal#1702]
# Environment

```none
Windows build number: 10.0.18362.207
Windows Terminal version (if applicable): Latest pull from Master

Any other software?
```

# Steps to reproduce

Open Terminal to reproduce issue

# Expected behavior

Buttons should show as seen on Store version (Left)

![Annotation 2019-06-28 185753](https://user-images.githubusercontent.com/10560135/60361643-ac0b8d00-99d6-11e9-9aa0-5a23bd02ee9f.png)

# Actual behavior

![Annotation 2019-06-28 185218](https://user-images.githubusercontent.com/10560135/60361595-8f6f5500-99d6-11e9-87fd-1ae4949a9379.png)

**Comment by theterminator3000** [comment]
I think its a bug, but I really like it

**Comment by DHowett-MSFT** [comment]
#1625 is where we are tracking the caption button issues.
