### ISSUE TITLE
[Canary]: Tab tear-off leads to crash

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/terminal#17032]
### Windows Terminal version

1.21.991.0

### Windows build number

10.0.22631.0

### Steps to reproduce

1. Open Windows Terminal Canary.
2. Try tearing off a tab.

### Expected Behavior

The tab is opened in a new WT window.

### Actual Behavior

WT crashes.

**Comment by tusharsnx** [comment]
In debug build on `main`, Closing a tab with the "❌" button also leads to the same crashing behavior. This is not reproducible on the latest Canary build (maybe due to release vs debug build?)

**Comment by tusharsnx** [comment]
Exception: Unhandled exception at 0x00007FFDD7FBEBDF (ntdll.dll) in WindowsTerminal.exe: Indirect call guard check detected invalid control transfer.

![image](https://github.com/microsoft/terminal/assets/55626797/6aea4c5d-f212-45fd-8e44-17c291b3dc9f)

**Comment by lhecker** [comment]
> Indirect call guard check detected invalid control transfer.

Hmm, this is just a hunch, and I apologize for your SSD 😣, but could you try cleaning the entire solution and building it again?

![image](https://github.com/microsoft/terminal/assets/2256941/c6ba8def-9147-4f22-986b-af0b2eedd3ed)

Some of us had this issue happen before and back then it could be resolved with a clean build. My suspicion is that the build system doesn't properly invalidate some compiled objects which results in mismatched vtables.

**Comment by tusharsnx** [comment]
@lhecker Thanks for the info. I'll try doing a clean build next time.

I'm also curious why Canary might crash on tab tear-off 🤔

**Comment by zadjii-msft** [comment]
FWIW I can repro the tear-off crash on my own canary 21.991 (and after upgrading, my 21.1011) here as well. So, it's definitely not just a clean build problem.
