### ISSUE TITLE
Certain characters taking up more than one line in height

### ISSUE THREAD

**Issue by leptr** [microsoft/terminal#1703]
I've only noticed this for a single character type so far, and it's the mesh-like character that is used for progress bars
Here's what I mean
![Untitled](https://user-images.githubusercontent.com/25707449/60362341-f2fe8000-99e0-11e9-9bb8-18379fb0fb06.png)
In the screenshot above the difference in height between the said mesh-like character and the box character is clearly visible, but the extending up on the line above is more clearly visible in this next one
![Untitled1](https://user-images.githubusercontent.com/25707449/60362452-3527c180-99e1-11e9-98b7-4240ddcc0fdc.png)
It's not the biggest of bugs and it's not really that important nor does it need immediate attention, but it is something that is really bothering me and I thought I should point it out.

**Comment by miniksa** [comment]
What character is this specifically? Can you find the unicode codepoint for it? (Or copy the output of that box and put it into a file and upload it?)

**Comment by leptr** [comment]
> What character is this specifically? Can you find the unicode codepoint for it? (Or copy the output of that box and put it into a file and upload it?)

Yes, I have found the character in the character map, here is a screenshot to verify that it is in fact that one
![Untitled](https://user-images.githubusercontent.com/25707449/60387077-687c5600-9a9e-11e9-8b4b-8ecb68819742.png)
And I have highlighted the Unicode value at the bottom
