### ISSUE TITLE
Upgrade Selenium version

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#17048]
Upgrade version of Selenium.

**Comment by DHowett** [comment]
Which vulnerabilities? In which components? It looks like you've upgraded Selenium, which is only used in local testing scenarios -- does Selenium 3 pose a risk to local testing scenarios? Those scenarios don't parse any untrusted data, and they don't access any remote servers.

**Comment by skanda890** [comment]
> Which vulnerabilities? In which components? It looks like you've upgraded Selenium, which is only used in local testing scenarios -- does Selenium 3 pose a risk to local testing scenarios? Those scenarios don't parse any untrusted data, and they don't access any remote servers.

That is what AI told me when I went to verify my code and if it is not correct please let me know what to replace it with.

**Comment by DHowett** [comment]
We'll revisit this once WinAppDriver is compatible.
