### ISSUE TITLE
Unable to open settingsver

### ISSUE THREAD

**Issue by ctron** [microsoft/terminal#1704]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

* Click on "Settings" in the menu
* Or: Press Ctrl+,

# Expected behavior

Settings open.

# Actual behavior

Nothing happens.

**Comment by rdorris** [comment]
Same on two computers.

**Comment by DHowett-MSFT** [comment]
Probably #assocjson

**Comment by DHowett-MSFT** [comment]
Sorry, i really whiffed it there. #1460

**Comment by MarcelVosslamber** [comment]
Also unable to open settings, someone with the same issues?
