### ISSUE TITLE
Incorrect ligatures in CMD shell

### ISSUE THREAD

**Issue by fibbo** [microsoft/terminal#1705]
When opening a command line the prompt shows the cwd, something like this `C:\Users\test>`

Entering now e.g. a `=` turns the last character (`>`) of the prompt message together with the `=` into a greater equal sign.

**Comment by DHowett-MSFT** [comment]
Broadly, because the terminal doesn't know what part of the output is the prompt vs the user input, this isn't _possible_. #757 might make it more possible. Until then, why not set your `PROMPT` to have a space at the end?

**Comment by fibbo** [comment]
> Broadly, because the terminal doesn't know what part of the output is the prompt vs the user input, this isn't _possible_. #757 might make it more possible. Until then, why not set your `PROMPT` to have a space at the end?

I wasn't aware of the `PROMPT` environment variable - thanks for that.
