### ISSUE TITLE
Okay so it keeps crashing being slow and lagging my computer keeps opening and closing so fast sometimes slow doing stuff idk what, I open games stuff like Xbox ROBLOX or EA it freaks out has seizures, and ruins everything either you are hackers injecting viruses or yall screwed up big time, please fix everything, ever since the new update its gotten worse nothing I do fixes it :(

### ISSUE THREAD

**Issue by DanielShively** [microsoft/terminal#17056]
### Steps to reproduce

Okay so it keeps crashing being slow and lagging my computer keeps opening and closing so fast sometimes slow doing stuff idk what, I open games stuff like Xbox ROBLOX or EA it freaks out has seizures, and ruins everything either you are hackers injecting viruses or yall screwed up big time, please fix everything, ever since the new update its gotten worse nothing I do fixes it :(

### Expected Behavior

Okay so it keeps crashing being slow and lagging my computer keeps opening and closing so fast sometimes slow doing stuff idk what, I open games stuff like Xbox ROBLOX or EA it freaks out has seizures, and ruins everything either you are hackers injecting viruses or yall screwed up big time, please fix everything, ever since the new update its gotten worse nothing I do fixes it :(

### Actual Behavior

Okay so it keeps crashing being slow and lagging my computer keeps opening and closing so fast sometimes slow doing stuff idk what, I open games stuff like Xbox ROBLOX or EA it freaks out has seizures, and ruins everything either you are hackers injecting viruses or yall screwed up big time, please fix everything, ever since the new update its gotten worse nothing I do fixes it :(

**Comment by matteodev8** [comment]
How is this related to the Terminal?

**Comment by zeitounmax** [comment]
So you opened a ticket, because you have a problem playing? 
I don't understand and you have to use 1- the cloud 2- Roblox is a virus

**Comment by korewaChino** [comment]
This issue tracker is for bugs related to Windows Terminal, a new, open-source terminal emulator for Windows 10 and later replacing the Windows Console Host (`conhost.exe`), also known as the default emulator for PowerShell and the Windows Command Prompt (`cmd.exe`).

Please explain how Windows Terminal is interfering with your system performance.

**Comment by nothingneko** [comment]
> This issue tracker is for bugs related to Windows Terminal, a new, open-source terminal emulator for Windows 10 and later replacing the Windows Console Host (`conhost.exe`), also known as the default emulator for PowerShell and the Windows Command Prompt (`cmd.exe`).
> 
> Please explain how Windows Terminal is interfering with your system performance.

They probably downloaded some modded or cracked copy of a game and it launches terminal on startup, I’ve seen this many a time.

**Comment by nanopone** [comment]
how does this have anything to do with windows terminal

**Comment by zadjii-msft** [comment]
Yea I'm closing this. Feel free to actually fill out the bug template next time, or maybe add some screenshots, but this doesn't sound like a Terminal issue to me. Thanks!
