### ISSUE TITLE
Slow Winget Upgrade and Stuck icon animation

### ISSUE THREAD

**Issue by aliajboy** [microsoft/terminal#17057]
### Windows Terminal version

1.19.10821.0

### Windows build number

19045.4291

### Other Software

Powershell 7.4.2.1

### Steps to reproduce

just use winget upgrade on some github programs like powershell 7

### Actual Behavior

the problem is `Winget Upgrade` slow download speed. as you can see in the picture below, each 1MB takes 10 seconds to download from github. my download speed is 12.5MB/s. 
another bug I noticed in this version is the animation icon that I illustrated in image is stuck at that positions when doing some jobs!

![aaa](https://github.com/microsoft/terminal/assets/73298440/b4c5bc59-6858-4101-8a1d-0c4915aaa32b)

**Comment by zadjii-msft** [comment]
This doesn't sound like a Terminal issue to me. This may be better suited for https://github.com/microsoft/winget-cli

**Comment by aliajboy** [comment]
Isn't that animated icon for Terminal?

**Comment by zadjii-msft** [comment]
I mean, sure, but the icon gets its state from the CLI application that's running. In this case, the icon looks like it's in the state that winget set it to, which is about 40% full. Note that the taskbar icon for the Terminal is also showing the same percent done - all of that is driven by the CLI application. If winget gets stuck, then winget is going to leave the progress icon in whatever state it got stuck at.
