### ISSUE TITLE
A key binding to disable any other keybindings

### ISSUE THREAD

**Issue by pilgrimlyieu** [microsoft/terminal#17055]
# Description of the new feature/enhancement

I use Vim in Windows Terminal and there's some keys conflicting. I know that I can unbind these keys so that I can use them in Vim, and I know that I can changes these keys binding to other if I still need these helpful actions provided by this amazing project.

However, if I don't want to disrupt the default key bindings (since I'm not able to manage so many keys and I'd believe the default key bindings are assigned more logically), then I hope there's a toggling key to allow me to disable any other key bindings defined default in Windows Terminal when I use Vim or other applications and then enable it again when I need these default bindings.

Sure, this may not be the best way. But this is the best alternative that I can imagine. So it'd be highly appreciated if there're better ways to achieve my will.

And I've searched GitHub issues and haven't found relevant issues. If I missed it, please tell me. Thanks!

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Hey this sounds exactly like #9301. It's a great suggestion, thanks! I' gonna merge this in with that thread. 

/dup #9301
