### ISSUE TITLE
 Customized fonts not working

### ISSUE THREAD

**Issue by ShaneLee-9** [microsoft/terminal#17061]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.22631.3447

### Steps to reproduce

Set the font, choose any one of the fonts

### Actual Behavior

![PixPin_2024-04-15_17-12-36](https://github.com/microsoft/terminal/assets/30720287/85d225af-d1b0-48d8-8d84-f3f1ea29acab)
![PixPin_2024-04-15_17-13-09](https://github.com/microsoft/terminal/assets/30720287/a1a0266b-a77b-4d85-b904-40ee11b86b50)
![PixPin_2024-04-15_17-14-28](https://github.com/microsoft/terminal/assets/30720287/d6f7dd05-654c-4312-9b44-9ea878b2b659)
 I'm warned that I can't find the "D2Coding" font, but I used this font a week ago and it has now been removed from my system.

As you can see, I can't change the font whether I set it via the GUI or change it via the settings.json configuration file.

I tried reinstalling the lower version 1.19.10573.0 and it still has the above problem.

**Comment by zadjii-msft** [comment]
Did you install that font for all users? Or just for your current user/? We've had persistent problems with fonts that aren't installed for all users 🤷

**Comment by inglepriyanka148867** [comment]
Ensure the custom fonts are correctly installed, restart the application, and verify font configuration settings.

**Comment by ShaneLee-9** [comment]
> Did you install that font for all users? Or just for your current user/? We've had persistent problems with fonts that aren't installed for all users 🤷 

The problem I'm having is that I've selected font A, but Windows Terminal tells me can't find font B!

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by lhecker** [comment]
@zadjii-msft I believe this occurs because they're using DxRenderer. It gets the font family from the font file here: https://github.com/microsoft/terminal/blob/39f90921fe68848112165b9258ecb1fb45c85dcc/src/renderer/dx/DxFontInfo.cpp#L257-L313
The warning pops up if that family name does not match the font name in the settings.

This issue has been solved in two ways:
* DxRenderer does not exist anymore. You can only use AtlasEngine in the latest builds.
* #16821 refactored the way we emit renderer warnings, so this can't happen anymore.

@ShaneLee-9 As a workaround you can simply use AtlasEngine until 1.21 is released.

**Comment by ShaneLee-9** [comment]
> Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

Hi, this is my settings.json

[settings.json](https://github.com/microsoft/terminal/files/15008806/settings.json)

**Comment by lhecker** [comment]
Now that you have AtlasEngine enabled, does the error go away? If it still happens for some reason, please feel free to temporarily use our Canary build (our nightly version): https://aka.ms/terminal-canary-installer

**Comment by ShaneLee-9** [comment]
> Now that you have AtlasEngine enabled, does the error go away? If it still happens for some reason, please feel free to temporarily use our Canary build (our nightly version): https://aka.ms/terminal-canary-installer

AtlasEngine enabled, but the problem persists!

**Comment by lhecker** [comment]
Hmm... I see, that's surprising.

Can you please provide a link to the font so I can download it?

**Comment by ShaneLee-9** [comment]
> Hmm... I see, that's surprising.
> 
> Can you please provide a link to the font so I can download it?

https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/D2Coding.zip

**Comment by lhecker** [comment]
Are you certain that this is the exact same font that you're using? It only contains an US English name which is "D2CodingLigature Nerd Font":
![image](https://github.com/microsoft/terminal/assets/2256941/b251bf67-2897-44b5-881b-7ff044cf680b)

There's no mention of "FragmentMono". Do you have a different font installed which is called "FragmentMono"? If so, can you provide a download link for that font as well?

"D2CodingLigature Nerd Font" does properly show up in Windows Terminal 1.19.10821.0 for me:
![image](https://github.com/microsoft/terminal/assets/2256941/b325f48f-3de0-452f-bdeb-112c3efec0d5)

Selecting it doesn't result in any error messages for me either. If I manually enter "FragmentMono Nerd Font" the correct font name shows up in the error message:
![image](https://github.com/microsoft/terminal/assets/2256941/00c11489-a765-477a-9339-5a4f66dc4925)

**Comment by ShaneLee-9** [comment]
> Are you certain that this is the exact same font that you're using? It only contains an US English name which is "D2CodingLigature Nerd Font": ![image](https://private-user-images.githubusercontent.com/2256941/323962483-b251bf67-2897-44b5-881b-7ff044cf680b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY1NzgsIm5iZiI6MTcxMzY4NjI3OCwicGF0aCI6Ii8yMjU2OTQxLzMyMzk2MjQ4My1iMjUxYmY2Ny0yODk3LTQ0YjUtODgxYi03ZmYwNDRjZjY4MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDc1NzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk4NGYxNWE4ZWEzNjIwZTZkZGZhYzU1YThmMmM1ZWQ1MDJlMDM2NDQwNTY5ZWJhZGIyMmM3MWExMzA2ZTgyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dZKX_rLH0SV-aAou7gFkUY_a7mGxL_F4VKPU-u30oBk)
> 
> There's no mention of "FragmentMono". Do you have a different font installed which is called "FragmentMono"? If so, can you provide a download link for that font as well? I know that [Fragment Mono](https://github.com/weiweihuanghuang/fragment-mono) exists, but there's no official "Nerd Font" variant for it.
> 
> "D2CodingLigature Nerd Font" does properly show up in Windows Terminal 1.19.10821.0 for me: ![image](https://private-user-images.githubusercontent.com/2256941/323963289-b325f48f-3de0-452f-bdeb-112c3efec0d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY1NzgsIm5iZiI6MTcxMzY4NjI3OCwicGF0aCI6Ii8yMjU2OTQxLzMyMzk2MzI4OS1iMzI1ZjQ4Zi0zZGUwLTQ1MmYtYmRlYi0xMTJjM2VmZWMwZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDc1NzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzAwZTg3ZjMxNDNmMDIwYzNhMTNmN2QzZDBmZWMyMjVmZGQ5ZTVkYzAxYTNlYTFjN2Y0ZTRjZThhODExNWE2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dD4ujqdFTMMrhzH_UUEoUYJRC9QAvpz5HBVgmXJ23nQ)
> 
> Selecting it doesn't result in any error messages for me either. If I manually enter "FragmentMono Nerd Font" the correct font name shows up in the error message: ![image](https://private-user-images.githubusercontent.com/2256941/323963865-00c11489-a765-477a-9339-5a4f66dc4925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY1NzgsIm5iZiI6MTcxMzY4NjI3OCwicGF0aCI6Ii8yMjU2OTQxLzMyMzk2Mzg2NS0wMGMxMTQ4OS1hNzY1LTQ3N2EtOTMzOS01YTRmNjZkYzQ5MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDc1NzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNlOTczZTdiNTM0ZWQ1Yjg5NzBkYTQ4OTE0YWRiYzdjNGM2ZmU5MTM0NzJhYzVmYTdjYWNhY2E3MTc5ODcwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.upp9LbLfQjptw3HN5VP3aFqIx_aA4uW8HxeDT2d5AVo)

The root cause of my problem is that I installed the font "D2CodingLigature Nerd Font Mono" about a week ago. One day I removed "D2CodingLigature Nerd Font Mono" from my computer and installed "FragmentMono Nerd Font". Then I wanted to change my Terminal font to "FragmentMono Nerd Font". Termina then shows the above error message. It actually can't find the "D2CodingLigature Nerd Font Mono" that I used and deleted.

Translated with DeepL.com (free version)

**Comment by lhecker** [comment]
Oh no. I hope this doesn't mean that your font cache is corrupted. 😣

Can you please try this series of steps? My hope is that this brings the cache back into a good state:
* Open `%LOCALAPPDATA%\Microsoft\Windows\Fonts` and check if the folder is empty. If it's not empty, open the Fonts control panel (search for "fonts" in the start menu):
  ![image](https://github.com/microsoft/terminal/assets/2256941/d06261a7-b041-4326-93e7-148a1427493e)
  Find and delete each corresponding font until the `%LOCALAPPDATA%\Microsoft\Windows\Fonts` folder is empty.
* Download the D2CodingLigature font (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/D2Coding.zip) again and install it for **all users**. 
* Uninstall both, your "D2CodingLigature Nerd Font" and "FragmentMono Nerd Font" fonts simultaneously.

Afterwards, reboot your PC and try installing the "D2CodingLigature Nerd Font" (for all users).

**Comment by ShaneLee-9** [comment]
Oh, I seem to have found the reason. I don’t know when the font of Powershell was set separately in my terminal.
![image](https://github.com/microsoft/terminal/assets/30720287/1f783746-b3bd-4a6f-9523-f7a0137c5344)
![image](https://github.com/microsoft/terminal/assets/30720287/e6cfd432-4ae7-4df2-8474-fb3864de0e66)

**Comment by DHowett** [comment]
Thanks for following up!

**Comment by lhecker** [comment]
I'd like to apologize for not noticing the extra font face entry in your settings file. 😣
I'm glad however, that you were to able to resolve the issue!
