### ISSUE TITLE
URL highlight broken when URL ends at the EOL

### ISSUE THREAD

**Issue by bestis** [microsoft/terminal#17065]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.22631.3447

### Steps to reproduce

- Open Ubuntu terminal
- Set your terminal to X cols
- Run these echo's so that the amount of spaces make the middle one end in the EOL
```
echo 'https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing'
echo '                 https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing'
echo '                  https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing'
```

- Open Windows Powershell
- Run similar echos

- Open Command Prompt
- Run similar echos without the quotes.

### Expected Behavior

All the links open the right webpage.

### Actual Behavior

- Ubuntu, the middle link looses the last letter.
![image](https://github.com/microsoft/terminal/assets/1753286/06d67ebd-a2ea-4826-bb73-0cbf6059c472)
- Powershell, the middle link gets extra PS in the end.
![image](https://github.com/microsoft/terminal/assets/1753286/3aff4ac5-f770-49dc-b908-9d6a6379a211)
- Command prompt, middle link looses the last letter
![image](https://github.com/microsoft/terminal/assets/1753286/aed85484-1f68-4c73-8d23-02ecaffdcad8)

**Comment by bestis** [comment]
My example has no emoji, wide-characters, etc. So doesn't seem related to me.

**Comment by lhecker** [comment]
This likely occurs because the `UTextAdapter.cpp` code doesn't insert newlines between rows. This only becomes apparent when there's a newline at the exact end of the row because then there's no separator between the match (URL) and the remaining text.
