### ISSUE TITLE
Clearer tab title for ssh-configurations immediately running a command like tmux, currently it is just OpenSSH SSH client without hostname

### ISSUE THREAD

**Issue by fjellvannet** [microsoft/terminal#17063]
# Description of the new feature/enhancement

It is possible to specify ssh-configurations, so instead of putting e.g. wsl.exe -d ubuntu, one can write ssh user@hostname into the command line field of the configuration to immediately ssh onto a host when a new tab is opened. When the configuration is like that, the tab title looks like this including the hostname (all good):

![bilde](https://github.com/microsoft/terminal/assets/22413504/2b8faef3-7477-4025-922c-584655468c75)

However, when I change the configuration to ssh user@hostname -t tmux a to immediately attach to a tmux session, I see the following: 

![bilde](https://github.com/microsoft/terminal/assets/22413504/573e84c3-ae2a-4945-92fd-320ce16d5c03)

This is not very handy, as I can't see which host I am connected to, only that it is through ssh. The behaviour is actually exactly the same if I open a powershell tab, and then run ssh user@hostname -t tmux a, also here the title now is just OpenSSH SSH client. If I only run ssh user@hostname in powershell, I see the hostname in the windowtitle as indicated in the first image.

# Proposed technical implementation details (optional)

1. A simple solution to this would be the ability to manually override the tab title for a configuration. Just always show some fixed text.

2. The nicer solution would be to actually fix the behaviour of how the hostname is displayed when the ssh-command is run with the -t option in General, so that it also works when I manually run the command in powershell.

But as option 2 most likely is more complicated / probably requires changes in the openssh client or the powershell configuration, solution 1 would be sufficient for now.

**Comment by fjellvannet** [comment]
The indicated closed issues are similar, but not the same. The problems indicated there have been fixed.

This issue however has not been fixed yet.

**Comment by fjellvannet** [comment]
I found a setting for profiles that is "suppressApplicationTitle", which gives the behaviour I suggested as solution 1. The profile's name will then just be displayed instead of the applicationTitle the process itself returns. 

However, solution 2 would be better if it is possible to get it to work. It is very weird that the windows openssh client only displays a default applicationTitle once the -t option is used.

**Comment by DHowett** [comment]
A potential option 3 would be to [configure tmux to properly propagate the title](https://github.com/tmux/tmux/wiki/Advanced-Use#pane-titles-and-the-terminal-title) from its hosted application up to the terminal emulator! It looks like your shell is configured to emit a title, and that tmux is dropping it. That would also make sure that the title updates when you switch panes inside tmux.

**Comment by inglepriyanka148867** [comment]
you had want to update the tab title for SSH configurations when immediately running a command like tmux. Currently, it displays as "OpenSSH SSH client without hostname," which isn't clear. You could modify the code responsible for setting the tab title to make it more descriptive, perhaps including the hostname.

**Comment by fjellvannet** [comment]
> A potential option 3 would be to [configure tmux to properly propagate the title](https://github.com/tmux/tmux/wiki/Advanced-Use#pane-titles-and-the-terminal-title) from its hosted application up to the terminal emulator! It looks like your shell is configured to emit a title, and that tmux is dropping it. That would also make sure that the title updates when you switch panes inside tmux.

That's genious! What a simple fix. Immediately solved my problem - better than that even. Didn't think far enough myself to realise this was the problem. 

I now just added set -g set-titles on to my tmux conf.

Also, I must say that I am impressed by your insanely fast response time! Thank you so much

**Comment by fjellvannet** [comment]
see my last comment, that's the solution.

**Comment by inglepriyanka148867** [comment]
Hello,
It's my pleasure!
