### ISSUE TITLE
Ability to have a profile that can open multiple tabs

### ISSUE THREAD

**Issue by amarth1982** [microsoft/terminal#1706]
Right now I use cmder and I have a keyboard shortcut that can launch multiple tabs, like, one will start and run the local proxy, the other one for development and one for database

I couldnt do that in current Windows Terminal, it would be nice to have that setup.

**Comment by dnagl** [comment]
@amarth1982 I will have a look on this and try to find a way to implement this functionality ;)
I will keep you up to date

**Comment by Kvanrooyen** [comment]
Something like [#756](https://github.com/microsoft/terminal/issues/756)?

**Comment by amarth1982** [comment]
Yes but not exactly same, if its done at default profile level, I would be able to launch multiple tabs when I launch terminal, instead if I can create a profile that would launch multiple tabs, then I could associate keyboard shortcut to it or still use it as default profile, and also it would not annoy me if I just need one tab for a simple task, I don't have to close others

**Comment by DHowett-MSFT** [comment]
I think we'll tackle them in the same way, so I'll close this as a duplicate. In general, if we think about a _profile_ as a type of configured launchable, we'll need to introduce a new top-level concept (arrangement?) that can be key-bound. It's really similar to opening one tab with multiple panes, each of which is running a different profile. That would also be one of these "arangement"s.
