### ISSUE TITLE
Always open in a new tab

### ISSUE THREAD

**Issue by mattm3** [microsoft/terminal#17064]
# Description of the new feature/enhancement
I'm not sure if this is already possible but is it possible or can it be implemented that tabs are always used. I have it set so the terminal opens in Powershell 7 as admin but if I am in command prompt and want to open a new tab it always opens in a new window. I have tried playing with a number of settings but haven't been successful in making it always open in a new tab no matter what.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Okay I'm gonna try and read between the lines here:
* your default profile is PowerShell 7
* You've set your PowerShell 7 profile to `"elevate": true` (in the settings UI, this is "Run this profile as administrator")
* you open the Terminal (unelevated) and run CMD
* From that unelevated window, you open a new tab. 
  * That uses the default profile, PowerShell 7
  * That opens a new, elevated window

Is that about right? Elevated and unelevated tabs can't coexist in the same Terminal window (as of writing, circa <=1.21). Either all the tabs are unelevated, or all are elevated. 

Now, with the upcoming Windows 11 release with Sudo for Windows, you could probably change your default profile from `pwsh.exe` and `elevate:true` to just `sudo.exe pwsh.exe`, and then just run the Terminal unelevated all the time.

Overall, I'd recommend _against_ having your default profile be `elevate:true`. There's kinda a lot of awkward edge cases with the default profile always wanting to run in an elevated window - this is just one of them

**Comment by mattm3** [comment]
Ah you're right, I was running CMD unelevated, I had them all set to open in admin so thought I was running all of them elevated. Changing them back to unelevated works as I want it to.

Thanks
