### ISSUE TITLE
Dragging and dropping files onto WSL instance still appears with double quotes

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17071]
v1.21.961.0
v1.20.11072.0 (bug bash on 4/16)

#16214 made it so that dragging files onto a WSL session would wrap it in single quotes. Tested it and that's not the case.

**Comment by carlos-zamora** [comment]
This has a similar root cause as #12961. Even though the shell is WSL, the profile source is not "Microsoft.Terminal.WSL" (or something similar).

**Comment by zadjii-msft** [comment]
I'm gonna close this as a /dupe of #12961. "shit's weird with the ubuntu profiles because of Canonical hijinks".
