### ISSUE TITLE
Using "Split tab" on the right-click context menu causes terminal to crash

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17076]
v1.21.1011.0

**Comment by zadjii-msft** [comment]
(almost certainly the same as #17075)

**Comment by AvogatoWizardWhisker** [comment]
It crashes when you want to duplicate tabs as well.


https://github.com/microsoft/terminal/assets/89489853/9d941343-042e-40ff-9dbb-0e89e364f601
