### ISSUE TITLE
Consider using a "system message" after a session restore, instead of ^[2J to clear the screen 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17074]
v1.20.11072.0 (bug bash on 4/16)

Consideration: we could use conpty inherit cursor mode

**Comment by lhecker** [comment]
Reopening for me as a reminder to address the remaining issue of the status message marking 2 lines as gray (https://github.com/microsoft/terminal/issues/17117#issuecomment-2075927637).
