### ISSUE TITLE
Ability to have different startup profile to default profile

### ISSUE THREAD

**Issue by Kore-rep** [microsoft/terminal#17081]
# Description of the new feature/enhancement

Currently the possible startup options are "default" or "previous session". It would be nice to have profile "A" be the startup profile, and profile "B" be the profile used when clicking the "+" symbol.

**Comment by carlos-zamora** [comment]
Thanks for filing! I'm gonna tag this up to #6685, but mark it as a /dup of #445. Being able to customize the profile opened by the new tab button fixes this.
