### ISSUE TITLE
ANSI 24-bit RGB foreground color codes don't display correctly when close to the background color

### ISSUE THREAD

**Issue by nora2605** [microsoft/terminal#17082]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.26100.1

### Steps to reproduce

1. echo an ANSI escape sequence like `\u{001b}[38;2;255;255;255m` (rgb: 255, 255, 255) for the foreground color and `\u{001b}[48;2;0;255;0m` (rgb: 0, 255, 0) for the background color (can be put together into one sequence) and some text to go after it
2. for some specific color values close enough to each other in brightness (?), setting both foreground and background changes the colors. This does not happen when the fore-/background color sequences are alone; but it does happen if there is text between them.
![grafik](https://github.com/microsoft/terminal/assets/51268331/f5a15372-d19c-42c2-8283-19f83670c519)

### Expected Behavior

The colors should be shown accurately when specified like this.
The conhost.exe does this correctly.
![grafik](https://github.com/microsoft/terminal/assets/51268331/c244f7eb-02f1-4249-8236-0eb36caba609)

### Actual Behavior

The foreground color will be way darker or way brighter than expected depending if the background has reached a calculated brightness threshold.

**Comment by DHowett** [comment]
Hey there! Are you using the “adjust the lightness of indistinguishable colors” setting? It’s on the profile appearance page.

**Comment by nora2605** [comment]
I can't believe I didn't see that option the first time.
Thank you!

**Comment by DHowett** [comment]
Sure thing! Thanks for following up :)
