### ISSUE TITLE
Terminal close immediately after open

### ISSUE THREAD

**Issue by PororoManon** [microsoft/terminal#17086]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.22631.0

### Other Software

-

### Steps to reproduce

Dont know how to reproduce it, because it suddenly happens. I do nothing on my terminal other than do npm run/build, and ssh to my local server.

### Actual Behavior

It close immediately after I open it, either through CMD, pwsh or git bash. To make sure its not corrupted or something, I already reinstall it from microsoft store.

https://github.com/microsoft/terminal/assets/148423664/58604394-95c4-430a-a61b-254d3e89fc7f

**Comment by PororoManon** [comment]
I have try the closed similar issues (install the .msixbundle). yes it works, but I cant call it through cmd or pwsh.

**Comment by carlos-zamora** [comment]
> I have try the closed similar issues (install the .msixbundle). yes it works, but I cant call it through cmd or pwsh.

Can you record another video with the new issue you're seeing /?

**Comment by PororoManon** [comment]
> Can you record another video with the new issue you're seeing /?
still same as video I record before. but now I can open Terminal app and it show PowerShell, because I set PowerShell as default. but if I open CMD or PWSH from search, Terminal open and close immediately.

sorry for my bad english, hope you understant what I mean. :D

**Comment by PororoManon** [comment]
Oh... now I can't open the Terminal app either. Last time, I installed a .msixbundle and the Terminal was able to open.
heres the video
https://github.com/microsoft/terminal/assets/148423664/4e444f43-2020-4609-9205-813ddf5d01ff

**Comment by npanagop** [comment]
I've been having the same issue with Terminal v1.19.10821.0 on Windows 11 build 22631 for the last week. Downgrading to [v1.18.10301.0](https://github.com/microsoft/terminal/releases/tag/v1.18.10301.0) solves the issue.

**Comment by zadjii-msft** [comment]
> > Can you record another video with the new issue you're seeing /?
> 
> still same as video I record before. 

Sorry for the confusion, while we were triaging yesterday, github failed to load the video, so we assumed it was corrupted. 

Looks like it's crashing after a small timeout for a defterm launch, but not a direct launch.

Any chance you have MacType installed? (if so, update it. See https://github.com/microsoft/terminal/issues/16730#issuecomment-1952336962 for details)

If you don't have MacType installed:
* Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?
* Can you provide /feedback with the feedback hub?

**Comment by lhecker** [comment]
FYI the direct download link to the latest MacType version that fixes the crash is here: https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31

**Comment by PororoManon** [comment]
Yes I have mactype installed. I update it to [v1.2023.5.31](https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31) and all works! I can call it from CMD and PWSH from start menu. will close this issue. Thanks!
