### ISSUE TITLE
Background repeat mode?

### ISSUE THREAD

**Issue by gigiboeru** [microsoft/terminal#17106]
Hi, I'd like to set an image to repeat itself as background. Think about something like a noise texture. Ideally the option to repeat on x and/or y axis independently, if I'm not asking for too much. 

Alternatively a built-in noise generator might be better. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3193 for more discussion.

/dup #3193
