### ISSUE TITLE
Bold text being rendered with wrong width

### ISSUE THREAD

**Issue by ElectrifyPro** [microsoft/terminal#17102]
### Windows Terminal version

1.20.10822.0

### Windows build number

Microsoft Windows [Version 10.0.19045.4170]

### Other Software

LunarVim 1.3.0
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

Ubuntu > Apperance:
Font face: CaskaydiaMono Nerd Font Mono
Font size: 16
Line height: 1.2
Font weight: Normal

### Steps to reproduce

Try running in the shell:
```
$ printf "\e[1mpressure map pressure map pressure map pressure map\e[0;7mDarn\e[m\n"
```

or:

```
$ printf "\e[1m|----------------------|-------------------|\e[0;7mDarn\e[m\n"
```

The bold text is rendered too wide and gets cut off (see actual behavior). I tried to search similar issues and they all seem to have been fixed by #14959, but I'm still experiencing the problem.

### Expected Behavior

The bold characters should all take up the same space.

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/1387522/6e7ab278-2a34-4426-b24f-3b215c29f0fc)

Mis-aligned Markdown table:

![image](https://github.com/microsoft/terminal/assets/1387522/2a410d44-e0f1-48b3-ade6-ee4378366c2c)

**Comment by lhecker** [comment]
Did you disable `AtlasEngine` in the `Rendering` settings? That can cause this issue.
If you did: Why?

**Comment by ElectrifyPro** [comment]
I have not disabled `AtlasEngine` (it is enabled). Unfortunately, the issue still occurs for me.

**Comment by lhecker** [comment]
The above is a very typical behavior for the old text renderer, which is why I've been assuming that. Is it possible that you accidentally have it disabled for one of your profiles? You can check it if you open your settings.json file (Ctrl+Shift+,) and search for "useAtlasEngine". You can delete any mention of it in the file.
If that doesn't resolve your issue, can you please post your settings.json file here?

**Comment by ElectrifyPro** [comment]
> Is it possible that you accidentally have it disabled for one of your profiles?

That's exactly it 😅 , I had it enabled in the Rendering tab but I didn't realize each profile had it's own `useAtlasEngine` option! Thanks for your help!
