### ISSUE TITLE
Bug Report - Settings function not working

### ISSUE THREAD

**Issue by OSG55** [microsoft/terminal#1710]
# Environment

Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version: 0.2.1715.0

Any other software?
No

# Steps to reproduce

Error (1) - Select settings from the drop down menu via the mouse
Error (2) - Ctrl+ , shortcut

# Expected behaviour

Expected a settings dialogue box/window to appear.

# Actual behavior

For Error (1):
A dialogue window asking "How I would like to open this file" appears.
![2019-06-29 - Error (1) Screenshot](https://user-images.githubusercontent.com/52337094/60377969-1bc55a80-9a5f-11e9-9366-b2f462abec36.png)

For Error (2) - Nothing happens

**Comment by JushBJJ** [comment]
Press more apps then press what ever text editor you want to edit profiles.json in like notrpad or vscode

**Comment by OSG55** [comment]
Thanks
