### ISSUE TITLE
Documentation Issue: optional values SettingsSchema should list default value

### ISSUE THREAD

**Issue by darthwalsh** [microsoft/terminal#1712]
Any optional settings in [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#globals) should have their default value listed. Otherwise, it may require some trial-and-error to determine which setting you are currently using.

A change like #918 then could have update the default values in the docs.

**Comment by DHowett-MSFT** [comment]
This probably doesn't help, but _leaving out an optional value_ will result in _two_ things:

1. the setting will be reset to its default
2. if we change the defaults, it'll automatically update to be the new default
