### ISSUE TITLE
Newly installed PowerShell version did not automatically become default profile

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17123]
### Windows Terminal version

1.21.1094.0

### Other Software

PowerShell 7

### Steps to reproduce

1. Have a fresh machine (or similar config)
2. Install WT Canary
3. Notice that you have the standard profiles of Windows PowerShell, CMD, and ACS
4. Install PowerShell 7 via winget
5. Close and reopen WT Canary

### Expected Behavior

We have code to automatically select PowerShell 7 as your default profile if it was just installed. That should happen.

### Actual Behavior

PowerShell 7 is not the default profile. Windows PowerShell continues to be the default.

**Comment by DHowett** [comment]
FWIW, we _never_ change the user's default profile once they've installed Terminal. Why would we?

**Comment by carlos-zamora** [comment]
Oh. I thought we had code in the PowerShell dynamic profile generator to figure out which PowerShell profile we wanted the user to have and make that the default.

**Comment by DHowett** [comment]
This only applies if pwsh is present at the time of first launch
