### ISSUE TITLE
disable word wrap.

### ISSUE THREAD

**Issue by farreros** [microsoft/terminal#17128]
Activate or Deactivate Word Wrap via configuration.  JSON with:
"wordWrap": false, 
in my Versión: 1.19.10821.0 do not works, for any terminal configuration, "simbolo del sistema" or default.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
That's not a setting that's supported by the terminal. There's nowhere in the JSON you could add that which would turn off word wrap. You're probably looking for /dup #1860. Or more correctly, I'd recommend using a pager like `less` that supports horizontal scrolling.
