### ISSUE TITLE
can not use special characters

### ISSUE THREAD

**Issue by kasylozy** [microsoft/terminal#1713]
I can not use the special characters Alt Gr combinations I then have the message digit-argument on the terminal

It would be useful if the terminal uses the same keyboard as the one for the computer if you are in Canada/French or in English/Swedish

**Comment by DHowett-MSFT** [comment]
There is an issue that mentions “Alt Gr” at the top of the issues page.
Is it the same as your issue?

**Comment by DHowett-MSFT** [comment]
You also filed the same issue twice. Please don’t do that.
