### ISSUE TITLE
We should show an error dialog for outdated MacType versions

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#17140]
AtlasEngine only works with v1.2023.5.31 and later. We have two options:
* Show an error bar similar to how we do it for the text input service
* Show a classic error dialog and refuse to start

I personally prefer the latter as users should definitely update MacType ASAP'st. It may potentially destabilize the rest of the OS too after all.

**Comment by zadjii-msft** [comment]
oh hey we merged this in #17369
