### ISSUE TITLE
Cannot move the Find dialog, if it covers a search result

### ISSUE THREAD

**Issue by sdbbs** [microsoft/terminal#17149]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.4355

### Steps to reproduce

I very much like the Find feature, which searches text in the terminal text.

But what do you do if the search result is right below the Find dialog?

![image](https://github.com/microsoft/terminal/assets/48317456/1d16ffee-8904-4298-bec6-8f3be8477e07)

I don't see an obvious way to move the dialog interactively, so now, I have to search, remember I'm on result 6/1203, close the damn dialog to see what the match is, right click tab/Find again, click my way to result 7/1203, close the dialog again to read etc... which to be honest is kinda stupid and irritating.

### Expected Behavior

To be able to move the dialog interactively, if it so happens that it covers a found result.

### Actual Behavior

See description above

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think we're more or less tracking this in /dup #4407.
