### ISSUE TITLE
Reflow behavior on window resize seems broken if the cursor is hidden

### ISSUE THREAD

**Issue by kunom** [microsoft/terminal#17151]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.4291

### Steps to reproduce

I have a strange reflow bug that seems to occur only when the cursor is hidden. Steps to reproduce:
1) Paste the following Python code into a file named `status.py`:
   ```Python
   import time

   HIDE_CURSOR = "\x1b[?25l"
   LF_AND_CLEAR_LINE = "\r\x1b[2K"

   print("foo " * 100)
   print()
   print(HIDE_CURSOR)  # --> removing this line fixes the issue
   for i in range(100000):
       print(f"{LF_AND_CLEAR_LINE}working {i}...", end="", flush=True)
       time.sleep(0.05)
   ```
1) Start the script in a new, non-maximized window: `start status.py`
1) Take your mouse and rapidly change the width of the window, so that content is repeatedly reflowed. See heavy display distortions: 
![image](https://github.com/microsoft/terminal/assets/1832956/2eba988f-40e9-4fc1-be90-7cb707ee264b)
1) In the script, remove the "hide cursor" statement and redo the test. Everything works fine now, regardless how heavy you try to distort the display:
![image](https://github.com/microsoft/terminal/assets/1832956/03d61ca8-a983-4f99-aee1-79cc78980260)

### Expected Behavior

The reflow mechanism should work regardless of whether the cursor is rendered or not. The behaviour with the visible cursor is the correct one.

### Actual Behavior

It looks as if the display reflow logic is broken when the cursor is not rendered, maybe the full line inclusive trailing whitespace is reflowed?

**Comment by carlos-zamora** [comment]
| Version | Repro? |
|---|---|
| 1.20.10822 | ✅ |
| 1.19.10821 | ✅ |
| 1.18.3181 | ✅, but not as badly |

Looks like this script doesn't enable VIRTUAL_TERMINAL_PROCESSING mode before printing control sequences. This isn't the root cause but it will cause problems down the line.

**Comment by salt-die** [comment]
Same issue with a much more complicated example:

## Cursor shown and resizing no issue

https://github.com/microsoft/terminal/assets/53280662/1d3792a3-cfe3-48a2-bc07-c8c17e98917e

## Cursor hidden and artifacts when resizing

https://github.com/microsoft/terminal/assets/53280662/fb6b47d3-a26f-4616-aea4-1f01092d6401

**Comment by lhecker** [comment]
I tested this with #17510 and at least the initial 2 repros above seem to be fixed.
