### ISSUE TITLE
Microsoft Support appears unaware of May update requirement

### ISSUE THREAD

**Issue by bert-laverman** [microsoft/terminal#1715]
Please ensure internal docs make this clear.

**Comment by bert-laverman** [comment]
I had a rather fruitless hunting session with someone who eventually tried resetting WSUS and associating a password-free local account. Eventually I took control back and started digging through store system requirements (sorry, I though that meant something else than updates required) and found the reference to the May update.

Microsoft Store BTW won't refuse to install: It will ask on which device I want it (the 'current' PC not being suitable), and selecting the self-same PC there will just result in silent failure.

**Comment by DHowett-MSFT** [comment]
This is probably a lingering issue in how we deployed our application. It's external, though, so I'm going to close it here. Thanks for the info.
