### ISSUE TITLE
wt.exe --version behaviour 

### ISSUE THREAD

**Issue by inoperable** [microsoft/terminal#17163]
### Windows Terminal version

latest

### Steps to reproduce

wt.exe --version

### Expected Behavior

Last thing I expected was to see a (useless) **popup window**
Whoever come up with the idea of popup in a cli executed binary to show a version string: how do i get that information in any kind of scripting env? 

### Actual Behavior

would be great to have what 99.9% of cli executables does when passed --version or -v the actual version/build information and NOT a POPUP window (!?!?)

**Comment by DHowett** [comment]
See https://github.com/microsoft/terminal/issues/4570#issuecomment-586551445 for more info.

/dup #15521
