### ISSUE TITLE
Pause and resume execution of left- and right-click like in PowerShell

### ISSUE THREAD

**Issue by github-account1111** [microsoft/terminal#17176]
# Description of the new feature/enhancement

I googled and searched through issues but couldn't find anything about this.

On Windows 10 I could left-click anywhere inside the PowerShell window, and the execution would pause. I knew the execution was paused when the title bar said "Select PowerShell." When I was ready to resume the execution I just needed to right-click anywhere on the window.

This incredibly handy feature seems to be missing in Microsoft Terminal's PowerShell on Windows 11. Now I have to either wait for the execution to finish (which depending on what I'm running could take hours) or cancel it entirely.

# Proposed technical implementation details (optional)

Same as on Windows 10.

**Comment by zadjii-msft** [comment]
Is the end goal here to actually suspend the CLI application that's running connected to the Terminal, or just make it easier to select text in the scrollback/? 

There's some related discussion in: 
* #980
* #408

**Comment by github-account1111** [comment]
It's the former. It's strange to me that most participants of those issues seem to only be interested in the latter.

Especially that second one. It's not a bug, it's the default PowerShell behavior on Windows 10. It doesn't "freeze." As I mentioned in the description, you can easily tell if it's active or not by looking at the title bar.

**Comment by zadjii-msft** [comment]
Well, it's technically correct that it doesn't "freeze". But selecting in the vintage console prevents conhost from servicing any further console API calls. It just blocks the call until the selection is dismissed. That effectively pauses powershell (or any other CLI app) that's waiting on writing before continuing. 

I'm guessing for most people (myself included) are just happy that selecting the Terminal accidentally doesn't entirely pause long builds anymore. I could have sworn there was an issue floating around asking for the ability to manually pause the conpty client, but I can't find anything like that now...

**Comment by github-account1111** [comment]
What's the issue with that behavior? You can just right-click to resume. Takes less than a second. Meanwhile potentially hours are wasted waiting for execution to finish, or execution has to be cancelled entirely.

**Comment by lhecker** [comment]
Maybe you already know, but...

Actually you can still pause the output at any time: Just press the "Pause" or "Break" key. 😅 Almost all modern hardware and operating systems use the Pause/Break key for pausing terminal output. It's usually in the top right next above the Delete and Insert keys, if you have a full sized keyboard. If you don't have a Pause/Break key you can press Ctrl+S instead. On the latest Windows Terminal versions both should pause/freeze the output immediately until you press another key.

If you did already know that the Pause key does this, can you explain why it doesn't work for you?

**Comment by carlos-zamora** [comment]
Thanks for the feedback. As stated above, this is a bit risky of a change and the desired behavior should be accessible via the Pause key and its Ctrl+S alias. Closing 😊
