### ISSUE TITLE
Settings option for the Windows Temminal is broken - doesn't do anything

### ISSUE THREAD

**Issue by techie-explorer** [microsoft/terminal#1717]
# Environment
Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal Version: 0.2.1715.0

```

# Steps to reproduce
1. Click on the settings button

# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
Supposed to open the settings window

# Actual behavior

<!-- What's actually happening? -->
Nothing is opening.

**Comment by alefnull** [comment]
you need to have a text editor set as your default JSON file editor, as the settings are currently contained in a JSON file. see #1460

**Comment by techie-explorer** [comment]
Worked, thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
