### ISSUE TITLE
Fonts don't render correctly on ubuntu in windows terminal, but render correctly on command prompt on windows terminal

### ISSUE THREAD

**Issue by Slarper** [microsoft/terminal#17177]
### Windows Terminal version

1.19

### Windows build number

 10.0.22631.3447

### Steps to reproduce

run wsl.exe to open a ubuntu terminal that doesn't apply the profile (theme), but to open a terminal from the ubuntu profile  is normal.

![image](https://github.com/microsoft/terminal/assets/98243861/11e3f908-351e-4714-b2c5-9ad62aa2e6ab)

left: not theme 
right: normal

according to https://github.com/microsoft/WSL/issues/9051

He says This issue should be filed in the Terminal repo.

### Actual Behavior

run wsl.exe to open a ubuntu terminal that doesn't apply the profile (theme)

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

Looks like your Ubuntu profile has anti-aliasing disabled.

**Comment by Slarper** [comment]
sure 
[settings.json](https://github.com/microsoft/terminal/files/15210681/settings.json)

Description:

Shift + Right Click on File explorer, select the "Open Linux Shell here", and it will open a shell with default theme.

![image](https://github.com/microsoft/terminal/assets/98243861/bf3b84dc-9637-414c-a2b0-3e49e334d555)

![image](https://github.com/microsoft/terminal/assets/98243861/1d64b832-1fae-4d2a-aa71-6f3c2cb841eb)

This was annoying. But I have migrated all my stuff (projects, compilers, i.e.) into Linux filesystem , so I don't need to open Linux shell in windows file explorer now.  It 's fine for me now.

**Comment by carlos-zamora** [comment]
Thanks! Glad that it's fine now. Closing 😊
