### ISSUE TITLE
wsl is not auto added in terminal's tab

### ISSUE THREAD

**Issue by GGyul-E** [microsoft/terminal#1719]
Terminal Versions is 0.2.1715.0

I downloaded 'Windows Terminal' in Microsoft Store and it's not adding Ubuntu-16.04, Ubuntu-18.04 wsl tab.

![image](https://user-images.githubusercontent.com/39231485/60384847-ab99f180-9abd-11e9-92da-5e60807d5582.png)

What should I do? I already did reinstall all the things. And it doesn't work.

**Comment by GGyul-E** [comment]
Just added by editing profiles.json.

![image](https://user-images.githubusercontent.com/39231485/60385823-d0e02d00-9ac8-11e9-86cc-afc7af78c969.png)

**Comment by Andrew5569** [comment]
@GGyul-E that didn't work for me. The terminal flashes a purplish color for a fraction of a second then immediately closes. 

Here is my configuration

```
{
  "acrylicOpacity": 0.75,
  "background": "#300A24",
  "closeOnExit": true,
  "colorScheme": "Campbell",
  "commandline": "wsl -d Ubuntu-1804",
  "cursorColor": "#FFFFFF",
  "cursorShape": "bar",
  "fontFace": "Consolas",
  "fontSize": 10,
  "guid": "{951db0c8-b337-4c02-a677-06ea1329f8e9}",
  "historySize": 9001,
  "icon": "ms-appx:///ProfileIcons/{951db0c8-b337-4c02-a677-06ea1329f8e9}.png",
  "name": "Ubuntu 18.04",
  "padding": "0, 0, 0, 0",
  "snapOnInput": true,
  "useAcrylic": true
},
```

I'm also the Ubuntu 18.04 LTS version

**Comment by JushBJJ** [comment]
Try changing the guid of the profile.
