### ISSUE TITLE
Enable dragging tabs to other Windows Terminal Windows

### ISSUE THREAD

**Issue by HolyOne** [microsoft/terminal#17209]
In chrome, firefox etc i like the feature of dragging tabs between different windows.

I think the same feature would also be useful in Windows Terminal

**Comment by DHowett** [comment]
You can definitely do this today, you just have to aim for the tab bar when you do it.

If you can’t drag at all: running Terminal as admin disables all drag/drop because Windows is a broken OS.

**Comment by zadjii-msft** [comment]
Yep, this has been in the Terminal since 1.18. Unless of course you're running the Terminal as administrator - where all drag-drop doesn't work (due to platform limitations tracked in #6661)

/dup #1256

**Comment by HolyOne** [comment]
Hello, my bad. yes I am using it in Windows Server and I am logged on as Administrator. However the other window is also launched as administrator so I expected it to work.

**Comment by zadjii-msft** [comment]
Yea, I agree. I'd expect it to work too. Alas, without some major platform improvements, tab dragging in elevated windows will remain broken for a while. Sorry about that.
