### ISSUE TITLE
Window layout persisted in `state.json` even if window persistence not enabled

### ISSUE THREAD

**Issue by ianjoneill** [microsoft/terminal#17207]
### Windows Terminal version

1.20.11215.0

### Windows build number

10.0.22631.3447

### Steps to reproduce

1. Ensure window persistence is turned off
2. Set windows terminal as your default terminal application
3. Go to run and type `cmd /k echo hello world`
4. Close the terminal
5. Inspect `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\state.json`

### Expected Behavior

There is no history of the command that I ran in `state.json`.

### Actual Behavior

`state.json` has leaked my super secret command line invocation!

```json
{
  "persistedWindowLayouts" : 
  [
    {
      "initialPosition" : "234,234",
      "initialSize" : 
      {
        "height" : 436.0,
        "width" : 873.0
      },
      "launchMode" : "default",
      "tabLayout" : 
      [
        {
          "action" : "newTab",
          "commandline" : "\"C:\\WINDOWS\\system32\\cmd.exe\" /k echo hello world",
          "profile" : "Command Prompt",
          "startingDirectory" : "C:\\Users\\Ian",
          "suppressApplicationTitle" : false,
          "tabTitle" : "C:\\WINDOWS\\system32\\cmd.exe"
        }
      ]
    }
  ],
  "settingsHash" : "190f05f1cd1315b4-01d98faa8aecd332"
}
```

This is not reproducible on version 1.19.11213.0.

**Comment by lhecker** [comment]
Oh dear... But #17206 was created a little earlier than this issue, so lets close it in favor of the older one. 🙂 /dup #17206

**Comment by ianjoneill** [comment]
I figured they were related, but not quite the same, so opened a separate ticket - given that this pre-dates 1.21.

**Comment by lhecker** [comment]
Oof, I saw the title, read the repro steps, and considering the timing I thought it would be a dupe. I'm sorry. 😣 However, it is in fact the exact same underlying reason: 1.20 contains the same session persistence improvements that 1.21 got, but without the buffer restore code. This is why both 1.20 and 1.21 have the same bug: They persist, even when they shouldn't.

I'll mark #17211 as fixing this issue. We'll then backport the parts that are relevant for 1.20 (a single if condition basically).
