### ISSUE TITLE
Show current position as starting position inn Windows Terminal Settings Launch Parameters Launch Position

### ISSUE THREAD

**Issue by DLBerger** [microsoft/terminal#17210]
As the title describes, when the Launch Position is first shown, give the current position greyed out as the x and y position.
When the Let Windows Decide is unchecked, un-grey out the x and y position and with each change of the x and y position, move the current window to match the new position.  If I move the window on the screen manually, automatically update the x and y positions.

**Comment by DLBerger** [comment]
Additionally, if I uncheck 'Let Windows Decide', automatically turn off the 'Center on launch' selection.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to merge this with #14156 to make it a part of improving this part of the settings UI as a whole.

/dup #14156
