### ISSUE TITLE
Settings synchronization

### ISSUE THREAD

**Issue by liciniomendes** [microsoft/terminal#1721]
# Summary of the new feature/enhancement

I have multiple machines using the same Windows account, all of them with Windows Terminal. It seems that Windows synchronizes my settings for Windows Terminal, I love it but not all my machines have the same hardware setup, so it ends up that some profiles only work on one machine and that makes me have multiple profiles for the same shell.

```JSON
 "profiles" : 
    [
        {        
            "commandline" : "X:\\my\\path\\to\\shell.com",
        }
    ]
```

# Proposed technical implementation details

It would be cool to have the possibility to have multiple paths if required. It can be achieved with something similar to:

```JSON
 "profiles" : 
    [
        {        
            "commandline" : 
             [
                  {
                       "deviceName": "my computer name",
                       "path": "X:\\my\\path\\to\\shell.com"
                   },
                   {
                       "deviceName": "my other computer name",
                       "path": "c:\\my\\path\\to\\shell.com"
                   },
             ]
        }
    ]
```

**Comment by DHowett-MSFT** [comment]
I'm going to choose to track settings roaming issues in #1770 until we have a holistic story for it. Thanks!
