### ISSUE TITLE
[1.21] Doesn't show the prompt when using "Shell Integration" escape sequences in bash prompt on WSL

### ISSUE THREAD

**Issue by crramirez** [microsoft/terminal#17218]
### Windows Terminal version

1.21.1272.0

### Windows build number

10.0.22631.3527

### Other Software

bash

### Steps to reproduce

```bash
PS1='\[\033]133;D;$?\]\[\033\\\033]133;A\033\\\]$ \[\033]9;9;"$(wslpath -w "${PWD}")"\033\\\]\[\033]133;B\033\\\]' 
```

### Expected Behavior

A prompt with enabled Shell integration

### Actual Behavior

The prompt doesn't show up until you hit enter, and the cursor is not in front of it.

It worked in Preview 1.20

**Comment by carlos-zamora** [comment]
Thanks for filing! This should be fixed by #17212, thus closing 😊. It's on our queue servicing so it'll be fixed when the servicing update goes out.

**Comment by crramirez** [comment]
Oh, sorry. I did a quick search to see if the issue had already been reported, and I didn't see it.

**Comment by DHowett** [comment]
@crramirez oh you don't need to apologize! Thanks! :)
