### ISSUE TITLE
wt.exe windows does not restore correctly after exiting full screen

### ISSUE THREAD

**Issue by pujfei** [microsoft/terminal#17214]
### Windows Terminal version

1.20.11271.0

### Windows build number

10.0.22635.3570

### Steps to reproduce

1. open wt.exe
2. press Alt + Enter to full screen
3. press Alt Enter to exit full screen

### Expected Behavior

wt.exe window shall restore previous state

### Actual Behavior

the wt.exe window does not restore normally, some of its full screen window remains stubborn on the desktop window.![IMG_20240509_000310.jpg](https://github.com/microsoft/terminal/assets/30553808/159d2ff1-af91-4642-a2cb-aef66efbfff7)

![IMG_20240509_000330.jpg](https://github.com/microsoft/terminal/assets/30553808/f27a8136-4238-42b8-a414-b95bf5c5fa15)

![IMG_20240509_000258.jpg](https://github.com/microsoft/terminal/assets/30553808/ff0e67ca-7730-4b0e-8072-15f0d216c629)

![IMG_20240509_000233.jpg](https://github.com/microsoft/terminal/assets/30553808/c722683d-ae9b-4a4d-addc-4bfc0524ecbd)

![IMG_20240509_000012.jpg](https://github.com/microsoft/terminal/assets/30553808/014d83e5-9d96-4ec1-bd89-efc9044d7492)

**Comment by zadjii-msft** [comment]
@pujfei just to confirm, are you on an Intel Iris Xe just like in #14865/?

**Comment by pujfei** [comment]
no, mine is intel core i9 vPro and independent GPU.

**Comment by pujfei** [comment]
@zadjii-msft @carlos-zamora Hi, is there a plan to identify and fix this issue? this seems to be a very old one, which was raised almost two years ago.

**Comment by zadjii-msft** [comment]
We've got a line out to some DWM folks currently. They think it's a DWM bug, so we'll need to get them some traces.

**Comment by pujfei** [comment]
ah, good news, b.t.w, are these codes inherited from windows 10 or are they completely new codes introduced in windows 11?

**Comment by zadjii-msft** [comment]
I can't say I have any idea how DWM is implemented 😅
