### ISSUE TITLE
Splitting pane with shortcut opens wrong terminal session

### ISSUE THREAD

**Issue by JMackay2000** [microsoft/terminal#17222]
### Windows Terminal version

Version: 1.19.11213.0

### Windows build number

Microsoft Windows [Version 10.0.22631.3447]

### Steps to reproduce

1. open terminal, open any session that is not configured as the default
2. use shortcuts to split pane `alt + shift + -/=` 

### Expected Behavior

It opens up a new pane using the profile/tab I split on

### Actual Behavior

It creates a new pane with the default profile

![image](https://github.com/microsoft/terminal/assets/14109314/6dd6116b-2032-42b3-a38f-0019ff8710a3)

**Comment by DHowett** [comment]
> 1.19

We changed this behavior to be what you’re expecting in 1.21. It turns out that roughly half of people expect it to be one way and the other half the other way!

You can rebind your split pane keys in the Actions page of settings while you wait for 1.21 to come out 🙂
