### ISSUE TITLE
Cloud shell console loses prompt location

### ISSUE THREAD

**Issue by SemperFu** [microsoft/terminal#17229]
### Windows Terminal version

1.211272.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Connect to Azure cloud shell, run something that scrolls the screen. Start typing and the line appears in the middle of the screen instead.

https://github.com/microsoft/terminal/assets/1786698/a2e91fa4-04e2-4940-8d9e-186b0ced726f

### Expected Behavior

Prompt to stay at the bottom of the console.

### Actual Behavior

After the first char it, the line will continue towards the middle of the console.

**Comment by carlos-zamora** [comment]
If you run `reset` does it fix itself /?
