### ISSUE TITLE
Windows Terminal crashes when opening after uninstalling Ubuntu in WSL (when it was set as default)

### ISSUE THREAD

**Issue by albertowar** [microsoft/terminal#1722]
Windows Terminal crashes when opening after uninstalling `wsl` when `wsl` was set as the default terminal.

# Environment

```none
Windows build number: [run "ver" at a command prompt]: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

- Install Ubuntu in WSL
- Set as default command line tool in Windows Terminal
- Uninstall Ubuntu
- Open Windows Terminal

# Expected behavior

Windows Terminal picks another default terminal and opens properly

# Actual behavior

It crashes

**Comment by DHowett-MSFT** [comment]
This'll be another form of #1458
