### ISSUE TITLE
Unlimited zoom-in using Ctrl+Wheel causes renderer to crash

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#17227]
### Windows Terminal version

Current main

### Windows build number

10.0.19045.4291

### Steps to reproduce

- ~~Set Direct3D backend active.~~ All rendering backends are affected.
- Run tab with any profile.
- Zoom-in by Ctrl+Wheel until it crashes.
  - Direct3D: ~ One minute of scrolling for my HW setup.
  - Direct2D: ~10 minutes of "doing nothing" with same result (crash).

### Expected Behavior

Reasonable zoom limits. E.g.: One text cell should not exceed the size of the terminal window.

### Actual Behavior

Direct3D:
![image](https://github.com/microsoft/terminal/assets/11535558/9eb06214-ec23-4bd6-a924-21995f8771b7)

Direct2D:
![image](https://github.com/microsoft/terminal/assets/11535558/ec4c1308-6fad-4dac-9b6f-8840b9355245)

**Comment by lhecker** [comment]
> Direct2D: ~10 minutes of "doing nothing" with same result (crash).

What do you mean with "doing nothing"?

**Comment by o-sdn-o** [comment]
> What do you mean with "doing nothing"?
I mean I scrolled intensively with the mouse for 10 minutes and nothing more 😅
