### ISSUE TITLE
Tab/title bar consistency

### ISSUE THREAD

**Issue by bonzibudd7** [microsoft/terminal#1723]
1. Title bar must be the same on the tab section as the right side. Currently, the tab section is a consistent dark grey, whatever accent color you use on the dark theme (consistent white on light theme). On the right side of the tab section, the title bar is either White (independent of light/dark theme) or chosen accent color. The title/tab bar should be the same on either side.
2. Window dragging is not available on the tab section. This is a pretty major issue, making the drag section very small at any dpi. This needs to be fixed.
-->

**Comment by DHowett-MSFT** [comment]
#1375
