### ISSUE TITLE
Add `Reload/Restart` Action - i.e. vscode's `Reload Window`

### ISSUE THREAD

**Issue by g0t4** [microsoft/terminal#17239]
# Description of the new feature/enhancement

Often I find myself wanting to restart Windows Terminal, it would be nice to have a stock command/action in the `Command Palette`. Something similar to vscode's `Developer: Reload Window` 

# Proposed technical implementation details (optional)

Two use cases come to mind:
- I modify settings and want to reload to ensure changes are loaded... this could be fixed via changing how settings apply to auto-reload like it used to but I assume that's not the direction settings are headed, in which case this feature becomes invaluable.
- I modify env vars and want to ensure they are picked up. I understand there is a new setting to open new tabs/panes with the new env block and that is great, but sometimes I want to ensure all my tabs/panes have the new block in which case just killing all of them and restarting would be great.

I do not personally need to re-open tabs/panes that were closed, instead I can start with a single new tab. That said, the new option to restore pane contents when starting terminal would likely work well with a restart action.

The net effect would be to terminate (close all windows/tabs/panes) the wt.exe process and then relaunch it. Or, if there is a way to do that without killing / starting a new process that would be fine too.

**Comment by zadjii-msft** [comment]
> I modify settings and want to reload to ensure changes are loaded... this could be fixed via changing how settings apply to auto-reload like it used to

It still does! I suspect though what you're seeing is that when you save a fragment file, the Terminal doesn't hot-reload that. I could have swore there was an issue for that. You can just touch the main terminal settings file to have it hot-reload the fragments too. 

The terminal will continue to always support hot-reloading its own settings file. I'm not about to break that any time soon 😄 

> I modify env vars and want to ensure they are picked up. I understand there is a new setting to open new tabs/panes with the new env block and that is great, but sometimes I want to ensure all my tabs/panes have the new block in which case just killing all of them and restarting would be great.

Oh you may be interested in the "Restart connection" action, added in 1.18, in #15241. (#3726 was this)

**Comment by zadjii-msft** [comment]
It is 1000% possible. As of #1812, that's by design. 

(and it looks like #6209 treads a lot of this same ground)

**Comment by g0t4** [comment]
Alright, I'll close this for now then as the other issue https://github.com/microsoft/terminal/issues/13416 addresses env vars.
