### ISSUE TITLE
ssh to linux mint pc, bash prompt blinks a line below 

### ISSUE THREAD

**Issue by billchandler** [microsoft/terminal#17235]
### Windows Terminal version

 1.21.1272.0-preview

### Windows build number

10.0.22631.3527

### Steps to reproduce

open windows terminal preview, ssh to my linux mint pc

### Expected Behavior

cursor to blink on the same line as my prompty, not the line below it. This works OK on previous windows terminal versions

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/16466289/cf5b546b-2c0d-4359-805b-66e2b91fecdd)

**Comment by lhecker** [comment]
Just SSHing into my Raspberry Pi with bash doesn't reproduce the issue. I think this may be #17204. Do you happen to know whether you have any OSC sequences configured (for things like shell integration for instance)?

**Comment by billchandler** [comment]
Same here, works OK on my pi. But get same issue if I ssh to my sdf.org
login.
I don't even get to see the bash prompt until I press enter once, then the
cursor blinks a line below

**Comment by billchandler** [comment]
I don't believe I am using OSC sequences.
Bill

**Comment by zadjii-msft** [comment]
Does this repro if you use the vintage console host, `conhost.exe`, as your terminal emulator instead/?

**Comment by billchandler** [comment]
Works OK with conhost. Also works OK with wezterm.
-bill

**Comment by carlos-zamora** [comment]
Could you try WT Canary /? We've made some changes there that could affect this.

**Comment by billchandler** [comment]
Sorry, I don't know how to pull WT Canary.  Nor would I know how to build
it if you are referring to src code.

**Comment by lhecker** [comment]
Here's the download link: https://aka.ms/terminal-canary-installer
It's a "app package" similar to the regular Windows Terminal, so it'll cleanly install, uninstall, and not interfere with your other Windows Terminal installation(s).

**Comment by billchandler** [comment]
The canary works good.  I tested it to my pc running  Linux Mint 21.2
Victoria
and my sdf.org account running  NetBSD sdf 9.3 NetBSD 9.3 (GENERIC) #0:

Thanks, Will use the canary till it flops over dead  :)
Bill

**Comment by lhecker** [comment]
Ah that's excellent to hear! It's likely that your issue was fixed in #17212. We have backported the fix to 1.21 Preview and it should ship sometime soon.

Please feel free to continue using Canary. It'll update itself during launch every other day, based on our latest version from our main branch, so it may have bugs. But I think by then the fix should be in 1.21. 😅
