### ISSUE TITLE
Focus should move to next tab when closing a tab

### ISSUE THREAD

**Issue by EdwinChan** [microsoft/terminal#17244]
# Description of the new feature/enhancement

When a tab is closed, focus should move to the tab to the right instead of to the left.

In Firefox and Chrome, when a tab is closed by clicking on 🗙, the cursor naturally lands on the following tab, and the browser shows the content of that tab, allowing the user to close multiple tabs by chain-clicking.

In Terminal, when a tab is closed by clicking on 🗙 (or by any other method), the previous tab is shown even though the cursor is on the following tab. The user must move their cursor from the 🗙, click elsewhere on the tab to preview its contents, and then decide whether to close it. An absentminded user may close important tabs because of this unexpected behavior, particularly because Terminal does not confirm tab closing #6549. Before the user moves their cursor, the tab does not show its usual hover effect, adding to the confusion.

# Proposed technical implementation details (optional)

**Comment by EdwinChan** [comment]
Given that others might have had this problem, I have tried searching for similar (open and closed) issues here and on Google—no luck at all. This issue is not about closing all tabs to the right #5524.

**Comment by michaeljsXu** [comment]
Should there be a setting for this or is it ok if we default to going to next tab when closing a tab?

**Comment by lhecker** [comment]
I think we should not have a setting for that. That just unnecessarily complicates things.
