### ISSUE TITLE
Version: 1.20.10572.0 reopens last tabs whenever it feels like it

### ISSUE THREAD

**Issue by working-name** [microsoft/terminal#17250]
### Windows Terminal version

Version: 1.20.10572.0

### Windows build number

Version	10.0.22631 Build 22631

### Steps to reproduce

Open terminal preview.
Open several tabs.
Restart computer either before or after you close down Terminal.
Wonder if it'll restore windows or it won't.

### Expected Behavior

Do what the option says: reopen tabs from last session.
![fucking-microsoft-again](https://github.com/microsoft/terminal/assets/16505052/ee7a2399-92ab-4300-8ed1-f9b578e2d3c3)

### Actual Behavior

randomly opens last session tabs whenever it feels like it. No option to save my own and restore manually, I'm just living at the mercy of my own (removed expletive to comply with Code of Conduct) computer. It's great.

**Comment by DHowett** [comment]
Please adhere to this repository’s Code of Conduct when you are reporting issues.

**Comment by working-name** [comment]
Sure thing. Was it "d***" that upset you?

**Comment by lhecker** [comment]
"damn" is not a problem. Your post is simply just overall very sarcastic. I'd understand it if we had done something to offend you, but it's just a bug in the application.

In any case, we're already aware about this issue and still collecting information when and why it happens. It's likely a race condition during shutdown or something similar, which is why it seems "random". My current theory is that it only happens if you have more than one window open.

**Comment by working-name** [comment]
Got it.

Your current theory matches what I experienced about a year ago (don't remember version) when I curbed my behavior to have more than 1 terminal window open before I close it. So this bug also happens when a single window with multiple tabs is open.

I think I made it happen once or twice when I was trying to reproduce it by killing the process from [Process Hacker](https://processhacker.sourceforge.io/).

**Comment by zadjii-msft** [comment]
If I were to posit a theory: I'm guessing you've got some other CLI process that starts at startup. The OS starts that process up, and it picks Terminal as the default terminal handler, and starts the Terminal. Then, when the Terminal starts, it _also_ starts up all the other windows for itself. 

Now I'm guessing that the reason why sometimes this _doesn't_ happen is along the lines of #17179 - sometimes, the window state _isn't_ getting persisted if you just straight shutdown the PC.
