### ISSUE TITLE
AltGr key not working correctly

### ISSUE THREAD

**Issue by cyberixae** [microsoft/terminal#1725]
```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

1. Use Finnish keyboard and Finnish keyboard layout
2. Click Windows Terminal to move focus to it
3. Press AltGr+2 combination to write "@"

# Expected behavior

"@" should appear on screen

# Actual behavior

"2" appears on screen

**Comment by DHowett-MSFT** [comment]
This is at the top of the issues page:

## Pinned Issues
![image](https://user-images.githubusercontent.com/14316954/60390036-52609c80-9a82-11e9-96aa-0a9eaff3ac65.png)

Does that sound like your issue?

**Comment by cyberixae** [comment]
Yes. #521 indeed sounds like the same problem.
