### ISSUE TITLE
[Feat.] Allow Remote Config Backup+Restore

### ISSUE THREAD

**Issue by CrazyWolf13** [microsoft/terminal#17277]
# Description of the new feature/enhancement

I use many different machines on a daily basis, for example my work laptop, my development laptop, my testing laptop, my private laptop, my private Tower etc.

On each Device I need to import the full Config of Windows Terminal. A way to synchronise all the Terminal Config files would be insanely great and would really hype up this terminal soo much more!!!

PowerToys already has a Backup option, could  similar thing be done for windows-terminal?
I'd even consider github integration a nice idea, as this would allow for easy fetching from a raw.githubusercontent link.
(I wouldn't mind the config being public).

Also something like fully remote fetching would be nice, for example the machine fetches the config from remote github repository and on no internet it fallbacks to a cached version.

# Proposed technical implementation details (optional)

The Github Integration to the initial Backup + Restore would be like a nice-to-have addon to keep in mine, but could also be done through scripts.

- Add a way to Backup and restore the Config
  - Backup to a specfic Path
  - Restore from Path
- Github Integration would be nice-to-have
  - User can enter a URL to a github file, where config is fetched from.
  - User can connect windows terminal to github account, select a repo and the accoring file, where windows terminal pushes changes to.

**Comment by carlos-zamora** [comment]
Thanks for filing! Marking this as a /dup of #2933. I copied over your post to https://github.com/microsoft/terminal/issues/2933#issuecomment-2207424906 too for easier tracking 😊

**Comment by CrazyWolf13** [comment]
> Thanks for filing! Marking this as a /dup of #2933. I copied over your post to https://github.com/microsoft/terminal/issues/2933#issuecomment-2207424906 too for easier tracking 😊

Hi Carlos
Thanks for the kind response 😊

Apologies for filing a dup, but I could not find that report beforehand.

**Comment by DHowett** [comment]
> Apologies for filing a dup, but I could not find that report beforehand.

Oh that’s not a problem! With 17,000 issues in our haystack it wouldn’t be fair for us to expect everyone to always find the needle :)
