### ISSUE TITLE
Allow custom config file location

### ISSUE THREAD

**Issue by blami** [microsoft/terminal#1727]
# Summary of the new feature/enhancement
As many of us carry over settings between computers using dotfiles git repository or similar technique it would be useful to allow custom configuration file location (adding RoamingState dir to dotfiles repo sounds wrong). Even with working configuration sync this would allow to carry over Terminal configuration from e.g. home to workplace/school where different restricted account is being used. 

# Proposed technical implementation details (optional)
Ideally it can be just registry setting that when imported changes config file discovery area to something like %HOME%/.config (using %HOME% as ~ in WSL). Would prefer something that could be automated rather than flipswitch in UI.

**Comment by DHowett-MSFT** [comment]
This is just going to be another version of #1567
