### ISSUE TITLE
Open windows from a previous session should not re-run processes or have ability to selectively stop that

### ISSUE THREAD

**Issue by krwq** [microsoft/terminal#17275]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.22631.3593

### Other Software

cmd.exe with any app running as startup

### Steps to reproduce

- Enable `Open windows from a previous session` and optionally auto-start when logging in
- Have any console app server running as auto-start (i.e. entry under `HKCU/HKLM\Software\Microsoft\Windows\CurrentVersion\Run` - in my case it directly points to the exe file)
- wait until app loads
- restart PC/re-log in
- start Windows terminal (if not auto-starting)

Observe how app is re-run through both Windows Terminal and Windows - in case of i.e. https server it will frequently show message about port being in use in one of the instances

### Expected Behavior

I'd expect either of following:
- do not restore apps started as part of login
- see only environment for the app (i.e. terminal could still open with all environmental variables but it would only have a prompt allowing me to start the app with pressing ENTER)
- have ability to selectively not restore it (i.e. right click and checkbox: `Ignore this process for session restore` or similar)
- any other way to prevent from

### Actual Behavior

Two instances of the app are run - in some cases it will lead to crashes. If you keep on restarting and app doesn't close you will have incrementally more apps start

**Comment by krwq** [comment]
This looks like it might want to be addresses as part of https://github.com/microsoft/terminal/issues/16487 but will let maintainers decide if it's same or separate issue as this one is not about multiple instances of Windows terminal

**Comment by carlos-zamora** [comment]
Thanks for filing! Yeah, some of the behaviors around this are non-intuitive. We'll be tracking it over there and marking this as a /dup of #16487.
