### ISSUE TITLE
persistedWindowLayout doesn't restore CWD in split panes

### ISSUE THREAD

**Issue by tunaflsh** [microsoft/terminal#17283]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.22631.3593

### Steps to reproduce

1. Follow the instructions in [here](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).
2. Run terminal.
3. Set `"firstWindowPreference": "persistedWindowLayout"` or in the UI `Startup > When Terminal starts` to `Open windows from a previous session`
4. Create split panes.
5. Change the working directories in each pane.
6. Restart terminal.

### Expected Behavior

Terminal restores the CWDs in all panes.

### Actual Behavior

This only works for the first pane in a tab and for the tabs that do not have split panes.

**Comment by zadjii-msft** [comment]
Hmm, this _does_ work for tearout in canary 1.22. I think it does even work generally in canary 1.22. 

I wonder if this was a 1.19 backport-specific regression?

**Comment by tunaflsh** [comment]
Looks like it's working now. Still the same version. I'm not sure what went wrong for me back then.
