### ISSUE TITLE
cursor shape wrong with nvim

### ISSUE THREAD

**Issue by zgpio** [microsoft/terminal#17286]
### Windows Terminal version

1.21.1272.0

### Other Software

NVIM v0.10.0-dev-3117+g4e5c633ed

### Steps to reproduce

a.vim
```vim
let &g:statusline="%#Visual#%{'['.winnr().']'}%#Normal#
      \ %{(&previewwindow?'[preview] ':'').expand('%:p:~:.')}%m
      \ %=%{(winnr('$')==1 || winnr('#')!=winnr()) ? '['.(&filetype!=''?&filetype.',':'').(&fenc!=''?&fenc:&enc).','.&ff.']' : ''}
      \ %{printf('%'.(len(line('$'))+2).'d/%d',line('.'),line('$'))}"

" If you annotate this line, there won't be this problem
set noshowmode

```
1. nvim -u a.vim
2. press `i`  and then press `<esc>`
3. you can see  the cursor did not turn into a square  after press `<esc>`

### Actual Behavior

in  reproduce

**Comment by carlos-zamora** [comment]
Thanks for filing. We're going to mark this as a /dup of https://github.com/neovim/neovim/issues/6005

**Comment by zgpio** [comment]
It work ok on terminal  1.20.11381.0   ，but not on 1.21.1272.0，so it is regression

**Comment by lhecker** [comment]
You may have hit #17212. Can you try updating Windows Terminal Preview? The latest version is here: https://github.com/microsoft/terminal/releases/tag/v1.21.1772.0

I just tested it on that version, and it worked for me.
