### ISSUE TITLE
Change the background colour per tab

### ISSUE THREAD

**Issue by dfoulkes** [microsoft/terminal#1729]
# Summary of the new feature/enhancement
Allow the user to choose a colour for the tab

# Proposed technical implementation details (optional)
 customise the colour of the tabs by right clicking on the tab --> settings --> choose colour

# BDD Stories

**SCENARIO**: user opens a new tab
 **GIVEN**: has opened a new terminal
 **WHEN** user right clicks the tab
 **THEN** they are supplied with a settings option

**SCENARIO**:  user wishes to change the colour of a tab
 **GIVEN**: user is in the settings menu
 **WHEN** wanting to change the colour of a tab
 **THEN** user is presented with the current colour, and a colour wheel to choose from

**SCENARIO**:  user selects a new colour
 **GIVEN**: user has selected a new colour
 **WHEN** user clicks _OK_
 **THEN** the tab is set to the colour selected.

**SCENARIO**:  user selects a new colour
 **GIVEN**: user has selected a new colour
 **WHEN** user clicks _Cancel_
 **THEN** the tab remains the same colour as it did prior

**Comment by JushBJJ** [comment]
This seems like a original idea, I like it

**Comment by DHowett-MSFT** [comment]
FWIW a connected text-mode application can set the Terminal’s background color with OSC 11: `\e]11;rgb:ff/ff/ff\e\\`

**Comment by dfoulkes** [comment]
I hope by colour coding the tabs without changing the terminal colour also. The idea is to supply visual cues to help manage multiple tabs simultaneously.

**Comment by andrestest1125** [comment]
Yes please, VSCODE it's great already, you can make it similar

**Comment by dfoulkes** [comment]
I wonder, should this also include the ability to rename the tab ? I suppose that would be another ticket.

**Comment by DHowett-MSFT** [comment]
For color coding tabs we've got #1337 (nice number). I'm not opposed to this, but I'd like to understand whether OSC 11 works for this scenario. If it does, we can drop it back in the order to line up with #1564 and other UI things.

**Comment by dfoulkes** [comment]
I would argue that #1337 is more about having a Permanent tab colour for a profile, my suggestion is that to help facilitate someone that’s let’s say has many PowerShell tabs open, to change its colour to help index them whilst working.

**Comment by dfoulkes** [comment]
Can anyone validate is OSC11 would work in this story described ?

**Comment by zadjii-msft** [comment]
@dfoulkes just to help clarify, do you want to set the background color of the _tab_ 
![image](https://user-images.githubusercontent.com/18356694/60815458-5022d000-a15d-11e9-86d8-4f2a17ca5ea6.png)

or the background color of the _buffer_
![image](https://user-images.githubusercontent.com/18356694/60815508-67fa5400-a15d-11e9-9c48-db38e10bb0fb.png)

at runtime? OSC 11 will work for the _buffer_:
![image](https://user-images.githubusercontent.com/18356694/60815614-a2fc8780-a15d-11e9-88fb-a4067adfac85.png)
but there's not a way to change the color of the _tab_ at runtime.

**Comment by dfoulkes** [comment]
@zadjii-msft the story was aimed at the tab.

**Comment by DHowett-MSFT** [comment]
Whoops, sorry about that. My bad. In that case, this is #1337 :smile:
