### ISSUE TITLE
Script Running after waking from Windows Sleep Freezes Window

### ISSUE THREAD

**Issue by hl2guide** [microsoft/terminal#17293]
### Windows Terminal version

Version: 1.19.11213.0

### Windows build number

10.0.22631.0

### Other Software

Batch file running a Python script.

### Steps to reproduce

1. Use task manager and schedule a task that can running during Windows sleep wake up (delayed).
2. Sleep Windows
3. Wake Windows later

### Actual Behavior

The window appears but is unresponsive and does not render frame (script does not run) and the process has to be manually ended.

e.g.

![Screenshot 2024-05-20 101456](https://github.com/microsoft/terminal/assets/17044982/5208eb34-73a1-4be7-b933-d1655aab42a9)

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #15936
