### ISSUE TITLE
Still cannot drop files to Terminal running as admin

### ISSUE THREAD

**Issue by szx0427** [microsoft/terminal#17291]
### Windows Terminal version

1.20

### Windows build number

10.0.19045.3930

### Other Software

Windows File Explorer 10.0.19041.3758

### Steps to reproduce

First, ensure you logged in as an ordinary admin account (I've not tested on the built-in Administrator account yet but I guess the problem will remain.)
**Method 1:** Set EnableLUA=1 (enable UAC), run Terminal with admin permission, drag a file from Desktop and drop it to Terminal.
**Method 2:** Set EnableLUA=0 (disable UAC), directly run Terminal, and do the drag&drop.

### Expected Behavior

I am simply expecting drag & drop can work.

### Actual Behavior

A cursor indicating "unavailable" will be displayed through either method above.
Such drag&drop is supported by the legacy conhost but not Windows Terminal. That's weird. Don't tell me this issue is a duplicate of #14946 or #15996 and that you have already fixed this in 1.18. I tested on both 1.18 and 1.20 only to find the problem remaining.

**Comment by zadjii-msft** [comment]
Notes: 

For the tab dragging scenario:
* https://github.com/microsoft/terminal/blob/01e4df152e6e4d5156ef394412eb63025f7d743b/src/cascadia/TerminalApp/TerminalPage.cpp#L175-L176
* https://github.com/microsoft/terminal/blob/01e4df152e6e4d5156ef394412eb63025f7d743b/src/cascadia/TerminalApp/AppLogic.cpp#L140
* https://github.com/microsoft/terminal/blob/01e4df152e6e4d5156ef394412eb63025f7d743b/src/types/utils.cpp#L680

But that's not file drag/drop. 

That code references all of 
* #13928
* #7754
* #11096

**Comment by carlos-zamora** [comment]
> First, ensure you logged in as an ordinary admin account (I've not tested on the built-in Administrator account yet but I guess the problem will remain.)
**Method 1:** Set EnableLUA=1 (enable UAC), run Terminal with admin permission, drag a file from Desktop and drop it to Terminal.
**Method 2:** Set EnableLUA=0 (disable UAC), directly run Terminal, and do the drag&drop.

Can you clarify if the issue occurs when UAC is enabled /?

For us, when it's enabled, drag & drop into conhost doesn't work. In that situation, it's not expected to work for Terminal either.

**Comment by Mingyueyixi** [comment]
Same with me. i also can't not drop file to window terminal from andy where , Whether the uac or admin  is enabled or not
