### ISSUE TITLE
SSH & emacs cause phantom characters when trying to scroll down

### ISSUE THREAD

**Issue by Hyper200** [microsoft/terminal#173]
* Your Windows build number: (Type ver at a Windows Command Prompt)
Version 10.0.16299.309

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Using ssh, connect to a system and open a file using emacs, as you open the file press the down key to scroll.

![capture](https://user-images.githubusercontent.com/37409036/39864368-43491584-5441-11e8-8b3a-440242acd79b.PNG)

* What's wrong / what should be happening instead:
The file should open a scroll down, instead it adds a B to the top of the text file while it loads. 

No entriley sure this is a console issue but the same issue dose not apply when using wsltty. Only seems to be an issue with emacs, I guess VI isn't in insert mode by default therefore it might not affect it.

**Comment by zadjii** [comment]
What's `TERM` set to on the remote machine? A lot of issues like these are because the remote machine is set to something other than `xterm-256color`

**Comment by Hyper200** [comment]
Spot on

echo $TERM
xterm-256color

I guess the terminal has a general bug with xterm-256color? Or is there an altertive we should be setting. 

xterm-256color must be the default for RHEL, CentOS etc.

**Comment by florian1984** [comment]
Im using vi with RHEL/SLES/Ubuntu, and got same problem (https://github.com/Microsoft/console/issues/188#issuecomment-391362285). 

When I set => TERM="" => cursor key works, but page up/down not.
With TERM=xterm-color => page up/down works, cursor keys not 

I could remap it in vimrc, but Im too lazy :-). With these bugs this m$ console is useless for me. Use now kitty (putty) again :-) ....

**Comment by Mythrix** [comment]
Hmm I see that this issue is a year old, but I still have the same issue with emacs on CentOS 7.8 in Windows Terminal.

When googling I found a thread for another console/terminal program ConEmu which had a similar issue with emacs: https://github.com/Maximus5/ConEmu/issues/1691

The top comment there seems to have some more detailed information about what the reason could be. Does that help in getting the issue fixed for Windows Terminal?

**Comment by zadjii-msft** [comment]
Hey this issue is... pretty dang old at this point. Anyone still seeing this? I reckon this is probably due to an input sequence getting chopped in half and not getting written to the console in a single write. Can we get a fresh repro here with a specific ssh version (and distribution)/?

**Comment by Hyper200** [comment]
i haven't had it since i switch to:
https://github.com/microsoft/terminal/issues/173#issuecomment-388091934

Thanks,

**Comment by zadjii-msft** [comment]
That's kinda weird tbh, cause typically the Windows Console & Terminal _should_ work with `xterm-256color`. I suppose your issue is sorted out, and we can just close this out for now. If something else like this comes up, we can track it in a fresh issue rather than this fairly stale one. 

Thanks!
