### ISSUE TITLE
Support for Kitty Graphics Protocol

### ISSUE THREAD

**Issue by RaraCool** [microsoft/terminal#17309]
# Description of the new feature/enhancement

The [Kitty Graphics Protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) would allow for more advanced graphics to be possible from within the terminal, such as images. Personally, this is so I can use [this neovim plugin](https://github.com/giusgad/pets.nvim), but of course there are more practical applications, such as an entirely terminal based version of [MPV](https://github.com/mpv-player/mpv), or better compatibility with [Twitch TUI](https://github.com/Xithrius/twitch-tui). This would generally benefit people who like to replace GUI functionality with a CLI.

**Comment by unxed** [comment]
One of the reason to implement this — Far Manager's PictureView plugin. There is no other way to get it working when switching from old Console API (with some tricks like rendering graphics to separate window on a top of console window) to rendering via ESC sequences. And 256 colors of sixels is defenitely not enough for it.

@DHowett pls reconsider

**Comment by unxed** [comment]
One of the reasons to implement this — far2l's [ImageViewer plugin](https://github.com/elfmz/far2l/tree/master/ImageViewer). It renders graphics using kitty protocol if far2l is working in tty mode.

And also it is original Far Manager's PictureView plugin. There is no other way to get it working if switching from old Console API (with some tricks like rendering graphics to separate window on a top of console window) to rendering via ESC sequences. And 256 colors of sixels is defenitely not enough for it.

@DHowett pls reconsider
