### ISSUE TITLE
Terminal crashes when closing any other pane than the last

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#17305]
### Windows Terminal version

1.21.1272.0

### Windows build number

10.0.22631.3593

### Steps to reproduce

open terminal. split horizontally twice. change to middle pane. CTRL-D -- crash.

i have mouse tracking turned on if relevant

![term-crash](https://github.com/microsoft/terminal/assets/46322585/fbb48d78-ecf0-4ced-8d41-5995c179b7ce)

### Expected Behavior

obviously, no crash :)

### Actual Behavior

it crashes and takes "a long time" to start

**Comment by dovholuknf** [comment]
It seems to be anything that's not the 'last' pane. I just tried it again and successfully closed the bottom (third) pane

![term-crash2](https://github.com/microsoft/terminal/assets/46322585/26387ec3-212e-4f1a-aee6-7a4f79c68a32)

**Comment by dovholuknf** [comment]
Happens when using powershell too (not ubuntu). I actually LIKE the change to use the active (not default) profile but I need to be able to close the panes :D

**Comment by dovholuknf** [comment]
any idea when this fix can get released? boy is this annoying.... thanks!

**Comment by lhecker** [comment]
If it's an option for you, you can work around the issue by closing panes with Ctrl-Shift+W.
It'll probably take a week or so for the fix to be released as the next Preview version. However, it should also be available in the nightly "Canary" build tomorrow. (The canary build is here: https://aka.ms/terminal-canary-installer)

**Comment by dovholuknf** [comment]
I was under the impression that this would be addressed in the next update. I see I'm now on Version: 1.21.1382.0. I reported this aginst 1.21.1272.0 so I thought it'd be fixed but this seems to still be a problem? Is that to be expected still? thx
