### ISSUE TITLE
Bug Report - Full Screen bug in extended display

### ISSUE THREAD

**Issue by nursoltan-s** [microsoft/terminal#1730]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version: 0.2.1715.0 

```

# Description
When I use extended secondary display, and make terminal fullscreen (press rectangular button from top right side), terminal overflowed from left side.

# Expected behavior
Terminal should fit overall display

![image](https://user-images.githubusercontent.com/7783676/60394587-4b588d80-9b59-11e9-8e69-f37dc445082e.png)

# Actual behavior
Terminal overflows and leftmost characters not showing.

![image](https://user-images.githubusercontent.com/7783676/60394591-590e1300-9b59-11e9-8786-0fd917456768.png)

**Comment by DHowett-MSFT** [comment]
#1055
