### ISSUE TITLE
Character navigation issue

### ISSUE THREAD

**Issue by WillPittenger** [microsoft/terminal#17315]
### Windows Terminal version

 1.20.11271.0

### Windows build number

 Win32NT             10.0.22631.0 Microsoft Windows NT 10.0.22631.0

### Other Software

PS 7.4.2

### Steps to reproduce

Paste in `'R🜨'`.  Now try to put a period immediately after the closing quotes as though you wanted to call one of the string's members.  If you do so by visually placing the caret to the immediate right of the  closing quote, you'll actually put the new character *in* the string.

### Expected Behavior

As you move the caret back and forth, you'd think it'd move left or right one character the user sees.  The user sees 4 characters in that code, 2 in the string and two quotes.

### Actual Behavior

Terminal acts like there are 5 characters.  It treats `🜨` as two characters.  I'm  creating this with FF 126.0 and it handle this situation correctly.  In this image, the caret was past the end of the string.

![image](https://github.com/microsoft/terminal/assets/5451058/4c0dfdbc-819e-483c-a4ce-25d4d006637f)

**Comment by lhecker** [comment]
Unfortunately, this is a bug in PowerShell, or more specifically in PSReadLine (which is a module in PowerShell that provides the commandline edit experience). If you try your string in a cmd tab for instance, you should notice that it works correctly. I believe this is the most active issue in their repo about this right now: https://github.com/PowerShell/PSReadLine/issues/2358
I've heard internally that they're currently trying to fix this issue, but there's no timeline yet when that may be done (doing it correctly is non-trivial).
