### ISSUE TITLE
Current clipboard text is pasted into the terminal when dragging the current tab page

### ISSUE THREAD

**Issue by galaxytass** [microsoft/terminal#17324]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.19045.4412

### Steps to reproduce

1) Copy some text to your clipboard,
2) Drag the current tab page.

### Expected Behavior

The input line remains empty.

### Actual Behavior

The clipboard text is repeatedly pasted into the terminal.

**Comment by zadjii-msft** [comment]
AHG we definitely saw this too during Build last week. For us the repro wasn't super consistent though - as soon as I went to go report it, it went away. 

I _think_ we were using a canary 1.22 build at the time, but we did also have a 1.20 preview build running on that machine. Impossible to say now. 

Thanks for filing this!

**Comment by jamief** [comment]
I'd like to add to this as this just began happening to me ONLY after enabling "Advanced Pasting" in Windows PowerToys.

Also using Windows Terminal version 1.19.11213.0. This happens in Windows Terminal Preview v 1.21.1272.0 as well.

Using Windows PowerToys version v0.81.0.

I am also on Windows 10 build number 19045.4412.

As soon as I disable "Advanced Paste" in PowerToys, I no longer have the issue.

Could they be related?

Hope it helps!

**Comment by galaxytass** [comment]
Disabling "Advanced Pasting" indeed solves the issue.

**Comment by zadjii-msft** [comment]
I believe the upstream is https://github.com/microsoft/PowerToys/issues/32971

**Comment by carlos-zamora** [comment]
Fixed on the PowerToys side by https://github.com/microsoft/PowerToys/pull/32976

Apparently Terminal is sending a None kb key on drag and Slack does the same when you left-click their sysstray icon. So PowerToys _was_ reacting to that key sent. It'd be nice to investigate why we're sending the key.

**Comment by DHowett** [comment]
> Apparently Terminal is sending a None kb key on drag and Slack does the same when you left-click their sysstray icon. So PowerToys was reacting to that key sent. It'd be nice to investigate why we're sending the key.

This is a normal way for applications to send signals to eachother (or themselves); it isn't a bug to be investigated. :)

**Comment by zadjii-msft** [comment]
I cannot tell you how relieved I am that it wasn't us for a change. 

/dup https://github.com/microsoft/PowerToys/issues/32971
