### ISSUE TITLE
Resizing drawing issue on Ubuntu

### ISSUE THREAD

**Issue by philoez98** [microsoft/terminal#1732]
# Environment

```none
Windows build number: [run "ver" at a command prompt] Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0


```

# Steps to reproduce
Simply resize the terminal window back and forth.

# Expected behavior
The content resizes correctly

# Actual behavior
![ezgif com-optimize](https://user-images.githubusercontent.com/40722053/60396003-31f51880-9b3c-11e9-9238-e49d59ea6f1e.gif)

**Comment by mcpiroman** [comment]
Looks like #1433, nice video tho.

**Comment by DHowett-MSFT** [comment]
Yep, that’s a duplicate! Thanks @mcpiroman :)
