### ISSUE TITLE
move the tab,the copied text will be pasted into the inputbox of the active tab

### ISSUE THREAD

**Issue by tongtongstudio** [microsoft/terminal#17328]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Open terminal and open two tabs,copy some text,then move the tab,the copied text will be pasted into the inputbox of the active tab

https://github.com/microsoft/terminal/assets/35002905/c99419b2-5f07-4cf2-80d6-104ad1519a61

### Actual Behavior

move the tab,the copied text will be pasted into the inputbox of the active tab

**Comment by j4james** [comment]
Thanks for the report. This looks like the same thing as #17324. And some of the comments there suggest that it may be an issue with the _Advanced Pasting_ option in Windows PowerToys. If you've got that installed, try turning off that feature and see if it fixes the problem.

**Comment by zadjii-msft** [comment]
Yea, let's dedupe this for now. 

Thanks @j4james!

/dup #17324
