### ISSUE TITLE
Regression in launching links

### ISSUE THREAD

**Issue by chrisant996** [microsoft/terminal#17323]
### Windows Terminal version

1.21.1272.0

### Windows build number

19045.4412

### Steps to reproduce

1. Open a cmd.exe tab in Terminal.
2. Run `echo Hello ^(https://github.com/chrisant996/clink^)`.
3. Move the mouse over the hyperlink -- observe that the hyperlink is underlined correctly.
4. Ctrl+Click the hyperlink -- the `)` is mistakenly included in the URL, and causes the web navigation to fail.

### Expected Behavior

It should open the link `https://github.com/chrisant996/clink`.
It should open the same link that it underlined.
Terminal 1.19.11213.0 works correctly.

### Actual Behavior

It opened the link `https://github.com/chrisant996/clink)` -- note that the `)` was mistakenly included.
What it opens is different from what it underlined.

**Comment by tusharsnx** [comment]
Thanks for reporting this.

I believe `result->stop` is an exclusive coord, but it was passed down to the GetPlainText which expects inclusive coords:
https://github.com/microsoft/terminal/blob/5d1cf1a704986808d09ae7729aaed39ce5d5f909/src/cascadia/TerminalCore/Terminal.cpp#L525

On it.

**Comment by DHowett** [comment]
@tusharsnx, @lhecker do either of you know if this will impact 1.20 as well?

**Comment by DHowett** [comment]
Checked it out - yes, 1.20 is impacted. I'll service this.

Thanks @chrisant996 for the report!

**Comment by chrisant996** [comment]
Ah, I see, yes it's fresh, introduced by 5b8eadb2ea16206bac2bb1c0b06f35bd4d0aae15 a month ago. 👍

**Comment by Psypher1** [comment]
Hello, I was told my issue #17424 is already being tracked here. My question; I see a merge was done. Does that mean I should update terminal to enact the changes?

Because while the merge sort of handle a similar issue, it's not quite what I'm experiecing

**Comment by lhecker** [comment]
Preview will receive the fix sometime soon. Until then you can test out our nightly version here: https://aka.ms/terminal-canary-installer
Don't worry: If you uninstall it later, no traces will be left behind. :)
