### ISSUE TITLE
[UI] there is a top edge white line

### ISSUE THREAD

**Issue by htharoldht** [microsoft/terminal#17325]
### Windows Terminal version

v1.20.11271.0

### Windows build number

10.0.18363.0

### Steps to reproduce

start up wt

### Actual Behavior

As shown in the picture, there is an obvious white line at the top, which is extremely disharmonious!

![img_v3_02ba_78e25616-454c-4954-85cc-0d460321ec2g](https://github.com/microsoft/terminal/assets/31093493/fdd05335-c329-4639-9212-62e24c3f264f)

**Comment by zadjii-msft** [comment]
I'm pretty confident that 18363 isn't a build of Windows that we officially support with the Terminal anymore. Does this repro on Windows Build 19041 or higher/?

**Comment by DHowett** [comment]
This is correct. We do not support 10.0.18362/18383.

**Comment by htharoldht** [comment]
> 我非常有信心 18363 不再是我们在终端上正式支持的 Windows 版本。这在 Windows Build 19041 或更高版本/上是否重现？

No, but I would like to know what might be causing this display problem, if possible.

**Comment by carlos-zamora** [comment]
Thanks for filing. Sorry, but there have been a lot of fixes between 18363 and 19041. Closing since we're not supporting that build of Windows.
