### ISSUE TITLE
Duplicate tab does not use the same command as the original tab

### ISSUE THREAD

**Issue by cverbiest** [microsoft/terminal#17337]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.19045.0

### Other Software

ssh

### Steps to reproduce

Start ssh session using
`wt  ssh user@domain.local@hostname -i ~/.ssh/id_rsa`

Select "Duplicate tab" from the ssh session tab

A new tab is created using the default profile  instead of a new ssh session

### Expected Behavior

Duplicate tab should also duplicate the command used to start the tab. Duplicate a ssh tab creates new ssh tab

### Actual Behavior

A default profile tab is created

**Comment by cverbiest** [comment]
Seems to be related to https://github.com/microsoft/terminal/issues/5047 but that issue only mentions commandline in the comments

**Comment by zadjii-msft** [comment]
You know what, I'll give it to the bot. It did find a dupe, which pointed at the right one over in /dup #5047. That was nice. 

Anywho, if you end up making a full _profile_ for that ssh session, then yea, duplicate tab will work. But for this specific scenario, I'd follow and 👍 #5047. Thanks!
