### ISSUE TITLE
An app opened from inside Terminal stays behind Terminal (but above other apps)

### ISSUE THREAD

**Issue by amaramth** [microsoft/terminal#17340]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.19045.4412

### Other Software

tmux 3.4 inside bash 5.2.21(1)-release (x86_64-pc-linux-gnu) inside Ubuntu 24.04 WSL (wsl.exe version 10.0.19041.4355)

windows terminal set to maximized focus

~/.tmux.conf containing
```
set -g prefix F1
set -g mouse on
set -g allow-rename off
set -g status off
bind-key -T prefix  M-7  resize-pane -x 72
bind-key -T prefix  M-8  resize-pane -x 80
bind-key % set-environment -F PWD "#{pane_path}" \; split-window -h -c "#{pane_path}"
bind-key '"' set-environment -F PWD "#{pane_path}" \; split-window -c "#{pane_path}"
```

### Steps to reproduce

run any app, such as `'/mnt/c/Program Files/Sublime Text 3/sublime_text.exe'`

### Expected Behavior

the app opens in front. this works correctly if the command is run in bash directly.

### Actual Behavior

the app opens in front of windows other than windows terminal, but behind windows terminal

**Comment by amaramth** [comment]
i fixed this by blanking ~/.tmux.conf, reloading tmux source, and then replacing the contents. various restarts (of tmux, windows terminal, windows) did not fix this. modifying launch mode from maximized focus to normal did not fix this.

**Comment by amaramth** [comment]
it did not stay fixed

**Comment by carlos-zamora** [comment]
Does this only happen in WSL /?

**Comment by amaramth** [comment]
this happens specifically in tmux in wsl. for example, i open command prompt, run `mpv.exe file`; this bug does not occur. i open command prompt, run `bash`, then run `mpv.exe file`; this bug does not occur. i open command prompt, run `bash`, run `tmux`, then run `mpv.exe file`; this bug does occur.

this bug also occurs if i use windows terminal instead of command prompt.

i file this bug here instead of https://github.com/tmux/tmux - this is an issue with windows, not tmux.
maybe i should file in https://github.com/microsoft/WSL? but they state to please file UI/UX related issues here.

**Comment by carlos-zamora** [comment]
> maybe i should file in [microsoft/WSL](https://github.com/microsoft/WSL)? but they state to please file UI/UX related issues here.

Generally, yes, but because WSL interop is involved, let's file the bug over there. Could you file the bug on [their repo](https://github.com/microsoft/WSL)? Thanks
