### ISSUE TITLE
`powershell.exe` starts a new console rather than attaching to current when not elevated

### ISSUE THREAD

**Issue by SteveL-MSFT** [microsoft/terminal#17347]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.3593

### Steps to reproduce

In non-elevated cmd.exe within WT, run: `powershell.exe`

Note: this repros with conhost

### Expected Behavior

`powershell.exe` uses the current console and starts within cmd.exe

### Actual Behavior

`powershell.exe` is spawned in a new window

Note:  if `cmd.exe` is elevated, then `powershell.exe` DOES start within the same console.  This also seems to only repro to domain joined systems and doesn't repro with a clean system in a workgroup so might be related to some GPO?

**Comment by zadjii-msft** [comment]
There's definitely something to the idea that it being domain-joined breaks it. 

My home laptop:
![image](https://github.com/microsoft/terminal/assets/18356694/e614bddc-ee4f-4d4a-bcde-bad43f2e4c5f)


my work VM:
![image](https://github.com/microsoft/terminal/assets/18356694/c20e623b-547e-402a-8967-c2682102ee57)

Same Windows builds. Different results. Yikes.

**Comment by yaozhenhua** [comment]
I noticed this problem too. It breaks our build process since we run powershell scripts in MSBuild. Now before the execution is completed the build has already moved forwarded which ends up an empty file.

**Comment by MichalStrehovsky** [comment]
This is related to some bad InTune policies that were rolled out Microsoft-wide. Opening Terminal as an administrator works around. Tickets with Microsoft IT have been raised internally.

**Comment by joon612** [comment]
> This is related to some bad InTune policies that were rolled out Microsoft-wide. Opening Terminal as an administrator works around. Tickets with Microsoft IT have been raised internally.

Could you provide more information about this? Our team and our services have been greatly affected by this issue, thanks!

**Comment by MichalStrehovsky** [comment]
> > This is related to some bad InTune policies that were rolled out Microsoft-wide. Opening Terminal as an administrator works around. Tickets with Microsoft IT have been raised internally.
> 
> Same issue here. Could you provide more information about this? Our team and our services have been greatly affected by this issue, thanks!

I don't have more information, sorry. Several of my Redmond-based coworkers were hitting this in the past 24 hours and at least two of them have a case number with MSIT. I can't refer you to the case number since Redmond is sleeping now but the issue started showing up after an Intune policy rollout. I recommend opening a case with MSIT as well.

**Comment by SteveL-MSFT** [comment]
Closing this as it appears to be Microsoft internal policy issue
