### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pygriaaf** [microsoft/terminal#1734]
#Demand report:
    -1.Need a better shell.
#Reason:
    -1.CMD is too old, and Incomplete function.
    -2.PowerShell's syntax is irrational. Commands and parameters are too long.
    -3.No matter how nice Windows Terminal is, it is just a beautiful coat.
#Solution
    -1.Program a new shell instead of cmd or powershell。
    -2.It is best to use bash, zsh, etc. as a shell.

PS: My English is not very good, please understand.

**Comment by DHowett-MSFT** [comment]
You can configure Windows Terminal to use whatever shell you want. Also, just a tip, it can be rude to say “Demand”. Consider the word “Request” Instead. :smile:
