### ISSUE TITLE
please make windows terminal into microsoft terminal with gtk3 buttons

### ISSUE THREAD

**Issue by YeesterPlus** [microsoft/terminal#17345]
# Description of the new feature/enhancement

port to linux

# Proposed technical implementation details (optional)

rewrite and compile for linux

**Comment by DHowett** [comment]
Thanks for the idea! We're not planning on porting Windows Terminal to any other platforms at the moment, but we'll keep it in mind.

**Comment by YeesterPlus** [comment]
May I please do it?

**Comment by lhecker** [comment]
Of course you can try it. You can do almost anything with this source code, as it's MIT licensed. But as Dustin said, you will fail in porting this project. It's almost entirely Windows-specific.
