### ISSUE TITLE
Issue with selectionBackground color

### ISSUE THREAD

**Issue by steakhutzeee** [microsoft/terminal#17355]
### Windows Terminal version

1.19.11213.0

### Windows build number

10.0.22621.0

### Other Software

N/A

### Steps to reproduce

Applied the following theme:

https://github.com/folke/tokyonight.nvim/blob/main/extras/windows_terminal/tokyonight_night.json

```
{
    "background": "#1a1b26",
    "black": "#15161e",
    "blue": "#7aa2f7",
    "brightBlack": "#414868",
    "brightBlue": "#7aa2f7",
    "brightCyan": "#7dcfff",
    "brightGreen": "#9ece6a",
    "brightPurple": "#9d7cd8",
    "brightRed": "#f7768e",
    "brightWhite": "#c0caf5",
    "brightYellow": "#e0af68",
    "cursorColor": "#c0caf5",
    "cyan": "#7dcfff",
    "foreground": "#c0caf5",
    "green": "#9ece6a",
    "name": "Tokyo Night",
    "purple": "#bb9af7",
    "red": "#f7768e",
    "selectionBackground": "#283457",
    "white": "#a9b1d6",
    "yellow": "#e0af68"
}
```

but I'm experiencing an issue with the `selectionBackground` color.

As you can see from the screenshot it actually changes to a different color code, different from `#283457`

![color](https://github.com/microsoft/terminal/assets/57228102/3a3d9190-bec6-490c-ad22-0bca5a92ab34)

If I use a picker I see that it's set to `#21273F` instead. 

Any hints why this happens?

Thank you!

### Expected Behavior

`selectionBackground` set to `283457` .

### Actual Behavior

`selectionBackground` is set to `21273F` instead.

**Comment by DHowett** [comment]
Unfortunately, yes, `selectionBackground` is blended at 50% opacity with the contents of the terminal. This will result in some differences depending on what is being displayed.

We're tracking making this better in /dup #3561 -- though don't let the exact title fool you, it means "do selection colors better"

**Comment by steakhutzeee** [comment]
> Unfortunately, yes, `selectionBackground` is blended at 50% opacity with the contents of the terminal. This will result in some differences depending on what is being displayed.
> 
> We're tracking making this better in /dup #3561 -- though don't let the exact title fool you, it means "do selection colors better"

Thank you for the quick feedback!
