### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [microsoft/terminal#1736]
# Environment

```none
Windows build number: [run "Version 10.0.18912.1001" at a command prompt]
Windows Terminal version (if applicable): unsure how to check, fresh install from the Microsoft Store

Any other software?
```

# Steps to reproduce

Start windows terminal,
Open couples of tabs
Try to select and then close final tab
# Expected behavior

Every tab should be able to select, and close
# Actual behavior

![Issue](https://user-images.githubusercontent.com/38671143/60399567-8ec3f380-9b7b-11e9-8313-191d27098e5e.gif)

**Comment by DHowett-MSFT** [comment]
#857
