### ISSUE TITLE
Background opacity and background acrylic meterial is not worked

### ISSUE THREAD

**Issue by truongan012** [microsoft/terminal#17367]
### Windows Terminal version

1.20.240506001

### Windows build number

10.0.19043.928

### Steps to reproduce

1. Launch terminal
2. Change background opacity in powershell profiles lower 100% and enable acrylic material.
3. Save
4. Open powershell tab

The same issue with background image opacity
![image](https://github.com/microsoft/terminal/assets/13611865/b9eaff96-3cab-460f-a15b-91d68dc616e6)

### Expected Behavior

Powershell tab opacity should work

### Actual Behavior

Background opacity is always 100% and enable acrylic meterial is not worked
![image](https://github.com/microsoft/terminal/assets/13611865/a2cc0cab-1bc4-4c38-99c7-3b0bd48eedef)

Enable acrylic meterial in tab row is still work
![image](https://github.com/microsoft/terminal/assets/13611865/22792cc0-2e99-4794-b679-ebe2013e45e7)

**Comment by zadjii-msft** [comment]
Okay I think I'm ultimately tracking this in /dup #16745


Another user reported that things got better after adding `"compatibility.enableUnfocusedAcrylic": false` to the global settings (i.e. next to `useAcrylicInTabRow`) (then rebooting the Terminal).
