### ISSUE TITLE
Keyboard Focus lost when entering WSL2

### ISSUE THREAD

**Issue by rainerzufalldererste** [microsoft/terminal#17373]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.3593

### Steps to reproduce

- Open a new Terminal Tab with cmd.exe
- Type `wsl` or `bash`
- Continue typing to notice that Keyboard Focus has been lost
- Click on Terminal to restore Keyboard Focus

### Expected Behavior

Keyboard Focus is maintained

### Actual Behavior

Keyboard Focus is lost

**Comment by zadjii-msft** [comment]
I am almost certain this is being tracked in https://github.com/microsoft/wslg/issues/894

**Comment by zadjii-msft** [comment]
Nope found the right comment: https://github.com/microsoft/terminal/issues/12134#issuecomment-1010333944

> can you check if disabling Linux GUI support by adding the below to `.wslconfig` (refer docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig)
> 
> ```ini
>  [wsl2]
>  guiapplications=false
>
>  ```

For linking:
* /dup https://github.com/microsoft/WSLg/issues/443
* https://github.com/microsoft/WSL/issues/7511
