### ISSUE TITLE
Drag tab into other tab to merge into split pane

### ISSUE THREAD

**Issue by Pl8tinium** [microsoft/terminal#17370]
# Description of the new feature/enhancement

When dragging a tab, it should be possible to drag it into an existing windows right or left side to merge this tab with the existing one into a split pane. 

See screenshots below

![image](https://github.com/microsoft/terminal/assets/50824212/3edba034-0573-47af-b886-729e27c2ac4c)

to 

![image](https://github.com/microsoft/terminal/assets/89969177/19210d54-6e95-4f5b-af1f-026bd65e387c)

In general this is useful because i usually work in multiple tabs and then afterwards just recognize that 2 tabs belong together and i want to inspect them at the same time, i usually then need to split and initialize it in the same way as my other tab 
... (set env variables, connect to ssh, and so on). If i do that i also dont have the history of commands of that window/ session which could sometimes be very handy

# Proposed technical implementation details

left side drag should result in the the split taking the new window to the left side, right side drag should result in the other way around

maybe also bottom side drag and top side drags would result in different splits

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4587 for more discussion.

/dup #4587


----

sidebar: the dupe bot _almost_ found this one. https://github.com/microsoft/terminal/actions/runs/9384087232/job/25839130085#step:2:84

```
  {
    "score": 0.791504443,
    "title": "Drag & Drop Tabs to create a Pane",
    "number": 4587,
    "html_url": "https://github.com/microsoft/terminal/issues/4587",
    "state": "open"
  },
```

maybe .8 was too high? .75 was definitely too low though: https://github.com/microsoft/terminal/pull/17318/files
