### ISSUE TITLE
Support custom environment.

### ISSUE THREAD

**Issue by zhizhi-dev** [microsoft/terminal#17379]
# Description of the new feature/enhancement
Like vscode , user can custom enviroment var using json .
```json
{
  "env" : {
    "PYTHONUTF8=1",
  }
}
```

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the request! 

* This was originally tracked in /dup #2785
* it was added in #15082
* and that first shipped in Terminal 1.18

And you can enable it like so:

> The profile's environment completely replaces the one specified in defaults.
> 
> So if you've got:
> 
> ```json
> "defaults": {
>   "environment": {
>     "Foo": "Bar"
>   }
> },
> "list": [
>   {
>     "name": "PowerShell",
>     "environment": {
>       "Baz": "Qux"
>     }
>   }
> ]
> ```
> 
> Your PowerShell profile will get `Baz=Qux` and your cmd profile will get `Foo=Bar`.

But looks like it never made it to the docs repo.

**Comment by zhizhi-dev** [comment]
thanks !!

**Comment by ThioJoe** [comment]
This is perfectly timed, literally today I was wondering if there is a way to customize how the prompt text looks to add a space before the cursor, and turns out there is!

```
"environment": {
                "PROMPT": "$P$G$S"
            }
```
