### ISSUE TITLE
File URLs are no longer opened after clicking (e.g. file:///C:/Test/)

### ISSUE THREAD

**Issue by rainman74** [microsoft/terminal#17372]
### Windows Terminal version

1.20.11381

### Windows build number

10.0.26100.712

### Steps to reproduce

1. Enter a file URL in the prompt (e.g. file:///C:/Windows/)
2. Press Return (ignore error message)
3. The URL is recognized correctly and underlined
4. Click on the URL with CTRL and mouse button
5. Window Explorer will no longer open in this path

Note: This is only intended for reproducing the error behavior, in real operation these URLs are automatically generated in a batch file and displayed via echo output.

### Expected Behavior

As in the previous terminal version 1.19.xxx, Windows Explorer was opened with the path when clicked. This is also the expected behavior.

### Actual Behavior

Nothing happens when clicking since version 1.20.xxx (the exact subversion cannot be named, from when this misbehavior occurs)

**Comment by zadjii-msft** [comment]
Weird, I can repro this in `1.20.11381.0` and `1.21.1382.0`, but _not_ in `1.22.1521.0` canary. w e i r d.

**Comment by zadjii-msft** [comment]
oh we found it!


/dup #17323


we'll service this soon ☺️
