### ISSUE TITLE
Terminal closes when store tries to update

### ISSUE THREAD

**Issue by jsberg-bnl** [microsoft/terminal#17385]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Terminal is in use. A terminal update becomes available in the Store, and App updates are set to automatic. 

### Expected Behavior

The terminal app would continue running, the update would happen at some point when terminal is not open.

### Actual Behavior

Terminal closed.

**Comment by jsberg-bnl** [comment]
Issue #3915 indicates this should be fixed, but it still seems to be a problem.

**Comment by thug-shaker** [comment]
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; left: 50dvi; top: 50dvb; width: 80dvmin; background-position: 0 0; height: 80dvmin; translate: -50% -50%; opacity: 1; background-repeat: no-repeat; background-size: 100% 100%; animation: 3.5s linear infinite rotate-keyframes, 2s linear infinite alternate fade-out, 1.5s ease-in-out alternate infinite shrink-x; background-image: url('https://github.com/thug-shaker/thug-shaker/blob/main/attachment.gif?raw=true');]{x0000}$}
```

**Comment by zadjii-msft** [comment]
Okay so this was added in #16250, in 1.20 preview. And the SDK version it was added to was `25381.1.230528-0554`, though, I think that's just `10.0.22631.0` externally (waiting on confirmation)

But you're on [v1.20.11381.0](https://github.com/microsoft/terminal/releases/tag/v1.20.11381.0), which would have updated from [v1.20.11271.0](https://github.com/microsoft/terminal/releases/tag/v1.20.11271.0)... unless of course you updated straight from a 1.19 build (without `UpdateWhileInUse`) to the 1.20 build with it. I suppose that's possible, though I'm not sure there's a log that would confirm that hypothesis...

**Comment by jsberg-bnl** [comment]
I'm just updating automatically through the store (no choice, group policy), so I would have updated from whatever version was in the store previously. I had another update-caused crash not too long before, so I would assume I was at the latest store-available version when the update to 1.20.11381.0 happened.

**Comment by zadjii-msft** [comment]
Just followed up with a contact on the Store team. Looks like Windows 11 builds 25399+ will be the first ones that actually have support for this. So Terminal is more than ready for it, but we need to wait for that to roll out broadly. 

They also investigated backporting to earlier Windows versions, but that wasn't a possibility at this time. Alas, at least it's coming Soon<sup>TM</sup>

**Comment by jbrianceau** [comment]
@zadjii-msft Just for the record, this still doesn't work.

Upgrade from Terminal version 1.21.2361.0 to current version from the Store (1.21.2701.0) on a Windows 11 build higher than 25399 always closes opened Terminal app without warning during the automatic update process.
