### ISSUE TITLE
Weird x5c path output when opening a integrated terminal in VSCode

### ISSUE THREAD

**Issue by shyney7** [microsoft/terminal#17381]
### Windows Terminal version

1.21.1382.0 (preview) and 1.20.11381.0

### Windows build number

10.0.19045.0

### Other Software

VSCode 1.90.0

### Steps to reproduce

Open a integrated Terminal inside VSCode

### Expected Behavior

No weird path output with x5c x1b outputs

### Actual Behavior

When I open a integrated Terminal in VSCode I get a weird path output that looks like this:
![grafik](https://github.com/microsoft/terminal/assets/17785769/0868a8d1-a712-4291-9f23-9a006d1db576)
This issue was also mentioned in the vscode repo and the devs say its a windows terminal problem.
https://github.com/microsoft/vscode/issues/211721

**Comment by zadjii-msft** [comment]
Okay, but does this actually repro in the Windows Terminal? Or only in VsCode/? 

Does this repro in a `conhost.exe` window? 

---

`0x5c` is just a `\`, so it kinda looks like there some extra level of escaping going on _somewhere_ in the stack. Like the OSC9;9 sequence got translated one too many times. 

I'd also reckon that this may be related to some combination of oh-my-posh and VsCode's own shell integration.

**Comment by zadjii-msft** [comment]
Upon investigation, I'm betting this is https://github.com/microsoft/vscode/issues/214386

**Comment by shyney7** [comment]
> Upon investigation, I'm betting this is [microsoft/vscode#214386](https://github.com/microsoft/vscode/issues/214386)

Ok thank you for the investigation and clarafication. I will close the isse since it seem not to be a Windows Terminal issue per se

**Comment by shyney7** [comment]
Relevant vscode issue (June Milestone): https://github.com/microsoft/vscode/issues/211922
