### ISSUE TITLE
When sorting tabs the content of the clipboard is pasted several times into the shell and the sort stutters

### ISSUE THREAD

**Issue by cbusoi** [microsoft/terminal#17399]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22635.3720

### Steps to reproduce

Open two terminal tabs and try to sort the tabs. 
I have made a video which shows the outcome.

https://github.com/microsoft/terminal/assets/1805182/e53fadae-518f-45a4-a034-f3a88e5cbc64

### Expected Behavior

To sort the tabs, not stutter when dragging the tab and not to insert the clipboard content in to the shell.

### Actual Behavior

The drag of a tab stutters and shakes and strange, the content of the clipboard is pasted as red text into the shell.

**Comment by zadjii-msft** [comment]
This looks like that PowerToys bug - I'd recommend updating to the latest PowerToys version

**Comment by cbusoi** [comment]
Good hint. Updated to PowerToys [Release v0.81.1](https://github.com/microsoft/PowerToys/releases/tag/v0.81.1) and this fixes the issue. 

thx @zadjii-msft
