### ISSUE TITLE
No terminal resize notification for unix/linux programs

### ISSUE THREAD

**Issue by ant5** [microsoft/terminal#17390]
### Windows Terminal version

1.21.1272.0

### Windows build number

10.0.19045.4291

### Other Software

QEMU 9.0

### Steps to reproduce

Run QEMU with unix-like guest OS which serial port connected to console (WindowsTerminal).  Resize Terminal window.

### Expected Behavior

As I understand WindowTerminal must emit control sequence to notify of width/height change.
Here is a screenshot of similiar system in another terminal that resize correctly: 

![image](https://github.com/microsoft/terminal/assets/11061796/677953e7-fd56-4a72-9c3e-0b67631d5cdd)

### Actual Behavior

Window is reisized but internal structure get corrupt. Notice the cursor moved outside it normal position. I think this is a result of adapation maked by WindowsTerminal itself. 

![image](https://github.com/microsoft/terminal/assets/11061796/b97905f8-136e-460b-b1cd-9f87ae4f0beb)

But most unix terminal programs can handle terminal resize notification.  It will be very nice to have it for seamless integration.

**Comment by DHowett** [comment]
Thanks for filing! Are you running QEMU-for-Windows or QEMU inside WSL? There is a standard resize message that the Windows console subsystem generates, and I would guess that qemu-for-win is not handling it.

For what it's worth, running something _inside qemu's serial console_ is much more specific than just "unix/linux programs" 🙂

**Comment by thug-shaker** [comment]
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; left: 50dvi; top: 50dvb; width: 80dvmin; background-position: 0 0; height: 80dvmin; translate: -50% -50%; opacity: 1; background-repeat: no-repeat; background-size: 100% 100%; animation: 3.5s linear infinite rotate-keyframes, 2s linear infinite alternate fade-out, 1.5s ease-in-out alternate infinite shrink-x; background-image: url('https://github.com/thug-shaker/thug-shaker/blob/main/attachment.gif?raw=true');]{x0000}$}
```

**Comment by ant5** [comment]
Hello!
I'm using QEMU-for-Windows.
As I understand QEMU just put data from emulated-for-guest COM-port to the stdout and let stdin go to the COM-port.

I think the first question is:  Does the terminal resize generate special escape sequence that goes to stdin of a process attached to the terminal?

**Comment by DHowett** [comment]
> I think the first question is: Does the terminal resize generate special escape sequence that goes to stdin of a process attached to the terminal?

It does not -- this is true of all terminal emulators on all platforms.

On Linux and POSIX-compatible equivalents, the TTY or PTY driver sends `SIGWINCH` (the window change signal.) It does not generate VT.

On Windows, the console subsystem inserts a `WINDOW_BUFFER_SIZE_EVENT` into the input stream, which WSL and most POSIX translation layers translate into `SIGWINCH`.

I do not believe there is a standard in-band signal for window size changes. QEMU-for-Windows should be listening for `WINDOW_BUFFER_SIZE_EVENT`... however: serial ports typically do not resize. There may not be an in-band signal that its serial port emulation can use to _cause_ the guest OS to generate a `SIGWINCH`.

I cannot find any window handling in QEMU's code that would give support for window resizing to the ISA or PCI serial devices. 🙂

**Comment by ant5** [comment]
Hmm...

Really there is a separate technique of resize notification:

https://github.com/contour-terminal/contour/discussions/1236#discussioncomment-7222641

But things work over ssh so I'm wondering does an ssh/telnet protocol cover this case.

Also I'm wandering was there a hardware terminal that has switch screen size and how do they do it over serial line. May be I'll ask somebodies in invisible island about  this if they are reachable...

**Comment by DHowett** [comment]
> Really there is a separate technique of resize notification:
> 
> [contour-terminal/contour#1236 (reply in thread)](https://github.com/contour-terminal/contour/discussions/1236#discussioncomment-7222641)

The comment you linked to says this:

> Size change -> TE resizes PTY with syscall -> application receives SIGWINCH -> TUI queries size from TE or with a SYSCALL -> response

Which is exactly what I described above. There doesn't seem to be another way 🙂 

If you find another way to handle this, please feel free to comment here and I will reopen the issue! Thanks so much!
