### ISSUE TITLE
Unicode symbols are turning into emojis

### ISSUE THREAD

**Issue by malezjaa** [microsoft/terminal#17400]
### Windows Terminal version

1.20.11381.0

### Windows build number

Microsoft Windows NT 10.0.22631.0

### Steps to reproduce

Log unicode characters like: `U+2139`, `U+26A0`, 

### Actual Behavior

These characters are turning into emojis:
![image](https://github.com/microsoft/terminal/assets/66274761/77a3a944-6b83-44eb-8ee6-238ad2e7de4d)

![image](https://github.com/microsoft/terminal/assets/66274761/74df024c-7e15-4e23-8d03-8f18b598b2f4)

This works fine in webstorm

Is there a way to fix or disable it?

**Comment by Lo0oG** [comment]
An option for this was added to the v1.21 preview (see #16871)

**Comment by malezjaa** [comment]
![image](https://github.com/microsoft/terminal/assets/66274761/0db88057-1ecb-4f29-9af5-6a4b5efbbb7b)
That's not really what I want. It just removes colors

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #13110.
