### ISSUE TITLE
Bug Report: Cursor no longer pauses blinking when focus is lost

### ISSUE THREAD

**Issue by dkter** [microsoft/terminal#1741]
# Environment

Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): Issue appears starting with commit https://github.com/microsoft/terminal/commit/ab08320dde8adf160b72af3e8bf51ee26f6cb476

# Steps to reproduce

1. Open Windows Terminal
2. Switch focus to another window

# Expected behavior

The cursor stops blinking and turns off, as it did before.

# Actual behavior

The cursor continues to blink.

I tested before and after https://github.com/microsoft/terminal/commit/ab08320dde8adf160b72af3e8bf51ee26f6cb476 and it seems like the issue started with that commit.

**Comment by angelog0** [comment]
I use the box cursor (`filledBox`) and when the focus is lost it disappears completely. On other terminals (`MinTTY`, `iTerm2`, for example), and in `Emacs`, when the focus is lost, the cursor becomes an empty box (not filled rectangle). 

I think that Windows Terminal should have the same behavior...

**Comment by dkter** [comment]
The issue only happens with `showTabsInTitlebar` on.

**Comment by dkter** [comment]
`TermControl::_LostFocusHandler` is not called when the window loses focus, but *is* called when the tab loses focus and the window stays in focus.

**Comment by dkter** [comment]
It seems this issue was inadvertently fixed at some point, so I'm closing it.
