### ISSUE TITLE
Terminal update crashes all running applications

### ISSUE THREAD

**Issue by Xenius97** [microsoft/terminal#17415]
### Windows Terminal version

10.0.19045.4412

### Windows build number

19045.4412

### Steps to reproduce

After terminal got an update, all of running apps will crash immediately.

### Expected Behavior

No crash

### Actual Behavior

Windows Update is disabled everywhere but terminal still getting unwanted updates. How to disable it????

**Comment by zadjii-msft** [comment]
Alas, yep, that'll happen on Windows 10. This was fixed in the app platform in Windows 11, but unfortunately, that doesn't seem like something they can backport to Windows 10. Sorry about that!

/dup #3915

(as fixed in #16250)

**Comment by Xenius97** [comment]
If you can't fix it why still supporting Windows 10?

> Windows Terminal requires Windows 10 2004 (build 19041) or later
<<< quote from readme

**Comment by zadjii-msft** [comment]
Because this doesn't really qualify as something to drop support for the whole OS over. It's been broken in Windows 10 forever, and despite this bug in the Store, the Terminal is still highly valuable on win10.

**Comment by dhj-io** [comment]
This happened on Windows 11 for me twice in the last two days.  A WSL update (the terminal was running WSL) and a Windows Terminal Update.  Both through the Microsoft Store, both crashed the terminal.  I had regular updates paused to avoid this, and I disabled automatic updates in the Microsoft Store the first time it happened.  Somehow, today automatic updates were turned on in the Windows Store.
