### ISSUE TITLE
No response when open windows terminal

### ISSUE THREAD

**Issue by Anz-03** [microsoft/terminal#17425]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.3737

### Steps to reproduce

Open windows terminal via shortcuts
https://github.com/microsoft/terminal/assets/106299500/358e018e-95dc-43cd-a6ff-dfc9196ec795

### Expected Behavior

 Open the terminal successfully.

### Actual Behavior

 Didn't. Have any response.

**Comment by Anz-03** [comment]
By the way I didn't use the famous font render mactype.

And I tried the solution from issue https://github.com/microsoft/terminal/pull/16939, Some people who have the same problem with me fixed this problem by turning off Settings-Rendering-Use the new text renderer("AtlasEngine").   But this solution doesn't work in my computer.

**Comment by carlos-zamora** [comment]
Can you share a copy of your settings.json /?

**Comment by Anz-03** [comment]
> Can you share a copy of your settings.json /?

{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        }
    ],
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": {},
        "list": 
        [
            {
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "\u547d\u4ee4\u63d0\u793a\u7b26"
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": true,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{458ea77d-d4f3-512b-b23b-9053f8892fce}",
                "hidden": false,
                "name": "Developer Command Prompt for VS 2022",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "guid": "{d41d1772-7c7d-5137-b12e-ea2cefbf96da}",
                "hidden": false,
                "name": "Developer PowerShell for VS 2022",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#4F525D",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#073642",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#555753",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        }
    ],
    "themes": []
}

**Comment by zadjii-msft** [comment]
Super weird. Launching the Terminal for defterm works for you, but opening a tab the normal way doesn't. There's nothing particularly standout about your settings either. 


Can you capture a dump for us using the feedback hub? That should get us a link to the crash, that we can investigate further. I'd:
* open PowerShell to open up the Terminal (like you did in the video). 
* Then start the recording with Feedback hub.
* Then attempt to open the new tab (causing the crash)

That should point us in the right direction. Thanks! 

/feedback

**Comment by JustTestCode** [comment]
The same problem happened yesterday, I checked my computer, the only change is that the system automatically updates the Chinese language pack, I don't know if this language pack affects this
```xml
<System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-06-13T10:35:03.9050648Z" /> 
  <EventRecordID>3998</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4772" ThreadID="12104" /> 
  <Channel>Application</Channel> 
  <Computer>desktop-win2go</Computer> 
  <Security UserID="S[-](https://github.com/microsoft/terminal/issues/17425#)1-5-21-3178200866-2858847593-4095046266-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">WindowsTerminal.exe</Data> 
  <Data Name="AppVersion">1.20.2405.17001</Data> 
  <Data Name="AppTimeStamp">66479c60</Data> 
  <Data Name="ModuleName">Windows.UI.Xaml.dll</Data> 
  <Data Name="ModuleVersion">10.0.26100.712</Data> 
  <Data Name="ModuleTimeStamp">6eb62e4d</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">0000000000903dd3</Data> 
  <Data Name="ProcessId">0x2190</Data> 
  <Data Name="ProcessCreationTime">0x1dabd7d55f845a4</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11381.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data Name="ModulePath">C:\Windows\System32\Windows.UI.Xaml.dll</Data> 
  <Data Name="IntegratorReportId">d1a9a587-8743-4536-b986-133ce601d3c0</Data> 
  <Data Name="PackageFullName">Microsoft.WindowsTerminal_1.20.11381.0_x64__8wekyb3d8bbwe</Data> 
  <Data Name="PackageRelativeAppId">App</Data> 
  </EventData>
  </Event>
```

**Comment by Anz-03** [comment]
> The same problem happened yesterday, I checked my computer, the only change is that the system automatically updates the Chinese language pack, I don't know if this language pack affects this
> 
> ```
> <System>
>   <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
>   <EventID>1000</EventID> 
>   <Version>0</Version> 
>   <Level>2</Level> 
>   <Task>100</Task> 
>   <Opcode>0</Opcode> 
>   <Keywords>0x8000000000000000</Keywords> 
>   <TimeCreated SystemTime="2024-06-13T10:35:03.9050648Z" /> 
>   <EventRecordID>3998</EventRecordID> 
>   <Correlation /> 
>   <Execution ProcessID="4772" ThreadID="12104" /> 
>   <Channel>Application</Channel> 
>   <Computer>desktop-win2go</Computer> 
>   <Security UserID="S[-](https://github.com/microsoft/terminal/issues/17425#)1-5-21-3178200866-2858847593-4095046266-1001" /> 
>   </System>
> - <EventData>
>   <Data Name="AppName">WindowsTerminal.exe</Data> 
>   <Data Name="AppVersion">1.20.2405.17001</Data> 
>   <Data Name="AppTimeStamp">66479c60</Data> 
>   <Data Name="ModuleName">Windows.UI.Xaml.dll</Data> 
>   <Data Name="ModuleVersion">10.0.26100.712</Data> 
>   <Data Name="ModuleTimeStamp">6eb62e4d</Data> 
>   <Data Name="ExceptionCode">c000027b</Data> 
>   <Data Name="FaultingOffset">0000000000903dd3</Data> 
>   <Data Name="ProcessId">0x2190</Data> 
>   <Data Name="ProcessCreationTime">0x1dabd7d55f845a4</Data> 
>   <Data Name="AppPath">C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11381.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
>   <Data Name="ModulePath">C:\Windows\System32\Windows.UI.Xaml.dll</Data> 
>   <Data Name="IntegratorReportId">d1a9a587-8743-4536-b986-133ce601d3c0</Data> 
>   <Data Name="PackageFullName">Microsoft.WindowsTerminal_1.20.11381.0_x64__8wekyb3d8bbwe</Data> 
>   <Data Name="PackageRelativeAppId">App</Data> 
>   </EventData>
>   </Event>
> ```

Yes, this problem occurs after I update my windows. But I have solved this problem by reinstalling windows 11 LTSC.

**Comment by Anz-03** [comment]
> Super weird. Launching the Terminal for defterm works for you, but opening a tab the normal way doesn't. There's nothing particularly standout about your settings either.
> 
> Can you capture a dump for us using the feedback hub? That should get us a link to the crash, that we can investigate further. I'd:
> 
> * open PowerShell to open up the Terminal (like you did in the video).
> * Then start the recording with Feedback hub.
> * Then attempt to open the new tab (causing the crash)
> 
> That should point us in the right direction. Thanks!
> 
> /feedback

I have solved this problem by reinstalling windows 11 LTSC. You can ask [JustTestCode](https://github.com/JustTestCode), who encounters the same problem. This problem occurs after we update our windows. Or, you simply close this issue.
