### ISSUE TITLE
Can't wake up a closed headless window

### ISSUE THREAD

**Issue by eusousu** [microsoft/terminal#17420]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Steps to reproduce

configure the options:
```
{
      "command": 
      {
          "action": "globalSummon"
      },
      "keys": "ctrl+alt+t"
},
```
and 
```
"compatibility.allowHeadless": true,
"minimizeToNotificationArea": true,
```

then open a window and close it (click on the top bar X).

try to make the window apper again.

### Expected Behavior

A month ago it would allow me to close the window (click on the top bar X) and keep it running on background with an icon in the tray. I would click the icon or hit ctrl+alt+t to focus the window and use the teminal.

### Actual Behavior

When I close the window (click on the top bar X) now I cant make it focus or apper in anyway. Not the shortcut, not clicking on the tray icon, nor even trying to open a new application window via start menu. The only action I can take after closing a window is going into the taskmanager, closing the terminal and then open it again. :/

**Comment by carlos-zamora** [comment]
Thanks for filing! It looks like we have some unexpected behavior here from a combination of bugs.
1. #16733: Windows should not show up in the tray after they've been closed
2. When `compatibility.allowHeadless` is enabled, `globalSummon` should work **(that's what we'll track in this bug)**

Here's some other issues that may appeal to you: #12933, #10448

**Comment by michaelarnauts** [comment]
See also https://github.com/microsoft/terminal/issues/17360 and https://github.com/microsoft/terminal/issues/17976
