### ISSUE TITLE
PHP Artsan command not recognised as URI

### ISSUE THREAD

**Issue by Psypher1** [microsoft/terminal#17424]
### Windows Terminal version

1.20.11381.0

### Windows build number

Version 22H2 (OS Build 19045.4412)

### Steps to reproduce

- Navigate to a Laravel project
- run `php artisan serve`
- ctrl + click the link

### Expected Behavior

A new window should load in the browser

### Actual Behavior

A pop up notification is shown. 
![pop up](https://github.com/microsoft/terminal/assets/34038162/ceed890b-664c-4bc2-aca1-d93e71df6d44)

It seems to be including the the closing `]` as part of the URL

Hovering over the link says

```
Invalid URI
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #17323 for more discussion.

/dup #17323
