### ISSUE TITLE
Pressing ESC + j or k will equal to Alt + j or k when using Neovim in Windows Terminal

### ISSUE THREAD

**Issue by fanlumaster** [microsoft/terminal#17427]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Other Software

NVIM v0.10.0
Lazyvim v12.13.0

### Steps to reproduce

Press esc + j or k at the same time in Insert Mode of Neovim.

### Expected Behavior

Back to Normal Mode, and move cursor to next or previous line.

### Actual Behavior

Swap current line with next or previous line.

Another issue in other repository that may be helpful: https://github.com/LunarVim/LunarVim/issues/1857

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #13792. When it's completed, that'll allow you to work around this issue by encoding ESC+J/K differently.
