### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Reelix** [microsoft/terminal#1743]
# Environment

```none
Windows build number:  [Version 10.0.18362.175]  
Windows Terminal version (if applicable): Version 0.2.1715.0

```

# Steps to reproduce

1.) Change the fontFace to "Verdana" - A native Windows font
2.) Save, and return to the terminal
3.) Zoom in slightly

# Expected behavior
The font is readable

# Actual behavior
The font is squashed, and difficult to read

![Sample image](https://i.imgur.com/jMydiuV.png)

**Comment by DHowett-MSFT** [comment]
We offer no warranty for when you use a proportional font in a monospaced environment.

**Comment by DHowett-MSFT** [comment]
For what it’s worth, this is by design. We aren’t going to support proportional fonts.
