### ISSUE TITLE
Font loading faults after Windows update KB5039212

### ISSUE THREAD

**Issue by i-e-b** [microsoft/terminal#17433]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Note: This is not the same as https://github.com/microsoft/terminal/issues/9375 , and the fix for that issue does not apply

1. Have a custom font set as the terminal font
2. Apply the Windows update "2024-06 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5039212)"
3. Restart system
4. Open the terminal app

### Expected Behavior

Terminal app should open, using the previously set font

### Actual Behavior

Terminal app opens with a new tab, showing this error message:
![image](https://github.com/microsoft/terminal/assets/576220/670fe7e7-334a-4fb8-8cd7-9f34963ee18c)

Any subsequent tabs opened show the same error.

**However**, if you open the `Settings` tab, subsequent tabs will open with the configured font.
This does not require any action to be taken inside the settings tab.

If the terminal app is closed and re-opened, the warning comes back.

At the same time this error started, opening "Powershell 7" as administrator no longer uses the Terminal app, but the old Windows Console instead.

Video of fault: https://youtu.be/W8RPSTKoh8Q

Custom font being used: https://github.com/i-e-b/Dave

**Comment by lhecker** [comment]
> Note: This is not the same as https://github.com/microsoft/terminal/issues/9375 , and the fix for that issue does not apply

For my understanding: You _did_ install the font for all users and, if you previously installed for your user only, you made sure to remove it from AppData again, right?

**Comment by i-e-b** [comment]
Hi.

Yes, the font is installed for all users. It is not installed in `AppData`, only in `C:\Windows\Fonts`.

I have also tried multiple reboots, and have run "Repair" for the Terminal app in Settings.

**Comment by lhecker** [comment]
Did you already try to remove the font and reinstall it? If not, I'd check both the old control panel

![image](https://github.com/microsoft/terminal/assets/2256941/b2e38b4c-222c-418f-b46e-28fcc8566b2c)

as well as the new one

![image](https://github.com/microsoft/terminal/assets/2256941/6ac7fa15-2526-49cb-a556-8b14182bf398)

If you already tried this, please let me know. 🙂

**Comment by i-e-b** [comment]
Hi.

So, the font was showing in the old control panel, but not in Settings->Personalisation->Fonts.

**Comment by lhecker** [comment]
> So, the font was showing in the old control panel, but not in Windows->Settings->Personalisation->Fonts.

I have encountered broken font caches before, but definitely not like that. Hopefully this isn't a common bug.

> The font is now loaded at the start up of Terminal, as expected.

I'm glad to hear that this fixed the problem! I'll close this issue for now and hope that this is just a rare bug in Windows. This is because...

> I guess there are multiple ways of enumerating the fonts, and something got damaged during the update? This would make sense if the start-up process was checking in a different way to the Terminal->Settings tab.

...your assumption is sort of correct. We have a number of problems with the font caching service on Windows and we're tracking the worst one in issue #3257: Per-user fonts simply don't work. That's internally tracked as MSFT:42103854. Font support is definitely more robust for unpackaged applications unfortunately.

**Comment by i-e-b** [comment]
This fault has re-occurred
![image](https://github.com/microsoft/terminal/assets/576220/11d14166-4360-41ac-b807-69bea25610ae)

Looks like it might be a bug in Windows -- I have made no font changes, but my chosen font was lost from the 'new style' Windows Settings, but was present in the 'old style' font.
