### ISSUE TITLE
Clicked URL contains unwanted delimiter

### ISSUE THREAD

**Issue by bobvandevijver** [microsoft/terminal#17430]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Other Software

My screenshot is a irssi inside a screen over SSH inside WSL Debian, but it happens in any environment.

### Steps to reproduce

Have a link wrapped with `<>` in your terminal, for example in bash:

```
echo "Some URL: <https://github.com>"
```

And click the link in the output.

### Expected Behavior

The parsed link should not include the `>` character. Angle brackets are a [common URL/IRI delimiter](https://datatracker.ietf.org/doc/html/rfc1738#page-3), which is [not allowed in IRIs](https://datatracker.ietf.org/doc/html/rfc3987#page-13).

### Actual Behavior

The opened link will include the `>` character, which can lead to interesting behaviour. The example above with Github leads me to an empty tab, the example from the screenshot below leads to a 404 (which isn't the case when the `>` is removed).

Also note that the `>` isn't actually underlined (which is good), but it is included in the mouseover and when clicked.

![image](https://github.com/microsoft/terminal/assets/1835343/66aa40b7-aa8e-442d-b946-82fce2210990)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to https://github.com/microsoft/terminal/issues/17323 for more discussion.

/dup #17323

**Comment by bobvandevijver** [comment]
A, didn't see that one as it was already closed. Thanks!
