### ISSUE TITLE
BUG: Error in TypeData "Microsoft.PowerShell.DeserializingTypeConverter": Cannot create an instance of the type converter for type Microsoft.PowerShell.DeserializingTypeConverter due to exception: The type initializer for 'Microsoft.PowerShell.DeserializingTypeConverter' threw an exception.. , and 3 another errors

### ISSUE THREAD

**Issue by BussyBakks** [microsoft/terminal#17447]
### Windows Terminal version

v1.21.1382.0

### Windows build number

10.0.26120.670

### Other Software

Oh-my-Posh 19.16.1 to customize the prompt
and powershell script
![image](https://github.com/microsoft/terminal/assets/108082159/1927b893-0758-4c59-8f7c-0649ec79b272)

### Steps to reproduce

open powershell. any permission

### Expected Behavior

open powershell window like normal

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/108082159/fe076ef1-ced8-489a-ac0d-5e713e82d0b7)
*maximized window is Powershell (PWSH) 7, another is an original powershell in my computer.*
Note: Powershell console in Powershell ISE still works

**Comment by lhecker** [comment]
Does PowerShell start successfully if you comment out the `oh-my-posh` line in your profile?

**Comment by BussyBakks** [comment]
> Does PowerShell start successfully if you comment out the `oh-my-posh` line in your profile?

@lhecker before i put oh-my-posh on $PROFILE to load with powershell, now i removed it and still have this error .-.

**Comment by BussyBakks** [comment]
ISSUE CLOSED: i fixed this bug, just restart .-.
maybe something that blocked powershell starts when back after hibernated .-.
`oh-my-posh` profile works too
![image](https://github.com/microsoft/terminal/assets/108082159/b54a1220-d109-448c-bcd6-1018d0cacabb)

**Comment by DHowett** [comment]
Thanks for following up! Congrats.

**Comment by BussyBakks** [comment]
> Thanks for following up! Congrats.

@DHowett this error caused by hibernation settings .-. after hibernating powershell not work again :)
