### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1744]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Start Windows Terminal,
Have the terminal on restore down,
Open a tab of Ubuntu 18.04 TLS,
Look for a file name in a certain directory that is being highlighted,
Then maximise the screen,
The highlighted part will stretch towards the end of the screen.

# Expected behavior

1. When maximised, the file name should NOT be highlighted till the end of the screen.
2. The highlighted part should stop at the end of file name.

# Actual behavior

Screenshot belows show what it looks like:
<img width="959" alt="bug-report" src="https://user-images.githubusercontent.com/50003738/60413563-fd4e9300-9c07-11e9-8688-83569a3fd226.PNG">

**Comment by DHowett-MSFT** [comment]
I think this is #294.
