### ISSUE TITLE
program length_of_line;
type
  point = record
    startX, startY : Real;
  end;

  line = record
    p1 : point;
    p2 : point;
  end;
var
  mPoint1, mPoint2 : point;
  mLine : line;

{Get length of line}
function getLength(L : line) : real;
var
  result : real;
begin
  Result := sqrt(Sqr(L.p1.startX + L.p2.startX) + Sqr(L.p1.startY + L.p2.startY));
  getLength := Result;
end;

begin
  mPoint1.startX := 1;
  mPoint1.startY := 2;
  mPoint2.startX := 3;
  mPoint2.startY := 5.2;

  mLine.p1 := mPoint1;
  mLine.p2 := mPoint2;

  WriteLn(getLength(mLine));

  readln;
end.


### ISSUE THREAD

**Issue by 47AD0** [microsoft/terminal#17448]
git

### actually enables `feature.manyFiles` 
- [ ] go to featured version 
  

[getting-started](accesses:category:ghpages://node.js)
_`features` Readme@AJPX in_    _[`415115814`](https://gpinas.com)_
  _[`zf-version-sampler`](https://ghpages.DOCS.AJPX/libgit/libgit1/libgitnew/oldlibgit/issues/6529/6530#keys-first-issuecomment-2052975956)_

### automatically with the version of git

- [ ] zoom_2fa v1. 0.1

- [ ] zoom_2fa v1. 0.2

- [ ] zoom_2fa v1. 0.3

|  Goatlib  |   deploy   |  Readme |
| ------------  | -------------- | -------------- |
| [🆎] ver  |  update | CODE |
| zf. v1
| zf. v1

| [`415115814`](https://lastlogin.rss/feed/ghpages) |
| ---- |
| _[`v1`](🆎://okhttps.wan.secured)_ |

### it was added, and have a specific reason to disable it.

_Originally posted by @mtalexan in https://github.com/libgit2/libgit2/issues/6531#issuecomment-2052975956_

**Comment by 47AD0** [comment]
§ how about your contribution §
¶[getting-started](help.gcash.com)¶

**Comment by lhecker** [comment]
?????
