### ISSUE TITLE
Multiple font style support

### ISSUE THREAD

**Issue by notreallyparanoid** [microsoft/terminal#17459]
# Description of the new feature/enhancement
![image](https://github.com/microsoft/terminal/assets/139852420/6f9bd6b0-a1dc-4bfe-b6a9-4a52834c9a37)

TUI editors like vim have support for alternate font highlighting using CSI SGR 10-20. Few terminal emulators in linux currently support this, and it would be great to have it in Windows Terminal because Windows really doesn't have many emulator options
## Sources, references and discussions: 
https://github.com/kovidgoyal/kitty/issues/6804
https://github.com/vim/vim/pull/13537

# Proposed technical implementation details (optional)
https://github.com/vim/vim/commit/a606f3ac036e5f3dc313f620e6b4bc00812314f9

**Comment by j4james** [comment]
This is already tracked in issue #6779. But thanks for the vim reference. It's helpful to know that there is actually someone making use of this functionality.

**Comment by notreallyparanoid** [comment]
While not having this feature integrated wouldn't be catastrophic, it would be slick to have some extras in terminal emulators, especially for people who use terminal editors. However, I don't foresee it coming to windows terminal anytime soon, as it may not be widely used by many people.

**Comment by DHowett** [comment]
Thanks for closing this out as a dupe! Feel free to subscribe or comment over on #6779 to help us prioritize!
