### ISSUE TITLE
Window title is not updated

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#17461]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.19045.4529

### Other Software

- startship shell prompt

### Steps to reproduce

- install [startship](https://starship.rs/guide/) shell prompt: `curl -sS https://starship.rs/install.sh | sh`
- enable it

### Expected Behavior

Current path should be displayed in the Windows Terminal's tab title.

### Actual Behavior

The window title doesn't show the path.

https://github.com/microsoft/terminal/assets/199648/13b22e30-7d54-4069-9630-0862fa413d44

**Comment by j4james** [comment]
@warpdesign I suspect this might be a configuration issue. The documentation for Startship implies that you need to set this up yourself. See here:

https://github.com/starship/starship/tree/e481b67f83e686f91523b2d7c6e3c7d73bfc2fad/docs/advanced-config#change-window-title
