### ISSUE TITLE
Use tab colors in the Ctrl-Tab switcher menu entry visuals 

### ISSUE THREAD

**Issue by contextfree** [microsoft/terminal#17465]
# Description of the new feature/enhancement

Somehow incorporating each tab's color into its Ctrl-Tab menu entry could allow faster recognition of tabs in this menu once you've internalized a color scheme, and also help reinforce the scheme so you can internalize it more readily. Plus for people who like to customize tab colors it could make Windows Terminal feel a tiny bit more pleasant to use by enhancing the sense of personalization.

I'm not sure exactly how it should look; highlighting each entire row with its tab color might be too visually loud, but a small indicator in each row would probably suffice. It can't just be the current tab indicator though, since that would prevent seeing all the tab colors and picking out the one you want at a glance.

# Proposed technical implementation details (optional)

I guess the Ctrl-Tab menu is a [`CommandPalette`](https://github.com/microsoft/terminal/blob/fa407332a5970164277919dc038f272c04628c9e/src/cascadia/TerminalApp/CommandPalette.cpp) in `CommandPaletteMode::TabSwitchMode` and its entries are [`TabPaletteItem`s.](https://github.com/microsoft/terminal/blob/fa407332a5970164277919dc038f272c04628c9e/src/cascadia/TerminalApp/TabPaletteItem.cpp), so they're presented through the [`TabItemTemplate`.](https://github.com/microsoft/terminal/blob/fa407332a5970164277919dc038f272c04628c9e/src/cascadia/TerminalApp/CommandPalette.xaml#L162) But I don't have any particular ideas on implementation unless I'm the one implementing it. I'd be up to try that if anyone's interested.

**Comment by PankajBhojwani** [comment]
Good catch! Thank you for submitting this

**Comment by nukoseer** [comment]
> I'm not sure exactly how it should look; highlighting each entire row with its tab color might be too visually loud, but a small indicator in each row would probably suffice. 

Maybe something like this? 

![resim](https://github.com/user-attachments/assets/480d984e-a56d-4ef2-88b4-64392c7c3e26)
