### ISSUE TITLE
wt: The term 'wt' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by Rusinas** [microsoft/terminal#17463]
### Steps to reproduce

Try to execute `wt` from the terminal 

### Expected Behavior

Opening another windows terminal

### Actual Behavior

Well, I don't know what happened, everything worked just fine yesterday and all of a sudden I started to get this error. Reinstallation didn't help, but I found that it is now being installed into the `Program Files` directory instead of `AppData/Local` and it creates inaccessible `WindowsApp` folder:
![image](https://github.com/microsoft/terminal/assets/42975143/51bd79d3-613b-4e47-8ea0-06fab300b81a)

I think that's the reason, but I don't know how to solve it, couldn't manage to gain the access to that folder

**Comment by lhecker** [comment]
Is the wt.exe alias still enabled for you? 
![image](https://github.com/microsoft/terminal/assets/2256941/c2b2a146-9285-4482-b396-c166c414be36)

**Comment by Rusinas** [comment]
@lhecker oh, yes, I forgot to mention that I toggled it back and forth too, didn't help 😭
![image](https://github.com/microsoft/terminal/assets/42975143/8474d5ba-9349-47be-93a9-befe975d17e3)

**Comment by Rusinas** [comment]
Now I manually opened `C:\Users\andre\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe` and found there `wt,exe` with 0 KB size which is weird.  
![image](https://github.com/microsoft/terminal/assets/42975143/d8e3af0e-06cb-4450-abed-d5831b03a6e4)

Unfortunately, I can't remove or replace it for some reason:
![image](https://github.com/microsoft/terminal/assets/42975143/537c0191-2cb6-4d28-a366-2ab4f95041de)

I also tried to add `C:\Program Files\WindowsApps` to the `Path`, as well as `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11381.0_x64__8wekyb3d8bbwe` specifically, nothing of this worked, even though there is valid `wt.exe` in that folder

**Comment by zadjii-msft** [comment]
I just want to quick jump in and say: Don't mess with the permissions on `C:\Program Files\WindowsApps`. That can _permanently_ mess up the OS install. 

The 0-byte `wt.exe` is something called an "App Execution Alias". It's basically a link to the one that lives in `C:\Program Files\WindowsApps`. The OS is supposed to have built-in special casing for those such that when they try to launch the thing from `C:\Program Files\WindowsApps` and fail, the OS will instead boot the thing from `C:\Program Files\WindowsApps` with the correct package identity. 

Do any other app execution aliases work for you/?

**Comment by Rusinas** [comment]
@zadjii-msft yeah, I just was desperate. Resintalled windows, now everything is fine 😂

**Comment by Fred-Vatin** [comment]
Adding `%LocalAppData%\Microsoft\WindowsApps` to the user path did the trick.
