### ISSUE TITLE
Feature Request: Background should stay transparent/acrylic when window is not focused

### ISSUE THREAD

**Issue by dasMulli** [microsoft/terminal#1747]
Steps to Reproduce:

* Open Terminal+cmd
* Adjust transparency via mouse scroll to let your beautiful desktop background shine through 🤩✨.
* Move focus to another window (e.g. other monitor).
* Background is now pitch black and user is very sad 😢 

Dunno if this is a feature/bug/dupe. (could only find the MEGA thread)

**Comment by DHowett-MSFT** [comment]
We can't do this, unfortunately! System policy dictates that acrylic is only allowed on the actively focused window. Once the terminal loses focus, the system takes acrylic away from us. ☹️
