### ISSUE TITLE
wt does not give terminal focus if batch scripting is running

### ISSUE THREAD

**Issue by michaelmesser** [microsoft/terminal#17484]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.3737

### Steps to reproduce

1. Close all Windows terminal windows
2. Make `test.cmd` with the contents `pause`
3. Open `test.cmd` with Windows terminal
4. Change focus to a different application like Edge
5. Press the Windows key and `r`, then type `wt`
6. Moving the mouse back to the edge window may contribute to reproducing this

### Expected Behavior

The new terminal window is on top and has focus.

The expected behavior happens if you skip step 3.

### Actual Behavior

Sometimes the new terminal window is behind and does not have focus. The terminal icon in the dock is red.

**Comment by carlos-zamora** [comment]
Possibly related: #15763

**Comment by carlos-zamora** [comment]
We're going to mark this as a /dup of #15763, but we copied over the contents to that thread since you gave us a nice repro. Thanks 😊
