### ISSUE TITLE
Windows (probably conhost) sometimes gets stuck.

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#17487]
For a lack of a better description, look at this screenshot: 
![image](https://github.com/microsoft/terminal/assets/170285982/9e726eb8-0fac-46ec-8bd7-4e63a3b8def5)

Sometimes, after an out of memory semi-crash, cmd windows remain in this state. If I click on them, nothing happens. (some of them work and open, but others stay in this state) The program run from these windows are still running. It's like the "host" of the window crashed. Obviously if I close them, they close and kill their spawned programs. I wish there was a way to resume them.

Addendum: This happebned to me already a few times in the past. It's like some reference or "father" process is dead and the windows associated with it are unresponsive (as windows, but the processes running inside them are still alive) Also some wsl "bash" windows are affected but no other windows are affected.. so I think it must be some "shell host" or similar process associated with those windows. But I don't know more than that. From past experience I know that if I kill them one by one, every new window (command prompt or bash) work without problems.

I am curious if there is any way to regain control of those windows.

Another example: 
![image](https://github.com/microsoft/terminal/assets/170285982/6b2c093f-dc2e-454c-af2f-f53b1d529a83)

The two windows on the left are responsive, but the 3 on the right are not. They don't pop up when clicking on them or using alt+tab or task manager.

I am 99% positive that the problem relies in CONHOST.

**Comment by carlos-zamora** [comment]
Thanks for filing! Could you create a dump file using Task Manager for one of these? Also, what version of windows are you on/?

**Comment by 0wwafa** [comment]
> Thanks for filing! Could you create a dump file using Task Manager for one of these? Also, what version of windows are you on/?

hmm I don't have them anymore and it does not happen always... very rarely when memory is full.

About the version, this is something that happened to me in the last years so it affects all versions of windows up until now.
At the moment I am running: Microsoft Windows [Version 10.0.19045.4529]

**Comment by carlos-zamora** [comment]
Ok, we're going to close this then. But if you hit this again, please capture a dump and we'll be happy to reopen it. 😊
