### ISSUE TITLE
Please add time stamps.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/terminal#17491]
# **Description of the new feature/enhancement**

I want time stamps in the terminal for every command (although some would prefer for every line number, potentially).

I envision it like https://gitlab.com/gitlab-org/gitlab/-/blob/72e14aa6bb97c6e10870812ac9b521d41b8f890b/doc/ci/yaml/ci_job_log_timestamps.md#example-configuration-and-output depicts:

<blockQuote>

## Example configuration and output

**Example pipeline configuration with `FF_TIMESTAMPS` enabled:**

```yaml
variables:
  FF_TIMESTAMPS: true
```

**Example log output with `FF_TIMESTAMPS` enabled:**

![Timestamps for each log line](https://gitlab.com/gitlab-org/gitlab/-/raw/master/doc/ci/yaml/img/ci_log_timestamp.png)

</blockQuote>

...which happens to depict how this feature would work well with https://github.com/microsoft/terminal/issues/17490#issue-2382168026.

# **Proposed technical implementation details (optional)**

https://gitlab.com/gitlab-org/gitlab/-/issues/463391 contains most of the useful discussions regarding implementation.

**Comment by RokeJulianLockhart** [comment]
This *might* be a duplicate of https://github.com/microsoft/terminal/issues/9331#issue-819782127, in retrospect, although I think I've phrased it better *if so*.

**Comment by carlos-zamora** [comment]
Thanks for filing! Marking this as a /dup of #9331.
