### ISSUE TITLE
Awesome! But can't change color schemes

### ISSUE THREAD

**Issue by freakyy85** [microsoft/terminal#1749]
In the config file there are some color schemes defined. I can't seem to find a way to specify which one to use. Maybe you could make this more obvious.

**Comment by cinnamon-msft** [comment]
There's a `colorScheme` property for profiles in the profiles.json file. Documentation can be found here: [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)
