### ISSUE TITLE
Request: color scheme browser 

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#1750]
Discussed a little bit in other threads, but I thought I'd add an issue as [all iTerm2 color schemes have been ported to Windows Terminal](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/windowsterminal).

# Summary of the new feature/enhancement

Add a color scheme browser. 

 - User hits Settings - Themes, and types 'Monokai Soda'
 - User sees a preview on the color scheme (dynamically fetched from an online source)
 - They click apply, 

# Benefits 

This means:

 - Windows Terminal isn't limited to a small amount of inbuilt color scheme
 - Users don't have to use or know about `colortool` 
 - Users who want to use a well known theme can just type the color scheme's name and use the colopr scheme

**Comment by DHowett-MSFT** [comment]
Probably in the future, but we should just talk about it as part of #1564 and #555 (plugin market, etc.)

**Comment by mikemaccana** [comment]
Sure will move there 👍
