### ISSUE TITLE
Alt code

### ISSUE THREAD

**Issue by inoperable** [microsoft/terminal#17517]
```
   ╔═════╗
   ║ Duh ║
o.O╜═════╝
```
Say I want to input something really fancy, say, √² or arcane stuff like https://brltty.app/details.html? Ctrl+Shift+U? Windows. Duh. Basically you gutted a not-so-common feature that has its own domain-name for the not-so-common-users and let user do alternatively what exactly? Maybe I need AI Prompt ;) 

# Proposed technical implementation details (optional)

**Comment by inoperable** [comment]
Alt + Code

**Comment by DHowett** [comment]
I know you have already found the other issue for Alt Numpad input. Please keep all relevant conversation over there.

> Basically you gutted a not-so-common feature that has its own domain-name for the not-so-common-users and let user do alternatively what exactly?

It’s a bug. If we didn’t care to fix it, we would not have left the other issue tracking it open.
