### ISSUE TITLE
Add an option to back up and restore Terminal settings

### ISSUE THREAD

**Issue by CompactProducer** [microsoft/terminal#17513]
# Description of the new feature/enhancement

It would be ideal to back up Terminal settings to a different folder (for example, C:\Users\username\OneDrive\Documents\Terminal). Every time that we want to back up Terminal settings, we have to navigate to the folder like %LocalAppData%\packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState and copy and paste the settings.json file to another folder. Also, every time that we want to restore Terminal settings, we have to navigate the settings.json file to a folder and copy and paste it to %LocalAppData%\packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState.

# Proposed technical implementation details (optional)

Add Backup and Restore buttons in the Terminal settings.

**Comment by carlos-zamora** [comment]
Thanks for filing! Marking this as a /dup of #2933. I copied over your post to https://github.com/microsoft/terminal/issues/2933#issuecomment-2207424906 too for easier tracking 😊
