### ISSUE TITLE
Add support for configuring Font Weight

### ISSUE THREAD

**Issue by EricWXY** [microsoft/terminal#1751]
# Summary of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This is not a discussion forum! Please make sure your issue reports and feature requests have information inside them.

Anyway, I am turning this into the "font weight" task.

**Comment by Jonjoe** [comment]
This would be super cool :+1:

**Comment by mdtauk** [comment]
If font weight is set to bold, text that is outputted that is meant to stand out in Bold, won't.

So if this is added, there needs to be some consideration as to how you emphasise text.  The same goes for Italic text.

**Comment by CXuesong** [comment]
Can terminal just support specifying font-weight for normal and emphasized text separately? I have a font-family that supports *light* font-weight, but the terminal won't let me to use it.
![image](https://user-images.githubusercontent.com/11611687/63645857-70244800-c739-11e9-9b73-8be205e7133d.png)

**Comment by danieldjewell** [comment]
#610 seems to be related... I'll make more detailed comments there, but FWIW, Terminal seems completely naïve regarding even the mere _existence_ of font styling

**Comment by Lombra** [comment]
Sort of a hypothetical issue, but I've noticed that console renders bold fonts differently than most other applications. When I use Consolas size 16 in console, it seems to be the equivalent of size 11 in other applications (terminal included), but the bold version looks very different. The terminal font is much bolder than the console one. I don't know what's going on here, but I would love it if it were possible to get the appearance from console once we get this option in terminal.

**Comment by DHowett-MSFT** [comment]
So, some of that might actually be that the _traditional console_ measures fonts in pixels, not points. 16px at a normal DPI is equivalent to 12pt, so it’s not surprising that you’ve found it to be close to that.

**Comment by Lombra** [comment]
Yes, I've understood that console measures in pixels. I'm fine with using "points", but I'm more concerned about the appearance of the bold font in other applications that use the points scale. I don't know whether it would be possible (or desirable) to have a non binary font weight setting in the terminal, if that would even help achieve the console appearance.
