### ISSUE TITLE
Terminal window jittering when resizing

### ISSUE THREAD

**Issue by Julian-C-Shinn** [microsoft/terminal#17538]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045.4598

### Steps to reproduce

I've noticed that the Terminal window jitters when I resize it, but only when I'm in console mode. The window doesn't jitter when I'm on the settings page.

### Expected Behavior

When resizing the terminal window, the window should smoothly and seamlessly adjust to the new dimensions without any jittering, flickering, or instability. The overall experience should be fluid and responsive, allowing the user to easily resize the window to their desired size without encountering any visual or performance issues.

Like in old PowerShell or Cmd, as seen in the video below:

https://github.com/microsoft/terminal/assets/174054659/df1c74b1-78ce-4d0d-a63b-7a82752fa926

### Actual Behavior

Terminal window jitters when I resize it in console mode (the video below shows it in PowerShell, but it also happens in other modes such as Cmd):

https://github.com/microsoft/terminal/assets/174054659/b6bb8837-d8ac-428a-a7e2-6d4242f320c0

However, when I'm on the settings page, the resizing is smooth:

https://github.com/microsoft/terminal/assets/174054659/674a42fa-c04a-4b15-84c6-ba22772786a1

**Comment by DHowett** [comment]
Thanks for filing!

The terminal window resizes character-by-character, so that it is always a perfect multiple of the character size.

You can turn that feature off here:



![Image](https://github.com/user-attachments/assets/2bf50633-63e7-425c-a2e1-ab1a1320fdfd)
