### ISSUE TITLE
Windows Terminal prevents you from switching the layout

### ISSUE THREAD

**Issue by magicxor** [microsoft/terminal#17532]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Other Software

PowerShell 7.4.3

### Steps to reproduce

Launch Windows Terminal and try to switch the keyboard layout by pressing alt+shift. (Workaround: switch the keyboard layout using a mouse)

### Expected Behavior

The keyboard layout is changed

### Actual Behavior

Windows Terminal switches the keyboard layout back to its original value

https://github.com/microsoft/terminal/assets/8275793/8b89cde9-90a3-4b3b-8288-bcf6c7cf8fff

**Comment by zadjii-msft** [comment]
Can you try [Windows Terminal Preview v1.21.1772.0](https://github.com/microsoft/terminal/releases/tag/v1.21.1772.0)/? I believe a bunch of IME issues were sorted out in the last release of the Terminal

**Comment by magicxor** [comment]
@zadjii-msft thank you, the issue seems to be fixed in v1.21.1772.0. I can't reproduce it anymore.
