### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by GitUniversities** [microsoft/terminal#17546]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Executing confusing commands in the terminal and the commands are rather long, taking about two or three hours to execute, printing one line per minute, and I execute them successfully in cmd powershell non-wt.exe

wt.exe back to exit and close all windows, including those that did not execute the command. 

### Actual Behavior

system event
```
Faulting application name: WindowsTerminal.exe, version: 1.20.2406.26001, time stamp: 0x667c7d41
Faulting module name: TerminalApp.dll, version: 1.20.2406.26001, time stamp: 0x667c7cd3
Exception code: 0xc0000005
Fault offset: 0x000000000003a29c
Faulting process id: 0x3ad0
Faulting application start time: 0x01dad3382b8f0d45
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11781.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11781.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: 7a7acd2b-a145-4a1f-b0a5-eed2714be0eb
Faulting package full name: Microsoft.WindowsTerminal_1.20.11781.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by carlos-zamora** [comment]
Thanks for filing. What commands are you running /?
