### ISSUE TITLE
Entered text can get overwritten while typing when wrapped

### ISSUE THREAD

**Issue by alrz** [microsoft/terminal#17542]
### Windows Terminal version

 1.21.1772.0

### Windows build number

10.0.19045.0

### Other Software

oh-my-posh

### Steps to reproduce

- Type some text until it gets wrapped (resize for a quicker repro)
- Or past a long command and start editing it in the middle

### Expected Behavior

Text should re-wrapped while editing

### Actual Behavior

Sometimes the caret stays on the previously entered text, causing overwrite.

Note: apparently this doesn't affect the committed text when hitting enter so it's different from what is rendered.

**Comment by zadjii-msft** [comment]
Are you using an IME to input text/?

**Comment by carlos-zamora** [comment]
Thanks for following up! Since it's an issue with Git bash we'll close this. Thanks!
