### ISSUE TITLE
Find dialog continually returns focus to found element after clicking out of the dialog

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#17549]
# Description of the new feature/enhancement

Find dialog returns focus even when not 'active', leading to poor UX/ergonomic

# Proposed technical implementation details (optional)

* Start a terminal and dump a load of text to the terminal.
* ctrl+shift+f (or whatever) to find some unique piece of data in the terminal scrollback and rejoice when the terminal shows you the line (it would be swell if the find window didn't obscure your text though). example: 
![image](https://github.com/microsoft/terminal/assets/46322585/45d60e41-47b5-458d-a078-ac372514a36a)
* click in the terminal pane to enter a command (do not close the find dialog), expecting for the scrollback to be returned to the bottom
* start typing your command and notice that the scrollback is returned to the position of the current 'find' (which imo is unexpected)
* out of frustration, hit the `esc` key, expecting the find dialog to close (be frustrated when it doesn't)
* press ctrl+shift+f again to enter find dialog, **then** press `esc` and start typing and be happy to see the scrollback/focus returned to the bottom

I tried to find a matching issue but didn't find one.

#### demonstration below
![terminal](https://github.com/microsoft/terminal/assets/46322585/46607da9-c762-4cb4-9754-2791562739b9)

**Comment by DHowett** [comment]
Thanks for the report! I'm looking at our all-up backlog and I think it's a /dup of #17301.
