### ISSUE TITLE
command palette doesnt open at all

### ISSUE THREAD

**Issue by aaaaaaaaahhhhh** [microsoft/terminal#17541]
### Windows Terminal version

Unsure, cannot check

### Windows build number

Unsure, cannot check

### Other Software

Visual Studio, Visual Studio Code

### Steps to reproduce

Press Crtl+Shift+P. Be in any app, including powershell, cmd or visual studio code, it will not open and nothing will happen.

### Expected Behavior

The command palette should open.

### Actual Behavior

Absolutely nothing happens.

**Comment by DHowett** [comment]
Can you share a screenshot of all the apps you are trying it on?

If you are using Windows Terminal, you should also have a “+v” menu at the top in the titlebar. That will let you get to the “About” dialog with the version in it.

You can check your Windows version in System Settings. We don’t have any control over that, so I am not sure why you would be unable to check.

We do not do any work on VSCode on this team, so if you are having trouble with their command palette as well you will want to file an issue on their repository.

**Comment by aaaaaaaaahhhhh** [comment]
<img width="960" alt="Capture1234" src="https://github.com/microsoft/terminal/assets/63686431/4ead6974-f97f-4c48-8e9f-dab09c5cce02">

Here's what my Windows Terminal looks like. Also, my Windows build number is 22H2 and the Windows Terminal version is 1.20.11781.0.

**Comment by zadjii-msft** [comment]
Does opening the Command Palette from that new tab dropdown button work/?
![image](https://github.com/microsoft/terminal/assets/18356694/467b5f08-d21b-452f-92ba-22cba856fb1c)

I suspect that there's some other application that's installed a global keyboard shortcut for <kbd>ctrl+shift+p</kbd>, which is why it seems like the command palettes in totally unrelated apps aren't working.

**Comment by aaaaaaaaahhhhh** [comment]
Dammit, I can't believe I didn't see that. I'm sorry I didn't see that but thank you for helping me. This matter can be considered resolved.
