### ISSUE TITLE
Reports that terminal cannot find powershell for one reason or another?

### ISSUE THREAD

**Issue by calvinwonghk** [microsoft/terminal#1754]
# Environment
Windows 10, with Powershell Core 6

Windows 10.0.18922.1000

# Steps to reproduce
1. Open Windows Terminal
2. Only windows powershell (older version that come with windows), but can't find Powershell Core 6/7

# Expected behavior
Expected the Powershell Core 6 to be there.

# Actual behavior
Powershell Core 6 is missing from there.

**Comment by zadjii-msft** [comment]
@calvinwonghk Where is `pwsh.exe` installed for you? Is it on your`%PATH%`?

We may need to update our search paths for a new version.

(PS: Please add a descriptive title when filing an issue. "Bug Report" with nothing else is likely to get closed without a second look)
