### ISSUE TITLE
Backspace in wrapped cooked read erases char on line above

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#17554]
### Windows Terminal version

Commit ac5b4f5831c125e7defe65eab93d3928b282559f

### Windows build number

10.0.19045.4529

### Steps to reproduce

1. Checkout the latest code from main (ac5b4f5831c125e7defe65eab93d3928b282559f or later).
2. Start a cmd shell in OpenConsole.
3. Type some content at the prompt until it wraps onto the second line.
4. Backspace until the cursor is at the start of that second line.

### Expected Behavior

Backspaces on the second line should have no effect on the characters in the first line.

### Actual Behavior

The last character on the first line gets erased when backspacing over the first character in the second line.

This is what it looks like after wrapping.
![image](https://github.com/user-attachments/assets/c31b06fa-52c1-4a74-b4ab-7eda11111eae)

And this is what it looks like after two backspaces. Notice the `r` erased from the first line.
![image](https://github.com/user-attachments/assets/e6e440b0-0460-452e-92f0-cc14cadce133)

The same thing occurs in both OpenConsole and Windows Terminal. I think this was introduced by the new VT cooked read implementation (PR #17445).

**Comment by j4james** [comment]
I should note that this is just a visual glitch. The actual prompt content is correct. It just looks like a character is missing.

**Comment by lhecker** [comment]
I found two more bugs:
* Writing a wide glyph into the last column breaks the cursor position
* Having a fairly full prompt (e.g. 80% of the viewport height) and pressing F7 with a rather full history will move the prompt contents upwards. But when dismissing F7 via ESC it'll not restore the prompt to its previous state.
