### ISSUE TITLE
command line option to launch new windows in zen mode

### ISSUE THREAD

**Issue by RalfReddings** [microsoft/terminal#17558]
Please provide a command line option to launch new windows in  [Focus mode](https://learn.microsoft.com/en-us/windows/terminal/tips-and-tricks#focus-mode).

As well as the ability to specify it per profile in the profiles settings but short of that, then a command line switch/option to use with wt.exe please!

Currently every time I launch a window, straight after, I have to use a long keyboard shortcut/command pallete to go into focus mode, which is not ideal.

 The[Focus mode](https://learn.microsoft.com/en-us/windows/terminal/tips-and-tricks#focus-mode) section of the "Windows Terminal tips and tricks" article, explains that its possible to get windows terminal to force every new window into focus mode:
>To set focus mode to launch every time you start Windows Terminal, open the Settings (Ctrl + ,) and select the Startup tab. Under Launch mode, select Focus (or Maximized focus, which is focus mode with your terminal window maximized). Select Save before exiting. The next time you launch the Windows Terminal, it will open up in focus mode

But going into the settings panel, I dont see this option at all:
![500](https://i.imgur.com/VrQdYzH.png)

I am on 1.19.-preview

**Comment by DHowett** [comment]
Thanks for pointing this out! It’s in “launch parameters” at the bottom.

**Comment by zadjii-msft** [comment]
Pretty sure you can already 

```
wt --focus
```

To launch into focus mode. IIRC I think that only applies to new windows (`wt -w 0 --focus` won't change the current window into focus mode)

https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#options-and-commands
