### ISSUE TITLE
Search resets current position while new results arrive

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#17551]
Originally posted by @OAguinagalde here: https://github.com/microsoft/terminal/commit/32fbb16d43ddfcdd039a61c5af051a16b972faeb:

---

On version `1.21.1772.0`, whenever using some log reading tool such as logcat or similar, I still get the scroll being triggered on many situations that I wouldn't expect it to:

Situation: logcat or whatever constantly outputs stuff to the terminal. I search for something on the terminal.
* Whenever a new occurrence of my search is output, it automatically jumps to the new one. I'd expect that if I'm on occurrence 10/10, and 2 new occurrences appear, my scrolls would be wherever I originally had it and the active search would stay at 10/12. Instead of that, the active search is automatically set to the latest one (12/12) and it jumps there.
* Also, If I try to "follow" the log output as it is printed to the terminal, as soon as the active search result is out of the screen, it jumps back to it, even if there is no new occurrences of the search, so I'm forced to cancel the search (meaning that I lose the highlighting) to be able to follow the logs being printed.

Is this commit supposed to fix those situations? I'm unsure whether I got my versions wrong or whether these situations where not taken into account when working on it.

---

https://github.com/microsoft/terminal/assets/2256941/e840403a-e418-4600-8d10-a2b4cbcd084e

**Comment by DHowett** [comment]
We should fix this at the same time as /dup #17301
