### ISSUE TITLE
Add an option to see "widthxheight" while resizing a window

### ISSUE THREAD

**Issue by CompactProducer** [microsoft/terminal#17560]
# Description of the new feature/enhancement

We want to see how the "widthxheight" appears while we resize a Terminal window. For example, if we resized a Terminal window, the box in the center would say "120x43"; if we resized it again, the same thing would say "80x50".

# Proposed technical implementation details (optional)

Add "Show column and row size when resizing a Terminal window" in Terminal Settings->Appearance.

**Comment by lhecker** [comment]
This sounds exactly like #2833. I'll close this in favor of the other issue. Please consider giving the other one a 👍.

/dup #2833
