### ISSUE TITLE
Sporadic cannot ctrl+D to or enter to close the terminal 

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#17578]
### Windows Terminal version

Version: 1.21.1772.0

### Windows build number

Microsoft Windows [Version 10.0.22631.3880]

### Other Software

N/A

### Steps to reproduce

No idea how to reproduce. Sometimes, after a long time open and running I notice the "track my mouse" feature stops working between panes and then when i exit the terminal it ends up printing:
```
[process exited with code 130 (0x00000082)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

but ctrl+d or enter don't exit the pane:
![terminal-pane-example](https://github.com/user-attachments/assets/7b66b6b6-39a4-4ad6-8de0-e95adf8bfb50)

### Expected Behavior

I want the "track my mouse" feature to keep working and if i have to close the terminal, i expect the pane to actually close.

### Actual Behavior

mouse tracking fails and ctrl+d/enter won't actually close the pane. the whole terminal window needs to be relaunched.

**Comment by dovholuknf** [comment]
I can't reproduce it on demand but it keeps happening. i did however go back to the released Version: 1.20.11781.0 and this is not a problem. I've moved away from the 'preview' for now because of this issue.

It might have to do with mouse tracking. Another example of how the mouse tracking seems to have failed and when i exit the terminal i get the Ctrl+D message

![track](https://github.com/user-attachments/assets/1643cc27-3c36-4b63-9d89-9e0a449599c7)

**Comment by dovholuknf** [comment]
CTRL-D doesn't close the window either on the preview version. I can confirm that the 'stable' terminal `1.20.11781.0` properly responds to CTRL-D and closes the pane

**Comment by vefatica** [comment]
I can repro (every time) like this.

Start WT normally (one tab, normal window).
Go full-screen (F11).
Split vertical (Alt+Shift++)
"exit" the shell on the right (this is OK)
"exit" the remaining shell (error occurs)

Note that exiting the lefthand shell then the other one does not cause the error.

Ditto for Split Horizontal with "bottom" replacing "right" and the analogous note about which is exitted first.

**Comment by vefatica** [comment]
It happens in WindowsTerminal 1.21.2406.25002 (preview) and not in WindowsTerminal 1.20.2406.26001.

**Comment by lhecker** [comment]
When I said "closed" I was referring to an internal function called "Close" that removes some event handlers from the "content" of a pane. This is what causes Ctrl-D and Enter to seemingly not work.
