### ISSUE TITLE
Install without Windows Store

### ISSUE THREAD

**Issue by mrchief** [microsoft/terminal#1757]
# Summary of the new feature/enhancement

Windows Store is broken and a hot mess. Often times it doesn't work, doesn't sync with your account, doesn't find your devices and even if it does, cannot install to it. 

If Windows store is the only option, then a good chunk (and I wouldn't be surprised if it's the larger chunk) of devs/folks around the world simply cannot get to it.

I've been dealing with store issues for the past week and frankly, if it's _**this hard**_ to try something, I might as well live with `Cmder` or `Cmd`. It's simply not worth the time and effort to sort out Windows store to get a simple utility.

![image](https://user-images.githubusercontent.com/781818/60444313-f402fd80-9bea-11e9-9843-a8d9cc8d0d84.png)

# Proposed technical implementation details (optional)

Publish the setup exe/msi independent of Windows store.

**Comment by DHowett-MSFT** [comment]
Go forth, be sarcastic about the store in issue #1386 :smile:
