### ISSUE TITLE
typeahead no longer works - commands entered while other commands processing in shell are not received

### ISSUE THREAD

**Issue by ajkessel** [microsoft/terminal#17587]
### Windows Terminal version

 1.21.240625002-preview

(also other recent builds)

### Windows build number

10 22H2 (19045.4598)

### Other Software

Ubuntu Lunar
bash

### Steps to reproduce

Historically, when I entered commands while other commands were processing, they would get queued up at the next command prompt. This no longer appears to work. I don't think it's specific to the shell since I'm getting the same behavior in WSL/Ubuntu and cygwin.

Screen recording below.

https://github.com/user-attachments/assets/f5fe027f-fc55-495d-86fb-c4e315796b41

### Expected Behavior

Commands typed while shell is processing should be processed next

### Actual Behavior

Nothing

**Comment by carlos-zamora** [comment]
Thanks for filing. Does this reproduce in the stable channel (version 1.20)?

**Comment by ajkessel** [comment]
Oddly enough, the problem no longer occurs. I am still on the same version of Terminal (1.21.240625002-preview) and same version of Windows. I can't think of what could possibly have changed on my system that would make this problem, which I've seen for a few weeks, suddenly disappear. I do regularly do Windows and Office 365 updates, but it would be strange for those to impact this behavior of Terminal. Anything you can think of that I should check to track this down?

**Comment by carlos-zamora** [comment]
Cool. Unforunately, no ideas on our end. We'll close it then, but if more people report this we'll be happy to reopen it later. Thanks!
