### ISSUE TITLE
Consider allowing transparent background

### ISSUE THREAD

**Issue by djk2004** [microsoft/terminal#1758]
The legacy console can set the background to be transparent, so that windows behind the console can be visible through the console.  Sometimes this has a nice visual effect when the transparency and background colors are set to compliment this feature (ex: a very dark and barely transparent console will heavily obscure the windows in the background, but the point isn't to be able to see the background windows, its just to make a visual effect).  
![example](https://user-images.githubusercontent.com/37919951/60446607-5b1eb300-9be7-11e9-94e1-266877214425.PNG)

**Comment by DHowett-MSFT** [comment]
#603
