### ISSUE TITLE
Ability to tell taskbar to take all tabs from all windows terminal windows that are open and list all tabs in 1 list

### ISSUE THREAD

**Issue by finjulhich** [microsoft/terminal#17588]
# Description of the new feature/enhancement

The windows taskbar shows icons. In the summary mode, clicking on the icon lists all the windows open for that application.
The question/feature suggestion is , when multiple terminal windows are open, each with their own list of tabs, to have the ability to get  1 Terminal icon in the taskbar, and that clicking on that icon shows all the tabs titles together from all the windows.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
IIRC we don't really have that kind of control over our taskbar entries. I believe this is basically the default behavior of Windows 11 (all the windows for an app are glommed into a single icon on the taskbar).

There's also #687 for "I want to see open tabs in the taskbar"

We _do_ already have support for a "tray icon" / "notification area icon"
![image](https://github.com/user-attachments/assets/f53c97ec-0386-4f11-98ba-f97c2edfb3ad)
(with plans to show tab titles there too #10448). I suspect that might be the best solution for you /?
