### ISSUE TITLE
By default, start in the home folder when opening a linux shell

### ISSUE THREAD

**Issue by djk2004** [microsoft/terminal#1759]
# Summary of the new feature/enhancement
When opening a new Linux shell, the starting folder is /mnt/c/WINDOWS/system32.  Instead, use the current user's home folder.  This would match the current behavior with the legacy console. 
Generally, most users would not want to work in the system32 folder.  However, starting from the home folder would be expected behavior.

# Proposed technical implementation details (optional)
Simply change the default starting path to the user's home folder.  This could either be the Windows user's home folder, or the Linux shell home folder at _/home/<user>_.  Alternatively, the profile configuration could also include a property that lets the user set the starting folder per profile.

**Comment by Kirlac** [comment]
#592 discusses the configurability of this

There is also a workaround in the comments for that issue - adding `~` to your wsl `commandline` setting will start in your linux home dir: https://github.com/microsoft/terminal/issues/592#issuecomment-504947429

I agree it would make sense for `profiles.json` to include this for WSL by default

**Comment by DHowett-MSFT** [comment]
Honestly, this should just be a dupe _of_ 592.
