### ISSUE TITLE
Two problems with documentation to do with prompts: 1) Oh My Posh might be overkill; 2) the instructions for installing Oh My Posh

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [microsoft/terminal#17591]
1) It would be good were [this (overly?) long page](https://learn.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup) to disclose _how one simply gives a colour to the prompt_ (and differentially to its various elements, if that is possible without a plugin), as against going the whole way with the 'Oh My Posh' plugin. The page does include a link to [a page that treats the PowerShell Prompt](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.4) and which, sort of, treats how to change the colour of that prompt. But what is wanted is an easy way for Windows Terminal users to find a reasonably thorough guide to changing the prompt's colour. For, setting that colour is fairly basic stuff, and yet users new to Windows terminal will not know how to do it.

2) (a) The aforementioned webpage about 'Oh My Posh' gives a command for installing that program and then a few lines later says, in effect: 'hey! Don't use _that_ installation command - use this one (the Windows Store one) instead'! I ended up aborting the first command and then running the second. (b) That same webpage recommends the command `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\paradox.omp.json" | Invoke-Expression`, which _throws a warning_ (albeit perhaps from my linter). The warning is: `Invoke-Expression is used. Please remove Invoke-Expression from script and find other options instead.'

**Comment by zadjii-msft** [comment]
Thanks for the feedback! I moved this over to our docs repo: https://github.com/MicrosoftDocs/terminal/issues/787
