### ISSUE TITLE
Windows Terminal Translation

### ISSUE THREAD

**Issue by vxiiduu1** [microsoft/terminal#17600]
# Description

More easier way to translate Windows Terminal into more languages

# A clear and concise description of what the problem is that the new feature would solve.
Describe why and how a user would use this new functionality (if applicable).

Currently there is no easy method to translate terminal.

# A clear and concise description of what you want to happen.

Easier way to help with translating terminal.

**Comment by lhecker** [comment]
Thank you for your question. Unfortunately, the translation is currently an internal process that we don't have much control over. As such we don't support community translations at the moment. You can read #15288 for more details.

/dup #10667

**Comment by vxiiduu1** [comment]
This made me depreesed.

> Thank you for your question. Unfortunately, the translation is currently an internal process that we don't have much control over. As such we don't support community translations at the moment. You can read #15288 for more details.
> 
> /dup #10667

**Comment by lhecker** [comment]
Yes, it's not something we like either, but we currently lack the time and resources to change this. You can subscribe to #10667 to be notified when this changes.
