### ISSUE TITLE
Bug Report - Trojan in conhost.exe compiled from SOURCE

### ISSUE THREAD

**Issue by xpwn3rx** [microsoft/terminal#1760]
# Environment

```none
Windows build number: [run "ver" at a command prompt] Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): Thursday 6/27 build from SOURCE

Any other software?
```

# Steps to reproduce

Compiled Thursday build from source.

# Expected behavior

Working terminal.

# Actual behavior

Get a popup about severe trojan from conhost.exe which was compiled from source.

![image](https://user-images.githubusercontent.com/19785522/60451388-c749e880-9be0-11e9-8bd1-2b3417a06774.png)

**Comment by JushBJJ** [comment]
Possible false positive.

**Comment by xpwn3rx** [comment]
Likely, but it's either a bug or something that really needs to be addressed.

**Comment by DHowett-MSFT** [comment]
This is literally the code for the console host executable that ships inside Windows. If your antivirus solution is tripping up on it, it is very likely that the bug is in your antivirus solution. If that happens to be Windows Defender, we can at least work with them to figure out why there’s a false positive.

**Comment by xpwn3rx** [comment]
> This is literally the code for the console host executable that ships inside Windows. If your antivirus solution is tripping up on it, it is very likely that the bug is in your antivirus solution. If that happens to be Windows Defender, we can at least work with them to figure out why there’s a false positive.

That was from Windows Defender. The Defender trip also caused a follow up ticket from our Crowdstrike AV system.
