### ISSUE TITLE
"duplicate tab" fails due to improper path being sent.

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#17602]
### Windows Terminal version

1.20.11781.0

### Windows build number

Microsoft Windows [Version 10.0.26100.1150]

### Other Software

Git bash
Oh-My-Posh

### Steps to reproduce

1. Open up a git bash window
2. <kbd>ctrl-shift-P</kbd>
3. "duplicate tab"

### Expected Behavior

open to current directory

### Actual Behavior

```
[error 2147942667 (0x8007010b) when launching `C:/Program Files/Git/bin/bash.exe -i -l']
Could not access starting directory "C:\Users13:06:36rajano"
```

```
[error 2147942667 (0x8007010b) when launching `C:/Program Files/Git/bin/bash.exe -i -l']
Could not access starting directory "C:\WINDOWS\system32\Tue Jul 23h\iblum-stack"
```

**Comment by zadjii-msft** [comment]
How do you have your prompt configured/?

**Comment by trajano** [comment]
With `oh-my-posh 22.0.2`.  Do you think it may be an issue with that? @JanDeDobbeleer FYI

**Comment by zadjii-msft** [comment]
Yes but _how exactly_? What theme? Do you have anything else in your `bashrc` (or whatever file)/?

**Comment by JanDeDobbeleer** [comment]
@trajano nothing changed in that area lately. OSC99 should work.

**Comment by trajano** [comment]
@zadjii-msft  Custom theme https://gist.github.com/trajano/6330ead3e34f8288f72e7eb54779b761  Haven't changed it in ages.

**Comment by DHowett** [comment]
@trajano can you [capture the output with the debug tap](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#enabling-the-debug-tap)

**Comment by JanDeDobbeleer** [comment]
@trajano this seems to be a bug on our end, I swear I'm going to make destroying Git Bash a mission.

**Comment by trajano** [comment]
Confirmed update of oh-my-posh fixes it thanks @JanDeDobbeleer
