### ISSUE TITLE
if you re creating cmd terminal why using same looks ?

### ISSUE THREAD

**Issue by Samthapa76** [microsoft/terminal#17605]
# Description of the new feature/enhancement

look i was here to see if am right place cause i am tired of stupid windows terminal if i start with normal privilage i can use theme background image it looks cool but with administrator privilage it dumb old crap looking terminal 

# Proposed technical implementation details (optional)

if you guy re creating terminal why in the world you make same looks why even you wasting time to create which is already exist from decades if you wanna re create it go for some stuff that should looks real change good looking and nice UI sci fi type or at least 1 simple theme thats it

**Comment by zadjii-msft** [comment]
I think what you're running into is /dup #10276. When you run a CLI app directly as admin, the platform can't hand it off to the Terminal. However, you can always just start `wt` directly as admin.
