### ISSUE TITLE
Add push/remove/peek/list api's for the terminals background image so multiple extensions can coexist.

### ISSUE THREAD

**Issue by dannyvv** [microsoft/terminal#1761]
# Add push/remove/peek/list api's for the terminals background image so multiple extensions can coexist.

I love the things people are doing with the background image and it is giving me lots of ideas as well.  (Detailed build progress bars overlay on the current background and current machine utilization)

We see similar issues with programs setting and getting text colors as well. Where programs remember the current color, set the new, do something, and then restore the remembered color. If something unexpected happens or multiple threads of the program are running, then all of a sudden your terminal can get 'stuck' in the wrong color.
If we are going to get many of these useful helpers and extensions for background, perhaps it would be useful for the api to support a hierachy of background images where the terminal maintains a priority order, so that it will be both easier to do the right thing and perhaps if it is inspectable diagnosable for end users why they ended up with a certain background :)

I can see things go wrong with a lost update for the backgrounds as well. The errorlevel 1 explosion caches and restores it to the profiles background, but what if you had actually set the background from a script in that terminal, after an error that 

# Proposed technical implementation details (optional)

I see a simple approach:
* The background image api also exposes a push/remove/peek/list style api (push would return a token, remove would take the token) in case threads are racing operating on the background.

and a more resource intensive but more powerfull approach:
* Allow for multiple background image layers, enable/disabeling of the layers can handle the push-pop. It would also enable people to write fancy graphical progress bars for their processes (think builds) and resource utilization charts (CPU/Memory/Disk)

**Comment by DHowett-MSFT** [comment]
Hey @dannyvv,
Thanks for the suggestion. Since we're trying to be "standards-compilant," we're not going to be introducing any more Win32 APIs -- each one of them is of a way higher maintenance burden than just adding support for some VT sequences. If there are some preexisting VT sequences (again, following existing standards rather than authoring our own!) that support pushing and popping terminal state, we'd be happy to look into them...

We're not likely to do something like this, with this scope, but it _is_ a cool idea.

**Comment by zadjii-msft** [comment]
What if we didn't do this as an API? I know there's another thread talking about having more background layers. I'm not suggesting we add an API ourselves, but if people could edit their profile (like with that powershell script) to push/pop background layers, would that work?

Do we have a specific issue for tracking N-ary background layers?
