### ISSUE TITLE
Terminal constantly minimizing and restoring

### ISSUE THREAD

**Issue by Candles** [microsoft/terminal#17616]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Restore Windows Terminal from being minimized.

### Expected Behavior

Windows Terminal restores without issue every time.

### Actual Behavior

On occasion, It'll restore, then minimize again, then cycle between minimized and restored. Every time it restores it steals focus, and it cannot be closed through regular methods (I have to use Task Manager to close it). It still receives some input and I can occasionally change tabs, but it's mostly unusable in this state.

https://github.com/user-attachments/assets/f8ae900f-f80c-4919-a998-1f77aa43d7c5

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #15279
