### ISSUE TITLE
Cursor droppings in WT cmd shell

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#17615]
### Windows Terminal version

Commmit 75f7ae4bec2f859b3f54043bd5c1a36161885a4d

### Windows build number

10.0.19045.4651

### Steps to reproduce

I don't know how many of these steps are strictly required, but this is what reproduces the issue for me quite consistently:

1. Open a cmd shell in Windows Terminal.
2. Create a directory with 6 files in it.
3. Make sure the screen height is 24 rows.
4. Clear the screen with `cls`.
5. Execute `dir` twice in a row.

### Expected Behavior

Only one instance of the cursor should be visible on the screen.

### Actual Behavior

There is an extra zombie cursor dropping left after the second `dir` is typed.

![image](https://github.com/user-attachments/assets/a79bd285-8896-4e2f-a92e-21024d287625)

It happens quite consistently for me, but not _every_ time, and it disappears quite easily - switching to another window and back again is usually enough. That made it very difficult to screenshot. I had to take a video and save one of the frames.

I can't reproduce it in the preview build (1.21.1272.0), so I'm assuming it's a regression. I'll try and do a git bisect later to see if I can figure out the exact commit.

**Comment by j4james** [comment]
It looks like commit 0a2b660e649bfc07b5142640b3fea56b1d8f564c is the cause.

**Comment by DHowett** [comment]
Thanks for bisecting, James!
