### ISSUE TITLE
Clickable filepaths

### ISSUE THREAD

**Issue by inoyakaigor** [microsoft/terminal#17612]
# Description of the new feature/enhancement
When I run ESLint in my project it shows some files as presented on screenshot below. It would be great if file paths can be clickable. I'm aware about #7562 and #14993 but the problem is still here.
![image](https://github.com/user-attachments/assets/7bd1c436-05c1-4d56-bf81-a553576c2250)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I think this is covered by issue #2671.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #2671.
