### ISSUE TITLE
Better icons for Visual Studio Developer Command Prompt/Powershell profiles

### ISSUE THREAD

**Issue by stamminator** [microsoft/terminal#17627]
# Description of the new feature/enhancement
Custom icons for the `Developer PowerShell for VS 2022` and `Developer Command Prompt for VS 2022` profiles would be a nice touch.

![5tXWrREqj0](https://github.com/user-attachments/assets/2456f899-1a19-4dfe-848c-e8543d339584)

# Proposed technical implementation details (optional)
Include images in the app's `ProfileIcons/` directory and automatically use them for said profiles. I threw these together in GIMP. If they are satisfactory, feel free to use them.

![cmd_vs](https://github.com/user-attachments/assets/1d3da7f9-1de7-40f1-9932-196fa10ec130)

![powershell5_vs](https://github.com/user-attachments/assets/1cb5ab60-31b2-4825-8666-74eca7b243fa)

**Comment by DHowett** [comment]
Thanks for the inspiration, and the suggestion! We got in touch with the Visual Studio design team and they made a set of icons for us that look pretty similar to your concept, except with some of the original shell icons punched out to form a keep-out zone.

You can see them over in #17706!
