### ISSUE TITLE
Cursor desync in Far Manager

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#17621]
### Windows Terminal version

current main

### Windows build number

10.0.19045.4651

### Other Software

Far Manager, version 3.0.6352.0 x64

### Steps to reproduce

1. Launch the latest Far Manager.
2. Press `Ctrl+O` to hide panels.
3. Press `Enter` (run empty command).

### Expected Behavior

The cursor should remain at the command line prompt.

### Actual Behavior

The cursor unexpectedly moved to the lower right corner (conhost is ok ,WT is affected).

https://github.com/user-attachments/assets/a95f71c8-d13c-4b4c-ac5e-902ca6f46932

This issue came up right after #17194.

**Comment by j4james** [comment]
As far as I can make out, we get a linefeed at the bottom of the page which triggers an `InvalidateFlush` setting the `_circled` flag. This occurs in a frame with no other changes, so the `VtEngine::StartPaint` doesn't think there's anything to do, and as a result we never execute the `VtEngine::EndPaint`, which is where the `_circled` flag is usually handled and reset.

The next thing that happens is that the cursor is moved to its expected position after the prompt, but the `_circled` flag will still be set when we paint the next frame, and that prevents the cursor from being "painted" (which is how its position is passed through to conpty). See the code here:

https://github.com/microsoft/terminal/blob/295cd17b028d288ff81445f532d9301b44f6ffd9/src/renderer/vt/XtermEngine.cpp#L210-L213

One possible fix would be to add the `_circled` flag to the list of things that are checked when determining whether there's something for the renderer to do, i.e. just add it to the condition here:

https://github.com/microsoft/terminal/blob/295cd17b028d288ff81445f532d9301b44f6ffd9/src/renderer/vt/paint.cpp#L33-L37

That seems to fix the issue for me, but I don't fully understand the circling behavior, so there might be more to it than that.

**Comment by lhecker** [comment]
Does this issue repro in Windows Terminal Canary?

If it doesn't repro there, I'd personally like to avoid fixing `VtEngine`, because I don't fully understand the nuances of the circling behavior either. Seemingly innocent fixes in that area in the past have repeatedly caused regressions.

**Comment by DHowett** [comment]
> Isn't the current main branch the same thing? 

Not currently. We're building Canary out of a merge between a couple in-flight branches right now.

**Comment by o-sdn-o** [comment]
This issue is not reproducible in the [`dev/lhecker/goodbye-vtengine`](https://github.com/microsoft/terminal/tree/dev/lhecker/goodbye-vtengine) branch.
