### ISSUE TITLE
Session management support

### ISSUE THREAD

**Issue by willzhang** [microsoft/terminal#17622]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Is it possible to support saving historical session connections, because if there are dozens of sessions, it would be very time consuming to manually enter the address each time to connect remotely.

like this:
![image](https://github.com/user-attachments/assets/4b208776-dffe-4c09-9d4c-9eb307f4b36a)

**Comment by lhecker** [comment]
Is there a reason why your shell's command history is insufficient for this?
