### ISSUE TITLE
Allow brightness/darkness adjustments on background images

### ISSUE THREAD

**Issue by djk2004** [microsoft/terminal#1762]
# Summary of the new feature/enhancement
In the profiles.json file, I can use the _backgroundImageOpacity_ property to increase brightness on an image, but I can't decrease it.  If _backgroundImageOpacity_ is 1.0, then the image is applied seemingly as-is with no adjustments behind the console text.  When _backgroundImageOpacity_ is closer to 0, then the image will appear brighter.  Finally, when the value is 0, the image will appear mostly white.

**NOTE:** As I use the terminal today, I was able to achieve the visual effect I wanted by decreasing the brightness in my target image using an editor, then setting that image in my profile with _backgroundImageOpacity_ set to 1.
![example](https://user-images.githubusercontent.com/37919951/60456028-b196ec00-9bfd-11e9-90b6-6439e40985b9.PNG)

# Proposed technical implementation details (optional)
Add a property in configuration that allows the background image to have a dark tint.

**Comment by Summon528** [comment]
I think what you actually want is to have `backgroundImageOpacity` works with profile's background color which is a part of #1107

**Comment by djk2004** [comment]
That may be the right answer.  It will be interesting to see once that ticket is done, thanks!
