### ISSUE TITLE
Fails to start when "Sync Settings" is active in a machine where the primary EXE is not installed

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#1763]
Cannot use Windows Terminal at all.

# Environment
Windows 10 19H1
PowerShell Preview 6 installed in machine 1
PowerShell Preview 7 installed in machine 2
Windows "Sync Settings" is active.

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1. Install Windows Terminal in 2 machines with the same MSA account.
2. Install PowerShell Core in machine 1.
3. Change the default console to be PowerShell Core.
4. Log out and wait for settings to sync.
5. Log into Machine 2.

Start Windows Terminal.

# Expected behavior
Windows Terminal can start (even in CMD or some recovery console mode)

# Actual behavior
Windows Terminal fails to start

The settings from machine 1 are getting copied to machine 2, but this is invalid as machine 2 does not have the same environment as machine 1.

**Comment by DHowett-MSFT** [comment]
I'm going to consolidate these discussions in #1770. Thanks, Oscar!
