### ISSUE TITLE
Terminal crashes when opening a split-window in settings menu.

### ISSUE THREAD

**Issue by LuigiDaBro** [microsoft/terminal#17633]
Duplicate of [#13528](https://github.com/microsoft/terminal/issues/13528)
Currently not resolved  

### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.0

### Steps to reproduce

> Start the program
> `[<ctrl> + T]` - Open the settings
> `[<alt> + <shift> + (+/-)]` - Press either the horizontal or vertical split hotkey

### Expected Behavior

Eighter the window should
- not split
- split into the default terminal emulator specifiend in the configuration.

### Actual Behavior

The terminal will stop responding, and eventually crash or just not respond anymore.

**Comment by DHowett** [comment]
Thanks for filing!

**Comment by zadjii-msft** [comment]
I can't repro this on `main` (~ 7b39d2491). I also can't repro this on 1.21.1772.0 (Terminal Preview).

I'm guessing this got solved some time in 1.21/?
