### ISSUE TITLE
WT Canary crash when opening Settings

### ISSUE THREAD

**Issue by Andarwinux** [microsoft/terminal#17649]
### Windows Terminal version

1.22.2141.0

### Windows build number

26120.1330

### Steps to reproduce

Open "Settings"

### Actual Behavior

crash
[crash.txt](https://github.com/user-attachments/files/16465017/crash.txt)

**Comment by DHowett** [comment]
Thanks! Looks like the compiler bug is still around after all.

**Comment by DHowett** [comment]
Fixed in #17653
