### ISSUE TITLE
Moving the terminal window is hard and confusing

### ISSUE THREAD

**Issue by mkArtakMSFT** [microsoft/terminal#1764]
Hi.

Thanks for bringing the terminal to the next level 👍 
I switched to using this as my default terminal. One thing, however, I haven't got used to yet, is that I constantly try to move the window by using (what I think, the window title) area, however later realizing that it's actually the area of the tab header.
![image](https://user-images.githubusercontent.com/34246760/60464410-61228d00-9c03-11e9-8eeb-578a996c9e04.png)

So I have to carefully use the super narrow area for moving the terminal window:
![image](https://user-images.githubusercontent.com/34246760/60464387-4cde9000-9c03-11e9-8341-7605b6b9f2a5.png)

This is an experience thing and it's hard to get used to. Can you please fix it.
One solution would be to allow moving using the empty tab header area too.

**Comment by DHowett-MSFT** [comment]
Hey @mkartakmsft! Thanks. Please make sure you search before reporting a new issue. This is #1375, #564, #1138, and more. :smile:
