### ISSUE TITLE
Follow GTK/Qt color scheme for frame and background and text

### ISSUE THREAD

**Issue by bphd** [microsoft/terminal#17663]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You're more than welcome to customize the [`colorScheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes) and [`theme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes) however you see fit ☺️

**Comment by bphd** [comment]
> You're more than welcome to customize the [`colorScheme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes) and [`theme`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes) however you see fit ☺️

Thing is that would define custom colors where I talk here rather about a mechanism to follow color scheme
