### ISSUE TITLE
url for file

### ISSUE THREAD

**Issue by yhgalaxy** [microsoft/terminal#17662]
# Description of the new feature/enhancement
I want the terminal to automatically recognize file path hyperlinks, so that when clicked, they can be opened in the file explorer or the default application, for example, /path/to/file. Currently, URLs can already be opened in the browser, such as https://..., but file paths are not yet recognized.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
FWIW, the Terminal does recognize the `file://` URI scheme:

![image](https://github.com/user-attachments/assets/5a5bcef4-cdae-4921-9d7a-791cd2b879a3)


But yea, I'd call this a /dup #8849 #2671 #5001

Thanks!
