### ISSUE TITLE
Font rendering issue in Windows Terminal Preview with Cascadia Mono Nerd Font when resizing the window

### ISSUE THREAD

**Issue by kikvinn** [microsoft/terminal#17687]
### Windows Terminal version

1.21.1772.0

### Windows build number

10.0.26100.0

### Other Software

ph-my-posh 23.6.0
powershell 7.5.0-preview.3

### Steps to reproduce

Open Windows Terminal Preview.
Set the font to Cascadia Mono Nerd Font.
Resize the terminal window by dragging the edges.
Observe the font rendering issues.

### Expected Behavior

The font should render correctly regardless of the window size, maintaining proper alignment and without any visual glitches.
![image](https://github.com/user-attachments/assets/a2c3c080-e811-4c6e-aa90-adbead6bcb9d)

### Actual Behavior

When the window is resized, the Cascadia Mono Nerd Font stops rendering correctly, leading to misalignment and visual glitches in the terminal.
![image](https://github.com/user-attachments/assets/bfe4310b-e4ff-4896-8ed9-043c3177d02c)

**Comment by lhecker** [comment]
Good news! This was recently fixed in #17568.

If you'd like to avoid waiting until the fix gets released (in a few weeks), please use our nightly Canary build in the meantime: https://github.com/microsoft/terminal/discussions/16121
