### ISSUE TITLE
> > Just add the path of the power shell to the environment variable

### ISSUE THREAD

**Issue by owaisishtiaqsiddiqui** [microsoft/terminal#17698]
> > Just add the path of the power shell to the environment variable
> 
> Thank you. It works! `%systemroot%\System32\WindowsPowerShell\v1.0`
> 
> ![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)

I did this but it does not work for mw

_Originally posted by @owaisishtiaqsiddiqui in https://github.com/microsoft/terminal/issues/6039#issuecomment-2119349027_

**Comment by owaisishtiaqsiddiqui** [comment]
I tried to run it as administrator it opens but then suddenly closed automatically

**Comment by carlos-zamora** [comment]
Can you share a copy of your %USERPROFILE%\Documents\PowerShell\profile.ps1 /?

Can you also provide some more information on what issue you're experiencing? The context is a bit difficult to follow since it's coming from another thread. Thanks!

**Comment by owaisishtiaqsiddiqui** [comment]
I have attached the file.

> Can you share a copy of your %USERPROFILE%\Documents\PowerShell\profile.ps1 /?
> 
> Can you also provide some more information on what issue you're experiencing? The context is a bit difficult to follow since it's coming from another thread. Thanks!

I have attached a video.

https://github.com/user-attachments/assets/bec7e7ab-732f-4795-8a19-e199a7e1da6a

**Comment by zadjii-msft** [comment]
Does running powershell normally (not as admin)work for you/? 

We're probably still gonna need a copy of your powershell profile. You can find that at:

```
%USERPROFILE%\Documents\PowerShell\profile.ps1
```

**Comment by owaisishtiaqsiddiqui** [comment]
No it opens and then got closed suddenly. This issue is same for (1) if I run it as admin (2) if I run it normally. Let me do the process which you advised me too. Please bear with me.

**Comment by owaisishtiaqsiddiqui** [comment]
@zadjii-msft 
looks the path of my PowerShell is: C:\Windows\System32\WindowsPowerShell\v1.0

Attached image is the proof.
![screenshot](https://github.com/user-attachments/assets/9b4e9e77-2101-4b31-b97e-8f1bfd6d1643)

**Comment by DHowett** [comment]
> [@zadjii-msft](https://github.com/zadjii-msft) looks the path of my PowerShell is: C:\Windows\System32\WindowsPowerShell\v1.0
> 
> Attached image is the proof.

My dude, he is asking you for a copy of a specific file from your computer. We believe you that PowerShell is installed. We think you have a configuration that is making PowerShell fail to start.

**Comment by owaisishtiaqsiddiqui** [comment]
> > [@zadjii-msft](https://github.com/zadjii-msft) looks the path of my PowerShell is: C:\Windows\System32\WindowsPowerShell\v1.0
> > Attached image is the proof.
> 
> My dude, he is asking you for a copy of a specific file from your computer. We believe you that PowerShell is installed. We think you have a configuration that is making PowerShell fail to start.

I don't know what to do with this "%USERPROFILE%\Documents\PowerShell\profile.ps1" but there is no such folder of file that exits on this path.
but in the attached picture i tried searching the file, so if this is what he is asking for? please tell

![1](https://github.com/user-attachments/assets/f1f5c390-89b6-4ce6-a552-07b9233fda03)

**Comment by DHowett** [comment]
Thank you, that is very helpful information.

Can you try these two things, separately?

1. Change the Windows PowerShell profile to "never automatically close"? This will help us determine if there is a message being displayed before it exits.



![Image](https://github.com/user-attachments/assets/642ef249-dd48-45ee-9464-1d3f8ce4f581)



![Image](https://github.com/user-attachments/assets/6770fb83-72d8-4a04-8119-5b349d657f27)



![Image](https://github.com/user-attachments/assets/d38dfbae-6f95-46e1-a632-227df2a0002d)



2. Change the `commandline` to include `-noprofile`



![Image](https://github.com/user-attachments/assets/b0496256-f770-4d73-be97-6c88b905b013)

**Comment by owaisishtiaqsiddiqui** [comment]
@DHowett are you referring to this?

![1](https://github.com/user-attachments/assets/f10d5413-ad77-4118-abba-6af00b57eaa8)

**Comment by DHowett** [comment]
No. I gave you screenshots of what I was referring to.

**Comment by DHowett** [comment]
I see in your video that you are reporting a bug with Windows Powershell _outside of Windows Terminal._ I am sorry.

Can you open the Run dialog with <kbd>Windows+R</kbd>, and run `powershell -noprofile`?

I see that you are using some sort of education software. I wonder if it is "locked down."

**Comment by DHowett** [comment]
Thank you.

That error corresponds with "file not found."

Your Windows installation is damaged. Please run `sfc /scannow` and consider reinstalling Windows.

**Comment by owaisishtiaqsiddiqui** [comment]
The issue caused has been addressed and specific guidelines have been given by @DHowett. Thank you for sparing your precious time to address my problem.

**Comment by DHowett** [comment]
Thanks! I am sorry that it was complicated. 🙂
