### ISSUE TITLE
bug report srsly

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#1769]
🤣

**Comment by zadjii-msft** [comment]
Please search for duplicates before filing new issues.

/dup #1769

/dup #1769

(edit: This is a duplicate of both the above issues.)

**Comment by DHowett-MSFT** [comment]
This is a /dupe of #1769

**Comment by DHowett-MSFT** [comment]
testing

**Comment by DHowett-MSFT** [comment]
testing

**Comment by DHowett-MSFT** [comment]
testing

**Comment by DHowett-MSFT** [comment]
testing

**Comment by DHowett-MSFT** [comment]
requesting feedback

**Comment by DHowett-MSFT** [comment]
resolving as question

**Comment by DHowett-MSFT** [comment]
resolving as question again?

**Comment by DHowett-MSFT** [comment]
RAQ

**Comment by DHowett-MSFT** [comment]
raq

**Comment by DHowett-MSFT** [comment]
How did that work for you?

**Comment by DHowett-MSFT** [comment]
This _is_ a **markdown** file

test test

**Comment by DHowett-MSFT** [comment]
Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with Windows Insider Build 19603.

**Comment by DHowett-MSFT** [comment]
?? Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with Windows Insider Build 19603.

**Comment by DHowett-MSFT** [comment]
?? Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with Windows Insider Build 19603.

**Comment by DHowett-MSFT** [comment]
?? Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with Windows Insider Build 19603.

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with Windows Insider Build 19603.

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 19603](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/).

**Comment by DHowett** [comment]
test

**Comment by DHowett** [comment]
This is a duplicate of #3

**Comment by DHowett** [comment]
how are you running x?

**Comment by itsme-alan** [comment]
/dup #1000 

Can I join the fun?

**Comment by itsme-alan** [comment]
Obviously, I can't 😞

**Comment by zadjii-msft** [comment]
for real tho/?

**Comment by zadjii-msft** [comment]
nice

**Comment by zadjii-msft** [comment]
Test post please ignore
