### ISSUE TITLE
useAcrylic doesn't work

### ISSUE THREAD

**Issue by ialobanov** [microsoft/terminal#17692]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.0

### Other Software

PowerShell 7.4.4.

### Steps to reproduce

Go to Setting - Default - Appearance - Transparency and enable "Enable acrylic material" and set any percentage of opacity - it doesn't work.

### Expected Behavior

Transparency with acrylic mode. 

### Actual Behavior

Opacity doesn't work with "Enable acrylic material".

**Comment by ialobanov** [comment]
All acrylic setting doesn't work.

**Comment by zadjii-msft** [comment]
* Are you running in a VM?
* On battery power? 
* with Transparency Effects enabled in the settings?
* Does acrylic work in any other apps? (IIRC the Start Menu uses acrylic)/?

There's any number of reasons why Windows itself disables acrylic.

**Comment by ialobanov** [comment]
It's my host machine with Windows 11.  I found an issue - I disable Transparency Effect in Windows settings. But transparency without acrylic effect in terminal work correctly with disabled feature Transparency Effect in Windows settings.

**Comment by zadjii-msft** [comment]
Sure, yea. The name for that OS-wide setting is a bit misleading. It just enables Acrylic & Mica. "vintage" transparency in the way the Terminal supports it is unaffected. 

Thanks for following up!
