### ISSUE TITLE
Git Bash commands in VS-Code: git init fatal: unable to access 'C:\Users?ikeh/.config/git/config': Invalid argument

### ISSUE THREAD

**Issue by EikeHanel** [microsoft/terminal#17693]
While using Visual Studio Code: Version: 1.92.1 (user setup) and then the Git Bash Terminal, every Git command leads to:
$ git init
fatal: unable to access 'C:\Users?ikeh/.config/git/config': Invalid argument
(.venv) 

When using PyCharm or the Windows Command Center the response is what you would expect.

I am still learning about Git and how to use it properly, so i would appreciate some help. 

Kind regards,
Eike

**Comment by lhecker** [comment]
Your `HOME` environment variable in git bash is probably incorrect. If you don't really want to use Git Bash, you can also just use powershell or even cmd. Git works in any shell.

**Comment by EikeHanel** [comment]
Thank you very much!
I found this regarding your post and it fixed the problem: 
https://graphite.dev/guides/git-change-home-directory-git-bash 

I am doing an online tutorial and they used Vs-Code and I was just confused why every other terminal worked but the one in Vs-Code didn't.

Anyway, this solves my problem I'll close this thread.
