### ISSUE TITLE
Ubuntu not considered as WSL for drag and drop

### ISSUE THREAD

**Issue by dgl** [microsoft/terminal#17691]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.0

### Other Software

Ubuntu 22.04.3 LTS (standard WSL build; installed via `wsl --install Ubuntu`)

### Steps to reproduce

Drag a file from explorer to the terminal.

### Expected Behavior

I get the path in Linux form.

### Actual Behavior

I get an untranslated Windows path.

I *think* this is because the profile that WSL set-up for me uses `ubuntu.exe` rather than WSL.

Relevant snippet of my settings.json is like this:

```
            {
                "colorScheme": "Campbell",
                "font":
                {
                    "size": 12.0
                },
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "scrollbarState": "hidden",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            },
  [...]
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": true,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
```

https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalControl/ControlInteractivity.cpp#L737 matches on source being `Windows.Terminal.Wsl` but that has been hidden, as far as I'm aware the only config I've changed is via the UI to change the colour scheme and scrollbar settings. Clearly now I've worked this out I can fix the config, but it isn't obvious the Ubuntu app isn't considered WSL...

**Comment by carlos-zamora** [comment]
Thanks! We're hoping to improve on this sometime soon. We'll mark this as a /dup of #12961
