### ISSUE TITLE
Stop roaming settings for now

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1770]
Until we come up with a good story for settings overrides and default profiles on different machines, we're going to want to move the settings from `RoamingState` to `LocalState`. Since right now a user's settings include everything we know about them _for a specific machine_, we're not capable of safely roaming them.

Roaming machine-specific settings causes (but is not limited to causing) the following issues:

* instant exit on launch because default shell has gone away
* new install's settings stomping other machines
* spurious changes at runtime resulting in syncs from other machines, changing settings unexpectedly

We should make the move to localstate sooner rather than later, since we only just released v0.2. This is still going to be a minor breaking change, but we should include some migration logic.

That migration logic **should** use a file move (instead of a read-parse-write cycle), as some folks are using symbolic links to manage their settings.

Refer: #1567 #1455.

**Comment by angelog0** [comment]
Usually, on GNU/Linux, the settings go in `$HOME/.appsrc` folder. On Windows, this should be something like `%USERPROFILE%\appssettings`, even if almost all apps use `%APPDATA%` (.`..\AppData\Roaming`).

For a while, I have put all physical files for Windows Terminal settings in `[MSYS2}/home/user/.ms-terminal` and in `[WT]/RoamingState` their symlinks. All this worked for a few days, than WT started to fail when it was the first app launched after the Windows login, I had to start something else, first...

I don't know your technical reasons, but for the POV of the user, `%USERPROFILE%\appssettings` would be fine.

Thanks.

**Comment by onovotny** [comment]
This is biting me already where I have different `startingDirectory` settings per machine. The roaming is causing one machine to always be wrong.

**Comment by sba923** [comment]
Just my €0.02: IMVHO this has higher priority than #1258 (cascading settings Defaults -> User). Of course, the full settings experience needs both.

**Comment by wenmin92** [comment]
With the new preview version v0.4, settings sync has stopped, how should I sync my settings? 

I use a symbolic link which link profiles.json in Dropbox, but modifications to this file are not effective immediately, I need to restart Windows Terminal to take the effect.

Where am I wrong? THX

**Comment by wenmin92** [comment]
Thanks for your reply. 
I like sync very much, as you said, maybe the symbolic is not a perfect solution. I think there could be a setting in the profile can control the sync behavior, use the old style or not. Or some other methods  that support sync. If all these are too much trouble, the current approach is acceptable.
