### ISSUE TITLE
Implement scriptable command promt and auto suggestions

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#17702]
# Description of the new feature/enhancement

For powershell we can use OhMyPosh to bring various auto completion capabilities, git branch integration etc. But many don't use PowerShell as default instead prefer simple commandline. Ability to have some colors and scriptability and auto completions will make the experience way better. For example, I integrated with clink and my commandline looks like this:

<img width="259" alt="image" src="https://github.com/user-attachments/assets/399d42d4-fc11-47fa-99c9-3a38bf040baa">

This uses Clink and OhMyPosh theme on simple commandline.

having this feature off the shelf with terminal will enhance the experience.

# Proposed technical implementation details (optional)

References: 
https://github.com/ichigo-afk/awesome-terminal/blob/master/ClinkCMD/CustomizingCMD.md
https://chrisant996.github.io/clink/clink.html#features

**Comment by carlos-zamora** [comment]
Thanks for filing. We appreciate it, but CMD is in maintenance mode so we're not planning on investing in any features for it. Thus closing.
