### ISSUE TITLE
Renderer encountered an unexpected error: 2147942414

### ISSUE THREAD

**Issue by m-terlinde** [microsoft/terminal#17703]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631

### Other Software

AMD onboard graphics driver 31.0.22048.10001
AMD Ryzen 7 PRO 7840U with Radeon 780M graphics

### Steps to reproduce

On a freshly booted Win11, opening the Terminal results in Terminal prompting the warning `Renderer encountered an unexpected error: 2147942414`.

It doesn't matter if I want to start the CMD or PowerShell.

Rebooting sometimes help, sometimes not. Over time the error always resurfaces.

### Actual Behavior

Does not display the actual terminal.

**Comment by lhecker** [comment]
2147942414 is 0x8007000E which is `E_OUTOFMEMORY` ("Ran out of memory"). That's unfortunately not something we can do anything about.

Couple questions:
* How much system memory do you have?
* Have you checked how much is being used while the issue occurs?
* Do you know which application may be using your memory (via Task Manager, etc.)?

**Comment by Regenhardt** [comment]
I have the same problem. Got a new ThinkPad T16 with Windows 11. Installed a few pending windows updates and lenovo firmware/bios updates but it didn't fix it. 

I have 32GB RAM installed.  
Task Manager says 11.5/30.7 GB (37%) used when the issue occurs. When I close the faulty terminal, it goes to 11.4/30.7 GB.  
Most usage is currently by Firefox, 2.8Gb RAM. Nothing else using significant RAM amounts.

**Comment by Regenhardt** [comment]
Turns out, the lenovo updater wasn't enough. I downloaded the GPU driver from AMD directly, uninstall the previous one and installed the new one, now my terminal works fine.

**Comment by Regenhardt** [comment]
So @m-terlinde try updating your graphics driver.

**Comment by m-terlinde** [comment]
I've done that, works like a charm. Thanks!
