### ISSUE TITLE
QuakeMode - Add a Title bar like ConEmu

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#17701]
# Description of the new feature/enhancement

Add a title bar like ConEmu which is tiny and doesn't take much screen space. The `Toggle focus Mode` adds a title bar, but it takes lot of screen space and looks super clunky. There are various other buttons on ConEmu which help quicly navigate as well.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/80a0680c-30ee-4903-b068-7779a8e5663c">

vs

<img width="959" alt="image" src="https://github.com/user-attachments/assets/7ee9df95-4ac3-4abc-99f6-d5e5529cf059">

# Proposed technical implementation details (optional)

Implement better title bar for quake mode

**Comment by carlos-zamora** [comment]
Thanks for filing! We're actually tracking this over in #8888. There's been some discussion before on this kind of issue (as shown with the bot above), so I'm marking this as a /dup of #8888.
