### ISSUE TITLE
Bug Report - Unable to scroll

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1771]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Start Windows Terminal,
Have the terminal on restore down,
Open a tab of Ubuntu 18.04 TLS,
Look for a directory with lots of file in it where scroll bar exists.
Then maximise the screen,
Click on the scroll bar and move it up,
The screen does not move upwards.

# Expected behavior

1. When maximised, the scroll bar should work.
2. Scroll bar does not work when you click and push it upwards

# Actual behavior

Screenshot belows show what it looks like:
<img width="960" alt="Bug-report-1" src="https://user-images.githubusercontent.com/50003738/60481673-f9cb1280-9cc0-11e9-88a2-ddec58ff911f.png">

**Comment by DHowett-MSFT** [comment]
Sounds like #1494.
