### ISSUE TITLE
add config except list to those exe that should not using WT

### ISSUE THREAD

**Issue by heartacker** [microsoft/terminal#17719]
# Description of the new feature/enhancement

after using WT， all things are open int WT
PLEASE add a config list so that users can make some except exe。PLEASE

# Proposed technical implementation details (optional)
add setting to except some application

**Comment by zadjii-msft** [comment]
Can I ask first what scenario isn't working for that app, such that you'd want it to not open in Terminal/? I'd rather fix that scenario, than offer an opt-out 😉

**Comment by heartacker** [comment]
@zadjii-msft FYI
![image](https://github.com/user-attachments/assets/3f25b61e-c36f-4ddc-adeb-c72937a47efa)

**Comment by heartacker** [comment]
it had to open a terminal while I am using the octave GUI

![image](https://github.com/user-attachments/assets/8c5239f4-0e8d-4288-8b80-4d3b9c4c3c82)

**Comment by carlos-zamora** [comment]
Thanks for filing! Due to the earlier discussion, we're going to mark this as a /dup of #17054.
