### ISSUE TITLE
Ctrl+D or Enter?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#17743]
Microsoft Windows 10 Pro for Workstations
10.0.19045.4780 (2009, 22H2)
WindowsTerminal 1.21.2406.25002 (preview)

In this situation, neither keystroke did anything.

![image](https://github.com/user-attachments/assets/7c704e09-6d63-4aa2-b481-d7add3d680e0)

**Comment by DHowett** [comment]
Thanks! I think this is a /duplicate of #17578

**Comment by vefatica** [comment]
I can repro (every time) like this.

Start WT normally (one tab, normal window).
Go full-screen (F11).
Split vertical (Alt+Shift++)
"exit" the shell on the right (this is OK)
"exit" the remaining shell (error occurs)

Note that exiting the lefthand shell then the righthand one does not cause the error.
