### ISSUE TITLE
Interested in working at MS Terminal/windows team and get paid for that if possible

### ISSUE THREAD

**Issue by appydam** [microsoft/terminal#17740]
So, as title suggests. I'm asking you if you can setup an interview/call with me.

Understanding a big codebase takes time and its hard to find some extra time apart from current job and personal life.
So, I was thinking if you may hire me and pay me, and I can work on this full time. 
Technically I'm asking for job in simple words.

You may choose to discard this issue, but if you may address then I would really appreciate it

Its my github: https://github.com/appydam

Would really appreciate if you acknowledge it...

**Comment by zadjii-msft** [comment]
Thanks for your interest! Unfortunately, our team isn't hiring at this time. If that ever changes in the future, we'd probably post something over on our https://github.com/microsoft/terminal/discussions page. 

Thanks!
