### ISSUE TITLE
Don't close Terminal upon closing the last tab

### ISSUE THREAD

**Issue by Cellhawk** [microsoft/terminal#17746]
### Description of the new feature/enhancement

As it is with most modern applications that use tabs, these days, like web browsers or even text editors (e.g. vscode), you can usually close all tabs without having to close the app itself.

_As someone, who works with a lot of different cmd tabs with different env variables, closing and opening new tabs relatively often, using .cmd files, I would find this extremely helpful and workflow-friendly, as I sometimes end up with all tabs closed, but want to keep the terminal open on my workstation._
___
### Proposed technical implementation details

Allow us to close tabs without closing the Windows Terminal app itself.

The "landing screen" that appears when all tabs are closed could be an empty window with either "Defaults" appearance settings, or a custom profile with custom settings.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6276 for more discussion.

/dup #6276

**Comment by Cellhawk** [comment]
Aw shucks, I tried searching but somehow failed to find that. Thanks!
