### ISSUE TITLE
Mouse events are not sent when the mouse is outside the top of the WT

### ISSUE THREAD

**Issue by BDisp** [microsoft/terminal#17744]
### Windows Terminal version

Versão: 1.20.11781.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Please clone this GitHub repository [MouseTests](https://github.com/BDisp/MouseTests.git) and run. Keep pressing the mouse inside the console and move around it, as the gif show.

### Expected Behavior

The mouse events should be sent while the mouse button is pressed and moving inside or outside the console until it's released.

### Actual Behavior

The mouse events are sent as expected except from outside of the console on top.

![MouseTests](https://github.com/user-attachments/assets/aa84e08d-a96f-43e2-a1ee-8ae199ba74d3)

With the `conhost` the mouse events are always sent from anywhere while the mouse isn't released.

**Comment by zadjii-msft** [comment]
Yep, that's super weird alright!

Our theory is that we're getting into the mouse-select-drag-scroll state, and attempting to "scroll" the terminal, and suppressing the mouse event

**Comment by BDisp** [comment]
Yep, I already noted that and that why I made my example writing always on the same line to avoiding scrolling. I noted that moving outside the console was causing to scroll. This would be valid if I was pressed the scroll bar but that wasn't the case. Maybe acceptable only if the scroll bar is visible. Thanks.
