### ISSUE TITLE
Efficiency Mode

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#17759]
# Description of the new feature/enhancement

Microsoft Edge has support for "Efficiency Mode" that's part of Windows 11.  I was wondering if something similar is applicable for Windows Terminal since most of the time its just going to idle in the background.

# Proposed technical implementation details (optional)

Have a settings.json entry to allow it or not, disabled by default until all bugs are sorted out.

**Comment by zadjii-msft** [comment]
Any idea for potential efficiency improvements beyond what we're tracking in #9600/? We're already _not a browser_, so I imagine a lot of the "efficiency" improvements that Edge does for background tabs don't really apply to the Terminal

**Comment by trajano** [comment]
If the tab is not in the foreground I would guess it would be sleeping a bit and not processing the updates it is getting from where it gets the data to show the screen from will be processed less frequently?

Or if it is getting a flood of updates and it's not in the foreground to also buffer the changes so it doesn't update as often.

I think I should move this to a discussion perhaps others can chime in can you switch it over?

**Comment by zadjii-msft** [comment]
Yea definitely. We can't totally stop processing the output (we've got to drain the output from conpty so something like a build doesn't get blocked), but we can totally stop rendering. That we're specifically tracking in #1989 (a sub-point in #9600). 

We can totally continue the discussion in /dup #9600. Thanks!
