### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [microsoft/terminal#1775]
# Summary of the new feature/enhancement
In the Linux terminal and Windows Powershell; CTRL + L is used to make the screen clear, It is so fast than using (cls or clear) command.
If it develops for the Windows Console, It will improve our work speed.

# Proposed technical implementation details (optional)
When the Console becomes full, there should be a hotkey (like CTRL + L) to clear the screen.

**Comment by zadjii-msft** [comment]
This is a shell feature implemented by `bash` and PowerShell. As you'll note, Ctrl+L works to clear the screen when you're running powershell in Windows Terminal.

As it's a shell feature, we'd have to implement it in cmd.exe, and cmd.exe is parked indefinitely. So unfortunately, this is never going to be fixed for cmd.exe. I'd recommend Powershell if you want a cross-platform shell that supports Ctrl+L.
