### ISSUE TITLE
Typo in Czech translation of the desktop context menu item

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/terminal#17752]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Use latest, fully updated Windows 10 system with Czech locale and latest version of Terminal installed.
2. Open the Start Menu and search for "Terminal" to confirm that the launcher is correctly translated as "Terminál".
3. Switch to the desktop and right click to open the context menu.

### Expected Behavior

"Open in Terminal" in the desktop context menu is translated as "Otevřít v aplikaci Termin**á**l".

### Actual Behavior

"Open in Terminal" in the desktop context menu is translated as "Otevřít v aplikaci Termin**a**l" instead of the correct "Otevřít v aplikaci Termin**á**l" one.

Context menu item in File manager (Explorer) has the same typo.

I did not test this on Windows 11, but I suspect that there will be the same typo there too.

String ID                                     | Current                                   | Suggestion                                | Reason
--------------------------------------------- | ----------------------------------------- | ----------------------------------------- | ------
ShellExtension_OpenInTerminalMenuItem         | Otevřít v aplikaci &amp;amp;Terminal      | Otevřít v aplikaci &amp;amp;Terminál      | a VS á
ShellExtension_OpenInTerminalMenuItem_Preview | Otevřít náhled &amp;amp;aplikace Terminal | Otevřít náhled &amp;amp;aplikace Terminál | a VS á
AppDescription                                | Nová Terminál Windows                     | Nový Terminál Windows                     | "Terminál" has a masculine gender

**Comment by AsciiWolf** [comment]
![start-menu-item](https://github.com/user-attachments/assets/bca7efa5-c812-4ae1-a99c-eff81769144b)

![context-menu](https://github.com/user-attachments/assets/e3731a1c-0e93-4b69-8565-6c0e92132bfe)

**Comment by AsciiWolf** [comment]
https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalApp/Resources/cs-CZ/ContextMenu.resw#L167
https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalApp/Resources/cs-CZ/ContextMenu.resw#L171

https://github.com/microsoft/terminal/blob/main/src/cascadia/CascadiaPackage/Resources/cs-CZ/Resources.resw#L167
https://github.com/microsoft/terminal/blob/main/src/cascadia/CascadiaPackage/Resources/cs-CZ/Resources.resw#L171

**Comment by AsciiWolf** [comment]
@zadjii-msft Any news? Did the localization team look at this? Thanks!

**Comment by lhecker** [comment]
Reported internally as GCS-716551.

**Comment by AsciiWolf** [comment]
@lhecker

Thanks! Here's another possibly incorrectly translated string:

https://github.com/microsoft/terminal/pull/17798#issuecomment-2308941406

**Comment by lhecker** [comment]
Can you explain what's wrong with the `AppDescription` translation?

**Comment by AsciiWolf** [comment]
Sure. It just does not sound correct. :-)

The original string is "The New Windows Terminal". It at least should be translated as "Nov**ý** Terminál Windows" (correct grammatical gender because the word "Terminál" has a masculine gender in Czech).

**Comment by AsciiWolf** [comment]
```
  <data name="ShellExtension_OpenInTerminalMenuItem" xml:space="preserve">
    <value>Otevřít v aplikaci &amp;Terminal</value>
    <comment>This is a menu item that will be displayed in the Windows File Explorer that launches the non-preview version of Windows Terminal. Please mark one of the characters to be an accelerator key.</comment>
  </data>
```

It is still unfixed! Termin**a**l instead of Terminál.

Only the second problem got fixed.

@DHowett @lhecker Please reopen this ticket.

**Comment by AsciiWolf** [comment]
Any update?

**Comment by lhecker** [comment]
Update: Reopened the localization issue internally because it wasn't fixed. :)

**Comment by AsciiWolf** [comment]
@lhecker Any news about this? It's just one incorrect character in one string (contained in four resw files). It should hopefully be fairly easy to fix. :-)

**Comment by lhecker** [comment]
> It should hopefully be fairly easy to fix. :-)

You say that, but you don't know our internal processes. 🥲
They translated it to `Otevřít v &amp;Terminálu` in this PR: #18031 
Does that sound right to you?

**Comment by AsciiWolf** [comment]
> Does that sound right to you?

Yes it does! :-)

Thanks!
