### ISSUE TITLE
The "Overwrite key binding" warning is very broken

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#17754]
(from bug bash 1.22)

Action Editor
🛑 "Overwrite key binding" warning is very broken

![image](https://github.com/user-attachments/assets/0cdbab01-b1d4-4963-b04e-9691b9ae2000)
_(thats right, I had to take a screenshot of the image in Loop, thanks Loop)_

I can't say "no". Dismissing it is like saying "yes". Also it scrolls horizontally.

**Comment by PankajBhojwani** [comment]
I'm somewhat certain this is the way it worked before my changes as well (I see this same behaviour in Stable)

**Comment by DHowett** [comment]
> I see this same behaviour in Stable

I do not. Dismissing the flyout does not "confirm" and overwrite the binding in Stable.

**Comment by zadjii-msft** [comment]
Dismissing the flyout does confirm for me in 1.21. So maybe it regressed in 20->21?

**Comment by zadjii-msft** [comment]
I wonder if it's something more subtle in XAML somewhere. Cause like, on 1.20, when you **hit the checkbox button**, the action stays in the "editing" state, with the textbox and the buttons. But in 1.21, the button immediately exits the editing state, then pops the "are you sure"?

**Comment by DHowett** [comment]
Much more likely that it was from #14292, which rewrote the action view model (and it should be the viewmodel that keeps track of states like this.)
