### ISSUE TITLE
Documentation Issue :install colorTool

### ISSUE THREAD

**Issue by Ferrymania** [microsoft/terminal#1776]
I followed the instruction in the colortool introduction https://github.com/Microsoft/Terminal/tree/master/src/tools/ColorTool#installing 
![Snipaste_2019-07-02_19-40-24](https://user-images.githubusercontent.com/28045677/60510626-7500e880-9d02-11e9-98be-cbadd8f9fd10.png)
and download the src package but I did't find the ColorTool.exe ,do I need to build it from source or miss something hhh  >_>
![Snipaste_2019-07-02_19-46-43](https://user-images.githubusercontent.com/28045677/60510548-39661e80-9d02-11e9-9a4c-a6e519dd8c2d.png)

**Comment by zadjii-msft** [comment]
That documentation might be out of date. Don't download the latest _terminal_ zip, you need the latest _ColorTool_ zip:
https://github.com/microsoft/terminal/releases/tag/1904.29002

Now that we're also using the repo for Terminal code, it looks like tagging commits is hiding the actual releases. 

@DHowett-MSFT is there a way we can make sure that the tagged terminal releases don't actually show up on that page (and only ColorTool releases do?)

**Comment by Ferrymania** [comment]
Thanks a lot Got it 😁 the colortool page install instruction give the link https://github.com/Microsoft/console/releases
but you can scroll down and click "next" button,which would show the colortool.zip
