### ISSUE TITLE
Alt button not working

### ISSUE THREAD

**Issue by K1LLER0M** [microsoft/terminal#1777]
After trying to use vim in the terminal to write a C program I realized that the Alt button does not work ( At least in AZERTY keyboard layout ) so I can't write neither `` [ backticks ] nor # [ hash symbol ]

**Comment by zadjii-msft** [comment]
Please try searching, this is a dupe of #521 which is pinned to the top of the repo.

**Comment by K1LLER0M** [comment]
Oops, I didn't notice that, thanks
