### ISSUE TITLE
Are there plans to support a secondary font?

### ISSUE THREAD

**Issue by SadSock** [microsoft/terminal#17784]
# Description of the new feature/enhancement

When the primary font does not fully cover the characters, the secondary font will be used. Many fonts, especially paid fonts, do not include nerd fonts.

thanks
# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Yep! In 1.21 (which is in Preview now, and will be rolling out to Stable over the next few weeks) you can specify multiple fonts separated by commas.
