### ISSUE TITLE
Padding appearance setting is not applied when set via fragments

### ISSUE THREAD

**Issue by callmeTayyy** [microsoft/terminal#17796]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045.4780

### Steps to reproduce

- Have Wsl
- Set padding to `10`
- Extract [wt-fragments-padding-bug.zip](https://github.com/user-attachments/files/16733527/wt-fragments-padding-bug.zip) and copy the folder to `%ProgramData%\Microsoft\Windows Terminal\Fragments\`
- Directory will be: `%ProgramData%\Microsoft\Windows Terminal\Fragments\Windows.Terminal.Wsl\themes.json` and `update.json`
- Open Wsl profile and check the padding (issue happens with any profile btw)

### Expected Behavior

Padding set in `update.json` should be applied along with the other settings. It doesn't work as `#`; `"#"`; `"#, #"` or `"#, #, #, #"` as detailed in the [documentation](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#padding).

![Screenshot](https://github.com/user-attachments/assets/5c011048-1e49-49cc-8113-d1d563bcee76)

### Actual Behavior

Setting on the fragment file is ignored and default is used.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're actually going to mark this as a /dup of #10790.

There's plenty of discussion over there around what's going on, but [this comment](https://github.com/microsoft/terminal/issues/10790#issuecomment-892196309) explains it best imo.

**Comment by callmeTayyy** [comment]
@carlos-zamora you are right! After looking at the comment you mentioned, I was able to change it. Thank you.
