### ISSUE TITLE
NonASCII Chars preventing seeing more text since 1803 release

### ISSUE THREAD

**Issue by iguyking** [microsoft/terminal#178]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.1]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Setup:  
1. Using Windows command prompt (not windows powershell)
1. ssh to VM running kafka and run the command kafka-console-consumer where there is AVRO binary encoded data on the topic.  So the initial data coming back will have binary encoded information then text then binary.   

* What's wrong / what should be happening instead:

In Pre-1803 I would get text back that looked like this:
```
▒▒▒▒XBusiness▒B0167BDC260D94E927C0C3BF6A88110819DE5555A2182249EE26BA1FEBF8187B9DFCD53019293B9A50Vm_KeyRotation_APP_CLT_LEG_ENT_EMAIL@6BDC0D3295D86D66B1CC2CAD8836A1CD▒fa76d7a3c1d88d0ede64cd484a971e0386421dab088ca36b1ca1ca559e94286eeccfd71373f8b9d54fb45b087855569e68c59ccf5db5805453321e6c821ec1eb▒▒▒▒▒X     
```
![goodoutput](https://user-images.githubusercontent.com/5004028/40064134-81a8286a-5824-11e8-874e-0294f5bf6c79.jpg)

In 1803 release I get nothing back.   
![badoutput](https://user-images.githubusercontent.com/5004028/40064158-8eaa5178-5824-11e8-96cd-b42bbb8d3423.jpg)

I expect to see the same output as I saw in the Pre-1803 release as that is the common thing I see in every other tool I utilize when viewing binary data like that.

**Comment by zadjii-msft** [comment]
@iguyking Sorry this got lost in the backlog. Is this still happening for you? Just printing that text to the Terminal seems to work fine in newer builds of the Console and Terminal:
![image](https://user-images.githubusercontent.com/18356694/142883400-66644d2f-5aec-4e05-b9f2-730a5ad833a4.png)


It might be an issue with `ssh` - if it's not working, which version of `ssh` are you using?
