### ISSUE TITLE
It seems like `DA1` is broken in 1.22 (the response doesn't include a valid CSI (`\x1b`))

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#17813]
It seems like [DA1](https://vt100.net/docs/vt510-rm/DA1.html) is broken in this release. When I query Sixel support by sending `\x1b[c`, the response doesn't include a valid CSI (`\x1b`) in the beginning:

```
[?61;4;6;7;14;21;22;23;24;28;32;42c
```

and it should be:

```
\x1b[?61;4;6;7;14;21;22;23;24;28;32;42c
```

I'm using [Microsoft.WindowsTerminalPreview_1.22.2362.0_arm64.zip](https://github.com/microsoft/terminal/releases/download/v1.22.2362.0/Microsoft.WindowsTerminalPreview_1.22.2362.0_arm64.zip)

_Originally posted by @sxyazi in https://github.com/microsoft/terminal/discussions/17809#discussioncomment-10469993_

**Comment by DHowett** [comment]
This is probably “the documentation said I can read VT replies *without* enabling VT INPUT mode, but the new ConPTY breaks that” as reported by @alabuzhev 

We drop the ESC during processed input handling. See discussion in #17729.
