### ISSUE TITLE
"Classic" should be included in the color schemes

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#1781]
# Summary of the new feature/enhancement
Trying to make ZtreeWin looks the same as before.

# Proposed technical implementation details (optional)
The classic scheme should be provided to use with legacy console mode apps like ZtreeWin.

    {
      "name": "Classic",
      "black": "#000000",
      "blue": "#000080",
      "green": "#008000",
      "cyan": "#008080",
      "red": "#800000",
      "purple": "#800080",
      "yellow": "#808000",
      "white": "#C0C0C0",
      "brightBlack": "#808080",
      "brightBlue": "#0000FF",
      "brightGreen": "#00FF00",
      "brightCyan": "#00FFFF",
      "brightRed": "#FF0000",
      "brightPurple": "#FF00FF",
      "brightYellow": "#FFFF00",
      "brightWhite": "#FFFFFF"
    }

**Comment by DHowett-MSFT** [comment]
We should probably call it "vintage" to carry forward our cursor shape joke :smile:
