### ISSUE TITLE
Icon is not displayed for console mode app

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#1783]
When defining a profile for ZtreeWin, the icon of the EXE is not displayed.

# Environment

```none
Windows build number: Windows 10 19H1
Windows Terminal version (if applicable): master Jul 1st 2019

Any other software?
```
ZtreeWin

# Steps to reproduce
Create a profile for Ztw like this:
    {
      "commandline": "C:\\Users\\ocalvo\\OneDrive\\Apps\\ZtreeWin\\ZTW64.EXE",
      "icon": "C:\\Users\\ocalvo\\OneDrive\\Apps\\ZtreeWin\\ZTW64.EXE",
      "name": "ZTW",
    }

# Expected behavior
The first icon of the EXE is displayed

# Actual behavior
No icon is displayed

**Comment by DHowett-MSFT** [comment]
This is #1504 :smile:
