### ISSUE TITLE
Terminal crashes when I click on the mark point.

### ISSUE THREAD

**Issue by markox92** [microsoft/terminal#17836]
### Windows Terminal version

1.21.2361.0

### Windows build number

22631.4112

### Steps to reproduce

I'm watching some realtime logs from a Python app; after a few minutes, when I click on the mark point, the terminal crashes.

Another problem with this last version is that when you have very long output and scroll up, then when I press the keyboard's up or down to run a command again, the terminal won't go to the current command, it stays in the same position, and I must scroll down to check what I have as a prompt. This wasn't happened before

### Actual Behavior

Only what i can found in event logs is this

```
Faulting application name: WindowsTerminal.exe, version: 1.21.2408.23001, time stamp: 0x66c8f3fe
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.4111, time stamp: 0x66b5fe39
Exception code: 0xc000027b
Fault offset: 0x000000000086fb40
Faulting process id: 0x0x1850
Faulting application start time: 0x0x1DAFB0FA150B7FB
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.21.2361.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: a43ed049-a3b0-4e94-b9fb-5a17d8a14aa0
Faulting package full name: Microsoft.WindowsTerminal_1.21.2361.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by zadjii-msft** [comment]
Could you try reproing this crash with the Feedback Hub's problem recorder? If you share the link to the /feedback here, we should be able to find the crash dump in the backend. Thanks!
