### ISSUE TITLE
Inclusion of Powershell modules in appref-ms packages

### ISSUE THREAD

**Issue by twoscoopsofpig** [microsoft/terminal#1785]
# Summary of the new feature/enhancement

In order to use modern authentication with Exchange Online, there is a module in appref-ms format which checks for updated versions of the module before running. The module is not accessible with Import-Module in a regular Powershell console, but can be installed from the Hybrid tab under the Exchange Admin Center of Exchange Online, as described at https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

I have attempted to add the full path to the appref=ms package as a new profile in Windows Terminal, but receive an error about bad syntax in profiles.json. I assume this is due to the presence of backslashes in the path to the module. Moving the appreff package to a folder in my PATH doesn't seem to make any difference either.

Considering the consolidation goal of this project, it would be useful to include all forms of the Powershell console, regardless of packaging.

Thanks for your attention!

**Comment by zadjii-msft** [comment]
You'll need to make sure to properly escape the commandline in your profile:
```json
{
  "commandline": "this\will\not\work",
  "commandline": "but\\this\\will"
}
```

See also #1090

**Comment by twoscoopsofpig** [comment]
That doesn't work either, much like adding the package to a folder in the
PATH and calling it by the relative filepath didn't work. This is probably
down to the appref-ms packaging, not what that package calls or how it gets
called.

**Comment by zadjii-msft** [comment]
Could you share the error you're seeing, and the profile? I'm also _fairly_ sure that you can't try and execute things that in subdirectories of things in your `%PATH%`, the executable's directory needs to be on `%PATH%` itself.

**Comment by twoscoopsofpig** [comment]
It is directly in the path. The error is simply that the requested package
won't open when I try to open it from the new tab dropdown or by hotkey -
the new tab flashes on screen but never populates or stays on screen.

I'm including my profile below. It does use a new GUID, though it reuses
the original icon from the initial Powershell profile.

{
    "acrylicOpacity" : 0.5,
    "background" : "#012456",
    "closeOnExit" : true,
    "colorScheme" : "Campbell",
    "commandline" : "C:\\Users\\conantb\\Documents\\Admin\\Microsoft
Exchange Online Powershell Module.appref-ms",
    "cursorColor" : "#FFFFFF",
    "cursorShape" : "bar",
    "fontFace" : "Consolas",
    "fontSize" : 10,
    "guid" : "{dad46b19-2e01-41cf-b310-e4022c80dbb9}",
    "historySize" : 9001,
    "icon" :
"ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
    "name" : "Windows EXOPS PowerShell",
    "padding" : "0, 0, 0, 0",
    "snapOnInput" : true,
    "startingDirectory" : "%USERPROFILE%",
    "useAcrylic" : false
}

Please also note that this profile is using the absolute path to the
package, though even after adding C:\users\conantb\Documents\Admin to the
path and referring to the package simply as "Microsoft Exchange Online
Powershell Module.appref-ms" I still see the issue. Further, renaming the
package and using that name fails in a similar manner.

I've also confirmed that calling the package in the path works from the run
box (among other methods).

**Comment by zadjii-msft** [comment]
Maybe try 
```json
"\\\"C:\\Users\\conantb\\Documents\\Admin\\Microsoft Exchange Online Powershell Module.appref-ms\\\""
```

Escaping spaces is particularly tricky ATM.

**Comment by twoscoopsofpig** [comment]
Neither that nor nesting single quotes (escaped or otherwise) works.

When the appref package fires, it runs an updater and then loads the console with the module imported.

**Comment by DHowett-MSFT** [comment]
Ah, this is somewhat worrying. I'm not actually sure how `appref-ms` modules are supposed to be launched. Let me have a look -- if it's something we can solve with the right powershell command line, this'll turn into general user documentation and advice. If it's something that can't be solved with a command line, we'll need to start asking the hard questions.

**Comment by DHowett-MSFT** [comment]
This might just boil down to #492. It looks like `appref-ms` shortcuts are another type of ClickOnce application, which means their launch _must_ be brokered through another process (internet explorer, windows shell, etc.) Right now, we can't support hooking the launch of another console application through a broker.

**Comment by twoscoopsofpig** [comment]
That rings true for me. Thanks for looking into it! Are there any plans on
the roadmap to support this?

**Comment by DHowett-MSFT** [comment]
Sure is. Please follow #492 :smile:

**Comment by twoscoopsofpig** [comment]
Much appreciated!
