### ISSUE TITLE
Terminal will wrap the output.

### ISSUE THREAD

**Issue by caolib** [microsoft/terminal#17865]
I don't want it to wrap, because word wrapping will make my output look confusing!
![image](https://github.com/user-attachments/assets/51e5e285-f18a-4476-9f3c-8f745d654e3d)

I want it to display a scroll bar at the bottom and I can drag the scroll bar left and right to view the content.
**thank you!**

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1860 for more discussion.

/dup #1860

**Comment by lhecker** [comment]
FYI the correct solution that works everywhere is this: https://dev.mysql.com/doc/mysql-shell/8.4/en/mysql-shell-using-pager.html
Also, see this: https://github.com/okbob/pspg
