### ISSUE TITLE
Weird terminal behavior

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#17864]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.0

### Steps to reproduce

When we create a lot of tabs in terminal. It ends up leaving a weird trail of icons when minimized.
![Screenshot](https://github.com/user-attachments/assets/401dd8ab-80b5-49de-a273-a98f93fbac2b)
They're related to terminal because as soon as i terminate or close terminal they disappear.

### Expected Behavior

These should not appear

### Actual Behavior

These appear
![Screenshot](https://github.com/user-attachments/assets/fccaa45d-129b-4c02-902c-705a15a4874d)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #15219 for more discussion.

/dup #15219
