### ISSUE TITLE
Different color for Admin terminals

### ISSUE THREAD

**Issue by Hexaae** [microsoft/terminal#17877]
# Description of the new feature/enhancement
Have separate color settings for Admin terminal shell

When I change Terminal color scheme it will be applied indifferently to normal user prompt and to admin prompt. A global color/scheme setting.
# Proposed technical implementation details (optional)
NA

I'd like the Terminal window opened with Admin privilege to have a different color scheme/settings (f.e. dark red), to immediately recognize it's not a normal user prompt (in a different color).

**Comment by j4james** [comment]
Thanks for the suggestion. But there's actually already an issue tracking admin-specific colors (#3246). There is also one for admin-specific themes (#8311). And more generally, there's an epic issue covering all admin-specific customizations, which you might want to follow (#11111).

**Comment by zadjii-msft** [comment]
Yep, I'll put this with /dup #3246. Thanks!
