### ISSUE TITLE
Closing One Instance of Windows Terminal Closes All Instances When unfocusedAppearance with Opacity 100 is Enabled

### ISSUE THREAD

**Issue by NikoEscobar** [microsoft/terminal#17873]
### Windows Terminal version

1.20.11781.0

### Windows build number

 10.0.22631.0

### Steps to reproduce

1. Open Windows Terminal.
2. In the settings, set the following configurations:

   ```json
   {
     "opacity": 40,
     "useAcrylic": true,
     "unfocusedAppearance": {
       "opacity": 100
     }
   }
   
3. Open multiple instances of Windows Terminal.
4. Close one of the open instances.

### Expected Behavior

Only the closed instance of Windows Terminal should close, leaving the other instances open and unaffected.

### Actual Behavior

Closing one instance of Windows Terminal causes all other open instances to close unexpectedly.

**Comment by zadjii-msft** [comment]
This sounds a lot like #17520 - can you try [Windows Terminal v1.21.2361.0](https://github.com/microsoft/terminal/releases/tag/v1.21.2361.0) or [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) and see if it's fixed for you there/?

**Comment by NikoEscobar** [comment]
> This sounds a lot like #17520 - can you try [Windows Terminal v1.21.2361.0](https://github.com/microsoft/terminal/releases/tag/v1.21.2361.0) or [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) and see if it's fixed for you there/?

I can confirm the issue is not present on [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0)

As for the [Windows Terminal v1.21.2361.0](https://github.com/microsoft/terminal/releases/tag/v1.21.2361.0) version, I'm not really sure how to update my current version to this one, Microsoft Store is not detecting new a version to update.

**Comment by carlos-zamora** [comment]
Awesome! Thanks for filing and following up! We'll mark this as a /dup of #17520.
