### ISSUE TITLE
Settings do not open if json files are assigned to gvim

### ISSUE THREAD

**Issue by maru-sama** [microsoft/terminal#1789]
# Environment

```none
Windows build number: Version 10.0.18362.207
Windows Terminal version (if applicable): master

Any other software?
gvim
```

# Steps to reproduce

Install gvim
Assign json files to gvim
Try to open the settings in terminal

# Expected behavior

Gvim opens the settings file
# Actual behavior

Nothing happens

More information:
I have visual studio installed as well. If I change the settings so visual studio is the default handler for json file it works, also notepad. If select gvim from the selection list I can open json files in explorer just fine but trying to open the settings in terminal does not work.
To be honest I am not sure if this is a terminal or vim issue but since terminal is the first application I see this behaviour I filled the bug here.

**Comment by zadjii-msft** [comment]
That's certainly super curious. I'm pretty sure @DHowett-MSFT uses gvim as his daily driver without issues. 

Are you sure the gvim window isn't just opening up somewhere lower in the Z-order?

**Comment by maru-sama** [comment]
No, nothing happens, as soon as I change this to notepd or visual studio it works right away. I am wondering if setting the standard viewer via explorer -> open with -> set as default is enough or if and entry is missing for gvim.

**Comment by maru-sama** [comment]
Since ShellExecute is being used it should "just-work"..

**Comment by maru-sama** [comment]
Ok, I made some progress. It DOES work with gvim if you change the code in LaunchSettings() to

' ShellExecute(nullptr, L"**edit**", settingsPath.c_str(), nullptr, nullptr, SW_SHOW);

instead of L"**open**". 
That said if I change it this way Visual Studio no longer works. I wonder why gvim is not honoring the "open"

**Comment by maru-sama** [comment]
Ok, so I found the entries in the registry for gvim. Apparently 
![registry](https://user-images.githubusercontent.com/152713/60608431-be633d80-9dbf-11e9-8dfb-9afdd7741458.png)
The command contains the gvim executable. As you can see in the screenshoit I changed "edit" to "open" and now gvim works. Would it make sense to try both values in the code if the first one does not work?

**Comment by DHowett-MSFT** [comment]
Interesting! So, calling `ShellExecute` without specifying the verb will use the "default" verb, whatever that happens to be? That'll probably be a pretty good solution.

**Comment by killroy1971** [comment]
Can confirm, but changing the .json_auto_file shell entry from edit to open did not alter Windows Terminal's Settings behavior.  I had to remove the registry keys to unset the json application association.

Now, it doesn't prompt me at all when I try to edit the Terminal settings.

Shame, as I'm primarily a Linux user and getting this right in corporate/disconnected environments would make life quite a bit easier.

**Comment by maru-sama** [comment]
> Interesting! So, calling `ShellExecute` without specifying the verb will use the "default" verb, whatever that happens to be? That'll probably be a pretty good solution.

That's right although the value can be something else then "open" or "edit". Maybe it is better to try "open" first and if this fails try with "edit", since these are more or less the values that should be normally used.

**Comment by perrybucsdad** [comment]
I think the problem is, for those of us who are not developers, we don't have anything associated with .json files.  The solution is by default to associate .json file to notepad.  Advanced users can always pick their favorite text editor.  With the install from Microsoft store or Github though, we need it to associate with Notepad since it is on every Win 10 OS.

**Comment by maru-sama** [comment]
I think this is very easy to implement. First you try to open it with nullptr so the assigned application (if there is one) will be used. You check the return value. If this shows that nothing was found open the file in notepad or wordpad which always exists in windows.

**Comment by perrybucsdad** [comment]
The common non-programmer will never understand or think to do that though.

**Comment by maru-sama** [comment]
What I mean is that the terminal first tries to open the assigned app and if this does not work, open the settings with notepad.



> HINSTANCE res;
>                 res = ShellExecute(nullptr, nullptr, settingsPath.c_str(), nullptr, nullptr, SW_SHOW);
>         if ((INT_PTR)res < 32)
>        {
>            ShellExecute(nullptr, nullptr, L"notepad", settingsPath.c_str(), nullptr, SW_SHOW);
>        }

@DHowett-MSFT what do you think?

**Comment by jayhill** [comment]
This still doesn't work for me in `1.0.200517002-release1.0`.
This seems super simplistic, but it looks to me like the issue is just that the path contains a space (`…\Windows Terminal\…`).
gvim opens, but it opens to the file picker view under `<root>\Users\<user>\AppData\Local\Microsoft` — it cuts off right where the space is.

**Comment by DHowett** [comment]
Can you run the following from powershell?

```
gp hkcu:/software/classes/.json
gp hkcu:/software/classes/.json_auto_file/shell/edit/command
```

**Comment by DHowett** [comment]
(Just to be clear: I’m helping you figure out what is wrong with your JSON association. Once the request to launch the json file leaves Terminal, it’s out of our control as to how it is passed to the final application that will be handling it.)

**Comment by jayhill** [comment]
Thanks @DHowett!
I don't have any `.json*` entries in that location.
I see gvim.exe associated with .json in other places in the registry, but nowhere with a command setting that could be changed from  `open` to `edit` (assuming that is where this is heading).

**Comment by DHowett** [comment]
The lack of those keys is _somewhat_ surprising (but not terrifically, because file associations went from simple to "dark magic" in the past six years.) I'm more concerned about the escaping, and the quoting, on any arguments passed to gvim. When I checked on my personal machine, I saw my JSON association target (something like) `gvim.exe "%1"` -- the quotes being, of course, crucial for preserving spaces in paths.

**Comment by jayhill** [comment]
Thanks again. Adding the keys did the trick.
For anyone finding this via search the way I did, this is what I added (update the `gvim.exe` path based on your installation). YMMV.

```
[HKEY_CURRENT_USER\SOFTWARE\Classes\.json]
@=".json_auto_file"

[HKEY_CURRENT_USER\SOFTWARE\Classes\.json_auto_file]

[HKEY_CURRENT_USER\SOFTWARE\Classes\.json_auto_file\shell]

[HKEY_CURRENT_USER\SOFTWARE\Classes\.json_auto_file\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Classes\.json_auto_file\shell\open\command]
@="\"C:\\Users\\JDoe\\scoop\\apps\\vim\\current\\gvim.exe\" \"%1\""
```

(If adding these directly through the regedit UI, you don't have to escape the path separators or quotation marks like that.)
