### ISSUE TITLE
[Windows Terminal - Command Palette]: Clear buffer button is not functional via mouse and keyboard. 

### ISSUE THREAD

**Issue by SaurabhNew** [microsoft/terminal#17891]
### Windows Terminal version

1.22.2362.0

### Windows build number

27695.1000

### Other Software

Test Environment:
OS: Windows 11 Version Dev (OS Build 27695.1000)
App: Windows Terminal Preview

### Steps to reproduce

**Repro steps :**
1.Open Windows Terminal.
2.Open the 'Command Palette' using 'Ctrl + Shift + P' keys.
3.Navigate to the clear buffer control and activate it via mouse and keyboard.
4.Observe the issue.

**User Experience**
Users are unable to perform the "Clear Buffer" action using either mouse or keyboard, which can hinder their workflow.

**Attachments:**
[Clear buffer button is not  functional via mouse and keyboard..zip](https://github.com/user-attachments/files/16943879/Clear.buffer.button.is.not.functional.via.mouse.and.keyboard.zip)

### Expected Behavior

Clear buffer button should be functional via both mouse and keyboard and on activating clear buffer button, it should clear all the buffer from the editing window.

### Actual Behavior

Clear buffer button is not functional via mouse and keyboard.
Clear buffer button is not functional with the shortcut key as well, which is added from actions.

**Comment by lhecker** [comment]
Hey! This was previously reported in #17867. I'll close your issue as a duplicate then. 🙂 /dup #17867
The good news is that a PR to fix it has been opened and should go out soon: #17884
