### ISSUE TITLE
GitHub Issue Duplicate Detector

### ISSUE THREAD

**Issue by 01x4-dev** [microsoft/terminal#17890]
# Description of the new feature/enhancement
As there are lots of open issues (`1.5k+` when writing this), the likelihood for the community of inadvertently introducing new duplicates is fairly high.

The only way for contributors to mitigate this risk is to follow the recommended guidelines and rigorously searching (manually) similar issues prior to open a new one. 

Needless to say, this is error prone as it depends on the quality of the research itself.  
Result: while everybody agrees on the rulebook, life is too short so let's submit new issue right away... 🤷🏻‍♂️ 

The new GitHub action <kbd>ghidd</kbd> delivers a seamless repo maintainer experience aiming to simplify triage tasks by automatically spotting and tagging duplicate issues.

📑 Read more at https://github.com/marketplace/actions/github-issue-duplicate-detector
Contributions are highly welcome 🙏🏻 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Our coworker @craigloewen-msft is actually in the process of upgrading our existing duplicate detector. It's temporarily offline, but he assures me it'll be back before too long. 

Thanks though!
