### ISSUE TITLE
The Thai language displays incorrectly in the Windows terminal.

### ISSUE THREAD

**Issue by pawawat** [microsoft/terminal#17908]
### Windows Terminal version

1.20.11781.0

### Other Software

inside wsl

### Steps to reproduce

`curl https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt`

### Expected Behavior

![image](https://github.com/user-attachments/assets/16d63278-15ad-4c1d-9954-f962a4683046)

### Actual Behavior

![image](https://github.com/user-attachments/assets/4d692996-8e1a-4027-a7bb-aa37e488ac1d)

**Comment by zadjii-msft** [comment]
This is what I see in  1.23.2501.0 (which is a canary build, but shouldn't be all that different from 1.22). 

![image](https://github.com/user-attachments/assets/e403217e-c3dd-4f83-bab9-04d92538a744)

can you try [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) and see if that fixes it/?

**Comment by pawawat** [comment]
> This is what I see in 1.23.2501.0 (which is a canary build, but shouldn't be all that different from 1.22).
> 
> ![image](https://private-user-images.githubusercontent.com/18356694/366555291-e403217e-c3dd-4f83-bab9-04d92538a744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMjkxMTYsIm5iZiI6MTcyODAyODgxNiwicGF0aCI6Ii8xODM1NjY5NC8zNjY1NTUyOTEtZTQwMzIxN2UtYzNkZC00ZjgzLWJhYjktMDRkOTI1MzhhNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA4MDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YjIxOWUyNjU1NDdjZmQ4Y2I1NWYyNWI0MzU4MDg2N2IwNWRlZWE0NTE1NGI0MDQ1NDk3ZDRlMjk2ZDE0NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xvu9DjbkxfA2_P3YWA1rliLynXoBekrdJw5KGQKu8QE)
> 
> can you try [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) and see if that fixes it/?

It's fixed !!! Thx
