### ISSUE TITLE
error 2147942487

### ISSUE THREAD

**Issue by CRY-2007** [microsoft/terminal#17906]
### Windows Terminal version

 1.20.11781.0

### Windows build number

10.0.19045.4651

### Steps to reproduce

Lounch Windows terminal with powerShell, got error  2147942487 
![image](https://github.com/user-attachments/assets/110c61a0-b3e4-498e-b819-066bb8652d08)

### Actual Behavior

Got error

**Comment by zadjii-msft** [comment]
> Warning
> An unexpected handler error occurred: 2147942487

Huh, not sure I've ever seen that one come from the renderer before. What's your GPU setup look like? Driver versions/?

**Comment by CRY-2007** [comment]
NVIDIA Quadro FX 880M
It was driver version 8.17.12.7643 (2011 year)
I change it to version 21.21.13.4201 (2016 year)
And now windows terminal works.

**Comment by zadjii-msft** [comment]
Fantastic, happy to hear it!
