### ISSUE TITLE
Set default shell

### ISSUE THREAD

**Issue by AnikHasibul** [microsoft/terminal#1791]
I want `ubuntu` as my default shell. How to do that?

When I open the terminal app, I would like to see ubuntu be opened instead of powershell.

**Comment by dnagl** [comment]
You can do this setting in the `profiles.json` file. There you find the option to set the default profile for your terminal.

You'll find the correct GUID for your profile in the `profiles` section of the file.

**Comment by AnikHasibul** [comment]
Thank you!

It worked. For people also looking for the answer:

```diff
{
    "globals" : 
    {
        "alwaysShowTabs" : true,
--      "defaultProfile" : "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
++      "defaultProfile" : "{2c4de342-38b7-51cf-b940-2309a097f518}",
        "initialCols" : 100,
        "initialRows" : 25,
        ....
```
This worked for me. Where `{2c4de342-38b7-51cf-b940-2309a097f518}` is the value of the `"guid"` in my ubuntu profile.
