### ISSUE TITLE
Terminal runs as an administrator but no response

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/terminal#17920]
### Steps to reproduce

1. Right-click PowerShell
2. Click Run as Administrator

### Expected Behavior

https://github.com/user-attachments/assets/078357d5-a4a4-4fe8-83da-c9e40523c5bb

### Actual Behavior

 no response

**Comment by zadjii-msft** [comment]
Can you share the Terminal and OS version you're running/?

**Comment by AlaricWeb** [comment]
sAfter the system update, there is no problem
