### ISSUE TITLE
Cannot open after downloading from Microsoft Store

### ISSUE THREAD

**Issue by llinfeng** [microsoft/terminal#1794]
# Environment

```none
Windows build number:  [Version 10.0.18362.175]
Windows Terminal version: latest on Windows Store.

Any other software: set WSL as the default profile.
```

# Steps to reproduce

Simply clicking the Launch button will give the following error message:
![image](https://user-images.githubusercontent.com/5890407/60587852-76163200-9d63-11e9-8b1f-9273f4273050.png)

## More details:
As I experimented with the Windows Terminal, I have installed it on all my Windows PCs that are running the latest build. 3 out of 4 are performing well. It is only one machine that kept complaining about the "profile". Yet, it is a bit confusing, as:

* One Surface Pro does not sync with all others; 
* Yet, the other 3 seem to sync their settings;

# Expected behavior
Expect the Windows Terminal to open up.

# Actual behavior

Repeatedly, I see the following error message:
![image](https://user-images.githubusercontent.com/5890407/60588481-0dc85000-9d65-11e9-8d8c-30395dd1de0d.png)

# Question:
1. I notice that the setting for Windows Terminal shall sync across all machines. This feels like magic, but also insecure: can I ask Windows Terminal to source some Dropbox directory, for the `profiles.json` file?
2. As an App on Windows Store, is it normal to have all other copies installed on other PCs deleted when I delete the app from one machine? As I was trying to uninstall and re-install Windows Terminal on the machine that cannot launch it (as reported), I noticed that other machines have also deleted their copies of Windows Terminal.

**Comment by zadjii-msft** [comment]
I don't believe we're showing that dialog, so any text about your "profile" isn't actually referring to the profiles in your settings file, this is something closer to the OS I believe. 

Is there anything that's particularly different about the setup of the non-working machine? Are you not an admin on that machine, but admin on the others? 

Are there any events in Event Viewer that look correlated with this crash? I've never seen this dialog before so I'm really at a loss for what might be causing it.

**Comment by llinfeng** [comment]
I would not consider the buggy machine to be any different from all the others. I am Admin to all these machines and I have been following the following steps to guarantee a stable username, say `xxx`, when I was setting up Windows OS.

* Choose to go with Offline account when setting up Windows;
* Name myself as `xxx Lastname`, and Windows was happily picking up `xxx` as the username
* Once the system loads, I use my Microsoft account to log into the Windows store.

The buggy machine should be the first machine that I installed Windows Terminal (Preview) onto: I found its setting file as `C:\Users\Username\AppData\Local\Packages\Microsoft.WindowsTerminal_8[xxxxxxxxxx]\RoamingState\profiles.json` and have been reusing this path on other machines. All other machines are liking the setting file, and the buggy machien liked the setting file as well.

## RE: "profile" as my Microsoft account?
One more thing that I notice: the buggy machine (I named it as "AW") may have some trouble with Windows Store? Here goes the screenshot of devices that I have linked to Microsoft account, T1, T2 and Surface had no trouble launching, and AW does have an issue. It appears that AW is the oldest machine on this list??

![image](https://user-images.githubusercontent.com/5890407/60595200-884c9c00-9d74-11e9-9642-eb6c5e53df10.png)


## Question about the setting file
Does the path stay stable? And, can I appoint a Dropbox location for `source`-ing?

**Comment by miniksa** [comment]
This sounds like #1770 might help mitigate your issues in the near term.

**Comment by AlvinKuruvilla** [comment]
Ok so I am having a sort of similar issue where I downloaded the preview from the Microsoft store but now I cannot open the new terminal. It seems like it doesn't exist and I can't even install it again because the store sats I already own it. Also, I don't think its an issue with system requirements as I am up to the May 2019 version, is there a requirement I am missing or is this a bug, and how do I fix it
Any answers would be appreciated

**Comment by DHowett-MSFT** [comment]
Alright, this one is definitely outside our wheelhouse. Would you mind filing feedback in the Feedback Hub, category Developer Platform > App Deployment, and sharing a link here? Thanks.

**Comment by llinfeng** [comment]
I am closing this ticket as it is not restricted to the Windows Terminal (Preview). Across the board on the faulty desktop machine, I receive the same error message from all Windows Store Apps. [This is a Windows OS problem and may or may not be addressed in future Windows updates.](https://techcommunity.microsoft.com/t5/Windows-10/quot-The-specified-user-does-not-have-a-valid-profile-quot-error/td-p/193455)

Will be interested to learn any fix to the issue without having the Windows 10 system re-installed.

**Comment by llinfeng** [comment]
I can open all Windows Store Apps on the buggy machine for now. I think a certain Windows Update has solved the problem. Thankfully, I don't need to redo my OS to fix the launching bug.

**Comment by llinfeng** [comment]
Update pre the recent Windows Update to OS Build `18362.10005` ==> I encountered the same error message when attempting to launch Windows Terminal. Performing a "in-place upgrade" solved the issue temoprarily, but the fix did not last two system reboots. Identical problem occured for X410 as well.

As things were working with oldre OS Build `18362.239`, here goes how to revert the OS build (not the "Version"):
![image](https://user-images.githubusercontent.com/5890407/62817417-31b94700-bb04-11e9-818a-65c56a060551.png)
![image](https://user-images.githubusercontent.com/5890407/62817422-4564ad80-bb04-11e9-974a-508274c5fdb4.png)
![image](https://user-images.githubusercontent.com/5890407/62817424-51506f80-bb04-11e9-9054-aef715403f20.png)
In the last step, look for the most recently installed "Upgrade for Microsoft Windows" that matches the time-tag and uninstall it. It takes a while and will restart the PC. Though this is actually a "downgrade", I staill saw a "Windows Updates 30% ..." blue window there.

Note, per my specific fix, I also performed one round of "in-place upgrade" in the beginning (as advised by the Support team). If directly reverting to the previous build did not work, please consider performing such "in-place upgrade".

**Comment by llinfeng** [comment]
Note, I still cannot open Windows Terminal through the Start menu after the "fix". I find the following locations for the executables helpful ==> things do get launched properly when calling the executables alone. And, it did not appear to be a need to cut/copy and paste the entire folder to some other locations.
* For Windows Terminal: `c:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.3.2171.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe`
* For X410: `c:\Program Files\WindowsApps\ChoungNetworksUS.X410_2.6.0.0_x64__vvzc8y2tzcnsr\X410\X410.exe`

I tried to schedule X410 for "start on startup" via the Task scheduler. Feeding the absolute address for the `X410.exe` into the Action tab when configuring the scheduled task got things launched properly. Yet, adding a new string-item to the following registry item did not help launch X410: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`. Same error was raised.

Also, the executables in the `shell:AppsFolder` (run in Run window) also did not work (for both Windows Terminal and X410).
* They won't work by themselves:
![image](https://user-images.githubusercontent.com/5890407/62817609-75618000-bb07-11e9-877e-424ae818f73d.png)
* Nor will a shortcut work: 
![image](https://user-images.githubusercontent.com/5890407/62817590-477c3b80-bb07-11e9-8e3e-403ef23204c1.png)
