### ISSUE TITLE
Cannot open Touch Keyboard in Terminal

### ISSUE THREAD

**Issue by MuscularPuky** [microsoft/terminal#17959]
### Windows Terminal version

1.22.2371.0

### Windows build number

10.0.27694.1

### Other Software

Visual Studio Code
PowerToys Peek

### Steps to reproduce

I have no physical keyboard and Terminal does not let me to open Touch Keyboard
even I touch Terminal onsol Touch Keyboard does not open
even I open Touch Keyboard in other app then focus Terminal Touch Keyboard closes automatically
touching with pen treated as mouse click so just select block... and can't deselect because I have no esc X(

### Expected Behavior

when I touching Terminal consol Touch Keyboard should open

### Actual Behavior

Touch Keyboard does nothing
other apps open Touch Keyboard

**Comment by Nikhil012N** [comment]
Use DISM to Repair the Windows Image
** DISM /Online /Cleanup-Image /RestoreHealth **
Hit Enter. This command checks and repairs your Windows image. Again, it might take some time

**Comment by MuscularPuky** [comment]
> Use DISM to Repair the Windows Image ** DISM /Online /Cleanup-Image /RestoreHealth ** Hit Enter. This command checks and repairs your Windows image. Again, it might take some time

I think it was weird bug. Windows said "This app doesn't support Touch Keyboard. Open On-Screen Keyboard instead?" just like Terminal app is more 20 years old Win32
