### ISSUE TITLE
Cyrillic characters are not pasted correctly when using far2l in WSL under Windows Terminal

### ISSUE THREAD

**Issue by unxed** [microsoft/terminal#17968]
### Windows Terminal version

Windows Terminal Preview v1.22.2702.0

### Steps to reproduce

1. Install Ubuntu 24.04 in WSL
2. Install the [far2l](https://github.com/elfmz/far2l) package
3. Run `far2l` in Windows Terminal
4. Try to paste any Cyrillic text into far2l

### Expected Behavior

Correct text is pasted

### Actual Behavior

No Cyrillic text is pasted

The same operation works ok in GNOME Terminal under plain Ubuntu, for example.

**Comment by DHowett** [comment]
Does it work when you paste into any other application under WSL/?

**Comment by unxed** [comment]
In bash is pasted ok.

But paste in far2l in other terminals (for example, gnome terminal under plain Ubuntu) also works ok

**Comment by unxed** [comment]
This issue is not reproduces in `cmd.exe` console window.

**Comment by o-sdn-o** [comment]
It seems to me that far2l parses the win32-input-mode protocol incorrectly.

For example lets take a charater `й` (UTF-16 decimal code 1081).

Request `win32-input-mode` ussuing `printf "\x1b[?9001h"` at the wsl prompt.

Press/release `й` generates: 1;16;1081;1;0;1_1;16;1081;0;0;1_
Pasting `й` generates: ;0;1081;1;0;1_;0;1081;0;0;1_

In a cmd.exe console window win32-input-mode doesn't work.

**Comment by unxed** [comment]
Thanks for investigating. Trying to fix that.
https://github.com/elfmz/far2l/pull/2401

btw, win32-input-mode seems to be working somehow even in cmd.exe: look at "w" char (after X) in window title. This char is appended on first successfull win32 input mode sequence decoding:
![изображение](https://github.com/user-attachments/assets/4e95d14f-5b0a-418e-8adf-85669879ccac)

**Comment by unxed** [comment]
Closing as problem confirmed on far2l side

**Comment by unxed** [comment]
@ClusterM

Does this bug reproduce for you in far2l from Ubuntu 24.04 repo under latest Windows Terminal Preview version (v1.22.2702.0)?
