### ISSUE TITLE
I can't make it default

### ISSUE THREAD

**Issue by SamtheEevee69** [microsoft/terminal#17974]
### Steps to reproduce

I open settings for the app
And I don't need to do anything to get it happening

### Expected Behavior

The setting to allow Terminal to be real default
And when I type CMD it opens Terminal instead
Like my school windows 10 pc
It is able to do it

### Actual Behavior

I open settings
The default doesn't exist

![image](https://github.com/user-attachments/assets/1df0f3f0-8001-4378-b10e-e3ec655b8532)

**Comment by j4james** [comment]
@SamtheEevee69 If you're using Windows 10, you may still require an update ([KB5026435](https://support.microsoft.com/en-us/topic/may-23-2023-kb5026435-os-build-19045-3031-preview-2751b693-5544-4110-bc0c-feb8dd7336b3)) before you can set the default terminal. It's explained in the discussion here: https://github.com/microsoft/terminal/discussions/15505

Also make sure you've using a recent version of Windows Terminal. It needs to be v1.17 or later.

**Comment by DHowett** [comment]
> ### … version
> 
> _No response_

This is why it is very helpful to know the version numbers!
