### ISSUE TITLE
Can't pass disk root to wt.exe from cmd

### ISSUE THREAD

**Issue by samuraiGH** [microsoft/terminal#17977]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Open `cmd.exe`
2. `wt nt -d "d:\"`

### Actual Behavior

`wt` tries to open `d:"` instead of `d:\`

**Comment by DHowett** [comment]
Due to argument escaping rules, you’ll need to use `"D:\."` or `"D:\\"`

The version with the dot is easier, as it will work reliably with all directories.
