### ISSUE TITLE
Bug Report - Prompt is located nowhere

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1797]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Start Windows Terminal,
Restore Down the terminal,
Open a tab of Ubuntu 18.04,
Allow the prompt to reach the end of the screen,
Maximise the terminal,
Restore Down again,
Maximise the terminal again,
One of the prompts will align right instead of left.

# Expected behavior

1. All the prompts should be aligned left.

# Actual behavior

Screenshot belows show what it looks like:
<img width="960" alt="Bug-report-1" src="https://user-images.githubusercontent.com/50003738/60600360-95a06f80-9de2-11e9-8985-8cd66d8ce03a.png">

**Comment by DHowett-MSFT** [comment]
I think this is just another version of #1465.
