### ISSUE TITLE
Hangs  when opening file selection window for command line in new profile

### ISSUE THREAD

**Issue by aranapatona** [microsoft/terminal#17979]
### Windows Terminal version

1.20.11781.0

### Windows build number

Microsoft Windows [Version 10.0.19045.4894]

### Steps to reproduce

- Open Windows Terminal
- click drop down menu
- select Settings
- select Add new profile (left panel)
- choose a different profile to duplicate
- click Duplicate (right panel)
- click Command Line
- don't edit the path in the provided field, instead select Browse...

the file selection window popup appears but freezes and you cannot input anything, select any file, or cancel and close the popup to return to your terminal session, you need to either wait a LOT of minutes (varies, sometimes returns control after closing some other window, some times it does not come back ever)

### Expected Behavior

Let you chose a file with your mouse or keyboard navigating in the opened file browser popup or type the path in the "Filename:" input box at the bottom of the opened file selection window.

### Actual Behavior

Does not let you type any text in the filename field nor does itlet you choose a file with mouse or keyboard from the file selection window.
The text cursor does blinkbut I cannot type anything.

![DE3x3oC](https://github.com/user-attachments/assets/503a2216-f935-4849-9ba7-4fbefd7799c8)

task manager shows no resources being aggressively consumed
![image](https://github.com/user-attachments/assets/f013f083-7978-4617-b9c3-2ac8dfdf7bef)
![image](https://github.com/user-attachments/assets/6185065b-d9de-4222-a42e-779493e3f788)
![image](https://github.com/user-attachments/assets/08ba8678-a173-4bef-9a7d-4a705e712b12)

**Comment by carlos-zamora** [comment]
Thanks for filing! Yeah, this is a /dup of #12199
