### ISSUE TITLE
Terminal sometimes starts with title bar

### ISSUE THREAD

**Issue by fireattack** [microsoft/terminal#17986]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045.4957

### Steps to reproduce

Sometimes when opening a new Terminal window, it shows with a title bar:

![image](https://github.com/user-attachments/assets/9076eef2-7704-4561-81e2-aede0bc8f3c9)

I don't know why and can't find a way to reproduce it reliably. It just happens from time to time.

### Actual Behavior

Once it happens, any new window would be affected by this too.

The title bar would be gone if I resize the window a little bit in anyway. 

Afterwards, any new window will no longer suffer from the bug until it appears again later.

**Comment by Stranger1298** [comment]
please assign this issue to me

**Comment by DHowett** [comment]
> please assign this issue to me

If you have any ideas about how to fix this, you are welcome to submit a pull request.

**Comment by fireattack** [comment]
I saw that issue, but I didn't change theme. Also forgot to mention, this is a recent regression that only started to appear lately.

**Comment by carlos-zamora** [comment]
> Maybe a duplicate of [#17457](https://github.com/microsoft/terminal/issues/17457)?

Thanks @Strong-pwned! Yeah, we're going to mark this as a /dup of #17457. We think this may be a refrigeration issue.
