### ISSUE TITLE
Dropdown menu ascends to space

### ISSUE THREAD

**Issue by Alouett-e** [microsoft/terminal#17982]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.26100.1882

### Steps to reproduce

- Open a dropdown menu
- Scroll down or up on the main window

https://github.com/user-attachments/assets/803c4b2e-073d-432f-8bc8-2fa5f7c36b1a

### Expected Behavior

There are 3 different behaviours on Windows 11 when a dropdown menu is open

- You can't scroll
- It closes the dropdown menu if you scroll
- It goes to space, this one has been patched in most WinUI3 apps

### Actual Behavior

- It goes to space, this is a regression as this bug was already present and then fixed in previous Terminal versions.

**Comment by carlos-zamora** [comment]
Thanks! This is actually a /dup of #9320 (which links to a WinUI bug).

**Comment by DHowett** [comment]
![Image](https://github.com/user-attachments/assets/11ad61c6-e9c3-46f9-a491-8e41d355279e)
