### ISSUE TITLE
wt.exe can't be launched as Scheduled Task

### ISSUE THREAD

**Issue by JonathanPitre** [microsoft/terminal#17981]
### Windows Terminal version

1.21.2701.0

### Windows build number

10.0.26100.0

### Steps to reproduce

When creating a scheduled task in windows and selecting the program wt.exe you get the following error
![image](https://github.com/user-attachments/assets/6eb7f245-9025-44ff-9f43-04c2a9db168f)

### Actual Behavior

I get this error
![image](https://github.com/user-attachments/assets/daf466fa-45f2-44d3-88d8-fb45a5d4d0e6)

If i type the full path and run the scheduled task, nothing happens. The process is not running.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're tracking this internally on another team with MSFT:44348845. As such, closing.
