### ISSUE TITLE
Unable to change font

### ISSUE THREAD

**Issue by withinboredom** [microsoft/terminal#17987]
### Windows Terminal version

1.22.2702.0

### Windows build number

10.0.22631.0

### Other Software

N/A

### Steps to reproduce

Go to settings, appearance, change font.

### Expected Behavior

The font to change

### Actual Behavior

https://github.com/user-attachments/assets/2c83970d-4b8e-4a73-b2dd-3049d22bda37

The font doesn't save.

**Comment by DHowett** [comment]
Thanks! This regressed in #17961
