### ISSUE TITLE
WSL Terminal: CMD.EXE was started with the above path as the current directory. UNC paths are not supported. 

### ISSUE THREAD

**Issue by siddhsql** [microsoft/terminal#17998]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.4169

### Steps to reproduce

I tried to run `npm run build` from **WSL** home directory and get this error:

```
'\\wsl.localhost\Ubuntu\home\xxx\xxx'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

It then defaults to `c:\Windows` and causes further problems as that is not the right directory.

### Expected Behavior

no error

### Actual Behavior

```
'\\wsl.localhost\Ubuntu\home\xxx\xxx'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

It then defaults to `c:\Windows` and causes further problems as that is not the right directory.

**Comment by DHowett** [comment]
The problem is that your Linux NPM setup is trying to use CMD. Why is that?

**Comment by siddhsql** [comment]
Solved: https://stackoverflow.com/a/75407212/147530

**Comment by DHowett** [comment]
Good find! Thanks for following up.
