### ISSUE TITLE
Bug Report - Weird closure of terminal through closing all the tabs

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1799]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Start Windows Terminal,
Close the terminal through closing the last remaining tab,
The terminal frame remains there for about 4 seconds.

# Expected behavior

1. The terminal should close immediately after the closure of last tab.

# Actual behavior

Screenshot belows show what it looks like:
<img width="832" alt="Bug-report-1" src="https://user-images.githubusercontent.com/50003738/60601731-2a0bd180-9de5-11e9-9f4a-6fd231f062b0.png">

**Comment by zadjii-msft** [comment]
Please [try searching ](https://github.com/microsoft/terminal/issues?utf8=%E2%9C%93&q=is%3Aissue+close+tab+crash+)before filing a new issue.

This is #1445.
