### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bahxkc** [microsoft/terminal#1800]
# Summary of the new feature/enhancement
The title bar should be all in light or dark mode instead of only the tabs' space are applied with themes; also please let the tabs be able to scale to small instead of pushing other tabs into an unseeable area. Please let the tab space that doesn't have tabs be able to move the terminal window instead of only the tiny space of the left side of the close button.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
#1375
