### ISSUE TITLE
Cannot change to new Nerd Font. Choosing new Nerd font does not save.

### ISSUE THREAD

**Issue by ariukkonen** [microsoft/terminal#18016]
### Windows Terminal version

: 1.21.2701.0

### Windows build number

10.0.26100.0

### Other Software

oh-my-posh 23.17.0
Avast Premium Security
[settings.json](https://github.com/user-attachments/files/17302341/settings.json)

### Steps to reproduce

Install IosevkaTerm Nerd Font. Install other Nerd Font like Hack.

Open settings, try to choose Hack Nerd Font and click save. Font change is not saved.

I can change it manually for a profile by editing the settings.json file however and if I choose an non-nerd font and click save, the change will save through the UI.

### Expected Behavior

Install IosevkaTerm Nerd Font. Install other Nerd Font like Hack.

Open settings, try to choose Hack Nerd Font and click save. Font change is not saved. Preview does not change when selecting nother nerd font, only changes when selecting a non-nerd font.

I can change it manually for a profile by editing the settings.json file however and if I choose an 

### Actual Behavior

Selecting another nerd font changes the preview and clicking save changes the saved font for the profile.

**Comment by ariukkonen** [comment]
This was working with previous builds of terminal/windows 11.

**Comment by Constrat** [comment]
It actually looks like you can't change font at all. Not only limited to Nerd Fonts.
Video descripting the issue: https://github.com/user-attachments/assets/96848b70-a170-4f89-ae35-8728ebf362ce

**Comment by lhecker** [comment]
This is a known issue, first reported here: #17987
Because of that we've rolled back the offending change: #17989
Currently I'm redoing the change without the bugs: #18010

Unfortunately, it'll take a little longer for the fix to be released. (@DHowett?)
I'll be closing this issue in the meantime, as it's just pending release. Thank you for the report though!
