### ISSUE TITLE
wsl commands result in lines with carriage returns

### ISSUE THREAD

**Issue by maharris77** [microsoft/terminal#1801]
From PowerShell, running
```
wsl cat file1 > file2
wsl echo text3 > file2
```
results in a file2 with carriage returns. If I am inside WSL-Ubuntu and run the commands (without `wsl`), the resulting file does not have carriage returns, which is the desired behavior.

**Comment by DHowett-MSFT** [comment]
This is because of how powershell handles piping from "native commands". When you use `wsl cat ... > file2`, `cat` is running inside wsl, but `> file2` is being handled by powershell.

File an issue over at [the powershell repository](https://github.com/powershell/powershell)!
