### ISSUE TITLE
There is no option for launching Terminal minimised

### ISSUE THREAD

**Issue by Myron472** [microsoft/terminal#18017]
If I enable Terminal autolaunch on startup, Terminal's windows will **always** be opened. And for now\* there is no option for changing that. Despite this Phone Link app **does** have an option for launching minimized on startup that prevents window from popping up.
I already made [Discussion page](https://github.com/microsoft/terminal/discussions/18011) where I listed all features I would like to see in app but nobody seems to be interested in adding those features. 
However, I think that this is **the most important feature** of what I listed in my Discussion page that should be added - if developers implement it would become much more convinient for me to use Microsoft Terminal.

---

\* - *At the moment of writing this issue*

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #7374
