### ISSUE TITLE
conhost.exe problem with fonts.

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#18024]
I have quite a few fonts in my system.
The problem now is that when using conhost.exe, fonts like Source Code Pro, Lucida Console and even  DejaVuSans, seem to have lost unicode.
None of them show unicode.
I have no idea what happened.

**Comment by lhecker** [comment]
Please provide your Windows version (`winver` command) and screenshots of the issue.

(We have a bug template when you click on "New issue". Please use it when filing issues that you think are bugs. That makes our lives a lot easier. Screenshots also always help us a ton!)

**Comment by 0wwafa** [comment]
> Please provide your Windows version (`winver` command) and screenshots of the issue.
> 
> (We have a bug template when you click on "New issue". Please use it when filing issues that you think are bugs. That makes our lives a lot easier. Screenshots also always help us a ton!)

Microsoft Windows [Version 10.0.19045.5011]

screenshot is useless... unicode character are just displayed as a box or a box with a question mark inside.
the only font where this does not happen is the newly installed "Cascadia" but all old fonts that work in terminal and in any other application, don't work anymore in conhost... I think I am a good programmer but I have no clue of what happened.

**Comment by 0wwafa** [comment]
Cascadia:
![Image](https://github.com/user-attachments/assets/bf48e26b-539e-4b1a-9532-03e41d3428c1)

Consolas (or even Ubuntu or my favourite DejaVu Mono Sans)
![Image](https://github.com/user-attachments/assets/f530ca9c-19c7-489f-8154-d6ee66cad087)

**Comment by 0wwafa** [comment]
The weirdest  thing is that my fonts (Consolas, DejaVu, etc) they all work in other applications...
For example, UltraEdit64 supports unicode and it shows correctly with all those fonts.
It's like  conhost has now some  problem probably related to codepage (but the codepage is set correctly to 65001)

**Comment by 0wwafa** [comment]
The crazy thing is that if I use Cascadia, conhost.exe works:![Image](https://github.com/user-attachments/assets/8fb1bc87-6cdc-4cca-8526-29f29a709db0)

Any other font I tried don't work anymore in pure conhost.

**Comment by 0wwafa** [comment]
Anyway.. I think some microsoft update f*ked up conhost.exe because if I do:

```
i:\OpenConsole.exe wsl
```
Unicode works!

but if I do:
conhost.exe wsl it does not.

![Image](https://github.com/user-attachments/assets/94c4e371-9706-4aba-beb7-1d4de436b1f6)

@lhecker reopen this please. there is a need for a windows update!

**Comment by 0wwafa** [comment]
All the incriminated files are dated:
Friday, ‎June ‎14, ‎2024, ‏‎5:18:03 PM

I am using windows 10 education.

How can I roll back those files??

**Comment by 0wwafa** [comment]
Please tell me how to install conhost.exe system wide (in a way that SFC /scannnow does not overwrite it in the future)

**Comment by lhecker** [comment]
> Anyway.. I think some microsoft update f*ked up conhost.exe because if I do:

Well, you aren't using conhost in that image, you're using OpenConsole and presumably a very recent version of it. That version will work of course, since it will contain #10478. You can't compare that with your system conhost.

> How can I roll back those files??

...put differently: Your conhost is not broken due to a recent update.

> Please tell me how to install conhost.exe system wide (in a way that SFC /scannnow does not overwrite it in the future)

Right now we don't support deploying OpenConsole as a conhost. You can only replace `C:\Windows\System32\conhost.exe` with it, but that will trigger the SFC failure you mentioned. (Note: If you do that, we can't help you if anything breaks. Please make backups.)

Unfortunately, the only way to fix it is to either use Windows Terminal, wezterm (which also includes a modern OpenConsole), or to upgrade to Windows 11 22H2 or newer.

**Comment by 0wwafa** [comment]
> > Anyway.. I think some microsoft update f*ked up conhost.exe because if I do:
> 
> Well, you aren't using conhost in that image, you're using OpenConsole and presumably a very recent version of it. That version will work of course, since it will contain [#10478](https://github.com/microsoft/terminal/pull/10478). You can't compare that with your system conhost which is 5+ years old.
> 

NO. If I do: START >> run >> cmd.exe  the conhost.exe in c:\windows\system32 runs.
And that is flawed and not 5 year old but dated: **Friday, ‎June ‎14, ‎2024, ‏‎5:18:03 PM**

> > How can I roll back those files??
> 
> ...put differently: Your conhost is not broken due to a recent update.

WRONG again. IT IS.

> > Please tell me how to install conhost.exe system wide (in a way that SFC /scannnow does not overwrite it in the future)
> 
> Right now we don't support deploying OpenConsole as a conhost. You can only replace `C:\Windows\System32\conhost.exe` with it, but that will trigger the SFC failure you mentioned. (Note: If you do that, we can't help you if anything breaks. Please make backups.)
> 
> Unfortunately, the only way to fix it is to either use Windows Terminal, wezterm (which also includes a modern OpenConsole), or to upgrade to Windows 11 22H2 or newer.

That's wrong too.
I changed the shortcuts to CMD.EXE and BASH.exe (ubuntu in wsl) to open with openconsole.exe (and not terminal, which *sucks*).
And everything work.

But everything worked also a couple of updates ago.

**Comment by DHowett** [comment]
On the version of Windows you are complaining about, there have been no changes to conhost (the tests commit does not contain conhost changes) since August 2023

![Image](https://github.com/user-attachments/assets/754f0c28-77af-494a-bfd8-12823af2dfa7)

Whatever is happening on your Windows installation is outside the scope of Microsoft's control.
