### ISSUE TITLE
Have a way of actually knowing the geometry of the terminal

### ISSUE THREAD

**Issue by steviator** [microsoft/terminal#18025]
# Description of the new feature/enhancement
A method by which the size of the terminal in rows and columns could be determined after resizing the window or changing font size

# Proposed technical implementation details (optional)
In every other terminal emulator that I have ever used going back to Windows 3.1 there has been some method of determining the Window size of the terminal in use, either by reading something like the title-bar, status bar or a pop-up that appears while resizing the window or by directly forcing the window to a desired geometry using escape codes like Unix, or a command like ms-dos MODE. 

None of these methods work in Windows Terminal and to make matters worse, the window size remains the same if you change the font size, causing the window geometry to change to unknowable values.

For Microsoft to implement one or more of the many established ways of determining the size of a terminal, this isn't rocket surgery. 

Examples: 
* A pop-up that states the window size in rows and columns while resizing
* Optionally displaying the window size in the title
* Supporting escape codes to set the window size in rows and columns
* Supporting the same commands to set the window size as conhost.exe
* Something new and great dreamed up by the Windows Terminal developers

**Comment by j4james** [comment]
> A method by which the size of the terminal in rows and columns could be determined after resizing the window or changing font size

If you mean programmatically, you can query the size with a `CSI 18 t` escape sequence.

> A pop-up that states the window size in rows and columns while resizing

This feature request is tracked in issue #2833.

> Supporting escape codes to set the window size in rows and columns

Support for resizing with a `CSI 8 t` escape sequence was recently added in PR #17721. That functionality should be working in the nightly build. But note that it's only applicable when you have a single tab with a single pane. Other scenarios are tracked in issue #5094.

> Supporting the same commands to set the window size as conhost.exe

That's also tracked in issue #5094.

**Comment by carlos-zamora** [comment]
Thanks for filing! We'll mark this as a /dup of #2833. Thanks for looking into this @j4james 😊
