### ISSUE TITLE
OpenConsole cursor problem

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#18038]
I don't know exactly how to reproduce this but if I run:

```
OpenConsole.exe %windir%\system32\bash.exe ~
```
it "works" but the cursor sometimes is kept in the scroll..

a quick way to show it is to run `top` the quit it...
![Image](https://github.com/user-attachments/assets/e9e51fbe-7d69-4813-b371-49dd1f0e4516)
issuing `reset`  everything is back to normal.

it does not happen **always** but very often.

Important:
if I scroll back and forth, the cursor at the ened of the previous lines (ghost cursor) does not appear, so I think it's a problem of graphic refresh.

**Comment by 0wwafa** [comment]
There is also another minor problem, perhaps I should open a new Issue.
If you scroll up and then type something, the scroll remeains where it is... in conhost the scroll goes to the last visible line if you press a key.

**Comment by lhecker** [comment]
I'm grateful that you're reporting issues, but if you continue filing issues without filling out the bug issue form, I'll start closing them and lock the conversation immediately.

Please write what version of OpenConsole you're using.

**Comment by 0wwafa** [comment]
> I'm grateful that you're reporting issues, but if you continue filing issues without filling out the bug issue form, I'll start closing them and lock the conversation immediately.
> 
> Please tell us what version of OpenConsole you're using.

Sorry for that. I am using the latest: **1.21.2409.26001**

**Comment by lhecker** [comment]
I suspect this is the same as #17310. Could you try OpenConsole 1.22.22409.26002 from the release below? I bet it's fixed there. 🙂
https://github.com/microsoft/terminal/releases/tag/v1.22.2702.0

**Comment by 0wwafa** [comment]
> I suspect this is the same as [#17310](https://github.com/microsoft/terminal/issues/17310). Could you try OpenConsole 1.22.22409.26002 from the release below? I bet it's fixed there. 🙂 https://github.com/microsoft/terminal/releases/tag/v1.22.2702.0

Testing it right now. So far so good.

**Comment by 0wwafa** [comment]
problem still present in latest version ( https://github.com/microsoft/terminal/releases/tag/v1.21.2911.0 )

![Image](https://github.com/user-attachments/assets/9acf6339-0774-46d4-bb02-fd1c77f44257)

not present in version https://github.com/microsoft/terminal/releases/tag/v1.22.2702.0

**Comment by 0wwafa** [comment]
Also not present in version https://github.com/microsoft/terminal/releases/tag/v1.22.2912.0

**Comment by carlos-zamora** [comment]
Thanks for following up. Looks like it was fixed between Stable and Preview. Closing.
