### ISSUE TITLE
Github Copilot ship list

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#18035]
List of todos to complete by the week before Github Universe (10/25/2024)

- [x] #17994
- [x] #17540
- [x] #18014
- [x] #18095 
- [x] #18051

**Comment by htcfreek** [comment]
What is the difference to #15000 and what about 16401?

**Comment by PankajBhojwani** [comment]
> What is the difference to https://github.com/microsoft/terminal/issues/15000

#15000 is more broad, and includes things like adding error handling and potentially future AI providers as well. This issue is specifically to ship Github Copilot support.

> what about https://github.com/microsoft/terminal/issues/16401?

Thanks for that reminder, added
