### ISSUE TITLE
[feature request] OpenConsole.exe as conhost.exe globally (C:\windows\system32\conhost.exe

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#18034]
Since a Microsoft update f*cked up conhost on my system (unicode not shown), I took openconsole.exe and after some manual testing I substituted it to conhost.exe

My system works perfectly (Windows 10 Education).

SO why not release openconsole so that it installs instead of the original conhost?
In that way sfc /scannow will not try to overwrite it and so will DISM.

**Comment by lhecker** [comment]
This is something we've been thinking about doing for a while. Thank you for opening an issue for it.

If you don't mind, though, would you please rephrase your description in a more "professional" way? In our repository you can talk in almost any way you want (= saying "Windows Terminal sucks" is not forbidden, "fuck" does not need to be censored, etc.), but it would make it easier for us to use your issue to track this work. Thanks!

**Comment by 0wwafa** [comment]
Well.. sorry for that but I am fighting with conhost since 2 days.
Apparently it was the last update KB5039211 that messed up things.
It's not conhost itself the problem  because I tryied with the conhost present in windows 10 22H1 ISO, and does the same thing.
So the update changed something "for security" which does not allow conhost to manage all fonts or the codepage.
OpenConsole has some quirks, but it's fast and it works.
I really wonder what happened.
(And obviously at windows 10 end of life).

**Comment by 0wwafa** [comment]
@lhecker update:
I tried from the release page conhost.exe of 2019 and I have the same unicode problem
![Image](https://github.com/user-attachments/assets/ff047042-24d6-4fb8-a223-64e8a4e3424d)
With the version v1.22.2702.0 instead, unicode works but I have some other problems (the one above and a few more).
Is there any way to understand why the original conhost (which worked before the last big windows update) now has problems?

**Comment by lhecker** [comment]
Since you haven't updated the issue description, I've created a more actionable issue for you: #18044
Please fill out the issue template next time. Closing this one.

> Is there any way to understand why the original conhost (which worked before the last big windows update) now has problems?

Definitely not in this issue, since it is about replacing conhost with OpenConsole. We can continue talking about your font issue in one of the other 2 issues that you recently created, for instance #18042.
