### ISSUE TITLE
settings.json schema rejects valid "disabledProfileSources"

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#18037]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19045.4894

### Other Software

VS Code:
```
Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

### Steps to reproduce

Adding "Windows.Terminal.VisualStudio" as "disabledProfileSources" to the settings.json

### Expected Behavior

"Windows.Terminal.VisualStudio" is not marked as wrong.

### Actual Behavior

![Image](https://github.com/user-attachments/assets/e34e6bd1-3f7b-4877-9508-7c9907d9ea69)

**Comment by zadjii-msft** [comment]
> 1.12.10982.0

👀 

you may want to get yourself an updated Terminal build 😝 

That won't necessarily fix this (the schema points at the file in the repo), but still, 1.12 is many years old now.

**Comment by htcfreek** [comment]
Sure. But it won't fix that. The shema is the same (file) for both.
