### ISSUE TITLE
Installation of .msixbundle fails cause Microsoft.UI.Xaml.2.8 is missing

### ISSUE THREAD

**Issue by ChaosBladeCoder** [microsoft/terminal#18033]
### Windows Terminal version

1.21.2701

### Windows build number

10.0.20348.2762 (Windows Server 2022 Standard)

### Other Software

N/A

### Steps to reproduce

1. Downloaded the latest Stable release (1.21.2701) as a .msixbundle.
2. Copied the installer to my **offline** Windows Server 2022 machine
3. Tried to follow the "Other install methods" on https://github.com/microsoft/terminal, specially:
4. Double-clicking the .msixbundle file didn't work, as there was no handler for this file type. Ok, disappointing, but I'll use PowerShell instead.
5. Ran Add-AppxPackage in Powershell 

### Expected Behavior

Bundle should install correctly, including dependencies, without requiring additional downloads .

### Actual Behavior

Add-AppxPackage <package> fails with the following error:

Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency, or conflict validation. Windows cannot install package Microsoft.WindowsTerminal_1.21.2701.0.x64 because this package depends on a framework that could not be found. Provide the framework Microsoft.UI.Xaml.2.8 publiched by [... etc].

**Comment by lhecker** [comment]
@DHowett will have to correct me here, but I believe that Windows Server comes without the necessary XAML dependency. This means you need to use the "PreinstallKit" from our release page. It includes the XAML appx package which you can install before installing our msixbundle.

**Comment by DHowett** [comment]
Yes, fully offline installs need to use the preinstallation/provisioning kit.

**Comment by ChaosBladeCoder** [comment]
Thank you, that is helpful!

However, how is anyone supposed to know this, currently? 

This isn't mentioned _anywhere_ in the installation instructions. I didn't find _any_ specific instructions for fully offline installation, nor is it explained anywhere that the preinstallation/provisition kit can/should be used for this. The [Windows Terminal Distribution Types](https://learn.microsoft.com/en-gb/windows/terminal/distributions) page doesn't mention this. In fact the wording of that page immediately made me disregard this package (especially,  _"Users who do not intend to preinstall Windows Terminal should continue using the Packaged distribution"_). I also looked for words like 'redist', 'redistributable package', which also don't appear anywhere.

It would be helpful to have at least _some_ note about fully offline mode in the installation instructions.

**Comment by DHowett** [comment]
You know, that's fair feedback. Thanks.

**Comment by sqwwwok** [comment]
> Yes, fully offline installs need to use the preinstallation/provisioning kit.

how to use this kit? i cannot find it or its instruction.

**Comment by LtdJorge** [comment]
> > Yes, fully offline installs need to use the preinstallation/provisioning kit.
> 
> how to use this kit? i cannot find it or its instruction.

Just extract the preinstallation kit and `Add-AppxPackage .\Microsoft.UI.Xaml.version_yourarchitecture.appx`.

Then `Add-AppxPackage .\Microsoft.WindowsTerminal...`
