### ISSUE TITLE
Sync SettingsSchema.md with all current settings

### ISSUE THREAD

**Issue by ChaseLandon** [microsoft/terminal#1804]
I am having trouble finding information on what additional profile properties I can use for backgroundImage. Are the properties and values listed some where and I am just over looking it? Basically what I want to find out is if I can control the background, size, location it appears, etc.

Thanks

**Comment by zadjii-msft** [comment]
This info _should_ be in [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#profiles), but I think was added at the same time the doc was. I'm converting this issue into "sync SettingsSchema.md with all current settings".

**Comment by cinnamon-msft** [comment]
I just went through all of the settings and the SettingsSchema.md is up to date.
