### ISSUE TITLE
Drag & Drop Folder to Elevated Terminal Not Working

### ISSUE THREAD

**Issue by arpan3t** [microsoft/terminal#18048]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.19045

### Steps to reproduce

1. Open Windows Terminal as administrator.
2. Open File Explorer (explorer.exe) to a directory that contains a subdirectory.
3. Drag subdirectory from File Explorer to elevated Windows Terminal new tab icon.

### Expected Behavior

New tab using default profile should open with the working directory of the subdirectory that was dragged over, as detailed [here](https://learn.microsoft.com/en-us/windows/terminal/tips-and-tricks#drag-and-drop-filefolder-to-open).

### Actual Behavior

🚫Windows Unavailable mouse pointer icon is displayed, and dropping the folder does nothing.

Tried launching explorer.exe from the same elevated Windows Terminal but get the same results.  Looks like the drag & drop feature only works for non-elevated Windows Terminal processes, which does work in the same environment btw.  Not sure if this is intentional to prevent some sort of privilege escalation scenario or something, but it's not a deal imo.  Just saw the feature in the documentation, but I doubt I'd use it regularly.  Maybe just add a note to the documentation that it only works in non-elevated Windows Terminals.

**Comment by DHowett** [comment]
> Not sure if this is intentional to prevent some sort of privilege escalation scenario or something

This is a Windows platform restriction that is also present in the original console host. The clipboard is the only "approved" way to get content from a medium-integrity process to a high-integrity one on the same Window Station.

We'll add a documentation note! Sorry!

**Comment by c834606877** [comment]
So many users raise issue here, it indicates that this Drag&Drop feature is necessary for daily usage.
So, Please make it as a optional feature for those users want use it at take self own risk way!
Do NOT break the user's usage habits. even you have strong security reason, you can take a msgbox as warning.

**Comment by lhecker** [comment]
There can't possibly be "user's habits" yet, since what you're asking for has never worked on any Windows version before. But we'll definitely take it into consideration for future versions.

**Comment by Quaraxkad** [comment]
> This is a Windows platform restriction that is also present in the original console host. The clipboard is the only "approved" way to get content from a medium-integrity process to a high-integrity one on the same Window Station.

Are you sure that's right? For me, drag+drop of a file or folder does work in normal conhost window but NOT Terminal. Since switching to Terminal as my default i have not been able to drag+drop files or folders to "paste" their paths. I searched and see a lot of posts about similar issues but they're almost all unclear if they're talking about the same feature I am.
