### ISSUE TITLE
Feature Request: Find

### ISSUE THREAD

**Issue by bricelam** [microsoft/terminal#1805]
Windows Console includes the ability to find text. Pressing Ctrl+F opens the Find dialog:

![image](https://user-images.githubusercontent.com/1226749/60613228-57be2f80-9d7f-11e9-8790-c09db5b14ea6.png)

Clicking Find will select the next match of the specified text.

Windows Terminal should include similar functionality.

To go above and beyond, Windows Terminal should implement Find similar to modern web browsers. With a less invasive UI for text entry. And all matches should be highlighted at once.

![image](https://user-images.githubusercontent.com/1226749/60613633-25610200-9d80-11e9-94c0-fa3a2712789a.png)

**Comment by bricelam** [comment]
P.S. This was the missing feature that made me switch back to Windows Console.

**Comment by zadjii-msft** [comment]
This is #605
