### ISSUE TITLE
Opening "elevate-shim.exe" causes Computer to glitch

### ISSUE THREAD

**Issue by Strong-pwned** [microsoft/terminal#18058]
### Windows Terminal version

1.21.2701.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Download the unpackaged Windows Terminal (ZIP file).
2. Extract the folder.
3. In Windows Explorer, double-click on "elevate-shim.exe".
4. In the UAC prompt window, click "Yes" to grant permissions.

### Actual Behavior

1. Windows Terminal window keeps flashing on the screen, quickly/instantly opening and closing.
2. Computer performance is seriously degraded, processor usage skyrockets, including fan speed up.
3. Almost impossible to close Windows Terminal, ALT+F4 keys do not work, Task Manager does not work.
4. Only way to close it is to run cmd as administrator and enter the command `taskkill /im windowsterminal.exe`.

**Comment by DHowett** [comment]
Thanks for filing!

As a note, elevate-shim is an implementation detail. It is not intended to be run directly.

**Comment by Zeroes1** [comment]
@DHowett If a person accidentally launched it, then now he should suffer? :)

**Comment by DHowett** [comment]
Yyyyes? People who launch random EXE files with reckless abandon _can_ learn not to do so! 😁

**Comment by lhecker** [comment]
I suspect this was fixed by #15327 because it fixed the argument passing.

**Comment by Zeroes1** [comment]
@DHowett @lhecker 
>As a note, elevate-shim is an implementation detail. It is not intended to be run directly.

Why not use a file without the EXE extension for this? for example elevate-shim.run ? 
You run elevate-shim with CreateProcessW (no need EXE extension for run)

**Comment by Zeroes1** [comment]
@lhecker 

TEST:
if user manually run elevate-shim.exe

terminal-1.21.2701.0 [latest release] -  problem 
terminal-1.22.2702.0 [latest preview] - no problem
terminal-1.23.2891.0 [latest canary] - no problem

in next release will be OK?

**Comment by lhecker** [comment]
Yeah, sounds like it was fixed in that PR then. Thanks for testing this!

> Why not use a file without the EXE extension for this? for example elevate-shim.run ?

If this issue comes up more often in the future we could explore that idea. 🙂

**Comment by Sinazrp** [comment]
I have same problem and I am in middle of installing something important

**Comment by zadjii-msft** [comment]
A question: why are you directly running `elevate-shim`? It is an internal helper tool. There's literally no reason to run that yourself directly, _right_?

**Comment by Sinazrp** [comment]
Why would a Microsoft-produced application include an executable file that behaves in a way similar to a virus? Why is there an unnecessary .exe file included? I don’t randomly click on executable files, but this is a Microsoft product—I thought we could trust Microsoft. Why is the responsibility being shifted to users instead of addressing this by modifying or removing that .exe file?
