### ISSUE TITLE
Error while building in directory with spaces

### ISSUE THREAD

**Issue by Haaziq386** [microsoft/terminal#18050]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.4317

### Steps to reproduce

Followed the steps for building 
1)cloned the repo in VS 2022
2)ran the git submodules command
3)double tapped OpenConsole.sln file 
4)followed the steps for debugging and after the process got completed it threw me errors

### Expected Behavior

Everything to work fine ig i would be able to start debugging the terminal

### Actual Behavior

![Image](https://github.com/user-attachments/assets/5c28261a-9916-4170-96f8-d9837ab20278)

i got 5 errors (& several warnings)

**Comment by DHowett** [comment]
Ah, this might be an issue with using a path with spaces in it. Can you see if it works in `C:\test`?

**Comment by DHowett** [comment]
Thanks for finding this!

**Comment by Haaziq386** [comment]
> Ah, this might be an issue with using a path with spaces in it. Can you see if it works in `C:\test`?

![Image](https://github.com/user-attachments/assets/9ce29269-2049-40b2-9bc1-98c5e9dce4e7)

still getting the error 

some of the errors is mentioning execution possibly it's related to my execution policy. I checked it is set to restricted

**Comment by carlos-zamora** [comment]
You should be able to change the execution policy via [Set-ExecutionPolicy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.4).

**Comment by Haaziq386** [comment]
@carlos-zamora  actually no i did change my execution policy to remotesigned once and unrestricted later but both still gave the same error(the errors) did not change.
So i tried rebuilding the "OpenConsole" folder but that just gave more errors.
Any solution you know about that can help me with this?
