### ISSUE TITLE
The "X" used to close a tab is too wide.

### ISSUE THREAD

**Issue by destenson** [microsoft/terminal#18060]
### Windows Terminal version

1.20.11781.0

### Steps to reproduce

- Open many tabs and/or make the window "small" (<HD).
- Quickly click other tabs to switch between them repeatedly.
- Accidentally close the tab you're trying to select.

### Expected Behavior

I expect the close button to be harder to accidentally click.

Alternatively, I expect the application to give me the option to cancel accidentally closing the tab I'm trying to select. Clicking close on a tab that is not in the foreground is almost always unintentional.

### Actual Behavior

The "X" region used to close a tab is way too wide, especially when there are many tabs open. The "X" button is 3 times wider than the X icon, and can take 20% or more of the tab's region.

As a result, up to 20% of the time, when selecting a tab, I accidentally close the tab.

**Comment by j4james** [comment]
> Clicking close on a tab that is not in the foreground is almost always unintentional.

In that case, you may find the [Theme Settings](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes) helpful - there's an option you can set so the close button only appears on the active tab, i.e. the one in the foreground (see [Show close button](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes#show-close-button)).

> Alternatively, I expect the application to give me the option to cancel accidentally closing the tab I'm trying to select. 

I believe that feature is being tracked in issue #5301.

**Comment by destenson** [comment]
@j4james, thank you for the info. The themes setting looks like it might work. It's quite inconvenient that can't be changed from the gui, though.

And wrt #5301, that appears to be for showing a cancel dialog if you close the whole window with multiple tabs, not for closing a background tab.

**Comment by carlos-zamora** [comment]
Thanks for filing! #5301 is more about a confirmation dialog when you close _the tab_, not the window. So in your case, it would prevent you from actually closing the tab immediately.

We're going to mark this as a /dup of #5301. Though it's not allowing you to modify the width of the X button, we feel that the combination of the theme setting mentioned above and #5301 should resolve the need for your ask.
