### ISSUE TITLE
Can't download Canary Version

### ISSUE THREAD

**Issue by Zeroes1** [microsoft/terminal#18068]
### Windows Terminal version

WT1.23+

### Steps to reproduce

I try downloading https://aka.ms/terminal-canary-zip-x64
it's redirect to
https://terminalbuilds-grbmacf3f6bsbma8.z01.azurefd.net/nightly/Microsoft.WindowsTerminalCanary_latest_x64.zip

### Expected Behavior

successfull downloading...

### Actual Behavior

return XML:

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>
Public access is not permitted on this storage account. RequestId:954898a1-e01e-00a8-65fd-1f445f000000 Time:2024-10-16T18:59:19.6383023Z
</Message>
</Error>

I try VPN to another country, and the same problem.

**Comment by DHowett** [comment]
We were transitioning our infrastructure, which led to a momentary outage. It once again works:

![Image](https://github.com/user-attachments/assets/882aab91-43fa-4cdf-a3b7-21f7b58b07a4)

(This is the appinstaller XML file. The ZIP is likewise fixed.)
