### ISSUE TITLE
Bug Report : ls (gnuwin32) command cause terminal to shutdown away in CMD window

### ISSUE THREAD

**Issue by f-quintero** [microsoft/terminal#1806]
# Environment
Windows 10 pro
Lenovo T470
GnuWin32 installed
CMD Windows
Windows terminal version: 0.2.1715.0

C:\Users\fabian.quintero>where ls                                                                                       C:\gnuwin32\bin\ls.exe        
C:\Users\fabian.quintero>ls --version
ls (GNU coreutils) 5.3.0
Escrito por Richard Stallman y David MacKenzie.

Copyright (C) 2005 Free Software Foundation, Inc.
Esto es software libre; vea el código fuente para las condiciones de copia.
No hay NINGUNA garantía; ni siquiera de COMERCIABILIDAD o IDONEIDAD PARA UN
FIN DETERMINADO.

C:\gnuwin32\bin is in the PATH environment variable

# Steps to reproduce
1) Start Windows terminal (preview)
  this start on powershell window
2) Start CMD window
3) Close the first powershell window
4) start a new powershell window
5) close the new powershell window
6) on the unique Windows (CMD) run the ls -l commnad
result: Windows Terminal crash

show the debug option. Start debug. This do nos show source. Detailed exption info is;
Excepción no controlada en 0x0000000000000074 en WindowsTerminal.exe: 0xC0000005: Infracción de acceso al ejecutar la ubicación 0x0000000000000074.

ls -l Works fine in others sequence 
# Expected behavior

A normal end of the ls -l command.

# Actual behavior

Described above.

**Comment by DHowett-MSFT** [comment]
Does it happen if you just open and close powershell tabs without running "ls"?

**Comment by f-quintero** [comment]
Hi,

yes, if i run commands in each windows, then when finally i run the LS on the CMD windows this works fine.


________________________________
De: Dustin L. Howett (MSFT) <notifications@github.com>
Enviado: miércoles, 3 de julio de 2019 1:57 p. m.
Para: microsoft/terminal
Cc: f-quintero; Author
Asunto: Re: [microsoft/terminal] Bug Report : ls (gnuwin32) command cause terminal to shutdown away in CMD window (#1806)


Does it happen if you just open and close powershell tabs without running "ls"?

**Comment by JL2210** [comment]
GnuWin32 is ancient and hasn't been updated in a long time.

**Comment by f-quintero** [comment]
Yes it is, i hope final version of Windows Terminal will handle this kind of software in a elegant way, like cmd.exe.



________________________________
De: James Larrowe <notifications@github.com>
Enviado: miércoles, 3 de julio de 2019 2:55 p. m.
Para: microsoft/terminal
Cc: f-quintero; Author
Asunto: Re: [microsoft/terminal] Bug Report : ls (gnuwin32) command cause terminal to shutdown away in CMD window (#1806)


GnuWin32 is ancient and hasn't been updated in a long time.

**Comment by f-quintero** [comment]
Hi,

I get the same result on another computer, with the same software versions. This is a consistent problem.


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: James Larrowe <notifications@github.com>
Enviado: Wednesday, July 3, 2019 2:55:47 PM
Para: microsoft/terminal
Cc: f-quintero; Author
Asunto: Re: [microsoft/terminal] Bug Report : ls (gnuwin32) command cause terminal to shutdown away in CMD window (#1806)


GnuWin32 is ancient and hasn't been updated in a long time.

**Comment by carlos-zamora** [comment]
Hola @f-quintero. Queremos saber si el problema esta relacionado con gnuwin32 o con PowerShell. Sabemos que hay un bug que puede aparecer cuando uno cierra PowerShell (hay un crash :( ). Si no abres/cierras ningún tab con PowerShell, y solamente usas CMD en Windows Terminal, este crash ocurre?

Podrias reproducir este crash en el  _master_ branch, para ver si puedes agarrar un call stack con mas información?

**Comment by f-quintero** [comment]
Hola Carlos, buenos días.

Powershell siempre se abre, así que la prueba solo la puedo hacer con al menos un powershell.

Prueba 1: Powershell abierto (el que abre por default) y ventana CMD.
Paso 1: inicio Terminal Window
Paso 2: inicio CMD window
Paso 3: ejecuto ls -l

Resultado: No ocurre el crash.

Prueba 2: Cierro el primer powershell el que abre por default.
Paso 1: Inicio Terminal Window
Paso 2: inicio CMD window
Paso 3: cierro el powershell por defecto.
Paso 4: Ejecuto ls -l

Resultado: No ocurre el crash.

Prueba 3: Usar el master branch .... No se como hacerlo.
Tengo instalado VS 2017 Community
De donde descargo el master branch?
Que otro requisito debo obtener?

Saludos,




________________________________
De: Carlos Zamora <notifications@github.com>
Enviado: jueves, 11 de julio de 2019 9:56 p. m.
Para: microsoft/terminal
Cc: f-quintero; Mention
Asunto: Re: [microsoft/terminal] Bug Report : ls (gnuwin32) command cause terminal to shutdown away in CMD window (#1806)


Hola @f-quintero<https://github.com/f-quintero>. Queremos saber si el problema esta relacionado con gnuwin32 o con PowerShell. Sabemos que hay un bug que puede aparecer cuando uno cierra PowerShell (hay un crash :( ). Si no abres/cierras ningún tab con PowerShell, y solamente usas CMD en Windows Terminal, este crash ocurre?

Podrias reproducir este crash en el master branch, para ver si puedes agarrar un call stack con mas información?

**Comment by zadjii-msft** [comment]
I'm almost certain this is a dupe of #1445 that's occurring with powershell instead of Ubuntu/WSL. We've seen a bunch of reports of that in various different versions. 

If that's _not_ the issue, we can re-open and try and investigate more.
