### ISSUE TITLE
Preview: Selecting fonts

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#18070]
### Windows Terminal version

1.22.2702.0

### Windows build number

10.0.22635.0

### Other Software

I actually have more than one problem with the font selection in Windows Terminal Preview.

1. When trying to select fonts in Settings -> Profiles: Defaults -> Appearance: Font Face ... it crashes to desktop if I hit "Enter" while _typing in the font selection text box_

2. When typing in the font selection box, if I stop typing and select from the list, and then hit save, it reverts to only the part I typed (and then saves) resulting an error popup that the font doesn't exist.

### Steps to reproduce

1. Open Settings -> Profiles: Defaults -> Appearance ... and click in the Font Face text box, and press Enter.

Then reopen Terminal and try again ... 

1. Type part of a font name in the Font Face box
2. Stop typing and select your font from the list
3. Hit save

### Expected Behavior

I should be able to use my keyboard and mouse together for settings

### Actual Behavior

Terminal crashes and pops up error messages.
Here's a video of the second problem, in case I'm confusing

https://github.com/user-attachments/assets/8c6b5cd9-0c0f-43e0-b87b-b019976ef910

**Comment by lhecker** [comment]
This is a known issue, first reported here: #17987
Because of that we've rolled back the offending change: #17989
Currently I'm redoing the change without the bugs: #18010

Unfortunately, it'll take a little longer for the fix to be released. Thank you for the report though!

**Comment by carlos-zamora** [comment]
Thanks Leonard. We'll mark this as a /dup of #17989
