### ISSUE TITLE
A way to temporarily install dependencies and then have them auto delete after

### ISSUE THREAD

**Issue by RustoMCSpit** [microsoft/terminal#18079]
# Description of the new feature/enhancement

If someone wants to build an app from source, they need dependencies. However, people do not want to clog up their systems with useless dependencies. Having the ability to install a multitude of dependencies and have them auto delete automatically once the terminal is closed would be ideal.

e.g. https://github.com/minetest/minetest/issues/15198#issuecomment-2420730855

# Proposed technical implementation details (optional)

something along the lines of
``` 
sudo apt install -t g++ make libc6-dev cmake libpng-dev libjpeg-dev libxi-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext
```

the terminal would then check which of these are already installed and ignore them, but download those that arent temporarily. you could then close the app and the ones that were downloaded would delete whilst the ones that were already on your system would stay

(i use linux by the way, so the sudo command would be something else)

**Comment by appgurueu** [comment]
This can hardly be and should not be implemented at a terminal level.

**Comment by RustoMCSpit** [comment]
> This can hardly be and should not be implemented at a terminal level.

what repo should i make this issue in then

**Comment by appgurueu** [comment]
> what repo should i make this issue in then

This is essentially package manager responsibility (and thus blends into OS responsibility).

The Nix package manager (and OS) should enable you to do this via environments, for example: https://nixos.org/.

Either way this issue should most probably be closed.

**Comment by DHowett** [comment]
Yup, that's pretty much all that needs to be said here. Thanks!
