### ISSUE TITLE
Incorrect cursor positioning for certain unicode special characters

### ISSUE THREAD

**Issue by jjcarrier** [microsoft/terminal#18088]
### Windows Terminal version

1.21.2701.0

### Windows build number

10.0.22631.0

### Other Software

Also tested on Windows Terminal v1.22.2702.0

### Steps to reproduce

1. Paste the following into the terminal
```pwsh
'✅' | Format-Hex
```
Observe cursor position, then press enter.

2. Paste the following into the terminal
```pwsh
'👨‍👩‍👧‍👦' | Format-Hex
```

### Expected Behavior

1. The cursor position should be immediately following the `x` character.
2. The cursor position should be immediately following the `x` character.

### Actual Behavior

1. The cursor position is off by one and you cannot move the cursor past the `x` character.
2. The cursor position is many characters past where it should be.

**Comment by DHowett** [comment]
Which shell are you using? Do you know whether it supports grapheme clusters?

The shell is unfortunately involved in cursor positioning. If it has an incongruous understanding of the layout of the screen from the terminal it is hosted in, it will tell Terminal the wrong cursor position.

**Comment by jjcarrier** [comment]
> Which shell are you using? Do you know whether it supports grapheme clusters?
> 
> The shell is unfortunately involved in cursor positioning. If it has an incongruous understanding of the layout of the screen from the terminal it is hosted in, it will tell Terminal the wrong cursor position.

I tried this on both PowerShell v7.4.5 and preview v7.5.0

**Comment by lhecker** [comment]
PowerShell indeed does not yet have support for complex graphemes and so it misplaces the cursor. That's not something we can fix on our side, unfortunately.

**Comment by lhecker** [comment]
I'll be closing the issue for now. Let us know if you find any issues with our implementation when used with a shell/application that supports them. You can try cmd.exe, for instance.
