### ISSUE TITLE
Terminal gets messed up when there is grapheme

### ISSUE THREAD

**Issue by cyruspyre** [microsoft/terminal#18082]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Type any grapheme cluster

https://github.com/user-attachments/assets/ef21bd1a-870a-44e9-a03c-ebcf9c832ce9

### Expected Behavior

It should look like this without all the invalid spaces and cursor movement
![Image](https://github.com/user-attachments/assets/57144868-45b8-4d22-aad1-bbb9a98b2a82)

### Actual Behavior

https://github.com/user-attachments/assets/ef21bd1a-870a-44e9-a03c-ebcf9c832ce9

**Comment by DHowett** [comment]
Grapheme cluster support is not present in 1.20! It is available in a newer version of Terminal. You can check the Releases page on this repository to find out more!
