### ISSUE TITLE
Canary installer not working

### ISSUE THREAD

**Issue by flobo09** [microsoft/terminal#18083]
### Windows Terminal version

NA / canary installer

### Windows build number

10.0.26120.2130

### Steps to reproduce

Launch canary installer 
 Add-AppPackage '.\Microsoft.WindowsTerminalCanary.appinstaller'

### Expected Behavior

Terminal Canary get installed

### Actual Behavior

Error message 

PS C:\Users\flo\Downloads> Add-AppPackage '.\Microsoft.WindowsTerminalCanary.appinstaller'
Add-AppxPackage: Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.

Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570.

NOTE: For additional information, look for [ActivityId] 7656e2e2-2235-0007-07c9-62763522db01 in the Event Log or use the command line Get-AppPackageLog -ActivityID 7656e2e2-2235-0007-07c9-62763522db01
PS C:\Users\flo\Downloads> Get-AppPackageLog -ActivityID 7656e2e2-2235-0007-07c9-62763522db01

Time                      ID           Message
----                      --           -------
19/10/2024 5:04:57 PM     603          Started deployment Add operation on a package with main parameter
                                       Microsoft.WindowsTerminalCanary.appinstaller and Options 0 and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
19/10/2024 5:04:57 PM     495          Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed
                                       with error 0x80070570.
19/10/2024 5:04:57 PM     402          error 0x80070570: Reading manifest from location:
                                       Microsoft.WindowsTerminalCanary.appinstaller failed with error: The file or directory is
                                       corrupted and unreadable.
                                       .
19/10/2024 5:04:57 PM     486          AppX Deployment operation failed with error 0x80070490 from API Could not find package name
                                       in path
19/10/2024 5:04:57 PM     404          AppX Deployment operation failed for package  with error 0x80073CF0. The specific error text
                                       for this failure is: Common::Deployment::MsixvcStagingSession::GetManifestReader in
                                       MsixvcStagingSession failed with error 0x80070570.

PS C:\Users\flo\Downloads>

**Comment by flobo09** [comment]
![Image](https://github.com/user-attachments/assets/c64ad12f-4a9b-4805-bea8-d02165780275)

Getting the actual Package from the MainBundle URL and installing it works perfectly though.

**Comment by elsaco** [comment]
I did a quick test by right-clicking and chose open with `App Installer` and it worked okay:

![Image](https://github.com/user-attachments/assets/e420bd78-0d9f-41a7-a836-004d6219e1c5)

However, using the `Add-AppxPackage` is failing:

```
PS C:\Users\elsaco\Downloads> Add-AppxPackage -Path .\Microsoft.WindowsTerminalCanary.appinstaller
Add-AppxPackage: Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.

error 0x8007000D: Opening the package from location Microsoft.WindowsTerminalCanary.appinstaller failed.

NOTE: For additional information, look for [ActivityId] 59848a33-21a8-000c-5cb2-8a59a821db01 in the Event Log or use the command line Get-AppPackageLog -ActivityID 59848a33-21a8-000c-5cb2-8a59a821db01

```

**Comment by DHowett** [comment]
`.appinstaller` XML documents are not intended to be used with `Add-AppxPackage`--only actual package files are supported by that cmdlet.

You'll need to use the App Installer to install `.appinstaller` app installers.

(As a side note: `.appinstaller` documents do not bear a digital signature, but they do point to signed binaries with a strong unforgeable identity so it doesn't really matter.)

**Comment by flobo09** [comment]
@DHowett  : 

It's doing the exact same error clicking on it & using the GUI. 
![Image](https://github.com/user-attachments/assets/1d784c6a-5b0c-4f13-abb1-5bc16d31f97d)


App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)

**Comment by DHowett** [comment]
_Huh_.

**Comment by DrusTheAxe** [comment]
0x80070570 = ERROR_FILE_CORRUPT

Perhaps this is what you meant?
```
Add-AppPackage '.\Microsoft.WindowsTerminalCanary.appinstaller' -AppInstallerFile
```

?

**Comment by elsaco** [comment]
@DrusTheAxe you're correct! `-AppInstallerFile` does the job:

```
PS C:\Users\elsaco> add-appxpackage -AppInstallerFile ".\Downloads\Microsoft.WindowsTerminalCanary.appinstaller"
PS C:\Users\elsaco> $LASTEXITCODE
PS C:\Users\elsaco>
```

No errors!
