### ISSUE TITLE
When you resize the window vertically until the "textbox" area is just not visible and resize back to normal, it can "reset" the console's text (look at image)

### ISSUE THREAD

**Issue by AngryCarrot789** [microsoft/terminal#1809]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
```

# Steps to reproduce
What you do is rapidly resize the height of the terminal's window until the textbox bit of the console disappears (basically so the only thing visible is the top window bar)

# Expected behavior
Normally what should happen is the text shouldn't change at all and should stay the same before resizing.

# Actual behavior
The text keeps "repasting" over and over again. I presume it's to do with the console's text buffer or something. when you resize the window, the text changing at the very top is noticed and the console thinks someone typed something in and because nothing was typed in it's registered as the enter key being clicked. This explains why it repeats `D:\>`.
Before resizing the height:
![image](https://user-images.githubusercontent.com/32274404/60626498-e021ec00-9de2-11e9-96d7-fef9b7974596.png)
After resizing the height quite fast (about 10 times):
![image](https://user-images.githubusercontent.com/32274404/60626553-0e9fc700-9de3-11e9-9d19-82c66f7bbf97.png)

**Comment by DHowett-MSFT** [comment]
#1465
