### ISSUE TITLE
Incorrect portable version for v1.21.2911.0 release

### ISSUE THREAD

**Issue by yavorski** [microsoft/terminal#18098]
### Windows Terminal version

v1.21.2911.0

### Windows build number

10.0.22621.0

### Other Software

Portable version for the mentioned release https://github.com/microsoft/terminal/releases/tag/v1.21.2911.0 is displaying wrong version number 

This one -> https://github.com/microsoft/terminal/releases/download/v1.21.2911.0/Microsoft.WindowsTerminal_1.21.2911.0_x64.zip

This looks like a build date, don't know if this is expected or not?

![Image](https://github.com/user-attachments/assets/957217c9-55a3-4475-a480-0d346b4b4195)

### Steps to reproduce

Run portable x64 version from v1.21.2911.0 release

https://github.com/microsoft/terminal/releases/download/v1.21.2911.0/Microsoft.WindowsTerminal_1.21.2911.0_x64.zip

### Expected Behavior

To show `v1.21.2911.0`

### Actual Behavior

Showing `1.21.241017001`

**Comment by Zeroes1** [comment]
It's allright! 

like:

v1.21.2911.0
it common version

1.21.241017001
it internal version,  show data build 24 - year 10 -month 17 -day 001      

may be guys from Microsoft they will correct me... :)

**Comment by DHowett** [comment]
This version number is already included in the release notes for each build that contains a ZIP distribution of Windows Terminal.

Most people don't need it. It is unnecessary clutter for 98% of the population.

**Comment by DHowett** [comment]
![image](https://github.com/user-attachments/assets/c97e8f2b-051f-4109-9c8a-0abc4c14754b)

**Comment by Zeroes1** [comment]
@DHowett  in bugreport can write only version from about window?

**Comment by DHowett** [comment]
> [@DHowett](https://github.com/DHowett) in bugreport can write only version from about window?

What?

You can write whatever you want in the bug report. We understand the version numbers, so either one is fine.
