### ISSUE TITLE
URL Detection Faulty

### ISSUE THREAD

**Issue by TheUnlimited64** [microsoft/terminal#18099]
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.0

### Other Software

Hey,

the URL detection seems to be a bit buggy in my case its about following example:

`https://foo/bar?foo[bar]=1`

In vscode the whole string is interpreted as an url, but in the Windows terminal only `https://foo/bar?foo` part is recognized as an url

### Steps to reproduce

1. print a link

`echo "https://foo/bar?foo[bar]=1"
`

2. Hover with ctrl over the link

### Expected Behavior

The whole string is interpreted as an url.

### Actual Behavior

If the bracket notation is used, the part after it will get cut off

**Comment by TheUnlimited64** [comment]
It's still not fixed in #8321 but it can be avoided in certain cases with encoded parameters

**Comment by carlos-zamora** [comment]
Thanks! Yeah, the fix would be to have a better regex for URL detection, which is tracked over in #8321. So we're going to mark this as a /dup of #8321 and track that work over there.
