### ISSUE TITLE
In newTabMenu allow assignment/override of the icon property for the action items

### ISSUE THREAD

**Issue by AbraxasDMG** [microsoft/terminal#18103]
### Description of the new feature

Hi.

One small cosmetic suggestion. 

Currently, I can define actions->command which I can then select as the action in newTabMenu.
If I would like to have an icon (or glyph) for that item displayed in the newTabMenu, icon needs to be defined at the level of actions->command. That will result in icon being visible in the command palette as well, which I'd like to avoid (I don't like it visually to have only one or a few items with the icon in a long list of commands).

Would it be possible to have a possibility to define "icon" for newTabMenu action items ("type": "action"). That would allow assignment of desired icons/glyphs to desired commands only in newTabMenu and not in command palette.

Other option would be to have a property on the actions->command item level that would allow for the icon not to be displayed in the command palette (e.g. iconVisibility to have one of the following values: "newtabmenu", "commandpalette", "both", "none").

One more thing that could work is to allow the whole custom command to be excluded from the command palette.

Thank you in advance!

**Comment by zadjii-msft** [comment]
It should totally let you do that! This must have just been overlooked in the initial implementation. 

Something like:

```json
        {
            "type": "action",
            "id": "User.scrollToMark.D3F0B923",
            "icon": "d:\\dev\\public\\terminal\\res\\terminal.ico"
        }
```

should totally work. Thanks for filing!

(We should probably allow that for profile entries too)

**Comment by GeekJosh** [comment]
Hi, I think this would be a really nice feature to add so I have opened a draft PR to implement your suggestion: #18116 

It's in draft right now with just the action entry updated to support custom icons. I will add support for Profile entries too before finalising the PR

**Comment by GeekJosh** [comment]
I have added the ability to override profile icons now too, and opened a PR to update the relevant docs: https://github.com/MicrosoftDocs/terminal/pull/808
