### ISSUE TITLE
Save/Restore settings to cloud/github gist

### ISSUE THREAD

**Issue by SivanagBalla** [microsoft/terminal#18100]
### Description of the new feature

It would be nice feature to be able to Save/Restore settings to cloud/github gist/. I usually have my google drive mirrored locally. So if I can make Terminal to use settings.json in my google drive, then i can sync/restore settings anywhere.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
