### ISSUE TITLE
Pin separate profiles to taskbar like app shortcuts

### ISSUE THREAD

**Issue by AsherCarneiro** [microsoft/terminal#18104]
### Description of the new feature

So i wanted so that i could pin separate profiles for example, i have a ssh profile to a server i login regularly so that instead of going into terminal and making a new tab or even right-clicking the terminal and waiting for the dropdown is sometimes not that smooth for me personally, so i would like so that i could pin profiles to taskbar like they were apps and run them with their specified set of commands.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I'm gonna dupe this over to /dup #8216. That thread covers a lot of the same idea. 

FWIW you could always make a shortcut on the taskbar with a commandline of `wt new-tab -p {the profile you want}`. That would however always spawn a new tab of that profile. 

There's also /dup #12135, for "I want to switch to the most recent window with a given profile"
