### ISSUE TITLE
Setting to show the terminal window on all virtual desktops

### ISSUE THREAD

**Issue by RalfReddings** [microsoft/terminal#18101]
### Description of the new feature

I have a few terminal profiles set up, I would like to set up one or two of these profiles windows on launch, to always show on all desktops.
Currently I am finding myself doing this manually every time after I launch the profiles window:
- Go in to "Task view"
- Right Click the profiles terminal window
- Select "Show window on all desktops"

This is not ideal, some times I even end up launching the same profile across multiple virtual desktops, because I have not realised the profile exists on another virtual desktop.

To that end, I am requesting profile setting that would allow the profiles window to be shown on all virtual desktops.

Lastly, this setting should be available as a flag for the WT cli window, so that new windows can forced to shown on all virtual desktops as well.

Thank you for any consideration on this.

I am on the latest windows terminal / windows 11

**Comment by zadjii-msft** [comment]
I think this is a cool feature request. However: I'm pretty sure there's no APIs for us to control if a window is shown on all virtual desktops or not. We can move it between desktops, but I don't think we can toggle the "show on all desktops" state ourselves. 

Which is a shame - I've personally just resorted to "Show all windows from this app on all desktops", which does seem to persist across reboots. 

If that ever changes and they add an API for that, I'd be happy to revisit

**Comment by RalfReddings** [comment]
Understood, thanks for the expalanation. I quess I will have to cobble something together on my end!
