### ISSUE TITLE
Settings are always saved with command id

### ISSUE THREAD

**Issue by ebarzilay-godaddy** [microsoft/terminal#18111]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.22631.4317

### Steps to reproduce

Making any modification to the settings and saving them adds an `id` field to all actions.

I don't use these IDs yet, and even when I do, then not for all of my actions.

This sounds harmless, but the annoying thing is related to #18110 -- I have a lot of `sendInput` actions (mapping obscure key combos to escape sequences which my environment knows about), and I'm forced to add useless IDs to all of them.

Looks like they're optional -- BUT -- if I drop them, then next time Terminal rewrites my settings, it blesses me with a fresh layer of IDs, and I now need to check the differences and re-remove them.  Since this is tedious and error prone, I'm effectively forced to accept this and add IDs.  Life becomes unnecessarily more verbose with IDs that I'll never need.

### Expected Behavior

No IDs added for actions unless I already had an id for them.

### Actual Behavior

IDs are always added.

**Comment by lhecker** [comment]
We know that this worsens the situation around #18110 and we're hoping to possibly remedy that in the future. To explain, if the settings model was a database, our intention was to "normalize" it, as we wanted multiple key bindings to be able to refer to the same action. In a sense, the action ID we're adding is a foreign key. For what it's worth, you can use arbitrary IDs that you choose yourself.
