### ISSUE TITLE
reload not triggered when profiles.json is a symlink

### ISSUE THREAD

**Issue by newgene** [microsoft/terminal#1812]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
```

# Steps to reproduce

I tried to keep `profiles.json` saved in my OneDrive, so I created a `profiles.json` symlink as the following:

```
DEL /Q %LocalAppData%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json
mklink %LocalAppData%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json %ONEDRIVE%\Windows\conf\WindowsTerminal\profiles.json
```
# Expected behavior
It should work exactly like the actual `profiles.json` file: any modification will trigger the reload of the app.

# Actual behavior
Windows Terminal works fine with the settings loaded from the created symlink, but when I modify the file content, it won't trigger any reload of the Terminal app. I have to close and relaunch the app in order to apply the modified settings.

**Comment by DHowett-MSFT** [comment]
So, here's the weird thing about file modifications. We can't subscribe to know when a file has been changed -- we must subscribe to know when its _directory_ changed. The risk in following the symbolic link is that we will probably start listening for file changes in somewhere crazy (with a high event volume) like the user's home directory. ☹️

**Comment by newgene** [comment]
Understand.

I just gave another try with the "hard link" instead of "symbolic link":

```
mklink /H %LocalAppData%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json %ONEDRIVE%\Windows\conf\WindowsTerminal\profiles.json
```

It works as expected, so it's not an issue for me anymore.
