### ISSUE TITLE
Process exists with code 1 if RDP session closes

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#18123]
### Windows Terminal version

 1.21.2911.0

### Windows build number

 Win32NT             10.0.26100.0 Microsoft Windows NT 10.0.26100.0

### Other Software

I was RDP'd into my work  PC from home and switched focus to an existing Windows Terminal session running on the remote PC.  The session had open tabs, all running powershell and I used a couple of them to issue commands, leaving them all at the prompt.

I put the home machine to sleep without explicitly closing the RDP session.

When I logged into the work PC at work, I discovered that _all_ windows terminal tabs including one I had not used were showing the error 

```
[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```
The screenshot below shows 2 distinct terminal sessions on the same machine.  Every tab within these sessions shows the "process exited" method.

![Image](https://github.com/user-attachments/assets/bf87ba79-5ce9-4468-b796-e76300a08668)

The terminal tab will restart the powershell session if RETURN is pressed....

![Image](https://github.com/user-attachments/assets/b351789f-73a9-4e56-90f7-82551faac502)

### Steps to reproduce

Still investigating.... possibly abnormal disconnect from RDP 

### Expected Behavior

Terminals should not exit processes simply because a remote session is lost.

### Actual Behavior

Processes were exited

**Comment by NeilMacMullen** [comment]
Possibly related 

[#17999 ](https://github.com/microsoft/terminal/issues/17999)

[#16608 ](https://github.com/microsoft/terminal/issues/16608)

**Comment by carlos-zamora** [comment]
Thanks for filing! Could you capture an ETL trace while disconnecting (refer to [this guide](https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capturing-a-debug-etl-trace)) /? That should help us debug this further.
