### ISSUE TITLE
Unable to create a key-binding [ctrl+i] for terminal chat.

### ISSUE THREAD

**Issue by autocloudarc** [microsoft/terminal#18136]
### Steps to reproduce

Configure the key binding for terminal chat as [ctrl]+i

### Expected Behavior

The terminal chat setting should be saved and available when the terminal is opened, and the terminal chat appears. 

### Actual Behavior

Pressing [ctrl+i] doesn't open terminal chat. :-(

**Comment by carlos-zamora** [comment]
Thanks for filing. Some questions from the team:
- Could you share a copy of your settings.json? 
- Could you provide clear repro steps for how you configured the key binding? Via the settings UI or via the JSON /?
