### ISSUE TITLE
Non responsiveness in tabs

### ISSUE THREAD

**Issue by ferjpi** [microsoft/terminal#1813]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.10000]
Windows Terminal version (if applicable): EARLY PREVIEW BUILD

Any other software?
```

# Steps to reproduce

Open multiple tabs in the terminal
# Expected behavior
The tabs resize in that way we can see all the tabs o close one

# Actual behavior

Many tabs open without been possible closed

**Comment by PankajBhojwani** [comment]
I believe this is mentioned in #1375, "When the window is smaller than the sum of the width of the tabs, the tabs are cut off, without indication to scroll".

**Comment by DHowett-MSFT** [comment]
This is actually #857 :smile: Thanks @PankajBhojwani for triaging!
