### ISSUE TITLE
Terminal Window foregrounds other app window before minimize animation could finish

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/terminal#18141]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.26100.2161

### Steps to reproduce

1. Place the Terminal window on top of another app window.
2. Minimize it.

### Expected Behavior

The Terminal window would (animate to) minimize while it's in the foreground

### Actual Behavior

The Terminal window goes in the background and minimizes.

**Comment by tusharsnx** [comment]
https://github.com/user-attachments/assets/3c5eec18-4f42-4252-a5a5-826c076b9a24

**Comment by carlos-zamora** [comment]
Thanks for filing! Does this repro on v1.22 /? We've done some changes to that area and they're available on 1.22.
