### ISSUE TITLE
"Run the profile as Administrator" option not present in Windows Terminal profile settings

### ISSUE THREAD

**Issue by sigshane** [microsoft/terminal#18156]
I am working in a VM with a Windows 11 image that has had a lot of baseline security settings pre-applied. One of those settings seems to be that the Terminal default setting option in the title of this post does not show up in the settings of Windows Terminal - not grayed out, just not there. It is not in Defaults, nor in any of the other profiles below that.

I feel that this has been accomplished via Group Policy, and would like to know what that group policy setting is, so that I can change it. (Yes, I do have permission/authorization to change the setting.)

Thanks in advance,

Shane

**Comment by DHowett** [comment]
I see that you’ve avoided the bug report template. Can you tell us what version of Terminal you’re using?

**Comment by sigshane** [comment]
Oops, I'm new at this! I just copy posted because someone at the Microsoft Community forum just directed me to here. If it would be better I can do the template - where can I find that?

**Comment by DHowett** [comment]
Oh that’s no problem! Sorry about that.

I’ll just ask the relevant template questions.

What version of Terminal? You can find it in the About dialog.

(The other ones aren’t really relevant right now, so I’ll skip em!)

**Comment by sigshane** [comment]
Ahh well, it seems that I blew that VM away a couple of days ago. I apologize for the smoke with no fire.

I will see if I can replicate the problem, then I will report using the proper procedure.

Sorry again, and thanks for the attention.

Shane

**Comment by DHowett** [comment]
Darn! Oh well.

I suspect that it’s due to Windows 11 coming with either Terminal 1.12 or 1.18 (depending on the specific OS version); we hadn’t at that time gotten all of the settings into the UI, even if they were in the JSON schema.
