### ISSUE TITLE
Last window position not remembered if I close the last TAB not the window's X button

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/terminal#18153]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.22631.4317

### Steps to reproduce

If close Windows Terminal normally via the window's "X" button at the top-riught corner - next launch restores window position normally.

However.

If I close Windows Terminal by closing active tabs one by one - next launch the position is random.

### Expected Behavior

Should preserve the last position + size.

### Actual Behavior

Random startup position.

**Comment by carlos-zamora** [comment]
Thanks for filing. We're actually tracking this over in #12633, so we'll mark this as a /dup of #12633.
