### ISSUE TITLE
Auto Reply like VS Code integrated terminal

### ISSUE THREAD

**Issue by balthild** [microsoft/terminal#18155]
### Description of the new feature

Auto replying specific prompts. The integrated terminal in Visual Studio Code has this feature to improve UX for commands invoking `*.cmd` files. The "Terminate batch job (Y/N)" prompt is really annoying.

```json
{
  "terminal.integrated.autoReplies": {
    "Terminate batch job (Y/N)": "Y\r"
  }
}
```

![Image](https://github.com/user-attachments/assets/dad5adab-5d5d-40d0-9012-257a4218205e)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5916 for more discussion.

/dup #5916

(see also #12366)
