### ISSUE TITLE
differnet keyboard shortcuts for different tab switcher interface

### ISSUE THREAD

**Issue by akamienski** [microsoft/terminal#18150]
### Description of the new feature

Basically as title says - I would liek to use tradiitonal navigaiton and with seperate windows tab switcher while using different keyboard shortcuts

### Proposed technical implementation details

By default - ctrl+tab and ctrl+shift+tab switches between opened tabs with the default tab switcher set up, how about ctrl+\` and ctrl+shift+\` or any other shorctut which you can customize to use alternative method. I switch between tabs with ctrl+tab and ctrl+\` by default, as I don't want to hold another key to switch between tabs, I'd just confiogure it in a way, you just hold shift for either key combination (ctrl+shift+tab or ctrl+shift+\`) to switch between tabs with seperate window.

**Comment by DHowett** [comment]
You should be able to do this by adding key bindingslike this to your JSON file (in the `actions` section).

FWIW, this is configured to use <kbd>Ctrl+\`</kbd> for forward motion and <kbd>Ctrl+Shift+\`</kbd> for backward motion in order with no separate window, but you can change the bindings to be whatever you'd like.

```jsonc
// "actions": [
// ...
	{ "command": { "action": "nextTab", "tabSwitcherMode": "disabled" }, "keys": "ctrl+`" },
	{ "command": { "action": "prevTab", "tabSwitcherMode": "disabled" }, "keys": "ctrl+shift+`" },
// ...
// ],
```

You can find more docs about the bindable actions and their options [here](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#open-next-tab).

Does that help/?

**Comment by DHowett** [comment]
Hey, happy to help! Thanks for confirming!
