### ISSUE TITLE
Wrong embedded version in 1.21.2911 msixbundle-package

### ISSUE THREAD

**Issue by BWWIT** [microsoft/terminal#18152]
### Windows Terminal version

1.21.2911.0

### Windows build number

NA

### Other Software

NA

### Steps to reproduce

The x64 version in the msixbundle-package contain version 1.21.2410 and not 1.21.2911
Full package-filename: Microsoft.WindowsTerminal_1.21.2911.0_8wekyb3d8bbwe.msixbundle
![Image](https://github.com/user-attachments/assets/36be8c95-0e47-46be-9638-4746b754bb51)

If you install using Winget you get this msixbundle file

### Actual Behavior

Please bundle the correct version i.e. 1.21.2911

**Comment by DHowett** [comment]
Thanks for filing!

They are the same version. You can confirm that on our [releases page](https://github.com/microsoft/terminal/releases/tag/v1.21.2911.0).

![Image](https://github.com/user-attachments/assets/bddf90b9-53d8-4ea1-8e54-158b136e0e0a)

**Comment by DHowett** [comment]
FWIW, if you are wondering why they're different...

The version resource in the PE files supports using all four version number components--each of which is 16 bits--in which we store Major, Minor, Year, Month, Day and Build Number.

The _Windows Store,_ however, expects the fourth version component to be `0`. The store will reject our updates if we use anything other than `0`.

So, we need to use a _less expressive_ version format for the MSIX bundle than for the DLLs/EXEs inside it. Rather than destroy that useful data, we just let them differ.

**Comment by BWWIT** [comment]
What you say doesn't make sense to me.
The embedded version IS older! And that is plain and simple a mess and goes against all good practice.
Secondly the older embedded version doesn't work, it has the "Faulting module name: ucrtbase.dll...." bug.
In simple words: WT will not work if you install it using winget (at least on some Windows installations)
You have to download the zip file and extract it manually.

**Comment by DHowett** [comment]
> What you say doesn't make sense to me. The embedded version IS older! 

2024-10-17 (the version number in the DLL) is the 291th day of the year (the version number in the package.)

QED.

If you are reporting a crash, please report a crash.

Otherwise: read the release notes, compare the version numbers, and find that they are the same release.

**Comment by DHowett** [comment]
The version downloaded by WinGet is expected to be registered as a store application using the deployment APIs; if you are extracting its contents and running it directly, **it will not work.**

If you want a deployment that can run without deployment API registration, you will need to use the "unpackaged distribution" (ZIP file) in the Releases section.

**Comment by VonC** [comment]
@DHowett Would it be possible for the about screen of an "unpackaged distribution" to *also* display the official public release version number?

In other word, do keep your current  "unpackaged distribution" version number, as you do today.  
But is it possible to add (as a string) in the About screen the other tag, the one listed in GitHub releases?

That way, nobody would have to "read the release notes, compare the version numbers, and find that they are the same release."

**Comment by vefatica** [comment]
What's the meaning/significance of the "2911" in 1.21.2911.0?
