### ISSUE TITLE
Setting startingDirectory on command line for WSL2 Location Windows 11 Ubuntu 24.04 fails

### ISSUE THREAD

**Issue by yorkshire-pudding** [microsoft/terminal#18162]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.22631.4317

### Other Software

Ubuntu 24.04.1 LTS inside WSL2 (2.3.24.0)
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

### Steps to reproduce

1. Create bash script in WSL2 to open a tab at a particular location

```bash
#!/bin/bash
# Create tab for Scripts
cmd.exe /c "wt.exe" \
  --window 0 \
  new-tab --title Scripts --suppressApplicationTitle \
  --profile "Ubuntu" \
  --startingDirectory "$HOME/projects/scripts"
```
2. Run script

I followed these instructions: https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=linux#target-a-directory
which do not give any insight into WSL2 locations.  (Note I prefer to use verbose options in scripts for later readability which is why I have ` --startingDirectory` rather than `-d`)

I also tried:
- `  --startingDirectory "~/projects/scripts"`
- `  --startingDirectory "/home/user/projects/scripts"`
- `  --startingDirectory '\\wsl$\Ubuntu\home\user\projects\scripts'`
- `  --startingDirectory "\\\\wsl.localhost\\Ubuntu\\home\\user\\projects\\scripts"` - this without the escaped `\` is the location I see in Windows Explorer
- `  --startingDirectory "\\wsl.localhost\Ubuntu\home\user\projects\scripts"` - this fails with error:
  -  `[error 2147942667 (0x8007010b) when launching 'ubuntu.exe'] Could not access starting directory 
 C:\wsl.localhost\Ubuntu\home\user\projects\scripts"`

### Expected Behavior

Tab opens at location with title.

This worked in Windows 10 with Ubuntu 20.04 inside WSL2

### Actual Behavior

Tab opens at home location (i.e. `~`) with title

**Comment by carlos-zamora** [comment]
Thanks for filing! This bug has actually been reported before (i.e. [#15827's comment](https://github.com/microsoft/terminal/issues/15827#issuecomment-1677170228)). It's being tracked in #12961 so we'll mark this as a /dup of #12961. However, as a workaround, you can try changing the commandline to `wsl -d Ubuntu-24.04` (or whatever the actual name of the distribution is). That should make startingDirectory work again.

**Comment by yorkshire-pudding** [comment]
@carlos-zamora 
>  However, as a workaround, you can try changing the commandline to `wsl -d Ubuntu-24.04` (or whatever the actual name of the distribution is). That should make startingDirectory work again.

Perhaps I'm being thick, but I can't follow which bit of my script I would add that in or swap.  It would be `wsl -d Ubuntu` but I wasn't aware that that can take a command.  Please can you provide a bit more guidance?

**Comment by DHowett** [comment]
@yorkshire-pudding Sure!

If you go to the Settings inside Terminal _for the Ubuntu 24.04 profile_, you can change the "commandline" that that profile executes.

Right now, it should be set to something like `ubuntu2404.exe`.

Today, our logic that lets you set `startingDirectory` to a _Linux filesystem path_ only works with `wsl.exe` (this is a point of contention, and not an easy fix for either us or Canonical). It can't be applied to `ubuntu2404.exe`.

So if you switch the command line from `ubuntu2404.exe` to `wsl.exe -d DistributionName`, it will keep working (and cut out Ubuntu's bespoke launcher) and gain the ability to use Linux paths as a starting directory.

FWIW, though, you will want to confirm the internal name of the distro as seen by WSL by running `wsl -l`.

**Comment by yorkshire-pudding** [comment]
Thanks @DHowett - that makes sense now and my script is now working again.
Many thanks

**Comment by IlanVivanco** [comment]
> So if you switch the command line from `ubuntu2404.exe` to `wsl.exe -d DistributionName`, it will keep working (and cut out Ubuntu's bespoke launcher) and gain the ability to use Linux paths as a starting directory.

Thanks @DHowett this saved me!
