### ISSUE TITLE
wap packaging: .xbf and .pri generation is not working for us

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1816]
The WAP packaging project, CascadiaPackage, consumes most of its important dependencies transitively. It depends on WindowsTerminal and Host.EXE.

By default, _wapproj_ puts all files collected from a project into a subdirectory _named after_ that project, even if those files were originally from a nested dependency. This includes the `.exe`s.

We've suppressed that behavior so that `WindowsTerminal` and `conhost` can live in the appx package root next to their DLLs.

**We must also do this** so that the `.winmd` -> AppX Manifest generator works right -- if we don't, it will insert references like this:

```xml
<InProcessServer>
  <Path>Whatever.dll</Path>
</InProcessServer>
```

when our directory structure looks like this:

```
WindowsTerminal/Whatever.dll
WindowsTerminal/Whatever.xbf
```

This will fail validation (and activation)! This cannot be fixed, so we stomp the directory for DLL and EXE files.

https://github.com/microsoft/terminal/blob/eae920e5f931d7efd33cc3e1bfb12f8c683b001b/src/cascadia/CascadiaPackage/CascadiaPackage.wapproj#L300-L310

Well, we're also stomping the directory for XBF files. Therefore, `MinMaxCloseControl.xbf` and `App.xbf` end up in the appx root.

This works, because we've overridden their resource locator paths:

https://github.com/microsoft/terminal/blob/eae920e5f931d7efd33cc3e1bfb12f8c683b001b/src/cascadia/TerminalApp/MinMaxCloseControl.cpp#L17-L18

That works great when deployed from Visual Studio. However, _when the project is deployed by MSBuild_ (like in our CI), those loose XBF files are missing. If you look in one of the _PRI_ files, it says that the path is `TerminalApp/MinMaxCloseControl.xbf`.

Well, **that never existed on disk** (see above: _wapproj_ would put it in `WindowsTerminal/MinMaxCloseControl.xbf` because it was a transitive dependency.)

It gets worse. That path would _actually work_ because the XBF file has been merged _into_ the PRI file(!). However, the PRI files from _wapproj_ transitive dependencies _do not get merged into the global `resources.pri`_.

If the transitive dependency PRI files can be merged into `resources.pri`, we can skip overriding the resource loader _and_ remove the loose XBF files from our package.

/cc @metathinker, who originally reported a crash from the CI builds.

**Comment by DHowett-MSFT** [comment]
Oh, also, this results in a crash when you use builds from Azure DevOps or MSBuild. Yeah.

**Comment by metathinker** [comment]
Previous (and occasionally silly) discussion as part of another issue thread: https://github.com/microsoft/terminal/issues/1364#issuecomment-508292860

As Dustin notes above, .appx packages and loose app package layouts with this defect will cause Terminal to crash on startup, as discussed in the other issue thread.

**Comment by DHowett-MSFT** [comment]
I have a terrible idea. I'm going to use my holiday and try to replace the WAP packaging project with a _native UWP project_. Instead of going from EXE to Centennial (which is apparently very hard), why not go from UWP to Centennial (which will probably expose hundreds of other issues, but solve this set of a hundred issues 😁)

**Comment by DHowett-MSFT** [comment]
Everything is terrible! :smile:

|feature|WAP|UAP|
|-|:-:|:-:|
|transitive dependencies|❌<br>(this issue)|✔️|
|PRI merging|❌<br>(this issue)|✔️|
|dependency resources|❌<br>(this issue)|✔️|
|partially works today|✔️|❌<br>(new uncharted unknown)|
|depends on `VCLibs.Desktop`|✔️|❌<br>(this seems hard)|
|intended for this purpose|✔️|❌<br>(throws a warning)|
|can be debugged<br>(with some hoops)|✔️|❌<br>(application thinks it isn't deployed)|
|simpler project structure|❌<br>(one extra project)|✔️|
|isn't a weird .NET project type|❌<br>(this makes debugging annoying)|✔️|
|**likely to ever be fixed**|❌|❌|

**Comment by mdtauk** [comment]
WinUI and XAML Desktop apps - may change all this.  I hope you are sharing your findings and thoughts with that team.

**Comment by DHowett-MSFT** [comment]
@mdtauk not only are we sharing our findings and thoughts with that team, we report to the same engineering manager as that team. :smile:
Unfortunately, that team doesn't own the packaging rules shipped with Visual Studio.

**Comment by mdtauk** [comment]
@DHowett-MSFT  I can only imagine that the VS team, would be developing new compilation and packaging processes, to match the requirements of the frameworks which are to come

**Comment by zadjii-msft** [comment]
IIRC the wsl distro launchers don't use a wapproj, maybe we can use their structure


________________________________

**Comment by DHowett-MSFT** [comment]
|feature|WAP|
|-|-|
|If you add the dependencies directly to the wap project,<br>**they fail with new and interesting _linker_ errors**|✔️|

Yeah, if you add TerminalConnection as a direct dependency to _wapproj_, it has to re-link it during deployment, and it refuses to link in ConTypes.lib.

**Comment by metathinker** [comment]
I can't reopen issues after they have been closed, so paging @DHowett-MSFT:

It looks like the issue wasn't fixed or was reintroduced - I built the current `master` commit 988fe0ba608a3c99f42f2245ce680e535ce6e97a and the crash on startup is back, and occurs at the same place. This time, the resource that failed to load is: `ms-appx:///TerminalApp/TerminalPage.xaml`

**Comment by DHowett-MSFT** [comment]
Yuuuup! #2018 to fix :)
