### ISSUE TITLE
Properly Resizable Tabs

### ISSUE THREAD

**Issue by kilasuit** [microsoft/terminal#18165]
### Description of the new feature

As a user running multiple different open instances of cmdline tools like PowerShell, I set Window Titles for additional visibility in being able to quickly context switch

Currently this is limited by a fixed width for each tab or worse to compact the tabs cutting off vital UI visible space.

I'd rather see tabs be resizable in future

**Comment by zadjii-msft** [comment]
Have you tried setting [`"tabWidthMode": "titleLength"`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#tab-width-mode)/? That sounds like what you're looking for.

**Comment by kilasuit** [comment]
I somehow missed that option! Thanks!
