### ISSUE TITLE
[Interesting Usage] Replace the Windows default conhost.exe to OpenConsole.exe

### ISSUE THREAD

**Issue by YihaoPeng** [microsoft/terminal#1817]
Since Windows Terminal is currently performing poorly in copying and pasting, I think OpenConsole is my better choice.

However, if you do not run it from OpenConsole, Windows will append the default console host (`C:\Windows\System32\conhost.exe`) to all console applications.

Then Microsoft said that the source code of OpenConsole comes from conhost.exe, then can we replace conhost.exe directly with OpenConsole.exe? This way we get a better default console host.

I tried it and it works well. Although OpenConsole is packaged as a UWP application, OpenConsole.exe is actually a normal Win32 window program that can be run by double-clicking its exe. You can find it from `terminal\bin\x64\Release\OpenConsole.exe` if you done a x64 release build.

Then, go to `C:\Windows\System32`, right-click `conhost.exe`, "Properties", and edit the permission list to give the current user the "Full Control" permission.

Then, rename `conhost.exe` to `conhost-old.exe` and copy `OpenConsole.exe` to here and rename it to `conhost.exe`.

Open any console application (powershell, wsl, ...) and enjoy your new console.

**Comment by DHowett-MSFT** [comment]
You found our secret! **We offer no warranty for using openconsole like this!**

**Comment by luke1961** [comment]
Works for me including win 2019 server

**Comment by DHowett-MSFT** [comment]
It _might_ work all the way down to Windows 8.1. Again, no warranty!

**Comment by nu8** [comment]
https://github.com/microsoft/terminal/issues/492

**Comment by NotWearingPants** [comment]
The open issue of this is #492
(for people coming here from search)

**Comment by brian6932** [comment]
A change between these tags has caused this no longer to work https://github.com/microsoft/terminal/compare/v1.17.11391.0...v1.18.1421.0
I get the following error on the newer releases:
![](https://github.com/microsoft/terminal/assets/18603393/8a29b9a3-dde8-4bc7-b6eb-8fb85352345f)

Not sure whether or not this should be made into it's own issue, as it's not a directly supported use-case, but it is one nonetheless.

**Comment by zadjii-msft** [comment]
@brian6932 That can't _possibly_ be the right commit, or at the very least, that's happenstance. The only two code changes in https://github.com/microsoft/terminal/compare/v1.17.11391.0...v1.17.11461.0 are firmly in Terminal-only code. None of that's compiled into OpenConsole.exe at all...

**Comment by brian6932** [comment]
yea it seems odd, but any release after `1.17.11391.0` exhibits this

**Comment by zadjii-msft** [comment]
Glad it went away? 😅

**Comment by YeesterPlus** [comment]
DONE IT
