### ISSUE TITLE
Error 0x80070002 when installing 1.21.2911.0 with winget

### ISSUE THREAD

**Issue by BWWIT** [microsoft/terminal#18170]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.19044.5011

### Other Software

Winget version:
Windows Package Manager v1.9.25180

### Steps to reproduce

winget install Microsoft.WindowsTerminal

### Expected Behavior

No error

### Actual Behavior

![Image](https://github.com/user-attachments/assets/552e77b4-c26d-4dd0-8e5f-4775fbf386c6)
Version 1.22.2912.0 (preview) same issue

**Comment by carlos-zamora** [comment]
Thanks for filing. Looking at #16331, this is being tracked over on the winget repo: https://github.com/microsoft/winget-cli/issues/3166
