### ISSUE TITLE
Terminal crash on start if secondary display is selected as main.

### ISSUE THREAD

**Issue by Dmytro-Shulha** [microsoft/terminal#18187]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.26100.2161

### Other Software

PC:
Asus ROG Zephyrus G14 2022
AMD Ryzen 9 6900HS
AMD Radeon RX 6800S
Windows 11 Pro

Second monitor:
LG UltraGear 27GP850-B

### Steps to reproduce

Connect second monitor (in my case - via DockCase hub with Type-C).

Scenario 1:
Go to Settings > Display > select first monitor as main
Open Terminal (no matter which shell - cmd, powershell, wsl)

Scenario 2:
Go to Settings > Display > select second monitor as main
Open Terminal (no matter which shell - cmd, powershell, wsl)

Scenario 3:
Go to Settings > Display > select first monitor as main
Open Terminal, open several tabs
Go to Settings > Display > select second monitor as main
Back in Terminal, open another tab

### Expected Behavior

Scenario 1:
Terminal opens and works just fine as usual.

Scenario 2:
Terminal opens and works just fine as usual.

Scenario 3:
another tab opens just fine, as usual

### Actual Behavior

Scenario 1:
Terminal opens and works just fine as usual.

Scenario 2:
Terminal opens with black screen, freezes for several seconds, then closes.
An error can be found in Event Viewer:
Log Name:      Application
Source:        Application Error
Date:          13.11.2024 18:07:41
Event ID:      1000
Task Category: Події неполадок застосунків
Level:         Error
Keywords:      
Description:
Ім’я несправної програми: WindowsTerminal.exe, версія: 1.21.2410.17001, позначка часу: 0x67118f02
Ім’я несправного модуля: amdxx64.dll, версія: 31.0.12024.2005, позначка часу: 0x6316d6fc
Код винятку: 0xc0000005
Зміщення помилки: 0x000000000020ef30
Ідентифікатор несправного процесу: 0x34D4
Час запуску несправної програми: 0x1DB35E62199BFE5
Шлях до несправної програми: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.21.2911.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Шлях до несправного модуля: C:\WINDOWS\System32\DriverStore\FileRepository\u0383113.inf_amd64_9242eb4af0e982f6\B383140\amdxx64.dll
Ідентифікатор звіту: 18f07ee5-aaaf-49ff-b9c3-0589b56eb121
Повне ім’я несправного пакета: Microsoft.WindowsTerminal_1.21.2911.0_x64__8wekyb3d8bbwe
Ідентифікатор несправної програми, пов’язаної з пакетом: App
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-11-13T16:07:41.4005736Z" />
    <EventRecordID>5749</EventRecordID>
    <Correlation />
    <Execution ProcessID="5288" ThreadID="3056" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security UserID="S-1-5-21-3257046100-1490035530-2740752173-1001" />
  </System>
  <EventData>
    <Data Name="AppName">WindowsTerminal.exe</Data>
    <Data Name="AppVersion">1.21.2410.17001</Data>
    <Data Name="AppTimeStamp">67118f02</Data>
    <Data Name="ModuleName">amdxx64.dll</Data>
    <Data Name="ModuleVersion">31.0.12024.2005</Data>
    <Data Name="ModuleTimeStamp">6316d6fc</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000000000020ef30</Data>
    <Data Name="ProcessId">0x34d4</Data>
    <Data Name="ProcessCreationTime">0x1db35e62199bfe5</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.21.2911.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\DriverStore\FileRepository\u0383113.inf_amd64_9242eb4af0e982f6\B383140\amdxx64.dll</Data>
    <Data Name="IntegratorReportId">18f07ee5-aaaf-49ff-b9c3-0589b56eb121</Data>
    <Data Name="PackageFullName">Microsoft.WindowsTerminal_1.21.2911.0_x64__8wekyb3d8bbwe</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>
```

Scenario 3:
another tab tries to open, freezes, terminal closes.
same kind of error can be found in Event Viewer.

**Comment by Dmytro-Shulha** [comment]
Following your link and installing new drivers from AMD's website seems to fix that problem, thank you very much!
Before that, I tried to check for updates via Windows Update and via Device Manager, but there were no available updates found.
Again - thank you very much! :)

**Comment by DHowett** [comment]
Thanks for following up! I'm glad it worked out!
