### ISSUE TITLE
Acrylic stopped working

### ISSUE THREAD

**Issue by brunoCCOS** [microsoft/terminal#18189]
### Windows Terminal version

1.21.2911.0

### Windows build number

Win 10 22H2 - 19045.5131

### Steps to reproduce

1. Open windows terminal
2. Go to setting
3. go to profile>appearence
4. turn acrylic on
5. save

### Expected Behavior

The background just starts to be transparent a

### Actual Behavior

I get a solid background color. Notice that transparency works if i disable acrylic 
![Image](https://github.com/user-attachments/assets/16999c10-5547-4d7e-a7bc-1c36680e1ac1)

But with acrylic turned on it just get full solid color

![Image](https://github.com/user-attachments/assets/b45a0c96-2739-41c6-83b4-ba2b95164b6d)

Acrylic was working just until yesterday, i booted the pc today and suddenly does not work anymore. I

This is the settings.json i'm using, in particular the profile "Ubuntu"

{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "id": "User.copy.644BA8F2",
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "id": "User.paste",
            "keys": "ctrl+v"
        },
        {
            "command": "find",
            "id": "User.find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "id": "User.splitPane.A6751878",
            "keys": "alt+shift+d"
        }
    ],
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{4ff56d04-d9cf-57ea-bae2-ad396374e7e3}",
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": 
        {
            "startingDirectory": null
        },
        "list": 
        [
            {
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell",
                "opacity": 71,
                "useAcrylic": true
            },
            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Prompt de comando"
            },
            {
                "guid": "{17bf3de4-5353-5709-bcf9-835bd952a95e}",
                "hidden": true,
                "name": "Ubuntu-22.04",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{8bd89bb2-28eb-5439-a6c3-641b5181fcd3}",
                "hidden": false,
                "name": "Developer Command Prompt for VS 2022",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "guid": "{3b7bcb5c-474f-50ad-b4ce-b4de125e0a50}",
                "hidden": false,
                "name": "Developer PowerShell for VS 2022",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "backgroundImage": null,
                "backgroundImageOpacity": 0.09,
                "colorScheme": "cyberdream",
                "commandline": "wsl -d Ubuntu-22.04",
                "font": 
                {
                    "builtinGlyphs": true,
                    "colorGlyphs": true,
                    "face": "JetBrainsMono Nerd Font Mono"
                },
                "guid": "{4ff56d04-d9cf-57ea-bae2-ad396374e7e3}",
                "hidden": false,
                "name": "Ubuntu",
                "opacity": 77,
                "padding": "5",
                "source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc",
                "startingDirectory": "~",
                "tabTitle": "Ubuntu",
                "useAcrylic": true
            }
        ]
    },
    "rendering.graphicsAPI": "direct3d11",
    "schemes": 
    [
        {
            "background": "#16181A",
            "black": "#16181A",
            "blue": "#5EA1FF",
            "brightBlack": "#3C4048",
            "brightBlue": "#5EA1FF",
            "brightCyan": "#5EF1FF",
            "brightGreen": "#5EFF6C",
            "brightPurple": "#BD5EFF",
            "brightRed": "#FF6E5E",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#F1FF5E",
            "cursorColor": "#FFFFFF",
            "cyan": "#5EF1FF",
            "foreground": "#FFFFFF",
            "green": "#5EFF6C",
            "name": "cyberdream",
            "purple": "#BD5EFF",
            "red": "#FF6E5E",
            "selectionBackground": "#3C4048",
            "white": "#FFFFFF",
            "yellow": "#F1FF5E"
        }
    ],
    "themes": [],
    "useAcrylicInTabRow": true
}

**Comment by zadjii-msft** [comment]
* Are you on battery power/? 
* Are you accessing the machine over RDP?
* is the Windows OS setting "Transparency effects" is turned on (Windows Settings -> Customize -> Colors -> Transparency effects)
* Does HostBackdrop acrylic work in any other apps? (The WinUI 2 Gallery has an example: `winui2gallery://item/Acrylic`)

If acrylic stopped working, it's probably for some reason out of our own control, and there's a lot of things that control if acrylic works or not.

**Comment by toastard** [comment]
I can confirm that I am also experiencing the same issue, which started approximately this month and can be replicated.

The transparency effect functions correctly; however, when acrylic is enabled, it completely disables the transparency effect.

**Environment**
    Windows Terminal version: 1.21.3231.0 (Microsoft Corporation)
    OS Information: Version 10.0.19045 Build 19045

**Are you on battery power/?**
No, I am using a desktop PC in full performance mode.

**Are you accessing the machine over RDP?**
    No, I am using the machine locally.

**is the Windows OS setting "Transparency effects" is turned on (Windows Settings -> Customize -> Colors -> Transparency effects)**
    Yes, "Transparency effects" is enabled (Settings -> Personalization -> Colors -> Transparency effects). I have also run the sfc /scannow command for verification.

**Does HostBackdrop acrylic work in any other apps? (The WinUI 2 Gallery has an example: winui2gallery://item/Acrylic)**
    I am unable to test this currently with the WinUI 2 Gallery (winui2gallery://item/Acrylic).

**Comment by avdaredevil** [comment]
I found that in my case it was related to my computer being in battery/energy saver mode.

Check `Power & battery > System` to see if your machine might have `Energy Saver` turned on!

**Comment by public-space** [comment]
I had the same problem and was super confused. 
With one of the updates in the late winter/early spring I encountered the same issue. 

Somehow Energy Saver Mode got permanently turned on. 
Turning this off got the acrylic to work! 

_(After I spent hours checking my settings all over and trying to configure it. 😅)_

🔋**Check your WiFi/Battery/Audio bar on the far right of your task bar** 
⚡**Turn off Energy Saver!**
💪🏻**Then it should work :)**
