### ISSUE TITLE
Application blocked when using file browser to create a new directory

### ISSUE THREAD

**Issue by Wakotu** [microsoft/terminal#18193]
### Windows Terminal version

1.21.2911.0

### Windows build number

windows 10, 22H2, 19045.5131

### Other Software

wsl2 with ubuntu 22.04 distro

### Steps to reproduce

1. Open windows terminal
2. enter the **settings** tab, select a profile
3. select the **launch directory** entry, and click **Browse** button to enter file browser interface
4. try to create a directory in the browser interface, and block

### Expected Behavior

application do not block

### Actual Behavior

application blocked

**Comment by Astabol** [comment]
Hello @Wakotu, 
Can You please specify:
1. What do you mean by Launch Directory?
2. What is block kindly eloborate.

If possible kindly add video or Screen Shot.

Thanks :)
Pritam

**Comment by Wakotu** [comment]
![Image](https://github.com/user-attachments/assets/76910bde-d323-4887-93fe-f13d6d9ad6e8)
1. the  **launch directory** means the screenshot above. GUI in my system is chinese, so I am not sure about  name of that button in English. Maybe **startup directory** would be the correct one.
2. **Application block** means any GUI operation to windows terminal would not be accepted, including keyboard event to enter name of the new directory.
https://github.com/user-attachments/assets/8e31df56-6ba6-4f90-a37a-d37c8f87c749

**Comment by Wakotu** [comment]
> ![Image](https://github.com/user-attachments/assets/76910bde-d323-4887-93fe-f13d6d9ad6e8)
> 
>     1. the  **launch directory** means the screenshot above. GUI in my system is chinese, so I am not sure about  name of that button in English. Maybe **startup directory** would be the correct one.
> 
>     2. **Application block** means any GUI operation to windows terminal would not be accepted, including keyboard event to enter name of the new directory.
>        https://github.com/user-attachments/assets/8e31df56-6ba6-4f90-a37a-d37c8f87c749

the video is attached through the url at the end.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #17028. There's more information over there about the relevant code and the repro is somewhat similar.
