### ISSUE TITLE
White Square on top left of screen when terminal is used for a long time in windows 11.

### ISSUE THREAD

**Issue by JenuelDev** [microsoft/terminal#18194]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.26100.0

### Other Software

n/a

### Steps to reproduce

Sometimes when opening windows terminal.. While using it for a long time, I see a small white thing on top left of the screen of my laptop. I see this often on 3 computers now.
![Image](https://github.com/user-attachments/assets/ccada1ee-de85-429c-a1d0-feee0d6f5966)

it seems it stays on the edge of the screen even the terminal window is minimized.. this will disappear if I close windows terminal.
![Image](https://github.com/user-attachments/assets/c7eb1316-2b2d-4c80-9dbe-45f7e20b9f97)

### Expected Behavior

I think this might be a UI issue.

### Actual Behavior

This should not show white square on top left edge of the screen when using terminal for long.

**Comment by jiangpengyuan** [comment]
look ugly, but not very urgent issue

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #15219.
