### ISSUE TITLE
The pixel information obtained by `TIOCGWINSZ` is incorrect.

### ISSUE THREAD

**Issue by mikoto2000** [microsoft/terminal#18192]
### Windows Terminal version

1.22.2912.0

### Windows build number

10.0.22631.0

### Other Software

My application.

termsize.c:

```c
#include <fcntl.h>
#include <termios.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/ioctl.h>

void main() {
  struct winsize ws;
  int fd = open("/dev/tty", O_RDONLY);
  if(fd == -1) {
    fprintf(stderr, "Can't open tty");
    return;
  }
  int ret = ioctl(fd, TIOCGWINSZ, &ws);
  close(fd);
  fprintf(stderr, "cols %d rows %d, xpixel %d, ypixel %d.\n", ws.ws_col, ws.ws_row, ws.ws_xpixel, ws.ws_ypixel);
}
```

### Steps to reproduce

1. Run `gcc termsize.c -o termsize && ./termsize`
2. Output stderr `cols 163 rows 60, xpixel 0, ypixel 0.` † xpixel and ypixel is fixed value zero.

(I was recommended to ask here in the comments at https://github.com/microsoft/WSL/issues/12265, so I am asking here as well.)

### Expected Behavior

Output xpixel and ypixel is correct value.

### Actual Behavior

Output xpixel and ypixel is fixed value zero.

**Comment by carlos-zamora** [comment]
Thanks for filing! We're going to mark this as a /dup of #8581
