### ISSUE TITLE
PATH variable not working at all in Terminal

### ISSUE THREAD

**Issue by Mcknight231** [microsoft/terminal#18203]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.22631.4460

### Other Software

The Windows Terminal doesn't seem to be reading the PATH variable. You see, when I add the System32 to the PATH variable it should be working. I added the file path to both User and  System variables. And ive restarted terminal. Any help is appreciated, thank you

### Steps to reproduce

When I type the command "ipconfig" it says it is not recognized as an internal or external command, operable program or batch file.

### Expected Behavior

For the command "ipconfig" to work of course

### Actual Behavior

"ipconfig" is not recognized as an internal or external command,
operable program or batch file.![Image](https://github.com/user-attachments/assets/b00677bb-bee1-4fc1-af2f-e7fb27f70c8c)

**Comment by zadjii-msft** [comment]
You're also _in_ `system32` as your CWD in that screenshot, so CMD shouldn't even need the `PATH` to find it. 

Here's a possibly silly question - is `ipconfig` somehow missing from system32/? 

```
dir c:\windows\system32 | findstr ipconfig
```

should output something like `02/13/2024  01:29 PM            53,248 ipconfig.exe`

**Comment by Mcknight231** [comment]
'findstr' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Mcknight231** [comment]
Idk man, feel like i would either need to reinstall windows or get it fixed

**Comment by Mcknight231** [comment]
Ok I kinda fixed it by pasting the full path of fndstr ![Image](https://github.com/user-attachments/assets/f8b5ec52-ad87-4c4c-843d-894d8e4e3bf2)

**Comment by zadjii-msft** [comment]
Uh okay _what_

what does this dialog look like?

![Image](https://github.com/user-attachments/assets/9aa88045-6055-4bf5-b9e3-35f22651f9f1)


What does `echo %PATH%` emit?

If you hit <kbd>win+R</kbd>, then use the run dialog to launch `conhost.exe`, then run `echo %PATH%`, what does that output/?

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/b4fa410f-6972-4f28-97f7-a6fdfe9b4681)
And here is what CMD echo %PATH% says: C:\Windows\System32\;C:\Program Files\dotnet;C:\HaxeToolkit;C:\Program Files\dotnet\sdk;C:\Windows\System32\;C:\WINDOWS\System32\;C:\Users\tahir\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\tahir\AppData\Local\Programs\oh-my-posh\bin;C:\HaxeToolkit\haxe;C:\HaxeToolkit\neko;C:\HaxeToolkit\haxe\haxelib.exe;C:\Users\tahir\.dotnet\tools;C:\Program Files\mingw64\x86_64-w64-mingw32;C:\HaxeToolkit;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\mingw-64\x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0\mingw64\bin;C:\Program Files\dotnet;C:\Program Files\dotnet\sdk;C:\Windows\System32\;C:\Program Files\dotnet;C:\HaxeToolkit;C:\Program Files\dotnet\sdk;C:\Windows\System32\;C:\WINDOWS\System32\;C:\Users\tahir\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\tahir\AppData\Local\Programs\oh-my-posh\bin;C:\HaxeToolkit\haxe;C:\HaxeToolkit\neko;C:\HaxeToolkit\haxe\haxelib.exe;C:\Users\tahir\.dotnet\tools;C:\Program Files\mingw64\x86_64-w64-mingw32;C:\HaxeToolkit;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\mingw-64\x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0\mingw64\bin;C:\Program Files\dotnet;C:\Program Files\dotnet\sdk;C:\mingw-64\x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0\mingw64\bin;

**Comment by Mcknight231** [comment]
Same, but yeah it's the same in Terminal.

**Comment by o-sdn-o** [comment]
Looks a lot like case sensitivity issues. https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

`test1`:
```
fsutil.exe file queryCaseSensitiveInfo c:\
fsutil.exe file queryCaseSensitiveInfo c:\windows
fsutil.exe file queryCaseSensitiveInfo c:\windows\system32
```

**Comment by Mcknight231** [comment]
Case sensitive attribute on directory C:\ is disabled.
Case sensitive attribute on directory C:\Windows is disabled.
Case sensitive attribute on directory C:\Windows\System32 is disabled.

![Image](https://github.com/user-attachments/assets/5fcb19fd-6fa7-4943-9fc1-3e5d19e2c708)


Is this good or not??

**Comment by o-sdn-o** [comment]
> Is this good or not??

This is okay.

Maybe some registry key is involved.

https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/
```
HKLM\SYSTEM\CurrentControlSet\Services\lxss\DrvFsAllowForceCaseSensitivity
```

https://superuser.com/questions/266110/how-do-you-make-windows-7-fully-case-sensitive-with-respect-to-the-filesystem
```
HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive
```

I think you need to dig in that direction.

**Comment by o-sdn-o** [comment]
Also check the following
```
cd \
cd C:\Windows\System32
ipconfig

```

This will work if it is a case sensitivity issue.

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/18413ad5-dd91-4f28-84bd-e8ae48ecc8e6)
![Image](https://github.com/user-attachments/assets/f3aafa76-40fd-488d-9820-f610796203f1)

Also I've changed casesensitiveinfo to 0 in regedit yet still the same output: ipconfig is not recognized as an internal blah blah blah.

**Comment by o-sdn-o** [comment]
What does the following command output?
```
cd \
cd C:\Windows\System32
ipconfig

```

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/b4e4d2ba-5d61-4d02-9339-7bebb02a6c3b)

Exactly the same

**Comment by o-sdn-o** [comment]
cmd.exe does not distinguish between the case of drive letters and puts the one ordered, and in this situation only capital letters are allowed. It seems that you should change the drive letters to capital letters everywhere in the terminal configs.

**Comment by o-sdn-o** [comment]
So this looks like an issue on the cmd.exe side. They don't check for case when they need to.

**Comment by Mcknight231** [comment]
How should I change the CMD's config files?

**Comment by o-sdn-o** [comment]
All occurrences of "commandline" option in `settings.json` must contain uppercase drive letters in their values.

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/106b378b-0d40-4af0-a9b3-1e7850590a58)
What would it be in this case?

**Comment by o-sdn-o** [comment]
Replace `%Systemroot%` with `C:\Windows`.

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/81c70508-c973-4e1e-bcda-d75b1adcd226)

**Comment by o-sdn-o** [comment]
Sorry, with `C:\\Windows`.

**Comment by Mcknight231** [comment]
Woops figured it out. Do I have to restart my Laptop for it to work? Cause it doesn't right now.

**Comment by o-sdn-o** [comment]
No. It should work instantly. (Just create a new tab with cmd profile)

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/ef076ff7-ee32-4190-9fa3-f39b8f59f2d7)

**Comment by o-sdn-o** [comment]
Could you show the output of the `set` command?

**Comment by o-sdn-o** [comment]
I'm trying to find a way to make my system case-sensitive to reproduce your experience, but so far no success. You have a lowercase drive letter C: coming from somewhere, it’s not clear where it comes from.

**Comment by o-sdn-o** [comment]
Please check the starting directory option
![Image](https://github.com/user-attachments/assets/8cab78f3-6318-4a24-b5a7-f5f4780077fd)

**Comment by Mcknight231** [comment]
Ugh it still doesn't recognize ipconfig

**Comment by Mcknight231** [comment]
Nope. Maybe I should dig around in regedit?

**Comment by o-sdn-o** [comment]
I don't know what else to look at or do. I'm also interested in how to get a system configuration like yours with case-sensitivity in the C drive partition.

**Comment by Mcknight231** [comment]
Should I look somewhere for the system config then? Maybe if I send it you'll look at it, 'cause idk what 2 do anymore.

**Comment by o-sdn-o** [comment]
Maybe it's some side effect of some WSL v1 or v2 setting. Maybe something related to DrvFs or Plan9(P9) protocol setting. As soon as I find something to cling to, I'll write here. Maybe someone else will suggest something.

**Comment by Mcknight231** [comment]
Thanks, I'll keep this issue open just in case.

**Comment by o-sdn-o** [comment]
Are you using WSL? If so, what does `C:\Windows\System32\wsl.exe mount` output? (or `C:\Users\tahir\AppData\Local\Microsoft\WindowsApps\wsl.exe mount`)

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/5e7dff05-5a8c-46f9-8af7-eb4f48b88572)

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/6e558c27-58ef-4186-919d-40b553dd2e1e)
It says I need to install thorugh this command, but uhh, yeah.

**Comment by o-sdn-o** [comment]
Try `C:\Windows\System32\wsl.exe --install`.

**Comment by DHowett** [comment]
If you haven’t installed WSL, don’t. If you haven’t installed it, it isn’t the cause of your issues. It is also not going to help you to diagnose them.

If you launch the original windows console host directly, by running `conhost.exe` with the Run dialog, does the problem persist?

**Comment by o-sdn-o** [comment]
@Mcknight231 Could you run the following?
```
subst c: C:\
```

**Comment by Mcknight231** [comment]
@o-sdn-o same on my end

**Comment by Mcknight231** [comment]
@DHowett Yes, it still persists.

**Comment by o-sdn-o** [comment]
I don't know what to grab onto, but what does the chcp command output?
```
C:\Windows\System32\chcp.com
```

**Comment by Mcknight231** [comment]
Active code page: 850

**Comment by o-sdn-o** [comment]
Note: The `subst.exe` command internally aligns the case of all passed parameters, and this is probably why it didn't work.

**Comment by Mcknight231** [comment]
So what's the solution?

**Comment by o-sdn-o** [comment]
Perhaps we need to find (or make) an analogue of the subst command that will accept parameters without changing their case.

**Comment by Mcknight231** [comment]
Okay, I'll wait for *some* kind of solution then, thanks!

**Comment by o-sdn-o** [comment]
I'll try to make a powershell script that will do this.

**Comment by o-sdn-o** [comment]
Try to run the following powershell script.

- `subst_cs.ps1`:
  ```pwsh
  $win32 = Add-Type -Name WinAPI -PassThru -MemberDefinition @'
  [DllImport("kernel32.dll")] public static extern bool DefineDosDevice(int dwFlags, string lpDeviceName, string lpTargetPath);
  '@
  $rc = $win32::DefineDosDevice(0, "c:", "C:\")
  C:\Windows\System32\cmd.exe /k "dir c:"
  $rc
  ```

**Comment by o-sdn-o** [comment]
Most likely it won't work. Win32 API function DefineDosDevice converts the disk name to uppercase...

**Comment by o-sdn-o** [comment]
What does the command `C:\Windows\System32\mountvol.exe` output?

**Comment by o-sdn-o** [comment]
I have a theoretical suspicion that in your system in the global names section there may be a symlink with a name in the form of a lowercase `c:` along with an uppercase `C:`. This can be inspected using [WinObj](https://learn.microsoft.com/en-us/sysinternals/downloads/winobj). There you can sort by name by clicking on the header of the corresponding column.

![Image](https://github.com/user-attachments/assets/7f20b4e9-8d6f-493b-9126-a6ce4043d4aa)

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/98ac5ac8-2531-43bc-80d9-5d0aece66520)

**Comment by o-sdn-o** [comment]
I found another clue. It may be related to locale. cmd.exe uses `int ::towupper(wint_t c)` function to change the case of drive letter, and the result depends on locale.

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/toupper-toupper-towupper-toupper-l-towupper-l?view=msvc-170
> The case conversion of `towupper` is locale-specific. Only the characters relevant to the current locale are changed in case.

**Comment by DHowett** [comment]
> It is possible that under certain conditions the string `c:\Windows\System32\...` is not converted to the required `C:\Windows\System32\...`

To be honest, CMD has about 500 *million* users. We would have heard about this.

@Mcknight231 would you be willing to install some debugging tools to send us some information? I can try to write them up over the weekend, but the latest I can do it is Monday.

In short, it would be to install Microsoft’s modern Windows Debugger (WinDbg) and recording a Time Travel Trace of CMD.

Install instructions: https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/

If you follow Section 2 of this guide (https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/time-travel-debugging-walkthrough#section-2-record-a-trace-of-the-displaygreeting-sample), but use…

```
Executable: C:\windows\system32\cmd.exe
Arguments: (nothing)
Starting Directory: C:\
```

And then reproduce the bug in the new CMD window after you follow the steps, it will make a huge file called cmd01.run that you can share with us.

Step 7 says to make the app crash, but you can just reproduce your bug and then `exit`!

**Comment by DHowett** [comment]
This will allow a Microsoft engineer, or o-sdn-o, to step through the execution of CMD while it is looking for commands in your `PATH`.

**Comment by o-sdn-o** [comment]
Last question, to satisfy my curiosity please, what does the command output?

```
C:\Windows\System32\systeminfo.exe | C:\Windows\System32\findstr.exe Locale
```

**Comment by Mcknight231** [comment]
c:\Windows\System32>C:\Windows\System32\systeminfo.exe | C:\Windows\System32\findstr.exe Locale
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)

**Comment by o-sdn-o** [comment]
I find another interesting clue. Could you run the following:

```
set PATHEXT=
find
```

- In my setup I see the following:
  ```
  c:\Windows\System32>set PATHEXT="qqq"
  
  c:\Windows\System32>find
  'find' is not recognized as an internal or external command,
  operable program or batch file.
  
  c:\Windows\System32>set PATHEXT=
  
  c:\Windows\System32>find
  FIND: Parameter format not correct
  
  c:\Windows\System32>
  ```

**Comment by Mcknight231** [comment]
c:\Windows\System32>set PATHEXT="qqq"

c:\Windows\System32>find
'find' is not recognized as an internal or external command,
operable program or batch file.

c:\Windows\System32>set PATHTEXT =

c:\Windows\System32>find
'find' is not recognized as an internal or external command,
operable program or batch file.
![Image](https://github.com/user-attachments/assets/14b76f1c-4d81-4f4c-a9c5-fccbb1ac4fea)

**Comment by o-sdn-o** [comment]
No! Please run exactly`set PATHEXT=` (without space before equal)

**Comment by Mcknight231** [comment]
@DHowett i did it aand here it is:https://www.mediafire.com/file/4kxtvhvjec2cn3h/cmd01.run/file

**Comment by Mcknight231** [comment]
@o-sdn-o  ![Image](https://github.com/user-attachments/assets/2761926b-fe08-4086-9e2c-f834b2f145dd)

**Comment by o-sdn-o** [comment]
It seems a cure has been found. Having a `PATHEXT` variable with an incorrect value was apparently the cause of the problems. Just remove it if it is set somewhere.

**Comment by Mcknight231** [comment]
Where the common, idk, locations for the PATHTEXT?

**Comment by Mcknight231** [comment]
Or how can I change the PATHTEXT to be correct>

**Comment by o-sdn-o** [comment]
PATHEXT (not PATHTEXT) search and delete (configure) here
![Image](https://github.com/user-attachments/assets/5f74c222-e2cc-4620-9cdc-763a7353cb45)

**Comment by Mcknight231** [comment]
![Image](https://github.com/user-attachments/assets/b3376612-809a-4e05-adb5-517bffa17edc)

So should I modify it our just completely delete it?

**Comment by Mcknight231** [comment]
OH MY GOD IT WORKED? But how can a variable mess up the commands for CMD? Tysm man!

**Comment by o-sdn-o** [comment]
Default value on Win10
```
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by Mcknight231** [comment]
Huh, okay thanks! Im gonna close this issue now.

**Comment by zadjii-msft** [comment]
Wow I've never heard of `PATHEXT` getting messed up like that before. I'm so glad this got sorted out! Hopefully it should be helpful to future readers too
