### ISSUE TITLE
How can I use the shell integration features with Starship?

### ISSUE THREAD

**Issue by eggbean** [microsoft/terminal#18213]
I use starship on Bash, Z-shell, cmd and PowerShell. I have enabled the shell integration features in my Windows Terminal configuration, but I cannot use them as there is no documentation on how to to use them with starship for all the shells I mentioned.

https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration

https://github.com/starship/starship

**Comment by j4james** [comment]
Starship has an open issue tracking support for shell integration here: https://github.com/starship/starship/issues/5463

**Comment by eggbean** [comment]
@j4james Thanks. I'll have a look at that. I just realised that there are actually some marks on the scrollbar which correspond with the prompt input lines, so it looks like Starship already has built-in support for that part. I just have to figure out how to use it and see what else is involved with shell integration. Cheers.

**Comment by bgshacklett** [comment]
https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory has an example of enabling a subset of integration from Starship, which can likely be extrapolated for further use cases:

```pwsh
function Invoke-Starship-PreCommand {
  $loc = $executionContext.SessionState.Path.CurrentLocation;
  $prompt = "$([char]27)]9;12$([char]7)"
  if ($loc.Provider.Name -eq "FileSystem")
  {
    $prompt += "$([char]27)]9;9;`"$($loc.ProviderPath)`"$([char]27)\"
  }
  $host.ui.Write($prompt)
}
```
