### ISSUE TITLE
Build failing with 17 errors

### ISSUE THREAD

**Issue by ShauryaAg** [microsoft/terminal#1821]

**Comment by zadjii-msft** [comment]
Yea we can't really do anything with that. You're going to have to add more details.

@miniksa I thought we were auto-closing empty issues?

**Comment by miniksa** [comment]
> 
> 
> Yea we can't really do anything with that. You're going to have to add more details.
> 
> @miniksa I thought we were auto-closing empty issues?

Apparently the rule I was using didn't hit for this one. I've changed it to a different rule and we'll see.
