### ISSUE TITLE
Emoji breaks with line breaks

### ISSUE THREAD

**Issue by gcgbarbosa** [microsoft/terminal#18216]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.26100.2033

### Other Software

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Steps to reproduce

1. Write a sentence with an emoji.
2. Resize the window horizontally until you get the same behavior in the image below.

![Image](https://github.com/user-attachments/assets/c1e8451b-c03f-4429-b2a9-165d7e7b077e)

### Expected Behavior

The emoji should be rendered correctly, either on the same line or next line.

### Actual Behavior

 The emoji is not displayed correctly. Half of the emoji is rendered on the same line, and ️the other half is an unrecognized symbol.

**Comment by gcgbarbosa** [comment]
closing. just found #18167

**Comment by DHowett** [comment]
Which emoji is that/?

**Comment by gcgbarbosa** [comment]
☁️
