### ISSUE TITLE
Expanded comboboxes move when you slide the page.

### ISSUE THREAD

**Issue by Goo-aw233** [microsoft/terminal#18212]
### Windows Terminal version

1.23.3191.0

### Windows build number

10.0.27749.1000

### Steps to reproduce

Expand a combo box at random in the settings and slide the page with the mouse wheel to see the expanded combo box move with the scrolling of the page
https://github.com/user-attachments/assets/8cbe2982-7d6b-4aef-911d-4bfc1ca05da8

### Expected Behavior

The combo box should be tucked away automatically, or follow the movement without going beyond the application window

### Actual Behavior

Follow the moving combo box beyond the application window

**Comment by zadjii-msft** [comment]
Thanks for the report! This actually is a recent regression - please refer to #16629 for more discussion.

/dup #16629
