### ISSUE TITLE
The option to start Windows Terminal has disappeared from the right-click menu.

### ISSUE THREAD

**Issue by Cufoon** [microsoft/terminal#18210]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.19045.5131

### Steps to reproduce

The option in the right-click menu has disappeared, and uninstalling and reinstalling did not restore it.

### Actual Behavior

disappear

**Comment by zadjii-msft** [comment]
Here's the dumbest possible solution - does restarting explorer.exe fix it? 

```
taskkill /f /im explorer.exe ; explorer.exe
```

The context menu on Windows 10 is well known to be.... fickle. Are you right clicking on an actually selected folder, or the background of explorer/? (those follow different code paths)

**Comment by Cufoon** [comment]
> Here's the dumbest possible solution - does restarting explorer.exe fix it? 
> 
> ```
> taskkill /f /im explorer.exe ; explorer.exe
> ```
> 
> The context menu on Windows 10 is well known to be.... fickle. Are you right clicking on an actually selected folder, or the background of explorer/? (those follow different code paths)
> 
> 

I had reinstall my system. And I do not think that restart explorer will work, because I have try to restart my pc many times. And in fact, `taskkill /f /im explorer.exe` could not be done, the system denied it.

**Comment by carlos-zamora** [comment]
Looking through the repo, we found this relevant comment: https://github.com/microsoft/terminal/issues/16236#issuecomment-2488757694

We'll mark this as a /dup of #14185.
