### ISSUE TITLE
Running Terminal as admin then locking the screen causes the screen to go black

### ISSUE THREAD

**Issue by nassoor** [microsoft/terminal#18224]
### Windows Terminal version

1.21.3231.0

### Windows build number

26100.2314

### Steps to reproduce

1. log in as standard user
2. launch Terminal as admin
3. lock the screen

### Expected Behavior

To be able to interact with the device 

### Actual Behavior

- the screen goes black except for the mouse pointer in the middle
- ctrl+alt+ delete does nothing
- only solution is to force shutdown

**Comment by carlos-zamora** [comment]
Thanks for filing! Can you try Win+ctrl+shift+b /? This will effectively TDR the graphics driver. So if someone is holding on to the resource, it might lose it.

**Comment by nassoor** [comment]
Invoking Win+ctrl+shift+B did not help. I can see the pointer refreshing but the background is still black.

**Comment by carlos-zamora** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/11050425?s=64&amp;u=8487d9902a1a9d2e56114007729a16b65adaff81&amp;v=4">@carlos-zamora](https://github.com/carlos-zamora) - could this be related to [#18105](https://github.com/microsoft/terminal/issues/18105)? Seems a similar interaction issue.

Good catch! Yeah, I'll mark this as a /dup of #181015 and we'll move the discussion over there. Thanks!

**Comment by woodyinwoodley** [comment]
As the other thread has been blocked, I'll post here. We are told this is down to the accent color in the Windows theme, which is pretty incredible, but whatever. "The right people are working on the problem" in June was the last update. It is now October, no public update to the open P1 bug since then. Can we get an update please?
