### ISSUE TITLE
need change/update history

### ISSUE THREAD

**Issue by HolyChen** [microsoft/terminal#1822]
I found the Windows Terminal (Preview) in Microsoft Store has updated but I cannot find change/update log, so I don't know what's new and which bug has been fixed.

**Comment by DHowett-MSFT** [comment]
The release notes are in the store listing.

**Comment by HolyChen** [comment]
> The release notes are in the store listing.

I'm so sorry, but I am not able to find update notes in the store listing, after I switched language to English even. I think an a web page to list update history may be useful.
![image](https://user-images.githubusercontent.com/8280605/60699722-cb02a580-9f27-11e9-96a2-60ac87eb93a6.png)
![image](https://user-images.githubusercontent.com/8280605/60699772-f1c0dc00-9f27-11e9-9b3a-8af34856d915.png)

**Comment by j4james** [comment]
@HolyChen That looks like it might be a Microsoft Store bug of some sort. I can definitely see a _What's new in this version_ section before the _Additional information_. And for me the _Screenshots_ come before the _People also like_ section. I guess your version of the store uses a different layout that doesn't include the _What's new_ section.

In any event, you should still able to see the _What's new_ section on the web version of the store. Try this link: [Windows Terminal (Preview)](https://www.microsoft.com/p/windows-terminal-preview/9n0dx20hk701)
