### ISSUE TITLE
open JSON settings file with default type association instead of notepad

### ISSUE THREAD

**Issue by AQFChristel** [microsoft/terminal#18230]
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.22631.0

### Other Software

please open the JSON settings file with the associated default app instead of notepad

### Steps to reproduce

open terminal, open settings, click on the "Open JSON file" label

### Expected Behavior

having the default associated app open the JSON file

### Actual Behavior

notepad opening the JSON settings file

**Comment by lhecker** [comment]
If it opens in Notepad, then Notepad _is_ your default associated application. To change it, press Win+R and execute `ms-settings:defaultapps`. TThere, you can search your favorite text editor and associate .json with it. Please let me know if that works for you.

**Comment by AQFChristel** [comment]
OMG, I'm so sorry, it is because I forgot I was running terminal as administrator and I haven't set any associations for that separate account, please ignore my message

**Comment by lhecker** [comment]
All good! Thanks for letting us know.
