### ISSUE TITLE
Ability to Automatically Switch Terminal Pane Color Scheme Based on Terminal Theme Setting

### ISSUE THREAD

**Issue by cpAtor** [microsoft/terminal#18236]
### Description of the new feature

I would like to request a feature that allows users to assign both a light and dark color scheme to the terminal panes in Windows Terminal. 
Depending on the terminal's theme setting, the pane's color scheme should automatically switch between the light and dark themes. 
This would enhance the user experience by providing a seamless transition between themes and improving readability under different lighting conditions.

This feature would greatly improve the usability of Windows Terminal, especially for users who frequently switch between light and dark themes.

## Key features:

- Allow users to specify a light color scheme and a dark color scheme for terminal panes.
- Automatically switch the pane's color scheme based on the terminal's theme setting.
- Ensure that the transition between light and dark themes is smooth and visually appealing.
- Provide options to customize the light and dark color schemes to fit individual preferences.

**Comment by zadjii-msft** [comment]
Thanks for the request! This is actually already possible. See: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme

```json
"colorScheme":
{
    "light": "One Half Light",
    "dark": "One Half Dark",
},
```

It's not in the UI yet, that's tracked in #16984
