### ISSUE TITLE
Windows Update breaks Windows Terminal due to Windows App SDK issue

### ISSUE THREAD

**Issue by ClausAndersen** [microsoft/terminal#18237]
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.19045.5131

### Other Software

Windows App SDK 1.6.3

### Steps to reproduce

TLDR; Windows Terminal **broken due to Windows update**. This update caused issues with Windows App SDK 1.6.2. This update was pulled but damage had already been done. The temporary fix for that is to update to Windows App SDK 1.6.3. This however leaves Windows Terminal MSIX bundle broken. Installing the latest avaialbe bundle will fail most likely because "WindowsAppSDKSelfContained=true" in the bundle.

Long version:

Windows Terminal stopped working for me after a reboot due to Windows update. At first I simply tried to uninstall it with the intent of re-installing.

This gave me the error 0x80073CFA which led me to a currently ongoing Windows App SDK issue:
https://github.com/microsoft/WindowsAppSDK/issues/4881

I did the manual fix and do now have Windows App SDK 1.6.3

This does however give me a problem when I try to install the latest MSIX bundle:

    Microsoft.WindowsTerminal_1.21.3231.0_8wekyb3d8bbwe.msixbundle

This gives the localized error:

    Pakken kan ikke installeres, fordi der allerede er installeret en højere version af denne pakke.

Which roughly translates to:

    Package cannot be installed, as there is already a newer version of this package.

From the linked Windows App SDK issue this seem to be the problem if you are using self-contained bundles:

    WindowsAppSDKSelfContained=true

And it would be worth examining if it is worth having native AOT on.

The system:
Windows 10 22H2
Build 19045.5131
Microsoft.WindowsTerminal_1.21.3231.0_8wekyb3d8bbwe.msixbundle (latest)
Windows App SDK 1.6.3

I think it would be very helpful to the community if a new release was built with SDK 1.6.3 as we now have a lot of breakage in the wild. I do not dare to submit a pull request for this as this will no doubt create a lot of bike shedding. But I think a new build using latest SDK would be most helpful middle of the road quickfix.

### Expected Behavior

Being able to install latest Windows Terminal MSIX bundle on a up-to-date Windows 10 installation.

### Actual Behavior

Installation reports a newer version is installed/available even though "Terminal" is no longer listed as an installed application and the latest version is used.

![Image](https://github.com/user-attachments/assets/eb600c94-e191-4c06-9d6d-04e333bf3bf5)

**Comment by Archomeda** [comment]
I think I'm hitting the same issue, I cannot even uninstall Windows Terminal via PowerShell. It gives me 0x80073CFA as error.
Right now I can't install, reinstall, remove or boot up Windows Terminal. It's completely unusable.

**Comment by ClausAndersen** [comment]
>  It gives me 0x80073CFA as error. 

If you go to SDK 1.6.3 you should be able to uninstall. For me I could not install it again after but others have reported success. YMMV.

**Comment by Archomeda** [comment]
Aha, I got it to reinstall and work again. But now I've lost all my settings 😂

**Comment by ClausAndersen** [comment]
> Thanks for surfacing this! Terminal actually doesn’t use WinAppSDK at all, neither self-contained nor systemwide. However, it will still be impacted by the WinAppSDK issue.

Oh! Cool. Thanks for responding anyway.

> If you use `Add-AppxPackage` with the `-AllowUpgradeFromAnyVersion` flag, it should let you reinstall the latest version.

Does not work. That flag is not listed with `-?` but I then found `-ForceUpdateFromAnyVersion` which did the job for me!

    Add-AppxPackage Microsoft.WindowsTerminal_1.21.3231.0_8wekyb3d8bbwe.msixbundle -ForceUpdateFromAnyVersion

This will work from Windows Powershell and not Powershell 7.

So everything works as it is supposed to do. Thanks!

**Comment by DHowett** [comment]
You're totally right, and I misremembered the name of the arg. I'm glad it worked!

**Comment by carlos-zamora** [comment]
This should now be fixed. Thanks for reporting it!
