### ISSUE TITLE
Skewed vertical box lines displayed in Far Manager

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#18247]
### Windows Terminal version

1.22.3232.0

### Windows build number

10.0.19045.0

### Other Software

Far Manager 3.0.6364.0 x64

### Steps to reproduce

Open a directory in the left panel of `Far Manager` with some Russian-named files there.

### Expected Behavior

No skewed surrounding boxes displayed anywhere.

An example from `conhost.exe`:

![Image](https://github.com/user-attachments/assets/1df5b720-f562-4263-a5d3-e4396573d9c3)

### Actual Behavior

On the rows where the Russian-named files are, the vertical box drawing lines are shifted left. The characters used to draw the given lines are Unicode `Box Drawings Double Vertical` encoded as `U+2551`.

Example:

![Image](https://github.com/user-attachments/assets/a4427a31-bac8-4e79-83df-91264c97fe55)

NOTE: I have not seen that issue in the previous versions (e.g. 1.21.3231.0) of the Terminal. It might be related to some new setting introduced in the Preview release, but I am not sure.

**Comment by DHowett** [comment]
![Image](https://github.com/user-attachments/assets/7ceb7987-2b70-46c7-bec8-80aa70e13f14)


This is highly unusual. Two files with the same display name?

Is there a chance you have decomposed and composed character versions of the same filename in that folder?

Decomposed (or composed, I guess) characters will have different measurement outcomes on 1.22+.

**Comment by vblazhkun** [comment]
> ![Image](https://github.com/user-attachments/assets/7ceb7987-2b70-46c7-bec8-80aa70e13f14)
> 
> This is highly unusual. Two files with the same display name?
> 
> Is there a chance you have decomposed and composed character versions of the same filename in that folder?
> 
> Decomposed (or composed, I guess) characters will have different measurement outcomes on 1.22+.

The filenames are actually different (see the attached hex dump):

![Image](https://github.com/user-attachments/assets/82421e46-8b41-46ff-b3cd-f2d9435445e5)

1. `d0 93 d1 80 d1 83 d0 bf d0 bf d0 be d0 b2 d0 b0 d1 8f 20 d0 bf d0 b5 d1 87 d0 b0 d1 82 d1 8c 20 d0 b2 d1 8b d0 b1 d1 80 d0 b0 d0 bd d0 bd d1 8b d1 85 20 d0 b7 d0 b0 d0 bf d0 b8 d1 81 d0 b5 d0 b8 cc 86 31 20 28 31 29 2e 70 64 66 0a`
2. `d0 93 d1 80 d1 83 d0 bf d0 bf d0 be d0 b2 d0 b0 d1 8f 20 d0 bf d0 b5 d1 87 d0 b0 d1 82 d1 8c 20 d0 b2 d1 8b d0 b1 d1 80 d0 b0 d0 bd d0 bd d1 8b d1 85 20 d0 b7 d0 b0 d0 bf d0 b8 d1 81 d0 b5 d0 b9 31 20 28 31 29 2e 70 64 66 0a`

**Comment by vblazhkun** [comment]
And the diff:

![Image](https://github.com/user-attachments/assets/880b3795-6085-43c1-9cab-56ea9043f6be)

**Comment by o-sdn-o** [comment]
- https://habr.com/en/articles/262679/
- And it looks like FarManager is not measuring grapheme clusters correctly.

**Comment by vblazhkun** [comment]
Another observation: `U+0306` somehow eats the space on the **right** and the space pops-up when I add any character on the **left**:

![Image](https://github.com/user-attachments/assets/e689e0ac-eedd-4645-b49b-dbfe24851845)

**Comment by Zeroes1** [comment]
@o-sdn-o Far Manager dont support grapheme now (it's may be later)

@vblazhkun Я надеюсь у вас выставлена эта опция в настройках?

![Image](https://github.com/user-attachments/assets/07981dcf-0633-4a20-aa15-695d480517d1)

@DHowett It's possible force set English lang interface of WT? not from regional settins from OS?

**Comment by DHowett** [comment]
> @DHowett It's possible force set English lang interface of WT? not get from regional settins from OS?

Yes. It is in the Appearance page if you are using the MSIX version.

**Comment by Zeroes1** [comment]
@DHowett   need close ticket? It's only Far Manager issue. There is a current solution to the problem.

**Comment by Zeroes1** [comment]
Main developper FAR Manager add PR
"Warn the user when the terminal uses grapheme clusters"

**Comment by lhecker** [comment]
For reference: https://github.com/FarGroup/FarManager/commit/2fe2415a400e7a7888c3f8df633cbaed680937fc
I'm glad now that I added the "text measurement mode" switch with all 3 variants. 😰

**Comment by Zeroes1** [comment]
Far Manager show warning only in this case:
in Windows Terminal ON option use grapheme clusters (default)
and in Far Manager activate option  [x] Fullwidth-aware rendering

**Comment by carlos-zamora** [comment]
Closing since this was an issue on the Far Manager side and they have a fix for it.
