### ISSUE TITLE
Pulsing Text

### ISSUE THREAD

**Issue by sigmaprojects** [microsoft/terminal#18245]
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Open Terminal

### Expected Behavior

Not pulsing

### Actual Behavior

![Image](https://github.com/user-attachments/assets/375d3605-041a-40c1-9c82-4e86e576e958)
Not sure what causes this, but turning on Software Rendering stops the pulsing text.  Terminal is the only application this happens with, regular PS, CMD, WSL, etc all work fine.
nvidia 3060 with latest drivers

**Comment by sigmaprojects** [comment]
I forgot to note: The pulsing stops while the window loses focus.

**Comment by lhecker** [comment]
Well, that's odd. Can you please do the following?
* Update to the latest drivers:
  * Regular (recommended): https://www.nvidia.com/en-us/drivers/details/235904/
  * For improved stability: https://www.nvidia.com/en-us/drivers/details/235906/
* Reboot
* Make a screen recording. I can recommend:
  * Simple: https://github.com/mmozeiko/wcap
  * More powerful: https://getsharex.com/
  * Built into Windows: Search for "Snipping Tool"

**Comment by sigmaprojects** [comment]
Good news.  I've narrowed the problem to an... incompatibility? with Wallpaper Engine. 

As I was preparing to take more recordings, I maximized a explorer window to use as a background and the pulsing text stopped.  
Doing that paused Wallpaper Engine animations, for whatever reason it interferes with Terminal.

**Comment by DHowett** [comment]
Thanks for digging in more! I wonder what's up with that... and if there's anything we can do about it.
