### ISSUE TITLE
NON-wrapping double-height lines start inserting whitespace when within ≈7 chars of the edge of the screen❓

### ISSUE THREAD

**Issue by ClaireCJS** [microsoft/terminal#18250]
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.19045.5131

### Steps to reproduce

New bug report that is similar, but different, to the line-wrapping bug report.

**This does not involve line wrapping.**

Something is happening.
And it is happening "prematurely": ≈7 columns from the right of the screen. 

Somehow, getting "too close" to the right of the screen while in "big mode" (VT100 double-height text) is catalyzing some weird bug that inserts unnecessary whitespace.

It's very hard to work around.  

This definitely isn't a wrapping situation, because the lines are too short to need to be wrapped!

```
rem Adjust terminal width to 209 columns first...
pause

set big_bot=←#4
set big_top=←#3
set message=there are 209 columns...there are 209 columns...there are 209 columns...there are 209 columns....
rem length of message is 97
rem length of message in double-height size is 194 — less than our 209 columns
echo %message%

echo ----------- BUGGY:
echo %big_top%%message% 
echo %big_bot%%message%
echo -----------

rem This message is one character shorter:
set message=there are 209 columns...there are 209 columns...there are 209 columns...there are 209 columns...

echo ----------- NOT BUGGY:
echo %big_top%%message% 
echo %big_bot%%message%
echo -----------


```

![Image](https://github.com/user-attachments/assets/0bd6aac8-1fe8-4dfe-b0fa-75568aea3944)
(```eset``` is just an inline environment variable editor so i could remove one of the periods at the end)

^ I can't think of a conceivable reason in existence for this blank line to start appearing when you get ~7 from the right like that

### Expected Behavior

Expected behavior is that it looks like the top line here, not the bottom line here:

![Image](https://github.com/user-attachments/assets/8862bfb6-cc30-4e89-a386-3f985b4d43f3)

In case you're asking how I got the top line to render correctly, when claiming a bug prevents this .... I scaled it down to a smaller text size of 236 columns, ```echo```'ed it, then scaled back up to a larger text size of the original 209 columns.

As you can see, the message (the one with 4 periods at the end, not 3!) _fits just fine_ in a 209 column space.

Why this whitespace is inserted is a mystery to me.

### Actual Behavior

![Image](https://github.com/user-attachments/assets/3580d172-b119-4a31-9ddb-a711ae596ade)

**Comment by ClaireCJS** [comment]
> We've found some similar issues:
> 
> * [ANSI  double-height 2️⃣ lines line-wrap several columns too early ❗ #18185](https://github.com/microsoft/terminal/issues/18185) , similarity score: 81%
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> > Note: You can give me feedback by 👍 or 👎 this comment.

Previous report wasn't reproduceable so I trashedi t. 
This one is the proper report for that one.

**Comment by j4james** [comment]
@ClaireCJS I suspect this is just a variation of issue #18091, and most likely only occurs with odd column widths. See my explanation in https://github.com/microsoft/terminal/issues/18091#issuecomment-2427447319. It should be fixed in the latest preview build.

**Comment by DHowett** [comment]
@ClaireCJS can you try it out in Preview or Canary?

[Preview](https://aka.ms/terminal-preview)

[Canary](https://github.com/microsoft/terminal/discussions/16121)

**Comment by ClaireCJS** [comment]
> [@ClaireCJS](https://github.com/ClaireCJS) can you try it out in Preview or Canary?
> 
> [Preview](https://aka.ms/terminal-preview)
> 
> [Canary](https://github.com/microsoft/terminal/discussions/16121)

Yup! It's fixed in terminal-preview!!! Sweet, thank you!!!
