### ISSUE TITLE
Keyboard shortcut to open Terminal chat

### ISSUE THREAD

**Issue by shriharshmishra** [microsoft/terminal#18253]
### Description of the new feature

As of version 1.23.3281.0, one has to click the drop-down menu to open Terminal Chat. A keyboard shortcut will surely help. 

![Image](https://github.com/user-attachments/assets/8335e933-222b-4878-b246-7a3d0e84c152)

**Comment by adrastogi** [comment]
@shriharshmishra you can do this via a keybinding! Could you please take a look at the documentation here and see if this addresses your request? https://learn.microsoft.com/en-us/windows/terminal/terminal-chat#assigning-a-keybinding-to-terminal-chat

**Comment by doggy8088** [comment]
This is how I set up my shortcuts:

![Image](https://github.com/user-attachments/assets/0851d6b5-7d90-4e51-9f36-fe6eadeb98c6)

**Comment by FrankFang** [comment]
@doggy8088 It appears you may have overlooked mentioning the step of clicking the 'Add New' button first.

**Comment by shriharshmishra** [comment]
@adrastogi @doggy8088 thanks. I added the shortcut.

**Comment by doggy8088** [comment]
> [@doggy8088](https://github.com/doggy8088) It appears you may have overlooked mentioning the step of clicking the 'Add New' button first.

I updated my steps.

**Comment by thedarkfalcon** [comment]
@shriharshmishra I don't think this should be closed, there should be a shortcut key for this by default.
Most users won't know to add a custom shortcut key (I didn't). I had been using the command pallet shortcut _CTRL + SHIFT + P_ and then typing _chat_ and then hitting _Enter_ as my work around that was very annoying.
