### ISSUE TITLE
Wsl and Linux ssh connection problem with Windows console host

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#18255]
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.26100.2454

### Other Software

Ubuntu 22.04 in wsl1

Ubuntu 24.04 connected through ssh.

### Steps to reproduce

1. Make a lot of lines of text. For example by running cat /etc/default/acpi-support
2. Scroll up 
3. Type something.

### Expected Behavior

 Expected behavior is that console window is automatically snapped down to input field.

### Actual Behavior

Actual behavior is that when I type input location remains out of view.

**Comment by kotenok2000** [comment]
It didn't happen untill I upgraded to 24h2

**Comment by carlos-zamora** [comment]
Thanks for filing! We'll mark this as a /dup of #18073 (targeted to be fixed by #17453 as Leonard said above).
