### ISSUE TITLE
Are there any alternatives for Linux?

### ISSUE THREAD

**Issue by githubcatw** [microsoft/terminal#1827]
I understand that Terminal is Windows-exclusive (#504). But, could you suggest any alternatives for Linux?
The closest I could get is Deepin Terminal (has themes, tabs and a modern design, but all tabs launch the same shell, unlike Windows Terminal).

**Comment by mackenza** [comment]
seems pretty far off topic for a Windows Terminal issue to discuss Linux terminals...

there are dozens of options, some of which could be found here: http://www.linuxandubuntu.com/home/10-best-linux-terminals-for-ubuntu-and-fedora

I am very fond of Tilix.

**Comment by githubcatw** [comment]
I'll close this issue and ask in a Linux-specific place, like r/linuxquestions.
