### ISSUE TITLE
New window dimension setting

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/terminal#18280]
### Description of the new feature

how do you set a new windows terminal window to be maximized on launch? 
vscode has a `"window.newWindowDimensions": "maximized"` setting that works but i cannot find the equivalent in windows terminal 

source: https://aka.ms/terminal-profiles-schema

### Proposed technical implementation details

create the setting in `(AppData/Local/Packages/WindowsTerminal/LocalState)/settings.json`

**Comment by zadjii-msft** [comment]
From the schema:
https://github.com/microsoft/terminal/blob/56dc9d1f981382da61f745d30600415df24729a5/doc/cascadia/profiles.schema.json#L2496-L2507

In the UI:
![Image](https://github.com/user-attachments/assets/e20276a4-8e46-442c-84ca-bbd23e09d7c7)

Does that work for you/?

**Comment by ridhwaans** [comment]
thanks
