### ISSUE TITLE
Disabled WARP has messed up my Oh-My-Posh theme.

### ISSUE THREAD

**Issue by Giresharu** [microsoft/terminal#18283]
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.26100.0

### Other Software

PowerShell 7.4.6
oh-my-posh 24.10.1
Font: Jetbrains Mono Nerd Font
oh-my-posh theme:
```
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "secondary_prompt": {
    "template": " \ueb70 ",
    "background": "transparent"
  },
  "transient_prompt": {
    "template": " \uf054 ",
    "background": "transparent",
    "type": "path"
  },
  "console_title_template": "{{if .Root}}Admin: {{end}} {{.Folder}}",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "cache_duration": "none"
          },
          "template": "\ue0c5",
          "foreground": "#0a565d",
          "type": "text",
          "style": "plain"
        },
        {
          "properties": {
            "cache_duration": "none"
          },
          "template": " {{ if .WSL }}WSL at {{ end }}{{.Icon}} ",
          "foreground": "#efe6be",
          "powerline_symbol": "\ue0c4",
          "background": "#0a565d",
          "type": "os",
          "style": "powerline"
        },
        {
          "properties": {
            "cache_duration": "none",
            "home_icon": "\uf015  Giresharu",
            "style": "agnoster"
          },
          "template": "{{ .Path }} ",
          "foreground": "#efe6be",
          "powerline_symbol": "\ue0c4",
          "background": "#0a565d",
          "type": "path",
          "style": "powerline"
        },
        {
          "properties": {
            "branch_ahead_icon": "\uf403 ",
            "branch_behind_icon": "\uf407 ",
            "branch_gone_icon": "\udb80\udd64 ",
            "branch_icon": "\ue0a0 ",
            "branch_identical_icon": "\udb80\udd60 ",
            "branch_max_length": 10,
            "cache_duration": "none",
            "fetch_stash_count": false,
            "fetch_status": true,
            "fetch_upstream_icon": false,
            "tag_icon": "\uf412 ",
            "truncate_symbol": "..."
          },
          "template": "{{if gt .Ahead 0}}{{end}} {{ .HEAD }} {{if .BranchStatus }}{{ .BranchStatus }} {{ end }}",
          "foreground": "#efe6be",
          "powerline_symbol": "<#0a565d>\ue0c6",
          "background": "#085b46",
          "type": "git",
          "style": "powerline",
          "foreground_templates": [
            "{{  if or (and .Working.Changed (or (or (gt .Working.Modified 0) (gt .Working.Deleted 0)) (gt .Working.Unmerged 0))) (.Staging.Changed) }}#000000{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#efe6be{{ end }}",
            "{{ if gt .Ahead 0 }}#000000{{ end }}"
          ],
          "background_templates": [
            "{{ if or (and .Working.Changed (or (or (gt .Working.Modified 0) (gt .Working.Deleted 0)) (gt .Working.Unmerged 0))) (.Staging.Changed) }}#eaca20{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#cc3e2b{{ end }}",
            "{{ if gt .Ahead 0 }}#1298df{{ end }}",
            "{{ if gt .Behind 0 }}#8266c5{{ end }}"
          ]
        },
        {
          "properties": {
            "cache_duration": "none",
            "fetch_stash_count": false,
            "fetch_status": true,
            "fetch_upstream_icon": false
          },
          "template": "\ue0c4",
          "foreground": "#085b46",
          "type": "git",
          "style": "powerline",
          "foreground_templates": [
            "{{ if or (and .Working.Changed (or (or (gt .Working.Modified 0) (gt .Working.Deleted 0)) (gt .Working.Unmerged 0))) (.Staging.Changed) }}#eaca20{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#cc3e2b{{ end }}",
            "{{ if gt .Ahead 0 }}#1298df{{ end }}",
            "{{ if gt .Behind 0 }}#8266c5{{ end }}"
          ]
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "properties": {
            "always_enabled": true,
            "cache_duration": "none"
          },
          "template": " {{ if gt .Code 0 }}{{ .Meaning }} \uf00d{{ else }}\uf00c{{ end }} ",
          "foreground": "#0e3310",
          "powerline_symbol": "\ue0c5\ue0c7",
          "background": "#d4d4d4",
          "type": "exit",
          "style": "powerline",
          "foreground_templates": [
            "{{ if gt .Code 0 }}#d3d7cf{{ end }}"
          ],
          "background_templates": [
            "{{ if gt .Code 0 }}#cc2222{{ end }}"
          ],
          "invert_powerline": true
        },
        {
          "properties": {
            "always_enabled": true,
            "cache_duration": "none"
          },
          "template": "\ue0c4",
          "foreground": "#d4d4d4",
          "powerline_symbol": "\ue0c5",
          "background": "#2d8967",
          "type": "exit",
          "style": "powerline",
          "foreground_templates": [
            "{{ if gt .Code 0 }}#cc2222{{ end }}"
          ],
          "invert_powerline": true
        },
        {
          "properties": {
            "always_enabled": true,
            "cache_duration": "none"
          },
          "template": "\udb81\udcc5 {{ .FormattedMs }} ",
          "foreground": "#efe6be",
          "powerline_symbol": " \ue0c7",
          "background": "#2d8967",
          "type": "executiontime",
          "style": "powerline",
          "invert_powerline": true
        },
        {
          "properties": {
            "cache_duration": "none",
            "time_format": "15:04:05"
          },
          "template": " \uf017 {{ .CurrentDate | date .Format }}",
          "foreground": "#efe6be",
          "powerline_symbol": "\ue0c5\ue0c4",
          "background": "#0a565d",
          "type": "time",
          "style": "powerline",
          "invert_powerline": true
        },
        {
          "properties": {
            "cache_duration": "none"
          },
          "foreground": "#ffd700",
          "powerline_symbol": "\ue0c4",
          "background": "#0a565d",
          "type": "text",
          "style": "accordion"
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "cache_duration": "none"
          },
          "template": " {{if .Commit.Subject}} [\ueafc {{.Commit.Subject}} \uf007 {{.Commit.Author.Name}} \udb80\uddee {{.Commit.Author.Email}}]{{end}}",
          "foreground": "#3a7c50",
          "background": "transparent",
          "type": "git",
          "style": "diamond"
        },
        {
          "properties": {
            "cache_duration": "none"
          },
          "foreground": "#5aAcAc",
          "background": "transparent",
          "type": "git",
          "style": "diamond",
          "templates": [
            "{{if or .WorktreeCount (gt (.Env.BRANCH_COUNT | int) 0)}}[{{end}}",
            "{{if gt (.Env.BRANCH_COUNT | int) 0}}\uf126 {{add .Env.BRANCH_COUNT 1}}{{end}}",
            "{{if and .WorktreeCount (gt (.Env.BRANCH_COUNT | int) 0)}} {{end}}{{if .WorktreeCount}}\udb83\ude94 {{add .WorktreeCount 1}}{{end}}",
            "{{if or .WorktreeCount (gt (.Env.BRANCH_COUNT | int) 0)}}]{{end}}"
          ]
        },
        {
          "properties": {
            "cache_duration": "none",
            "fetch_stash_count": true,
            "fetch_status": true,
            "fetch_upstream_icon": false
          },
          "trailing_diamond": "\ue0b0",
          "foreground": "#506463",
          "background": "transparent",
          "type": "git",
          "style": "diamond",
          "foreground_templates": [
            "{{if or .Staging.Added .Staging.Modified}}#eeb573{{end}}"
          ],
          "templates": [
            "{{if or .Staging.Changed (gt .StashCount 0)}}[{{end}}",
            "{{if .Staging.Added}}\udb81\udf52 {{.Staging.Added}}{{end}}",
            "{{if and .Staging.Added .Staging.Modified}} {{end}}{{if .Staging.Modified}}\udb83\uddc8 {{.Staging.Modified}}{{end}}",
            "{{if and (or .Staging.Added .Staging.Modified) .Staging.Deleted}} {{end}}{{if .Staging.Deleted}}\udb86\ude9f {{.Staging.Deleted}}{{end}}",
            "{{if and (or (or .Staging.Added .Staging.Modified) .Staging.Deleted) .StashCount}} {{end}}{{if .StashCount}}\uf187 {{.StashCount}}{{end}}",
            "{{if or .Staging.Changed (gt .StashCount 0)}}]{{end}}"
          ]
        },
        {
          "properties": {
            "cache_duration": "none",
            "fetch_stash_count": false,
            "fetch_status": true,
            "fetch_upstream_icon": false
          },
          "foreground": "#eee673",
          "background": "transparent",
          "type": "git",
          "style": "powerline",
          "foreground_templates": [
            "{{if .Working.Unmerged}}#E74555{{end}}",
            "{{ if and (eq .Working.Modified 0) (eq .Working.Deleted 0) }}#6b5c80{{ end }}"
          ],
          "templates": [
            "{{if .Working.Changed}}[{{end}}",
            "{{if or .Working.Untracked .Working.Added}}\uf059 {{add .Working.Untracked .Working.Added}}{{end}}",
            "{{if and (or .Working.Untracked .Working.Added) .Working.Modified}} {{end}}{{if .Working.Modified}}\udb83\uddc8 {{.Working.Modified}}{{end}}",
            "{{if and (or .Working.Untracked .Working.Modified) .Working.Deleted}} {{end}}{{if .Working.Deleted}}\udb86\ude9f {{.Working.Deleted}}{{end}}",
            "{{if and (or (or .Working.Untracked .Working.Modified) .Working.Deleted) .Working.Unmerged}} {{end}}{{if .Working.Unmerged}}\ue728 {{.Working.Unmerged}}{{end}}",
            "{{if .Working.Changed}}]{{end}}"
          ]
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "cache_duration": "none"
          },
          "template": "\ueb70\uf054",
          "type": "text",
          "style": "powerline"
        }
      ],
      "newline": true
    }
  ],
  "version": 3,
  "final_space": true
}

```

### Steps to reproduce

1. Follow the instructions on the [oh-my-posh official website](https://ohmyposh.dev/docs/installation/windows) to install oh-my-posh. (I used winget to install it.)
2. Save the theme I provided above as a local JSON file, and use `code $profile` or another editor to open the `Microsoft.PowerShell_profile.ps1` file, and add the following line:
```
oh-my-posh init pwsh --config "PathToTheme.json" | Invoke-Expression
```
4. Download the [JetBrains Mono Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip) from NerdFont (the font I am actually using is a full patch version manually created with the patch provided by NerdFont; I am unsure if providing the file here would cause copyright issues. If there are no copyright issues, I will provide the attachment later).
5. Change the font of Windows Terminal to the one downloaded in step 3, and disable the WARP feature.
6. Restart Windows Terminal, and open pwsh7 in it. 

### Expected Behavior

The correct theme is the same as when WARP is enabled; the text color does not mess up the background, causing the theme to become muddled. As shown in the figure: 
![Image](https://github.com/user-attachments/assets/d3e94239-410e-4e83-a965-f6f154020ee3)

However, enabling it will cause another issue, which is that the cursor is not displayed. Therefore, I cannot work with WARP enabled.

### Actual Behavior

Messed up theme, as shown in the figure. Each yellow Nerd Font character has incorrectly affected the color of the background block, resulting in a confused theme:
![Image](https://github.com/user-attachments/assets/c4af0dee-f031-4df1-9828-3cd632598f32)

**Comment by DHowett** [comment]
> However, enabling it will cause another issue, which is that the cursor is not displayed. Therefore, I cannot work with WARP enabled.

This is a separate bug worth investigating.

**Comment by carlos-zamora** [comment]
Thanks for filing! Some questions from the team:
- Can you share the current ttf file you're using for this font as a ZIP?
- If you use the latest version of the font, does this repro?

**Comment by lhecker** [comment]
The latest Windows Terminal Preview version supports a new text selection mode, which reveals why this issue occurs:

https://github.com/user-attachments/assets/1fc61248-ee5f-44ac-90d8-df1da0018cd1

Your powerline characters are visually 2 columns wide, but Unicode says that they're supposed to be 1 column wide characters. This is why you need to use `"\ue0c5 "` with a space at the end as padding.

That aside, I noticed that your oh-my-posh configuration has *a lot* of issues and smaller mistakes. If you search for your example powerline character in the repository, you'll find a lot of reference code that you can use: https://github.com/search?q=repo%3AJanDeDobbeleer%2Foh-my-posh%20ue0c5&type=code
Among others, you can merge your first and second segment together by simply using the `"leading_diamond"` attribute.

Let me know if you have any questions!

**Comment by lhecker** [comment]
I should add that the only reason you don't see this when WARP is enabled is because we use a fallback text renderer in that case that is less accurate. You should also never ever use WARP if you can avoid it. It's basically a small CPU torture test every time you print lots of text. 😟

**Comment by Giresharu** [comment]
> The latest Windows Terminal Preview version supports a new text selection mode, which reveals why this issue occurs:
> 
>  QKKiuJdjMHnn7acE.mp4 
> Your powerline characters are visually 2 columns wide, but Unicode says that they're supposed to be 1 column wide characters. This is why you need to use `"\ue0c5 "` with a space at the end as padding.
> 
> That aside, I noticed that your oh-my-posh configuration has _a lot_ of issues and smaller mistakes. If you search for your example powerline character in the repository, you'll find a lot of reference code that you can use: https://github.com/search?q=repo%3AJanDeDobbeleer%2Foh-my-posh%20ue0c5&type=code Among others, you can merge your first and second segment together by simply using the `"leading_diamond"` attribute.
> 
> Let me know if you have any questions!

 That makes sense, I must find a way to improve my theme file.

**Comment by Giresharu** [comment]
> The latest Windows Terminal Preview version supports a new text selection mode, which reveals why this issue occurs:
> 
>  QKKiuJdjMHnn7acE.mp4 
> Your powerline characters are visually 2 columns wide, but Unicode says that they're supposed to be 1 column wide characters. This is why you need to use `"\ue0c5 "` with a space at the end as padding.
> 
> That aside, I noticed that your oh-my-posh configuration has _a lot_ of issues and smaller mistakes. If you search for your example powerline character in the repository, you'll find a lot of reference code that you can use: https://github.com/search?q=repo%3AJanDeDobbeleer%2Foh-my-posh%20ue0c5&type=code Among others, you can merge your first and second segment together by simply using the `"leading_diamond"` attribute.
> 
> Let me know if you have any questions!

I took another look at the themes provided by oh_my_posh that use the same characters, and they seem to have the same issue. Other terminals do not have similar problems. Can this really not be considered a problem with Windows Terminal? If the theme configuration needs to be modified due to character length reasons, wouldn't that configuration no longer be universal?

Windows Terminal:
![Image](https://github.com/user-attachments/assets/38df6720-68e7-4143-8bcd-531a0179a2e5)
![Image](https://github.com/user-attachments/assets/c1ff0f0c-91e2-493f-9c73-cb9920b840f5)

Tabby:
![Image](https://github.com/user-attachments/assets/d8e27c92-b056-4d3d-a000-23c8a1bf464d)
![Image](https://github.com/user-attachments/assets/2f4faf71-253b-441a-b87a-fd00e558a3dc)

**Comment by lhecker** [comment]
Hmm... I don't mind treating this as a bug in Windows Terminal, but I'm honestly not convinced yet that it is one. Your example images from Tabby perhaps shows it best. This is how it's supposed to look like, coming straight from the oh-my-posh website:

![](https://ohmyposh.dev/assets/images/cert-8d2ac0cdcc6d5eddcd7b51475808ec83.png)

![](https://ohmyposh.dev/assets/images/free-ukraine-4fa3aa47e5d76560075972193a1f0343.png)

In the "cert" theme, Tabby is drawing the powerline symbols on top of the colored background, while in the reference image it blends in perfectly. In the "free-ukraine" theme, the color of the icons is wrong (it's white but should be yellow).

I think it's fair to say that the more advanced oh-my-posh themes make certain assumptions about the text rendering behavior of the terminal that may not be universally true.
