### ISSUE TITLE
Add Find to Terminal dropdown menu

### ISSUE THREAD

**Issue by cniggeler** [microsoft/terminal#18298]
### Description of the new feature

Terminal is a GUI app. Instead of forcing users to remember that finding text is SHIFT+CTRL+F, why not just add Find to the dropdown menu that's already present?

### Proposed technical implementation details

I know the Terminal code is massive, so if someone had a pointer to where this change needs to go, I'd be glad to give it a shot!

**Comment by zadjii-msft** [comment]
You're more than welcome to modify your own new tab menu. You can add the following:

```json
{
    "type":"action",
    "id": "Terminal.FindText"
}
```

to the `newTabMenu` (as of 1.22 IIRC), and that'll add find to the menu:

![Image](https://github.com/user-attachments/assets/0b2b3b49-fb10-497c-99ad-4ff37f892a12)


But I'd probably reject the request to add more to that top level menu. The bar is very high, to avoid the menu getting too cluttered. 

The Command Palette (on ctrl+shift+p) shows all the commands we have in the Terminal, and there's quite a lot nowadays. That's a generally better menu UI for such a keyboard-driven application as the Terminal
