### ISSUE TITLE
a cursorCornerRadius setting suggestion

### ISSUE THREAD

**Issue by thiagoigfraga** [microsoft/terminal#18305]
### Description of the new feature

Hello, everybody. I’ve been looking around the issues list and noticed that this one about adding rounded corners to the cursor shape has been hanging here for a really long time. It attracted my attention: the “filledBox” or “vintage” cursor shapes look so harsh with their sharp edges—especially given how slick and modern everything else in the Terminal can feel. So I figured, why not make this my first “good first issue” contribution, hm?
[](url)
My plan is pretty straightforward: introduce a new property (something like cursorCornerRadius) so that if someone sets "cursorShape": "filledBox" or "cursorShape": "vintage", they can also tweak this radius value and get a nice, rounded rectangle look. Basically, if we’re already drawing a shape, we just need to feed in a corner radius parameter before it’s rendered, which should give us that softer, more “polished” look.

I think this approach is simple, direct, and easy to configure. it’ll give users more control over how their cursor appears. I’m excited to dive in and try to make this long-standing request finally happen.

If it interest you to, let me know.

[Feature Request: CornerRadius on Cursor Shape #1446](https://github.com/microsoft/terminal/issues/1446)

**Comment by DHowett** [comment]
Hey, welcome to the repository! I appreciate your enthusiasm -- and I'd encourage you to keep all your updates in issue #1446 itself. Since that's the main issue for this request, it'll be the best place to write up your proposal and eventually link to your pull request. You don't need to file a new separate issue to declare your intent 🙂 

Mind if I mark this one as a duplicate?

**Comment by thiagoigfraga** [comment]
> Hey, welcome to the repository! I appreciate your enthusiasm, but I'd encourage you to keep all your updates in issue [#1446](https://github.com/microsoft/terminal/issues/1446) itself. Since that's the main issue for this request, it'll be the best place to write up your proposal and eventually link to your pull request. You don't need to file a new separate issue to declare your intent 🙂
> 
> Mind if I mark this one as a duplicate?

Hey, no problem, I understand. I'll keep all the updates in issue #1446, as suggested. Thanks for the clarification! You can mark this one as a duplicate, yes.

**Comment by carlos-zamora** [comment]
Thanks for filing. Yeah, we're going to mark this as a /dup of #1446
