### ISSUE TITLE
Full Duplex Operation

### ISSUE THREAD

**Issue by CannibalVox** [microsoft/terminal#18319]
### Description of the new feature

In https://github.com/microsoft/terminal/issues/18265 @carlos-zamora informed me that while operating the terminal as full duplex (reading from stdin and writing to stdout at the same time) does work in the stable version of Windows Terminal, Microsoft did not recommend doing so, so a bug with full duplex operation was not actually a bug.

Given that the last half-duplex terminal to exist was decommissioned sometime in the 1990s, however, I suggest that Microsoft undergo a project to add full duplex operation to Windows Terminal. And bring it into line with similar products. While Carlos did not believe there were any known use cases for a full duplex terminal, I'm inclined to disagree. While I can't speak for anyone else, the Go programming language does not have the capability to cancel reading from stdin, meaning that no application written in Go is capable of half-duplex operations.  I believe that adding Full Duplex capability to Windows Terminal would be a major boon for Go developers, especially since we all thought Windows Terminal already had it.

### Proposed technical implementation details

I'm not clear on the technical specifics, but probably do whatever the current version of Windows Terminal does, since Full Duplex works in that version.

**Comment by DHowett** [comment]
I'd rather reopen #18265 for discussion than entertain "full duplex operation" as a di novo feature request, if you wouldn't mind. There are a lot of assumptions and messages flying by without response, so _please hold up._

**Comment by DHowett** [comment]
In general, turning a legitimate concern (which you do have!) about how your bug report was handled into a somewhat facetious feature request is not conducive to discussion.

**Comment by CannibalVox** [comment]
Unfortunately, I don't have a twitter account, so there wasn't really another option.
