### ISSUE TITLE
Tab management + Zoom

### ISSUE THREAD

**Issue by azjerei** [microsoft/terminal#1831]
Tabs should work and look like those in Edge:

- The "new" button should follow the width of the tabs, not stay in place.
- Tabs should resize if there are too many for the bar to handle. Right now, they disappear behind the "new" button, which is really bad.
- Use only icons on the tabs perhaps? Or at least icon and name only, not a full path. But definitely icons only when there are too many tabs.

Would be nice with a "zoom" button that zooms out all open terminals (like using Task View in the taskbar) and presents thumbnails. That way you can get to the window you want faster, since there is no way of telling any two terminals apart in the tabs.

**Comment by azjerei** [comment]
![windows_terminals_concept](https://user-images.githubusercontent.com/33510302/60699790-b9a0a580-9ef5-11e9-9f32-74f37267427b.png)

**Comment by DHowett-MSFT** [comment]
#1375 please help us keep our issues focused by checking out the pinned issues before filing a new one!
