### ISSUE TITLE
GitHub Copilot on Terminal Chat wrongly treat path as shell

### ISSUE THREAD

**Issue by doggy8088** [microsoft/terminal#18314]
### Windows Terminal version

1.23.3461.0

### Windows build number

10.0.19045.5131

### Other Software

N/A

### Steps to reproduce

1. Add a new profile in the Windows Terminal Canary. The command line is `C:\Program Files\PowerShell\7\pwsh.exe -NoLogo`.

2. Open a new tab to this profile

3. Open Terminal Chat

4. Enter `list files`

5. You will see "Program" shell which is wrong.

    ![Image](https://github.com/user-attachments/assets/57e151e7-2629-4481-a8ee-04f67a4193e5)

    GitHub Copilot seems treat `C:\Program Files\PowerShell\7\pwsh.exe -NoLogo` as a `Program` shell. This should be a bug.

### Expected Behavior

The shell of the `C:\Program Files\PowerShell\7\pwsh.exe -NoLogo` should be `pwsh`.

### Actual Behavior

The shell of the `C:\Program Files\PowerShell\7\pwsh.exe -NoLogo` become `Program` shell.

**Comment by DHowett** [comment]
Thanks!

In general, and for safety reasons, you should use quotes when you include a path with spaces in it.

We should handle this better, but you can get around the bug today by quoting the EXE path 🙂

**Comment by doggy8088** [comment]
After adding quote on it, it works perfectly. Thank you! :)
