### ISSUE TITLE
command 'conda activate' not work correctly

### ISSUE THREAD

**Issue by li-zheng-hao** [microsoft/terminal#1832]
# Environment

```none
Windows build number: Microsoft Windows [version10.0.18362.175] 
Windows Terminal version (if applicable): Version: 0.2.1831.0

Any other software?
Anaconda
```

# Steps to reproduce

1. open terminal
2. input-> "conda activate python3.6" (my conda environment name which use python3.6.8 )
3. input->"python"
4. the env is base (use python3.7) rather than python3.6

# Expected behavior

![image](https://user-images.githubusercontent.com/22129824/60701517-99410d00-9f2e-11e9-903f-6b8cb416cd81.png)
use cmd:
![image](https://user-images.githubusercontent.com/22129824/60701504-88909700-9f2e-11e9-9d59-a5fa0e270668.png)

 # Actual behavior

**Comment by DHowett-MSFT** [comment]
You're demonstrating with powershell in the "broken" screenshot and cmd in the "working" one. This might just be how `conda activate` _works_. If it is a `.cmd` or `.bat` file that is setting environment variables, it just won't work from PowerShell. We can't change that.

**Comment by abiro** [comment]
For the benefit of somebody finding this from Google: 

Anaconda 4.6.0 and later supports PowerShell by running `conda init powershell` after the installation. Having done that, Terminal works with Anaconda out of the box.
