### ISSUE TITLE
New window instances do not gain foreground rights

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#18324]
### Windows Terminal version

1.23.3471.0

### Steps to reproduce

* Set "New instance behavior" to "Create a new window"
* Launch from the start menu (= first window, first tab)
* Explicitly minimize
* Launch from the start menu again

### Expected Behavior

New window is in the foreground.

### Actual Behavior

New window fails to gain foreground rights.

**Comment by zadjii-msft** [comment]
Can we `AllowSetForeground`? I suppose we don't know the PID of the instance holding the mutex, do we. hmm....

**Comment by lhecker** [comment]
Oh, I didn't see your message! And yeah, I fixed it exactly like that. We can get the PID with `GetWindowThreadProcessId`.
