### ISSUE TITLE
Unable to open settings

### ISSUE THREAD

**Issue by MarcelVosslamber** [microsoft/terminal#1833]
# Environment

Windows build number: [10.0.18362.116]
Windows Terminal version (if applicable): 0.2.1831.0

# Steps to reproduce

Click on settings
CTRL + , 

# Expected behavior

Open settings windows

# Actual behavior

Nothing

**Comment by marcogroppo** [comment]
Unfortunately it seems that you can open the Settings only if you have an application that can handle JSON files. In the Windows File Explorer you can right-click on a JSON file (just create an empty file with a `.json` extension if you don't have one), then click `Open with` -> `Choose another app` and check `Always use this app to open .json files`.

**Comment by MarcelVosslamber** [comment]
> Unfortunately it seems that you can open the Settings only if you have an application that can handle JSON files. In the Windows File Explorer you can right-click on a JSON file (just create an empty file with a `.json` extension if you don't have one), then click `Open with` -> `Choose another app` and check `Always use this app to open .json files`.

Thanks, linked VS code and works like a charm.

**Comment by LewisTian** [comment]
Thanks, I also encountered this problem : )
