### ISSUE TITLE
elevate-shim.exe quickly opens and closes forever

### ISSUE THREAD

**Issue by tenix7676** [microsoft/terminal#18346]
### Steps to reproduce

Downloaded the latest version Microsoft.WindowsTerminal_1.21.3231.0_x64. I'm on windows 10. 
Click on elevate-shim.exe

### Actual Behavior

elevate-shim.exe continually open for a few miliseconds and closes in an endless loop

**Comment by DHowett** [comment]
Thanks!

If you are launching it directly, a quick workaround is to not do that. It is an implementation detail.

In general, running random EXE files isn't always a winning strategy. :)
