### ISSUE TITLE
Color themes and nerdfonts not applying

### ISSUE THREAD

**Issue by KonstaVilkman** [microsoft/terminal#18356]
### Windows Terminal version

1.21.3231.0

### Windows build number

Microsoft Windows [Version 10.0.22631.4602]

### Steps to reproduce

1. Set color, and font
2. Hit save
3. Open new tab of powershell or cmd

### Expected Behavior

Expected result would be that it would look the same as in the preview window in the settings

### Actual Behavior

Color theme nor font make any changes
![Image](https://github.com/user-attachments/assets/e26f5264-461f-49ff-83af-0ab404d4dbef)
![Image](https://github.com/user-attachments/assets/014a28d3-0cd9-4450-ad3a-9a829e80bb77)

**Comment by DHowett** [comment]
The color schemes only apply when the console application is actually using colors.

I can see that the font in your terminal matches the font in the preview. It stands to reason that the other settings have been applied as well!

The sample text in the preview is for illustrative purposes. Terminal will not configure your shell to *use* those colors.

**Comment by KonstaVilkman** [comment]
Hmm I see. The problem was in between the monitor and the chair's headrest. I'll look into this more. Thanks!
