### ISSUE TITLE
Control-T creates a new tab

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/terminal#1835]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.207]

Any other software?
FreeBSD VM, remote FreeBSD systems.
```

# Steps to reproduce

Hit control-T

# Expected behavior

A ^T character is delivered to stdin on the controlling process which, on UNIX systems, will cause the pty layer to deliver SIGINFO to the foreground application.

# Actual behavior

A new tab opens, leaving me with no mechanism to deliver SIGINFO.

This is a regression relative to the old console host.  The convention for other terminals on platforms that don't have a command key is to always use control-shift for terminal control commands (e.g. control-shift-c instead of control-c for copy, control-shift-t instead of control-t for new tab) so that they do not conflict with normal command entry.

**Comment by Summon528** [comment]
You can rebind it to control-shift-t via modifying the setting file though

**Comment by DHowett-MSFT** [comment]
Hey @davidchisnall :smile: We're tracking this one in #1417 (admittedly, I made the name not particularly searchable!)
