### ISSUE TITLE
Can't download Canary Version

### ISSUE THREAD

**Issue by thggdx** [microsoft/terminal#18352]
I try downloading https://aka.ms/terminal-canary-installer
It return XML:
```XML
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:99fdf444-001e-0054-1c57-5495a6000000 Time:2024-12-22T09:56:43.1699461Z</Message>
</Error>
```

**Comment by N4RMA** [comment]
same here

**Comment by ddodogames** [comment]
I had this too

**Comment by DHowett** [comment]
Thanks!

The builds age out after seven days, which I guess assumes that we'll have a commit to main at least every seven days.

Turns out we don't necessarily have ongoing work over the holidays!

A new build should be up in about 2 hours and the URL should once again work.

**Comment by DHowett** [comment]
Build's out. Thanks again!
