### ISSUE TITLE
Windows Terminal on Windows ARM device doesn't output unicode combining character sequences

### ISSUE THREAD

**Issue by tomlm** [microsoft/terminal#18364]
### Windows Terminal version

1.21.3231.0

### Windows build number

 10.0.22631.4460

### Steps to reproduce

```csharp
Console.OutputEncoding = System.Text.Encoding.UTF8;
Console.WriteLine("👨‍👩‍👧‍👦👨‍👩‍👧‍👦👨‍👩‍👧‍👦");
```

### Expected Behavior

Used to output 
👨‍👩‍👧‍👦👨‍👩‍👧‍👦👨‍👩‍👧‍👦

### Actual Behavior

outputs 
![Image](https://github.com/user-attachments/assets/9b76dcf2-3ec0-44c6-b54a-737b21e78fb8)
 

The issue is that the caret is advanced the codepoint width (11) instead of the glyph width (2)

**Comment by j4james** [comment]
@tomlm Support for grapheme clusters was only added in Windows Terminal Preview v1.22.2362.0, so I wouldn't expect it to be working in the version you're using. If it worked for you before, I suspect you must have had a preview version of the terminal installed at some point.

**Comment by tomlm** [comment]
Ah that is probably what I've done, thanks
