### ISSUE TITLE
add shortcut to execute the focus terminal operation when minimizeToNotificationArea

### ISSUE THREAD

**Issue by bushnerd** [microsoft/terminal#18379]
### Description of the new feature

Windows Terminal version
1.17.11461.0

Windows build number
NA

Other Software
No response

Steps to reproduce
Enable "minimizeToNotificationArea": true
Open terminal
Minimize terminal
Set the global shortcut key as specified, such as ctrl+`, to execute the focus terminal operation.

Expected Behavior
Restore terminal window

Actual Behavior
Currently, this feature is not available

I have implemented a shortcut to minimizeToNotificationArea with autohotkey, code as follows:
```
^`::
if WinActive("ahk_exe WindowsTerminal.exe") {
	WinMinimize, ahk_exe WindowsTerminal.exe 
} else {
}
return
```

**Comment by zadjii-msft** [comment]
The `globalSummon` action _should_ work even when minimized to the notification area. 

Is it possible that some other program has already bound that hotkey? Can you try binding a different keybinding in the settings, just to see what happens?

Also, can you try a build of the Terminal from this year/? 1.17 is [literally 18 months old](https://github.com/microsoft/terminal/releases/tag/v1.17.11461.0) 😄

**Comment by bushnerd** [comment]
非常感谢你这么快的回复。是我的问题，我一直在找这样的一个操作，没想到已经实现了。
我已经按如下操作，达到我的想法了。
```json
        {
            "command": {
                "action": "globalSummon",
                "toggleVisibility": true
            },
            "keys": "ctrl+`"

```
