### ISSUE TITLE
 `Use legacy console` option prevents Terminal from launching ConPTYs correctly

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#1838]
I got this issue and after uncheck `Use legacy console` option, my terminal show up

![image](https://user-images.githubusercontent.com/3783976/60732611-b6003380-9f74-11e9-8fa6-63caa802b4b2.png)

_Originally posted by @oclockvn in https://github.com/microsoft/terminal/issues/1364#issuecomment-508796240_

This represents double-checking that the startup routines in `entrypoints.cpp` are ignoring the v1/v2 status when identifying a ConPTY-style connection and always doing v2.

**Comment by DHowett-MSFT** [comment]
Confirming: we check the ForceV1 key and fail out if the user has ForceV1 and is requesting commandline launch. To make legacy console not interfere with CreatePseudoConsole (which doesn't use commandline launch), we need to detect that the server handle being passed in is for pseudoconsole work.
We could key off the presence of `--signal` in both cases.

**Comment by DHowett-MSFT** [comment]
(Confirmed this is broken in the windows image as well. pwincon refuses to launch because it bombs out in CreatePseudoConsole :))
