### ISSUE TITLE
Profile::Set...(std::wstring param) not using std::move

### ISSUE THREAD

**Issue by yves-dolce** [microsoft/terminal#1844]
Let me start by saying I did not read the whole source so I might have missed important details.

I was looking at the source code to understand how you're handling the `commandline` setting and saw that many methods in the `Profile` class do not move the instance of the `std::wstring` received and instead create a copy. 

Also, why do you mark the methods `noexcept` when some strings might not be small enough to allow SSO? (e.g. a long command line)

# Proposed technical implementation details (optional)
```
void Profile::SetCommandline(std::wstring cmdline) noexcept
{
    _commandline = std::move(cmdline);
}

```

**Comment by zadjii-msft** [comment]
I'm sure that no one really thought too hard about it - seems like that would work to me. 

I'm not sure I know why they're marked noexcept. I bet that we assumed that all the setters in `Profile` were just simple setters that couldn't possibly throw.

**Comment by yves-dolce** [comment]
If I'm confident you'll take the PR, I can spend time forking and submitting a PR. Just tell me.

**Comment by DHowett-MSFT** [comment]
We would definitely take any PR that makes our code better. Thanks :smile:

**Comment by yves-dolce** [comment]
OK. So I'm ready to submit it but when I follow the README.MD and call testcon, it ends with:
Summary of TAEF Warnings:
```
    Warning: TAEF: The test file "......\terminal.fork\bin\x64\Debug\ConHost.Api.Tests.dll" does not exist.
    Warning: TAEF: The test file "file ......\terminal.fork\bin\x64\Debug\ConHost.Resize.Tests.dll" does not exist.
    Warning: TAEF: The test file "file ......\terminal.fork\bin\x64\Debug\ConHost.CJK.Tests.dll" does not exist.

Summary of Non-passing Tests:
    ClipboardTests::CanConvertCharsOutsideKeyboardLayout [Failed]

Summary: Total=1054, Passed=1053, Failed=1, Blocked=0, Not Run=0, Skipped=0
```
Is this a known issue of the UT?

**Comment by DHowett-MSFT** [comment]
I believe so. The UTs might not work if your system codepage is not 1252 :smile:

**Comment by yves-dolce** [comment]
Just submitted my ever first Open Source PR  #1899 ...
