### ISSUE TITLE
Left-clicking selected text to copy copies the single character accidentally selected

### ISSUE THREAD

**Issue by 439bananas** [microsoft/terminal#1845]
# Environment

```none
Windows build number: 10.0.18922.1000
Windows Terminal version (if applicable): 0.2.1715.0

WSL, Node.JS, Git-SCM (shouldn't really affect anything, right?)
```

# Steps to reproduce

- Select text by dragging over it
- Click the text, which copies
- Notice that now one character where you clicked is selected
- Right-click into your input
- Observe the text actually pasted is just that character selected after (or during) copying

# Expected behavior

The original selected text should be pasted

# Actual behavior

The character below where you clicked to copy that was accidentally selected is pasted

**Comment by carlos-zamora** [comment]
The copy specifically happens when you right-click. So, on step 3, you created a new selection. Then, you actually copied it on step 4.

Are you saying that you want the selection to be copied when you left-click on the selection?

**Comment by 439bananas** [comment]
> The copy specifically happens when you right-click. So, on step 3, you created a new selection. Then, you actually copied it on step 4.
> 
> Are you saying that you want the selection to be copied when you left-click on the selection?

Pretty much...

**Comment by DHowett-MSFT** [comment]
This will be helped by #1553
