### ISSUE TITLE
Bug: Native Powershell 5 Does Not Run As Expected

### ISSUE THREAD

**Issue by 8thHalfHour** [microsoft/terminal#1848]
My installation of Terminal from the Windows Store gives me the choice to open tabs of PowerShell Core (I have v7 installed separately), PowerShell, CMD, and Ubuntu. All work as I would expect, except for the native PowerShell. To be clear, when I choose PowerShell Core, it opens Core v7 Preview; the other choices also work, as expected. However, the PowerShell item does not initiate a native PowerShell 5 tab, as expected; instead it opens another tab for PowerShell Core 7. I tried changing the path for the Powershell entry in `Settings`, but when I set the full path, Terminal no longer executed at all.

**Comment by yogesh-aggarwal** [comment]
No worries. It's now fixed 😊✔

**Comment by 8thHalfHour** [comment]
I don't understand. The issue remains, and there has been no change.

**Comment by DHowett-MSFT** [comment]
Just change the `defaultProfile` GUID in your settings (`profiles.json`) to the one for `Windows PowerShell`.

**Comment by 8thHalfHour** [comment]
@DHowett : Where/how do I find the GUID?
