### ISSUE TITLE
Nit: Logo on Live Tile has no shadow

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#1853]
![image](https://user-images.githubusercontent.com/75278/60761558-5b85d680-a04b-11e9-8715-4ded9bc39e66.png)

# Environment

```none
Windows build number: Win10 1903 18362.207
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
```

# Steps to reproduce

Pin Windows Terminal to the start menu
# Expected behavior
Icon should have a shadow like the office icons

# Actual behavior
Icon has no shadow

Also I think it's a bit too small? Or maybe the YourPhone one is the outlier here, I actually like the size of that one way better.

**Comment by carlos-zamora** [comment]
@cinnamon-msft sending this one your way.

**Comment by DHowett-MSFT** [comment]
Let's do what the xbox icon did :grin:

**Comment by Stanzilla** [comment]
Dear god, no :D

**Comment by anjc** [comment]
I would take another look at this, @DHowett-MSFT. Terminal's icon looks **really** out of place without a shadow, despite it being aesthetically similar to the rest of the new Fluent icons.

![Terminal Start Icon](https://user-images.githubusercontent.com/36517378/81772042-bf223100-94b2-11ea-8f01-740cd7e5f43e.jpg)

**Comment by mdtauk** [comment]
This is going to become an increasingly larger problem as more developers move to coloured icons, and none of the live tile documentation has updated.

Not only should there be a shadow, but it should be a consistent shadow with the other apps using Fluent App Icons.

I made an issue on the WinUI repo that covers this.
https://github.com/microsoft/microsoft-ui-xaml/issues/2307

**Comment by miniksa** [comment]
@cinnamon-msft can we fix this? It's been open a while...

**Comment by vefatica** [comment]
Hmmm!  If I pin it, I get the right icon (don't care about the shadow).  But if I search in the start menu, I just get a generic icon associated with IrfanView (third party image viewer).  In the same situation (having typed something in the search) ALL other apps that I've tried show a correct icon.
![image](https://user-images.githubusercontent.com/61856645/112761085-6a52b080-8fc7-11eb-8114-06dc76597689.png)

**Comment by Cyberdroid1** [comment]
> Hmmm! If I pin it, I get the right icon (don't care about the shadow). But if I search in the start menu, I just get a generic icon associated with IrfanView (third party image viewer). In the same situation (having typed something in the search) ALL other apps that I've tried show a correct icon.
> ![image](https://user-images.githubusercontent.com/61856645/112761085-6a52b080-8fc7-11eb-8114-06dc76597689.png)

This issue is with Windows Search, not the app.

**Comment by Cyberdroid1** [comment]
Any updates to this issue?

![image](https://user-images.githubusercontent.com/51435948/122675546-8bf2bb00-d1f7-11eb-84c3-d03e5088fb4b.png)

**Comment by zadjii-msft** [comment]
Hey so this might be a spicy take, but I'm gonna close this out. With Windows 11, live tiles are gone from the Start Menu. We still intend on supporting Windows 10 for a while in the Terminal, but I don't think we're gonna have the bandwidth to add this to our live tile just for Windows 10. If someone comes through and finds a way to do it, I'll probably still accept the PR.
