### ISSUE TITLE
Please don't set Ctrl-W to close a tab as default

### ISSUE THREAD

**Issue by 0x00000FF** [microsoft/terminal#1854]
# Summary of the new feature/enhancement

I'm using Vim as default editor on Linux, also doing some job on multiple vim windows. As you know, Vim uses Ctrl-W to switch between its window, but it also causes closing tab on microsoft terminal. Would you please remove Ctrl-W from default keybindings?

Thank you!

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This'll be #1417. Thanks!
