### ISSUE TITLE
app  crashing before opening

### ISSUE THREAD

**Issue by jaswanthjashu** [microsoft/terminal#1855]
I downloaded windows terminal preview from windows store if I open it its closing automatically.
Please help !

**Comment by braithair** [comment]
Are you running as Admin, Jas? Mine does this too if I don't run as admin.

**Comment by alefranz** [comment]
I'm having a similar issue:

```
Faulting application name: WindowsTerminal.exe, version: 1.0.1907.2001, time stamp: 0x5d1bd2d0
Faulting module name: ucrtbase.dll, version: 10.0.18362.1, time stamp: 0x5cbddb81
Exception code: 0xc0000409
Fault offset: 0x000000000006d3be
Faulting process ID: 0x43f4
Faulting application start time: 0x01d534ed298890cf
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 210b99ca-c2f2-4769-8ca3-1f8948041019
Faulting package full name: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```
Windows Insiders
Version	10.0.18362 Build 18362

**Comment by DHowett-MSFT** [comment]
In the windows console settings, have you enabled `[ ] Use legacy console`?

**Comment by alefranz** [comment]
My issue was related to the config, I fixed it copying the `profiles.json` from another PC.
This was on the first install, so no manual edits in the config

**Comment by 2MuchLag4you** [comment]
I had the same solution on a secondary system.

> My issue was related to the config, I fixed it copying the profiles.json from another PC.
( Mine was referring to a non install powershell 6 core )
> This was on the first install, so no manual edits in the config
( Same here, it looked like it copied the config from the secondary computer )

**Comment by DHowett-MSFT** [comment]
This is another version of #1364.

**Comment by jthvedt** [comment]
I was getting Exception code: 0xc0000409 in ucrtbase.dll, and it was apparently triggered by something in my profiles.json file. I deleted that file, then launched Windows Terminal, which recreated the file. If you have lots of config changes, you probably should make a backup first, so you can use it as a reference to recreate your changes.
