### ISSUE TITLE
Snapping to smaller screen with a COOKED_READ crashes conpty

### ISSUE THREAD

**Issue by 2MuchLag4you** [microsoft/terminal#1856]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
**Microsoft Windows [Version 10.0.18362.207]**
OS language is dutch
Windows Terminal version (if applicable):
**Windows Terminal (Preview)
Version: 0.2.1831.0**

Any other software?
```

# Steps to reproduce

full screen the terminal window and use the keys "windows + shift + arrow" to move the window to your second screen

# Expected behavior
Go full screen on second monitor

# Actual behavior
When I move it from a 1920x1080 screen to a 2560x1080 screen it goes full screen. When moving it from a 2560x1080 screen to a 1920x1080 screen the terminal crashes.

# Message event viewer (Dutch)
Naam van toepassing met fout: WindowsTerminal.exe, versie: 1.0.1907.2001, tijdstempel: 0x5d1bd2d0
Naam van module met fout: ucrtbase.dll, versie: 10.0.18362.1, tijdstempel: 0x5cbddb81
Uitzonderingscode: 0xc0000409
Foutmarge: 0x000000000006d3be
Id van proces met fout: 0x3028
Starttijd van toepassing met fout: 0x01d534b9425f56b0
Pad naar toepassing met fout: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Pad naar module met fout: C:\WINDOWS\System32\ucrtbase.dll
Rapport-id: d822f0b0-3805-4c9f-b74e-87c80dc48334
Volledige pakketnaam met fout: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
Relatieve toepassings-id van pakket met fout: App

**Comment by zadjii-msft** [comment]
This seems like it's related to #1572, but since you're on 0.2.1831.0 (which includes the fix for that issue), it can't be the same root cause as that issue.

**Comment by DHowett-MSFT** [comment]
This may be the same as #1795. We'll leave it open just to make sure.

**Comment by zadjii-msft** [comment]
Largely, this issue's been fixed, but there's certainly another bug here, and it goes beyond the terminal.

If you create a conpty, and then you have a COOKED_READ with some input in that conpty, then snap the Terminal window to a smaller size like this, the conpty crashes. The conpty crashes when resizing, specifically due to the presence of the input line. I thought I had a fix in d34a3be for this, but I'm not sure that it totally works. It seems trivial enough, but knowing what I know about COOKED_READs, an easy fix is usually wrong. There's almost certainly edge cases it misses. 

I want to leave this bug open to track that specific crash.

**Comment by galassie** [comment]
With v 6.0 is even worse.
Every time I go in full screen in other screen devices except the main one, it crashes.

This is the error logged in the event viewer:

Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.418, time stamp: 0x253810c2
Exception code: 0xc000027b
Fault offset: 0x0000000000712dc0
Faulting process id: 0x3e58
Faulting application start time: 0x01d58a469cd74c0e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 41431fbc-2508-4fde-af06-7e59afe73e85
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by DHowett-MSFT** [comment]
@galassie this looks unrelated (since the crash is in "Windows.UI.Xaml.dll" -- i bet that's #2277.

**Comment by galassie** [comment]
> @galassie this looks unrelated (since the crash is in "Windows.UI.Xaml.dll" -- i bet that's #2277.

Yeah, you're right! I haven't seen that issue!

**Comment by zadjii-msft** [comment]
Pulling this into 1.0 since we think it might actually be a pretty common crash
