### ISSUE TITLE
Windows Terminal Opened Tabs Bug

### ISSUE THREAD

**Issue by nxtexe** [microsoft/terminal#1857]
# Environment

```none
Windows build number: [10.0.18362.207]
Windows Terminal version (0.2.1831.0):
```

# Steps to reproduce

1. Open windows terminal
2. Open 3 or more terminal tabs

# Expected behavior

The 3rd tab and other tabs thereafter should be clickable making navigation between 3 or more terminals possible.

# Actual behavior

The 3rd and subsequent tabs are hidden behind the close/maximize/minimize bar and therefore it is impossible to navigate between these terminals.
![Screenshot_284](https://user-images.githubusercontent.com/50880261/60770679-6b310980-a0a3-11e9-8682-ead46ec1f2f7.png)

**Comment by Luuk34** [comment]
Suggestion for better title:
There is no way to display the list of opened tabs, which can be a problem when opening more then 3 tabs.

**Comment by ibuioli** [comment]
You can use Mousewheel Scroll for navigate between Tabs. Even with that, there are some graphicals bugs being discussed on #1375

**Comment by Kvanrooyen** [comment]
A work around I found: change the size of the window, and the hidden tab will appear again

**Comment by hassaananjum** [comment]
I think there should be a dropdown to select the open tabs. And the tab size should just shrink like the browser tabs. The header can be shown as a tooltip.

**Comment by nxtexe** [comment]
> I think there should be a dropdown to select the open tabs. And the tab size should just shrink like the browser tabs. The header can be shown as a tooltip.

How though? It doesn't show as a dropdown for me no matter how many times I resize the window. Is there a setting I am missing in the .json?

**Comment by DHowett-MSFT** [comment]
This is just another version of #857
