### ISSUE TITLE
Sanitize paths when pasting into a bash shell

### ISSUE THREAD

**Issue by axfelix** [microsoft/terminal#1858]
# Summary of the new feature/enhancement

Not sure if this is out of scope, but it would be nice if Windows Terminal could automatically sanitize paths (e.g. quoting spaces, inverting or escaping Windows-style slashes) when pasting to a non-cmd, non-Powershell environment. ConEmu's Far Manager does this and it makes mingw bash much more usable.

# Proposed technical implementation details (optional)

Automatically make assumptions about the running shell and change pasted paths to match the interpreter flavour.

P.S.: Just noticed you already fixed the Windows Terminal gsyncing my entire desktop when it's focused, thanks! If you add this feature and a warning on quitting when you have an ssh connection open or another running program, I'll be really happy to switch to using Windows Terminal fulltime!

**Comment by DHowett-MSFT** [comment]
This'll be similar to #904; there's a bunch of pain in "detecting" on both sides of this problem.

The first is pain in detecting _what is a path_; for example, `/Windows` is a valid path to powershell on Windows, but it looks like an absolute WSL path.

The second is detecting what the shell is on the other end of the terminal. For local shells it's possible, although easily fooled (wsl -> powershell.exe -> cmd.exe should be detected as cmd but the terminal only knows about wsl), and for remote shells it is impossible in the general case. :smile:

**Comment by DHowett-MSFT** [comment]
Also, this is #1772 :smile:
