### ISSUE TITLE
Bug Report - Color command not working in cmd

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1861]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Start Windows Terminal,
Open a tab of cmd,
Type this command in the prompt,
```
color 1
```
Any color (number) will do,
Change to a new tab of cmd,
Changes were not saved into the profiles.json.

# Expected behavior

1. Upon issuing the color command it should save the font color into profiles.json.

# Actual behavior

Screenshot belows show what it looks like:
<img width="825" alt="Bug-report-1" src="https://user-images.githubusercontent.com/50003738/60782255-84f05080-a178-11e9-9943-2d4844335763.png">
![image](https://user-images.githubusercontent.com/50003738/60782273-9174a900-a178-11e9-9db0-ade900173617.png)

**Comment by DHowett-MSFT** [comment]
Color has never been a command for changing permanent settings.

**Comment by TayYuanGeng** [comment]
My bad.
