### ISSUE TITLE
Windows Vim crashes terminal when I close the tab

### ISSUE THREAD

**Issue by 0x00000FF** [microsoft/terminal#1863]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18932.1000]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56), 32bit Console version, [Korean]
```

# Steps to reproduce
Start windows terminal with PowerShell 6.2.0 and runs Vim with `vim`.
`PATH` for vim was `C:\Program Files (x86)\Vim\vim81`.
Close tab with vim is running.

# Expected behavior
Tab must be closed. If the tab was only one, terminal must be terminated.

# Actual behavior
Entire terminal is crashed.

**Comment by TayYuanGeng** [comment]
Correct me if I am wrong, Windows Vim is your last tab and you're attempting to close the terminal through the tab?

**Comment by 0x00000FF** [comment]
Whether the tab is last or not, Terminal always crashed when I close a tab which is running Windows Vim

**Comment by TayYuanGeng** [comment]
Seems like a similar issue to #36

**Comment by 0x00000FF** [comment]
I don't think so, because there's no cpu or memory fluctuation, terminal just stays without any responses.

**Comment by RichardSlater** [comment]
Confirmed this as happening on Dev Build compiled from source with master at commit 7eae91:

```
Windows:     10.0.18362.0
PowerShell:  5.1.18362.145
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)
```

Attached profiler showed no change in memory consumption and CPU dropped to 0%, event viewer reports:

```The program WindowsTerminal.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 3724
 Start Time: 01d53576439f9dd6
 Termination Time: 7
 Application Path: C:\source\richardslater\terminal\src\cascadia\CascadiaPackage\bin\x64\Release\AppX\WindowsTerminal.exe
 Report Id: f8bc8e57-e771-400e-b1e0-c9634c1baab9
 Faulting package full name: WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe
 Faulting package-relative application ID: App
 Hang type: Cross-process
```

Only occurs in PowerShell and CMD, not in WSL Bash (Ubuntu) and seems to occur regardless of whether the tab is the last tab, first tab, middle tab, etc.

**Comment by zadjii-msft** [comment]
IIRC this crash is #1380, but @DHowett-MSFT can correct me if I'm wrong. It seems like it's still happening even after the fix from that issue.

**Comment by DHowett-MSFT** [comment]
This is almost certainly #1380 (we love this bug, we just keep bringing it back)
