### ISSUE TITLE
[Feature Request] A confirmation dialect window show up before closing the current tab.

### ISSUE THREAD

**Issue by were** [microsoft/terminal#1864]
# Summary of the new feature/enhancement

Is it possible, to implement something like this:
When there is an active process in the current tab, a confirmation dialect window may show up before actually closing.

When I was writing vim, I need to use `C-W` to switch among vim tabs.
`C-W` is also the hotkey to close the current tab.
When the first two times I ran into this problem, I suppose it was some crashing thing.
Finally, I realized it was a hotkey conflict.

# Proposed technical implementation details (optional)

I did not dive into the code base of this project yet, but I hope it is not too hard to implement.

**Comment by zadjii-msft** [comment]
This seems like a good feature request. I think we've mentioned it somewhere else in another thread, but this is a good setting. Something like:

```json
"promptBeforeClosing": bool
```

or similar, to control whether the dialog appears or not. Or something like 

```json
"suppressCloseDialog": bool
```

and display the dialog by default when we notice there's more than one child\* process attached to the terminal

\*: not including conhost of course

**Comment by were** [comment]
Is there any branch implementing this? If not, I can take it.

**Comment by zadjii-msft** [comment]
@were nope, not yet. Feel free to take a stab at it!

**Comment by zadjii-msft** [comment]
Hey so this was partially implemented in #2526, to resolve #1589.

There's also #2976, which tracks a follow-up to #2526 to connect more settings to the dialog. Since that issue seems to have a few more details, I'm going to close this one in favor of that one. Thanks!

/dup #1589
/dup #2976
