### ISSUE TITLE
How to customize commands?

### ISSUE THREAD

**Issue by LewisTian** [microsoft/terminal#1866]
I installed the terminal from the app store and I want to customize some commands.

for exmaple:

|  Key Binding  | Desc             |
|  -------------  | -------------  |
| ctrl+shift+c   | copy selected  text      |
| ctrl+u            | clear cmd     |

Thanks in advance.

**Comment by babafeng** [comment]
CTRL+L clear cmd

**Comment by carlos-zamora** [comment]
Here's a blog post on a few of the neat things you can do to customize your terminal: https://devblogs.microsoft.com/commandline/windows-terminal-microsoft-store-preview-release/

You can also check out our docs folder in `/doc/cascadia`. We're populating it more and more as we go. One doc of interest here might be [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)

If there's any commands you want us to create, please submit an issue as a feature request. 😊

**Comment by LewisTian** [comment]
thanks :D
