### ISSUE TITLE
Feature Request: Support environment variables for icon

### ISSUE THREAD

**Issue by alefranz** [microsoft/terminal#1867]
# Summary of the new feature/enhancement
Using environment variables for icon path is currently not working.

## Current behavior
```
"icon" : "%SystemRoot%\Installer\{90CBDC15-F4FE-49D2-A245-EC066B70845F}\PowerShellExe.ico"
```
cause the terminal to crash.

## Expected behavior
This should work and be equivalent to
```
"icon" : "C:\\Windows\\Installer\\{90CBDC15-F4FE-49D2-A245-EC066B70845F}\\PowerShellExe.ico"
```

**Comment by zadjii-msft** [comment]
I believe this is a subset of work that needs to be done in #1468, but it's atomic enough that someone could fix this without fixing the larger issue.

**Comment by DHowett-MSFT** [comment]
We should almost certainly genercizise the environment string expander from profile/cascadaisettings.
