### ISSUE TITLE
QOL Feature Request - let us drag from anywhere in the title bar

### ISSUE THREAD

**Issue by jefflindholm** [microsoft/terminal#1870]
# Summary of the new feature/enhancement
Simply let the window to be moved around anywhere on the title bar, right now it is a very small section between the menu drop down and the system menu. This is purely a QOL issue, but it is one I noticed within 1 minute of starting the console.

Regardless, great work. Thanks

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Please search before filing new issues - this is #564
