### ISSUE TITLE
Bug Report - Icon in taskbar popup is missing

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1875]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Pin Windows Terminal in your taskbar,
Right click on the terminal icon,
Terminal icon in popup is missing.

# Expected behavior

1. Terminal icon should appear in the popup.

# Actual behavior

Screenshot belows show what it looks like:
![image](https://user-images.githubusercontent.com/50003738/60820759-b565d800-a1d4-11e9-91ec-3627693d76c4.png)

**Comment by DHowett-MSFT** [comment]
None of us are able to reproduce this, and it's probably a shell issue. If you can reproduce this (even after the `0.2.1831.0` update,) please submit it via the feedback hub in the category "Desktop Environment", "Taskbar"
