### ISSUE TITLE
Bug Report - hitting ctl-t when in a WSL2 tab opens a new with a new terminal

### ISSUE THREAD

**Issue by pcause** [microsoft/terminal#1876]
I have Terminal 2.1715.  I have a base powershell tab and a wsl2 tab (Ubuntu).  I am in the WSL2 tab and enter CTL-T and instead of passing through I get a new powershell tab opened.  I think you need to default to something a bit different for this function.

**Comment by TayYuanGeng** [comment]
As of now, you could set it through your profiles.json
```
"defaultProfile" : 
```
I am also wondering if we could have a separate setting for default tab when we open the terminal and another setting for opening new tabs. For example, when you first open the terminal, you get a windows cmd and when you open a new tab it gives you ubuntu bash or PowerShell instead.

**Comment by pcause** [comment]
I think you misunderstood.  I don't want to create a new tab on ctl-t.  i want ctl-t passed through to the app in the tab (WSL).  Actually, I think they need an option for a definition to say that all keys get passed through to the underlying app, or to make several keybindings and allow the definition of a terminal to say which keybinding that terminal wants to use.

**Comment by cinnamon-msft** [comment]
I would recommend changing this keybinding in your profiles.json file to something other than `ctrl+t`:
`{
                "command" : "newTab",
                "keys" : 
                [
                    "ctrl+t"
                ]
            },`
This will free up this keybinding and allow it to be passed to your WSL 2 distro.

**Comment by pcause** [comment]
already did that, but this is not a good default choice.  Linux curses apps use keys like ct-T and other single litter keys with ctl
