### ISSUE TITLE
ignore json profile data not understood

### ISSUE THREAD

**Issue by fredless** [microsoft/terminal#1880]
# Summary of the new feature/enhancement

Current implementation seems to clean up json ~~parameters~~ *entries in the config file* not understood or implemented.  Rather than removing unknown parameters, perhaps just ignore them.

# Proposed technical implementation details (optional)

Moving\syncing profiles.json between profiles\machines with differing builds (i.e. msftstore release versus "nightly") can result in undesired configuration removal.  If you are 2-way syncing profile data it's even worse: configuration removal would head back to the source machine, where the configuration was valid.

**Comment by zadjii-msft** [comment]
This is something that _will_ be fixed by the work that needs to be done for #754. I'll parent it to that deliverable.

**Comment by DHowett-MSFT** [comment]
This is done as of #(the pull request that disabled settings reserialization), actually.
