### ISSUE TITLE
Implement support for more VT sequences and special characters

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#1883]
# Summary of the new feature/enhancement

We need to support more VT sequences and special characters so that when we establish non-Conhost connections those sequences/characters are dealt with. VT sequences such as erase-in-line and special characters such as BEL should be implemented. 

# Proposed technical implementation details (optional)

VT sequences need to be implemented in TerminalDispatch.hpp/cpp and special characters need to be implemented in Terminal.cpp - in  the _WriteBuffer function (these files are in TerminalCore). For reference for how these functions could be implemented, see adaptDispatch.cpp (in TerminalAdapter).

**Comment by oising** [comment]
I'm building out a specification that we will be using to track VT sequence support. See https://github.com/microsoft/terminal/pull/1884

**Comment by zadjii-msft** [comment]
See also: #13408

**Comment by zadjii-msft** [comment]
Tagging for discussion/triage to see if we can de-dupe this with #13408 these days
