### ISSUE TITLE
Background acrylic effect

### ISSUE THREAD

**Issue by loganbaker97** [microsoft/terminal#1886]
Hey folks, I am not sure if it is meant to be this way, but I noticed that when the terminal window is not in focus, the blush/transparency effect stops working and it goes back on when you click on the window again.
![2019-07-08 (1)](https://user-images.githubusercontent.com/28610489/60851976-41bfcd00-a1cc-11e9-99d1-18aeb38c5342.png)
![2019-07-08 (2)](https://user-images.githubusercontent.com/28610489/60851977-41bfcd00-a1cc-11e9-83a3-17d648e92649.png)

**Comment by DHowett-MSFT** [comment]
Yep this is totally by design. The system-level policy for all acrylic is that only an active and focused window is allowed to have it. It is unfortunate :)

**Comment by tuananh** [comment]
that's very sad unfortunate. it seems a little weird that way :(

**Comment by mcpiroman** [comment]
so maybe add setting to break that system policy?
