### ISSUE TITLE
Bug Report - Weird effect on down icon

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1891]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

Open Windows Terminal,
Click on down icon,
Instead of having the effect on the dropdown, it was highlighted on both plus and down icon,
There was a delay from the effect too,
The down icon was highlighted but after 0.5 seconds later the plus icon gets highlighted too.
Apart from that, I am wondering if the dropdown is supposed to fit the side of the terminal? 

# Expected behavior

1. Instead of adding effects on both icon, add it on the icon that was being clicked.
OR
1. The delay of the effect should be eliminated.

# Actual behavior

Screenshot belows show what it looks like:
<img width="219" alt="Bug-report-1" src="https://user-images.githubusercontent.com/50003738/60876099-c9114d00-a26d-11e9-9cd6-b57efd541759.png">

**Comment by widersky** [comment]
Actually this makes sense, because by clicking dropdown button you're having options to create new tab with selected shell 🤔

**Comment by DHowett-MSFT** [comment]
This is just how the "SplitButton" works. Sorry!
