### ISSUE TITLE
Os

### ISSUE THREAD

**Issue by andres25ortega** [microsoft/terminal#1893]
Hi, 

I have a little question, the support for other OS when is this available.

Thanks!

**Comment by 2MuchLag4you** [comment]
Make sure you're on the right version of Windows. You'll need to be on Insider's builds, or wait for the 1903 release, as the Windows Terminal REQUIRES features from the latest Windows release.

> https://github.com/microsoft/terminal#i-tried-running-windowsterminalexe-and-it-crashes

**Comment by DHowett-MSFT** [comment]
Hey, sorry, we're not going to support operating systems below version 1903. There are some important operating system features we depend on.
