### ISSUE TITLE
Weird behavior for fonts with ligatures

### ISSUE THREAD

**Issue by andtit2001** [microsoft/terminal#1903]
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 122f0de
```

# Steps to reproduce

1. Set `"cursorShape" : "bar"` and `"fontFace" : "Fira Code"` in a profile
2. Run Terminal
3. Paste symbol `CYRILLIC SMALL LETTER ER`: `р`
4. Press `Backspace`

# Expected behavior

Symbol must be erased.

# Actual behavior

Cursor "stucks" in the symbol:
![image](https://user-images.githubusercontent.com/47827604/60955354-548bec00-a309-11e9-976a-f3b3ae065b6c.png)

## Another example
![image](https://user-images.githubusercontent.com/47827604/60955415-76856e80-a309-11e9-8e8b-e174ddf312b9.png)

**Comment by zadjii-msft** [comment]
@miniksa may be interested

**Comment by miniksa** [comment]
Curious, but no idea. I welcome anyone to try to figure it out before I get to it.

**Comment by DHowett-MSFT** [comment]
This looks like #666.
