### ISSUE TITLE
GOOS SET BUG

### ISSUE THREAD

**Issue by saxoned** [microsoft/terminal#1904]
I set GOOS=linux in windows terminal,
It does not take effect,
But it take effect in CMD

**Comment by zadjii-msft** [comment]
I'm pretty sure this should be working fine:
![image](https://user-images.githubusercontent.com/18356694/60967823-301c1980-a2e1-11e9-8ae0-368141a5adea.png)


Are you using `cmd` in Windows Terminal, or `powershell`?

**Comment by saxoned** [comment]
![批注 2019-07-11 090730](https://user-images.githubusercontent.com/32501575/61014800-bd33a100-a3bb-11e9-9c1a-8842a9be4287.jpg)
like this!

**Comment by DHowett-MSFT** [comment]
Friend, that's just powershell. Powershell doesn't use `%` for environment variables.

**Comment by DHowett-MSFT** [comment]
[Here](https://ss64.com/ps/syntax-env.html) is a helpful resource about how to use environment variables from powershell.

**Comment by saxoned** [comment]
ok,thanks very much~
