### ISSUE TITLE
Is there a method for Windows Terminal to set wt.exe as default instead of cmd.exe when run a console application program?

### ISSUE THREAD

**Issue by yanglr** [microsoft/terminal#1907]
Since there is a setting for `ConEmu` to set itself as default terminal for console application (see below).
![image](https://user-images.githubusercontent.com/3152813/60959918-9df52f00-a33b-11e9-98c2-3e13b29fca32.png)

So I wonder is there a method for Windows Terminal to set wt.exe as default instead of cmd.exe when run a console application program? Looking forward to your reply~

**Comment by zadjii-msft** [comment]
This is work that's being tracked by #492
