### ISSUE TITLE
I don't want to/can not update Windows but I love to use terminal, what should I do?

### ISSUE THREAD

**Issue by dehghani-mehdi** [microsoft/terminal#1909]
Hi,

I'm a developer like you and I can not/don't want to update Windows, _I have my reasons_ (_I'm using Windows 10 btw_), but I love to use Terminal, because its features are essential to me (and all developers I think), so what should I do?

Please don't tell me there is no way but updating Windows.

Thank you.

**Comment by lucas-gautier** [comment]
https://github.com/microsoft/terminal/blob/master/README.md#i-tried-running-windowsterminalexe-and-it-crashes

See this readme section.

**Comment by zadjii-msft** [comment]
> the Windows Terminal **REQUIRES** features from the latest Windows release.

Unfortunately, there's really no workarounds available to us. XAML Islands is the technology we use to host our XAML UI in a Win32 process. Without that, we'd be unable to display anything. Since XAML Islands is only complete as of the latest Windows 10 release, there's nothing we can do about it.
