### ISSUE TITLE
Bug Report: Dark Theme requires settings reload

### ISSUE THREAD

**Issue by mdtauk** [microsoft/terminal#1913]
Despite the **requestedTheme** setting being set to **dark**, the Terminal window opens up in a light theme (which matches my OS default App Mode) and it is only when I re-save the profiles,json file, whilst the window is open, that it redraws as Dark.

# Environment

```none
Windows build number: 18362.207
Windows Terminal version (if applicable): Windows Terminal (Dev Build) - Wed 10 July, 16:56 GMT

Any other software?
```

# Steps to reproduce

Set **requestedTheme** to **dark** in the profiles.json file, and open Windows Terminal.

Once open open and re-save the profiles.json file, change the setting, and the app window will redraw.

Close Windows Terminal, and re-open.

# Expected behavior

Windows Terminal's window should draw in the correct Requested Theme everytime the app is open.

# Actual behavior

The app ignores the theme choice within the profiles.json file, and defaults to the OS system setting for the App Mode.

**Comment by zadjii-msft** [comment]
Yea I'm pretty sure this regressed around #929 time frame. I'm gonna track this as part of #1625.
