### ISSUE TITLE
Document shell icons and their paths

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#1918]
It'd be awesome if [the docs](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) for `profiles.json` included a table enumerating the icons included in the Terminal and their paths.

For example, it's highly non-intuitive that the PowerShell icon is `"ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png"` whereas the icon for Cmd is `"ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png"`.

What, therefore, is the path to the PowerShell Core icon?

**Comment by DHowett-MSFT** [comment]
These aren't really intended to be used by users. They exist to support dynamic profile generation. When we have a settings UI, you can just select from a palette of icons.

**Comment by bitcrazed** [comment]
Either way, we should document these icons' guids.

**Comment by DHowett-MSFT** [comment]
I profoundly disagree! They're an implementation detail, not an implementation on their own!

**Comment by kshji** [comment]
I like to see documented palette of icons - which I can select to tell me tab using.  Example current Ubuntu bash icon is not same as I use directly wsl bash, like to change it. It would be nice to see set of icons which user like to select to tell meaning of tab. Same way as you setup ex. favicon in netsite/tab.
In "real" program you can setup icon from set of icons. But this "apps" you can't ?  Ex. I like to set some icon to this Window Terminal which are not so much as PS cmd window has been.

**Comment by ffes** [comment]
Since @DHowett-MSFT doesn't want to document them, and we (the users) don't have a UI at the moment and I was curious what icons I could use, I searched and found https://github.com/microsoft/terminal/tree/master/src/cascadia/CascadiaPackage/ProfileIcons

There you have the 5 GUIDs that are available at the moment :wink:

**Comment by md2perpe** [comment]
It's also possible to use ordinary URL:s. For example, I added [Git bash](https://gitforwindows.org/) and used [this git logo URL](https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png) for `"icon"`.

**Comment by bitcrazed** [comment]
@md2perpe We'd recommend referring to local files, NOT URLs - the latter may take considerable amounts of time to retrieve (if at all) and since the image you refer to is quite large, it'll take a noticeable amount of time for it to be reduced down to 32x32px. Combined, this will likely result in a poor experience, and perhaps intermittent "disappearing" icons.

**Comment by DHowett-MSFT** [comment]
To add to that, you probably don't want to be making a web request to a remote server every time you launch Terminal. :smile:

**Comment by bitcrazed** [comment]
@ffes While I agree to some point, as stated [here](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#icons):

>  Note: Do not rely on the files referenced by the ms-appx URI Scheme - they are considered an internal implementation detail and may change name/location or may be omitted in the future.

We're going to be working on a settings UX in the future, but for now if you want to use specific icons, we encourage you to create & refer to your own icon collection.

**Comment by kjmitch** [comment]
For others' future reference, I added a line to my `profiles.json` file:

`"icon": "file:///c:/users/<username>/icons/bash_logo_32x32.png"`

This points to an icon file in a completely different folder than whatever `ms:///appx` points to, and it worked once I saved the profile. I didn't even have to reload the program for it to apply.

**Comment by Devilmoon** [comment]
Can confirm the process outlined by @kjmitch works in 1.0; I don't know if this is intended behaviour but when displaying a PNG the terminal won't keep the transparency but rather use a white background.

**Comment by DHowett** [comment]
Well, uh, all of the PNGs that come with terminal have transparency in them. . .

**Comment by bitcrazed** [comment]
FWIW, I keep a folder called "WindowsTerminal" in my OneDrive in which I stash all the icons and background images for the shells etc. that I use, and which are automatically synchronized across all my machines.

![image](https://user-images.githubusercontent.com/961950/82487175-e1a7e180-9a92-11ea-963e-885ef9bdc3eb.png)

Then in my settings.json, I just need to specify `"%USERPROFILE%/OneDrive/WindowsTerminal/...` to reach any of those files.

This makes it MUCH easier to keep my profiles tuned just the way I like them. 

Bonus tip: Once I have my settings the way I like them, I also keep a backup copy in the aforementioned OneDrive folder so I can just copy it onto new/re-paved machines.

**Comment by bitcrazed** [comment]
@Devilmoon - I bet if you open your PNG in Paint.NET, you'll find that it has a white background. If it's transparent, you'll see a gray and white chequerboard pattern indicating areas of transparency.

You can use Paint.Net's magic wand & selection tools to select & delete white areas, revealing the transparency chequerboard - see left hand side of Dustin's profile image here 😜:

![image](https://user-images.githubusercontent.com/961950/82487562-609d1a00-9a93-11ea-8cdf-de470a1fb773.png)

**Comment by Devilmoon** [comment]
@bitcrazed Yes, that seemed to be the case even though I had downloaded what seemed like a transparent PNG image from Google. However after manually removing the background it now works as expected.

**Comment by JimF42** [comment]
> FWIW, I keep a folder called "WindowsTerminal" in my OneDrive in which I stash all the icons and background images for the shells etc. that I use, and which are automatically synchronized across all my machines.
> 
> ![image](https://user-images.githubusercontent.com/961950/82487175-e1a7e180-9a92-11ea-963e-885ef9bdc3eb.png)
> 
> Then in my settings.json, I just need to specify `"%USERPROFILE%/OneDrive/WindowsTerminal/...` to reach any of those files.
> 
> This makes it MUCH easier to keep my profiles tuned just the way I like them.
> 
> Bonus tip: Once I have my settings the way I like them, I also keep a backup copy in the aforementioned OneDrive folder so I can just copy it onto new/re-paved machines.

FYI @bitcrazed : I really liked your idea, but when I used this in my office environment, this didn't get resolved correctly--probably due to folder redirection or some such. But, what I can use everywhere is `"%OneDrive%/WindowsTerminal/...` Thanks.

**Comment by bitcrazed** [comment]
Hey @JimF42 - thanks for the tip - if you configure OneDrive for Business on your machine, then %ONEDRIVE% points there, not to your personal OneDrive.

Looks like one could also use `%ONEDRIVECOMMERCIAL%` and `%ONEDRIVECONSUMER%` too:
![image](https://user-images.githubusercontent.com/961950/82592054-22682f00-9b55-11ea-9495-beecb2cf4481.png)

Updating my settings.json now :)
![image](https://user-images.githubusercontent.com/961950/82592312-8e4a9780-9b55-11ea-990b-632943948dd9.png)

**Comment by weitzhandler** [comment]
Where is the Windows terminal icon itself located?

**Comment by bitcrazed** [comment]
@weitzhandler This what you're looking for? https://github.com/microsoft/terminal/tree/master/res/terminal

**Comment by weitzhandler** [comment]
Yes! But where is its location on the windows installation?

**Comment by bitcrazed** [comment]
Windows Terminal is a modern, packaged app. All packaged apps are installed by the Windows packaged app installation engine into the protected `C:\Program Files\WindowsApps\<app>` folders.

Because it's a modern app, Windows Terminal doesn't contain an `.ico` icon file per se., but instead contains several multi-resolution images in the app's `images` folder.

May I ask why you're trying to file Terminal's icon/tile image files on disk?

**Comment by imthenachoman** [comment]
@bitcrazed I, personally, want to set the icon to a shortcut I made to `C:\Users\nacho\AppData\Local\Microsoft\WindowsApps\wt.exe. I do not use Windows 10 style pinned apps and prefer the Windows 7 style Quick Launch folder in my taskbar. But the `wt.exe` shortcut doesn't have the Windows Terminal icon -- it has the default/generic one. So I am [trying to find the Windows Terminal `.ico` file so I can set the icon in my shortcut](https://github.com/microsoft/terminal/issues/7682).

**Comment by zooboo44** [comment]
The default icons that Windows Terminal is using is here: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_#####

To get into the WindowsApps folder you will need permission. However, if you do not want to mess with permissions, you can do the following.

1. Open the Windows Terminal App
2. Click the drop-down arrow.
3. alt+click settings -that opens the default .json file
    I would recommend opening it up in VS Code
4. Right click the tab and click "Reveal In File Explorer"
5. The icons are located in the ProfileIcons

To use these icons keep the `ms-appx:///ProfileIcons/` then just add the icon name and extension.

**Comment by DHowett** [comment]
We reserve the right to change the names of and paths to these icons.

**Comment by imthenachoman** [comment]
@zooboo44 Thanks! I appreciate it. I was looking for the main icon for terminal icon, the one with `>_`, in an `.ico` format. I don't need the specific terminal type icons. But I was able to use `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_####\wt.exe` to get to it. Thanks~

@DHowett Got it.

**Comment by TheFern2** [comment]
> FWIW, I keep a folder called "WindowsTerminal" in my OneDrive in which I stash all the icons and background images for the shells etc. that I use, and which are automatically synchronized across all my machines.
> 
> ![image](https://user-images.githubusercontent.com/961950/82487175-e1a7e180-9a92-11ea-963e-885ef9bdc3eb.png)
> 
> Then in my settings.json, I just need to specify `"%USERPROFILE%/OneDrive/WindowsTerminal/...` to reach any of those files.
> 
> This makes it MUCH easier to keep my profiles tuned just the way I like them.
> 
> Bonus tip: Once I have my settings the way I like them, I also keep a backup copy in the aforementioned OneDrive folder so I can just copy it onto new/re-paved machines.

Do you keep these icons on github or share somewhere? Don't feel like fetching and googling to get all these icons. I thought the terminal would have some default ones to use.

**Comment by waf** [comment]
I've uploaded a collection of icons here: https://github.com/PacktPublishing/Windows-Terminal-Tips-Tricks/tree/main/Chapter%2004 (in the `icons` subdirectory).

**Comment by TheFern2** [comment]
@waf Nice, I also had done the same a while back.

https://github.com/TheFern2/windows-terminal-icons

**Comment by sdudnic** [comment]
Please, give me an advidce I customized the PowerShell icon, but was not good, I now need to restore the former (default) icon. Where can I found the default PowerShell icon?

**Comment by sdudnic** [comment]
> @sdudnic If you just delete the `icon` set for your Windows PowerShell profile, it should fall back to the default one.

and the default one is take from the PowerShell .exe directly?

**Comment by DiHydro** [comment]
The best thing about the devs seeing this thread is they can see how much work users are putting into collating and distributing icon sets to share, because there was no way for them to have a repository that could just let the user select an icon from some sort of dropdown or file browsing prompt. 
/s

The thing that actually annoys me the most is that my icons broke after either Kali or Ubuntu updated, and now they default to the linux icon. Finding the URIs for the original icons seems impossible in the settings as of right now.

**Comment by Witchilich** [comment]
The default icons are useful to users who need them. For example, I use Yori(a modern CMD replacement), whose prompts can be customized like any modern shell(PowerShell, Z shell) with modern features like tab completion and can also function as a replacement of cmd. I set it to the default cmd icon `ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png`. 
But in Windows 11 when I open a bat file with Windows Terminal it uses some default cmd profile to run that script and uses this icon 
![image](https://user-images.githubusercontent.com/56309157/207569073-40bca0af-f4ab-4785-a213-73185df8b609.png)
What is this icon and where can I find it?

**Comment by zadjii-msft** [comment]
Ah, good eye, the docs should be updated. 

If there's _no_ icon specified, we'll fall back to this glyph from [Segoe Fluent](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font):

Glyph | Unicode point | Description
-- | -- | --
![](https://learn.microsoft.com/en-us/windows/apps/design/style/images/glyphs/segoe-fluent-icons/e756.png)  | e756 | CommandPrompt

**Comment by qJake** [comment]
I came here after seeing the glyph from Segoe Fluent, seeing that it was just a text value, copying+pasting it, finding out its Unicode value, and then googling for what `U+E756` was.

This is actually a super useful trick! If you can copy the actual Unicode character for one of the glyphs in the Segoe Fluent font, you can have crisp, matching icons for all your profiles. For example, if you copy the actual character `U+EA18` (use PS or an online tool) onto your clipboard and paste it into the icon setting textbox in Terminal's Profile Settings, you correctly get a shield:

![image](https://user-images.githubusercontent.com/652006/211387733-fb7c212e-f6a8-4d02-996b-b49094a6d26e.png)

Neat!

**Comment by ruguysgoingtrickortreating** [comment]
Worth noting: all the icons are fully available at `C:\Program Files\WindowsApps\[Microsoft.WindowsTerminal... version name etc here]\ProfileIcons`

All of them can be made the profile icon by copying the full filename of the icon and appending it to `ms-appx:///ProfileIcons/` in the Icon field in settings.

![Image](https://github.com/user-attachments/assets/f4a61c33-029b-4d76-a676-ec1915c98c45)
![Image](https://github.com/user-attachments/assets/644d7b74-3f65-4f40-a974-ac2ab60cdb27)
