### ISSUE TITLE
Feature Request (default type tab)

### ISSUE THREAD

**Issue by OraUser** [microsoft/terminal#1922]
# Summary of the new feature/enhancement

By default, the PowerShell tab opens. And even with a single open CMD tab, PowerShell always opens.

# Proposed technical implementation details
The user uses only CMD and should be able to select the default tab type (CMD or PowerShell)

**Comment by DHowett-MSFT** [comment]
You should read the documentation. Specifically, focus on the `defaultProfile` setting.

**Comment by OraUser** [comment]
I changed profiles in places, but did not copy GUID CMD.

Thank you for the support.
