### ISSUE TITLE
Bug Report - Clipping Bug on Titlebar

### ISSUE THREAD

**Issue by ffdd270** [microsoft/terminal#1923]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version : 0.2.1831 

Any other software? Nope. 
```

# Steps to reproduce
1. Make tabs more then current terminal width. (tab name should be over the terminal topbar.)
2. Scroll topbar Using Mouse Wheel. 
3. Tab does not appear. but topbar size has increased.

# Expected behavior
 topbar size has increase, and Tab have to appear.

# Actual behavior
 topbar size has increased, but Tab does not appear. 

if close one tab, or increase window size.  now appear hide tab. 

On Two tab added,  Topbar size has increased, but Tab does not appear. 
![image](https://user-images.githubusercontent.com/21333789/61039192-41f8dc00-a409-11e9-8fee-fdc5df0a529d.png)

increase window size, then Tab apeear.
![image](https://user-images.githubusercontent.com/21333789/61039262-60f76e00-a409-11e9-851b-9c84c7fbf400.png)

**Comment by DHowett-MSFT** [comment]
#857
