### ISSUE TITLE
Bug Report - Weird Startup

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1925]
# Environment

```
Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

Click Windows Terminal icon in taskbar,
Weird start up,
Frame appears first for 1.5 seconds,
Followed by the contents.

# Expected behavior

1. Both the frame and contents should appear at the same time.

# Actual behavior

Screenshot belows show what it looks like:

![image](https://user-images.githubusercontent.com/50003738/61047062-2a255600-a411-11e9-8c4f-021a2f15d839.png)

![image](https://user-images.githubusercontent.com/50003738/61047574-66a58180-a412-11e9-8b39-b3ca0b1f7acf.png)

**Comment by zadjii-msft** [comment]
IIRC @Austin-Lamb was going to file some issues on us for _why_ exactly our startup perf isn't the best.

**Comment by DHowett-MSFT** [comment]
Wow, 1.5 seconds is quite a while.

**Comment by DHowett-MSFT** [comment]
Haven't seen this one in a while, so I'm gonna close it out. Let me know if you hit it again!
