### ISSUE TITLE
Text is displayed with blurry font

### ISSUE THREAD

**Issue by NDelt** [microsoft/terminal#1926]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.2.1831 
Any other software? No
```

# Steps to reproduce
Just open the terminal and write some text.

# Expected behavior
Normal font rendering

# Actual behavior
![Capture](https://user-images.githubusercontent.com/46282492/61047073-91df9f00-a419-11e9-8851-8835c5c56e42.PNG)
![Capture2](https://user-images.githubusercontent.com/46282492/61047076-93a96280-a419-11e9-899a-4348a79710c2.PNG)

Text is displayed with blurry and aliased font. (The font is Consolas)

**Comment by DHowett-MSFT** [comment]
Duplicate of #1298
