### ISSUE TITLE
Any documentation on using regular windows shortcut arguments?

### ISSUE THREAD

**Issue by shmediaproductions** [microsoft/terminal#1927]
For example .lnk files or tasks. If I just use cmd.exe I can quickly create shortcuts, tasks, etc. with "cmd /A /C blah blah blah" and integrate it with my scripts. But for the new terminal, the parameters don't do anything unless I actually type them in the terminal window, after starting the app. I thought it was just a syntax or path issue so I tried the real path to wt.exe instead of the shell shortcut but same issue, the terminal window starts up but there's no input. So then I figured I'd just build it myself but it doesn't make any difference if I use wt or wtd. I definitely built it correctly with no errors and it works fine in general but I just can't send any arguments to it from outside the app. Looking at the documentation there's not really any mention of it so maybe this is intentional? But I figured the syntax is probably just different, or maybe I need to prefix the arguments to declare which command line or profile I'm trying to use? But I already had changed the settings to make cmd the default profile, it's not like it was starting in the wrong console.

Really what I'm trying to do is just integrate it with all the other non-hidden command line utilities and scripts I used before I started using this terminal. I have a little mini input field app on my desktop that I use to type quick commands and it runs them in cmd.exe. So I want to migrate that over to the terminal if possible, especially since the input box itself can support any encoding I specify. I also have some random automated scripts that occasionally open up command prompts requesting user input or remote input. All these implementations are super basic, like "cmd %blahblah%" so I figured it would be pretty easy.

But if it's not some simple thing, I'm open to modifying the source code if anyone has a sense of what I'd need to change. I already built it once so I have the whole repo cloned already. Otherwise hopefully some documentation can be added that explains how exactly those simple external command line arguments would be parsed. Thanks!

**Comment by DHowett-MSFT** [comment]
This issue has a couple different layers actually. Let me see if I can pick them apart:

* Launching WT with command line arguments, #607 
   * this will also be helped by #492 when WT can be launched "by default" for cmd/powershell/etc
* Having a profile that has complicated/annoying arguments: just a bug, recently fixed (not released yet) #1090 
* We think it would be cool to let you import .lnk files (one-way) as profiles: #1793

Sorry to send you off to so many different places, but I think that'll help both of us out!
