### ISSUE TITLE
Settings: Not working

### ISSUE THREAD

**Issue by TARDISDweller** [microsoft/terminal#1928]
Whenever I click on Settings - or Ctrl+, - nothing happens. I have tried several times and nothing seems to happen. The other menu items (Windows Powershell, cmd, Feedback, About) work.

**Comment by ExXeptional** [comment]
When I klicked on settings, it opened "profiles.json" in Visual Studio

**Comment by DHowett-MSFT** [comment]
You need to have a json association set. #1460

**Comment by DHowett-MSFT** [comment]
Also, it's on purpose that it opens a json file.

**Comment by TARDISDweller** [comment]
I did have a JSON association but it didn't work. I changed it to something else, then back to noteapad++, and it's working now.
