### ISSUE TITLE
Terminal crashes when invalid font is specified

### ISSUE THREAD

**Issue by intel352** [microsoft/terminal#1930]
When adding Ubuntu to my list of terminals, I followed the example for Debian [here](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md) which referenced "Hack" as the font to use. Every time I attempted to launch the Ubuntu terminal, Terminal would crash without any errors displayed.

Ideally an error should show, suggesting that the font was invalid/missing.

Additionally that markdown doc I referenced ought to either have it's example updated to reference the default font, or else give a warning about fonts must exist or else they will break Terminal.

**Comment by zadjii-msft** [comment]
This looks like a dupe of #550 to me. Either that or #1017.
