### ISSUE TITLE
Absolute path to image needs backslashes escaped (not mentioned in docs)

### ISSUE THREAD

**Issue by intel352** [microsoft/terminal#1931]
Doc: https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md

When I followed this doc, at the bottom of the page it mentions that a typical Windows-style path to an image can be used in the JSON settings. That is only partly correct. I found if the backslashes `\` weren't double-escaped `\\`, then the JSON failed to validate.

That's fine, it's JSON behavior, but this should be noted in the docs.

**Comment by DHowett-MSFT** [comment]
We're happy to accept contributions that improve our docs! Thanks for the report.

**Comment by DHowett-MSFT** [comment]
It looks like this is actually in the docs now.
