### ISSUE TITLE
Feature Request : Make BackgroundImage avaliable for websites

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1936]
# Summary of the new feature/enhancement

Make BackgroundImage avaliable(load) not for only image, also can load websites or html file but just like a image. (Not avaliable to click or type in. It is terminal, not web browser)
( ~~ So I can load like clock website to see the time in the terminal ~~ )

# Proposed technical implementation details (optional)

BackgroundImage also loads website, local html file, etc.. whatever it could be loaded.

**Comment by zadjii-msft** [comment]
I don't think this is a _terrible_ idea. It kinda plays into the idea we were discussing in another thread about having a "stack" of backgrounds. 

Might make more sense as an extension, though I guess that's something to work out when we're designing that.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the suggestion. This isn't something we're going to be pursuing for a while, and it looks like it might not be possible with our architecture today.
I'm going to close this out. Sorry!
