### ISSUE TITLE
UI Bug - Misaligned commands 

### ISSUE THREAD

**Issue by LadyNaggaga** [microsoft/terminal#1941]
# Environment
OS - Windows 10 

```none
Windows build number: Version 10.0.18362.239]
Windows Terminal version (if applicable):0.2.1831.0

Any other software?
```

# Steps to reproduce

-  Type a any command in the new terminal for example `md new_folder_name`
-  change directory to the new folder 
-  Press the arrow up key 
Causes the misaligned text in the terminal and duplication of the text randomly on the terminal window. See the below image 
![Capture](https://user-images.githubusercontent.com/2546640/61137201-17536580-a493-11e9-9eef-1c5eee3c2aea.PNG)

**Comment by DHowett-MSFT** [comment]
That's unusual. Nobody here can reproduce this. Are you sure there aren't more steps?

What version of powershell? of PSReadline?

**Comment by LadyNaggaga** [comment]
Those are they only steps. I am using the Windows Terminal (Preview) Version: 0.2.1831.0

**Comment by zadjii-msft** [comment]
> What version of powershell? of PSReadline?

**Comment by LadyNaggaga** [comment]
Version of Powershell 5.1.18362.145.  Version of PSReadline  2.0.0

**Comment by zadjii-msft** [comment]
@LadyNaggaga You still seeing this? It's been like, 25 releases of the Terminal since this was originally filed, so there's a _very_ good chance this was fixed by now. Sorry this got lost in the backlog!
