### ISSUE TITLE
Documentation Issue: "WxH character" undefined

### ISSUE THREAD

**Issue by jzabroski** [microsoft/terminal#1943]
See this page: https://github.com/microsoft/terminal/blob/master/doc/ConsoleHostSettings.md
And this blog post by @mscraigloewen https://devblogs.microsoft.com/commandline/understanding-windows-console-host-settings/

Both use the phrase "WxH characters" for describing window width and height, but I can't find a definition for this anywhere.  I'm guessing it's a 32 bit value where the upper 16 bits are width and the lower 16 bit value is height, but, AGAIN, I can't find this documented anywhere.

**Comment by jzabroski** [comment]
@mscraigloewen responded on Twitter. 

> WxH stands for Width by Height, it's the fact that things like a Window size store the Width and Height values in the high and low word in the registry's double word values.

Below is my PowerShell script which demonstrates how to pull the values:

```powershell
$windowSize = $(get-item hkcu:\console).GetValue("WindowSize")
$windowWidth = $windowSize -shr 16
$windowHeight = ($windowSize -shl 16) -shr 16
```

Cross-posted on SO: https://stackoverflow.com/a/57013539/1040437

Thanks, @mscraigloewen !

**Comment by tapaswenipathak** [comment]
Hi @jzabroski: I took the liberty for pushing a PR, attached, hope it is useful.

**Comment by jzabroski** [comment]
@tapaswenipathak I do not work for Microsoft, but I recommend adding the above powershell snippet to demonstrate how to manipulate the high-order word and low-order word.
