### ISSUE TITLE
Settings Setup in a Simple Window and copy paste.

### ISSUE THREAD

**Issue by CESBER** [microsoft/terminal#1945]
Hi. 
I like this project very much. Please note that I have troubles to change the program's settings (see below), so that, it is possible that some of my comments/ideas may already be available. 
1) I use Visual Studio and every time I select settings option, a window with Visual Studio code opens. What about having a nice Window to edit the program settings being open by default?
2) What about Ctrl+C and Ctrl+V to copy and paste selected text?
3) What about an option to copy selected text automatically immediately after selection?
4) What about an option to open by default a different terminal (e.g. UBUNTU) that PowerShell?
Regards CESBER

**Comment by musaugurlu** [comment]
@CESBER 
as for question 4, it is available in settings. In profiles.json file, set "defaultProfile" under "globals" to the "guid" of your preferred shell. 

![image](https://user-images.githubusercontent.com/18178232/61159778-2d7d1800-a4cb-11e9-9e5a-1b39a361c844.png)

**Comment by kcd83** [comment]
Regarding #2 - does the new terminal have an option to disable "Quick edit mode"? Which, if I remember correctly, is how to enable ctrl+c/ctrl+v for copy and paste in windows cmd.

**Comment by carlos-zamora** [comment]
> 1. I use Visual Studio and every time I select settings option, a window with Visual Studio code opens. What about having a nice Window to edit the program settings being open by default?

#1564 

> 2. What about Ctrl+C and Ctrl+V to copy and paste selected text?

Copy/Paste is a bindable setting as of #1093. Currently set to CTRL+SHIFT+C/V, I believe.

> 3. What about an option to copy selected text automatically immediately after selection?

#524 

> 4. What about an option to open by default a different terminal (e.g. UBUNTU) that PowerShell?

answered above.

Closing as duplicate x 4
