### ISSUE TITLE
Feature Request: Background image alignment

### ISSUE THREAD

**Issue by trigger-segfault** [microsoft/terminal#1949]
# Summary of the new feature/enhancement

When using the `backgroundImage` profile setting, the image is anchored to the center of the `TermControl`. Background images that have a primary point of interest that is *not* the center are not aesthetically pleasing when either... a large part of this focus is cut off via `uniformToFill`, or the image is centered via `uniform` or `none` and there is a abrupt end to the image before the border of the terminal control.

### Image Example

Here is a background designed for anchoring to the bottom right. If we rely on `uniformToFill`, then we run the risk of the image's focus getting completely cut off. If we use `none` or `uniform`, then the image will display in the middle and abruptly end on the right while the console display has more room. Alignment anchoring would allow us to display the background image as it is intended.

![Preview Figure A (Left) and Figure B (Right)](https://i.imgur.com/kUTPL9P.png)

*Figure A (Left), shows an image making use of alignment. Figure B (Right), shows the outcome of using the same background without alignment.*

# Proposed technical implementation details (optional)

Changes would require two additional profile settings shown below, (with center being the default for both).

```json
"backgroundImageHorizontalAlignment": "center" | "left" | "right",
"backgroundImageVerticalAlignment":   "center" | "top"  | "bottom",
```

These settings will be needed only once, in this location:

https://github.com/microsoft/terminal/blob/02e8389518c7027fa20a99b4642f29f2b6b4ef7a/src/cascadia/TerminalControl/TermControl.cpp#L273-L276

Here, `HorizontalAlignment::Center` and `VerticalAlignment::Center` will be replaced with their respective parsed settings of `backgroundImageHorizontalAlignment` and `backgroundImageVerticalAlignment`.

These two settings will need constant definitions for of their JSON/serialized values, and `Parse`/`Serialize` methods for the enums (in `Profile.cpp`).

## Alternative Setting

One enum setting that combines the flags of `HorizontalAlignment` and `VerticalAlignment` could be used. The setting and values would be as follows:

```json
"backgroundImageAlignment": "none" | "left" | "top" | "right" | "bottom"
                 | "topLeft" | "topRight" | "bottomLeft" | "bottomRight"
```

*A value of `none`, or missing axis alignment, implies that the default action of centering is used. Alternatively `none` could be labeled `center` to make this clearer.*

There are pros and cons to this alternative. The pros being the setting name is shorter, and can be fully modified from a single line in `profiles.json`. The longer enum value names are still relatively simple and easy to remember. The cons being we are not referring to a real existing enum anymore, but a combination of enums. We also require more enum definitions and handling cases than if we made each setting separate. Lastly the implied *centering* with the values of `none`, `left`, `top`, `right`, and `bottom` are not as user-friendly.

**Comment by trigger-segfault** [comment]
This feature also has minor relations to #1936 and the ability to more-thoroughly customize background layout.

**Comment by trigger-segfault** [comment]
I will take a go at writing a PR to implement this as my first contribution. Implementation seems very straight forwards, especially when looking at the structure of the PR that first introduced background images.

**Comment by DHowett-MSFT** [comment]
This seems totally reasonable to me; I'm going to triage it as an accepted feature request. :smile:

I'm not averse to the single setting that you've got in PR in #1959; in general I'm worried that we have too many settings and even though this is technically two enums it's _one setting._ For discussions about schema I'll defer to @zadjii-msft, however, since settings is his area.

Thanks for designing this!

**Comment by DHowett-MSFT** [comment]
I've gone ahead and assigned you, as well, so people know this one is claimed!

**Comment by trigger-segfault** [comment]
Thanks! I’m definitely happy about the preference towards a single setting. This was a very simple and fun first contribution.

Shall I hold off on *undrafting* PR #1959 so that the specifics of the JSON setting can be discussed with zadjii-msft here?

**Comment by zadjii-msft** [comment]
Ah see, I think I am slightly in favor of the two settings, which is a little closer to the raw XAML properties. That being said, I'm not about to start a crusade over this. This seems fine the way it is, so I'll try and take a look at the PR.
