### ISSUE TITLE
Feature Request:  Double-Click Word Select

### ISSUE THREAD

**Issue by jeffbearer** [microsoft/terminal#1950]
It's common for double click to to do a "word select"  Where it will highlight the word clicked on delimiting on space characters.  

When implementing this make sure that periods and colons aren't word delimiters I'd really like to be able to double-click IP and MAC addresses and have them selected.

Extra Credit.  In some terminals a triple click will do something wider.  it would either select the whole line.  Or a wider selection based on only whitespace characters where as a double click might delimit on some printable characters.

**Comment by DHowett-MSFT** [comment]
Hey Jeff, thanks for filing. Please make sure you search for existing issues! We just merged (for the next preview release!) support for double-click selection (with configurable word delimiters!)

The defaults include period and colon, but they're totally customizable.

#1197 #988
