### ISSUE TITLE
About v0.2.1831.0 preview

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#1952]
I have seen you have released `0.2.1831.0` as `.msixbundle` a few days ago but the Store still report as publication date Jun 21 2019. 

Does this mean we cannot update this new preview from the Store? 

I had uninstalled WT because after few days it worked, it stopped working.. So, can I just install it from the `.msixbundle`. How should this package be installed? just double clicking it?

Why you don't release WT as `.zip` or `.tar.gz` so that the user could install it where he prefers?

**Comment by DHowett-MSFT** [comment]
1. I do not understand the basis for your question. V0.2.1831.0 is available in the store.
2. #1386
