### ISSUE TITLE
output of "wsl --help | more" lookes wrong

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#1956]
When typing "wsl --help | more" output shows as 1 column of text.

```
D:\Temp>ver

Microsoft Windows [Version 10.0.18362.239]

D:\Temp>where more
C:\Windows\System32\more.com

D:\Temp>wsl --help | more
C
o
p
y
r
i
g
h
t

```

**Comment by DHowett-MSFT** [comment]
Huh, it looks like WSL is printing to the console in UTF-16. @benhillis may know more about what's going on there.

FWIW: we are not likely to change `more.com` to support UTF-16.
