### ISSUE TITLE
Add a setting to enable the using the Accent Color for the titlebar

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#1963]
# Summary of the new feature/enhancement

My feature request is the following: Currently, there is this huge tab at the left of window Title:
https://i.imgur.com/NkCGn3f.jpg but the problem here is, that I am using an accent color that overwrites the title bar for every application.

So I wanted to ask if it would be possible to give us a feature, that we can change that the color of the title bar on the left to the other color, or at least a feature that it automatically gets the same color as the accent color.

Thanks for reviewing.

**Comment by zadjii-msft** [comment]
I'm changing the title to be slightly more specific.

After #929 we stopped using the accent color, and started drawing the entire titlebar ourselves. 

#1934 made the appearance of the titlebar _better_, but still doesn't use the accent color. 

We'll need some way of setting the resources at runtime to override the Background property of the TitlebarControl (introduced in #1948). 

This is also related to #1625.

**Comment by WSLUser** [comment]
Any way ColorTool can help with this too? At some point, it may be better to merge Terminal and ColorTool together and use ColorTool for the colors and Terminal settings for applying them based on what's configured in the Settings UI (alternatively the json). I don't think too much rework would be needed here as the functionality would remain but the commands used for executing would be altered. While ColorTool can remain useful on it's own, anybody who can will probably use the Windows Terminal, especially once it reaches v1.

**Comment by mdtauk** [comment]
Are you able to query the registry to see if that setting is turned on?

![image](https://user-images.githubusercontent.com/7389110/61492990-74c34700-a9aa-11e9-8b3a-62cc3a7bf552.png)

**Comment by modscleo4** [comment]
> Are you able to query the registry to see if that setting is turned on?
> 
> ![image](https://user-images.githubusercontent.com/7389110/61492990-74c34700-a9aa-11e9-8b3a-62cc3a7bf552.png)

This could be done by accessing the registry key `HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorPrevalence`


```csharp
public Color ThemeColor
{
    get
    {
        var regBaseKey = RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, RegistryView.Registry64);
        var regKey = regBaseKey.OpenSubKey(@"Software\Microsoft\Windows\DWM", RegistryKeyPermissionCheck.ReadSubTree);
        if  (regKey != null)
        {
            var value = regKey.GetValue("ColorPrevalence");
            if (value != null && Convert.ToBoolean(value))
            {
                value = regKey.GetValue("ColorizationColor");
                if (value != null) {
                    var color = (uint)(int)value;

                    return Color.FromArgb(
                        (byte)((0xFF000000 & color) >> 24),
                        (byte)((0x00FF0000 & color) >> 16),
                        (byte)((0x0000FF00 & color) >> 8),
                        (byte)((0x000000FF & color) >> 0));
                }
            }
        }

        // This is the default Windows 10 colorization color
        return Color.FromArgb(0xFF, 0x00, 0x78, 0xD7);
    }
}
```

**Comment by justingallagher** [comment]
I'm interested in taking a shot at a fix for this one. Would make sense to incorporate this into the existing `requestedTheme` setting (for example, adding `darkAccent` or `lightAccent` themes), or introduce an independent setting?

By default we'd want to follow the system setting, I'm hoping there's an API to read the setting in a more elegant way than digging through the registry.

**Comment by zadjii-msft** [comment]
As an update to this thread - this is going to be addressed in a future update as a part of #3327. We're working on a spec currently, but that feature should address this issue in a more unified way with other similar feature requests.

**Comment by Poopooracoocoo** [comment]
should this even be a setting? it should just be on when the windows setting is on

**Comment by zadjii-msft** [comment]
@Poopooracoocoo Yea, I'd still like this to be an independent setting. As a part of #3327, we're going to let people put whatever color they want there (not just their accent color), or match the color to the color in the terminal control, or throw Acrylic up there, or Mica, or whatever. Much more flexible than just the accent color.

**Comment by mdtauk** [comment]
> @Poopooracoocoo Yea, I'd still like this to be an independent setting. As a part of #3327, we're going to let people put whatever color they want there (not just their accent color), or match the color to the color in the terminal control, or throw Acrylic up there, or Mica, or whatever. Much more flexible than just the accent color.
>
With the colour picking, it would be neat to allow assigning the Accent Colour to various elements, like the cursor or selected background.  Obviously when it comes to the theming, then that allows all kinds of possibilities.

**Comment by ijprest** [comment]
Is this really fixed?  The color is influenced by the theme (light or dark), but I don't see the accent color being used, or any settings that reference it.

**Comment by DHowett** [comment]
Yep! If you declare a new theme whose `tabRow.backgroundColor` is `"accent"`, you'll get this:


<img width="358" alt="image" src="https://user-images.githubusercontent.com/189190/190011919-3c5c7329-a1f6-4826-9539-622b77c3424a.png">

```json
    "theme": "Cool Things",
    "themes": 
    [
        {
            "name": "Cool Things",
            "tab": 
            {
                "background": "terminalBackground"
            },
            "tabRow": 
            {
                "background": "accent"
            }
        }
    ],

```

(We should look at offering more inbox themes.)

**Comment by Poopooracoocoo** [comment]
I was disappointed when I installed Terminal Preview and saw that this wasn't enabled when the Windows setting is enabled. Is there an issue for tracking respecting the system preference?
