### ISSUE TITLE
Crashes on startup (v.0.2.1831.0); works only in elevated mode

### ISSUE THREAD

**Issue by kasiagauza** [microsoft/terminal#1966]
# Environment

```none
Windows build number: [Version 10.0.18362.239]
Windows Terminal version: 0.2.1831.0
```

# Steps to reproduce

- Install the Terminal with Windows Store (recent version as of writing, v. 0.2.1831.0).

# Expected behavior

- Terminal opens.

# Actual behavior

- The hollow terminal window blinks for a moment and closes. **The terminal works in elevated mode**, though.

```Event log
Faulting application name: WindowsTerminal.exe, version: 1.0.1907.2001, time stamp: 0x5d1bd2d0
Faulting module name: TerminalApp.dll, version: 1.0.1907.2001, time stamp: 0x5d1bd294
Exception code: 0xc0000005
Fault offset: 0x000000000003a999
Faulting process id: 0x377c
Faulting application start time: 0x01d53a713ed90f7d
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: 414f0462-b94c-4f1c-957c-22929ab60502
Faulting package full name: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment]
Thanks for the report. Would you mind sharing the contents of your `profiles.json`? It should be in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8xxxxxxxxx\RoamingState`

**Comment by braithair** [comment]
I too get this same issue. I can run the Windows Terminal App as administrator, but only as administrator. I regenerated my .json file (Attached below)

It seems relatively stable when running as Admin, I just find that running it as admin is an inconvenience and I gravitate to using another terminal (like the one in VSCode). I know I am lazy haha.

[profiles.zip](https://github.com/microsoft/terminal/files/3424320/profiles.zip)

**Comment by kasiagauza** [comment]
@DHowett-MSFT , here's the file: [profiles.zip](https://github.com/microsoft/terminal/files/3430740/profiles.zip)

**Comment by braithair** [comment]
Hey @kasiagauza - I fixed this issue for myself today! It was that my terminal (default in my case was PowerShell Core 7.0.0 preview) was in "Run as Administrator" mode on the "pwsh.exe". I reversed this setting on the pwsh.exe and presto, fixed - No longer need to run as administrator.

**Comment by DHowett-MSFT** [comment]
@kasiagauza would you mind checking that? If so, we'll track this in #2233 :smile:

**Comment by kasiagauza** [comment]
@DHowett-MSFT @braithair the same here, I've disabled _run as administrator_ setting and the Terminal works now in non-elevated mode. I've double checked it, so this issue may be closed. I'll observe #2233
