### ISSUE TITLE
Take the best from Gnome terminal and simple implement features in windows terminal.

### ISSUE THREAD

**Issue by VGaranja** [microsoft/terminal#1968]
Take the best from Gnome terminal and simple implement features in windows terminal.

**Comment by DHowett-MSFT** [comment]
Thanks for the request. We already have a lot of good terminal features on our backlog, so it isn't very helpful to say "implement all of somebody else's project." We should have a discussion about the features that you'd like to see!

We have plans for panes #1000, a nice settings UI #1564, plugins #555, and literally five hundred other things that have been reported by the community.

Please have a look and follow the ones you're most interested in.
