### ISSUE TITLE
"tabTitle" does not work in version 0.2.1831.0 (from Windows Store), but works in version 0.0.1.0 (from Github)

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#1969]
Microsoft Windows [Version 10.0.18362.239]
Windows Terminal (as named in subject)
   0.2.1831.00 from Windows Store
   0.0.1.0 from Github

# Steps to reproduce
Start Windows Terminal after adding "tabTitle" to the config
(lines like:            "tabTitle" : "tab1",  )

# Expected behavior
Show title as named in "tabTitle" (in this example show "tab1"

# Actual behavior

In version 0.2.1831.0 the tag "tabTitle" is removed from the config directly when starting WindowsTerminal, and the full path to the started application is show, and not the short "tabTitle"

In version 0.0.1.0 (from Github) all works OK

Question:
- What about this confusing version numbers? what's newer than wat, what's better than what, and how is this supposed to work OK, when finally released?

**Comment by DHowett-MSFT** [comment]
### public store builds

the higher the number, the better
check the releases page to see what's changed

### dev build

it'll always be `0.0.1.0`, don't read into it

### `tabTitle`

it's not in 0.2.1831.0.

**Comment by sharifanani** [comment]
Should this issue be reopened if the issue is still present in 0.2.1831.0 (store preview) but not in the build from source?

**Comment by DHowett-MSFT** [comment]
It’s not in 0.2.1831.0, so no? It will never be in 0.2.1831.0. We do not reuse version numbers.

**Comment by sharifanani** [comment]
I'm running 0.2.1831.0 and I'm experiencing it

**Comment by DHowett-MSFT** [comment]
The feature has not yet been incorporated in a version released to the store.
