### ISSUE TITLE
Terminal rendering vs. console rendering

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#1970]
# Environment

```none
Windows build number: 18922
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?

This particular example was generated on Debian Buster with ponysay 3.2.0, but the same rendering issue occurs with other combinations; this is just the one that makes it most obvious.
```

# Steps to reproduce

With WSL installed and a WSL prompt open in Windows Terminal:

```
sudo apt install ponysay
ponysay -q
```

# Expected behavior

![renderingdifferences](https://user-images.githubusercontent.com/371623/61190095-5ed91d80-a65c-11e9-9d20-97c4bfb969a5.jpg)

ASCII art image on the left (Terminal) should match ASCII art image on the right (console), without blur, jaggies, or superfluous underlines.

# Actual behavior

It, well, doesn't.

**Comment by DHowett-MSFT** [comment]
This is probably some combination of #1703, #1626, #404, and #455!

**Comment by cerebrate** [comment]
Aaah, I missed #455 

I've subscribed to all those; will re-open if this persists once they're resolved.
