### ISSUE TITLE
Ctrl+W doesn't terminate shells properly (so they can't do teardown and cleanup things)

### ISSUE THREAD

**Issue by axfelix** [microsoft/terminal#1971]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18917.1000]
Windows Terminal version (if applicable): 0.2.1831.0

# Steps to reproduce

Exit a mingw bash shell using a keyboard shortcut to close the tab

# Expected behavior

`exit` is sent to the shell, process is terminated, if closing a running process the user is warned

# Actual behavior

Terminal is detached and not killed

**Comment by zadjii-msft** [comment]
Maybe we need to consider having an `exitCommand` setting? Though, what would happen if you launched a process from bash where `exit` did _not_ exit the program? For example, `vim`. How would we determine when to send `exit` to the commandline application?

**Comment by axfelix** [comment]
Most terminal apps I've used on other platforms will warn when pressing Ctrl+W if anything else is running, on the assumption that the user probably doesn't want to kill the shell after all, and if they really do then probably all bets are off (you could send Ctrl+C then exit but that's a much less predictable use case anyway).

**Comment by DHowett-MSFT** [comment]
This is absolutely a bug, we shouldn't go and add a new "command to send on exit". That's probably not a winning strategy.

We constrain our shells into job objects, so they _should_ absolutely be getting terminated when the tab is closed.

**Comment by wuss912** [comment]
CTRL + W is also used in a number of curses based apps... need a way to disable it as a kill switch so it can pass through instead

**Comment by axfelix** [comment]
yup, that's why Mac has separation between Ctrl and Cmd and Linux terminals use Ctrl+Shift for any terminal window shortcuts so that Ctrl shortcuts can be sent directly to the term. Not sure if you want to adopt that convention here too.

**Comment by tats-u** [comment]
Ctrl+Shift+W must be used to close the terminal instead

**Comment by shtirlic** [comment]
+1 to `exitCommand `
I use terminal with docker desktop, running as default ENV for development, every new tab started with command like `docker start -ti dev_env zsh`, so when I close the tab, I would like to send `exit 0` to the zsh process, and then tab will be closed since exit code is 0.

**Comment by shtirlic** [comment]
Also update I can autoclose background zsh process with setting TMOUT env for idle timeout as workaround but it's not good because when you leave tabs open it's closes after  TMOUT time, since there is no SIGALRM handling.

**Comment by fprimex** [comment]
I was editing in vim and using `:vert sp` when I discovered this behavior trying to change between splits. There should be an option or default behavior to not close the window with Ctrl+W. On non-mac systems, as @tats-u mentioned, ctrl+shift+w is the keyboard shortcut for window closing.

I feel like this is perhaps a separate issue from not cleaning up the shells. If that's the case I can open a new issue.

**Comment by DHowett** [comment]
Hey @fprimex! Thanks for sticking with us since version 0.2! We actually changed the default for all new users to have `closePane` bound to `ctrl+shift+w` back in v0.3, in July 2019.

It might be a good time to refresh your settings file! Back up the bindings and profiles you care about, delete the file, and let Terminal make a new one. Things have changed _a lot_ since the default was `ctrl+w` for that action. :smile:

**Comment by fprimex** [comment]
Hmm. This is a fresh install from the app store on a recently new-to-me machine that I only got in the past month. All I have changes are the prev & next tab bindings. I will review everything & see if I went wrong somewhere doing the install.

**Comment by fprimex** [comment]
Alrighty, seems fine. Not sure where I went wrong. Maybe I managed to fat finger across ctrl and shift twice earlier lol. Thanks!

**Comment by axfelix** [comment]
This seems to be working now -- I think I'll close this issue. Thanks!
