### ISSUE TITLE
Precision touchpad scrolling (maybe Direct Manipulation API)

### ISSUE THREAD

**Issue by Tarik02** [microsoft/terminal#1980]
### NOTE: This feature is addition to #1066

# Summary of the new feature/enhancement

Scrolling with (precision) touchpad is very convenient but only if application responds to scroll event instantly. This can be observed in Microsoft Edge, vscode, JetBrains IDEs (Smooth Scrolling option).

I think that Windows Terminal should have option to enable scrolling not line by line but pixel by pixel.

**Comment by DHowett-MSFT** [comment]
This seems like a duplicate of #1400, actually! Thanks!
