### ISSUE TITLE
Add List of available commands to SettingsSchema.md

### ISSUE THREAD

**Issue by MindSwipe** [microsoft/terminal#1984]
The list of available commands to bind keys to should be documented somewhere. When searching for it I first found  [doc/cascadia/SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) where profiles.json properties are documented, however the valid values for the command property on keybindings is not documented.  

I then went through the commit history searching for a commit message with "keybind" in it and found [this](https://github.com/microsoft/terminal/commit/b1157998100f34cf8fd254f97e8a3b85f2f5005e) commit modifying [src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp) which has all the options as `static constexpr`

Documenting this would really help other users customize their Windows Terminal adding shortcuts like `splitHorizontal` or `splitVertical` which before didn't have a keybind

**Comment by DHowett-MSFT** [comment]
Great idea.
