### ISSUE TITLE
Auto-generate our SxS manifest

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1987]
I found a todo in the code that I don't think was ever ported to github.
```c++
TODO MSFT#21300206: Switch to automatically generating these.
```

I believe @DHowett-MSFT was working on this before we went open-source, but `mt.exe` wasn't updated to handle our scenario at the time. Not sure if that still applies.

This might affect some of our elevated launch bugs IIRC.

**Comment by DHowett-MSFT** [comment]
Funny enough, I've got just the branch for you! microsoft/terminal@10853a139f9b5481f79b4c329ced9ee3ac4c2e2d
