### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 24Naman** [microsoft/terminal#1990]
# Summary of the new feature/enhancement

Several times a user may need a administrator cmd window for doing some task.
But the current terminal design doesn't allow it. This terminal is beneficial for using multiple command line tools easily.
If the new administrator tab is opened in the current window then it will help user to keep all the command tools in the same window.

# Proposed technical implementation details (optional)

The proposed idea would allow user to access super user cmd/powershell/wsl shell easily.
It can implemented in following ways,
1. A right click on current tab allowing user to open admin window in new tab.
2. A right click on the option in the dropdown list allow user to launch the prompt in administrator mode.
3. A icon alongside the name in the dropdown list to launch list item in administrator mode.

If the new administrator tab is opened in the current window then it will help user to keep all the command tools in the same window.

**Comment by DHowett-MSFT** [comment]
#1032 :smile:
