### ISSUE TITLE
Feature Request: Tab bar, Title bar and App Icon styling

### ISSUE THREAD

**Issue by upeguiborja** [microsoft/terminal#1994]
# Summary of the new feature/enhancement

Current tab styling is ugly, it would be better if some customization options are added:

1. Custom Tabs Position: {Top, Bottom, Sides}
2. Custom Tabs height and font size (Affects oversized + button and down pointing arrow too)
3. Tab opacity and color.
4. Dynamic app icon set per active tab.
5. Custom static text for tab name
6. Tab controls are too far away from window controls, reduce distance or change sides when tabs are on superior position

# Proposed technical implementation details (optional)

Adding configuration options to the profiles.json accordingly should do the job

**Comment by mdtauk** [comment]
The current tabs are using an early version of the control being built in the WinUI repo.  Design has not been applied to the control yet, but Windows Terminal may decide to override that default styling with their own styles.

**Comment by DHowett-MSFT** [comment]
This is a lot of different requests rolled up into one issue. We're probably not going to let you have side tabs, tab color is #1729 and others, dynamic icon is #1868, static text is #1358 (fixed for v0.3), tab controls are too far away is #1375.
