### ISSUE TITLE
Sometimes, tabs delay closing for 2+ seconds

### ISSUE THREAD

**Issue by clounie** [microsoft/terminal#1996]
Looked around for `delay close`, `tab close` etc, couldn't find. Apologies if it's a dup!

# Environment

```none
Windows build number: [Version 10.0.18362.239]
Windows Terminal version (if applicable):  0.2.1831.0

Any other software? No
```

# Steps to reproduce
1. Open Terminal
2. Press "+" button to open new tab or two
3. Fairly quickly after, press `Ctrl+W` multiple times

# Expected behavior
Tabs close instantly upon pressing `Ctrl+W`

# Actual behavior
Sometimes the tab takes awhile (like, multiple seconds) to obey your "close" command via `Ctrl+W`

When this happens, the human gets frustrated, and presses it multiple times, resulting in Terminal being entirely closed after a few seconds.

This makes for a **terrible** first user experience. I couldn't reproduce it every time, but it happened the first two times I opened the terminal, which was all it took to give me a bad first impression.

**Comment by DHowett-MSFT** [comment]
Thanks for the report.. yeah, we've been talking on the team about how to make sure tab closing is as smooth and instant as it can be. Have some ideas here.

**Comment by runemoberg** [comment]
Suggestion: Put the wait circle animation on the tab itself and make sure other tabs remain responsive.

**Comment by zadjii-msft** [comment]
Note to self: the repro we're looking at here is 
* use `ssh.exe` to ssh somewhere (anywhere)
* While it's sitting at the prompt for the password, close the tab. <kbd>Ctrl+Shift+W</kbd> works fine for this.
