### ISSUE TITLE
Windows Terminal does not display a line with Thai text in Emacs properly.

### ISSUE THREAD

**Issue by veer66** [microsoft/terminal#2003]
# Environment

```
Windows: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal: 0.2.1831.0
Remote OS:  Raspbian GNU/Linux 9.8 (stretch) armv7l   
Emacs 25.1.1 with rust-mode
Vim 8.0.707 
```

# Steps to reproduce

1. Open Windows Terminal
2. Run ssh to remote GNU/Linux
3. Download https://file.veer66.rocks/windows/re.rs
4. Run emacs
5. Install rust-mode to Emacs
6. In Emacs, open file re.rs

# Expected behavior

Windows Terminal should display this code:

```Rust
lazy_static! {
    static ref DATE_RE: Regex = Regex::new(r"(\d{4})(\d{2})(\d{2})").unwrap();
    static ref CHUNK_RE: Regex = Regex::new(r"[ก-์]+|\([^\)]+\)").unwrap();
    static ref THAI_RE: Regex = Regex::new(r"[ก-์]+").unwrap();
}
```

like below:

![xfce_term_emacs](https://user-images.githubusercontent.com/370688/61382821-a8816c80-a8d7-11e9-9555-0a2b122bcddd.png)

# Actual behavior

Line 3 was broken.

![win-term-emacs](https://user-images.githubusercontent.com/370688/61382857-bd5e0000-a8d7-11e9-8240-cf6a62abe92c.png)

**Comment by DHowett-MSFT** [comment]
We may have another bug that's better-suited than this laying around. There's a huge problem if this text requires composing characters. We don't support that today. Or, perhaps we're just measuring wrong?

**Comment by metathinker** [comment]
> There's a huge problem if this text requires composing characters. We don't support that today.

The example text in the issue report doesn't include any compositions of multiple characters. It does have the opposite feature: a combining character that has no base to attach to, namely  ์  _thanthakhat_, which is supposed to go over a Thai consonant letter to mark a silent consonant.

For comparison, here is some text in Thai that does use _thanthakhat_ over a letter. I haven't checked whether Windows Terminal displays it correctly, though it sounds like it it currently can't:

> มนุษย์ทั้งหลายเกิดมามีอิสระและเสมอภาคกันในเกียรติศักดิ์และสิทธิ

**Comment by veer66** [comment]
> We may have another bug that's better-suited than this laying around. There's a huge problem if this text requires composing characters. We don't support that today. Or, perhaps we're just measuring wrong?

It wasn't about composing characters, but Latin alphabet text, namely, "]+|\([^\)]+\)" was missing.

![image](https://user-images.githubusercontent.com/370688/61574560-9bd56200-aaeb-11e9-8fd2-9a9c0e0ac436.png)

**Comment by zadjii-msft** [comment]
Oh jeez, this is what we get for leaving bugs open for 9 months. 
![image](https://user-images.githubusercontent.com/18356694/79240372-51dd9a80-7e37-11ea-9b5c-98998884c795.png)
![image](https://user-images.githubusercontent.com/18356694/79240484-789bd100-7e37-11ea-9b5b-1c17c6cc5a67.png)
![image](https://user-images.githubusercontent.com/18356694/79240514-82bdcf80-7e37-11ea-85fb-1e407f76b2a1.png)

I couldn't get `rust-mode` working, but it looks like the original bug here is largely fixed. 

We've ton a _ton_ of improvements to our rendering of composed characters since _0.2_ when this was originally filed. It would be a pain to try and bisect where exactly this got fixed, but I'm inclined to say that it is. 

@veer66 Could you confirm for me that this is working better in and updated version of the Terminal? If it's not fixed in 0.10 for you, then we can pull this back in to 1.0 to investigate. Thanks!

**Comment by veer66** [comment]
Windows Terminal Version: 0.10.781.0 works.

![ภาพ](https://user-images.githubusercontent.com/370688/79565619-45796c00-80db-11ea-96e1-2c3392f25f08.png)

**Comment by zadjii-msft** [comment]
Thanks for following up!

**Comment by izcream** [comment]
I have issues like this on my windows terminal with Thai text

when same line has english and thai text it's will start wrong cursor position(picture below show cursor was highlight at `n` character not `i` character in last word_[Thai]_ of line)

![cursor](https://user-images.githubusercontent.com/10282500/177830826-c9ede5eb-eeb1-491a-bba5-6fe2df7b378d.png)

picture below show strange text when trying to type word "สวัสดีครับ" in terminal

picture below show the correct cursor position(open same file in vscode)
![cursor2](https://user-images.githubusercontent.com/10282500/177831203-49689ee4-9780-429e-a073-0467b988fe21.png)

![common](https://user-images.githubusercontent.com/10282500/177831984-0d0fc339-daf8-4b4e-88c6-49e1b0794e33.png)

have any solution to solve this?

my machine info
Windows 11 Home version 21H2 build 22000.778
Windows Terminal PreviewVersion: 1.15.1863.0

**Comment by admin-ssg** [comment]
Version: 1.21.1272.0 still have issue with Thai words

![image](https://github.com/microsoft/terminal/assets/123747046/86864cf4-f854-4df3-8595-4d5d69e51bd7)
