### ISSUE TITLE
We're hiring!

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2008]
**Hey!** If you're interested in working on the Windows Terminal and other Windows developer initiatives, have a look at [our job posting](https://careers.microsoft.com/i/us/en/job/659301/SOFTWARE-ENGINEER-II)!

> Do you want to help make Windows the best place for developers? The Windows Terminal team is looking for motivated engineers who want to help shape the future of text-mode applications on Windows. We own the new tabbed, acrylic, fully customizable Terminal and the Windows console infrastructure, as well as several other projects and initiatives that seek to empower developers. And all the work we’re doing is out in the open, using GitHub to directly interface with customers and contributors.

If you have any questions, feel free to send me an e-mail (the address is in my GitHub profile, @DHowett-MSFT) or a direct message on [Twitter](https://twitter.com/DHowett).

_There are currently no postings._

**Comment by JeanPhilippeKernel** [comment]
How I can  fix this issue ?? :) can I take it ??

**Comment by SteveL-MSFT** [comment]
The `Help-Wanted` label color seems out of place...

**Comment by zadjii-msft** [comment]
@miniksa you're my favorite

**Comment by utybo** [comment]
Damn that label list is satisfying
![image](https://user-images.githubusercontent.com/5175705/61580407-3b0d5000-ab12-11e9-90eb-5badef1e4598.png)

**Comment by jeditobe** [comment]
ReactOS is better... 
Much freedome, more opensource.
And they are hiring too https://reactos.org/node/785

**Comment by miniksa** [comment]
> 
> 
> @miniksa you're my favorite

Aww shucks.

**Comment by JushBJJ** [comment]
Thats some big issue. 🤔

**Comment by adiviness** [comment]
Perhaps I should apply.... I always wanted SDE2 😂🤣

**Comment by johnmorrisbeck** [comment]
I applied and I suggest anyone who would like a very important job to do the same. The fate of windows programming hangs in the midst of this project. Backwards and forwards compatibility is thrown in huge jeopardy by merging unix and windows, even on an experimental level. When it reaches windows stable and the first 1% of users get it that's like in the movies when to moving bodies are in orbit and they sync up and lock on to each other magnetically or what have you. The level of engineering on a project like this one is critical, it HAS to work.

**Comment by knilecrack** [comment]
too bad I'm not that good with C++

**Comment by miniksa** [comment]
> too bad I'm not that good with C++

The longer I work on C++, the more I am convinced that literally no one is good at C++.

**Comment by ihodev** [comment]
I wish you find the right people! I appreciate the work you are doing. We can wait but isn't better to fix existing bugs before introducing dozens of features that could bring the other bugs.

**Comment by yc-zc** [comment]
> > too bad I'm not that good with C++
> 
> The longer I work on C++, the more I am convinced that literally no one is good at C++.



> **Hey!** If you're interested in working on the Windows Terminal and other Windows developer initiatives, have a look at [our job posting](https://careers.microsoft.com/i/us/en/job/659301/SOFTWARE-ENGINEER-II)!
> 
> > Do you want to help make Windows the best place for developers? The Windows Terminal team is looking for motivated engineers who want to help shape the future of text-mode applications on Windows. We own the new tabbed, acrylic, fully customizable Terminal and the Windows console infrastructure, as well as several other projects and initiatives that seek to empower developers. And all the work we’re doing is out in the open, using GitHub to directly interface with customers and contributors.
> 
> If you have any questions, feel free to send me an e-mail (the address is in my GitHub profile, @DHowett-MSFT) or a direct message on [Twitter](https://twitter.com/DHowett).
> 
> ### Postings
> * [**Software Engineer II**](https://careers.microsoft.com/i/us/en/job/659301/SOFTWARE-ENGINEER-II)
>   
>   * This position is for a software engineer with a couple years of experience who's comfortable with C++ and really loves text-mode applications.

Thank you so much for the work!

**Comment by praveensvsrk** [comment]
I work on C++ but I only have 1 year of experience :(

**Comment by DHowett-MSFT** [comment]
@praveensvsrk you should still e-mail me :smile:

**Comment by eduardonunesp** [comment]
Super-duper interested on this project would be awesome to contribute to the Terminal application, Windows 10 and WSL is a game-changer that deserves a great terminal to work on command-line applications

**Comment by DHowett-MSFT** [comment]
Since there aren't any postings, I'm closing this one out for now. Thanks for playing!

**Comment by xgdyp** [comment]
> **Hey!** If you're interested in working on the Windows Terminal and other Windows developer initiatives, have a look at [our job posting](https://careers.microsoft.com/i/us/en/job/659301/SOFTWARE-ENGINEER-II)!
> 
> > Do you want to help make Windows the best place for developers? The Windows Terminal team is looking for motivated engineers who want to help shape the future of text-mode applications on Windows. We own the new tabbed, acrylic, fully customizable Terminal and the Windows console infrastructure, as well as several other projects and initiatives that seek to empower developers. And all the work we’re doing is out in the open, using GitHub to directly interface with customers and contributors.
> 
> If you have any questions, feel free to send me an e-mail (the address is in my GitHub profile, @DHowett-MSFT) or a direct message on [Twitter](https://twitter.com/DHowett).
> 
> _There are currently no postings._

Hello, I am a student and my research work is to explore Github log data and find some interesting metrics, this issue is one of the issues with the most issue label colors in year 2021 hahaha

**Comment by ZhiyuanChen** [comment]
LOL, who knows, I'm leaving MSFT in a few months. I can never imagine I'll be here one day back then
