### ISSUE TITLE
Raster/VGA/Code page 437 font

### ISSUE THREAD

**Issue by ghosttie** [microsoft/terminal#2013]
It would be nice if the Terminal had the option to use raster fonts, or if there was an official TTF version of the VGA/Code page 437 font.

In the past people have created unofficial TTF versions of the Code page 437 font ([Perfect DOS VGA 437](https://www.dafont.com/perfect-dos-vga-437.font) and [More and Less Perfect DOS VGA](http://laemeur.sdf.org/fonts/)) but in spite of their names they're not perfect.

I think users would want this because people who intentionally choose to use a console are the same people who would be nostalgic for the fonts of their youth.

An argument against it would be that Code page 437 doesn't contain characters for other languages/unicode/emojis.  Potentially these could be added for full compatibility (if that's possible in 8x16 pixels) or left as a known limitation that users would know they're opting in for by using the font.

**Comment by zadjii-msft** [comment]
This is gonna be a hard no. I am not the person qualified to rant on _why_ we're not supporting raster fonts in the terminal, but needless to say it's a inconcievably complicated mess that we're just not going to add a compatibility layer for. I'd recommend finding a TTF that comes close to the right appearance for you. 

@miniksa is the person who'll have a longer rant (if you're interested)

**Comment by miniksa** [comment]
Raster fonts don't work in DirectX. Terminal uses a DirectX renderer. 

I have a lot more to complain about in this space, but I have already wasted enough of my life to raster fonts that I'm going to just stop there and "Won't Fix" this.

**Comment by ghosttie** [comment]
Is that also a no on an official TTF version of the Code page 437 font?

**Comment by miniksa** [comment]
Correct. That would cost money. To get money to recreate the font, I'd have to convince someone to pay for it. I don't think I can convince anyone to pay for it for nostalgia purposes.

**Comment by HackerDaGreat57** [comment]
I got it working perfectly by installing the attached files (Less Perfect has tighter kerning while More Perfect is easier on the eyes). Make sure to turn off anti-aliasing in your profile's appearance settings.

[Originally obtained from here](https://laemeur.sdf.org/fonts/)
[RasterFonts.zip](https://github.com/microsoft/terminal/files/9865167/RasterFonts.zip)
