### ISSUE TITLE
Example profiles.json file with all options needed

### ISSUE THREAD

**Issue by chrisfair** [microsoft/terminal#2016]
I am having a hard time recovering from deleting all of my keyboard shortcuts.   I only wanted to delete a few and I can find no examples about how to add them back.

**Comment by WSLUser** [comment]
Not a complete answer but a starting point: https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md

**Comment by DHowett-MSFT** [comment]
This will actually get better with #754 :smile: I'm going to close this in favor of landing that properly.
