### ISSUE TITLE
I met error when I close all tabs

### ISSUE THREAD

**Issue by Laowang777** [microsoft/terminal#2019]
#Environment
```
Windows build number:Microsoft Windows [版本 10.0.18362.239]
Windows Terminal version (if applicable):Version: 0.2.1831.0
```

# Steps to reproduce
close all tabs

# Expected behavior
![image](https://user-images.githubusercontent.com/33250307/61421876-9a653780-a93b-11e9-902e-70c2304c2f54.png)

# Actual behavior
the picture above.

**Comment by DHowett-MSFT** [comment]
This is probably another instance of #1380
