### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by windyboy1704** [microsoft/terminal#2021]
# Summary of the new feature/enhancement

New tab button and drop-down menu should be right next to the tab instead of spacing far away, like Edge. And the tab button should be designed like Edge.

# Proposed technical implementation details (optional)
![term](https://user-images.githubusercontent.com/5692900/61428831-1a949880-a94e-11e9-8fa5-2c0c1d107899.png)
This is just an example. I think the new tab and drop-down button should be designed to suit with the tab button's design.

It can be designed like this:
![image](https://user-images.githubusercontent.com/5692900/61428703-84607280-a94d-11e9-838c-197a79ef5d1e.png)

**Comment by DHowett-MSFT** [comment]
#1375 please look at the pinned issues
