### ISSUE TITLE
Windows Terminal not running

### ISSUE THREAD

**Issue by gwy15** [microsoft/terminal#2022]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

1. Install Windows Terminal from Microsoft Store.
2. Click on the Windows Terminal icon from the start menu.
3. Running wt.exe behaves identically.

# Expected behavior

Windows Terminal shows its window.

# Actual behavior

Nothing happens after two seconds of mouse cursor showing a loading status.

**Comment by jthvedt** [comment]
Have you tried deleting or renaming your profiles.json file? I was having that same problem. The applications event log showed "Exception code: 0xc0000409" and referenced ucrtbase.dll. I may have had a corrupt settings file; after I deleted profiles.json, Windows Terminal would run. It recreated a new profiles.json file. Of course, I lost a few trivial settings I had changed. If you've made changes, you probably want to make a backup to use for reference.

**Comment by gwy15** [comment]
@jthvedt The thing is Windows Terminal haven't run even once on this PC so there's no `profiles.json` created. I used Everything to search for files named `profiles.json` or `profile.json` on this PC and none was found. So I guess it's not a corrupted config file.

BTW Can you tell me how do I access the application event log? Thanks a lot.

**Comment by thegreatco** [comment]
I'm having a similar issue albeit with a slightly different Windows version.

Edition: WIndows 10 Pro
Version: 1903
OS Build 18362.175

I've tried removing the application using Add/Remove Programs, it has never successfully run on this host.

From Application Event Log
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1907.2001, time stamp: 0x5d1bd2d0
Faulting module name: ucrtbase.dll, version: 10.0.18362.1, time stamp: 0x5cbddb81
Exception code: 0xc0000409
Fault offset: 0x000000000006d3be
Faulting process id: 0x539c
Faulting application start time: 0x01d53d715cdee907
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: c16952b6-1fb4-4b4b-9511-e6332b0f86fe
Faulting package full name: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by jthvedt** [comment]
> BTW Can you tell me how do I access the application event log? Thanks a lot.

Easiest way is type Win-S and search for "Event Viewer". In the left panel, expand the "Windows Logs" section and choose "Application". It sorts by date, so it'll be easiest to find the error if you try to run Window Terminal immediately before you open the Event Viewer.

**Comment by jthvedt** [comment]
@thegreatco - That's exactly the error I was getting in my event log. Removing the app did _not_ remove the profiles.json file for me; I had to delete that file manually.

**Comment by gwy15** [comment]
I had a look at the logs and I have the same report as @thegreatco .

**Comment by thegreatco** [comment]
I am now upgraded to OS Build 18362.10005 and it is still failing to start. This is a freshly installed copy after the update to 10005.
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1907.2001, time stamp: 0x5d1bd2d0
Faulting module name: ucrtbase.dll, version: 10.0.18362.1, time stamp: 0x5cbddb81
Exception code: 0xc0000409
Fault offset: 0x000000000006d3be
Faulting process id: 0x28c
Faulting application start time: 0x01d53e5d96827e9b
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 65231be6-67f6-4d16-8a0a-705ff3795fd7
Faulting package full name: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```
```
Fault bucket 1713649042173444167, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.0.1907.2001
P4: 5d1bd2d0
P5: ucrtbase.dll
P6: 10.0.18362.1
P7: 5cbddb81
P8: 000000000006d3be
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER58C4.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5971.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5992.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER59A3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER59D3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_e2e3fa6c896198f1ea9ed1ce1e1cb6e78fc13_07ada22b_6c2d78f5-1793-49a2-ba93-def3371d502c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 65231be6-67f6-4d16-8a0a-705ff3795fd7
Report Status: 268435456
Hashed bucket: 0170e7cb87c40f84a7c81ab97c6fc047
Cab Guid: 0
````

I have a `wer` file if it would be helpful.

**Comment by DHowett-MSFT** [comment]
This seems similar to #1364. @thegreatco, is there a chance your "default profile" points to something that doesn't exist on this computer?

**Comment by gwy15** [comment]
So it turns out Windows automatically sync the `profiles.json` between different computers under your account. And it seems that if the synced profiles includes something that is not suitable for the host, e.g., a font not installed, the Windows Terminal crashes without giving any warnings or logs.

For my case, I manually entered the directory 
`%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState` and deleted the synced `profiles.json` from my laptop, which does exist but for some reason was not found in everything. Then I re-ran the Windows Terminal and a default profiles.json was generated which Windows Teminal worked with fine.

**Comment by fedelaport** [comment]
I have two laptops. Installing from Windows Store works nice on the first laptop. Then, installing on the second laptop syncs the `profiles.json`. The file points to things that I don't have on the second laptop.

**Comment by brkattk** [comment]
I have two machines as well. On one machine, I have Ubuntu. The other has Ubuntu-18.04. If I use WSL as the default profile, it will only run on one machine because:

```
"commandline": "wsl.exe -d Ubuntu-18.04",
```
is not the same as
```
"commandline": "wsl.exe -d Ubuntu",
```

**Comment by thegreatco** [comment]
I was missing a font. I deleted the `profile.json`, and it started up just fine. Then i slowly merged the old and new `profile.json` until something broke. Installed the font, problem solved.

**Comment by TheAndyMac** [comment]
Thank you! This fixed my install as well... had the same problem for weeks and only just found this solution - I had assumed that an Uninstall/Reinstall and/or a Reset of the app through the Windows App Settings would sort it out - maybe one easy fix to cope with profile "corruptions" would be to make sure the Windows App Settings "Reset" feature deletes the profile file?

**Comment by gwy15** [comment]
For WT 0.3.2171.0, it seems that for a `profiles.json` with invalid font Windows Terminal will now fallback to a default font (seems like consolas to me) instead of crashing. For now I don't see any necessary to keep this issue open and I'm closing it.

But still, no warnings are raised to remind users to fix their `profiles.json`.

**Comment by EricBuist** [comment]
Hi,
Is there a way to prevent synching this profile.json, which looks to me like the worst idea ever. The file depends on what is installed on the host computer so it should not be synched, or things in there that don't work on the host computer should trigger warnings at worst, not crash the terminal without any form of clue. I cannot spend my time deleting that file (and finding it) and then trying to figure out again the tweaks I did in there to have a block cursor, disable the annoying beep, add a tab pointing at my SSH server, etc. It was working yesterday and all of a sudden, I cannot start the Windows Terminal. That problem WILL occur again, again and again, if I just recreate that profile.json file. Having to remove profile.json (and search for it, it is really non-obvious to find), is not a fix.

**Comment by zadjii-msft** [comment]
@EricBuist We stopped syncing `profiles.json` like, [nearly two years ago](https://github.com/microsoft/terminal/pull/2298). We also [don't migrate settings from the old roamed location](https://github.com/microsoft/terminal/pull/5199) to `settings.json` anymore. 

If you're experiencing a new crash on launch, then it's probably some totally new scenario. Could you follow up in a new thread, so we can track your issue specifically? Thanks!

**Comment by gemini88mill** [comment]
Hey All ran into the exact same issue and realized that I didn't even have a profiles.json. I ended up going into "Add or Remove Programs" and repairing Windows Terminal, fixed the problem for me.

**Comment by alibenmessaoud** [comment]
I am experiencing the same issue and WT stills always crashing after restart and a new Windows update.

**Comment by etalian** [comment]
Same here, fixed by "repairing". Even though this is the top search result now, I believe we are actually seeing #10211.

**Comment by DLX23** [comment]
Now, same Problem here. "Repairing" and "reset" dont help.

`Name der fehlerhaften Anwendung: WindowsTerminal.exe, Version: 1.8.2105.24004, Zeitstempel: 0x60ac2e94
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.19041.789, Zeitstempel: 0x2bd748bf
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000000000007286e
ID des fehlerhaften Prozesses: 0x9858
Startzeit der fehlerhaften Anwendung: 0x01d7552ffe6e2922
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: c1016986-f7c6-4cde-8f0d-669bdea6c357
Vollständiger Name des fehlerhaften Pakets: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App`

**Comment by annahri** [comment]
Fixed this by reparing.

**Comment by uberubert** [comment]
There is no "Repair" option in the "Apps and features" screen, only "Move" and "Uninstall". I clicked "Uninstall" thinking maybe there would be the familiar wizard popping up that would give me options other than uninstalling. It got uninstalled without further prompts.

It seems to be back and starting after reinstalling.

**Comment by alanaasmaa** [comment]
@uberubert The "Repair" option is under "Advanced options"
![image](https://user-images.githubusercontent.com/12788337/120307858-1f615c00-c2dc-11eb-80bf-00c8b76a351f.png)

Worked for me.
