### ISSUE TITLE
Bug Report (Don't display ubuntu terminal)

### ISSUE THREAD

**Issue by dilantha111** [microsoft/terminal#2023]
I installed windows terminal through Microsoft store. But I can only see power shell and cmd. In the introduction video I can see that it has bash as well. I couldn't find any documentation section to whether how to enable this or not.

**Comment by khronos2** [comment]
Have you installed Ubuntu from the Store as well? I pulled down the terminal yesterday and my 18.04 install was added automatically. Make sure it's installed and if it doesn't pop up, go to the settings for the terminal and edit the JSON file to include it.

**Comment by WSLUser** [comment]
Reference: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by dilantha111** [comment]
Hi @WSLUser  I have ubuntu as Windows subsystem for linux. But the thing is it's not included in the drop down list in windows new terminal. I only get powershell and cmd. If you check here https://devblogs.microsoft.com/commandline/introducing-windows-terminal/ they are listed to be chosen.

**Comment by WSLUser** [comment]
Try another distro to see if it's specific to Ubuntu. Pengwin and FedoraRemixforWSL came up automatically after installing the Terminal from Store.

**Comment by Plancke** [comment]
It showed up for me automatically but you could try adding a new profile and setting `commandline` option to `wsl.exe -d Ubuntu`

**Comment by WSLUser** [comment]
I was going to mention that but was wondering if Ubuntu had a bug in it. If you don't have a version of Windows that supports `wsl.exe -d`. Set Ubuntu as default and omit the `-d`.

**Comment by JBanks** [comment]
@dilantha111 can you run the following command for me? `wsl --list`  If it looks anything like the following, I'd like you to try deleting or renaming you profiles.json file and tell me if that fixes your issue.

```
Windows Subsystem for Linux Distributions:
Ubuntu (Default)    
```

@WSLUser That would cause issues when you actually click on the new tab, it won't cause issues with populating the list.  The list is populated using the noisy, old `wsl --list`.

**Comment by WSLUser** [comment]
Ah I see. but launching wsl.exe opens a regular terminal. So I was thinking it should be able to work in Terminal as well, if indirectly at least. Say you use Terminal to open Powershell, and enter wsl. If the distro wasn't listed before, it should be able to detect it now that it's actively being used within Terminal. It just happens to be running in a PS session in my example.

**Comment by DHowett-MSFT** [comment]
This is because we do not refresh your list of default profiles on launch. You can delete your `profiles.json` to make it re-scan the distribution list. #754 #1321

**Comment by dilantha111** [comment]
Thanks @JBanks  it worked like a charm after deleting the profiles.json and launching the windows terminal again.
