### ISSUE TITLE
ColorTool is missing in store version of Terminal

### ISSUE THREAD

**Issue by andylamp** [microsoft/terminal#2025]
# Environment

```none
Windows build number:  Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable):  0.2.1831.0 (Store Version)

Any other software? No
```

# Steps to reproduce

Start Windows Terminal and try to invoke `ColorTool` in the Store Version of the app - not built from source.

# Expected behavior

Invoke `ColorTool` correctly

# Actual behavior

Not found.

**Comment by WSLUser** [comment]
Not advertised on the Store page. They aren't together right now. But you can download it from this repo or request it in pengwin-setup if you use Pengwin in WSL.

**Comment by andylamp** [comment]
I see - thanks @WSLUser, I guessed that was the case but was nowhere to be found in the documentation, maybe put a pointer to this into the docs to avoid confusion?

As for `pengwin-setup` am not currently using it but would be keen since being able to customise the terminal colors is a huge plus :). I would appreciate if you have a pointer on how to use this to get `colortool` working.

**Comment by WSLUser** [comment]
Well on the README, it actually provides a link to it with all the guidance for it. But since it took literally 2 seconds to get the URL here you go: https://github.com/Microsoft/Terminal/tree/master/src/tools/ColorTool

**Comment by WSLUser** [comment]
oh and to make it easier to download: https://github.com/microsoft/terminal/releases/tag/1904.29002

**Comment by andylamp** [comment]
@WSLUser, do you have something that can be used *without* building it? I saw that, but had no binary distribution available.

**Comment by andylamp** [comment]
@WSLUser okay cool that second link was not in the `README` nor in the releases - thanks, that works!

**Comment by WSLUser** [comment]
It's in the releases but because Terminal is out, you have to look for it under Releases as a few versions of Terminal are in the way of getting to ColorTool.  A direct link would be probably be helpful and simply update the link next time a new release is out for ColorTool.

**Comment by andylamp** [comment]
if you don't mind a pull request I could add these bits to the `ColorTool` read me.

**Comment by WSLUser** [comment]
I'm not a member of the Console team as awesome as that might be. I'm sure @zadjii-msft would love to see a PR.

**Comment by andylamp** [comment]
cool - thanks!

**Comment by DHowett-MSFT** [comment]
The Readme being updated should close this issue. We don't currently have plans to put ColorTool into the package with Windows Terminal.

In the future, Windows Terminal should have some or all of the same features.

**Comment by WSLUser** [comment]
@DHowett There's no shame is re-using/adapting code from other terminals like mintty and Iterm2 to get that functionality as well as other features into Terminal.  Probably would help a bit in speeding things along.
