### ISSUE TITLE
Terminal crashes when vim split over ssh

### ISSUE THREAD

**Issue by TapeWerm** [microsoft/terminal#2026]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.263]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
Ubuntu Server 18.04.2 (host ssh'd to, probably doesn't matter)
```

# Steps to reproduce

SSH to a server running Ubuntu 18.04.2. Edit something with vim and split view. Hopefully you know how to escape hotel vim and how to use it. [This guide](https://vim.rtorr.com/) may help. It crashes for me, repeatedly.

EDIT: I tried this ssh'ing to a RHEL5 host, it did not repeat. Then when I tried it a 3rd time on the Ubuntu 18.04.2 host it did not crash. Sorry, this may be harder to reproduce than I thought. Specifically, I also used vs, vertical split. That may be important.

# Expected behavior

Not crashing when I split view in vim over SSH, actually being able to edit 2 files side-by-side just like I can on my local host.
# Actual behavior

Crashes. This does not happen on the local host, just over SSH to another.

**Comment by TapeWerm** [comment]
It's actually just me pressing Ctrl-W twice as that switches windows in vim. That is also the default close tab shortcut in Terminal. Is it okay to change the subject? This is definitely a questionable default.

**Comment by DHowett-MSFT** [comment]
In that case, I've got good news!

#1417, #2014
