### ISSUE TITLE
Flyout/Dropdown light dismiss not working with Titlebar click

### ISSUE THREAD

**Issue by mdtauk** [microsoft/terminal#2028]
# Environment

```none
Windows build number: 18362.263
Windows Terminal version (if applicable):0.0.1.0 - Built 01:02 Fri 19 July
```

# Steps to reproduce

When you tap on the drop down button, and bring the flyout on screen.  Clicking on the Titlebar will not trigger the light dismiss behaviour and the flyout remains open.  Tapping on the terminal display, tab or tab bar, works as expected.

# Expected behavior

Tapping on the titlebar should dismiss the flyout
![image](https://user-images.githubusercontent.com/7389110/61500003-2b322680-a9c1-11e9-8858-6402f4aa8dbd.png)

# Actual behavior

Tapping the Titlebar does not dismiss it, and if you drag the window, the flyout lags in moving to the correct position

![image](https://user-images.githubusercontent.com/7389110/61500048-71878580-a9c1-11e9-9af6-0b6aa8ac42d1.png)

**Comment by DHowett-MSFT** [comment]
Alas, these are both real issues and you're going to tell me to file them on the WinUI 3.0 team and I'm going to tell you that we report to the same manager, so I'll just comment all that right now and leave this open/marked.

**Comment by mdtauk** [comment]
Sorry @DHowett-MSFT  :)
