### ISSUE TITLE
Terminal does not start after building

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#2029]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18936.1000]
Windows Terminal version (if applicable): commit ID 8ffff8e
```

# Steps to reproduce

.\tools\razzle.cmd rel
bcz rel
Run terminal at .\src\cascadia\CascadiaPackage\bin\x64\Release\WindowsTerminal.exe

# Expected behavior

Windows Terminal Starts correctly.

# Actual behavior

Terminal starts, and right after start it closes (like when commandline argument is not able to open - There is no problem for profiles.json).

**Comment by DHowett-MSFT** [comment]
You cannot run Windows Terminal by double-clicking the EXE; please deploy and launch the appx package. Visual Studio makes this way easier. #926

**Comment by SJang1** [comment]
Hmmmm.... it was possible before this commit.. 🤔
Is there a way to deploy by using a command-line?
