### ISSUE TITLE
Tabs covered by '+v' buttons

### ISSUE THREAD

**Issue by RomanticStrings** [microsoft/terminal#2030]
When the app opened the first time ("floating" rather than maximized etc.) and I opened a second tab, the right tab and its 'x' close button were covered by the '+v' buttons to add tabs.  I had to expand the window to make it wide enough that the tab was no longer covered.
![Annotation 2019-07-18 194642](https://user-images.githubusercontent.com/7991648/61501448-fc05c000-a994-11e9-8202-f709274d3c00.jpg)
![Annotation 2019-07-18 194715](https://user-images.githubusercontent.com/7991648/61501449-fc05c000-a994-11e9-93de-2bb7682eb964.jpg)

**Comment by imjasonmiller** [comment]
It is in #1375, the megathread on all issues related to the design, at the end of the post, so they are aware of this issue :-)

**Comment by zadjii-msft** [comment]
Yep that's correct. #1948 will make this _better_, but we're still waiting on some features to be added to the TabView in the upstream microsoft-ui-xaml project. 

Closing as a dupe for now :)

**Comment by RomanticStrings** [comment]
Thanks, folks!  I figured it'd been caught, but my cursory search showed no results and many issues.  Thanks for following up!
