### ISSUE TITLE
terminal open as empty if "commandline" is set wrong 

### ISSUE THREAD

**Issue by MasterFastwind** [microsoft/terminal#2034]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0

# Steps to reproduce

In the configuration file: the "commandline" variable, of a profile, is set to a non existing .exe or command

# Expected behavior

I was expecting a warning with the fact that the "commandline" variable is wrong

# Actual behavior

It will open the window/tab empty and than, it close it; with no clue of what append

**Comment by DHowett-MSFT** [comment]
#982
