### ISSUE TITLE
Bug Report: Settings Do Not Open

### ISSUE THREAD

**Issue by lnorton89** [microsoft/terminal#2036]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version: Latest
```

# Steps to reproduce
Open Windows Terminal and try to open the settings via the arrow button. 

# Expected behavior
A settings dialog opens. 

# Actual behavior
Nothing.

**Comment by alefnull** [comment]
currently the settings are stored in and edited via a JSON file, so you'll need to associate a text editor with JSON files in your system settings. after that, clicking the settings button will open the settings JSON file for you to edit as you wish.

**Comment by kyleskrinak** [comment]
I have confirmed that my system has mapped *.json to vim, yet control-comma or choosing “Settings” from the tabbed menu fails to load the settings file. Or, as the OP says; “nothing” happens.

**Comment by DHowett-MSFT** [comment]
Alas, this is a silly bug. #1789 
It's been fixed, and that fix is just waiting for another release.

**Comment by DHowett-MSFT** [comment]
The core of the issue is that gvim registers itself for the "edit" verb but we were using the "open" verb.
The fix for 1789 also added a fallback to Notepad just in case nothing was able to open it.
