### ISSUE TITLE
Bug Report - Ubuntu not listed as new tab option

### ISSUE THREAD

**Issue by misolori** [microsoft/terminal#2037]
# Environment

```none
Windows build number: Version 10.0.18362.239
Windows Terminal version (if applicable): 0.2.1991.0
```

# Steps to reproduce
1. Install Ubuntu from Microsoft store
2. Install Terminal from Microsoft store
3. Open Terminal and create new Ubuntu tab
4. :bug: Ubuntu not listed as one of the options

# Expected behavior

Expected to have Ubuntu added automatically to the list

# Actual behavior

Ubuntu is not on the list and had to add it to `profiles.json` manually

**Comment by code4clouds** [comment]
I have the same issue as well.  Same versions.

**Comment by JBanks** [comment]
What is your output from `wsl -list`?  If it looks like the below, I'd ask that you also run `wsl -list | wsl -e xxd` in case there's a weird language thing.

```
PS C:\Users\[redacted]> wsl -list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Debian
```

**Comment by code4clouds** [comment]
It shows the help and the list of options...
```
PS C:\Users\[redacted]> wsl -list 
Invalid command line option: -list
Copyright (c) Microsoft Corporation. All rights reserved.
Usage: wsl.exe [Argument] [Options...] [CommandLine]
Arguments to run Linux binaries:   
```
Adding two dashes (--) shows your output.  
```
PS C:\Users\[redacted]> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)                          
```

**Comment by JBanks** [comment]
Sorry, I edited the command and forgot to add the second hyphen.  

I just installed the version from the store (0.2.1831.0) on the same version of windows that you have (18362.239) and it worked perfectly.  Unfortunately I won't be able to debug this for you.  If you're feeling ambitious, here is the section of code where the WSL profiles are added: https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/CascadiaSettings.cpp#L527

I just installed a new distro and did notice that it took a few minutes to populate in the list.  Did you install windows terminal prior to initializing Ubuntu?  

Try closing terminal, deleting/renaming profiles.json and re-opening terminal again.

**Comment by code4clouds** [comment]
Yes... I installed WSDL and Ubuntu after installing Terminal.  I'll remove it and report back.  I did noticed before installing Ubuntu and WSDL the Terminal crashed a few times after closing it, so maybe there is something that is required or needed related by the Terminal that is not liking it.

**Comment by code4clouds** [comment]
Just reporting back that removing the Terminals and installing it again worked for both issues.  The Ubuntu is now listing (nice penguin) and the crashes are no longer happening when closing.  

I guess the "init" routine needs to  check the environment.  Ideally it would be nice if Terminal checks for environmental changes.  It would be also neat to have a menu-time in the drop-down to launch the MS store with the available options to install on the Terminal.

**Comment by JBanks** [comment]
>  Ideally it would be nice if Terminal checks for environmental changes.

Sounds like a great idea for a feature request!  I'm glad that everything is working now.

**Comment by DHowett-MSFT** [comment]
There's a couple things here.

* Your settings file was probably roaming, either from an earlier install or from another machine. #1770 
* We don't autoregenerate default profiles _ever_ #754 #1258 #1321
