### ISSUE TITLE
Feature Request: Make profile.json easily portable between machines and accessible

### ISSUE THREAD

**Issue by mrallen1** [microsoft/terminal#2040]
# Summary of the new feature/enhancement

Currently profile.json is stored in the "roaming" application location which makes storing a "common" profile to be shared across *all* Windows Terminal installs difficult.

# Proposed technical implementation details (optional)

Please enable a mechanism to look for/load profile.json from a location which can be easily shared using a service like OneDrive or Dropbox so that it acts more like "just another dot file" I can easily synchronize/share among *all* of the Windows installs I use on a day to day basis.

Thanks

**Comment by DHowett-MSFT** [comment]
#1567 :smile:
