### ISSUE TITLE
Bug Report - profiles.json "background" conflict between profiles and (color) schemes

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/terminal#2041]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): Version: 0.2.1831.0

Any other software?  Yes, I have other software installed on my computer.
```

# Steps to reproduce

The default profiles in profiles.json contain the element "background" which overrides any color scheme that you set.

# Expected behavior

The expectation is that a color scheme's background would override the profile's.

# Actual behavior

You have to know to delete the "background" element from the profiles, and only then will color schemes' background color take effect.

**Comment by DHowett-MSFT** [comment]
This is by design, but it could be better-documented. A profile should be able to override specific local things about its color scheme. It can even embed an entire color table if you'd like.

**Comment by JeremyTBradshaw** [comment]
Thanks for the confirmation on design - makes sense.
