### ISSUE TITLE
Terminal crashes when the window width is too small

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#2045]
# Environment

```none
Windows build number: [run "ver" at a command prompt] 10.0.18941.1001
Windows Terminal version (if applicable): commit 5074335392c14d3359280609c8a03166cc20b857

Any other software?
```

# Steps to reproduce

Open Windows Terminal, and resize the window, when the window width is smaller than a certain value, it crashes.
![out](https://user-images.githubusercontent.com/22699485/61577629-a5c38900-ab1c-11e9-9c9b-020f22c7556e.gif)

# Expected behavior
It should not crash.

# Actual behavior
It crashes.

**Comment by vblazhkun** [comment]
@driver1998 I have the same issue and have two core dumps waiting to be uploaded.

**Comment by mcpiroman** [comment]
It strongly seems to be regression caused by #1948.

**Comment by DHowett-MSFT** [comment]
We can reproduce this here, so we probably don't need any dumps. Thanks!
