### ISSUE TITLE
Feature Request - Administrator and non-administrator Powershell in one terminal instance

### ISSUE THREAD

**Issue by davystrong** [microsoft/terminal#2048]
I would like to be able to open a new administrator terminal using the "+" button, within the same terminal instance.

**Comment by joandrsn** [comment]
You should search before adding feature requests. Recent duplicates of this request: #1490 #1990
#1032 is the mega thread for all of them.

**Comment by davystrong** [comment]
Sorry, I had searched but only open issues. I forgot it might already be closed. I'll close
