### ISSUE TITLE
CTRL+W to close last tab is SLOW.)

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#2052]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): Version: 0.2.1831.0

Any other software?
```

# Steps to reproduce

Close last tab using CTRL+W

# Expected behavior

Immediate closing of 'Windows Terminal'

# Actual behavior

a closed tab, a delay, and than closing of Windows Terminal

**Comment by DHowett-MSFT** [comment]
This is probably just #1380
