### ISSUE TITLE
touch keyboard doesn't auto-trigger

### ISSUE THREAD

**Issue by LordObsidian01** [microsoft/terminal#2055]
When using a touch device (such as a Surface Pro 4) in tablet mode, I expect the touch keyboard  to be presented when  you tap on the input area of the terminal, however it does not. it is the same behavior with PS, cmd, wsl. the cursor appears and waits for input but no keyboard.

**Comment by miniksa** [comment]
I am relatively sure that #1919 will resolve this. I think touch and pen input is activated via a TSF context. If we have a TSF context, I think it will show the keyboard.

**Comment by DHowett-MSFT** [comment]
Moving discussion to /dup #3639
