### ISSUE TITLE
Dragging into corner for 1/4 view will result tab to be smaller than maximum

### ISSUE THREAD

**Issue by DragonbornSR** [microsoft/terminal#2057]
Dragged into corner of windows to snap into 1/4 view
![image](https://user-images.githubusercontent.com/3610982/61629908-e6dbaa80-ac8e-11e9-887f-cb259b57b816.png)

Using WINDOWS KEY + Arrows will not produce same result (is good)
Expected result:
![image](https://user-images.githubusercontent.com/3610982/61629960-083c9680-ac8f-11e9-82ad-ca377f274dd0.png)

**Comment by DHowett-MSFT** [comment]
Whoa. Are you in a mixed-DPI world? What are the scaling factors on your monitors?

**Comment by DragonbornSR** [comment]
actually, 4k 2 monitors, one was like 150% and second 100%. Yes they were different.

**Comment by zadjii-msft** [comment]
Oh wait I think I have a fix for this. The commit is 7015128, but I'm not sure it's ready for PR yet.
