### ISSUE TITLE
Feature Request: automatic scroll while selecting with the mouse

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#2064]
# Summary of the new feature/enhancement

Windows Terminal should support automatic scrolling when user is selecting text with the mouse, as the mouse approaches the first or last lines. This is supported in the current conhost and it is missing in Windows Terminal.

If the feature is already planned or tracked by another bug, feel free to close it.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This is actually #1247.
