### ISSUE TITLE
Create new window key binding

### ISSUE THREAD

**Issue by havidarou** [microsoft/terminal#2068]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

I edit my settings to add a key binding for `newWindow` as listed here: https://github.com/microsoft/terminal/blob/v0.2.1831.0/src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp#L28

This is a sample of the configuration:

```
            {
                "command" : "newWindow",
                "keys" : 
                [
                    "ctrl+n"
                ]
            }
```

# Expected behavior

Upon pressing `ctrl+n` a new Windows terminal window should be opened.

# Actual behavior

Nothing happens.

**Comment by zadjii-msft** [comment]
Yea, that one hasn't been implemented yet. We should do that.

**Comment by ffes** [comment]
Isn't this a dup of #1051 (which is placed on `Terminal Backlog` BTW)

**Comment by zadjii-msft** [comment]
🤦‍♂ yep it definitely is, thanks for helping clear up our backlog ☺️ 

/dup #1051
