### ISSUE TITLE
Terminal Profile should allow for running as admin or other user in Tab

### ISSUE THREAD

**Issue by jkavanagh58** [microsoft/terminal#2071]
# Summary of the new feature/enhancement
This might be related to #1133 
When creating a new profile there should be an option to runas ... I have seen mention of  security issues... My current workstation I have a CLI as standard, then I have one that was launched As Administrator and then another CLI that runs as a different user, a user that has elevated privileges in the domain. I have a sudo like function I can use once the tab starts but that seems to fail. I thought using a GUID that correlates to Admin or the domain admin type account but that does not seem to work. 

# Proposed technical implementation details (optional)
Include an option to run elevated or provide a credential object in the profile
{
            "acrylicOpacity" : 0.30000001192092896,
            "background" : "#012456",
            "backgroundImage" : "C:\\users\\johnk\\Pictures\\powershell-wmi1.jpg",
            "backgroundImageOpacity" : 0.34999999403953552,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "powershell.exe",
            "AsAdmin": true,
            "credObject" : <notsurehow to grab PSCredential but it would be my FeatureRequest",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "underscore",
            "fontFace" : "ProFontWindows Nerd Font",
            "fontSize" : 12,
            "guid" : "{d5e8489d-3400-4ea9-9eb7-d723fb4f19f5}",
            "historySize" : 9001,
            "icon" : "ms-appdata:///roaming/powershell-wmi1.jpg",
            "name" : "Windows PowerShell",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : false
        }

**Comment by zadjii-msft** [comment]
This smells like a dupe of #1032 to me...
