### ISSUE TITLE
Feature Request - PowerShell Hidden Window Launch Parameter

### ISSUE THREAD

**Issue by nkasco** [microsoft/terminal#2072]
# Summary of the new feature/enhancement
Windows PowerShell supports using the `-WindowStyle Hidden` launch parameter, however due to [limitations of the console](https://github.com/PowerShell/PowerShell/issues/3028) it is not possible to completely suppress the flicking, ultimately leading to a poor user experience.

Adding a feature to Terminal is an opportunity to resolve this issue entirely, which would ultimately lead to larger adoption and better overall experience with Windows Terminal.

**Comment by DHowett-MSFT** [comment]
There's, unfortunately, nothing Terminal can do to fix this. This is baked down into the lowest layers of process creation on Windows. 😦

**Comment by nkasco** [comment]
> There's, unfortunately, nothing Terminal can do to fix this. This is baked down into the lowest layers of process creation on Windows. 😦

Is the core of Terminal still a console? Or rather a framework that allows staging of multiple consoles? If it is the latter it could be considered a feature in lieu of the need for creating an entirely separate wscript-like host to simply suppress the console window entirely for background automation and GUI based scripts. This would give me a reason to use Terminal even if I were only planning to have a single console open during the session.
