### ISSUE TITLE
Running as administrator shows the window frame for a second and then crashes

### ISSUE THREAD

**Issue by andrew-z** [microsoft/terminal#2073]
# Environment

```none
Windows build number: 10.0.18945.1001
Windows Terminal version (if applicable): 0.2.1991.0
```

# Steps to reproduce

1. Window Terminal (Preview), run as administrator

# Expected behavior

Everything works fine

# Actual behavior

App frame shows for a second, then crashes. Does not repro for non-administrator launch.

**Comment by DHowett-MSFT** [comment]
#2042, fixed with #2043, not yet deployed.
