### ISSUE TITLE
Impossible to start Terminal 

### ISSUE THREAD

**Issue by toomanysecrets** [microsoft/terminal#2074]
# Environment

```none
Windows build number: [Versión 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
```none

# Steps to reproduce

Install Cmder with Chocolatey, and ConEmu also.
Open Microsoft Store, install Terminal Preview.
Uninstall ConEmu (in this order) and later Cmder.
Terminal refuse to start at this point. 

# Expected behavior

Open the Terminal app.

# Actual behavior

Impossible to run Terminal. If I try to execute through Powershell (using "wt" command) I can only obtain the message: "Last command exited with error status."

**Comment by zadjii-msft** [comment]
Does the terminal launch normally through the start menu? Or is it only launching from the execution alias (`wt.exe`) that doesn't work?

Did the terminal work _before_ installing/uninstalling conemu, cmder?

**Comment by toomanysecrets** [comment]
I have to try directly with wt.exe because was impossible to start through the start menu.

Installed Cmder: just the same. Doesn't start from the menu or "wt.exe". When I try from a PowerShell terminal the message is the same: "Last command exited with error status".

Installed ConEmu (and uninstalling Cmder first): is like Cmder; doesn't run.

Installed ConEmu also with Cmder: the error persists. I cannot start the app.

Thank you so much for your work and help.

**Comment by zadjii-msft** [comment]
So I'm going to go out on a limb and suggest that conemu and cmder have no correlation to this issue, since the terminal didn't work even with them. 

Could you share your `profiles.json` file? It should be in `%userprofile%\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\`

**Comment by toomanysecrets** [comment]
Looking the profiles.json file, I look that the first profile (powershell) has a fontFace that I don't have installed at this momment so, I just edited the profiles.json, put an existed font and all is running again like a farm ;-)

**Comment by toomanysecrets** [comment]
Looking the profiles.json file, I look that the first profile (powershell) has a fontFace that I don't have installed at this moment so, I just edited the profiles.json, put an existed font and all is running again like a farm ;-)
Maybe, it will be a great thing that if the app detects a wrong fontFace, it can communicate or use something like a "defaultfont".
I will apologize about my English because it isn't my mother tongue.

Thank you so much for your great help and attention.
