### ISSUE TITLE
Store release 

### ISSUE THREAD

**Issue by unuunc** [microsoft/terminal#2076]
This is question/suggestion -

How frequently we update STORE version of Terminal , I see last release was done 15 days back.

I used to build and deploy , but post preview release I started using from store , as it is already mentioned as preview , can we update it frequently?

**Comment by zadjii-msft** [comment]
We'll push updates to the store more regularly once 0.3 is ready. We're holding on to pushing that release until we've put a little bit more polish on our UIA story. 

We also don't want to be pushing _too_ frequently, as we don't want to push prematurely and regress something for our users.

**Comment by yangshuairocks** [comment]
When will 0.3 be ready?

**Comment by DHowett-MSFT** [comment]
We have not announced a release date. Please follow the milestone progress in this repository.

**Comment by unuunc** [comment]
thanks , closing the issue
