### ISSUE TITLE
Crash on About dialog when running Terminal unpackaged

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#2078]
# Environment

```none
Windows build number: [run "ver" at a command prompt] 10.0.18941.1001
Windows Terminal version (if applicable): commit 9d36b08b82c67c6965263c63bb83b024c15f3474

Any other software?
```

I know it is not a supported scenario, but with https://github.com/microsoft/terminal/pull/2043 we can now run Terminal unpackaged. 
And some people might prefer it this way.

# Steps to reproduce

Run WindowsTerminal.exe directly, outside of app package.
Click about in the drop down menu.

# Expected behavior

The about dialog show up as normal.

# Actual behavior

The app crashes.

**Comment by zadjii-msft** [comment]
I'm going to chime in and say if #2043 made this work a little, I kinda want to make sure it keeps working. Before we went open-source, there was a time you could build and run the terminal from the commandline, using unpackaged activation like this. At some point it broke, and we just never had the time to investigate. If #2043 fixes launching, then I'm inclined to leave this open to track fixing this entirely.

**Comment by DHowett-MSFT** [comment]
This actually also fails in the packaged version. :smile:

**Comment by zadjii-msft** [comment]
I'm leaving a note to myself here: When the trying to run the terminal unpackaged, the `resources.pri` from `CascadiaPackage` is what you need. You can double-click WindowsTerminal.exe when you copy that file out of CascadiaPackage's output into `bin\%ARCH%\%CONFIGURATION%`, and launch the WindowsTerminal.exe in that folder. Running the WindowsTerminal.exe in the CascadiaPackage directory shockingly doesn't work.

However, I think we only build the resources.pri file if we build CascadiaPackage, so trying to _only_ build WindowsTerminal then running it won't work. Hmmmm.

**Comment by zadjii-msft** [comment]
This should maybe block v0.3. You can't open the about dialog at all, so we're going to get 100 dupes for this, and bug reports are going to become impossible to track.

```
  🌛
💪 💪
  👖
```

**Comment by zadjii-msft** [comment]
So this seems to be related to the `NavigateUri` property on the Hyperlinks in the about dialog. If you remove those `NavigateUri`'s, then it'll display just fine (but obviously not work).

Maybe we hack a workaround for now?
