### ISSUE TITLE
Bug Report The Windows terminal window may flash when dragged

### ISSUE THREAD

**Issue by ntdeev** [microsoft/terminal#2079]
# Environment

```none
Windows build number: 18947.1000
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

Open Windows terminal from the Start menu or taskbar
Drag the window on random intervals.

# Expected behavior

It should not flash but drag normally and see the text reflow when run standalone such as PowerShell or Command prompt.

# Actual behavior

It starts to flash in random intervals

**Comment by zadjii-msft** [comment]
Any chance you mean this behavior (from #1375)?
> * [ ] Resizing the window causes the UI to disapper/reappear. 
> ![ezgif-2-9dc95bf607e7](https://user-images.githubusercontent.com/1243172/59960788-78f06780-94c5-11e9-863d-3adfa6f1c6d2.gif)

**Comment by ntdeev** [comment]
Yes, it looks like that.
