### ISSUE TITLE
Feature Request: ssh connections / bookmarks

### ISSUE THREAD

**Issue by atyachin** [microsoft/terminal#2085]
Add ability to save remote connection bookmarks - similar to mRemoteNG

# Proposed technical implementation details (optional)

Can be based on the native Windows SSH client.

**Comment by zadjii-msft** [comment]
This is already possible, by editing the `profiles.json` file, right? You could always just set the `commandline` to `"ssh me@someserver --with --some --args"`

**Comment by atyachin** [comment]
This is indeed doable, however would be great to be add/edit via the UI (currently it requires to manually edit the json file, generate GUIDs etc..)

**Comment by zadjii-msft** [comment]
Yep, we do plan on having a settings UI to be able to set these things easier: #1564

**Comment by techcomthanh** [comment]
That would be great if we can connect to existing ssh_config profiles from vscode (including location paths saved by vscode).
We can also have a quick access to such ssh profiles from recent workspaces by right click from taskbar or startmenu
