### ISSUE TITLE
Can't install nvidia drivers, can't install DIGITS

### ISSUE THREAD

**Issue by cat768** [microsoft/terminal#2086]
# Environment
Ubuntu 18.04
Windows build number: 10.0.18362.239

System specifications:
MSI GS63-7RD Stealth Pro
i7-7700HQ, GTX 1050 (non max-q), 16GB DDR4-2400, 1TB SSD

Any other software?
Trying to install nvidia digits using lambda stack
Lambda stack: https://lambdalabs.com/lambda-stack-deep-learning-software
DIGITS Install: https://github.com/NVIDIA/DIGITS/blob/digits-6.0/docs/UbuntuInstall.md

# Steps to reproduce

cd into <user>/Desktop on c drive
run lambda stack (using the link attacked above)
after that, run nvidia-smi

# Expected behavior

nvidia-smi should report driver version, e.g. 430.

# Actual behavior

It says "nvidia-smi cannot be found, but can be installed with nvidia-340"
Afer I run nvidia-340, it displays "/usr/bin/dpkg returned error code"

**Comment by zadjii-msft** [comment]
This isn't really a terminal issue, is it? If anything it sounds like it might belong in [microsoft/WSL](https://github.com/microsoft/wsl/).

If this is more directly related to the terminal or console, please feel free to tell me I'm wrong, and we'll re-open it.
