### ISSUE TITLE
Resolve longstanding issues with conhost's MeasureRight

### ISSUE THREAD

**Issue by BladeMF** [microsoft/terminal#2089]
# Environment

```none
Windows build number: Version 10.0.18362.239
Windows Terminal version (if applicable):0.2.1831.0

Symfony 4.3
```

# Steps to reproduce

Render a block with background color after the text. The used command is from Symfony 4.3. I can provide instructions or find the exact control codes that were used if needed.

# Expected behavior

A solid block of background color. The screenshot is from cmd.

![image](https://user-images.githubusercontent.com/12109622/61876774-4d163680-aef6-11e9-8cb6-eef0265530c0.png)

# Actual behavior

The background color ends after the text.

![image](https://user-images.githubusercontent.com/12109622/61876748-3cfe5700-aef6-11e9-9625-e86fbc63af85.png)

**Comment by DHowett-MSFT** [comment]
Congrats, this is now the "Kill MeasureRight" (it'll make sense later) issue. The heart of the issue is that conhost can occasionally not tell whether the spaces that are in the buffer were on purpose or not. 🤷‍♀

**Comment by BladeMF** [comment]
More examples (hopefuly useful):
![image](https://user-images.githubusercontent.com/12109622/62536702-4ae99b80-b857-11e9-9304-82bbaebc2848.png)
See how "Success!" is OK, but "Application Migration" isn't? Not sure what that means.

**Comment by DHowett-MSFT** [comment]
I hacked at making MeasureRight care about attributes, and while it was slow it felt like it did the right thing.

**Comment by zadjii-msft** [comment]
Huh, this is /dup #32, and more broadly, we're tracking this in #8000.
