### ISSUE TITLE
Plotting using matplotlib from Windows terminal (ubuntu) doesn't work in python shell

### ISSUE THREAD

**Issue by anandijain** [microsoft/terminal#2106]
# Environment

```
Microsoft Windows [Version 10.0.18362.239]
Windows Terminal (Preview)
Version: 0.2.1831.0
```

# Steps to reproduce

1. Open a windows terminal, then an ubuntu tab.
2. Start python
3. `import matplotlib.pyplot as plt`
4. try to plot anything using matplotlib

# Expected behavior
I can't get the matplotlib graph window to show up at all, however, the graph will show in a normal command prompt.

# Actual behavior
No graph is produced, although, when calling `plt.plot(...)`, a memory location is displayed, indicating that a plot was initialized, but `plt.show()` does not actually create a window for viewing the plot.

**Comment by DHowett-MSFT** [comment]
WSL doesn't typically have support for windowing. Are you using an X server? Can you check whether your `DISPLAY` environment variable is being set?

The window that is being displayed in the working case is not owned by Console or Terminal, so .. we don't really have control over it.

The best I can think is we're not updating the environment to pick up the `DISPLAY` env var if you start your X server after you start Terminal.
