### ISSUE TITLE
Opening tab too fast crashes terminal

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#2113]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18941.1001]
Windows Terminal version (if applicable): commit id c97cccb

```

# Steps to reproduce

Open tab too fast and many of them.
Using shortcut key(default ctrl+shift+number) makes easy to open lots of tab at once

Which I was doing was holding shortcut key(crtl+shift+2 to open cmd) for few seconds.

# Expected behavior

Only one tab open or Lots of tabs opens without any problem.

# Actual behavior

Terminal crashes (without any error message)

**Comment by zadjii-msft** [comment]
The error that appears in the log is "Bad optional access".

My guess is this is secretly related to #2122 (shockingly). It might be already fixed, but I haven't checked on that branch quite yet.

If it's not already fixed, then it could be an exception on any of the Pane's `optional`s, it could be the profile `optional`s like 2122 was, or it could even theoretically be the `_cursorTimer` in `TermControl`. All of those were spots we were investigating for the previous bug.

**Comment by SJang1** [comment]
It seems to fixed crashing, but made another bug : 
![image](https://user-images.githubusercontent.com/29011440/62143582-34a98000-b32b-11e9-9c47-6d5ef494a2a6.png)

![image](https://user-images.githubusercontent.com/29011440/62143745-91a53600-b32b-11e9-8a53-2346e22324df.png)
(with tabTitle as cmd)

clicking on a tab and clicking in the console makes "only that" tab name to be shown like as normal.

**Comment by SJang1** [comment]
I'll make it as a new issue. This bug seems to be fixed. Thanks!
