### ISSUE TITLE
Iosevka Nerd Font crashes the app

### ISSUE THREAD

**Issue by vasiby** [microsoft/terminal#2114]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.2.1831.0

Any other software?
```

# Steps to reproduce

1. Download the font  
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf
2. Install into Windows
3. Edit profiles.json `"fontFace" : "Iosevka NF"`

# Expected behavior

Able to render the font without crashing. 
This font doesn't crash other software, tested Fluent Terminal, Hyper, ConEmu, cmder, VS code, IntelliJ IDEA

# Actual behavior

App immediately  exits  without any error messages when tab with this font is opened. If it's the default profile, the app doesn't even start.
Same with other Iosevka nerd fonts (Iosevka Term, Iosevka Mono)

**Comment by Kri-Ol** [comment]
Had the similar but a bit different issue with Fira Code. Fira Code comes with five faces - Light, Regular, Medium, Bold, Retina. If I put font face in JSON config as "Fira Code" it works (Regular face, I guess, is being picked up). If If I put font face in JSON config as "Fira Code Regular" it starts with garbled output in existing terminal and crash on new terminal start. Same problem (garbage, crash) for "Fira Code Light", "Fira Code Medium" and "Fira Code Bold". "Fira Code Retina" surprisingly, works fine as well as just "Fira Code". F.e., in VS Code all faces worked.

**Comment by DHowett-MSFT** [comment]
Yeah, this is a family/face issue #1163 combined with #550
