### ISSUE TITLE
Add some tests for invalid GUIDs in JSON

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2119]
> 
> 
> Should we add tests for the following?
> 
>     * [ ]  GUID in different GUID format
> 
>     * [ ]  completely invalid GUID (i.e.: guid = )
> 
>     * [ ]  GUID with letters in caps
> 
> 
> Or would the first two just be examples of invalid settings values anyways so there's no point?

From @carlos-zamora in #2117

**Comment by marcelwgn** [comment]
I would like to take my shot at this

**Comment by DHowett** [comment]
Go for it!
