### ISSUE TITLE
Feature Request - Prettified copy and paste to external sources

### ISSUE THREAD

**Issue by mscraigloewen** [microsoft/terminal#2124]
# Description of the new feature/enhancement

In email when I copy and paste from VSCode I get very nicely formatted text inside of the email which I find quite appealing. Could we add this to the terminal?

For example, here's what VSCode does:
- First I copy: 
![image](https://user-images.githubusercontent.com/42221804/61981495-b48fbd00-afae-11e9-89af-12b10629ce7c.png)
- Then I paste into email and it looks great: 
![image](https://user-images.githubusercontent.com/42221804/61981588-f1f44a80-afae-11e9-8150-4e5ae25d33fb.png)

I'd like Terminal to have the same behaviour.

Thank you!

**Comment by DHowett-MSFT** [comment]
Thanks! I think this is tracked by #1146.
