### ISSUE TITLE
Feature Request: Fixed window position and size

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/terminal#2126]
# Description of the new feature/enhancement

It would be great to be able to set a fixed window position for the terminal, like "top", "topLeft", "left", "bottomLeft" ... and the size.

Kind of like iTerm2 for macOS behaves. 

Let's say, I'd like to have the terminal window on the bottom of the screen, using the screen's full width, and 20% of the screen's height, or even 300px of the screens height.

"windowPosition": "bottom",
"windowSize: "20%" // or "300px"

**Comment by DHowett-MSFT** [comment]
This is #1043
