### ISSUE TITLE
Feature Request: Admistrator shell in new tab

### ISSUE THREAD

**Issue by 54696d21** [microsoft/terminal#2127]
add a button to open an admistrator shell in the same windows (make it possible to having adminstator shells and non administator shells in the same window)

**Comment by haydennyyy** [comment]
Maybe this could be done in the same way it is when launching any app as admin from the start menu. If you over over the profile and hold <kbd>ctrl+shift</kbd> and click, it'll launch the profile as admin.

**Comment by CatTheHacker** [comment]
Possible puplicate of https://github.com/microsoft/terminal/issues/632

**Comment by haydennyyy** [comment]
@CatTheHacker Not a dupe of #632, but it does seem related to #146

**Comment by CatTheHacker** [comment]
> 
> 
> There is not. I don't think we plan on supporting mixed elevated and unelevated tabs, because it's a bit of a security hole.
> 
> Yes I know `sudo` is a thing, but we've had lots of discussions with the security team about the creation of a `sudo` for Windows. The main problem is due to the fact that any unelevated processes can send keystrokes to any other unelevated windows.
> 
> If you had an elevated commandline running in an unelevated window, an untrusted bad actor could execute an elevation-of-privilege attack by driving the unelevated windows that's running the elevated commandline.
> 
> (as a matter of linking related threads, #146)

Maybe not exactly a dupe, but hella related

**Comment by joandrsn** [comment]
You should search before adding feature requests. Recent duplicates of this request: #1490 #1990 #2048
#1032 is the mega thread for all of them.

**Comment by 54696d21** [comment]
I'm sorry; I did search; I didn't find those
