### ISSUE TITLE
HTML copied text has invalid background after last char in row

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#2128]
## Environment
(note that HTML copy is not yet on master)

## Steps to reproduce
In terminal:
![image](https://user-images.githubusercontent.com/38111589/61994864-a8743000-b080-11e9-9de7-6b91bf93597a.png)

Pasted to Word:
## Expected behavior
![image](https://user-images.githubusercontent.com/38111589/61994710-5a5e2d00-b07e-11e9-981c-a4efbdff382a.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/38111589/61994721-91344300-b07e-11e9-9b5c-750636d08b32.png)

The color is taken form the first copied cell, `X` in this example.

**Comment by DHowett-MSFT** [comment]
Interesting. You filed this based on your pull request to GenHTML. Would you be interested in taking a look at it??

**Comment by mcpiroman** [comment]
It's mostly about html things like enforcing proper width of spans, and I'm moderately familiar with html. I might take it once I have more time.
