### ISSUE TITLE
File system error (12007)

### ISSUE THREAD

**Issue by wrathofodin** [microsoft/terminal#2129]
I installed terminal with choco and I can't run it. I installed from msixbundle and I'm getting the same error.

Windows 10 1903 (18362.239)

https://github.com/microsoft/terminal/issues/2022

**Comment by zadjii-msft** [comment]
Do you have a Windows Error Reporting bucket ID we could investigate?

Could you try deleting your profiles.json file, and re-starting the terminal, to see if that fixes it? The settings roam across PC's, so it's possible valid setting on another machine is invalid on this one. (make sure to back the profiles.json file up first, just in case).

**Comment by wrathofodin** [comment]
I don't have any bucket ID. There's no crash, just a message box with this error.

I don't have profiles.json file

**Comment by DHowett-MSFT** [comment]
Do you even have a screenshot of this filesystem error? This is not very much to go on.

**Comment by wrathofodin** [comment]
![image](https://user-images.githubusercontent.com/3116731/62082186-8df2b000-b254-11e9-821a-bdd4cdf6a22e.png)

**Comment by DHowett-MSFT** [comment]
This looks like the same thing as #1538.

**Comment by wrathofodin** [comment]
I wouldn't say it's the same. I can't use the terminal doesn't matter if elevated or not. Also, the error from the issue you linked doesn't show the same error.

**Comment by wrathofodin** [comment]
It was an issue with a firewall. It works fine now

**Comment by conradolandia** [comment]
> 
> 
> It was an issue with a firewall and etc/hosts. It works fine now

Could you comment a little more on that? I'm having the same issue. I think I have the same problem as you.

**Comment by DHowett-MSFT** [comment]
Yeah, I too am very interested in how those things are related.

**Comment by wrathofodin** [comment]
@conradolandia In the past, I used a tool [Destroy Windows 10 Spying](https://github.com/Nummer/Destroy-Windows-10-Spying) and it was blocking a bunch of Microsoft's addresses in the `C:\Windows\System32\drivers\etc\hosts` file and in the firewall. I removed those addresses from hosts and temporarily disabled the firewall and re-installed the terminal and it worked. I am suspecting it just couldn't download some default configuration or something like that.

**Comment by JamesSeaward** [comment]
I know this has been closed for a while but I just ran into this issue and it wasn't immediately clear how to workaround it.

Just empty your `C:\Windows\System32\drivers\etc\hosts` file, open Windows Terminal once, and then put the `hosts` file back to normal. Since doing this, the terminal has worked correctly. 

Both bugs related to this are marked as closed but this unhelpful error message is still present in the latest build. Even if this problem is caused by people blocking microsoft ip addresses it would be nice if it could fail more gracefully/helpfully.

**Comment by shark300** [comment]
I had a same issue too. I've installed Terminal on a corporate notebook but I've tried to log in my private Live account unsuccessfully earlier. Sometimes, I've got a notification message to repair that, but it was unsuccessful. After I removed this account, it works.

**Comment by zszen** [comment]
I have the same problem. Because I install it with offline network. It's ok.

**Comment by zhro** [comment]
I just did a clean format and reinstall of Windows 10 and got this error after installing the Minecraft launcher. I can't log in either, with it reporting some "Deep Ocean" error.

![launcher](https://user-images.githubusercontent.com/4738876/194766948-9d9d6f5e-2ca3-40ad-abf0-d2bb04c79ef2.png)
![after-installation](https://user-images.githubusercontent.com/4738876/194766949-900828f0-1249-4dbe-81c1-39fafc13e2bd.png)

**Comment by DHowett** [comment]
This is very interesting! Your Minecraft issue probably has the same root cause as the Terminal issue you're commenting on, but we haven't been able to solve either of them. _Huh._

**Comment by sylveon** [comment]
This is happening to users of my app that try to install the app on their debloated system. They're forced to downgrade to a 4 years old version :(

I'm trying to be a good citizen of the platform and adopt appinstaller, but it's hard when you get these kinds of strange reports every other week... Not to mention some of them removed the app installer app so they have to use powershell to even be able to install the app, ugh.

**Comment by zadjii-msft** [comment]
> try to install the app on their debloated system

_perhaps_, some of that stuff they removed as "bloat" was actually important. Crazy idea, I know 🤔 /s

In all seriousness, I don't think any of us on the Terminal team can really help with this. Maybe you'd have more luck getting traction over on the WASDK repo. Not sure where the internal bug report went, or what the status of that is ATM - I'm sure I could find it if I looked hard enough. 

I appreciate the effort in being a good citizen - it's something we deal with every day here on the Terminal, and we do try our best to make sure the papercuts we experience are escalated as we see 'em. It's annoying when we've got to deal with them, but it outright sucks when any 3p devs have to deal with them too.

**Comment by niekvb** [comment]
I experienced the same issue while having blocked MS telemetry endpoints. The app needs phone home to activate it's license so temporarily lifting the blocked endpoints (I suspect `licensing.mp.microsoft.com`) resolve fix the issue.

**Comment by zadjii-msft** [comment]
Not... really? The Terminal is a packaged app like any other packaged app on Windows. We (the Terminal) don't do any extra validation of our license beyond what the OS / Store already do. You can of course always grab an unpackaged terminal .zip off our Releases page as an alternative.

**Comment by sylveon** [comment]
Yes, store signed-apps need a license to run, whether they're free or not.

Speaking of @DHowett @zadjii-msft, but is there a way for a third party store dev to also get an offline license to deploy on offline machines, like you did in the preinstallation kit? Some of my users don't have access to the MS store for business and neither do I (I'm a solo independent dev).

I would try using the appLicensing capability to avoid this (since AFAIk it should bypass the store license stuff) but people I know tried this already and their store submissions where rejected and they were told to use the store for business :\

**Comment by DHowett** [comment]
@savchenko You can also download the "Preinstallation Kit" from any of our release artifacts, which contains an offline license provisioning file. _As of today,_ it's the best we can do for making sure a Terminal package install doesn't require internet access. I don't love it either.

@sylveon Watch this space (re `appLicensing`). We're about to go bother the Partner Center folks to make sure people don't get rejected for it. Grabbing a preinstall kit should be possible for any developer with partner center access, though... `Manage packages` -> `Get Windows 10 Package` -> `Download Windows 10 Package`.

If that's not available for you, then I'm all "question marks guy" meme over here.

**Comment by sylveon** [comment]
Yeah there doesn't seem to be a download option:

![image](https://github.com/microsoft/terminal/assets/6440374/c01c3daf-f444-4031-a761-8972d6deb4d6)

Gonna watch for the appLicensing stuff though 👀

**Comment by daltzctr** [comment]
@DHowett 

Is there any update on 
> Watch this space (re appLicensing). We're about to go bother the Partner Center folks to make sure people don't get rejected for it. 

I just submitted an app with appLicensing enabled to improve support for enterprise type scenarios (IE the above), and it got rejected saying the capability is not approved.

![image](https://github.com/microsoft/terminal/assets/105223895/df6087a1-c9b4-4fdc-b40e-513625d33176)

**Comment by unkowncoder01** [comment]
> I experienced the same issue while having blocked MS telemetry endpoints. The app needs to phone home to activate it's license so temporarily lifting the blocked endpoints (I suspect `licensing.mp.microsoft.com`) should resolve the issue.

Any solution to how to use .msix windows app without connecting to the internet for verfication? When I install an .msix app for the first time and turn off the wifi, it gives me the same error when launching the app "..error 12007", but just connecting to the internet then launching it once allows the app to launch even afterwards offline when disconnected from the internet & uninstalling then re-installing the app still works offline, its like the issue happens only the first time after a first-time install. Is there a way to bypass that signature thingy to launch the app first time offline after a first-time install?
