### ISSUE TITLE
[question] how to set the default path on startup?

### ISSUE THREAD

**Issue by tuananh** [microsoft/terminal#2132]
right now, it's default to mnt/c/WINDOWS/system32. can i change it to sth else, say $HOME?

**Comment by CatTheHacker** [comment]
You can change it by setting the `startingDirectory` property in `profiles.json`.
For example `~` results in CWD to be set to user profile path on Windows partition.
![image](https://user-images.githubusercontent.com/31106839/62002333-7fd84e80-b0f1-11e9-8580-9446e6488558.png)
![image](https://user-images.githubusercontent.com/31106839/62002338-9bdbf000-b0f1-11e9-90ac-a0b5948e98c4.png)

**Comment by tuananh** [comment]
when i use ~, it's not wsl home so  i ended up doing this instead `

`"commandline" : "wsl.exe ~ -d Ubuntu",`

**Comment by ckhordiasma** [comment]
how do I set the starting directory to the WSL version of "~", so for me, /home/ckhordiasma ?

I tried that and it didn't work.

**Comment by bestony** [comment]
yes, i try `~` and `/home/bestony`, but didn't work
