### ISSUE TITLE
Opening Windows Terminal exits program to report errors directly

### ISSUE THREAD

**Issue by csluoqi** [microsoft/terminal#2133]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

![image](https://user-images.githubusercontent.com/13494828/62001482-0148d480-b124-11e9-9c22-5a6c833c9a25.png)

**Comment by TayYuanGeng** [comment]
This looks related to #1445

**Comment by miniksa** [comment]
There are no steps in this bug and there are other similar crash bugs on the tracker already. I can't prove this is specifically any of those, but I'm relatively certain we have it covered. So I'm resolving this.
