### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by bgilbank** [microsoft/terminal#2136]
NEW documentation needed.

For WSL2, how can I set a starting directory in profiles.json? For PowerShell and CMD it's simply "startingDirectory" : "%USERPROFILE%".

What would it be for WSL using Ubuntu 18:04? Right now I land in name@sysstem32$, can't I just start at name@$.

This works correctly in the vscode terminal.

Thank you,
Brian

**Comment by Jarvis73** [comment]
Just use `"startingDirectory" : "//wsl$/Ubuntu/home/<user name>"`

**Comment by bgilbank** [comment]
Ah, thank you @Jarvis73. I had to specify the version too.

`\\wsl$\Ubuntu-18.04\home\<username>`
