### ISSUE TITLE
Backspace moves cursor left even ENABLE_LINE_INPUT is off

### ISSUE THREAD

**Issue by dimant** [microsoft/terminal#2137]
Windows Version	10.0.18362 Build 18362

I am setting up my console mode as: 

            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_ECHO_INPUT;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_EXTENDED_FLAGS;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_INSERT_MODE;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_LINE_INPUT;
            newMode |= Kernel32.CONSOLE_INPUT_MODE.ENABLE_MOUSE_INPUT;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_PROCESSED_INPUT;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_QUICK_EDIT_MODE;
            newMode |= Kernel32.CONSOLE_INPUT_MODE.ENABLE_WINDOW_INPUT;
            newMode &= ~Kernel32.CONSOLE_INPUT_MODE.ENABLE_VIRTUAL_TERMINAL_INPUT;

expected:
pressing backspace leaves the cursor where it is and sends me a backspace event via ReadConsoleInput

actual:
I receive a "\b" event and after I process it, the cursor moves left.

I can work around this issue by using VT sequences:
                        vtSequencer.CursorHide();
                        vtSequencer.CursorBackward(1);
                        vtSequencer.TextDeleteChar(1);
                        vtSequencer.CursorForward(1);
                        vtSequencer.CursorShow();

**Comment by zadjii-msft** [comment]
@dimant Is this a regression in behavior from a previous version of Windows? My gut's telling me that is just how backspace works. 

Usually when I see applications that are tying to emulate a line of input, they handle backspace by emitting `"\b \b"` - backspace, space, backspace. It looks to me like you only want `"\b "`, to leave the cursor where it was before.
