### ISSUE TITLE
Ability to move Windows Terminal by garbing an empty area of the tab region.

### ISSUE THREAD

**Issue by ddcruver** [microsoft/terminal#2138]
# Description of the new feature/enhancement
Allow Windows Terminal to be moved across screen easier by allowing more grab points.  Right now only clicking and dragging on a small section of the top bar allows you to move the window.  I keep on trying to click and drag on the empty portion of the tab selection to move the window.  This section is from far right most open tab to the + sign used to open a new terminal.

# Proposed technical implementation details (optional)
N\A

**Comment by DHowett-MSFT** [comment]
Please make sure to search before filing a new issue.
