### ISSUE TITLE
Unable to build with Visual Studio 2019 version 16.2.0

### ISSUE THREAD

**Issue by ajaykagrawal** [microsoft/terminal#2143]
# Environment
Windows build number: Version 10.0.18362.267

# Steps to reproduce
Update to the latest Visual Studio 2019 (16.2.0)
Build Terminal (you will get a compiler error)

(I had no issues building with 16.1.0)

# Expected behavior
Terminal should build without any errors

# Actual behavior
Here is the error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3272: There was a problem reading the implementation file "C:\Users\Ajay\microsoft\terminal\x64\Release\TerminalAppLib\TerminalAppLib.lib". "Unable to read beyond the end of the stream."

Possibly related to https://github.com/microsoft/msbuild/issues/4547

**Comment by DHowett-MSFT** [comment]
We're the ones who reported that issue! Is this in the `TerminalApp.UnitTests` project or the `TerminalApp` project?

**Comment by ajaykagrawal** [comment]
>>We're the ones who reported that issue! I
Oops! Perhaps the MSBuild team should use Terminal in its regression test suite!

>>Is this in the TerminalApp.UnitTests
Yes in the TerminalApp.UnitTests

**Comment by DHowett-MSFT** [comment]
We missed that one with our workaround. :smile:

**Comment by ajaykagrawal** [comment]
Managed to get the deploy done by commenting out UnitTests_TerminalApp from the configuration. (Every few hours or so I do a git pull and build a new version of the Terminal app. This is how much addicted I am to this app!)

**Comment by mbreaton** [comment]
Easier to just **unload** the project. This avoids any src changes and git pull will work normally

**Comment by hh-shiung** [comment]
Where in the solution would you comment it out from configuration? Unloading the project did not work for me.
