### ISSUE TITLE
Cannot cancel gitbash running task

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [microsoft/terminal#2145]
# Environment

```none
Windows build number: 18362.239
Windows Terminal version (if applicable): 0.2.1.18831.0

Any other software?

Git bash with the profile:
        {
            "acrylicOpacity" : 0.5,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "C:\\Program Files\\Git\\bin\\bash.exe",
            "icon" : "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
            "name" : "Git Bash",
            "startingDirectory" : "%HOMEDRIVE%%HOMEPATH%",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{9a3f80c4-d840-4781-a7d3-84f6c7c9dd7c}",
            "historySize" : 9001,
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : false
        },

Python 3.6.8-amd64

```

# Steps to reproduce

Set up gitbash with the json above. Run a long-running task in the current window. Ctrl+c doesn't kill the task

# Expected behavior

ctrl+c should kill the task

# Actual behavior

Cannot regain control over the current window.

**Comment by samuelkdavis-mccarthyfinch** [comment]
Opening a new gitbash tab, running `ps` to find the process id, then running `kill 1234123` fixes the first tab

**Comment by samuelkdavis-mccarthyfinch** [comment]
This could be the cause...

https://stackoverflow.com/questions/45987985/asyncio-loops-add-signal-handler-in-windows

**Comment by samuelkdavis-mccarthyfinch** [comment]
After a bit of investigation, it does seem to be an issue specifically with asyncio. I'm not sure if there's anything the terminal can do to regain control from runaway asyncio loops. Feel free to close this if there aren't any viable ways to control this from a terminal level.

**Comment by zadjii-msft** [comment]
Yea, this looks like it's out of our control. Fundamentally, the terminal is just a frontend for the Console API, so asynchio would need to find a better way to deal with this. 

I'm kinda surprised they don't implement a windows-specific version of `add_signal_handler` that adds a ConsoleCtrlEvent handler, but I don't really know the specifcs of why they may have chosen not to do that.
