### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Eddy555** [microsoft/terminal#2147]
# Reduce the Size Of the Tab Section To Give a Larger Area Of Title Bar For Drag and Drop of the Window 

Most windows apps allow you to click the title bar and drag the window around the desktop to place it where you want. The Terminal window has very large tabs which instinctively I go to grab and drag the window around, but all that does is select that tab. The actual area of the title bar you can grab on the right of the title bar is pretty small, so is awkward to use.
Looking at Chrome or Firefox their tabs are much smaller and provide a bigger area of the title bar to be selected. They also provide a small section above the tab to be selected. Clicking on a tab allows it to be pulled out of the window into it's own window. This is the kind of functionality I'm used to.

# Proposed technical implementation details (optional)

Reduce the size of the tab section to show a larger area of the title bar which will make it easier to select the window and drag it around the desktop. The tab section should obviously grow and shrink with the number of tabs that are open - much like most web browsers
![2019-07-30 07_55_56-Window](https://user-images.githubusercontent.com/13731803/62107532-b2c04500-b29f-11e9-96e7-466efdfdcb9a.png)

**Comment by widersky** [comment]
There is issue for that: #564 , described in mega thread #1375 too. And looks like this issue is solved and will be published in Terminal v0.3 :)

**Comment by Eddy555** [comment]
Ah brilliant. I did search before I posted too. (-: 
I'll close this then
