### ISSUE TITLE
[Bug Report] I carnt run the terminal in administrative mode

### ISSUE THREAD

**Issue by josh-65** [microsoft/terminal#2148]
# Environment
Windows build number: 1903 - 18362.239 - 64 bit
Windows Terminal version: 0.2.1831.0

# What's happening
I can't run commands because there's no way I know to run the app in administrator mode.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/62135507-ef903a00-b2a7-11e9-8b6f-f70da8314261.png)

**Comment by Gab1c** [comment]
The first four methods work, but the fifth method doesn't.
![1](https://user-images.githubusercontent.com/32360991/75891963-83903880-5e6b-11ea-87e5-a87936b414a6.png)

When I press this key, it looks like this
![2](https://user-images.githubusercontent.com/32360991/75892184-d964e080-5e6b-11ea-8396-347afc02f861.png)
Means the system cannot access this file
