### ISSUE TITLE
tab opening too fast, no title provided.

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#2151]
# Environment

```none
Windows build number: Microsoft Windows [Version 18945.1001]
Windows Terminal version (if applicable): commit id 3f62c8b
```

# Steps to reproduce

from #2113 

> Open tab too fast and many of them.
> Using shortcut key(default ctrl+shift+number) makes easy to open lots of tab at once
> 
> Which I was doing was holding shortcut key(crtl+shift+2 to open cmd) for few seconds.

> ![image](https://user-images.githubusercontent.com/29011440/62143582-34a98000-b32b-11e9-9c47-6d5ef494a2a6.png)
> 
> ![image](https://user-images.githubusercontent.com/29011440/62143745-91a53600-b32b-11e9-8a53-2346e22324df.png)
> (with tabTitle as cmd)
> 
> clicking on a tab and clicking in the console makes "only that" tab name to be shown like as normal.

# Expected behavior

Title shows.

# Actual behavior

newly fastly opend tab's title doesn't show before clicking a tab and clicking in the console.

**Comment by DHowett-MSFT** [comment]
This is actually #1205
