### ISSUE TITLE
PSCore fails to load profile if startingDirectory points to other drive

### ISSUE THREAD

**Issue by davidkwoods** [microsoft/terminal#2154]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
No
```

# Steps to reproduce

Set startingDirectory for the PSCore profile to a directory not on the C: drive.  In my example, the D: drive.

# Expected behavior

PSCore should still load its profile from `C:\Users\<user>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

# Actual behavior

PSCore attempts to load its profile from `\Users\<user>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` and fails because it tries to find it on the D: drive, which doesn't contain that file.

The same steps do not repro for classic PowerShell.  It loads its profile correctly when set to start on a different drive.

**Comment by DHowett-MSFT** [comment]
This is highly irregular. What version of PSCore?
This should also reproduce if you run `pwsh` from a standard console host by starting it from CMD. Windows Terminal doesn’t change how an application starts up, after all.

```
C:\>D:
D:\>pwsh
```

**Comment by BjoernPetersen** [comment]
I'm having the same problem with PSCore, but it's not related to the new terminal for me. It also happens in the old terminal and integrated in IDEs like IntelliJ.

**Comment by zadjii-msft** [comment]
@Björn Did you delete your comment for some reason? If you can confirm this is happening in other terminals, not _just_ the Windows Terminal, then we should definitely just close this issue in favor of tracking an issue on the powershell repo

**Comment by BjoernPetersen** [comment]
I re-read the issue and realized my problem is not related.
