### ISSUE TITLE
Win32 curl.exe should enable VT processing

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#216]
I believe curl.exe is owned by PowerShell team, but since the issue is conhost-related, and you guys are probably the ones who can best understand what the issue is, and know how to fix it quickly, I'll report this here hoping you can get it done.

curl for Windows 10 (%SystemRoot%\System32\curl.exe) works pretty well, but inherits the conhost mode of the parent process.
Because of this, VT markup served over http for console users renders the escape characters instead of processing them as control sequences.

For behavior parity with the original version, can someone please add a SetConsoleMode ENABLE_VIRTUAL_TERMINAL_PROCESSING to curl.exe ?

![curl wsl](https://user-images.githubusercontent.com/25664275/42294504-99f2c30a-7fe1-11e8-9fed-d54bc284980b.png)
![curl win32](https://user-images.githubusercontent.com/25664275/42294506-9b3492fc-7fe1-11e8-9c3d-a41e88827cc0.png)

**Comment by bitcrazed** [comment]
I actually have a change-set to enable VT mode in Curl and will be working with the team to incorporate it if they're willing to accept my PR.

Hopefully, this will remedy this problem.

**Comment by bitcrazed** [comment]
Update: The core of the changes is working nicely. A few more changes required to make curl handle codepages better on Windows, but we're making progress:

![image](https://user-images.githubusercontent.com/961950/45336503-bc7e7400-b538-11e8-9dd7-9b5425deae9b.png)

**Comment by bitcrazed** [comment]
Reopening since we haven't yet pulled & rebuilt curl from recent sources. 

Also started thread with team to consider taking this on.

**Comment by DHowett-MSFT** [comment]
Looks like it does this now.

**Comment by nu8** [comment]
How do users get the new cURL? It seems even Windows 10 1909 still has cURL 7.55.1
