### ISSUE TITLE
Narrator line navigation gets stuck on some lines

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2160]
> Open PowerShell, type dir, press &lt;Enter&gt;
> Caps + Page up a few times to switch to Line view
> Caps + Left arrow to move up the history buffer
> Caps + right arrow to move back down
> When Narrator tries to read pass the heading area (see below, navigation got stuck. (Somehow Narrator rectangle was cover two lines all at once)
> Mode LastWriteTime Length Name
> ---- ------------- ------ ----
> I was able to get past that using word or character navigation.

_migrated from 23051804_

**Comment by DHowett-MSFT** [comment]
> This is a bug in the Text pattern implementation of the application:
> 1. Create a few distinct lines in the command prompt/PS.
> 2. Get the document range and move it by line a few times (to such a line that the previous and current are very distinct).
> 3. Collapse the line at the Start endpoint.
> 4. Expand the endpoint to Word.
> 
> **Expected:** First word (however that unit is defined) in the navigated-to line (navigated in 2).
> **Actual:** The line preceding the line navigated in (2).

**Comment by miniksa** [comment]
Carlos, I think we agreed that it could be acceptable to use the user-defined word delimiters list to segment any individual expansion from character to word to satisfy this ask. Can you start a mail thread and confirm that's acceptable then implement it eventually?

**Comment by carlos-zamora** [comment]
Pushing back to 21H1 Milestone. We're not entirely ready to merge Accessibility changes to 20H1 and there's a workaraound for this issue. Better to push it back and fix altogether than potentially break more things.

**Comment by carlos-zamora** [comment]
For the record, there's two bugs here and I'm pretty sure they are related.

1. Line navigation downwards
  - Narrator rereads the same line
2. Line navigation upwards
  - Narrator skips the line above

There's a few surprising issues here...
- When using Inspect.exe or Accessibility Insights to explore the text buffer, this bug does not occur. These tools accurately move to the preceding or next line without any issues. The same goes for moving just the endpoints, as opposed to the entire Text Range.
- I've tested this with Narrator and set two print breakpoints to know when a `Move` function call is performed and when an `ExpandToEnclosingUnit` (Enclose) one is performed (as well as the parameter used). And the results were interesting and confusing...

**Result when on the WRL Upgrade branch**
```
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
MOVE: TextUnit_Line (3)
ENCLOSE: TextUnit_Line (3)
ENCLOSE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
ENCLOSE: TextUnit_Format (1)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
```
**Result when on the Word Navigation branch**
```
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
MOVE: TextUnit_Line (3)
ENCLOSE: TextUnit_Line (3)
ENCLOSE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
MOVE: TextUnit_Word (2)
ENCLOSE: TextUnit_Format (1)
ENCLOSE: TextUnit_Format (1)         <---
ENCLOSE: TextUnit_Format (1)         <---
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Document (6)
ENCLOSE: TextUnit_Format (1)         <---
ENCLOSE: TextUnit_Format (1)         <---
```

Here, the lines with a `<---` are the new lines compared to the one before.

I noticed that Narrator updates the bounding rects to match the word it is reading at the time, AS IT READS IT.

But I don't understand why Format is being called. I'm guessing it just wants to do a better job with groupings.


Either way, I'm betting that this is somewhat related to the issue. Investigating further.
