### ISSUE TITLE
Azure Cloud Shell Connector Not Working

### ISSUE THREAD

**Issue by isaac2004** [microsoft/terminal#2170]
# Environment

```none
Windows build number: 10.0.18941.1001
Windows Terminal version (if applicable): Source
```

# Steps to reproduce

- Fresh Install of Terminal from Source
- Try to open Azure Cloud Shell Connector

# Expected behavior

- Device Flow kicks off and you can connect to Azure
 
# Actual behavior

- Get following message
> Could not connect to Azure. You may not have internet or the server might be down.

Opening up Fiddler, the request is failing, here is the request

```
POST https://login.microsoftonline.com/common/oauth2/devicecode HTTP/1.1
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded; charset=utf-8
User-Agent: cpprestsdk/2.10.13
Content-Length: 57
Host: login.microsoftonline.com

client_id=0&resource=https://management.core.windows.net/
```

and response
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: 036d9b04-0b15-4948-88e3-1298fe521f00
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=AgBw0kjQZyJGh-9yya_oOWo; expires=Fri, 30-Aug-2019 13:29:10 GMT; path=/; secure; HttpOnly
Set-Cookie: esctx=AQABAAAAAAAP0wLlqdLVToOpA4kwzSnx6Nn0i9n3KONl8oqKUDrwVI49N60kNuXitGhI2l65usEtATWKSOh8_SSS6SxU8qs6Mc2TKjto45yvCwsR1FnOxysOiKELlbMM8oFUyR0pRNEedN5J_pDsAlMLiz5CCixbFrYu1kevQ7G277G0tWGQ1Bmr6yQvertj7I1EFoMdyWkgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=prod; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
Date: Wed, 31 Jul 2019 13:29:10 GMT
Content-Length: 468

{"error":"invalid_request","error_description":"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 036d9b04-0b15-4948-88e3-1298fe521f00\r\nCorrelation ID: 62f6beea-e136-430d-8262-d762ad319f00\r\nTimestamp: 2019-07-31 13:29:10Z","error_codes":[50059],"timestamp":"2019-07-31 13:29:10Z","trace_id":"036d9b04-0b15-4948-88e3-1298fe521f00","correlation_id":"62f6beea-e136-430d-8262-d762ad319f00"}
```

Looks like no client_ id is being set in code. Do you need to set this somewhere?

**Comment by zadjii-msft** [comment]
This definitely isn't supposed to work at the moment. We need to manually embed our client ID in the code, and we're definitely not pushing that to the repo. We'll stamp that client ID into the build during the release process, but it won't work in local builds unfortunately.

This is now the issue for "Display a message when someone tries to use the azure connection in a local build without the client ID".

CC @PankajBhojwani and @DHowett-MSFT

**Comment by isaac2004** [comment]
So is there a workaround at the moment? Or should we just remove the profile?

**Comment by PankajBhojwani** [comment]
There is no workaround right now, you can remove the profile if you don't want it. We will make it so this option does not show up in local builds in the future. Thank you!
