### ISSUE TITLE
Find a way to build and run Windows Terminal from the commandline

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2171]
Since #1987, our SxS manifest is auto-generated, so it's certainly possible to run the terminal unpackaged again. However, we need the `resources.pri` that's only generated by building the CascadiaPackage project. Ideally, we'd be able to rebuild the terminal code (with `bx`, #2168), and launch it using `openterm`. We need to figure out a way to get openterm to build the appx's resources.pri for us, and not re-build every time `openterm` is called.

**Comment by DHowett-MSFT** [comment]
This is a duplicate of #926!

**Comment by zadjii-msft** [comment]
Oh my god it is
