### ISSUE TITLE
Windows Server 2019 not work

### ISSUE THREAD

**Issue by zb737472783** [microsoft/terminal#2177]
choco install 
ERROR: This package requires at least Windows 10 version 1903/OS build 18362.x.

**Comment by DHowett-MSFT** [comment]
Yup. It's true.

**Comment by zb737472783** [comment]
Server2019 
When can I use it?

**Comment by zadjii-msft** [comment]
We're not planning on extending support to Server 2019, because there are certain OS features we depend upon that are only available on Windows 18362 and above.

**Comment by VasilyMedved** [comment]
This is sad.
You know the main target audience for Windows Terminal, right? It is very frustrating that for some unclear reason I cannot use the application for managing my servers as they don't (and will not to in observable future) be updated to latest 18362. This is kind of things that remind you that despite its cool and stuff its still Microsoft.

**Comment by zadjii-msft** [comment]
> for some unclear reason

>  there are certain OS features we depend upon that are only available on Windows 18362 and above

That seems like a pretty clear reason to me. Namely, the features that are missing are "XAML Islands" and unpackaged/side-by-side winrt activation. The Terminal can't really draw _any_ UI without xaml islands, and we' can't do very much of _anything_ without the second.

**Comment by VasilyMedved** [comment]
Thank you @zadjii-msft for quick and honest answer. I appreciate the intentions of the developers making Terminal and apologize if my previous comment is offensive in any kind.
However, if we take a look more deeply, on higher level, the root of the problem persists in my opinion.

1. According to ms blog https://blogs.windows.com/windowsdeveloper/2018/11/02/xaml-islands-a-deep-dive-part-1/ the XAML Islands was announced back in 2018, included only in 2019 may update 18362

2. There was intention decision to 100% rely on this technology back in July 2019 - first Terminal release - month or so after XAML Islands its just released officially. 

Conclusion: As an engineer I understand the urge to try latest and greatest things. 
But, hey, the target audience of Terminal is not accountants or  - its IT enthusiasts, professionals, system administrators. 
The urge of having better tooling for windows, including cmd among this people is big.
So in this case intention decision to ignore all of these users - the Win 7 (still 30% of market as of today), Win 8, Win Server 2016, Win Server 2019 even.... It's just...sad, you know? 

Even its completely logical and valid, the fact that one need to update entire OS just to finally have cool terminal in windows is killing me.

Again, I appreciate the work, the app is free and I have no right to complain about it, so please ignore.

**Comment by rtc-focus** [comment]
VasilyMedved above is very gracious imo. We are not talking about open-source software here, Windows is expensive and continued investment in its improvement is to be expected.
This is absolutely in line with Microsoft's sorry history in command line. In nearly 40 years from the pathetic MS-DOS command line and its impaired descendants, through Powershell (let's look at Perl and invent something even more obscure and idiosyncratic) to Windows Terminal lies a consistent indifference to user needs and failure to learn from other people's work on command line systems from the 1960s onwards.
So finally Microsoft creates a respectable interactive command shell - to fanfares of self-congratulation about the cool advanced platform it is based on. Never mind that as Vasily points out the result is inaccessible to the very community that actually needs and wants it.
I know Microsoft is doing great work these days in the open source community, and I applaud that. But I would still like to see more user focus in the products I actually pay for.

**Comment by DHowett** [comment]
Thanks for the reminder to lock this thread.
