### ISSUE TITLE
Ssh-copy-id error passing the certificate

### ISSUE THREAD

**Issue by consciencelx** [microsoft/terminal#2178]
Ssh-copy-id : The "ssh-copy-id" entry cannot be recognized as a cmdlet, function, script file, or the name of a runnable program. Please check the spelling of the name, if the path is included,
Make sure the path is correct and try again.

**Comment by DHowett-MSFT** [comment]
We don't own that tool, console or terminal don't provide that tool, your SSH provider should be providing that tool.
