### ISSUE TITLE
Find the actual issue keeping conhosts from exiting when tabs are closed

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#2185]
We have a job object for the conhost in PTY mode that is supporting the connection on each tab. But this was because the conhosts weren't exiting.

However, conhosts should just exit when they have nothing to do.

This represents taking the job object off and figuring out what the actual underlying issue is that is keeping the conhost from realizing it can just exit.

**Comment by zadjii-msft** [comment]
We think this was actually probably resolved by #2525. It's not happening anymore, so we're going to resolve it for now?
