### ISSUE TITLE
Tab row is not aligned to the left on initial loading

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2188]
version 0.3.2112.0

![image](https://user-images.githubusercontent.com/3235846/62271622-6446ae00-b439-11e9-8bc0-35c75462eebe.png)

This happens on initial loading. Maximizing -> Restoring window corrects this.

_Originally posted by @rjfmachado in https://github.com/microsoft/terminal/issues/1375#issuecomment-517145501_

**Comment by zadjii-msft** [comment]
@rjfmachado Can I get more info from you? 
* Do you have multiple displays?
* What DPI is your primary (and secondary) displays?
* Does simply resizing the window fix this?
* If you set the `background` of your terminal to something dark (like `#000000`), does the line appear along the entire left side of the window, or just the tabs?

**Comment by rjfmachado** [comment]
Do you have multiple displays?
**[RM] 3 monitors, Portrait (24" 1200x1920 @ 100%), Landscape (32" 4K @ 150%, Primary), Portrait (24" 1200x1920 @ 100%)**, side by side
What DPI is your primary (and secondary) displays?
Does simply resizing the window fix this?
**Yes, as does maximize/restore**
If you set the background of your terminal to something dark (like #000000), does the line appear along the entire left side of the window, or just the tabs?
**Entire left side**
[profiles.txt](https://github.com/microsoft/terminal/files/3468956/profiles.txt)

**Comment by DHowett-MSFT** [comment]
@cinnamon-msft and @carlos-zamora are apparently also seeing this

**Comment by DHowett-MSFT** [comment]
Haven't seen this one in a while. Let me know if it's still around!
