### ISSUE TITLE
Feature Request: Start teminal when user log-in

### ISSUE THREAD

**Issue by leoniDEV** [microsoft/terminal#2189]
# Description of the new feature/enhancement

Over time I written many Powershell scripts and modules to manage many stuff (either for personal and for work) I use some modules for manage my dev environment or my home router, or move, rename, delete personal fotos, ect.
So I'm used to have a Powershell session start when I log-in.
Now I want to move to Windows Terminal and so I would like to have it to start when I log-in

# Proposed technical implementation details (optional)

The UWP SDK expose a way to configure a packaged app to start when a user log-in by adding the [`windows.startupTask`](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#start-an-executable-file-when-users-log-into-windows) extention to the manifest

**Comment by miniksa** [comment]
If someone wants to add something like this following the MSDN documentation on adding a startup task, we're fine with it.

https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.StartupTask
https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.StartupTask.RequestEnableAsync

**Comment by jelster** [comment]
I want to help out with this, so I've been assessing the work involved in doing it. Though this isn't quite in my wheelhouse, I figured that laying these thoughts out might help move this particular feature along a bit even if I'm not able to actually complete everything on my own. Feedback on the below worklist is appreciated as I'm sure there's a lot I've missed or gotten wrong in this first draft!

High-level task list:

- [ ] Define startupTask extension in AppX manifest. _[note: I am still not familiar enough with the project structure to say exactly _which_ manifest will need this]_ Here are some candidates:
    - [CascadiaPackage](https://github.com/microsoft/terminal/tree/master/src/cascadia/CascadiaPackage)
    - [WindowsTerminalUniversal](https://github.com/microsoft/terminal/tree/master/src/cascadia/WindowsTerminalUniversal)

- [ ] Modify [GlobalAppSettings](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/GlobalAppSettings.cpp) to add `StartOnUserLogin` global app setting. Include implementations for To/FromJson, ApplyToSettings, etc 
- [ ] Incorporate into [AppLogic](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/AppLogic.cpp)
    - Implement methods to invoke enable/disabling of startup task via `StartupTask.GetAsync... 

    ? [`AppLogic::OnLoaded`](https://github.com/microsoft/terminal/blob/4834604ddc285a0b85ced592a8f1773294856711/src/cascadia/TerminalApp/AppLogic.cpp#L335) add conditional logic to invoke the enable on startup request process `startupTask.RequestEnableAsync`

    ? [`AppLogic::ReloadSettings`](https://github.com/microsoft/terminal/blob/4834604ddc285a0b85ced592a8f1773294856711/src/cascadia/TerminalApp/AppLogic.cpp#L625) Add call to startup task logic _[note: not sure if this is correct location]_

HTH!

**Comment by jelster** [comment]
@miniksa - would you prefer I create a new issue following the same format as [this](https://github.com/microsoft/terminal/issues/4000) to track [these specs](https://github.com/microsoft/terminal/issues/2189#issuecomment-596604648), or continue to edit in-place with refinements?

**Comment by zadjii-msft** [comment]
Honestly, you could probably edit-in-place here if you want.
