### ISSUE TITLE
Chinese characters are not rendering correctly if I type above them.

### ISSUE THREAD

**Issue by klesh** [microsoft/terminal#2191]
# Environment

```none
Windows build number:  Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable):   0.2.1831.0
```

# Steps to reproduce

1. Fire up WSL
2. Run vim
3. Enter some Chinese characters, they seems to be fine.
4. Press Esc, press o to insert a new line above
5. Start typeing some English letter...
6. And the Chinese characters become smaller than normal size...
7. If I type English letter beneath, It works OK

![](https://i.imgur.com/R9Zfvka.png)
![](https://i.imgur.com/QAyWUVK.png)
![](https://i.imgur.com/fZSyyJa.png)

# Expected behavior

Chinese characters should stay the same size no matter I type something above or beneath it

# Actual behavior

Chinese characters turn into smaller size  if I type English above the line.

**Comment by miniksa** [comment]
WELP. I'll get to this.

**Comment by skyline75489** [comment]
This is also happening in OpenConsole:

![图片](https://user-images.githubusercontent.com/4710575/69121839-382e6600-0ad8-11ea-926a-21ff110d4ab8.png)

But strange enough. The stock  `cmd.exe`  on Windows 10 is good:

![图片](https://user-images.githubusercontent.com/4710575/69121883-56946180-0ad8-11ea-8176-432b9098f066.png)

**Comment by zadjii-msft** [comment]
Another repro gif courtesy of @zhixiangjoy in #3812

![](https://user-images.githubusercontent.com/15685217/70017393-ed274f00-15bd-11ea-822e-2ba2fe29a14c.gif)
