### ISSUE TITLE
Reset settings

### ISSUE THREAD

**Issue by letanloc1998** [microsoft/terminal#2192]
# Description of the new feature/enhancement
I think it has feature reset settings

# Proposed technical implementation details (optional)

**Comment by miniksa** [comment]
It does. Delete the JSON file.

**Comment by letanloc1998** [comment]
> It does. Delete the JSON file.

Thank you. But I think should button or somthing like that to easy reset

**Comment by zadjii-msft** [comment]
I'm sure when we land #1564, we'll make sure to include such a button.
