### ISSUE TITLE
Provide Terminal program path reliably / ability to open new Terminal instance using a keyboard shortcut

### ISSUE THREAD

**Issue by drk-mtr** [microsoft/terminal#2194]
**Apologies if this is a duplicate - I was unable to find anything related after a few searches - if it is then please feel free to remove without any warning!**

# Description of the new feature/enhancement

Currently in Windows 10, the only way to open the program with a keyboard shortcut is by:
- Opening a run prompt and running `shell:AppsFolder`
- Dragging a shortcut to the desktop
- Binding keys to this shortcut and leaving it on the desktop

This clutters the desktop unnecessarily and is brittle in that (I suspect) the folder changes upon update due to the version number in the path (e.g. `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\...`).

# Technical considerations

It would be great if there was a way to bind a key as part of the install process or within the settings file, but I realise this may reasonably be regarded as an OS level concern. I'm stunned that Microsoft doesn't provide a simple way to do this within Windows, but this is not an issue for the Windows Terminal team. 

I'm sure I could get around this by using something like `AutoHotKey` though, so I guess we just need a way to reliably derive the path of the application...

**Comment by bitcrazed** [comment]
A good interim solution here is to pin any app to your taskbar. You can launch any app pinned to your taskbar by hitting the <kbd>WINDOWS</kbd>+<kbd>[n]</kbd> where n is the 1-based index of that pinned app - 1st  = 1, 2nd = 2, etc.

I always layout my pinned icons so my favorite browser is 1st, Terminal is 2nd, Outlook is 3rd, VSCode is 4th, etc. I can then launch Terminal, for example, by hitting <kbd>WINDOWS</kbd>+<kbd>2</kbd> with my left hand.

**Comment by zadjii-msft** [comment]
To pile on Rich's bullet 2: you can also just hit Windows and type `wt` and hit enter. That should execute `wt.exe`, which is the execution alias we've registered for the terminal.

You may also be interested in #653

**Comment by bitcrazed** [comment]
Ooh, nice one @zadjii-msft - adding with credit to the list above :)

**Comment by drk-mtr** [comment]
Thanks both - really appreciate it!

**Comment by bitcrazed** [comment]
Glad we could help :)

**Comment by letmaik** [comment]
I actually still prefer the solution by the issue poster. To avoid the icon on the desktop you can change it to "hidden", assuming you're hiding hidden files/folders. I now made ctrl+alt+t the shortcut to open Terminal. It takes a surprisingly long time to pop up though (4-5s) compared to launching from the start menu (~0.5s).
