### ISSUE TITLE
Cursor blinking snaps the viewport back to the bottom

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2196]
I just updated to 0.2.1831.0 in 18950.1000.  In an Ubuntu shell (now WSL 2), I can't scroll back the buffer.  It looks like the flashing cursor is pulling the focus back to the bottom line every time I try to scroll up with both the keyboard and the mouse wheel.  

It also looks like a new line is sent on every scroll up too, so the text I want to see gets further away on each attempt!

Powershell and Dos windows do not do this

_Originally posted by @tomfakes in https://github.com/microsoft/terminal/issues/1375#issuecomment-517422583_

**Comment by tomfakes** [comment]
And of course, a reboot fixed it.

This might be a WSL problem, as I'd just upgraded my Ubuntu to WSL 2.

**Comment by zadjii-msft** [comment]
Ah shoot. I was really curious what was causing that. I'd be really shocked if it was a WSL problem if it worked in conhost ("powershell" and "dos" windows) but not the Terminal.

Was there a particular shell or program you were running that caused the behavior to start?

I guess if it's not repro'ing anymore we'll need to close this, bu twe can always re-open if we get a lead.

**Comment by BrightSoulXYHY** [comment]
hello I have the problem too 
at the version 0.3.2142.0  download in win store
In cmd/WSL/PowerSheel it doesn't work well

using key map to scroll works 
using wheel not


I've reboot macnhie and softare both,and reinstall win Termibal could not solve it

**Comment by adrianghc** [comment]
This may be a different issue altogether, in that case please let me know and I will open a separate issue. But one case where I cannot scroll is with an application like poolmon from the Windows WDK that takes up the entire screen buffer while it's running. Under the normal Windows 10 terminal, I can scroll through it with the scrollbar and the scroll wheel but using Windows Terminal 0.3.2142.0, there is no scrollbar and using the scroll wheel does not do anything either.

**Comment by TayYuanGeng** [comment]
Currently running on Microsoft Windows [Version 10.0.18362.239], Windows Terminal 0.3.2142.0
The scrolling gesture on my laptop trackpad is not working.

**Comment by zadjii-msft** [comment]
The last 3 comments all sound like #979, so I'll redirect y'all to that thread.

**Comment by adrianghc** [comment]
I saw that issue but mine is different because it is unrelated to touchpad usage, under my scenario scrolling doesn't work even with mouse or keyboard.

**Comment by zadjii-msft** [comment]
@adrianghc Can you file a new issue then? Preferably with screenshots :)

**Comment by adrianghc** [comment]
@zadjii-msft Done. #2364

**Comment by DHowett-MSFT** [comment]
We never got a lead on this, I think, and the repro disappeared. Closing. Feel free to ping me to reopen if it's not covered elsewhere.
