### ISSUE TITLE
Bug Report - Terminal crashes after WSL changes (reinstalling Ubuntu)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/terminal#2199]
* I set WSL as my default profile
* I then uninstalled Ubuntu 
* The terminal crashes on opening (see picture)
* I reinstalled Ubuntu - Same issue
* I uninstalled the terminal and reinstalled it - Same issue

I can't seem to fix it now, even if i uninstall and reinstall.
I don't know where the profile is located either.

**Behaviour**
It will be transparent for a few seconds, then crash

<img width="819" alt="terminalScrewed" src="https://user-images.githubusercontent.com/936006/62329929-300dd480-b4af-11e9-999a-349b2c4fecdf.png">

**Comment by jasonwilliams** [comment]
Luckily i still had the profile open in VSCode so was able to change it. 
But it would be good for developers who are tinkering around with this to know where the profile is located

**Comment by miniksa** [comment]
This is #1348 and @zadjii-msft is going to try to make it pick something else when the default is missing to stop the crash ASAP.
