### ISSUE TITLE
Title tab is very large, don't auto scale size

### ISSUE THREAD

**Issue by letanloc1998** [microsoft/terminal#2202]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Title tab is very large, don't auto scale size. If I open many tab, i can't click "x" to close this tab (use exit command to exit)
There is many tab but can't see three tab
![image](https://user-images.githubusercontent.com/26348718/62345261-e27b8100-b51b-11e9-86fa-24897814cc75.png)

# Expected behavior
Auto scale size title tab as chrome

# Actual behavior
Hidden title tab

**Comment by zadjii-msft** [comment]
This is something we're tracking as part of #1375
