### ISSUE TITLE
Bug Report: Double Click should select delimiter runs

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2206]
# Environment

Caused by #1197.
More apparent in #2184.

# Steps to reproduce

1. ensure double click delimiters includes " "
2. double click on empty line

# Expected behavior

Selection should encompass entire line.

# Actual behavior

Selection encompasses one cell.

# Additional Info

This one's on me. Idk why I thought that double clicking a delimiter should only select the delimiter itself. That's not useful.

Instead, the selection seems like it should expand to the first non-delimiter in either direction (exclusive range). For example,
`O` is non-delimiter
`X` is delimiter
Double clicking on any of the X would result in the following selection (denoted by [ and ])
`OOOXXXXXXOOO`
`OOO[XXXXXX]OOO`

**Comment by DHowett-MSFT** [comment]
From #2353

> Not sure if I'll be able to get to this one on time. I'm hoping that the PRs referenced above provide enough guidance to get started. Feel free to tackle this on (just be sure to mention that here).
