### ISSUE TITLE
Screen space usage is not lean + a few UX issues

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#2209]
# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version: 0.3.2142.0
```
I just tried out the new Terminal v0.3. I have legacy WSL installed. I'd like to report a few UX issues. I realize that some of them are not related to others and will be happy to open separate issues for them if you let me know which ones are admissible.

First a few screenshots

1. When I first open it, I have by default a PowerShell tab popped up, the Terminal Window occupied approx. half screen on my laptop.
![image](https://user-images.githubusercontent.com/1041752/62408517-99ced100-b5ca-11e9-8886-f7b883c21900.png)

2. When I open a Legacy tab:
![image](https://user-images.githubusercontent.com/1041752/62408545-f8944a80-b5ca-11e9-8645-1d0fed76fe1f.png)

3. When I open two more tabs, the active one is the fourth when which is not visible at all:
![image](https://user-images.githubusercontent.com/1041752/62408681-d26faa00-b5cc-11e9-8644-ae9bca61d9d6.png)

4. Active tab is the second one, but you can barely see it:
![image](https://user-images.githubusercontent.com/1041752/62408711-35614100-b5cd-11e9-90fb-1147e22ade1d.png)

Some issues I experience with this UI:
1. Very huge tab title for PowerShell: `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` which occupies 25% of my total screen width. This makes the WSL tab title be cut to: `kantorov@pc:/mnt/c/WINDO`. I would be completely satisfied if this read `PS v1`, I don't care to learn the full shell executable path to be present at all times in tab titles. In the context menu that creates tab this is just called "Windows PowerShell" (still long), but much shorter than the the full path. Also the tab title is inconsistent with the context menu

2. Tab titles are inconsistent. The PowerShell one points to the underlying shell binary: `powershell.exe`, the WSL one to the working directory path.

3. When I open another tab (PowerShell one by default), they are simply not visible. Not a single indication that I have more tabs. To see the third tab I have to maximize the shell window. Yet when I maximize it, I still cannot see the fourth tab.

4. Active tab is "black on dark gray". You can barely see which tab is active, the color difference is not contrastive enough. Chrome uses "gray on dark gray + some shadows" which is a bit better. The Terminal case is aggravated because the WSL Legacy shell background color precisely matches the color of the active tab.

5. `WSL v1` is called just `Legacy` in the context menu, which is very confusing. Word `WSL` / `Ubuntu bash` (or similar) is not even mentioned.

6. By default WSL Legacy starts in `/mnt/c/Windows/system32`. The old install started in `/mnt/c/Users/user` which is home directory and makes much more sense.

7. Copy-Paste: most expected "Enter" / "Ctrl+Shift+C" do not work

8. The cursors are strange. The text cursor is caret which is not very well visible. A single mouse click creates another selection cursor. It's impossible to get rid of by more mouse clicks. The Ubuntu Terminal is much more predictable.

Unfortunately all these issues prevent me from daily usage of the new Terminal, and I am retreating to wsltty (which does not support tabs, so I wish Microsoft Terminal could replace it).

**Comment by vadimkantorov** [comment]
Should I convert these as comments to https://github.com/microsoft/terminal/issues/1375 ?

**Comment by Luuk34** [comment]
No, but maybe change the title to "WTF are they doing to improvement, and why are they not incorporated in the 0.3 release?"

Like:
1) the missing 'tabeTitle'  (is not present by default, and therefore creating a very wide tab)
2) the 'added' Azure thing   (why not make the thing you have work OK. by adding this you create extra noise about not working thing... see #1375)

**Comment by DHowett-MSFT** [comment]
@vadimkantorov Some of these are already tracked in this bug tracker, but the rest can be turned into comments on #1375. It's very hard for us to handle bug reports that have, like, eight different things in them, so we try to consolidate them where we can.
