### ISSUE TITLE
All IME's don't work (Chinese/Japanese/Korean input, Emoji Picker, etc.)

### ISSUE THREAD

**Issue by ZeddG93** [microsoft/terminal#2213]
# Environment

```none
Microsoft Windows [版本 10.0.18362.267] 
Windows Terminal version (if applicable):0.3.2142.0
```

# Steps to reproduce

1. Open the terminal.
2. Switching CJK input methods.(doesn't work)
3. Typing.

# Expected behavior

Show phrase candidate boxes.

# Actual behavior

Directly entered English.

**Comment by klesh** [comment]
Microsoft Windows [Version 10.0.18362.239]
Version: 0.3.2142.0

I'm having the same problem here.

**Comment by yuchenyang1994** [comment]
Microsoft Windows [Version 10.0.18950.1000]
Version: 0.3.2142.0

i'm having the same problem here.

**Comment by etern** [comment]
Same here, as I remember, it works fine in Preview-0.2

**Comment by Z-H-Sun** [comment]
Likewise. IME selection was supported in version 0.2

**Comment by zeyu203** [comment]
Microsoft Windows [Version 10.0.18362.267]
Version: 0.3.2171.0

I'm having the same problem here.

**Comment by zadjii-msft** [comment]
I'd think that @philnach might have some thoughts in this area. I believe #1919 might improve this dramatically. I'd be curious to find out what caused this to regress since 0.2. Maybe something from @carlos-zamora's accessibility work slightly regressed this as an unexpected side-effect?

(also related #459)

**Comment by spindensity** [comment]
Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version: v0.3.2171.0 installed from Microsoft Store.

Same problem here.

**Comment by wrvsrx** [comment]
Microsoft Windows [Version 10.0.18956.1000]
Windows Terminal version: v0.3.2171.0 installed from Microsoft Store.

Can't input Chinese character in windows terminal.

**Comment by etern** [comment]
Hi developers, I notice that this issue is added to milestone `Terminal v1.0`, which is Due by April 30, 2020.
Would you consider fix this a little earlier? I think IME is of great use in non-english countries.

**Comment by zadjii-msft** [comment]
@etern Yea this is certainly a higher priority task for us than that milestone lets on. Unfortunately we only really have milestones for "things we're getting done in the current month", "things we need by 1.0", and "things that can wait till after 1.0". I don't think we're going to be able to fix this by the end of the month, hence why it's parked on the 1.0 milestone currently.

**Comment by ubsan** [comment]
This also affects the emoji picker afaict.

**Comment by zhoupro** [comment]
Uninstall v0.4, download v0.2 from assets.

**Comment by szgaozg** [comment]
Windows Terminal version: v0.4.2382.0 installed from Microsoft Store.

Can't input Chinese character in windows terminal.

**Comment by duskmoon314** [comment]
Microsoft Windows [10.0.18362.356]

Windows Terminal (Preview) Version: 0.4.2382.0 `Get from Microsoft Store`

Same problem

I also can not use emoji in windows terminal. I try to use `windows + .` to use emoji, but nothing happens when I click.

**Comment by zeyu203** [comment]
Windows Terminal (Preview) Version: 0.5.2661.0
Can't use Chinese IME in it eighther

**Comment by zhoucl** [comment]
> Windows Terminal (Preview) Version: 0.5.2661.0
> Can't use Chinese IME in it eighther

+1

**Comment by richpurnellai** [comment]
Windows Terminal (Preview) Version: 0.5.2681.0
Can't use Chinese IME in it eighther

**Comment by zadjii-msft** [comment]
Hey all, just to let you know, unless we make some comments in here, you should go ahead and assume that this will continue to not work. We don't really need 100 people telling us "+1" or that it doesn't work in the current version. We know it doesn't. Expect it to continue not working until this issue is closed.

**Comment by Milly** [comment]
Because there are too many duplicate issues,
How about changing the title like this?
`CJK IME doesn't work (Chinese, Japanese, Korean, Emoji, etc)`

**Comment by wizcas** [comment]
Same problem with additional details:

- The shortcut for switching IME in a certain language `Ctrl + Shift`  **won't work**.
- The shortcut for switching between languages `Alt + Shift` *DO* work.
- The shortcut for switching between Chinese/English in Microsoft Pinyin `Shift` **won't work**
- Can't input Chinese even I manually clicked the language icon in the taskbar 
![image](https://user-images.githubusercontent.com/2867434/67156939-9d672e00-f357-11e9-889c-fad6c9656c42.png)

Windows Terminal (Preview)
Version: 0.5.2762.0

**Comment by NDelt** [comment]
I think this issue should be resolved with #2664.

**Comment by z1900** [comment]
Windows Terminal (Preview) Version: 0.5.2762.0 Get from Microsoft Store
Same problem

**Comment by ruiyong-lee** [comment]
It’s been a long time

**Comment by chuanjiao10** [comment]
1 不能输入，但可以粘贴中文。emojs等。
2 可以用alt键+unicode码输入中文。emojs等。如：按住alt，再按小键盘的45678。

**Comment by hez2010** [comment]
A temporary workaround:
you can input the characters in notepad, and then copy&paste them into the terminal :)

**Comment by ybj14** [comment]
+1

**Comment by QingYuan-L** [comment]
waiting for fixing the problem

**Comment by tats-u** [comment]
This is one main reason why I keep using https://hyper.is/

**Comment by transtone** [comment]
> This is one main reason why I keep using https://hyper.is/

powershell with `sarasa term` is good.

**Comment by merfais** [comment]
same at 0.6.2951.0

**Comment by qqkookie** [comment]
Please pay attention to related feature request to CJK input and IME use, too.

#1304 : Feature Request: IME mode switching after pressing Escape or Enter key in CJK input

In short, automatic switching from CJK input IME mode to alpha mode after Escape key press.

**Comment by Green1ee** [comment]
OS Version: 10.0.18362 Build 18362
Windows Terminal (Preview)
**Version: 0.6.2951.0**
Get from Microsoft Store

Same problem

**Comment by cmsax** [comment]
Bug still there...

- os: `1903 18326.476`
- terminal ver: `0.6.2951.0`

Even vscode integrated terminal window works better than current Windows `new` terminal.

**Comment by NextStack** [comment]
os: 19013
terminal version: 0.6.2951.0

Same problem

**Comment by leadscloud** [comment]
同样的问题，这bug这两天还有人一直提问题，我记得这软件出来好久了
os: win10 1909 18363.476
terminal version: 0.6.2951.0

**Comment by namewalt** [comment]
无法使用任何输入法,更不能输入中文

**Comment by dbwodlf3** [comment]
why closed? it is still a problem!

**Comment by hez2010** [comment]
> why closed? it is still a problem!

It has been fixed but the newer build hasn't shipped to Windows Store yet.

**Comment by sidian123** [comment]
same question, why closed ? i encounter the same problem, cannot input chinese character

**Comment by hez2010** [comment]
It has been fixed, but the build was not shipped to Windows Store yet.

________________________________

**Comment by dbwodlf3** [comment]
aha.. okay. thanks reply.

**Comment by dbwodlf3** [comment]
> It has been fixed, but the build was not shipped to Windows Store yet.
> […](#)
> ________________________________ From: JaeIL Ryu <notifications@github.com> Sent: Saturday, November 23, 2019, 9:57 PM To: microsoft/terminal Cc: Steve; Comment Subject: Re: [microsoft/terminal] All IME's don't work (Chinese/Japanese/Korean input, Emoji Picker, etc.) (#2213) why closed? it is still a problem! — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fterminal%2Fissues%2F2213%3Femail_source%3Dnotifications%26email_token%3DADSENWPTGVW2JGDZV3Y632TQVEZFNA5CNFSM4IJCU4O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7VUGA%23issuecomment-557799960&data=02%7C01%7C%7Cde980989948f43e35f4308d7701d1c9d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637101142639359378&sdata=qtmJq%2BBECemtWl8Ksb0idxXrQx88wOoFK%2Bz2t4KI2N8%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSENWMBAWWB66QQT2LMVOTQVEZFNANCNFSM4IJCU4OQ&data=02%7C01%7C%7Cde980989948f43e35f4308d7701d1c9d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637101142639369387&sdata=9tSccOqF5UQ%2FUydAIbmqPiqcAk90ToBH1g9494B8wVc%3D&reserved=0>. Get Outlook for Android<https://aka.ms/ghei36>

aha.. okay. thanks reply.

**Comment by Green1ee** [comment]
When can i get the newer from Windows Store.

**Comment by DHowett-MSFT** [comment]
You can get the newer version when it is released.

**Comment by Green1ee** [comment]
> You can get the newer version when it is released.

ha,so when?

**Comment by LaTristan** [comment]
Though it can print Chinese and Japanese(maybe), there's something different from what Chinese and Japanese uses today.

**Comment by JushBJJ** [comment]
@Green1ee 30th of November. Only a few days left!

**Comment by luochen1990** [comment]
I updated and it works well, hooray!

**Comment by seonk** [comment]
Upgraded, Chinese input method can be used, but the continuous input of several sentences is 100% crashed. Is it a bug or a problem with my computer settings? (using Google Translate)

**Comment by seonk** [comment]
Reset the app and the problem persists. The Chinese input method has been changed to Microsoft Pinyin, and it has not crashed so far. However, to input punctuation marks, you need to double-click consecutively to input correctly. No symbol is displayed when you click it. (Still using Google Translate)

**Comment by zhoupro** [comment]
I update it, It crash 100%.

**Comment by foriequal0** [comment]
Korean input also doesn't work for https://github.com/microsoft/terminal/releases/tag/v0.8.10261.0
For example, If I type "한글이 안돼" (It messes up Korean doesn't work), with 2-beolsik  Microsoft IME,
It normally shown as these sequences in the screen (A character with _ means it is in the composition, `v` means space bar)
```
ㅎ_
하_
한_
한ㄱ_
한그_
한글_
한글ㅇ_
한글이_
한글이v
한글이 ㅁ_
한글이 마_
한글이 망_
한글이 망ㄱ_
한글이 망가_
한글이 망갖_ # Notorious 2-beolsik phantom character phenomenon. Koreans are used to this. This is not a problem.
한글이 망가져_
한글이 망가져v
한글이 망가져 ㅇ_
한글이 망가져 아_
한글이 망가져 안_
한글이 망가져 안ㄷ_
한글이 망가져 안도_ # Some middle vowel characters are also composed themselves, not only consonants and vowels(가), and vowels(않).
한글이 망가져 안돼_
한글이 망가져 안돼v
```

However, in Terminal,
```
ㅎ_
하_
한_ # works well for the first character after the ascii charcter
한ㄱ_
한그ㄱ # Weird things starts. compositioning cursor disappears
한그ㄱ글_ # reappear cursor
한그ㄱ글ㅇ_
한그ㄱ글이ㅇ
한그ㄱ글이ㅇ이_
한그ㄱ글이ㅇ이v
한그ㄱ글이ㅇ이 ㅁ_
한그ㄱ글이ㅇ이 마_
한그ㄱ글이ㅇ이 망_
한그ㄱ글이ㅇ이 망ㄱ_ 
한그ㄱ글이ㅇ이 망가ㄱ # again
한그ㄱ글이ㅇ이 망가ㄱ갖_ # reappear
한그ㄱ글이ㅇ이 망가ㄱ가져_ # sometimes 가 and 져 is overlayed in the same place.
한그ㄱ글이ㅇ이 망가ㄱ가져져v # sometimes 가 and 져 is overlayed in the same place.
한그ㄱ글이ㅇ이 망가ㄱ가져져 ㅇ_
한그ㄱ글이ㅇ이 망가ㄱ가져져 아_
한그ㄱ글이ㅇ이 망가ㄱ가져져 안_
한그ㄱ글이ㅇ이 망가ㄱ가져져 안ㄷ_
한그ㄱ글이ㅇ이 망가ㄱ가져져 안도 # again
한그ㄱ글이ㅇ이 망가ㄱ가져져 안도ㄷ_ # reappear
한그ㄱ글이ㅇ이 망가ㄱ가져져 안도ㄷ돼_
한그ㄱ글이ㅇ이 망가ㄱ가져져 안도ㄷ돼v
```

**Comment by simnalamburt** [comment]
@foriequal0 That issue is currently being tracked in https://github.com/microsoft/terminal/issues/4226
