### ISSUE TITLE
Prerequisite for an install could not be satisfied

### ISSUE THREAD

**Issue by RUSshy** [microsoft/terminal#2214]
I tried to download and install the package in the release page but i get the following error:

![image](https://user-images.githubusercontent.com/18348637/62410454-cfcd7e80-b5e5-11e9-8c1c-63194a936cb6.png)

Version: https://github.com/microsoft/terminal/releases/tag/v0.3.2142.0

**Comment by RUSshy** [comment]
And btw, that package thing is really bad

- error message non helpful AT ALL, at least in macOS i could check the log using a dedicated program

- just an Install button, i guess to way to tell where to install it (diferent drive for example), at least in macOS i can choose the disk target

If copy macOS please do it right, not the broken linux way

**Comment by TayYuanGeng** [comment]
Do note that you need a Windows 10 version 18362 otherwise the windows terminal may not be able to support.

**Comment by RUSshy** [comment]
Oh looks like i have: Microsoft Windows [Version 10.0.17763.557]
My bad!

**Comment by RUSshy** [comment]
Suggestion:

On that installation screen, requirments should be listed, otherwise you leave user in the smoke... this is part of bad UX on windows

**Comment by TayYuanGeng** [comment]
![image](https://user-images.githubusercontent.com/50003738/62412792-c40ba780-b639-11e9-9cdb-112e33a82fd4.png)
It's actually stated in the Microsoft Store, I guess it wasn't visible after all!

**Comment by RUSshy** [comment]
UX is bad, there is no color other than (white/black/blue) wtf

Wrong version message should be more VISIBLE than anything else, this is the main problem, but it is displayed like a normal text..

**Comment by TayYuanGeng** [comment]
Ermm I set my laptop to dark mode....

**Comment by zadjii-msft** [comment]
@bitcrazed Can you follow up with the Store team and/or the ADEX/APT/whatever-their-acronym-is-now team on this? There's two main things that need polish here:
1. If you're trying to install and app from the store and don't have a high enough Windows version installed, that's not clearly highlighted enough. _This should go to the store team_
2. If you're trying to sideload a package and don't have a high enough Windows version installed, the error message is not clear enough (when it definitely could be). _This should go to the ADEX team_
