### ISSUE TITLE
Feature Request: Rearrangeable Tabs

### ISSUE THREAD

**Issue by Pantastisch** [microsoft/terminal#2215]
# Description of the new feature/enhancement
Rearrangeable tabs would be a great feature. Especially when someone is working on multiple machines as me. This helps organizing machines in tabs, when they are started in different times.

Simple example:
![image](https://user-images.githubusercontent.com/45369229/62411778-bbdf4800-b5f8-11e9-8dad-a9038ee55f26.png)

Thanks!

**Comment by DHowett-MSFT** [comment]
#443.
