### ISSUE TITLE
Feature Request: Allow tab title to be set by console apps

### ISSUE THREAD

**Issue by mbreaton** [microsoft/terminal#2218]
### Add support for console apps that attempt to set their window title:

**cmd** => `title "Title"`
**pwsh** => `$host.ui.RawUI.WindowTitle = "title"`
**bash** => `export PS1=`

This works in current shells and is useful for allowing long running scripts to display a current action message before executing a block of long running commands that emit a lot of superfluous console output (compiler output, file copies, etc) and would reduce switching back and forth to a tab just to view its progress

```
$host.ui.RawUI.WindowTitle = "compile..."
# build command
$host.ui.RawUI.WindowTitle = "containerize..."
# docker build
$host.ui.RawUI.WindowTitle = "deploy..."
# docker push
```

**Comment by DHowett-MSFT** [comment]
... have you tried this? It works.

**Comment by DHowett-MSFT** [comment]
If you are setting a `tabTitle` that will, by design, override whatever the shell says.

**Comment by mbreaton** [comment]
Yes, I have tabTitle set. Would it not make more sense to be able to override that via running scripts?

**Comment by zadjii-msft** [comment]
See, the problem with that is the path that you're already seeing without setting `tabTitle` is a title that's emitted by the shell. So you can't really have it both ways, where the `tabTitle` overrides the thing set by the shell, and the shell is able to override the `tabTitle`.

**Comment by mbreaton** [comment]
Understood, thanks for the clarification
