### ISSUE TITLE
Feature Request: Option to only allow one instance

### ISSUE THREAD

**Issue by Johannestegner** [microsoft/terminal#2227]
# Description of the new feature/enhancement

When I work in the terminal (currently mainly CMDer/ConEmu) I like to keep one terminal going with multiple tabs.  
When opening a new terminal window, my terminal does not create a new instance of the application but rather opens a new tab in the currently running instance.

Best approach would probably be to make it an option, I.E., not forcing the functionality on people, but rather have it toggle-able for people like me!

# Proposed technical implementation details (optional)

Open a terminal while there is a terminal already running opens the running terminal application and creates a new terminal tab, alt. opens the terminal and allows the user to open a new tab manually.

_(Love the terminal, it's really neat!)_

**Comment by zadjii-msft** [comment]
I think this is a reasonable feature request. It definitely plays off a lot of the things @miniksa was looking at for #2080. While it might not be in the roadmap for 1.0, I think this is definitely something we'd like to see at some point.

**Comment by DHowett-MSFT** [comment]
Triage: backlogged, needs a spec, but MIGHT be handled by a comprehensive look at #2080.
