### ISSUE TITLE
Crash after closing an Azure tab and entering something in default PowerShell tab

### ISSUE THREAD

**Issue by hangvane** [microsoft/terminal#2230]
# Environment

```none
Windows build number: version 10.0.18362.239
Windows Terminal version (if applicable):0.3.2142.0 from Microsoft Store 
```

# Steps to reproduce

1. Fresh install of Terminal from Microsoft Store
2. Try to open the default Azure Cloud Shell tab and close the tab without login
3. Enter something in default PowerShell and press Enter, for example, type "abc" and press Enter

# Expected behavior

Displays the return value or error information of the command 

# Actual behavior

Crash

**Comment by TayYuanGeng** [comment]
Do you have a screenshot of the actual behaviour as the reported issue is too brief.

**Comment by hangvane** [comment]
> Do you have a screenshot of the actual behaviour as the reported issue is too brief.
sure
1.open the terminal
![1](https://user-images.githubusercontent.com/22473909/62445028-dbf63f00-b791-11e9-9564-bf98e6d42514.jpg)
2. open the azure tab
![2](https://user-images.githubusercontent.com/22473909/62445052-ec0e1e80-b791-11e9-8bd7-6a78e9e287bb.jpg)
3. close the azure tab
![3](https://user-images.githubusercontent.com/22473909/62445139-211a7100-b792-11e9-9ec5-8eee0815d421.jpg)
4. type "a" in default powershell tab
![4](https://user-images.githubusercontent.com/22473909/62445179-3d1e1280-b792-11e9-9b90-41a2a9fc4d52.jpg)
5. the terminal disappeared after i pressing enter without any error message

**Comment by zadjii-msft** [comment]
I'm pretty sure @miniksa was investigating some other crashes that looked a lot like this.

**Comment by miniksa** [comment]
@hangvane, can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?

![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png)
![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

Thanks!

**Comment by DHowett-MSFT** [comment]
I think i've seen this as well. I'll go digging for cabs on my machine.

**Comment by hangvane** [comment]
> @hangvane, can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?
> 
> ![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png)
> ![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)
> 
> Thanks!

https://aka.ms/AA5roiw

**Comment by zadjii-msft** [comment]
This is more likely #2375 but maybe also #2525

**Comment by DHowett-MSFT** [comment]
I think both of the bugs that could have been this are now fixed. Please let me know if it still reproduces!
