### ISSUE TITLE
Reports that terminal can't launch applications marked [Run as Administrator]

### ISSUE THREAD

**Issue by braithair** [microsoft/terminal#2233]
# Description of the new feature/enhancement

## Descriptor
I had an issue where my Windows Terminal was consistently crashing and had a lot of frustration on my personal part) trying to self resolve the issue.

## Problem
Long story short, I had a the same issue as a few other people "My terminal opens and then closed at launch with very little information"

## Solution
It was simple in the end - I have Powershell Core 7 preview installed and the "pwsh.exe" file was set to "Run as Administrator". I removed the "Run as Administrator" for the pwsh.exe and boom, problem instantly solved and the terminal now opens when i just run it.

# Proposed technical implementation details (optional)

The solution options I thought of were:

1. Warn the user on install that their shells are in "Run as administrator" mode, and they will have to run the terminal as administrator to facilitate this setting.
2. Warn the user that the administrator setting is active for the shell as above, and offer to change this setting.
2. Allow the App to be permanently run as administrator, if this is relevant for the user (I don't see this as the optimal solution)

I hope this is a relevant place to put this request. Thanks Microsoft team for creating and enhancing a product that has long needed some love and attention. With Windows Terminal, I see a springboard of future opportunities to make it a powerful tool!

**Comment by DHowett-MSFT** [comment]
(1) seems like a real bug -- we should be able to activate shells marked "run as administrator." (3) will be #1032

**Comment by zadjii-msft** [comment]
@miniksa Might also be interested, I think he had a collection of issues that this might be relevant for

**Comment by braithair** [comment]
Thanks for your awesome work @DHowett -- True Hero dude!

**Comment by DHowett-MSFT** [comment]
Unfortunately, this is just going to have to be by design. We can't force the OS to launch an application at a privilege level higher than us, and this'll need some treatment similar to #1032. With the recent `closeOnExit` changes, you will at least get an error message instead of a terminal that instantly tastes clay.

**Comment by DHowett-MSFT** [comment]
Thanks!
