### ISSUE TITLE
ALT+'ASCII number' generate repeterad characters

### ISSUE THREAD

**Issue by magol** [microsoft/terminal#2236]
# Environment
Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version 0.3.2142.0

# Steps to reproduce
Press `ALT + 0192`

# Expected behavior

One `°` should be written in the console

# Actual behavior
`°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°` is written to the console

**Comment by encladeus** [comment]
This seems to be a duplicate of the issue already reported in #657.

**Comment by DHowett-MSFT** [comment]
It is! Thanks.
