### ISSUE TITLE
Not possible to paste multiline commands in WSL

### ISSUE THREAD

**Issue by chkt** [microsoft/terminal#2240]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.3.2142.0
WSL Ubuntu 18.04.2 LTS
```

# Steps to reproduce

1. Open WSL Terminal
2. Copy a multiline escaped command like below to clipboard
```sh
test -f \
~/.bashrc
```
3. Paste clipboard into open Terminal window using right-click.

# Expected behavior

The terminal should print
```sh
$ test -f \
> ~/.bashrc
```
and wait for further input

# Actual behavior

The first line is run and the second put in a new prompt afterwards. The second prompt is awaiting further input.
```sh
$ test -f \
>
$ ~/.bashrc
```

**Comment by DHowett-MSFT** [comment]
This is a manifestation of #1454
