### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NIRVANALAN** [microsoft/terminal#2242]
# Description of the new feature/enhancement

Hi, I have been using this Terminal for a while and find it impressive. But I have one question/feature request here, I use WSL in my daily work and the new tab is Powershell by default when I open the Terminal or create a new tab(ctrl+shift+t)... Is there a way to set my default tab?
# Proposed technical implementation details (optional)

In settings.json adds default tab entry I think..

**Comment by DHowett-MSFT** [comment]
It’s called `defaultProfile`...

**Comment by NIRVANALAN** [comment]
Sorry sir ..
