### ISSUE TITLE
UTF-8 line-drawing characters do not render correctly in Terminal vs. console

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#2243]
(This may well be a duplicate, but I didn't find a specific duplicate and I'm not clueful enough to figure out if it's included in any of the others.)

# Environment

```none
Windows build number: 10.0.18945.1001
Windows Terminal version (if applicable): 0.3.2142.0

Any other software?

Reproduced using Debian Buster; also, font in use in both Terminal and console is Consolas.
```

# Steps to reproduce

1. Ensure that you are configured to use the UTF-8 locale and UTF-8 codeset; i.e., that the output of the `locale` command is as follows:

```
LANG=en_US.UTF-8                                                                                                                                            LANGUAGE=en_US.UTF-8                                                                                                                                        LC_CTYPE="en_US.UTF-8"                                                                                                                                      LC_NUMERIC="en_US.UTF-8"                                                                                                                                    LC_TIME="en_US.UTF-8"                                                                                                                                       LC_COLLATE="en_US.UTF-8"                                                                                                                                    LC_MONETARY="en_US.UTF-8"                                                                                                                                   LC_MESSAGES="en_US.UTF-8"                                                                                                                                   LC_PAPER="en_US.UTF-8"                                                                                                                                      LC_NAME="en_US.UTF-8"                                                                                                                                       LC_ADDRESS="en_US.UTF-8"                                                                                                                                    LC_TELEPHONE="en_US.UTF-8"                                                                                                                                  LC_MEASUREMENT="en_US.UTF-8"                                                                                                                                LC_IDENTIFICATION="en_US.UTF-8"                                                                                                                             LC_ALL=en_US.UTF-8 
```

2. Run `pstree`, or another command which detects and uses UTF-8 line-drawing characters.

Note that this is not the default configuration of Debian for the en_US.UTF-8 locale, which leaves LC_ALL set to C; `sudo update-locale LC_ALL=en_US.UTF-8` is required.

# Expected behavior
# Actual behavior

Expected behavior is line-drawing characters, as seen in console on the right. Actual behavior is all such characters rendering as "underline", as seen in Terminal on the left.

![bad-linedrawing](https://user-images.githubusercontent.com/371623/62431251-72235a00-b6eb-11e9-9d7f-77682dbd8fcb.jpg)

**Comment by DHowett-MSFT** [comment]
It looks like this is in tmux or screen. Can you share the value of `$TERM` inside and outside your multiplexer?

**Comment by cerebrate** [comment]
Outside, it’s xterm-256color. Inside, it’s screen-256color. 

I should add, though, that I also thought it might be tmux-related, so I tried the same experiment without it running. Same results.

**Comment by zadjii-msft** [comment]
@cerebrate What font are you using? Is `en-us.UTF-8` important? I'm working with `C.UTF-8` over here, and that seems just fine.

Curiously also, in the conhost.exe window on the right, you have `LANG=C.UTF-8`.

**Comment by DHowett-MSFT** [comment]
Hm. Can you run

```
pstree -G
pstree -A
pstree -U
```

in both conhost and Terminal?

**Comment by cerebrate** [comment]
@zadjii-msft Consolas.

And I'm using `en-US.UTF-8` rather than `C.UTF-8` primarily for collation reasons; I do a fair amount of work with non-ASCII characters, which `en-US.UTF-8` sorts correctly and `C.UTF-8` does not.

**Comment by cerebrate** [comment]
@DHowett-MSFT Well, this is awkward.

Since reporting this issue yesterday, and without me intentionally changing anything (font, locale, etc.), it is now working - i.e., rendering with line-drawing characters in Terminal, as well as in conhost. Behavior on running the three commands in either is as expected: -G and -U render with line-drawing characters, -A with ASCII art, and no underlines are to be seen.

And so far, I can't seem to break it again. Gah. I _hate_ heisenbugs.

Leaving this open for now, and I'll try tomorrow to repro it on another machine still running on installation defaults.

**Comment by nicm** [comment]
tmux will draw all UTF-8 characters as underscores if it thinks the terminal does not support UTF-8, perhaps that is the case here. Are you sure at least one of LANG, LC_ALL or LC_CTYPE is set correctly *outside* tmux? You can also use -u to tell tmux explicitly that the terminal supports UTF-8.

**Comment by DHowett-MSFT** [comment]
I'll close this one out in light of "tmux ... underscores ...". Thanks!

**Comment by cerebrate** [comment]
@nicm Trouble is, the same thing was happening outside tmux, per comment above: https://github.com/microsoft/terminal/issues/2243#issuecomment-518049785 ; just bypassing all my normal .zprofile / .zcshrc and starting up in bash alone.

On the other hand, since I can't get the issue to reproduce, yeah, might as well go ahead and close it/leave it closed.

**Comment by iamkentleom** [comment]
I had the same issue. Probably there's something wrong with the rendering/screen because I've tried making the font bigger and everything came back to normal. Probably the font is small enough that the rendered line can't be seen.

**Comment by DHowett** [comment]
Curious! @ivho what's the output of `locale`?

**Comment by DHowett** [comment]
I suspect that the missing `.UTF-8` on `LANG` (and perhaps the empty `LC_ALL`?) are contributing to tmux's decision to remove the UTF-8 characters from its output. :smile:
