### ISSUE TITLE
Title bar color does not change when changing dark/light mode in Windows Settings app

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#2246]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
@nitishvijai please be aware that you can EDIT bugs once you’ve filed them, so you don’t need to close them and make new ones when you forgot to put something in.
