### ISSUE TITLE
Azure Cloud Shell Connector Not Working

### ISSUE THREAD

**Issue by rkttu-devsisters** [microsoft/terminal#2249]
# Environment

```none
Windows build number: 10.0.18950.1000
Windows Terminal version (if applicable): 0.3.2142.0 (from Microsoft Store)

Any other software?
Not a software, but I'm using GitHub authentication with Microsoft Account.
```

# Steps to reproduce

I tried to use Azure CloudShell Connector, but the connector shows an error message like below.

<img width="737" alt="issue" src="https://user-images.githubusercontent.com/35712113/62438852-4a340500-b784-11e9-8ba3-954ae121b17e.png">

# Expected behavior

I think it should work normally.

# Actual behavior

I captured traffic with Fiddler4. The OAUTH API returns 400 error code like below. The API says `AADSTS70016: Pending end-user authorization.`. I don't know what causes the error after authentication is complete, but authentication fails as shown in the attached screenshot. 

If there are any conditions or circumstances that prevent the device from logging in, it may be necessary to provide guidance on how to respond appropriately.

Request

```
POST https://login.microsoftonline.com/common/oauth2/token HTTP/1.1
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded; charset=utf-8
User-Agent: cpprestsdk/2.10.13
Content-Length: 328
Host: login.microsoftonline.com
Cookie: stsservicecookie=ests; x-ms-gateway-slice=prod; fpc=...

grant_type=device_code&resource=https://management.core.windows.net/&client_id=...&code=...
```

Response:

```
{"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 020679d0-f785-40be-b55c-b6dfa9029500\r\nCorrelation ID: 2de85d18-59f3-44b5-8e91-aa9ada0412b8\r\nTimestamp: 2019-08-05 04:19:27Z","error_codes":[70016],"timestamp":"2019-08-05 04:19:27Z","trace_id":"020679d0-f785-40be-b55c-b6dfa9029500","correlation_id":"2de85d18-59f3-44b5-8e91-aa9ada0412b8"}
```

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the report. Are you able to use the shell through [the official portal](https://shell.azure.com)?

**Comment by rkttu-devsisters** [comment]
Yes. It's possible to use. However, only the second item displayed on the screen is available. I've added this account as a manager in closed subscriptions. Only the second item on the screen is currently available, and everything else is unavailable.

![image](https://user-images.githubusercontent.com/35712113/62461903-0ad7d980-b7c1-11e9-9d71-25f5f41e288b.png)

**Comment by DHowett-MSFT** [comment]
Interesting. We'll need to add some better logging here, because nobody on our team has enough tenants to try this out.

**Comment by revpixel** [comment]
![image](https://user-images.githubusercontent.com/21064412/62717111-4ba63d00-b9d1-11e9-8ca8-a5af6d7840f5.png)

Getting the same from my Windows 10 Insider box.

**Comment by DHowett-MSFT** [comment]
Nobody here has been able to reproduce this, which is very dismaying. Sorry.

**Comment by rkttu-devsisters** [comment]
@DHowett-MSFT // If necessary, I would get a debug build and test it. How can I assist you?

**Comment by revpixel** [comment]
> Nobody here has been able to reproduce this, which is very dismaying. Sorry.

Hit me up internally :) I can repro it all the time on my corp laptop using my personal Azure account. I'm on teams :)

**Comment by revpixel** [comment]
Here is an interesting issue update. While I'm trying to get the debug buuld to run I did try and load this one more time using my CORP Credentials instead of my personal MSDN Account and it worked. I'm starting to this this is a MFA issue.

![image](https://user-images.githubusercontent.com/21064412/63435207-7ee6c400-c3f4-11e9-8167-45c977825225.png)

**Comment by revpixel** [comment]
Trying that premise I used an InPrivate Window which did resend my MFA request to my personal MSDN Account but it still did not connect to my account 

![image](https://user-images.githubusercontent.com/21064412/63435458-ed2b8680-c3f4-11e9-9613-8449e518be16.png)

**Comment by revpixel** [comment]
Here is an interesting issue update. While I'm trying to get the debug buuld to run I did try and load this one more time using my CORP Credentials instead of my personal MSDN Account and it worked. I'm starting to this this is a MFA issue.

Trying that premise I used an InPrivate Window which did resend my MFA request to my personal MSDN Account but it still did not connect to my account
