### ISSUE TITLE
`startingDirectory` prevent terminal from opening in the current directory

### ISSUE THREAD

**Issue by chungweileong94** [microsoft/terminal#2250]
# Environment

```none
Windows build number: 18362.267
Windows Terminal version: 0.3.2142.0
```

# Steps to reproduce

1. Open a directory in explorer.exe
2. Type 'wt' in the search bar to launch the terminal

# Expected behavior

The terminal starting directory should be the same as the directory in explorer.exe.

# Actual behavior

The terminal starting directory always use the `startingDirectory` value in the settings instead of the current directory.

**Comment by zadjii-msft** [comment]
This is basically #878, with a touch of #607
