### ISSUE TITLE
Terminal crashes when scrolling text under certain scenarios

### ISSUE THREAD

**Issue by markSmurphy** [microsoft/terminal#2251]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version: 0.3.2142.0
Any other software:
* Powershell6
* Windows Subsystem for Linux - Ubuntu

```

# Steps to reproduce

* Open Windows Terminal with `cmd.exe` as the default profile .
* Open a new terminal tab hosting `pwsh.exe` or `WSL Ubuntu`
* Type `exit` to close the new tab
* Back in the `cmd.exe` tab, `type` a reasonably sized text file to the console.  (_Mine was a 59,219 byte csv file_)

# Expected behavior

The terminal console should scroll through the text file.
# Actual behavior

**Terminal** crashes with no error message.
The **Windows Problem Report** lists the following detail:
```none
Description
Faulting Application Path:	C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe
Application Name:	praid:App
Application Version:	1.0.1908.2002
Application Timestamp:	5d448424
Fault Module Name:	TerminalControl.dll
Fault Module Version:	1.0.1908.2002
Fault Module Timestamp:	5d448318
Exception Code:	c0000005
Exception Offset:	0000000000018abb
OS Version:	10.0.18362.2.0.0.768.101
Locale ID:	2057
Additional Information 1:	17fc
Additional Information 2:	17fc9f89663473fc7bed7d821c616059
Additional Information 3:	df83
Additional Information 4:	df83cd4f4def141c4bbf7772ff64cc94
```

**Comment by zadjii-msft** [comment]
@markSmurphy , can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?

![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png)
![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

Thanks!

**Comment by markSmurphy** [comment]
> 
> 
> @markSmurphy , can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?
> 
> ![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png)
> ![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)
> 
> Thanks!

Hopefully, this is what you need:
https://aka.ms/AA5s8ub

**Comment by DHowett-MSFT** [comment]
I'm gonna close this one out since we haven't seen a repro in a while. Let me know.
Thanks!
