### ISSUE TITLE
Clicking on the TitleBar does not close the dropdown menu

### ISSUE THREAD

**Issue by danielgary** [microsoft/terminal#2252]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18950.1000]
Windows Terminal version (if applicable):0.3.2142.0
```

# Steps to reproduce

Open the drop-down menu
Click on the TitleBar

# Expected behavior

Expect the drop-down menu to close since it has lost focus

# Actual behavior

The drop-down menu stays open

**Comment by zadjii-msft** [comment]
This is a good bug report. I'll make sure to track this as part of #1625.

**Comment by DHowett-MSFT** [comment]
This is #2028.

**Comment by danielgary** [comment]
Sorry, I searched but didn't see it.
