### ISSUE TITLE
opening the prompt as admin

### ISSUE THREAD

**Issue by austinmarner** [microsoft/terminal#2255]
windows terminal looks good so far, but please add function to open the ps, wsl, cmd sessions as admin as well as root for wsl inside the windows terminal after opening it 

and also it displays the full path of the respective session in the tab change it too

**Comment by zadjii-msft** [comment]
1. Please search before filing issues. There's a bunch of issues for "it displays the full path of the respective session in the tab change it too", #608 is the primary, and also tracking this is a bucket of stuff in #1375.
1. Please don't file more than one problem per issue, it makes it _really_ hard for us to track issues and resolve them. 
1. "add function to open the ps, wsl, cmd sessions as admin as well as root for wsl inside the windows terminal after opening it" is already #1032 #691 #632 #2200 #146
