### ISSUE TITLE
Lucida Console can not fallback to display CJK characters after updating to 1803

### ISSUE THREAD

**Issue by toshichi** [microsoft/terminal#226]
* Windows build number:  Version 10.0.17134.165

* What you're doing and what's happening: 
**Under chcp 65001 (UTF-8)**
the Lucida Console font in cmd is unable to display Chinese Japanese and Korean characters after updating to 1803 version in semi-year channel:
![image](https://user-images.githubusercontent.com/5460009/43044988-95cd69f6-8de2-11e8-9d17-4fd0c1031ee0.png)

* What's wrong / what should be happening instead:
Under MS-Mincho it works fine (but the font is ugly):
![image](https://user-images.githubusercontent.com/5460009/43044984-8b47f280-8de2-11e8-948d-5eb4694ae35a.png)
  
and under version 1709 (build 10.0.16299.492) it also worked fine:
![image](https://user-images.githubusercontent.com/5460009/43044993-aa3ce7cc-8de2-11e8-979e-a67347eeca13.png)

I have different computers set in English, Japanese and Chinese language, they all behaved the same. Maybe I'll have to change some setting in the registry?

**Comment by amasover** [comment]
I am seeing the same behavior on Windows 1803. I'm using the NSimSun font for now, as it looks much better than MS-Mincho. My system locale and display language are both set to English (United States). In control panel -> region -> administrative -> change system locale I tried checking the box "Beta: Use Unicode UTF-8 for worldwide language support" but that did nothing.

**Comment by bitcrazed** [comment]
This ask is specifically tagged against the Console and is largely resolved by @miniksa's new renderer, though that renderer won't be on by default in Console prior to 21H1 release (at the earliest).

Let's revisit for 21H1

**Comment by lhecker** [comment]
I just found this issue by pure chance. This can be closed now that the duplicate issue #10472 has been fixed.
