### ISSUE TITLE
WSL Ubuntu clear -x partially clears scrollback

### ISSUE THREAD

**Issue by RyanHope97** [microsoft/terminal#2260]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): 0.3.2142.0
WSL 1 with Ubuntu 18.04
```

# Steps to reproduce

1. Open terminal with WSL Ubuntu
2. Display something on stdout (e.g. `echo Hello world!`)
3. Run `clear -x` or `Ctrl+L`

# Expected behavior

Move promt to top of the screen and put what is currently dispalyed on the screen in the scrollback. This is how the old console functioned.

# Actual behavior

Moves promt to top of the screen, and clears what is currently displayed on the screen without putting it in the scrollback

**Comment by zadjii-msft** [comment]
There's a 50-70% chance there's already a dupe for this issue but I'll leave it open to make sure

**Comment by RyanHope97** [comment]
@zadjii-msft > There's a 50-70% chance there's already a dupe for this issue but I'll leave it open to make sure

I had a quick look but couldn't find anything, but I could be blind 😊
