### ISSUE TITLE
Trackpad scroll not working

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2263]
# Environment

```none
Windows build number: Version 10.0.18362.239
Windows Terminal version (if applicable): 0.3.2142.0
```

# Steps to reproduce

1. Open terminal (e.g. with Ubuntu as the shell)
2. Run some command that produces output that extends beyond bottom of window (e.g. `ls -al` on a directory with lots of files in it)
3. Two-finger scroll with the trackpad through the output

# Expected behavior

The windows scrolls so you can see all output

# Actual behavior

Nothing happens

**Comment by DHowett-MSFT** [comment]
This sounds like #979.
