### ISSUE TITLE
Maximizing terminal when window is across two monitors causes bars to bleed across monitor.

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2268]
Maximizing terminal when window is across two monitors causes bars to bleed across monitor.
![multimonitor](https://user-images.githubusercontent.com/3235846/62490241-2f37b400-b7c9-11e9-9a42-152760e56628.gif)

_Originally posted by @rjfmachado in https://github.com/microsoft/terminal/issues/1375#issuecomment-518370430_

**Comment by DHowett-MSFT** [comment]
This was also fixed by #3394.
