### ISSUE TITLE
Norwegian keyboard: Several characters not possible to write in fresh install (Key combinations)

### ISSUE THREAD

**Issue by dennorske** [microsoft/terminal#2270]
# Environment

```none
Windows build number: [Version 10.0.18362.239]
Windows Terminal version (if applicable):  0.3.2142.0

Any other software?
```

# Steps to reproduce

Pressing AltGR + 2/3/4/7/8/9/0/+ (number row) - and possibly other key combinations requiring AltGR does not seem to bite on the terminal. For instance, getting the "at" sign "@", we usually press AltGR+2 or CTRL+ALT+2 to write it, but terminal does not recognise both of these ways.

# Expected behavior

I was hoping to print out special letters very often needed in the terminal.

# Actual behavior

Nothing happens, nothing shows up, not even prints of weird character codes. Just no response.

**Comment by DHowett-MSFT** [comment]
#521
