### ISSUE TITLE
Interactive performance is horrible after displaying a full screen image with viu

### ISSUE THREAD

**Issue by jeichorn** [microsoft/terminal#2274]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version 0.3.2142.0
Testing using wsl 1.0,  Ubuntu 18.04.2 LTS
viu 0.2.1 https://crates.io/crates/viu
```

# Steps to reproduce

Install viu, and display an image big enough to be full screen
`cargo install viu`
`viu /mnt/c/.../image.jpg`

type

# Expected behavior

No performance drop

# Actual behavior
Typing performance will be horrible until the image has been scrolled off the screen.  Bad enough that typing will have 1 second of lag.

**Comment by DHowett-MSFT** [comment]
Probably two issues here. One is #778, one is #1064. Also, we're probably reserializing the entire buffer over conpty again and again. Sometimes it happens.
