### ISSUE TITLE
BUG: Text Encoding issues (backgroundImage path, tabTitle)

### ISSUE THREAD

**Issue by kfarmer-msft** [microsoft/terminal#2276]
# Environment

```none
Windows build number: 
Microsoft Windows [Version 10.0.18362.267]

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.3.2142.0

Any other software?
VS 2019, latest build
```

# Steps to reproduce

These profile settings cause the specified background image to display.  Each of these images is viewable via File Explorer and in use as desktop background images.

      "backgroundImage": "C:\\Users\\kfarm\\OneDrive\\Backgrounds\\Characters (Landscape)\\Oddr [Vizsla] - desktop.png",
      "backgroundImageAlignment": "bottomRight",
      "backgroundImageOpacity": 0.5,
      "backgroundImagesStretchMode": "fill"

These backgroundImage paths fail to render:

      "backgroundImage": "C:\\Users\\kfarm\\OneDrive\\Backgrounds\\Characters (Landscape)\\Þiálfi [Vizsla] - desktop.png",

      "backgroundImage": "C:\\Users\\kfarm\\OneDrive\\Backgrounds\\Characters (Landscape)\\Fálki [Vizsla] - desktop.png",

Additionally, adding these characters to tab name causes them to display the bad-encoding diamond.

# Expected behavior

Background image renders for any valid NTFS path or URI

Tab title renders without encoding issues

# Actual behavior

No background image shown, bad characters, great sadness.

... Given the rash of other character issues, I think it's a failure to interpret UTF-8, perhaps?

... Further investigation showed that switching the encoding of the file in VS would fix the tab issue, but Terminal would rewrite the background image paths with \uxxxx codes which I'd have to re-type.

**Comment by zadjii-msft** [comment]
Yea I'd concur that this is a utf-8 roundtripping problem. This could be on either end of serializing or deserializing, impossible to know four sure without debugging further.

**Comment by DHowett-MSFT** [comment]
I can't repro this with a JSON file saved in codepage 65001.
![image](https://user-images.githubusercontent.com/14316954/65552844-4c8c2300-deda-11e9-862c-e3a838b8c432.png)

![image](https://user-images.githubusercontent.com/14316954/65552848-52820400-deda-11e9-831a-6aa0c1af53c8.png)
