### ISSUE TITLE
Copied text from git diff inside powershell core doesn't have carriage return characters

### ISSUE THREAD

**Issue by medoni** [microsoft/terminal#2278]
# Environment

```
Windows build number: 10.0.18362.10005
Windows Terminal version (if applicable): 0.2.1831.0
Powserhell core version: 6.2.2
git version: 2.22.0.windows.1
```

# Steps to reproduce
- Setup a profile to open a powershell core tab directly. Starting pwsh.exe from cmd.exe or powershell.exe doesn't have the issue!
- call `git diff` inside of a git directory with unstaged changes
- select git output with mouse
- right click to copy
- open `notepad.exe`
- right click -> paste

# Expected behavior
pasted text with new line characters like  git output

# Actual behavior
no newline characters

**Comment by ebmarquez** [comment]
I'm having the same problem when coping syntax out of a ssh session.  EOL char seem to be missing.

**Comment by medoni** [comment]
Affects also 0.3.2171.0

**Comment by DHowett-MSFT** [comment]
This is @2275.

**Comment by DHowett-MSFT** [comment]
Sorry, #2275.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/1073
https://github.com/microsoft/terminal/issues/1126
https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275

https://github.com/microsoft/terminal/issues/2278
https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395
https://github.com/microsoft/terminal/issues/2717
https://github.com/microsoft/terminal/issues/52
