### ISSUE TITLE
"An empty pipe element is not allowed" after curly braces

### ISSUE THREAD

**Issue by schneidr** [microsoft/terminal#2279]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.3.2171.0

Any other software?
```

# Steps to reproduce

Paste a multiline PowerShell cmd that has a pipe symbol after curly braces in a powershell terminal.

Example:

	Get-Volume |
	Where-Object {
		$_.DriveLetter.length -gt 0
	} |
	Select DriveLetter,Size

# Expected behavior

The commands get executed. It works in regular PowerShell:

    PS C:\Users\geschnei> Get-Volume |
    >> Where-Object {
    >> $_.DriveLetter.length -gt 0
    >> } |
    >> Select DriveLetter,Size

    DriveLetter         Size
    -----------         ----
              C 254524760064

# Actual behavior

You get an error message:

> At line:2 char:47                                                                                                       + Where-Object { $_.DriveLetter.length -gt 0 } |                                                                        +                                               ~                                                                       An empty pipe element is not allowed.                                                                                       + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException                                       + FullyQualifiedErrorId : EmptyPipeElement

**Comment by DHowett-MSFT** [comment]
This is another manifestation of #1454

**Comment by DHowett-MSFT** [comment]
Sorry, I meant #1091.
