### ISSUE TITLE
BUG: profiles.json values do not round trip properly

### ISSUE THREAD

**Issue by kfarmer-msft** [microsoft/terminal#2280]
# Environment

```none
Windows build number:
Microsoft Windows [Version 10.0.18362.267]

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.3.2142.0

Any other software?
VS 2019 (though probably not relevant -- merely used this for editing profiles.json)
```

# Steps to reproduce

Start terminal.
Edit profiles.json to give background image an opacity of 0.3 exactly:
```none
            "backgroundImageOpacity" : 0.3,
```
Save.
Observe opacity change in running terminal.
Close profiles.json.
Close terminal.
Restart terminal.
Launch profiles.json from terminal.
Observe opacity value rewritten as 

```none
            "backgroundImageOpacity" : 0.30000001192092896,
```

Another case:

Set background image path to an interesting name, like:

```none
            "backgroundImage" : "C:\\Users\\kfarm\\OneDrive\\Backgrounds\\Characters (Landscape)\\Þiálfi [Vizsla] - desktop.png",
```

It comes back as

```none
            "backgroundImage" : "C:\\Users\\kfarm\\OneDrive\\Backgrounds\\Characters (Landscape)\\\u00dei\u00e1lfi [Vizsla] - desktop.png",
```
# Expected behavior

All values round-trip, retaining the actual value from the file, unless the value was explicitly changed as a result of user action.

# Actual behavior

Arguably, data corruption.  The values still *work*, technically, but they are not what the user specified.  A failure to properly re-encode will lose data.  Better to leave the original values untouched.

Related:  If I omit a profile GUID, why add one to the file?  Pick one on load and use it internally, but unless it's getting referenced elsewhere in the file, why have it at all?

**Comment by DHowett-MSFT** [comment]
This is tracked in #1398 . We may want to make all opacities and percentages integral anyway like we did for `cursorHeight`.

**Comment by surfer776** [comment]
.

mascouten777@gmail.com
