### ISSUE TITLE
Feature Request: Add a Copy Profile command

### ISSUE THREAD

**Issue by kfarmer-msft** [microsoft/terminal#2281]
# Description of the new feature/enhancement

Adds a command that, when executed, pops up a dialog with a field prompting for the name of a new profile, and another to edit the command (pre-populated with the command of the current profile?).  On confirmation, the new profile is created and added to the end of the list, and persisted in profiles.json for later editting.

Other profiles options can be omitted.  This is intended to be a quick "make a new profile using the settings of the current" command, without having to edit profiles.json.

# Proposed technical implementation details (optional)

This may be part of the larger profiles.json editting feature, but I think it warrants a separate, simpler workflow than a larger editing experience leads to.

I think this would be a good pairing for #2046.

**Comment by zadjii-msft** [comment]
Frankly I think this is better suited under the umbrella of #1564

**Comment by kfarmer-msft** [comment]
Agreed.  My intent was "I think the feature would work well in conjunction with #2046" -- which I'm also a fan of.

**Comment by DHowett-MSFT** [comment]
This is an interesting one. I think that we should relegate these actions to the settings UI, but I can see some value in having this be a quick action. I dunno. I'm inclined to come down on the side of "let's have an easy button once we _have_ buttons related to Settings".

**Comment by DHowett-MSFT** [comment]
(If y'all disagree, we can definitely reopen.)
