### ISSUE TITLE
Feature Request: Bundle more CLIs

### ISSUE THREAD

**Issue by kfarmer-msft** [microsoft/terminal#2283]
# Description of the new feature/enhancement

Microsoft has a number of CLIs that are worth having on-hand without having to install, for example, Visual Studio:  C# and F# interactive prompts come to mind.

I'd propose that some of these should be brought in either directly or as Store apps that tie into WT.  C# and F# would be good starts, since they are otherwise unavailable except by installing Visual Studio.

Office/Exchange prompt may be another good candidate.

# Proposed technical implementation details (optional)

Given the addition of the Azure Cloud prompt to WT, I expect the technical details of bundling such things is understood.  

Where it's not tractible to include the CLI itself (eg, Git), it may be useful to have at least the icon available (see #2282).

Proposed list:

- [ ] C# Interactive
- [ ] F# Interactive
- [ ] Exchange
- [ ] [HttpRepl](https://devblogs.microsoft.com/aspnet/httprepl-a-command-line-tool-for-interacting-with-restful-http-services)

**Comment by ffes** [comment]
Maybe some sort of snippet feature to add new CLIs from a (community based?) on-line collection?

**Comment by DHowett-MSFT** [comment]
Somebody had an idea on another thread about being able to put profile snippets in a common folder... and that dovetails very nicely with the idea of having a dynamic profile generator (#754 touches on this). That dynamic loader could just _load them from the files_. The more socialized I get to this idea the more I like it. #2303 :smile:

**Comment by DHowett-MSFT** [comment]
(In light of that, I'm going to close it as a duplicate. We'd like to get _out_ of the business of detecting shells, at least as far as we can, and into the business of letting applications tell us they exist!)
