### ISSUE TITLE
Ship with Windows

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#2284]
I know it this might be implemented in far future, or never be fullfilled, but I really wish that WT to be shipped *with* Windows and become the default terminal. (CONHOST would be kept for someone who really want to run very old programs.)

**Comment by CatTheHacker** [comment]
What do you mean? Windows Terminal uses `conhost`
Does this should ship with default Windows installation? No.
Is it possible to deploy it together with prepared Windows image? Yes.

**Comment by saschanaz** [comment]
It would be great to see Windows Terminal on Win+X menu by default instead of the old PowerShell 5.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the enthusiasm here! We're evaluating our options in this space, but putting ourselves fully into the Windows image puts a whole other set of constraints on us that we can't take at the moment.
We'll keep the community updated. :smile:
