### ISSUE TITLE
Start Windows Terminal with the command [terminal]

### ISSUE THREAD

**Issue by jrahma** [microsoft/terminal#2286]
Hi,

I suggest to use the **terminal** command for the new Windows Terminal and keep **cmd** for the old console

Because currently both **terminal** and **cmd** open the old console when you type in the start menu

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by zadjii-msft** [comment]
That might just mean the indexer needs to catch up on your machine:
![image](https://user-images.githubusercontent.com/18356694/62541800-20302080-b820-11e9-8f1d-2b2df29c7790.png)


You can actually already launch the terminal with the `wt.exe` alias. Just entering `wt` in the start menu should launch the terminal. You can also use `wt` to launch the terminal from cmd, powershell, etc.
