### ISSUE TITLE
Open terminal from folder explorer

### ISSUE THREAD

**Issue by jrahma** [microsoft/terminal#2287]
Hi,

When the user clicks inside file explorer and types **cmd**, they should be able to also type **terminal** to start the Windows Terminal in the selected folder

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by CatTheHacker** [comment]
Dupe of https://github.com/microsoft/terminal/issues/2286
Launching from File Explorer relies on `PATH` and `terminal` alias.

**Comment by zadjii-msft** [comment]
This is actually a dupe of #607 & #878.
