### ISSUE TITLE
No VERSIONINFO resource? [UAC prompt says "Unknown program" instead of "Windows Terminal"]

### ISSUE THREAD

**Issue by nyuszika7h** [microsoft/terminal#2289]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18945.1001]
Windows Terminal version (if applicable): 0.3.2142.0

Any other software?
```

# Steps to reproduce

Run Windows Terminal as an administrator.

# Expected behavior

The program's name should show up correctly in the UAC prompt.

# Actual behavior

The UAC prompt calls it "Unknown program" rather than "Windows Terminal". However, it's detected as a signed application and the icon is shown correctly.

![Screenshot of UAC prompt](https://user-images.githubusercontent.com/482367/62536495-69976480-b84e-11e9-9ec5-40386822a3ea.png)

**Comment by DHowett-MSFT** [comment]
We've honestly got almost no idea why this happens. :grin:

**Comment by DHowett-MSFT** [comment]
The "Desktop App Converter" (also a Centennial application) _doesn't_ do this, so I'm going to bet it's our fault somehow. We don't have a `VERSIONINFO` resource... and I bet that it's really cramping our style.

**Comment by DHowett-MSFT** [comment]
It turns out this is because we're using a resource for our app name (you know: the way they recommend)

**Comment by DHowett-MSFT** [comment]
Note to self: It looks like the UAC consent dialog pulls the application name from the `DisplayName` field in the manifest. That's the only one we need to pin down.
