### ISSUE TITLE
Use JSONC / allow comments in JSON per other Microsoft products

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#2292]
Windows 10.0.18362.0, Terminal Preview 3.

I needed to add a comment explaining why I'd disabled a config option

![image](https://user-images.githubusercontent.com/172594/62541842-846bd800-b852-11e9-9c85-420e85bdcfaf.png)

This is correct, comments aren't permitted in JSON. Terminal, like vsCode, should use JSONC (whether it has a .json or .jsonc extension):

![image](https://user-images.githubusercontent.com/172594/62541915-a49b9700-b852-11e9-9450-e11d359a80e2.png)

I know Code and Terminal are different teams but consistency would be good here, and comments are useful.

**Comment by zadjii-msft** [comment]
We actually do allow comments in the json file as of #1005. Dunno why VS Code is tagging the file like that, but they're definitely allowed.

**Comment by mikemaccana** [comment]
OK I'll fine it with vscode. 👍🏼

**Comment by mikemaccana** [comment]
https://github.com/microsoft/vscode/issues/78559

**Comment by cup** [comment]
https://github.com/microsoft/terminal/issues/4232

**Comment by flying-sheep** [comment]
It highlights it like this because things with a `.json` extension are supposed to be JSON and not JSONC. Adding an exception in VS Code will only fix it there, not for any other editor. The file should be renamed to reflect its real type.

**Comment by wetterkrank** [comment]
@zadjii-msft The settings.json file of Windows Terminal is not a valid JSON, so it will alert linters in most code editors. Why don't you rename the file to settings.jsonc?
