### ISSUE TITLE
`sl | lolcat` does not work

### ISSUE THREAD

**Issue by hsiktas** [microsoft/terminal#2295]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): 0.3.2142.0

Any other software?
Ubuntu 18.04 running in WSL1 with zsh as the default shell.
```

# Steps to reproduce

`apt install sl lolcat` in case they are not installed yet.
Then run `sl | lolcat`

# Expected behavior

A colorful steam locomotive runs over the screen and my productivity increases by 0.2 %.

# Actual behavior

![image](https://user-images.githubusercontent.com/4571159/62558503-7a110480-b879-11e9-9cd6-d5096f8111c1.png)
🤷‍♂️
`sl` works on its own but when piped through `lolcat`, I only see hundreds of lines of colorful gibberish scrolling by.

**Comment by kfechter** [comment]
what is the output of lolcat --version?

**Comment by hsiktas** [comment]
Confirmed! Updating to the recent lolcat fixes this issue and is seems like this was not caused by the new terminal emulator at all.
