### ISSUE TITLE
Feature Request: Requesting ability to change taskbar icon

### ISSUE THREAD

**Issue by mgrant24601** [microsoft/terminal#2299]
# Description of the new feature/enhancement

Allow user to customize the icon's appearance on taskbar. The little >_ is cute, but I'd like to assign an icon that pops out better. 

# Proposed technical implementation details (optional)

Probably allow user to configure desktop icon through a file reference in JSON configuration file

**Comment by oising** [comment]
duplicate: #1871 #1868
