### ISSUE TITLE
Feature Request: Setting to remove paths from tab title

### ISSUE THREAD

**Issue by AshrafMichail** [microsoft/terminal#2302]
# Description of the new feature/enhancement

**Problem:**
Tab titles are quite long including the full path of cmd.exe or powershell.exe which leaves little horizontal space for numerous tabs.  

**Other solutions:**
Friendly name by overriding the title is already tracked by another issue, however, it loses the name of current running application.

**Proposed feature:**
Preserve the running executable and provide an option to trim the full paths to only the .exe names in tab title.  For example, cmd.exe, powershell.exe would display in tabs instead of the full path.

# Proposed technical implementation details (optional)

Add a setting to let users filter display tab title string by removing full paths and only showing the exe filename.

**Comment by zadjii-msft** [comment]
This is something that's going to be addressed by #1320. 

You can also just have your shell program change the title for you. Most decent shells provide a way to do this via the prompt (`bash` and `powershell` both work like this). In cmd.exe, `title foo` will set the tab title to `foo`.
