### ISSUE TITLE
Option for choosing Ubuntu by default

### ISSUE THREAD

**Issue by Fegon** [microsoft/terminal#2305]
Please add an option for choosing Ubuntu shell by default

Thanks!

**Comment by zadjii-msft** [comment]
This is something that's already possible! By replacing the `globals.defaultProfile` value with the `guid` of the Ubuntu profile, the Windows Terminal will launch Ubuntu by default.

Refer to [this document](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md) for more info.

**Comment by mrchief** [comment]
How does one find these guids?

**Comment by DHowett-MSFT** [comment]
They're in your `profiles.json` file already.

**Comment by mrchief** [comment]
Not mine 
![image](https://user-images.githubusercontent.com/781818/62654887-d71ac200-b92e-11e9-97bb-d0fefa2bf8e7.png)

**Comment by mrchief** [comment]
I didn't have Ubuntu installed and I'm not sure if WSL was enabled when I first installed this. Maybe that's the reason I'm missing them?

**Comment by zadjii-msft** [comment]
Yea, we only generate the Ubuntu profile if it exists on first launch of the terminal. You could delete your profiles.json file and we'll re-generate it with the Ubuntu profile now that you have Ubuntu installed. 

This is a scenario that'll get better with #754.
