### ISSUE TITLE
Documentation Issue backgroundImageStrechMode

### ISSUE THREAD

**Issue by kort3x** [microsoft/terminal#2306]
Which values are allowed for backgroundImageStrechMode in profiles.json?

**Comment by zadjii-msft** [comment]
From https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md:

> Sets how the background image is resized to fill the window. Possible values: `"none"`, `"fill"`, `"uniform"`, `"uniformToFill"`
