### ISSUE TITLE
Bug Report (IF I DO NOT CHANGE THIS THE ISSUE WILL BE AUTO-CLOSED)

### ISSUE THREAD

**Issue by chrisericchapman** [microsoft/terminal#2308]
When I click setting, a JSON file opens

# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by oising** [comment]
"When I click setting, a JSON file opens" -- until the team gets around to designing a graphical settings UI, this is the expected behaviour. If you want to change a setting, change the json file and save it.
