### ISSUE TITLE
Cannot input Chinese after update

### ISSUE THREAD

**Issue by jliu1992** [microsoft/terminal#2311]
I can't switch to Chinese input method after update, current version is 0.3.2142.0.

**Comment by Elgx** [comment]
I also have the same problem.., do you solve this?

**Comment by zeyu203** [comment]
I also have the same problem.., do you solve this? thanks

**Comment by jliu1992** [comment]
Not yet, I think this is a problem with Microsoft terminals and requires a software upgrade to solve.

**Comment by DHowett-MSFT** [comment]
What versions of Windows are you all on?
Thanks.

**Comment by etern** [comment]
same issue #2213

**Comment by DHowett-MSFT** [comment]
I'll close this as a duplicate. Thank you.
