### ISSUE TITLE
Keep acrylic effect even when the window loses focus

### ISSUE THREAD

**Issue by michalhudecek** [microsoft/terminal#2314]
According to this Windows issue, it is up to the app developer to set if the acrylic effect keeps showing even when the window is out of focus: https://aka.ms/AA2vz28

With focus:
![image](https://user-images.githubusercontent.com/1215304/62600126-6489f200-b8ee-11e9-8a85-53299dd36a8b.png)

Without focus:
![image](https://user-images.githubusercontent.com/1215304/62600169-7c617600-b8ee-11e9-8ef5-0d5ecda65ed7.png)

**Comment by DHowett-MSFT** [comment]
According to _an unsubstantiated public comment_. Trust us, we would have done this if there were a way officially sanctioned by the team that owns Acrylic to do it.

**Comment by DHowett-MSFT** [comment]
(We're having that discussion with them, of course! Sorry!)

**Comment by devrnt** [comment]
Any updates on this feature?

**Comment by DHowett-MSFT** [comment]
Nope, the stance of the team that owns acrylic hasn’t changed on this.

**Comment by AkazaRenn** [comment]
May I ask if they have changed their views after six years? 🤦
