### ISSUE TITLE
Feature Request: Specify cursor behaviour on window focus / unfocus

### ISSUE THREAD

**Issue by flindeberg** [microsoft/terminal#2316]
# Description of the new feature/enhancement

Currently I find it hard to find focus, and confusing to pasting text into unfocused terminals, since you cannot change cursor behaviour in unfocused terminals. For example by changing color or opacity (I do not know the feasability of this). 

# Proposed technical implementation details

(Speculating without looking at actual code for ease of implementation, and images curtesy of Google image search along the lines of "terminal [window] focus") Since I like box cursors, I will provide three examples with box cursors which can be extended to other types of cursors.

An example from Code (possible today, terminal in focus shows unfilled box as cursor, terminal out of focus does not):
<img width="692" alt="terminal-split-pane" src="https://user-images.githubusercontent.com/11232267/62599791-728b4300-b8ed-11e9-8176-dfdf50184fc3.png">

An example from Linux (possible today, specifically Kali and Gnome terminal, focused terminal shown filled box while unfocused terminal shows nothing)
![root@TheHackerToday-_185](https://user-images.githubusercontent.com/11232267/62599986-fc3b1080-b8ed-11e9-8420-b7de035534b1.png)

Another example from Linux (not possible today, specifically Ubuntu and Tilix terminal emulator, focused terminal shows filled box while unfocused terminal shows unfilled box)
![Tilix-Interface](https://user-images.githubusercontent.com/11232267/62600093-47edba00-b8ee-11e9-9228-e2eb34f0aa03.png)

I do not propose that the result should be static, rather that the user can select what the cursor should look like in a focused window and an unfocused window. I.e.:

```
... profiles.json ...
"cursorShapeWindowFocus" : "filledBox",
"cursorShapeNoWindowFocus" : "emptyBox",
...
```

Of course taking height for #1203 so that the "filledBox" setting becomes more meaningful.

**Comment by zadjii-msft** [comment]
This is a pretty good idea.

**Comment by DHowett-MSFT** [comment]
Hey we just came to the same conclusion. Good idea, terminal backlog is great for it. :smile:

**Comment by fishzle** [comment]
This is an option, but you could also highlight/frame/focus the pane with the active cursor. Or, the one that sometimes get's implemented is de-focus the inactive panes (eg increase transparency, reduce contrast in text, etc).

I'm not saying cursor-highlight is right or wrong, I'm just saying the range of possible solutions is > changing-shape-fill-colour of cursor.

Note that there may be relationship to mouse-behaviours like focus-follows-mouse / click-to-focus etc.

**Comment by flindeberg** [comment]
> I'm not saying cursor-highlight is right or wrong, I'm just saying the range of possible solutions is > changing-shape-fill-colour of cursor.

I completely agree, I just wrote this issue with a suggested solution since I got frustrated after playing around with Windows Terminal and mutliple tabs / windows and constantly getting the vim / emacs / nano / other nox-editor right-click-pastes-into-unfocused-window wrong (not to mention that you have to click twice, once to focus, and once to paste).

Ties into #2444 (single click should focus and paste) and #524 (marking text should put text in clipboard) as the mouse as the primary copy-and-paste tool _between_ terminals (which the mouse should do well IMHO, but it should do neither more nor less).
