### ISSUE TITLE
Background color is not preserved when scrolling

### ISSUE THREAD

**Issue by twindan** [microsoft/terminal#2317]
# Environment

```none
Windows build number: Microsoft Windows Version 10.0.18362.239
Windows Terminal version (if applicable): 0.3.2171.0

Any other software? None needed to reproduce this.
```

# Steps to reproduce

1. Open a cmd.exe prompt using Windows terminal
2. Change the background color using the color command ("color 1f")
3. Press Enter until you are close to the bottom of the screen
4. Run the "dir" command  so that the text will scroll
5. Notice that the background color is reset for the part of the window that scroll.s

These images show side by side comparisons between Windows Terminal and the classic console
![BeforeScroll](https://user-images.githubusercontent.com/35891420/62603948-8a80b800-b929-11e9-91c6-0ec4af71ce92.png)

![AfterScroll](https://user-images.githubusercontent.com/35891420/62603965-95d3e380-b929-11e9-9f08-56c2fd5bf9b9.png)
:

# Expected behavior

As noted in the screenshots above, when the window scrolls, it should use the current background color instead of reverting to the default.

# Actual behavior

The window is reverting the background color.

**Comment by DHowett-MSFT** [comment]
This is #1036.
