### ISSUE TITLE
Feature Request: Title bar keep it simple

### ISSUE THREAD

**Issue by panoscool** [microsoft/terminal#2318]
Remove the long title bar and keep it simple, just the name/type of the terminal. For example imagine if i navigate many levels deep inside a folder tree how long it will be the title bar and wasting so much space. It will be much better just having for example logo + terminal.

**Comment by joandrsn** [comment]
You should search before suggesting new features.
Checkout #608 #1320 
In #2304 Microsoft asks for help documenting the feature for setting the title of the shell.

**Comment by DHowett-MSFT** [comment]
You can also just, you know, set `tabTitle`.
