### ISSUE TITLE
Feature Request: Shift+Click on "+" button should open new window

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#2320]
# Description of the new feature/enhancement

When I Shift-Click on the `+` button to start another terminal session I would like it to open a new window instead of a new tab, just like for instance Firefox does.

The same goes for Shift-Clicking an entry in the list of profiles.

**Comment by ffes** [comment]
Maybe related to #1051 and #1256

**Comment by DHowett-MSFT** [comment]
Definitely related. I made this a comment on #1051.
