### ISSUE TITLE
Copy and paste in bash generates one single line

### ISSUE THREAD

**Issue by havidarou** [microsoft/terminal#2324]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): Version: 0.3.2171.0

Using bash within Windows terminal.
```

# Steps to reproduce

Copy several text lines and paste them using vi text editor in bash (WSL).

# Expected behavior

Properly copied lines within the text editor.

# Actual behavior

A single line is generated with spaces so that it looks like they are different lines.

**Comment by havidarou** [comment]
Just to clarify, this happens when copying lines from within a file in vi to the very same file in vi.

If I copy text lines from outside (let's say, Visual Code) to vi, then this is what happens:
```
Line1

Line2

Line3
```

I get a jump line in between every line that I am copying.

**Comment by carlos-zamora** [comment]
So, clipboard keybindings copy/paste came in with PR #1093. There's two copy actions `copy` and `copyTextWithoutNewlines`. With mouse copy, holding SHIFT differentiates the two. With keyboard copy, these are two separate keybound options.

Given this information...
- if you try to mouse copy with(out) SHIFT, does that fix the issue?
- if you try to keyboard copy with one `copyTextWithoutNewlines` (vs `copy`), does that fix the issue?

Let me know below. Thanks!

**Comment by havidarou** [comment]
I tried copying with and without shift by using the mouse: same result.
I did the same thing with the keyboard: same result.

This basically renders useless editing text within the terminal in any Linux system : /

**Comment by johanburati** [comment]
Having the same issue you select a couple of lines from Windows Terminal, click the right button,  go to notepad, do Ctrl-V and everything ends up on the same line with space in between.

![image](https://user-images.githubusercontent.com/106444/62755050-63eb8a00-baad-11e9-9512-4a4ca050eb38.png)

**Comment by jonneolie** [comment]
This issue still exists. After i copy from a file/site or notepad etc. into the terminal with the Ubuntu app configured, i get an extra new line between every line.

When i open the Ubuntu app self, i can paste without any extra new lines.

**Comment by havidarou** [comment]
Hi, I also mentioned that
there are two kind of behaviors:

1. **Copying from within the terminal** -> generates a single line with spaces.
2. **Copying from outside the terminal** -> you get an extra line between every line.

**Comment by polyisobutylene** [comment]
When copying from a text editor (ex. vscode) spaces between lines will still be generated even if the file is using LF line endings
![image](https://user-images.githubusercontent.com/1903878/63097615-ee653b00-bf3e-11e9-893f-a02110319506.png)

Copying out of the terminal into a text editor does not add proper newlines as expected
![image](https://user-images.githubusercontent.com/1903878/63097675-15bc0800-bf3f-11e9-9e0f-4d744312024e.png)

On further review it also appears to add all of the whitespace after the content on each line (more space added the wider the terminal is)
![image](https://user-images.githubusercontent.com/1903878/63097776-43a14c80-bf3f-11e9-852e-5b367b32c062.png)

**Comment by threequarterwit** [comment]
I am seeing this is not just related to bash.  Within Powershell 5, powershell core 6 and 7 running in windows terminal, I am getting very inconsistent copy/paste behavior.  Extra whitespace, and missing line endings.  The whitespace and (missing)line endings are in different places if i resize the terminal window and re-generate the output and copy/paste once again.

Sometimes all lines of output might be pasted as 1 single line, other times, it may paste 6 lines correctly before it begins to start missing line endings, and running lines together

Reproduced by copying any multi-line output from terminal and pasting it into Notepad++ or vscode

**Comment by Aebian** [comment]
Can confirm this behaviour.

**Comment by hteibler** [comment]
If you paste the output of a table ( with \t and \n ) 
![image](https://user-images.githubusercontent.com/24313736/63688683-56056b00-c808-11e9-97b9-64e6c395b0e1.png)
in LibreOffice
all \t and \n are replaced with spaces ???
![image](https://user-images.githubusercontent.com/24313736/63688721-6d445880-c808-11e9-916c-4b560eae462b.png)

**Comment by genio** [comment]
This is the single most frustrating thing about Terminal that makes it mostly unusable. I can live with the little UI glitches, but this is pure frustration.

**Comment by nitinyadav745** [comment]
I am also facing the same issues as reported above in thread. I am primarily using powershell core 6 as primary profile in terminal . This inconsistent behaviour renders windows terminal useless for sysadmins. This is one tool which has huge potential as it gives you option for multiple tabs.

**Comment by termski** [comment]
When I copy paste from Windows Notepad three lines with data in towords a Ubuntu in WSL, the copy paste buffer adds an extra carriage return to every line.
look at this printscreen and the hexdump on the file with the copy pasted data  and you see the double '0a0a' when it should be a single. (running Windows Terminal (Preview) Version: 0.4.2382.0)
![copy-paste](https://user-images.githubusercontent.com/55285077/64867544-d962f100-d63d-11e9-919f-983a4eff3529.PNG)

**Comment by havidarou** [comment]
This is still happening in 0.5.
From Windows to bash: double jump lines.
From bash to Windows: there are no jump lines every two lines.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/1073
https://github.com/microsoft/terminal/issues/1126
https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275
https://github.com/microsoft/terminal/issues/2278

https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395
https://github.com/microsoft/terminal/issues/2717
https://github.com/microsoft/terminal/issues/52
