### ISSUE TITLE
Window Background Transparency behavior backwards?

### ISSUE THREAD

**Issue by nurbles** [microsoft/terminal#2326]
I just installed Windows Terminal for the first time this morning and the first thing I noticed -- before trying to make ANY changes to settings or even using the command lines -- was the semi-transparent background in the CMD tabs.  I think it looks neat, but I am confused about why it is transparent when the terminal window is in use but becomes solid when the terminal window loses focus?

It would seem to make much more sense with those states reversed as it is much easier to read text on a single, solid background color and it may be useful to have an idea what is behind the inactive terminal window.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.3.2171.0

Any other software? no
```

# Steps to reproduce

Open a CMD tab and focus then unfocus the terminal window to see the background opacity change.

# Expected behavior

My preference would be for solid when in use and some transparency when inactive.  Or at least, I would like an option to choose that mode.

# Actual behavior

The CMD tab is semi-transparent when in use and becomes solid when inactive.

**Comment by carlos-zamora** [comment]
This is by design. The system-level policy for all acrylic is that only an active and focused window is allowed to have it. :(

**Comment by nurbles** [comment]
> The system-level policy for all acrylic is that only an active and focused window is allowed to have it.

Luckily I figured out how to disable it.  A feature like this will only have value for me when can work like I expect.  Sorry if I wasted your time.

**Comment by carlos-zamora** [comment]
@nurbles No worries! Just curious, how were you able to disable it?

**Comment by nurbles** [comment]
You need to mess with the JSON settings file and set `"useAcrylic": false` for the shells you don't want to do acrylic at all or set `"acrylicOpacity":1.0` (or maybe to zero, I'm not sure which way is completely solid)  But if you search for those settings, they are documented online.

**Comment by FriskyDev** [comment]
Really broken if you ask me. The point of transparency in the terminal (for example in Unix) was always to allow you to see beneath the window when it does **not** have focus to help find other things you might have hidden underneath. When it has focus, you want the background to be tight on the font to make them easier to read.

**Comment by youngmit** [comment]
If the Fluent folks have made that decision, and in such a rigid manner, then it seems like Acrylic is simply being mis-used in this context? I'm not a UI designer, but it seems like Acrylic isn't really intended for this type of application. Is there some other means to achieve a similar effect, while maintaining more control? I think it's super pretty, but I've just had to turn it off, since the behavior is so jarringly upside-down. Even straight-up transparency that changes between a focused/unfocused window would be better than nothing.
