### ISSUE TITLE
CLS in CMD shell doesn't clear scrollback

### ISSUE THREAD

**Issue by nurbles** [microsoft/terminal#2328]
In a stand-alone CMD window, the **CLS** command clears not only the text currently visible in the window, but all of the history in the scrollback buffer.  In a Windows Terminal CMD tab, clear is clearing only the currently visible text, leaving the scrollback content untouched.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.3.2171.0

Any other software? no
```

# Steps to reproduce

1. Open a command (CMD) tab.
2. Execute enough commands to put data in the scrollback buffer.
3. Execute **cls**
4. Observe results

# Expected behavior

I expect the screen and scrollback buffer to be completely cleared.

# Actual behavior

Only the screen is cleared.

**Comment by richardcox13** [comment]
This also happens with PowerShell.

**Comment by j4james** [comment]
I believe this is a duplicate of #1305.

**Comment by DHowett-MSFT** [comment]
Looks like! Thanks.
