### ISSUE TITLE
Feature Request: Nested profiles

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#2330]
# Description of the new feature/enhancement

Right now I have 5 profiles I use. I just played a bit with adding a ssh-profile and it works fine. But when I want to add all the profiles I have in Putty in WT I need to add another 20+ ssh-profiles. This means the list is going to be really long.

So being able to make submenus and put my profiles in a multiple submenus would be much welcomed.

Initially the menu looks like this: 
```
PowerShell
CMD
WSL
SSH-Group1 > 
SSH-Group2 > 
```
When a submenu is selected, something like this
```
PowerShell
CMD
WSL
SSH-Group1 >
SSH-Group2 > +--------+
             | Host 1 |
             | Host 2 |
             | Host 3 |
             +--------+
```

**Comment by DHowett-MSFT** [comment]
What we really need is more of a _configurable menu._ Profiles should never nest, but a configurable menu should. That'll be #1571.
