### ISSUE TITLE
Split terminals like tmux or cmder

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/terminal#2332]
Will be great if we can duplicate/divide terminal screen like tmux or cmdr using some key shortcuts like Ctrl + Alt + H for horizontal division or Ctrl + Alt + V for vertical, and the new terminal need open in the same path of the previous terminal if we are in c:\Users the new terminal need open in the same place, if we are in Linux using /home/ the new need do the same thing and open in same /home directory.

**Comment by DHowett-MSFT** [comment]
Please make sure you search before requesting a new feature. This is #1000.

**Comment by ucavalcante** [comment]
sorry for that a didn't know these feature its called panes.
ty for your help.
