### ISSUE TITLE
external: TSF auxiliary input box doesn't exist in 20H1

### ISSUE THREAD

**Issue by ksawerykarwacki** [microsoft/terminal#2334]
I'm on build Fast Ring build 18950 and Terminal 0.3.2171.0 and I cannot input any emoji from emoji keyboard that shows using win + .

It doesn't work no matter which shell I'm using (PS Core, cmd, Ubuntu). If I copy emoji from some other place and paste in to the console everything works fine.

**Comment by DHowett-MSFT** [comment]
It looks like the small box with the green arrow that used to exist on 19H1 has been removed in recent insider builds. I'll let the text services team know that they broke a core scenario.
Thanks.

**Comment by DHowett-MSFT** [comment]
This is almost certainly the same as #2213. Thanks!
