### ISSUE TITLE
x to close Tab is hidden by long title.

### ISSUE THREAD

**Issue by koolhand** [microsoft/terminal#2336]
# Environment

Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.3.2171.0

# Steps to reproduce

* Open Windows Terminal (Preview)
* The default Powershell tab opens, with the title "c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe"
* click the **+** button to open a new tab
* A second tab opens. the title "c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe" does not fit inside the tab, and is cut off at "...\pow" before the new Tab *+* button

# Expected behavior

* The **x** to close the second tab would be visible, after the truncated window title, and before the New Tab **+** button, to allow the tab to be closed.

# Actual behavior

* There is no **x** to close the tab available. It is truncated along with the window title.

![terminal-preview-tab-noX](https://user-images.githubusercontent.com/3262046/62661009-096e0300-b9b3-11e9-93d0-c59b947ef63f.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the report. I think there are at least two other identical reports on the front page of the issue list so I’m going to close this one without digging up the number.

**Comment by koolhand** [comment]
Whoops yes thanks @DHowett-MSFT dupe of #2333
