### ISSUE TITLE
Copy paste is not working 

### ISSUE THREAD

**Issue by nitishk72** [microsoft/terminal#2340]
# Environment

```none
Microsoft Windows [Version 10.0.18362.267]

Any other software?
```

# Steps to reproduce
I copied some text and tried to paste in new Windows Terminal and it doesn't paste that.
### How I pate the content
- Ctrl + V
-  Shift + Ins
- Right Click ( No context menu )

# Expected behavior
When I copy something and paste it. It should work as it works in Command Prompt 

# Actual behavior
It doesn't paste anything

**Comment by zadjii-msft** [comment]
Do you have a keybinding for `paste` in your profiles.json? Mine looks like the following:

```json
            {
                "command" : "paste",
                "keys" :
                [
                    "ctrl+shift+v"
                ]
            },
```

If you installed the terminal for the initial 0.2 release, you won't automatically get the copy and paste keybindings added.

**Comment by trajano** [comment]
I added ctrl-ins and shift-ins in my settings.  here's the gist https://gist.github.com/trajano/24f4edccd9a997fad8b4de29ea252cc8 it would be nice if it were added in by default.

**Comment by nitishk72** [comment]
I found the default setting for paste: Ctrl + Shift + V

Thanks for help
