### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by mr1ay** [microsoft/terminal#2344]
https://github.com/mr1ay/changebrightness/tree/master
 I dont run program in Terminal :/
but I runnig normal cmd.

Or you add mouse access command to terminal 
for example;

echo "button1"
for /f "tokens=1-3" %%a in ('bg.exe mouse') do set x=%%a&set y=%%b
if %x%==1  goto asdaf

**Comment by zadjii-msft** [comment]
Mouse input doesn't work correctly in the Windows Terminal currently. That's being tracked by a pair of issues: #545 and #376. Once _both_ of those are done, mouse input will work in the Terminal again.
