### ISSUE TITLE
AltGr+4 (§) (portuguese keyboard) does not get deleted as I'm trying AltGr sequences.

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2345]
AltGr+4 (§) (portuguese keyboard) does not get deleted as I'm trying AltGr sequences.
![2019-08-07_09-21-07](https://user-images.githubusercontent.com/3235846/62602891-0dd3e680-b8f5-11e9-8732-1760874bc7c1.gif)

_Originally posted by @rjfmachado in https://github.com/microsoft/terminal/issues/1375#issuecomment-518975239_

**Comment by zadjii-msft** [comment]
There's a good chance conpty isn't handling backspacing double-wide characters correctly. That's my initial theory looking at this bug.

**Comment by DHowett-MSFT** [comment]
This'll definitely be helped by #2066. Probably so much so that it's just gonna be a duplicate?
