### ISSUE TITLE
Redraw issue

### ISSUE THREAD

**Issue by SeanTAllen** [microsoft/terminal#2352]
I use `fish` shell that will display possible autocompletions. In terminal, it doesn't always draw the screen correctly. Here is a screenshot after completion where the last couple ghost characters were left over from the suggested completion. Note, this doesn't always happen. Normally everything is redrawn correctly.
![Annotation 2019-08-08 120632](https://user-images.githubusercontent.com/193596/62719126-4fd45980-b9d5-11e9-8a71-314070562396.png)

Currently using 0.3.2171.0

**Comment by zadjii-msft** [comment]
I'd bet money that this is due to us incorrectly guessing the widths of the powerline chars. Looks like they're all being treated as double wide, but I'd imagine they're actually only 1 wide in the buffer. 

Could you repro that scenario with the same font set in WSL via conhost.exe (not the Windows Terminal), and paste what it looks like?

**Comment by SeanTAllen** [comment]
I can not reproduce via conhost.exe nor via the terminal in VSCode. It's purely a Windows Terminal issue.

**Comment by SeanTAllen** [comment]
@zadjii-msft playing with this a bit more in windows terminal, it only appears to happen when the powerline has "git status" icons in it. The font that is used for that, doesn't display those symbols in conhost.

**Comment by zadjii-msft** [comment]
Could I get a screenshot with the up and down arrows in conhost? they look like maybe the one we're guessing is 2 wide instead of 1 wide:

These guys:
![image](https://user-images.githubusercontent.com/18356694/62723058-65498380-b9d5-11e9-9ad6-15a48f3989f1.png)

**Comment by SeanTAllen** [comment]
![Annotation 2019-08-08 131124](https://user-images.githubusercontent.com/193596/62723186-0ccab400-b9de-11e9-98d1-15094a67562f.png)

**Comment by SeanTAllen** [comment]
And here they are in VSCode...

![Annotation 2019-08-08 131204](https://user-images.githubusercontent.com/193596/62723231-2b30af80-b9de-11e9-8669-56fc9c410bc9.png)

**Comment by zadjii-msft** [comment]
Yea that'll do it. 

This is probably some combination of issues, #2066 might be the one that ends up fixing it. 

@miniksa might also have thoughts on the character being rendered as 2 wide

**Comment by SeanTAllen** [comment]
@zadjii-msft Let me know if you need anything else from me.

**Comment by Dijir** [comment]
On mine it is not rendering poweline characters correctly.

VSCode:
![](https://i.imgur.com/iyDH0Xr.png)

Windows Terminal:
![](https://i.imgur.com/R909JiW.png)

**Comment by ksawerykarwacki** [comment]
@zadjii-msft I have some rare case. Characters have some strange random gaps (they are not always on the same spot) but it is like pixel or two wide not whole character.

[
<img width="180" alt="{81FF00FF-FB28-4E40-98ED-C4E62F55346B}" src="https://user-images.githubusercontent.com/11694791/63029165-5caeec80-beb0-11e9-914e-d577679bb4aa.png">
](url)

**Comment by DHowett-MSFT** [comment]
This is almost certainly #633 #635, and will be helped by #2066.
