### ISSUE TITLE
Label color recommendation for readability

### ISSUE THREAD

**Issue by sharwell** [microsoft/terminal#2354]
The foreground color for labels **Area-Performance** and **Issue-Bug** are difficult to read. I suggest changing them ever-so-slightly darker (really an imperceptible change to the background color) so that GitHub detects that the foreground color should be white instead of black. 👍 

Observed in https://github.com/microsoft/terminal/issues/2008#issuecomment-513475858

**Comment by cinnamon-msft** [comment]
Fixed!
