### ISSUE TITLE
Bug Report - PowerShell Tool not working in Azure Cloud Shell.

### ISSUE THREAD

**Issue by MaximoTrinidad** [microsoft/terminal#2356]
After signing to Azure Cloud Shell, I immediately want to use PowerShell, but I'm having issue with the cursor going to the top of the screen.

# Environment
```
Windows 10 Pro Build 1903 (x64)
Windows Terminal (Preview) - Version: 0.3.2171.0
PowerShell 6.2.2 GA
PowerShell 7 Preview.2
```

# Steps to reproduce
1. Open Terminal Settings to change the "colorScheme": "Solarized Dark", to "colorScheme": "Campbell", for better user experience
2. From the terminal list select "Azure Cloud Shell".
3. Type pwsh, and wait for the prompt.
4. At the PowerShell prompt, type  $psversiontable, and press enter.
5. Type "dir" and check the cursor position.
6. Type "exit" and press enter to exit PowerShell. (not possible)

# Expected behavior
To be able to use PowerShell without any issues.

# Actual behavior

1. At the PowerShell prompt, type  $psversiontable, and press enter.

![TerminalAppErr_01_2019-08-08_14-04-40](https://user-images.githubusercontent.com/19892435/62726914-515a4d80-b9e6-11e9-803b-a2e94b38f977.png)

2. Type "dir" and check the cursor position.

![TerminalAppErr_02_2019-08-08_14-04-40](https://user-images.githubusercontent.com/19892435/62726941-5a4b1f00-b9e6-11e9-9cb7-0e29e607e2b8.png)

3. Type "exit" and press enter to exit PowerShell. (not possible)

At this moment, after a few minutes, Azure Shell seems to freeze, forcing the manual terminate the session.

**Comment by DHowett-MSFT** [comment]
Is there a chance that this is the same as #2267?

**Comment by MaximoTrinidad** [comment]
@DHowett 

Apologies! I did a search and didn't saw #2267. 
:(
