### ISSUE TITLE
Use hyphen-minus (-) for command-line options instead of a slash (/)

### ISSUE THREAD

**Issue by ErikHumphrey** [microsoft/terminal#2357]
# Description of the new feature/enhancement

To reduce ambiguity, increase ease-of-use and ease-of-learning for users, and increase parity with Unix-like systems, Windows should use a hyphen-minus (`-`) as an equivalent of a slash (`/`) character for command-line options (AKA options, flags, switches). 

Microsoft has advocated for the use of `\` as the path separator for decades.<sup>[[1]](https://stackoverflow.com/a/38428899/3011319)</sup> While Windows can generally use both `\` and `/` interchangeably for file paths, other operating systems cannot. This change, though not trivial, will allow `/` to be the standard path separator, reducing the headaches when copying Windows paths with backslashes (`\`) failing to work in Shell comands. For example, copying the path to the current folder/directory in File Explorer (by clicking the empty space beside the breadcrumbs is not useful when using Bash or similar due to the path using backslashes as a path separator. The same applies for other path-copying features in Windows programs, such as Microsoft Visual Studio Code's "Copy Path" and "Copy Relative Path" in the context menu for open files (https://github.com/Microsoft/vscode/issues/6308).

# Proposed technical implementation details 

I don't know the specifics of resolving this issue, but I do know a few things to consider. Further, it's possible this issue may not primarily apply to any of the many projects tracked by this repository, but it's better-suited as an issue for a public GitHub tracker than as a feature request in Feedback Hub.

* Spaces around command-line options are not required in Windows, but are in Unix-like systems.<sup>[[2]](https://en.wikipedia.org/wiki/Command-line_interface#Command-line_option)</sup>
  * `DIR/Q/O:S d*` does the same thing as `dir /q d* /o:s` on Windows.
* Windows should require spaces around all arguments and options (beyond `args[0]`) like Unix-like systems, but allow running options together.
  * While `ls -lS D*` is equivalent to `ls -l -S D*` on Unix-based systems, `DIR /qo:s d*` doesn't contain a valid parameter on Windows.
* An effort to retain the existing functionality to some extent should be made, so as to not break old software. This is a challenge because `/` command-line options in Windows have been historically added right after paths with `\` characters.

Though the `\` is more of a convention than an OS restriction in Windows, the restrictions of Unix shells are further hamstrung by this convention in Windows.

## Alternative solution

Alternatively, the Ubuntu shell used by Windows Terminal (whether it's bash, csh, fsh, sh, or zsh) could creatively resolve backslashes (`\`) in file paths to (`/`), or at least when `cd` is being used, but in no other scenarios. That would eliminate a lot of inconvenience, whether it's having to manually type the file path out, having to manually change all the backslashes to slashes or having to use a utility that produces the path with Unix-like `/` format.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the feature request.
Most newly-authored tools in Windows _do_ support `-` (and even recommend it instead of `/`). The problem is one of compatibility. Unfortunately, we can't fix this for the vast majority of preexisting and deployed tools in the wild.
We are making an "effort to retain the existing functionality" by simply never changing them -- old tools like cmd and its builtins (`dir` being one such) are fully parked because every single change we make [comes back to bite us.](https://github.com/microsoft/terminal/blob/master/doc/Niksa.md#cmd).

**Comment by Obed-oparaugo2001** [comment]
it was helpful
