### ISSUE TITLE
Ability to Launch new shell (cmd powershell etc) with elevated privileges. 

### ISSUE THREAD

**Issue by linuxrebel** [microsoft/terminal#2358]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by linuxrebel** [comment]
Right now there is no means to launch an admin level window within the shell.  Much needed.

**Comment by DHowett-MSFT** [comment]
This is being tracked in enough different issues that I'm not going to pick any single one to link it to. Sorry!
