### ISSUE TITLE
Feature Request - Use color schema "Campbell" for the Azure Cloud Shell.

### ISSUE THREAD

**Issue by MaximoTrinidad** [microsoft/terminal#2359]
# Description of the new feature/enhancement
Improve the console User Experience by using the console schema "Campbell".  Currently, using the  "Solarize Dark", makes it harder to read and the bash console colors are gone.

# Proposed technical implementation details (optional)
Change:
"colorScheme": "Solarized Dark",
to:
"colorScheme": "Campbell",

**Comment by DHowett-MSFT** [comment]
Looks like this was already changed.

https://github.com/microsoft/terminal/blob/6c747c565b52b377410b317469efe3ef5e0beb50/src/cascadia/TerminalApp/CascadiaSettings.cpp#L271

**Comment by MaximoTrinidad** [comment]
@DHowett 

Thank You!
:)
