### ISSUE TITLE
Feature Request: disable bell

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#2360]
# Description of the new feature/enhancement

Make a setting to disable the bell. This could be a per profile setting.

Maybe other "bell" settings can be desirable like:

```
"bell": "enable"  (default)
"bell": "disable" (this feature request)
"bell": "visual"
```

So with that in mind don't let the setting be a boolean.

Probably related to #72

**Comment by DHowett-MSFT** [comment]
This depends on #1608.

**Comment by trajano** [comment]
In addition, I want that to be configurable on both `global` and on `profile` level

One change though, instead of the following to be default 

```
"bell": "enable" 
```
use 

```
"bell": "default" 
```

that way we can use 

```
"bell": "path to mp3,wav,ogg" 
```

**Comment by DHowett** [comment]
I'm gonna merge this with "the terminal should actually support bell", because right now it actually _doesn't even support bells._

/dup #4046

**Comment by zadjii-msft** [comment]
Hey with #7679 adding support for audible bells, let's re-open this to track disabling them (again)

**Comment by ffes** [comment]
Since this issue is reopened, will this get the same milestone as #7679?

**Comment by zadjii-msft** [comment]
@ffes Absolutely, I'll make sure of that ☺️

**Comment by nathanblair** [comment]
I'm on the Windows Terminal Preview from the Microsoft Store, and while I can't determine if the bell is truly disabled for a Powershell shell, I am definitely hearing it while in Alpine WSL.

Here's what I have in my settings.json (which I allowed Terminal to recreate after installing the newest 1.5 release):

```
    ...
    "bellStyle": "none",
    ...
```

I'll note that VS Code was unable to see any "bell" properties (I assume these properties are populated from the json schema).

I have other features from 1.5 like a maximizedFocus so I'm positive I have the most recent version. Should I do a full uninstall and then install Terminal Preview fresh?

**Comment by zadjii-msft** [comment]
Where did you put `bellStyle`? In the global settings (at the root of the json), or in a profile? Since `bellStyle` is a per-profile setting, if you want it to apply to all profiles, you'll need to put it in the `profiles.defaults` object:

 
![image](https://user-images.githubusercontent.com/18356694/98959071-8c401080-24c8-11eb-863a-8279c3f4c70b.png)

**Comment by nathanblair** [comment]
Excellent call! Indeed, that fixes it. Thanks!
