### ISSUE TITLE
Feature Request : enable WinRM or PowerShell Remoting connections

### ISSUE THREAD

**Issue by RoguePointer80** [microsoft/terminal#2362]
# Description of the new feature/enhancement
For remote Windows computers, like Azure VM (or other cloud providers), there is no direct way to have a remote terminal. Automation tools like Hashicorp Packer rely on WinRM, also known as PowerShell Remoting, to send powershell commands and receive the output.
It would be a great productivity improvement to have a new connection type (similar to the Azure Cloud Shell), which would connect to a remote computer securely using WinRM and provide a shell. With the current ability to have tabs in Windows Terminal, a developer could have in the same app multiple shells on multiple computers. Think of it like Remote Desktop Connection Manager, but for terminals instead of GUI.
This is related to issues #555 and #626.

# Proposed technical implementation details (optional)
In addition to the curren azure cloud shell connection type, add a new type called for WinRM. When the profile contains this particular guid, launch a new WinRM client. As for the connection settings like the remote host address, username/password etc, this could either be parsed from the "commandline" profile property, or add a new profile property called "connectionspecific", which would be a json object that is passed down to the specific connection being created.

I believe the WinRM client components are part of Windows, so that wouldn't be too much of a problem to use.

**Comment by DHowett-MSFT** [comment]
Windows has both an SSH server (in 1803, 1809 and 1903) and an SSH client. Please use those instead of WinRM.
Terminal supports SSH already. Just use `ssh.exe`.

**Comment by DHowett-MSFT** [comment]
(WinRM is not good for remoting terminals because it deals with objects, not text streams. It is very, very difficult to use it for interactive sessions.)
