### ISSUE TITLE
WSL-Tab immediately closing

### ISSUE THREAD

**Issue by LarsBehl** [microsoft/terminal#2363]
# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version: 0.3.2171.0

Additional Software: Ubuntu WSL1
```

# Steps to reproduce
Unknown, happened on first launch after update to v0.3

# Expected behavior
Open an Ubuntu WSL1-Tab

# Actual behavior
Open an Ubuntu WSL1-Tab and immediately closing it

**Comment by DHowett-MSFT** [comment]
What happens if you run WSL from CMD?

**Comment by LarsBehl** [comment]
Performs normally; starting WSL

**Comment by zadjii-msft** [comment]
Could you share your profiles.json and also:

**Comment by LarsBehl** [comment]
Feedback via feedback hub is sent. I am currently using the same profiles.json file on another machine, where it works perfectly fine

[profiles.zip](https://github.com/microsoft/terminal/files/3487033/profiles.zip)

**Comment by DHowett-MSFT** [comment]
That'll do it. Right now, and until we make a release with #2298 included, your settings will "roam" from machine to machine. The exact name of the Ubuntu distribution on your first machine probably doesn't match the one on your second.

Can you confirm that the name after `wsl.exe -d` matches the name of your distribution when you run `wsl.exe -l`?

**Comment by LarsBehl** [comment]
Name did not match completely, ```wsl.exe -l``` showed up ```Ubuntu-18.04 (Standard)```. Currently I am wondering why it worked in the first place. Most important is, that it is fixed now, thanks
