### ISSUE TITLE
Scrolling not possible with some window-filling applications

### ISSUE THREAD

**Issue by adrianghc** [microsoft/terminal#2364]
# Environment

```
Windows build number: 18362.267
Windows Terminal version (if applicable): 0.3.2171.0

Any other software? poolmon
```

# Steps to reproduce

Start an application like poolmon from the Windows WDK that takes up the entire screen buffer while it's running.

# Expected behavior

Under the normal Windows 10 terminal, I can scroll through it with the scrollbar and the scroll wheel.

![image](https://user-images.githubusercontent.com/11506007/62737206-86d75900-ba2f-11e9-9b99-2aba49fcd2c4.png)
![image](https://user-images.githubusercontent.com/11506007/62737218-8ccd3a00-ba2f-11e9-8ce5-088fae3fb43d.png)

# Actual behavior

Using Windows Terminal 0.3.2142.0, there is no scrollbar and using the scroll wheel does not do anything either. Hovering over where the scroll bar should be makes it appear, but there is no actual bar, only up and down arrows.

![image](https://user-images.githubusercontent.com/11506007/62737233-99519280-ba2f-11e9-9841-5920d2a5e762.png)
![image](https://user-images.githubusercontent.com/11506007/62737238-9e164680-ba2f-11e9-80f5-06aadef69c12.png)

(By the way, if anyone knows what's up with that PEPI memory leak you'd be my hero but that's another story, I guess.)

**Comment by DHowett-MSFT** [comment]
This is likely to be "conpty doesn't support mouse events" and then "windows terminal doesn't support mouse events." This is doubly true if the application in question _actually listens for Windows mouse events_ (and not VT mouse events.). #376  #545

**Comment by Squall-Leonhart** [comment]
None of the changes mentioning this issue have fixed this issue, Poolmon is not scrollable when the buffer size exceeds the starting window height.
