### ISSUE TITLE
It is hard to see the pane divider in dark mode

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#2377]
# Environment

```none
Windows build number: 18362.239
Windows Terminal version (if applicable): 0.3.2142.0
```

# Steps to reproduce

Open Windows Terminal in dark mode.
Add keybindings to split a tab into multiple panes. Ex:
```json
            {
                "command": "splitHorizontal",
                "keys": [
                    "ctrl+shift+-"
                ]
            },
            {
                "command": "splitVertical",
                "keys": [
                    "ctrl+shift+|"
                ]
            },
```

Open a profile that has a dark background, like black or something close to that, ex, Campbell theme, where background is #0C0C0C.

Split the tab.

# Expected behavior

To be able to easily distinguish the pane separator.

# Actual behavior

In dark mode the pane separator is hard to see due to low contrast with surrounding background. Example:
![image](https://user-images.githubusercontent.com/4239171/62805059-b45dea00-baa3-11e9-80c4-e97ffaebcb5f.png)

In comparison, in light mode the separator is very visible:
![image](https://user-images.githubusercontent.com/4239171/62805092-d3f51280-baa3-11e9-9d73-756e141ae1fe.png)

Ideally, the color of the separator should take into consideration the surrounding background in order to show up with enough contrast to be visible in any combination.

**Comment by WSLUser** [comment]
Make it color configurable. Because I'd like red for dark mode but somebody might want blue, and another person green, and so on.

**Comment by DHowett-MSFT** [comment]
I am not of the opinion that we need a configuration option for every pixel that appears on the screen. It's a UI element: when we have a configurable UI, it'll "follow". :smile:

**Comment by WSLUser** [comment]
Ha yeah I don't believe there should be a config option for every pixel but with the configurable UI, I'd like control over each of the UI elements if possible. Probably can just make it match light mode for now as a default (though I'd appreciate you more if you made it red by default).

**Comment by jolsen71** [comment]
In related manner, it'd be nice to have a visual border between the tabs, too. At least for me I can't see any border at all.
![image](https://user-images.githubusercontent.com/6641548/63056931-ba423980-beae-11e9-8993-3d818c1d2804.png)
In distant (unrelated?) topic, I can barely tell which tab is active.

**Comment by DHowett-MSFT** [comment]
The tab separator issue was already fixed upstream; we just need to ingest a new version of the package.
I'm going to close this out in favor of #1000, the epic for panes.

**Comment by dlukes** [comment]
> I'd like control over each of the UI elements if possible

@WSLUser Currently, the color of the separator in dark mode seems to match your highlight color setting under the system-wide *Themes and related settings* (find that via the Start menu), so if you want to customize it, that's the way to go :)
