### ISSUE TITLE
Can't use Chinses input in terminal

### ISSUE THREAD

**Issue by HelloGithubC** [microsoft/terminal#2385]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by HelloGithubC** [comment]
- Environment

Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable):

- Any other software?
Microsoft Pinyin
Sogou Pinyin

- Steps to reproduce
1、open the terminal
2、choose cmd or powershell
3、input something

- Expected behavior
![image](https://user-images.githubusercontent.com/47917101/62820668-45af8800-bb9a-11e9-92b2-364611094e69.png)

- Actual behavior
![image](https://user-images.githubusercontent.com/47917101/62820680-624bc000-bb9a-11e9-9b3d-4598a7532b9f.png)

**Comment by zadjii-msft** [comment]
This is a dupe of #2213
