### ISSUE TITLE
Terminal won't open maxmized when "Run" field in shortcut set to Maximized

### ISSUE THREAD

**Issue by miklevin** [microsoft/terminal#2386]
# Environment

```none
Windows build number: 10.0.18956.1000

Windows Terminal version (if applicable): 0.3.2142.0
```

# Steps to reproduce

Drag tile from Windows Start Menu to desktop to create Link shortcut. Right-click shortcut icon and select properties. Change Run field to Maxmimized. Hit Apply. Close properties. Double-click shortcut icon. Terminal window does not open maxmimized, or at least it doesn't move the window to the upper-left of the screen the same way it would if you hit the Maxmimize button or Windows Key + up-arrow.

# Expected behavior

Terminal window should open Maxmimized in the upper-left of the Screen appearing full-screen for immediate use the same way it would as if you hit the Maximize button on the Terminal window or pressed Windows Key + up-arrow.

# Actual behavior

Terminal window is opening, but is positioned offset to the lower-right from what is expected. This requires an extra keystroke or mouse movement to maximize the window properly, which is a real show-stopper for terminal dandies like myself who thing you should be able to hit your keyboard shortcut to launch your Terminal and then immediately start using it.

![Mike-Levin-Desktop-Shortcuts](https://user-images.githubusercontent.com/4175278/62822331-ab2a5700-bb4f-11e9-9b5b-53959cb131aa.PNG)
![Mike-Levin-Bash-Terminal](https://user-images.githubusercontent.com/4175278/62822333-b087a180-bb4f-11e9-8c15-976603c0fe85.PNG)

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, a platform limitation. I have filed MSFT:23202140 on the appropriate team to see if we can't get something done about it.

**Comment by miklevin** [comment]
In what way is that a platform limitation? It works on all other apps, just not here on Microsoft Terminal, like the key place where it should work. Not being able to pull up a full-screen with the OS's built-in keyboard shortcut system is a pretty big deal. Maybe further research is necessary before closing.

**Comment by zadjii-msft** [comment]
It's something that actually doesn't work for any _Win32 packaged applications_ ("Centennial apps"). For example, with Edge or any WSL distro, that doesn't necessarily work. The flag that checkbox sets isn't getting properly passed to the `STARTUPINFO` of a centennial application.

**Comment by DHowett-MSFT** [comment]
> Maybe further research is necessary

Here's a snippet of the bug I filed on the team that owns "centennial" activation:

> It is possible to create a shortcut to a centennial application using "shell:appsfolder" It is further possible to configure that shortcut to spawn the application in Maximized/Minimized/Normal windowing mode.
> 
> ![image](https://user-images.githubusercontent.com/14316954/63113969-86b3ed80-bf48-11e9-8870-e92393a16675.png)
> 
> The WinMain entrypoint has a parameter, "nShowCmd", which should receive this information.
> 
> I have created an application that displays a messagebox containing the value of nShowCmd. Here's an example when i run it in different circumstances.
> 
> * UNPACKAGED (raw EXE)
>    * Double-clicked in explorer
>       * ![image](https://user-images.githubusercontent.com/14316954/63113983-8e739200-bf48-11e9-817f-0383fe1ac19a.png)
>    * From a shortcut marked RUN MAXIMIZED
>       * ![image](https://user-images.githubusercontent.com/14316954/63113997-95020980-bf48-11e9-8883-f0839ef0b1c3.png)
> * PACKAGED (Centennial)
>    * Start Menu
>       * ![image](https://user-images.githubusercontent.com/14316954/63114004-99c6bd80-bf48-11e9-8050-ce5fcdf9ed59.png)
>    * shell:appsfolder
>       * ![image](https://user-images.githubusercontent.com/14316954/63114004-99c6bd80-bf48-11e9-8050-ce5fcdf9ed59.png)
>    * From a shortcut marked RUN MAXIMIZED
>       * ![image](https://user-images.githubusercontent.com/14316954/63114004-99c6bd80-bf48-11e9-8050-ce5fcdf9ed59.png)
> 
> As you can see, the centennialized application never receives the show setting. This applies equally well to the App Execution alias.
> 
> Because of this, users who create shortcuts to traditional applications (including "Windows Terminal") distributed via centennialization will not be able to configure them to launch maximized.
> 
> This was reported by a member of the general public.

Would you like me to do more research?

**Comment by miklevin** [comment]
Yes into a workaround. It's unreasonable for the main Microsoft Terminal app that's supposed to be a game changer and a big part of Microsoft's future to not be able to open maximized, LOL!

**Comment by miklevin** [comment]
Maybe just the option of opening in true Maximized from Settings. There naturally needs to be a way to open a Terminal app fullscreen.

**Comment by oblitum** [comment]
Dude I have the same felling, I just downloaded the thing to try it out and my first impression was: where's fullscreen?!

**Comment by miklevin** [comment]
> Dude I have the same felling, I just downloaded the thing to try it out and my first impression was: where's fullscreen?!

How do I launch directly into fullscreen mode is the first thing any real terminal person is going to think, right? If the desktop shortcut isn't the way to do go because of of packaging details, then surely they can add it to the preferences config file.

**Comment by oblitum** [comment]
@mikemaccana [Alacritty works](https://github.com/microsoft/terminal/issues/531#issuecomment-531084700)
