### ISSUE TITLE
Adding multiple items to the "keys"

### ISSUE THREAD

**Issue by pickscrape** [microsoft/terminal#2387]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): 0.3.2171.0

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by pickscrape** [comment]
Apologies for the spam: I accidentally hit submit long before this was fully filled in.

**Comment by DHowett-MSFT** [comment]
@pickscrape you can actually edit bug reports ;p

**Comment by pickscrape** [comment]
Yeah, but it was so early in the process of filling it in, that I was afraid that the junk report would be insta-closed by a bot and forever tainted as a result before I even had chance to finish it off. :)
