### ISSUE TITLE
Adding multiple elements to a "keys" list under "keybindings" causes the entire binding to be discarded

### ISSUE THREAD

**Issue by pickscrape** [microsoft/terminal#2388]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): 0.3.2171.0

Any other software?
```

# Steps to reproduce

1. Edit config.
1. For any keybinding, add an additional key definition to the "keys" list.
1. Close and re-open Terminal
1. See that the entire command has been removed from the "keybindings" section of the config

In my case, I was trying to add shift+insert as an additional paste keybinding. At first, I though the problem was an incorrect key specification on my part, but using "shift+insert" as the sole keybinding worked fine.

# Expected behavior

At the very least, I would expect both the keybinding element, and the first item in the "keys" list, to be maintained.

Ideally, all keybindings in the list would work to activate the function (assuming no conflicts with keybindings in other functions).

# Actual behavior

The entire keybinding element is removed

**Comment by DHowett-MSFT** [comment]
So this is pretty interesting. The right way to add multiple bindings for the same event is to _duplicate the entire binding_ -- that is:

```
{command: "x", keys: [ "y" ]},
{command: "x", keys: [ "z" ]},
```

multiple keys in the `keys` array are actually for key _chording_, like "<kbd>Ctrl+B</kbd> followed by <kbd>E</kbd>". That's not _actually_ supported today, it's just aspirational.

**Comment by pickscrape** [comment]
Oh! Well, that makes sense now that I know it, but it wasn't clear to me at all.

I'm not sure where I should have gone to find that out myself?

**Comment by DHowett-MSFT** [comment]
We could definitely document this better. It'll work a lot better once #1334 is done, though. :smile: Sorry about that.

**Comment by 0xabu** [comment]
I just came here to note that I made the same assumption/mistake at the original submitter. I've never encountered a terminal that used chorded key bindings before (surely there will never be so many actions in a terminal?), so didn't even consider the possibility.

Given that multiple bindings are effectively broken at the moment anyway (#2389) might this design choice be worth revisiting?
