### ISSUE TITLE
vim/nvim background rending highlight color?

### ISSUE THREAD

**Issue by thisguychris** [microsoft/terminal#2391]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Microsoft Windows [Version 10.0.18950.1000]     

Windows Terminal version (if applicable):
Version: 0.3.2142.0

Any other software?
vim/nvim
Ubuntu 18.04.2 LTS
```

# Steps to reproduce

forwarding a long document in vim/nvim via ctrl-f and then going backward via ctrl-b renders background incorrectly.

link to my [dotfiles](https://github.com/thisguychris/dotfiles)

# Expected behavior

The background should use the theme's background

# Actual behavior

The background is using highlight color for vim/nvim?
![Alt text](https://monosnap.com/image/DLBI4thaStPvP8gbJcn6m6bleiPBvp)
![Alt text](https://monosnap.com/image/hBnJnOOWsxG28kt1oDaYNhsPNpgQiT)

I also posted to the theme author:
https://github.com/haishanh/night-owl.vim/issues/23

Also related to #832 

## Note:
Doing `:redraw` or `Cltr-L` in vim fixes the background issue.

**Comment by DHowett-MSFT** [comment]
This isn't just related to #832, it's _the same as_ it! Thanks for the footwork.

**Comment by thisguychris** [comment]
@DHowett-MSFT is it really similar? Non of the workarounds posted in that thread work :(. Some even suggested its not a conhost issue?

**Comment by thisguychris** [comment]
@DHowett-MSFT 
Hey, just want to update you. So I recently updated to Version: 0.3.2171.0 and it seems that it's not giving me the blue background anymore:

![Alt text](https://monosnap.com/image/LjACLtjQCUxeGBGKnMUC4WaM4dGMh6)

**Comment by DHowett-MSFT** [comment]
I'm alarmed that it went away.
