### ISSUE TITLE
Use visual layout for moveFocusX target

### ISSUE THREAD

**Issue by richardszalay** [microsoft/terminal#2398]
# Description of the new feature/enhancement

Currently `moveFocus{Up,Down,Left,Right}` appears to move based on how the panes were split rather than what is visibly adjacent to the current pane.

Here's a screenshot to illustrate. The red are the `moveFocus{Up,Down,Left,Right}` commands I'm using and the change in focus (1, 2, 3, 4), and green is how I'd expect it to work.

I've added this is a feature request rather than a bug since it may just be personal preference:

![wt-movepane](https://user-images.githubusercontent.com/229467/62846099-b7a9dd80-bd10-11e9-9fa0-58b30660adf4.png)

# Proposed technical implementation details (optional)

Focus the first pane that first collides with the vector from the current window (top-left corner? cursor location?) in the direction of the command.

**Comment by zadjii-msft** [comment]
Hmm. this does seem better, and it looks like tmux does it this way, so it must be possible.
