### ISSUE TITLE
Vietnamese IMEs don't work

### ISSUE THREAD

**Issue by phuclv90** [microsoft/terminal#2406]
# Environment

```none
Windows build number: 0.3.2171.0
Windows Terminal version (if applicable): 0.3.2171.0

Any other software?
```

# Steps to reproduce

1. Open Windows Terminal
2. Change to any of the Vietnamese input methods and type

# Expected behavior

* Vietnamese texts being entered

# Actual behavior

* For the [Vietnamese keyboard layout](https://en.wikipedia.org/wiki/QWERTY#Vietnamese), only the keys 2, 3, 4 work and produce âêô. A few diacritic keys work but produce the separate diacritics instead of combining them into the base letter. The remaining keys failed to work and produce `?` or the letters with diacritics removed
* For the Vietnamese number based and Telex input methods, nothing works

**Comment by DHowett-MSFT** [comment]
#2213

**Comment by phuclv90** [comment]
@DHowett I've already seen that ticket long time ago and I don't believe it's a duplicate. Vietnamese isn't typed like Chinese because it uses Latin charactesr

**Comment by DHowett-MSFT** [comment]
If it uses any type of “input method”, it is a duplicate of that bug :smile:
