### ISSUE TITLE
Dialog overlay does not resize with window

### ISSUE THREAD

**Issue by jmlee2k** [microsoft/terminal#2408]
# Environment

```none
Windows build number: 10.0.18362.267
Windows Terminal version (if applicable): 0.3.2171.0
```

# Steps to reproduce
Open the about dialog, then resize the window.

# Expected behavior
The overlay should resize to cover the window.

# Actual behavior
The overlay does not resize with the window.

![image](https://user-images.githubusercontent.com/7396545/62880871-67288500-bcfc-11e9-986f-9fe83c690f3e.png)

**Comment by DHowett-MSFT** [comment]
This looks like #2380.
