### ISSUE TITLE
Settings file being reformatted when settings are changed by the program

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#2411]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0                                                                                                                                                                                     

Windows Terminal version: latest from the master branch

Any other software?
N/A
```

# Steps to reproduce

With the terminal closed, do anything that trigger a json settings file rewrite, for example, add any setting to the settings json file that is not on the schema (or is invalid), for example:

````json
{
    "Foo": 1,
    "globals" :
    {
````

Then, open the terminal

# Expected behavior

Terminal warns me somehow, or comments out the invalid setting. But does not, ever, reformat the file.

# Actual behavior

The settings file is rewritten and reformatted, and, worse of all, an annoying trailing space is added to the end of every json key. See image bellow:

![CodeSettingsFile](https://user-images.githubusercontent.com/334958/62889785-6dc4f580-bd18-11e9-8b9a-dceb89684bfe.gif)

**Comment by DHowett-MSFT** [comment]
Getting rid of this behavior is a critical (and already called out!) part of the work specified in #1258. :smile:

**Comment by egmontkob** [comment]
The Actual vs. Expected behavior sections are swapped, aren't they?

**Comment by giggio** [comment]
Yes, fixed, thanks.

**Comment by DHowett-MSFT** [comment]
@zadjii-msft got rid of settings reserialization recently. :smile:
