### ISSUE TITLE
Start new Tab with multiple profiles in panes

### ISSUE THREAD

**Issue by Tobsel** [microsoft/terminal#2416]
It would be cool to be able to define a profile containing other different profiles that open up in a single tab an there in multiple panes (right / left etc.)

![image](https://user-images.githubusercontent.com/53915293/62897211-14c68300-bd53-11e9-8113-d4b52cea02d1.png)

**Comment by DHowett-MSFT** [comment]
This is another shade of #756, even though it says "multiple tabs."
