### ISSUE TITLE
Add Glyphs to Cascadia Code Font

### ISSUE THREAD

**Issue by isaac2004** [microsoft/terminal#2421]
I know the font will have it's own repo, but wanted to track this feature here until that repo is available. :)

# Description of the new feature/enhancement

Have glyph functionality in Cascadia code (similar to UbuntuMono for instance)

![image](https://user-images.githubusercontent.com/8878502/62954528-8f2bed00-bdbd-11e9-8041-e05753e283c0.png)

Existing Cascadia Code Font

![image](https://user-images.githubusercontent.com/8878502/62954716-dd40f080-bdbd-11e9-85ff-96df8c774882.png)

# Proposed technical implementation details (optional)

Cascadia Code Font would leverage existing OSS glyph source (like [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/))

**Comment by zadjii-msft** [comment]
@cinnamon-msft

**Comment by DHowett-MSFT** [comment]
Given that all characters represented in a font are _glyphs_, we'll need to break these out into more specific issues about exactly which glyphs (and hopefully the codepoints to which they should be attached) you want us to support.

**Comment by ExE-Boss** [comment]
I’ve opened #2437 for adding **PowerLine** symbols.

**Comment by DHowett-MSFT** [comment]
If somebody can find a good informative source on what these glyphs should be, how they should look, etc. I'd love to port this to the font repo once it's live. Otherwise, this isn't really actionable?

**Comment by DHowett-MSFT** [comment]
n.b. i've already done this for powerline.

**Comment by isaac2004** [comment]
@DHowett-MSFT Does this satisfy what you are looking for?

https://github.com/ryanoasis/nerd-fonts#glyph-sets

If you look at option 8

> Option 8: Patch Your Own Font
The option for patching your own font or fully customizing the patched font.
> Use the provided Python command line script to generate a patched font from your own font to get the extra new glyphs

**Comment by xtremeperf** [comment]
[](https://github.com/powerline/fontpatcher/blob/develop/fonts/powerline-symbols.sfd)

**Comment by mdtauk** [comment]
In an ideal world, part of the Open Source process for Cascadia Code, would include a tool/web app, which would allow people to submit glyph suggestions (with visual examples or even a "build your own glyph" tool based on maybe a 16px grid - which the font design team could then look at, evaluate, and decide on.

**Comment by DHowett-MSFT** [comment]
Now that [cascadia code is open](https://github.com/microsoft/cascadia-code), these requests belong there. Thanks for playing!

**Comment by ExE-Boss** [comment]
@bdw429s I’ve been subscribed to microsoft/cascadia-code#10 since the font’s public beta was released.
