### ISSUE TITLE
New tab needs to have the same user elevation

### ISSUE THREAD

**Issue by maxiledesma** [microsoft/terminal#2428]
If i run the terminal as administrator, the new tab doesn't have the same elevation and run as an normal user. The new tab should be runing as an administrator or give the option to create a new tab as an administrator.

**Comment by DHowett-MSFT** [comment]
All tabs run at the same elevation level. How did you determine that the new tab did not?

**Comment by maxiledesma** [comment]
I tested a couple of times and i missunderstood the results. Closing the issue.
