### ISSUE TITLE
WIndows Terminal (Preview) is missing, even though it's still installed

### ISSUE THREAD

**Issue by tksunw** [microsoft/terminal#2429]
# Environment
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

### Windows Terminal version (if applicable):

The most recent version from the Windows Store.

# Steps to reproduce
Can be reproduced by searching for `wt.exe`, and in search results, clicking the `Open File Location`  option.  This will open a File Explorer window in the `%LOCALAPPDATA%\AppData\Local\Microsoft\WindowsApps` folder.  From there double-click on wt.exe to execute.

# Expected behavior

I expected the Windows Terminal (Preview) application to open. 

# Actual behavior

Windows seems to think the file doesn't exist, even though it's quite visible in the File Explorer.
![wt-error](https://user-images.githubusercontent.com/497321/63046141-da1e3100-be9f-11e9-9456-43b3d82395b1.png)

The windows "Settings -> Apps" dialog is unable to open Advanced options for the Windows Terminal (Preview) app.  Attempting this causes the Settings app to crash.  It is also unable to uninstall the app.

The Windows Store app is unable to uninstall, launch, or reinstall the Windows Terminal (Preview). The installation failure only leaves a very generic message in the System event log:
```
Installation Failure: Windows failed to install the following update with error 0x80004005: 9N0DX20HK701-Microsoft.WindowsTerminal.
```

If I try to launch the Windows Terminal (Preview) by clicking the icon on the taskbar, the desktop, or the Start Menu, the Application event log receives the following event:
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1907.2001, time stamp: 0x5d1bd2d0
Faulting module name: ucrtbase.dll, version: 10.0.18362.267, time stamp: 0x080a13f7
Exception code: 0xc0000409
Fault offset: 0x000000000006d33e
Faulting process id: 0x391c
Faulting application start time: 0x01d552cf45d41bc7
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: cf0aa6d1-c581-4144-a460-a25512a48bd9
Faulting package full name: Microsoft.WindowsTerminal_0.3.2171.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

I have verified on other computers, that running `wt.exe` from the LOCALAPPDATA directory does work as expected.

I have tried removing the profiles.json file, which has enabled me to work past previous "crash on start up" issues, but it didn't work this time.

Attempting to run `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe` by hand from a terminal simply results in an access denied error.
```
Program 'WindowsTerminal.exe' failed to run: Access is deniedAt line:1 char:1
+ & 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ & 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1831.0_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by PseudoResonance** [comment]
I have the same issue and the "Fix Windows Store Apps" troubleshooting thing doesn't fix the issue either.

**Comment by tksunw** [comment]
Fix Windows Store Apps did nothing for me either.  Except it did lead me to a Settings Dialog for Apps, but clicking on the Advanced Options for Windows Terminal Preview just caused the whole Settings app to crash.

**Comment by tksunw** [comment]
I was able to resolve the issue by creating a zip archive of the two `WindowsApps\*WindowsTerminal*` directories from another computer, and unzipping them in my local WindowsApps directory.

```
PS C:\Program Files\WindowsApps> dir *Terminal*

    Directory: C:\Program Files\WindowsApps 

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/16/2019  11:54 AM                Microsoft.WindowsTerminal_0.3.2171.0_x64__8wekyb3d8bbwe
d-----        8/16/2019  11:54 AM                Microsoft.WindowsTerminal_2019.806.135.0_neutral_~_8wekyb3d8bbwe

```

Expanding the archive into my local `C:\Program Files\WindowsApps\` has resulted in a working Windows Terminal (Preview) app.   I still can't see the Advanced Options dialog in the Apps section of the Settings app, but I've sent that as separate feedback to the Windows Store team.
