### ISSUE TITLE
BUG REPORT: Terminal doesn't keep cmd.exe's color setting

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/terminal#2430]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.3.2171.0

Any other software?
cmd.exe
```

# Steps to reproduce

1. Start WT using `cmd.exe`
2. Type in a command to change the background color, such as `color 90` (light blue background, black text)
3. Observe with satisfaction that the screen turns blue, with black text
4. Hit the enter/return key a couple of times
5. Look on in disappointment as you see that all the new lines you just added kept the original background color instead of using the blue background with black text like we told `cmd.exe`.

# Expected behavior

The entire screen should have a blue background, with black text 
(This would be consistent with what cmd.exe does on it's own)

# Actual behavior

The new lines keep the original background color instead of keeping the blue background with black text.
It's worth noting that _the parts of the lines that cmd.exe prints (such as the prompt) are formatted correctly - blue bg with black fg_

**Comment by DHowett-MSFT** [comment]
Thanks! This is some of #2089 and #832 and #1036.
