### ISSUE TITLE
PowerShell Core crashs when app is closed

### ISSUE THREAD

**Issue by jeffrson** [microsoft/terminal#2431]
# Environment

```none
Windows build number:  10.0.18362.207
Windows Terminal version (if applicable): 0.3.2171.0
PowerShell Core: 6.2.2, 7.0preview2
```

# Steps to reproduce

Open terminal with PowerShell Core, close app (click "x" top right)

# Expected behavior

Application closes without any (obvious) issue....

# Actual behavior

Visual Studio as JIT debugger is triggered and reports this unhandled exception of pwsh.exe:
System.InvalidOperationException: "Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read."

**Comment by DHowett-MSFT** [comment]
This was fixed with #2198, which has not yet been released.
