### ISSUE TITLE
Terminal crashes on showing docker status

### ISSUE THREAD

**Issue by belyaev-andrey** [microsoft/terminal#2434]
# Environment
```
Windows Terminal (Preview)
Version: 0.3.2171.0

Platform ServicePack Version      VersionString                                                                         
-------- ----------- -------      -------------                                                                          
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0                                                     

Docker for Windows 
Version 2.1.0.1(37199)
Channel stable

h2 database image running in docker
```

# Steps to reproduce
1. Start Windows Terminal (Preview) with PowerShell as a default environment
2. Open Linux Ubuntu tab as a second tab
3. In the second tab execute `ls` command
4. Close the second tab
5. In the first tab execute `docker ps` command

# Expected behavior
Docker list of running images is shown

# Actual behavior
`CONTAINER ID` is printed in the console and then the terminal window closes.

Logs attached: [Terminal.zip](https://github.com/microsoft/terminal/files/3504587/Terminal.zip)

**Comment by zadjii-msft** [comment]
So I'm going to go out on a limb here - this doesn't repro if you take out steps 2, 3, and 4, right? Just running `docker ps` works fine, correct?

**Comment by belyaev-andrey** [comment]
Correct. If I just execute `docker ps` in the power shell without opening the linux terminal, it works fine.

**Comment by zadjii-msft** [comment]
Fantastic. I'm 80-90% sure that this is a dupe of _#the-bug-fixed-by_ #2198, and it might also be #2394

**Comment by zadjii-msft** [comment]
This might also be #2525 or even #2375

**Comment by DHowett-MSFT** [comment]
It's been a very long time since this was reported. Is it still happening?

**Comment by belyaev-andrey** [comment]
Looks OK to me now.
