### ISSUE TITLE
Cascadia Code: Add PowerLine symbols

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/terminal#2437]
## Description of the new feature/enhancement
[PowerLine](https://github.com/powerline/powerline) is a custom shell prompt, with [an implementation for PowerShell](https://github.com/Jaykul/PowerLine).

## Proposed technical implementation details (optional)
**Cascadia Code** would include [the **PowerLine** glyphs](https://github.com/powerline/fontpatcher/blob/develop/fonts/powerline-symbols.sfd).

**Comment by DHowett-MSFT** [comment]
Thanks for linking these up. In the interest of making our jobs easier when we do get Cascadia Code into its own repository, I'm going to close this out and migrate #2421 as a number of different issues.
