### ISSUE TITLE
Settings get shared between Windows devices and causes configuration problems

### ISSUE THREAD

**Issue by rrmistry** [microsoft/terminal#2439]
# Environment

```none
Windows build number: 10.0.18362.0

Details:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
Ubuntu 18.04 WSL
Anaconda/Miniconda
```

# Steps to reproduce

1. Install [*Windows Terminal (Preview)*](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) through the *Microsoft Store* on two separate Windows devices
   **IMPORTANT**: Use the same credentials in the Microsoft Store on both devices
2. Change settings on one device (e.g. add a new profile to start in drive `D:\` )
3. Change the settings on the other device (e.g. add the same profile but use drive `E:\`)

# Expected behavior

Configurations stay local to the device being configured on

# Actual behavior

* Configurations get shared between devices
* It is also not predictable when the configuration gets updated from the other device

# My use case
I had created a new profile for *Anaconda* on my desktop but I used *Miniconda* on my laptop. I was surprised to see that these profiles kept getting shuffled around.

The same happened with Ubuntu WSL, which I have manually installed on a different drive through Powershell.

# Minor workarounds
* Use environment variables in profile configuration 😄 
* Have duplicated profiles with proper path and drive mappings per device 😐 
* Install software in paths consistent across devices 😢 , etc. etc.

**IMHO**, this feels like a bug because I expected profiles to be created specific for each device. Though I suspect that the config file sharing is a feature of the Microsoft Store app platform and working as expected.

It would be nice to see this working as expected, but I'm OK if not possible. At least wanted to raise awareness about this behavior. Thank you!

**Comment by zadjii-msft** [comment]
Wadda ya know, this was already fixed by #2298! It'll be in the next release :)
