### ISSUE TITLE
Bug Report: Invalid DefaultProfile returns wrong warning

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2440]
# Environment

After PR #2422 

If I change the defaultProfile to an invalid guid, I get "No profiles were found in your settings.".

# Expected behavior

Something a bit more specific like "GUID is invalid"

# Actual behavior

"No profiles were found in your settings."

**Comment by zadjii-msft** [comment]
You know, this was fixed when we started allowing names in the `defaultProfile` property. Now it just gives you 

![image](https://user-images.githubusercontent.com/18356694/129954046-7372385b-622b-4bf3-a10f-f5ca2c897d6a.png)


which makes sense
