### ISSUE TITLE
Bug Report: splitVertical should duplicate opened shell instead of defaul

### ISSUE THREAD

**Issue by guibirow** [microsoft/terminal#2442]
This is related to the #1000 - Deliverable: Add support for panes

Currently, when a new pane is opened by splitting the window, the default shell is opened instead of an instance of same shell already open in the side pane.

I would expect the window to be split using the same shell, maybe have a separate command to split using the default shell.

# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.3.2171.0

Any other software?
WSL 1 (Ubuntu) (Default shell in Win Terminal)
```

# Steps to reproduce

Open a non default shell (In my case CMD, because WSL is the default)
Press the shortcut for command **splitVertical** (ctrl+shift+\\)
The pane will split and 

# Expected behavior

Open a new pane of same shell 

# Actual behavior

The default shell is opened in the new pane

**Comment by zadjii-msft** [comment]
Literally in #1000:

> #1756 The user should be able to configure what profile is used for splitting a pane. Currently, the default profile is used, but it's possible a user might want to create a new pane with the parent pane's profile.
