### ISSUE TITLE
Feature Request: "Paste" should focus and paste

### ISSUE THREAD

**Issue by flindeberg** [microsoft/terminal#2444]
# Description of the new feature/enhancement

Using the mouse paste mechanism (regardless of right mouse, middle mouse or whatever mouse) on an unfocused terminal window / split-pane should focus _and_ paste. Currently it focuses on windows and does nothing on panes.

Paste in window is currently: right click (or well, left click works as well for focus) + right click. Paste in split-panes is: left click + right click. 

I only want to click once (regardless of middle mouse or right mouse or doing a rain dance in front of the camera) and not several times to paste text. 

Also belong together with #524 function and use wise, since no-click-copy and single-click-paste are two of the best mechanisms out there 👍 

# Proposed technical implementation details (optional)

I haven't looked at the cose base, but I imaging it is a case of looking at how mouse-events are handled in focused contra unfocused windows and split-panes.

**Comment by richardszalay** [comment]
Related: You cannot copy text from an unfocused pane without first focusing it. If you try, nothing happens.

(I would think that both these issues could potentially be resolved by focusing on mousedown rather than click)

**Comment by carlos-zamora** [comment]
This got fixed. I have no idea when though. I recall working with @leonMSFT on this back when we were at the office.

I can't seem to find the PR that actually fixed it though.

**Comment by carlos-zamora** [comment]
Leon found it: https://github.com/microsoft/terminal/pull/4506
