### ISSUE TITLE
Allow profiles to have arguments member that can be used that can be used as parameter to underlying text application

### ISSUE THREAD

**Issue by lon3wolf** [microsoft/terminal#2445]
Sample profile for cmd.exe for example (Bold is the what I want)
{
            **"arguments" : "f:\GIT\Tools\Razzle.cmd x64fre",
            "startingDirectory" : "f:\GIT",**
            _"name" : "Razzle",
            "commandline" : "cmd.exe",_
            "acrylicOpacity" : 0.75,
            "closeOnExit" : true,
            "colorScheme" : "Vintage",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 11,
            "foreground" : "#00FF00",
            "guid" : "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : true
        },

**Comment by DHowett-MSFT** [comment]
?

```
"commandline": "cmd /k f:\git\tools\razzle.cmd x64fre"
```

**Comment by lon3wolf** [comment]
I have tried this and tried again, the arguments are completely ignored, also the startup directory doesn't change

![image](https://user-images.githubusercontent.com/10262489/63131563-05258500-bf73-11e9-9311-83f2a7d9a488.png)

![image](https://user-images.githubusercontent.com/10262489/63131574-11a9dd80-bf73-11e9-94f5-ca68bcf6510d.png)

**Comment by DHowett-MSFT** [comment]
If you're seeing settings not changing, you should 100% check to make sure you haven't duplicated your `guid` :wink:

**Comment by DHowett-MSFT** [comment]
An easy to way to reset the guid is to just delete it.
