### ISSUE TITLE
Command "Cmder" always opens in a separate window instead of tabbed shell

### ISSUE THREAD

**Issue by hanuk** [microsoft/terminal#2448]
I configured "Cmder" as a shell command and it always opens outside tabbed shell.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
Cmder is another terminal emulator. It’s a GUI application. Launch the actual shell you want to use instead.

**Comment by bastienlemaitre** [comment]
https://gist.github.com/bastienlemaitre/b59aa44b7db6a66551c950a06df88e98
