### ISSUE TITLE
Terminal colors disappear after setting the acrylic to "true" (KaliLinux)

### ISSUE THREAD

**Issue by BMoon945** [microsoft/terminal#2451]
The title is clear. 
Windows build: 1903
I've downloaded the terminal in 16/08/2019 (GMT+3)

First i choose the kali linux. There was no problem. The colors were fine. And then i wanted to add it the acrylic transparency. I've changed the "useAcrylic" value at the .json file. And i've set the opacity to 0.75. When i launch the terminal again acrylic was working. But the terminal colors had disappeared. Now it's black and white. With a good acrylic transparency background.

**Comment by BMoon945** [comment]
I don't know if this issue is related of the terminal. I've set the values back to their defaults and the colors didn't come back. So, it may not be caused by the terminal's acrylic feature.

**Comment by zadjii-msft** [comment]
Could you add your `profiles.json` and a screensoht of what's occurring? What's your `TERM` set to in your Kali instance?

**Comment by BMoon945** [comment]
I've reinstalled the app. And the colors were still missing. So i've launched the kali terminal and have seen that it doesn't have colors, either. I think that's not the problem of the w. terminal. (But i'm sure at the first launch there was a blue colored line. Then when i wanted to change the settings it has disappeared. ) So, i'm going to close the issue page. Thanks for the attention.
