### ISSUE TITLE
The terminal crashed

### ISSUE THREAD

**Issue by pitaohc** [microsoft/terminal#2452]
# BackgroundImage & Drag to under the taskbar
I tried to customize my terminal with a GIF at the rightRight. It looks so normal before I drag him to under the taskbar. When I did it, actually it is the GIF under the bar, its window got dark and I couldn't do anything with it except close it.

**Comment by zadjii-msft** [comment]
Could you share your `profiles.json` and the gif in question? Maybe add a screenshot of what's happening?

**Comment by pitaohc** [comment]
Today, I tried it again. But it is different.
**1.**The question is similarly due to the GIF.
**2.**When I try it again, the GIF disappointed. But I didn't do anything.
**3.**I think it has a closer relation with draging and droping than taskbar.
**4.**There are some evidences in the ZIP.My profile, two GIFs, a screenshot and a vedio
[evidence.zip](https://github.com/microsoft/terminal/files/3511376/evidence.zip)

I hope they can help you to fix the problem.😁

**Comment by DHowett-MSFT** [comment]
SORRY
