### ISSUE TITLE
Cannot use miniconda in terminal.

### ISSUE THREAD

**Issue by soerendip** [microsoft/terminal#2453]
Hi, 

it seems miniconda is not working with the terminal. I added the condabin directory to the windows path. `activate` is found, but when I activate a particular environment by running `activate mint`, and type `which python` the terminal returns `

> C:\Users\<Username>\AppData\Local\Microsoft\WindowsApps\python.EXE

Which is actually not even a python version!

**Comment by DHowett-MSFT** [comment]
If you’re using miniconda from powershell please make sure you are following the miniconda powershell instructions. The CMD instructions won’t work from powershell.

**Comment by kliberty** [comment]
@soerendip 

I was able to add a Conda tab by editing the settings file with the entry below. I wasn't sure what to use for a GUID so I copied one of the others and changed a few numbers, YMMV.

```
{
    "acrylicOpacity": 0.5,
    "closeOnExit": true,
    "colorScheme": "Campbell",
    "commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& '%USERPROFILE%/Miniconda3/shell/condabin/conda-hook.ps1' ; conda activate '%USERPROFILE%/Miniconda3' \"",
    "cursorColor": "#FFFFFF",
    "cursorShape": "bar",
    "fontFace": "Consolas",
    "fontSize": 10,
    "guid": "{PUT A GUID HERE}",
    "historySize": 9001,
    "icon": "%USERPROFILE%/Miniconda3/Menu/Iconleak-Atrous-PSConsole.ico",
    "name": "Conda",
    "padding": "0, 0, 0, 0",
    "snapOnInput": true,
    "startingDirectory": "%USERPROFILE%",
    "useAcrylic": false
}
```

**Comment by DHowett-MSFT** [comment]
The GUID doesn’t matter. You can also just delete it and let WT generate a new one for you.

**Comment by soerendip** [comment]
What is WT? I am talking about the thing that is called Terminal that is supposedly the new Windows Subsystem for Linux.


________________________________

**Comment by DHowett-MSFT** [comment]
WT is windows terminal, and it is _not_ the new Windows Subsystem for Linux. It is a new terminal where you can _use_ WSL, WSL2, cmd, powershell, bash, whatever you want.
