### ISSUE TITLE
Bug Report: Cannot find profile --> Crash

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2455]
# Environment

Introduced by #2422 

Since we'll be defaulting to the Windows Terminal default settings, this means that the user may be working with profiles that don't exist AFTER the proper settings are imported. Below is an example of such a case, but several other places may cause the same issue to arise.

I'd bet that this is because we usually use "FindProfile()" (or something like that) and we just don't handle that properly.

# Steps to reproduce

- create a tab from the WT default settings
- import your custom settings
- duplicate the created tab

# Expected behavior

Not sure. Maybe a dialogue box saying "This operation could not be completed"?

# Actual behavior

CRASH!

**Comment by zadjii-msft** [comment]
for the record, I don't think this was introduced in #2422, this probably dates back to pre-open source, when we started falling back to the default profiles if the settings were invalid. This just makes it more apparent, because we crash less aggressively.
