### ISSUE TITLE
terminalapp, terminalconnection: use `cppwinrt_utils.h` macros where possible

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2456]
# Description of the new feature/enhancement

Make sure we're using the `cppwinrt_utils.h` macros everywhere we can. And if we have a lot of repeated code in some places, feel free to introduce new macros.

**Comment by DHowett-MSFT** [comment]
I 100% think we should kill cppwinrt_utils and make it an include in the winrt types library from #2146. We can then make sure that library is _on the include path_ for all C++/WinRT things automagically, so we don't need to use this annoying relative path include..
