### ISSUE TITLE
Version: 0.3.2171.0无法使用中文输入法

### ISSUE THREAD

**Issue by deng104** [microsoft/terminal#2459]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by TayYuanGeng** [comment]
P.s. "无法使用中文输入法" = "Unable to input Chinese characters"

**Comment by zadjii-msft** [comment]
Thanks @TayYuanGeng!

Presumably, this is a dupe of #2213

**Comment by ketchuppp** [comment]
将win10打开设置，**时间和语言→语言→管理语言设置→更改系统区域设置→勾选Beta...提供全球语言支持**，然后重启，再打开windows terminal即可使用中文输入。然后神奇的事情发生了，即使此时关闭当时的勾选，再次重启仍可在windows terminal使用中文输入法。
原因不明，但有效。
