### ISSUE TITLE
Bug Report - Chinese input method failed

### ISSUE THREAD

**Issue by weichzh** [microsoft/terminal#2460]
# Environment

```none
10.0.18362.0
Windows Terminal (Preview)
Version: 0.3.2171.0
Microsoft Pinyin IME or other Chinese IME
```

# Steps to reproduce

Just use a Chinese IME, then type.
Win + . can't print any symbol.

# Expected behavior

the console should print Chinese characters.

# Actual behavior

just print latin letters.

**Comment by TayYuanGeng** [comment]
This is similar to #2459

**Comment by zadjii-msft** [comment]
This is also a dupe of #2213
