### ISSUE TITLE
Unwanted characters printed when scrolling over non-alphanumeric characters when using tmux and emacs

### ISSUE THREAD

**Issue by mbelmadani** [microsoft/terminal#2463]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): Version: 0.3.2171.0

Any other software?
GNU Emacs 24.3.1
tmux1.8
CentOS 7.0
```

# Steps to reproduce

When I ssh to my CentOS 7.0 server and start a new tmux session (`tmux new-session -s someSession`), and open a new or existing file in emacs, every time I move my cursor on a white space or special character, I get a unwanted square character printed on the screen. Some characters are already there (e.g. on empty lines) when I first open the file. The changes are only visual and don't modify the actual text file (i.e. saving and re-opening the file clears the new characters) but those that are there when the file opens appear consistently, generally in empty lines.

If I try with emacs outside of tmux it works fine, so it seems to be specific to tmux or one of its setting.

I did try to set my `$TERM` to xterm-256color, rxvt, etc. in the tmux configs but it didn't seem to change anything. 

# Expected behavior
The text file should display as is without any additional characters, e.g.

![image](https://user-images.githubusercontent.com/14117454/63214587-01a71080-c0cf-11e9-9ef6-618b3add0e62.png)

# Actual behavior

See screen shot and additional square characters:
![image](https://user-images.githubusercontent.com/14117454/63214584-ec31e680-c0ce-11e9-809f-a021e9b1aa38.png)

**Comment by zadjii-msft** [comment]
Can you try reproing this with the console (conhost.exe) instead of the Windows Terminal? You can get a conhost window by just opening wsl.exe directly. 

This seems extra suspicious that it doesn't repro w/out tmux, but it'll certainly help narrow down our investigation if it's Windows Terminal specific o if this repros in conhost too.
