### ISSUE TITLE
Option to copy on Enter key-press like classic console QuickEdit mode

### ISSUE THREAD

**Issue by nguerrera** [microsoft/terminal#2464]
# Description of the new feature/enhancement

Going back many years, as long as QuickEdit mode was enabled, you could use the following workflow to copy/paste

1. Make selection with mouse and left button
2. Press Enter to Copy
3. Right click to paste

I'm aware that step 2 can be done in both classic and new terminal using right click instead of Enter. I'm further aware that that is more efficient, but I was taught to press enter over a decade ago and I can't shake the muscle memory. I have been committing unfinished commands at step 2 and pasting prior junk like whole documents as commands at step 3 since adopting the new terminal. It would be great if there was a way to make it tolerate my sub-optimal technique. 😄 

I would like an option to make Enter copy when I have a selection, just like right click does now.

**Comment by DHowett-MSFT** [comment]
I have a feeling that now that #2446 is merged, this will just work if you add a key binding with command=`copy` keys=`enter`. Once we fix #2389, you can even keep it alongside `ctrl+shift+c`!

**Comment by nguerrera** [comment]
@DHowett-MSFT Would I need to build from source to confirm that or is that already worth trying on what I got from the store?

**Comment by DHowett-MSFT** [comment]
For that one, you'll need to build from source. Sorry about that! We're tracking for a new preview release "pretty soon," though.

**Comment by nguerrera** [comment]
No worries at all! I'll wait a bit. Thanks!

**Comment by carlos-zamora** [comment]
Just tested it on `master` and @DHowett-MSFT is correct! You'll have to add the following keybinding:
```
{
    "command": "copy",
    "keys": [
        "enter"
    ]
}
```
It's available if you build from `master` or in the next release. Thanks!

**Comment by nguerrera** [comment]
Works like a charm, thanks!
