### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by loxal** [microsoft/terminal#2466]
Your bot closed my feature request!

I mean does this feature request really need further elaboration beyond its title? 

Ok, I propose that you use Qt, distribute DEB packages and support other major package formats. Also provide a Snap! Ok, I hope I satisfied your bot now.

**Comment by imjasonmiller** [comment]
I am not affiliated with the team here, but you can use the query `linux in:title` to find that similar issues have been submitted, see #624, #563 and #504.

**Comment by egmontkob** [comment]
See also #2331.

**Comment by zadjii-msft** [comment]
Yea I'm going to close this as a dupe of the countless other issues we've already closed for the exact same ask. Please search before filing new issues.
