### ISSUE TITLE
Severe memory leak with Desktop Window Manager

### ISSUE THREAD

**Issue by radu-matei** [microsoft/terminal#2468]
# Environment

```none
Windows build number: Windows [Version 10.0.18963.1000]
Windows Terminal version (if applicable): installed from Store

Any other software?
Ubuntu on WSL2
```

# Steps to reproduce

- open an Ubuntu tab in the Terminal

- the memory allocated to the Desktop Window Manager starts growing 

- it grows at a rate of around 1 GB / 10 seconds without stopping

![image](https://user-images.githubusercontent.com/13103165/63218560-3fa34380-c166-11e9-8836-efb1f8d7b459.png)

- closing the WSL2 tab and opening another one (PowerShell for example), the issue goes away.
- using the same WSL2 distro and shell from another terminal app (VS Code, for example), issue is not present.

Just upgraded to 18963, mostly similar setup worked fine for 18950.

EDIT: The issue goes away after turning `useAcrylic` off.

**Comment by DHowett-MSFT** [comment]
Actually, we’ve been seeing reports of this on newer insider builds of windows regardless of WT being used :smile: thanks!

**Comment by radu-matei** [comment]
Assuming WT is Windows Terminal.

At least in my current scenario, the issue seems to be directly connected to using _some_ transparency settings?
If you think it's not related to the terminal, feel free to close the issue.

Ok, I'll either try to reproduce with other apps that have transparency settings, or really stay away from transparency 😄

**Comment by radu-matei** [comment]
FWIW, I created an [issue in the Feedback Hub](https://aka.ms/AA5vuqw) - if anyone else experiences this, disabling all transparency settings is a known workaround.
