### ISSUE TITLE
Update Accessibility Model to use `wil`

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2474]
# Description of the new feature/enhancement

We currently manually keep track of our own RefCount for our accessibility providers. This can cause improper RefCounts and updating, as well as improper transferring of ownership.

We should be using the `wil` library to fix these issues. Starting by making references `wil::com_ptr`s. This probably won't be too bad for Windows Terminal. We'll have to update some ConHost code too.

**Comment by DHowett-MSFT** [comment]
And WRL!

**Comment by DHowett-MSFT** [comment]
Moving this out to 1911. Splitting it into a fix for #3209.
