### ISSUE TITLE
Unwanted scrolling?

### ISSUE THREAD

**Issue by akulbe** [microsoft/terminal#2476]
# Environment

18963

Any other software?
N/A

# Steps to reproduce

This isn't something I've been able to reliably reproduce, but it has happened 3 times to me so far.... switch back from another app, back to Windows Terminal, and the cursor is several lines down from the prompt.

# Expected behavior

I expect the cursor to stay aligned with the last prompt in the session.

# Actual 
See screenshot!
<img width="1920" alt="windows_terminal_scrolling_issue" src="https://user-images.githubusercontent.com/123279/63291739-fee81f00-c278-11e9-9017-d895c60b7da3.png">

**Comment by akulbe** [comment]
I'm sorry for the lame description. I had trouble coming up with better words to describe the issue.

**Comment by DHowett-MSFT** [comment]
This has the same visual effect as #2432; probable duplicate.
