### ISSUE TITLE
guacamole 注册不了

### ISSUE THREAD

**Issue by lvshuishangshang** [microsoft/terminal#2479]
升级到最新版本之后，guacamole一直注册不了，然后导致Windows服务器无法连接了，从guacamole 的docker日志里查看 显示的是 “[Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService 210 - 等待心跳，AccessKey验证未通过”，我启动docker的时候的那个token确实是和jumpserver的配置文件里面的一样的

**Comment by DHowett-MSFT** [comment]
Sorry, I can't figure out how this is a _Windows Terminal_ problem.

**Comment by lvshuishangshang** [comment]
after updating,the jumpserver is the latest version, but i cant connect the windows terminal,and the guacamole's docker log is "[Thread-6] INFO o.a.g.a.j.r.JumpserverRegisterService 210 - 等待心跳，AccessKey验证未通过", the guacamole installed by docker

**Comment by vy12021** [comment]
@DHowett-MSFT I agree.

**Comment by DHowett-MSFT** [comment]
Sorry, I don't think there's anything we can do about this without more info or a good repro?
