### ISSUE TITLE
Possiblity to install on older Windows 10 builds

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2480]
I didn't see any information on _why_ Terminal requires "Windows build 18362 or higher".
Is it likely to become possible in the future?

I enjoy using Terminal on my personal machine.
Unfortunately my workplace has not seen fit to upgrade work machines from 1709 (16299) 😞

**Comment by zadjii-msft** [comment]
You know, there's actually a pile of discussions on this:
 ### https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691
> Sorry. Right now, there's two big blockers to adoption on 1809.
> 
>     * XAML islands was a technology preview and didn't support high-DPI, DPI changes, or accessibility in 1809. We rely on them heavily.
> 
>     * 1903 added support for side-by-side WinRT component activation, something deep in the COM stack that lets us find our DLLs when they're right next to our EXE.
> 
> 
> We just can't go back to 1809.


### https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323
> 
> 
> > the Windows Terminal **REQUIRES** features from the latest Windows release.
> 
> Unfortunately, there's really no workarounds available to us. XAML Islands is the technology we use to host our XAML UI in a Win32 process. Without that, we'd be unable to display anything. Since XAML Islands is only complete as of the latest Windows 10 release, there's nothing we can do about it.
> 
> If you'll want to use the terminal, you'll _need_ to be on the latest Windows 10 version.


### https://github.com/microsoft/terminal/issues/841#issuecomment-492940388

### https://github.com/microsoft/terminal/issues/498#issuecomment-490091740
> 
> 
> There are no plans currently.
> 
> We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.
> 
> Furthermore, our entire build system is MsBuild-based, and I could be wrong, but I don't think our build system will work on linux.


### https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952
### https://github.com/microsoft/terminal/issues/2024#issuecomment-512788360

**Comment by wolf99** [comment]
Apologies for the dupe (I did search beforehand but must not have used the right words!)
And thanks for the information 👍

**Comment by rismoney** [comment]
> There's nothing we can do.

Sounds like the usual non forward thinking Windows folks making crappy limiting technical decisions prevailed.  Oh well.  Not surprised as with blinders on, they can't seem to learn from other open source projects.
