### ISSUE TITLE
Bug Report (Menu doesn't move with window when opened)

### ISSUE THREAD

**Issue by kephax** [microsoft/terminal#2482]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.3.2171.0

```

# Steps to reproduce

Open the dropdown menu, now move the window

# Expected behavior

I expect either the menu to close or the menu to move together with the window.

# Actual behavior

Menu stays on position it was opened while window moves in the background

**Comment by zadjii-msft** [comment]
Wadda ya know, this is already fixed by #2438
