### ISSUE TITLE
Different GIF backgrounds for Different Terminal Profiles

### ISSUE THREAD

**Issue by farmstrong8** [microsoft/terminal#2483]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): v0.3.2171.0

Any other software?
```

# Steps to reproduce

* Create multiple terminal profiles
* Add different gif backgrounds for each terminal profile
* Open them in microsoft terminal

# Expected behavior

* Expected that I can tab through my different terminal windows and see each respective gif play for each terminal.

# Actual behavior

* only the gif background of the default terminal plays, all the others play for few seconds and become still images.

**Comment by zadjii-msft** [comment]
* Could you share your profiles.json with us? (and preferably the gifs in question)
* If you swap the gif for the default profile with another profile's gif, does the other profile's gif magically start looping when applied to the default?

**Comment by farmstrong8** [comment]
I just tried swapping the gifs and it seems the other two don't loop T _ T . Gonna close this issue, thanks!
