### ISSUE TITLE
Terminal couldn't be opened if profile's commandline couldn't be opened (re-open)

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#2484]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18963.1000]
Windows Terminal version (if applicable): commit id 734fc1d
```

# Steps to reproduce

still, like #1404
at the defualt profile, "commandline" can't be opened, terminal starts and right after it shuts down.

Make profile a mistake, like the image under.
![image](https://user-images.githubusercontent.com/29011440/63356452-c6dcfb00-c3a2-11e9-8d34-8c9e7f14bf97.png)

After that, starting a windows terminal, terminal automatically closes without any message.

# Expected behavior
Terminal shows up an error message like #2422 

# Actual behavior
Terminal doesn't show up any error message, just shuts down.

**Comment by wolf99** [comment]
Doesn't #2422 solve this?

**Comment by SJang1** [comment]
@wolf99 It didn't.

**Comment by DHowett-MSFT** [comment]
This is still #982.
