### ISSUE TITLE
Feature Request: Rich Text Format (RTF) Copy

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2487]
# Description of the new feature/enhancement
Copy RTF data from selection. Useful for pasting text over to MS Word (or something similar).

Split off from #1146 for clarity. 

Resources:

Copy and Paste Docs
DataPackage Docs (how to actually save the stuff. This is probably the more important doc)

# Proposed technical implementation details (optional)

So, looking at Clipboard.cpp under ConHost's InteractivityWin32 project, should cover most of what is done. We're just slightly different in that we're using the UWP Clipboard API but that should actually make a lot of it much easier.

The data should already be saved in data in Terminal::RetrieveSelectedTextFromBuffer(bool). We just need to actually save it properly.

**Comment by carlos-zamora** [comment]
HTML copy was accomplished with #1224 . The logic should be pretty similar and will point you in the right direction.

Also adding the Help-Wanted tag in case anybody wants to implement this feature.

**Comment by anirudhrb** [comment]
@carlos-zamora Attempted a PR (#3535) for this. Please have a look.
