### ISSUE TITLE
AzCopy does not work in Terminal

### ISSUE THREAD

**Issue by revpixel** [microsoft/terminal#2489]
Created GUID for AzCopy in PowerShell
Created JSON Template (Below) for Terminal)
Tried Launching AzCopy In Terminal 

AzCopy Does not launch - no errors

Here is the copy of my JSON Profiles Template:

 {
            "acrylicOpacity" : 0.75,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\AzCopy\\AzCopy.exe",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{7eacfb45-78d6-4078-bab2-0215d95a6fac}",
            "historySize" : 9001,
            "icon" : "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\AzCopy\\WAIcon.ico",
            "name" : "AzCopy",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
 }

I've used this format with adding PowerShell 7, Python, Ubuntu WSL and others with no issues. Not sure if this is a bug or a feature request.

**Comment by DHowett-MSFT** [comment]
Couple questions.

1. Do you get any better diagnostics when you set `closeOnExit` to `false`?
2. What happens if you quote the `commandline` down another level (`"\"C:\Path To\AzCopy\AzCopy.exe\""`?

**Comment by revpixel** [comment]
Hey! Close on Exit fixed my issue...

Which then allowed me to figure out how to get it in the terminal working.. That also meant a command line update (see below)  And while it looks a little bit ugly (I need to color the screen blue to make it look better but it works!

		{
            "acrylicOpacity" : 0.75,
            "closeOnExit" : false,
            "colorScheme" : "Campbell",
            "commandline" : "cmd.exe /T:1F /K cd /D C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\AzCopy\\ & launchcmd.cmd",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{7eacfb45-78d6-4078-bab2-0215d95a6fac}",
            "historySize" : 9001,
            "icon" : "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\AzCopy\\WAIcon.ico",
            "name" : "AzCopy",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
        },

It doesn't fill the screen with the AzCopy Blue unless you maximize and restore the window (weird little bug)

**Comment by DHowett-MSFT** [comment]
That'll be a number of different background coloration bugs that we've got tracked. Looks like this one is resolved? :smile:
