### ISSUE TITLE
Ligatures Move around and don't respect spacing

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/terminal#2490]
# Environment

```none
Windows build number: 10.0.18956.0
Windows Terminal version (if applicable): 0.3
```

# Steps to reproduce
Install FiraCode NF or another ligature font
Type ligatures

# Expected behavior
Ligatures when typed, the console will move back appropriately.

# Actual behavior
![LigatureExample](https://user-images.githubusercontent.com/15258962/63381761-3674cb00-c34e-11e9-9638-88f9d97acc77.gif)

**Comment by JustinGrote** [comment]
This appeared to be a transient issue, after a reboot and futzing with the cmd font settings (may be unrelated) the spacing issue appears to have stopped. May be worth investigating still so I'll leave it open.

![LigatureWorks](https://user-images.githubusercontent.com/15258962/63385931-c0c12d00-c356-11e9-9431-e8cf87888c4b.gif)

**Comment by DHowett-MSFT** [comment]
Hey, does this still repro if you type `test ` before the ligature? If so, this might be #633.
