### ISSUE TITLE
Cannot copy nor paste (through RDP from mac)

### ISSUE THREAD

**Issue by will** [microsoft/terminal#2493]
# Environment

![image](https://user-images.githubusercontent.com/1973/63391493-7d22ef00-c367-11e9-8347-822a08ea558b.png)

Sorry for the screenshot and not text, but I can't copy

# Steps to reproduce

Connect to windows from a mac with Microsoft Remote Desktop and the "Use Mac Shortcuts for Cut, Copy, and Paste" option on.

# Expected behavior

Command-c copy, command-v paste. This does work in just powershell, but not in the new Terminal

# Actual behavior

It sends `^C` and `^V`

**Comment by DHowett-MSFT** [comment]
This is just a really fancy way to report #2420 😁 
Please refer to https://github.com/microsoft/terminal/issues/2420#issuecomment-522263775 for some reasoning.

**Comment by will** [comment]
@DHowett-MSFT Do you know what the key name is for the windows key, so I can set it? All the docs and shortcuts I have in there are just `ctrl` `alt` and `shift`. Is it `win` or `windows` or something like that?

**Comment by DHowett-MSFT** [comment]
Command and Win are typically called `meta`, but I don't think WT lets you bind it. Right now, all the Windows key bindings are owned by the OS 😒

**Comment by will** [comment]
Got it thanks. I mean I _could_ press the button to switch my monitor over the workstation and avoid this remapping of keys, but…  😁
