### ISSUE TITLE
Changing "startingDirectory" to /mnt/d (another disk)?

### ISSUE THREAD

**Issue by Paul-00910** [microsoft/terminal#2495]
I have been trying but with "/" terminal opens in "/mnt/c". I want the starting directory to be "mnt/d" or "D:\" of windows, how should i do it?

**Comment by zadjii-msft** [comment]
`startingDirectory` needs to be a Windows path. So instead of `/mnt/d/path/to/directory` try `d:\path\to\directory`.

**Comment by Paul-00910** [comment]
Yeah it works now, thanks. I was confused by the fact that forward slashes are used in the documentation (https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md), which are used in linux paths

Maybe have ""%USERPROFILE%\\wslhome" instead of ""%USERPROFILE%/wslhome"" in the doc? I think it would be more clear
