### ISSUE TITLE
Visual artifacts when using Go Mono Nerd Font at size 11

### ISSUE THREAD

**Issue by blami** [microsoft/terminal#2496]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): 0.3.2171.0
Display resolution: 2560x1440 @ 150%
```

# Steps to reproduce
Install either Go Mono or Go Mono Nerd Font font, change settings to use it and set size to 11.

# Expected behavior
No artifacts visible.

# Actual behavior
A thin line is rendered after every other line. This happens only at size 11. Both smaller sizes (8, 9, 10 tested) and bigger (12, 13, 14, 15 tested) are fine. Size 11 is fine in Hyper.js and also in wsltty.

![terminal-gomononf](https://user-images.githubusercontent.com/435090/63433454-2c41f200-c45e-11e9-8f7f-aca0f781af6e.png)

**Comment by DHowett-MSFT** [comment]
#455
