### ISSUE TITLE
Settings option broken & string for keyboard shortcut is truncated

### ISSUE THREAD

**Issue by ChandanaNT** [microsoft/terminal#2503]
Steps to repro
1. Open the Windows Terminal app
2. Click on the down arrow button in the title bar to open up the menu
3. Click on the Settings option

Version : 0.3.2171.0

Expected behavior
Some sort of panel to modify settings should open up

Actual behavior
No settings panel opens up

I also think the string for the keyboard shortcut for Settings is truncated. This is what I can see 
![image](https://user-images.githubusercontent.com/10185741/63455137-c52a3a80-c469-11e9-9ac8-baa6e29857d2.png)

**Comment by DHowett-MSFT** [comment]
The keyboard shortcut is the Control key plus the Comma key. What are you _expecting_ to see there?

**Comment by DHowett-MSFT** [comment]
Right now, the settings menu item launches your favorite text editor or, barring that, the text editor you have configured to open .json files. Barring _that_, it'll launch Notepad. Barring even _that_, it'll ask you which application to use to open the json file.

**Comment by ChandanaNT** [comment]
Oh okay, my bad. I didn't see that it opened up a profiles.json because I already had a lot of files open in VS Code. Sorry.
