### ISSUE TITLE
Win-Key resets scroll location

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2506]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): Version: 0.3.2171.0

```

# Steps to reproduce

1. Pick a shell (any shell) ✨ 
2. Run any commend (or just mash the enter key) that produces enough output to push the screen down (not sure what the technical phrase for this is).
3. Scroll back up to look at some portion of the output
4. Push the Win-key 

# Expected behavior

Terminal scroll position is not affected

# Actual behavior

Terminal scroll position is returned to the current prompt location/line

Particularly annoying as trackpad scrolling is also broken

**Comment by wolf99** [comment]
Awesome, thanks @frieb98 & @DHowett-MSFT !

**Comment by DHowett-MSFT** [comment]
That was all @freib98's work :smile:

**Comment by debmaj2** [comment]
I am having the exact same issue. Please help.  **Terminal Version: 1.3.2651.0** Windows 10 2004
