### ISSUE TITLE
Highlighting broken on new tab

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2507]
# Environment

```none
OS: Microsoft Windows [Version 10.0.18362.295]
WT: Version: 0.3.2171.0
```

# Steps to reproduce

1. Open terminal
2. Open a second tab
3. Attempt to select text by clicking and dragging (I'm using a track pad, might be issue around that, don't have mouse available to test difference)

# Expected behavior

Text should be highlighted

# Actual behavior

Nothing

If I select text in the original tab, then try it in the new, second tab, selection starts working.

**Comment by DHowett-MSFT** [comment]
We think we've seen this before, but didn't have a formal bug to track it. Thanks!

**Comment by Summon528** [comment]
I think this is pretty similar with #1038

**Comment by zadjii-msft** [comment]
It definitely is! Thanks for finding that!

/dupe #1038
