### ISSUE TITLE
C# ConPTY Example

### ISSUE THREAD

**Issue by waf** [microsoft/terminal#251]
I've created a (very) rough C# terminal using ConPTY. It's barely past "hello world" stage, but I thought it might be useful for others, as it includes the pinvoke constants and declarations required to get everything working.

https://github.com/waf/MiniTerm

It's pretty much a straight-forward translation of the C++ examples (including the work from @bitcrazed's PR). If there's interest, I could submit this in a PR to this repository. I'd need some help getting it up to an acceptable level of quality -- there are still rendering issues I'm trying to figure out. 

The core of the interaction with the pseudoconsole is here:

https://github.com/waf/MiniTerm/blob/ef13d4ea5e5505aeb18efaad38d361a4ccf0c6f7/MiniTerm/Program.cs#L37-L57

**Comment by zadjii-msft** [comment]
Absolutely, I'd be happy to take a look at the PR :)

I'd add your sample as another child of `samples/ConPTY`, next to where @bitcrazed's sample will end up.

**Comment by bitcrazed** [comment]
Nice! Thanks for sharing @waf.

Just wrapping-up final edits to our sample. Will be publishing soon.

**Comment by bitcrazed** [comment]
Thanks again WAF - I've now published our C++ ConPTY sample. Will add WAF's sample. Please feel free to submit a PR with your managed MinTerm sample, and we'll work with you to get it added :)

**Comment by waf** [comment]
Great, thanks! I'll probably get a PR opened in the next week or so as I work through some of the known issues.

**Comment by ethanhs** [comment]
Hi, I seem to be getting mojibake when I try this sample (I realize my prompt of `ethanhs▶C:\❯` is not exactly common). I took a look but didn't see anything obvious that could cause this. Thoughts on what could cause this would be appreciated, as I am very interested in using ConPTY, but I am confused as to why this would break.

<img width="175" alt="miniterm_2018-11-15_00-17-33" src="https://user-images.githubusercontent.com/9504279/48539904-677b1900-e86d-11e8-8899-364254904e6a.png">

**Comment by miniksa** [comment]
We don't support characters above U+FFFF yet. ▶ and ❯ both have codepoints over U+FFFF. 

Also, I'd highly recommend that you choose to file a new issue next time instead of bumping an old closed one.
