### ISSUE TITLE
Guidance - Launch windows terminal from command line

### ISSUE THREAD

**Issue by dazinator** [microsoft/terminal#2510]
I'd like to know how to launch windows terminal from the command line, as this opens up the possibility of launching it from third part tools. As it's a windows store app, it doesn't seem as straightforward - I can't even figure out how to get the path of the executable!

**Comment by DHowett-MSFT** [comment]
It comes with an app execution alias called “wt”. Just run “wt”.

**Comment by dazinator** [comment]
@DHowett-MSFT thanks. Is it possible to open it at a particular path? I've tried things like:

> wt c:/

and 

> wt --path c:/

then realised I could be guessing all day for something that is currently not supported?

**Comment by DHowett-MSFT** [comment]
Alas, that's #608 :smile:

**Comment by DHowett-MSFT** [comment]
Sorry, i meant #607. Got my numbers mixed up.

**Comment by chorman0773** [comment]
Is there a way to specify which profile to open, such as
`wt —profile 4`?

**Comment by DHowett-MSFT** [comment]
Please go read #607.
