### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SchoolforDesign** [microsoft/terminal#2512]
Two things I suggest to create in the feature of  Windows Terminal V0.4:
**1.** Ctrl + Backspace: you know when you write the cmd's you can delete the cmd's (Word by Word), but your terminal can't do that, your terminal delete (Char by Char).
**2.** Ctrl + Space (Windows Powershell): if you write cmd's in the original windows powershell host, you also can show all snippets by hitting the ctrl + space. ex: get-pr[ctrl + space]
[https://pbs.twimg.com/media/EBDf-dsWkAAq7Lm?format=png&name=large](https://pbs.twimg.com/media/EBDf-dsWkAAq7Lm?format=png&name=large)

**Comment by zadjii-msft** [comment]
Please search for duplicates before filing new issues.

/dup #755

/dup #879
