### ISSUE TITLE
NonClientIslandWindow -- titlebar doubleclick no longer minmaxes

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2513]
Double-click the titlebar as of 0.3.2321; it does not min/max.

**Comment by zadjii-msft** [comment]
I broke this with #2438 almost certainly

**Comment by Ade-Joshe** [comment]
Mine works...

**Comment by DHowett-MSFT** [comment]
Our open bugs generally refer to whatever's on the `master` branch, which is almost certainly ahead of the released version. :smile: We're tracking this to make sure the public release doesn't break.

**Comment by eyalroth** [comment]
I just installed the terminal from the store and that's the first bug I've noticed.
```
Windows Terminal (Preview)
Version: 0.4.2382.0
```
