### ISSUE TITLE
CTRL+W doesn't work in SSH sessions

### ISSUE THREAD

**Issue by atyachin** [microsoft/terminal#2522]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable):  0.3.2171.0


Any other software?
```

# Steps to reproduce
1. Open remote SSH session to Linux (Ubuntu)
2. run nano
3. try to use CTRL+W to search for a string

# Expected behavior
CTRL+W should put nano in search more

# Actual behavior
The Linux tab closes immediately without even properly logging out of the SSH session.

**Comment by DHowett-MSFT** [comment]
Your `closeTab` or `closePane` key binding is set to <kbd>Ctrl+W</kbd>. If you don't want it to `closeTab` or `closePane`, change that binding to something else.

Terminal has already changed the default binding for close to <kbd>Ctrl+Shift+W</kbd>.
