### ISSUE TITLE
Bug Report - Immediate Crash to Desktop in Windows 10 on ARM

### ISSUE THREAD

**Issue by Chirishman** [microsoft/terminal#2523]
# Environment

```none
Windows build number: 10.0.18362
Windows Terminal version (if applicable): Newest direct from Windows Store
```

# Steps to reproduce

- Install via Windows store on to one of the few Windows 10 on ARM devices (in my case the [ASUS NovaGo TP370](https://www.microsoft.com/en-us/p/asus-novago-tp370ql-6g128g-convertible-2-in-1-laptop-with-gigabit-lte-unlocked/8z6d8jn7cgg9?activetab=pivot%3aoverviewtab))
- Attempt to run Terminal

# Expected behavior

Terminal successfully opens/runs or else Store does not allow the install

# Actual behavior

Store allows me to install, attempting to run Terminal results in immediate crash to desktop. No window is ever created as far as I can tell and no error message is returned.

**Comment by Chirishman** [comment]
Here you go: https://aka.ms/AAwrb2

**Comment by DHowett-MSFT** [comment]
Hey, really sorry about that. I was waiting for the feedback hub link to become valid (since it says it takes some time), but it never did. Would you mind producing another feedback hub item?

**Comment by jlorich** [comment]
Just checked this out on a Surface Pro X at the Retail store and experienced the same issue.  A fresh install from the Microsoft Store on a fresh store-demo distro and it immediately crashes on launch.
