### ISSUE TITLE
How is this different from ConEmu?

### ISSUE THREAD

**Issue by itmuckel** [microsoft/terminal#2524]
I used ConEmu for years and I don't know how this Windows Terminal is different from what ConEmu does.

Can anyone clarify? 🤔

**Comment by DHowett-MSFT** [comment]
...? Competition is good. Having multiple good terminal emulators on Windows is a good thing. It does what ConEmu does, but it's written by the same team that has been working on the original Windows console for five years.

**Comment by itmuckel** [comment]
Yes, of course competition is good, but usually you start developing an alternative product, because it has additional capabilities that the other one didn't have. Maybe I'll have to wait for this to mature to see its advantages over ConEmu. 😉
