### ISSUE TITLE
There's a break in margin on fullscreen. Titlebar content overflow and break the main display 

### ISSUE THREAD

**Issue by Ade-Joshe** [microsoft/terminal#2532]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Could you maybe share a screenshot? This sounds really similar to #2268, but without more details I'm not really sure what to do with this bug.
