### ISSUE TITLE
Bug Report Closing one tab with internet connection bug

### ISSUE THREAD

**Issue by iamukasa** [microsoft/terminal#2533]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
I'm going to need some more information here. What's the bug? What do you expect to happen, and what is actually happening?
