### ISSUE TITLE
Terminal crashes on launch - no error in Event Viewer

### ISSUE THREAD

**Issue by dgweller** [microsoft/terminal#2535]
# Environment

Windows build number:  10.0.18965.0 (fast ring - 190816-1722)
Windows Terminal version (if applicable): updated today (23 Aug) using choco
GPU: GTX 1070 with dual 4k moniitors driven via DVI.  Drivers up to date.
x64 architecture (AMD Ryzen, FWIW)

# Steps to reproduce

Installed from MS store
launching results in an empty window border showing (less than 1 sec) and terminating
Updated to latest version using Chocolatey
Same results
See #1364 for appropriate image of what I observe

# Expected behavior

Working terminal window

# Actual behavior

wt.exe fails to launch

# Additional Data
- I reviewed #1364 with no obvious corrective action to take, even though the bug appears to be identical.  Since that bug is closed, I am recommending reopening, unless there is an obvious corrective action I failed to read.
- Windows Event Viewer did NOT show any errors
- I have not attempted to create my own build
- (Added Aug 26) The same issue happens whether or not Event Viewer is running.
- Perhaps relevant: I installed WSL 2 prior to installing Windows Terminal Preview

**Comment by angelog0** [comment]
@dgweller, I would say that this is very similar to #1954. Just out of curiosity, have you tried to launch WT after launching some other applications? for example Event Viewer and the WT...

**Comment by madcpt** [comment]
Maybe check if 'powershell.exe' is included in the environment variables. When PowerShell is set as the default profile while 'powershell.exe' is not found by the system, Terminal may just crash.

**Comment by madcpt** [comment]
@dgweller, I used PowerShell a lot too, but still 'powershell.exe' is not included in my Environment Variables. You can try using 'powershell' in cmd.exe to check if it is correctly recognized. Anyway, it solved my problem (which is very similar to yours in your description), so maybe it's worth a shot.

**Comment by DHowett-MSFT** [comment]
Would you mind sharing your `profiles.json`?

**Comment by dgweller** [comment]
Sorry for not responding sooner.  Can you tell me where profiles.json is located?  It is not in C:\Users\<username>\AppData\Local\Microsoft\WindowsApps

**Comment by DHowett-MSFT** [comment]
It'll be in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`

**Comment by dgweller** [comment]
> It'll be in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`

The only file there is wt.exe

**Comment by DHowett-MSFT** [comment]
That's the only file in `%LOCALAPPDATA%\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe`. I'm talking about `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState` (`WindowsApps` -> `Packages`).

**Comment by dgweller** [comment]
Doh!  It would help to, you know, READ your instructions :)
File attached.
[profiles.zip](https://github.com/microsoft/terminal/files/3572775/profiles.zip)

**Comment by DHowett-MSFT** [comment]
Would you mind listing the contents of `C:\Program Files\PowerShell`?

**Comment by dgweller** [comment]
here you go (short version: Only ps6 dir directly inside the ps dir - I included ./6 in this file)
[ps_dir.zip](https://github.com/microsoft/terminal/files/3584100/ps_dir.zip)

**Comment by DHowett-MSFT** [comment]
Your default profile specifies `7-preview` ;)

**Comment by alex-slover** [comment]
Just wanted to chime in and say that this is also occurring for me on a totally fresh install of Windows (1903, 18362.329) and using the current Store release. Powershell is my default shell and `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` is on my PATH. I have not installed PSCore yet and so I have no `C:\Program Files\PowerShell` directory, and my `profiles.json` file is the default one you get through a Store installation.

**Comment by zadjii-msft** [comment]
#2039 is related (for bookkeeping)
