### ISSUE TITLE
Display a new WSL distro in the profiles list

### ISSUE THREAD

**Issue by olivbau** [microsoft/terminal#2536]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.18362.295]
Windows Terminal version (if applicable): Version: 0.3.2171.0
```

# Steps to reproduce

1. Install Windows Terminal
2. Install a Linux Distribution from Windows Store
3. Enable the Windows Subsystem for Linux
4. Reboot
5. Launch the WSL distro and configure it
6. Reboot

# Expected behavior

Display the WSL distro in the profiles list
Or add easy way to add it

# Actual behavior

The WSL distro not appear in the profiles list

**Comment by DHowett-MSFT** [comment]
#754 will help this. Right now we only generate the list of WSL distributions on initial install.
