### ISSUE TITLE
Terminal (Dev Build) crashed on launch

### ISSUE THREAD

**Issue by madcpt** [microsoft/terminal#2537]
I was using VS 2019 and 1903 SDK, the building and deployment were all good, while the terminal crashed on launch.
I started a debug instance and got this following message:
`Exception thrown at 0x00007FFB0EDEE052 (Windows.UI.Xaml.dll) in WindowsTerminal.exe: 0xC0000005: Access violation reading location 0x0000000000000610. occurred`

**Comment by DHowett-MSFT** [comment]
Since you've got a dev build running, and you're using Visual Studio to do it, it would be _very helpful_ if you could give us a call stack instead of just an exception line. :smile:

**Comment by madcpt** [comment]
Actually, it turned out to be that the Xaml lib was not correctly loaded. This problem should be solved by reloading Xaml from NuGet.
