### ISSUE TITLE
Terminal fails to launch when installed from the store

### ISSUE THREAD

**Issue by mukaschultze** [microsoft/terminal#2555]
# Environment

```none
Microsoft Windows [Version 10.0.18362.295]
Any other software? No
```

# Steps to reproduce

Install the application from Windows Store (or from binaries released on this repo) and launch it, it results in the following error:

![image](https://user-images.githubusercontent.com/13923364/63764494-526ff380-c89d-11e9-8679-dfb8ffc2d608.png)

Builds made on my machine launches just fine, so I don't know how I can get more info to debug this issue (they crash after using it for a while, but I don't think this is related to the same bug).

# Expected behavior

The application installed from the store should launch just like the ones built on my machine.

# Actual behavior

It crashes, with the error `File system error (12029).`

**Comment by DHowett-MSFT** [comment]
Do you have a third-party AV or firewall solution installed?

**Comment by mukaschultze** [comment]
I'm not running any third-party AV and firewalls.

I tried running it with Windows firewall disabled just in case, and... it launched...
So I reenabled the firewall and tested it again, now it is working all the times, even after uninstalling and reinstalling it.

I think it's worthing mentioning that the app was allowed through the firewall in the settings while it was crashing.

### Solution
In case anyone runs into the same issue in the future: Disable Windows firewall, start the terminal application and then reenable the firewall.

**Comment by DHowett-MSFT** [comment]
Thanks for confirming. We've seen something like this before, but we have no idea what causes it. It's definitely external to our project. ☹️

**Comment by Xairoo** [comment]
> In case anyone runs into the same issue in the future: Disable Windows firewall, start the terminal application and then reenable the firewall.

Same for NetLimiter.

**Comment by ericgl** [comment]
I installed the latest version of Terminal (v1.10.1933.0), and upon launch - it gave me this error (**12029**).
It seems to be caused by my firewall app. After disabling it, Terminal launched normally. I then re-enabled my firewall app.
Strange behavior...
