### ISSUE TITLE
If the default shell can't be launched and closeOnExit=true, Terminal buys the farm

### ISSUE THREAD

**Issue by KAMiKAZOW** [microsoft/terminal#2563]
# Environment

```
Windows build number:  10.0.18362.295
Windows Terminal version: 0.4.2382.0
```

# Steps to reproduce

* Install a WSL distribution (openSUSE Leap 15.0 in my case).
* Move it to top spot and make it default.
* Uninstall old WSL distribution and install the upgraded one (openSUSE Leap 15.1 in my case).

# Expected behavior

Remove uninstalled WSL distributions. Add all installed WSL distributions unless explicitly disabled in WT.

# Actual behavior

WT closes right away. I'm somehow expected to know the UUID change (`wsl.exe --list` does not show the UUIDs).

----
Another bug report claims that behavior for non-existent profiles would be handled gracefully in 0.4. Can't confirm that.

**Comment by KAMiKAZOW** [comment]
WT still closes right on launch.

**Comment by JBanks** [comment]
We should add in a fail-safe for the event that the default profile has been corrupted.  The current settings directory is quite difficult to find for new users, and could discourage experimentation.  Perhaps a safe-mode if the past execution exited immediately?

**Comment by DHowett-MSFT** [comment]
This is now the master bug for "my default shell doesn't launch and it makes me sad because terminal exits instantly"

**Comment by DHowett-MSFT** [comment]
This will be helped by #2039 and #2091 (or an evolution thereof).
