### ISSUE TITLE
Bug Report - Windows Defender detect suspicious behavior

### ISSUE THREAD

**Issue by rodoaravena** [microsoft/terminal#2568]
# Environment

```none
Windows build number: 18965
Windows Terminal version: Dev Build
```

# Steps to reproduce

1. Open Windows Terminal

# Expected behavior

1. Open default tab

# Actual behavior

After open Windows Terminal (Dev Build), Windows Defender detect a suspicious behavior, and block the execution
Windows Defender Message:
Behavior:Win32/Generic.WR!ml
Alert level: Severe
Status: Quarantined
Date: 08/27/2019
Category: Suspicious behavior
Details: This program is dangerous and Executes commands from attacker
Affected items: file: 
appmodel: WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe

file: C:\Users\rodoa\source\repos\WindowsTerminal\terminal\src\cascadia\CascadiaPackage\bin\x64\Debug\AppX\conhost.exe

Note: I compiled and deployed 8 hours ago and it ran fine, but I opened it (from start menu) again a few minutes ago and W.D. alerted of the thread

**Comment by DHowett-MSFT** [comment]
This is external to us, but internal to Microsoft. We'll pursue it from our side.
Thanks!

**Comment by AshrafMichail** [comment]
What's the workaround people use?  Adding the full path of the built conhost.exe location to the exclusion list?  Of course, I wouldn't want to do anything to exclude scanning for the actual conhost.exe virus that defender is trying to prevent against.
