### ISSUE TITLE
Chocolatey issue template 

### ISSUE THREAD

**Issue by mkevenaar** [microsoft/terminal#2573]
# Description of the new feature/enhancement

Adding a template for Chocolatey to the issue template list where a warning is that they should not create an issue here, will (hopefully) prevent additional issues.

# Proposed technical implementation details (optional)

When someone creates an issue and clicks on the Chocolatey question option, a text will be displayed to stop creating this issue and go to another repo.

**Comment by zadjii-msft** [comment]
I'm gonna say "meh". In the 2 years this has been open, it's rarely been an issue. Thanks anyways!
