### ISSUE TITLE
[Feature Request] Add ubuntu icon

### ISSUE THREAD

**Issue by TheZoker** [microsoft/terminal#2576]
# Description of the new feature/enhancement
Currently the icon for the ubuntu shell is the linux icon. Would be nice to have to ubuntu logo for the ubuntu shell. 

![IMG_2019 08 28_12h24m32s_003_](https://user-images.githubusercontent.com/1368405/63847797-d6ee6f00-c98e-11e9-8dea-cf6480782462.png)

**Comment by TheZoker** [comment]
Thanks for the heads up. Should I leave this issue open until a solution is found?

**Comment by DHowett-MSFT** [comment]
We'll be tracking this as part of #2282. Thanks!
