### ISSUE TITLE
[Feature Request] Add setting to open window in full screen

### ISSUE THREAD

**Issue by TheZoker** [microsoft/terminal#2577]
# Description of the new feature/enhancement
Currently when I pin the windows terminal to my taskbar and open it, it will open in windowed mode. I would like to have a setting, where the windows terminal opens in fullscreen mode per default.

# Proposed technical implementation details (optional)

- Add setting `openFullscreen`

**Comment by DHowett-MSFT** [comment]
Tracking this as part of /dup #1043
Thanks!

**Comment by navidR** [comment]
You guys should reopen this issue. Fullscreen is not the same as maximized, and the patch only address maximized state. *Not* fullscreen.

**Comment by DHowett** [comment]
FYI: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#launch-size:

![image](https://user-images.githubusercontent.com/189190/87821274-6a899200-c824-11ea-9de8-05ba6a197cd5.png)

![image](https://user-images.githubusercontent.com/189190/87821248-5ba2df80-c824-11ea-8595-6a5d7fae1275.png)

**Comment by navidR** [comment]
Whoops. That would solve what I was looking for. Thanks.
