### ISSUE TITLE
emacs 24.x and 26.x  slow

### ISSUE THREAD

**Issue by xiaonigejian** [microsoft/terminal#2579]
when i use emacs in terminal, is very very very slow. opposite，i use windows cmd tool is very fast。

**Comment by xiaonigejian** [comment]
没人回复？
在terminal中使用emacs反应很慢，反而使用原始的cmd反应很顺畅。

**Comment by xiaonigejian** [comment]
wsl version
![image](https://user-images.githubusercontent.com/10397085/63913874-408c7d00-ca64-11e9-99de-7f8834be396c.png)
emacs version
![image](https://user-images.githubusercontent.com/10397085/63913924-5c901e80-ca64-11e9-8491-a97fa334ec6a.png)
terminal version
![image](https://user-images.githubusercontent.com/10397085/63913956-6ade3a80-ca64-11e9-804d-3390e25253f8.png)
windows version
![image](https://user-images.githubusercontent.com/10397085/63914103-c7d9f080-ca64-11e9-9e84-183189aa0871.png)

**Comment by zadjii-msft** [comment]
I'm pretty sure this just falls under the category of #1064. There's a lot of work we can still do here to improve performance. I'm tempted to leave this open as a _"make sure to optimize conpty for emacs"_ issue, and at the same time I'm tempted to just close this as a dupe. I'll leave it to someone else on the team to make the final call.

**Comment by DHowett-MSFT** [comment]
Yeah we'll close this one out as a dupe. Thanks!
/dup #1064
