### ISSUE TITLE
Establish CI/CD using Azure Pipelines (Build/Release)

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#2580]
# Description of the new feature/enhancement
Create a Release Pipeline that pushes the release to the Github Release page. There is already a Build Pipeline so half of the battle is already done. Just need to copy it and adjust to go to master as the current one is for PR checking. Then once a week, the Release Pipeline would deploy to the Github Release page. An eventual todo is setup a deploy to the Microsoft Store in addition to the Github Release page.

**A clear and concise description of what the problem is that the new feature would solve.**

Automates the deployment of the app in addition to starting the set up of an update schedule. 

**A clear and concise description of what you want to happen.**

I'd like to see releases more frequently from Github that require little administrative effort from the core team.

**Comment by DHowett-MSFT** [comment]
We've [actually got one](https://github.com/microsoft/terminal/blob/master/build/pipelines/release.yml), we're just not publishing the builds from it.

**Comment by DHowett-MSFT** [comment]
(We're not quite ready for that, because we need to settle on our cadence; that's more of a project management issue than a bug/feature here.)

**Comment by WSLUser** [comment]
Yeah, as I said, I was hoping to see more releases get published for testing instead of having to build to get more frequent from master. I would be fine doing this myself but unfortunately I lack the necessary permissions in Azure. I specified a week as a starting point for the Release due to that cadence not being quite settled yet (and the deployment can be cancelled if need be).  It'll be easy enough to adjust the deployment schedule once everything settles down.
