### ISSUE TITLE
Allow Terminal Window auto-size and position based on Viewport

### ISSUE THREAD

**Issue by manjnath** [microsoft/terminal#2584]
# Description of the new feature/enhancement

1. Include a Setting to auto-size the Terminal Window based on a percent of the current deskport/viewport size. For example, Width=80% display screen width; Height=40% Display Screen Height.
2. Include a Setting to designate the top left screen coordinates for the Terminal window. For example, WindowPos=0,10 for the top left of the Terminal window to be positioned at row 0, column 10.

# Proposed technical implementation details (optional)

When such a Setting is enabled, the Terminal window will always open at these dimensions and coordinates.

**Comment by zadjii-msft** [comment]
/dupe #1043 

Thanks!
