### ISSUE TITLE
Bug Report : Windows Terminal Crashes on Startup

### ISSUE THREAD

**Issue by xpwn3rx** [microsoft/terminal#2587]
# Environment
![image](https://user-images.githubusercontent.com/19785522/63887885-9abd0d80-c992-11e9-9d9b-2d96342cb834.png)

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): Latest from Github source, compiled 11am 8/28/2019 after git pull.

Any other software?

Visual Studio 2019

# Steps to reproduce
Open Windows Terminal Dev build. This used to work, and stopped working about two weeks ago after a git pull and recompile. I have tried uninstalling and reinstalling using multiple methods, have deleted my source directory and re-downloaded and followed all the steps in the documentation in the README.

# Expected behavior

Terminal should open, and used to open.
# Actual behavior

Terminal crashes on launch every time. https://aka.ms/AA5yrsw

Faulting application name: WindowsTerminal.exe, version: 0.0.0.0, time stamp: 0x5d66be04
Faulting module name: ucrtbase.dll, version: 10.0.18965.1000, time stamp: 0xafa25d02
Exception code: 0xc0000409
Fault offset: 0x00000000000714ae
Faulting process id: 0x3dc0
Faulting application start time: 0x01d55dcc172dff9a
Faulting application path: C:\Temp\winterm\src\cascadia\CascadiaPackage\bin\x64\Release\AppX\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 06aba601-3041-4c3b-899b-432c97e7e44d
Faulting package full name: WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: APP

**Comment by xpwn3rx** [comment]
I am still seeing this, even with the latest code. Anyone on the MS side got any ideas?

**Comment by DHowett-MSFT** [comment]
I'm so sorry. Our bot went a little crazy for a second.

**Comment by xpwn3rx** [comment]
Hi Dustin - I got an automated email asking for a feedback link, which was included. Here it is again:

https://aka.ms/AA5yrsw

**Comment by xpwn3rx** [comment]
Update, I saw there were a lot of changes today. This still builds, installs and explodes on launch.

**Comment by DHowett-MSFT** [comment]
Hey, so, I can't actually look at any of your crash logs. Unfortunately, since you're running a locally-built dev build (and I'm sorry I missed this in the beginning) it's up to you to provide a stack trace from your development environment. My debugger cannot resolve the symbols produced on your machine. :smile:

**Comment by dyyylan** [comment]
I found this issue through a ~google~bing search and had a similar problem. My terminal (the windows store version) has been crashing for months immediately upon opening. I kept trying new builds when they were released but the problem persisted.

I eventually tracked it down to the settings file, I believe I had an default guid set for a profile (and maybe I deleted the other profiles, I can't remember) that may have become invalid after reinstalling WSL? This crashing behavior actually persisted through two OS reinstalls, so I assume the settings file is stored in the cloud somewhere? After resetting the app through the right click -> "app settings" pane, it works fine again.

Not sure if this is a separate is a separate issue from the OP's that should be tracked, but wanted to mention it.

**Comment by Wallace-Kelly** [comment]
For me, the solution was to run the application with the *integrated graphics card*, instead of my NVidia graphics card. There are two ways to do that:

![image (1)](https://user-images.githubusercontent.com/52675700/64494865-20c53800-d260-11e9-892b-368dc5bc7a24.png)

<hr>

![image (2)](https://user-images.githubusercontent.com/52675700/64494867-26bb1900-d260-11e9-83c3-74a289558cb5.png)

I had three applications start doing this at the same time... Paint.NET, mRemoteNG, and Windows Terminal. I _think_ they started failing when I connected a new Thunderbolt "docking station" with USB3 and DisplayPort monitors.

**Comment by xpwn3rx** [comment]
I tried doing that with the graphics settings. It did not improve the situation. I will get you a stack trace @DHowett. Do you want me to create a dump from the process as well, with it hung on crash?

**Comment by DHowett-MSFT** [comment]
Yes, please. Thanks!

**Comment by xpwn3rx** [comment]
Exception thrown at 0x00007FFEE4584F99 in WindowsTerminal.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000008E1CAFE518

 	KernelBase.dll!00007ffee4584f99()	Unknown
 	vcruntime140d.dll!00007ffeb71382f7()	Unknown
>	TerminalApp.dll!winrt::throw_hresult(const winrt::hresult result) Line 4367	C++
 	TerminalApp.dll!winrt::check_hresult(const winrt::hresult result) Line 4413	C++
 	TerminalApp.dll!winrt::get_activation_factory<winrt::Microsoft::Terminal::TerminalConnection::IConhostConnectionFactory>(const winrt::param::hstring & name) Line 5295	C++
 	TerminalApp.dll!winrt::impl::factory_cache_entry<winrt::Microsoft::Terminal::TerminalConnection::ConhostConnection,winrt::Microsoft::Terminal::TerminalConnection::IConhostConnectionFactory>::call<<lambda_4c3dc08770363e37251a9b4ac844b54d> &>(winrt::Microsoft::Terminal::TerminalConnection::ConhostConnection::<lambda_4c3dc08770363e37251a9b4ac844b54d> & callback) Line 5500	C++
 	TerminalApp.dll!winrt::impl::call_factory<winrt::Microsoft::Terminal::TerminalConnection::ConhostConnection,winrt::Microsoft::Terminal::TerminalConnection::IConhostConnectionFactory,<lambda_4c3dc08770363e37251a9b4ac844b54d>>(winrt::Microsoft::Terminal::TerminalConnection::ConhostConnection::<lambda_4c3dc08770363e37251a9b4ac844b54d> && callback) Line 5574	C++
 	TerminalApp.dll!winrt::Microsoft::Terminal::TerminalConnection::ConhostConnection::ConhostConnection(const winrt::param::hstring & cmdline, const winrt::param::hstring & startingDirectory, const winrt::param::hstring & startingTitle, unsigned int rows, unsigned int columns, const winrt::guid & guid) Line 229	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::TerminalPage::_CreateConnectionFromSettings(_GUID profileGuid, winrt::Microsoft::Terminal::Settings::TerminalSettings settings) Line 431	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::TerminalPage::_CreateNewTabFromSettings(_GUID profileGuid, winrt::Microsoft::Terminal::Settings::TerminalSettings settings) Line 361	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::TerminalPage::_OpenNewTab(std::optional<int> profileIndex) Line 339	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::TerminalPage::Create() Line 85	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::App::Create() Line 158	C++
 	TerminalApp.dll!winrt::impl::produce<winrt::TerminalApp::implementation::App,winrt::TerminalApp::IApp>::Create() Line 723	C++
 	WindowsTerminal.exe!winrt::impl::consume_TerminalApp_IApp<winrt::TerminalApp::IApp>::Create() Line 47	C++
 	WindowsTerminal.exe!AppHost::Initialize() Line 81	C++
 	WindowsTerminal.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 147	C++
 	[External Code]	

Dump file in 7zip file: https://drive.google.com/file/d/1Y_gqlBMhX4LBC7IhfSDhxtLNgb1jMFZA/view?usp=sharing

**Comment by DHowett-MSFT** [comment]
Hold up, you’re using the preview release of VS aren’t you?

**Comment by xpwn3rx** [comment]
I am using 2019 Preview 3. I was using Preview 2 and it was broken before I updated as well. This used to work on Preview 1.

**Comment by DHowett-MSFT** [comment]
This is more than likely just #2625. Sorry!

**Comment by xpwn3rx** [comment]
@DHowett-MSFT This broke before I upgraded to preview 3. Do we know if there is a manual way to fix this for the time being?
