### ISSUE TITLE
Can't scroll with mouse wheel in my PC (only?)

### ISSUE THREAD

**Issue by archongum** [microsoft/terminal#2594]
# Environment

- Windows 10 build 18965.1000
- WT 0.4.2382.0 

# Steps to reproduce

Re-install WT still won't work.  
But installed in my other PC worked so I think it's something wrong with my PC settings.

# Expected behavior

Can scroll with mouse wheel in my PC

# Actual behavior

Can scroll using mouse or touchpad without WT which opening by `ctrl + R` then `powshell` or `cmd` or `bash`.

Can't scroll using mouse or touchpad with WT but scroll bar works.

![Snipaste_2019-08-28_09-58-50](https://user-images.githubusercontent.com/20929338/63903197-29876400-ca3f-11e9-933f-8e9cbe922045.jpg)

**Comment by archongum** [comment]
@zadjii-msft here, thanks

**Comment by zadjii-msft** [comment]
@archongum what mouse are you using?

I'm not really sure how to phrase this next question, but are you using a precision/smooth scrolling wheel or a "clicky" scrolling?

Does that mouse work on the other PC? Does the other PC's mouse work on the broken PC?

**Comment by archongum** [comment]
I don't know how to provide more details/error-logs either... But I'm sure there is not about the hareware(mouse). 
Currently, I think let's leave this issue here. I will try other way to figure it out when I have time, like install WT in a vm and change some settings to see whether something goes wrong...

**Comment by archongum** [comment]
The difference between normal and broken WT. What is `C:\ProgramData\Intel\ShaderCache`? Is it relevant to this issue? If not, I think there is something wrong with my Windows then because other thing broken too (check the gif below).

![Snipaste_2019-09-02_10-33-37](https://user-images.githubusercontent.com/20929338/64087812-35da2c80-cd71-11e9-92c9-2472cb9206dd.jpg)

---

Can't un-check the checkbox.

![1](https://user-images.githubusercontent.com/20929338/64087814-38d51d00-cd71-11e9-96c0-e5ec77c87a85.gif)

Any suggestions instead of re-install Windows?😂

**Comment by SkyEmie** [comment]
i have the same issue, i can't scroll on win terminal with the mouse wheel :/

**Comment by yossizahn** [comment]
Same issue here, scrolling not working.

**Comment by WSLUser** [comment]
@archongum `DISM.exe /Online /Cleanup-image /Restorehealth` and `sfc /scannow` are your best bets short of re-installing WIndows if you're experiencing other issues with Windows.

**Comment by archongum** [comment]
@WSLUser Tried but issue remain, thanks anyway.

**Comment by geirsagberg** [comment]
Scrolling is broken for me too, using Surface Book 2 with a Logitech MX Master 3. Neither touchpad nor mouse scroll works.

**Comment by geirsagberg** [comment]
UPDATE: I tried disabling "X-Mouse Button Control", an app I use to remap mouse buttons, now scrolling works. Not sure why it's the only app affected though?

**Comment by yossizahn** [comment]
Thanks @geirsagberg !
Same here. Disabled X-Mouse Button Control and now scrolling works again.

**Comment by archongum** [comment]
AT geirsagberg  
WTF! Works for me too. Good new!

**Comment by yossizahn** [comment]
@archongum disabling "Make scroll wheel scroll window under cursor" in the main settings, or overriding it in the profile options for windows terminal will fix the issue. It seems that x-mouse-button control is sending the scroll messages to the wrong window.

**Comment by archongum** [comment]
@yossizahn Works! ❤

**Comment by SkyEmie** [comment]
Thanks +1
