### ISSUE TITLE
Preview 0.4 still has problems displaying emoji

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#2600]
Windows 10.0.18362.0, Windows Terminal Preview 0.4

The character is the Scotland flag emoji.

![image](https://user-images.githubusercontent.com/172594/63948275-45572e00-ca70-11e9-9df1-345bae9549f9.png)

**Comment by DHowett-MSFT** [comment]
/dup #2066 #1472

All flags are combining-character emoji. I suspect you know this, though.
