### ISSUE TITLE
Bug Report: Cannot double-click titlebar to maximize

### ISSUE THREAD

**Issue by jantari** [microsoft/terminal#2602]
# Environment

```none
Windows build number: 10.0.18965.0 (Insider Fast)
Windows Terminal version (if applicable): 0.4.2382.0

Any other software? No.
```

# Steps to reproduce

1. Open the terminal
1.1 Perhaps it's relevant that I have `showTabsInTitlebar` set to the default value of `true`
2. double-click anywhere inside the draggable titlebar

Image for illustration purpose of the area I mean by "titlebar":  
![wt_cant_doubleClickToMaximize](https://user-images.githubusercontent.com/25607767/63949936-6c672d00-ca7b-11e9-8d7d-ef99ae702707.jpg)

# Expected behavior

The window should maximize

# Actual behavior

Nothing happens

**Comment by zadjii-msft** [comment]
Please search before filing a new issue. 
/dup #2513
/dup #2564
/dup #2583
