### ISSUE TITLE
Able to group profiles

### ISSUE THREAD

**Issue by jimf5** [microsoft/terminal#2608]
Able to group profiles 

All profiles are shown in the one list. It would be much more convenient to able to group some profiles with common label and show them in sub-lists.

**Comment by richardszalay** [comment]
You should rename this issue to include a one line summary of your request. If it stays as "Feature Request" it will be closed

**Comment by carlos-zamora** [comment]
Sounds like you want #2330. This functionality will be encompassed in #1571.

**Comment by jimf5** [comment]
Yes, it does.
Thank you.
