### ISSUE TITLE
Copy/Paste with line wrapping selection enabled, does not filter CR/LF

### ISSUE THREAD

**Issue by cnschindler** [microsoft/terminal#261]
When copying conten from PowerShell where "Enable line wrapping selection" is activated, if the Shell command spans more than one line, CR/LF characters are not filtered. This breaks the shell command into several pieces (a separate one per line) and eventually leads to Errors when pasted into another shell.

Repro:

-Open Windows PowerShell (5.x/6.x))
-Activate "Enable line wrapping selection"
-Write shell command that spans more than one line
-Mark the whole shell command (including line wrapping)
-Copy the marking
-Clear the shell with ESC
-Paste the previously copied shell command
-Every line of the copied shell command will be pasted on a new line separated with CR/LF

Expected behavior:

When copying shell command with line wrapping, the console host should ommit CR/LF so that the command will be pasted as a whole.

**Comment by zadjii-msft** [comment]
How are you copying the text? Ctrl+C, Ctrl+Shift+C, or Right Click?

**Comment by cnschindler** [comment]
Hi, regardeless which method I use. But I edited my issues description: it only happens in PowerShell. CMD.EXE is not affected… So Maybe this is a PowerShell issue, not a Console issue?

**Comment by miniksa** [comment]
Yes, this is probably a PowerShell issue given PowerShell uses PSReadline to handle this stuff by default and it only happens there for you.
