### ISSUE TITLE
my terminal crashed whenever I copy this code from it -- '(LinkedNode *)mallock(sizeof(LinkedNode))'

### ISSUE THREAD

**Issue by zeyu203** [microsoft/terminal#2612]
# Environment
windows 10 version: 18362.295
windows terminal version:  0.4.2382.0

# Steps to reproduce

my terminal crashed whenever I copy this code from it：
> (LinkedNode *)mallock(sizeof(LinkedNode))

**Comment by zadjii-msft** [comment]
80-90% chance this is fixed by #2590 

/dupe #2570
