### ISSUE TITLE
扩展向下箭头可以放在右侧，最小化旁边，左右下边框可以取消，不需要看到

### ISSUE THREAD

**Issue by cjsvaxlp** [microsoft/terminal#2613]
扩展向下箭头可以放在右侧，最小化旁边，左右下边框可以取消，不需要看到

**Comment by cjsvaxlp** [comment]
可以模仿下chrome header 设计

**Comment by zadjii-msft** [comment]
From a very rough internet translation of this issue, I'm going to dupe this to #1375 

/dup #1375
