### ISSUE TITLE
Add "Open Terminal Here" to context menu

### ISSUE THREAD

**Issue by developer82** [microsoft/terminal#2614]
As with today's command line or powershell, it is possible to go to the address bar in the file explorer and type 'cmd' or 'powershell' and it would open in the current directory location.

1. This feature request is about allowing the same behavior by typing 'terminal' - which will open the terminal with the default profile in the directory location.

1. In addition please also allow a context menu entry for terminal that would also open the default profile in the current directory.

**Comment by DHowett-MSFT** [comment]
Please make sure you search for existing issues before you file a new one.

**Comment by mlocati** [comment]
>     1. This feature request is about allowing the same behavior by typing 'terminal' - which will open the terminal with the default profile in the directory location.

Use `wt`
