### ISSUE TITLE
 the text paste doesn't match the format

### ISSUE THREAD

**Issue by adyoi** [microsoft/terminal#2616]
# Environment

SSH

Any other software?
```

# Steps to reproduce

on an SSH connection, paste the text on the screen tab position incorrectly

# Actual behavior

on an SSH connection, paste the text on the screen tab position incorrectly

**Comment by zadjii-msft** [comment]
I'm going to need more specific information from you to be able to do anything. 

What SSH are you running?

What text are you copying? 

When you say "incorrectly", what specifically do you mean? Could you share screenshots?

This may be any combination of #2324, #1073, #2275, #1091, but I can't be sure without more information.
