### ISSUE TITLE
Terminal crashes if I specify an invalid fontFace

### ISSUE THREAD

**Issue by jtnord** [microsoft/terminal#2617]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.3.2171.0


Any other software?

 Clink v0.4.9 [git:2fd2c2]  (http://mridgers.github.io/clink)
```

# Steps to reproduce

open a cmd tab
edit the settings and change fontFace for the cmd profile to something invalid (apending "ZZZ" for example)

# Expected behavior

terminal uses a default font and does not crash

# Actual behaviour

terminal terminates

This would sound like a perfect dupe of #550 only I am running `0.3.2171.0` and that was "fixed" in `0.3.2142.0`
Terminal does not terminate if you start cmd.exe without autorun extensions (clink) with the `/D` flag.

If you have powershell tabs open terminal still terminates and you loose work (which is why I beleive this is a terminal bug and not a clink one)

**Comment by DHowett-MSFT** [comment]
Interesting. I can't repro this, as you expected, without clink. What does clink do on startup that cmd doesn't do? Does it print something? Terminal is isolated from the shell by a text stream, so it's only text and escape sequences that could be coming from clink that'd cause us to crash.
