### ISSUE TITLE
Windows Terminal is not opening after downloading.

### ISSUE THREAD

**Issue by jaintanmay121** [microsoft/terminal#2618]
# Can't open my Windows Terminal

I installed the windows terminal from the microsoft store few hours ago and whenever I tried to open the terminal, it just displays the windows border for 2 seconds and then it closes. Tried to re-install the terminal and restarted the system several times too.
Any help ??

**Comment by Cmoen11** [comment]
I got the same issue when my laptop is connected to the Targus workstation. Seems to be related to not finding the correct GPU to use. Seems to be a issue if your computer has two graphics-cards.

**Comment by jaintanmay121** [comment]
> I got the same issue when my laptop is connected to the Targus workstation. Seems to be related to not finding the correct GPU to use. Seems to be a issue if your computer has two graphics-cards.

Yes my system has two AMD graphic cards (crappy ones though). How did you resolved it the problem??

**Comment by jaintanmay121** [comment]
@Cmoen11 

Yes my system has two AMD graphic cards (crappy ones though). How did you resolved it the problem??

**Comment by Cmoen11** [comment]
You can try to disable one of them, and try to open the app once again
