### ISSUE TITLE
Right click Terminal taskbar item: 'Run as Administrator'

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#2623]
# Description of the new feature/enhancement

Right now, to start Terminal as Administrator, it's **Start** > **Find Terminal** > **Right click** > **More** > **Run as administrator** (5 steps)

It would be useful to **right click the terminal icon** and pick **Run as Administrator** (2 steps)

![image](https://user-images.githubusercontent.com/172594/64048703-5ab08300-cb6a-11e9-87f8-61db333096c1.png)

**Comment by DHowett-MSFT** [comment]
This is going to end the same way as all the other elevation work items.

**Comment by mikemaccana** [comment]
@DHowett-MSFT  I get that the Terminal instance can't start a Admin tab (from all the prior discussions). 

 - Are you 100%sure the taskbar can't launch a separate window with a second instance as admin when the Start menu can? 
 - How can the Start menu do it and the task bar cannot?

**Comment by mikemaccana** [comment]
@DHowett-MSFT Checking this out, the console invoked by Powershell 5 already does this:

![image](https://user-images.githubusercontent.com/172594/64052640-3e671300-cb77-11e9-8146-7869a0a65183.png)

**Comment by zadjii-msft** [comment]
I mean, the taskbar already _can_:
![image](https://user-images.githubusercontent.com/18356694/64181018-5a92da80-ce2b-11e9-9f6e-8f50182f4506.png)

That's right click the Terminal taskbar icon, right click again, then click to launch as admin.

That's _three_ steps, which isn't 2, but is certainly better than 5.

If we did want to support this, we'd certainly need to reconcile the jumplist items with #689. We'd need support for launching another instance of ourselves elevated, which I'm sure is tracked with some other issue somewhere. Then we'd need #607 support to have the jumplist item be able to indicate the new instance should be launched as a new elevated window.

**Comment by mikemaccana** [comment]
Ah thanks for the clarification @zadjii-msft. Yes, a top-level jump list item would be helpful:

 - Previous Windows terminals have had a top level jump list item

 - two steps is better than three, particularly for a common action like launching an admin shell

 - as a user I didn't discover you could right click the name of the app in the jumplist to launch an admin version until you told me.

**Comment by mikemaccana** [comment]
PS @zadjii-msft if adding a top level 'Run as Admin' to the jump list is cool with you, could you reopen? Thanks! 🙂

**Comment by amithegde** [comment]
I start my console as admin all the time because of the dev workflow. Starting terminal as admin in one click is very important to me. For example, I have setup my ConEmu to start as admin from taskbar by going into properties like this:

![image](https://user-images.githubusercontent.com/816051/64925095-8c4b6000-d7a0-11e9-9b4b-1670929e96a9.png)

If you can consider including the `Properties` there it will be helpful👍

**Comment by DHowett-MSFT** [comment]
> If you can consider

We don't actually have control over that -- it's hidden because we're a "Centennial" application ☹️

**Comment by amithegde** [comment]
> > If you can consider
> 
> We don't actually have control over that -- it's hidden because we're a "Centennial" application ☹️

That means I will need 3 clicks every day instead of 1. I see it's a limitation enforced by the system here.🤦‍♂️

As I see it, application like terminal are for power users and we kind of expect these features to simplify our workflow. Painting ourselves into a corner is not that great in my opinion.

**Comment by Biswa96** [comment]
> That means I will need 3 clicks every day instead of 1.

AutoHotKey may help!

**Comment by mdtauk** [comment]
Add this to the list of asks for WinUI Desktop API wrappers :)

**Comment by DHowett-MSFT** [comment]
@mdtauk this ask is strictly on the people who own app installation and activation. WinUI Desktop applications will _probably_ run in the same Centennial container as Terminal does, and this is likewise out of their control.

**Comment by mdtauk** [comment]
Ah, so WinUI Desktop Apps may not get low level access to the Taskbar APIs then.

Hopefully the OS team will allow more entry points into the current and Modern Shells - even if it requires a permissions dialog :)

**Comment by DHowett-MSFT** [comment]
It's not even a question of access to taskbar APIs. You'll notice that you can use the shortcut features on an application you've never launched! That's all handled by the shell and is specific to standard shell shortcuts. :smile:

**Comment by mdtauk** [comment]
As I understand it, its in the application manifest from Vista onwards.

So what technical change would need to be made, which would allow at the very least, the ability to launch an instance from the taskbar as Administrator?

**Comment by zadjii-msft** [comment]
> If we did want to support this, we'd certainly need to:
>   * reconcile the jumplist items with #689. 
>   * We'd need support for launching another instance of ourselves elevated, which I'm sure is tracked with some other issue somewhere.
>   *  Then we'd need #607 support to have the jumplist item be able to indicate the new instance should be launched as a new elevated window.
