### ISSUE TITLE
VS2019.3 wapproj changes broke our precarious packaging situation

### ISSUE THREAD

**Issue by mdtauk** [microsoft/terminal#2625]
# Environment

```none
Windows build number: 18362.327
Windows Terminal version (if applicable):Build from VS 2019, 01:12 2019/08/31
```

# Steps to reproduce

- I have selected CascadiaPackage as the Startup Project
- I have set x64 and done Build and Deploy
- When I try to run Windows Terminal, I get a window outline and shadow, and a crash dialog

# Expected behavior

I expect the app to build, deploy, and be able to run

# Actual behavior

![image](https://user-images.githubusercontent.com/7389110/64056651-c86da680-cb8c-11e9-923d-a96a7f808d9e.png)

**Comment by DHowett-MSFT** [comment]
Psychic debugging: VS 2019 Update 3 Preview?

**Comment by mdtauk** [comment]
> Psychic debugging: VS 2019 Update 3 Preview?

![image](https://user-images.githubusercontent.com/7389110/64057063-834b7380-cb90-11e9-8434-a2105285ad6d.png)
Preview 2

**Comment by DHowett-MSFT** [comment]
I'm just going to repurpose this one for its real cause. Thanks.

**Comment by xpwn3rx** [comment]
Just cross posting from #2587 - This was working on Preview 2, then broke after some updates to 2 I guess. It is also broken in 3. Everything I've tried is not working.

**Comment by mdtauk** [comment]
```
Exception thrown at 0x00007FFDF6C8A839 in WindowsTerminal.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000DB2290DB38
```

**Comment by xpwn3rx** [comment]
#2587 is not fixed with this set of changes. The terminal still crashes on startup.

**Comment by mdtauk** [comment]
I have just successfully Cleaned, Built and Deployed the project, and I am able to run the terminal now!

**Comment by xpwn3rx** [comment]
#2587 is fixed now. Thanks!
