### ISSUE TITLE
releasenotes say:"The shell can read and change this title. ", but how to read title?

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#2627]
Version 0.4

Releasenotes say:"The shell can read and change this title. ", 

but how to **read** title?

I know changing can be down with TITLE (in command prompt)

**Comment by PhMajerus** [comment]
The shell can do it through the Win32 API function GetConsoleTitle(A/W)
https://docs.microsoft.com/en-us/windows/console/getconsoletitle

As far as I know, cmd.exe doesn't provide any built-in command to do it, but some other shells do, and an external command could easily be built to provide the functionality to cmd.exe.
![AXSH Title set](https://user-images.githubusercontent.com/25664275/64075471-25ff1180-ccb9-11e9-8bbd-cb00cbc7ebd6.png)

**Comment by DHowett-MSFT** [comment]
This is the correct answer. Thanks!
