### ISSUE TITLE
Digital keypad cannot be recognized by keyboard shortcuts

### ISSUE THREAD

**Issue by lvzhuangzhuang** [microsoft/terminal#2628]
Shortcuts I bind to
 {
                "command" : "newTabProfile6",
                "keys" : 
                [
                    "ctrl+3"
                ]
            },
Not working properly when using numeric keypad

**Comment by JasonHK** [comment]
Could you please use English to describe the issue? Not everyone here can understand Chinese.

**Comment by DHowett-MSFT** [comment]
Unfortunately, the `3` key on the top of the keyboard and the `3` key in the number pad are _different keys._

Try this:

```json
{
"command" : "newTabProfile6",
"keys" :
[
"ctrl+numpad_3"
]
},
```

**Comment by lvzhuangzhuang** [comment]
thinks
