### ISSUE TITLE
Open Windows Terminal here

### ISSUE THREAD

**Issue by schonz** [microsoft/terminal#2629]
# Description of the new feature/enhancement
It would be great if you could implement the "Open PowerShell window here" ability and have it open a new tab in the Windows Terminal CD'd into the specified directory. Would save a bunch of time.

**Comment by j4james** [comment]
This sounds like a duplicate of #1060.

**Comment by schonz** [comment]
Yup it is, thanks for pointing me to it. I'll close this and +1 that thread
