### ISSUE TITLE
Bug Report: initialRows (or buffersize) doesn't get updated on windows size changes

### ISSUE THREAD

**Issue by Vreyesm** [microsoft/terminal#2630]
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.18362.295]
Windows Terminal version: 0.4.2382.0
```

# Steps to reproduce

1. Set the `initialRows` value to something like 30 rows (a value that makes the openned window has less rows than the maximized window should have).
2. Maximize the window.
3. Run some command with a lot of output (like `ps`, `ls`or `dir`).

# Expected behavior

- The buffersize setted with `initialRows` gets updated after window size changes.
- Behavior on PowerShell.
![image](https://user-images.githubusercontent.com/12416901/64070190-a6763180-cc29-11e9-892d-8ffa4d3f9e24.png)

![image](https://user-images.githubusercontent.com/12416901/64070158-146e2900-cc29-11e9-9c70-903fbe72662c.png)

# Actual behavior
- After maximizing the window and running `ps` the buffer size setted with the `initialRows` value doesn't get updated after the window size changes. 

![image](https://user-images.githubusercontent.com/12416901/64070198-d7566680-cc29-11e9-8278-8b4fe5c8b138.png)

![image](https://user-images.githubusercontent.com/12416901/64070205-e3dabf00-cc29-11e9-88f4-45e3500f15b2.png)

- The problem gets solved if I open a new tab and run the command again.
![image](https://user-images.githubusercontent.com/12416901/64070208-f1904480-cc29-11e9-9705-5ebc57e0b609.png)

**Comment by zadjii-msft** [comment]
@Vreyesm Out of curiosity, does this repro if you execute `Remove-Module psreadline` before maximizing? Does it repro if you switch the default profile to `cmd`?

**Comment by Vreyesm** [comment]
@zadjii-msft Executing `Remove-Module PSReadline` doesn't make any changes on the behavior, but if I change the default profile to `cmd` (or  `wsl` running ubuntu 18.04) as you suggest, the problem gets solved (following the steps described above).

**Comment by hwinkler** [comment]
I too have this problem as described, yet my default profile is `wsl` Ububtu 18.04.

I can confirm the workaround described, opening a new tab: the new tab doesn't have the problem. Thanks for that tip.

**Comment by zadjii-msft** [comment]
Hey so while burning down bugs, it looks like this is the same bug as #2815. This one was filed first, but the other one's got a bit more details on the specific root cause of the problem, so I'm going to mark that one as the parent bug. **Regardless**, I've got a fix ready for these that should be in PR later today. Thanks!

/dup #2815

**Comment by f9analytics** [comment]
Any idea when this buffer resize issue will have a fix? If I run a normal cmd the screen adjusts, if I run in Windows Terminal I get [process exited with code 4294967295] {See Image-1 }. If I manually expand the window, and rerun, everything works fine {See Image-2 }.

**Image-1**
<img width="825" alt="Error" src="https://user-images.githubusercontent.com/61324207/83191205-77252000-a0e8-11ea-9a9f-c50e91360b14.png">

**Image-2**
<img width="887" alt="Ok" src="https://user-images.githubusercontent.com/61324207/83191490-f4e92b80-a0e8-11ea-81ab-a8bc1add2252.png">

**Comment by zadjii-msft** [comment]
Oh, that's probably #4062 or #5094, or some combo of the two

**Comment by f9analytics** [comment]
@zadjii-msft - I believe it is thrown due to SetCursorPosition. Please See Below: 

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 30.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)

Any thoughts? thx

**Comment by f9analytics** [comment]
@zadjii-msft - I think I found the issue. The old school conhost.exe apparently auto resizes buffer rows without any explicit setting. If I set the console buffer height explicitly. No error. It works as intended. perfectly. Please let anyone know that had similar issue.

Thanks again msft.
