### ISSUE TITLE
actually there are 4 tabs, but only 3 tabs are displayed in the title bar!!!

### ISSUE THREAD

**Issue by oceanMIH** [microsoft/terminal#2632]
actually there are 4 tabs, but only 3 tabs are displayed in the title bar!!!
![image](https://user-images.githubusercontent.com/28834785/64071571-8721e780-ccaf-11e9-93cd-9371b52e3dd3.png)

**Comment by encladeus** [comment]
This is a duplicate of #857.

**Comment by DHowett-MSFT** [comment]
/dup #857

Thanks @encladeus!
