### ISSUE TITLE
Improvements for the application header

### ISSUE THREAD

**Issue by gulshanmudgal** [microsoft/terminal#2633]
# Description of the new feature/enhancement

If the path can be moved to header and just use the binary name as Tab Name (With Tab Renaming for distinction). I feel this would make the terminal much more useful.

# Proposed technical implementation details (optional)

I would suggest to make the Tab Interface two Layered stacked vertically, basically two rows. how it is implemented as of now is, the whole tab interface is on the header itself, i would suggest if header area(First Row) displays the path of the active tab and in 2nd row tabs are there displaying just the binary name would work better. for distinguishing between two same tabs the user should have ability to rename the tab.

If in future split screen is coming, such an interface would make much more sense, in my opinion.

**Comment by mikemaccana** [comment]
Maybe edit this and give the feature request a name other than 'feature request'? 😉

**Comment by DHowett-MSFT** [comment]
1. You can set the tab name to whatever you'd like using shell magic (documentation to be written)
2. We're trying to track the UI nits in #1375; please pile in there!
