### ISSUE TITLE
Clicking on window without dragging causes a selection

### ISSUE THREAD

**Issue by Molanda** [microsoft/terminal#2636]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.4.2382.0
```

# Steps to reproduce

Click on the terminal window without dragging.

# Expected behavior

This should clear any existing selection but not create a new one.  This is consistent with other Windows programs which only show a selection when the cursor is dragged.

# Actual behavior

A character is selected.

**Comment by DHowett-MSFT** [comment]
Today, this is by design. We don't act like other Windows applications that emit text because they have a _selection caret_, and we don't. We've been talking about the right behavior here for a while, and we decided that in the "default" configuration we'd match the existing console, which does work like this.

We recently added `copyOnSelect` which, while it does add the eponymous copy-on-select, also suppresses single-character selection (you must click and drag to another cell before selection begins.)

I'm going to mark this one by-design for now. Thanks/sorry!

**Comment by Molanda** [comment]
Thank you for your response.  I understand the current decision, but would like to add some additional details for consideration.

- Not all application that emit text have a _selection caret_.  The most notable example is the web browser (excluding form fields).  If you click on text in a browser, no selection happens unless you also drag.  PuTTY is another example where a drag is required to select.
- If anything, creating a block on click gives the false visual impression that the cursor has been moved.
- The existing console has the ability to turn off _QuickEdit_ mode.
- While the behavior matches the existing console, it really offers no value.  If someone clicks the window to the front, their next move is extremely unlikely to be to copy the random character that is  now selected.

I will try the copy-on-select once released (I have the build from the Microsoft Store).

**Comment by garth** [comment]
>  it really offers no value

I could not agree more with this observation. This needs to be an option. eg 'selectOnClick'?

**Comment by DHowett-MSFT** [comment]
For what it's worth, I agree. Selection is a charged topic, though, as we've well seen.

If you enable `copyOnSelect`, terminal disables single-character selection. If that's an acceptable compromise, we can leave it at that and evaluate more robust selection settings as we go forward. :smile:

**Comment by ryanmortier** [comment]
This is such a terrible user experience.

**Comment by DHowett-MSFT** [comment]
Thanks for your feedback. It's a good thing we fixed it in #5096.

**Comment by Molanda** [comment]
Awesome news!

**Comment by ryanmortier** [comment]
This is great news, thanks so much.
