### ISSUE TITLE
CMD is opening, showing a series of errors and closing immediately.

### ISSUE THREAD

**Issue by techie-explorer** [microsoft/terminal#2637]
# Environment
Windows build number: [18970.1005] (but this problem is there from the last 3 builds
Windows Terminal version (if applicable):

# Steps to reproduce

Just open the cmd in windows terminal.

# Expected behavior
Expected to open normally as usual.

# Actual behavior

Getting the following series of statements as arguments for the cmd.exe and closing immediately.

1. mode 20.5
2. tasklist /F1 "IMAGENAME eq SoundMixer.exe"
3. find /I /N "SoundMixer.exe"
4. start /MIN "" "C:\Users\farhan\AppData\Roaming\Microsoft
5. tasklist /FI "IMAGE NAME eq explorer.exe"
6. find /I /N "explorer.exe"

**Comment by DHowett-MSFT** [comment]
This sounds like some sort of terrible OEM script doing something on startup. Please check the _Startup_ tab in Task Manager to see if there's anything unexpected in it.

We don't have control over what the startup scripts on your computer do; sorry!

**Comment by DHowett-MSFT** [comment]
By the way, there's a legitimate non-zero chance that you've got [some malware](https://www.reddit.com/r/windows/comments/8x1apa/i_cant_use_cmd/). That post describes the exact same behavior.

**Comment by techie-explorer** [comment]
I don't think so. This started to happen exactly after I upgraded to a new Insider build. Not a malware for sure! And there are no startup programs. Not even 1. Powershell and bash are working super fine. But cmd went mad in some way. I remember SoundMixer being some module used when Cortana tries to listen to us. Pretty sure it has something to do with Cortana's new beta build.
