### ISSUE TITLE
Add support for short hex color codes (like #CCC)

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#2639]
Windows 10.0.18908.0. Terminal Preview 0.4.2382.0

Using `#CCC` instead of `#CCCCCC` results in an unparsable settings file. Not a big deal but since most other places (eg browser devtools)) that take hex also take short codes, worth fixing. 

Not sure re: HSLA etc but that's a separate issue.

**Comment by DHowett-MSFT** [comment]
Yeah, we should probably support this. The first thing, not the HSLA thing.

**Comment by kojoru** [comment]
Should be a few lines' worth of change around https://github.com/microsoft/terminal/blob/c97cccb55c393856f92b714970fd3f53224afa19/src/types/utils.cpp#L92 right?

Can I try and take a stab at it?

**Comment by zadjii-msft** [comment]
@kojoru go right ahead!

Bonus points if you add a test [in here](https://github.com/microsoft/terminal/blob/master/src/types/ut_types/UtilsTests.cpp) :)
