### ISSUE TITLE
Crash on launch / creating new tab when using RDP

### ISSUE THREAD

**Issue by mtanatwine** [microsoft/terminal#2646]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): 0.4.2382.0_x64

Any other software? 
- Remote Desktop
- Not sure if relevant, but Ubuntu WSL is the default profile

```

# Steps to reproduce

1. Use RDP to access your device
2. Either start the terminal fresh, or close a tab, or try to open a new tab.

# Expected behavior

Terminal should open / tab should open / close.

# Actual behavior

The terminal will not start when using RDP to connect to my laptop. It brings up the outline, then crashes (eventvwr log below). It will also crash if I try to close a tab or open a tab. General use, like switching tabs or generally interacting with the window (resizing, maximising, etc.) works fine. This is reproducible 100% of the time. It never fails to open when I'm physically on the device, but it is intermittent if I can then switch to RDP and continue to use it. Potentially related to #2183?

EDIT: I've done some more fiddling and by going into the graphics settings and by forcing the app to use the "Power Saving" (onboard) GPU, it launches and works via RDP as intended.

Faulting application name: WindowsTerminal.exe, version: 1.0.1908.26002, time stamp: 0x5d641823
Faulting module name: ucrtbase.dll, version: 10.0.18362.267, time stamp: 0x080a13f7
Exception code: 0xc0000409
Fault offset: 0x000000000006d33e
Faulting process ID: 0x54d4
Faulting application start time: 0x01d562452690fb35
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.4.2382.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 7edb0c83-abc5-43dc-b02f-f1bb04084933
Faulting package full name: Microsoft.WindowsTerminal_0.4.2382.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by mtanatwine** [comment]
Feedback Hub link here: https://aka.ms/AA6017r

**Comment by DHowett-MSFT** [comment]
I think we might have fixed this in one of our recent crash purges. Would you mind seeing if this still repros? We were never able to hit it ourselves. Thanks!

**Comment by mtanatwine** [comment]
Sorry for the delay in responding, completely forgot about this and the use case wasn't as prevalent anymore. I can verify that it is indeed resolved.
