### ISSUE TITLE
Tabs do not auto-shrink when a new tab being opened would place that new tab outside of the tab bar. Major pain point in environments where shell writes long text to the tab bar causing only 2 tabs to be available. 

### ISSUE THREAD

**Issue by mstoaster** [microsoft/terminal#2648]
# Environment

Microsoft Windows [Version 10.0.18362.295]

Any other software?
Not applicable

# Steps to reproduce

Open multiple tabs

# Expected behavior

As the number of tabs increase, I would expect the tab bar to behave like tabs from a web browser: the size of the tab would shrink in order to make space for the newly created tab. 

If the above doesn't happen, I would expect a setting that would limit how much text is displayed in a particular tab, so that one long tab doesn't take the entire tab bar real-estate. 

# Actual behavior

Tabs do not shrink nor is the text in one tab limited, causing one tab with a lot of text to take up the entire tab bar real estate. 
The new tabTitle setting does not fix this issue, since long tab bars are created by the shell writing to them (such as a Razzle build environment).

**Comment by DHowett-MSFT** [comment]
/dup #597 #857

From the interface megathread #1375 

> #597 Without using tabs don't shrink/expand like browser tabs / I want to set a min width for my tabs / I want a fixed width for my tabs / I want tabs to expand to split the available space / any other possible tab sizing
