### ISSUE TITLE
Tab title not getting set appropriately

### ISSUE THREAD

**Issue by LarsBehl** [microsoft/terminal#2649]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version: 0.4.2382.0

Other Software: WSL1 Ubuntu 18.04
```

# Steps to reproduce
Open Windows Terminal. Open new Ubuntu tab.

# Expected behavior
Tab title should be the profile name

# Actual behavior
Tab title still shows current directory.
![tabTitle](https://user-images.githubusercontent.com/26459044/64196166-88a40900-ce83-11e9-9d99-108ab479d492.PNG)

# Note
I did also try to change the title via the settings, but it had no effect.
[profiles.txt](https://github.com/microsoft/terminal/files/3570781/profiles.txt)

**Comment by DHowett-MSFT** [comment]
From our blog post:

> 👉 Note: The shell title is overridden in WSL distributions because the default shell configuration in many distros sets the window title before every prompt. You can change this behavior in your bash or ZSH profiles in /etc.

**Comment by nishp77** [comment]
It does show the title bar for like some while that is may be 2 seconds then it changes and show the path for user profile
