### ISSUE TITLE
Support for Windows 10 LTSC 

### ISSUE THREAD

**Issue by duanyukai** [microsoft/terminal#2650]
# Description of the new feature/enhancement
Support for Windows 10 LTSC 

# Proposed technical implementation details (optional)
Windows 10 LTSC doesn't support Windows Store Apps, but the terminal is an essential part of daily management.

**Comment by DHowett-MSFT** [comment]
Sorry. We require features that only exist on Windows 1903. If those features can be used on older versions in the future, we will reevalute this.

**Comment by Andrew-Hanlon** [comment]
@DHowett-MSFT Would you be able to provide details (or a link to more information) on which features require 1903+? Thanks!

**Comment by zadjii-msft** [comment]
There's a bunch of threads on this already, but the main one is the Xaml Hosting "XAML Islands" APIs that the Terminal uses to host UWP XAML UI elements in a desktop application.

**Comment by pedro2555** [comment]
This crap moved me into Linux. Really tired of fighting the OS.

**Comment by five23** [comment]
Lame.
