### ISSUE TITLE
Can't change into hinese

### ISSUE THREAD

**Issue by applejwjcat** [microsoft/terminal#2667]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

不能切换中文输入法

**Comment by zadjii-msft** [comment]
From a really rough internet translation of this issue, I'm going to _guess_ that this is #2213. Feel free to correct me if I'm wrong.

/dupe #2213
