### ISSUE TITLE
Crash when running random commands

### ISSUE THREAD

**Issue by drichardson** [microsoft/terminal#2669]
Windows Terminal sometimes crashes when I run commands. [Feedback Hub Report here](https://aka.ms/AA604mm).

# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0
PowerShell 7.0.0-preview.3
```

# Steps to reproduce

No exact steps to reproduce. I'm using Windows Terminal (Preview) for a while, and after running a command it will crash.

For example, the last crash occurred when I ran the following subversion command:

```
svn cat ^/users/doug/Operations/Operations/Context.cs
```

However, I ran that command after the crash several times in a row with no issue.

# Expected behavior

My command should run without crashing Windows Terminal (Preview).

# Actual behavior

Windows Terminal (Preview) crashes.

# More Info

Anecdotally, the crashes seem to occur when I run commands that list files contents or spit out a lot of output (e.g., `gci -Recurse .`).

**Comment by drichardson** [comment]
@DHowett-MSFT I already included the feedback hub link.

**Comment by DHowett-MSFT** [comment]
Whoops, you definitely did. Sorry about that.

**Comment by DHowett-MSFT** [comment]
Does this tend to happen more, would you say, when you've created and closed a few tabs?

**Comment by drichardson** [comment]
@DHowett-MSFT I'm not certain, but I do use tabs frequently.
