### ISSUE TITLE
Start Menu tile color should be customized

### ISSUE THREAD

**Issue by brianblakely** [microsoft/terminal#2679]
# Description of the new feature/enhancement

Windows Terminal's Start Menu tile uses whichever color the OS theme is using.  Maybe it can have a nice custom color?

# Proposed technical implementation details (optional)

Perhaps a Campbell Blue, or a more universal Sysadmin Black?

**Comment by mdtauk** [comment]
**IF** an option to change the Tile colour is added, there should be a way to keep it Transparent.

The tile colour setting would have to be per-app, and not linked to profiles.

**Comment by brianblakely** [comment]
Please note that I'm not suggesting a "customizable" tile, but one which does not use the OS theme color ("customized").

**Comment by mdtauk** [comment]
> Please note that I'm not suggesting a "customizable" tile, but one which does not use the OS theme color ("customized" by the Terminal developers).

That is what I read into your request, I just like to be able to use my Accent Colour for the tiles, and would not want it to change, without the ability to "undo" that change. 😃

**Comment by zadjii-msft** [comment]
For the record, I believe you may have stumbled into a [holy war](https://www.reddit.com/r/Windows10/search?q=tile+color&restrict_sr=on&include_over_18=on&sort=relevance&t=all). 

I'm not saying this as a designer or as someone with any UX expertise, but I'm not sure there is a consistent pattern here, either having a color or not. @cinnamon-msft might be able to hook us up with someone who _does_ know.

**Comment by zadjii-msft** [comment]
Hey I'm gonna go out on a limb - with the changes to the Start Menu in [recent insider's builds](https://blogs.windows.com/windowsexperience/2020/07/01/announcing-windows-10-insider-preview-build-20161/), maybe we shouldn't bother with this?

**Comment by DHowett** [comment]
Agreed.
