### ISSUE TITLE
Terminal crashes on any text copy

### ISSUE THREAD

**Issue by tomcss** [microsoft/terminal#2685]
# Environment

```none
Windows build number: Win32NT 10.0.18362.0
Windows Terminal version (if applicable): v0.4.2382.0

```

# Steps to reproduce

Go to About screen, select text, right click, copy -> Crash
Select text if auto copy is enabled -> Crash
Select text and right click, copy -> Crash

# Expected behavior

Expected behaviour is to have the selected text copied to the clipboard.

# Actual behavior

Terminal becomes unresponsive for a second, then disappears.

**Comment by hoxha-saber** [comment]
Hi, I followed the steps to reproduce but my terminal doesn't seem to crash...

I have the same terminal version but I'm running Windows [Version 10.0.18362.295]

**Comment by tomcss** [comment]
Are you running a 32 bit or 64 bit version of windows?

**Comment by robbarry** [comment]
I'm having the same issue.

Windows build number: x64 Windows 10 Enterprise Insider Preview 18936.rs_prerelease.190705-1333.
Windows Terminal version: v0.4.2382.0

**Comment by hoxha-saber** [comment]
> Are you running a 32 bit or 64 bit version of windows?

64 bit

**Comment by AnnatarHe** [comment]
same issue.

windows 10 pro 64 bit
OS build: 18362.295

**Comment by RevThreat** [comment]
So, same issue, it seems to happen if it has idled for a minute or two and then you go to use it, but also have seen it crash on text, really annoying. was ssh'd into a server setting up a multi api key tool, and quit right at the end, had to do it over.. I will try to get some logs for it..

**Comment by DHowett-MSFT** [comment]
The fix for this was committed, we just need to produce a servicing release for it :smile: sorry for the inconvenience.

**Comment by DHowett-MSFT** [comment]
And for those of you keeping track at home, that’s /dup #2570
