### ISSUE TITLE
Terminal takes long time to appear when launched elevated/as-admin

### ISSUE THREAD

**Issue by Kettoch** [microsoft/terminal#2687]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): Version: 0.4.2382.0

Any other software?
Office C2R
SSMS 18.2
VSCode

# Steps to reproduce

- Right-Click app from start menu
- Fill in appropriate credentials

# Expected behavior

Expecting a copy of Windows Terminal to load.

# Actual behavior

Nothing after entering credentials.   Looking in task manager, WindowsTerminal.exe does not seem to load.

This was not built, this was the preview through the store.

**Comment by someniatko** [comment]
It looks like it is Windows issue. I have downloaded Notepad++ from the Store and I also cannot run it as an admin. It shows up two consecutive UAC prompts, then fails with an error. The Terminal does the same thing.

**Comment by Kettoch** [comment]
Not sure if this link helps, but it might.
[How to change the Manifest](https://stefanwick.com/2018/10/01/app-elevation-samples-part-1/)

**Comment by bitcrazed** [comment]
> Note to all: We're investigating this internally with the app plat team and will report back here when we get a resolution.

We managed to repro this yesterday while on work machines connected to Microsoft's corporate network, but cannot on this machine at home! We suspect some interaction with AD/AAD/etc.

Stay tuned for updates if you're affected by this issue. If possible, [please submit feedback via Feedback Hub as requested above](https://github.com/microsoft/terminal/issues/2687#issuecomment-528876664).
