### ISSUE TITLE
Feature Request: Add a setting that disables HTML copy

### ISSUE THREAD

**Issue by amazingant** [microsoft/terminal#2690]
# Description of the new feature/enhancement

The new HTML copy feature introduced in `v0.4.2382.0` may not always be desirable, and removing the formatting typically means either opening a text editor like Notepad, pasting the text, and then copying it again, or asking the receiving application to strip formatting. When text is copied out of the terminal on a regular basis, this small delays can add up a bit, and suck up time in someone's day. For cases where a user knows this is going to happen to them frequently, it would be helpful if there were a setting that could disable the HTML copy feature.

If entirely disabling HTML copy is undesirable, under the assumption that users may still want to keep formatting sometimes, another possible option would be to provide separate key bindings that behave the "old" way. However, admittedly with no experience with the codebase, this seems like it would be more work.

**Comment by DHowett-MSFT** [comment]
As an aside, what application is serving as the destination that doesn't support "Paste [as] Plain Text"?

**Comment by amazingant** [comment]
The last place I pasted before leaving work today was the web version of outlook, which actually does have the option to paste as plain text - but it's in a context menu that has to be clicked and has no keyboard shortcut. I have a tendency to copy something out of the terminal, start typing an email, and then press Ctrl+V, only to find that I've pasted colored text with a dark background into my email.

Like I said in the original post, it's a small delay; it's just a new delay that wasn't there before the last update, in exchange for a feature I wasn't really looking for and typically don't want to use.

**Comment by bitcrazed** [comment]
When copying text to the clipboard, Terminal copies both the plaintext, and HTML text. Applications that can handle both generally allow you to paste content keeping source formatting, keeping target formatting, or pasting plain text. This is available via the context menu (<mouse>right-click</mouse> / Keyboard: <kbd>right-context-menu-key</kbd> / <kbd>SHIFT</kbd>+<kbd>F10</kbd>) and is a well understood, and well supported behavior by most rich-text apps/tools.

**Comment by amazingant** [comment]
@bitcrazed Thanks, but as I mentioned above, the place I'm mostly running into this *does* support these options via a context menu after I paste. In the web version of outlook, right clicking and using the keyboard shortcuts mentioned just bring up my browser's context menu, which only includes "paste".

**Comment by bitcrazed** [comment]
@amazingant When I hit the context key / <kbd>SHIFT</kbd>+<kbd>F10</kbd> in Outlook online, I see a context menu that offers me both `paste` and `paste as text`:

![image](https://user-images.githubusercontent.com/961950/64653493-6d814e00-d3db-11e9-9c49-4d905b8b7b65.png)

This MAY be because I am running a preview release of Outlook online, and if so, its likely this will be publicly released before long.

**Comment by amazingant** [comment]
Nope; that's Chrome's default context menu, I use Firefox. :)

**Comment by bitcrazed** [comment]
Then this would be a great bug to file on the Firefox team. It is 2019 and the Clipboard's ability to contain content in multiple formats has been there for at least 20 years.
