### ISSUE TITLE
There is no merits in one-liner text terminal prompt - go full-blown text windows

### ISSUE THREAD

**Issue by sq2500** [microsoft/terminal#2691]
# Description of the new feature/enhancement
There is no merits in one-liner text terminal console - boldly use proper text IDE windows
- With 2K, 4K display "estate" it make absolut no sense to stick with one-liner prompt
- enable use multiple split views windows like a text editor.

Enables better integration between traditional keystroke shortcuts UI, GUI and mouse-clicks.
One-line prompt were invented in days with limited resources.

Today Console UI's does not need in those "exact" foot steps - proper editor windows would supplement console UI more conveniently with features such as history, searches, line numbers (easing scripting editing).

Multiple split views windows would resemble more loading text files, interactive interpreter.
VS Code has most of the plumping, lineby-line debugging already, shortcuts easy accessible by and re-assignable in windows UI.

Features like on-the-fly filenames highlighting (current folder, folders in the path), Output redirection, Output Error codes & Hyper Linking, Line numbers etc. could be implemented with much less effort.

Text-click selection expansion similar to Excel cell selection range expansion.
Browser like ALT+click to open/launch/clipboard/buffer copy for selected text.

MDI split screen views for file load, file save, history will be easier to support etc.)

Combination of both GUI keyboard shortcuts, traditional console keyboard shortcuts enable larger user base, make it easier for newbies.

Traditional Console keyboard short should take precedence, but at same time allow colliding GUI keyboard shortcuts by keyboard modifier keys.
F. ex.: WIN key ==> GUI, CTRL/ALT/SHIFT key ==> console
- "standard" keyboard shortcuts could be used in a larger context, quickly become "natural"
- configurable mouse-click interact with the console prompt

Enables higher level of Terminal console UI interaction with Windows GUI applications.

# Proposed technical implementation details (optional)
Split screen buffer views: 0..9, Q-P (scrollable splitview windows)
Side by side buffer views for copy/paste/diff/highlighting

"Standard" window buffers available for copy/paste/search/replace/regexp (NFA)
Buffer 0: Clipboard Text
Buffer 1: Search, Replace output
Buffer 2: Filenames, symbol links, (folder view)
Buffer 3: Matched searches/replaced (like find all)
Buffer 4: Command History
Buffer 5: Filename History (recent filelist)
Buffer 6: Edit history (column-view of keystroke, filename, date/time like VS Code Ctrl+K+S)
Buffer 7: Diff history
Buffer 8: Regexp history
Buffer 9: Output history applications (stdout, stderr, date/time)

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
We have a policy against filing one issue that contains, like, a hundred feature requests. There's a whole bunch of these that have already been filed, and I really appreciate you taking the time to write this up. I'll break a couple of them down:

* One-line prompts
   * every shell in existence now allows you to customize your prompt -- and I think that by providing a short prompt by default we _encourage_ people to customize them.
* Split panes #1000
* Highlighting of directories, filenames
   * This shouldn't be provided by the terminal.
* Text-click selection expansion -- like, double-click and triple-click combined with dragging? That already exists as of 0.4
* All of our key bindings are customizable, and you can set key bindings that interact with the terminal UI
* configurable mouse bindings #1553

**Comment by sq2500** [comment]
I do not agreed, there might be some overlap
Please do a review by human

**Comment by DHowett-MSFT** [comment]
dude, I AM A HUMAN.

**Comment by sq2500** [comment]
OK, where do You see the duplicate - my core intent is to have more window like seamless integration of the terminal

**Comment by DHowett-MSFT** [comment]
Half of the things you asked for are possible today, with integration from the shell and some additional text-mode programs.

![image](https://user-images.githubusercontent.com/14316954/64465980-2554e980-d0c4-11e9-94b0-c7206cb30f4e.png)

**Comment by sq2500** [comment]
What do I need to cut or refrase?

**Comment by DHowett-MSFT** [comment]
Please review the work items I've linked to this one (#1553 #1000 #1933 #2285 #2046 #1595 #605) and consider filing _individual_ feature requests for the other ones you need. Some of these things are totally out of our control, though. The _shell_ (we do not own the shell) controls the prompt and the text editing experience. The other things, we'll have to discuss individually.

Thanks!

**Comment by sq2500** [comment]
OK - thanks for Your review
