### ISSUE TITLE
Guidance - Windows Terminal SEO - Finding help online

### ISSUE THREAD

**Issue by selfup** [microsoft/terminal#2693]
### Suggest a nickname or alias to Windows Terminal

Currently searching the internet for `Windows Terminal` and trying to find answers about this specific application is quite the task 🤔 

Typically end up finding `CYGWIN/MINGW/WSL/WSL2/CMD/POWERSHELL` instead of anything to do with `Windows Terminal`. I know this might just be an SEO issue, but keywords like `Terminal` and `Windows` are going to cover a lot of ground vs. being specific.

I am sure it's a bit late for this but is there a way we can associate `Windows Terminal` with another name that would make looking for answers easier?

For things like languages you can add `lang` at the end. Unclear what we could add here.

Would this fall under Accessibility?

Just like with `Rust` and `Go`. They are a bit awkward to search for but when you add `lang` at the end (`rustlang/golang`) the appropriate results come flying in. 

However this is quite hard because there are a lot of hits for `Terminal` combined with `Windows`.

I guess over time SEO will win out, but then it will make all the content for the other 20+ different terminal applications hard to find.

Just a thought 🙏 

***

Things like:

1. `winterm.exe`
1. `term.exe`
1. `win32term.exe`
1. `windows_terminal.exe`
1. `WinTerm`

Not saying these are ideal, but I hope they help get the point across?

**Comment by bitcrazed** [comment]
Hey @Selfup. Sorry - we're not going to be able to create a whole new phrase/nickname/etc. to refer to the Terminal for various practical, logistical, and legal reasons.

Over time, if you search for Windows Terminal, chances are that the search engines will find related articles/docs/posts more correctly than not.

Closing since there are no follow-up actions.

**Comment by selfup** [comment]
That is what I figured. I guess SEO will have to win out on this one. Thanks!
