### ISSUE TITLE
Cannot type chinese characters.

### ISSUE THREAD

**Issue by yx91490** [microsoft/terminal#2694]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version :  0.4.2382.0
Input method: the system defaut microsoft pinyin input method.
```

# Steps to reproduce

always.

# Expected behavior
the input method can switch to chinese mode, and can type chinese characters.

# Actual behavior
the input method  is always in english mode, and cannot type chinese characters .

**Comment by j4james** [comment]
This sounds like it might be a duplicate of issue #2213.

**Comment by yx91490** [comment]
> This sounds like it might be a duplicate of issue #2213.

oh, yes.
