### ISSUE TITLE
Copy Paste Error

### ISSUE THREAD

**Issue by ManojMaheshPatil** [microsoft/terminal#2695]
When I copy a text from some website or a pdf or anywhere else and paste it in Notepad,
everything is pasted in a single line, not the original format.
I am using Windows 10.
Can anyone please help!

**Comment by zadjii-msft** [comment]
@ManojMaheshPatil Are you using the Windows Terminal, or the legacy conhost.exe (which is launched when you run cmd.exe, powershell.exe, wsl.exe, etc.)?

What program are you running in the console/terminal that's generating the single line of output?

Are you holding Shift when copying?

This may be any of #1073 #2275 #1091

**Comment by bitcrazed** [comment]
@ManojMaheshPatil Closing this issue as it's unactionable.

Also, please follow [the instructions](https://github.com/microsoft/terminal/blob/master/doc/contributing.md) when filing issues, especially:

1) Complete the provided issue template as thoroughly as possible
1) Be sure to file an issue against a relevant project - Terminal has nothing to do with Notepad
