### ISSUE TITLE
UP arrow does not work in R session

### ISSUE THREAD

**Issue by GaaH** [microsoft/terminal#2701]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0

Any other software?
Powershell 6.2.1 or Powershell 5.1
R 3.6.1
```

# Steps to reproduce

Open a [R](https://cran.r-project.org/index.html) session then type any expression and evaluate it. Then the up arrow should retrieve older commands in the history.

# Expected behavior

The up arrow should retrieve older commands in the history.

# Actual behavior

The up arrow does nothing, even if the R history is in an expected state as showed by the `history()` function.

This bug occurs only in "Windows based" terminal, such as powershell and cmd, executed by Windows Terminal. This bug does not exist if R is run inside the *old* terminal. This bug does not exist either if R is running inside a ssh session inside powershell.

Windows Terminal -> Powershell -> R -> Bug
Windows Terminal -> CMD-> R -> Bug
Windows Terminal -> WSL Ubuntu 18.04 -> R -> Bug
Old terminal -> Powershell -> R -> No bug
Old terminal -> CMD -> R -> No bug
Windows Terminal -> Powershell -> SSH into a linux host -> R -> No bug

**Comment by zadjii-msft** [comment]
This might sound crazy, but could you open a old console window, run WSL, then run cmd.exe, then try the repro?

Running cmd.exe inside WSL will activate conpty, which is used to power the Terminal, and should help me narrow this bug down a bit.

**Comment by bitcrazed** [comment]
Related to #2397?

**Comment by zadjii-msft** [comment]
Might also be related to #2520

**Comment by GaaH** [comment]
> 
> 
> This might sound crazy, but could you open a old console window, run WSL, then run cmd.exe, then try the repro?
> 
> Running cmd.exe inside WSL will activate conpty, which is used to power the Terminal, and should help me narrow this bug down a bit.

I followed the steps you mentioned, and the bug is indeed present.

**Comment by GaaH** [comment]
It is indeed related to #2520 because pressing left or right arrow does not move the cursor. I use mostly emacs shortcuts (ctrl+b and ctrt+f) to move the cursor, that's why I didn't notice that.

#2751 describes the same issue.
