### ISSUE TITLE
windows 10 Pro 18950 Preview Vistual Studio 2019 is not working

### ISSUE THREAD

**Issue by jovanallhimal** [microsoft/terminal#2703]
Hello
Needs some help.

Cannot open the console

[logs.txt](https://github.com/microsoft/terminal/files/3592277/logs.txt)
 

at the end,  when I do > start .         and then select the file from the explore window,  OpenConsole.sln,  the visual studio 2019 opens but,  gives me error,  saying 

The following files were specified in command line, …...like in below picture....

![start](https://user-images.githubusercontent.com/53494829/64562222-6128c280-d301-11e9-96d9-a69dc1316759.PNG)
![start2](https://user-images.githubusercontent.com/53494829/64562223-6128c280-d301-11e9-8647-f14d74f03cdb.PNG)

Any idea what should I do  ?

Much appreciated.
thx

**Comment by zadjii-msft** [comment]
While I'm not sure this is related, it's definitely very odd to place your own files under `C:\Windows\system32`. Does this repro if you try just checking out the repo to somewhere else, perhaps `%userprofile%`?

**Comment by nishp77** [comment]
Hi, did you include the git submodules??

**Comment by jovanallhimal** [comment]
still no luck

![start3](https://user-images.githubusercontent.com/53494829/64576824-462d7100-d348-11e9-8505-b436b5d283ea.PNG)
![start4](https://user-images.githubusercontent.com/53494829/64576825-46c60780-d348-11e9-87c5-bb5d8ba9be2f.PNG)
![start5](https://user-images.githubusercontent.com/53494829/64576826-46c60780-d348-11e9-9672-db5a72c46bed.PNG)


the logs are here... 

Anybody has any suggestions

[buildlog1.txt](https://github.com/microsoft/terminal/files/3593219/buildlog1.txt)

**Comment by jovanallhimal** [comment]
sorry that I had to change the subject head line.  It is 18950,  Windows 10 Pro Preview Build 18950.

**Comment by WSLUser** [comment]
I will mention while I might get issues building with VS2019, opening the project works well. I would prefer Code but since you can't build as easily VS2019 it is. I'm on the latest Windows 10 stable aka 1903 with Preview3 installed.

**Comment by zadjii-msft** [comment]
@jovanallhimal Sorry for the delay responding, was this ever resolved? Looking through the build log, it looks like the TerminalControl and TerminalSettings projects definitely _didn't_ build for some reason or another, though it's unclear why. 

Does this still repro for you on a fresh pull of `master` with an updated VS install?
