### ISSUE TITLE
Opening a WSL tab really quickly upon sign in does not add Windows Paths to PATH variable

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/terminal#2707]
# Environment

```none
Windows build number: 18972

Any other software?: WSL installed
```

# Steps to reproduce

- Sign out of Windows
- Sign back in
- Start Terminal really quickly and open up a WSL instance
- The WSL instance does not have Windows file paths connected to it (e.g: typing in `cmd.exe` fails)

# Expected behavior

- Even if you open up WSL quickly it should add Windows paths correctly. 

# Actual behavior

- Opening WSL quickly from Windows Terminal upon signing in does not add in Windows file paths correctly

# Additional notes

We (the WSL team) don't think this is a WSL specific issue since we use environment variables to add the Windows path. If you open up a CMD window and run `wsl` very quickly upon startup you still get the correct Windows paths added. This seems to be an issue with how Windows Terminal treats environment variables.

**Comment by DHowett-MSFT** [comment]
Windows Terminal _doesn't_ treat environment variables in any particular way. Perhaps this is #1125?

**Comment by DHowett-MSFT** [comment]
Unless WSL is somehow loading the user's `PATH` from some source other than _the actual active environment_, there's nothing we can do about this. `PATH` is set by winlogon when you, you know, log on. 🤷‍♂
