### ISSUE TITLE
Under terminal Folder there is Windows Terminal App??

### ISSUE THREAD

**Issue by nishp77** [microsoft/terminal#2709]
Hi I would like to understand where to begin from, that is the windows terminal folder under the terminal folder , is that the app?? . I'm sorry but i don't know where to begin from. Please would someone help on where to begin from.

**Comment by bitcrazed** [comment]
Could you please be more descriptive in what you're looking for or the problem you're seeing.

And please complete the provided issue template when filing issues in the future. The issue template helps you include the information we need to best diagnose and answer your question.
