### ISSUE TITLE
Unicode font rendering problem

### ISSUE THREAD

**Issue by dotSlashLu** [microsoft/terminal#2711]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18362.295]
Windows Terminal version (if applicable): 0.4.2382.0
Profile Font: Consolas

Any other software? 
Remote Linux box locale: en_US.UTF-8
```

# Steps to reproduce

(Some of these steps might not be relevant)
1. Open the debian WSL profile
2. SSH to a remote Linux box
3. Start a tmux session
4. Edit a file which contains Chinese character and has lines more than the terminal using neovim
5. Scroll through the lines in neovim

# Expected behavior

The unicode(Chinese) characters' font size should be consistent and should not be duplicated.

![snapshot](https://user-images.githubusercontent.com/3133289/64590078-46c21800-d3d9-11e9-8b13-720a5b72492d.png)

# Actual behavior

When scrolling, by chances the Chinese characters get duplicated and the font get smaller than other normally rendered Chinese characters.

**Comment by zadjii-msft** [comment]
This looks similar to  #610, but considering the duplicated characters I'm thinking it isn't the same thing.

**Comment by DHowett-MSFT** [comment]
I think there's a duplicate for this, so I'm assigning myself to find it.
