### ISSUE TITLE
Copying text to clipboard from Ubuntu and pasting it in Notepad loses line terminators.

### ISSUE THREAD

**Issue by michelforget** [microsoft/terminal#2717]
Copying text to clipboard from Ubuntu and pasting it in Notepad loses line terminators.  The text looks right in the Ubuntu window, but when pasted into Notepad the text seems to have no line terminators.  It seems like the text isn't being converted to MS-DOS line terminators before going into the clipboard, but probably should be.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior
Line terminators should not be stripped.  I think that if the text is in Unix format, it should be converted to Windows format prior to going into the clipboard.

Text in Notepad should look the same as the text in the source window.
# Actual behavior

**Comment by zadjii-msft** [comment]
Are you holding Shift when copying?

This may be any of #1073 #2275 #1091

**Comment by michelforget** [comment]
No, I was not holding shift.  Just highlighting the text using the left mouse button.

**Comment by DHowett-MSFT** [comment]
In that case, this is /dup #1073 #2275 :smile:

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/1073
https://github.com/microsoft/terminal/issues/1126
https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275
https://github.com/microsoft/terminal/issues/2278
https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395

https://github.com/microsoft/terminal/issues/2717
https://github.com/microsoft/terminal/issues/52
