### ISSUE TITLE
Ensure that dynamic profiles have a consistent place in the profiles list

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2722]
Follow up to #2603

I'm not totally sure that when a dynamic  profile is _first_ added to the list of profiles, it will be in the same place on a subsequent launch. This has to do with the fact that we re-order profiles to match the user settings file.

There's a 80% chance it will just work as-is in #2603, but I'm not positive. This bug represents me doing the due diligence to write tests to ensure this.

**Comment by DHowett-MSFT** [comment]
Nobody's ever complained about this. If it's a problem, we'll reopen.
