### ISSUE TITLE
Crash when displaying emoji

### ISSUE THREAD

**Issue by zb140** [microsoft/terminal#2724]
Starting after I updated to the latest `master` today, I'm getting a crash when displaying at least some emoji.  Commit bac69f7 is the most recent one I was able to find that definitely works.  I tried bisecting to narrow it down further but ran into a bunch of build issues and gave up.

Running in a debugger I get this exception:
```none
Unhandled exception at 0x00007FFF994F4B29 in WindowsTerminal.exe: Microsoft C++ exception: wil::ResultException at memory location 0x0000006A998FDE10.
```
The particular result being complained about is this: `E_INVALIDARG One or more arguments are invalid.`.
The call stack seems to point to this line as being the problem: https://github.com/microsoft/terminal/blob/12d2e170dd0ff0e23c956a754a308c4ce3f0c1f8/src/renderer/base/renderer.cpp#L639  (Technically it points to the next line, but I think that's just the debugger being funny).

This is 100% reproducible for me on both of the systems I've tried it on. I'm happy to help dig up more info if needed.

# Environment
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
10.0.18965.0 
I happen to be filing this from a system with a fairly recent Insider build, but this also happens on the latest non-Insider build.

Windows Terminal version (if applicable):
Latest from master

Any other software?
Powershell 6.2.2 (not sure if this matters)
```

# Steps to reproduce
In Powershell:
```
PS> echo "$([char]0x2714)"
```

# Expected behavior
Should print a ✔️

# Actual behavior
The terminal crashes.

**Comment by jbolton-corvalgroup** [comment]
I cannot get a crash using `PowerShell 5.1.18362.145`, maybe it's a `PowerShell core/6+` bug, not terminal ?

Tested on windows10.

bash, (specifically `git-bash` from `github desktop` in WindowsTerminal
```bash
$ python -c 'print(chr(0x2714))'
✔
```

cmd.exe in WindowsTerminal

```cmd
C:\Users\john>python -c "print(chr(0x2714))"
✔
```

powershell 5 (non-core) from WindowsTerminal
```powershell
PS C:\Users\john> [char]0x2714
✔
```

**Comment by zb140** [comment]
Whatever's going on on my systems doesn't seem to be related to Powershell.  I've just now tried it in Powershell 5, in `cmd.exe`, in Git's bash, and even after `ssh`ing to a Linux host, and all of them crash in exactly the same way.

Which commit of Terminal are you using?  I'm seeing these crashes in 2ac24979da6eada2d5af758e6521e649600d5510 on both of the systems I've tried it on.  I see there are new commits this morning but I haven't tried them yet.

**Comment by j4james** [comment]
I can reproduce this too. And if you look at the debug output log from within the debugger, you can trace the source of the `E_INVALIDARG` to this line:

https://github.com/microsoft/terminal/blob/d8ff47a0d3534e8ddfd7cfd12b3c43738b51257f/src/renderer/dx/CustomTextRenderer.cpp#L436

But from what I can make out, the _glyphRunDescription_ parameter is not actually required. It's documented as optional for the [`ID2D1DeviceContext::DrawGlyphRun`](https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/nf-d2d1_1-id2d1devicecontext-drawglyphrun) method, which is where it's ultimately being used.

> The _glyphRunDescription_ is ignored when rendering, but can be useful for printing and serialization of rendering commands, such as to an XPS or SVG file

So I suspect that NULL check is probably a mistake. It was only recently added in commit 30e8e7f3a34e86567be960063dddb1ff278a0c82, and removing that line certainly fixes the problem for me.

cc @miniksa
