### ISSUE TITLE
Pops up and Closes Not Loading

### ISSUE THREAD

**Issue by TyronSamaroo** [microsoft/terminal#2737]
Windows Terminal won't load. I reinstall and deleted it a couple of times and still doesn't work.
Im in Developers Mode and System is type is x64

**Comment by DHowett-MSFT** [comment]
* Is this your first installation, or did you have it working on another computer?
* What version of Windows are you on?

**Comment by TyronSamaroo** [comment]
I had installed it earlier and it was working. For past week when I try to open it, it just flashed an empty box and closes. Im on 
Windows 10 Pro
10.018362 Build 18363 
Version 1903

**Comment by TyronSamaroo** [comment]
https://aka.ms/AA63nug 
Under Apps, there was no Windows Terminal(Preview) I recreate the problem with a video as one the options.

**Comment by TyronSamaroo** [comment]
Is it because I turn on WSL? Is there anything I need to add to my path environment?

**Comment by TyronSamaroo** [comment]
After Spamming Application to open I got this error. 
<img width="563" alt="Annotation 2019-09-27 002637" src="https://user-images.githubusercontent.com/34173862/65742443-2921cd80-e0be-11e9-982f-2afceedf1354.png">

**Comment by TyronSamaroo** [comment]
I have solved the problem. For some reason when I checked Use Legacy Console It works. Any explanation why?

**Comment by DHowett-MSFT** [comment]
Hey there! Sorry for the delay. Does this issue still reproduce? I wasn't able to find any crashes in the feedback hub link you sent, but it looks like you might be running into either #2563 or #2375. :smile:

**Comment by DHowett-MSFT** [comment]
If it still repros, let me know and I'll reopen this bug.
