### ISSUE TITLE
copied text does not include sufficient/correct HTML entity escaping

### ISSUE THREAD

**Issue by 0xabu** [microsoft/terminal#2738]
# Environment

```none
Windows build number: 10.0.18362.356
Windows Terminal version (if applicable): 0.4.2382.0
Copy-on-select is enabled (I doubt it matters)
```

# Steps to reproduce
Select some text in the terminal containing a `<` character. Right-click to copy it if needed.

For example:
![image](https://user-images.githubusercontent.com/13037682/64804858-8f4a1480-d544-11e9-860b-5381ee83422a.png)

# Expected behavior
Text is copied to the clipboard as both plain text and valid HTML.

# Actual behavior
Pasting into notepad pastes the full selected plain text.
Pasting into an HTML-capable app (in this case the mail client) shows that entity-escaping hasn't been done correctly:
![image](https://user-images.githubusercontent.com/13037682/64804930-c1f40d00-d544-11e9-8fbc-252ab5e5abe6.png)

**Comment by kojoru** [comment]
Note this comment in PR #2038:
> HTML text was unescaped, and it still is, becouse Word doesn't work with HTML entities, like &lt;. But it seems to accept the invalid HTML with > from prompts. So if there is no text like `<someTextThatNowBecomesATag>`, it should work.

**Comment by mcpiroman** [comment]
Indeed, I left it unescaped only because MS Word wouldn't handle that (its HTML support is quite retarded actually), which is quite common target for such copy.
However, when RTF copy is supported (#2487), then Word might prioritize it over HTML (though if someone explicitly selects HTML paste, then it still wouldn't work).
It might be worthwhile to introduce `escapeHtml` setting maybe?

**Comment by 0xabu** [comment]
> Indeed, I left it unescaped only because MS Word wouldn't handle that (its HTML support is quite retarded actually), which is quite common target for such copy.

@mcpiroman how did you determine that Word couldn't handle it? Do you have a ref for that? I did some quick tests copying and pasting from mintty in HTML format, and whatever it emits for < > etc. appears to paste correctly into Word.

**Comment by mcpiroman** [comment]
@0xabu I've played with it a quite a bit when writing mentioned PR few month ago and it simply didn't work (they were just literally displayed as I can remember). However I've just tried this once again and it worked. So it looks like they've updated Word to handle that.

**Comment by SeanLeftBelow** [comment]
I have a concern that this is not the right fix here. As mentioned by @DHowett-MSFT
(https://github.com/microsoft/terminal/pull/2777/files#r324902781)

I have been having issues with copy/paste from terminal but in this test above my copy worked.

>Microsoft Windows NT 10.0.18362.0
>Windows Terminal (Preview) Version: 0.4.2382.0
```
PS C:\> echo "<foo>" 
 <foo> 
PS C:\> echo "<bar"
 <bar 
```

Not sure if this is related but when I put the above commands in a script and output I get this weird spacing issue:
![output](https://user-images.githubusercontent.com/5666862/65083375-3a9c0480-d95d-11e9-8757-87e72ecabc5c.png) 
[output.log](https://github.com/microsoft/terminal/files/3623622/output.log)

Opening in Atom shows two unreadable characters. Notepad does not. 

I have been having issues with coping JSON from Terminal and I plan on opening a separate issue for this. But for context on why I think its how I think Terminal handles symbols and characters. 

When I copy JSON from Terminal to Atom/Notepad it strips the `"Topics":[` completely out. Oddly enough, in Chrome when posting this it copied correctly, but still does not in Atom/Notepad.
```
{                                                                                                                                                                                                                                                                                 "Topics": [
    {
      "TopicArn": "arn:aws:sns:"
    },
    {
      "TopicArn": "arn:aws:sns:"
    },
```

**Comment by DHowett-MSFT** [comment]
Your first thing looks like you’re using UTF-16; don’t do that :P
The second thing: if you scroll all the way to the right in Atom/Notepad, do you see Formats on the right edge?

**Comment by 0xabu** [comment]
Those unreadable characters are a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), it's probably unrelated.

This issue is only with HTML copy. You didn't say, but it sounds like you may have done the copy into an applciation (like a text editor) that pastes plain text.

**Comment by SeanLeftBelow** [comment]
@DHowett-MSFT, I did switch Atom from Auto to UTF-8 and that is when I get the odd spacing, UTF-16 LE displays properly. Thanks for the tip.
@0xabu I see how the issues differ I apologize for hijacking your issue. 
Could the escaping characters be only limited to the HTML tags or expand to `[` and `{`?
