### ISSUE TITLE
_tabView.Items() and _tabs should not need to be kept in sync manually

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2740]
Right now in TerminalPage, we have two separate vectors of "tabs" that need to be kept in sync:
1. Our own `vector<shared_ptr<Tab>> _tabs`
2. The vector owned by `_tabView` of all the `TabViewItem`s. 

This is kinda silly, we should probably just use the  `_tabView.Items()` vector, and more closely associate the `Tab` with them. 

Case in point is `TerminalPage::_RemoveTabViewItem`, where we need to both remove the tab from both the tabs and the tabView.Items(). 

We could probably make tabs an observable vector or something, so the tabview is inherently tied to the tabs collection. I did a bit of similar prototyping in the command palette prototype, see #2046 for that branch.

**Comment by DHowett-MSFT** [comment]
_yes please_! If we make Tab a WinRT runtime class or something, we can probably even use it _as_ the TabView Item.

**Comment by leonMSFT** [comment]
Closing because we actually need access to the TabViewItem to perform some of our custom modifications like tab color and tab title boxes (and maybe future modifications), and so letting us have total control of our TabViewItems is needed, so this in fact is the way
