### ISSUE TITLE
Buffer still goes missing when using python in terminal with Windows Powershell/pwsh6/cmd

### ISSUE THREAD

**Issue by Jarvis73** [microsoft/terminal#2744]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.18362.356]
Windows Terminal version: 0.4.2382.0
Windows Powershell: 
                     PSVersion                      5.1.18362.145
                     PSEdition                      Desktop
                     PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
                     BuildVersion                   10.0.18362.145
                     CLRVersion                     4.0.30319.42000
                     WSManStackVersion              3.0
                     PSRemotingProtocolVersion      2.3
                     SerializationVersion           1.1.0.1
Pwsh 6:
                     PSVersion                      6.2.2
                     PSEdition                      Core
                     GitCommitId                    6.2.2
                     OS                             Microsoft Windows 10.0.18362
                     Platform                       Win32NT
                     PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
                     PSRemotingProtocolVersion      2.3
                     SerializationVersion           1.1.0.1
                     WSManStackVersion              3.0
```

# Steps to reproduce
1. Open any of the WindowsPowershell/pwsh/cmd in windows terminal
2. Install python package `pyreadline` 
3. Input `python` and enter interactive mode
4. Press `Enter` a bunch of times, until current view goes up
5. Lines at the top got missing and can not scroll up

# Expected behavior

All the lines at the beginning should be kept and scrollback/scroll bar should appear

# Actual behavior
* cmd
![cmd](https://user-images.githubusercontent.com/26033896/64836052-0356ec00-d61b-11e9-8c67-e4d9a5774315.gif)

* pwsh
![pwsh](https://user-images.githubusercontent.com/26033896/64836074-18337f80-d61b-11e9-9424-17a45ccd02c3.gif)

* Windows Powershell
![windowspowershell](https://user-images.githubusercontent.com/26033896/64836112-37caa800-d61b-11e9-82e4-c786e19b8331.gif)

# Note
* I think it is not the problem mentioned in #2410 and [PSReadLine](https://github.com/PowerShell/PSReadLine/issues/724), because I have fix the PSReadLine problem by installing v2.0.0-beta4
![image](https://user-images.githubusercontent.com/26033896/64835291-0d2b2000-d618-11e9-98fb-4d5a51b500ac.png)
![psreadline](https://user-images.githubusercontent.com/26033896/64835923-888dd100-d61a-11e9-9de1-901d476edf9a.gif)

* Besides, build-in Windows Powershell is correct:
![powershell](https://user-images.githubusercontent.com/26033896/64835730-af97d300-d619-11e9-9d8a-feacc97d9bac.gif)

**Comment by DHowett-MSFT** [comment]
Nobody over here can repro this, but we're keeping it open because clearly it's an issue.

**Comment by Jarvis73** [comment]
I found python package `pyreadline` causes the problem. Temporarily I can skip this bug by uninstalling the package. But I think it is still necessary to fix it.

**Comment by DHowett-MSFT** [comment]
Is this still happening? With PWSH 7 :smile:

**Comment by Jarvis73** [comment]
It seems that the problem has gone.

**Comment by DHowett-MSFT** [comment]
Thank you!
