### ISSUE TITLE
Bug Report (Windows PowerShell CTRL+C no longer works for copying selected text)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/terminal#2749]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): Version: 0.4.2382.0

Any other software?
```

# Steps to reproduce

1. Highlight text in Windows PowerShell, in Windows Terminal.
2. Press CTRL+C and watch as a new line is generated but realize the selected text is both no longer selected and not on the clipboard.

# Expected behavior

CTRL+C should continue to work for copying text out of Windows PowerShell.

# Actual behavior

CTRL+C is instead just the typical cancel and new line.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the report! This’ll be the same as /dup #2285. Your key bindings are configurable, and if you bind ctrl+c as copy you’ll get the behavior you’re expecting.

**Comment by JeremyTBradshaw** [comment]
@DHowett-MSFT Thanks and awesome.  I searched for "ctrl copy" and a few other trying-to-be-smart searches, but didn't see that issue.  Glad it is such an easy solution.
