### ISSUE TITLE
Scrolling sometimes doesn't work after resizing window

### ISSUE THREAD

**Issue by filip-hejsek** [microsoft/terminal#2752]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.4.2382.0
```

# Steps to reproduce

Resize the window (or maximize or unmaximize it) and drag the scrollbar.

# Expected behavior

The terminal is scrolled when dragging the scrollbar

# Actual behavior

Dragging moves the scrollbar but doesn't scroll the terminal. Also the scrollbar sometimes changes size when i start dragging it. Moving the scrollbar completely to the bottom and releasing it makes scrolling work again.

**Comment by DHowett-MSFT** [comment]
Thanks! /dup #1494
