### ISSUE TITLE
Highlighting (copying) from left edge of window with cursor in full screen fails

### ISSUE THREAD

**Issue by mitchcapper** [microsoft/terminal#2756]
# Environment
10.0.18362.0 Terminal: 0.4.2382.0

# Steps to reproduce

Maximize the terminal window.  Move cursor all the way to the left of the screen and start dragging to highlight the text on that row.

# Expected behavior

It starts highlighting the row you are on (the text).  This is similar to putty, cmd, and powershell outside of terminal.

# Actual behavior

The row you are on is not highlighted.  You must click on the first character of the row, not to the left of it.

This requires for more precise highlighting to avoid missing what you want to copy and is far slower.

**Comment by mcpiroman** [comment]
Does this happen also in non-maximized window and not happen if you disable padding?
If yes, then this is #1367

**Comment by mitchcapper** [comment]
@mcpiroman indeed, good catch lets hope #1672 or a similar fix gets merged soon.  For now padding off works to solve:)  Closing as dupe.
