### ISSUE TITLE
Command alias inside profiles.json

### ISSUE THREAD

**Issue by bertyhell** [microsoft/terminal#2757]
# Description of the new feature/enhancement

**Problem**: it is hard to setup command aliases in the old cmd.exe. You need to define a bat file and a reg file and then set the commands with DOSKEY.
Example: https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt

**Solution**: allow users to define command aliases by defining them in the profiles.json file.

# Proposed technical implementation details

profiles.json file is read at startup of terminal, then aliases are run as DOSKEY commands in the background.
The commands could be saved in json like this:
```json
{
    "profiles" :  [
        {
            "commandline" : "powershell.exe",
            "name" : "Windows PowerShell",
            "..."
            "commandAliases": [
                {
                    "alias": "ls",
                    "command": "dir /B"
                },
                {
                    "alias": "sshmyserver",
                    "command": "ssh 234.234.456.788 -u admin -p god"
                }
            ]
        },
    ]
}
```

**Comment by Luuk34** [comment]
you also can use DOSKEY for the simple ones. This makes your 'alias' also work in a normal command-prompt.

ALIAS WindowsTerminal=wt

After above statement one can use 'WindowsTerminal' to start 'wt'.

**Comment by DHowett-MSFT** [comment]
You'll have a way better time (and a more extensible experience!) setting these aliases during your shell startup script (profile) than in your terminal emulator. That way, you get your aliases over SSH, in the original console host, in ConEmu _and_ in Windows Terminal!

**Comment by Rafi993** [comment]
I do wanted this feature badly. I ended up writing a simple go script that does this job https://dev.to/rafi993/al-simple-alias-manager-2pg6

**Comment by sgmath12** [comment]
Hi. I did following.

DOSKEY WindowsTerminal=wt

and I can strat 'wt' by typing 'WindowsTerminal' in cmd.
However, when in the Windows Powershell, the following error occured.

WindowsTerminal : The term 'WindowsTerminal' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.

How can I use alias in Windows powershell?

I also fix my profiles.json.

**Comment by Rafi993** [comment]
I was able to write a simple go script that manages aliases across different shells https://github.com/nestedobjects/al

**Comment by thadguidry** [comment]
Make a file called `init.cmd` or whatever, somewhere perhaps in your User folder:
![image](https://user-images.githubusercontent.com/986438/102720645-388cc800-42bb-11eb-97e2-b9a734476ca8.png)
Then in your Windows Terminal - Profile `settings.json` you can modify `cmd.exe` with `/K` to carry out all your init commands in that `init.cmd` first before giving you your prompt:
![image](https://user-images.githubusercontent.com/986438/102720709-8bff1600-42bb-11eb-9e62-674a374afa06.png)
