### ISSUE TITLE
Request for support for vim (vim for windows) in windows terminal

### ISSUE THREAD

**Issue by codingonHP** [microsoft/terminal#2761]
# Description of the new enhancement
Currently windows terminal does not support vim (vim for windows) completely. When vim is launched from the windows terminal, the document opens fine and all of the vim features are available. The only issue is that the rendering of the document is with blue color as opposed to normal terminal background-color (say black)

![image](https://user-images.githubusercontent.com/7105293/64915982-73877e00-d791-11e9-974d-2a7e76ecf212.png)

Due to the improper rendering, the syntax highlighting feature of vim no longer works.
When vim is launched from the terminal it should respect `.vimrc` file of the user.

It will be helpful if I can use vim in the windows terminal directly :)

### A clear and concise description of what the problem is that the new enhancement would solve.
Describe why and how a user would use this new functionality (if applicable).

It would be really helpful if I can use vim for windows on the windows terminal. Ever since the new terminal was announced I was looking forward to using vim on it. Currently, I use vim software for windows. 

### A clear and concise description of what you want to happen.

It would be useful if something close to below happens:

![image](https://user-images.githubusercontent.com/7105293/64916013-5ef7b580-d792-11e9-9fb2-1f14ecc65fdd.png)

**Comment by jantari** [comment]
This does not happen to me.

Windows Terminal Version: 0.4.2382.0
Windows 10 Version: 10.0.18975.1000 (Insiders Fast)

[screenshot from my pc](https://i.imgur.com/Bx1Sp7t.png[/img)

Are you sure this isn't a problem with your `_vimrc`?

**Comment by DHowett-MSFT** [comment]
Does this reproduce if you use `vim -u NONE`?

**Comment by codingonHP** [comment]
@DHowett-MSFT 
No. It renders correctly with `vim -u NONE`

**Comment by codingonHP** [comment]
my .vimrc had `:colorscheme palenight` set which was causing the problem
Thanks for the help
