### ISSUE TITLE
acrylicOpacity not working on a two monitor setup when screen looses focus

### ISSUE THREAD

**Issue by lucas-felix** [microsoft/terminal#2763]
# Environment

```none
Windows build number: 10.0.18980.0

Windows Terminal version (if applicable): 0.4.2382.0
```

# Steps to reproduce

Two displays setup: in my case, an LG  monitor, used as the primary monitor, connected with an HDMI cable to a Dell Inspiron 14 5000.

# Expected behavior

I have the following configs on my `profile.json` file (just a fragment of the file):

```json
        {
          "acrylicOpacity": 0.85,
          "closeOnExit": true,
          "colorScheme" : "Solarized Dark",
          "commandline": "wsl.exe -d Ubuntu-18.04",
          "cursorColor": "#FFFFFF",
          "cursorShape": "vintage",
          "fontFace" : "Fira Code",
          "fontSize": 12,
          "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
          "historySize": 9001,
          "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
          "name": "Ubuntu",
          "padding": "10, 0, 10, 0",
          "snapOnInput": true,
          "useAcrylic": true
        },
```

The opacity would work besides the focused screen at the moment. Example: if my terminal is open on Dell display, even I move the focus to LG display, the opacity must stay working.

For reference purposes, that's the way iTerm2 behaves.

# Actual behavior

Actually, when I change the display focus, the terminal opacity is disabled. [This recorded video capture](https://youtu.be/8HKNohf7Fms) tries to illustrate the behavior. At second 00:07 I click on the other display that leads to opacity losing. When I click again on the second display with the open terminal, the opacity is enabled.

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, by design. System policy dictates (and Windows controls this, not Terminal(!)) that _only a currently-active window_ can be displayed with the acrylic effect.
