### ISSUE TITLE
Run script at startup - task bar jump list support

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/terminal#2766]
Please allow terminal to run scripts at startup from a task bar jump list.

What would be nice is having the Windows Terminal jump list provide a list of startup scripts, same way VS allows me to open projects form the jump list. I could pull up the jump list from the task bar and select whichever project I was working on. For example I could select a script from the jump list to take me to a particular working directory and setup command line compilation for the terminal instance.

**Comment by zadjii-msft** [comment]
This is /dupe #576. Please search before filing new issues.

**Comment by Gavin-Williams** [comment]
Issue #576 is all about profiles and which tabs to open. Does that encompass what I've proposed here?

**Comment by K1ngjulien** [comment]
well you can add profiles with different startup commands to do just that, i guess.
once the jump list is in place,  a whole bunch options open up for things to be featured there.
