### ISSUE TITLE
Bug Report (IF I DO NOT CHANGE THIS THE ISSUE WILL BE AUTO-CLOSED)

### ISSUE THREAD

**Issue by ain-soph** [microsoft/terminal#2767]
# Environment

Windows build number: (powershell)
$psversiontable
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Windows Terminal version (if applicable): Windows Terminal (Preview) 0.4.2382.0

Any other software?
No

# Steps to reproduce
1. Open two tabs in the terminal.
2. In the first terminal, cd it into a path with a long name.

# Expected behavior
Every tab name should be limited in a certain length or set adaptively. It should be easy to switch  among tabs and easy to close.  

# Actual behavior
The tab name is too long but the terminal doesn't give it a length limit, and it strongly affects the function of following tabs.
There is no close button for the second tab.
![image](https://user-images.githubusercontent.com/13214530/64932516-90fa2d80-d80d-11e9-8c0f-92c177e2187c.png)

**Comment by mdtauk** [comment]
You can set the name you want to use for the Tab, to prevent them being so long.  But I think you are asking for either fixed width Tab sizing, or a character count before the text is cut with ellipses (perhaps with the full text appearing in a tooltip)
