### ISSUE TITLE
Tab name too long

### ISSUE THREAD

**Issue by ain-soph** [microsoft/terminal#2768]
# Environment

Windows build number: 
powershell version
$psversiontable

PSVersion 5.1.18362.145
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.18362.145
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

Windows Terminal version (if applicable): Windows Terminal (Preview) 0.4.2382.0

Any other software?
No

# Steps to reproduce
1. Open two tabs in the terminal.
2. In the first terminal, type "ubuntu" to go into WSL.
3. cd it into a path with a long name.

# Expected behavior

Every tab name should be limited in a certain length or set adaptively.

It should be easy to switch among tabs and easy to close.

# Actual behavior

The tab name is too long but the terminal doesn't give it a length limit, and it strongly affects the function of following tabs.
There is no close button for the second tab.

![image](https://user-images.githubusercontent.com/13214530/64932516-90fa2d80-d80d-11e9-8c0f-92c177e2187c.png)

**Comment by mdtauk** [comment]
You do have the ability to set the tab text for each profile, which will prevent the really long text appearing.  But I think you may be asking for either a MaxWidth for the Tabs (perhaps as a global setting) - or you would like to set a character count, which when met, would cut the text with an ellipses **…** (the full text of the Tab text, could appear in the tooltip)

**Comment by ain-soph** [comment]
> You do have the ability to set the tab text for each profile, which will prevent the really long text appearing.  But I think you may be asking for either a MaxWidth for the Tabs (perhaps as a global setting) - or you would like to set a character count, which when met, would cut the text with an ellipses … (the full text of the Tab text, could appear in the tooltip)

Yes. It behaves well on normal tabs (But it just shows "Powershell" rather than the file path). When I use WSL in the terminal, there is no MaxWidth property I guess.

The MaxWidth property works I think. But I hope there could be a more beautiful way to show the information adaptively according to the width of the terminal window.

![image](https://user-images.githubusercontent.com/13214530/64932990-a0c74100-d810-11e9-980e-e51eb3c65a33.png)

**Comment by DHowett-MSFT** [comment]
If you need a quick fix, change your shell settings to not set your title to something so long. :smile:
