### ISSUE TITLE
ConPTY mangles U+1F600 to U+FFFD

### ISSUE THREAD

**Issue by chris-morgan** [microsoft/terminal#2770]
# Environment

Windows build number: 10.0.18362.356  
Windows Terminal version: 0.4.2382.0

Also reproducible with Alacritty on https://github.com/jwilm/alacritty/pull/2438 with its ConPTY backend (`enable_experimental_conpty_backend: true`), and *not* with its WinPTY backend.

# Steps to reproduce

Type U+1F600. (Ways of achieving this are discussed below.)

# Expected behavior

U+1F600, `😀`, should be the input.

# Actual behavior

U+FFFD, REPLACEMENT CHARACTER, gets sent through instead.

This doesn’t affect most characters. This is the only such character that I regularly use that is affected. U+1F600 and U+1F700 are two examples of affected characters, while U+1F5FF and U+1F601 are examples of characters that are not affected.

----

# How to reproduce if you’re not sure

If you don’t have an IME that lets you insert such characters, you can install [WinCompose](https://github.com/samhocevar/wincompose) and type <kbd>Compose</kbd><kbd>1</kbd><kbd>f</kbd><kbd>6</kbd><kbd>0</kbd><kbd>0</kbd><kbd>Enter</kbd>, or put a line like this into %USERPROFIEL%\\.XCompose:

```
<Multi_key> <colon> <D> : "😀" U1F600
```

… which will allow you to use <kbd>Compose</kbd><kbd>:</kbd><kbd>D</kbd>.

To inspect what’s been sent, I like to use Vim with its `ga` command.

**Comment by DHowett-MSFT** [comment]
Sorry, does this fail _in Windows Terminal_? If so: we're seeing it working here. What shell are you using?

Windows PowerShell and CMD have very poor support for high-unicode input, whereas PowerShell Core supports it handily.

We made some fixes to ConPTY that aren't in 19H1, but _are_ in Terminal, which could explain why Alacritty is having trouble.

**Comment by chris-morgan** [comment]
This is failing for me in both Windows Terminal and Alacritty-with-ConPTY, with both cmd and WSL bash as the shell, running both Python (e.g. `hex(ord('…'))`) and Vim (e.g. `i…<Escape>ga`) for inspection of input codes.

Command Prompt and Alacritty-with-WinPTY are not experiencing this problem.

**Comment by miniksa** [comment]
I repro'd this against master today with an Ubuntu tab inside Windows Terminal, the WinCompose utility emitting the U+1F600 on <kbd>Right Alt</kbd>+<kbd>Left Shift</kbd>+<kbd>;</kbd>+<kbd>D</kbd>

I've traced through the Windows Terminal project and the U+1F600 character is landing as 0xF0 0x9F 0x98 0x80 (this is the valid UTF-8 per http://www.fileformat.info/info/unicode/char/1f600/index.htm) in the call to send it into PTY's input channel.

Next step is to attach to the underlying PTY and see how it might be losing it.

**Comment by miniksa** [comment]
OK. This goes off the rails here: https://github.com/microsoft/terminal/blob/0c8a4df9636982fc92137c47b31877f2c7b5efdb/src/terminal/adapter/InteractDispatch.cpp#L60-L86

In InteractDispatch, we appear to be feeding each piece of the surrogate-pair UTF-16 sequence in one wchar_t at a time.

This heads into https://github.com/microsoft/terminal/blob/0c8a4df9636982fc92137c47b31877f2c7b5efdb/src/types/convert.cpp#L135-L168.

At this point, we're identifying these things as invalid keys and synthesizing numpad events instead. But there's not really a valid numpad equivalent to half of a surrogate pair (https://github.com/microsoft/terminal/blob/0c8a4df9636982fc92137c47b31877f2c7b5efdb/src/types/convert.cpp#L160).

We did identify above on the `GetStringTypeW` call https://github.com/microsoft/terminal/blob/0c8a4df9636982fc92137c47b31877f2c7b5efdb/src/types/convert.cpp#L147 that this is the high portion of a surrogate pair. `CharType` has been filled with `0x800` at this point, which does map to `C3_HIGHSURROGATE`.

The conversion here ends up becoming effectively just the equivalent input of the <kbd>ALT</kbd> button going down and up.

It then does the same thing for the low surrogate half.

This then travels for a bit until it hits `InputBuffer::_WriteBuffer` here: https://github.com/microsoft/terminal/blob/0c8a4df9636982fc92137c47b31877f2c7b5efdb/src/host/inputBuffer.cpp#L598-L673

None of the code finds an appropriate mapping for the ALT so it is just stored into the input buffer.

The input buffer alerts waiting readers that data is available.

The WSL driver calls `ReadConsoleInputW` and attempts to retrieve any input information. It asks for a single event. We give it back. I can't see any further because I'm user mode debugging and I think the PTY drain got moved into kernel mode.

**Comment by miniksa** [comment]
Typing the 😀 character inserts this into the buffer:
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xde00 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

Pasting the 😀 character inserts this into the buffer:
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xde00 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

Typing the 😂 character inserts this into the buffer:
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xde02 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

Pasting the 😂 character inserts this into the buffer:
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038
↓  wch:0x0000 '\0' mod:LeftAlt (0x00000002) repeat:0x0001 vk:0x0012 vsc:0x0038
↑ wch:0xde02 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

😀 does not work.
😂 does work.

So it appears that the buffer state is consistent between typing and pasting, ruling that out.
It also appears that the format of the input messages is the same for the working and non working case.

Now I suspect the WSL TTY code. I'll look there next.

**Comment by chris-morgan** [comment]
Huh, does look like something related to WSL TTY code now. I had incorrectly assumed that running cmd.exe was equivalent to running cmd.exe from inside WSL, but it turns out not to be. Shows how poor a grasp I have on the moving parts!

- Windows Terminal → cmd: success, 😀 comes through alright.
- Windows Terminal → ubuntu → cmd: fail, 😀 gets mangled to U+FFFD.
- Windows Terminal → cmd → ubuntu → cmd: fail, 😀 gets mangled to U+FFFD.

**Comment by miniksa** [comment]
@benhillis, this is `_IsActionableKey` inside the WSL TTY causing an issue.

For a `KEY_EVENT` to be aggregated in the WSL TTY to be converted to UTF-8 and sent into the client, each individual event has to pass the `_IsActionableKey` check inside `_GetNextCharacter` which is called inside the `_ConsoleWorker` input loop.

The `_IsActionableKey` method contains this code snippet:
```C++
if ((KeyEvent->wRepeatCount == 0) ||
        (KeyEvent->uChar.AsciiChar == ANSI_NULL) &&
        ((KeyEvent->wVirtualScanCode != 0) ||
         ((KeyEvent->dwControlKeyState & ENHANCED_KEY) != 0))) {
             return FALSE;
}
return TRUE;
```

# 😀
## ↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

var | value | evaluation
--- | ---| ---
wRepeatCount | 1 | false
uChar.UnicodeChar | 0xd83d | (for reference only)
uChar.AsciiChar | 0x3d | false
wVirtualScanCode | 0x38 | true
dwControlKeyState | 0x0 | false

`false || false && true || false` --> `false` --> inverted by function --> `return TRUE;`

## ↑ wch:0xde00 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038
var | value | evaluation
--- | ---| ---
wRepeatCount | 1 | false
uChar.UnicodeChar | 0xde00 | (for reference only)
**uChar.AsciiChar | 0x00 | true**
wVirtualScanCode | 0x38 | true
dwControlKeyState | 0x0 | false

**`false || true && true || false` --> `true` --> inverted by function --> `return FALSE;`**

# 😂
## ↑ wch:0xd83d '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

var | value | evaluation
--- | ---| ---
wRepeatCount | 1 | false
uChar.UnicodeChar | 0xd83d | (for reference only)
uChar.AsciiChar | 0x3d | false
wVirtualScanCode | 0x38 | true
dwControlKeyState | 0x0 | false

`false || false && true || false` --> `false` --> inverted by function --> `return TRUE;`

## ↑ wch:0xde02 '☐' mod:None (0x00000000) repeat:0x0001 vk:0x0012 vsc:0x0038

var | value | evaluation
--- | ---| ---
wRepeatCount | 1 | false
uChar.UnicodeChar | 0xde02| (for reference only)
uChar.AsciiChar | 0x02 | false
wVirtualScanCode | 0x38 | true
dwControlKeyState | 0x0 | false

`false || false && true || false` --> `false` --> inverted by function --> `return TRUE;`

-------------------

For the 😀 case, the high surrogate passes the check and is appended to the TTY input. The low surrogate fails and is not appended. Then `RtlUnicodeToUTF8N` is called and it converts the broken surrogate pair unto `U+FFFD`, the unicode replacement character, which is forwarded through to the WSL instance.

For the 😂 case, the high and low surrogate pass the check, are appended tot he TTY input, and then converted successfully to UTF8 and forwarded into the WSL instance.

So overall, it looks like the `_IsActionableKey` method needs to be updated to check the whole `uChar.UnicodeChar` to see if the high word is also null before ruling something out as a null character or it will drop "numpad sequence" type characters that have an 0x00 in the low word.

**Comment by miniksa** [comment]
Now tracking internally as MSFT:23541483

**Comment by DHowett-MSFT** [comment]
The fix for this just went out with WSL in insiders’ build 19002!

**Comment by benhillis** [comment]
@DHowett - Wow you beat me to it, was planning on looping back here to close this :)

**Comment by DHowett-MSFT** [comment]
@benhillis y'can't beat a guy on the train to the airport with nothing to do except check twitter! :grin:
