### ISSUE TITLE
Docker not working in Ubuntu Terminal

### ISSUE THREAD

**Issue by anandijain** [microsoft/terminal#2773]
# Environment

```
Windows Terminal (Preview)
Version: 0.4.2382.0
Microsoft Windows [Version 10.0.18362.356] 

```
Docker 

# Steps to reproduce
I installed docker via `sudo apt-get`, following [this guide](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

However, `sudo systemctl start docker` gives me the following error:
`System has not been booted with systemd as init system (PID 1). Can't operate.`

Other people said that `sudo service docker start` would work but that gives:
`* Starting Docker: docker`

Which looks fine, but when running any `docker run` command, I get:

```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'. 
```

# Expected behavior

I am expecting to have docker start up and run in the terminal.

# Actual behavior

The actual behavior is that I get permission denied when connecting to the Docker daemon

**Comment by DHowett-MSFT** [comment]
This is not a terminal issue. Please ask on the Docker forums or the [WSL repository](https://github.com/microsoft/wsl).
