### ISSUE TITLE
There's no backscroll.

### ISSUE THREAD

**Issue by chx** [microsoft/terminal#2775]
# Environment

```none
Windows build number: 10.0.18362.356
Windows Terminal version (if applicable): : 0.4.2382.0

Any other software? 
```

# Steps to reproduce

Open cmd, go to  a directory with lots of files, type dir, observe there is no backscroll. Also with wsl and everything else.

# Expected behavior

There's a scrollbar and I can see things no longer in the viewport.

# Actual behavior

There is no scrollbar.

**Comment by zadjii-msft** [comment]
Could you share a screenshot of what's happening, and your `profiles.json` file?

The `historySize` property controls how many lines are available for scrollback - is that set to 0?

Also note that the scrollbar is only visible when you actually mouse over the scrollbar area:
![image](https://user-images.githubusercontent.com/18356694/64987123-6942ae00-d87d-11e9-8144-c0512de377be.png)

![image](https://user-images.githubusercontent.com/18356694/64987135-6f388f00-d87d-11e9-84d5-ccc6a9865f33.png)
(imagine the mouse over the scrollbar)

![image](https://user-images.githubusercontent.com/18356694/64987148-75c70680-d87d-11e9-8012-8db643f4c460.png)

**Comment by chx** [comment]
Oh that's tricky. Thanks!
