### ISSUE TITLE
Launch from context menu

### ISSUE THREAD

**Issue by Wagnerp** [microsoft/terminal#2776]
I don't know if this can be done already, but can we have an option to launch the terminal as an normal/elevated user from the context menu in explorer, similar to what you can already do with CMD/Powershell?

**Comment by zadjii-msft** [comment]
Please search before filing new issues. This is a duplicate of a ton of issues that were _already_ closed as duplicates of the following:

/dupe #1060

**Comment by Wagnerp** [comment]
Hi @zadjii-msft 

Thanks, will post ideas about this particular issue on the referenced thread.
