### ISSUE TITLE
line height improperly calculated for scaling other than 100%

### ISSUE THREAD

**Issue by ivanov** [microsoft/terminal#2779]
# Environment

```none
Microsoft Windows [Version 10.0.18362.295]
Windows Terminal (Preview)
Version: 0.4.2382.0
```

# Steps to reproduce

Switch the "Change the size of text, apps, and other items" to something other than 100%
Open up Terminal and colorize multiple contiguous lines on the screen
(For me, I'm running WSL and run `vim` followed by `:color blue`)

# Expected behavior

There should not be any gaps between the characters.

Here's the terminal on a 2560x1440 resolution monitor (Landscape) at 100% scale setting
![image](https://user-images.githubusercontent.com/118211/64994589-e0803e00-d88d-11e9-93d0-47979b062768.png)

# Actual behavior

On 125% zoom, the same window now looks like this (tiny black horizontal marks between what should be contiguous lines of text all colored blue).

![image](https://user-images.githubusercontent.com/118211/64995002-f5110600-d88e-11e9-9477-0e168c96b404.png)

At 150% scale, we have a similar issue, though now instead of every line being affected, every other line has the horizontal artifact.
![image](https://user-images.githubusercontent.com/118211/64995065-2558a480-d88f-11e9-9bbc-6c828b21cdd7.png)

175%, and 225% zoom seem to have the same artifact line pattern as 125%

200% zoom has no artifact.

This looks similar to the artifact reported by @shanselman in https://github.com/microsoft/terminal/issues/455#issuecomment-518455051, but the issue I see is present independent of the fontFace setting (i see it both with fontFace set to Fira Code, and with fontFace setting removed thus falling back to the default fontFace).

Note: I initially came across this while using multiple monitors, and the artifact presented itself when dragging between two monitors. It turns out that the Scale setting is on a per-monitor basis, so if anyone working on a fix has multiple monitors, they can test several scale settings in parallel, as dragging the window between monitors will dynamically apply the scaling to the window.

**Comment by DHowett-MSFT** [comment]
This is actually still just /dup #455, even if the context is different. Thanks!
