### ISSUE TITLE
Bug Report built from git sources deployment uses files in Build Directory 

### ISSUE THREAD

**Issue by darthpale** [microsoft/terminal#2781]
# Environment

```Windows 10 x64 1903 
Windows build number:  Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
Windows Terminal built from git clone 9/92019.  Have noticed it in the past.

```

# Steps to reproduce
Build Microsoft Terminal 
git clone https://github.com/microsoft/Terminal.git
cd Terminal
git submodule update --init --recursive
nuget restore OpenConsole.sln
Open VS2019
Set build to release X64
Build Solution
Deploy Solution

Launch Terminal from Start menu.

# Expected behavior
At this point the build directory should be able to be deleted.  Solution was deployed.  Build dirs should not be used

# Actual behavior
Build dir tree is still used by running deployed release build app
Terminal\src\cascadia\CascadiaPackage\bin\x64\Release\AppX
Files opened by running "Windows Terminal.exe" verified by  Process Explorer.

Not sure why it does this, but it shouldn't

**Comment by DHowett-MSFT** [comment]
This is just how Visual Studio development app deployment works.
