### ISSUE TITLE
Uncontrollably fast scrolling on Surface Pro trackpad

### ISSUE THREAD

**Issue by Zee2** [microsoft/terminal#2786]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0

Any other software? Just running bash terminal as usual
```

# Steps to reproduce

Run Windows Terminal on a recent Surface Pro device with the official Type Cover

# Expected behavior

Relatively controllable scrolling, comparable to other terminals like cmd.exe or Powershell. (Both scroll completely fine on my setup)

# Actual behavior

Windows Terminal scrolls at least 8+ lines at a time, zipping up the console history at lightspeed. The smallest scroll increment scrolls at least 8 lines at a time, making precise scrolling nigh impossible.

In my mouse/trackpad settings, I've verified that it is set to only scroll 1 line at a time with the trackpad. This is correctly reflected by other terminals (cmd.exe, powershell, etc) scrolling correctly.

**Comment by zadjii-msft** [comment]
This looks like a /dupe #1066
