### ISSUE TITLE
(Bug Report) Does not let msys2 use its own env

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/terminal#2792]
# Environment

```none
Windows build number: Unable to acquire at this moment, will update when i am back on my PC
Windows Terminal version (if applicable): Microsoft Store release (as of 1730, PST-8, 9/16/2019)

msys2.org 
```

# Steps to reproduce

Install msys2, and then, in `settings.json` specify the command to open `msys2`'s version of `bash.exe` instead of `cmd.exe`
`C:/msys64/usr/bin/bash.exe`
# Expected behavior

A proper working MSYS2 shell like in vs-code along with msys2.exe

# Actual behavior
Loads basic BASH.exe and anything sourced in `~/.bashrc` but otherwise, any environment variable not set in `~/.bashrc` is overwritten by windows environment variables. Such as PATH
MSYS2 `$PATH` is overridden with windows `%PATH%`, which while it works, it defeats the purpose of msys2 as MANY core programs to msys2 (such as `pacman`, `ls`, `nano`, and anything else) are not in path

**Comment by Biswa96** [comment]
In the JSON file, append the login (`-l`) and interactive (`-i`) option with bash.exe of msys2.

**Comment by DHowett-MSFT** [comment]
Yeah, this is because bash isn't being started as a login shell. We can't change that -- you have to be the one to do that. Thanks @Biswa96!

**Comment by Biswa96** [comment]
Maybe, this can be added in docs with some highlight. There are many environments like cygwin, mingw, msys2 and even WSL distros uses bash.

**Comment by Merith-TK** [comment]
Ah, so it was something i was failing on, Alright. thanks for the information
