### ISSUE TITLE
hiding all profiles makes terminal very upset

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2794]
It does this,

![image](https://user-images.githubusercontent.com/14316954/65074148-10d8e280-d949-11e9-95e7-750df4f782b7.png)

and then this,

![image](https://user-images.githubusercontent.com/14316954/65074157-16362d00-d949-11e9-9819-d3b7df5971aa.png)

and then this:

![image](https://user-images.githubusercontent.com/14316954/65074166-1c2c0e00-d949-11e9-8074-f5db6feb4f23.png)

**Comment by zadjii-msft** [comment]
I'm on it
