### ISSUE TITLE
should profile stubs include { hidden: false } to indicate that they can be suppressed?

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2795]
As in the title. Adding `hidden: false` to the default stub might clue users into profile hiding.

**Comment by DHowett-MSFT** [comment]
@zadjii-msft likely has an opinion here

**Comment by zadjii-msft** [comment]
To the `defaults.json` or the stubs in the user profiles or the DPG stubs?

I think yes, sure, no

**Comment by DHowett-MSFT** [comment]
I was thinking `userSettings.json` and DPGs.

**Comment by zadjii-msft** [comment]
Would putting it in the cmd, powershell profiles not be good enough?

I don't feel particularly strong one way or the other. Code shouldn't be hard, I'll throw something together
