### ISSUE TITLE
JSON patching is hard

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2805]
`git push github HEAD:refs/heads/dev/migrie/b/json-patching-is-hard` thanks @DHowett-MSFT for putting this out there

> user settings is "{}" -- AppendDynamic transforms that into , { guid, name commandline }, {guid, name, ...}{}

> user settings is {"profiles":[]} gets transformed into something lovecraftian too

Let's add some tests for these, and fix them.

**Comment by DHowett-MSFT** [comment]
meh, literally nobody's reported this. Moving it to 1.1

**Comment by zadjii-msft** [comment]
Since we're not json patching anymore, I'm moving this to _closed_
