### ISSUE TITLE
Copy pasting from WSL to clipboard crashes the terminal and breaks copypaste system wide with very severe side effects

### ISSUE THREAD

**Issue by Razumihin** [microsoft/terminal#2807]
# Environment

Windows version: 10.0.18362.0
Terminal version: 0.4.2382.0

ESET Endpoint Security Antivirus 7.1.2053.0
Razer Blade 2019 15" laptop with default drivers.

# Steps to reproduce

Use WSL on the terminal and copy paste text back and forth from the terminal to other parts of the system. At some point the terminal will crash on copy. 

# Expected behavior

The string would be on the clipboard and windows would continue functioning properly. 

# Actual behavior

After the crash I'm fully unable to use Windows clipboard functionalities. Some places like explorer show both copy&paste disabled until restart but also clipboard actions from other software like vim are broken. At the same time radio boxes in Windows UI elements like installers stop working (wtf?)  and some of the start menu shortcuts like windows+x also stop functioning until I restart the computer. 

This seems rare, but I already reinstalled the system that I'm experiencing this on once, as I thought that some of the system files must be corrupt, but now I'm getting the same problem again. In both cases the first sign of trouble was the copy paste functionality of the terminal and everything else is fully working, so I think it might actually be related even though this seems very obscure.

**Comment by zadjii-msft** [comment]
@carlos-zamora Is this the same as the other clipboard crash?

**Comment by carlos-zamora** [comment]
> @carlos-zamora Carlos Zamora FTE Is this the same as the other clipboard crash?

Sounds like it. Particularly the "both copy&paste disabled until restart" part. So, what is going on is that the clipboard stays open. Because it is "in use", no other application is suddently able to use it.

Just to be safe, mind submitting some additional feedback?

/feedback

**Comment by Razumihin** [comment]
Sorry about not having Feedback Hub link before, I had to do some work and the Feedback Hub UI is somewhat confusing. Here is a link for you anyway: https://aka.ms/AA63lsi

**Comment by DHowett-MSFT** [comment]
Somebody remarked that this sounds like you're out of GDI handles. When this happens again, can you launch Task Manager, go to the Details tab, enable the "GDI objects" column and see what's taking up so many of them?

I bet it's not WT.

**Comment by Razumihin** [comment]
I'll check for GDI objects next time. I'm not that optimistic about that being the reason, as I was not doing anything that would hog up GDI handles yesterday when this occurred.

**Comment by Razumihin** [comment]
Okay, got it to crash again with the same symptoms. Most GDI objects were consumed by the task manager itself, so I don't think that's it. 

![image](https://user-images.githubusercontent.com/11144994/65593661-a43d9380-df99-11e9-8054-1693e2275271.png)

**Comment by torchesburn** [comment]
this still occurs!

**Comment by zadjii-msft** [comment]
@torchesburn This original thread is over 3 years old now. If you're seeing something similar, I'd bet it's due to a different root cause. Mind filing a new issue, so we can follow up on the specifics of whatever you're seeing? Thanks!

**Comment by james1236** [comment]
All inside WSL, doing `sudo apt-get remove xclip` and then following the commands to install win32yank [taken from here](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl) fixed it!
```
curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
chmod +x /tmp/win32yank.exe
sudo mv /tmp/win32yank.exe /usr/local/bin/
```
Specifically for those using neovim, using the clipboard took about 500ms after this, so I had to set `vim.opt.clipboard = ""` in my config
