### ISSUE TITLE
Copy issue

### ISSUE THREAD

**Issue by xuwei152** [microsoft/terminal#2822]
When I run pwd|xclip and paste in wls, it changs line automaticly. How can I disable the effect?

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by mikkushukla** [comment]
Same issue I am also facing

**Comment by zadjii-msft** [comment]
I'm going to need more information. What _exactly_ are you seeing, and what would you expect?

**Comment by mikkushukla** [comment]
When select multi line text and paste in file, it will replace new line by space.
It is very difficult to copy and paste configuration.

**Comment by DHowett-MSFT** [comment]
/dup #1073

Sorry/thanks @chx :smile:
