### ISSUE TITLE
Left character removed after press space in any command

### ISSUE THREAD

**Issue by patrickmaciel** [microsoft/terminal#2828]
This not happens outside terminal = using powershell directly.

# Steps to reproduce

1. start type anything
2. press space

# Expected behavior

1. the left space or character on the left of command do not delete

# Actual behavior

1. any character on left was deleted and the command characters go to left

![microsoft-terminal-space-bug](https://user-images.githubusercontent.com/671670/65354835-e85e1c00-dbc6-11e9-84c0-83385143c4ae.gif)

**Comment by zadjii-msft** [comment]
It looks to me like you're using a prompt with some powerline symbols in it (namely, the arrow and the three horizontal lines glyph).

Does this repro in a shell where those aren't in your prompt? 

What shell are you using?

**Comment by DHowett-MSFT** [comment]
This presents exactly like #633 #635.

**Comment by DHowett-MSFT** [comment]
Closing as a duplicate. Thanks!
