### ISSUE TITLE
Feature Request: Option to remove entire UI

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/terminal#2838]
# Description of the new feature/enhancement
Add an option to fully hide the ui including the title bar and tab bars.
for peopel that know their keyboard shortcuts.

see screenshot

![image](https://user-images.githubusercontent.com/13624265/65375994-3cd2cb80-dc9b-11e9-9e77-47a63d8dc575.png)

**Comment by myheartsgoon** [comment]
+1

**Comment by zadjii-msft** [comment]
This seems to me like it's /dupe #2238
