### ISSUE TITLE
Ctrl + F not working

### ISSUE THREAD

**Issue by SiqingYu** [microsoft/terminal#2847]
**Please fill out the below information:**
* Your Windows build number:  10.0.18362.356

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
I can open the find box by right-clicking the title bar and select from the menu. But I can't open it with Ctrl + F shortcut.
![image](https://user-images.githubusercontent.com/22290018/65384136-21c29300-dd51-11e9-8fbf-2aa42ebdb579.png)
![image](https://user-images.githubusercontent.com/22290018/65384179-8978de00-dd51-11e9-93e9-4c4d382714f5.png)

My `/etc/inputrc` is the default.
```
# /etc/inputrc - global inputrc for libreadline
# See readline(3readline) and `info rluserman' for more information.

# Be 8 bit clean.
set input-meta on
set output-meta on

# To allow the use of 8bit-characters like the german umlauts, uncomment
# the line below. However this makes the meta key not work as a meta key,
# which is annoying to those which don't need to type in 8-bit characters.

# set convert-meta off

# try to enable the application keypad when it is called.  Some systems
# need this to enable the arrow keys.
# set enable-keypad on

# see /usr/share/doc/bash/inputrc.arrows for other codes of arrow keys

# do not bell on tab-completion
# set bell-style none
# set bell-style visible

# some defaults / modifications for the emacs mode
$if mode=emacs

# allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line

# allow the use of the Delete/Insert keys
"\e[3~": delete-char
"\e[2~": quoted-insert

# mappings for "page up" and "page down" to step to the beginning/end
# of the history
# "\e[5~": beginning-of-history
# "\e[6~": end-of-history

# alternate mappings for "page up" and "page down" to search the history
# "\e[5~": history-search-backward
# "\e[6~": history-search-forward

# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word

$if term=rxvt
"\e[7~": beginning-of-line
"\e[8~": end-of-line
"\eOc": forward-word
"\eOd": backward-word
$endif

# for non RH/Debian xterm, can't hurt for RH/Debian xterm
# "\eOH": beginning-of-line
# "\eOF": end-of-line

# for freebsd console
# "\e[H": beginning-of-line
# "\e[F": end-of-line

$endif
```

**Comment by logeab** [comment]
Looks like you're using bash, doesn't `^F` move forward a character by default? I think you'll find most of those shortcuts will be passed through and won't work as they do under CMD

**Comment by SiqingYu** [comment]
@logeab My fault. I forgot that `Ctrl + F` is a shortcut in Bash.
Anyway, how to open the find tool in [terminal](https://github.com/microsoft/terminal/)?

**Comment by DHowett-MSFT** [comment]
Find isn't implemented in Terminal yet. /dupe #605.
