### ISSUE TITLE
Add shell in windows terminal

### ISSUE THREAD

**Issue by Creator-360** [microsoft/terminal#2848]
Do some one have the documentation to add other shell in the windows terminal profiles.json (powershell 6, ubuntu...) ?

Thanks

**Comment by Biswa96** [comment]
This docs may help https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md

**Comment by zadjii-msft** [comment]
Yep, that's the doc. Thanks!
