### ISSUE TITLE
Font rendering issue related to bold fonts using Consolas and MesloLGM (open source font)

### ISSUE THREAD

**Issue by sjetha** [microsoft/terminal#2852]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0

Any other software?
tmux v2.6
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

# Steps to reproduce
Run the following script to show full colour and font styles: curl -s -L https://git.gnome.org/browse/vte/plain/perf/256test.sh\?h\=vte-0-38 | bash

# Expected behaviour
Expect that the emboldened text to appear as below:
![image](https://i.stack.imgur.com/E6tSb.png)

# Actual behaviour
No bold text is shown in the output.
![image](https://user-images.githubusercontent.com/1066864/65443120-af05f600-ddea-11e9-8c8d-bbb757fa11d1.png)

# Note: This has been tested with MesloLGM and Consolas.
MelsoLGM repo link: https://github.com/andreberg/Meslo-Font
Licence: https://github.com/andreberg/Meslo-Font#license

**Comment by DHowett-MSFT** [comment]
/dup #109 

Thanks!
