### ISSUE TITLE
Feature Request - Adding languages

### ISSUE THREAD

**Issue by mattmazer0397** [microsoft/terminal#2854]
# Description of the new feature/enhancement
Allow the users to add new languages into terminal, or create "extensions" like exist in VSCode

# Proposed technical implementation details (optional)
No problem currently, other than end-user inconvenience. I've downloaded several different language libraries, and each one comes with their own console shells. It would be so much easier, and convenient if there were a way to "link" the terminal app to these other consoles (e.g. python) so that I could work within one location. I've got compilers and such already downloaded in VS and VSCode, but if I want to try something basic, I've found console to be quicker and easier than starting VS

**Comment by driver1998** [comment]
I guess we can start by automatically search and add the Visual Studio command prompts, interactive python (maybe only the Windows one for now), and maybe MSYS2 shell?

**Comment by DHowett-MSFT** [comment]
/dup #2303 #2283

There's a few competing ideas here; perhaps we need to _get a spec going_.
