### ISSUE TITLE
Crash to desktop when running an invalid Export Certificate Powershell command 

### ISSUE THREAD

**Issue by Choke101** [microsoft/terminal#2861]
# Environment

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal 
0.4.2382.0

Powershell version
$PSVersionTable.PSVersion                                                                                                                                                                                                   Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145

Any other software?
no

# Steps to reproduce
1. Type a poorly formed Export-Certificate powershell command such as 
Export-Certificate -Type CERT -FilePath "cert:\LocalMachine\my\blah" -Force
2.  Don't supply any details and hit enter when prompted for 
   "Supply values for the following Parameters  CERT:
3.  Get a great long exception stack trace that you can't read before windows closes as it crashes to desktop ending the WindowsTerminal process.

# Expected behavior
Get a stack trace, and the terminal doesn't actually close and crash back to desktop.

# Actual behavior
Closes window and Crashes back to desktop after printing out stack trace.

**Comment by Choke101** [comment]
https://aka.ms/AA65778

**Comment by DHowett-MSFT** [comment]
We can't reproduce this, but we also can't get any helpful information out of your feedback entry. Sorry about that! I'm going to mark this one Needs-Repro.

**Comment by miniksa** [comment]
I think this is related to #3380.

**Comment by DHowett-MSFT** [comment]
So, it looks like this was a powershell crash the whole time. Powershell is exiting with code 3221225477 or STATUS_ACCESS_VIOLATION.

**Comment by Choke101** [comment]
I'm confused by changing the label to Product-Powershell is that stating the bug should only be fixed in powershell and not Terminal?  I understand powershell may need to be fixed a bit to handle those but the terminal app should have resilience to safely recover from bad exit codes or violations so that it doesn't close the entire process and destroy the window and other tabs.

**Comment by DHowett-MSFT** [comment]
You may not have tried this recently, or your terminal settings may be out of date, but this no longer wipes out your terminal. It prints out "process exited with code 322xxx" and just stays open for you to inspect the dmage.
