### ISSUE TITLE
Run wsl.exe with Powerline font in Windows Terminal will crash

### ISSUE THREAD

**Issue by kkbruce** [microsoft/terminal#2862]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable):
0.4.2382.0
Any other software?
```

# Steps to reproduce

I install WSL - Ubuntu in Windows 10, want setup WSL in Windows Terminal. If change profile **fontFace** from **Consolas** to **Ubuntu Mono derivative Powerline** (https://github.com/powerline/fonts/tree/master/UbuntuMono), Windows Terminal will crash and close.

```
{
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "wsl.exe -d Ubuntu /bin/bash -c zsh",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Ubuntu Mono derivative Powerline",
            "fontSize" : 10,
            "guid" : "{d5ed219b-a9ca-4618-8250-d6b965766ba6}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Ubuntu",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
        },
```

# Expected behavior

Run wsl.exe with Powerline font in Windows Terminal.

# Actual behavior

Windows Terminal crash and close.

**Comment by DHowett-MSFT** [comment]
Also, you can just use `chsh` to set your shell to zsh instead of starting bash _just to start zsh_...

**Comment by kkbruce** [comment]
https://aka.ms/AA63upg

**Comment by kkbruce** [comment]
I change use https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DejaVuSansMono/Regular/complete font and commandline is work now.

```
{
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "C:/Windows/System32/bash.exe -c zsh",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "DejaVuSansMono Nerd Font",
            "fontSize" : 10,
            "guid" : "{d5ed219b-a9ca-4618-8250-d6b965766ba6}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Ubuntu",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
        },
```

**Comment by utybo** [comment]
I can confirm that the Windows Terminal crashes when "Ubuntu Mono derivative Powerline" font is used in any terminal, not just the WSL one. Workaround is to either use the non-derivative version which works fine, or another Powerline-compatible font.

**Comment by betteridiot** [comment]
Yes, I can confirm that some of the Powerline fonts do not work, but not all of them. My suggestion is to keep trying different powerline fonts until it doesn't crash. I currently use "Noto Mono for Powerline"

**Comment by speedy1812** [comment]
I had the same problem with "Ubuntu Mono derivative Powerline" crashing the Windows Terminal. But it turns out that the [Nerd Font version of Ubuntu Mono](https://www.nerdfonts.com/font-downloads) doesn't have the same problem.

**Comment by DHowett-MSFT** [comment]
This seems like /dup #602.

```
1                              32
|------------------------------|
Ubuntu Mono derivative Powerline
DejaVuSansMono Nerd Font
Noto Mono for Powerline
```

**Comment by tautomer** [comment]
For my case, Menlo powerline works, Meslo falls bak to the default and Droid Sans Mono family directly crashes the terminal.
