### ISSUE TITLE
Feature Request: Support the new cross-platform PowerShell

### ISSUE THREAD

**Issue by amirrammari** [microsoft/terminal#2868]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Hello, Windows Terminal doesn't support the new cross-platform PowerShell.
Please add below feature:
- Support the new cross-platform PowerShell

![Powershell](https://user-images.githubusercontent.com/23485114/65532018-f209bb80-df07-11e9-9afe-741e15a3f56a.png)

**Comment by zadjii-msft** [comment]
I bet that if you update to the latest store version (v0.5), powershell core will just appear for you 😉 

Granted, that's only for the release versions of Powershell Core. For the preview versions, see #2300.

**Comment by amirrammari** [comment]
Now I installed the latest store version of Terminal.
![image](https://user-images.githubusercontent.com/23485114/65535435-444ddb00-df0e-11e9-9012-77f208a63313.png)

Also now I installed the latest store version of PowerShell.
![image](https://user-images.githubusercontent.com/23485114/65535286-f9cc5e80-df0d-11e9-810b-0b16adb11ab5.png)
