### ISSUE TITLE
Scrollbar blocks console

### ISSUE THREAD

**Issue by bn-d** [microsoft/terminal#287]
10 Pro Insider Preview 1809 Build 18252.1000, though I think this is also an issue for the previous version.

The scrollbar is blocking about 1.5 char on the right side when the window is maximized or docked at left/right half of the screen. The scrollbar is not blocking anything under any other window size.

Window maximized
![image](https://user-images.githubusercontent.com/10731263/46925641-e5dc6500-cffa-11e8-8c92-a1b5c7e5ea85.png)

Normal
![image](https://user-images.githubusercontent.com/10731263/46925654-01477000-cffb-11e8-8740-47d55eea8e7b.png)

**Comment by miniksa** [comment]
@Erebuxy:

What font is this? What font size? What DPI is the screen? What resolution is the screen?

I'm having a hard time reproducing this issue this morning on my machine. I think I don't have the same dimensions or fonts that you do.

**Comment by Erebuxy** [comment]
I have this problem on both my desktop (34" 3440x1440) and laptop (13" 1920x1080). I believe I was using DejaVu Sans Mono and size is 16. I had also tried different fonts and sizes, and the problem persisted.

**Comment by miniksa** [comment]
I still can't manage to reproduce this issue internally which means unfortunately I cannot debug and fix it. I'm trying assorted different resolutions and DPIs on my monitors and with a maximized and non-maximized window with the DejaVu Sans Mono font size 16 and I can't figure out how you're getting into the situation with the characters covered up.

Your initial screen shot had some interesting arrow shaped overlay going on. Perhaps you're using some piece of software that's calling one of our APIs and getting us into a weird state? I'm just trying to repro with CMD.exe by typing at the prompt line and nothing weird is happening.

**Comment by miniksa** [comment]
I'm closing the internal work item MSFT: 19302761 as Not Repro for now. We can reactivate in the future if we can nail down a consistent repro that we can get to happen in-house so I can debug this.

**Comment by Erebuxy** [comment]
I think tmux is causing the problem. The problem occurs in tmux after I resize or dock the window several times or change the font or size etc.
The arrow is nothing special. It is just a character in the Deja Vu Sans Mono for Powerline

**Comment by moritzfalke** [comment]
I am currently running into the same issue when using tmux in WSL, without tmux it works fine and its also only when in fullscreen

**Comment by zadjii-msft** [comment]
We never got a repro for this, and have subsequently released the Windows Terminal. I'm suspecting that this doesn't repro in the Terminal. If it's still happening, we can revisit reopening this, but I suspect a conhost visual artifact like this isn't going to get prioritized any time soon.
