### ISSUE TITLE
ConPTY doesn't set KeyEvent::_virtualScanCode for certain characters like : (which bothers GoW less)

### ISSUE THREAD

**Issue by perlmaster** [microsoft/terminal#2873]
# Environment

Windows 10
Any other software?
```

# Steps to reproduce

1. Run cmd.exe under windows terminal preview
2. navigate to a directory containing text files
3. Run the command "less -MN *.txt"
4. When you reach the end of the 1st file enter the "less" command ":n" to go to the next file

# Expected behavior
"less" should start displaying the next file.

# Actual behavior
I get the following error message "no previous regular expression". This does not happen when I run less under a cmd.exe session the old fashioned way.

**Comment by DHowett-MSFT** [comment]
`less` doesn't ship with Windows, so you're going to need to share exactly _which `less` you are using_. Otherwise, we can't exactly debug the issue.

**Comment by perlmaster** [comment]
according to "less --version" I am running less version 378

**Comment by zadjii-msft** [comment]
I think @DHowett-MSFT meant more of "are you using wsl's `less`, cygwin's `less`, some unknown `less.exe`?"

**Comment by perlmaster** [comment]
I downloaded "less" a long time ago. I don't remember exactly where I got it.

The command "less --version" produces the following

less 378
Copyright (C) 2002 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

In the documentation I got at the time, there is the following paragraph:

       Copyright (C) 2002  Mark Nudelman

       less is part of the GNU project and is free software.  You
       can redistribute it and/or modify it under  the  terms  of
       either  (1) the GNU General Public License as published by
       the Free Software Foundation; or  (2)  the  Less  License.

Although I have cygwin, I do not use it.

**Comment by zadjii-msft** [comment]
```
zadjii@migrie-slaptop:~$ less --version
less 487 (GNU regular expressions)
Copyright (C) 1984-2016  Mark Nudelman
```

**Comment by perlmaster** [comment]
I must be having a slow day. Who or what is WSL ?

**Comment by perlmaster** [comment]
Sorry, it just occured to me that WSL == Windows Subsystem for Linux

**Comment by perlmaster** [comment]
Does anyone know where I can find a compiled binary version of less ? So far the only thing I have found is source code and I have always had issues trying to compile anything that requires the bourne shell to run a script named "configure" which starts the whole build  process. On my windows 10 64 bit system I can't get sh.exe to run properly

**Comment by DHowett-MSFT** [comment]
That's a really good question, honestly. It looks like the _GoW_ project produces binaries of these tools with reasonable frequency, but their terminal emulator bridge leaves a little bit to be desired. Perhaps their `less` works slightly better than the one you've got?

Sorry, I know it's not much. :smile:

**Comment by perlmaster** [comment]
The GoW version of less did not solve the problem. I am continuing my search for some kind of solution.

**Comment by DHowett-MSFT** [comment]
That is very good news for us, because now we have learned of a distribution of less that we can use for a repro. Thank you!

What keyboard layout are you using? Standard en-US PC104?

**Comment by perlmaster** [comment]
I am not sure about the exact specs for my keyboard, but it is definitely en-US. I am unable to determine if it is PC104 , I have checked in the control panels and nothing speaks of PC104

**Comment by perlmaster** [comment]
just for the record I have the same issue wether I use my laptop keyboard or my wired USB keyboard

**Comment by 0xd4d** [comment]
Try `less` that's part of [Git for Windows](https://git-scm.com/download/win)

**Comment by perlmaster** [comment]
I already had git for windows 2.15.0 on my system. I was not aware that it had all those extra executables. It had less version 481. That version of less seems to be working just fine !

That solves my specific issue. Thanks to all who helped !

**Comment by DHowett-MSFT** [comment]
And we've got a root cause, too!

It looks like some versions of less for windows are checking the _scancode_ of the keyboard key that's pressed, and when that key comes in off a pty (which Windows Terminal, VSCode, Visual Studio, etc. use), _that scancode isn't set._

### pseudoconsole

```
unique_ptr {↓ wch:0 '\0' mod:Shift (16) repeat:1 vk:16 vsc:42}
unique_ptr {↓ wch:0 '\0' mod:Shift (16) repeat:1 vk:16 vsc:42}
unique_ptr {↓ wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:0} <---
unique_ptr {↓ wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:0} <---
unique_ptr {↑ wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:0} <---
unique_ptr {↑ wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:0} <---
unique_ptr {↑ wch:0 '\0' mod:None (0) repeat:1 vk:16 vsc:42}
unique_ptr {↑ wch:0 '\0' mod:None (0) repeat:1 vk:16 vsc:42}
```

### conhost

```
unique_ptr {↓  wch:0 '\0' mod:Shift (16) repeat:1 vk:16 vsc:42}
unique_ptr {↓  wch:0 '\0' mod:Shift (16) repeat:1 vk:16 vsc:42}
unique_ptr {↓  wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:39} <---
unique_ptr {↓  wch:58 ':' mod:Shift (16) repeat:1 vk:186 vsc:39} <---
unique_ptr {↑ wch:0 '\0' mod:None (0) repeat:1 vk:16 vsc:42}
unique_ptr {↑ wch:0 '\0' mod:None (0) repeat:1 vk:16 vsc:42}
```

**Comment by DHowett-MSFT** [comment]
And as a final followup, it's because somewhere deep in the console host, we're doing a "vkey to vsc" translation, but we're providing it a character instead of a vkey. 🤦‍♂

**Comment by DHowett-MSFT** [comment]
```diff
diff --git a/src/types/convert.cpp b/src/types/convert.cpp
index c2049ded9..bc87bab18 100644
--- a/src/types/convert.cpp
+++ b/src/types/convert.cpp
@@ -206,7 +206,8 @@ std::deque<std::unique_ptr<KeyEvent>> SynthesizeKeyboardEvents(const wchar_t wch
                                                        SHIFT_PRESSED));
     }

-    const WORD virtualScanCode = gsl::narrow<WORD>(MapVirtualKeyW(wch, MAPVK_VK_TO_VSC));
+    auto vk = keyState & 0xFF;
+    const WORD virtualScanCode = gsl::narrow<WORD>(MapVirtualKeyW(vk, MAPVK_VK_TO_VSC));
     KeyEvent keyEvent{ true, 1, LOBYTE(keyState), virtualScanCode, wch, 0 };

     // add modifier flags if necessary
```
