### ISSUE TITLE
Settings reload resets font zoom

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#2874]
# Environment

Commit 56c35945

# Steps to reproduce

1. Zoom font e.g. with `ctrl`+ mouse wheel
2. Change and save settings file

# Expected behavior

Zoom level should remain the same (even when changed font size)

# Actual behavior

Zoom level resets to 100%

**Comment by DHowett-MSFT** [comment]
Hey, this one's currently by design. That doesn't mean that the design is _good_. The user taking affirmative action to update their settings file is taken by Terminal to mean that they want all their settings to be applied. :smile:
