### ISSUE TITLE
HTML Copy does not preserve background colors in PowerPoint

### ISSUE THREAD

**Issue by utybo** [microsoft/terminal#2875]
# Environment

```none
Windows build number:  10.0.18362.0
Windows Terminal version (if applicable): 0.5.2661.0

Any other software? Windows Subsystem Linux (version 1) with Ubuntu 18.04, latest zsh, 
    latest Oh My Zsh, agnoster theme in Oh My Zsh, Source Code Pro for Powerline font, 
    although these may not be strictly necessary to reproduce
```

# Steps to reproduce

1. Open a Ubuntu 18.04 tab
2. Select the prompt and copy it (right click in this specific case)
3. Paste in PowerPoint

# Expected behavior

A somewhat similar copy of the prompt gets pasted in PowerPoint. (the strange looking blue part at the top is just the line right above the prompt that was just another prompt but shifted a little bit)

![image](https://user-images.githubusercontent.com/5175705/65538908-a3a8ec80-df08-11e9-91de-6afcd9cdec47.png)

# Actual behavior

The background information is not pasted. The background of the line is not copied either.

![image](https://user-images.githubusercontent.com/5175705/65539202-3cd80300-df09-11e9-8310-8edc5003d72b.png)

The background information is pasted correctly in Word. 
![image](https://user-images.githubusercontent.com/5175705/65539053-f5ea0d80-df08-11e9-9934-09a047550d3f.png)

I do not know whether this issue is caused by Windows Terminal or PowerPoint. If PowerPoint is the culprit, could you point me towards where I could report this?

Thank you, and thanks for the amazing job you guys are doing on this project!

**Comment by DHowett-MSFT** [comment]
Hey @utybo! Thanks for the report. As far as we can tell, this is unfortunately an issue in PowerPoint. It looks like they're just rejecting the backgrounds on all incoming pasted `<span>`s ☹️

It might be worth filing an issue in their feedback portal! If you could do that--it means more when it comes from a customer--I'd be happy to upvote it or prod some powerpoint folks about it on your behalf.

In our case, though, this is going to be Resolution-External.

**Comment by utybo** [comment]
Understood, I'll leave an issue on the feedback portal ASAP and I'll post a link here 😄

**Comment by utybo** [comment]
Here is a link: https://aka.ms/AA67u2t

Please tell me if there is something else I need to do
