### ISSUE TITLE
[Setting] Option to launch already maximized / fullscreen

### ISSUE THREAD

**Issue by gavenkoa** [microsoft/terminal#288]
I use following `cmd.reg` to increase console size:

````
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
; 0x28 X 0x78 = 40x120.
"WindowSize"=dword:280078
````

There is no way to run it maximized (or fullscreen). There is <kbd>Alt + Enter</kbd> to switch to fullscreen but Windows toolbar is hidden in in this mode...

I tested trick with:

````
"AutoRun"="mode 800"
````

and it works only for `cmd` and doesn't work for `ubuntu` / `debian` WSL.

It should be high demand on opening console maximized because now it capable to serve emacs / vim and ssh connections within WSL.

**Comment by zadjii-msft** [comment]
Is <kbd>Win + Up</kbd> to maximize the window not what you want? 

Are you looking for a fullscreen console, without the titlebar, but with the taskbar? or do you want a fullscreen console with the titlebar, but without the taskbar?

**Comment by gavenkoa** [comment]
> Is Win + Up to maximize the window not what you want?

I want exactly what <kbd>Win + Up</kbd> does but without necessity to press those keys!

**Comment by gavenkoa** [comment]
Similar desire:

https://superuser.com/questions/285984/how-do-i-full-screen-my-cmd
https://superuser.com/questions/7219/fullscreen-vistas-command-prompt-or-replacement
https://superuser.com/questions/160134/how-can-i-use-the-windows-7-command-prompt-in-fullscreen
https://superuser.com/questions/884690/fullscreen-dos-console-on-windows-7

All people look for automatic / one-time-configuration solution.

Going fullscreen is extra. I personally don't need it. I am looking to run console maximized. Everyone who runs Emacs want this ))

**Comment by zadjii-msft** [comment]
All of those posts are about the Win7 conhost, which doesn't get any of the new features (including the ability to freely resize the console window) we add to conhost (and won't ever).

I've filed a backlog item to add this setting, MSFT:19308650

**Comment by donovanlange** [comment]
Personal preference, perhaps, but `F11` would be stellar. 

Having used this functionality in Console2/Console.Z for a while, I'll mention that part of the value is hiding some of the other UX (even the tab bar).  If not already considered, would like to call this out for consideration.  As someone who often works on a laptop, the combination of full screen terminal with virtual desktops maximizes screen space for terminal editors, etc.

**Comment by FrigoCoder** [comment]
I always missed this feature from console windows, it would be nice if the new terminal had it.

**Comment by kariem-ali** [comment]
Preserving window size/location/state on exit, like many windows applications do, is a very desirable behavior and might be a good (better?) solution for this without the need for a specific setting.

**Comment by miklevin** [comment]
Made the suggestion here. https://github.com/microsoft/terminal/issues/2386

Doesn't seem to make sense for a Terminal app to not be able to open fullscreen.

**Comment by LubosRemplik** [comment]
+1

**Comment by cpi-akoirala** [comment]
+1.

This is the **only** thing preventing me from switching to Windows Terminal.

**Comment by DHowett-MSFT** [comment]
Wait, isn't this fixed with `"launchMode":"maximized"`? I'm fairly sure we added this in v0.6.

**Comment by mdtauk** [comment]
If a launch full screen option is there, when the full screened app launches, I think the TabView should be visible for a few seconds before sliding out of view.  Moving the mouse to the top would then slide it into view.

**Comment by cpi-akoirala** [comment]
> launchMode":"maximized"

Thanks, @DHowett-MSFT - that is exactly what I was looking for.

**Comment by gauravmanchanda** [comment]
> "launchMode": "maximized"

Works perfectly.
I think this can be closed, as there already is a ticket for further enhancements? #3486

**Comment by gavenkoa** [comment]
Teach me how can I use `"launchMode": "maximized"`.

Latest what I've done was: Properties => Layout => uncheck "Let system position window".

That way it remembers X/Y size and X/Y offset (-4/0 to emulate "full screen").

**Comment by DHowett-MSFT** [comment]
@gavenkoa this is about the new Windows Terminal, not the original console window.

**Comment by gavenkoa** [comment]
@DHowett-MSFT Thanks. Now I see what it is: https://github.com/microsoft/terminal/releases

**Comment by miklevin** [comment]
I am a happy camper. Thank you!

**Comment by oblitum** [comment]
> 
> 
> Wait, isn't this fixed with `"launchMode":"maximized"`? I'm fairly sure we added this in v0.6.

 F11/Alt+Enter allows me to toggle fullscreen, but for me that is not working that setting is not working for it to start in fullscreen mode, it just starts maximized, which means tabs are still visible (even with `"alwaysShowTabs": false`).

**Comment by dancingmonkey** [comment]
> Wait, isn't this fixed with `"launchMode":"maximized"`? I'm fairly sure we added this in v0.6.

Please let us override the default launchMode. As of now it only accepts default and maximized but default is like 80% width of my screen

**Comment by DHowett-MSFT** [comment]
o_O can't you just set `initialColumns`?

**Comment by dancingmonkey** [comment]
> o_O can't you just set `initialColumns`?

Ah nice! Gracias!

**Comment by Poopooracoocoo** [comment]
btw it's a bit weird that win+shift+enter doesn't make it fullscreen but alt+enter does.
