### ISSUE TITLE
Terminal won't start / immediately crashes as of v0.5.2661.0

### ISSUE THREAD

**Issue by vsalvino** [microsoft/terminal#2884]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): v0.5.2661.0

Any other software? PowerShell Core 6.2.2 is also installed.
```

# Steps to reproduce
1. Install windows terminal from either Microsoft Store, or via download from GitHub release.
2. Try to launch the terminal.

Have tried un-installing/re-installing/rebooting multiple times to no avail.

# Expected behavior
Terminal should launch, and at least show an error message.

# Actual behavior

Terminal immediately crashes, you can see the ghost of a window frame before it disappears.

**Comment by DHowett-MSFT** [comment]
Can you share the contents of your profiles.json? `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json`

Thanks.

**Comment by vsalvino** [comment]
Ah thanks for the path, was having trouble tracking down the install folder. The profile seems suspiciously small compared to past versions?
```
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore"
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
```

**Comment by DHowett-MSFT** [comment]
Indeed! That's part of the recent settings reform.

Since it doesn't look like a bad default profile, would you mind sharing a feedback hub link?

**Comment by vsalvino** [comment]
Feedback hub: https://aka.ms/AA63w7j

**Comment by vsalvino** [comment]
After tinkering with the profile.json, It only exhibits this problem when trying to open a Windows PowerShell terminal (which was the default). Changing the default to PowerShell Core or CMD works! Same problem persists when trying to open a Windows PowerShell tab: the new tab immediately crashes/closes.

**Comment by DHowett-MSFT** [comment]
If powershell's not on your path, that's a sign of a serious system misconfiguration. Has something changed the systemwide `PATH` variable? The system-provided powershell should definitely be there.

Otherwise, this is /dup #2563.

**Comment by vsalvino** [comment]
Thanks for the help. Glad there is already an issue for this problem. Yes, many things have changed the PATH over the years (countless developer tools such as git, python, node/npm, ruby, dotnet, docker, and all of the other cruft that comes along with such toolchains). I imagine some botched install or crappy tool must have hosed the PATH at one time.

**Comment by GaaTY** [comment]
I can confirm the PATH thing.

The app was also closing on startup, checked my PATH. No reference to powershell. Added the powershell path to PATH, Terminal opens on my default (which I set to Powershell).
