### ISSUE TITLE
Show alt+# shortcut tooltip when hovering on an unselected tab

### ISSUE THREAD

**Issue by YoungjaeKim** [microsoft/terminal#2886]
# Description of the new feature/enhancement

It would be good to show a shortcut tooltip (`alt+1`, etc) when hovering on an unselected tab.

Users might know the shortcut only if they read Settings.

# Proposed technical implementation details (optional)

N/A

**Comment by zadjii-msft** [comment]
This seems like a good and just idea. I think we already have code for creating a string from a ShortcutAction's key binding as well, so it shouldn't be that hard for someone to add a tooltip to the tab using that text.

**Comment by ggadget6** [comment]
A bit old I know, but can I work on this?

**Comment by DHowett** [comment]
Sure! Feel free to take a crack at it.

**Comment by ggadget6** [comment]
I've been looking around for where the current tooltip is displayed (currently it's just the name of the tab) but I can't find it. Could I get some guidance on where that might be?

**Comment by ggadget6** [comment]
I thought it might be somewhere in the Tab.cpp, Tab.h, or TerminalPage files, but I couldn't find it. I did a search for "tooltip" that ended up bringing me mostly into autogenerated files which didn't seem to help much.

**Comment by zadjii-msft** [comment]
Honestly, we're not generating the tooltips for the TabViewItems currently. I'd bet that they're just being auto-generated by the TabViewItem template itself. Maybe you'll have luck looking in [here](https://github.com/microsoft/microsoft-ui-xaml/tree/98a6b746dc409fa3c64bca4db2c3e6aa31e73470/dev/TabView)?

**Comment by Don-Vito** [comment]
@ggadget6 - this has been stale for  a while, so I allowed myself to work on it.. if you have a solution we can absolutely discard mine.

**Comment by ggadget6** [comment]
@Don-Vito nope, that's fine. I had a partial solution but I got busy and wasn't able to finish it. Yours is fine.
