### ISSUE TITLE
Preview 0.5 asset fails to install (hangs on 'Installing required frameworks 16%')

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/terminal#2890]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): 0.5.2661.0
Any other software? N/A
```

# Steps to reproduce

In https://github.com/microsoft/terminal/issues/2647 I reported that the Github preview asset 0.4 hung when installing behind a company proxy server.  This was fixed by manually installing dependency package: VCLibs.140.

Now, on installing Terminal Preview 0.5, using the GitHub release asset, the same problem happens. There is no indication of the missing dependency. This is on the same machine so I assume VCLibs.140 is still present.

![image](https://user-images.githubusercontent.com/7724321/65578765-5e1f0a80-df6e-11e9-9e48-d0911162f752.png)

**Comment by zadjii-msft** [comment]
_I'm not sure why this thread isn't a dupe of #2647_. The original thread is still open, and we haven't resolved the problem, so whatever caused it to be broken is probably _still_ broken for 0.5. I don't think we need another one of these threads for each release...

/dupe #2647

**Comment by DavidA2014** [comment]
This issue is different to #2647.  #2647 was fixed by manually installing 'C++ Runtime v14 framework package'.  That package is already installed on my machine (same machine as was used for #2647) but the 0.5 asset does not install. Therefore it must be failing because of another dependency, which we need to identify.

Therefore I contend that this is not a duplicate. Please reopen.

**Comment by zadjii-msft** [comment]
Sure, assigning @bitcrazed to loop in the appropriate teams.

**Comment by DavidA2014** [comment]
This problem is still present in 0.6.2951.0. Any chance of a fix please?

**Comment by bitcrazed** [comment]
Thanks for reporting @DavidA2014. We're investigating, but as you can see from the appmanifest, Terminal only depends on the VC 140 RTL redist:

```xml
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.18362.0" MaxVersionTested="10.0.18362.0" />
    <PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.27323.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.27323.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>

It is possible that:
1. Your machine's installation engine is in an incomplete/pending/waiting state and hasn't yet seen the manually installed VC 140 RTL redist
1. Your admin's may have removed/uninstalled the VC redist behind the scenes

Can you please 
1. Install the redist
1. Rebooted your machine
1. (Re) install the Terminal 
```

⚠ If you still see problems, as per [the redist](https://www.microsoft.com/en-us/download/details.aspx?id=53175)'s "Details" section, ensure that your VC 140 Desktop redist is installed. :
>  After installation succeeds: If you look under the folder “C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs” on your machine, you will see the Microsoft.VCLibs.Desktop folder that contain the framework packages for C++ Runtime 14.0.

**Comment by DavidA2014** [comment]
@bitcrazed Thanks for your help.  The redist was already installed. I uninstalled Terminal, rebooted and then ran the 0.6 installer again. It succeeded this time.

I'll close this issue now.  Could you support an installation log to make it easier to diagnose why the installation fails when the redist is not found?

**Comment by bitcrazed** [comment]
Good to know, thanks @DavidA2014. 

It's quite possible that if your corporate Proxy/Firewall may simply block certain calls/responses/traffic causing your machine's installer's state engine to stall, waiting for a response that never comes. If you do see this again, please let us know and we'll broker a conversation with the installer engine team.
