### ISSUE TITLE
Bug Report: C0 control code 0x09 (TABULATOR) not properly sent to terminal emulator.

### ISSUE THREAD

**Issue by christianparpart** [microsoft/terminal#2891]
# Environment

```none
Windows build number: Version 10.0.18362.356
Windows Terminal version (if applicable): 0.4.2382.0

Any other software?: as usual: *mine*. :-)
```

# Steps to reproduce

```sh
echo -ne "a\tb"
```

# Expected behavior

The terminal emulator should receive "a\tb\n" (or "\a\tb\r\n" respectively).

# Actual behavior

Receives `"a\x20\x20\x20\x20\x20\x20\x20b\n"` (I'm using `\x20` here, because GitHub didn't like my actual SPs :) )

**Comment by j4james** [comment]
I believe this is by design. To get the result you're expecting, the terminal would need to support passthrough mode, which is discussed in issue #1173.

**Comment by zadjii-msft** [comment]
Yep, this is definitely a subset of #1173. Conpty doesn't just act as a "dumb pipe" like a *nix pty. That linked thread, as well as #57, have lots on this topic.

**Comment by christianparpart** [comment]
i know. I wanted to make sure you are aware of it. so since i didn't find a duplicate (ugh? tag?) I was creating an issue for it to let you know.
