### ISSUE TITLE
Bug Report (IF I DO NOT CHANGE THIS THE ISSUE WILL BE AUTO-CLOSED)

### ISSUE THREAD

**Issue by ruslanfedoseenko** [microsoft/terminal#2894]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable):Windows Terminal (Preview)
Version: 0.5.2661.0

Any other software?
```

# Steps to reproduce

1. Run Windows Terminal (Preview)
2. In drop down menu press Settings

Running settings 

# Expected behavior
Showing settings for terminal.

# Actual behavior
MS Visual studio is launching with argument /dde instad settings.

**Comment by Marc-B-Reynolds** [comment]
I have had this with all versions I've tried (most recently: 0.5.2661.0).  Visual studio launches and brings up the file "profiles.json".

**Comment by zadjii-msft** [comment]
@Marc-B-Reynolds That's by design, it'll open in whatever program is your default `.json` editor. If you've installed VS, then it'll automatically configure itself as the default json editor.

**Comment by Marc-B-Reynolds** [comment]
Ah ha!  I was expecting a GUI dialog to pop up and assumed it was a bug.  Cheers.

**Comment by ruslanfedoseenko** [comment]
> Ah ha! I was expecting a GUI dialog to pop up and assumed it was a bug. Cheers.

same for me!
