### ISSUE TITLE
Openning Settings launch Visual Studio

### ISSUE THREAD

**Issue by ruslanfedoseenko** [microsoft/terminal#2895]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable):Windows Terminal (Preview)
Version: 0.5.2661.0

Any other software?
Visual Studio 17 15.9.4
```

# Steps to reproduce

1. Run Windows Terminal (Preview)
2. In drop down menu press Settings
# Expected behavior
Showing settings for terminal.

# Actual behavior
MS Visual studio is launching with argument /dde instad settings.

**Comment by j4james** [comment]
This is almost certainly a duplicate. See issues #1422 #1586 #2599.

**Comment by zadjii-msft** [comment]
Yep this is a pile of dupes
