### ISSUE TITLE
Cascadia Code not the new default in 0.5 like it's supposed to be

### ISSUE THREAD

**Issue by cprivite** [microsoft/terminal#2901]
# Environment

```none
Windows build number:  Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable):  0.5.2661.0

If it matters, Cascadia Code was already installed on this machine before the update.

```

# Steps to reproduce

Update to the new Terminal  0.5.2661.0. 
Delete all content from profiles.json. 
Relaunch Terminal and let it regenerate defaults.
Hold down Alt while clicking Settings to see the defaults. 
Scroll down and see that Consolas is still being used as the default.
New size actually is 12, btw.

# Expected behavior

Should be using Cascadia Code as per the release notes.

# Actual behavior

Is still using Consolas.

**Comment by DHowett-MSFT** [comment]
The release notes indicate that it’s _included_, not that it’s the default. We didn’t think it had broad enough character range coverage to be made the default font.

**Comment by zadjii-msft** [comment]
I don't believe the release notes say anything about us using Cascadia Code as the new font by default 😜 . We're simply shipping the font _with_ the terminal for now. If you want to set it as your font, feel free to, but until we work out some additional bugs in the font, we didn't feel comfortable shipping it as the default font for everyone.
