### ISSUE TITLE
Terminal Windows don't snap with PowerToys Fancy Zones

### ISSUE THREAD

**Issue by john-landgrave** [microsoft/terminal#2905]
# Environment

```none
Windows build number: 10.0.18990.0
Windows Terminal version (if applicable): 0.5.2661.0

Any other software?
PowerToys
```

# Steps to reproduce

1. Configure (or use a prebuilt) Fancy Zone from PowerToys, leaving shift+drag to zone enabled.
2. Grab Terminal by the title bar, hold shift, and drag into a zone.

# Expected behavior

I would expect the zone to light up and the terminal to snap to the zone as every other app that I've tried does.

# Actual behavior

The zone doesn't light up and it appears as though it's not registering that I'm even dragging a window into the zone.

This seems like an issue for here, not the PowerToys repo because this is the only app that I've seen that is having this issue.

**Comment by DHowett-MSFT** [comment]
microsoft/PowerToys#209
