### ISSUE TITLE
Crash if Narrator open

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#2907]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18991.1000]
Windows Terminal version (if applicable): 0.5

Any other software?
```

# Steps to reproduce

1. Ensure Windows Terminal isn't open
2. Open Narrator (if it isn't open already)
3. Open Windows Terminal

# Expected behavior

Windows Terminal opens

# Actual behavior

Crash :(

**Comment by carlos-zamora** [comment]
@DHowett-MSFT and I investigated this. It seems to be an issue with the TabViewItem's Icons on startup?

Current workaround is to open Narrator **after** Windows Terminal is open.

**Comment by DHowett-MSFT** [comment]
My job to follow up with MUXC -- it looks like their visual tree is stumping the non-visual-tree visual tree reader.

**Comment by DHowett-MSFT** [comment]
tree. Blocked behind #1896 (FYI)
