### ISSUE TITLE
Store Update of WinTerminal closes open terminals

### ISSUE THREAD

**Issue by wigster** [microsoft/terminal#2910]
# Environment

```
Windows 10.0.18362.0 
Windows Terminal version: upgrading 0.5.2661 -> 0.5.2681 (store version)
```

# Steps to reproduce
* Windows Terminal window open
* Update available in store found by "Get Updates" in Downloads & Updates 
* Update installs automatically
* Update kills all open windows without warning

# Expected behaviour

WT should not begin update if a Windows is open with potential unfinished work

Other Store apps do not begin update if there are open windows. Instead a user-trigger is required by explicit click on Update button

# Actual behaviour

Update occurs leading to potential work loss.

**Comment by DHowett-MSFT** [comment]
I don’t believe terminal can tell the store when it’s in use. Would you mind filing a request on Feedback Hub (in the Windows Store category)? That’ll make sure it gets to the right folks.
