### ISSUE TITLE
Bug Report: ScreenBufferSize is limited to 32766

### ISSUE THREAD

**Issue by sureshkotapydev** [microsoft/terminal#2911]
# Environment
Windows Server 2016 Standard Evaluation

```none
Windows build number: Microsoft Windows [Version 10.0.14393]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

mode con:Lines=32767

# Expected behavior
Should set Lines/ScreenBufferSize to 32767

# Actual behavior
The screen cannot be set to the number of lines and columns specified.

**Comment by zadjii-msft** [comment]
That's a pretty fundamental part of conhost unfortunately. The Console API unfortunately only accepts sizes as `SHORT`s, so we can't resize to anything larger than that, nor can any program tell us to resize to something larger than that. This behavior probably dates back to the _earliest_ versions of Windows.

Changing the console API to accept a larger integer type is also not about to happen. That would be a pretty substantial breaking change, and we're not really investing in the legacy Console API anymore.
