### ISSUE TITLE
The data area passed to a system call is too small.

### ISSUE THREAD

**Issue by jdudleyintelliflo** [microsoft/terminal#2912]
# Environment

Microsoft Windows NT 10.0.18362.0

# Steps to reproduce

Install app from windows store OR build from source and deploy Cascadia package.

# Expected behavior

Terminal runs successfully.

# Actual behavior

Error "The data area passed to a system call is too small." is shown and terminal does not open.

![image](https://user-images.githubusercontent.com/48676819/65696894-f225ca80-e071-11e9-8c71-5b6f5f448329.png)

**Comment by zadjii-msft** [comment]
By any chance is [this page](https://support.microsoft.com/en-us/help/4073393/fix-the-data-area-passed-to-a-system-call-is-too-small-error-when-you) relevant to your scenario?

**Comment by jdudleyintelliflo** [comment]
Ah thanks, yes I saw that page before but somehow I didn't think it was relevant. Will try that and hopefully it will resolve it.

**Comment by jdudleyintelliflo** [comment]
This resolves it - thanks.

**Comment by manugonzalez** [comment]
Hi folks,

I've been running the same error for a while now.
How can this error be fixed?

**Comment by zadjii-msft** [comment]
If you're hitting the same thing as OP, then

> For more information about Desktop Bridge and workarounds for this issue, see [this MSSQL Tiger Team Blog article](https://docs.microsoft.com/en-us/archive/blogs/sql_server_team/centennial-appsdesktop-bridge-sql-server-and-error-the-data-area-passed-to-a-system-call-is-too-small).

From that link:

> The hotfix for this issue for SQL Server 2017, SQL Server 2016 SP1 and SQL Server 2014 SP2 branches was included in following cumulative update.
> 
> https://support.microsoft.com/en-us/help/4073393/fix-the-data-area-passed-to-a-system-call-is-too-small-error-when-you
> 
> Fix for other versions of SQL Server is in progress. I'll update the article as and when additional details are available.
