### ISSUE TITLE
Some default profiles have a different effective default for useAcrylic than the JSON schema

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#2913]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2681.0

Any other software? Applicable to this issue, no.
```

# Steps to reproduce

1. Install Terminal (Preview) from Microsoft Store.
2. Start each of the default shells.

# Expected behavior

All shells default to effectively ```"useAcrylic": false`.

# Actual behavior

It varies. Windows PowerShell and PowerShell Core default to no acrylic. Cmd, Ubuntu, and Azure Cloud Shell default to use acrylic. If you edit settings and type "useAcrylic" for a profile, VSCode (or, I imagine, any software that supports JSON schema) adds `"useAcrylic": false`. If the default setting is false, then why do some profiles use it by default?

**Comment by DHowett-MSFT** [comment]
The default in the schema isn’t exactly a _default_, I learned: its more of a “what will a complying text editor automatically insert for you” (when talking about autogeneration of values). The default profiles are configured to provide a little bit of flair so users know what to expect from their options.

**Comment by DHowett-MSFT** [comment]
(just had a chat with the team: They agree with this assertion. I'm going to close this out.)
