### ISSUE TITLE
Touchpad 2-Finger Scroll Guesture Works in RDP Session but not GUI Shell

### ISSUE THREAD

**Issue by MOrlassino** [microsoft/terminal#2918]
# Environment

Windows Terminal (Preview)
Version: 0.5.2681.0

PowerShell
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

# Steps to reproduce

Scenario 1 (via RDP)
From Windows Terminal Windows PowerShell shell running in a Windows Remote Desktop (RDP) Session:
> clear
> ls c:\ -recurse
Use 2 finger scroll gesture on touchpad -> Vertical scrolling works

Scenario 2 (via native Windows Desktop, i.e. no RDP session)
From Windows Terminal Windows PowerShell shell running in a Windows Remote Desktop (RDP) Session:
> clear
> ls c:\ -recurse
Use 2 finger scroll gesture on touchpad-> Vertical scrolling does not work.

Also, note that both standard "non-Windows Terminal (beta)" legacy built-in CMD and PowerShell terminals work as expected in both scenarios. I.e. All four test cases.

# Expected behavior
Two-finger scroll gesture on the touchpad should work as expected just like in legacy PowerShell and CMD terminals

# Actual behavior
Scrolling does not function except if one is using a Remote Desktop session.

**Comment by DHowett-MSFT** [comment]
@MOrlassino what sort of touchpad hardware and drivers are you on?
