### ISSUE TITLE
Bug Report: "initialRows" value is not parsed correctly

### ISSUE THREAD

**Issue by daviox** [microsoft/terminal#2919]
# Environment

```none
Windows build number: 1903, build 18362
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.5.2681.0

Any other software?
Terminal Font: Fira Code
```

# Steps to reproduce

In CMD: `mode con`

# Expected behavior

`Lines` value equals `initialRows` value defined in profile config.

# Actual behavior

Terminal size is smaller than defined:

![Case 1](https://user-images.githubusercontent.com/25099832/65713723-12697f80-e09a-11e9-801a-67d03f74a805.png)

![Case 2](https://user-images.githubusercontent.com/25099832/65714339-31b4dc80-e09b-11e9-9661-85e4e323dc0d.png)

**Comment by DHowett-MSFT** [comment]
I think we have a dupe for this, I just can't find it right now. Assigning myself.
