### ISSUE TITLE
Powerline arrows rendering at incorrect size

### ISSUE THREAD

**Issue by weswigham** [microsoft/terminal#2921]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2681.0
```

# Steps to reproduce

I imagine this is similar to #633, except it seems like my arrows are rendering _too far to the left_ (and/or too small), rather than having a gap. See:

![image](https://user-images.githubusercontent.com/2932786/65722911-22656d00-e062-11e9-9320-241d06be21e1.png)

I'm using a `Menlo for Powerline` patched font - with a powershell prompt generated by [this](https://github.com/its-not-batch/PSPowerline). For comparison, here's the same prompt in vscode's integrated terminal:

![image](https://user-images.githubusercontent.com/2932786/65723147-a7508680-e062-11e9-86b1-5d877c91eff1.png)

With visible colors:

![image](https://user-images.githubusercontent.com/2932786/65723466-4ecdb900-e063-11e9-8038-08b683c778ef.png)

# Expected behavior

Arrows in the powerline font rendered in full size, aligned with the center of the line.

# Actual behavior

Powerline arrows are rendered at an incorrect size/location - the branch name text is also similarly reduced, it seems.

**Comment by DHowett-MSFT** [comment]
There's a duplicate for this, I just can't find it at the moment. Assigning myself so as I might find it.

**Comment by weswigham** [comment]
I thought #900 was close, but I didn't think powerline arrows count as emoji - moreover, noone else in that thread seems to have the issue.

**Comment by DHowett-MSFT** [comment]
Found it! /dup #610
