### ISSUE TITLE
Entering space character in ipython session freezes the prompt

### ISSUE THREAD

**Issue by pLOPeGG** [microsoft/terminal#2923]
# Environment

Windows build number: 10.0.18362.356,
Terminal: 0.5.2681.0

Python: tried with 3.6 and 3.8 (alpha)
I'm using conda to manage packages (ipython in this case)

This only happens in Terminal tabs, not in basic Powershell / Cmd windows.

# Steps to reproduce

* Open a tab (tried with powershell and cmd).

* Run `ipython`

* Start entering at least one character and then hit spacebar. No more char can be added to the line and ipython doesn't respond anymore.

* Hit Ctrl + C to clear the line

# Expected behavior

We should be able to write spaces in the ipython prompt

# Actual behavior

Space characters are not printed out and make the prompt freeze.

**Comment by pLOPeGG** [comment]
Tried again today with version 0.6.2951.0, the bug is not reproducible anymore. Closing this.

**Comment by geeanlooca** [comment]
I am encountering this exact bug on version 0.10.781.0. Also, maybe unrelated, I have the same bug using the integrated VsCode terminal.

**Comment by pLOPeGG** [comment]
Just tested again, it's working perfectly on my computer on version 0.10.781.0

**Comment by paulflang** [comment]
@geeanlooca : I do have the same problem when running IPython in a VSCode Powershell termial. Have you found a solution?

**Comment by geeanlooca** [comment]
Sorry for the late reply, for some reason it decided to start working again
without me doing anything in particular. I’m afraid I can’t help
