### ISSUE TITLE
Powershell shortcuts/intellisense doesn't fully work

### ISSUE THREAD

**Issue by jtsalten** [microsoft/terminal#2935]
A very useful feature of Powershell terminal is being able to get all commands that start with a particular string just writing the initial letters and clicking Ctrl-Space... that give us a bunch of similar commands to select from. That feature seems missing in new Windows Terminal.
Example: typing ConvertTo<Ctrl-Space>
![imagen](https://user-images.githubusercontent.com/6997495/65764981-40e16c00-e127-11e9-8900-f033ce210ba7.png)

**Comment by zadjii-msft** [comment]
<kbd>ctrl+space</kbd> not working is a known issue, see:
/dup #530 #879 #2556 #2865

You can always rebind the menu complete action to another keychord.
