### ISSUE TITLE
ConPTY fills background incorrectly when resized

### ISSUE THREAD

**Issue by Tyriar** [microsoft/terminal#294]
Repro:

1. echo -e '\x1b[41mabc'
2. Resize terminal vertically

Expected (conhost/wsl.exe):

![image](https://user-images.githubusercontent.com/2193314/47322997-e7b3b300-d60e-11e8-816b-94b5151cc24d.png)

Actual (vscode/conpty/bash.exe):

![image](https://user-images.githubusercontent.com/2193314/47322993-e3879580-d60e-11e8-85a9-b6400d3eb703.png)

**Comment by DHowett-MSFT** [comment]
This _may_ be another case of #32, but it looks craaaaaaaazy so I'm going to leave it open.

**Comment by zadjii-msft** [comment]
Looks like this was fixed at some point in the past, unclear when
![image](https://user-images.githubusercontent.com/18356694/142884719-07ed11a1-4053-48cd-a01e-0757d824a12e.png)


So, I guess it _wasn't_ #32 after all.
