### ISSUE TITLE
WT behaves differently for same configuration in different profiles

### ISSUE THREAD

**Issue by vladhietala** [microsoft/terminal#2943]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version:  0.5.2681.0
```

# Steps to reproduce

Set that profiles in settings: 

```
{
    "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "name": "Windows PowerShell",
    "backgroundImage": "ms-appdata:///roaming/arthas.jpg", //any Image 
    "backgroundImageOpacity": 0.25,
    "backgroundImageStretchMode": "uniformToFill"
},
{
    "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "name": "PowerShell Core",
    "source": "Windows.Terminal.PowershellCore",
    "backgroundImage": "ms-appdata:///roaming/arthas.jpg", //any Image
    "backgroundImageOpacity": 0.25,
    "backgroundImageStretchMode": "uniformToFill"
}
```

# Expected behavior
Both profiles should look the same

# Actual behavior

In the Windows Powershell profile the image is more whitish than in the Powershell Core profile

Powershell Core Profile
![image](https://user-images.githubusercontent.com/3045903/65799503-a7c44c80-e14a-11e9-8743-8fcc64bc04e1.png)

Windows Powershell profile
![image](https://user-images.githubusercontent.com/3045903/65799542-bd397680-e14a-11e9-9c4e-614fafad127d.png)

**Comment by DHowett-MSFT** [comment]
It may not look like a duplicate, but the fix is the same!
