### ISSUE TITLE
Windows Terminal goes blank after some random time running

### ISSUE THREAD

**Issue by javad94** [microsoft/terminal#2948]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): 0.5.2661.0
```

# Steps to reproduce
1. run Windows Terminal 

# Expected behavior
Windows Terminal should work normally and get input.

# Actual behavior
Windows Terminal goes blank and not show the terminal or get any input.

![image](https://user-images.githubusercontent.com/7765309/65809175-631ace80-e1a7-11e9-8cfc-35864ec7380c.png)

**Comment by encladeus** [comment]
This is probably a dupe of #2733.

**Comment by javad94** [comment]
Yes, it is. sorry for duplicate.

**Comment by DHowett-MSFT** [comment]
Thanks!
