### ISSUE TITLE
can't open file 

### ISSUE THREAD

**Issue by wa008** [microsoft/terminal#2950]
\terminal\src\inc\LibraryIncludes.h(51,10): fatal error C1083: can't open file : “wil/Common.h”: No such file or directory

**Comment by DHowett-MSFT** [comment]
You gotta restore submodules man, it’s in the READMEZ

**Comment by wa008** [comment]
thanks！！

**Comment by wa008** [comment]
> You gotta restore submodules, friend, it’s in the README.
thanks！！
