### ISSUE TITLE
Bell does not work or does not exist

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#2952]
Many terminals have `bell` (_beep_), a sound which is activated when the user uses completion or make a mistake typing a command. WT does not seem to have it or I have not understood how to set it. I have tries wit Ubuntu, CMD, PS and my setting of MSYS2. Notice the bell/beep works using MinTTY...

**Comment by j4james** [comment]
I think this is a known issue. The BEL control character is not yet supported by the conpty layer. See #1883 and #1608.

**Comment by zadjii-msft** [comment]
Honestly yea we should be passing through the BEL.

**Comment by angelog0** [comment]
> This issue was addressed in #2990, which has now been successfully released as Windows Terminal Preview v0.5.2762.0

Thanks

**Comment by DHowett-MSFT** [comment]
We're not actually emitting a bell right now, but the underlying infrastructure now supports it.

**Comment by angelog0** [comment]
In WT 0.6... I continue to not hear any bell... does it mean we have to customize something in profiles? In MSYS2 profile I DO hear `bell` but not in Ubuntu or DOS etc...

**Comment by DHowett-MSFT** [comment]
Sorry: this workitem was repurposed to track getting bell working through the intermediate layers of the console subsystem behind Windows Terminal, so that all terminals on windows could start belling. We haven't yet implemented bell support in WT itself.

**Comment by duaneking** [comment]
The above says this is fixed but I'm on Windows 11 Pro and it's not fixed.  This is a critical feature, a part of the core standard that should work automatically, and the fact that it doesn't is broken.
