### ISSUE TITLE
copy some thing in the Windows Terminal Preview 1909 Avatar, can't pause them to wechat

### ISSUE THREAD

**Issue by lijiansheng325** [microsoft/terminal#2957]
# Environment

```none
Microsoft Windows [版本 10.0.18362.356]
Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.5.2681.0

# Steps to reproduce

<!-- 1. input "dir" in the Terminal, copy some thing from the Terminal by select and right click mouse  2.  Pause in the Wechat input windows-->

# Expected behavior

<!--Pause success -->

# Actual behavior

<!-- Pause none  -->

**Comment by fpqc** [comment]
In Terminal, you have to copy with "ctrl+shift+c" after highlighting text with the mouse.

**Comment by lijiansheng325** [comment]
i have try "ctrl+shift+c" , can't pause in Wechat. 
But all copy with right click mouse or  "ctrl+shift+c" can pause in notepad++.

**Comment by fpqc** [comment]
Wechat or `weechat`?

They are different.

Anyway, the problem with weechat exists on Linux as well.  The way this is dealt with is by copy-on-select controls.

To enable this, add the line 

```
"globals" : 
     {
         [...],
        "copyOnSelect" : true
    },
```

**Comment by zadjii-msft** [comment]
@lijiansheng325 Can you share your `profiles.json`? 

What do you have `paste` bound to?

Can you paste into _any_ commandline applications in the Terminal?
