### ISSUE TITLE
Schema location is wrong

### ISSUE THREAD

**Issue by skrysmanski** [microsoft/terminal#2961]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): 0.5.2681.0

Any other software?
Visual Studio Code: 1.38.1
```

# Steps to reproduce

1. Close Windows Terminal
1. Delete any existing `profiles.json` (i.e. Windows Terminal's settings)
1. Re-open Windows Terminal
1. Open newly created `profiles.json` in Visual Studio Code

# Expected behavior

Code completion should work.

# Actual behavior

Code completion does not work because in the newly created `profiles.json` the `$schema` property points to <https://aka.ms/terminal-profiles-schema> which points to <https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json> instead of <https://raw.githubusercontent.com/microsoft/terminal/master/doc/cascadia/profiles.schema.json>.

**Comment by cinnamon-msft** [comment]
Thanks for finding this! I just fixed the link 😊
