### ISSUE TITLE
setting menu error

### ISSUE THREAD

**Issue by sjgamer** [microsoft/terminal#2969]
when ever i click on setting icon it open a .json file in notepad
![Screenshot (20)](https://user-images.githubusercontent.com/55340717/65831824-0caeac80-e2db-11e9-9ecc-5a997f09d29f.png)

**Comment by brunovieira97** [comment]
That's the settings.

**Comment by mdtauk** [comment]
Until the settings UI is finalised and added, it will open up the JSON file where all the settings are stored.

**Comment by zadjii-msft** [comment]
Yea this is a dupe of a ton of issues. Please search before filing new issues:

/dup #1422 #1586 #2599 #2895 #2036 #1928 #1786 #1704 #1460 #1664
