### ISSUE TITLE
Feature Request: Change keyboard shortcut ctrl-W

### ISSUE THREAD

**Issue by gdevacc12** [microsoft/terminal#2973]
Feature request: Change the keyboard shortcut for "closeTab" & "newTab" to something other than ctrl+w ctrl+t respectively.

The keyboard shortcut ctrl-w and ctrl-t are used by popular linux editors (nano, vim, emacs).
Many users may have to edit settings to remove/change this keyboard shortcut.
Changing the shortcut to close tab is some other combination or remove entirely would make it less conflicting.

If changing, propose: "closeTab" change to alt+- and "newTab" i.e. new default profile (alt-shift-0).

**Comment by DHowett-MSFT** [comment]
The default for these commands changed two releases ago; right now they’re on ctrl+shift instead of bare ctrl. If you delete them from your settings file (as of 0.5) Terminal will assume you want the defaults. If you delete your entire key bindings array, doubly so.

**Comment by DHowett-MSFT** [comment]
(Also, thanks for reporting!)

**Comment by gdevacc12** [comment]
Thanks for the feedback. The keybinding settings must have persisted from a previous version.
Apologies I didn't spot the change in the release notes.
