### ISSUE TITLE
Cannot start WindowsTermianl.exe from commandline

### ISSUE THREAD

**Issue by kice** [microsoft/terminal#2974]
I want to start Windows Termianl from folder right-click menu, something like "Open Termianl Here". Since we cannot start UWP by double-clicking the exe. I change the command to start Microsoft Edge to start Windows Termianl, but it did not work.

For Microsoft Edge
```
explorer shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge
```

For WindowsTermianl (dose not work)
```
explorer shell:AppsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!WindowsTerminal
```

Did I miss something here or do we need to change the code in order to make it work?

ref:
https://stackoverflow.com/questions/26244759/opening-a-file-in-a-metro-app-from-command-line

**Comment by ColdEvul** [comment]
Don't think its possible per default but you can add: `%userprofile%\AppData\Local\Microsoft\WindowsApps\` to your path variable this should allow you to call `wt.exe`

For right click manual solution see here: https://github.com/microsoft/terminal/issues/1060

**Comment by DHowett-MSFT** [comment]
@ColdEvul is right, you should use the app execution alias `wt.exe`. It should already be on your `PATH`.
