### ISSUE TITLE
Setup to get vscode intellisense working with the repository

### ISSUE THREAD

**Issue by fpqc** [microsoft/terminal#2977]
I rather like vscode, and I was wondering exactly what setup I need to do in order to get intellisense up and running.  Right now, vscode is reporting errors with my `includePath`, but doing a little bit of digging, I found that by setting up the `compilerPath`, the includepath will be automatically resolved.

Could we have some documentation on how to set up vscode for working with the repo?

Also, what SDKs and compilers do we need?  Do I need to install all of Visual Studio and the entire Windows SDK?

**Comment by zadjii-msft** [comment]
Right now I don't think there's anyone on the team using VsCode as their editor, so you'd probably be the most qualified to write up this guide 😜 

I believe [this file](https://github.com/microsoft/terminal/blob/master/.vsconfig) contains everything that needs to be installed from VS2019 to be able to build the repo.

**Comment by WSLUser** [comment]
Bonus points if you add a setup task to do the auto-build from VS Code vice Visual Studio.

**Comment by zadjii-msft** [comment]
You know, IIRC @miniksa's been using VsCode for a bit now. Did the changes you did in #9297 happen to help auto-configure VsCode?

**Comment by miniksa** [comment]
I checked right now and it looks like it's working if you install the C++ tools extension into VScode. So I'll call this one good? Not certain if #9297 fixed it but hey whatever.
