### ISSUE TITLE
Windows Terminal does not create a Profile for PowerShell Core when install via MSIX or Global Tool

### ISSUE THREAD

**Issue by shanselman** [microsoft/terminal#2982]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18990.1]
Windows Terminal version:  0.5.2622.0
```

# Steps to reproduce

Windows Terminal doesn't find PowerShell Core unless it was installed via a standard MSI.

However, folks can also install PowerShell via  .NET Core global tool (which is makes its detection and location different) https://devblogs.microsoft.com/powershell/introducing-powershell-as-net-global-tool/

Or you can install PowerShell Core via an MSIX installer (not an MSI) https://github.com/PowerShell/PowerShell/releases

I would propose that we detect all three of these PowerShell Core possible installation vehicles and make profiles for them. Example: PowerShell Core (MSIX), PowerShell Core (Global Tool), etc.

# Expected behavior

PowerShell Core is totally ignored when installed in these alternate, but supported, ways.

# Actual behavior

Nada.

**Comment by DHowett-MSFT** [comment]
Hey Scott, thanks! This is a /dup #2300. There’s a comment at the bottom asking for additional guidance on some of these points. Any thoughts?

**Comment by davidfowl** [comment]
I couldn’t even get the msix installed but I can confirm that powershell core isn’t picked up with global tool install
