### ISSUE TITLE
Shortcut key to launch Terminal

### ISSUE THREAD

**Issue by phillip-white-jarden** [microsoft/terminal#2983]
It would be great if shortcut key's would work to launch Windows Terminal. I have created a shortcut from the `shell:AppsFolder` folder, and added a shortcut key. Unfortunately after a restart the shortcut keys stop working.

**Comment by zadjii-msft** [comment]
Could you be more specific on how you're setting the "shortcut key" for the Terminal? This sounds like a Windows Shell feature that I'm totally familiar with.

For the record, you can always use <kbd>Win+[num]</kbd> to launch the N'th shortcut on your taskbar. For example, on my taskbar:
![image](https://user-images.githubusercontent.com/18356694/65886212-8ee1b400-e361-11e9-8c39-c5e19ad304a1.png)

<kbd>Win+1</kbd> launches explorer, <kbd>Win+2</kbd> is Teams, etc.

**Comment by profse** [comment]
I do a standard Windows shortcut, which uses ctrl+alt, to create one with Windows Terminal.  I install through Chocolatey so I found the .exe, which is in 
"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.5.2681.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe"
and created a shortcut to the desktop.  And on that shortcut, right-click and set the shortcut key to s, which sets it to ctrl+alt+s.

**Comment by phillip-white-jarden** [comment]
@profse  Under `C:\Program Files\WindowsApps\` I am unable to access the folder:

![image](https://user-images.githubusercontent.com/51097800/65909365-f876c680-e424-11e9-80d7-be79eb4bbb29.png)

And I am unable to give myself read permissions:

 
![image](https://user-images.githubusercontent.com/51097800/65909463-35db5400-e425-11e9-8d3e-dd2dd47f2af7.png)

@zadjii-msft That works fine, thanks for the tip.

I did find a work around. I can set a shortcut key to launch the app from `C:\Users\user\AppData\Local\Microsoft\WindowsApps\wt.exe`. [WinHotKey ](https://directedge.us/content/winhotkey) can make a shortcut to a VB script (to run cmd in background while the app launches) to launch a bat file to call Windows Terminal.

**VB Script**
```
Set WshShell = CreateObject("WScript.Shell" ) 
WshShell.Run chr(34) & "win_terminal.bat" & Chr(34), 0 
Set WshShell = Nothing 
```

**Bat file**
```
@ECHO OFF
start /B C:\Users\user\AppData\Local\Microsoft\WindowsApps\wt.exe
```

That's the long way round but at least I can have any shortcut key I like.

**Comment by whiter001** [comment]
Desktop shortcut icons can be built like this
![image](https://user-images.githubusercontent.com/19288411/69924893-7ff5ba00-14e8-11ea-9331-3496b8b0c473.png)
Locate windows terminal, from the start menu,  then drag the terminal icon from the start screen to the desktop.

The disadvantage is that a new window opens every time, and the speed is a little slow.

**Comment by rhbecker** [comment]
@profse's recommendation of using a "standard windows shortcut key" works on a shortcut manually created to point at the wt.exe path @phillip-white-jarden mentioned. In the screenshot below, you'll see wt.exe as the target and that I've selected "t" as my "shortcut key" ...

![wt-shortcut](https://user-images.githubusercontent.com/224732/71751841-c153ef00-2e31-11ea-9c51-39d441e0dea0.png)


It would be nice to be able to add that keybinding directly to the shortcut automatically added to the start menu when windows terminal is installed. I don't understand enough about Windows to know why that Windows Terminal start menu shortcut doesn't allow the usual right-click, _more_ > _open file location_, which means I can't find where the start menu shortcut lives. I checked the 2 spots I know about ...

- %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
- C:\ProgramData\Microsoft\Windows\Start Menu\Programs

If it isn't in either of the locations below, where is it?

**Comment by Kimosabe2015** [comment]
Create a desktop shortcut by dragging the icon from the Start Menu. Once on the desktop, right-click the icon and you will see the windows Terminal properties. You can change the Shortcut Key in there and the actual icon. You can grab the icon from Github. https://github.com/microsoft/terminal/blob/master/res/terminal.ico

**Comment by Surya-06** [comment]
Is there a way to create something similar to ctrl+~ on conemu. I think for any multi-tabbed terminal that would be of great use since the existence of multiple tabs is to avoid having multiple windows.

**Comment by saadibadr** [comment]
Here is the easy way, i hope you'll find it usefull

Add **C:\Users\_YOUR_WINDOWS_USERNAME_\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe** to **PATH** (environnement variable)

![image](https://user-images.githubusercontent.com/21370630/83294256-f009a200-a1e4-11ea-96d2-812621e99258.png)

now, WIN+R and type wt

it will start the Terminal directly ^^

**Comment by mobeigi** [comment]
I've tried to customise the shortcut icon used for Windows Terminal but am having trouble, it seems to always fallback to the executable icon for this Windows 10 store app. I like to use a white theme for my taskbar icons.

Any ideas?

![image](https://user-images.githubusercontent.com/5266113/84045959-d2121d80-a9ec-11ea-93c4-92ca72763025.png)

**Comment by LinuxOnTheDesktop** [comment]
What a poster above calls 'the easy way' is not easy. Nor on my system can I find any way of setting a keyboard shortcut for Windows Terminal via File Explorer.

The whole point of the new Windows Terminal is to make Windows looks less bad in comparison with some features of Linux. Until the day comes when one can easily . . open a terminal on windows with a keyboard shortcut, that embarrassment will persist - and irk some users.

**Comment by rodrigocipriani** [comment]
> Could you be more specific on how you're setting the "shortcut key" for the Terminal? This sounds like a Windows Shell feature that I'm totally familiar with.
> 
> For the record, you can always use Win+[num] to launch the N'th shortcut on your taskbar. For example, on my taskbar:
> ![image](https://user-images.githubusercontent.com/18356694/65886212-8ee1b400-e361-11e9-8c39-c5e19ad304a1.png)
> 
> Win+1 launches explorer, Win+2 is Teams, etc.

To me, it works like a charm... 😍
Now I will reorganize all of my taskbar. Thanks' a lot.

**Comment by KwikKwekKwak** [comment]
Just copy the C:\Users_YOUR_WINDOWS_USERNAME_\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe folder to a place where you have all the rights, e.g. C:\Users\{username}\wt.
It's 18.5 MB and you will have no problem creating shortcuts

**Comment by LinuxOnTheDesktop** [comment]
@rodrigocipriani

Thanks for trying to help.

'Could you be more specific on how you're setting the "shortcut key" for the Terminal?' The problem is I see no way to set a shortcut key.

Using Win+[num] to launch taskbar items I find unsatisfactory. For, the items are not numbered and indeed the first of them is not even separated from the first of the - what? - numbered-in-no-sense items. I mean: in your screenshot, File Explorer is the first numbered icon but, also, merely, the fourth item in a row.

@KwikKwekKwak

Thanks for trying to help.

'Just' copy that obscurely named system folder? That seems the sort of thing that will make Windows break later on.

**Comment by rodrigocipriani** [comment]
@LinuxOnTheDesktop 

I can't find the comment I've made that you are taking about. 
But... After you install cmder.net, you don't need to configure nothing to have this hotkey, you have just press Ctrl + ' after open it.

I think a default hotkey like that would be great.

**Comment by LinuxOnTheDesktop** [comment]
@rodrigocipriani

Ah: I find that I was not quoting you - as I thought I was - but rather quoting you quoting someone else.

Isn't [cmder.net](cmder.net) an alternative terminal emulator to the Microsoft terminal? And isn't this the current github about the latter?

**Comment by rodrigocipriani** [comment]
> @rodrigocipriani
> 
> Ah: I find that I was not quoting you - as I thought I was - but rather quoting you quoting someone else.
> 
> Isn't [cmder.net](cmder.net) an alternative terminal emulator to the Microsoft terminal? And isn't this the current github about the latter? EDIT: But, oh, I suppose you are saying: one can have a nice terminal on Windows and one that is launchable via shortcut, by using 'cmder.net'.

Not exactly... Cmder.net is a also a terminal. You can try it. I was using this, but now, after testing new Windows Terminal on preview version, I uninstall cmder, because Windows Terminal is veeeery nice.

I talk about cmder just to compare the hotkey it have natively.

**Comment by mobeigi** [comment]
Hi all, I have somewhat of a workaround that I am which may interest some people.
It has a dependency on AutoHotkey. I have it set up to start Windows Terminal using **Control + Alt + T** (like Ubuntu) in the current directory in context. So I can launch it from inside a folder and have the current directory be set correctly.

Just pushed the code into a public space. See **Windows Terminal Hotkey** in this repo:
https://github.com/mobeigi/AutoHotKey-Scripts

**Comment by LinuxOnTheDesktop** [comment]
mobeigi:

That looks just the thing. Thank you very much. (Autohotkey: making Windows usable, one hack at a time.)

Note for others: of the two scripts, one (namely 'windows-terminal-hotkey.ahk') is the main one and the other ('Explorer.ahk') is sourced from it (like `source`/`.` in shell). And one could compile the thing - using Autohotkey itself - into a single executable.

I will try out the scripts tomorrow.

**Comment by mobeigi** [comment]
@LinuxOnTheDesktop If you come up with any improvements, submit a PR please, I'd like to benefit too!

**Comment by Sadi224** [comment]
PR

**Comment by atjustbeinghumaid** [comment]
@mobeigi where are the instructions to set it up?

**Comment by mobeigi** [comment]
> @mobeigi where are the instructions to set it up?

Have a look online at how AutoHotKey works and how to run AutoHotKey scripts on startup. For the most part, you just make sure the script when your computer starts and it should work for you. I've been using it for a while now with no issues.

**Comment by maxreuben** [comment]
> 
> 
> I've tried to customise the shortcut icon used for Windows Terminal but am having trouble, it seems to always fallback to the executable icon for this Windows 10 store app. I like to use a white theme for my taskbar icons.
> 
> Any ideas?
> 
> ![image](https://user-images.githubusercontent.com/5266113/84045959-d2121d80-a9ec-11ea-93c4-92ca72763025.png)

How did you customize your taskbar like that? (skin&icons both)

**Comment by mobeigi** [comment]
> How did you customize your taskbar like that? (skin&icons both)

Start10 app + using custom white shortcuts icons and pinning them to task bar.

**Comment by carloswm85** [comment]
> Could you be more specific on how you're setting the "shortcut key" for the Terminal? This sounds like a Windows Shell feature that I'm totally familiar with.
> 
> For the record, you can always use Win+[num] to launch the N'th shortcut on your taskbar. For example, on my taskbar:
> ![image](https://user-images.githubusercontent.com/18356694/65886212-8ee1b400-e361-11e9-8c39-c5e19ad304a1.png)
> 
> Win+1 launches explorer, Win+2 is Teams, etc.

`Win` + `1` .. `9` are fantastic, and one would think that it would work also with the numeric pad, but it does not. Does any one if there's a way to make it work that way? I can't use the regular numbers at the top of the keyboard because my keyboard is set differently. 

![image](https://user-images.githubusercontent.com/29048235/129971950-6e3056e1-2088-4a40-8af7-85e59b38fde5.png)

**Comment by zadjii-msft** [comment]
@carloswm85 fwiw the <kbd>win+num</kbd> built in hotkeys are a little less valuable now that you can configure [global hotkeys](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands)

**Comment by kunalkapoor** [comment]
Another option is to use `Win+x -> i` for the terminal. Or `Win+x -> A` to open as administrator.

**Comment by ccrsxx** [comment]
@kunalkapoor Woah, didn't know about this, thanks!

**Comment by hirios** [comment]
I created a python script to do this. By default it is configured to open cmd and work with "ctrl+alt+t", but you can easily configure it. It is also easy to compile an executable with pyinstaller.

https://github.com/hirios/OpenTerminal/

**Comment by VidarDev** [comment]
Open Windows Terminal With a Desktop Shortcut
Desktop shortcuts are one of the most direct ways to open software and apps. So, adding a Windows Terminal shortcut to the desktop will give you a very quick way to open that app. Here is how you can set up a Windows Terminal desktop shortcut within Windows 11:

1. Right-click an area of your desktop wallpaper to select the New and Shortcut context menu options.

![new-and-shortcut-options](https://user-images.githubusercontent.com/98586665/155138599-310ee82b-facd-405f-a08f-8fdc94fe7c40.png)

2. Then input %LocalAppData%\Microsoft\WindowsApps\wt.exe within the item location text box.

![create-shortcut-window2](https://user-images.githubusercontent.com/98586665/155138690-8fab43a4-469d-432c-9012-a175057b8601.png)

3. Click Next to bring up the name box.
4. Type Windows Terminal within the text box.
5. Select Finish to add the shortcut to the desktop.

![windows-terminal-desktop-shortcut](https://user-images.githubusercontent.com/98586665/155138913-fd1bcd7b-ce86-4367-8fa6-36720c1007ea.png)

6. Now click the desktop shortcut to bring up Windows Terminal.
You can configure the shortcut to always run Windows Terminal as an administrator, which might be necessary for certain commands. To do that, right-click the desktop shortcut and select Properties. Select the Run this program as an administrator checkbox on the Compatibility tab shown directly below. Then click Apply, and select OK to close the properties window.

![run-this-program-as-administrator-option](https://user-images.githubusercontent.com/98586665/155139047-37b177dc-49f4-4535-9d70-9ae70065c473.png)

**Comment by SylveonBottle** [comment]
Okay, that's cool and all, but is there any way to do this that doesn't require having a silly icon on my desktop or put me at risk for getting banned in online games for having AHK running?
I just want Ctrl+Shift+T to open a terminal window. And if I press it again, to open another window. Just like Linux. I shouldn't have to go through these silly Windows+X or Run prompts just to type a command to pull up the terminal- A that point I may as well just press Start and search for the terminal. 

Minimal programs, minimal icons, minimal pinned taskbars, minimal keystrokes. 
I don't want to install any programs to get this to work. I don't want to create any desktop shortcuts to get this to work. I don't want to pin any tasks to get this to work. I don't want to press multiple hotkeys to get this to work. I just want it to work. 

Does anyone have a method of opening a new windows terminal without any unnecessary extra stuff?
