### ISSUE TITLE
WT does not respect the initial rows and columns

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#2984]
By default I see that

```
"initialCols": 120,
"initialRows": 30,
```

but truly they are cols=129, rows=28. See 
![wrong-init-rows-cols](https://user-images.githubusercontent.com/35931460/65856786-cc930c80-e362-11e9-9673-5d1dd6fa7be2.png) I tested this also with the original `profile.json`.

May be you intend to include also the tabs row etc. but I think it is wrong. When one sets those parameters in Command prompt (that comes with Windows) the number of rows and columns is respected. See 
![cmd-init-rows-cols](https://user-images.githubusercontent.com/35931460/65857212-ac178200-e363-11e9-9bdd-47c2a0780bd7.png)

**Comment by fpqc** [comment]
The original profiles.json includes 8,8,8,8 padding on cmd.  Could this be the problem?
