### ISSUE TITLE
User keybindings for profiles in the flyout should have priority over default keybindings

### ISSUE THREAD

**Issue by linuxrebel** [microsoft/terminal#2991]
Example:

  If I change the code for launching my Ubuntu instance from ctrl+shift+4 to ctrl+alt+u in the json, the UI still lists the original key combo in the UI.  I feel that if it's available for modification, it should also reflect the new value.

**Comment by zadjii-msft** [comment]
Oh, this is tricky. 

With the v0.5 change, when you add a keybinding for 

```json
{ "command": "newTabProfile3", "keys": ["ctrl+alt+u"] },
```

It doesn't _remove_ the default "newTabProfile3" keybinding, which is still bound to <kbd>ctrl+shift+4</kbd>. Then when we go look up the text for the keybinding, it finds the default one _first_, and uses that keybinding.


We should probably make sure that user-defined ones are found first, right? Not sure if that's possible, considering it's an unordered map.

**Comment by zadjii-msft** [comment]
This similarly affects the bindings we display in the command palette.
