### ISSUE TITLE
Feature Request: Quake style drop down for terminal window

### ISSUE THREAD

**Issue by linuxrebel** [microsoft/terminal#2992]
Requesting that an option exist for a quake style drop down of the terminal window from the top of the screen be added.  (Not unlike ConEmu for windows, Guake or Yakuake)

**Comment by zadjii-msft** [comment]
Please [search](https://github.com/microsoft/terminal/issues?utf8=%E2%9C%93&q=is%3Aissue+quake) before filing new issues. 

/dup #653

**Comment by linuxrebel** [comment]
Please add search as a feature that works Sent from a mail client From: Mike GrieseSent: Monday, September 30, 2019 10:22 AMTo: microsoft/terminalCc: James Sparenberg; AuthorSubject: Re: [microsoft/terminal] Feature Request: Quake style drop down for terminal window (#2992) Please search before filing new issues./dup #653—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by DHowett-MSFT** [comment]
... your email client seriously destroyed your message.
Regardless, we already have an issue tracking Find.
