### ISSUE TITLE
No Accessibility ID locators for UI elements - needed for UI tests 

### ISSUE THREAD

**Issue by hassanuz** [microsoft/terminal#2997]
# Environment

```none
Windows build number: 1903 (Build 18890)
Windows Terminal version (if applicable): N/A 

Any other software? Inspect.exe and UI Recorder to identify UI elements.
```

# Steps to reproduce

1. Launch Terminal
2. Launch Inspect or [UI Recorder](https://github.com/microsoft/WinAppDriver/releases/tag/UIR-v1.1)
3. Attempt to locate Accessibility/Automation ID for the Terminal Tab Elements (big **+** sign and Down Arrow **˅** sign, and the close tab little **x** sign)

# Expected behavior

Inspect.exe is able to recognize Accessibility Attributes in the top bar, and WinAppDriver is able to automate against them.

# Actual behavior

No automation ID attributes being picked up via Inspect.

**Comment by DHowett-MSFT** [comment]
This is a likely /dupe #1896
