### ISSUE TITLE
Bash on Ubuntu on Windows drawing issues while resizing window

### ISSUE THREAD

**Issue by SilviuArdelean** [microsoft/terminal#30]
Updating a Raspberry Pi  with Raspbian OS using 'apt' via SSH in Bash for Windows and resizing the window during the upgrade phase (_sudo apt upgrade -y_) seems to have rows drawing issues.

I was able to reproduce it also within my Bash sub-system while upgrading it.

![clipboard01_bash_resize_while_updating_apt](https://user-images.githubusercontent.com/5840603/30311426-d78cb180-979d-11e7-96b3-57117365243d.jpg)
![clipboard02_bash_resize_while_upgrading_apt](https://user-images.githubusercontent.com/5840603/30311429-d792f48c-979d-11e7-9bf2-585eb03bff1f.jpg)
![clipboard03_bash_resize_while_upgrading_apt](https://user-images.githubusercontent.com/5840603/30311427-d79131ec-979d-11e7-81bb-c8924b365ef0.jpg)
![clipboard04_bash_resize_while_upgrading_apt](https://user-images.githubusercontent.com/5840603/30311428-d792c624-979d-11e7-8181-000ed99fffba.jpg)

**Comment by zadjii-msft** [comment]
I can confirm that this is in fact happening. I can understand why it's happening, given the current workings of the console. However, I don't think a fix would be super easy. I believe this has something to do with out reflowing of the text after a resize event. We keep redrawing the buffer every time the size changes, and then apt is also redrawing on top of that, and everyone gets confused. We might be able to defer reflowing until the resize has stopped, but that might not resolve the problem entirely, and might make it worse.

I'll add it to my bug backlog either way.

**Comment by noscript** [comment]
The problem has probably something do with recognizing `\r` or `^H`.

**Comment by zadjii-msft** [comment]
So, I've taken a closer look at this. I believe the "Right Way" to fix this is to implement a more unix-y buffer. Unfortunately that's a little bit bigger of a task then we can get done for the next release, but (without committing to anything) we do have work planned in that area. 

In the meantime, I'm replacing the "bug" label with the "feature" label - still on our radar, just a little bit farther out.

**Comment by mominshaikhdevs** [comment]
Can this issue be closed now that #8000 is closed?

**Comment by carlos-zamora** [comment]
Yeah, now that #8000 is done, we think that this is as good as it gets. Closing.
