### ISSUE TITLE
Tabs can "forget" focus and title

### ISSUE THREAD

**Issue by richardszalay** [microsoft/terminal#3002]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): 0.5.2661.0
```

# Steps to reproduce

1. Create three tabs
2. Use the CTRL+ALT+{1,2,3} short cut to quickly jump between tabs in random order

I've had the problem occur under more normal usage, but the above steps reproduce it consistently.

# Expected behavior

Tabs continue to change and apply focus.

# Actual behavior

At least one tab will forget it's focused pane, causing:

a) The tab's title to go blank
b) The keyboard bindings to stop responding

Clicking inside the tab's terminal restores the focus, title, and binding responsiveness.

**Comment by DHowett-MSFT** [comment]
This is, weird enough, /dup #1205 :smile:

**Comment by richardszalay** [comment]
Ah yes so it is. It was a tricky one to search for. I might even attempt the PR if I can find the time.
