### ISSUE TITLE
Easy way to get Windows Terminal version info via script

### ISSUE THREAD

**Issue by tig** [microsoft/terminal#3003]
# Description of the new feature/enhancement
I like having my console sessions start with a dump of pertinent version information. I was hoping to find an easy way to get the version info of the Windows Terminal session. I'd add it to my `profile.ps1`:

```
"- posh-git version/path: $($m = Get-Module posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.Prerelease,$m.ModuleBase.Replace($HOME,'~'))`n- PowerShell version: $($PSVersionTable.PSVersion)`n- $(
git --version)`n- OS: $([System.Environment]::OSVersion)`n- Terminal: ($([System.Environment]::WindowsTerminalVersion)"
```
Seems the best place to do this is in an environment variable as I've shown above (`- Terminal: ($([System.Environment]::WindowsTerminalVersion)`).

**Comment by DHowett-MSFT** [comment]
If #1040 were solved, would you be able to use that?

**Comment by tig** [comment]
Yes. Thanks.

**Comment by DHowett-MSFT** [comment]
(Closed as a /dup of #1040)

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;Seven years have elapsed since this issue was opened, and - from what I see in #1040 and on the wider Internet - it is still exceptionally hard to get Windows Terminal to . . report its own version number.

**Comment by DHowett** [comment]
Alternatively, you could look at it as "seven years yet no compelling reason found for applications to detect Terminal's version" :)
