### ISSUE TITLE
Feature Request: Duplicate open tab

### ISSUE THREAD

**Issue by AndreasGalster** [microsoft/terminal#3010]
# Description of the new feature/enhancement

It would be helpful to be able to duplicate an open tab. 

**Use Case:**
I am going into a repo that has two npm scripts, one to run the frontend and one to run the backend. So I run `npm run frontend`, great my frontend server is running. Now I want to go into the same folder on a second terminal window and run the other command `npm run backend`.

Right now I would need to open a new window and manually navigate to the window. It would be very convenient to either right-click in the terminal or on the terminal-tab and have a "duplicate tab" option which opens a new tab in the same folder as the duplicated tab.

**Comment by zadjii-msft** [comment]
This is something we've discussed before, briefly in #1536, but the main meat of the issue is the following:

/dup #1437
