### ISSUE TITLE
When using posh-git, the line being writtens gets desaligned after 3 characters

### ISSUE THREAD

**Issue by jfbueno** [microsoft/terminal#3013]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2681.0
Powershell Core: 6.2.1

Powershell Modules:
posh-git: 1.0.0
PSReadLine: 2.0.0
```

I'm not able to reproduce this bug outside git repos, so I think this is somehow related to posh-git (or maybe the PS1 variable).

> I'm not sure if this is a problem with posh-git or the terminal itself, so I'm posting here looking for some guidance.

# Steps to reproduce

If you're using posh-git, open the terminal on a GIT repository and type something with 3 or more characters. 

# Actual behavior

The line moves one column left.

![terminal2](https://user-images.githubusercontent.com/8502026/65963688-af793f00-e431-11e9-8a6c-3aef520bd13d.gif)

---

## Update

Digging a little bit more into this I've found that this doesn't happen on a branch with no upstream tracking — which is represented by that 3 vertical lines character on posh-git.

So maybe it's related with the `≡` character?

**Comment by zadjii-msft** [comment]
/dup #1584 #635

also related: #2066
