### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nesalang** [microsoft/terminal#3018]
# Description of the new feature/enhancement

There should be an option for choosing default shell. Currently, If one wishes to use WSL, it has to open terminal, then open new tab with wsl. previously, one could simply pin wsl to taskbar, and when needed, one could open the wsl directly.  furthermore, it would be nice to be able to pin terminal multiple times with different default shells. When pinned, it would be preferable to show default shell's icon or something that identifies what is the default shell that will be launched.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is what the `defaultProfile` setting is for. I'd encourage reading [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#global-settings) for more details.

Also refer to [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) for more specifics on how the settings work.

/dup #2546 #1466 #1583 #496
