### ISSUE TITLE
Crash report easier for users to report an issue

### ISSUE THREAD

**Issue by eduardonunesp** [microsoft/terminal#3021]
Sometimes the Terminal crashes and closes without an specific reason, I would like to know if is possible to create a crash report or if is possible to the Terminal to create a crash report.

No need something too fancy on the beginning, it can be just a report file generated on Desktop or on some specific directory.

**Comment by DHowett-MSFT** [comment]
Right now, our major crash report source is Feedback Hub. Filing a feedback item in the feedback hub and sharing the link with us is a pretty good way to collect a crash report.

**Comment by Biswa96** [comment]
How about some event traces? ConHost has many of those GUIDs.

**Comment by DHowett-MSFT** [comment]
We don't have much good or useful eventing around "the applications shuffled off their mortal coil," unfortunately.

**Comment by DHowett-MSFT** [comment]
Sorry -- we can't really detect our own crashes, and we're relying on Windows Error Reporting to get all the crash logs up to us and routed to the appropriate people. I wish we had better reporting here, though!
