### ISSUE TITLE
bold characters are always brightWhite regardless of foreground color

### ISSUE THREAD

**Issue by jdbruner** [microsoft/terminal#3022]
# Environment

```none
Windows build number: 10.0.18995.0
Windows Terminal version (if applicable): 0.5.2661.0

Any other software?
```

# Steps to reproduce

1. Open a wsl tab using a light color scheme (e.g., Solarized Light)
2. echo -e "\033[1mhello\033[0m"

# Expected behavior
"hello" is printed in bold (or at least a darker version of the foreground color)

# Actual behavior
"hello" is printed in brightWhite and is hard to see. (In some color schemes brightWhite is identical to the background color and is completely invisible)

It looks like the interpretation of the ANSI "bold" sequence is simply to render the following text in brightWhite. This "works" if the background is dark and the foreground is light, but it is pretty useless when using a light background and dark text. This impacts all programs that use the ANSI escape sequences (e.g., the "less" pager).

**Comment by DHowett-MSFT** [comment]
Plus #293
