### ISSUE TITLE
SHIFT-Curso, CTRL-C and CTRL-V not working but where in old console

### ISSUE THREAD

**Issue by tryptamic** [microsoft/terminal#3030]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356] 
Windows Terminal version (if applicable): 0.5.2681.0

# Steps to reproduce

Try to select, copy and paste with the normal windows shortcuts for these operations.

# Expected behavior

I can select, copy and paste text with these shortcuts just like in the old console

# Actual behavior

The operations do not work

**Comment by zadjii-msft** [comment]
This is mostly: /dup #2285 #2749

Additionally, keyboard selection is in spec currently at /dup #2840, with the original issue being /dup #715. 

From elsewhere in #2749:
> 
> 
> Don't do that, just add a keybinding for `copy` (that was my bad the action is `copy` not `copyText`).
> 
> ```json
> { "command": "copy", "keys": ["ctrl+c"] },
> { "command": "paste", "keys": ["ctrl+v"] }
> ```
> 
> should do the trick.
> 
> You can set the keybinding to whatever you want. Ctrl+C, Ctrl+Shift+C, Shift+Insert.
