### ISSUE TITLE
Ubuntu session doesn't run bashrc

### ISSUE THREAD

**Issue by halfninja** [microsoft/terminal#3032]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2681.0 (from store)

Any other software?
```

# Steps to reproduce

(Happy for this to be closed if it should be raised with WSL instead.)

* Have WSL installed and a .bashrc file set up
* Open an Ubuntu tab in Windows Terminal

# Expected behavior

.bashrc is executed as this is an interactive shell

# Actual behavior

.bashrc is not executed. Only .bash_profile is executed.

This can be worked around by changing the commandline from `wsl.exe -d Ubuntu` to `wsl.exe -d Ubuntu bash` - but I'm not sure if this is a problem with Terminal, or with WSL. If I use the default shortcut to Ubuntu provided by WSL, that doesn't run .bashrc either, unless I create a similar shortcut to wsl.exe by hand.

**Comment by DHowett-MSFT** [comment]
If it reprise outside if Terminal, it is a WSL issue. :smile:

**Comment by halfninja** [comment]
👌 No problem, I'll go harass them 😃

**Comment by papadi** [comment]
@halfninja , did you harass them? Can you link to the harassment, please? :D

**Comment by papadi** [comment]
WSL issue indeed. Solution is [here](https://github.com/microsoft/WSL/issues/2067#issuecomment-299622057)...
