### ISSUE TITLE
ctrl-w is a terrible default for a terminal to use for 'close window'

### ISSUE THREAD

**Issue by peterwie** [microsoft/terminal#3034]
I keep seeing Windows Terminal 'crash' the current tab when i was using VIM through ssh and doing things that had heavier screen movement commands (like opening and closing windows).

It was only when i was looking through the preferences for something else that i noticed that ctrl-W was bound in my defaults to close tab.  This seems like a surprising and somewhat dangerous default for a terminal.

**Comment by DHowett-MSFT** [comment]
The default `closePane`/`closeTab` binding changed in v0.3; if you've not taken our advice to nuke your settings (mentioned in a couple changelogs), you're a little bit out of date. :smile:
