### ISSUE TITLE
Feature Request: Always On Top

### ISSUE THREAD

**Issue by kwongtn** [microsoft/terminal#3038]
# Description of the new feature/enhancement
Option to let terminal be always on top of all windows, just like the new calculator app. This would be useful for people learning how to do stuff, as it can be on top of the tutorial window while not suffering from text going on to the next line during resizing.

**Comment by zadjii-msft** [comment]
This seems like a good idea. Maybe it could be a setting, but I could certainly see it being something toggle-able at runtime as well. Presumably if the calulator folks can figure it out, so can we 😝 

I suppose my next question would be: what happens when multiple applications want to be "always on top" - who wins?

**Comment by pingzing** [comment]
> I suppose my next question would be: what happens when multiple applications want to be "always on top" - who wins?

[The docs seem to imply](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos) that you only get one stays-on-top Window at a time, and most recent wins.

**Comment by WSLUser** [comment]
I would add that this should be configurable to be "Always on bottom or right/left side", in which case, a setting in profiles.json would be the answer there. A UI toggle once opened would also be nice. The setting would be for setting as a default vice the toggle being good for only while open during that session. Once closed, behavior reverts back to normal when opened again..

**Comment by zadjii-msft** [comment]
@WSLUser there might be a bit of a miscommunication here - I believe this issue more means "always on top _of the z-order_", not literally always on the top portion of the display. Presumably, always on top (of the z-order) would be easily combined with other window positioning mechanisms (that the Windows shell provides) without us needing to create settings for those ourselves.

**Comment by DHowett-MSFT** [comment]
This is an important part of #2238 and a slightly-less-important-but-still-fairly-important part of #653. Yanking triage, leaving it on the backlog. Thanks!

**Comment by AnuthaDev** [comment]
@DHowett Could something like this be more useful? https://blog.walterlv.com/post/dock-window-into-windows-desktop.html

**Comment by zadjii-msft** [comment]
Hey so I've got this done in [`dev/migrie/f/3038-alwaysOnTop`](https://github.com/microsoft/terminal/tree/dev/migrie/f/3038-alwaysOnTop), but I accidentally built that branch on top of #6804. Hopefully we can get that one merged quick so we can sneak this into 1.2 😉
