### ISSUE TITLE
Repository description: "--" should be merged into "–".

### ISSUE THREAD

**Issue by leduyquang753** [microsoft/terminal#3040]
![image](https://user-images.githubusercontent.com/26449060/66114767-b9e63500-e5f9-11e9-8930-65e92abd1017.png)

Currently, the description uses a pseudo en-dash which is actually two hyphens and looks ugly. It should be changed to an actual en-dash (– | `Alt+0150`).

**Comment by zadjii-msft** [comment]
Thanks for the catch :)
