### ISSUE TITLE
In the Terminal. Grag and select some txt, then right click. Terminal crash and exit.

### ISSUE THREAD

**Issue by Pccnzb** [microsoft/terminal#3041]
# Environment

```none
Windows build number: [[版本 10.0.18362.10019]]
Windows Terminal version (if applicable):Windows Terminal (Preview) Version: 0.5.2681.0

Any other software?
```

# Steps to reproduce

when drag and select some character, now right click the mouse. the terminal will exit without any clue.
# Expected behavior
terminal do not exit, and paste the txt I selected.

# Actual behavior
windows closed.

**Comment by zadjii-msft** [comment]
I believe this is a duplicate of #2881, which was fixed by #2927. Thanks!

/dup #2881
