### ISSUE TITLE
Terminal crashed on launch while accessing system through RDP

### ISSUE THREAD

**Issue by asyncpoint** [microsoft/terminal#3043]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.5.2681.0
```

# Steps to reproduce
1. Install the latest (0.5.2681.0) windows terminal on windows 10 (1903), launch it and it works.
2. RDP (using window RDP tool) your system from another windows computer
3. Try to launch the windows terminal, it opens and crashed instantly

# Expected behavior
Terminal should work while accessing it through RDP session

# Actual behavior

Terminal crashed with below given windows event log entry:
Faulting application name: WindowsTerminal.exe, version: 1.0.1909.25001, time stamp: 0x5d8b1a61
Faulting module name: TerminalControl.dll, version: 1.0.1909.25001, time stamp: 0x5d8b194b
Exception code: 0xc0000409
Fault offset: 0x0000000000052691
Faulting process id: 0x1d3c
Faulting application start time: 0x01d579d25edff7c0
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.5.2681.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.5.2681.0_x64__8wekyb3d8bbwe\TerminalControl.dll
Report Id: 98b3041c-8f29-4d12-a639-8deebd0f828f
Faulting package full name: Microsoft.WindowsTerminal_0.5.2681.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by oising** [comment]
It's funny -- my terminal instance crashed while I was on lunch also. Seriously.

**Comment by MikeJerred** [comment]
I also get a crash on startup. It was working fine a few days ago, but now it crashes every time I try to start it. Possibly caused by a recent update to Windows - I installed an update recently.

Currently OS build is: Windows 10 x64 version 1903, OS build: 18362.356

**Comment by DHowett-MSFT** [comment]
/feedback

This still needs a feedback item, but the bot un-marked it as such. Sorry/thanks!
