### ISSUE TITLE
Can I save/redirect the output text in the terminal to some file? Just like ConEmu & SecrurCRT does?

### ISSUE THREAD

**Issue by 19317362** [microsoft/terminal#3044]
# I've tried WSL2 + docker + Windows Terminal.  It's very good for developing.
  It will be better if some features in SecureCRT & ConEmu can be introduced,

## Save or redirect the output text in the terminal to some file with this feature

1. The format of the filename can be generated like yyyy-mm-dd_HH_MM_SS.log
    (like SecureCRT).  
    This is very useful while using something like adb logcat etc.

2. Can change a new file while day changing.

3. File name has session name (just like SecureCRT & ConEmu

**Comment by Biswa96** [comment]
`adb logcat` already has a `-f` option to dump output in a file.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This sounds to me like it's just about the same thing as #642, so I'm going to close in favor of that original one.

/dup #642

**Comment by 19317362** [comment]
> Thanks for the suggestion! This sounds to me like it's just about the same thing as #642, so I'm going to close in favor of that original one.
> 
> /dup #642

Yes. It's duplicate.
The feature of SecureCRT is very useful for long time runing (several days for test & debug with log).
