### ISSUE TITLE
colorScheme for the powershell profile is ignored

### ISSUE THREAD

**Issue by garth** [microsoft/terminal#3054]
# Environment

```
Microsoft Windows [Version 10.0.18995.1]
Windows Terminal version (if applicable): 0.5.2681.0

```

# Steps to reproduce

set "colorScheme" to setting under powershell profile to one of the scheme listed in the settings file. 

# Expected behavior

The custom theme should be used

# Actual behavior

The standard blue powershell theme is still shown

# Notes

Other profiles seem to accept and use the configured color theme correctly

**Comment by zadjii-msft** [comment]
Thanks for the report! This looks like something that's hitting quite a few people, but fortunately, one we already have a fix for :)

/dup #2883 #2936 #2978 #2943 #2925 #2902 #3012

**Comment by claudiusraphaelpaeth** [comment]
So where is the solution?

[Resolution-Duplicate](https://github.com/microsoft/terminal/labels/Resolution-Duplicate) mentioned, leads into nothingness ("No results matched your search") ...

I stumbled across this problem (again) in the latest "Windows Professional Insider Slow Ring (19631.1)" with "Windows Terminal (1.0.1401.0)".
