### ISSUE TITLE
sentence in "azure cloud shell" tab didn't show correctly

### ISSUE THREAD

**Issue by zhangzp9970** [microsoft/terminal#3055]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable):
Version: 0.5.2681.0

Any other software?
```

# Steps to reproduce

first, open the windows terminal and then open the azure cloud shell tab, you will see someting like this:
![图片](https://user-images.githubusercontent.com/30102054/66203330-b5de1400-e6da-11e9-9732-257659c3f667.png)
exactly, some words are missing after the word "enter"
then, when I maximize the window and reopen that tab, the correct sentence will show:
![图片](https://user-images.githubusercontent.com/30102054/66203642-6ea45300-e6db-11e9-92b3-5bf6e49b9d9a.png)

# Expected behavior

see the full sentence
# Actual behavior

some words disappeared

**Comment by zadjii-msft** [comment]
Thanks for the report! This looks like #2588 to me, which is actually going to be the same root problem as #780.

/dup #2588 #780 #2581
