### ISSUE TITLE
About the default open question

### ISSUE THREAD

**Issue by qaralotte** [microsoft/terminal#3056]
[Environment] Windows 10 1903 18362.356
1.In general, when I type 'cmd' in the address bar of a folder, cmd will switch the directory location to the location of the folder.However, if the open is 'wt', it is still the same, he still opens C:\\Users\\XXXX，even if I did not write the parameter ”startingDirectory“.
2.Even if I set the WSL ‘startingDirectory’ parameter on the terminal to the absolute location of a folder in the wsl root directory, he still opens the root directory of wsl.

---
If it is my parameters are not written, please advise
If it is a bug, please fix it as soon as possible.

**Comment by zadjii-msft** [comment]
Thanks for the bug report! Let me try and break each of these down:

1. This is the same issue as #878. Unfortunately, if you have a `startingDirectory` set, you won't currently be able to use explorer to open the Windows Terminal in the current directory.
2. This sounds quite a bit like #592, though I could be misunderstanding. `startingDirectory` needs to be a _Windows_ path, not a WSL path.

/dup #878
/dup #592
