### ISSUE TITLE
Add backgroundOpacity option

### ISSUE THREAD

**Issue by crydotsnake** [microsoft/terminal#3059]
Maybe add an `backgroundOpacity` option to make the background transparent. I found no option to do this in the settings. Sorry if there is already an option to do that!.

**Comment by Biswa96** [comment]
See `acrylicOpacity` option in this [Settings Schema](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md).

**Comment by crydotsnake** [comment]
Oh, i'm sorry!. I didnt saw that 😕 !. Thank you!.
