### ISSUE TITLE
Add a configuration object for focused vs unfocused state

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3062]
Follow up from #994.

Originally suggested by @cdmihai in #994 
> 
> Hyper changes the text color. The focused pane uses a saturated, bright version of the font color, the out of focus panes use a desaturated, dark version of the font. I found that this makes it quite visually intuitive to instantly notice which pane is active. Yet the other panes are still quite readable.
>
> Sounds like the holy grail would be to have a configuration object for pane switching features (text fonts, background colors, borders, cursor, etc) with some sensible accessible defaults.

Taking that idea and running with it, what if each profile could specify an "unfocused" state that's used when it loses focus?
```json
    "profiles":
    [
        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",

            "colorScheme": "Solarized Dark",
            "cursorColor": "#FF00FF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 12,
            "foreground": "#C0C0C0",
            "background": "#000000",

            "unfocusedState": 
            {
                "colorScheme": "Campbell",
                "cursorColor": "#888",
                "cursorShape": "emptyBox",
                "foreground": "#C0C0C0",
                "background": "#000000"
            }
        }
    ],
```

Presumably, `backgroundImage` settings would also be fine in that block.

Things I _wouldn't_ want to enable in this block:
* Anything that causes a resize. `padding`, `fontFace`, `fontSize`.
* The acrylic settings. Acrylic doesn't work when the window _isn't_ focused, and I wouldn't want people to think that it magically will if they add that setting. <sup>[1]</sup>

###### [1]: Technically, with split panes, they could have an unfocused control that could still have an acrylic BG, as long as the window remains focused. 

<hr>

I'm realizing now that this is strictly a superset of #2316, and will also resolve that one. I maybe could have just used that thread originally.

<hr>

26 Mar 2020: #5130 brought up the good point that this should also include enabling the cursor to still be On, even when the control isn't focused

**Comment by DHowett-MSFT** [comment]
Yanking Triage -- this is a neat feature, but it does require a little bit of thinkin' about.

**Comment by coupez** [comment]
Why is it not possible to permanently allow acrylic settings, both in a focused as in an unfocused state?  I understand it makes sense on laptops to save battery, but it's not possible on a desktop PC either.

**Comment by zadjii-msft** [comment]
@coupez There's actually a bunch of other threads that have covered that discussion, but this isn't one of them. This mostly tracks controlling the appearance of an active pane vs inactive panes, when there are many panes in the same tab. For discussion on how acrylic works, see: #2326, #1886, #1747, #1546, #1505, #1099, #593, #3336, #2763, #2698, #3497

**Comment by solariz** [comment]
Sure it's "just" a cosmetic thing, but isn't the new Term also about a cosmetic refresh? So for me it is totally annoying having it going totally black when not focused. Looks pretty bad und totally uneccessary.

**Comment by anwar3606** [comment]
not even a hack for the Acrylic to be present when the focus is lost?

**Comment by reinux** [comment]
The lack of Acrylic on background windows turns out to be [a deliberate Windows 10 limitation](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#usability-and-adaptability).

Even back on Vista hardware, when there were a ton of false rumors about its resource consumption, Aero Glass being a culprit for battery consumption was ruled out by everyone who bothered to test the theory.

So this decision on the Windows team's part strikes me as being really bizarre, even from a PR standpoint, as it validates those claims.

**Comment by zadjii-msft** [comment]
This isn't the thread to discuss whether acrylic should be enabled when the window is focused or not. There's like 11 threads I linked above that are better suited for that discussion. There's also #7158 which is tracking investigating if unfocused acrylic is possible in the Terminal. I'd ask that we re-direct this discussion to that thread, thanks.
