### ISSUE TITLE
Dragging causes UI to dissapear

### ISSUE THREAD

**Issue by Bogidon** [microsoft/terminal#3065]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.388]
Windows Terminal version (if applicable): 0.5.2762.0
15" 2015 MacBook Pro -- integrated graphics

Any other software?
Ubuntu 1804.2019.521
```

# Steps to reproduce

1. Open Windows terminal
2. Drag window

# Actual behavior

![image](https://user-images.githubusercontent.com/3252307/66232503-d340bd00-e69d-11e9-9330-df52ab251134.png)

**Comment by itKelis** [comment]
I have an exact problem

**Comment by Bogidon** [comment]
Not happening so far today. System hasn't changed except for a reboot.

**Comment by carlos-zamora** [comment]
If anybody can provide a consistent repro on this, that would be much appreciated. Not occurring on my machine. :)

**Comment by lapazddd** [comment]
I have the same problem and I can only close the window from the task bar. The app was installed from  MS store.

**Comment by DHowett-MSFT** [comment]
Nobody on the team has hit this, still, but I'm tagging it into v1.0 because it's _pretty bad._

**Comment by Yasharah** [comment]
Hello,
i have the same problem and its also fixed if  it set this in the profiles.json:
    "initialCols": 90,
    "initialRows": 25,

I installed the app from the MS Store and tried with choco and the one from git :(

**Comment by lapazddd** [comment]
Hi, I've tested some combinations of 'initialCols' and 'initialRows' in profiles.json and here are the results:

initialCols | initialRows | disappear after   draging?
-- | -- | --
90 | 24 | No
90 | 25 | No
90 | 26 | Yes
90 | 30 | Yes
91 | 30 | Yes
92 | 30 | Yes
95 | 30 | No
100 | 25 | No
100 | 26 | Yes
100 | 30 | Yes
110 | 30 | No
120 | 26 | No
120 | 30 | No
150 | 30 | No

It seems strange and i cannot find exactly how it works, but fortunately I found that you can double-click the window for twice to maximize it and recover it, and you will find everything in the terminal back.
Anyway, it is still a very good app despite this problem and I hope you can figure it out one day.
Thanks~
