### ISSUE TITLE
Terminal takes >2 mins to start-up on ARM64

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#3067]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0

Any other software? VSCode, Office, 
```

# Steps to reproduce
1. Install Terminal from the store
1. Wait for installation to complete
1. Launch terminal

# Expected behavior
Terminal opens.

# Actual behavior
Terminal fails to start correctly. App process is created, but Terminal window fails to render its content to appears almost entirely transparent. Sometimes, the outer non-client area is visible and draggable which leaves pixel-trash on-screen.

HOWEVER, Terminal does finally appear on-screen after ~2 mins:
![image](https://user-images.githubusercontent.com/961950/66247576-d6a26b80-e6d2-11e9-8e3e-21b2dd0c4cff.png)

**Comment by DHowett-MSFT** [comment]
ARM64, not AMD

**Comment by DHowett-MSFT** [comment]
Couldn't repro under debug, problem seems to have gone away.
