### ISSUE TITLE
Slider does not work 

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#3069]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.388]
Windows Terminal version (if applicable): Version: 0.5.2762.0
```

# Steps to reproduce

Type a command in command prompt which outputs more lines than fit on screen 
(i.e.: for /l %f in (1,1,100) do @echo abcdefghijklmnopqrstuvwxyz %f )

# Expected behavior

Pulling the slider up, should scroll the window (up)

# Actual behavior

See this:
![WT_Slider](https://user-images.githubusercontent.com/7850737/66252047-1f036d00-e757-11e9-84b8-a9b0dd4bb512.gif)

**Comment by DHowett-MSFT** [comment]
Does this seem to happen more often when you resize the Terminal, or can you reproduce it from a totally new session?
It looks like your scrollback buffer is already at maximum height. What is your `historySize`?

**Comment by Luuk34** [comment]
This is the part of my profile for command prompt:

>       {
>             "acrylicOpacity" : 0.75,
>             "closeOnExit" : true,
>             "colorScheme" : "Campbell",
>             "commandline" : "cmd.exe",
>             "cursorColor" : "#FFFFFF",
>             "cursorShape" : "bar",
>             "fontFace" : "Consolas",
>             "fontSize" : 10,
>             "guid" : "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
>             "historySize" : 9001,
>             "icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
>             "name" : "cmd",
>             "padding" : "0, 0, 0, 0",
>             "snapOnInput" : true,
>             "startingDirectory" : "D:\\TEMP\\",
>             "tabTitle" : "CMD",
>             "useAcrylic" : true
>         },

**Comment by Luuk34** [comment]
hhmmmm, something changed....
The described problem is only visible when using the for loop till 100000
(for /l %f in (1,1,100000) do @echo abcdefghijklmnopqrstuvwxyz %f)

Scolling back should still be possible when this is done, or not?

**Comment by DHowett-MSFT** [comment]
This is probably the same root cause as /dup #1494, even though that one only happens on resize. We should revisit our scroller code. :smile:
