### ISSUE TITLE
Cannot use Chinese input method

### ISSUE THREAD

**Issue by zwn19910807** [microsoft/terminal#3070]
Cannot use Chinese input method

**Comment by j4james** [comment]
Sounds like a duplicate of #2213.

**Comment by etern** [comment]
`CJK IME` (#2213) is not a well known notion, I suggest keep this issue to prevent more duplicate ones

**Comment by j4james** [comment]
You really don't need to know what CJK or IME mean to find that issue. The moment you try and open a bug report with the subject "chinese input method", the system will immediately point out three closed issues (now four) with very similar titles, all marked as duplicates of #2213.

**Comment by DHowett-MSFT** [comment]
Thanks @j4james, and thanks @zwn19910807 for the bug report. /dup #2213.
