### ISSUE TITLE
Profiles Appearing Even After Being Deleted.

### ISSUE THREAD

**Issue by NickITGuy** [microsoft/terminal#3071]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.388]
Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
Git Bash

# Steps to reproduce

Delete Powershell Profile and Azure profile
Save

# Expected behavior

The profiles are deleted.

# Actual behavior

On save deleted profiles come back, and powershell appears even though its not in the settings.

**Comment by Luuk34** [comment]
I have this problem too.

**Comment by mrdrwest** [comment]
Having similar problem.

The following keep reappearing after deletion from my profiles.json:

        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore"
        },
        {
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl"
        }

**Comment by DHowett-MSFT** [comment]
Set hidden to true to remove them. This is by design, as Terminal cannot tell a profile you’ve deleted from a profile you never had.

**Comment by mrdrwest** [comment]
Rgr that. I thought about doing that earlier, but didn't because it was an extra step.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NickITGuy** [comment]
@DHowett Whats interesting is that I dont have that hidden option for powershell but it shows up anyway (I had already deleted it from my profiles.json a long time ago.)

**Comment by DHowett-MSFT** [comment]
There’s a few intricacies here. If you’re talking about PowerShell Core, it should reappear with a reset `hidden` flag. If you’re talking about Windows PowerShell, however, you’ll need to explicitly suppress that one. It gets inherited from the _default_ settings, which you can see/copy data out of by holding down <kbd>Alt</kbd> while clicking on the Settings menu item.

The “empty state” user settings do include a stub for Windows PowerShell, which does contain `hidden`.

**Comment by Luuk34** [comment]
`which you can see/copy data out of by holding down Alt while clicking on the Settings menu item.`

Why not with ALT+CTRL+','. Because CTRL+',' opens Settings.

**Comment by DHowett-MSFT** [comment]
Because we didn't get that far. :smile:
