### ISSUE TITLE
Add ability to daemonize proccesses

### ISSUE THREAD

**Issue by qwright10** [microsoft/terminal#3072]
# Description of the new feature/enhancement
There should be a button if you right-click the shell tab where you can "Daemonize Process." This can make the process run in the background so the terminal/tab can be closed. Then, when returning to the terminal later, you can click on some button and view daemonized processes. You should also have the ability to start it at a certain time, such as 30 seconds after startup.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the feature request! Unfortunately, it's not really the Terminal's job to handle process daemonization. We appreciate that you might want that, however!
