### ISSUE TITLE
Applying changed environmental variables (such as PATH)

### ISSUE THREAD

**Issue by HubKing** [microsoft/terminal#3074]
# Description of the new feature/enhancement
It seems that I have to restart the application to apply changed environmental variables (such as PATH). Opening a new "cmd" tab did not reflect the changes. 

How about adding an option to read environmental variables again when opening a new "cmd" tab? Or a "Refresh environmental variables" entry in the drop-down menu.

**Comment by DHowett-MSFT** [comment]
Thanks! This is going to be /dup #1125.
