### ISSUE TITLE
'ø' displayed as 'o' in PowerShell

### ISSUE THREAD

**Issue by Raytar** [microsoft/terminal#308]
When I type an 'Ø' in PowerShell it is displayed as an 'O' but still interpreted as an 'Ø'.
Works as expected in cmd.exe and WSL

* Your Windows build number: 10.0.17763.107
It didn't happen on 1803.

* What you're doing and what's happening:
I type 'ø' or 'Ø' into powershell and it displays an 'o' or 'O'

* What's wrong / what should be happening instead:
It should display an 'ø', not an 'o'

![powershell_2018-11-14_10-27-23](https://user-images.githubusercontent.com/10762082/48473192-4b896000-e7f8-11e8-8997-c1d5869f6875.png)

**Comment by zadjii-msft** [comment]
Works in cmd and wsl but not powershell? That sure sounds like a powershell issue to me. 
Summoning @SteveL-MSFT and @lzybkr 

Does it repro still if you `Remove-Module PSReadline`?

**Comment by lzybkr** [comment]
This seems to be encoding related. PSReadLine sets the output encoding to UTF8, but after returning, the encoding is restored to the previous encoding.

If the previous encoding was UTF8, then it seems to work correctly:

![image](https://user-images.githubusercontent.com/2148248/48501584-62c54f00-e7f2-11e8-8736-cadda635d019.png)

And the text from that screen capture:

```
PS E:\> $x = "O"; [Console]::WriteLine($x); $x
O
Ø
PS E:\> [Console]::OutputEncoding


IsSingleByte      : True
BodyName          : IBM437
EncodingName      : OEM United States
HeaderName        : IBM437
WebName           : IBM437
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : False
CodePage          : 437



PS E:\> [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
PS E:\> $x = "Ø"; [Console]::WriteLine($x); $x
Ø
Ø

**Comment by Raytar** [comment]
It does not repro after running `Remove-Module PSReadline`

**Comment by DHowett-MSFT** [comment]
@lzybkr It looks like I can't do an issue transfer over to PSReadline. Are you able to, or should we manually mirror it?

**Comment by lzybkr** [comment]
Any tool changing the output encoding would hit this.  Does that mean changing the output encoding is not supported?

**Comment by SteveL-MSFT** [comment]
@DHowett-MSFT I believe the issue transfer feature only works within the same GitHub org.  You can use https://github.com/google/github-issue-mover which copies it over to a target repo.
