### ISSUE TITLE
Split screen shouldn't open the default shell in a new pane

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#3083]
Split screen in Windows Terminal opens the default shell in a new pane. Wouldn't be better to open the same kind of shell? (e.g. if I'm in #PowerShell Core, don't open Windows PowerShell in a new pane, open PowerShell Core again).

**Comment by DHowett-MSFT** [comment]
Thanks for reporting. This is tracked as one of the linked issues from /dup #1000.
