### ISSUE TITLE
Enable auto-completion on cmd

### ISSUE THREAD

**Issue by lucamauri** [microsoft/terminal#3091]
# Environment
Windows build number: `Microsoft Windows [Version 10.0.18362.356]`
Windows Terminal version: `Windows Terminal (Preview) - Version: 0.5.2762.0`

# Steps to reproduce
I very often need to use `cmd` so the auto-completion feature is very useful to me. I normally activate it by invoking the command prompt with `cmd /f:on` from Windows Run.
I noticed the command prompt comes with no auto-completion out of the box in MS Terminal. so I proceeded modifying the settings in `profiles.json` from

`"commandline": "cmd.exe",`

to

`"commandline": "cmd.exe /f:on",`

# Expected behavior
I expected any new CMD window to open with auto-completion enabled

# Actual behavior
Auto-completion is not enabled

**Comment by HBelusca** [comment]
Sounds like a problem of arguments passing?

**Comment by DHowett-MSFT** [comment]
Hey @lucamauri, thanks for filing this feature request! Since it's so easy to add `/f:on` to profiles.json for users who want it, I don't think we're liable to make it the default. CMD is our legacy, and we're not really looking to make changes to user expectation here. Sorry!

**Comment by lucamauri** [comment]
Dear @DHowett-MSFT I am not sue I got your point. I opened this ticket exactly to explain that adding `/f:on` to profiles.json _does not_ work.
Here you are telling me this is very easy to do: yes, it is easy, but my point is that it does not do what it is expected to.
I am not saying that you are liable of anything or that you should make any modification to a default: I am just explaining that this customization does not work.
Thanks for helping with this

**Comment by DHowett-MSFT** [comment]
Oh! Interesting. If I understand correctly, `/f:on` should make <kbd>Ctrl+F</kbd> and <kbd>Ctrl+D</kbd> complete filenames and directories separately? When I add that to my cmd command line, it does work.

Can you share your entire profiles.json?
Thanks!

**Comment by lucamauri** [comment]
Dear @DHowett-MSFT I found the issue.
While
`"commandline": "cmd.exe /f:on",`
does not work,
`"commandline": "cmd /f:on",`
works instead, so it seems the problem is `.exe`.
All in all, it looks this is not actually a bug, but maybe something to note in the documentation to give the user a heads-up.

In regards to your question on `/f:on`, for further information please refer to this documentation https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd

Thanks for the help

Luca

**Comment by DHowett-MSFT** [comment]
That's really strange. It works fine for me with or without the `.exe`.

**Comment by DHowett-MSFT** [comment]
Thanks for the report!

**Comment by DHowett-MSFT** [comment]
Is this still happening? Can you run `where cmd` from cmd?
