### ISSUE TITLE
Terminal: add support for showing/hiding the cursor (DECSET/DECRST 25, DECTCEM)

### ISSUE THREAD

**Issue by egmontkob** [microsoft/terminal#3093]
# Environment

```none
Windows build number: Win32NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

    printf '\e[?25l'

# Expected behavior

The cursor should become invisible.

# Actual behavior

The cursor remains visible and blinking. It is often misplaced on subsequent operations, though.

E.g. press the Up arrow, it brings back the previous printf command to the command line. Press the Left arrow, the cursor doesn't move. Press Backspace, the letter `l` is removed (that is, the logical cursor did indeed move to the left in the previous step), the cursor now blinks at the right edge.

**Comment by DHowett-MSFT** [comment]
Hey, we actually just got ConPTY support for rendering the cursor's hidden state (#2829). Right now, if conhost thinks the cursor is hidden it's not liable to leave it in the right place... I think we have another bug in here somewhere about the cursor being misplaced when deleting characters (and that's definitely something we shouldn't do :P)

**Comment by DHowett-MSFT** [comment]
Tearing off the Triage tag: this is now the master Task for supporting cursor hiding in WT. :smile:

(when the cursor is hidden by the application, conhost is a lot more lax in keeping its location in sync with the connected terminal)

**Comment by j4james** [comment]
Note that the escape sequence used by the `XtermEngine` to hide the cursor is incorrect:

https://github.com/microsoft/terminal/blob/6f667f48ae109d4291cda1f8d4e977315c0dae8a/src/renderer/vt/XtermEngine.cpp#L106-L112

The `\x1b[25l` should be `\x1b[?25l`.

**Comment by zadjii-msft** [comment]
@j4james holy crap that's a good catch

**Comment by zadjii-msft** [comment]
note to self: I'm waiting on #4859 to merge because that PR's got most of the implementation of `TerminalDispatch::_PrivateModeParamsHelper` (where these sequences would need to be handled), and I don't want to create a massive merge conflict
