### ISSUE TITLE
UI Change Tabs Design

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [microsoft/terminal#3095]
Change the UI for tab tiles, increase the height respective to the window action buttons. Same as edge, currently there height is not suitable and there edges are cornered, which resemble material design instead of fluent design. Plus make the design consistent with the tab actions buttons (e.g. '+'). One has outline effect on hover, other has text color change. The edge design is very polished, it should follow its footsteps for fluent design.

**Comment by DHowett-MSFT** [comment]
Hey there, thanks for reaching out. A lot of this is covered in /dup #1375. We'll converge with the new tab control when we finish #1896, which should address a few of these.
