### ISSUE TITLE
Pwsh not found if installed as .NET Core global tool

### ISSUE THREAD

**Issue by onovotny** [microsoft/terminal#3096]
# Environment

```none
Windows 10 188995
Latest nightly terminal build as-of 10/6

```

# Steps to reproduce

Install PowerShell Core as a .NET Core global tool. `dotnet tool install -g powershell`. Confirm it works when you use `pwsh.exe`. 

Create a new PowerShell Core profile and set "source": to "Windows.Terminal.PowershellCore". And open a new shell. Doesn't work. Commenting out `source` and using `"commandLine": "pwsh.exe"` works, as it is in the path.

# Expected behavior
PowerShell Core should load.

# Actual behavior
Profile is skipped or doesn't load.

**Comment by DHowett-MSFT** [comment]
This'll largely be handled with /dup #2300. Thanks!

**Comment by DHowett-MSFT** [comment]
(We'll make sure to grab `pwsh.exe` wherever it lives and trust the system path as part of 2300)
