### ISSUE TITLE
Allow more settings to be global, not per profile

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#3098]
# Description of the new feature/enhancement
Currently it is not possible to set `colorScheme` or `padding` on a global level, only per profile. 

# Proposed technical implementation details (optional)

Every setting that can be per-profile, minus the obvious ones like name and guid etc, should be able to be set on a global level as well.

**Comment by DHowett-MSFT** [comment]
This'll be addressed by /dup #2325. Thanks!
