### ISSUE TITLE
Alt arrow keys print extra characters

### ISSUE THREAD

**Issue by paulwhiting** [microsoft/terminal#3101]
Terminal Version: 0.5.2762.0
Microsoft Windows [Version 10.0.18362.356]

### Steps to reproduce
Open terminal.  Press alt-up, alt-down, alt-right, alt-left.

(For byobu:  start byobu with 'byobu'.  Press F2 to add a new tab.  Press alt-right and alt-left to switch between tabs.)

### Expected behavior

- When not running something like byobu perhaps [the letters ABCD should be printed out](https://unix.stackexchange.com/questions/73669/what-are-the-characters-printed-when-altarrow-keys-are-pressed).

- When using byobu to manage console sessions it should switch between tabs.

### Observed behavior

- c:\windows\system32\bash.exe: ABCD is printed out as expected.
- c:\windows\system32\bash.exe in byobu: Byobu tabs are switched on alt-left and alt-right. (Only a single session is running so alt-up and alt-down just error out as expected.)  No additional characters are printed out, as expected.
- Windows Powershell terminal (run->powershell): Nothing is printed out. (Expected? I don't know.) 
- Terminal App powershell: ☻♠♦ is printed out.
- Terminal App ubuntu: A◘B☻C♠D♦  is printed out.
- Terminal App ubuntu in byobu: Byobu tabs are are switched as expected, BUT when alt is released one of ◘☻♠♦ is printed out depending on which arrow key was pressed last.

**Comment by rideron89** [comment]
I'm having the same issue. Happens in both `fish` and `bash`.

I am also on Terminal version 0.5.2762.0. Windows 10 version 18362.388 (1903).

I use alt-left and alt-right to navigate through words on a command.

Terminal version: 0.5.2762.0
Windows 10 version 18362.388 (1903)

**Comment by DHowett-MSFT** [comment]
Confirmed! Possible regression from #2836 (/cc @lhecker)?

**Comment by lhecker** [comment]
@DHowett-MSFT This issue is caused by the use of `ToUnicodeEx()`, which has the following warning...
> As ToUnicodeEx translates the virtual-key code, it also changes the state of the kernel-mode keyboard buffer. This state-change affects dead keys, ligatures, alt+numpad key entry, and so on. It might also cause undesired side-effects if used in conjunction with TranslateMessage (which also changes the state of the kernel-mode keyboard buffer).

I'll open a PR.

@paulwhiting I was not able to exactly replicate your observed behavior. Is there a way to switch between "keypad mode" on/off? I'm "Press[ing] alt-up, alt-down, alt-right, alt-left" (in that order) and I'm not really certain why I'm getting these different results:
* C:\Windows\System32\bash.exe: Alt+Up/Down causes a beep (or "bing") and Alt+Left/Right jumps between words
* Terminal App powershell: ◘☻♠♦ is printed out.
* Terminal App ubuntu: ♦◘☻♠ is printed out.

**Comment by paulwhiting** [comment]
I believe num lock should do what you want?  My keyboard doesn't have a numeric keypad, just standalone arrow keys.

**Comment by david50407** [comment]
In my case, the extra keystroke will happens when I "release the Alt key" after pressing Alt+Left/Right/Up/Down. 
If I doesn't release Alt key, the control key `\cA` `\cB` `\cC` `\cD` won't come out.

**Comment by sivaramn** [comment]
can confirm, I too face this. Within tmux, if i switch panes using Alt+direction keys, i get funny chars on the command line

**Comment by daveshih01** [comment]
Hi folks, sorry for stating the obvious.  Please review/approve the [PR](https://github.com/microsoft/terminal/pull/3117) so this can be addressed.  Thanks!

**Comment by daveshih01** [comment]
Thanks, everyone!
