### ISSUE TITLE
Enforce a minimum window size when resizing

### ISSUE THREAD

**Issue by nishp77** [microsoft/terminal#3102]
# Set the window size to be of minimum fixed size. I mean is that, allow the user to resize the whole window to a limit.

It would solve the issue on multiple tabs not being shown plus there's a bug when we completely resize to very small window then resize back to normal the path is not shown.  

# Proposed technical implementation details (optional)

We could come up within minimum window size that every user is allowed to resize, this could be done by comparing using the user's screen resolution, to be not biased

**Comment by DHowett-MSFT** [comment]
Yep, this is solid. Thanks!

**Comment by DHowett-MSFT** [comment]
So good an idea is this that I'm tagging it for v1.0.

**Comment by nishp77** [comment]
Thank you Sir

**Comment by Lee-Seong-Ju** [comment]
hello, i wonder this issue. 
i want this problem to solve so i found serveral document.(To find out where the documents and sources are related to this part)
but i cant find ,,,,,ㅠㅠㅠ 
sorry where i find "this issue related source and docs?"

**Comment by DHowett-MSFT** [comment]
It looks like we actually shipped this with @mcpiroman's grid resize PR. Filed #4349 to enable it by default.
