### ISSUE TITLE
Starting the Windows IoT Core ADK Add-ons IoTPShell script causes the resulting powershell windows outside of terminal

### ISSUE THREAD

**Issue by TGoodhew** [microsoft/terminal#3103]
# Environment
Microsoft Windows [Version 10.0.18362.388]
Windows Terminal (Preview) Version: 0.5.2762.0
https://github.com/ms-iot/iot-adk-addonkit/

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1. Clone IoT Core ADK Add-ons to local machine
2. Create IOT ADK entry in settings:
    {
      "guid": "{255BF760-7EE8-4346-B260-494BBBE234A6}",
      "name": "IOT ADK",
      "commandline": "C:\\Users\\Tony\\source\\repos\\iot-adk-addonkit\\IoTCorePShell.cmd",
      "hidden": false
    },
3. Select "IOT ADK" from new window drop down
4. Click yes on elevation prompt

# Expected behavior
IoTPShell script/window opens as part of Terminal

# Actual behavior
IoTPShell script/window opens a new PShell window on the desktop

**Comment by Biswa96** [comment]
Try to copy the whole command from `IoTCorePShell.cmd` file and paste it in the `commandline` entry in the `settings.json` file.

**Comment by TGoodhew** [comment]
The same result, the elevated PShell ends up outside of the terminal.

**Comment by DHowett-MSFT** [comment]
To, it looks like `IoTCorePShell.cmd` is launching a separate elevated powershell instance. If you run Terminal elevated, it won't have to do that.

This is a combination of /dup #1032 and #492. 492 because if WT were the "default terminal", it wouldn't appear as a separate powershell window.
