### ISSUE TITLE
Terminal update stuck at 50%

### ISSUE THREAD

**Issue by chriskuech** [microsoft/terminal#3105]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version
Version: 0.5.2762.0
```

Also observed on my other Windows system

# Steps to reproduce

Triggered by an automatic update of the application.

# Expected behavior

The application updates normally

# Actual behavior

The application is stuck updating at about 50%:

![image](https://user-images.githubusercontent.com/3680671/66335197-54db5980-e8ef-11e9-9a65-7cbe67e0a53c.png)

**Comment by ad-on-is** [comment]
Happens to me too. But it's just the progress bar that's stuck. The app itself actually gets updated if you look at the "about" dialog.

**Comment by chriskuech** [comment]
Yes.  I reinstalled it on one of my computers and the issue reoccurred, so its not a problem with a specific version.  I also confirmed that both computers have the same version, so it doesn't seem to be preventing updates.  Still, I have not observed the issue with any other UWP apps.

**Comment by ffes** [comment]
I think this a bug in Windows Explorer. I see this as well, but not just for Terminal but a lot of (all?) apps that get updates and are pinned to Start. Restarting the Windows session, for instance logoff and logon again, fixes the glitch.

**Comment by DHowett-MSFT** [comment]
Unfortunately, this does look like a non-terminal problem. Would you mind filing feedback (in the feedback hub) on the Windows Application Platform next time this happens?
