### ISSUE TITLE
The program crash when opening a new profile other than default profile if the fontSize is smaller than or equal to 10

### ISSUE THREAD

**Issue by seanywang0408** [microsoft/terminal#3113]
# Environment

```none
Windows build number: 10.0.18362.388
Windows Terminal version (if applicable):0.5.2762.0
```

# Steps to reproduce

If setting the ``fontSize`` smaller than or equal to 10 in any object in array ``profiles`` in profiles.json, when opening a new profile window other than the default profile (specifized by ``defaultProfile``), the program would crash and be terminated.
# Expected behavior
open a new profile window

# Actual behavior
the program crash and is terminated.

**Comment by seanywang0408** [comment]
> Hi there!
> 
> Can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png) ![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

Feedback sent :)

**Comment by DHowett-MSFT** [comment]
Thanks! It would be really helpful if you could use the "Share my feedback" button and send us a copy of the link!

**Comment by seanywang0408** [comment]
> Thanks! It would be really helpful if you could use the "Share my feedback" button and send us a copy of the link!

Sorry that I forgot about the link, it's my first time to use the feedback hub. Did you mean this link? https://aka.ms/AA68u5u

**Comment by DHowett-MSFT** [comment]
This looks like it might be the same as /dup #2277; I can't get any good feedback info from your feedback link (not your fault!) but the system thinks they may be related.

**Comment by seanywang0408** [comment]
Thanks for your reply! hope that this bug would be fixed soon. btw this product is amazing! (except for some bugs :)
