### ISSUE TITLE
Double-clicking the title bar should resize the window

### ISSUE THREAD

**Issue by Baljak** [microsoft/terminal#3114]
# Description of the new feature/enhancement

Like any desktop application, double-clicking the title bar should either maximize or minimize the window.

**Comment by DHowett-MSFT** [comment]
/dup #2513, fixed in v0.5.2761.0. We made absolutely sure it does this.

**Comment by Baljak** [comment]
Sorry, I didn't found the similar issue. Thanks for your fast answer anyway!
