### ISSUE TITLE
Icons from EXE/DLL as Custom Profile Icon Source

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [microsoft/terminal#3119]
# Description of the new feature/enhancement
I was experimenting with adding the Python 3.7.3 shell to Windows Terminal and was trying to figure out a way to add its icon with extracting it from python.exe. Unless there is some way I am unaware of to use an icon embedded in an EXE or DLL as a profile's icon, this appears to be a feature that is missing. I would expect to be able to use the EXE or DLL's path as part of the profile's icon path, with an integer specifying the index after a comma, similar how [autorun.inf files](https://docs.microsoft.com/en-us/windows/win32/shell/autorun-cmds#icon) specify an icon to use.

Is this already possible to do? If not, is this something that should be added?

**Comment by DHowett-MSFT** [comment]
/dup #1504. Thanks for filing! It's definitely something we'd like to do.
