### ISSUE TITLE
Allow to start from program like Run (Win+R, ShellExecuteEx)

### ISSUE THREAD

**Issue by stax76** [microsoft/terminal#3124]
Hello,

if I press Win+R and enter WindowsTerminal then Windows Terminal should start. Typically, I start PowerShell from somewhere else and not from the start menu, almost always I start it from Windows File Explorer with my shell extension Open with++, that starts apps with ShellExecuteEx.

![Open with++](https://raw.githubusercontent.com/stax76/OpenWithPlusPlus/master/Main.png)

**Comment by DHowett-MSFT** [comment]
Try using `wt` as the command. It works!

If you want more flexible functionality, you'll have to wait for #607.
