### ISSUE TITLE
running wt should use the current working directory

### ISSUE THREAD

**Issue by stax76** [microsoft/terminal#3125]
When you start cmd or powershell with ShellExecuteEx or CreateProcess then you can define a working directory, cmd or powershell will start with that working directory but not wt. Is this unsupported or is there a setting?

SHELLEXECUTEINFO shExecInf

shExecInfo.cbSize = sizeof(SHELLEXECUTEINFO);
shExecInfo.fMask = NULL;
shExecInfo.hwnd = hwnd;
shExecInfo.lpVerb = verb.c_str();
shExecInfo.lpFile = path.c_str();
shExecInfo.lpParameters = args.c_str();
**shExecInfo.lpDirectory = DirectoryExist(szDir) ? szDir : NULL;**
shExecInfo.nShow = Items[i]->HideWindow ? SW_HIDE : SW_NORMAL;
shExecInfo.hInstApp = NULL;

**Comment by DHowett-MSFT** [comment]
/dup #878 

If you set `"startingDirectory": null` in your profiles, they'll launch in the current working directory. Be careful, though: they'll also launch in `System32` when you start WT from the start menu.

We're working on that one.

For anything else, you'll want #607 (which we hope to use to allow you to specify a working directory.)

**Comment by stax76** [comment]
I really appreciate the fast support. I don't use the start menu for that anyway so "startingDirectory": null will be fine for me. Thanks.

**Comment by DHowett-MSFT** [comment]
Awesome! Happy to help. :smile:
