### ISSUE TITLE
When the mouse is selected, it cannot be duplicated.

### ISSUE THREAD

**Issue by IIvguan** [microsoft/terminal#3127]
![D4ERW2QZ V@U4VS81XMSLH3](https://user-images.githubusercontent.com/26371169/66444301-4e76ea00-ea75-11e9-89f9-957e5f130f4f.png)

In this case，when I press Ctrl+C，I can not copy the selected words。

![5$_RT7$(GWTY8B(7M~JL0B1](https://user-images.githubusercontent.com/26371169/66444419-cba25f00-ea75-11e9-86f1-cd05bf63fcfd.png)

**Comment by carlos-zamora** [comment]
I'm a little confused by the issue. Please update your post to be in accordance with the template below:

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce



# Expected behavior



# Actual behavior

**Comment by DHowett-MSFT** [comment]
I think it's a report that <kbd>Ctrl+C</kbd> doesn't copy text.

**Comment by IIvguan** [comment]
> 我认为这是一份Ctrl+C不复制文字的报告。

Yes,That's what I mean

**Comment by IIvguan** [comment]
I know that the copy shortcut has become Ctrl+Shift+C, and I think it is unwise to modify the copy default button.

**Comment by DHowett-MSFT** [comment]
This is a /dupe of #3058
