### ISSUE TITLE
CMD and PowerShell aren't being transparent like gitBash or Azure cloud. They have no opacity

### ISSUE THREAD

**Issue by Prottoy2938** [microsoft/terminal#3130]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

![Screenshot (7)](https://user-images.githubusercontent.com/51432728/66457204-a1f73100-ea91-11e9-81e1-f25768f8aaa5.png)
![Screenshot (5)](https://user-images.githubusercontent.com/51432728/66457209-a4f22180-ea91-11e9-9e37-df116a8d7077.png)

**Comment by DHowett-MSFT** [comment]
turn on `useAcrylic` and set the `acrylicOpacity`. @bitcrazed can point you in the right direction.

Closing because this isn’t a bug or a feature request.

**Comment by bitcrazed** [comment]
Some background here: We agreed with the WinUI team to disable Acrylic by default in Cmd and PowerShell because these shells have never had transparency enabled by default.

However, you can enable Acrylic if you wish, and adjust the level of opacity via your profiles' settings.

**Comment by ratatoeey** [comment]
in title, it should be `translucent` as its referring to those apps being used with windows terminal. Which doesn't support transparency at all.

title is misleading.

----

regards ratatoeey

**Comment by DHowett-MSFT** [comment]
It’s just a feature you can turn on. It’s in the documentation.

**Comment by bitcrazed** [comment]
@ratatoeey I've adjusted the title of the issue a little, though Terminal DOES support transparency, albeit blurred transparency. We are tracking work to add new forms of transparency and/or blur in future releases.
