### ISSUE TITLE
Profiles file contains invalid json when using comments

### ISSUE THREAD

**Issue by davidpendraykalibrate** [microsoft/terminal#3131]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

1. Press Control + , to open settings in editor

# Expected behavior

Comments are encoded in json in a valid way like:
```
{
  "//1": "To view the default settings, hold 'alt' while clicking on the 'Settings' button.",
  "//2": "For documentation on these settings, see: https://aka.ms/terminal-documentation"
}
```

# Actual behavior

VS Code shows the comment lines with red squiggles under lines like this:
![image](https://user-images.githubusercontent.com/35926989/66463374-d90b1980-ea74-11e9-8718-b012658e2de2.png)

This is not just a vscode issue though: the file also doesn't validate in online json validators:
https://jsonformatter.org/16a575

**Comment by daviox** [comment]
Comments are not officially supported in JSON, that's why the validator is giving you an error while parsing the file.

**Comment by DHowett-MSFT** [comment]
Hey, sorry about that. Our "JSON" file is actually _JSONC_. Almost every day I wish we hadn't chosen a JSON derivative. :smile:
