### ISSUE TITLE
Double usage of Strg + W

### ISSUE THREAD

**Issue by dwittenberg** [microsoft/terminal#3134]
I using ssh to an Linux machine. To edit text-files i use the editor "nano".
This editor uses his own shortcuts, like STRG + X to close document.

To search in a document, the shortcut ist STRG + W.  When I want to use this, it close the active tab instead of use the search.
I know it's wanted the terminal to have its own shortcuts. That also makes working easier. 

It would be great to first check whether the running program inside the window evaluates the shortcut before it is interpreted as a terminal shortcut.

**Comment by DHowett-MSFT** [comment]
We already changed the default binding for closeTab, but if you are using a settings file from 0.2 you will need to change it yourself. This was mentioned in the release notes for 0.3 or 0.4.
Thanks!
