### ISSUE TITLE
Insert Mode? Mark mode

### ISSUE THREAD

**Issue by unuunc** [microsoft/terminal#3135]
How about having some kind of insert mode , such that screen can be abstracted as text and we can select some text from anywhere?

So , say I am doing git pull , it failed throwing error that "error: Your local changes to the following files would be overwritten by merge:"

Now I want to get the name of that file I have to use mouse to go up and copy and paste the file name , instead if I have some kind of insert mode , the terminal will behave as text and I can move my cursor up , select and copy relevant line, press some kind of escape sequence and paste the copied text in next command. 

This is Quick Edit mode / Mark mode in command line

**Comment by carlos-zamora** [comment]
\dup of #715. Spec is in PR here #2840. Feel free to comment on the design 😄

**Comment by carlos-zamora** [comment]
Aargh. I have trouble using the bot. Sorry!
/dup of #715

**Comment by kongdd** [comment]
call for insert mode too
