### ISSUE TITLE
Window Border expands when showTabsInTitlebar is enabled

### ISSUE THREAD

**Issue by RRitts** [microsoft/terminal#3136]
I originally opened #2333 which was supposed to be resolved by #2150 but I am still seeing the issue in 0.5

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0


```

# Steps to reproduce
Set showTabsInTitlebar to true.

# Expected behavior

![working](https://devblogs.microsoft.com/commandline/wp-content/uploads/sites/33/2019/07/title-bar-v03.png)

# Actual behavior
![true](https://i.imgur.com/zU6WXCR.png)

When showTabsInTitlebar is false

![false](https://i.imgur.com/Crck80B.png)

**Comment by DHowett-MSFT** [comment]
Thanks for reopening! Now that the DPI thing is fixed, I've got a hunch.

When you drag/drop things (anywhere!), does it seem like it takes longer to trigger or is less sensitive?

**Comment by RRitts** [comment]
As a matter of fact, yes. 

We put a GPO in place years ago to cut down on things "missing" from our file server when a user would inadvertently drag and drop folders. It modifies the DragHeight and DragWidth values in HKLM\Control Panel\Desktop

**Comment by DHowett-MSFT** [comment]
YES! You are now an excellent case study on why nobody should use the `SM_CXDRAG` system metric to measure _window borders_. We've been told not to, but we ended up doing it anyway (good question as to how: we don't know!) -- and I tried to pass that guidance along to another team. Thanks!

**Comment by RRitts** [comment]
Behold!

![BAM](https://i.imgur.com/88DYqyO.png)

This is this DragHeight and DragWidth set to 4. The GPO was setting them to 45.

**Comment by zadjii-msft** [comment]
(We think that this is going to be closely related to a bucket of things, #3136 #1859 #3064 #1307)
