### ISSUE TITLE
Terminal output paused when RDP session disconnected

### ISSUE THREAD

**Issue by dtrailin** [microsoft/terminal#3137]
# Environment 

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): Microsoft Windows NT 10.0.18362.0   

Any other software?  msbuild
```

# Steps to reproduce

1. Log into a machine over RDP 
2. Open a terminal cmd session 
3. Start a build using msbuild.exe
4. Close RDP session

# Expected behavior

It's expected that the build will continue in the background even after the RDP session is disconnected. 

# Actual behavior
Terminal output is blocked, causing the build to be blocked as well. This means that the build will not proceed until reconnecting the RDP session or logging into the host machine.

**Comment by Biswa96** [comment]
If only Command Prompt is used, does it behave same?

**Comment by dtrailin** [comment]
No, this behavior is only in the new terminal. It seems to have some weird interaction with RDP.

**Comment by DHowett-MSFT** [comment]
Just to confirm: Terminal continues running, it just doesn't complete building until you reconnect?

**Comment by dtrailin** [comment]
Yes the terminal stays open, but it seems like stdout is blocked during this time.

**Comment by zadjii-msft** [comment]
Hey this issue is like, 3 years old. You still seeing this/? There's a pile of other renderer deadlocks we're tracking these days, but this doesn't sound like one of them.
