### ISSUE TITLE
Ability to tile tabs

### ISSUE THREAD

**Issue by adreed-msft** [microsoft/terminal#3139]
# Description of the new feature/enhancement

This one is a "nice to have", but I'd love to be able to stack tabs and tile them side-by-side (ex. a powershell tab on one half, and a WSL tab on the other half). This'd help my efficiency when I need to be testing my work on Windows and Linux at the same time.

# Proposed technical implementation details (optional)

Effectively, I'd like something akin to [Vivaldi's tab tiling](https://help.vivaldi.com/article/tab-tiling/) at a minimum, but control on the tier of say, i3wm would be amazing. I should be able to drag a tab over another, and have them drop into a stack.  I should then be able to (in some context menu) be able to set up the layout of the windows in the stack.

**Comment by DHowett-MSFT** [comment]
I think most of these are covered in #1000, actually, with a little bit of "select multiple things" and "predefined layouts". What do you think about #1000?

**Comment by adreed-msft** [comment]
Looks good to me. I'll close this since the same general idea is already tracked.
