### ISSUE TITLE
Idea: Align Terminal keymappings with VS Code conventions

### ISSUE THREAD

**Issue by aaronsteers** [microsoft/terminal#3140]
# Description of the new feature/enhancement

Would be great if we could align Terminal keybinding settings with the VS Code keybinding conventions (link below).

Currently, the shortcut keys abbreviations do not match and this makes it more difficult to get started with keybindings - requiring users to try to do tons of digging to find the right convention - for example, to know page down is 'pgdn' (Terminal) instead of 'pagedown' (VS Code).

Would be fantastic if we could memorize and use a single convention rather than inventing a new one and trying to remember which convention works in which tool.

# Proposed technical implementation details (optional)

The Terminal shortcut key abbreviations are documented here:
    `(Couldn't find any reference docs. Eventually found examples by holding Ctr while selecting "Settings" in order to get to the defaults.json file.)`

The VS Code shortcut key abbreviations are documented here:
    https://code.visualstudio.com/docs/getstarted/keybindings#_accepted-keys

For example of the problem currently, "Page Up" is "pgup" in Terminal `profiles.json` and "pageup" in VS Code.

**Comment by Pertel** [comment]
Hey, I was having the exact same problem when trying to configure keybindings using page-up and page-down; I couldn't find any documentation with all the valid keys and had to dig around in the source code.

If you'd like, I could update the documentation to list all possible keys and submit a PR.

My suggestion is to grab the keys from [KeyChordSerialization.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/KeyChordSerialization.cpp) 
And include them in the [Profiles.json Documentation](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) file under the keybindings section.

Even if that doesn't create parity with VS Code keybindings, it would be helpful for users creating keybindings.
