### ISSUE TITLE
vim acts crazy in recent builds

### ISSUE THREAD

**Issue by darthpale** [microsoft/terminal#3148]
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version commit: 200e90d1c64cb8ad3f48b808ac695bac5bb6e696 

Any other software?

Visual Studio Community 2019 16.3.3

```

# Steps to reproduce
vim Terminal\src\cascadia\TerminalApp\TerminalPage.cpp
yank and paste second line.

# Expected behavior
pasted line appears text, below scrolls down

# Actual behavior
pasted line appears text scrolls up.
At this point there is no consistency between cursor and location in the file.
Hitting "u" to undo even when at the "Already at the oldest change" point removes the text under the cursor and scrolls everything up. leading  to multiple copies of the vim status line

Confirms this is a problem even when ssh [-ing] to a remote machine and using vim there not the local windows instance as well.

**Last known working commit:   2c8b3243dca0c48dd05ecd7b420a7a03b3e19c93  Wed Sep 25 22:00:06 2019 -0700**

![image](https://user-images.githubusercontent.com/48268993/66604133-8a947280-eb7b-11e9-92ed-a54d73cd9bb1.png)

Screenshot is after simply hitting "u" 6 times.

**Comment by DHowett-MSFT** [comment]
This might be related to #3052, actually. If you revert the change from 5d906d9f3e78a467c1914a1b8b6fde92e7d86090, does it resolve?

**Comment by darthpale** [comment]
Thanks, yes reverting 5d906d9 fixes this issue for me.
