### ISSUE TITLE
Terminal crashes after extended use with multiple tabs with SSH sessions

### ISSUE THREAD

**Issue by mxplusb** [microsoft/terminal#3150]
# Environment

```none
Windows build number: 10.0.18999.0
Windows Terminal version (if applicable): 0.5.2762.0

Any other software? No
```

# Steps to reproduce

Work via multiple SSH sessions.

# Expected behavior

Terminal continues to function normally.

# Actual behavior

Terminal randomly crashes, I haven't found the specific cause. I do have the event data, though.

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-10-11T04:37:45.793053500Z" /> 
  <EventRecordID>753</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>boulder</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WindowsTerminal.exe</Data> 
  <Data>1.0.1910.3002</Data> 
  <Data>5d969447</Data> 
  <Data>TerminalControl.dll</Data> 
  <Data>1.0.1910.3002</Data> 
  <Data>5d96931e</Data> 
  <Data>c0000005</Data> 
  <Data>000000000001a68b</Data> 
  <Data>6a50</Data> 
  <Data>01d57fa8e0a8a2e6</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.5.2762.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.5.2762.0_x64__8wekyb3d8bbwe\TerminalControl.dll</Data> 
  <Data>b28e87f8-8675-4143-9172-92de557b1410</Data> 
  <Data>Microsoft.WindowsTerminal_0.5.2762.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

**Comment by rennex** [comment]
Here too, I've been using Terminal for about a week (1-2 windows open, usually with a few WSL tabs in each), and I see at least one crash a day. My version is also 0.5.2762.0.

I doubt SSH has anything to do with it though. Whatever software runs in WSL doesn't concern the Terminal, it just handles console input and output.

**Comment by foddrick** [comment]
I have experienced this too. A few tabs, ssh inside wsl, cmd, sqlplus (oracle tool). It will just abort when I'm not even actively using it. Also on version 0.5.2762.0.
Is there an option to enable better collection of crash data?

**Comment by DHowett-MSFT** [comment]
This might be a bit better as of v0.6. Would you mind reporting whether you still see sporadic crashes once you've updated?
Thanks!
