### ISSUE TITLE
Windows Terminal & Visual Studio

### ISSUE THREAD

**Issue by Kizmar** [microsoft/terminal#3153]
# Description of the new feature/enhancement
The ability to run a solution in Visual Studio and open multiple projects as Windows Terminal tabs. So if I set up my solution to run two API projects, instead of opening in separate command/Powershell windows, it opens in Windows Terminal Tabs.

# Proposed technical implementation details (optional)
Visual Studio extension? No idea, just thought this would be nice. :)

**Comment by DHowett-MSFT** [comment]
You might really like the [new terminal in the Visual Studio preview](https://devblogs.microsoft.com/visualstudio/say-hello-to-the-new-visual-studio-terminal/)! They're using our terminal code :smile: and contributing it back to us to boot!

**Comment by Kizmar** [comment]
Ohh nice. Too bad that's not in the Options > Preview Features in non-Preview Visual Studio. Thanks!
