### ISSUE TITLE
Dark titlebar in classic CMD is broken in Insider builds

### ISSUE THREAD

**Issue by sylveon** [microsoft/terminal#3156]
# Environment

```none
Windows build number: 10.0.18985.1 (Sorry for being outdated, I haven't been able to update to a more recent Insider build)
Windows Terminal version (if applicable): N/A

Any other software? No
```

# Steps to reproduce

Open cmd.exe compiled from this repo or built in Windows.

# Expected behavior

The titlebar is black, like in the current stable Windows.

# Actual behavior

The titlebar isn't black: 
![image](https://user-images.githubusercontent.com/6440374/66656102-57012900-ec0b-11e9-9f8c-2e241b294569.png)

**Comment by Biswa96** [comment]
Does the tittle bar becomes black when you click on the window?

**Comment by sylveon** [comment]
The window is active in this screenshot

**Comment by DHowett-MSFT** [comment]
Funny enough -- you filed this shortly after I saw an uptick in log entries (in a local dev build) about this API failing. Thanks!

**Comment by sylveon** [comment]
The API used is technically undocumented and got moved to `WCA_USEDARKMODECOLORS` in the also undocumented `SetWindowCompositionAttribute` API, IIRC.

IMO it should be documented, because other apps might also want a dark titlebar, especially if they have a built-in dark theme because the white titlebar becomes an eye sore.

**Comment by DHowett-MSFT** [comment]
Hey! The fix for this went out in Windows in the Insider channel's Fast Ring with build 19013.

**Comment by raddinet** [comment]
> The API used is technically undocumented and got moved to `WCA_USEDARKMODECOLORS` in the also undocumented `SetWindowCompositionAttribute` API, IIRC.

Thank you! Can confirm that [such change](https://github.com/raddinet/raddi/commit/a050e80c79e16a88980a549214d255197fe73225) works.

> IMO it should be documented, because other apps might also want a dark titlebar, especially if they have a built-in dark theme because the white titlebar becomes an eye sore.

Exactly.

**Comment by DHowett-MSFT** [comment]
We don't disagree with you.

**Comment by sylveon** [comment]
Finally got to update my insider build after windows update kept refusing, can confirm it works (third party apps are still broken so they'll have to move to `SetWindowCompositionAttribute`).

The code here also hasn't been updated https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/interactivity/win32/windowtheme.cpp#L47
