### ISSUE TITLE
can we bing custom keyboard shortcuts?

### ISSUE THREAD

**Issue by videni** [microsoft/terminal#3157]
```
ctrl+c  for copy
ctrl+v for past
```
why we can't use `ctrl+c` and `ctrl+v` in  window console?  this confuses me for years. the copy and paste are very painful comparing with Mac and Linux,  which is the primary reason why I give up development in Windows.

also , I'd like to add some global keyboard shortcuts that works for console and for the whole Windows system.  can we do this?
```
ctrl+a for jump to line head
ctrl+e for jump to line end
```

**Comment by flickerfly** [comment]
Is this a duplicate to #3058 ?

**Comment by DHowett-MSFT** [comment]
You can set these key bindings yourself in your settings file. Thanks!

**Comment by DHowett-MSFT** [comment]
(except for ctrl+a/e across all of Windows. The terminal team isn't staffed to go add emacs keybindings to all edit controls across the entire OS. sorry.)
