### ISSUE TITLE
UIA Word Navigation

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#3161]
# Description of the new feature/enhancement

UIATextRanges don't know how to move by "word" because a terminal doesn't really know what a "word" is. This is a place to discuss what that should look like.

# Proposed technical implementation details (optional)
For Windows Terminal, the user defined "wordDelimiters" and the space character could be used for this.

For ConHost, the user can't define a "wordDelimiter". So, should we just use the space character?

**Comment by carlos-zamora** [comment]
Related to #2160. Might even be the same??

**Comment by ZoeyR** [comment]
I don't think its the same as #2160 since the text navigation helpers explicitly decide that requests to move by word should just do line navigation instead.

**Comment by zadjii-msft** [comment]
As an aisde, you technically _can_ set `wordDelimiters` for conhost. We'll read that setting from the registry, but never exposed a UI for it ¯\\\_(ツ)_/¯

https://github.com/microsoft/terminal/blob/f8f079882606247dcba6379dca20064bcffe65ef/doc/ConsoleHostSettings.md#L27

https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/host/registry.cpp#L78-L116

**Comment by carlos-zamora** [comment]
oooh. If that's the case, then we can make the UIA Provider read what the `wordDelimiters` are. Then, just have it read them differently according to the project. We already have a set of UIA Providers for ConHost and another for Terminal (both with the same base class).

**Comment by ZoeyR** [comment]
Why not use the definition of a word boundary as defined by unicode? http://www.unicode.org/reports/tr29/#Word_Boundaries

**Comment by DHowett-MSFT** [comment]
If somebody has the time to implement that _as an alternative to user-requested word delimiters_ (fwiw: users want all sorts of things, and they were already fairly cross with us for shipping a delimiter set that included `/` and `\` by default)), I'd entertain it :smile:

I imagine the same would extend to "move by word"... but I'm not sure
