### ISSUE TITLE
somebody needs to add ctrl&shift+ins to the default settings

### ISSUE THREAD

**Issue by hybcloud** [microsoft/terminal#3162]
# Description of the new feature/enhancement

when typing "shift + insert",wsl should insert the content in clipboard into command line

# Proposed technical implementation details (optional)

**Comment by carlos-zamora** [comment]
You should be able to add it as a keybinding for "paste" as "shift+ins", I believe.

**Comment by PromoFaux** [comment]
@carlos-zamora thanks for the pointer! That said, it appears the correct value is `shift+insert` for it to work :)

**Comment by vineethrp** [comment]
I tried adding the key bindings for shift+insert, but is not working.
This is my settings:

`"keybindings" : [
		{
			"command": "paste",
			"keys": 
			[
				"shift+insert"
					
			]
		}
	],`

Now when I try to paste using "Shift+Insert", I get " 2~"

Am I missing something in the settings?
