### ISSUE TITLE
Lost history

### ISSUE THREAD

**Issue by KanDisheng** [microsoft/terminal#3163]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

Just keep typing.

# Expected behavior

Keep the history.

# Actual behavior

Lost the history. See the GIF file:

![terminal](https://user-images.githubusercontent.com/1520283/66694992-812b1780-eced-11e9-891b-da2042021203.gif)

**Comment by DHowett-MSFT** [comment]
This is actually a duplicate of PowerShell/PSReadline#724.
