### ISSUE TITLE
cmd selected state translucent display is unfriendly

### ISSUE THREAD

**Issue by godcong** [microsoft/terminal#3164]
In the process of using terminal cmd.
The background color setting of `cmd` is very unfriendly.
When cmd is selected, it will be translucent display.
When the background color behind cmd is a white-like background.
It will become very glaring, And it is difficult to see the white text.
![image](https://user-images.githubusercontent.com/2727298/66697110-30271d80-ed05-11e9-8e3c-a5df4ff7e33f.png)

The color in the non-selected state is more comfortable.
![image](https://user-images.githubusercontent.com/2727298/66697125-4df48280-ed05-11e9-9e9a-17e205ed0518.png)

Is it possible to change the selected and unselected states?

**Comment by DHowett-MSFT** [comment]
Good news! We actually disabled translucency on cmd by default.

**Comment by godcong** [comment]
This is really good news.
