### ISSUE TITLE
Extraordinarily sluggish response to input over busy ssh session

### ISSUE THREAD

**Issue by hwinkler** [microsoft/terminal#3169]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

`Microsoft Windows [Version 10.0.18999.1]`

Windows Terminal version (if applicable):
`0.5.2762.0`

Any other software? 
`ssh`, `cmd`
```

# Steps to reproduce

1. ssh to an Ubuntu 18.04 host; log in to `bash` session.
2. start `byobu`
2. run command
```$ while :; do echo 'All work and no play makes Jack a dull boy.';  done```
3. press `F2` key to create new `byobu` window
4. press `F3` and `F4` to toggle screens back and forth several times

# Expected behavior
Steps  4 and 5 respond quickly.

# Actual behavior
Steps 4 and 5 can take very long times to process the keystroke and respond.
Sometimes 10, 20, 30 seconds, sometimes immediate.

Compare to doing the same process from `cmd.exe` (in its native window), which responds immediately as expected.

Ctrl-C also is sluggish. 

[edited to correct EB and AB and add Ctrl-C comment]

**Comment by hwinkler** [comment]
Also: Try typing `Ctrl+C`... same sluggish behavior.

**Comment by ZimGil** [comment]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): 0.8.10261.0
```

I feel the same sluggish response to ssh `Connection to <IP> closed by remote host` that will also not be solved by Ctrl-C
Maybe related...?

**Comment by hwinkler** [comment]
Just a note for context:

The purpose of running the shell script infinite loop is to force the remote session to spew a torrent of text. Consuming the torrent seems to block Terminal from prompt handling of control sequences. There are probably simpler ways to repro. But the repro I described still clearly demonstrates the behavior on Terminal  0.8.10091.0.

Also, I omitted in the original description to say I am running a `wsl` Ubuntu session locally, and from that I am ssh-ing to a remote host to run `byobu` and the infinite loop script.

**Comment by zadjii-msft** [comment]
@hwinkler Are you using `ssh.exe` that comes with Windows, or the `ssh` from your linux distro?

Are you possibly using `"experimental.retroTerminalEffect": true` in your `profiles.json`? 

Does this repro _without_ `ssh`? or does it require `ssh` to be in the middle? I'm trying this locally w/o `ssh` in the middle and I can't seem to get it to repro at all. 

Maybe this just got resolved on it's own in the last few releases?
