### ISSUE TITLE
CONSOLE_INFORMATION has an ODR violation contributing to test instability

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#3170]
> It turns out that there's an ODR violation! `CONSOLE_INFORMATION` changes size based on whether `UNIT_TESTING` is defined (VtIo got a new `UNIT_TESTING`-only member in #2525), and that gets rolled up into Host.unittest.lib. InteractivityBase.lib has a compile-time dependency on the layout of `CONSOLE_INFORMATION`, but InteractivityBase isn't built with a `UNIT_TESTING` variant. CI gets _constructed_ in InteractivityBase, and as the linker can resolve the ODR violation in whatever way it sees fit it ends up choosing the shorter layout when packing in file-level statics.

> This bug only exists in our tests. The fix in 83fcb6c moves the trampled global out of the way... but just fixes the symptom. :|

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/pull/3107#issuecomment-541369066_

**Comment by zadjii-msft** [comment]
With the revert of #2525 in #3488, I don't _think_ this is relevant anymore. There's no longer a debug-only member of `CONSOLE_INFORMATION`, so we can close this one out, yea? @DHowett

**Comment by DHowett** [comment]
I believe so! Thanks.
