### ISSUE TITLE
Not able to set the custom folder startingDirectory to be opened by default

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#3175]
I am not able to set the custom folder startingDirectory to be opened by default.
Tried the following combinations:

            "startingDirectory" : "\\D:$\\custom\\folder",
            "startingDirectory" : "//d$/custom/folder",
            "startingDirectory" : "//d$//custom//folder",
            "startingDirectory" : "//D:$//custom//folder",
            "startingDirectory" : \\d$\\custom\\folder",

**Comment by DHowett-MSFT** [comment]
Why did you think there should be a $ in it? Or that it should start with a slash?

Try `D:\\custom\\folder`.
