### ISSUE TITLE
We needs **shellArgs! & transparent cursor!**

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [microsoft/terminal#3178]
# Description of the new feature/enhancement
This is a best terminal for windows and built in shell chooser but why it can't set **shellArgs**.
And secondary is **transparent cursor** is a bundle feature with **filledBox** cursorShape but not included.

That's very much better!

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
I'm sorry, I can't tell what you're requesting. Do you want a cursor you can see though? Why can't you set the commandline to contain the "shellArgs" you want?

**Comment by Cyl3el2Cleal2** [comment]
> I'm sorry, I can't tell what you're requesting. Do you want a cursor you can see though? Why can't you set the commandline to contain the "shellArgs" you want?

Yes, I want a cursor I can see though.
I don't know about shellArgs from [user doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#settings-layering) before.
I will try to set shellArgs to commandline later.
Thank you.

**Comment by Cyl3el2Cleal2** [comment]
My bad. I saw the "cammand to execute on startup".
Wow amazing keyword.
That's very much better!

![image](https://user-images.githubusercontent.com/38637268/66818691-e7bb6a00-ef67-11e9-92e1-e989fe1afe52.png)

**Comment by K1ngjulien** [comment]
@DHowett-MSFT this can be closed, i think
