### ISSUE TITLE
select + enter does not copy selected text into clipboard just as old Terminal

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#3179]
# Environment

Affected: any supported Windows 10, currently 18362.10022
Windows Terminal preview 0.5.2762

Any other software?
nothing special

# Steps to reproduce
Open Windows Terminal 
type commands or text
select the stuff with your mouse
press enter key

# Expected behavior

This should copy the selection into clipboard just as usual with legacy cmd / powershell terminal

# Actual behavior
pressing enter key will issue the command as if there was no selection in progress

**Comment by DHowett-MSFT** [comment]
More info in /dup #2464; we should consider adding this to our default settings.

**Comment by ncoghlan** [comment]
@DHowett-MSFT Should the bot have closed this one? The referenced ticket seems to be about enabling the config setting, this ticket seems to be about having it in the defaults for new installations.

**Comment by Karl-WE** [comment]
hi @ncoghlan I think I have read similar what you wrote, I've uninstalled terminal app and installed it again.
for the non "preview" app I don't see this is working select + enter will not copy to clipboard but ignoring selection and issue the command (as enter would do usually when not selected). So basically, it seems to be no default for new installation or uninstall / install does not remove configs. But given the tabs it looks like this.
