### ISSUE TITLE
Terminal processing regression from v0.5.2762.0

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#3180]
# Environment
master at b9233c03 (I haven't sought for faulting commit though)
Windows version: `10.0.18362.388`

# Steps to reproduce

1. open wsl
2. open tmux/mc/htop/similar program

# Expected behavior
Taken from v0.5.2762.0 release (commit 7faf3342)

![term_ok](https://user-images.githubusercontent.com/38111589/66715208-b81e2d80-edc0-11e9-95c0-ecc450871f66.gif)

# Actual behavior

![term_glitchy](https://user-images.githubusercontent.com/38111589/66715577-32e94780-edc5-11e9-9231-6d7d81e8d6e7.gif)

**Comment by skyline75489** [comment]
Looks like duplicate of #3052

**Comment by mcpiroman** [comment]
Ah yeah, what deceived me is the issue is older than the (working) release.
