### ISSUE TITLE
Consider adding support for `win` in key bindings?

### ISSUE THREAD

**Issue by david50407** [microsoft/terminal#3184]
# Description of the new feature/enhancement

Support more keystroke on keybinding like: meta (win) key.
In most UNIX terminal, Ctrl, Alt and Shift are captured by the program, if we use these modifiers to bind keybinding, we cannot send these keys into the program.

Like most terminal emulators in macOS, they most use command (cmd) key to bind shortcuts to avoid prevent occupying sending these modifiers into terminal, IMO, Terminal should support capturing Win (Meta) as modifier and allowing to bind shortcuts.

# Proposed technical implementation details (optional)

It seems that `Windows::System::VirtualKeyModifiers` supports `Win` key, so is this feature possible?

**Comment by DHowett-MSFT** [comment]
The Windows key is owned by the OS Shell, unfortunately, so we won't have terribly much luck in re-binding it inside Terminal. Our current solution is "bind Ctrl+Shift", because the standard set of control sequences doesn't contain serializations for ctrl+shift+(letter).

**Comment by szeiger** [comment]
For the record, ConEmu supports this. Switching between tabs with Win+number combinations works just fine.

**Comment by evertheylen** [comment]
I strongly support a feature like this. Visual Studio Code allows this too, and I use it extensively.

> The Windows key is owned by the OS Shell

If the OS catches a keystroke before Terminal can, no harm done right?

**Comment by flery** [comment]
Would love to be able to reimplement i3 keybindings (would require win modifier as well).

**Comment by wulfland** [comment]
I think this is a very important topic to allow people to customize there shortcuts the way they are used to from Cmder or ITerm. And the documentation is not clear that windows is not an option so far. I had to search hard for it.

**Comment by zadjii-msft** [comment]
Note to self, re the changes to `TermControl::_TrySendKeyEvent` in #9163 - when this feature lands, we can get rid of creating a CoreWindow and querying the modifiers. We'll already _have_ the <kbd>win</kbd> modifier
