### ISSUE TITLE
Login Azure Clodu Shell problem in the configuration after first login

### ISSUE THREAD

**Issue by joejony** [microsoft/terminal#3190]
After doing first login and selecting the subscription the shell ask if we can keep this subscription as default and fail during "yes/no" selection. Pressing Y or N does not work.

**Comment by DHowett-MSFT** [comment]
@joejony thanks for the report. Would you mind filling out the bug template? I'd love to know your version numbers. Also, what is your system keyboard layout?

```
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?

# Steps to reproduce

A description of how to trigger this bug.

# Expected behavior

A description of what you're expecting, possibly containing screenshots or reference material.

# Actual behavior

What's actually happening?

```

**Comment by joejony** [comment]
Windows Terminal (Preview) - Version: 0.5.2762.0
Keyboard: English United States International
I opened the Azure Cloud Shell for the first time. Went to the website and added the code. Entered my username.
Then I got back to the Cloud Shell to select the environment (subscription). And after that I was trying to answer yes or no for the question about making it default. And the system halted.

**Comment by DHowett-MSFT** [comment]
/feedback

Thanks for the confirmation! Would you mind filing a feedback item so we can figure out what happened to Terminal?
