### ISSUE TITLE
Opening a tab for a shell that is not installed anymore does not notify user that something went wrong

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#3192]
# Environment

```none
Windows build number: 18363.418
Windows Terminal version: 0.5.2762.0
```

If a profile is defined with an invalid commandline, or if the shell specified has been uninstalled by the user, trying to open a tab with that profile will not show any warning about the failure to launch the shell process.

If the profile is defined with "closeOnExit":false, the tab will wait forever for the shell to get connected instead of showing an error message. If the profile is defined with "closeOnExit":true, the tab will immediately close with no explanation.

# Steps to reproduce
Create a profile with a non-existing shell such as the following:
 {
      // A non-existing shell
      "guid": "{0225F6B6-EC1C-4746-8384-A83DB214D13A}",
      "closeOnExit": false,
      "name": "dummy",
      "commandline": "dummyshell.exe",
      "hidden": false
    },

# Expected behavior
If the commandline cannot be launched, an error should notify the user that the process couldn't be created, so they know they have to look at the command line more closely.

# Actual behavior
Instead of some error message, Windows Terminal keeps the tab open and cursor waiting with no hint that something went wrong launching the shell, or simply silently closes the tab if "closeOnExit":true.

**Comment by DHowett-MSFT** [comment]
Hey @PhMajerus, thanks for the report!
This is actually a dupe of #2563, for which we've got a couple plans.
Cheers!
