### ISSUE TITLE
Cursor misaligned in nano

### ISSUE THREAD

**Issue by zulc22** [microsoft/terminal#3202]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
GNU nano (windows port, installed from chocolatey.)
```

# Steps to reproduce

Run GNU nano.

# Expected behavior

Cursor is aligned with where the text is appearing, follows after a newline, etc. (screenshot of conhost)

![conhost screenshot](https://uploads.kscott.cf/sharex/cmd_9sJyU82r9H.png)

# Actual behavior

Cursor doesn't follow after a newline, and doesn't stay aligned to the insert point.

![windows terminal screenshot](https://uploads.kscott.cf/sharex/WindowsTerminal_lxyQGcg7jw.png)

**Comment by egmontkob** [comment]
Probably the same as #2642 and #3093.

**Comment by PromoFaux** [comment]
Confirmed in the wrong place.  Also one cannot move the cursor about with the arrow keys.

![](https://i.imgur.com/yITq9IS.gif)

**Comment by DHowett-MSFT** [comment]
Honestly, this looks like GOW nano, which has made some eminently questionable decisions regarding how the Windows Console works. The arrow keys don't even work..?

Technically, this is a conpty issue, but I cannot figure out how it ended up so bad.

**Comment by KScottDB** [comment]
the arrow keys work for me in my copy of nano. @PromoFaux may need to give more information on their part about that.

**Comment by PromoFaux** [comment]
When pressing the arrow keys, the cursor does not move around, I just get `[Unknown Command]` at the bottom of the screen.  using nano 2.5.3 installed via Chocolatey, using Terminal 0.6.2951.0

**Comment by jeffrson** [comment]
I found the same issue.
"nano" installed via scoop (scoop.sh), which specifically comes from https://github.com/ScoopInstaller/Main/blob/master/bucket/nano.json or currently  https://files.lhmouse.com/nano-win/nano-win_8303_v4.5-103-gb12aeeac.7z cannot move visible cursor. Although the cursor is moved internally because you would start typing at the new position.

No problem with "external" PowerShell.

OTOH it's rather strange that "nano" from GitForWindows does not show this behaviour - cursor works fine.

**Comment by DHowett** [comment]
I can no longer reproduce this using the linked nano from scoop!

**Comment by PromoFaux** [comment]
Completely forgot about this issue :) But yeah, confirm no longer seeing the issue even with the same binary as before

![image](https://user-images.githubusercontent.com/1998970/114592645-0f85ae00-9c83-11eb-8f19-4216dd05b61e.png)

**Comment by DHowett** [comment]
Thanks! :D
