### ISSUE TITLE
copy text from chrome and paste in vstudio shows funny characters

### ISSUE THREAD

**Issue by gadros** [microsoft/terminal#3205]
# Environment
Microsoft Windows [Version 10.0.17763.557]

other software:
1. Chrome Version 77.0.3865.90 (Official Build) (64-bit)
2. vstudio about (note the Resharper because this is where it happened):
Microsoft Visual Studio Professional 2019
Version 16.2.5
VisualStudio.16.Release/16.2.5+29306.81
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

ASP.NET and Web Tools 2019   16.2.292.25104
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.292.25104
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.292.25104
Azure App Service Tools v3.0.0

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.1.2   Build 191.0.20190603.142841
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Word Highlight With Margin Extension   1.0
[VS2017] Highlight all occurrences of a selected word and display carets on the enhanced vertical scrollbar at the right margin.

# Steps to reproduce
1. in Chrome, in a tab that shows a PR of TFS copy text (see cascadia_paste_copy_from_chrome.png)
2. in vstudio bring up Resharper's GoTo-Symbol window and paste the copied text

# Expected behavior
show normal characters. 
note that this doesn't happen with in
![cascadia_paste_copy_from_chrome](https://user-images.githubusercontent.com/1727294/66808962-0d7b4b80-ef35-11e9-836b-f938dde1f4d3.png)
![cascadia_paste_funny_characters](https://user-images.githubusercontent.com/1727294/66808963-0d7b4b80-ef35-11e9-97ea-e78209564590.png)

 version b84a073464cdda225ccf65214f58b354cbe6a166
# Actual behavior
funny characters are shown (see cascadia_paste_funny_characters.png)

**Comment by DHowett-MSFT** [comment]
_this is the Windows Terminal repository_, we have nothing to do with chrome OR visual studio.

**Comment by DHowett-MSFT** [comment]
This looks like the font confusion issue we've been seeing in the cascadia-code repo. The usual fix is "uninstall all copies of the font and then reboot". It seems like Windows caches some information about the font that changed from version to version, and sometimes it gets it wrong when multiple copies are installed.
