### ISSUE TITLE
No termcap entry for terminal session

### ISSUE THREAD

**Issue by reggie1515** [microsoft/terminal#3208]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.5.2762.0


Any other software?
```

# Steps to reproduce

1. Connect SSH session to application server. use '-l' switch
2. Type in password, accept EULA, and accept session SSH host Key.
3. Enter in 'CRS' at terminal to load custom application.
(On a Putty Terminal Emulator, the custom application would load without issue)

# Expected behavior

Customer Application should load, presenting user with splash screen. From here, user can navigate Linux based application.

# Actual behavior
<--

-bash-4.2$ crs
Can't find termcap entry for this terminal
Can't Run crs

--!>

**Comment by DHowett-MSFT** [comment]
1. Can you describe the remote host? What version is it, and what distribution?
2. Can you share the output of `echo $TERM`?
3. Terminal reports itself as `xterm-256color`, which is standard and should be present on all modern machines.
4. If the `xterm-256color` terminfo isn't available, can you try after setting `TERM=xterm`?
