### ISSUE TITLE
Exiting a PowerShell tab does not trigger the Powershell.Exiting event.

### ISSUE THREAD

**Issue by Borkason** [microsoft/terminal#3210]
# Environment

```none
Windows build number: 10.0.18999.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

1. Open a new PowerShell tab. PowerShell version does not matter.
2. Paste and run the following code in the PowerShell tab:
```powershell
Register-EngineEvent -SourceIdentifier Powershell.Exiting -Action { Set-Content -Value "Hello there." -Path "$env:TEMP\General Kenobi.txt" }
```
4. Close the PowerShell tab by clicking the x button or by the `exit` command. Or close the Terminal window.

![grafik](https://user-images.githubusercontent.com/2971735/66866265-3a614a00-ef99-11e9-9dd1-d33e4fd371cb.png)

# Expected behavior

The PowerShell tab should trigger the Powershell.Exiting event and a file `%temp%\General Kenobi.txt` should be created.

# Actual behavior

The event does not trigger and no file is created.

Note: If you reproduce this in the native PowerShell 5 or 7-preview.3 console (not the Terminal app) you'll find that the event triggers correctly only when using the `exit` command. Clicking the close button also does not trigger the event. Although I also reported that at https://github.com/PowerShell/PowerShell/issues/8000, I believe that with Terminal it's an independent issue.

**Comment by Borkason** [comment]
Perhaps related: https://github.com/PowerShell/PowerShell/issues/8000

**Comment by DHowett-MSFT** [comment]
I just tried to reproduce this, and it _does_ work in Terminal when you `exit`. It doesn't work on tab/window close, but that is almost certainly for the same reason as PowerShell/PowerShell#8000.

Powershell can determine when its console is being closed -- it should receive a `CTRL_CLOSE_EVENT` through its `CtrlEvent` handler. This is true regardless of whether terminal or conhost is in active use.

It looks like this is just an External issue.
