### ISSUE TITLE
Acrylic background does not render in real-time while being maximized or minimized.

### ISSUE THREAD

**Issue by Borkason** [microsoft/terminal#3211]
# Environment

```none
Windows build number: 10.0.18999.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

1. Open Terminal and use the acrylic background.
2. You should put some contrastful windows behind the Terminal window so you can clearly see the display bug in the acrylic section.
3. Move the Terminal window around. You can see that the acrylic background is rendered in real-time and displayed correctly.
4. Resize the Terminal. You can see that the acrylic background is rendered in real-time and displayed correctly.
5. Double-click the task bar or click on the maximize button to maximize the Terminal window to full screen. Then minimize the window again. There is a slight delay until the acrylic background is rendered correctly. Also, the acrylic background is distorted during the maximize animation.

It is less notable to see it in this tiny gif. It's best you reproduce this by yourself on your computer.

![aZ0pSfm6Fr](https://user-images.githubusercontent.com/2971735/66867610-ed32a780-ef9b-11e9-9698-5202dcac8fad.gif)

# Expected behavior

During the maximize animation (step 5) the acrylic windows should render in real-time, as it does when moving (step 3) or resizing (step 4) the Terminal window.

# Actual behavior

The acrylic background freezes, distorts and is only rendered once the maximize/minimize animation is completed.

**Comment by DHowett-MSFT** [comment]
I believe this is, unfortunately, by design. Calculator acts the same way. ☹️
