### ISSUE TITLE
Failed to open a shell in current dir when type `wt` in  location bar of File Explore

### ISSUE THREAD

**Issue by AlanDecode** [microsoft/terminal#3217]
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
```

# Steps to reproduce

1. Open File Explore
2. Navigate to some directory
3. Type `wt` in the location bar, hit Enter

# Expected behavior

A new Terminal window is started and the current path set to current directory in File Explore. 

# Actual behavior

The current path in new started shell is always home dir, for me, `C:\Users\Alan`.

# More Info

I followed instructions in #1060 and deleted `startingDirectory ` in profiles.json, but still no luck.

**Comment by DHowett-MSFT** [comment]
Sorry for the confusion. There's some other instruction in #1060 that should help (mainly: set `startingDirectory` to `null` instead of deleting it.)

This'll be addressed by /dup #878.
