### ISSUE TITLE
Tabs don't appear after adding a lot of them

### ISSUE THREAD

**Issue by setzer17** [microsoft/terminal#3220]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

1. Keep adding tabs until the newest tabs are no longer visible

![Alt Text](https://i.ibb.co/n8wZK6q/wt-tabs-bug.gif)

# Expected behavior

The new tabs should be visible

# Actual behavior

The new tabs are not visible

**Comment by skyline75489** [comment]
I believe this no longer exists with #3027 .

**Comment by setzer17** [comment]
If that's the case please close this issue.
