### ISSUE TITLE
Suspicious remains of previous window borders flash up when closing the window

### ISSUE THREAD

**Issue by egmontkob** [microsoft/terminal#3222]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

Resize the window to smaller, then back to about its original size or even bigger.

Close the window.

# Expected behavior

The window should simply disappear.

# Actual behavior

For a fraction of a second, tons of horizontal and vertical lines, which look like the border of the window at its previous sizes, are painted inside the window area.

This suspiciously looks like some leftover widgets that don't get properly cleaned up during a resize, potentially consuming various resources (and maybe causing who knows what other problems).

(Could be related to #3207?)

![WT-closing](https://user-images.githubusercontent.com/5750745/66922099-afc72c00-f026-11e9-8ef2-d568a8223cda.png)

**Comment by DHowett-MSFT** [comment]
So! This is actually because we're only painting the border of our window and leaving the rest _unpainted_. We've seen DWM do some very strange things when we paint the client area, so this is more reactionary than planned. :smile:

**Comment by DHowett-MSFT** [comment]
Sticking this one on to #1625. Thanks!
