### ISSUE TITLE
Only tab bar is shown

### ISSUE THREAD

**Issue by dotSlashLu** [microsoft/terminal#3225]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18362.418]
Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
```

# Steps to reproduce
Unclear, but I unlocked the screen and switched to terminal from another application to find this happening.

Update:
When I resize the window from maximized to normal the body is shown.

# Expected behavior
A full window is shown.

# Actual behavior
Only the tab bar is shown and the main body is transparent.

When focused:
![screenshot-20191016222658](https://user-images.githubusercontent.com/3133289/66929043-f176c780-f064-11e9-97e4-4c5a86cbd70e.png)

Application switcher view:
![screenshot-20191016223158](https://user-images.githubusercontent.com/3133289/66929044-f3d92180-f064-11e9-8bb3-32b4a4f125af.png)

**Comment by 0xcaffebabe** [comment]
i have same proplem when maximize window

**Comment by j4james** [comment]
This might be a dup of #2733.

**Comment by dotSlashLu** [comment]
@j4james looks like so, closing.
