### ISSUE TITLE
The font selection description is misleading and should be updated

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#3226]
![image](https://user-images.githubusercontent.com/11453922/66928265-0897c400-f029-11e9-8735-e90b23712c6d.png)

> TrueType fonts are recommended for high DPI displays as raster fonts may not display clearly.

I agree that TrueType fonts are recommended. However, the motivation is irrelevant and misleading.

It is not a big deal if you have a high DPI display and choose a raster font. The worst thing that could happen is that it will be pixelated (and note - some weirdos even love that).

If someone is not satisfied with the console font, **it is pretty clear what to do** - just change it.

There's a much bigger problem with raster fonts: they can't display **anything** outside of the current OEM code page. If your OEM code page is, say, 850 - Multilingual Latin I, with raster fonts you will see `?????` instead of Cyrillic `абвгд` or `?p??s` instead of Greek `οπρςσ`.

**It is not clear at all, especially for laypeople, that the problem is in raster fonts.** I've seen multiple occasions when people think that such strings are damaged due to bugs in software or that their actual data (file names or content) is corrupted.

This sentence should be rephrased and clearly stress that raster fonts, first of all, cannot display Unicode characters in general, so beware. And only after that, if there's still some space left, it can be mentioned that hey, they can also look ugly sometimes.

**Comment by DHowett-MSFT** [comment]
If I had my way, it would say:

```
Please stop using
Raster Fonts, it’s
2019.
```

(And then, in 2020, we would get rid of them forever. Some console APIs necessarily behave differently when the user’s selected Raster Fonts as their font.)

**Comment by egmontkob** [comment]
Pango (the font rendering engine used by Linux apps using the GTK widget, including the entire GNOME desktop) just recently [dropped bitmap font support](https://blogs.gnome.org/mclasen/2019/08/07/pango-1-44-wrap-up/). Let's see where it goes, how it will be received by users...

**Comment by DHowett-MSFT** [comment]
@alabuzhev Thanks for reporting this. We're not really investing in this dialog or the legacy setting experience right now, and the burden we take on for changing it (which includes getting translation changes for every language Windows supports) is too great for us to countenance. I appreciate that it's wrong, but perhaps it'll just have to be wrong by design. That doesn't mean the design is great :smile:.
