### ISSUE TITLE
No way to select tenant number greater than 9 in Azure Cloud Shell connector

### ISSUE THREAD

**Issue by MikeLarah** [microsoft/terminal#3233]
# Environment

```none
Windows build number: 10.0.18999.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

- Open new Azure Cloud Shell tab
- Use code sign-in flow
- Presented with tenants to select

# Expected behavior

Should be able to select a tenant number greater than tenant 9, e.g. tenant 12

# Actual behavior

Selects tenant for first key that is pressed, so you can't select tenant 12, for example, as it will select tenant 1 as soon as you press the 1 key.

**Comment by DHowett-MSFT** [comment]
Yep, that's our bad. We didn't expect folks to have so many tenants.
Thanks!

**Comment by 2ndcahl** [comment]
I've got 31 tenants here ... 😵

**Comment by boecskoer** [comment]
I'm not able to select any tenant. Pressing a number doesn't do anything. Using Version: 0.7.3451.0 on Windows 10 Prof. 1909
We're are a CSP and therefore we have tons of tanents to choose from
