### ISSUE TITLE
Changing build target from debug to release makes Visual Studio hang

### ISSUE THREAD

**Issue by darthpale** [microsoft/terminal#3235]
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version 35d7d20a079e78323ed510e5535bb71fdb68712a 

Any other software?

Visual Studio Community 2019 16.3.4
```

# Steps to reproduce
git clone https://github.com/microsoft/Terminal.git
cd Terminal
git submodule update --init --recursive
nuget restore OpenConsole.sln
Open solution in VS
Change debug to release

# Expected behavior
VS Changes debug to release and proceeds

# Actual behavior
VS hangs at 100% cpu then drops to 0% still hung.

# Other Info

Other projects still work OK, previous WindowsTerminal trees can still be built either release or debug target.

**Comment by DHowett-MSFT** [comment]
VS seems to have trouble with certain solutions that contain more than, like, ten projects. It might be worth reporting an issue at the [VS developer community](https://developercommunity.visualstudio.com) if you can reliably reproduce this issue. We've seen it sporadically, on all sorts of projects, but never reliably enough to report.
