### ISSUE TITLE
Settings Opens different program

### ISSUE THREAD

**Issue by ssandeep96** [microsoft/terminal#3240]
I am seeing an issue with the settings part of the installation. Whenever I press Settings to change some of the behaviors of the program, another program (Max 6.0) opens instead of the actual settings. 

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable):
 0.5.2762.0

Any other software?
```

# Steps to reproduce

Just press the settings button

# Expected behavior
To open the settings for Windows Terminal

# Actual behavior
Opens another program called Max

**Comment by DHowett-MSFT** [comment]
The Settings button opens a JSON file using your configured JSON editor so that you can configure your settings. This is on purpose.
