### ISSUE TITLE
Cursor obscures text in Vim

### ISSUE THREAD

**Issue by johnmcdowall** [microsoft/terminal#3241]
# Environment

```none
Windows build number: 10.0.18999.1
Windows Terminal version (if applicable): Version: 0.5.2762.0
```

# Steps to reproduce
Start Windows Terminal in Ubuntu 18.04.  Install Vim. Start Vim. Type a sentence then move the cursor over a letter. See that the letter is obscured.

# Expected behavior
I'd expect the text underneath the cursor to be inverse of the cursor, or something that isn't the same as the cursor color making it invisible. I've tried almost every Vim setting for changing cursor color etc but it has no effect. Changing the `cursorColor` in the profile has no effect. 

Running the same test in Fluent Terminal (while having a blinking cursor by default) does the right thing. 

# Actual behavior
The cursor obscures the text underneath it: 

![Annotation 2019-10-17 175016](https://user-images.githubusercontent.com/237175/67057800-f68c5300-f106-11e9-9db6-5b9fe108f3e5.png)

**Comment by skyline75489** [comment]
I believe this is duplicate of #1203. I can't blame you for not finding this issue, though. For heaven's sake, it took me like 10 minutes to find it, even I clearly know it it there.

**Comment by johnmcdowall** [comment]
Ah yeah! I did search for a good while as well and didn't find that. Will close this issue.

**Comment by osmaniarb** [comment]
Possible workaround: Use the KDE [Konsole](https://en.wikipedia.org/wiki/Konsole) via X11.
