### ISSUE TITLE
Each tab should show in Filtered Task View.

### ISSUE THREAD

**Issue by michelforget** [microsoft/terminal#3247]
There is a feature in Windows called Filtered Task View which, when activated, shows all the windows associated with a given task (ie: a much cleaner view than alt+tab).  It would be nice if each tab in the terminal showed up in this view.

I suspect each tab would have to be classified as a "window" for this to work.  
The primary problem this would solve is that it would give you a way to switch to the desired tab without having to see literally everything else running on your system.

**Comment by DHowett-MSFT** [comment]
I swear we have a duplicate for this, I just won't remember where it is. This is a "hard problem" for us because those APIs only work for things that actually have windows. Like, _win32 `HWND`s_. It would also get us the ability to show individual tabs when you hover over the taskbar button ...

**Comment by DHowett-MSFT** [comment]
Found ti! /dup #2887.
