### ISSUE TITLE
First hit or keystroke misses the text

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#3249]
I am using multiple tabs in Windows Terminal, and I always notice that whenever I type very fast onto the terminal in any tab right after switching, the first letter from my written text does not get typed.

Earlier I was using git bash etc. and never faced any such issue.

Please fix this issue.

**Comment by jiveshwar** [comment]
This also happens with the text we paste into the terminal.

Example:
I pasted the below line:

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

Which automatically got pasted in the Windows terminal as 

![image](https://user-images.githubusercontent.com/7592502/67152568-893f1480-f2f6-11e9-9244-4853b541c360.png)

And, when I again pasted in the terminal, the command worked fine.

**Comment by leonMSFT** [comment]
I've tried to repro this on our current build (0.9.433.0), and can't see what you're seeing. Perhaps this has been fixed in one of the PRs that have gone in since you've reported this issue? If you can repro this bug still on our latest build, let us know!
