### ISSUE TITLE
Settings Opens Visual Studio!

### ISSUE THREAD

**Issue by asrvstv5** [microsoft/terminal#3251]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Click on the drop down menu and click settings
# Expected behavior
Settigns window should open

# Actual behavior
It launches Visual Studio 2017

**Comment by DHowett-MSFT** [comment]
That’s because Visual Studio is your JSON file editor. Change that, and it won’t launch Visual Studio any more.

**Comment by foreachthing** [comment]
@DHowett This is no help at all!
Change it to what?! Notepad++ ???

**Comment by zadjii-msft** [comment]
@foreachthing You can change it to literally whatever you want - Notepad++, Vs Code, Sublime Text, Atom, Notepad, Wordpad, whatever. Our settings are currently implemented as a `.json` file, so clicking "settings" will attempt to open the settings file with whatever the default `json` editor is on your machine. When you install Visual Studio, VS configures itself as the default editor.

**Comment by RUSshy** [comment]
this is horrible UX issue, why is every microsoft tools full of UX mistakes

is it hard to make a simple settings menu?

why Visual Studio thinks it can be a good json editor? a multi gigabytes IDE that takes an eternity to start as a json editor?

anayways, please, if you want to be taken seriously, create a setting menu, we shouldn't have to ask, this should have been implemented for release 0.1

**Comment by RUSshy** [comment]
the terminal app is super nice, feels good to use, light and start super fast, but this setting thing, i don't understand

**Comment by DHowett-MSFT** [comment]
You can change your json editor to whatever you want. Terminal doesn't control that. Sorry.
