### ISSUE TITLE
REGRESSION: HTML Copy Broken

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#3252]
# Environment

Occurs in commit 9c7e8ce1e38dafc019edca1b562fcbf43ed9652c (master as of Oct. 18, 4:50 PM PST ).

# Steps to reproduce

make a selection
copy it
paste to ms word

# Expected behavior

formatted text

# Actual behavior

formatted text paste does nothing
pasting text only works fine

**Comment by carlos-zamora** [comment]
Probably related to PR #3215.

After running a quick test, the issue is caused by `TextBuffer::GenHTML()`. The html data is not output properly. Since this is shared code between ConHost and Terminal, I'm adding an additional label.

Adding Help-Wanted so that anybody can try to fix it over the weekend. If not, I'll take a look on Monday.

**Comment by DHowett-MSFT** [comment]
#3215 only touches code in conhost (Win32 Interactivity) :smile: it’s not a likely culprit.

**Comment by DHowett-MSFT** [comment]
@0xabu is this similar to your report?

**Comment by 0xabu** [comment]
@DHowett-MSFT yes, same symptoms. Regressed between 0.5.2762 and 0.6.2911.
