### ISSUE TITLE
Terminal Window Disappears

### ISSUE THREAD

**Issue by mneundorfer** [microsoft/terminal#3253]
When I don't use the terminal for some time (preferably when I left my PC unattended for some time...), the window just disappeared.

Since I have little to no idea on how this can be reproduced consistently, I mainly want to post this here in case other people observe the same behavior.

# Environment

```none
Windows build number: 10.0.18999.1
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

I can't consistently reproduce this, but it happens to me lots of the times when I leave the terminal unused for some time (at least half an hour I would say).

# Expected behavior

As long as I don't explicitly close it, the Terminal stays open.

# Actual behavior

After some undefined period of time, the Terminal window is just gone. All that is left to make sure I'm not crazy is the processes of the tabs / panes I had opened - although I have no idea how to get back to them:

![image](https://user-images.githubusercontent.com/4457940/67140072-1fbbf900-f257-11e9-83b9-ec11f6b3e603.png)

**Comment by skycommand** [comment]
Noticed this and #3261 as well.

**Comment by mneundorfer** [comment]
Sure: https://aka.ms/AA6d8wi

**Comment by DHowett-MSFT** [comment]
Based on the feedback stream from your machine, it looks like you're hitting /dup #2735. The desktop window manager is crashing, and Terminal just cannot handle that. We'll improve it soon. :smile:

**Comment by DHowett-MSFT** [comment]
Also, you're probably having other instability issues as well!

**Comment by mneundorfer** [comment]
.. such as? Do you mean concerning the Terminal, or in general?

**Comment by DHowett-MSFT** [comment]
Oh, in general. The desktop window manager is a critical system component, and we've seen reports of Google Chrome and other things -- mostly games and browsers -- crashing at the same time that it does. :smile: Sorry for the confusion.

**Comment by mneundorfer** [comment]
I see. Although I must admit I didn't notice that... Will try to explicitly watch out for that the next time I hit this. Thanks for the feedback, though!
