### ISSUE TITLE
Support to execute 32-bit executables in a 64-bit system

### ISSUE THREAD

**Issue by srinivasanc22071986** [microsoft/terminal#3254]
# Environment

Hi, Recently I installed to PL/1 compiler from Iron-Spring http://www.iron-spring.com/index.html for Linux in the New Windows Terminal under WSL(Windows Subsystem for Linux), But I heard from certain online forums that the WSL of Windows will support only 64-bit executables and no 32-bit executables, Unfortunately the above-mentioned PL/1 compiler is a 32-bit compiler, so I tried to many times to get that working, but unable to do so, and I kept on getting the  below error,

-bash: ./plic: cannot execute binary file: Exec format error

![image](https://user-images.githubusercontent.com/49483717/67143141-e8b10c00-f285-11e9-8c31-497835c9c80d.png)

To you have any plans to implement the feature to support 32-bit executables in WSL and also in the final version of Windows New Terminal 1.0? If so when?

Also technically we cannot execute a 64-bit executable on a 32-bit operating system, but the other way round should be possible with certain minor changes in the system,

At last, I achieved the above action using some additional installation given in the below link,

https://github.com/microsoft/wsl/issues/2468#issuecomment-374904520

# Steps to reproduce

Try to execute a 32-bit executable you will get this error.

# Expected behavior

The windows terminal should execute 32-bit executables without throwing any error

# Actual behavior

The windows terminal throws a blank error without proper error descritption when a 32-bit executable is tried

**Comment by DHowett-MSFT** [comment]
_There's nothing Terminal can do about this._ Please continue to follow microsoft/wsl#2468.

**Comment by srinivasanc22071986** [comment]
Yes, I expected this reply, thank you for your support, and I will continue to follow this issue.
