### ISSUE TITLE
Unable to go past 26,428 characters

### ISSUE THREAD

**Issue by Reelix** [microsoft/terminal#3258]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
```

# Steps to reproduce

1.) Open the Windows Terminal in cmd.exe mode
2.) Navigate to C:\\
3.) Paste the following 26,425 characters

> aaaaaaaabaaaaaaacaaaaaaadaaaaaaaeaaaaaaafaaaaaaagaaaaaaahaaaaaaaiaaaaaaajaaaaaaakaaaaaaalaaaaaaamaaaaaaanaaaaaaaoaaaaaaapaaaaaaaqaaaaaaaraaaaaaasaaaaaaataaaaaaauaaaaaaavaaaaaaawaaaaaaaxaaaaaaayaaaaaaazaaaaaabbaaaaaabcaaaaaabdaaaaaabeaaaaaabfaaaaaabgaaaaaabhaaaaaabiaaaaaabjaaaaaabkaaaaaablaaaaaabmaaaaaabnaaaaaaboaaaaaabpaaaaaabqaaaaaabraaaaaabsaaaaaabtaaaaaabuaaaaaabvaaaaaabwaaaaaabxaaaaaabyaaaaaabzaaaaaacbaaaaaaccaaaaaacdaaaaaaceaaaaaacfaaaaaacgaaaaaachaaaaaaciaaaaaacjaaaaaackaaaaaaclaaaaaacmaaaaaacnaaaaaacoaaaaaacpaaaaaacqaaaaaacraaaaaacsaaaaaactaaaaaacuaaaaaacvaaaaaacwaaaaaacxaaaaaacyaaaaaaczaaaaaadbaaaaaadcaaaaaaddaaaaaadeaaaaaadfaaaaaadgaaaaaadhaaaaaadiaaaaaadjaaaaaadkaaaaaadlaaaaaadmaaaaaadnaaaaaadoaaaaaadpaaaaaadqaaaaaadraaaaaadsaaaaaadtaaaaaaduaaaaaadvaaaaaadwaaaaaadxaaaaaadyaaaaaadzaaaaaaebaaaaaaecaaaaaaedaaaaaaeeaaaaaaefaaaaaaegaaaaaaehaaaaaaeiaaaaaaejaaaaaaekaaaaaaelaaaaaaemaaaaaaenaaaaaaeoaaaaaaepaaaaaaeqaaaaaaeraaaaaaesaaaaaaetaaaaaaeuaaaaaaevaaaaaaewaaaaaaexaaaaaaeyaaaaaaezaaaaaafbaaaaaafcaaaaaafdaaaaaafeaaaaaaffaaaaaafgaaaaaafhaaaaaafiaaaaaafjaaaaaafkaaaaaaflaaaaaafmaaaaaafnaaaaaafoaaaaaafpaaaaaafqaaaaaafraaaaaafsaaaaaaftaaaaaafuaaaaaafvaaaaaafwaaaaaafxaaaaaafyaaaaaafzaaaaaagbaaaaaagcaaaaaagdaaaaaageaaaaaagfaaaaaaggaaaaaaghaaaaaagiaaaaaagjaaaaaagkaaaaaaglaaaaaagmaaaaaagnaaaaaagoaaaaaagpaaaaaagqaaaaaagraaaaaagsaaaaaagtaaaaaaguaaaaaagvaaaaaagwaaaaaagxaaaaaagyaaaaaagzaaaaaahbaaaaaahcaaaaaahdaaaaaaheaaaaaahfaaaaaahgaaaaaahhaaaaaahiaaaaaahjaaaaaahkaaaaaahlaaaaaahmaaaaaahnaaaaaahoaaaaaahpaaaaaahqaaaaaahraaaaaahsaaaaaahtaaaaaahuaaaaaahvaaaaaahwaaaaaahxaaaaaahyaaaaaahzaaaaaaibaaaaaaicaaaaaaidaaaaaaieaaaaaaifaaaaaaigaaaaaaihaaaaaaiiaaaaaaijaaaaaaikaaaaaailaaaaaaimaaaaaainaaaaaaioaaaaaaipaaaaaaiqaaaaaairaaaaaaisaaaaaaitaaaaaaiuaaaaaaivaaaaaaiwaaaaaaixaaaaaaiyaaaaaaizaaaaaajbaaaaaajcaaaaaajdaaaaaajeaaaaaajfaaaaaajgaaaaaajhaaaaaajiaaaaaajjaaaaaajkaaaaaajlaaaaaajmaaaaaajnaaaaaajoaaaaaajpaaaaaajqaaaaaajraaaaaajsaaaaaajtaaaaaajuaaaaaajvaaaaaajwaaaaaajxaaaaaajyaaaaaajzaaaaaakbaaaaaakcaaaaaakdaaaaaakeaaaaaakfaaaaaakgaaaaaakhaaaaaakiaaaaaakjaaaaaakkaaaaaaklaaaaaakmaaaaaaknaaaaaakoaaaaaakpaaaaaakqaaaaaakraaaaaaksaaaaaaktaaaaaakuaaaaaakvaaaaaakwaaaaaakxaaaaaakyaaaaaakzaaaaaalbaaaaaalcaaaaaaldaaaaaaleaaaaaalfaaaaaalgaaaaaalhaaaaaaliaaaaaaljaaaaaalkaaaaaallaaaaaalmaaaaaalnaaaaaaloaaaaaalpaaaaaalqaaaaaalraaaaaalsaaaaaaltaaaaaaluaaaaaalvaaaaaalwaaaaaalxaaaaaalyaaaaaalzaaaaaambaaaaaamcaaaaaamdaaaaaameaaaaaamfaaaaaamgaaaaaamhaaaaaamiaaaaaamjaaaaaamkaaaaaamlaaaaaammaaaaaamnaaaaaamoaaaaaampaaaaaamqaaaaaamraaaaaamsaaaaaamtaaaaaamuaaaaaamvaaaaaamwaaaaaamxaaaaaamyaaaaaamzaaaaaanbaaaaaancaaaaaandaaaaaaneaaaaaanfaaaaaangaaaaaanhaaaaaaniaaaaaanjaaaaaankaaaaaanlaaaaaanmaaaaaannaaaaaanoaaaaaanpaaaaaanqaaaaaanraaaaaansaaaaaantaaaaaanuaaaaaanvaaaaaanwaaaaaanxaaaaaanyaaaaaanzaaaaaaobaaaaaaocaaaaaaodaaaaaaoeaaaaaaofaaaaaaogaaaaaaohaaaaaaoiaaaaaaojaaaaaaokaaaaaaolaaaaaaomaaaaaaonaaaaaaooaaaaaaopaaaaaaoqaaaaaaoraaaaaaosaaaaaaotaaaaaaouaaaaaaovaaaaaaowaaaaaaoxaaaaaaoyaaaaaaozaaaaaapbaaaaaapcaaaaaapdaaaaaapeaaaaaapfaaaaaapgaaaaaaphaaaaaapiaaaaaapjaaaaaapkaaaaaaplaaaaaapmaaaaaapnaaaaaapoaaaaaappaaaaaapqaaaaaapraaaaaapsaaaaaaptaaaaaapuaaaaaapvaaaaaapwaaaaaapxaaaaaapyaaaaaapzaaaaaaqbaaaaaaqcaaaaaaqdaaaaaaqeaaaaaaqfaaaaaaqgaaaaaaqhaaaaaaqiaaaaaaqjaaaaaaqkaaaaaaqlaaaaaaqmaaaaaaqnaaaaaaqoaaaaaaqpaaaaaaqqaaaaaaqraaaaaaqsaaaaaaqtaaaaaaquaaaaaaqvaaaaaaqwaaaaaaqxaaaaaaqyaaaaaaqzaaaaaarbaaaaaarcaaaaaardaaaaaareaaaaaarfaaaaaargaaaaaarhaaaaaariaaaaaarjaaaaaarkaaaaaarlaaaaaarmaaaaaarnaaaaaaroaaaaaarpaaaaaarqaaaaaarraaaaaarsaaaaaartaaaaaaruaaaaaarvaaaaaarwaaaaaarxaaaaaaryaaaaaarzaaaaaasbaaaaaascaaaaaasdaaaaaaseaaaaaasfaaaaaasgaaaaaashaaaaaasiaaaaaasjaaaaaaskaaaaaaslaaaaaasmaaaaaasnaaaaaasoaaaaaaspaaaaaasqaaaaaasraaaaaassaaaaaastaaaaaasuaaaaaasvaaaaaaswaaaaaasxaaaaaasyaaaaaaszaaaaaatbaaaaaatcaaaaaatdaaaaaateaaaaaatfaaaaaatgaaaaaathaaaaaatiaaaaaatjaaaaaatkaaaaaatlaaaaaatmaaaaaatnaaaaaatoaaaaaatpaaaaaatqaaaaaatraaaaaatsaaaaaattaaaaaatuaaaaaatvaaaaaatwaaaaaatxaaaaaatyaaaaaatzaaaaaaubaaaaaaucaaaaaaudaaaaaaueaaaaaaufaaaaaaugaaaaaauhaaaaaauiaaaaaaujaaaaaaukaaaaaaulaaaaaaumaaaaaaunaaaaaauoaaaaaaupaaaaaauqaaaaaauraaaaaausaaaaaautaaaaaauuaaaaaauvaaaaaauwaaaaaauxaaaaaauyaaaaaauzaaaaaavbaaaaaavcaaaaaavdaaaaaaveaaaaaavfaaaaaavgaaaaaavhaaaaaaviaaaaaavjaaaaaavkaaaaaavlaaaaaavmaaaaaavnaaaaaavoaaaaaavpaaaaaavqaaaaaavraaaaaavsaaaaaavtaaaaaavuaaaaaavvaaaaaavwaaaaaavxaaaaaavyaaaaaavzaaaaaawbaaaaaawcaaaaaawdaaaaaaweaaaaaawfaaaaaawgaaaaaawhaaaaaawiaaaaaawjaaaaaawkaaaaaawlaaaaaawmaaaaaawnaaaaaawoaaaaaawpaaaaaawqaaaaaawraaaaaawsaaaaaawtaaaaaawuaaaaaawvaaaaaawwaaaaaawxaaaaaawyaaaaaawzaaaaaaxbaaaaaaxcaaaaaaxdaaaaaaxeaaaaaaxfaaaaaaxgaaaaaaxhaaaaaaxiaaaaaaxjaaaaaaxkaaaaaaxlaaaaaaxmaaaaaaxnaaaaaaxoaaaaaaxpaaaaaaxqaaaaaaxraaaaaaxsaaaaaaxtaaaaaaxuaaaaaaxvaaaaaaxwaaaaaaxxaaaaaaxyaaaaaaxzaaaaaaybaaaaaaycaaaaaaydaaaaaayeaaaaaayfaaaaaaygaaaaaayhaaaaaayiaaaaaayjaaaaaaykaaaaaaylaaaaaaymaaaaaaynaaaaaayoaaaaaaypaaaaaayqaaaaaayraaaaaaysaaaaaaytaaaaaayuaaaaaayvaaaaaaywaaaaaayxaaaaaayyaaaaaayzaaaaaazbaaaaaazcaaaaaazdaaaaaazeaaaaaazfaaaaaazgaaaaaazhaaaaaaziaaaaaazjaaaaaazkaaaaaazlaaaaaazmaaaaaaznaaaaaazoaaaaaazpaaaaaazqaaaaaazraaaaaazsaaaaaaztaaaaaazuaaaaaazvaaaaaazwaaaaaazxaaaaaazyaaaaaazzaaaaababaaaaabacaaaaabadaaaaabaeaaaaabafaaaaabagaaaaabahaaaaabaiaaaaabajaaaaabakaaaaabalaaaaabamaaaaabanaaaaabaoaaaaabapaaaaabaqaaaaabaraaaaabasaaaaabataaaaabauaaaaabavaaaaabawaaaaabaxaaaaabayaaaaabazaaaaabbbaaaaabbcaaaaabbdaaaaabbeaaaaabbfaaaaabbgaaaaabbhaaaaabbiaaaaabbjaaaaabbkaaaaabblaaaaabbmaaaaabbnaaaaabboaaaaabbpaaaaabbqaaaaabbraaaaabbsaaaaabbtaaaaabbuaaaaabbvaaaaabbwaaaaabbxaaaaabbyaaaaabbzaaaaabcbaaaaabccaaaaabcdaaaaabceaaaaabcfaaaaabcgaaaaabchaaaaabciaaaaabcjaaaaabckaaaaabclaaaaabcmaaaaabcnaaaaabcoaaaaabcpaaaaabcqaaaaabcraaaaabcsaaaaabctaaaaabcuaaaaabcvaaaaabcwaaaaabcxaaaaabcyaaaaabczaaaaabdbaaaaabdcaaaaabddaaaaabdeaaaaabdfaaaaabdgaaaaabdhaaaaabdiaaaaabdjaaaaabdkaaaaabdlaaaaabdmaaaaabdnaaaaabdoaaaaabdpaaaaabdqaaaaabdraaaaabdsaaaaabdtaaaaabduaaaaabdvaaaaabdwaaaaabdxaaaaabdyaaaaabdzaaaaabebaaaaabecaaaaabedaaaaabeeaaaaabefaaaaabegaaaaabehaaaaabeiaaaaabejaaaaabekaaaaabelaaaaabemaaaaabenaaaaabeoaaaaabepaaaaabeqaaaaaberaaaaabesaaaaabetaaaaabeuaaaaabevaaaaabewaaaaabexaaaaabeyaaaaabezaaaaabfbaaaaabfcaaaaabfdaaaaabfeaaaaabffaaaaabfgaaaaabfhaaaaabfiaaaaabfjaaaaabfkaaaaabflaaaaabfmaaaaabfnaaaaabfoaaaaabfpaaaaabfqaaaaabfraaaaabfsaaaaabftaaaaabfuaaaaabfvaaaaabfwaaaaabfxaaaaabfyaaaaabfzaaaaabgbaaaaabgcaaaaabgdaaaaabgeaaaaabgfaaaaabggaaaaabghaaaaabgiaaaaabgjaaaaabgkaaaaabglaaaaabgmaaaaabgnaaaaabgoaaaaabgpaaaaabgqaaaaabgraaaaabgsaaaaabgtaaaaabguaaaaabgvaaaaabgwaaaaabgxaaaaabgyaaaaabgzaaaaabhbaaaaabhcaaaaabhdaaaaabheaaaaabhfaaaaabhgaaaaabhhaaaaabhiaaaaabhjaaaaabhkaaaaabhlaaaaabhmaaaaabhnaaaaabhoaaaaabhpaaaaabhqaaaaabhraaaaabhsaaaaabhtaaaaabhuaaaaabhvaaaaabhwaaaaabhxaaaaabhyaaaaabhzaaaaabibaaaaabicaaaaabidaaaaabieaaaaabifaaaaabigaaaaabihaaaaabiiaaaaabijaaaaabikaaaaabilaaaaabimaaaaabinaaaaabioaaaaabipaaaaabiqaaaaabiraaaaabisaaaaabitaaaaabiuaaaaabivaaaaabiwaaaaabixaaaaabiyaaaaabizaaaaabjbaaaaabjcaaaaabjdaaaaabjeaaaaabjfaaaaabjgaaaaabjhaaaaabjiaaaaabjjaaaaabjkaaaaabjlaaaaabjmaaaaabjnaaaaabjoaaaaabjpaaaaabjqaaaaabjraaaaabjsaaaaabjtaaaaabjuaaaaabjvaaaaabjwaaaaabjxaaaaabjyaaaaabjzaaaaabkbaaaaabkcaaaaabkdaaaaabkeaaaaabkfaaaaabkgaaaaabkhaaaaabkiaaaaabkjaaaaabkkaaaaabklaaaaabkmaaaaabknaaaaabkoaaaaabkpaaaaabkqaaaaabkraaaaabksaaaaabktaaaaabkuaaaaabkvaaaaabkwaaaaabkxaaaaabkyaaaaabkzaaaaablbaaaaablcaaaaabldaaaaableaaaaablfaaaaablgaaaaablhaaaaabliaaaaabljaaaaablkaaaaabllaaaaablmaaaaablnaaaaabloaaaaablpaaaaablqaaaaablraaaaablsaaaaabltaaaaabluaaaaablvaaaaablwaaaaablxaaaaablyaaaaablzaaaaabmbaaaaabmcaaaaabmdaaaaabmeaaaaabmfaaaaabmgaaaaabmhaaaaabmiaaaaabmjaaaaabmkaaaaabmlaaaaabmmaaaaabmnaaaaabmoaaaaabmpaaaaabmqaaaaabmraaaaabmsaaaaabmtaaaaabmuaaaaabmvaaaaabmwaaaaabmxaaaaabmyaaaaabmzaaaaabnbaaaaabncaaaaabndaaaaabneaaaaabnfaaaaabngaaaaabnhaaaaabniaaaaabnjaaaaabnkaaaaabnlaaaaabnmaaaaabnnaaaaabnoaaaaabnpaaaaabnqaaaaabnraaaaabnsaaaaabntaaaaabnuaaaaabnvaaaaabnwaaaaabnxaaaaabnyaaaaabnzaaaaabobaaaaabocaaaaabodaaaaaboeaaaaabofaaaaabogaaaaabohaaaaaboiaaaaabojaaaaabokaaaaabolaaaaabomaaaaabonaaaaabooaaaaabopaaaaaboqaaaaaboraaaaabosaaaaabotaaaaabouaaaaabovaaaaabowaaaaazzzzz

4.) After the 5 ending z's, type the word "hello"

# Expected behavior

You are able to carry on typing

# Actual behavior
You are prevented from typing

**Comment by DHowett-MSFT** [comment]
This is just a length limit in CMD, which we can't change for compatibility reasons. I've heard that PowerShell is a lot better here. :smile:

Thanks!
