### ISSUE TITLE
Multiple Key bindings don't work

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#3260]
I tried assigning multiple key bindings to the events in Windows Terminal, but it is leading to the default action of the category.

Example: I assigned CTRL+C and CTRL+SHIFT+C to the Copy feature, but then only the default CTRL+SHIFT+C worked. Not the CTRL+C

![image](https://user-images.githubusercontent.com/7592502/67152971-b099df80-f2fe-11e9-9776-2cd976f45ed9.png)

**Comment by DHowett-MSFT** [comment]
Add a new command entry (a separate key binding) for every different key combination you want to trigger the event. Putting multiple keys into the “keys” array is for key _chording_, when you want to press multiple keys in a given order to accomplish one action.
Chording is not yet supported. :smile:

**Comment by DHowett-MSFT** [comment]
Also, all bindings are additive. You don’t need to include the default bindings in your settings because your settings are _added_ to the defaults.
