### ISSUE TITLE
Feature Request - Running commands every new instance(s)

### ISSUE THREAD

**Issue by cloudrex** [microsoft/terminal#3265]
# Description of the new feature/enhancement
Ability to specify a list of command(s) to be ran upon opening a new terminal. This would be extremely useful if users wanted to configure their terminal upon opening a new tab, for example, I would like that once I open a new CMD instance it would go to a specific directory (cd ...).

It's obvious there may need to be different lists for different terminals.

**Comment by Biswa96** [comment]
Try this command line `cmd.exe /k cd /d "C:\path\to\folder"`. The `/k` option carries out the command but remains the Command Prompt window.

**Comment by cloudrex** [comment]
@Biswa96 That's a great idea, seems to work just fine. I guess power users would see this as a given as well.

**Comment by oising** [comment]
@cloudrex -- I'm closing this as your question/need appears to be answered.
