### ISSUE TITLE
Exceptional slowness of low level input of console since 09.19

### ISSUE THREAD

**Issue by Agrael1** [microsoft/terminal#3269]
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version (if applicable):
```

# Steps to reproduce

I had a 640:360 buffer, which was resized from original by making font smaller(2x2). Buffer Must not be monolithic, but even single colored buffer takes 15ms to fill with 7th system call on NtDeviceIOControl from WriteConsoleOutputW. When it contains some picture, render time grows drastically to 79-84ms. 

If Asked I can pass a serialized picture from my engine, drawn using char_info with custom palette

# Expected behavior

A Low level output prior to latest updates was projecting the same symbol buffer at 100-200 actions per second. Timings were 25ms at max. I'm making a console game engine and those timings are crucial. If there is any better function which passes the console output buffer (CHAR_INFO*) please tell me.

# Actual behavior

Low level output takes 74-76 ms to accomplish, no faster analogs found, buffer size is 640:360

![image](https://user-images.githubusercontent.com/23313867/67164049-8edc3f00-f376-11e9-8f7c-91a10762e65e.png)

**Comment by parkovski** [comment]
Hey, I'd really like to see profiler data for that project... I'm not necessarily ruling out conhost doing something slowly as I've experienced those kind of issues myself. However, I looked at your Veritas-2D code and it's hard to understand but I can tell you right away that you have a lot more allocations than is normal for C, and your `shared_ptr` can easily result in unaligned reads/writes of the counter.

Cache locality and memory alignment are two of the most important things that if you mess up will make your code extremely slow (or not work at all depending on the architecture, Intel is forgiving here but ARM is not). Coupling this with a denser grid (e.g. more allocations, assumedly more memory fragmentation), I could easily see it running 4x-8x slower. I couldn't really say if there are other issues because there's a lot of obfuscation behind macros.

**Comment by Agrael1** [comment]
> Hey, I'd really like to see profiler data for that project... I'm not necessarily ruling out conhost doing something slowly as I've experienced those kind of issues myself. However, I looked at your Veritas-2D code and it's hard to understand but I can tell you right away that you have a lot more allocations than is normal for C, and your `shared_ptr` can easily result in unaligned reads/writes of the counter.
> 
> Cache locality and memory alignment are two of the most important things that if you mess up will make your code extremely slow (or not work at all depending on the architecture, Intel is forgiving here but ARM is not). Coupling this with a denser grid (e.g. more allocations, assumedly more memory fragmentation), I could easily see it running 4x-8x slower. I couldn't really say if there are other issues because there's a lot of obfuscation behind macros.

Ok, I'll try to allocate as less memory as possible, also, `shared_ptr` is just made from what I've seen in C++ (I'm trying to learn internals of the C++, because its mechanics are obfuscated the same way as macros and I hate magic), also the buffer has to be dynamic, otherwise buffer resize won't work e.g. changing resolution... 

The most of the macros are just automation for namings which emulate mangling, and ENDCLASSDESC is just making a class table definition. but there are no problems in class code, as I've tested the render of nanosuite model takes around 6ms with dynamic lights and complete texture. The question takes solely the part of WriteConsoleOutput, which takes the buffer produced by render and passes it to console. From here I can't predict what alignment it requires, because those buffers are allocated by default malloc, meaning 16 is an alignment of the buffer, so from that I can't really tell what is wrong with it.

**Comment by lhecker** [comment]
We're still not down to where we used to be but it's a lot better now:

![Image](https://github.com/user-attachments/assets/0fd8b343-5cac-408b-a2dd-f08a68c18c16)

I'll be closing this issue then, as I continue to noodle on our performance. It'll get a lot better in the next version once I rewrote the GDI renderer and detached it from the global console mutex (= async rendering). FYI: For optimal performance, please make sure to use VT output.
