### ISSUE TITLE
Terminal exits when moving window to another display

### ISSUE THREAD

**Issue by rjfmachado** [microsoft/terminal#3273]
# Environment

```none
Windows build number: Windows 10 18363
Windows Terminal version (if applicable): 0.6.2911.0
```

# Steps to reproduce

Drag the terminal window to other display. Terminal will exit after a second or so of being unresponsive.

![2019-10-21_19-58-18](https://user-images.githubusercontent.com/3235846/67230611-e2659000-f43d-11e9-93f7-12b0915a592f.gif)

**Comment by rjfmachado** [comment]
https://aka.ms/AA6cvr1

**Comment by DHowett-MSFT** [comment]
Based on your feedback archive, this looks like https://github.com/microsoft/terminal/issues/2277#issuecomment-521064993

Thanks @rjfmachado!

/dup #2277
