### ISSUE TITLE
Can't launch wt.exe with current directory as the starting directory

### ISSUE THREAD

**Issue by terrajobst** [microsoft/terminal#3274]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19002.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Scenario

I was using the new & shiny Git client [Fork](https://fork.dev/). It allows launching a terminal for the current repo. All other shells properly lunch in my Git folder except for Windows Terminal which always ends up in user profile.

# Steps to reproduce

Here is what I tried:

1. Entirely removed `startingDirectory` from my profile
2. Explicit set `startingDirectory` to %CD%

# Expected behavior

Give me a way to allow the terminal to launch from a current directory. I'm OK if that means having to set my default profile to `%CD%`.

# Actual behavior

Removing `startingDirectory` or setting it to `%CD%` still results in launching in `%USERPROFILE%`. However, setting an explicit path (e.g. `P:\`) still works.

**Comment by terrajobst** [comment]
Apparently, this is by-design:

https://github.com/ForkIssues/TrackerWin/issues/475#issuecomment-538691506

> This is a "feature" of Windows Terminal.
> 
> You must change 'profiles.json':
> 
> "startingDirectory" : ".",

Syntax is slightly unexpected, but hey.

**Comment by skygate2012** [comment]
You can the starting directory as argument in command line: https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#target-a-directory
