### ISSUE TITLE
Diagonal blanks when using vim

### ISSUE THREAD

**Issue by lzybkr** [microsoft/terminal#3277]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.6.2911.0

Any other software?
Windows vim 8.1.1006
```

# Steps to reproduce

Open a file in vim and type <kbd>Ctrl+b</kbd> repeatedly. The 3 screenshots below are each after typing <kbd>Ctrl+b</kbd> once.

# Expected behavior

No weird blank diagonals while using vim.

# Actual behavior

![image](https://user-images.githubusercontent.com/2148248/67248410-41fd7480-f419-11e9-911e-b8314ca66f5e.png)
![image](https://user-images.githubusercontent.com/2148248/67248420-488bec00-f419-11e9-800e-08024fa48ada.png)
![image](https://user-images.githubusercontent.com/2148248/67248430-4e81cd00-f419-11e9-8e2b-b94b7c32d5d1.png)

**Comment by DHowett-MSFT** [comment]
Repro'd. Time to pop into the debugger and see what's coming out of conhost. :smile:

**Comment by DHowett-MSFT** [comment]
This regressed with #2965 due to the cursor positioning changes.

**Comment by skyline75489** [comment]
This is really a "wow" bug, as in "wow how did this happen" and also "wow how did you notice this".

**Comment by skyline75489** [comment]
Yeah, I also think it may has something to do with #2965 . Should we just revert both #2965 and #2932 ?

**Comment by DHowett-MSFT** [comment]
There's two "real" solutions to the issue in #1360 -- one is to _always do "deferred EOL" for terminal_ (if we go off the edge of the screen, only increment Y and reset X for the _next_ character. This is partially supported by Cursor, which has deferred EOL options.

The other is to implement #780. :smile:

**Comment by DHowett-MSFT** [comment]
@skyline75489  I wish we didn't have to, but I do feel safest about reverting both of them.

**Comment by skyline75489** [comment]
@DHowett-MSFT I'm OK with it. No hard feeling. The CJK support is, after all, right now far from ideal with #2213 still open. Reverting those commits doesn't really hurt anyone, at least not me.

But #1360 and the crash while resizing will still be in the dark. That's somewhat discomforting.

**Comment by lzybkr** [comment]
@DHowett-MSFT - I'm seeing this issue again in vim using Version: 0.9.271.0

![image](https://user-images.githubusercontent.com/2148248/73384118-7639ca00-427f-11ea-94e1-11828c67bb7e.png)

I don't yet have a consistent repro though.

**Comment by DHowett-MSFT** [comment]
Ugh.

**Comment by DHowett-MSFT** [comment]
This likely regressed with #4150 (@lhecker) -- this ares has traditionally been frustrating to work in because Terminal doesn't support Delayed EOL properly.

**Comment by lhecker** [comment]
I'm sorry. 😓 Normally I'd try and remedy the issue now, but I'm sadly unable to reproduce it.
I tried various files in vim and in none of them did <kbd>Ctrl</kbd><kbd>B</kbd> generate any blank spots for me. Do I have to modify vim in any fashion for this to happen?

**Comment by zadjii-msft** [comment]
Hey @lzybkr are you still seeing this? If you can consistently repro this, @DHowett-MSFT's got an idea of how you might be able to get us some debug output to help us investigate ☺️

**Comment by lzybkr** [comment]
I haven't seen it for awhile, I'll close it and reopen if I see it again.
