### ISSUE TITLE
WSL Distro Logos Missing from Tabs and Menu

### ISSUE THREAD

**Issue by RebornJumpman** [microsoft/terminal#3283]
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version (if applicable): 0.5.2762.0

Any other software? WSL
```

# Steps to reproduce

- Install Windows Terminal (Preview) from Microsoft Store
- Install Linux distro from Microsoft Store
- Setup distro using WSL
- Run Windows Terminal

# Expected behavior

Expected to see the distro logos for Ubuntu, Debian, openSUSE, and Kali in the menu and on each tab.  An example can be found at this article from the Microsoft dev blog [this article from the Microsoft dev blog](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1909/).

<img width="835" alt="close-window-prompt" src="https://user-images.githubusercontent.com/24984140/67256446-fa94d980-f454-11e9-8c4c-2debef7c53d1.png">

# Actual behavior

The logos for all 4 distros were replaced with the standard Tux logo

![tux logos](https://user-images.githubusercontent.com/24984140/67256463-18fad500-f455-11e9-8755-e095ba825610.PNG)

**Comment by RebornJumpman** [comment]
I'm new to GitHub and this is my first time reporting a bug on here.  If I need to do anything differently, please let me know!

**Comment by carlos-zamora** [comment]
@DHowett-MSFT would we be able to include the assets in our package and just link them in our dynamic profiles?

**Comment by carlos-zamora** [comment]
@RebornJumpman as of now, we don’t include the assets in our package so we just link the Tuz penguin. You can override them by using the “icon” setting in your profiles.json. Then put whatever image you want there.

Ideally, though, we’d be able to do this automatically for you.

**Comment by RebornJumpman** [comment]
@carlos-zamora got it.  That makes sense.  I'm really excited about this project and look forward to see the upcoming changes!

**Comment by DHowett-MSFT** [comment]
Thanks for the request! We actually can't really redistribute all their logos, so we've left this up to user choice. Sorry!
