### ISSUE TITLE
How soon can it be used in Windows 1803?

### ISSUE THREAD

**Issue by lsongseven** [microsoft/terminal#3285]
# Description of the new feature/enhancement
My windows version is 1803, but I want to try this cool terminal. So how soon can it come into reality?

# Proposed technical implementation details (optional)

**Comment by MitchTalmadge** [comment]
Probably never unless some of the new features of 1903 (like XAML Islands) get ported to the older versions, which may never happen.

For more reasons see this comment: 

https://github.com/microsoft/terminal/issues/2480#issuecomment-523020964

**Comment by DHowett-MSFT** [comment]
Sorry. ☹️ I'm closing this as a /dupe of #2480 as suggested by @MitchTalmadge. Thanks, Mitch!
