### ISSUE TITLE
Set default WSL path to distro $HOME

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#3286]
# Set default WSL path to distro $HOME

The default path for WSL distros is currently the Windows user path (`%USERPROFILE%`) but it's may be better to set it to the distro `$HOME`.

# Proposed technical implementation details (optional)

I don't know if it's possible, but ideally in the `WslDistroGenerator.cpp` the command line should be conditionally set to `"wsl.exe -d " + distName` if `startingDirectory` is set in `profile.json`, `"wsl.exe ~ -d " + distName` otherwise.
Another possibility is to add a boolean setting `UseWSLHome` on the wsl `profile.json`
Thank you.

**Comment by Biswa96** [comment]
Two ways:

1. Add this command in `.bashrc` file `cd ~`
Or
2. Run this command line `wsl -d Ubuntu sh -c "cd ~;exec $SHELL"`

**Comment by mveril** [comment]
I already set `"commandline" : "wsl.exe ~ -d Ubuntu"` in my profile `profile.json`and it works, but it's a workaround and a standard method should be better.

**Comment by leoniDEV** [comment]
As said in [this issue](https://github.com/microsoft/terminal/issues/2849), you can set the `startingDirectory` to `//wsl$/distro/home/username`

**Comment by mveril** [comment]
Ok it's another good workaround
Thank you @leoniDEV

**Comment by leoniDEV** [comment]
Anyway I agree with you that the default `startingDirectory` for WSL should be the `$HOME `of the WSL user and not the `%USERPROFILE%` of the Windows user

**Comment by sivaramn** [comment]
> Anyway I agree with you that the default `startingDirectory` for WSL should be the `$HOME `of the WSL user and not the `%USERPROFILE%` of the Windows user

Agreed, at least going by the principle of DWIM. if we're launching WSL, it should default to normal *nices behaviour of logging into users home directory *within* wsl, not some other directory

**Comment by carlos-zamora** [comment]
Is this the default directory for WSL distros when opening with ConHost.

**Comment by sivaramn** [comment]
> 
> 
> Is this the default directory for WSL distros when opening with ConHost?

Don't understand.  If I login into wsl using putty, mintty or any other terminal software, the shell prompt comes at `/home/<userid>` that you created at first install of wsl.  

In MS terminal, the default seems to be `/mnt/c/users/profile` or something.  This is generally not the default way

**Comment by mveril** [comment]
> > Is this the default directory for WSL distros when opening with ConHost?
> 
> Don't understand. If I login into wsl using putty, mintty or any other terminal software, the shell prompt comes at `/home/<userid>` that you created at first install of wsl.
> 
> In MS terminal, the default seems to be `/mnt/c/users/profile` or something. This is generally not the default way

When we launch `wsl.exe` without `~`  argument it's run WSL at the working directory and when we add `~` in the argument list of WSL it's launched at the distro $HOME (`/home/<userid>`) directory.
If we launch `<distro>.exe` of a distro downloaded from the store or when we open the distro app from the start menu the directory is also set to $HOME.
I hope I answered to your question @carlos-zamora

**Comment by DHowett-MSFT** [comment]
It looks like you've got a workaround here. For the rest, we'll track them in /dup #878 and #592

**Comment by chihab** [comment]
From Terminal Settings (ctrl + ,):

![image](https://user-images.githubusercontent.com/196852/132467618-706f18c0-10c0-4706-8e2b-d3e5ca734ba2.png)

Starting directory should be: \\wsl$\YOUR_DISTRIB\home\YOUR_USERNAME

You can access the path in Explorer.

**Comment by aress31** [comment]
Well, I am facing the same issue, and I launch my VM directly via the `wsl` command rather than opening a `Terminal Profile`, there is the workaround of typing `wsl --cd ~` but maybe this `startDirectory` option could be added to `wsl.config` to not pollute my `.bashrc`.
