### ISSUE TITLE
'Win+.' emoji picker doesn't start in the terminal

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3308]
Terminal 0.6.2951.0, Windows 10.0.18908.0.

# Steps to reproduce

Open terminal (I;m using pwsh as that's default) and hit 'Win .'

# Expected behavior

Emoji picker is shown.

# Actual behavior

Nothing happens.

**Comment by j4james** [comment]
This is actually a duplicate of #2213. See #3042 for a similar report.
