### ISSUE TITLE
Copy/Paste in WSL terminal adds extra newline after each line of copied text

### ISSUE THREAD

**Issue by vineethrp** [microsoft/terminal#3309]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19008.1]
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

1. Copy a set of lines by marking using mouse and then Ctrl+C.  You can also use `"copyOnSelect" : true,` in the settings.
2. Open vim and paste using Shift + Insert.
3. You would be able to see extra newlines after each line of copied text

# Expected behavior
You should not be seeing extra newlines when you copy text

# Actual behavior

Extra newlines after each line of copied text.

**Comment by zadjii-msft** [comment]
I'm _fairly_ certain this is a dupe of #1091, though I think @DHowett-MSFT or @carlos-zamora should confirm for me

**Comment by vineethrp** [comment]
> I'm _fairly_ certain this is a dupe of #1091, though I think @DHowett-MSFT or @carlos-zamora should confirm for me

Yes, I think you are right. Sorry for the dup, my github search did not show this 1091.
