### ISSUE TITLE
UI: active tab background should match terminal background

### ISSUE THREAD

**Issue by simonferquel** [microsoft/terminal#3310]
# Description of the new feature/enhancement

With some terminal background colors, spotting witch tab is active is a bit tricky:
![image](https://user-images.githubusercontent.com/1677333/67476237-eb31ae00-f657-11e9-8570-e31b73c99e0b.png)
In this example, with only 2 tabs open, with the same name, it is confusing.

# Proposed technical implementation details (optional)

The active tab background/foreground colors should match the terminal's profile background/foreground colors:
![image](https://user-images.githubusercontent.com/1677333/67476439-57acad00-f658-11e9-87d4-31be46e28bf6.png)

**Comment by zadjii-msft** [comment]
We definitely agree that this is a good suggestion! It definitely needs some massaging settings-wise to make sure it's configurable the way people like, but it's a good idea. You can track the progress of this at the original issue below:

/dup #702
