### ISSUE TITLE
typing exit in a PowerShell instance doesn't close the Tab/Session

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/terminal#3312]
# Environment

10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal (Preview) Version: 0.6.2951.0

# Steps to reproduce

1. open a PowerShell tab
2. type exit

# Expected behavior
tab closes (if last tab, Terminal closes)

# Actual behavior

powershell session ends, but tab stays open

**Comment by burtonrodman** [comment]
of course, now I can't reproduce this again :(

**Comment by DHowett-MSFT** [comment]
Closing no repro. Let us know! Thanks.
