### ISSUE TITLE
No keybinding command for resetFontSize

### ISSUE THREAD

**Issue by blami** [microsoft/terminal#3319]
# Description of the new feature/enhancement
There are commands for increase/decrease font size but no command for resetting to default stored in profile. This is very useful when you end presenting, etc. and want keep using pane in normal conditions.

# Proposed technical implementation details (optional)
Add resetFontSize command that will set font size to configured value.

**Comment by zadjii-msft** [comment]
This is something I know that @bitcrazed has definitely complained about before :) Thanks for the report!

**Comment by bitcrazed** [comment]
I don't complain. I just implore the team for reason and sanity. Sometimes I get one or the other but rarely both. Perhaps this can be one such case? ;)

**Comment by blami** [comment]
Thanks!
