### ISSUE TITLE
Starting a ConPTY process with UAC elevation

### ISSUE THREAD

**Issue by Eugeny** [microsoft/terminal#332]
What is the Microsoft's recommended way to start an elevated process with an attached PTY?

1) CredUIPromptForWindowsCredentialsW + LogonUserW + CreateProcessWithTokenW?
2) Running runas.exe with a PTY?
3) Something else?

**Comment by Biswa96** [comment]
`KernelBase.dll` has an un-exported function `CreatePseduoConsoleAsUser()` which uses `CreateProcessAsUserW(hToken, ...)`. The `hToken` parameter can be configured with admin privileges. It seems that the underlying `conhost.exe` process should also be run as administrator.

**Comment by DHowett** [comment]
@Biswa96 please do not encourage people to rely on our private APIs.

**Comment by DHowett** [comment]
@Eugeny we don’t have an official stance on elevating a pseudoconsole client. At the moment, you’d have the best chance of success by shipping an elevated helper and using that to broker communication with your lower-IL process.

**Comment by parkovski** [comment]
I don't think the private API really matters here - when you call `CreateProcessAsUser`, you need to have `SE_ASSIGNPRIMARYTOKEN_NAME`, which restricted tokens don't have. So the only thing that API would help with is letting you create a PTY as another user _if you are already elevated_.

I'm experimenting with these scenarios [here](https://github.com/parkovski/wsudo), but it's **very** experimental and currently broken as I'm refactoring it to be more testable.

**Comment by Biswa96** [comment]
Is it possible to implement `CreatePseduoConsole()` function in `conhost.exe` or `cmd.exe`, then enable/disable conpty feature from registry? I am asking this because when I implement that function in a main program (like in EchoCon) without linking with kernel32 then all associated executables run with administrator privilege.

**Comment by DHowett-MSFT** [comment]
This discussion has, perhaps, outlived its usefulness.

**Comment by Biswa96** [comment]
The private API `CreatePseduoConsoleAsUser()` now becomes a open source one in `src/winconpty/winconpty.cpp`.

**Comment by DHowett-MSFT** [comment]
Creating a process as a different user was always possible, even without a pseudoconsole running as that user. The hard part is getting the correct part of the user's split token to launch _elevated_, which CreatePseudoConsoleAsUser _still_ doesn't let you do. :smile:

**Comment by DHowett-MSFT** [comment]
to wit: it is subject to the same limitation @parkovski already pointed out.
