### ISSUE TITLE
Writing random output to console output handle fails with no last error set

### ISSUE THREAD

**Issue by benhillis** [microsoft/terminal#3320]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19002.1000]

Any other software?
WSL2
```

# Steps to reproduce
https://github.com/microsoft/WSL/issues/4495
1. Install Ubuntu 18.04 distro from store
2. `for i in /bin/*; do head ${i}; done`
3. Observe wsl window hang or crash

# Expected behavior

Contents of the files are displayed, no hang / crash.

# Actual behavior

WSL window will close, or hang.  Seems like an issue with (or around) Utf8ToWideCharParser::_InvolvedParse.

**Comment by jstarks** [comment]
Should `_InvolvedParse` just stop passing `MB_ERR_INVALID_CHARS` to `MultiByteToWideChar`?

**Comment by benhillis** [comment]
@jstarks - that was my naive take, I can try building a private with that change.

**Comment by jstarks** [comment]
Although there's also a call to `_RemoveInvalidSequences` before that, which presumably should remove any invalid UTF-8 sequences.

**Comment by DHowett-MSFT** [comment]
(This is being investigated.)
