### ISSUE TITLE
Cursor color should be part of color scheme, not profile

### ISSUE THREAD

**Issue by cayos** [microsoft/terminal#3322]
# Changes
I wrote a small script to import Terminal color schemes from VSCode themes. However, there's something I think is unintended design:

The "cursorColor" setting is currently part of the profile, not the color scheme. In my opinion it doesn't make sense, because by changing the color scheme of a given profile, the background color may be similar to the cursor color. Both settings should be coupled to each other for consistency.

# Additional features
It'd be amazing if you guys could implement the few remaining color customization options from VSCode's terminal to reach feature parity. They are:

* terminal.border: The color of the border that separates split panes within the terminal.
* terminal.selectionBackground: The selection background color of the terminal.
* terminalCursor.background: The background color of the terminal cursor. Allows customizing the color of a character overlapped by a block cursor.

**Comment by zadjii-msft** [comment]
Thanks for the report. I believe we have issues for a lot of these already, so lemme link them up:
* "cursor color should be part of the color scheme": #764
* Add a setting to manually set the Pane highlight color #3061
  - I suppose that there's not an issue for separator background in general. I believe we wanted to control that with XAML theming, though we don't really have a proper spec for what that looks like quite yet. @cinnamon-msft might be able to dig up the "theming" issue. It looks to me like we've danced around the idea in #2735, #1337, #3061/#3062, #2994, but never had a comprehensive answer.
* There doesn't seem to currently be a "selection color" issue.
* #1356 tracks wetting a FG/BG for the cursor _in conhost_, but not the terminal. There's also #1203 for "show the character under the cursor" in the Terminal, but again, not exactly what we're looking for here. 

In general, it's really hard for us to track and resolve issues that have a bunch of suggestions in them. I'm going to move selection BG color to it's own issue, cursor bg/fg into #1203, and I'll make an issue for "theming" that will incorporate the pane border BG color.

Thanks for the feedback!
