### ISSUE TITLE
Please add an enhanced git support

### ISSUE THREAD

**Issue by jhueppauff** [microsoft/terminal#3328]
[cmder ](https://cmder.net/) has an amazing git built feature. It will show you the current status of the branch (if it is modified, even with the remote etc... directly in the terminal after the directory path as soon you are in a git backed directory. 

Looks like this:
![image](https://user-images.githubusercontent.com/20532954/67584343-b30c9700-f74d-11e9-91b8-6630108f0e28.png)

It would be awesome to have this feature as well in the new terminal.

**Comment by zadjii-msft** [comment]
That almost sounds more like a _shell_ feature that a _terminal_ feature, right? Does cmder ship its own shell with their terminal? Could we just use the cmder shell within the Terminal?

IIRC there's already Posh-Git for achieving the same functionality in Powershell, as well as various different "powerline" implementations for `bash`, `zsh`, etc

**Comment by jhueppauff** [comment]
cmder is just a console emulator. It can run multiple shells: 
https://github.com/cmderdev/cmder#access-to-multiple-shells-in-one-window-using-tabs

**Comment by zadjii-msft** [comment]
Sure, but they must be configuring the shells to display the git info somehow, unless they're manually injecting the git information into the output from the shell (which seems impossible to me).

This page would seem to indicate that you can actually run the cmder _shell_ in other terminals as well:
https://github.com/cmderdev/cmder/wiki#integrate-cmder-with-other-terminalides

Maybe try setting `commandline` to `cmd.exe /k %CMDER_ROOT%\\vendor\\init.bat`?

**Comment by jhueppauff** [comment]
> Maybe try setting `commandline `to `cmd.exe /k %CMDER_ROOT%\\vendor\\init.bat?`

this works :)
