### ISSUE TITLE
PSReadLine colors and schemes

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#3329]
# Environment

```none
Windows build number: 10.0.18362.0

```

# Steps to reproduce

```
Set-PSReadLineOption -Colors @{
    "Command" = [ConsoleColor]::Yellow
}
```

in scheme change color for  powershell / pwsh .exe
```
            "brightYellow": "#F9F1A5",
```

# Expected behavior

yellow should change the [ConsoleColor]::Yellow   color but does not

**Comment by zadjii-msft** [comment]
I'm having a hard time reproing any bug here. If you change the `brightYellow` property of the powershell profile's color scheme, it definitely updates for me:

![image](https://user-images.githubusercontent.com/18356694/67588655-3b724400-f71c-11e9-8a9c-fa4c8faaeebb.png)

Here I've changed `brightYellow` from it's default value of `#f9f1a5` to `#ff00ff`, and you can see it's updated in the powershell tab.

**Comment by musm** [comment]
The problem is why does `"brightYellow"` and not simply `"Yellow"` change   `[ConsoleColor]::Yellow`

**Comment by musm** [comment]
Is this because `[ConsoleColor]::DarkYellow`  is mean to be changed by   "Yellow" and 
 `[ConsoleColor]::Yellow`  is mean to be changed by  "BrightYellow" ?

**Comment by DHowett-MSFT** [comment]
There's some discussion around color names in #2641. To match more closely with ANSI ECMA-48 standard color names, we're departing from the `ConsoleColor` enum.

**Comment by musm** [comment]
![image](https://user-images.githubusercontent.com/4319522/67590095-17b4fb00-f728-11e9-90c7-16f1daf91550.png)


@DHowett  which  ENUM do you reccomend then when coloring items in powershell and psreadline ?

**Comment by DHowett-MSFT** [comment]
For PowerShell Core (or anything else consuming PSReadline 2), you should prefer to use escape sequences to set your colors -- it's better-supported than `ConsoleColor` _everywhere_.

```powershell
Set-PSReadLineOption -Colors @{
    "Command" = "`e[93m"
}
```

```
Write-Host "`e[96mWSup`e[m"
```

**Comment by musm** [comment]
Ok regardless the names are super confusing, since they don't correspond to the names here https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by DHowett-MSFT** [comment]
I mean, apart from `purple`/`magenta` the Windows Terminal settings _do_ correspond to those names? That's called out in https://github.com/microsoft/terminal/issues/2641#issuecomment-527247390.

ConsoleColor cannot be changed. It was created for a different, Windows-only, world. We're not in that world any longer.

Let's continue the discussion in /dup #2641.
