### ISSUE TITLE
Static tab title...

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3330]
Hi Guys.

I have an profile with ssh.exe which connects to one of my linux boxes. All works fine but i would like to adjust it a little bit.

My problem is that when i connect to that linux box then tab title is automatically changed to 'OpenSSH SSH client". I would like to to keep it as i named it "My linux box".

I tried to use:

            "name" : "My linux box",
            "tabTitle" : "My Linux Box",

in profile config but tab title still changes.

Is there any way of getting rid off dynamically changed tab titles or setting up static tab title which never changes?

Thank you.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by #2645, and is in PR in #2750.

/dup #2645

**Comment by 4k3or3et** [comment]
Thank you guys.

By the way... impressive piece of work that terminal is...

May i ask one more thing out of the topic?

I like to understand what i use best i can.

One thing which i cannot figure out is that why when you specify paths in  "commandline" parameter, to separate folders u need you use / and not \ like in rest of Windows system?

Thanks for any clues in that matter.

**Comment by zadjii-msft** [comment]
@4k3or3et You can definitely use `\` as a path separator, but because the file is a **JSON** file, you need to make sure to escape it properly 😉 `\` is the escape character for JSON files, so you need to use "\\" whenever you want a single `\`.
