### ISSUE TITLE
Add Support for Power Toys Fancy Zones

### ISSUE THREAD

**Issue by contento** [microsoft/terminal#3332]
# Description of the new feature/enhancement
Terminal seems not to play well with Power Toys, that is, the Shift + Move Window doesn't activate [Power Toys Fancy Zones](https://github.com/microsoft/PowerToys/blob/master/src/modules/fancyzones/README.md) 

# Proposed technical implementation details (optional)
Implement move Terminal Window to Fancy Zone [Shift + Left Cursor on Window Bar]

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually a dupe of a bunch of existing issues:

/dup #2689 #2905 #3191
