### ISSUE TITLE
Acrylic effect off when window is not active.

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3336]
Hi guys

When Windows Terminal is not active acrylic effect is gone. In Campbell scheme it simply becomes black. Is that an expected behaviour? If yes, is there any parameter i can use in config to keep acrylic effect on while window is not active?

Thank you.

**Comment by garrlker** [comment]
Unfortunately this is by design.

The system-level policy for all acrylic applications is that only the active/focused window is allowed to display it.

/dup #2326  #1886 #1747 #1505

**Comment by 4k3or3et** [comment]
Thanks guys and sorry for duplicate.

**Comment by DHowett-MSFT** [comment]
@garrlker thanks!
