### ISSUE TITLE
Passing paramter to wt command to open different tab than default

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3339]
Hi Guys

is there a way of passing paramtetr to wt command so Windows Terminal would start with different tab than the default?

For example:

wt {guid}

If not i would like to propose feature request.

Thank you.

**Comment by j4james** [comment]
If I've understood you correctly, I think this is essentially the same feature request as #607.

**Comment by DHowett-MSFT** [comment]
Yep! This is a /dupe of #607. Thanks!
