### ISSUE TITLE
Scrolling speed with mouse is too quick

### ISSUE THREAD

**Issue by sovaska** [microsoft/terminal#3340]
Speed is much quicker than with any of other applications in my Lenovo and Dell laptops. Scrolling speed should be slower, or there should be a way to adjust the speed in configuration.

**Comment by j4james** [comment]
This might be a duplicate of #1066.

**Comment by sovaska** [comment]
Thanks, sounds similar!

**Comment by DHowett-MSFT** [comment]
It sure is! Thanks, James! /dup #1066.
