### ISSUE TITLE
Terminal hangs after second invalid invocation of "start powershel"

### ISSUE THREAD

**Issue by grkramer** [microsoft/terminal#3342]
# Environment

Windows build number: 10.0.18363.0 
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
No

# Steps to reproduce

1. Launch Terminal
2. Open a new cmd tab
3. Type 'start powershel' and then press enter. The misspelling of PowerShell is part of the repro
4. A dialog box pops up indicating that 'powershel' cannot be started. Dismiss the dialog box
5. Type 'start powershel' and then press enter again.

# Expected behavior

The same dialog box appears indicating the error and I can dismiss the dialog and continue using the cmd tab.

# Actual behavior

The cmd tab hangs and there is no dialog box. Ctrl-C does not recover and the only option I've found to exit this state is to close the tab.

**Comment by zadjii-msft** [comment]
@grkramer Are you sure the dialog isn't just appearing _below_ the Terminal window (in the z-order)?
![image](https://user-images.githubusercontent.com/18356694/67689321-29391580-f969-11e9-99bd-14dc720d2e5f.png)

For me, with the acrylic like this, you can see the faint image of the dialog appearing below the terminal. You should be able to alt-tab to the dialog and dismiss it.

**Comment by jantari** [comment]
I can confirm that the second messagebox appears below the terminal.

    Terminal version: 0.6.2951.0
    Windows version: 10.0.19013.1

That's inconvenient but what bothers me way more is that focus is not returned to the terminal after dismissing this messagebox:

1. Open a CMD tab in WT
2. type `start powershel` as per OPs example
3. dismiss the dialog box with ENTER or ESCAPE, if neccessary after alt-tabbing to it
4. press UP-ARROW to get the last command back and correct it or try typing
5. nothing will happen as focus is not returned to the terminal window. If you have acrylic enabled this is also evident by the acrylic effect missing
