### ISSUE TITLE
Title bar won't turn black in dark mode

### ISSUE THREAD

**Issue by Ptheguy** [microsoft/terminal#3349]
# Environment

Windows build number: Windows 10, Version 1903, Build 18362.418
Windows Terminal version (if applicable): 0.6.2951.0

# Steps to reproduce

Set `"requestedTheme": "dark"` in `profile.json`.

# Expected behavior

Before I updated the OS, the title bar used to be black under this theme.

# Actual behavior

After I updated the OS, the title bar is now gray under this theme.

![Capture](https://user-images.githubusercontent.com/39744455/67642294-b5532a80-f8e0-11e9-9a2b-1ef944f98b58.PNG)

**Comment by guibirow** [comment]
I have the same problem, I quite like the new color though, now I can distinguish better which tab is active!

But I would prefer to have the old color (black) and change the inactive tabs color to this new scheme

**Comment by DHowett-MSFT** [comment]
Sorry, we're following the standard WinUI color ramp as of v0.6 to better integrate with the rest of Windows.

We're considering theming support, so please throw your support behind /dup #3327.
