### ISSUE TITLE
Send the same command to all the active tabs within windows terminal

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3352]
# Send the same command to all the active tabs within windows terminal
I hope windows terminal come with a feature that it can send the same command to all the active tabs. 
Let's say we open 4 tabs within terminal,then each tab have a connection to a SSH server. and we want to know the status of the firewall on those server by issue "systemctl status firewalld" . but we want do it in one time. not one by one for each connection in these 4 tabs.

# This feature had been implement in SecureCRT.
Bellow is the steps to send the same command to all active tabs in SecureCRT.

This can be done using the 'Chat Window'.
1. Select 'Chat Window' from the 'View' menu so that the window will be displayed.
2. Then just right click inside the 'Chat Window' and select the 'Send Chat to All Tabs' option in the pop-up menu.
3. Once enabled, any commands entered in the 'Chat Window' will be sent to all tabs when 'Enter' is pressed.

# It will be very handy in daily task if it can be like that.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We're actually already tracking a pretty similar ask over in #2634, so I'm going to close this one as a dupe. 

/dupe #2634
