### ISSUE TITLE
Terminal exits when window is dragged to other screen (with different DPI setting)

### ISSUE THREAD

**Issue by mstevens83** [microsoft/terminal#3355]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0
```

# Steps to reproduce
- Start Windows Terminal
- Drag window to other screen (which happens to run at a different DPI/scaling setting)
- **Terminal exits** :-/

My first screen (on which Terminal initially opened) is set 150% scaling, the second one (on which Terminal dies) is at 100%.

# Expected behavior
Terminal should continue working on other screen.

# Actual behavior
After releasing the drag&drop operation the window briefly (~1s) seems to be usable, but then it just closes.

**Comment by zadjii-msft** [comment]
This sounds awfully similar to #3303 - I'm just going to mark this as a dupe. Thanks!

/dup #3303
