### ISSUE TITLE
Dragging a path from Windows Explorer address bar doesn't work

### ISSUE THREAD

**Issue by mstockman** [microsoft/terminal#3358]
# Environment

```none
Windows build number: Version 10.0.18362.418
Windows Terminal version (if applicable): 0.6.2951.0

Any other software? No
```

# Steps to reproduce
In Windows Explorer, click the yellow folder icon in the address field (next to the path to the folder you're viewing) and attempt to drag it into a Windows Terminal cmd window.

# Expected behavior
The full path should be dropped into the command line at the cursor location, as it does in Windows command prompt.

# Actual behavior
The cursor changes to an international No symbol to indicate that you cannot drop the path onto the terminal window.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is already being tracked by another issue on our repo, so I'm going to close this one as a duplicate. Thanks!

/dup #904
