### ISSUE TITLE
Azure cloud shell on dev build

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#3359]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version: Dev build from commit `634687ba`
```

# Steps to reproduce

Git clone this repo, and run a release build.

# Expected behavior

Cloud shell shows up as a profile.

# Actual behavior

Cloud shell does not show up as a profile.

# Extra info

I'm also running the preview release from the store. It works there, the cloud shell profile shows up and works.

I tried to manually add to the `profiles.json`  file:

````json
{
  "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
  "hidden": false,
  "name": "Azure Cloud Shell",
  "source": "Windows.Terminal.Azure"
}
````

It doesn't work, nothing shows up.

If I add a configuration without a `source`, like so:

````json
{
    "acrylicOpacity" : 0.6,
    "closeOnExit" : false,
    "colorScheme" : "Vintage",
    "commandline" : "Azure",
    "connectionType" : "{d9fcfdfa-a479-412c-83b7-c5640e61cd62}",
    "cursorColor" : "#FFFFFF",
    "cursorShape" : "bar",
    "fontFace" : "Consolas",
    "fontSize" : 10,
    "guid" : "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "historySize" : 9001,
    "icon" : "ms-appx:///ProfileIcons/{b453ae62-4e3d-5e58-b989-0a998ec441b8}.png",
    "name" : "Azure Cloud Shell",
    "padding" : "0, 0, 0, 0",
    "snapOnInput" : true,
    "startingDirectory" : "%USERPROFILE%",
    "useAcrylic" : true
}
````

Then the profile shows up, but it starts blank. This is after I start it:

![image](https://user-images.githubusercontent.com/334958/67712668-3115ab80-f9a3-11e9-870a-5dfde72d9eff.png)

If I add a `source` attribute to it, it disappears from the profiles dropdown.

Is there a dependent executable that I should have added to the destination directory, or something like that? What am I missing?

**Comment by gmsantos** [comment]
I can reproduce this issue on dev build as well.

**Comment by DHowett-MSFT** [comment]
If you launch that session, you'll see that it doesn't work. You'll need to provide your own Azure client ID (in AzureClientID.h). This is by design.

**Comment by DHowett-MSFT** [comment]
(Thanks for the report!)

**Comment by giggio** [comment]
> If you launch that session, you'll see that it doesn't work. You'll need to provide your own Azure client ID (in AzureClientID.h). This is by design.

@DHowett how do we do that? How does the build in the store does it?
