### ISSUE TITLE
High GPU usage(~100%) when terminal is in the foreground

### ISSUE THREAD

**Issue by vineethrp** [microsoft/terminal#3360]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19008.1000]
Windows Terminal version : 0.6.2951
Lenovo Thinkpad P1 :
    Intel Xeon E-2176M
    Hybrid Graphics with Intel P630 and Nvidia Quadro P2000
    64GB RAM
Any other software?
```

# Steps to reproduce
Very easy to reproduce. Have the performance monitor open and bring terminal to foreground. The GPU usage spikes.
I noticed this issue because, mouse becomes laggy and UI is almost unusable.

I am pasting two screen shots when the terminal goes foreground and when the terminal goes background

## High GPU usage when the terminal is foreground
![terminal_highcpu](https://user-images.githubusercontent.com/808507/67729628-30434080-f9c8-11e9-90b2-2c7c830876b1.png)

## Low GPU usage when the terminal goes background
![terminal_lowcpu](https://user-images.githubusercontent.com/808507/67729634-35a08b00-f9c8-11e9-8b29-0887781578e7.png)

# Expected behavior
A relatively idle terminal should not be consuming 100% GPU and there by freezing the UI

# Actual behavior
 UI lockups due to 100% GPU

**Comment by DHowett-MSFT** [comment]
If you set `useAcrylic` to `false`, does it help?

**Comment by vineethrp** [comment]
> If you set `useAcrylic` to `false`, does it help?

It helped :-). The usage came down drastically to 10-20%
Also one more data point: The UI interactivity is even worse when we have a chrome tab playing video in the background of the terminal. Looks like the implementation of  transparency is the problem. After disabling transparency, UI interactivity is more or less back to normal.

**Comment by DHowett-MSFT** [comment]
Thanks for letting us know! We will make sure this feedback ends up with the appropriate people.
Acrylic transparency is not recommended for use on large windows because of the toll it takes on the GPU, but our community has asked for the option :smile:
