### ISSUE TITLE
AzModule with PowerShell

### ISSUE THREAD

**Issue by ribeiry** [microsoft/terminal#3363]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

- Az Component Version ---> AZ 2.5.0 and AZ 2.8.0;
- PowerShell Version ----> 5.1.18362.145
- Windows Terminal Version ----->0.6.2951.0
- Windows Version ------->10.0.18362

Any other software?
```

# Steps to reproduce
I Install the Az Component(AZ 2.5.0 and AZ 2.8.0) in my PowerShell  and i run the command ``Connect-AzAccount`` .

# Expected behavior

The Expected behavior is run command to open website microsoft.com/deviceslogin or open a webpage to log in my account Azure.I opened the powershell window and repeated the process and the result is login with sucess in  my Azure Account

# Actual behavior
The Terminal is processing in process about 10 mint, and no ansewered

**Comment by DHowett-MSFT** [comment]
Sorry, can you share in more detail what's wrong? If there's a login window that should be presented, it might be behind your terminal. If it should be printing out a prompt, that shouldn't be terminal's fault.

**Comment by ribeiry** [comment]
HI @DHowett-MSFT, so sorry, i did the test and really error isn't the prompt, i updated my az component and it's work now, so once again sorry.
