### ISSUE TITLE
Add mouse support

### ISSUE THREAD

**Issue by cascer1** [microsoft/terminal#3364]
# Description of the new feature/enhancement

Currently it seems like the terminal doesn't pass mouse events to WSL (for example to select text in visual mode in vim). I would like to be able to continue using my mouse inside WSL.

**Comment by zadjii-msft** [comment]
Thanks for the report! Mouse input doesn't work correctly in the Windows Terminal currently. That's being tracked by a pair of issues: #545 and #376. Once _both_ of those are done, mouse input will work in the Terminal again.

/dup #376 
/dup #545  #2727 #2344 #2364 #2056 #1975
