### ISSUE TITLE
Split one window into multiple windows

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3365]
# Implement a feature that split one window into multiple windows

Usually , when we start a terminal , and make a connection ,then the whole connection will occupy the whole window, I hope we can split one window into multiple ,then we can start connection in each sub window , then we can watch multiple connection at the same time. cool.

Maybe a picture is much more clear to express what I want ,
See bellow:
![slipt](https://user-images.githubusercontent.com/36788337/67753291-769faa80-fa6f-11e9-8795-a9a09651183c.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We actually already support multiple splits ("panes") within the terminal - check out our megathread #1000 which is tracking all the remaining work to polish panes off. 

/dup #1000
