### ISSUE TITLE
Inconsistent `ls` colors given `$LS_COLORS`

### ISSUE THREAD

**Issue by Ptheguy** [microsoft/terminal#3372]
# Environment

Windows build number: Windows 10, Version 1903, Build 18362.418
Windows Terminal version (if applicable): 0.6.2951.0

# Steps to reproduce

I'm not sure if this is exactly reproducible, simply because it happens erratically on my machine. There is no consistency behind this bug. But, there is inconsistency between `$LS_COLORS` and what the terminal shows.

![Capture](https://user-images.githubusercontent.com/39744455/67808257-b913b800-fa6c-11e9-9f1e-fa1fac266a08.PNG)

# Expected behavior

The `ls` command respects the colors set forth by the `$LS_COLORS` flag. 

# Actual behavior

There is wide inconsistency between what `$LS_COLORS` sets and what color is displayed via `ls`. Pay attention to the fact that both `.png` files have different colors, and `.tif` does not respond to the coloring set forth by `$LS_COLORS`.

**Comment by DHowett-MSFT** [comment]
Those files are probably being colored differently because they're `+x`. Your `LS_COLORS` coloring for executable files (`ex`) is `ex=01;32` (bright green). `ex` always wins out over base coloring for normal files.

Incidentally, this is not a Windows Terminal, Console _or_ WSL issue. :smile:
