### ISSUE TITLE
can't read and write japanese(euc-jp)

### ISSUE THREAD

**Issue by pb-nguyenvanlam** [microsoft/terminal#3373]
# Environment

```none
18362.449: [run `[Environment]::OSVersion: 1903]
Windows Terminal version (if applicable):V0.6

Any other software?
```

# Steps to reproduce
my project just use euc-jp encode
powerShell command:
chcp 20932
but can't read text for euc-jp encode
and i can't change to write japanese

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
Writing Japanese: #2213
Reading Japanese: Can you share a screenshot, or an example application that you are seeing a problem with? We cannot troubleshoot this. Sorry.

**Comment by pb-nguyenvanlam** [comment]
![aaa](https://user-images.githubusercontent.com/52989180/67908346-8c6fb580-fbbe-11e9-894a-eb607c3262fd.png)
![set](https://user-images.githubusercontent.com/52989180/67908354-91346980-fbbe-11e9-9ddc-eba110386407.png)

i connect to ubuntu server version 16.04, and  my ubuntuOS is use euc-jp encode.

**Comment by DHowett-MSFT** [comment]
This is a bug with [win32-openssh](https://github.com/PowerShell/Win32-OpenSSH), the Windows OpenSSH client. It resets your codepage to UTF-8. I cannot move your issue to that repository, can you help me? Thanks!
