### ISSUE TITLE
Can I replace windows 7 console with this?

### ISSUE THREAD

**Issue by determin1st** [microsoft/terminal#3375]

**Comment by electronic-dk** [comment]
@determin1st I assume that by "console" you mean cmd or powershell, sorry if I'm mistaken. Windows Terminal is not a shell in itself, but rather a front for existing shells (powershell, cmd, bash, etc) so it's not a replacement for them. Also, AFAIK, it requires the latest SDK features (e.g. XAML islands) so it will only work on the latest Windows build (1903 at the time of writing).
