### ISSUE TITLE
Reconcile UTF-8 behavior in `utf8ToWideCharParser.cpp`

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#3378]
Outcomes from #3320... (this is all related to `utf8ToWideCharParser.cpp`)

1. When we encounter obviously invalid UTF-8 (wrong number of continuation bytes for a lead, lead without continuations, etc.), we straight up discard them from the stream in `_InvolvedParse`.
- We need to consider replacing them with U+FFFD or having the option to do so.
2. When we get not-obviously invalid UTF-8 (non-minimal forms like 0xC0 0x80 for null), we didn't detect and remove those.
- We now (as of #3320) replace them with U+FFFD, though that's inconsistent with eating them above. This was chosen as a quick fix to be easy to port into the Windows 20H1 cycle during our bug fixing phase.
- We should reconcile this difference with part 1 above (being able to toggle both of them on or off)
3. We seem to need to walk though this entire sequence multiple to many times inside our code and then again inside the kernel as the `MultiByteToWideChar` call eventually thunks to `RtlUTF8ToUnicodeN`.
- The reason we have to walk through it ourselves is to attempt to preserve partial sequences that just happen to fall across a call boundary. If the client application emits one UTF-8 character at a time, we still want to aggregate them and turn it into the correct result if they properly gave us "3-sequence-lead, continuation, continuation" in 3 separate calls. `MultiByteToWideChar` will not do this. It will either error (MB_ERR_INVALID_CHARS) or replace (U+FFFD).
- The call to `RtlUTF8ToUnicodeN` is a kernel syscall on a hot path in our codebase that is quite probably slowing us down. 

Given that we're already doing almost everything required to understand the UTF-8 sequence such that we can store partials across calls, perhaps we just add the final two steps of:
1. Detecting non-minimal forms of UTF-8 as invalid
2. Just doing the conversion to UTF-8 ourselves in user mode as it's just an algorithmic translation and we're already most of the way there bit twiddling to identify sequence length and continuations

This issue represents investigating:
1. Is there a serious performance detriment to the kernel syscall for UTF-8 conversion that will start biting us especially hard as more and more things need UTF-8 <--> UTF-16?
2. How hard is it for us to detect the non-minimal forms?
3. Can we just finish the algorithm on our side in user mode relatively simply?
4. Can we decide on a replacement strategy and make it consistent between clearly invalid sequences and non-minimal forms?

**Comment by DHowett-MSFT** [comment]
We also have half of a UTF-8 parser in UTF8OutputPipeReader, where it's used for detecting valid but partial encoded characters and shuffling them to the beginning of a string for the next parse cycle. It's unnecessarily coupled with doing a `ReadFile`. It seems like a solution to `utf8ToWideCharParser` would also be able to unify our disparate UTF-8 parsers.

**Comment by german-one** [comment]
@miniksa @DHowett-MSFT 

I spent a little time over Xmas to transpose my own UTF-8 <--> UTF-16 functions that I wrote in C into C++. I'm afraid you will still discern the C origin 😊 I'll provide them here first in order to get feedback
* if this is close to what you're looking for
* if this has the slightest chance to pass a code review with all the magic numbers and static_casts

If so, they could probably land in `types/convert.cpp` and be used instead of `MultiByteToWideChar` and `WideCharToMultiByte`.

Also it should be relatively easy to write a functor class based on `UTF8OutputPipeReader` which just detects partials at the string end, caches them, and completes them at the next call. The conversion functions and the cache class might be either used directly or rather for the composition of more specialized classes like `Utf8ToWideCharParser` ...

However, the `U8ToU16` and `U16ToU8` first:
```
// Routine Description:
// - Takes a UTF-8 string and performs the conversion to UTF-16. NOTE: The function relies on getting complete UTF-8 characters at the string boundaries.
// Arguments:
// - u8Str - string_view of the UTF-8 string to be converted
// - u16Str - reference to the resulting UTF-16 string
// - discardInvalids - if `true` invalid characters are discarded instead of replaced with U+FFFD, default is `false`
// Return Value:
// - S_OK          - the conversion succeded without any change of the represented code points
// - E_FAIL        - the incoming string contained at least one invalid character
// - E_OUTOFMEMORY - the function failed to allocate memory for the resulting string
// - E_ABORT       - the resulting string length would exceed the max_size and thus, the conversion was aborted before the conversion has been completed
// - E_UNEXPECTED  - an unexpected error occurred
[[nodiscard]] HRESULT U8ToU16(const std::string_view u8Str, std::wstring &u16Str, bool discardInvalids = false) noexcept
{
  constexpr const BYTE contBegin{ 0x80u }; // usual begin of the range of continuation Bytes
  constexpr const BYTE contEnd{ 0xBfu }; // usual end of the range of continuation Bytes
  constexpr const UINT32 unicodeReplacementChar{ 0xFFFDu }; // Unicode Replacement Character
  HRESULT hRes{ S_OK };

  try
  {
    u16Str.clear();

    if (u8Str.empty())
    {
      return hRes;
    }

    auto it8{ u8Str.cbegin() };
    auto end8{ u8Str.cend() };

    while (it8 < end8)
    {
      UINT32 codePoint{ unicodeReplacementChar }; // default

      // *** convert UTF-8 to a code point ***
      // valid single bytes
      // - 00..7F
      if (static_cast<BYTE>(*it8) <= 0x7Fu)
      {
        codePoint = static_cast<BYTE>(*it8++);
      }
      // valid two bytes
      // - C2..DF | 80..BF (first byte 0xC0 and 0xC1 invalid)
      else if (static_cast<BYTE>(*it8) >= 0xC2u && static_cast<BYTE>(*it8) <= 0xDFu)
      {
        unsigned cnt{ 1u };
        if ((it8 + 1) < end8 && static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= contEnd)
        {
          ++cnt;
          codePoint = ((static_cast<BYTE>(*it8) ^ 0x000000C0u) << 6u) |
                      (static_cast<BYTE>(it8[1]) ^ 0x00000080u);
        }
        else
        {
          hRes = E_FAIL;
        }

        it8 += cnt;
      }
      // valid three bytes
      // - E0     | A0..BF | 80..BF
      // - E1..EC | 80..BF | 80..BF
      // - ED     | 80..9F | 80..BF
      // - EE..EF | 80..BF | 80..BF
      else if (static_cast<BYTE>(*it8) >= 0xE0u && static_cast<BYTE>(*it8) <= 0xEFu)
      {
        unsigned cnt{ 1u };
        if ((it8 + 1) < end8 &&
            (( // E0     | *A0*..BF
                 static_cast<BYTE>(*it8) == 0xE0u &&
                 static_cast<BYTE>(it8[1]) >= 0xA0u && static_cast<BYTE>(it8[1]) <= contEnd) ||
             ( // E1..EC | 80..BF
                 static_cast<BYTE>(*it8) >= 0xE1u && static_cast<BYTE>(*it8) <= 0xECu &&
                 static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= contEnd) ||
             ( // ED     | 80..*9F*
                 static_cast<BYTE>(*it8) == 0xEDu &&
                 static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= 0x9Fu) ||
             ( // EE..EF | 80..BF
                 static_cast<BYTE>(*it8) >= 0xEEu && static_cast<BYTE>(*it8) <= 0xEFu &&
                 static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= contEnd)))
        {
          ++cnt;
          if ((it8 + 2) < end8 && static_cast<BYTE>(it8[2]) >= contBegin && static_cast<BYTE>(it8[2]) <= contEnd)
          {
            ++cnt;
            codePoint = ((static_cast<BYTE>(*it8) ^ 0x000000E0u) << 12u) |
                        ((static_cast<BYTE>(it8[1]) ^ 0x00000080u) << 6u) |
                        (static_cast<BYTE>(it8[2]) ^ 0x00000080u);
          }
        }

        it8 += cnt;
        if (cnt < 3u)
        {
          hRes = E_FAIL;
        }
      }
      // valid four bytes
      // - F0     | 90..BF | 80..BF | 80..BF
      // - F1..F3 | 80..BF | 80..BF | 80..BF
      // - F4     | 80..8F | 80..BF | 80..BF
      else if (static_cast<BYTE>(*it8) >= 0xF0u && static_cast<BYTE>(*it8) <= 0xF4u)
      {
        unsigned cnt{ 1u };
        if ((it8 + 1) < end8 &&
            (( // F0     | *90*..BF
                 static_cast<BYTE>(*it8) == 0xF0u &&
                 static_cast<BYTE>(it8[1]) >= 0x90u && static_cast<BYTE>(it8[1]) <= contEnd) ||
             ( // F1..F3 | 80..BF
                 static_cast<BYTE>(*it8) >= 0xF1u && static_cast<BYTE>(*it8) <= 0xF3u &&
                 static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= contEnd) ||
             ( // F4     | 80..*8F*
                 static_cast<BYTE>(*it8) == 0xF4u &&
                 static_cast<BYTE>(it8[1]) >= contBegin && static_cast<BYTE>(it8[1]) <= 0x8Fu)))
        {
          ++cnt;
          if ((it8 + 2) < end8 && static_cast<BYTE>(it8[2]) >= contBegin && static_cast<BYTE>(it8[2]) <= contEnd)
          {
            ++cnt;
            if ((it8 + 3) < end8 && static_cast<BYTE>(it8[3]) >= contBegin && static_cast<BYTE>(it8[3]) <= contEnd)
            {
              ++cnt;
              codePoint = ((static_cast<BYTE>(*it8) ^ 0x000000F0u) << 18u) |
                          ((static_cast<BYTE>(it8[1]) ^ 0x00000080u) << 12u) |
                          ((static_cast<BYTE>(it8[2]) ^ 0x00000080u) << 6u) |
                          (static_cast<BYTE>(it8[3]) ^ 0x00000080u);
            }
          }
        }

        it8 += cnt;
        if (cnt < 4u)
        {
          hRes = E_FAIL;
        }
      }
      else
      {
        hRes = E_FAIL;
        ++it8;
      }

      // *** convert the code point to UTF-16 ***
      if (codePoint != unicodeReplacementChar || discardInvalids == false)
      {
        if (codePoint < 0x00010000u)
        {
          u16Str += static_cast<WCHAR>(codePoint);
        }
        else
        {
          codePoint -= 0x00010000u;
          u16Str += { static_cast<WCHAR>(0x0000D800u + ((codePoint >> 10u) & 0x000003FFu)),
                      static_cast<WCHAR>(0x0000DC00u + (codePoint & 0x000003FFu)) };
        }
      }
    }
  }
  catch (std::length_error&)
  {
    return E_ABORT;
  }
  catch (std::bad_alloc&)
  {
    return E_OUTOFMEMORY;
  }
  catch (...)
  {
    return E_UNEXPECTED;
  }

  return hRes;
}

// Routine Description:
// - Takes a UTF-16 string and performs the conversion to UTF-8. NOTE: The function relies on getting complete UTF-16 characters at the string boundaries.
// Arguments:
// - u16Str - wstring_view of the UTF-16 string to be converted
// - u8Str - reference to the resulting UTF-8 string
// - discardInvalids - if `true` invalid characters are discarded instead of replaced with U+FFFD, default is `false`
// Return Value:
// - S_OK          - the conversion succeded without any change of the represented code points
// - E_FAIL        - the incoming string contained at least one invalid character
// - E_OUTOFMEMORY - the function failed to allocate memory for the resulting string
// - E_ABORT       - the resulting string length would exceed the max_size and thus, the conversion was aborted before the conversion has been completed
// - E_UNEXPECTED  - an unexpected error occurred
[[nodiscard]] HRESULT U16ToU8(const std::wstring_view u16Str, std::string &u8Str, bool discardInvalids = false) noexcept
{
  constexpr const UINT32 unicodeReplacementChar{ 0xFFFDu };
  HRESULT hRes{ S_OK };

  try
  {
    u8Str.clear();

    if (u16Str.empty())
    {
      return hRes;
    }

    auto it16{ u16Str.cbegin() };
    auto end16{ u16Str.cend() };

    while (it16 < end16)
    {
      UINT32 codePoint{ unicodeReplacementChar }; // default

      // *** convert UTF-16 to a code point ***
      if (*it16 >= 0xD800u && *it16 <= 0xDBFFu) // range of high surrogates
      {
        const UINT32 high{ *it16++ };
        if (it16 < end16 && *it16 >= 0xDC00u && *it16 <= 0xDFFFu) // range of low surrogates
        {
          codePoint = (high << 10u) + *it16++ - 0x035FDC00u;
        }
        else
        {
          hRes = E_FAIL;
        }
      }
      else if (*it16 >= 0xDC00u && *it16 <= 0xDFFFu) // standing alone low surrogates are invalid
      {
        hRes = E_FAIL;
        ++it16;
      }
      else
      {
        codePoint = *it16++;
      }

      // *** convert the code point to UTF-8 ***
      if (codePoint != unicodeReplacementChar || discardInvalids == false)
      {
        if (codePoint < 0x00000080u)
        {
          u8Str += static_cast<char>(codePoint);
        }
        else if (codePoint < 0x00000800u)
        {
          u8Str += { static_cast<char>((codePoint >> 6u & 0x1Fu) | 0xC0u),
                     static_cast<char>((codePoint & 0x3Fu) | 0x80u) };
        }
        else if (codePoint < 0x00010000u)
        {
          u8Str += { static_cast<char>((codePoint >> 12u & 0x0Fu) | 0xE0u),
                     static_cast<char>((codePoint >> 6u & 0x3Fu) | 0x80u),
                     static_cast<char>((codePoint & 0x3Fu) | 0x80u) };
        }
        else
        {
          u8Str += { static_cast<char>((codePoint >> 18u & 0x07u) | 0xF0u),
                     static_cast<char>((codePoint >> 12u & 0x3Fu) | 0x80u),
                     static_cast<char>((codePoint >> 6u & 0x3Fu) | 0x80u),
                     static_cast<char>((codePoint & 0x3Fu) | 0x80u) };
        }
      }
    }
  }
  catch (std::length_error&)
  {
    return E_ABORT;
  }
  catch (std::bad_alloc&)
  {
    return E_OUTOFMEMORY;
  }
  catch (...)
  {
    return E_UNEXPECTED;
  }

  return hRes;
}
```

**Comment by miniksa** [comment]
> @miniksa @DHowett-MSFT
> 
> I spent a little time over Xmas to transpose my own UTF-8 <--> UTF-16 functions that I wrote in C into C++. I'm afraid you will still discern the C origin 😊 I'll provide them here first in order to get feedback
> 
> * if this is close to what you're looking for
> * if this has the slightest chance to pass a code review with all the magic numbers and static_casts
> 
> If so, they could probably land in `types/convert.cpp` and be used instead of `MultiByteToWideChar` and `WideCharToMultiByte`.
> 
> Also it should be relatively easy to write a functor class based on `UTF8OutputPipeReader` which just detects partials at the string end, caches them, and completes them at the next call. The conversion functions and the cache class might be either used directly or rather for the composition of more specialized classes like `Utf8ToWideCharParser` ...
> 
> Edit: Nevermind it's in PR #4093 wich should make it easier to comment 🙂
> BTW Happy New Year!

Oooh. I am excited for this. Thank you very much! I'll put it on my list to look at.

**Comment by german-one** [comment]
Thanks for your interest @miniksa !
I'm struggling to think out loud because I guess `Utf8ToWideCharParser` became a good friend, but ... if you guys like my implementation then we are only a few updated lines away to supersede `Utf8ToWideCharParser`.

**Comment by DHowett-MSFT** [comment]
@miniksa do the changes as merged fulfill the brief for this bug?

**Comment by miniksa** [comment]
> @miniksa Michael Niksa FTE do the changes as merged fulfill the brief for this bug?

Close enough.

I think we proved that we can't do it faster in user and we now have a way to reconcile them thanks to @german-one's utility functions. And it's been unified in the major places. So I believe we're good.

**Comment by german-one** [comment]
@miniksa Actually I left two questions in the PR. One was if it really closes this issue (which is now answered), and the other one was if we still need `utf8ToWideCharParser` in the code base or if I should commit its removal.

BTW You encouraged me to write extensions `au16` and `u16a`. I'm already about to implement them 🙂
