### ISSUE TITLE
Can not use 'rz' & 'sz'

### ISSUE THREAD

**Issue by FIGHTING-TOP** [microsoft/terminal#3383]
![](https://user-images.githubusercontent.com/22701388/67914239-7d8f0000-fbca-11e9-931d-8bda1ffeffe5.png)

**Comment by FIGHTING-TOP** [comment]
![image](https://user-images.githubusercontent.com/22701388/67914239-7d8f0000-fbca-11e9-931d-8bda1ffeffe5.png)

**Comment by zadjii-msft** [comment]
Please make sure to search before filing new issues 😊

This is /dup #1999 #1602 #2229 #2769

**Comment by lonnywong** [comment]
https://trzsz.github.io/ssh supports [trzsz](https://github.com/trzsz/trzsz)  ( trz / tsz ), similar to rz / sz.
