### ISSUE TITLE
Word-by-word movement doesn't work in Cooked Read over conpty

### ISSUE THREAD

**Issue by srv-code** [microsoft/terminal#3386]
Hi developers,
I really appreciate the effort spent to develop the most awaited application in Windows. I really want to see it come out of beta as a final product as soon as possible.

My suggestions  for Windows Terminal:
1. Atleast provide all the basic text editing capabilities like the word-by-word cursor navigation using Ctrl+\<navigation-key-left\>|\<navigation-key-right\> (Already present in cmd.exe).
2. Provide the tab re-positioning capability, by dragging tab using the mouse.
3. Text font looks little bold (a difference noticed in comparison to cmd font even after keeping the same font properties).
4. Full-screen capability (should have already been there).
5. Tab switcher pop-up like in other editor applications (e.g. in Visual Studio Code editor when pressed Ctrl+TAB).
6. Auto-complete feature like in the macOS iTerm.
7. Add "Open Windows terminal here" to Windows File Explorer right-click context menu.
8. Support for transparency also like in cmd.exe or wsl.exe.

Thank you. Hope I get to see atleast some of the requested features/suggestions if not all.

Keep doing the awesome work!

**Comment by zadjii-msft** [comment]
So for the record, we generally like to avoid giant issues with multiple issues reported like this one. It makes triaging and tracking the individual component issues much harder. Plus, there are already issues tracking some of the things you've mentioned here:

1. This one actually _doesn't_ have an issue, so I'm leaving this open for **only this issue**
2. This is #443
3. I'm moving this discussion to #3388
4. #531
5. I'm moving this discussion to #3389

**Comment by zadjii-msft** [comment]
(back on topic)

I've definitely noticed this in tmux with cmd.exe previously, so I'm thinking this is a conpty bug. We're probably not decoding Ctrl+Arrow keypresses exactly correctly.

Now that I'm thinking on it, maybe this is related to #2397?

**Comment by zadjii-msft** [comment]
@srv-code I see that you updated your original post with additional requests, _after_ I said that we don't want people filing issues with multiple requests in them. I'm not going to address _any_ of those requests in this thread, please search for duplicates and file additional issues so that we can address each suggestion individually. (spoiler: there are already issues present for those suggestions.)

We're using this thread currently to track "Word-by-word movement doesn't work in Cooked Read over conpty", which is the technical reason that "basic text editing capabilities like the word-by-word cursor navigation using Ctrl+<navigation-key-left>|<navigation-key-right> (Already present in cmd.exe)." doesn't work in the Windows Terminal.

**Comment by srv-code** [comment]
What is the current progress on this issue " Word-by-word movement doesn't work in Cooked Read over conpty"?

**Comment by srv-code** [comment]
What is the current progress on this issue "Word-by-word movement doesn't work in Cooked Read over conpty"? Can I expect this feature in the v1.0 release? It means a lot to me to be able to navigate naturally as in a text editor without jamming through my navigation keys. @zadjii-msft

**Comment by DHowett-MSFT** [comment]
You will know there is progress on the issue when you see new comments or that it is closed. Right now it is in the “Terminal v1.0” milestone, which means that we want to fix it before v1.0.

**Comment by srv-code** [comment]
> You will know there is progress on the issue when you see new comments or that it is closed. Right now it is in the “Terminal v1.0” milestone, which means that we want to fix it before v1.0.

Thank you for your response.

**Comment by srv-code** [comment]
Hi! The main issue (Atleast provide all the basic text editing capabilities like the word-by-word cursor navigation using Ctrl+<navigation-key-left>|<navigation-key-right> (Already present in cmd.exe)) seems to be working with the latest update (version: 0.7.3291.0) along with many other additions (e.g. ability to go full screen etc.). 
I don't know if the fix was because of this thread or from someone else but I'm glad that this happened. Thank you for listening! :)

**Comment by zadjii-msft** [comment]
Since this seems to be resolved, I'm closing this. I don't really know what commit fixed it. It also seems to be fixed in inbox conhost, so maybe it was never broken in conpty - it might have been a Terminal bug. Regardless, since it's gone, I'm closing this.
