### ISSUE TITLE
Renaming tabs with double-click

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [microsoft/terminal#3387]
# Description of the new feature/enhancement
It would be really nice to be able to rename tabs by just double-clicling them and setting new title in some kind of text-box. This name replaces original title and stays until tab closed or renamed again.  

This feature is very useful when working with multiple similar tabs like many ssh connections to different servers or tailing multiple logs, etc. Quite often it's one-time sessions and there is no reason to make custom profile for them. Example - hackathon event when you work with a lot of terminal tabs but when it's finished - you never use it again. 

For example i use this very feature in IntelliJ IDEs (PyCharm, PhpStorm, etc) all the time.

**Comment by zadjii-msft** [comment]
This is a good idea! In fact, we've already got another thread on this topic, though I don't think we ever brought up the "double-click" to rename. I'll make sure to add that to the original discussion.

/dup #1079

Thanks!

**Comment by Vasiliy-Bondarenko** [comment]
yep, i see a dupe now. but you are right - double-click is important part of the beauty of this feature. little thing like this make a difference for tools we use so much as terminal :))
