### ISSUE TITLE
Tab switcher pop-up like VSCode

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3389]
From @srv-code in #3386:

> Tab switcher pop-up like in other editor applications (e.g. in Visual Studio Code editor when pressed Ctrl+TAB).

It's quite impossible for me to grab a screenshot of this in action, but it's a little dialog that appears with each of the tab titles in it, and lets you up/down arrow through them.

This kinda reminds me of the "window switcher" (not sure if that's the correct name) in `tmux`: (on the right)

![image](https://user-images.githubusercontent.com/18356694/67951521-a955ba00-fbb9-11e9-9e61-ba514aef6c3d.png)
![image](https://user-images.githubusercontent.com/18356694/67951532-b4104f00-fbb9-11e9-9187-c54d1502a663.png)

which lets you not only switch tabs, but directly to a child pane, and can even give you a preview (when the window is big enough)

**Comment by jantari** [comment]
Visual Studio Code screenshot:

![vscode_fileswitcher](https://user-images.githubusercontent.com/25607767/68248003-467e7b80-001c-11ea-9e3f-ab4967b6c1fd.png)

I grabbed it using the delayed snip feature of the Snip and Sketch app, but the old Snipping tool can do it too:

![snipandsketch](https://user-images.githubusercontent.com/25607767/68248080-6c0b8500-001c-11ea-97c7-4e59782fbf33.png)

**Comment by DHowett-MSFT** [comment]
This was mentioned as part of #973, should we track it separately?

**Comment by zadjii-msft** [comment]
@jantari thanks for the screenshots <3

Honestly maybe? I'm not sure that #973 _necessitates_ a UI.

IMO, this UI could be used in both MRU tab/pane switching order, but also in in-order (left/right) switching order. If we determine that MRU switching order is impossible w/o this dialog, then sure lets collapse the threads, but for now they seem like reasonable separate requests.

**Comment by zadjii-msft** [comment]
Hey so I was crawling through the backlog, and I think I came across a duplicate of this suggestion:

Feature Request: An advanced tab switcher #1502 

I'm gonna move our screenshots and discussion to that thread. Thanks!

/dupe #1502
