### ISSUE TITLE
Run Windows Terminal as Administrator at startup

### ISSUE THREAD

**Issue by Melandel** [microsoft/terminal#3390]
**Edit:** By startup, I mean _**Windows Operating System** startup_.

# Description of the new feature/enhancement

As a user who works primarily with the terminal,

I want Windows Terminal to offer me a way of running it as Administrator at Windows startup

So that I can start working instantly after logging in

# Additional Notes
* I tried setting `C:\Users\me\AppData\Local\Microsoft\WindowsApps\wt.exe` with "right click > Properties > Compatibility > Run this program as Administrator" but it didn't make it run as Administrator (I could confirm by renaming folders in the `Program Files` folder)
* I tried setting `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe` as well, but it didn't make Windows Terminal run as Administrator.
* Given the two settings above, I tried setting `pwsh.exe` for being run as administrator, but
  * when running Windows Terminal (set up for being run as Administrator through its Properties), it opens then immediately closes.
  * when manually running Windows Terminal as Administrator (right click > run as Administrator), it works.

# Proposed technical implementation details
Grant access to an exe file that we can **effectively** "right click > Properties > Compatibility > Run this program as Administrator".

**Comment by akulbe** [comment]
There are two ways that I know of, to start the Terminal as administrator, _right now_. 

1. Hold down Ctrl+Shift when you click the Terminal icon on your taskbar.
2. See screenshot. Right-click on WT icon (1), right-click on "Windows Terminal (preview)" (2), left-click on "Run as administrator."
![wt_run_as_admin](https://user-images.githubusercontent.com/123279/67959747-6e9e5280-fbb6-11e9-81ad-155cc0e62a43.png)

**Comment by Melandel** [comment]
Thank you for your comment.

I meant machine startup, as in when you boot your machine, and programs run automatically, not startup as is when I run Windows Terminal. I edited the original post. 

Thanks for pointing out this ambiguity!

**Comment by DHowett-MSFT** [comment]
This is something we can't do with our current architecture. Thanks for the request!
