### ISSUE TITLE
[Code Health] Use SaferCPlusPlus to reduce memory usage/ violations

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#3395]
# Description of the new feature/enhancement

 "SaferCPlusPlus" is essentially a collection of safe data types intended to facilitate memory and data race safe C++ programming. This library is intended to work with and be complimentary to the Core Guidelines lifetime checker over its various stages of development and availability. (Including situations where the lifetime checker is not available at all.)

# A clear and concise description of what the problem is that the new feature would solve. 

See the rest of the README for the benefits as well usage examples: https://github.com/duneroadrunner/SaferCPlusPlus/blob/master/README.md

# Proposed technical implementation details (optional)
Include the necessary headers as described in the README.

# A clear and concise description of what you want to happen.

A more memory safe conhost, conpty, and Terminal.

**Comment by DHowett-MSFT** [comment]
Hey there! Thanks for the request and the idea, but it's important for us to remain close to the [VC++ STL](https://github.com/microsoft/stl). I agree that memory and data race safety would be an _awesome_ thing to add, especially as "close-to-drop in replacements", but I think that request is better made against the upstream STL.

Sorry!

**Comment by WSLUser** [comment]
I think the idea is to use only the headers you need to save on performance. Implementing at STL is great idea but that would mean having all headers added. I'm not sure that's what we want, especially as it does take away some dangerous behaviors for some of the std calls. I'd say it's more likely to get traction with gsl but they follow upstream and the upstream isn't really interested in picking it up, hence why it's "complimentary" to Core Guidelines. 

So this boils down into two paths: 

1) We get STL to adopt it and potentially break any number of customer workflows 

or 

2) We implement it at this project and as we have a fallback "legacy" mode for conhost, we don't have to worry as much about breaking workflows. As it's mostly drop-in replacements, the biggest hurdle would determining which headers we need and which ones we don't.

**Comment by WSLUser** [comment]
https://github.com/microsoft/STL/issues/241 filed for tracking.

**Comment by WSLUser** [comment]
Not sure if noticed but that issue was closed. I had high suspicion it might be. I found an issue for adopting at the iso guidelines repo but it hasn't been looked at in over a year. So for now, I'd think this project should adopt it as it implements best practice and requires not much to start using.
