### ISSUE TITLE
Default theme and colors are sucks

### ISSUE THREAD

**Issue by effolkronium** [microsoft/terminal#3396]
After opening the terminal app I have a strong desire to go back to standard cmd app with black white colors

**Comment by oising** [comment]
The terminal is customizable. You can change all of the colours yourself. Example: https://www.howtogeek.com/426346/how-to-customize-the-new-windows-terminal-app/

Closing this as non-constructive commentary.

**Comment by effolkronium** [comment]
Yep, but the background was terrible :)

i like the solid color in current update )
