### ISSUE TITLE
top-level "Run as Administrator" shortcut

### ISSUE THREAD

**Issue by yangshuairocks** [microsoft/terminal#3398]
# Description of the new feature/enhancement
On Windows 10, when you pin the native PowerShell shortcut to start, there is a menu item "Run as Administrator" when you right-click it.

![image](https://user-images.githubusercontent.com/39968/67994098-922cd000-fc7e-11e9-8d87-b09573273aa5.png)

However, the same operation for Windows Terminal results in this:

![image](https://user-images.githubusercontent.com/39968/67994128-aec90800-fc7e-11e9-80fc-41a84d95833f.png)

The user has to choose "more" -> "Run as Administrator".

![image](https://user-images.githubusercontent.com/39968/67994141-be485100-fc7e-11e9-8db6-acbefc80651d.png)

I hope Windows Terminal has the top-level "Run as Administrator" just as native PowerShell does.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
_platform limitation, sorry._ /dup #3152 #1872 #2623
