### ISSUE TITLE
Paste Issue

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#3399]
When we paste anything in the Windows Terminal ubuntu instance using any command like **vim abc.txt**, it automatically inserts new line after each line, and eats up some characters from the beginning of the pasted text.
Here is the screenshot: https://i.imgur.com/pJ0Fsbw.png

Here the text copied to my clipboard copied was:
```
Line 1
Line 2
Line 3
Line 4
Line 5
Line 6
Line 7
```
I ran command: **vim abc.txt**
And after paste, it became 
```
ne 1

Line 2

Line 3

Line 4

Line 5

Line 6

Line 7


```

**Comment by DHowett-MSFT** [comment]
Please search before reporting new issues. /dup #1093.
