### ISSUE TITLE
Bug Report - Azure Security Center Flags Windows Terminal launching conhost as Suspicious

### ISSUE THREAD

**Issue by ld0614** [microsoft/terminal#3402]
I noticed after connecting my computer up to a Log Analytics account in Azure that I started getting alerts from Azure Security Center about Windows Terminal launching conhost.  This might be a duplicate of #2568 but might just be related.  

I am running version 0.6.2951.0 downloaded and installed from the Microsoft Store. 

## Alert Details ##
DESCRIPTION The system process c:\program files\windowsapps\microsoft.windowsterminal_0.6.2951.0_x64__8wekyb3d8bbwe\conhost.exe was observed running in an abnormal context. Malware often use this process name to masquerade its malicious activity.
ACTIVITY TIME Thursday, October 31, 2019, 9:36:12 AM
SEVERITY  Medium
STATE Active
DETECTED BY  Microsoft
ENVIRONMENT Non-Azure
RESOURCE TYPE  Non-Azure Resource
COMMAND LINE conhost.exe --headless --width 120 --height 27 --signal 0x7b8 -- pwsh.exe
PARENT PROCESS windowsterminal.exe
PROCESS ID 0x54b4
PARENT PROCESS ID 0x9dd4
SYSTEM PROCESS CONHOST.EXE

**Comment by DHowett-MSFT** [comment]
This is likely largely no longer an issue since we stopped calling it `conhost.exe`. Let me know if it's still flagging!
