### ISSUE TITLE
How to set startDictionary?

### ISSUE THREAD

**Issue by HoranZuo** [microsoft/terminal#3404]
How to set the default path to be Ubuntu home path instead of Windows home path?
<img width="329" alt="批注 2019-11-01 211802" src="https://user-images.githubusercontent.com/35492958/68027366-1e75dc00-fced-11e9-9ca9-7e83b905db03.png">
<img width="419" alt="批注 2019-11-01 211736" src="https://user-images.githubusercontent.com/35492958/68027367-203f9f80-fced-11e9-9400-e508eef137dd.png">

**Comment by zadjii-msft** [comment]
(this post inspired #3405. Thanks! The following is largely taken from that documentation)

With Windows 1903, the filesystems of WSL distros can easily be addressed using the `\\wsl$\` prefix. For any WSL distro who's name is `DistroName`, you can use `\\wsl$\DistroName` as a Windows path that points to the root of that distro's filesystem.

For example, the following works as a profile to launch the "Ubuntu-18.04" distro in it's root:

```json
{
    "name": "Ubuntu-18.04",
    "commandline" : "wsl -d Ubuntu-18.04",
    "startingDirectory" : "//wsl$/Ubuntu-18.04/home/zadjii",
}
```
