### ISSUE TITLE
Rendering - PSReadline's MenuComplete output was rendered twice

### ISSUE THREAD

**Issue by xa0082249956** [microsoft/terminal#3407]
# Environment

|Name|Value|
|-------------|--------|
|Platform      | Win32NT|
|ServicePack   ||
|Version       |10.0.19013.0|
|VersionString | Microsoft Windows NT 10.0.19013.0|
|Windows Terminal version | 0.6.2951.0 from Microsoft Store|

# TL;DR GIF

![fig.gif](https://i.loli.net/2019/11/01/6bWMlK54karNFGy.gif)

# Steps to reproduce

1. Open a PowerShell tab in Windows Terminal.
2. Type `Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete`
2. `cd` to a folder with lots of files.
3. Type `ls` and then enter.
4. After it finished, type `Start-` and **press `Tab` to trigger `MenuComplete`**

# Expected behavior

A auto completion menu is displayed **once** and I can select with my keyboard.

# Actual behavior

I can select but auto completion menu is displayed **twice**.

**Comment by zadjii-msft** [comment]
@xa0082249956 What psreadline version are you using?

**Comment by xa0082249956** [comment]
> @xa0082249956 What psreadline version are you using?

Version **2.0.0**.

```powershell
~\Documents\PowerShell> Get-Module PSReadLine | Format-List

Name              : PSReadLine
Path              : C:\Users\xtyzw\Documents\PowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1
Description       : Great command line editing in the PowerShell console host
ModuleType        : Script
Version           : 2.0.0
PreRelease        : beta4
NestedModules     : {Microsoft.PowerShell.PSReadLine2}
ExportedFunctions : PSConsoleHostReadLine
ExportedCmdlets   : {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
ExportedVariables :
ExportedAliases   :
```

**Comment by DHowett-MSFT** [comment]
This looks like an issue with [PSReadline](https://github.com/PowerShell/PSReadline), honestly. It doesn't repro under the same circumstances with the PSReadline 2.0.0 beta2/3 that's shipped with Windows.

**Comment by DHowett-MSFT** [comment]
We could still handle it better, though.

**Comment by xa0082249956** [comment]
> This looks like an issue with [PSReadline](https://github.com/PowerShell/PSReadline)

You are right. I update `PSReadLine` to version `2.0.0-beta5` and now I can't repro the issue anymore.
I checked the update log of `PSReadLine` and found the problem is fixed in a [PR](https://github.com/PowerShell/PSReadLine/pull/937).

However, I still cannot understand why I can only found the problem in Windows Terminal. Maybe just because the problem happens randomly.

**Comment by zadjii-msft** [comment]
Hey since this is fixed upstream, I'm going to close this one out.

I bet the reason that this seemed more prevalent in the Windows Terminal is because we're using conpty. When things are running in conpty, they're always running in a virtual console buffer that's only ever the size of the viewport, so the console is _always_ at the end of the buffer.
