### ISSUE TITLE
Can't add more then 5 profiles

### ISSUE THREAD

**Issue by tomlm** [microsoft/terminal#3410]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.18363.418]
Windows Terminal version (if applicable): 0.6.2591.0

Any other software? no
```

# Steps to reproduce

I have a number of environment profiles (9 in total) 
[profiles.txt](https://github.com/microsoft/terminal/files/3799445/profiles.txt)

# Expected behavior

To be able to have more then 5 profiles (like shown in the windows store screenshot)
![image](https://user-images.githubusercontent.com/17789481/68053381-02e8e200-fca9-11e9-96a5-926f5cfb6798.png)

# Actual behavior

In the drop down and using the hotkeys what I get is
![image](https://user-images.githubusercontent.com/17789481/68053263-c1583700-fca8-11e9-8b01-12ad84e45c77.png)

Which after many experiments appears to be:
* first 2 profiles
* last 3 profiles
for a total of 5 profiles

**Comment by DHowett-MSFT** [comment]
Hey @tomlm,
It looks like four of your profiles have the same GUID.

```
(DHOWETT-DEV2) /mnt/c/Users/duhowett/Downloads % grep guid profiles.txt | sort | uniq -c
      1             "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
      1             "guid": "{161aa5c3-9d21-4b50-8a55-b50510318502}",
      1             "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
      4             "guid": "{a4bc9602-0476-4366-9faa-9b3ec249484b}",
      1             "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
```

Windows Terminal can't tell which you want to actually see. If you want, you can delete the GUIDs from your custom profiles and we'll automatically generate (a hidden) one for you.

**Comment by DHowett-MSFT** [comment]
(we had a feature where we'd warn on duplicates, but I bet that the cascading settings change made it so that each new instance of the same guid modified the existing instance)

**Comment by tomlm** [comment]
oh snap.  I just couldn't figure it out.  Thanks a million!
Idea:. It would be nice if you simply used the array index as the id instead of requiring an external guid, or auto-assigned a GUID based on index if you really really really must have a guid.

**Comment by DHowett-MSFT** [comment]
We actually do assign a guid, but it's based on the name. Couple reasons why we don't use index (and really do want to have guids)

* Your profile's index isn't guaranteed to be stable across the lifetime of the application, especially with settings hot reloading.
* It would be wacky if you switched your cmd and powershell profiles in your settings file to change their order in the menu and they switched livery and started to look like eachother at runtime
* Dynamic profile generators (all WSL, powershell core, azure) need the ability to determine whether the user actually has a profile they know about
* Not having a solid mapping of profile blob to unique identifier would make cascading settings nigh-unto impossible (where later profile configs override settings from earlier ones, even ones in earlier files)

**Comment by DHowett-MSFT** [comment]
(If you remove the guids entirely, the names will be used to generate new guids. They're namespaced so they will not collide with autogenerated ones. If you remove the GUIDs for `cmd` and `Windows PowerShell`, the ones from _defaults.json_ will suddenly reappear because they're no longer being overridden by unique ID)
