### ISSUE TITLE
Pasting into Linux...

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3417]
Hi All

i dont't know if there is something wrong with my confing or it is a bug but in WSL and linux boxes connected via ssh when pasting clear text from notepad, Windows Terminal after each line, leaves one empty line. I am pasting using right click.

It does not happen on cmd.exe or PowerShell

Anybody know how to resolve that?

Thanks

**Comment by j4james** [comment]
Sounds like a duplicate of #1091.

**Comment by DHowett-MSFT** [comment]
Yep! This is a  /dupe of #1091. Thanks!
