### ISSUE TITLE
Proper handling of multiline copy paste

### ISSUE THREAD

**Issue by testautomation** [microsoft/terminal#3418]
# Description of the new feature/enhancement
As a user I want to be able to paste long commands that are spread over multiple lines where the linebreaks are escaped with `\`. Example below
```shell
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
``` 

## ACTUAL
The actual behavior is that terminal tries to execute each line immediately . See example below
```
learn@DESKTOP-4FCRN5Q:~/projects$ sudo apt-get install \
>
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
learn@DESKTOP-4FCRN5Q:~/projects$     apt-transport-https \
>
apt-transport-https: command not found
learn@DESKTOP-4FCRN5Q:~/projects$     ca-certificates \
>
ca-certificates: command not found
learn@DESKTOP-4FCRN5Q:~/projects$     curl \
>
curl: try 'curl --help' or 'curl --manual' for more information
learn@DESKTOP-4FCRN5Q:~/projects$     gnupg-agent \
>
gnupg-agent: command not found
```

## EXPECTED

The multiline command from above example is treated as on command and after being paste waits for the user to press ENTER before it is executed.

> NOTE: The Ubuntu WSL is a good example of how it should behave correctly
![image](https://user-images.githubusercontent.com/38438046/68070038-c11f7080-fd68-11e9-8966-0b0623ecc226.png)

**Comment by Luuk34** [comment]
You should not copy the final end-of-line character. If you do than the final ENTER will not be pasted, and you will have the ability to do it yourself.
