### ISSUE TITLE
WSL home direcotry...

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3419]
Hi All

anybody knows how to configure profile with 'wsl.exe -d Debian' so it would start in WSL's home direcotry and not windows home direcotry?

Thank you.

**Comment by Biswa96** [comment]
Add `cd ~` in `.bashrc` file in that WSL user's home directory.

**Comment by encladeus** [comment]
There is a pull request that explains how to set your profile to open in WSL user home directory. See #3405.

**Comment by 4k3or3et** [comment]
Thanks for point out that post.

**Comment by Zuyv** [comment]
I’m using ubuntu. In my case, switching ‘wsl.exe -d Ubuntu’ to ‘ubuntu.exe’ will make it start in home directory. Not sure but you could try with ‘debian.exe’.

**Comment by zadjii-msft** [comment]
Thanks for finding the duplicate @encladeus! That's correct, #3405 will add this documentation.
