### ISSUE TITLE
Copying multiline commands shows an error

### ISSUE THREAD

**Issue by Jazzynupe** [microsoft/terminal#3420]
When copying and pasting a multiline command to the terminal. I get weird extra lines and terminal errors that command was not valid.

In particular this is related to PowerShell (5 and 6 core)

Even function definitions that are complex also show errors

Here is a sample response from Powershell when pasting the function to the console window

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
```
 g i t Space r e s e t Space o r i g i n / m a s t e r Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space # g i t Space s t a t u s Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space } Enter      Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space } Space - E n d Space { Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space g e t - g i t s t a t u s Enter      Ctrl+Enter Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space } Enter
 Ctrl+Enter Enter
 Ctrl+Enter E n d Space { Enter
 Ctrl+Enter Space Space Space Space Enter
 Ctrl+Enter Space Space Space Space Enter
 Ctrl+Enter Space Space Space Space p o p - L o c a t i o n Enter
 Ctrl+Enter } Enter
 Ctrl+Enter Enter
 Ctrl+Enter }
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -111.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
```

However if I open the regular terminal window for Powershell, it works fine.

**Comment by DHowett-MSFT** [comment]
Please search for existing issues. /dup #1091.
