### ISSUE TITLE
Pwsh and azure cloud shell.

### ISSUE THREAD

**Issue by EwertonJordao** [microsoft/terminal#3422]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0


Any other software?
```

# Steps to reproduce

Connect on azure cloud shell
Run pwsh
if you run any command in bash mode and after running PowerShell clear output 
![image](https://user-images.githubusercontent.com/12378570/68080091-f5c81200-fdd2-11e9-9959-04397cf36908.png)
freezing cursor and I can`t interact in the terminal.

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
Hey, this is a /dup of #2267. Thanks!

**Comment by EwertonJordao** [comment]
Sorry
