### ISSUE TITLE
Add an option to disable copy/paste with right click

### ISSUE THREAD

**Issue by cra0zy** [microsoft/terminal#3424]
I personally prefer having a context menu with right click.

Basically I request that you mimic an option from Visual Studio Code where you have "terminal.integrated.rightClickBehavior" that allows you to specify how right click behaves.

**Comment by DHowett-MSFT** [comment]
Broadly, this is covered by /dup #1553 and #3337. Thanks!

**Comment by vwheeler63** [comment]
There is another issue related to this that is even more important:  right-click paste can be dangerous or even catastrophic when working in a source-code environment.  I believe it is not only important, but critical to making Windows Terminal safe to use in a source-code environment.

**Comment by 354651432** [comment]
two years pasted, the issue is still an issue

**Comment by zadjii-msft** [comment]
Yep. It's still on the backlog. If you've got a clever design for mouse bindings, we'd love to hear it over in #1553!
