### ISSUE TITLE
Terminal freezes sometimes when it's minimised

### ISSUE THREAD

**Issue by widersky** [microsoft/terminal#3426]
# Environment

```none
Windows build number: 10.0.18363.0
VSCode
Node v10.15.1
Laragon Full v4.0.14 190508
MS Edge v79.0.309.7
```

# Steps to reproduce

1. Run Terminal and some npm script (in my case)
2. Minimise
3. Return to Terminal's windows after few minutes

# Expected behavior

Simple - terminal should not be freezing when it's minimised

# Actual behavior

Terminal does not respond

**Comment by lesleyxyz** [comment]
Had something similar, terminal was in background with a few panes open connected to ssh and after checking back a few hours later (with my laptop sleeping in for some time) everything was blank and unresponsive. Will also use the feedback hub if I can repro

**Comment by widersky** [comment]
@DHowett-MSFT 
https://aka.ms/AA6htod

**Comment by huoyaoyuan** [comment]
Note: I'm also getting freezed seldom when minimizing on Edge and my self-built UWP application.
I think this should be an external bug of XAML UI itself.

**Comment by zadjii-msft** [comment]
Hey I know it's been like a year since this was originally filed - are you still seeing this? We haven't gotten any other reports, which makes me think it might have just gone away on its own 🤞

**Comment by huoyaoyuan** [comment]
I don't remember any repro of this in 2020. But I haven't use the original app/PC frequently, and UWP Edge has been replaced with Chromium Edge.
The original issue looks like something external.
