### ISSUE TITLE
Switching on-off property 'Use Legacy Console' does not return terminal to original state.

### ISSUE THREAD

**Issue by wpqs** [microsoft/terminal#3430]
# Environment

https://github.com/microsoft/terminal/issues

# Steps to reproduce

1. Open Command Prompt - i.e. run cmd
2. Open Properties | Options - remove check from 'Use Legacy console'   - switch OFF
3. Close Command Prompt
4. Open Command Prompt - i.e. run cmd
5. Open Properties | Options - add check from 'Use Legacy console'   - switch ON
6. Close Command Prompt
7. Open Command Prompt - i.e. run cmd

# Expected behavior

All properties of the terminal should be the same as before step 2. That is to say restoring the 'Use Legacy console' property in step 5 should restore the state of the terminal to what it was before the property was changed.

# Actual behavior

After restoring the 'Use Legacy console' to OFF the terminal window is blank because the terminal colours have not been correctly restored to their previous state - both foreground and background are black. Similarly the cursor color is black rather than inverse colour.

**Comment by zadjii-msft** [comment]
Hey so I think the bug you're describing is actually a couple things, both in more detail here: #2956. They're #2319, fixed by #2651, and also #2855 makes this scenario better as well. 

These should all be arriving with the next feature update of Windows :)

/dup #2319
