### ISSUE TITLE
Menu option 'Defaults' does not restore terminal properties to factory settings in non-legacy mode

### ISSUE THREAD

**Issue by wpqs** [microsoft/terminal#3431]
# Environment

Microsoft Windows [Version 10.0.18362.418]

# Steps to reproduce

1. Open Command Prompt - i.e. run cmd
2. Open properties dialog and ensure 'Use Legacy Console' is unchecked, then close dialog
3. Select menu option 'defaults'

# Expected behavior

The terminal properties should be set to their factory defaults. 

# Actual behavior

Property window opens and properties have not been changed. What are the factory defaults? Who knows?

**Comment by zadjii-msft** [comment]
Hey thanks for the feedback! I definitely understand that UX is especially confusing. However, the "defaults" menu has literally never worked that way. When it comes to console settings, they're layered from a variety of locations, starting with the first here and successively applying subsequent layers:

1. The hardcoded defaults embedded in the application itself.
2. "Defaults" storen in the registry under `HKCU\Console`
3. Optionally, one of the following:
  * Properties that are stored in the shortcut
  * per-title settings that can be stored in `HKCU\Console\<title>`
4. Runtime settings passed in through `STARTUPINFO`.

When you open the "Defaults" propsheet, what you're actually doing is opening the menu to edit the defaults in item 2, the "registry defaults". 

If you _really_ want to "reset to factory defaults", you can just delete all the the keys under `HKCU\Console`.
