### ISSUE TITLE
Block Cursor Negative color or Transparency

### ISSUE THREAD

**Issue by Jkoutsoumpas** [microsoft/terminal#3434]
#3052 Description of the new feature/enhancement
Profile option *cursorShape* with setting *filledBox* displays a totally opaque block cursor with the color defined in the *cursorColor* setting.

when navigating through characters, the cursor totally blocks (no pun intended!) the underlying character and it is frustrating for the user and error prone while editing the line text.

# Proposed technical implementation details (optional)
 
Make the filledBox use an alpha channel (transparency) and/or give the option to display the underlying character with a negative color on top of the cursor so it is visible and sufficiently legible in all cases and all color configurations.

**Comment by zadjii-msft** [comment]
Thanks for the report! This sounds quite a bit like #1203 to me. It was also breifly discussed in #3322. I'm going to redirect discussion to that thread. 

/dup #1203
