### ISSUE TITLE
Slow powershell startup

### ISSUE THREAD

**Issue by cdmihai** [microsoft/terminal#3437]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
Powershell 6.2.3
```

I get slow startup times (~6-7 perceived seconds). It started happening with Terminal 0.5.2762.0. It's particularly annoying when I start splitting off panes left and right.
I ruled out my `$Profile` script by printing out its execution time as its last command.

Let me know how I can give you any profiled data.

**Comment by DHowett-MSFT** [comment]
Interesting. And it doesn't repro if you just run pwsh from <kbd>Win+R</kbd>? That's highly unusual.

Incidentally, powershell tells me how long it took to load my user profile every time I start it up, and I don't recall configuring that. Is it doing that here for you too?

**Comment by cdmihai** [comment]
Yes, Powershell is telling me profile scripts load times as well. The startup times difference between the Powershell terminal and Terminal is that Terminal takes slightly longer before and after Powershell writes its times (but the times are mostly on par with the Powershell terminal). Maybe it would be useful to log the Terminal overhead before and after invoking the inner shell.

**Comment by DHowett-MSFT** [comment]
Huh, that's interesting. Thanks!

**Comment by Fonta** [comment]
I think I might the same thing here. By times when I start Windows Terminal i simply get a blinking cursor for around 7-10 seconds or so.
This happened when I had pwsh 5.1 as default and now also with pwsh 7 as default.
There's nothing in my profile that gets started.

The weird thing is also that it isn't always slow. A lot of times it's as fast as starting PS normally.

**Comment by DHowett-MSFT** [comment]
Contrasting running pwsh directly, which _never_ takes a long time? I'm somewhat skeptical: we're really just spawning it in the exact same way as always...

**Comment by cdmihai** [comment]
@DHowett-MSFT, maybe there's a measurement gap somewhere. My $Profile script prints out its time at the end, and Terminal still does something 1-4 seconds after that, until I can type. Ideally it would be nice to measure 3 times;
- terminal startup to shell invocation
- shell startup time
- time from end of shell startup to when user can type stuff

**Comment by DHowett-MSFT** [comment]
> Terminal (or something else) still does something 1-4 seconds after that, until I can type.

By this point, terminal is just two pipes hooked up to a console process; it cannot introduce further delay between when the shell prints something and accepts input.
Do you, per chance, have a complicated `Prompt` function?

Regardless, would you mind capturing traces using [this WPR profile](https://raw.githubusercontent.com/microsoft/terminal/dev/duhowett/wprp/src/TerminalPerf.wprp), using the `Console Performance Default Profile`? Thanks!

My e-mail (and therefore MS alias ;P) is in my github profile.

**Comment by cdmihai** [comment]
>Do you, per chance, have a complicated Prompt function?

I do have posh-git installed, but my startup directory is not in a git repo.

I'll get a recording and send it to you.

**Comment by DHowett-MSFT** [comment]
@cdmihai guessing that posh-git ended up being the culprit?

**Comment by cdmihai** [comment]
That's my current lead, per our email discussion. Unfortunately I didn't manage to carve out enough time to study it further, and posh-git is too useful to remove. But one of these days ...

**Comment by archongum** [comment]
> That's my current lead, per our email discussion. Unfortunately I didn't manage to carve out enough time to study it further, and posh-git is too useful to remove. But one of these days ...

Same here. I need `post-git` and startup speed too.

**Comment by DHowett** [comment]
It would be worth filing a bug on them to get git.exe out of the critical path then!

**Comment by dacokid** [comment]
I have the same problem :/ Seems like posh really is causing the slow down

**Comment by dacokid** [comment]
I have just found a solution in stackoverflow 
[you can find it here](https://stackoverflow.com/questions/48262269/how-to-i-remove-the-powershell-start-text)

**Comment by dacokid** [comment]
![image](https://user-images.githubusercontent.com/28742636/97610576-d7035800-19f3-11eb-9429-077244c1323c.png)

**Comment by DHowett** [comment]
I do not know why you have decided that powershell printing 4 lines of text is at all related to its _speed_.

**Comment by cdmihai** [comment]
> I do not know why you have decided that powershell printing 4 lines of text is at all related to its speed.

I decided to give it a try because why not, and it is indeed a major improvement in startup speed. Seems ridiculous, but alas that's software for ya :)

**Comment by dacokid** [comment]
I didn't decide, it was just a coincidence. I wanted to remove that 4 lines of text and it also improved startup speed. So yeah :)

**Comment by DHowett** [comment]
It's 2020. Weirder things have happened! :smile:

**Comment by AnantTiwari-Naman** [comment]
-nologo helped me too, ig we can close this issue  now

**Comment by wolfygit** [comment]
Execute the next .bat

```lang-bash
net stop CryptSvc /y
rename c:\windows\system32\catroot2 Catroot2.bak
net start CryptSvc
```
