### ISSUE TITLE
Windows Terminal does not open with button displaying "maximized" state

### ISSUE THREAD

**Issue by mu88** [microsoft/terminal#3440]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 0.6.2951.0

```

# Steps to reproduce

Set `"launchMode": "maximized"` within `profiles.json`

# Expected behavior

Windows Terminal opens maximized.

# Actual behavior

Windows Terminal opens with maximum screen size, but not maximized (see screenshots).
wrong (actual implementation): ![wrong](https://user-images.githubusercontent.com/4560672/68200105-7fd4ce00-ffbf-11e9-8ab8-376373701524.png)
correct: ![correct](https://user-images.githubusercontent.com/4560672/68200162-9d099c80-ffbf-11e9-92e6-b3fd1e707934.png)

**Comment by trajano** [comment]
One other thing, the original size is also lost so when you launch again, you have to manually resize the window again.
