### ISSUE TITLE
Terminal fails to run after installing - app license missing

### ISSUE THREAD

**Issue by LonMcGregor** [microsoft/terminal#3441]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0_x64

Any other software?
* Powershell 7 Preview (x64)
* WSL - Ubuntu
```

# Steps to reproduce

0. Open microsoft store
1. Search for terminal
2. Install terminal
3. Launch terminal

# Expected behavior

Terminal launches

# Actual behavior

An error message is displayed:

> [Window Title]
> C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
> 
> [Content]
> C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
> 
> No applicable app licenses found.
> 
> [OK]

**Comment by a-gn** [comment]
This has been happening to me for a few days. Before that, Terminal worked fine. I get the exact same error window.

**Comment by a-gn** [comment]
The accepted answer to [this question](https://answers.microsoft.com/en-us/windows/forum/all/windows-apps-no-applicable-app-licence-found/4627a18a-9229-4d7d-a94b-30c4b5eaf15e) fixes it. The problem was not in Terminal.

**Comment by zadjii-msft** [comment]
@a-gn Thanks for the suggestion! @LonMcGregor does that solution work for you?

**Comment by LonMcGregor** [comment]
_seems_ to work now. No need to even try to apply the fix. But I'll remember this if it happens again.

Don't you just love DRM. 🤦‍♀️

**Comment by DHowett-MSFT** [comment]
We started shipping builds of the terminal that have been re-signed by the store. This should help. Let me know if it doesn't!
