### ISSUE TITLE
Windows Terminal works once, and then refuses to start afterwards

### ISSUE THREAD

**Issue by dalgibbard** [microsoft/terminal#3442]
Feedback Hub ref: https://aka.ms/AA6h5a5

# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.18363.449]
Windows Terminal version (if applicable): 0.6.2951.0
```

# Steps to reproduce
* Install via Microsoft Store
* Run once, change no settings, just exit the application
* Try to run the application again. Refuses to start

Uninstalling and re-installing allows me to run it once before it stops working again.
The following shows in Event Viewer:
```none
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: ucrtbase.dll, version: 10.0.18362.387, time stamp: 0x4361b720
Exception code: 0xc0000409
Fault offset: 0x000000000006db8e
Faulting process ID: 0x648
Faulting application start time: 0x01d593d9ad986ce2
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report ID: 12631cc9-d497-4e43-b19a-b38d76e9dc8e
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

# Expected behavior
* Expect application to start repeatably

# Actual behavior
* Windows Terminal not starting after first run

**Comment by DHowett-MSFT** [comment]
Hey @dalgibbard! Thanks for the report.

Would you mind sharing your `profiles.json`? It's in `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\` (since you can't launch Terminal to get at it 😀)

**Comment by dalgibbard** [comment]
Ah, i posted a reply to this with the code in it, but it's not here now? Must've had a sketchy network connection at the time.

Today I bit the bullet and installed the Fast Ring build (10.0.19018.1), and after reinstalling Windows Terminal it works correctly.
So; I no longer have access to the profile.json which had an issue, and after upgrading Windows to the fast ring (was: slow ring), I no longer have the issue.

**Comment by dalgibbard** [comment]
Whoops I take that back; it's not opening again now; since it was working i've installed docker (with WSL2 integration), set that up for use with WSL2 and rebooted a bunch of times.

So issue still persists on latest windows fast ring build too :(

**Comment by DHowett-MSFT** [comment]
And if you just run `wsl -d Ubuntu` directly, it works?

**Comment by dalgibbard** [comment]
Yes indeed, running ```wsl -f Ubuntu``` from cmd.exe, works fine.

**Comment by nizmow** [comment]
I'm getting what seems to be the exact same behaviour, but I'm building from source. Slightly different information is shown in the event log:

```
Faulting application name: WindowsTerminal.exe, version: 0.0.0.0, time stamp: 0x5dce6789
Faulting module name: InputHost.dll, version: 10.0.18362.387, time stamp: 0x1217c36e
Exception code: 0xc0000409
Fault offset: 0x0000000000041a73
Faulting process id: 0x3f68
Faulting application start time: 0x01d59bb49d507fdb
Faulting application path: C:\Code\third_party\Terminal\src\cascadia\CascadiaPackage\bin\x64\Release\AppX\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\InputHost.dll
Report Id: fd4f1b3a-c074-47ce-94c2-2c8fc0cce74d
Faulting package full name: WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

My `profiles.json` isn't anything special, the default tab is standard Powershell.

Built this morning from master branch:

`commit ebdcfbd9400d505978675f0610275e72ebb70208 (HEAD -> master, tag: v0.6.3181.0, origin/master, origin/HEAD)`

**Comment by DHowett-MSFT** [comment]
Since you built it from source, can you run it inside Visual Studio and capture a stack trace? That’ll be really helpful :)

**Comment by dgibbard-cisco** [comment]
OK i found something of interest; In Settings> Storage> "Change Where New Content Is Saved", I had this set to save new apps to drive "F:" (which is a Storage Spaces RAID1 across 2x 2TB HDDs) - I'd set this so that Xbox (Beta) games were saved to this drive; seems it affects all microsoft store apps.

After uninstalling Windows Terminal, setting this back to "C:" and re-installing, it now works correctly!

**Comment by DHowett-MSFT** [comment]
? ! ?

Well, that's not supposed to happen! Thanks for following up, that's really concerning.

**Comment by nizmow** [comment]
Follow up from earlier: I'm a C# developer, not a C++ developer, and wrangling Visual Studio to get a stack trace was sadly beyond me (even in Debug mode, the exception wouldn't give me much but an opportunity disassemble to assembler, which didn't seem that useful).

However, to follow up on this last comment, I'm in an enterprise environment was using folder redirection (to a network share) for a lot of things. I've recently asked IT to switch this off, and surprise, Terminal now works fine all the time. So we may be onto something here.

**Comment by DHowett-MSFT** [comment]
It's been a while since we got a good repro for this, so I'm going to close it out. Let me know if it's still a problem!
Thanks
d
