### ISSUE TITLE
Adding the contributing.md file in a supported location for community standards

### ISSUE THREAD

**Issue by shakeel30** [microsoft/terminal#3443]
The community profile for this repository indicates there is no contributing.md file even though it exits in the docs folder. 

![2019-11-05 (2)](https://user-images.githubusercontent.com/38057565/68218279-0edae980-ffb2-11e9-97cf-597287bb9685.png)

I'd like to add a copy of the already existing contributing.md to a supported location so that it reflects in the repository's community profile.

**Comment by zadjii-msft** [comment]
Huh that's weird. Yea it should probably reflect there, I blame @bitcrazed 😜 If anything I'd just move it to the root, no need having `doc/` and `docs/`

**Comment by shakeel30** [comment]
Okay great. I'm gonna go ahead and do just that.

**Comment by shakeel30** [comment]
Working on it.
