### ISSUE TITLE
Terminal tabbed content disappears, chrome around window only shows tabs

### ISSUE THREAD

**Issue by arjun-msft** [microsoft/terminal#3446]
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version (if applicable): 0.6.2951.0

```

# Steps to reproduce

I didn't do anything specific, left terminal running, when I tried to use it, the content of the tabs were gone and the minimize/maximize/close buttons on the terminal window were also gone.  

Potential things that did happen on the machine:
- I have terminal running on Virtual Desktop 2
- I have remoted in from another PC which has caused DPI changes
- I have unplugged/plugged in a monitor multiple times

![terminal-screenshot](https://user-images.githubusercontent.com/20304470/68236069-4b5e1380-ffb9-11e9-9a4e-10d13b041b8b.png)

# Expected behavior

Show a display

# Actual behavior

No display for tabs

**Comment by miniksa** [comment]
OK, I remote debugged @arjun-msft's machine. All of our threads appear to be operating normally.

He's going to try to watch it today to see which specific event causes it to go away.
The suspicious things include DisplayPort displays and multiple NVIDIA graphics cards of different model years. There's a bunch of Nvidia APC threads stuck. Might just be an artifact of monitor plug/unplug.

I also left the debugger attached to see if we get a LOG_IF_FAILED message output throughout today.

**Comment by miniksa** [comment]
Also, opening a new tab restores all the drawing to normal. Weird.

**Comment by lediur** [comment]
I'm experiencing the same issue under Windows 10 Pro Insider build 19028. Tab contents and window controls disappear after restoring from a minimized state (or from standby). Creating a new tab makes the tab contents and window controls reappear.

**Comment by zadjii-msft** [comment]
Woah uh, this was filed in **0.6**. It's been like, almost 3 years, with PILES of bug fixes. You still seeing this/?

**Comment by arjun-msft** [comment]
Wow, I haven't seen in a long long time.  Closing it out.
