### ISSUE TITLE
Sending negative values to `ResizePseudoConsole` returns `S_OK`

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/terminal#3447]
# Environment

```none
Windows build number: 18363,418
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Call `ResizePseudoConsole` with negative values stored in the passed `COORD` structure.

# Expected behavior

returned HRESULT should indicate failure since a pty cannot have a negative size

# Actual behavior

returned HRESULT indicates success.

**Comment by miniksa** [comment]
https://github.com/microsoft/terminal/blob/388b975663e895c45710584e0e0fda8bcebc1fbe/src/winconpty/winconpty.cpp#L201

The `COORD` which has two signed `SHORT`s is being pushed into a structure of `unsigned short` and apparently nothing is complaining or validating that.
