### ISSUE TITLE
Tab title gets reset by Win32 apps in WSL

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#3451]
# Environment

```none

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

+ Ubuntu 16.04.5 LTS via WSL
```

# Steps to reproduce

1. Create profile for Ubuntu.
2. Set `"tabTitle": "Ubuntu"` in config.
3. Start bash tab. Notice title says "Ubuntu".
4. Run Win32 console program: sc.exe

# Expected behavior

Title still shows "Ubuntu"

# Actual behavior

Title shows, before and after running the program, "C:\Windows\system32\sc.exe"

**Comment by DHowett-MSFT** [comment]
/dup #2645. `tabTitle` is an _initial_ tab title.

**Comment by heaths** [comment]
I understand that, but with Win32 consoles the initial tab title is restored. Is this a limitation of wsl?

**Comment by DHowett-MSFT** [comment]
It's not exactly a limitation of WSL, but it _is_ a configuration issue coupled with an issue that plagues _all_ terminals[*]. What's really happening is this:

1. We launch a console, and set its initial title
2. We spawn WSL attached to that titled console.
2. Your shell (through WSL) does not set the title.
3. You launch `sc.exe`, which runs in a nested console with an initial title
4. That nested console's title change propagates to the parent console
5. `sc.exe` exits
6. The shell does not set the title.

[*] There is no affordance in the VT standard for a "title stack" such that an application can push on a title frame and _ask that the title be restored_ afterwards. Titles are write-only, and there's only one of them, so everybody on the same machine needs to work together to make sure the title always makes sense.

Most stock distribution shell configurations include a line that sets or resets the window title after every command; on my installed copy of Ubuntu that happens in `$HOME/.bashrc` line 69 with a crazy escape sequence inserted into the _prompt_.

If I suppress that configuration by resetting `PS1` to something that doesn't contain the "set title" escape sequence, then run `sc.exe`, the title remains `sc.exe` for all eternity.

**Comment by DHowett-MSFT** [comment]
Ah, and here's why it works for CMD. My bit about titles being "write-only" only applies to VT, not the Win32 API. CMD calls GetConsoleTitle and saves/restores that between every command invocation. WSL cannot do that, but because of that limitation shared by all implementors of the common terminal language.

**Comment by heaths** [comment]
Thanks for the explanation. Very insightful.
