### ISSUE TITLE
Windows Terminal does not pass mouse events to WSL 2

### ISSUE THREAD

**Issue by garrettdc** [microsoft/terminal#3456]
# Environment

```none
Windows build number: 10.0.19008.0
Windows Terminal version: 0.6.2951.0
WSL 2: Ubuntu 19.04
```

# Steps to reproduce

* Open terminal
* Open file to edit in vim
* Type ':set mouse=a' to enable mouse mode globally
* Attempt to scroll

# Expected behavior

* Scrolling and other mouse events should be passed through and handled by the respective program
* Double clicking should engage VISUAL mode in vim

# Actual behavior

* Scrolling causes the terminal to scroll into it's scrollback buffer
![windows_terminal_vim_scroll](https://user-images.githubusercontent.com/13264485/68268359-737e5e80-001b-11ea-8b2a-3b9de40bebe9.png)
* Double clicking selects text in the terminal, but not in the application itself. This seems more in line with how I would expect single click and drag or shift + click events to be handled.

**Comment by DHowett-MSFT** [comment]
/dup #376, #545, #531, #2056, #2344, #2364, #2727, #3046, #3364, #3450

**Comment by DHowett-MSFT** [comment]
(please make sure you search before submitting a new issue! thanks!)
