### ISSUE TITLE
Microsoft Store download alternative

### ISSUE THREAD

**Issue by lflogistis-morriswong** [microsoft/terminal#3457]
# Description of the new feature/enhancement

Available to download outside of Microsoft Store

# Proposed technical implementation details (optional)

Company policy blocked access to Microsoft Store and therefore there is no way to download it.

An alternative way to download the windows terminal

**Comment by DHowett-MSFT** [comment]
Come on, it's in the [readme](https://github.com/microsoft/terminal#manually-installing-builds-from-this-repository).
