### ISSUE TITLE
Window frame is rather wide.

### ISSUE THREAD

**Issue by swarfega** [microsoft/terminal#3464]
On my 1909 RP PC the window frame size in 0.6 Terminal is much wider than it should be. I don't have this problem with my other machine running Insider.
![winterm06](https://user-images.githubusercontent.com/2217248/68347303-5e263480-00ee-11ea-85d2-6cfa7daac9d4.PNG)

**Comment by DHowett-MSFT** [comment]
First, you win the award for "most understated title of the week"

Second, this is a /dupe of #3136.
