### ISSUE TITLE
Default Background/Foreground found in the schema doesn't match with what shows up in Terminal.

### ISSUE THREAD

**Issue by leonMSFT** [microsoft/terminal#3466]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19013.1102]
Windows Terminal version (if applicable): 0.6
```

# Steps to reproduce

Create a color scheme with foreground as \#ffffff and background as \#000000 to represent white and black respectively. Create two profiles of cmd, assign one the custom color scheme, and the other with no color scheme to give it the default background and foreground. The default profile has a slightly lighter black background, and a slightly darker white foreground.

# Expected behavior

The schema found here: https://aka.ms/terminal-profiles-schema says that the default background is \#000000 (black) and the default foreground is \#ffffff (white).

# Actual behavior

Default background is slightly lighter than black and default foreground is slightly darker than white.

**Comment by BartXZX** [comment]
Maybe its because of the acrylic/transparancy effect?

**Comment by zadjii-msft** [comment]
Hmm, this is a bit confusing. The trick here is that the default value of "colorScheme" is "Campbell".

That documentation should probably be updated to not give a default value for those settings, since they're _unset_ by default 😄

**Comment by DHowett-MSFT** [comment]
> not give a default value

So, the `default` in schema is actually the value that shows up as a suggestion or gets automatically input in a compliant editor— it’s apparently less about what the default is and more about user education?

**Comment by leonMSFT** [comment]
Ah, the default scheme being Campbell was tripping me up a little. 😅 I was in the mindset of thinking of default as "what the fg/bg color should be when I don't set it in either the profile or the color scheme".

Looks like in the schema, <code>background</code>/<code>foreground</code> block doesn't have a <code>default</code> property, and so when adding fg/bg to the settings json, it simply auto fills a "#" and lets you put the hex in yourself. But, hovering over the key for the description tells you this: "Default #000000 (black).".
