### ISSUE TITLE
Addition of an advanced find box

### ISSUE THREAD

**Issue by srv-code** [microsoft/terminal#3469]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Please add a find box as in cmd.exe:
![image](https://user-images.githubusercontent.com/32870803/68366089-65822800-0158-11ea-8567-edcf2a29be03.png)

A more advanced find box will be helpful just as in Notepad++:
![image](https://user-images.githubusercontent.com/32870803/68366120-7c287f00-0158-11ea-96a9-6930742dc9a3.png)

User should be able to:
1. Option to search using regular expression.
2. Option to search in current tab only.
3. Option to search across all the tabs.
4. Option to search across tabs of similar type (e.g. across Ubuntu tabs only), 
5. Option to get the count of matches etc.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is already being tracked by #605, and is already being worked on in a number of PRs, #3299, #3413 and #3279. Please make sure to _search_ for existing issues when filing a new issue.

/dup #605

Thanks!
