### ISSUE TITLE
Tree-shake the lib linking list

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#3477]
We should be able to get away with using umbrellas and not individual libs to link.

This represents shaking the tree to get rid of the duplication.

That is, I think we can get away with just using one of these:
1. windowsapp.lib
2. onecoreuap.lib
3. onecoreuap_apiset.lib
4. onecore.lib
5. onecore_apiset.lib

and none of things like this:
- kernel32.lib
- gdi32.lib
- user32.lib
etc.

This represents someone groveling around `common.build.post.props` and friends and shaking them out.

**Comment by DHowett-MSFT** [comment]
This also solves our `MinimalCoreWin` problem.
