### ISSUE TITLE
wt Command does not open windows terminal

### ISSUE THREAD

**Issue by stef011** [microsoft/terminal#3481]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0



```

# Steps to reproduce

Just update WT I think...

# Expected behavior

Opens Windows Terminal

# Actual behavior

Nothing, just a error saying this command does not exist.

```none
wt : Le terme «wt» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 1
+ wt
+ ~~
    + CategoryInfo          : ObjectNotFound: (wt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by zadjii-msft** [comment]
@stef011 Did you install the terminal from the store? Or from another source (chocolatey, `.msix` directly from github)?

You can find the version number in the "About" dialog:

![image](https://user-images.githubusercontent.com/18356694/68480497-974bcb00-01fa-11ea-857a-29ad762cbe30.png)

I know I've seen this before where the execution aliases of the WSL distros can just _disappear_ sometimes.

Is `wt` in `C:\Users\<your username>\AppData\Local\Microsoft\WindowsApps`?

**Comment by stef011** [comment]
So, about six month ago, I installed it myself from GitHub, last week, I re-installed it with the windows store, to get back a clean config.json .

**Comment by DHowett-MSFT** [comment]
There's a settings page, "Manage app execution aliases", which lets you configure which aliases you can use. Mine looks like this:

![image](https://user-images.githubusercontent.com/14316954/68534700-3ef4f600-02ec-11ea-8038-b4495f84726f.png)

![image](https://user-images.githubusercontent.com/14316954/68534704-43211380-02ec-11ea-911a-faa5047a35f5.png)

You can get there through "Apps & features". Would you mind checking your Windows Terminal entry/entries?

**Comment by stef011** [comment]
Again, everything looks fine, `Windows Terminal (Preview)` is checked as below...
![image](https://user-images.githubusercontent.com/3099695/68541417-85eff380-039f-11ea-862d-bc2216373b52.png)

I discovered (by mistake) that, when I type `wt` in an admin console, it launches wt properly...
And after testing, none of the applications in my aliases works when not in admin... 🤔

Admin :
![admin](https://user-images.githubusercontent.com/3099695/68541513-bf752e80-03a0-11ea-8b54-5639837b44cb.gif)

Not Admin :
![notadmin](https://user-images.githubusercontent.com/3099695/68541552-209d0200-03a1-11ea-925e-636828b7be12.gif)

**Comment by Luuk34** [comment]
Try 'Advanded Options', it has a 'RESET' option...
![AdvancedOptions](https://user-images.githubusercontent.com/7850737/68541810-48419980-03a4-11ea-888e-5fdd8bed0f85.jpg)

**Comment by stef011** [comment]
Sorry @Luuk34 but this doesn't work either...

I started a `sfc /scannow` I think the problem is not from windows terminal...

**Comment by stef011** [comment]
OKAY !
Many cleaning tools later I figured it out !

> BUT I have no `USERPROFILE` in my variables...

This was the main error, I don't know how, but the `USERPROFILE` var was deleted, I added it back like this :

![image](https://user-images.githubusercontent.com/3099695/68542529-b9397f00-03ad-11ea-8cae-e20e84d94c11.png)

And miracle ! It works, wt and  everything else...

Thank you very much for your help ! 😄 

Now I feel like I'm really dumb... 🤓

**Comment by HajAhmad** [comment]
> @stef011 Did you install the terminal from the store? Or from another source (chocolatey, `.msix` directly from github)?
> 
> You can find the version number in the "About" dialog:
> 
> ![image](https://user-images.githubusercontent.com/18356694/68480497-974bcb00-01fa-11ea-857a-29ad762cbe30.png)
> 
> I know I've seen this before where the execution aliases of the WSL distros can just _disappear_ sometimes.
> 
> Is `wt` in `C:\Users\<your username>\AppData\Local\Microsoft\WindowsApps`?

I just neede to add WindowsApps path to PATH variable manually. Thanks Alot :)

**Comment by HO-pilo-studios** [comment]
for me is not working it saying "this file cannot accessed by the system"

**Comment by stef011** [comment]
> @stef011 You seemed to have resolved this on your own - is there a specific reason you reopened this?

Sorry I thought HO-pilo-studios needed more help, so I reopened this Issue, I wanted to reply, but I forgot to do it... 

> for me is not working it saying "this file cannot accessed by the system"

@HO-pilo-studios Can you better describe your problem, maybe send some screens or try to use the path to wt.exe instead and see if you have the same issue ?

**Comment by garyng** [comment]
I bumped into this issue as well after Windows Terminal was updated. 

Repairing the app from App & features works for me:
![image](https://user-images.githubusercontent.com/4453664/120081288-8968de00-c0ef-11eb-81c1-932ea31536bf.png)

**Comment by palenshus** [comment]
This just happened to me too, and Repairing the app fixed the problem

**Comment by nrrpinto** [comment]
> 
> 
> OKAY !
> Many cleaning tools later I figured it out !
> 
> > BUT I have no `USERPROFILE` in my variables...
> 
> This was the main error, I don't know how, but the `USERPROFILE` var was deleted, I added it back like this :
> 
> ![image](https://user-images.githubusercontent.com/3099695/68542529-b9397f00-03ad-11ea-8cae-e20e84d94c11.png)
> 
> And miracle ! It works, wt and everything else...
> 
> Thank you very much for your help ! 😄
> 
> Now I feel like I'm really dumb... 🤓

Thanks so much for the tip. It solved my issue.

No, you are no dumb, Microsoft is! Or who ever creates this kind of rules.

**Comment by DHowett** [comment]
> No, you are no dumb, Microsoft is! 

It is not necessary for you to come into our house and slander us.
