### ISSUE TITLE
Emojis are rendering unusually small

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3482]
Emojis are rendering unusually small:

![image](https://user-images.githubusercontent.com/172594/68474189-afccdd00-021c-11ea-8fd6-9cd870d903ac.png)

# Environment

Microsoft Windows NT 10.0.18908.0
Terminal 0.6.2951.0

**Comment by zadjii-msft** [comment]
I'm pretty sure this is some combination of the following:

/dup #610 #2921
/dup #900
