### ISSUE TITLE
Bug Report: Only 3 terminal tabs visible

### ISSUE THREAD

**Issue by calloncampbell** [microsoft/terminal#3484]
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

Open any console (I'm using PowerShell for this issue submission). After you open 3 tabs you get tab scroll bar buttons on either end. 

# Expected behavior

When opening many tabs I expect them to grow across the top like in any web browser and only show tab scroll bar buttons when needed (I have more tabs than the window can display).

# Actual behavior

I only ever see my 3 tabs and I have to scroll. A screenshot of this issue can be seen on my twitter feed... https://twitter.com/flying_maverick/status/1192882256517324800

**Comment by DHowett-MSFT** [comment]
@calloncampbell This sounds a lot like pinned issue #3300. Was the tab bar sized to fit a smaller window, and it didn't grow when you maximized it?

**Comment by calloncampbell** [comment]
So resizing the window and then adding another tab seems to fix the issue.

**Comment by DHowett-MSFT** [comment]
Thanks for confirming. This is indeed a /dupe of #3300.
