### ISSUE TITLE
Double cursors in neovim terminal buffer (and fzf, probably more)

### ISSUE THREAD

**Issue by schffp** [microsoft/terminal#3499]
# Environment

```none
Windows build number: 10.0.18362.418
NVIM v0.3.8
```

# Steps to reproduce

Open Neovim in WSL Windows Terminal and open a terminal buffer (:ter). Then enter insert mode.

# Actual behavior

There will be two cursors.

**Comment by zadjii-msft** [comment]
@schffp Could you share screenshots of what you're seeing? What Windows Terminal version are you running?

**Comment by schffp** [comment]
Sure! I'll attach screenshots of fzf.vim and the terminal buffer. I'm using version 0.6.2951.0 of Windows Terminal.

![fzf](https://user-images.githubusercontent.com/35227426/68683623-64416880-0567-11ea-8f67-88804b0c09c4.png)
![terminalbuffer](https://user-images.githubusercontent.com/35227426/68683628-69061c80-0567-11ea-9a23-c2673e1ceb8a.png)

**Comment by schffp** [comment]
I just noticed, this only happens when using `set guicursor =` in my nvim.init. I have this there in order to stop nvim from overwriting the "emptyBox" cursor I had to set. So this shouldn't matter to me anymore after #1203 is adressed. That being said, `set guicursor =` works in mintty without inducing this bug.

**Comment by zadjii-msft** [comment]
Okay I think I see what's happening here. `wt` vs `conhost`:
![image](https://user-images.githubusercontent.com/18356694/68867577-b398ad80-06bb-11ea-8b2b-f57ea38abb73.png)
![image](https://user-images.githubusercontent.com/18356694/68867609-bf846f80-06bb-11ea-9c0b-e56fceda6999.png)

I bet that this is due to the Windows Terminal not currently supporting the "cursor off" VT sequence. This is tracked over in  #3093, but I'm going to cautiously leave this open to make sure this case is _also_ fixed when we implement that.

**Comment by mkarbo** [comment]
I also have this issue, which makes it pretty much impossible for me to use the terminal application

**Comment by surajp** [comment]
Has this fixed been deployed to the store yet? I'm still seeing the issue

**Comment by DHowett-MSFT** [comment]
@surajp you'll know when we make a new release

like the one we sent out 6 minutes ago with an accompanying blog post

**Comment by DHowett-MSFT** [comment]
The bot also _usually_ comments on resolved issues, but it doesn't seem to be doing so right now.

**Comment by ErickTucto** [comment]
I also have a double cursor, and I'm on linux (Ubuntu 20.04.3) using the xfce terminal

I have Nvim 0.5 (AppImagen)
![gnome-shell-screenshot-5DRX90](https://user-images.githubusercontent.com/22831024/134585839-26ad5109-8b47-4877-b17e-8b4432c3b2b2.png)
