### ISSUE TITLE
profiles.json is invalid JSON

### ISSUE THREAD

**Issue by samscode** [microsoft/terminal#3503]
# Environment
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.6.2951.0

Any other software?
MiTeC JSON Viewer 1.2.1.0 (default application for opening json files)

# Steps to reproduce
Select Settings from the menu.

# Expected behavior
Software associated with json file able to open a valid JSON settings file.

# Actual behavior
JSON Viewer complains the settings file is invalid. It contains comments which are not valid in json.

**Comment by Luuk34** [comment]
If you remove all the comments, it IS valid JSON (according to https://tools.ietf.org/html/rfc8259 )

- Do you have any suggestion where to puts the 'documentation' for this settings file?
- Will there ever be a GUI to edit settings for 'Windows Terminal'?

**Comment by DHowett-MSFT** [comment]
Yeah, we're actually JSONC. Since the config is meant to be human-editable, it seemed a more _humane_ choice.

There will be a UI: #1564.
