### ISSUE TITLE
Unable to enter Chinese on any terminal opened by Windows terminal

### ISSUE THREAD

**Issue by HaroldCC** [microsoft/terminal#3509]
Unable to enter Chinese on any terminal opened by Windows terminal
Windows terminal : Windows Terminal (Preview)   Version: 0.6.2951.0
windows : Win10 Enterprise Edition  version: 18362.449

**Comment by skyline75489** [comment]
#2213

**Comment by zadjii-msft** [comment]
Thanks for the early triage pass @skyline75489! This is in fact /dup #2213.
