### ISSUE TITLE
Fitts' Law to the tab bar

### ISSUE THREAD

**Issue by denilsonsa** [microsoft/terminal#3510]
# Description of the new feature/enhancement

Currently, there are 4 pixels of distance between each of the top of the tabs and the top of the maximized window:

![image](https://user-images.githubusercontent.com/121676/68541168-7f13b180-039c-11ea-82eb-c72a98231061.png)

According to the Fitts' Law, the time to interact with a component is a function of the distance from the mouse pointer to the component, and the area of the component. As a special case, because the computer screen is bounded, the four screen borders (and the four corners) have infinite area, making them extremely easy and fast to use.

However, the Windows Terminal (version 0.6.2951.0) places the tabs just 4 pixels away from the screen border, making it very frustrating to click (even more so because users are already used to tabs in Chrome and Firefox).

Further reading:

* https://blogs.msdn.microsoft.com/jensenh/2006/08/22/giving-you-fitts/
* http://particletree.com/features/visualizing-fittss-law/
* https://blog.codinghorror.com/fitts-law-and-infinite-width/
* https://en.wikipedia.org/wiki/Fitts%27s_law

# Proposed technical implementation details (optional)

The tabs should touch the screen border when the terminal is maximized. Just like how Chrome and Firefox also behave.

---

Footnote: I tried searching if this issue had been reported before, but I found nothing. This issue here should be included into #1625.

**Comment by innovoix** [comment]
> The tabs should touch the screen border when the terminal is maximized. Just like how Chrome and Firefox also behave.

Yes please! 👍 
I realized that in Firefox the distance between tab and window border is much smaller (almost no gap) then in Chrome/Edge chromium when not maximized. 
Chrome/Edge chromium when not maximized is more like Windows Terminal now. Just saying. 😄

**Comment by skyline75489** [comment]
I actually like the idea. Maybe Windows Terminal should just behave more like Chrome and Firefox.

**Comment by kfsone** [comment]
This is **_infuriating_** in any scenario where the top of the screen is acting as any kind of hot zone: remote desktop, hyper-v, screen capture, or [insane] people who put their task bars at the top of the screen.

Chrome non-fullscreen:
![image](https://user-images.githubusercontent.com/323009/68549597-de7abd00-03ae-11ea-805f-c2d3810b9cfd.png)

Chrome after WM_MAXIMIZE: Note: hitbox is both rectangular and includes the tab border chrome to reach the top of the display.
![image](https://user-images.githubusercontent.com/323009/68549618-0e29c500-03af-11ea-9d8e-25e030ee2834.png)

Terminal after WM_MAXIMIZE:
![image](https://user-images.githubusercontent.com/323009/68549621-213c9500-03af-11ea-9967-9ea0efcdddf9.png)

**Comment by zadjii-msft** [comment]
Yea this makes sense to me. I could have sworn there was a dupe for this but I'm not finding it. Thanks for the write-up!

**Comment by miniksa** [comment]
@cinnamon-msft is going to find where this goes. She's working on tab pixel-y things right now.

**Comment by miniksa** [comment]
Kayla says (now verbally in triage) that this is a /dup of #2541.
