### ISSUE TITLE
Codebase invokes lots of undefined behavior by using reserved identifiers

### ISSUE THREAD

**Issue by Longhanks** [microsoft/terminal#3512]
The code base seems to use lots of identifiers for private member objects or functions that start with an underscore, followed by an uppercase letter, such as `IslandWindow::_ApplyWindowSize` ([/src/cascadia/WindowsTerminal/IslandWindow.h#L99](https://github.com/microsoft/terminal/blob/db797580923472c08613f054364097be06d73229/src/cascadia/WindowsTerminal/IslandWindow.h#L99)).

The C++ standard however says:

> In addition, some identifiers are reserved for use by C++ implementations and shall not be used otherwise; no diagnostic is required. Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

(From https://eel.is/c++draft/lex.name#3.1)

Using such identifiers is technically an invocation of undefined behavior.

**Comment by miniksa** [comment]
Yeah.... someone on our team brought this up once but we determined it wasn't a big enough deal to spend time on at the moment. If you or anyone else is interested in fixing all the names to be compliant with the standard (and hopefully also write a test or something to enforce that we don't violate it again), we'd be happy to take it.

**Comment by zadjii-msft** [comment]
Oh my goodness this is actually already tracked in /dup #721
