### ISSUE TITLE
Open links on clicking

### ISSUE THREAD

**Issue by angelfraga** [microsoft/terminal#3517]
# Description of the new feature/enhancement

If some link is shown in the terminal, it would be nice to allow open it whether clicking over it.

# Proposed technical implementation details (optional)
Maybe  `ctrl+left mouse key`  as default combination could produce a similar behaviour like VSCode integrated terminal. 
If the link uses a file path such as `C:\myfile.txt`, clicking opens it. 
If the link is an URL, then default system browser will open it in a new tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is already being tracked in another issue, so I'll redirect conversation there:

/dup #574
