### ISSUE TITLE
Pasting doesn't trigger `snapOnInput` behavior

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3518]
# Description of the new feature/enhancement

I'd consider this a bug, since nearly every terminal does it, but it's also a missing feature:

Windows 10: 10.0.18908.0
Windows Terminal: 0.6.2951.0\

When scrolled up so the prompt isn't visible, pasting or typing should scroll to the prompt.

Example:
 - I just scrolled up to copy something
 - I found it and pasted it (into the prompt)
 - I then want to see my prompt, and would expect the terminal to have scrolled down

**Comment by zadjii-msft** [comment]
For the record, this looks like it only happens when output is pasted. This already works fine for input that's _typed_ into the Terminal.

**Comment by mikemaccana** [comment]
Thanks @zadjii-msft 🙂
