### ISSUE TITLE
Tabs don't reappear after resizing the window horizontally 

### ISSUE THREAD

**Issue by theaaronstewart** [microsoft/terminal#3523]
# Windows 10 1903 Build 18362.449
Terminal version 0.6.2951.0

# Steps to reproduce

Drag the window from either the right or left side and shrink it until the tabs are no longer visible. Extend the window back out until there is enough room for a few tabs. 

# Expected behavior

The tabs disappear when the window becomes to small to display them. Then slide back out when the window is resized to fit them again.

# Actual behavior

The tabs don't reappear on the tab bar unless you click to add a new tab, then they all pop back in. The tab bar scroll buttons are there but don't so anything when clicked.

**Comment by zadjii-msft** [comment]
Hey thanks for the report! This is actually one of the pinned issues at the top of the repo - please make sure to search when filing new issues.

![image](https://user-images.githubusercontent.com/18356694/68608691-20703580-0479-11ea-822a-e0f802ec9c39.png)

/dup #3300
