### ISSUE TITLE
Custom profiles that do not specify `startingDirectory` crash on launch

### ISSUE THREAD

**Issue by nathpete-msft** [microsoft/terminal#3526]
This issue is new as of 0.6.3121.0, and is happening for profiles I've had around for a long time.

# Environment
```none
Windows build number: 10.0.19023.0
Windows Terminal version: 0.6.3121.0
```

# Steps to reproduce
1. Have an existing, custom profile in `profiles.json` that does _not_ specify a `startingDirectory`.
2. Open a tab with that profile.
3. 💥
4. Add `startingDirectory` to the profile in question.
5. Open a tab with that profile again.
6. No 💥

# Expected behavior
No 💥

# Actual behavior
💥

**Comment by miniksa** [comment]
Looks like a /dupe of #3506 which Dustin already fixed. We'll get another build out soon. Thanks!
