### ISSUE TITLE
Include Terminal Settings from my PowerShell profile folder or any arbitrary folder.

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#3529]
# Description of the new feature/enhancement
Customizing Terminal settings should be allowed to be loaded from my OneDrive folder or my own github repository, just like my powershell settings are or my VIM settings.

Currently, when I login into a new machine I have to merge or manually copy settings for Terminal, I don't have this problem in PowerShell or VIM as all I need to do is git clone and redirect to my settings folder.

# Proposed technical implementation details (optional)
Here are some options:
1. Allow for an arbitrary folder to be configured to read settings.
2. Read from ~\.terminal folder (but allow redirection)

After configuring the "reditected" folder, all my settings and profile are restored.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This looks like it's a /dup of #2303.
