### ISSUE TITLE
Cannot paste text into `git` input

### ISSUE THREAD

**Issue by sitefinitySDK** [microsoft/terminal#3533]
# Environment

```none
Windows build number: Version 10.0.18363.449
Windows Terminal version (if applicable): Version: 0.6.2951.0

Any other software? Git for Windows 2.24.0
Powershell core 6.2.3
```

# Steps to reproduce

I am using WT with PSC. Inside it, I issue `git push` command. It require me to input account and password. Instead of typing them manually, I tried to paste the password.

I tried two things:

1. using the right mouse button
2. using Ctrl-V

# Expected behavior

I expect that the password text would be pasted and accepted by `git` command

# Actual behavior

Nothing happens. `git` does not receive the pasted text.

Please note, I verified that I can paste text inside WT itself. Both right mouse button and Ctrl-V options worked. The issue is somewhere in the interaction of WT, PSC, and git. If I am using CMD only or PSC only, I can successfully paste the text and git accepts the input.

**Comment by celsojr** [comment]
This seems to be an OS line ending issue (CRLF). Please try this small tool before you paste yuor credential contents and let me know if it works for you.

https://github.com/celsojr/p2u

**Comment by DHowett-MSFT** [comment]
If it's a line ending issue, this seems like a /dup of #1091.

**Comment by DHowett-MSFT** [comment]
Thanks!
