### ISSUE TITLE
DesktopWindowXamlSource Not Responding

### ISSUE THREAD

**Issue by wbuck** [microsoft/terminal#3537]
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

Launch the Windows terminal by clicking on the icon either on the task bar or from the start menu.

# Expected behavior

The Windows terminal to open.

# Actual behavior

The process starts but no view is displayed. Checking the TaskManager I see the following:

![image](https://user-images.githubusercontent.com/13386150/68696587-3cdca280-054b-11ea-9954-5a2e671725b5.png)

**Comment by wbuck** [comment]
Below is the link to the data taken from my FeedBack Hub issue.
https://aka.ms/AA6kukq

**Comment by wbuck** [comment]
OK, so turned my laptop on just now and tried to open the terminal again and it worked. This is exactly like another issue I saw here. Everything auto magically fixed it self. I guess the issue can be closed..

**Comment by andresbm05** [comment]
This also happends to me randomly. Some times when I start my PC the terminal app does not launch and the DesktopWindowXamlSource does not responds.

I have also noticed that the WSL doesn't work either so the ubuntu app freezes on startup and VSCode gets stuck in "Starting VS Code in WSL (default distro): Starting Linux Subsystem"

After a reboot everything works as expected. I think this issue should be reopened.

**Comment by wbuck** [comment]
When it happened to me restarting the PC didn’t work. It had just fixed it self after 3-4 days. Since it fixed it self it’s been fine though.

**Comment by skydivin4ng3l** [comment]
Have exactly the same issue, also with Ubuntu WSL.

**Comment by zadjii-msft** [comment]
If anyone here can repro this consistently, could you repro it with the Feedback Hub, and share the link so we can investigate?

/feedback

Also, cc @ocalvo

**Comment by skydivin4ng3l** [comment]
https://aka.ms/AA6zdkw

**Comment by wbuck** [comment]
@zadjii-msft I did post the link to my Feedback Hub issue. I posted the issue when the problem was still occurring.

**Comment by luizwhite** [comment]
It just happened to me
I restarted my PC then it started working normally 🤷‍♂️

**Comment by Gavin152** [comment]
Just happened to me, too. Wasn't even able to kill the processes via the TaskManager. 
First reboot didn't help, same thing ... second reboot *somehow* fixed it.

**Comment by danwhitston** [comment]
Same thing just happened to me. Gonna try rebooting now...
