### ISSUE TITLE
Refactor GenRTF() and GenHTML() to use shared components

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#3538]
# Description of the new feature/enhancement

#3535 adds `GenRTF()` to enable RTF Copy. It has some parts that are _very_ similar to `GenHTML()`, which makes sense. It'd be nice to find a way to refactor the code a bit to reuse some sections.

My concern is that we make find a bug and fix it in one and not the other.

# Proposed technical implementation details (optional)

We could probably use a few helper methods to create a more distinct separation of HTML vs RTF specific portions. The overall architecture and flow of both functions are essentially the same. Maybe even add an enum?

# Bonus points
`Make GenHTML()` noexcept too.

**Comment by carlos-zamora** [comment]
@DHowett I was taking a closer look at the differences between `GenRTF()` and `GenHTML()`. Refactoring them would just make the code more difficult to understand and risks breaking something. Mind if I just close this issue?

**Comment by DHowett** [comment]
Go ahead!
