### ISSUE TITLE
doubleclick doesn't highlight full path

### ISSUE THREAD

**Issue by paulelong** [microsoft/terminal#3541]
# Environment
Microsoft Windows NT 10.0.18362.0

# Steps to reproduce
- git status
- double click a path that you want to diff
- only highlights part of the path.  In a normal powershell window it includes the full path.

# Expected behavior
I expect it to include the full path so I can use it with git in terminal very easily.

# Actual behavior
Instead I only copy a single directory in the path, and I have to manually highlight the path.

**Comment by DHowett-MSFT** [comment]
Go configure your `wordDelimiters`.
