### ISSUE TITLE
Refactor Search module to have different implementations for Terminal and ConHost

### ISSUE THREAD

**Issue by KaiyuWang16** [microsoft/terminal#3542]
# Description of the new feature/enhancement
This is a follow up of https://github.com/microsoft/terminal/pull/3279. Search module is migrated as a shared component for Terminal and ConHost. However, Color method is used in ConHost but not in Terminal. For now, in Terminal directory we only call Terminal::ColorSelection, which does nothing but just throws exception. We need to consider refactor the codes to provide ConHost and Terminal different implementation. 

A possible fix is to make Search an abstract class and provide different implementation in Terminal and ConHost. 

# Proposed technical implementation details (optional)
Search class can be an abstract class, and we implement it in Terminal and ConHost directory. In this way we can have more specific realization of the Color method. 

Search module is well-designed and implemented and can fit Terminal and ConHost's needs.

**Comment by carlos-zamora** [comment]
This seems more of a CodeHealth thing to me. I'm throwing it into our v2 milestone and assigning it to myself for now.

This might be a random thing we should do as a part of working on Search v2 in #3920.

**Comment by lhecker** [comment]
I'm gonna go ahead and close this issue. Both applications now use the exact same functionality. Also, I rewrote `Search` the past few days and it's now 33 LOC. It's not a maintenance burden anymore. 🙂
