### ISSUE TITLE
Set panes keybindings by default

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#3544]
# Description of the new feature/enhancement
Include panes keybindings by default

# Proposed technical implementation details (optional)
Current keybinding suggestion:
```       
		{ "command": "splitHorizontal", "keys": [ "alt+shift+-" ] },
        { "command": "splitVertical", "keys": [ "alt+shift+plus" ] },
        { "command": { "action": "moveFocus", "direction":"down" }, "keys": [ "alt+down" ] },
        { "command": { "action": "moveFocus", "direction":"left" }, "keys": [ "alt+left" ] },
        { "command": { "action": "moveFocus", "direction":"right" }, "keys": [ "alt+right" ] },
        { "command": { "action": "moveFocus", "direction":"up" }, "keys": [ "alt+up" ] },
        { "command": { "action": "resizePane", "direction":"down" }, "keys": [ "alt+shift+down" ] },
        { "command": { "action": "resizePane", "direction":"left" }, "keys": [ "alt+shift+left" ] },
        { "command": { "action": "resizePane", "direction":"right" }, "keys": [ "alt+shift+right" ] },
        { "command": { "action": "resizePane", "direction":"up" }, "keys": [ "alt+shift+up" ] },
```

**Comment by zadjii-msft** [comment]
I like this suggestion, because it ties everything related to Panes together with the <kbd>alt</kbd> key. Splitting, moving focus, resizing, all done with the alt key in the key chord.

<sub> I also like these because _these are **my** current keybindings_ 😜 </sub>

**Comment by egmontkob** [comment]
Which camp did you guys join according to https://english.stackexchange.com/q/293520 ? :-)

**Comment by zadjii-msft** [comment]
@egmontkob I pretty arbitrarily picked the following:
>  * If a Pane is split vertically, the two panes are seperated by a split, as to appear side-by-side. Think `[|]`
> * If a Pane is split horizontally, the two panes are split by a horizontal separator, and appear above/below one another. Think `[-]`.

The Split(Direction) commands are used to add a separator such that the separator itself is either vertical or horizontal. At least that's the way I interpreted it, though there was some discussion on the matter.
