### ISSUE TITLE
The text layout code is expecting the quantity of glyphs is equal to the cells allocated for each line

### ISSUE THREAD

**Issue by reli-msft** [microsoft/terminal#3546]
The issue is found in `CustomTextLayout`:

Instead of carefully process the `clusters` input, `CustomTextLayout` drops nearly all the information from `clusters`, and only keeping how many columns a cluster occupy, and later it is expecting that the glyph quantity equals to the quantity of clusters. This may lead to incorrect rendering result for many cases (complex script, ligatures, etc.)

Bug #610, #696 may be caused by this.

**Comment by reli-msft** [comment]
Running the following script in Node.JS shows _a lot of_ problems in current text layout code:

```javascript
console.log(`
Combining Diacritics    | [a\u0300\u0304]
Polytonic Greek         | [ᾊ] [Α\u0345\u0313\u0300]
Ideographic Variation   | [東京都葛\u{E0101}飾区] [奈良県葛\u{E0100}城市]
Composite Hangul        | [\u1100\u116A\u11B3]
Combining Dakuten       | [か\u309A]
Emoji vs Text           | [\u2602] [\u2602\uFE0E] [\u2602\uFE0F]
Emoji                   | [\u{1F469}]
Emoji with Skin Tone    | [\u{1F469}\u{1F3FB}]
Emoji Variation and ZWJ | [\u{1F469}\u{1F3FB}\u200D\u{1F4BB}]
`)
```

![image](https://user-images.githubusercontent.com/50213618/68721295-c51c7100-0566-11ea-9dea-75cd57f95378.png)
![image](https://user-images.githubusercontent.com/50213618/68721316-cf3e6f80-0566-11ea-8336-cf73b9e04ad8.png)

**Comment by skyline75489** [comment]
Possibly also #2191

**Comment by skyline75489** [comment]
Let me add Firefox result here, so that people don't forget that there's a browser out there called "Firefox":

![图片](https://user-images.githubusercontent.com/4710575/68726167-a0bea400-05fb-11ea-9e66-29e9b9b1709c.png)

**Comment by DHowett-MSFT** [comment]
@skyline75489 my hero

**Comment by skyline75489** [comment]
@DHowett-MSFT my man. I'm seeing regression on current master https://github.com/microsoft/terminal/commit/306e75163929161b130872dcae890686da57790d

![图片](https://user-images.githubusercontent.com/4710575/68740302-ba74e100-0625-11ea-8ca4-c02fbf7cc099.png)

**Comment by skyline75489** [comment]
I've used `git bisect` and found that ddcc06e911a18250c8544c7ea83011451e8256a2 is the first bad commit.

**Comment by skyline75489** [comment]
I've tried this on my laptop and sadly the regression is the same:

![图片](https://user-images.githubusercontent.com/4710575/68770861-e615bc80-0661-11ea-840f-dab6528b9841.png)

Emoji is noticeably broken.  Japanese characters are different, too.

**Comment by zadjii-msft** [comment]
@skyline75489 Thanks for the report! I'm going to move that regression to it's own thread (#3553), considering you've narrowed the regression down to a particular commit. _Broadly_ our text rendering needs help with M chars->N glyphs scenarios like this issue describes, but we probably shouldn't have things getting worse on us.

**Comment by reli-msft** [comment]
**This** is heavily related to this issue: https://github.com/microsoft/terminal/issues/780
There's `WriteCharsLegacy` and `Terminal::_WriteBuffer`, and they should be unified into one function that writes char stream to the back buffer with _proper_ itemization.

**Comment by skyline75489** [comment]
Without #780 we can still improve the current implementation like #3578 . I'm not sure whether that's worth the effort, though. It's more like scratching the surface.

**Comment by reli-msft** [comment]
@skyline75489 
We need to change the way we write buffers to perform correct line wrap and cursor movement.
For WT there are two buffers being used: one for `CONHOST`, which is the "Ground Truth", and one for WT, and the write subroutine is written differently.

So what's wrong with `WriteCharsLegacy`? Well...
 * It does not process surrogate pairs properly.
 * Combining characters are not written into the "previous" cell. They are treated separately and the cursor is moved.

**Comment by skyline75489** [comment]
@reli-msft Gotta admit, the whole Unicode experience is harder to fix than I initially anticipated. I'm not sure the exact plan Console team have. But I'm positive that we are heading to the right direction.

**Comment by reli-msft** [comment]
@skyline75489 
Everybody are underestimating how complex text could be.

**Comment by skyline75489** [comment]
@reli-msft I'd trust you with the whole Unicode thingy myself. I'm a real rookie on this. You can tell from my PR ... Anyway let @DHowett-MSFT take us to where we should eventually be.

**Comment by DHowett-MSFT** [comment]
Latest results from master

![image](https://user-images.githubusercontent.com/14316954/75734034-b4c20a80-5cab-11ea-89cb-e91e955623a4.png)

**Comment by reli-msft** [comment]
@DHowett-MSFT Looks better... Sort of.
Still needs to update our knowledge about Hangul Jamos' width

**Comment by DHowett** [comment]
You know, with the completion of #16916 I believe we've finally cracked this nut.

![Image](https://github.com/user-attachments/assets/46a4b77b-9c29-4d1d-82ee-6b573b2b2df5)
