### ISSUE TITLE
Moderately complex commandline property in profiles.json stopped working

### ISSUE THREAD

**Issue by rbeesley** [microsoft/terminal#3550]
# Environment

```none
Windows Terminal (Preview)
Version: 0.6.3121.0
```

```none
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19018.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19018.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```none
PS C:\> conda --version
conda 4.7.12
```

# Steps to reproduce

1. Install Anaconda
2. Create a profile in `profiles.json` which is the same as the following, with updated references where needed:

```json
// profiles.json

{
   "profiles":
    [
        {
            "guid": "{398546a1-6641-4b31-b81d-2afca23ddc5f}",
            "icon": "ms-appx:///ProfileIcons/{574e775e-4f2a-5b96-ac1e-a2962a402336}.png",
            "hidden": false,
            "name": "Anaconda Powershell Prompt (current)",
            "startingDirectory": "%HOMEPATH%",
            "commandline": "%windir%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current' \""
        },
    ],
}
```

3. Try to launch launch this profile in Terminal

# Expected behavior

This same profile had been used to launch an Anaconda Powershell Prompt and until Terminal v0.6.3121.0, had been working properly.

# Actual behavior

Now, there is a brief flash where it seems like Terminal is trying to launch the shell, but it quickly fails to do so and closes that tab. If I launch a regular PowerShell shell, and then manually issue the Command, I can get things working as they previously did, so this seems to be a recent change with how the commandline property is read rather than what I'm trying to execute. This seems to have stopped working with the update I received from Microsoft Store recently. Microsoft Store indicates that I received an update yesterday, but I can't confirm that this was when this change occurred, only that it happened in the past few days as this was working last week. I am suspicious that there was a change with how escaping things might have changed but I wasn't able to determine what is different now and what might work.

**Comment by DHowett-MSFT** [comment]
Good news! This was #3548, and an update was published to the selfhost channel that fixed it.

**Comment by rbeesley** [comment]
Seems like it could be related to #3198. I created a new profile, with different GUID, kept everything else the same, but replaced the Environment variables in the profile with their expanded replacements. This allows the new profile to open as before, but with hard-coded paths.

**Comment by rbeesley** [comment]
Looks like it might be a duplicate of #3548. I think this might be fixed.

**Comment by rbeesley** [comment]
@DHowett-MSFT, I should have refreshed my bug report page... I just saw that fix in the changes and presumed it to be the same issue when reading the bug, so I didn't see that you had already resolved this when I was commenting.
