### ISSUE TITLE
I need ‘watch’ instruction for watch -n 1 -d nvidia-smi like linux bash

### ISSUE THREAD

**Issue by p577665228** [microsoft/terminal#3551]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Please make sure to fill out the issue template. Are you asking for a new application (`watch.exe`) to be shipped with Windows? Or would you want a `Watch` command built in to powershell/cmd? How would this command work? Perhaps link some documentation on the original `watch` command, and why it's not possible to achieve the same effect on Windows today.
