### ISSUE TITLE
How to open a Visual Studio Developer Command Prompt in Terminal?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/terminal#3552]
A Visual Studio Developer Command Prompt can be accessed by opening a cmd prompt in Windows and then running the appropriate vcvarsall.bat command file.

Is it possible to create a cmd profile that will execute that bat file automatically?

**Comment by encladeus** [comment]
Sure. This is the way I have my profile configured for such a command prompt. One for x86 and one for x64 cross compiler.

```
"commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/Build/vcvars32.bat\"",

"commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/Build/vcvarsx86_amd64.bat\"",
```

**Comment by DavidA2014** [comment]
Thanks for your answer. Would I need to have unique guid for each entry?  Currently I have:

        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false,
            "fontFace": "Cascadia Code",
            "fontSize": 10
        },
        // My profiles for VS2019 Developer Command Prompts
        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "x86 VS2017 Developer Command Prompt",
            "commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build/vcvars32.bat\"",
            "hidden": false,
            "fontFace": "Cascadia Code",
            "fontSize": 10
        },
        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "x64 VS2017 Developer Command Prompt",
            "commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build/vcvars64.bat\"",
            "hidden": false,
            "fontFace": "Cascadia Code",
            "fontSize": 10
        }, 

but I only see one of these profiles in the dropdown menu.

**Comment by encladeus** [comment]
Yes, each will require a unique GUID. I just incremented the last number in the duplicate GUID to make it unique.

**Comment by ffes** [comment]
You might want to add this line to set the CMD icon:

```json
"icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
```

**Comment by ffes** [comment]
> Would I need to have unique guid for each entry?

When include a GUID it needs to be unique. When you don't want to set a profile as default profile a GUID is optional.

**Comment by DavidA2014** [comment]
Thank you both for your answers. All working well now.

I did find that the icon does not work without a GUID.
