### ISSUE TITLE
Possible regression of emoji rendering since 0.6

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3553]
@DHowett-MSFT my man. I'm seeing regression on current master https://github.com/microsoft/terminal/commit/306e75163929161b130872dcae890686da57790d

![图片](https://user-images.githubusercontent.com/4710575/68740302-ba74e100-0625-11ea-8ca4-c02fbf7cc099.png)

_Originally posted by @skyline75489 in https://github.com/microsoft/terminal/issues/3546#issuecomment-553266974_

**Comment by zadjii-msft** [comment]
I'm going to pre-emptively mark this as blocking. We can discuss in triage if this isn't that bad of a regression.

UNFORTUNATELY, I'm not seeing this at all myself :( Black is 0.6, purple is master:
![image](https://user-images.githubusercontent.com/18356694/68772523-99919900-05ef-11ea-8d5a-0b95ae6a4a01.png)

**Comment by skyline75489** [comment]
Could it be my locale setting? I'm in zh-CN locale.

**Comment by zadjii-msft** [comment]
@skyline75489 That's the first thing I thought of. I'd really hate if a CRT change like that would cause this, but hey, who knows.

Just to try and rule out other factors, could you try the following python script?

```python

print('''\
Combining Diacritics    | [a\u0300\u0304]
Polytonic Greek         | [ᾊ] [Α\u0313\u0300\u0345]
Ideographic Variation   | [東京都葛\U000E0101飾区] [奈良県葛\U000E0100城市]
Composite Hangul        | [\u1100\u116A\u11B3]
Combining Dakuten       | [か\u309A]
Emoji vs Text           | [\u2602] [\u2602\uFE0E] [\u2602\uFE0F]
Emoji                   | [\U0001F469]
Emoji with Skin Tone    | [\U0001F469\U0001F3FB]
Emoji Variation and ZWJ | [\U0001F469\U0001F3FB\u200D\U0001F4BB]
''')

```

That should be the same as the Node.JS one - I just want to make sure to rule Node out in this case.

**Comment by skyline75489** [comment]
I'm seeing the same thing with python.

![图片](https://user-images.githubusercontent.com/4710575/68774414-08aad400-0668-11ea-8ece-3eca6f6730ac.png)

**Comment by skyline75489** [comment]
As long as I revert ddcc06e911a18250c8544c7ea83011451e8256a2 (even on master), everything is back to normal.

**Comment by DHowett-MSFT** [comment]
@skyline75489 what if you only revert the `_VC_Target_Library_Platform` part?

**Comment by miniksa** [comment]
You've got to be kidding me. The App CRT is different by locale than the Desktop CRT? :|

**Comment by skyline75489** [comment]
Would it be even more weird if I say that `DynamicLibrary` is the key? I change `winconpty` back to `DynamicLibrary` and it works.  Both `_VC_Target_Library_Platform` and `onecoreuap_apiset.lib` are seemingly irrelevant.

**Comment by DHowett-MSFT** [comment]
Of course! This is the 19H1 emoji bug! @miniksa we aren’t linking the right CreatePseudoConsole. It’s probably the linkage declspec...

**Comment by DHowett-MSFT** [comment]
We can’t repro it locally because the Vb conhost has the fixes.

**Comment by skyline75489** [comment]
Glad you know where the problem is. Guess now I don't need to change my PC's locale to en-US 😄

**Comment by DHowett-MSFT** [comment]
I’m assigning myself because I have the most context.

**Comment by JustinGrote** [comment]
Potentially related, some emojis are super tiny on my system in the console but fine in the titlebar? (They are fine in VSCode et. al.)
![image](https://user-images.githubusercontent.com/15258962/68920906-addab080-072b-11ea-9f02-598333a2012c.png)

**Comment by DHowett-MSFT** [comment]
@JustinGrote that one is #900 :smile:

**Comment by DHowett-MSFT** [comment]
(also, we don't support VS16/`U+FE0F` for a bunch of reasons that are being covered in active threads about unicode (#1472))
