### ISSUE TITLE
Blacklist Docker for Windows WSL2 Service Machines

### ISSUE THREAD

**Issue by bushidocodes** [microsoft/terminal#3556]
# Description of the new feature/enhancement

The latest version of Docker for Windows is adding a WSL2-based backend powered by a series of service machines. Terminal currently discovers these and adds them as options that the user can select. These should probably be blacklisted from being presented to the user in the short-term. I imagine a better long-term solution is for WSL2 to be able to use metadata to differentiate service-machines from user-created machines that I might want to log into.

![image](https://user-images.githubusercontent.com/8700322/68788886-4bda5800-0612-11ea-8016-13a803b97f08.png)

```json
  [
  ...
        {
            "guid": "{d8afdc0e-a636-5b68-89dd-50a9d0b54349}",
            "hidden": false,
            "name": "docker-desktop-data",
            "source": "Windows.Terminal.Wsl"
        },
        {
            "guid": "{570fcb8d-792c-5ac7-ab1f-5cfb2cdfdb99}",
            "hidden": false,
            "name": "docker-desktop",
            "source": "Windows.Terminal.Wsl"
        }
  ],
```

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Ugh. I knew this day would come!

@benhill should we just, like, match the name or something? That seems bad.

**Comment by zadjii-msft** [comment]
@benhillis is the right one 😉

**Comment by benhillis** [comment]
I don't have a strong opinion, but a blacklist doesn't seem like a terrible idea.

**Comment by DHowett-MSFT** [comment]
Sorry about tagging you into a random issue, wrong-Ben.

A disallow list doesn't sound terrible. I mean, it 100% does sound terrible, but it doesn't sound _awful_.

**Comment by benhillis** [comment]
Semantics :)

I don't like it either, I just think it's really our only choice.

**Comment by gmsantos** [comment]
As a workaround, I set these profiles as hidden:

```
    {
        "guid": "{570fcb8d-792c-5ac7-ab1f-5cfb2cdfdb99}",
        "hidden": true,
        "name": "docker-desktop",
        "source": "Windows.Terminal.Wsl"
    },
    {
        "guid": "{d8afdc0e-a636-5b68-89dd-50a9d0b54349}",
        "hidden": true,
        "name": "docker-desktop-data",
        "source": "Windows.Terminal.Wsl"
    }
```

Maybe docker backend could be hidden as default...
