### ISSUE TITLE
Connect GenRTF to conhost (Win32Interactivity Clipboard)

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#3560]
Make conhost do RTF!

@DHowett-MSFT @carlos-zamora What needs to be done to bring this into conhost? Are you gonna create a new issue?

_Originally posted by @anirudhrb in https://github.com/microsoft/terminal/pull/3535#issuecomment-553435031_

**Comment by anirudhrb** [comment]
I would like to pick this up too!

I believe this is the file I should be looking at: https://github.com/microsoft/terminal/blob/master/src/interactivity/win32/Clipboard.cpp

At a high-level, I should do the same things that are being done for HTML copy right?

Also, we are registering a format for HTML here:
https://github.com/microsoft/terminal/blob/13406b746b326f1d15c4aca5f1b61a612afd6bca/src/interactivity/win32/Clipboard.cpp#L303

The way I understand it, any other program that wants to read this HTML needs to know that format name is `HTML Format`. Similarly, is there some standard name for RTF? Is it simply `RTF Format`? Do we document these names somewhere?

Let me know if I'm on the right track here.

**Comment by DHowett-MSFT** [comment]
You’re on the right track! I’ll assign this to you.

I’m not sure what the legacy clipboard API contract is for RTF content, but figuring that out is half the fun!

**Comment by DHowett-MSFT** [comment]
To trigger formatted copy in conhost, you’ll want to hold down <kbd>Alt</kbd> when you issue the final right-click that performs the copy. It’s not “on by default” like Terminal’s is.

**Comment by anirudhrb** [comment]
@DHowett-MSFT raised a PR (#3595) for this. Please review.
