### ISSUE TITLE
Selection Color should invert selected text color

### ISSUE THREAD

**Issue by javierdlg** [microsoft/terminal#3561]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): All
```

# Steps to reproduce

1. Open the terminal.
1. Select some text.

# Expected behavior

Selected text should invert the text colors:

# Actual behavior

Text maintains it's original color which leads to contrast issues. 
![image](https://user-images.githubusercontent.com/2334756/68795006-ed5aad00-0604-11ea-822f-51f3ae4d9c9c.png)

# Notes

Powershell and CMD both invert the text colors when selected, which would fix the contrast ratio accessibility issue present in the terminal:
![image](https://user-images.githubusercontent.com/2334756/68793524-3b21e600-0602-11ea-820f-c1885cb48aa6.png)

**Comment by zadjii-msft** [comment]
_oh no_

This is hard to _very hard_ on the scale of tasks, unfortunately. 

GDI has a very handy function for inverting the colors of a region of the window. unfortunately, DX has so such equivalent function. I believe @miniksa has said something in that past about rendering the frame, then specially inverting the selected area in another rendering pass? He can elaborate more.

**Comment by javierdlg** [comment]
How about being able to choose the selected text foreground color? This could potentially solve the contrast ratio issue on selected text and not force us to vet all the colors against two background colors for every theme.

**Comment by miniksa** [comment]
Didn't #3471 committed today literally just do this?

**Comment by mdtauk** [comment]
> Didn't #3471 committed today literally just do this?

It only includes a Selection Background colour.  I did make the suggestion there should also be a Selection Foreground colour.

**Comment by DHowett-MSFT** [comment]
We're open to contributions to our DX renderer. Thanks!
