### ISSUE TITLE
Windows vim broken on alt screen buffer

### ISSUE THREAD

**Issue by lzybkr** [microsoft/terminal#3562]
# Environment

```none
Microsoft Windows NT 10.0.18363.0
Version: 0.6.3161.0
```

# Steps to reproduce
Run vim from PowerShell with the following PowerShell function:

```powershell
    function vim
    {
        Write-Host "$([char]0x1b)[?1049h"
        vim.exe @args
        Write-Host "$([char]0x1b)[?1049l"
    }
```

This is used to work around how vim screen scrapes the screen so it can restore it, but colors are messed up because screen scraping doesn't work with 24 bit colors.

Edit a file with at least double the number of lines in the window.

Go to the bottom, reposition the cursor, and move the cursor line wise up - rendering will be horribly broken.
<kbd>G</kbd><kbd>z</kbd><kbd>t</kbd><kbd>k</kbd><kbd>k</kbd><kbd>k</kbd><kbd>k</kbd>

Here's a guess at the commit introducing the regression: https://github.com/microsoft/terminal/pull/3160

# Expected behavior

Rendering works the same as on the main screen buffer.

# Actual behavior

Lines are duplicated or sometimes not, it's super confusing to understand what exactly is happening.

**Comment by DHowett-MSFT** [comment]
/cc @j4james 
Any thoughts? Thanks!

**Comment by j4james** [comment]
I wasn't able to reproduce this in vim - not sure if I needed a specific version, or I was just doing something wrong - but I did manage to reproduce a similar issue when running some of my own alt buffer tests.

Note that this doesn't happen in conhost - only the Windows Terminal - so I'm assuming it's got something to do with the conpty layer. Also, I did a bisect, and the actual commit on which it first fails is ddcc06e911a18250c8544c7ea83011451e8256a2, so I don't think the DECSC/DECRC changes had anything to do with it.

I can try and do a bit more digging when I have some time, but the conpty stuff is outside my area of understanding, so I'm not sure I can tell you much more than this.

**Comment by DHowett-MSFT** [comment]
If it fails on ddcc063 (good find, thank you!) it's because we actually stopped using the in-package conhost (#3582, fixes #3553)!

**Comment by j4james** [comment]
Yeah, that looks like the solution. Applying the changes from 0d106c8f9998b9fdf98a699a2246322174c09ac1 fixed the problem for me. Hopefully that means it'll fix the OP's vim problem too.

**Comment by lzybkr** [comment]
It seems fixed now, thanks.

**Comment by DHowett-MSFT** [comment]
This may have actually been caused by #3553 -- we were accidentally using the windows console host instead of the one in the package. 3161 and 3181 both suffered from this :smile:

**Comment by DHowett-MSFT** [comment]
(Incidentally, this means it _also_ works inbox on Windows 20H1, and not in 19H1, for non-Windows Terminal consumers.)
