### ISSUE TITLE
Reproducible freeze / hang in Windows Terminal when under stress and zooming text

### ISSUE THREAD

**Issue by Treit** [microsoft/terminal#3571]
# Environment
Windows build number: 10.0.19023.0
Windows Terminal version: 0.6.2951.0

# Steps to reproduce
1. Download the following simple C# project:
https://github.com/Treit/TerminalStress/tree/master/src
2. Launch wt.exe (Windows Terminal) and start a Developer Command Prompt for VS2019
3. Execute 'dotnet run' from the folder to which you downloaded the project in step 1.
4. While the stress application is running, hold down Ctrl and use the mouse wheel to 'zoom' the text to be larger.

# Expected behavior
No hang.

# Actual behavior
The terminal freezes and becomes unresponsive.

**Comment by DHowett-MSFT** [comment]
This turned out to be a different version of /dup #1360.
