### ISSUE TITLE
Terminal app creates false positives with FireEye rules

### ISSUE THREAD

**Issue by SOM-fermonte** [microsoft/terminal#3579]
This will only be an issue for users in Enterprise environments where there are tight firewall controls.

I don't have access to the Windows Store and I downloaded Windows Terminal from the GitHub page. I installed the required runtimes and was able to launch the app, only to be contacted by network security about alerts coming from my PC. After explaining what I was doing, they said they would submit a ticket for a false positive, but in the meantime I cannot use the application at all without triggering more alerts. If someone who is not familiar with my case is on duty, then I get calls again.

Rather than having issues like this, it is better if Microsoft approaches a few major security vendors with details about Windows Terminal so that they can work out the kinks in their rules. This would avoid issues when trying to do the product launch next year.

**Comment by DHowett-MSFT** [comment]
Thanks. We'll track this with its counterpart /dup #2568.
