### ISSUE TITLE
Reordering tabs crashes when Terminal is running elevated

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#3581]
# Environment

Windows build 10.0.18362.0
Windows Terminal version (if applicable): 0.6.3161.0

# Steps to reproduce

Launch Terminal as administrator.
Create a couple of tabs.
Try to reorder the tabs via click+drag

# Expected behavior

Tabs are reordered

# Actual behavior

Terminal crashes

**Comment by DHowett-MSFT** [comment]
Amazing. I bet this is a platform feature.

**Comment by DHowett-MSFT** [comment]
(related to XAML islands, tearouts, capturing the mouse across elevation boundaries, etc.)

**Comment by DHowett-MSFT** [comment]
This is now being tracked as MSFT:24041938.

**Comment by Alacritous** [comment]
Are you guys trying to heal this bug holistically or something?

**Comment by DHowett-MSFT** [comment]
You're funny.
If by holistically you mean "by approaching the people on the Windows platform who own drag/drop to let them know that the drag/drop model doesn't support this use case properly" and "getting them to consider this a valuable feature", yes.

**Comment by Alacritous** [comment]
So, you're saying it's unequivocally their fault?   That's brave of you.

**Comment by miniksa** [comment]
The platform team has said that they are not going to fix it. They want us to detect when running as administrator and disable drag & drop activity.
