### ISSUE TITLE
Add ability to save console scroll buffer to a file.

### ISSUE THREAD

**Issue by swpalmer** [microsoft/terminal#3584]
# Description of the new feature/enhancement

Add the ability to save the scroll buffer to a file so it can be easily searched and large regions can be copied and pasted.

# Proposed technical implementation details (optional)

You have the buffer... adding a context menu to the tab to save the history shouldn't be to hard.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This looks like it's actually something that's already been suggested, so I'll direct discussion to that thread. 

/dup #642

Thanks!
