### ISSUE TITLE
Queue Commands using a Sequential manner. 

### ISSUE THREAD

**Issue by jaibeer72** [microsoft/terminal#3591]
# Command Queue language or simple Commands Queue 
To be able to in a single command time queue up multiple commands that can either run sequentially or based on conditions(especially if integrated well). 

for example, in my program, I use Mercurial, with Perl for build environment and python to run tests. Sometimes I want to locally run it like 

```cmd 
→ C:\Users\project› q-commands (perl build.pl workspace --androidSupport=true >
                                 if("build sucessful"),
                                 [py tests.py --test-project=Android --test-filter=GradelTests]
                                 | hg up -r fixedBranch)
```

# Proposed technical implementation details
   personally not sure how can we implement it but this seems super useful and new build dev friendly and overall expandable over time. 
   Allowing python or other languages that we can build pipelines in to have the ability to provide ```explicit.terminal.outs``` 
  where you can basically have on a function in python that simple returns 
```python 
   def isBuildSucessful(): 
         wte.explicitoutbool("isBuildSucessful",True)
```
and in the terminal we can have 
```Terminal
→ C:\Users\project›py main.py .explicit-return("isBuildSuccessful")
→ C:\Users\project› True
```

**Comment by DHowett-MSFT** [comment]
Couple things here. It's a good idea! It is also an idea for a _shell_, not for a terminal, to implement. Terminals deal in text and text only. They don't _know_ that ";" is a command separator, or anything else.

It's such a good idea, though, that almost every shell already has support for something like this...

## powershell

### chaining commands

```powershell
./build; ./deploy
```

### conditional

```powershell
If (./build) {
    Echo "It worked!"
} Else {
    Echo "Beefed it"
}
```

### conditional (powershell 7)

```powershell
./build && echo "it worked"
```

## bash

### chaining commands

```bash
./build; echo "it completed"
```

### conditional

```bash
./build && echo "it worked" || echo "it failed"
```
