### ISSUE TITLE
Choose your own editor for Settings

### ISSUE THREAD

**Issue by AndrewR66** [microsoft/terminal#3592]
When I pick Settings in the dropdown menu, profile.json opens in Visual Studio. This is slow. I would like to open it in a smaller/faster editor. I suppose it opens in VS due to my windows file extension settings for .json files. I don't wan't to change this setting, but I would like a seperate setting where I can choose my editor.

# Proposed technical implementation details (optional)

With the new feature:
1) I will somehow pick editor for editing settings.
2) When I choose to edit settings, profile.json opens in the editor from 1)

**Comment by DHowett-MSFT** [comment]
Hey @AndrewR66, thanks for the request! On the balance, this seems like a _huge_ amount of work (providing an in-terminal file association UI) for a pretty narrow use case. If you don't mind, though, why are you averse to changing your default JSON association? VS is going to be huge and take forever to load regardless of which JSON file you're opening, so it might be advantageous to just change the association everywhere.

**Comment by AndrewR66** [comment]
Thank you for responding, I think I'll change my JSON association after all, like you suggest.
