### ISSUE TITLE
CMD: Typing chars until line break and then back space confuses typing position

### ISSUE THREAD

**Issue by devsko** [microsoft/terminal#3594]
# Environment

```none
Windows build number: 10.0.18363.476
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

- Open cmd
- Type any chars until line breaks
- Type ```Backspace``` until the cursor gets back to the previous row
# Expected behavior

Every ```Backspace``` should delete one char
# Actual behavior

When cursor changes line there is one additional space to delete and the typing position is off by one afterward.
PS seems to work correctly
Deleting chars with ```Del``` seems to work correctly

**Comment by VikingScientist** [comment]
```
Windows build number: 10.0.18362
Windows Terminal version (if applicable): 0.6.2951.0
```

Bug appears on my setup as well. Note: it is only a visual bug. Increasing font size up and down again "fixes it": the extra space vanishes and the cursor is in the right place. Looking at the command which is run, then there is no space in this command.

**Comment by zadjii-msft** [comment]
Thanks for the bug report! This is actually something that's already been reported, so I'm going to redirect conversation to the original thread.

/dupe #1245

Thanks!
