### ISSUE TITLE
Terminal doesn't resize if historySize is set to ~32700 or larger

### ISSUE THREAD

**Issue by sphennings** [microsoft/terminal#3599]
# Environment

```
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version: 0.6.2951.0
```

# Steps to reproduce

1. Set the `historySize` of a terminal profile to a sufficiently large number. (I modified the default profiles in my testing)
  - 32747 or larger for powershell
  - 32797 or larger for wsl
2. Create a new terminal tab using the modified profile
3. Record the current reported terminal size
  - Use `$Host.UI.RawUI.WindowSize.Width; $Host.UI.RawUI.WindowSize.Height` for powershell
  - Use `tput cols; tput lines` for wsl
4. Resize the terminal window
5. Record the new reported terminal size

# Expected behavior

Resizing the terminal window should change the reported terminal dimensions. 

Terminal resize behavior should be unaffected by historySize.  

# Actual behavior

When the historySize profile setting is sufficiently large resizing the terminal window does not change the reported terminal dimensions.

**Comment by egmontkob** [comment]
Is this perhaps the same as #2815?

**Comment by zadjii-msft** [comment]
Yea this looks like a /dup of #2815. Thanks for the early triage pass @egmontkob!
