### ISSUE TITLE
Windows Terminal Status Updates

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#3600]
This issue contains all of the status updates for Windows Terminal. This helps provide insight into where the project is at between releases.

Feel free to subscribe to this issue to receive updates whenever we post another status update.

Comments have been disabled for this issue in order to reduce noise. Please use [this issue](https://github.com/microsoft/terminal/issues/3601) for any discussion relating to status updates.

**Comment by cinnamon-msft** [comment]
# October 25, 2019 Status

## Recent News / Releases

### [Terminal 1910 was released on Wednesday][1]

* Announced dynamic profiles and cascading settings
* New tabs from WinUI

![Terminal v0.6](https://raw.githubusercontent.com/microsoft/terminal/master/doc/images/terminal-0.6.png "Terminal v0.6")

* These look very much like our original mockups from March :)

![Terminal Mockup](https://raw.githubusercontent.com/microsoft/terminal/master/doc/images/terminal-mockup.png "Terminal Mockup")

## Current Status

### Plan for 1911 is in place

* Accessibility improvements
* Suppress application title
* Progress on search functionality
* UI tweaks
* Bug fixes
* (Fewer features because of Ignite)

### Cascadia Code

* Features currently in scope:
    * UFO conversion
    * Character extensions (Cyrillic, Greek, and Vietnamese)

### Ignite Session

* Carlos and Kayla are delivering a 45-minute breakout session at Ignite

## [Windows In-box Console/ConHost 20H1 Issues][2]

## [Terminal 1911 Work][3]

## [Terminal Roadmap][4]

[1]: https://devblogs.microsoft.com/commandline/windows-terminal-preview-1910-release/
[2]: https://github.com/microsoft/terminal/milestone/9
[3]: https://github.com/microsoft/terminal/milestone/16
[4]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by cinnamon-msft** [comment]
# November 15, 2019 Status

## Recent News / Releases

### Terminal 1911 will be released in 2 weeks

* Terminal 1911 (v0.7) was released to selfhosters yesterday and another version will be released next week. The release will go out to the public on Tuesday, 11/26
* Features include:
	* Tab reordering
		* You can now rearrange your tabs within the Terminal window!
	* Panes
	* Opening multiple terminal sessions within the same tab is supported!
		* ![Terminal Panes](https://raw.githubusercontent.com/microsoft/terminal/master/doc/images/panes.png "Terminal Panes")
	* Bug fixes
		* Line endings when pasting in WSL is fixed!
		* Profiles without starting directories won’t crash!
		* Using Alt+Arrow-Keys won’t print extra characters!

### Ignite session

* Carlos and Kayla delivered a 45 minute session at Ignite
* Session link: [https://myignite.techcommunity.microsoft.com/sessions/81329?source=sessions][1]

## Current Status

### Planning for 1912 will occur on Monday, 11/18

* We're planning to be feature complete in 1912
 
### Cascadia Code

* Additional features that have been approved:
	* UFO conversion
	* Character extensions (Cyrillic, Greek, and Vietnamese)
	* Aaron (our font designer) has a draft PR in covering both the UFO conversion and character extensions
   
## [Terminal 1911 Work][2]

## [Terminal Roadmap][3]

[1]: https://myignite.techcommunity.microsoft.com/sessions/81329?source=sessions
[2]: https://github.com/microsoft/terminal/milestone/16
[3]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by cinnamon-msft** [comment]
# December 5, 2019 Status

## Recent News / Releases

### Terminal v0.7 was released on Tuesday 11/26

* Features included:
	* Tab reordering
	* Panes (multiple terminal windows within the same tab)
	* Suppress application title (custom tab titles)
	* Bug fixes
		* Copying and pasting works better now :)

### Terminal v0.8 is scheduled for 1/7

* Planned features include:
	* Search (below are mockups)
![image](https://user-images.githubusercontent.com/48369326/70285152-615b2180-177b-11ea-83fd-2e5f568f37bd.png)
![image](https://user-images.githubusercontent.com/48369326/70285162-691ac600-177b-11ea-941c-8d7769ab3a1c.png)
	* Accessibility improvements
	* VT mouse mode
	* Tab sizing (below are mockups)
![image](https://user-images.githubusercontent.com/48369326/70285184-7e8ff000-177b-11ea-962e-f4cf416ce897.png)
![image](https://user-images.githubusercontent.com/48369326/70285189-818ae080-177b-11ea-9b50-2c2b92958f9d.png)
	* Servicing releases are scheduled for before the holidays
		* Bug fixes!

### Cascadia Code

* https://github.com/microsoft/cascadia-code/releases
* New versions include:
	* Cascadia Code
		* Base version, includes coding ligatures, new version includes character tweaks
	* Cascadia Mono
		* Does not include coding ligatures
	* Cascadia Code PL
		* Base version with powerline glyphs
	* Cascadia Mono PL
		* No coding ligatures, with powerline glyphs
	* The newest base version of Cascadia Code was shipped inside the v0.7 Terminal release

## Community News

### Node+JS Interactive

* Kayla is going to Node+JS Interactive in Montreal from December 10 - 12
* Demo/Labs on Windows Subsystem for Linux 2 (WSL 2) and Terminal
* 20 minute lightning talk: The New Command Line Experience on Windows
   
## [Terminal 1912 Work][1]

## [Terminal Roadmap][2]

[1]: https://github.com/microsoft/terminal/milestone/17
[2]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by cinnamon-msft** [comment]
# January 9, 2020 Status

## Recent News / Releases

### Terminal v0.8 will be released on Tuesday 1/14

* Release candidate is going out to internal Microsoft employees today
* Features include:
	* Search
![image](https://user-images.githubusercontent.com/48369326/72114501-96b5da80-32f8-11ea-886c-14fb89657cf9.png)
	* Tab sizing
![image](https://user-images.githubusercontent.com/48369326/72114515-a6352380-32f8-11ea-9a06-4da22fc05916.png)
![image](https://user-images.githubusercontent.com/48369326/72114522-ac2b0480-32f8-11ea-9adc-181e41dac81c.png)
	* Retro-style CRT effects (experimental feature)
![image](https://user-images.githubusercontent.com/48369326/72114572-e8f6fb80-32f8-11ea-9c6e-fea966fd760e.png)
(font used is PxPlus IBM VBA8 from https://int10h.org/oldschool-pc-fonts/)
	* Enhanced panes and tabs key bindings
		* You can now specify a profile to open using custom key bindings
		* Ex:
		`{
			"command": {
				"action": "newTab",
				"profile": "Ubuntu"
			},
			"keys": [ "ctrl+shift+u" ]
		}`
	* Custom default settings
		* You can now apply one setting to all of your profiles in your profiles.json file
![image](https://user-images.githubusercontent.com/48369326/72114933-142e1a80-32fa-11ea-9b7d-a7a53de1f19c.png)

## [Terminal v0.8 Work][1]

## [Terminal v0.9 Work][2]

## [Terminal Roadmap][3]

[1]: https://github.com/microsoft/terminal/milestone/17
[2]: https://github.com/microsoft/terminal/milestone/18
[3]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by cinnamon-msft** [comment]
# January 31, 2020 Status

## Recent News / Releases

### Terminal v0.9 is scheduled for 2/11

* This is the last release that will have new features before the v1 release
* Subsequent releases are strictly for bug fixes and polishing
* Features include:
	* Command line arguments
		* new-tab, split-pane, focus-tab
		* Examples:
			* wt -d . (opens a new Terminal in the current working directory)
			* wt -p "profile name" (opens a new Terminal with the given profile)
			* wt; new-tab -p "profile name"; split-pane -V -p "profile name" (demonstrated below)
![terminal-cla](https://user-images.githubusercontent.com/48369326/73583802-0840fe80-4449-11ea-9c63-0659edca2c84.gif)
	* Accessibility improvements

### Community News
#### One Dev Minute Videos

* Kayla has recorded some One Dev Minute videos about the Terminal
* Three have been released so far:
	* https://twitter.com/WindowsDocs/status/1220020741409837056
	* https://twitter.com/WindowsDocs/status/1221826568349196288
	* https://twitter.com/WindowsDocs/status/1222551369883832324

## [Terminal v0.9 Work][1]

## [Terminal Roadmap][2]

[1]: https://github.com/microsoft/terminal/milestone/18
[2]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by cinnamon-msft** [comment]
# April 3, 2020 Status

## Recent News / Releases

### Settings changes are coming

* The following changes have been made on GitHub and will be released via the Store in our next servicing release (v0.11):
    * Profiles.json has been renamed to settings.json
    * <kbd>Ctrl+c/v</kbd> will be shipped inside the settings.json file for copy and paste
        * <kbd>Ctrl+shift+c/v</kbd> will still be bound be default to copy and paste in the defaults.json file
    * The following settings have been deprecated on the master branch:

| Deprecated Setting | Replacement Setting |
| ------------------ | ------------------- |
| `copyTextWithoutNewlines` | `{ "command": { "action": "copy", "singleLine": true }, "keys": "ctrl+c" }` |
| `decreaseFontSize`   | `{ "command": { "action": "adjustFontSize", "delta": -1 }, "keys": "ctrl+-" }` |
| `increaseFontSize`   | `{ "command": { "action": "adjustFontSize", "delta": 1 }, "keys": "ctrl+=" }` |
| `moveFocusDown`      | `{ "command": { "action": "moveFocus", "direction": "down" }, "keys": "alt+down" }` |
| `moveFocusUp`        | `{ "command": { "action": "moveFocus", "direction": "up" }, "keys": "alt+up" }` |
| `moveFocusLeft`      | `{ "command": { "action": "moveFocus", "direction": "left" }, "keys": "alt+left" }` |
| `moveFocusRight`     | `{ "command": { "action": "moveFocus", "direction": "right" }, "keys": "alt+right" }` |
| `newTabProfile0 - newTabProfile8` | `{ "command": { "action": "newTab", "index": NUMBER }, "keys": "ctrl+shift+NUMBER" }` |
| `resizePaneDown`     | `{ "command": { "action": "resizePane", "direction": "down" }, "keys": "alt+shift+down" }` |
| `resizePaneUp`       | `{ "command": { "action": "resizePane", "direction": "up" }, "keys": "alt+shift+up" }` |
| `resizePaneLeft`     | `{ "command": { "action": "resizePane", "direction": "left" }, "keys": "alt+shift+left" }` |
| `resizePaneRight`    | `{ "command": { "action": "resizePane", "direction": "right" }, "keys": "alt+shift+right" }` |
| `splitHorizontal`    | `{ "command": { "action": "splitPane", "split": "horizontal"}, "keys": "alt+shift+-" }` |
| `splitVertical`      | `{ "command": { "action": "splitPane", "split": "vertical"}, "keys": "alt+shift+plus" }` |
| `switchToTab0 - switchToTab8` | `{ "command": { "action": "switchToTab", "index": NUMBER }, "keys": "ctrl+alt+NUMBER" }` |
| `trimWhitespace`     | `{ "command": { "action": "copy", "singleLine": true }, "keys": "ctrl+c" }` |

## [Terminal v1.0 Work][1]

## [Terminal Roadmap][2]

[1]: https://github.com/microsoft/terminal/milestone/6
[2]: https://github.com/microsoft/terminal/blob/master/doc/terminal-v1-roadmap.md

**Comment by zadjii-msft** [comment]
We've kinda gone in another direction with posting status updates. I'm gonna close this one out for now.
