### ISSUE TITLE
Discussion for Windows Terminal Status Updates

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#3601]
Please use this issue to comment on or ask questions about status updates posted in #3600

**Comment by phongtruongg** [comment]
I see you missing this feature in Terminal 1911 changelog (or is it not release in this ver?)
[Increase left padding around tabs](https://imgur.com/uDq4Yfl)

**Comment by DHowett-MSFT** [comment]
The list of changes in the status update is intended to be a broad overview. The fine-grained changelog will be available on the Releases page with the release.

**Comment by JushBJJ** [comment]
What are the keybinds for opening a new pane and splitting vertically or horizontally?

**Comment by devnoname120** [comment]
I would suggest linking to the relevant commits/pull requests/issues inside the status update messages.

**Comment by cinnamon-msft** [comment]
@JushBJJ they can be found here: #3544 😊

**Comment by mnpenner** [comment]
The new `wt` open new terminal and split commands look great. I've often wanted this so that I can boot up a project consisting of multiple servers all at once. Will we be able to run arbitrary commands in each pane in addition to choosing a profile?

**Comment by zadjii-msft** [comment]
@mnpenner Yep! Both `new-tab` and `split-pane` support passing a `commandline`. See [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#split-pane) for details.

**Comment by AnuthaDev** [comment]
@DHowett Maybe update #3600 or if not atleast unpin/close it...

**Comment by DHowett** [comment]
@AnuthaDev I’m not the person who updates #3600. What info are you looking for, specifically?

**Comment by AnuthaDev** [comment]
@DHowett Not anything in particular, its just... weird that a pinned issue has outdated info...

**Comment by Ricardonacif** [comment]
I have a .exe application that right now opens with the regular powershell. Is there a way to make it open with the new windows terminal? Can I ship it with this new app?

**Comment by zadjii-msft** [comment]
@Ricardonacif The work that's being done in #492 will let _any_ application open in the Terminal window by default, instead of the vintage console. So hopefully in the near future, you won't have to do _anything at all_.

**Comment by Ricardonacif** [comment]
> @Ricardonacif The work that's being done in #492 will let _any_ application open in the Terminal window by default, instead of the vintage console. So hopefully in the near future, you won't have to do _anything at all_.

But if I need it right now, do you suggest me anything? My idea was to ship the Windows Terminal with the application, and ship a .ps1 file that would open the Windows Terminal with parameters to run my .exe file. Makes sense?

**Comment by zadjii-msft** [comment]
We've kinda gone in another direction with posting status updates. I'm gonna close this one out for now.
