### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by aoandres** [microsoft/terminal#3602]
it would be so cool if you guys included ubuntu terminal to windows terminal in microsoft store...
sorry for posting it here,i am an average user...i dont jnow how to compile gits, and choco installer giving me errors when im logging on as admin

**Comment by DHowett-MSFT** [comment]
@aoandres thanks for submitting an issue! Would you mind telling me what version of Windows you're using?

When you submit a new issue, there is usually a template that you can fill out to give us more information. That information is very helpful in figuring out your issue!

**Comment by Luuk34** [comment]
'Ubuntu' has noting to do with 'Windows Terminal'.

'Ubuntu' can be installed via this link: https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab

If you want in included in your previously installed 'Windows Terminal', than delete the profile (on 1 line):
`DELETE C:\Users\%USERNAME%\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json`


or remove 'Windows Terminal' and do a re-install.

**Comment by aoandres** [comment]
I enabled windows Linux subsystem and got it working beatifully...we can close the topic now...
