### ISSUE TITLE
Reload PATH when opening new Powershell instance

### ISSUE THREAD

**Issue by KSiig** [microsoft/terminal#3605]
# Description of the new feature/enhancement

When opening a new Powershell tab, it seems to use the same PATH that was present when opening Terminal. It would be nice if it used the updated path, like what you'd expect from opening a new tab in Linux.

I just installed node, and was wondering why the `node -v` command wouldn't work. Opened a regular powershell instance and it worked, which is why I believe it simply stems from Terminal not reloading the PATH.

**Comment by piotrpalek** [comment]
I just wanted to open the same issue :) 

In addition to the above, opening splits should also keep the current PATH / working directory.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that's already being tracked in another thread. I'll redirect discussion there:

/dup #1125
