### ISSUE TITLE
无法使用输入法输入中文

### ISSUE THREAD

**Issue by shilei-exists** [microsoft/terminal#3606]
版本：0.6.2951.0
Windows版本：18363.476

通过win+space切换至中文输入法后，无法输入中文，有问题的输入法包括：
微软拼音输入法，版本：系统自带；
小狼毫，版本：0.12.0；
手心输入法，版本：2.7.0.1702；

具体表现为，切换输入法后，系统托盘图标显示切换成功，但是输入的内容实际还是英文。

**Comment by DHowett-MSFT** [comment]
Machine translation:

> The specific performance is that after switching the input method, the system tray icon display is successfully switched, but the input content is actually English.

This is a /dupe of #2213
