### ISSUE TITLE
UI: add option to remove title/tab bars, extra buttons, resize box

### ISSUE THREAD

**Issue by eugenesvk** [microsoft/terminal#3610]
# (short) Description of the new feature/enhancement
**Problem**: Some users don't need/like a window title bar with min/max/close buttons and view these default UI elements as a minor design flaw/waste of screen real estate. Same for an empty tab bar with e.g. add-tab button. Likewise for the window resizing borders (these take to space, but needlessly change the mouse cursor)
**Proposed solution**: Please add an user configuration option to completely remove all of thse elements:
1-2) the title bar itself AND min/max/close buttons (currently I can only remove the title bar, but leave the buttons with the `"showTabsInTitlebar": true`
3) window resize borders (so that hovering over the window border would do nothing) 
**Ideal result**: only tabs are visible above the terminal window, nothing extra (no title/tab bars)
**User benefit**: no unnecessary window elements are visible

# (longer) Description 
I'm never using the default Window controls as there are way more convenient ways to:
- resize: instead of trying to precision-target the little right window border to make the window wider I just <kbd>Win</kbd><kbd>RMB</kbd> in the general right area of the window and then move my mouse left/right to change the window's width (thanks, [AltDrag](https://stefansundin.github.io/altdrag/))
- move: <kbd>Win</kbd>+Mouse
- minimize/maximize: use mouse gestures, e.g. <kbd>RMB</kbd><kbd>↑</kbd> to maximize (thanks, [StrokesPlus)](https://www.strokesplus.net/)
- close: any convenient keyboard shortcut, e.g. <kbd>Ctrl</kbd><kbd>Q</kbd>

As a result, I consider the default min/max/close buttons in the title bar as well as the title bar itself as well as the empty tab bar to be a waste of space. Also, moving a mouse pointer over the window borders changes its icon, which is not ideal as that's a useless signal to me

While I'm able to **partially** fix it with a script to remove the **WS_Caption** (0x00C00000) and **WS_SizeBox** (0x00040000) window properties (thanks, [AutoHotkey](https://www.autohotkey.com/)), I thought that you could support such visual no title/tab bar/no borders modifications natively given the advanced features you plan for it

**Comment by zadjii-msft** [comment]
Thanks for the detailed write-up! It looks to me like you're looking for #2238, so I'll direct conversation to that thread instead.

/dup #2238

**Comment by eugenesvk** [comment]
@zadjii-msft would you then please reopen this request as it's still currently not implemented despite the fact the both this and the supposedly duplicate request are closed: I'd still like to be able to have options to remove the useless window elements listed above:
- window resize box/border
- window title bar with the min/max/close buttons
- 'open a new tab' plus button
- 'open a new tab' drop-down button
- window tab bar (but NOT the tabs themselves)

Thanks!

**Comment by DHowett** [comment]
@eugenesvk it sounds like what you're asking for is just focus mode? we hide the tab bar (but you can still use tabs) and all those other things too. What specifically are you looking for that _isn't_ focus mode?

**Comment by eugenesvk** [comment]
Not really, focus mode is actually worse vs what I can achieve on my own with the aforementioned Autohotkey tricks:

**Focus mode**:
- resize border is still there
- 😱 my tabs are gone! I don't need to remove the tabs themselves, they contain valuable information about my sessions!
- (title bar is also not removed properly, there is still a thick grey bar on top, although `showTabsInTitlebar=true` fixes this)

**Autohotkey tricks**:
1. title bar is completelyand cleanly gone (with `showTabsInTitlebar=false`) — there is no gap between tabs and window border
2. border is also completely and cleanly gone
3. single tab can be hidden with `alwaysShowTabs`

😢 however, the other elements are still there:

4. 'open a new tab' plus button (with multiple tabs shown)
5. 'open a new tab' drop-down button (with multiple tabs shown)
6. window tab bar (but NOT the tabs themselves, I need the tags, they're useful)

And that's what I **ultimately want**❗:
- (1,2,3 from the list above) what I can already achieve with AHK (BUT on **launch** instead of post-launch as it's a bit annoying)
- `+` (4, 5, 6) options to remove of the other three tab bar elements that I can't remove on my own even with AHK
- While retaining the tabs themselves!

**Comment by DHowett** [comment]
The resize border is a single pixel on each edge -- I'm not gonna compromise on its existence. Sorry. :smile:

I'm still struggling to understand how you envision having tabs but no tab bar. Mind putting together a quick mock-up? They have to take up space, overlap the terminal (which is just going to be _more annoying_) or be completely invisible but accessible via keyboard shortcuts.

**Comment by eugenesvk** [comment]
> The resize border is a single pixel on each edge -- I'm not gonna compromise on its existence. Sorry. 😄

But you don't need to compromise, you just need to add a very simple option to remove one of the window element/styles I mentioned in the original description (and that pixel will be gone as a bonus)! And no, it's not really about "a single pixel on each edge", as I mentioned in the original description the key issue is that this useless resize border affects mouse cursor when it's hovering over the borders:
> Also, moving a mouse pointer over the window borders changes its icon, which is not ideal as that's a useless signal to me

 — check out the mouse cursor in my screenshot below, it's not `←→` despite being on the window border (think it might be a pixel or two off), but of a regular form because I've removed the resize/border box with AHK)

I just don't get how a pro tool can be customized via a script in a better way rather than via a native config!


>I'm still struggling to understand how you envision having tabs but no tab bar.

Like so — by removing all the area within the red boxes, so the first tab would start from the topmost-leftmost corner and to the right from the second tab there would be nothing, just the desktop/other windows
So I'd still have tabs (two tabs in this screenshot), but I'd have to tab bar (all the grey area within the red boxes) — or you could say that the width of the tab bar = the sum of the width of the tabs
![WT-Remove](https://user-images.githubusercontent.com/12956286/108121131-5b690c00-70b3-11eb-8f19-9f5a76c2d632.png)

> overlap the terminal...

That's not what I'm looking for, I'm fine with tabs being **on top** of a terminal window and being there permanently except for when there is a single one (that's why I don't like the focus mode as it hides all the tabs), though a less annoying implementation of this alternative might be to show the overlapping tabs only during some actions (e.g. during tab switching or <kbd>alt</kbd> press or mouse movements or something else) — not sure how annoying this would be in practice given that I've never used terminal with such an interesting implementation of tabs
