### ISSUE TITLE
The Terminal crashes when dragging the window to a secondary monitor

### ISSUE THREAD

**Issue by blkwtch** [microsoft/terminal#3611]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal Version: 0.6.2951.0


Any other software?: NO
```

# Steps to reproduce

when i open the terminal on my surface laptop it works fine but when i try to drag the windows to another monitor, the application crashes.
i have a surface laptop hooked up to surface dock which is connected to 2 monitors and the behavior appears on both of them

# Expected behavior

the terminal stays open and might change the size and the resolution depending on the monitor

# Actual behavior

the terminal window crashes and all the tabs in the windows get closed

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that's already being tracked by another issue:

/dup #3303 

Please make sure to search when filing new issues. Thanks!
