### ISSUE TITLE
Provide Windows version in the about box

### ISSUE THREAD

**Issue by teobugslayer** [microsoft/terminal#3616]
# Description of the new feature/enhancement

To simplify bug reporting, please provide the version you request from the community in one place.

I suggest adding the windows version in WT's About box and let the users easily copy/paste it in the GitHub issues.

**Comment by zadjii-msft** [comment]
This is actually something we've had in the terminal since the first public release...
![image](https://user-images.githubusercontent.com/18356694/69059430-1ef3bf80-09db-11ea-9ea5-2cb277c55f88.png)

/dup #867 #1196 #1335 #1452

**Comment by DHowett-MSFT** [comment]
This one actually looks like a request for the _OS version_, which does seem useful.

**Comment by teobugslayer** [comment]
Yep, I meant to ask to show the OS version, which is required to submit a Github issue. Just saving one annopying step in the process.

**Comment by mkitzan** [comment]
I'll look into an implementation for this

**Comment by mkitzan** [comment]
Coming along. What OS version formatting would be most helpful for the dev team so users could just copy-paste the text in their issue post?
<img width="556" alt="in-progress" src="https://user-images.githubusercontent.com/28279285/69474970-32f14580-0d7c-11ea-88ba-7c60a71d63d2.PNG">

**Comment by zadjii-msft** [comment]
@mkitzan Honestly that looks pretty good to me. I probably wouldn't even move the `_GetWindowsVersion` function, since the `TerminalPage` is generally responsible for building the rest of that dialog, I think it fits well there.

**Comment by mkitzan** [comment]
Sounds good, I'll make a PR for this fix.

**Comment by mdtauk** [comment]
Is the full build number needed, over say the 1909 versioning?

**Comment by DHowett-MSFT** [comment]
@mdtauk since we are the windows console team, and the console subsystem is part of windows, and it can be serviced with an update I’m going to say _yes absolutely_

**Comment by mdtauk** [comment]
> @mdtauk since we are the windows console team, and the console subsystem is part of windows, and it can be serviced with an update I’m going to say _yes absolutely_

Good good!  Perfect justification.

**Comment by zadjii-msft** [comment]
Hey there's a really long conversation in #3696 about why we're not doing this. If anyone's interested in the reasons why, go read that PR. Thanks!
