### ISSUE TITLE
Start in WT?

### ISSUE THREAD

**Issue by Timothep** [microsoft/terminal#3617]
I'm not sure if this is already a way to do this or not...

I have two long running python scripts that I run from Powershell. Instead of opening two PS Windows and then calling the the scripts manually, I created a batch file that spins up two instances of Powershell and calls the scripts on each:

`start powershell -noexit -executionpolicy remotesigned .\some_path\script.py -somearguments`

I was wondering if there is a way to tell it to spin the Powershell windows inside the new Windows Terminal?

**Comment by zadjii-msft** [comment]
Funnily enough, I literally _just_ replied to an internal mail thread on this exact question. From that thread:

> It _might_ be more possible once commandline args (#607/#3495) lands, though that’s not really slated for 1.0. With that, you'd be able to call `wt.exe <some command>` and have that run `<some command>` in a Windows Terminal window.
> We do have plans to enable users to configure their “default terminal emulator” on Windows, though that won’t land for a while. You can track the that request at microsoft/terminal#492.

Broadly, this is a /dup of #492, so I'll direct conversation to that thread. Thanks!
