### ISSUE TITLE
Terminal windows crash when you RDP in

### ISSUE THREAD

**Issue by stevenh** [microsoft/terminal#3620]
# Environment

```none
Microsoft Windows [Version 10.0.18362.449]
Windows Terminal (Preview)
Version: 0.6.2951.0
```

# Steps to reproduce

Log on to a machine using RDP which is already running a terminal, in my case they where Ubuntu terminals.

# Expected behaviour

The terminals should remain running.

# Actual behaviour

All terminals crash.

Details from event viewer
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: ucrtbase.dll, version: 10.0.18362.387, time stamp: 0x4361b720
Exception code: 0xc0000409
Fault offset: 0x000000000006db8e
Faulting process ID: 0x23ec
Faulting application start time: 0x01d59e0083a1795f
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 98ac8e04-9879-4c10-a5e1-c47ab781f51a
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by stevenh** [comment]
Could you clarify where to find that, the feedback link in terminal just links to the github issues page, I can't find anything that looks like the above.

**Comment by zadjii-msft** [comment]
@stevenh That's in the "Feddback Hub" app

**Comment by stevenh** [comment]
Sorry I must be missing something as the feedbackup Hub app doesn't have an option to provide feedback for the terminal app.

All I get is:
![image](https://user-images.githubusercontent.com/104239/69551689-03695580-0f95-11ea-9bdf-f17d64a38fee.png)

**Comment by zadjii-msft** [comment]
@stevenh You need to scroll that first list up to "Apps":
![image](https://user-images.githubusercontent.com/18356694/69568008-58e73780-0f80-11ea-8082-bf58893f3d45.png)

Once you select Apps, it'll populate the second dropdown with all your installed applications.

**Comment by stevenh** [comment]
Thanks @zadjii-msft I must say that's terrible UI on Feedback Hub

- It pre-selects an random category from the list
- It hides the scrollbar really quickly, when it does display one, doesn't always see my screenshot.
- It looks like the list is alphabetical but isn't `Apps`, `Gaming and Xbox` then `Accessibility`
- Search doesn't work well, I had to open `App and Features` to find the exact name of the Terminal app `Windows Terminal (Preview)` as scrolling through hundreds in the list would have take ages.
- No suitable option in the `Which of the following best describes your problem?` really no option to report an application crash?

I'm sure this was meant to make things easier but it's been a real pain to get to this point. Compare that to the simplicity of raising the github issue an it's night an day, so definitely some improvements that could be made.

Anyway I hope you got the info you required, not sure how its going to get associated to this issue as it didn't ask me for any linking information.

**Comment by zadjii-msft** [comment]
@stevenh After filing your feedback, could you click the "Share my feedback" button? That will give you an aka.ms link you can share that we can use to find the crash report.

![image](https://user-images.githubusercontent.com/18356694/69639737-acaa5d00-1022-11ea-9c4c-f5e5aa39965a.png)
