### ISSUE TITLE
Provide an extension for Windows terminal that provides True VI/VIM like experience

### ISSUE THREAD

**Issue by kprpg** [microsoft/terminal#3621]
I want a way to customize the Windows Terminal (be it "CMD" or "PowerShell" or "Ubuntu" for VI? 

For instance/specifically regardless of whether I am running it as PS, Ubuntu, CMD mode of the Terminal editor, I want the file editing experience including saving ( ESC Key, colon, w q ) file edits to reflect the VI/Vim behavior, without requiring me to specifically open VI to get that experience. 

File save:--> ESC colon w q
Copy line :--> yy
Copy N lines from cursor :-> Nyy
Delete current line :--> dd
Delete N lines:--> Ndd
string substitute for occurrence between lines 20 and 30:--> 20:30 s/originalPattern/replacePattern/
etc. etc.

**Comment by DHowett-MSFT** [comment]
I'm sorry, I don't quite understand. Windows Terminal isn't a text editor, and we don't have any plans to _become_ a text editor. Most of the operations you've indicated here require a mutable buffer (deleting lines, substituting strings)... which we just aren't going to have.

There _are_ some shells with Vi-like keybindings (PowerShell + PSReadline in Vi mode, ZSH, Bash with `bindkey`).

Are you asking for a modal terminal? Are you asking for Terminal to become a text editor?
