### ISSUE TITLE
Title bar does not respect the system theme

### ISSUE THREAD

**Issue by lorenzodallavecchia** [microsoft/terminal#3624]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0
```

# Steps to reproduce

Open Terminal and look at the window title bar.

# Expected behavior

I would expect the title bar to use the same color/theme as the other apps in the system.

# Actual behavior

The title bar is of a different color (a light gray).

**Comment by zadjii-msft** [comment]
@lorenzodallavecchia  I'm not totally sure, but could you maybe mean "Add a setting to enable the using the Accent Color for the titlebar #1963"?

**Comment by lorenzodallavecchia** [comment]
Thanks for the swift reply @zadjii-msft .
I was expecting the accent color to be used automatically (as per the system setting), but a setting to enable it would be fine too. I will track #1963.
