### ISSUE TITLE
Pasting Issues

### ISSUE THREAD

**Issue by JulianSchneider** [microsoft/terminal#3625]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version (if applicable):  0.6.2951.0

Any other software?
Nano editor 

# Steps to reproduce

Open new file with nano. Write "Before" New line "After". Paste any multiline string with right click or ctrl shift v.

# Expected behavior

```
before
test
test
test
test
after
```

# Actual behavior

```
before

test


after
test

test

test
```

Pasting adds newlines and skips existing entries. Not sure if thats only the case for nano. Works with nano on traditional cmd and bash (wsl).

**Comment by zadjii-msft** [comment]
Thanks for the report! I'm pretty sure this was actually recently resolved in #3449. This should be fixed in the next preview release.

For discussion, I'll refer you to any of the following threads:
/dup #1091
/dup #1094
/dup #2390
/dup #3314
