### ISSUE TITLE
Text display error after restore down

### ISSUE THREAD

**Issue by qiutt1994** [microsoft/terminal#3627]
# Environment

```none
Windows build number: 10.0.19013.0
Windows Terminal version: 0.6.2951.0
```

# Steps to reproduce

1. SSH to a linux. I tired centos7.
2. Maximize the windows terminal window.
3. Enter a command which print something to the terminal. for example "ls".
4. Restore down the window.
5. keep pressing enter to create new lines.

# Expected behavior

Nothing happens.

# Actual behavior

Previous message is shown again.

![bugreportjpg](https://user-images.githubusercontent.com/36209665/69176554-d54fc580-0afd-11ea-9f72-e0643d87b989.jpg)

**Comment by DHowett-MSFT** [comment]
This looks like a /dupe of #1465. Thanks!
