### ISSUE TITLE
Under Solarized Light, the text returned by findstr is not visible

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/terminal#3630]
# Environment

```none
Windows build number: 10.0.18363.418
Windows Terminal version (if applicable): 0.6.2951.0

Any other software? No
```

# Steps to reproduce

Use this json file:
// THIS IS AN AUTO-GENERATED FILE! Changes to this file will be ignored.
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "alwaysShowTabs": true,
    "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "initialCols": 120,
    "initialRows": 30,
    "requestedTheme": "system",
    "showTabsInTitlebar": true,
    "showTerminalTitleInTitlebar": true,
    "wordDelimiters": " /\\()\"'-.,:;<>~!@#$%^&*|+=[]{}~?\u2502",

    "profiles":
    [
        {
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false,
            "startingDirectory": "%USERPROFILE%",
            "closeOnExit": true,
            "colorScheme": "Campbell Powershell",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 12,
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false,
            "startingDirectory": "%USERPROFILE%",
            "closeOnExit": true,
            "colorScheme": "Solarized Light",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 12,
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        }
    ],
    "schemes":
    [
        {
            "name": "Campbell",
            "foreground": "#CCCCCC",
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "red": "#C50F1F",
            "green": "#13A10E",
            "yellow": "#C19C00",
            "blue": "#0037DA",
            "purple": "#881798",
            "cyan": "#3A96DD",
            "white": "#CCCCCC",
            "brightBlack": "#767676",
            "brightRed": "#E74856",
            "brightGreen": "#16C60C",
            "brightYellow": "#F9F1A5",
            "brightBlue": "#3B78FF",
            "brightPurple": "#B4009E",
            "brightCyan": "#61D6D6",
            "brightWhite": "#F2F2F2"
        },
        {
            "name": "Campbell Powershell",
            "foreground": "#CCCCCC",
            "background": "#012456",
            "black": "#0C0C0C",
            "red": "#C50F1F",
            "green": "#13A10E",
            "yellow": "#C19C00",
            "blue": "#0037DA",
            "purple": "#881798",
            "cyan": "#3A96DD",
            "white": "#CCCCCC",
            "brightBlack": "#767676",
            "brightRed": "#E74856",
            "brightGreen": "#16C60C",
            "brightYellow": "#F9F1A5",
            "brightBlue": "#3B78FF",
            "brightPurple": "#B4009E",
            "brightCyan": "#61D6D6",
            "brightWhite": "#F2F2F2"
        },
        {
            "name": "Vintage",
            "foreground": "#C0C0C0",
            "background": "#000000",
            "black": "#000000",
            "red": "#800000",
            "green": "#008000",
            "yellow": "#808000",
            "blue": "#000080",
            "purple": "#800080",
            "cyan": "#008080",
            "white": "#C0C0C0",
            "brightBlack": "#808080",
            "brightRed": "#FF0000",
            "brightGreen": "#00FF00",
            "brightYellow": "#FFFF00",
            "brightBlue": "#0000FF",
            "brightPurple": "#FF00FF",
            "brightCyan": "#00FFFF",
            "brightWhite": "#FFFFFF"
        },
        {
            "name": "One Half Dark",
            "foreground": "#DCDFE4",
            "background": "#282C34",
            "black": "#282C34",
            "red": "#E06C75",
            "green": "#98C379",
            "yellow": "#E5C07B",
            "blue": "#61AFEF",
            "purple": "#C678DD",
            "cyan": "#56B6C2",
            "white": "#DCDFE4",
            "brightBlack": "#5A6374",
            "brightRed": "#E06C75",
            "brightGreen": "#98C379",
            "brightYellow": "#E5C07B",
            "brightBlue": "#61AFEF",
            "brightPurple": "#C678DD",
            "brightCyan": "#56B6C2",
            "brightWhite": "#DCDFE4"
        },
        {
            "name": "One Half Light",
            "foreground": "#383A42",
            "background": "#FAFAFA",
            "black": "#383A42",
            "red": "#E45649",
            "green": "#50A14F",
            "yellow": "#C18301",
            "blue": "#0184BC",
            "purple": "#A626A4",
            "cyan": "#0997B3",
            "white": "#FAFAFA",
            "brightBlack": "#4F525D",
            "brightRed": "#DF6C75",
            "brightGreen": "#98C379",
            "brightYellow": "#E4C07A",
            "brightBlue": "#61AFEF",
            "brightPurple": "#C577DD",
            "brightCyan": "#56B5C1",
            "brightWhite": "#FFFFFF"
        },
        {
            "name": "Solarized Dark",
            "foreground": "#839496",
            "background": "#002B36",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "purple": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightPurple": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3"
        },
        {
            "name": "Solarized Light",
            "foreground": "#657B83",
            "background": "#FDF6E3",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "purple": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightPurple": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3"
        }
    ],
    "keybindings":
    [
        { "command": "closePane", "keys": ["ctrl+shift+w"] },
        { "command": "closeWindow", "keys": ["alt+f4"] },
        { "command": "copy", "keys": ["ctrl+shift+c"] },
        { "command": "duplicateTab", "keys": ["ctrl+shift+d"] },
        { "command": "newTab", "keys": ["ctrl+shift+t"] },
        { "command": "newTabProfile0", "keys": ["ctrl+shift+1"] },
        { "command": "newTabProfile1", "keys": ["ctrl+shift+2"] },
        { "command": "newTabProfile2", "keys": ["ctrl+shift+3"] },
        { "command": "newTabProfile3", "keys": ["ctrl+shift+4"] },
        { "command": "newTabProfile4", "keys": ["ctrl+shift+5"] },
        { "command": "newTabProfile5", "keys": ["ctrl+shift+6"] },
        { "command": "newTabProfile6", "keys": ["ctrl+shift+7"] },
        { "command": "newTabProfile7", "keys": ["ctrl+shift+8"] },
        { "command": "newTabProfile8", "keys": ["ctrl+shift+9"] },
        { "command": "nextTab", "keys": ["ctrl+tab"] },
        { "command": "openNewTabDropdown", "keys": ["ctrl+shift+space"] },
        { "command": "openSettings", "keys": ["ctrl+,"] },
        { "command": "paste", "keys": ["ctrl+shift+v"] },
        { "command": "prevTab", "keys": ["ctrl+shift+tab"] },
        { "command": "scrollDown", "keys": ["ctrl+shift+down"] },
        { "command": "scrollDownPage", "keys": ["ctrl+shift+pgdn"] },
        { "command": "scrollUp", "keys": ["ctrl+shift+up"] },
        { "command": "scrollUpPage", "keys": ["ctrl+shift+pgup"] },
        { "command": "switchToTab0", "keys": ["ctrl+alt+1"] },
        { "command": "switchToTab1", "keys": ["ctrl+alt+2"] },
        { "command": "switchToTab2", "keys": ["ctrl+alt+3"] },
        { "command": "switchToTab3", "keys": ["ctrl+alt+4"] },
        { "command": "switchToTab4", "keys": ["ctrl+alt+5"] },
        { "command": "switchToTab5", "keys": ["ctrl+alt+6"] },
        { "command": "switchToTab6", "keys": ["ctrl+alt+7"] },
        { "command": "switchToTab7", "keys": ["ctrl+alt+8"] },
        { "command": "switchToTab8", "keys": ["ctrl+alt+9"] },
        { "command": "decreaseFontSize", "keys": ["ctrl+-"] },
        { "command": "increaseFontSize", "keys": ["ctrl+="] }
    ]
}

Run "findstr /snip  a *" under a folder with some text files.

# Expected behavior

The file name /line # should be visible.

# Actual behavior

![image](https://user-images.githubusercontent.com/12282281/69194385-e2f55300-0add-11ea-9ad9-d33f4acc86b5.png)

The file name /line # is not visible. Blue Circle.

**Comment by 9527KGG** [comment]
"One Half Light" has similar issue: file name/line# is not visible. 

thanks.

**Comment by j4james** [comment]
I think this might be covered by issue #2661.

**Comment by zadjii-msft** [comment]
@j4james Thanks for finding the dupe! That's correct, this is either #2661 or the related #293, or some variety of that. Either way, this should be resolved when we get to those.

/dup #2661 #293
