### ISSUE TITLE
Provide a concise and automation-friendly way to start Windows Terminal

### ISSUE THREAD

**Issue by noseratio** [microsoft/terminal#3633]
# Description of the new feature/enhancement

I'd like to be able to start Windows Terminal via:

- <kbd>Win</kbd>+<kbd>R</kbd> system dialog
- a desktop shortcut (so I can assign a hot key to it and launch it maximized)
- another console command line prompt (e.g. from CMD or PowerShell started via `CreateProcess` API)
- [ShellExecute](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea) Win32 API

# Proposed technical implementation details (optional)

So far, the only way I'm able to run the Windows Terminal from another console app (or script) is to run it as:

    explorer.exe shell:AppsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!App

or:

    cmd.exe /c start /max shell:AppsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!App

or (from PowerShell):

    explorer.exe shell:AppsFolder\$(get-appxpackage -name Microsoft.WindowsTerminal | select -expandproperty PackageFamilyName)!App

This feels like a hack to me, and it ignores the flag to run maximized, if instructed so in a desktop shortcut (former), or with `start /max` command (latter).

Ideally, Windows Terminal should register itself as [a custom URI handler](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-app-with-uri), and accept arguments like `maximized` etc. via an URI.

**Comment by dhrdlicka** [comment]
There already already is the `wt.exe` execution alias that you could use in such cases.

**Comment by noseratio** [comment]
> There already already is the `wt.exe` execution alias that you could use in such cases.

@dhrdlicka , I'm getting `'wt.exe' is not recognized as an internal or external command`. I've installed WT via `choco install microsoft-windows-terminal`. Just in case, I went ahead and re-installed it, still no `wt.exe`. Am I missing something?

**Comment by noseratio** [comment]
Found it, `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` - thanks!
