### ISSUE TITLE
Feature Request: Show frequently used shells on context menu when pinned to taskbar

### ISSUE THREAD

**Issue by edwnjos** [microsoft/terminal#3634]
When using terminal, its a common pattern to frequently switch between 2 or more different shells, it will be will be really useful if these frequently used shells appear on the context menu when u right click from the pinned terminal on the taskbar. 

This will make the user experience much better, for example: if I wanted to the access a frequently used shell thats not the default, I could just right click the pinned terminal app and select it instead of opening terminal>clicking the down arrow>selecting shell.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually a feature request we're already tracking in #576, so I'll redirect discussion to that thread.

/dup #576
