### ISSUE TITLE
Running git difftool doesn't run external diff tool in foreground

### ISSUE THREAD

**Issue by dracan** [microsoft/terminal#3636]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

* Setup a git diff tool in your git config (see below for example)
* Run `git difftool` in any git repo that has pending changes

Example .gitconfig section...

    [diff]
        tool = winmerge
    [difftool "winmerge"]
        cmd = \"C:/Program Files (x86)/WinMerge/winmergeu.exe\" -e -u \"$LOCAL\" \"$REMOTE\"

# Expected behavior

The external tool appears in the foreground.

# Actual behavior

The external diff tool appears behind the Windows Terminal window.

# Additional Information

* I've tried this with multiple diff tools (both Winmerge and P4Merge), and get the same issue.
* I've tried this with other terminal apps (Cmder, normal Powershell window, and normal cmd window). This only happens when using the Windows Terminal.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that's already tracked in #2988. This one's a little hard to search for, but that thread does explain why this is:
 
> I (believe) that traditionally, `start` uses `GetConsoleWindow` to get the `HWND` of the console, to place explorer (or any application really) in the z-order above the conhost.exe window.
> 
> For something running in conpty however, the console doesn't actually have a window. The Terminal does, but the console doesn't. So there's no way for `start` to place something above the console window, since there _is no console window_.

I'll refer you to that thread for continued discussion.

/dup #2988
