### ISSUE TITLE
nextTab and prevTab keyboard shortcuts don't scroll tab bar to keep active tab in view

### ISSUE THREAD

**Issue by KevKeating** [microsoft/terminal#3638]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version : 0.6.2951.0
```

# Steps to reproduce

- Open Terminal and create enough new tabs that some tabs aren't visible without scrolling
- Hit the nextTab or PrevTab keyboard shortcuts repeatedly (Ctrl+Tab and Ctrl+Shift+tab by default)

# Expected behavior

As the active tab changes, the tab bar should automatically scroll to keep the active tab visible.

# Actual behavior

As the active tab changes, the tab bar doesn't scroll, which can make it difficult to tell which tab is currently active,

**Comment by zadjii-msft** [comment]
Upstream issue: microsoft/microsoft-ui-xaml#3945

**Comment by Don-Vito** [comment]
> 
> 
> Upstream issue: [microsoft/microsoft-ui-xaml#3945](https://github.com/microsoft/microsoft-ui-xaml/issues/3945)

@zadjii-msft - there is a workaround the upstream issue. I can try it.

**Comment by zadjii-msft** [comment]
@Don-Vito That would be great, thanks!
