### ISSUE TITLE
TSFInputControl determine proper Width for TextBlock 

### ISSUE THREAD

**Issue by philnach** [microsoft/terminal#3640]
from #1919 

Code TODO to determine proper dynamic width for the TextBlock in the TSFInputControl.  Ideally the Width should be set to the starting point of the cursor to the end of the border of the containers (Parent) control (i.e.: TerminalControl).  Today it's set to a fixed width of 200.  The size should take into account any scaling if applicable.

**Comment by leonMSFT** [comment]
Removing the `width(200)` setting in #4688 allows the TextBlock to dynamically grow as the text grows. It'll stop growing once it hits the terminal window limit though, so I'll consider this issue closed.
