### ISSUE TITLE
TSFInputControl focusRemovedHandler should do something according to documentation

### ISSUE THREAD

**Issue by philnach** [microsoft/terminal#3644]
from #1919 

Code TODO, [documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.core.coretexteditcontext.focusremoved) indicates that the focusRemovedHandler should do something, but it's unclear what.  This issue tracks determining proper thing to do.

**Comment by zadjii-msft** [comment]
Hey @lhecker does #4140 fix this issue too?

**Comment by DHowett-MSFT** [comment]
Based on the PR, it does add "the right thing" to focusRemovedHandler. Closing! Thanks
