### ISSUE TITLE
how can I switch my vim windows when the Ctrl+w+w only related to 'close window'

### ISSUE THREAD

**Issue by shulizi** [microsoft/terminal#3649]
How can I switch my vim windows when the Ctrl+w+w only related to 'close window', and why can not I input Chinese characters.

**Comment by j4james** [comment]
See issues #2973 and #2213. If those doesn't answer your questions, please fill out the full bug template when submitting the issue, and only list one concern at a time.

**Comment by shulizi** [comment]
> See issues #2973 and #2213. If those doesn't answer your questions, please fill out the full bug template when submitting the issue, and only list one concern at a time.

thanks for your  reply, I have just issued a stupid question.
