### ISSUE TITLE
"About Box" popover does not resize with the window

### ISSUE THREAD

**Issue by DHainzl** [microsoft/terminal#3653]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version (if applicable):  0.6.2951.0

Any other software? -
```

# Steps to reproduce

* Open up the "About" box
* Resize the window

# Expected behavior

The overlay resizes with the window size and the about box itself stays centered

# Actual behavior

The overlay and box stay at the position they were initially in which is ugly and, depending on the resize, allows selecting of the underlying text or cuts the contents of the box.

# Screenshot

![image](https://user-images.githubusercontent.com/5126798/69327096-3e921e80-0c4d-11ea-8f77-127e8f65dfea.png)

**Comment by skyline75489** [comment]
I think this is basically #2380

**Comment by DHainzl** [comment]
Ack, looks like a duplicate. Sorry, missed that one in my search.
