### ISSUE TITLE
About modal's context menu is not legible when using dark theme

### ISSUE THREAD

**Issue by ducaale** [microsoft/terminal#3654]
# Environment

```none
Windows build number: 10.0.18363.476
Windows Terminal version (if applicable): 0.6.2951.0
```

# Steps to reproduce

1. Make sure Windows Terminal is in dark theme and Windows 10 default app mode is light
2. Open `about` modal
3. Highlight some text and right click

# Expected behavior
Context menu should be legible with white text on dark background.

# Actual behavior

Context menu text is not legible.

![Screenshot (35)](https://user-images.githubusercontent.com/16341131/69338535-5375ae80-0c5b-11ea-9bf8-b59d693a5a6f.png)

**Comment by AritraNath** [comment]
Works fine in my case...
![2019-11-21 (1)](https://user-images.githubusercontent.com/38553944/69342963-a028ac00-0c92-11ea-988c-2a9be3676c74.png)

**Comment by zadjii-msft** [comment]
@ducaale Did you switch to dark mode while the app was already running? Or did you launch the app in dark mode?

**Comment by ducaale** [comment]
@zadjii-msft I launched the app in dark mode.

**Comment by ducaale** [comment]
@AaChristian it seems that the color of text depends on the theme of windows and not on the theme of the terminal. the context menu is legible when windows default app mode is dark

![Screenshot (42)](https://user-images.githubusercontent.com/16341131/69345979-f2090c00-0c69-11ea-99bf-ce1f011f271d.png)
