### ISSUE TITLE
Graphical Tools cmdlets in PowerShell 7 Preview 6 open windows behind the Terminal

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#3665]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable):
PowerShell: PowerShell 7 Preview 6

```

# Steps to reproduce

If you run PowerShell 7 Preview 6 in Windows Terminal, Out-GridView, Show-Command, and Get-Help -ShowWindow don't get a focus. They open windows behind the Terminal.
# Expected behavior
Windows opened by these PowerShell commands will get focus and be open over Windows Terminal. 

# Actual behavior

If you run PowerShell 7 Preview 6 in Windows Terminal, Out-GridView, Show-Command, and Get-Help -ShowWindow don't get a focus. They open windows behind the Terminal.

**Comment by SteveL-MSFT** [comment]
This isn't just these tools, but if you do `start $env:SystemDrive`, the explorer window starts behind

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/42356

**Comment by electronic-dk** [comment]
Sorry, but might it be related to https://github.com/microsoft/terminal/issues/2988 ?

**Comment by zadjii-msft** [comment]
Thanks for the triage @electronic-dk! This is, in fact, the same root cause as #2988. That thread has a lot more discussion in it so I'll redirect this thread there. Thanks!

/dup #2988
