### ISSUE TITLE
App terminates unexpectedly when moved from high-DPI-Screen to Lower-DPI-Screen

### ISSUE THREAD

**Issue by MartinStettner** [microsoft/terminal#3668]
# Environment

```none
Windows Build Number: 10.0.18362.0
WIndows Terminal version: 0.6.2951.0

3 Monitor Setup
- Main Screen High-DPI (Scaling 150%, 3840x2160)
- Left and right: Scaling 100%, 1920x1200
```

# Steps to reproduce

- Start Terminal
- Terminal window opens on Main Screen (High DPI, Scaling 150%)
- Move Window on secondary screen (Scaling 100%)

# Expected behavior

- (Window scales down correctly)
- Window should stay on second monitor

# Actual behavior

- (Window scales down correctly)
- Terminal window disappears after around 1 second without message
- (Process is terminated according to Task Manager/Process Explorer)

# Additional information

If I set both screens to the same scaling (either 100% or 150%) the error does not occur.

If I set the _secondary_ screen to 150% and the main screen to 100%, I can move the Window from the (low-scale) main screen to the (150% scaled) secondary screen without problem. When I move the window back to the 100%-Screen, it disappears again.

**Comment by j4james** [comment]
Sounds like #3303.

**Comment by DHowett-MSFT** [comment]
Absolutely is. /dup #3303. Also, /feedback.
