### ISSUE TITLE
Titlebar only updates when you switch tabs (not when terminal changes it)

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#3674]
It looks like the event that updates the _titlebar_ (TerminalPage calling TitleChangeHandlers) got disconnected. The tab works fine.

https://github.com/microsoft/terminal/commit/9ed3da8b3b3b91f17731fcb33343de3485aa473f#diff-ded63038d58dbb9f43cb344d7cc06c76L727-L737 removed the roundabout "page listens to control to make tab update itself" event handler, but in doing so broke this.

**Comment by zadjii-msft** [comment]
oh no
