### ISSUE TITLE
Remove gap between tab and window edge when maximized

### ISSUE THREAD

**Issue by chadbaldwin** [microsoft/terminal#3676]
# Description of the new feature/enhancement
Screenshot taken while terminal is maximized (sorry, mouse disappears when it reaches the screen edge, but you can see the yellow circle pop up when I click):
![terminal-issue](https://user-images.githubusercontent.com/16479446/69483710-9791bc00-0ddf-11ea-938a-f0d6e7b997c1.gif)

When using Windows Terminal in a maximized state, if you quickly move your mouse over to the tab you want to switch to, it is common to just move the mouse until the mouse stops when it reaches the edge of the screen above the tab. There is a small section between the the screen edge and the top of the tab, if your mouse lands in this area, the tab is not highlighted and you cannot click on it. You then have to move your mouse down just slightly in order to highlight and click. This is fine when the window is floating, but in maximized mode, it is frustrating.

What I want to happen is similar to how the Chrome browser works. If it is a floating window, it has that gap between tab and window edge. But if you maximize it, then the gap goes away. So when you move your mouse all the way to the edge of the screen, over the tab you want to use, it still highlights the tab and you can click. This makes for a much more fluid experience.

**Comment by j4james** [comment]
This is a duplicate of #2541.

**Comment by chadbaldwin** [comment]
@j4james crap how did I miss that. I even searched. Thanks for finding.
