### ISSUE TITLE
Color schemes with itermcolors extension are not applied properly

### ISSUE THREAD

**Issue by merajmasuk** [microsoft/terminal#3677]
# Environment

```none
Windows build number: Windows 10.0.18363.476
Windows Terminal version (if applicable): Windows Terminal Preview v0.6.2951.0

ColorTool v1.0.1904.29002
```

# Steps to reproduce

Applied [this theme](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Batman.itermcolors) via colortool. Perfectly works on the regular PowerShell and Command Prompt but not on the Terminal.

# Expected behavior

![image](https://user-images.githubusercontent.com/34513961/69484986-e123ea80-0e63-11ea-8047-8a5adf1769cc.png)

# Actual behavior

Side by side comparison for cmd (Command Prompt):

![image](https://user-images.githubusercontent.com/34513961/69485131-5e039400-0e65-11ea-8986-90dea6f221eb.png)

Side by side comparison for PowerShell:

![image](https://user-images.githubusercontent.com/34513961/69484998-17616a00-0e64-11ea-9bb3-57731019c18f.png)

# Workaround

Adding -x option in the command seems to fix the problem

PowerShell:

![image](https://user-images.githubusercontent.com/34513961/69485174-18939680-0e66-11ea-841f-e250d36606d3.png)

Command Prompt:

![image](https://user-images.githubusercontent.com/34513961/69485179-29440c80-0e66-11ea-9a3f-4816be6d4eb4.png)

**Comment by DHowett-MSFT** [comment]
I think you have to use `colortool -x` to switch into a mode that is compatible with WSL and Windows Terminal.

**Comment by merajmasuk** [comment]
Yeah, I stated that in the workaround section. Now I see it's the design.
