### ISSUE TITLE
Feature: Ability to lock the scroll bar

### ISSUE THREAD

**Issue by z0rgy** [microsoft/terminal#3679]
# Description of the new feature/enhancement
When I use make to build application via ssh, I get screen fulls of text going through. Sometimes in that text I get warnings which my eye catches.
It is very difficult to read the text as even if I attempt to scroll up the text keeps on moving forward due to make generating more output to stdout.
I tried to press on the scroll lock and expected that the scroll bar would be locked, however this did not happen.
Could there be a feature where I could lock the scroll bar ? (it doesn't have to be the scroll lock key)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This is probably a duplicate of #980. The issue title only mentions pausing the scrolling on click, but support for the `ScrollLock` key has been suggested a number of times in the comments.

**Comment by z0rgy** [comment]
Agreed this is a duplicate of #980 I will close the ticket.
