### ISSUE TITLE
Which tab is active -- not clear

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3682]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.5.2762.0


```

# Steps to reproduce

open multiple tabs in terminal. The switch tab between them

# Expected behavior

I can see which tab is active clearly.

# Actual behavior  -- Could we use a very different color to identify the active tab ?
Please see bellow picture. it's hard to figure out which tab is active when my monitor is not so good. I have to chick on each tab to find the active one.

![not clear](https://user-images.githubusercontent.com/36788337/69489026-c37b7300-0ead-11ea-99a7-eef2d59775f9.png)

**Comment by j4james** [comment]
This looks like a dup of #771. It should be improved in v0.6.2951.0.

See also #1337 and #2994.

**Comment by zadjii-msft** [comment]
Thanks for the report! @j4james is correct, this looks like #771, the fix for which should already be available.

I'd also throw out #3327 as another potentially related issue.

/dup #771
