### ISSUE TITLE
Cursor type changes when entering and exiting Neovim

### ISSUE THREAD

**Issue by brukbrhane** [microsoft/terminal#3684]
I have found that when entering nvim, the cursor type often changes to filledBox (away from the one I was using which is bar). And upon exiting nvim the cursor type still stays as filledBox. I tried this in the powershell window but it doesn't exhibit the same behavior. It returns to the deafult cursor shape when nvim is exited.

**Comment by j4james** [comment]
This sounds like it would be fixed by #1604.

**Comment by DHowett-MSFT** [comment]
Yeah, this is now a /dup of #1604. Thanks!
