### ISSUE TITLE
a white screen occurs when I drag the windows terminal

### ISSUE THREAD

**Issue by kqkdChen** [microsoft/terminal#3689]
**It is normal to open the terminal window first, but once I drag the window, it will turn white.My Windows version 1909**

**Comment by Sir-kaze** [comment]
I got the same problem. Then when I maximized window and turned it back, it seems OK. Next I try to drag, but it turns to white screen again. To fix it, I've tried many ways. Finally, I try to resize the windows, then I find it won't white again however I drag it. I guess the problem may related to window size.

**Comment by DHowett-MSFT** [comment]
This looks like a /dupe of #3446
