### ISSUE TITLE
About Windows Terminal

### ISSUE THREAD

**Issue by sapomuyverde** [microsoft/terminal#3691]
Hi,
I can't drag a file and run, for example, drag a bat file from the file explorer
I can't copy any text, for example a command line from the browser or some other text from a text file, etc.
It is possible to set your own image (photo) as a background?

I appreciate your time.

Regards,
Javier

**Comment by zadjii-msft** [comment]
@sapomuyverde Thanks for the questions! In general, we prefer if you create a separate issue for each problem or feature request you might have - it makes it easier to search for existing issues, and easier on us from tracking issues.
> I can't drag a file and run, for example, drag a bat file from the file explorer
This is actually already being tracked in #904 "Drag and drop from File Explorer should put full path at cursor location in Windows Terminal"
> I can't copy any text, for example a command line from the browser or some other text from a text file, etc.
Perhaps try using <kbd>Ctrl+shift+c</kbd> to copy? That's the keystroke that is bound to `copy` by default. You can also add custom keybindings, see [this guide](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#adding-copy-and-paste-keybindings).
> It is possible to set your own image (photo) as a background?
It sure is! Please refer to [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#add-a-custom-background-to-the-wsl-debian-terminal-profile).

**Comment by sapomuyverde** [comment]
Hi @zadjii-msft Thank you for your help, helped me set the keys to copy and paste and to put background image.
