### ISSUE TITLE
Terminal quits immediately if %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ is not on PATH

### ISSUE THREAD

**Issue by rossng** [microsoft/terminal#3697]
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

1. Remove `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` from your system `PATH` variable
2. Start Windows Terminal

# Expected behavior

Windows Terminal warns you that PowerShell cannot be found, or perhaps launches a fallback `cmd` session instead. I encountered this issue because some unruly installer erased my `PATH` 😒 

# Actual behavior

The Windows Terminal UI flashes briefly and immediately quits.

**Comment by DHowett-MSFT** [comment]
Hey, you're in luck! We just fixed this, but unfortunately it's not going out on the current release train. /dup #2563
