### ISSUE TITLE
Windows terminal has been terminated when dragging terminal to another display that has different resolution

### ISSUE THREAD

**Issue by KimKiHyuk** [microsoft/terminal#3699]
# Environment

```
Windows build number: 10.0.19025.1051
Windows Terminal version (if applicable): 0.6.2951.0

- display1 : 3840 x 2160
- display2: 1920 x 1080
```

# Steps to reproduce

1. launch windows terminal as user mode **(bug doesn't occur when running windows terminal as admin)**
2. move it to another display 

# Expected behavior

1. terminal has to be move to a specific display

# Actual behavior

1. 'running' icon which looks like blue circle appears
2. terminal is shut down without any message

**Comment by cellerich** [comment]
Same behavior with me. Even when executed as "Admin".
If the Terminal Window is "PowerShell" then I can move to the other display.
If it is "Ubuntu - WSL" then it will crash

**Comment by j4james** [comment]
This is probably #3303. Although the fact that is doesn't crash when you're admin is interesting - I've never seen any mention that before.

**Comment by KimKiHyuk** [comment]
@j4james i think it is related to powershell and cmd. i've just tried open terminal as user mode and close power shell(power shell is default shell for me) and open wsl shell. now i can move terminal to another display.  if i have opened power shell or cmd shell and try to move windows terminal to another display, windows terminal die

**Comment by j4james** [comment]
If you look at https://github.com/microsoft/terminal/issues/3303#issuecomment-545908870, you'll see that other people have reported similar results with powershell. I'm pretty sure this is the same bug.

**Comment by zadjii-msft** [comment]
Yea, this is #3303/#2277. I'd bet that the fact it repros in Admin mode is because for some reason, that bug is more or less likely to repro _based on the length of the tab title_. Really unsure _why_ that is, but in that thread, you'll see that `aaaaaaaaaaaaa` will repro it consistently, but not longer/shorter titles. It's been my personal hell these last couple weeks 😝 

/dup #3303
