### ISSUE TITLE
Reading cursor position from exe started from WSL

### ISSUE THREAD

**Issue by parkovski** [microsoft/terminal#37]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.19]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
I'm working on [enabling PSReadLine to work when input is redirected](https://github.com/lzybkr/PSReadLine/pull/564). I have all the console I/O working in a plain Windows console using just ANSI escape sequences. My motivation though is to be able to run the Windows version of PowerShell under tmux, but I'm getting strange inconsistent results from the cursor position query when I start it from WSL - whether in the actual shell, tmux, or just `ubuntu run pwsh.exe`. Basically, the cursor position response is getting _mostly_ auto-echoed to the console, and I'm not able to read and parse it. Since PowerShell and PSReadLine are big complicated projects, I wrote a simple line editor using just Windows APIs, but it does the same thing.

Screenshot with order of events:
![lineedit](https://user-images.githubusercontent.com/1094150/32517768-a5af92ec-c3c4-11e7-83f3-a2028ba94cbe.png)
1. Compile the program
2. Start it from Windows - this worked fine (see the lines `test` and `wow it works! how cool!`)
3. Start it from WSL - after the first line the cursor jumped to the top of the screen and when I hold down enter, it may read none, some, or all of the cursor position response. Usually some unpredictable portion of it.

Here is the program I'm running: https://gist.github.com/parkovski/c0af657c8371760e89c6a82febbd4f84

* What's wrong / what should be happening instead:
It should act like it does when started from Windows - a cursor position response should send the whole thing to stdin; it shouldn't echo parts of it to the screen. Am I missing something? It seems like cmd and PowerShell without PSReadLine handle this scenario, albeit with very basic capabilities, so I'm inclined to think this is not necessarily a console bug, but some mode or setting that I'm missing.

**Comment by parkovski** [comment]
I got the line editor working by using an asynchronous/overlapped `WriteFile` and reading larger blocks of bytes, which suggests to me that the pipe is not buffered and if no one is reading at the moment that multiple bytes of input come in at once, it will clear itself by echoing everything to stdout. If this is the intended behavior or a Linux thing I was unaware of, feel free to close this issue.

**Comment by DHowett-MSFT** [comment]
November 8, 2017. Hm. That predates WSL switching to ConPTY. This should be significantly more reliable, and if it's not it's almost certainly WSL's issue. Closing? Thanks!

**Comment by parkovski** [comment]
This is indeed not an issue anymore, thanks!
