### ISSUE TITLE
Clicking on Tab with cd command in the cmd should end with a slash 

### ISSUE THREAD

**Issue by venuBondugula** [microsoft/terminal#3700]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I'm going to presume you meant "_pressing_ <kbd>tab</kbd> with a cd command...".

@venuBondugula Are you using `cmd.exe` or `powershell.exe`/`pwsh.exe`?

**Comment by venuBondugula** [comment]
> I'm going to presume you meant "_pressing_ tab with a cd command...".
> 
> @venuBondugula Are you using `cmd.exe` or `powershell.exe`/`pwsh.exe`?

Yes pressing tab in cmd.exe

**Comment by DHowett-MSFT** [comment]
Sorry -- we're not going to change CMD. You need to "confirm" the tab completion anyway, so you could just do it by pressing `\` instead of .. whatever other thing you were doing that `\` automatically appearing would have made easier.
