### ISSUE TITLE
When entering a Chinese punctuation, it acts like keeping hitting the key

### ISSUE THREAD

**Issue by wrvsrx** [microsoft/terminal#3706]
# Environment

```none
Windows build number: 10.0.19030.1
Windows Terminal version: 0.7.3291.0
```

# Steps to reproduce

Hit the key "，" (or other punctuation) in windows terminal with Chinese input method 

# Expected behavior

Output a "，" (I delete the extra "，" in the following picture manually)

![image](https://user-images.githubusercontent.com/42770726/69660038-6f91a980-10ba-11ea-83df-0c8a7181f12d.png)

# Actual behavior

keeps outputting "，" just like I keep hitting the "，"

![image](https://user-images.githubusercontent.com/42770726/69659737-cd71c180-10b9-11ea-9430-0617081f5b9f.png)

# Some other information

1. I have reproduced it in Windows Terminal using wsl, cmd and powershell7-preview on my two PCs.
2. Another phenomenon is that Windows Terminal add space behind Chinese character automatically after my inputting one character.

**Comment by etern** [comment]
For me, I have to type twice to input one Chinese puncutation, like period(。), I'm also using terminal version 0.7.3291.0

It reminds me this issue #2191 , one Chinese character rendered as two small charactors. 
It seems wide character is not handled properly.

**Comment by ice1000** [comment]
I am in the same situation as @etern 's instead of OP's

**Comment by Lemmingh** [comment]
I have the same problem as @etern which has been discussed in #3745

Though looking opposite, I wonder whether these issues are related in some aspect.

**Comment by luxrck** [comment]
I have encountered the same bug @wrvsrx 

![image](https://user-images.githubusercontent.com/4439100/70957691-e3b7df80-20b1-11ea-8708-176788404255.png)

wt version: 0.7.3382.0

**Comment by wrvsrx** [comment]
Recently, I test it on another PC whose windows build number is 10.0.18363.535, and it behave like what #3745 describes. Comparing this to windows terminal's behavior mentioned above on my PC  with windows build number 10.0.19030.1, I think it might be related to the windows version.

**Comment by luxrck** [comment]
@wrvsrx And my windows version is: 10.0.19037.1
Seems that it did relate to the win10 version......
