### ISSUE TITLE
Full Screen issues with Panes Open?

### ISSUE THREAD

**Issue by OmriSama** [microsoft/terminal#3707]
# Environment

**Windows build number**: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

**Windows Terminal version (if applicable)**: 0.7.3291.0

**Any other software?**: Connected via OpenSSH to an Ubuntu VM running locally. Using ZSH.

# Bug

When going into the new full-screen mode, you can't see other panes. So my terminal will look like this:

![image](https://user-images.githubusercontent.com/10534779/69660591-82ae6600-1035-11ea-8b05-a43910b01797.png)

But then in full-screen mode like this:

![image](https://user-images.githubusercontent.com/10534779/69660431-29463700-1035-11ea-9980-fa80b34c067f.png)

And the other panes are still there, and I can move focus to them, but not actually see them.

---
_edit: moved this second bit to #3709_

I apologize ahead of time if this is already documented, or is not a completed feature/duplicate issue.

**Comment by mdtauk** [comment]
Does a Full Screen window behave differently to a normal window?  In terms of reporting it's size?

**Comment by zadjii-msft** [comment]
@OmriSama Well that's certainly odd. For the sake of keeping discussion simple, I'm going to focus on just that first issue in this thread, and track the "fullscreen from maximized doesn't work" in #3709.

I'm unfortunately not seeing that behavior myself, so we'll need to find what causes that to repro... If you navigate to the other pane when it's in the broken state, does typing text appear where the pane should be?

Does it only occur with that Profile?

**Comment by OmriSama** [comment]
Just checked again and this specific issue seems to have been fixed with the latest release. Cheers!
