### ISSUE TITLE
Entering Fullscreen from Maximized doesn't work right

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3709]
###### Moved from  #3707

# Environment

**Windows build number**: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

**Windows Terminal version (if applicable)**: 0.7.3291.0

*Another behavior* is that when going into Full-Screen mode from a maximized window, you still see the taskbar and the padding around the shell looks all messed up:

![image](https://user-images.githubusercontent.com/10534779/69660521-60b4e380-1035-11ea-824b-8bf2339c4567.png)

fullscreens to:

![image](https://user-images.githubusercontent.com/10534779/69660545-6ad6e200-1035-11ea-8590-69d579ec3c1f.png)

**Comment by OmriSama** [comment]
Thanks @zadjii-msft !

**Comment by OmriSama** [comment]
I should also mention that I use three monitors at work, and my 4k monitor (my third, as opposed to the other two being 1080p) displays a different behavior when fullscreening:

Not maximized -> fullscreen:
![image](https://user-images.githubusercontent.com/10534779/69661977-4b8d8400-1038-11ea-817c-f02103a0561c.png)

Maximized -> fullscreen:
![image](https://user-images.githubusercontent.com/10534779/69662014-6102ae00-1038-11ea-8dc6-9b98293ab8ec.png)

**Comment by shanselman** [comment]
Yep, I hit this within minutes. :(

**Comment by nicolaskeller** [comment]
Fullscreen looks good if padding is set to 8,8,8,8. 
If padding is set to 0,0,0,0 the content gets cut.

**Comment by OmriSama** [comment]
> 
> 
> Yep, I hit this within minutes. :(

Did THE Scott Hanselman just comment on my GitHub issue??? 😱😱😱😱😱😱😱

**Comment by nathpete-msft** [comment]
Interestingly, this issue (including the 4k monitor issue mentioned by @OmriSama) _only_ repros for me if I have `showTabsInTitlebar` enabled. With that setting off switching to fullscreen works as expected regardless of the starting window state or the monitor it's on.
