### ISSUE TITLE
fullscreen not working on all displays

### ISSUE THREAD

**Issue by kort3x** [microsoft/terminal#3710]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce
Entering fullscreen only works on two of my three monitors.
On the third one terminal just maximizes and shows nothing but black/gray and a bright white titlebar.

![image](https://user-images.githubusercontent.com/13918530/69661858-73eea000-1083-11ea-83f2-b90d8a3783a4.png)

**Comment by encladeus** [comment]
My machine has two identical monitors, but _fullscreen_ only works on the primary monitor. Fullscreen on monitor 2 fails per the screenshot above.

**Comment by kort3x** [comment]
I have three identical monitors.
Two of them connect with DisplayPort and one D-Sub.
The secondary DP craps out when entering full screen.

Reminds me of an issue over at PowerToys:
https://github.com/microsoft/PowerToys/issues/611

**Comment by DHowett-MSFT** [comment]
Are those displays connected to different display adapters, or to the same one? What's your graphics hardware situation?

**Comment by kort3x** [comment]
### GPU:
Videoprocessor  : GeForce GTX 1050 Ti
Videomodedescription : 1920 x 1200 x 4294967296 colors
DriverDate  : 05.09.2019 02:00:00
DriverVersion : 26.21.14.3630

### Monitors:
GetSystemMetrics = 3
GetMonitorInfo OK
EnumDisplayDevices OK:
	DeviceID = \\?\DISPLAY#GSM59B4#5&e062d6f&0&UID4353#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
	DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0010
	DeviceName = \\.\DISPLAY1\Monitor0
	DeviceString = Generic PnP Monitor
GetMonitorInfo OK
EnumDisplayDevices OK:
	DeviceID = \\?\DISPLAY#GSM59B4#5&e062d6f&0&UID4356#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
	DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0012
	DeviceName = \\.\DISPLAY2\Monitor0
	DeviceString = Generic PnP Monitor
GetMonitorInfo OK
EnumDisplayDevices OK:
	DeviceID = \\?\DISPLAY#GSM59B4#5&e062d6f&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
	DeviceKey = \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0011
	DeviceName = \\.\DISPLAY3\Monitor0
	DeviceString = Generic PnP Monitor
EnumDisplayMonitors OK

WMI report:
Active: 1
WeekOfManufacture: 9
InstanceName: DISPLAY\GSM59B4\5&e062d6f&0&UID4353_0
YearOfManufacture: 2016
ManufacturerName: 71 83 77 0 0 0 0 0 0 0 0 0 0 0 0 0 
ProductCodeID: 53 57 66 52 0 0 0 0 0 0 0 0 0 0 0 0 
SerialNumberID: 54 48 57 78 84 83 85 52 88 56 54 50 0 0 0 0 
UserFriendlyName: 50 52 69 66 50 51 0 0 0 0 0 0 0 

Active: 1
WeekOfManufacture: 9
InstanceName: DISPLAY\GSM59B4\5&e062d6f&0&UID4356_0
YearOfManufacture: 2016
ManufacturerName: 71 83 77 0 0 0 0 0 0 0 0 0 0 0 0 0 
ProductCodeID: 53 57 66 52 0 0 0 0 0 0 0 0 0 0 0 0 
SerialNumberID: 54 48 57 78 84 90 78 55 51 54 48 53 0 0 0 0 
UserFriendlyName: 50 52 69 66 50 51 0 0 0 0 0 0 0 

Active: 1
WeekOfManufacture: 9
InstanceName: DISPLAY\GSM59B4\5&e062d6f&0&UID4355_0
YearOfManufacture: 2016
ManufacturerName: 71 83 77 0 0 0 0 0 0 0 0 0 0 0 0 0 
ProductCodeID: 53 57 66 52 0 0 0 0 0 0 0 0 0 0 0 0 
SerialNumberID: 54 48 57 78 84 74 74 52 88 56 50 56 0 0 0 0 
UserFriendlyName: 50 52 69 66 50 51 0 0 0 0 0 0 0

**Comment by kort3x** [comment]
Oh, it's no D-Sub but DVI

**Comment by encladeus** [comment]
Both of my monitors are connected to separate DPs. Both monitors using NVIDIA GeForce GTX 1060 6GB GPU. Both monitors using native resolution (1920 x 1080).

**Comment by BundyB** [comment]
I'm seeing this on one of my monitors, plus different behaviour on a second.

The two 2560x1440 panels (one of which is primary) fullscreen fine.
The 2560x1600 panel to the right of primary displays like the screenshot above.
The 1920x1080 panel fullscreens perfectly to the top half of the display, with the bottom half matching the screenshot.

All panels are DP off the same AMD FirePro W5100.

**Comment by Aarklendoia** [comment]
Same problem for me. I have an nVidia NV300 (one connector for two DVI monitor). The display shows a strip on the left but the rest is entirely grey (dark theme).
 
![image](https://user-images.githubusercontent.com/1765298/69724685-af897880-111c-11ea-9cde-b588b8976017.png)

**Comment by LuanVSO** [comment]
similar to https://github.com/microsoft/terminal/issues/3710#issuecomment-559074329
but with more cols.

hardware: laptop

second screen conected via hdmi to intel graphic adapter.
main screen resolution(left):1366X768
secondary screen resolution(right):1920X1080

![image](https://user-images.githubusercontent.com/43626415/69742345-64229a80-111b-11ea-8303-dc56a5459ff6.png)

**Comment by moswald** [comment]
I have three identical monitors, and full screen behaves differently on each. On my center (primary) monitor it works fine. On my right monitor, the terminals are only sized about 20px wide (see Aarklendoia's screenshot above), but the app does take up the whole monitor. On my left monitor, the app takes up the whole monitor, but now the terminals are sized larger than the app. I'm using panes, and what happens is my right-most pane is pushed offscreen, while my center and left panes are visible and look somewhat normal.

**Comment by SkyTrix** [comment]
I have a laptop with one external monitor connected through DVI. When my laptop screen is set as the main display in display settings, full screen works on both screens. However, when I set the external monitor as the main display, fullscreen only works on the external monitor and on my laptop it shows similar results as image from OP. None of the displays are scaled (100%). I hope this helps.

**Comment by LoZeno** [comment]
My setup:

Laptop with 4k display with 150% scaling on an Nvidia GeForce GTX 950M GPU;
Two external monitors: 1080p display with 100% scaling connected through an HP 3005pr USB 3.0 dock.

On the main (integrated) monitor, fullscreen works perfectly; on the two external monitors, fullscreen looks like this:

![Annotation 2019-11-28 092009](https://user-images.githubusercontent.com/3267561/69796264-97b9ff00-11c5-11ea-9f0f-566ea10ce0cd.png)

**Comment by hoshinomahiro** [comment]
Environment:
Windows Insider Preview 19025
Windows Terminal 0.7.3291.0

I have two same screens, and `Alt+Enter` works well in each screen if I don't move terminal from 
 the first screen to the second. Once I move it, I will get the this bug!

**Comment by DHowett-MSFT** [comment]
Assigning myself as followup to test whether the in-PR fix helps this.

**Comment by Elevate08** [comment]
I'm having this happen on my Laptop, 2 displays connected via Docking Station over USB-C work fine. The 3rd via HDMI from Laptop results in the full screen bug reported here.

**Comment by ajaykumarkannan** [comment]
I'm seeing the same issue. I have two identify monitors but the second one (the one where the failure occurs) is in rotated by 90 degrees.

**Comment by encladeus** [comment]
FWIW, this started working for me after upgrade to WT 0.8 on both machines where I previously experienced the issue.

**Comment by kort3x** [comment]
works for me now.

Thanks!
