### ISSUE TITLE
Window get white border when you snapped to left/right half of screen

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#3711]
Terminal Version: 0.7.3291.0
Windows Theme: Light with accented title bar
Configuration: `"requestedTheme": "dark"`

![image](https://user-images.githubusercontent.com/240091/69662330-0584f000-1039-11ea-8496-fd843fdbbc34.png)

**Comment by zadjii-msft** [comment]
I think this is just kinda how Windows applications work
![image](https://user-images.githubusercontent.com/18356694/69663111-34a45d00-104b-11ea-89f3-04ca54909286.png)
![image](https://user-images.githubusercontent.com/18356694/69663151-4a198700-104b-11ea-9d47-db3596334bfa.png)

**Comment by be5invis** [comment]
@zadjii-msft The color is correct when you focused. When not focused **and** snapped, it is white.

**Comment by DHowett-MSFT** [comment]
This is another instance of /dup #3425 (which I'll rename)

**Comment by be5invis** [comment]
This still repros in v0.10. I do not think it is a dupe of #3425.
This is what you get after you press WIN-RIGHT then WIN-UP
![image](https://user-images.githubusercontent.com/240091/76938680-4f2d6b00-68b4-11ea-9808-07c4e8d9c190.png)

**Comment by be5invis** [comment]
It happens when your system app color is light, but forced Terminal to become dark.
Turning the system app color in Settings to "dark" may fix this.

**Comment by DHowett-MSFT** [comment]
Yes- If you want dark window borders, use dark theme. This is true across Windows.

**Comment by be5invis** [comment]
@DHowett-MSFT This _should_ be considered as a bug. White border only occurs when the window is snapped. On every other cases it worked well.

**Comment by be5invis** [comment]
cf. #4980

**Comment by DHowett-MSFT** [comment]
I'm not seeing this when snapped if system==dark and terminal==dark. This is expected.
