### ISSUE TITLE
Contextual menu in About dialog under dark UI is unreadable

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#3712]
Windows build: 18362.476 x64
Windows theme: Light with accented title bars
Configuration: "requestedTheme": "dark"

![image](https://user-images.githubusercontent.com/240091/69662555-70cec200-1039-11ea-9038-15b75c3e8e55.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked in /dup #3654
