### ISSUE TITLE
Full screen not quite working in 0.7.3291.0

### ISSUE THREAD

**Issue by gnllucena** [microsoft/terminal#3714]
# Environment

```none
Windows build number: Microsoft Windows [versão 10.0.19030.1]
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?

Powershell 7.0.0-preview 4
```

# Steps to reproduce

Just use the new shortcuts Alt + Enter or F11

# Expected behavior

To full screen everything

# Actual behavior
The screen it`s not fully covered by Terminal and it appears to be cut the top of Terminal

![image](https://user-images.githubusercontent.com/2061623/69666450-08003d80-106b-11ea-9bb6-da3f25ee1715.png)

Is this by design?

**Comment by zadjii-msft** [comment]
@gnllucena by any chance, did you have the terminal maximized before you hit the fullscreen keybinding?

Out of curiosity, what graphics card do you have?

**Comment by gnllucena** [comment]
Yes, I did have. 

Just noticed it doesn`t happen when Terminal is not maximized. Is this a known bug? :P

by the way, my graphics card is Intel(R) UHD Graphics 620, I`m working in a thinkpad.

**Comment by zadjii-msft** [comment]
Yea, this is /dup #3709
