### ISSUE TITLE
[FR] New 'selectAll' shortcut action with default mapping ctrl+shift+a

### ISSUE THREAD

**Issue by iamGavinJ** [microsoft/terminal#3723]
# Description of the new feature/enhancement
Create a new shortcut action to select all text in the buffer

# Proposed technical implementation details (optional)
ctrl+shift+a should select all text

**Comment by j4james** [comment]
This is probably covered by #1469, which was also suggesting the need for a _Select All_ key binding.

**Comment by DHowett-MSFT** [comment]
Yep, this is a /dupe of #1469.

**Comment by iamGavinJ** [comment]
@j4james, @DHowett thanks for finding the dupe.  I did do a brief search as I really didn't believe I would be the first to raise this but none of my search terms were turning anything up.
