### ISSUE TITLE
[FR] New 'emptyScrollbackBuffer' shortcut action with default corresponding mapping

### ISSUE THREAD

**Issue by iamGavinJ** [microsoft/terminal#3724]
# Description of the new feature/enhancement
There should be a method of emptying the scroll-back buffer.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This sounds like #1882.

**Comment by DHowett-MSFT** [comment]
It is indeed! /dup #1882. Thanks.

**Comment by iamGavinJ** [comment]
@j4james, @DHowett thanks for finding the dupe.  I did do a brief search as I really didn't believe I would be the first to raise this but none of my search terms were turning anything up.
