### ISSUE TITLE
Settings is being invoked when expanding abbreviation in Emmet

### ISSUE THREAD

**Issue by thisguychris** [microsoft/terminal#3728]
I'm using https://github.com/mattn/emmet-vim plugin for vim to expand css like selectors to actual html. To invoke Expand Abbreviation, it uses <kbd>Ctrl</kbd><kbd>y</kbd><kbd>,</kbd>, unfortunately, this is picked up by Terminal and open the settings instead.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19030.1]   
Windows Terminal version (if applicable): 0.7.3291.0


Any other software?
```

# Steps to reproduce

Open or create a New File:
```
vim index.html
```

Type ("_" is the cursor position):

```
html:5_
```

Then type `<c-y>,` (<kbd>Ctrl</kbd><kbd>y</kbd><kbd>,</kbd>), and you should see:

# Expected behavior

```html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	_
</body>
</html>
```

# Actual behavior

It opens the settings profiles.json

Note: I have tried remapping the settings to use <kbd>Ctrl</kbd><kbd>;</kbd> instead but it still open if I try to "expand abbreviation" <kbd>Ctrl</kbd><kbd>y</kbd><kbd>,</kbd>

So I guess this is another form of bug, where you can't remap the settings to a different key?

**Comment by DHowett-MSFT** [comment]
Couple unusual things:
1. I'm only seeing this behavior if I accidentally hit `<C-y><C-,>`. When I press `<C-y>,` I get a `^Y` and a `,`, as expected.
2. You have to explicitly _unbind_ <kbd>Ctrl+,</kbd> in your key bindings to suppress it. Add a binding for `ctrl+,` with `"command": null`.

**Comment by owennewo** [comment]
It's undocumented (and therefore subject to change) but I reckon if you add this to your settings (profile.json) it'll work:
`
"keybindings": [
    { "command": "openSettings", "keys": ["ctrl+shift+%"] }
  ]
`

I got the keybinding name from here:

https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp#L66

**Comment by zadjii-msft** [comment]
@owennewo I'm pretty sure the `openSettings` key is pretty well documented:

https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#L129

https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json#L44

**Comment by thisguychris** [comment]
@DHowett 

Thank you very much for your reply to answer your questions:

1. You're right, If I press <C-y><C-,> it does open the settings, for some reason that's how I've been using it. Having the modifier (Ctrl) hold while pressing the other key combination, in this case `,`.

If I press `<C-y>` <release Ctrl> then `,` it works as expected.

2. adding command: null does unbind the command. Though I wish it unbinds itself if you assign the settings a different shortcut.

I apologize for the delayed answer and if this is a false alarm. ✌🏻

**Comment by DHowett-MSFT** [comment]
Thanks for following up!

> wish it unbinds itself

Ah, I see. Sorry, I had a long writeup on why terminal input was annoying, but then I went back and read your request. Terminal’s bindings operate backwards from the way they seem in the settings: they really take a key _first_ and a command second. We absolutely want people to be able to set multiple bindings for the same command—like “copy” being on C-S-c or Return or Ctrl-Ins simultaneously, for example.

Terminal largely tries to stay away from key combinations that a text-mode application could want to detect.
Now, `<C-,>` is an interesting case. There actually isn’t a valid encoding that an application can detect. It reads the same way as `,`!
