### ISSUE TITLE
Alt arrow keys do nothing; key unbinding broken?

### ISSUE THREAD

**Issue by paulwhiting** [microsoft/terminal#3729]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version:  0.7.3291.0

Any other software?
- Ubuntu 16.04.3 LTS
- byobu version 5.106
- tmux 2.1
```
# Note

This issue is a follow-on to #3101.  In that issue superfluous keys were being generated.  Now it appears no keys are being generated.  Alt arrows are dead to me.

# Steps to reproduce

- Start Byobu:  byobu
- Create a new Byobu tab:  F2
- Press alt left or alt right to switch between the tabs

# Expected behavior

Byobu switches between the two tabs.

# Actual behavior

Nothing happens.

**Comment by paulwhiting** [comment]
This behavior is possibly due to #3585.  Is there a way to disable default key bindings?

**Comment by sivaramn** [comment]
> 
> 
> This behavior is due to #3585. Proper expected behavior is restored with the following:
> 
> ```
>     "keybindings": [
> 	{ "command": "unbound", "keys": [ "alt+shift+-" ] },
>         { "command": "unbound", "keys": [ "alt+shift+plus" ] },
>         { "command": "unbound", "keys": [ "alt+down" ] },
>         { "command": "unbound", "keys": [ "alt+left" ] },
>         { "command": "unbound", "keys": [ "alt+right" ] },
>         { "command": "unbound", "keys": [ "alt+up" ] },
>         { "command": "unbound", "keys": [ "alt+shift+down" ] },
>         { "command": "unbound", "keys": [ "alt+shift+left" ] },
>         { "command": "unbound", "keys": [ "alt+shift+right" ] },
>         { "command": "unbound", "keys": [ "alt+shift+up" ] }
>     ]
> ```

I also have the same issue.  Do we have to unbind the keys for tmux to work?  And what about mouse-focus?  Prior to this release, in `tmux` clicking with mouse on any pane would focus the cursor in that pane.  Now apparently that's gone.  How does one restore mouse clicky behaviour ?

**Comment by zadjii-msft** [comment]
I'm confident that clicking in a pane in `tmux` never worked in the Windows Terminal, since we don't yet support mouse mode (#376, #545)...

**Comment by sivaramn** [comment]
> 
> 
> I'm confident that clicking in a pane in `tmux` never worked in the Windows Terminal, since we don't yet support mouse mode (#376, #545)...

thanks for that.  I could be mistaken, as I use  versions of tmux in wsl & cygwin using `mintty`.

And the key unbounding didn't work.  I'm still not able to use the alt keys to switch panes

**Comment by zadjii-msft** [comment]
@sivaramn what exactly do you have in your `profiles.json`, and what's in your `tmux.conf`?

**Comment by sivaramn** [comment]
````
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n S-Left  previous-window
bind -n S-Right next-window
````
that's in `.tmux.conf`

in `profiles.json`
````
 // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": [{ "unbound": "nextTab", "keys": ["ctrl+tab"] },
		    {"command": "paste","keys": ["shift+insert"]},
		    //{ "keys": ["shift+insert"], "command": "paste" },
                    { "keys": ["ctrl+shift+v"], "command": "paste" },
		    { "command": "unbound", "keys": [ "alt+shift+-" ] },
       		    { "command": "unbound", "keys": [ "alt+shift+plus" ] },
       		    { "command": "unbound", "keys": [ "alt+down" ] },
       		    { "command": "unbound", "keys": [ "alt+left" ] },
                    { "command": "unbound", "keys": [ "alt+right" ] },
                    { "command": "unbound", "keys": [ "alt+up" ] },
                    { "command": "unbound", "keys": [ "alt+shift+down" ] },
                    { "command": "unbound", "keys": [ "alt+shift+left" ] },
                    { "command": "unbound", "keys": [ "alt+shift+right" ] },
                    { "command": "unbound", "keys": [ "alt+shift+up" ] }
			
                   ]
}
````

**Comment by samba2** [comment]
> ```
>...
>        		    { "command": "unbound", "keys": [ "alt+down" ] },
>        		    { "command": "unbound", "keys": [ "alt+left" ] },
>                     { "command": "unbound", "keys": [ "alt+right" ] },
>                     { "command": "unbound", "keys": [ "alt+up" ] },
>                     { "command": "unbound", "keys": [ "alt+shift+down" ] },
>                     { "command": "unbound", "keys": [ "alt+shift+left" ] },
>                     { "command": "unbound", "keys": [ "alt+shift+right" ] },
>                     { "command": "unbound", "keys": [ "alt+shift+up" ] }
>                    ]
> }
> ```

Just want do confirm that **unbinding** the alt key bindings **worked for me**. tmux resizing is now working as expected.

**Comment by fabricio7p** [comment]
Thank you so much for this!
This is an issue with Tmux alt key commands too.

**Comment by finlaybob** [comment]
Thanks for the example keybindings. Adding the unbound entries helped with behaviour in [micro](https://github.com/zyedidia/micro), which uses "alt+direction" by default for moving word at a time.

**Comment by paulwhiting** [comment]
Reopening issue because my alt-arrow buttons stopped working after upgrading Terminal to 0.10.761.0.

Windows build number: 10.0.18363.720
Windows Terminal version:  0.10.761.0

Any other software?
- Ubuntu 16.04.6 LTS
- byobu version 5.106
- tmux 2.1

**Comment by DHowett-MSFT** [comment]
Yep, fair enough. Bet we broke this with VT input tunneling.

**Comment by DHowett-MSFT** [comment]
Actually, no, I think we broke _unbinding_. /cc @zadjii-msft.

**Comment by yveslange** [comment]
Same issue :)
ALT-LEFT, RIGHT, TOP, DOWN does not react. Really feel that the "unbounds" are not working anymore.

**Comment by zadjii-msft** [comment]
looking now

**Comment by onefuncman** [comment]
Why is this the default behavior?  Seems like a bad UX -- what's the tradeoff?

**Comment by zadjii-msft** [comment]
You know, you've just inspired an idea - if the user has _no_ panes, then the Terminal could probably pass the Alt+Arrow through, similar to the way that Ctrl+C for copy sends a ^C when there's no text selected.
