### ISSUE TITLE
White border arround window when window focused

### ISSUE THREAD

**Issue by wenkeming** [microsoft/terminal#3731]
System: Windows 10 18363.476
Terminal: 0.7.3291.0
The system and terminal is in dark mode. When I focusd the terminal window, there is 1px white border arround the window. But it's OK in version 0.6.x.
![1](https://user-images.githubusercontent.com/8252267/69699561-304b7300-1123-11ea-97f1-370ffb1385d7.gif)

**Comment by DHowett-MSFT** [comment]
Please search before filing a new issue. Thanks for the report!

**Comment by carlinmack** [comment]
#3425
