### ISSUE TITLE
Tab reordering drag and drop approach is confusing

### ISSUE THREAD

**Issue by andriysavin** [microsoft/terminal#3734]
I find it confusing from the point of user experience that tab reordering is visually implemented as regular drag and drop. It makes me feel that in addition to reordering I can: 

a) detach a tab into its own window, like I'm used to do with web browser tabs;
b) drag a tab from one terminal window to other and thus move the tab between windows (again, like in web browsers);
c) and some users may even expect that they can drop a tab into some other app (e.g. embed it into a word document).

My opinion on this is unless implementing features mentioned above is on the roadmap, tab reordering should not allow dragging a tab outside of the tab panel. Instead, the tab being moved should slide within the tab row. A good example is how the tabs are visually sliding during reordering in MS Edge (Chromium version). 

And even if tab detaching is planned, it can be done exactly the same as in Edge (Chromium), i.e. the tab header is not floating with the mouse, but is detached with tab content after significant mouse movement.

**Comment by zadjii-msft** [comment]
Thanks for the feedback! I definitely agree with the points you're making. Fortunately, tab tear-out _is_ on the roadmap, but likely not until after 1.0. Before that, we should definitely just keep the tab in the row, with the sliding behavior. This is great feedback for the XAML team (and @teap in particular ☺️).

I've filed https://github.com/microsoft/microsoft-ui-xaml/issues/1685 upstream to make sure this gets added to WinUI, and so we can ingest it ourselves.

**Comment by tstager** [comment]
Do you guys realize that tab reordering crashes terminal if it was run as an administrator?

**Comment by DHowett-MSFT** [comment]
Uh we definitely fixed a bug like that two whole versions ago. Can you confirm the version you’re on?

**Comment by tstager** [comment]
0.11.1121.0

**Comment by tstager** [comment]
0.11.1121.0

**Comment by DHowett-MSFT** [comment]
https://github.com/microsoft/terminal/pull/5542

It looks like we regressed this when we were cleaning some stuff up.

**Comment by zadjii-msft** [comment]
Huh so I'm looking through the backlog here, and I honestly think we're gonna get to #1256 before the WinUI team is going to be able to get to  microsoft/microsoft-ui-xaml#1685. They're pretty swamped with Win11 work at the moment, and we've been making a lot of progress towards tear-out (see #5000). 

I'm just going to close this for now. It's still a good idea for the WinUI TabView, but one we probably won't end up needing ourselves 😅
