### ISSUE TITLE
How do I control which terminal is used for new panes?

### ISSUE THREAD

**Issue by VikingScientist** [microsoft/terminal#3738]
I'm looking at the [release notes](https://github.com/microsoft/terminal/releases) and this gives a pretty good introduction to the new Pane controls, but I cannot find how to control the profile which is used for new panes. It always uses my profile number 1 regardless of what original profile was used to spawn the new pane.

Also: a minor note that the default hotkeys are wrong for non-english keyboard layouts as discussed in #3737

**Comment by Bertieio** [comment]
It currently only launches the default profile. which is set at the top of the profiles.json
`"defaultProfile": "{GUID OF PROFILE}",`

**Comment by zadjii-msft** [comment]
In #1000 we're tracking all the remaining panes work we think we have left, including being able to set the profile you want to open a pane with. Specifically, you're looking for the following two issues:

/dup #998 Open panes with a specific profile
/dup #1756 The user should be able to configure what profile is used for splitting a pane. Currently, the default profile is used, but it's possible a user might want to create a new pane with the parent pane's profile.
