### ISSUE TITLE
Multi-line emoji crashes program

### ISSUE THREAD

**Issue by VikingScientist** [microsoft/terminal#3739]
# Environment

```none
Windows build number: 10.0.18362 Build 18362
Windows Terminal version (if applicable):  0.7.3291.0


Any other software?
```

# Steps to reproduce

Open a new WSL terminal and fill a commandline with emojis (i.e. copy-paste from https://getemoji.com/ ). Resize the terminal window (width) so emojis would need to change line, i.e. the newline character would move location.

# Expected behavior

Program would not crash

# Actual behavior

Program crashes. "WindowsTerminal.exe is not responding, would you like to close the program".

NOTE: It does not appear with all emojis, but the string " 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳 🤯 😬 😰 😱 🥵 🥶 😳" does cause a crash

**Comment by 0xd4d** [comment]
Smaller repro, open WSL in WT, paste one of these strings including the double quotes

- "🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶"
- "🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵"

```json
    "initialCols": 120,
    "initialRows": 30,
```

**Comment by zadjii-msft** [comment]
I have a feeling that this is #1360, which will be solved by #780, but just to make sure it is in fact the same thing, could you file a crash report?

/feedback

**Comment by VikingScientist** [comment]
I am unsure on where to find the Feedback Hub and thought #3739 was the crash report. If I press the "Feedback" button inside Windows Terminal, then I get sent directly to the github issue page.

I do not build from source, so I don't know where any debug information gets logged/printed.

**Comment by zadjii-msft** [comment]
You need to use the "feedback hub" application:
![image](https://user-images.githubusercontent.com/18356694/69735171-e304dc80-10f5-11ea-9816-f6e3f9f9a96d.png)


If you file a problem using the Feedback hub, and tag it as Apps > Windows Terminal, then hit the "share my feedback" button, you'll get an `aka.ms` link that we can use to look up the stack trace of the crash on our end.

**Comment by VikingScientist** [comment]
This app is blocked by company policy on my computer. I could see if I could try and recreate the entire setup on a different personal computer, but at this point I think it is easier if others try to recreate the bug as I don't think it should be too hard to reproduce.

**Comment by ts252** [comment]
Having had similar problems and found my way here, I've reported this via the feedback hub. I don't know how to get an aka.ms link from it but I referenced this github issue in my feedback.

For me it's an "unresponsive" not a crash per se. The tab you paste into freezes immediately, but other tabs are fine until you re-select the frozen one.

**Comment by DHowett-MSFT** [comment]
Got this under a debugger -- looks the same as /dup #1360
