### ISSUE TITLE
Full screen doesn't works on secondary monitors

### ISSUE THREAD

**Issue by kklorenzotesta** [microsoft/terminal#3742]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.476]
Windows Terminal version (if applicable): 0.7.3291.0

Primary monitor is a 21:9 1080p, secondary monitors are a 16:9 1080p and a 4:3 1024p
```

# Steps to reproduce

press `alt+enter` to enter full screen mode

# Expected behavior

The terminal should enter in full screen mode

# Actual behavior

On the primary monitor everything works correctly.

On my secondary 16:9 monitor the windows taskbar still visible and there is a black area in the terminal:
![169](https://user-images.githubusercontent.com/26228693/69722579-ced1d700-1117-11ea-8682-eee3430e41a8.png)

On my secondary 4:3 monitor the terminal is all black with a gray box and unusable:
![image](https://user-images.githubusercontent.com/26228693/69722623-e610c480-1117-11ea-932e-8e4c50c38ea9.png)

In all monitors the terminal exits correctly from full screen mode by pressing again `alt+enter`.

The problem happens also with the default profiles.json.

**Comment by encladeus** [comment]
This is a duplicate of #3710.

**Comment by kklorenzotesta** [comment]
@encladeus thanks! I didn't see that issue, apologies!
