### ISSUE TITLE
suppressApplicationTitle doesn't seem to work in all cases

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#3743]
# Environment

```none
Windows build number: Version 10.0.18363.476
Windows Terminal version: Version: 0.7.3291.0
```

# Steps to reproduce

I created a profile like this:

```json
{
    "name": "VS2017 Developer CMD",
    "tabTitle": "VS2017 Developer CMD",
    "commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/Tools/VsDevCmd.bat\"",
    "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
    "suppressApplicationTitle": true,
    "startingDirectory": "C:/Source"
},
```

# Expected behavior

The title of the tab should be `VS2017 Developer CMD`.

# Actual behavior

The title of the tab is `VS2017 Developer CMD - C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/Tools/VsDevCmd.bat`

![Knipsel](https://user-images.githubusercontent.com/3225656/69727651-40fbe900-1123-11ea-9428-e760e9cf37e0.png)

**Comment by 4k3or3et** [comment]
I can confirm the issue.

It works with:

"commandline" : "%windir%/system32/openssh/ssh.exe root@192.168.1.2

However when you have:

"commandline" : "%windir%/system32/openssh/ssh.exe root@192.168.1.2 -i path_to_the_authentication_key"

the title still changes to 'OpenSSH SSH client'...

Anything else i can try?
