### ISSUE TITLE
Option to set window border color

### ISSUE THREAD

**Issue by supercoww** [microsoft/terminal#3746]
# Description of the new feature/enhancement
We should add a setting option in profiles.json to change color or completely remove the white window border. Currently(v0.7) it can only be done by changing it in system settings which affects all applications.

# Proposed technical implementation details (optional)

**Comment by Tommasov** [comment]
Good suggestion, I agree.

**Comment by 4k3or3et** [comment]
I tought its a bug while dark theme is active. Looks OK in light theme but so ugly in dark one...

+1 for chagning color or removing white border.

**Comment by 4k3or3et** [comment]
> # Description of the new feature/enhancement
> We should add a setting option in profiles.json to change color or completely remove the white window border. Currently(v0.7) it can only be done by changing it in system settings which affects all applications.
> 
> # Proposed technical implementation details (optional)

May i ask how do you change the borders to black in system settings?

**Comment by supercoww** [comment]
> > # Description of the new feature/enhancement
> > We should add a setting option in profiles.json to change color or completely remove the white window border. Currently(v0.7) it can only be done by changing it in system settings which affects all applications.
> > # Proposed technical implementation details (optional)
> 
> May i ask how do you change the borders to black in system settings?

Change your accent color to black and select the checkbox for show accent colors on `title bars and window borders` from the color settings.

**Comment by j4james** [comment]
Isn't this just #3425?

**Comment by DHowett-MSFT** [comment]
Yep -- we're not likely to add custom border colors when we're actively trying to just _get rid of the borders_. /dup #3425.

**Comment by carlinmack** [comment]
#3425
