### ISSUE TITLE
Windows Terminal 0.7 immediately crashes on startup

### ISSUE THREAD

**Issue by johnc44** [microsoft/terminal#3747]
# Environment

Microsoft Windows [Version 10.0.18363.476]
Windows Terminal 0.7

# Steps to reproduce

Start Windows Terminal.

# Expected behavior

Was hoping the application would open..

# Actual behavior

The terminal icon appears in the start bar, then a moment later it disappears.  The application never starts.

I've been using Windows Terminal for the last few versions and it's been fine.  I upgraded to 0.7 today and now it no longer opens.  I tried uninstalling and reinstalling it.  I also tried explicitly removing profile.json, because i had previously changed it.

I've also tried rebooting.

**Comment by zadjii-msft** [comment]
Thanks for the report! Would you mind filing a report with the feedback hub so we can get a stack trace and see what's going on?

/feedback

**Comment by johnc44** [comment]
That was quick!  I've submitted something through feedback hub now.  I didn't realise it could be used for things like this.

**Comment by zadjii-msft** [comment]
@johnc44 Could you share the `aka.ms` link from the "Share my feedback" button here? I can't look it up without that unfortunately 🤣

**Comment by johnc44** [comment]
Oops, sorry - https://aka.ms/AA6ptgu

**Comment by Viruslav** [comment]
I have almost the same issue/crash - the window shows as a non-transparent single color rectangle and then disappears. I tried resetting and reinstalling but nothing helped. I tried on 2 very different devices and it was the same. I already submitted a feedback in the Feedback Hub but unfortunately I didn't include a stack trace.

**Comment by zhoupro** [comment]
Same problem

**Comment by Ma5ker** [comment]
Same problem,Microsoft Windows [Version 10.0.18363.476]

**Comment by johnc44** [comment]
Just noticed that I do get a single colour rectangle as per @Viruslav - I just didn't notice it yesterday.

**Comment by gregmuellegger** [comment]
Same problem here.

**Comment by a-wasilewski** [comment]
Same here. Updated today and app crashes after start. Only single grey color and then window immediately closed.
I updated through MS Store.

**Comment by owennewo** [comment]
Something to try...
Delete your terminal settings file (make a backup first!).

My settings file is below but there is a hash in the directory name so yours will probably be different:
`<User>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json
`
My guess is that will get you up on your feet and you could play around with introducing parts of the old file to see what is causing the crash.

**Comment by Viruslav** [comment]
I use custom scaling set at 160% on both PCs.

**Comment by owennewo** [comment]
It would be useful to know if original poster has custom scaling.  If so this issue can be marked as duplicate of #3749.  It's entirely possible there is more than one reason for startup....

**Comment by elangelo** [comment]
I have the same
tried deleting the appdata folder and i have no custom scaling set.

**Comment by johnc44** [comment]
@owennewo  Yes, I have custom scaling set to 135%, mirrored displays.  (

I've already tried deleting profile.json which didn't help.

**Comment by marknelson** [comment]
this is my first install - i'm seeing the same symptoms. 175% scaling. Yeah, deleted profile, same thing.

**Comment by colcrunch** [comment]
I am having the same issue as this after an app update.

Feedback Hub link with Error Logs:
https://aka.ms/AA6q4df

**Comment by vuhg** [comment]
Hey guys, several usages are fine with normal 125% scale.
But the Terminal crash when i use **custom scale** 138%.

**Comment by zhoupro** [comment]
I disable advanced scale, Now It works fine.

**Comment by zhoupro** [comment]
> Hey guys, several usages are fine with normal 125% scale.
> But the Terminal crash when i use **custom scale** 138%.

Thanks for your tips.

**Comment by gregmuellegger** [comment]
Disabling custom scaling worked for me as well! Thanks so far.

**Comment by Viruslav** [comment]
I'm not gonna change my custom scale factor. I'd rather not use this terminal. I'm sorry but this is not a solution. Everything else works just fine.

**Comment by VictorNanka** [comment]
It’s working when I change the custom scale factor into default. Thanks a lot.

**Comment by DHowett-MSFT** [comment]
This looks like a /dupe of #3749. Thanks!
