### ISSUE TITLE
Windows Terminal hangs when hitting Ctrl-C many times

### ISSUE THREAD

**Issue by doggy8088** [microsoft/terminal#3748]
# Environment

```none
Windows build number: 10.0.18363.476
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce

1. Open Windows Terminal
2. Run **cmd** shell
3. Hit `Ctrl-C` twice very quickly.
4. Then the **cmd** shell just hangs.

# Expected behavior

It should show up prompt after hitting `Ctrl-C` many times.

# Actual behavior

The shell window get hang.

Here is a video clip that shows the situation. The demo contains two keystroke, the first is simply `Ctrl-C`, the second one if hit `Ctrl-C` twice very quickly.

![2019-11-28_00-28-06](https://user-images.githubusercontent.com/88981/69741488-17b87880-1176-11ea-8182-fb768c60e06d.gif)

**Comment by GaganBhat** [comment]
I am not able to reproduce this. For some reason, it looks like your terminal is doing something that the `exit` command causes. 

![3OoQdPFctq](https://user-images.githubusercontent.com/25236969/69918211-14064980-1435-11ea-90e1-6439969c7a58.gif)

**Comment by doggy8088** [comment]
The problem is gone for now. I don't know why.

**Comment by sterlingdcs-damian** [comment]
This is still an issue
