### ISSUE TITLE
vim colorscheme does render BG colors correctly. Corrupts shell window BG colors.

### ISSUE THREAD

**Issue by OriginalMadProgrammer** [microsoft/terminal#375]
Linux HEINLEIN 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the [console issue tracker](https://github.com/microsoft/console/issues).

Seems related to https://github.com/Microsoft/console/issues/85

**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
    Microsoft Windows [Version 10.0.17134.590]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Each CASE starts with a freshly started shell window.

CASE 1: 

    vi /etc/passwd
    :colorscheme blue
    :q 

* What's wrong / what should be happening instead:
   Expected: Background should be entirely blue, unless syntax highlighting changed it. 
   Observed: Blue background stops at the end of each line then returns to native black.

   Expected: on exit screen should return to all black background on return to shell. 
   Observed: blue background on characters of bottom line that also returns to native black at EOL.
   New blue background under text are  for each new line written.

NOTE: repeating the vi command produces a screen with full blue background, as desired.. 

CASE 2:
https://github.com/GilbertsHub/web-utils/blob/master/cgibinIntercept.sh

    vi cgibinIntercept.sh 
    :colorscheme blue
    :q 

 Expected: background is all blue. 
 Observed: in this case background is correctly all blue. 

 Expected: on exit shell window should return to black background.
 Observed: same is with CASE 1 exit.

**Comment by ntak** [comment]
The patch 8.1.0933 I sent to Vim the other day is invalid. I will fix it now.

**Comment by ntak** [comment]
I fixed, confirmed and sent PR. Sorry for the inconvenience.

**Comment by ntak** [comment]
After that, you can move here: https://github.com/vim/vim/issues/3988
Thank you very much.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! I'm not able to reproduce this on 17763 (the October 2018 Update) or the latest Insider builds. We've been improving SGR handling over time, so I'm not terribly surprised about that.

Would you mind testing this again once you get to the October update?

**Comment by ntak** [comment]
Sorry, it is a careless mistake of the patch I submitted to Vim.
WIndows 7 can also be reproduced in the same way, it will be like this.
It is a shot just scrolled up.

![image](https://user-images.githubusercontent.com/44701315/52978152-641a9f00-3413-11e9-90ad-34fc6a54b43a.png)

It is now being fixed.

**Comment by zadjii-msft** [comment]
This looks like it was fixed at some point in the past - unclear when precisely:

![image](https://user-images.githubusercontent.com/18356694/142878228-efc101d4-b6a6-4050-aa8e-02f865e574fe.png)
