### ISSUE TITLE
when using a dual monitor setup, fullscreen only works on the primary monitor

### ISSUE THREAD

**Issue by dcasati** [microsoft/terminal#3750]
# Environment

```noformat
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
Win32NT             10.0.19023.0 Microsoft Windows NT 10.0.19023.0
```

# Steps to reproduce
1. Using Windows Terminal (Preview) Version: 0.7.3291.0 try to go full screen on a second monitor (with F11 or ALT+Enter).

# Expected behavior
See the terminal in fullscreen. This works just as expected on the primary monitor.

# Actual behavior
the terminal doesn't show up.

![windows-terminal-dual-monitor-2019-11-27 105217](https://user-images.githubusercontent.com/3240777/69747885-6af1e300-1104-11ea-9cce-1d498d46cdcb.png)

**Comment by moswald** [comment]
I have three monitors, and full screen behaves differently on each. My center (primary) monitor it works fine. On my right monitor, the terminals are only sized about 20px wide (collectively), but the app does take up the whole monitor. On my left monitor, the app takes up the whole monitor, but now the terminals are sized larger than the app. I'm using panes, and what happens is my right-most pane is pushed offscreen, while my center and left panes are visible and look somewhat normal.

**Comment by Srfigie** [comment]
I also am having this issue when going full screen on any non-primary monitor

**Comment by dcasati** [comment]
Guys, just retest this. seems to be related to something else. closing this issue.

**Comment by urossavelj** [comment]
It actually crashes if I put it to full screen on other monitor than the primary one.
