### ISSUE TITLE
Deterministic location of the configuration file

### ISSUE THREAD

**Issue by r-darwish** [microsoft/terminal#3751]
# Description of the new feature/enhancement
I would like to add support to [Topgrade](https://github.com/r-darwish/topgrade) for pulling the terminal configuration from Git if it resides in a Git repository. On my machine, the location of the configuration is at `c:/Users/roey/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/profiles.json`. I assume that `8wekyb3d8bbwe` is some kind of ID that might be different on other computers or might change on my computer. Is there any way for an external application to determine whether Terminal is installed and where is the location of the configuration file?

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This location is deterministic. It's generated from the package family name (`Microsoft.WindowsTerminal_8wekxxxxxxx`), which is generated from the code signing certificate we use :smile: That ID unequivocally identifies all Microsoft store applications.
