### ISSUE TITLE
Title bar icons unusable

### ISSUE THREAD

**Issue by mKay00** [microsoft/terminal#3755]
# Environment

```
Windows build number: 10.0.18363.0 and 10.0.19033.0
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce

I don't know, I just started Windows Terminal today on my PC and it happened. A few hours later the same happened on my Surface Pro 5

# Expected behavior

I expect the title bar to be clickable and functioning (e.g. clicking on the "+" opens a new tab or clicking the arrow opens the option pane)

# Actual behavior

The whole title bar is unclickable. Including the "X" to close the tab, the "+" to open a new tab, the arrow for the options pane, as well as minimize, maximize and close. But I can use the open terminal window and enter commands. And I can move the window when clicking on the title bar and dragging.

Weirdly enough it works (for now) on my PC, without doing anything.

Edit: Something I just noticed is that the mouse cursor seems to keep the symbol when entering the Windows Terminal window, i.e. if I move my mouse slowly from left to right into the Terminal window, the cursor changes to the horizontal resize symbol and keeps this symbol as long as I am inside the Terminal window with my mouse (except between the part between the down arrow for the options pane and the minimize button, there the mouse cursor changes to the normal mouse pointer)

**Comment by greg904** [comment]
Sounds similar to #3325.

**Comment by mKay00** [comment]
Indeed! I looked for similar issues, but couldn't find one. So I guess this can be closed. But the issue apparently still exists 😅

**Comment by greg904** [comment]
Yeah it's hard to look for duplicate issues if you don't have the right keywords.

**Comment by DHowett-MSFT** [comment]
Thanks for the report @mKay00 and finding the dupe @greg904! /dup #3325.
