### ISSUE TITLE
Terminal doesn't respect refresh rate

### ISSUE THREAD

**Issue by GavinHaak** [microsoft/terminal#3756]
This issue applies where the user has a monitor with a refresh rate greater than 60hz.

If the Terminal window is selected, the refresh rate drops back to 60hz across the users desktop regardless of the users selected refresh rate (i.e 120hz).

Tested on Windows 10 Pro, OS Build 18362.476, Terminal Release 7.

**Comment by h1nk** [comment]
Why was this closed? This still very much a problem.

**Comment by DHowett-MSFT** [comment]
Probably because the author found #649
