### ISSUE TITLE
Launch profiles by alt-clicking in task bar.

### ISSUE THREAD

**Issue by dmvtech** [microsoft/terminal#3757]
# Description of the new feature/enhancement

Sometimes I want to be able to launch Windows Terminal with a specific profile (not my default profile). It would be nice to be able to have an option to be able to right-click in the taskbar (or start menu/start screen) and be able to launch that. Here is an example for NotePad++ that launches recent documents:
![image](https://user-images.githubusercontent.com/43397658/69766206-bc619880-112b-11ea-8534-5df6d8effb4c.png)

**Comment by j4james** [comment]
This sounds like #576 and #2339.

**Comment by DHowett-MSFT** [comment]
Yep! /dup #576.
