### ISSUE TITLE
Display abnormal when delete command line more than one line

### ISSUE THREAD

**Issue by vscpp** [microsoft/terminal#3760]
1. Type a command that more than one line as below picture.
2. Press backspace key to clear command. But still one character remained (t）
![image](https://user-images.githubusercontent.com/26138585/69783073-b3d19680-11ed-11ea-86c3-ff7823941f16.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! I think this is actually already be tracked in another thread, so I'll direct attention to that thread: 

/dupe #1245
