### ISSUE TITLE
GetGuid noexcept function throws

### ISSUE THREAD

**Issue by mkitzan** [microsoft/terminal#3763]
# Environment

```none
Windows build number: 0.0.1.0 Dev Build
Windows Terminal version (if applicable): 10.0.18363
```

# Steps to reproduce

Invoke [`Profile::GetGuid`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Profile.cpp#L141) on a `Profile` object without a GUID.

# Expected behavior

`GetGuid` is specified as `noexcept`, the compiler and users expect the function to never throw.

# Actual behavior

Exception thrown by a `noexcept` function.

New function semantics need to be decided for `GetGuid` and functions affected by `GetGuid` no longer being `noexcept`. Could be fixed by removing the `noexcept` specifier from the function and all affected functions.

**Comment by zadjii-msft** [comment]
You're not wrong. I bet it was never changed from `noexcept` back when `Profile`s just had a `GUID`, as opposed to an `std::optional<GUID>`

**Comment by mkitzan** [comment]
@zadjii-msft, sounds like you're going to be [working in this area soon](https://github.com/microsoft/terminal/issues/3680#issuecomment-559298230). I can make the `noexcept` corrections once you're finished. Until then I'll just find all the affected functions.

**Comment by mkitzan** [comment]
I have a branch in my fork with the changes revoking `noexcept`, but PR [#3762](https://github.com/microsoft/terminal/pull/3762) needs be merged so its code can be fixed too.

**Comment by DHowett-MSFT** [comment]
Thanks for working on this! We'll be a bit slow on account of it's the Thanksgiving holiday here in the US, but we'll try to get through your PRs. :smile:
