### ISSUE TITLE
when starting git gui in Powershell 5.1, next line shows ANSI codes

### ISSUE THREAD

**Issue by peetrike** [microsoft/terminal#3767]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3291 (and 0.6.2951.0)

Any other software?
Git for windows (v2.24.0.windows.2)
Windows Powershell v5.1
```

# Steps to reproduce

1. On Windows Powershell prompt enter `git gui`
2. On next line start entering next command

# Expected behavior

the entered text shows as it is supposed, with correct coloring from PSReadline.

# Actual behavior

ANSI escape codes are showed until Enter is pressed.  The actual input is correctly executed.

![image](https://user-images.githubusercontent.com/34946805/69823900-fb1e4e00-1212-11ea-93eb-ad17ba44055e.png)

When PSReadline module is removed from session, the problem ceases to exist.

**Comment by DHowett-MSFT** [comment]
This is a bad interaction between PSReadline and `git` -- one or the other is failing to restore the console mode to one that supports VT. Does it work with the new PSReadline verison in PowerShell 6/7?

(closing this as it's a shell/application issue)
