### ISSUE TITLE
Default keybindings are not cancelled after modification

### ISSUE THREAD

**Issue by pxl-th** [microsoft/terminal#3769]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce

- Press `F11` => Terminal goes fullscreen
- Change in settings keybindings for `toggleFullscreen` to any other keybinding, for example:
```
"keybindings": [
   {"command": "toggleFullscreen", "keys": ["alt+f"]}
]
```
- Press `F11` => Terminal **still** goes fullscreen
- Press `Alt + F` => Terminal goes fullscreen

# Expected behavior

- Press `F11` => Terminal goes fullscreen
- Change in settings keybindings for `toggleFullscreen` to any other keybinding, for example:
```
"keybindings": [
   {"command": "toggleFullscreen", "keys": ["alt+f"]}
]
```
- Press `F11` => Terminal **does not** go fullscreen
- Press `Alt + F` => Terminal goes fullscreen

**Comment by DHowett-MSFT** [comment]
You need to unbind `f11` by adding a binding with a `null` command. Keys are bound to commands, so user key bindings are additive.

**Comment by pxl-th** [comment]
Thanks! Didn't notice that in [docs](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md) first time.
