### ISSUE TITLE
ColorTool switches --both and --xterm throw error

### ISSUE THREAD

**Issue by ianmcl** [microsoft/terminal#377]
Microsoft Windows [Version 10.0.17763.346]
colortool v1.0.1810.02002

* What I'm doing and what's happening: 
Occurs in both user and elevated command prompt
`ColorTool.exe` and `/schemes/` directory are both in `C:\WINDOWS\system32`
```
C:\WINDOWS\system32>colortool campbell -b -x
Could not find or load "-x"
```
```
C:\WINDOWS\system32>colortool campbell -b
Could not find or load "-b"
```
```
C:\WINDOWS\system32>colortool campbell -x
Could not find or load "-x"
```
```
C:\WINDOWS\system32>colortool campbell --both
Could not find or load "--both"
```
```
C:\WINDOWS\system32>colortool campbell --xterm
Could not find or load "--xterm"
```
* What's wrong / what should be happening instead:
Switches should not throw error and work

**Comment by Megasware128** [comment]
`colortool.exe [options] <schemename>`
Place options first, after that the scheme name ;)
