### ISSUE TITLE
Invalid JSON in  terminal/doc/cascadia/profiles.schema.json 

### ISSUE THREAD

**Issue by jdevens** [microsoft/terminal#3771]
Missing a comma in line 212

**Comment by DHowett-MSFT** [comment]
Happy to review a pull request for this. Thanks!

**Comment by jdevens** [comment]
@DHowett-MSFT - got one at 3772, first time using Github, though, so not sure if I need anything else. Let me know if I'm missing anything!

**Comment by DHowett-MSFT** [comment]
You nailed it. Thanks again!
