### ISSUE TITLE
Changing the title bar color in accordance with the terminal's background.

### ISSUE THREAD

**Issue by mohamedhaddi** [microsoft/terminal#3774]
# Description of the new feature/enhancement

It would be great if the backgroud color also applied to the title bar, for example, this is the terminal with a custom background color:

![1](https://user-images.githubusercontent.com/6943864/69833863-cb813d00-1236-11ea-8fb2-f7ef940a337a.png)

This is how it should look with the added feature (supposing the thick white border issue was fixed as well):

![2](https://user-images.githubusercontent.com/6943864/69833981-ad680c80-1237-11ea-9c95-28f5f9bbf712.png)

I think the tabs color doesn't look the best either, I don't have any ideas but maybe adding some opacity to them would look better...

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This looks like the inverse of #3310.

**Comment by mohamedhaddi** [comment]
@DHowett Interesting! What if both perferences were added as a boolean option? But also with the ability to change the one left (either the tab or the title bar) to a prefered color.
For example, I'd love for the tab to take my system's accent color:
![1](https://user-images.githubusercontent.com/6943864/69902144-56bf1780-138a-11ea-82d5-743ca60ebc5a.png)

Also, another suggestion is that I think it'd look great if the tabs were (just like in Microsoft Edge) attached to the upper side of the window:
![2](https://user-images.githubusercontent.com/6943864/69902152-6179ac80-138a-11ea-9909-e38e305799ea.png)

**Comment by DHowett-MSFT** [comment]
If we're going to do this, we have to figure out how it works with split panes. For now, it's backlogged and marked as requiring a spec. Thanks!

**Comment by mdtauk** [comment]
> If we're going to do this, we have to figure out how it works with split panes. For now, it's backlogged and marked as requiring a spec. Thanks!

The Active pane could set the window background colour - maybe with a short 500ms colour transition animation

**Comment by simioni** [comment]
If the title bar takes the same color as the window, the active tab should be rounded at the bottom too. No point for it to float midair with a squared bottom.

![69902144-56bf1780-138a-11ea-82d5](https://user-images.githubusercontent.com/7426615/78491871-1b10d180-771f-11ea-9d46-81fc51ff97df.png)

**Comment by mohamedhaddi** [comment]
@simioni looks nice!

**Comment by mdtauk** [comment]
> If the title bar takes the same color as the window, the active tab should be rounded at the bottom too. No point for it to float midair with a squared bottom.
> 
> ![69902144-56bf1780-138a-11ea-82d5](https://user-images.githubusercontent.com/7426615/78491871-1b10d180-771f-11ea-9d46-81fc51ff97df.png)

The padding would need to be adapted to account for there being no gap between the console background and the window edge

**Comment by zadjii-msft** [comment]
I'm yanking this out of the spec tracker, since this is incorporated in the spec for #3327, over in #5772. Thanks!

**Comment by isayakmondal** [comment]
How to get the desired effect that OP wanted?

**Comment by isayakmondal** [comment]
I think it's only available in the preview version. @zadjii-msft

**Comment by isayakmondal** [comment]
Write now it's looking like this
![image](https://user-images.githubusercontent.com/51121313/226403513-e11b224e-2b57-41f7-900e-8c69b1b1bcc3.png)
Please check out the file here -> [settings.json](https://gist.github.com/isayakmondal/7750f0ad485cd900416ec5e37b89f010)

**Comment by zadjii-msft** [comment]
Not in 1.16, that was only fixed in 1.17, in #13935

**Comment by isayakmondal** [comment]
Got it, any idea when will that be a stable release? @zadjii-msft

**Comment by zadjii-msft** [comment]
We don't have a timetable at the moment, though, Preview is typically just as stable. I suspect we won't be shipping a new release for a couple of months, we've got some BIG changes in the pipeline that will take a little longer to bake than usual.

**Comment by isayakmondal** [comment]
Alright, thank you, keep up the good work. 1.16 would work for me atm. @zadjii-msft

**Comment by isayakmondal** [comment]
On a whole separate topic is there any feature to have the context menu while right-clicking? By default, it pastes things which is pretty annoying for me instead I would like a context menu as we can find in git bash or in other terminal emulators? @zadjii-msft

**Comment by zadjii-msft** [comment]
@isayakmondal That's tracked elsewhere in the repo, in #3337.

**Comment by debajyoti1990** [comment]
I am able to get the tab bar to follow the terminal background but, there's a thin line below tab bar which is kind of annoying.
