### ISSUE TITLE
TrueType font linking does not work

### ISSUE THREAD

**Issue by akritikos** [microsoft/terminal#3778]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
```

# Steps to reproduce

- Add a monospace TrueType font and configure a profile to use it
- Add a second font and configure it as fallback to the first using font linking
- Open Windows Terminal
- Characters are reported as missing despite existing in the fallback font

# Expected behavior

Characters rendered using the main font, missing glyphs being rendered from the first font containing it in the FontLink configuration.

Here's a preview on PowerShell Core
![image](https://user-images.githubusercontent.com/1242406/69868224-d0cf9d80-12b1-11ea-8156-3421b190a2fc.png)
 
With the following entries under FontLink
![image](https://user-images.githubusercontent.com/1242406/69868291-fceb1e80-12b1-11ea-90aa-7918447fcdbd.png)

# Actual behavior

Windows Terminal ignores FontLink configuration and renders characters as missing. Same session as in the expected behavior, using Windows Terminal:
![image](https://user-images.githubusercontent.com/1242406/69868362-2c019000-12b2-11ea-8c5a-72f86223d1c0.png)

**Comment by hanubeki** [comment]
I think it's the restriction of DirectWrite that doesn't use FontLink.
Maybe related: #1163, #1790, #2664

**Comment by DHowett-MSFT** [comment]
TryeType font linking isn't going to be supported in anything that isn't GDI.
/dup #2664
