### ISSUE TITLE
No description of /src/cascadia in code organization

### ISSUE THREAD

**Issue by K1ngjulien** [microsoft/terminal#3780]
https://github.com/Microsoft/Terminal/blob/master/doc/ORGANIZATION.md

This file seems like it should have documentation about the "/src/cascadia/" folder, which it doesn't.

I'd like to contribute to this project but have been struggling with what does what. Figureing that out by myself could take a while :).

**Comment by DHowett-MSFT** [comment]
Ah, good catch. `src/cascadia` contains all of the _Windows Terminal_-specific code. The rest of the code is all either shared or part of the windows console host.

**Comment by K1ngjulien** [comment]
I thought so, but that's about all I could figure out on my own.
