### ISSUE TITLE
cmder does not appear in the list of available shells

### ISSUE THREAD

**Issue by radcapitalist** [microsoft/terminal#3783]
# Description of the new feature/enhancement
Support cmder as one of the optional shells you can use in Windows Terminal

# Proposed technical implementation details (optional)
Not real sure, but I can use cmder in a CMD window, so it seems like I ought to be able to use it in a Windows Terminal window.

If I have cmder installed, and maybe if I tell you where to find it, it would nice if showed up in the list of shells that you can pick from to use in Terminal.

**Comment by DHowett-MSFT** [comment]
You are aware that you can add your own shells to Windows Terminal, yes? If we start adding every shell in existence we’ll have a very long list indeed :smile:

**Comment by radcapitalist** [comment]
Hey, Dustin - I wondered about that and web-searched it a little and didn’t see anything, but it sounds like the ability is there, so I will look into it further.  Thanks!

Eric

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DHowett-MSFT** [comment]
I’ll close this bug out, but let me know if you need anything else!

**Comment by radcapitalist** [comment]
In case others stumble into this. I was able to get cmder working in Windows Terminal.  My profile ended up looking like this:

`        {
            "guid" : "{3254f3d4-eeff-43d7-a869-59642a7757b7}",
            "commandline" : "cmd.exe /k %CMDER_HOME%\\vendor\\init.bat",
            "icon" : "%CMDER_HOME%\\icons\\cmder.ico",
            "name" : "cmder",
            "useAcrylic" : false,
            "acrylicOpacity" : 1.00,
            "fontFace" : "Consolas",
            "fontSize" : 12,
            "closeOnExit" : true,
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%"
        },
`
Eric

**Comment by zadjii-msft** [comment]
(For others getting here: we also have a growing list of "How to add third party tools to the Terminal", which you can find here: https://github.com/microsoft/terminal/blob/master/doc/user-docs/ThirdPartyToolProfiles.md

This guide actually already includes cmder ☺️
