### ISSUE TITLE
Fullscreen on secondary display has has more than double the expected width

### ISSUE THREAD

**Issue by krage** [microsoft/terminal#3785]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3291.0
```

Two displays on same nvidia GPU (441.41 drivers). Primary is 2560x1440, secondary positioned to the left is 1920x1200.

# Steps to reproduce

Use powershell `$Host.UI.RawUI.WindowSize` to check dimensions of terminal both maximized and fullscreen.

# Expected behavior

Fullscreen terminal should report at most a handful of extra rows/cols compared to a maximized window (accounting for space consumed by window border/task bar).

# Actual behavior

For primary monitor as expected:
Maximized: 229x61
Fullscreen: 231x63

On secondary monitor *gigantic* width in fullscreen:
Maximized: 171x50
Fullscreen: **348**x52

The fullscreen window itself is still correctly sized to the display.  The left/top/bottom edges of the terminal content are aligned to the matching edges of the window (or approximately when fullscreened directly from maximized ala #3709).  The extra columns aren't visible beyond the right edge of the window.

**Comment by DHowett-MSFT** [comment]
This may (???) be helped by #3721?

**Comment by krage** [comment]
I've built a copy of that branch in #3721 and it does appear to fix this behavior for me.

I removed my settings file to directly compare the powershell-reported dimensions of the built-in defaults across both:

## Release Build
Primary Display Maximized 280x64
Primary Display Fullscreen (from non-maximized) 280x67
Primary Display Fullscreen (from maximized) 283x67
Secondary Display Maximized 209x52
Secondary Display Fullscreen (from non-maximized) 423x56
Secondary Display Fullscreen (from maximized) 425x55

## #3721 Build
Primary Display Maximized 280x64
Primary Display Fullscreen (from non-maximized) 280x67
Primary Display Fullscreen (from maxmimized) 280x67
Secondary Display Maximized 209x52
Secondary Display Fullscreen (from non-maximized) 209x56
Secondary Display Fullscreen (from maximized) 209x56

So can confirm on my setup at least that it fixes both the incorrect width on secondary display and the fullscreen from maximize issues.
