### ISSUE TITLE
Text Cursor Indicator does not move with cursor

### ISSUE THREAD

**Issue by Migod11** [microsoft/terminal#3791]
# Environment

```none
Windows build number: 10.019033.0
Windows Terminal version (if applicable): 0.7.3291.0

Any other software? -
```

# Steps to reproduce

Turn text cursor indicator in windows settings, and start wt

# Expected behavior

Text Cursor Indicator follows text cursor, works fine in Windows Console

# Actual behavior

Text cursor is displayed, but does not follow cursor
<img width="455" alt="Annotation 2019-12-01 085324" src="https://user-images.githubusercontent.com/17233518/69911484-6edf7700-141c-11ea-973c-573d6e24696b.png">

**Comment by DHowett-MSFT** [comment]
Yeah, looks like we'll need to notify some input subsystem where the insertion point is. Thanks!

**Comment by shanselman** [comment]
Just checking in.
![image](https://user-images.githubusercontent.com/2892/73687544-23954f00-467f-11ea-86ab-8c8addee1ecb.png)

**Comment by DHowett-MSFT** [comment]
Yep: this bug will be closed when we believe the issue to be fixed. :smile:
