### ISSUE TITLE
cannot tail new content using `tail -f file.log` in terminal ubuntu, except `Get-Content file.log` at same time in PowerShell 

### ISSUE THREAD

**Issue by yuercl** [microsoft/terminal#3796]
# Environment

```none
Windows Terminal version: 0.7.3291.0 . Windowns Terminal (Preview)
```

# Steps to reproduce
- Tab A install ubuntu, Tab B  use PowerShell default.
- Run program background at Tab A, and program will print new lines into file.log continuously.
- Tab A `tail -f file.log`, will see some lines, but cannot display lines appended.
- Tab B `Get-Content file.log -Wait -Tail 10`  can see new lines appended.
- Tab B `Get-Content ...` and Tab A `tail -f ...`, tail -f can display nen lines  continuously.

# Expected behavior

tail -f file.log is same as pure ubuntu

**Comment by DHowett-MSFT** [comment]
This sounds like an issue you should report on [the WSL repository](https://github.com/microsoft/wsl). I’m betting that it happens even when you use powershell and WSL outside of Windows Terminal.
