### ISSUE TITLE
Background image supports animated APNG (or WEBP)

### ISSUE THREAD

**Issue by Xdminsy** [microsoft/terminal#3798]
# Animate .apng/.webp background image

I can use an animated .gif as my background image. But due to GIF color limit, I want to use APNG instead to have a high-resolution animated background.

But now when I specified a .apng or a .webp file in backgroundImage, Windows Terminal only displays the first frame with no animation.

Could you please add support for APNG (or WEBP).

**Comment by zadjii-msft** [comment]
Seems like a reasonable feature request to me ☺️

**Comment by Xdminsy** [comment]
Thanks for your reply!

I thought it was the Terminal treat GIF differently, but I did some searches right now and find that in [TermControl.cpp](https://github.com/microsoft/terminal/blob/901a1e1a09ed66f5556407d34b39af7404fa7f69/src/cascadia/TerminalControl/TermControl.cpp#L323) Windows Terminal just treat all picture formats the same, and simply set the bgImageLayer source. It is the [Image Control](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image#remarks)(or actually BitmapImage) automatically animate gif and only gif.

I figure that it seems not to be an easy work to support additional formats like APNG.
Well, how can we achieve this, could you give me some ideas? Need we implement a derived Image Control with more formats supported? Sorry for that I don't know much about Xaml or Windows Terminal.

**Comment by zadjii-msft** [comment]
Honestly I don't know that much about XAML either 😝 I'd imagine the best way to solve this would be to try and get support added upstream at [microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml). Hopefully they'd accept contributions to enable APNG in `BitmapImage`. If they can't add support there, then we'd need to somehow manually add support for that as an `ImageSource`, which I don't know how possible that would be.

**Comment by Xdminsy** [comment]
Oh, I see, many other programs may benefit if xaml supports APNG directly.

**Comment by DHowett-MSFT** [comment]
This one may be better-suited for filing on microsoft-ui-xaml. Would you mind making the request over there? It'll mean more coming from a community member. :smile:
