### ISSUE TITLE
Stuck when type `exit` command in cmd

### ISSUE THREAD

**Issue by imReker** [microsoft/terminal#3800]
# Environment

```none
Windows build number: 10.0.19018.1
Windows Terminal version (if applicable):
0.7.3291.0

Any other software?
```

# Steps to reproduce

Test 1: Start a `PowerShell` tab and type `exit` then hit enter.
Test 2: Start a `cmd` tab and type `exit` then hit enter.

# Expected behavior

In both Test 1 and 2, terminal tab get closed correctly.

# Actual behavior

PowerShell closed correctly in Test 1.
Cmd tab stuck in Test 2.

**Comment by jonnygehlot** [comment]
Yes same this is happening to me

**Comment by DHowett** [comment]
File a new bug, this one is five years old.
