### ISSUE TITLE
Add ability to change profile settings when shell is not active.

### ISSUE THREAD

**Issue by pf-mike-breaton** [microsoft/terminal#3802]
# Description of the new feature/enhancement

When multiple windows are open on a monitor(s), it would be visually useful for Windows Terminal to have slightly different appearances when it has focus or not - e.g., bright text when terminal has focus, vs gray text when not.

# Proposed technical implementation details (optional)

Perhaps add "inactive" property to the profile of each shell that can override any of the other shell profile properties.

```(json)
"profiles":
    [
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore",
            "fontSize": 10,
            "foreground": "#ffff00",
            "colorScheme": "Campbell",
            "acrylicOpacity": 1,
            "background": "#20207f",
            "useAcrylic": true,
            "inActive": {
                "foreground": "#808080",
            }
        }
    ]
}
```

When the shell window loses focus, its profile changes to match the settings specified in the "inActive" profile settings

**Comment by zadjii-msft** [comment]
@pf-mike-breaton This is a good idea! In fact, it's such a good idea, that we're actually already tracking the same request over in #3062. You can follow the development over in that thread ☺️ 

/dup #3062
