### ISSUE TITLE
Cannot open files beginning with '.' and containing additional '.' from jump list

### ISSUE THREAD

**Issue by pf-mike-breaton** [microsoft/terminal#3808]
# Environment

 Win32NT             10.0.19033.0 Microsoft Windows NT 10.0.19033.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

1. Open a file beginning with a '.' and containing another (e.g., .profile.json) in Windows Explorer by selecting "Open with Code" in file's context menu
2. Exit Visual Studio Code
3. Bring up Visual Studio Code's jump list
4. Select the file opened in step 1

# Expected behavior

Expected the file to open in VS Code

# Actual behavior

Error message stating:

> The item you selected is unavailable. It might have been moved, renamed, or removed. Do you want to remote it from the list?

**Comment by DHowett-MSFT** [comment]
This is not the [VS Code repository](https://github.com/microsoft/vscode). Please file this bug there.
