### ISSUE TITLE
Terminal cannot start up and crash (when Scale and layout IS 100%)

### ISSUE THREAD

**Issue by elangelo** [microsoft/terminal#3814]
This is not a duplicate of #3813, #3749, ...

I have no custom scaling. Tried removing and reinstalling, removed all settings.

# Environment

Windows build number: 
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT **10.0.18362.0**
```
Windows Terminal version (if applicable): `0.7`

Any other software?
```

# Steps to reproduce

just try starting the terminal

# Expected behavior

terminal starts

# Actual behavior

I see a short flash of something like a window but then it immediately vanishes

**Comment by elangelo** [comment]
I figured this one out... apparently somehow my $ENV:Path did not longer contain cmd.exe and powershell.exe. Which apparently is enough to make terminal crash.

**Comment by mika76** [comment]
Had the same issue - thanks @elangelo!
