### ISSUE TITLE
When opening a new terminal with WSL (Debian) as the default tab, it doesn't fill the available vertical space

### ISSUE THREAD

**Issue by tovine** [microsoft/terminal#3815]
When opening a new Terminal window with Debian as the default shell, the height is capped to 27 lines before it starts scrolling - regardless of the actual window height. Resizing the window doesn't help either.
If I open a new tab (Debian or otherwise) it works as expected, and all subsequent tabs will work as well.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
Debian WSL: Linux tone 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux
```
Terminal config: [profiles.json.txt](https://github.com/microsoft/terminal/files/3916823/profiles.json.txt)

# Steps to reproduce

Start a fresh Terminal with Debian as the default tab

# Expected behavior

![image](https://user-images.githubusercontent.com/8265757/70054507-fde4be80-15d7-11ea-96e3-26469bae8534.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/8265757/70054433-db52a580-15d7-11ea-883c-6c8409847624.png)

**Comment by zadjii-msft** [comment]
@tovine What happens if you set the `historySize` for Debian to something smaller, say, 9001?

(my theory is that this is #2815 or something related)

**Comment by tovine** [comment]
After changing the historySize to 9001 the problem goes away.
In fact, the pain point seems to be at 32652 lines (32651 works fine).

**Comment by zadjii-msft** [comment]
@tovine Yep, that sounds about right. This is an integer overflow bug that's fundamentally the same thing as that other issue, so I'll close it as a dupe. Thanks for the follow-up!

/dup #2815
