### ISSUE TITLE
Command and environment variable completion

### ISSUE THREAD

**Issue by erickulcyk** [microsoft/terminal#3822]
Command Completion detail per KenSy:

For Redstone, regular command line apps should get a similar tab completion experience to what powershell scripts get: tab to get switch options, allowed values for switches, etc.  The ability to get useful help, including examples, for command line apps.

Windows 10 console apps can provide this info through new APIs, help documents via well-known resource IDs, etc. Because we have no control over the vast number of command line apps written by 3rd parties this mechanism can use a database keyed off of exe name / exe version that has all the metadata needed to provide the experience. Further, because there is a whole ecosystem of command line apps, we publish the data format used to describe command line switches, etc., and create an open source project where people can contribute settings for the apps they use.

Environment Variable Completion detail per JeffMill:
e.g. in razzle:
notepad %INIT%\setenv<TAB>
would be great if this autocompleted the same way:
notepad d:\rs1_oc_store_wu\developer\jeffmill\setenv<TAB>
does.

**Comment by erickulcyk** [comment]
Cloned from https://microsoft.visualstudio.com/OS/_workitems/edit/615183 That task was created in 2014, and still hasn't been fixed :(  It someone could give me some guidelines on where to start, I could perhaps try to work on this myself as it is my most desired feature at the moment.

**Comment by remkop** [comment]
@erickulcyk Check out [clink](https://github.com/mridgers/clink), which supports configurable tab completion with simple lua scripts. See [docs](https://github.com/mridgers/clink/blob/298113a61272afa3f646a912c97e2ce34da67597/docs/clink.md#file-locations) and [pre-built completions](https://github.com/vladimir-kotikov/clink-completions) for common tools.

**Comment by zadjii-msft** [comment]
Huh. This looks like a `cmd.exe` feature request. The Console isn't involved in the processing tab completion for commandlines in `cmd.exe`. (that's in `ReadBufFromConsole` in cmd.exe, _I think_).

Since we're not planning on making any changes to `cmd.exe` now or ever, I'm gonna close this one out. Thanks!
