### ISSUE TITLE
Figure out copyWith{,out}Newlines, perhaps rename Keybinding Arg for Copy

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#3824]
# Description of the new feature/enhancement

 the discussion about what it means to strip newlines but not strip whitespace, strip whitespace but not strip newlines, strip all or strip nothing needs to be had in a followup issue.
-Dustin, December 2019

# Proposed technical implementation details (optional)
`trimWhitespace` is weird and ambiguous. Here's some ideas that have been thrown out...
- `copyNewlines`
- `stripNewlines`

Keep in mind how this plays with box selection (holding alt key).

**Comment by DHowett-MSFT** [comment]
We may want to determine how often `copyTextWithoutNewlinesButWithAllTheWhitespace` is used.

**Comment by DHowett-MSFT** [comment]
Kayla and I decided on `singleLine`.
