### ISSUE TITLE
Add support for VT100 Auto Wrap Mode (DECAWM)

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#3826]
# Description of the new feature/enhancement

The [`DECAWM`](https://vt100.net/docs/vt510-rm/DECAWM.html) escape sequence is a DEC private mode which controls whether characters wrap at the end of the line. It corresponds, more or less, with the existing console `ENABLE_WRAP_AT_EOL_OUTPUT` flag.

I'm not sure how widely it's used, but it's supported by most terminal emulators I've tested, and it's required to pass the _Test of screen features_ in Vttest.

# Proposed technical implementation details

Since we already have the `ENABLE_WRAP_AT_EOL_OUTPUT` flag, it should just be a matter of hooking up the mode change escape sequence to toggle that flag. However, there is one slight catch - disabling the `ENABLE_WRAP_AT_EOL_OUTPUT` flag doesn't actually work when `WC_DELAY_EOL_WRAP` is set (which is always the case in VT mode), so that'll need to be fixed first.

**Comment by DHowett-MSFT** [comment]
Yup, this sounds good to me. I'd be interested to see how it lands with `...EOL` as well. :smile:
