### ISSUE TITLE
CJK input method full width mode cause crash

### ISSUE THREAD

**Issue by hoshinomahiro** [microsoft/terminal#3830]
# Environment

```none
Windows build number: 10.0.19033.0
Windows Terminal version: 0.7.3291.0
IME: Microsoft Pinyin Input Method(Simplified Chinese)
```

I use `Microsoft Pinyin Input Method(Simplified Chinese)`, and use  `Shift+Space` to switch between full width and half width.
When I press `Shift+Space` to switch to full width and enter a character in terminal, it will print the character repeatly and does not response any input, after a while, the terminal will crash.

[Screen Shot](https://user-images.githubusercontent.com/9637681/70131125-be43d280-16bc-11ea-8706-9dcd109278f3.png)

**Comment by hoshinomahiro** [comment]
Thanks for your reply. Here is the feedback link: `https://aka.ms/AA6r4pm`

**Comment by DHowett-MSFT** [comment]
We wonder if this is related to #3706.

**Comment by hoshinomahiro** [comment]
yes,  this issue is duplicate
