### ISSUE TITLE
Can scroll up to view previous ouput after printf "\033c"

### ISSUE THREAD

**Issue by liamness** [microsoft/terminal#3831]
# Environment

```none
Windows build number: 19033.1
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
zsh
```

# Steps to reproduce

- I open a new terminal window running Ubuntu 18.04, using zsh as the shell
- I run`repeat 100 echo wat` (not something you would actually want to do, but sufficient to demonstrate the issue)
- I then run `printf "\033c"`

# Expected behavior

A clear terminal, with no previous output that you can scroll back up to.

# Actual behavior

You can scroll upwards to view the output of previous commands. This can make working in the terminal a bit cumbersome when you are running a command with a long output (e.g. a suite of tests), as it then becomes difficult to scroll back through the output without accidentally scrolling into the output of previous commands.

Also reported as microsoft/WSL#4727

**Comment by liamness** [comment]
Seems related to #2715 possibly.

**Comment by DHowett-MSFT** [comment]
Sure is! Thanks! /dup #2715.
