### ISSUE TITLE
consistency with work

### ISSUE THREAD

**Issue by anish137i** [microsoft/terminal#3836]
simple but not visible.

i am using windows 10 for office, windows 10 pro for my personal and other if i set something default setting for my office WSL and other same settings is not work on other no meter same id is used for all

**Comment by DHowett-MSFT** [comment]
I'm sorry? What?

**Comment by zadjii-msft** [comment]
Maybe this has to do with us not roaming settings? Like they want the settings to roam from their work PC to their personal one?
