### ISSUE TITLE
[Feature] Make colortool part of cmd

### ISSUE THREAD

**Issue by p-groarke** [microsoft/terminal#384]
Add a theme tab to the console properties, to allow us to quickly and easily load/change themes. Instead of having to download a seperate tool.

Or.

Ship colortool as part of windows, already in your path.

Thx for the great work as always.

**Comment by miniksa** [comment]
Sorry, we're not going to take additions to CMD and it's not likely that we'll be authorized to add a utility for developer-only scope to the default image. So I'm just going to resolve this. Sorry!
