### ISSUE TITLE
Add keybinding: something like moveCursorLeft, moveCursorRight

### ISSUE THREAD

**Issue by Sopharizer** [microsoft/terminal#3841]
# Description of the new feature/enhancement

Ctrl+F/X/N/P etc. work in the wt by default (like emacs keybindings). However, Ctrl+B didn't work, and there is no property which can set keybindings for cursor moving. 
# Proposed technical implementation details (optional)

I'm not sure this feature can easily be implemented, for example, by modifying AppKeyBindingsSerialization.cpp, but I think there's many users familiar with emacs keybindings (including me).

**Comment by DHowett-MSFT** [comment]
Cursor movement is the responsibility of the shell you are using. If that shell is PowerShell, use the PSReadline options to set up those motions. If you’re using bash, configure your `inputrc`. If you’re using zsh, use `bindkey`. If you’re using cmd, we aren’t going to add those bindings (sorry.)

**Comment by Sopharizer** [comment]
I'm using zsh(wsl).
Executing `bindkey` command, The output was
`......`
`"^B" backward-char`
`......`
and Ctrl+B still didn't work. Ctrl+B did work if I use FluentTerminal as a terminal emulator, so I thought wt could be responsible for that.

**Comment by 9at8** [comment]
@Sopharizer I was able to achieve this by [setting PSReadline edit mode option](https://github.com/PowerShell/PSReadLine/blob/master/docs/Set-PSReadLineOption.md#-editmode) and [saving that to a configuration file](https://devblogs.microsoft.com/scripting/understanding-the-six-powershell-profiles).
