### ISSUE TITLE
unbinding commands has no effect

### ISSUE THREAD

**Issue by maximebl** [microsoft/terminal#3842]
# Environment
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
no

# Steps to reproduce
1) In `profiles.json` set the keybinding for the commands `scrollUp` and `scrollDown` to `"unbound"`
2) get the terminal in a state where there are enough lines to make the vertical scrollbar appear
3) press `ctrl+shift+up` or `ctrl+shift+down`

# Expected behavior
Nothing should happen because the `scrollUp` and `scrollDown` were unbound.

# Actual behavior
The terminal is still scrolling up and down.

**Comment by DHowett-MSFT** [comment]
Can you share the snippet from your settings where you are doing the unbinding?

**Comment by maximebl** [comment]
"$schema": "https://aka.ms/terminal-profiles-schema",
    "globals" : 
    {
        "alwaysShowTabs" : true,
        "copyOnSelect" : false,
        "defaultProfile" : "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "initialCols" : 120,
        "initialRows" : 30,
        "keybindings" : 
        [        
            {
                "command" : "scrollDown",
                "keys" : 
                [
                    "unbound"
                ]
            },
            {
                "command" : "scrollUp",
                "keys" : 
                [
                    "unbound"
                ]
            }
        ],
        "requestedTheme" : "system",
        "showTabsInTitlebar" : true,
        "showTerminalTitleInTitlebar" : true,
        "wordDelimiters" : " ./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}~?\u2502"
    }

**Comment by DHowett-MSFT** [comment]
Ah, so, key bindings bind keys to invoke commands, not the other way around. You will have to add a key binding that specifies `keys=ctrl+shift+up` and `command=unbound` to remove the binding that exists for <kbd>Ctrl+Shift+Up</kbd>

**Comment by maximebl** [comment]
This does stop the scrolling from hapenning, however it seems like it's swallowing the keypress entirely since my text editor running in the terminal is not receiving the key chord
