### ISSUE TITLE
How does LTSC install the terminal?

### ISSUE THREAD

**Issue by Hiddensu** [microsoft/terminal#3843]
???

**Comment by DHowett-MSFT** [comment]
It doesn’t, sorry.

**Comment by zadjii-msft** [comment]
For more context: we've discussed this at length previously why the terminal doesn't work on older versions of Windows. From another discussion:
### https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691
> Sorry. Right now, there's two big blockers to adoption on 1809.
> 
>     * XAML islands was a technology preview and didn't support high-DPI, DPI changes, or accessibility in 1809. We rely on them heavily.
> 
>     * 1903 added support for side-by-side WinRT component activation, something deep in the COM stack that lets us find our DLLs when they're right next to our EXE.
> 
> 
> We just can't go back to 1809.


### https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323
> 
> 
> > the Windows Terminal **REQUIRES** features from the latest Windows release.
> 
> Unfortunately, there's really no workarounds available to us. XAML Islands is the technology we use to host our XAML UI in a Win32 process. Without that, we'd be unable to display anything. Since XAML Islands is only complete as of the latest Windows 10 release, there's nothing we can do about it.
> 
> If you'll want to use the terminal, you'll _need_ to be on the latest Windows 10 version.


### https://github.com/microsoft/terminal/issues/841#issuecomment-492940388

### https://github.com/microsoft/terminal/issues/498#issuecomment-490091740
> 
> 
> There are no plans currently.
> 
> We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.
> 
> Furthermore, our entire build system is MsBuild-based, and I could be wrong, but I don't think our build system will work on linux.


### https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952
### https://github.com/microsoft/terminal/issues/2024#issuecomment-512788360
### https://github.com/microsoft/terminal/issues/2480

**Comment by nonetrix** [comment]
Yeah LSTC is too old and doesn't support stuff needed to run it I guess was hoping I could install it manually rather than from the MS store.

Best bet is to wait for the next version of LTSC when ever that is or use normal Windows 10, you could also look at alacritty I use it on Linux and apparently it's on windows, uses rust and opengl might not be as good but it's something and it's better than cmd.

**Comment by kskeigrshi** [comment]
Windows Terminal successfully installs on Windows 10 Enterprise LTSC 2021 with `Add-AppXPackage`. Yeah it finally got an update.

**Comment by rj-hwang** [comment]
> Windows Terminal successfully installs on Windows 10 Enterprise LTSC 2021 with `Add-AppXPackage`. Yeah it finally got an update.

How?

**Comment by kskeigrshi** [comment]
> > Windows Terminal successfully installs on Windows 10 Enterprise LTSC 2021 with `Add-AppXPackage`. Yeah it finally got an update.
> 
> How?

Please, if you know how to use powershell then you must be able yo install a package. I mean just google it and you’ll get an immediate answer. Why even bother to ask here?

**Comment by averyfreeman** [comment]
> Yeah LSTC is too old and doesn't support stuff needed to run it I guess was hoping I could install it manually rather than from the MS store.
> 
> Best bet is to wait for the next version of LTSC when ever that is or use normal Windows 10, you could also look at alacritty I use it on Linux and apparently it's on windows, uses rust and opengl might not be as good but it's something and it's better than cmd.

I am on new LTSC 2021 install. After installing MS Store (for AppX), install MS App Installer from MS Store (has Winget, etc.). Then can install Terminal via `choco install microsoft-windows-terminal`.  Obvs I had installed Chocolatey (a must get), and I also installed `vcredist-all` before App Installer package from store, but not sure if it was required.

**Comment by K7CTC** [comment]
Windows 10 Enterprise LTSC 21H2 (19044.2604)

Download the C++ Runtime Framework for your architecture.  In my case this was:
Microsoft.VCLibs.x64.14.00.Desktop.appx

Download the Windows 10 Terminal msix bundle from the releases page.  In my case this was:
Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle

Open an Administrator PowerShell window (right click and run as Administrator).

Navigate to your download directory.

Use Add-AppxPackage to install the C++ framework then Terminal.  In my case this was:
Add-AppxPackage .\Microsoft.VCLibs.x64.14.00.Desktop.appx
then
Add-AppxPackage .\Microsoft.WindowsTerminal_Win10_1.16.10261.0_8wekyb3d8bbwe.msixbundle

Done!

Hopefully this helps someone else looking for the same answer.  I'm thrilled to have Terminal up and running on LTSC!

**Comment by notrealdev** [comment]
Thank @K7CTC 
It works for me ☺️

**Comment by VitaliyAT** [comment]
`Windows 10 LTSC 21H2 19044.3324`
it runs but can't be install... strange... a lot

Don't want to install MS Store for it... not for this LTSC was installed... Manually copy it in Program Files, create lnk and put it in Start menu. After that, pin it to quick access. Done. It was impossibly done such installer, yea?

**Comment by realsarius** [comment]
The Windows 10 PreinstallKit in Releases has Windows Terminal and its dependencies for multiple architectures. Just download that, install the dependencies and the terminal and enjoy

**Comment by notrealdev** [comment]
@VitaliyAT can you try it?
![Imgur](https://i.imgur.com/DqEO5B2.png)

**Comment by K7CTC** [comment]
@realsarius is correct.

To update my original post:

I'm running Windows 10 Enterprise LTSC 21H2 (19044.3448)

Download the Windows Terminal Windows 10 Preinstall Kit from the releases page. In my case this was:
Microsoft.WindowsTerminal_1.17.11461.0_8wekyb3d8bbwe.msixbundle_Windows10_PreinstallKit.zip

Extract to a location of your preference.

Open an Administrator PowerShell window (right click and run as Administrator).

Navigate to the directory you extracted to.

Use Add-AppxPackage to install the prerequisites. In my case this was:
Add-AppxPackage .\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe.appx
then
Add-AppxPackage .\Microsoft.UI.Xaml.2.7_7.2208.15002.0_x64__8wekyb3d8bbwe.appx

Then use Add-AppxPackage to install the Windows Terminal msixbundle file.  In my case this was:
Add-AppxPackage .\1ff951bd438b4b28b40cb1599e7c9f72.msixbundle

Done!

Hopefully this helps someone else looking for the same answer. I'm happy to have the latest release of Terminal up and running on LTSC!
