### ISSUE TITLE
Add a option for make tabTitle can auto override when title is too loooooooooooon....

### ISSUE THREAD

**Issue by flying1020** [microsoft/terminal#3844]
The option 'suppressApplicationTitle' is not smart eniough, either show ${tabTitle} or ${name} is a little arbitrary. If possiable that add a option for make tableTitle can auto override just when it's too long?

Sorry for I am not good at express in English.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by owennewo** [comment]
@flying1020 - you've made a reasonable suggestions, however is your underlying issue the fact that you can only see approximately 4 tabs at a time with the rest of the tabs scrolled off screen?  

Personally I'd prefer to see the tabs behave more like a web browser tabs.  i.e. if I have 20 tabs open then they'd shrink to a smaller width but most/all tabs would be displayed.  Title text would be truncated and a hover over the tab would reveal the full title as a tooltip.  Perhaps there would be a setting for minimum tab width but I think most people would be happy if the min width is fixed and displays the icon + about 10 characters.

**Comment by zadjii-msft** [comment]
Yea I think the more complete solution to this problem would come from #597, enabling changing the min/max width of tabs and providing other tab sizing settings. I'll direct further discussion to that thread. 
/dup #597
Thanks!

**Comment by flying1020** [comment]
Thinks for all you replies! Though the issue is not get solved immediately, I am happy for your sincere replies. “middle mouse button roller” is good alternative.
