### ISSUE TITLE
Terminal crashes when SSH tab connection closes

### ISSUE THREAD

**Issue by DevJonny** [microsoft/terminal#3845]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
SSH
```

# Steps to reproduce

Configure a tab to open directly into an SSH session e.g. ssh 123.456.789.012. Open the tab, and wait for the session to expire due to lack of activity. 

# Expected behavior

SSH tab to close, if it's the last tab then Windows Terminal to close as well.

# Actual behavior

Windows Terminal crashes, and all tabs are lost.

**Comment by DHowett-MSFT** [comment]
This looks like another instance of /dup #3801
