### ISSUE TITLE
support * title when console change!

### ISSUE THREAD

**Issue by jliu666** [microsoft/terminal#3846]
support * title when console change!
![image](https://user-images.githubusercontent.com/14869749/70234702-32a17300-179c-11ea-9b4d-eac39c5fab66.png)

**Comment by zadjii-msft** [comment]
Generally, we do support changing the title. Could you be more specific here? What commands are you running that you'd expect to change the title? What does your `profiles.json` look like?

IIRC there were some bugs with the OpenSSH client around changing the title, but I would have thought they were resolved by now...

**Comment by xa0082249956** [comment]
Do you mean #1620 ?

**Comment by jliu666** [comment]
yes,

**Comment by zadjii-msft** [comment]
Fantastic, thanks for confirming!

/dup #1620
