### ISSUE TITLE
snapping the window fast shuts down terminal

### ISSUE THREAD

**Issue by thomasnguw** [microsoft/terminal#3853]
Open a terminal, and press windows key + left arrow key a bunch in succession, terminal will close. I usually need to snap across two monitors

**Comment by DHowett-MSFT** [comment]
Please fill out the bug template. What version are you using? What version of Windows? What other software is in use? That info is _really helpful_!

**Comment by thomasnguw** [comment]
Windows Terminal (Preview)
Version: 0.7.3291.0


windows version 1903 os build 18990.1
intellij, wsl ubuntu 18.04, sublime, onenote, outlook, chrome

**Comment by DHowett-MSFT** [comment]
Okay, so, we fixed this in 0.7.3381.0 (which has been available for a week.)
