### ISSUE TITLE
Tab disappears when resizing the window

### ISSUE THREAD

**Issue by jenkijo** [microsoft/terminal#3862]
# Environment

```none
Windows build number: 10.0.19033.0
Windows Terminal version (if applicable): 0.7.3382.0
```

# Steps to reproduce

Resize window

Normal:
![normal](https://i.imgur.com/umt6eKS.png)

After resized
![after](https://i.imgur.com/nXHYR5i.png)
![after2](https://i.imgur.com/8UbLqCz.png)

# Expected behavior

Tab still show up

# Actual behavior

Tab disappears

**Comment by mkitzan** [comment]
Looking like a dupe #3300

**Comment by phongtruongg** [comment]
> Looking like a dupe #3300

I remember it is fixed before

**Comment by mkitzan** [comment]
Maybe something similar to it was fixed, but this has been a nagging issue for as long as I've been using WT.
