### ISSUE TITLE
Feature Request: Preserve scroll position while not "at bottom"

### ISSUE THREAD

**Issue by geordiemhall** [microsoft/terminal#3863]
# Description of the new feature/enhancement

I tried searching for this but couldn't find any dupes, but please let me know if this is already possible!

It'd be great to (at least have an option to) preserve the terminal scroll position while you aren't scrolled to the bottom.

Eg. If I'm doing a build or something, which is logging out info every second, but then want to scroll up and take a look at an error message I noticed higher up, my view shouldn't be affected by new lines being printed to the terminal. Whereas currently the view jerks around as new stuff is appended to it, making it impossible to actually read any history.

If I then scroll back down "as far as you can go", that should then be a signal to "stick" the scroll with the latest output again.

Could also be nice to have a small button appear somewhere if new lines have been printed while you were scrolled up, which you could click to jump back to the "stuck to the bottom" mode.

Thanks!

**Comment by carlos-zamora** [comment]
We don't have a duplicate bug for this, but it'd definitely on our radar. :)

I'll be sure to add it to #2529, since there was a similar request in that PR.

**Comment by PhMajerus** [comment]
This seems like something that would finally put the Scroll Lock key to good use, it should be a toggle available through a tab right-click menu, as well as the Scroll Lock key for faster keyboard use.

Related: Tabs could show some icon when new content has been added to their buffer while they were not visible, like the audio notification icon in Edge. This would make it easy to see some update happened while working in another tab.
