### ISSUE TITLE
Question: What is the end goal of this project?

### ISSUE THREAD

**Issue by JamesLear92** [microsoft/terminal#3865]
Hi, I love what you're doing; but what is the end goal? Will Cmd, PowerShell, etc open in this terminal by default once properly released?

Is it possible to set the default console for powershell to this terminal? At the moment I can't see a way to launch powershell (with parameters, for instance -File) in the new terminal. This really limits the use for me at the moment and I can't tell from the documentation/roadmap if this is possible, and if it's even the end goal.

But yeah, it's looking really nice.

**Comment by zadjii-msft** [comment]
I think "end goal" is maybe too broad a question to answer here on Github. I'm not totally sure we know the answer to that question - maybe it's just "build the best terminal on the planet".

The more specific part of your question is related to the "default terminal" experience on Windows. 
In short: Yes, we want the Windows Terminal to be able to act as the default terminal on Windows, so launching any commandline application will automatically appear in a Windows Terminal instance.

In long: see #492
