### ISSUE TITLE
adding admin consoles to the console list

### ISSUE THREAD

**Issue by JustBeta** [microsoft/terminal#3867]
Would it be possible to integrate a console with the 'admin' token so that it can be associated with the other tabs.

Here is the profile I use, they are functional but not integrate.
        {
            "acrylicOpacity" : 0.75,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NoLogo -Command Start-Process \"%SystemRoot%\\system32\\cmd.exe\" -Verb runAs",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{f406ac09-24c5-4f23-ab3b-e1303ef722e6}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{f406ac09-24c5-4f23-ab3b-e1303ef722e6}.png",
            "name" : "cmd (admin)",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
        },
        {
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NoLogo -Command Start-Process \"powershell.exe\" -Verb runAs",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{05bba87c-60ce-485b-b510-766ea0c24805}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Windows PowerShell (Admin)",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : false
        },

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is something that's been discussed _at length_ in #632 and #1032. I'd refer to those threads for more details.

/dup #632 #1032
