### ISSUE TITLE
Add additional characters to Consolas Font

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#387]
Many OSS projects use various Unicode symbols as dingbats in CLI, and if Consolas can support them it may be helpful for OSS developers.

The list below is an **incomplete** list that modern OSS programs use.

NOTE: Some of these characters are punctuations in non-Latin scripts. It is NOT recommended to include them.

|"Figures" Name|Character|Unicode|CP437?|Notes|
|---|---|---|---|---|
|`tick`|`✔`|`U+2714`| | |
|`cross`|`✖`|`U+2716`| | |
|`star`|`★`|`U+2605`| | |
|`square`|`▇`|`U+2587`| | LOWER SEVEN EIGHTHS BLOCK, close to U+2588 |
|`squareSmall`|`◻`|`U+25FB`| | |
|`squareSmallFilled`|`◼`|`U+25FC`| | |
|`play`|`▶`|`U+25B6`| | |
|`circle`|`◯`|`U+25EF`| | |
|`circleFilled`|`◉`|`U+25C9`| | |
|`circleDotted`|`◌`|`U+25CC`| | |
|`circleDouble`|`◎`|`U+25CE`| | |
|`circleCircle`|`ⓞ`|`U+24DE`| | |
|`circleCross`|`ⓧ`|`U+24E7`| | |
|`circlePipe`|`Ⓘ`|`U+24BE`| | |
|`circleQuestionMark`|`?⃝`|`U+003F U+20DD`| | Combination of U+003F and U+20DD |
|`bullet`|`●`|`U+25CF`| | |
|`dot`|`․`|`U+2024`| | |
|`line`|`─`|`U+2500`|✔||
|`ellipsis`|`…`|`U+2026`| | |
|`pointer`|`❯`|`U+276F`| | May also include its mirror |
|`pointerSmall`|`›`|`U+203A`| | May also include its mirror |
|`info`|`ℹ`|`U+2139`| | |
|`warning`|`⚠`|`U+26A0`| | |
|`hamburger`|`☰`|`U+2630`| | |
|`smiley`|`㋡`|`U+32E1`| | Enclosed form of TSU (ツ). **Not recommended** |
|`mustache`|`෴`|`U+0DF4`| | Sinhala punctuation _Kunddaliya_. **Not recommended** |
|`heart`|`♥`|`U+2665`|✔||
|`arrowUp`|`↑`|`U+2191`|✔||
|`arrowDown`|`↓`|`U+2193`|✔||
|`arrowLeft`|`←`|`U+2190`|✔||
|`arrowRight`|`→`|`U+2192`|✔||
|`radioOn`|`◉`|`U+25C9`| | |
|`radioOff`|`◯`|`U+25EF`| | |
|`checkboxOn`|`☒`|`U+2612`| | |
|`checkboxOff`|`☐`|`U+2610`| | |
|`oneHalf`|`½`|`U+00BD`|✔||
|`oneThird`|`⅓`|`U+2153`| | |
|`oneQuarter`|`¼`|`U+00BC`|✔||
|`oneFifth`|`⅕`|`U+2155`| | |
|`oneSixth`|`⅙`|`U+2159`| | |
|`oneSeventh`|`⅐`|`U+2150`| | |
|`oneEighth`|`⅛`|`U+215B`| | |
|`oneNinth`|`⅑`|`U+2151`| | |
|`oneTenth`|`⅒`|`U+2152`| | |
|`twoThirds`|`⅔`|`U+2154`| | |
|`twoFifths`|`⅖`|`U+2156`| | |
|`threeQuarters`|`¾`|`U+00BE`| | |
|`threeFifths`|`⅗`|`U+2157`| | |
|`threeEighths`|`⅜`|`U+215C`| | |
|`fourFifths`|`⅘`|`U+2158`| | |
|`fiveSixths`|`⅚`|`U+215A`| | |
|`fiveEighths`|`⅝`|`U+215D`| | |
|`sevenEighths`|`⅞`|`U+215E`| | |

**Comment by be5invis** [comment]
cc. @sindresorhus

**Comment by sindresorhus** [comment]
It shouldn't just include symbols from my [`figures`](https://github.com/sindresorhus/figures) package, it should include **all** Unicode characters.

**Comment by be5invis** [comment]
@sindresorhus 
There are 87,887 ideographs currently in Unicode. You need all of them too?
We need a boundary, and characters beyond that boundary should be handled by font fallback / font linking / whatever.

**Comment by sindresorhus** [comment]
> There are 87,887 ideographs currently in Unicode. You need all of them too?

I don't need them all, but it shouldn't be limited to an arbitrarily chosen subset.

> should be handled by font fallback / font linking / whatever.

This is more important IMHO. As a developer, I just want all Unicode characters to be available in some form. I don't care which font it is.

**Comment by be5invis** [comment]
@sindresorhus 
I added a note that it is not a complete list.
Font fallback is not a simple task. Trust me, I maintain one, and it used >2000 lines of C++ to cover all the edge cases.

**Comment by zadjii-msft** [comment]
I don't believe our team owns Consolas, nor am I really sure any team owns Consolas. I do know that our team certainly doesn't have the resources to make changes to a font ourselves, but I can sic @bitcrazed on trying to find a person to make updates to Consolas.

This is now the "Make Improvements to Consolas" thread

**Comment by be5invis** [comment]
May also include full block elements support (U+2580--U+259F)

**Comment by E3V3A** [comment]
Just a few notes about the *box* characters: 

See:
*   https://github.com/PowerShell/PowerShell/issues/8409
*   https://en.wikipedia.org/wiki/Code_page_437
*   https://en.wikipedia.org/wiki/Box-drawing_character
*   https://en.wikipedia.org/wiki/Block_Elements

My experiments have show that:

*   2585,               # Look best but is not part of cp437 and thus font dependent & not widely available
*   2580, 25A0, 2588    # IBM-437

```python
def print_legend():
    #cc = u'\u2585' # Unicode Character for a "5/8th box"           # (U+2585) is not part of IBM-437
    #cc = u'\u2588' # Unicode Character for a "full box"            # (U+2588) is part of IBM-437
    #cc = u'\u25A0' # Unicode Character for a "black square"        # (U+25A0) is part of IBM-437
    cc = u'\u2580'  # Unicode Character for a "Upper half block"    # (U+2580) is part of IBM-437
```

The other "boxes" was not even considered, as they either didn't render anything like what one would expect from a "box", or it was placed too high/low within the character frame. 

Running the following in a PWSH using `Deja Vu Sans Mono`, yield:

![pwsh_2019-03-28_10-12-36](https://user-images.githubusercontent.com/194392/55141145-a7161380-5131-11e9-94f3-3540a09f3be6.png)

**Comment by miniksa** [comment]
This will probably not be necessary if Terminal is used or if DX is turned on in conhost since it will have font fallback.

**Comment by eryksun** [comment]
@miniksa, IIRC, conhost sort of works with manual font linking configured for Consolas in "HKLM\Software\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink". But last I checked the rendering seems to gets widths wrong, and the result is erratic. I suppose it's because it's based on the selected font instead of the linked font. Is there any way to improve the result with font linking?

**Comment by miniksa** [comment]
A major point of moving to the Terminal and to the DX renderer is to not fix/update the GDI one anymore. So while it is always *possible* to improve it, it would be out of scope for what we're trying to achieve.

**Comment by eryksun** [comment]
To clarify, I was wondering whether there's a way to tweak the configuration to get a better result, particularly in older Windows 7 systems. I know there's no chance to see font rendering improvements in the conhost window, at least not for a long while to come. You mentioned in another post that you might switch conhost to the DX renderer, but I won't get my hopes up for that.

**Comment by miniksa** [comment]
I probably will change conhost to the DX one once it stabilizes and I feel like I have the capacity to accept bugs on it.

I also have no advice for Windows 7. It's dead as of January 2020. It's time to accept that and move on.

**Comment by PiotrGrochowski** [comment]
The latest version of Consolas is available at https://typedesign.netlify.com/consolas.html

Warning: Consolas is not suitable for terminal/commandprompt environments! Use a bitmap font instead for that purpose.

**Comment by musm** [comment]
Any chance we could also add ∅ ?

**Comment by DHowett** [comment]
To Consolas? No.

**Comment by mdtauk** [comment]
Cascadia Code/Mono is the font being targeted going forward, so you should direct your needs to that Repo

**Comment by flawrist** [comment]
> @miniksa
> I also have no advice for Windows 7. It's dead as of January 2020. It's time to accept that and move on.

Abandoned by the developer ≠ dead. I have a garage full of tools inherited from my father that have long since expired warranty, but they work better than what's out now. Fortunately, Windows 7 support was declared financially unprofitable at a time when this OS was polished to a high shine, so it will serve people for years to come. And there's nowhere to move on, because Microsoft's subsequent OSes are an embarrassment: e.g. you need a video card with DirectX 12 to run the damn calculator. Compare this twisted understanding of progress with the true revolution that NTFS and 64-bit have brought.

> @mdtauk 
> Cascadia Code/Mono is the font being targeted going forward…

[Meh](http://xahlee.info/js/cascadia_vs_consolas.html). Consolas is here to stay.

> @be5invis
> Add additional characters to Consolas Font

Check [DMCA Sans Serif](https://typedesign.replit.app/dmcasansserif.html) and [ConEmu](https://conemu.github.io/en/Screenshots.html).
