### ISSUE TITLE
Shortcut keys to fullscreen window cause unexpected behavior on second monitor

### ISSUE THREAD

**Issue by DukeOfEtiquette** [microsoft/terminal#3871]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19033.0 Microsoft Windows NT 10.0.19033.0


Windows Terminal version (if applicable):
0.7.3382.0


Any other software?
Nope.
```

# Steps to reproduce

1. Launch terminal
2. Move terminal window to second monitor/screen
3. Press with F11 or alt+enter
4. Gives an unworkable black screen in fullscreen

# Expected behavior

Full screen with normal styling and interaction

# Actual behavior

Black screen that seems to be non-interactive.
![win_terminal_fullscreen](https://user-images.githubusercontent.com/8975234/70343839-1e498e80-180d-11ea-85cf-78243b3d1ba9.gif)

I fullscreen twice on each monitor, using the F11 and alt+enter once on each monitor.

# Note

As well, the Terminal window ALWAYS launches from monitor 1, and does not remember it was closed in monitor 2. Since I always run my terminal on monitor 2, this is a slight annoyance.

**Comment by gerhardamegg** [comment]
Same on `Microsoft Windows [Version 10.0.18363.476]`: Works as expected on primary screen, is buggy on secondary.

**Comment by zadjii-msft** [comment]
Thanks for the report and the gif to demonstrate it! Looks to me like this is a /dup of #3710, so I'll direct discussion to that thread. Thanks!
