### ISSUE TITLE
More Cosmetic Adjustment Options

### ISSUE THREAD

**Issue by LeeThompson** [microsoft/terminal#3873]
I'm using Terminal more and more but I've noticed something with it as I go between my tabs, namely the glass effect when Terminal is in focus can look (if there are bright windows behind it) like the effect when Windows believes an application is not responding.

I'd like to propose the following optional tweaks:

- Ability to set a static background (color or image) for active/inactive tabs
- Ability to enable/disable glass effect for active/inactive tabs (or globally)
- Ability to set glass effect opacity level for active/inactive tabs (or globally)

**Comment by zadjii-msft** [comment]
I'm not going to really touch the "acrylic when the window is unfocused subject here" (it's been discussed at length already).

I will however say that we already have a plan that's almost exactly like what you're looking for. I'll refer you to /dup #3062

Thanks!
