### ISSUE TITLE
Hide scroll bar

### ISSUE THREAD

**Issue by gohar94** [microsoft/terminal#3878]
# Description of the new feature/enhancement

The scroll bar is mostly unnecessary for me when working and slightly distracts from the complete full screen experience. Terminal should obey the "Automatically hide scroll bars in Windows" setting from the display control panel and hide the scroll bar at least when not being used, if not always.

# Proposed technical implementation details (optional)

I would appreciate the ability to completely hide the scroll bar and just be able to scroll using mouse scroll wheel/touch pad.

<img width="117" alt="scroll_bar" src="https://user-images.githubusercontent.com/6470801/70372089-86d94f80-188f-11ea-8b85-f566b06ef086.PNG">

**Comment by DHowett-MSFT** [comment]
You should look into `scrollbarState` in the [settings schema](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md). Does `hidden` seem like what you’re looking for?

**Comment by dnandrade** [comment]
Doesn't work for me. Even after doing:
`"scrollbarState": "hidden"`
the config file ignores it and maintains the visible state

I've tried setting up globally and locally (on my profile). Same result.

**Comment by DHowett-MSFT** [comment]
Even after relaunching? It’s a profile specific setting but in 0.9 it doesn’t hot-reload.

**Comment by dnandrade** [comment]
The behavior was the following: the original pane would have the scrollbar and the consequent panes, after spiting, would behave as expected.

Closing the original pane before the others and relaunching the terminal fixed for me. Now even the original one behaves as expected.

Weird behavior but I think it's not very common since apparently I was the only one having it (judging by Google results).

Thanks for taking the time to answer.

**Comment by sweihub** [comment]
Any solution yet? I want to remove the scrollbar, the setting dose not work at all  
`"scrollbarState": "hidden"`

Windows Terminal Preview
version: 1.5.3242.0

![image](https://user-images.githubusercontent.com/5334841/100322455-45413780-2fff-11eb-92bf-4876a40369d3.png)

**Comment by DHowett** [comment]
@sweihub where did you put that setting?

**Comment by simonla** [comment]
put "scrollbarState": "hidden" in profiles-defaults block, it works for me
```json
{
    "profiles":
    {
        "defaults":
        {
            "scrollbarState": "hidden"
        }
    }
}
````

**Comment by zboyles** [comment]
😳 **_Acknowledging rookie move_**: If you're like me and searched through the registry and powershell cmdlets and custom windows terminal themes ("scrollbarState": "visible") so it wouldn't auto-collapse.... it's right in:
`Windows Settings -> Ease of Access -> Vision (Tab Group) -> Display (Tab) -> Automatically hide scroll bars in Windows = Set to false/Off`

**Note**:
If there are some theme options I'm missing to configure the Windows Terminal scroll bar's collapsed width size, expanded width size, set to preview (like VS Code), please let me know.

**Comment by sweihub** [comment]
> put "scrollbarState": "hidden" in this block, it works for me:
> 
> ```json
> {
>     "profiles":
>     {
>         "defaults":
>         {
>             "scrollbarState": "hidden"
>         }
>     }
> }
> ```

@simonla @DHowett 
Now it works, thank you guys!

**Comment by vserdyuk** [comment]
Personally I dislike the decision of obeying "Automatically hide scroll bars in Windows" setting from the display control panel. When turned on, Settings UWP app looks much clunkier. Why not just add separate setting for the app - always, auto-hide and never? Why make people go search through "Ease of access" menu setting?

**Comment by zadjii-msft** [comment]
@vserdyuk Uh, there are already Terminal-specific settings for this?

https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#scrollbar-visibility

`always` was added in #14047 which is shipping in 1.17 (https://github.com/MicrosoftDocs/terminal/pull/593 may have been pre-emptively merged to the published docs...)

**Comment by vserdyuk** [comment]
@zadjii-msft Thank you for pointing to this, glad to know that there is a fix and it will soon be released!

**Comment by rfc2119** [comment]
Hello all,

Thank you for working on the scrollbarState in the [the schema](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md). I still have a problem that I would like to confirm with everyone. There is still some space horizontally **in full screen mode**. Here is an example showing tmux bar:
![image](https://user-images.githubusercontent.com/4954847/228237311-cb61c5a0-8f0a-40be-a5bf-e62a69f5a797.png)

While the terminal window is not in full screen mode, there is no space noticed:
![image](https://user-images.githubusercontent.com/4954847/228237133-29cc0d9c-04f9-48b9-8e4e-4e2833bcb754.png)

Does anyone experience this ? Sorry for jumping into this issue

**Comment by zadjii-msft** [comment]
@rfc2119 You mean that tiny black space at the bottom of the window? If that's what you're talking about, the reason is basically this: when the window is _windowed_, it can "snap" to the size of a character, so that there's no leftover space in the window. The window is exactly a multiple of the character size (+ the titlebar, etc). However, if the window is maximized or fullscreen, then the window can't be snapped exactly to the character grid. It's instead snapped exactly to the size of the display. Hence the tiny bit of padding - something has to fill those last few pixels.

**Comment by rfc2119** [comment]
@zadjii-msft Understood. Thank you for the explanation and your quick response. I can live with that.

**Comment by groutoutlook** [comment]
hi,
I have set [this on my profiles](https://github.com/microsoft/terminal/issues/3878#issuecomment-745020477), but it is only applicable on the first pane instance, scroll bar is still visible in the second panes I spawn in tab.
![Image](https://github.com/user-attachments/assets/a8da9cb5-bc35-4323-abfb-44364f787424)
Should I make a new issue for this?
