### ISSUE TITLE
Feature Request: Search or run a command in Dropdown menu

### ISSUE THREAD

**Issue by xa0082249956** [microsoft/terminal#3879]
# Description of the new feature/enhancement

1. User pressed <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd>, then focus moved to the Text Box automatically.
      <img width="900" alt="Windows Terminal Default" src="https://user-images.githubusercontent.com/9026813/70376954-7be2f580-1949-11ea-977b-36a2b2768ac8.png">

3.  User typed `arc`.
      <img width="899" alt="Typing _arc_" src="https://user-images.githubusercontent.com/9026813/70376958-83a29a00-1949-11ea-91bf-171fc9776cf0.png">

4. User typed `ipy` instead.
      <img width="899" alt="Typing _ipy_" src="https://user-images.githubusercontent.com/9026813/70376909-2575b700-1949-11ea-894f-d87133f129fd.png">

**Comment by zadjii-msft** [comment]
Hey thanks for the great mockups! We've actually got a pretty similar feature in progress already - a full "command palette" like VsCode or Sublime, that'll enable searching for commands like this. That work is being tracked in #2046, so I'll direct discussion there. 

/dup #2046

Thanks!
