### ISSUE TITLE
White border aroung terminal

### ISSUE THREAD

**Issue by serd2011** [microsoft/terminal#3880]
# Environment

```none
Windows build number: [Version 10.0.18363.476]
Windows Terminal version (if applicable): 0.7.1912.4002

Any other software?
```

# Steps to reproduce

Turn off "Show accent color in title bars and windows borders" at the windows settings, run terminal and focus on it.
# Expected behavior

if "show accent color in title bars and windows borders" is turned off the border at focus should be the same as without focus. (like in explorer)
![image](https://user-images.githubusercontent.com/45919738/70381171-e189ae80-1956-11ea-8b2d-71822a3fc7d9.png)

# Actual behavior
Displays white border around terminal when it is in focus even if "show accent color in title bars and windows borders" is turned off
![image](https://user-images.githubusercontent.com/45919738/70381095-a89d0a00-1955-11ea-9740-28d65ec4f478.png)
![image](https://user-images.githubusercontent.com/45919738/70381099-bbafda00-1955-11ea-925c-78161433ffa9.png)

**Comment by DHowett-MSFT** [comment]
There is a pinned issue tracking this.
