### ISSUE TITLE
Windows terminal unbound keys are not being recorded by applications 

### ISSUE THREAD

**Issue by maximebl** [microsoft/terminal#3881]
# Environment
Win32NT 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```none
Any other software?
```
Windows Terminal version `0.7.3291.0`
Vim version `8.1.2102` (Windows vim, not WSL)

# Steps to reproduce
Unbind a key chord the following way:

```
    "keybindings" : 
    [        
        {
            "command" : "none",
            "keys" : 
            [
                "ctrl+shift+up"
            ]
        }
    ]
```

# Expected behavior
The key chord should now be useable by applications running inside the Windows terminal. For example Vim or Emacs.

# Actual behavior
The applications do not receive the key chord at all.

**Comment by DHowett-MSFT** [comment]
Can't reproduce this:

![image](https://user-images.githubusercontent.com/14316954/70382390-33f3ac80-1910-11ea-8e32-a0d707bd6a00.png)

`^[[1;6A` is the encoding for <kbd>Ctrl+Shift+Up</kbd>.

**Comment by DHowett-MSFT** [comment]
(also: you said "no other software", but.. you didn't include your Terminal version, emacs verison, vim version, WSL distribution, whether you're using Windows vim/emacs or WSL vim/emacs, etc. Please fill out the template: it helps us help you, and we _will_ close bugs that do not have enough information in them.)

**Comment by maximebl** [comment]
I updated my original report with the missing information. Sorry about that! I didn't include it in my last report without a fuss so I figured it wasn't necessary.
When I try what you do in the screenshot you posted, I get no input at all. Same for inside vim. In vim you can type `:` and then do `ctrl+k` and then a key chord, it will tell you what key you pressed. When I try that in the Windows terminal I get nothing at all back, vim doesn't even know I pressed a key at all it seems.

**Comment by maximebl** [comment]
I updated my original report with the missing information. Sorry about that! I didn't include it in my last report without a fuss so I figured it wasn't necessary but it's pretty clear it matters a lot!

In vim you can type `:` and then do `ctrl+k` and then a key chord and it will tell you what key you pressed. When I try that in the Windows terminal under windows I get nothing at all back, vim doesn't even know I pressed a key at all it seems.

When I try the same thing while running vim under WSL, the command correctly reports back that I pressed ctrl+shift+up.

**Comment by DHowett-MSFT** [comment]
Thanks for filling out the template! This is interesting. It might be #2397, but if it’s not it’s a similar codepath. Windows Vim receives keyboard events in a different way than WSL Vim.

**Comment by DHowett-MSFT** [comment]
Until we learn otherwise, this is a /dup of #2397. Thanks!
