### ISSUE TITLE
Issues while running PWSH with Azure Cloud Shell

### ISSUE THREAD

**Issue by Nickperf** [microsoft/terminal#3882]
Console Screen doesn't clean or clear.. anytime you use PWSH on Azure Cloud Shell. AZ CLI works fine.

![Annotation 2019-12-07 193928](https://user-images.githubusercontent.com/13839283/70382391-59d97b00-1929-11ea-8bc7-54541c1f3402.jpg)

**Comment by DHowett-MSFT** [comment]
Also, please fill out the bug template. Your version number, at the very least, would have been helpful. :smile:
