### ISSUE TITLE
Feature request: Close on multiple tabs confirmation dialog being optional.

### ISSUE THREAD

**Issue by jovibor** [microsoft/terminal#3883]
When closing terminal with multiple tabs, it's always a confirmation dialog shows up, forcing you to confirm closing. It's so annoying.

Please make it optional, through profile settings.
Thank you.

**Comment by zadjii-msft** [comment]
Huh I could have sworn I filed this issue myself, but I can't seem to find it on the backlog. Congratulations! _this is now the thread_.

I totally agree that this needs to be a setting, it's been driving me mad over here too 😄

**Comment by rstat1** [comment]
Is anyone working on this? I'd like to take a stab at implementing it if not.

**Comment by DHowett-MSFT** [comment]
@rstat1 feel free!
