### ISSUE TITLE
Missing ctrl+a (select all) from shortcut

### ISSUE THREAD

**Issue by csabattier** [microsoft/terminal#3887]
I don't see shortcut definition in terminal/src/cascadia/TerminalApp/ShortcutActionDispatch.cpp but function exist in terminal/src/host/selection.cpp. I didnt find where this function is called and how we can add it to the shortcut.

**Comment by DHowett-MSFT** [comment]
`src/host/selection.cpp` is a component in conhost, the Windows Console Host.

You're probably looking for /dup #3723

**Comment by DHowett-MSFT** [comment]
Sorry, I meant /dup #1469.
