### ISSUE TITLE
Scroll with Touchpad 

### ISSUE THREAD

**Issue by massgh** [microsoft/terminal#3888]
# TouchPad Scrolling in Terminal
You have keybinding **Ctrl+Shift+Up/Down** for scrolling up/down through terminal. What if we can scroll using TouchPad like we do in other applications. How to bind a swipe gesture of TouchPad to scroll through terminal?

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
You're supposed to be able to. You are hitting a /dupe of #979.
