### ISSUE TITLE
Way to sync Profiles

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/terminal#3893]
# Description of the new feature/enhancement
Ability to configure profile sync via some web process

# Proposed technical implementation details (optional)
A lot of folks love sharing the profiles they have and there should be a way to store them/sync them with the cloud. Maybe having a process to save your profile.json in a gist or repo that can ve easily cloned. I am already doing this, but it would be great to have this as part of the tool

**Comment by DHowett-MSFT** [comment]
Since we (as Microsoft) have a bunch of different syncing technologies, it'll probably be better to consider this as a /dup of #2933 and let you store `profiles.json` in a place that you can manage.
