### ISSUE TITLE
Use SSH2 instead of telnetpp

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#3894]
# Description of the new feature/enhancement
Instead of using insecure telnet, why not use ssh? Even devs have to consider security. https://github.com/mscdex/ssh2 seems like a suitable replacement to telnetpp. Granted it's in TS/JS instead of C++ but we already have some JS for windbg so precedent set. 

# A clear and concise description of what the problem is that the new feature would solve. 
Describe why and how a user would use this new functionality (if applicable).

Removes a security vulnerability. 

# Proposed technical implementation details (optional)

# A clear and concise description of what you want to happen.

Have a secure alternative to telnet.

**Comment by zadjii-msft** [comment]
Hey thanks for your concern! The telnet connection added in #3858 isn't really supposed to be a public-facing tool. In fact, it's something that we've only really added for internal testing. We _know_ telnet's not particularly secure, but we have no intention of the public ever using it 😉

**Comment by DHowett-MSFT** [comment]
Additionally: the existence of a telnet _client_ is not in itself a security issue.
