### ISSUE TITLE
Copy & Paste problem with Ubuntu Linux

### ISSUE THREAD

**Issue by hirschnase** [microsoft/terminal#3898]
When I copy a text from an Ubuntu Linux terminal window (for example from a logfile output) and paste it into a text editor in Windows (Sublime Text 3), the formatting of the text is broken. There are a lot of spaces between the lines of text that need to be manually removed.

**Comment by DHowett-MSFT** [comment]
Can you tell us what version you’re using? We fixed some stuff here recently, so it would be great if you could fill out the bug report template to give us a bit more info.

**Comment by hirschnase** [comment]
> Can you tell us what version you’re using? We fixed some stuff here recently, so it would be great if you could fill out the bug report template to give us a bit more info.

I am using the latest version from the Store: 0.7.3291.0

Hope this helps. Please let me know if you need more information.

**Comment by DHowett-MSFT** [comment]
Thanks! That’s not the latest version, actually, 0.7.3382.0 is. 3382 contains a fix for this issue.
