### ISSUE TITLE
Feature Request: Tab title max length/truncation

### ISSUE THREAD

**Issue by jonknowles** [microsoft/terminal#3899]
Because I use posh-git to append the current git branch name to my terminal prompt, the titles of the tabs in Windows terminal can become very long, appearing in the format `<directory><git branch> ~ <terminal program name>`. Could the tab names be restricted to a fixed number of characters and some kind of truncation behavior (i.e. ellipsis) be applied? 

What I would prefer is if a title that would currently show as something like this:

`~\workspace\myDirName [my-current-git-branch-name] ~ PowerShell 6.0.0 64-bit (21244)`

Could be truncated to some fixed character length, e.g. 50 and an ellipsis appended:

`~workspacemyDirName [my-current-git-branch-name] ~...`

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We're actually already tracking a number of requests related to the sizing of tabs in #597, which also has a PR in progress over in #3876. I'd recommend taking a look at those for more discussion.

/dup #597
