### ISSUE TITLE
Pressing CTRL+Tab does not send full CTRL+Tab chord to the application

### ISSUE THREAD

**Issue by Hoffs** [microsoft/terminal#3902]
# Environment

```none
Windows build number: 10.0.18362.476
Windows Terminal version (if applicable): 0.7.3382.0

WSL Distro: Debian 10 Buster (4.4.0-18362-Microsoft)
Neovim: NVIM v0.3.4
```

# Steps to reproduce

Unbound ctrl+tab, ctrl+shift+tab in keybinds section
```json
{
      "command": "unbound",
      "keys": [
        "ctrl+tab"
      ]
    },
    {
      "command": "unbound",
      "keys": [
        "ctrl+shift+tab"
      ]
    }
```

Bind vim `C-Tab` to `gt` (next tab)
```vim
nnoremap <C-Tab> gt
```

Try to change tab in vim using `CTRL+Tab`. 

# Expected behavior

Execute bound vim command and change tab.

# Actual behavior

Bound action is not executed, tab is not switched.

# Notes

In insert mode clicking CTRL+Tab just inserts tabs, which according to how other terminal emulators behave might mean that it's just sending Tab and ignoring CTRL. Is this the case here too?
https://stackoverflow.com/questions/2686766/mapping-c-tab-in-my-vimrc-fails-in-ubuntu
https://stackoverflow.com/questions/1646819/how-can-i-map-ctrl-tab-to-something-in-vim

I've tried binding `nnoremap <C-L> gt` (CTRL+L for same command) and it works as expected, as in it switches to next tab.

**Comment by DHowett-MSFT** [comment]
Yeah, it looks like there is no encoding for <kbd>Ctrl+Tab</kbd> that can be sent by a terminal emulator. Tab is _already_ a control character (<kbd>Ctrl+I</kbd>, actually), and you can't really exactly have a double-control character. SOrry.
