### ISSUE TITLE
Right click in conhost.exe is now entering multiline, but in reverse order

### ISSUE THREAD

**Issue by ekoschik** [microsoft/terminal#3905]
Copy three lines, for example:
$myList = @()
$myList += 'asdf'
$myList.count

Using ctrl+v to paste into (powershell) conhost works fine, and recently right clicking would have entered each line independently (not multi-line). Now though, it's entering each line in a multi-line, but in reverse order.

> $myList.count
>> $myList += 'asdf'
>> $myList = @()

not sure how to check my conhost.exe version, but my windows build is:
19530.rs_onecore_dep_ixp5.191204

**Comment by DHowett-MSFT** [comment]
Cannot repro. vb_release_dep, but all of our conhost changes are 100% cross-integrated (and we haven't taken post-vb payload)

## 5.1

![image](https://user-images.githubusercontent.com/14316954/70573904-b7eba580-1b57-11ea-98cc-26600168801b.png)

## 6

![image](https://user-images.githubusercontent.com/14316954/70574013-eb2e3480-1b57-11ea-86d0-19c07db6c4cb.png)


## 7

![image](https://user-images.githubusercontent.com/14316954/70574109-2af51c00-1b58-11ea-9050-601b8e5847fa.png)


^V doesn't work for me on any of them. **If this reproduces only with `^V`, this is a PSReadline change.** (PSReadline handles clipboard pasting through ^V.)
