### ISSUE TITLE
Cannot paste into PowerShell and right clicking does nothing (no context menu shows up)

### ISSUE THREAD

**Issue by jjgriff93** [microsoft/terminal#3914]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
@jjgriff93 Hey thanks for the report! Could you maybe fill out the issue template? Like for example, 
* what version of Windows are you running?
* Are you using the Windows Terminal, or the legacy console?
* What version of Windows Terminal are you running?
* What version of Powershell are you running?
* What version of PsReadline do you have installed?

We can't really do anything with this until we get a little more info :/
