### ISSUE TITLE
On-screen icons to indicate shell type?

### ISSUE THREAD

**Issue by MikePanitz-CCC** [microsoft/terminal#3916]
# Description of the new feature/enhancement

Windows Terminal has the ability to display an image in the background.  In addition to eye candy this feature can be used to identify the type of shell that is being run in the window.  For example:

![image](https://user-images.githubusercontent.com/45976071/70641538-a5727a00-1bf2-11ea-8ed5-22609f583eda.png)

or:

![image](https://user-images.githubusercontent.com/45976071/70641602-b8854a00-1bf2-11ea-979c-db1cea9bb2fa.png)

etc.

Proposed feature: What do y'all think about including a set of common icons so that it's easy to set this up 'out of the box'

# Proposed technical implementation details (optional)

I'd need to find appropriately licensed images, then size them appropriately, and then figure out where to put them in the repo/distro for Windows Terminal.  Including commented-out lines in the config file would be good, too.

If there's interest I think I can do the actual work on this.

I'm not guaranteeing that I'll be able to support the feature going forwards, but hopefully the support costs would be low.

**Comment by DHowett-MSFT** [comment]
Hey @MikePanitz-CCC! Sorry about the delay: all of December is pretty much a no-fly zone here :smile:. I've chatted with the team about this one, and we all decided it's probably better to let the users source their own background images to really bring out their personalities. Coupled with the licensing concerns, It might be best to leave this one be. I really appreciate your offer of help, though!
d
