### ISSUE TITLE
Uninstalled Ubuntu terminal is not removed from Windows Terminal list 

### ISSUE THREAD

**Issue by syamsitaufik** [microsoft/terminal#3924]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.535]
Windows Terminal version (if applicable): Windows Terminal (Preview)Version: 0.7.3382.0
Any other software: Ubuntu 18.04 LTS from windows store

# Steps to reproduce

1. I uninstalled Ubuntu 18.04
2. Then install Ubuntu 18.04

# Expected behavior

Ubuntu 16.04 or (uninstalled terminal) should be remove from list of windows terminal.

# Actual behavior

Ubuntu 16.04 still in the  list of windows terminal even already uninstalled.

![windows_terminal](https://user-images.githubusercontent.com/45581956/70677732-f48bde00-1cca-11ea-8fd7-bd2e2af2128d.png)

**Comment by DHowett-MSFT** [comment]
If you have never cleared your `profiles.json`, [_now is the time to do it._](https://www.hanselman.com/blog/NowIsTheTimeToMakeAFreshNewWindowsTerminalProfilesjson.aspx)

If you are carrying around a `profiles.json` from before version 0.5, WSL distributions that have been uninstalled will not automatically be removed.

The distribution scanning happens on launch.
