### ISSUE TITLE
Can't copy text with the defined or default keybinds

### ISSUE THREAD

**Issue by rafamoreira** [microsoft/terminal#3926]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.7.3382.0

Any other software?

WSL 2

This is a fresh install OS
Browser;
WSL;
drivers in general; 
VScode 
```

# Steps to reproduce
Open any shell available on Terminal, Ubuntu via WSL 2, PowerShell, or cmd, and it's not possible to copy the selected text, using the default bindings (ctrl+shift+c) even if those are defined on the settings json `{ "command": "copy", "keys": ["ctrl+shift+c"] }`

I don't know if it's related but the contextual menu is gone too. 

# Expected behavior

Copy on ctrl+shift+c 

# Actual behavior

Nothing happens when you hit the keybinding

Note that the pasting is working fine, both with the default ctrl+shift+v and right clicking without text selected

**Comment by zadjii-msft** [comment]
@rafamoreira Could you share your entire `profiles.json` file? I'm not aware of any current bugs with copying like this, so I'll definitely need some help repro-ing this. Thanks!

**Comment by rafamoreira** [comment]
Sure here it is:
```json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        },
        {
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": [
        { "command": "copy", "keys": ["ctrl+shift+c"] }
    ]
}
```

**Comment by DHowett-MSFT** [comment]
Just as a sanity check: if you right-click with text selected, does that successfully copy?

**Comment by rafamoreira** [comment]
Yes, it does copy, and if I add another keybinding, let's say:
`{ "command": "copy", "keys": ["shift+insert"] }`
It works with the shift+insert but not the ctrl+shift+c

**Comment by rafamoreira** [comment]
So, turns out the target was the wrong one, nothing is wrong with the Terminal, the culprit is the AMD GPU driver, that is capturing for some reason the ctrl+shift+c shortcut without any options to either inform, or change this.

I only noticed only on Terminal because is probably the only thing I use on windows that have this shortcut. I'm sorry for the trouble and wast of your time.

**Comment by DHowett-MSFT** [comment]
Thanks for letting us know!

**Comment by crackedmind** [comment]
@rafamoreira thnx, for point to amd issue. Find this solution to disable amd hotkeys https://community.amd.com/thread/246308
