### ISSUE TITLE
Range of scroll bar should be improved

### ISSUE THREAD

**Issue by kernelbin** [microsoft/terminal#3937]
# Description of the new feature/enhancement

The way scroll bar working now may bring some inconvenience.
Like this situation:
![新建位图图像](https://user-images.githubusercontent.com/25586021/70738855-8b4eae00-1d50-11ea-99db-78bb278cad24.jpg)
![1576175508(1)](https://user-images.githubusercontent.com/25586021/70738956-bf29d380-1d50-11ea-8f3b-d6e80f9488da.png)

I often do this when I got too much windows opened.
The problem is....
I can't scroll the window (scroll bar have already reached it's bottom), and I can't see the content below ( I cricled it by red pen in the following picture )
I even can't see the command i'm typing now. really terrible....

![新建位图图像2](https://user-images.githubusercontent.com/25586021/70739436-d4ebc880-1d51-11ea-8515-0c22510ceb40.jpg)

but traditional cmd doesn't have this problem (in fact it have, but in most case I won't output so many text that use up the whole buffer, by default, 9001 line. )
![1576175662(1)](https://user-images.githubusercontent.com/25586021/70739789-9c98ba00-1d52-11ea-8c80-95068591754e.png)

# Proposed technical implementation details (optional)

I think the way Visual Studio Text Editor work is better. (Extend the scroll bar range, so that the last line can be shown on the top of the window)
like this:

So even if I move half of the window out of the working area, I can still work without resize the window.

![1576176419(1)](https://user-images.githubusercontent.com/25586021/70739949-f13c3500-1d52-11ea-92c0-14c70ac95b9b.png)

Just simply calculate the windows height divided by the height per line, and add it to the scroll range.

**Comment by kernelbin** [comment]
Is this hard to implement caused by VT sequence?

**Comment by DHowett-MSFT** [comment]
@kernelbin Thanks for the request, and sorry for the delay. This is one thing we will probably never do: we have worked so hard in conhost to make it possible _not_ to do this.

If you want your window to be at the bottom of the screen, but still display all of its content ... can you not just make it shorter?

**Comment by kernelbin** [comment]
Oh ... It's a pity. But why worked hard to not to do this?
VT Sequence caused this or something else?

**Comment by DHowett-MSFT** [comment]
It makes it very hard to support every VT sequence. Many VT sequences operate on the “screen”, and if we let the “screen” scroll halfway off the window it will be very difficult.
