### ISSUE TITLE
Ctrl+C some programs closes Terminal instead of stopping current process when running PowerShell Core

### ISSUE THREAD

**Issue by daniefer** [microsoft/terminal#3940]
When attempting to stop some programs the terminal will close instead of stopping the current process. `npm`, `ping`, and `cmd` are the only programs I have found so far that do this. Windows Terminal used to not do this and it only started happening after an update about 15-30 days ago. I can provide more info if needed, I just don't know what else to provide.

## What I have tried so far
1. Uninstalling and Reinstalling
1. Trying running commands in PowerShell Core without Windows Terminal

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.7.3382.0

PowerShell Core version
6.2.3

npm version:
6.12.0

node version:
v12.13.0

cmd version:
Microsoft Windows [Version 10.0.18362.476]
```

# Steps to reproduce
1. Open a terminal 
1. Run `cmd`
   * this is not the only command that does this. `npm run <script>` or `npm run` also do it. These are just the two cases I have run across so far
1. Enter `Ctrl + C`
1. The terminal closes instead of stopping the current running process

# Expected behavior
The current running process is killed

# Actual behavior
The terminal closes

**Comment by DHowett-MSFT** [comment]
Did you install powershell core as a dotnet global tool? If so, #3869.

**Comment by daniefer** [comment]
Wholly cow! You are a god send! Thank you and sorry for the duplicate issue.

**Comment by daniefer** [comment]
For those looking for a resolution, use the MSI installer

**Comment by DHowett-MSFT** [comment]
Thanks for confirming! Closing as an actual /dup of #3869.
