### ISSUE TITLE
Pepper emoji not properly displayed

### ISSUE THREAD

**Issue by ice1000** [microsoft/terminal#3945]
# Environment

```none
Windows build number: 10.0.18363.535
Windows Terminal version (if applicable): v0.7.3451.0
```

# Steps to reproduce

+ Type `` `\u{1f336}\u{1f414}` `` in your browser console and copy the output (should be `🌶🐔`)
+ Do `echo "` - paste - `"`
+ Enter

# Expected behavior

Display `🌶🐔`

# Actual behavior

Display 
![image](https://user-images.githubusercontent.com/16398479/70762937-69d5ce00-1d20-11ea-8da6-5c140794e2bc.png)

Also, the pepper displayed is very small. A regular emoji should be larger. Here's a comparison:
![image](https://user-images.githubusercontent.com/16398479/70762977-8d991400-1d20-11ea-82c7-2c0654be43f8.png)

**Comment by DHowett-MSFT** [comment]
This is either related to or will be fixed by us fixing /dup #900.
