### ISSUE TITLE
git diff cannot show chinese/unicode character

### ISSUE THREAD

**Issue by onriv** [microsoft/terminal#3946]
# Environment

```powershell
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

terminal version

```
Windows Terminal (Preview)
Version: 0.7.3382.0
```

# Steps to reproduce

```
echo "中文" >> test.txt;git add .;git commit -m "中文"
git diff HEAD HEAD^
```

# Expected behavior

show chinese/unicode character in git diff,  the follow screenshot is from conemu:

![image](https://user-images.githubusercontent.com/1629055/70764430-8f9bbb00-1d92-11ea-9115-f326aa8b15dd.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/1629055/70764327-3fbcf400-1d92-11ea-892d-41e4388c9fe4.png)

**Comment by DHowett-MSFT** [comment]
This is a bug in git. It does not believe that it can display UTF-8 on the terminal.
Thanks.
