### ISSUE TITLE
WT_SESSION doesn’t appear in WSL

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#3948]
We did not realize that `WT_SESSION` wouldn’t appear in WSL because it’s not in `WSLENV`.

This may also impact VS Code.

/cc @mixmastamyk

**Comment by DHowett-MSFT** [comment]
@benhillis is it valid for us as a hosting application to prepend to the user’s `WSLENV`?

**Comment by benhillis** [comment]
Yeah that should be fine.
