### ISSUE TITLE
Change profiles.json and defaults.json to profiles.jsonc and defaults.jsonc.

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/terminal#3949]
The format of the content of `profiles.json` changed from JSON to JSONC, which is incompatible with JSON. The format of the file should be changed to `.jsonc` to avoid triggering JSON linters.

# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19025.0 Microsoft Windows NT 10.0.19025.0

Windows Terminal (Preview)
Version: 0.7.3451.0
```

# Steps to reproduce

1. Open settings

# Expected behavior

A file named `profiles.jsonc` opens in VSCode.

# Actual behavior

A file named `profiles.json` opens in VSCode.

**Comment by DHowett-MSFT** [comment]
For VSCode _specifically_, this experience should be a lot better as of microsoft/vscode#78559 (which looks like it shipped in 1.41.0). For the broader use case, I appreciate your concern (and thank you for flagging this issue!)... but we're not likely to change horses this late.

Sorry!

**Comment by NatoBoram** [comment]
> we're not likely to change horses this late.

Isn't it *exactly* what you did by changing the format to JSONC in the first place? You could have added a simple migration logic to respect naming conventions and avoid breaking everything that's not in this repo.

**Comment by DHowett-MSFT** [comment]
> isn’t that _exactly_ what you did

It may appear that way, but we were using JSONC from the outset- we just didn’t ship a config file that contained comments by default.

**Comment by hapylestat** [comment]
no idea where here is the problem, for example Sublime Editor keep his JSONC configs with JSON file extension, also able to distinguish JSON from JSONC files by content, as it supposed to be.  I guess this sample is true for another products as well: for example json parser for java able to handle such cases as well.

**Comment by GTonehour** [comment]
I'd also like the possibility to suffix `settings` to `jsonc`. For instance my Helix install doesn't support commentaries in `json`-suffixed files.

**Comment by DHowett** [comment]
I am sorry. We are not staging a migration for 300 million users because some text editors lack the configurability to set the language mode for certain files.
