### ISSUE TITLE
bracketed paste in conhost

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/terminal#395]
Does the Windows console support [bracket paste mode](https://wpdev.uservoice.com/forums/266908)? I wasn't able to find any information about that.

**Comment by DHowett-MSFT** [comment]
Funny you should ask! I've been working on this one myself, as I'd love to see it land.
I'll mark this one with our backlog/tracking tags.

**Comment by vapier** [comment]
one suggestion to keep in mind (as I've seen more than one implementation forget this edge case): make sure to filter out control sequences when pasting. otherwise the buffer could embed the end sequence thus defeating the point of it.

if you want to be compatible with xterm (who invented this feature), you want to filter:
\x00-\x07
\x0b-\x0c
\x0e-\x1f

**Comment by oising** [comment]
@DHowett-MSFT  -- worth ingesting this page here concerning the security issues various implementations of bracketed paste mode may have: https://lwn.net/Articles/749992/

**Comment by miniksa** [comment]
@oising, thank you for that read. I think the best thing we could do is write tests for the specific security issues listed there and attempt to mitigate them as we implement the bracketed paste mode.

**Comment by chris-morgan** [comment]
Would it be possible and/or reasonable for starters to just have ConPTY pass through `ESC [ ? 2004 h`, `ESC [ ? 2004 l` on stdout, and `ESC [ 200 ~` and `ESC [ 201 ~` on stdin, so that other terminals that support bracketed paste (e.g. Alacritty) can support it? (It makes me sad when such terminal emulators are blocked from supporting functionality on Windows because ConPTY filters out the magic.)

**Comment by FlipperPA** [comment]
@DHowett Dustin, thanks for pointing me to this issue from the one I had opened concerning pasting into IPython / vi. Are there any workarounds in the meantime?

**Comment by DHowett-MSFT** [comment]
In the meantime, before/after pasting in vim you can `:set paste` and `:set nopaste`. I'm not certain what ipy needs here, unfortunately. ☹️

**Comment by FlipperPA** [comment]
Just a note to anyone looking: it may be possible to enable this in `bash`. I haven't been able to test yet (currently on my Mac, where pasting works fine).

https://stackoverflow.com/questions/35611134/bash-bracketed-paste-is-it-supported

**Comment by skyline75489** [comment]
For the 8 people who subscribed this (one of them being an obsolete account of Dustin), the bracketed paste mode in Windows Terminal is implemented in #9034 and should be available in 1.7 preview 🎉 . 

Thanks everyone for the discussion about the potential security issues. I believe most of them has been taken care of in the implementation. Feel free to contact me if you have any questions about the current implementation.

**Comment by oising** [comment]
@skyline75489  ! Woo

**Comment by FlipperPA** [comment]
This is fantastic, @skyline75489 - thank you to everyone who worked on it.

**Comment by gbtec-markusmeier** [comment]
Wasn't subscribing, but watching silently for some months - just saw that @cinnamon-msft mentioned this great feature in Terminal Preview 1.7. Looking forward to next month's release!

**Comment by DHowett** [comment]
@gbtec-markusmeier Preview is fairly stable itself; you could switch over today!

**Comment by davidanthoff** [comment]
Fantastic, thanks for implementing this! I'm closing this issue, because I guess it is all done :)

**Comment by skyline75489** [comment]
@davidanthoff my work is to bring bracketed paste into Windows Terminal. The support for bracketed paste in Conhost is yet to be done. I understand this issue is probably opened when Windows Terminal wasn’t really a thing, but here it is. 

We may want to reopen this and change the title to just “bracketed paste in conhost”.

**Comment by davidanthoff** [comment]
Done!

**Comment by FlipperPA** [comment]
Just a big THANK YOU to everyone involved - this is a huge time saver and help for my workflow.

**Comment by blayz3r** [comment]
> 
> 
> @davidanthoff my work is to bring bracketed paste into Windows Terminal. The support for bracketed paste in Conhost is yet to be done. I understand this issue is probably opened when Windows Terminal wasn’t really a thing, but here it is.
> 
> We may want to reopen this and change the title to just “bracketed paste in conhost”.

So bracketed paste will not work in ConPTY atm? correct?

**Comment by zadjii-msft** [comment]
No it should work just fine in conpty (the Terminal uses conpty too 😉). Conhost (the vintage console) still needs to implement support for this itself, but that should be much simpler now.

**Comment by blayz3r** [comment]
> 
> 
> No it should work just fine in conpty (the Terminal uses conpty too 😉). Conhost (the vintage console) still needs to implement support for this itself, but that should be much simpler now.

Ok great, is there a preview version on ConPty. or do we have to wait for the new release:
Context using conpty in Gvim:
![image](https://user-images.githubusercontent.com/12205650/110487098-3e749700-80bb-11eb-9c41-bdccccb39fac.png)

**Comment by dashesy** [comment]
I have 1.15.2875.0 but this seems to be unsupported still.

**Comment by DHowett** [comment]
> I have 1.15.2875.0 but this seems to be unsupported still. 

@dashesy i would encourage you to file a new issue and fill out the issue template. As far as we are aware, paste bracketing works fine for every client application that requests it. Filing a new issue would be the best way to draw attention to, and provide specific information about, the problem you're facing.
