### ISSUE TITLE
Strange artifacts when running NVim

### ISSUE THREAD

**Issue by asolopovas** [microsoft/terminal#3954]
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

# Steps to reproduce
Start nvim in `Windows Terminal Preview`

# Expected behaviour

No lines across the window and no yellow/orange artefacts when resizing the window 

# Actual behaviour
You will see at the beginning of the gif you have some sort of horizontal lines across the window. 

![fIgOCxRp74](https://user-images.githubusercontent.com/6893216/70802004-3b9bd100-1da8-11ea-94f2-3c7b8482db90.gif)

**Comment by DHowett-MSFT** [comment]
We're tracking this one and its friends in /dup #455.

**Comment by offero** [comment]
Just came here to report a similar issue still with terminal leaving character artifacts on incorrect lines when scrolling in neovim.

Terminal Version: 1.2.2381.0
