### ISSUE TITLE
Feature Request: Integrate tmux scrolling with Terminal's scrollbar

### ISSUE THREAD

**Issue by sjetha** [microsoft/terminal#3955]
# Description of the new feature/enhancement
XTerm has a feature that allows you to interface between the scrollbar and some application inside.
Here is the code that will get this working between tmux and XTerm:
`set -g terminal-overrides 'xterm*:smcup@:rmcup@'`

# Proposed technical implementation details (optional)
It would be cool if Terminal also provided some way of integrating with things like tmux or screen, so that scrolling the Terminal window will scroll back and forth through the console's output rather than scrolling up into text that was previously written to the buffer, which doesn't make much sense for these sorts of applications.

Reference: https://superuser.com/a/326592

**Comment by DHowett-MSFT** [comment]
I think you're asking for /dup #545.
