### ISSUE TITLE
Fullscreen on Rotated Display

### ISSUE THREAD

**Issue by Elevate08** [microsoft/terminal#3959]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.476]
Windows Terminal version (if applicable): 0.7.3451.0

Any other software?
```

# Steps to reproduce

Place Windows Terminal on Rotated Display (Portrait (flipped))
Press F11
Receive Grey block in middle of screen, and no text. Terminal still receives input but you don't see it unless you press F11 again and exit Full Screen mode

# Expected behavior

Terminal takes up full screen in all monitor orientations.

# Actual behavior

Full screen on Portait mode results in the terminal not displaying correctly. Cannot see shell at all but input is still passed in
     (confirmed by exiting Full Screen mode and seeing input on screen)

![microsoft-terminal-portrait-fullscreen](https://user-images.githubusercontent.com/3460250/70829152-eddc9400-1dba-11ea-9ab7-48ef8460ff78.png)

**Comment by j4james** [comment]
This might be related to issue #3710. The cause is different, but they're seeing the same grey block when the fullscreen fails.

**Comment by Elevate08** [comment]
Duplicate of #3710 , closing this issue
