### ISSUE TITLE
Feature request: automatic splits similar to tiling window managers

### ISSUE THREAD

**Issue by ericist** [microsoft/terminal#3960]
# Description of the new feature/enhancement
Creating new splits could be made easier by providing a keybinding that automatically splits the currently active pane based on the current split type, similar to tiling window managers such as bspwm.

When activating the keybinding (e.g. Alt+Shift+Enter) following would happen:
If no split exists yet, the terminal would be split vertically. If a split exists and the currently active pane is part of a vertical split, it would be split horizontally and vice versa.

This is also visualized in [the documentation of bspwm](https://github.com/baskerville/bspwm#longest-side-scheme)
Additionally, other schemes such as a [spiral scheme](https://github.com/baskerville/bspwm#spiral-scheme) could also be implemented

# Proposed technical implementation details (optional)
The implementation could in theory be very simple: Just query the split type of the active pane
(vertical/horizontal) and create a new split of the other type when pressing the keybinding.

I would try to implement this feature myself but unfortunatley do not have the time at the moment.

**Comment by zadjii-msft** [comment]
Okay so this sounds like _two_ different requests here
1. Use the current profile for creating a new split. This is already tracked by #1756, so let's direct that discussion to that thread.
2. "automatic" or "spiral" split mode - I don't hate this. And with `horizontal` and `vertical` already being parameters for `splitPane`, we could totally extend that to split in automatic ways like this.

**Comment by ericist** [comment]
You're right, I didn't think about different profiles because I currently only use one.

Simply alternating the split types would propably be way easier to implement than
something more complex like a spiral (sometimes also called fibonacci) mode (which personally
I also find not very useful anyway, I just wanted to give another example).

If this would be implemented there could also be a split ratio parameter (also found in bspwm)
which decides if a new split should split the current pane in the middle (ratio 50%) or at another point.
