### ISSUE TITLE
OBS Studio cannot Window capture Windows Terminal

### ISSUE THREAD

**Issue by jiria** [microsoft/terminal#3961]
# Environment

```none
Windows build number: 10.0.18363.0, 10.0.19534.0
Windows Terminal version: 0.7.3451.0, 0.7.3382.0
OBS Studio version: 24.0.3
```

# Steps to reproduce

1) Start `Windows Terminal`
2) Start [OBS Studio ](https://obsproject.com/)
3) Add a source in the `Sources` pane at the bottom by clicking `+` and selecting `Window Capture -> OK`. Then select `Windows Terminal` window from the `Window` drop box.

# Expected behavior

You should see contents of `Windows Terminal` window in the preview window.

# Actual behavior

You only see gray rectangle.

**Comment by driver1998** [comment]
Using "Game Capture" sort-of works, but only the active tab when capture is set is captured. It won't change after switching tabs.
![QQ截图20191222183644](https://user-images.githubusercontent.com/22699485/71320701-06029080-24ea-11ea-9b40-ccce6195992f.png)
![QQ截图20191222183754](https://user-images.githubusercontent.com/22699485/71320706-2e8a8a80-24ea-11ea-9420-a82f2206636e.png)

**Comment by SeanChao** [comment]
> Using "Game Capture" sort-of works, but only the active tab when capture is set is captured. It won't change after switching tabs.
> ![QQ截图20191222183644](https://user-images.githubusercontent.com/22699485/71320701-06029080-24ea-11ea-9b40-ccce6195992f.png)
> ![QQ截图20191222183754](https://user-images.githubusercontent.com/22699485/71320706-2e8a8a80-24ea-11ea-9420-a82f2206636e.png)

I tried to **set `useAcrylic` to false** in Windows Terminal Profiles as with using game capture,  and then OBS can capture it normally.

**Comment by LinHeLurking** [comment]
Setting capture method as "Windows Capture (Windows 10 1903 and up)" solves this, even with useAcrylic on.
![image](https://user-images.githubusercontent.com/35602373/79727569-2a973980-831f-11ea-936d-89af3b000705.png)

**Comment by jiria** [comment]
I can confirm with the latest version (25.0.4) of OBS studio, using Windows Graphics Capture works. Quickly looking at OBS changelog, it seems this was only recently enabled in the version 25. As such, I think there is no additional work needed by WT team.

**Comment by DHowett-MSFT** [comment]
That's great news; thanks for following up.

**Comment by daanbreur** [comment]
Thanks that fixed it for me  :)

**Comment by iuriguilherme** [comment]
Happening to me in Windows Home 18363

Not only OBS Studio can't add Windows Terminal as a window, it seems to block whole screen capture as well.

**Comment by zadjii-msft** [comment]
@iuriguilherme Which version of OBS Studio are you using? A previous commenter mentioned that updating to OBS Studio version 25+ fixed the issue for them.

**Comment by iuriguilherme** [comment]
@zadjii-msft OBS Studio 26.1.0 (64 bit)

**Comment by zadjii-msft** [comment]
Interesting. I wonder if they have a bug tracker - it sounds like they regressed support (since it did work at one point)

**Comment by iuriguilherme** [comment]
I've just attempted to change the capture method from "automatic" to "windows graphic capture" and it seem to work as expected.

The full screen capture is still not working, but that could be an unrelated issue which I will report to OBS Studio tracker.

![screenshot 1611836816](https://user-images.githubusercontent.com/2027447/106138794-59aec700-614b-11eb-89a5-8ecbec35c815.png)

![screenshot 1611836829](https://user-images.githubusercontent.com/2027447/106138781-561b4000-614b-11eb-95c4-de7df8fc53ea.png)

**Comment by raveensrk** [comment]
> Setting capture method as "Windows Capture (Windows 10 1903 and up)" solves this, even with useAcrylic on.

Can confirm that this works.

**Comment by kyrlon** [comment]
> I've just attempted to change the capture method from "automatic" to "windows graphic capture" and it seem to work as expected.
> 
> The full screen capture is still not working, but that could be an unrelated issue which I will report to OBS Studio tracker.
> 
> ![screenshot 1611836816](https://user-images.githubusercontent.com/2027447/106138794-59aec700-614b-11eb-89a5-8ecbec35c815.png)
> 
> ![screenshot 1611836829](https://user-images.githubusercontent.com/2027447/106138781-561b4000-614b-11eb-95c4-de7df8fc53ea.png)

Confirm this works on Windows 11!

**Comment by ka1ne** [comment]
The relevant option now is _Windows 10 (1903 and up)_
<img width="698" height="42" alt="Windows 10 (1903 and up)" src="https://github.com/user-attachments/assets/ba928eac-eafa-4da5-857d-15ae3077548b" />
