### ISSUE TITLE
Save connections as a list in terminal

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3964]
# Description of the new feature/enhancement
I hope terminal has a feature that let user save a connection into a list , then user can start connection again by click on the connection in the list(drop down list I think).

Every day I need to connect to many server, I have to start a new tab in terminal ,then type connection info ,then connect to the server. not cool.!.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
You can add any number of different connections in your `profiles.json`.
