### ISSUE TITLE
History not saved on some machines

### ISSUE THREAD

**Issue by XinranZhao** [microsoft/terminal#3966]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18363.476]

Windows Terminal version (if applicable): 0.7.3382.0

Any other software?
Ubuntu 16.04.6 LTS

# Expected behavior

command history can be saved  and got accessed by command 'history'

# Actual behavior
I have the same profiles.json file for multiple pc machines running Win10. Strangely, some of them can save history properly and some of them cannot. Can you help me with some hint what is stopping some machines from saving command history?

**Comment by zadjii-msft** [comment]
@XinranZhao What _shell_ are you using (`cmd`, `powershell`, `bash`, `zsh`, etc.)? It's typically the responsibility of the _shell_ to save the command history, so whatever problem you're having is probably related specifically to the _shell_, not the _terminal_, though I'll be happy to help you figure it out 😄

**Comment by XinranZhao** [comment]
> @XinranZhao What _shell_ are you using (`cmd`, `powershell`, `bash`, `zsh`, etc.)? It's typically the responsibility of the _shell_ to save the command history, so whatever problem you're having is probably related specifically to the _shell_, not the _terminal_, though I'll be happy to help you figure it out 😄

Appreciate your reply. As mentioned I only use terminal for WSL so the shell is bash:

GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

I am comparing two Win10 PCs, with the same profile.json setting for windows terminal, and .bashrc for WSL, but one of them can save history and the other cannot. Can you advise me how to troubleshoot this problem? 

Thanks!

**Comment by Biswa96** [comment]
This doesn't look like Windows Terminal issue. For shell history, bash uses two environment variables `HISTFILE` and `HISTFILESIZE`. Check if those varibales have some value. Otherwise, check `.bashrc` file.

**Comment by XinranZhao** [comment]
I agree that this is not an issue with WT, so I herein close this thread. Thanks a lot for the help!

**Comment by sinistram** [comment]
It will be great to support history keeping in the terminal (for cmd and etc).

**Comment by DHowett-MSFT** [comment]
@sinistram thanks for the feedback! As per https://github.com/microsoft/terminal/issues/3966#issuecomment-566071286it's not really the _terminal's_ job to save history... unless you're referring to the scrollback history.

**Comment by sinistram** [comment]
@DHowett-MSFT I mean in windows cmd, powershell and etc history of called commands is not keeping after shell restart. And it will be great to have a functionality for keeping commands history even after pc reboot (like in osx). 

Imagine that you have some long command and every time you restart terminal you have to write command again and again. I understand that cmd is not providing this feature, but may be it is possible to implement it in the terminal?

**Comment by DHowett-MSFT** [comment]
The main reason command history is _so bad_ in cmd and legacy powershell is because we implemented it in the “terminal” 25 years ago.

The windows console host keeps track of the history for every legacy process.

Please switch to a more civilized shell, like powershell 6 or 7. Even powershell 5.1 supports saving history to a file. The only shell in common modern use that doesn’t is cmd.
