### ISSUE TITLE
Feature Request: Custom CSS

### ISSUE THREAD

**Issue by ngschroeder** [microsoft/terminal#3967]
# Description of the new feature/enhancement

Custom CSS. For example, in VS Code, there's an extension that allows custom CSS. This should be native functionality. (Maybe with a developer flag to play it safe?)

# Proposed technical implementation details (optional)

```
    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{nnn}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false,
            "custom_css": "/path/orURL/to/myfile.css"
        },
    ]
```

Allows for cool stuff like this.
![theme](https://user-images.githubusercontent.com/16778828/70850323-fc788900-1e56-11ea-9435-04bbfefaf899.jpg)

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the request! Since we’re not built on a web browser engine, it would be almost impossible for us to properly support CSS. You might want to follow #3327 for an alternative, though.

**Comment by ngschroeder** [comment]
Thanks Dustin, looks like that covers a lot of it!
