### ISSUE TITLE
Support minimum contrast ratio of characters

### ISSUE THREAD

**Issue by Piroro-hs** [microsoft/terminal#3969]
# Description of the new feature/enhancement

It would be great if the foreground color of rendered text in terminal change dynamically to meet a specified contrast ratio, like [this](https://github.com/xtermjs/xterm.js/issues/1514).

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This sounds similar to what issue #2638 evolved into.

**Comment by zadjii-msft** [comment]
Yea I think @j4james has got this right. Thanks!

/dup #2638
