### ISSUE TITLE
How to enable "Use Ctrl+Shift+C/V as Copy/Paste" for our command line app?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/terminal#397]
How would we enable support for that out of the box for a command line app we ship? Would we somehow create a shortcut that has this configured as true during our setup? If so, I couldn't find any information how that would configured in the shortcut.

Or is there a way to enable this via say `SetConsoleMode`?

**Comment by davidanthoff** [comment]
Thanks!

I think as a first step publishing the GUID for the `InterceptCopyPaste` would be great.

I think probably the right thing to do would be that the julia setup (that is what I'm investigating here) writes both the registry key and the shortcut file with this change.

The one thing that would still not work, I believe, is if someone started julia from say a PowerShell prompt, right? In that case the setting for PowerShell for this would take over?

If this setting is not set, does the terminal then pass these keystrokes through to the command line app?

**Comment by miniksa** [comment]
I'm not certain whether the settings will stay inherited or switch to the other application's preferences. My gut says you're right and the Powershell settings would stay applied, but it's been a long time since I messed with this code (and don't honestly have time today to page that back into memory, sorry.)

If it's not set, then yes. The keystrokes go through to the application instead of being intercepted and acting on the host window level.

**Comment by miniksa** [comment]
I think this is answered and the GUID should be in the sources now.

**Comment by eryksun** [comment]
> If it's launched without a shortcut, it uses the user defaults in HKCU\Console and then stacks the specific subfolder node for the executable on top of it.

The subkey name is based on the initial window title (`STARTUPINFO.lpTitle`) of the process that allocates the console. It happens that `CreateProcess` defaults to using the executable path as the window title if `lpTitle` is `NULL`. But note that it's not the resolved path, so the same executable accessed via different paths (e.g. junction, directory symlink, subst drive) corresponds to a different console subkey. If a specific title is set, the console uses the subkey for that title (with backslash replaced by underscore), and *not* the subkey for the executable path (e.g. if the title is set via CMD's `start` command, even with `start "" "command"`, an empty title used to work around the simplistic argument parsing of the `start` command). When run by a shortcut, `lpTitle` is the .LNK file path, and this is flagged in the startup info as `STARTF_TITLEISLINKNAME`.
