### ISSUE TITLE
Changing Keybinds

### ISSUE THREAD

**Issue by dmoa** [microsoft/terminal#3970]
I am unsure about what the correct variables are to use and change in profiles.json

I am trying to switch my keybindings for shells from ctrl+shift+1 & ctrl+shift+2 to ctrl+1 and ctrl+2. 

In the documentations, it does not mention what the names for these are.

any help is appreciated!

**Comment by dreadnaut** [comment]
I have these in my `profile.json` file:
```json
{ "command" : "newTabProfile0", "keys" : [ "ctrl+shift+1" ] },
{ "command" : "newTabProfile1", "keys" : [ "ctrl+shift+2" ] },
[ ... ]
```
The commands should be `newTabProfileX`.

**Comment by zadjii-msft** [comment]
The docs _definitely_ do mention what names to use though - see [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keybindings) for both a list of possible actions and [possible keys](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#example-keys) to use.

**Comment by dmoa** [comment]
Must have missed that file, thanks for the link
