### ISSUE TITLE
Titlebar color isn't updated according to color scheme

### ISSUE THREAD

**Issue by rafifos** [microsoft/terminal#3973]
# Description of the new feature/enhancement

The titlebar (and tabs) color should have the same background color of the current color scheme, or if this isn't possible, something (like a border or a shadow) to differenciate between the shell and titlebar.

What shouldn't happen:

![image](https://user-images.githubusercontent.com/12601769/70865918-76853c80-1f41-11ea-8746-938f3909bb7c.png)

**Comment by j4james** [comment]
I'm not exactly sure what you're asking for, but I suspect this is a duplicate of either #702 or #3774.

**Comment by rafifos** [comment]
Yeah, it basically both of them. I couldn't find any related issues before, sorry.
