### ISSUE TITLE
Keybinding commands

### ISSUE THREAD

**Issue by TeoTN** [microsoft/terminal#3974]
I'm not able to find information about all commands that can be bound to keys. Documentation only gives an example for a few of them:
```
{
    "keybindings":
    [
        { "command": "closePane", "keys": ["ctrl+shift+w"] },
        { "command": "copy", "keys": ["ctrl+shift+c"] },
        { "command": "newTab", "keys": ["ctrl+shift+t"] },
        // etc.
    ]
}
```
I wasn't able to find more options neither in Google nor in the repository

**Comment by j4james** [comment]
The documentation you're looking for is here:
https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#implemented-commands

**Comment by zadjii-msft** [comment]
Taken from my reply in #3970

> 
> The docs _definitely_ do mention what names to use though - see [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keybindings) [](/microsoft/terminal/blob/HEAD@{2019-12-16T13:49:07Z}/doc/cascadia/SettingsSchema.md#keybindings) for both a list of possible actions and [possible keys](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#example-keys) [](/microsoft/terminal/blob/HEAD@{2019-12-16T13:49:07Z}/doc/cascadia/SettingsSchema.md#example-keys) to use.

[Here](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp#L27-L80) it is in the code too.
