### ISSUE TITLE
Where can I get list of all keybinding commands and default mappings?

### ISSUE THREAD

**Issue by happylynx** [microsoft/terminal#3975]
https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#implemented-commands lists commands but without default mappings. The `keybindings` section in `profiles.json` is empty by default. How can the default mapping be obtained?

**Comment by zadjii-msft** [comment]
You can open the `defaults.json` file by holding <kbd>alt</kbd> and clicking on the "settings" button, or you can just view it online [here](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json).
