### ISSUE TITLE
Provide a programmatic way to open a program in a new tab

### ISSUE THREAD

**Issue by pfmoore** [microsoft/terminal#3977]
# Allow the user to open a new tab from the command line

Rather than opening a new tab by selecting an item from the drop-down menu, or pressing a shortcut key, allow the user to open a new tab using a command line. So, for example, to open an instance of Python in a new tab, something like `new-tab python`. Obviously the exact command name doesn't matter, the key is to have the functionality.

A similar feature is available in [ConEmu](https://conemu.github.io/), where the command line is scanned for a `-new_console` flag: `python -new_console`. I'm assuming that intercepting and scanning command lines is messier and less robust than a dedicated command would be. This feature is extremely useful when starting a command that should run "in the background" - for example when starting a Jupyter notebook session. 

# Proposed technical implementation details

This proposal would probably require exposing a programmatic API to "the currently running instance of terminal". Such an API could in practice have far wider reaching implications than just a "run command in new tab" API, and I understand that it could be a significant feature addition. At this point, though, I would be happy with a limited approach that only offered "open a new tab".

It's also possible that something like this already exists, but I haven't been able to find any documentation or examples of it, if that's the case.

**Comment by zadjii-msft** [comment]
Hey thanks for the suggestion! We're actually working on designing this exact request over in #607 and #3495. I'll direct discussion to those threads.

/dup #607

**Comment by pfmoore** [comment]
Nice! Thanks for the pointer, I'd missed the other issue :-)

**Comment by pfmoore** [comment]
Update: Sorry it took me so long to get back to this, but it appears that #607 did *not* address this issue - that issue as implemented only allows controlling how a *new* instance gets opened. My request here is for a way to control an *already open* instance of Windows Terminal. I'd held off coming back here on the assumption that the implementation was "still in progress", but that issue now seems to have been closed and the feature is considered released, but it doesn't do what I asked for.

What I am looking for is a way to (for example) type a command into an existing Terminal instance, and have that command open a new pane alongside the existing one, and run my program in that pane. Here's a couple of screenshots of how the equivalent functionality works in ConEmu:

![image](https://user-images.githubusercontent.com/1110419/92741357-6f774780-f376-11ea-8ff0-afd1a4199560.png)

![image](https://user-images.githubusercontent.com/1110419/92741391-7b630980-f376-11ea-8985-c9f39ea69d55.png)

I'd be expecting an equivalent command in wt to be something like `wt -action split-pane -run py`

@zadjii-msft I don't know how to re-open this issue, could you do that please? Or should I open a new issue, explaining my request more clearly?

**Comment by zadjii-msft** [comment]
@pfmoore Oh, sorry for the misunderstanding. We're tracking that part of this scenario over in #4472 and #5000 now

**Comment by pfmoore** [comment]
@zadjii-msft Awesome, thanks for the pointers - and apologies that I didn't manage to find those issues myself.

I'm really impressed with both Windows Terminal itself, and the super responsive and helpful interactions on the tracker here - keep up the good work! 🙂
