### ISSUE TITLE
Text with combining characters is rendered incorrectly after editing

### ISSUE THREAD

**Issue by mandel59** [microsoft/terminal#3979]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.535]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.7.3451.0
Ubuntu 18.04.3 LTS/WSL1
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
```

# Steps to reproduce

1. Paste "そのチェㇷ゚は𩸽" to the terminal.
2. Type backspace key 8 times.
3. Paste "そのチェㇷ゚は𩸽" to the terminal.
4. Type backspace key 8 times.
5. Paste "そのチェㇷ゚は𩸽" to the terminal.
6. Type Home key.
7. Type "echo ".
8. Type enter key.

# Expected behavior

You can delete and insert characters as expected:

![MSYS__c_Users_mande 2019-12-17 16-17-47](https://user-images.githubusercontent.com/1079715/70973453-07e2e300-20e9-11ea-9f0f-399e72d2a422.gif)

# Actual behavior

Some characters remains after deletion, and characters are inserted in strange places:

![mandel59@MSI_ ~ 2019-12-17 16-20-42](https://user-images.githubusercontent.com/1079715/70973703-7de74a00-20e9-11ea-8f57-8a98dc407f63.gif)

**Comment by DHowett-MSFT** [comment]
Text with combining characters isn't actually supported. It will occasionally render "okay", but it's not ready for prime tmie. /dup #1472
