### ISSUE TITLE
The first keystroke after dismissing the find dialog is eaten

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3984]
### Repro Steps:

1. Open the find dialog
2. Type some text
3. Press <kbd>esc</kbd> to dismiss the dialog
4. type some characters

### Actual behavior:
The first character typed after dismissing doesn't get sent to the `TermControl`

### Expected
All the characters typed after dismissing the dialog should be sent to the `TermControl`/`TerminalConnection`

**Comment by KaiyuWang16** [comment]
Hi @zadjii-msft , I wonder if you can try again and repo this now ? Actually, I cannot repo this.

**Comment by DHowett-MSFT** [comment]
@KaiyuWang16 have you tried with both the keyboard _and_ the mouse?

**Comment by KaiyuWang16** [comment]
> @KaiyuWang16 have you tried with both the keyboard and the mouse?

Yes, I used "Esc" and mouse to close the search dialog.

**Comment by zadjii-msft** [comment]
Oh I see what's happening. It doesn't _really_ repro in `cmd`, but it does fairly consistently in a `bash` shell. The reason is not that the search box is eating a char, but the <kbd>Esc</kbd> is getting turned into a literal `Esc` sent to the input, and `bash` treats this specially. 

You can really see this "`esc` to the input" if you try the following in a `cmd` tab:
1. Type a command, but _don't_ enter it. Just leave it on the prompt line
2. Open the find dialog
3. Dismiss it with <kbd>Esc</kbd>

You'll see that the command you've typed is now gone, as if you hit <kbd>Esc</kbd> in `cmd`

**Comment by KaiyuWang16** [comment]
@zadjii-msft this PR should fix this issue: https://github.com/microsoft/terminal/pull/4028 I can not repro now.

**Comment by zadjii-msft** [comment]
@DHowett-MSFT confirmed for me that #4028 fixed this as well 😄
