### ISSUE TITLE
Investigate Defering Pane initialization until after layout is completed

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3996]
Found during the course of investigating #607. Right now we attempt to create the UI of the Pane _immediately_ on construction. While investigating commandline args, I'd try to create a bunch of `Pane`s. This didn't work, because the Pane would have 0 height/width, and would fail to create the UI, or attache the child, until a resize came through.

This is overall bad. We should probably wait until we complete the first layout to calculate how much size we have. Part of the reason this was so bad is that we're manually setting the width/height of our rows/columns to the number of pixels equal to some % of what's available. When that's being calculated, there's only 0px available.

**Comment by DHowett-MSFT** [comment]
I just had a crazy thought. Have we been missing something Xaml gives us for free for a long time?

```
<ColumnDefinition Width="49*" />
<ColumnDefinition Width="51*" />
```

`Star` sizes are proportional-weighted; perhaps we can parlay that into percentages?

**Comment by zadjii-msft** [comment]
@DHowett-MSFT huh. Never considered that. Though, I don't think that'll really work, since I think those have to be integer values. When we add the pane snapping in #3181, the percentages won't be even integers anymore, we'll start getting crazy fractions.

**Comment by DHowett-MSFT** [comment]
Nah, docs say they can be weird things like `0.5*` and stuff.

**Comment by zadjii-msft** [comment]
no way. Then yea we could probably use that. Thanks for the tip!

**Comment by zadjii-msft** [comment]
Uh, it kinda looks like we already do this. Neat. Either that, or I firmly don't remember what I was talking about here. Either way:
