### ISSUE TITLE
CMD Tab Label Contains Batch File Name Forever If Batch File Has An Error

### ISSUE THREAD

**Issue by LeeThompson** [microsoft/terminal#4008]
# Environment

```none
Windows build number: 10.0.18363.535
Windows Terminal version (if applicable): 0.7.3451.0

Any other software? Batch file that terminates with an error (overflow, missing label, etc.)
```

# Steps to reproduce

Run a batch file that terminates with an error (missing label, etc.)

# Expected behavior

The Windows Terminal tab title should revert to just "cmd" instead of staying "cmd - _batchfilename_.bat"

# Actual behavior

When the batch file terminates due to an error, the Windows Terminal tab remains "cmd - _batchfilename_.bat"

I've included a sample batch file to reproduce the error:
```
@echo off
goto :wibble

```
[test.zip](https://github.com/microsoft/terminal/files/3977144/test.zip)

**Comment by zadjii-msft** [comment]
Unfortunately, this is just a part of how `cmd` works. It definitely feels like a bug, but `cmd` is parked indefinitely. Undoubtedly, there's some software out there that depends upon this (broken) behavior, and we won't be able to change this.
