### ISSUE TITLE
Make double-click at the edge select across the edge

### ISSUE THREAD

**Issue by liamness** [microsoft/terminal#4009]
# Environment

Windows build number: 19041.1
Windows Terminal version (if applicable): 0.7.3451.0

# Steps to reproduce

- You may need to configure `wordDelimiters` to equal `" \\()\"',;<>~!@#$^*|+[]{}~│"`
- Open Windows Terminal at default window width, using Ubuntu
- Run `echo 'really long string of text, really particularly long indeed, typing typing typing typing, also this url: https://example.com'`
- Double click on the URL

# Expected behavior
 

The entirety of the URL should be selected.

# Actual behavior

Depending on whether you double click on the URL before or after the line wrap, either just `https://example` or `.com` is selected.

**Comment by DHowett-MSFT** [comment]
This is a nontrivial amount of work because Terminal doesn't exactly know when a word was wrapped. I think we have another task, which would be a prerequisite of this, lying around to fix pty wrapping. Marked appropriately.

**Comment by vadimkantorov** [comment]
This is especially nasty when some long file path is wrapped, and that's exactly you want it be selected easily

**Comment by zadjii-msft** [comment]
> **Note**
> ## Walkthrough
 
I'd start by looking at `TextBuffer::_GetWordEndForSelection` in `textBuffer.cpp`. That's the code that _should_ ultimately handle double-click selection. Looks to me like that `while` loop only iterates over a single row (the `result.x < bufferSize.RightInclusive()` check). I bet there's a better way to not do that (but also not explode if the user double clicks a word that runs right up to the end of the row in the _last_ row of a totally full buffer). 

Probably possible to write tests in `TextBufferTests.cpp`, but shockingly, there aren't any selection tests in there..?

**Comment by jnm27** [comment]
This is important.

Cygwin does it, why not terminal?

Thanks.

**Comment by Detzler** [comment]
+1 for multiline selection

extremely important.
