### ISSUE TITLE
Typos in function comments? "iff" vs. "if"

### ISSUE THREAD

**Issue by jonitis** [microsoft/terminal#4010]
This question or problem report applies to the codebase, not the documentation files. I've just noticed that comments for many functions in "Return Value:" part often contains "True iff ..." or "true iff ...". Currently there are 72 such lines in 19 files. In some cases "iff" is in the middle of sentence. I suspect it is typo, since many other function comments have expected "if " e.g. "True if there was a title to output.", but I still not sure that it does not have some special meaning in automatic documentation generation from code or something like that.

If that "iff" is typo that has somehow multiplied all over codebase, are you interested in pull request to fix that? There are other typos like "dsipatch"

**Comment by zadjii-msft** [comment]
As far as "iff" is concerned - we use that as a shorthand for ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if). So those are totally intentional.


Other typos like "dsipatch" are probably unintentional. If you open a PR, we'd be happy to review those and make sure :)

**Comment by jonitis** [comment]
Ok. Thanks for clarification!

**Comment by retokromer** [comment]
indeed, “iff” is a very common shorthand (in our field)
