### ISSUE TITLE
Irrelevant Caret Browsing warning when pressing F7 on keyboard

### ISSUE THREAD

**Issue by shytikov** [microsoft/terminal#4011]
# Environment

```none
Windows build number: 10.0.18362.0 
Windows Terminal version (if applicable): 0.7.3451.0
```

# Steps to reproduce

* Open `WindowsTerminal`
* Press `F7`

# Expected behavior

Action binded to `F7` should be triggered

# Actual behavior

Irrelevant `IE` window pops up.

![image](https://user-images.githubusercontent.com/1185905/71087769-4df97e80-219d-11ea-8c09-0aa42b7f4047.png)

This is especially stupid if pressing `F7` has contextual meaning, like create folder in two-panel manager like `Far` or in any other console application. 

![image](https://user-images.githubusercontent.com/1185905/71088117-09221780-219e-11ea-867d-6f8475402c10.png)

This behavior actually blocks list of most recent commands in `cmd` too (which is core functionality):

![image](https://user-images.githubusercontent.com/1185905/71088271-569e8480-219e-11ea-9a35-4ed4167212dc.png)

Caret browsing does not make sense in this context and I don't get why we have pieces of `IE` sticking out of `terminal`...

**Comment by DHowett-MSFT** [comment]
> why we have pieces of `IE`

It's a fair question. It's partly answered in https://github.com/microsoft/terminal/issues/638#issuecomment-510999193.
