### ISSUE TITLE
How to append doskey.cmd at start of the Terminal?

### ISSUE THREAD

**Issue by DanyGee** [microsoft/terminal#4019]
# Environment

```none
Windows build number: Version 10.0.18363.535
Windows Terminal version (if applicable): Version: 0.7.3451.0

```

# Steps to reproduce
Edit the shortcut (target) of the Terminal, to launch doskey.cmd when starting the Terminal:
```
C:\Users\%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe /K C:\Windows\System32\doskey.cmd
```
(I used this trick with classic cmd and it worked)

# Expected behavior
Doskey.cmd gets loaded when Terminal starts.

# Actual behavior
Doskey.cmd isn't loaded when Terminal starts.
To make it work I have to type the command manually, then it works.
If I close the Terminal and reopen it, I have to type the command [doskey.cmd] again, to make it work.

# Question
Is there any other way to make it work automagically without manual typing?

**Comment by encladeus** [comment]
Presumably you are trying to automatically launch `doskey` for the cmd shell. If yes, try overriding the cmd shell profile and minimally define the following (paying close attention to the cmd shell GUID, it must match).
 ```
"profiles": [
    {
      // Command
      "commandline": "cmd.exe /k \"C:/Windows/System32/doskey.cmd\"",
      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    }
]
```

**Comment by DanyGee** [comment]
> Presumably you are trying to automatically launch `doskey` for the cmd shell. If yes, try overriding the cmd shell profile and minimally define the following (paying close attention to the cmd shell GUID, it must match).
> 
> ```
> "profiles": [
>    {
>      // Command
>      "commandline": "cmd.exe /k \"C:/Windows/System32/doskey.cmd\"",
>      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
>    }
> ]
> ```

Yes! Thx, it worked!
![bitmoji](https://render.bitstrips.com/v2/cpanel/b9baff8d-2774-464d-b513-c1d6be51e56c-7692d7fb-cede-4c34-947c-12129a06b524-v1.png?transparent=1&palette=1&width=246)
