### ISSUE TITLE
Feature request: dragging a file over the terminal should paste the path

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#4020]
# Description of the new feature/enhancement

So in macOS, dragging a file over the terminal prints the full path to the file. This is handy because then you can run a command using the file path. it would be nice for Windows Terminal to do this.

**Comment by zadjii-msft** [comment]
Hey thanks for the suggestion! Please make sure to search for issues before filing new ones - this ones currently being tracked in /dup #904
