### ISSUE TITLE
When typing exit (no matter the shell) in multipane, pane just stays open 

### ISSUE THREAD

**Issue by hmande** [microsoft/terminal#4030]
# Environment

**Microsoft Windows [Version 10.0.18362.535]**
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?

**pwsh 7.0.0-preview.5**

# Steps to reproduce

**run shell then type exit**

# Expected behavior

**close the pane / restart the shell** 

# Actual behavior

**stays open with exit command not ended no responds for enter key**

**Comment by DHowett-MSFT** [comment]
> Windows Terminal version (if applicable):

no version has been specified

Are you using `closeOnExit`, and is it set to `false`?

Would you mind telling us what version you're on? We've made changes in this area recently.
