### ISSUE TITLE
WSL watch tree command display abnormal

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/terminal#4033]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
```

# Steps to reproduce
wsl ubuntu
watch -n .5 tree

# Expected behavior
display correctly

# Actual behavior

![image](https://user-images.githubusercontent.com/15936231/71303285-90b39480-23f1-11ea-8642-564d0283bb18.png)
See, deleted file didn't disappear

resize window would cause it to refresh correctly
![image](https://user-images.githubusercontent.com/15936231/71303331-36ff9a00-23f2-11ea-9224-117d8b46c816.png)

**Comment by zadjii-msft** [comment]
@CGQAQ what is the output of `echo $TERM` in WSL?

It's _possible_ that this was fixed in the most recent release, since I can't repro this locally on a 10.0.19041 build.

**Comment by CGQAQ** [comment]
> @CGQAQ what is the output of `echo $TERM` in WSL?
> 
> It's _possible_ that this was fixed in the most recent release, since I can't repro this locally on a 10.0.19041 build.

sorry for replying so late, here's the output
![image](https://user-images.githubusercontent.com/15936231/71786527-5419a700-3047-11ea-906b-f1a8ea1f4b14.png)

**Comment by CGQAQ** [comment]
![a](https://user-images.githubusercontent.com/15936231/71786656-a4453900-3048-11ea-8dae-810d106d166c.gif)

**Comment by zadjii-msft** [comment]
Okay I just grabbed a `conhost.exe` from a 1903 machine, and it looks like it repros there, but not on the Insider's `conhost`. So this is already fixed in the next version of Windows, whenever that's released 😄

**Comment by CGQAQ** [comment]
> Okay I just grabbed a `conhost.exe` from a 1903 machine, and it looks like it repros there, but not on the Insider's `conhost`. So this is already fixed in the next version of Windows, whenever that's released 😄

thank you
