### ISSUE TITLE
How to add Anaconda Powershell prompt into the Windows terminal ?

### ISSUE THREAD

**Issue by BruceXSK** [microsoft/terminal#4034]

**Comment by encladeus** [comment]
This is documented in the user documentation section for 
[third party tool profiles](https://github.com/microsoft/terminal/blob/d2dcdef62019617c178818c96289ae022158f6fc/doc/user-docs/ThirdPartyToolProfiles.md), including Anaconda.

**Comment by BruceXSK** [comment]
> This is documented in the user documentation section for [third party tool profiles](https://github.com/microsoft/terminal/blob/d2dcdef62019617c178818c96289ae022158f6fc/doc/user-docs/ThirdPartyToolProfiles.md), including Anaconda.

Thank you so much!!!

**Comment by DHowett-MSFT** [comment]
@BruceXSK when your question has been answered, you are welcome to close your issue! Happy you figured it out.
