### ISSUE TITLE
Starting directory + other

### ISSUE THREAD

**Issue by ssccoouutt** [microsoft/terminal#4035]
When I set 'startingDirectory' to 'null' (to open the folders directory by Ctrl+L -> wt.exe, except the 'Run' (Win+R) option), I noticed that when I just start wt.exe (from Start Menu or taskbar), it opens in 'C:\WINDOWS\System32' directory. 
The question is how can I cause the wt open the '%USERPROFILE%' directory, both open the folder directions by Ctrl+L -> wt.exe?

**Comment by mkitzan** [comment]
This might be a duplicate of #878. @ssccoouutt, could you check that issue?

**Comment by zadjii-msft** [comment]
Yea this is definitely a dupe of #878, and there's more details in #3547 as well. Thanks!

/dupe #878
