### ISSUE TITLE
Window size and position

### ISSUE THREAD

**Issue by oomek** [microsoft/terminal#4036]
How do I set the default window size and position? I do not see anything relevant in the config fields. There is only `padding`

Update:
I found `initialCols` and `initialRows` which allow to set the default window size, but it still opens in random places on the screen.

**Comment by volkancakil** [comment]
there is an `initialPosition` config option.
we are looking for the therminal's top left corner  coordinates, calculate that point with a rough but useful simple math `(Wx - Tx.fontWidth)/2, (Wy - Ty.fontHeight)/2`
```
"globals": {
    "initialCols": 100,
    "initialRows": 30,
    "initialPosition": "510, 255"
  }
```
