### ISSUE TITLE
Rendering of colors introduces small artifact during rendering to the console

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#404]
On Linux the color boxes shown below don't have the  artifact of the very thin black lines separating each color box from each other. 

CMD.exe
![image](https://user-images.githubusercontent.com/4319522/55361456-32323900-54a5-11e9-94a6-78ccc1bcb1cc.png)

compare to running the equivalent code in bash.  
![image](https://user-images.githubusercontent.com/4319522/55362953-8d662a80-54a9-11e9-955c-3ae9563431a8.png)

**Comment by miniksa** [comment]
Both of those screenshots are of the console host window? Just the top one is CMD.exe and the bottom one is Bash via WSL to some distro? And they're both the same font?

If yes to all of the above, I am very, very curious. Can you help me understand how I can set this up locally to reproduce it? I'm not familiar with Julia. And is Crayons a default library of Julia? (i.e. if I go search for Julia and download it for Windows and run it, can I simply type what you did and reproduce it here? Same goes for if I install an ubuntu WSL and apt-get or otherwise install Julia?)

**Comment by musm** [comment]
Sorry I should've provided a lot more clarification. 
The top one uses my modified julia build to try and support VT Term sequences  (link to windows installer https://www.dropbox.com/s/w4zr2tkldz15f12/julia-a62b8ec9c6-win64.exe?dl=0)
after installing julia open it up in a cmd.exe window and run 
`julia --color=yes -E "using Pkg; Pkg.add(\"Crayons\"); using Crayons; Crayons.test_256_colors(false)"`

In WSL you can just use  https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz 
and run the exact same command

**Comment by musm** [comment]
Side by side comparison of other images where these artifacts are more obvious

![image](https://user-images.githubusercontent.com/4319522/55372765-df6e7680-54d0-11e9-9d09-2a84d4bddba0.png)

**Comment by musm** [comment]
Now I'm not sure if this is due to libuv doing some wonky thing or what not. In fact, this is the libuv patch incorporated https://github.com/JuliaLang/libuv/pull/51/files
and I modified julia as follows to use utf8 code page https://github.com/musm/julia/commit/db1c6a82233c6fef20d56d735ba832456244ddda 

The libuv patch should allow vt sequences to pass through the julia console and allow them to be rendered properly.

(FWIW I'm trying to egg on libuv devs to try and use conpty....) 


Now why exactly do I see those artifacts, that I'm not sure. It might be a bug related to conhost?

**Comment by musm** [comment]
So it seems that this is an issue due to conhost, because  all the images I have shown above that render properly are from mintty

**Comment by musm** [comment]
Interesting. Even though I'm using the same font in the comparisons. I  have noted that if I use Deja Vu Sans Mono the effects are lessened in conhost.

**Comment by miniksa** [comment]
OK, less interesting then. It's probably just the way that conhost decides to render things puts gaps between the cells somehow.

I was very interested if two different clients both hosted in conhost appeared differently.

Any chance you can tee the output from the colors command to a file for me?

**Comment by musm** [comment]
[myfile.txt](https://github.com/Microsoft/console/files/3039892/myfile.txt)

I've attached a test file above, let me know if this is what you were looking for.

It prints the 24bit color block

**Comment by miniksa** [comment]
That's good but I am specifically looking for which Unicode codepoint is being used to print the block character. It looks like you have those files printing the number of every color instead of the square block that your picture above uses.

Do you know specifically which codepoint that block is?

**Comment by musm** [comment]
I think it's  `  ██   `

**Comment by miniksa** [comment]
Ugh. U+2588 is an ambiguous width block per http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt which means it can vary per font.

Which font were you using and what size?

**Comment by musm** [comment]
Ahh I see. I was using consolas font for both comparisons, which is a bit confusing then as to why they render differently.

**Comment by miniksa** [comment]
Well, the console host window even with Consolas does some stuff to force characters into a certain cell grid. That might be getting in the way. I'm going to look into it.

**Comment by musm** [comment]
That makes more sense then. Ok great, good luck.

**Comment by musm** [comment]
Looks like this is fixed because I don't see it anymore !

**Comment by DHowett** [comment]
Wow, great find! We missed closing this one when we did #5743

**Comment by DHowett** [comment]
Thanks for following up
