### ISSUE TITLE
Low Framerate on Desktop

### ISSUE THREAD

**Issue by anonymouspornhubuser** [microsoft/terminal#4042]
My laptop perfoms very smoothy (144hz screen) and everything looks great.
But on my DESKTOP I can feel a very-low-framerate-phenomenon,what the hell was that?
Both version are 0.7.3451.0. HELP!!!!

**Comment by DHowett-MSFT** [comment]
> what the hell was that?

Thanks for this report! Please try to avoid cursing at us for no reason. This is a /dup of #649.
