### ISSUE TITLE
Application must be run from Visual Studio

### ISSUE THREAD

**Issue by dgnuff** [microsoft/terminal#4043]
This should go in the "Building and Debugging" section of the docs.  I have Terminal cloned in f:\dev\terminal, so after a debug build using PowerShell the executable is found in f:\dev\terminal\x64\Debug\WindowsTerminal.exe .

You can't directly execute this app, you have to either run it from within Visual Studio, or launch it via the Application folder found at shell:appsfolder

**Comment by mkitzan** [comment]
If you've deployed the solution (using VS), you should be able to run the application from outside VS. A deployed solution can be run by pressing the Windows button then typing `terminal`. Something like `Windows Terminal (Dev Build)` should appear in the search window.

<img width="960" alt="terminal-dev-build" src="https://user-images.githubusercontent.com/28279285/71420069-f8ebbb80-2627-11ea-9e19-33cfa1fdf6cd.png">

**Comment by dgnuff** [comment]
@mkitzan I know all those things.  I'm talking about opening a PowerShell window in f:\dev\terminal and then typing ".\x64\Debug\WindowsTerminal.exe".  For non-UWP development, this is a first time "smoke test" that is sometimes done as soon as you have a successful build.  In the case of UWP apps, that smoke test is generally going to fail, it's worth noting this for the benefit of people who are looking at this as an introduction to UWP.

**Comment by Destroyer-LDB** [comment]
Yes, me too. I installed Windows Terminal from Microsoft Store and found it in "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe". However, an error occurred saying I can't visit this program.
