### ISSUE TITLE
Terminal doesn’t support audible bell (BEL, 0x7)

### ISSUE THREAD

**Issue by bsld** [microsoft/terminal#4046]
# Environment

Microsoft Windows [Version 10.0.19030.1]

Windows Terminal 0.7.3451.0

# Steps to reproduce

echo Ctrl+G

# Expected behavior

A beep

# Actual behavior

Silent

**Comment by DHowett-MSFT** [comment]
I thought we had a duplicate for this, but it looks like we don’t. We had #2952, but that was tracking the pseudoconsole infrastructure for bell support.

**Comment by DHowett-MSFT** [comment]
This will land after #780.

**Comment by ffes** [comment]
Probably related to #2360

**Comment by angelog0** [comment]
When is the BELL/Beep scheduled for? Initially it was planned for version 1.0.. or not?

**Comment by sebimoe** [comment]
I'm having issue described in #6568 in v1.19.11213.0

Is the bell supposed to be playing Critical Stop sound?

**Comment by j4james** [comment]
@sebimoe You can configure the bell sound in the settings.json file. See PR #11511.
