### ISSUE TITLE
OperatorColor and ParameterColor are same color as background on Solarized Dark

### ISSUE THREAD

**Issue by duckness** [microsoft/terminal#4047]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3451.0

Any other software?
```

# Steps to reproduce

Leaving other settings as default, set on the profile: `"colorScheme": "Solarized Dark"`

# Expected behavior

Text is not the same color as the background.

# Actual behavior

`OperatorColor` and `ParameterColor` are same color as background
![WindowsTerminal_7iJtSJmZkh](https://user-images.githubusercontent.com/6380270/71335214-97224780-257c-11ea-8d1b-50fc22729fa0.png)

**Comment by j4james** [comment]
That's just the way the _Solarized Dark_ color scheme is setup. The default background color is set to "bright black" rather than "black", so if the foreground is set to "bright black", it's going to invisible. Frankly it's just not a good color scheme for a terminal.

**Comment by duckness** [comment]
> That's just the way the Solarized Dark color scheme is setup.

I see. What is the intent/reason that it is set up in this manner? I have not had issues using this theme in other terminals.

**Comment by j4james** [comment]
My understanding is the _Solarized_ scheme was originally designed for syntax highlighting, and it doesn't have the right range of colors for a terminal color scheme. Trying to use that exact same palette just doesn't map very well to terminal colors, and no mapping of that sort will ever be sensible (although the "official" one seems particularly bad IMHO).

As for why you may not have this problem in other terminals, it's likely they just aren't using the official _Solarized_ colors. Conemu, for example, has four variations of the _Solarized_ scheme, none of why match the official colors. So if there is some version of the scheme that you like in another terminal, I'd recommend you just convert those values into an equivalent Windows Terminal scheme.

**Comment by DHowett-MSFT** [comment]
Looks like this has been answered. Thanks everyone!

**Comment by gavinbeatty** [comment]
The provided Solarized Dark color scheme is unusable. I just wrote a long ffmpeg command and I absolutely *needed* to use a different scheme in order to fix a minor issue (`-metadata:s:a:0 language=eng` must be quoted as `"-metadata:s:a:0" language=eng` in powershell).

If the advice is for users to substitute their own scheme, I strongly recommend removing the default Solarized Dark scheme. Anyone using it is going to have a bad time, and by extension, have a bad time using Windows Terminal.

**Comment by M-Pixel** [comment]
This is still an issue, it should not be closed.  It is closely related to #6390 which is still open.

The Solarized Dark theme that is included with the current version of Terminal defines `brightBlack` and `background` as the same color ([source](https://github.com/microsoft/terminal/blob/c1076a823d45f7c8b5e893fd8684f3947ea418ce/src/cascadia/TerminalApp/defaults.json#L198)).  `brightBlack` maps to `[ConsoleColor]::DarkGray`, which is the default color for Parameters in PowerShell 6.

In all _other_ color schemes defined in `defaults.json`, `black` and `background` are set to the same values, while `brightBlack` is lighter than `black`; Solarized Dark is an anomaly in this regard.  Unless somebody can justify this anomaly, it should be seen as a flaw that needs fixing.

The following steps reproduce the issue:
- Install the latest version of Terminal from the Windows Store
- Change the color scheme for PowerShell to Solarized Dark

Expected:  I can enter a basic PowerShell command that uses flags, and see the text that I type.

Actual:  Flag text is the same color as the background, and therefore cannot be seen unless it is highlighted.
