### ISSUE TITLE
The one thing that keeps me away from using it

### ISSUE THREAD

**Issue by mrwnmonm** [microsoft/terminal#4049]
If you have the taskbar auto-hidden, and you are in the terminal (Maximized), the taskbar won't show up when you move the mouse at the bottom of the screen. 

This happens for all versions.

**Comment by j4james** [comment]
This is a duplicate of #1438.

**Comment by zadjii-msft** [comment]
@j4james thanks for the early triage finding the dupe for this!

/dup #1438
