### ISSUE TITLE
ClosePseudoConsole() leaves lingering conhost.exe processes

### ISSUE THREAD

**Issue by krayon007** [microsoft/terminal#4050]
# Environment

```none
Windows build number: 10.0.18362.535
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Create PseudoConsole. then associate it with child process (cmd.exe).
Spawn thread to read the output pipe.
At this point, everything about the PseudoConsole appears to work fine. However, when you call ClosePseudoConsole() on the PsuedoConsole handle, it correctly closes the child process, however conhost.exe lingers until the parent process is terminated... If you do this dozens of times, there will be dozens of conhost.exe processes running. 

When the child process is terminated, by ClosePseudoConsole(), it does not break the communication pipe. (ie ReadFile does not return). When the process handle  for cmd.exe is signaled, I called CancelIoEx() on the pipes, then closed the pipes. This does not seem to have any effect on cleaning up the conhost.exe processes that are lingering. If I spawn dozens of PseudoConsoles in this fashion, and close them in this fashion, only the cmd.exe processes are destroyed. There are still dozens of conhost.exe processes lingering, until the parent process is terminated.

# Expected behavior

When calling ClosePseudoConsole(), I expected either a final data frame to be received on the pipe, or the pipe to break when the child process exits. I also expected the conhost.exe process to be destroyed along side the cmd.exe process.

# Actual behavior

When calling ClosePseudoConsole(), the cmd.exe process is cleaned up, but the conhost.exe process stays resident until the parent process is terminated.

**Comment by miniksa** [comment]
This is going to be related to #1810.
