### ISSUE TITLE
Ctrl+Shift+6 conflict with vim

### ISSUE THREAD

**Issue by evakili** [microsoft/terminal#4053]
Ctrl+Shift+6 (a.ka. Ctrl+^) is a nice shortcut in Vim that switches to previous buffer. But it opens the sixth terminal in Terminal.

**Comment by thisguychris** [comment]
@evakili you can unbind them using this
```json
{
    "command" : null,
    "keys" : 
    [
        "ctrl+6"
    ]
},
```

**Comment by zadjii-msft** [comment]
@thisguychris is correct - if there's ever a keybinding that you're unhappy with, you're feel free to rebind or unbind it. Thanks!

**Comment by evakili** [comment]
Tnx

**Comment by dliakh** [comment]
Is there (or rather would that be possible to add) an "escape sequence" to _temporarily_ stop the Terminal from capturing keyboard input and interpreting it as action request sequences but rather sending those sequences right to the application ? (in this case, vim)
