### ISSUE TITLE
OpenSSH won't change the tab title after connecting remote while telnet has.

### ISSUE THREAD

**Issue by aioliahexi** [microsoft/terminal#4054]
# Description of the new feature/enhancement
When I use openSSH to connect to a batch of remote servers on Windows Terminal, the tab titles share the same name **OpenSSH SSH client**, it's hard to navigate the bash. If I use telnet to connect to a remote server, the tab name will switch to the remote server IP address. When I quit from the telnet,  the title will toggle back to **Windows PowerShell** again.  

I do believe it's a smarter idea to keep them consistent.

**Comment by DHowett-MSFT** [comment]
This is because the remote shell is not setting a title. OpenSSH for Windows has full support for changing the title.
