### ISSUE TITLE
Need a executable .exe file in a stable folder .

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#4055]
# Description of the new feature/enhancement

I am using a application launcher `Listary` , click `ctrl` twice , type  a keyword , it would open the keyword related software . 

But, terminal doesn't have a executable file, I search for windowsterminal.exe got below which can't be open :
![image](https://user-images.githubusercontent.com/3938751/71432865-0469e000-2717-11ea-86f4-da9bf066b79b.png)

I need a stable path of executable  .exe file so that I can set a keyword to quick open windows terminal in an app launcher.

**Comment by DHowett-MSFT** [comment]
`wt.exe` is an execution alias and it is always in a stable location.
