### ISSUE TITLE
Using tab completion with wide characters causes incorrect display in Terminal

### ISSUE THREAD

**Issue by Long-Tu** [microsoft/terminal#4056]
### 1、使用 tab 键补全会出现显示文字变小（原因未知）
![image](https://user-images.githubusercontent.com/37840939/71436466-8f070b00-2728-11ea-8527-ea7b91b7584b.png)

### 2、使用tab键补全会出现信息显示遮挡及移位问题。

![image](https://user-images.githubusercontent.com/37840939/71438853-4bb19a00-2732-11ea-9850-07768307b058.png)
>terminal中使用 vim 打开新文档，使用 tab 补全功能，多次点击 tab 键会出现文件夹中多个文档重复出现在页面问题

![image](https://user-images.githubusercontent.com/37840939/71436466-8f070b00-2728-11ea-8527-ea7b91b7584b.png)
>terminal中使用 vim 打开新文档，使用 tab 补全功能，上一次文件名称比新文件名长时，会显示部分上次文件名。

**Comment by ZhaoMJ** [comment]
Translation: 
Title: Using tab completion causes incorrect display in Terminal

使用 tab 键输入补全功能时，出现上次输入信息遮挡新信息显示问题
When using tab completion, (there's a problem that) the old text and the newly entered text are overlapping. 
1、使用 tab 键补全会出现显示文字变小（原因未知）
1. Tab completion causes the displayed text getting smaller (for some reason)
2、使用tab键补全会出现信息显示遮挡及移位问题。
2. Tab completion causes text overlapping and shift position
terminal中使用 vim 打开新文档，使用 tab 补全功能，多次点击 tab 键会出现文件夹中多个文档重复出现在页面问题
When using vim to open a new document and using tab completion, if you type Tab key for many times, there will be multiple files in the folder showed up on the screen.
terminal中使用 vim 打开新文档，使用 tab 补全功能，上一次文件名称比新文件名长时，会显示部分上次文件名。
When using vim to open a new document and using tab completion, if the file opened last time has a longer filename than the new one, then part of the old filename will be displayed.

**Comment by DHowett-MSFT** [comment]
I think this is actually a /dupe of #696
