### ISSUE TITLE
Borders of panes are improperly updated when closing a pane

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#4057]
Simplest possible repro way: 
1. Split pane two times
2. Close left-most pane

Effect: Right pane doesn't have any border, although it touches other pane (btw, this is also the repo for #3744).

This is because a `remainingPane` always clears the border that it got from split, even if it is still needed. 
I've actually fixed this in my upcoming PR, I'm only filling this issue so I can mark it as closed ;)

**Comment by zadjii-msft** [comment]
Hey this was fixed in 1.17. I _bet_ is was fixed when support for selecting parent panes was added a couple releases ago.
