### ISSUE TITLE
Windows terminal launched with admin rights crashes while dragging a tab

### ISSUE THREAD

**Issue by oclaw** [microsoft/terminal#4059]
# Environment

```
Windows 10 1909
Windows build number: 18363.535
Windows Terminal version: 0.7.3451.0
```

# Steps to reproduce
1. Launch Windows Terminal with admin rights.
2. Try to drag opened tab.

# Expected behavior
Tab is dragged 

# Actual behavior
Windows terminal crashes

**Comment by electronic-dk** [comment]
Looks like a dupe of https://github.com/microsoft/terminal/issues/3581

**Comment by DHowett-MSFT** [comment]
Yep! Thanks. /dup #3581
