### ISSUE TITLE
Profile default settings not supported even though valid against schema

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/terminal#4060]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3451.0
```

# Steps to reproduce

1. Open profiles.json
2. Change profile settings so it has the following structure:
```
"profiles": {
	"defaults": {
		"acrylicOpacity": 0.95,
		"colorScheme": "Campbell",
		"cursorColor": "#FFFFFF",
		"fontFace": "Cascadia Code PL",
		"fontSize": 11,
		"historySize": 9001,
		"padding": "5, 0, 0, 0",
		"useAcrylic": true
	},
	"list": [
		{
			"name": "Windows PowerShell",
			"guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
			"commandline": "powershell.exe"
		},
		{
			"name": "cmd",
			"guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
			"commandline": "cmd.exe"
		}
}
```
3. Restart the Windows Terminal

# Expected behavior

Windows Terminal starts and applies the settings correctly, using the ones in "defaults" for every profile and the ones in each item of "list" for the specific profile.

# Actual behavior

Windows Terminal shows an error dialog with the following message:
```
Settings could not be loaded from file. Check for syntax errors, including trailing commas.

Temporarily using the Windows Terminal default settings.
```

I checked the `profiles.json` schema and it seems to be correct, even though Terminal app doesn't parse/identify them correctly. There's this "variable" on my profiles file:
```
"$schema": "https://aka.ms/terminal-profiles-schema"
```

Already checked for trailing commas and any syntax errors, everything seems correct. Also, I did comment out the `defaults` and `list` tags, reverting the `profiles.json` to an array, therefore having duplicated settings on each profile (like it used to be on first releases) and it works fine then.

**Comment by DHowett-MSFT** [comment]
This schema update was made in anticipation of the upcoming 0.8 release. It’s fair feedback, however, that our schema tracking master will prove to be somewhat annoying until we stop adding new features.

**Comment by ChristoferK** [comment]
@brunovieira97, your `"list"` array doesn't have a closing `]`.
