### ISSUE TITLE
Incorrect behavior when on fullscreen from maximized window

### ISSUE THREAD

**Issue by denisdifazio** [microsoft/terminal#4064]
Sorry if this issue has already been posted. I couldn't find anything related.

# Environment

```none
Windows build number: Microsoft Windows Version 10.0.18362.535
Windows Terminal version: 0.7.3451.0
```
# Steps to reproduce

- open terminal
- maximize window (alt+space+x)
- toggle fullscreen (alt+enter)

# Expected behavior

- taskbar hidden
- window correctly displaying terminal's content

![normal_screen](https://user-images.githubusercontent.com/11673757/71478344-d85d6600-27cd-11ea-969a-83757bb1cb06.png)

# Actual behavior

- taskbar showing
- distorted content displayed on terminal

![incorrect_screen](https://user-images.githubusercontent.com/11673757/71478421-4bff7300-27ce-11ea-88db-495ce9ec5c0b.png)

This only happens when toggling fullscreen from a maximized terminal window

**Comment by zadjii-msft** [comment]
I believe this is a /dup of #3709, which was fixed by #3721. Thanks for the report!
