### ISSUE TITLE
copy, cut, pasting

### ISSUE THREAD

**Issue by jku209** [microsoft/terminal#4065]
Copy, cut, pasting is a total pain. I can't get the test to copy off the terminal or past on to the terminal to execute commands. With the old CMD there wasn't an issue, I could right click on the top of the window and select an option or enter to copy. There doesn't seem to be an to use control keys.  Enter just does nothing. Please let me know if im just doing it wrong.

**Comment by mkitzan** [comment]
It's unclear what the exact issue is here. Could you list you copy-paste process in a bulleted list. Something like:
- Select text to copy in WT
- Hit <kbd>Ctrl+C</kbd>
- Change tab in WT, and make sue cursor is active
- Hit <kbd>Ctrl+V</kbd>

**Comment by pmiddleton** [comment]
I am having issues as well with copy paste. 

I highlight some text I want to copy with the mouse.  I then press ctrl+c to copy the text, but instead of copying the selected text a SIGINT is sent to the window.

This happens in both powershell and cmd windows.

I am runnning the latest build from the windows store on windows 10 build 10.0.18363.535

**Comment by mkitzan** [comment]
@pmiddleton to get copy-paste to work try adding these lines to the `keybindings` section of `profiles.json`:
```
{ "command": "paste", "keys": ["ctrl+v"]},
{ "command": "copy", "keys": ["ctrl+c"] },
```
If there's no `keybindings` section, just add this whole block after the `profiles` json section:
```
"keybindings":
[
{ "command": "paste", "keys": ["ctrl+v"]},
{ "command": "copy", "keys": ["ctrl+c"] }
]
```

**Comment by jku209** [comment]
This works. Thank you this can be closed.

**Comment by pmiddleton** [comment]
That works.  Thank you.

**Comment by mkitzan** [comment]
Glad it works, happy to help.
