### ISSUE TITLE
Selection Issue

### ISSUE THREAD

**Issue by satyampathak223** [microsoft/terminal#4069]
Keyboard shortcut used for highlighting text for selection  ( SHIFT + ←,→,↑,↓ ) behaving 
unexpectedly .
Shift +↑  produces A
Shift +↓  produces B
Shift +→ produces C
Shift +←  produces D

Windows Version 1909 (OS Build 18363.535 )
Windows Terminal (Preview) Version:  0.7.3451.0

**Comment by DHowett-MSFT** [comment]
This may be a /dupe of #715
