### ISSUE TITLE
Shell prompt repeating when using ssh in terminal

### ISSUE THREAD

**Issue by micrat** [microsoft/terminal#407]
Hello, a small bug in **ssh** under the cmd terminal.
If I open a file (for instance "vi .bashrc"), on exit the prompt displays incorrectly (repeats twice).

This happens only on the windows cmd ssh (left panel in the figure herebelow, evidenced in red). 
The WSL console (right panel) behaves correctly. (My windows version in the left panel)
![ssh1](https://user-images.githubusercontent.com/15943390/55887017-10276d80-5bad-11e9-9179-c2e93d0862f4.png)

**Comment by DHowett-MSFT** [comment]
This is almost certainly related to https://github.com/PowerShell/Win32-OpenSSH/issues/1253.

**Comment by flyingdutchman** [comment]
This has been marked as fixed in the PowerShell project but I still have this issue. Any ideas ?

**Comment by DHowett** [comment]
This is going to sound like a repeated comment, but:

Depends. Are you using the bundled 7.7 version of SSH that comes with Windows?

**Comment by o-sdn-o** [comment]
> This has been marked as fixed in the PowerShell project but I still have this issue. Any ideas ?

This might be fixed in https://github.com/PowerShell/openssh-portable/pull/806
