### ISSUE TITLE
WSL terminal - more command - navigation with space, b, q does not work

### ISSUE THREAD

**Issue by eliranwong** [microsoft/terminal#4070]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

open Winodws Terminal (Preview)
open a WSL terminal
cat [a text file] | more

navigation with keys "space", "b", or "q" does not work

# Expected behavior

# Actual behavior

**Comment by eliranwong** [comment]
don't know why.  after a restart of Windows, keys "space" and "q" work with command "more", but key "b" is till not working.

**Comment by DHowett-MSFT** [comment]
As far as I am aware, _more_ doesn’t support `b`, only space and `q`. You may want to use _less_ if you need support for scrolling backwards in history?

**Comment by DHowett-MSFT** [comment]
Does this work in a normal WSL window (outside of Windows Terminal)?

**Comment by eliranwong** [comment]
@DHowett-MSFT thanks for reply.

"b" is on man page of "more".  I just tried in a normal WSL window.  It does not work.  It is not a big problem to me, I will use "less" instead.  What strange was that on first launch after I installed Windows Terminal, even "space" and "q" does not work with both "man" and "more" command.

The issue disappear now after a restart, though I am not sure if it relates to the restart.

**Comment by j4james** [comment]
From the man page:
>b or ^B   Skip backwards k screenfuls of text.  Defaults to 1.
   Only works with files, not pipes.

Note the last bit. If you want to be able to skip backwards, you can't pipe the output from `cat` into `more` - you need to open the file directly, e.g. `more filename.txt`

**Comment by DHowett-MSFT** [comment]
A-ha!
