### ISSUE TITLE
support shift+left, shift+right in wsl terminal

### ISSUE THREAD

**Issue by stleusc** [microsoft/terminal#4071]
# Description of the new feature/enhancement

Most if not all text editors allow shift+left, right and shift+ctrl+left, right to select character/word to then further copy it. Opening PowerShell in the new terminal actually does exactly that!
Opening Cmd acts as if only left/right were pressed.
Ubuntu WSL2 prints C/D.

# Proposed technical implementation details (optional)

Add support for these very common shortcuts or provide guidance why powershell does work and the rest does not

Sidenote: Love what I see so far!

**Comment by DHowett-MSFT** [comment]
This is something you’ll have to configure with your shell. If you’re using bash, look into `bindkey` and `.inputrc`.

As a general rule: if powershell can do it inside Windows Terminal, so could another shell.

**Comment by riverar** [comment]
@DHowett Can you provide some guidance here? What do users need to put into `.inputrc`?

**Comment by myudak** [comment]
so is there any solution? install another shell?
