### ISSUE TITLE
Unable to view Unicode on CMD or PowerShell

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#4074]
I do have a `Centos 7` server which i access it via `CMD` or `PowerShell`.

But it's displaying the Unicode characters as `?`

[![enter image description here][1]][1]

But if i accessed it via `putty` it's displayed correctly.

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/nju1p.png
  [2]: https://i.stack.imgur.com/sIaHV.png

**Comment by j4james** [comment]
See issue #190.

**Comment by DHowett-MSFT** [comment]
Yep, this is a /dupe of #190. Thanks!
