### ISSUE TITLE
Splitting Terminal

### ISSUE THREAD

**Issue by Fernien** [microsoft/terminal#4075]
# Description of the new feature/enhancement

Sometimes it is necessary/pretty helpful to see multiple terminals at once. It would be nice to be able to split the Terminal horizontally and vertically to see multiple shells at once. 

# Proposed technical implementation details (optional)

Right click in the current terminal window, then have 2 new options in the dropdown "split horizontally" and "split vertically". When you press on of these buttons it will open another shell of the same type. Basically like the Terminator app on Ubuntu.

**Comment by gmsantos** [comment]
You can use Alt Shift - (minus)

https://www.bleepingcomputer.com/news/microsoft/microsoft-adds-split-panes-feature-to-windows-terminal-v07/

**Comment by Fernien** [comment]
Thanks, i didn't know that. Would be nice if you could do it with right click as well.

**Comment by gmsantos** [comment]
Yes, it is considered in https://github.com/microsoft/terminal/issues/1000#issuecomment-562674537

**Comment by DHowett-MSFT** [comment]
Looks like this one is already covered. Thanks.
