### ISSUE TITLE
arcanist with PHP in GitBash tab shows extra characters but not other tabs

### ISSUE THREAD

**Issue by briannipper** [microsoft/terminal#4076]
- Laptop Manufacture: **ASUS**
- Laptop Model: **K501UW**
- CPU Arch: **x64**
- RAM: **16 GB**
- Disk: **SSD 500 GB (Primary Drive for OS and Apps)**
- OS: **Windows**
- OS Version: **Microsoft Windows 10.0.18362**
- Windows Terminal Info: **Windows Terminal (Preview)**
- Windows Terminal Version: **Version: 0.7.3451.0**

The profile for the tabs I'm including in this bug report are:
- GitBash for WIndows 
- PowerShell Core

In both of these terminals, as shown in the screen shots I've used an app that is part of my path namely [arcanist](https://github.com/phacility/arcanist)

As you can see, in the GitBash tab when I've run the command to "arc diff" the results include extra characters such as <-[44m or <-[1m

I've looked into the code of the arcanist CLI and it's using a version of PHP that runs on windows.

In futher testing, the GitBash for Windows running OUTSIDE of the windows terminal does NOT show these extra characters.

Not all lines from the arc commands include these lines. I've modified the source locally and it seems to be related to how PHP is interacting with the terminal output by attempting to create specific text to indicate how the text should be formatted in columns or with types of text.

The same command in the PS Core tab does NOT show these extra characters.

Any assistance with this would be greatly appreciated.

![BashGit_Windows_Terminal_Extra_Text](https://user-images.githubusercontent.com/361720/71563235-1ff82200-2a5a-11ea-8f66-8aa5e3bb0b82.jpg)
__removed any sensitive info__

![PSCore_Windows_Terminal_NO_Extra_Text](https://user-images.githubusercontent.com/361720/71563236-1ff82200-2a5a-11ea-8d2c-b467bd7c3f27.jpg)
__removed any sensitive info__

**Comment by zadjii-msft** [comment]
`←[` is a telltale sign that the application in question is trying to use VT Escape Sequences to format the text - in this case, colorize the text. My guess is that the application in question isn't setting [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`](https://docs.microsoft.com/en-us/windows/console/setconsolemode) to enable support for VT. 

Curious that it's "working" in PS Core but not mingw - is the `arc` that's being run in both mingw and PS core the same? 

Maybe something in the `arc` stack is trying to use the terminfo to format the text appropriately. In gitbash, the `TERM` env var would be set, but probably not in PS Core. Though, I bet mingw isn't blanket enabling VT processing for all child processes

**Comment by briannipper** [comment]
Thanks for following up.

The arc command is in fact the "same" arc in both mingw and PS Core. I have arcanist installed on my machine which basically means I have the directory that houses the arcanist application on my path so from any command window I'm able to issue arc commands.

If I can make any adjustments to mingw to attempt to address I'm happy to give it a shot.

**Comment by DHowett-MSFT** [comment]
This does look like an msys/mingw/cygwin runtime issue in that it's not turning on `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. The escape codes aren't even being printed in the PSCore example because, as @zadjii-msft says, msys is setting `TERM` where PSCore is not.

**Comment by DHowett-MSFT** [comment]
Resolving this one as (unfortunately) external.

**Comment by briannipper** [comment]
Just wanted to say thank you to those that responded to this thread.
