### ISSUE TITLE
Can't copy

### ISSUE THREAD

**Issue by xitieshiz** [microsoft/terminal#4078]
ctrl+c not work!

**Comment by zadjii-msft** [comment]
Nope, sure doesn't. The default keybinding for copy is <kbd>Ctrl+Shift+C</kbd>, as we've discussed in many other threads. If you want to bind <kbd>Ctrl+C</kbd> as `copy`, you can do so by following [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#adding-copy-and-paste-keybindings)
