### ISSUE TITLE
terminal output freezes on click

### ISSUE THREAD

**Issue by kunwon1** [microsoft/terminal#408]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt) 10.0.17134.648

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots) Tailing a log file, the screen is continuously scrolling, I click on the terminal window and output freezes until ESC is pressed

* What's wrong / what should be happening instead: Output should continue regardless of clicking on the terminal window

I see this issue that was closed, it references this repo, but I cannot find a corresponding issue
https://github.com/Microsoft/WSL/issues/1223

**Comment by zadjii-msft** [comment]
You're right, this was closed in the WSL repo without creating a matching issue in this repo. 

As stated in the original issue, this is a feature request for the console that's on the backlog.

**Comment by HBelusca** [comment]
Is this happening because QuickEdit mode (in the console Properties dialog) was enabled?

**Comment by jcoutch** [comment]
This is the same behavior as the current ConHost in Windows.  If you click inside the window, it assumes you're attempting to select text, highlights a single character, and pauses execution of whatever process is in that window.

I can't tell you how much time I've wasted trying to debug applications running in a console window, getting mad at why it's not responding, just to find out I had one character selected in the terminal that was halting it's execution.  😭

**Comment by HBelusca** [comment]
> I can't tell you how much time I've wasted trying to debug applications running in a console window, getting mad at why it's not responding, just to find out I had one character selected in the terminal that was halting it's execution.

Usually said console window prepends "Select " or "Mark " in front of its title.
I note that it's not done by the new windows-terminal.

**Comment by miniksa** [comment]
This is how conhost is supposed to work. Resolving.

**Comment by kunwon1** [comment]
Does this text from the referenced issue no longer apply? Are there no longer plans to make this a configurable option?

> We tried disabling it once on internal builds and were nearly overrun by angry engineers with pitchforks and burning torches! We do, however, hear you and agree that it should be a configurable behavior, and so have added this ask to our internal feature tracking system and will consider implementing in a future build.

https://github.com/Microsoft/WSL/issues/1223#issuecomment-391165898

**Comment by jcoutch** [comment]
I'm also pretty sure the behavior of Terminal is inconsistent with the existing console in Windows.  For example, if the window is un-focused, a single click on the console **does not** initiate select/mark.  It only initiates select/mark when clicked while the window is focused.  When I tried out Terminal a couple weeks ago, it was marking regardless of the windows current focus state.

**Comment by zadjii-msft** [comment]
This issue is closed because it was promarily tracking the feature in the legacy conhost.exe. Since we're not planning on making this configurable in conhost.exe, we closed the issue. We do however plan on making it configurable in the Windows Terminal. I've moved that discussion to #980
