### ISSUE TITLE
Windows terminal使用vim打开文件鼠标上下滚动会出现terminal页面滚动，而不是vim编辑文档内容滚动

### ISSUE THREAD

**Issue by Long-Tu** [microsoft/terminal#4087]
##  Windows terminal使用vim打开文件鼠标上下滚动会出现terminal页面滚动，而不是vim编辑文档内容滚动
![image](https://user-images.githubusercontent.com/37840939/71608208-6a90b000-2bba-11ea-8d7b-5c763c722b27.png)

**Comment by j4james** [comment]
Just based on the images, and a machine translation of the text, I suspect this is the same issue as described in #4088. And as I mentioned there, I think it's a dup of #381.

**Comment by DHowett-MSFT** [comment]
Yep! Thanks @j4james. /dup #381.
