### ISSUE TITLE
Interface error when used with wim

### ISSUE THREAD

**Issue by dovankhai** [microsoft/terminal#4088]
<img width="960" alt="s" src="https://user-images.githubusercontent.com/24471733/71608852-b9d4e180-2bb6-11ea-8c24-1255a4924b50.png">

I use " cat file"
After "vim file"
I use the mouse wheel to drag the interface as shown above

I use ubuntu 16.04
Windows Terminal (Preview)
Version: 0.7.3451.0

**Comment by j4james** [comment]
I believe this is because conpty doesn't pass through the alt buffer state, so the terminal doesn't know that it should disable mouse scrolling outside the viewport area. This is probably a dup of #381.

**Comment by DHowett-MSFT** [comment]
Yep! Thanks @j4james. /dup #381.
