### ISSUE TITLE
Ubuntu Default Purple Theme

### ISSUE THREAD

**Issue by jainsamyak** [microsoft/terminal#4090]
# Description of the new feature/enhancement
Add a default ubuntu Ambiance theme to WSL

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
You can quite easily make your own themes, just by adding a new entry in the _schemes_ section of the settings file (see the [settings documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#color-schemes) for more details).

I don't know what the official Ubuntu Ambiance colors are, but below is an example of a purple Ubuntu color scheme, which I copied from the iterm theme here: https://iterm2colorschemes.com/

```
{
    "name": "Ubuntu",
    "foreground": "#EEEEEC",
    "background": "#300A24",
    "black": "#2E3436",
    "blue": "#3465A4",
    "green": "#4E9A06",
    "cyan": "#06989A",
    "red": "#CC0000",
    "purple": "#75507B",
    "yellow": "#C4A000",
    "white": "#D3D7CF",
    "brightBlack": "#555753",
    "brightBlue": "#729FCF",
    "brightGreen": "#8AE234",
    "brightCyan": "#34E2E2",
    "brightRed": "#EF2929",
    "brightPurple": "#AD7FA8",
    "brightYellow": "#FCE94F",
    "brightWhite": "#EEEEEC"
}
```

**Comment by jainsamyak** [comment]
Thanks for the quick response, I've already added this theme to my terminal. Just thought it would be good if the terminal shipped with it by default for the Ubuntu WSL extension.
Thanks again!
