### ISSUE TITLE
`profile.colorTable` is broken

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#4091]
Setting a `colorTable` in a profile was broken in microsoft/terminal@8ba8f35dc5 when we set the default `_schemeName` to `Campbell`. During the construction of a `TerminalSettings`, we apply the table and _then_ the scheme. If we do it in a different order, or delete `_schemeName` when we find `colorTable`, it works fine.

_However:_ nobody noticed. This is the perfect opportunity to _kill that feature_ or _replace it with "`colorTable` overlays on top of the scheme"_!

Related: #1069.

**Comment by mhintzke** [comment]
@DHowett-MSFT I just tried to customize my `colorTable` and noticed none of my changes took effect. Finally tracked down this issue. Do you know of a work around for now by any chance or are we out of luck and forced to just use a `colorScheme` for now?

**Comment by DHowett-MSFT** [comment]
Consensus among the team is that color schemes are better suited to this purpose: we never implemented individual color index overriding for tables overlaid on schemes, which would have been the only way to make them broadly useful.

If you don’t mind my asking, why might you prefer setting the color table in the profile over having a color scheme?

**Comment by mhintzke** [comment]
It is very possible that a scheme is what I'm after. I tried out a couple of the out-of-box ones like "One Half Dark" and "Solarized Dark", but there were minor tweaks I wanted to make as my `oh-my-posh` theme was causing some low contrast points for me that were hard look at.  It is possible I am just not aware of how to use the Color Schemes properly.

I tried playing around with the `profile.json` a little, but the tooltip hints weren't enough for me to figure it out. Is there specific documentation on how to customize your own color scheme within this repository?

**Comment by mhintzke** [comment]
Ok I have found a pretty easy path towards installing a bunch more color schemes. I'm not sure if I am just missing this documentation somewhere, but for any future people that are having an issue installing their own custom scheme here is what you do:

1. From the Windows Terminal, open up Settings which will open up your `profiles.json`
2. Find a Windows Terminal scheme from the [iTerm2 github](https://github.com/mbadolato/iTerm2-Color-Schemes) and then find it in the [Windows Terminal folder here](https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/windowsterminal)
3. Copy the JSON in the theme you want to try and paste it into the `"schemes": []` property inside the `profiles.json` you opened up in step 1
4. Go up in the `profiles.json` and find the shell profile of the one you want to change (I changed PowerShell Core) and set the `"colorScheme"` to the name of the scheme you just pasted on step 3.

Voila!

@DHowett please let me know if there is some other documentation I can point to that already states this information. It would be great if there were instructions on how to do this in the root level README.md of this repository, no?
