### ISSUE TITLE
Unusual behavior when navigating 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/terminal#4094]
I'm using Terminal Version: 0.7.3451.0 and I'm experiencing an issue whereas when starting a command (DOS) program in Windows Terminal, unlike the native shell which comes with Windows. When navigating though the menus, instead navigating though the files, I experience the following; whereas, up continues to go down and among other unusual behavior.

![terminalnavigation](https://user-images.githubusercontent.com/6827459/71643580-88791600-2c89-11ea-8156-d1043bedf9e0.gif)

**Comment by zadjii-msft** [comment]
@SheepDomination What tool is that? It would be easier to investigate if I could repro this on my end 😝

**Comment by SheepDomination** [comment]
@zadjii-msft It is a native tool available in a program I use, you want me to send you the small program ?

**Comment by zadjii-msft** [comment]
Sure? A link to the tool would probably be good enough too.

Out of curiosity, does this repro if you run the program after running `cmd.exe` from within WSL?

**Comment by SheepDomination** [comment]
@zadjii-msft Are you saying, if I run the program in WSL after running command (`cmd.exe`) do I experience the same problem, if so; yes.  Can I send you the file as a PM ?

**Comment by DHowett-MSFT** [comment]
Does this tool have a name? Is it available somewhere online? We're somewhat averse to running EXEs from folks on the internet -- sorry!

**Comment by SheepDomination** [comment]
@DHowett-MSFT @zadjii-msft It is part of a software program from SideFX, I thought it would be easier that I send one executable rather then you having to install the entire program; the executable is from a legitimate source.

**Comment by zadjii-msft** [comment]
@SheepDomination There's 0% chance I'm going to run a binary from a stranger on the internet like this, sorry. I'd rather install the entire SideFX from the source than do that. Which tool from the install is the one that's causing the issue?

**Comment by SheepDomination** [comment]
@zadjii-msft @DHowett-MSFT 
The tool is called `spy.exe` it's the program from a company called SideFX (Houdini) the executable is located within the `bin` folder when installed on Windows.

**Comment by zadjii-msft** [comment]
Hey sorry for letting this fester for so long. 

It's been something like 20 releases of the Terminal since this was originally filed - any chance it was fixed in the meantime? Looks like [that tool needs to be purchased](https://www.sidefx.com/download/) to be downloaded, which will greatly reduce my ability to investigate it 😉
