### ISSUE TITLE
Not Launching - Windows Store App

### ISSUE THREAD

**Issue by CaptainMorgans** [microsoft/terminal#4096]
I’m running Windows 10 Home build 1909. After installing the application from the Windows Store, it will not launch. P.S. Does the app installation require a reboot before launching successfully? Any other suggestions?

Device Specs: 
Processor:	Intel Core i5-4210U
RAM:		16GB
System Type:	64-bit operating system, x64-based processor

Windows Specs:
Edition:	        Windows 10 Home
Version:	        1909
Installed on:	2019/12/18
OS build:	        18363.535

**Comment by CaptainMorgans** [comment]
Fault bucket 1990708153217050770, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 0.7.1912.11001
P4: 5df14b53
P5: ntdll.dll
P6: 10.0.18362.418
P7: 99ca0526
P8: c0000005
P9: 000000000003b890
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC741.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCABC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCADC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCAEC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB0C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_98e57d373afa02bf793368bdd5f5f5b98dee9b_975a6bf9_dd7ecdf4-915b-49b3-bd62-57676750b546

Analysis symbol: 
Rechecking for solution: 0
Report Id: 46a5c1c3-7e78-4369-a212-7e0344cf19b1
Report Status: 268435456
Hashed bucket: b0382dcc567b51d2cba06a84a3f9e892
Cab Guid: 0

**Comment by CaptainMorgans** [comment]
Faulting application name: WindowsTerminal.exe, version: 0.7.1912.11001, time stamp: 0x5df14b53
Faulting module name: ntdll.dll, version: 10.0.18362.418, time stamp: 0x99ca0526
Exception code: 0xc0000005
Fault offset: 0x000000000003b890
Faulting process ID: 0x1504
Faulting application start time: 0x01d5c16fe35ff0cd
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: 46a5c1c3-7e78-4369-a212-7e0344cf19b1
Faulting package full name: Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by zadjii-msft** [comment]
@CaptainMorgans You shouldn't need to restart after install, the Terminal _should_ just work. Could you use the Feedback Hub to trace the crash when trying to launch? That'll make it easier for us to debug the crash. _Bot, do the thing:_

**Comment by ffes** [comment]
Store apps sometimes stop working without any clear reason. Search the internet and see. At the office on a couple of Windows machines the calculator won't start anymore. On some others the Photos app doesn't start anymore. None of the common tips work. Maybe you ran into a similar problem 😞
