### ISSUE TITLE
Not working with chinese character input 

### ISSUE THREAD

**Issue by fengzhao** [microsoft/terminal#4097]
Windows 10 2004

WSL2  ubuntu18.04 

Windows Terminal (Preview)
Version: 0.7.3451.0

I using WSL2 ubuntu18.04 on windows terminal , When i type ` with chinese character input . The windows terminal will auto appear many  .... 

just like this:

```
root@fengzhao-laptop:~# ············································································································································································································································^C
root@fengzhao-laptop:~#
root@fengzhao-laptop:~#
```

**Comment by zadjii-msft** [comment]
Thanks for reporting this! This looks like it's a /dupe of #3706.
