### ISSUE TITLE
Terminal displays incorrect warning when we fail to parse a GUID

### ISSUE THREAD

**Issue by jagansankara** [microsoft/terminal#4098]
# Environment

```none
Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): Version: 0.7.3451.0

```

# Steps to reproduce

1. Open profile.json file.
2. Add new profile details. 
3. Save profile.json file

Sample file
[profiles.json.txt](https://github.com/microsoft/terminal/files/4016144/profiles.json.txt)

# Expected behavior

Saved profile should be reflected in WT menu.

# Actual behavior

Getting parsing error in Windows Terminal application even though setting is valid. 
![image](https://user-images.githubusercontent.com/10755858/71671836-147a6300-2d9a-11ea-9910-8aeb0845e952.png)

**Comment by zadjii-msft** [comment]
`"{b453ae62-4e3d-5e58-b989-0a998ec441b82}"` Isn't a valid GUID - we should probably have a better warning there for invalid GUIDs.

You could probably get away with deleting the `guid` field entirely from that profile, though, you'd still need to manually set a `commandline` for it to do something.

**Comment by jagansankara** [comment]
Without `guid` how can we set `defaultProfile` value ?

**Comment by zadjii-msft** [comment]
@jagansankara You've got me there. If you want to set the profile as the default profile, you'll need to give it a valid GUID.

**Comment by jagansankara** [comment]
@zadjii-msft  That's what i'm asking. What is valid GUID. Sorry to ask this. I know nothing about Windows system id's.

**Comment by zadjii-msft** [comment]
> GUID (or UUID) is an acronym for 'Globally Unique Identifier' (or 'Universally Unique Identifier'). It is a 128-bit integer number used to identify resources. The term GUID is generally used by developers working with Microsoft technologies, while UUID is used everywhere else. 

You can use https://www.guidgenerator.com/ to generate them. The problem you were having was that the string you were using, `"{b453ae62-4e3d-5e58-b989-0a998ec441b82}"` is _not_ a GUID - it has one too many digits. You can't just append digits to the GUID string like that

**Comment by jagansankara** [comment]
Thanks @zadjii-msft . As you said earlier in your comment If we have separate ticket for warning issue, we can close this issue.

**Comment by zadjii-msft** [comment]
Hey so this is a subset of #4299 so I'm closing it as a dupe.

/dup #4299

Thanks!

**Comment by Piot1998** [comment]
I have the same problem with this message only when trying to modify myself https://www.bleepingcomputer.com/news/microsoft/windows-terminal-now-has-a-hidden-graphical-settings-editor/ in windows terminal . What can I do in such a situation?
