### ISSUE TITLE
Using Microbit serial VT100 with WSL Ubuntu gives wrong output and early hangup

### ISSUE THREAD

**Issue by mobluse** [microsoft/terminal#41]
Microsoft Windows [Version 10.0.17063.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Configure BBC Microbit according to: https://youtu.be/w_-rEYKZ3do
I use WSL Ubuntu (most upgraded).
```
$ sudo chmod 666 /dev/ttyS3
[sudo] password for pi:
$ sudo cu -l /dev/ttyS3
Connected.
```
Press button B on BBC micro:bit.
BBC micro:bit VT100 WSL Ubuntu:
https://youtu.be/oUPFZrn_mHw
* What's wrong / what should be happening instead:
It should look like this:
BBC micro:bit VT100 WSLTTY 1.8.2 https://github.com/mintty/wsltty :
https://youtu.be/pl-IIPlDeew
Or perhaps even better like this:
BBC micro:bit VT100 Tera Term VT:
https://youtu.be/o8-67Y03hRk

**Comment by mobluse** [comment]
I think one problem is due to that \x1B[2J or \033[2J is not erasing the screen with blanks. 
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idtextmodificationspanspan-idtextmodificationspanspan-idtextmodificationspantext-modification

The other problem is due to that some character codes higher than 127 from the serial port hangs up.

These are problems with WSL Ubuntu (built-in console), but [WSLTTY](https://github.com/mintty/wsltty) with Ubuntu handles this.

**Comment by DHowett-MSFT** [comment]
I know it's been a while, but I was wondering if you're still hitting this (or if you've since moved on, I guess). We've definitely made some console changes since 17063 :smile:

**Comment by mobluse** [comment]
I have reported a bug and given very detailed instructions on how to reproduce it. Why do you ask me to test if the bug still exists several years later when you can do it yourself? Surely Microsoft can afford to buy a Microbit.

**Comment by DHowett-MSFT** [comment]
If we purchased every weird one-off piece of hardware everybody who reported a bug complained about, we would be absolutely swimming in it.

You, on the other hand, already have one.

Seems like a fairly reasonable request.
