### ISSUE TITLE
Curses programming: cursor handled incorrectly

### ISSUE THREAD

**Issue by thautwarm** [microsoft/terminal#4102]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.1]
Windows Terminal version : Version: 0.7.3451.0

CPython: 3.7.4
CPython package curses(Windows-curses)
```

# Steps to reproduce
Open `cmd` or `PowerShell` inside Windows Terminal, with `python` run 

```python
def main():
    window = curses.initscr()
    curses.noecho()
    curses.nonl()
    curses.nocbreak()
    curses.raw()
    window.keypad(False)
    x = 0
    y = 0
    while True:
        window.refresh()
        c = window.getch()
        window.addstr(0, 0, str(c))
        if c == ord('q'):
            return
        elif c == ord('a'):
            x = 10
        elif c == ord('b'):
            y = 10
        else:
            x = 0
            y = 0
            pass

        window.move(y, x)
try:
    main()
finally:
    curses.endwin()
```

# Expected behavior

Press `a`, the cursor move to `(0, 10)` immediately.

# Actual behavior

After pressing `a`, the cursor doesn't move to `(0, 10)` immediately, i.e., the screen show doesn't change at all.  Then after an another pressing, the cursor moves to `(0, 10)`. 

P.S:

- Expected behavior is according to the package `curses` bundled in Python of Linux  distros.
- Things work perfectly when we use `cmd` or `PowerShell` without Windows Terminal.

https://github.com/zephyrproject-rtos/windows-curses/issues/7

**Comment by zadjii-msft** [comment]
Yep that looks broken to me. Definitely something wrong in conpty, since this repros in inception (`cmd.exe /c wsl.exe cmd.exe`) as well. Thanks for the clear report with easy repro steps!

**Comment by j4james** [comment]
I expect this is the same bug as #4107.

**Comment by DHowett-MSFT** [comment]
Nah, this one is separate from #4107. It repros in inception (https://github.com/microsoft/terminal/issues/4102#issuecomment-570584042), and the inbox conhost servicing interop hasn't been updated to the changeset that regressed 4107.
