### ISSUE TITLE
Text duplicates endlessly when resizing window

### ISSUE THREAD

**Issue by kengeman** [microsoft/terminal#4103]
# Environment

```none
Windows build number: 
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  145

Windows Terminal version (if applicable): 0.7.3451.0

Any other software? Ubuntu 18-04 ///  4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

# Steps to reproduce

Load up Ubuntu in Terminal (Preview). Resize the window to be small (slimmer than the width of the path) and then drag it out to be wider - the text will follow and duplicate itself endlessly. Resize _really fast_ to a large size and it will correct itself sometimes.

![1](https://user-images.githubusercontent.com/55498989/71735110-85ae2a80-2e1b-11ea-9cb7-5c9791aee740.png)
![2](https://user-images.githubusercontent.com/55498989/71735111-85ae2a80-2e1b-11ea-9f79-a07e3a8e6a9d.png)
![3](https://user-images.githubusercontent.com/55498989/71735112-85ae2a80-2e1b-11ea-86ca-5aad1a4cee16.png)

# Expected behavior

Don't mess with the text on resize

# Actual behavior

Text duplicates endlessly.

**Comment by DHowett-MSFT** [comment]
This seems to be a side effect of /dup #1465
