### ISSUE TITLE
When changing cursor shape using DECSCUSR escape sequences, the cursor shape doesn't change until the cursor is moved

### ISSUE THREAD

**Issue by daxian-dbw** [microsoft/terminal#4106]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3451.0

Any other software?
`pwsh + PSReadLine`
```

# Steps to reproduce

I tried to fix https://github.com/PowerShell/PSReadLine/issues/1233 in PSReadLine by always applying the standard escape sequences, so the cursor shape can be changed when switching between Insert and Command modes in the VI edit mode.

A quick fix looks like this: https://github.com/daxian-dbw/PSReadLine/commit/d29dad98426992c2d9f3b92cebedd7d85c4a0fac
It works fine in the terminals on Linux and macOS.
However, in Windows Terminal and VS Code terminal, the cursor shape doesn't changed immediately after writing out the escape sequences. The change happens only after the cursor is moved.

# Expected behavior

The behavior should be the same as on Linux.
1. type <kbd>Esc</kbd> to switch from insert mode to command mode. Cursor shape is changed to steady block.
2. type <kbd>i</kbd> to switch from command mode to insert mode. Cursor shape is changed to blinking bar.
3. type <kbd>a</kbd> to insert the character `a`.

![linux](https://user-images.githubusercontent.com/127450/71749029-3111ac00-2e29-11ea-9c42-e9bf2fe0febd.gif)

# Actual behavior

This is what happens in Windows Terminal.
1. type <kbd>Esc</kbd> to switch from insert mode to command mode. Cursor shape is changed to steady block.
2. type <kbd>i</kbd> to switch from command mode to insert mode. Cursor shape doesn't change.
3. type <kbd>a</kbd> to insert the character `a`. Cursor shape is changed to blinking bar. Moving the cursor with <kbd>LeftArrow</kbd> or <kbd>RightArrow</kbd> will also trigger the cursor shape change.

![winterminal](https://user-images.githubusercontent.com/127450/71749201-9bc2e780-2e29-11ea-84ba-02804f4be95a.gif)

**Comment by zadjii-msft** [comment]
I'm almost certain that this means conpty isn't immediately flushing the updated cursor shape to the terminal pipe.

**Comment by zadjii-msft** [comment]
I've got this crazy theory that #2665 will fix this too, but that PR is kinda _months_ old now. Lemme pull it into a new branch and see what happens.
