### ISSUE TITLE
documentation is unclear about being able to use wt.exe

### ISSUE THREAD

**Issue by BananaAcid** [microsoft/terminal#4109]
It would be helpful, to have `wt.exe` being mentioned in the `Readme.md`.

While creating an issue on not being able to find out how to run it from commandline, I found a closed issue already about it - others had the same issue finding info about it already.

**Comment by KharmaScribbles** [comment]
Also, if you set 

"startingDirectory": .

in settings, you can use "wt.exe" in File Explorer's path bar and start inside the directory File Explorer was in.

**Comment by BananaAcid** [comment]
How does "use [...] in File Explorer's path bar" work? Typing the exe into it does not.

**Comment by KharmaScribbles** [comment]
> How does "use [...] in File Explorer's path bar" work? Typing the exe into it does not.

Please ensure you've set "StartingDir" to the value= . in your profiles.json and start a new shell.


Go to File Explorer, pick an accessible directory by clicking into it as normal, then:

![wt](https://user-images.githubusercontent.com/36386908/71796377-80adce80-3007-11ea-90b2-9fcb433dd7cc.png)

Click into File Explorer's 'address bar and type "wt.exe" and press enter.

Give it a moment to start up, but when it does it should be in the same directory that File Explorer was :)

**Comment by zadjii-msft** [comment]
You know, it's been a few years now, and the docs have actually gotten pretty good now: https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows

(I believe when this was originally filed, we didn't have a docs repo yet 😋)

I'm gonna close this one out. Thanks!
