### ISSUE TITLE
How to configure to always start elevated

### ISSUE THREAD

**Issue by BananaAcid** [microsoft/terminal#4110]
It would be helpful on where and how to configure it to always require elevated permissions (UAC popup?).

From the start menu, there is no option to configure - right click - more - app settings - does not have an option either.

**Comment by Surya-06** [comment]
a hack would be to create a bat file which launches wt with cmd all the time and try using that. ( this wouldn't be the best way though and is a workaround )

**Comment by DHowett-MSFT** [comment]
Given that we're distributed and serviced via the store, this isn't going to be easily possible. I'm going to have to redirect you towards #1032 for further discussion. Thanks!
