### ISSUE TITLE
App installation failed with error message: Class not registered (0x80040154)

### ISSUE THREAD

**Issue by diman82** [microsoft/terminal#4111]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
Sorry, we don't actually own the app installer. Can you file feedback in the "App Installation" category and share the link here? I'll route it to the appropriate team.
