### ISSUE TITLE
Terminal will auto repeat my last input

### ISSUE THREAD

**Issue by xjr7670** [microsoft/terminal#4114]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable):
Version: 0.7.3451.0

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

when I input something within the terminal, no matter it is command line or coding with VIM editor in WSL, it will all occur this problem.

For example, I want to key down "cat -n 10 myfilename" in the wsl command line, **sometimes** when I finished key down the letter "n", I want to continue to write "a", but at this time, The terminal will auto repeating the letter "n" for many many times. I was not able to do anything unless just press the X button to close that window.

I have recorded a video to show this problem

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7731794/71775906-2b4fce00-2fc3-11ea-83bb-26d4f67d4a6d.gif)

But this will not occur in the system's cmd which opens with "win+r" then write down "cmd" or PowerShell and so on. Only occur in terminal
![image](https://user-images.githubusercontent.com/7731794/71775851-88974f80-2fc2-11ea-8a59-6a21ba21bdbf.png)

The system version which I use is:
![image](https://user-images.githubusercontent.com/7731794/71775925-605c2080-2fc3-11ea-9292-22b057f603fd.png)

I cannot search for anything with this problem. Appreciate to get some help

**Comment by DHowett-MSFT** [comment]
This seems like #3706, but your example indicates that it happens for normal input?

**Comment by xjr7670** [comment]
> This seems like #3706, but your example indicates that it happens for normal input?

Yes, absolutely normal. I see that issue #3706 was caused by the Chinese character. Or it may occur by the Chinese input software? I am using the Microsoft Wubi from the system. But this problem occurred when I was in English input status.

**Comment by onovotny** [comment]
I started seeing this to on the latest nightlies. 

See screenshot. This appears to be a display issue as the commands execute successfully. 

![2020-01-05_11-10-55](https://user-images.githubusercontent.com/1427284/71782791-2c293580-2fac-11ea-8b9f-79cbb64edc6b.gif)

**Comment by djdv** [comment]
I'm experiencing the same as @onovotny 
Building from current master (d711d731d7d00259b2e0fe5847928c9f1c1121ed) results in this behaviour.
I reverted to 4daf1d7f9c36eb2129c277e89255d44670db0537 (just because it was the last usable version I built) and don't have this, so the issue may be within that commit range.

**Comment by DHowett-MSFT** [comment]
Yeah, this is #4107 (PR #4113)

**Comment by DHowett-MSFT** [comment]
@xjr7670 Are there any other interesting things about your machine that might help us figure this one out? Nobody here's got any idea.

Just FYI - #4107 is a new regression after 0.7, so it is not the cause of this issue.

**Comment by xjr7670** [comment]
> @xjr7670 Are there any other interesting things about your machine that might help us figure this one out? Nobody here's got any idea.
> 
> Just FYI - #4107 is a new regression after 0.7, so it is not the cause of this issue.


In addition to the input software, there is a software called DLP. Which is used to monitoring every computer's internet I/O traffic inside our company to prevent information leakage.

After installed DLP, it will auto output some error info to the shell window, especially within the powershell
![image](https://user-images.githubusercontent.com/7731794/71861506-8e5f7300-3131-11ea-97aa-66bebac8d8d3.png)
![image](https://user-images.githubusercontent.com/7731794/71861530-a33c0680-3131-11ea-84df-abd1bc6e1249.png)

I can offer something about DLP if you need it. For example the log file or something else.

**Comment by DHowett-MSFT** [comment]
We have made some changes to the input stack recently. Is this still happening?

**Comment by xjr7670** [comment]
It has not reappeared recently, it should have been repaired

![image](https://user-images.githubusercontent.com/7731794/81557284-4d68bb00-93be-11ea-9fd4-df0c0121a5b5.png)

**Comment by DHowett-MSFT** [comment]
Thank you!
