### ISSUE TITLE
Commands panel

### ISSUE THREAD

**Issue by Grafikart** [microsoft/terminal#4115]
# Description of the new feature/enhancement

This terminal is becoming more and more awesome with lots of feature that you have to discover using keybinding. Building an UI for every command is not possible and I think it could be interesting to have a shortcut that displays a command panel (like VSCode: workbench.action.showCommands).

![](https://i.stack.imgur.com/sT6j8.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually something I'm working on already 😄 

We originally stated work on it with issue /dup #2046.
There's a spec over in #2193 
I've even got a (stale) branch in `dev/migrie/f/2046-command-palette`

**Comment by Grafikart** [comment]
Oh thanks for the references, and sorry for the dup.
