### ISSUE TITLE
Issues pasting into the new terminal. 

### ISSUE THREAD

**Issue by martinowren** [microsoft/terminal#4118]
# Environment

Windows build number: 10.0.18362.535
Windows Terminal version (if applicable): 0.7.3451.0

# Steps to reproduce

1. Open the program
2. Open a new Ubuntu terminal tab
3. Go to another piece of software (Can be anything like a browser, notepad etc) and copy a string.
4. Paste into the new terminal tab. 

# Expected behavior

The string would be pasted into the terminal tab instantly

# Actual behavior

The is either a delay of 1-4s before the string gets pasted into the terminal or it doesnt get pasted at all. 

# Other comments

I have reproduced this bug on a self built computer, surface book 2 and a surface laptop 3.

**Comment by zadjii-msft** [comment]
I certainly wouldn't expect that - is there anything else running on your system that might be trying to manage the clipboard? I honestly have no idea how to debug this without a local repro, so any help you could give would be helpful.

**Comment by martinowren** [comment]
There is nothing locally managing the clipboard. What can I do to help you reproduce the bug 🙌

**Comment by ZhaoMJ** [comment]
I could reproduce this bug yesterday, but for some reason now I can't. Maybe it's worth noting I also surface book 2.

**Comment by zadjii-msft** [comment]
I honestly have no idea how we'd be able to repro this on my end 😟 Maybe try repro'ing with task manager open. Is there anything that spikes in CPU usage when you paste into the Terminal?

Also, cc'ing @DHowett-MSFT, maybe we could get someone from the clipboard team to help us get some diagnostics here

**Comment by ZhaoMJ** [comment]
Ah I think I got a repro. Try this - 
1. Open a new Ubuntu terminal tab
2. Go to another piece of software (Can be anything like a browser, notepad etc) and copy a string.
3. Close WT and reopen a new Ubuntu tab
4. Paste into the new terminal tab.

**Comment by ZhaoMJ** [comment]
I'm so sorry I was wrong...😥 It now again can't be reproduced consistently on my end...
But I indeed got a GIF where I was able to repro it several times. Meanwhile, I found nothing noticeble in CPU usage. Hope it could help.
(It's hard to get a long GIF smaller than 10MB)
![repro](https://user-images.githubusercontent.com/48666391/71903955-2b58f500-31a0-11ea-98fe-bd2849db5e84.gif)

**Comment by martinowren** [comment]
> I'm so sorry I was wrong...😥 It now again can't be reproduced consistently on my end...
> But I indeed got a GIF where I was able to repro it several times. Meanwhile, I found nothing noticeable in CPU usage. Hope it could help.
> (It's hard to get a long GIF smaller than 10MB)
> ![repro](https://user-images.githubusercontent.com/48666391/71903955-2b58f500-31a0-11ea-98fe-bd2849db5e84.gif)

This is exactly the same issue I have.

**Comment by DHowett-MSFT** [comment]
We're guessing this is a /dup of #3609 -- right-clicking doesn't seem to focus the terminal itself... but left-clicking will. If you manage to repro this, and then left-click _then_ right-click, does it work?

**Comment by martinowren** [comment]
> We're guessing this is a /dup of #3609 -- right-clicking doesn't seem to focus the terminal itself... but left-clicking will. If you manage to repro this, and then left-click _then_ right-click, does it work?

It would still not paste into the terminal.

**Comment by DHowett-MSFT** [comment]
Hm. Fair enough!

**Comment by cinnamon-msft** [comment]
@martinowren Are you still seeing this?
