### ISSUE TITLE
Reports of native crashed using ConPTY under Windows 32-bit (Build 18362 and 18877)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/terminal#412]
We got 2 reports of VS Code crashing by simply opening the terminal when ConPTY is enabled, switching to winpty fixes the issue: https://github.com/Microsoft/vscode/issues/72190

**Comment by DHowett-MSFT** [comment]
@Tyriar: There should be nothing conhost.exe (as the host of a pseudoterminal) can do to _cause VS Code to crash_. There may be a bug in conhost here, but VS Code should be more robust.

**Comment by Tyriar** [comment]
👍 something mustn't be handled right in node-pty https://github.com/Microsoft/node-pty/issues/277

**Comment by oising** [comment]
Make that three reports ;)

**Comment by Tyriar** [comment]
I believe ConPTY is failing specifically on sysnative\cmd.exe as that should be the path used in WoW64 vscode: https://github.com/Microsoft/vscode/blob/e4b5bccf9364a0f678606d5bdfc18800854bf678/src/vs/workbench/contrib/terminal/electron-browser/terminalService.ts#L121-L126

**Comment by DHowett-MSFT** [comment]
`CreatePseudoConsole` does not spawn your shell; that's your responsibility.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/node-pty/issues/277

**Comment by dgriffen** [comment]
I think this issue should be reopened. I also saw problems when attempting to create C# bindings to the ConPTY APIs. When running in a 32-bit process (Visual Studio), I would get an exception back from the streams. It's been a while since I repro'd the issue, but if I remember correctly the error indicated that some stream internal to the conpty infrastructure had been unexpectedly closed.

**Comment by DHowett-MSFT** [comment]
Mirroring internal discussion bits:

>This is definitely concerning. We’ve tested conpty in WOW6432, WOA and CHPE (Windows on ARM) scenarios. If you are using the CreatePseudoConsole API, it will launch a conhost of the appropriate bitness.

>When I say “appropriate bitness,” what I really mean is “the system’s native bitness.” Since conpty is a conhost feature, and conhost must match the bitness of its kernel driver, the pseudoconsole host will always be native. Fortunately, this is not unusual: launching a 32-bit console application on WOW64 also results in a mixed-bitness environment where conhost is different from the application.
>All of these scenarios have been pretty well tested at this point.

Waiting for a repro. I'll reopen this bug with `Needs-Repro` until then.

**Comment by DHowett-MSFT** [comment]
This seems to have been partially the fault of node-pty for [getting the calling conventions wrong](https://github.com/microsoft/node-pty/blob/master/src/win/conpty.cc#L36) and partially the vault of VS.

**Comment by Tyriar** [comment]
Thanks for looking into it 🙂
