### ISSUE TITLE
copy/paste issue over SSH connection

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#4121]
```
Windows Terminal (Preview)
Version: 0.7.3451.0
```

I can copy/paste using `ctrl-c` & `ctrl-v` before i connect to SSH session.

My question here:

can i enable the same over `ssh` session ? or to copy on select via mouse ?

waiting for your feedback ASAP

Regards,

**Comment by mkitzan** [comment]
I am able to copy-paste over an SSH connection using WT and use mouse selection. Are you asking whether or not this is possible or are you unable to perform this yourself?

**Comment by AmericanY** [comment]
@mkitzan thanks for your response. here on my end, I can only copy/paste using `right click`.

How can i enable Mouse selection ? and what do you mean by `WT`.

**Comment by mkitzan** [comment]
Take a look at my comment [here](https://github.com/microsoft/terminal/issues/4065#issuecomment-569192075) about enabling <kbd>Ctrl+C</kbd> and <kbd>Ctrl+V</kbd> copy-paste. 

Mouse selection should be there by default by performing the steps listed. If those don't work, let me know what happens when you perform those steps. 
- left click at the point you want to start selecting text
- then drag the mouse over the text you want to select

Also, `WT` just stands for Windows Terminal.

**Comment by AmericanY** [comment]
@mkitzan now it's works via <kbd>Ctrl+C</kbd> <kbd>Ctrl+V</kbd>. how about if i want to use mouse copy on selection ?

**Comment by zadjii-msft** [comment]
From [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)

> ## Globals
> Properties listed below affect the entire window, regardless of the profile settings.
> 
> | Property | Necessity | Type | Default | Description |
> | -------- | --------- | ---- | ------- | ----------- |
> | `copyOnSelect` | Optional | Boolean | `false` | When set to `true`, a selection is immediately copied to your clipboard upon creation. When set to `false`, the selection persists and awaits further action. |
>

**Comment by AmericanY** [comment]
@zadjii-msft  thanks for your response. could you please advise me where i should put this ?

I'm now inside profiles.json, i try to insert `"copyOnSelect": true` under keybindings but VScode telling me it's incorrect `Property copyOnSelect is not allowed.`

**Comment by zadjii-msft** [comment]
You can put it right in the root object of `profiles.json`:

```json
{
    "$schema": "file:///c:/Users/migrie/dev/private/OpenConsole/doc/cascadia/profiles.schema.json",

    "alwaysShowTabs": false,
    "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "copyOnSelect": true,
	...
}
```

**Comment by AmericanY** [comment]
@zadjii-msft thank you very very much. it's works!
