### ISSUE TITLE
Arrow keys broken in riscv64-unknown-elf-gdb

### ISSUE THREAD

**Issue by xobs** [microsoft/terminal#4127]
# Environment

```none
Windows build number:

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable): Version: 0.7.3451.0

gdb: GNU gdb (SiFive GDB 8.3.0-2019.08.0) 8.3 from https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-w64-mingw32.zip
```

# Steps to reproduce

1. Run riscv64-unknown-elf-gdb
2. Press "up arrow"

# Expected behavior

The terminal should go back to the previous command.  Since there is no command, it should beep and do nothing.

# Actual behavior

The terminal prints out "H"

# Differences from `cmd.exe`

When running the same program under `cmd.exe` and powershell, it behaves correctly.  Therefore this is a regression from previous functionality.

**Comment by zadjii-msft** [comment]
I'm going to guess that this is related to #2397. There's a bunch of dupes of that with similar symptoms, so I'm going to assume it's that one. Thanks!

/dup #2397
