### ISSUE TITLE
Change default key bindings for compatibility with nano

### ISSUE THREAD

**Issue by pedroaugustosmribeiro** [microsoft/terminal#4136]
# Description of the new feature/enhancement

The default key bindings for new tab (Ctrl+T) and close tab (Ctrl+W) conflict with UNIX nano shortcuts.

# Proposed technical implementation details (optional)

Maybe could send the conflicting key combination to the foreground terminal application (nano, bash, etc…) and if no action happens, then terminal itself captures it and executes the key binding action?!

**Comment by zadjii-msft** [comment]
So, the default keybindings were changed probably 4 months ago to <kbd>Ctrl+Shift+T</kbd>/<kbd>Ctrl+Shift+W</kbd>:

https://github.com/microsoft/terminal/blob/488291749994822ef54ba5140c7726b6d984116f/src/cascadia/TerminalApp/defaults.json#L201-L213
