### ISSUE TITLE
`hidden` profiles are deleted, not hidden

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#4139]
Right now, "hiding" a profile totally deletes it. This has some interesting effects on profiles that are in active use - their icons and background images disappear, and their `closeOnExit`s get ignored. Anything that relies on the _presence_ of a profile for a given tab fails.

I'm wondering if `hidden` shouldn't just mean "don't show in the list". This has _other_ interesting follow-on questions: should a profile that's been hidden still be launchable with a keyboard shortcut that specifically targets it? should a hidden profile be defaultable? I don't totally see why not.

Partially related to [workitem for customizing the dropdown menu].

**Comment by acshef** [comment]
A hidden profile also can't be started using the command line argument `wt -p` introduced in v0.9. I believe that behavior to be a bug. The generally observed behavior of "hidden things" in UX/UI is that they can still be accessed explicitly -- this is what makes those items distinct from ones that are deleted.

**Comment by WSLUser** [comment]
If you can provide the option to remove the Azure Shell then I'd be fine with it. Didn't even know hidden profiles are deleted. To me, that's a good thing. Less junk on my system. I like Azure but if a business or individual isn't using it, it should be gone.

**Comment by zadjii-msft** [comment]
@WSLUser For the record, this mostly just means that the profile is deleted from our runtime list of profiles, which means that you cannot reference it in any actions or commandline args, not that it's "uninstalled". The code that makes the Azure shell work is built-in to the Terminal - it's basically just a thin wrapper for a web API to establish the connection.
