### ISSUE TITLE
Terminal won't open

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/terminal#4146]
# Environment

```none
Windows build number:19013
Windows Terminal version (if applicable): I can't look it up :( 

Any other software? No
```

# Steps to reproduce

I've somehow gotten Windows Terminal into an interesting error state. Sorry I don't know how to reproduce this error. Looking more to see if I can collect any traces or anything for your team to help identify this.

* I click on the Windows Terminal and it starts up
![image](https://user-images.githubusercontent.com/42221804/71942360-cf777780-3171-11ea-815d-22a8bdb25d88.png)
* No Window pops up (I checked with Alt+Tab)
* Try to close Terminal and see a 'Not responding' message
![image](https://user-images.githubusercontent.com/42221804/71942355-c5ee0f80-3171-11ea-9c1b-1041cab082f0.png)

# Expected behavior

Windows Terminal should open up.

# Actual behavior

Windows Terminal doesn't open.

**Comment by craigloewen-msft** [comment]
More info:

I tried to open WSL from a regular Console window and it was stuck. My WSL service was in a stuck state.

My guess is that Terminal was polling my WSL instance to get my distros, but since that was stuck Terminal ended up stuck. I restarted and my WSL service was fixed, and Terminal was fixed as well.

**Comment by zadjii-msft** [comment]
@craigloewen-msft I bet this is #3987, right?

**Comment by craigloewen-msft** [comment]
Yeah that's very very likely what it was. Feel free to close this if you're tracking it over in #3987 as that would fix my issue.

**Comment by zadjii-msft** [comment]
k cool, thanks Craig

/dup #3987

**Comment by Samary1999** [comment]
Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine)** may help.
