### ISSUE TITLE
Enter tmux would reset console font .

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#415]
* Your Windows build number: windows 10 1809

1. I set a powerline font `dejavu` in ubuntu 18.04 shell 
2. quit ubuntu bash and re-enter 
3. the font setting is keeped 
4. vim powerline theme worked very well
    ![image](https://user-images.githubusercontent.com/3938751/56483200-f108d400-64fa-11e9-8aa4-7a34c36c4522.png)
5. enter tmux, its powerline theme was broken , font setting became `新宋体`
6. in tmux, enter vim , powerline theme became broken too .
    ![image](https://user-images.githubusercontent.com/3938751/56483194-e4847b80-64fa-11e9-88ab-75da9667f3b6.png)
7. quit tmux, the font setting return to `dejavu`

This is a weird behavior. 
Enter tmux would reset console font to default .

**Comment by zadjii-msft** [comment]
@eromoe Hey sorry for letting this one linger for so long. Is this still happening for you? It's been a few years of bug fixes, so this might have been taken care of something along the way. I'd presume this doesn't happen in the Terminal either 😄

**Comment by eromoe** [comment]
Yeah, fine now.
