### ISSUE TITLE
Add an client FTP 🌐

### ISSUE THREAD

**Issue by ilohamc** [microsoft/terminal#4151]
## My idea
I love the new terminal and I think it would be really cool to add an ftp client and ftp account manager, like on ubuntu in the file explorer.

## Description
I think we should add a dropdown, 4 input and a button.
- Dropdown list for already registered acounts
- First input for IP address
- Second input for user
- Third input for port (FTP, SFTP ...)
- Fourth input for password
- Button to connect

**Comment by DHowett-MSFT** [comment]
Hey @ilohamc! Thanks for the feature request. I really appreciate your enthusiasm! An FTP client (and file manager) is way, way beyond the scope of a terminal application, so we're not likely to do this one. Sorry! There's a bunch of really good file managers out there, and I don't think we'd end up being as good as they are at managing files.
