### ISSUE TITLE
TSFInputControl::_layoutRequestedHandler crashes on call to TransformToVisual.TransformToPoint during teardown

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#4159]
## Root Cause

TSFInputControl's `CoreTextEditContext` is requesting a final layout during application teardown, after the TSFInputControl has been removed from the core Xaml object tree.

**Comment by DHowett-MSFT** [comment]
Exception thrown at 0x00007FF9DC972E26 (Windows.UI.Xaml.dll) in WindowsTerminal.exe: 0xC0000005: Access violation reading location 0x0000000000000010.

**Comment by zadjii-msft** [comment]
@DHowett-MSFT is this a recent regression? Should this block 0.8?

**Comment by DHowett-MSFT** [comment]
Tracking MSFT:24530757, as it's partially a platform bug.
