### ISSUE TITLE
Multiple Windows.Terminal.PowershellCore profiles not possible

### ISSUE THREAD

**Issue by bormm** [microsoft/terminal#4160]
# Environment

Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): Windows Terminal Preview v0.7.3451.0
Powershell: 7.0.0-rc.1

# Steps to reproduce

Create a second entry with
`source": "Windows.Terminal.PowershellCore"`
and a different GUID.

# Expected behavior

- It is possible to have one or endless more powershell core profiles in the configuration
- They show up in the GUI
- they can be selected as defaultProfile

# Actual behavior

- After starting the terminal, no second entry will show up.
- Using the GUI of the second entry shows the message, that the GUID is not found.

# Additional information

- Modifying the first entry, like changing the name, is correctly reflected within the GUI.
- Duplicating the powershell.exe (old one) profile is possible and works as expected
- Creating a profile that calls pwsh.exe directly is also possible and works as expected

[profiles.zip](https://github.com/microsoft/terminal/files/4039650/profiles.zip)

**Comment by DHowett-MSFT** [comment]
Yeah, this one's a bit thorny. Sorry about that. Profiles with `source` metadata are built by "dynamic profile generators", which run on startup to detect the things you might have on your system. I believe you'll be better served by /dup #3818, which will let you create a new profile that applies customizations _on top of_ existing profiles.

**Comment by bormm** [comment]
@DHowett-MSFT 
Thank you for the hint for the alternative solution, even its open, but I have still some comments on this:
> Yeah, this one's a bit thorny. Sorry about that. Profiles with `source` metadata are built by "dynamic profile generators", which run on startup to detect the things you might have on your system.
1. If the profile is created dynamicaly and not a really a profile, why its still called profile? Why its not an additional section called "profileSources"? 
That would clearly separate the generators from the profiles. That would also allow to prevent setting all the values like id and so one just via the json schema.

2. In case you would not accept that argument, why is setting the name on a profile source is allowed, but the id is not? Why is setting the id not throwing some error at startup time? Why is no error thrown at all, if at the end the profile was not processed?
