### ISSUE TITLE
Investigate/implement Dependabot

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#4165]
It's very interesting seeing Windows Terminal will have some of it's source code coming from Chromium. I'd also suggest configuring dependabot to update this dependency source from the github mirror as updates to the source occur. 

_Originally posted by @WSLUser in https://github.com/microsoft/terminal/pull/4144#issuecomment-572697227_

**Comment by WSLUser** [comment]
FYI, Github should of already provided the service for other dependencies unless it was already disabled. https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates. If not, there are other existing mechanisms that can be utilized. Openssh portable (from which win32 openssh forks from) auto pulls from the mainstream openssh project for instance.

**Comment by DHowett** [comment]
It looks like dependabot implemented itself!
