### ISSUE TITLE
We're not sizing the drag handle correctly all the time; it cuts off parts of the window sometimes

### ISSUE THREAD

**Issue by burhan** [microsoft/terminal#4166]
# Environment

Windows Version: 10.0.19041.0 ("slow ring" is enabled)

![image](https://user-images.githubusercontent.com/603112/72106066-c1775180-333f-11ea-94a8-6b3341278541.png)

Terminal Version (0.7.3451.0); from the Windows Store

![image](https://user-images.githubusercontent.com/603112/72106171-e966b500-333f-11ea-925b-5a1df34c1899.png)

Native resolution: 2560 x 1440 (14" Lenovo X1 Carbon); scaling set at 125% (changed from 150% during this issue).

# Steps to reproduce

Change the scaling ratio on your screen.

# Expected behavior

Terminal window scales / adjusts automatically (which happens), but the controls for minimizing / maximizing disappear.

_Honestly, not sure what is the expected behavior as many apps don't adjust properly, but after opening a new window, existing window at random starts showing the controls is why I raised this issue._

# Actual behavior

(two instances I had open, when I changed the scaling ratio)

![image](https://user-images.githubusercontent.com/603112/72105865-65143200-333f-11ea-8581-1d4aed137392.png)

After opening a new window, randomly, the first window starts showing the minimize/maximize controls.

![image](https://user-images.githubusercontent.com/603112/72105987-9a208480-333f-11ea-8101-ffbdc3877430.png)

**Comment by DHowett-MSFT** [comment]
This is now the bug tracking the class of issues around drag bar sizing. Thanks!

**Comment by zadjii-msft** [comment]
Getting the repro working exactly for me was a little tricky, but I think I got it. For me, the trick was that the window had to be in a spot where the cursor wouldn't be on top of the window immediately after the DPI scale changes. Expect a PR soon ☺️
