### ISSUE TITLE
How to disable "Startup MSG"

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#4167]
Hello,

is it possible to disable `Startup MSG`

Which is 

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6
```

that's will be great if there's something like `"StartupMSG": false`

**Comment by AmericanY** [comment]
Well solved it by.

`"commandline": "powershell.exe -nologo"`

**Comment by DHowett-MSFT** [comment]
Thanks for following up!
