### ISSUE TITLE
Please Add Jump Lists - Each templated shell should be an option on Right click of the icon

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/terminal#4178]
# Description of the new feature/enhancement
Right now you have to open the terminal, which opens a default shell and then click on the drop down, then click on the shell you want. It would be way better if there was a jump list on the icon itself starting the terminal window so that it would jump directly to the shell I wanted to open.  

So in the start menu or if pinned to the taskbar I'm 2 clicks to the shell I want and no other shells open.

**Comment by zadjii-msft** [comment]
Hey thanks for the suggestion! We've actually already got an issue tracking this feature request, /dup #576. In fact, there's also already a spec in progress for this feature, which is over in #1357. PLease make sure to search for duplicate issues when filing an issue 😉 Thanks!

**Comment by JohnGalt1717** [comment]
@zadjii-msft I did, got a lot of noise about other stuff, so I missed it. I apologize.
