### ISSUE TITLE
Create `til` namespaces shorthanding the chromium safe math

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#4179]
We may actually want to namespace a bunch of this stuff into `til` (with `using`), more than what @lhecker's already suggested. It'll make us more robust if we ever do want to change things up in the future, _and_ avoid littering `chromium::numerics::whatever` all over every part of the code.

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/pull/4144#issuecomment-572804554_

This represents putting something like `til::saturated<T>` as the shorthand for the `chromium::numerics::ClampedNumeric<T>` and so forth for the other representations per @DHowett-MSFT's comment.

**Comment by DHowett-MSFT** [comment]
We may have decided we don't need to do this, actually. The namespace isn't all that bad. I don't recall, though.

**Comment by zadjii-msft** [comment]
Hey @miniksa @DHowett, it's been two years of this and I don't think this is bothering anyone. Close?

**Comment by miniksa** [comment]
@lhecker, as the current master of the `til` namespace, what's your opinion here?

**Comment by lhecker** [comment]
![maybe... no](https://media.giphy.com/media/LSFwEyHmoBwF0S3YM5/giphy-downsized.gif)
