### ISSUE TITLE
Screen scrolls when cursor is at the bottom of the screen and the console shrinks

### ISSUE THREAD

**Issue by x1bzzr** [microsoft/terminal#4181]
# Environment

```none
Windows build number: 19013.1102 build
```

# Steps to reproduce

- Position cursor at the bottom of the screen.
- Decrease the size of the console window by resizing it.

# Expected behavior

Screen should not scroll.

# Actual behavior

If the cursor is positioned at the bottom of the screen and the user decreases the size of the console window by resizing it. the console will automatically scroll down to keep the cursor within the screen which makes the contents of the screen change.

**Comment by DHowett-MSFT** [comment]
Based on your description in #4180, it seems like the application is doing something wrong?

> I'm running into a situation where, when the the cursor is positioned at the bottom of the screen and the user decreases the size of the console window by resizing it, the console will automatically scroll down to keep the cursor within the screen which makes the contents of the screen change. The application will then notice than the console has resized and will move the cursor to the first row in order to update the screen for the new console size, but because previously the screen was scrolled, moving the cursor to the top row will trigger another scroll which again will update the contents of screen. After this the application updates the screen to reflect the new console size. The unintended effect of all this is that the screen is updated three times instead of only once after the console is resized. Is there a way I can avoid this?

"The application ... will move the cursor to the first row ... trigger another scroll"

If the application is moving the cursor to a row that is not within the boundaries of the screen, which the application can detect by reading a `WINDOW_BUFFER_SIZE_EVENT`, is it not simply doing something wrong?

Programmatically moving the cursor within the bounds of the viewport will not trigger a scroll operation.

Just to confirm, though: do you have the experimental Terminal feature "Disable scroll-forward" turned on?
![image](https://user-images.githubusercontent.com/14316954/72285907-e9dda500-35f8-11ea-8b59-ebe4c17236c0.png)

**Comment by x1bzzr** [comment]
The only reason why moving the cursor to the first row triggers a scroll is because, like I said, the screen is automatically scrolled down if the cursor is at the bottom row and the user shrinks the console by resizing it. If the screen had not been previously scrolled the first row would still be within the bounds of the screen, so this doesn't seem to be the application's fault. I didn't know about the "Disable Scroll-Forward" option, but I tried it and it didn't have any effect. The screen still scrolled automatically given the situation I described.

**Comment by DHowett-MSFT** [comment]
This is likely to be a contentious issue. What do you think that the console host should do? Keeping the cursor on the screen is its most important job, and _yes_ that does mean the viewport changes. I'm at a loss for how we properly serve users _and_ applications here. :smile:

**Comment by DHowett-MSFT** [comment]
I'd guess solidly 80% of the time the console resizes the user did it and wants to interact with it in the same way/place they were. An application should be ready to deal with the console's viewport or contents changing _as a result of user action._ This is one of the bad/annoying things about the Windows console APIs that we just have to keep supporting. Sorry!@

**Comment by x1bzzr** [comment]
How should an application deal with a scroll due to a resize if it wants to have the cursor at the bottom of the screen given that the application can only know about a resize *after the fact*? It seems to me that, if a resize happens when the cursor is at the bottom line, that will always trigger a scroll, which the application can then only *react to* by scrolling the viewport back up and finally redrawing the screen. This will introduce flickering as the application states before and after the resize will be separated by a third intermediary state in which the lines were scrolled down. Couldn't an application choose to opt-out of this behavior?
