### ISSUE TITLE
IS_GLYPH_CHAR macro returns the opposite of what it should

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#4185]
I apologise for not using the template, but this isn't exactly a bug - it's more of a code-health issue. 

The way `IS_GLYPH_CHAR` is defined, it returns TRUE for C0 control characters and DEL, which is the exact opposite of what you would expect.

https://github.com/microsoft/terminal/blob/6f667f48ae109d4291cda1f8d4e977315c0dae8a/src/host/_stream.cpp#L30

The only place it's used is here:

https://github.com/microsoft/terminal/blob/6f667f48ae109d4291cda1f8d4e977315c0dae8a/src/host/_stream.cpp#L398-L400

Clearly the intention is that the branch should be followed if the char is actually a glyph (or we're in unprocessed mode), but its had to be written as `!IS_GLYPH_CHAR` to work around the macro being backwards (which just makes the code incredibly confusing).

**Comment by zadjii-msft** [comment]
Wow yea that absolutely is confusing.
