### ISSUE TITLE
\r ends up unescaped in formatted copy on blank lines

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#4187]
Introduced by #2038

Select some text in terminal, copy and paste to e.g. Word. For every blank line in terminal there, are 2 blank lines in the output. One from `<BR>` and one from `\r`, which sneaks in unescaped.

**Comment by zadjii-msft** [comment]
Wow yea that's absolutely true. Good catch 😄

**Comment by DHowett-MSFT** [comment]
That's not great! Thanks.
