### ISSUE TITLE
Add setting to select which formats of copy to perform (text, rtf or html)

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#4191]
# Description of the new feature/enhancement

This is extension of #2690, which would allow to separately enable/disable all formats of copy, which there are currently 3, but might be more in the future.

Why disable? Ideally, all editors should well handle these formats, allow selection etc. However, in addition to what #2690 stated,, certain editors might for example better support RTF that HTML or whatever format there might be (I still think about #1084).

# Proposed technical implementation details (optional)

This might either be a profile setting in form of:

`"copyFormats": "text,html,rtf"`

or an argument on copy action, when that is the thing. You could the just remove one or more of these formats, e.g. keep only plain text.

**Comment by DHowett-MSFT** [comment]
This could do with a mini spec (perhaps in the discussion here?) before we go ahead on implementation.

**Comment by shanselman** [comment]
How about just two commands? copy and copyPlain? Would be far simpler.
