### ISSUE TITLE
Touchpad scrolling much faster than other apps

### ISSUE THREAD

**Issue by setek** [microsoft/terminal#4193]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows NT 10.0.19041.0
Windows Terminal 0.7.3451.0

Using MS Surface Pro 7 type cover's touchpad. Haven't tested with mouse scroll wheels or others, but I can and get back to you.

# Steps to reproduce

Have enough in buffer to scroll for a while, like a man page or something.
Scroll

# Expected behavior

Scrolls as fast as all other apps, eg. Hyper, or a browser window. Able to scroll to and read what I want to read.

# Actual behavior

Scrolls so fast I either end up at the top or the bottom. I can't scroll bit by bit to read a man page.

**Comment by j4james** [comment]
This sounds like a duplicate of #1066.

**Comment by setek** [comment]
Ooops, my bad, I scrolled through open issues and couldn’t find one.
