### ISSUE TITLE
Can't run Windows Terminal with parameters

### ISSUE THREAD

**Issue by amirrammari** [microsoft/terminal#4195]
Hello, I running Windows Terminal with this command but this command not working

`
C:\Users\Amir\AppData\Local\Microsoft\WindowsApps\wt.exe -noexit -command Set-Location -literalPath '%V'
`

**Comment by zadjii-msft** [comment]
Hey wadda ya know, we're actually currently working on adding support for commandline arguments to the terminal. See #607, #3495, #4023. Granted, we're not planning on adding the args you've suggested here, but I think `wt -d %V` might be what you're looking for, once #4023 lands.

/dup #607
