### ISSUE TITLE
Deselected current tab when pressed Ctrl+Click

### ISSUE THREAD

**Issue by amirrammari** [microsoft/terminal#4196]
Hello,
When pressing the Ctrl button and clicking on the current tab, current tab will be deselected.
![Windows Terminal](https://user-images.githubusercontent.com/23485114/72271987-2206d700-363d-11ea-9f6d-937328b1fd4a.gif)

**Comment by DHowett-MSFT** [comment]
Funny you should mention this! We just got a fix in with #4024 :smile:
