### ISSUE TITLE
Control-Alt-z is sending the code for Control-z

### ISSUE THREAD

**Issue by amareshjoshi** [microsoft/terminal#4201]
when i type (in emacs) control-alt-z (C-M-z) the terminal interprets it as control-z.

i can type other C-M combos. for eaxmple C-M-f is different from C-f.
but it doesn't work for C-M-z. i can get the right behavior using:
ESC (and release) and then pressing C-z

curiously it does work properly in the regular wsl.exe application.

**Comment by zadjii-msft** [comment]
note to self: this is a conpty bug, not a Terminal bug:
![image](https://user-images.githubusercontent.com/18356694/76772761-70387380-676f-11ea-9a79-526e27b6645a.png)


We're probably mis-translating the `^[^Z` as <kbd>Ctrl+Z</kbd>
