### ISSUE TITLE
Not able to maintain scroll position if terminal is outputting new data, have to fight the scroll bar

### ISSUE THREAD

**Issue by awarmfastbear** [microsoft/terminal#4205]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.18362.535]  

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.7.3451.0

Any other software?

```

Apologies if this has been reported already..

# Steps to reproduce

Throw this in a bash terminal and run it on the Microsoft Terminal, it's just a simple counter loop:

```
 my_count=0
 while [  $my_count -lt 1000 ]; do
     echo The count is $my_count
     let my_count=my_count+1
     sleep 0.1
 done
```

Now try and scroll up and the scroll location will keep changing as more output is received. The terminal should lock is position and ignore the additional output so the operator can focus on the output they are viewing instead you have to fight to maintain your position.

# Expected behavior

As the Windows Terminal outputs more information, your scroll position should remain unchanged, you shouldn't have to fight to stay where you are.

# Actual behavior

The Windows Terminal will shift your view for each new line of output, the faster the output the harder it is to stay in one position

**Comment by j4james** [comment]
This sounds like a duplicate of #3863.

**Comment by awarmfastbear** [comment]
Yep, it is! Thank you.
