### ISSUE TITLE
Make tab clickable on top border in fullscreen mode

### ISSUE THREAD

**Issue by anki-code** [microsoft/terminal#4207]
For example we have two tabs and the window in fullscreen mode. We want just move the mouse to the top right corner (first line of pixels on the screen) and click the tab. But we can't do it because tabs aren't clickable on the top border:

![image](https://user-images.githubusercontent.com/1708680/72341739-0f8faa80-36dc-11ea-8b8a-70dae133eb6c.png)

Please make it clickable to fast selecting without precise aiming )

**Comment by zadjii-msft** [comment]
Thanks for the report! I believe this is actually /dup #2541, or at least should be handled at the same time.
