### ISSUE TITLE
terminal have many garbled!!!

### ISSUE THREAD

**Issue by zFitness** [microsoft/terminal#4210]
# Environment

```none
Windows10 Professional  x64 1909
Windows Terminal (Preview) Version: 0.7.3451.0
```

# Steps to reproduce
* use gitbash as default shell
* Typing ls, Chinese characters appear in windows terminal, but no garbled characters appear in gitbash.
* Vim for gitbash is garbled

# Expected behavior
The tool is powerful.I hope no Chinese garbled. Thanks!

# Actual behavior
Many commands are garbled. I recorded a video. 
[video](https://drive.google.com/open?id=14AODpGXVB4hNukjFv4NwUwbG3PXL88JA)

**Comment by zadjii-msft** [comment]
This looks to me like maybe the `LANG` values are different for gitbash running in the Windows Terminal vs running in the legacy console. Note how when you open vim, there's a difference in the footers on the left side:
![image](https://user-images.githubusercontent.com/18356694/72349431-23b6b600-36a2-11ea-8a14-d6e2f46d5324.png)


Could you share what the output of `locale` is in both the original console and in Windows Terminal? For me it looks like:
![image](https://user-images.githubusercontent.com/18356694/72349477-37fab300-36a2-11ea-8b85-049d136ba4ca.png)

**Comment by zFitness** [comment]
thank you for your reply. Two vim locales seem to be different. 
Vim of gitbash is in Chinese, and vim of terminal is in English. So there's a difference in the footers on the left side.  @zadjii-msft 
[locale](https://drive.google.com/open?id=1KIE3AN5D3KnVZAbkP6BxBBSN987I9TAx) 

> This looks to me like maybe the `LANG` values are different for gitbash running in the Windows Terminal vs running in the legacy console. Note how when you open vim, there's a difference in the footers on the left side:
> ![image](https://user-images.githubusercontent.com/18356694/72349431-23b6b600-36a2-11ea-8a14-d6e2f46d5324.png)
> 
> Could you share what the output of `locale` is in both the original console and in Windows Terminal? For me it looks like:
> ![image](https://user-images.githubusercontent.com/18356694/72349477-37fab300-36a2-11ea-8b85-049d136ba4ca.png)

**Comment by zadjii-msft** [comment]
@zFitness Is there a reason you've re-opened this issue? It looks to me like this wasn't a problem with the Terminal, but instead it was a configuration for gitbash.
