### ISSUE TITLE
Documentation advice results in error

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#4214]
In https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#setting-the-startingdirectory-of-wsl-profiles-to- it is suggested to use $WSL paths but if you do, you'll get the following error:

```
'\\wsl$\Ubuntu\home\stan'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

**Comment by DHowett-MSFT** [comment]
And just to confirm, you did this with a _wsl_ profile? One that launches wsl, and not CMD.exe?
Interesting!

**Comment by Stanzilla** [comment]
Yup, it was 

```jsonc
{
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory" : "//wsl$/Ubuntu/home/stan"
},
```

**Comment by DHowett-MSFT** [comment]
I can't reproduce this; my WSL profile is actually launching WSL. Curious!

Now, if I launch cmd from WSL (_or a script does it for me (!)_), I do get the error in your original report.

```
(Libra) ~ % cmd.exe /c dir \\
'\\wsl$\Debian\home\dustin'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
 Volume in drive C is γ
 Volume Serial Number is B645-B3DE

```

That's unavoidable, and if something on in your startup scripts is shelling out to cmd.exe that's just not something we can help with.

**Comment by DHowett-MSFT** [comment]
FWIW: if that's the case, this should also happen if you use `wsl.exe -d Ubuntu ~` from outside WT.

**Comment by Stanzilla** [comment]
Oh interesting, it does happen with `wsl.exe ~ -d Ubuntu` as well. Guess it's a user error then?

**Comment by DHowett-MSFT** [comment]
I wouldn't go so far as to call it _user error_, it's just that.

* interop (wsl -> windows) attempts to inherit the current working directory, possibly through path translation
* translating a WSL working directory that has no mapping to the windows filesystem yields a `\\wsl$\$DISTRIBUTION` path
* that is, unfortunately, a UNC path
* CMD cannot run from a UNC path
* CMD prints an error message on startup when it's run from a UNC path
