### ISSUE TITLE
Crash when moving tab in admin mode

### ISSUE THREAD

**Issue by K-miy** [microsoft/terminal#4215]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.7.3451.0

OS version : 10.0.19041.2.0.0.256.48

```

# Steps to reproduce

- Launch windows terminal as an admin
- Try to move a tab (even the first)
- OR add a tab (or two) and try to reorder them

# Expected behavior

the tab will move to the assigned place like it does when not lauched as an admin

# Actual behavior

Windows Terminal terminates without any error messages.

**Comment by Harmon758** [comment]
Duplicate of #3581

**Comment by carlos-zamora** [comment]
Thanks @Harmon758. \dup #3581
