### ISSUE TITLE
Change tab-title back to default after closing SSH-connection 

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/terminal#4220]
Right now, when I ssh into a server (example.com), the tab-title changes to something like `root@example.com:~`. When I type `exit` or the SSH-connection self-closes, the title still persist.

This is somehow confusing, especially when SSH-connections auto-close, but the title imposes, as if the connection is still up.

## Expected behavior:
- Open a new tab (or window): title shows as specified in `profiles.json`
- Open SSH-connection: title changes to `root@example.com:~`
- Close SSH-connection: title changes back, to the setting from `profiles.json`

## Actual behavior:
- Open a new tab (or window): title shows as specified in `profiles.json`
- Open SSH-connection: title changes to `root@example.com:~`
- Close SSH-connection: title still `root@example.com:~`

**Comment by DHowett-MSFT** [comment]
This is because your shell (cmd, powershell) is not resetting the title to what it was before ssh started. This isn't something Terminal can help.
