### ISSUE TITLE
Support key-bindings for "Find up" and "Find down"

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/terminal#4221]
The default user-behaviour when searching something in code-editors is to "Ctrl+G" and "Ctrl+Shift+G" through the search results. Would be nice in addition to the current find-feature.

**Comment by DHowett-MSFT** [comment]
As a workaround, you can use <kbd>Shift+Enter</kbd> (instead of Enter) to flip the direction for a single search when the search flyout is open.

**Comment by carlos-zamora** [comment]
This should be a part of the #3920 scenario.

**Comment by Don-Vito** [comment]
@carlos-zamora - isn't it the same as https://github.com/microsoft/terminal/issues/7695. Since then it will be solved by  @Hegunumo in https://github.com/microsoft/terminal/pull/8522

**Comment by ad-on-is** [comment]
@Don-Vito yes... it's the same. Thanks! (y)

**Comment by DHowett** [comment]
/dup #7695 even though I don't love duping lower numbers to higher ones!
