### ISSUE TITLE
The word become very small when list docker containers

### ISSUE THREAD

**Issue by WhiteGreeny** [microsoft/terminal#4225]
# Environment

Windows build number: 10.0.18362.535
Windows Terminal version (if applicable):0.7.3451.0
Native resolution: 1920 x 1080(17.3")
Romote server: Ubuntu 18.04.1 LTS
FontFace: Sarasa Mono SC
Docker version:
![image](https://user-images.githubusercontent.com/19926964/72397509-14576b80-377b-11ea-8e80-ab0b46a0dcc8.png)

# Steps to reproduce
use ssh connect to a server that installed docker and execute "docker ps" or "docker container ls -a"

# Expected behavior
show the docker container list

# Actual behavior
![image](https://user-images.githubusercontent.com/19926964/72396859-ff79d880-3778-11ea-8c6a-0e68c36596c6.png)
the word become so small

**Comment by WhiteGreeny** [comment]
i changed fontface from "Sarasa Mono SC" to "Sarasa Term SC"，and it's work.

**Comment by zadjii-msft** [comment]
I'm glad you were able to fix this! This looks like a /dup of #610
