### ISSUE TITLE
Closing tabs with the mouse wheel button causes an immediate crash of the entire Terminal

### ISSUE THREAD

**Issue by glitch100** [microsoft/terminal#4230]
I assume this is to do with the `TabViewItem.CloseRequested` Event not being respected properly or some sort of bad subscription to it. 

For what it's worth I would be happy to take a swing at this one if you aren't going to prioritise it but would need some pointers. CPP isn't my main, (C# is) but I suspect the event that is required or used somewhere might be in the CPP modules.

# Environment

```none
Windows build number:  Win32NT 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.8.10091

Any other software?
None
```

# Steps to reproduce
- Open Terminal
- Add new Tab
- Use Mousewheel to second tab
- **Crash**

# Expected behavior
New tabs being closed don't cause crashes

# Actual behavior
New tabs being closed by mousewheel cause issues

**Comment by zadjii-msft** [comment]
Does this only happen with certain profiles and not others? I can't get this to repro on 0.8 myself, but who knows. There could be any number of reasons why this is happening, it's hard to say definitively without a stack trace. Could you maybe capture it with the Feedback hub and share the link, so we could investigate? /feedback

Though, if you're feeling brave enough to build the code and repro this under the debugger, you'll probably get a lot more relevant information than the Feedback hub can give us.
