### ISSUE TITLE
Powerhsell / CMD as admin

### ISSUE THREAD

**Issue by kramit** [microsoft/terminal#4231]
There may already be a way to do this with adding some info into the JSON profiles.

On the drop down menu for selection of terminal to open in a new tab add options for "powershell (admin) and cmd (admin)" there is still quite a few operations that I need to run as admin and adding a new section into the profiles JSON and calling an admin powerhsell terminal makes it pop out into the old terminal. 

Is there a way of acomplishing this? Or is it something that is on the roadmap

**Comment by gerardog** [comment]
Workaround: Install [gsudo](https://github.com/gerardog/gsudo) and add a new profile:

```
    {
      "guid": "{0667cbea-6f8d-43d6-b50a-e4f795569d86}",
      "name": "Elevated PowerShel",
      "commandline": "gsudo.exe PowerShell",
      "hidden": false
    },
```
