### ISSUE TITLE
Terminal not focused on Taskbar after startup

### ISSUE THREAD

**Issue by BalintFarkas** [microsoft/terminal#4233]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10091.0
Any other software? none
```

# Steps to reproduce

Pin Terminal to the Taskbar. Start Terminal using its hotkey (e.g. Windows + 5 if it is the 5th item on the taskbar).
Terminal starts, but its icon isn't highlighted.
If you press the hotkey again, the expected behavior is that the window becomes minimized. Instead, the icon becomes highlighted, and it only becomes minimized after pressing the hotkey yet again.

# Expected behavior

When Windows Terminal starts up, its icon is highlighted right away on the Taskbar, and pressing its hotkey (e.g. Windows + 5) minimizes the window on the first attempt.

![image](https://user-images.githubusercontent.com/11557213/72427706-a025c380-378c-11ea-8ba6-c38cf00d05e0.png)

# Actual behavior

When Windows Terminal starts up, its icon isn't highlighted, and pressing its hotkey (e.g. Windows + 5) only minimizes the window on the second attempt.

![image](https://user-images.githubusercontent.com/11557213/72427689-9a2fe280-378c-11ea-983e-e524cebb043f.png)

**Comment by DHowett-MSFT** [comment]
I think this is an issue that's fixed in the upcoming Windows release. Classic packaged win32 applications were having trouble coming to the foreground on launch in all instances.

**Comment by BalintFarkas** [comment]
OK, great news, thank you!
