### ISSUE TITLE
terminal.dmg

### ISSUE THREAD

**Issue by include** [microsoft/terminal#4235]
Hi,

First and foremost, finally a decent terminal for Windows. Thank you 👍 
So... title says everything :) are there any plans for porting it to macOS? :)

Cheers,
F

**Comment by electronic-dk** [comment]
AFAIK, Terminal relies heavily on windows-specific components, particularly ConHost and WinUI, so it's highly unlikely it will ever be ported to other systems.

**Comment by zadjii-msft** [comment]
Yea, there's a ton of duplicate issues for this topic already on this repo. Including, but not limited to:
From https://github.com/microsoft/Terminal/issues/498#issuecomment-490091740 
> We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.

s/linux/macOS/

/dup #2331 #504 #563 #624 #2466 #699
