### ISSUE TITLE
Error "The specified user does not have a valid profile" after updating to 0.8

### ISSUE THREAD

**Issue by RoguePointer80** [microsoft/terminal#4237]
# Environment

Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable): 0.8

# Steps to reproduce

Turn on the computer in the morning. Let Microsoft Store do its updates.
Windows Terminal now at v0.8.
Click on the pinned icon on the taskbar (I use it every day all day, so I pinned it there)
The program does not start, instead a dialog is presented with the path to the main executable and the error message "The specified user does not have a valid profile.

I then made a backup of my profiles.json file, deleted it (expecting it to be created fresh), restart the app; same behaviour.
I then went to Add Remove Programs, uninstalled Windows Terminal. Then re-install it from the Windows Store; same behaviour.

# Expected behavior

When I click on the icon, the program starts.

# Actual behavior

![image](https://user-images.githubusercontent.com/30326057/72438060-123cdf00-3772-11ea-8de6-d9430bd52f4e.png)

**Comment by DHowett-MSFT** [comment]
We have not been able to reproduce this issue. If you reboot the computer, does it help?

**Comment by RoguePointer80** [comment]
Somehow, rebooting the computer fixed the issue. I hate when it does that.
Not much to work with; I guess you can close this issue, maybe it wasn't related to Terminal after all. (strange that the rest of my programs worked).
