### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Goatmaster** [microsoft/terminal#4241]
I really would like to have the option for a folder in the overview of my sessions.

I have multiple saved sessions for a direct ssh connection to my virtual machines. So it would be really nice to have to option to create different folders where I can categorize the different ssh sessions.

To understand it a bit better I have a screenshot of super putty which I used before.

![screen](https://user-images.githubusercontent.com/12907358/72443304-55b53e80-37ae-11ea-8935-3d0b08a22525.png)

**Comment by ffes** [comment]
/dup of #2330 which is a /dup of #1571

**Comment by zadjii-msft** [comment]
Yep, that looks like a dupe to me. Thanks for finding those @ffes!

/dupe #1571 #2330
