### ISSUE TITLE
Swift REPL can't readLine()

### ISSUE THREAD

**Issue by eddydu44** [microsoft/terminal#4243]
# Environment

```none
Windows build number: 10.0.19541.0
Windows Terminal version : 0.7.3451.0
```

# Steps to reproduce

```
root@EDDY:/mnt/c/Users/eddyb# swift
Welcome to Swift version 5.1.3 (swift-5.1.3-RELEASE).
Type :help for assistance.
  1> var test = readLine()
the text
Not working when I press ENTER
have to do Ctrl + Z
^Z
[1]+  Stopped                 swift
```

# Expected behavior

Should read my input

# Actual behavior

I can't use readLines() functions, any idea why ?
Thx

**Comment by DHowett-MSFT** [comment]
Does this reproduce outside of Windows Terminal?

**Comment by eddydu44** [comment]
Yes, so I alternatively launch swift with a file as argument and now readLine() works. Maybe it's a problem from Swift ...
