### ISSUE TITLE
"splitPane" key binding action schema is missing "auto" as a valid split type

### ISSUE THREAD

**Issue by 0xabu** [microsoft/terminal#4245]
# Environment

```none
Windows build number: 10.0.18363.592
Windows Terminal version: 0.8.10091.0
```

# Steps to reproduce

Add a keybinding for the auto splitPane action introduced by #4025. Open the profile in vscode. Observe warning squiggly:

![image](https://user-images.githubusercontent.com/13037682/72460815-65b72900-3782-11ea-9573-d5644239847c.png)

# Expected behavior

No squiggly.

# Actual behavior

Looks like the schema is missing "auto" as a valid option.

**Comment by mkitzan** [comment]
Nice catch! I think I've got a fix for this.
