### ISSUE TITLE
Keyboard input blocked for all profiles

### ISSUE THREAD

**Issue by ev-dev** [microsoft/terminal#4257]
# Environment

```none
Windows build number: 10.0.19541.0
Windows Terminal version (if applicable): 0.8.10091.0

Any other software? n/a
```

# Steps to reproduce

1. Update Terminal from WIndows Store
2. Open Terminal, begin typing.
3. Try all other profiles, revert settings to default, uninstall/reinstall, remain sad :(
# Expected behavior
Keyboard input should be passed into the Terminal's shell stdin, opening new tabs/profiles & switching between them should not effect user input.

# Actual behavior
After updating to v0.8 I've been unable to type normally into any profile. Tried reverting my settings to default and reinstalling Terminal app but still very odd keyboard input bug. Both physical & on-screen keyboards are unable to send any keystrokes to any shell. 

Even more strange, creating a new tab will _occassionally_ allow normal input functionality however if you attempt to create/switch tabs or change focus to outside the Terminal app window, I am back to no input passing through. 

Please watch this clip closely to see the extremely bizarre behavior I am experiencing...

![ezgif-7-166e735da314](https://user-images.githubusercontent.com/26840537/72523477-e1ba7b00-382d-11ea-82e5-477c58f6e2a5.gif)

**Comment by ev-dev** [comment]
Latest insider's build came out today (10.0.19546.1000) and now I no longer experience the input issues. 

No idea what was causing the bug but seeing as clean reinstalls didn't help me when I was troubleshooting. there must've been something corrupt affecting Terminal that the update processes resolved. 

Problem might still come up for other users but if there's no hits here soon probably just close it 👍

**Comment by DHowett-MSFT** [comment]
Thanks for following up! Closing for now.
