### ISSUE TITLE
Built Windows Terminal asserts with an abort()

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/Terminal#426]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 1809 (17763.475)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Built the repo using the instructions in the readme (w/VS 2017 x86 native prompt).  When I run `Debug\WindowsTerminal.exe` I get this error:

![image](https://user-images.githubusercontent.com/5177512/57248616-05bb9080-7000-11e9-9d7e-7268d01a5286.png)

* What's wrong / what should be happening instead:
The app should start unless I need to be on a newer version of Windows?

**Comment by miniksa** [comment]
Psychic debugging says you're trying to use x86 on an amd64 machine. Build the other architecture.

Actual debugging, can you do the Retry button and get me the stack?

**Comment by rkeithhill** [comment]
What version of VS do you recommend to build with?  I have both VS 2017 and VS 2019.  Also, 32-bit binaries normally run just fine on 64-bit Windows.

**Comment by miniksa** [comment]
VS 2017 is what I use, but I should probably move over to 2019. I've heard from others on the team that it works in both.

This is a little different because the console host is a part of the package to provide bleeding-edge conpty support to the Windows Terminal application. The console host has to match architecture of the underlying system.

**Comment by rkeithhill** [comment]
![image](https://user-images.githubusercontent.com/5177512/57250584-0efb2c00-7005-11e9-96e5-3177d9fdf9e9.png)
 
![image](https://user-images.githubusercontent.com/5177512/57250594-17536700-7005-11e9-9743-b07a4bb19e23.png)

This is with `WindowsTerminal (Windows Store 10.0)` set as the startup project.

**Comment by zadjii-msft** [comment]
Oh, you're gonna want to set CascadiaPackage as the startup project

**Comment by rkeithhill** [comment]
Ah, and I do need to be on a newer version of Windows 10:

![image](https://user-images.githubusercontent.com/5177512/57250805-85982980-7005-11e9-8778-a55c59df179c.png)

Is that `1903` or post `1903`?

**Comment by rkeithhill** [comment]
Might want to update the readme with a few basic prereqs like:

* Windows 10 1903 or later
* Enable Windows Developer Mode
* Visual Studio 2017 (with desktop C++ and UWP workloads installed)

**Comment by codecat** [comment]
I saw you editing your comment.. :) So it does require 1903? `OpenConsole.exe` just opens a regular old cmd on my machine. (Still running 1803 though..)

**Comment by rkeithhill** [comment]
Yeah, `OpenConsole.exe` does not seem to be *the* interesting exe.

**Comment by miniksa** [comment]
`OpenConsole.exe` will work on things before 1903, but is "not the interesting EXE" in that it is not where the Terminal is. It is where the console host is, however, including the PTY engine and all the other services required to make this work. So in that way, it is interesting to some degree.

You should probably be on 1903 to get the whole Windows Terminal going. 

And yes, we should probably update the README. We're a bit inundated today and this week with Build, so I'd be happy to take a PR with those changes if you want to send it!

**Comment by bschoepke** [comment]
I'm on a 1903 build (internal, 18865) and still see the old cmd.exe when I run Cascadia

**Comment by rkeithhill** [comment]
It looks like the the terminal is a UWP/Store app so then it is true that you need to enable Windows Developer Mode in order to side-load the app?

**Comment by zadjii-msft** [comment]
@bschoepke try pressing ctrl+t

The default settings for winterm right now are specifically designed to make it look like conhost+cmd.exe out of the box.

**Comment by bschoepke** [comment]
Pressing Ctrl + T does indeed show the XAML tab bar and settings menu, thanks. 

I also realized I don't have the 1903 SDK installed (https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk) and I'm guessing that's needed to get the new UI on F5 deployment

**Comment by zadjii-msft** [comment]
@rkeithhill I believe that's correct, but I haven't had Developer Mode disabled in the longest time, so I can't be sure.

@bschoepke I'll make a note of that in the README

**Comment by keithn** [comment]
I seem to be having a LOT of problems trying to build it in 2019

**Comment by matthew4850** [comment]
I was able to get it to compile, see my reply in #435

**Comment by shuffle2** [comment]
@zadjii-msft is there a reason it isn't just made the default in the .sln file? (first listed project should become default startup project, normally..)

I decreased the version in CascadiaPackage/Package.appxmanifest to 10.0.17763.404, and the app crashes on launch now:
```
 	TerminalApp.dll!winrt::impl::consume_Microsoft_UI_Xaml_Controls_ITabViewFactory<winrt::Microsoft::UI::Xaml::Controls::ITabViewFactory>::CreateInstance(const winrt::Windows::Foundation::IInspectable & baseInterface, winrt::Windows::Foundation::IInspectable & innerInterface) Line 5196	C++
 	TerminalApp.dll!<lambda_8456af98b166b0be9dea16317fc91623>::operator()<winrt::Microsoft::UI::Xaml::Controls::ITabViewFactory const &>(const winrt::Microsoft::UI::Xaml::Controls::ITabViewFactory & f) Line 18959	C++
 	TerminalApp.dll!winrt::impl::factory_cache_entry<winrt::Microsoft::UI::Xaml::Controls::TabView,winrt::Microsoft::UI::Xaml::Controls::ITabViewFactory>::call<<lambda_8456af98b166b0be9dea16317fc91623> &>(winrt::Microsoft::UI::Xaml::Controls::TabView::{ctor}::__l2::<lambda_8456af98b166b0be9dea16317fc91623> & callback) Line 5440	C++
 	TerminalApp.dll!winrt::impl::call_factory<winrt::Microsoft::UI::Xaml::Controls::TabView,winrt::Microsoft::UI::Xaml::Controls::ITabViewFactory,<lambda_8456af98b166b0be9dea16317fc91623> >(winrt::Microsoft::UI::Xaml::Controls::TabView::{ctor}::__l2::<lambda_8456af98b166b0be9dea16317fc91623> && callback) Line 5501	C++
 	TerminalApp.dll!winrt::Microsoft::UI::Xaml::Controls::TabView::TabView() Line 18959	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::App::_Create() Line 85	C++
 	TerminalApp.dll!winrt::TerminalApp::implementation::App::Create() Line 70	C++
 	TerminalApp.dll!winrt::impl::produce<winrt::TerminalApp::implementation::App,winrt::TerminalApp::IApp>::Create() Line 428	C++
 	WindowsTerminal.exe!winrt::impl::consume_TerminalApp_IApp<winrt::TerminalApp::IApp>::Create() Line 18	C++
 	WindowsTerminal.exe!AppHost::Initialize() Line 72	C++
 	WindowsTerminal.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 46	C++
```
```
Exception thrown: read access violation.
pPLMHandler was nullptr.
```
It also took quite a while to figure out what packages had to be installed via the VS2017 Installer. I wound up installing ~11GB of crap I probably don't need. It would be great to have a min list / script to do that.

fun...

**Comment by miniksa** [comment]
OK. This has turned into a grab bag of assorted build issues and many of them are already resolved. The rest of it is trying to move versions down which we don't support. I'll close this in favor of the other issues hanging around.
