### ISSUE TITLE
process exited with code 9009

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#4263]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): Version: 0.8.10091.0

Any other software?
```

# Steps to reproduce

1) split screen (ALT+SHIFT+-)
2) type 'exi'
3) type 'exit'

# Expected behavior

the Pane should close normally?

# Actual behavior

![exi_or_exit](https://user-images.githubusercontent.com/7850737/72558123-5f1fd300-38a2-11ea-9942-1788fe72a258.gif)

**Comment by DHowett-MSFT** [comment]
This is in line with how bash and zsh work when presented with an invalid command before they exit.

**Comment by viniciusvillas** [comment]
@DHowett-MSFT , what does that mean? Just because they do it this way then Windows Terminal will follow them? Why?

**Comment by DHowett** [comment]
This behavior exists to stop an error message printed out by a program from _disappearing instantly_ when it exists. There is a class of applications for which that is extremely important. We're following this behavior because it is the right brhavior to follow, _and because you can turn it off with a config option very easily._

**Comment by Luuk34** [comment]
The config option is: "closeOnExit": "always"

**Comment by viniciusvillas** [comment]
> This behavior exists to stop an error message printed out by a program from _disappearing instantly_ when it exits. There is a class of applications for which that is extremely important. We're following this behavior because it is the right brhavior to follow, _and because you can turn it off with a config option very easily._
Thank you so much for clarifying! ;)
