### ISSUE TITLE
Spawn the same shell type when terminal is split vertical or horizontal and not the default

### ISSUE THREAD

**Issue by api0cradle** [microsoft/terminal#4264]
# Description of the new feature/enhancement
A problem I have is that I want to be able to create different profiles for lets say cmd.exe with different backgrounds. Profiles could be ssh, proxy etc... When I create a tab with for instance ssh and I want to have two or maybe three ssh cmd windows split either horizontal or vertical I cannot use the ctrl+shift+r or ctrl+shift+i, because that will spawn a window in my tab with the default profile. 

# Proposed technical implementation details (optional)
I would like to have a possibility to have an inherit true or false for each profile so when it is set to true and I use the split horizontal or vertical it creates the same type of profile window as the first one. 

Or if it would be possible get a menu to choose from when you are about to do a split so you can choose which one you want to use in the split.

See the technical implementation...

**Comment by zadjii-msft** [comment]
@api0cradle Sounds to me like you're looking for some combination of the following issues:
* Allow the user's "open pane" bindings to open a pane with the current pane #1756
* Open panes with a specific profile #998
* Open a new pane by prompting the user for which profile to use #3586

**Comment by api0cradle** [comment]
Yes! Something like that would be awesome!

**Comment by DHowett-MSFT** [comment]
In that case, I'll close it as /dup #1756 #998 #3586. Thanks!
