### ISSUE TITLE
Clicking a tab and dragging causes a crash

### ISSUE THREAD

**Issue by EliScherrer** [microsoft/terminal#4270]
# Environment

```none
Windows build number: 10.0.18362.592
Windows Terminal version (if applicable): 0.8.10091.0

Any other software? n/a
```

# Steps to reproduce

Click on a tab and drag like you were going to move the tab order

# Expected behavior

As far as I know tab moving hasn't been implemented as a feature so nothing should happen.

# Actual behavior

The terminal immediately crashes.

**Comment by EliScherrer** [comment]
Yes I am

**Comment by zadjii-msft** [comment]
Good to know! This is actually /dup #3581 then. Thanks!
