### ISSUE TITLE
Retro Terminal Effect really slow in VM

### ISSUE THREAD

**Issue by htmsousa** [microsoft/terminal#4271]
# Environment

```none
Windows build number: [Version 10.0.19041.21]
Windows Terminal version (if applicable): 0.8.10091.0

Any other software? Running Windows Insider Preview Build within a virtual machine (4 cores at 4.20GHz, 16Gb RAM) on Hyper-V
```

# Steps to reproduce

Activate flag ```"experimental.retroTerminalEffect":true```

# Expected behavior

Retro Terminal Effect is applied

# Actual behavior

Retro Terminal Effect is indeed applied, but any terminal (powershell, debian, etc) with that flag activated becomes really slow (even just typing). Looking at task manager while typing some command, the CPU goes to near 100% usage on all 4 cores. 
Setting the flag to ```false``` makes everything to work as usual.
Could it be caused by the fact it is running within a virtual machine? Or maybe because Hyper-V doesn't allow to use Physical GPU in the VM and it has to rely on CPU only to do the rendering?
The main system has the latest Windows Release Build, not the Insider Preview Build and I can't test the terminal outside the VM.

**Comment by DHowett-MSFT** [comment]
If you're running on CPU rendering, this is expected. I don't know if that's the case for a VM.

> The main system has the latest Windows Release Build, not the Insider Preview Build and I can't test the terminal outside the VM.

The latest windows release build is 1903 or 1909, which _does_ support Terminal.

**Comment by htmsousa** [comment]
> The latest windows release build is 1903 or 1909, which does support Terminal.

My bad.. didn't realise it was already supported by latest release. I tested in the main SO which has the GPU available and terminal windows are not slow when the retro terminal effect is active.

> If you're running on CPU rendering, this is expected. I don't know if that's the case for a VM.

Fair point. Maybe there should be a note somewhere saying that if GPU is not available (which is very unlikely, apart usage within VMs), this is pretty much "useless".

**Comment by jantari** [comment]
I don't think a note is needed.

Graphics effects of all kinds are usually very slow when done by CPU software rendering, this has been true and universally known for decades. It doesn't have anything to do with Windows Terminal really, and the effect isn't enabled by default either. You can also pass a GPU through to the VM to mitigate this problem.

**Comment by Wartoz** [comment]
this option eats a lot of GPU resources 😥

**Comment by Piruzzolo** [comment]
Still present in Terminal version 1.5.10411.0

**Comment by zadjii-msft** [comment]
@Piruzzolo Yep. As noted above: 

> Graphics effects of all kinds are usually very slow when done by CPU software rendering, this has been true and universally known for decades. It doesn't have anything to do with Windows Terminal really, and the effect isn't enabled by default either. You can also pass a GPU through to the VM to mitigate this problem.

**Comment by Piruzzolo** [comment]
> @Piruzzolo Yep. As noted above:
> 
> > Graphics effects of all kinds are usually very slow when done by CPU software rendering, this has been true and universally known for decades. It doesn't have anything to do with Windows Terminal really, and the effect isn't enabled by default either. You can also pass a GPU through to the VM to mitigate this problem.

Yep, I'm now in GPU rendering and it's slow too. I think [this shader](https://github.com/microsoft/terminal/blob/7c42ed4cc3d76a60b9182897fe3e12ac90f2040e/samples/PixelShaders/Retro.hlsl) is the problem. It may be simplified/optimized in some way

**Comment by zadjii-msft** [comment]
Yep, that is _the_ shader responsible for retro effects. We'd be happy to review any PRs to help optimize the effect if you can find something 😄 

Note that the biggest cause of slowdown while using shaders is the fact that we can't use differential drawing while shaders are enabled. Differential drawing lets us only update the parts of the screen that have changed from one frame to the next, and is a _massive_ perf improvement for the Terminal. #7147 is the closest thing we have to tracking "re-enable differential drawing when pixel shaders are enabled".

**Comment by Piruzzolo** [comment]
Maybe it would be easier of we don't use shaders for this effect and use a CRT-like font and a proper background, instead. This retro effect is so common that It would make sense to someway hardcode it. Or maybe precompute the visual rendering per-character and show the bitmap as the user types.
