### ISSUE TITLE
Error 0x800702e4 when launching `C:\Program Files\PowerShell\6\pwsh.exe']

### ISSUE THREAD

**Issue by ttoennies** [microsoft/terminal#4272]
I receive error  0x800702e4 when launching `C:\Program Files\PowerShell\6\pwsh.exe'] .  It occurs every time.

# Environment

```Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

 Occurs every time I launch Terminal
![2020-01-16_191640](https://user-images.githubusercontent.com/3342697/72576258-c3d43100-3894-11ea-9e5a-af1d9ad7ad04.png)

# Expected behavior

 Would like it to work.

# Actual behavior

 The error indicated above.

**Comment by ttoennies** [comment]
Oh that was embarrassing... thanks for the help.

**Comment by junior-ramone** [comment]
> 
> 
> Oh that was embarrassing... thanks for the help.

That issue helped me as I was facing the same problem, so thanks

**Comment by RufusJWB** [comment]
Same problem here. Would be good to have a more 'speaking' error message. I'll open an issue.

**Comment by ebicoglu** [comment]
This solved my problem:

![image](https://user-images.githubusercontent.com/9526587/148068511-a9a003d3-d99c-42ad-bd9f-cda8b8a5ec0b.png)
