### ISSUE TITLE
Feature Request: Context Menu for Tabs

### ISSUE THREAD

**Issue by tmknight** [microsoft/terminal#4276]
Each Tab should have a Context Menu (e.g. Close, size)

Currently, tab title text can be longer than the tab width, requiring scroll-right to get to the close button.

This is in reference to #1912, however, #1912 has become muddled and inactive regarding the original topic of content menu.

**Comment by zadjii-msft** [comment]
I'm closing this as it's a exact /dupe of #1912. That's not an _inactive_ issue, it's just _on the backlog_. When we're discussing larger features like that, it's helpful to have lots of requests in the thread, to help us understand the full scope of how the feature might be used, and lets us design the most flexible solution possible.
