### ISSUE TITLE
Error message when trying to provide a `--startingDirectory` to a WSL `wt.exe` command

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#4277]
(Follow-up from #4023)

Say you wanted to open a `Debian` WSL instance in `C:\Users`. According to the docs, you might try:

```
wt -d c:\Users wsl -d Debian
```

Unfortunately, this _won't_ work, and will give you an error about "expected exactly 1 argument to `--startingDirectory`, got 2". This is because we'll erroneously try to parse the `-d Debian` parameter as a second `--startingDirectory` value. This is unexpected.

**Comment by DHowett-MSFT** [comment]
Triaged into 1.x.
