### ISSUE TITLE
Evolve development guidance

### ISSUE THREAD

**Issue by giggio** [microsoft/Terminal#428]
The current developer guidance on `README.md` is incomplete. I tried restoring the project with `nuget`, but I needed the "Desktop devopment with C++" and "Universal Windows Platform Development":

![image](https://user-images.githubusercontent.com/334958/57252649-0dd8f780-7023-11e9-80d8-19b6954de5e1.png)

It would be nice to have a `build.cmd` or `build.ps1` script on the root to check for these things.

I only realized I needed them when I opened the solution on VS 2019.

I'm installing these things now. If I have to perform any other steps I'll document here.

**Comment by miniksa** [comment]
Thanks, much appreciated. We do definitely need to do this. We'll prioritize improving the README as issues come in, especially after we get back from the Build conference this week. (Most of us are on the show floor or presenting in one way or another!)

If you have anything you find out and want to make your first contribution be a pull request for the README to help others, please do so. We can approve PRs from the show floor more easily than produce quality content!

**Comment by giggio** [comment]
Cool. I'll document what I find here, and when I'm done I'll send a PR.

**Comment by giggio** [comment]
It seems I need VS 2017, I tried it with VS 2019 and some build errors pointed me that the I would need to retarget the solution, which I won't do. I'll try with 2017 now.

**Comment by brunofin** [comment]
I am trying to build this myself too, but I am required to download a total of 14 GB which I do not have available on my SSD, and I can't change the installation location.

Can we have a nightly build server of some sort set up?

**Comment by miniksa** [comment]
@brunofin, we're going to get a nightly build server set up to some degree. @DHowett-MSFT was working on our Azure Pipelines before Build, but now he's at Build like all the rest of us. I'm sure we'll get back to it in the coming weeks.

**Comment by zadjii-msft** [comment]
@giggio see #429 - pile on in the comments if you find something else.

@brunofin We do plan on having a nightly/weekly preview build available from the Store, once the Terminal is a bit more polished.

**Comment by Biswa96** [comment]
@brunofin Me too see this issue. I just move the VS and SDK folder in other drive/partition and make a directory symbolic link.

**Comment by lol768** [comment]
Would also like pre-built binaries! If it was painless as a recursive clone and a `./configure`/`make` I'd be more inclined to try it out

**Comment by zadjii-msft** [comment]
I'd really recommend against doing something like what @biswa96 mentioned - VS can be incredibly fragile sometimes, so I wouldn't trust that doing the above wouldn't lead to more insane issues in the future.

@lol768 Unfortunately I don't believe there's a way to install VS dependencies from the commandline quite yet. If there is though, I'd be super happy to review a PR that had a script to do that for you.

**Comment by JustJinxed** [comment]
Kind of a big deal for the README.md, to not include such information. Especially when a press release went out on this project today. *sigh*

**Comment by giggio** [comment]
Ok, I was able to build the solution, but it throws when running. I'll search and try to find the reason.

**Comment by giggio** [comment]
@zadjii-msft #429 looks good to me. I'm not on 1903 yet, so that is probably the terminal is throwing when I run it. It would be nice to add some type of warning that the required minimum Windows version was not met.
Feel free to close this issue when #429 is merged.

**Comment by snooopcatt** [comment]
Having same problem, naturally. Trying to build solution with community edition, lot of errors saying I miss: 
- windows SDK
- v141 build tools
- need to specify OutputPath (why though? couldn't that be provided in project config?)

Is there a way to conveniently install only parts that are required? I also have limited space on system drive.

**Comment by wangshubo** [comment]
LINK : fatal error LNK1104: 无法打开文件“atls.lib” [F:\windows_terminal\Terminal\src\host\exe\Host.EXE.vcxproj]

**Comment by zadjii-msft** [comment]
Fixed with #429
