### ISSUE TITLE
How to insert Unicode to file over SSH connection

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#4280]
I'm trying to paste `Unicode` which is 🔥 to file over `SSH` connection to my `CentOS 8` server.

I'm trying to paste the following to the file

```
function fish_title
    echo "🔥 AmericaN 🔥"
end
```

But upon trying to paste it into file.

I see the following:

```
function fish_title
    echo " AmericaN "
end
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/dOYjT.png

via `cat` command, still unable to see it.

here's the output of `locale` and `$TERM`

```
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```
❯ echo $TERM
xterm-256color
```

I'm pasting to the file using <kbd>CTRL+V</kbd> or <kbd>SHIFT+INSERT</kbd> or mouse right-click.

the `editor` is `nano`

**Comment by DHowett-MSFT** [comment]
The version of OpenSSH-Win32 that’s available today doesn’t support receiving Unicode. That has been fixed pending release!
