### ISSUE TITLE
Add privacy policy to about section

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#4281]
# Description of the new feature/enhancement

The Microsoft privacy policy should be added as a link in the About section of the Terminal.

https://privacy.microsoft.com/en-US/privacystatement

# Proposed technical implementation details (optional)

**Comment by reidrankin** [comment]
Forgive the necropost, but I was hoping that this issue would have a bit more documentation on the rationale for this change -- specifically, I'm trying to understand why exactly a terminal needs a privacy policy? [(Obligatory XKCD)](https://xkcd.com/463/)
