### ISSUE TITLE
Setting UI + logging

### ISSUE THREAD

**Issue by yellow-starburst** [microsoft/terminal#4283]
Ideas for improvement -
1. I noticed that the terminal is lacking a settings UI. This means that non-technical users have load VS just to change a simple color.

2. I would like to see the terminal have a logging setting, allowing users to save all commands whether it is powershell, cmd or whatever.

**Comment by zadjii-msft** [comment]
Thanks for the suggestions! These are actually both already tracked elsewhere on this repo - please make sure to search when filing new issues:

1. /dup #1564
2. /dup #642
