### ISSUE TITLE
DuplicateTab shortcut redo same splitedPane layout from previous tab.

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/terminal#4284]
When we using duplicate tab shortcut (default "ctrl+shift+d") if current Tab has splited panes replicate the same splited panes layout from current Tab in the next Tab.
![image](https://user-images.githubusercontent.com/13587928/72652888-6230c700-3967-11ea-8158-eda7b90301b5.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually a /dup of #1756.
