### ISSUE TITLE
Improve first-run experience for non-developer audience

### ISSUE THREAD

**Issue by pronichkin** [microsoft/terminal#4286]
I just started Terminal for the first time on a new machine, and I see Windows PowerShell using Courier New font.

I have heard that Terminal comes with a new font, and now I am puzzled why it's not the default. Ok maybe I need to change it manually in settings.

There's no visible Settings button or menu. I have to look around for it. Finally, I find it under the down arrow, which is not very intuitive.

Opening settings pops up Windows dialog which asks me what to do with this file. I do not have any specialized editor on my machine. So, I am confused by this choice.

Finally, I chose Notepad because that's what I'm used to when opening unknown file types. I see JSON which is not formatted nicely. In fact, the first block (Azure Cloud Shell) is formatted while others are not. This is highly confusing.

I'm an IT Pro, not a developer. I'm not used to JSON files. I might have figured that out by trial and error, but that would be time consuming. Moreover, without visible indentation it's almost impossible.

**Comment by DHowett-MSFT** [comment]
A great many of the things reported here make me think you had an old v0.1 settings file laying around. You might be a lot happier if you [reset your settings](https://www.hanselman.com/blog/NowIsTheTimeToMakeAFreshNewWindowsTerminalProfilesjson.aspx).

For the rest- we generally try to avoid bucket bugs. I’ll figure out what to do with this on Tuesday.

**Comment by pronichkin** [comment]
Ok that's weird. I just tried again on a new machine and the experience was the following.

1. Double-checked that `.\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState` directory is empty.
2. Started Terminal, observed the same unpleasant behavior.
3. Verified that the `profiles.json` file was created in the abovementioned directory.
4. Closed Terminal.
5. Deleted the `profiles.json` file.
6. Started Terminal again, the _experience is now different._ At least the font is visually different and much better looking. (Also there's fewer profiles this time, which I appreciate. Previously there were duplicates for Windows PowerShell, where one of them was called just "PowerShell.")
7. Puzzled.

So, apparently the older settings were hanging around somewhere in my Windows profile, but **not** in the profiles.json?

**Comment by DHowett-MSFT** [comment]
Yeah, back in v0.3 we moved the settings from Roaming to Local, but apparently the sync engine _doesn’t sync file deletions_. On a new machine, you get a roamed copy of your oldest settings that lived in the roaming folder, and they get promoted to local and left there. Before 0.9, we’ll probably kill the migrator for roamed settings.

**Comment by DHowett-MSFT** [comment]
If your settings were old enough (if you were on the v0.1 selfhost before we got JSON formatting, it’s highly likely) they even predated stable GUIDs for the built-in profiles, so duplicates would show up after v0.5 when we added settings merging. It’s a really rare situation. 😄

**Comment by zadjii-msft** [comment]
I'm coming across this hiding in the backlog today, and it seems like the main remaining complaint in this thread is "there's not a settings UI, you have to edit a json file". Which, as of 1.7 (preview), is no longer the case. So I'm gonna close this out.

/dup #1564
