### ISSUE TITLE
Windows terminal not running

### ISSUE THREAD

**Issue by TommyAlmeida** [microsoft/terminal#4291]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.535]
Windows Terminal version (if applicable): Latest on the release page
```

# Steps to reproduce

I've installed the terminal from the release page (since the ms store doens't download it for me) and just opened.

# Expected behavior

Terminal should be up and running.

# Actual behavior
It says "time limit exceeded trying to open "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.8.10091.0_x64_8...\WindowsTerminal.exe""

PS: My pc is in portuguese so program files doens't exists, it might be that problem but how can i solve it than?

**Comment by DHowett-MSFT** [comment]
I cannot reproduce this issue. Does it still happen if you reboot your computer? I have never seen this bug before.

**Comment by TommyAlmeida** [comment]
Yes i did, i haven't been enable to solve it anyways.

A quinta, 23 de jan de 2020, 23:50, Dustin L. Howett (MSFT) <
notifications@github.com> escreveu:

**Comment by DHowett-MSFT** [comment]
Would you mind sending us some feedback using the _Feedback Hub_? Please choose the "Developer Platform", "App Deployment" sections and _share_ the feedback hub link in this issue?

**Comment by simonpeterdebbarma** [comment]
@DHowett-MSFT Can we re-open this issue? I'm having the same problem.

**Comment by DHowett-MSFT** [comment]
@simonpeterdebbarma If you'll follow the request in my earlier comment, sure.

**Comment by simonpeterdebbarma** [comment]
@DHowett-MSFT Things took a different turn in the last 10 minutes. 

I've been trying to try to run it for hours and finally found a relevant issue here with the same error I've been getting. Right after I sent the above message to you, I tried running it once again, and it worked. Sorry for bothering you! 

I do not recall taking any new/extra steps before the failed runs and the last successful run so I'm also unable to explain why it worked now. Thank you for your time.

**Comment by simonpeterdebbarma** [comment]
@DHowett-MSFT, if it helps, I can send you data for you to analyze?

**Comment by DHowett-MSFT** [comment]
Unfortunately, I'm not sure what data there'll be now that it's working. I hate when bugs just go away!
