### ISSUE TITLE
Unicode Characters Shown as Underscores

### ISSUE THREAD

**Issue by dotSlashLu** [microsoft/terminal#4292]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18362.592]
Windows Terminal version (if applicable): 0.8.10091.0

Any other software?
terminal font: Cascadia

remote linux locale:
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

# Steps to reproduce
SSH from WSL to a remote linux box and input unicode characters.

I have two tabs connecting to the same remote host and only one of it has this problem. So I think it can't be reproduced stably. 

# Expected behavior
Input unicode characters shown correctly

# Actual behavior
Input unicode characters shown as underscore
It's normal when inputting:
![input](https://user-images.githubusercontent.com/3133289/72675331-e779c000-3abc-11ea-96ba-009bdef882aa.png)

After hitting enter:
![result](https://user-images.githubusercontent.com/3133289/72675332-ec3e7400-3abc-11ea-9dd1-53a1139efb4c.png)

The same for both Japanese and Chinese IME. Emoji keyboard doesn't work at all,  the selection window will pop up but nothing happens when an emoji is selected.

**Comment by zadjii-msft** [comment]
What application are you running on the remote host? Does this repro in the legacy console too, or only the Windows Terminal?

**Comment by dotSlashLu** [comment]
I was running neovim in tmux. 

The legacy console is also affected but XShell is not... Here's an image showing three software connected and attached to the same tmux pane in the same time:

![snap](https://user-images.githubusercontent.com/3133289/72692943-9c69b680-3b69-11ea-984e-f24ec571cdde.png)

**Comment by goyzhang** [comment]
The same issue for git-bash. When run `git log` the author name is displayed with unicode characters like :
![WindowsTerminal_2020-01-20_11-05-15](https://user-images.githubusercontent.com/24909320/72695994-8f52c480-3b75-11ea-92c6-fb5c919f99de.png)

**Comment by DHowett-MSFT** [comment]
This honestly looks like a shell/codepage configuration issue. Terminal and conhost do not contain code that replaces unicode characters with _underscores._

It looks like _tmux_ is choosing to send `_` because it does not think the terminal supports UTF-8.

@goyzhang that is an issue in git. You need to set the `LANG` environment variable to tell it that UTF-8 is supported.

**Comment by goyzhang** [comment]
> This honestly looks like a shell/codepage configuration issue. Terminal and conhost do not contain code that replaces unicode characters with _underscores._
> 
> It looks like _tmux_ is choosing to send `_` because it does not think the terminal supports UTF-8.
> 
> @goyzhang that is an issue in git. You need to set the `LANG` environment variable to tell it that UTF-8 is supported.

An issue in git? I'm not sure what LANG is. Is it a window terminal setting? The git-bash comes with windows git works fine. And months ago the windows terminal display correctly. "Å" now it's just 
![image](https://user-images.githubusercontent.com/24909320/73039067-b1a75380-3e8f-11ea-82ea-582d5b925bf6.png)

**Comment by goyzhang** [comment]
> This honestly looks like a shell/codepage configuration issue. Terminal and conhost do not contain code that replaces unicode characters with _underscores._
> 
> It looks like _tmux_ is choosing to send `_` because it does not think the terminal supports UTF-8.
> 
> @goyzhang that is an issue in git. You need to set the `LANG` environment variable to tell it that UTF-8 is supported.

@DHowett-MSFT  No it's not. The git-bash comes with git works fine. And months ago windows terminal displayed correctly.  But now ( Swedish character Å in windows terminal vs git bash):
![2020-01-24 102015](https://user-images.githubusercontent.com/24909320/73040097-41023600-3e93-11ea-8714-7cdf10260493.png)

**Comment by DHowett-MSFT** [comment]
So, I see that too:

![image](https://user-images.githubusercontent.com/14316954/73040471-9fd19c00-3e0e-11ea-8bb3-84eec15f4c1c.png)


but when I _actually set the `LANG` and `LC_ALL` variables_, I get this:

```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

![image](https://user-images.githubusercontent.com/14316954/73040510-c7c0ff80-3e0e-11ea-8959-c391a1d7f0b4.png)

When I check "git bash", it tells me that it set `LANG` by default.

![image](https://user-images.githubusercontent.com/14316954/73040527-ddcec000-3e0e-11ea-8ffc-fbb62dbf37e2.png)

This is a configuration problem, not a Terminal problem.

**Comment by goyzhang** [comment]
@DHowett-MSFT OK, now it's working. Thank you! I was just confused that it used to be working by itself in windows terminal until some update...

**Comment by DHowett-MSFT** [comment]
That _is_ very strange :smile:
Windows Terminal doesn't want to set LANG, because it's an important variable for the user on Linux. You may be able to set it in your system environment so you do not need to set it all the time!
