### ISSUE TITLE
Consider customizing cursor blink

### ISSUE THREAD

**Issue by imkiva** [microsoft/terminal#4296]
# Description of the new feature/enhancement
Allows the user to control whether the cursor should blink.

So we can write something like this in `profiles.json`:
```json
"cursorBlink": false,
```
to disable cursor blink (like other terminals: iTerm2, Konsole, etc.)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
Sounds like a duplicate of #1379.

**Comment by zadjii-msft** [comment]
Yep this looks like a dupe to me. Thanks!

/dup #4296
