### ISSUE TITLE
Using the wrong data type for a setting in profiles.json gives misleading "Missing '}' or object member name" error

### ISSUE THREAD

**Issue by icheatatlan** [microsoft/terminal#4299]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.8.10091.0


Any other software? 
```

# Steps to reproduce

1. Edit profiles.json
2. Add a setting value with an inappropriate data type, eg:
```
{
  // ...
  "profiles": [
    {
      "guid": "...",
      // ...
      "fontSize": "12"  // <-- string instead of number
    }
  ]
}
```

# Expected behavior
The 'Failed to reload settings' message box should present a message explaining that the offending setting has the wrong type.

# Actual behavior

The 'Failed to reload settings' message box presents the following:
> Settings could not be reloaded from file. Check for syntax errors, including trailing commas.
> * Line 34, Column 9
>   Missing '}' or object member name
> Temporarily using the Windows Terminal default settings.

**Comment by zadjii-msft** [comment]
Yep that looks wrong to me. We should give better errors in this case.

This also includes #2440, which is this error but specific to the `defaultProfile` setting. We really should handle this generically.
