### ISSUE TITLE
Teminal doesn't preserve colored blocks of characters.

### ISSUE THREAD

**Issue by elbertlev** [microsoft/terminal#4300]
# Environment

```none
Windows build number: 10.0.18362.592
Windows Terminal version (if applicable): 0.8.10091.0
```

# Steps to reproduce
1. Launch the Windows Terminal (it opens the Powershell tab)
2. Run any of the color16.bat (or any other .bat file) file from https://gist.github.com/k-takata/2d4f562bacf8bae6691973a540970117#file-color256_block-sh
3. The colored block is drown
4. Resize the terminal window and observe the  colored block disappears. 
# Expected behavior
The colored block should be preserved
![image](https://user-images.githubusercontent.com/34284289/72690159-4e53a500-3ace-11ea-92b2-83c557c21fcf.png)
# Actual behavior
The colored block disappears.
Note. The same behaviour in all kinds of shells it terminal (cmd, bash) and in standalone cmd.exe

**Comment by zadjii-msft** [comment]
Yea, this is true. Since the console buffer can't know the difference between "no character" and "space", when the console buffer resizes, it doesn't know to copy that color information over. This is technically the same bug as #32 - I'll leave it to the rest of the team to decide if this should be left open or closed as a dupe.

**Comment by elbertlev** [comment]
Thank you for prompt response. I believe I found the reason for such behavior. 
Let's start with cmd.exe. It behaves exactly the same way as terminal if "Wrap text output on resize" is enabled. If disabled it works as it should.
The terminal settings do not include such option (at least I don't know how to disable wrapping).

I think it is possible to make cmd and terminal work correctly with wrapping, but don't know is it worth the efforts. After all you are mimicking the full screen mode. Maybe documenting is enough. Also it would be nice to check the behavior of a real Linux terminal.

**Comment by DHowett-MSFT** [comment]
I'm gonna call this one officially a /dup of #32. Thanks!
