### ISSUE TITLE
Set Windows Terminal as Default (instead of current cmd window)

### ISSUE THREAD

**Issue by HumanGamer** [microsoft/terminal#4305]
# Description of the new feature/enhancement
Allow setting the Windows Terminal as the default console instead of the legacy one that windows currently uses.

# Proposed technical implementation details (optional)
I attempted to implement this myself but was unable to get conhost to call windows terminal as it works the other way around. So it may be tricky to implement in it's current state.

# What should happen

If you set Windows Terminal as the default terminal, then opening any application that uses conhost, the new windows terminal will be used. (unless specified otherwise by cmd argument)

# Other
I couldn't find an existing issue for this suggestion, so I apologize if this is a duplicate.

**Comment by zadjii-msft** [comment]
Hey thanks for the suggestion! This actually _is_ tracked by another issues already on this repo - "Change Windows OS to support default terminal", though I guess that isn't the _most_ discoverable.

/dup #492

**Comment by HumanGamer** [comment]
> Hey thanks for the suggestion! This actually _is_ tracked by another issues already on this repo - "Change Windows OS to support default terminal", though I guess that isn't the _most_ discoverable.
> 
> /dup #492

Oh ok, thank you.
