### ISSUE TITLE
Basic transparency instead of Acrylic fuzzy transparency

### ISSUE THREAD

**Issue by admered1** [microsoft/terminal#4306]
# Description of the new feature/enhancement

At present the only transparency is "Acrylic" which gives a fuzzy image through the terminal of what is directly behind it, or backdrop image, where the transparency value relates to the image itself and does not allow the user to see through to what is behind the window.

The gnome-terminal application in Gnome based distros has another way of working which is very very useful (as well as looking good) in that the transparency number allows the user to set the transparency in a similar way to the Acrylic, only it isn't fuzzy, it is a clear picture of what is there. This allows the user to keep track of things like progress bars and log files while working on something else.

I would strongly suggest that for hard core Gnome users who have been forced to migrate (like me), this will make their Windows experience a whole lot nicer.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I believe this is largely being tracked by #603.

/dup #603
