### ISSUE TITLE
Button corners in the "Do you want to close all tabs" pop-up dialogue are not rounded

### ISSUE THREAD

**Issue by rico-et22** [microsoft/terminal#4307]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.8.10091.0

Any other software? No
```

# Steps to reproduce
Open at least two tabs in Windows Terminal and press the close button

# Expected behavior
The grey buttons in the "Do you want to close all tabs" pop-up dialogue should have rounded corners from the latest WinUI library, like in the "About" pop-up, for better consistency

# Actual behavior
These grey buttons don't have rounded corners (like in older WinUI versions), which is weird because Windows Terminal uses the latest WinUI version & elements

**Comment by zadjii-msft** [comment]
Huh, yea, they should be rounded. Good eye!
