### ISSUE TITLE
Default profile should be powershell, rather than cmd

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/Terminal#431]
@bitcrazed can hopefully back me up here, but `cmd` is frozen and not getting any more changes, and we generally want people to be using the latest Powershell release.

**Comment by miniksa** [comment]
ARGH. We meant to do that before pushing this. We were talking about this last week for exactly this reason.

**Comment by DHowett-MSFT** [comment]
We may also want to follow the Windows Shell option that dictates what shell lives in your `WIN+X` menu.

**Comment by zadjii-msft** [comment]
@DHowett-MSFT if that's something we can query, let's please do that.

*sponsored by the cmd squad*

**Comment by mdtauk** [comment]
The Windows team should allow read only access to the user's chosen default, so the Terminal can respect that

**Comment by binarycrusader** [comment]
The registry key set by settings is:

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\DontUsePowerShellOnWinX

The default is 0 to use powershell by default I believe.

Is it ok to query that?

**Comment by zadjii-msft** [comment]
This PR was successfully merged, so I'm closing this issue, and moving discussion of querying the user's default shell to #740
