### ISSUE TITLE
When I select the "settings" menu item, I get an error about Visual Studio.

### ISSUE THREAD

**Issue by smeredith** [microsoft/terminal#4312]
1. Open the terminal.
2. Select "settings".

I get the following error message:

"Setup Error"
"The setup for this installation of Visual Studio is not complete. Please run the Visual Studio again to correct the issue."

<img width="311" alt="screenshot" src="https://user-images.githubusercontent.com/6439539/72773508-32c6c800-3bbc-11ea-8950-3a0dbe07bdc9.png">

**Comment by DHowett-MSFT** [comment]
visual studio is set as your JSON editor. Either fix your VS installation or set a different JSON editor as your default file association for `json` files.
