### ISSUE TITLE
Please backport to Windows 180x series

### ISSUE THREAD

**Issue by arobert3434** [microsoft/terminal#4313]
# Description of the new feature/enhancement

Please backport this to be compatible with the Windows 180x series, in particular 1809 which is on the long term support track and is / will be in use by many large enterprises until 2021. We would like to use the Terminal app, and the wider testing would benefit the app as well.

Make Terminal available to a wider audience to benefit them and provide better QA support to the app.

# Proposed technical implementation details (optional)

The  current requirement of Windows 1903 for Terminal is brought back to 1809.

**Comment by DHowett-MSFT** [comment]
Sorry- I’m going to close this one per our bug template. There are a bunch of instances of this request, already closed, with long lists of reasons provided. I apologize.

**Comment by arobert3434** [comment]
No problem and no need to apologize. I take your word there are reasons it is not worth the effort. I did search for a request for this already and did not find (and still can't).

**Comment by DHowett-MSFT** [comment]
:smile: I did end up going digging for this.

https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691 https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323 https://github.com/microsoft/terminal/issues/841#issuecomment-492940388 https://github.com/microsoft/terminal/issues/498#issuecomment-490091740 https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952

Some of them go into detail, others are somewhat brusque.

Thanks!
