### ISSUE TITLE
Allow cursorColor to be specified in color schemes

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#4316]
Currently, all of `foreground`, `background`, `selectionBackground` can be specified in color schemes and overridden in profiles. However, `cursorColor` can only be defined in profiles.
So I propose to allow specifying `cursorColor` in color schemes as well, analog to the others.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #764 for more discussion.

/dup #764
