### ISSUE TITLE
tmux in ssh session does not receive ctrl+space prefix

### ISSUE THREAD

**Issue by jupiterneptune** [microsoft/terminal#4317]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 0.8.10091.0

Any other software?
Remote Linux machine (Ubuntu 19.10 having ssh-server and tmux installed)
```

# Steps to reproduce

Open Windows Terminal, SSH to the remote Linux machine, start tmux with bellow configuration (in tmux.conf) - this changes the tmux default keyboard prefix from Ctrl+B to Ctrl+Space.
```none
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
```

# Expected behavior

Ctrl+Space, % - should split into panes.

# Actual behavior

Ctrl+Space, % - it does not register the Ctrl+Space prefix, the terminal types the '%' character.
If the above configuration is commented out and tmux restarted, the default prefix Ctrl+B is registered and works as intended.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2865 for more discussion.

/dup #2865

**Comment by jupiterneptune** [comment]
Thanks, @zadjii-msft!
