### ISSUE TITLE
fontFace for Powershell profile is Courier New, should be Consolas

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/Terminal#432]
Consolas seems to be the current monospace font of choice for Microsoft apps.

**Comment by crablab** [comment]
If you want to PR this, you need to change [this](https://github.com/microsoft/Terminal/blob/35229a775d9e9908a8dfb102e01f49b494b29194/src/cascadia/TerminalApp/CascadiaSettings.cpp#L146) line.

**Comment by DHowett-MSFT** [comment]
Yeah, this was probably chosen to show that two fonts could live side by side in the same console. Here, though. I want to throw out a different suggestion.

We should probably have a `default` profile that things optionally inherit from. Somewhat like cascading style sheets with but a single level of cascade.

That'll settle questions around "what do we put into the default profiles? what if we change one and forget the others?"

**Comment by zadjii-msft** [comment]
You know what, we're gonna dupe this into #430, as the defaults we currently have for Powershell are generally not great, and we should get the Powershell team's guidance on that they'd like.

**Comment by mikemaccana** [comment]
Thanks @zadjii-msft (and thanks for all your work on everything else I've reported) 🙂
