### ISSUE TITLE
Can't move terminal store install to another drive

### ISSUE THREAD

**Issue by themohaammari** [microsoft/terminal#4324]
![image](https://user-images.githubusercontent.com/23485114/72851292-773b8c00-3cc0-11ea-86f4-1e73816320e4.png)

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
That error looks like "The package could not be installed because resources it modifies are currently in use.". Is Windows Terminal currently running? If you check for processes called `OpenConsole.exe`, are _they_ still running?

**Comment by themohaammari** [comment]
Problem resolved after restarting the PC.
![image](https://user-images.githubusercontent.com/23485114/72862585-f80b7f80-3ce2-11ea-93ac-4633e79bc98b.png)
I close this issue.

**Comment by Shashi9503** [comment]
> Problem resolved after restarting the PC. ![image](https://user-images.githubusercontent.com/23485114/72862585-f80b7f80-3ce2-11ea-93ac-4633e79bc98b.png) I close this issue.

I am facing same problem even after restarting the PC

**Comment by Blackbird88** [comment]
Same problem here on W11
![image](https://user-images.githubusercontent.com/4414625/224534770-969b30a2-9b94-41c2-b4db-f3e6b845c8d5.png)
