### ISSUE TITLE
Esc character not created ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/terminal#4326]
The `Esc` character when in a command line shell should create `^[` rather nothing is created; unlike in the command line shell which comes with Windows ?
Microsoft Terminal; Version: 0.7.3451.0

**Comment by zadjii-msft** [comment]
@SheepDomination In what shell are you seeing <kbd>esc</kbd> write an escape character to the input? In `cmd` and `powershell`, <kbd>esc</kbd> clears the input line, and in `bash` it simply escapes the next character pressed. Have you changed something about the configuration for those shells that would cause a change in behavior for the legacy console?

**Comment by SheepDomination** [comment]
I mean it's not doing an [Escape character](https://en.wikipedia.org/wiki/Escape_character). In the default command line shell which comes with Windows, it works; by works I mean when I use the keyboard commands `crtl`+`[` I get `^[` but in Windows Terminal it erases the line; which is identical to that in the default command line which comes with Windows, if I have [click](https://github.com/mridgers/clink) installed. 

Nothing in my configuration has been altered, I've left everything at their defaults for Windows Terminal.

**Comment by zadjii-msft** [comment]
Okay that gives me a lot more information. There's a very real difference between <kbd>Esc</kbd> and <kbd>Ctrl+[</kbd> in the legacy console, but unfortunately, they both map to the `ESC` character. This means that unfortunately, conpty (which provides the backend for the Windows Terminal) can't tell the difference between the two, and chooses to treat `\x1b` as <kbd>Esc</kbd>, _not_ <kbd>Ctrl+[</kbd>.

This is related to the broader class of problems that are currently being tracked in #879, so I'm going to resolve this as a dupe. Thanks!

/dup #879

**Comment by SheepDomination** [comment]
Would this also fall into the same line as pasting from the clipboard only pastes `^V` when in a command line shell, rather then the contents which were cut anywhere within windows ?

**Comment by DHowett-MSFT** [comment]
That is unrelated.
