### ISSUE TITLE
Hangul(Korean) input is messed up.

### ISSUE THREAD

**Issue by wonho21** [microsoft/terminal#4327]
Hello.

Tested on same machine.
 - Windows 10 Enterprise 1909 Korean
 - Powershell : Powershell 5.1.18362.145 + D2Code Font
 - Windows Terminal : 0.8.10091.0 + Cascadia Code Font

There is no problem with Korean input in the built-in Powershell.
However, Hangul phonemes are broken in the Windows Terminal as shown below.

Good
![Image of Powershell](https://s3-ap-northeast-1.amazonaws.com/ftt-img.four33.com-tok/github-Powershell.png)

Bad
![Image of WindowsTerminal](https://s3-ap-northeast-1.amazonaws.com/ftt-img.four33.com-tok/github-WindowsTerminal.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4226 for more discussion.

/dup #4226
