### ISSUE TITLE
Feature request: put tabs at top in title bar

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/Terminal#433]
Current Windows Terminal (top) has a separate title bar and an address bar. It could be useful to consolidate them like Fluent (bottom) uses:

![image](https://user-images.githubusercontent.com/172594/57257753-4512cd00-7052-11e9-824a-d95b94a5602f.png)

This would:

 - Save real estate
 - Increase signal/noise ratio (name of app `pwsh` is already in tab)
 - Be consistent with Edge

**Comment by zadjii-msft** [comment]
This is actually already available, if you set `"experimental_showTabsInTitlebar": true` in the root of the settings object.

UNFORTUNATELY, there are some real bugs with this solution currently. Notably, you won't be able to drag the entire "tabs" region, only the area that's immediately adjacent to the caption buttons. So beware, here be dragons.

![image](https://user-images.githubusercontent.com/18356694/57258007-b5a0f600-7020-11e9-85fa-262aaf0d3362.png)

**Comment by mikemaccana** [comment]
Ah OK. I don't quite understand your caveat, but I can see that dragging tabs (eg, to reorder) definitely doesn't work when using this. 

PS. off topic, but vscode keeps minifying the `profiles.json` on save so I can't read it - there's no extension doing this (I've disabled them). Terminal doesn't have some kind of magic to make VScode do this by chance??

**Comment by zadjii-msft** [comment]
Oh, like, the entire white section of the titlebar in my above screenshot doesn't work to drag the window around currently. This is a bug with XAML islands which we're working on currently.

The profiles.json thing is a temporary thing. Unfortunately, Windows.Data.Json always writes out json as a single line, without the ability to pretty-print it, and we re-write the profiles.json to make sure that it stays up to date with the schema of the app. So currently, it'll keep re-writing it. But that's a huge pain point that we want to fix ASAP.

**Comment by DHowett-MSFT** [comment]
I'm going to close this one out since it _exists_, but we just need to make the behaviour better and capture drag events. Thanks for the suggestion!

**Comment by mikemaccana** [comment]
Sure, thanks @DHowett-MSFT! 🙂
