### ISSUE TITLE
Open the terminal at the current path from the file explorer

### ISSUE THREAD

**Issue by Ballzer0** [microsoft/terminal#4330]
When you type **wt** in the file explorer, it open the terminal, but the terminal opens at the default path of my users library. It would be awesome if it opened in the same path as the file explorer i typed it in.

The same happens when i type **wt** in the CMD. it opens at the default path for my user, not the path i was already navigated to in CMD.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #878 for more discussion.

/dup #878
