### ISSUE TITLE
selection action not right

### ISSUE THREAD

**Issue by metasong** [microsoft/terminal#4333]
in terminal type something and press Shift+Ctrl+LeftArrow then press RightArrow, all the other editor and Terminal, would move the cursor to the right side of the selection and undo the selection. but this terminal is not.

I normally use keyboard to do selection and then copy and then continue.

**Comment by DHowett-MSFT** [comment]
Terminals do not have the same caret movement mechanisms as text editors. Sorry. The terminal is to be considered equivalent to a sheet of paper, where text is appended at the cursor location. The cursor cannot be moved by direct user action.
