### ISSUE TITLE
Modifier keys are not properly propagated to application hosted in Windows Terminal

### ISSUE THREAD

**Issue by neurohunter** [microsoft/terminal#4334]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10091.0
Far Manager 3.0.0.5511 x64 [Official page](https://www.farmanager.com/)
```

# Steps to reproduce
1. Install Windows Terminal
2. Install Far Manager
3. Add Far manager as one of Windows Terminal profiles
4. Start Far manager profile
5. Memorize the bottom function key row of Far Manager.
![farmanager-original-state](https://user-images.githubusercontent.com/7010508/72916279-10f74d80-3d42-11ea-81b6-3b35d7b04f58.png)
6. Press and hold Alt key on a keyboard

# Expected behavior
Bottom function key row is changed
![farmanager-proper-reaction](https://user-images.githubusercontent.com/7010508/72915993-7b5bbe00-3d41-11ea-8a5b-bb2e9b8bf08b.png)
This can be observed on a same system by running Far from separate CMD or Powershell session (not within Windows Terminal)

# Actual behavior
Bottom function key row is not changed.
![farmanager-no-reaction](https://user-images.githubusercontent.com/7010508/72915940-6aab4800-3d41-11ea-8754-44421a12c2ac.png)

**Comment by j4james** [comment]
I've mentioned this in a couple of other issues already, but I really think the [DECPCTERM](https://vt100.net/docs/vt510-rm/DECPCTERM.html) mode is the ideal solution for all of our conpty key forwarding problems (the full details are documented in [chapter 8](https://vt100.net/docs/vt510-rm/chapter8.html) if you want to know). It should easily be able to handle keydown events like this.

**Comment by DHowett-MSFT** [comment]
@j4james definitely. I'm gonna fold this one into /dup #879 and rename that one to be a little clearer. DECPCTERM would be excellent, and we can tie it in with the windows console modes such that ConPTY requests DECPCTERM if it needs it. :smile:

**Comment by unxed** [comment]
win32-input-mode support also added to the Linux Far Manager port: https://github.com/elfmz/far2l/pull/1581

**Comment by unxed** [comment]
win32-input-mode support also added to the Linux Far Manager port: https://github.com/elfmz/far2l/pull/1581
