### ISSUE TITLE
get used to windows terminal

### ISSUE THREAD

**Issue by pisoto** [microsoft/terminal#4338]
Hi,
there is a way to make windows terminal to open from the run line when I am writing "cmd"?
Because I want to get used to working with the windows terminal and it's hard to write "wt" while working, because I am writing "cmd" in the run for command prompt by instinct.
I already change the default command prompt in windows terminal to cmd so it will be very nice if I will write in run line "cmd" and it will open cmd on windows terminal beside the regular cmd.

**Comment by DHowett-MSFT** [comment]
Not yet. You'll want to follow /dup #492, which will add support to Windows to launch Terminal by default for all commandline applications.
