### ISSUE TITLE
Choose Direction to Split Pane

### ISSUE THREAD

**Issue by LowellBateman** [microsoft/terminal#4340]
# Description of the new feature/enhancement

Sometimes I like to have my panes organized in a specific way. This can be difficult when you are only allowed to split to the right or below. I suggest adding commands to split above and to the left. I know conemu was capable of splitting panes in any direction.

# Proposed technical implementation details (optional)

Add splitUp, splitDown, splitLeft, splitRight commands instead of / in addition to splitHorizontal, splitVertical

**Comment by DHowett-MSFT** [comment]
Since this has been accumulated into the Panes deliverable, #1000, I'm yanking the Triage tag.
