### ISSUE TITLE
add holder on Title bar

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#4343]
# Could terminal team add a holder on the Title bar?

 When terminal locate at the edge screen. I can not drag it back to my screen. There is a similar feature in Firefox browser. I make a screenshot to make my idea more easy to under stand . Please see bellow image.
![add-holder](https://user-images.githubusercontent.com/36788337/72988605-8852dd00-3e27-11ea-937f-9a00b72bd0ee.png)

# Proposed technical implementation details (optional)

**Comment by pc-v2** [comment]
IMO, it will cause inconsistency in Fluent Design UI

**Comment by DHowett-MSFT** [comment]
Thanks for the request! We're not going to pursue this at this time, but we're definitely collecting feedback here.

I'll close this for now, and we can revisit it post-1.0
