### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by HorseGlass** [microsoft/terminal#4348]
Hi!
I am not able to access the Store Page of the **preview** terminal. I tried to do the manual installation but it didn't work too.

I have **Windows 10**  _**1909**_
My build number is **_18363.592_**

Any fix idea?

**Comment by zadjii-msft** [comment]
@HorseGlass Unfortunately we can't really do anything with "it didn't work". Is it displaying any sort of error message? Are there any event logs that seem relevant?

**Comment by HorseGlass** [comment]
![{E19A1338-FCCE-4AFC-890D-034D44F6E1DF} png](https://user-images.githubusercontent.com/35706509/73020565-2c3b8900-3e26-11ea-8eff-e8efdf7ff9a7.jpg)
Sorry i am hungarian but it means: **The installer cant install dependecies. Ask the developer to send _blank space in the text_ indentification package.**

**Comment by gliptak** [comment]
There numerous failures to install this package (in particular when access to Microsoft Store was restricted):

https://github.com/microsoft/terminal/issues/1386
https://github.com/microsoft/terminal/issues/3097
https://github.com/microsoft/terminal/issues/3219
https://github.com/microsoft/terminal/issues/3304

Maybe you find some workarounds reading above

**Comment by DHowett-MSFT** [comment]
I'm gonna close this as a /dup of #1386 #3097 #3219 #3304. Thanks!
