### ISSUE TITLE
Allow to use multiple fonts primary font and powerline font

### ISSUE THREAD

**Issue by sagarrabadiya** [microsoft/terminal#4351]
I want to use operator mono fonts but with console zsh theme like powerlevel10k some characters are missing and to fill those character powerline patched fonts are required.

currently only one fonts are supported so i can not use operator mono with another powerline font to show prompt characters

VS Code built in terminal provide a way to define multiple font with comma separated list so i can use both fonts operator mono and powerline fonts which gives perfect experience

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Thanks for the request! This is a /dup of #2664.
