### ISSUE TITLE
Full Screen mode layers title bar on top of the terminal

### ISSUE THREAD

**Issue by rohith** [microsoft/terminal#4352]
# Environment

Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10091.0

# Steps to reproduce
Enter full screen mode by hitting `Alt + Enter`

# Expected behavior
Terminal should be full screen mode without any overlays

# Actual behavior
There's an overlay of what seems to be like a title bar right on top of the terminal & it obstructs the text on first 2 lines

![image](https://user-images.githubusercontent.com/5032439/73090826-1d74d500-3eff-11ea-8100-baccf41989dc.png)

**Comment by DHowett-MSFT** [comment]
Thanks! /dup #4224.
