### ISSUE TITLE
Ctrl + C in pwsh doesn't return to prompt & makes the tab useless

### ISSUE THREAD

**Issue by rohith** [microsoft/terminal#4353]
# Environment

Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10091.0

# Steps to reproduce
- Open PowerShell Core in Terminal
- Type `ping 8.8.8.8 -t`
- Press `Ctrl + C`

# Expected behavior
The ping is cancelled & PS Core returns to prompt

# Actual behavior
There's a message *process exited with code 3221225786*

Issue only happens with PS Core when run in Windows Terminal otherwise a standalone PS Core shell reacts as expected

![image](https://user-images.githubusercontent.com/5032439/73091444-74c77500-3f00-11ea-9d66-288fc8ca72e7.png)

**Comment by DHowett-MSFT** [comment]
This is https://github.com/PowerShell/PowerShell/issues/11314
