### ISSUE TITLE
WSL shell tab not closed on exit if last command executed had a non-zero exit code

### ISSUE THREAD

**Issue by slieschke** [microsoft/terminal#4355]
# Environment

```none
Windows build number: 10.0.18363.592
Windows Terminal version (if applicable): 0.8.10091.0
No "closeOnExit" setting in my profile.
```

# Steps to reproduce

1. Open an WSL shell
1. Run a command that results in a non-zero exit code
1. Run `exit`

# Expected behavior

The WSL shell tab closes

# Actual behavior

The WSL shell tab remains open and it displays _[process exited with code \<exit code of previous command>]_.

![image](https://user-images.githubusercontent.com/742941/73108977-e20ee200-3ecf-11ea-9767-24aeb952cf81.png)

**Comment by DHowett-MSFT** [comment]
Far as we can tell, this is by design following the example of the ubuntu default terminal: https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181

**Comment by slieschke** [comment]
Thanks @DHowett for the explanation. I've added `"closeOnExit": "always"` as you mentioned at https://github.com/microsoft/terminal/issues/4223#issuecomment-574774501 and that's a good enough workaround for me.
