### ISSUE TITLE
Suggestion for keybindings

### ISSUE THREAD

**Issue by filip123** [microsoft/terminal#4356]
it would be nice if there was an option to launch with arguments like when i open cmd i want it to do /ipconfig each time i open a spesific cmd :)

**Comment by DHowett-MSFT** [comment]
You can do this. Here's an example of a keybinding that launches cmd and runs ipconfig.

```jsonc
{
    "command": {
	    "action": "newTab",
        "commandline": "cmd.exe /s /k ipconfig"
    },
    "keys": [ "ctrl+alt+i" ]
}
```
