### ISSUE TITLE
Start New Tabs in New Machine Context

### ISSUE THREAD

**Issue by rkitover** [microsoft/terminal#4357]
Currently new tabs launch in the context of the terminal process, so if for example you change a machine scope environment variable, the change will not be effective in a new tab.

Having child shell processes start in machine scope would be more like the behavior the user would expect. For example, the user installs a chocolatey package which adds an entry to machine scope PATH, and a new shell would have the modifications so that utilities could be run from that PATH entry.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I'm pretty sure this is work that's actually tracked by #1125, though that title is certainly confusing. 

/dup #1125
