### ISSUE TITLE
Make it possible to copy, paste, split panes, etc. from the main menu (appearing when “∨” clicked)

### ISSUE THREAD

**Issue by tats-u** [microsoft/terminal#4360]
# Description of the new feature/enhancement

ConHost has the "Edit" item in the menu appearing when the title bar is clicked.  We can copy or paste text from it.  [Hyper](https://hyper.is/) has a similar one in the menu appearing when "≡" button is pressed.  I feel like GNOME Terminal also has one.

Moreover, Hyper can split panes from the menu (File → Split Horizontally (or Vertically)).

Main menu is not only for those unused to terminals; it also reminds us of keyboard shortcuts slipping our minds.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Thanks for the request. I think this'll be a better fit folded into /dup #1912

**Comment by tats-u** [comment]
I suppose these commands shouldn't be in the context menu per tab.
Is there a still-opened issue suggesting to add additional commands to the main menu?
