### ISSUE TITLE
Retro terminal effect prodces artifacts on the right screen edge

### ISSUE THREAD

**Issue by jantari** [microsoft/terminal#4362]
# Environment

```none
Windows build number: 10.0.19551.1005
Windows Terminal version: 0.8.10091.0

Any other software?
Confirmed in the PowerShell 7.0.0-rc2 and cmd shells, but should affect all.
```

# Steps to reproduce

Set your PowerShell Core (7) profile like or similar to this:

```json
"acrylicOpacity":  0.84,
"fontFace":  "Cascadia Code",
"fontSize":  11,
"hidden":  false,
"name":  "PowerShell 7",
"experimental.retroTerminalEffect": true,
"source":  "Windows.Terminal.PowershellCore",
"padding":  "25, 25, 25, 25",
"useAcrylic":  true
```

# Expected behavior

No glowy artifacts on any screen border/edge.

# Actual behavior

![image](https://user-images.githubusercontent.com/25607767/73139244-4f577a00-406c-11ea-8753-d12b9531f138.png)

When retro terminal effects AND screenbuffer padding is enabled, text-effect artifacts are visible on the right edge in many lines (not all). This will also happen without padding but it's visually less obvious.

**Comment by DHowett-MSFT** [comment]
I like to think that it's like a misaligned electron gun, yeah?

**Comment by DHowett-MSFT** [comment]
Jokes aside: triaged, marked for v1.x
