### ISSUE TITLE
Build WindowsTerminalUniverasl AppPackage fails with missing Images

### ISSUE THREAD

**Issue by lovettchris** [microsoft/terminal#4365]
# Environment

```none
Microsoft Windows [Version 10.0.18362.592]
```

# Steps to reproduce

Load OpenConsole.sln, right click "WindowsTerminalUniversal" and select build Publish/CreateAppPackages.

# Expected behavior

Should succeed

# Actual behavior

16>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6292,5): error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'd:\git\terminal\src\cascadia\WindowsTerminalUniversal\Images'.

Interestingly there is an Images folder under `Debug\PackageLayout\Images` ?

**Comment by zadjii-msft** [comment]
I'm not saying that we're expecting that to not work, but I'm pretty sure that's _not the option you're looking for_. You probably want to "Deploy" "CascadiaPackage" if you want to build and run the Terminal locally. `WindowsTerminalUniversal` is actually pretty much just an internal testing tool at this point.
