### ISSUE TITLE
Terminal ignores anything from clipboard 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/terminal#4368]
When attempting to paste anything within Windows Terminal, rather then the contents of what should be placed from the clipboard, instead what is pasted using `Ctrl`+`v` is `^V` ?

**Comment by zadjii-msft** [comment]
Paste is bound to <kbd>Ctrl+Shift+V</kbd> by default. You'll need to rebind it to <kbd>Ctrl+V</kbd> in your `profiles.json` it you want <kbd>Ctrl+V</kbd> to paste. See [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#adding-copy-and-paste-keybindings) for more details.

**Comment by SheepDomination** [comment]
Thanks, my fault.
