### ISSUE TITLE
Font Size Mixed Rendering in WSL2

### ISSUE THREAD

**Issue by DKingCN** [microsoft/terminal#4369]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.8.10091.0

Any other software?    WSL 2 (Ubuntu 18.04.3 LTS)
```

# Steps to reproduce
1. WT config
```
        {
            "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "name": "Ubuntu-18.04",
            "source": "Windows.Terminal.Wsl",
            "hidden": false,
            "fontFace": "宋体",
            "fontSize": 12,
            "acrylicOpacity" : 0.8,
            "useAcrylic" : true,
            "historySize" : 9999,
            "snapOnInput": false,
            "closeOnExit": "graceful"
        }
```

2. in WT wsl, run `man ptrace`, find the section below.

# Expected behavior
In bash.exe:
![image](https://user-images.githubusercontent.com/15340687/73185896-e0f0e580-4159-11ea-851d-f325ab4e0412.png)

# Actual behavior
In Windows Terminal:
![image](https://user-images.githubusercontent.com/15340687/73185915-e51d0300-4159-11ea-8cd4-3457cda6f8c0.png)
![image](https://user-images.githubusercontent.com/15340687/73186577-eef33600-415a-11ea-831f-00f7a40c0dd4.png)

The font size of latter ones is mixed and unreadable.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #610 for more discussion.

/dup #610
