### ISSUE TITLE
How do I actually run the new terminal?

### ISSUE THREAD

**Issue by Daniel15** [microsoft/Terminal#437]
I compiled the terminal from this repo using
```
msbuild OpenConsole.sln /p:Configuration=Release
```

It compile fine, but when I run `bin\x64\Release\OpenConsole.exe`, it just loads regular `cmd.exe`, rather than the fancy terminal shown at https://devblogs.microsoft.com/commandline/introducing-windows-terminal/. Am I missing something?

Windows version 10.0.17763.437
Visual Studio 2017 Professional
MSBuild 15.9.21+g9802d43bc3

**Comment by Gnbrkm41** [comment]
https://github.com/microsoft/Terminal/tree/master/tools
try using `opencon`?

**Comment by jimblanchard** [comment]
If you run the solution, making sure that you have CascadiaPackage set up as the startup project, it should sideload the app. It will now just be in your Start menu.

**Comment by jimblanchard** [comment]
Oh, also something I picked up in one of the other threads. When you run it, it still _looks_ like cmd.exe. Hit ctrl-T to show the tab bar. Then go into settings and set alwaysShowTabs to true.

**Comment by Daniel15** [comment]
@Gnbrkm41 `opencon` just seems to copy the binaries to a temp folder, then runs `OpenConsole.exe`: 
https://github.com/microsoft/Terminal/blob/35229a775d9e9908a8dfb102e01f49b494b29194/tools/opencon.cmd#L19-L25

Just tried it and it still appears to open a regular terminal for me:
![](https://d.sb/2019/05/explorer_06-15.40.16.png)

@jimblanchard - That sounds promising... I was compiling using MSBuild, but I'll try running that `CascadiaPackage` through Visual Studio. Currently it fails to compile in VS, seems like it doesn't like my Windows version:
> DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.18362.0 or higher. You currently are running version 10.0.17763.437. Please update your OS, or change your deployment target to a device with the appropriate version

**Comment by jimblanchard** [comment]
Yes. You definitely need the latest version of Win10 installed. I think there is another issue thread discussing that topic.

**Comment by Daniel15** [comment]
I tried hacking `Package.appxmanifest` to use my Windows version:
```
<TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.17763.0" />
```

Now it compiles, but when I run it, it starts then immediately exits:
```
The program '[25624] WindowsTerminal.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
```

I guess it probably actually does need the newer Windows version. Oh well.

Unfortunately I can't use any prerelease Windows versions on my work PC, so I'm stuck on 17763.

**Comment by oising** [comment]
Yeah, 1903 is a hard requirement here.

**Comment by Daniel15** [comment]
Thanks @oising. In that case, I'll close this issue and re-test it when 1903 is released.

**Comment by hapylestat** [comment]
@Daniel15 check the guides, if you running OpenTerminal.exe you doing wrong things. The application at the output called WindowsTerminal.exe, compile the CascadiaPackage instead of OpenConsolePackage

**Comment by thomthom** [comment]
@hapylestat where in the guides is this described?

The root README file doesn't mention this. Nor does the tools/README. doc/building.md only mentions razzle, bcz and opencon.

With all the projects in the solution and no mention in the main README it's somewhat confusing if you have never touched the project. The minimum Windows version required is also something I found no mention of - other than in this issue.

**Comment by hapylestat** [comment]
@thomthom  I guess that project is really in early stage and the flow, how you r going to build it may be changed faster than the will to update the documentation each time. 

As of now, the complete guide and links r maintained here #489, later it could be moved to a separate PR to form proper and full readme update

**Comment by sourabhsomani** [comment]
> I tried hacking `Package.appxmanifest` to use my Windows version:
> 
> ```
> <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.17763.0" />
> ```
> 
> Now it compiles, but when I run it, it starts then immediately exits:
> 
> ```
> The program '[25624] WindowsTerminal.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
> ```
> 
> I guess it probably actually does need the newer Windows version. Oh well.
> 
> Unfortunately I can't use any prerelease Windows versions on my work PC, so I'm stuck on 1809 (build 17763). Will try it again once 1903 is out as a stable release.

Thank You. Finally done and Deployed :)

**Comment by Stiles-X** [comment]
I hope 17763 gets supported. It's not even old
