### ISSUE TITLE
Windows Taskbar Jumplist Terminal Selection

### ISSUE THREAD

**Issue by jmsnavarro** [microsoft/terminal#4374]
![windows_terminal_feature_request_jumplist](https://user-images.githubusercontent.com/17264947/73230366-eaa93600-41b7-11ea-8630-e4043d45f395.png)

# Description of the new feature/enhancement

Jumplist ability to launch and choose a new shell

# Proposed technical implementation details (optional)

- Right-click Windows Terminal icon on the taskbar
- Choose a new shell

**Comment by ffes** [comment]
I would say:  
/dupe #576

**Comment by zadjii-msft** [comment]
Yep, this is definitely a duplicate. Thanks @ffes!

/dup #576
