### ISSUE TITLE
moveFocusUp command unexpected behavior

### ISSUE THREAD

**Issue by ZimGil** [microsoft/terminal#4376]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): 0.8.10091.0
```

# Steps to reproduce

1. Split pane horizontally, then split each pane vertically to reach a cross.
2. Move focus to the bottom right pane.
3. Use the `moveFocusUp` command.

# Expected behavior

* Focus is moved to the upper right pane

# Actual behavior

* Focus is moved to the upper left pane

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2398 for more discussion.

/dup #2398
