### ISSUE TITLE
Dark theme activation for windows terminal only

### ISSUE THREAD

**Issue by labTifo** [microsoft/terminal#4378]
I want to be able to enable dark mode for the terminal only rather than enabling it for the whole windows applications.

**Comment by hanubeki** [comment]
Put `"requestedTheme": "dark",` to root of profiles.json.

**Comment by zadjii-msft** [comment]
@hanubeki has got it right. @labTifo does that work for you?

**Comment by labTifo** [comment]
@zadjii-msft yes it works, thank you @hanubeki

**Comment by JamieCorkhill** [comment]
@hanubeki  Is it `profiles.json` or `settings.json`? I take it you meant the latter? Thanks.

@zadjii-msft Setting `"requestedTheme: "dark"` at root does not change the color of the top bar for me at all. It stays at the default system light color.

**Comment by DHowett-MSFT** [comment]
As part of 0.11, requestedTheme changes to just `theme`

**Comment by JamieCorkhill** [comment]
Thanks, @DHowett-MSFT, that worked. I appreciate it.

Sorry for potentially cluttering anyone's inbox with this.
