### ISSUE TITLE
Feature Request: option to relaunch a profile when it exits

### ISSUE THREAD

**Issue by tatroc** [microsoft/terminal#4379]
If I have a ssh.exe session open to another machine using ssh.exe (Openssh) and I disconnect from the network the session hangs in the Windows Terminal. I must close the tab. Could we make the session resume by pressing enter? Or is there a better way to handle this?

 {
            "guid": "{5f77e6d6-8215-45d0-be70-a277c72accf6}",
            "hidden": false,
            "name": "user@host",
            "commandline": "ssh.exe user@host",
            "fontFace": "Consolas",
            "fontSize": 12,
            "icon": "%USERPROFILE%\\AppData\\Local\\lxss\\bash.ico"
        },

**Comment by DHowett-MSFT** [comment]
Thanks for the request! I've triaged it and converted it into a request to relaunch a profile when it exits.

**Comment by DHowett-MSFT** [comment]
For now, you can relaunch a new copy of that profile with <kbd>ctrl+shift+d</kbd> (`duplicateTab`)

**Comment by KalleOlaviNiemitalo** [comment]
Would this preserve the screen buffer, window title, and WT_SESSION environment variable?

**Comment by zadjii-msft** [comment]
From #4772: It might be nice if this was an enum value for `closeOnExit`. Something like `"reconnect"` to automatically reconnect (or reconnect after prompting for <kbd>enter</kbd> or something) to re-spawn the connection. 

There's also #3726 for "manually restart a connection", which is similar, but _different_.

**Comment by thernstig** [comment]
I wrote a duplicate for this (which I have now closed) that might contain some more context: https://github.com/microsoft/terminal/issues/10075

**Comment by masics** [comment]
We need to reconnect in the same tab. 
* It will keep the order of the tabs
* No need to close the original tab manually
* It will keep the screen buffer

**Comment by SteffenBlake** [comment]
I have created a very simple little powershell script one can utilize to sort of replicate this behavior.

Save the following script to: `C:\Windows\System32\Keep-Alive.ps1`

```
$command=$args[0]

while ($TRUE) {
    Invoke-Expression $command
    Start-Sleep -Seconds 1
    Write-Output "Scope ended. Press Enter to reload."
    Read-Host
}
```

Then you can put your SSH or whatnot call nested within this function call to loop it on exit.

For example I put the following as my command for my profile's Command Line field:

`PowerShell Keep-Alive 'ssh rancher@Usagi -i \"C:\Users\MyName\Documents\SSH Keys\Usagi\Usagi.pem\"'`

Then you get something like the following:

![image](https://user-images.githubusercontent.com/16726175/130714717-8463f1b5-003e-42fe-9326-a6d376ffbfa2.png)

**Comment by sisrfeng** [comment]
modified from above :

create a file called  `C:\Windows\System32\leo_keep.ps1`
```
$leo_command=$args[0]

while ($TRUE) {
    Invoke-Expression $leo_command
    Start-Sleep -Seconds 1
    Write-Output "leo: ssh disconnected,  Press Enter to reload."
    Read-Host
}
```
use `PowerShell leo_keep 'ssh -X you@yourip' ` instead  of `'ssh -X you@yourip` at windows terminal' s profile

---
`Set-ExecutionPolicy -ExecutionPolicy unrestricted`



![image](https://user-images.githubusercontent.com/53520949/154267287-6aae59f1-ec91-4882-9f34-724fd049fc6c.png)



---


`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`



![image](https://user-images.githubusercontent.com/53520949/154262876-c1d844aa-7a7d-4d1f-afc3-3983669dd88a.png)

**Comment by swinder0161** [comment]
In wt profile use: wt_ssh.bat 192.168.1.100

modify ssh %1 to you command. No need of powershell to execute it. No policy change needed.

n followed by enter will terminate and exit
any other key followed by enter or simply press enter to reconnect. 

`wt_ssh.bat`
```
@echo off

:START
ssh %1

echo.

set /a reconnect=y
set /p reconnect="ssh connection terminated, do you want to reconnect(Y/n)?"
rem echo reconnect: %reconnect%

echo.

if %reconnect%==n (echo exit) else (goto START)
```

**Comment by IBNobody** [comment]
> In wt profile use: wt_ssh.bat 192.168.1.100
> 
> modify ssh %1 to you command. No need of powershell to execute it. No policy change needed.
> 
> n followed by enter will terminate and exit any other key followed by enter or simply press enter to reconnect.
> 
> `wt_ssh.bat`
> 
> ```
> @echo off
> 
> :START
> ssh %1
> 
> echo.
> 
> set /a reconnect=y
> set /p reconnect="ssh connection terminated, do you want to reconnect(Y/n)?"
> rem echo reconnect: %reconnect%
> 
> echo.
> 
> if %reconnect%==n (echo exit) else (goto START)
> ```

Change `ssh %1` to `ssh %*`. Some of us need ssh with extra switches.

**Comment by jbormolini** [comment]
I would also like this feature but if anyone else stumbles here like I did here is my one-liner workaround.

Automatically restart ssh in a loop: `cmd /C for /L %i in (0,0,1) do @ssh user@host`
Add a sleep in the loop: `cmd /C "for /L %i in (0,0,1) do @ssh user@host & timeout /T 2"`
Add a command to ssh (for me, reattach tmux): `cmd /C "for /L %i in (0,0,1) do @ssh user@host -t . ~/.bashrc; my-tmux-bash-function %COMPUTERNAME% & timeout /T 2"`

I couldn't figure out how to use '&' in the ssh command because windows cmd/for will interpret that. There is probably a way to escape it.
