### ISSUE TITLE
Build fails with spaces in user directory

### ISSUE THREAD

**Issue by fridtjof** [microsoft/Terminal#438]
* Your Windows build number:  10.0.17763.437

* What you're doing and what's happening:
Trying to build using VS 2017 Enterprise, the build fails like this:

```
24>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: Der Befehl "
24>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:         if not exist C:\Users\Fridtjof Mund\git\Terminal\x64\Debug\WindowsTerminal mkdir C:\Users\Fridtjof Mund\git\Terminal\x64\Debug\WindowsTerminal
24>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:       
24>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" wurde mit dem Code 3 beendet.
```
I suspect this is because of the space in my user folder. This also breaks razzle.cmd

**Comment by ourway** [comment]
IMHO, It's so fascinating to see Windows people got interested by a new Terminal. Looks like 25 years ago with a fedora 2.

**Comment by wvdvegt** [comment]
Same here (really annoying this kind of issues still exists).

**Comment by zadjii-msft** [comment]
Yep, this is a real bug. Should've escaped that commandline with quotes. I believe the bug is in one of the `.props` files, but I can't be sure which one.

**Comment by zadjii-msft** [comment]
If someone wanted to dig into this and properly escape the commands in question, I'd happily review the PR :)

**Comment by DHowett-MSFT** [comment]
Or, replace the commands with real MSBuild rules!

________________________________

**Comment by jpandersen87** [comment]
Files of note in regards to fixing directories not being quoted in commands (either by quotation marks or `&quot;` as necessary):

- src\host\ft_uia\Host.Tests.UIA.csproj
- src\cppwinrt.build.post.props
- src\propsheet\propsheet.vcxproj (I inserted a period character after the output path variables to force a period before the ending slash so that mc.exe was happy)

I am able to successfully build the CascadiaPackage project on x64 release after these changes.

**Comment by wvdvegt** [comment]
1) src\cppwinrt.build.post.props (added &quot; entities):
```
  <ItemDefinitionGroup Condition="'$(Platform)'!='Win32'">
    <PreBuildEvent>
      <Command>
        if not exist &quot;$(OpenConsoleDir)$(Platform)\$(Configuration)\$(ProjectName)&quot; mkdir &quot;$(OpenConsoleDir)$(Platform)\$(Configuration)\$(ProjectName)&quot;
      </Command>
    </PreBuildEvent>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <PreBuildEvent>
      <Command>
        if not exist &quot;$(OpenConsoleDir)$(Configuration)\$(ProjectName)&quot; mkdir &quot;$(OpenConsoleDir)\$(Configuration)\$(ProjectName)&quot;
      </Command>
    </PreBuildEvent>
  </ItemDefinitionGroup>
```
2) src\propsheet\propsheet.vcxproj (added &quot; entities to mc.exe arguments AND added a . to $(IntermediateOutputPath) because the project uses a .dll suffix):
```
  <Target Name="MessageCompile" Inputs="@(MessageCompile)" Outputs="$(IntermediateOutputPath)\%(MessageCompile.Filename).h" BeforeTargets="ClCompile">
    <Exec Command="mc.exe /h &quot;$(IntermediateOutputPath).&quot; /r &quot;$(IntermediateOutputPath).&quot; @(MessageCompile)" />
  </Target>
```
3) src\cppwinrt.build.post.props (added &quot; entities to xcopy arguments):
```
  <ItemDefinitionGroup Condition="'$(NoOutputRedirection)'=='true' And '$(ConfigurationType)'=='DynamicLibrary' And '$(DontCopyOutput)'!='true'">
    <PostBuildEvent Condition="'$(Platform)'!='Win32'">
      <Command>
        echo OutDir=$(OutDir)
        (echo f | xcopy /y &quot;$(OutDir)$(ProjectName).dll&quot; &quot;$(OpenConsoleDir)$(Platform)\$(Configuration)\$(ProjectName).dll&quot; )
        (echo f | xcopy /y &quot;$(OutDir)$(ProjectName).pdb&quot; &quot;$(OpenConsoleDir)$(Platform)\$(Configuration)\$(ProjectName).pdb&quot; )
      </Command>
    </PostBuildEvent>
    <PostBuildEvent Condition="'$(Platform)'=='Win32'">
      <Command>
        echo OutDir=$(OutDir)
        (echo f | xcopy /y &quot;$(OutDir)$(ProjectName).dll&quot; &quot;$(OpenConsoleDir)$(Configuration)\$(ProjectName).dll&quot; )
        (echo f | xcopy /y &quot;$(OutDir)$(ProjectName).pdb&quot; &quot;$(OpenConsoleDir)$(Configuration)\$(ProjectName).pdb&quot; )
      </Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
```

**Comment by RefundGarbage** [comment]
One possible solution:
**DON'T** put the files under your user folder, or any sub directories from your user folder such as Documents, Downloads. 
Even USB drives work fine.

**Comment by fridtjof** [comment]
To be fair, that's a workaround, not a solution.

**Comment by PikaFan123** [comment]
> 
> 
> One possible solution:
> **DON'T** put the files under your user folder, or any sub directories from your user folder such as Documents, Downloads.
> Even USB drives work fine.

I tried doing this but still get the same Error

**Comment by zugazagoitia** [comment]
There's still a problem in the post-compile commands.

Some paths are unquoted, i was able to fix it like this.

![image](https://user-images.githubusercontent.com/23284823/58079867-4b588b80-7bb2-11e9-8331-f737a42f9178.png)
![image](https://user-images.githubusercontent.com/23284823/58079882-54495d00-7bb2-11e9-8a37-b2f82d7d5761.png)

**Comment by usergotnoname** [comment]
20>mc : error : 0x3 trying to open file <Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\>.
20>C:\Users\Itachi Uchiha\Documents\Terminal\src\propsheet\propsheet.vcxproj(81,5): error MSB3073: The command "mc.exe /h C:\Users\Itachi Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\ /r C:\Users\Itachi Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\ strid.mc" exited with code 1.

**Comment by usergotnoname** [comment]
`20>mc : error : 0x3 trying to open file <Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\>.
20>C:\Users\Itachi Uchiha\Documents\Terminal\src\propsheet\propsheet.vcxproj(81,5): error MSB3073: The command "mc.exe /h C:\Users\Itachi Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\ /r C:\Users\Itachi Uchiha\Documents\Terminal\\obj\x64\Release\Propsheet.DLL\ strid.mc" exited with code 1.`
