### ISSUE TITLE
Can we get a list of all the properties that we can use in settings

### ISSUE THREAD

**Issue by labTifo** [microsoft/terminal#4383]
I apologise in advance because this is not a technical issue.

Can we get a list of all the properties that we can use in settings.json file ?

**Comment by zadjii-msft** [comment]
We've already got one ready for you 😄 

* [This is the complete list of all the properties](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)
* [This is a helpful doc for how to use them](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md)
* [For the more  technically inclined, this is the json schema for all the settings as well](https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json)

**Comment by labTifo** [comment]
@zadjii-msft  Thank you so much.
