### ISSUE TITLE
10X Terminal concatenates early input with "cls" command

### ISSUE THREAD

**Issue by bviglietta** [microsoft/terminal#4385]
# Environment

```none
Windows build number: Windows 10X build 19553
Windows Terminal version (if applicable): 0.8.3521.0
```

# Steps to reproduce

I launched the Windows Terminal Universal (Preview) app, and as it launched I started typing, beginning with the letters "cm".

# Expected behavior

# Actual behavior

The first thing the Terminal displayed was

```
M:\windows\system32>cmcls
'cmcls' is not recognized as an internal or external command, operable program or batch file.
```

Evidently Terminal likes to start things off with a "cls" to clear the screen, but if you type too early, your input gets concatenated with the secret cls command.

**Comment by miniksa** [comment]
Set to me to reject input processing until after I'm done with the secret wink-nudge.

**Comment by miniksa** [comment]
And by reject, I mean... buffer it until I'm done. Not reject it straight up. The one that makes sense.

**Comment by zadjii-msft** [comment]
lol

**Comment by miniksa** [comment]
> lol

Yeah well. Whatever.
