### ISSUE TITLE
Display what's being typed when waiting for another command to finish

### ISSUE THREAD

**Issue by sachinjoseph** [microsoft/terminal#4386]
Many common commands take a few seconds to complete, and the command that follows is usually known in advance. A common command-flow example:
**pwsh**> git checkout master ↲
`<wait for command to complete>`
**pwsh**> git pull ↲
`<wait for command to complete>`
**pwsh**> git checkout -b feature/foo ↲

Now, after typing in "git checkout master↲", there's a short wait for the command to complete. The next command can be typed in during this wait, but they are not displayed. Can we display what's being typed in while some command is executing? Then, the flow becomes something like:
**pwsh**> git checkout master ↲
`<see characters typed in while waiting for the previous command>` git pull
**pwsh**> git pull ↲ `<user would have to just hit the enter key at this point as the command has already been typed in while waiting for the previous command to complete>`
`<see characters typed in while waiting for the previous command>` git checkout -b feature/foo 
**pwsh**> git checkout -b feature/foo ↲ `<user would have to just hit the enter key at this point as the command has already been typed in while waiting for the previous command to complete>`

**Comment by DHowett-MSFT** [comment]
This is, strictly-speaking, up to the application that's receiving input. I think there's a duplicate for this laying around somewhere else in out repo, but I can't find it at the moment.

**Comment by DHowett-MSFT** [comment]
The console backing the terminal has a mode where it will echo all user input; engaging this is an application's choice.
