### ISSUE TITLE
Open PowerShell as Admin

### ISSUE THREAD

**Issue by jimblanchard** [microsoft/Terminal#439]
Is it possible to have Terminal open PowerShell as an admin? The UAC popup is fine, I'm working interactive, I just occasionally need the elevation.

**Comment by DHowett-MSFT** [comment]
For now you’ll need to elevate the entire terminal application. Sorry.

________________________________

**Comment by donovanlange** [comment]
Thanks @DHowett-MSFT, @jimblanchard for the response!  Curious if this is something that's open to consideration though in the future, and worth tracking as a Feature Request.  (Not sure how much to read into the Closing of the Issue per-se.)

As a frequent user of Console2/Console.Z/ConEmu/and other Windows Console replacements -- this is one of the great benefits of having an integrated _tabbed_ terminal, in that I can keep all of my terminals in a singular window (in fact, I often theme the background colors to be noticeably different with my admin prompt "red" so it's easily distinguishable) and easily switch between elevated priveleges and non-elevated as needed.  Being able to start a new Admin terminal via a keyboard shortcut to `choco install` a utility is a very handy and convenient feature!
