### ISSUE TITLE
powershell error:  [error 0x80070002 when launching `powershell.exe']

### ISSUE THREAD

**Issue by ZOASR** [microsoft/terminal#4390]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.30]
Windows Terminal version: v0.8.10261.0
```

# Steps to reproduce

Just By Opening Powrshell Command-Line In windows terminal  (cmd Works fine)

# Actual behavior
This Error appears:
```
[error 0x80070002 when launching `powershell.exe']
```

``powershell``
![image](https://user-images.githubusercontent.com/44146518/73313035-ce96aa80-4232-11ea-8f01-43adf9b49586.png)

``cmd``
![image](https://user-images.githubusercontent.com/44146518/73313181-2fbe7e00-4233-11ea-8a2d-8384a2d5abfe.png)

**Comment by DHowett-MSFT** [comment]
Your `PATH` environment variable is damaged and does not contain `C:\Windows\system32\WindowsPowerShell\v1.0`.
