### ISSUE TITLE
Backspace functionality broken thru SSH after latest update

### ISSUE THREAD

**Issue by OmriSama** [microsoft/terminal#4391]
# Environment

```none
Windows build number: **10.0.18363.592**
Windows Terminal version (if applicable): **0.8.10261.0**


Any other software? **No**
```

I use Windows Terminal everyday, SSHing into a local Virtual machine. (`profile.commandline = "ssh.exe ubuntuvm"`).

Before updating, I was able to use `Ctrl+Alt+Backspace` to delete whole words at a time. I saw that the update made changes to `Ctrl+Backspace`, and went to check and noticed the functionality is broken. This happens both when I use Zsh or Bash (but not with `cmd.exe`), so I'm thinking it is a terminal level issue. 

Interestingly enough, `Ctrl+Alt+Backspace` seems to work fine when I use WSL 1 (same configuration and everything as my VM though).

# Steps to reproduce

Try to use `Ctrl+Backspace` or `Ctrl+Alt+Backspace` to delete whole words in terminal.

# Expected behavior

The terminal erases one word at a time.

# Actual behavior

Only one character is erased at a time.

**Comment by DHowett-MSFT** [comment]
Good news! This is actually an openssh issue (https://github.com/PowerShell/Win32-OpenSSH/issues/1310) which will be fixed with the 8.1 release.
