### ISSUE TITLE
`Ctrl + h`'s behavior is differ from command prompt window

### ISSUE THREAD

**Issue by koron** [microsoft/terminal#4397]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): 0.8.10261.0

Any other software? no
```

# Steps to reproduce

just type <kbd>Ctrl + h</kbd>

# Expected behavior

Delete a character before the cursor, as same as command prompt window.

# Actual behavior

Delete a whole word before the cursor.

# Notes

I guess that this is a side effect of https://github.com/microsoft/terminal/pull/3935

**Comment by koron** [comment]
it affects vim in cmd in WindowsTerminal.

when i hit <kbd>Ctrl+h</kbd> in insert mode, i got `Îz`.

![image](https://user-images.githubusercontent.com/468368/73423946-effdb080-4370-11ea-9da5-8952aae3cddd.png)

I expected to delete a character before the cursor.

**Comment by DHowett-MSFT** [comment]
So, this is one of those issues we _might_ just have to live with for now. `^H` means, to many other applications, the same thing as <kbd>Ctrl+Backspace</kbd>. To the rest of them, it means <kbd>Backspace</kbd>. It looks like Vim for Windows has an explicit binding for `<C-H>`, but now it's receiving `<C-Bksp>`. In Vim for LInux this works fine.

We may need to wait for /dup #879 so that Windows Vim can use raw key mode.

**Comment by dianlujitao** [comment]
@DHowett-MSFT I encountered the same issue, but don't think it's related to Vim for Windows.

Here's my result:

Setup | Result
--- | ---
WT (wsl) + Vim | Y
WT (wsl) + Vim over OpenSSH_8.1p1 | Y
WT (powershell) + Vim over OpenSSH_for_Windows_7.7p1 | __N__
WT (cmd) + Vim over OpenSSH_for_Windows_7.7p1 | __N__
powershell.exe + Vim over OpenSSH_for_Windows_7.7p1 | Y

**Comment by DHowett-MSFT** [comment]
This is one of those weird things :smile: WT and OpenSSH_for_Windows actually use the same translation backend to talk to windows console applications, but WT uses a newer version of it. The older version was more compatible with certain windows apps, but it worked less well with everything else.

**Comment by koron** [comment]
this problem is introduced by #3935 .
#3935 solved only one problem which describled in #879 in wrong way.
so i think that #3935 should be reverted.

**Comment by DHowett-MSFT** [comment]
The problem is that 3935 solved the problem described in 879 the only way that is correct for a Terminal emulator. We're right here on the boundary between what consoles and terminals need to support, and we made the call to be a _terminal_ first.

I'm not certain that was the right decision?

**Comment by debuuu** [comment]
The bot mentioned a "referenced thread", where is that? Would like to track this, it broke some Vim muscle memory for me.

**Comment by DHowett-MSFT** [comment]
Sorry @debuuu - it's referring to #879

**Comment by koron** [comment]
the problem is that the terminal generate same codes `0x08` for <kbd>ctrl+h</kbd> and <kbd>ctrl+backspace</kbd>.
but #3935 resolved it by parsing the code (`0x08`) as <kbd>ctrl+backspace</kbd> always.

i don't think this is correct way to fix.

**Comment by Milly** [comment]
Ref #4999 #5957
