### ISSUE TITLE
Don't let results hide under search box

### ISSUE THREAD

**Issue by fredless** [microsoft/terminal#4407]
# Description of the new feature/enhancement

Sometimes a search result can hide under the search box, this is confusing to the uninitiated.  Search should always show the found item without hiding it under a UI element.
![hidingUnderSearchBox](https://user-images.githubusercontent.com/16697069/73428988-61951a80-42ef-11ea-9421-d89c66a20cee.gif)

# Proposed technical implementation details (optional)

Perhaps scroll the search result further up to pad it away from the search box in most situations - not very elegant though.

**Comment by zadjii-msft** [comment]
I think you've got a good point here.

**Comment by DHowett-MSFT** [comment]
Yep, this is reasonable.

**Comment by DHowett-MSFT** [comment]
Moved to v1.0 - we can talk about this in a later scrub. :smile:

**Comment by carlos-zamora** [comment]
Also tagging this to #3920 since this would be something nice to deliver as a part of an updated Search experience.
