### ISSUE TITLE
Symbol @

### ISSUE THREAD

**Issue by Valkinaz** [microsoft/terminal#4409]
Hello.
Found some bug with `@` symbol.
I use terminal for SSH connections to remote servers mostly. I have my local server on the Hyper-V and a few remote servers. Plus, I am from Russia, so my language is RU often.

# Environment
Version of Terminal:
`0.8.10261.0`

Version of Windows:
`Microsoft Windows [Version 10.0.18362.592]`

Version of SSH:
`OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`

> Are you using ssh through WSL?

No

# Steps to reproduce
1. Set RU language before run the terminal
2. Run the terminal
3. On this stage you can use `@` and login into remote server, for example `ssh user@192.168.*.*`
4. And after it, you can't use `@` anymore. Terminal nothing print by keypress and cut `@` if you tried to paste string with it from buffer.

Don't try reproduce it with EN language before run the terminal. In that case it works well.

# Expected behavior
Can use `@` at any time

# Actual behavior
Can't use `@`

**Comment by DHowett-MSFT** [comment]
Can you please fill out the template and provide information on what version you are using?

**Comment by Valkinaz** [comment]
Sure but where can i find the template?
I just click to support link in Microsoft Store

**Comment by DHowett-MSFT** [comment]
When you filed this bug, there was a block of text that you deleted asking for your version number.

What version of Terminal are you using?
What version of Windows are you using?
What version of SSH are you using? Are you using ssh through WSL?

**Comment by Valkinaz** [comment]
Sorry for incorrect creation of bug report.
There is straight link at new issue without templates in MS Store.
I found it now when clicked `New Issue` on my own.
I updated the first message.

**Comment by DHowett-MSFT** [comment]
Thanks for the info! Sorry about that bad link.

Since @ works in the Terminal and not over SSH (I had to verify that you were using Win32-OpenSSH), I think the issue needs to be reported on [their repository](https://github.com/PowerShell/Win32-OpenSSH).

Sorry again!
