### ISSUE TITLE
switch acrylic effect to transparency when window is not focused

### ISSUE THREAD

**Issue by ackvf** [microsoft/terminal#4413]
# Description of the new feature/enhancement

Apparently the loss of acrylic transparency is an OS limitation.

Can we get good old transparency when the window is not focused and `useAcrylic` when focused?

From left
standard CMD with transparency, focused terminal, background terminal
![image](https://user-images.githubusercontent.com/2313018/73467282-699e9a00-4383-11ea-9871-5c3ac6d29afe.png)

**Comment by DHowett-MSFT** [comment]
I know you specified “when not focused,” but the engineering work required is the same as 603. :)

**Comment by ackvf** [comment]
@DHowett-MSFT Thank you, I was focused on the Acrylic transparency so much that I have missed that.
There also already is a feature-request to have different config for focused and unfocused so I guess this issue is perfectly covered by the two.

**Comment by admered1** [comment]
I am a Linux native and miss the gnome-terminal transparency. The idea is to see through one or more of the terminals to the windows underneath. If the focused window goes fuzzy, this defeats the whole purpose.

**Comment by b-hayes** [comment]
Totally agree with @admered1 I really don't care for acrylic it has no use.
I want plain transparency so that I can read the text behind my terminal as I am typing. That's the whole point to transparent terminal IMO.
