### ISSUE TITLE
Tmux doesn't refresh properly

### ISSUE THREAD

**Issue by eduardoarandah** [microsoft/terminal#4414]
Tmux doesn't refresh properly on yarn

# Environment

Microsoft Windows [Versión 10.0.19041.21]
Windows terminal: 0.8.10261.0
tmux 2.6
yarn 1.21.1

.tmux.conf
```
set -g default-terminal "tmux-256color"
```

# Steps to reproduce

1.- Split screen with tmux and run some webpack watcher process on the right. 
(I've tried to run "top" on the right, but it works fine!)

```
tmux
Ctrl-%
yarn start
```

2.- Then resize, open another windows-terminal-tab or resize tmux splits

This is the package I'm running: https://github.com/roots/sage

Installation:
```
yarn
yarn start
```

# Expected behavior

If same command is run in the old terminal, it works fine:

![Screenshot_2](https://user-images.githubusercontent.com/4065733/73470975-4efdfe00-434e-11ea-81c7-e127edd9adc5.png)

# Actual behavior

The terminal doesn't refresh, creating this mess:

![Screenshot_1](https://user-images.githubusercontent.com/4065733/73470919-3857a700-434e-11ea-979c-19061504a6b9.png)

**Comment by DHowett-MSFT** [comment]
Sorry, when you say "then resize" do you mean resize _terminal_ or resize _the tmux pane_?

**Comment by eduardoarandah** [comment]
Once the bug starts happening, it doesn't refresh on any of those. 

It only happens on tmux. 
If I close tmux and run `yarn` then it refreshes fine. 

In case this could be related: 
After upgrading to windows insiders, my third monitor (VGA) sometimes doesn't work unless I restart my PC completely. 
Could there be something related to video card? 
NVIDIA GeForce GT710

**Comment by DHowett-MSFT** [comment]
Do you perchance have the ability to build and run terminal from source? I've got a theory...

**Comment by eduardoarandah** [comment]
yeah I guess, do you have the commands? 
it's 64bit intel

**Comment by DHowett-MSFT** [comment]
Are you still seeing this with v0.10? We've made some changes to our rendering and text processing infrastructure.

**Comment by eduardoarandah** [comment]
## It works fine now!

tried: 
- tmux
- change windows
- webpack
- htop
- vim 

Version: 0.10.781.0

![image](https://user-images.githubusercontent.com/4065733/77376167-3b12bf00-6d35-11ea-87ef-9864fdbee688.png)

![image](https://user-images.githubusercontent.com/4065733/77376173-4108a000-6d35-11ea-9370-ee8fd9750c4b.png)

**Comment by DHowett-MSFT** [comment]
I'm so happy to hear that. Thank you.
