### ISSUE TITLE
Wrong showing app name on run as administrator prompt (Unknown program)

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#4425]
Hello,
Wrong showing app name on run as administrator prompt
Please fix it.
![User Account Control](https://user-images.githubusercontent.com/23485114/73538980-2c68f500-43e1-11ea-957f-7ef55ad3740e.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2289 for more discussion.

/dup #2289
