### ISSUE TITLE
Update `TestHostApp` to always copy `TerminalApp.LocalTests.dll`

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#4426]
Since I just used a copy rule for the `TestHostApp` project's dependency on the `LocalTests_TerminalApp` project, if you just change the test code, the `TestHostApp` build won't auto pick-up the updated `TerminalApp.LocalTests.dll`. This is annoying if youre iterating on the local tests, since you can't just build `TestHostApp` to get the updated LocalTests.

The rule that's bad:

```xml
    <!-- Copy our test code from LocalTests_TerminalApp into this directory -->
    <Copy SourceFiles="$(_TestBinRoot)\LocalTests_TerminalApp\TerminalApp.LocalTests.dll"
          DestinationFiles="$(TargetDir)\TerminalApp.LocalTests.dll" />
```

As a workaround, you have to manually

`copy bin\x64\Debug\LocalTests_TerminalApp\TerminalApp.LocalTests.dll x64\Debug\TestHostApp\ /y`

from the solution root

**Comment by DHowett-MSFT** [comment]
I think there's a `<Copy>` option that says "always do this" or "only do if out of date".

**Comment by zadjii-msft** [comment]
You know what, we did this at some point in the past. I'm too lazy to look up the specific commit ATM.
