### ISSUE TITLE
_PaintBufferOutputHelper is causing a crash when state is invalid

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#4427]
Linked to MSFT:21270995.

Seeing a moderate crash volume on the console host with error 8007139f (E_INVALID_STATE).

Need to investigate and stop the crash.

This looks sorta like #2778 (same stack) but that one was duped a different direction...

**Comment by DHowett-MSFT** [comment]
Reflected inbox commit that fixes this.
