### ISSUE TITLE
Add support for tab reordering

### ISSUE THREAD

**Issue by matthew4850** [microsoft/terminal#443]
* Your Windows build number:  10.0.18890.1000

* What you're doing and what's happening: Attempting to drag tabs to reorder or detach does not work. Tabs stay exactly where they are and show no sign of moving

* What's wrong / what should be happening instead: Tabs should be able to be reordered and detached.

**Comment by zadjii-msft** [comment]
This is because we're using a really early version of the Tab Control. In future versions, it'll be more feature complete. Until then, all we request is patience :)

**Comment by DHowett-MSFT** [comment]
This one is actually on us. Tammy so kindly hooked up the reordering events for us!

@carlos-zamora even tried hooking them up to TerminalApp, but it underwent immediate and energetic disassembly.

**Comment by DHowett-MSFT** [comment]
I'm repurposing this for tab reordering and demoting it to a Task. We'll track the (much larger) workitem to do tab tearoff as a deliverable for vBacklog.

Notes/reasoning:
* Tab reordering is easy.
* Tab tearoff requires us to answer the following questions:
  * WT.exe is a multi-instance app. How do we drag tabs between _different processes?_
    * Should WT be multi-instance? We may want to single-instance it.
      * If we want to single-instance it we need to design "new window" (part of #1051)
  * We still need to design "new window" for tearoff-without-merge because we need a drop target for the old tab.

**Comment by DHowett-MSFT** [comment]
Moved tearoff to #1256.

**Comment by JeroMiya** [comment]
Was about to open up my own issue but found this one - great idea! Just want to add one thing to the suggestion (not sure if it should be a separate issue, seems related?):

In addition to being able to tear off tabs into new windows, it would also be nice to be able to dock tabs onto an existing window, similar to Visual Studio, with support for snapping to quadrants to make it easy to setup a 4 x 4 tab window grid (in this use case, you'd snap left/right tabs first, then snap the last two into quadrants, if that makes sense).

**Comment by mbrodala** [comment]
@JeroMiya You should open a separate issue for your suggestion.

**Comment by eyalroth** [comment]
Another suggestion to add on top of this feature: add a keyboard shortcut for moving the currently active tab left/right. For instance, in my Chrome I have this configured to `Alt+Shift+Left/Right arrow`.

**Comment by LatinSuD** [comment]
Is there any key shortcut to move tab? Mouse dragging is not working too smooth.

**Comment by eyalroth** [comment]
@LatinSuD See #3593.
