### ISSUE TITLE
Terminal Intellisense dropdown

### ISSUE THREAD

**Issue by Ayanmullick** [microsoft/terminal#4436]
## Description of the new feature/enhancement
Is there a way to get a terminal intellisense dropdown in Microsoft terminal like one could in PowerShell ISE?

## Proposed technical implementation details (optional)
![image](https://user-images.githubusercontent.com/17693249/73595222-ac738580-44db-11ea-887f-28c3ffea218d.png)

Working on the terminal with PowerShell 7 could become more convenient if one was able to see all the potential matches for one's command in a dropdown right in the terminal.

**Comment by Ayanmullick** [comment]
Maybe a SQLCLI-like dropdown if not a PSISE-like dropdown.

![image](https://user-images.githubusercontent.com/17693249/74194301-9d4cb000-4c1e-11ea-81ed-77f490dd2d30.png)

**Comment by Ayanmullick** [comment]
@DHowett-MSFT , This isn't a duplicate of [#643](https://github.com/microsoft/terminal/issues/643). This is specifically about the intellisense **dropdown**.

**Comment by DHowett** [comment]
It's a duplicate because both of them request auxiliary terminal UI based on shell-provided completion content.
