### ISSUE TITLE
How to add the python command line?

### ISSUE THREAD

**Issue by eflrp** [microsoft/terminal#4439]
Hello,
on my computer I installed python and I would like to know if we can add the python command line in Windows Terminal.
If possible, you can tell me how to do it.

thank you in advance

**Comment by nikeplusdash** [comment]
Hi,
You can do this by adding profiles in the settings of the preview.
I have added the following,

```JSON
{
    "name": "Python",
    "commandline": "python.exe",
    "hidden": false
}
```

For detailed explanation on the profiles.json check out this:
https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md
https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md

**Comment by DHowett-MSFT** [comment]
Closing this as it’s been answered. Thanks @nikeplusdash

**Comment by eflrp** [comment]
Hello,
do not fill in the "uuid" field ?

**Comment by DHowett-MSFT** [comment]
Correct. Do not provide the `guid` field.

**Comment by eflrp** [comment]
ok thanks
