### ISSUE TITLE
Show the current active github branch

### ISSUE THREAD

**Issue by labTifo** [microsoft/terminal#4440]
As  daily user of github, I would love to see the terminal display the name of the active branch of the repository in the current folder.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for the request! Terminal's only job is to get text onto the screen, so this'll have to be a request against your shell. For PowerShell, you should look into "posh-git." For CMD, you'll have to come to terms with it being too dangerous for us to change it :smile:
