### ISSUE TITLE
Allow end-users to select and copy shell output without the mouse

### ISSUE THREAD

**Issue by shaunluttin** [microsoft/terminal#4441]
# Description of the new feature/enhancement

Problem: Selecting and copying shell output requires the use of the mouse.

Solution: Allow end-users to select and copy shell output without the mouse.

Example: In the ConEmu terminal emulator, [pressing Shift+UpArrow](https://conemu.github.io/en/KeyboardShortcuts.html) initiates block selection and navigation of the shell output.

Here is an example from ConEmu which shows a use case in which the end-user selects and copies a commit hash from the `git log` output.

![conemu-cursor-select](https://user-images.githubusercontent.com/2066637/73618462-c052e080-45dc-11ea-99ff-876058e63e7c.gif)

**Comment by zadjii-msft** [comment]
You'd probably be interested in:
* #2840 - a spec for this functionality
* #3758 - a PR for some of the functionality mentioned in the above spec
* the issue we're using to track this functionality - /dup #715
