### ISSUE TITLE
Is there way to download the terminal installer?

### ISSUE THREAD

**Issue by thkrishn** [microsoft/terminal#4442]
#3299 Description of the new feature/enhancement
Windows store access is blocked on some corporate machines so is there a way to download the terminal executable/ installer?
Looked for the same on google search and bing search could not find anything on the same 

Github builds are misx which still needs to install from store; I still do not have a build where I can double click and install misx

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
You can install the msix build outside the store, or unzip it like a zip archive. /dup #1386
