### ISSUE TITLE
Minimize/maximize shortcut

### ISSUE THREAD

**Issue by JekRock** [microsoft/terminal#4443]
# Description of the new feature/enhancement

It would be nice to have a system shortcut to minimize/maximize the terminal window

**Comment by zadjii-msft** [comment]
Do you mean like <kbd>Win+Up</kbd> or <kbd>Win+Down</kbd>?

**Comment by JekRock** [comment]
No, I mean a shortcut that will work when the terminal window doesn't have the focus.
For example, I open the terminal window, minimize it, switch to any other window, and then push a shortcut that will maximize the terminal window and move the focus on it. If the terminal window was maximized the shortcut just moves the focus to the terminal window. If the focus is on the terminal window, the shortcut will minimize the terminal window.
And it would be nice to have an option to either minimize the terminal window or minimize it to the tray.

**Comment by zadjii-msft** [comment]
Ah okay, that's much clearer. You're looking for /dup #653
