### ISSUE TITLE
How to Compile x86

### ISSUE THREAD

**Issue by icoder-new** [microsoft/terminal#4447]
_**How to compile this project and which program!!**_

<h1>HELP!!!</h1>

```
for i in range(0,101):
     print('HELP!!')
```

**Comment by DanAtkinson** [comment]
This repository is for the development of the Terminal application and is not intended to answer questions relating to coding inside the Terminal app (or indeed any OS console). You should instead direct such questions as sites such as stackoverflow.com

**Comment by DanAtkinson** [comment]
Assuming you have Visual Studio installed, clone the project, open `OpenConsole.sln` and compile, setting the platform to x86.

**Comment by zadjii-msft** [comment]
You know, there's a really helpful guide for building the code in [the README](https://github.com/microsoft/terminal#building-the-code). Maybe you should start there?

**Comment by icoder-new** [comment]
**_

> Thanks I know it doesn't work in windows 7 Ultimate x86

_**

1. My computer is older
2. It was for confuse my English knowledge
3. Sorry I don't use Windows (I'm on MX Linux)
