### ISSUE TITLE
ScreenInfoUiaProvider::GetSelection() returns an improper result

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4452]
# Summary
Our TermControlUiaProvider (aka ScreenInfoUiaProvider) returns a list of UiaTextRange for our selection (one per row in the buffer).

The docs for `GetSelection` state we should only return one range.

# Technical Details
For [SupportedTextSelection](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/ne-uiautomationcore-supportedtextselection), we state that we only support a single selection.

The documentation for [GetSelection](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-itextprovider-getselection) states as follows:

>For UI Automation providers that support text selection, the provider should implement this method and also return a ITextProvider::SupportedTextSelection value.
>
>If the control contains only a single span of selected text, the pRetVal array should contain a single text range.
>
>If the control contains a text insertion point but no text is selected, the pRetVal array should contain a degenerate (empty) text range at the position of the text insertion point.

**Comment by carlos-zamora** [comment]
This impacts signaling for selection (#2447).

If a selection is created, we return the wrong range.

**Comment by DHowett-MSFT** [comment]
-triage since this is in PR and we chatted about it offline
