### ISSUE TITLE
Terminal crashing when dragging the tab

### ISSUE THREAD

**Issue by mmativ** [microsoft/terminal#4453]
# Environment

Windows Terminal version (if applicable): v0.8.10261.0

# Steps to reproduce

1. Open 2 tabs and try to drag it

# Expected behavior

- It should change tab without crashing

# Actual behavior

- When dragging the tab, it will hang and crash after.

**Comment by DHowett-MSFT** [comment]
Just going to guess this is a /dupe of #4059
