### ISSUE TITLE
Can't write "|" = pipe in comand line 

### ISSUE THREAD

**Issue by Lender2806** [microsoft/terminal#4454]
During work with the console. noticed that can't write "|" = pipe to use grep command.
Using PowerShell inside.
![Bug Micr](https://user-images.githubusercontent.com/49481774/73737285-029a3000-474b-11ea-904b-029ed4f379b8.jpg)

**Comment by DHowett-MSFT** [comment]
This is very unusual. Can you share more information? What sort of keyboard do you have? What layout is your OS using? What language is your machine?

What versions of Windows and Terminal and PowerShell? (that looks like WSL or git bash to me, not powershell. Are you using SSH?)
