### ISSUE TITLE
Customize default panes layout when launch terminal

### ISSUE THREAD

**Issue by kindox10** [microsoft/terminal#4462]
I want to launch the terminal with two vertical panes by default. Is there a way to do this?

Idea:

I already have a command to add a vertical pane:

`{ "command": { "action": "splitPane", "split": "vertical"}, "keys": ["ctrl+t"]}`

so it would be enough adding a way to "execute" commands automatically on terminal startup.

**Comment by zadjii-msft** [comment]
Hey wadda you know, this is something I considered when writing the [Commandline Args Spec](https://github.com/microsoft/terminal/blob/master/doc/specs/%23607%20-%20Commandline%20Arguments%20for%20the%20Windows%20Terminal.md).

> In the past we've had requests (like #756) for having the terminal start with multiple tabs/panes by default. This might be a path to enabling that scenario. One could imagine the profiles.json file including a defaultConfiguration property, with a path to a .conf file filled with commands. We'd parse that file on window creation just the same as if it was parsed on the commandline. If the user provides a file on the commandline, we'll just ignore that value from profiles.json.

Okay maybe that text is a little out of date, but the point stands. This is something that's largely going to be tracked by /dup #756, so I'll redirect discussion to that thread.
