### ISSUE TITLE
The terminal receives a background color error after these actions

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#4463]
# Environment

```
Windows build number: 10.0.18363.628
Windows Terminal version:  0.8.10261.0

Any other software?
```

# Steps to reproduce

Minimize the height of the Terminal.
Create two or more tabs
Press ALT+F4
Maximize the height of the Terminal.

![Anmerkung 2020-02-04 210621](https://user-images.githubusercontent.com/47790579/73782338-39dfff80-4792-11ea-8eb9-dc8d2835707b.png)

# Expected behavior

A new Window was opened

# Actual behavior

The Terminal receives a fault.

**Comment by DHowett-MSFT** [comment]
Thanks. This is the same as /dup #2380
