### ISSUE TITLE
All tabs cannot be closed after these actions.

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#4464]
# Environment

```
Windows build number: 10.0.18363.628
Windows Terminal version:  0.8.10261.0

Any other software?
```

# Steps to reproduce

Create two or more tabs.
Reduce the width and the length until it is no longer possible.
Press ALT+F4
Maximize the width and the length.

![Anmerkung 2020-02-04 224705](https://user-images.githubusercontent.com/47790579/73790182-5aaf5180-47a0-11ea-93a7-b29da067a0ad.png)

# Expected behavior

The "Do you want to close all tabs" window should remain in the middle.

# Actual behavior

The "Do you want to close all tabs" window is displayed in the upper left corner.

**Comment by DHowett-MSFT** [comment]
Dude, same bug as last time you filed it. /dup #2380

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by Qantex** [comment]
I'm sorry, if I  **irritated** you. 😅

**Comment by DHowett-MSFT** [comment]
You haven't irritated me 👍 alles gut

**Comment by AVDAX** [comment]
@DHowett-MSFT 
Could you delete this report? I'd like to run a diagnostic on Github and maybe find a weakness.
**Thank you very much! :)**

**Comment by AVDAX** [comment]
@DHowett-MSFT 
Could you delete this report? I'd like to run a diagnostic on Github and maybe find a weakness.
Thank you very much! :)

**Comment by DHowett-MSFT** [comment]
**Please do not run a diagnostic on GitHub using our repository.**

**Comment by AVDAX** [comment]
@DHowett-MSFT Don't worry, this shouldn't do much damage to this source. 
**No texts are displayed; the system checks for errors when deleting.**

**Comment by AVDAX** [comment]
By source I mean this report that I have compiled.

**Comment by DHowett-MSFT** [comment]
@AVDAX I'm not concerned about this repository specifically, it is simply inappropriate to use a production repository to test for flaws in other software. :smile:

This is best done on a personal repository, where you have control over the reports and when you delete them. It makes for a better vulnerability report if you can reproduce it in isolation!

**Comment by AVDAX** [comment]
@DHowett-MSFT I have already tested this internally, but I want to test it externally as well.
**No damage is added, it only checks whether errors occurred when deleting from this source.**

**Comment by AVDAX** [comment]
@DHowett-MSFT I mean, there are people who ask others to delete this source without knowing that they are looking for an error.

**I asked you and I told you why.**

**Comment by DHowett-MSFT** [comment]
I appreciate that. Thank you. Unfortunately, by the policy we follow in this repository we don't really delete issue content. I can't complete your request.

**Comment by AVDAX** [comment]
@DHowett I can understand that.

**Comment by AVDAX** [comment]
@DHowett-MSFT But could you make an **exception** for me?

**Comment by AVDAX** [comment]
@DHowett-MSFT Could you explain this **directive** to me in more detail? :)

**Comment by AVDAX** [comment]
@DHowett-MSFT I will try to contact GitHub customer service. **I hope this doesn't bother you.**
