### ISSUE TITLE
Selection Expansion should not be occurring during Rendering

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4465]
This is a _major_ bug, not because of what it's doing _now_, but how it's affecting other things.

## How our selection model operates
Whenever we set a selection anchor (i.e.: pointer movements, search, etc), we are recording the COORD of the pointer or space that we want to select. If we encounter a wide glyph (i.e.: 😐) or are doing chunk selection for words/lines, the selection anchors are wrong and we expand to encompass them during `_GetSelectionRects()`.

## Issues this is causing
1) #2447 Signaling for selection: the selection anchors we're returning are not representative of what gets selected.
2) #3758 MoveSelectionAnchor: moving the selection anchors don't actually represent what is selected. So expanding by character on a double click selection really shows this.

Both of these issues are blocked until this gets resolved.

## Proposed Approach
- On click,
  - decide if this was a single/double/triple click
  - this establishes an expansion mode
  - set start/end at pointer
  - edit start/end based on expansion mode + glyphs
- On drag,
  - if moving to the "right" of start, set end. Otherwise, set start.
  - from current cursor position, expand appropriately and update target endpoint

**Comment by DHowett-MSFT** [comment]
Wait, this is already in PR? Whoa. Yanking triage tag.

**Comment by carlos-zamora** [comment]
> Wait, this is already in PR? Whoa. Yanking triage tag.

Nope. Not in PR. Just related to the referred issue.

**Comment by DHowett-MSFT** [comment]
Okay. Can you build an estimate on fixing this one?

**Comment by carlos-zamora** [comment]
> Okay. Can you build an estimate on fixing this one?

I'd say 3 days of actual work. I'm having trouble wrapping my head around how to actually implement it.
