### ISSUE TITLE
The new tab button cannot be used via touch screen

### ISSUE THREAD

**Issue by matthew4850** [microsoft/Terminal#447]
* Your Windows build number:  10.0.18890.1000

* What you're doing and what's happening: If you tap the new tab button via touch screen then it acts as though you have tapped the drop-down arrow.

* What's wrong / what should be happening instead: It should open a new tab

**Comment by zadjii-msft** [comment]
I think this is "by-design" of all SplitButtons in UWP, which makes the UI a little friendlier for touch-only devices.
