### ISSUE TITLE
Powershells Start-Process with a -Verb and -WorkingDirectory flag does not set the New Processes Working Directory

### ISSUE THREAD

**Issue by runewake2** [microsoft/terminal#4471]
# Environment

```none
Microsoft Windows NT 10.0.18362.0
Windows Terminal (Preview) Version: 0.8.10261.0
```

# Steps to reproduce

1. Open Powershell in the Windows Terminal:

2. run `Start-Process cmd -verb RunAs -WorkingDirectory ./` to create a custom command prompt (or powershell instance) with a specific Working Directory.

3. A new command prompt is started but the Working Directory was not correctly set (it will be `C:\Windows\System32` - seems to be using the default as if the flag was not provided)

# Expected behavior

The newly started powershell instance should use the Working Directory passed into the `-WorkingDirectory` flag. This works if run from the included Powershell.exe

This behaves as expected if the `Start-Process` commandlet does not include both a Verb and WorkingDirectory flag (starting a non-administrative prompt has the correct working directory).

# Actual behavior

Working Directory for process started always seems to default back to the default value (`C:\Windows\System32`)

**Comment by DHowett-MSFT** [comment]
Does this happen outside of Windows Terminal as well?

I’m certain this is simply how ShellExecute works: the `runas` verb doesn’t allow you to specify any additional information, as it could lead to a trivial escalation of privilege.

**Comment by runewake2** [comment]
No, if you open a Powershell instance or Command Prompt and use `Start-Process powershell -verb RunAs -WorkingDirectory C:\` for example you'll open a new process at the top level of your `C:\` drive. This seems to be a distinct behavior to the Windows Terminal (which opens `C:\Windows\system32`).

A note: I have UAC enabled on the computers with this behavior.

While this behavior doesn't occur in normal Powershell or Command Prompt it does seem to also occur in the Powershell ISE.

**Comment by DHowett-MSFT** [comment]
Interesting! Thanks.

**Comment by DHowett-MSFT** [comment]
When I run this from standard powershell, I get...


![image](https://user-images.githubusercontent.com/14316954/73871189-4865ff80-4802-11ea-843a-6a9d9577a06e.png)

**Comment by DHowett-MSFT** [comment]
(with UAC enabled, as befault)

**Comment by runewake2** [comment]
I think I may be incorrect on the behavior here. Going to close this.

Passing in a working directory only appears valid when the original command is executed in an admin prompt already. Elevating it from any of CMD, Powershell, Powershell ISE or Windows Terminal has the same effect.

**Comment by jborean93** [comment]
In case it helps anyone coming across this in the future, the problem here is that using UAC (`-Verb Runas`) to start any executable inside `C:\Windows\System32` will ignore the explicit working directory provided to it, in this case it's `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`. This is behaviour inside the UAC broker that as far as I know cannot be changed.
