### ISSUE TITLE
[ui] Inconsistent "cmd" in new tab context menu

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#4476]
I just installed the most recent update from Releases.

Note the available shell names: "Windows PowerShell", "cmd", "Ubuntu-18.04", "Azure Cloud Shell" and how "cmd" is the only one not capitalized and not a proper word. Shouldn't it be "Command Prompt" or "Command Prompt (cmd)"? It is a well-known everywhere-existing shell. It would be nice if it is named consistently.

![image](https://user-images.githubusercontent.com/1041752/73861695-acf28000-483d-11ea-9e49-6e3ebae6fc30.png)

**Comment by DHowett-MSFT** [comment]
Yeah, we should probably call it Command Prompt.

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by vadimkantorov** [comment]
Also, please note that if one searches for Ubuntu app in Cortana, it is called "Ubuntu 18.04 LTS" without any dash:
![image](https://user-images.githubusercontent.com/1041752/73869196-2bedb580-484a-11ea-9443-9f211515494b.png)

Consistency would also be great in this respect too!

**Comment by DHowett-MSFT** [comment]
We explicitly ask the WSL distribution for its name. This is an upstream issue on Canonical.

**Comment by vadimkantorov** [comment]
Well, this difference in style is confusing (all other names use spaces for word separation). If the team considers this is okay - so be it. I just wanted to have it in issues in case other users want to search for this.

**Comment by vadimkantorov** [comment]
Also the minor margin between the context menu and the "v" button is not very common on Windows. And also when clicking on "v", both "v" and "+" get focus - strange.

**Comment by DHowett-MSFT** [comment]
Alright, let's not make this too big of a bucket issue for a bunch of UI complaints :smile:
We're following the windows xaml SplitButton style here: all Xaml split buttons do this!

**Comment by vadimkantorov** [comment]
> We're following the windows xaml SplitButton style here: all Xaml split buttons do this!

Ok :)

**Comment by vadimkantorov** [comment]
Would you like me to file a separate issue about the space between buttons and context menu?

**Comment by DHowett-MSFT** [comment]
Looking at it more, the menu spacing also seems consistent with other Xaml apps:

![image](https://user-images.githubusercontent.com/14316954/73871722-333da080-4803-11ea-8052-e4fdc9e1d5f3.png)

![image](https://user-images.githubusercontent.com/14316954/73871743-3b95db80-4803-11ea-8615-ccb26858e93b.png)

**Comment by vadimkantorov** [comment]
Hmm, ok then :)

**Comment by DHowett-MSFT** [comment]
1.x item: we may want to reopen the book on being able to use resource names as profile names; otherwise, we would have to figure out how to localize profile names (since `Command Prompt` is different in different languages, but `cmd` is _not_)

**Comment by vadimkantorov** [comment]
If one wanted to keep `cmd` in the name, you could have default name as "Command Prompt (cmd.exe)" and have that suffix regardless of localization

**Comment by DHowett-MSFT** [comment]
Meh, I'm not particularly bothered by the loss of "cmd.exe"

**Comment by vadimkantorov** [comment]
Just a discoverability question. But if localization is on, the user is doomed in any case: "PowerShell", "Ubuntu-18.04", "Командная строка" :)

**Comment by DHowett-MSFT** [comment]
PowerShell, Windows, and Ubuntu are product names and aren't generally localized. Your argument was that _command prompt_ usually is :smile: and on Windows it's not localized with "cmd.exe" at the end.

> It is a well-known everywhere-existing shell. It would be nice if it is named consistently.

**Comment by vadimkantorov** [comment]
Yes :)
