### ISSUE TITLE
Provide profile name in tab tooltip when it improves clarity

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#4478]
I opened a PowerShell and WSLv1 Ubuntu tabs. I've got:

Tab names:
- Windows Power Shell
- "Ubuntu-18.04" changing after a few seconds into "vadimkantorov@DESKTOP-4UF8FID"

Tab tooltips:
- Windows Power Shell
- vadimkantorov@DESKTOP-4UF8FID

For consistency, shouldn't WSLv1 tab tooltip read something like "Ubuntu-18.04: vadimkantorov@DESKTOP-4UF8FID"? 

Shouldn't all tabs either use shell-provided prompts or not? Shouldn't tooltips preserve shell type?

**Comment by DHowett-MSFT** [comment]
This is actually because Windows PowerShell _doesn't_ set the shell-provided title. This is consistent with the behavior we expect for tab titles.

**Comment by vadimkantorov** [comment]
In this issue the main complaint is about the Ubuntu tab tooltip (as is pointed out by the issue name!).

The Ubuntu tab tooltip has no mention of the the terminal type (it also has no logo). Also the Ubuntu tab name has no mention of Ubuntu. Even if the information is conveyed by the logo, consistency 
 such as "[Shell type][colon][tab name]" helps to parse the text especially when moving the mouse among the tabs.

**Comment by vadimkantorov** [comment]
Yes, I understand that PowerShell fails to provide a more specific prompt name. But it hurts the final user experience, especially when the user has many tabs.

The terminal is in position to do something about it, because it decides what's finally displayed. The PowerShell doesn't have the final say.

**Comment by DHowett-MSFT** [comment]
Terminal _isn't_ really in a position to do something about it: there's nothing it can detect about powershell if powershell doesn't tell it. It can't pull out a prompt line, for example, because we're not going to add heuristics to determine what a prompt line is (they're likely to be wrong). It can't pull out a working directory because it's not Terminal's job to crack its child process's process token and grovel through it (and this doesn't work for predominantly remote sessions). I'd rather consistently do less than inconsistently do more. Y'know?

**Comment by DHowett-MSFT** [comment]
I appreciate the feedback that we could put the originating profile's name in the tooltip if it differs from the active title. I'll pop that on the backlog.

**Comment by vadimkantorov** [comment]
> Terminal _isn't_ really in a position to do something about it: there's nothing it can detect about powershell if powershell doesn't tell it. It can't pull out a prompt line, for example, because we're not going to add heuristics to determine what a prompt line is (they're likely to be wrong). It can't pull out a working directory because it's not Terminal's job to crack its child process's process token and grovel through it (and this doesn't work for predominantly remote sessions). I'd rather consistently do less than inconsistently do more. Y'know?

I did not suggest pulling working directories out of processes (on the side note, I don't in general think working directories, user names, machine names  are useful in tab names and tab tooltips, I would rather all of them just read Ubuntu 18.04 / PowerShell). All I wanted to bring attention to is kindly asking to allocate to UI consistency a bit more priority, especially when Terminal is being designed to support many different shell types in one window.

I understand that hacks makes more maintenance in future etc. And hopefully configurability is a bit more practical when we have a UI configuration window.

**Comment by DHowett-MSFT** [comment]
That's fair. I appreciate that.

If you _do_ prefer the profile name and don't find the shell title useful, you should be able to suppress shell titles with the `suppressApplicationTitle` profile setting. You can also set an explicit tab title w/ `tabTitle`.

Thanks!
