### ISSUE TITLE
Can't switch tabs with topmost pixel in full-screen mode

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#4479]
In Chrome I can move mouse cursor to the top of the screen and still click on the tab (this is useful on laptops with track points like ThinkPads, it is much easier to move mouse to the top and then left-right than to top, then a few pixels down and then left-right). This is not the case in WT.

When I click on where the red dot is, nothing happens:

![image](https://user-images.githubusercontent.com/1041752/73864243-9bab7280-4841-11ea-8ed7-a4bb3d6d7f60.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2541for more discussion.

/dup #2541

**Comment by vadimkantorov** [comment]
That issue is about "padding". In that issue it is not clear if the complaint is about the visual or about behavior.

In this issue the point is about the tab switching behavior.

If that issue is considered in its own scope, it might be decided "won't fix" for aesthetic reasons. Here the complaint is different. For this reason, could you please keep this issue open? Or modify/add more context to that issue?

Thank you,
Vadim

**Comment by vadimkantorov** [comment]
Chrome also "pads" the tabs a bit, but the padded area is still functional:
![image](https://user-images.githubusercontent.com/1041752/73869049-e16c3900-4849-11ea-8b49-5219ac08f143.png)

**Comment by DHowett-MSFT** [comment]
We'll mention the hit targeting in 2541. Thanks.

**Comment by vadimkantorov** [comment]
Unfortunately, mouse pointer doesn't get preserved on the screenshot, and the topmost pixel row somehow doesn't get clearly preserved either. The screenshot shows maximized window.

**Comment by zadjii-msft** [comment]
the most recent incarnation of this tracked in #11309

**Comment by vadimkantorov** [comment]
@DHowett-MSFT  On Version: 1.18.2822.0 it somehow mostly fixed itself:

So I can now switch tabs by clicking on the topmost pixel.

But I still can't click via topmost pixel on "+" to open a new tab. This works in Chrome.

<img width="118" alt="image" src="https://github.com/microsoft/terminal/assets/1041752/9a229f31-084a-4b3c-897b-ff050a01b17d">

**Comment by vadimkantorov** [comment]
Same problem for clicking on <kbd>v</kbd>
