### ISSUE TITLE
Ctrl+H not detected properly

### ISSUE THREAD

**Issue by vincentfiestada** [microsoft/terminal#4487]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version: 0.8.10261.0

Other software:
NVIM v0.4.3
```
See [here](https://gist.github.com/vincentfiestada/0f7de76bde603373447ec3e5c20fca30) for the contents of `profile.json` and `init.vim`.

# Steps to reproduce

1. Open Neovim.
    - I have mapped <kbd>Ctrl</kbd><kbd>H</kbd> to switch to the left window
    - I have verified that <kbd>Ctrl</kbd><kbd>H</kbd> is not a keybinding in Windows Terminal's `profile.json`
2. Open the NERDTree file browser; or, open two windows in vertical split.
3. With the cursor in the rightmost window, in Normal mode, press <kbd>Ctrl</kbd><kbd>H</kbd> to switch to the leftmost window.

# Expected behavior

The cursor should move to the leftmost window.
Note that doing the same steps in `pwsh.exe` and `cmd.exe` in the old command-line, Neovim behaves as expected.

Neovim on `pwsh.exe` in the old command-line ✔️  
![Neovim on `pwsh.exe` in the old command-line](https://media.giphy.com/media/Tf4NUDY5pS9fbfibcP/giphy.gif)

Neovim on `cmd.exe` in the old command-line ✔️
![Neovim on `cmd.exe` in the old command-line](https://media.giphy.com/media/KfCHPGmN2Vh7eLgia0/giphy.gif)

# Actual behavior

The cursor only moves left one character. This should happen if I press _only_ the <kbd>H</kbd> key.

![Neovim on `pwsh.exe` in Windows Terminal](https://media.giphy.com/media/W5fOWlFlaBhHPaNAXE/giphy.gif)

The issue persists on `cmd.exe` in Windows Terminal.

**Comment by vincentfiestada** [comment]
I should also note that this issue did not exist before, so I suspect the new version of Windows Terminal introduced this bug.

**Comment by j4james** [comment]
This sounds like the same issue as #4397.

**Comment by vincentfiestada** [comment]
I'm not that familiar with the intricacies of how input sequences interpreted, but after reading #4397 and #3935 it seems this was a trade-off due to the requirement of supporting both native and WSL programs??

But I guess until #879 is fixed, I'll have to rebind those commands to other keys.

**Comment by DHowett-MSFT** [comment]
Thanks for finding the dupe. Sorry for the inconvenience.

**Comment by cristiandonosoc** [comment]
The issue this was pointed to says it was fixed, but I'm still seeing this issue on Windows Terminal Preview 1.9.1523.0, so I'm guessing not all sequences are covered?

I have this literal same issue. Show I open a new issue or re-opening this one is the correct way to go?
Thank you
