### ISSUE TITLE
When cmd.exe not exit correctly, the zombie process will get CPU High

### ISSUE THREAD

**Issue by doggy8088** [microsoft/terminal#4489]
# Environment

```none
PS C:\WINDOWS\system32> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

```
Windows Terminal (Preview)
Version: 0.8.10261.0
```

# Steps to reproduce

1. Open **Windows Terminal (Preview)**
2. Open multiple tabs with `cmd.exe`
3. Typing fast with any randam keywords and hit `Ctrl-C` many times, then enter `exit`.
4. If the tab get hang, you will see this:

    ![image](https://user-images.githubusercontent.com/88981/73958194-85d1a680-4942-11ea-98d2-e56cf833e9b9.png)

5. Then Hit the `X` to close the tab. If you close the last tab in Windows Terminal, the Windows Terminal will be closed.

6. Check the Task Manager. You will still see Windows Terminal and `cmd.exe` still on it and it will consime 1/3 of my CPU resources.

    ![image](https://user-images.githubusercontent.com/88981/73957852-fa581580-4941-11ea-8ce2-82dfc3c060b8.png)

# Expected behavior

I expected the process will close and not consuming any CPU resource.

# Actual behavior

This screenshot is from Process Explorer:

![image](https://user-images.githubusercontent.com/88981/73957708-ba912e00-4941-11ea-80b5-66b1b1d255a1.png)

**Comment by DHowett-MSFT** [comment]
Windows Terminal only displays the `process exited` message when the process actually exits. The instance of cmd that was running is no longer running. Can you use Process Explorer to find the "parent process" for the cmd instance that has high CPU?

**Comment by doggy8088** [comment]
@DHowett-MSFT I tried. It "had" a parent process before. When I close the Windows Terminal process, the `cmd.exe` process is been pull up to a parent process.

**Comment by DHowett-MSFT** [comment]
I cannot get this to happen on my machine. Is there anything else about your environment that you can think of?

**Comment by doggy8088** [comment]
@DHowett-MSFT I do have installed [clink](https://github.com/mridgers/clink) and injected into my `cmd.exe`.

**Comment by DHowett-MSFT** [comment]
What version of clink, and how are you launching and injecting it? I just tried 13 times with clink 1.0.0a1, and I cannot get cmd.exe to detach from terminal and hang while reporting that it was closed.

**Comment by doggy8088** [comment]
@DHowett-MSFT I'm using `Clink v0.4.9 [git:2fd2c2]`.

**Comment by DHowett-MSFT** [comment]
Can you share a process dump of the cmd that is misbehaving? I would love to see what it is doing, because even with v0.4.9 I cannot make this happen on my computer.

**Comment by doggy8088** [comment]
I couldn't reproduce this problem for days after upgrade to `0.9.433.0`.  So I think this problem might be solved.

**Comment by DHowett-MSFT** [comment]
Thanks for following up!
