### ISSUE TITLE
Terminal+Git bash+gulp: sometimes CTRL+C does not terminate process and the tab gets lost

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#4492]
# Environment

```none
Windows build number: 1909 18363.592
Windows Terminal version (if applicable): 0.8.10261.0

Any other software?
node: v12.13.1
gulp: CLI version 2.0.1, Local version 4.0.2
git version 2.24.1.windows.2
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

# Steps to reproduce
Press CTRL+C after starting `gulp` in the OWA codebase.

# Expected behavior
For the running process to stop and the shell to be available again.

# Actual behavior
**Sometimes** the terminal tab seems to stop responding after a CTRL+C and I have to kill it.
Unfortunately I don't have a consistent repro. It is very sporadic.

I'm entering the issue in case it rings a bell with someone else and if I find a consistent repro I'll update it.

**Comment by dyonng** [comment]
Also using Git Bash as my shell.

This sometimes happens to me regardless of using CTRL+Z or CTRL+C to end a process. It usually happens when I'm running a server/stay-alive process, like `webpack-dev-server`, for a long time.

```
Windows Version: 10.0.18362
Terminal Version: 0.9.433
Git Bash Version: 2.25.0

**Comment by DHowett-MSFT** [comment]
@fpintos any luck on a consistent repro? If you can get it into this state with v0.9, and can capture a process dump of `WindowsTerminal.exe`, I'd be very much appreciative.

Thanks!
