### ISSUE TITLE
Cosmetic issue - file path too long on WSL and it overlaps on to next line.

### ISSUE THREAD

**Issue by lew-d** [microsoft/terminal#45]
# This only happens when using ZSH

> version - Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

>When booting up WSL the prompt is overlapping on to the next line. This issue only seems to occur when using longer file paths (eg '/mnt/c/Users/Lewis').

* What's wrong / what should be happening instead:

>What should be happening is that the prompt and the path should be on the same line.

The right is what should be happening. https://imgur.com/a/ZeXi2

**Comment by zadjii-msft** [comment]
@hexx112 what's your `PS1` setting in your ~/.bashrc?

**Comment by hexx112** [comment]
@zadjii-msft Unfortunately, no. Screenshots I have seen display it on one line
