### ISSUE TITLE
Terminal is crashing if we drag a tab and try to reorder

### ISSUE THREAD

**Issue by upadhyayap** [microsoft/terminal#4501]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): preview

Any other software?
```

# Steps to reproduce

- Open Windows terminal with more than one tabs
- try reorder tabs by drag and drop

# Expected behavior

The tab which is getting dragged and dropped should be shifted to dropped position

# Actual behavior

Terminal is crashing.

**Comment by zadjii-msft** [comment]
@upadhyayap Are you running elevated / as Administrator? If so this'll be #3581

**Comment by upadhyayap** [comment]
yes i am running as elevated. I see this is being tracked #3581

**Comment by vchirikov** [comment]
@zadjii-msft can we disable drag&drop completely? this is very confusing and annoying.

**Comment by zadjii-msft** [comment]
As mentioned in #3581, our plan is to:

> detect when running as administrator and disable drag & drop activity.
