### ISSUE TITLE
ScreenInfoUiaProvider::GetVisibleRanges() returns an improper result

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4507]
# Summary
Our TermControlUiaProvider (aka ScreenInfoUiaProvider) returns a list of `UiaTextRange` for our visible ranges (one per row in the buffer).

The docs for `GetVisibleRanges` state we should only return one range.

# Technical Details
We only have one continuous span of text visible at a time (within a given Terminal Control).

The documentation for [GetVisibleRanges](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-itextprovider-getvisibleranges) states as follows:

>If the visible text consists of one contiguous span of text, the pRetVal array should contain a single text range that represents all of the visible text.
>
>
>ITextProvider::GetVisibleRanges should return a degenerate (empty) text range if no text is visible, if all text is scrolled out of view, or if the text-based control contains no text.

**Comment by DHowett-MSFT** [comment]
We'll scrub this in a discussion with @cinnamon-msft.
