### ISSUE TITLE
Wrong font variation for Chinese (Simplified)

### ISSUE THREAD

**Issue by skyanchor** [microsoft/terminal#4508]
# Environment

```none
Windows build number: 19041.21
Windows Terminal version (if applicable): 0.8.10261.0

Any other software? No.
```

# Steps to reproduce

When I open the app, the Chinese characters on the screen (or what I type) is in the wrong variation in zh-cn.

# Expected behavior
The Chinese characters (in zh-cn) should be like this. Please notice the highlighted strokes.
![image](https://user-images.githubusercontent.com/52092252/74076391-b0128980-4a52-11ea-8f82-7325489f6d71.png)

# Actual behavior
The default descriptions are shown like this. Please notice the highlighted strokes.
![image](https://user-images.githubusercontent.com/52092252/74076412-e05a2800-4a52-11ea-8add-6cc085c2a1e6.png)

Please notice that it is definitely not an issue for the use of a specific font, but a font-variation issue. Contents shown like that are in a font variation optimized for zh-hk or zh-tw, not optimized for zh-cn. 

This issue was not present in the first test build of Terminal. It was present in the second of third public beta till now.

**Comment by DHowett-MSFT** [comment]
Team, I've tagged v1.0 as this is a globalization concern.

@skyanchor, Thanks for the report and the info.

**Comment by skyline75489** [comment]
I noticed this a long time ago but didn’t realize it’s a font variant issue. Recently I came across a similar issue on Firefox which uses a Japanese variant of CJK font in zh-CN locale. Since there are several font variation in CJK environment, users from other regions may also be affected by this.

**Comment by Bwin4L** [comment]
Hello!
That's [Han Unification](https://en.wikipedia.org/wiki/Han_unification) at its best (worst)!

Developers usually tend to just go for setting the traditional Chinese fonts as default CJK font variant fallback nowadays when there's no language information in the content — see e.g. Chrome, or even Visual Studio Code which are both affected by this issue (maybe I should open an issue on the VSCode repo, see attached files).

This causes display issues for the rest of the world because, hey, maybe what I'm showing in my terminal as e.g. an English or French user is Japanese, maybe it's simplified Chinese, maybe it's traditional Chinese (slightly different use case here as EN/FR aren't CJK languages), and believe me it's really annoying because some of the ideogram variants are wildly different between languages (as you can see on the Wikipedia page linked above).

I hope the chosen solution lets us at least select what fallback language variation we want to use as a setting in the preferences (and maybe default to one of the CJK variants when the system locale matches one of them, e.g. simplified Chinese for zh-CN, Japanese for ja-JP).

**Comment by reli-msft** [comment]
`IDWriteFontFallback::MapCharacters` will take the locale information from the text source, so maybe it is incorrect here? Allowing user to configure the fallback sequence is always a workaround to this though.

**Comment by reli-msft** [comment]
A test case for this is character “遍”.
 ![](https://blogsimages.adobe.com/CCJKType/files/2018/10/locl-example.jpg)

**Comment by richardtsai** [comment]
https://github.com/microsoft/terminal/blob/f919a46caf4d492c5d8e5cb3aa58b68a52d77eb0/src/renderer/dx/DxRenderer.cpp#L1984-L1986

`_GetLocaleName()` retrieves the system's locale name, but `_ResolveFontFaceWithFallback()` would override `localeName` with the font's locale name. As we normally configure a font with latin alphabet only, and let the system fallback to a CJK font, the locale from the latin font would be used, which is normally en-us.

```diff
-        const auto face = _ResolveFontFaceWithFallback(fontName, weight, stretch, style, localeName);
+        std::wstring fontLocaleName = localeName;
+        const auto face = _ResolveFontFaceWithFallback(fontName, weight, stretch, style, fontLocaleName);
```
The patch above seems to resolve this issue:

![image](https://user-images.githubusercontent.com/1297550/76591589-c9b06080-652b-11ea-904a-f7dd6d178372.png)

**Comment by DHowett-MSFT** [comment]
Wow! Good catch. Mind submitting a pull request so we can review it? :)

**Comment by lonble** [comment]
I use the English version of Windows and set Chinese as my second language, as shown below. 

<img width="1168" height="1264" alt="Image" src="https://github.com/user-attachments/assets/aba8f826-07de-41d3-9ef7-aed66d6bb5df" />

The fonts are normal in Windows File Explorer, input method, Notepad, VS Code, and even chrome, but not in Windows Terminal.

File Explorer:

<img width="568" height="337" alt="Image" src="https://github.com/user-attachments/assets/fda834c3-966a-45b3-97b6-8539572d5540" />

input method:

<img width="1254" height="147" alt="Image" src="https://github.com/user-attachments/assets/71951623-5436-42d1-abd2-b8d16032f65b" />

Notepad:

<img width="688" height="299" alt="Image" src="https://github.com/user-attachments/assets/86472fc5-6af9-458d-add2-2a055e57979b" />

VS Code:

<img width="796" height="271" alt="Image" src="https://github.com/user-attachments/assets/ebf7347d-0508-4005-b877-7f0c4fe87990" />

chrome:

<img width="2058" height="278" alt="Image" src="https://github.com/user-attachments/assets/604bd0c8-bd23-4321-8816-024fc2af025e" />

**Windows Terminal, with wrong font:**

<img width="654" height="219" alt="Image" src="https://github.com/user-attachments/assets/9c16d283-64cd-4af4-808c-1a845092f4c4" />

**Comment by lhecker** [comment]
Can you please create a new issue for that?

**Comment by lonble** [comment]
> Can you please create a new issue for that?

New issue here <https://github.com/microsoft/terminal/issues/19194>
