### ISSUE TITLE
UIA Providers misrepresent box selections

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4509]
# Summary
Our TermControlUiaProvider (aka ScreenInfoUiaProvider) assumes that a retrieved selection is always a line selection.

# Technical Details
`ScreenInfoUiaProviderBase::GetSelection()` returns a `UiaTextRange` for the endpoints of the selection (after a brief inclusive/exclusive conversion). We need two modifications here:
1. `ScreenInfoUiaProviderBase` should check if the selection is a box selection or a line selection. And should create a different branch for each of those options.
2. `UiaTextRangeBase` needs...
  - [x] a constructor for a box selection UTR
  - [x] a flag to know if it is in this style
  - [x] a new bounding rect for a UTR of this style
  - [x] a modified way to retrieve text for this
  - [x] ~(?) modify `Select` to make a box selection?~ not needed. How selections are made is already abstracted to the selection code, not UIA providers

**Comment by carlos-zamora** [comment]
Closed the PR attempting to fix this. Ran into the following problem:
Closing this PR. This is the incorrect approach because of the following scenario:

TextBuffer:
```
     axxxx
   😀xxx😀
     xxxxx
   😀xxx😀
     xxxxb
```

Selecting from `a` to `b` in box selection should result in all of the `x` being selected, but the selection expanding to encompass the wide glyphs. The implementation in this PR does not account for the wide glyphs.


# Proposed Implementation
Create a `SelectionTextRange` class that implements the `UiaTextRange` class.
Make this heavily rely on `GetSelectionRects` to properly represent the selection.
`GetSelection` from `ScreenInfoUiaProviderBase` should just create this type of text range and abstract all of the difficult bits away. The `SelectionTextRange` constructor would just take the output from `GetSelectionRects`.

**Comment by DHowett-MSFT** [comment]
This has always been an issue and is task-level work; recategorized as a task.
