### ISSUE TITLE
Provide a list of requirements, dependencies and building instructions

### ISSUE THREAD

**Issue by oakkitten** [microsoft/Terminal#451]
Apparently building and running this project requires:

* Windows 10 1903+ (?)
* Visual Studio 2017 (and not 2019 (?))
* More than 14 GB of disk space for the dependencies
* Files located in very specific places
* Probably more things

None of which is obvious from the readme. Instead, the readme says,

> OpenConsole.sln may be built ... from the command-line using MSBuild.

which one can take to be implying that building this project takes a single run of of MSBuild, which I happen to have 16 copies of on my machine.

Please provide a full list of requirements, dependencies, and building instructions that a regular power user can follow.

P.S. Even after installing both VS 2017 and 2019, `tools\razzle` can't find my MsBuild. Surely there's a better way of finding it than by going through a few of possible locations?

**Comment by cr4shcod3** [comment]
In my case. MSBuild is located at C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319

**Comment by zadjii-msft** [comment]
For the record, #489 has a boatload of info on it. I'd direct conversation into that thread instead.
