### ISSUE TITLE
List of supported disabledProfileSources in schema 

### ISSUE THREAD

**Issue by chelnak** [microsoft/terminal#4513]
Is there a list of disabledProfileSources anywhere? I couldn't find anything in the profiles.json schema.

Googling around I found three supported entries:

```
    "disabledProfileSources": [
      "Windows.Terminal.Azure",
      "Windows.Terminal.PowershellCore",
      "Windows.Terminal.Wsl",
    ]
```

But would like to hide `cmd` and `Windows PowerShell`.

Cheers 👍

**Comment by DHowett-MSFT** [comment]
`cmd` and `Windows PowerShell` aren't dynamic profiles and aren't subject to the dynamic profile system -- we could use better docs here, but for now it will suffice to switch them to `hidden:true`. That's actually why we left the hidden property in the user settings there: so it was more discoverable.
