### ISSUE TITLE
How to change color schemes

### ISSUE THREAD

**Issue by cdmihai** [microsoft/terminal#4521]
I want to switch Terminal to a light color scheme (light background, dark letters). After a quick 2-3 minute inspection of the json settings it's still not clear how to do it. How does one do it? Ideally there would be a `currentColorScheme` setting which points to a symbolic name for the color scheme that I want.

**Comment by DHowett-MSFT** [comment]
Each profile has a `colorScheme`, though it may not be present if it's set to the default value. Much of this is documented in [Using JSON settings](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md), which is linked from the About dialog.
