### ISSUE TITLE
Add the ability to launch a new tab as an Administrator but without launching a whole second copy of the terminal

### ISSUE THREAD

**Issue by borland** [microsoft/terminal#4529]
# Description of the new feature/enhancement

I'm not entirely sure if this is possible given the limitations of the Windows elevation model, but what I would very much like is to be able to launch a new Tab within Terminal as an administrator.

(Actually what I'd really like is sudo, but windows is doggedly not going there and that's not within the remit of the Terminal team)

Anyway, something like this:

![image](https://user-images.githubusercontent.com/6362/74229140-a88b0300-4d26-11ea-84fc-738aa1c77989.png)

and the admin tabs would have a corresponding (Admin) and variation on the icon color or something to that effect

I would like to use this feature because I occasionally (once/twice per day) need to perform administrative commands. Having to open or find a seperate administrative entire terminal window is not great, it's hard to keep track of and unwieldy. Tabbed terminals are great, and it would be even greater to incorporate an Admin tab.

# Proposed technical implementation details (optional)

See above mockup

**Comment by j4james** [comment]
This has been requested before, but it can't be done. See issue https://github.com/microsoft/terminal/issues/1032#issuecomment-496308808.

**Comment by borland** [comment]
Oh awesome, sorry for raising the dupe

**Comment by gerardog** [comment]
FYI @borland: https://github.com/gerardog/gsudo

Then you can add a WT profile:

    {
      "name": "Elevated PowerShel",
      "commandline": "gsudo.exe PowerShell",
      "hidden": false
    },
