### ISSUE TITLE
Setting historySize=32767 causes WindowsTerminal to hang.

### ISSUE THREAD

**Issue by doubleyewdee** [microsoft/terminal#453]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  Microsoft Windows [Version 10.0.18885.1001]

* What you're doing and what's happening: Setting historySize to 32767 (0x7FFF) via profile.json settings. I tried 32766 and that also failed, but 32000 was fine. So something on the fringes there is busted.

* What's wrong / what should be happening instead: The console hangs and subsequent attempts to open it also cause hangs.

**Comment by zadjii-msft** [comment]
That makes sense. 

Currently I think we're using a `short` for the history size, and this is a carry-over from the conhost code. 

We should probably sanitize that input - if someone uses a value larger than `SHORT_MAX`, we should just clamp it when we create the buffer.
