### ISSUE TITLE
Changing Default Profile Does Not Work

### ISSUE THREAD

**Issue by tjquinn1** [microsoft/terminal#4530]
# Environment

Microsoft Windows NT 10.0.18363.0
Terminal Verison: 0.8.10261.0
 WSL1 with Ubuntu 18.04.3 LTS

# Steps to reproduce

I changed the default profile from power shell to Ubuntu in settings.json using the profiles guid.

# Expected behavior
 Ubuntu to be default profile.

# Actual behavior

The Terminal makes Ubuntu the default profile but instead of loading Ubuntu it loads powershell in the Ubuntu shell. I tried reverting the default back to powershell but it will not revert back. So even though the powershell is again the default in settings.json, it has kept loading the Ubuntu hybrid as the default. If I open WSL through powershell that does work and Ubuntu seems to work as expected then.

![terminalpic](https://user-images.githubusercontent.com/16781171/74246044-25739980-4ca1-11ea-9107-9541bcaa3dcf.png)

**Comment by zadjii-msft** [comment]
@tjquinn1 Could you share your `profiles.json` file?

**Comment by tjquinn1** [comment]
Sure Here you go 

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        },
        {
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl",
            "fontFace": "Ubuntu Mono derivative Powerline",
            "background": "#58b8ae",
            "selectionBackground": "#d25bd9"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}

**Comment by tjquinn1** [comment]
I see the error. I accidentally overwrote the guid of powershell.

**Comment by zadjii-msft** [comment]
@tjquinn1 thanks for following up!
