### ISSUE TITLE
[Menu] Shells sub-grouping

### ISSUE THREAD

**Issue by nunix** [microsoft/terminal#4535]
# Description of the new feature/enhancement

for some (crazy) fans of having several shells, the selection menu can become very long very fast (see picture below).

It might be nice to have a "sub-grouping" for the different shells, so the menu would remain more clean.
At first, it could even be the "discovered shells" that could all be in a sub-group, so we could customize them and bring them back to the main menu

today's example:
![image](https://user-images.githubusercontent.com/905874/74275501-46c19d80-4d14-11ea-9347-76a00bf89dd2.png)

# Proposed technical implementation details (optional)

The nearest solution that already exists, might be the browser favorites, with only 1 level deep to keep it simple.

The Corsair

**Comment by DHowett-MSFT** [comment]
_Wow_ have you ever got a lot of WSL distributions!

**Comment by nunix** [comment]
and I cleaned some out to avoid "shocking" 😭

**Comment by mdtauk** [comment]
It would be nice to have groups that have a flyout menu.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571

**Comment by nunix** [comment]
oh sorry for that, great it's already discussed, thanks a lot Mike 👍

**Comment by bkraul** [comment]
@DHowett-MSFT this doesn't only apply t multiple WSL distributions. It could be that we only have one WSL distribution but have a number of SSH connections to remote servers. Right now, using solutions like [cmder](https://cmder.net/), we have something like this:
![image](https://user-images.githubusercontent.com/14616851/83256843-cf0b6780-a178-11ea-9f39-c36d3cb68e40.png)

So yeah, it would definitely be great. I am liking Windows Terminal so far.
