### ISSUE TITLE
Characters stay present on terminal but disappear from command when using backspace

### ISSUE THREAD

**Issue by BenConstable9** [microsoft/terminal#4537]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): 0.8.10261.0
```

# Steps to reproduce

Hard to reproduce as only occasionally happens.

# Expected behavior

The characters should be deleted from the input command.

# Actual behavior

When backspacing after typing an input command, characters stay in the command input but do not seem to affect the command. Rogue characters (normally the first character of the previous command typed), will linger on the UI but do not appear to have any effect on a command typed afterwards.

**Comment by DHowett-MSFT** [comment]
This may have been fixed by #4403. Can you try to confirm when 0.9 comes out (tomorrowish?)
