### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Bonuspunkt** [microsoft/terminal#4540]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

1. Install via Store
2. Launch Window Terminal

# Expected behavior

Windows Terminal stays open

# Actual behavior

Crashes, Event Logs shows
```
Faulting application name: WindowsTerminal.exe, version: 0.8.2001.26001, time stamp: 0x5e2e5240
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x64b4
Faulting application start time: 0x01d5e1283661b6f5
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: bed3d691-c869-4e4c-bcab-39efe39783f6
Faulting package full name: Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

on a sidenode:
- Feedback Hub does not list Windows Terminal
- works fine on all my dev machines where VS2019 is installed

**Comment by DHowett-MSFT** [comment]
Hmm. And you've not customized Terminal at all in this installation?

**Comment by Bonuspunkt** [comment]
no, reinstall also didn't fix it

**Comment by Bonuspunkt** [comment]
fixed after rebooting 😅

**Comment by DHowett-MSFT** [comment]
I hate to hear that (since it means it's nondeterministic and based on global system state), but thanks for following up!

**Comment by wt29** [comment]
I had this problem after upgrading to W10 2004 - I wanted the WSL Linux container integration. My laptop is now 8 YO, still functions well but has an integrated Intel 3000 GPU and an Nvidia GT520M. Disabling the GT520 fixed the issue with terminal and other apps that use GPU acceleration. There are some comments that 2004 has problems with Nvidia drivers < 328. The Nvidia experience app wouldn't run on 2004 under the GT520 so I had to specify "run on the Intel Integrated" which allowed me to update the drivers. Terminal now runs well. Other option was disable the GT520 in the BIOS.

**Comment by maPer77** [comment]
> I had this problem after upgrading to W10 2004 - I wanted the WSL Linux container integration. My laptop is now 8 YO, still functions well but has an integrated Intel 3000 GPU and an Nvidia GT520M. Disabling the GT520 fixed the issue with terminal and other apps that use GPU acceleration. There are some comments that 2004 has problems with Nvidia drivers < 328. The Nvidia experience app wouldn't run on 2004 under the GT520 so I had to specify "run on the Intel Integrated" which allowed me to update the drivers. Terminal now runs well. Other option was disable the GT520 in the BIOS.

I have the same configuration and the same problem.

You have 2 options:
- On the panel nvidia force the use of integrated graphics for the windows terminal.

or

- In the windows terminal settings use: "experimental.rendering.software": true https://github.com/microsoft/terminal/issues/8286#issuecomment-729204294

![notepad_jBTWh0JQsn](https://user-images.githubusercontent.com/5252293/99722058-d90a8500-2a8e-11eb-9d27-2ebc28d567c9.png)

**Comment by rudironsonijr** [comment]
> I had this problem after upgrading to W10 2004 - I wanted the WSL Linux container integration. My laptop is now 8 YO, still functions well but has an integrated Intel 3000 GPU and an Nvidia GT520M. Disabling the GT520 fixed the issue with terminal and other apps that use GPU acceleration. There are some comments that 2004 has problems with Nvidia drivers < 328. The Nvidia experience app wouldn't run on 2004 under the GT520 so I had to specify "run on the Intel Integrated" which allowed me to update the drivers. Terminal now runs well. Other option was disable the GT520 in the BIOS.


---------------------------------------

Thank you SO MUCH! I even formatted my computer in order to use Terminal but the issue was with NVIDIA.
Just like Linus said... F*ck you NVIDIA! hahahah
Can't believe that my GPU driver is the culprit.
