### ISSUE TITLE
Inconsistent touch screen scrolling

### ISSUE THREAD

**Issue by jamestut** [microsoft/terminal#4542]
# Environment

```none
Windows build number: 10.0.18363.628
Windows Terminal version (if applicable): 543f5339d73ed49ccf3392627663c59cd5e51aec

Any other software?
```

# Steps to reproduce

Scroll the terminal viewport using touch screen.

# Expected behavior

Viewport should move consistently, line by line, and the scrolling should "follow the finger".

# Actual behavior

Scrolling is not consistent, and jellying/jumping. This is very apparent especially when scrolling the viewport up, where the line moves by 2 instead of 1. Also when scrolling quickly, the actual scrolling lags a little bit.

# Proposed Fix

Since this is caused by rounding errors, I modified the scrolling to operate on `_scrollBar`'s `Value` directly (which uses `double`) instead of calculating the previous offset from `GetScrollOffset` in `TermControl.cpp`. 

Tested this and I didn't found any glitches with this approach, and now the touch screen scrolling works as expected.

**Comment by jamestut** [comment]
I applied the same fix for the regular mouse wheel scrolling handling, and now precision touchpad scrolling works perfectly, just like the original built-in conhost.

By using non integral scrolling delta, precision touchpad's scrolling speed is also adjustable via the `rowsToScroll` setting.

Moderators, once you agree with my proposed changes, I will create a PR.

**Comment by zadjii-msft** [comment]
I mean, it's kinda hard to agree with the proposed changes without having the PR to look at 😄. I think it'd be easier to just look at the PR and discuss in the PR. That's my opinion at least - @DHowett-MSFT can feel free to override me here

**Comment by DHowett-MSFT** [comment]
I would love to evaluate a PR here. :smile:

**Comment by DHowett-MSFT** [comment]
Triaged into v1.x, but if it can land sooner that'd be neat.
