### ISSUE TITLE
w3m images (ranger) display in terminal

### ISSUE THREAD

**Issue by zyy1998** [microsoft/terminal#4544]
# Display images in terminal
I'm trying to use **_WSL_** to substitute some functions on windows, it performed well in some text-only functions. But I'm also want to use **_ranger_** ( a linux terminal file explorer ) to replace **_totalcommander_** which I often used or even **_windows file explorer_**, **_ranger_** satisfies my content in many occasions but for image preview.

**_w3m_** is a terminal web browser that could be used to display images in terminal, and it can also be used by **_ranger_**. However, **_w3m_** didn't work on this terminal.

There are many other terminals like **_iTerm2_**、**_urxvt_** and **_alacritty_** could display images. As a terminal under windows, I think it's more necessary to support this feature. 

# Proposed technical implementation details
I don't know how does w3m works, but I have noticed that the terminal could be changed the background pictures, so if you want to render some images, you can just change the specific area of the background of the terminal. Actually it's how **_urxvt_** handled it.

Of course, you don't have to support w3m, just do something that could display images correctly and the method could be called by other apps like **_ranger_**, that's all what I need. 

Thanks! ( And pardon for my poor English😁 )

You can find more information here: https://github.com/ranger/ranger/wiki/Image-Previews

**Comment by jantari** [comment]
Have you tried with [überzug](https://github.com/seebye/ueberzug) ? It's the recommended way to get image previews in ranger, w3m is always wonky even when you do get it to work on native Linux.

Also, if you just want something ranger-like on Windows you don't have to use WSL, you can just use [lf](https://github.com/gokcehan/lf) which runs on Windows (and Linux) natively and is much faster too. But it has no option to do image previews.

**Comment by akho** [comment]
w3m and überzug both rely on x11 to draw an image in a subwindow. It is highly unlikely that either of the two can be made to work in Terminal without also modifying the tools themselves.

Having some way to draw images in terminal would be very nice though. Kitty, for example, implements its own thing (icat), and integrates well with ranger. Would be lovely to have that in Terminal.

**Comment by j4james** [comment]
FYI, there are separate issues for Sixel (#448), and the other proprietary image formats (#5746).

**Comment by DHowett-MSFT** [comment]
Thanks for the request here. I'm going to make /dup #5746 the master issue for graphics-in-the-terminal and copy your comments over there.

At the end of the day, if other terminals are doing this _in a standards-compliant, secure and portable way_... we should _consider_ following suit.
