### ISSUE TITLE
Updating a distro from WSL1 to WSL2 seems to have broken terminal

### ISSUE THREAD

**Issue by billwert** [microsoft/terminal#4549]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19559.0 Microsoft Windows NT 10.0.19559.0

Windows Terminal version (if applicable):  0.9.362.0

Any other software?
```

# Steps to reproduce

1) install Ubuntu 18.04 in WSL1
2?) Update from retail to selfhost so you can have WSL2 (not entirely sure this matters, but it's a thing I did.)
3) Update the Ubuntu instance to WSL2
4) Start an Ubuntu bash window

note: starting wsl or bash directly works fine. It's only failing through terminal.

# Expected behavior

Terminal can start an Ubuntu bash window

# Actual behavior

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

[process exited with code 1]

**Comment by DHowett-MSFT** [comment]
This looks like microsoft.com/wsl#4860, per https://github.com/microsoft/WSL/issues/4860#issuecomment-583085326
