### ISSUE TITLE
Shift+Multi-Click Selection Expansion

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4557]
# Environment
```
Windows Terminal Version: 0.9.362.0
```

# Steps to reproduce
1. Single Click
![image](https://user-images.githubusercontent.com/11050425/74386849-dfefc300-4dab-11ea-933a-ea4d6caf6013.png)

2. Hold Shift and Double-Click an unselected region

# Expected behavior
![image](https://user-images.githubusercontent.com/11050425/74386900-04e43600-4dac-11ea-9d04-14890e819469.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/11050425/74386893-fdbd2800-4dab-11ea-9444-21f8585c71a0.png)

**Comment by DHowett-MSFT** [comment]
Triaged into 1.x, assigned @carlos-zamora since he's working in this area and pretty convicted about its correctness. :smile:
