### ISSUE TITLE
Hazardous key repeats across tabs

### ISSUE THREAD

**Issue by gitfool** [microsoft/terminal#4568]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

- Open multiple tabs to Linux shells, either WSL or ssh to Linux remotes
- Press and hold down `ctrl+d` to close the currently active shell

# Expected behavior

- Only the active shell / tab should close

# Actual behavior

- All shells / tabs close in quick succession

Of course it might be unreasonable for me to _expect_ the behavior I describe above, but I've been bitten a few times already where just pressing what I thought was a normal `ctrl+d` key sequence must've lingered a fraction too long, thereby "repeated" and accidentally closed another shell / tab I didn't intend to.

**Comment by DHowett-MSFT** [comment]
Interesting. I'm not sure how we comport this with "I want my input to instantly and immediately go to the active terminal." _hmm_

**Comment by gitfool** [comment]
Understood. I resisted logging an issue for a while, but it recently happened while I was mid "deploy" in another shell / tab, which needless to say was not good. 😱

**Comment by DHowett-MSFT** [comment]
Tentatively, I'm going to close this one- I appreciate that it's bitten you, but we're optimizing for input fidelity and time-to-response, and this may just have to be fallout for that. Terminal will -- or, should! -- respect your OS-wide key repeat delay. I know that's not an amazing way to fix this, but I can't find any prior art on suppressing control characters for something like this.
