### ISSUE TITLE
Terminal app crashes when the last tab is closed

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#457]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18890.1000

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Build & run the new Windows Terminal, then set alwaysShowTabs=true in the profiles.json file.
Restart Windows Terminal and try to close the last (only) tab

* What's wrong / what should be happening instead:
the whole app just crashes
What should happen: the app closes elegantly, or close the current tab and then open a new tab.

**Comment by driver1998** [comment]
It seems that you can't close the last tab with the X button or Ctrl-W, but it crashes when you try to close it with the middle mouse button.

**Comment by Oxyenyos** [comment]
Same happens with me

**Comment by zadjii-msft** [comment]
This is a good bug :)

@carlos-zamora I think you did the middle-click close thing

**Comment by DHowett-MSFT** [comment]
This is also the cause of a crash when `closeOnExit` is true and you exit the last shell.

**Comment by xa0082249956** [comment]
It seems to have been fixed.

**Comment by zadjii-msft** [comment]
I can't get this to repro anymore either. Looks like it must have been resolved at some point recently.

**Comment by hassieswift621** [comment]
This issue is occurring again using the version from the Microsoft Store.
Windows version: 18362.175
Terminal version: 0.2.1715.0 (Microsoft Store)

**Comment by StefPlue** [comment]
I have to confirm this, the version crashes with me as well.

**Comment by geocine** [comment]
I still encounter this issue
```
Windows version: Windows 10 Pro 1903
Windows Build: 18362.267
Terminal version: 0.3.2171.0
```

**Comment by zadjii-msft** [comment]
@DHowett-MSFT wasn't there something about XamlApplication needing to get cleaned up correctly? Maybe #1380? Is that being worked on by the XamlApplication folks?

**Comment by WilliamVenner** [comment]
I'm getting this too.
It seems to only happen when you close the last tab and if it's a PowerShell window.
Sometimes it will freeze and never recover, sometimes it will freeze momentarily and then work again.

```
Microsoft Windows [Version 10.0.18362.295]
```

**Comment by dexterslaboratory** [comment]
Am getting the same error now. on ubuntu 18.04.

**Comment by wengm** [comment]
Still have this problem with version  1.8.1521.0

**Comment by carlos-zamora** [comment]
> Still have this problem with version 1.8.1521.0

Hmm. Latest thing I could find that may be relevant is PR #10549, but I'm not sure if that exactly matches.

**Comment by cjacobsatnwea** [comment]
I deal w/ this all the time. But I figure like MS Teams "it works good enough for them" so that's that.
I still have line breaks when copying lines that are on multiple lines. like, really? copy the presented display instead of what was actually sent to display? broken methodology.
