### ISSUE TITLE
Hang when using Powershell Core 6.2.3

### ISSUE THREAD

**Issue by ryzngard** [microsoft/terminal#4574]
# Environment

```none
[Environment]::OSVersion


Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19564.0 Microsoft Windows NT 10.0.19564.0


Windows Terminal version (if applicable):  0.8.10261.0

Any other software?  powershell core 6.2.3
```

# Steps to reproduce

1. Have long running command or process in powershell core
2. Stop using ctrl+c 
3. Get message `[process exited with code 3221225786]` 

# Expected behavior

Process exits and returns back to powershell

# Actual behavior

Message stays on screen. Terminal does not return to being usable. 

# Other Notes

Does not reproduce with cmd or system installed powershell with version info below. System cmd host does not reproduce running powershell core. 

```none
>get-host


Name             : ConsoleHost
Version          : 5.1.19564.1000
InstanceId       : f018dc07-d319-427e-8928-6286b18585fa
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by DHowett-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/11314
