### ISSUE TITLE
Azure Cloud Shell Could not connect to Azure behind Corp Proxy

### ISSUE THREAD

**Issue by Ugenx** [microsoft/terminal#4575]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): v0.9.433.0

Any other software?
```

# Steps to reproduce

Add a new "Azure Cloud Shell" tab to your terminal instance.

# Expected behavior

A prompt should appear asking to authenticate with Azure.

# Actual behavior

The message "Could not connect to Azure. You may not have internet or the server might be down." appears immediately in the new tab. Fiddler only shows a single outgoing SSL initiation request to login.microsoftonline.com with a 200 response and no followup communication. 

I recently had to update the cacert bundle for the azure cli located in C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem to include our corp proxy certificate which restored its functionality. Is there something similar here or should the terminal be using the windows store?

**Comment by DHowett-MSFT** [comment]
Terminal should be using the Windows certificate store; is your corp proxy cert part of the Trusted Roots (at either User or System level?)

I believe the HTTP library we're using _does_ use the WinHTTP APIs.

**Comment by Ugenx** [comment]
My corp cert is definitely in both user and machine Trusted Root stores (confirmed just now). Does cloud shell function when running from source? Perhaps I could get some additional context on the connection error that way?

**Comment by Ugenx** [comment]
Pulled source to attempt debugging my specific version (v0.9.433.0), followed the instructions in the readme to restore git submodules via `git submodule update --init --recursive`, opened OpenConsole.sln in VS2019 Community V16.4.4, installed the required desktop development components, re-opened the solution and when right-clicking on CascadiaPackage -> Properties I am met with the error: 

"An error occurred trying to load the project properties window.  Close the window and try again.
The project configuration "Debug|x86" was not found in the project manifest."

Same problem in master branch. Tried searching issues for an existing bug report of this scenario and found nothing. Should I open one or am I missing something obvious here?

**Comment by TpSr52** [comment]
@Ugenx I just bumped into it also. I changed the platform in the top menu from x86 to x64 and then I successfully opened the "CascadiaPackage" properties. You should try it also.

It's happening because the x86 platform isn't defined in the project configuration and I think the main reason is that the "CascadiaPackage" debug project configuration for the x86 platform isn't configured deployable.
