### ISSUE TITLE
Confirm or Prevent Last Tab Close

### ISSUE THREAD

**Issue by psylenced** [microsoft/terminal#4579]
# Description of the new feature/enhancement

Sometimes when completing a session with multiple tabs open, a user may want to close everything but still keep a tab open.

There are two possible alternatives (when the option is true):

1) When closing last tab, prevent it from closing.

2) When closing last tab, present a confirm dialog.

When the option is false/default - last tab closes app as per current behaviour.

# Proposed technical implementation details (optional)

Add `confirmCloseLastTab` or `preventCloseLastTab` to profile.json

**Comment by DHowett-MSFT** [comment]
Thanks for the request.
Would this happen when the user closes almost all of the tabs, and then manually closes the last one? Would it happen when they click the `[x]` or press <kbd>Alt+F4</kbd>.. which would close all the tabs except for the last one?

Right now, the user must explicitly agree to close _all_ tabs, or manually close the final tab themselves (because there's no other way to close tabs)... so I am a little confused :smile:

**Comment by electronic-dk** [comment]
What about an option for not closing the window when the last tab is closed? Same as Firefox's "closeWindowWithLastTab"?

Offtop: I've sent a similar feature request to MS Edge's team.

**Comment by psylenced** [comment]
> Thanks for the request.

As mentioned by @electronic-dk above, I was picturing this as similar to how browsers handle the process.

It usually takes effect from keyboard shortcuts to close tabs (Ctrl-W or similar). If you hold the shortcut down (or press the shortcuts in succession) you'll end up with an empty window or a default tab rather than the application closing.

It's basically a process to say I still want to do something, but I want to start fresh.

**Comment by zadjii-msft** [comment]
Hey this is also related to #2976, I'm commenting here to make sure I don't lose that issue again

**Comment by stela2502** [comment]
I am using the terminal app together with the WLS and R. 

If I am in a similar situation using Ubuntu the terminal asks if I close a tab that contains a running process. If I have a resting tab with just the command prompt waiting for some input I can close the tab without any questions, but if I have an R or ssh session running I get the confirmation dialogue.

I think this would actually be the best way to make everybody kind of happy - right?

**Comment by electronic-dk** [comment]
@stela2502 while I think your suggestion is pretty useful (there might be a ticket for it actually, but I'm not sure), I think what OP meant was: "Avoid closing the entire terminal window when the last tab of the said window is closed".

**Comment by stela2502** [comment]
You are absolutely right, but from a usability point of view I would honestly just re-open an anyhow empty (all tabs are closed) terminal. The other functionality is really a pain in the ass if it is missing.

**Comment by DHowett** [comment]
/dup #6276 because it has more information/is a little clearer :)
