### ISSUE TITLE
In PowerShell Core, Terminal lost response after pressing Ctrl+C

### ISSUE THREAD

**Issue by chunliu** [microsoft/terminal#4580]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.9.433.0

PowerShell Core 6.2.4 installed with `dotnet tool install --global PowerShell`
```

# Steps to reproduce

1. In Windows Terminal, open a tab for PowerShell Core. 
2. Tap `help`. It shows the help info and "-- More --" at the bottom. 
3. Press Ctrl+C to terminate help command. 
4. The Terminal shows a message "[process exited with code 3221225786]" and stop responding. 

# Expected behavior

The help command should be terminated and the cursor should return to command prompt. 
The same issue doesn't happen with PowerShell. 

# Actual behavior

The Terminal shows a message "[process exited with code 3221225786]" and stop responding.

**Comment by DHowett-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/11314
