### ISSUE TITLE
[console]::CursorVisible acting funny in v0.9 (Powershell) with custom prompt

### ISSUE THREAD

**Issue by OtterKring** [microsoft/terminal#4582]
# Environment

```none

Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): 0.9.433.0

Any other software?
```

# Steps to reproduce

1) run a tab with PowerShell 5.1 or 7rc-2

2) use this prompt function in your profile: 
[Github: OtterKring's TimeMeasuringPrompt](https://github.com/OtterKring/PS_TimeMeasuringPrompt)
It will add the runtime of the previous command at the very right of the cmdline.

3) run `[console]::CursorVisible = $false`
> cursor does not disappear (which it did not do either in previous versions of WT) but stays at the end of the line after the time string written in the custom prompt function.

4) run `[console]::CursorVisible =$true`
> cursor is back to normal

# Expected behavior

The command `[console]::CursorVisible = $false` should hide the cursor. Compare functionality of standard Powershell consoles.

# Actual behavior

Cursor does not vanish but stays after the last character written by the custom prompt function.

**Comment by DHowett-MSFT** [comment]
Funny enough, this is the same as /dup #3093

**Comment by DHowett-MSFT** [comment]
(Conhost thinks the terminal is respecting the cursor position, so it doesn't update its position as readily. It thinks it cannot be seen. :smile:)

**Comment by OtterKring** [comment]
Lol!
________________________________
