### ISSUE TITLE
Dragging tabs when run as admin crashes Windows Terminal

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#4583]
# Environment

```none
Windows build number: 10.0.19564.1000
Windows Terminal version (if applicable): 0.9.433.0


Any other software?
```

# Steps to reproduce

Run Windows Terminal as administrator.
Drag the tabs around and try to reorder them.

# Expected behavior
Be able to reorder the tabs.

# Actual behavior
The app crashes.

**Comment by electronic-dk** [comment]
Dupe of https://github.com/microsoft/terminal/issues/3581

**Comment by DHowett-MSFT** [comment]
Indeed! Thanks. /dup #3581
