### ISSUE TITLE
Option to run on current working directory by default when run via wt alias

### ISSUE THREAD

**Issue by MahdiGhiasi** [microsoft/terminal#4584]
# Description of the new feature/enhancement

I regularly open terminals from File Explorer by typing `cmd` or `bash` or `powershell` into the address bar of the File Explorer and pressing enter. This opens a new shell window in the current directory.

As of the 0.9 release, I can do the same with Windows Terminal by typing `wt -d .` into the address bar and pressing enter, but that's long and not pretty. I'd rather type just `wt` and have Windows Terminal opened in that directory.

# Proposed technical implementation details (optional)

An optional key inside settings that when enabled, causes `wt` command to behave the same as `wt -d .` (run the new terminal in the current working directory, instead of opening a terminal in the user's home directory)

**Comment by DHowett-MSFT** [comment]
more info in https://github.com/microsoft/terminal/issues/4581#issuecomment-586143658
