### ISSUE TITLE
DesktopWindowXamlSource is not responding.

### ISSUE THREAD

**Issue by m13kj** [microsoft/terminal#4586]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

Open Windows Terminal (Preview) using any method: wt.exe, Windows Terminal (Preview) app and etc

# Expected behavior

The window opens normally. You can use terminal.

# Actual behavior

The terminal icon with "DesktopWindowXamlSource" title shows app in the task bar. 
There are three processes in the task manager (from Windows Terminal (Preview) process): "Microsoft Windows Subsystem Configuration Tool", "Microsoft Windows Subsystem Launcher" and "DesktopWindowXamlSource" (this one is not responding)
Also, we you hover over the terminal icon in task bar, the transparent window shows up.

**Comment by m13kj** [comment]
Don't know what have just happened, but the terminal now is warking fine...

**Comment by DHowett-MSFT** [comment]
Thanks for the info. /dup #3537, but we still don't know what's causing this. Perhaps #3987?
