### ISSUE TITLE
IME UI does not follow the cursor in Windows Terminal

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#459]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18890.1000

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Build & run the new Windows Terminal, and type something using IME (I am using Microsoft Pinyin IME)

* What's wrong / what should be happening instead:
The IME UI appears in the upper left corner of the screen, not following the current cursor.
![TIM截图20190507122302](https://user-images.githubusercontent.com/22699485/57271693-f6e9e200-70c2-11e9-8bf8-1247209846b5.png)

**Comment by zadjii-msft** [comment]
This is something we're working on currently!

**Comment by DHowett-MSFT** [comment]
@philnach's so kindly volunteered to look at it. I may even assign it to him! :smile:

**Comment by philnach** [comment]
@driver1998, thanks! @DHowett-MSFT, send it my way.

**Comment by davidwin** [comment]
So this is the same issue that makes the IME UI with a green arrow appear when opening the emoji panel? In #1557 I wasn't expecting that UI at all.

**Comment by DHowett-MSFT** [comment]
It sure is! The toolbar with the green arrow is actually a fallback UI for when the application doesn't explicitly say "Here's an input handler!"
