### ISSUE TITLE
Option to include outside border

### ISSUE THREAD

**Issue by d3x0r** [microsoft/terminal#4593]
# Description of the new feature/enhancement

The latest Windows minimalist view frames makes multiple command windows, stacked on top of each other hard to distinguish. 
I notice that this renders a frame line between frames, I would just like the option to draw that frame line inside the terminal always.

![console overlap issue](https://user-images.githubusercontent.com/1909610/74562636-1bab9980-4f20-11ea-8dcd-a6bfe9d85faa.png)

I don't really have an issue with all other windows having a transparent border that is grabbable to resize; but command prompts, since they now go edge-to-edge are a bit of an issue...

Depending on the console application (running FAR which has graphic frames itself for instance) makes it not be such an issue... but then many editors don't frame left and right...

![console overlap issue2](https://user-images.githubusercontent.com/1909610/74563028-b73d0a00-4f20-11ea-976d-ba73e0a85041.png)

# Proposed technical implementation details (optional)

I saw a demo of a command to split a window, which results in 3 consoles in a single window, and they have a nice border to separate them internally; it would be nice if this same border could be applied to the outside of the whole console window (optionally; maybe with a default on? to go back to the old behavior with windows that had distinct borders builtin?)

![terminal-command-args1](https://user-images.githubusercontent.com/1909610/74563219-26b2f980-4f21-11ea-81eb-bcd8107918b9.gif)

I saw #1375 and thought of adding this as a comment there.

**Comment by Ezroosp** [comment]
Poderia explicar como personalizar a aba do Terminal Windows? Gostaria que ficasse no mesmo tema de cor  da area de trabalho do windows.

**Comment by DHowett-MSFT** [comment]
We hear your feedback here -- but we're trying to fit in with the visual design of other terminals and other Windows applications, which don't have chonky borders.

If you enable the Personalization option "Show my accent color in .. title bars and window borders", you get a significantly better experience:

![image](https://user-images.githubusercontent.com/14316954/75079147-a2321f00-54bc-11ea-954b-5dd47fa4eb81.png)

This option is just like defaulting borders to on for the whole window.

In addition, it looks like this is a request against the standard windows console host, which we're not actively investing in.

**Comment by d3x0r** [comment]
I have accent color on.  And the experience is no different.  
Oh I see, the focused window is separate, doesn't help with multiple windows in the background running things.

**Comment by DHowett-MSFT** [comment]
Fair enough. We've got a lively discussion over in #1375 about where we can take the UI :smile:
