### ISSUE TITLE
Split screen fails to resize

### ISSUE THREAD

**Issue by TotallyInformation** [microsoft/terminal#4597]
# Environment

Platform | ServicePack | Version |     VersionString
--------|-----------|-------|-------------
 Win32NT |  | 10.0.18363.0 | Microsoft Windows NT 10.0.18363.0

Microsoft Surface Book 2, i7, 16GB RAM.

# Steps to reproduce

Open cmd.exe, issue `wt -p "WSL (Home1 Remote)" ; split-pane -p "WSL (Home1 Remote)"`

Where "WSL (Home1 Remote)" is a profile that opens WSL and issues an SSH connection to a remote Debian Buster server.

Or, open any other profile or simply `wt ; split-pane` which opens two PowerShell v6 panes.

It is not possible to drag the split left or right (nor up/down if starting 3 or more panes).

# Expected behavior

Be able to resize the internal boundaries of the panes.

# Actual behavior

The panes cannot be resized.

This generally makes the panes of little to no use since it is often the case that at least one of the panes is too narrow to be useful.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #992 for more discussion.

/dup #992

Right now, panes can't be resized with the mouse, however, you can resize them with keybindings. See #1207, and the default keybindings:
https://github.com/microsoft/terminal/blob/941a44a46491e1a018419eb24c9d92d3b2640e55/src/cascadia/TerminalApp/defaults.json#L234-L237
