### ISSUE TITLE
Pass commands to new wt instance. Is this already supported?

### ISSUE THREAD

**Issue by gregdegruy** [microsoft/terminal#4598]
# Description of the new feature/enhancement

Like how I can open a new command prompt with a command arg passed `start cmd.exe /k echo Hello, World`.

This does not work using Windows Terminal preview `start C:\Users\me\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt /k Hello, World`

# Proposed technical implementation details (optional)

Implement this using `cmd.exe` like syntax.
`start C:\Users\me\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt /k Hello, World`.

or even better `start wt /k Hello, World`.

**Comment by DHowett-MSFT** [comment]
You can do `wt cmd /k command` if you want. Check out our docs folder for UsingCommandLineArgs.

**Comment by gregdegruy** [comment]
Got it working thanks! I used this [blog](https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-9-release/)

![terminal-command-args](https://user-images.githubusercontent.com/8151045/74591711-0f324a00-4fcf-11ea-8852-4b514d38f727.gif)

**Comment by gregdegruy** [comment]
@DHowett-MSFT is it possible to pass args to each split pane?

**Comment by DHowett-MSFT** [comment]
Yes.

`wt cmd /k cd \ ; split-pane -H cmd /k dir ; split-pane powershell -noexit -c echo hi`
