### ISSUE TITLE
Dragging paths to WSL session should be converted to a WSL path

### ISSUE THREAD

**Issue by viniciusjarina** [microsoft/terminal#4599]
Dragging a folder or a file to the terminal on a WSL session should convert the path to to a WSL path.
eg:

Dragging `C:\Users\vinja` -> `/mnt/c/Users/vinja`
Dragging `\\wsl$\Ubuntu\home\vinja\local` -> `/home/vinja/local/` 

This way you could drag files/folders from the explorer and easily use on WSL 
![wsl_drop](https://user-images.githubusercontent.com/926868/74579894-3d724400-4f53-11ea-8a31-d66b9c439d91.gif)

**Comment by DHowett-MSFT** [comment]
Hey @viniciusjarina! Thanks for the request. This is, largely, a /dup of #1772. I'll redirect discussion over there, if you don't mind!

**Comment by DHowett-MSFT** [comment]
(even though that one is paste and this one is drag/drop: they'd be unified, of course)
