### ISSUE TITLE
Exiting a console doesn't close the tab or window

### ISSUE THREAD

**Issue by ObsidianMinor** [microsoft/Terminal#460]
* Windows build number: 10.0.18362.30

* What's happening: Exiting a console via an `exit` command doesn't close the tab or window. Instead the tab or window just hangs until you manually close it.
![image](https://user-images.githubusercontent.com/10121870/57272089-c02ab200-7057-11e9-99dd-14eaddb2d4fa.png)

* What should be happening: The tab or window should close upon exit

**Comment by JBanks** [comment]
For tabs, make sure that you have `"closeOnExit": true,` as a setting in the particular profile.  
This only works if you have more than one tab open.

**Comment by Flipp3rrr** [comment]
In my opinion `"closeOnExit": true` should be turned on by default. This behaviour is a little bit weird.

**Comment by bef178** [comment]
And ctrl-w closes the tab currently

**Comment by zadjii-msft** [comment]
Yea, closeOnExit should probably default to true. *This would be a fairly good starter issue if someone wanted to make a PR :)*

Closing the terminal when the last tab is closed is also something we should be doing, but that might be a bit trickier of a PR. I think we're manually suppressing the close action on the last tab currently, but that could be replaced with just closing the app (somehow).

**Comment by JBanks** [comment]
> Closing the terminal when the last tab is closed is also something we should be doing, but that might be a bit trickier of a PR. I think we're manually suppressing the close action on the last tab currently, but that could be replaced with just closing the app (somehow).

@zadjii-msft,  should we open a separate issue for this, or re-open this one until the second piece is resolved?

**Comment by zadjii-msft** [comment]
A second issue is probably best. Filed #627 to track it :)
