### ISSUE TITLE
Drop Down for profiles and setting isn't working and the minimize and maximize buttons on the pane doesn't work.

### ISSUE THREAD

**Issue by M0hammedImran** [microsoft/terminal#4600]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Thanks for the bug report! This is actually already being tracked by another issue on our repo - please refer to #3325 for more discussion.

/dup #3325
