### ISSUE TITLE
Quickly dragging a tab into the terminal area that has text selected modifies that selection

### ISSUE THREAD

**Issue by greg904** [microsoft/terminal#4603]
# Environment

```none
Windows build number:  10.0.18362.0
Windows Terminal version (if applicable): master (941a44a46491e1a018419eb24c9d92d3b2640e55)

Any other software?
```

# Steps to reproduce

1. Make a selection.
2. Quickly drag a tab onto the terminal area.

# Expected behavior

The selection is not modified.

# Actual behavior

The selection is modified.

**Comment by DHowett-MSFT** [comment]
Marking this as a v1.0 P3 polish issue; we will discuss it during the next v1 scrub.
