### ISSUE TITLE
Lines when use console file managers like Far or mc

### ISSUE THREAD

**Issue by sHAsHiLx** [microsoft/terminal#4605]
# Environment

```none
Windows build number: Version 10.0.18363.657
Windows Terminal version (if applicable): 0.9 but this was from the start

Any other software?
```

# Steps to reproduce

Just tried to run these programs with the default config

# Expected behavior

These ugly lines must absent

# Actual behavior

This https://paste.pics/6d2d34cdcc748cbabdcbf2cf2f6aa8e5

**Comment by j4james** [comment]
Duplicate of #3626.
