### ISSUE TITLE
Hidden taskbar not showing in fullscreen mode

### ISSUE THREAD

**Issue by fuadnafiz98** [microsoft/terminal#4606]
The hidden taskbar is not showing when the terminal is in fullscreen mode.

**Comment by billkindle** [comment]
Can confirm. 

F11 >
![image](https://user-images.githubusercontent.com/7315466/74595102-b7fe9a80-500b-11ea-852a-34001976401e.png)

Normal view >
![image](https://user-images.githubusercontent.com/7315466/74595106-c2209900-500b-11ea-8182-c053c5fe6efa.png)

**Comment by zadjii-msft** [comment]
This sounds a lot like "Cannot access taskbar when terminal is maximized #1438" but I'll leave this open to make sure that fullscreen mode is fixed _in addition_ to maximized.

**Comment by fuadnafiz98** [comment]
Yes, [#1438](https://github.com/microsoft/terminal/issues/1438) is the same bug as mine.

**Comment by DHowett-MSFT** [comment]
I think we need to fix them at the same time w/ the same fix. /dup #1438
