### ISSUE TITLE
Inconsistent behavior with Start-Transcript / capturing output

### ISSUE THREAD

**Issue by clintoncampbell** [microsoft/terminal#4609]
When I record a Powershell transcript in Terminal with `start-transcript` and run  certain .com or .exe based application, the output is not recorded properly in the file. If I run the same commands in the standard Powershell console or elevate privileges in Terminal, the output is captured.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.8.10261.0

Any other software?
```

# Steps to reproduce

This can be tested by running the following sequence of commands in each scenario, i.e., Terminal, PS Console, Administrator Terminal. The non-admin Terminal session will fail:

```
start-transcript test
ipconfig /all
stop-transcript test
```

Workarounds include elevating the session as an Administrator or piping output, e.g., `ipconfig /all | out-default`. Behavior does not appear to impact cmdlets, such as `get-netipaddress`. I have heard reports from my students that in some cases, output for ping.exe is omitted, but I could not replicate that case.
# Expected behavior

The output of ipconfig /all should be saved to the file and shown on the screen. 

# Actual behavior

Output is shown on the screen, but not in the file. Example transcript below:

```
PS C:\Users\clementine> cat .\terminal
Windows PowerShell transcript start
Start time: 20200215142057
Username: DESKTOP-6NDRMH1\clementine
RunAs User: DESKTOP-6NDRMH1\clementine
Configuration Name:
Machine: DESKTOP-6NDRMH1 (Microsoft Windows NT 10.0.18363.0)
Host Application: powershell.exe
Process ID: 12284
PSVersion: 5.1.18362.145
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.145
BuildVersion: 10.0.18362.145
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is terminal
PS C:\Users\clementine> ipconfig /all

PS C:\Users\clementine> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20200215142104
**********************
```

**Comment by DHowett-MSFT** [comment]
This appears to be an issue in PowerShell; I cannot reproduce it with powershell 6 or 7, but it does repro in powershell 5. I know they've evolved their use of the console APIs over the years, but I can't exactly pinpoint how they would have fixed or broken this for WT specifically.

As a test, I used the inbox console host, _set the console buffer height to the window height_, and ran a transcript. Saw the same behavior as in Terminal.

This is likely a similar class of issues that PSReadline has been tackling: they attempt to address an area of the screen that's off the top now, and they _can't_ do so. They had to fix this for Linux/macOS so they ended up fixing it for Windows too.
