### ISSUE TITLE
[wt.exe] -H and -V parameters shouldn't be case-sensitive

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#4611]
# Environment

```none
Microsoft Windows [Version 10.0.18363.535]
```

# Steps to reproduce
```
PS C:\> wt `; split-pane -h cmd.exe
PS C:\> wt `; split-pane -v cmd.exe
```
# Expected behavior

Commands run without a problem when I specify -h and/or -v.

# Actual behavior

Help dialog pops-up complaining about the wrong syntax. Btw, help dialog is not the same for -v and -h.

**Comment by Jaykul** [comment]
I get that we want `-h(elp)` and `-H(orizontal)` but I think you need to settle for `-?` or `--help` without `-h` because not only is this confusing to those of us who've been using Windows for years, but it's also backward to tmux's `-h` for horizontal ...

**Comment by DHowett-MSFT** [comment]
Please use /dup #4601 as the master discussion issue for things like this. Thanks!
