### ISSUE TITLE
[wt.exe] Help windows are inconsistent

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#4612]
# Environment

```none
Microsoft Windows [Version 10.0.18363.535]
```

# Steps to reproduce
```
# at the moment, this is considered a wrong syntax, so a help window pops up
# and help messages are not the same
PS C:\> wt `; split-pane -h cmd.exe
PS C:\> wt `; split-pane -v cmd.exe

# calling help gives us the third kind of a help message
--help, -h, -?, and /?
```
# Expected behavior

All help windows are the same.

# Actual behavior

Help windows contain different help messages dependent of the way how help is triggered.

**Comment by DHowett-MSFT** [comment]
For at least the first and second, you’re seeing “split pane with an unknown argument,” “split pane help” (`-h` is help, so it can’t be repurposed for `-H`), and “wt global help”.

This seems consistent to me; any ideas how we can be better here?

**Comment by alexandair** [comment]
`wt ; split-pane -v cmd.exe`
<img width="241" alt="v" src="https://user-images.githubusercontent.com/3135708/74615987-782bd600-5125-11ea-8ec9-ab5413f86729.png">

`wt ; split-pane -h cmd.exe`
<img width="302" alt="h" src="https://user-images.githubusercontent.com/3135708/74615988-78c46c80-5125-11ea-9770-ca111e5bd91e.png">

The first command gives us an error, the second the help for split-pane sub-command, althought both dialog windows are a result of case-sensitivity issue with -H and -V.

Solution is quite simple. Remove -h as a shortcut for help command (--help, -?, and /? are more than enough).
Make horizontal and vertical arguments case-insensitive.

**Comment by WSLUser** [comment]
> Make horizontal and vertical arguments case-insensitive.

That would break compatibility with WSL so that can't happen. We should be able to use the wt commandline from any shell, including ones utilized in WSL (bash, fish, zsh, etc.)

**Comment by alexandair** [comment]
@WSLUser 
What do you mean "that would break compatibility"? wt.exe is still not GA. It's 0.9. So, now is the right time to fix the problem in PowerShell shell. Pre-GA time is the time for a breaking change. In any supported shell.

**Comment by WSLUser** [comment]
Yes there are a number of issues with the WT commmandline but certain fundamentals need to be kept in place. Perhaps we can simply add different aliases depending on the shell being supported. For PS (Windows installed) and cmd, we can get the traditional type of commandline and for everything else, continue the same syntax and simply fix the logic that appears that have a number of bugs with it.

**Comment by DHowett-MSFT** [comment]
I'm closing this one as by-design for now. We're tracking the case sensitivity in another issue, and requests for the help dialog to change go in the discussion thread #4601.

The dialogs are consistent if you consider that one is an error for an invalid param, one is subcommand --help and one is wt --help. We could likely improve them by showing subcommand --help when we present an error for an invalid param.

/dup #4601
