### ISSUE TITLE
Crash: `_terminal` (and other members?) used after freed in `TermControl`

### ISSUE THREAD

**Issue by greg904** [microsoft/terminal#4613]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): master (672010a1)

Any other software?
```

# Steps to reproduce

1. Open the terminal
2. Put your mouse cursor on the <kbd>+</kbd> button to open a new tab
3. Quickly click with the left mouse button and then click with the middle mouse button to open a tab and close it. If you do it right, you should get this error message (which might be a bug in and of itself?): ![image](https://user-images.githubusercontent.com/56923875/74605546-4c7b0280-50c9-11ea-9e06-07c1c54c2304.png)
4. **Don't click <kbd>OK</kbd> yet!**
5. Focus the terminal window, behind that error message.
6. Repeat 3. Nothing will happen because the application is frozen while you click <kbd>OK</kbd> in the dialog.
7. Click <kbd>OK</kbd> in the dialog.
8. Now, the dialog closes and another dialog with the same error message opens. If it didn't open, you need to start again from 2. You'll need to train to click with the right timing.
9. Click <kbd>OK</kbd> in the new dialog.
10. Terminal crashes!

# Expected behavior

No crash.

# Actual behavior

Crash on this line: https://github.com/microsoft/terminal/blob/941a44a46491e1a018419eb24c9d92d3b2640e55/src/cascadia/TerminalControl/TermControl.cpp#L563 because even though we check that `this` is still alive with `weakThis`, `_terminal` is null. Also, it seems that there are other places where we do check `this` but don't check members that could be null now because `Close` was called. It's scary!

**Comment by DHowett-MSFT** [comment]
Triaged this one into v1.0 - it's stability and reliability, sp p1

**Comment by DHowett-MSFT** [comment]
The "c0000142" error is actually because powershell was started and its parent console object died before it had a chance. That one we just can't help here :smile:

**Comment by zadjii-msft** [comment]
Okay I tried to to this naively and bluescreened my laptop. I'm _not_ touching this, but @DHowett-MSFT has an idea of how to go about this, so I'm going to let him have it
