### ISSUE TITLE
Get-PSReadlineKeyHandler and Set-PSReadlineKeyHandler throw TypeInitializer exceptions

### ISSUE THREAD

**Issue by Sarafian** [microsoft/terminal#4616]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.21]
Windows Terminal version (if applicable): 0.9.433.0

PowerShell Core: 6.2.4
```

# Steps to reproduce

After updating the Windows Terminal from the store, my profile scripts started throwing TypeInitializer exceptions for `Set-PSReadlineKeyHandler` and `Get-PSReadlineKeyHandler` that are invoked as part of my `pwsh` profile.

The code that registers a KeyHandler is

```powershell
    Set-PSReadlineKeyHandler -Chord "Ctrl+Alt+1" -BriefDescription 'Toggle $DebugPreference' -Description 'Toggle $DebugPreference between Continue and SilentlyContiinue' -ScriptBlock {
        if($DebugPreference -eq 'Continue')
        {
            Write-Debug "Setting DebugPreference=SilentlyContinue"
            Set-Variable -Name DebugPreference -Value "SilentlyContinue" -Scope Global -Force
            return
        }
        if($DebugPreference -eq 'SilentlyContinue')
        {
            Set-Variable -Name DebugPreference -Value "Continue" -Scope Global -Force
            Write-Debug "Setting DebugPreference=$DebugPreference"
            return
        }
    }
```
And before the profile script finishes and overview is produced like this
```powershell
    Get-PSReadlineKeyHandler |Where-Object -Property Function -Like "Toggle*" | Format-Table Key,Description
    Get-PSReadlineKeyHandler |Where-Object -Property Function -Like "Reload*" | Format-Table Key,Description
```

# Expected behavior

The expected behavior is for the keyhandlers to register and the profile to finish loading with this
```none
Key        Description
---        -----------
Ctrl+Alt+1 Toggle $DebugPreference between Continue and SilentlyContiinue
Ctrl+Alt+3 Toggle $InformationPreference between Continue and SilentlyContiinue
Ctrl+Alt+2 Toggle $VerbosePreference between Continue and SilentlyContiinue


Key        Description
---        -----------
Ctrl+Alt+0 Reload profile
```

# Actual behavior

`TypeInitializer` Exceptions for both cmdlets were thrown. Issue didn't resolve despite new sessions  and restarting the terminal. But it somehow got fixed only after I started the powershell core and  the profile loaded without problems. This happened on first execution. Then it also started working in the terminal. For this reason I don't have the exceptions. I cannot find if and where the transcriptions files of core are to find the errors. If you can help I can provide more information although from general experience they don't say anything useful.

During this short period of problems to resolution, the Windows Store was updating other apps. I don't use many so it was mostly default ones but I thought it could be of interest especially because of the nature of `TypeInitializer` exceptions.

I'm not saying there is something to actually fix here because **I don't have the problem any longer** and I can't really prove it. The bug submission is mostly to raise awareness and share if other do something similar.

**Comment by DHowett-MSFT** [comment]
So, the one thing that could have caused this is a change in powershell core versions. Terminal used to _only detect one location_ for powershell. Now it detects 8-10 and chooses the highest one to be your "preferred" installation.

Is there a chance that one of those installations was damaged somehow, and is a different one than you were expecting?

**Comment by Sarafian** [comment]
> So, the one thing that could have caused this is a change in powershell core versions. Terminal used to _only detect one location_ for powershell. Now it detects 8-10 and chooses the highest one to be your "preferred" installation.
> 
> Is there a chance that one of those installations was damaged somehow, and is a different one than you were expecting?

I didn't change anything to be honest, so I'm not sure how it could got broken. But, the settings json file has full paths of the shell's executable and I'm not sure how the terminal would chose a better version as long as the configuration file is there.

Also the problem got fixed at the moment I ran powershell independently. I think there was something wrong with the module's type initializers that are specific to the environment (console) they need to work with.

One additional thing I noticed yesterday is that this version cannot launch as an Admin. I'll check further and the problem is still there I'll create a separate bug.

**Comment by DHowett-MSFT** [comment]
This is all really interesting. Thanks for confirming! If you manage to hit it again, I'd love to know... but for now I'm going to close this one as no-repro (since one of the descriptions in no-repro is "the repro went away") ☹️

**Comment by DHowett-MSFT** [comment]
l

**Comment by Sarafian** [comment]
One of the problems I had was that I didn't know what to capture to provide analytics and by accident it went away. So, please tell me what to look into, what to capture and anything that could help from my part.

Thank you
