### ISSUE TITLE
wt command-line cannot consistently parse more than one argument

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#4618]
Bottom line: the more arguments I put on `wt` the less likely it is to work. This is currently unusable even for launching the app clean.

Something like this, in a run dialog:
```
wt new-tab -p "PowerShell Core"; split-pane -H -p "Windows PowerShell"; split-pane -p cmd
```

Seems to work less than one time in five on my computer. Most of the time I get two panes, not three, and occasionally only one.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.657]
Windows Terminal Version: 0.9.433.0
```

# Steps to reproduce

Run the command above from a run dialog a half dozen times

# Expected behavior

The window should open the same way every time, with three panes, one for each of the shells I have in Windows...

# Actual behavior

Sometimes just PowerShell Core, sometimes both PowerShells, rarely all three including cmd.

**Comment by opus131** [comment]
I can confirm that I'm seeing the same behaviour.

**Comment by wrexxor** [comment]
If i run wt with multiple arguments I always get:

> split-pane : The term 'split-pane' is not recognized as the name of a
> cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

If i just run `wt split-pane -H` it will work fine

**Comment by DHowett-MSFT** [comment]
> not recognized

You need to escape the `;` so powershell doesn't consume it.

**Comment by moswald** [comment]
I can confirm that `wt` does something similar on my machine. Repeating the following command: `wt ; split-pane -V ; split-pane -V` has resulted in:

* Two vertical panes, with the right-most vertical pane also split horizontally (what?)
* Two vertical panes
* No panes, just the default tab

**Comment by brucejo75** [comment]
I am seeing the same thing.

### Repro
It repros with a very simple scenario...
Execute this multiple times and often times the last `split-pane` does not execute:
```
wt.exe new-tab; split-pane -V ;split-pane -H
```

**Comment by nbabanov** [comment]
I also reproduce it.

**Comment by 3s-217** [comment]
split-pane ,new-tab only works from Run, address bar and search bar, but does not work if executed from powershell or cmd

**Comment by nbabanov** [comment]
It works properly now! Thanks!
