### ISSUE TITLE
How to build New Windows Terminal

### ISSUE THREAD

**Issue by ivanalexo** [microsoft/Terminal#462]
Hello, I have problems when starting to compile, I followed the README file but I have many errors when I run `msbuild OpenConsole.sln` does the msbuild version matter? I also tried to run `razzle.cmd`,` bcz.cmd` and `bz.cmd` but it does not compile. Could you tell me what dependencies do i need like a version of Visual Studio or another?
I will be very grateful if you can help me.

**Comment by juincen** [comment]
I come from a mysterious Chinese organization, wearing a yellow robe and accompanied by big fish and meat in Dunton. Can you tell me how to start using this tool?

**Comment by DimitriLambrou** [comment]
#461

**Comment by cm19940306** [comment]
> 别的我不管,我就想问什么时候能在windows的linux子系统下能玩英雄联盟

**Comment by cm19940306** [comment]
I don't care about anything else. I want to ask when I can play  a game named  LOL  under the Linux subsystem of Windows.

**Comment by jmoeyersons** [comment]
#489

**Comment by xcorpio** [comment]
> > 别的我不管,我就想问什么时候能在windows的linux子系统下能玩英雄联盟

啊，兄弟 这么逗

**Comment by cm19940306** [comment]
全民的制作人们,大家好,我是练习时长2年半的个人练习生蔡徐坤,会唱,跳,rap,篮球.......music...........鸡你太美

**Comment by Mickeyto** [comment]
> 全民的制作人们,大家好,我是练习时长2年半的个人练习生蔡徐坤,会唱,跳,rap,篮球.......music...........鸡你太美

请不要丢中国人的脸。丢中国人的脸请回去中国社区丢，这是技术社区，不允许你们这些垃圾污染

**Comment by cm19940306** [comment]
> > 全民的制作人们,大家好,我是练习时长2年半的个人练习生蔡徐坤,会唱,跳,rap,篮球.......music...........鸡你太美
> 
> 请不要丢中国人的脸。丢中国人的脸请回去中国社区丢，这是技术社区，不允许你们这些垃圾污染

我丢你麻痹,你装你妈呢?

**Comment by zadjii-msft** [comment]
Okay, this thread seems to be getting a bit off topic.

For all your build-related questions, see #489.
