### ISSUE TITLE
Copy & Paste still not working v 0.9.433.0

### ISSUE THREAD

**Issue by maybeageek** [microsoft/terminal#4621]
# Environment

```none
Windows build number: Version 1909 Build 18363.657
Windows Terminal version (if applicable): 0.9.433.0

Any other software?
```

# Steps to reproduce

Mark text in the terminal windows with the mouse. Either pres CTRL+C or Enter to copy, and try to paste in texteditor.

# Expected behavior

I'd expect to have the marked textportions in my clipboard, ready to paste.

# Actual behavior

nothing gets copied to clipboard. Instead, ^C is displayed in terminal OR, when using Enter, a carriage return is seen in the terminal windows.

To clarify: I can copy&paste perfectly in cmd, powershell and linux subsystem windows. As soon as I use the Terminal Preview App, it does not work, and never has.

**Comment by scriptingstudio** [comment]
Check your keybinding settings (press `CTRL+,`) and change it properly
```
{
	"command" : "copy",
	"keys" : 
	[
		"ctrl+c"
	]
},
```

**Comment by maybeageek** [comment]
That did the trick, thanks.

curiously, my colleague said just now he could copy from the beginning without changing his settings, in two of my computers this section was completely missing.

Anyhow, thank you very much!
