### ISSUE TITLE
incorrect alignment of name in ls in wsl2 in windows terminal, but correct in windows wsl console

### ISSUE THREAD

**Issue by souradeep100** [microsoft/terminal#4624]
# Environment
Windows 10 version 2004 (build 19041.84)
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Version: 0.9.433.0
Any other software?
oh-my-zsh
➜  test echo $ZSH_VERSION
5.4.2
```
WSL2
font cascadia code
from profiles:
            "colorScheme": "Dracula",
            "fontFace": "Cascadia code",
            "fontSize": 12,
            "cursorShape": "filledBox"
# Steps to reproduce
create more good number of files in a directory and the last file name of the dir aligns incorrectly.

Like following:
➜  test ls
abcd  abcd1  abcd10  abcd2  abcd3  abcd4  abcd5  abcd6  abcd7  abcd8  abcd9  one_abcd_  one_abcd_1  one_abcd_2  one_abcd_3  one_abcd_4                                 one_abcd_5  one_abcd_6

create more good number of files in a directory and the last file name of the dir aligns incorrectly.

Like following:
➜  test ls
abcd  abcd1  abcd10  abcd2  abcd3  abcd4  abcd5  abcd6  abcd7  abcd8  abcd9  one_abcd_  one_abcd_1  one_abcd_2  one_abcd_3  one_abcd_4                                 one_abcd_5  one_abcd_6
# Expected behavior

from windows console:
➜  ~ cd test                                                                                                                                                  ➜  test ls                                                                                                                                                    abcd   abcd10  abcd3  abcd5  abcd7  abcd9      one_abcd_1  one_abcd_3  one_abcd_5                                                                             abcd1  abcd2   abcd4  abcd6  abcd8  one_abcd_  one_abcd_2  one_abcd_4  one_abcd_6     

# Actual behavior

**Comment by souradeep100** [comment]
![Capture](https://user-images.githubusercontent.com/11392837/74682471-28641200-51ec-11ea-843b-ba8bf3fab599.PNG)

**Comment by souradeep100** [comment]
Also the PS1: 
➜  test echo $PS1
%(?:%{%}➜ :%{%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)

**Comment by DHowett-MSFT** [comment]
Does this only happen after you resize the terminal? Or can you reproduce this by running `ls` without resizing it?

**Comment by souradeep100** [comment]
No it happens by default. I don't have to do any resizing. It happens only on maximized window which is default size. But when I do restore down button, in that mini scaled window the problem does not happen.

**Comment by souradeep100** [comment]
![image](https://user-images.githubusercontent.com/11392837/75180803-f100e280-5762-11ea-84fa-2c9910c51566.png)

**Comment by souradeep100** [comment]
see the o in the last "ls" output . Shared the PS1 details as well.

**Comment by souradeep100** [comment]
The oh-my-zsh theme was "robbyrussell". No changes done on theme.

**Comment by jdebp** [comment]
In colour mode, GNU `ls` uses EL 0 after every filename.  In all modes, it then uses TAB/SPC to align to the start of the next column followed by LF after the final column.  souradeep100, you can help the Microsoft people narrow the potential locus of the problem by eliminating all use of colour (and hence EL 0) by GNU `ls`, with `--colour=none`.

**Comment by DHowett-MSFT** [comment]
That would be very helpful. I’ll mark this one for author feedback. Thanks!
