### ISSUE TITLE
Terminal interferes with global hotkeys assigned to another app

### ISSUE THREAD

**Issue by davidjade** [microsoft/terminal#4625]
I have an Win32 tray app installed (3RVX) that allows me to configure the Windows Key + Scroll Wheel (middle mouse button) to alter the system volume. This is a global hotkey combination. When I open a Windows Terminal and it has the focus, this global hotkey no longer works. When I switch to any other app, then it works again. 

# Environment
Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Terminal Version: 0.9.433.0

Any other software?
https://www.3rvx.com/

# Steps to reproduce

1. Install 3RVX and config to use Windows + Scroll Wheel to change the system volume.
2. Install Windows Terminal preview from Store
3. Open Terminal and keep focused, then try Windows + Scroll Wheel hotkey to change system volume - this does not work. If you switch to any other app then the hotkey combination works.

# Expected behavior
Should not interfere with another app's global hotkey configuration that uses the Windows+Scroll wheel.

# Actual behavior
Prevents another app's Windows+Scroll hotkey from working

**Comment by DHowett-MSFT** [comment]
I'm concerned about this one, actually. I've not run into any other applications that Terminal consumes the key bindings for...
It seems like there's a >0 chance that 3RVX is doing something untowards to get at the keyboard queue.

Do the hotkeys added by 3RVX work when you're looking at Calc, or Magnifier (in Windows 10.0.19041)?

**Comment by DHowett-MSFT** [comment]
(magnifier changed in 19041 to an architecture that's like Terminal's, weirdly enough, so it can help us repro issues like this)

**Comment by davidjade** [comment]
3RVX defined hotkeys seem to work fine with Calc, magnifier, etc... It's just the new Terminal app and it seems just the hotkeys that use the key + mouse scroll are affected. 3RVX source appears to be here, btw : https://github.com/malensek/3RVX

**Comment by DHowett-MSFT** [comment]
So, weird enough, I can't get this to happen. I bound Win+WheelUp to Volume Up and it works in Terminal and everywhere else. 3RVX Beta 10.

**Comment by DHowett-MSFT** [comment]
Triaged into backlog as P2: If we can get a repro, this will be important to fix. Could be an external issue, but we're not yet sure.

**Comment by zadjii-msft** [comment]
@davidjade You still seeing this on a fresh build of 3RVX/? They may have just fixed this on their side in the last few years. 

@jstaro I can't seem to repro that on a 0.57 build of PowerToys, I suspect they may have fixed that on their side
