### ISSUE TITLE
Terminal leaves a stray tab when exiting shell

### ISSUE THREAD

**Issue by keithn** [microsoft/terminal#4627]
# Environment

```none
Windows build number:  Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0   
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.9.433.0

Any other software?
```

# Steps to reproduce

went to cmd

then was mucking around with switching tabs, came back to this cmd tab, and typed exit,  I also typed exit on a few other cmds and they disappeared correctly

# Expected behavior

tab disappears

# Actual behavior

tab stays and it says
```
C:\Users\keith.nicholas>exit

[process exited with code 9009]
```

and is non interactive

**Comment by DHowett-MSFT** [comment]
/dup #4223 with more context here  https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181
