### ISSUE TITLE
New administrative tab in current windows instead closing and open terminal by administrator

### ISSUE THREAD

**Issue by brucezlata** [microsoft/terminal#4630]
1. Already open windows terminal without opening by administrator
2. In current window, want to create a new tab by picking it from the list (see below screenshot)

![image](https://user-images.githubusercontent.com/21032579/74723964-7a517a00-5276-11ea-9e88-46c73132ae51.png)

3. New requirement add a "Run as administrator" in menu when I right-click my mouse.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #632 for more discussion.

/dup #632
