### ISSUE TITLE
Add possibility to set text line height

### ISSUE THREAD

**Issue by widersky** [microsoft/terminal#4631]
# Description of the new feature/enhancement

Would be nice to have possibility to change terminal's output content line height.

# Proposed technical implementation details (optional)

Add a

`"lineHeight": "1.3"`

option to profiles.json

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3498 for more discussion.

/dup #3498
