### ISSUE TITLE
Cursor covers the letter it is on

### ISSUE THREAD

**Issue by r-janik** [microsoft/terminal#4633]
![image](https://user-images.githubusercontent.com/47327915/74753017-ce0c9500-526f-11ea-902f-9daf773a10c0.png)

The cursor on the left is the active one, the one on the right is the one after I click on a letter. The active one seems to be covering the letter it is on. Is there a setting I don't know about that would let me see the letter?

Thank you!

**Comment by r-janik** [comment]
The cursor on the left is the active one, the one on the right is the one after I click on a letter. The active one seems to be covering the letter it is on. Is there a setting I don't know about that would let me see the letter?

Thank you!

![image](https://user-images.githubusercontent.com/47327915/74746479-ca741080-5265-11ea-8d6f-13dc883bfd20.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1203 for more discussion.

/dup #1203
