### ISSUE TITLE
Terminal title in tab is of limited use

### ISSUE THREAD

**Issue by juergenpf** [microsoft/terminal#4636]
In classical terminal emulators like e.g. putty, the windows title line is used to display useful information from the running shell (e.g. very often current working directory etc.). Displaying that in the tab is of little use, because in most cases, the display space in the tab is too small.

I suggest to add a current title line below the tabs, that displays the current terminals title line in full width of the terminal. You may make that a configurable option. Also, it would be nice to have a (configurable) status line on the bottom, that for example shows the current row and column of the cursor, the width and height of the terminal etc.

**Comment by DHowett-MSFT** [comment]
If you set `"showTabsInTitlebar": false` in your settings, you'll get a behavior somewhat like what you're asking for: trading screen real-estate for displaying more information.

**Comment by srdjanjovcic** [comment]
While `showTabsInTitlebar` gets the job done, it is far from ideal... We now end up with basically double titlebar.

**Comment by zadjii-msft** [comment]
> I suggest to add a current title line below the tabs, that displays the current terminals title line in full width of the terminal.

I mean, a double titlebar is almost exactly what was asked for in OP. It's certainly not the style I'd choose myself, but the Terminal is all about letting the user make the Terminal work however they like it. There's also `"tabWidthMode": "titleLength"` for making the tabs as long as whatever text is set for the tab.

There's also #3459 already tracking adding a status bar

**Comment by juergenpf** [comment]
Ok, the "showTabsInTitlebar" option provides what I want.

**Comment by DHowett-MSFT** [comment]
Alright, in that case I'm going to close this one out. Thanks for the input!
