### ISSUE TITLE
Acrylic Effect in the terminal is not working in Windows High Contrast

### ISSUE THREAD

**Issue by warnov** [microsoft/terminal#4638]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.592]
Windows Terminal version (if applicable): 0.8

Any other software?
```

# Steps to reproduce

Change the Windows theme to High Contrast (black). Open Windows Terminal. Notice how the acrylic effect just disappear and scrolling the mouse wheel while pressing the SHIFT key doesn't  change the opacity either.  

# Expected behavior

Changing the Windows theme to High Contrast (black) should allow to still enjoying the acrylic effect.

# Actual behavior

Changing the Windows theme to High Contrast (black) is not allowing to have acrylic effect in the terminal.

When you scroll the mouse wheel while pressing the SHIFT key, it doesn't  changes the opacity either.

**Comment by DHowett-MSFT** [comment]
High contrast is an accessibility feature to aid the visually impaired. Acrylic is very difficult for that group of people to perceive well, so it is disabled _on all Windows applications_ when high contrast is enabled.

This one is by design. Thanks!

**Comment by warnov** [comment]
Well, this is a shame. It would be great Windows Terminal could implement it as the old **cmd** is doing now:
![image](https://user-images.githubusercontent.com/1912680/74788156-023b8200-527f-11ea-806a-a7680d5ad6c9.png)

**Comment by DHowett-MSFT** [comment]
It could be argued that the legacy console host should suppress transparency in HC mode.
