### ISSUE TITLE
Terminal content goes missing when resizing (powershell/conpty)

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/terminal#4640]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Any other software?
```

# Steps to reproduce

This bug is identical to what VSCode had a few months ago: https://github.com/microsoft/vscode/issues/78634

1. Open Terminal
2. Type some PowerShell command
3. Get output
4. Resize terminal and notice how half of the output is missing

# Expected behavior

No cutouts on resize

# Actual behavior

![TerminalFail](https://user-images.githubusercontent.com/15063294/74781692-40966880-52a2-11ea-86ae-2c7823e6d702.gif)

**Comment by zadjii-msft** [comment]
This is a _bunch_ of issues that are all largely being tracked by #4200. Thanks!

/dup #4200
