### ISSUE TITLE
Add option to always start terminal with multiple tabs

### ISSUE THREAD

**Issue by ladal1** [microsoft/terminal#4641]
# Description of the new feature/enhancement
One of IMHO biggest strengths of terminal is the possibility of having multiple different cli open at the same time, just in different tabs. However as far as I can see, there doesn't appear to be a simple option how to make terminal start out with multiple different tabs already open. That would speed up work for somebody who often has to switch in between different enviroments, and while loving terminal, I'm a little sick of having to open a new tab right after opening the window because i need a different prompt then my default. (I might have just been blind and missed this in the schema, but I hope I didn't)

# Proposed technical implementation details (optional)
Argument inside profiles.json, where an array of starting tabs - by GUID - could be added. When kept unset, terminal would just default back to using defaultProfile tab as its base tab

**Comment by DHowett-MSFT** [comment]
And as of 0.9 you can do `wt -p cmd ; -p cmd -p cmd` or whatever profile you want to launch.
