### ISSUE TITLE
Copy everything from mac terminal

### ISSUE THREAD

**Issue by JasonDeving** [microsoft/terminal#4643]
copy all the features from mac terminal and put it on windows terminal. 

I want to be able to type **node** and the server works. 

Plus  `open .`  to open files.

**Comment by DHowett-MSFT** [comment]
Node is not a feature of the Mac terminal. Open is a feature of the Mac shell. This isn’t an actionable feature request, sorry.

**Comment by DHowett-MSFT** [comment]
On Windows we have node, if you install it, and `start .` instead of open.
