### ISSUE TITLE
Cursor position seems to be mispositioned when using WLS2 & git rebase

### ISSUE THREAD

**Issue by AndrejMitrovic** [microsoft/terminal#4644]
# Environment

```none
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0
Git: 2.25.0 (also reproduced with 2.17.1)
Vim: 8.0 (also reproduced with Vim 8.2)
```

# Steps to reproduce

- Run a WSL2 instance (Ubuntu)
- Clone any Git repository
- Begin a rebase `git rebase -i HEAD~2`

# Expected behavior

The cursor should be at the beginning of the line:

![Capture](https://user-images.githubusercontent.com/15028641/74801693-dcfc5180-531a-11ea-8792-decb4ed9424b.PNG)

# Actual behavior

The cursor position is not at the beginning of the line:

![Capture](https://user-images.githubusercontent.com/15028641/74801679-cce47200-531a-11ea-9f5e-62d18821b626.PNG)

-----------

Other notes:

- When running WSL (bash.exe) through the command prompt (Linux host), it works OK. But then I'm not using Windows Terminal.
- When running Git directly on Windows with the command prompt, it also works OK. But again, it's not using Windows Terminal.

 So I think this is a Windows Terminal bug.

**Comment by AndrejMitrovic** [comment]
I have also recently upgraded to a new laptop, so this is the second machine I've been able to reproduce this on.

**Comment by DHowett-MSFT** [comment]
Do you, per chance, know if Vim is trying to _hide_ the cursor? If so, we are definitely ignoring that request and keeping it visible (and when we think it's hidden, we are lazier about updating its position.)
