### ISSUE TITLE
wt command should by default background itself (detach) when opening a new window

### ISSUE THREAD

**Issue by sgsthor** [microsoft/terminal#4645]
# wt command should by default background itself (detach) when opening a new window

When the user types into a window "wt -- ssh user@host" it will open up a new window. In the current implementation, it will also leave the original window blocked until the child window is closed.

# Proposed technical implementation details (optional)

 A default action of backgrounding (or simply forking and exiting the parent process) would leave the parent shell available for use. Not backgrounding/forking blocks the shell and is (unless you are waiting for the exit code of the child) both an abuse of resources and clutter/messy.

IFF the user explicitly wants to wait for the exit code, there should be a command-line switch for enabling that.

**Comment by DHowett-MSFT** [comment]
> Not backgrounding/forking blocks the shell and is both an abuse of resources and clutter/messy.

It is also a bug, albeit one in powershell: https://github.com/PowerShell/PowerShell/issues/9970
