### ISSUE TITLE
Typing "wt" in File Explorer's address bar (while browsing a file folder) opens Terminal but does not browse the current folder. CMD works.

### ISSUE THREAD

**Issue by shanselman** [microsoft/terminal#4647]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19041.84]
Windows Terminal version (if applicable): 0.9.433.0 (but N/A)
```

# Steps to reproduce

Typing "wt" in File Explorer's address bar (while browsing a file folder) opens Terminal but does not browse the current folder. CMD works.

![image](https://user-images.githubusercontent.com/2892/74858921-f42b4700-52fa-11ea-96ad-dd904d050387.png)
Click in the address bar in Explorer, type wt and press enter. This works with cmd, not with wt.

![image](https://user-images.githubusercontent.com/2892/74858952-00af9f80-52fb-11ea-8b39-50b94bf7f2f2.png)

# Expected behavior

I'd expect wt to imply -d in this context and work the same way cmd does.

# Actual behavior

Terminal just opens at the default starting directory.

**Comment by Wason1797** [comment]
I think this was discussed here: https://github.com/microsoft/terminal/issues/620

> @carlinmack I don't think that's entirely necessary.
 
> * If you launch wt from the Windows Explorer address bar, or via something like cmd.exe (or another shell) navigated to a certain folder, then the `"startingDirectory": "."`  will ensure that Windows Terminal opens in the directory you were in.

Maybe you can look at https://gist.github.com/akunzai/b4b1f394db3ceb399ba1976a30e540fa#file-profiles-json-L9
It worked for me.

**Comment by zadjii-msft** [comment]
@shanselman there's like so much discussion on this in /dupe #878, please search before filing new issues 😜

**Comment by shanselman** [comment]
Sorry for that. I just think that https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 isn't really an acceptable answer. :(

**Comment by shanselman** [comment]
So, @zadjii-msft this worked for me https://github.com/microsoft/terminal/issues/4647#issuecomment-588354967 why don't we promote/do that?

**Comment by zadjii-msft** [comment]
@shanselman Because if you do that, then launching the Terminal from the Start Menu starts up in `C:\Windows\System32`. There's no way to have the app launch in a reasonable starting directory from both the Start Menu and also from the address bar of `explorer.exe`

**Comment by shanselman** [comment]
I literally just launched wt from Win+R just now and it shows up in C:\Users\scott

**Comment by AndeYashwanth** [comment]
@shanselman launching wt from win+R launches in user directory, but launching terminal from search it launches in system32. I used ```"startingDirectory": "."``` in my profiles.

**Comment by Banyc** [comment]
TL, DR;

Go to the settings of `wt`, add one line like the following:

```json
            {
                "guid": "{...}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "startingDirectory": "./"
            },
```
