### ISSUE TITLE
有中国人吗

### ISSUE THREAD

**Issue by juincen** [microsoft/Terminal#465]
## 这个怎么用

**Comment by Berrysoft** [comment]
去读README，写得很清楚

**Comment by CoderOverflow** [comment]
哈哈哈

**Comment by dathlin** [comment]
路过看看。

**Comment by VINO6520** [comment]
实在不行就试试谷歌翻译吧

**Comment by aishang5wpj** [comment]
国外项目第一动作就是找中文issue😁

**Comment by maikebing** [comment]
啊哈

**Comment by fiany** [comment]
哈哈。路过

**Comment by maikebing** [comment]
好好学学英文吧。 github上混 ， 英语不行很难受。

**Comment by LeisureZhang** [comment]
路过路过

**Comment by Felyne** [comment]
PHP是最好的语言    PHP is the best language

**Comment by juincen** [comment]
I come from a mysterious Chinese organization, wearing a yellow robe and accompanied by big fish and meat in Dunton. Can you tell me how to start using this tool?

**Comment by Berrysoft** [comment]
> I come from a mysterious Chinese organization, wearing a yellow robe and accompanied by big fish and meat in Dunton. Can you tell me how to start using this tool?

Read README.md first.

**Comment by wujysh** [comment]
#461

**Comment by lumason** [comment]
大家好

**Comment by ayousir** [comment]
顶顶顶，我们都是天朝人。

**Comment by Sokasa** [comment]
看到这个提问，我反手就是一个赞

**Comment by juincen** [comment]
> > I come from a mysterious Chinese organization, wearing a yellow robe and accompanied by big fish and meat in Dunton. Can you tell me how to start using this tool?
> 
> Read README.md first.

yeah,I'm reading

**Comment by xiyu1992** [comment]
get

**Comment by SakuraGaara** [comment]
> PHP是最好的语言 PHP is the best language

你想找事儿是吧？

**Comment by 1andme** [comment]
您好亲，有的呢grin

**Comment by xinkunZ** [comment]
右键 - 翻译中文（简体）

**Comment by charlesCXK** [comment]
Shame on you. Please do not make trouble because this is a technology community, not your `Tiger Forum`.

**Comment by Felyne** [comment]
PHP is the best language, have questions?

**Comment by chy083** [comment]
nope ,just  a joke .I am chinese.

**Comment by depeiwang** [comment]
打扰了

**Comment by maikebing** [comment]
> Shame on you. Please do not make trouble because this is a technology community, not your `Tiger Forum`.

  在这里讨论能有什么麻烦？

**Comment by dayknchung** [comment]
文字的力量大於問題的

在 2019年5月7日週二 下午2:53，Vincent <notifications@github.com> 寫道：

**Comment by qmdx00** [comment]
真TM让人头大

**Comment by liangqiushi1995** [comment]
去读README啊，至于对你的态度，看我头像

**Comment by RwLin69** [comment]
源码编译不过求组

**Comment by RwLin69** [comment]
源码编译不过求助

**Comment by Vict0r-Lee** [comment]
我来来回回看了README也不知道该怎么编译

**Comment by wuzuhou** [comment]
楼上那些说看README的，要是README看得懂。。。哎，其实我也想问，所以进来看看答案

**Comment by LinkChenzy** [comment]
README.md，不行就谷歌右键翻译吧

**Comment by SnailMann** [comment]
等待大白使用反馈

**Comment by 78778443** [comment]
下载解压后打开闪退，有遇到过吗？

**Comment by wx0322** [comment]
强大！

**Comment by dtboy1995** [comment]
windows系列的软件不都是提供exe吗，这还得自己编译。。。

**Comment by fjp203** [comment]
怎么用?

**Comment by SeriaWei** [comment]
安装包。先导信任根证书
https://1drv.ms/u/s!Aj53J0r2UND0kf1rweVP1nIbgERsqw
> https://github.com/microsoft/Terminal/issues/468

**Comment by SeriaWei** [comment]
可惜啊，系统版本太低了
![image](https://user-images.githubusercontent.com/6006218/57282222-332b3b80-70df-11e9-920b-891a05c7d3a6.png)

**Comment by Skylark0924** [comment]
> I come from a mysterious Chinese organization, wearing a yellow robe and accompanied by big fish and meat in Dunton. Can you tell me how to start using this tool?

笑死

**Comment by SeriaWei** [comment]
@Skylark0924 这是人才

**Comment by FoxInFlame** [comment]
I'm having difficulties comprehending this issue, but from translating parts I'm assuming most of the comments here are unrelated to this repo at all.

While GitHub may be a big platform in China, this is an English repo made by an English company, accepting English issues. Seems like this issue is pretty much spam and waste of space, when Microsoft is looking for genuine issue reports.

**Comment by dtboy1995** [comment]
@FoxInFlame 自由一点，何必呢，不是抬杠。

**Comment by chengluyu** [comment]
Please stop spamming. Issue board is NOT a general-purpose web forum.

**Comment by juincen** [comment]
> Shame on you. Please do not make trouble because this is a technology community, not your `Tiger Forum`.

【readme我读了好几遍，也不知道怎么编译，我哪里找麻烦了，不想回答你就别说话】
【readme I've read it several times, and I don't know how to compile it. Where I'm in trouble, don't talk if you don't want to answer.】

**Comment by chengluyu** [comment]
> @FoxInFlame 自由一点，何必呢，不是抬杠。

People should use tools in its intended way.

**Comment by Berrysoft** [comment]
> 我来来回回看了README也不知道该怎么编译

你是认真的吗……[这里](https://github.com/microsoft/Terminal/#building-the-code)写得很清楚啊

**Comment by juincen** [comment]
Yes, it should stop. I shouldn't ask.

**Comment by chengluyu** [comment]
> > Shame on you. Please do not make trouble because this is a technology community, not your `Tiger Forum`.
> 
> 【readme我读了好几遍，也不知道怎么编译，我哪里找麻烦了，不想回答你就别说话】
> 【readme I've read it several times, and I don't know how to compile it. Where I'm in trouble, don't talk if you don't want to answer.】

I don't think you did read the documentation carefully. And the issue board is not a place for general Q&A. Please turn to StackOverflow for help.

**Comment by xinkunZ** [comment]
浪费了人生中的半天用来编译这个工程。。。总之，这个真的很预览版，太丑了
![image](https://user-images.githubusercontent.com/7759897/57283522-f01e9780-70e1-11e9-9232-83923609c96b.png)

**Comment by dtboy1995** [comment]
<img width="932" alt="捕获" src="https://user-images.githubusercontent.com/19227547/57283449-be0d3580-70e1-11e9-99dc-5de18162f99d.PNG">
@xinkunZ 请教编译指南

**Comment by balthild** [comment]
If you cannot understand the README, you might not really need this software. Just go ahead with `cmd` is fine.

如果你看不懂 README，那么你大概并不需要这个软件，用 `cmd` 就行了。

**Comment by xinkunZ** [comment]
* 编译不过的可以用这个老哥@aaron-sonin fork的这份，https://github.com/aaron-sonin/Terminal.git, 亲测可以在vs2019上编译，相信我一个java开发都编的出来，你们也可以
    * 这个老哥提的PR: https://github.com/microsoft/Terminal/pull/449
* 不想自己动手的也可以用前面几楼@SeriaWei 老哥提供的OneDrive分享包

**以及#437 说明了需要Win10 1903版本以上才支持，版本不对的也不要瞎折腾了**

**Comment by kmahyyg** [comment]
Shame on you.

**Comment by jamesyangget** [comment]
Do you like van♂ 游戏？

**Comment by SamNormcoreWayne** [comment]
钓个鱼钓出来这么多人才

**Comment by liyishuai** [comment]
> I don't think you did read the documentation carefully. And the issue board is not a place for general Q&A. Please turn to StackOverflow for help.

担心话题发起人看不懂英文，谨翻译如下：
你不像是认真读过文档的样子。另外 Issue 不是用来提“如何使用”这类问题的，出门左转 StackOverflow 谢谢。

---
另请参阅[《提问的智慧》](/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)。简单来讲，你的错误包括：
- 提问场合不当
- 问题不明确
- 标题与内容无关

**Comment by liuyongtao** [comment]
66666

**Comment by dtboy1995** [comment]
大佬们别发了，邮件收的很烦

**Comment by niconiconi** [comment]
> 
> 
> > @FoxInFlame 自由一点，何必呢，不是抬杠。
> 
> People should use the tool in its intended way.

真当外国人不会Google translate, 以及以为MS里面中国人很少? 凭什么不可以说中文? Github的intention是交流, 用中文不能交流? 那做NLP的特别是Translation的组都可以停了.

**Comment by Berrysoft** [comment]
为个语言争论什么？有这个时间早就编译成功了。

**Comment by niconiconi** [comment]
> 
> 
> 为个语言争论什么？有这个时间早就编译成功了。

1809 放弃治疗, 不想升insider. 其实开x server里面弄个Linux的终端也还是可以用用. 或者Powershell也还凑合.

**Comment by niconiconi** [comment]
> 
> 
> 为个语言争论什么？有这个时间早就编译成功了。

算了, 删帖了, 不想跟这个老哥争论. 反正也改变不了什么.

**Comment by WangJincheng4869** [comment]
我觉得中国人应该很多，但是像我这样英文很差的人应该很少！
