### ISSUE TITLE
Cluster SSH Features

### ISSUE THREAD

**Issue by ryanmerolle** [microsoft/terminal#4653]
# Description of the new feature/enhancement

- Cluster SSH support to open  and control multiple terminal windows to ssh to devices auto-scaling and arranging windows on the screen with one command window allow you to input to all windows
- ping_test argument to ping devices to check if live instead of auto opening a window
- sorthosts argument to sort windows by hostname
- host range support using square brackets examples: `hostname[0-10]`, `192.168.0.[5-20]`, `host-[prod,dev][a-f]`, `192.168.[0,2-3].[1-2,3-5]`

**Comment by vbyrd** [comment]
Related to Windows Terminal and SSH. I was playing around with the recently added wt command-line arguments and I put together a URL Protocol handler helper script that will launch ssh://someuser@someserver:port URLs in Windows Terminal using OpenSSH or Plink. https://github.com/vbyrd/windows-terminal-ssh-protocol-handler

Cluster SSH type functionality would be quite nice to have. It's saved the day for me many times.

**Comment by DHowett-MSFT** [comment]
Hey @ryanmerolle; thanks for the feature request!

This would be a great opportunity for a plugin author once we get plugin support (#4000.)

I'm not sure that this sort of feature belongs in the terminal core -- we're focusing on making a great local terminal experience first and foremost -- and I think that anything we do internally would naturally play second fiddle to that. In light of that, I'm going to close this one out after linking it up to #4000 as an interesting thing that plugins could enable.

Thank you!
