### ISSUE TITLE
Add support for wt.exe to run commands in the current Terminal Window

### ISSUE THREAD

**Issue by plusls** [microsoft/terminal#4656]
# Description of the new feature/enhancement
I found that wt.exe can open a new window and split it, can it  split current window like `tmux split-window -v`, `tmux split-window -h`?
like this:
![image](https://user-images.githubusercontent.com/23459592/74924879-38f3d280-540e-11ea-8813-e38ed501bd4e.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Yep, it absolutely can! See [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#opening-with-multiple-panes) for more details.

https://github.com/microsoft/terminal/blob/9df9bd00d74e7910395306f551fc57a673155a7a/doc/user-docs/UsingCommandlineArguments.md#L115-L130

> Consider the following commandline: 
> ```powershell 
> wt ; split-pane -p "Windows PowerShell" ; split-pane -H wsl.exe 
> ``` 
>   This creates a new Windows Terminal window with one tab, and 3 panes: 
>   * `wt`: Creates the new tab with the default profile 
>   * `split-pane -p "Windows PowerShell"`: This will create a new pane, split from the parent with the default profile. This pane will open with the "Windows PowerShell" profile 
>   * `split-pane -H wsl.exe`: This will create a third pane, slit _horizontally_  from the "Windows PowerShell" pane. It will be running the default profile,  and will use `wsl.exe` as the commandline (instead of the default profile's  `commandline`).

**Comment by plusls** [comment]
but i want split current window

**Comment by plusls** [comment]
```powershell
wt ; split-pane -p "Windows PowerShell" ; split-pane -H wsl.exe 
```
it will open a new terminal...

**Comment by zadjii-msft** [comment]
Sure yea you can do that in the current window. Use the `splitPane` keybindings. By default, these are bound to the following keys:
https://github.com/microsoft/terminal/blob/39d3c6542006fa3cd45d85fc00e9d546a1398625/src/cascadia/TerminalApp/defaults.json#L242-L243

**Comment by plusls** [comment]
but I want use a shell command to do it, I want to write it in my script.

**Comment by zadjii-msft** [comment]
Unfortunately, that's not supported quite yet. It's mentioned in the "future considerations" part of the [original spec](https://github.com/microsoft/terminal/blob/master/doc/specs/%23607%20-%20Commandline%20Arguments%20for%20the%20Windows%20Terminal.md#future-considerations). It's sort-of tracked as a sub-point in #4632, but there's not a dedicated thread for it yet.

_Congratulations_, this is now the thread

**Comment by DHowett-MSFT** [comment]
We actually do have a thread for it, /dup #4472!

**Comment by lewis-munyi** [comment]
> # Description of the new feature/enhancement
> I found that wt.exe can open a new window and split it, can it split current window like `tmux split-window -v`, `tmux split-window -h`?
> like this:
> ![image](https://user-images.githubusercontent.com/23459592/74924879-38f3d280-540e-11ea-8813-e38ed501bd4e.png)
> 
> # Proposed technical implementation details (optional)

@plusls I use this workaround. 

Create a function in my default profile that opens the new tab with split windows and exits the previous tab. 
```
# %USERPROFILE%\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
Function split{
    # Open window with split panes
    start-process wt ' -p "Windows Powershell" ; split-pane -p "Windows Powershell" ; split-pane -H -p "Ubuntu"';
   # Exit
    echo "Exiting...!";
    Exit(0);
}
```
Then call the function from the terminal when needed.

`> split`
