### ISSUE TITLE
Cannot access network drives by Letter

### ISSUE THREAD

**Issue by kbalint** [microsoft/terminal#4657]
# Environment
Win: Microsoft Windows [Version 10.0.19041.84]
Terminal: Version: 0.9.433.0

# Steps to reproduce
1. mount a working network drive in File Explorer as a letter (I use L: ), verify if you see the files.
2. open Start\cmd.exe, type "L:", it switches and can access all files.
3. open Terminal -> cmd profile, type "L:" error : "The system cannot find the drive specified."

further verification steps: 
1. open Far Manager as is, see and access L: drive from dropdown
2. add Far Manager as a profile item in Terminal, and access the drive dropdown: no network drives show up.

# Expected behavior

should be able to access network drives

# Actual behavior

can't access any network drives :(

**Comment by 9Rune5** [comment]
Accidentally running Terminal elevated?

**Comment by DHowett-MSFT** [comment]
![image](https://user-images.githubusercontent.com/14316954/74965416-117b1680-53ca-11ea-9ea8-673922641e82.png)

![image](https://user-images.githubusercontent.com/14316954/74965428-150e9d80-53ca-11ea-93a4-ada631df2f6a.png)


I cannot reproduce this when I am running Terminal as the same user that mapped the drive, even if I map the drive after Terminal starts.

**Comment by kbalint** [comment]
ah sorry, @9Rune5  was right, I was running as Administrator
