### ISSUE TITLE
Process exited with code 127

### ISSUE THREAD

**Issue by anuditnagar** [microsoft/terminal#4660]
# Environment

Ouput of `ver`
```
Microsoft Windows [Version 10.0.19564.1005]
```

Ouput of `wsl -l`
```
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
```

# Steps to reproduce

1. Startup Terminal with WSL as the only Shell
2. Type `exit`

# Expected behavior

It should exit the Terminal.

# Actual behavior
![image](https://user-images.githubusercontent.com/12015553/74957458-8cc1e400-542d-11ea-97d0-467bcf050d0c.png)

**Comment by DHowett-MSFT** [comment]
This will happen if something in your user profile (`.bash_profile` or `.bashrc` or similar) fails with an exit code, or if you run a command that doesn't exist before entering `exit`. It's also possible that `.bash_logout` is failing.

This is by-design as per https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181, with a workaround supplied.
