### ISSUE TITLE
Rearranging tabs while running as admin crashes Windows Terminal

### ISSUE THREAD

**Issue by esimkowitz** [microsoft/terminal#4662]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.657]
Windows Terminal version (if applicable): 0.9.433

Any other software?
I have tweaked the settings.json file, if that is relevant I can include it.
```

# Steps to reproduce

Right click on the Windows Terminal icon in the Start Menu and click `Run As Administrator`.

Click OK on the Admin prompt (also, separate bug but this shows "Unknown program" instead of "Windows Terminal" for the app name.

Open two cmd tabs.

Drag one of the tabs.

# Expected behavior

The tabs should rearrange as they do in non-admin windows.

# Actual behavior

The window crashes immediately when you try to drag the tab and Windows Error Reporting prompt appears.
![image](https://user-images.githubusercontent.com/16651283/74969109-cdd7db00-53d0-11ea-881f-e5a22470e06a.png)

I've taken a memory dump but I can't upload it because the file is too big. I can provide this directly if needed.

**Comment by esimkowitz** [comment]
#3581 why is commenting disabled for this issue?  I see that this is marked as won't fix and that the current plan is just to disable tab reordering in Admin but it does still currently cause crashes so I'd love to know what the timeline is for this fix. From a clumsy user standpoint, this is definitely a bug. If I try to drag the window and accidentally drag a tab, my terminal session will crash and any processes I'm running will too, which is very inconvenient.

**Comment by DHowett-MSFT** [comment]
Commenting is disabled on #3581 to abate a discussion spiraling out of control. It's in the v1 milestone, and it's p1, which means we'll be fixing it.
/dup #3581.
