### ISSUE TITLE
Discussion about further improvements for the colored tab

### ISSUE THREAD

**Issue by gbaychev** [microsoft/terminal#4663]
@zadjii-msft @DHowett As mentioned in #3789 I'm opening this issue to have a discussion about further improvements and adjustments of the tab's custom color selection. If this was not what you had in mind, please close the issue.

The idea about ability to pick a custom color for a tab is described in #2994. Currently (at least in my opinion) there are two, maybe three things, which need to be discussed:
- Should the coloring of the split button be removed and exactly which pieces of code need to go away? Or should be this activated by a setting?
- How to signify the selected tab? Currently a lot of alpha transparency is added to color of the deselected tabs, is this good enough?
- There was a suggestion that the painting of the non-client is maybe provided as a follow-up PR. Is this really needed, in which from, when (after or before the implementation of the xaml themeing)?

**Comment by DHowett-MSFT** [comment]
(I tagged this one for discussion and put in on the backlog. Thanks for filing it!)

**Comment by gbaychev** [comment]
So, about the first two things:
1. I think that the coloring of the split button should go away in any form. It is awkward and looks bad.
2. Regarding the signifying of the selected tab - I did a thing
![image](https://user-images.githubusercontent.com/3358056/75117329-aef77400-5670-11ea-84ee-fa30cfcb75ac.png)

Now the selected tab has a colored bar inside of it (like the orange one). Firefox does something pretty similar with its container tabs. Why within the tab not above it? Because I need to calculate the color of the selection bar based on the tab's background. But this can collide with the color of the non-client area (even if they are different colors, a low contrast between them can make the indicator bar invisible).  
Pros:
- it is better visible than if slapped above the tab
- hey, I can make the corner of the tabs round again
Cons:
- the tab is a little bit fatter and the split button looks a bit rectangular

I think I can bring the indicator bar a little bit closer to the bottom. 
Also I'm pretty sure this is the way to go in regards to the indicating the selected bar. What are your thoughts/feedback?

**Comment by jdhitsolutions** [comment]
I think this is a related question or issue but I'm looking for a way to set the tab color as part of the profile json file.

**Comment by zadjii-msft** [comment]
@jdhitsolutions That's actually been discussed in a whole bunch of threads recently ([search](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22set+tab+color+%22+is%3Aclosed+), #6878,#6707,#7073) -  please refer to #1337, #3327, and the spec #5772 for more discussion.

**Comment by zadjii-msft** [comment]
You know, we've let this discussion fester for a while. In the meantime though, we shipped colored tabs a while ago, and we really haven't had any complaints from people about _which_ tab is selected. Honestly, people seem really happy with it as is (myself included!)

For housekeeping purposes, I'm gonna close this one out. Thanks again for working on this!
