### ISSUE TITLE
Add setting for displaying all borders on active pane

### ISSUE THREAD

**Issue by deoradh** [microsoft/terminal#4666]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0

Any other software? No
```

# Steps to reproduce

1. Open tab
2. Divide tab into two, either horizontally or vertically.  Don't divide further.

# Expected behavior

The UI clearly shows which pane has focus.

# Actual behavior

The current design (#994) just highlights the internal borders between panes: it doesn't fully encircle the pane or provide other UI cues to the user.  The shift in line placement in this case is about one line width, making the difference relatively imperceptible and largely useless at that point.

# Straw man suggestion

The existing design relies on having multiple cells to allow for disambiguation. I'd suggest just showing all borders of the pane that has focus, making it clear in all cases.

**Comment by zadjii-msft** [comment]
Questions:
* Should all borders be visible around all panes _always_ when this setting is enabled?
* If no, when the borders are added to the active pane, should they:
  - cover content from the pane?
  - change the width/height of the pane content, to make room for the borders around the edges?

**Comment by deoradh** [comment]
> Should all borders be visible around all panes always when this setting is enabled?

If there are multiple panes, all borders should be visible on the pane that has focus.  If there is only a single pane, the border is unnecessary.

> If no, when the borders are added to the active pane, should they:
> cover content from the pane?

No.  Covering content in neighboring panes should be okay, but can be avoided if inter-pane spacing is appropriately sized (if all borders are drawn, that spacing can be shared in ways it cannot be, today).  The question of what to do with the edges that correspond to the tab window itself is a slightly tricky one, of course.

> change the width/height of the pane content, to make room for the borders around the edges?

No.  You risk weird UI behaviors doing so (eg, scroll bars pop into existence for no apparent reason).

**Comment by DHowett-MSFT** [comment]
I'm going to hook this up to #1000 and put it on the backlog, marked help-wanted.

I think there's a good UI we can come to that doesn't require us to add another setting.

Perhaps #3062 would help?

**Comment by DHowett-MSFT** [comment]
Actually, yeah, I'd like to roll this into /dup #3062. Providing better visual differentiation for focused versus unfocused terminals is going to do a lot more to solve this than adding another border option.
