### ISSUE TITLE
NuGet.exe is missing

### ISSUE THREAD

**Issue by forki** [microsoft/terminal#467]
The build assumes that Nuget.exe is in path. It would be better to either include it in the repo or use dotnet restore

**Comment by wujysh** [comment]
Run `tools\razzle.cmd`

**Comment by forki** [comment]
I did. but it didn't work. 

Now I looked into it again and itshould indeed set the path to the local nuget. but it doesn't work for me

**Comment by wujysh** [comment]
@forki Can you `echo %PATH%` and validate whether `\dep\nuget` is in it?
Anyway, the `nuget.exe` is located in the directory `\dep\nuget`, you can use it directly.

**Comment by zadjii-msft** [comment]
@forki could you provide any more info as to why it doesn't work for you? As @wujysh said, there's a nuget.exe that's in the repo already, so `tools\razzle.cmd` should work correctly.

**Comment by zadjii-msft** [comment]
Also gonna drop a link to #489

**Comment by miniksa** [comment]
This appears to have sorted itself out. Closing.
