### ISSUE TITLE
Some color emojis are scaled too small

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#4672]
Terminal v0.9.433 renders some color emoji too small:

Examples:

```bash
$ echo -e "\U2620"

```
![image](https://user-images.githubusercontent.com/961950/74992924-528d1e00-53fe-11ea-84c6-48e445fe9f78.png)

```bash
$ echo -e "\U270f"
```
![image](https://user-images.githubusercontent.com/961950/74992968-7486a080-53fe-11ea-8ec8-dc893d13dc48.png)

**Comment by dgellow** [comment]
Hi @DHowett-MSFT. I see that you closed the issue and marked it as duplicate. Could you provide an issue ID we could track if we are interested in this problem?

**Comment by zadjii-msft** [comment]
@dgellow you're looking for #610
