### ISSUE TITLE
Recognizing of UTF-8 partials in `til :: u8u16` may fail

### ISSUE THREAD

**Issue by german-one** [microsoft/terminal#4673]
# Steps to reproduce

@j4james discovered that `printf "\xE2"; printf "\x98\xBA\n"` failed to output the expected glyph using a build from the latest source. See https://github.com/microsoft/terminal/issues/1851#issuecomment-588557757
I was able to reproduce this issue by updating the unit test using the same byte sequences.

# Expected behavior

Shall print a single 'WHITE SMILING FACE' (U+263A).

# Actual behavior

Prints 'REPLACEMENT CHARACTER' (U+FFFD)  three times in a row.

**Comment by DHowett-MSFT** [comment]
Hereish:

https://github.com/microsoft/terminal/blob/671110c88a13c6de2371a9ec001ae4c6f581d241/src/inc/til/u8u16convert.h#L87-L91


We're getting the lead byte at the end of the buffer, setting `stopLen` to 1 (`in.length()`), then failing out of the for loop because !`1<1`

**Comment by german-one** [comment]
I knew it was something that simple. But it was 2 in the morning here when I filed this issue and I felt like 😴😴
Thanks for assigning me. I'm happy to fix this bug when I'm back home.

**Comment by DHowett-MSFT** [comment]
Thanks so much for jumping on this and our other u16/a/u8 conversions!
