### ISSUE TITLE
How to open/run terminal

### ISSUE THREAD

**Issue by justSteve** [microsoft/terminal#4675]
I visit the Store for the app and have the '_You own this app_' but don't see it anywhere on my system and I'm unable to actually run it. **Win-R terminal** only offers **cmd**. I saw one post that said **Win-R wt** but nothing was found there. Perhaps I have a Path problem? **ver** says: Microsoft Windows [Version 10.0.17763.1039]

**Comment by greg904** [comment]
Maybe you haven't actually installed it. I think that the "You own this app" message on the store is shown when you have already installed it previously but you uninstalled it or you're on another device. This is confusing.

![image](https://user-images.githubusercontent.com/56923875/75056932-3c539080-54d8-11ea-8b4f-42e2f5e142c4.png)

**Comment by justSteve** [comment]
Install is grayed out.

**Comment by DHowett-MSFT** [comment]
Terminal is not supported on 10.0.17763.0.

**Comment by justSteve** [comment]
Yep - updated and Install is enabled. Thanks!
