### ISSUE TITLE
Lines scrolled up by `less` command remain to exist after quitting the command

### ISSUE THREAD

**Issue by sh-ikeda** [microsoft/terminal#4676]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.657]
Windows Terminal: 0.9.433.0
WSL1
Ubuntu 18.04
bash
```

# Steps to reproduce
1. Open Ubuntu 18.04 on WSL
2. Fill the console screen with any outputs
3. Run `less` command
4. Scroll down
5. Quit `less` command
6. Scroll up

# Expected behavior
The console screen recovers to the state just before the `less` command

# Actual behavior
Lines scrolled up during the `less` command remain to exist above the upper boundary
![winterm_issue_less](https://user-images.githubusercontent.com/45062593/75015019-f5ab6980-54ca-11ea-9643-1570f83bf63e.gif)

This does not happen in the default console of WSL and ConEmu.

**Comment by DHowett-MSFT** [comment]
This one's actually a /dupe of #381 -- Terminal doesn't know that Less has switched to an alternate screen mode, and therefore it doesn't know not to push those lines into scrollback.
