### ISSUE TITLE
Background Color Gradients

### ISSUE THREAD

**Issue by connorcarnes** [microsoft/terminal#4679]
# Description of the new feature/enhancement

This feature would add more customization options to the windows terminal. Currently you can only specify one color for your background. It would be nice if multiple could be specified to create a gradient. The feature could be expanded to specify the type, size and alignment of the gradient (e.g. radial gradient, aligned bottom left, size 0.5).

What setting a gradient may look like in the settings: 
https://github.com/Ghosh/uiGradients#contributing
Examples of different gradient types: 
https://www.figma.com/dictionary/gradient/

**Comment by DHowett-MSFT** [comment]
This would be a really great thing for an extension to do once we've got an extensibility model (#555) :smile:

In general, I'm struggling with how to categorize these things. We're not likely to add support for background gradients, so I'm inclined to close it... but it is valuable to know the things that we've said "could be extensions".

Perhaps me backlinking from 555 to this issue (by mentioning 555 here) is enough? The team may override me if they want!
