### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by RUSshy** [microsoft/terminal#4684]
I don't want to configure an app using a json file

I want a menu

Example:

# iTerm

![image](https://user-images.githubusercontent.com/18348637/75067254-e63d1800-54ec-11ea-9915-6c663c75b7ff.png)

![image](https://user-images.githubusercontent.com/18348637/75067280-f5bc6100-54ec-11ea-877c-33274337336a.png)

# XFCE Terminal
![image](https://user-images.githubusercontent.com/18348637/75067357-197fa700-54ed-11ea-9700-e86651ce160a.png)

# CMDER

![image](https://user-images.githubusercontent.com/18348637/75067476-63688d00-54ed-11ea-8106-04f1a89d4432.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1564 for more discussion.

/dup #1564
