### ISSUE TITLE
Cannot download Windows Terminal via Microsoft Store (0x8024001D)

### ISSUE THREAD

**Issue by Kalaschnik** [microsoft/terminal#4686]
When I try to download Windows Terminal I receive the error code `0x8024001D`. I have not found other resources about it...

I’m on fresh installed system:
Windows 10 20H1 (19041.84)

![image](https://user-images.githubusercontent.com/9831678/75071063-d7f2fa00-54f4-11ea-8298-9b60be2e7a25.png)

![image](https://user-images.githubusercontent.com/9831678/75071083-e6d9ac80-54f4-11ea-9053-5ce615b84281.png)

**Comment by DHowett-MSFT** [comment]
This appears to be an issue in Windows; that error code indicates "an update contains invalid metadata". Can you submit feedback in the Store > Update section? Is Windows Update working for you?

**Comment by Kalaschnik** [comment]
Windows Update is working fine. Store is working fine, apart form the Terminal App.

**Comment by DHowett-MSFT** [comment]
If you install Terminal from the [releases page](https://github.com/microsoft/terminal/releases), do you get the same issue?

**Comment by Kalaschnik** [comment]
That is indeed working fine; also the MS Store is showing it was installed and the Launch Button appears.
Consider this issue as semi-closed ¯\_(ツ)_/¯

**Comment by DHowett-MSFT** [comment]
That's very unusual. I'm gonna close it for now, but I'll keep my ear to the ground for other occurrences of this error code. Thanks!

**Comment by DizdarArmin** [comment]
Can't install as well. Getting this one : Code: 0x80070424

**Comment by DHowett** [comment]
@DizdarArmin That error message indicates, "The specified service does not exist as an installed service."

It sounds like your AppxSvc is disabled. If you've done anything to the windows service configuration, this project offers no warranty. If your enterprise has done the same, perhaps they need to be told that they're impeding progress.

**Comment by epikbeat** [comment]
Can't install Code:0x80070005 ;(

**Comment by brenocg1** [comment]
Same here, no error code, just this message of Error when trying download.

**Comment by vplb** [comment]
I have tried through Chrome and Edge, on the Microsoft Store: i hit the "get" button, and nothing happens. No download, no error.

**Comment by DarrellDudics** [comment]
Same here. Can't download from MS Store.

**Comment by farkroft** [comment]
mine is 0x80073CF9. If you guys know something to fix it, let me know.

**Comment by zadjii-msft** [comment]
@farkroft from [this docs page](https://docs.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting):


Error code | Value | Description and possible causes
-- | -- | --
ERROR_INSTALL_FAILED | 0x80073CF9 | Package install failed. Contact the software vendor. For more information, check the AppXDeployment-Server event log.


If the Store isn't working, then maybe try installing directly from the [releases page](https://github.com/microsoft/terminal/releases)

**Comment by DizdarArmin** [comment]
Doing all windows updates fixed my problem.

**Comment by penieldev** [comment]
Restarting AppXSvc from Task Manager solved mine.

**Comment by HarveyStroud** [comment]
Is there a fix for this, Jan 2021 and I'm having the same problem, Windows Store is just spinning its wheels when I try to install Windows Terminal - the store works for other products however?.

**Comment by wdrury-uk** [comment]
Sadly same situation.  Running PiA VPN, no issues with my other applications or Windows Updates (did the recent 20H2 update no issues)

Try to install Windows Terminal today from MS Store and receive error code 0x800704cf as below.

![image](https://user-images.githubusercontent.com/37814130/108191978-a4e54580-710b-11eb-9fbf-cd828a9113cd.png)

**Comment by DHowett** [comment]
Given that you're reporting an error code that isn't the one in the title of this bug, it is not the same situation. However, your error code maps to "network not reachable".

**Comment by wdrury-uk** [comment]
@DHowett ok, would you like to raiuse it as a new issue so can be treated speratley.  I call the issue, "Unable to down when using PiA VPN" ?

**Comment by DHowett** [comment]
You are welcome to file whatever issue you like. However: if you are using VPN software that makes it impossible to access the Microsoft Store, we aren’t going to be able to help you. Install Terminal via the Releases page on this repository or disable your VPN.

**Comment by FlexMcMurphy** [comment]
I had this problem as well. Restarting AppXSvc fixed the issue. I had to enable AppXSvc via the Registry as I could not change the settings from "Services".
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\AppXSvc`
When here, double click the Start DWORD in the right-hand pane. Change the Value data to 3 to ENABLE and to 4 is DISABLE, click OK.
Reboot and then try downloading again from Windows App store.

**Comment by nonotnoah** [comment]
I'm having this issue as well, but I'm getting no error code or any indication of things going wrong. On the store, the "install" button doesn't appear to do anything. Sometimes it will add Terminal to my start menu with a progress bar for the download, but no progress is made.

I tried installing from releases (stable, preview, even went back a couple stable releases) and the installer would sometimes complete (sometimes it would have the same issue as the store), but not launch the app. Running it from the start menu didn't work either and nothing showed up in task manager.

I have restarted AppXSvc, restarted my computer, and installed all windows updates to no avail.

Are there any diagnostics or log files that can help me debug this?

**Comment by barakad** [comment]
Happened to me too - Install from the store does nothing.
Downloading and installing from the [releases page](https://github.com/microsoft/terminal/releases) works fine.

**Comment by kapral** [comment]
Same for me, code 0x80240438

**Comment by DHowett** [comment]
@amar-01 that's a pretty unexpected failure. Are the permissions on `C:\Program Files\WindowsApps` broken somehow? Can you follow the reporting steps in #9452?

**Comment by Dylenjm** [comment]
Tired installing the terminal from both the windows store and the GitHub release page. both times I get the error 0x80073D05. I checked the error troubleshooting page, and I have neither a simulator nor a file open that would prevent the terminal from installing. it's super weird. Im on windows 11 (not a beta version or anything just the normal release).
