### ISSUE TITLE
[Windows 10X] Terminal should open on-screen keyboard

### ISSUE THREAD

**Issue by bviglietta** [microsoft/terminal#4689]
# Environment

```none
Windows build number: Windows 10X build 19571
Windows Terminal version (if applicable): 0.8.3521.0
```

# Steps to reproduce

Switch focus to a terminal window when no hardware keyboard is present.

# Expected behavior

The on-screen keyboard should appear on the screen, as it usually does when a text-entry control gains focus.

# Actual behavior

The on-screen keyboard does not appear. It can be opened from the action center.

**Comment by DHowett-MSFT** [comment]
I believe this is a /dupe of #3639
