### ISSUE TITLE
defaults.json duplicates an entry rather than adds to an array, what is the reason?

### ISSUE THREAD

**Issue by keithn** [microsoft/terminal#4691]
```
        { "command": "toggleFullscreen", "keys": [ "alt+enter" ] },
        { "command": "toggleFullscreen", "keys": [ "f11" ] }
```

looks like it should be

```
        { "command": "toggleFullscreen", "keys": [ "alt+enter", "f11" ] },
```

But there might be a reason why, but I can't find anything explaining why.

**Comment by DHowett-MSFT** [comment]
Ah, so, putting multiple keys in one array is for key _chording_ — pressing the keys in order to do the action. Using multiple entries here is on purpose. Thanks for working to keep us honest though!

**Comment by keithn** [comment]
@DHowett-MSFT  is there documentation for this?, for instance  I just tried

```
  "keybindings": [
	 { "command": "duplicateTab", "keys": [ "alt","alt","d"] }
    ]
```
or 

```
 { "command": "duplicateTab", "keys": [ "shift","shift","d"] }
```

and it doesn't seem to work.

I'm desperately trying to find ways to use terminal without all the weird finger gymnastics all the default keybindings have.  Imagine your index fingers were glued to F and J, then windows terminal is nearly impossible to use.
