### ISSUE TITLE
Can't start Windows Terminal as administrator

### ISSUE THREAD

**Issue by JekRock** [microsoft/terminal#4693]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

1. Install Windows Terminal from Microsoft Store
2. Run Windows Terminal as administrator from a non-administrator user

# Expected behavior

Windows Terminal starts with administrator rights.

# Actual behavior
Windows asks to enter an administrator password twice and then show the following error

![image](https://user-images.githubusercontent.com/5882133/75090386-17f4c400-556b-11ea-95a9-360ede0bf205.png)

**Comment by DHowett-MSFT** [comment]
Is your administrator account different from your default user account? If so, this is #4217.

**Comment by JekRock** [comment]
Yes, the administrator account is different from the logged-in user account.

**Comment by pilgi3** [comment]
I have the same issue - and yes my administrator account is different from the logged-in user account too!

**Comment by zadjii-msft** [comment]
Fantastic, thanks for following up. I'm gonna close this as a duplicate then. /dup #4217
