### ISSUE TITLE
Incorrect output when using Git for Windows bash.exe profile

### ISSUE THREAD

**Issue by benjivm** [microsoft/terminal#4697]
# Environment

```none
Windows build number: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

Use the following (or similar, i.e., `bash.exe`) profile:

```json
"profiles" : 
[
    {
        "name" : "bash",
        "guid": "{00000000-0000-0000-ba54-000000000001}",
        "closeOnExit" : true,
        "colorScheme" : "One Half Dark",
        "fontFace" : "Cascadia Mono PL",
        "fontSize" : 12,
        "commandline" : "\"%USERPROFILE%\\scoop\\apps\\git\\current\\bin\\bash.exe\" -i -l",
        "icon" : "%USERPROFILE%\\scoop\\apps\\git\\current\\mingw64\\share\\git\\git-for-windows.ico",
        "useAcrylic" : true,
        "startingDirectory" : "%USERPROFILE%",
        "acrylicOpacity" : 0.8
    },
]
```

# Expected behavior (top, `git-bash.exe`) Actual behavior (bottom, `wt.exe` with above profile)

![](https://i.imgur.com/oldWzzj.png)

# Expected behavior (top, `git-bash.exe`) Actual behavior (bottom, `wt.exe` with above profile)

![](https://i.imgur.com/BARMOBg.png)

**Comment by DHowett-MSFT** [comment]
You've indicated two different issues, actually. The first is that git-bash cannot detect that it can print UTF-8 to the console, and so it's not putting the terminal in a mode that will parse UTF-8. This is an application issue -- though one you can perhaps mitigate by setting `LANG=en_US.UTF-8` and `LC_ALL=en_US.UTF-8` in your environment.

The second is that `TERM` is not being set to `xterm-256color`. Can you confirm the value of `TERM`?

**Comment by benjivm** [comment]
Thanks for your guidance: where do I set the `LANG` and `LC_ALL` environment variables? I tried setting them as Windows system variables with no effect.

Regarding the value of `term`:

From Windows Terminal using `sh.exe` (profile above):
```bash
$  echo $TERM
cygwin
```

From Git Bash:
```bash
$  echo $TERM
xterm
```
