### ISSUE TITLE
Initial execution of Terminal to have 1 tab 4 panel open

### ISSUE THREAD

**Issue by RyKaj** [microsoft/terminal#4699]
First off **LOVE** what you guys have done. This is much better then putty and having 4 powershell console window all at once. 

# Description of the new feature/enhancement

I could not find anything on the net. I tried to modify the profile.json as well. 

Is there a way when I initially run the terminal to have it open 1 tab with 4 equal panels within it?  I am happy if all four panel default is PowerShell. 

![image](https://user-images.githubusercontent.com/48734848/75100385-ed226400-559a-11ea-8522-91a0fa284f3f.png)

**Comment by DHowett-MSFT** [comment]
Some version of this is possible with some version of the WT commandline arguments; see our docs on [using commandline arguments](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) for more info!

**Comment by zadjii-msft** [comment]
The other version of being able to set this up in your settings is tracked by #756

**Comment by RyKaj** [comment]
The color in your documentation is based on the profile. My suggestion was if I had 4 panel of the same profile to have different color.

**Comment by zadjii-msft** [comment]
I'm sorry, could you elaborate? I'm pretty sure color isn't mentioned in the original post in this thread at all...

**Comment by RyKaj** [comment]
Sorry I might have put this in the wrong issue #. I know I created couple of issues. I am not able to find the other ones.  

Lets say the console is PowerShell. Right now you guys have color configuration based on console. 
The color suggestion was if I had 4 panel on 1 tab of the same console.  Can each panel have different color. For me each panel could represent different development environment and/or same environment different servers (API, Website, Database).
The color could be base on a word in the host name or something. 



(If you like I can create a new ticket about the colors).
