### ISSUE TITLE
Touchpad not working

### ISSUE THREAD

**Issue by vj-abishek** [microsoft/terminal#4700]
# Enable Touchpad in terminal

# Proposed technical implementation details (optional)

```Touchpad gestures like scrolling with two figures are not working. ``` 
 I'm Using Dell laptop. It is also not working in Microsoft store in the details page. Please make it available!!

**Comment by DHowett-MSFT** [comment]
/dup #979 -- we still have no idea what causes this, but you say it doesn't work in Store either?

Does it work in other modern windows apps like Groove Music or Feedback Hub?
