### ISSUE TITLE
Windows Terminal won't start

### ISSUE THREAD

**Issue by MichalNemecek** [microsoft/terminal#4701]
Behavior:
Windows terminal opens as a big white window and then closes.

Version:
* Windows: 10 Home Insider build 19569.rs_prerelease.200214-1419
* Windows Terminal: v0.9.433.0

Steps to reproduce:
* Install Windows Terminal
* Open Windows Terminal

**Comment by DHowett-MSFT** [comment]
Haven't hit one of these in a while!

/feedback
