### ISSUE TITLE
CMD mishandles app execution aliases when they're spawned from scripts

### ISSUE THREAD

**Issue by ablujay** [microsoft/terminal#4702]
Environment

```none
Windows build number: 10.0.18363.657
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

1. Create a `cmd` script that is meant to open windows terminal. 
(e.g. `wt ; split-pane -p "Ubuntu" ; split-pane -p "Ubuntu" -H`)

2. Run the script by double-clicking on the file

# Expected behavior

The script should run, open the configured windows terminal with 3-panes, and then the script should complete. 

# Actual behavior

The `wt` command does not seem to complete -- so both the cmd prompt and the newly created terminal are now open. The cmd prompt will close once the terminal window that was created is closed out.

**Comment by DHowett-MSFT** [comment]
Weirdly enough, this one is actually a cmd bug (not a terminal bug.) When a batch file runs an app execution alias, it refuses to return to the prompt.

**Comment by german-one** [comment]
I wouldn't call this a bug. CMD is required to work synchronously. Usually you'll call a lot of external tools (such as findstr.exe, robocopy.exe, chcp.com, etc.) from within a batch script. They have to complete before the CMD resumes with the next command.
There is the `start` command for asynchronous execution.

**Comment by ablujay** [comment]
@DHowett-MSFT — the same seems to happen when you create PS profile function and run it, it refuses to return to the prompt. 

Hope it helps!

**Comment by DHowett-MSFT** [comment]
Actually, yeah, this isn't a bug at all. CMD waits for GUI applications _from batch scripts_ in all circumstances. Use `start wt split-pane whatever` instead.
