### ISSUE TITLE
Conhost: UIA word navigation is slow

### ISSUE THREAD

**Issue by codeofdusk** [microsoft/terminal#4703]
# Environment

Windows build number: 1909 (18363.657).

Windows Terminal version (if applicable): Open Console (commit b8e33560f90ff7c4b3294f83bbeabb1b6a74d3e1).

Any other software? Yes, test build of NVDA and Open Console build used [available here](https://codeofdusk.com/UIASlowWordNavTest.zip).

# Steps to reproduce

1. Run the included NVDA build (a patched version of nvaccess/nvda#10784 that uses native UIA word navigation and disables our workarounds in Windows Console).
2. From advanced preferences (press insert+n/right-click tray icon -> preferences -> settings -> advanced), enable UI automation in Windows Console.
3. Run the latest conhost from this repository (a build of commit b8e33560f90ff7c4b3294f83bbeabb1b6a74d3e1 is included in the zip).
4. Attempt to navigate by word (numpad 4/6 with numlock disabled).

# Expected behavior

NVDA quickly reads the previous or next word, similar to Windows Terminal.

# Actual behavior

An approximately one second lag is observed for each word movement.

**Comment by codeofdusk** [comment]
Cc @carlos-zamora.

**Comment by codeofdusk** [comment]
Alternative STR, which exhibits even worse performance:

1. Start Narrator.
2. Open Open Console.
3. Move Narrator focus to the console text area (caps lock+right arrow until "text area" is announced).
4. Select word navigation (caps lock+control+down arrow until "words" is announced).
5. Attempt to navigate with caps lock+left/right arrow.

**Comment by DHowett-MSFT** [comment]
@codeofdusk thanks for testing our top-of-tree :)

@carlos-zamora, this is the issue with the end of the buffer being incalculable. JFYI this is blocking ingestion of recent conhost changes back into Windows (anything after Dec 12), as I don’t want to regress the inbox experience.
