### ISSUE TITLE
Some kind of unicode regression

### ISSUE THREAD

**Issue by djdv** [microsoft/terminal#4704]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 4420950337ccdd7bb5bb66d84538d2ea4195c101
Powershell 7-rc3
```

# Steps to reproduce

After 4420950337ccdd7bb5bb66d84538d2ea4195c101, characters like `🏠` appear to get corrupted.

I'm using this symbol in my Powershell prompt and it has stopped working as expected.
7d6738cde745655b26119aaf0daa810f615f0360:
![001](https://user-images.githubusercontent.com/13862850/75122418-45289b80-566b-11ea-9c78-cbcbf38ba968.png)
4420950337ccdd7bb5bb66d84538d2ea4195c101:
![002](https://user-images.githubusercontent.com/13862850/75122419-4bb71300-566b-11ea-948b-7dc6e9617db3.png)
```Powershell
$script:pathDelim = [IO.Path]::DirectorySeparatorChar.ToString()
(@($pwd.Path.Split($pathDelim) | select-object -skip 1) -join  $pathDelim).replace([environment]::UserName, "🏠
```

**Comment by DHowett-MSFT** [comment]
Yeah, this is fairly serious. :smile:

Thanks!

I bet it's part of the conpty change in 4420950.

![image](https://user-images.githubusercontent.com/14316954/75136321-2e993900-5699-11ea-80e1-313ad6358bd1.png)

```
function things {
write-host "🏠"
write-host "a🏠"
write-host "🏠b"
write-host "c🏠d"
}
```

/cc @miniksa

**Comment by miniksa** [comment]
```
function things {
write-host "`u{1f3e0}"
write-host "a`u{1f3e0}"
write-host "`u{1f3e0}b"
write-host "c`u{1f3e0}d"
}
```

**Comment by miniksa** [comment]
SURROGATE PAIRS!

*shakes fist into air*

**Comment by djdv** [comment]
@DHowett-MSFT , @miniksa 
Thanks for the render fix!
However, this is still presenting an issue.
If I set glyphs like that to be part of the prompt, I'm not able to actually use the shell (input seems to do nothing).
Rendering them seems fine however.
Example: https://youtu.be/5Dswxk6XdTs

**Comment by miniksa** [comment]
> @DHowett-MSFT Dustin Howett FTE , @miniksa Michael Niksa FTE
> Thanks for the render fix!
> However, this is still presenting an issue.
> If I set glyphs like that to be part of the prompt, I'm not able to actually use the shell (input seems to do nothing).
> Rendering them seems fine however.
> Example: [youtu.be/5Dswxk6XdTs](https://youtu.be/5Dswxk6XdTs)
> 
> EDIT: spoke too soon
> This doesn't happen under #4747 ([ddadcc5](https://github.com/microsoft/terminal/commit/ddadcc5fa9b0105df2e72baf235f09e9ea482b2c)) but does in current master ([4608fd0](https://github.com/microsoft/terminal/commit/4608fd0b94af2f4cf6ceec7b324ba36462e9c06b) ).

OK, great. I'm trying to bring #4747 in ASAP, so hopefully this will be fully resolved for you then.
