### ISSUE TITLE
81010002 Unrecognized Element "activatableClass" in namespace "urn:schemas-microsoft-com:winrt.v1".

### ISSUE THREAD

**Issue by kilodelta8** [microsoft/Terminal#471]
Fails when building via CMD, even though git submodules are updated, NuGet installed in directory, and envVar for cmd and powershell set to MSbuild.
Tried deploying via VS 2017 and ended up with a fail.  I updated my machine, and corrected a few other issues.  This one is beyond me.
If only my coding abilities were better.  I may tinker in the WIndowsTerminal.Manifest on line 1.
Keep up the good work everyone

![MSterm](https://user-images.githubusercontent.com/7333183/57281155-025fed80-7070-11e9-88b8-cde1c14f891f.PNG)
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

**Comment by DHowett-MSFT** [comment]
Hey there, this is by design right now when you build with the RS5 (17763) SDK. `activatableClass` is a new manifest entry for the 19H1 manifest parser.
Thanks for the report!

**Comment by Biswa96** [comment]
May I ask which parse the manifest?

**Comment by DHowett-MSFT** [comment]
What? `mt.exe`, the manifest tool

**Comment by kilodelta8** [comment]
Cool.  
I may be still premature in development here, but I am not sure how to complete the build with that particular instance failing the build.
What can I do to deploy a successful build on my machine?

**Comment by zadjii-msft** [comment]
That's not an error fortunately, it's only a warning. If you have some sort of `/Wall` set for VS, I'd disable it for the Terminal sln.

**Comment by kilodelta8** [comment]
Awesome.  Thank you.  I will give that a try.

**Comment by kilodelta8** [comment]
Alright guys.  I have finagled all I can.  Over 24 hours straight and still no luck.  I fix/workaround an issue and another comes up, I've googled with surgical precision.  I am right back to being prompted for the 10.0.18362.x SDK again after already installing it.  OS is up to date, SDK is correct, solution builds and rebuilds correctly, no errors in deployment until you run the application (see pic). I know it has to be something I am doing, or not doing.
My eyes are on fire.  I will just wait until an installer becomes available, or try again after sleep.
Really excited about this application.  Kudos to the team and everyone involved.

![MSterminal002](https://user-images.githubusercontent.com/7333183/57358906-09ecc880-713c-11e9-8c31-4c36860512db.PNG)
![MSterminal003](https://user-images.githubusercontent.com/7333183/57358907-09ecc880-713c-11e9-944a-fa59d26b0cf1.PNG)
![MSterminal004](https://user-images.githubusercontent.com/7333183/57358908-09ecc880-713c-11e9-99cf-f3112a050f36.PNG)

**Comment by ysc3839** [comment]
Your Windows build number? (Type ver at a Windows Command Prompt)

**Comment by zadjii-msft** [comment]
You need to be running Windows version >= 18362. I don't believe it's hit general availability quite yet, so the easiest route to get to a high enough build number is to be a Windows Insider.

**Comment by kilodelta8** [comment]
Makes sense.  Thanks everyone.
