### ISSUE TITLE
Improve text rendering consistency between WSL bash.exe and Windows Terminal

### ISSUE THREAD

**Issue by robeving** [microsoft/terminal#4710]
# Environment
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal 0.9.433.0  - Windows Store latest

# Steps to reproduce
https://github.com/migueldeicaza/gui.cs
cd gui.cs/StandaloneExample/
dotnet run

# Expected behavior

* Rendering fills Window
* Window border does not have gaps in spacing around | char
* Mouse movements are reported like in Bash on Windows conhost

# Actual behavior
![screenshot](https://user-images.githubusercontent.com/38658282/75168613-179d2a00-571f-11ea-82d1-00370f8cee8d.PNG)

Out of the terminal emulations I've tried (PuTTY/KiTTY, Windows Terminal and Bash on Windows), Bash on Windows correctly handles most of the display elements correctly.

**Comment by DHowett-MSFT** [comment]
Thanks for the report.

* Rendering fills Window
   * This is not necessarily always going to be possible: there will always be a gutter <= 1 cell in size on the bottom and <=1 cell in size plus the side of the scrollbar on the right (assuming you have scrollbars turned on.)
* Window border does not have gaps in spacing around | char
   * I think this is a /dup of #455
* Mouse movements are reported like in Bash on Windows conhost
   * This is a /dup of #545 

(please try to avoid filing "bucket bugs" -- they're hard for us to triage.)
