### ISSUE TITLE
Garbage/Encoded characters displayed instead of expected alphabetical chars

### ISSUE THREAD

**Issue by amit-msft** [microsoft/terminal#4712]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0

Any other software?
```

# Steps to reproduce

1. Launch `git gui` in a PowerShell tab
2. Return to Terminal window, input anything, say `dir`

# Expected behavior

Regular alphabetical input characters displayed

# Actual behavior

Garbage/Encoded characters displayed instead of expected alphabetical chars

![image](https://user-images.githubusercontent.com/11775857/75184450-3ee10080-56f9-11ea-854d-2c6178d27518.png)

**Comment by DHowett-MSFT** [comment]
So, weird enough, this is because of `git-gui.exe` turning off virtual terminal processing mode. Since that's a thing we let console applications do, we can't really _stop_ it from doing that. :smile:
