### ISSUE TITLE
Handle String value for Keybindings's Keys

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4713]
# Description of the new feature/enhancement

In the following example...
```json
"keybindings": [
  { "command": "copy", "keys": "ctrl+c" }
]
```
the desired keybinding is not added because `keys` accepts an array type. The user receives no notification of this being dropped.

# Proposed technical implementation details

We have two options here...
1. throw a warning telling you that this is being dropped
2. accept the string value and assume it's a key chord of size 1

I propose we do the second one. It's easier to implement and not annoying.

**Comment by zadjii-msft** [comment]
Wow that's so obvious. Lets just do 2. That's so easy.

**Comment by DHowett-MSFT** [comment]
I laughed aloud at that response . . . and then moved this into the v1 milestone :wink:
