### ISSUE TITLE
wt.exe /d doesn't work if the directory path ends in '\' and is quoted

### ISSUE THREAD

**Issue by viorel-m-git** [microsoft/terminal#4715]
WT Version: 0.9.433.0
OS/PS Build: 10.0.19572.1000.

This works:
wt /d "C:\Users\\"

This doesn't:
wt /d "c:\Documents and Settings\\"

The error is
[error 0x8007010b when launching `powershell.exe']

Workaround: add a period at the end:
wt /d "c:\Documents and Settings\\."

**Comment by zadjii-msft** [comment]
_wait what_

I didn't think that we supported `/d`, `/startingDirectory`, etc. I thought we only supported the `-d` `--startingDirectory` format. Color me _pleasantly surprised_ 😄.

_regardless_ this is _probably_ a bug, so I'll add it to 1.0. Thanks!

**Comment by DHowett-MSFT** [comment]
This is actually a /dup of #4571 (more info in that thread)

**Comment by DHowett-MSFT** [comment]
(Also, 4571 and 4715 o_O)

**Comment by viorel-m-git** [comment]
Ah, yes - sorry - I looked for duplicates but my search didn't find these.
Thanks
