### ISSUE TITLE
libraryincludes.h(46): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory

### ISSUE THREAD

**Issue by geeksfn** [microsoft/Terminal#472]
I am getting this error when trying to build using VS 2017:
libraryincludes.h(46): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
Microsoft Windows [Version 10.0.17763.437]

**Comment by SwimmingTiger** [comment]
You need this:
```
git submodule update --init --recursive
```
I also forgot this operation at the beginning.

**Comment by zadjii-msft** [comment]
@SwimmingTiger has the correct solution.

**Comment by dantheman213** [comment]
Perhaps add this into the README?

**Comment by zadjii-msft** [comment]
You're joking right?

https://github.com/microsoft/Terminal#building-the-code

**Comment by CaptainMorgans** [comment]
Where do I run this ? git submodule update --init --recursive
