### ISSUE TITLE
Incorrect Render After Terminal Is Full-Screened

### ISSUE THREAD

**Issue by Nafana** [microsoft/terminal#4725]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19569.1000]
Windows Terminal version: 0.9.433.0
```

# Steps to reproduce

1) Maximize the terminal (either by dragging the terminal to the top of the screen, or pressing the maximize icon on the top right of the application).
2) Press the F11 hot-key to full-screen the application.
3) Observe the top of the screen.

# Expected behavior

The terminal is full-screened and only the main terminal pane is rendered.

# Actual behavior

A white box is rendered on top of the terminal, presumably from the application navbar (taskbar?).

![Full-Screen Render Incorrectly](https://i.gyazo.com/16a73a022f9517433ccc26d5f8137a53.gif)

**Comment by Nafana** [comment]
Should have tested this sooner, sorry! This is only reproducible if you have the "Automatically hide the taskbar in desktop mode" set to enabled in Windows settings.

To access this setting:
1.  Right-click on your taskbar
2. Click Taskbar Settings

**Comment by zadjii-msft** [comment]
Thanks for the report! Your note that this only happens when "Automatically hide the taskbar in desktop mode" is actually _very_ helpful, thanks!


This is already being tracked by another issue on our repo - please refer to #4224 for more discussion.

/dup #4224
