### ISSUE TITLE
Control Menu doesn't render correctly

### ISSUE THREAD

**Issue by keithn** [microsoft/terminal#4726]
# Steps to reproduce

ALT-SPACE to bring up the control menu
![image](https://user-images.githubusercontent.com/86080/75335111-cdb66e80-58ed-11ea-98b6-89469601ff29.png)

# Expected behavior

Normal text nothing light gr(a|e)y  with the ability to restore/min/max, something like 
![image](https://user-images.githubusercontent.com/86080/75335542-854b8080-58ee-11ea-9050-876ef38b46da.png)

# Actual behavior

Move and Size look fine,  min/max/restore/close are not visible BUT they are functional and the hotkeys work for them.

**Comment by soul4soul** [comment]
I tried to repo since it was so easy to do. It works as expected here using 0.9.433.0

![image](https://user-images.githubusercontent.com/5142635/75385899-b0ae7b00-58ae-11ea-9565-8f678395ec58.png)

**Comment by DHowett-MSFT** [comment]
Right, I also can't reproduce this on 0.9 or 0.10-pre.

**Comment by DHowett-MSFT** [comment]
@keithn it looks like you removed the version info template -- can you share what builds of Windows and Terminal you're using?
