### ISSUE TITLE
Incorrect rendering of a TUI

### ISSUE THREAD

**Issue by yossizahn** [microsoft/terminal#4727]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.657]
Windows Terminal version (if applicable): 0.9.433.0

Any other software? WSL (version 1) + python
```

# Steps to reproduce

Install [ranger terminal file manager](https://github.com/ranger/ranger) in WSL
```
pip install ranger-fm
```
run ranger:
```
ranger
```
Set it to show borders by pressing `:` (colon) followed by `set draw_borders=True` followed by the Enter key.

# Expected behavior
It should display similar to this:
![image](https://user-images.githubusercontent.com/19174667/75352883-21f02d00-58b3-11ea-9347-28c1fded60e4.png)

# Actual behavior

The border sometimes disappears and the highlighted area overshoots the border
![image](https://user-images.githubusercontent.com/19174667/75352976-48ae6380-58b3-11ea-9970-13afa98af406.png)

NOTE: It's very likely that this is a known bug, however I don't know enough about terminal sequences to understand the underlying cause of this...

**Comment by oising** [comment]
If you extend or reduce the horizontal width of the terminal itself by a few pixels, does it fix itself (you may need to force ranger to re-render itself) ?

**Comment by yossizahn** [comment]
@oising yes that fixes it temporarily, but the problem will reappear after interacting with the program a bit.

**Comment by DHowett-MSFT** [comment]
Looks like an issue in conpty (of all things):

![image](https://user-images.githubusercontent.com/14316954/75506747-d3ff2600-5993-11ea-8b3f-bc32176855fe.png)

(happens in putty-wincon)

**Comment by zadjii-msft** [comment]
@DHowett-MSFT is that a `master` build of conpty? Just important to know for sure, since the last couple conpty PRs I had were touching a similar section of code

**Comment by DHowett-MSFT** [comment]
Yes, this repros with master. ☹️

**Comment by DHowett-MSFT** [comment]
The strangest thing about this is that sometimes it _does_ draw the border. When you flick between two directories, the righthand side gets and loses a border seemingly at random.

**Comment by DHowett-MSFT** [comment]
We decide to use `ED` instead of `ECH` when we're overwriting the next-to-last cell in the row with spaces longer than an ECH/ED sequence.
