### ISSUE TITLE
Command line argument (--startingDirectory,-d) does not accept folders with spaces

### ISSUE THREAD

**Issue by jasondicker** [microsoft/terminal#4728]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version: 0.9.433.0

# Steps to reproduce

From the command line, run: wt -d c:\Users\Folder With Spaces

--or--

From the command line, run: wt -d "c:\Users\Folder With Spaces"

# Expected behavior

Windows Terminal should open at the specified starting directory i.e "c:\Users\Folder With Spaces"

# Actual behavior

Windows Terminal opens with the following error(s):

[error 0x80070002 when launching `With Spaces']

--or--

[error 0x8007010b when launching `cmd.exe']

**Comment by zadjii-msft** [comment]
This will almost certainly get better with  #4724. 

This might be a duplicate of #4571

**Comment by german-one** [comment]
@jasondicker Can you confirm that
`wt -d "C:\Program Files"`
works, while
`wt -d "C:\Program Files\"`
does not?

**Comment by jasondicker** [comment]
I can confirm that the trailing "\" causes the problem.

**Comment by german-one** [comment]
Thank you for testing again! In that case it's a dup of #4571 and fortunately we have a potential fix already.

**Comment by zadjii-msft** [comment]
Thanks for confirming!

/dup #4571
