### ISSUE TITLE
When typing "exit" from CMD, WT tab doesn't exit

### ISSUE THREAD

**Issue by manbearian** [microsoft/terminal#4736]
# Environment

```none
Windows build number:  Microsoft Windows [Version 10.0.18363.657]
Windows Terminal version (if applicable): 0.9.433.0

Any other software? not relevant
```

# Steps to reproduce

open a new cmd shell in wt
type a command that doesn't work (e.g. `foobarfoobar`)
type exit

# Expected behavior

wt tab/process should exit

# Actual behavior

WT prints a message about exit code (e.g. `[process exited with code 9009]`)
tab is "paused" as it no longer processes intput or output. wt can still be exited through the UI normally and continues to pump messages (so isn't "hung" in the technical sense).

# Other Notes

This happens to me from time to time when exiting from wt. I've only seen it with cmd shell. I've seen it with various exit codes and other scenarios, but my above steps are the simplest to reproduce.

**Comment by DHowett-MSFT** [comment]
Alas, this is a behavior that's highly conserved across multiple shells and terminal emulators on most mainstream operating systems; more info in https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181. If you'd rather it just exit every time, set `closeOnExit` to true. :smile: /dup #4223.
