### ISSUE TITLE
Shift+Click plus copyOnSelect drops newlines :(

### ISSUE THREAD

**Issue by nortakales** [microsoft/terminal#4737]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version (if applicable): Version: 0.9.433.0
```

# Steps to reproduce

1. Select some text
2. Shift + Click to select more text across multiple terminal lines (this is the important step, clicking and dragging to select does NOT produce the same effect).
3. Copy (if you have copy on select enabled this is done automatically)
4. Paste into any text editor

# Expected behavior

If this was the text that was selected:
```
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
```
this should be pasted:
```
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
C:\Users\nicholao>
```
# Actual behavior

Width of terminal determines how much white space is between each line, and there are no newlines present in the pasted content:
```
C:\Users\nicholao>                                                                   C:\Users\nicholao>                                                                   C:\Users\nicholao>                                                                   C:\Users\nicholao>                                                                   C:\Users\nicholao>
```

**Comment by DHowett-MSFT** [comment]
This is likely because..

https://github.com/microsoft/terminal/blob/2f60cf0e9138f0d788f0a7bf189ee4116a701a4d/src/cascadia/TerminalControl/TermControl.cpp#L980
https://github.com/microsoft/terminal/blob/2f60cf0e9138f0d788f0a7bf189ee4116a701a4d/src/cascadia/TerminalControl/TermControl.cpp#L988

"shift" is being held down during the pointer release, which triggers "no newlines" mode. hm.

**Comment by nortakales** [comment]
For anyone else that comes across this issue right now, there is a work around: release Shift before releasing your mouse button. As long as you can consciously remember to do things in that order, you can preserve newlines.
