### ISSUE TITLE
Perl color command produces strange glyphs

### ISSUE THREAD

**Issue by rdnlsmith** [microsoft/terminal#4738]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0

Any other software?

PowerShell: 6.2.4
Git: 2.25.1.windows.1
```

# Steps to reproduce

I was trying out [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) with their recommended color settings, and encountered a [very strange issue](https://github.com/so-fancy/diff-so-fancy/issues/361). I'm not convinced this is a problem with Windows Terminal, but I don't have enough knowledge in this area to be sure so I wanted to see what you all think.

The minimum reprod is to run the following perl script. I've also run the equivalent PowerShell script, which works correctly; see screenshot below.

```perl
binmode(STDOUT, "encoding(UTF-8)");
$bar = "\x{2500}" x 50;
$yellow = "\e[38;5;11m";
$reset = "\e[0m";
print "$yellow$bar$reset\n";
```

# Expected behavior

A 50-char yellow line is displayed.

# Actual behavior

Strange, repeating glyphs appear, in foreground-color and a gray highlight.

![image](https://user-images.githubusercontent.com/4039042/75491036-3f8cc780-5983-11ea-96f4-cb6edf11fdc0.png)

Thanks in advance for your time!

**Comment by DHowett-MSFT** [comment]
I think that's the utf-8 encoded bytes for `U+2500` 50 times, isn't it? It looks like there's a couple things going on.

1. Whatever libc perl is using to print to the screen thinks it can parse VT sequences, but it cannot. This is the classic cygwin/msys2 problem: they were written for a Windows console that doesn't support things like color, and it was never updated for the ones that do (which have existed for 4 years now.)
2. Perl is printing UTF-8 to the console _but the console is not in UTF-8 mode_.

Both of these things are, unfortunately, outside of our control. ☹️

**Comment by rdnlsmith** [comment]
I see. What confused me was, the lines do draw correctly without the color
sequence. Anyways, thanks for the response!

**Comment by DHowett-MSFT** [comment]
Interesting. Unfortunately, perl's built on a huge stack of things that are pretty adversarial to the console subsystem as it stands in Windows 10, so it's a difficult issue to debug fully :smile:
