### ISSUE TITLE
Disabling legacy console mode does not show any text on cmd console

### ISSUE THREAD

**Issue by varshavjm** [microsoft/terminal#4739]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString                    
-------- ----------- -------      -------------                    
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
Microsoft Windows [Version 10.0.18363.657]

Any other software?
```
N/A

# Steps to reproduce
1. Open cmd -> right click on top -> properties -> Options -> Check "use Legacy console" -> select OK.
2. After a few minutes for a new session,  right click on top-> properties -> Options -> Uncheck "use Legacy console" -> select OK.
3. Close and open new window.
4. The new window does not show any text.
5. Try typing in the window. 
6. Switch back to legacy mode as per step 1.
# Expected behavior

For step 4,5 no text shows up even after changing the font color, restarting a bunch of times.

# Actual behavior

Typed text and current directory should show up in the console window.

**Comment by varshavjm** [comment]
Hi, 

I wanted to disable non-legacy mode of the command prompt so I unchecked the Legacy mode option. After reopening cmd window I cannot see what I typed. Also did a bunch of font color changes, but nothing shows up still. Then switching back to Legacy mode and reopening a cmd tab makes the newly typed content  visible.

**Comment by DHowett-MSFT** [comment]
Explanation and workarounds in /dup #2319.
