### ISSUE TITLE
Terminal background colour bleeds through consol app's (VIM's) background colour - differently with different fonts.

### ISSUE THREAD

**Issue by Matthew-Maclean** [microsoft/terminal#4749]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version (if applicable): Windows Terminal (Preview)
Version: 0.9.433.0

Any other software?

VIM 8.1.1512
```

# Steps to reproduce

Using VIM 8.1 (probably other versions too), set a background colour in your colourscheme to one that is different to the one for your terminal's colourscheme. Turn on syntax highlighting, and make sure that at least some characters use a different colour. Set the font in your terminal to Cascaida Code or Consolas. View a file.

# Expected behavior

The whole of VIM should have the background colour that you set, things outside of VIM should have the background colour of your terminal. This is how it might look (done in the old Command Prompt since it gets it right):
![good](https://user-images.githubusercontent.com/20546688/75600493-ec4b6f80-5a7d-11ea-8ec8-091bd8db1114.png)

# Actual behavior

(in the examples below, VIM's background colour is a sort of grey-green (#272822), and Terminal's is yellow (#FFFF00) to make the bug easy to see).

If the font is Consolas: Between changes in the colour of text, the background colour of the terminal bleeds though the background colour of VIM. 
![bad_consolas](https://user-images.githubusercontent.com/20546688/75600515-2fa5de00-5a7e-11ea-8831-943690f0d884.png)

If the font is Cascadia Code, Between every other line, a line of the terminal's background colour bleeds through. Also note that for the Cascadia Code version, there doesn't need to be any syntax highlighting happening. The bug will appear on a blank file.
![bad_cascadia](https://user-images.githubusercontent.com/20546688/75600542-63810380-5a7e-11ea-8eb9-d60ad5406a92.png)

(notes: The easy workaround is to just have your terminal background be the same as your VIM background. This probably shows up differently or maybe not at all on different fonts.)

**Comment by j4james** [comment]
This is probably the same issue as #3626 (see also #2496, #2779, #2790, #3954).

**Comment by DHowett-MSFT** [comment]
It definitely is. /dup #3626

Thanks @j4james!
