### ISSUE TITLE
Switch to a JSON serializer that supports pretty printing

### ISSUE THREAD

**Issue by Robosky** [microsoft/terminal#475]
The contents of `profile.json` are all in the same line, marks its readability very low. Maybe it's better to change the default format of it?
![profile_screenshot](https://8spcvg.bn.files.1drv.com/y4mUgkPShHtpUhClusfL_auqEky35dYHGjJE6demYMeUGbDeeIkVi57n1vyU6DiQZHZ-TCXpa-P5PZ0mUKi38syhrnb7sJWGAWKMdTdIY4HHcwGXmux1Xtqn3Kf02JwPZT7rCf-YtqvNFf2dlNplGRlROr8dZxL1pLkV3otaCGU5K8Rol4bayKxEF7M2ukyA10BTm6koRtxR_Gjqg_91TWDXg?width=1920&height=1080&cropmode=none)

**Comment by Biswa96** [comment]
To view in formatter way, use JSONViewer plugin in Notepad++ or open that JSON file in Firefox or Chrome + Json Formatter extension.

**Comment by mikemaccana** [comment]
This is a bug (though it doesn't have an issue so it is good you made one). Copying @zadjii-msft's comment from another bug:

> The profiles.json thing is a temporary thing. Unfortunately, Windows.Data.Json always writes out json as a single line, without the ability to pretty-print it, and we re-write the profiles.json to make sure that it stays up to date with the schema of the app. So currently, it'll keep re-writing it. But that's a huge pain point that we want to fix ASAP.

**Comment by utybo** [comment]
If profiles.json is temporary, what will eventually remplace it? Will it still be a json file?

**Comment by SwimmingTiger** [comment]
Consider the case of VSCode. You can edit the JSON file directly, but they also now provide a GUI to modify configurations.

**Comment by zadjii-msft** [comment]
Oh, I'm not saying the file is temporary, I'm saying the bug is temporary.

And @SwimmingTiger hit the nail on the head - we're planning on having both an actual GUI for modifying the settings and a plaintext file to edit (for those who like living dangerously)

**Comment by Jaykul** [comment]
Yeah, I've been editing with VS Code and pressing `Shift + Alt + F` to reformat after every save.
Very confusing.

**Comment by zadjii-msft** [comment]
That's probably the one we'd go with TBH.

I think there's a small internal ingestion process that we'd need to go through just to make sure everything's above board, but when we get signoff, then I'd be happy to update the code :)

@DHowett-MSFT let's get on it (after Build is done of course)

**Comment by onovotny** [comment]
How about raising an issue with System.Data.Json to enable better formatting options on save? Seems like that'd be beneficial to a lot of people.

**Comment by DHowett-MSFT** [comment]
@onovotny It'd be excellent, and we _absolutely_ will push that dependency.
Until we can switch to the "20H1" SDK, though, we'll need to take a two pronged approach. :smile:

**Comment by DHowett-MSFT** [comment]
@lennylxx That looks like a nice library... but this worries me:

> This library does not support comments. It does so for three reasons:

I know that JSON doesn't _have_ comments. Perhaps we should open a discussion about what our settings serialization format _should_ be?
I was partial to TOML. That's a bridge too far, I reckon, so how about *JSONC*? JSON with Comments is always, always going to be more human-friendly than JSON without comments.

**Comment by mqudsi** [comment]
fwiw, vscode and many others have adopted "bastardized json" as their default for settings; it is basically "the object construction format accepted by ECMA6" where things like `// commented line` in the middle of an object, `/* comment here */`, and `{ nameWithoutQuotes: "some value" }` are accepted.

**Comment by zadjii-msft** [comment]
Oh yea, JSON _with comments_ would be important. Kinda frustrating that [nlohmann/json](https://github.com/nlohmann/json) doesn't at least have an option for it, but I get it. Stripping the comments before parsing shouldn't be that hard, *right*?

**Comment by utybo** [comment]
I guess the problem would be to write the json file with the comments it had when it was first parsed, which could be more difficult.

e.g. the terminal loads my json configurations, I make modifications through the terminal's settings, it would be great to keep the comments I put in the json files when the terminal makes modifications to it.

**Comment by zadjii-msft** [comment]
Hmm. This is a good point. 

If VsCode supports comments in their settings json, then how can they keep the comments? IIRC they have a settings UI as well.

summoning @Tyriar who might be able to link someone who actually knows

**Comment by Tyriar** [comment]
We use a parser that our team built https://github.com/microsoft/node-jsonc-parser, the settings UI is basically a UI on top of the json file and is built into VS Code itself (you wouldn't be able to leverage this).

Also FYI comments are apparently part of "json5" https://json5.org/

**Comment by jozsefsallai** [comment]
@zadjii-msft VS Code is build on top of electron which allows packages like [jsonc-parser](https://www.npmjs.com/package/jsonc-parser) to be used within the application. In fact, this module is built by the guys behind VS Code and is [being used widely across the editor](https://github.com/microsoft/vscode/search?q=jsonc-parser&unscoped_q=jsonc-parser).

**Comment by zadjii-msft** [comment]
Welp. So much for that. I can't see us having the resources needed to port that to c++ any time soon :/

**Comment by lennylxx** [comment]
Since porting jsonc-parser to C++ is quite time consuming, maybe we should seek other serialization formats. We need: 
1. hierarchical configuration 
2. human friendly 
3. pretty printing 
4. comments 
5. popular enough that most people know how to modify

So how about YAML?
There are some libraries [yaml-cpp](https://github.com/jbeder/yaml-cpp) and [rapidyaml](https://github.com/biojppm/rapidyaml), both released under MIT license.

**Comment by utybo** [comment]
YAML might feel out of place. Since VS Code uses JSON, people might expect the terminal to use json as wrll (unless we are talking about YAML 1.2 which has become a superset of JSON)

**Comment by lennylxx** [comment]
@utybo VS Code uses JSON doesn't mean JSON is a good format for configuration. Otherwises, VS Code would use JSON directly, instead of a reimplementation with comment supporting.
Don't get me wrong, actually I like json, I use it a lot in my RESTful services, but we need to choose the right techniques based on scenarios and resources we have here, not personal preferences.
Here is an ariticle taking about why json is not perfect for configuration.
https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by ysc3839** [comment]
[rapidjson](https://github.com/Tencent/rapidjson#highlights-in-v11-2016-8-25) has [relaxed JSON syntax](https://github.com/Tencent/rapidjson/blob/master/doc/dom.md#parsing-parsing) (comment, trailing comma, NaN/Infinity) options.

**Comment by DHowett-MSFT** [comment]
Personally, I wanted us to use TOML. It's robust enough, but it's far less ubiquitous than JSON.

I had a look at _rapidjson_ and _jsoncpp_. rapidjson has the benefit of being a header-only library, admittedly, but it looks like jsoncpp has a bit of an edge here specifically regarding how it handles comments and pretty printing. Comments are accessible through the `Value` interface, and they can be both read _and written_. It seems like it lets a writer control flow/pretty printing per element as well.

That'll let us do some nice things like:
* preserve user comments, but reformat file
* print out optional settings commented out (`/* "requestedTheme": ["dark", "light", ... ] */`)

I may have missed something about rapidjson, of course.

**Comment by lzl1918** [comment]
Maybe we should just wait for updates of the `Windows.Data.Json` APIs for stringify JSON objects with formatting.

And, since the existing function provided by `Windows.Data.Json` APIs can correctly parse strings with formats into JSON objects, as a workaround, instead of introducing additional libraries, a function that manually converts a JSON object into a multiple-line string with human-readable indents can be implemented before the corresponding APIs getting updated.

**Comment by mikemaccana** [comment]
Woo thanks @zadjii-msft! 😃✨

**Comment by atimholt** [comment]
Would it be possible to re-open and re-title this? The scope of the discussion expanded to choice of a different format entirely. I’d still vote for yaml compatibility, but saving as json by default (readable by yaml parsers).

Maybe this isn’t reasonable, considering how full-steam-ahead the project is on json now.

**Comment by DHowett-MSFT** [comment]
First off: I agree. But honestly, we’re probably not moving away from JSONC unless there’s a very good reason. It’s nearly ubiquitous. There’s good enough tooling for it. Even though it’s pretty screwy as a format, it does what it intends to.

I was a proponent of TOML for this project, but we’re a pretty small team and making strategic bets that get us moving faster is (almost) always going to win out.

**Comment by mqudsi** [comment]
FWIW, I wrote a `Makefile` to automatically upgrade Jira to new releases. The http XML configuration file changes every release, and is included in the release. You need to manually reconfigure the file every release, editing in changes like what port to listen on and what protocol to use, the accepted hostnames, etc. Anyway, it seems to be edited by hand on their end and each release ships with different (mangled and unformatted) xml configuration files, with different comments in different places, etc.

To work around this, I had the script take the original file from the previous release and run it through a formatter (that forces all whitespace, indentation, etc (ie doesn’t have an “allow” policy) — importantly, definitively sorting the elements and attributes to a strict order such that there can only be one valid, correct sort — and created a standardized view of the unmodified file from the previous distribution. Then I do the same with the user-modified version containing the changes we want to preserve, and finally standardize the file that shipped with the new release; giving us three different standardized files.

At this point, generate two diffs: one between the the standardized view of the previous version of the stock file and the standardized view of the user modified file, and the other between the cleaned-up previous stock file and the cleaned-up new stock file, then do a three-way merge with maximum fuzz to get a configuration with the latest features but all user changes from the previous release.

——

If you consider the old version without comments, the old version with the comments, and the new version without comments to be the three snapshots, you can generate a version with the comments with a library that doesn’t support that. It sounds scary but with the toolset already in place to format, diff, and patch it’s actually just a few lines. 

Or you could just write a patch to save any comments encountered after parsing one node/property/value and before you get to the other, then spit it back out on write, lol.
