### ISSUE TITLE
JSON schema of profiles.json doesn't accept "unbound" command of keybinding

### ISSUE THREAD

**Issue by utgwkk** [microsoft/terminal#4751]
According to [Profiles.json Documentation](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keybindings), the following keybinding setting unbinds scrollUp from `ctrl+shift+up` and it actually unbinds the scrollUp command.

```json
{
    "command": "unbound",
    "keys": ["ctrl+shift+up"]
},
```

But JSON schema validator raise warning to `unbound` with following message:
>Incorrect type. Expected "object".

**Comment by yozaam** [comment]
Hey, I didn't find this in the docs are you talking of the lines,


unbound | Unbind the associated keys from any command.
-- | --

unbound | Unbind the command.
-- | --


Also maybe you're getting the warning because you put a comma at the end of your 


> 
> ```json
> {
>     "command": "unbound",
>     "keys": ["ctrl+shift+up"]
> },
> ```
> 

the " , " ?

**Comment by DHowett-MSFT** [comment]
Yeah, this should definitely work. We should also accept `null`, which I like rather more than `"unbound"`.

**Comment by jelster** [comment]
I think this issue might be more about handling of the "unbound" key binding, with the serialization error being what is expected when the extra `,` is included in the keymap array. 

> Yeah, this should definitely work. We should also accept `null`, which I like rather more than `"unbound"`.

From what I can tell, #4988 demonstrates this behavior

**Comment by musm** [comment]
I'm also seeing the same
