### ISSUE TITLE
Cannot build using Powershell Core - 0.9.443

### ISSUE THREAD

**Issue by tebeco** [microsoft/terminal#4755]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.113]
Windows Terminal version (if applicable): origin/release-0.9
VS2019 Preview 16.5.0 preview 4
```

# Steps to reproduce

```
checkout origin/release-0.9
> git reset --hard
> git clean -fdx
> git submodule update --init --recursive
> nuget.exe restore
```
# Steps to reproduce

* open powershell core (7.0.0-rc3)
* follow this repo docs

I am supposed to run this :
```pwsh
Import-Module .\tools\OpenConsole.psm1
Set-MsBuildDevEnvironment
Invoke-OpenConsoleBuild
```

# Expected behavior

Build should pass, or doc should be updated

# Actual behavior
![image](https://user-images.githubusercontent.com/2266487/75611158-32551180-5b18-11ea-861a-81720db197f6.png)
![image](https://user-images.githubusercontent.com/2266487/75611263-45b4ac80-5b19-11ea-926f-606d9bd84c6a.png)

i also tried on `Powershell DevPrompt for vs2019`, the build pass but with weird errors messages

![image](https://user-images.githubusercontent.com/2266487/75611233-f79fa900-5b18-11ea-8c5d-e031c7f9f8ae.png)

This seems not to be listed at the end of the build :
![image](https://user-images.githubusercontent.com/2266487/75611252-1e5ddf80-5b19-11ea-94d5-9c00f339763c.png)

**Comment by tebeco** [comment]
(My point here is that there's probably some update to do to the docs as i managed to make it work, but not "out of the box" :

* Does not work with powershell 7.x (Powershell Core `pwsh.exe`)
* Does not work with powershell 5.1 (one of the latest release of `powershell.exe`)
* Only works from the embedded powershell prompt build in for/with Vs2019
  it would be lovelly to have to docs points at this ^^
  ![image](https://user-images.githubusercontent.com/2266487/75615325-78bf6600-5b42-11ea-9e66-2540579893ba.png)
* you need to set the switch `-Prerelease` to `Set-MsbuildDevEnvironment` to avoid errors
  why not just use `$env:VSCMD_VER` ?, for example the value for me is `16.5.0-pre.4.0` so you can deduce if it's preview or not from that ? using SemVer parsing

**Comment by zadjii-msft** [comment]
Hey so since you filed three issues that are all fundamentally about "getting the build to work", I'm gonna close these two as a /dup of #4754, since that one has more discussion in it. Thanks!
