### ISSUE TITLE
new-tab not working when running wt.exe from command line

### ISSUE THREAD

**Issue by codenotworking** [microsoft/terminal#4757]
I read the documentation and saw `new-tab` subcommand.  When I use it from the command line, it keeps opening a new instance of Windows Terminal.

For example:
`wt.exe new-tab -d "c:\folder1"`
`wt.exe new-tab -d "c:\folder2"`

I've even tried adding different profiles:
`wt.exe new-tab -p "PowerShell Core" -d "c:\folder1"`
`wt.exe new-tab -p "Windows PowerShell" -d "c:\folder2"`

How do I get the `new-tab` subcommand to work properly and only use one instance of Windows Terminal?  Am I using the command correctly?

Any help would be much appreciated.

**Comment by DHowett-MSFT** [comment]
All wt commandline activations result in a new window right now. Fixing this requires us to fix /dup #4472.

**Comment by codenotworking** [comment]
Got it.  Thanks for the information.
