### ISSUE TITLE
The command 'cls' (clear screen) takes ~1 second

### ISSUE THREAD

**Issue by robertpaulhoving** [microsoft/Terminal#476]
Running 'cls' for clear screen takes ~1-2 seconds. That's a long time for a simple command which always works immediatly  :) 

Microsoft Windows [Version 10.0.17763.437]
Build 7-May-2019

**Comment by Oxyenyos** [comment]
Yeah, normal command execution like `cls`, `dir` etc take 3-4 secs in my case. I'm running 19H1 from preview ring on desktop with AMD 2700X and 64 GB ram

**Comment by staticvoidmain** [comment]
I noticed that initially as well in the debug build. Try compiling under Release instead. Clearing the screen feels snappy now.

**Comment by zadjii-msft** [comment]
Yea, Debug is kinda painfully slow ATM. This is because it's using both a Debug Terminal, but also a Debug ConPTY to render the text, and both of them together are pretty slow.

I'd really recommend building it as Release if you want to use it as your daily driver.
