### ISSUE TITLE
Can't install windows terminal

### ISSUE THREAD

**Issue by maximborisov** [microsoft/terminal#4761]
Hello. I can't install windows terminal on Windows 10 Insiders preview Version 2004 (OS Build 19041.113).

I've tried:
 - via Microsoft Store - process hang
 - via Microsoft.WindowsTerminal_0.9.433.0_8wekyb3d8bbwe.msixbundle package - process returned error: App installation failed with error message: error 0x8007177E: Failure to get staging session for: Microsoft.WindowsTerminal_0.9.433.0_8wekyb3d8bbwe.msixbundle. (0x8007177e)
 - via chocolately  - process returnned the same error: ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CF9)
![Via_Chocolately](https://user-images.githubusercontent.com/27629287/75625035-2d04cf00-5bcb-11ea-926c-d092b9cd7fd8.PNG)
![Via_Package](https://user-images.githubusercontent.com/27629287/75625036-2e35fc00-5bcb-11ea-8c98-5fa741348850.PNG)

**Comment by DHowett-MSFT** [comment]
So, that error message (0x8007177E) maps to `ERROR_VOLUME_NOT_SUPPORT_EFS`. It's saying that the volume you're installing Terminal to doesn't support file encryption. Weird! I think this is just something that the store is going to require for our package, as we haven't explicitly requested it or anything.

**Comment by bunswoDS** [comment]
I have the same issue.  

App installation failed with error message: error 0x8007177E: Failure to get staging session for: Microsoft.WindowsTerminal_1.1.1671.0_8wekyb3d8bbwe.msixbundle. (0x8007177e)

Can't install on windows store, errors out, can't install from release page msi download version.  Same problem with the preview version.

**Comment by IanJespersen** [comment]
I have resolved this by enabling systemwide NTFS encryption by changing the setting in the registry.
 Check if it is disabled (set to 1).

` Get-ItemProperty HKLM:SYSTEM\CurrentControlSet\Control\FileSystem NtfsDisableEncryption`

 Set it to 0 if it has been disabled.  I have no idea how this got set, it was not something I had done.

`Set-ItemProperty HKLM:SYSTEM\CurrentControlSet\Control\FileSystem NtfsDisableEncryption -Value 1`

This change required a reboot.

Once restart try installing again from the Store.

Hope this is of use.

**Comment by bunswoDS** [comment]
That fixed it!  Thanks so much.
