### ISSUE TITLE
Invoking profiles from command line even if profile is hidden.

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#4762]
Hi all

i would like to propose a feature/ability to invoke profiles from command using `wt --profile HIDDEN_PROFILE` even if profile is hidden by parameter `hidden": true`.

For now, when profile is hidden, Windows Terminal starts with default profile when using `wt --profile HIDDEN_PROFILE`

Do you think it is possible?

Thank you.

**Comment by DHowett-MSFT** [comment]
Thanks! This is a /dupe of #4139
