### ISSUE TITLE
Command line argument to open new tab in existing window.

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#4764]
Dear all

i would like to suggest and feature that would allow to open profile as a new tab to existing window.

Now when i do `wt -p PROFILE` or `wt new-tab -p PROFILE` it always opens new window.

If it is already possible could someone tell me what i am doing wrong?

Thank you.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472

**Comment by rdoering** [comment]
I would to link keepass with "windows terminal" to open ssh connections inside a existing window. But currentliy I am not  able to create the new tab inside of an existing window by the command "wt new-tab". This command will spawns a new window always.
