### ISSUE TITLE
wt.exe can not be started from wsl2/ubuntu

### ISSUE THREAD

**Issue by korpa** [microsoft/terminal#4765]
# Environment

```none
Windows build number:  10.0.19018.1
Windows Terminal version (if applicable): 0.9
```

# Steps to reproduce

* Open WT with Ubuntu 18.04
*  `export PATH="$PATH:/mnt/c/Users/<user>/AppData/Local/Microsoft/WindowsApps"`

```shell
~ $ wt.exe --help
~ $
```

# Expected behavior

Should print help or start a new WT and print help

# Actual behavior

Nothing happens

**Comment by DHowett-MSFT** [comment]
This needs to be filed over on [the WSL repo](https://github.com/microsoft/wsl) -- i bet it's related to "app execution aliases", and not just WT.

**Comment by korpa** [comment]
@DHowett-MSFT Have you already opened an issue in the WSL repo? 
microsoft/WSL#4969

Or is this a different thing?

**Comment by DHowett-MSFT** [comment]
Yes, that is the correct bug.
