### ISSUE TITLE
Running as administrator from standard user gives error

### ISSUE THREAD

**Issue by CKingX** [microsoft/terminal#4766]
# Environment

```none
Windows build number: Windows 10 version 10.0.18363.693
Windows Terminal version (if applicable): 

Any other software?
```

# Steps to reproduce

Create a standard account. Then, open wt as administrator. UAC opens up, and you type your administrator account password. 

It gives the following error: C:\User\[name of user]\AppData\Local\Microsoft\WindowsApps\wt.exe The file cannot be accessed by the system.

When running as administrator by searching the start menu for Windows Terminal, I get a different error: Windows cannot find 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.9.....(skipped the rest of the name)\WindowsTerminal.exe'. Make sure you typed the name correctly, and then try again.

# Expected behavior
It should run as administrator and run commands with administrator privileges.

# Actual behavior

It gives the error that it cannot find the path of the executable file.

**Comment by zadjii-msft** [comment]
Thanks for the bug report! This is actually already being tracked by another issue on our repo - please refer to #4217 for more discussion.

/dup #4217

**Comment by omril1** [comment]
I don't think it's a duplicate, the app just decides to crash one day and not run again with this message in repeat, also the executable "wt.exe" cannot be moved, copied or read after this happens.
