### ISSUE TITLE
Visible text input lag

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/terminal#4767]
# Environment

Windows build number: Microsoft Windows [Version 10.0.19041.113]
Windows Terminal version (if applicable): Latest from Microsoft Store

# Steps to reproduce

Use the Terminal!

# Expected behavior

Less visible input lag within the Terminal, in both Powershell and WSL.

# Actual behavior

While typing, there is visible input lag in all Windows Terminal windows.

**Comment by zadjii-msft** [comment]
Any chance you're using the retro terminal effects? I've seem personally that feature seems to introduce a bit of lag. 

Is this possibly #1311?

**Comment by privacyguy123** [comment]
I'm not sure what retro terminal effects so I don't think I'm using them no!

**Comment by DHowett-MSFT** [comment]
We're doing performance and rendering work; I bet that this is going to be related to /dup #1064 and #778
