### ISSUE TITLE
Special characters display issue after windows restart.

### ISSUE THREAD

**Issue by DominikWojciechowski** [microsoft/terminal#4769]
# Environment
1. Windows 10 :  10.0.18362.0
2. Windows Terminal version (if applicable):Windows Terminal (Preview) Version: 0.9.433.0
3. posh-git
4. oh-my-posh
5. Theme: Agnoster

# Steps to reproduce

1. Install https://github.com/adam7/delugia-code font
2. Open windows terminal settings and apply it in simmilar fashion:
```
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "fontFace" : "Delugia Nerd Font",
                "colorScheme": "Mocha Dark",
                "hidden": false
            },
```
3. Open $profile for powershell and add following lines:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Agnoster
```
4. Open in Windows Terminal PowerShell and confirm that font is changed and is displayed correctly.
![2020-03-02 08_11_50-intellij-community](https://user-images.githubusercontent.com/18571662/75653306-a220e480-5c5d-11ea-9725-600e98d8db09.png)
5. Restart windows
6. Open in Windows terminal PowerShell and confirm that font is changed bust special characters are not displayed correctly.
![2020-03-02 07_50_27-intellij-community](https://user-images.githubusercontent.com/18571662/75652326-1312cd00-5c5b-11ea-8357-041a208f355e.png)
7. Reinstall font
8. Reopen PowerShell in windows termianal and confirm that font is working fine now.

# Expected behavior
![2020-03-02 08_11_50-intellij-community](https://user-images.githubusercontent.com/18571662/75653306-a220e480-5c5d-11ea-9725-600e98d8db09.png)
After restart font should be working fine, all characters are displayed correctly

# Actual behavior

![2020-03-02 07_50_27-intellij-community](https://user-images.githubusercontent.com/18571662/75652326-1312cd00-5c5b-11ea-8357-041a208f355e.png)
![2020-03-02 07_58_28-intellij-community](https://user-images.githubusercontent.com/18571662/75652581-b2d05b00-5c5b-11ea-96c6-be2a5c4b4bbb.png)

In PowerShell everything is working fine, but when PS is opened in Windows terminal, after restart some characters are not displayed correctly.

**Comment by jdebp** [comment]
It should help to note that the characters widely used for those triangles are in the private use range of Unicode.  https://unix.stackexchange.com/q/320735/5132

**Comment by DHowett-MSFT** [comment]
This looks a lot like /dup #3257
