### ISSUE TITLE
Feature: Maximize split keyboard shortcut 

### ISSUE THREAD

**Issue by IgnusG** [microsoft/terminal#4770]
# Description of the new feature/enhancement
The shortcut would, on a screen with multiple splits, hide other splits and resize the current split to the whole window. Upon pressing the shortcut again, this would revert the split to its original size and position among the other splits.

### What is this for? 
Imagine having a split with vim left, build with file watcher on the right. You save your vim file and the build fires up compiling your files. Suddenly a **wild** bug appears and the whole right split is covered in red. There's too much and the long (multi line) text makes it difficult to read. 

#### Solution now:
1. Resize the right split up so it covers more of the window - you need multiple key presses and the vim split resizes as well causing a re-render (all kinds of visual annoyances)
2. Use a tab instead of a split for the build - if you forget to do this you can only restart the build on a new window and close the split (might as well just go with number one)

#### Solution with this feature:
1. Press a single key combination. The build split covers the whole window (vim cannot be seen). Debug in peace. Press it again and the split layout is restored. Switch to vim and for *added bonus* press it again so you can now "maximize" the vim screen to focus on it while fixing the bug.

### The problems
1. How to indicate a split is maximized? (maybe the split's (white/color) border around the inside of whole window? some text or indicator in the tab?)

### How it would look like
![image](https://user-images.githubusercontent.com/6438760/75665059-d8695e80-5c73-11ea-969e-96e7a8e74d42.png)

![image](https://user-images.githubusercontent.com/6438760/75665125-f767f080-5c73-11ea-933e-48b30c6ae79b.png)

### References
Something similar just for vim (vim splits) I use: https://github.com/timfeirg/ZoomWin

# Proposed technical implementation details (optional)
Not entirely sure how the split mechanism is designed, but if possible place the maximizing split over all other splits and fill window (leave other splits original size behind it) -> transparent background?

I'm not yet familiar with the repository code - my apologies for the lack of further info. And for anyone feel free to add or extend this issue 👍

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #996 for more discussion.

/dup #996
