### ISSUE TITLE
Add a feature/option to automatically relaunch terminated profiles (vs closeOnExit)

### ISSUE THREAD

**Issue by mknart** [microsoft/terminal#4772]
# Description of the new feature/enhancement
Automatically attempt to reconnect terminated sessions.

# Proposed technical implementation details (optional)
In profiles.json, profile.closeOnExit, add a "reconnect" option that automatically reconnects a terminated session alternatively keeps attempting to do so every, say, ten seconds until connection is made or tab is closed.

# Description
When I wake up my computer from hibernation alternatively restart a remote server, I'd like to not have to manually reopen tabs.

**Comment by pernu** [comment]
This would be a significant quality of life improvement.

I think the profile setting should take a couple of options, maybe something like "automatic" to work as the reporter described, and "manual", where the user would be required to hit the enter key to initiate the relaunch.

**Comment by zadjii-msft** [comment]
You know what, I think this is actually the same thing as #4379 "Feature Request: option to relaunch a profile when it exits". I'm gonna use that as the megathread for tracking this (and related) issues for now. Thanks!

/dup #4379
