### ISSUE TITLE
Where do I find default keybindings?

### ISSUE THREAD

**Issue by pjoe** [microsoft/terminal#4773]
I may have missed something, but have already spent 30+ minutes, trying to find documentation of the default keybindings 🤔 

Please add this info, preferably accessible from the app itself, e.g. in the `About`menu.

**Comment by zadjii-msft** [comment]
I mean, right at the top of the settings file is the following:

https://github.com/microsoft/terminal/blob/4608fd0b94af2f4cf6ceec7b324ba36462e9c06b/src/cascadia/TerminalApp/userDefaults.json#L1-L2

and if you do follow those directions and hold <kbd>Alt</kbd> while pressing the settings button, [this file ](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json) will open, with the [default keybindings](https://github.com/microsoft/terminal/blob/4608fd0b94af2f4cf6ceec7b324ba36462e9c06b/src/cascadia/TerminalApp/defaults.json#L206-L258) in it

**Comment by carlos-zamora** [comment]
Actually, opening this issue again. This may be an accessibility issue. @cinnamon-msft is gathering data from Twitter and we'll figure out next steps from there.

This has an impact on Accessibility's Automation Properties because if we have text visible on the screen, no reason to add an auto property of hidden help text to say this.

**Comment by DHowett-MSFT** [comment]
This is a p3 docs issue for backlog.

**Comment by pjoe** [comment]
Hmm, this seems very convoluted, compared to e.g. VS Code: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by pjoe** [comment]
TBH. I never thought to look at that comment in the settings, I was browsing source code and googling, trying to 'reverse-engineer' from files like: https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/CascadiaSettings.cpp#L135

**Comment by fredless** [comment]
Agree with @pjoe, if you don't know where to look this is a pretty large usability\documentation gap.

**Comment by Don-Vito** [comment]
Is this one still relevant once we have the Actions Page?

**Comment by zadjii-msft** [comment]
You know, I'm gonna say _no, it's not_. This can be found in the SUI now.
