### ISSUE TITLE
Closing terminal via taskbar will blur some areas

### ISSUE THREAD

**Issue by jlzhjp** [microsoft/terminal#4774]
# Environment

```none
Microsoft Windows [版本 10.0.19041.113]
Windows Terminal 0.9.433.0

Any other software?
PowerShell 6.2.4
```

# Steps to reproduce

1. Open Windows Terminal (only one tab)
2. Close it via taskbar.

# Expected behavior
Windows Terminal closed, nothing happens.

# Actual behavior

Some areas become fuzzy.
Other programs (UWP and Win32) works as expected.

![test](https://user-images.githubusercontent.com/35339647/75679126-ffeb1600-5cc9-11ea-8cdf-7422607e4bdb.gif)

![test](https://user-images.githubusercontent.com/35339647/75679194-201ad500-5cca-11ea-8d95-0f2bfbabb944.JPG)

Sorry, I'm not very good at English.

**Comment by zadjii-msft** [comment]
Woah that's crazy, that definitely happens to me too, although for only a _very_ brief time. Maybe there's something weird about how our window gets closed? I'd guess that it was Xaml Islands related, but I have no real idea.

**Comment by DHowett-MSFT** [comment]
Does the area stay fuzzy for a long time? When I do it, it goes back to normal very quickly.

If it stays fuzzy, can you check with Task Manager if WindowsTerminal.exe is still running?

**Comment by jlzhjp** [comment]
> Does the area stay fuzzy for a long time? 

In my case, It doesn't disappear until I move the cursor away from the fuzzy area. 

> If it stays fuzzy, can you check with Task Manager if WindowsTerminal.exe is still running?

No. Task Manager shows that the terminal has closed correctly.

**Comment by jlzhjp** [comment]
@DHowett-MSFT 
I guess that's because Windows Terminal is not pinned to taskbar.
***
![example](https://user-images.githubusercontent.com/35339647/77426700-f90a7b80-6e0f-11ea-9986-7c2df59054c1.gif)

**Comment by brunovieira97** [comment]
Any progress on this issue?

**Comment by zadjii-msft** [comment]
Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by DHowett** [comment]
But just FYI: It’s a very minor operating system bug with a trivial workaround, so nobody who would know what is causing it cares too much to look at it.

**Comment by zadjii-msft** [comment]
Any chance anyone who was seeing this before on Windows 10 is now on Windows 11 and can check if this is still happening? Looks like the acrylic blur that was there on Windows 10 is totally gone in Windows 11, so I'm betting this was fixed by the Windows shell folks.

**Comment by jlzhjp** [comment]
Hi, I've just tested it and it seems that this issue has been fixed in Windows 11.
