### ISSUE TITLE
problem to deploy after building

### ISSUE THREAD

**Issue by Jerem59** [microsoft/terminal#4776]
HI,
i'm a french (sorry for french log messages)
 and i compile windows terminal on ma laptop but i meet a problem during deployment.

Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		DEP0700 : Échec de l'inscription de l'application. [0x80073CF6] AppxManifest.xml(30,27) : erreur 0x80070002 : impossible d’installer ou de mettre à jour le package WindowsTerminal.TestHost_aq7gd5554gxm8, car l’image de l’écran de démarrage [taef.png] est introuvable. Vérifiez que le package contient bien une image pouvant servir d’écran de démarrage pour l’application et que le manifeste du package pointe sur l’emplacement dans le package où cette image d’écran de démarrage se trouve effectivement.	TestHostApp	

File missing teaf.png missing ?

Thx
Jerem

**Comment by zadjii-msft** [comment]
`TestHostApp` is actually just a utility project for helping to run some of our tests. If you want to deploy the Windows Terminal locally, you'll want to deploy `CascadiaPackage`
