### ISSUE TITLE
RTL is worse after #4747

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#4779]
Before: 
![image](https://user-images.githubusercontent.com/18221333/75720498-7ae10c00-5c8b-11ea-91c2-8df36af1a7be.png)

After:
![image](https://user-images.githubusercontent.com/18221333/75720516-8df3dc00-5c8b-11ea-9e84-596b44b8063a.png)

See utf82.txt within https://github.com/microsoft/terminal/issues/4375.

This is probably just not accounting for RTL stuff when dividing glyphs for scaling.
Also, I'm not sure that any of the RTL was correct before 4747, but it was at least displaying something. Now it's blank spaces.

We don't really state we support RTL at all yet (#538)...

**Comment by DHowett-MSFT** [comment]
We'll need to figure out RTL, but not for v1. Backlogged.

**Comment by schorrm** [comment]
Before the change, if your font supported the given RTL language natively it actually mostly worked. Okay, yes, it got much worse on the font fallback, but that was still useful -- I could mentally read the words in the wrong order for a brief peek into a file.
