### ISSUE TITLE
Cursor block doesn't show the character underneath

### ISSUE THREAD

**Issue by tudorprodan** [microsoft/terminal#4786]
![image](https://user-images.githubusercontent.com/1012368/75765193-082d6a80-5d37-11ea-9d91-bc191a5d9cb0.png)

I've searched for a `"cursorColor": "inverse"` option or something similar, haven't found one.

Please close if this is expected behaviour for some reason.

**Comment by j4james** [comment]
I believe this is a duplicate of #1203.

**Comment by tudorprodan** [comment]
> I believe this is a duplicate of #1203.

Yep, it's a duplicate of #1203
