### ISSUE TITLE
bash cannot render fonts properly

### ISSUE THREAD

**Issue by Ibrahim-Islam** [microsoft/terminal#4788]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

```

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
    {
        "guid": "{00000000-0000-0000-ba54-000000000002}",
        "acrylicOpacity" : 0.75,
        "closeOnExit" : true,
        "colorScheme" : "Campbell",
        "commandline" : "\"%PROGRAMFILES%\\git\\usr\\bin\\bash.exe\" -i -l",
        "cursorColor" : "#FFFFFF",
        "cursorShape" : "bar",
        "fontFace" : "Consolas",
        "fontSize" : 10,
        "historySize" : 9001,
        "icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
        "name" : "Bash",
        "padding" : "0, 0, 0, 0",
        "snapOnInput" : true,
        "startingDirectory" : "%USERPROFILE%",
        "useAcrylic" : true
    }

        ]
    },

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
```

# Expected behavior
Not the actual behavior show below

# Actual behavior
![image](https://user-images.githubusercontent.com/6401874/75802169-d952db00-5dae-11ea-94c9-71255dae4f25.png)

**Comment by zadjii-msft** [comment]
That pretty firmly looks like git bash not enabling virtual terminal processing for some reason. 

Also related: #3445, #2837, but I'm not sure if those are dupes or not.

**Comment by DHowett-MSFT** [comment]
also, bash is not the tool printing out those lines. we need a lot more info to figure out what's going on.

what tool are you using?

**Comment by Ibrahim-Islam** [comment]
> also, bash is not the tool printing out those lines. we need a lot more info to figure out what's going on.
> 
> what tool are you using?

sorry I dont understand what you mean by what tool
I just tried to open bash from windows terminal

**Comment by DHowett-MSFT** [comment]
Just to confirm: when you open bash OUTSIDE of terminal does it print “warn” in yellow about 400 times? That seems unusual..

**Comment by Ibrahim-Islam** [comment]
> Just to confirm: when you open bash OUTSIDE of terminal does it print “warn” in yellow about 400 times? That seems unusual..

Oh this screenshot is from running a build so that is why there are lot of warnings and stuff
But the point I wanted to make was the weird text like arrow and stuff
Not that there are lot of warnings but the warnings are rendered weird

**Comment by DHowett-MSFT** [comment]
Okay, so that thing you’re running is something we call a “tool.” It is in charge of how its own output is displayed on the screen, and there isn’t anything bash can do to change that.

Is this “tool” running inside Cygwin? Inside MSYS2? Inside WSL?

**Comment by Ibrahim-Islam** [comment]
I see. Sorry for the confusion.

When opening a bash from inside Windows Terminal its this:
![image](https://user-images.githubusercontent.com/6401874/75949711-aa855380-5ed9-11ea-8980-0b14ce4f411e.png)

But when I open git bash its this:
![image](https://user-images.githubusercontent.com/6401874/75949756-c7ba2200-5ed9-11ea-815c-976f62a0d62a.png)

Also I dont see the weird texts when running the same script from Git Bash only from Bash inside Windows Terminal.

**Comment by DHowett-MSFT** [comment]
It really looks like you have two different versions of bash installed, and when you type in “bash” you get one and when you run git bash you get a different one. You’ll need to get that sorted out!
