### ISSUE TITLE
Azure Pipelines build failed: NuGet restore failed

### ISSUE THREAD

**Issue by zuozishi** [microsoft/Terminal#479]
The nuget command failed with exit code(1) and error(Errors in packages.config projects
    Unable to find version '2.1.190405001-prerelease' of package 'Microsoft.UI.Xaml'.
      https://api.nuget.org/v3/index.json: Package 'Microsoft.UI.Xaml.2.1.190405001-prerelease' is not found on source 'https://api.nuget.org/v3/index.json'.
    Unable to find version '10.30.180808002' of package 'Taef.Redist.Wlk'.
      https://api.nuget.org/v3/index.json: Package 'Taef.Redist.Wlk.10.30.180808002' is not found on source 'https://api.nuget.org/v3/index.json'.)
Packages failed to restore
![image](https://user-images.githubusercontent.com/20531439/57285227-535df900-70e5-11e9-851e-a0b508a82e08.png)

**Comment by wolking** [comment]
Package in "./dep/packages"
![image](https://user-images.githubusercontent.com/12195297/57288223-a470eb80-70eb-11e9-8f52-c4455d2f1d41.png)

**Comment by zuozishi** [comment]
@wolking Thanks
