### ISSUE TITLE
`wt` opens a new windows with the default profile instead of the current profile

### ISSUE THREAD

**Issue by ranyitz** [microsoft/terminal#4793]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version (if applicable): Version: 0.9.433.0
```

# Steps to reproduce

Choose a profile which is not the default profile
Run `wt`

# Expected behavior

Open a new window with the same profile as the currently used profile 

# Actual behavior

Open a new window with the default profile

# Context
It makes sense to have the best defaults as possible. If I ran a command from a certain profile (for example PowerShell) I would like to continue and use the same profile.

**Comment by DHowett-MSFT** [comment]
This is just a different variation of /dup #445 for new window instead of new tab. Also, right now, there's no communication between `wt` instances.
