### ISSUE TITLE
I dont see text after i type "--"

### ISSUE THREAD

**Issue by VjekoslavKrainovic** [microsoft/terminal#4794]
When I type "--" i don't see any text in the terminal after that aswell as "--", for example when I type "git --version" I see it as "git" but when I press enter I see a version.

I use Posh-Git, Oh-My-Posh and Cascadia Code PL font.

**Comment by DHowett-MSFT** [comment]
Please share a screenshot.

**Comment by DHowett-MSFT** [comment]
And version info. And anything else that was in the bug report template.

**Comment by VjekoslavKrainovic** [comment]
[https://imgur.com/a/U2m3Knt](url)

**Comment by VjekoslavKrainovic** [comment]
https://imgur.com/a/Yi6bALT this is screenshot. I dont know how to get terminal version information

**Comment by DHowett-MSFT** [comment]
It looks like you're using a color scheme where color `90` (`brightBlack`) is the same as your background color. _All_ utilities that set color 90 will see it disappear into the background.

Sorry; this is a configuration problem.

For PowerShell, you can change the colors for parameters and operators using `Set-PSReadlineOption` (you can view the current values with `Get-PSReadlineOption`)

**Comment by VjekoslavKrainovic** [comment]
Is it possible for you to explain me how to change color?
When i type "Get-PSReadlineOption"i am getting an error -> 

> Get-PSReadLineOp : The term 'Get-PSReadLineOp' is not recognized as the name of a cmdlet, function, script file, or ope
rable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
.
At line:1 char:1
+ Get-PSReadLineOp
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PSReadLineOp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 

>

**Comment by DHowett-MSFT** [comment]
You appear to have typed `Get-PsReadlineOp`. I don't know why you've left off the `tion` that belongs on the end.

You might be happier just choosing a different color scheme for Terminal in your Settings file. "Solarized Dark" is not a very good color scheme.
