### ISSUE TITLE
Reports that terminal subprocesses are exiting with 0xc0000142 (no console host)

### ISSUE THREAD

**Issue by CaptainMorgans** [microsoft/terminal#4795]
![image](https://user-images.githubusercontent.com/3514724/75823501-89721500-5daa-11ea-92ad-9044289ebfa5.png)

Get this error on opening the Terminal. Please help!

**Comment by DHowett-MSFT** [comment]
Please don't delete the bug template.

**Comment by DHowett-MSFT** [comment]
That information is very, very important for us to figure out what happened to your Terminal.

**Comment by CaptainMorgans** [comment]
Please reopen this thread so I can get feedback on what is wrong with my terminal program.

**Comment by CaptainMorgans** [comment]
![image](https://user-images.githubusercontent.com/3514724/75824290-ecb07700-5dab-11ea-8015-cdc39b7518b4.png)

This is my current system for consideration to the above reported bug.

**Comment by zadjii-msft** [comment]
Can we get the version of the Terminal that you're running? Perhaps share your `profiles.json`?

**Comment by CaptainMorgans** [comment]
Windows Terminal (Preview)
Version: 0.9.433.0

**Comment by CaptainMorgans** [comment]
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}

**Comment by zadjii-msft** [comment]
And what's your `%PATH%` environment variable set to?

**Comment by CaptainMorgans** [comment]
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\PuTTY\;C:\Users\Captain\AppData\Local\Microsoft\WindowsApps;;C:\Users\Captain\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap

**Comment by CaptainMorgans** [comment]
Any feedback on this issue?
