### ISSUE TITLE
I did it

### ISSUE THREAD

**Issue by wolking** [microsoft/Terminal#480]
![image](https://user-images.githubusercontent.com/12195297/57285406-bd769e00-70e5-11e9-83fd-db8cea7f75c4.png)

**Comment by goroyal** [comment]
Hi @wolking ,

How do you build the application, when I try to run `msbuild OpenConsole.sln`, I always get errors.

**Comment by gotliuyan** [comment]
I always get errors

**Comment by chudovsky** [comment]
@wolking U just run openterminal.exe ? if so, it is not exactly what is needed, as I undestood.
I builded all and get some result as U, but can't deploy cascadia.app, because need update OS version

**Comment by whins** [comment]
I built it too
![wt](https://user-images.githubusercontent.com/2223328/57287053-5cd46a80-70bf-11e9-9596-b6e793b305c3.gif)

**Comment by wolking** [comment]
@whins Yes, just like you

**Comment by wolking** [comment]
win10

**Comment by JinLingChristopher** [comment]
I did it too, but it is just a cmd.exe. what is wrong?
