### ISSUE TITLE
Lines written to the console window sometimes contain carried over text from earlier lines.

### ISSUE THREAD

**Issue by RichardHowells** [microsoft/terminal#4800]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Terminal version: 0.9.433.0
Any other software?
```

# Steps to reproduce

I have a bunch of scripts, that run together, and show the behavior.  I don't have a small repro case.  I can say that when the scripts are run in a stand alone powershell window they work as expected.  When run in a powershell tab in Windows Terminal they misbehave.

# Expected behavior

I expect lines written to the console window to be independent.  

# Actual behavior

I find some later lines in the console window have traces of text that looks to come from earlier lines.  In the attached screenshot the text labelled A is correctly emitted by the script.  The text labelled B is unexpected and looks like a hang over from when A was emitted.

![WindowsTerminalPowershellDisplayBug](https://user-images.githubusercontent.com/6627531/75886023-7c433d80-5e1f-11ea-84f1-deff27a47914.PNG)

**Comment by RichardHowells** [comment]
Hi,

No.  No resizing going on.

**Comment by jdebp** [comment]
Compare #4771.

**Comment by DHowett-MSFT** [comment]
We changed a bit about how we render text and emit screen invalidations in v0.10 -- does this still reproduce for you? We fixed a couple off-by-one errors that resulted in us not clearing the ends of certain lines.

**Comment by RichardHowells** [comment]
Unfortunately I observed this once (screenshot above) and I wasn't able to reproduce it.

I've rerun the relevant script, using v 0.10.781.0, I can't repro that behaviour.

Thank you for your efforts.  I like Terminal.

**Comment by zadjii-msft** [comment]
Awesome, thanks for following up!
