### ISSUE TITLE
Azure Shell can't connect to the internet

### ISSUE THREAD

**Issue by rido-min** [microsoft/terminal#4803]
# Environment

```none
Microsoft Windows [Version 10.0.18363.657]
Windows Terminal version: 0.9.433.0

Any other software? No
```

# Steps to reproduce
Install from store
Open the Azure Cloud Shell

# Expected behavior
Can connect to Azure Cloud Shell

# Actual behavior

Receive the message: `Could not connect to Azure. You may not have internet or the server might be down.`

**Comment by DHowett-MSFT** [comment]
@rido-mn This is, unfortunately, our catch-all error message for "something failed during token exchange". Since you're internal, I can furnish you with a more verbose version ;P
