### ISSUE TITLE
Update AutomationProperties for SplitButton

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4804]
The SplitButton isn't cooperating with me setting the AutomationProperties. I've filed an issue on WinUI [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2064).

Related to...
- #2099 
- #2102

**Comment by DHowett-MSFT** [comment]
This is v1 work, but it could slip because of a dependency.

**Comment by DHowett-MSFT** [comment]
It turns out that this was broken because of something on our side (#5031)
