### ISSUE TITLE
wsl missing option "--list"

### ISSUE THREAD

**Issue by AppFzx** [microsoft/terminal#4808]
# Environment

```none
Windows build number: 
Microsoft Windows [Version 10.0.17763.1039]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

at command prompt, type "wsl --list --all"
# Expected behavior

should list all available distributions

# Actual behavior

Error message "Invalid command line option: --list"
![Capture](https://user-images.githubusercontent.com/6544880/75943822-0629ef80-5e8e-11ea-9da0-be6b5664e2f3.PNG)

**Comment by DHowett-MSFT** [comment]
You forgot the first `-`.

**Comment by DHowett-MSFT** [comment]
Okay, in your _original_ screenshot you left off the first `-`. In your new screenshot, you’re running on 17763 which doesn’t have `--list`...

**Comment by DHowett-MSFT** [comment]
This is in no way a terminal or console issue

**Comment by AppFzx** [comment]
Ok, then it's a documentation issue. I'm on a fresh Win 10 Azure VM fully updated. In what version was --list deprecated?

**Comment by DHowett-MSFT** [comment]
`wsl --list` wasn't deprecated. You're using a version of Windows that predates it even _existing_. You probably want `wslconfig /l` on your version of Windows.

**Comment by ITCTOM** [comment]
I´m using Windows Server 2019 an wsl --list is not working.
I think Microsoft have to update their documentation. your products aren´t working this way. So please invest in quality management.

**Comment by zadjii-msft** [comment]
@ITCTOM Thanks for the feedback, but the place to report something like that would be over at https://github.com/microsoft/wsl 😉
