### ISSUE TITLE
360 prompt virus

### ISSUE THREAD

**Issue by jsoly** [microsoft/Terminal#481]
![image](https://user-images.githubusercontent.com/25276251/57286148-42ae8280-70e7-11e9-8372-795f43de5e2e.png)

**Comment by JalanJiang** [comment]
应该给360提bug？

**Comment by jsoly** [comment]
> 应该给360提bug？

我看行

**Comment by justdoITlkq** [comment]
那儿下载的

**Comment by chitfknc** [comment]
呵呵，这是检测到源码内容了。

**Comment by jsoly** [comment]
> 那儿下载的

就一个 download zip动作

**Comment by ijacksonliu** [comment]
If this is your personal computer,please do not use 360.You are a developers you can solve computer problems by yourself.

**Comment by wolking** [comment]
use git clone

**Comment by evil7** [comment]
# do NOT developing your project when some AV is on. Or you will LOSE some codes at save... delete your codes without alert. easy like ringing finger. Thanos of AV world and maybe released from DC.    ----devDpool xD a joke

**Comment by Domonlee** [comment]
Please kill 360safe.exe, and run **git clone** to get the code.

**Comment by jsoly** [comment]
> # do NOT developing your project when some AV is on. Or you will LOSE some codes at save... delete your codes without alert. easy like ringing finger. Thanos of AV world and maybe released from DC. ----devDpool xD a joke

AV is not exist.. haha

**Comment by evil7** [comment]
> > # do NOT developing your project when some AV is on. Or you will LOSE some codes at save... delete your codes without alert. easy like ringing finger. Thanos of AV world and maybe released from DC. ----devDpool xD a joke
> 
> AV is not exist.. haha

"Anti-Virus" I means. 不是说那个AV熊迪~

**Comment by kateflower** [comment]
I used git clone and received the same virus warning for tools\openps.cmd

**Comment by 10jasper10** [comment]
This is simply a false positive, exclude the programs from your Antivirus and report it as a false positive to your Antivirus provider.

**Comment by xiuluo** [comment]
It is a virus itself.

**Comment by XiLingHost** [comment]
You just need uninstall 360 software and revoke their cert.
https://github.com/chengr28/RevokeChinaCerts

**Comment by DHowett-MSFT** [comment]
Your overactive virus software is not a bug in our code, sorry.

**Comment by sxzz** [comment]
Then uninstall 360 virus.

**Comment by Trumeet** [comment]
Do not use that, 360 is the biggest virus on Windows platform.

**Comment by dangswing** [comment]
Pour some water into your computer.
