### ISSUE TITLE
Crash on closing tab in fullscreen mode

### ISSUE THREAD

**Issue by mayeths** [microsoft/terminal#4810]
Feedback Hub: https://aka.ms/AA7kn4w

## Environment

```none
# Windows build number:

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

# Windows Terminal version (if applicable):

0.9.433.0

```

## Steps to reproduce

- F11 to enter fullscreen mode
- ctrl+shift+space to open a shell (MUST be different to current shell, like powershell to cmd)
- ctrl+tab to switch tab
- ctrl+shift+w to close tab

Then it crash :) This is ok if we don't enter fullscreen mode.

## Expected behavior

Switch between tab correctly.

## Actual behavior

Application crash.

<br/>

---

I don't know whether this may help, but it say `Unhandled exception at 0x00007FFEFCAC600E (TerminalControl.dll) in WindowsTerminal.exe: 0xC000041D` if I choose vs2019 to "debug" after it report something to Microsoft.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! Would you mind filing feedback?

**Comment by mayeths** [comment]
Yes, I have submitted to Feedback Hub above. And what's more?

**Comment by DHowett-MSFT** [comment]
> and paste the link here so we can more easily find your crash information on the back end?

**Comment by mayeths** [comment]
Do you mean https://aka.ms/AA7kn4w ? I pasted it in the first line above.

**Comment by DHowett-MSFT** [comment]
Sorry! I tend to read bugs that follow the template by starting at the headings :smile:

**Comment by mayeths** [comment]
Hope that will help😊

**Comment by DHowett-MSFT** [comment]
Yup, I can reproduce this. _What on earth?_

**Comment by DHowett-MSFT** [comment]
Okay, this is another instance of /dupe #4613
