### ISSUE TITLE
Error starting up after installing PowerShell 7

### ISSUE THREAD

**Issue by fr3dd** [microsoft/terminal#4811]
# Environment
Windows build number: Microsoft Windows [Version 10.0.18362.0]
Windows Terminal version: v0.9.433.0

# Steps to reproduce
Install PowerShell 7 on a system with a working copy of Windows Terminal (Preview) and open a PowerShell Core session.

# Expected behavior
Successfully start a new PowerShell Core session in Windows Terminal (Preview).

# Actual behavior
When starting a new PowerShell Core session, you receive the following error message:

`[error 0x80070002 when launching 'C:\Program Files\PowerShell\6\pwsh.exe']`

This appears to be failing because the installation of PowerShell 7 removes the old directory (C:\Program Files\PowerShell\6) and creates a new one (C:\Program Files\PowerShell\7). In the default profiles.json, the following value called **commandline** needs to be changed from `"C:\\Program Files\\PowerShell\\6\\pwsh.exe"` to `"C:\\Program Files\\PowerShell\\7\\pwsh.exe"`.
The issue can be addressed by updating the value, but many people are not going to be able to figure that out on their own.

**Comment by DHowett-MSFT** [comment]
This is only true if you are using a version of the powershell profile generated before 0.5 (October 2019). Terminal now detects the existence of `pwsh.exe` in a bunch of locations and automatically chooses one. 

If you have an old profile with hundreds of keybindings and full profile blocks, it’s probably a great time to [refresh it](https://www.hanselman.com/blog/NowIsTheTimeToMakeAFreshNewWindowsTerminalProfilesjson.aspx) by deleting it.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! Given that our settings architecture is still evolving, and that this was fixed by circumstance, I’m gonna close it out for now.

**Comment by g0t4** [comment]
This is happening in 1.11. I modified my commandline setting for powershell (not preview) ... setting it to "pwsh.exe -nologo" to hide the banner. If I launch Windows Terminal Preview directly it opens just fine. If however, I use the "app execution  alias" which I have mapped to Windows Terminal Preview and then I open preview via "wt" it breaks:

[error 0x80070002 when launching `pwsh -nologo']

**Comment by DHowett** [comment]
> This is happening in 1.11. I modified my commandline setting for powershell (not preview) ... setting it to "pwsh.exe -nologo" to hide the banner. If I launch Windows Terminal Preview directly it opens just fine. If however, I use the "app execution  alias" which I have mapped to Windows Terminal Preview and then I open preview via "wt" it breaks:
> 
> 
> 
> [error 0x80070002 when launching `pwsh -nologo']
> 
> 
> 
> And, setting the "commandline" to just "pwsh" also breaks it. 
> 
> 

This suggests that the PowerShell installation location is not on your system `PATH`.

**Comment by g0t4** [comment]
Yeah I saw some other red flags, haven't had time to investigate yet. It's
odd that it only happens under some circumstances and not others. I'll do
some more digging and see if maybe it's just a Win 11 Insiders build issue
or otherwise a bug in a Preview build of something (terminal or ps).
