### ISSUE TITLE
Terminal not accepting keyboard input

### ISSUE THREAD

**Issue by keithnyc** [microsoft/terminal#4813]
# Environment

```
Windows build number: 10.0.19569.0
Windows Terminal version: 0.9.433.0
```

# Steps to reproduce
1. Launch Terminal
2. Attempt to type anything

# Expected behavior
Characters show up on the screen.

# Actual behavior
Nothing happens. It's as if I have no keyboard attached.

I tried repairing, resetting, uninstalling / reinstalling (the app), rebooting, but nothing seems to help. Keyboard input works fine in cmd window, just not Terminal.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #4448 for more discussion.

/dup #4448
