### ISSUE TITLE
vertical scrolling is not possible in the current version

### ISSUE THREAD

**Issue by cosm1c-serpent** [microsoft/terminal#4815]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by tukusejssirs** [comment]
This is still true on Win10 Build 18363.720 and Windows Terminal v0.9.433.0.

I cannot scroll using mouse (but I can scroll other windows), I wish I could scroll at least with <kbd>Shift</kbd>+<kbd>PgUp</kbd> and <kbd>Shift</kbd>+<kbd>PgDn</kbd> (I still need to check if there is a keybinding `command` to set the shortcuts for it).

Currently, the only way to scroll the output is using the the mouse clicking of the scrollbar.
