### ISSUE TITLE
Option text (--option) same as background on Solarized Dark theme

### ISSUE THREAD

**Issue by hennievn** [microsoft/terminal#4818]
Using Powershell, and the Solarized Dark theme, any text preceded by, and including a "-" is the same as the background color.  This is assumed to be due to the definition of "background" and "brightBlack" being identical -> #002B36

# Environment

 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
```

# Steps to reproduce

<!-- A description of how to trigger this bug. -->

# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
Visible text, i.e. changing the Solarized Dark "brightBlack" definition to #777777 the text displays as expected
# Actual behavior

<!-- What's actually happening? -->
Text not visible

**Comment by DHowett-MSFT** [comment]
Yeah, the solution here is "we should not have shipped Solarized as a stock theme" moreso than "it is broken"
