### ISSUE TITLE
Microsoft.DesktopBridge.props not found 

### ISSUE THREAD

**Issue by Wid-Mimosa** [microsoft/Terminal#482]
I use visual studio 2017.
“C:\Program Files (x86)
       \Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props” is not found.

**Comment by gokulraja** [comment]
Similar issue for reference
C:\mydesktop\projects\git\Terminal>C:\tools\nuget restore OpenConsole.sln
MSBuild auto-detection: using msbuild version '16.0.461.62831' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'.
C:\mydesktop\projects\git\Terminal\src\wap-common.build.pre.props(40,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\mydesktop\projects\git\Terminal\src\cascadia\CascadiaPackage\CascadiaPackage.wapproj]
C:\mydesktop\projects\git\Terminal\src\wap-common.build.pre.props(40,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\mydesktop\projects\git\Terminal\pkg\appx\OpenConsolePackage.wapproj]

**Comment by SerialSmile** [comment]
Try to install UWP development tools.

**Comment by zadjii-msft** [comment]
@SerialSmile is correct.

See https://github.com/microsoft/Terminal#prerequisites on the README
