### ISSUE TITLE
Screen turns to black for ~1s when launching Terminal

### ISSUE THREAD

**Issue by mrtolkien** [microsoft/terminal#4822]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal (Preview)
Version: 0.9.433.0

GPU:
RTX 2080 Super

Drivers:
GeForce Game Ready Driven v442.50
```

# Steps to reproduce

Launch Terminal after rebooting Windows.

# Expected behavior

Terminal launches without any hiccups.

# Actual behavior

The screen it starts on turns to black for about 1s before coming back to normal with no error message. Happened on every reboot for the last week.

**Comment by anyoun** [comment]
I've noticed a similar issue. If I leave Terminal running when I hibernate the machine, the first time I bring Terminal into the foreground after waking the machine up, the entire screen flashes black for about a second.

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version: 0.10.781.0

GPU: Geforce GTX 1080
Drivers: v445.75
```

**Comment by DHowett-MSFT** [comment]
The screen turning black sounds like a video card TDR. Would you mind sharing feedback?

**Comment by mrtolkien** [comment]
I have sent the issue through the feedback hub but have not found a way to get the link to send back here.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/78046195-77997880-733c-11ea-9ecd-a02f08d65058.png)

@mrtolkien ^ This button ^ will give you an `aka.ms` link you can share that we can use to look up your crash
