### ISSUE TITLE
Inconsistent  Font attribute 

### ISSUE THREAD

**Issue by pmahend1** [microsoft/terminal#4824]
Font looks bold and blurry on windows terminal

# Environment

```none
Windows build number: 
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): 0.9.433.0

Any other software?
Powershell-Core
```

# Steps to reproduce

None

# Expected behavior
Font should not be bold on Windows-Terminal by default 

# Actual behavior
Font is bold and looks thick.

![image](https://user-images.githubusercontent.com/21352870/76096199-afa6d900-5f93-11ea-8f0a-f381db7de6f8.png)

**Comment by zadjii-msft** [comment]
Could you share your `profiles.json` file? I'm looking specifically for the font face, size your using, and the antialiasing mode. It's possible we're just picking a heavier weight for that particular font than conhost does, but it might also just be differences between the GDI (conhost) renderer and the DX (terminal) renderer.

**Comment by pmahend1** [comment]
@zadjii-msft 

```json

{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "profiles":
    {
        "defaults":
        {
            "colorScheme": "Campbell"
        },
        "list":
        [
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false

            },
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "background": "#0C0C0C",
                "foreground": "#8CC5DB"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    "schemes": [],
    "keybindings": []
}
```

**Comment by zadjii-msft** [comment]
Okay so you've basically made no modifications to the font. _In general_ font size 10 in the vintage console is going to be smaller than 10 is in the Terminal. It looks to me like the font isn't actually bold, it's just _bigger_. If I just naively resize the text on the right to be the same width/height as the text on the left, the fonts look like roughly the same weight to me:
![image](https://user-images.githubusercontent.com/18356694/76110500-3f548380-5fa4-11ea-9ca3-1a4ae9c76f86.png)

(+/- some corruption from just resizing in mspaint)
