### ISSUE TITLE
Incorrect vertical snapping with `showTabsInTitlebar = false`

### ISSUE THREAD

**Issue by 1kjo** [microsoft/terminal#4827]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): master (3953b71d)

Any other software? no
```

# Steps to reproduce

Set `showTabsInTitlebar = false` in config and try to resize the window.

![test](https://user-images.githubusercontent.com/56923875/76111442-91b39580-5fe0-11ea-8706-c74b7016b0c6.gif)

# Expected behavior

Window height correctly "snaps" to terminal lines.

# Actual behavior

Window height doesn't "snap" exactly to terminal lines.

**Comment by DHowett-MSFT** [comment]
I'd love to fix this, but I don't have engineering resources before version 1.0. :smile: Triaged, backlog.

**Comment by DHowett-MSFT** [comment]
Help-wanted, though, too-- if somebody wanted, we would 100% take this in for 1.0

**Comment by lhecker** [comment]
I'll close the issue for now then. We'll see if it comes back. Thanks!
