### ISSUE TITLE
 Cannot open include file: 'atlbase.h': build failed

### ISSUE THREAD

**Issue by CanoeFZH** [microsoft/Terminal#483]
"D:\Terminal\openconsole.sln" (default target) (1) ->
"D:\Terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"D:\Terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"D:\Terminal\src\tsf\tsf.vcxproj" (default target) (18) ->
(ClCompile target) ->
  d:\terminal\src\tsf\precomp.h(26): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory [D:\Terminal\src\tsf\tsf.vcxproj]

**Comment by pulimento** [comment]
You need to install the ATL libs corresponding to your build tools version

![image](https://user-images.githubusercontent.com/503313/57287962-d9b01600-70b8-11e9-8a43-2f28537132fd.png)

**Comment by CanoeFZH** [comment]
> You need to install the ATL libs corresponding to your build tools version
> 
> ![image](https://user-images.githubusercontent.com/503313/57287962-d9b01600-70b8-11e9-8a43-2f28537132fd.png)

Any details to help newbies to set up these ATL libs?

**Comment by lrssnn** [comment]
In Visual Studio, you can go to Tools->Get Tools and Features, which will open the Visual Studio Installer. From there you can click the Modify button for your Visual Studio version, then go to the Individual Components tab at the top. The C++ ATL components are in the section titled "SDKs, libraries, and frameworks" which is the last section in my list at least.

Fair warning, I had to install the V141 versions to get the atlbase error to go away, not the V142 versions in the picture.

**Comment by zadjii-msft** [comment]
I'm gonna redirect further discussion on this topic to #489, which is the build problems megathread
