### ISSUE TITLE
Clear screen 

### ISSUE THREAD

**Issue by demongodYY** [microsoft/terminal#4833]
I want to know is there any shortcut to clear screen?  Like cmd+ R on Mac, or ctrl + L on Linux.

**Comment by j4james** [comment]
That's a feature of the shell rather than the terminal itself. If you're using Powershell or a WSL bash shell, then <kbd>Ctrl</kbd>+<kbd>L</kbd> should clear the screen. I don't think the cmd shell has an equivalent shortcut though.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by a bunch of issue on our repo - please refer to the following threads for more discussion:

/dup #2832
/dup https://github.com/microsoft/terminal/issues/1882#issuecomment-510468487
/dup #1193
