### ISSUE TITLE
How compile it using windows 7 Ultimate x86

### ISSUE THREAD

**Issue by icoder-new** [microsoft/terminal#4834]
I want to compile it using **_Windows 7 Ultimate x86_**!! Can I or Not please help me!!

>     ¯\_(ツ)_/¯

**Comment by j4james** [comment]
For instructions on how to build the project, have a look at the [Developer Guidance](https://github.com/microsoft/terminal#developer-guidance) on the home page.

Quoting from the _Prerequisites_ section:
> You must be running Windows 1903 (build >= 10.0.18362.0) or later to run Windows Terminal

**Comment by DHowett-MSFT** [comment]
This project is not intended for use on Windows 7.
