### ISSUE TITLE
Copy Paste not working

### ISSUE THREAD

**Issue by GarvGoyal7** [microsoft/terminal#4835]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

The copy paste is not working when we use the command ctrl+v in command.
![Screenshot (5)_LI](https://user-images.githubusercontent.com/48591733/76140997-3e941e00-6086-11ea-9032-2de5175b4176.jpg)

# Expected behavior

It is expected that the command that you copies will be pasted in the terminal windows

# Actual behavior

Instead of pasting the command that you copied, the terminal is showing  ^V

**Comment by j4james** [comment]
See issue #3058.

**Comment by zadjii-msft** [comment]
Thanks for the report! As @j4james mentioned, this is actually already being tracked by another issue on our repo - please refer to #3058 for more discussion.

/dup #3058
