### ISSUE TITLE
White border around window

### ISSUE THREAD

**Issue by itsandreramon** [microsoft/terminal#4837]
The Windows Terminal has a white border around it. This does not happen with other apps on Windows 10 (e.g. Settings) as they have a colored / grey window border.

# Environment

```none
Windows build number: 10.0.18363
Windows Terminal version (if applicable): 0.9.433.0
```

# Expected behavior
<img src="https://i.imgur.com/N7cEBdT.jpg"/>

# Actual behavior
<img src="https://i.imgur.com/4hLLGqz.jpg"/>

**Comment by michalhudecek** [comment]
This issue was not fixed. Compare the terminal with other Microsoft apps in the light mode:
https://github.com/microsoft/terminal/issues/3425#issuecomment-646283849

**Comment by cloudhan** [comment]
I am currently facing the same issue.

The 1px border is just so fucking ugly, no matter what the fuck color it is!
