### ISSUE TITLE
Is there a Windows Terminal .ico file available somewhere?

### ISSUE THREAD

**Issue by damienbutt** [microsoft/terminal#4840]
Is this available anywhere in the package?

**Comment by j4james** [comment]
You probably want the _terminal.ico_ file in the _res_ directory.
https://github.com/microsoft/terminal/tree/master/res

**Comment by zadjii-msft** [comment]
There's also all the image files for the icon in `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_<application version>_x64__8wekyb3d8bbwe\Images` when you install the Terminal. They're all .png's, but if you _need_ the ico you can always use the one @j4james mentioned.
