### ISSUE TITLE
Unicode redirection results in empty file

### ISSUE THREAD

**Issue by bsld** [microsoft/terminal#4841]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal (Preview)
Version: 0.9.433.0

Consider the following example C program (use MSVC to compile):

```
main() {
AllocConsole();
WriteConsoleW(GetStdHandle(STD_OUTPUT_HANDLE), L"\x1F600\x1F600\x1F600", 3, NULL, NULL);
}
```

Run:

`./program | Out-File -Encoding Unicode -LiteralPath ./out.txt`

I expect to get an UTF-16 encoded text file I can somehow open with WordPad or maybe a web browser and get three smiles.

An empty file.

**Comment by DHowett-MSFT** [comment]
You are explicitly calling _WriteConsole_, which is an API that only works if your output handle is a console. Since you’ve redirected it to either a file or a pipe, it’s not a console.
