### ISSUE TITLE
The terminal process terminated with exit code: 2147516566

### ISSUE THREAD

**Issue by Candelit** [microsoft/terminal#4843]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): PowerSHell extension 2020.3.0 (Just updated)

Any other software?
```

# Steps to reproduce
Update to 2020.3.0, reboot VS code, bam!

Load a PowerShell script file (*.ps1) into VS code.
# Expected behavior
Load PowerShell extension, start terminal
Downgrading to 2020.1.0 solved the issue...

# Actual behavior
AN error pop upp, a small 'one line windows' in the bottom right corner, an orange X and the error: 'The terminal process terminated with exit code: 2147516566'

**Comment by zadjii-msft** [comment]
Wait is this an issue with a VS Code extension? This probably belongs on the issue tracker for that extension, not here. This is the issue tracker for the Windows Terminal and the inbox Windows Console.

Maybe this would be a better repo? https://github.com/powershell/vscode-powershell
