### ISSUE TITLE
CRT effect bleeds from right side when terminal window padded

### ISSUE THREAD

**Issue by idlelimey** [microsoft/terminal#4844]
# Environment

```none
Windows build number: Windows 10 1909 18363.657
Windows Terminal version (if applicable): 0.9.433.0
Any other software? No.
```

# Steps to reproduce
Use the following settings and then run a new tab.
```
        {
            "useAcrylic": true,
            "acrylicOpacity" : 0.9,
            "experimental.retroTerminalEffect": true,
            "background": "#000",
            "foreground": "#ffffff",
            "fontFace": "Cascadia Code",
            "fontSize": 10,
            "padding": "40",
            "cursorColor" : "#a4d816",
            "cursorShape": "filledBox"
        }
```

# Expected behavior
CRT effect should not bleed in from the right.  See screenshot.

# Actual behavior
Notice that the blur from the CRT effect bleeds in from the right hand side of the terminal window.

Not the end of the world but worth pointing out.  I suspect this is due to the padding on the tab window.

![image](https://user-images.githubusercontent.com/10774334/76196723-a52e4e80-61e2-11ea-9342-0e2330530b51.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This one's actually already fixed in master, but hasn't been pushed out quite yet. This is being tracked by #4362, and was fixed in #4716

/dup #4362
