### ISSUE TITLE
Write version number in "What's new in this version" of Windows Store

### ISSUE THREAD

**Issue by BusyJay** [microsoft/terminal#4846]
# Description of the new feature/enhancement

Write a short introduce and latest version number in "What's new in this version" of Windows Store.

# Proposed technical implementation details (optional)

Windows Store doesn't show App's version number or last update time [due to no obvious reason](https://answers.microsoft.com/en-us/windows/forum/all/where-can-i-find-app-version-and-last-update-date/9a4a26bc-6c12-4d7b-a2a6-bf5a9abfeec4). When I try to install Windows Terminal from the store, I can only see the release date of the app is 6/21/2019. It makes me doubt if the version in the store is latest.

It will be very helpful to include a short descriptions and current version number in "What's new in this release", so users like me can know if it's actively maintained easily and whether to install from Github release page instead.

It maybe off the topic as it's not caused by your (awesome) app. Sorry to bother, but it's certainly an issue to the new users.

**Comment by DHowett-MSFT** [comment]
Oh, gladly. I forgot that the store doesn’t show the version in any prominent place. Thanks!

**Comment by DHowett-MSFT** [comment]
I’m assigning myself with the note, “put this into our release engineering documentation.” After that, I’ll close this out.

**Comment by DHowett-MSFT** [comment]
This is done as of 0.10. Thanks!
