### ISSUE TITLE
Touchpad scrolling is way too fast

### ISSUE THREAD

**Issue by saschanaz** [microsoft/terminal#4847]
# Environment

```none
Windows build number: 19041
Windows Terminal version (if applicable): 0.9.443.0

Any other software?
```

# Steps to reproduce

Scroll with touchpad on Surface Pro 7

# Expected behavior

A swipe should scroll a few lines

# Actual behavior

A swipe instead scrolls a few pages

**Comment by DHowett-MSFT** [comment]
/dup #1066 which is fixed for 0.10
