### ISSUE TITLE
Have saw many build/run environment issues, collect them here.

### ISSUE THREAD

**Issue by CanoeFZH** [microsoft/Terminal#485]
rt

**Comment by CanoeFZH** [comment]
[Cannot open include file: 'atlbase.h': build failed](https://github.com/microsoft/Terminal/issues/483)

**Comment by CanoeFZH** [comment]
[Platform='ARM64' build failed.](https://github.com/microsoft/Terminal/issues/477)

**Comment by wangshubo** [comment]
build sln using vs2017, there is no errors. but i cannot execute any exe. i do not know how to do it then.

**Comment by CanoeFZH** [comment]
[Built Windows Terminal asserts with an abort() ](https://github.com/microsoft/Terminal/issues/426)

**Comment by computerline1z** [comment]
after build, I run OpenConsole, but it not difference from the orignal cmd, does it need to build another project 
![image](https://user-images.githubusercontent.com/2786420/57291204-2f9cb200-70e9-11e9-8112-17940a157d32.png)

**Comment by wujysh** [comment]
@computerline1z Try `Ctrl+T`?

**Comment by wangshubo** [comment]
can not open atls.lib

**Comment by sagood** [comment]
![image](https://user-images.githubusercontent.com/1913817/57292496-1f251100-70c2-11e9-838f-ac44ab1eac3e.png)

**Comment by bozax** [comment]
Only can run in 1903?

**Comment by wujysh** [comment]
@bozax
Yeah, at least 1903 (10.0.18362).

**Comment by EnterpriseBCMe** [comment]
Can't open include file: “winrt/Microsoft.Terminal.Settings.h”: No such file or directory	TerminalCore	c:\github\terminal\src\cascadia\terminalcore\terminal.cpp	13
This error happens when i try to deploy the solution
And also
Can't open input file “C:\GitHub\Terminal\bin\x64\Release\TerminalCore.lib”	UnitTests_TerminalCore	C:\GitHub\Terminal\src\cascadia\UnitTests_TerminalCore\LINK	1

**Comment by YottaByte090** [comment]
> 
> 
> Can't open include file: “winrt/Microsoft.Terminal.Settings.h”: No such file or directory TerminalCore c:\github\terminal\src\cascadia\terminalcore\terminal.cpp 13
> This error happens when i try to deploy the solution
> And also
> Can't open input file “C:\GitHub\Terminal\bin\x64\Release\TerminalCore.lib” UnitTests_TerminalCore C:\GitHub\Terminal\src\cascadia\UnitTests_TerminalCore\LINK 1

Try this.
https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264

**Comment by kdimiche** [comment]
```
...
FinalizeBuildStatus:
  Deleting file "x64\Release\TerminalApp.tlog\unsuccessfulbuild".
  Touching "x64\Release\TerminalApp.tlog\TerminalApp.lastbuildstate".
Done Building Project "C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj" (default targets).

Done Building Project "C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj.metaproj" (default targets).
Done Building Project "C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\Users\kdimi\projects\community\microsoft\Terminal\OpenConsole.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\kdimi\projects\community\microsoft\Terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj.metaproj" (default target) (45) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj.metaproj" (default target) (46) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj" (default target) (47) ->
(Link target) ->
  XamlTypeInfo.g.obj : warning LNK4197: export 'DllGetActivationFactory' specified multiple times; using first specification [C:\Users\kdimi\projects\community\microsoft\Terminal\src\cascadia\TerminalApp\T
erminalApp.vcxproj]


"C:\Users\kdimi\projects\community\microsoft\Terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"C:\Users\kdimi\projects\community\microsoft\Terminal\src\tsf\tsf.vcxproj" (default target) (18) ->
(ClCompile target) ->
  C:\Users\kdimi\projects\community\microsoft\Terminal\src\tsf\precomp.h(26): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory [C:\Users\kdimi\projects\community\microsof
t\Terminal\src\tsf\tsf.vcxproj]

    1 Warning(s)
    1 Error(s)
```

**Comment by zadjii-msft** [comment]
I'm gonna direct all build-related problems to #489
