### ISSUE TITLE
Cannot run the Windows terminal

### ISSUE THREAD

**Issue by CaptainMorgans** [microsoft/terminal#4851]
# Environment

Windows 10 Home (build 1909)
Microsoft Windows [Version 10.0.18363.693]

PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\PuTTY\;C:\Users\Captain\AppData\Local\Microsoft\WindowsApps;;C:\Users\Captain\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files **(x86)\Nmap**

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Open Windows Terminal (Preview) from Start menu

# Expected behavior

I expect that command prompt in powershell within the Windows Terminal window, however a pop up box appears with an error that the application was unable to start correctly. See screenshot below for the actual error.

# Actual behavior

![image](https://user-images.githubusercontent.com/3514724/76252747-03dee100-6252-11ea-84f4-986b234689a5.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the report. This is a /dup of #4795
