### ISSUE TITLE
Retain font-size and opacity changes made in terminal window

### ISSUE THREAD

**Issue by abhijeetviswam** [microsoft/terminal#4855]
# Description of the new feature/enhancement
Any changes to font-size and acrylic opacity done from the terminal window using ctrl/shift hotkeys+mouse scroll gesture need to be made persistent.

In the existing implementation, any changes in font size or opacity made while using the terminal window and not explicitly changed in profile.json is not being retained. I think it would be more user friendly if the user preferences are retained without explicit change in settings.

**Comment by zadjii-msft** [comment]
This is pretty close to the following discussions:

#766
#1056
#961

Though, none of them call out specifically persisting window state like this automatically. I'm wondering if there's one that this should be merged in with, or if we should leave this open as it's own unique discussion 🤔

**Comment by DHowett-MSFT** [comment]
I think this is best considered a feature of /dup #1056, honestly. Being able to take the "current active" settings and positively confirm committing them somewhere would really seal the deal.
