### ISSUE TITLE
default font isn't as sharp as default ubuntu shell font

### ISSUE THREAD

**Issue by fishzle** [microsoft/terminal#4858]
The black background is wt 0.9.433.0
The brown background is ubuntu shell in windows 10 rel 1909.

![image](https://user-images.githubusercontent.com/8211862/76265438-9dd97480-62b8-11ea-98bd-0fe4f2da10ad.png)

**Comment by DHowett-MSFT** [comment]
This is a combination of things, but it just boils down to text rendering being different and that it should be configurable--I'm going to say it's a /dup of #1790
