### ISSUE TITLE
When I run Windows Terminal as admin cannot start WSL

### ISSUE THREAD

**Issue by svpudik** [microsoft/terminal#4863]
# Environment
OS version: 10.0.18362 N/A Build 18362
Windows Terminal version (if applicable):0.9.433.0

Any other software?
WSL

# Steps to reproduce

run windows terminal as admin

# Expected behavior
ability run WSL in same window as powershell

# Actual behavior
WSL is visible when i start Windows terminal as standard user but when I start it as Administrator WSL is not visible in menu.

**Comment by DarthJahus** [comment]
OS version: 19041.113 (Insider Slow)
Windows Terminal version: 0.9.433.0

I am unable to reproduce this issue. When I run WT as administrator, Ubutnu-18.04 is visible and usable.
![image](https://user-images.githubusercontent.com/7353366/76305227-0dedf780-62c5-11ea-94da-071c9b66d519.png)

**Comment by zadjii-msft** [comment]
@svpudik Are you maybe using another user account to elevate the Terminal? Or are you using the currently logged-in user?

If you try running WSL manually in an admin Windows Terminal instance, does that still work? What's the output of `wsl -l` in both an unelevated and an elevated Windows Terminal window?

**Comment by pc-v2** [comment]
i can't launch it with Search > wt with run as administrator

**Comment by svpudik** [comment]
I am running admin as logged user.
here is screen ad admin: 
![image](https://user-images.githubusercontent.com/32640971/76709323-4135e980-66fe-11ea-85cf-eb7533ba4488.png)
screen without admin:
![image](https://user-images.githubusercontent.com/32640971/76709327-4c891500-66fe-11ea-80d3-ab79929e51ba.png)
screen of  `wsl -l` ad admin have not enough priviledges:
![image](https://user-images.githubusercontent.com/32640971/76709353-73474b80-66fe-11ea-924a-1da2adeecaf6.png)
What I have to modify to provide there admin access?
here is my config
`uid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"`

**Comment by zadjii-msft** [comment]
That's certainly curious. @benhillis @craigloewen-msft any ideas why the user might not be able to see any linux distros while they're running as admin?

**Comment by DHowett-MSFT** [comment]
This may need to be filed on [the WSL repository](https://github.com/microsoft/wsl). Sorry!
