### ISSUE TITLE
Convert Windows style path to a unix style path when pasting in WSL

### ISSUE THREAD

**Issue by abhijeetviswam** [microsoft/terminal#4865]
# Description of the new feature/enhancement
On pasting windows style path (C:\Program Files\Git) in WSL profile, it should automatically be converted to unix style WSL path (/mnt/c/Program Files/Git)
This is a feature already available in cmder terminal emulator which I miss in Windows Terminal

# Proposed technical implementation details (optional)
WSL provides the "wslpath" utility which does just this. I'm not sure how feasible it is, however I'm thinking if we can listen to paste events when in WSL profile, we could identify the argument as a windows style and pass it to the wslpath utility.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1772 for more discussion.

/dup #1772
