### ISSUE TITLE
Windows Terminal should support right-click copy & paste for PowerShell (MobaXterm on Windows does)

### ISSUE THREAD

**Issue by jdrch** [microsoft/terminal#4866]
# Description of the new feature/enhancement

Support inline right-click copy and paste for PowerShell. Although this *may* be an issue specific to PowerShell, MobaXTerm on Windows supports it just fine, so either PowerShell or Windows Terminal is doing something wrong.

# Proposed technical implementation details (optional)

I'm unfamiliar with the code, so I'm not sure how it would be done.

**Comment by zadjii-msft** [comment]
Could you clarify? The Windows Terminal _should_ already support right-click for copy and paste... Does this not work for you currently? What version of the Terminal are you running?

**Comment by jdrch** [comment]
The latest release. I guess I'm expecting a right-click context menu within the app like what I get in MobaXterm (also Windows) or Konsole in KDE on Linux.

**Comment by zadjii-msft** [comment]
Ahhh, okay, I think you're looking for #3337, and maybe #1553 is related as well. Right now we just copy by default, but there's been discussion to may that configurable, so the user could open a dropdown menu instead.

/dup #3337

**Comment by jdrch** [comment]
@zadjii-msft OK fair enough. I'll get on that original bug then. Thanks!
