### ISSUE TITLE
Make ConPty understand more types of input

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4873]
Work item introduced by #4856.

For now, as long as conpty can parse AppKeys and some mouse events, we don't need to turn input passthrough off. Since the VT is only passed through if the app is ready for it (denoted by `ENABLE_VIRTUAL_TERMINAL_INPUT`), we stop the VT Input at InputStateMachineEngine. So it should be OK. Not ideal, but it works.

_when we fix this, revert or remove the fix for #4911_

**Comment by DHowett-MSFT** [comment]
Triaged into Console Backlog.

**Comment by DHowett-MSFT** [comment]
When we fix this, revert the fix for #4911.
