### ISSUE TITLE
The split-pane subcommand has a --target\-t parameter

### ISSUE THREAD

**Issue by wayne-scott** [microsoft/terminal#4878]
The [split-pane](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#split-pane) section in the [UsingCommandlineArguments](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) document says that there is a `[--target,-t target-pane]` parameter.  However if you try to use it you get a windows error box stating "The following argument was not expected: -t".

I've not looked into the code base in great detail, but from looking at [this](https://github.com/microsoft/terminal/blob/b6ec670bd8cf8ac7f6f7e67ac28a0210ba56b2c8/src/cascadia/TerminalApp/AppCommandlineArgs.cpp#L193) section I'm assuming that this parameter hasn't been implemented yet.

**Comment by zadjii-msft** [comment]
You're absolutely right that this hasn't been implemented yet. I copy-pasta'd that section from the spec, then forgot to remove that arg. 🤦‍♂ 

Thanks for catching this!

**Comment by wayne-scott** [comment]
@zadjii-msft, just a quick followup question.  I want to keep track of when this will be implemented but couldn't find an issue to follow.  The best I could find was #4632, but it didn't mention this particular parameter.  Can you point me in the right direction?

**Comment by HSVAdam** [comment]
Has this made it into the preview package?  I still have this exact same problem on a fresh new install of Windows 10.
