### ISSUE TITLE
Light theme is not supported well?

### ISSUE THREAD

**Issue by learning** [microsoft/terminal#4882]
# Environment

```none
Windows build number: 10.0.18363.657
Windows Terminal version (if applicable): 0.9.433.0

Any other software?
1. Debian Linux (WSL)
2. fish shell

```

# Steps to reproduce
Use ColorTool convert this [Github style iTerm2 color theme](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Github.itermcolors), and add it to Windows Terminal

My color scheme in Windows Terminal:
```
{
    "name": "github",
    "black":"#3e3e3e",
    "blue":"#003e8a",
    "green":"#07962a",
    "cyan":"#89d1ec",
    "red":"#970b16",
    "purple":"#e94691",
    "yellow":"#f8eec7",
    "white":"#ffffff",
    "brightBlack":"#666666",
    "brightBlue":"#2e6cba",
    "brightGreen":"#87d5a2",
    "brightCyan":"#1cfafe",
    "brightRed":"#de0000",
    "brightPurple":"#ffa29f",
    "brightYellow":"#f1d007",
    "brightWhite":"#ffffff",
    "foreground":"#3e3e3e",
    "background":"#ffffff",
    "selectionBackground": "#ffa29f"
}
```

# Expected behavior

Just like iTerm2 in macOS

<img width="962" alt="macos" src="https://user-images.githubusercontent.com/354626/76388975-4fee6a80-63a5-11ea-87fb-18f8a7be6250.png">

# Actual behavior

Some text is in white, the same color with background
![windows](https://user-images.githubusercontent.com/354626/76389030-5c72c300-63a5-11ea-902a-084e25740ae9.png)

**Comment by learning** [comment]
Not only the Node.js+webpack, it goes crazy when I use fish shell.

![wt](https://user-images.githubusercontent.com/354626/76389990-85945300-63a7-11ea-8b27-376837a0f2f5.gif)

**Comment by hanubeki** [comment]
Could be #293 and/or #2661

**Comment by zadjii-msft** [comment]
I'm just reposting the theme here so you can preview the colors here

<details>
<summary>Color sheme</summary>


"name": ` "github",`
"black":  `#3e3e3e`,
"blue":  `#003e8a`,
"green":  `#07962a`,
"cyan":  `#89d1ec`,
"red":  `#970b16`,
"purple":  `#e94691`,
"yellow":  `#f8eec7`,
"white":  `#ffffff`,
"brightBlack":  `#666666`,
"brightBlue":  `#2e6cba`,
"brightGreen":  `#87d5a2`,
"brightCyan":  `#1cfafe`,
"brightRed":  `#de0000`,
"brightPurple":  `#ffa29f`,
"brightYellow":  `#f1d007`,
"brightWhite":  `#ffffff`,
"foreground":  `#3e3e3e`,
"background":  `#ffffff`,
"selectionBackground": ` `#ffa29`

</details>

I'd bet that this was #293, but I'm not seeing this orange color
![image](https://user-images.githubusercontent.com/18356694/76419657-b7d58e80-636e-11ea-8b14-33e5fef9feaf.png)

anywhere in that scheme. Maybe you could edit the foreground, white, or brightWhite colors, to see if text is getting printed in any of those colors at all?

**Comment by DHowett-MSFT** [comment]
But given that you do have working black text, I believe this is because the application is _explicitly requesting_ "white". It's also correct that you have not specified that orange color in this color scheme. Perhaps that's what you should put in place of White?

**Comment by DHowett-MSFT** [comment]
Oh, @zadjii-msft, this is actually because we don't have "bold foreground" (color 19)... eeeeee

**Comment by learning** [comment]
> 
> 
> I'm just reposting the theme here so you can preview the colors here
> Color sheme
> 
> I'd bet that this was #293, but I'm not seeing this orange color
> ![image](https://user-images.githubusercontent.com/18356694/76419657-b7d58e80-636e-11ea-8b14-33e5fef9feaf.png)
> 
> anywhere in that scheme. Maybe you could edit the foreground, white, or brightWhite colors, to see if text is getting printed in any of those colors at all?

Yes, I have tried to adjust foreground color for the **fish** and **webpack**, but it turns unreadable elsewhere, like **ls**, **vim** or **git**, the daily tools.

**Comment by DHowett-MSFT** [comment]
Thanks everyone for your input here. Now that we know the root cause, I'm going to refer to the new issue filed to track it. /dup #5682.
