### ISSUE TITLE
Ctrl+Shift+C dont working...

### ISSUE THREAD

**Issue by neygomon** [microsoft/terminal#4883]
Hello.
I had a problem with this Windows Terminal, namely, the Ctrl + Shift + C key combination refuses to work to copy the selected text.

In profiles.json, I tried adding `{"command":"copy","keys": ["ctrl+shift+c"]}` to the keybindings, it did not help.
Default.json also contains this shortcut, but it doesn’t work.

At the same time, Ctrl + Shift + V on paste works.
And Ctrl + Ins works on copying, as it is written in default.json

```
Microsoft Windows [Version 10.0.19577.1000] Insider Preview
Windows Terminal (Preview) Version: 0.9.433.0
```

This key combination is important to me, because I have to work mainly on Linux and am already used to this kind of copying behavior.

**Comment by DHowett-MSFT** [comment]
Interesting! What keyboard layout are you using on your computer?

**Comment by neygomon** [comment]
RUS and ENG

**Comment by neygomon** [comment]
Help, please...
I thought that some software intercepts this combination, but I even reinstalled Windows and checked the software without any installation, it still does not respond to copying ...

**Comment by neygomon** [comment]
I solved this problem!

In AMD RADEON SOFTWARE exist hot keys with combo Ctrl+shift (one is ctrl+shift+c)
For fix this problem go to:
amd radeon software -> settings -> shortcuts - > change cameras (or search by combo ctrl+shift+c) -> click this item and press DELETE for disable shortcut

Have fun!

**Comment by zadjii-msft** [comment]
Wow very interesting! Thanks for following up, it's the _absolute worst_ when people solve a problem and don't post the solution online. 

Since this is resolved for you, we're going to close this issue. Thanks!
