### ISSUE TITLE
FR: Marks for easy navigation like Terminal.app

### ISSUE THREAD

**Issue by jkuebart** [microsoft/terminal#4884]
# Description of the new feature/enhancement

I would really like to see a feature I use heavily when working on the command line in Terminal.app on macOS: marks.

When pressing enter, the current line is automatically »marked«. Visually, this is indicated by little brackets on the side of the line – but that's not the interesting/useful part: subsequently, it's possible to navigate between these lines using Command-↑ and Command-↓, among other things. The marked lines scroll into view, making it very convenient to navigate the terminal's back buffer.

This is very useful when programs produce long outputs, such as the debugger lldb: simply press Command-↑ and you see the top of the list and can then scroll back down using scroll bars, mouse wheel, whatever…

Another really nice feature is Command-Shift-A which selects the text up to the most recently marked line: for example, one can simply type »ls« enter, Command-Shift-A Command-C, which selects the output of the command and copies it to the clipboard.

# Proposed technical implementation details (optional)

I have no idea how it could be implemented in practice, but it doesn't feel like a very big feature. I think that the visual feedback is secondary, just marking a line automatically after hitting enter already covers 99% of use cases.

The most important keyboard shortcuts are »up« and »down« to scroll the back buffer between the marks. The second most important shortcut is to select from the current position to the most recent mark, but even that could be implemented as a second step.

Terminal.app has more features such as marking manually, bookmarks &c which I have never used, so seems comparatively unimportant.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1527 for more discussion.

/dup #1527

**Comment by DHowett-MSFT** [comment]
There's no explicit note about inserting a mark when you press <kbd>Enter</kbd> in that bug, but it _does_ mention prompt positions so I believe it's sufficient. Thanks!

**Comment by jkuebart** [comment]
@DHowett-MSFT I briefly looked at #1527 but that looked like it's just about visual cues on the scrollbar rather than navigation shortcuts. I see now that keyboard bindings *are* mentioned in a comment, so I'm taking the liberty to add my suggestions on that ticket as well.
