### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by Robylyon93** [microsoft/terminal#4886]
Windows build number: 18363.693
Windows Terminal version (if applicable): 0.9.433.0

Sometimes, Windows Terminal takes a few seconds (3+) to startup. During this time it seems like freezed. Before displaying the actual name of the terminal in the taskbar (e.g.: Windows Powershell), it shows "DesktopWindowsXa...".
![image](https://user-images.githubusercontent.com/9963021/76399997-e27c1300-637f-11ea-82ba-96f7c2c9d3d4.png)

I'm not able to reproduce this consistently, since other times it just starts as fast as a normal powershell.

**Comment by DHowett-MSFT** [comment]
This might be crazy, but.. if you just start WSL does it take a long time sometimes? Outside of Terminal.

There's a moment during Terminal's startup where we ask WSL a question (so this might be #3987)

**Comment by Robylyon93** [comment]
Oh, now that I think about it, yes it does from time to time.

Thanks!

**Comment by DHowett-MSFT** [comment]
Great! Thanks for confirming. /dup #3987
