### ISSUE TITLE
pwsh in Azure Cloud shell halts and returns to bash

### ISSUE THREAD

**Issue by breasor** [microsoft/terminal#4891]
# Environment

```none
Windows build number:  10.0.19041.0
Windows Terminal version (if applicable):  0.9.433.0

Any other software?
```

# Steps to reproduce

Open Azure Cloud Shell
login
launch pwsh 
wait

# Expected behavior

launch pwsh 7 core in azure cloud shell like I would from shell.azure.com

# Actual behavior

![image](https://user-images.githubusercontent.com/2437845/76456915-37cf1900-63ae-11ea-8b8c-1e52ec356580.png)

**Comment by DHowett-MSFT** [comment]
/dup #2267 (same root cause, but also exacerbated by https://github.com/PowerShell/PSReadLine/issues/1376)
