### ISSUE TITLE
Cannnot use sftp

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [microsoft/terminal#4893]
Hi folks !

I've came across an unexpected issue when trying to download some stuff with `sftp` using Windows Terminal.

# Environment

```none
Windows build number: 18362.239 (Windows 10 1903)
Windows Terminal version (if applicable): 0.9.433.0

openSSH (delivered with Windows 10): OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

# Steps to reproduce

In my `.ssh` directory, I have a `config` with hosts definitions and settings. I have not tried wiping this one out to see if this changes anything.

```powershell
sftp host_in_config
```

# Expected behavior
Ability to type in commands in the `sftp` prompt.

# Actual behavior

It is impossible to enter any command, anything or whatsoever. I can't even quit `sftp`. The prompt keeps awaiting for inputs that... I cannot give.
I had to kill the `sftp` process.

I tried it in a conhost PowerShell window, and I could use it as expected.

Good hunt ! 😉 

**EDIT**
Fixed Windows Terminal version.

**Comment by WSLUser** [comment]
>openSSH (delivered with Windows 10): OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

Did you try updating your OpenSSH to 8.1 and check again? Some changes were made that made make working in Terminal better. I do not have problems using Terminal with the latest but I haven't attempted to use sftp either. I use scp instead and that has always worked.

**Comment by DHowett-MSFT** [comment]
I can't actually reproduce this on my machine with sftp from 7.7p1. Can you share a bit more information about your system? What sort of keyboard layout are you using?

**Comment by StinGer-ShoGuN** [comment]
> 
> 
> > openSSH (delivered with Windows 10): OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> 
> Did you try updating your OpenSSH to 8.1 and check again? Some changes were made that may make working in Terminal better. I do not have problems using Terminal with the latest but I haven't attempted to use sftp either. I use scp instead and that has always worked.

I'm not talking about OpenSSH in a Linux subsystem here, I'm talking about the one embedded in Windows 10. So no, I can't update to 8.1 (or 8.2 to be more up to date).


> 
> 
> I can't actually reproduce this on my machine with sftp from 7.7p1. Can you share a bit more information about your system? What sort of keyboard layout are you using?

I'm using Windows in French with a QWERTY keyboard configured for entering French in a US international layout.
I did not try to switch to English input with US international. Will do.

**Comment by StinGer-ShoGuN** [comment]
And... problem is gone. I can't reproduce it neither (I have restarted my computed since Friday, that may have helped).

**Comment by DHowett-MSFT** [comment]
Sorry to hear that the repro went away 😦 
Please let us know if it comes back.

**Comment by WSLUser** [comment]
@StinGer-ShoGuN Despite my username, I do use Windows OpenSSH as well in addition to WSL ssh. I've opened up PS many times in Terminal just to ssh to a Linux server. You can run both, just configure the WSL ssh to port 2222 or something else. And the Win32-OpenSSH release is currently pointing at 8.1. I would still suggest upgrading your OpenSSH but this sounds like you had a resource issue that was fixed by rebooting. That is probably OS specific, not Terminal or SSH (though if there's buggy code in the Win implementation of OpenSSH causing resource exhaustion, it would be worth filing an issue over there: https://github.com/PowerShell/Win32-OpenSSH)

**Comment by StinGer-ShoGuN** [comment]
> 
> 
> @StinGer-ShoGuN Despite my username, I do use Windows OpenSSH as well in addition to WSL ssh. I've opened up PS many times in Terminal just to ssh to a Linux server. You can run both, just configure the WSL ssh to port 2222 or something else. And the Win32-OpenSSH release is currently pointing at 8.1. I would still suggest upgrading your OpenSSH but this sounds like you had a resource issue that was fixed by rebooting. That is probably OS specific, not Terminal or SSH (though if there's buggy code in the Win implementation of OpenSSH causing resource exhaustion, it would be worth filing an issue over there: https://github.com/PowerShell/Win32-OpenSSH)

Thanks @WSLUser, wasn't aware of the up to date releases. 👍
