### ISSUE TITLE
Tabs in fullscreen

### ISSUE THREAD

**Issue by kort3x** [microsoft/terminal#4894]
Seems minor but it's really bugging me.

In fullscreen mode there are a few pixels of blank space between upper screen border and upper tab border. This means you cannot flick the mouse upwards and click on a tab but you have to aim for the tab.

![image](https://user-images.githubusercontent.com/13918530/76520100-8c33d080-6462-11ea-9eab-ce0ef2854289.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2541 for more discussion.

/dup #2541
