### ISSUE TITLE
requestedTheme does not match with Title Theme Color.

### ISSUE THREAD

**Issue by betancour** [microsoft/terminal#4895]
# Description of the new feature/enhancement

Normally we have two settings scenarios with our title color with this set on Json Settings scheme. 
even using System, Dark or Light what comes it's the same.

One the Light theme.
![image](https://user-images.githubusercontent.com/283403/76540526-0400fb80-6461-11ea-98e5-9a78b27a0ad5.png)

and Dark Mode
![image](https://user-images.githubusercontent.com/283403/76540569-10855400-6461-11ea-97c6-0aa5c0eafeab.png)

# Proposed technical implementation details (optional)

But in real life we have differents scenarios.

![image](https://user-images.githubusercontent.com/283403/76540703-4591a680-6461-11ea-8fba-7ee98193252e.png)
![image](https://user-images.githubusercontent.com/283403/76540729-504c3b80-6461-11ea-9192-a2eb5dc9e549.png)
![image](https://user-images.githubusercontent.com/283403/76540756-5b9f6700-6461-11ea-8a27-af6bfb68ba5e.png)

it's known that Dark and Light theme means the content of the windows but this does not alter the title in windows.

Is there a way to obtain this color from the Windows Title Color API? 

Thanks for all...

Regards 
Yitz

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1963 for more discussion.

You might also be interested in #3327

/dup #1963
