### ISSUE TITLE
CTRL + C kills entire terminal tab

### ISSUE THREAD

**Issue by oledid** [microsoft/terminal#4899]
# Environment
Microsoft Windows NT 10.0.18363.0
Windows Terminal (Preview) Version: 0.9.433.0
PowerShell Core 7.0.0

# Steps to reproduce

When running a long-running or infinite task from powershell, for example a watch-task for building and compiling, and I press "CTRL + C", the entire powershell process exits, and I have to create a new tab and navigate to the correct folder to be "where I was" before pressing "CTRL + C".

# Expected behavior

I would expect that "CTRL + C" would kill the long running process which was run from powershell, and not the entire powershell terminal tab. I would expect to return to powershell in the current working directory.

# Actual behavior

The entire tab stops and prints [process exited with code XXXXX]

![test](https://user-images.githubusercontent.com/1911049/76601972-47fc0b00-650a-11ea-878d-6a37610194a1.gif)
(here I press CTRL + C right after ```[nodemon] clean exit - waiting for changes before restart```)

**Comment by DHowett-MSFT** [comment]
How did you install powershell 7?

**Comment by oledid** [comment]
@DHowett-MSFT with scoop, https://scoop.sh, «scoop install pwsh» probably

**Comment by DHowett-MSFT** [comment]
This is very similar to https://github.com/PowerShell/PowerShell/issues/11314, but scoop needs to fix it on their end. Same exact problem. I can’t find the bug on their tracker right now, but somebody did file it. 😄

**Comment by oledid** [comment]
Thanks!

If other people are reading this, the solution is to change the exe being used, in windows terminal's `profiles.json`:

```json
"commandline": "C:\\Users\\username\\scoop\\apps\\pwsh\\current\\pwsh.exe",
```

**Comment by jorgensigvardsson** [comment]
> Thanks!
> 
> If other people are reading this, the solution is to change the exe being used, in windows terminal's `profiles.json`:
> 
> ```json
> "commandline": "C:\\Users\\username\\scoop\\apps\\pwsh\\current\\pwsh.exe",
> ```

So, I've installed it as a global dotnet tool. How do I solve it? This is causing neural damage... I've become wary of using Ctrl+C. :confounded:

**Comment by oledid** [comment]
@jorgensigvardsson I haven't done that, but the problem for the scoop installation was that the pwsh.exe in PATH was a [shimmed](https://en.wikipedia.org/wiki/Shim_(computing)) .exe, which did not work. If I changed to the real .exe, it worked. Maybe the global dotnet tool-installation also has another shim .exe? Check what you have in PATH when you run `where.exe pwsh`

**Comment by oledid** [comment]
Or locate the installation directory and see if there is another exe there

**Comment by jorgensigvardsson** [comment]
@oledid I only find `pwsh.exe` in my global dotnet directory `C:\Users\user\.dotnet\tools`. Maybe I should install it as a "real" application as well.

**Comment by oledid** [comment]
@jorgensigvardsson Yeah, maybe. Post it here if you find out :)

**Comment by jorgensigvardsson** [comment]
@oledid I downloaded the Power Shell 7 distribution for Windows x64, and Ctrl+C now works as expected. I hope my neurons will recover in time. 😀

**Comment by jorgensigvardsson** [comment]
And thank you very much for your help @oledid!

**Comment by oledid** [comment]
@jorgensigvardsson No prob, the problem made me pretty crazy too :)

**Comment by Livven** [comment]
FWIW this is the scoop issue: https://github.com/lukesampson/scoop/issues/3634 @DHowett-MSFT

**Comment by CHerSun** [comment]
Thank you @oledid . Just a small note from my side - when configuring pwsh installed using Scoop in Windows Terminal switch line `"source": "Windows.Terminal.PowershellCore",` to `"commandline": "%USERPROFILE%\\scoop\\apps\\pwsh\\current\\pwsh.exe",` if you are using default Scoop installation path.

**Comment by AndrewSav** [comment]
Alternatively `scoop config shim kiennq` seems to also work, after that you need to recreated the shim with `scoop update -f pwsh`

**Comment by Spinks90** [comment]
I know it's an old post but hopefully, this will help someone out. My JSON config was missing the keybindings.

   ` // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]`
