### ISSUE TITLE
Status update on tabbed terminal?

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/Terminal#49]
Heya! Sorry about this not being a real issue. In the Powershell AMA yesterday, [one of your colleagues](https://techcommunity.microsoft.com/t5/PowerShell-AMA/Tabbed-terminal-progress-update/m-p/144157#M173) recommended we could get in contact via this repo. 

> Last year, [Mike Griese mentioned on Hacker News](https://news.ycombinator.com/item?id=14099051) that a process-isolated, tabbed terminal was being worked on inside Microsoft. How is this progressing, and is there any way we can try builds of the updated terminal?

I suspect there's a massive bunch of Windows console fans who'd love to test your work!

**Comment by zadjii-msft** [comment]
Unfortunately, there's not a whole lot more to mention at this time. We're continuing to put the building blocks in place. It's turned out to be really quite a bit harder than we could have possibly imagined. We're working on a solution that we're all going to be really happy with, but that's about as much as I can say for now.

**Comment by mikemaccana** [comment]
Thanks OtherMike I appreciate the honesty. Gien your comments on HN about the age of the codebase, 
I wonder if keeping the existing terminal for compatibility purposes, and shipping a new one might be a better solution?

**Comment by mikemaccana** [comment]
Hey @zadjii-msft! Just wondering how the Sets feature in newer Windows builds releates to this - is the tabbed terminal functionality just using sets or is it an independent effort?

**Comment by zadjii-msft** [comment]
So here's the deal. We've basically known internally that Sets was a feature that was coming for a fairly long time now. There's been work done across the org for a few major releases now. So once we knew that was an effort that Windows as a whole was working on, to give every app a uniform tab experience, it didn't really make sense for us to implement it ourselves. If we had, it probably wouldn't have come much sooner than Sets, and it would have been a different UI/UX then the rest of the system. 

So, it's Sets is an independent effort that we get to leverage for free :)

**Comment by mikemaccana** [comment]
Fair enough! So you're leveraging Sets, what other stuff do you need to add
on top? Just interested. Thanks Mike!

**Comment by neurogenesis** [comment]
Hoping this will pave the way for flexible multi-pane consoles like iTerm. For a console-based dev or system management environment, iTerm2 is perhaps the single most compelling reason to stick with macOS over Windows.

Regex searches, multiplexed keyboard input to multiple panes, flexible profiles, etc..

https://www.iterm2.com/features.html

**Comment by Stanzilla** [comment]
This has nothing to do with panes though

**Comment by zadjii-msft** [comment]
@Stanzilla is correct - the Windows shell is giving us tabs for free, but if people want to implement a pane'd terminal, then they'll be able to do that by leveraging the new pty functionality we're working on (see #57 for more discussion).

**Comment by mikemaccana** [comment]
Playing with this now: 
![image](https://user-images.githubusercontent.com/172594/39745283-b99896d2-529e-11e8-9f5d-cf16dc9dcf70.png)

Currently 'New tab' just starts an Edge window - apparently there's supposed to be a list of apps I can start too, ut I can't see it. So I'm starting powershell via start each time and dragging it into the existing powershell window. Is there a better way of doing this? 

https://superuser.com/questions/1320651/windows-sets-how-can-i-make-new-tab-in-powershell-launch-powershell-rather-t

**Comment by zadjii-msft** [comment]
@mikemaccana That's the expected behavior for current Insider's builds. The "list of apps you can start" is Coming Soon<sup>tm</sup>, So you'll just have to wait for now.

We did check some code in to cmd.exe recently so that apps started with the `start` command (eg `start cmd`) should open as new tabs, that should be out in a couple weeks. 

The shell team is working on a lot of features here, so I'd expect the Sets experience to still be a little wonky for a while now, until a lot of the bugs are hammered out.

**Comment by klauern** [comment]
I had to turn off Tabbed Sets entirely, as I couldn't get an app that I use to run WSL terminals to **not** show up with that bar.  Is there an easy way to have this Tabbed Set configured per application more easily?  I feel like I'm going to have to clean up after this feature gets rolled out on a case-by-case basis and as a user, I'd like some easy way to do that.

As a developer, I assume this is something that you can opt-out of for your particular applications, correct?

**Comment by mikemaccana** [comment]
So it looks like you can find Powershell in the 'Search the web and Windows' bit. The address bar doesn't work.

@zadjii-msft As a rep for the terminal, could you talk to the sets people and find out if there was some way to make it easier to **'start a new tab with the same app'*. So we could hit a key combo or something and just launch another powershell or WSL or cmd or whatever in the same window without having to find it from the dropdown?

**Comment by mikemaccana** [comment]
Thanks @miniksa!

@bitcrazed one other piece of feedback, in addition to 'a quick way to start another tab of the same app' is the ability to click the taskbar a second time and have the whole set bought to the front.

For example, here I'm using four Powershell tabs in a set. I want to go back to whatever tab wwas in front. I can't remember whether that was tab 1, tab 2, tab 3 or tab 4. 

![image](https://user-images.githubusercontent.com/172594/39866267-e04a50a4-5447-11e8-89f7-9dd36f3fb12c.png)

If I could just click the taskbar item for the window a second time, and have the window bought to the front it would be really useful, since I couldn't have to think about which tab it was that I was using.

**Comment by bitcrazed** [comment]
Great feedback, thanks! I’ll share with the tabs team 😊

**Comment by glen-84** [comment]
@mikemaccana Perhaps this should be closed now?

**Comment by zadjii-msft** [comment]
Yea I'd say yesterday's announcement answered this question :)
