### ISSUE TITLE
shortcut key - Move Focus order

### ISSUE THREAD

**Issue by RyKaj** [microsoft/terminal#4900]
I am not sure if this is a bug or a feature. Can I move focus based on the visual order of the panels - to be able to navigate clockwise/coutner based on what I see not the order I create the panels?

I already configured my to use shortcut key to switch focus and create horizontal and vertical panels. 

I usually create panels based on different (development) environments and/or purpose of the server. 
Example: 

- Top panels might be the servers that host website or API, bottom might be database
- Top left development API,  bottom left development (mysql) database. Top right QA API, bottom right QA (mysql)  database

When I create the panel I usually first create another vertical panel. Intial is panel 1 and I created panel 2.  Shortcut key focus works
![image](https://user-images.githubusercontent.com/48734848/76618639-71636980-64ff-11ea-93ef-fe277bd8d5ed.png)

I create panel 3 when I am focus in Panel 2.. I need to be focus in panel 2 to focus on panel3. To my this make sense - clockwise and counter clockwise navigation.
![image](https://user-images.githubusercontent.com/48734848/76618813-d9b24b00-64ff-11ea-9947-be5b5166e864.png)

I now create panel 4 when I am focus in panel 1.
![image](https://user-images.githubusercontent.com/48734848/76618921-2138d700-6500-11ea-9e68-e19496a38c5d.png)

The focus only allows me to go in the order as I created. If I am in panel 3 I can only go to panel 3 or panel 1. I would like the ability to go to panel 4. If I am in panel 4 I can only go to panel 1 and 2. I can not go directly to panel 3.

**Comment by RyKaj** [comment]
Are you guys able to see my screen shot attachments?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2871 for more discussion.

/dup #2871
