### ISSUE TITLE
Align the text and icons in the title bar

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#491]
The title bar's metrics and alignment just looked strange. Please copy Chromium Edge's layout!

![image](https://user-images.githubusercontent.com/240091/57294613-c32aae80-70fa-11e9-9af4-7c0500dbdf6f.png)

**Comment by YantCaccia** [comment]
How did you get icons in this drop-down menu? Also my title bar looks a bit different:
![Annotazione 2019-05-07 145806](https://user-images.githubusercontent.com/11892754/57301160-9f567100-70d8-11e9-9732-9df7a3c9ebef.jpg)

**Comment by zadjii-msft** [comment]
The UI is still in pretty active development, so please be patient with us as we polish it :)

**Comment by zadjii-msft** [comment]
@YantCaccia You can add a `"icon":"<path_to_image>"` to the profile to set the icon for it. Make sure to properly escape the json though - `c:\windows\foo.png` should be `c:\\windows\\foo.png`

**Comment by fcharlie** [comment]
@YantCaccia See https://gist.github.com/fcharlie/7530d36175bc5249f1ae92be536238cd
@zadjii-msft  The configuration file is compressed after each load, which is not conducive to editing.

**Comment by zadjii-msft** [comment]
@fcharlie yea, that's a known pain point ATM. Windows.Data.Json unfortunately doesn't have a pretty-print option, so until we get approval for another JSON lib, we're stuck ;___;

**Comment by glen-84** [comment]
@fcharlie See #475.

**Comment by wahid** [comment]
Is it also possible to shown a short title instead of the whole path?

**Comment by DHowett-MSFT** [comment]
@wahid I moved your comment into #608.

**Comment by DHowett-MSFT** [comment]
This one is old and we've made some improvements here for v0.3. I'm going to close it in favor of #1375.
