### ISSUE TITLE
Windows + V do not work

### ISSUE THREAD

**Issue by Po-wei** [microsoft/terminal#4914]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.18363.720]]
Windows Terminal version (if applicable): Version: 0.9.433.0

```

# Steps to reproduce
Use Win+V to open the clipboard history
press Enter to paste

# Expected behavior

clipboard  content is pasted

# Actual behavior

Nothing happen or maybe ^M is sent ?

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #322 and #4184 for more discussion.

/dup #322 #4184
