### ISSUE TITLE
Bug and feature request about scrollbar

### ISSUE THREAD

**Issue by cloudhan** [microsoft/terminal#4920]
With scrollbarState hidden, there will be different visual effect

With Windows PowerShell, "scrollbarState" not set (this is a normal case, both bar and space present):
![win-ps-visible](https://user-images.githubusercontent.com/1279292/76679518-28550780-661c-11ea-96fc-3b25a0140360.png)

With Windows PowerShell, "scrollbarState" set to "hidden" (abnormal):
The scroll bar is hidden, but the space is left there 
![win-ps-hidden](https://user-images.githubusercontent.com/1279292/76679523-3acf4100-661c-11ea-8c5e-88f3cd78acaa.png)

With PowerShell Core (this is a normal case, the bar and the space is hidden):
![pscore-hidden](https://user-images.githubusercontent.com/1279292/76679538-62bea480-661c-11ea-99e1-e675083f26aa.png)

The bug is the abnormal case, I think it might be related with #3878.
The **feature request** is add ability to hide the space but show the bar.

**Comment by cloudhan** [comment]
Forgot to mention, Terminal Version: 0.9.433.0

**Comment by DHowett-MSFT** [comment]
I believe we accidentally fixed this with #4729 -- when you set `scrollbarState` it doesn't reload scrollbars that already exist.

**Comment by DHowett-MSFT** [comment]
(This will be fixed in the next release.)

**Comment by DHowett-MSFT** [comment]
(I didn't see your feature request; that one I'm going to keep closed as we've determined it's fairly difficult to do custom scrollbar things and the state of the art here is acceptable.)

**Comment by cloudhan** [comment]
@DHowett-MSFT I don't see how this feature can be difficult, isn't the scrollbar just an overlay over the text?

**Comment by DHowett-MSFT** [comment]
@cloudhan There's a bit more information about how annoying doing custom scrollbar stuff is in https://github.com/microsoft/terminal/issues/3454#issuecomment-550329209

**Comment by cloudhan** [comment]
I actually achived what I want with a negative padding, quiet ugly 😂

**Comment by DHowett-MSFT** [comment]
LOL. I didn't even know that worked.
