### ISSUE TITLE
UI Issue with panels

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/terminal#4923]
I am running Version: 0.9.433.0. I have multiple panels open like below.
![image](https://user-images.githubusercontent.com/211268/76692734-9e0aa480-6617-11ea-9ee3-df31faef373c.png)

If I close the panel on the left. Here is what I see.
![image](https://user-images.githubusercontent.com/211268/76692759-eb871180-6617-11ea-9994-a42bd6035152.png)

I expect the two panels below to auto resize and fill the entire space.

**Comment by carlos-zamora** [comment]
Looks like a /dup of #3744. We hope to fix this by v1. Thanks!
