### ISSUE TITLE
Prompt when pasting (multiple lines)

### ISSUE THREAD

**Issue by Enf0** [microsoft/terminal#4926]
Other terminal emulators (like ConEmu or SecureCRT) have an option to confirm before pasting anything into the terminal, or specifically when pasting multiple lines. 
It will open a pop-up dialog showing you what you are about to paste, and you can choose to proceed or cancel.

This is very useful to verify what is in your clipboard before pasting it, which will help you avoid accidentally pasting the wrong thing.

Is this something you could consider implementing into Windows Terminal?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2349 for more discussion.

/dup #2349
