### ISSUE TITLE
Visual artifacts while closing Terminal

### ISSUE THREAD

**Issue by PawanKartikS** [microsoft/terminal#4928]
There's this weird artifact that shows up while closing the terminal.

Steps for reproducing the issue -
1. Open Terminal
2. Hover your mouse cursor on terminal's icon in the taskbar.
3. Hit the close (X) button on the preview that the taskbar shows you.

Observe the weird artifact that develops at the bottom part of the screen (kind of some weird blur that covers the whole taskbar).

Windows Version: 2004 (19041.153)
Terminal: Running latest version with no updates in the store (0.9.433.0)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #4774 for more discussion.

/dup #4774
