### ISSUE TITLE
vim in PowerShell and cmd sessions ignore cursor settings

### ISSUE THREAD

**Issue by iovuio** [microsoft/terminal#4929]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.113]
Windows Terminal version (if applicable): 0.9.433.0

Any other software?
vim for Windows (installed via chocolatey): 8.2.0381
```

# Steps to reproduce

1. Edit the vim configuration file ($HOME\\_vimrc), append the snippet mentioned here: [#4335 comment](https://github.com/microsoft/terminal/issues/4335#issuecomment-577365966)
2. Open Windows Terminal
3. Open new CMD or PowerShell session/tab.
4. start vim -> vim starts in normal mode
5. Type i to enter insert mode

# Expected behavior

After step 4, according to configuration at step1 vim's cursor should be block
After step 5, according to conf at step 1. vim's cursor should be vertical bar.

# Actual behavior

vim's cursor is at all times whatever cursor the terminal has.

# Notes

Different vim cursors in normal vs insert modes do work partially in PowerShell and CMD windows (not started as sessions in Windows Terminal). Partially because the configuration at step 1 above is ignored indeed, however block for normal and underscore are the different cursors in the two modes.

This bug report only addresses only vim in PowerShell and CMD sessions in Windows Terminal.
Please refer to  [#4335](https://github.com/microsoft/terminal/issues/4335) for a solution for vim in WSL sessions) works in both WSL1 and WSL2. There are two problems there as described in [#4335 comment2](https://github.com/microsoft/terminal/issues/4335#issuecomment-599246201)

Thank you for building the soundest terminal on windows.

**Comment by jdebp** [comment]
As I wrote in #4734, Windows Terminal already does what is needed here, pace the flushing problem.  One can demonstrate it with [CursorShape.ps1](https://github.com/jdebp/terminal-tests/blob/master/PowerShell/CursorShape.ps1), indeed.

Therefore look to vim for the locus of this problem.

**Comment by DHowett-MSFT** [comment]
Indeed. Thanks jdepb :smile:

**Comment by iovuio** [comment]
@jdebp, thank you for the info.

neovim acts correctly when started (`nvim`). vim is the culprit in the OP and needs to be taught to act rightly, indeed.

One problem left. When neovim is exited, the Terminal is left with neovim's last cursor before exit (block) instead of underscore that the terminal profile has configured:
```
"name": "Windows PowerShell",
"cursorShape": "underscore"
```
and that incorrect cursor is not blinking. This will persist until session killed.

That problem has been reported [here](https://github.com/microsoft/terminal/issues/4335#issuecomment-591338416) too.

Please let me know if neovim exits incorrectly so that I can address that with its team. Thanks.

**Comment by iovuio** [comment]
> 
> 
> ... pace the flushing problem. ...
>
> ... has to do, here, pace the bug about it not taking effect ...

I believe you use "pace" as a preposition incorrectly. Please refer to [Oxford Dictionary definition](https://www.oxfordlearnersdictionaries.com/definition/american_english/pace2).
