### ISSUE TITLE
Got a different GUI of Windows Terminal

### ISSUE THREAD

**Issue by Jarvis73** [microsoft/Terminal#493]
Windows build number:  Microsoft Windows [版本 10.0.18362.86]
Builder: VS2017  version 15.9.11

I have built the "microsoft/Terminal" solution with VS 2017 and deployed the solution. But I got a Windows Terminal(Preview) which seems to be different with other people's.  For example this terminal doesn't have "+" button to create a new tab.

![image](https://user-images.githubusercontent.com/26033896/57297755-0be66580-7103-11e9-93a3-2f3fe264047f.png)

**Comment by dhrdlicka** [comment]
The default configuration hides the tab bar by default. You need to press Ctrl+T to open a tab and only then the tab bar will appear, together with a new tab button.

**Comment by Jarvis73** [comment]
Edit Windows Terminal settings in 
**C:\Users\<UserName>\AppData\Local\Packages\Microsoft.WindowsTerminal_<RandomString>\RoamingState\profiles.json**

And set "alwaysShowTabs" = true

**Comment by SwimmingTiger** [comment]
I think `"alwaysShowTabs" = true` should be the default, otherwise untrained users will not be able to find any way to open the tab from the GUI.

Or consider providing an expand button when tab hidden like some other GUIs.

**Comment by batzen** [comment]
@zadjii-msft Closing this does not seem to be the best solution to me. I also think that the default should be changed as it's not really obvious to new users why tabs are missing and the presentation from msbuild seemed to have tabs visible by default. Other tools with tab support, like browsers and editors, don't hide their tabs by default.

**Comment by zadjii-msft** [comment]
We're actually planning on having the default be tabs in the titlebar, which are always visible. Unfortunately, that experience is a little too buggy for our likes at the moment, which is why it's hidden under the `experimental_showTabsInTitlebar` setting.

Please bear with us as we polish the UI over the coming months :)

**Comment by batzen** [comment]
That's a way better answer than just closing the issue as answered ;-)
Thanks for your great work. I think the new terminal will be amazing.
