### ISSUE TITLE
Powerline Nerdfonts show fine blank lines between gyphs at 125%/175% scale

### ISSUE THREAD

**Issue by allymparker** [microsoft/terminal#4930]
# Environment
Windows 10.0.19041.0
Terminal  0.9.433.0
WSL 2, Ubuntu 18.04
Nerdfonts (FiraCode in this case, but it was the same for Cascadia Code PL)
Bash with Powerline Go
or ZSH with OhMyZSH and Powerline 10K

# Steps to reproduce
Set a +25% display scaling (eg 125, 175, 225%) in Display Settings.
100, 150, 200 all seem fine

# Expected behavior
Powerline Nerdfonts should display correctly:
![image](https://user-images.githubusercontent.com/2056009/76708839-d54d8400-66f1-11ea-80b6-848515370f63.png)

![image](https://user-images.githubusercontent.com/2056009/76708843-e8605400-66f1-11ea-84ff-5a1f52b42e06.png)

# Actual behavior
There are fine black lines between glyphs:

![image](https://user-images.githubusercontent.com/2056009/76708827-c4047780-66f1-11ea-9bce-27e9783a2465.png)

![image](https://user-images.githubusercontent.com/2056009/76708847-f7470680-66f1-11ea-8e1a-d8c9cbbc1136.png)

**Comment by zadjii-msft** [comment]
Thanks for the report - I'm pretty sure this is already being tracked in some combination of #3626 and #455 - I'd refer to those issues for more information. 

Thanks!

/dup #3626 #455

**Comment by allymparker** [comment]
No probs, I figured as much, but just wanted to add some more data :)
