### ISSUE TITLE
Ctrl+F4 keybinding to close tabs

### ISSUE THREAD

**Issue by Backup-eric645** [microsoft/terminal#4932]
# Description of the new feature (in this case the Ctrl+F4 keybinding)

Browsers have support for Ctrl+F4, so why not add it to Windows Terminal?

A user with knowledge of Windows default keybindings and browser keybindings might want to use the tabbed Terminal and if he does, he might experience no support for Ctrl+F4.

# Proposed technical implementation details

You might want to modify that `Tabs.h` in one of the projects. (Note: I did not have `Win32.Package.DeveloperMode` (the Windows Developer Mode package, mentioned the first time someone tries to use it) installed and activated at the time of opening.)

**Comment by DHowett-MSFT** [comment]
Thanks for the request! You may set whatever key bindings you like in your personal settings file.
