### ISSUE TITLE
typing on ternimal would enter Chinese input mode though I don't tend to .

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#4935]
# Environment

![image](https://user-images.githubusercontent.com/3938751/76728742-886dba00-6792-11ea-96a9-4fc62d897f7b.png)

# Actual behavior

Everytime I click terminal and type word, it would go into Chinese input mode , but I my input method doesn't turn on in Terminal (see the underline) : 
![image](https://user-images.githubusercontent.com/3938751/76728781-9d4a4d80-6792-11ea-9353-832769eaafd9.png)

I need press `shift` to quit Chinese input mode. This is very very incovenent !

My input method settings is : 
![image](https://user-images.githubusercontent.com/3938751/76729111-645ea880-6793-11ea-95a4-6b5cd931cba7.png)

From top to down : 
- Direct English Input(default)
- Chinese Input

I set shortcut `shift` + `ctrl` to switch input method (Follow the old window way ,I don't like windows 10 default behavious )

**Comment by DHowett-MSFT** [comment]
How does this work in other applications? I expected that people would want to use their "primary" input method in all applications.

**Comment by eromoe** [comment]
In others applications, first focus/click input box would not enter Chinese Input Method . 
Only ternimal would automatically enter Chinese Input Method .

**Comment by eromoe** [comment]
@DHowett-MSFT  How is going on ? This problem still exists in 0.11 . We usually open a terminal type some command then close it , this problem is very annoying .

**Comment by DHowett-MSFT** [comment]
I'm sorry it took so long for me to triage this. It looks like the other half of the request for #1304 -- entering Chinese input mode _first_, and re-entering Chinese input mode _after pressing enter_, are probably the same problem.

I'm going to move your images over to /dup #1304. Thank you!
