### ISSUE TITLE
Open Windows Terminal From File Explorer Navigation Bar With Same Folder Path

### ISSUE THREAD

**Issue by pc-v2** [microsoft/terminal#4936]
# Description of the new feature/enhancement
Open Windows Terminal with wt.exe command from File Explorer Navigation bar with current folder path
![image](https://user-images.githubusercontent.com/58063311/76749427-148dda80-67af-11ea-96b7-149903cf44db.png)
![image](https://user-images.githubusercontent.com/58063311/76749717-8cf49b80-67af-11ea-8641-b9ddf863f16d.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #878 for more discussion.

/dup #878 #4787 #4647 #4330 #4287
