### ISSUE TITLE
Crash when closing tab while loading power shell modules

### ISSUE THREAD

**Issue by michaelmairegger** [microsoft/terminal#4937]
# Environment

Windows build number: 10.0.18363.657
Windows Terminal version (if applicable): 0.9.433.0

# Steps to reproduce

- Open new Windows Power Shell Tab
- Close the tab as soon as the module loading message appears.

# Expected behavior

No crash

# Actual behavior

Crash of the power shell process.

**Comment by DHowett-MSFT** [comment]
Sorry, is _powershell_ crashing or is _terminal_ crashing?

**Comment by michaelmairegger** [comment]
_powershell_ is crashing but if I do the same steps directly on the powershell the powershell does not crash

**Comment by DHowett-MSFT** [comment]
So, all Terminal does is send a standard close event to powershell; there shouldn't be any magic in how it tears down within versus without terminal. It might be worthwhile to file a bug on [the powershell repository](https://github.com/powershell/powershell), as they may have more insight into what's going on.

Thanks!
