### ISSUE TITLE
"wt split-pane" and "wt new-tab" commands always open a new window

### ISSUE THREAD

**Issue by davidjade** [microsoft/terminal#4942]
# Environment

```none
Microsoft Windows [Version 10.0.18363.657]
Windows Terminal (Preview) Version: 0.9.433.0


No other software involved that I can determine
```

# Steps to reproduce

run wt new-tab
or
run wt split-pane

# Expected behavior

Operate per the docs:

for new-tab
_Opens a new tab with the given customizations. On its first invocation, also opens a new window. **Subsequent new-tab commands will all open new tabs in the same window.**_

for split-pane
_Creates a new pane in the **currently focused tab** by splitting the given pane vertically or horizontally._

# Actual behavior

Each "new-tab" or "split-pane" opens a new window every time. I've tried every launch combination I can think of but I always get a new window with the new tab or split pane.

**Comment by DHowett-MSFT** [comment]
The docs are correct here:

> Opens a new tab with the given customizations. **On its first invocation,** also opens a new window. Subsequent new-tab commands will all open new tabs in the same window.

On its first invocation _in a single wt.exe command_
