### ISSUE TITLE
splitHorizontal/splitVertical should respect/inherit current setting

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/terminal#4944]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): latest

Any other software?
```

# Steps to reproduce
My terminal has cmd and powershell. 
cmd is the default one.
open powershell, call splitHorizontal/splitVertical 

# Expected behavior
The new window should be powershell. It should respect/inherit its parent.

# Actual behavior

The new window is cmd window, which does not respect/inherit current setting.

Thanks.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1756 for more discussion.

/dup #1756
