### ISSUE TITLE
Git branch name text color cannot be controlled from properties menu

### ISSUE THREAD

**Issue by ianHunterClipd** [microsoft/terminal#4945]
# Environment

 Windows build number:
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
Ubuntu 

Any other software?
git

# Steps to reproduce

Create a new git repo and initialize or step into an existing git repo.
Use `git branch` to display current working branch

# Expected behavior

The branch names for the given repo should be listed, with the current working branch denoted by an asterisk. It would seem that the color of the branch name text should be controlled by the same terminal properties that control the other text colors in the terminal, namely 
Colors --> Screen Text and Colors --> Popup text

# Actual behavior

The branch names are displayed in a single color that is independent of the font color for the terminal. 
![gitBranchColor](https://user-images.githubusercontent.com/42324272/76798245-74bf5500-678c-11ea-830c-5d0e5c27a266.png)
In the image above, both of my text color settings in the Properties --> Colors window have been set to red, which is reflected in the user input in the terminal. However, the color of the branch name remains black. For light colored backgrounds this is not a problem - I noticed the issue when trying to set the background to Ubuntu's default purple color. 

Am I missing something simple? I have been using a custom color palette for the past two years, but earlier this week one of the Windows updates reset my Ubuntu terminal color preferences. After reverting to the colors in this article [Ubuntu colors for windows bash](https://medium.com/better-programming/make-bash-on-ubuntu-on-windows-10-look-like-the-ubuntu-terminal-f7566008c5c2) the issue was immediately noticeable. Any advice would be greatly appreciated - I'll roll with a lighter color scheme for now but would much prefer my old palette back. 

Cheers,
Ian

**Comment by zadjii-msft** [comment]
Could you share what the contents of the "Terminal" tab in the console properties shows as well?

**Comment by ianHunterClipd** [comment]
![terminalPropertiesUbuntu](https://user-images.githubusercontent.com/42324272/76799533-f2846000-678e-11ea-88d9-be26996cd655.png)

**Comment by DHowett-MSFT** [comment]
git likes to print the current branch name in _color index 2_ (which is usually green.)

normally:

![image](https://user-images.githubusercontent.com/14316954/76807247-f91bd300-67a0-11ea-86b0-017c6e29c2ea.png)

your color scheme:

![image](https://user-images.githubusercontent.com/14316954/76807266-0d5fd000-67a1-11ea-9987-a2159de5a6af.png)


it appears as though you've swapped black and green.

**Comment by ianHunterClipd** [comment]
Thank you so much! 

Is there a reference available that maps each color index to its uses in the terminal? Curious for future changes.

**Comment by DHowett-MSFT** [comment]
Sure! The canonical meanings of all the color indices are [here on Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) for both the classic 16- and xterm 88/256-color palette.

**Comment by DHowett-MSFT** [comment]
Oh, if you're asking for a list of what colors applications typically use for what, I'm afraid that that would be a nigh-unto infinite list and one that might be very difficult to keep up to date :smile:

**Comment by ianHunterClipd** [comment]
Definitely was asking for something like the latter, but now that it's here the former is certainly a more informative read!

**Comment by zadjii-msft** [comment]
I'm gonna go ahead and also pitch [colortool](https://github.com/microsoft/terminal/tree/master/src/tools/ColorTool) here too, since editing all 16 colors by hand is a MAJOR pain, the kind of pain that colortool was specifically created to fix ☺️
