### ISSUE TITLE
Reflow with long input loses cursor

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4955]
# Environment

```none
Windows Terminal version (if applicable) :0.10.721.0

Any other software?
```

# Steps to reproduce

Not too sure what caused it but I know I have a really long path in the prompt. It's fine when I interact with it at first. But after attempting to run the command, and pasting the same path again, the cursor goes crazy. Specifically, I was ctrl+left and it started happening. Here's a gif:

1. paste long path/command
2. run it (mine failed, derp)
3. press up (populates prompt)
4. ctrl+left to browse the input

# Actual behavior

cursor goes wack

![reflow bug](https://user-images.githubusercontent.com/11050425/76829418-63a03380-67e0-11ea-90ee-3b3187d8d049.gif)

**Comment by carlos-zamora** [comment]
@zadjii-msft Thoughts?

**Comment by DHowett-MSFT** [comment]
This may be a combination of the perfect wrap bug and this issue where sometimes the conpty host is off by one width

**Comment by zadjii-msft** [comment]
GAH I don't know what this is but I'll put it on me

**Comment by zadjii-msft** [comment]
@carlos-zamora what's your prompt set to in powershell? I can't get this to repro with

```
$esc = [char]27; function prompt() { "${esc}[41mhas a newline${esc}[m`n${esc}[33;40mha ha ha${esc}[m> " }
```

Was there any actual resizing involved?

**Comment by carlos-zamora** [comment]
> @carlos-zamora what's your prompt set to in powershell? I can't get this to repro with
> 
> ```
> $esc = [char]27; function prompt() { "${esc}[41mhas a newline${esc}[m`n${esc}[33;40mha ha ha${esc}[m> " }
> ```
> 
> Was there any actual resizing involved?

I guess it's just a reflow bug, not resize. 

I have a custom prompt, but it's basically just the Powerline theme from oh-my-posh. I'm wondering if this is just another manifestation of #2432?

**Comment by zadjii-msft** [comment]
I mean, I'm sure it's _possible_, though that one I'm positive that conpty and Terminal have the same contents in the buffer, while this one I'm a little more scared. I'll try `oh-my-posh` and see if that repros it for me.

**Comment by carlos-zamora** [comment]
Ok. We somehow couldn't get a repro of this. We're thinking it might be a powerline issue? But we're just gonna close this out until it pops up again. _Spooky_
