### ISSUE TITLE
Resizing the window cause text rendering error

### ISSUE THREAD

**Issue by Po-wei** [microsoft/terminal#4957]
# Environment

```none
Windows build number: [Version 10.0.18363.720]
Windows Terminal version (if applicable): Version: 0.9.433.0


Any other software?
```

# Steps to reproduce

1. press  Alt+Enter to full screen. **[Full screen]**
   _choose an app would print lots of line to stdout: such as SSH_
3. ssh serverName  **[Full screen]**
4. alt+Enter back to windows mode  **[window mode]**
5. ctrl+D to quit SSH session. **[window mode]**
  _run app that will generate lots of line to stdout: such as apt update_
6. sudo apt update **[window mode]**

**BOOOM some text of previous SSH session appear.**

Resize the windows in proper order is the key!!

# Expected behavior

work as expected
# Actual behavior

Some text of previous session will appear.

**Comment by scriptingstudio** [comment]
Can confirm. Resizing cuts text from right side.
**before**
![before](https://user-images.githubusercontent.com/17237559/76844348-338f7980-684e-11ea-951f-85f57822e2fd.png)

**after**
![after](https://user-images.githubusercontent.com/17237559/76844361-37bb9700-684e-11ea-9c2d-3e3d6fc6c9bb.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3490 and #4771 for more discussion.

/dup #3490 #4771
