### ISSUE TITLE
how to set powershell as default and change the color of it?

### ISSUE THREAD

**Issue by JinLingChristopher** [microsoft/Terminal#496]
how to set PowerShell as default? and how to change the color theme of it?
At the current time, I don't see any difference between this windows terminal and cmd.exe  or PowerShell.exe...

At least, not as cool as in the film.

**Comment by Robosky** [comment]
> how to set PowerShell as default?
- Edit `C:\Users\$USER\AppData\Local\Packages\Microsoft.WindowsTerminal*\RoamingState\profile.json`. By default there will be two profiles with different GUID, change the value of `"defaultProfile"` to the GUID of PowerShell profile

> how to change the color theme of it?
- If you just want to see the fluent effect, change `"useAcrylic"` in PowerShell profile to true. There are several custom options, you call try them by yourself.

**Comment by JinLingChristopher** [comment]
> > how to set PowerShell as default?
> 
> * Edit `C:\Users\$USER\AppData\Local\Packages\Microsoft.WindowsTerminal*\RoamingState\profile.json`. By default there will be two profiles with different GUID, change the value of `"defaultProfile"` to the GUID of PowerShell profile
> 
> > how to change the color theme of it?
> 
> * If you just want to see the fluent effect, change `"useAcrylic"` in PowerShell profile to true. There are several custom options, you call try them by yourself.

thanks!
