### ISSUE TITLE
Administrative Rights Elevation

### ISSUE THREAD

**Issue by bezzauk85** [microsoft/terminal#4969]
More of an oversight then an issue. As a heavy PowerShell user using both Administrative and non-administrative sessions, it would be really helpful to be able to have the ability to open tabs as administrators in the same window. The application is great other wise and so far so good. Great work everyone :)

**Comment by DHowett-MSFT** [comment]
Thanks for the comment! This is, unfortunately, not an oversight. There's a huge thread over at #1032 detailing what's up with our run-as-admin plan. Sorry about that!

/dup #1032.
