### ISSUE TITLE
Feature Request: duplicate current path with panes

### ISSUE THREAD

**Issue by Olyno** [microsoft/terminal#4970]
# Description of the new feature/enhancement

Currently, when I split a pane, my directory comes back to the root directory. It's really annoying when I need to run multiples different commands in the same directory. Maybe cache the path to go in when spliting a pane could benefic.

# Proposed technical implementation details (optional)

In the last Window Terminal Preview Update, you introduced "duplicate" key for panes. Maybe we could still the same key but add behind it the path of the current directory.

**Comment by DHowett-MSFT** [comment]
(the duplicate bug refers to a tab, pane is same thing in this case)
