### ISSUE TITLE
windows version 'ssh' does not have mouse support (while WSL version of ssh does)

### ISSUE THREAD

**Issue by tigerinus** [microsoft/terminal#4973]
# Environment

Microsoft Windows NT 10.0.18363.0
Windows Terminal 0.10.761.0
OpenSSH for Windows

# Steps to reproduce
1. Use OpenSSH comes with Windows to log onto a Linux host.
2. run `tmux` with `set -g mouse on` in its conf
3. split panel and try to select a panel using mouse

# Expected behavior

Mouse support should work. (I tried ssh from my Debian WSL and it works)

# Actual behavior

Mouse support does not work, if I use OpenSSH that comes with Windows.

**Comment by DHowett-MSFT** [comment]
This is a bug in Windows OpenSSH. It is fixed in version 8.

**Comment by fejjj** [comment]
I have version 8.1.0.1 (windows 10) and I have this bug unfortunately.

**Comment by zadjii-msft** [comment]
@fejjj you may be seeing https://github.com/PowerShell/Win32-OpenSSH/issues/1990 or https://github.com/PowerShell/Win32-OpenSSH/issues/1863, or something else from their repo. IIRC, mouse support is dependent on the OS version, and I'm not sure which Windows 10 versions actually included the mouse support in conpty.

**Comment by fejjj** [comment]
Ok, thank you.  The tickets you referenced had a more recent conhost
version than mine, so I guess that is indeed the problem.  Do you know
whether it's possible to update conhost without upgrading the whole OS?

**Comment by lhecker** [comment]
It's possible to replace conhost.exe in C:\Windows\System32 with a newer version. That said, don't do it, because you risk breaking the OS permanently that way. Upgrading Windows would be a lot safer.

**Comment by fejjj** [comment]
I wonder where I could source a newer version of conhost.  This is just a
home pc, no problem to restore windows if I break it.  But it is not
compatible with Windows 11 so upgrading is probably out of the question.
