### ISSUE TITLE
COOKED_READ tab completion is very wrong when the prompt is wrapped

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#4975]
# Environment
Windows build number: Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable): 0.10.761.0

# Steps to reproduce
1. Open cmd in Terminal.
2. Reduce the width to minimum (well, not minimum but small enough, as it occurs after crossing some threshold).
3. Press and hold Tab.

# Expected behavior
cmd cycles through the directories:

![ezgif-5-366a3a796ac1](https://user-images.githubusercontent.com/36439704/76931217-318cef80-690e-11ea-845c-e2cbf2eacb47.gif)

# Actual behavior
The names of directories are printed in succession without erasing the previous name which leads to this:

![](https://user-images.githubusercontent.com/36439704/76930157-db1eb180-690b-11ea-873b-18f50db871c3.png)

Also, note that this behaviour is not unique to Terminal, the default command promt(cmd/conhost/conPTY??) also has this bug:

![image](https://user-images.githubusercontent.com/36439704/76930682-0fdf3880-690d-11ea-9f9f-7c9f9c8e1d1a.png)

After resizing the terminal the text cannot be erased.

**Comment by zadjii-msft** [comment]
I'm not saying that this _isn't_ a bug, but it definitely repros in conhost too, so it's not necessarily a conpty or terminal bug. 

![image](https://user-images.githubusercontent.com/18356694/76960761-1b6d3800-68ea-11ea-8e1e-55366f8b1997.png)

For me, the trick is to resize such that the line the prompt starts on reflows, then hold <kbd>tab</kbd>. I'm seeing this on the ` 10.0.19587.1001` conhost, so that's not a particularly new conhost either.

**Comment by AnuthaDev** [comment]
Hey @zadjii-msft I was not saying that this *is* a bug in conpty, I have just seen that word used in similar contexts and didn't actually know the name of the default console, so threw it ther.(Note the question marks)

**Comment by DHowett-MSFT** [comment]
It looks like this reproduces as far back as RS4, and only impacts the first cooked_read line that wraps after the resize, so I'm going to move it from 21H1 to Backlog and yank Triage. P3.

Thanks all!

**Comment by piotrzarycki** [comment]
can i take care of it :) ?

**Comment by DHowett-MSFT** [comment]
If you want to take a crack at it, by all means do!

**Comment by serd2011** [comment]
This has something to do with the actual resizing cuz launching conhost with small width (enough to wrap cd path) does not reproduce this. And resizing back to big width causes it to print over the cd path. Interestingly, just writing after resizing works fine.

https://user-images.githubusercontent.com/45919738/187336803-70ab2a20-bf27-452a-9cfe-442caaf7c63d.mp4
