### ISSUE TITLE
Minimize button disappears at minimum size

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#4976]
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.18363.535]]
Windows Terminal version (if applicable): 0.10.761.0
```

# Steps to reproduce

Resize the terminal to the minimum size.

# Expected behavior
Minimize button should be visible/A minimum size limit like other apps:
Chrome: ![image](https://user-images.githubusercontent.com/36439704/76931592-048d0c80-690f-11ea-846a-df054bc2561e.png)

Credge: ![image](https://user-images.githubusercontent.com/36439704/76931612-1373bf00-690f-11ea-888d-5ab014aa5094.png)

Firefox: ![image](https://user-images.githubusercontent.com/36439704/76931681-3900c880-690f-11ea-8d89-d8f54bd7ed9b.png)

Notepads: ![image](https://user-images.githubusercontent.com/36439704/76931776-68173a00-690f-11ea-8595-6be26ed0aefb.png)

# Actual behavior
Just like most win32 apps, the terminal becomes too small(Also look how near the close button is to the edge. Some grid layout issues I guess):
![image](https://user-images.githubusercontent.com/36439704/76932057-05726e00-6910-11ea-84ba-61a10257f641.png)

Other programs like explorer, task manager etc show the same behaviour(atleat explorer has a minimum size limit):
![image](https://user-images.githubusercontent.com/36439704/76932401-d6103100-6910-11ea-9f97-d603d7048026.png)

![image](https://user-images.githubusercontent.com/36439704/76932413-df010280-6910-11ea-8376-e86ae2f2295f.png)

Interestingly, you can see that a minimize button drawn by the system(DWM?) can be seen in the screenshot just outside the windoe. Some other win32 apps like task manager have it too.But from what I understand it should not be there since we are drawing our own title bar (Using Xaml Islands?). Also, if I try to take a screenshot of only the window by using alt+prtsc, the minimize button does not appear.

I think we should have a minimum size limit like the browsers, or if not, atleast the (caption?) buttons should be fully visible at minimum size.

**Comment by DHowett-MSFT** [comment]
LOL. I can’t believe DWM draws a minimize button outside of our frame. Yeah, we should have a minimum size. Thanks for the report!

**Comment by DHowett-MSFT** [comment]
Best option would just be to enforce a minimum size.
