### ISSUE TITLE
Inconsistent line gap height

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#4977]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable): 0.10.761.0

```

# Steps to reproduce
1. Open cmd (Doesn't matter if its in terminal or conhost)
2. Press Ctrl+C 2-3 times.(Note the height of the line gap)
3. Press Enter.
4. Press Ctrl+C 2-3 times.(Note the height of the line gap)
5. Enter some invalid command.(Well, not necessarily invalid)
6. Press Ctrl+C 2-3 times.(Note the height of the line gap).

# Expected behavior
Consistent height of line gap

# Actual behavior
Terminal:

![image](https://user-images.githubusercontent.com/36439704/76933537-5a63b380-6913-11ea-9a5d-7ecb9bb411ed.png)

Conhost:
![image](https://user-images.githubusercontent.com/36439704/76933370-f214d200-6912-11ea-924c-a6add218550c.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the report! This is just a minor visual issue in CMD that doesn’t seem to have any impact on its usability, so it doesn’t meet the bar for fixes to CMD. I’d rather not risk destabilizing it since it really exists to maintain legacy compatibility.

Sorry!
