### ISSUE TITLE
Add a button or setting to make Windows Terminal always on top

### ISSUE THREAD

**Issue by gregkolodny** [microsoft/terminal#4979]
# Description of the new feature/enhancement

This would solve the problem of keeping the terminal window visible when it is not selected, which is useful for multi-tasking especially when there is a slow task being executed while you focus on something else, and for watching the output change when you make changes in another app.

Ideally, you would click a button in the title bar, and the terminal window would become "pinned" until that same button/option is reselected.

# Proposed technical implementation details

With other programs that have this feature, such as the Windows Calculator, you click a button and the calculator window becomes always on top even if it is not focused on. Clicking the same button again disables it.

![calculator-always-on-top](https://user-images.githubusercontent.com/11412644/76936684-b6a1e580-68c9-11ea-9a18-ecbc1527d811.gif)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3038 for more discussion. Please make sure to search for existing duplicates before filing new issues.

/dup #3038
