### ISSUE TITLE
White border when Terminal is dark while Windows is in Light theme

### ISSUE THREAD

**Issue by hylowaker** [microsoft/terminal#4980]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19582.1001]
Windows Terminal version (if applicable): 0.10.761.0
```

# Steps to reproduce

1. Set Windows theme to Light. 
1. In `profiles.json`, set `"requestedTheme": "dark"` and `"showTabsInTitlebar": true`
1. Focus on the window.

# Expected behavior

No white borders, regardless of Windows theme color. (Like as VSCode)

# Actual behavior

![image](https://user-images.githubusercontent.com/10094075/76942951-e8ef2980-6941-11ea-9878-de93feaed95f.png)

Though https://github.com/microsoft/terminal/pull/4817 fixes the white border issue for Dark mode in Windows, the border still presents with the combination of dark theme for Terminal settings and light theme for Windows.

**Comment by DHowett-MSFT** [comment]
So, we're doing our level best with the system API here. I'm going to keep this one around tracking our switch to the final API when it's out.

**Comment by michalhudecek** [comment]
This has not been fixed. There should be no white border regardless the theme as mentioned in Expected behavior in this issue

![image](https://user-images.githubusercontent.com/1215304/85220414-8cb9fc80-b3ab-11ea-9b57-77c882426bd0.png)
