### ISSUE TITLE
Add support for Russian characters for PowerShell within 

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/terminal#4982]
This is how it looks now if to type on Russian
![image](https://user-images.githubusercontent.com/60220228/76946420-0fe33680-6915-11ea-81be-a4b836da6207.png)

**Comment by ertyz** [comment]
it's a system-wide problem. Not a WT. You can see the same issue in your regular PowerShell console.
The reason is: Your current code page in powershell likely is set to "437 (OEM - US)".
To see normal Cyrillic characters it should be set to "866 (OEM - Rus)".

You can activate it for whole system in Classic Control Panel -> Region -> Administrative
and set "Current language for non-Unicode programs" to "Russian"

**Comment by SiarheiKuchukBelitsoft** [comment]
@ertyz Thanks. I thought that you were using Unicode and stuff behind the scenes and those setting will go away

**Comment by SiarheiKuchukBelitsoft** [comment]
@ertyz Can I ask you to just consider switching to Unicode by-default for PowerShell since it sounds like we have modern technologies with ASCII epoch

**Comment by zadjii-msft** [comment]
@SiarheiKuchukBelitsoft That might be a request that's better suited for the Powershell repo, [powershell/powershell](https://github.com/powershell/powershell). I'd think that the newer versions of powershell might just handle this better already. The one that's pre-installed on Windows is Powershell 5, and Powershell **7** was just released

**Comment by SiarheiKuchukBelitsoft** [comment]
@zadjii-msft Thanks for your input!
@ertyz, Thanks for so fast response!

**Comment by SiarheiKuchukBelitsoft** [comment]
I've just checked, Powershell 7 indeed works with Unicode out of the box!

**Comment by Aliaksandr3by** [comment]
[Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("utf-8")

![image](https://user-images.githubusercontent.com/11432724/103971453-aa01bd00-517b-11eb-91bc-0500a6322f50.png)

**Comment by Don-Vito** [comment]
> [Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("utf-8")

@Aliaksandr3by  - Cool! Seems to work in terminal as well:
![image](https://user-images.githubusercontent.com/4639110/103987226-d4ac3f80-5194-11eb-9501-e7d8a67b82f5.png)

**Comment by drweb86** [comment]
@Aliaksandr3by  It would be better if that it will enabled by default

**Comment by Aliaksandr3by** [comment]
> 
> 
> @Aliaksandr3by It would be better if that it will enabled by default

I use pwsh7
https://github.com/PowerShell/PowerShell

You might use 

%windir%\system32\WindowsPowerShell\v1.0
and to create either file:
notepad $pshome\profile.ps1
or
notepad $pshome\Microsoft.PowerShell_profile.ps1
![image](https://user-images.githubusercontent.com/11432724/104163020-bf3e4c00-5406-11eb-8988-7bc2bb86cab1.png)
