### ISSUE TITLE
Typing two identical characters causes the first one to display blank

### ISSUE THREAD

**Issue by fabienheureux** [microsoft/terminal#4984]
# Environment
Win32NT             10.0.19546.0 Microsoft Windows NT 10.0.19546.0
WSL2 / Ubuntu / bash 
Windows Terminal Preview version 0.10.761.0

# Steps to reproduce
Open a new windows terminal preview tab or window or pane, type `..` or `//` or `--`

# Expected behavior

`..` or `//` or `--`  are displayed in the terminal

# Actual behavior

The first character displays blank ` .` or ` /` or ` -`

**Comment by zadjii-msft** [comment]
@fabienheureux Could you share your `profiles.json` with us?

My hunch is that you're using a ligature font, and there's a bit of a regression in those recently: #4974

**Comment by fabienheureux** [comment]
Ho yeah...I am using a ligature font 🤦‍♂️
I am going to use another font for now. 
Closing as duplicate. 

Thanks !
