### ISSUE TITLE
Unbound No Longer Respected For Keybindings

### ISSUE THREAD

**Issue by raisin-loaf** [microsoft/terminal#4989]
Windows build number: `10.0.19013.0`

With Terminal `v0.9.433.0` this profile setting works as expected:

```
"keybindings": [
    { "command": "unbound", "keys": ["ctrl+^"] }
]
```

Instead of opening another Terminal tab the command is sent to the running app (in my case `Ctrl+^` switches to the [alternate file](https://stackoverflow.com/questions/5182852/in-vim-what-is-the-alternate-file) in Vim).

With Terminal `v0.10.761.0` this stops working. I've tried all of the following without success:

```
{ "command": "unbound", "keys": ["ctrl+^"] }
{ "command": "null", "keys": ["ctrl+^"] }

{ "command": "unbound", "keys": "ctrl+^" }
{ "command": "null", "keys": "ctrl+^" }

{ "command": "unbound", "keys": ["ctrl+shift+6"] }
{ "command": "null", "keys": ["ctrl+shift+6"] }

{ "command": "unbound", "keys": "ctrl+shift+6" }
{ "command": "null", "keys": "ctrl+shift+6" }
```

The only relevant-looking change in the release notes for `v0.10.761.0` is [this one](https://github.com/microsoft/terminal/pull/4714) but I'm not smart enough to figure out exactly what the problem might be.

All advice very gratefully received. 🙂

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3729 for more discussion. It's also already in PR 😉 #4988

/dup #3729

**Comment by raisin-loaf** [comment]
@zadjii-msft - nuts, sorry. I saw that issue but didn't read all the way to the bottom of the thread.

My apologies!
