### ISSUE TITLE
Is there any plan to support MacOS?

### ISSUE THREAD

**Issue by fhefh2015** [microsoft/Terminal#499]
Is there any plan to support MacOS?

**Comment by WaiwaiTAN** [comment]
maybe it's a little hard to fit...

**Comment by WaiwaiTAN** [comment]
> Is there any plan to support MacOS?

maybe it's a little hard to fit...

**Comment by hez2010** [comment]
It uses a GPU accelerated DirectWrite/DirectX-based text rendering engine and it's Windows only. I think it's hard to support MacOS.

**Comment by zadjii-msft** [comment]
There are no plans currently. 

We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to MacOS sometime, then I'd say there's very little chance we ever support MacOS.

**Comment by Biswa96** [comment]
How about using wine? https://wiki.winehq.org/MacOS
