### ISSUE TITLE
Interesting Resizing behaviour

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#4990]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable): 0.10.761.0

```

# Steps to reproduce
Grab the **left** edge of terminal window and resize it to be smaller, after the pointer crosses the window, terminal starts moving towards it.

# Expected behavior
Terminal should not move towards pointer

# Actual behavior
This:
![ezgifn](https://user-images.githubusercontent.com/36439704/76977887-f4e7e500-695b-11ea-85f4-fba0c6f1b98f.gif)

This is the first time I have seen something like this, pretty weird.

**Comment by zadjii-msft** [comment]
Well that's some real spooky action at a distance 👻 

I bet this has to do with an off-by-one on pane snapping, but I really can't be sure.

I'm gonna throw this one one the backlog.

**Comment by DHowett-MSFT** [comment]
LOL. I love your resizing bugs. Would this be helped if we just enforced a minimum size as the resolution to #4976 i wonder?

**Comment by zadjii-msft** [comment]
Hey so this seems to have magically gone away on its own, at least, it's gone in the  0.11.1153.0 build I'm running. @AnuthaDev could you check if this is still happening for you?

**Comment by AnuthaDev** [comment]
@zadji-msft I am running build 0.11.1121.0 (Latest release build) and still seeing this issue. If you can give me the 0.11.1153.0 build msix, I will test it.

**Comment by AnuthaDev** [comment]
@zadjii-msft This behaviour is fixed in latest build. Thanks.
