### ISSUE TITLE
Click here for a compiled version for testing

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/Terminal#500]
Since many people are unable or unwilling to compile their own version, here you go https://twitter.com/thebookisclosed/status/1125480984068153344

Install `CascadiaPackage_2019.5.6.0_x86_x64_arm64.cer` first
then `CascadiaPackage_2019.5.6.0_x86_x64_arm64.msixbundle` 
afterwards run `Add-AppDevPackage.ps1` 

Requires: 
* Developer Mode activated in Settings
* Windows 10 1903

**Comment by DHowett-MSFT** [comment]
1. This is not a bug.
2. This bug tracker is not for you to distribute binaries.
