### ISSUE TITLE
Document fields and effects in terminal settings

### ISSUE THREAD

**Issue by dperkins3600** [microsoft/terminal#5002]
There is limited descriptions of the fields in the terminal settings JSON file.
Ideally, there should be a description, and where appropriate, screen shots showing the effect of each change. If someone can provide me a list of fields with the descriptions, I can create a Word doc (or Markdown doc) with screen shots showing the effects.

**Comment by zadjii-msft** [comment]
I mean, there is https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md

**Comment by dperkins3600** [comment]
Thanks - that is helpful and a start. Can you provide me with additional info on the how and where the colors are used. For example, why would you want the, say, yellow color displayed as something different than yellow?

**Comment by zadjii-msft** [comment]
That's pretty much entirely at the discretion of whatever commandline application is running. Some applications use yellow to mean a warning. Some, like a text editor, might just change the colors o the text in accordance with the apps own color theme. 

In general, all commandline applications use some subset of the 16 ASCII color table. See for example 
![image](https://user-images.githubusercontent.com/18356694/77011354-b17c7f00-6939-11ea-9d4a-35c1da4f47c6.png)
(from [this repo](https://github.com/mbadolato/iTerm2-Color-Schemes))

Apps are free to use the colors however they like. Not however that apps have no idea what the _value_ of these colors are. Commandline applications merely say "I would like color 1", knowing that in general, the color that's in index 1 is "dark red". If the user wants to make "dark red" a green color like `#00ff00`, they're absolutely free to. Sure, apps will probably look peculiar, but that's just how terminals work.

**Comment by DHowett-MSFT** [comment]
Since it looks like we do have a doc for this, I'm gonna close the bug out. Thanks!
