### ISSUE TITLE
Tab won't close after entering exit in Ubuntu-18.04, Linux and CMD.

### ISSUE THREAD

**Issue by Idov31** [microsoft/terminal#5003]
When I enter an invalid command and afterward entering exit the result is that the tab is still open and just showing  [process exited with code 127] without actually closing the tab if it is Linux or Ubuntu and [process exited with code 9009] if it is CMD. The tab is not usable, but just showing the message mentioned above. It happens only after I enter an invalid command. Photos attached below.

# Environment
Windows build number: 1909
Windows Terminal version (if applicable): 0.10.761.0

Any other software?
No

# Steps to reproduce
Need to check the way that the command exit works in the specific cases that mentioned and fix it so it'll work like in the PowerShell terminal (I tried the same there but didn't face an issue).

# Expected behavior
The tab to be closed, just like after entering a valid command.

# Actual behavior
The tab remains open and unavailable to use, just showing the message [process exited with code 127].

![cmd_exit](https://user-images.githubusercontent.com/62358580/77009934-7e55e200-6971-11ea-84a8-f6dbfebc0e7f.png)
![linux_generated_command](https://user-images.githubusercontent.com/62358580/77009938-7f870f00-6971-11ea-9e1d-c0c2b09581b6.png)
![linux_terminated](https://user-images.githubusercontent.com/62358580/77009939-801fa580-6971-11ea-939e-69b4cd66f4e7.png)
![ubuntu_generated_command](https://user-images.githubusercontent.com/62358580/77009942-801fa580-6971-11ea-8031-1c16bdb32c95.png)
![ubuntu_terminated](https://user-images.githubusercontent.com/62358580/77009947-80b83c00-6971-11ea-8a1e-fe90e1e5e501.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the report! This one is by design, pursuant to https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181. /dup #4223
