### ISSUE TITLE
wt.exe mybatch.cmd runs the batch file and exits, need it to stay open

### ISSUE THREAD

**Issue by CarlosOnline** [microsoft/terminal#5004]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.720]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.10.761.0

Any other software? No
```

# Steps to reproduce

wt.exe mybatchfile.cmd

# Expected behavior

wt.exe runs the batch file and stays open kind of like cmd.exe /k mybatchfile.cmd

# Actual behavior

Batch file is run and then the terminal exits.

**Comment by DHowett-MSFT** [comment]
This is operating as expected: if the batch file exits successfully, it will result in the terminal closing. If it fails, it will result in the terminal staying open.

If you want to keep it open, be explicit and say `wt cmd /k mybatchfile.cmd`.

**Comment by isosphere** [comment]
This command line argument isn't mentioned in the --help popup. 

![image](https://user-images.githubusercontent.com/163370/125478652-ca2e30c7-9f23-4099-a300-2fb2a8161d40.png)
