### ISSUE TITLE
Right click on pinned icon to choose which terminal to open (powershell, cmd, ubuntu, etc).

### ISSUE THREAD

**Issue by Lawrence-Brad** [microsoft/terminal#5006]
# Description of the new feature/enhancement
Many applications have useful options when right clicking the pinned icon in the taskbar. It would be awesome if this application would have allow you to choose which terminal to open when right clicking the pinned icon in the taskbar like powershell, cmd, Ubuntu, or any other configured terminal.  It would be much faster and simpler than opening the application, then opening a new tab with the desired terminal.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Thanks! /dup #576
