### ISSUE TITLE
Can't maximize terminal after latest update (0.10.761.0)

### ISSUE THREAD

**Issue by bdrum** [microsoft/terminal#5009]
Dear experts, 
first of all thanks for the product. It' really nice!
But after latest update  (0.10.761.0) I have got such behavior:
# Environment

```none
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal (Preview)
Version: 0.10.761.0
```

# Steps to reproduce
When I maximize terminal it's stuck and trying to take all memory:
![image](https://user-images.githubusercontent.com/16210997/77031205-ec21fe00-69b1-11ea-9b8a-4b26e6f8a8de.png)

**Comment by DHowett-MSFT** [comment]
We’ll have a release out to fix this soon.
