### ISSUE TITLE
Cannot Open

### ISSUE THREAD

**Issue by harrcorr** [microsoft/Terminal#501]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

**Comment by zadjii-msft** [comment]
You'll need to provide some info for us to be able to help you. A stack trace maybe? A screenshot of the error it gives you?

As this issue is currently, this isn't actionable.
