### ISSUE TITLE
当我向wsl子系统命令行中粘贴路径的时候无法自动转换

### ISSUE THREAD

**Issue by meichangliang** [microsoft/terminal#5011]
cmder中:
![图片](https://user-images.githubusercontent.com/24769632/77036890-17750f00-69eb-11ea-8ade-f90be9160e06.png)

windows terminal 中:

![图片](https://user-images.githubusercontent.com/24769632/77037015-4a1f0780-69eb-11ea-8f5b-caaaa9b10fa6.png)

**Comment by meichangliang** [comment]
![图片](https://user-images.githubusercontent.com/24769632/77037070-733f9800-69eb-11ea-8c2a-efd4787cc7a6.png)

**Comment by meichangliang** [comment]
比如git-bash 命令 , 在  windows terminal  中也是无法做到正确转换的

**Comment by skyline75489** [comment]
To my understanding, this is about different behaviours between cmder and Windows Terminal when it comes to copy&pasting file URL. 

I think it's a nice feature, to automatically convert `C:\` to `/mnt/c`. I do not use cmder so I'm not aware of this feature in cmder.

**Comment by j4james** [comment]
If it's about path translation, then this is probably duplicate of #1772.

**Comment by meichangliang** [comment]
> If it's about path translation, then this is probably duplicate of #1772.

yes

**Comment by zadjii-msft** [comment]
Thanks for the help triaging everyone! 

/dup #1772
