### ISSUE TITLE
Issues with font

### ISSUE THREAD

**Issue by takecmd** [microsoft/terminal#5012]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

When I type the “em dash” symbol(U+2014 —), there's something wrong with the font

# Expected behavior

# Actual behavior

As the following screenshot:
![shot.png](https://i.loli.net/2020/03/19/tlkvYLbXW3BdK9U.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #610 for more discussion.

/dup #610
