### ISSUE TITLE
Open new terminal from cli as new tab on the already opened instance

### ISSUE THREAD

**Issue by LukaszGrela** [microsoft/terminal#5013]
# Description of the new feature/enhancement
I would like to open new terminal from CLI but with option to add it as new tab if there is terminal opened (either to first opened, or by some id).

or at the very least the new tab button to use the same location as previous tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4472 for more discussion. There's even more discussion over in #4632 as well.

/dup #4472
