### ISSUE TITLE
Key binding for closeTab

### ISSUE THREAD

**Issue by msmigiel** [microsoft/terminal#5014]
# Description of the new feature/enhancement

There are key bindings for various tab functions (newTab, duplicateTab, etc...) but I do not see one for closing a tab.

# Proposed technical implementation details (optional)

In defaults.json, we should have something like:

{ "command": "closeTab", "keys": "ctrl+shift+x" }

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! The action `closePane` will actually act to close a tab if there is only one pane in a tab. This has worked well so far as a effective default for "close tab".

**Comment by kid1412621** [comment]
> Thanks for the suggestion! The action `closePane` will actually act to close a tab if there is only one pane in a tab. This has worked well so far as a effective default for "close tab".

The `closeTab` scenario should like this: if I got multi panes and want to close current tab.
