### ISSUE TITLE
Memory leak on window resize

### ISSUE THREAD

**Issue by seanhelling** [microsoft/terminal#5016]
# Environment

```none
Windows build number: 10.0.19555.0
Windows Terminal version (if applicable): 0.10.761.0

Any other software?
zsh on WSL, oh-my-zsh
```

# Steps to reproduce

1. Open Terminal
2. Resize window

# Expected behavior

A resized window that continues to function properly

# Actual behavior

Window is resized, Terminal consumes entirety of system memory and stops responding 
![terminal-leak](https://user-images.githubusercontent.com/871536/77076049-a5400280-69c9-11ea-9f9d-f7a05d95847e.gif)

This issue is novel to the Windows Store update that was pushed to me this morning.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually tracked buy a bunch of other issues on this repo already: #4972, #4978, and the root cause #2815. In fact, this one's already fixed too, see PR #4964, which should be getting pushed out later today.

/dupe #4972 #4978 #2815
