### ISSUE TITLE
docs for all key bindings

### ISSUE THREAD

**Issue by javad94** [microsoft/terminal#5019]
Hi, Thanks for this great terminal.
My question is are there any docs that list all windows terminal's key bindings? because I have not found it yet.

**Comment by zadjii-msft** [comment]
Sure thing! They're all listed here: https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keybindings

**Comment by javad94** [comment]
@zadjii-msft Thanks. Sorry for the inconvenience.

**Comment by zadjii-msft** [comment]
No problem, I'm happy to help ☺️ 

As mentioned at the top of the settings file:
https://github.com/microsoft/terminal/blob/ae3f8f37596e16a1963875a1734153586237ec54/src/cascadia/TerminalApp/userDefaults.json#L1

Doing that will open up [this file](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json), which lists the defaults [here](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L211-L263)

**Comment by javad94** [comment]
@zadjii-msft Oh great, Thank you!
It's good to put a link for that in [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keybindings) file too.
