### ISSUE TITLE
Adding a mathematical function to solve a mathematical problem

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5020]
# Description of the new feature/enhancement
The **math function** should enable **Windows Terminal** users to **solve math problems** in the **Windows Terminal**, such as **dividing, multiplying, adding and subtracting**.

The **math function** works only in **Windows PowerShell**.

**Comment by DHowett-MSFT** [comment]
Windows Terminal is not a replacement for Windows PowerShell, so you can continue to use powershell _inside terminal_ to do your math.

![image](https://user-images.githubusercontent.com/14316954/77101671-ea1d6680-69d4-11ea-8477-0b3775bcf227.png)

**Comment by Qantex** [comment]
Thanks for the fast answer! 👍 😊
