### ISSUE TITLE
Windows PowerShell - Second character appears grey instead of yellow.

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5022]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.10.761.0

Any other software?
```

# Steps to reproduce

Start Windows PowerShell, type: "**a** (space bar) **a**"

# Expected behavior

The **second** letter should appear as **yellow**.

# Actual behavior

The **second** letter appears as **grey**.

![Anmerkung 2020-03-19 212744](https://user-images.githubusercontent.com/47790579/77111985-86bd2400-6a28-11ea-8388-3693eb5b9240.png)

**Comment by DHowett-MSFT** [comment]
That's how powershell's syntax highlighting works. the "Command" is yellow, and the first parameter is a different color.
