### ISSUE TITLE
Paste using right-click

### ISSUE THREAD

**Issue by K-Hoffmann** [microsoft/terminal#5023]
In some terminals I can mark the text and it is automatically copied to the clipboard. In Windows Termial with PowerShell this is not possible. At least I did not find an appropriate option to force this behavior.

# Proposed technical implementation details (optional)

A function like "Paste using right-click" or "Copy on select" would be very useful for everyday use.

**Comment by DHowett-MSFT** [comment]
We have a global setting called `copyOnSelect`.
