### ISSUE TITLE
[feature] Add setting for hidden scroll bar

### ISSUE THREAD

**Issue by dacapoday** [microsoft/terminal#5027]
# Description of the new feature/enhancement

add a setting that terminal can hidden scroll bar, make the UI more concise.
when use tmux with multiple panels, the terminal scroll bar is unnecessary.
In Putty, I can do it with unset "Display scrollbar" or "Display scrollbar in full screen mode"

# Proposed technical implementation details (optional)
Expect:
![expect](https://user-images.githubusercontent.com/9378047/77130074-6e352400-6a91-11ea-8077-1db229e05473.png)
Now:
![Snipaste_2020-03-20_09-29-22](https://user-images.githubusercontent.com/9378047/77130085-79884f80-6a91-11ea-8ff3-15c410115239.png)

**Comment by DHowett-MSFT** [comment]
This setting already exists. `scrollbarState`. See [here](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#profiles).
