### ISSUE TITLE
Doesn't work after upgrading to Windows 10 1909 (build 18363.720)

### ISSUE THREAD

**Issue by xlg210** [microsoft/terminal#5030]
The windows terminal was installed from  Microsoft Store. It does not work after upgrading to win 10 1909(build 18363.720). I try to reinstall Terminal  with release version 'Preview v0.10.761.0', doesn't work neither. The error in the picture said "The specified user does not have a valid configuration file"
![term_error](https://user-images.githubusercontent.com/4524943/77139320-7fd9f400-6ab0-11ea-901a-368723dd0621.png)

**Comment by DHowett-MSFT** [comment]
Are you using "Run as user"?

**Comment by xlg210** [comment]
> Are you using "Run as user"?
I used to double click. I tried running with administrator, but got the same error.  Is it possible because I am a domain user.

**Comment by xlg210** [comment]
I restart windows, and it's working now. Not only terminal got this problem, many windows apps has the same problem, but disappeared after restart.
Thanks!
