### ISSUE TITLE
Inconsistent number of panes being created

### ISSUE THREAD

**Issue by flery** [microsoft/terminal#5034]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): 0.10.761.0
```

# Steps to reproduce

When executing the following batch file multiple times an inconsistent number of panes is being created. 

```
wt -p cmd ^
	; split-pane -H -p cmd  ^
 	; new-tab -p cmd ^
 	; split-pane -p cmd -H ^
 	; split-pane -p cmd -H ^
 	; split-pane -p cmd -H
```

# Expected behavior

Two horizontal panes in tab one, four horizontal panes in tab two.

# Actual behavior

2, 3 or 4 panes in tab two (inconsistently).

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #4618 for more discussion.

/dup #4618
