### ISSUE TITLE
Duplicate tab should open in same directory as original tab

### ISSUE THREAD

**Issue by msmigiel** [microsoft/terminal#5036]
# Description of the new feature/enhancement

When duplicating a tab, the new tab should already be in the directory of the original tab. I'm finding that the new tab opens in the startingDirectory of the original.

# Proposed technical implementation details (optional)

Upon duplication, the new tab should be in the current directory of the original tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3158 for more discussion.

/dup #3158
