### ISSUE TITLE
Ctrl+Break behaves in cmd not as expected

### ISSUE THREAD

**Issue by schlamar** [microsoft/terminal#5037]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): Version: 0.10.761.0
```

Usually a Ctrl+C behaves different than Ctrl+Break in a cmd console.

But in Windows Terminal Ctrl+Break behaves like Ctrl+C.

For example you can reproduce this with Python by running in cmd

    py -c "import time; time.sleep(60)"

# Expected behavior

Ctrl+C --> KeyboardInterrupt
Ctrl+Break --> Program quits **without** KeyobardInterrupt

This is the default behavior in standalone cmd.exe.

# Actual behavior

Ctrl+C --> KeyboardInterrupt
Ctrl+Break --> KeyboardInterrupt

**Comment by schlamar** [comment]
It is possible that this is a regression from the 0.10 update because I haven't noticed this before.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1119 for more discussion.

/dup #1119
