### ISSUE TITLE
[Feature request] Linux support

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/Terminal#504]
Please.

**Comment by niquenen** [comment]
Genious 👏🏻

**Comment by DHowett-MSFT** [comment]
This is a Windows project. Linux is not in our plan.

**Comment by SafariMonkey** [comment]
https://github.com/microsoft/Terminal/issues/498#issuecomment-490091740 covers some technical reasons for why this would be difficult.

**Comment by probonopd** [comment]
> This is a Windows project. Linux is not in our plan.

Uh, https://twitter.com/windowsdev/status/1125476958794539008 has

[![](https://user-images.githubusercontent.com/2480569/57327355-4b5e8300-70fe-11e9-9861-6d01536702a8.png)](https://twitter.com/windowsdev/status/1125476958794539008)

**Comment by zadjii-msft** [comment]
Sure, you'll be able to launch into any of your WSL distros straight from the new tab drop down, but running _on linux_ is not part of our strategy at this time.

**Comment by DHowett-MSFT** [comment]
Hey @probonopd, those are WSL instances! The [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) lets you run unmodified Linux distributions (and unmodified ELF64 binaries!) natively on Windows.

Running the terminal _on_ linux is not in our plan. :)

**Comment by v3ss0n** [comment]
Port this to linux anyways , just need to replace directx with opengl calls.

**Comment by zadjii-msft** [comment]
@v3ss0n It's definitely not "just replace directx with opengl". The entirety of the Terminal UI is written using UWP XAML, which definitely doesn't work on linux, and neither does C++/WinRT. Without both of those, the Terminal won't be possible to port to linux.

The core of the logic might be possible to port, but there's already a plethora of good terminal abstractions on linux.

**Comment by v3ss0n** [comment]
Thanks , but Graphic accelerated Terminal is very interesting , hope this will spark inspirations on linux

**Comment by zadjii-msft** [comment]
I believe [jwilm/alacritty](https://github.com/jwilm/alacritty) is a OpenGL terminal for linux, if you need a linux terminal.

**Comment by wiltaylor** [comment]
Don't need to replace DirectX calls. You could use VKD3D to translate them to Vulkan calls. :D 

Once it's ported to Linux we will have to figure out how to run doom in it.
