### ISSUE TITLE
(PowerShell) ISE possibilty in Windows Terminal

### ISSUE THREAD

**Issue by ParkHost** [microsoft/terminal#5042]
Integrate the PowerShell Script Environment within the Windows Terminal. Probably you can use this 'notepad / scriptpad' with all the different shells, this will ease with writing some multi line code quick and easy without switching to different programs. Btw this is also a lack of PowerShell-Core, or do you advise to do this in VS Code?

**Comment by DHowett-MSFT** [comment]
VS Code is the preferred embedded development environment for Powershell Core. Sorry! This is outside of Terminal's area of expertise.
