### ISSUE TITLE
Hebrew Characters do not render at all

### ISSUE THREAD

**Issue by GalHorowitz** [microsoft/terminal#5045]
# Environment

```none
Windows build number:  Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.10.761.0

Any other software?
```

# Steps to reproduce

I just open terminal, write some characters in English, and then write some characters in Hebrew, and the Hebrew characters do not show up

# Expected behavior

Hebrew should show up.

# Actual behavior

![image](https://user-images.githubusercontent.com/7957292/77194217-373e2d00-6ae8-11ea-85c6-d0676beeceda.png)

**Comment by j4james** [comment]
I think this is #4779. It used to work, but apparently it was broken by PR #4747.

**Comment by zadjii-msft** [comment]
@j4james thanks for finding that!

/dup #4779 #538
