### ISSUE TITLE
Terminal update loses all scrollback history

### ISSUE THREAD

**Issue by sozercan** [microsoft/terminal#5048]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

Microsoft Windows [Version 10.0.19041.153]

# Steps to reproduce

- Terminal update is released in Store
- Store updates Terminal
- Terminal shuts down abruptly (unless there are multiple tabs open, it will ask if it should close)

# Expected behavior

Terminal update should not close automatically when app is updated through store
If Windows Store is a blocker in this case, provide other means to install/update

For example, iTerm2 handles this excellent on Mac. Even after update, it will keep current sessions alive, users keep their scrollback and environment variables just as before any update happened (best case fix).

# Actual behavior

Lose all scrollback history and other runtime environment variables that were configured

**Comment by DHowett-MSFT** [comment]
You didn't include your terminal version, but you're describing a symptom from 0.10.761 (instead of 0.10.781, which was just released.)

**Comment by DHowett-MSFT** [comment]
Oh, I see what you're talking about. I'm sorry. This is actually /dup #1386 -- we don't have control over the store's update process, but distributing outside the store will help.
