### ISSUE TITLE
Run Diskpart only from Windows Terminal

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5050]
# Description of the new feature/enhancement
**After you run the Diskpart command in the Windows PowerShell of Windows Terminal, a new window opens. Problems can be solved faster if the new window would not appear when entering "DIskpart".** **From my point of view it would be much better if the "Diskpart" command is executed on the Windows terminal and no new window has to be opened.**

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This is actually an elevation issue. If you use one of the existing "sudo" implementations for Windows, you should be able to run it inside terminal directly.

**Comment by DHowett-MSFT** [comment]
It is a separate window because diskpart wants to run as Administrator.
