### ISSUE TITLE
Terminal does not respond to DSR 5 VT Sequence

### ISSUE THREAD

**Issue by wthueb** [microsoft/terminal#5052]
# Environment

```none
Windows build number: 10.0.18363.720
Windows Terminal version (if applicable): 0.10.761.0

Any other software? Ubuntu for Windows Subsystem for Linux.
```

# Steps to reproduce

Run the following script (it was created for iTerm2 in order to check if the terminal is iTerm2 regardless of ssh connections or anything) in Ubuntu: https://github.com/gnachman/iterm2-website/blob/master/source/utilities/it2check

# Expected behavior

The terminal responding with its status to the ESC[5n sequence.

# Actual behavior

stdin gets blocked since the terminal doesn't respond to the ESC[5n sequence. I have only ran into it with this one script, however I'm sure there are other scripts out there using this.

**Comment by zadjii-msft** [comment]
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_

```
CSI Ps n  Device Status Report (DSR).
            Ps = 5  ⇒  Status Report.
          Result ("OK") is CSI 0 n
            Ps = 6  ⇒  Report Cursor Position (CPR) [row;column].
          Result is CSI r ; c R

          Note: it is possible for this sequence to be sent by a func-
          tion key.  For example, with the default keyboard configura-
          tion the shifted F1 key may send (with shift-, control-, alt-
          modifiers)

            CSI 1 ; 2  R , or
            CSI 1 ; 5  R , or
            CSI 1 ; 6  R , etc.

          The second parameter encodes the modifiers; values range from
          2 to 16.  See the section PC-Style Function Keys for the
          codes.  The modifyFunctionKeys and modifyKeyboard resources
          can change the form of the string sent from the modified F1
          key.
```

**Comment by DHowett-MSFT** [comment]
Note for actionable issue titles: there are hundreds of “ANSI Sequences,” so it’s very helpful if you call out the one that isn’t supported when you write the title of the issue.

**Comment by j4james** [comment]
I actually have a patch for this stashed somewhere, but I got sidetracked looking into refactoring the parameter handling in the state machine (which is somewhat necessary for a strictly correct DSR implementation, but not really essential).

So if there's any urgency for this, I can always dig up my original solution from the stash (it probably just needs a unit test or two). But I suspect you probably won't be accepting feature PRs like this until after the May release anyway.
