### ISSUE TITLE
Tab strip scroll bumpers don't disable when scrolling to the edge

### ISSUE THREAD

**Issue by AmineI** [microsoft/terminal#5053]
# Environment

```none
Windows build number: 19577.1000
Windows Terminal version (if applicable): 0.10.761.0
tab settings set to default, ie:
    "showTabsInTitlebar": true,
    "tabWidthMode": "equal",
```

# Steps to reproduce

1. Add enough tabs to make the tab strip scrollable, so that the scroll arrows appear.
2. Scroll as much as possible in one direction (left or right)

# Expected behavior

The corresponding arrow should be disabled and grayed out to indicate the state of being at the complete left/right. Example with Microsoft Edge (Legacy) tab strip :

![image](https://user-images.githubusercontent.com/15179425/77209163-cefa4600-6afd-11ea-8836-94293d7018aa.png)
Screenshot above on MS Edge, after doing the repro steps, with the _mouse cursor on the arrow button_ 
As you can see, MS Edge reacts to the edges of the tab strip. (..Mandatory pun)

# Actual behavior

3. Notice that even though you can't scroll anymore, the scroll arrow doesn't reflect this state. (Not grayed out, and reacts to clicks, even though nothing happens

![image](https://user-images.githubusercontent.com/15179425/77208907-31067b80-6afd-11ea-9dcc-5da47f6ad034.png)

Screenshot above on Windows Terminal, after doing the repro steps, with the _mouse cursor on the arrow button_

I went ahead and tried to look into it a bit, and was able to repro with WinUI 2 through the [XAML Control Gallery](https://github.com/microsoft/Xaml-Controls-Gallery), and WinUI 3 alpha as well.
I thought it would be wiser to file the issue on their repo, but it was apparently advised to report it there as Terminal's Tab View may be a prototype version and not directly using Win UI's - My apologies if this issue would have been better off on WinUI's repo !

**Comment by zadjii-msft** [comment]
Yea you should definitely file it on the WinUI repo. We are using the TabView directly from their package. A couple months ago, it was just a prototype, but they've been shipping it officially for a couple releases now 😄

**Comment by AmineI** [comment]
Good to know, thanks for the precision 🙂 !

I'll do exactly that and cross-reference both issues, to try to make issues management easier on your end. Apologies for the outdated information I had !

**Comment by DHowett-MSFT** [comment]
I'm gonna mark this one Tracking-External as well and close it out, but we'll keep our eyes on it. Thanks!
