### ISSUE TITLE
IME fails very frequently in the v0.10 release

### ISSUE THREAD

**Issue by etern** [microsoft/terminal#5054]
In the middle of typing, IME frequently fails, I tried but still can't figure out how the failure is triggered, but only if I type and delete for a while, it always happen, so I get the chance to record a gif:
![terminal_IME_fail](https://user-images.githubusercontent.com/4412793/77214542-a64c6d80-6b4a-11ea-8ddf-6e9563f4c7c7.gif)

From the gif, you can see the first two characters were typed correctly, after that, nothing from the IME can be typed again.

# Environment
Microsoft Windows [版本 10.0.18362.476]
The gif is recorded in v0.10.761.0, and it still happens in v0.10.781.0
I have been using Terminal v0.9, which works fine, the error comes with v0.10
# Steps to reproduce
Can't figure out exactly, keep typing and deleting in a prompt for a while, it always happen

# Expected behavior
characters from IME can be typd onto terminal

# Actual behavior
IME fails

**Comment by leonMSFT** [comment]
Just curious, what's the version of Windows you're running?

**Comment by leonMSFT** [comment]
@etern I've managed to half repro the issue you're seeing (my work machine can't repro, but my personal PC can repro), so I'm not sure if I'm fixing the exact issue you're seeing. I have a _potential_ fix in the branch named `dev/lelian/imeweird`. If you have a chance to take a look and try it out, it would help me know whether or not I'm encountering the same bug you are!

**Comment by etern** [comment]
@leonMSFT My Windows version is 10.0.18362.476.

If you can fix this, you might know how it can be triggered (hope it's not random behavior). I can verify the trigger method on my PC, so we know if you fixed the right problem.

If that doesn't help, I will try to build your branch by this weekend. Since I'm not familiar with the code, I don't have the confidence to make it work

**Comment by leonMSFT** [comment]
I believe the trigger is to start composition with something like "wei'yua" but backspace delete your composition completely before you complete the composition. After deleting the composition, try creating a composition again and nothing will show up but the composition picker box will show and update as if you're typing normally.

**Comment by etern** [comment]
Yes, "delete composition completely" can reproduce the bug every time, you get it right. Please merge the fix.

**Comment by leonMSFT** [comment]
Actually, I have one more follow up question: after deleting the composition "wei'yuan", does the starting letter 'w' reappear?

**Comment by etern** [comment]
Yes, the first character reappear

**Comment by etern** [comment]
One more thing, after the deletion triggers the bug, I just `Enter` to a new line, IME works.

But sometimes, when I switch from other place to terminal window, IME fails and can't be restored by `Enter` to a new prompt. In this occasion, I have to close the tab and open a new one. I don't know how to reproduce this, these two problems may be related.

**Comment by skyline75489** [comment]
I can reproduce this easily on my laptop with Windows 10.0.18363.720 and Windows Terminal at a3382276d7977fe521065793b366fa024fe519a7 under two different circumstances:

* First, backspace deleting all composition completely, basically the same as @etern pointed out.  After deleting the composition the letter 'w' will reappear. 
* Second, unfocus WT window while the IME prompt is displayed. The entire composition (wei'ruan) will reappear.

@leonMSFT Your fix seems to be working with both cases. But the reappearing is still there, which I suppose is something you are aware of.

**Comment by leonMSFT** [comment]
Yeah the reappearing character is a particularly annoying problem. For some reason, I'm receiving a `CompositionCompleted` event _before_ getting the `TextUpdate` that the last character was deleted. This causes me to believe the Composition is finished, so I send what's in our buffer, but then right after sending it, I get an update saying the last character is deleted, so then I delete it from the buffer.

**Comment by leonMSFT** [comment]
I've made a PR to at the very least allow y'all to continue typing in Chinese IME, but I haven't come up with a way to resolve the reappearing initial character due to not understanding why the text server API must act this way 😢
