### ISSUE TITLE
Cannot unbind default keybindings

### ISSUE THREAD

**Issue by hgminh95** [microsoft/terminal#5056]
# Environment

```none
Windows build number: 10.0.18362 Build 18362
Windows Terminal version (if applicable): 0.10.761.0
```

# Steps to reproduce

Unbind Ctrl + Shift + 6 key as shown in the [docs](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#unbinding-keys)

```
"keybindings": [
  { "command": null, "keys": ["ctrl+shift+6"] }
]
```

# Expected behavior

The key is unbound.

# Actual behavior

Nothing changed. The key still has effect.

### Note

```
    "keybindings": [
        { "command": "copy", "keys": ["ctrl+shift+6"] },
        { "command": "copy", "keys": ["ctrl+shift+c"] }
    ]
```

Above settings work for me, i.e. Ctrl+Shift+6 is disabled, while Ctrl+Shift+C for Copy still works as expected.

**Comment by DHowett-MSFT** [comment]
Upgrade to 0.10.781.0.

**Comment by DHowett-MSFT** [comment]
And please search before filing a new issue. One of the pinned issues refers to unbinding. :)

**Comment by hgminh95** [comment]
Thank you. Sorry I forgot to check the closed issues.
