### ISSUE TITLE
Only one part of unicode character get deleted on backspace in git bash for windows

### ISSUE THREAD

**Issue by wallymathieu** [microsoft/terminal#5057]
# Environment

```none
PS C:\Users\osge> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): Version: 0.10.781.0 and older

Git for windows : 2.25.1.windows.1 and older
```

https://github.com/git-for-windows/git/releases/tag/v2.25.1.windows.1

# Steps to reproduce

For git bash set
locale C character set UTF-8 : 
```env
LANG=C.UTF-8
```
Start a windows terminal with git bash:

```json
      {
        "guid": "{c72ed3ae-ef92-4961-ba3b-c51ae3021680}",
        "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
        "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
        "name": "GitHub",
        "startingDirectory": "%USERPROFILE%\\Documents\\GitHub",
      },
```

Enter Swedish character

```none
öåä
```

Delete a character

# Expected behavior

expect the single character to be deleted

# Actual behavior

part of the character gets deleted, you get an invisible character left causing issues with further input

**Comment by DHowett-MSFT** [comment]
When I enter those characters, and then delete them, it works fine. Can you share some screenshots of what you're seeing?

**Comment by wallymathieu** [comment]
I've done some configuration in git bash: 
```
export LC_ALL=sv_SE.utf8 
```
Git bash on it's own works fine without the LC_ALL configuration. It seems like in windows terminal without LC_ALL åöä gets translated into two bytes. When deleting the character, it looks like it works, but only part of the two byte character get deleted. If you continue deleting you delete the other hidden byte.

**Comment by wallymathieu** [comment]
[MINGW64__c_Users_osge_Documents_GitHub 2020-03-24 06-45-14.zip](https://github.com/microsoft/terminal/files/4373408/MINGW64__c_Users_osge_Documents_GitHub.2020-03-24.06-45-14.zip)

**Comment by DHowett-MSFT** [comment]
I have set my keyboard layout to Swedish (Sweden, not Finland), and I still cannot reproduce this issue.

Can you use `cat` to generate a text file with these characters in it?

```
cat >sv_se.txt
åöä½
<ctrl+d to end>
```

I'd like to see what bytes we're getting from the input stack. Thanks!

**Comment by wallymathieu** [comment]
[sv_se.txt](https://github.com/microsoft/terminal/files/4382086/sv_se.txt)

**Comment by DHowett-MSFT** [comment]
This is going to be a crazy question, but if you change your `commandline` from `bash.exe` to `bash.exe -li`, does it work better?

**Comment by wallymathieu** [comment]
Using `bash -li` makes the characters work as expected. Another solution is to set `LC_ALL=sv_SE.utf8`.

**Comment by DHowett-MSFT** [comment]
Thanks for confirming. THe Git folks let me know that things "won't work correctly" if we leave off the `-li`, so I've asked the person updating our third-party profiles documentation in #5141 to add it there.

Thanks for working with us on this! :smile:
