### ISSUE TITLE
Selecting terminals using jump lists

### ISSUE THREAD

**Issue by PlastMan420** [microsoft/terminal#5058]
# Description of the new feature

To access different terminals faster. it would be nicer to have terminals specified in profiles.json accessible via jumplists. something like right mouse clicking taskbar or start tile -> start new ubuntu terminal

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #576 for more discussion, and make sure to search for existing duplicates when filing new issues.

/dup #576
