### ISSUE TITLE
Cannot Compile Gives Error 

### ISSUE THREAD

**Issue by harrcorr** [microsoft/Terminal#506]
The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	PropertiesLibrary	D:\ImportantPrograms\Visual Studio\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets
After trying to fix Error cannot include Common.h

**Comment by ObiWahn** [comment]
I got a similar error even though I answered with yes when I was asked if I would like to upgrade. Maybe they should provide a CMakeLists.txt that allows us to generate for 14.20.

**Comment by zadjii-msft** [comment]
The `Common.h` error is because you didn't do a `git submodule update --init --recursive`. Please read the README.

**Comment by zadjii-msft** [comment]
I'm gonna defer any other build errors discussion to the megathread in #489.

**Comment by harrcorr** [comment]
> The `Common.h` error is because you didn't do a `git submodule update --init --recursive`. Please read the README.

i did this i still receive the error

**Comment by harrcorr** [comment]
im also now getting error cannot open source file (alot of files)

**Comment by javierdlg** [comment]
@harrcorr make sure to set your build to x86 when building cpp projects
