### ISSUE TITLE
Mouse Wheel does not Scroll the content

### ISSUE THREAD

**Issue by d35r0n** [microsoft/terminal#5060]
I frequently use mouse wheel to scroll the text in the terminal and using the arrow buttons is too much of a hassle and less productive for me. If possible, please add the function to use the Mouse Wheel for scrolling in the Terminal Preview.

**Comment by zadjii-msft** [comment]
Could you give us a bit more detail? Mouse scrolling is supposed to work already to scroll the Terminal.

* Are you using a touchpad? Particularly a HP one? Then you might be seeing #979 
* Are you trying to scroll in a particular application that uses VT mouse mode? Then this might be #376

**Comment by j4james** [comment]
See also #3321.

**Comment by d35r0n** [comment]
Hi, I wanted to point something out. The scroll is working in the original
Terminal. I was talking about the Terminal Preview. The scroll doesn't work
in the Terminal Preview version.

**Comment by DHowett-MSFT** [comment]
> Could you give us a bit more detail? Mouse scrolling is supposed to work already to scroll the Terminal.
> 
> * Are you using a touchpad? Particularly a HP one? Then you might be seeing #979 
> * Are you trying to scroll in a particular application that uses VT mouse mode? Then this might be #376

**Comment by d35r0n** [comment]
2020-03-23-0103-05.mp4
<https://drive.google.com/file/d/1whUSkDcL7KrfUk_rAYkDkwSAYAsFAYHS/view?usp=drive_web>
I am using a Lenovo Laptop (Legion Y520 to be exact) and a standard
External Mouse. I am trying to scroll the text using the mouse wheel in
Windows Terminal Preview but It just doesn't respond to my Scrolling input.
I have attached a screen recording of comparing the scroll using the mouse
wheel in both normal Terminal and the Preview Terminal if that helps. Also,
I am not using it in any application that uses VT mouse mode as far as
I know.

**Comment by DHowett-MSFT** [comment]
Unfortunately, I do not have access to that video. Sorry.

**Comment by d35r0n** [comment]
Hi, here's the link to the video:
https://drive.google.com/file/d/1whUSkDcL7KrfUk_rAYkDkwSAYAsFAYHS/view?usp=drivesdk

**Comment by zadjii-msft** [comment]
By any chance, do you have either of the following installed?
* "X-Mouse Button Control" - then this might be #2594/#4315
* "ZoomText 2020" - then this might be #4889
