### ISSUE TITLE
Windows Terminal Panes in Tabs

### ISSUE THREAD

**Issue by woowil** [microsoft/terminal#5061]
# Description of the new feature/enhancement

Windows Terminal Panes in Tabs

# Proposed technical implementation details (optional)

My scenario is that I have Windows Subsystem for Linux (WSL) activated with the Debian package. I am using Windows Terminal to open the Debian shell. I have installed Powershell 7 for Linux, Kubernetes CLI, Azure CLI, Git in the Debian WSL to manage my Azure AKS deployments.  I want a feature that can split the tab (similar as in PowerShell ISE) so that one section uses **PS7** shell and the other one uses **bash** shell.  The aim is to be able to use the run different shells in one tab som that for example Linux command  "**watch -t -n1 kubectl get pods**" in bash pane while running kubectl commands in a PS7 pane.  [In this example](https://www.youtube.com/watch?v=_r368h-mxxs)  he is using two window frames which a bit cumbersome. This feature would blow all other Terminals away and attracted many developers and operators 

This feature will have a menu choice of splitting a tab into several panes, both horizontally and vertically.

**Comment by zadjii-msft** [comment]
Hey thanks for the suggestion! The Terminal actually already supports panes! You might be interested in #1000 and any of the threads linked to that issue. I'm pretty sure all the asks you're looking for are tracked there. 

Thanks!
