### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#5063]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
Ctrl+Shift+(1-9) (1-9 from numpad)

# Expected behavior
Opening new tab

# Actual behavior
Nothing

**Comment by DHowett-MSFT** [comment]
Those bindings are not applicable to the numpad.
