### ISSUE TITLE
Dark Mode in Winodws Terminal

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5068]
# Description of the new feature/enhancement
**The dark mode function developed in the operating system Android / iOS, which many computer scientists / developers use.
From my point of view I think that many computer scientists / developers would like to use this function.**

# Proposed technical implementation details (optional)
![external-content duckduckgo c5om](https://user-images.githubusercontent.com/47790579/77242114-61344400-6bfb-11ea-863b-0318c236eba9.png)

**Comment by DHowett-MSFT** [comment]
Windows Terminal will use dark theme if your operating system theme is set to Dark theme.

![image](https://user-images.githubusercontent.com/14316954/77242247-c36c5500-6bb9-11ea-8288-5c07c0a6bed7.png)

**Comment by DHowett-MSFT** [comment]
You can also set `"requestedTheme": "dark"`!
