### ISSUE TITLE
On Build error xcopy on not english localized machines

### ISSUE THREAD

**Issue by DieselMeister** [microsoft/terminal#507]
On a non english localized machine the xcopy command lines in the file:

**cppwinrt.build.post.props**

generate an error while building.

the "echo f" in front of the 4 commands (look for xcopy) works only if the word "file" in your language begins also with an "f".

In germany it's a "D" for "Datei".

**Comment by zadjii-msft** [comment]
wait _really_

That seems insane to me, but that can be fixed. `echo f | xcopy` always seemed like a hack to me anyways.

**Comment by DHowett-MSFT** [comment]
We should address this by removing manual `xcopy` steps :)

**Comment by schuettecarsten** [comment]
> We should address this by removing manual `xcopy` steps :)

Or use robocopy, which should have the same command syntax for all languages.
