### ISSUE TITLE
Change text color in Windows PowerShell

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5070]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.10.781.0

Any other software?
```

# Steps to reproduce
**First, start the Windows PowerShell command prompt. Now run the CMD command, which starts a new command prompt. After the command prompt starts, type and then run the ("color a") command. You must now start Windows PowerShell by typing this command ("powershell.exe").**

# Expected behavior
**Windows PowerShell should return to its default text color.**

# Actual behavior

**The text color of Windows PowerShell has been changed**
![Anmerkung 2020-03-22 065013](https://user-images.githubusercontent.com/47790579/77243457-72d11800-6c0a-11ea-851d-da78177aeb4a.png)

**Comment by DHowett-MSFT** [comment]
This is how the Color tool is supposed to work.

**Comment by Qantex** [comment]
However, this **should not happen** because **Windows PowerShell does not accept a change in text color**.

**Comment by Qantex** [comment]
However, this should not happen.

**Comment by Qantex** [comment]
This should not happen. Windows PowerShell should return to its default text color.

**Comment by DHowett-MSFT** [comment]
_Every_ console application accepts a change in color! That’s one of the coolest things about console applications. Powershell doesn’t reset the color, so you can make it appear in whatever color you want.

This is because a terminal has an “active” color, and that active color is used to write all new text. CMD’s `color` command changes the active color. Powershell respects the active color because that is what a well behaved application does 😄

**Comment by Qantex** [comment]
I am very happy that you continue to write with me, but there is still a small error that I want to explain. Windows PowerShell has a green text color at the end but not anymore when a Windows terminal user starts to execute a function in Windows PowerShell that does not exist.
![Anmerkung 2020-03-23 091120](https://user-images.githubusercontent.com/47790579/77295463-52768b80-6ce6-11ea-99fa-1a65fe594f07.png)

**Comment by DHowett-MSFT** [comment]
I'm happy to help!

Here's what's happening.

1. `color a` sets the "active" color to `a`
2. cmd exits
3. powershell starts printing text in "active" color `a`
4. powershell wants to print an error message
5. powershell sets the color to `8` (bright red)
6. powershell prints the error message in `8`
7. powershell _doesn't know_ what the old color used to be (`a`), so it uses its hardcoded default `7` (plain white)

Unfortunately, Terminal doesn't know what powershell is doing: it only sees text and color commands. It is powershell's job to make sure the colors remain correct. :smile:

**Comment by Qantex** [comment]
> Unfortunately, Terminal doesn't know what powershell is doing: it only sees text and color commands. It is powershell's job to make sure the colors remain correct. 😄

PowerShell did not reset the text colors correctly.
When a Windows terminal user starts typing this text (" [a] ") in PowerShell, the square brackets turn green.

**Comment by Qantex** [comment]
@DHowett-MSFT I have found my old message about this error and have not yet received a reply. 
You can still see the error in Windows PowerShell.

**Comment by DHowett-MSFT** [comment]
This is, as described above, completely on purpose. This is by design.
