### ISSUE TITLE
("color a") command in Windows PowerShell

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5071]
# Description of the new feature/enhancement
**Windows Terminal users can change the text color from the CMD prompt by executing the command ("color a"). 
Windows PowerShell users currently do not have the ability to change the text color by running the ("color a") command.**

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Powershell has its own way to set colors. Please look up Powershell ConsoleColor enum.
