### ISSUE TITLE
The command ("exit") works after it has been executed several times.

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5072]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.10.781.0

Any other software?
```

# Steps to reproduce
**Start the Windows PowerShell command prompt. 
Now run the command ("CMD") 3 times. 
After executing the command ("CMD") 3 times, execute the command ("EXIT") 3 times.**

# Expected behavior

**From my point of view it would be much better if the CMD prompt was stopped with an execution.**

# Actual behavior

**Windows Terminal users must run the command ("EXIT") 3 times to return to Windows PowerShell.**

**Comment by DHowett-MSFT** [comment]
You have started three shells, you need to exit them three times. That’s just how this works.

You’ve been filing a lot of issues lately, all of which have been closed. You might be happier using the MSDN discussion forums!

**Comment by Qantex** [comment]
I reported this to see if it would be possible to include a command that would close all command prompts **simultaneously**.

**Comment by DHowett-MSFT** [comment]
The best way to do that is to close the tab! We can’t add an exit command that stops every process, because it would not know when to stop!

**Comment by DHowett-MSFT** [comment]
Thanks for the feature request :)
