### ISSUE TITLE
Colors & glyphs broken with git-for-windows bash

### ISSUE THREAD

**Issue by niderhoff** [microsoft/terminal#5073]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.10.761.0

Any other software?
- Git for Windows v2.25.0 (January 13th 2020)
```

# Steps to reproduce

- Open vim in a git-bash shell

# Expected behavior

Colors & glyphs work same as in WSL bash

# Actual behavior

Background color is messed up, other colors are missing and different font-glyphs are replaced by squares:

![image](https://user-images.githubusercontent.com/5991543/77248617-1afed500-6c3b-11ea-933b-543c11e9633e.png)

As you can see it is only vim, the prompt is fine.

As a comparison, the same vim config in a WSL-bash environment:

![image](https://user-images.githubusercontent.com/5991543/77248643-53061800-6c3b-11ea-83fa-ca2591cf0dbc.png)

Any ideas? Seems like some issue with mingw?
Here is the related profile:

```json
            {
                "guid": "{269bed3e-4c58-495f-a318-3cfbadc27934}",
                "name" : "Git Bash",
                "commandline" : "C:\\Program Files\\Git\\bin\\bash.exe",
                "icon" : "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "startingDirectory" : "C:\\Develop\\projects"
            },
```

**Comment by DHowett-MSFT** [comment]
I believe this is a limitation of the MSYS2 runtime git-bash uses. Since the upstream MSYS2 runtime has been updated to support the Windows Console better, I expect that it will eventually be released as part of a Git for Windows update. Sorry!

**Comment by niderhoff** [comment]
can you link me to the corresponding msys2 runtime update?

**Comment by trajano** [comment]
I tried using the latest msys2 from scoop using the following

```
        {
            "guid": "{00000000-0000-0000-ba54-000000000003}",
            "commandline" : "%UserProfile%/scoop/apps/msys2/current/usr/bin/bash.exe -i -l",
            "startingDirectory": "%UserProfile%",
            "name" : "MSys2"
        },
```

But running the test output still does not work correctly in Windows Terminal using
```
curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash
```

**Comment by ean5533** [comment]
@DHowett-MSFT Based on the most recent comment above it sounds like there isn't actually an upstream fix. Do you have any further info?

**Comment by niderhoff** [comment]
I am running the most recent .exe installer from git for windows and the most recent windows terminal (preview) from the microsoft store with MINGW64 (not msys) and colors now work fine.

So there might be still a problem with msys2?

**Comment by trajano** [comment]
Actually the current git bash works well it may have been fixed since the last time I tested it
![image](https://user-images.githubusercontent.com/110627/91378049-7b4b0180-e7ed-11ea-82e5-42736d039fbd.png)

Mind you it is very slow to run that bash script.  I haven't determined whether it is bash or windows terminal issue.  But `bat` also gets really slow.
