### ISSUE TITLE
Drawing a button?

### ISSUE THREAD

**Issue by Richienb** [microsoft/terminal#5075]
With the addition of mouse support, is it possible to simulate buttons in the Windows Terminal?

**Comment by j4james** [comment]
> With the addition of mouse support, is it possible to simulate buttons in the Windows Terminal?

Yes. You can test this with the Linux [`dialog`](https://linux.die.net/man/1/dialog) utility. In a WSL bash shell, try something like this:

    dialog --yesno "Click Yes or No" 5 20 && echo Yes clicked

**Comment by Richienb** [comment]
@j4james Is there a demo with code that I can use or an implementation guide for this?

**Comment by j4james** [comment]
The general idea is you enable up/down click events by setting private mode 1000 (`"\e[?1000h"`). And then you can just read the events from stdin in the form of an escape sequence, in the same way you'd read a keypress event.

There are a bunch of a different reporting modes you can choose from, depending on whether you need a wider coordinate range, or you want to know the state of modifier keys, etc. Have a look at the [Terminal Guide](https://terminalguide.netlify.com/mouse/) website for a nice explanation of the different options, and the format of the reports. But note that some formats are better supported than others. Windows in particular only supports modes 1000, 1002, 1003, 1005, and 1006 (at least for now).

Anyway, that's the low level protocol, but depending on what programming language and operating systems you're targeting, there may be higher level libraries you can use (e.g. [ncurses](https://en.wikipedia.org/wiki/Ncurses)). I'm not sure this is the best place to ask for example code though.

**Comment by zadjii-msft** [comment]
This is a fine discussion, and by all means, feel free to continue it here, but since there's nothing really actionable for the Terminal team here, I'm going to close this issue. Thanks!
