### ISSUE TITLE
Specify number of lines for scollUp and scrollDown commands (+ follow system setting?)

### ISSUE THREAD

**Issue by Livven** [microsoft/terminal#5078]
# Description of the new feature/enhancement

It would be nice if the `scrollUp` and `scrollDown` commands supported a `lines` argument that would specify how many lines to scroll.

Alternatively or additionally, it might make sense to set the default to the number of lines the mouse wheel is set to scroll, i.e. usually 3. This seems more useful to me as a default than just scrolling a single line, which is very slow, or scrolling a whole page, which can be jarring (at least without smooth scrolling #1400).

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
We've got a global setting, `"rowsToScroll"`, that configures how many lines to scroll with the wheel. If you do not set it, it defaults to your system setting (as set in the Mouse settings page.) If I recall, that default on Windows is 3.
If you're using a precision trackpad, that setting should still apply.

**Comment by Livven** [comment]
I was talking about the keyboard-bindable commands :)

**Comment by zadjii-msft** [comment]
You know, when I first [spec'd arguments for keybindings](https://github.com/microsoft/terminal/blob/master/doc/specs/%231142%20-%20Keybinding%20Arguments.md), I called out `scrollUp` and `scrollDown` as two actions that needed args for customizable values. Looks like that never got turned into an actual issue.

**Comment by Livven** [comment]
@zadjii-msft For me personally it would actually be enough if the value was simply linked to `rowsToScroll` or the Windows mouse wheel setting, because that already fixes the issue of scrolling by just 1 line being super slow. But of course additional customization doesn't hurt.

(accidentally hit the close issue button there)

**Comment by DHowett-MSFT** [comment]
Thanks! Triaged this onto the backlog, but marked it Help-Wanted. If somebody were to implement this before v1, I'd almost certainly pull it in.
