### ISSUE TITLE
VS failed to build with many errors

### ISSUE THREAD

**Issue by Naibaowjk** [microsoft/terminal#508]
conpronps.lib不是有效的win32程序，，release不了。。

**Comment by Mika-Lahtinen** [comment]
如果是VS 2019，前面有解决方案试试

**Comment by svandex** [comment]
刚编译了一把，107个warning，1个错误，Windows.UI.Xaml版本不对，但是nuget又没有那个版本。。。。

**Comment by Naibaowjk** [comment]
> 如果是VS 2019，前面有解决方案试试

2017..

**Comment by Naibaowjk** [comment]
> 刚编译了一把，107个warning，1个错误，Windows.UI.Xaml版本不对，但是nuget又没有那个版本。。。。

这有编译好的版本么。。

**Comment by svandex** [comment]
> > 刚编译了一把，107个warning，1个错误，Windows.UI.Xaml版本不对，但是nuget又没有那个版本。。。。
> 
> 这有编译好的版本么。。

看老外也有好多没法编译的。。。我还在摸索中

**Comment by SamNormcoreWayne** [comment]
vs2017
command: msbuild OpenConsola.sln /p:Platform=x64
129 警告
21 错误

**Comment by svandex** [comment]
我猜测是不是要Windows 1903版本才行啊，我第二次编译出现了新的错误。。。。

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory	WindowsTerminal	c:\users\svandex\documents\github\terminal\src\cascadia\windowsterminal\apphost.h	6	
```

缺少头文件了

**Comment by SamNormcoreWayne** [comment]
> 我猜测是不是要Windows 1903版本才行啊，我第二次编译出现了新的错误。。。。
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C1083	Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory	WindowsTerminal	c:\users\svandex\documents\github\terminal\src\cascadia\windowsterminal\apphost.h	6	
> ```
> 
> 缺少头文件了

之前有帖子说要1903

**Comment by loveuav** [comment]
> 我猜测是不是要Windows 1903版本才行啊，我第二次编译出现了新的错误。。。。
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C1083	Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory	WindowsTerminal	c:\users\svandex\documents\github\terminal\src\cascadia\windowsterminal\apphost.h	6	
> ```
> 
> 缺少头文件了

安装WinRT包即可
https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264

**Comment by zadjii-msft** [comment]
So for the record, the megathread for all build issues is #489.

Make sure to use VS 2017. There are workarounds for 2019, but 2017 will be easier.

Make sure to install all the necessary VS components, as noted in https://github.com/microsoft/Terminal#prerequisites.

Also, make sure to init the git submodules, and do a nuget restore.

**Comment by yu-liang-zheng** [comment]
B站有教安装的视频：https://www.bilibili.com/video/av51726432/

**Comment by SwimmingTiger** [comment]
VS2019提示`function`不是`std`成员，或者`包含不能在当前代码页(936)中表示的字符`等错误的可以考虑我这个分支：
```
git clone -b vs2019fix https://github.com/SwimmingTiger/Terminal.git
```

提示`wil/Common.h`找不到的，请运行
```
git submodule update --init --recursive
```

提示程序集缺失的，请用Visual Studio打开解决方案，在解决方案上右击，点击“还原NuGet包”，或者运行（如果该命令找不到，请进行`git submodule update --init --recursive`）
```
dep\nuget\nuget.exe restore OpenConsole.sln
```

如果提示缺少构建工具集，请为VS2019安装以下组件（可能有多余，我不知道哪个多余）：
* 工作负载：
   * 通用Windows平台开发
* 单个组件
   * C++ ATL for v142 生成工具 (x86和x64)
   * Windows 10 SDK （任一版本）
   * Windows 通用 C 运行时
   * NuGet 包管理器
   * C# 和 Visual Basic
   * C++ 核心功能
   * C# 和 Visual Basic Roslyn 编译器
   * MSBuild
   * MSVC v142 - VS 2019 C++ x64/x86 生成工具
   * Windows 通用 CRT SDK


如果构建目标是ARM64，请切换为x64或者x86，否则不能运行。

构建完成后怎么安装？请在解决方案上右击，选择“部署解决方案”，“Windows Terminal (Preview)”将出现在开始菜单。

最后，如果找不到多标签功能，请按Ctrl+T。

最终效果：
![最终效果](https://user-images.githubusercontent.com/4986069/57313957-3cd69280-7123-11e9-93a6-cfe7c8b6ecca.jpg)

**Comment by svandex** [comment]
@SwimmingTiger 你的操作系统版本是1903吧

**Comment by SwimmingTiger** [comment]
> 
> 
> @SwimmingTiger 你的操作系统版本是1903吧

是的

**Comment by svandex** [comment]
> > @SwimmingTiger 你的操作系统版本是1903吧
> 
> 是的。不过即使程序不能在低版本运行，也不会出现在低版本不能构建的问题，因为Visual Studio及其编译器工具集可以在低版本正常运行。构建错误通常是代码和配置文件，或者Visual Studio缺少组件。

我编译成功了，在Visual Studio里点击调试，是会要求我升级操作系统的

**Comment by SwimmingTiger** [comment]
你可以通过“重定目标解决方案”更换一个Windows SDK版本。

**Comment by SamNormcoreWayne** [comment]
> VS2019提示`function`不是`std`成员，或者`包含不能在当前代码页(936)中表示的字符`等错误的可以考虑我这个分支：
> 
> ```
> git clone -b vs2019fix https://github.com/SwimmingTiger/Terminal.git
> ```
> 
> 构建目标默认是ARM64，请切换为x64或者x86，否则构建后不能运行，并且通常不能构建（没有安装ARM工具集）。
> 
> 提示`wil/Common.h`找不到的，请运行
> 
> ```
> git submodule update --init --recursive
> ```
> 
> 提示程序集缺失的，请用Visual Studio打开解决方案，在解决方案上右击，点击“还原NuGet包”，或者运行
> 
> ```
> dep\nuget\nuget.exe restore OpenConsole.sln
> ```
> 
> （如果该命令找不到，请进行`git submodule update --init --recursive`）
> 
> 如果提示缺少构建工具集，请为VS2019安装以下组件（可能有多余，我不知道哪个多余）：
> 
> * 工作负载：
>   
>   * 通用Windows平台开发
> * 单个组件
>   
>   * C++ ATL for v142 生成工具 (x86和x64)
>   * Windows 10 SDK （任一版本，但不能比你当前系统版本高，否则构建出的程序可能无法运行）
>   * Windows 通用 C 运行时
>   * NuGet 包管理器
>   * C# 和 Visual Basic
>   * C++ 核心功能
>   * C# 和 Visual Basic Roslyn 编译器
>   * MSBuild
>   * MSVC v142 - VS 2019 C++ x64/x86 生成工具
>   * Windows 通用 CRT SDK
> 
> 构建完成后怎么安装？请在解决方案上右击，选择“部署解决方案”，“Windows Terminal (Preview)”将出现在开始菜单。
> 
> 最后，如果找不到多标签功能，请按Ctrl+T。
> 
> 最终效果：
> ![最终效果](https://user-images.githubusercontent.com/4986069/57313957-3cd69280-7123-11e9-93a6-cfe7c8b6ecca.jpg)

谢谢大佬。不过我也是README没看仔细。

**Comment by Naibaowjk** [comment]
> VS2019提示function不是std成员，或者包含不能在当前代码页(936)中表示的字符等错误的可以考虑我这个分支：
> git clone -b vs2019fix https://github.com/SwimmingTiger/Terminal.git
> 
> 构建目标默认是ARM64，请切换为x64或者x86，否则构建后不能运行，并且通常不能构建（没有安装ARM工具集）。
> 提示wil/Common.h找不到的，请运行
> git submodule update --init --recursive
> 
> 提示程序集缺失的，请用Visual Studio打开解决方案，在解决方案上右击，点击“还原NuGet包”，或者运行
> dep\nuget\nuget.exe restore OpenConsole.sln
> 
> （如果该命令找不到，请进行git submodule update --init --recursive）
> 如果提示缺少构建工具集，请为VS2019安装以下组件（可能有多余，我不知道哪个多余）：
> 
> 
> 工作负载：
> 
> 通用Windows平台开发
> 
> 
> 
> 单个组件
> 
> C++ ATL for v142 生成工具 (x86和x64)
> Windows 10 SDK （任一版本，但不能比你当前系统版本高，否则构建出的程序可能无法运行）
> Windows 通用 C 运行时
> NuGet 包管理器
> C# 和 Visual Basic
> C++ 核心功能
> C# 和 Visual Basic Roslyn 编译器
> MSBuild
> MSVC v142 - VS 2019 C++ x64/x86 生成工具
> Windows 通用 CRT SDK
> 
> 
> 
> 构建完成后怎么安装？请在解决方案上右击，选择“部署解决方案”，“Windows Terminal (Preview)”将出现在开始菜单。
> 最后，如果找不到多标签功能，请按Ctrl+T。
> 最终效果：
> 
> 
> 谢谢大佬。不过我也是README没看仔细。

感觉VS每个人的问题都不一样。。真是奇怪

**Comment by VATALU** [comment]
> B站有教安装的视频：https://www.bilibili.com/video/av51726432/
> 相关编译包下载地址：https://cloud.baiyue.one/?/Tool/

这个编译好的版本，打开是这样的
<img width="826" alt="批注 2019-05-08 014741" src="https://user-images.githubusercontent.com/30646562/57321159-4f58c800-7133-11e9-8fdd-97df102d07ad.png">

**Comment by Dolphinsimon** [comment]
> > B站有教安装的视频：https://www.bilibili.com/video/av51726432/
> > 相关编译包下载地址：https://cloud.baiyue.one/?/Tool/
> 
> 这个编译好的版本，打开是这样的
> <img alt="批注 2019-05-08 014741" width="826" src="https://user-images.githubusercontent.com/30646562/57321159-4f58c800-7133-11e9-8fdd-97df102d07ad.png">

#i-built-and-ran-the-new-terminal-but-it-looks-just-like-the-old-console-what-gives
[https://github.com/microsoft/Terminal#i-built-and-ran-the-new-terminal-but-it-looks-just-like-the-old-console-what-gives](url)

**Comment by zadjii-msft** [comment]
@VATALU this is by design - try pressing Ctrl+t.

**Comment by ddzy** [comment]
win10-1903已入坑

**Comment by yang-shuaijun** [comment]
编译两天了，狂报错，哎！

**Comment by pq1949** [comment]
![image](https://user-images.githubusercontent.com/9245399/57355777-60d8b900-71a1-11e9-8fe5-4823601b4437.png)
win10升级到预览版才安装成功，感觉就多了个透明和多标签页的效果，期待继续更新

**Comment by gotliuyan** [comment]
一点也不炫酷，还不如继续用console emulator

**Comment by Naibaowjk** [comment]
我找了一个人家编译好的直接就装了。。Am 08.05.2019 08:28 schrieb Picoman Yang <notifications@github.com>:编译两天了，狂报错，哎！

**Comment by miniksa** [comment]
I've changed the title to English for triage purposes. We think that this is related to and/or will resolve itself with #565 and #489

**Comment by planetPocket** [comment]
> conpronps.lib不是有效的win32程序，，release不了。。

这个问题+1，1903的版本

**Comment by miniksa** [comment]
This appears to have sorted itself out. Closing.

**Comment by kid1412621** [comment]
error : The OutputPath property is not set for project 'TerminalControl.vcxproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Release' Platform='x64'. This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform. 
HELP

**Comment by uk0** [comment]
deal all this release Now !! https://github.com/uk0/microsoft-terminal-release

**Comment by haojie1** [comment]
显示没有<command.h>怎么吧啊？求助

**Comment by Oldmoooon** [comment]
搞到午夜，有点绝望。
![image](https://user-images.githubusercontent.com/13718160/59554487-2d761f00-8fd6-11e9-9a63-b6ec7bc15aba.png)

**Comment by Oldmoooon** [comment]
> 搞到午夜，有点绝望。
> ![image](https://user-images.githubusercontent.com/13718160/59554487-2d761f00-8fd6-11e9-9a63-b6ec7bc15aba.png)

破案了，是windows defender阻止了程序访问我的目录，关掉就好了。
