### ISSUE TITLE
Determine proper behavior for single-cell selection; only highlight on click + threshold-drag?

### ISSUE THREAD

**Issue by aybiss** [microsoft/terminal#5082]
# Environment

```
Windows 10 v1909
Windows Terminal 0.10.781.0
```

# Steps to reproduce

Click anywhere in the text on an already focused Windows Terminal window.

# Expected behavior

Window should do nothing since it is already focused. Text should not be highlighted because there has been no mouse drag.

# Actual behavior

The character that's clicked on is now going to overwrite the clipboard if I right click to paste something I've just hunted out in another program or window. I will often fail to notice I've highlighted anything, and even if I do catch myself before muscle memory has completed the action, I cannot "unhighlight" text, and am basically screwed at this point. This means I have to go through with the failed paste operation, if I haven't already, and then go hunt out what I was about to paste again.

This is a pet hate of mine. Please make it so that clicking on the window is not interpreted as marking text, or at least provide an option for this. You would simply have to wait for a mouse drag event, which is what people generally do when they DO want to copy some text, so most people would not even notice this change unless they often copy a single character from a console.

**Comment by egmontkob** [comment]
> wait for a mouse drag event

Considering e.g. traditional mouse where clicking almost certainly includes a tiny movement too, it's probably better to introduce some drag threshold (at least that's what VTE does).

**Comment by BartXZX** [comment]
Would also love it if a single non-dragging click would deselect anything currently selected. That would prevent me from having to press ESC to deselect.

**Comment by aybiss** [comment]
> Would also love it if a single non-dragging click would deselect anything currently selected. That would prevent me from having to press ESC to deselect.

Yes that would be an excellent addition too.

**Comment by DHowett-MSFT** [comment]
Honestly, it's my least favorite part of the traditional console that you can start _and finish_ a selection with a single click.

Putty's threshold is "one cell"; Console's is 0. I'd very much like to get to somewhere between 0.25 and 1 cells as our threshold.

**Comment by DHowett-MSFT** [comment]
I'm triaging this as a bug-task into v1 to force the discussion. :smile:

**Comment by aybiss** [comment]
> I'm triaging this as a bug-task into v1 to force the discussion. 😄

Thanks, I appreciate it. This is the whole reason I go looking for console alternatives for Windows - so that they'll behave more like a Linux console in this one critical area.

**Comment by egmontkob** [comment]
See also closely related #5099.

**Comment by DHowett-MSFT** [comment]
Marking this v2-scrubbed as Kayla and I discussed scoping it into the milestone. :smile:

**Comment by DHowett-MSFT** [comment]
Sorry, _v1-scrubbed_

**Comment by aaron-oxford** [comment]
I just got the new version and it is now working as desired. Fantastic job guys!

**Comment by DHowett-MSFT** [comment]
Glad we could help :smile:
