### ISSUE TITLE
copyOnSelect does not work

### ISSUE THREAD

**Issue by Dibbyo456** [microsoft/terminal#5085]
# Environment

```none
Windows build number: 10.0.18363.720
Windows Terminal version: 0.10.781.0
```

# Steps to reproduce

Enable `copyOnSelect` on `profiles.json`
```
"defaults":
{
    "copyOnSelect": true
},
```

# Expected behavior

Auto copy selected text on terminal (cmd or bash)

# Actual behavior

Not auto copying the selected text.

**Comment by Qantex** [comment]
.
