### ISSUE TITLE
 Adding a new custom profile with the new UI-Button

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5086]
# Description of the new feature/enhancement

**This function is intended to help computer scientists/developers to solve problems faster by adding a button to the context menu. The button has a function that consists in creating custom profiles.**

- **This function enables computer scientists / developers to solve problems faster and easier.**

# Proposed technical implementation details (optional)
![Anmerkung 2020-03-23 161130](https://user-images.githubusercontent.com/47790579/77331877-9d61c480-6d21-11ea-98b9-ff8128c4c8e4.png)

**Comment by zadjii-msft** [comment]
What would that button do all by itself? It would need to display some sort of UI for the user to interact with to create the profile, right? The better solution here would just be to have a whole settings UI, which we're tracking over in #1564. 

/dup #1564

**Comment by Qantex** [comment]
That's also a **good idea**! 😄👍

**Comment by Qantex** [comment]
But it would be much faster to create profiles instead of clicking Settings.

**Comment by zadjii-msft** [comment]
Sure, but we'd still fundamentally need a settings UI in the first place to be able to support this ask at all. Without that UI, this button doesn't really make sense.

Plus, we'd have to consider if the frequency in which users create new profiles is high enough to justify cluttering that flyout with another button. We've been pretty reluctant to add buttons to that flyout in general. It's already easy enough for the Windows context menu to get easily cluttered, making each and every option in it so we're trying to avoid that mistake.

My hypothesis would be that creating profiles is something that would happen far less frequently than opening that dialog for opening a new tab, and adding that additional menu item would be less useful than just having the button in the settings UI.
