### ISSUE TITLE
exit on remote system after privilege escalation clears clipboard

### ISSUE THREAD

**Issue by CosmicCatnap** [microsoft/terminal#5087]
# Environment

```Microsoft Windows [Version 10.0.18362.720]```

# Steps to reproduce

1. ssh to remote linux system
2. escalate to root
3. copy and paste a command
4. issue exit command to return to login user
5. notice the clipboard has been cleared after this command

# Expected behavior

clipboard should persist

# Actual behavior

clipboard is empty

**Comment by DHowett-MSFT** [comment]
Thanks for the report! There's only one way for a text-mode application, especially one on Linux (or OS X), to change the state of the clipboard on the computer running the terminal. That's to use an escape sequence -- `OSC 52`, if i recall -- that tells the terminal what to put on the clipboard.

Terminal has never implemented OSC 52, which means that all clipboard modification happens as a result of user action. There's nothing that `sudo` or `exit` or your shell can do to change the contents of the clipboard today.

Can you share a screen recording of this happening?
Thanks!

**Comment by CosmicCatnap** [comment]
If you are unable to reproduce or unwilling I can't help further. Good luck

**Comment by DHowett-MSFT** [comment]
I'm willing to reproduce, I just can't. There's nothing in Terminal that knows anything about elevation, especially not _over ssh_, so I can't even begin debugging this without additional information.
