### ISSUE TITLE
The Vista-style frame appears briefly when the Terminal enter/exits fullscreen

### ISSUE THREAD

**Issue by REALTIV** [microsoft/terminal#5089]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.10.781.0

Any other software?
```

# Steps to reproduce

- **Start Windows Terminal**
- **Press the F11 key and keep it pressed**
- **Move the mouse over the Exit, Minimize and Fullscreen buttons**

# Expected behavior

- **That the Windows Terminal user would see the Fluent design**

# Actual behavior

- **The Vista-style frame appears**

**Comment by DHowett-MSFT** [comment]
Thanks for the report! Unfortunately, this is _very_ difficult for us to fix :smile: because nobody should be holding down <kbd>F11</kbd>, it's an uncommon scenario. Because it is so uncommon, I cannot commit engineering resources to fixing it.

**Comment by Qantex** [comment]
Thanks for the answer! 👍😄

**Comment by zadjii-msft** [comment]
I could have sworn there was a dupe for this laying around, but I can't find it. To be clear - this is a real bug with how we're handling fullscreen, and I've updated the title to match.

**Comment by Qantex** [comment]
Thanks! 😄

**Comment by Qantex** [comment]
The Vista-style appears not only on the Windows Terminal, but also on other Microsoft products.

**Comment by Qantex** [comment]
The Vista style appears not only on the Windows terminal, but also on other software products that are also developed in the Fluent-design.

**Comment by CharlesPMaxwell** [comment]
@AVDAX Good research, I wish you all the best in research and study!
---
@DHowett-MSFT  **I wish the whole Microsoft team good health!**
---
### That's what I wanted to tell you!

**Comment by AVDAX** [comment]
@CharlesPMaxwell Thank you very much! :)

**Comment by itsme-alan** [comment]
Is this a bug with Windows itself?

**Comment by zadjii-msft** [comment]
Oh hey, this looks fixed!

![gh-5089-no-repro-002](https://user-images.githubusercontent.com/18356694/145428914-fa4ac0d5-a61e-4d7c-a598-ad6464f7cd14.gif)

(screen2gif must have clipped exactly all the frames where the terminal was fullscreen, but just know that I was holding F11 there.)

Either in one of the recent fullscreen PRs, or maybe just in Windows 11 itself. Thanks!
