### ISSUE TITLE
Rendering problem with multi-line insertion in Powershell

### ISSUE THREAD

**Issue by e-Dark** [microsoft/terminal#5097]
# Environment
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0

# Steps to reproduce
1. Open Windows Terminal with config Powershell
2. Insert multi-line string with total rows more then Terminal window height.
Ex.: inserting 40 lines from test-001 to test-040 into multi-line string.
3. As a result - multiple duplicates of string in Terminal with errors.
![image](https://user-images.githubusercontent.com/61321141/77417669-bed0b800-6dd6-11ea-8c2d-9b2acd715c64.png)

Looks like PSReadLine bug, but in Powershell window I don't have the problem
![image](https://user-images.githubusercontent.com/61321141/77418049-677f1780-6dd7-11ea-8925-92e49f111b57.png)
![image](https://user-images.githubusercontent.com/61321141/77418189-9b5a3d00-6dd7-11ea-9454-40e575eb0c7d.png)

**Comment by zadjii-msft** [comment]
This is definitely a bug that should be filed over at https://github.com/lzybkr/PSReadLine/issues/new - You'll get the same behavior in the legacy console by setting the console "screen buffer height" to be the same as the height of the window, or tried doing this right near the end of the buffer.
