### ISSUE TITLE
Error when adding Anaconda prompt

### ISSUE THREAD

**Issue by sbacelar** [microsoft/terminal#5100]
I am running  `Windows 10.0.18363.720` and `Terminal 0.10.781.0`. 
I tried to add Anaconda prompt to Windows Terminal but I receive a `failed to load settings` error on `commandline` (second line) that I can not explain. I have run that command on cmd with success. 
```
            {
                // Make changes here to the Anaconda profile
                "commandline": "cmd.exe /K C:\Users\sbac\Anaconda3\Scripts\activate.bat",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6102}",
                "name": "Anaconda",
                "hidden": false
            },
```

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
You need to make sure to escape the backslashes in the commandline - try `"commandline": "cmd.exe /K C:\\Users\\sbac\\Anaconda3\\Scripts\\activate.bat",`

**Comment by DHowett-MSFT** [comment]
Based on your upvote of zadjii's comment, I'm going to guess that this solved it for you?
