### ISSUE TITLE
Maximizing the size of any pane in a tab.

### ISSUE THREAD

**Issue by yasintz** [microsoft/terminal#5101]
# Description of the new feature/enhancement
It would be nice to have such a shortcut.
A similar question is available in this link for tmux : https://superuser.com/q/238702
> Sometimes it would be very useful to maximize a pane in tmux and then restore it to it's previous size. I've been reading the manual and I can't find a way. What I've come up with is that I could bind a key to resize the pane to "max" width, and another key to restore it to some predefined width. Of course this has its drawbacks, so I'm wondering if anyone has a better idea.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #996 for more discussion.

/dup #996
