### ISSUE TITLE
Cleartype Color Issues

### ISSUE THREAD

**Issue by Nosamdaman** [microsoft/terminal#5102]
# Environment

Windows build number: [Version 10.0.18363.720]
Windows Terminal version: 0.10.781.0

Font: Cascadia Code
Theme: Solarized Dark

# Steps to reproduce

Set font anti-aliasing to `cleartype`.

# Expected behavior

The font color should not shift. It should look like this:
![normal](https://user-images.githubusercontent.com/54364725/77441468-d6e90d00-6dbf-11ea-81aa-7865269a5722.png)

# Actual behavior

The color shifts to something more blue:
![shift](https://user-images.githubusercontent.com/54364725/77441530-e9fbdd00-6dbf-11ea-8225-7357772d3050.png)

**Comment by zadjii-msft** [comment]
This is curiously similar to #5098

**Comment by Nosamdaman** [comment]
I wondered if they had the same root cause, but I figured I should share my experience.

**Comment by DHowett-MSFT** [comment]
Thanks for sharing! In the interest of consolidation, I'm gonna dupe this one up to #5098. If they don't turn out to be the same, I bet we'll figure it out pretty quick. This'll serve to link them up :smile:

/dup #5098
