### ISSUE TITLE
environment variable changes (like PATH) are not applied during runtime

### ISSUE THREAD

**Issue by bernstein82** [microsoft/terminal#5103]
# Environment
```none
Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal Version: 0.10.781.0
```

# Steps to reproduce
1) echo $env:Path
2) change environment variables using Control Panel > System > ...
3) open new powershell tab
4) echo  $env:Path

# Expected behavior
environment variable change is reflected in :
- new powershell tab
- currently open poweshell tabs

# Actual behavior
environment variable change is only reflected after closing & reopening microsoft terminal application

**Comment by creativenobu** [comment]
I am also getting this issue. Steps I followed:
+ Keep the powershell tab open
+ Add a new environment variable via control panel: `PROJECTS` set to `D:\projects`
+ Close the current powershell tab and open a new one
+ Check if the variable is set: `echo $env:PROJECTS`
+ I get __no__ value back.

However, closing the terminal window and re-opening solves the issue.  But not really a solution if you have multiple tabs open.
