### ISSUE TITLE
Changing the position of the buttons in the context menu

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5108]
# Description of the new feature/enhancement
It would be a very good idea to include this feature in the new settings UI. ([#1564)](https://github.com/microsoft/terminal/issues/1564)

- **A feature that allows Windows terminal users to vertically change the position of buttons in the context menu.**

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Thank you! This is covered by /dup #1571. That feature request is about letting you configure the order of your menu.

**Comment by Qantex** [comment]
Hello @DHowett-MSFT,

- **thanks for the answer! 😁**

With kind regards
Michael
