### ISSUE TITLE
Deleting Chinese IME during composition sends the first character to the Terminal

### ISSUE THREAD

**Issue by leonMSFT** [microsoft/terminal#5110]
# Steps to reproduce
Related to #5054
Start a Chinese IME composition without completing it/selecting the characters e.g. "wei'yuan", then delete the characters.

# Expected behavior
There should be no characters left on the screen.

# Actual behavior
The letter "w" will appear in the buffer.

# Cause
We're receiving a `CompositionCompleted` event before we receive a `TextUpdating` event for the final character "w" to be deleted. This causes us to believe that "w" is a completed composition, so we send it to the terminal. We then receive the `TextUpdating` event right after to tell us to delete the "w", so it disappears from the `_inputBuffer`.

**Comment by DHowett-MSFT** [comment]
Tagging this into v1.x -- feel free to override me

**Comment by skyline75489** [comment]
As weird as it may seem, the behaviour of WT is actually aligned with stock `cmd.exe`. This bug also exists there. Exactly same bahaviour. Does this mean it is what we actually expect it to be? I'm confused...

**Comment by DHowett-MSFT** [comment]
For version 1, "works like cmd.exe" will be acceptable. We'd love to do better than cmd.exe, but our deadlines are getting closer every day :grin:

**Comment by leonMSFT** [comment]
I'm surprised cmd behaves the same way! It kinda sounds like both Terminal and cmd use the same underlying api, making them both able to repro this bug.
