### ISSUE TITLE
Add synchronization/update of Windows account names in Windows Terminal

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5111]
# Description of the new feature/enhancement

- **This function is used to update/synchronize the newly defined Windows account name directly in the Windows Terminal.**

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
What do you mean by this? Where would the user's account name be displayed? Could you add more details?

**Comment by Qantex** [comment]
Hello @zadjii-msft,

- **Sure. For example, if a Windows Terminal user changed his or her Windows account name to Hanna, the Windows account name should also be synchronized/updated in Windows PowerShell in real time.**

With kind regards
**Michael**

**Comment by DHowett-MSFT** [comment]
Powershell uses the name of the user's _profile folder_, and profile folders are never renamed on Windows. It's a dangerous system-wide operation.

**Comment by DHowett-MSFT** [comment]
:smile:
