### ISSUE TITLE
Laggy mouse cursor on high fps / gsync monitor

### ISSUE THREAD

**Issue by tenox7** [microsoft/terminal#5112]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Nvidia GeForce drivers
```

# Steps to reproduce

Use a G-Sync High Framerate monitor.
Enable high framerate in Windows, eg 120 Hz or 144 Hz.
Launch Windows Terminal app

# Expected behavior

FPS should remain at 120/144Hz.
Mouse moves smoothly.
Window dragging works smoothly.

# Actual behavior

Framerate drops to 60 Hz.
Mouse cursor is laggy, draggy and jittery.
Window dragging is laggy and jittery.

**Comment by DHowett-MSFT** [comment]
Thanks! Please be sure to search before reporting a new issue. This is a /dup of #649
