### ISSUE TITLE
How to run a bat file in current windows terminal instead of open new cmd window?

### ISSUE THREAD

**Issue by xinkunZ** [microsoft/terminal#5114]
* I want to know, how to run a bat file just in the windows terminal
* I have try to use `call` or `start`, but it did not work
* everytime I open a bat file, It always open a ugly cmd window
* anyone can help？

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This isn't something that's really supported by the Terminal currently. You can refer to #492 for more details.

You _might_ be able to use the `wt` [commandline arguments](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) to serve the purpose you want. Something like `wt cmd /c my_bat_file.bat` would work to open a new Windows Terminal window running `my_bat_file.bat`.
