### ISSUE TITLE
LaTeX code support in Windows Terminal

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5115]
# Description of the new feature/enhancement

- **The ultimate tool for displaying fractions and many mathematical characters is LaTeX.
 LaTeX or TeX is a notation for mathematical characters, a so-called typesetting system. The input is done with the keyboard. Formatting and mathematical characters are entered in text form and then converted.** 

**LaTeX code example:** 

- **`\frac{a}{b}`**

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Okay so I'm not sure what you're really looking for here - Do you want LaTeX rendering directly within the Terminal? A LaTeX shell application?

**Comment by Qantex** [comment]
Hello @zadjii-msft ,

> A LaTeX shell application?
- **Yes, would that be possible?**

With kind regards

- **Michael**

**Comment by zadjii-msft** [comment]
I mean, there's https://github.com/nilqed/latex2sixel

Which would depend on the Terminal supporting sixel graphics, #448

**Comment by Qantex** [comment]
Would it be possible for the Microsoft team to release their own version which is always checked for errors?

With kind regards

- **Michael**
