### ISSUE TITLE
Windows Terminal Does Not Render 4-digit unicode.

### ISSUE THREAD

**Issue by stuartthomson** [microsoft/terminal#5116]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
Git Bash: 4.4.23(1)-release (x86_64-pc-msys)
Mintty: 3.1.0 (x86_64-pc-msys)
```

# Steps to reproduce

1. Install windows terminal.
2. Install git bash.
3. Use git bash in windows terminal.
4. Run `echo -e '\u25B6'`

# Expected behavior
Expect to see (from running git bash in mintty):
![image](https://user-images.githubusercontent.com/1838353/77557904-33c4f000-6eb2-11ea-8d35-5a42512f8d54.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/1838353/77557973-4d663780-6eb2-11ea-92e4-4230c112319e.png)

**Comment by DHowett-MSFT** [comment]
This is exactly what it looks like when _bash_ isn't translating the escape code for you. How are you launching git bash?

**Comment by stuartthomson** [comment]
@DHowett-MSFT Thanks for getting back to me.
Example 1 (the working example) is launched using the 'Git Bash', an executable at `C:\Program Files\Git\git-bash.exe`.
Example 2 is using windows terminal, with the following profile:
```            
           {
                "guid": "{e4b90cc8-3358-4c53-bd74-bcc1c3cd9144}",
                "name": "Git bash",
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "hidden": false,
                "snapOnInput": true,
                "startingDirectory": "C:\\projects",
                "fontFace": "Fira Code",
                "colorScheme": "One Half Light",
                "cursorColor": "#000"
            }
```
I imagined that the 'bash' executable above would do the translation when running in windows terminal, but perhaps it is actually mintty which does it in the working example?

**Comment by DHowett-MSFT** [comment]
It's definitely bash that does the translation. Can you try changing your commandline from `bash.exe` to `bash.exe -li`?

**Comment by stuartthomson** [comment]
Yes, that works now - thank you very much! I'm not sure at what point the login changes something to allow this, but I can look into that on my own.

Thanks.
