### ISSUE TITLE
Windows Terminal sometimes does not handle processes correctly

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5117]
# Environment

```none
Windows build number: 10.0.18363.752
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
```

# Steps to reproduce

- The processing **error occurs only rarely**

- **Start Windows Terminal**

# Expected behavior

- **Windows Terminal should add Ubuntu to the context menu**

# Actual behavior

- **Windows Terminal has not added Ubuntu to the context menu**

**Comment by DHowett-MSFT** [comment]
Unfortunately, we cannot reproduce this bug without more information.

If you run ubuntu directly, does it take a long time to start up sometimes?

**Comment by Qantex** [comment]
Hello @DHowett ,

- **yes, sometimes it takes a very long time for Ubuntu to start properly. This can also be due to the computer performance.**

With kind regards
**Michael**

**Comment by zadjii-msft** [comment]
Out of curiosity, how reliably are you hitting this? 

If you've already got Ubuntu running (like, in another `conhost.exe` window), then open the Windows Terminal, does "Ubuntu" show up in the list of profiles consistently?

**Comment by Qantex** [comment]
Hello @zadjii-msft ,
Ubuntu was not started before, only Windows Terminal.

With kind regards
**Michael**

**Comment by zadjii-msft** [comment]
That doesn't actually answer either of my questions...

**Comment by Qantex** [comment]
Hello @zadjii-msft ,
Yes, Ubuntu is displayed even if Ubuntu was started in Conhost.

With kind regards
**Michael**

**Comment by DHowett-MSFT** [comment]
It looks like this is because WSL is stalled. It would be worth filing a bug on microsoft/wsl explaining that sometimes WSL takes multiple seconds to start up. One of the engineering leads helping with WSL told me that it should never take more than 2 seconds to answer Terminal's question about what distributions exist.
