### ISSUE TITLE
Error codes and crashes occur when you hold down the Ctrl key c and open a new tab like Azure Cloud Shell

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5118]
# Environment

```none
Windows build number: 10.0.18363.752
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
```

# Steps to reproduce

- Start Windows Terminal
- Start Windows PowerShell
- Hold down the Ctrl C key
- Open a new Windows PowerShell tab or other

# Expected behavior

- **No error should be displayed when a new Windows PowerShell tab is opened by holding down Ctrl C.**

# Actual behavior

- **An error is displayed when a new Windows PowerShell tab is opened by holding down Ctrl C.**

**Comment by zadjii-msft** [comment]
Could you share the error that's displayed?

**Comment by Qantex** [comment]
Hello @zadjii-msft ,

- Sure, the code with which the process was terminated is:
**`Process terminated with code 3221225786]`**. **Sometimes it also comes to crashes**

With kind regards
Michael

**Comment by zadjii-msft** [comment]
Thanks for following up! looks like this is #3869. Please make sure to search for duplicates when filing new issues ☺️ 

/dup #3869 #4353 #4574 #4580

**Comment by Qantex** [comment]
I just noticed that this error occurs not only when pressing Ctrl C, but also when pressing Ctrl G or Ctrl T. @zadjii-msft

**Comment by zadjii-msft** [comment]
Is it just <kbd>Ctrl+G</kbd> & <kbd>Ctrl+T</kbd>, or _any input_ that's causing that error? I'm not seeing that with those keys on my build, but I'm running a build with some different commits than 0.10 so it's possible there's a fix being prepared for 0.11

**Comment by Qantex** [comment]
Errors and crashes also occur when `Ctrl V` and `Ctrl B` are pressed.

**Comment by DHowett-MSFT** [comment]
Okay, the crash on input sometimes is probably related to the bug fixed by #5051 then

**Comment by Qantex** [comment]
Hello @DHowett ,

The problem is that the problem still exists.

With kind regards
**Michael**

**Comment by DHowett-MSFT** [comment]
Yes, because that pull request isn't merged, and you do not have a version with that pull request in it :wink:

**Comment by Qantex** [comment]
**Thanks for the answer.** 😁
From my point of view, I thought the problem was solved because you wrote that the problem was solved. 
I thought that this problem was already integrated in this version of Windows Terminal.

**Comment by DHowett-MSFT** [comment]
Not yet :smile: It is going t be available in an updated version soon.
