### ISSUE TITLE
An option to swallow the trailing CRLF on paste

### ISSUE THREAD

**Issue by wasker** [microsoft/terminal#5120]
# Description of the new feature/enhancement

Whenever I paste a line with a trailing CRLF in Terminal, it gets executed immediately. I'd like to have an option for Terminal to swallow the trailing CRLF, so it would be safe to paste text.

# Proposed technical implementation details (optional)

I don't have any suggestions on implementation, but ConEmu has an option like that.

**Comment by DHowett-MSFT** [comment]
Yeah, we might as well have something like this. Somebody needs to suggest a config option (and whether it's profile-specific), and explain how it works when there's multiple newlines.

For reference, #395 is the holistic solution to this problem when all shells and applications eventually support it.

**Comment by zadjii-msft** [comment]
You know, we also discussed this over in 9400 and have a proposed fix in #11473. To quoth:

> just to trim the trailing newline if that's the only one in the paste contents. To quote: "It doesn't make sense to be warned for multiple lines, but copy a single line and try to paste it AND ONLY SEE ONE LINE IN THE DIALOG. That's dumb".

@wasker you think that'll work for you?

**Comment by wasker** [comment]
@zadjii-msft Yeah, I think this is a decent resolution for this bug, thanks!
