### ISSUE TITLE
Please add option to disable dialog "Do you want to close all tabs?"

### ISSUE THREAD

**Issue by 0ric1** [microsoft/terminal#5125]
When closing the Windows Terminal with multiple tabs a dialog opens "Do you want to close all tabs?" with two buttons "Close all" and "Cancel".
I would like to see a third button or checkbox "Never ask again" because it would save a lot of unnecessary clicks - I see that I have multiple tabs open and when I close the terminal it is clear that all tabs are closed - in Firefox there exists a similar dialog, see 
e.g. https://superuser.com/questions/1183272/re-enable-the-multiple-tabs-close-warning-in-firefox-50/1271027
Thanks

**Comment by DHowett-MSFT** [comment]
Thanks for the request! There's an option you can set in your `profiles.json` called `confirmCloseAllTabs`. If you set it to _false_, you will never be asked again.

**Comment by thinkjrs** [comment]
For 

> Thanks for the request! There's an option you can set in your `profiles.json` called `confirmCloseAllTabs`. If you set it to _false_, you will never be asked again.

Here's a link to [current docs (as of Oct. 2020) on the matter from MSFT](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#hide-close-all-tabs-popup), in case this helps future travelers.

**Comment by brandonjclark78** [comment]
Well, I just opened %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json and there is no option in the profiles.json by default.

For those of you who had no idea WHERE to put this, this is what worked for me...


First, Open your profiles.json file:

Terminal (stable / general release): %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
Terminal (preview release): %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json
Terminal (unpackaged: Scoop, Chocolately, etc): %LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json

Then, all the way at the bottom enter the following `"confirmCloseAllTabs": false`

I had made a couple of changes to my file so the "end" where I entered this now looks like:


    "showTerminalTitleInTitlebar": false,
    "tabWidthMode": "titleLength",
    "confirmCloseAllTabs": false
}

Hope this helps.

**Comment by githik999** [comment]
"copyFormatting": "none",
  "copyOnSelect": false,
  "confirmCloseAllTabs":false,
  "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

 click settings and click open json file

edit settings.json add one line as show

"confirmCloseAllTabs":false,

works 2022 05 08

**Comment by pizzaazzip** [comment]
Clarification for future readers, I think what @githik999 is trying to say is Ctrl+F for _copyFormatting_ or something similar  and stick _ConfirmCloseAllTabs":false,_ in that block.  This isn't at the _very bottom_ as some of the other comments mention, in fact for me I've very far from the bottom.  I hope this helps.
 

![image](https://user-images.githubusercontent.com/3604065/197013657-67bd4312-06e5-4d17-8c75-8331279eaca9.png)

**Comment by notrealdev** [comment]
Hi, how to Warn if only one tab?
