### ISSUE TITLE
Cannot Open include file: 'wil/Common.h': No Such File Or Directory

### ISSUE THREAD

**Issue by harrcorr** [microsoft/Terminal#513]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

**Comment by zadjii-msft** [comment]
Please read the README.

`git submodule update --init --recursive`

**Comment by komatera** [comment]
Microsoft Windows [Version 10.0.17763.437]
Trying to compile in VS2017 by pressing the button.
wil/Common.h: No such file or directory 18 times.

**Comment by komatera** [comment]
> Please read the README.
> 
> `git submodule update --init --recursive`

It DOESNT help!

**Comment by Rowdster** [comment]
> Please read the README.
> 
> `git submodule update --init --recursive`

How do we properly "git" this project?  

C:\Projects\Terminal-master>git fetch https://github.com/microsoft/Terminal.git
**fatal: not a git repository (or any of the parent directories): .git**

**Comment by DHowett-MSFT** [comment]
it looks like you downloaded the source by choosing “download ZIP.” That will never work as a git repository.

Please clone the repository using “git clone”.

________________________________

**Comment by thanabodi** [comment]
I used git clone but have same error.

**Comment by HelloWorDomain** [comment]
I get the same Error,I will try to git clone

**Comment by josephwinston** [comment]
Another note.  The included files have one case while the #include uses a different one.

eg
```
src/propsheet/precomp.h:#include <wil/Common.h>
src/terminal/adapter/MouseInput.cpp:#include <wil\Common.h>
src/terminal/input/terminalInput.cpp:#include <wil\Common.h>
src/tools/buffersize/main.cpp:#include <wil\Common.h>
src/tools/echokey/main.cpp:#include <wil\Common.h>
src/tools/vtpipeterm/main.cpp:#include <wil\Common.h>
```
```
find . -iname common.h
./dep/wil/include/wil/common.h
./dep/wil/tests/common.h
```

**Comment by do5rsw** [comment]
compling worked here after doing:
- git clone
- git submodule update --init --recursive
- open Solution in VC2019
- Restore NuGET Packages to Project

Thus the compiled application don't start....

**Comment by hyungonhwang** [comment]
> compling worked here after doing:
> 
> * git clone
> * git submodule update --init --recursive
> * open Solution in VC2019
> * Restore NuGET Packages to Project
> 
> Thus the compiled application don't start....

It worked.

$ git submodule update --init --recursive
Submodule 'dep/gsl' (https://github.com/microsoft/gsl) registered for path 'dep/gsl'
Submodule 'dep/wil' (https://github.com/microsoft/wil) registered for path 'dep/wil'
Cloning into 'C:/Users/HHG/Documents/Github/MS_Terminal/dep/gsl'...
Cloning into 'C:/Users/HHG/Documents/Github/MS_Terminal/dep/wil'...
Submodule path 'dep/gsl': checked out 'b74b286d5e333561b0f1ef1abd18de2606624455'
Submodule path 'dep/wil': checked out 'fbcd1d2abb558da4564ce343b688f7a658f51318'
