### ISSUE TITLE
Cursor position is not shown in not focused window

### ISSUE THREAD

**Issue by kasper93** [microsoft/terminal#5130]
# Environment
Windows 10.0.18363.0

# Steps to reproduce

1. Attach to the same tmux session from two terminals.
2. Not focused terminal should show and update cursor position

# Expected behavior

Just to make it clear, here goes table: 
| State \ Terminal 	| WT 	| Mintty 	|
|------------------	|----	|--------	|
| Focused |  ![image](https://user-images.githubusercontent.com/1126053/77643498-c079b780-6f5f-11ea-9eb4-49a97fc119c5.png) | ![image](https://user-images.githubusercontent.com/1126053/77643417-9cb67180-6f5f-11ea-9848-b8d6b0a77b36.png)| 
| Not Focused| ![image](https://user-images.githubusercontent.com/1126053/77643453-ad66e780-6f5f-11ea-94ea-b02f6102fdbc.png)| ![image](https://user-images.githubusercontent.com/1126053/77643559-e3a46700-6f5f-11ea-9591-d8512b3325c2.png)|

As you can see when WT is not focused cursor is not visible. Mintty shows it as not blinking dotted beam. And of course if you move the cursor in tmux session, position is updated in other one.

Of course tmux is not necessary to reproduce this. But it is convenient way to move cursor in not focused window ;p Also maybe there is an option to change this behavior that I missed?

**Comment by zadjii-msft** [comment]
@kasper93 What Windows Terminal version are you running?

**Comment by kasper93** [comment]
Latest master, 31efd69149c3b23c000c7491f98254356b1eaf34

**Comment by zadjii-msft** [comment]
You know what, that's what I get for trying to read issues before morning coffee. I'm pretty sure this is actually /dup #3062. It wasn't originally called out in that issue, but I've made sure to include this in that one. 

Thanks!

**Comment by kasper93** [comment]
> You know what, that's what I get for trying to read issues before morning coffee.

It is 2PM already :D /jk 

> I'm pretty sure this is actually /dup #3062.

Sure we can track it there. Once we get option I will be happy :) I see that cmd also hides cursor, maybe in WT actually changing default behavior would be good to keep it in line with other terminal emulators.
