### ISSUE TITLE
Include active sub process in tab title.

### ISSUE THREAD

**Issue by cpietrzykowski** [microsoft/terminal#5137]
# Description of the new feature/enhancement
With `cmd.exe` (for example) the title of the window includes the active process (when it differs from the shell). This would be welcome for `Windows Terminal`, most notably when there are multiple active tabs per host.

# Proposed technical implementation details (optional)
Either append the process name to the tab title, or provide some profile customisation formats to give the user some control over what/when the tab title is automatically updated to reflect shell activity.

When a non-trivial sub process is started (say if the task takes longer than a few hundred millseconds), append the process name to the tab title.

Some shells support dynamic prompts, but I don't think they're all consistent with how events are triggered. (understanding that not all processes would be visible to the host -- i.e. Powershell -> ssh -> vi; would only result in the tab title being "ssh".)

I'd be happy to take a stab at implementing this if a more seasoned maintainer could point me in the right direction.

**Comment by DHowett-MSFT** [comment]
Thanks for the request! I'd like for it to be part of the spec for #1320 -- we'll need to have a discussion about what we can do with our subprocess' token, and what makes sense to scrape to put in the title.

Mind moving future discussion for this feature over there?

Thanks!

/dup #1320

**Comment by cpietrzykowski** [comment]
> Thanks for the request! I'd like for it to be part of the spec for #1320 -- we'll need to have a discussion about what we can do with our subprocess' token, and what makes sense to scrape to put in the title.
> 
> Mind moving future discussion for this feature over there?
> 
> Thanks!
> 
> /dup #1320

No problem at all -- I assure you I searched countless times looking for a dupe, trying all manner of search terms.
