### ISSUE TITLE
Background tabs shouldn't actually render their contents

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5144]
I noticed that while running the tests in the Terminal that we always spend CPU/GPU time rendering a TermControl, even if the hosting tab is in the background. I'm not 100% certain about this, but it sure seemed like this was happening on my slaptop.

IIRC conhost does some logic to no-op rendering when it's minimized - `TermControl` should probably do something similar, including for when the tab isn't visible.

### Basic Repro

1. Open two tabs
2. In the first one, run the unit tests, or anything else that'll generate a ton of output.
3. Switch to the other tab, and do nothing in it.

### Expected

The GPU usage for the Terminal should be at the baseline usage for a terminal that's _not_ doing anything.

### Actual

GPU seemed to be getting the workout it normally does processing boatloads of output

**Comment by DHowett-MSFT** [comment]
I believe this is related to #1989

**Comment by zadjii-msft** [comment]
See, I don't think so. That one is more specifically the _whole window_, while this one's more specific _inactive_ tabs. I'm fine changing the other one to call out this case better though

**Comment by DHowett-MSFT** [comment]
I dunno, the title includes "control has been hidden". I think that a solution to one helps the other.
