### ISSUE TITLE
Small "unwrapping" quirk

### ISSUE THREAD

**Issue by nurbles** [microsoft/terminal#5146]
# Environment

```none
Windows build number: [Version 10.0.18363.720]
Windows Terminal version (if applicable): 0.10.7810

Any other software? no
```

# Steps to reproduce

I was using a CMD shell for a directory listing.  Some names (I used `dir *.c /s/b`) were longer than the window's width and were wrapped.  When I dragged the right side of the window, I was pleasantly surprised to see the long lines "unwrap" ... at least until a couple of them somehow 'grabbed' the next line from the screen and appended it to themselves.  I cannot see a way to attach a screen shot, so you can see it on my web site [bad unwrap example](https://www.svalli.com/files/badwrap.png)

If you want to use the _exact_ set of files I was using, get [calibre-master from github](https://github.com/kovidgoyal/calibre), extract the files and issue the same command I used (shown above and in the screen shot) with the window only about 60-70 characters wide.  Unfortunately, it doesn't always occur, but I got it to happen 3 out of 5 times, with different numbers of joined lines each time.

# Expected behavior

I expected each separate line of output to remain **separate**.

# Actual behavior

When the output is "unwrapped" as the window gets wider, some lines mysteriously join with the next (or previous?) line of output to make an even **longer** line that is still wrapped!

**Comment by zadjii-msft** [comment]
Okay this is the "you print a line that's exactly the width of the terminal, and we can't tell that the line actually broke there". It _might_ be #3088, but I'm not positive

**Comment by nurbles** [comment]
Yes, I think this is the same thing.  Sorry for the duplicate report, but I would **NEVER** have **EVER** found it searching for size/wrap issues as I was doing.  Feel free to close this and I will got vote for the referenced issue instead.

**Comment by zadjii-msft** [comment]
Haha I wouldn't blame you, that's probably only apparent to someone who's been spending his last 3 months working on [nothing but resizing](https://github.com/microsoft/terminal/issues/4200). Thanks for following up!

/dup #3088
