### ISSUE TITLE
Inserting overwrites existing text in C shell on FreeBSD

### ISSUE THREAD

**Issue by Lombra** [microsoft/terminal#5151]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
```

# Steps to reproduce

- SSH into a FreeBSD machine that uses C shell.
- Start typing a command in the prompt.
- Move the cursor back to any point before the end of the pending prompt command.
- Start typing.

# Expected behavior

Text is inserted at the cursor position.

# Actual behavior

Text overwrites existing text as it is written. It only appears overwritten, however, as pressing enter reveals that the command is executed as though the text was inserted correctly without overwriting. Furthermore, moving the cursor back to the end of the text reveals the "real" text as the cursor moves over it.

Both the console and WSL exhibits the same behavior. PuTTY does not.

The issue does not occur when using Bash instead of C shell on the target machine.

Here are some other people having the same issue on FreeBSD machines.
https://github.com/microsoft/WSL/issues/1756#issuecomment-335611423

**Comment by DHowett-MSFT** [comment]
If you have access to the `script` utility, can you capture a script? We can't troubleshoot this without knowing exactly what VT sequences the shell is emitting. :smile: Thanks!

**Comment by Lombra** [comment]
Here I typed `echo "hello world"`, and then went back to insert `new` before the `w`.
```
Script started on Sat Mar 28 00:03:53 2020
root@LP50:~ # echo "hello world"^H^H^H^H^H^H^[[4hn^[[4l^[[4he^[[4lw^[[4hw^[[4l^H^[[4h ^[[4l^M
hello new world
root@LP50:~ # ^D^H^Hexit

Script done on Sat Mar 28 00:04:11 2020
```
