### ISSUE TITLE
Bash Profile not sourcing on start up

### ISSUE THREAD

**Issue by Mansour-J** [microsoft/terminal#5154]
Bash profile is not sourcing on start up in Microsoft Terminal(git bash loaded in Microsoft Terminal) while in Git Bash Terminal it works fine.
```none

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```
# Steps to reproduce
1. install git_bash
2. Create a bash_profile
3. add following alias => `alias TEST="echo 'it works'"`
4. close both terminals (MS Terminal & Git Bash)
5. Open both and type `TEST`

# Expected behavior
Both work the same way. 

# Actual behavior
MS Terminal doesn't look up the `.bash_profile` on start up....

![image](https://user-images.githubusercontent.com/12991664/77811682-dbcff880-7100-11ea-8e72-fb6da9ca99a6.png)

**Comment by DHowett-MSFT** [comment]
Please make sure you are running `bash.exe -li`.
