### ISSUE TITLE
multiple cmd

### ISSUE THREAD

**Issue by ccapeng** [microsoft/terminal#5157]
{
                "guid": "{b463ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "sqlite",
                "commandline": "C://Windows//SysWOW64//cmd.exe /k \"D://db.bat\""
            },
            {
                "guid": "{b463ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "project",
                "commandline": "C://Windows//SysWOW64//cmd.exe",
                "startingDirectory": "d://dvp//project",
                "icon": "D:/dvp/project.ico"
            },

In the above profile, one open sqlite, the other open project folder.
Since they are in the same guid, only the second one show in the dropdown list.

Any ideas to work around it?

**Comment by DHowett-MSFT** [comment]
Yes: don’t give them the same guid. Delete the guids.
