### ISSUE TITLE
Arrow ligature does not render consistently in Windows Terminal

### ISSUE THREAD

**Issue by LukeJeremy** [microsoft/terminal#5158]
# Environment

| Software | Version |
-----------|-----------
| OS | Microsoft Windows NT 10.0.18363.0 |
| Windows Terminal | 0.10.781.0 |
| VS Code | 1.43.2 |
| Fira Code | 2.0.0
| Cascadia Code | 1911.210
| Powershell Core | 7.1.0-preview |
| Windows Powershell | 5.1.18362.752 |

Issue occurs using both fonts and both versions of Powershell.

# Steps to reproduce

Type the following sequence of characters into Windows Terminal.

`-> -> -> ->`

# Expected behavior

Four arrow ligatures are rendered, separated by spaces, as in VS Code.

![arrow_ligature_VSCode](https://user-images.githubusercontent.com/61129048/77817426-6b33d680-7116-11ea-8298-618411a02009.gif)

# Actual behavior

Two arrow ligatures are rendered. Every second `->` is rendered as a ligature.

![arrow_ligature_Windows_Terminal](https://user-images.githubusercontent.com/61129048/77817436-81da2d80-7116-11ea-9a0f-4b0b8326062f.gif)

**Comment by DHowett-MSFT** [comment]
If you look closely, you can see that the color changes between the - and the >. We don’t stand a chance of ligating the two together, because PowerShell has told us they’re two different units.
