### ISSUE TITLE
Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': build failed 

### ISSUE THREAD

**Issue by luxiangnk** [microsoft/Terminal#516]
38>e:\software\microsoftterminal\terminal\src\cascadia\windowsterminal\apphost.h(6): fatal error C1083: Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory
38>AppHost.cpp
38>e:\software\microsoftterminal\terminal\src\cascadia\windowsterminal\apphost.h(6): fatal error C1083: Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory
38>IslandWindow.cpp
38>e:\software\microsoftterminal\terminal\src\cascadia\windowsterminal\islandwindow.h(6): fatal error C1083: Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory
38>NonClientIslandWindow.cpp
38>e:\software\microsoftterminal\terminal\src\cascadia\windowsterminal\islandwindow.h(6): fatal error C1083: Cannot open include file: 'winrt/Microsoft.Terminal.TerminalControl.h': No such file or directory

**Comment by zadjii-msft** [comment]
Seems to me the TerminalControl project didn't build. Do you get any errors if you try just building that project?

**Comment by Paul-Weisser** [comment]
U need to install the binary of winrt which can be found here:
https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264

The nuget extension didn't work for me

**Comment by EnterpriseBCMe** [comment]
> U need to install the binary of winrt which can be found here:
> https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
> 
> The nuget extension didn't work for me

dude I tried as you said but nothing special happens to me. I still can't find that stupid header LOL

**Comment by luxiangnk** [comment]
> U need to install the binary of winrt which can be found here:
> https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
> The nuget extension didn't work for me

Thanks, dude! It works for me!

**Comment by psychohamster** [comment]
For me , it turns out even though I had UWP Development feature checked in VS2017, the default didn't include C++ files for it. Once I modified the setup and re-opened the solution, it built like a charm.

**Comment by moomdate** [comment]
> 
> 
> U need to install the binary of winrt which can be found here:
> https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
> 
> The nuget extension didn't work for me

it's work for me
