### ISSUE TITLE
TryDuplicateBadTab and TryDuplicateBadPane unit tests are hanging when run locally

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#5169]
# Environment

Windows build number: Version 10.0.18362.657
Windows Terminal version (if applicable): Commit 28d108bf32de4dce061d80a2bd160cd617c7e698

# Steps to reproduce

1. Build the OpenConsole solution from a recent commit
2. Run the unit test with `runut.cmd /name:*TabTests::TryDuplicate*`

# Expected behavior

The unit tests should execute successfully.

# Actual behavior

The `TestHostApp` window opens up and the test then appears to be stuck. Closing the window manually doesn't help, but if you instead kill the `TestHostApp` process, it will at least continue with the rest of the tests.

**Comment by zadjii-msft** [comment]
That's not what you want to hear 😞. I wonder when this regressed - I'd bet it's the combo of #5051 with #5090, but I can't be sure ATM
