### ISSUE TITLE
Strange text behaviour

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/terminal#5170]
# Environment

Windows build number: 19041.172
Windows Terminal version (if applicable): Latest from Microsoft Store

# Steps to reproduce

Install latest Terminal

# Expected behavior

2 -- symbols in grey text

# Actual behavior

After the 2nd - the text goes grey but the first - gets deleted, please see screenshot

![image](https://user-images.githubusercontent.com/50337995/77860310-6bab9a80-7206-11ea-84c5-9d3a5d6fc995.png)

**Comment by DHowett-MSFT** [comment]
This is just how PowerShell is configured to render parameters.

**Comment by DHowett-MSFT** [comment]
Oh, sorry, this is /dup #5158

**Comment by DHowett-MSFT** [comment]
I’m not doing very well at this bug triaging today: this is actually #4974

**Comment by privacyguy123** [comment]
My bad - yes, in the preview versions it would correctly show the TWO grey --s
