### ISSUE TITLE
Cannot start in cmd Informix Server 12.10

### ISSUE THREAD

**Issue by iliev72** [microsoft/terminal#5174]
when i sign oninit -d and push enter
before start oninit i start ol_informix1210.cmd to set env.
give message "WindowStation/Desktop Setting Failed"

**Comment by DHowett-MSFT** [comment]
You seem to have deleted the bug template, so I don’t know what version of Windows you’re on or if you are using Windows Terminal.

**Comment by DHowett-MSFT** [comment]
I also don’t know what Informix is.

**Comment by iliev72** [comment]
Windows 10 1909 (18363.720 .720)windows terminal 0.10.781.
IBM Informix Database Server(IDS)12.10FC14DE

**Comment by DHowett-MSFT** [comment]
Even though the names are different, this is probably the same root cause as /dup #2988. IBM Informix server is using `GetConsoleWindow`, which terminal will not support.
