### ISSUE TITLE
Terminal stop responding in Remote Desktop Session

### ISSUE THREAD

**Issue by ekalchev** [microsoft/terminal#5176]
# Environment
Microsoft Windows [Version 10.0.18363.720]

# Steps to reproduce

Connect to the machine that is running Terminal with Remote Desktop - resize the terminal window 

# Expected behavior

Should resize

# Actual behavior

Application stop responding and needs restart

**Comment by zadjii-msft** [comment]
@ekalchev What version of the Windows Terminal are you running? A very similar bug to this was resolved in 0.10.781 (see #4964).

**Comment by ekalchev** [comment]
I am using version 0.10.761

**Comment by zadjii-msft** [comment]
@ekalchev Thanks for following up!
