### ISSUE TITLE
Support Azure Cloud Shell Code Editor in Windows Terminal

### ISSUE THREAD

**Issue by wbpluto** [microsoft/terminal#5183]
Support Azure Cloud Shell Code Editor in Windows Terminal

![image](https://user-images.githubusercontent.com/5191513/77961318-3e491480-730c-11ea-93c7-146cd10091f3.png)

**Comment by zadjii-msft** [comment]
@wbpluto Does that command work from a legacy `conhost.exe` (`cmd` / `powershell`) window?
