### ISSUE TITLE
Add ctrl+c/ctrl+v to settings.json

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#5187]
# Description of the new feature/enhancement
We should add `copy` and `paste` key bindings as `ctrl+c/v` in the settings.json file so people can see them and have the option to remove them.

Additionally, there should be a comment in the file explaining that `ctrl+shift+c/v` are still shipped by default so they have a backup key binding if they choose to remove the above bindings.

This would also close #3058 

# Proposed technical implementation details (optional)

**Comment by levicki** [comment]
@cinnamon-msft In Windows Terminal Version 1.7.1033.0 I don't have any keybindings in settings.json for copy and paste. Moreover, under Settings -> Actions, defaults are shown as copy being `ctrl+insert`, and paste being `shift+insert`.

I might have had an existing settings json without keybindings before installing the Windows Terminal.

From the bug reports here it is unclear to me what behavior is expected and what should the actual defaults for copy and paste be. I have the following questions:

1. Was WT supposed to update the existing settings.json to add keybindings for copy and paste or at least add commented out example?
2. Are copy and paste default bindings decided and if so what they are?
3. I am aware of the challanges with ctrl+c and ctrl+v and that we cannot please everyone, but as a longtime Windows cmd.exe user and occasional Linux user, I would prefer if a core Windows application such as WT (which is seemingly supposed to replace the old conhost?) provides default Windows experience out of the box with the ability to change it to something else.

**Comment by zadjii-msft** [comment]
@levicki Would you mind filing a new issue to track your problem? This issue's over a year old, and specifically was used to track adding <kbd>ctrl+c</kbd>/<kbd>ctrl+v</kbd> to the default `settings.json` file back in 2020. If you're not seeing those keybindings, then it's likely that you're running into something entirely else. Screenshots of the settings UI, and your entire `settings.json` file would be appreciated as well. Thanks!

**Comment by levicki** [comment]
@zadjii-msft I asked here intentionally because description of this fix does not reflect reality. 

It says:

> Additionally, there should be a comment in the file explaining that ctrl+shift+c/v are still shipped by default...

My settings show different defaults when keybindings are empty.

All I wanted is to be pointed to some place where current behavior is documented so I can determine whether I am having a problem or not before eventually submitting an issue.

**Comment by DHowett** [comment]
@levicki so, this is one of those annoying things we chose to do to preserve our userbase's sanity.

We added the key bindings for people who first launch the terminal, or delete their settings, after 4/9/2020. It's part of the template settings file that is put on disk during startup _if you don't already have settings._

That template data is here-

https://github.com/microsoft/terminal/blob/8661dc51ddb0b8e4869ae762edce513468cd8df9/src/cascadia/TerminalSettingsModel/userDefaults.json#L60-L64

If we had added them to the set of default key bindings in the application settings (the immutable ones), all the users who had installed and launched Terminal before 4/9/2020 would have suddenly lost ctrl+c/ctrl+v.

We place a reasonably high value on not breaking existing users¹, so this was the compromise we came to.

¹ we have done this before, and it tastes bad. Especially considering the input service discussion :smile:

**Comment by levicki** [comment]
@DHowett Thanks for clarifying that part and linking to the template.

Frankly, I was expecting from a Windows application that ctrl+c and ctrl+v are the built-in defaults for copy and paste even in the absence of keybindings in settings.json (of course with the ability to override them), but the graphical settings page is showing different defaults which also differ from the ones mentioned here and which aren't very discoverable.
