### ISSUE TITLE
Trying to open the terminal a white window pops up with nothing on it.

### ISSUE THREAD

**Issue by vishal17209** [microsoft/Terminal#519]
Windows Build Number:
Microsoft Windows [Version 10.0.18362.30]

What you're doing and whats happening:
After deploying the solution in VS2019 16.03 tried to open Windows Terminal (Preview) from the start menu which gave me a white window shown in the screenshot

![image](https://user-images.githubusercontent.com/43264946/57317268-54a71a00-7115-11e9-9e06-8c89d3b14d8e.png)

**Comment by zadjii-msft** [comment]
Could you share your `profiles.json` file? To get at it quick, press Ctrl+t, then hit "Settings" in the new tab dropdown, to open the file in your default json editor (which might take a minute)

**Comment by vishal17209** [comment]
The terminal is completely unresponsive too, I have updated my original issue with a screenshot of what I am getting. Please correct me if I am doing something wrong here.

**Comment by zadjii-msft** [comment]
Any chance you could try running it from VS, and posting the Output log here? I've never seen this before, but I'd think it should be working.

**Comment by RamblingGeekUK** [comment]
I'm getting the same.

**Comment by frye** [comment]
I see this same as well. Of course now it is working but had to battle with it last night quite a few times. No matter what I tried I could not get it to break into debugger so it seemed weird. The behavior was same from start menu and launching from VS2019. That being said I knew I was maybe pushing it with VS2019 and build tools 142 so was blaming myself for this.

**Comment by skasturi** [comment]
I faced this too. This likely occurs because of Windows Defender. A Windows defender pop-up opens when this occurs and clicking on that pop-up unfreezes the Windows Terminal window.

**Comment by frye** [comment]
I don't get a defender popup. But definitely something. Pulled the latest changes and rebuilt and same situation.

**Comment by miniksa** [comment]
This should be explained now with the README update from #777. Resolving.

**Comment by leet0rz** [comment]
This is still an issue, just happened with me today.
