### ISSUE TITLE
`ctrl + d` quit terminal 

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#5191]
In cmd , msys2 , hyper or something else ,  `ctrl + d` would quit current window.

but `microsoft/terminal` only show `process exited with code 130`

**Comment by zadjii-msft** [comment]
Alas, this is a behavior that's highly conserved across multiple shells and terminal emulators on most mainstream operating systems; more info in https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181 and additionally https://github.com/microsoft/terminal/issues/5040#issuecomment-601855840. If you'd rather it just exit every time, set `closeOnExit` to `always`. :smile: /dup #4223.
