### ISSUE TITLE
Split screen keyboard shortcut should open new instance in same environment as current

### ISSUE THREAD

**Issue by aguerot** [microsoft/terminal#5198]
# Description of the new feature/enhancement
When splitting the screen using keyboard shortcut `[ALT]+[SHIFT]+-` the default profile is used for the newly created profile instance. I would be great if the current profile would used to instanciate the new splitted instance. 

On my setup, I have PSCore as my default profile and WSL2 Debian as my second profile. If I create a new splitted instance with the keyboard shortcut `[ALT]+[SHIFT]+-` or `[ALT]+[SHIFT]++` from a WSL2 Debian instance, the newly created tab in the split panel is PSCore instead of WSL2 Debian. Would be great to use the context of the current tab/profile active 

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
You can configure this by setting `"splitMode": "duplicate"` in your own `splitPane` key bindings. If you copy the ones from the default settings file (hold down <kbd>Alt</kbd> while clicking **Settings**), you can even replace the existing bindings.

**Comment by aguerot** [comment]
Thanks for the heads up
