### ISSUE TITLE
Console device is relabeling 24-bit SGR color values if they match a 16-color primary in the Windows color scheme.

### ISSUE THREAD

**Issue by Undercat** [microsoft/terminal#5201]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Various example means of triggering are shown in issues libuv/libuv#2766 and mintty/mintty#981

# Expected behavior
Truecolor ANSI SGR codes should never be relabeled as 16-color primary codes. Not all downstream consumers use colormaps that will render these values equivalently. (In fact, many environments have chosen markedly different RGB values for their SGR primaries.<sup>[ref](https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit)</sup>)

# Actual behavior
All 24-bit SGR color sequences are remapped to shorter 16-color SGR primaries if the 24-bit RGB intensity values happen to match a primary&rsquo;s RGB intensity values in the Windows color scheme.

For example, the value `\e[48;2;118;118;118m` gets relabeled `\e[100m` because the RGB intensities that Windows uses for "bright black" happen to match those given by the somewhat longer 24-bit ANSI string. But not all environments map "bright black" to the same 24-bit RGB intensity values; see screenshots in the mintty issue, referenced above.

Note: this applies to 8-bit SGR codes, too, if the canonical RGB values for the 8-bit color match what Windows has chosen for one of their primaries: `\e[48;5;243m => \e[100m`

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2661 for more discussion.

/dup #2661
