### ISSUE TITLE
Feature request: Add redundant \r on line wrap

### ISSUE THREAD

**Issue by rovf** [microsoft/terminal#5202]
This feature request evolves from a [discussion about mintty (Cygwin) not working correctly](https://github.com/mintty/mintty/issues/971) with the new winpty anymore.The problem is that copying a line longer than the terminal width, which is being output by a typical Windows console (i.e. non-Cygwin) program from the mintty terminal, causes a hard line break being inserted in the copied string, because the controlling terminal (mintty in this case), can not recognize whether the line is really a long line having been wrapped around, or two short lines, where the first of these happened to be exactly the Window width.

I want to select with the mouse a long line which has been wrapped around, and paste it somewhere, without getting a hard line break at the point where the line wrap has occured.

# Proposed technical implementation details (optional)

Since there seems to be no really good alternative, the mintty maintainer suggested that winpty would output \r\r\n, if there is a wrap around of the line. The redundant \r would signal to the controlling terminal, that a line wrap has occured.

**Comment by zadjii-msft** [comment]
So this is actually a bug that we're already tracking in #5113, and I'm trying to fix over in #5181. The real solution to this problem shouldn't be "add another hack to make this scenario work", the solution is just "don't hard break lines"

/dup #5113

p.s. winpty != conpty. winpty is a third party library for creating pseudoterminals on Windows, and ConPTY is the set of APIs that we maintain for hosting "pseudo-consoles". They're similar, but we only maintain conpty 😉
