### ISSUE TITLE
Resizing a Terminal with retro terminal effects hangs the Terminal

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5203]
This is on the selfhost 0.11.912.0 release, but also repro'd on the last 0.11 preview. Unsure if it repros on earlier builds also.

Add the following to a profile:

```json
"experimental.retroTerminalEffect": true
```

Then open a tab with that profile and try resizing the Terminal. 

### Expected 
The Terminal should not hang.

### Actual 
It hangs 😢 

Looks like we're waiting for the read lock at the top of `TermControl::RenderEngineSwapChainChanged` on the `RenderThread`. This is higher on the stack than `Renderer::_PaintFrameForEngine`, which I believe has a write lock. But it's the same thread, so we should be fine, right?

Oh no the main thread also is waiting on the write lock 😲 
```
03 TerminalControl!std::unique_lock<std::shared_mutex>::{ctor}+0x8 
04 TerminalControl!Microsoft::Terminal::Core::Terminal::LockForWriting+0x14
05 TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::_SwapChainSizeChanged+0x37
06 TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControlT<winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl>::Connect::__l10::<lambda_87fbcfa1739d624dde571db8710dac26>::operator()+0x77 
```

Wait no, that's fine. The main thread doesn't _have_ the lock, it's just waiting for it. That's fine. I think the problem is the render thread can't seem to re-enter the lock

because it's a `shared_mutex` not a [`recursive_mutex`](https://en.cppreference.com/w/cpp/thread/recursive_mutex)

**Comment by DHowett-MSFT** [comment]
I accept that this is _probably_ my fault: call stack looks like it's in `LockForWriting` :wink:

**Comment by DHowett-MSFT** [comment]
Oh, you .. already .. did that. Ugh, sorry.

**Comment by DHowett-MSFT** [comment]
I'm actually seeing a second thread contending the lock _also_ handling a swap chain change.


```
02 (Inline Function) --------`-------- TerminalControl!std::shared_mutex::lock_shared+0x5 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\shared_mutex @ 55] 
03 (Inline Function) --------`-------- TerminalControl!std::shared_lock<std::shared_mutex>::{ctor}+0x5 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\shared_mutex @ 241] 
04 (Inline Function) --------`-------- TerminalControl!Microsoft::Terminal::Core::Terminal::LockForReading+0x17 [E:\BA\193\s\src\cascadia\TerminalCore\Terminal.cpp @ 542] 
05 00000037`4cfff580 00007ffc`cc0931f5 TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::RenderEngineSwapChainChanged$_ResumeCoro$2+0xb3 [E:\BA\193\s\src\cascadia\TerminalControl\TermControl.cpp @ 489] 
06 00000037`4cfff690 00007ffc`cc0a1a5b TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::RenderEngineSwapChainChanged+0x45 [E:\BA\193\s\src\cascadia\TerminalControl\TermControl.cpp @ 506] 
```

**Comment by DHowett-MSFT** [comment]
UGH YOU ALREADY DID THAT PART TOO okay i'm stopping
