### ISSUE TITLE
Unexpected network traffic to SMB shares

### ISSUE THREAD

**Issue by JannesMeyer** [microsoft/terminal#5204]
# Steps to reproduce

1. Open terminal
2. Observe the popup about an outgoing connection on port 5000 by your firewall of choice (if it's configured to warn about that)

# Expected behavior

According to [DHowett on Hacker News](https://news.ycombinator.com/item?id=22325292) you do not expect any outgoing connections unless explicitly requested

# Actual behavior

![image](https://user-images.githubusercontent.com/704336/78147397-f963d180-7422-11ea-8d5f-916d04e4f2d0.png)

Source is my desktop computer
Remote is my NAS device with some SMB file shares (but none of them are mapped to drive letters)

**Comment by zadjii-msft** [comment]
That's crazy - I really wouldn't expect that to happen. Does this repro with cmd.exe as your shell? Maybe this is powershell trying to enumerate some file?

Also, what Windows version and Windows Terminal version are you running? I wouldn't expect this on _any_ version, but you never know

**Comment by JannesMeyer** [comment]
Yes, I have just reproduced it with cmd.exe as the default shell in `profiles.json` and I have also reproduced it with an empty PowerShell profile (I had some small customisations in my `profile.ps1`).

Windows Terminal Version: 0.10.781.0
Windows Version: 10.0.18362.720

**Comment by zadjii-msft** [comment]
Huh, that's certainly weird. Maybe this is caused by us trying to enumerate the `pwsh` installs you have? 

Could you try adding this to the root of your `profiles.json`? 

```json
    "disabledProfileSources": ["Windows.Terminal.PowershellCore"]
```

and try again? That should disable the lookup for pwsh installs. You could also try 


```json
    "disabledProfileSources": ["Windows.Terminal.PowershellCore", "Windows.Terminal.Wsl", "Windows.Terminal.Azure", "Windows.Terminal.Telnet"]
```

to be comprehensive about all the possible dynamic profiles

**Comment by JannesMeyer** [comment]
Thanks for your help! It turns out that it was entirely my own fault.

I found an old profile that I had forgotten about... With a custom icon that's being loaded from the NAS...

Sorry for bothering you with this! After removing the custom icon it stopped happening.

**Comment by zadjii-msft** [comment]
Hey no problem! I'm glad it was something in your own config after all, thanks for following up!

**Comment by DHowett-MSFT** [comment]
@JannesMeyer (thanks for following up! I was really curious about this one when I saw you on Hacker News 😄)
