### ISSUE TITLE
Windows Terminal won't open in the right path.

### ISSUE THREAD

**Issue by Idov31** [microsoft/terminal#5220]
# Environment
Windows build number: 10.0.18363.720
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
No

# Steps to reproduce
Write "wt" in the search line in file explorer won't open Windows Terminal in the current folder but
in the user's folder.

# Expected behavior
Opening Windows Terminal in the current path.

# Actual behavior
Opening Windows Terminal in the user's path.

![1](https://user-images.githubusercontent.com/62358580/78222545-186b6d80-74ce-11ea-82c5-30cb6c43f9b9.png)
![2](https://user-images.githubusercontent.com/62358580/78222549-1a353100-74ce-11ea-9720-5d75fa61c6bb.png)
![3](https://user-images.githubusercontent.com/62358580/78222550-1a353100-74ce-11ea-9471-444970196d5b.png)
![4](https://user-images.githubusercontent.com/62358580/78222551-1acdc780-74ce-11ea-939b-59981ab7fb86.png)
![5](https://user-images.githubusercontent.com/62358580/78222552-1b665e00-74ce-11ea-9d39-ea620e1a200c.png)
![6](https://user-images.githubusercontent.com/62358580/78222553-1b665e00-74ce-11ea-8b82-c5569f4e273d.png)

**Comment by j4james** [comment]
See https://github.com/microsoft/terminal/issues/878#issuecomment-579508860

**Comment by Idov31** [comment]
Thank you.

**Comment by zadjii-msft** [comment]
I'm closing this since it seems to have been answered. Thanks all!
