### ISSUE TITLE
Conpty: Additional `ScrollFrame` optimizations

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5228]
In #5181, I changed `XtermEngine::ScrollFrame` to actually work. 

Part of the trickiness with that function is that we need to make sure to emit newlines to scroll new lines into the terminal, but we also need to preserve linewrap state for lines that might have been split across paints.

* [ ] If only the bottom line is invalid, don't manually emit a newline. 
  - We need to manually emit newlines to make sure there's space at the bottom of the terminal's buffer. However, if only the bottom line is invalid, then we're going to emit a newline to get to the next line of the buffer anyways. We only need the newlines if there's other invalid regions in the buffer, because those regions will get painted (to the wrong place) _before_ we newline to the new bottom line.
  - This includes "don't mark the last cell as invalid" for a wrapped line
* [ ] Also discussed at this time: use a `bitset` to track which lines are new instead of the single `_newBottomLine` member. This is probably _more_ correct for cases where multiple lines are getting scrolled in at a time.
* [x] #7019

**Comment by DHowett-MSFT** [comment]
Triaged- 21H1 is correct here.
