### ISSUE TITLE
Right click does not paste data copied from other apps

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#523]
In existing Terminals, eg Fluent Terminal, Hyper, Terminus, I can copy something from eg a web browser and paste it into the terminal with a right mouse click,

This does not work on Windows Terminal. Instead the contents of a second clipboard are pasted.

## Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
ver : The term 'ver' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ver
+ ~~~
+ CategoryInfo          : ObjectNotFound: (ver:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

I think you mean 😉:

```
$ [Environment]::OSVersion.VersionString
Microsoft Windows NT 10.0.18890.0
```

### To replicate

 - Copy something from a web page or other app
 - Paste using right click

### What happens

The contents of a second clipboard are pasted - whatever the most recent selected text pas

### What should happen

The content from the web page or desktop app is pasted

**Comment by zadjii-msft** [comment]
@carlos-zamora is working on this currently :)

**Comment by Jaykul** [comment]
I _was_ going to say this is working fine for me, but I see that in `cmd` it actually locks up the tab and I can't seem to get it to pay attention to anything I do after that. 

Works ok in `pwsh` ...

**Comment by carlos-zamora** [comment]
As a heads up, make sure you're not trying to add focus to Windows Terminal (WT) before right-clicking. In Powershell/CMD (prior to WT) if the shell wasn't focused, a left-click would give it focus, then a second left-click would begin selection. WT begins a selection from the first left-click.

So, if you left-click to give it focus, then right-click, you'll end up selecting something (presumably an empty space), then pasting nothing haha.

**Comment by will** [comment]
I don’t know if this is the right spot but one of the more annoying things I have with comemu/cmdr (and I assume maybe also the first-party terminal emulators) is if I'm in vim or something and I do a normal keyboard paste, all the newlines are ignored, so I *have* to do right click paste if it's multi-line. I hope that behavior is not carried over to the new Terminal, and just normal keyboard paste can be good.

**Comment by mikemaccana** [comment]
@will Fluent Terminal supports multi line paste right now. Obviously I hope Windows Terminal supports pasting newlines properly too!

**Comment by zadjii-msft** [comment]
@will I am pretty sure that the solution to the issue you're decsribing is adding support for VT bracketed paste mode, which I believe @DHowett-MSFT was working on earlier. We'll need to add support for the terminal to both send pastes as bracketed sequences, and for conpty to be able to read pastes as bracketed, and then _also_ add support for conhost to know what a bracketed paste is.

**Comment by zadjii-msft** [comment]
Is this still happening? I'm pretty sure scenario works now that clicking the terminal window doesn't erroneously select text:
![image](https://user-images.githubusercontent.com/18356694/59705215-9078d900-91c3-11e9-848e-c16734076e61.png)

**Comment by mikemaccana** [comment]
@zadjii-msft Working fine on git from a couple of days ago.

![image](https://user-images.githubusercontent.com/172594/59932926-3b95c680-9440-11e9-81f9-7a3142586a72.png)
