### ISSUE TITLE
Shift Tab does not work when using ssh

### ISSUE THREAD

**Issue by in42** [microsoft/terminal#5235]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
Neovim: NVIM v0.5.0-13-g618045685
```

# Steps to reproduce

Open the powershell profile of Windows Terminal. ssh to a remote linux host. Open neovim, try to open a file using `:e <Tab><Tab>` to cycle through the files. Press `<Shift><Tab>` to cycle back, it won't work.

Now go into insert mode and press `Ctrl-v`, then `Tab`.
You should get a tab.
Now press `Ctrl-v` then `Shift-Tab`.
# Expected behavior

`<S-Tab>` should be inserted (like in putty).
# Actual behavior

Nothing is inserted.

**Comment by in42** [comment]
Shift-Tab is working if I ssh using the WSL Ubuntu profile instead of Powershell profile.

**Comment by DHowett-MSFT** [comment]
Ah, then this is probably a bug in Win32-OpenSSH. They are generating their own VT input in version 7.x, and this should be fixed when 8.x is generally available.

**Comment by DHowett-MSFT** [comment]
Thanks for following up!
