### ISSUE TITLE
More future rich settings with an option to set the default shell

### ISSUE THREAD

**Issue by andreipaciurca** [microsoft/terminal#5236]
# Description of the new feature/enhancement
As for myself I would love to start Windows Terminal with WSL or CMD not PowerSehll

# Proposed technical implementation details (optional)

**Comment by Sahil2004** [comment]
You can easily do it by just changing the code in "defaultProfile" and setting its value to be equal to the value of "guid" of the CLI you like! For example: for cmd set:

"defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",

**Comment by DHowett-MSFT** [comment]
Looks like this question is answered :) thanks
