### ISSUE TITLE
Remember my last open tabs (like a browser) + remember my command history

### ISSUE THREAD

**Issue by mbriand1** [microsoft/terminal#5242]
# Description of the new feature/enhancement
My Edge browser can remember my last opened tab, why not the same feature for the terminal? If I open 3 tabs I could have a checkable option in the menu to remember my last tabs. Bonus points for remembering also my command history as I left it...

Productivity gains.
# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I think this is already covered by issue #961.

**Comment by oising** [comment]
Seems the magic dup bot ignores me.

**Comment by DHowett-MSFT** [comment]
/dup #961

we should iron that out, because it's really helpful having you triage :smile:
