### ISSUE TITLE
The documentation lacks information about NuGet.

### ISSUE THREAD

**Issue by jsakkine** [microsoft/terminal#5244]
The documentation does not instruct to do `nuget restore` as part of the compilation steps.

**Comment by DHowett-MSFT** [comment]
This is because the default configuration of Visual Studio 2019 is to restore packages before building the solution, and some of the build scripts that _are_ recommended in the readme do so as well.

**Comment by jsakkine** [comment]
I took the PS route:

```
Import-Module .\tools\OpenConsole.psm1
Set-MsBuildDevEnvironment
Invoke-OpenConsoleBuild
```

`nuget restore` fixed the issue.

Why I get wrong?

**Comment by zadjii-msft** [comment]
I'm not sure that you did anything wrong - `Invoke-OpenConsoleBuild` looks like it's supposed to call `nuget restore`

https://github.com/microsoft/terminal/blob/4f8acb4b9fbd61196d0a5287749a58abe0fbaa28/tools/OpenConsole.psm1#L256-L260

Did you happen to see any errors like "Error parsing solution file", or any errors related to `nuget` in the initial build that failed?

**Comment by WSLUser** [comment]
We also need to document how we're even using Nuget in this project.

**Comment by DHowett-MSFT** [comment]
And why is that? We're using it for packages.

**Comment by WSLUser** [comment]
Indeed but what Nuget packages are in use? I can't even find most of the deps available through the public Nuget feed. We also aren't creating a .net app either. It seems like our deps are supposed to update through this method but they weren't created with .net in mind and we utilize them in C++.  It's just a bit confusing on how all the pieces fit together. Maybe if we had a more detailed design flow schematic in the docs, this would be a bit more clear for contributors.
