### ISSUE TITLE
Programs don't take mouse input due to selection

### ISSUE THREAD

**Issue by TheMayhem6328** [microsoft/terminal#5246]
# Environment

```none
Windows build number : 2004
Windows Terminal version : 0.10.781.0
```

# Steps to reproduce

After adding [FAR Manager](https://www.farmanager.com/) to path, try running it from Terminal.
# Expected behavior

I should be able to interact with FAR Manager using the mouse
# Actual behavior

Mouse selects text, but does not interact with the CLI Program.

 ![{C__Program Files_Far Manager} - Far 3 0 5577 x64 4_5_2020 12_05_19 PM](https://user-images.githubusercontent.com/56154436/78468104-08ee5d80-7736-11ea-8ed6-ab184712a093.png)

**Comment by DHowett-MSFT** [comment]
_Windows_ programs don't take mouse input because we haven't implemented that part yet. Please be sure to subscribe to /dup #376 for updates!
