### ISSUE TITLE
Antivirus trips on openps.cmd

### ISSUE THREAD

**Issue by dw2546** [microsoft/Terminal#525]
During cloning BitDefender Total Security complains: "The file C:\Users\dw2546\Documents\GitHub\Terminal\tools\openps.cmd is infected with Generic.Botget.7A4F2C92 and was moved to quarantine."

**Comment by zadjii-msft** [comment]
Well that's new. Never seen that before.

Does it work if you copy the text of the file into another `.cmd` file named something else?

**Comment by dw2546** [comment]
Nope. As soon as I click save, even if it's a TXT, BitDefender jumps in and scolds me. I will try on another PC but I just wanted to mention it here.

**Comment by dw2546** [comment]
Interesting. If I remove the REM comment lines and save the file there are no issues:

@echo off
call opencon powershell.exe

**Comment by sorcerer86pt** [comment]
yep, happened to me too.

**Comment by miniksa** [comment]
This looks inactionable from here now that BitDefender has been told. Resolving.
