### ISSUE TITLE
Terminal is one pixel to small

### ISSUE THREAD

**Issue by n-gao** [microsoft/terminal#5250]
# Environment

```none
Windows build number: 10.0.18383.0
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
Using the snap to position feature:
* Snap the terminal to the left side of the monitor 
* Snap any other program to the right side

# Expected behavior
There should be no gap at all sides of the window like vs code.

# Actual behavior
There is a one pixel gap at all sides.
![image](https://user-images.githubusercontent.com/9084670/78510101-27cf0d00-7793-11ea-9215-d89418fbe725.png)
![Untitled](https://user-images.githubusercontent.com/9084670/78510154-8c8a6780-7793-11ea-90c4-0c5e7032453a.png)

**Comment by DHowett-MSFT** [comment]
This is also true of Windows Explorer in dark theme. I'm gonna close this one out, since it looks like it's part of the platform's affordance for dark window borders -- it's not that it's a pixel too small, it's more that the "dark" window border is alpha-blended with the thing behind it.
