### ISSUE TITLE
A couple of versions ago Terminal have started to steal `shift-ins` from the client apps and handles it horribly bad

### ISSUE THREAD

**Issue by awson** [microsoft/terminal#5253]
# Environment

```none
Windows build number: 10.0.18363.720
Windows Terminal version: 0.10.781.0
Far Manager 3.0.5577 x64
```

# Steps to reproduce
Copy any text to clipboard. Open builtin Far Manager editor and `shift-ins` into it.

# Expected behavior
Copied text immediately appeared in the editor window.

# Actual behavior
Copied text appears horribly slow, million times slower than expected, with broken formatting (some `lf`s appeared skipped).

This behaved well a couple of versions ago and `ctrl-v` still behaves well, since it's (still, in release version of Terminal) handled by Far Manager.

I tried to unbind it with
```
    "keybindings": [
        { "unbound": "paste", "keys": ["shift-ins"] }
    ]
```
but haven't succeeded.

Is there a way to accomplish this?

**Comment by zadjii-msft** [comment]
That's correct, we added <kbd>shift+ins</kbd> as a keybinding for paste to [defaults.json](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json) in #4467.

You can unbind it with 


```json
{ "comamnd": "unbound", "keys": ["shift-ins"] }
```

**Comment by awson** [comment]
This doesn't work.

**Comment by zadjii-msft** [comment]
Oof, typo'd. Thats my bad, not enough coffee yet. You need to use `command`, not `comamnd`. See also https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#unbinding-keys

```json
{ "command": "unbound", "keys": ["shift-ins"] }
```

**Comment by awson** [comment]
Even `shift-insert` *doesn't work for me*.

**Comment by zadjii-msft** [comment]
Did you try `shift-insert` or `shift+insert`?

**Comment by awson** [comment]
Ah, I tried, `shift-insert`, `shift+insert` finally works, thanks!
