### ISSUE TITLE
Windows Powershell resize

### ISSUE THREAD

**Issue by trungutt** [microsoft/terminal#5254]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
My Windows version: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.10.781.0
I think this bug is in all versions of Terminal and Windows
Any other software? No
```

# Steps to reproduce

1. Open Terminal in full screen
2. Type `ls`
3. unmaximize the window
4. maximize the window
5. type `ls` again and see that ls is not positioned correctly

![displaybug](https://user-images.githubusercontent.com/18528548/78541017-45cd5980-77f5-11ea-95aa-d34eb2eef788.gif)

# Expected behavior
cursor at the right position

# Actual behavior
cursor not at the right position, it's below the prompt

**Comment by zadjii-msft** [comment]
Oh this is a much easier repro than the one I had before.

Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2432 for more discussion.

/dup #2432
