### ISSUE TITLE
Tmux doesn't refresh (again)

### ISSUE THREAD

**Issue by eduardoarandah** [microsoft/terminal#5260]
This issue was solved before (I made the report) 
check: https://github.com/microsoft/terminal/issues/4414

Then you changed something and it worked:
https://github.com/microsoft/terminal/issues/4414#issuecomment-602931355

I didn't make any changes to my hardware.
Video card: NVIDIA GeForce GT 710

# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.19041.172]
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
TMUX 3.0a
```

# Steps to reproduce

- Open tmux with a split
- Open a second tab (a windows terminal tab, not tmux)
- Go back and forth to see it not refreshing 

# Expected behavior

Refreshing content

# Actual behavior

Content not refreshing, see screenshot:
![image](https://user-images.githubusercontent.com/4065733/78593341-16761700-780c-11ea-870f-a496d98f4ce4.png)

**Comment by DHowett-MSFT** [comment]
It's weird; we haven't made any changes to the version of Terminal available in the store since you reported that it was fixed. :smile:

**Comment by eduardoarandah** [comment]
it's weird, 
Maybe it's something wrong with my graphics acceleration and my video card? (NVIDIA GeForce GT 710)

In my computer, this terminal has no issues:
https://github.com/mintty/wsltty

**Comment by DHowett-MSFT** [comment]
I can't make this happen with any number of splits or terminal tabs.

![image](https://user-images.githubusercontent.com/14316954/78725016-712e7200-78e3-11ea-9a4a-13b46800133c.png)

**Comment by DHowett-MSFT** [comment]
What scale is your display set to?

**Comment by eduardoarandah** [comment]
> What scale is your display set to?

100% scale

I don't know what other info might be helpful. 

It might be useful checking how this other program works graphically. 
https://github.com/mintty/wsltty

It works without problem with multiple processes in tmux and vim working all day:

**Comment by zadjii-msft** [comment]
I mean, there are a lot of parts of our stack that are different than wsltty - our buffer, our VT implementation, our renderer, the fact that we use conpty, etc, etc. It's not going to be much help to compare the two considering just how much will be different 😉

Looks like you've updated from tmux 2.6 (in #4414) to tmux 3.0a in this issue, maybe that had something to do with it?

what's the output of `infocmp` in `tmux`?

**Comment by eduardoarandah** [comment]
Looks like you've updated from tmux 2.6 (in #4414) to tmux 3.0a in this issue, maybe that had something to do with it?

I'm not sure. Before I tried with both versions and same problem. 

Tell me if this is of any help:

infoctmp info:

```
#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
        am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^?,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8,
        rep=%p1%c\E[%p2%{1}%-%db, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
        rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
        rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?%[;0123456789]c,
        u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by DHowett-MSFT** [comment]
This is kind-of crazy, and it might capture some information you're not comfortable with, but I'd love to get a "VT trace" from your tmux session up until the point at which it breaks.

1. (Debian, Ubuntu) Install the package `bsdutils` (probably already have it)
2. Run `script -c "tmux" tmux_refresh_repro.script -ttmux_refresh_repro.timing`
3. Use tmux until it breaks
4. Exit tmux as quickly as possible
5. Send us tmux_refresh_repro.script _and_ tmux_refresh_repro.timing

The script file captures everything that tmux sent to the screen, and the timing file captures exactly _when_ it did each print.
If you're not comfortable posting that stuff on GitHub, my e-mail address is in my github profile. If you're not comfortable with this _at all_, even in private, I understand. :smile:

**Comment by parkerault** [comment]
I suddenly started having this problem today, which was strange because I had been using tmux in windows terminal with no trouble previously. It appears to only happen when using a vertical split. However, I realized that I had recently set `tmux_conf_theme_highlight_focused_pane` to true. Sure enough, resetting it to false fixed the issue. 🤷
