### ISSUE TITLE
copyFormatting Keybinding Arg for Copy

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#5262]
# Description of the new feature/enhancement
A copy keybinding should have a keybinding arg that allows you to copy the formatting of a selection.

More details on how this feature should be implemented are included here:
- #5212 - Spec for Formatted Copying
- #4191 - Setting to enable/disable formatted copy

**Comment by DHowett-MSFT** [comment]
Triaged into 1.x.
