### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by ahmedhrayyan** [microsoft/terminal#5266]
# Description of the new feature/enhancement
Currently the terminal does not support the Arabic language at all, even when you want to do simple things like list all the children in a directory that has a file with Arabic name; the entire file name will not appear in the terminal (the issue occurs even if you use a font which support Arabic)

So it would be really nice if the terminal have at least basic Arabic language support

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #538 for more discussion.

/dup #538

You might also be interested in #4779
