### ISSUE TITLE
When I click About, and the mouse selects Windows terminal right-click copy, the terminal exits immediately

### ISSUE THREAD

**Issue by GrumpyCat0413** [microsoft/terminal#5268]
When I click About, and the mouse selects Windows terminal right-click copy, the terminal exits immediately

![image](https://user-images.githubusercontent.com/17582148/78670331-2840e280-7910-11ea-8227-d90e5f431d54.png)

**Comment by WSLUser** [comment]
Works for me on Version: 0.10.781.0

**Comment by zadjii-msft** [comment]
@GrumpyCat0413 Could you share your Windows build number and the version of the Windows Terminal you're running? Additionally, how did you install the Terminal? The Store? Chocolatey? The .msix straight from Github?

**Comment by GrumpyCat0413** [comment]
> @GrumpyCat0413 Could you share your Windows build number and the version of the Windows Terminal you're running? Additionally, how did you install the Terminal? The Store? Chocolatey? The .msix straight from Github?

 Version: 0.10.781.0
 The Store

**Comment by skyline75489** [comment]
This is shockingly similar to #4260 . I'm not sure the underlying problems are the same, though.

**Comment by DHowett-MSFT** [comment]
For now, I'll track this with /dupe #4260 :smile: same symptom, likely same cause.
