### ISSUE TITLE
Crash in ScrollConsoleScreenBuffer when destination coordinates overflow

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#5271]
# Environment

Windows build number: Version 10.0.18362.657

# Steps to reproduce

Compile and run the following C++ code in a conhost cmd shell:
```cpp
#include <windows.h>

void main() {
    SMALL_RECT rect = {0, 0, 40, 0};
    COORD dest = {32767, 0};
    CHAR_INFO fill = {L'X', 0x07};
    HANDLE output = GetStdHandle(STD_OUTPUT_HANDLE);
    ScrollConsoleScreenBufferW(output, &rect, NULL, dest, &fill);
}
```

# Expected behavior

The first 40 characters of the first line should fill with X's.

# Actual behavior

The console crashes. 

When the `ScrollRegion` function is copying the area that is being scrolled, the `_CopyRectangle` function makes use of the `Viewport::WalkInBoundsCircular` method, and that fails when the target position goes out of bounds. See here:

https://github.com/microsoft/terminal/blob/5de9fa9cf375e9b5bdc582d8d166604eeb519844/src/types/viewport.cpp#L411

**Comment by j4james** [comment]
FYI, I've just tested with the first open source release (commit d4d59fa3395012ca37ba12665da4ec11c7dcf9cb), and the bug was already present there. However, the legacy console doesn't have this issue.

In some ways this is could be considered a part of issue #4153, but I thought it worth raising separately because of the crash, and the fact that it's not obviously "safe math" code.

**Comment by DHowett-MSFT** [comment]
Regressed between RS5 (17763) and 19H1 (18362). Thanks!

**Comment by DHowett-MSFT** [comment]
Off triage, P2, /cc @miniksa for a conhost regression from the scrolling change in 19H1
