### ISSUE TITLE
Add support for profiles.defaults in defaults.json

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#5276]
# Description of the new feature/enhancement
defaults.json only supports `"profiles"` as a list, not an object. This means that `profiles.defaults` cannot be used to present the default values for `profiles`.

# Proposed technical implementation details (optional)
This is a surprisingly large change with very little gain. The `CascadiaSettings::LoadAll()` function must be rewritten to match the following order:

1. load defaults/profiles.defaults = A
2. load defaults/profiles.list = B		
   - apply [A] to [B]
   - apply [B] to [B]
3. load dynamics = C		
   - apply [A] to [C]
4. load user/profiles.defaults = D		
   - apply [D] to all existing profiles [B, C]	
5. load user/profiles.list = E		
   - apply [A] to [E]
   - apply [D] to [E]
   - apply [E] to [E]

Additionally, dynamic profiles add an additional level of complexity. Each dynamic profile generator relies on DefaultProfileUtils' `CreateDefaultProfile`. We need to layer defaults/profiles.defaults here. But defaults/profiles.defaults is saved in `CascadiaSettings`. So we need to find a way to ensure that a construction of a Profile object has defaults/profiles.defaults layers already.

**Comment by DHowett-MSFT** [comment]
We may want to consider a "prototype Profile" object that we `.Clone()`. This simplifies the flow:

1. load defaults/profiles.defaults = Prototype
2. load defaults/profiles.list
   - copy [Prototype] = B
   - layer `list[i]` on [B]
3. load dynamics
   - copy [Prototype] = C
   - dynamic loader changes [C]
4. layer user/profiles.defaults _on [Prototype]_
   - layer user defaults on all existing profiles [B, C]
5. load user/profiles.list
   - copy [Prototype] = D
   - layer `list[i]` on [D]

If you notice that 1-2 and 4-5 are _the same operation_, gold star. This will also reduce the difference between "defaults.json" and "settings.json".

**Comment by DHowett-MSFT** [comment]
Tagging into v1.x. We should figure out the settings model in advance of doing the settings UI.

**Comment by JustinGrote** [comment]
Related to this, defaults.json should have the "defaults" and "list" subformat as well by default. The more "OneOf" entries in the JSON schema that can be removed for the various configuration iterations that can be removed, the better for code generation tools like my MSTerminalSettings 2.0 powershell module.

**Comment by DHowett-MSFT** [comment]
That's not exactly "related to" this issue insofar as it literally just _is_ this issue. :smile:
We just about did this for v1, but recognized that it would be too great a change for us to feel comfortable with ☹️
