### ISSUE TITLE
Please Support the Tango Color Theme

### ISSUE THREAD

**Issue by rkitover** [microsoft/terminal#5281]
# Description of the new feature/enhancement

Include the Tango color scheme in the list of predefined color schemes.

Ideally both Tango Light and Tango Dark, but including just Tango Dark, which is often called simply Tango would be fine as well, since that is what most people would want.

Both of these are included in iterm2 and various other places.

This is the default terminal color scheme on Ubuntu and various other linux distributions.

It is, in my opinion, the nicest set of terminal colors, and many linux and mac users agree.

I am using it in my `settings.json` as:

```json
    {
      "background": "#000000",
      "black": "#000000",
      "blue": "#3465a4",
      "brightBlack": "#555753",
      "brightBlue": "#729fcf",
      "brightCyan": "#34e2e2",
      "brightGreen": "#8ae234",
      "brightPurple": "#ad7fa8",
      "brightRed": "#ef2929",
      "brightWhite": "#eeeeec",
      "brightYellow": "#fce94f",
      "cyan": "#06989a",
      "foreground": "#d3d7cf",
      "green": "#4e9a06",
      "name": "Tango Dark",
      "purple": "#75507b",
      "red": "#cc0000",
      "white": "#d3d7cf",
      "yellow": "#c4a000"
    }
```

# Proposed technical implementation details (optional)

I am happy to do all the necessary work on a proper PR for this, I just need a bit of guidance.

I found `cascadia/TerminalApp/defaults.json` but the comment at the top says it's a generated file.

Please tell me what generates it, and I will add all the necessary source material, attributions, copyrights and theme sources as necessary.

**Comment by DHowett-MSFT** [comment]
Hey, sorry about that! The part about it being generated is kind of a lie. It says it’s generated so that when it gets copied into the terminal application data it has that header so people who receive a copy of the app know not to touch it. The version in our source tree actually is the live source copy :smile:

**Comment by zadjii-msft** [comment]
Thanks for offering to do this! I've tagged this issue up as such. 

I'm having a hard time finding the license for the Tango color scheme, if one even exists. There's [this page](https://web.archive.org/web/20160202102503/http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines) that's got the palette from the original tango.freedesktop.org site, but I'm not seeing anything mentioned on there.

**Comment by DHowett-MSFT** [comment]
If color schemes can be licensed, and the license is compatible, I'd be happy to ship this one by default. If they can't be licensed, I'd like to figure out what our options are here. I'm taking this one off the triage queue, as i do think it'd be pretty cool, and it is appropriately tagged up.

**Comment by rkitover** [comment]
According to this page, all Tango Desktop Project materials were released to the public domain in 2009:

http://tango-project.org/

I am working on a PR, should be ready in a few hours at most.

**Comment by OskarKlintrot** [comment]
Is there any way to use Tango Light but override just the first bit in yellow? I find it really difficult to see that part.
![image](https://user-images.githubusercontent.com/6783879/80562096-f2f75400-89e6-11ea-9d05-ff53a01b74a0.png)

**Comment by DHowett-MSFT** [comment]
You will want to look into customizing PSReadline. PSReadline is the powershell module that sets the colors at the edit line.

**Comment by OskarKlintrot** [comment]
So I was barking up the wrong tree apperently, thanks! 

For anyone interested how to change the color, open your profile:

```powershell
> code $PROFILE # Will open the profile in VS Code
```

Add this line:

```powershell
Set-PSReadLineOption -Colors @{ "Command"=[ConsoleColor]::DarkYellow } # or whatever color you prefer
```

You can play around with `Set-PSReadLineOption` in the terminal if you want, the changes won't be saved.
