### ISSUE TITLE
Scrollback buffer doesn't work with screen

### ISSUE THREAD

**Issue by wmertens** [microsoft/terminal#5284]
# Environment

```none
Windows build number: 10.0.19041.172
Windows Terminal version (if applicable): 0.10.781.0

Any other software? GNU screen in WSL2
```

# Steps to reproduce

I have the following in my .screenrc:
```
  termcapinfo xterm*|xs ti=\E7\E[?47l
```

This makes it so screen doesn't internally scroll but instead just lets lines go out into the terminal, so that I can scroll the terminal buffer which is bigger and faster than screen's buffer.

# Expected behavior

This setting works in all terminals I've used so far, including Hyper

# Actual behavior

In Terminal, the setting has no effect, and the screen scrollback buffer doesn't flow into the terminal scrollback buffer.

**Comment by DHowett-MSFT** [comment]
This is the intersection of a couple different issues.

* We don't support alternate screen buffer through private mode `47` (we support 1049) -- tracked in #3082
* When there's a scrolling region, even if it touches the top of the screen, it doesn't push lines into the scrollback: #3673

/dup #3082 #3673

Thanks!
