### ISSUE TITLE
Typing emoji breaks cursor position

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#529]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
Microsoft Windows [Version 10.0.18362.86]
```

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Trying to type something like this into the new Windows Terminal

```
echo "I💙MS"
```

When I bring up the emoji keyboard, it doesn't interact with the terminal properly at all, but after I close it, I do get the character I selected. 

The problem is that the console acts as if the emoji is double-character-width, and after the emoji, shows the cursor a character to the left of where it should be. More emoji? Further to the left. Eventually it becomes impossible to work because you can't tell where your cursor really is.

* What's wrong / what should be happening instead:

Emoji should be treated as a character and the bar/cursor should go to the right place.

NOTE: not shell-specific

**Comment by oising** [comment]
I get a different error when I try to use the emoji keyboard (win+period), but I'm compiled with v142 toolset and I retargeted all SDKs to 18362. I get this:

![conhost_abort](https://user-images.githubusercontent.com/1844001/57321031-57325100-70ce-11e9-8a30-4a6cc8645cb5.jpg)

**Comment by oising** [comment]
But the shell doesn't terminate outright, I can ctrl+t to bring up another tab but the target tab for input is hosed afaict.

**Comment by zadjii-msft** [comment]
This is a combo of things:

* [ ] The emoji keyboard interacts poorly with the Windows Terminal
* [ ] Emoji roundtrip poorly through conpty, causing the cursor position to be wrong.
* [ ] Trying to type emoji (in powershell) in Windows Terminal causes the attached conpty to crash

**Comment by nizos** [comment]
I can get mine to echo:
`"I❤MS"`
but not:
`"I💙MS"`

I am looking closer at it, it is buggy for sure.
____________
Microsoft Windows [Version 10.0.18362.86]

**Comment by adiviness** [comment]
I'm in the process of fixing some of our emoji input when running cmd.exe. What's happening is that while the output buffer can store UTF-16 surrogate pairs, conhost.exe has an edit buffer cmd.exe's prompt that can't yet understand the surrogate pairs. The difference between ❤ and 💙 is that the red heart is not a surrogate pair while the blue heart is. 

I'm not 100% sure this is a conpty problem to be honest, at least for cmd.exe it has to do with conhost managing some of cmd's interactive features.

**Comment by zadjii-msft** [comment]
Hey so this issue was filed like 10 months ago, and there have been a ton of changes to the Terminal, conhost and conpty since then. Is anyone still seeing this?

![image](https://user-images.githubusercontent.com/18356694/76781489-c8c23d80-677c-11ea-8a60-05a2880a26e4.png)
