### ISSUE TITLE
Map Ctrl-K to clear scrollback buffer and screen

### ISSUE THREAD

**Issue by ragunyrasta** [microsoft/terminal#5290]
Map Ctrl-K to clear the scrollback buffer and screen

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1882 for more discussion.

/dup #1882

As I said in that thread:

> To clarify for future me - <kbd>cmd</kbd>+<kbd>k</kbd> is not something that's being handled by `bash` or the shell. This is the Terminal itself handling the keybinding, and clearing both the buffer and the scrollback.
> 
> You've described a user story that makes sense to me, so I'm gonna put this on the backlog. 
> * We'd probably want #1142 to be able to support adding keybindings for Clear Screen, Clear Scrollback, or Clear Both all on the same "clear" action.
> * We'll need #1193 for clearing the conpty buffer. W/o this, we'll just get the screen repainted immediately.
