### ISSUE TITLE
wsl vim is horribly broken after #5181

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#5291]
![image](https://user-images.githubusercontent.com/14316954/78860291-aec7f380-79e6-11ea-9ad7-90cf224a0082.png)

tap output:

```
~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K
```

no cursor movement after the EL :/

**Comment by zadjii-msft** [comment]
looking now
