### ISSUE TITLE
Horizontal Pane Splitting puts cursor on incorrect line

### ISSUE THREAD

**Issue by spetz83** [microsoft/terminal#5295]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
10.0.19041.0
Windows Terminal version (if applicable):
0.10.781.0
Any other software?
N/A
```

# Steps to reproduce

- Open Windows Terminal
- Trigger Horizontal pane split

# Expected behavior
I expect the pane to be split horizontally with the cursor on the same line as the current directory prompt similar to below screen shot.
![image](https://user-images.githubusercontent.com/291664/78909781-9fc65d00-7a49-11ea-8209-2866a79da566.png)

# Actual behavior
When you do the first horizontal pane split the cursor jumps down a line in the newly opened pane. However, if you split horizontally a second time, the second pane cursor appears correctly. See below gif.
![terminal](https://user-images.githubusercontent.com/291664/78910045-f2a01480-7a49-11ea-8ae5-e1bee7f58353.gif)

A vertical pane split does not exhibit the same behavior.

**Comment by zadjii-msft** [comment]
GAH that's not great.

Could you share the config for whatever shell you're using? I'm betting that this is due to that first line that's getting printed in your prompt. Clearly the right text is in the buffer (because the third pane you create refreshes the contents of the second pane to be displayed correctly), but maybe we missed a frame or something.

I'd also bet that #5181 either made this way better or worse (see #5291).

**Comment by spetz83** [comment]
So, I'm using ZSH, so do you want the zshrc file I have? I've been using the same zshrc file for quite a while, this only started happening in the last month or 2.

**Comment by spetz83** [comment]
I should clarify, ZSH using Oh My ZSH.

**Comment by spetz83** [comment]
[zshrc-bak.txt](https://github.com/microsoft/terminal/files/4457880/zshrc-bak.txt)

**Comment by zadjii-msft** [comment]
Yikes okay, I'm not seeing this on my build with the same `.zshrc`, but it's entirely possible that the bits from #5181 fixed this, making it hard for me to repro. I'm pulling a 0.10 build now to check if that build will repro this.

**Comment by zadjii-msft** [comment]
Okay I unfortunately can't get this to repro on 0.10.781 either, even with the same zsh config. I'm _really_ hoping that this is just going to go away in 0.11, but since I can't be sure, I think I'm just going to have to stick it in the 1.x milestone.

**Comment by spetz83** [comment]
@zadjii-msft Wanted to let you know. I updated to 0.11.1121.0 and I can no longer replicate this issue. Everything seems to be working correctly again. Thanks for looking into this.

**Comment by zadjii-msft** [comment]
I'm glad to hear it! Thanks for following up on this thread 😄
