### ISSUE TITLE
Shift+Enter always submits, breaking PSReadline features [Windows.Terminal]

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#530]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.18362.86]
```
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Trying to add an empty line in a multi-line input by pressing `Shift` + `Enter` with PSReadline in PowerShell

* What's wrong / what should be happening instead:

`Shift+Enter` is treated as `Enter`, and it tries to run my incomplete command line

**Comment by zadjii-msft** [comment]
So I'm not sure this is fixable without a _lot_ of work.

Because the Windows Terminal is using ConPTY as a backend, we can only send keypresses to the attached client app that are encodable by VT sequences. Unfortunately, there's no way to differentiate between Enter and Shift+Enter with just VT. 

So, we need to add support for encoding entire `INPUT_RECORD`s as VT sequences. Then add support to conpty (in `InputStatemachineEngine.*`) for parsing such an input record. Then we need to enable the terminal to tell conpty that it should expect such a type of input sequences, and the terminal needs to be able to synthesize them.

It's something that's doable, but not without at least a weeks worth of work, not including testing.

**Comment by Jaykul** [comment]
Ouch. Didn't even think of that. 

At least in PSReadLine it's settable, so I will just have to try to learn to use `Ctrl+Enter` instead
 ... that seems to send a linefeed instead of a carriage return, so it's detectable.

There's probably a bigger picture here about helping those of us who aren't used to VT learn which combinations just aren't going to work...

**Comment by pingzing** [comment]
This actually seems to be a bit of a broader problem--a lot of PSReadLine hotkeys that use Ctrl+<key> chords don't work either. `Ctrl+Space` and `Ctrl+.` come to mind as well.

**Comment by flxflx** [comment]
The issue seems to prevent the typing of certain characters on non-US keyboard layouts. For example, I cannot type *\* (alt-gr+?) on my German keyboard. This makes Terminal pretty much unusable for me.

**Comment by krokofant** [comment]
Any known workaround for this?

**Comment by herolover** [comment]
It's really important. In Far I can't open a windows explorer by pressing shift+enter, or call a context menu by pressing a corresponding key of keyboard.

**Comment by Jaykul** [comment]
I think the workaround is to use different hotkeys or different (VT-capable) apps.

The bottom line is that Windows Terminal is a _Terminal Emulator_, and both it and ConPTY are inherently limited by (really ancient) standards. I'm almost positive that "we" (the community of Windows users?) don't want to simultaneously "embrace and extend" those standards 😉

I still think the best solution is just education about what key combinations can't be encoded ...

**Comment by zsimic** [comment]
I noticed that latest 1.4.3243.0 seems to still be sending (as observed with `showkey -a` in an ubuntu wsl2 session):
- `0x0d` for `enter`
- `0x0d` also for `shift+enter`
- `0x0a` for `ctrl+enter`
- nothing for `ctrl+shift+enter`

I worked around it by adding these actions to my `settings.json`:
```
{ "command": {"action": "sendInput", "input": "\u001b[13;2u" }, "keys": "shift+enter" },
{ "command": {"action": "sendInput", "input": "\u001b[13;5u" }, "keys": "ctrl+enter" },
{ "command": {"action": "sendInput", "input": "\u001b[13;6u" }, "keys": "ctrl+shift+enter" },
```

And similarly for `shift+space`:
```
{ "command": {"action": "sendInput", "input": "\u001b[32;2u" }, "keys": "shift+space" },
{ "command": {"action": "sendInput", "input": "\u001b[32;5u" }, "keys": "ctrl+space" },
{ "command": {"action": "sendInput", "input": "\u001b[32;6u" }, "keys": "ctrl+shift+space" },
```

**Comment by adouzzy** [comment]
> 
> 
> I noticed that latest 1.4.3243.0 seems to still be sending (as observed with `showkey -a` in an ubuntu wsl2 session):
> 
>     * `0x0d` for `enter`
> 
>     * `0x0d` also for `shift+enter`
> 
>     * `0x0a` for `ctrl+enter`
> 
>     * nothing for `ctrl+shift+enter`
> 
> 
> I worked around it by adding these actions to my `settings.json`:
> 
> ```
> { "command": {"action": "sendInput", "input": "\u001b[13;2u" }, "keys": "shift+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;5u" }, "keys": "ctrl+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;6u" }, "keys": "ctrl+shift+enter" },
> ```
> 
> And similarly for `shift+space`:
> 
> ```
> { "command": {"action": "sendInput", "input": "\u001b[32;2u" }, "keys": "shift+space" },
> { "command": {"action": "sendInput", "input": "\u001b[32;5u" }, "keys": "ctrl+space" },
> { "command": {"action": "sendInput", "input": "\u001b[32;6u" }, "keys": "ctrl+shift+space" },
> ```

This is gold. 
with https://www.asciitable.com/ , you can set any combination on shortcuts.
My emacs is flying in the terminal now. 
Huge thanks!

**Comment by jbsilva** [comment]
Same problem still happening in 2023 in Version: 1.12.10983.0.

> { "command": {"action": "sendInput", "input": "\u001b[13;2u" }, "keys": "shift+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;5u" }, "keys": "ctrl+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;6u" }, "keys": "ctrl+shift+enter" },

This worked for me.

**Comment by CervEdin** [comment]
> I noticed that latest 1.4.3243.0 seems to still be sending (as observed with `showkey -a` in an ubuntu wsl2 session):
> 
>     * `0x0d` for `enter`
> 
>     * `0x0d` also for `shift+enter`
> 
>     * `0x0a` for `ctrl+enter`
> 
>     * nothing for `ctrl+shift+enter`
> 
> 
> I worked around it by adding these actions to my `settings.json`:
> 
> ```
> { "command": {"action": "sendInput", "input": "\u001b[13;2u" }, "keys": "shift+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;5u" }, "keys": "ctrl+enter" },
> { "command": {"action": "sendInput", "input": "\u001b[13;6u" }, "keys": "ctrl+shift+enter" },
> ```
> 
> And similarly for `shift+space`:
> 
> ```
> { "command": {"action": "sendInput", "input": "\u001b[32;2u" }, "keys": "shift+space" },
> { "command": {"action": "sendInput", "input": "\u001b[32;5u" }, "keys": "ctrl+space" },
> { "command": {"action": "sendInput", "input": "\u001b[32;6u" }, "keys": "ctrl+shift+space" },
> ```

I did this but then I started getting ';2u` instead of space when lingering on the shift key while pressing space. Excluding `shift + space` did the trick.

**Comment by revoconner** [comment]
```AutoHotKey
; Sends Ctrl+Shift+Enter when Claude Code is active, otherwise normal Shift+Enter

#Persistent
#SingleInstance force

; Shift+Enter hotkey
+Enter::
    WinGet, activeProcess, ProcessName, A
    WinGetTitle, activeTitle, A

    ; Check if Windows Terminal with Claude Code (title starts with U+2733)
    if (activeProcess = "WindowsTerminal.exe" && SubStr(activeTitle, 1, 1) = Chr(0x2733))
    {
        ; Claude Code is active - send Ctrl+Shift+Enter
        Send ^+{Enter}
    }
    else
    {
        ; Not Claude Code - pass through normal Shift+Enter
        Send +{Enter}
    }
return
```

I use this AHK script to send ctrl+shift+enter when I send shift+enter if the active window is WindowsTerminal.exe and has the claude code unicode character in it - U+2733
