### ISSUE TITLE
Cmd/Bash input command macros

### ISSUE THREAD

**Issue by suchislife801** [microsoft/terminal#5308]
# Cmd/Bash input command macros

# Proposed technical implementation details

+ A method for allowing the clicking of user dynamically created buttons to call macros that contain cmd/bash commands in their native form.

For example

a. When a user is on Windows under a cmd tab, the button1_Click event could...

# Windows
button1_Click event =  dir
Action = list directory contents.

b. When a user is on Linux under a bash tab, the button_Click event could...

# Linux
button2_Click event =  ls
Action = list directory contents.

# A clear and concise description of what you want to happen.
+ In the process of creating a button, the user assigns a macro to it. A macro is nothing more then a string of native commands that already exist in their own respective operating systems.

+ The buttons would have a property propTargetSystem & propIssueCommand that would allow the user to target each macro created to their respective operating system.

+ Alternatively, this could be possibly implemented as a "Favorites" dropdown menu.

**Comment by zadjii-msft** [comment]
Okay so this is kinda similar to #5273. There's also #2046, which could be combined with #a-shortcut-action-for-sending-input (I can't find the issue ATM) might be able to achieve this. 

Since this is so similar, I think I'm just going to resolve it as a dupe. Thanks!

/dup #5273
