### ISSUE TITLE
Feature Request: Consider supporting chromeless fullscreen mode like conhost alt+enter

### ISSUE THREAD

**Issue by oising** [microsoft/terminal#531]
As the title says: Conhost (V2 only?) has a legacy-style fullscreen mode, and with the recent ability to theme the scrollbars, this gives a pleasant clutter-free terminal experience. I'd like to see this with windows terminal also.

**Comment by zadjii-msft** [comment]
Sounds like a good feature to me.

**Comment by vapier** [comment]
i'd be wary of binding it to something like Ctrl-Enter.  there are applications (like Emacs) that users expect to be able to use modifiers with the Enter key.

of course, if there were generic keybindings settings, then it'd be somewhat of a moot issue as people could rebind however they liked.

**Comment by zadjii-msft** [comment]
Hey wadda ya know, we do plan on having all the keybindings configurable! So no need to worry about that :)

**Comment by miniksa** [comment]
its alt+enter and f11

**Comment by be5invis** [comment]
Borderless window or real exclusive mode like games?

**Comment by kfsone** [comment]
`Alt-Enter` for full-screen borderless dates back to the earliest days of Windows, and it transferred into GDI and then into every subsequent windows rendering API. Then eventually we got full-screen exclusive as an performance booster for early, primitive 3d cards.

`Alt-Enter` is what the built-in cmd/powershell console uses, both the new versions and versions of windows going all the way back to 95.

**Comment by BrainBacon** [comment]
To expand on what @kfsone said, `Alt-Enter` is used by [wsltty](https://github.com/mintty/wsltty) which is a great Terminal for WSL.

**Comment by mdtauk** [comment]
UWP has a full screen mode, as used by the Media Controls, Film & TV app, etc

**Comment by terrajobst** [comment]
To me, it's only about the window experience. I want a chromeless full window mode. I didn't even know about exclusive mode.

**Comment by rcarmo** [comment]
I would also appreciate having a zero-clutter full-screen mode via Alt-Enter.

**Comment by WSLUser** [comment]
Ideally we’d have both chromeless full window mode _and_ exclusive mode. 

> UWP has a full screen mode, as used by the Media Controls, Film & TV app, etc

We should have some XAML controls we can use to implement this then (and would probably be the better route than any custom solution).

**Comment by oblitum** [comment]
Is there any way at the moment to set fullscreen?

**Comment by zadjii-msft** [comment]
@mdtauk Let's not mix and match discussion threads, I'm pretty sure combining the tab with the pane is being tracked in #702

@oblitum Suggesting that users try another terminal emulator isn't really helpful in a discussion thread about trying to implement support for that feature in the Windows Terminal. Obviously other terminal emulators will have other features that we don't have yet in the first few _preview_ builds of the Windows Terminal. Let's try and keep the discussion to _how_ we implement those features and narrow that gap 😄

**Comment by fabricio7p** [comment]
This feature is pretty much all i need to switch to windows terminal.
For now i'll have to remain on regular cmd

**Comment by mdtauk** [comment]
I only meant if a full screen mode comes, without the Title Bar (which could use the same code for running Windows Terminal in Tablet Mode) then you need to decide if tabs are visible or hidden.

If you want the tabs to be always visible, making the entire Tab Bar blend in, will not be distracting and jarring.

That #702 issue is more about fitting into an Acrylic Title Bar.

Of course a full screen mode, could well hide the Tab Bar too, have it show on hover.

**Comment by Rican7** [comment]
Woot! Awesome work guys! Thank you! Stoked to try this out in the next release. 😀

**Comment by shanselman** [comment]
OMG

**Comment by oising** [comment]
YASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by rcarmo** [comment]
Yep. Entirely new world here - zero windows on screen :)
