### ISSUE TITLE
Ctrl+Shift+

### ISSUE THREAD

**Issue by danstur** [microsoft/terminal#5315]
# Environment

```none
Windows build number: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
For some reason on 

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
You can edit existing bug reports; you do not need to go file a new one to fix a typo. :smile:

**Comment by danstur** [comment]
@DHowett-MSFT Oh I wasn't aware that had happened, I'm sorry.

The cat decided to get attention and post the report in a rather.. intermediate state. Didn't realize that when fixing it I accidentally posted a new one 😆

**Comment by DHowett-MSFT** [comment]
No problem! This happens about as often as me accidentally closing one of our really big/loud issues and making the community mad (:wink:), so /shrug
