### ISSUE TITLE
Ctrl+Shift+C Not working to copy text

### ISSUE THREAD

**Issue by danstur** [microsoft/terminal#5316]
For some reason I can't use Ctrl+Shift+C on a new Windows Terminal installation with the default bindings (nothing changed in profiles.json). Ctrl+Insert works fine. 

I tried to explicitly add `{ "command": "copy", "keys": "ctrl+shift+c" }` in profiles.json but that didn't help either.

# Environment

```none
Windows build number: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
1. Open Windows Terminal. 
2. Select text and press Ctrl+Shift+C.

# Expected behavior
The text is put into the clipboard.

# Actual behavior
Nothing happens.

**Comment by DHowett-MSFT** [comment]
What is your keyboard layout?

**Comment by zadjii-msft** [comment]
Where are you trying to paste the text?

Does the text appear in the "cloud clipboard" (press <kbd>Win+v</kbd>)

Does copying from other applications and pasting _into_ the Terminal work?

Do you have any clipboard manager style applications installed?

**Comment by danstur** [comment]
@DHowett-MSFT English (with Austrian locale settings) with US Qwerty and German QWERTZ keyboard layouts. I tried with both without success.  

@zadjii-msft I tried notepad and the terminal itself. I can paste things from the clipboard into the terminal with ctrl+v without problems. 
There's nothing in the cloud clipboard. 
This is a new windows installation and I haven't installed any clipboard manager style applications - at least intentionally. Apart from the AMD chipset and GPU drivers, the realtek audio drivers and VS2019 I've installed everything I can think of via chocolatey. I added the list from choco list -lo at the end.

What's noticeable if I use ctrl+insert to copy the selection is removed, while using ctrl+shift+c the selection stays as-is. I tried cmd, the old PowerShell 5 and PowerShell Core 7 with the same behavior in all of them, so I think we can exclude PowerShell profiles as well

If I'm using the default PowerShell core shell (i.e. just open pwsh.exe) copying things via Ctrl+C works just fine. 

`choco list -lo`
```
7zip.install 19.0
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
chocolatey-misc-helpers.extension 0.0.3.1
chocolatey-windowsupdate.extension 1.0.4
coretemp 1.15.1.20190411
cpu-z.install 1.91
discord.install 0.0.306
DotNet4.5.2 4.5.2.20140902
dotnetcore-sdk 3.1.201
furmark 1.21.1.0
git.install 2.26.0
goggalaxy 1.2.67.58
gpg4win-vanilla 2.3.4.20191021
gpu-z 2.30.0
hearthstone-deck-tracker 1.1.6
hwinfo 6.20
hwinfo.install 6.24
irfanview 4.54
KB2533623 1.0.4
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3118401 1.0.4
kdiff3 0.9.98
nodejs.install 13.12.0
notepadplusplus.install 7.8.5
openvpn 2.4.7
powershell-core 7.0.0
prime95 29.4
pwsh 7.0.0
spotify 1.1.29.592
steam 3.0.1.20190215
treesizefree 4.4.1.1
vcredist140 14.24.28127.4
vcredist2015 14.0.24215.20170201
vscode.install 1.43.2
```

**Comment by myusrn** [comment]
why are the defaults copy = ctrl+shift+c and paste = ctrl+shift+v to begin with vs the ctrl+c and ctrl+v standard used everywhere else in windows?

**Comment by DHowett-MSFT** [comment]
@myusrn this has been discussed in a bunch of other threads, and is not worth on-topic for @danstur's bug report.

**Comment by zadjii-msft** [comment]
> What's noticeable if I use ctrl+insert to copy the selection is removed, while using ctrl+shift+c the selection stays as-is. I tried cmd, the old PowerShell 5 and PowerShell Core 7 with the same behavior in all of them, so I think we can exclude PowerShell profiles as well

That's certainly peculiar. 

Could you share you whole `profiles.json` file? Maybe there's some peculiar combo of settings that's causing this? Because by all accounts, Ctrl+Shift+C should be working for you 🤔

**Comment by danstur** [comment]
@zadjii-msft Certainly. The path is `C:\Users\<UserName>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json` I opened it via the GUI (but just to be save that there's not a problem here somehow). The file is as follows: 
```

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
        },
        "list":
        [
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"            },
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": [
	]
}
```

**Comment by danstur** [comment]
@zadjii-msft I created a sample WPF app to see if I could reproduce the error and lo-and-behold I have the same problem there. So I guess some helpful program decided to register a global hotkey. I love those things.

Sorry to take your time, most certainly a user error.

**Comment by zadjii-msft** [comment]
Hey no problem at all! I'm glad you were able to figure it out, and I'm especially happy that you decided to post your findings once you figured it out ☺️

**Comment by onuryurdupak** [comment]
> @zadjii-msft I created a sample WPF app to see if I could reproduce the error and lo-and-behold I have the same problem there. So I guess some helpful program decided to register a global hotkey. I love those things.
> 
> Sorry to take your time, most certainly a user error.
> 
> Edit: For anyone else having the same problem: It was the Radeon GPU driver that decided to helpfully enable a dozen global hotkeys without mentioning that anywhere. (It's always the awful drivers isn't it?)

Bless you. It would have been very hard to pinpoint (the very same issue) if it wasn't for your edit. :)

**Comment by vinayak19th** [comment]
> @zadjii-msft I created a sample WPF app to see if I could reproduce the error and lo-and-behold I have the same problem there. So I guess some helpful program decided to register a global hotkey. I love those things.
> 
> Sorry to take your time, most certainly a user error.
> 
> Edit: For anyone else having the same problem: It was the Radeon GPU driver that decided to helpfully enable a dozen global hotkeys without mentioning that anywhere. (It's always the awful drivers isn't it?)

Thanks. This fixed my error too. I use an Nvidia GPU and the iGPU on my CPU installed adrenaline software

**Comment by giggio** [comment]
> @zadjii-msft I created a sample WPF app to see if I could reproduce the error and lo-and-behold I have the same problem there. So I guess some helpful program decided to register a global hotkey. I love those things.
> 
> Sorry to take your time, most certainly a user error.
> 
> Edit: For anyone else having the same problem: It was the Radeon GPU driver that decided to helpfully enable a dozen global hotkeys without mentioning that anywhere. (It's always the awful drivers isn't it?)

Thank you!
Same thing here, it was the "AMD Software: Adrenaline Edition" in my case.
For anyone having the problem: click on the gear icon on the top right for settings, then go to the Hotkeys menu, and disable all hotkeys, or the "Toggle camera" option. I disabled it all.

**Comment by Letus252** [comment]
> @zadjii-msft I created a sample WPF app to see if I could reproduce the error and lo-and-behold I have the same problem there. So I guess some helpful program decided to register a global hotkey. I love those things.
> 
> Sorry to take your time, most certainly a user error.
> 
> Edit: For anyone else having the same problem: It was the Radeon GPU driver that decided to helpfully enable a dozen global hotkeys without mentioning that anywhere. (It's always the awful drivers isn't it?)

Same problem for me, thanks for providing fix.
