### ISSUE TITLE
define autostart for profile

### ISSUE THREAD

**Issue by leisefuxX** [microsoft/terminal#5322]
# Description of the new feature/enhancement

is there a way to implement autostart into terminal? so when i run profile "AD-Shell" it opens me powershell.exe with command "Enter-PSSession -ComputerName SOMEHOST-Credential someuser" ?
i tried adding it to commandline-option in profiles.json and it starts the command but closes terminal as soon as command is run

pretty much like adding a program to .bashrc or .profile in linux (:

# Proposed technical implementation details (optional)

add a "start-command" switch to profiles.json

**Comment by zadjii-msft** [comment]
Could you share your `profiles.json` file?


I'm _pretty sure_ that just adding `-noexit` to the powershell command you're using will prevent Powershell from exiting after the first command, but I'm not a pwsh wizard.

**Comment by leisefuxX** [comment]
i tried something like 
            "commandline": "powershell.exe -NoExit -Command {Enter-PSSession -ComputerName SOMEHOST -Credential SOMEUSER}" ,
inside the profiles.json but no luck

**Comment by DHowett-MSFT** [comment]
Please share how it's failing.
