### ISSUE TITLE
After changing key binding to open new tab "Ctrl+shift+6" still works 

### ISSUE THREAD

**Issue by nimabokhar** [microsoft/terminal#5323]
#env:  Microsoft Windows [Version 10.0.18363.752]
I need to issue the following sequence in an ssh session Ctrl+^but this key binding is used for "newTabProfile5"
but after changing the keymap to "ctrl+shift+0"
the old keymap still opens a new tab

**Comment by DHowett-MSFT** [comment]
Did you “replace” the original key binding by setting its command to `"unbound"`, or did you just delete it? Can you share a copy of your `profiles.json` file?

**Comment by nimabokhar** [comment]
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "globals": {
        "alwaysShowTabs": true,
        "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "initialCols": 120,
        "initialRows": 30,
        "keybindings": [
            {
                "command": "closeTab",
                "keys": [
                    "ctrl+w"
                ]
            },
            {
                "command": "newTab",
                "keys": [
                    "ctrl+t"
                ]
            },
            {
                "command": "newTabProfile0",
                "keys": [
                    "ctrl+shift+1"
                ]
            },
            {
                "command": "newTabProfile1",
                "keys": [
                    "ctrl+shift+2"
                ]
            },
            {
                "command": "newTabProfile2",
                "keys": [
                    "ctrl+shift+3"
                ]
            },
            {
                "command": "newTabProfile3",
                "keys": [
                    "ctrl+shift+4"
                ]
            },
            {
                "command": "newTabProfile4",
                "keys": [
                    "ctrl+shift+5"
                ]
            },
            {
                "command": "newTabProfile5",
                "keys": [
                    "ctrl+shift+-"
                ]
            },
            {
                "command": "newTabProfile6",
                "keys": [
                    "ctrl+shift+7"
                ]
            },
            {
                "command": "newTabProfile7",
                "keys": [
                    "ctrl+shift+8"
                ]
            },
            {
                "command": "newTabProfile8",
                "keys": [
                    "ctrl+shift+9"
                ]
            },
            {
                "command": "nextTab",
                "keys": [
                    "ctrl+tab"
                ]
            },
            {
                "command": "openSettings",
                "keys": [
                    "ctrl+,"
                ]
            },
            {
                "command": "prevTab",
                "keys": [
                    "ctrl+shift+tab"
                ]
            },
            {
                "command": "scrollDown",
                "keys": [
                    "ctrl+shift+down"
                ]
            },
            {
                "command": "scrollDownPage",
                "keys": [
                    "ctrl+shift+pgdn"
                ]
            },
            {
                "command": "scrollUp",
                "keys": [
                    "ctrl+shift+up"
                ]
            },
            {
                "command": "scrollUpPage",
                "keys": [
                    "ctrl+shift+pgup"
                ]
            },
            {
                "command": "switchToTab0",
                "keys": [
                    "alt+1"
                ]
            },
            {
                "command": "switchToTab1",
                "keys": [
                    "alt+2"
                ]
            },
            {
                "command": "switchToTab2",
                "keys": [
                    "alt+3"
                ]
            },
            {
                "command": "switchToTab3",
                "keys": [
                    "alt+4"
                ]
            },
            {
                "command": "switchToTab4",
                "keys": [
                    "alt+5"
                ]
            },
            {
                "command": "switchToTab5",
                "keys": [
                    "alt+6"
                ]
            },
            {
                "command": "switchToTab6",
                "keys": [
                    "alt+7"
                ]
            },
            {
                "command": "switchToTab7",
                "keys": [
                    "alt+8"
                ]
            },
            {
                "command": "switchToTab8",
                "keys": [
                    "alt+9"
                ]
            }
        ],
        "requestedTheme": "system",
        "showTabsInTitlebar": true,
        "showTerminalTitleInTitlebar": true,
        "wordDelimiters": " ./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}~?\u2502"
    },
    "profiles": [
        {
            "acrylicOpacity": 0.65,
            "background": "#012456",
            "closeOnExit": true,
            "colorScheme": "Campbell",
            "commandline": "powershell.exe",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 11,
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name": "Windows PowerShell",
            "padding": "0, 0, 0, 0",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%",
            "useAcrylic": true
        },
        {
            "acrylicOpacity": 0.75,
            "closeOnExit": true,
            "colorScheme": "One Half Dark",
            "commandline": "cmd.exe",
            "cursorColor": "#FFFFFF",
            "cursorShape": "vintage",
            "fontFace": "Consolas",
            "fontSize": 11,
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "name": "cmd",
            "padding": "0, 0, 0, 0",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%",
            "useAcrylic": true
        },
        {
            "acrylicOpacity": 0.75,
            "closeOnExit": true,
            "colorScheme": "One Half Dark",
            "commandline": "wsl.exe -d Ubuntu",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 11,
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
            "name": "Ubuntu",
            "padding": "0, 0, 0, 0",
            "snapOnInput": true,
            "useAcrylic": true
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        },
        {
            "guid": "{46ca431a-3a87-5fb3-83cd-11ececc031d2}",
            "hidden": false,
            "name": "kali-linux",
            "source": "Windows.Terminal.Wsl"
        }
    ],
    "schemes": [
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cyan": "#3A96DD",
            "foreground": "#F2F2F2",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#073642",
            "black": "#073642",
            "blue": "#268BD2",
            "brightBlack": "#002B36",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cyan": "#2AA198",
            "foreground": "#FDF6E3",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#D30102",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#073642",
            "blue": "#268BD2",
            "brightBlack": "#002B36",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cyan": "#2AA198",
            "foreground": "#073642",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#D30102",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        }
    ]
}

**Comment by nimabokhar** [comment]
I have just changed the key combination in double quotes

[windows terminal config.txt](https://github.com/microsoft/terminal/files/4469210/windows.terminal.config.txt)

**Comment by zadjii-msft** [comment]
Wow your `profiles.json` is pretty old - thanks for being such an early adopter of the Terminal 😄 

Your keybindings actually come from two places - both your settings file (`profiles.json`) and a set of defaults (which you can find [here](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json)). When you changed the keybinding for "newTabProfile5" to `"ctrl+shift+-"`, you weren't actually removing the old (default) keybinding, you were just adding a new keybinding to <kbd>ctrl+shift+-<kbd>.

You can unbind the default keybinding by adding the following to your `profiles.json` file:

```json
            { "command": "unbound", "keys": "ctrl+shift+6" },
```

This will remove the default keybinding of <kbd>ctrl+shift+6</kbd>. You can read more [in this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md).
