### ISSUE TITLE
No way to Rename / Name Tenants

### ISSUE THREAD

**Issue by t0dbld** [microsoft/terminal#5325]
Using Azure Cloudshell with Terminal it brilliantly can save tenants (thank you) however It does the naming on its own, and to the best of my knowledge we can not rename them later, working as a Devops engineer for a large MSP, makes this less than ideal scenario. Esp across devices where the first usage and thus named Default Directory is likely not even the same.  Additionally if there are mutiple accounts with in an organization (lets say a company has an Azure AD domain, and multiple employees have an azure account, as well as a main organization azure account, well I'm sure you get the idea)  Perhaps we could add this to the existing profile.json where names could be edited ?

**Comment by DHowett-MSFT** [comment]
Funny enough, I was working in the area already. Would this help?

![image](https://user-images.githubusercontent.com/14316954/79058261-8deae280-7c20-11ea-97e4-2652b5108c8a.png)
![image](https://user-images.githubusercontent.com/14316954/79058263-93482d00-7c20-11ea-9238-17dfd6ec7db0.png)


I know it's a far cry from nicknames, but perhaps it'd  life a bit easier in the interim.

**Comment by t0dbld** [comment]
showing fqdn before the subscription ID ? If so yes would be better in the interim
