### ISSUE TITLE
ColorTool does not resolve schemes properly, and does not work with WSL paths

### ISSUE THREAD

**Issue by johnazariah** [microsoft/terminal#5326]
# Environment

10.0.18363.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

Ubuntu on WSL

# Steps to reproduce

- on Windows Command Shell/PowerShell/GitBash
    * running `ColorTool.exe <schemename>` (without extension) does not resolve the scheme
    * running `ColorTool.exe <schemename.extension>` resolves the scheme correctly. 

This behaviour is contrary to the advertised behaviour, which says that the scheme will be resolved trying a specific order of extensions

- on Ubuntu bash running in WSL
    * running `ColorTool.exe -x <schemename>` (without extension) does not resolve the scheme
    * running `ColorTool.exe -x <schemename.extension>` does not resolve the scheme and throws exceptions. 

This behaviour is also not the expected behaviour.

# Expected behavior

`ColorTool.exe OneHalfDark` should have the same behaviour as `ColorTool.exe OneHalfDark.itermcolors`, and should actually load the terminal colors on both Windows shells and WSL shells

# Actual behavior

![before](https://user-images.githubusercontent.com/830311/79059824-3b66f180-7c33-11ea-80f0-fb1686eb0876.JPG)
![before-wsl](https://user-images.githubusercontent.com/830311/79059826-402ba580-7c33-11ea-8f1a-87a3cbe8e8fb.JPG)

**Comment by DHowett-MSFT** [comment]
It looks like this might be because your color schemes are in the WSL-only part of the filesystem. We haven’t yet done the compatibility work required to make sure ColorTool can use the new `\\wsl$` redirector paths from Windows 19H1.

**Comment by johnazariah** [comment]
Thanks, @DHowett-MSFT 

I've put it a fix that works in my test cases...

https://github.com/microsoft/terminal/pull/5327
![after](https://user-images.githubusercontent.com/830311/79060162-859da200-7c36-11ea-9ed2-02b47459b88d.JPG)
![after-wsl](https://user-images.githubusercontent.com/830311/79060166-87fffc00-7c36-11ea-9b2b-3993bca992f6.JPG)

Hope this helps :)

**Comment by DHowett-MSFT** [comment]
Thanks for submitting a fix! We're a little behind on pull request reviews right now, but I'll tag this bug up properly in the meantime.
