### ISSUE TITLE
Feature Request: Full screen (like alt+enter in cmd)

### ISSUE THREAD

**Issue by pres1er** [microsoft/Terminal#533]
Hi! Consider Supporting full screen terminal as already implemented in cmd.exe. It's very convenient.

**Comment by DHowett-MSFT** [comment]
hi,
*please* look for similar issues before reporting your own. The existing feature request for full screen isn’t even off the front page of issues yet.

**Comment by zadjii-msft** [comment]
For the record, the dupe is in #531
