### ISSUE TITLE
Ctrl+F Search in Console Output

### ISSUE THREAD

**Issue by Dev1lroot** [microsoft/terminal#5330]
# Description of the new feature/enhancement
Ctrl+F Search in Console Output (Like in browsers or notepad)

# Proposed technical implementation details (optional)
- Open a dialog or pop a toolbar for search
- Highlight all matches by foreground color
- Jump from line to line by F3 or Enter

**Comment by DHowett-MSFT** [comment]
This exists. Press Ctrl+Shift+F
