### ISSUE TITLE
When copying wrapped text, occasionally copies rendered newline

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/terminal#5332]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19587.1000]
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
Nope.
```

# Steps to reproduce
resize the window to the size of your phone, and either over ssh or on localhost, echo a long string such as 
`asdfasdfasd65f4a6s5d4f56asd4f65a4sdf654asd65f4a6s5d4f65a4sdf65a4sdf65as6dfsdaqwfasd231xcvedfr9864werasdf354asd`

 Select and copy the terminal output
and then without resizing paste elsewhere
# Expected behavior
Copy/paste properly

# Actual behavior
At the time of creating this issue, it was not occurring, 
but I will describe
I cat'ed this file to share to my buddy off my server over ssh
```
[Unit]
Description=Webserver for VSCODE
Documentation=https://github.com/cdr/code-server/
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=on-abnormal
StartLimitInterval=10
StartLimitBurst=3

User=code
Group=code

#WorkingDirectory=/home/developer/Workspace
ExecStart=/opt/code-server/program/code-server --extensions-dir /opt/code-server/extensions --user-data-dir /opt/code-server/data/ /home/code/Workspace --auth=none --host 0.0.0.0 --disable-ssh
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target
```

selected text was wrapped so the `ExecStart` directive looked like this
```
ExecStart=/opt/code-server/program/code-server --extensions-dir /opt/code-serv
er/extensions --user-data-dir /opt/code-server/data/ /home/code/Workspace --a
uth=none --host 0.0.0.0 --disable-ssh
```
And when I pasted it it pasted what It looked like in the terminal, with no regard for the fact there was no new lines.

This happens a bit too often for my liking, (at least on average of constant use, 3 times an hour)

**Comment by skyline75489** [comment]
This should be fixed by #5181, if i'm not mistaken

**Comment by Merith-TK** [comment]
well if it is fixed, the update has not rolled out... last release was almost a month ago

**Comment by DHowett-MSFT** [comment]
An astute observation.

**Comment by Merith-TK** [comment]
yep. forgot to close this sorry,
