### ISSUE TITLE
Rename tab title not working for WSL and Bash

### ISSUE THREAD

**Issue by matheusfelipeog** [microsoft/terminal#5333]
Hi :)

# Bug report

I use the latest Windows Terminal with PowerShell, CMD, Ubuntu (WSL) and Bash (Git Bash for Windows) and I can't change the title of the Ubuntu and Bash tab in the `profiles.json file`.

I saw that it was implemented in [#1358](https://github.com/microsoft/terminal/pull/1358), but it doesn't work in the cases I described.

And why this?
Is there a solution?

# Configuration and Execution

In `profiles.json file`:
![image](https://user-images.githubusercontent.com/50463866/79081464-08386700-7cf4-11ea-9f38-37f47c7550d1.png)

In Windows Terminal:
![image](https://user-images.githubusercontent.com/50463866/79081501-78df8380-7cf4-11ea-8775-3985b1c32c0a.png)

But it's working for CMD and PowerShell:

![image](https://user-images.githubusercontent.com/50463866/79081616-86e1d400-7cf5-11ea-9444-faeecf9a1d97.png)
![image](https://user-images.githubusercontent.com/50463866/79081597-6154ca80-7cf5-11ea-9b4e-4d258976715a.png)

**Comment by DHowett-MSFT** [comment]
Turn on the `suppressApplicationTitle` option. The "tab title" is a recommendation, and the application can delete it if it wants to. Bash usually does. `supressApplicationTitle` overrides bash.

**Comment by matheusfelipeog** [comment]
Oh, right. It worked. 
Thanks 😄
