### ISSUE TITLE
CreatePseudoConsole API uses old conhost even though the latest Windows Terminal is installed

### ISSUE THREAD

**Issue by luke1961** [microsoft/terminal#5334]
# Environment
Windows 10, tried with multiple builds.
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

1. Create a simple program which uses CreatePseudoConsole API.
2. Launch Process Explorer
3. Find your process in the process tree
4. Watch what got launched by CreatePseudoConsole
# Expected behavior

Expected to see OpenConsole from the Windows Terminal folder
# Actual behavior

I see that the old conpty is being launched instead of OpenConsole. This is a serious problem because the old conpty has problems with emoji characters etc. The VTPipeTerm from your package has the same problem when it uses CreatePseudoConsole. Of course CreateConPty in conpty.h may be modified to brute force a specific path in the manual creation mode but this is not my point. I would like the CreatePseudoConsole to work because I like the control it gives me over child process creation. Any suggestions? Even a hack will do for now. or maybe a 'CreatePseudoconsoleEx' that allows for a path to the conpty/OpenConsole? Or an installation option in Windows Terminal setup to replace the existing conpty.

**Comment by DHowett-MSFT** [comment]
Yeah, this is by design for now. It's complicated, because conhost is a system component. You'll have to wait until we can finish #1130 and #3577.

/dup #1130
