### ISSUE TITLE
Wrong "contributing" link in Specification Tracker project description

### ISSUE THREAD

**Issue by Rems19** [microsoft/terminal#5335]
It's not really a documentation issue in itself but it's the closest category I think.
On the [projects page](https://github.com/microsoft/terminal/projects), the link "the contributions guidelines" points to https://github.com/microsoft/terminal/blob/master/doc/contributing.md which does not exist. I'm guessing the correct file to link would be https://github.com/microsoft/terminal/blob/master/CONTRIBUTING.md.

**Comment by DHowett-MSFT** [comment]
Thanks! Fixed!
