### ISSUE TITLE
Feature Request - Support multiple default Profiles

### ISSUE THREAD

**Issue by dkling-msft** [microsoft/terminal#5338]
We have different terminals for different git repos. I have a shorter list that I would like windows terminal to open by default, however there is only one defaultProfile that can be selected. It would be great if Windows Terminal allowed me to specify a list of default profiles, and then open each one of them when a new window is opened.

**Comment by DHowett-MSFT** [comment]
Thanks for the request! This is a /dupe of #756, and you can _somewhat_ do this today by making a shortcut that runs `wt -p "Profile 1" ; -p "Profile 2"`
