### ISSUE TITLE
Readme doesn't match VS 2019 Preview Installer

### ISSUE THREAD

**Issue by jongio** [microsoft/Terminal#534]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

1903

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Readme has this:

> If you're running VS2019, you'll also need to install the "v141 Toolset" and "Visual C++ ATL for x86 and x64"

VS Preview install tool has this:
![image](https://user-images.githubusercontent.com/2163001/57330436-e0e01f80-70ca-11e9-9423-2800ca640859.png)

![image](https://user-images.githubusercontent.com/2163001/57330448-ea698780-70ca-11e9-8ae8-c14fffc6f1f4.png)

* What's wrong / what should be happening instead:

Since the names don't exactly match it is unclear if I'm selecting the right options.

**Comment by Pitta** [comment]
feels like im getting caught up here as well since my local builds are failing.

**Comment by chunliu** [comment]
you need to go to **Individual components** tab rather than **Workloads** tab to install it.

**Comment by jongio** [comment]
Yeah but the names still don’t match. Can you confirm what the exact names are and match then letter for letter?

________________________________

**Comment by chunliu** [comment]
It is "C++ ATL for v141 build tools", not "Visual C++". But it is not necessary to install v141 toolset in VS2019.

**Comment by timheuer** [comment]
I added more explicitness for VS2019 in this PR: https://github.com/microsoft/Terminal/pull/560

Additionally here is what my ultimate config options were to my VS2019 installer I needed:
VC++ Added components under the "Desktop Development for C++"
![image](https://user-images.githubusercontent.com/4821/57350003-24f61300-7111-11e9-9232-455f93835d99.png)

Additional under "Individual Components"
![image](https://user-images.githubusercontent.com/4821/57350027-5242c100-7111-11e9-8ba9-348c3ae4b0ec.png)

Under "Universal Windows Platform Development" despite having UWP selected as a workload for me these were not installed and I had to ensure they were to load the TerminalApp/Settings projects:
![image](https://user-images.githubusercontent.com/4821/57350062-74d4da00-7111-11e9-84a1-371b74f2a94c.png)

**Comment by jankun** [comment]
And make sure that you got enough space because the I just runned out of space (just for x86...) after 40gb random dependencies and 15gb+ obj's data...

**Comment by miniksa** [comment]
OK, I'm going to resolve this for now because we just merged #560 with more explicit instructions and names of the dependencies in the installer.
