### ISSUE TITLE
Crash in render engine due to directx device hanging up

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/terminal#5340]
VSExtensibility team got a watson logged internally with a crash coming from the terminal. After looking into the watson it appears that the crash is coming from this line:

https://github.com/microsoft/terminal/blob/ca33d895a359664c337c6482b853489823c216d3/src/renderer/base/renderer.cpp#L81

It looks like an intentional fail fast but it would be better to surface the error and allow the application hosting the rendering engine to decide if it should crash or not.

**Comment by DHowett-MSFT** [comment]
I'm gonna take this one on. Two things:

1. Implementing a backoff on retry, to increase our chances of having a successful render
2. Implementing a "stop rendering for god's sake" when we fail 3 times, so the application can kick the render engine to life.
