### ISSUE TITLE
-d option does not accept links and mounted drives in path for WSL

### ISSUE THREAD

**Issue by iorlov1** [microsoft/terminal#5344]
# Environment

```none
Windows build number: Version 10.0.18363.720
Windows Terminal version (if applicable): 0.9

Any other software?
```

# Steps to reproduce

Run wt -d with path to mounted drive or sym link
for example: wt split-pane -d \\wsl$\Ubuntu-18.04/mnt/c 

# Expected behavior

wt split-pane -d \\wsl$\Ubuntu-18.04/mnt - works and opens terminal in /mnt

/mnt/c is mounted Windows "C" drive.
So the expectation is that terminal would open in /mnt/c

# Actual behavior
[error 0x8007010b when launching `wsl.exe -d Ubuntu-18.04']

**Comment by DHowett-MSFT** [comment]
You’re looking for `-d C:\`. There is no compelling reason to use the WSL path mapper just to get back to a Windows path. Just use a Windows path.

**Comment by DHowett-MSFT** [comment]
The reason for this is that you can’t even access the Windows paths through wsl$ _outside of terminal._

**Comment by iorlov1** [comment]
i can't use c:\ . with WSL terminal ... 
Thats exactly the idea. to set start directory D drive for example where my working folder is, instead of launching WSL with user home and doing CD

**Comment by iorlov1** [comment]
more over i need in fact start WSL in /mnt/d/work/git_root something and i can't
/mnt/c was given as an example.

**Comment by DHowett-MSFT** [comment]
> I can't

`wt.exe` is always going to be a Windows application. If you need to pass a Windows path, that came in as a WSL path, from WSL: use the `wslpath` utility.

```
$ wslpath -w '/mnt/c'
C:\
$ wslpath -w '/home/duhowett'
\\wsl$\Debian\home\duhowett
```

**Comment by iorlov1** [comment]
not sure why it is closed

**Comment by iorlov1** [comment]
so how can i start WSL terminal on my d drive? or /mnt/d?
Any other non-mount point folder works fine ...

**Comment by iorlov1** [comment]
i try to pass WSL path - /mnt/c. This path do exists. i can cd into it after terminal starts. But i can;t set it as startup directory

**Comment by DHowett-MSFT** [comment]
_Terminal is a windows program. You have to pass windows paths. Sorry._

The WSL filesystem redirector **does not let you access Windows files in `/mnt`**. I promise.

This message is from Explorer

![image](https://user-images.githubusercontent.com/14316954/79167788-23ab7c80-7d9d-11ea-97ea-f13c5eca4845.png)

This is why Terminal _cannot use that path_. You _MUST_ provide the canonical Windows path.

**Comment by iorlov1** [comment]
this is not true
If i run ">wt split-pane -d \\wsl$\Ubuntu-18.04/bin" from CMD

WSL will open terminal in /bin as starting directory

**Comment by iorlov1** [comment]
second pane obviously in this case

**Comment by DHowett-MSFT** [comment]
That's a windows path, dude. It's using the "windows WSL redirector", `\\wsl$`.

**Comment by iorlov1** [comment]
so \\wsl$ redirect is not able to use any windows mounts, this is what you are saying

**Comment by DHowett-MSFT** [comment]
Yes.

>The reason for this is that you can’t even access the Windows paths through wsl$

>The WSL filesystem redirector does not let you access Windows files in /mnt.

**Comment by iorlov1** [comment]
Understood. Thanks for clarification. Didn't know

**Comment by DHowett-MSFT** [comment]
I'm happy to help :smile:
