### ISSUE TITLE
DPI Setting will break the characters should be connected

### ISSUE THREAD

**Issue by kix99aug** [microsoft/terminal#5349]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

0.10.781.0

Any other software?

With oh-my-posh plugin
```

# Steps to reproduce
If set the system DPI to 100%, the character will display in the right way.
But set the system DPI to 125%. there will be a wired line between the characters.

# Expected behavior
![image](https://user-images.githubusercontent.com/10905628/79246179-afabca00-7eab-11ea-8247-b85399d53521.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/10905628/79246115-9efb5400-7eab-11ea-9230-7f1399ff1e71.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3626 for more discussion.

/dup #3626

This was also actually resolved in #5149, and should be fixed in the 0.11 release of the Terminal (coming soon<sup>TM</sup>)
