### ISSUE TITLE
DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.18362.0 or higher. 

### ISSUE THREAD

**Issue by luxiangnk** [microsoft/Terminal#535]
I get an error when I deploy the solution.

"DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.18362.0 or higher. You currently are running version 10.0.17763.475."

I already updated the windows. Does someone else get this problem? Thanks.

**Comment by zadjii-msft** [comment]
https://github.com/microsoft/Terminal#i-tried-running-windowsterminalexe-and-it-crashes

> * Make sure you're on the right version of Windows. You'll need to be on Insider's builds, or wait for the 1903 release, as the Windows Terminal REQUIRES features from the latest Windows release.
