### ISSUE TITLE
Make the "new tab" button prompt what kind of new tab(cmd, ps, etc.) and get rid of the "more options" button.

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5354]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by Chips1234** [comment]
Minimize the steps it takes to open a new tab by putting the options found in the "more options" button into the "new tab" button. For example, I click on "+", the menu prompts me options, then, select option (ex. PowerShell).

**Comment by DHowett-MSFT** [comment]
Sorry, we're not going to do that. For every person who wants the "new tab" button to _be_ the menu, there is bound to be a person who will _hate_ the fact that they have to open a menu every time they just want a new tab.

**Comment by Chips1234** [comment]
Okay.
