### ISSUE TITLE
Add tool tip text to buttons

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5355]
Example: Display "New Tab" when hovering over "+". I know it's minor, but I think it'll be important.

**Comment by Chips1234** [comment]
Example: Display "New Tab" when hovering over "+". I know it's minor, but I think it'll be important.

**Comment by zadjii-msft** [comment]
Wow yea I'm kinda surprised I haven't heard this request already tbh

**Comment by Chips1234** [comment]
How do I find the design tab for the project (in Visual Studio)? I can add tooltips there. I'm sorry if this question seems dumb, but that's because I'm new. Pls, help. Thanks!!

**Comment by DHowett-MSFT** [comment]
You should be able to look at the Design view if you open up one of the Xaml files. If you want to work on the Tab bar and the + button, you should look at `TabRowControl.xaml`.

It might be hard to use this with C++ projects like Terminal. :smile: Sorry

**Comment by Chips1234** [comment]
Okay, thanks for the help!

________________________________

**Comment by Chips1234** [comment]
Sorry, another question: I can't load properties for `Cascadia Package`  saying that project config or `debugx86` was not found in project manifest. Thanks in advance!!

**Comment by DHowett-MSFT** [comment]
Are you on a 32-bit computer?

**Comment by Chips1234** [comment]
No, 64 bit

**Comment by DHowett-MSFT** [comment]
Then don't use the x86 project configuration.

**Comment by Chips1234** [comment]
Ah, I see thanks.
