### ISSUE TITLE
Add Key Binding to open the menu with the keyboard (w/o mouse)

### ISSUE THREAD

**Issue by DrPepperBianco** [microsoft/terminal#5358]
# Description of the new feature/enhancement

Add a command and key binding for opening the menu.

There are many key shortcuts for open new tabs or switching tabs. For some reason there is no shortcut to simply open the menu. Often I don't know what entries are there or in which order (because I don't use it very often). Then open the menu would be very helpful.

# Proposed technical implementation details (optional)

Maybe use "Context Menu" key (the one that usually between right Win key and right Ctrl key). It probably has no use in terminal applications anyway.

**Comment by zadjii-msft** [comment]
There actually already is this keybinding 😉 

https://github.com/microsoft/terminal/blob/37e62dabd5ed6f94f9a8d0ddfbbcfb2363854032/src/cascadia/TerminalApp/defaults.json#L276

Try <kbd>Ctrl+Shift+Space</kbd>

**Comment by DrPepperBianco** [comment]
Well than that should be probably added to the documentation and probably to the settings.json too.

Should I open a new ticket regarding to that?

**Comment by zadjii-msft** [comment]
No need to open another issue, it already is in the documentation:

See [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#implemented-commands-and-actions)

Command | Command Description | Action (*=required) | Action Arguments | Argument Descriptions
-- | -- | -- | -- | --
openNewTabDropdown | Open the dropdown menu. |   |   |  


Also, the whole point of `defaults.json` is that the user doesn't need to put every single keybinding in their `profiles.json`/`settings.json` (as of 0.11) file manually 😄

**Comment by DrPepperBianco** [comment]
Well, thank you very much. I still think that it was hard to find this information in the documentation. Mainly because, I wasn't aware that the documentation has multiple documents, because this is not obvious.

I opened the documentation via link in in the app. Than the wiki page opened. Than I Ctrl+F’ed for several key words, but didn't found anything. Also most other key shortcuts are shown in the app. But this particularly shortcut unfortunately isn't.

Anyway thanks very much for your help.
