### ISSUE TITLE
search

### ISSUE THREAD

**Issue by telmocalhaco** [microsoft/terminal#5359]
Please add a search like the iTerm , thks

**Comment by zadjii-msft** [comment]
_How ironic_, you're asking for a search feature but were unable to use it to search for duplicates 😆 

Press <kbd>ctrl+shift+f</kbd> to open the search dialog

/dup #3299 #3590 #4028 #3920 #5329 #5330 #5314

**Comment by telmocalhaco** [comment]
Yap :) , thanks .

Mike Griese <notifications@github.com> escreveu no dia quarta, 15/04/2020
à(s) 14:43:
