### ISSUE TITLE
New tabs doesn't read environment variables changes

### ISSUE THREAD

**Issue by danielfh7** [microsoft/terminal#5363]
When I open new tabs, is not possible to read the new values of environment variables, in previous versions it was normally functioning.
I have to open a new standar cmd app to execute commands of recently installed apps.

Sorry my english is not very good.

**Comment by zadjii-msft** [comment]
Hey thanks for the report! I'm actually fairly confident this _never_ worked in the Windows Terminal 😄 

We've got #1125 on the backlog to actually add support for this. You can refer to that thread for many more details.

/dup #1125

Thanks!
