### ISSUE TITLE
Schemas

### ISSUE THREAD

**Issue by Youtube-Consolas** [microsoft/terminal#5370]
if i run terminal it say error Line 62, Column 14
  Missing '}' or object member name
![{15F865A1-9999-4862-BC3A-A1B5155E04A9} png](https://user-images.githubusercontent.com/62821670/79403183-212d6a80-7fc9-11ea-88b3-2ee5c6fdbbdf.jpg)
![{EF5DDF5A-A014-4D11-9120-DDAF50295FCB} png](https://user-images.githubusercontent.com/62821670/79403187-22f72e00-7fc9-11ea-89b0-0fd8b0d04f79.jpg)

**Comment by DHowett-MSFT** [comment]
Yeah, that's because that's not how the "schemes" element is supposed to work. Please refer to our [settings documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md).
