### ISSUE TITLE
Can't run terminal (The service has not been started)

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#5371]
Windows 10.0.18363.1909

I just installed WindowsTerminal.  When I try to run it (by any means) I get a message box stating the following.

 c:\program files\...\windowsterminal.exe

The service has not been started

Help!  Thanks!  - Vince

**Comment by DHowett-MSFT** [comment]
That's very curious. Can you share the output of...

```
sc.exe query dcomlaunch
sc.exe query AppXSvc
```

Thanks

**Comment by DHowett-MSFT** [comment]
Interesting. You might want to tune in to #3097; there's a couple suggestions there for getting it up and running. Worst case scenario, you can unzip the msixbundle file (it's just a zip file).

It looks like this one isn't exactly related to the _terminal_, just the app installation machinery... so I unfortunately have to close it out.
