### ISSUE TITLE
New CMD Icon!

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5372]
# Description of the new feature/enhancement

If PowerShell and terminal have a new icon, then good old command prompt should have one! That would comply with Microsoft's new fluent design system!

**Comment by mdtauk** [comment]
Something like this maybe

![image](https://user-images.githubusercontent.com/7389110/79416171-0649fe80-7fa7-11ea-8ac8-195747412ff1.png)

**Comment by DHowett-MSFT** [comment]
Thanks for your enthusiasm! We're not updating CMD, and that includes not updating its visuals. Sorry, we're just not investing in it. Terminal's icon is going to be the icon you see for your commandline going forward, and keeping CMD's legacy as an homage is the best way to honor it.

**Comment by gusbemacbe** [comment]
Hello @mdtauk, please, can you share this icon so we'll set Command Prompt icon as new default at Windows Terminal.
