### ISSUE TITLE
New Cascadia Code font is blurry

### ISSUE THREAD

**Issue by mimi89999** [microsoft/terminal#5376]
# Environment

```
Windows build number: 10.0.19603.1000
Windows Terminal version (if applicable): fe3f52882758812f0f7ae780dfb4987d5cb7d41d
```

# Steps to reproduce

Use a fresh terminal build or change font to `Cascadia Code` in the app from Windows Store

# Expected behavior

The new font should look OK.

# Actual behavior

The new font seems blurry. Please see the attached screenshots. Left side is version from Windows Store, right is fe3f52882758812f0f7ae780dfb4987d5cb7d41d. This issue also affects the version from Windows store if I change the font to `Cascadia Code`. `M`, `W`, `w`, `I` and `"` are the worst.
![Screenshot_win10_2020-04-16_13:23:03](https://user-images.githubusercontent.com/8530546/79451630-1eda0900-7fe7-11ea-9979-ba0305fc5f69.png)
![Screenshot_win10_2020-04-16_13:27:24](https://user-images.githubusercontent.com/8530546/79451633-1f729f80-7fe7-11ea-9cea-5b130c40f49d.png)

**Comment by mimi89999** [comment]
This font also looks strange in _gnome-terminal_. Here are screenshots with `Cascadia Code`, my usual monospace font, `Fira mono` and `Fira code`. Didn't test `Fira` in MS Terminal.

![Capture d’écran du 2020-04-16 16-02-32](https://user-images.githubusercontent.com/8530546/79484301-b81f1480-8013-11ea-9a3b-a4889bbe5dd4.png)
![Capture d’écran du 2020-04-16 16-02-50](https://user-images.githubusercontent.com/8530546/79484303-b9504180-8013-11ea-98d9-22fbd24df944.png)
![Capture d’écran du 2020-04-16 16-07-34](https://user-images.githubusercontent.com/8530546/79484306-b9504180-8013-11ea-8fa7-1a14d26a1f10.png)
![Capture d’écran du 2020-04-16 16-09-19](https://user-images.githubusercontent.com/8530546/79484307-b9e8d800-8013-11ea-96f8-d81719c286c5.png)

**Comment by mimi89999** [comment]
Another screenshot
![Capture d’écran du 2020-04-16 19-18-39](https://user-images.githubusercontent.com/8530546/79486539-21eced80-8017-11ea-8e92-51a645cf9bd8.png)

**Comment by DHowett-MSFT** [comment]
You moved the issue to our other repo, so i'm closing this one.

**Comment by mimi89999** [comment]
OK. Am I the only one to whom that font seems blurry or did you also notice it?
