### ISSUE TITLE
How to make wsl go to $HOME directory

### ISSUE THREAD

**Issue by NOVA-ME** [microsoft/terminal#5377]
When I first use wsl, it go to /mnt/c/Users/NOVA this directory,I dislike that,I want it just go to $HOME directory

**Comment by WSLUser** [comment]
wrong repo. Try https://github.com/MicrosoftDocs/WSL/issues

**Comment by zadjii-msft** [comment]
@WSLUser I don't think so, it sounds like this user is trying to configure their WSL profile to go to `~` by default.  (ps did you mean [microsoft/WSL](https://github.com/Microsoft/WSL/issues)?)

@NOVA-ME try setting your `startingDirectory` to 

```json
"startingDirectory":"\\\\wsl$\\<your distro>\\home\\<your username>"
```

So for my "Ubuntu 18.04" instance, that's 
```json
"startingDirectory":"\\\\wsl$\\Ubuntu-18.04\\home\\zadjii"
```

**Comment by WSLUser** [comment]
Well there's a way to configure it in WSL but it does help we have a profile setting as well. It was filed as docs issue so that's why I chose the WSL docs issue tracker. Should of thought about the use of profile to work around using WSL to change it (this is one of the things that make Terminal great to work with for WSL).

**Comment by NOVA-ME** [comment]
> @WSLUser I don't think so, it sounds like this user is trying to configure their WSL profile to go to `~` by default. (ps did you mean [microsoft/WSL](https://github.com/Microsoft/WSL/issues)?)
> 
> @NOVA-ME try setting your `startingDirectory` to
> 
> ```json
> "startingDirectory":"\\\\wsl$\\<your distro>\\home\\<your username>"
> ```
> 
> So for my "Ubuntu 18.04" instance, that's
> 
> ```json
> "startingDirectory":"\\\\wsl$\\Ubuntu-18.04\\home\\zadjii"
> ```

Yes, thank you so much, my english is poor

**Comment by NOVA-ME** [comment]
> @WSLUser I don't think so, it sounds like this user is trying to configure their WSL profile to go to `~` by default. (ps did you mean [microsoft/WSL](https://github.com/Microsoft/WSL/issues)?)
> 
> @NOVA-ME try setting your `startingDirectory` to
> 
> ```json
> "startingDirectory":"\\\\wsl$\\<your distro>\\home\\<your username>"
> ```
> 
> So for my "Ubuntu 18.04" instance, that's
> 
> ```json
> "startingDirectory":"\\\\wsl$\\Ubuntu-18.04\\home\\zadjii"
> ```

I have another question, how to make the first time open the terminal just go to my ubuntu wsl

**Comment by utybo** [comment]
> I have another question, how to make the first time open the terminal just go to my ubuntu wsl

@NOVA-ME If you mean that you want to launch WSL instead of Powershell when you launch the Windows Terminal, you can do that by changing the value of `defaultProfile` in your configuration file to the WSL profile's `guid`. See [here](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#global-settings) for more info. 😄

**Comment by NOVA-ME** [comment]
> > I have another question, how to make the first time open the terminal just go to my ubuntu wsl
> 
> @NOVA-ME If you mean that you want to launch WSL instead of Powershell when you launch the Windows Terminal, you can do that by changing the value of `defaultProfile` in your configuration file to the WSL profile's `guid`. See [here](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#global-settings) for more info. 😄

Thank you,I got it

**Comment by NOVA-ME** [comment]
![% KZ{(2TQWVS$SN_0%@B89O](https://user-images.githubusercontent.com/18442141/79571595-086aa500-80ee-11ea-9885-035e16ef79cf.png)

It is perfect now.I love it
