### ISSUE TITLE
Command line parameters need adjustments to run in PowerShell

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/terminal#5379]
# Environment

```none
Platform ServicePack Version      VersionString                    
-------- ----------- -------      -------------                    
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal 0.10.78.1.0

Any other software?
```

# Steps to reproduce

I am trying out the command line examples. If I open a CMD window, and run this command

```dos
wt -p "Windows PowerShell No Profile"; split-pane -p "PowerShell 7 No Profile"
```
I get a new Terminal window with my two profiles vertically split.  You can use any two profiles you want. This isn't a profile problem.

# Expected behavior

When I run the same command in Windows PowerShell 5.1 or PowerShell 7 I expect or at least want the same result.

# Actual behavior

Instead, I get the first profile in a new WT instance. When I close it, the next profile opens. PowerShell is treating the `;` as an end of command marker so your example is actually two commands. 

I think the command line option needs to be a single command that allows the user to specify the initial profile plus any additional customization such as split pane.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! We have some documentation changes outstanding in https://github.com/microsoft/terminal/pull/5361 and a lively discussion over in /dup #4570, so I'm gonna redirect discussion over there. Thanks!
