### ISSUE TITLE
Cannot start Windows Terminal through powershell cmdlet

### ISSUE THREAD

**Issue by BSG-75** [microsoft/terminal#5380]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0
Powershell 5.1 / Powershell Core 7
```

# Steps to reproduce

```powershell
start wt -verb runas
# or
Start-Process "C:\Users\[username]\AppData\Local\Microsoft\WindowsApps\wt.exe" -verb runas
```

# Expected behavior

After a UAC confirmation prompt, Windows Terminal should be started under administrator mode.

# Actual behavior

An error is displayed: `This command cannot be run due to the error: The file cannot be accessed by the system.`

**Comment by DHowett-MSFT** [comment]
Sounds like your admin user isn't the same as your normal user. That would be #4217.

**Comment by BSG-75** [comment]
> Sounds like your admin user isn't the same as your normal user. That would be #4217.

I only created one user on this PC (and that's the user I'm using), it's also the administrator user.

**Comment by DHowett-MSFT** [comment]
Interesting. We usually only see this problem when the application is registered for a user that _isn't_ the admin user. Unfortunately, since this is an app platform registration issue, there isn't much we can do about it.

You might be able to `repair` the application in the Application settings.
