### ISSUE TITLE
Gaps between characters in 'mc' when used with 150% display scaling

### ISSUE THREAD

**Issue by agavrilov** [microsoft/terminal#5382]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce

- Set Windows Display scaling to 150%
![image](https://user-images.githubusercontent.com/3209180/79501033-3e226780-7fe2-11ea-8fd0-ca6a1f4d8145.png)

- Open Ubuntu-18.04 terminal
- Install 'mc':
```bash
sudo apt update && sudo apt install mc
```
- Open mc

# Expected behavior

Displays screen without gaps between characters

# Actual behavior

There are gaps between characters:
![image](https://user-images.githubusercontent.com/3209180/79501356-c0129080-7fe2-11ea-8ca2-b222c237b674.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3626 for more discussion.

/dup #3626

This was also actually resolved in #5149, and should be fixed in the 0.11 release of the Terminal (coming soon<sup>TM</sup>)
