### ISSUE TITLE
Blue lines trailing output

### ISSUE THREAD

**Issue by TapeWerm** [microsoft/terminal#5387]
# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.19041.207]
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
Windows 10 2004, WSL 1, Ubuntu 18.04
```

# Steps to reproduce
I updated to Windows 10 2004 (Insider release preview), and in WSL 1 distro Ubuntu 18.04, there were blue lines trailing the last character of almost every line of output. Specifically the blue lines were rectangle characters of blue, about the same shade as the default Windows 10 accent color. Upgrading to WSL 2 fixed this.

# Expected behavior
No lines of blue characters trailing most lines.

# Actual behavior
Wish I had a screenshot, I'm in a hurry so I upgraded to WSL 2 before thinking of making an issue on GitHub. Got to study for a quiz tomorrow. My Surface Pro 1 (backup) is updating right now since my ThinkPad is back to normal after the move to WSL 2. If that also has the same issue I'll add a screenshot.

**Comment by TapeWerm** [comment]
Well my Surface just finished updating and WSL 1 is fine on that, not sure what the difference is. Considering that has 4GB of RAM I think I'll stay on WSL 1 for that potato, will update this issue if it ever crops up again. It happened multiple times until I went WSL 2 on my ThinkPad, not sure what is different. Maybe a dotfile is different.

**Comment by zadjii-msft** [comment]
Okay since there's not really any repro steps for this issue, and the original issue isn't reproing any longer, I'm going to close this. If you can get this to start happening again, we can re-open and investigate. There's just not really anything we can do with this issue at the moment.

Thanks!
