### ISSUE TITLE
DNS problems on WSL with Cisco VPN

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#5391]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.752]
Windows Terminal version (if applicable): Version: 0.10.781.0
```

# Steps to reproduce

Connect to Cisco AnyConnect and try to ping named service on `wsl` and `cmd`
Connect to FortiClient is ok

# Expected behavior
![image](https://user-images.githubusercontent.com/17201690/79552338-8fdef680-80a3-11ea-87e7-d2ef2d60bcfa.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/17201690/79552242-6faf3780-80a3-11ea-8070-56e929c67172.png)

When we shutdown VPN client it will become ok

**Comment by zadjii-msft** [comment]
Does the use of the Terminal change the behavior at all here? I'm going to guess not. I'd think that this issue belongs over at [microsoft/WSL](https://github.com/microsoft/wsl) instead, where they might be able to help debug this.

Just searching "cisco" on that repo I was able to find https://github.com/microsoft/WSL/issues/4698, which already looks pretty similar.

**Comment by lego963** [comment]
Sorry, didn't know about WSL repo. Thanks.
