### ISSUE TITLE
A11y_Windows Terminal_Settings_Non text Contrast: For "Plus(+)" and "Drop down" buttons the non text contrast ratio is not meeting 3:1 ratio

### ISSUE THREAD

**Issue by SpandanaPaladi** [microsoft/terminal#5392]
#A11y_WindowsTerminal; #WindowsTerminal; #A11yWCAG2.1; #A11yTCS; #DesktopApp; #Win10 ; #C+E-H; #NonTextContrast; #A11ySev2; #BenchMark; #MAS1.4.11

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-shcha1%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847087032&sdata=uWx6cTEfazn%2BoCV3cL1iYB4KN%2BuXQ/MTlmOVec%2BZgKc%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier

**Environment Details:**
Version: 0.10.781.0

**Repro steps:**
1. Hit the URL ""aka.ms/terminal"" and install ""Windows terminal (Preview)"" application
2. Open ""Windows terminal (Preview)"" application
3. Open the "Accessibility insights" tool to check color contrast ratio
4. Tab to ""Windows Powershell"" tab 
5. Tab till "plus(+)" button and "Drop down" button
6. Verify whether  the color contrast ratio for "Plus(+)" and "drop down" buttons are meeting 3:1 contrast ratio using the "Accessibility insights" tool

**Actual Result:​**
Both the "Plus(+) and "Drop down" buttons are not meeting the non text  contrast ratio 3:1 ratio
​
**Expected Result:​**
Both the "Plus(+) and "Drop down" buttons should meet the non text  contrast ratio 3:1 ratio
​
**User Impact:​**
Low vision users will face difficulty if the buttons don't meet the non text contrast ratio 3:1
**MAS Reference:​**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7B6CA3BF14-2635-434A-832C-28DD9A18B9FC%7D&file=MAS%201.4.11%20%E2%80%93%20Non-text%20Contrast.docx&action=default&mobileredirect=true&cid=ab731ae2-c015-4cce-8636-dda5170eef34

![Bug_plus button non text contrast](https://user-images.githubusercontent.com/63839131/79557454-346f3180-80c0-11ea-95a9-cdbe2b9696bb.png)
![Bug_drop down non text contrast](https://user-images.githubusercontent.com/63839131/79557481-40f38a00-80c0-11ea-8099-ec8ea47c9d9f.png)

**Comment by carlos-zamora** [comment]
We just use the built-in resources from the WinUI Theme Dictionary. Submitted the following issue on the WinUI repo:
https://github.com/microsoft/microsoft-ui-xaml/issues/2353

**Comment by Amulya-95** [comment]
Regressed in latest environment, still able issue is not fixed. We will take action and close the bug, once the issue gets resolved.

**Attachments:**

![Bug 5392_Dropdown_Non text contrast](https://user-images.githubusercontent.com/51435266/81951074-5954b700-9622-11ea-8aca-bd972cf56bd9.png)

![Bug 5392_Non text contrast issue](https://user-images.githubusercontent.com/51435266/81951092-5f4a9800-9622-11ea-9e19-ce56de379961.png)

**Comment by carlos-zamora** [comment]
@Amulya-95 as I said above, we're just using WinUI's resources here. Can we close this in favor of the attached WinUI issue?

CC @DHowett-MSFT

**Comment by Amulya-95** [comment]
[#1901](https://github.com/microsoft/microsoft-ui-xaml/issues/1901) still in Active (open) state.

As per C & AI external bug process we will take action on this bug once the external bug is fixed and verified

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/148084772-413f254e-5f8b-4b0e-b622-68d7f8422d8a.png)
![image](https://user-images.githubusercontent.com/18356694/148085044-56ed5438-4fb8-4d9c-87d2-f9f86fda31d2.png)

(it can't auto-detect the colors for the split button, so I picked them manually)

I believe this was fixed at some point in the past, likely when we updated a MUX version (unclear which).

I also think we've got a new a11y team now so I'm gonna close this one out.
