### ISSUE TITLE
fontFace settings reset to default after upgrading to 0.11.1072.0

### ISSUE THREAD

**Issue by jackhorton** [microsoft/terminal#5396]
# Environment

```none
Windows build number: 10.0.19608.0
Windows Terminal version (if applicable): 0.11.1072.0

Any other software? Lots, but nothing relevant to this issue
```

# Steps to reproduce

I dont think its a reliable repro, but updating to 0.11.1072.0 through the Microsoft Store on my laptop this morning seems to have been what caused this. I am happy to provide logs if they exist, but I couldnt find any. After this happened, I updated on my desktop (which is on 19H2/non-insider, as opposed to my insider fast laptop) and this _did not_ repro. However, while backing up my settings on my desktop, I noticed that the settings path did change during the upgrade - it went from profiles.json to settings.json transparently. Perhaps there was some data migration going on that was successful on my desktop but not on my laptop?

# Expected behavior

fontFace setting is not reset to default

# Actual behavior

fontFace setting is reset to default. I had only made two modifications to my terminal settings, and the other (the default profile guid) was unimpacted by the update.

**Comment by Batzer** [comment]
I don't think reseting custimizations after upgrading in a prerelease can be considered an issue. It's just what happens when using alpha/beta builds.

**Comment by jackhorton** [comment]
Ah, this was likely caused by https://github.com/microsoft/terminal/pull/5190, and thus probably intentional. With that being said, I dont think its fair to say that you should _expect_ settings to be lost in a beta build -- I am fine with losing settings, but losing them without knowing ahead of time means it might be a bug that needs fixing, hence the issue.
