### ISSUE TITLE
When entering double (special character), the first character renders black

### ISSUE THREAD

**Issue by spoorcrystallogy** [microsoft/terminal#5397]
# Environment

```none
Windows build number: Windows 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
Write almost any special character twice in a row, ie:
```
^^
!!
--
__
;;
::
```

# Expected behavior
Source-specific formatting, default to normal text formatting. See conhost behavior:
![bug_report_terminal_doublechar](https://user-images.githubusercontent.com/62602956/79601852-c8092800-80e9-11ea-937f-97414c0a7300.png)

# Actual behavior
First characters foreground color turns black (in darkmode themes) making it impossible to see. See Terminal screenshot below for comparison:
![image](https://user-images.githubusercontent.com/62602956/79602429-becc8b00-80ea-11ea-8756-3db0b697fbb4.png)
This is in powershell and pwsh, WSL profile does *something* to it but it doesn't change foreground color at least.

Most noticable in powershell when referencing `[dotnet]::` classes

**Comment by zadjii-msft** [comment]
@spoorcrystallogy What font are you using? Display scaling?

**Comment by spoorcrystallogy** [comment]
@zadjii-msft Yup you were right it was the font that messed it up, sorry for non-issue. 
For reference it was FuraCode NF (Fura Code Regular Nerd Font Complete Mono Windows Compatible)
