### ISSUE TITLE
Add a shortcut action for toggling retro terminal effects

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5402]
* [ ] Dependent upon us being able to hot-reload this setting, which is tracked in #3927 

```json
{  "command": "toggleRetroEffects", "keys": [] }
```

I don't really think this needs arguments. Just toggle the setting.

**Comment by KalleOlaviNiemitalo** [comment]
This was already implemented in <https://github.com/microsoft/terminal/pull/6691>, except the name is "toggleRetroEffect" rather than "toggleRetroEffects".

**Comment by zadjii-msft** [comment]
lol you caught me forgetting to tag up my own issue! Thanks!
