### ISSUE TITLE
Found multiple profiles with the same GUID in your settings file

### ISSUE THREAD

**Issue by davelowndes** [microsoft/terminal#5408]
# Environment

Microsoft Windows NT 10.0.18363.0
Windows Terminal Version: 0.10.781.0

# Steps to reproduce
Launch the program

# Expected behavior
No error about non-unique profile guids when all profile guids in settings are unique

# Actual behavior
Error message on launch:
`Found multiple profiles with the same GUID in your settings file - ignoring duplicates. Make sure each profile's GUID is unique.`
![launch_error](https://user-images.githubusercontent.com/327084/79637084-59eb6080-81d0-11ea-8488-6733186f0b4b.PNG)

[profiles.json.txt](https://github.com/microsoft/terminal/files/4496580/profiles.json.txt)

Off-topic, but please fix the default fuzzy text, an awful experience for a first look and to have to go hunting through bug reports and merge requests to find a JSON property to add to your settings to fix is horrible.  Attached my current launch view side by side with a properly rendered PowerShell. "cleartype" setting doesn't seem to have an effect, maybe due to the aforementioned profile error.

![fuzzy_font](https://user-images.githubusercontent.com/327084/79637140-f01f8680-81d0-11ea-8b1a-bcaca6e407ba.PNG)

**Comment by DHowett-MSFT** [comment]
Interesting. The only time we generate multiple profiles is for powershell and WSL ... perhaps you've hit a case where we try to assign two powershells the same name?

Would you mind running the following from powershell? It'll enumerate all the instances of PowerShell Terminal would otherwise look for.

```
Function Find-Pwsh($p) {
    If ($null -ne (Get-Item $p -EA:Ignore)) {
        Get-ChildItem $p -filter pwsh.exe -rec
    }
}

$a=@()
$a+=Find-Pwsh $Env:ProgramFiles\PowerShell
$a+=Find-Pwsh ${Env:ProgramFiles(x86)}\PowerShell
$a+=Find-Pwsh $Env:HOMEPATH\.dotnet
$a+=Find-Pwsh $Env:HOMEPATH\scoop
$a+=Find-Pwsh $Env:LOCALAPPDATA\Microsoft\WindowsApps -r -filter pwsh.exe
$a | Select -expand FullName
```

**Comment by davelowndes** [comment]
Hi, the output from the script is one line:
`C:\Program Files\PowerShell\7-preview\pwsh.exe`

**Comment by DHowett-MSFT** [comment]
_huh, just the one._ And `wsl -l`?

**Comment by davelowndes** [comment]
```
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Ubuntu
```

**Comment by DHowett-MSFT** [comment]
WHOA. Okay, that should be an impossible state to get into! This is great. WSL should not allow the registration of two distributions with the same name.

Can you share the output of...

```
reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss /s
```

**Comment by davelowndes** [comment]
Hmm, I haven't even used WSL that much though I will in the future (actually today). 

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss
    DefaultDistribution    REG_SZ    {aa042764-ff32-4f39-a0dc-5e5fd31910d8}

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{189b95e5-c133-46bd-b0b4-bc385899dabf}
    State    REG_DWORD    0x1
    DistributionName    REG_SZ    Ubuntu
    Version    REG_DWORD    0x1
    BasePath    REG_SZ    C:\Users\dtlow\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState
    Flags    REG_DWORD    0x7
    DefaultUid    REG_DWORD    0x3e8
    PackageFamilyName    REG_SZ    CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
    KernelCommandLine    REG_SZ    BOOT_IMAGE=/kernel init=/init
    DefaultEnvironment    REG_MULTI_SZ    HOSTTYPE=x86_64\0LANG=en_US.UTF-8\0PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games\0TERM=xterm-256color

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{aa042764-ff32-4f39-a0dc-5e5fd31910d8}
    State    REG_DWORD    0x1
    DistributionName    REG_SZ    Ubuntu
    Version    REG_DWORD    0x1
    BasePath    REG_SZ    C:\Users\dtlow\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState
    PackageFamilyName    REG_SZ    CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
    KernelCommandLine    REG_SZ    BOOT_IMAGE=/kernel init=/init ro
    DefaultUid    REG_DWORD    0x3e8
    Flags    REG_DWORD    0x7
    DefaultEnvironment    REG_MULTI_SZ    HOSTTYPE=x86_64\0LANG=en_US.UTF-8\0PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games\0TERM=xterm-256color
```

**Comment by DHowett-MSFT** [comment]
Okay, they look like they're identical. That's really interesting.

I want to say you can safely delete the 189b95e5 one (in regedit), but I've asked one of my peers on WSL to see if they want any more info... :smile:

**Comment by davelowndes** [comment]
`KernelCommandLine` is different. I don't remember doing anything weird, just followed the standard instructions to enable WSL and install Ubuntu from the store. I might've uninstalled and reinstalled to get a different release, or possibly switch from the "Ubuntu 18.04 LTS" version to the "Ubuntu" version. But it was a good 6months ago so can't recall.

**Comment by DHowett-MSFT** [comment]
For this version of WSL, that kernel commandline is actually totally ignored.

If you want a hacky way to work around it:

`reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{189b95e5-c133-46bd-b0b4-bc385899dabf}" /v DistributionName /t REG_SZ /d "Ubuntu (Weird)" /f` (may need to restart after?)

It'll split your two distributions into "Ubuntu" and "Ubuntu (weird)". For now, please don't delete that distribution using the `wsl` tool: the weird one has the same folder as the good one, and you'd nuke both that way.

**Comment by DHowett-MSFT** [comment]
I'm gonna close this one out as external; some other OS component failed us here, and allowed some unusual and inconsistent state. Sorry.

**Comment by henrickgoldwurm** [comment]
I encountered the same issue after the last cumulative update (KB4577671). I still get the popup in Windows Terminal, but your steps fixed all of the breaking problems (Ubuntu/Docker failing on startup), thanks!

> If you want a hacky way to work around it:
> 
> `reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{189b95e5-c133-46bd-b0b4-bc385899dabf}" /v DistributionName /t REG_SZ /d "Ubuntu (Weird)" /f` (may need to restart after?)
> 
> It'll split your two distributions into "Ubuntu" and "Ubuntu (weird)". For now, please don't delete that distribution using the `wsl` tool: the weird one has the same folder as the good one, and you'd nuke both that way.
