### ISSUE TITLE
Capslock + Ctrl rebind to starting Terminal instead of activating "Caps Lock"

### ISSUE THREAD

**Issue by brianherman** [microsoft/terminal#5409]
# Description of the new feature/enhancement

A lot of people don't use or need capslock + Ctrl in their every day lives as developers.
# Proposed technical implementation details (optional)
I tried doing something similar with conemu/sharpkeys but my capslock + Ctrl rebind didn't work. If anyone has a better idea how this is supposed to work it would be you guys. I could try to code something up in javascript/c++ but I don't know where to look. There is a similar issue on vscode.
https://www.reddit.com/r/vscode/comments/85abey/swapping_esc_and_caps_lock_windows_10/
https://github.com/VSCodeVim/Vim/issues/854#issuecomment-303777549

Rebind caps lock key to start Microsoft terminal.
This is a difficult feature request.
I would be willing to help but I don't know where to start.
Thank you for reading this I appreciate this.

**Comment by brianherman** [comment]
I figured how to do it with the following AutoHotKey Script and rebound to Ctrl+Caps Lock

#NoTrayIcon

CapsLock::Escape

**Comment by brianherman** [comment]
https://www.autohotkey.com/

**Comment by DHowett-MSFT** [comment]
Thanks for the request. This isn't something we can fix in the Terminal -- it requires an operating-system level keybinding, and Ctrl+Caps is _hot real-estate_ which we'd never get approval to use.
