### ISSUE TITLE
DisabledProfileSources is not part of the JSON Schema

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/terminal#5410]
# Environment

N/A

# Steps to reproduce

Open Json Schema

# Expected behavior

https://github.com/microsoft/terminal/issues/4513 should be defined as part of the current schema at least as a string property and at best with validation to the available dynamic sources

# Actual behavior
https://raw.githubusercontent.com/microsoft/terminal/v0.10.781.0/doc/cascadia/profiles.schema.json is missing the disabledProfileSources setting

**Comment by JustinGrote** [comment]
This is still present in 0.11. @DHowett-MSFT is this something to resolve prior to 1.0?

**Comment by DHowett-MSFT** [comment]
I don't mean to be persnickety, but this will be in every release made while this bug is still open :wink:

Yeah, we should probably resolve this before 1.0.

**Comment by JustinGrote** [comment]
> "I don't mean to be persnickety, but this will be in every release made while this bug is still open"
Yes I suppose that first sentence was self-expanatory :)
