### ISSUE TITLE
splitPane open same kind of console

### ISSUE THREAD

**Issue by iuricarraro** [microsoft/terminal#5414]
Command splitPane creates new default's console. For example: User is operating Ubuntu console, press key binding os splaitPane and then PowerShell is open. 

My suggest is splitPane creates a new console of same kind of console on focus at the momento of key binding.
This setting should in json.

**Comment by dreadnaut** [comment]
You can already do that adding the argument `"splitMode": "duplicate"` to your split keyboard bindings.

See https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#implemented-commands-and-actions

**Comment by DHowett-MSFT** [comment]
Yep, this is part of version 0.10. Thanks!
