### ISSUE TITLE
Private Mode in Terminal 🧐

### ISSUE THREAD

**Issue by aloamaloa** [microsoft/terminal#5415]
# Description of the new feature/enhancement
Private mode in the terminal as with the browsers? :D

# Proposed technical implementation details (optional)

**Comment by aloamaloa** [comment]
I mean that would be fantastic! 👍 💯

**Comment by DHowett-MSFT** [comment]
You seem to be related to @Qantex, and you therefore must know that he filed an issue for this already. /dup #5378
