### ISSUE TITLE
How to actually run Terminal?

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5416]
# Description
I tried debugging `OpenConsole` in Visual Studio but nothing happened. The executable did not start. Instead, 28 errors popped up (see image below). Thanks in advance!

![OpenConsole Errors](https://user-images.githubusercontent.com/47545798/79698485-162f4000-823e-11ea-9cb5-cc95a4b47c5e.jpg)

**Comment by DHowett-MSFT** [comment]
You've gotta follow the [building instructions in the readme](https://github.com/microsoft/terminal#building-the-code) ...

**Comment by Chips1234** [comment]
I was confused for a long time but I looked at post #489
