### ISSUE TITLE
A11y_Windows Terminal_About_Screen Reader: Narrator/NVDA not reading anything when focus lands on the links when the "About" pop up is opened

### ISSUE THREAD

**Issue by SpandanaPaladi** [microsoft/terminal#5420]
#A11y_WindowsTerminal; #WindowsTerminal; #A11yMAS; #A11yTCS; #DesktopApp; #Win10; #C+E-H; #ScreenReader; #Narrator; #NVDA; #A11ySev2; #NonBenchMark; #MAS1.3.1

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-shcha1%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847087032&sdata=uWx6cTEfazn%2BoCV3cL1iYB4KN%2BuXQ/MTlmOVec%2BZgKc%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier

**Environment Details:**
Version: 0.10.781.0

**Repro steps:**

1. Turn on Narrator/NVDA
2. Hit the URL ""aka.ms/terminal"" and install ""Windows terminal (Preview)"" application
3. Open ""Windows terminal (Preview)"" application
4. Tab to "Dropdown" control and press enter or use "Ctrl + Shift + Space"
5. Tab till "About" and press enter
6. Verify whether the links present in the "About" pop up are read by the screen reader when the focus lands on the links

**Actual Result:**
Narrator/NVDA is not reading anything when the focus lands on the links present in the "About" pop up

**Expected Result:​**
Narrator/NVDA  should read the name of the links when the focus lands on the links in the "About" pop up

**User Impact:​**
Screen Reader users will face difficulty if the links present in the "About" pop up are not read even focus lands on the links because they don't know that there are links present in the pop up

**MAS Reference:​**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

[Bug_Narrator not reading the links in about pop up.pptx](https://github.com/microsoft/terminal/files/4502648/Bug_Narrator.not.reading.the.links.in.about.pop.up.pptx)
[Bug_NVDA not reading the links in about pop up.pptx](https://github.com/microsoft/terminal/files/4502651/Bug_NVDA.not.reading.the.links.in.about.pop.up.pptx)

**Comment by carlos-zamora** [comment]
Verified that this was fixed sometime between 0.10 and 0.11. Tagging appropriately.

**Comment by Amulya-95** [comment]
Regressed the bug in latest environment. The issue resolved, now Narrator/NVDA is reading when focus lands on the links present in the 'About' dialog. Hence closing this bug.
Please find the attachments for reference.

**Attachments:**

[[Fixed]Bug 5420_Screen reader is reading about the links when focus lands on it.pptx](https://github.com/microsoft/terminal/files/4627689/Fixed.Bug.5420_Screen.reader.is.reading.about.the.links.when.focus.lands.on.it.pptx)

![Fixed Bug 5420_NVDA reading about the links](https://user-images.githubusercontent.com/51435266/81924941-6e6b1f00-95fd-11ea-90bc-643a6df2e1a9.png)

**Comment by zadjii-msft** [comment]
> Hence closing this bug.
