### ISSUE TITLE
Nvim resize windows

### ISSUE THREAD

**Issue by pianocomposer321** [microsoft/terminal#5429]
When you restore or resize the window while running Neovim in the terminal, the text gets moved around and the formatting is messed up.

Examples:

![image](https://user-images.githubusercontent.com/54072354/79792449-87412700-8314-11ea-954d-be9e856cbcf1.png)

![image](https://user-images.githubusercontent.com/54072354/79792496-9f18ab00-8314-11ea-8ec3-61382a0dd762.png)

**Comment by zadjii-msft** [comment]
@pianocomposer321 what nvim version is this? 

I'm thinking this might just be #3263

**Comment by pianocomposer321** [comment]
Yes I think you are right.

Thanks for your reply.
