### ISSUE TITLE
Terminal: ANSI Underlines are rendered in the wrong color/not at all

### ISSUE THREAD

**Issue by dhrdlicka** [microsoft/terminal#543]
* **Your Windows build number:  (Type `ver` at a Windows Command Prompt)**
`Microsoft Windows [Version 10.0.18885.1001]`

* **What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)**
When running `colortest-16` in WSL from inside Windows Terminal, underline sequences are rendered in strange colors (if they get rendered at all). Here is a comparison between the Terminal and the classic console:
![Screenshot](https://i.imgur.com/c4xlwHD.png)

* **What's wrong / what should be happening instead:**
The Terminal should render ANSI underlines in the current foreground color.

**Comment by miniksa** [comment]
Yeah I'll get to this.

**Comment by rbeesley** [comment]
I saw this, but doing research on whether I should file a bug or not, I couldn't find anything which defined what the behavior actually should be. In some cases, the color of the underline seems to benefit the visibility. Is there a way to use escape codes to set the color of the underline?

**Comment by zadjii-msft** [comment]
I'm 99% sure that this is in `CustomTextRenderer::_FillRectangle` in the DxRenderer. We think it's a BGR vs RGB problem.

**Comment by zadjii-msft** [comment]
I take that back; I don't know how the DxRenderer draws underlines. They're not coming from `CustomTextRenderer::DrawUnderline`, that's for sure.

**Comment by miniksa** [comment]
It's probably in `PaintBufferGridLines` given that an underline has been traditionally part of the box drawing set.

https://github.com/microsoft/terminal/blob/bd5cae13281401cda50cff29b6dda29b8350cc07/src/renderer/dx/DxRenderer.cpp#L929-L1001
