### ISSUE TITLE
delete typed text after terminal shutdown

### ISSUE THREAD

**Issue by MariaLiama** [microsoft/terminal#5433]
# Description of the new feature/enhancement
like the browsers

# Proposed technical implementation details (optional)
function like firefox or chrome

**Comment by zadjii-msft** [comment]
The Terminal already does this... could you elaborate on why you think we need this? How this experience would be different than the way the terminal behaves currently? Did you hear this suggestion somewhere else?

**Comment by DHowett-MSFT** [comment]
You appear to be affiliated with Qantex, so you must already know that he filed #5378 and #5415.

**Comment by Frnaklin12** [comment]
@MariaLiama What do you mean by that? :///
