### ISSUE TITLE
wt.exe commands open new Window

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [microsoft/terminal#5442]
# Environment

```none
Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): Windows Terminal Version: 0.10.781.0


Any other software?
```

# Steps to reproduce
I type the command `wt split-pane` in powershell-core 7 and a new Window opens with to split panes.

# Expected behavior
The command `wt split-pane` does not open a new window, instead it splits the actual window.

# Actual behavior
A new window with splited panes is opend

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472
