### ISSUE TITLE
Add configuration option to unbind all keys

### ISSUE THREAD

**Issue by fitzgibbon** [microsoft/terminal#5443]
# Description of the new feature/enhancement

The current user experience for conflicts between Windows Terminal bindings and console application bindings is to try something in the console application, notice the keystroke doesn't work as it is intercepted by Windows Terminal, then try to identify the exact combination of modifier keys that Windows Terminal intercepts (not always trivial) and unbind that combination in the configuration.

When using Windows Terminal in an environment such as WSL2 + tmux/emacs the user will almost always want keypresses to be interpreted by the console application rather than Windows Terminal itself.

The user should have a way of unbinding all keys from Windows Terminal without listing them all individually.

# Proposed technical implementation details (optional)

Add a configuration option to remove all key bindings without having to list them individually, leaving only the GUI as a means to interact with Windows Terminal, passing all keystrokes on to the console application.

**Comment by zadjii-msft** [comment]
Largely, this discussion is much of the same of #3318, so I'd rather we unify the discussion in that thread. Thanks!

/dup #3318
