### ISSUE TITLE
Always empty last line when using padding

### ISSUE THREAD

**Issue by vasily-codefresh** [microsoft/terminal#5445]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.10.8710

Any other software? no
```

# Steps to reproduce

1. I have a 1920x1080 screen with display scaling set to 150%
2. I just install and launch the Windows Terminal

# Expected behavior

A good-looking and functional terminal =)

# Actual behavior

1. My last line in the terminal is always empty and doesn't allow to display any text in it, see [screenshot](https://1drv.ms/u/s!AqSdRn_IUsGpgcU2EGeBqx981TYOxA?e=SLnV3U)
2. This reproduces with default settings; `initialRows`, `initialCols`, `initialPosition` and `snapToGridOnResize` have no effect, the empty line is always there
3. This reproduces with any host: PS7, PS5, cmd
4. `padding` set to `8, 0, 8, 0` eliminates this problem, with `8, 1, 8, 1` it's still there

I think it's the bug in rendering as using `padding` (default or non-zero) causes terminal to delete one line and it's not possible to get around this (as `initialRows` is an integer).

In fact, it appears like `padding` doesn't work correctly as it effectively ignores `initialRows` and maybe `initialCols`. What do you expect when setting `initialRows` to `25`, `initialCols` to `80` and `padding` to `2,2,2,2`? I'd expect that I'll have a 80x25 screen with 2px padding on each side.

**Comment by zadjii-msft** [comment]
You might be interested in #2061, or the related PRs #4825 and #5091. This will be fixed in 0.11 ☺️ 

/dup #2061
