### ISSUE TITLE
Issues produced by shrinking window size

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#5450]
[If this is a console issue (a problem with layout, rendering, colors, etc.), please post to the console issue tracker.](https://github.com/microsoft/WSL/issues)

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
```

# Steps to reproduce

1. Opent new WSL window
2. Shrink this window

# Expected behavior

Windows shrinks and content will not change 

# Actual behavior

![image](https://user-images.githubusercontent.com/17201690/79901529-9e693d00-8418-11ea-9981-d687d4842801.png)
![image](https://user-images.githubusercontent.com/17201690/79901550-a6c17800-8418-11ea-8960-6fa0fb085968.png)

**Comment by zadjii-msft** [comment]
I'm pretty sure this is just a variation on #3088

**Comment by lego963** [comment]
If you think so, let it be. :)

**Comment by zadjii-msft** [comment]
I'm gonna resolve this one as a dupe for now. I'll add some context from #5666:

> 
> This seems less like it's something we're doing, but more an artifact of how `bash` handles reprinting it's prompt. Compare `gnome-terminal` with `conhost`:
> 
> ![image](https://user-images.githubusercontent.com/18356694/80713420-0672ef80-8ab9-11ea-8a09-9329a09502df.png)
> 
> As soon as the prompt wraps onto a _third_ line, you `bash` seems to handle unwrapping particularly poorly.


/dup #3088
