### ISSUE TITLE
[Vim] Split window cannot be resized with mouse

### ISSUE THREAD

**Issue by jianbinw** [microsoft/terminal#5454]
# Environment
**Terminal**:
Version: 0.10.781.0
Installed from Windows Store.

**Windows**:

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

**WSL**:
        {
            "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "hidden": false,
            "name": "Ubuntu-18.04",
            "source": "Windows.Terminal.Wsl"
        }

**VIM**:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 21 2020 18:07:44)
This is not a customized vim. Just downloaded the latest version and compiled and installed.
Same vim settings on my Macbook Pro works fine with mouse resizing split window in vim.

# Steps to reproduce

1. Launch the terminal
2. Select to start a tab for the WSL ubuntu 18.04 or automatically start
3. Edit ".vimrc" or other vim settings to enable mouse : "set mouse=a"
4. Enter command "vim <some_file>" to start vim to edit some_file
5. In vim, enter ":sp <another_file>" to split the window and edit another file
6. Use mouse to click on the bar of the splitted window and move. The bar doesn't move with pointer and window is not resized.

# Expected behavior

The bar of splitted window should move with pointer of mouse and the window should be resized accordingly.

# Actual behavior

The bar of splitted window is treated as text when clicked on and cannot be moved.

**Comment by zadjii-msft** [comment]
@jianbinw What version of the Windows Terminal are you using?

**Comment by jianbinw** [comment]
@zadjii-msft Ah sorry about forgetting the most important info. Just updated in the "environment" section and the version is:
Version: 0.10.781.0

**Comment by jianbinw** [comment]
Not sure if this is a problem in Terminal itself as the same function is not working in WSL or WSL2. Probably depends on how Teminal is implemented.

**Comment by zadjii-msft** [comment]
I just tried this in `gnome-terminal` with `vim -u NONE` and this doesn't work, but my usual `.vimrc` actually _does_ work in `gnome-terminal`, but not `conhost` or Windows Terminal. That should narrow this down.

**Comment by DHowett-MSFT** [comment]
Can you share the output of `:set ttymouse` when it's working/not working? Vim supports multiple VT mouse encodings.

**Comment by DHowett-MSFT** [comment]
I just tested the repro, and yeah: when `ttymouse` is the default (`xterm`), i can't resize the split. When `ttymouse` is `sgr` (the all-around best encoding), it works perfectly even in conhost/terminal.

**Comment by DHowett-MSFT** [comment]
Is it possible that the vim installation on macOS is customized to prefer sgr?

**Comment by jianbinw** [comment]
Not working:
![image](https://user-images.githubusercontent.com/46470901/79921288-099d2880-8486-11ea-9666-d0732891c716.png)

Working:
ttymouse=sgr
This is my mac output

**Comment by jianbinw** [comment]
Accroding to vim doc: http://vimdoc.sourceforge.net/htmldoc/options.html#'ttymouse', I changed the ttymouse to xterm2 and it is all working now.

**Comment by DHowett-MSFT** [comment]
Looks like a case of bad vim defaults. Thanks!

**Comment by DHowett-MSFT** [comment]
Just so you know, `xterm2` (and `xterm`) mode cannot address cells on the far right edge of the screen -- if your terminal is wider than 93 characters, you won't be able to click any of the extra ones past 93. You really should prefer sgr: it works in a lot of terminal emulators :smile:

**Comment by grawity** [comment]
> Just so you know, `xterm2` (and `xterm`) mode cannot address cells on the far right edge of the screen -- if your terminal is wider than 93 characters, you won't be able to click any of the extra ones past 93. You really should prefer sgr: it works in a lot of terminal emulators 😄

Thanks, I was looking for this -- but in other terminal emulators (namely PuTTY), as well as in Vim's own docs (`:help 'ttymouse'`), the limit is actually 223 columns. How does WT get its 93-column limit then?

**Comment by DHowett** [comment]
You know what? It looks like we top out at 93 due to a self-imposed limitation. While it looks like X10 mouse tracking mode supports coordinates up to 223, we can't put anything in the input buffer that's >= 0x80 without _wsl_ corrupting it on the way in.

https://github.com/microsoft/terminal/blob/695ebffca1e7d8fbee18755032e60512cef4778e/src/terminal/input/mouseInput.cpp#L403-L408

**Comment by grawity** [comment]
That makes sense. And now I faintly remember some Linux terminal emulator documenting the same issue as well...

Thanks for the information about `ttymouse=sgr`, looks like that's the best option.
