### ISSUE TITLE
Conhost output is invisible when UseDx is set

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#5455]
# Environment

Windows build number: Version 10.0.18362.657
Windows Terminal version (if applicable): Commit f6f0731eae61f24e6777e5cf98aaf7e746f1b2bd

# Steps to reproduce

1. Set the DWORD registry value `HKCU\Console\UseDx` to `1` to enable the DirectX renderer.
2. Build the latest source (or at least commit 79684bf82177dfa52bd1eca84476a2950d765bb9).
3. Start a cmd shell in conhost (the problem isn't exclusive to the cmd shell though).

# Expected behavior

I'd expect to see the copyright message and command prompt.

# Actual behavior

The screen is blank. I can still see the cursor, but any text output is invisible. It's like it's rendering everything in black on black.

This was working for me in commit ffbdfe32ac972ecf76ead140a2ae5bad59cf6f91, but broke after commit 79684bf82177dfa52bd1eca84476a2950d765bb9. It still seems to be broken in the latest commit (f6f0731eae61f24e6777e5cf98aaf7e746f1b2bd).

**Comment by DHowett-MSFT** [comment]
Thanks for filing this one. We quasi-knowingly broke conhost with that PR :/

**Comment by DHowett-MSFT** [comment]
(`UseDx` used to be hidden behind Windows' feature gating infrastructure, so it was only really _incidentally_ available because we stripped that stuff out going open-source. It's not "supported", but we try not to break things like that generally.)

**Comment by j4james** [comment]
I figured it might have been something like that. Not a big deal. Just wanted to make sure you were aware of the issue.
