### ISSUE TITLE
Remove Powershell 5.0 from the dynamic profiles

### ISSUE THREAD

**Issue by edyu** [microsoft/terminal#5459]
# Environment

```none
Windows build number: 10.0.19608.0
Windows Terminal version (if applicable): 0.10

Any other software?
```
I also have powershellcore v7.0 installed as well.

# Steps to reproduce

The profiles.json doesn't have the "dynamically generated" Windows Powershell 5.0 defined anywhere but it keeps on showing up on the menu. I already created one for the PowerShellCore so there is no need to have it being there. Because it's "automatically" generated, there is no way to use profiles.json to make it "hidden."

# Expected behavior

I expect that it's either in the generated profiles.json so I can make it hidden or doesn't even show up in the first place.

# Actual behavior

The Windows PowerShell option is always the last option and there is no way to hide it or remove it.

**Comment by DHowett-MSFT** [comment]
There's a way to hide it; it was in the original profile block that you may have removed. Every profile starts out with a "stub" in the settings file that you can use to customize it or hide it.

If you need to hide the default "Windows PowerShell" profile and you've already deleted that stub, you can re-add it and set `hidden` to true.

```jsonc
            {
                /* Windows PowerShell - hidden */
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": true
            }

```

**Comment by edyu** [comment]
Thank you.
