### ISSUE TITLE
Italics are not rendered for terminal programs such as Neovim

### ISSUE THREAD

**Issue by edyu** [microsoft/terminal#5461]
# Environment

```none
Windows build number: 10.0.19608.0
Windows Terminal version (if applicable): 0.10

Any other software? Neovim and WSL2
```

# Steps to reproduce

I have neovim installed on wsl2 and when I have configured neovim to render italics for comments. However, italics are not rendered when I use neovim when I run it in terminal mode in the windows terminal. I know that it's not a neovim problem because if I run it on alacritty for example, the comments are rendered in italics. I'm running neovim under WSL2 but I don't think it has any effect to this.

# Expected behavior

Italics should render properly on the terminal.

# Actual behavior

Italics are being ignored when rendering and fonts are only rendering in the "regular" style.

**Comment by jdebp** [comment]
One does not need WSL or NeoVIM to reproduce this .  [`Attributes.ps1`](https://github.com/jdebp/terminal-tests/blob/master/PowerShell/Attributes.ps1) will do, and indicates the currently missing SGR support.

**Comment by DHowett-MSFT** [comment]
Yep, we should add support for italic and faint and ~ ~ bold ~ ~ (don't ask, it's complicated).

**Comment by rashil2000** [comment]
Italics is a very important missing feature, I feel. Alacritty supports it (@edyu mentions this). Even ConEmu supports this (and ConEmu is _really_ old). 

Cheers!

**Comment by DHowett** [comment]
Thanks for letting us know. In the future, you can register your support for an issue by using the :+1: button (or the Reactions) button if that button is not available.

**Comment by mowestusa** [comment]
I did +1 this feature request, because I have observed this same behavior with the vim syntax highlighting of markdown. Vim comes out of the box configured to display for markdown files *italics*, **bold**, and ***bold/italics*** which I find very handy when I have large blocks of text written in markdown and I'm doing edits in the terminal. I'm loving using Ubuntu 20.04 in WSL 2 inside of Windows Terminal, but this one feature would be a huge quality of life improvement when you spend hours of your day editing markdown text in the terminal. Thanks for considering this feature, and thanks for the work that developers have already done on Windows Terminal.

**Comment by haininhhoang94** [comment]
since we already fixed/improve the issues, when will the next release include this commit (for either Release and Preview?

**Comment by DHowett** [comment]
The next release will include this commit when the next release comes out.

**Comment by Leandros** [comment]
Is it possible to disable italics, in case my font doesn't support any italics?

**Comment by j4james** [comment]
Not in the terminal, but the application that's requesting the italics may have an option for that. In Neovim I think it's controlled by the color scheme.

**Comment by bryant-the-coder** [comment]
my italics is being cut off at the end of each letter

**Comment by zadjii-msft** [comment]
@bryant-the-coder [Yep, they sure are](https://github.com/microsoft/terminal/issues?q=is%3Aissue+italics+cut+off), see #9381

**Comment by k1ng440** [comment]
Its been 2 years still no fix :(

**Comment by zadjii-msft** [comment]
@k1ng440 Italics support was added nearly two years ago: #8580. What specifically "has no fix"? The "italics get cut off some times" issue? That's tracked over in #9381
