### ISSUE TITLE
Add cursor foreground/background color

### ISSUE THREAD

**Issue by nj-ms** [microsoft/terminal#5469]
# Description of the new feature/enhancement

Unless I'm mistaken, Windows Terminal configuration supports just the `cursorColor` setting, which functions as if I've set both the foreground and background colors to the same color.
Other terminal programs (Alacritty, ..., ?) support configuration of the cursor foreground color and the cursor background color, and/or they respect the foreground color setting and the character shows through the cursor.
For example, I'd like to set the background to black (`#000000`), foreground to white (`#ffffff`), the cursor background to magenta (`#990099`) and the cursor foreground to white (`#ffffff`).
This way, I can still see the character under the cursor.
This is especially annoying, for example, if I'm in a Linux WSL and vim'ing a file.
This modification is also important in relation to #1379.

# Proposed technical implementation details

* Make the current `cursorColor` setting continue to set both foreground and background colors.
* Add a `cursorBackground` setting to set just the background color; should use `cursorColor` by default.
* Add a `cursorForeground` setting to set just the foreground color; should use `foreground` and/or `cursorColor` by default. It might also work to just use the `foreground` color and make the character show through the cursor, with the drawback that it's slightly less configurable.

**Comment by JeunghunKim** [comment]
![Inverse_cursor](https://user-images.githubusercontent.com/18302308/80050618-1a66a080-8551-11ea-9b80-309efd153d8c.png)

Some terminals just inverse foreground/background colors like that picture.

**Comment by DHowett-MSFT** [comment]
Thanks for the well-written feature request! I'm going to move it over as a comment to /dup #1203. We need a good story for this, whether it's inversion or a defined color. I played with making this work properly using "D2D Magic" at one point, and the results weren't horrid.
