### ISSUE TITLE
有哪位老哥可以共享一个编译好的版本出来

### ISSUE THREAD

**Issue by SHALEWOXIEXIE** [microsoft/Terminal#547]
have 
which 
old  brother
can
share 
a
compiled
version
come out

中英对照 散装英语 凑合看吧.

.
.
.
.
.
.
.
.
.
.
.
.

----------------5.8 --11.00更新-------------------
有老哥楼下发了release版本,但是貌似连接没了 不知道为啥。 
我重新贴一下,找不到那位老哥了, 再此感谢

链接: pan.baidu.com/s/1yFgFGUzaIj5bEzv8ZmctsQ 
提取码: 13qp

**Comment by lbbgit** [comment]
WTF，terrible english translating ....

U mean "Can U give me a compiled version ..." ?

**Comment by dukanghui** [comment]
I
cant't
my brother

**Comment by yangqingmang** [comment]
perfect english

**Comment by baight** [comment]
> U



> WTF，terrible english translating ....
> 
> U mean "Can U give me a compiled version ..." ?

Yes, it is.

**Comment by Menggggg** [comment]
> WTF，terrible english translating ....
> 
> U mean "Can U give me a compiled version ..." ?

he mean "releases version" 🤔

**Comment by Menggggg** [comment]
都已经开源了，为什么就不能自己编译呢🤔

**Comment by RyuAsuka** [comment]
> WTF，terrible english translating ....
> 
> U mean "Can U give me a compiled version ..." ?

He means "Does anybody can share a released  version". This is a standard translation, but your translation is also OK.

The original machine translation makes me laugh 😄wwwww

**Comment by ddzy** [comment]
这里
https://github.com/microsoft/Terminal/issues/508#issuecomment-490136581

**Comment by RyuAsuka** [comment]
> 都已经开源了，为什么就不能自己编译呢🤔

编译不了啊 windows要升级到1903，我还在1809

**Comment by TypicalSEE** [comment]
未接触过Windows方面的开发，为了这个专门安装了VS2019，结果还是编译失败，按照Readme.md里面的步骤也是失败……

**Comment by Menggggg** [comment]
> > 都已经开源了，为什么就不能自己编译呢thinking
> 
> 编译不了啊 windows要升级到1903，我还在1809

我也是1809，vs2019也不能编译吗

**Comment by SHALEWOXIEXIE** [comment]
> > > 都已经开源了，为什么就不能自己编译呢thinking
> > 
> > 
> > 编译不了啊 windows要升级到1903，我还在1809
> 
> 我也是1809，vs2019也不能编译吗

md文件里有写  必须1903及以上版本

**Comment by heshuimu** [comment]
Jokes aside, opening an issue for make this kind of request is not a good practice. Please consider using forums or other communication channels.

**Comment by Deathef** [comment]
> > > > 都已经开源了，为什么就不能自己编译呢思考
> > > 
> > > 
> > > 编译不了啊windows要升级到1903，我还在1809
> > 
> > 
> > 我也是1809年，vs2019也不能编译吗
> 
> md文件里有写必须1903及以上版本
升级下系统呗

**Comment by yueyelengguang** [comment]
一半人在研究你说的英语。🤣🤣🤣🤣

**Comment by ZgblKylin** [comment]
Perfect english.

散装英语满分。


I wrote a issue for how to build (#489).

可以按照我写的这个issue #489来编译。



I'm creating a pr to fix the compile errors.

我正在提一个pr修复相关编译错误。

**Comment by yh-git** [comment]
Windows server可以吗？（我有vs2019）

**Comment by shijunti19** [comment]
windows10 版本企业版不发布更新，根本无法用的，正式版都没出来，就宣传，好坑啊

**Comment by jack80342** [comment]
cool translation

**Comment by ghl0903** [comment]
you  english  vary  good!!!

**Comment by hioop** [comment]
old brother 
you are 
six
six
six

**Comment by jack80342** [comment]
old brother 666

**Comment by oahceh** [comment]
我都出去了，想了想，又回来给你点了个赞，就凭你这散装英语。

**Comment by linchengzzz** [comment]
需要 vs2017 把

**Comment by nexteve** [comment]
http://cdn.lr3800.52qdw.cn/Terminal.7z

**Comment by xstnet** [comment]
我就是来凑热闹的.

**Comment by lidelin** [comment]
six
six
six

**Comment by nexteve** [comment]
链接：https://pan.baidu.com/s/1c5CEqCnA4yfb14qZjfqLDw 
提取码：j22l

**Comment by baight** [comment]
你好，我是等等党，我在等六月中应用商店的预览版和年底应用商店的正式版，

**Comment by fengxianqi** [comment]
长夜将至，我从今开始守望，至死方休。 
我将不娶妻，不封地，不生子。 
我将不戴宝冠，不争荣宠。 
我将尽忠职守，生死于斯。 
我是黑暗中的利剑，长城上的守卫， 
抵御寒冷的烈焰，破晓时分的光线，唤醒眠者的号角，守护王国的坚盾。 
我将生命与荣耀献于守夜人，今夜如此，夜夜皆然。 

Night gathers, and now my watch begins. It shall not end until my death. 
I shall take no wife, hold no lands, father no children. 
I shall wear no crowns and win no glory.

**Comment by Develkone** [comment]
> you english vary good!!!

vary?very!

**Comment by suxinren** [comment]
This is an English website，你们这些Chinese能不能尊重一下人家。please speak English , are you ok?

**Comment by taroballs** [comment]
Wait Wait党 Plus One！Plus One! +1 +1  望哪位大佬发链接~

**Comment by mu-yu** [comment]
There is a build version in an issue.Delete after tried 3 minutes because it's hard to use at the moment.（还是 hyper 好用！）

**Comment by SHALEWOXIEXIE** [comment]
> This is an English website，你们这些Chinese能不能尊重一下人家。please speak English , are you ok?

天生自带优越感的吗？你回复的内容里不也用了中文？不会英文就没资格上github了？

**Comment by Alexader** [comment]
大家就是用工地英语开开玩笑，何必当真

**Comment by Robosky** [comment]
> 大家就是用工地英语开开玩笑，何必当真

issue 并不是适合拿来开玩笑的地方 : )

**Comment by hapylestat** [comment]
> Already open source, why can't you compile it yourself?🤔

Well, basically coz Windows is not yet Linux, where all users able to use command line and build applications from the source =))

...just kidding.

**Comment by SHALEWOXIEXIE** [comment]
> > Already open source, why can't you compile it yourself?🤔
> 
> Well, basically coz Windows is not yet Linux, where all users able to use command line and build applications from the source =))
> 
> ...just kidding.

My system version is too low and the compilation is not successful. Other users should have many of the same situations as me.

**Comment by DHowett-MSFT** [comment]
if your system version is too low, you won’t be able to run it anyway ...

________________________________

**Comment by wkgcass** [comment]
you 你
english 英语
real 真
is 是
good 好
ah! 啊！

**Comment by yingjiayu** [comment]
old iron double-click
six six six 
🤔

**Comment by yingjiayu** [comment]
bulk 散装
english 英语

**Comment by StealGuevara** [comment]
哈哈哈，老兄的散装英语牛逼

**Comment by djjbwdhl** [comment]
看了你的散装英语，忍不住给你回一个，哈哈~

**Comment by wustwg** [comment]
> 都已经开源了，为什么就不能自己编译呢

因为在公司上班，vs要钱买，公司不让装也不让装盗版的，所以没办法编译。

**Comment by wustwg** [comment]
old iron, 老铁
six 6
six 6
six 6

**Comment by neverno** [comment]
sorry for the terrible english, BUT i have to say, two three three three three.
anyway, ISSUES is not COMMENTS, not any more, guys.

**Comment by WoodSimple** [comment]
you these big brothers are coming here to gossiping？？？

**Comment by mmabluesky** [comment]
This is an English website，shame on you .

**Comment by mmabluesky** [comment]
This is an English website，shame on you .

**Comment by kasuganosoras** [comment]
好像 Windows 10 1809 不能安装
```
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CFD, 无法满足安装的先决条件。

未指定的错误

注意: 有关其他信息，请在事件日志中查找 [ActivityId] 902b3f9e-0521-0000-3e93-2c902105d501，或使用命令行 Get-AppPackageLo
g -ActivityID 902b3f9e-0521-0000-3e93-2c902105d501

错误: 未能安装应用程序。
```

**Comment by kasuganosoras** [comment]
折腾了两天了都没编译安装成功，还更新了下系统都没用，自闭了

**Comment by simon0628** [comment]
old brother 老哥
you 你
is 是
real 真的
cow 牛
B B

**Comment by longletian** [comment]
> I
> cant't
> my brother
Vs2017 opens, some files are not available

**Comment by clearcodecn** [comment]
vs装起来太麻烦了，各种环境，要用一个编译好的版本。

vs zhuang up is too terrible, every environment, need to use a compiled version.

**Comment by miaobin** [comment]
six six six

**Comment by fghzxm** [comment]
Why isn't this f****** spam thread closed???

**Comment by DHowett-MSFT** [comment]
@fghzxm was it necessary for you to swear at us?

Everyone else: this thread isn’t productive, and I’m going to close and lock it. Sorry!
