### ISSUE TITLE
TSFInputControl alignment is slightly off on High DPI

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#5470]
- [ ] - `TSFInputControl` needs to account for scaling (migrie: ✔️)
    - miniksa 4/20@5:04pm, something's still a little off here cutting off the prev text and being a bit small...
    - DHowett 4/20, seems better after it's been opened and closed once, weirdly, for me

_Originally posted by @miniksa in https://github.com/microsoft/terminal/pull/5345#issuecomment-614127648_

**Comment by miniksa** [comment]
![image](https://user-images.githubusercontent.com/18221333/80260382-a6092b80-863c-11ea-8df5-905b80057b03.png)
It's a little to the left, but I just checked 0.11 (without incremental) and it's like that too.

However, resizing and moving the window cause the IME popup to go out of alignment until the cursor position changes (by deleting something in the edit line)

**Comment by leonMSFT** [comment]
(just a thought, noting it down here) maybe the text box has a slight border thickness and where the ime shows up is actually at the beginning of the text box?
