### ISSUE TITLE
Changes to globals section of settings.json are ignored

### ISSUE THREAD

**Issue by lagbolt** [microsoft/terminal#5473]
# Environment

```none
Windows build number: Version 10.0.18362.778
Windows Terminal version (if applicable):   0.11.1121.0

Any other software?
```

# Steps to reproduce

Immediately after I upgraded to 0.11, I started Terminal, opened the settings.json file and made some changes, including two changes to the globals section, changing the defaultProfile and initialRows.  I saved the settings.json file and restarted Terminal.  The change I made to individual profiles (font size) had taken effect, but not the defaultProfile and initialRows changes.

# Expected behavior

When you start Terminal, the initial pane and number of rows should reflect the changes I made to settings.json.

# Actual behavior

Initial pane and number of rows were unaffected.

**Comment by DHowett-MSFT** [comment]
/dup #5458 Gotta read the release notes for this one, sorry.

**Comment by DHowett-MSFT** [comment]
(Sorry if my replies to issues like this one are terse: we're having a discovery problem, so people aren't finding the issue we pinned to the top of the repo. Trying to get through them quickly, not necessarily curtly.)
