### ISSUE TITLE
settings.json: "defaultProfile" seems to work only at old top-level place

### ISSUE THREAD

**Issue by digitalAssetStore** [microsoft/terminal#5474]
Version: 0.11.1121.0

<b>File: settings.json</b>

"defaultProfile" seems to work only at old top-level place
<pre>
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    <b>"defaultProfile":</b> "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
</pre>

But not at new location
<pre>
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "globals" : 
    {
        "alwaysShowTabs" : true,
        <b>"defaultProfile":</b> "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
</pre>

Greetings

**Comment by DHowett-MSFT** [comment]
Thanks for filing. Please read the release notes.
