### ISSUE TITLE
Question: How I can change the default background color?

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#5475]
Hello,
How I can change the default background color?
I want to change the default background color to white.

![Windows Terminal](https://devblogs.microsoft.com/commandline/wp-content/uploads/sites/33/2020/04/tango-light.png)

**Comment by DHowett-MSFT** [comment]
Dude it looks like your default background color _is_ white already.

![image](https://user-images.githubusercontent.com/14316954/80032524-23e40000-84a0-11ea-86c2-29c38f704953.png)

**Comment by DHowett-MSFT** [comment]
Oh, that's a screenshot of Kayla's terminal. You should consider opening the settings file and setting `background` or making your own `colorScheme`.

**Comment by xmha97** [comment]
I find this screenshot on Twitter.
Now I add `"colorScheme": "One Half Light"` and using light theme.
![Windows Terminal](https://user-images.githubusercontent.com/23485114/80033583-3a22a800-8502-11ea-9626-121e6420f0d1.png)

**Comment by DHowett-MSFT** [comment]
That looks good.
