### ISSUE TITLE
 The new monospaced font

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#548]
Is the new monospace font discussed in the blog hosted here? My impression from the blog was that this content was all hosted in this repo, but I might be wrong.

**Comment by DHowett-MSFT** [comment]
All I can say is:
Watch this space. :)

________________________________

**Comment by be5invis** [comment]
I hope there's an exact-half-em-wide variant for coupling with East Asian scripts.

**Comment by eliheuer** [comment]
It would be fun to watch the development of this font in the open on GitHub. I would be interested in testing early versions if the repo is made public.

**Comment by mittalyashu** [comment]
Did you guys got the name for this font from The Flash - Season 5 villain name **cicada** 🤣 _(just kidding)_.

**Comment by mittalyashu** [comment]
@eliheuer I guess the font is open source, as they have mentioned in the Microsoft build videos https://youtu.be/veqs2WVou9M.

**Comment by mdtauk** [comment]
I imagine it will be open source from the start, but not currently included in the repo.

Font design is a complicated thing, and there is/was a topography team in the Windows XP-Vista time frame.

It may be worked on by an outside foundry, and so not able to be released openly in the same way that the Ubuntu fonts are, or even IBM:s font

**Comment by cinnamon-msft** [comment]
The font will be open sourced within its own repository once we have a more finalized v1 with an approved name 😊

**Comment by eliheuer** [comment]
Awesome, a separate repository will make the font easier to contribute issues to and fork. Will it use the [OFL](https://en.wikipedia.org/wiki/SIL_Open_Font_License)?

**Comment by lhutyra** [comment]
It going to be default font for visual studio? Or it's designed for terminal purpose?

**Comment by musm** [comment]
any news here after the initial release a few days ago?

**Comment by DHowett-MSFT** [comment]
If you are subscribed to this thread, _you will receive updates without even having to ask!_

**Comment by musm** [comment]
hahah ok I will be more patient 😄

**Comment by jnnrz** [comment]
I'm curious, will this font have powerline symbols? they're useful for things like oh-my-posh

**Comment by tsukiRep** [comment]
Looking for this as well~

**Comment by ITSecMedia** [comment]
We are waiting 👍

**Comment by cinnamon-msft** [comment]
Cascadia Code is here! https://github.com/microsoft/cascadia-code
If you'd like to read about it, here's the blog post: https://devblogs.microsoft.com/commandline/cascadia-code/
😊😊😊
