### ISSUE TITLE
Darken or disable the window border

### ISSUE THREAD

**Issue by Tuxie** [microsoft/terminal#5486]
Version 0.11.1121.0 fixed the white border issue but the window still has an ugly light grey border in dark mode. I would like this to be far darker gray or even removed entirely.

![image](https://user-images.githubusercontent.com/218697/80069703-17b07f00-8542-11ea-8530-a71e41638125.png)

It looks much better when the window is unfocused. If it could look like that when focused I would be ok, even though I'd prefer it to be even darker.
![image](https://user-images.githubusercontent.com/218697/80069773-3747a780-8542-11ea-9610-dce144bfda44.png)

**Comment by j4james** [comment]
The border color is just your chosen accent color (assuming you've checked the accent option for _Title bars and window borders_). So if you want it to be darker, you could just choose a darker accent color. I just tried setting mine to be completely black, and while it claims that isn't a supported color, it does make it extremely dark (about twice as dark as the normal unfocused border).

**Comment by Tuxie** [comment]
Ok, unchecking "Title bars and window borders" or chosing black as the accent color makes the terminal look much better, but then the file explorer and other windows are ugly instead. Oh well. Thanks.

**Comment by DHowett-MSFT** [comment]
Thanks for confirming. Sorry -- we're trying to follow your settings as best we can, here. Terminal's going to continue using the accent color when accent color borders are enabled, and not use it when they're not.
