### ISSUE TITLE
Disable the … ligature in Terminal.

### ISSUE THREAD

**Issue by PetterS** [microsoft/terminal#5487]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]  
Windows Terminal version (if applicable): 0.11.1121.0
```

# Steps to reproduce

Type "." repeatedly in WSL

# Actual behavior

A ligature (…) appears when the number of periods is three.

This is not desired because a lot of software prints progress by repeatedly printing "." and this ligature is aesthetically not very pleasing.

**Comment by PetterS** [comment]
A setting to completely disable ligatures would solve the problem.

Even though I think having a "…" ligature make very little sense for fixed-width fonts where we still have to make sure the horizontal space is equal to three "."

**Comment by mdtauk** [comment]
The ligature in the font could be altered to only switch to the proper ellipsis after there are three full stops, followed by a space.

**Comment by PetterS** [comment]
> The ligature in the font could be altered to only switch to the proper ellipsis after there are three full stops, followed by a space.

Yes, that would fix most of the problem. I see no point of having it at all though.

**Comment by zadjii-msft** [comment]
> this ligature is aesthetically not very pleasing.

That's really a "eye of the beholder" kind of thing though, isn't it? You're always free to chose another font that _doesn't_ have that ligature if you want.

Broadly, settings to disable ligatures are being tracked in /dup #759, so we can continue the discussion over in that thread. Thanks!

**Comment by PetterS** [comment]
> That's really a "eye of the beholder" kind of thing though, isn't it? 

Sure, by itself it may be. But when it is part of an animation of "." being printed one at a time, it is a clear visual bug.
