### ISSUE TITLE
ssh pip broen ?

### ISSUE THREAD

**Issue by fengzhao** [microsoft/terminal#5491]
When i use WSL2 and windows terminal to login my remote Linux with ssh , 

the remote connection will disconnect after a wile  if i don't type anything. it's normal 

but the windows terminal will delay to long , and will return pip broken for very long time .

**Comment by JushBJJ** [comment]
Seems more like a WSL2 issue more than the terminal one.

**Comment by zadjii-msft** [comment]
Does this repro _only_ with the Windows Terminal, and not the inbox console? If it repros even with the inbox console, then I'd bet that this belongs over in [microsoft/WSL](https://github.com/microsoft)
