### ISSUE TITLE
backgroundImage no longer works using ms-appdata:///

### ISSUE THREAD

**Issue by brentbordelon** [microsoft/terminal#5496]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.778]
Windows Terminal version (if applicable):0.11.1121.0

Any other software? None
```

# Steps to reproduce

1. Locate and copy the `"backgroundImage:"` setting from a previous (working) version's `profile.json` file, where the value is specified using `ms-appdata:///...`  (my actual value is: `"backgroundImage": "ms-appdata:///roaming/ps2.gif"`
2. Add the copied line from step one to the same relevant profile in `settings.json` on version `0.11.1121.0`
3. Save `settings.json`

# Expected behavior

The background specified in `settings.json` shows on the relevant tab as it does in previous versions supporting backgroundImage.

# Actual behavior

No background is shown on the relevant tab, and no configuration error is shown.

**Comment by DHowett-MSFT** [comment]
?
