### ISSUE TITLE
Specifying a font to be used in profile that does not exist causes the app the crash

### ISSUE THREAD

**Issue by nshanny** [microsoft/terminal#550]
I added a new profile to the profiles.json specifying a font that is not installed on my system.  When attempting to start the profile the app crashes with the following:

> The program '[15980] WindowsTerminal.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

Specifying a font that is installed causes the problem to not occur. 

The profile definition looks like this:

```
    {
      "guid": "{e2f9d7d6-369b-4841-9429-61f5b38474cf}",
      "name": "Bash",
      "colorscheme": "Campbell",
      "historySize": 9001,
      "snapOnInput": true,
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "commandline": "bash.exe",
      "fontFace": "Fira Code",
      "fontSize": 12,
      "acrylicOpacity": 0.5,
      "useAcrylic": false,
      "closeOnExit": true,
      "padding": "0, 0, 0, 0"
    }

```

**Comment by ryzngard** [comment]
Similar to this, specifying a large font name seems to crash as well. I used "Ubuntu Mono derivative Powerline" and it crashes, although the font is installed.

**Comment by DHowett-MSFT** [comment]
That one is #602.
