### ISSUE TITLE
Add Additional Terminal Types

### ISSUE THREAD

**Issue by bcordle** [microsoft/terminal#5500]
-->

Add the ability to combine all types of terminals i.e

1) FTP Client and Console
2) SFTP Client and Console
3) Remote Desktop
4) Standard terminal types  i.e. VT108, 3270, 3278 ...
5) Xrdp
6) Docker
7) x-411
8) X11
9) STDOUT Console
10) VM console
and I believe there are other's but this would be an excellent start.

**Comment by DHowett-MSFT** [comment]
Sorry, I'm confused. Most of the things you listed are other graphical applications or display servers (x11, x410, x-411, xrdp, remote desktop) ... and some of them are physical terminal devices (vt108, 3270) and some of them are just two computer-related terms stuck together ("stdout console"). I'm honestly not sure how Terminal could make any of these better, so I've got to close this issue out.

Plus, there's already an FTP and SFTP client in Windows _and you can use it from windows terminal today._

![image](https://user-images.githubusercontent.com/14316954/80139626-97971300-855b-11ea-8ade-235d12c99735.png)
