### ISSUE TITLE
newTab opens the default profile, does not reuse the currently opened profile

### ISSUE THREAD

**Issue by jiria** [microsoft/terminal#5503]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):  0.11.1121.0
```

# Steps to reproduce

1) Open a new tab with non-default profile.
2) Invoke `newTab` command.
3) New tab with default profile is opened.

# Expected behavior

I believe in the past, in step 3), the new tab would use the profile of the currently opened tab, not the default profile. I prefer that behavior.

# Actual behavior

The new tab uses the default profile.

**Comment by DHowett-MSFT** [comment]
This was never the case. You can duplicate the current tab with <kbd>Ctrl+shift+d</kbd> or whatever you bind the `duplicateTab` action to.

**Comment by jiria** [comment]
Thanks, I can confirm that `duplicateTab` works.
