### ISSUE TITLE
The black background shows errors and is displayed as transparent

### ISSUE THREAD

**Issue by Tomato224** [microsoft/terminal#5504]
The black background shows errors and is displayed as transparent

// running versionr
Windows Terminal Version: 0.11.1121.0

![20200418044407](https://user-images.githubusercontent.com/63882336/80139204-a8d23500-85d8-11ea-853d-e1acc08c57d8.png
![20200424030617](https://user-images.githubusercontent.com/63882336/80139241-b8ea1480-85d8-11ea-84d5-36823970a420.png)
)

// test code, powerShell
Write-Host "test" -Background "Yellow"
Write-Host "test" -Foreground "Black"
Write-Host "test" -Background "Black" // Error transparency

// test code, linuxBash
echo -e "\e[41mtest"
echo -e "\e[30mtest"
echo -e "\e[40mtest" // Error transparency

**Comment by DHowett-MSFT** [comment]
You're looking for #293 and #900.
