### ISSUE TITLE
v0.11.1121.0 Does not allow switching tabs with Alt+1, Alt+2, (etc)

### ISSUE THREAD

**Issue by nabieasaurus** [microsoft/terminal#5511]
# Environment

```none
Microsoft Windows [Version 10.0.19037.1]
Windows Terminal version (if applicable): v0.11.1121.0

Any other software?
```

# Steps to reproduce

Open few tabs and try to switch between tabs using Alt+1, Alt+2, etc

# Expected behavior

Terminal should switch between tabs

# Actual behavior

No tab switch

**Comment by zadjii-msft** [comment]
Thanks for the report!  0.11 introduced some breaking settings changes which is probably causing this issue for you. This is tracked by another issue on our repo - please refer to #5458 for more discussion.

/dup #5458
