### ISSUE TITLE
[Schema] Cursorshape Help has ( ??? ) in possible values

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/terminal#5514]
```json
        "cursorShape": {
          "default": "bar",
          "type": "string",
          "description": "Sets the cursor shape for the profile. Possible values: \"vintage\" ( ??? ), \"bar\" ( ???, default ), \"underscore\" ( ??? ), \"filledBox\" ( ??? ), \"emptyBox\" ( ??? )",
          "enum": [
            "bar",
            "emptyBox",
            "filledBox",
            "underscore",
            "vintage"
          ]
        }
```
The ( ??? ) should not be present in the description. This is not present on any other parameter.

**Comment by DHowett-MSFT** [comment]
what on earth, those were UTF-8 before I left for lunch

**Comment by DHowett-MSFT** [comment]
![5FD432AE-F36B-45E5-8501-BCFFC3C52399](https://user-images.githubusercontent.com/14316954/80156574-1ea6b400-8579-11ea-992d-75dbc5b3b4f2.jpeg)

Here’s what I see.

Here’s what RFC7159 has to say on the matter:

> 8.  String and Character Issues
>
>8.1.  Character Encoding
>
>   JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32. 

This is, so far as I can tell, by design.

**Comment by JustinGrote** [comment]
@DHowett-MSFT  good catch, I was looking at a converted one. Apologies for the wasted time.
