### ISSUE TITLE
Documentation still uses profiles.json and global object

### ISSUE THREAD

**Issue by CookieHCl** [microsoft/terminal#5522]
In line 1 of [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md),  

```
# Profiles.json Documentation
```  
should be fixed to  
```
# Settings.json Documentation
```

In line 49~50 of [UsingJsonSettings.md](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#global-settings),

```
These global properties can exist either in the root json object, or in an
object under a root property `"globals"`.
```  
should be fixed to  
```
These global properties can exist in the root json object.
```

**Comment by zadjii-msft** [comment]
You're not wrong
