### ISSUE TITLE
Feature request: close tabs to the right

### ISSUE THREAD

**Issue by Adam13531** [microsoft/terminal#5524]
# Description of the new feature/enhancement

Hey, I was hoping for a feature in Windows Terminal that I've seen in many browsers and text editors: being able to close all tabs to the right of the current one. Here are some examples:

Sublime:
![image](https://user-images.githubusercontent.com/7192897/32975351-51c31100-cbbb-11e7-93dc-8b205a57f7c9.png)

Firefox:
![image](https://user-images.githubusercontent.com/7192897/32975359-62468d90-cbbb-11e7-91cf-91f4545d4996.png)

Chrome:
![image](https://user-images.githubusercontent.com/7192897/32975366-6fe98650-cbbb-11e7-8735-304c1f35f03a.png)

ConEmu:
![image](https://user-images.githubusercontent.com/7192897/80177901-dd7ec600-85b1-11ea-97d7-5103b24bdf1d.png)

The scenario I have is that I keep long-lived tabs like build processes, servers, etc. in the leftmost positions in my terminal, then I have "temporary" tabs on the right. Every once in a while, I end up with 20+ tabs open, so I want to activate the 6th or 7th one and close all tabs to the right to get rid of all of the clutter.

Even just having a customizable keyboard shortcut would be great, but this is the kind of thing that could live in a context menu eventually (#1912).

P.S. much of this text was copy/pasted from [here](https://github.com/Maximus5/ConEmu/issues/1321).

**Comment by zadjii-msft** [comment]
Okay yea this is a neat idea.

**Comment by DHowett-MSFT** [comment]
Yeah, I love this. Great tag-in for the tab context menu in 1.1+

**Comment by DHowett-MSFT** [comment]
Backlinked from 1912. Thanks!

**Comment by Chips1234** [comment]
How about "Close all except for this tab"?

**Comment by zadjii-msft** [comment]
That certainly fits in well with this request IMO. I really like the Firefox way of doing it:
![image](https://user-images.githubusercontent.com/18356694/87152814-055dfb80-c27c-11ea-8453-9aca75fa4c3b.png)

"Close Tab" is a top level entry, and then I imagine a "Close..." option with nested entries for:
* Close other tabs
* Close tabs to the right
* Close pane
* Close other panes in this tab
