### ISSUE TITLE
Alt+Ctrl not acting like AltGr

### ISSUE THREAD

**Issue by Agazoth** [microsoft/terminal#5526]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):
0.11.1121.0

Any other software?
PowerShell 7.0
PowerShell 7.1, preview 2

Danish keyboard
```

# Steps to reproduce 1
Any combination of (Left)Ctrl+Alt used for getting special characters, that can be retrieved by AltGr has unexpected behavior.
Behavior in Terminal depends on PowerShell version

Ctrl+Alt+0

In all PowerShell versions this returns {

# Expected behavior

}

# Actual behavior

Powershell core: ^]
Windows PowerShell: (nothing)
cmd: ^]

# Steps to reproduce 2
With 2 tabs open

Ctrl+Alt+2

In all PowerShell versions and cmd this returns @

# Expected behavior

@

# Actual behavior

Toggles tabs focus to tab 2

**Comment by DHowett-MSFT** [comment]
This looks like a /dup of #5525
