### ISSUE TITLE
`defaultProfile` setting doesn't work 

### ISSUE THREAD

**Issue by Besedin86** [microsoft/terminal#5527]
After update to version 0.11.1121.0 setting `defaultProfile` doesn't work and always open PowerShell terminal by default.

# Environment

Windows 10 Home Build 19592

# Steps to reproduce

Edit settings.json to use Ubuntu terminal
![image](https://user-images.githubusercontent.com/2121842/80194574-3f2b4880-8623-11ea-9a7a-fc21bbed40c0.png)
![image](https://user-images.githubusercontent.com/2121842/80194636-566a3600-8623-11ea-981b-86f5079dab56.png)

# Actual behavior

After change `defaultProfile` to `Ubuntu terminal` or even `cmd` by default uses PowerShell.

![image](https://user-images.githubusercontent.com/2121842/80195264-3dae5000-8624-11ea-9055-986d534e7933.png)

**Comment by Sukiyakijango** [comment]
same here

**Comment by mdtauk** [comment]
The Settings format has been changed, and there is no longer a specific "globals" section.

**Comment by Besedin86** [comment]
@mdtauk thanks a lot! I moved settings from `globals` section to root and it works as expected.

**Comment by wukann** [comment]
Oh, I read that in CHANGELOG... (´・ω・｀)

https://github.com/microsoft/terminal/releases/tag/v0.11.1121.0
> BREAKING CHANGE We've deleted a lot of legacy settings handling (#5190)
Please see our blog post and our most recent status update for more information.
If you had settings hanging out in the globals dictionary, you'll want to move them out.
Failure to do so will cause us to ignore your default profile, launch mode, etc., etc.

**Comment by zadjii-msft** [comment]
Thanks for the report! 0.11 introduced some breaking settings changes which is probably causing this issue for you. This is tracked by another issue on our repo - please refer to #5458 for more discussion.

/dup #5458
