### ISSUE TITLE
Invalid fontFace parameter defaults terminal font to Cascadia Mono instead Cascadia Code

### ISSUE THREAD

**Issue by alecacco** [microsoft/terminal#5529]
# Environment

```none
Microsoft Windows [Version 10.0.19613.1000] 
Windows Terminal Version: 0.11.1121.0

# Steps to reproduce

Change the terminal "fontFace" setting to an invalid font name, like "fontFace":"IPreferCascadiaMonoButIGetThePoint"

# Expected behavior

Terminal should give back some form of error or set the font to "Cascadia Code", the new default font.

# Actual behavior

Font is actually set to "Cascadia Mono" the old default font.

**Comment by zadjii-msft** [comment]
Wait _what?_

I'm fairly certain that's not what should be happening at all. If you specify an invalid font name, we should be falling back to "Consolas", not "Cascadia Mono"

**Comment by DHowett-MSFT** [comment]
Yeah, our fallback font is Consolas. It's fallback for a reason: sometimes the font subsystem totally gives up on packaged fonts, and we need to choose a sane fallback that will just always always be present on all builds of windows all the time. Sorry, this one's by design.
