### ISSUE TITLE
Issue with several AltGr key combinations

### ISSUE THREAD

**Issue by Alxandr** [microsoft/terminal#5530]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
0.11.200421001-release0.11

Any other software?
```

# Steps to reproduce

Use a Norwegian keyboard layout, and attempt to use `@` (altgr+2), `$` (altgr+4) or `{` (altgr+7), or others in terminal.

# Expected behavior

The keys should show up in the terminal, just like they would in the old windows console host or any code editor.

# Actual behavior

Depending on how many tabs you have open in the terminal, multiple things can happen. If you only have 1 tab open, `@` (altgr+2) and `$` (altgr+4) works. If you have 2 tabs open, `@` stops working and instead goes to the second tab. If you have 4 or more tabs, `$` stops working and goes to the fourth tab. `{` never works as expected and inserts `^[` (which is a really unfortunate escape code) if you have fewer than 7 tabs, and (as would be expected at this point) navigates you to the seventh tab if you have that many.

All of this can be seen in the gif below (note that Carnac also displays the keys pressed as US keyboard layout, so instead of `=` (shift+0) it displays `)`):

![error](https://user-images.githubusercontent.com/112334/80204969-1e1a2600-862a-11ea-9ab1-6550d30dd5f1.gif)

Having altgr+# as a keyboard shortcut by default in any program intended for developers is likely going to break for a large number of users who do not use US keyboard layout, as that is generally where the programming symbols are. All of the following are behind altgr+# on Norwegian keyboards for instance: `@${[]}`.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is a great writeup, but #5525 was filed just before this, so we'll be using that thread to track this issue. I've moved your writeup into that thread as well. 

/dup #5525

**Comment by Alxandr** [comment]
Ah, sorry for posting a duplicate. I only found an older one that had already been resolved with a similar issue.

**Comment by zadjii-msft** [comment]
No problem, they were posted pretty closely together so I can't really fault you for that ☺️
