### ISSUE TITLE
Link directly to settings documentation in settings.json comments

### ISSUE THREAD

**Issue by ezramorris** [microsoft/terminal#5531]
In settings.json, the opening comment states:

> For documentation on these settings, see: https://aka.ms/terminal-documentation

This takes the user to the Terminal documentation index page, they then have to read through that page to find the right link to go to the settings documentation. User experience could be improved by linking directly to [said documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md).

**Comment by ezramorris** [comment]
I note that since the version of settings.json I had (before the "generated by" line appeared), more comments have been added with links throughout the documentation. I still think this line should link to the page referenced.

**Comment by DHowett-MSFT** [comment]
So, this is just something we haven't lit up yet -- when we have individual docs online, those sections will all link to the right place. Thanks for making sur we're honest!
