### ISSUE TITLE
[Terminal v0.11.1121.0] "defaultProfile" section under 'globals' setting isn't working 

### ISSUE THREAD

**Issue by prayagsingh** [microsoft/terminal#5532]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version: 0.11.1121.0
```

# Steps to reproduce
1. Open `settings.json` file ad go to `"defaultProfile"` section present under `"globals"`.
2. set `"defaultProfile": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}"` . `c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40` is the `guid` of `wsl ubuntu 18.04` present under `profiles` section.
3. Now close and open the terminal and still it is opening `powershell terminal` instead of `ubuntu 18.04`. 
4. Windows got updated to `KB4558244` and Terminal to `0.11.1121.0`. Everything was fine before these updates. 

# Expected behavior
If `deafultProfile` is set to `wsl Ubuntu 18.04 guid` then it should open the `ubuntu 18.04` distro(I'm using Ubuntu 18 only) not `Powershell` eveytime.

# Actual behavior
`defaultProfile` is set to `wsl ubuntu 18.04 guid` and it is opening `powershell`.

PFA the screenshots.
![Screenshot (145)](https://user-images.githubusercontent.com/8455114/80212347-f12f3880-8654-11ea-848c-b43bca0b1d42.png)
![Screenshot (146)](https://user-images.githubusercontent.com/8455114/80212360-fa200a00-8654-11ea-8fb3-cb16ce5ac63e.png)
![Screenshot (147)](https://user-images.githubusercontent.com/8455114/80212365-fbe9cd80-8654-11ea-8383-71f0dd37322a.png)

**Comment by mdtauk** [comment]
The Globals section was removed, and the settings format has changed

**Comment by zadjii-msft** [comment]
Thanks for the report! 0.11 introduced some breaking settings changes which is probably causing this issue for you. This is tracked by another issue on our repo - please refer to #5458 for more discussion.

/dup #5458
