### ISSUE TITLE
Change of locale via settings.json is not possible

### ISSUE THREAD

**Issue by heavelock** [microsoft/terminal#5537]
# Environment

```none
Windows Terminal version (if applicable): 0.11.1121.0
```

# Expected behavior

Having a possibility of selecting locale via settings.json.

# Actual behavior

Apparently it's not possible to change locale? At least settings schemas do not show possibility (https://github.com/microsoft/terminal/tree/master/doc/cascadia). I tried setting "locale" or "language" or "lang" to "en-EN" without any effect.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5497 for more discussion.

/dup #5497
