### ISSUE TITLE
Symbols with error, when updated the windows terminal

### ISSUE THREAD

**Issue by alexandreserradev** [microsoft/terminal#5538]
In a previous version it was working, however when it updated it stopped working.
![Anotação 2020-04-24 111332](https://user-images.githubusercontent.com/38169175/80228505-1f912180-861d-11ea-9bba-de8a074d6640.png)

**Comment by zadjii-msft** [comment]
Could you share what those glyphs are _supposed_ to be?

**Comment by alexandreserradev** [comment]
@zadjii-msft 
![Anotação 2020-04-24 124917](https://user-images.githubusercontent.com/38169175/80237103-25d9ca80-862a-11ea-98d1-b11b922ac72e.png)

**Comment by DHowett-MSFT** [comment]
Apart from the small emoji (#900), it looks like these are working fine.

![image](https://user-images.githubusercontent.com/14316954/80265886-05236c00-864e-11ea-8091-9e27a5ad41f6.png)

Can you make sure your MSYS profile specifies `bash.exe --login -i` or something equivalent? We've had a bunch of issues with that lately.

Resolving external since this seems to work outside msys/vue.

**Comment by alexandreserradev** [comment]
The settings are the same as the documentation
https://github.com/microsoft/terminal/blob/master/doc/user-docs/ThirdPartyToolProfiles.md

`{
    "name" : "Git Bash",
    "commandline" : "C:/Program Files/Git/bin/bash.exe -li",
    "icon" : "C:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
    "startingDirectory" : "%USERPROFILE%"
}`

I did the tests on other terminals (CMD, Cmder and Power Shell) and had the same problem.

**Comment by DHowett-MSFT** [comment]
All the applications depicted above are using the legacy input line. I'd be interested in seeing emoji _output_ under those three shells.

**Comment by alexandreserradev** [comment]
In cmder, when I insert the emoji it appears normal, but when I remove selection the emoji disappears 

![terminal2](https://user-images.githubusercontent.com/38169175/81245490-1c197500-8fe3-11ea-90e7-93f68d9d533c.png)
