### ISSUE TITLE
Feature request: Disable double hyphens system 

### ISSUE THREAD

**Issue by Caceresenzo** [microsoft/terminal#5539]
# Description of the new feature/enhancement

Double hyphens are not liked by everyone.
It should have a way to disable them.

A really simple exemple is the 'NOT EQUAL TO', when you type '!=' it will appear as '≠'.

**Comment by Caceresenzo** [comment]
A fix can be to restore the old 'Consolas' font.

```json
{
	"profiles":
	{
		"defaults":
		{
			"fontFace": "Consolas"
		}
	}
}
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Largely, this is a /dupe of #759. Before 1.0 lands, we'll also be switching the default font to "Cascadia Mono", which has ligatures disabled, instead of "Cascadia Code" (which has ligatures). For more info, see #5505
