### ISSUE TITLE
What do references to the 17763 SDK in project files have to do with the building requirement of a 18362 SDK?

### ISSUE THREAD

**Issue by fghzxm** [microsoft/terminal#554]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`10.0.18362.86`

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
```cmd
:: commit d5b8e7c32f7a419a7d467eab038251ee529056e6
> grep -r . -I -Fwe 17763
./build/scripts/Create-AppxBundle.ps1:    $MakeAppxPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\MakeAppx.exe"
./packages/Microsoft.UI.Xaml.2.1.190405001-prerelease/build/Microsoft.UI.Xaml.targets:        Text="Microsoft.UI.Xaml nuget package requires TargetPlatformVersion &gt;= 10.0.17763.0 (current project is $(MicrosoftUIXamlTargetPlatformCheckValue))"
./packages/Microsoft.UI.Xaml.2.1.190405001-prerelease/build/Microsoft.UI.Xaml.targets:        Condition="$(MicrosoftUIXamlTargetPlatformCheckValue) &lt; 17763" />
./pkg/appx/OpenConsolePackage.wapproj:    <TargetPlatformVersion>10.0.17763.0</TargetPlatformVersion>
./samples/ConPTY/EchoCon/EchoCon/EchoCon.vcxproj:    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
./src/cascadia/CascadiaPackage/CascadiaPackage.wapproj:    <TargetPlatformVersion>10.0.17763.0</TargetPlatformVersion>
./src/cascadia/CascadiaPackage/CascadiaPackage.wapproj:    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
./src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj:    <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
./src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj:    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
./src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj:    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
./src/common.build.pre.props:    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
./src/cppwinrt.build.pre.props:    <!-- 17763 is RS5 -->
./src/cppwinrt.build.pre.props:    <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0.17763.0</WindowsTargetPlatformVersion>
./src/cppwinrt.build.pre.props:    <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
./src/tools/vtpipeterm/VtPipeTerm.vcxproj:    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
```

* What's wrong / what should be happening instead:
What do those references to the 17763 SDK in the project files have to do with the building requirement of a 18362 SDK?

**Comment by fghzxm** [comment]
Contrasting to the grep above, searching for the string "18362":
```cmd
> grep -r . -I -Fwe 18362
./README.md:* You must be running Windows 1903 (build >= 10.0.18362.0) or above in order to run Windows Terminal
./README.md:* You must have the [1903 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) (build 10.0.18362.0) installed
./src/cascadia/CascadiaPackage/Package.appxmanifest:    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.18362.0" MaxVersionTested="10.0.18362.0" />
```
This is confusing.  I guess this repo can actually be built with the 17763 SDK, since it has been referring to 17763 all along whilst being able to build?

**Comment by hapylestat** [comment]
@fghzxm yes, you could build Terminal with 17763 SDK, tested it. But no chance to run it on same run-time version.

**Comment by fghzxm** [comment]
@hapylestat Have you tried building with 17763 and running on 18362 (which is my configuration)?

**Comment by Biswa96** [comment]
I build it with SDK 18362. You have to retarget the OpenConsole solution to that SDK version and toolset. Open the solution file in VS and right click on the solution icon, click retarget solution. Otherwise just `sed -i '/s/17763/18362/g` it.

**Comment by Biswa96** [comment]
I build it with SDK 18362. You have to retarget the OpenConsole solution to that SDK version and toolset. Open the solution file in VS and right click on the solution icon, click retarget solution. Otherwise just `sed -i '/s/17763/18362/g'` it.

**Comment by fghzxm** [comment]
@hapylestat I can build it with 17763 and run it on 18362.  I'm yet to do some further testing but everything seems fine now.

**Comment by zadjii-msft** [comment]
That might just be an artifact of our dev process that never got updated. IIRC we were using the 17763 SDK for a while, but since the package required 18362 to run, we switched to that SDK, yet clearly didn't get all the references updated.

**Comment by DHowett-MSFT** [comment]
You know, I think we changed this with #1012.
