### ISSUE TITLE
Scroll Sometimes Stops Before Reaching Bottom of Terminal

### ISSUE THREAD

**Issue by vfrazao-ns1** [microsoft/terminal#5540]
# Environment

```
$ [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```
wsl 1
ubuntu 18.04

Windows Terminal
Version: 0.11.1121.0

# Steps to reproduce

Cannot reliably reproduce, the bug occurs when I scroll up to read past output in the terminal, then try to scroll back down to the current line. 

# Expected behavior
I am able to reliably scroll down to the current line in the terminal

# Actual behavior
The terminal sometimes locks the scrolling before reaching the bottom of the terminal -- you are unable to scroll down to the current line in the terminal. The scroll bar on the right hand side of the app _looks_ like its reached the bottom of its scrolling capacity.

To fix this I type `ctrl+c` which brings me back down to the current line.

I hate to report an issue that I cannot reliably reproduce, but this has inadvertently happened twice since upgrading Windows Terminal versions yesterday.

**Comment by DHowett-MSFT** [comment]
I'm actually seeing this, too, and I can't figure out how to reproduce it reliably.

**Comment by DHowett-MSFT** [comment]
Tagging into 1.0 tentatively -- this is pretty bad when it's happening, but easy to get out of. We'll probably move it on Monday, but this is so we have the discussion :smile:

**Comment by IamAIQ** [comment]
有意思的是
