### ISSUE TITLE
guid problem with defaultProblem message when opening Terminal after update to 0.11.1121.0

### ISSUE THREAD

**Issue by 0ric1** [microsoft/terminal#5547]
After updating to version 0.11.1121.0 I get the following error message after opening the terminal:
![20200424_WindowsTerminalUpdateTo_0 11 1121 0](https://user-images.githubusercontent.com/309430/80249217-b982b980-8671-11ea-8d6a-4cb22e55f11d.PNG)
It complains that the guid of the defaultProfile is not found in the profiles.
The guid of the defaultProfile is 574e775e-4f2a-5b96-ac1e-a2962a402336 and I have exactly one profile with this guid and it's PowerShell 7.
I remove the line "defaultProfile" : "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
and closed and reopen the terminal and the same message occurs.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! Can you share a copy of your `settings.json` file?

**Comment by DHowett-MSFT** [comment]
If your `defaultProfile` is inside the `globals`, section, you're hitting #5458

**Comment by 0ric1** [comment]
> If your `defaultProfile` is inside the `globals`, section, you're hitting #5458

Yes, I have this configuration, I will change it and see if it solves it.

**Comment by 0ric1** [comment]
Solved, thank you very much for the fast help.
