### ISSUE TITLE
Sub-menus (groups) for profiles

### ISSUE THREAD

**Issue by 0ric1** [microsoft/terminal#5548]
I have a lot of profiles in the list that exceed the screen high so that I always have to scroll up/down the profiles list. It would be a better usability if it would be possible to group the profiles, e.g.:
- Powershell
- Ubuntu
  - Ubuntu 16.04
  - Ubuntu 18.04
- cmd
  - Administrator
  - Normal User
...

Thanks.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
