### ISSUE TITLE
Command new-tab opens a tab in a new window

### ISSUE THREAD

**Issue by thiagodp** [microsoft/terminal#5553]
Command `new-tab` is supposed to open a **tab** in the **current** window

# Environment

```none
Windows build number: 10.0.18362.719
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce

`wt new-tab -d .`

# Expected behavior

Open a new tab in the _current_ window.

# Actual behavior

It opens a tab in a _new_ window.

![image](https://user-images.githubusercontent.com/2997844/80263762-16797200-8668-11ea-884c-4417e5a76ba4.png)

# Additional suggestions

* Create the command `new-window` to open a new window.

**Comment by DHowett-MSFT** [comment]
/dup #5447 which is a complaint that we don't yet have #4472.
