### ISSUE TITLE
Old key binding stop working and my type in been changed.

### ISSUE THREAD

**Issue by hardwaysun** [microsoft/terminal#5555]
Microsoft Windows [Version 10.0.18363.778]

Terminal Version Version: 0.11.1121.0

Any other software?
No, issue is from Terminal

# Steps to reproduce
My setting

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "copyOnSelect": true,
    "defaultProfile": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        },
        {
            "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "hidden": false,
            "name": "Ubuntu-18.04",
            "historySize": 9999,
            "source": "Windows.Terminal.Wsl"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": 
    [
         { "command": "switchToTab0", "keys": ["alt+1"] },
         { "command": "switchToTab1", "keys": ["alt+2"] },
         { "command": "switchToTab2", "keys": ["alt+3"] },
         { "command": "switchToTab3", "keys": ["alt+4"] },
         { "command": "switchToTab4", "keys": ["alt+5"] },
         { "command": "switchToTab5", "keys": ["alt+6"] },
         { "command": "switchToTab6", "keys": ["alt+7"] },
         { "command": "switchToTab7", "keys": ["alt+8"] },
         { "command": "switchToTab8", "keys": ["alt+9"] },
         { "command": "switchToTab9", "keys": ["alt+0"] },
         { "command": "increaseFontSize", "keys": ["ctrl+="] },
         { "command": "decreaseFontSize", "keys": ["ctrl+-"] },
         { "command": "splitPane", "keys": ["alt+/"] },
         { "command": "moveFocusLeft", "keys": ["alt+s"] },
         { "command": "moveFocusRight", "keys": ["alt+f"] },
         { "command": "moveFocusUp", "keys": ["alt+e"] },
         { "command": "moveFocusDown", "keys": ["alt+d"] },
         { "command": "toggleFullscreen", "keys": ["alt+w"] },
         { "command": "copy", "keys": ["alt+c"] },
         { "command": "paste", "keys": ["alt+v"] }
    ]
}

![image](https://user-images.githubusercontent.com/28275753/80268659-14121a80-865e-11ea-9daa-475354ace4e7.png)

Also my Alt+number to switch tab not working anymore like if I type Alt+1 it shows (arg: 1) instead of switch tab.
# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
Thanks for the report! This is covered in /dup #5458

**Comment by hardwaysun** [comment]
While yes and no, yes after delete my settings.json and let system recreate it, fix the alt+number binding, that switchTab issue solved. 

But the issue of can't type in != like the below picture discribed, I still didn't find answer

![image](https://user-images.githubusercontent.com/28275753/80271315-0bc4da00-8674-11ea-992a-6ce847f1ef7b.png)

**Comment by hardwaysun** [comment]
Ok, sorry, find the issue it is the cascadia-code , strange default

**Comment by DHowett-MSFT** [comment]
We just changed it to "Cascadia Mono" so the `!=` will look correct in the next update.
