### ISSUE TITLE
Windows Terminal blocks user input after a tab is removed

### ISSUE THREAD

**Issue by AVDAX** [microsoft/terminal#5559]
# Environment

```none
Windows build number: 10.0.18363.815
Windows Terminal version (if applicable): 0.11.1121.0

Any other software?
```

# Steps to reproduce

- Start Windows Terminal
- Open a new Windows PowerShell tab
- Now drag the tab to a location without releasing the tab
- Now close the tab with this key combination **Ctrl + Shift + W**
- Now try to make an input in the command line on the first tab, or try a key combination.

# Expected behavior

- Windows PowerShell should allow input.
- Windows Terminal should allow keyboard input after trying to create a new tab with the key combination **Ctrl + Shift + T**.

# Actual behavior

- Windows PowerShell does not allow input.
- Windows Terminal does not allow keyboard input after you try to create a new tab with the key combination **Ctrl + Shift + T**.
---
![ezgif-7-9b0200dbcf4a](https://user-images.githubusercontent.com/47790579/81594415-23fd5e80-93c1-11ea-8346-d448fed6f31e.gif)

**Comment by Sandra2001** [comment]
All right, I'd say that's a bug. **😲🤯**
### Not even Ctrl + Shift + T works

A well found error @Qantex

**Comment by Sandra2001** [comment]
@Qantex Why are you always ### busy??

**Comment by Sandra2001** [comment]
👍

**Comment by Qantex** [comment]
Hello **@Sandra200**1,
I am **very focused on learning**. It sometimes happens that I answer a question later.

**Comment by DHowett-MSFT** [comment]
If you click inside the terminal, does it start responding again?

Do you see the Windows “this program is not responding” message?

**Comment by Qantex** [comment]
@DHowett No, this message "this program is not responding" is not displayed.

**Comment by Qantex** [comment]
@DHowett The application reacts first when a new tab is created by clicking the "+" button. 
The application also **does not react to key combinations** as described above.

**Comment by zadjii-msft** [comment]
_huh_

**Comment by IamAIQ** [comment]
有意思的是

**Comment by DHowett-MSFT** [comment]
@IamAIQ please stop posting the same comment on all of our issues. If you would like to subscribe, please click the "Subscribe" button. If you would like to add your support, please click the ":+1:" button.

**Comment by zadjii-msft** [comment]
This might have gotten better with #5799/#5809 - if it didn't, then this will certainly be a similar class of issue.

**Comment by DHowett-MSFT** [comment]
Almost certainly. Thanks for investigating!

**Comment by AVDAX** [comment]
@DHowett-MSFT I have added a **GIF** to better understand the problem.

**Comment by DHowett-MSFT** [comment]
Thanks.

**Comment by AVDAX** [comment]
@DHowett-MSFT You're welcome. :)

**Comment by EugeneLockett** [comment]
Now, do I know who found this problem. DHowett
Thanks for the help
