### ISSUE TITLE
Add all available options to --help 

### ISSUE THREAD

**Issue by Meyhem** [microsoft/terminal#5560]
```none
Windows build number: irrelevant
Windows Terminal version (if applicable): 0.11.1121.0
```

The "-h" CLI option doesn't provide information about all WT's options, 
ex: _--startingDirectory, -d is missing from there._

It would also be nicer if the "help" would be printed to __stdout__ instead of popping __MessageBox__ which is annoying and does not allow copying.

# Steps to reproduce
1. Open any terminal (wt, cmd, PS...)
2. execute "wt -h"

# Expected behavior
WT help should display all available CLI options

# Actual behavior
WT doesn't display all available CLI options

**Comment by DHowett-MSFT** [comment]
So, each subcommands has context-specific options. Try `wt new-tab -h`!

**Comment by DHowett-MSFT** [comment]
As for the message box, that’s probably the issue that makes us most sad: 
https://github.com/microsoft/terminal/issues/4570#issuecomment-586551445

Section “displaying an output in a dialog”

**Comment by Meyhem** [comment]
@DHowett-MSFT Oh, I haven't realized one of the subcommands is ran by default and has the opts. Thanks for explaining.

**Comment by DHowett-MSFT** [comment]
Sure thing!
