### ISSUE TITLE
No properties in rightclick menu when pinnen to taskbar.

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/terminal#5561]
This bug tracker is monitored by Windows Terminal development team and other technical folks.

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.
Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

If this is an application crash, please also provide a Feedback Hub submission link so we can find your diagnostic data on the backend. Use the category "Apps > Windows Terminal (Preview)" and choose "Share My Feedback" after submission to get the link.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible.

-->

# Environment

```none
Win32NT             10.0.18362.0           home
```

# Steps to reproduce .

Pin the app to the start menu.
Richt click the app. 
right click it again in the menu that just opened.
 
# Expected behavior
There is a properties tab.

![image](https://user-images.githubusercontent.com/13624265/80274886-0a2ffc00-86de-11ea-8398-7fe2590b9d57.png)

# Actual behavior

There is no properties tab.

![image](https://user-images.githubusercontent.com/13624265/80274862-d6ed6d00-86dd-11ea-9e61-e107eecb048e.png)

**Comment by DHowett-MSFT** [comment]
Because this is a store application, there will not be a Properties link. If you create a new shortcut on your desktop, or elsewhere on your start menu, you can access its Properties.

**Comment by NicTanghe** [comment]
Wel thats pretty fucking retarded.
sure there's a good reasen for it tho.
gues i'm never using the store again tho.

**Comment by DHowett-MSFT** [comment]
@NicTanghe When you're contributing to this repository -- even when you're just writing comments -- please make sure you're following our [code of conduct](https://opensource.microsoft.com/codeofconduct/). Thanks!

**Comment by david-poindexter** [comment]
@DHowett I just stumbled on this issue.  I am a bit confused and looking for clarity.  A very common need, for developers especially, is to always `Run as Administrator`.  Likewise, it is very common to need to do that via an app that is pinned to the taskbar.  I personally do not use shortcuts on your desktop (perhaps traumatized by past performance hits for doing so).  So do you know of any way to always force Windows Terminal to `Run as Administrator`?  Thanks in advance for your help!

**Comment by david-poindexter** [comment]
Oh, and I just tried to create a shortcut, but that did not work due to denied permissions to access the `~\Program Files\WindowsApps` directory.  😦

**Comment by byamagata** [comment]
@DHowett-MSFT Anything more on this?  We have a need here and it would be nice to pin to taskbar and always run as administrator.  It's a huge pain clicking on it instinctively, then having to close and reopen because unlike any other app on my taskbar, it is not modified to run as admin always.
