### ISSUE TITLE
JetBrains Mono Ligatures not working

### ISSUE THREAD

**Issue by OmegaRogue** [microsoft/terminal#5563]
# Environment

```none
Microsoft Windows [Version 10.0.19041.208]
```

# Steps to reproduce

1. Install [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono)

2. Add the line
```json
"fontFace" : "JetBrains Mono Regular"
```
to a profile or the profile defaults in settings.json

# Expected behavior

JetBrains Mono works with ligatures

# Actual behavior

Ligatures aren't working

**Comment by OmegaRogue** [comment]
Was a mistake on my part, removing the `Regular` fixed it

**Comment by stackgik** [comment]
still not working

**Comment by lhecker** [comment]
@stackgik Try using Windows Terminal Preview v1.18. (And please write more information when reporting issues in the future. 🙂)

**Comment by stackgik** [comment]
i use Linux

**Comment by stackgik** [comment]
![JSON-settings](https://github.com/microsoft/terminal/assets/120647217/b42c1ac0-0cf6-417a-a4c8-d90c3eb20805)
this the settings i currently have @lhecker  and Ligature is still not working

**Comment by lhecker** [comment]
If you have an issue with Windows Terminal (= not macOS, not VS Code) you can report your issue here: https://github.com/microsoft/terminal/issues/new/choose
If you have an issue with VS Code on macOS you can report it here: https://github.com/microsoft/vscode/issues/new/choose

**Comment by Navid-Rahman-Fahim** [comment]
> ![JSON-settings](https://github.com/microsoft/terminal/assets/120647217/b42c1ac0-0cf6-417a-a4c8-d90c3eb20805) this the settings i currently have [@lhecker](https://github.com/lhecker) and Ligature is still not working
Hi try this. This worked for me. I was also having ligature issue
![Image](https://github.com/user-attachments/assets/f7e0e90e-7b7a-4835-b663-093622935a76)
