### ISSUE TITLE
No color info at link location for color info in settings.json

### ISSUE THREAD

**Issue by nbgibson** [microsoft/terminal#5568]
Line ~64 of the settings.json includes the text:"    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes"

This link routes to https://github.com/microsoft/terminal/blob/master/doc/user-docs/index.md which is a good source of knowledge, but doesn't actually contain any info on color schemes. 

Recommended solutions: 

- Update user docs to include info regarding color schemes 
and/or
- Point the link at https://github.com/mbadolato/iTerm2-Color-Schemes#windows-terminal-color-schemes as that's the go to source for terminal color schemes.

**Comment by DHowett-MSFT** [comment]
Thanks for the report. We inserted these links with the intention of pointing them to the live documentation with the 1.0 release -- please pardon our dust!
