### ISSUE TITLE
Three dots replaced with unicode character

### ISSUE THREAD

**Issue by vlovich** [microsoft/terminal#5569]
# Environment

Microsoft Windows [Version 10.0.18363.657]
WSL1 Ubuntu 20.04

# Steps to reproduce
Type three dots `...` into terminal. Observe they get replaced by Unicode version `…`. Spacing is off (especially noticeable in code viewed in vi). Similarly `!=` is replaced by a single Unicode `≠` even though cursor underneath is really treating it as two separate ascii characters.

# Expected behavior

Really don't expect this, especially for monospace code.

# Actual behavior

Automatic character substitution with Unicode "equivalents" that makes it hard to see what the spacing in code actually is.

**Comment by DHowett-MSFT** [comment]
It's actually just a ligature, and in PR #5505 we switched to the non-ligature version of the default font. This will be out soon.

**Comment by DHowett-MSFT** [comment]
(Ligatures only change the visual representation of the data, not the actual data.)

**Comment by vlovich** [comment]
Is there anything I can change in settings? Just changing the font doesn't seem to work.

**Comment by DHowett-MSFT** [comment]
Sure! If you set your font to Consolas or Cascadia Mono (which you can install from [the cascadia repository](https://github.com/microsoft/cascadia-code/releases)) it will turn off the ligatures.

**Comment by vlovich** [comment]
Ahh. The missing part was getting the font setting it into the right spot. I had it outside the profiles list. Needed to put `"fontFace": "Consolas"` into my WSL profile. Thanks a lot for the help!
