### ISSUE TITLE
Illegal command parameter handling issue

### ISSUE THREAD

**Issue by yangshuairocks** [microsoft/terminal#5575]
# Environment

Windows:
```none
Platform      : Win32NT
Version       : 10.0.19035.0
VersionString : Microsoft Windows NT 10.0.19035.0
```

Windows Terminal version (if applicable):
```none
Version: 0.10.781.0
```

# Steps to reproduce
Run command `mkdir "A TCP/HTTP Load Balancer"` in a PowerShell session and a cmd session.
<img src="https://i.imgur.com/BqPhNVe.gif" />

# Expected behavior
It should report that the character `/` is invalid and stop the command.

# Actual behavior
Two nested folders were created:
- .\A TCP
- .\A TCP\HTTP Load Balancer

**Comment by DHowett-MSFT** [comment]
Uh, it’s not invalid. You’re complaining about a powershell feature—if you’d like it changed, please go to the powershell repository.

**Comment by yangshuairocks** [comment]
Is this a PowerShell feature? As you can see, this behavior also happens in the cmd window.

**Comment by DHowett-MSFT** [comment]
I mean, it’s more of a _Windows_ gesture. Many many parts of Windows support the `/` directory separator!
