### ISSUE TITLE
drop-down terminal window with hotkey

### ISSUE THREAD

**Issue by Peterinor** [microsoft/terminal#5576]
it's a very nice to make terminal window roll down/up from the top of screen with hotkey like Yakuake(https://kde.org/applications/system/org.kde.yakuake)

**Comment by skyline75489** [comment]
Pretty sure this is #653

**Comment by zadjii-msft** [comment]
Yep this is definitely a /duplicate of #653. Thanks for helping with the triage @skyline75489 ☺️
