### ISSUE TITLE
small scripts to convert xshell color scheme to windows terminal 

### ISSUE THREAD

**Issue by sfn101** [microsoft/terminal#5577]
I create small scripts to convert  xshell color scheme syntax to windows terminal 
it is in HTML and javascript - (I know it can be done better I just start learning programming for a weak) -
it will help people customize the Terminal 

xshell is being around for a long time so there is a lot of color scheme for it and even online tool to create colors for it
https://github.com/sfn101/xshell-to-Wterminal-color-scheme

you need xshell color scheme code like this 

 ```[terminal.sexy]
text=c5c8c6
text(bold)=c5c8c6
background=1d1f21
black=282a2e
black(bold)=373b41
red=a54242
red(bold)=cc6666
green=8c9440
green(bold)=b5bd68
yellow=de935f
yellow(bold)=f0c674
blue=5f819d
blue(bold)=81a2be
magenta=85678f
magenta(bold)=b294bb
cyan=5e8d87
cyan(bold)=8abeb7
white=707880
white(bold)=c5c8c6
[Names]
name0=terminal.sexy
count=1```

and it will give you code like 

```,{
"name": "Your theme name",
"black": "#282a2e",
"red": "#a54242",
"green": "#8c9440",
"yellow": "#de935f",
"blue": "#5f819d",
"purple": "#85678f",
"cyan": "#5e8d87",
"white": "#707880",
"brightBlack": "#373b41",
"brightRed": "#cc6666",
"brightGreen": "#b5bd68",
"brightYellow": "#f0c674",
"brightBlue": "#81a2be",
"brightPurple": "#b294bb",
"brightCyan": "#8abeb7",
"brightWhite": "#c5c8c6",
"background": "#1d1f21",
"foreground": "#c5c8c6"
}```

I hope it will help some one

**Comment by DHowett-MSFT** [comment]
Thanks! I'm going to keep this issue in our repo, but close it -- it'll be easily searchable if anybody needs it.

If you're familiar with C#, I'd welcome you contributing an xshell converter to "ColorTool", our "swiss army knife" of color palette management.
