### ISSUE TITLE
Terminal defaults to powershell ignoring settings

### ISSUE THREAD

**Issue by simmessa** [microsoft/terminal#5578]
# Environment

```none
Win32NT             10.0.19592.0 Microsoft Windows NT 10.0.19592.0
Windows Terminal version (if applicable):
Version: 0.11.1121.0
```

# Steps to reproduce

Just open Windows Terminal, and the starting shell is powershell, regardless of "defaultProfile" setting in global (settings.json).

I don't really know of any other things that might trigger this.

# Expected behavior

Windows Terminal should just honor my settings and open Ubuntu as default profile (the guid is specified in defaultProfile).

# Actual behavior

A powershell prompt is started

![image](https://user-images.githubusercontent.com/1277216/80307419-47bd8380-87c9-11ea-8d04-9f8850d1d1f0.png)

**Comment by simmessa** [comment]
Ok, I just had a look at the release notes and realized it's supposed to work this way...

https://github.com/microsoft/terminal/releases

```
BREAKING CHANGE We've deleted a lot of legacy settings handling (#5190)
Please see our blog post and our most recent status update for more information.
If you had settings hanging out in the globals dictionary, you'll want to move them out.
Failure to do so will cause us to ignore your default profile, launch mode, etc., etc.
```
But let me say, since pretty much all of us have this on autoupdate from the Windows store, this very far from the best user experience, especially for people who have been part of the alpha since the beginning (yours truly).

Suddenly the app updates, you might not even realize it and... boom, part of your settings aren't used anymore and you head to github to file for a nasty bug...

I'd suggest doing SOMETHING to notify users of this **BREAKING** change, otherwise this makes me feel pretty stupid...

For example? Open a window on the first launch showing the DAMN release notes... that might be a nice approach IMHO. It's very similar to what's used in... let me think of a modern example... uhm have you heard about the little app called _VsCode_ ?

Sorry for the sarcasm, I love your work and would love even more if you paid more attention to this kind of things.

Thank you for your time and patience.

S.

**Comment by simmessa** [comment]
Hopefully this non-existent issue can help other ppl by pointing to the release notes:

https://github.com/microsoft/terminal/releases/tag/v0.11.1121.0

## The Problem

```
“Globals” namespace
The Terminal no longer supports the globals property in the JSON file. If you have settings inside the globals object, they will be ignored. To fix this, remove the globals object and move your global settings into the root of the JSON file.
```
more infos here:
https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-11-release/

![image](https://user-images.githubusercontent.com/1277216/80307687-e1d1fb80-87ca-11ea-8662-0fe05bf3cf8f.png)

## The Fix

Discard globals and move them to the json root:

![image](https://user-images.githubusercontent.com/1277216/80307715-22317980-87cb-11ea-9fd7-e4aeca23cfde.png)

After that it's good. Have fun!

**Comment by Flyour** [comment]
good job. Solved my problem.

**Comment by DHowett-MSFT** [comment]
Hey @simmessa 

> especially for people who have been part of the alpha since the beginning (yours truly).

Thanks for being with us so long. I appreciate that this has been a terrible obnoxious and sudden change for everyone, and I’m really sorry about the communication—or lack thereof—here. One of the things that we’re hoping to roll out after we launch 1.0 is some sort of update notification with release notes (#5513, colorfully-titled by our community). We ended up batching all the breaking changes up until the end of the preview cycle, but I’d like to assure you that post-v1 settings changes will be accompanied with migrators, notifications or just good old-fashioned backwards compatibility.

**Comment by simmessa** [comment]
Hi Dustin, 

sure, no problem, please forgive my rant, it's nice to know you're working on #5513. That kind of functionality will surely make things much smoother for all of us!

Again, you've done some outstanding job and now that V1 is here I can't wait to put my CLI hands on it :)

**Comment by crazyshot** [comment]
@simmessa I think that, in addition to showing the message, they could have just migrated it automatically

**Comment by simmessa** [comment]
@crazyshot yes that would have been ideal but...guess they also had a lot of better /more useful things to do :D
