### ISSUE TITLE
Split Pane with same Profile

### ISSUE THREAD

**Issue by aykborstelmann** [microsoft/terminal#5579]
# Description of the new mini-feature
For what I know it is only possible to split the pane with the default profile or with a selected profile, e.g. always the 2nd profile. I would like to suggest an option to define a shortcut for splitting the pane with the same profile as the profile currently opened. This would come handy because the is the functionality I expected in the first place.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is such a good idea that _we already implemented it_ 😆 

You can achieve what your looking for with a keybinding like the following:
```json
        { "command": { "action": "splitPane", "split":"auto", "splitMode": "duplicate" }, "keys": [ "ctrl+alt+t" ] },
```

`"splitMode": "duplicate"` tells the keybinding to create a pane with the same profile as the current pane.

`"split":"auto"` tells the binding to create a pane in whichever direction results in the pane being _larger_. If the Terminal is currently wider than it is tall, then the split will be vertical (think "[ | ]").

/dup #1756

**Comment by aykborstelmann** [comment]
Okay sorry for bothering you 🥴. I've should have looked deeper for it but didn't find it in the `default.json`. But cool to have it and thank you for your work ✌️
