### ISSUE TITLE
multiple startup issues

### ISSUE THREAD

**Issue by perlmaster** [microsoft/terminal#5581]
recently the version of Windows Terminal was updated on my system and after that update there are now several issues at startup.

1) the initial window that is opened upon startup does not have the correct size. In the global values section of the settings I have specified 120 columns and 40 rows. It opens up with smaller values for both those dimensions.

2) the program that is run in the initial window is the powershell. However the "defaultprofile" indicates that CMD.EXE should be run

According to the "About" command I am running version 0.11.1121.0

My system is a windows 10 64 bit laptop.

**Comment by tadmccorkle** [comment]
I am getting the same issue. Same version. Settings file points to an msys2 profile, but powershell opens on start-up. I can still launch different profiles, but the default is incorrect.

**Comment by tadmccorkle** [comment]
looks like there's a [pinned issue that fixes this problem](https://github.com/microsoft/terminal/issues/5458). Just move your settings out of the global dictionary. Or...
> Or even better, make a backup of your settings file, and delete the contents entirely. We'll re-generate the file with some better formatting and more sane defaults, and you can copy the modifications you want back in.

**Comment by perlmaster** [comment]
that seems to have fixed the issues.   thanks.....

**Comment by DHowett-MSFT** [comment]
Looks like this discussion has run its course, thanks! /dup #5458
