### ISSUE TITLE
Tab Animation Delay

### ISSUE THREAD

**Issue by zroncarij** [microsoft/terminal#5583]
When you open up a new tab there is a delay on the animation before it opens.

**Comment by DHowett-MSFT** [comment]
I'm not seeing this. Can you capture it with a screen recorder? Tabs open instantly for me on 0.11.

**Comment by zroncarij** [comment]
Well now it works. When I tested this before the speed was very slow, but that was likely an issue with my PC. So sorry!

**Comment by DHowett-MSFT** [comment]
That's no problem! I'm always on the lookout for ways we can make the Terminal experience better. Thanks for getting back to me.
