### ISSUE TITLE
Opacity not working

### ISSUE THREAD

**Issue by jorduino** [microsoft/terminal#5586]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.11.1121.0

Any other software?
```

# Steps to reproduce
change useAcrylic to true and acrylicOpacity to 0.5

# Expected behavior
terminal becomes transparent

# Actual behavior
terminal stays opaque

**Comment by jorduino** [comment]
Transparency wasn't enabled in windows settings. Enabling this fixed the issue.

**Comment by jinfagang** [comment]
@jorduino  how to enable tranparency?
