### ISSUE TITLE
Mouse no longer works

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#5587]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.11.1121.0
```

# Steps to reproduce
No idea, it suddenly just happened an hour or 2 ago. I've tried all of Terminate/Repair/Reset the app, but that didn't help. Since I can't access the menu, I don't know where the logs are, so if there's anything I can do to help reproduce, just ask.

# Expected behavior
The mouse works: I can use it to open/close tabs, to close the Terminal window, click the arrow and access settings, ...

# Actual behavior
Only the keyboard works.

![demo](https://user-images.githubusercontent.com/15714253/80350714-6ecf9000-8871-11ea-8cce-147e2860cbd5.gif)

**Comment by DHowett-MSFT** [comment]
Do you have PowerToys installed/

**Comment by anthonyvdotbe** [comment]
Yes, and that's it: exiting PowerToys makes everything work again. Thanks!
Not sure who's at fault here: I can't readily find an issue neither here nor in the PowerToys issues.

**Comment by anthonyvdotbe** [comment]
Ah, my bad, this is a duplicate of https://github.com/microsoft/terminal/issues/3325
