### ISSUE TITLE
Add configuration for whether selection remains or clears on copy

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#5588]
Selection disappears after copy (on latest release):

If I remember well, this is behavior of cmd.exe and is not how Gnome Terminal / wsltty / Notepad /  any Windows app works. If you work in multiple tabs and copy things in several rounds. It is quite useful to see what was copied / where selection was previously.

Given that https://github.com/microsoft/terminal/issues/4477 is fixed, it is now trivial to discard selection when one does not want it. So keeping selection even after copy now is practical.

After selection, before copy:
![image](https://user-images.githubusercontent.com/1041752/80354342-e522c100-8876-11ea-8c00-ef579b0a283c.png)

After copy (Ctrl+Shift+C):
![image](https://user-images.githubusercontent.com/1041752/80354386-f66bcd80-8876-11ea-9ca6-15bfb8a976a0.png)

Now if I switched windows / tabs / did some other clipboard manipulations, I no longer have a way to remember / recall what I already copied last time from this lovely Python disclaimer.

**Comment by DHowett-MSFT** [comment]
Marked up as a p3 task for terminal backlog. Thanks!

**Comment by carlos-zamora** [comment]
After scanning most of our repo, I think this is actually a /dup of #3884. Linking and updating that one. Refer to that one for updates and discussion.
