### ISSUE TITLE
Type '=' changes command prompt, in stead of showing  'C:\>='

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#5594]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.815]
Windows Terminal version (if applicable): 0.11.1121.0

Any other software?
```

# Steps to reproduce

Type the equal sign '='.

# Expected behavior

The command promt (C:\>) should be show followed by the equal sign ('=') as (C:\>=)

# Actual behavior

The last two character a join into an 'greater-or-equal-sign'   ('≥')

**Comment by Luuk34** [comment]
![goe](https://user-images.githubusercontent.com/7850737/80389837-e8846f80-88ab-11ea-8059-1532478f0fa1.gif)

**Comment by zadjii-msft** [comment]
This is indeed how ligatures work.

/dup #514 #725
