### ISSUE TITLE
Could you make terminal console tab to under?

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#5596]
Could you make terminal console tab to under?
like my picture.
If i many time used terminal with Labtop, my neck is hurt.  

![Screen Shot 2020-04-28 at 2 28 58 AM](https://user-images.githubusercontent.com/23658192/80402235-96b60680-88f8-11ea-9306-c6e20259d8da.png)

**Comment by DHowett-MSFT** [comment]
I think this is a request for "can I put the tab bar at the bottom of the screen".

/dup #835
