### ISSUE TITLE
Misspelled "PowerShell" in defaults.json and settings.json files

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#5600]
Could PowerShell be properly capitalized in the defaults.json and settings.json file by GA release? 

"Campbell Powershell" should be "Campbell PowerShell"

 "Windows.Terminal.PowershellCore" should be "Windows.Terminal.PowerShellCore"

Actually, "Core" is now gone. In 0.11 Terminal team even removed 7 and is using just "PowerShell", so source should be "Windows.Terminal.PowerShell".

# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version:
Version: 0.11.1121.0
```

# Steps to reproduce

Open auto-generated defaults.json and settings.json files.
# Expected behavior

"name": "Campbell PowerShell"
 "source": "Windows.Terminal.PowerShell"
# Actual behavior

"name": "Campbell Powershell"
 "source": "Windows.Terminal.PowershellCore"

**Comment by IamAIQ** [comment]
有意思的是

**Comment by DHowett-MSFT** [comment]
Thanks for the report! Unfortunately, the `source` value is a contract between the user settings and Terminal, and it was created back when Core was part of powershell's name. It's not negotiable now that we've shipped it.

As for the color scheme name, I reckon we could fix it -- that color scheme is also deprecated, and only intended to be used by the inbuilt Windows PowerShell profile.

I don't disagree that these are _wrong_, but I'm going to mark this one as Won't fix. It's not worth the compatibility issue we'll probably cause with our future selves 😦

**Comment by alexandair** [comment]
Windows Terminal is not shipped. It's still in preview. You broke my profiles.json in 0.11, and you haven't heard me complaining about that. Because it's a preview release. And I expect breaking changes. Not fixing wrong capitalization bugs before GA is just sloppy. Sorry.

**Comment by DHowett-MSFT** [comment]
If it were just you and just your opinion, I’d be sold on it, you know? But the number of duplicates on #5458 and the sheer volume of dissatisfaction _even though we’re in preview_ has made us more than a little shy about making further breaking changes.. especially mere weeks before we do final signoffs. I’m happy to fix the scheme name, but the generator may just have to stay. Sorry.
