### ISSUE TITLE
After Migration all shortcuts are working, but Creating new tabs from profile 1 etc. shortcuts isn't

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#5602]
After Migration all shortcuts are working, but Creating new tabs from profile 1 etc. shortcuts isn't.
I placed this line which I got through Devblogs.microsoft.com - https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-11-release/

But it is not working.
        { "command": { "action": "newTab", "index": 1 }, "keys": "ctrl+shift+NUMBER" },

I had earlier shortcuts in my settings to create tabs from CTRL+SHIFT+1 and so on.
Please help

**Comment by jiveshwar** [comment]
![image](https://user-images.githubusercontent.com/7592502/80433571-ec001100-8914-11ea-865b-a2dc8e05a620.png)

**Comment by DHowett-MSFT** [comment]
It looks like you are _not_ using the syntax you included in your own initial comment...

`"command": {"action": "newTab", "index": 0} ...`

**Comment by DHowett-MSFT** [comment]
Didn't mean to close. Sorry!

**Comment by jiveshwar** [comment]
This was my previous lines.

**Comment by jiveshwar** [comment]
These were my previous lines.

**Comment by DHowett-MSFT** [comment]
And is there some way you can share your _current_ lines? That's somewhat important for us to help you.

**Comment by DHowett-MSFT** [comment]
You need one shortcut, with a different `NUMBER`, for every index.

Or, you can just delete them -- ctrl+shift+### is the _default_ shortcut for those actions.

**Comment by jiveshwar** [comment]
Great. this seems working now.
Also, how can I set the default opener index after I press ALT+SHIFT+PLUS.
It is opening initial index only.

**Comment by DHowett-MSFT** [comment]
You can add an "index" to the `splitPane` key binding just like you can to the `newTab` binding. You can make your own `splitPane` with an `index` or even a `profile` (so you can use its name.)

Like this:

```
{ "command": { "action": "splitPane", "profile": "PowerShell" } ... }
```

**Comment by IamAIQ** [comment]
有意思的是
