### ISSUE TITLE
Splitpane not accepting the Profile or index values

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#5603]
Added these in keybindings settings but seems not working.
I want to open certain index or profile guid (in new splitted window) right after I hit ALT+SHIFT+PLUS

        {"command": { "action": "splitPane", "profile": "Ubuntu-18.04" }},
        {"command": { "action": "splitPane", "profile": "{1c3d14aj-67c1-s0s8-siog9-e0ghidf79}" }},
        {"command": { "action": "splitPane", "index": 2 }},

All the above keybindings are not working. Only default 0 index is opening on splitting.

**Comment by IamAIQ** [comment]
有意思的是

**Comment by DHowett-MSFT** [comment]
My dude you have to actually set _keys_. They're key bindings. You have to bind them to keys. Look at the key bindings guide in our Documentation, or any of the key bindings in the Default settings file, for more information.
