### ISSUE TITLE
Equal sign is incorrectly combined with the previous greater-than sign

### ISSUE THREAD

**Issue by kaiidams** [microsoft/terminal#5605]
# Environment

```none
Windows build number:  10.0.18363.815
Windows Terminal version (if applicable):  0.11.1121.0
Language: Japanese

Any other software?
```

# Steps to reproduce

- Launch the app with cmd or another shell
- Type `>=`. You can try other possible ones like `>=>` or `>>`.

# Expected behavior

- `>=` should be rendered. 

# Actual behavior

- `≥` is rendered.

**Comment by kaiidams** [comment]
![image](https://user-images.githubusercontent.com/34785393/80443859-2dabae80-894b-11ea-8998-4b6017d720e8.png)

**Comment by DHowett-MSFT** [comment]
This is a ligature. You can switch your `fontFace` to a font that does not have ligatures.
