### ISSUE TITLE
Terminal closes on startup due to "specified command or file was not found" in Powershell

### ISSUE THREAD

**Issue by izackp** [microsoft/terminal#5606]
![WindowsTerminal_2020-04-27_23-44-14](https://user-images.githubusercontent.com/2636382/80444976-1f28ad00-88e1-11ea-8284-d313865393e3.png)
# Environment
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
I can find no startup scripts for powershell

# Steps to reproduce
Open Windows Terminal

# Expected behavior
See Terminal and a powershell tab

# Actual behavior
Powershell reports an error, returns 0, then instantly closes the entire app. It shows the error:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-C:\Users\Isaac does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I think its because there is a space in my windows username. However, I have no idea why powershell is trying to execute a command on start up in the first place. Everything seems to start up fine when I open powershell outside of windows terminal. I'm not really sure how to further diagnose this issue. It took a while just to figure out how to keep windows terminal from closing (running wt.exe with bad parameters let me run it and keep it from closing).

Either way, powershell instantly shutting down the app is a bad user experience.

**Comment by DHowett-MSFT** [comment]
Wow, there's so many errors bundled up into one bug report!

* I presume you have powershell installed as a dotnet global tool?
   * if so: we need to file a bug on that wrapper for returning _0_ during a catastrophic failure
* Is this the powershell profile as-generated by Terminal? If you open Settings, does it say `source: ...PowershellCore`?

**Comment by DHowett-MSFT** [comment]
And per chance if you actually run _the dotnet global tool version_ of powershell directly, does it fail in the standard console host?

`%USERPROFILE%\.dotnet\tools\pwsh.exe`

Judging by [this commit](https://github.com/PowerShell/PowerShell/commit/42b599dc664a5f588e833f8591282fc4ed861943#diff-608b5e99fec56a95d8c0661b9709dd36), it's the powershell tool wrapper that couldn't handle spaces up until after August 2019. If you have an old wrapper . . . there isn't anything Terminal can do for you.

**Comment by DHowett-MSFT** [comment]
(https://github.com/PowerShell/PowerShell/issues/10184)

**Comment by izackp** [comment]
> I presume you have powershell installed as a dotnet global tool? 
Yea

> Is this the powershell profile as-generated by Terminal? If you open Settings, does it say source: ...PowershellCore?
Yea from what I can recall; I already resolved my issue before checking this out. I've also resetted the app data 2 or 3 times when I was experiencing the issue.

>And per chance if you actually run the dotnet global tool version of powershell directly, does it fail in the standard console host?
Yea, I tried it and it also failed in the standard console host.

I ended up installing PowerShell 7, and uninstalled the powershell dotnet global tool. One of which (or both) fixed my problem. I noticed Powershell 7 was now the default shell in the terminal app.

I wanted to see if I can recreate the buggy environment, so I deleted powershell 7 then reinstalled powershell as a dotnet global tool (it installed pwsh 7.0). At which point, the terminal app reverted back to using the system's powershell (v5) then displayed an error about a missing guid/profile (Sorry I didn't pay too much attention). I resetted the app again which removed the error.

I reinstalled PowerShell 7 and noticed the Terminal App stayed with the system powershell (v5).

It does seem like the terminal app picked up dotnet's pwsh as what it should use... however, I don't know if that's the app's fault or if there was some sort of setting somewhere that specified it.

**Comment by izackp** [comment]
![Annotation 2020-04-28 091152](https://user-images.githubusercontent.com/2636382/80491198-64280000-8930-11ea-96bf-fdb8a539de8a.png)

Also, the additional powershell option for dotnetglobal did not appear when I was experiencing the issue.

**Comment by izackp** [comment]
I forgot I saved a copy of settings.json. It looked  like this:
`
 "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{6e9fa4d2-a4aa-562d-b1fa-0789dc1f83d7}",
                "hidden": false,
                "name": "Legacy",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]`

**Comment by DHowett-MSFT** [comment]
> Yea, I tried it and it also failed in the standard console host.

Definitely seems like https://github.com/PowerShell/PowerShell/issues/10184, then. Thanks!

The process by which Terminal selects a "best" powershell version is ... underdocumented. Right now it's all in code:

https://github.com/microsoft/terminal/blob/db5d2fe0a5f4664c62ca0696a9c4bc14874ae66c/src/cascadia/TerminalApp/PowershellCoreProfileGenerator.cpp#L41-L47

Apart from this comment, Windows PowerShell will always be present -- it's part of Windows, so it'll always be a quasi-reliable fallback.

Marking this as question/answered. Thanks!
