### ISSUE TITLE
How to add to the right-click menu

### ISSUE THREAD

**Issue by shijunti19** [microsoft/Terminal#561]
How to add to the right-click menu

This is a necessary function.

Administrator mode must also be supported

For example:
```cmd
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\folder\shell\cmd]
@="CMD"

[HKEY_CLASSES_ROOT\folder\shell\cmd\command]
@="cmd.exe /k cd %1"
```
![image](https://user-images.githubusercontent.com/5392211/57354343-d0e54000-719d-11e9-82d0-6abf3538e6d2.png)

![image](https://user-images.githubusercontent.com/5392211/57354433-068a2900-719e-11e9-8a00-ed0f1192f776.png)

![image](https://user-images.githubusercontent.com/5392211/57354861-40a7fa80-719f-11e9-8299-92210143eaac.png)

**Comment by Dyalius** [comment]
I got a script for vscode in @sdyalor repo is made in python, you can try it UwU

**Comment by Dyalius** [comment]
I got a script in my repo, for the same thing but vscode, you are free to modify

**Comment by shijunti19** [comment]
@Dyalius I can't find exe for Windows Terminal

He's an uwp program.

**Comment by shijunti19** [comment]
![image](https://user-images.githubusercontent.com/5392211/57353581-8bc00e80-719b-11e9-971a-47140f4784f1.png)

**Comment by Summon528** [comment]
It's wt.exe

**Comment by shijunti19** [comment]
@Summon528 Thank you

**Comment by yanglr** [comment]
@shijunti19
the complete steps are here:
https://github.com/microsoft/terminal/issues/1060#issuecomment-497539461

**Comment by KUTlime** [comment]
@shijunti19 
An easy-to-use solution can be found [here](https://github.com/KUTlime/PowerShell-Open-Here-Module).
