### ISSUE TITLE
Mouse wheel scrolls backwards when set to "one screen at a time"

### ISSUE THREAD

**Issue by sebfoucault** [microsoft/terminal#5610]
# Environment
```
Microsoft Windows [Version 10.0.18363.720]
Windows Terminal 0.11.1121.0
Lenovo X1 Yoga
Logitech Mouse (M185)
```

# Steps to reproduce
- Open Windows Terminal
- Open a shell (cmd, Powershell, ...)
- Issue commands leading to the display of vertical scrollbar 
- Use the mouse wheel

# Expected behavior
- Mouse wheel should behave in Windows Terminal as it does in other system apps 

# Actual behavior
- Mouse wheel scrolls in the other direction (rolling the mouse wheel upward scrolls down)

Suspecting potential conflicts with the Laptop touchscreen or trackpad i disabled them, but still observe the same behavior. I tried to look for parameters allowing to control the mouse wheel but did not find any.

**Comment by zadjii-msft** [comment]
When you use the mouse wheel in the legacy console (`conhost.exe`), does scrolling the wheel up move the buffer contents down / move the scroll position up? Or does it move in the opposite direction? 

Does the Terminal scroll in the same direction as the legacy console?

**Comment by sebfoucault** [comment]
> When you use the mouse wheel in the legacy console (`conhost.exe`), does scrolling the wheel up move the buffer contents down / move the scroll position up? Or does it move in the opposite direction?

In `connhost.exe`, it is the other way around: scrolling the wheel up, move the scroll position up (toward the beginning of the console buffer)

> Does the Terminal scroll in the same direction as the legacy console?

From the mouse wheel perspective, the behavior of the new Terminal is inconsistent with the one of the legacy console.

**Comment by PhMajerus** [comment]
Testing with a Microsoft Sculpt Ergonomic Mouse, the scrolling works in the correct direction in both conhost and Windows Terminal.
Could Logitech have some extra software that has a per-app customization?

**Comment by sebfoucault** [comment]
> Could Logitech have some extra software that has a per-app customization?

That is what i was initially suspecting but actually i don't have any Logitech-specific app installed.
The external mouse relies on the "default-driver" (assuming that this means something - i am not a driver specialist).

**Comment by WSLUser** [comment]
Works right for me using CMStorm mouse in my Windows VM.

**Comment by DHowett-MSFT** [comment]
Were you one of the people for whom the older versions of Terminal just _didn't let you scroll_?

**Comment by sebfoucault** [comment]
@DHowett-MSFT - No. The old version of Terminal just worked fine.

After more research, I think I found the root cause of the problem (can reproduce consistently on two different PCs):
- The Windows mouse wheel configuration screen has two options for  _"Roll the mouse wheel to scroll"_: 1 - _"One screen at a time"_ and 2 - _"Multiple lines at a time"_
- The inversion occurs when the _"One screen at a time"_ option is selected.

Paying more attention to this problem, i also noticed that some of one of "MS Powerpoint" windows is subject to the same problem in the same _"One screen at a time"_ configuration: on the left-hand side powerpoint displays thumbnails of the slides. The scrolling in _this_ thumbnails window has the same inversion problem.

**Comment by DHowett-MSFT** [comment]
Wow! Good find.

**Comment by DHowett-MSFT** [comment]
Two bugs. We're storing the return value from SPI_GETWHEELSCROLLLINES as an int when it should be a uint, and we're ignoring WHEEL_PAGESCROLL (which once we store it in the wrong type comes out as `-1`).
