### ISSUE TITLE
Moving from profiles.json to settings.json broke my colorschemes

### ISSUE THREAD

**Issue by VikingScientist** [microsoft/terminal#5611]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.11.1121.0

Any other software? No
```

# Steps to reproduce

Have a customized `profiles.json` file and upgrade to newest release which uses `settings.json`

# Expected behavior

No change whatsoever

# Actual behavior

None of my customized colorschemes seemed to work and they all reverted to their default values.

# Fix for me

It would seem that `settings.json` is case-sensitive and requires the keyword to be written `colorScheme`, while I had previously used `colorscheme`.

**Comment by zadjii-msft** [comment]
Wow, if you had `colorscheme` in your settings file, you must have installed the Terminal an exceptionally long time ago. Thanks for sticking with us for so long through the preview process ❤️!

As you've found out, the `colorscheme` key was deprecated in favor of `colorScheme`. Largely, we're tracking all the "upgrade to 0.11 broke my settings" bugs with #5458, so I'm gonna close this thread as a duplicate.

Thanks!

/dup #5458

**Comment by nandesu** [comment]
Thanks for this. I spent hours creating my custom themes and was having the same issue. Finally just opened it in VSCode instead of vim and noticed that the scheme has this camel case key now.
