### ISSUE TITLE
Emoji input doesn't input anything

### ISSUE THREAD

**Issue by mbartlett21** [microsoft/terminal#5617]
Environment
========

```none
Windows build number: Microsoft Windows [Version 10.0.18363.815]
Windows Terminal version (if applicable): 

Any other software?
```
This is using [Lua](https://github.com/lua/lua), edited to execute `chcp 65001 > nul` before reading any input.

Steps to reproduce
============
When entering a line into Lua, enter a unicode emoji.

Expected behavior
============
The emoji would be read as four utf-8 bytes: `\xf0\x9f\x99\x82`

Actual behavior
==========
The line is only read up to the emoji (not including it).

Notes
====
When I tried this in `cmd` (also through MS Terminal), it entered correctly, resulting in
`'😀' is not recognized as an internal or external command, operable program or batch file.`

Lua uses `fgets` to read a line.

I tested `_getch` as another method and it had the same problem (It refused to read anything unless it was ASCII and not an emoji).

**Comment by jdebp** [comment]
Or, rather, a C program whose `fgets()` devolves onto `ReadFile()` does not read characters greater than U+00007F &hellip; which is issue #4551 .

**Comment by mbartlett21** [comment]
Ok. I'll close this then.
