### ISSUE TITLE
Wrong colors after executing bat

### ISSUE THREAD

**Issue by JekRock** [microsoft/terminal#5619]
# Environment

Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1121.0

# Steps to reproduce

1. Install [bat](https://github.com/sharkdp/bat) via chocolatey
2. Create a text file with content that doesn't fit into a screen height
3. In Windows Terminal push ENTER while the output takes more than the screen height
4. Open the file created at the second step with the command _bat filename_
5. Press _q_
6. Now the output has wrong colors that get back to previous colors after a few commands or after the _clear_ command

# Expected behavior

Colors should remain the same after executing console utils

# Actual behavior

Here is the command prompt before performing anything

![Annotation 2020-04-28 170844](https://user-images.githubusercontent.com/5882133/80499246-65c7e700-8975-11ea-8b49-eb8aa1fc99bf.png)
The expected bat util output
![Annotation 2020-04-28 171203](https://user-images.githubusercontent.com/5882133/80499325-83954c00-8975-11ea-9782-4415144cd472.png)
The bat util output after performing 1-4 steps. Please notice that the ":" in the bottom left corner is now black
![Annotation 2020-04-28 171303](https://user-images.githubusercontent.com/5882133/80499443-a9225580-8975-11ea-8406-fe2a7ee67fe4.png)
The console prompt after performing all described steps
![Annotation 2020-04-28 171342](https://user-images.githubusercontent.com/5882133/80499653-ebe42d80-8975-11ea-92ab-4cf5cb2f8503.png)

Also, colors remain unchanged if the bat util command is executed right after the _clear_ command

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, an application bug. `bat` believes that it understands the windows console API, and it's replacing the active color attributes with ones of its choosing.

**Comment by DHowett-MSFT** [comment]
(this happens outside of Terminal too:

![image](https://user-images.githubusercontent.com/14316954/80520092-ca674f80-893d-11ea-8dd4-8555d24949c0.png)

there's a `:` there.

)

**Comment by DHowett-MSFT** [comment]
(THis could be related to #4177 if `less` is in the picture.)
