### ISSUE TITLE
Terminal ignores defaultprofile setting

### ISSUE THREAD

**Issue by tomlm** [microsoft/terminal#5621]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1121.0
```

# Steps to reproduce
I have 9 profiles defined with defaultProfile pointing to a profile guid

1. start terminal

# Expected behavior
For defaultProfile to be honored, or first profile to be used.

# Actual behavior
first tab window defaults to POWERSHELL profile regardless of "defaultProfile" setting.  Even if I remove the powershell profile it still defaults to powershell on startup.

This behavior started after the latest upgrade.  It used to work just fine. 

attached is profile 
[profiles.txt](https://github.com/microsoft/terminal/files/4546585/profiles.txt)

**Comment by zadjii-msft** [comment]
Thanks for the report! 0.11 introduced some breaking settings changes which is probably causing this issue for you. This is tracked by another issue on our repo - please refer to #5458 for more discussion.

/dup #5458
