### ISSUE TITLE
Terminal closes to update without asking permission

### ISSUE THREAD

**Issue by aleksey-hoffman** [microsoft/terminal#5622]
# Environment

```none
Windows build number: Version 10.0.18363.752
Windows Terminal version (if applicable): 0.11.1121.0
```

# Steps to reproduce

Have the terminal app open

# Expected behavior

Am I seeing things, or does terminal automatically closes to update without asking permission? It happend to me for the 2nd time. 

When I got back to my computer, I realised that my running server was stopped because the terminal app was closed, turns out it got updated (as always its icon was in the "stuck progress" state, but that's a Windows 10 bug and is not related to this issue)

![image](https://user-images.githubusercontent.com/61761672/80514656-78e4b200-8989-11ea-91aa-a39cc91acb20.png)

# Actual behavior

Terminal closes automatically to update without asking permission.

**Comment by DHowett-MSFT** [comment]
Before I triage this-

> Knowing Microsoft developers, I understand that they don't care

Hi, we are real people. You do not need to resort to ad hominem to make your point.

**Comment by aleksey-hoffman** [comment]
@DHowett-MSFT sorry mate, I edited it out.
I just lost too much unsaved work too many times because Windows 10 restarted after updating while I was away from the computer without asking any permission.

**Comment by aleksey-hoffman** [comment]
@DHowett-MSFT sorry mate, I edited it out. 
It's just I lost too much unsaved work too many times because of Windows 10 restarting without asking permission after updating while I was away from the computer.

**Comment by DHowett-MSFT** [comment]
I know, it’s pretty crappy. We haven’t yet cracked the API that lets us tel the store to hold off yet. We try, though, when there are multiple tabs open. I’ve seen reports that clicking “cancel” in the “are you sure you want to close all these fine tabs?” dialog just makes the store _kill_ us instead of waiting :/

**Comment by DHowett-MSFT** [comment]
(Also, thank you. I’ve filed bugs out of anger, and I always feel bad afterwards. Sorry we made you lose some work :()

**Comment by zadjii-msft** [comment]
There's also #3915 - maybe we should dupe this thread?

**Comment by aleksey-hoffman** [comment]
@DHowett-MSFT yeah thanks for understanding. I know we shouldn't get annoyed by stuff like this, you guys are doing your best, you made the app open source, you are improving it every day, what is there more to ask, it takes time, you guys are doing a good job!

I suppose we can dupe this thread since there's a similar one opened, I didn't see it.

**Comment by zadjii-msft** [comment]
Thanks!

/dup #3915
