### ISSUE TITLE
Possible to get multiple selections visible with `copyOnSelect` enabled

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5628]
On the 0.11.1153.0 prerelease

Stick these in your globals:

```json
    "copyOnSelect": true,
    "copyFormatting": false,
```

run `dir` to fill the buffer up, then `ping -t google.com`.

If you quickly select two different spots in the buffer, you can get both the old selection region and new selection region to be visible at the same time. I'm 88% sure this is purely graphical - it seems like the only _actual_ selection is the second one, and as soon as more lines appear in the buffer, the old selection will disappear.

This might just be an ordering issue? Maybe we're not invalidating the old selection region when making a new one?

Weirdly, I couldn't get this to repro w/o running ping.

**Comment by DHowett-MSFT** [comment]
This is definitely a regression from incremental R.

**Comment by zadjii-msft** [comment]
I'm just gonna shove this on 1.0, since it regressed with #5345 (et. al) but feel free to override me if this doesn't make the bar

**Comment by zadjii-msft** [comment]
Hey so playing I'm with 0.11.1204.0, and I absolutely can't get this to repro anymore. This must have been fixed between `1153` and `1204`
