### ISSUE TITLE
[Question] How I can change the selection color?

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#5635]
Hello,
How I can change the selection color?
![Windows Terminal](https://user-images.githubusercontent.com/23485114/80568556-7b3c2000-8a0c-11ea-8b21-151b4635fd35.gif)

**Comment by DHowett-MSFT** [comment]
You can set `selectionColor` in your profile.

**Comment by xmha97** [comment]
I added this line to my profile and working fine.
```
"selectionBackground" : "#fedba9"
```
But this not working when I added to schemes
![VisualStudio Code](https://user-images.githubusercontent.com/23485114/80639848-d1927880-8a77-11ea-8c32-9866f663d46e.png)

**Comment by DHowett-MSFT** [comment]
It doesn't work in a scheme, but it's reasonable to expect that it would.
