### ISSUE TITLE
Make settings easy to share and deploy

### ISSUE THREAD

**Issue by MartinSGill** [microsoft/terminal#5638]
# Description of the new feature/enhancement

To make settings much more portable/shareable it would be good to allow an "import" or "include" folder for settings.

This would allow settings to be easily distributed, installed via automation (Group Policy, Ansible, Chef, etc) or stored in Drive/Dropbox to share between machines.

For Example: If people want to create/share themes it would now be possible to just drop a new file into the folder, instead of editing json by hand.

# Proposed technical implementation details (optional)

 The common linux practice of using a `settings.d` style folder and loading all files in that folder seems like a good approach to me.

* Settings.json defines an "include" directory (environment variables permitted)
* Settings loads all files in that folder in alphabetical order.
* Settings adds/overrides settings based on loaded files.
* Additional files would all have the same structure/schema as the default settings.json
* [Extra Credit] Support multiple folders, allow shared/user settings.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
