### ISSUE TITLE
Ctrl+V (vertical selection in Vim) does not work

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#5641]
I guess it's because it's now bound by default to do paste.

I think it's quite a pain point for anyone new to Linux development on Window: vim basic functionality does not work :(

**Comment by vadimkantorov** [comment]
I think MS Terminal should allow some Keybinding Profiles (like Visual Studio / ReSharper do) and hopefully it would be super-easy to change them. It may seem that satisfy everyone is impossible :(

**Comment by zadjii-msft** [comment]
So we've probably had this discussion 1000 times across this repo now. The basic conclusion is always the same: 

>  It may seem that satisfy everyone is impossible

When we only had <kbd>Ctrl+Shift+C</kbd>/<kbd>Ctrl+Shift+V</kbd> as the copy/paste keybindings, users were unhappy. Now that we've added back <kbd>Ctrl+C</kbd>/<kbd>Ctrl+V</kbd>, users are still unhappy.

With the new "default" settings in 0.11, the balance we've tried to compromise on is the following:
* <kbd>Ctrl+Shift+C</kbd>/<kbd>Ctrl+Shift+V</kbd> are bound in `defaults.json`, and users will need to actually _unbind_ those keys to disable their functionality. 
  - These are the keybindings we've always had for copy-paste, so breaking them seemed like a terrible idea
  - Nobody was really complaining about these being used for copy/paste as opposed to something else
* <kbd>Ctrl+C</kbd>/<kbd>Ctrl+V</kbd> are now listed in new user's `settings.json` file when they create a new settings file.
  - If they don't like them, it's _trivial_ to just delete them from the file. 
  - <kbd>Ctrl+Shift+C</kbd>/<kbd>Ctrl+Shift+V</kbd> will still work if the user deletes the <kbd>Ctrl+C</kbd>/<kbd>Ctrl+V</kbd> bindings from their `settings.json`

**Comment by vadimkantorov** [comment]
I understand there're tradeoffs. I understand one can fix manually the keybindings by editing settings.json.

The point of this issue is to point out a concrete example of very common, wide-spread `vim` functionality that breaks. This is not just "I don't like Ctrl+V", it is a problem that almost every vim-user will encounter. Since it's wide-spread, I think, it calls for more special consideration: e.g. big letters in README about this specifically or MessageBox on first launch, or an explicit invitation to change keybindings on the first launch, or sth else.

The profile idea would allow users to change multiple keybindings at once without encountering the problems and fixing them one by one. The same motivation applies to Microsoft Visual Studio / IntelliJ etc. If my preset is e.g. "Gnome Terminal", I'm sure everything will "just work" and have correct expectations about the chosen tradeoffs.

**Comment by rayfoss** [comment]
I'm actually having issues with ctrl+shift+v behaving erratically. It's not pasting new lines apparently.

**Comment by DHowett-MSFT** [comment]
So, this would ultimately be solved by /dup #5790, which I've promoted to be "profile-specific keybindings". FWIW: I don't like binding ^V by default either, but I more don't like how literally 50% of all our users yell at us regardless of the choice we made. :smile:

All we can do is add more flexibility.
