### ISSUE TITLE
Duplicate tab isn't duplicate

### ISSUE THREAD

**Issue by PandaClone** [microsoft/terminal#5647]
**Issue**:
Duplicating a tab changes your directory to the default directory instead of duplicating the tab's current working directory.

**Expectation**:
Duplicate tab to be a duplicate. Should open up the same terminal type and the same directory. It's not a duplicate if it's different.

**Steps**:
1) Open Windows Terminal
2) Change directory (e.g. cd test)
3) Duplicate the tab (Ctrl + Shift + D)
4) New tab is in the default directory instead of your current working directory (i.e. test)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3158 for more discussion.

/dup #3158
