### ISSUE TITLE
Add ability to click on links within the terminal

### ISSUE THREAD

**Issue by AgrMohit** [microsoft/terminal#5648]
# Description of the new feature/enhancement
A feature that would let users click on any hypertext link in the console and be able to open that in the default browser would be very helpful. 

Such a feature would help a lot in many cases like viewing the raw markdown using 'cat' command and being able to know where it links rather than going through the process of copying the link by mouse.

# Proposed technical implementation details (optional)
An implementation similar to what is in place in visual studio code would, in my opinion, be quite adequate. Like underlining clickable links and only (ctrl+click) opens the link to prevent accidental clicks.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #574 for more discussion.

/dup #574
