### ISSUE TITLE
Json Schema doesn't autocomplete when setting the color scheme in VS Code

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#5649]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software?
VS Code
```

# Steps to reproduce

Open Settings from the About Page and see it launch in VS Code.
Define `"colorScheme"` to use a color scheme listed in `defaults.json`. Watch as Code refuses to do autocomplete for it. 
# Expected behavior

I expect the auto-complete to supply a list of color schemes listed in` defaults.json` that narrows as you start typing. For example, if the first letter I choose is "T", I'd expect all options that start with the letter T to appear in the helpful drop-down list (the newly added Tango schemes in this case.)

# Actual behavior

You need to manually type it or copy/paste the name from `defaults.json`.

**Comment by zadjii-msft** [comment]
This _might_ be possible for the built-in themes, but I can't imagine that it would be possible to get this auto-complete behavior for schemes that the user has added

**Comment by WSLUser** [comment]
Yes, I'm thinking anything in `defaults.json` ought to be able to get IntelliSense. The user is on their own for any custom schemes.

**Comment by WSLUser** [comment]
> but I can't imagine that it would be possible to get this auto-complete behavior for schemes that the user has added

```
// Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],
```
Actually now that I think about it, before "colorScheme" is set, if `"schemes": []` is configured, then we ought to be able to use what's defined there to allow "colorScheme" to get IntelliSense. VSCode does this when you write code that is intended to be re-used later on such as a variable. We should be able to take advantage of that.

**Comment by DHowett-MSFT** [comment]
We would need an entire LanguageServer to get VSCode to suggest existing schemes. That’s just not something the schema can do, and it’s not something we’re likely to do. Great VSC extension idea!

**Comment by WSLUser** [comment]
Probably there should be a way to get the TS/JS language server to help with json. Red Hat puts out a YAML extension though so it could go either way. I'll file a feature request on their side for it.

**Comment by DHowett-MSFT** [comment]
I mean, I think the JS/TS language servers _do_ help with JSON, by way of the schema. Since there’s no schema-approved way to set dependent values and implement dynamic sets or say that you need to parse TWO json files instead of just the one, it’s just not something a generic language server or schema can _do_. It needs to be specific to the terminal settings format just so that it can actually give you contextual feedback.

**Comment by WSLUser** [comment]
I think it's reasonable to only be able to parse through settings.json. If users create a separate json for settings, probably via extension, it would be on the extension to ensure the schema registers that json instead of the regular `settings.json` (It really ought to just overwrite the original and ensure it stays synced to any changes made to `settings.json`.

**Comment by WSLUser** [comment]
You can always add` jq` as a dep for json parsing. That is exactly what it's intended to do and it does it well (and it available for Windows, not just Linux unlike `sed`, `awk`, `gawk`, etc.)

**Comment by DHowett-MSFT** [comment]
Sorry, it’s just not terminal’s job. This is really good stuff to capture for VSC though

**Comment by WSLUser** [comment]
The action still here is reading the schemes from default.json. The schema can do that.

**Comment by vmiheer** [comment]
The schema causes warning (Incorrect type String expected) when using (valid):

```json
              "colorScheme": { "light": "Solarized Light", "dark": "Solarized Dark" },
```

Not sure if it's already fixed.
