### ISSUE TITLE
Move the solution to VS2019 and v142 toolset

### ISSUE THREAD

**Issue by chunliu** [microsoft/terminal#565]
As mentioned in README, (also related to #534) 

> If you're running VS2019, you'll also need to install the "v141 Toolset" and "Visual C++ ATL for x86 and x64"

But actually v141 Toolset is not required in VS2019. The following are the configurations of my VS2019 and I can build the solution successfully. 

C++ Desktop development
![image](https://user-images.githubusercontent.com/2128551/57354074-ad69c780-7194-11e9-9126-9c212db2a214.png)

UWP development
![image](https://user-images.githubusercontent.com/2128551/57354124-dbe7a280-7194-11e9-8994-e1f670e14a34.png)

Individual components
![image](https://user-images.githubusercontent.com/2128551/57354263-40a2fd00-7195-11e9-8594-99c906e554be.png)

To build the solution in VS2019, you need to have:
- Windows 10 version 1903
- Windows 10 SDK (10.0.18362.0)
- VS2019 with C++ Desktop and UWP development workloads, as shown in the above screenshots

And **retarget the solution** to v142 platform and the latest Windows SDK.

**Comment by Biswa96** [comment]
Consider the README instructions as minimal build environment requirements. And v142 > v141.

**Comment by fcharlie** [comment]
```
git clone https://github.com/microsoft/Terminal.git
cd Terminal
git submodule init
git submodule update
nuget restore OpenConsole.sln
msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
```

**Comment by MarioLiebisch** [comment]
> Consider the README instructions as minimal build environment requirements. And v142 > v141.

Might be, but it's still very misleading. If you have VS 2019, you don't **need** the v141 tools, because it should install either v141 or v142 by default anyway. My first impression was also that I'd have to install those, too.

**Comment by sagood** [comment]
Have the same issue by using VS2019 16.1.0 Preview 3.0

![image](https://user-images.githubusercontent.com/1913817/57365154-d71af280-7184-11e9-927f-ae57d8d2b173.png)

But can be built within by using VS 2017

**Comment by timheuer** [comment]
@chunliu consider renaming this issue to "Move to VS2019 and v142 toolset" to be more directed at what is proposed.

**Comment by jongio** [comment]
@fcharlie Did you run in Command Tools for VS or cmd?

**Comment by timheuer** [comment]
> @fcharlie Did you run in Command Prompt for VS or cmd?

If you run tools/razzle.cmd before what @fcharlie runs you can do it in cmd and not need the 'for VS' one (basically sets all the paths just in case)

**Comment by chunliu** [comment]
@timheuer if the source solution is moved to VS2019 and v142, people with VS2017 could have problem to build it as v142 toolset might not be installed on VS2017. 

I think the proper way to address the building issue of VS2019 is to keep the source solution targeting on VS2017 and v141 toolset, but include the proper instructions for VS2019 and v142 toolset in README. The team can retarget the source solution when they don't need to support VS2017 anymore.

**Comment by chunliu** [comment]
@jongio I tried it with VS2019 command prompt and it is working fine. You need to include the path `.\dep\nuget\` for nuget command.

**Comment by jankun** [comment]
After installing 35gb of randomly inserted dependencies (which VS is even more confused about) and even more confusing ARM|x86 named configs I got 40gb of sdk's installed just to find out I still only need another 12GB of extra bloatware to build parts with v141. Makes sense for vs2019. Totally.

**Comment by snooopcatt** [comment]
> ```
> git clone https://github.com/microsoft/Terminal.git
> cd Terminal
> git submodule init
> git submodule update
> nuget restore OpenConsole.sln
> msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
> ```

this worked, but how do I deploy? OpenConsole.exe starts old console

**Comment by fcharlie** [comment]
@snooopcatt My notebook is too old, I have not tried how to package and deploy it on the command line.

**Comment by chunliu** [comment]
@snooopcatt the easiest way is to package or deploy it with Visual Studio.

**Comment by chunliu** [comment]
@snooopcatt there is a PowerShell script in `build/scripts/Create-AppxBundle.ps1`. I didn't try it, but maybe you can use it to package the app from command line.

**Comment by 12101111** [comment]
![图片](https://user-images.githubusercontent.com/8438475/57467977-290f6580-72b6-11e9-96c2-992fcc85e044.png)
I have thousands of "error MIDL2003: [msg]redefinition [context]".
I 'm using VS 2019, v142 and SDK 10.0.18362

**Comment by Tuumke** [comment]
> > ```
> > git clone https://github.com/microsoft/Terminal.git
> > cd Terminal
> > git submodule init
> > git submodule update
> > nuget restore OpenConsole.sln
> > msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
> > ```
> 
> this worked, but how do I deploy? OpenConsole.exe starts old console

Don't you need to press CTRL+T to start a new tab?

**Comment by YYYGH** [comment]
I have a error 	MIDL2011	[msg]unresolved type declaration [context]: Windows.UI.Xaml.Markup.IXamlMetadataProvider [ RuntimeClass 'TerminalApp.XamlMetaDataProvider'  ]	TerminalApp	F:\GitHub\Terminal\src\cascadia\TerminalApp\x64\Release\XamlMetaDataProvider.idl	6	
![image](https://user-images.githubusercontent.com/26573739/57499179-44f42500-7311-11e9-8b37-a809a0649f4e.png)

**Comment by chunliu** [comment]
@YYYGH and @12101111 Did you retarget the solution to the latest Windows SDK and v142 platform in Visual Studio?

**Comment by YYYGH** [comment]
> @YYYGH and @12101111 Did you retarget the solution to the latest Windows SDK and v142 platform in Visual Studio?

thank you! I renew the solution config and is build success.
![image](https://user-images.githubusercontent.com/26573739/57504410-e5087900-7326-11e9-90ba-d2e2fcf31dfc.png)
but can't run WindowsTerminal.exe, is no reaction.
windows 10 version: 1803

**Comment by chunliu** [comment]
@YYYGH to run it, you need Windows 10 1903 with Developer mode on. Then you can right click the solution in VS and choose Deploy Solution.

**Comment by YYYGH** [comment]
> @YYYGH to run it, you need Windows 10 1903 with Developer mode on. Then you can right click the solution in VS and choose Deploy Solution.

Thanks very much!

**Comment by DallasTheCat** [comment]
> ```
> git clone https://github.com/microsoft/Terminal.git
> cd Terminal
> git submodule init
> git submodule update
> nuget restore OpenConsole.sln
> msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
> ```
Thanks!

**Comment by Backer-Sultan** [comment]
I'm not able to deploy the WindowsTerminal. I'm getting the following error telling me that the deployment target should be running on 10.0.18362.0 or higher
![image](https://user-images.githubusercontent.com/8945603/57580479-5a508700-74aa-11e9-9ba7-db80c2333db4.png)
 Though, in the project setting, the target SDK is 10.0.17763
![image](https://user-images.githubusercontent.com/8945603/57580504-b0252f00-74aa-11e9-9138-7c701512a91c.png)

And I'm sure that my Windows is running that version.
![image](https://user-images.githubusercontent.com/8945603/57580508-c59a5900-74aa-11e9-8d1a-b1b9bb1ca668.png)

I'm not sure where is the error coming from!

**Comment by MarioLiebisch** [comment]
@Backer-Sultan The error message is correct. It's not just an SDK thing (the "target" you select). It's also a functionality thing. You'll need Windows 10 version 1903 (i.e. the May 2019 update) for this to be deployable and functional.

**Comment by Backer-Sultan** [comment]
> @Backer-Sultan The error message is correct. It's not just an SDK thing (the "target" you select). It's also a functionality thing. You'll need Windows 10 version 1903 (i.e. the May 2019 update) for this to be deployable and functional.

Thank you for the clarification! The May 2019 update is still not available for me for some reason. I will try to manually install it.

**Comment by MarioLiebisch** [comment]
@Backer-Sultan As far as I know it's only on MSDN so far, not yet on Windows Update (think that will follow some time within the next 2 or 3 weeks).

**Comment by BaRRaKudaRain** [comment]
Install newer version of Windows 10 SDK.
In your case you need to install 10.0.18362.0 or try insider version. Next retarget project/solution and try to build it.


--
----------------------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by BaRRaKudaRain** [comment]
Get the image of Windows 10 1903 from tb.rg-adguard.net

--
----------------------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by DHowett-MSFT** [comment]
You should probably not download your operating systems from a website called `rg-adguard.net`. Link scrubbed.

Please don't share dodgy advice and strange binaries in this issue tracker.

**Comment by thenecroscope** [comment]
Hi, can anyone give me any pointers please. I'm using VS2019 and everything is building within VS2019 nicely and I can click deploy and I get no errors. When I try to run the app from an elevated command prompt using:

1, razzle.cmd
2, bcz
3, opencon.cmd

Everything runs fine, no errors, but it launches  the old console when I ran the batch file. If I press CtrlT I just get ctrl characters sent to the console. What am I missing, I'm not seeing any errors just 3 warnings.

I have the latest SDK installed. Nuget packages installed fine. I've ran the 2 git submodules  commands.

I've tried using MSBuild as detailed above also,, all looks good. Just 3 warnings, but still no joy.

I'm currently on Windows 10 insider, fully up to date with patches etc....

thanks

**Comment by ksawerykarwacki** [comment]
After few hours of struggle I used @fcharlie method i reduced number of warnings to 3:

`Build succeeded.

"C:\Users\ksawe\source\repos\Terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\ksawe\source\repos\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj.metaproj" (default target) (47) ->
"C:\Users\ksawe\source\repos\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj.metaproj" (default target) (48) ->
"C:\Users\ksawe\source\repos\Terminal\src\cascadia\TerminalApp\TerminalApp.vcxproj" (default target) (49) ->
(Link target) ->
  XamlTypeInfo.g.obj : warning LNK4197: export 'DllGetActivationFactory' specified multiple times; using first specification [C:\Users\ksawe\source\repos\Terminal\src\cascadia\Ter minalApp\TerminalApp.vcxproj]


"C:\Users\ksawe\source\repos\Terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\ksawe\source\repos\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj.metaproj" (default target) (47) ->
"C:\Users\ksawe\source\repos\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj" (default target) (51) ->
  WindowsTerminal.manifest : manifest authoring warning 81010002: Unrecognized Element "maxversiontested" in namespace "urn:schemas-microsoft-com:compatibility.v1". [C:\Users\ksaw e\source\repos\Terminal\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj]


"C:\Users\ksawe\source\repos\Terminal\OpenConsole.sln" (default target) (1) ->
"C:\Users\ksawe\source\repos\Terminal\pkg\appx\OpenConsolePackage.wapproj" (default target) (63) ->
(_ConvertItems target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(413,5): warning : The project 'OpenConsolePackage.w approj' has both an EntryPointExe property and one or more application references. The generated package will use the entry point specified in the EntryPointExe property. [C:\User s\ksawe\source\repos\Terminal\pkg\appx\OpenConsolePackage.wapproj]

    3 Warning(s)
    0 Error(s)

Time Elapsed 00:16:55.30`

I'm using VS2019 and lates Fast Ring build (Version 10.0.18895.1000). What should I do next?

**Comment by chunliu** [comment]
@ksawerykarwacki I think you can temporarily ignore the warnings.

**Comment by chunliu** [comment]
@thenecroscope after you deploy the solution, you should see **Windows Terminal (Preview)** in Start menu. You can launch the terminal from there.

**Comment by ksawerykarwacki** [comment]
@ksawerykarwacki I switched to building from VS after those warnings and everything builded and started. One misleading thing was lack of tabs which were hidden by default.

**Comment by thenecroscope** [comment]
Hi,

Where is the best place to add some feedback to the team with feature requests, bugs etc...?
Do you have a simple Wiki page that details keyboard shortcuts for the app?

thanks!

**Comment by mKay00** [comment]
Here on github under issues is the best place for feature requests, bugs, etc.
Keyboard shortcuts will be remappable soon and you can find and change them in the profiles.json #748

**Comment by valen214** [comment]
> ```
> git clone https://github.com/microsoft/Terminal.git
> cd Terminal
> git submodule init
> git submodule update
> nuget restore OpenConsole.sln
> msbuild /p:Configuration=Release;AppxBundle=Always;AppxBundlePlatforms="x64" /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
> ```

I have to add `/p:OutputPath=<project directory>\bin` to mitigate some error.

**Comment by miniksa** [comment]
Current issues delaying completion of this:
- The internal build lab required for signing packages does not yet support Visual Studio 2019, 14.2, nor the 1903 SDK (10.0.18362).
    - Mail has been sent to the lab onboarding team asking for support and an ETA
- The alternative of using a multi-phase build (use public Hosted 2019 pool for build, use internal pool for signing) is a possibility, but...
    - We would need to have something that sets up the versioning resources for us. This is currently done by an internal-only pool support task. We would need to identify and implement a public task to set up the version during the compilation phase on the Hosted 2019 pool and then send the artifacts to the internal 2017 pool for signing dispatch and symbol registration 
- A final alternative recommendation was given to us by the lab build team: try to nuget-fetch the build tools required onto the 2017 machine.
    - I tried this and it sat for 6+ minutes going nowhere and I presume it will time out. Reliability/performance of this is too bad for me to consider further.


- I will upload a draft PR with the version number changes. It works fine in VS2019 with the version number changes. Also, as of my tests today thanks to the .vsconfig file, VS2019 can build it just fine (after resolving dependencies automatically/installing them). So can VS2017.

**Comment by miniksa** [comment]
More stuff we're stuck on:
- Hosted agents don't have the 18362 SDK installed yet. I've linked the discussion on adding them and related PRs from the Azure Agents repository in the PR #1012.

**Comment by fcrick** [comment]
> I have thousands of "error MIDL2003: [msg]redefinition [context]".
> I 'm using VS 2019, v142 and SDK 10.0.18362
> I can build it using SDK 10.0.17663 and v142

@12101111 I hit this. Doing Clean Solution and building again made it go away.
