### ISSUE TITLE
IDA Pro/Freeware console application display corruption

### ISSUE THREAD

**Issue by levicki** [microsoft/terminal#5651]
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version (if applicable): 0.11.1191.0

Any other software? IDA Pro/Freeware¹
```

# Steps to reproduce

1. Install either IDA Freeware or IDA Pro (freeware download link at the bottom).
2. Run `idat64.exe C:\Windows\Notepad.exe` from Windows Terminal.

# Expected behavior

Normal display (in cmd.exe):
![image](https://user-images.githubusercontent.com/16415478/80626211-5f596e00-8a4e-11ea-9ba9-e3c2271f0194.png)

# Actual behavior

Corrupted display (in Windows Terminal):
![image](https://user-images.githubusercontent.com/16415478/80625666-d9d5be00-8a4d-11ea-83c5-a2a01099a0bb.png)

¹ - [IDA Pro](https://www.hex-rays.com/products/ida/), there is also a free version download [here](https://www.hex-rays.com/products/ida/support/download_freeware/).

**Comment by DHowett-MSFT** [comment]
It looks like IDA attempts to force the console width, which doesn’t work in Terminal. /dup #5094

**Comment by levicki** [comment]
Is there any way to set console width that the program is expecting?

**Comment by DHowett-MSFT** [comment]
For now, resize the terminal window until the line wrapping dosappears

**Comment by DHowett-MSFT** [comment]
Disappears

**Comment by levicki** [comment]
Thanks, does that mean there are currently no JSON settings for width and height?

**Comment by DHowett-MSFT** [comment]
Not per-profile, but you can absolutely set your "initialColumns" and "initialRows" to whatever value you want.

It doesn't necessarily make sense to set the width/height per-profile in an application that can look like this:

![image](https://user-images.githubusercontent.com/14316954/80629452-bd169780-8a07-11ea-91b0-4198df24acdd.png)

**Comment by levicki** [comment]
Thanks.
