### ISSUE TITLE
Fresh install shows blank window then exits

### ISSUE THREAD

**Issue by swpalmer** [microsoft/terminal#5658]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18363.815]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software?  Just setting up a new Windows re-install, so nothing I can think would be relevant. The new chromium-based edge, but Terminal was failing before and after installed that.  Windows update says there are no updates.

settings.json is new and untouched from this initial install.
```

# Steps to reproduce
Try to launch Windows Terminal by opening or "Run as Administrator" from the start menu

# Expected behavior

Windows Terminal would launch and be usable.

# Actual behavior

A blank "gel" window appears for a second or two and goes away. Nothing for Windows Terminal is shown on the start bar.  An Application event is logged.

Faulting application name: WindowsTerminal.exe, version: 0.11.2004.28001, time stamp: 0x5ea883f8
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.815, time stamp: 0x9fa806f2
Exception code: 0xc000027b
Fault offset: 0x0000000000713530
Faulting process id: 0x1560
Faulting application start time: 0x01d61e5dc395feaa
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.11.1191.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 47537453-c99e-4fe4-834e-f02b48c6bcdd
Faulting package full name: Microsoft.WindowsTerminal_0.11.1191.0_x64__8wekyb3d8bbwe

**Comment by swpalmer** [comment]
https://aka.ms/AA8aekz

**Comment by swpalmer** [comment]
Finally solved this.  it appears to be an issue with nVidia Quadro 2000m.  Changing the setting in the nVidia control panel that had the "Preferred graphics processor" set to the "high-performance NVIDIA processor", instead to be "Auto-select" (presumably defaulting to the integrated graphics for non-3D), made this problem go away.

**Comment by DHowett-MSFT** [comment]
Wow, that's quite strange. I didn't stand a chance of figuring that one out. Thanks for following up!
