### ISSUE TITLE
Font colors for PowerShell with Acrylic

### ISSUE THREAD

**Issue by adk3141** [microsoft/terminal#5659]
I created a profile for PowerShell with Acrylic, but the colors don't work as I would expect:

![image](https://user-images.githubusercontent.com/23560567/80642418-5b354c80-8a5e-11ea-9e6d-8f69e8e964a0.png)

**Comment by zadjii-msft** [comment]
Could you share your `settings.json`? What version of the Terminal are you running?

**Comment by adk3141** [comment]
Hi Mike,

 

Could you share your settings.json?

 

Attached.

 

What version of the Terminal are you running?

 

Windows Terminal

Version: 0.11.1191.0

 

        Many thanks,

 

                -Tony-

 


Professor A D Kennedy


School of Physics and Astronomy, JCMB 4404, The University of Edinburgh

Mayfield Road, Edinburgh, EH9 3JZ, Scotland


+44 131 650 5272 (office)

 <mailto:adk@ph.ed.ac.uk> mailto:adk@ph.ed.ac.uk


+44 131 650 6555 (FAX)

 <http://www.ph.ed.ac.uk/~adk> http://www.ph.ed.ac.uk/~adk


+44 788 182 5458 (mobile)

 

 

 

 

 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by zadjii-msft** [comment]
@adk3141 Unfortunately, if you reply by mail to the github bot, I don't think it actually uploads the settings file somewhere I can see it 😕 You'll have to actually just paste it into a reply directly on github.com.

Thanks!

**Comment by adk3141** [comment]
// This file was initially generated by Windows Terminal 0.11.1191.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
  "$schema": "https://aka.ms/terminal-profiles-schema",

  "defaultProfile": "{AD13930E-3A92-44A2-9196-5E0D01D4EF97}",

  // You can add more global application settings here.
  // To learn more about global settings, visit https://aka.ms/terminal-global-settings

  // If enabled, selections are automatically copied to your clipboard.
  "copyOnSelect": false,

  // If enabled, formatted data is also copied to your clipboard
  "copyFormatting": false,

  // A profile specifies a command to execute paired with information about how it should look and feel.
  // Each one of them will appear in the 'New Tab' dropdown,
  //   and can be invoked from the commandline with `wt.exe -p xxx`
  // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
  "profiles": {
    "defaults": {
      // Put settings here that you want to apply to all profiles.
      "fontFace": "Cascadia Code PL",
      "fontSize": 15,
      "initialCols": 80,
      "initialRows": 60
    },
    "list": [
      {
        "guid": "{AD13930E-3A92-44A2-9196-5E0D01D4EF97}",
        "name": "PowerShell 7",
        "commandline": "pwsh.exe",
        "hidden": false,
        "startingDirectory": "H:/Computers/languages/PowerShell/Scripts",
        "colorScheme": "adk",
        "cursorShape": "bar",
        "scrollBarState": "visible",
        "acrylicOpacity": 0.5,
        "useAcrylic": true,
        "backgroundImage": "https://devblogs.microsoft.com/powershell/wp-content/uploads/sites/30/2018/09/Powershell_256.png",
        "backgroundImageOpacity": 0.25,
        "backgroundImageStretchMode": "none",
        "backgroundImageAlignment": "bottomRight"
      },
      {
        // Make changes here to the powershell.exe profile.
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell",
        "commandline": "powershell.exe",
        "hidden": false,
        "startingDirectory": "H:/Computers/languages/PowerShell/Scripts"
      },
      {
        // Make changes here to the cmd.exe profile.
        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "name": "Command Prompt",
        "commandline": "cmd.exe",
        "hidden": false
      },
      {
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "hidden": false,
        "name": "PowerShell",
        "source": "Windows.Terminal.PowershellCore",
        "startingDirectory": "H:/Computers/languages/PowerShell/Scripts"
      },
      {
        "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
        "hidden": false,
        "name": "Azure Cloud Shell",
        "source": "Windows.Terminal.Azure",
        "startingDirectory": "H:/Computers/languages/PowerShell/Scripts"
      }
    ]
  },

  // Add custom color schemes to this array.
  // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
  "schemes": [
    {
      "name": "adk",
      "foreground": "#ffff00",
      "background": "#0000c0",
      "cursorColor": "#F9F1A5",
      "selectionBackground": "#C19C00",
      "colors": [
        "#0C0C0C", // DARK_BLACK
        "#C50F1F", // DARK_RED
        "#13A10E", // DARK_GREEN
        "#C19C00", // DARK_YELLOW
        "#0037DA", // DARK_BLUE
        "#881798", // DARK_MAGENTA
        "#3A96DD", // DARK_CYAN
        "#CCCCCC", // DARK_WHITE
        "#767676", // BRIGHT_BLACK
        "#E74856", // BRIGHT_RED
        "#16C60C", // BRIGHT_GREEN
        "#F9F1A5", // BRIGHT_YELLOW
        "#3B78FF", // BRIGHT_BLUE
        "#B4009E", // BRIGHT_MAGENTA
        "#61D6D6", // BRIGHT_CYAN
        "#F2F2F2" // BRIGHT_WHITE
      ]
    }
  ],

  // Add custom keybindings to this array.
  // To unbind a key combination from your defaults.json, set the command to "unbound".
  // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
  "keybindings": [
    // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
    // These two lines additionally bind them to Ctrl+C and Ctrl+V.
    // To learn more about selection, visit https://aka.ms/terminal-selection
    {
      "command": {
        "action": "copy",
        "singleLine": false
      },
      "keys": "ctrl+c"
    },
    {
      "command": "paste",
      "keys": "ctrl+v"
    },

    // Press Ctrl+Shift+F to open the search box
    {
      "command": "find",
      "keys": "ctrl+shift+f"
    },

    // Press Alt+Shift+D to open a new pane.
    // - "split": "auto" makes this pane open in the direction that provides the most surface area.
    // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
    // To learn more about panes, visit https://aka.ms/terminal-panes
    {
      "command": {
        "action": "splitPane",
        "split": "auto",
        "splitMode": "duplicate"
      },
      "keys": "alt+shift+d"
    }
  ]
}

**Comment by zadjii-msft** [comment]
Ah, that'll do it. I'm _fairly_ certain we deprecated the `colors:[]` format for color schemes in 0.11.

I'd take a look at #5458 for more info

**Comment by DHowett-MSFT** [comment]
We'd deprecated that back in 0.3, and only removed it in 0.11. Sorry about that.

**Comment by adk3141** [comment]
Yes, that fixed it.
Is there a reason initialRows does not seem to work anymore?

**Comment by DHowett-MSFT** [comment]
>Is there a reason initialRows does not seem to work anymore?

Is it's in `globals`, you'll want to continue to refer to #5458

**Comment by adk3141** [comment]
Not in globals, but in `defaults`. Moving it to top-level solved that problem too. Thanks so much!
