### ISSUE TITLE
Terminal runs at 60Hz

### ISSUE THREAD

**Issue by ismaeelakram** [microsoft/terminal#5662]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.121.0

Any other software?
```

# Steps to reproduce

Run Terminal on 144Hz Monitor.

# Expected behavior

Terminal should run smoothly and cursor should move at 144hz.

# Actual behavior

Terminal runs at 60Hz and cursor looks choppy compared to normal.

**Comment by mendhak** [comment]
Possible duplicate of:  https://github.com/microsoft/terminal/issues/649

**Comment by zadjii-msft** [comment]
Sure sounds like it to me. Thanks @mendhak!

/dupe #649
