### ISSUE TITLE
unicode typing problem

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#5663]
Hello,
Windows Terminal do not display Persian (Arabic) texts
![XmYVPtci8i](https://user-images.githubusercontent.com/23485114/80669268-34583400-8ab9-11ea-8faa-16446ec0fe9c.gif)
This is while PowerShell is working properly
![Bh2K8GxTu6](https://user-images.githubusercontent.com/23485114/80669317-56ea4d00-8ab9-11ea-98ab-46b90597f67f.gif)
I even changed the Windows Terminal font and selected fonts that support Persian.
I didn't have a problem with previous versions of Windows Terminal, and everything worked fine.
Please help me solve this problem.
Thanks

**Comment by zadjii-msft** [comment]
You might be interested in #538 and #4779.

I'm kinda shocked how well this is doing in the `powershell.exe` window - I'd think that the vintage console would do a much _worse_ job than that 😋 

/dup #4779
