### ISSUE TITLE
BSOD When clicking Settings

### ISSUE THREAD

**Issue by Zagan202** [microsoft/terminal#5664]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1191.0

```

# Steps to reproduce

Click settings button 

# Expected behavior

Opens settings.json

# Actual behavior

BSOD

**Comment by DHowett-MSFT** [comment]
What was the bug check code?

**Comment by Zagan202** [comment]
I’m unsure where I would find the bug check code.

**Comment by Zagan202** [comment]
https://aka.ms/AA8amwr

**Comment by DHowett-MSFT** [comment]
Unfortunately, it looks like the feedback system was unable to recover any information about your bugcheck. I hate to ask, but does this happen _every_ time you open Settings?

All Terminal does when you click "Settings" is, effectively, double-click the `json` file using `ShellExecute`. I'd be very surprised to learn that that's broken.

If it _does_ reproduce when you click Settings again, there should be a filename and an "error code" ont he screen next to the QR code. That would be really quite helpful in figuring out what's up.

**Comment by Zagan202** [comment]
It does happen every time I click settings.
The BSOD says 
Stop code: SYSTEM_SERVICE_EXCEPTION
What failed: Ntfs.sys
This is where the QR code led me
https://support.microsoft.com/en-us/help/14238/windows-10-troubleshoot-blue-screen-errors

**Comment by DHowett-MSFT** [comment]
Whoa whoa whoa that's _really bad_.

If you go into this folder:

```
%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState
```

and double-click settings.json

... does it also explode?

I hate to keep asking you to BSOD your computer again and again ☹️

**Comment by Zagan202** [comment]
It does not blow up when I open it directly, which is what I've been doing for the past day or so because of this.

Some extra bit of info, I open JSON files with vscode instead of notepad.

**Comment by DHowett-MSFT** [comment]
Hmm. What about if you run the command (from cmd, unfortunately):

```
start %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```

That uses the same API as Terminal does.

**Comment by DHowett-MSFT** [comment]
Judging by it being in _ntfs.sys_, my first concern would be filesystem corruption. The filesystem driver should _never_ be killing the system under normal circumstances.

Any unusual third-party AV?

**Comment by Zagan202** [comment]
Running that from cmd seemed to work and I got this output
```
 [main 2020-05-01T02:54:13.829Z] update#setState idle
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:22348) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:5176) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:5176) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more `information`
```

No unusual third party AV just Avast

**Comment by zadjii-msft** [comment]
Curious, what's your default editor for `json` files? VsCode? What version are you running?

This is getting weirder and weirder

**Comment by Zagan202** [comment]
Default editor for json is `vscode`.
Version of vscode `1.44.2`
It is bizarre.

**Comment by DHowett-MSFT** [comment]
Thanks for bearing with us. I've not been able to find any followup steps here, unfortunately, and it looks like Terminal's holding the ShellExecute API correctly. Im don't think there's a path forward from this project's perspective...

Gonna tentatively resolve this one as "no-repro" since we can't get our hands on it. It looks like a filesystem issue, and perhaps a disk check will restore order. Perhaps it won't. ☹️

**Comment by cobyl** [comment]
Interesting. Have exactly same situation. How you solve that?

**Comment by Zagan202** [comment]
Unfortunately I didn't solve it.
What does your BSOD report say btw?
