### ISSUE TITLE
We can expect to running this terminal on Linux some day?

### ISSUE THREAD

**Issue by reinaldocoelho** [microsoft/terminal#5665]
# Description
This is a bealtiful terminal, we can expect to run that on other SOs in future? It can be possible?

**Comment by skyline75489** [comment]
Mostly likely not. Windows Terminal depends heavily on Windows-only technologies such as DirectX, XAML Island and WinRT. And let's be honest, we got almost too many good terminals on Linux Desktop. Gnome Terminal, Konsole, Yakuake, Tilda, just to name a few. It is Windows who needs a little terminal-wise care desperately.

**Comment by reinaldocoelho** [comment]
Great answer.
Thank you very mutch :-)
