### ISSUE TITLE
编译之后得到一个OpenConsole.exe，和 CMD完全一样

### ISSUE THREAD

**Issue by gotliuyan** [microsoft/Terminal#567]
编译之后得到一个OpenConsole.exe，和 CMD完全一样?

**Comment by Matrix-Zhang** [comment]
等正式的release吧，

**Comment by GreatV** [comment]
https://github.com/microsoft/Terminal#i-built-and-ran-the-new-terminal-but-it-looks-just-like-the-old-console-what-gives

**Comment by Robosky** [comment]
在VS里选择**CascadiaPackage**而不是**OpenConsolePackage**
![{CBE24FC2-CD99-4D72-BBEA-38823276EAFA}.png](https://storage.live.com/items/EF66CE83628B94A4!134074?authkey=AJCcVWIFLhvkvc4)

**Comment by vipwp** [comment]
> 在VS里选择**CascadiaPackage**而不是**OpenConsolePackage**
> ![{CBE24FC2-CD99-4D72-BBEA-38823276EAFA}.png](https://camo.githubusercontent.com/f952d4403e236adb28a567bcc09cb23966921607/68747470733a2f2f73746f726167652e6c6976652e636f6d2f6974656d732f45463636434538333632384239344134213133343037343f617574686b65793d414a4363565749464c68766b766334)

我vs2019，编译和运行这个都有错误，请问下你那是什么版本vs？

**Comment by bef178** [comment]
https://github.com/microsoft/Terminal#prerequisites

> If you're running VS2019, you'll also need ...

**Comment by Heyxiang** [comment]
有没有编译好的.exe文件，想下载体验下

**Comment by zadjii-msft** [comment]
OpenConsole.exe is the same thing as the old console.

"CascadiaPackage" is the project to run if you want to try the new Terminal.

There is not a compiled package available for download yet. We're hoping to start shipping preview builds in mid-June.

**Comment by archongum** [comment]
@Heyxiang UWP没有exe的，可以试一下这个？https://blog.csdn.net/c13232906050/article/details/90698772
