### ISSUE TITLE
[question] Using shemes color themes in oh-my-posh without retyping colors ?

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/terminal#5670]
Do you guys have anny idea how to make oh-my-posh themes use the shemes color shemes?
right now it seems to use the default ones.
(using ps-7)

**Comment by zadjii-msft** [comment]
Could you maybe elaborate a bit on what you're trying to achieve here? If you're using a scheme from your settings, it should apply by default to the 16-color palette that all commandline applications use within that terminal instance. 

I was under the impression that `oh-my-posh` just controlled how the prompt was displayed in powershell - it _should_ still be using colors from your colorscheme.

**Comment by NicTanghe** [comment]
That's not happening maybe oh-my-posh's fault.
if it keeps bugging me i'l reopen but can be closed 4 now.

**Comment by T-Flet** [comment]
Oh-my-posh uses a different colour type and naming convention (related Terminal scheme naming issue: https://github.com/microsoft/terminal/issues/2641).

If you look at, say, the end of the [Paradox theme](https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/Themes/Paradox.psm1), it is casts the enumeration type like this: `[ConsoleColor]::DarkBlue`.

The Terminal scheme colours do not have a `DarkBlue`, though I assumed command-line applications would just find the value specified by `blue` when looking for it (and e.g. the `brightBlue` one when looking for `[ConsoleColor]::Blue`).

On which side is the issue occurring?
