### ISSUE TITLE
Tab navigation fails with keypad

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/terminal#5676]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

WT Version 0.11.1191.0

```

# Steps to reproduce

Open multiple tabs and attempt to use the default key bindings such as `Ctrl+Alt+1` or 'Ctrl+Alt+2` using the numeric keypad on your keyboard.

# Expected behavior

I would expect the same tab switching that I get when using the number keys across the top of the keyboard.

# Actual behavior

Nothing happens. The numeric keypad functions just fine but now when used in this key combination.

**Comment by DHowett-MSFT** [comment]
So this one's pretty curious. Those keys _are actually different keys_, which we chose to not bind by default. You're free to bind them with the `numpad0` through `numpad9`.

I'd like to avoid making them "act the same" as the traditional number keys, as the expressiveness of being _able_ to choose them beats out the (in my opinion!) confusion of not.
