### ISSUE TITLE
微软要做的并不是提供一款Windows下面的Terminal

### ISSUE THREAD

**Issue by wanlinus** [microsoft/Terminal#568]
我并不关心是不是使用哪款Terminal,关心的是操作系统.,这款Terminal做得再漂亮还是运行在Windows上面,作为开发者我更倾向于在Linux下面敲命令,如果微软能够开发一款Linux, 我想比这个软件来得更实在, 既然都是开发者,那么在win下开发有多少时间是使用的cmd或者ps呢?开发这个Terminal最多还是一个华丽的壳,Shell什么的命令完全是不存在的,拿来有什么用

**Comment by Robosky** [comment]
WSL2了解一下，请不要在这里KY，这里是issue不是评论区。

**Comment by smallprogram** [comment]
Please close this Issues

**Comment by Sharpeli** [comment]
我靠，还有中文6666

**Comment by mmabluesky** [comment]
真low

**Comment by zoro96** [comment]
👎👎👎👎👎👎

**Comment by 1111chance** [comment]
又看到了高人一等的 linux 党

**Comment by UnnameBao** [comment]
话说回来了，你干嘛用windows？

**Comment by orient33** [comment]
用了linux, 就有那么多终端还不够你用??

**Comment by wanlinus** [comment]
> 话说回来了，你干嘛用windows？

我用mac

**Comment by jakara** [comment]
> > 话说回来了，你干嘛用windows？
> 
> 我用mac

还以为你是纳德拉小号呢， 指点微软的产品方向

**Comment by AmmRage** [comment]
> > 话说回来了，你干嘛用windows？
> 
> 我用mac

I think ms's priority is developing tools for windows users. 
maybe you can try join ms and become the CEO to achieve that.

这里有个闹事的。 @平安微软

**Comment by mmabluesky** [comment]
@wanlinus 
拜托WSL2了解一下吧 ， 这个issue赶紧关了 ，丢人...
还有对于国外的开源项目，提问最好英文，起码的尊重...

**Comment by LiJinyao** [comment]
If you don't know what issue is, please refer to https://guides.github.com/features/issues/#intro

**Comment by zadjii-msft** [comment]
Yea this seems pretty off-topic to me.
