### ISSUE TITLE
Procedure to use a custom profiles.json for all Active Directory profiles

### ISSUE THREAD

**Issue by lauxjpn** [microsoft/terminal#5680]
As far as I can see, the `profiles.json` file is currently located in the `AppData\Local` folder.

Wouldn't that mean, that I would need to make the same custom changes to the file on every machine I log into with the same user account, only to get the same terminal experience?

Also, there should be a simple (or at least documented) was to use the same custom `profiles.json` file for all active directory accounts (either forced or as the default but modifiable).

These both are much needed features for every administrator out there, so they don't have to tinker with the settings on every machine again, before they can do their actual tasks (like in the old `cmd.exe` days).

**Comment by DHowett-MSFT** [comment]
You're right -- it's annoying right now. We've got /dup #2933 on our backlog, though, to make this better :smile:
