### ISSUE TITLE
SSH user and host NOT showing in tab anymore after update 0.11.1191.0

### ISSUE THREAD

**Issue by arqeco** [microsoft/terminal#5685]
After updating to version 0.11.1191.0 the username and host are not anymore being displayed in the tab. I don't know what was my previous version, but It was older than 0.11.

The tab displays now only "OpenSSH SSH Client" and it's now impossible to know which tab is connected to which SSH user@host.

This is how I got ssh working in Terminal. If there's a better way please let me know. At least, you could use the profile "name" in the tab.

```
            {
		"commandline" : "ssh.exe myuser@myhost.com",
		"guid" : "{57e72a65-631a-426d-a8ba-322976884677}",
		"name" : "SSH myuser MYHOST",
                "hidden": false
            },
```
Greetings,
Márcio

**Comment by zadjii-msft** [comment]
I think you're probably missing `"suppressApplicationTitle": true` in your profile. From [the docs](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md):


`suppressApplicationTitle` | Optional | Boolean | false | When set to true, `tabTitle` overrides the default title of the tab and any title change messages from the application will be suppressed. When set to false, `tabTitle` behaves as normal.
-- | -- | -- | -- | --

I _believe_ that just setting that to true will force the Terminal to use the profile's name as the tab title.

**Comment by WSLUser** [comment]
So I actually get the opposite but with regular cmd/ps/pwsh/wsl tab. If I use ssh, the user@host will appear in the tabtitle but after I exit, it will keep it unless I ssh to something else, in which case, the tab title will then update. I can file a seperate bug for that if that's not intended behavior (probably not). It does update during the ssh session from the username to root and back if I use `sudo` and `exit`.

**Comment by DHowett-MSFT** [comment]
It’s intended behavior that _the program attached to the terminal_ gets control of the title. If the thing that’s running when SSH exits doesn’t re-assert its title, that’s on that thing. If that’s powershell, you can configure that behavior!

**Comment by arqeco** [comment]
It worked.

Please add somewhere in https://github.com/microsoft/terminal page that to use SSH in Windows Terminal you should use a profile like this. It's a hard to find information:
```
            {
		"commandline" : "ssh.exe myuser@myhost.com",
		"guid" : "{8135a039-684d-449d-b27c-e2182164c222}",
		"name" : "SSH myuser MYHOST",
		"suppressApplicationTitle": true,
                "hidden": false
            },

```
Thank you

**Comment by DHowett-MSFT** [comment]
I’d document that, but when your remote shell is set up in a stock configuration (for most distributions) it isn’t required to force the title to be different ;)

**Comment by DHowett-MSFT** [comment]
Since it looks like this thread came to a close, I'm gonna mark it question/answered. Thanks all!

**Comment by ZeppLu** [comment]
> I think you're probably missing `"suppressApplicationTitle": true` in your profile. From [the docs](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md):
> 
> `suppressApplicationTitle`	Optional	Boolean	false	When set to true, `tabTitle` overrides the default title of the tab and any title change messages from the application will be suppressed. When set to false, `tabTitle` behaves as normal.
> I _believe_ that just setting that to true will force the Terminal to use the profile's name as the tab title.

Hi, using the provided configuration can set a static tab title like `ssh user@host`. But if I want it to change dynamically according to the working directory (like `ssh user@host:/home/user/path/to/dir`), what should I do?

**Comment by zadjii-msft** [comment]
@ZeppLu If you want to include context like the current directory in your title, then it's probably easiest to configure your shell to set the title. [This guide](https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title#set-the-shells-title) might be a helpful starting place.
