### ISSUE TITLE
add keybinding to maximize/restore active pane

### ISSUE THREAD

**Issue by copdips** [microsoft/terminal#5686]
# Description of the new feature/enhancement

I would like to have a keybinding to maximize/restore the active pane. Currently, on can only maximize/restore the whole windows terminal window. 

# Proposed technical implementation details (optional)
`alt+shift+enter`
or
`alt+shift+f11`
or
`ctrl+f11`

Which keybinding is not important as I can change it later, I would just like to make the action available.

When I press the first time the keybinding, it maximizes the active pane, that I can only see the active pane.
When I press twice, it restores the active pane to its original size, and original position with other panes.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #996 for more discussion.

/dup #996
