### ISSUE TITLE
Cursor resets to legacy on text entry

### ISSUE THREAD

**Issue by grigorije** [microsoft/terminal#5688]
# Environment

Windows build number: **Microsoft Windows v.10.0.18363.778**

Windows Terminal version: **PowerShell v.1.18362.752**

**Note**: Changes have been made to the background color, font size, and scroll-forward has been disabled.

# Steps to reproduce

1. Change the cursor to a non-legacy one
2. Type something

# Expected behavior

Preferred cursor remains persistent.

# Actual behavior

Non-legacy cursor remains persistent on console (re)launch only. As soon as any characters are typed in the console, the cursor is reset to the default, legacy version.

**Comment by DHowett-MSFT** [comment]
This is with the traditional console host -- not Windows Terminal -- right?

**Comment by grigorije** [comment]
It's the regular PowerShell, if that's what you mean.

**Comment by DHowett-MSFT** [comment]
Excellent. /dup #4124

This should be out with one of the upcoming _windows_ releases. (Sorry, we can only service the inbox console so quickly. :smile:)

**Comment by grigorije** [comment]
Now to find out what 'inbox console' means... 🤔

**Comment by DHowett-MSFT** [comment]
Oh, sorry about that.

So! Powershell and CMD both use the same console window code to get their text onto the screen. It's called "conhost" (short for "console host", becuase it "hosts" the console APIs). It lives in `"c:\windows\system32\conhost.exe"`.

Inbox -- i assume you know what that one means, but I'm on a roll :smile: -- is just "things that come with the Windows OS". They get updated through Windows Update or the windows install ISO.

This repository contains the source code for the console host _and_ the new Windows Terminal (which is like the console host, but it has tabs and a lot more customization!), so we usually handle all the inbox console complaints here too. Same code, same bugs!

**Comment by zadjii-msft** [comment]
The "inbox console" is `conhost.exe`, the terminal window that you're probably used to seeing in Windows. This is the window that appears whenever you launch `cmd.exe` or `powershell.exe` directly.

`conhost` is this window:
![image](https://user-images.githubusercontent.com/18356694/80823247-ebc87580-8ba1-11ea-97d1-17066233fd53.png)

**Comment by grigorije** [comment]
Oh, wow, totally forgot about this thread. 🤔 
Yeah spent a good 30 minutes figuring out the difference between a console, terminal, and shell. 😆
