### ISSUE TITLE
The update to a new version happens silently without user consent

### ISSUE THREAD

**Issue by IustinMicu** [microsoft/terminal#5689]
# Environment
```none
Windows build number: Windows 10
Windows Terminal version: 0.11.1191.0 (currently installed)
```

# Steps to reproduce

# Expected behavior
Let the user decide when to update to a newer version or opt out from automatic updates.

# Actual behavior
The software is silently updating without user consent!
After last update there were breaking changes (1. My custom color scheme stopped working. Out of  nowhere I got black text on black background - which you can imagine is a very cool experience when you are in a hurry and need to get things done fast. 2. The syntax to overwrite shortcuts to switch to a tab by number changed, so my navigation shortcuts stopped working, hitting my productivity).
Again: Updates, especially breaking changes should not happen without user consent, otherwise this software is not reliable to be used in a production environment!
Also, I don't think it`s hard to migrate the syntax in settings.json when you do it in defaults.json (Like it happend with breaking change 2 that I mentioned earlier)! Just saying..

**Comment by DHowett-MSFT** [comment]
I'm sorry about all that. We haven't been able to get the store to stop killing us -- even when the application says "hold up, I'm in use", it gets terminated automatically. I'm in talks with the store and servicing folks about how best to handle this.

Also, I'm sorry about the one-time breaking settings change. This software really isn't _intended_ to be used in a production environment when it's a technical preview. I know that we do that, and a lot of folks are doing that, but it's like being in the Windows Insider program.

After 1.0, settings changes will come with migration.

I'm gonna close this one out with a hat tip to #5458 and /dup #3915.

Thanks for letting us know. I know it's been rough. ☹️

**Comment by DHowett-MSFT** [comment]
(The main issue is that we yanked all the code that re-wrote a user's settings file, because it was unreliable and dangerous. We didn't want to reintroduce it so late in the cycle when we were worried it would end in something worse than "my key bindings aren't working".)

**Comment by IustinMicu** [comment]
Thanks for the reply. I understand the situation.
I am glad that you are working to solve it. I hope you'll manage to find a solution before the next update.
Also, thanks for caring about the user experience even thou the terminal is still in preview.
Keep up the good work :)

**Comment by DHowett-MSFT** [comment]
> before the next update

We definitely won't before then, but we won't have any breaking settings changes in it at least 😬
