### ISSUE TITLE
Build process fails, if the source is in user directory

### ISSUE THREAD

**Issue by danisenpai** [microsoft/Terminal#569]
Step 3-5 from the Issue #489 fail, if the source folder, cloned from github, is in the user directory, e.g. `C:\Users\user\Terminal`

More specific, the `xcopy` command fails.

![grafik](https://user-images.githubusercontent.com/33071778/57358620-20177a80-7176-11e9-8b77-27e087665533.png)

A solution is to move the source folder to another location.

`Windows Build Version: 17763.437`

**Comment by zadjii-msft** [comment]
This is #507
