### ISSUE TITLE
Crash on new tab/split

### ISSUE THREAD

**Issue by schleumer** [microsoft/terminal#5697]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

Windows Terminal 0.11.1191.0

# Steps to reproduce

With version v0.11.1121.0 or greater.

Create a new tab via CTRL+SHIFT+T or splitting ALT+SHIFT+(plus/minus), with any kind of terminal, cmd, powershell or wsl.

# Expected behavior

Do not crash.

# Actual behavior

It crashes. Before crash, terminal screen becomes black with no output.

**Comment by schleumer** [comment]
https://aka.ms/AA8b4qo

**Comment by DHowett-MSFT** [comment]
It appears as though Terminal is crashing because of something called "RivaTuner". When using hook libraries that load themselves into other applications, you're taking the stability of applications into your own hands.

**Comment by valentinmk** [comment]
Same is here
Exiting MSI Afterburner software fixes crashing terminal on a new tab.

**Comment by KidesLeo** [comment]
Fixed mine too. Thanks.

**Comment by scorsy63** [comment]
I had no idea MSI Afterburner/Riva Tuner was causing the crashes.  To fix the issue without having to close MSI/Riva Tuner -

Open Riva Tuner, click the "Add" button at the bottom left corner, to add new profile properties.

Find Windows Terminal in "C:\Program Files\WindowsApps"

There might be older versions of WindowsTerminal in there, make sure to open the current version you're using.

There's 4 .exe files inside, open each one and set "Application detection level" to "None".

**Comment by FM1337** [comment]
> I had no idea MSI Afterburner/Riva Tuner was causing the crashes. To fix the issue without having to close MSI/Riva Tuner -
> 
> Open Riva Tuner, click the "Add" button at the bottom left corner, to add new profile properties.
> 
> Find Windows Terminal in "C:\Program Files\WindowsApps"
> 
> There might be older versions of WindowsTerminal in there, make sure to open the current version you're using.
> 
> There's 4 .exe files inside, open each one and set "Application detection level" to "None".

Thanks mate, this was driving me bonkers, I had to open up a new terminal window each time I wanted to use the terminal because it would literally crash on each new tab.
