### ISSUE TITLE
Acrylic background does not work

### ISSUE THREAD

**Issue by easypickings** [microsoft/terminal#5698]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.18363.815]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software?
```

# Steps to reproduce

Just open the terminal

# Expected behavior

The window should have an acrylic background. I already set `"useAcrylic": true` in `settings.json`, as shown below:

```json
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "initialRows": 30,
    "initialCols": 120,
    "alwaysShowTabs": true,
    "showTerminalTitleInTitlebar": true,
    "experimental_showTabsInTitlebar": true,
    "confirmCloseAllTabs": false,
    "profiles": {
        "defaults": {
            // Put settings here that you want to apply to all profiles
            "historySize": 9001,
            "snapOnInput": true,
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Source Code Pro",
            "fontSize": 12,
            "useAcrylic": true,
            "acrylicOpacity": 0.75,
            "closeOnExit": true,
            "padding": "8, 8, 8, 8",
            "startingDirectory": "."
        },
        "list": [
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false,
                "colorScheme": "Campbell"
            },
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
                "colorScheme": "Solarized Dark"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "colorScheme": "UbuntuLegit",
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "guid": "{9686caab-6b01-46c8-9091-35b3ea8e410c}",
                "hidden": false,
                "name": "Jupyter Notebook",
                "commandline": "jupyter notebook",
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    // Add custom color schemes to this array
    "schemes": [
        {
            "name": "Campbell",
            "foreground": "#F2F2F2",
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#C50F1F",
            "brightBlack": "#13A10E",
            "brightBlue": "#C19C00",
            "brightCyan": "#0037DA",
            "brightGreen": "#881798",
            "brightPurple": "#3A96DD",
            "brightRed": "#CCCCCC",
            "brightWhite": "#767676",
            "brightYellow": "#E74856",
            "cyan": "#16C60C",
            "green": "#F9F1A5",
            "purple": "#3B78FF",
            "red": "#B4009E",
            "white": "#61D6D6",
            "yellow": "#F2F2F2"
        },
        {
            "name": "Solarized Dark",
            "foreground": "#FDF6E3",
            "background": "#073642",
            "black": "#073642",
            "blue": "#D30102",
            "brightBlack": "#859900",
            "brightBlue": "#B58900",
            "brightCyan": "#268BD2",
            "brightGreen": "#D33682",
            "brightPurple": "#2AA198",
            "brightRed": "#EEE8D5",
            "brightWhite": "#002B36",
            "brightYellow": "#CB4B16",
            "cyan": "#586E75",
            "green": "#657B83",
            "purple": "#839496",
            "red": "#6C71C4",
            "white": "#93A1A1",
            "yellow": "#FDF6E3"
        },
        {
            "name": "Solarized Light",
            "foreground": "#073642",
            "background": "#FDF6E3",
            "black": "#073642",
            "blue": "#D30102",
            "brightBlack": "#859900",
            "brightBlue": "#B58900",
            "brightCyan": "#268BD2",
            "brightGreen": "#D33682",
            "brightPurple": "#2AA198",
            "brightRed": "#EEE8D5",
            "brightWhite": "#002B36",
            "brightYellow": "#CB4B16",
            "cyan": "#586E75",
            "green": "#657B83",
            "purple": "#839496",
            "red": "#6C71C4",
            "white": "#93A1A1",
            "yellow": "#FDF6E3"
        },
        {
            "name": "Ubuntu",
            "foreground": "#EEEEEC",
            "background": "#2C001E",
            "black": "#EEEEEC",
            "blue": "#16C60C",
            "brightBlack": "#729FCF",
            "brightBlue": "#B58900",
            "brightCyan": "#268BD2",
            "brightGreen": "#D33682",
            "brightPurple": "#2AA198",
            "brightRed": "#EEE8D5",
            "brightWhite": "#002B36",
            "brightYellow": "#CB4B16",
            "cyan": "#586E75",
            "green": "#657B83",
            "purple": "#839496",
            "red": "#6C71C4",
            "white": "#93A1A1",
            "yellow": "#FDF6E3"
        },
        {
            "name": "UbuntuLegit",
            "foreground": "#EEEEEE",
            "background": "#2C001E",
            "black": "#4E9A06",
            "blue": "#CC0000",
            "brightBlack": "#729FCF",
            "brightBlue": "#C4A000",
            "brightCyan": "#3465A4",
            "brightGreen": "#75507B",
            "brightPurple": "#06989A",
            "brightRed": "#D3D7CF",
            "brightWhite": "#555753",
            "brightYellow": "#EF2929",
            "cyan": "#8AE234",
            "green": "#FCE94F",
            "purple": "#729FCF",
            "red": "#AD7FA8",
            "white": "#34E2E2",
            "yellow": "#EEEEEE"
        }
    ],
    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
```

# Actual behavior

The window has a black plain background
![snapshot](https://user-images.githubusercontent.com/56877655/80853241-aff4e500-8c61-11ea-938e-46d6e9938770.png)

**Comment by zadjii-msft** [comment]
Does acrylic work in the "Calculator" app, and _not_ in the Terminal? There are lots of things in the OS that actually control whether acrylic works or not.

**Comment by easypickings** [comment]
> Does acrylic work in the "Calculator" app, and _not_ in the Terminal? There are lots of things in the OS that actually control whether acrylic works or not.

Hmm...somehow it works again today. Anyway thank you!

**Comment by StevenLi-DS** [comment]
I ran into the same issue with `1.0.1401.0` and my OS doesn't seem to have acrylic effect either. Is there any way to fix it?

**Comment by easypickings** [comment]
> I ran into the same issue with `1.0.1401.0` and my OS doesn't seem to have acrylic effect either. Is there any way to fix it?

Hmm... Now my terminal losses acrylic effect from time to time again... Wish someone could figure out the bug and fix it :(

**Comment by VincentJoshuaET** [comment]
Same issue.

**Comment by zadjii-msft** [comment]
There are lots of things that control whether acrylic is enabled or not - one of the more subtle ones is acrylic will often get disabled by the OS when the PC is in power saver mode, or is on battery. I forget the exact details of how that works. @easypickings could you check if the acrylic is going away when you're on battery (or low battery)?

[This is a source ](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#transient-surfaces)that might shed some light
> Acrylic effects are automatically disabled when devices enter Battery Saver mode, and users can disable acrylic effects for all apps, if they choose.

**Comment by easypickings** [comment]
> There are lots of things that control whether acrylic is enabled or not - one of the more subtle ones is acrylic will often get disabled by the OS when the PC is in power saver mode, or is on battery. I forget the exact details of how that works. @easypickings could you check if the acrylic is going away when you're on battery (or low battery)?
> 
> [This is a source ](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#transient-surfaces)that might shed some light
> 
> > Acrylic effects are automatically disabled when devices enter Battery Saver mode, and users can disable acrylic effects for all apps, if they choose.

I've been using PC with power plugged in and the PC is not in power saver mode. However the acrylic just doesn't work.

**Comment by zadjii-msft** [comment]
To reiterate a previous question - does acrylic not work for other apps, like the Calculator, or does it only not work in the Terminal?
![image](https://user-images.githubusercontent.com/18356694/82672358-e345e680-9c05-11ea-8e3e-25b33ef1fd81.png)

**Comment by easypickings** [comment]
It seems the Calculator has a plain appearance too.
![image](https://user-images.githubusercontent.com/56877655/82675453-66535500-9c77-11ea-8f04-6d6d723a5c2c.png)

**Comment by VincentJoshuaET** [comment]
Are you using Fast Ring builds?

**Comment by easypickings** [comment]
Nope. Stay in stable build

**Comment by zadjii-msft** [comment]
@easypickings what about the following setting?
![image](https://user-images.githubusercontent.com/18356694/82680850-7edd5400-9c12-11ea-823c-c7afacb08cf8.png)


Or by any chance, are you using remote desktop or something similar to connect to the machine?

**Comment by StevenLi-DS** [comment]
@zadjii-msft tried that before posting... it doesn't work... sadly...

**Comment by easypickings** [comment]
@zadjii-msft Transparency effects are on. Not using remote desktop.

**Comment by easypickings** [comment]
I happened to solve this problem by edit the registry:

1. open regedit and locate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced`
2. add an new DWORD value named `UseOLEDTaskbar Transparency` and set value to `1`

Hope it could help 😃

**Comment by Karl-WE** [comment]
> I happened to solve this problem by edit the registry:
> 
> 1. open regedit and locate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced`
> 2. add a new DWORD value named `UseOLEDTaskbar Transparency` and set value to `1`
> 
> Hope it could help

There is an ADMX GPO for that, so no reghack needed.

**Comment by sentakuhm** [comment]
if you have forced enabling Clear Acrylic Taskbar Transparency you'll get this issue, the same thing happened with me i just disabled it and terminal Acrylic works again.

if you want disable Clear Acrylic Taskbar Transparency save in registry file with name: Turn_Off_clear_acrylic_taskbar_transparency.reg the following settings

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"UseOLEDTaskbarTransparency"=-

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"ForceEffectMode"=-
```
double click to run it, after that reboot.

**Comment by Karl-WE** [comment]
I dislike reghack, please use ADMX or settings app to set the correct option.
Just posted similar quite a second ago

**Comment by zadjii-msft** [comment]
Okay, since you seemed to find a solution, I'm gonna close this one for now. I have no idea why that works for you, or why nothing else seemed to work, but I'm glad you found a solution!
