### ISSUE TITLE
Support Mouse Vanish (Hide pointer while typing)

### ISSUE THREAD

**Issue by gfody** [microsoft/terminal#5699]
If the pointer is over the terminal window then hide it on any non-control keydown event, and restore it on the next mousemove event. But only when `SystemParametersInfo(SPI_GETMOUSEVANISH) == true`.

**Comment by DHowett-MSFT** [comment]
This is an _excellent_ feature request. It might also be tied up with the cursor visibility work in #5028. I’ll mark this one Help Wanted: if you want to work on it, feel free!
