### ISSUE TITLE
The text is disappear when I resize the window to minimum

### ISSUE THREAD

**Issue by kasuganosoras** [microsoft/terminal#570]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  10.0.18362.30

* What you're doing and what's happening: Resize the terminal window to minimum, then resize the window to normal, the text will disappear.

### The normal window size
![img](https://i.natfrp.org/254f7e3405c3fe9141a218ddd2fc922c.png)
### Resize it to minimum
![img](https://i.natfrp.org/5384f0555e0b9e02e44be6eb83c6df06.png)
### Then resize to normal, the text disappear
![img](https://i.natfrp.org/4cc59d090c602c86a562602d61664fee.png)
### Scroll up the window
![img](https://i.natfrp.org/1d7f6a2fbc2b6756979292e0448f0a28.png)

* What's wrong / what should be happening instead: I don't know. Is this a bug?

**Comment by zadjii-msft** [comment]
Yea, I think resizing is a little funky right now.

Part of this has to do with how conpty deals with resizing, by repainting the window. So that's why there seems to be multiple `Microsoft Wi` bits.

I also don't think the new terminal is resizing with refolw currently, which is why the terminal seems to lose any of the old output.

There's definitely work to do in this space to make the experience more fluid.

**Comment by zadjii-msft** [comment]
Hey so this particular issue has maybe not aged so well - the screenshots are all broken, at least for me. I'm tracking a bunch of these issues that have since gotten their own threads over in #4200, so I'm going to just blanket close this as a duplicate of that thread.

/dup #4200

thanks!
