### ISSUE TITLE
Newly installed Windows Terminal - error 0xd000003a when launching powershell.exe

### ISSUE THREAD

**Issue by jozefizso** [microsoft/terminal#5701]
# Environment

```none
Windows build number: Windows 10.0.18363.778
Windows Terminal version: 0.11.1191.0

Any other software?
No, this is a clean installation of Windows 10
```

# Steps to reproduce

1. Install new Windows 10 Professional 1909 64-bit
2. Open Microsoft Store, search fro Windows Terminal
3. Install Windows Terminal
4. Run Windows Terminal from Start menu

# Expected behavior

Windows Terminal should run the first time correctly.

# Actual behavior

Error message is displayed: **[error 0xd000003a] when launching `powershell.exe']**

![image](https://user-images.githubusercontent.com/287778/80860413-caca5800-8c67-11ea-9eeb-d6532cb74e53.png)

**Comment by DHowett-MSFT** [comment]
/dup #4750

This seems to happen in virtual machines more often than on real ones. You can work around it by launching a normal console application before launching Terminal. This should only be necessary one time.

**Comment by jozefizso** [comment]
Yes, this was a VM.

**Comment by genteelmagpie** [comment]
I am not using it in a virtual machine. Just installed a clean windows from microsoft.com and I am getting the same error. Any ideas how to fix it ?

**Comment by svovel** [comment]
I just got this issue now. Pretty fresh win10 VM in HyperV.
All was working fine, but after a reboot I got the 0xd000003a error when starting windows terminal with powershell 7 or cmd.
Starting powershell directly works and I'm then able to start windows terminal, but if I reboot I gotta do it all over again.

**Comment by bolte-io** [comment]
Same here on the preview, loading it manually before opening terminal works.
Not on a VM, on latest 21H1 build of W10.

**Comment by bilogic** [comment]
> Not on a VM, on latest 21H1 build of W10.

Yes, I'm facing this on 21H1 too, this is regression.

**Comment by bibinsyamnath** [comment]
just repair with powershell core installer. it worked for me :)

**Comment by teknoraver** [comment]
I have the same on a fresh VM install, with latest terminal

**Comment by rayleigh1990** [comment]
I have the same on a fresh physical machine install, with latest terminal 1.17.11461.0
after startup windows , this problem appears
but after wait for about 5 minutes later , this problem disappear
