### ISSUE TITLE
Did as you suggested, I removed all content in settings.json; now it fails

### ISSUE THREAD

**Issue by rfalanga** [microsoft/terminal#5702]
# Environment  10.0.18362.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software? None
```

# Steps to reproduce

I did as your instructions said to do: 
"Or **even better**, make a backup of your settings file, and delete the contents entirely. We'll re-generate the file with some better formatting and more sane defaults, and you can copy the modifications you want back in."

I edited the settings.json file. I removed everything, but the opening and closing braces.

# Expected behavior

I was expecting Windows Terminal to rebuild my settings.json file, once I closed and reopened Windows Terminal.

# Actual behavior

After closing Windows Terminal and reopening it, I immediately got this error:

"Encountered errors while loading user settings

The 'globals' property is deprecated - your settings might need updating."

I reopened the settings.json file. There is no 'globals' property. All that's in there is this:

{

}

Kinda lost as to what it thinks is a global property when I can't see it.

**Comment by Domain** [comment]
Maybe you should delete the settings.json file.

**Comment by rfalanga** [comment]
I cleared out even the braces. Once I did that, suddenly new code appeared. It surprised me, but that seems to have fixed it.
