### ISSUE TITLE
Background image does not display with antialiasingMode = cleartype

### ISSUE THREAD

**Issue by encladeus** [microsoft/terminal#5703]
# Environment

```none
Windows build number: [10.0.18363.778]
Windows Terminal version (if applicable): unreleased master 44689b93

Any other software? No
```

# Steps to reproduce

Create a profile with a background image and uses "antialiasingMode": "cleartype" + "useAcrylic": false

This is probably related to #5277, but is this the intended behavior? 

Profile used is attached:
[settings.zip](https://github.com/microsoft/terminal/files/4567793/settings.zip)

# Expected behavior
![ok](https://user-images.githubusercontent.com/8571098/80865504-d296f600-8c81-11ea-87bd-3c6c4175e89e.jpg)

# Actual behavior

![nok](https://user-images.githubusercontent.com/8571098/80865507-d75baa00-8c81-11ea-9f4e-0cd51477cecc.jpg)

**Comment by encladeus** [comment]
I realize that #CCC is not a great choice of background color, but just choose it to illustrate the issue.

**Comment by zadjii-msft** [comment]
Wow that looks bad 😦

That should probably not happen, we should probably fall back to grayscale if the user's using a background image, for a bunch of the same reasons as in #5277

**Comment by SWB2** [comment]
This issue just appeared appeared for me with the v0.11.1251.0 release candidate released to the Store today. The previous Store version worked fine with ClearType and a background image.

**Comment by Milly** [comment]
for search words:
backgroundImage + antialiasingMode + cleartype

**Comment by plainee** [comment]
it's not fixed for more than one year. 👎
