### ISSUE TITLE
Cannot select text when using SSH on powershell 7.0

### ISSUE THREAD

**Issue by w93163red** [microsoft/terminal#5704]
# Environment

```none
Windows build number:  10.0.18363.0
Windows Terminal version (if applicable): 0.11.1191.0

```

# Steps to reproduce

Using tmux with oh-my-tmux, cannot select/copy the text

# Expected behavior

be able to select text in terminal

# Actual behavior

When I use my mouse to select text, it does not work.

**Comment by DHowett-MSFT** [comment]
This will only happen if some application in the middle (tmux?) asks for the terminal to enter "mouse mode" -- where the terminal tells the application about mouse clicks. SSH 7.7 doesn't support it, but it still "asks".

Temporary workaround: disable mouse mode in tmux or vim if you're using it
Temporary workaround: disable mouse mode by holding down <kbd>shift</kbd> while selecting.
