### ISSUE TITLE
Crash when Ctrl + Scroll

### ISSUE THREAD

**Issue by autoantwort** [microsoft/terminal#5707]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.208]
Windows Terminal version (if applicable): 0.11.1191.0 (when you view it at Download and Updates in the Store)

Any other software?
I use Windows from a mac with remote desktop
```

# Steps to reproduce
1. Open Windows Terminal
2. Holt `ctrl` and scroll (maybe fast) to make the font smaller

![windows terminal crash](https://user-images.githubusercontent.com/41973254/80894562-4b2aa080-8cdc-11ea-9ef8-0c482d52a40d.gif)

# Expected behavior
No crash / stops at a very smal font

# Actual behavior
Crash  
Maybe this is a future. If you want such a small front is it the same as closing the terminal ;)

**Comment by autoantwort** [comment]
> If this is an application crash, please also provide a Feedback Hub submission link so we can find your diagnostic data on the backend. Use the category "Apps > Windows Terminal (Preview)" and choose "Share My Feedback" after submission to get the link.
Where is the "Apps > Windows Terminal (Preview)" Option? In the Feedback Hub App: No, In the Settings: No, In the Windows Terminal: No ?

**Comment by autoantwort** [comment]
https://aka.ms/AA8b8qy

**Comment by letmaik** [comment]
Duplicate of https://github.com/microsoft/terminal/issues/5479. And it's already fixed.
