### ISSUE TITLE
Don't scroll while backscrolling

### ISSUE THREAD

**Issue by autoantwort** [microsoft/terminal#5710]
# Description of the new feature/enhancement
When I backscroll and new output is generated, the terminal should not scroll, otherwise is it nearly impossible to select something.

![windows terminal select](https://user-images.githubusercontent.com/41973254/80895419-18d17100-8ce5-11ea-9e1e-da056892d7e2.gif)

# Proposed technical implementation details
Here is an example to macOS Terminals does it:

![mac terminal](https://user-images.githubusercontent.com/41973254/80895458-59c98580-8ce5-11ea-86b8-869abb512452.gif)

**Comment by j4james** [comment]
I think this is probably covered by issue #980. See also the _SnapOnOutput_ spec in PR #2529.

**Comment by autoantwort** [comment]
I think it is a bit different: I do not want scrolling at all when I scroll scroll upwards and new output is generated, like in the macOS terminal. There I can scroll to the top and read the text without selecting anything while new output is generated. This is currently not possible with Windows Terminal

**Comment by j4james** [comment]
Issue #3863 is possibly closer to what you're asking for then. But either way, it's going to need to be part of a more general solution, and that's what the _SnapOnOuput_ spec is meant to be defining.

**Comment by autoantwort** [comment]
Yeah this issue is a duplicate of #3863. I want the behavior described in #3863.

**Comment by autoantwort** [comment]
Duplicate of #3863
