### ISSUE TITLE
How do I open newTab and splitPane same as current directory?

### ISSUE THREAD

**Issue by Dibbyo456** [microsoft/terminal#5715]
```
...

"keybindings": [
    {
        "command": "newTab",
        "keys": ["ctrl+t"]
    },
    {
        "keys": ["ctrl+p"],
        "command": {
            "action": "splitPane",
            "split": "vertical",
            "splitMode": "duplicate"
        }
    }
]
```
For example: Let's say I'm currently on `C:\Users\HARRY\Desktop` when I press `ctrl+t` or `ctrl+p` it changes the directory to `C:\Users\HARRY` I would like to open new tab or pane same as the directory the command was invoked (`C:\Users\HARRY\Desktop`)

I know this settings can be configured using `startingDirectory` parameter but how do I configure it to open same directory the command was invoked?

**Comment by DHowett-MSFT** [comment]
Thanks for the request! Right now this isn't possible. /dup #3158
