### ISSUE TITLE
ColorTool does not work on Linux distributions

### ISSUE THREAD

**Issue by Aylexx** [microsoft/terminal#5718]
**ColorTool** does not work on **Linux distributions**.

**- Windows Terminal Version: 0.11.1191.0**

**- Microsoft Windows [Version 10.0.18363.815]**

**Comment by DHowett-MSFT** [comment]
What happens? How are you running it?

**Comment by Aylexx** [comment]
When running `ColorTool.exe SCHEMENAME` without extension, there is no problem.
But when I run ColorTool.exe SCHEMENAME.EXTENSION with extension, an error occurs. 
@DHowett

**Comment by Aylexx** [comment]
Sorry for the late answer

**Comment by DHowett** [comment]
> Sorry for the late answer

No need to apologize!

**Comment by DHowett-MSFT** [comment]
Thanks for the info! Looks like this is a /dupe of #5326.
