### ISSUE TITLE
`exit` doesn't close the window

### ISSUE THREAD

**Issue by pavlkara1** [microsoft/Terminal#572]
* Windows build number:  10.0.18362.30

* What you're doing and what's happening: When having one tab (no matter what type of terminal used) open and type `exit`, the terminal doesn't close and the cursor just blinks. However, when having more than one tabs open, the terminal tab closes just fine. 

* What's wrong / what should be happening instead: When typing `exit` in the last tab, the Windows Terminal should close alongside the open tab.

**Comment by bef178** [comment]
#460

**Comment by pavlkara1** [comment]
Closing as duplicate
