### ISSUE TITLE
In Light mode, it is recommended to remove or improve the white border. This seems too coordinated. Also allow custom fonts and background colors? Can the CMD window be opened by default?

### ISSUE THREAD

**Issue by 395053994** [microsoft/terminal#5721]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

In Light mode, it is recommended to remove or improve the white border. This seems too coordinated.
Also allow custom fonts and background colors? Can the CMD window be opened by default?
Light 模式下建议将白色边框去除或改进，这个看起太协调了，
另外可以允许自定义字体和背景色？可以自定义默认开启CMD窗口吗？

![image](https://user-images.githubusercontent.com/27546390/80920535-1df4f580-8da3-11ea-87d5-94a1015f1b34.png)
windows10 64

**Comment by 395053994** [comment]
Look too ugly
外观太丑了

**Comment by DHowett-MSFT** [comment]
> In Light mode, it is recommended to remove or improve the white border. This seems too coordinated.

You can change the border color across all of Windows in the Personalization settings.

![image](https://user-images.githubusercontent.com/14316954/80925011-519f3380-8d41-11ea-8dd5-e60dadff2388.png)

![image](https://user-images.githubusercontent.com/14316954/80925013-549a2400-8d41-11ea-897c-0f9fde6d02da.png)


> Also allow custom fonts and background colors?

You can set any color scheme you want in the **Settings** file. You can set any `fontFace` you want in the **Settings** file.

> Can the CMD window be opened by default?

You can set any "default profile" you want in the **settings** file.

**Comment by 395053994** [comment]
Although it can be achieved more, but it is not very aspect, should not be bundled with the system




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dustin L. Howett (MSFT)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月4日(星期一) 凌晨4:24
收件人:&nbsp;"microsoft/terminal"<terminal@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/terminal] In Light mode, it is recommended to remove or improve the white border. This seems too coordinated. Also allow custom fonts and background colors? Can the CMD window be opened by default? (#5721)





  
In Light mode, it is recommended to remove or improve the white border. This seems too coordinated.
  
You can change the border color across all of Windows in the Personalization settings.
 

 

  
Also allow custom fonts and background colors?
  
You can set any color scheme you want in the Settings file. You can set any fontFace you want in the Settings file.
  
Can the CMD window be opened by default?
  
You can set any "default profile" you want in the settings file.
