### ISSUE TITLE
Run As Admin doesn't work - twice elevation prompt end with executable not found

### ISSUE THREAD

**Issue by Sarafian** [microsoft/terminal#5723]
# Environment

```none

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

Member of Windows Insider Program on slow ring

```none
Windows Terminal (Preview)
Version: 0.9.433.0
```

My logged in user is not admin and when I "Run As Admin" i try to run with a local admin user.

# Steps to reproduce

From anywhere, run as the **Windows Terminal** as administrator.

1. First elevated request for admin password (mention Unknown Program)
1. First elevated request for admin password (mention Unknown Program)

# Expected behavior

I would expect all tabs to be in admin mode

# Actual behavior

Popup error

```none
Windows cannot find "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.9.433.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe" ...
```

Actually in the popup the highlights segment of the path x64__8we**kyb3d8bbwe** is replaced with `...`.

# Extra notes

There seems to be some sort of weird behavior when one Windows Terminal is already open and you try to lunch one as admin. 
- The task bar icon (Pin to Taskbar) is removed.
- The admin password happens only once.

This flow used to work in the past. Then it got broken. Then worked again but for 2020 as far as I remember hadn't. Take my dates with a grain of salt. I don't have version numbers unfortunately but I thought this could be useful

**Comment by DHowett-MSFT** [comment]
> Windows Terminal (Preview)
> Version: 0.9.433.0

You're using a very old version.

If you are trying to run as a _different_ user, this is going to be a /dup of #4217.
