### ISSUE TITLE
Window controls and mouse stop working when moving the terminal to an external monitor

### ISSUE THREAD

**Issue by threkk** [microsoft/terminal#5724]
# Environment

```none
Windows build number: Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable) :0.11.1191.0

Any other software?
```

# Steps to reproduce
Open terminal or move an existing terminal window to an external monitor.

# Expected behaviour vs actual behaviour
When I open the terminal in my laptop's screen, it works: I can click on minimise, maximise, new tab, etc. Once I move it to my external monitor, all the buttons become unresponsive. I cannot maximise, close, create a new tab, etc until I move it to my laptop's screen. However, key bindings, moving the window or resizing the window still works.

**Comment by DHowett-MSFT** [comment]
Are you using PowerToys?

**Comment by threkk** [comment]
Yes! I forgot to mention it! I am running PowerToys 0.16.0 It has exactly the same issue as Terminal. Once I closed it, everything worked as expected. Should I report this bug on the Power Toys repository?

**Comment by DHowett-MSFT** [comment]
That would be great. We also have /dup #3325 on our side tracking this :smile:

**Comment by threkk** [comment]
Update: this is not happening if I am running PowerToys 0.17.0 Whatever it was, on the latest version does not happen, so I guess everything is good :)

**Comment by DHowett-MSFT** [comment]
That's great!

**Comment by itsjef** [comment]
Mine is exactly opposite! Window control and mouse only work in an external monitor. The issue disappeared after upgrading to PowerToys 0.17.0
