### ISSUE TITLE
It is no longer working with .cmd files

### ISSUE THREAD

**Issue by Kaponyt** [microsoft/terminal#5725]
# Environment

```none
wt "# Development 3 dev.cmd"; split-pane -V "# Development 2 wds.cmd"; split-pane -H "# Development 1 ts-watch.cmd"
```
And 3 .cmd files:
![image](https://user-images.githubusercontent.com/55726043/80925376-a9e82c80-8d65-11ea-9549-77dd199383ac.png)

# Steps to reproduce

A few weeks ago I spent a lot of time trying to run commands ready to split windows, I tried hard to put the commands in the WT command itself, but the only way I could do it was by calling external command files, and now neither method is working

# Expected behavior

I had taken a print when it worked, it looked like this:
![image](https://user-images.githubusercontent.com/55726043/80925459-43afd980-8d66-11ea-8f9b-d8ce72013484.png)
It was making my life a lot easier, I was full of open terminals before.

# Actual behavior

![image](https://user-images.githubusercontent.com/55726043/80925387-b2406780-8d65-11ea-86b1-1152259d8274.png)

Translation of errors:
```none
'"# Development 3 dev.cmd"' is not recognized as an internal command
or external, an operable program or a batch file.
[case closed with code 1]
```

**Comment by DHowett-MSFT** [comment]
It looks like the starting directory is not being set to the folder that contains the batch files. It would be best to make sure that the batch files can be accessed without an absolute path, or provide the path in the script.

The script is fragile and will break when the environment changes slightly without absolute paths.

**Comment by Kaponyt** [comment]
But they are all in the same folder, I tried to add ". \", "\" At the beginning but it still doesn't work, how can i correctly call the files to run?
