### ISSUE TITLE
Ubuntu Folder Color in changing screen size

### ISSUE THREAD

**Issue by NIL-zhuang** [microsoft/terminal#5726]
# Environment

```none
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

Windows10 1909 OS 18363.778

Windows Terminal(Preview) 0.11.1191.0
```

# Steps to reproduce

1. type in wsl in the terminal to start wsl
2. go to root where we have tmp, usr folders etc (forgive me for not familiar with linux)
3. ls -l to see all the folders, where tmp should be colored green
4. change folder size,and the green line would fulfill the whole line

# Expected behavior

just the same as usual

# Actual behavior

the green block which should only color tmp change into a line

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually one of the oldest bugs in the console, and already being tracked by another issue on our repo - please refer to #32 for more discussion.

/dup #32
