### ISSUE TITLE
[Feature-request] Minimize to tray

### ISSUE THREAD

**Issue by manojvignesh** [microsoft/terminal#5727]
# Description of the new feature/enhancement
Add an option to minimize to tray instead of task bar.
It can be a setting when enabled, always minimize the terminal to tray.
I also like the option in cmder where right click on close minimizes to tray in that way i have both the minimize to tray and taskbar available to me always.
It need not be exactly like right click on close button, it can be a shortcut too.

On reopening of terminal minimized to tray:
It'd be good if opening of terminal from taskbar icon reopen the minimized instance of terminal and not a new one. Though i can work around it using the win + b shortcut.

**Comment by zadjii-msft** [comment]
This is an entirely reasonable feature request, one that would probably mix well with #653 and #5000. Thanks!

**Comment by NicTanghe** [comment]
Anny ita on picking this up ?
like in about how manny releases focus can shift to include this HQ feature.

**Comment by NicTanghe** [comment]
Anny ita on picking this up ? 
this also mixes well with having 0 ui if you add a hotkey to this.

**Comment by zadjii-msft** [comment]
@NicTanghe Nope, no ETA, as indicated by the milestone of this issue:
![image](https://user-images.githubusercontent.com/18356694/83152760-cad14280-a0c3-11ea-9ce7-70cfc514fdbd.png)

**Comment by NeuroAssassin** [comment]
Interested in this as well, as I usually have a lot of windows open and it'd be nice to move this one out of the way.

**Comment by Hlsgs** [comment]
> 
> 
> This is why I am still using cmder instead of windows terminal. If they add it I will switch to Windows Terminal

Thanks for the `cmder` tip, just got into that, and now I can concur: not giving MS Terminal the time of day until it supports this.

**Comment by zadjii-msft** [comment]
@Hlsgs That's not really a constructive comment now, is it? 

This thumbs up button:
![image](https://user-images.githubusercontent.com/18356694/91449505-d3f7ba00-e840-11ea-9e8b-43550430f2cc.png)
Is a perfectly good way of showing your support for this issue without pinging everyone on the thread with negative vibes.

**Comment by Hlsgs** [comment]
> 
> 
> @Hlsgs That's not really a constructive comment now, is it?
> 
> This thumbs up button:
> ![image](https://user-images.githubusercontent.com/18356694/91449505-d3f7ba00-e840-11ea-9e8b-43550430f2cc.png)
> Is a perfectly good way of showing your support for this issue without pinging everyone on the thread with negative vibes.

You're absolutely right. Sorry about that, I got carried away.

**Comment by DAud-IcI** [comment]
Would it be okay to add a minimize to tray button at the bottom of the New Tab dropdown menu? That would make the feature (and the hotkey) intuitively discoverable as opposed to the right click on close idea which feels like a secret if you don't already come from a cmder background and expect it.


>It'd be good if opening of terminal from taskbar icon reopen the minimized instance of terminal and not a new one.

I think that's covered separately by single instance mode (#2227).

**Comment by Mystik01** [comment]
If I could upvote this i would

**Comment by DHowett** [comment]
@Mystik01 other folks appear to have figured out how to upvote issue comments 

![DD59F8CB-6F99-446F-BAF3-16C3AE3F1E62](https://user-images.githubusercontent.com/189190/99887142-9f548e00-2bf6-11eb-90cb-bf7b27da739b.jpeg)

Please use that.

**Comment by NicTanghe** [comment]
How is this just backlog ...
ps.
PLZ dont just make the feature minimize to tray but also add a keyboard shortcut to open and close the window.

**Comment by levicki** [comment]
If this gets implemented please consider not breaking standard UI behavior by introducing stuff like right-click on close button but instead use minimize so it can be done using keyboard shortcuts as well.

**Comment by juventus18** [comment]
I'm using https://github.com/flyingpie/windows-terminal-quake to put WT in the tray instead of taskbar

**Comment by orcmid** [comment]
I'm a little concerned how this interacts with there being multiple terminal sessions (not tabbed), as when some app launches wired to a (new) terminal instance.

**Comment by WSLUser** [comment]
The logic for the tray icon will have to be updated to be smart enough to know when a new window is opened while the tray icon exists for another window and a user decides to minimize that one too, otherwise that window should be ignored.  It should also provide the choices to summon a specific window or all windows (we'll need to be careful here as it could cause a large perf impact trying to restore potentially a bunch of windows and ensure they're summoned in a way to keeps resources down as much as possible).

**Comment by orcmid** [comment]
@WSLUser the task bar already handles the multiple instance case quite nicely, and indicates when there are running instances.  I suspect we are asking too much of the tray, which regularly hides some instances it is keeping hot (like Discord which I can't keep from going to the tray).

**Comment by WSLUser** [comment]
Well there are a great many applications where what I've described occurs, usually with some kind of perf cost that can cause the machine (or monitor at least) to freeze up for a moment.
