### ISSUE TITLE
shortcut "alt-1" "alt-2" "alt-3" should change active tab

### ISSUE THREAD

**Issue by bef178** [microsoft/Terminal#573]
Shortcut "alt-1" "alt-2" "alt-3" should change active tab.
Shortcut to switch tab really improve productivity and those keys are defaulted in Linux terminal.

**Comment by coldiron** [comment]
> those keys are defaulted in Linux terminal


This strongly depends upon which terminal app you're using.

**Comment by zadjii-msft** [comment]
Adding keybindings to go to a specific tab sounds like a swell idea. 

And we'll make them re-mappable, so if you don't like the defaults, you're free to change them!

**Comment by miniksa** [comment]
We're mildly concerned about stealing more keys away before remapping is complete, but #537 should make this a non-issue when it's done.

**Comment by krokofant** [comment]
This makes a bell noise everytime I switch to a tab via alt+1, alt+2 etc.
