### ISSUE TITLE
wsl session keeps running in background on automatic update by microsoft store

### ISSUE THREAD

**Issue by Lakerfield** [microsoft/terminal#5731]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version: update to 0.11.1191.0 and some versions before

Any other software?
wsl - Ubuntu 18.04.4 LTS
```

# Steps to reproduce

Start a wsl session with a webpack-dev-server process running, wait for update from the microsoft store

# Expected behavior

- automatic reconnect to previous running tabs/processes ('small' feature request :wink:)
- or a manual option to reconnect to the orphaned wsl process
- a fix for the automatic update as described in #3915
- terminate the wsl process with a working #2232 (#2198) when updating

# Actual behavior

The wsl process keeps running in the background as a orphaned process and its difficult for a user to terminate the correct one in the taskmanager. I use process explorer to find to one without a parent process.

![image](https://user-images.githubusercontent.com/1453606/80955490-b0c37d80-8dff-11ea-8b05-c573f436b4fc.png)

**Comment by DHowett-MSFT** [comment]
As far as I can tell, this is on purpose. WSL supports background execution, so it opts to run in the background on its own. There is nothing Terminal can do to stop this, and there's nothing that we can do to reattach to it.

There is a copy of "OpenConsole.exe" associated with every Terminal tab -- if there's one of _those_ running alongside the stray WSL application, it's a terminal bug. If there isn't, the application _explicitly detached itself_. :smile: sorry!
