### ISSUE TITLE
settings.json - where it is located?

### ISSUE THREAD

**Issue by eliassal** [microsoft/terminal#5732]
Can you please tell where is the settings.json file in the system?
In the doc, you indicated all possible config but nowhere the location of this file
Thanks

**Comment by nandesu** [comment]
AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json

**Comment by eliassal** [comment]
Thanks, I found it and was able to customize it. However, ion hamsleman blog
https://www.hanselman.com/blog/ItsTimeForYouToInstallWindowsTerminal.aspx
I see that he is using "split" to have 3 different panes, 1 with PS, one with cmd, a 3rd with ubuntu...

I kept my settings as the default

> { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }

pressing "alt+shift+d", it duplicates with the same thing if PS then it is PS it cmd then it is cmd, is this correct?

**Comment by zadjii-msft** [comment]
@nandesu is absolutely correct. For a "more complete" path, it's under

```
C:\Users\<your username>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```


So for me, with my PC's user being `migrie`, the path is:
```
C:\Users\migrie\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```

**Comment by zadjii-msft** [comment]
> pressing "alt+shift+d", it duplicates with the same thing if PS then it is PS it cmd then it is cmd, is this correct?

It duplicates whichever _profile_ was used to launch the currently focused pane. So if you open the PowerShell profile, then run `cmd` in that pane, then try to duplicate it, it will run another PowerShell instance (without the child `cmd.exe`).

**Comment by eliassal** [comment]
Yes correct, if PS it opens PS. However, is it possible to reorganize the panes?
Also, do you think that it will be possible to add a new feature is that you control which profile when doing "alt+shift+d"?

**Comment by zadjii-msft** [comment]
There's answers to a ton of panes questions in #1000, so in general I'll direct your attention there.

Regarding:
> do you think that it will be possible to add a new feature is that you control which profile when doing "alt+shift+d"?

This was added in #3825. From that PR:
> With this PR, you can make bindings like the following:
> 
> ```json
> { "keys": ["ctrl+a"], "command": { "action": "splitPane", "split": "vertical" } },
> { "keys": ["ctrl+b"], "command": { "action": "splitPane", "split": "vertical", "profile": "{6239a42c-1111-49a3-80bd-e8fdd045185c}" } },
> { "keys": ["ctrl+c"], "command": { "action": "splitPane", "split": "vertical", "profile": "profile1" } },
> { "keys": ["ctrl+d"], "command": { "action": "splitPane", "split": "vertical", "profile": "profile2" } },
> { "keys": ["ctrl+e"], "command": { "action": "splitPane", "split": "horizontal", "commandline": "foo.exe" } },
> { "keys": ["ctrl+f"], "command": { "action": "splitPane", "split": "horizontal", "profile": "profile1", "commandline": "foo.exe" } },
> { "keys": ["ctrl+g"], "command": { "action": "newTab" } },
> { "keys": ["ctrl+h"], "command": { "action": "newTab", "startingDirectory": "c:\\foo" } },
> { "keys": ["ctrl+i"], "command": { "action": "newTab", "profile": "profile2", "startingDirectory": "c:\\foo" } },
> { "keys": ["ctrl+j"], "command": { "action": "newTab", "tabTitle": "bar" } },
> { "keys": ["ctrl+k"], "command": { "action": "newTab", "profile": "profile2", "tabTitle": "bar" } },
> { "keys": ["ctrl+l"], "command": { "action": "newTab", "profile": "profile1", "tabTitle": "bar", "startingDirectory": "c:\\foo", "commandline":"foo.exe" } }
> ```

**Comment by eliassal** [comment]
Fantastic zadijii, it works like a charm, keep the good efforts.
