### ISSUE TITLE
Problems when used with Mouse Without Borders

### ISSUE THREAD

**Issue by strandloper** [microsoft/terminal#5733]
# Environment

```none
Windows build number: 10.0.18363 (on LOCAL computer) & 10.0.18362 (on CONNECTED computer)
Windows Terminal version (if applicable): 0.11.1191.0 (on BOTH computers)

Any other software?
Mouse Without Borders version 2.1.8.0105 from http://www.aka.ms/mm
```

# Steps to reproduce

When using Mouse Without Borders to share mouse and keyboard between two computers, run Windows Terminal on both the LOCAL and CONNECTED computer.

# Expected behavior

Windows Terminal is expected to work correctly on both computers.

# Actual behavior

Windows Terminal works perfectly on the LOCAL computer, i.e. the one that has the mouse and keyboard connected to it. But on the CONNECTED computer Windows Terminal is only semi-usable. On opening a tab with the default console is opened and is fully usable for keyboard interaction. But the entire Windows Terminal window does not accept mouse interaction. This includes the open console (text cannot be selected with mouse), Terminal controls (new tab and menu pulldown cannot be clicked) and window controls (minimise, maximise and close buttons cannot be clicked, to close must use Close window on taskbar icon's context menu). Drag handles do appear over window edges and corners and the window can be resized. Additionally the mouse pointer is not always correctly drawn over the window, often being drawn as the up/down sizing handle when over the console; if the pointer is then moved to the title bar or out of the window and back, the correct arrow pointer is drawn.

I am using a wireless Logitech MX Ergo trackball on the LOCAL computer and a wireless Logitech M570 trackball on the CONNECTED computer. The MX Ergo is dual channel and bound to the receivers on both computers and the terminal behaviour is the same regardless of whether the LOCAL computer channel is connected and the mouse is being shared via Mouse Without Borders, or whether the CONNECTED computer channel is connected and the mouse is thus native to the CONNECTED computer. Additionally the window misbehaviour persists when the single channel M570 connected only to the CONNECTED computer is used.

Closing Terminal, stopping Mouse Without Borders and disabling it's service then re-running Terminal makes no difference, the problem persists. However, after restarting Windows with the Mouse Without Borders service disabled, Terminal behaves correctly and accepts mouse interaction. Finally after enabling the Mouse Without Borders service again (set to Automatic) and restarting Terminal works correctly even with the mouse from the LOCAL computer. Thus it would seem to have been some transient problem and given that and the fairly edge case nature of the usage, you may choose not to investigate further but I thought I should report this in any case.

**Comment by zadjii-msft** [comment]
@strandloper by any chance, are you using PowerToys?

This does seem like a well written report, but the following concerns me:

>  Finally after enabling the Mouse Without Borders service again (set to Automatic) and restarting Terminal works correctly even with the mouse from the LOCAL computer. Thus it would seem to have been some transient problem

This might make it really challenging for us to debug and fix. Hopefully, if it is a real bug, we'll be able to get a consistent repro from someone ☺️

**Comment by strandloper** [comment]
> @strandloper by any chance, are you using PowerToys?

Yes, I am using PowerToys. It didn't occur to me that they might somehow be involved as they are running on both computers, but in hindsight perhaps I should have. I was affected by a PowerToys bug (the number key row problem) in earlier versions.

As you say, reproducing this may be a problem and I understand if no cause is found. I will update here if it happens again.

**Comment by zadjii-msft** [comment]
@strandloper Which version of PowerToys? There are reports that PowerToys 0.17 actually fixes exactly this sort of problem

**Comment by strandloper** [comment]
> Which version of PowerToys?

That might be part of the problem. I have 0.17 on the LOCAL computer (installed and updated with Chocolatey) but 0.14.1 on the CONNECTED computer that had the problem (installed manually and obviously hasn't reminded me to update). I'll update it now, which should help.

**Comment by fjudith** [comment]
Disabling the option **Draw mouse cursor** worked for me.
