### ISSUE TITLE
Visual "glass" effect after window close

### ISSUE THREAD

**Issue by DVDAndroid** [microsoft/terminal#5739]
# Environment

```none
Windows build number: Microsoft Windows [Versione 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software? No
```

# Steps to reproduce

1. Open new terminal window
2. Move your mouse on Windows Taskbar, on terminal icon
![image](https://user-images.githubusercontent.com/6277172/81006499-f1e37e00-8e4f-11ea-8601-544b8ab98803.png)
3. Close the terminal with middle mouse (scroll wheel) click

# Expected behavior

No visual glitches

# Actual behavior

Visual "glass" effect glitch

![image](https://user-images.githubusercontent.com/6277172/81006309-96b18b80-8e4f-11ea-90fc-f0fd1242c889.png)

## Notes

Visual glitch persists with stock settings

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #4774 for more discussion.

/dup #4774
