### ISSUE TITLE
Create dynamic profile

### ISSUE THREAD

**Issue by Aylexx** [microsoft/terminal#5745]
# Description of the new feature/enhancement
Create dynamic profile in Terminal

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
What? You've gotta give us some actual details here...

**Comment by Aylexx** [comment]
Create new profile when one get deleted

**Comment by zadjii-msft** [comment]
That still gives me new information. 

Dynamic profiles are automatically re-added when they're deleted. To remove them, use `"hidden": true` in the json blob for the profile.

Do you mean when a profile is deleted, you want us to resurrect it? I'm not sure by what dark magic that would be possible.

**Comment by Aylexx** [comment]
@zadjii-msft you have answered my question correctly, thanks!
