### ISSUE TITLE
new-tab doesn't open new tab in 0.11

### ISSUE THREAD

**Issue by JanWerder** [microsoft/terminal#5751]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal Version: 0.11.1191.0
```

# Steps to reproduce

Execute ```wt -d . ; new-tab -d C:\ pwsh.exe```

# Expected behavior

As described in the [blog post of 0.9](https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-9-release/) I would expect a new windows terminal window with two tabs.

# Actual behavior

A window of windows terminal opens, but only with one empty tab. When I close the new window, I get the following error:

 In Zeile:1 Zeichen:11
+ wt -d . ; new-tab -d C:\ pwsh.exe
+           ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (new-tab:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by zadjii-msft** [comment]
You might be interested in [this section of the docs](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#using-multiple-commands-from-powershell)

> The Windows Terminal uses the semicolon character `;` as a delimiter for separating subcommands in the `wt` commandline. Unfortunately, `powershell` also uses `;` as a command separator. To work around this you can use the following tricks to help run multiple wt sub commands from powershell. 
>
> ```PowerShell
> start wt 'new-tab "cmd"; split-pane -p "Windows PowerShell" ; split-pane -H wsl.exe'
> ```

**Comment by JanWerder** [comment]
Ok, thanks for the information
