### ISSUE TITLE
Can't disable copyOnSelect

### ISSUE THREAD

**Issue by guibirow** [microsoft/terminal#5754]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software?
wsl (Ubuntu)
```

# Steps to reproduce

I've set *copyOnSelect* in profile.json to false but any time I select a text in the terminal it does replace what is on my clipboard.

The configuration is set like below:
```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,
    "copyFormatting": false,

    "profiles":
    { ...
```

# Expected behavior

I would expect the clipboard to no be replaced with text select in terminal when "copyOnSelect" is set to false,

# Actual behavior

Contents in the clipboard is replaced with selected text from terminal

**Comment by DHowett-MSFT** [comment]
Definitely can't reproduce this one. Can you share the rest of your `settings.json`?

**Comment by guibirow** [comment]
Closing down the issue
Noticed the new behavior now copy the select content when I right click, not on selection.
Working as expect
