### ISSUE TITLE
Multiple Selections Rendered with Search Box

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#5756]
# Environment

```none
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
```

# Steps to reproduce

1. (Optional) cd to our repo's src\cascadia\CascadiaPackage
2. `ls -R` (or just print a lot of output)
3. Open search box (<kbd>ctrl+shift+f</kbd>)
4. Search `png` a few times (at least until you force the viewport to scroll)
5. Scroll up about half a page (current selection should be past halfway down your viewport)
6. Search `png` again (just hit enter)

# Expected behavior
Only one selection is visible at a time (because only one exists).

# Actual behavior

![bug image](https://user-images.githubusercontent.com/11050425/81117065-5566bd80-8edb-11ea-8691-79fa09e3f563.png)

**Comment by DHowett-MSFT** [comment]
Search probably doesn't lock the renderer when changing its state or trigger scrolling properly. Want to look into this for 1.0?

**Comment by carlos-zamora** [comment]
I can. I think Michael did a recent PR adding a bunch of those locks so I'll take a look at that and try it.

**Comment by DHowett-MSFT** [comment]
It is so assigned.
