### ISSUE TITLE
Text gets duplicated and magled when resizing window to minimum width and out again

### ISSUE THREAD

**Issue by diddledan** [microsoft/terminal#5761]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19619.0
Windows Terminal version (if applicable): 0.11.1251.0

Any other software? Ubuntu on WSL as default Terminal Profile
```

# Steps to reproduce

1. Start Terminal
1. Open new Ubuntu session from drop-down menu
1. Resize terminal window to minimum width
1. Resize out to reasonable width again
1. Repeat previous two steps as many times as you desire thereby increasing the text mashing

# Expected behavior

The BASH prompt and other text on the screen should reflow. It should remain intact with no repetitions or extra text inserted where there was no text before.

# Actual behavior

The prompt is getting duplicated and mangled after multiple resizes.

Before resizing multiple times:
![image](https://user-images.githubusercontent.com/147548/81130905-4155a700-8f41-11ea-9c33-fde18deac9bf.png)

After resizing multiple times:
![image](https://user-images.githubusercontent.com/147548/81130774-defca680-8f40-11ea-88fa-683bc9dc25ed.png)

**Comment by diddledan** [comment]
You can exacerbate the issue by ensuring your prompt is very long, possibly it requires the prompt to be longer than the minimum window width to trigger the problem, such as by navigating deep into a very deep filesystem hierarchy.

**Comment by skyline75489** [comment]
We have #5450 for this.

**Comment by zadjii-msft** [comment]
Thanks for the help triaging @skyline75489!

/dup #5450 #5666
