### ISSUE TITLE
Windows Terminal settings reset on reinstall

### ISSUE THREAD

**Issue by dgellow** [microsoft/terminal#5763]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

Version: 0.11.1251.0

Any other software?

-
```

# Steps to reproduce

1. Install Windows Terminal from Microsoft Store
2. Modify Windows Terminal settings
3. Uninstall Windows Terminal
4. Reinstall Windows Terminal from Microsoft Store

At this point notice how you just lost your precious Windows Terminal settings and start crying.

# Expected behavior

Windows Terminal settings are stored in the user data and should persist between reinstallation.

# Actual behavior

Settings are reset each time the application is installed.

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, how applications deployed through the store work. When you uninstall them, their settings are cleared.

**Comment by dgellow** [comment]
Isn't the [Roaming Folder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingfolder) exactly for that purpose? I.e: keep user data between an application installation.

**Comment by DHowett-MSFT** [comment]
We used to store settings in the roaming folder, but it turns out that people have different WSL distributions and powershell installations on different computers, and really do want different things on their other machines. We moved _out_ of the roaming folder, and then found that it was resurrecting settings from _very old_ versions of Terminal back into the roaming folder.

This is an area of active development, but "move settings back to the roaming folder" isn't going to be a viable solution. Sorry!

**Comment by dgellow** [comment]
Hey @DHowett-MSFT. Thanks for answering, I appreciate.

If it is an area of active development, is there an issue number I can subscribe to if I want to follow the discussion? If there isn't one yet, would it then make sense to reopen this issue? Or is the discussions and development happening outside of the GitHub repository?

I'm fine with the issue being closed, I just want to know where I can get update on that development, even just by intellectual curiosity.

**Comment by DHowett-MSFT** [comment]
The best issue you can follow for this is gonna be #2933. Thanks!

**Comment by chylex** [comment]
In case someone else finds this issue after it happened to them, if you have system backups (which you should), you can restore the settings by copy/pasting contents of this folder from the backup:

```
C:\Users\<USERNAME>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe
```
