### ISSUE TITLE
"shift extend selection" feature doesn't work in the click->shift-click case because single-cell selection is gone

### ISSUE THREAD

**Issue by ymkun** [microsoft/terminal#5766]
# Environment

```none
Windows build number: [19041.208  wsl ]
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
```

# Steps to reproduce
1. Single click.
2.  Hold SHIFT and single click an unselected region.

# Expected behavior

 Region between two click should be selected.

# Actual behavior

region between two click hasn't been selected.
I remeber this feature has been released in "Windows Terminal Preview v0.9.433.0", said: "You can now hold down Shift and click to extend your selection (#4404)". But in recent releases, it gone.

**Comment by DHowett-MSFT** [comment]
So, fair enough. Shift only works to extend an _actual extant selection_ Since single-click no longer selects a cell, it doesn't comprise an active selection.

We should probably expand the touchdown anchor when you click + shift-click. It's not high-priority, because there's a workaround (select 2 cells, then use shift-click.)

**Comment by ymkun** [comment]
> So, fair enough. Shift only works to extend an _actual extant selection_ Since single-click no longer selects a cell, it doesn't comprise an active selection.
> 
> We should probably expand the touchdown anchor when you click + shift-click. It's not high-priority, because there's a workaround (select 2 cells, then use shift-click.)

Thanks.  It's just a little inconvenient when select a long region now.

**Comment by Don-Vito** [comment]
@DHowett, @carlos-zamora, @ymkun - ConEmu does something that is IMHO more intuitive:
1. Shift+Click - selects single cell
2. The next Shift+Click expands this selection.

![ShiftSelect](https://user-images.githubusercontent.com/4639110/102410899-de111480-3ff9-11eb-9955-72d69f7141ec.gif)

If you like this approach, I can commit (it is less than one-liner :blush:)

**Comment by DHowett** [comment]
Sounds great, with one caveat.

We need to figure out how this works with <kbd>Shift</kbd> suppressing VT mouse mode. Will any single shift-click on a _mouse mode_ application cause a single cell selection?

I might be okay with that.

**Comment by Don-Vito** [comment]
@DHowett - I am not sure I understood the concern, can you please explain?

I mean I tried this in tmux with mouse mode on, and it works exactly like shift +drag one char (but with no need to drag).

Guess I am missing something.

**Comment by DHowett** [comment]
Sure.

I was worried that introducing this behavior would make it difficult to single-click on the _terminal itself_ when there was a mouse mode application running without selecting a single cell.

However, thinking about it more: There is no reason to click on the terminal itself during mouse mode _unless_ you are making a selection, so this is okay. As long as it does not highlight a cell when you use Ctrl+Shift+Click on a URL!

**Comment by Don-Vito** [comment]
> 
> 
> Sure.
> 
> I was worried that introducing this behavior would make it difficult to single-click on the _terminal itself_ when there was a mouse mode application running without selecting a single cell.
> 
> However, thinking about it more: There is no reason to click on the terminal itself during mouse mode _unless_ you are making a selection, so this is okay. As long as it does not highlight a cell when you use Ctrl+Shift+Click on a URL!

I will try this. If works as expected - should I submit PR under this ticket?

**Comment by DHowett** [comment]
Absolutely! :smile: We love your PRs.

**Comment by Don-Vito** [comment]
@DHowett - lol. Actually I am asking if I should mark the PR as "Closing" this one.. or not

**Comment by DHowett** [comment]
Yeah, I think that your proposal is sufficient to solve this issue!
