### ISSUE TITLE
Azure Cloud Shell Failed to Authenticate 

### ISSUE THREAD

**Issue by cconrado** [microsoft/terminal#5768]
When using Azure Cloud Shell I'm able to get past the device login. But then it tries to authenticate and it fails. But it works for others on my team so I must have something different.

# Environment

Windows Terminal version (if applicable): 0.11.1251.0
![image](https://user-images.githubusercontent.com/9168464/81188731-4fc0b480-8f7b-11ea-8747-03506470b326.png)

# Steps to reproduce

Open Azure Cloud Shell and wait for it to authenticate.

# Expected behavior

It's supposed to authenticate to Azure.

# Actual behavior

It's stating failed.
![image](https://user-images.githubusercontent.com/9168464/81189731-8945ef80-8f7c-11ea-89ad-11d9e0f6a1f3.png)

**Comment by DHowett-MSFT** [comment]
This message should be harmless in most cases, but we're tracking fixing it in /dup #2371. There's a control socket that we're not listening to, where the shell can ask for additional credentials.
