### ISSUE TITLE
Installing custom theme not looking right

### ISSUE THREAD

**Issue by VjekoslavKrainovic** [microsoft/terminal#5781]
After following guide how to install theme, its not looking same.
This is [guide ](https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx)i am following and this is [image ](https://imgur.com/aUbSOnH)of my terminal after i made all steps from guide.

**Comment by raxraj** [comment]
I hate it to break it down to you, the guide you're using isn't the official one from Microsoft, so this issue doesn't fit right in with what you claim for.
Take a look at https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md

To closely understand the way settings in Windows terminal work for right now.

**Comment by zadjii-msft** [comment]
I mean, anything from @shanselman is _basically_ an official guide 😝 

@VjekoslavKrainovic could you share your `settings.json` file? I'd bet that you need to use a Powerline font, because the default font doesn't have the little arrow glyphs that make powerline prompts so pretty.

> ## Step Three - Get a better font
> 
> If you do all this and you see squares and goofy symbols, it's likely that the font you're using doesn't have the advanced Powerline glyphs. Those glyphs are the ones that make this prompt look so cool!
Weird fonts
>
> 
> Cascadia Code has been updated with a PL (Powerline) Glyph version! Go get it at https://github.com/microsoft/cascadia-code/releases and change the fontFace in your settings.json to "Cascadia Code PL"
>
> `"fontFace":  "Cascadia Code PL"`
>
> Remember also you can get lots of Nerd Fonts at https://www.nerdfonts.com/, just make sure you get one (or generate one!) that includes PowerLine Glyphs.

**Comment by VjekoslavKrainovic** [comment]
> I mean, anything from @shanselman is _basically_ an official guide 😝
> 
> @VjekoslavKrainovic could you share your `settings.json` file? I'd bet that you need to use a Powerline font, because the default font doesn't have the little arrow glyphs that make powerline prompts so pretty.
> 
> > ## Step Three - Get a better font
> > If you do all this and you see squares and goofy symbols, it's likely that the font you're using doesn't have the advanced Powerline glyphs. Those glyphs are the ones that make this prompt look so cool!
> > Weird fonts
> > Cascadia Code has been updated with a PL (Powerline) Glyph version! Go get it at https://github.com/microsoft/cascadia-code/releases and change the fontFace in your settings.json to "Cascadia Code PL"
> > `"fontFace":  "Cascadia Code PL"`
> > Remember also you can get lots of Nerd Fonts at https://www.nerdfonts.com/, just make sure you get one (or generate one!) that includes PowerLine Glyphs.

Thank you for helping, you were right , my settings were corret but i had Cascadia Code font, after i installed one you told me it looks exactly same now!

**Comment by zadjii-msft** [comment]
Happy to help ☺️ Thanks for following up!
