### ISSUE TITLE
Terminal blocks the task bar when it is auto hidden

### ISSUE THREAD

**Issue by OnurGumus** [microsoft/terminal#5782]
# Environment

```none
Windows build number: 10.0.19582.0
Windows Terminal version (if applicable):0.11.1191

Any other software? No
```

# Steps to reproduce
- From task bar settings, turn on auto hide task bar on desktop mode
- Make the terminal full screen and wait for task bar to disappear
- Try to access to the taskbar.

# Expected behavior

Task bar should appear

# Actual behavior

Task bar doesn't appear.

**Comment by zadjii-msft** [comment]
This is actually pretty consistent with the way other applications work with auto-hiding taskbars and fullscreen mode. Chrome/Firefox/Edgium, when fullscreened, will all block the taskbar _on the primary monitor_. If you fullscreen on a secondary display, then the auto-hidden taskbar _will_ reveal itself. 

I couldn't tell you _why_ this is. I'm just keeping the behavior consistent with the other apps I see 😄 

See also: #4857
