### ISSUE TITLE
More convenient shortcut key for opening new Tab(s).

### ISSUE THREAD

**Issue by raxraj** [microsoft/terminal#5783]
# Description of the new feature/enhancement
A more suitable way to open new tabs, with the latest release as of now, the CTRL+Tab to switch between tabs was brought back, but to open new tabs it is still set to ctrl+shift+1 and show on.
For default new Tab it is set to Ctrl+Shift+T which doesn't appear much convenient. I believe we need the Ctrl+T way to open a new tab, which brings consistency in the way new tabs open in every other software.

# Proposed technical implementation details (optional)

Well it is simple I just believe that CTRL+TAB is there for changing tabs then I guess we pretty much need CTRL+T to open a new tab with default and CTRL+1, CTRL+2, etc for the others.
Though CTRL+1, 2, etc are optional CTRL+T is a requirement I believe.

# More Details
I understand it pretty well, that we can change it using the JSON keybindings, but I am requesting it as a default behavior and not as a customization.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We've played with the defaults pretty extensively over the last year, and we've found that the <kbd>Ctrl+Shift+key</kbd> versions of the keyboard shortcuts are almost _always_ better. The main reason is that a lot of commandline applications already have actions bound to <kbd>Ctrl+key</kbd> key chords. If the Terminal were to bind these keys by default, then most users would have to opt _out_ of these keybindings. It's been less painful to instead have the few users who want to use <kbd>Ctrl+key</kbd> chords for the Terminal shortcuts to opt-_in_ to them.

**Comment by raxraj** [comment]
@zadjii-msft Well I understand the fact that you're stating.
But I recently shifted from the Ubuntu to Windows, just because of the Terminal and the Linux Subsystem being available on Windows.
And Ubuntu Terminal, as well as other Linux env have a Ctrl+key for the new tab, and I still believe it won't be a major problem with Ctrl+T since it is the most prominent for new tabs among all the terminals and CLI dev know this fact.

But Yet, if the dev team thinks it's for the best, then I think we have to assume it.
