### ISSUE TITLE
Ability to disable some dead keys

### ISSUE THREAD

**Issue by gpotter2** [microsoft/terminal#5784]
# Description of the new feature/enhancement

**Feature:** Ability to disable SOME dead keys.

**Motivation**

It might be hard to understand for people who have sensible layouts, but many keyboard layouts have dead keys that are very cumbersome when programming.

I personally use the terminal on the daily, and the tilde ~ is used a lot in Linux. On my AZERTY default layout, ~ acts as a dead key: i need to type it then add a space to get a single ~. See the layout below
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/500px-KB_France.svg.png)
`~` needs `ALTGR + 2 + space`. This is exhausting. We also have a dead `^` that could use this feature.

**Notes**
- Ubuntu provides very useful layouts made for coders, that disable the cumbersome dead keys: https://askubuntu.com/questions/56560/what-exactly-is-meant-by-eliminate-dead-keys . Windows doesn't provide this natively, thus this feature request (I would never expect this to be added to the main OS...)
- Some people will say they use ñ while coding, or ê. Even if the Terminal has great:tm: support for UTF8, I'm not among them. I belive this is a tiny minority
- I'm sure many people have that one dead key they wish they could get rid of. If this feature was builtin the terminal, it would allow a better coding experience for the people that only use those characters in the terminal anyways. This could also be profile based...

**Do people also want that**
- [Google for "disable dead keys"](https://www.google.com/search?q=disable+dead+keys+windows)
- It seems the germans also have tons of dead keys: many articles try to workaround those: https://zauner.nllk.net/post/0014-windows-no-dead-keys/

For the user, It could be as simple a config value to disable dead keys using their key codes (?) such as
```
disable_dead_keys: [50]  # the 2/~ key code
```

Thanks a lot for you time, the Terminal is absolutely amazing and it just keeps getting better ! Cheers

**Comment by zadjii-msft** [comment]
This doesn't seem entirely unreasonable to me. We might want to workshop how we specify these keys in json, but I think the idea sounds valid. I'm gonna summon our keyboard layout expert @lhecker to see if he's got any thoughts on the matter ☺️ 

(sorry for the long silence)

**Comment by lhecker** [comment]
Yeah that's probably relatively easy to implement. Add a config setting like [so](https://github.com/microsoft/terminal/pull/6212) (minus the UB I introduced), and add a `&& !disabledDeadKeys.contains(vkey)` [here](https://github.com/microsoft/terminal/blob/f32761849f716db70248854b39160cf58c22ed8d/src/cascadia/TerminalCore/Terminal.cpp#L456).
I'd be able to implement that next weekend or so. 👍

**Comment by gpotter2** [comment]
Thanks a lot for looking into this !

**Comment by lhecker** [comment]
I had the idea of adding a command called "passthrough" to the keybindings.
If you e.g. add a `{ "command": "passthrough", "keys": "~" },` binding it would then pass the key event (with the character `~`) to the shell instead of deferring the event to the character event handler.
In order to support this I'd modify `IKeyBindings::TryKeyChord` to return a ternary instead of a boolean.
What do you think?

**Comment by lhecker** [comment]
Ah! I forgot about this issue! While it's slightly cumbersome I believe this functionality can now be achieved in the v1.3 preview version using the [new `sendInput` command](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings#send-input-preview).
If that's sufficient for you @gpotter2 would you like to try it out in the preview version?

**Comment by gpotter2** [comment]
It's working great ! The only issue now is that there is no way to register `AltGR` in the current key binders :/

**Comment by lhecker** [comment]
The current key bninding interface [doesn't make a distinction between left and right Ctrl/Alt](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/KeyChord.idl).
We'll have to extend that interface and teach it to do so first. It'll also require adding logic to make it parse e.g. "LeftCtrl"/"RrightCtrl" and teach it that "Ctrl" is an alias for the presence of either of those keys. Only then can we alias "AltGr" as "RightAlt+LeftCtrl". Unfortunately that's clearly another feature that needs to implemented unrelated to both `sendInput` this issue. 🤔

**Comment by gpotter2** [comment]
Definetly ! Thanks for your work on this.
Is there an opened issue for this next one ? Thanks

**Comment by gpotter2** [comment]
Actually, there's an issue: it seems the dead key are not consumed (which is the whole point of this issue), even if made a shortcut.
For instance on my AZERTY keyboard, there's a `^` that is a dead key. If i use:

```
{ "command": { "action": "sendInput", "input": "b" }, "keys": "^" }
```

If i then press once the `^` key (which is a dead key) then a, I'll get:
```
bâ
```

**Comment by lhecker** [comment]
I'll investigate this. 👍

**Comment by gpotter2** [comment]
Thanks a lot for your work on this !!!
❤️
