### ISSUE TITLE
Terminal crashes while opening new tab when using Ubuntu as a default profile

### ISSUE THREAD

**Issue by xxzefgh** [microsoft/terminal#5785]
# Environment

```none
Windows build number: 10.0.19041.208
Windows Terminal version (if applicable): 0.11.1251.0
```
I haven't modified terminal configuration except setting Ubuntu as a default profile. 
When I open a new tab it crashes randomly, so if I just spam add new tabs it eventually happens.
I reverted default profile to PowerShell and it seems to only happen for ubuntu. Unfortunately feedback hub doesn't recognize it as a crash so I don't have a diagnostic data.
Here is the screen recording: https://streamable.com/lmooag

# Steps to reproduce

open new tabs repetitively

# Expected behavior

not crash

# Actual behavior

crash

**Comment by xxzefgh** [comment]
After further investigation, it seems to be zsh (or oh-my-zsh) specific issue. doesn't happen when using bash

**Comment by zadjii-msft** [comment]
Since this seemed to be an issue with your own `zsh` install, I'll close this issue up. Thanks for following up!
