### ISSUE TITLE
How to change the default startup directory?

### ISSUE THREAD

**Issue by baabaaox** [microsoft/terminal#579]
I think " C:\WINDOWS\System32" unfriendly to the user, Can you replace it with '%HOMEPATH%'?

**Comment by AsciiWolf** [comment]
Would it be possible to re-open this issue? Please, consider shipping Terminal with the startup directory setting changed to `%HOMEPATH%` by default. `C:\WINDOWS\System32` is user unfriendly and confusing.

**Comment by ccurrens** [comment]
It looks like someone has already put out a PR for that #604
