### ISSUE TITLE
Line with multiple whitepaces in Python REPL gets written over

### ISSUE THREAD

**Issue by vangorden** [microsoft/terminal#5791]
# Environment

```none
Windows build number: 10.0.19624.0
Windows Terminal version (if applicable): 0.11.1251.0 (this issue existed in previous versions as well)

Any other software?
WSL
Python
```

# Steps to reproduce
Open a Python REPL from within WSL by entering `python`.
Enter a character followed by a space and another character followed by a space, then left arrow back to beginning of line. `>>> s s s`
Now enter some new characters.

# Expected behavior
New characters should be inserted between existing characters pushing those that come after forward.

# Actual behavior
Existing characters are written over by new characters.

# Observations
I've only observed this behavior through WSL, it does not seem to be present in Powershell so this may be an issue with WSL.
It appears to be related to having more than one space character in the line.

**Comment by zadjii-msft** [comment]
Hmm, curious, I can't seem to repro this. 

![image](https://user-images.githubusercontent.com/18356694/81319657-95ea4680-9055-11ea-8833-300d3510d017.png)

Maybe there's something else about your WSL environment that's causing this. Which version of `python` are you running? Which linux distro? What shell are you using, and have you done anything to configure that shell?

What's the output of `stty -a` both straight from the shell, and from the python REPL?
![image](https://user-images.githubusercontent.com/18356694/81319953-0c874400-9056-11ea-981f-7f2828f18d9e.png)


Does this repro in the vintage console window, or only in Windows Terminal?

**Comment by vangorden** [comment]
Thanks for looking at this!

Linux Distro: Ubuntu 20.04 LTS
Shell: zsh
Python versions: 2.7.17 and 3.7.6

![image](https://user-images.githubusercontent.com/8635099/81321709-caef9c80-9047-11ea-9600-254a07b2618f.png)

Actually I think I just found the culprit in my .zshrc
`export TERM=xterm-color`

Removing this has resolved the issue for me, so I'll go ahead and close this.
