### ISSUE TITLE
Open Terminal in any directory by typing wt in the address bar

### ISSUE THREAD

**Issue by Borkason** [microsoft/terminal#5796]
If you type `cmd` in the address bar of the Windows Explorer and press enter, a command line opens in the current directory of the Windows Explorer.

![grafik](https://user-images.githubusercontent.com/2971735/81331899-90671d80-90a2-11ea-91bc-9bd33efea069.png)

I propose that typing `wt` in the address bar should do the same. It opens, but the path always defaults to %userprofile%.

This would make it extremely easy opening Terminal at the location that I am currently working in Windows Explorer.

**Comment by DHowett-MSFT** [comment]
/dup #592 #878 we've looked at fixing this before, but it's difficult to tell when the user wants to launch wt and have it preserve the directory versus have it ignore it. We settled on either `wt -d .` or telling people they can set `startingDirectory` in their profiles to `.` or `%CD%`.

**Comment by rahulsingh-2024** [comment]
wt -d .               is working file
