### ISSUE TITLE
Terminal freezes after tab close

### ISSUE THREAD

**Issue by victoralvesp** [microsoft/terminal#5799]
# Environment

```none
Windows build number: 18363
Windows Terminal version (if applicable): 0.11.1251.0

I'm running Terminal with Powershell Core 7.1.0 preview2
```

# Steps to reproduce
1. Run Terminal
1. Activate fullscreen
1. Open new tab
1. Switch to previous tab
1. Close tab (I use a `Ctrl+W` binding to close tab)

# Expected behavior

Tab closes and focus goes to recently opened tab.

# Actual behavior

Sometimes the whole terminal will freeze and the only way to continue is to kill Terminal process

**Comment by DHowett-MSFT** [comment]
Thanks! This looks like a /dupe of #5559, and I finally got it under the debugger.

**Comment by DHowett-MSFT** [comment]
Nevermind, it doesn't look like that dupe.

**Comment by DHowett-MSFT** [comment]
Oh no. It looks like the TabView never notifies us that its selection changed because it's invisible... We end up directing input into a TerminalControl that's on-screen but _just dead_.

Since the terminal control handles all app key bindings, the app stops responding. If you press <kbd>F7</kbd> when it's in this state, it'll attempt to send F7 to a dead connection and then it'll crash.

**Comment by zadjii-msft** [comment]
Oh uh yea I do have a clever idea - while I was trying to figure out a clever idea, I kinda accidentally the whole thing. Sorry to step on your toes here 😬

**Comment by MohammatMajken** [comment]
I have reproduced the steps, and I must say that whoever found this mistake did a good job.
@zadjii-msft When will the solution come? I can't wait! 😊

**Comment by MohammatMajken** [comment]
By the way, good work!

**Comment by zadjii-msft** [comment]
I'm not really sure what the timeline for this fix will be - it _might_ get pulled into Terminal 1.0. The bot will come through and post on this issue when it _does_ get released, that's for sure ☺️

**Comment by victoralvesp** [comment]
That was quick! Thanks for the great work!
