### ISSUE TITLE
Fullscreen toggle commandline parameter

### ISSUE THREAD

**Issue by Firehawke** [microsoft/terminal#5801]
# Description of the new feature/enhancement

A command-line parameter that can toggle fullscreen status; initially since you can't modify existing WT sessions (to add or remove tabs) yet you wouldn't be able to use it to turn FS off, but you could use it when running a WT script to open several tabs to make those fullscreen.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Not bad. Hooked up to #4632.
