### ISSUE TITLE
Possible system hang linked to a call to the ESENT API

### ISSUE THREAD

**Issue by Yevano** [microsoft/terminal#5802]
[Feedback Hub link](https://aka.ms/AA8d0mj)

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1251.0
```

# Steps to reproduce

Windows session had been alive for maybe a couple of weeks, and I'm sure the terminal had been open for several days between having the desktop in sleep mode. Reproducing this bug may be quite difficult, unless you happen to find the same error in the event viewer as I did. (below) Hopefully someone can filter for it to see if the problem is systematic, or if it is just my own system acting up.

# Expected behavior

Obviously the program shouldn't just be allowed to hang a desktop due to a file access error, if that actually was the cause.. 

# Actual behavior

I got an error message box, which I didn't have time to read since after a second or so all three of my monitors went black. After a hard reset, I had a look at the event viewer. I have sent logs to `secure@microsoft.com` as is stated that I should do in the template. The gist is that the call to ESENT causes an `ERROR_NOT_FOUND` exception while attempting to open the file `C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log`.

First time doing an issue here. If there is more info in the issue that I am supposed to share and I missed it, please let me know so that I can help with further investigation into this issue.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! I'm not certain that Terminal calls any ESENT APIs or interacts with TileDataLayer at all. It's more on the "classic" application side of the "modern/classic" continuum.

I'm not sure any of us will be able to reproduce it.

Is there a chance that you have a `dmp` file? If this happens again, you can capture one by right-clicking `WindowsTerminal.exe` in Task Manager's Details view. My e-mail's on my GitHub profile. :smile:

**Comment by DHowett-MSFT** [comment]
(We've not gotten any other reports of this; sorry!)

**Comment by DHowett-MSFT** [comment]
Ah, and one last thing -- I can't actually see the e-mails sent to `secure` unfortunately. ☹️

**Comment by Yevano** [comment]
Okay I forwarded that email to you. Thanks for the response. :)

**Comment by DHowett-MSFT** [comment]
Thanks again!

So, having looked at that attachment, the best I can find is "the store decided to update the Terminal package right before it blasted off into outer space." Unfortunately, there's not too much we can do with this information.

I'm going to mark this one no-repro, but please do let me know if it happens with subsequent updates!
