### ISSUE TITLE
在一定缩放的情况下

### ISSUE THREAD

**Issue by rendaoer** [microsoft/terminal#5805]
通过菜单栏打开的时候会使窗口距离顶部和左边的间隙过大，导致窗口展示不完全且需要移动窗口使用，很不方便
![image](https://user-images.githubusercontent.com/46780118/81387416-3a00ea00-9149-11ea-962d-ac00141976bf.png)

**Comment by rendaoer** [comment]
> 通过菜单栏打开的时候会使窗口距离顶部和左边的间隙过大，导致窗口展示不完全且需要移动窗口使用，很不方便
> ![image](https://user-images.githubusercontent.com/46780118/81387416-3a00ea00-9149-11ea-962d-ac00141976bf.png)

**Comment by zadjii-msft** [comment]
I apologize in advance if I'm not understanding your bug report - internet translations can be pretty bad sometimes 😝 

I believe what you're looking for is the `initialPosition` setting. This property lets you set a location on the screen to start the Terminal window when it is first created. I think you might be able to use the following in your `settings.json` file to get the behavior you're looking for:

```json
  "initialPosition": "0,0"
```


There's also `"launchMode": "maximized"`, which you can use to open the Terminal _maximized_ by default. From [our docs](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#globals):

Property | Necessity | Type | Default | Description
-- | -- | -- | -- | --
initialPosition | Optional | String | "," | The position of the top left corner of the window upon first load.  On a system with multiple displays, these coordinates are relative to  the top left of the primary display. If launchMode is set to "maximized", the window will be maximized on the monitor specified by those coordinates.
launchMode | Optional | String | default | Defines whether the Terminal will launch as maximized or not. Possible values: "default", "maximized"

**Comment by rendaoer** [comment]
At some times, the window is not at the center of the screen, so there will always be a part of the screen, which needs to be moved to see all of it. This is very inconvenient. My screen is 1920x1080 150% zoomed, the window is focused It will affect the position where the terminal is opened. Opening the terminal when opening the browser will cause the terminal window to be too low to the right, and opening the terminal after clicking the desktop will only be too low. I tried to modify the settings.json, but it could not be saved, even Administrator rights
Figure 1 (Browser opens window when running):
![image](https://user-images.githubusercontent.com/46780118/81408625-27e67200-9170-11ea-83f8-372067e6c4a6.png)
Figure 2 (Open window on desktop):
![image](https://user-images.githubusercontent.com/46780118/81408642-2ddc5300-9170-11ea-920e-be0a7c8b40ed.png)

**Comment by gxywy** [comment]
I have the same issue, but I found it can be solved by setting `fontSize`
