### ISSUE TITLE
can't type symbols like | <> @ ^

### ISSUE THREAD

**Issue by fiber-optics** [microsoft/terminal#5806]
Hi, i use Microsoft Windows NT 10.0.18363.0
Terminal version - 0.11.1251.0

when i type in powershell | <> ^ @ - its typing, all goods, but when i run 
ssh myhost
and try type again symbols like | <> @ ^
it's not typing, not showing, i can't even paste it's, if i copy thats symbols.

but if i run just power shell(not in terminal, single app) - all good.

**Comment by zadjii-msft** [comment]
What keyboard layout are you using? What version of `ssh`?

**Comment by fiber-optics** [comment]
windows terminal version 0.11.1251.0
keyboard layout us-102

**Comment by zadjii-msft** [comment]
Alright here's another question that might be able to narrow this issue down - if you use `ssh` from a WSL distro, do those keys work?

**Comment by fiber-optics** [comment]
> Alright here's another question that might be able to narrow this issue down - if you use `ssh` from a WSL distro, do those keys work?

i don't try. any wsl distro not install currently

**Comment by fiber-optics** [comment]
i install wsl ubuntu 20.04, all symbols works perfect.
but in powershell from win terminal still not working

**Comment by touuki** [comment]
I can type these symbol  `|<>@^`, but when I type symbols like `… — ‧`, it has exactly the same problem. Work fine on wsl and standalone powershell, but cannot work on ssh or telnet from terminal.

**Comment by DHowett-MSFT** [comment]
@touuki those symbols are not in the standard CP437 symbol plane, so _Windows Telnet_ will never support them, and Windows SSH has a bug right now that makes them not work. This has been resolved in the 8.x releases. :smile:

**Comment by DHowett-MSFT** [comment]
This sounds like a Win32-OpenSSH bug.

@fiber-optics, if you install Win32-OpenSSH 8.x from [their releases page](https://github.com/PowerShell/Win32-OpenSSH/releases), does it work?

**Comment by DHowett-MSFT** [comment]
Resolving external for now.

**Comment by touuki** [comment]
@DHowett-MSFT Oh, yeah. It works fine in OpenSSH_for_Windows_8.1p1, thanks.

**Comment by DHowett-MSFT** [comment]
I'm happy to hear that!
