### ISSUE TITLE
Open the terminal with the "wt" command

### ISSUE THREAD

**Issue by rendaoer** [microsoft/terminal#5807]
After updating the rc1 version a few days ago, the terminal cannot be opened by the "wt" command, and there is no icon for the "wt" command. Can I add an icon?

**Comment by rendaoer** [comment]
Search the "wt" command in the start menu to select the execution does not respond, select the administrator authority to start it will prompt "the system can not access this file", but found in the resource manager to start the file is effective, hope "wt" file is added icon

**Comment by rendaoer** [comment]
It can be used normally after restarting, but it still prompts "The system cannot access this file" when starting with administrator rights
![image](https://user-images.githubusercontent.com/46780118/81411993-bc9f9e80-9175-11ea-87ae-03af8dca7df6.png)

**Comment by DHowett-MSFT** [comment]
There cannot be an icon (sorry -- platform limitation). If your administrator is a different user you need to register the terminal package for that user.
