### ISSUE TITLE
About box is not modal / masked improperly. Unexpectedly allows text entry behind it.

### ISSUE THREAD

**Issue by fishzle** [microsoft/terminal#5810]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
Using focus-follows-mouse
```

# Steps to reproduce
Open a terminal.
click on the down arrow and bring up the about box.
![image](https://user-images.githubusercontent.com/8211862/81411679-0e502500-9186-11ea-9d21-446dca32ef3f.png)

**Method 1**: resize the terminal horizontally so it's wider than the original terminal width.
**Method 2**: resize the terminal vertically so it's taller than the original terminal width.

![image](https://user-images.githubusercontent.com/8211862/81411900-5bcc9200-9186-11ea-976b-1da6e90ab4f2.png)
near the right edge you can see the lighter grey section. If you put your cursor there, you can enter text at the cursor (in the picture, you can see I added "hello covid-19")

![image](https://user-images.githubusercontent.com/8211862/81411737-24f67c00-9186-11ea-89ff-381062d0e933.png)

similarly, when resized vertically, entering text in the light grey section works.
![image](https://user-images.githubusercontent.com/8211862/81413081-30e33d80-9188-11ea-93cf-048d8703c89b.png)

Once you've entered text in the textarea:
Pressing ESC in the light grey section doesn't close the About box.
Pressing ESC in the dark grey section outside the About box doesn't close the About box.
Pressing ESC anywhere doesn't close the About box.
The only way to dismiss the About box is to click the OK.

# Expected behavior
The about box should be modal, it should not be possible to enter text behind it.
But perhaps, resizing the terminal should close the About box. Avoiding this issue.

# Actual behavior

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion.

/dup #2380
