### ISSUE TITLE
Command line focus-pane to split

### ISSUE THREAD

**Issue by chechorincon** [microsoft/terminal#5811]
It would be great to have a focus-pane option from the command line, so you can start wt with some layouts that currently are almost impossible (2x2 splitted, 3x3, and so on) and be able to pass parameters to a specific pane (not tab)

Right now, (as far as I´ve found and searched) there is a way to start wt from the command line and split the pane (H or V), but when you append a new split-pane, it splits the last (Current) pane. So if you want to split, from the command line, the tab to have a layout of 2x2 panes or 3x3 panes, its not possible. With a focus-pane option, each pane should have an ID, so at the command line you can tell to what paneID you want to split.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5464 for more discussion.

/dup #5464
