### ISSUE TITLE
Terminal doesn't translate LF to CR on paste; it only translates CRLF

### ISSUE THREAD

**Issue by riverar** [microsoft/terminal#5821]
Notes from @DHowett-MSFT:

## Line ending conversions by other terminals

Clipboard Contains | xterm sends | wt sends | putty sends | gnome-terminal sends | conhost sends
-|-|-|-|-|-
`\r\n` (CRLF)|`\r` ✔️|`\r` ✔️|`\r` ✔️|`\r` ✔️|`\r` ✔️
`\r` (CR)    |`\r` ✔️|`\r` ✔️|`\r` ✔️|`\r` ✔️|`\r` ✔️
`\n` (LF)    |`\r` ✔️|`\n` ❌|`\n` ❌|`\r` ✔️|`\r` ✔️

I guess that means that both of WT and putty are wrong :smile:

--- original filing below ---

# Environment

```none
Windows 10 10.0.19041.207
Windows Terminal 0.11.1251.0
```

# Steps to reproduce

1. Open Windows Terminal (Windows PowerShell or PowerShell Core).
2. Copy all the text in the attached file [fake_key.txt](https://github.com/microsoft/terminal/files/4602399/fake_key.txt).
3. Paste into Windows Terminal with the mouse.
4. Observe the lines appear in reverse order.

# Expected behavior

Similar behavior to cmd.exe and wsl, in that the pasted lines are in original order and intact.

# Actual behavior

Bamboozled. Lines are presented in reverse order.

# Screenshots

![image](https://user-images.githubusercontent.com/475132/81459801-6d964100-9156-11ea-83f9-9bccad07aa8c.png)

![image](https://user-images.githubusercontent.com/475132/81459807-72f38b80-9156-11ea-995e-47b9989faf69.png)

![image](https://user-images.githubusercontent.com/475132/81459811-7b4bc680-9156-11ea-946c-d1167f8d6f55.png)

**Comment by skyline75489** [comment]
Stock powershell.exe shares the same behavior. Also seen this in PowerShell Core 7.

**Comment by DHowett-MSFT** [comment]
That _is_ strange. I would call that CMD and WSL work properly evidence that _it is possible for the shell to either mess this up or fix it_, so...

**Comment by DHowett-MSFT** [comment]
Rafael, if you `Remove-Module PSReadline`, do you get the result you’re expecting?

**Comment by skyline75489** [comment]
I was about to add that. But I wouldn't really say "CMD and WSL works property". First, in CMD the `\n` is completely ignored. Second, in WSL the '\n' is treated as an actual <kbd>Enter<kbd>, causing many `command not found` complains from bash.

To me, `PSReadline` does not seem to matter.

**Comment by riverar** [comment]
Results with `PSReadline` removed:

PowerShell Core (correct order, but truncated)
![image](https://user-images.githubusercontent.com/475132/81464322-60d51580-9175-11ea-87ef-124e33b8d85a.png)

Windows PowerShell (correct)
![image](https://user-images.githubusercontent.com/475132/81464330-76e2d600-9175-11ea-98e1-8be29b26b404.png)

**Comment by DHowett-MSFT** [comment]
Even curiouser: It works "fine" (that is: to the same extent as cmd and without PSReadline) for me on PowerShell 7.0 and 7.1-preview.

I was inclined to call this a miss in our clipboard conversion, but... it looks like there's no consensus here.

Clipboard Contains | xterm sends | wt sends | putty sends | gnome-terminal sends
-|-|-|-|-
`\r\n` (CRLF)|`\r`|`\r`|`\r`|`\r`
`\r` (CR)|`\r`|`\r`|`\r`|`\r`
`\n` (LF)|`\r`|**`\n`**|**`\n`**|`\r`

I guess that means that both of WT and putty are wrong :smile:

**Comment by DHowett-MSFT** [comment]
Well, conhost does it right. I guess that's it then. I'm renaming your bug ;P

**Comment by riverar** [comment]
Thanks all! A++ would file another bug.

**Comment by 71walceli** [comment]
FYI, for anyone using Alacritty + tmux + SSH, this is a good workaround:

```
sh -c 'sleep 5; xdotool type "$(xclip -o -selection clipboard | tr "\n" "\r")"'
```

There should be a command just to re-copy the terminal contents into the clipboard, having piped through `tr` the same way I have.
