### ISSUE TITLE
Settings sync / cloud backup

### ISSUE THREAD

**Issue by rdlf0** [microsoft/terminal#5827]
# Description of the new feature/enhancement

Would be really nice if `settings.json` can be backed up/synced with some cloud account similarly to the upcoming [VSCode feature](https://code.visualstudio.com/docs/editor/settings-sync). This doesn't seem to depend on the implementation of Settings UI.

# Proposed technical implementation details (optional)

I think the way it happens in [VSCode](https://code.visualstudio.com/docs/editor/settings-sync) is good enough. There will be a new item in the dropdown menu where `Settings` is now. This item will  have a label "Turn on Settings sync..." which will open a dialog for signing in with your preferred account (for ex. Microsoft account, GitHub account, etc.) After signing in, a ✔ will appear right before the menu item's label and the syncing will start happening in background.

**Comment by DHowett-MSFT** [comment]
Thanks for the request! I'm going to track this with its compatriot and partner in crime, /dup #2933. If that requires us to stand up our own sync service (gosh, I hope it doesn't), that'll be captured there.
