### ISSUE TITLE
Request: Support for Font Width Variants

### ISSUE THREAD

**Issue by sharpjs** [microsoft/terminal#5828]
Some fonts have multiple width variants.  [Iosevka](/be5invis/Iosevka) from @be5invis, for example, has an Extended variant.  Terminal should support the use of such variants.

Currently:
```
"fontFace": "Iosevka SS04"
```
![image](https://user-images.githubusercontent.com/708461/81503142-d84e9600-9296-11ea-865a-862401d6bcdc.png)

But when asking for the Extended variant, Terminal falls back to a default font — Consolas for me.
```
"fontFace": "Iosevka SS04 Extended"
```
![image](https://user-images.githubusercontent.com/708461/81503165-00d69000-9297-11ea-84a7-b83cea64f16f.png)

I propose support for width variants either through `fontFace` or through a new `fontWidth` profile configurable.

Please add this feature request to @be5invis's epic for similar issues, #1790.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! I think this is mostly covered by /dup #1790 #1751--they suggest that we need something more than "font face name" for selecting the font, and might further posit that we need variant/opentype feature selection.

**Comment by DHowett-MSFT** [comment]
(I just realized 1751 wasn't linked up, so that was the important part of the dupe here. Weight and family/face together make up this issue :smile:)

**Comment by sharpjs** [comment]
Thanks. Hopefully we get width and weight support at the same time.

**Comment by DHowett** [comment]
Figured I'd just reopen this since we're on the cusp of closing it :smile:

**Comment by sharpjs** [comment]
Two thoughts: "Woo!" and "Hoo!".  Thanks, Terminal developers! 🙇🏽

**Comment by DHowett** [comment]
> Two thoughts: "Woo!" and "Hoo!". Thanks, Terminal developers! 🙇🏽

@PankajBhojwani deserves most of the credit here. Thanks Pankaj! :smile:

**Comment by AnrDaemon** [comment]
And how would we utilize it? No matter how hard I look, I can't see where I could select font variant. So far my only option is to install only variant I want to use.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/215735759-31aaa148-6290-4a7c-ad4d-cd8e3dcf81f9.png)


![image](https://user-images.githubusercontent.com/18356694/215735594-b4d7c64a-c0f6-4463-a26c-7b9910506037.png)

**Comment by AnrDaemon** [comment]
It is good I know the specs and details of the font I'm using. But it is all but making the life unnecessarily harder for general use, and any changes to the JSON will be destroyed on any UI changes.
There's no simple way to know what to enter in each block, unless you have a very specific tool to inspect the font you wish to use.

**Comment by LtqxWYEG** [comment]
Hi  
Width is still not implemented and adding the axis code for that does not work:  

```
{
    "cellHeight": "1.2",
    "face": "Iosevka Custom Mono",
    "size": 13.0,
    "weight": "semi-bold",
    "axis": {
        "wdth": 658
    }
}
```

That should be correct. I've red through some more of the microsoft docs regarding axis's, and the value 658 is exactly one of the width of the font. (Cause you can make the font yourself); I don't get an error but nothing changes. :(  

**Workaround**, _though_:  
Build another font that has only the width you want. (You can't just rename the .ttf) :(  
Fortunately, you can define such things with Iosevka. Make one with their customizer on their website, then delete a few lines in the `.toml` to only leave one width. If you also only leave one weight, building the font is pretty much instant! Experimenting with it to get the perfect width and weight takes no time! 👍    
BTW, the `shape = 658` value in the can be anything you want! However, `10 is not a valid number.` will crush your dreams. (Must be a bug!) The value can be anything between 416 and 720, which is disappointing to say the least. (Presumably, the same goes for weight.)  👎   

kind regards :)

**Comment by AnrDaemon** [comment]
Why this issue was closed, pretty please?

**Comment by LtqxWYEG** [comment]
Aparently because of a dev misreading the point of this issue, and fixing "it". https://github.com/microsoft/terminal/pull/10525

But now we have weight adjustment. One missing ;)

**Comment by DHowett** [comment]
> Width is still not implemented and adding the axis code for that does not work:
> 
> ```
> {
>     "cellHeight": "1.2",
>     "face": "Iosevka Custom Mono",
>     "size": 13.0,
>     "weight": "semi-bold",
>     "axis": {
>         "wdth": 658
>     }
> }
> ```
> 
> That should be correct. I've red through some more of the microsoft docs regarding axis's, and the value 658 is exactly one of the width of the font. (Cause you can make the font yourself); I don't get an error but nothing changes. :(
>
> Aparently because of a dev misreading the point of this issue, and fixing "it"


You spelled `axes` wrong.

That does not indicate that my engineers "misread" the point of this issue.

If you spell it right, it works fine. Here's Bahnschrift:

`wdth` 100:

![Image](https://github.com/microsoft/terminal/assets/189190/30ffd33a-00ca-4bef-ac67-ead3852770e3)

`wdth` 30

![Image](https://github.com/microsoft/terminal/assets/189190/69002d8e-5c72-40c4-a815-3a4f01060c29)

**Comment by LtqxWYEG** [comment]
Ffffssssffs? They wrote evrywhere "**Axis**". That must have blinded me to "_axes_". I mean, what do you need multiple axes for? You can't realistically dual-wield them. One's enough.
