### ISSUE TITLE
A few typos in razzle.cmd

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/Terminal#583]
As mentioned in #436, there are a few typos, where we're searching `%ProgramFiles%` but setting `%ProgramFiles(x86)%`.

https://github.com/Gnbrkm41/Terminal/blob/3d7c2605818e7278453d85a2d76c3c8356dc95bb/tools/razzle.cmd#L40-L43

https://github.com/Gnbrkm41/Terminal/blob/3d7c2605818e7278453d85a2d76c3c8356dc95bb/tools/razzle.cmd#L48-L51

https://github.com/Gnbrkm41/Terminal/blob/3d7c2605818e7278453d85a2d76c3c8356dc95bb/tools/razzle.cmd#L56-L59

If we get a PR that uses `vswhere` instead of searching manually, then this won't be needed obviously

**Comment by Gnbrkm41** [comment]
oops, my bad

**Comment by DHowett-MSFT** [comment]
This will also be resolved by #606.

**Comment by Gnbrkm41** [comment]
shouldn't this be closed now? 😁

**Comment by zadjii-msft** [comment]
Yep, good catch
