### ISSUE TITLE
Being able to drag the borders of pane to resize

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5832]
# Description of the new feature/enhancement
The ability to drag the borders of the pane (once your cursor goes to the border, it becomes an arrow cursor) to resize the pane.

**Comment by Chips1234** [comment]
Oops, sorry, this is a duplicate of #992

**Comment by DHowett-MSFT** [comment]
This is a /dupe of #992, I believe. Check out the list of pane workitems in #1000!

**Comment by DHowett-MSFT** [comment]
Aw, you beat me to it.
