### ISSUE TITLE
Menu item for "Find" in context menu

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5835]
# Description of the new feature/enhancement
I've already written about this, but I was told to wait for the implementation of the menu context menu. Since the menu will be out soon, I'm going to write about it again.

**Comment by DHowett-MSFT** [comment]
/dup #5633 


There is no reason for you to close and recreate issues for the same thing. It just complicates things for us. Somebody needs to go through and copy the tags, the milestone, the discussion comments and the connections to other issues when you do that.
