### ISSUE TITLE
Context Menu does not move or close when window is moved

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5837]
# Environment

```none
Windows build number: 10.0.19624.1000
Windows Terminal version (if applicable): 0.0.1.0
```

# Steps to reproduce

Just right click on the tab and drag the window around. 

# Expected behaviour

The context menu disappears when the window is moved around, just like new tab menu flyout.

# Actual behaviour

It just stays there
![Terminal Context Menu Bug Edited](https://user-images.githubusercontent.com/47545798/81522964-40d25d00-9301-11ea-9afe-d89065094556.gif)

**Comment by zadjii-msft** [comment]
This will probably have the same resolution as #2028, which was just "dismiss the flyout when the window is dragged". Thanks!

**Comment by Don-Vito** [comment]
@zadjii-msft - this one does not reproduce as of 1.5

**Comment by zadjii-msft** [comment]
Sure doesn't! Weird. I don't remember fixing this, but it might have just be caught up in one of the other fixes. Thanks for the catch @Don-Vito!
