### ISSUE TITLE
[REGRESSION >0.11.1251] Backward-kill-word after line wrapping in powershell doesn't clear exited line properly

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#5839]
I typed "eeeeeeee.. dddddddddd.." until the line wrapped, then hit <kbd>Ctrl+Backspace</kbd>

## Before, both:

![image](https://user-images.githubusercontent.com/14316954/81533956-fdd1b300-931b-11ea-8af1-5924bdfe7031.png)

## After, 0.11.1251.0:

![image](https://user-images.githubusercontent.com/14316954/81533890-e0044e00-931b-11ea-8c5e-95745ca121ef.png)

## After, 0.11.1294.0:

![image](https://user-images.githubusercontent.com/14316954/81533929-edb9d380-931b-11ea-9d8e-53e340af8a56.png)

**Comment by zadjii-msft** [comment]
welp. Back to 1.0 investigations -.-
