### ISSUE TITLE
The VS2017 can't build success. what shou I do first?

### ISSUE THREAD

**Issue by qs991011** [microsoft/Terminal#584]
This is two tips:
>E:\visulstudio2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.InvalidPlatform.Targets(21,7): error MSB8006: 项目“propslib.vcxproj”的平台无效。  平台为“ARM64”。如果其他一些项目尝试使用针对此项目的项目到项目引用，但此项目已经卸载或未包括在解决方案中，并且引用项目不是使用相同的或等效的平台进行生成，则也可能出现此错误

错误		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\packages\Microsoft.UI.Xaml.2.1.190405001-prerelease\build\native\Microsoft.UI.Xaml.targets.	CascadiaPackage (正在加载...)	E:\ascode\Terminal-master\src\cascadia\CascadiaPackage\CascadiaPackage.wapproj	120

**Comment by sagood** [comment]
see #489

**Comment by zadjii-msft** [comment]
Try restoring the nuget packages.

![image](https://user-images.githubusercontent.com/18356694/57385601-548c3600-7178-11e9-9947-8761f6e0af9b.png)

**Comment by corylamontagne** [comment]
I tried this to no avail.
