### ISSUE TITLE
Settings.json is KO, need a fresh one

### ISSUE THREAD

**Issue by jimmypierre** [microsoft/terminal#5840]
Hi,

I keep getting : SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I cannot find any documentation to regenerate.

I can open file in Visual Studio Code

Cheers,
Jimmy

Contents :
// This file was initially generated by Windows Terminal 0.11.1251.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{2b31bbfc-067a-5da6-96de-694569bda618}",
                "hidden": false,
                "name": "SLES-15-SP1",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{1777cdf0-b2c4-5a63-a204-eb60f349ea7c}",
                "hidden": false,
                "name": "Alpine",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{46ca431a-3a87-5fb3-83cd-11ececc031d2}",
                "hidden": false,
                "name": "kali-linux",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
                "hidden": false,
                "name": "Debian",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{0110db4a-cf7b-5647-9a03-7232d80cd09e}",
                "hidden": false,
                "name": "openSUSE-Leap-15-1",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}

**Comment by pingzing** [comment]
You can find a file's location in VSCode by right clicking its tab and clicking `Reveal in Explorer`. Anecdotally, mine is in `C:\Users\<username>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`

**Comment by jimmypierre** [comment]
Hi Neil,

 

Mine is there too.

 

I posted my settings.json, is it what expected.

 

Thanks,

**Comment by DHowett-MSFT** [comment]
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

This error isn’t coming from Terminal. What software is emitting this error?

**Comment by jimmypierre** [comment]
Hiya,

When you are in terminal and that you click on settings, it opens 

file:///C:/Users/jpier/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json in a browser. 

And briefly displays the actaul settings for a fraction of a second, then displays:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

As a matter of fact, I had a doubt while reading our statement and opened settings.json in Edge and, bingo, you are right, it's the browser, nor Terminal.

Best,

**Comment by jimmypierre** [comment]
PS. I have set devtools.jsonview.enabled to false now and this works perfect.! 
Cheers,
