### ISSUE TITLE
Implemented Named sessions so `new-tab` and other commands can be executed on an existing session

### ISSUE THREAD

**Issue by darcyparker** [microsoft/terminal#5841]
# Description of the new feature/enhancement

The ability to defined a named `sessionId` to `wt`.   If the `sessionId` does not exist, a new session would be created. And if the `sesssionId` does exist, then the commands would be applied to the existing session.  This would allow users to minimize the number of `wt` windows.

# Proposed technical implementation details (optional)

As an example, if I am working in Windows explorer I could type `wt --sessionId="someSessionId"; new-tab -d .` in the address bar (or wire this command into a context menu), and it would open a new tab at the end of my existing `someSessionId` and bring my existing `wt` session to focus with the new tab in focus.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472
