### ISSUE TITLE
New tab does not work as intended

### ISSUE THREAD

**Issue by aronchick** [microsoft/terminal#5842]
# Environment
```
Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
0.11.1251.0
```

# Steps to reproduce
Open fresh windows terminal for powershell.
Type `wt.exe new-tab`
(behavior same if background-ed as well `Start-Process -NoNewWindow wt`)

# Expected behavior
Opens a new tab in the existing window.

# Actual behavior
Opens a new window.

**Comment by DHowett-MSFT** [comment]
Thanks for the report! This is a /dupe of #4472.
