### ISSUE TITLE
Tab names for SSH session to Windows 10 OpenSSH host

### ISSUE THREAD

**Issue by jonharris0n** [microsoft/terminal#5844]
# Environment

```none
Windows build number: 19041.208
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
```

# Steps to reproduce

Open a new tab by SSH to a Windows 10 OpenSSH host.

# Expected behavior

New tab title contains machine name or IP of host.  
This would help identify tabs when multiple SSH sessions are active.

# Actual behavior

New tab title contains "C:\Windows\System32\conhost.exe".
There is no SSH related host identifying information in the tab.

**Comment by DHowett-MSFT** [comment]
So, two things you can do today:

1. Configure your remote shell to put the hostname and path in the terminal title
   * This works today, and _many_ stock distribution shell configurations do this by default.
2. Wait for /dup #1079, in PR at #5775.
