### ISSUE TITLE
Installation blocked by AppLocker

### ISSUE THREAD

**Issue by jasonnutter** [microsoft/terminal#5845]
# Environment

```none
Windows build number: 10.0.19041.263 (internal MSFT ring)
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
```

# Steps to reproduce

When I started work today, Microsoft Terminal would simply not open, so I decided to uninstall and reinstall. When attempting to install via the [msixbundle](https://github.com/microsoft/terminal/releases/download/v0.11.1251.0/Microsoft.WindowsTerminal_0.11.1251.0_8wekyb3d8bbwe.msixbundle), installation failed with the following error:

<img width="489" alt="Annotation 2020-05-11 103856" src="https://user-images.githubusercontent.com/443409/81593568-81b78980-9374-11ea-8aa2-b9519fff87e4.png">

> App installation failed with error message: error 0xD0E90002: Deployment of package Microsoft.WindowsTerminal_0.11.1251.0_x64__8wekyb3d8bbwe was blocked by AppLocker. (0xd0e90002)

Installing via the Windows Store results in this error:

<img width="405" alt="Annotation 2020-05-11 104554" src="https://user-images.githubusercontent.com/443409/81593833-da872200-9374-11ea-978a-6c2bf96614dc.png">

# Expected behavior

Installation completes successfully.

# Actual behavior

Unable to install via msixbundle on Github or via Microsoft Store app.

**Comment by zadjii-msft** [comment]
Oh I hit this this morning too. There's a bug that's going around the tree, see MSFT:26335608. There's a workaround in that work item. Fortunately, this _should_ only be an internal bug 🤞

**Comment by jasonnutter** [comment]
@zadjii-msft Great, thanks for the info! I was unable to reproduce the failed installation on my personal Windows 10 machine, so seems like it may be internal only.

**Comment by jasonnutter** [comment]
Workaround linked above appears to have fixed it, thanks again!

**Comment by abhipantina** [comment]
We are seeing the same issue with one of our apps. Do you mind sharing the resolution/workaround?

**Comment by abhi-msft** [comment]
We are seeing the same issue with one of our apps. Can you help by sharing workaround/resolution?

**Comment by DHowett-MSFT** [comment]
(Handling offline.)

**Comment by Ar5ham** [comment]
I am hitting this issue as well and the workaround mentioned above doesn't seem to apply in my case. I don't have anything under the directory mentioned in the bug above.
