### ISSUE TITLE
Selected texts in Neovim on WSL are hard to read because of opaque highlighting.

### ISSUE THREAD

**Issue by leejy12** [microsoft/terminal#5846]
# Environment

```none
Windows Version 2004 (Build 19041.208)
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
Windows: Neovim v0.5.0
    WSL: Neovim v0.2.2
```
# Description
In Neovim on WSL (I'm using Ubuntu from Microsoft Store), selected texts are hard to read because the highlighting isn't transparent, unlike on PowerShell (Windows).

![ps](https://user-images.githubusercontent.com/60320918/81593123-f08af600-93f9-11ea-9deb-9b8aabfb8682.png)
![wsl](https://user-images.githubusercontent.com/60320918/81593393-59726e00-93fa-11ea-9fe8-15daba6d49f3.png)

could be a nvim issue.

**Comment by DHowett-MSFT** [comment]
This is due to NVIM intercepting the mouse clicks and handling its own selection. This is a good thing, but you will want to configure NVIM so it becomes useful for you.
