### ISSUE TITLE
Organize profiles by folder

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/terminal#5850]
I may be an edge user or perhaps just an enthusiastic user but I would like to have a way to organize my profiles into "folders" or some type of hierarchy. I currently have 11 profiles and I know this will increase. It would be very helpful to have a way to organize the layout.

Somehow the json would need on outer folder element. Maybe something like this:

```json
{
    "folder": "Foo",
    "list": [
        {
            "guid": "{a3a2e83a-884a-5379-baa8-16f193a13b21}",
            "hidden": false,
            "name": "PowerShell 7 Preview",
            "source": "Windows.Terminal.PowershellCore"
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": true,
            "useAcrylic": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        }
    ]
}
```

I suppose another way might be to extend the schema and include a new element that indicates the folder.

```json
{
    "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "hidden": true,
    "useAcrylic": false,
    "name": "Azure Cloud Shell",
    "source": "Windows.Terminal.Azure",
    "folder":"Foo"
}
```
The application would build a display based on the folder setting.

I realize this is a long term request

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
