### ISSUE TITLE
Adding powershell miniconda prompt

### ISSUE THREAD

**Issue by johncleveland** [microsoft/terminal#5852]
Having difficulties adding miniconda terminal prompt to windows terminal.

Here is what I am putting into the settings.json 

{
            // Make changes here to the cmd.exe profile
            "guid": "{8694b928-8309-4380-aee7-2a61e1bca47e}",
            "name": "Windows Anaconda",
            "commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& 'C:\\Users\\gag20\\wminiconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\gag20\\wminiconda3' \" ",
			"hidden": false
        }

From the properties of Anaconda Powershell Prompt: 

Target: 

%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\gag20\wminiconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\gag20\wminiconda3' "

error messages tend to to show up for  C:\\Users  at U.

**Comment by jdhitsolutions** [comment]
Don't forget you need to escape the \ characters in the path.

**Comment by jdhitsolutions** [comment]
"commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\\Users\\gag20\\wminiconda3\\shel\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\gag20\\wminiconda3' " ",
"hidden": false

**Comment by gilz688** [comment]
Here's how I was able to add Miniconda to Windows Terminal using the latest version of Powershell.
It's better to use %USERPROFILE% environment variable for user profile path.
```
      {
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402337}",
        "name": "Anaconda (PowerShell)",
        "icon": "ms-appx:///ProfileIcons/{574e775e-4f2a-5b96-ac1e-a2962a402336}.png",

        "fontFace": "Cascadia Code",
        "commandline": "pwsh.exe -ExecutionPolicy ByPass -NoExit -Command & '%USERPROFILE%\\Miniconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate '%USERPROFILE%\\Miniconda3'"
      },
```

**Comment by DHowett-MSFT** [comment]
Did these suggestions help?

**Comment by johncleveland** [comment]
After changing pwsh.exe to powershell.exe (I probably don't have the latest version.) @gilz688 's suggestion worked like a charm!

**Comment by peter197321** [comment]
it seems not working 👎

**Comment by peter197321** [comment]
& : The term 'C:\Miniconda3\shell\condabin\conda-hook.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:3
+ & 'C:\Miniconda3\shell\condabin\conda-hook.ps1' ; cond ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\conda-hook.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:66
+ ... rs\Miniconda3\shell\condabin\conda-hook.ps1' ; conda activat ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\System32>

**Comment by DHowett** [comment]
Well, is C:\Miniconda3\ where you’ve installed miniconda3?

**Comment by peter197321** [comment]
I don't use minconda3 :(

**Comment by DHowett** [comment]
Ah, that might be why. Thanks!

It looks like we have documentation on this in our repository in the [Third-party tool profiles document](https://github.com/microsoft/terminal/blob/master/doc/user-docs/ThirdPartyToolProfiles.md#anaconda).

It's not easy to provide generic advice in this matter, because it is possible to install Anaconda with any number of  and in any location on your system. This is why there's no single source of truth or single source of information on how to do it.

I did a quick internet search for "windows terminal anaconda", and it provided me with a couple suggestions:

* [this blog post, about adding Anaconda to WT](https://dev.to/azure/easily-add-anaconda-prompt-in-windows-terminal-to-make-life-better-3p6j)
* [this other blog post, about adding Anaconda to WT](https://blog.jcharistech.com/2020/01/09/how-to-add-anaconda-to-windows-terminal-for-data-science/)

**Comment by peter197321** [comment]
MSFT closed issue and min. support from their side :( I try to look over the web - I'm disappointed to use their system which is enforced by the employer...

**Comment by DHowett** [comment]
My dude, I am from Microsoft and I am _trying to help you_.

![image](https://user-images.githubusercontent.com/189190/92506776-d18b4d80-f1ba-11ea-863e-1668e753d1b5.png)

All three of the links I gave you above explain how to get Anaconda working in Terminal.

**Comment by peter197321** [comment]
Thank you a lot :)

**Comment by vuhuy** [comment]
Leaving this behind for the next time I format my Windows. Updated snippet for latest Miniconda 3, with the icon, name and command line values sourced from the Anaconda Powershell Prompt shortcut that the installer creates. Generate a fresh new GUID if you like. Adjust path to `powershell.exe` when needed (example should work for default Windows 11 24H2 installation).

When installed for all users (system wide):

```
{
    "guid": "{9f7fe069-6875-40b9-a5aa-ebcea44a705e}",
    "hidden": false,
    "name": "Anaconda PowerShell Prompt",
    "commandline": "%WINDIR%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& '%ALLUSERSPROFILE%\\miniconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate '%ALLUSERSPROFILE%\\miniconda3' \"",
    "startingDirectory": "%USERPROFILE%",
    "icon": "%ALLUSERSPROFILE%\\miniconda3\\Menu\\anaconda_powershell_prompt.ico"
}
```

When installed for current user (just me):

```
{
    "guid": "{b417efa2-de5e-46fe-b2db-6e0c88587683}",
    "hidden": false,
    "name": "Anaconda PowerShell Prompt",
    "commandline": "%WINDIR%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& '%USERPROFILE%\\miniconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate '%USERPROFILE%\\miniconda3' \"",
    "startingDirectory": "%USERPROFILE%",
    "icon": "%USERPROFILE%\\miniconda3\\Menu\\anaconda_powershell_prompt.ico"
}
```
