### ISSUE TITLE
My terminal does not react when I have closed a tab keyboard also

### ISSUE THREAD

**Issue by EugeneLockett** [microsoft/terminal#5854]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Open a new tab and drag the tab, then close the tab with Ctrl Shift W

# Expected behavior
Windows Terminal should react

# Actual behavior
Windows Terminal doesn't react

**Comment by EugeneLockett** [comment]
I hope I haven't made a mistake here.

**Comment by DHowett-MSFT** [comment]
In the middle of dragging the tab?

**Comment by EugeneLockett** [comment]
What exactly do you mean?

**Comment by EugeneLockett** [comment]
Do you think if I pull the tab and press Ctrl Shift W?

**Comment by DHowett-MSFT** [comment]
Correct. Are you pressing Ctrl+Shift+W _while the tab is being dragged_

**Comment by EugeneLockett** [comment]
Yes

**Comment by DHowett-MSFT** [comment]
1. Why would you do that?
2. You're not the first person to report this :smile:

**Comment by EugeneLockett** [comment]
I don't understand you. You mean that one person has already reported it. If so, it's good but the problem still exists.

**Comment by EugeneLockett** [comment]
i wanted to be the first, but well the first person to report this bug

**Comment by EugeneLockett** [comment]
What will happen next? DHowett

**Comment by DHowett-MSFT** [comment]
I am asking "why are you closing it WHILE you are dragging it?" because that behavior is confusing to me. :smile:

**Comment by EugeneLockett** [comment]
I also wanted to try to find problems that would motivate me and make me learn more about the world. DHowett

**Comment by EugeneLockett** [comment]
I want to develop great applications in the future.

**Comment by EugeneLockett** [comment]
I hope that my first answer will answer your question

**Comment by DHowett-MSFT** [comment]
Thank you!

It looks like this is the same issue as #5559, so I am going to call it a "duplicate".

/dup #5559.
