### ISSUE TITLE
Open new tab as Administrator

### ISSUE THREAD

**Issue by GlenNicholson** [microsoft/terminal#5862]
When opening a new tab would it be possible to have the following options:
- Windows PowerShell
- Windows PowerShell (Administrator)
- cmd
- cmd (Administrator)
- Azure Cloud Shell

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #632 for more discussion.

/dup #632
