### ISSUE TITLE
Drag and drop to paste

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#5863]
# Description of the new feature/enhancement

Drag text from external source and drop to paste inside the terminal.

# A clear and concise description of what you want to happen.

![1](https://user-images.githubusercontent.com/4319522/81722553-8866ff00-944f-11ea-953c-b7ea179a9083.gif)

**Comment by zadjii-msft** [comment]
Yea that makes sense to me.

**Comment by musm** [comment]
wow that was quick thanks so much!

**Comment by musm** [comment]
It looks like this made in the 1.0 release, yet it isn't working for me.

Is it supposed to work in Powershell 7?

**Comment by DHowett** [comment]
I mean, again, as far as we can tell, _this works and will work and should work._

Drag and drop from a non-admin process into an admin process _will never work._

**Comment by DHowett** [comment]
Sorry, I got this mixed up with a separate issue!

This one did not make it into v1. We branched off to stabilize the release a month ago :smile:

**Comment by musm** [comment]
> This one did not make it into v1. We branched off to stabilize the release a month ago 😄

I also tried the preview version and that also didn't work for some reason

**Comment by DHowett** [comment]
The preview version is the same as the stable version until the first update.
