### ISSUE TITLE
Terminal crashes when tabs are closed

### ISSUE THREAD

**Issue by EugeneLockett** [microsoft/terminal#5869]
# Environment

```none
Windows build number: 10.0.18363.815
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
```

# Steps to reproduce
Start Terminal, then create 10 or many tabs, and then close one tab at a time.

# Expected behavior
Terminal shouldn't crash

# Actual behavior
Terminal crashes

**Comment by DHowett-MSFT** [comment]
Also, are you closing them with the mouse? Clicking the “x” or middle clicking? Are you deliberately closing one at a time or are you closing them as fast as humanly possible?
