### ISSUE TITLE
Crashes and missing text when using tmux

### ISSUE THREAD

**Issue by kasper93** [microsoft/terminal#5871]
# Environment

```none
Windows build number: 10.0.18363.815 (fun fact, PS actually reports 10.0.18363.0)
Windows Terminal revision: 88ed94d2acea5f1274800378e9d7662de9015c28

Latest cygwin with latest openssh client,
```

So I did update my terminal and it broke my workflow with tmux.

# Steps to reproduce

1. Run tmux (I use it in remote session over ssh)
1. Split panes, add some windows.
1. Zoom pane, change window in tmux
1. Resize Terminal window

# Expected behavior

Everything redraws correctly and doesn't crash.

# Actual behavior

1. Things doesn't draw correctly. Generally it is broken, not much to explain. Some things are drawn, other doesn't. 
1. Terminal will crash resize its window with tmux open. Maybe not instantly, but text blinks during resize, some disappear and eventually will crash. More panes probably will make it crash faster.

**Comment by DHowett-MSFT** [comment]
Since it looks like you've built terminal at a specific commit, I have to assume you've got Visual Studio and can help grab a call stack or logs from the debug build. Would you mind?

**Comment by kasper93** [comment]
In release build it fails here:
https://github.com/microsoft/terminal/blob/b4c33dd84260e3a4883ca179be97a94420fedab2/src/buffer/out/textBuffer.cpp#L277
```
F:\dev\terminal\src\buffer\out\textBuffer.cpp(277)\TerminalControl.dll!00007FFC36C47E83: (caller: 00007FFC36C4C42B) FailFast(1) tid(3718) 8000FFFF Catastrophic failure
Unhandled exception at 0x00007FFC36C47E83 (TerminalControl.dll) in WindowsTerminal.exe: Fatal program exit requested.
```

In debug it is very slow to resize window, but it crashes still:
```
F:\dev\terminal\src\cascadia\TerminalConnection\ConptyConnection.cpp(347)\TerminalConnection.dll!00007FFC32193309: (caller: 00007FFC321F46F0) Exception(1) tid(4d20) 800700E8 The pipe is being closed.
    [winrt::Microsoft::Terminal::TerminalConnection::implementation::ConptyConnection::Resize(ConptyResizePseudoConsole(_hPC.get(), { Utils::ClampToShortMax(columns, 1), Utils::ClampToShortMax(rows, 1) }))]
Exception thrown at 0x00007FFCA3C1A799 in WindowsTerminal.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000042562FBC50.
Exception thrown at 0x00007FFCA3C1A799 in WindowsTerminal.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
TerminalConnection.dll!00007FFC322976DC: ReturnHr(1) tid(4d20) 800700E8 The pipe is being closed.
    Msg:[F:\dev\terminal\src\cascadia\TerminalConnection\ConptyConnection.cpp(347)\TerminalConnection.dll!00007FFC32193309: (caller: 00007FFC321F46F0) Exception(1) tid(4d20) 800700E8 The pipe is being closed.
    [winrt::Microsoft::Terminal::TerminalConnection::implementation::ConptyConnection::Resize(ConptyResizePseudoConsole(_hPC.get(), { Utils::ClampToShortMax(columns, 1), Utils::ClampToShortMax(rows, 1) }))]
] 
Exception thrown at 0x00007FFCA3C1A799 (KernelBase.dll) in WindowsTerminal.exe: WinRT originate error - 0x800700E8 : 'The pipe is being closed.'.
Exception thrown at 0x00007FFCA3C1A799 in WindowsTerminal.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00000042562FD450.
Exception thrown at 0x00007FFCA3C1A799 in WindowsTerminal.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
TerminalControl.dll!00007FFC3268675C: ReturnHr(1) tid(4d20) 800700E8 The pipe is being closed.
    Msg:[winrt::hresult_error: The pipe is being closed.] 
Unhandled exception at 0x00007FFC98373530 (Windows.UI.Xaml.dll) in WindowsTerminal.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001D2F73B4BD0, 0x0000000000000002).
```

Please give me pointer if you want me to look at something specific.

**Comment by DHowett-MSFT** [comment]
Interesting. This has the same callstack as #4907.

Are you displaying wide glyphs in tmux?

**Comment by kasper93** [comment]
> Are you displaying wide glyphs in tmux?

Which one are those? I use zsh with powerlevel10k theme. And indeed with bash without fancy things it works fine. Also I have status indicator on the right side. And this seem to mess with rendering.

**Comment by DHowett-MSFT** [comment]
That's really interesting! Thanks for the info.

Would you share some of the glyphs that are in your powerlevel10k theme?

I'll mark this as a /dup of #4907 in the meantime -- same call stack, same symptoms, same repro (go wild on resizing with garb in the buffer)
