### ISSUE TITLE
[Feature Request] Switch tab by click at top edge of window when maximized

### ISSUE THREAD

**Issue by hzhangxyz** [microsoft/terminal#5872]
# Description of the new feature/enhancement

currently, when I maximize the window, and I cannot switch tab by click the top edge, which is inconvenient, and I have to move my mouse a little down to switch. in other product such as chrome, the tab table is against the top edge.

**Comment by maximousblk** [comment]
This gets annoying at times when working with different tabs and you have to do some back and forth tasks.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2541 for more discussion.

/dup #2541
