### ISSUE TITLE
Mechanism to send code to the active tab of the terminal 

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#5873]
# Description of the new feature/enhancement

I'd love to get https://github.com/randy3k/SendCode to be compatible with the new Termal. In order to accomplish this we need a way to:

1 Send code to the active tab of the terminal.
2. Bracketed paste mode. (https://github.com/microsoft/terminal/issues/395)

**Comment by zadjii-msft** [comment]
By any chance, is #3799 what you're looking for here?

**Comment by musm** [comment]
I don't believe that covers what is required here

**Comment by DHowett-MSFT** [comment]
I mean, this should absolutely be possible through clipboard stuffing and key binding stuffing today. I'm not sure how we can make this easier as there isn't really an IPC mechanism available to us that'll make SendCode's life easier.
