### ISSUE TITLE
Does not accept keyboard input

### ISSUE THREAD

**Issue by arlandi1974** [microsoft/terminal#5876]
# Environment

Windows build number: Microsoft Windows [Version 10.0.19041.208]
Windows Terminal version (if applicable): 0.11.1251.0

Any other software?
No

# Steps to reproduce
Open Windows Terminal from Start menu
Start typing

# Expected behavior
Terminal accepts keyboard input

# Actual behavior
Terminal does not accept any keyboard input for any type of terminal (Powershell, regular Command Prompt and Ubuntu), even after Repair and Reset the App

**Comment by DHowett-MSFT** [comment]
This sounds like /dup #4448 -- can you capture a trace using the instructions in that comment thread? Thanks!
