### ISSUE TITLE
Uninstalling WSL breaks Terminal

### ISSUE THREAD

**Issue by BenConstable9** [microsoft/terminal#5877]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.208]
Windows Terminal version (if applicable): 0.11.1251.0

Any other software? WSL with Ubuntu
```

# Steps to reproduce

Uninstall WSL distros that are included automatically in the list available on Terminal.

# Expected behavior

Terminal should function as usual and remove uninstalled distro from the list.

# Actual behavior

Terminal freezes and the dropdown list will not respond to user input. Closing and reopening did not resolve. Resolved by uninstalling and reinstalling.

**Comment by DHowett-MSFT** [comment]
Sorry, have you uninstalled the _distributions_ or have you uninstalled the entire WSL feature from Windows?

**Comment by BenConstable9** [comment]
> Sorry, have you uninstalled the _distributions_ or have you uninstalled the entire WSL feature from Windows?

I uninstall a distribution to change from Ubuntu to another Linux distro. Issue happened before I even had installed new one. Uninstalled through Settings panel like MSFT recommends.

**Comment by DHowett-MSFT** [comment]
Would you mind sharing the document you were referring to?

**Comment by BenConstable9** [comment]
https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-uninstall-a-wsl-distribution

That is where I found it.

**Comment by zadjii-msft** [comment]
We've made a ton of changes to how we enumerate WSL's, how we initialize controls, etc, etc, that makes me think this probably won't be an issue anymore. @BenConstable9 you still seeing this on 1.11+?
