### ISSUE TITLE
Can't write vertical slash (pipe) with ssh to Centos7

### ISSUE THREAD

**Issue by effolkronium** [microsoft/terminal#5878]
Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.30]
Windows Terminal version (if applicable): 0.11.1251.0
Russian default windows language

ssh default windows
```

# Steps to reproduce
Install centos7 (vmware for me)

ssh CENTOT_IP -l root

try to write '|' or '@' symbols. Nothing happens. No symbols was written. (The same if i copy paste string with those symbols. The resulting string in terminal is without | or @ symbols (((

**BUT It works with cmd.exe !!!!!!**

My config:

// This file was initially generated by Windows Terminal 0.11.1251.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Командная строка",
                "commandline": "cmd.exe",
                "hidden": false,
                "foreground": "#00FFFF"

            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}

centos version:
[root@dr-team-runner ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

Also, i've installed c++ and svn extensions to centos via VSCODE via SSH.

**Comment by DHowett-MSFT** [comment]
This sounds like an issue that should be filed on the [Win32-OpenSSH issue tracker](https://github.com/PowerShell/Win32-OpenSSH/issues). I bet it works better with SSH 8.1 or 8.2 from their [releases page](https://github.com/PowerShell/Win32-OpenSSH/releases)

**Comment by effolkronium** [comment]
No no no, it works with cmd.exe and do not work with win10 terminal

**Comment by effolkronium** [comment]
But when i reinstall terminal it works. 

idk, but after some time it prevent typing symbols like @ or $

**Comment by zadjii-msft** [comment]
@effolkronium Are you still seeing this? This must have slipped out of our triage queue somehow, sorry about this. 

>  after some time it prevents typing symbols like @ or $

That's very weird, but I'd suspect that's an issue with `ssh` or something external to the Terminal. I have no idea why those would stop working over time... Maybe they stop working after entering/exiting something like `vim`?

**Comment by effolkronium** [comment]
Well, sometimes it worked. Like after process restart. I don't remember for sure, probably u can close ticket.

I'm using Hyper now, and sometimes it also has the issue, so looks like the issue in ssh

**Comment by zadjii-msft** [comment]
> I'm using Hyper now, and sometimes it also has the issue, so looks like the issue in ssh

Well that's a pretty good confirmation that it's not an issue in our code 😅 thanks for following up!
