### ISSUE TITLE
Select the cli at startup

### ISSUE THREAD

**Issue by juliomorales-drone** [microsoft/terminal#5879]
# Description of the new feature/enhancement
If terminal is pinned to the task bar, you right click to get a list of cli to run

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Could you possibly mean #576?

**Comment by juliomorales-drone** [comment]
yes, that's what I'm talking about

**Comment by zadjii-msft** [comment]
Perfect - I'll close this one as a duplicate than. Thanks for following up!

/dup #576
