### ISSUE TITLE
How to increase de log buffer on settings.json

### ISSUE THREAD

**Issue by fischerdouglas** [microsoft/terminal#5885]
I have made a considerable search on the docs on github of the Windows Terminal and I didn't find the way to increase the log buffer of the sessions.
I din't find the attribute on the settings.json

I work with network devices configurations, and some equipment have tens o thousand lines...
If I need to get all the config on the buffer, it cuts the beginning of the config...

For what I could see, it just keep +/-9000 lines on the buffer.

How to increase it?

**Comment by zadjii-msft** [comment]
Perhaps try the `historySize` setting?

From [the docs:
](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#profiles)
Property | Necessity | Type | Default | Description
-- | -- | -- | -- | --
historySize | Optional | Integer | 9001 | The number of lines above the ones displayed in the window you can scroll back to.

**Comment by fischerdouglas** [comment]
It Worked!
Sorry... I Acted like a noobie... But I didn't searched for other words the "log" an "buffer"...

Maybe fits here a suggestion to improve the description of that property?

**Comment by DHowett-MSFT** [comment]
We'll make sure the documentation is improved here. Thanks!
