### ISSUE TITLE
Select all the buffer - Equivalent to CTRL+A or Command+A

### ISSUE THREAD

**Issue by fischerdouglas** [microsoft/terminal#5886]
Several times I need to copy all the buffer of a session to the clipboard.

Actually on Windows terminal, to get all the buffer copyed, I need to scrooll back to the top, click on the begging, hold shift, scroll to the end, and then copy all the buffer.

O putty a simple right-click on the title bar gives-me that option.

I'm Migrating from MacOS, and there Command+A is different from CTRL+A.
 - CTRL+A could means some special command to the remote session.
 - WinKey+A (equivalent to Command+A from MacOS) is a special Key combination of Operational system.

I searched for it on the docs, and I did't find anything.
I tried to guess the key combination, but I had no success.

How do I copy all the buffer without and hercúleos effort?

**Comment by zadjii-msft** [comment]
Huh, okay I don't think we actually have an issue for this. 
Fortunately, I do think we have a PR for it here:#3758

**Comment by carlos-zamora** [comment]
Fortunately, I recently did a whole scan of our repo for work I can do haha. This is a /dup of #1469.

**Comment by csabka** [comment]
Workaround similar to [this](https://superuser.com/questions/1560181/hotkey-menu-to-select-all-and-copy-text-in-the-windows-terminal-app) so you don't need to scroll by hand

1. Press Ctrl+Shift+Home
2. Select first n char with mouse and hold the mouse button
3. Press Ctrl+Shift+End (still holding the mouse button during selection)
4. Move mouse to the end of the screen

Whole Terminal scrollback + screen should be selected (and can be copied)

**Comment by ThomsonTan** [comment]
> Workaround similar to [this](https://superuser.com/questions/1560181/hotkey-menu-to-select-all-and-copy-text-in-the-windows-terminal-app) so you don't need to scroll by hand
> 
> 1. Press Ctrl+Shift+Home
> 2. Select first n char with mouse and hold the mouse button
> 3. Press Ctrl+Shift+End (still holding the mouse button during selection)
> 4. Move mouse to the end of the screen
> 
> Whole Terminal scrollback + screen should be selected (and can be copied)

Is there an easy way to press Ctrl+Shift+End while still holding the mouse button during selection? Or need some key map for helping?

**Comment by extratype** [comment]
1. Press Ctrl+Shift+Home
2. Select first n char with mouse
3. Press Ctrl+Shift+End
4. While holding Shift click the end of the last line

It looks like only the last line is selected, but actually all lines are selected :)
