### ISSUE TITLE
CTRL+f Search in Buffer

### ISSUE THREAD

**Issue by fischerdouglas** [microsoft/terminal#5890]
# Description of the new feature/enhancement

A way to search in buffer of local session for some string.
It could/should be triggered by a key combination (like CTRL+f, as in all other apps).

# Proposed technical implementation details (optional)

Once again: "Nothing is created, everything is copied."
So, in Iterm2 we have the feature:

Regular Expression Search
When you open the find field (cmd-f) there is a down-arrow on the left of the field by the magnifying glass. Clicking it opens a menu of options in which you can enable regular expression search. The ICU syntax is used.

Source -> https://www.iterm2.com/documentation-one-page.html

On the first moment a simple string match is OK.
But regular expression is "the way and the truth and the life". So this would be a great idea.

Visual Studio supports regular expression based searchs!
Maybe this link could be inspiring:
https://docs.microsoft.com/pt-br/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019

An extra ideia is:
- Search only on local buffer.
- Search on the buffer of all the open tabs.

**Comment by fischerdouglas** [comment]
Default Powershell App has a dummy CTRL+F

![image](https://user-images.githubusercontent.com/7989601/81858122-998c3a80-9539-11ea-8c38-725e624251d4.png)

The CTRL+F doesn`t actualy works as expect.
(It sends a ^F to the input)

You need to Rigth-Click on Title bar -> Edit -> Find
But at least i can search with it.

(Sorry, I'm using pt_BR as my default Language.)
![image](https://user-images.githubusercontent.com/7989601/81858348-fee02b80-9539-11ea-88ad-443925c674fb.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is something we already support today - it's bound to <kbd>Ctrl+shift+f</kbd> [by default](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L279). As far as improvements go, we've got #3920 tracking a number of improvements, including:

> * [ ] Add "Find" button in dropdown menu to trigger search. Now the search dialog is launched by key bindings, we may need to consider binding the dialog to a button in dropdown menu for mouse only operations. 
> * [ ] Search from all tabs. In phase one search are limited within one Terminal window. However, the community also requests search from all tabs. This may require a big change to the search algorithm. 
> * [ ] Regular expression match. This is a useful search pattern and is implemented in some editors.
> * [ ] Search history. Sometimes users would do the same search for several times, thus, storing the search history is useful.
> * [ ] High-light while you type. Emphasizing all the matches in the buffer with an outline or selection with another color. This provides a clearer view of the searched text.
> * [ ] Add size handle. Some text editors let the user resize the search box, and there is a size handle on the left side of the search box. This helps user when they search for long text.
> * [ ] #5314 Fuzzy Search 

/dup #3920

**Comment by fischerdouglas** [comment]
Hey man...
I'm feeling stupid... I'm doing questions and suggestions that are already replied/solved.

I'm used to that exhausting docs from MS products... (like exchange, or sql-server)

I don't know what docs I need to read to stop that stupid questions about Windows Terminal.
(Please don't tell-me that the recommended reading is all the issues related to the project)

**Comment by DHowett-MSFT** [comment]
Sorry about that. As of today, all our documentation is in the `user-docs` folder on this repository and in the settings files. The default settings file has an explicit callout for search :smile:

We're working on making sure our documentation is available, discoverable and accessible.

**Comment by yanke1311** [comment]
when I use ctrl+shift+f, I can no longer  find any change, and in setting I really have setted key-binding of "find", I don't know  what  happend?

**Comment by DHowett** [comment]
Can you share your settings file?

**Comment by yanke1311** [comment]
@DHowett   // To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
  "$schema": "https://aka.ms/terminal-profiles-schema",
  "defaultProfile": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
  "fontFace": "DejaVu Sans Mono",
  "profiles": [
    {
      // Make changes here to the powershell.exe profile
      "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
      "hidden": false,
      "name": "Windows PowerShell",
      "fontFace": "Monaco",
      "fontSize": 11,
      "commandline": "powershell.exe",
      "colorScheme": "Gruvbox Dark",
      "useAcrylic": true,
      "acrylicOpacity": 0.9
    },
    {
      // Make changes here to the cmd.exe profile
      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
      "name": "cmd",
      "commandline": "cmd.exe",
      "hidden": false
    },
    {
      "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
      "hidden": false,
      "name": "Azure Cloud Shell",
      "source": "Windows.Terminal.Azure"
    },
    {
      "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
      "hidden": false,
      "name": "Ubuntu-18.04",
      "fontFace": "Monaco",
      "fontSize": 11,
      "source": "Windows.Terminal.Wsl",
      "colorScheme": "Gruvbox Dark",
      "useAcrylic": true,
      "acrylicOpacity": 0.9,
      "icon": "ms-appdata:///roaming/ubuntu_32px.png"
    },
    {
      "guid": "{a5a97cb8-8961-5535-816d-772efe0c6a3f}",
      "hidden": false,
      "name": "Arch",
      "source": "Windows.Terminal.Wsl"
    }
  ],
  // Add custom color schemes to this array
  "schemes": [
    {
      "background": "#282A36",
      "black": "#21222C",
      "blue": "#F1FA8C",
      "brightBlack": "#6272A4",
      "brightBlue": "#D6ACFF",
      "brightCyan": "#A4FFFF",
      "brightGreen": "#69FF94",
      "brightPurple": "#FF92DF",
      "brightRed": "#FF6E6E",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#FFFFA5",
      "cyan": "#8BE9FD",
      "foreground": "#F8F8F2",
      "green": "#50FA7B",
      "name": "Dracula",
      "purple": "#BD93F9",
      "red": "#FF5555",
      "white": "#F8F8F2",
      "yellow": "#F1FA8C"
    },
    {
      "name": "Cobalt Neon",
      "black": "#142631",
      "red": "#ff2320",
      "green": "#3ba5ff",
      "yellow": "#e9e75c",
      "blue": "#8ff586",
      "purple": "#781aa0",
      "cyan": "#8ff586",
      "white": "#ba46b2",
      "brightBlack": "#fff688",
      "brightRed": "#d4312e",
      "brightGreen": "#8ff586",
      "brightYellow": "#e9f06d",
      "brightBlue": "#3c7dd2",
      "brightPurple": "#8230a7",
      "brightCyan": "#6cbc67",
      "brightWhite": "#8ff586",
      "background": "#142838",
      "foreground": "#8ff586"
    },
    {
      "name": "Violet Light",
      "black": "#56595c",
      "red": "#c94c22",
      "green": "#85981c",
      "yellow": "#b4881d",
      "blue": "#2e8bce",
      "purple": "#d13a82",
      "cyan": "#32a198",
      "white": "#d3d0c9",
      "brightBlack": "#45484b",
      "brightRed": "#bd3613",
      "brightGreen": "#738a04",
      "brightYellow": "#a57705",
      "brightBlue": "#2176c7",
      "brightPurple": "#c61c6f",
      "brightCyan": "#259286",
      "brightWhite": "#c9c6bd",
      "background": "#fcf4dc",
      "foreground": "#536870"
    },
    {
      "name": "Gruvbox Dark",
      "black": "#1e1e1e",
      "red": "#be0f17",
      "green": "#868715",
      "yellow": "#cc881a",
      "blue": "#377375",
      "purple": "#a04b73",
      "cyan": "#578e57",
      "white": "#978771",
      "brightBlack": "#7f7061",
      "brightRed": "#f73028",
      "brightGreen": "#aab01e",
      "brightYellow": "#f7b125",
      "brightBlue": "#719586",
      "brightPurple": "#c77089",
      "brightCyan": "#7db669",
      "brightWhite": "#e6d4a3",
      "background": "#1e1e1e",
      "foreground": "#e6d4a3"
    },
    {
      "name": "Ubuntu",
      "foreground": "#EEEEEE",
      "background": "#2C001E",
      "colors": [
        "#4E9A06",
        "#CC0000",
        "#300A24",
        "#C4A000",
        "#3465A4",
        "#75507B",
        "#06989A",
        "#D3D7CF",
        "#555753",
        "#EF2929",
        "#8AE234",
        "#FCE94F",
        "#729FCF",
        "#AD7FA8",
        "#34E2E2",
        "#EEEEEE"
      ]
    },
    {
      "name": "MaterialOcean",
      "black": "#546e7a",
      "red": "#ff5370",
      "green": "#c3e88d",
      "yellow": "#ffcb6b",
      "blue": "#82aaff",
      "purple": "#c792ea",
      "cyan": "#89ddff",
      "white": "#ffffff",
      "brightBlack": "#546e7a",
      "brightRed": "#ff5370",
      "brightGreen": "#c3e88d",
      "brightYellow": "#ffcb6b",
      "brightBlue": "#82aaff",
      "brightPurple": "#c792ea",
      "brightCyan": "#89ddff",
      "brightWhite": "#ffffff",
      "background": "#0f111a",
      "foreground": "#8f93a2"
    },
    {
      "name": "Pip-Boy",
      "black": "#012026",
      "red": "#2aea5e",
      "green": "#2aea5e",
      "yellow": "#2aea5e",
      "blue": "#2aea5e",
      "purple": "#2aea5e",
      "cyan": "#2aea5e",
      "white": "#2aea5e",
      "brightBlack": "#2aea5e",
      "brightRed": "#2aea5e",
      "brightGreen": "#2aea5e",
      "brightYellow": "#2aea5e",
      "brightBlue": "#2aea5e",
      "brightPurple": "#2aea5e",
      "brightCyan": "#2aea5e",
      "brightWhite": "#2aea5e",
      "background": "#001015",
      "foreground": "#2aea5e"
    },
    {
      "name": "Nord",
      "foreground": "#D8DEE9",
      "background": "#2E3440",
      "black": "#3B4252",
      "red": "#BF616A",
      "green": "#A3BE8C",
      "yellow": "#EBCB8B",
      "blue": "#81A1C1",
      "purple": "#B48EAD",
      "cyan": "#88C0D0",
      "white": "#E5E9F0",
      "brightBlack": "#4C566A",
      "brightRed": "#BF616A",
      "brightGreen": "#A3BE8C",
      "brightYellow": "#EBCB8B",
      "brightBlue": "#81A1C1",
      "brightPurple": "#B48EAD",
      "brightCyan": "#88C0D0",
      "brightWhite": "#E5E9F0"
    }
  ],
  // Add any keybinding overrides to this array.
  // To unbind a default keybinding, set the command to "unbound"
  "keybindings": [
    {
      "command": "copy",
      "keys": ["ctrl+c"]
    },
    // {
    //     "command": "paste",
    //     "keys": [
    //         "ctrl+v"
    //     ]
    // },
    {
      "command": "nextTab",
      "keys": ["ctrl+pgdn"]
    },
    {
      "command": "prevTab",
      "keys": ["ctrl+pgup"]
    },
    {
      "command": "newTab",
      "keys": ["ctrl+shift+t"]
    },
    {
      "command": "newTabProfile0",
      "keys": ["ctrl+shift+1"]
    },
    {
      "command": "newTabProfile1",
      "keys": ["ctrl+shift+2"]
    },
    {
      "command": "newTabProfile2",
      "keys": ["ctrl+shift+3"]
    },
    {
      "command": "newTabProfile3",
      "keys": ["ctrl+shift+4"]
    },
    {
      "command": "newTabProfile4",
      "keys": ["ctrl+shift+5"]
    },
    {
      "command": "newTabProfile5",
      "keys": ["ctrl+shift+6"]
    },
    {
      "command": "newTabProfile6",
      "keys": ["ctrl+shift+7"]
    },
    {
      "command": "newTabProfile7",
      "keys": ["ctrl+shift+8"]
    },
    {
      "command": "newTabProfile8",
      "keys": ["ctrl+shift+9"]
    },
    {
      "command": "switchToTab0",
      "keys": ["alt+1"]
    },
    {
      "command": "switchToTab1",
      "keys": ["alt+2"]
    },
    {
      "command": "switchToTab2",
      "keys": ["alt+3"]
    },
    {
      "command": "switchToTab3",
      "keys": ["alt+4"]
    },
    {
      "command": "switchToTab4",
      "keys": ["alt+5"]
    },
    {
      "command": "switchToTab5",
      "keys": ["alt+6"]
    },
    {
      "command": "switchToTab6",
      "keys": ["alt+7"]
    },
    {
      "command": "switchToTab7",
      "keys": ["alt+8"]
    },
    {
      "command": "switchToTab8",
      "keys": ["alt+9"]
    },
    {
      "command": { "action": "splitPane", "split": "vertical" },
      "keys": ["ctrl+shift+v"]
    },
    {
      "command": { "action": "splitPane", "split": "horizontal" },
      "keys": ["ctrl+shift+h"]
    },
    // {
    //     "command": "closeTab",
    //     "keys": [
    //         "ctrl+shift+w"
    //     ]
    // },
    {
      "command": { "action": "moveFocus", "direction": "down" },
      "keys": "alt+down"
    },
    {
      "command": { "action": "moveFocus", "direction": "left" },
      "keys": "alt+left"
    },
    {
      "command": { "action": "moveFocus", "direction": "right" },
      "keys": "alt+right"
    },
    {
      "command": { "action": "moveFocus", "direction": "up" },
      "keys": "alt+up"
    },
    {
      "command": "resizePaneUp",
      "keys": ["ctrl+alt+up"]
    },
    {
      "command": "resizePaneDown",
      "keys": ["ctrl+alt+down"]
    },
    {
      "command": "resizePaneLeft",
      "keys": ["ctrl+alt+left"]
    },
    {
      "command": "resizePaneRight",
      "keys": ["ctrl+alt+right"]
    },
    {
      "command": "closePane",
      "keys": ["ctrl+m"]
    },
    {
      "command": "scrollUp",
      "keys": ["ctrl+up"]
    },
    {
      "command": "scrollUpPage",
      "keys": ["ctrl+shift+up"]
    },
    {
      "command": "scrollDown",
      "keys": ["ctrl+down"]
    },
    {
      "command": "scrollDownPage",
      "keys": ["ctrl+shift+down"]
    },

    {
      "command": "find",
      "keys": "ctrl+shift+f"
    }
  ]
}

**Comment by DHowett** [comment]
I'm sorry, you put it into your json file with the three &#x60;&#x60;&#x60; in it? Don't do that.

Also, it looks like you have a _very old version of terminal settings_. You might be a lot happier if you migrate to the new format (back up the things you care about, delete the file, and let Terminal make a new one.)

**Comment by yanke1311** [comment]
so strange , even I migrate to the new format, "find" is still not work

**Comment by DHowett** [comment]
Okay can you share your _new_ settings file?

**Comment by yanke1311** [comment]
// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
  "$schema": "https://aka.ms/terminal-profiles-schema",

  "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

  // You can add more global application settings here.
  // To learn more about global settings, visit https://aka.ms/terminal-global-settings

  // If enabled, selections are automatically copied to your clipboard.
  "copyOnSelect": false,

  // If enabled, formatted data is also copied to your clipboard
  "copyFormatting": false,

  // A profile specifies a command to execute paired with information about how it should look and feel.
  // Each one of them will appear in the 'New Tab' dropdown,
  //   and can be invoked from the commandline with `wt.exe -p xxx`
  // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
  "profiles": {
    "defaults": {
      // Put settings here that you want to apply to all profiles.
    },
    "list": [
      {
        // Make changes here to the powershell.exe profile.
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell",
        "commandline": "powershell.exe",
        "hidden": false,
        "fontFace": "Monaco",
        "fontSize": 11,
        // "colorScheme": "Gruvbox Dark",
        "useAcrylic": true,
        "acrylicOpacity": 0.9
      },
      {
        // Make changes here to the cmd.exe profile.
        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "name": "命令提示符",
        "commandline": "cmd.exe",
        "hidden": false
      },
      {
        "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
        "hidden": false,
        "name": "Ubuntu-18.04",
        "source": "Windows.Terminal.Wsl",
        "fontFace": "Monaco",
        "fontSize": 11,
        // "colorScheme": "Gruvbox Dark",
        "useAcrylic": true,
        "acrylicOpacity": 0.9,
        "icon": "ms-appdata:///roaming/ubuntu_32px.png"
      },
      {
        "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
        "hidden": false,
        "name": "Azure Cloud Shell",
        "source": "Windows.Terminal.Azure"
      }
    ]
  },

  // Add custom color schemes to this array.
  // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
  "schemes": [],

  // Add custom keybindings to this array.
  // To unbind a key combination from your defaults.json, set the command to "unbound".
  // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
  "keybindings": [
    // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
    // These two lines additionally bind them to Ctrl+C and Ctrl+V.
    // To learn more about selection, visit https://aka.ms/terminal-selection
    { "command": { "action": "copy", "singleLine": false }, "keys": "ctrl+c" },
    { "command": "paste", "keys": "ctrl+v" },

    // Press Ctrl+Shift+F to open the search box
    { "command": "find", "keys": "ctrl+shift+f" },

    // Press Alt+Shift+D to open a new pane.
    // - "split": "auto" makes this pane open in the direction that provides the most surface area.
    // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
    // To learn more about panes, visit https://aka.ms/terminal-panes
    {
      "command": {
        "action": "splitPane",
        "split": "auto",
        "splitMode": "duplicate"
      },
      "keys": "alt+shift+d"
    }
  ]
}

**Comment by yanke1311** [comment]
the code block is automatically by markdown of github, and in my json, there is no ```

**Comment by yanke1311** [comment]
I have known it , `ctrl+shift+f` will conflict to input method of system in chinese. thank you @DHowett !!

**Comment by DHowett** [comment]
Oh! Thank you!
