### ISSUE TITLE
Define a profile with split panes

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/terminal#5892]
# Description of the new feature/enhancement

I don't think there is a way to do this now, but I'd like to be able to define a profile that included split panes.  So I guess this becomes a feature request. This is related to feature request #5891 with the idea that my default profile might include a 3-panel layout.

**Comment by DHowett-MSFT** [comment]
So, it's not named properly but we're tracking this as part of /dup #756 (linked from panes epic #1000). Ideally we'll leverage our commandline support to make this seamless.

Right now, you can accomplish this by adding your own shortcut that starts `wt.exe split-pane ; split-pane -p Ubuntu ; ...` :smile;

**Comment by DHowett-MSFT** [comment]
(I realize it isn't directly related to starting up with multiple panes, but the same work should solve both use cases.)
