### ISSUE TITLE
🐛 Solarized Dark theme renders certain commands/text unreadable.

### ISSUE THREAD

**Issue by MiniFlames** [microsoft/terminal#5896]
Certain text is unreadable when using the 'Solarized Dark' theme, for example the following command in Powershell

`pktmon start --etw -m real-time`

is rendered like this:

![image](https://user-images.githubusercontent.com/7881404/81873482-c6f5da00-9573-11ea-84e1-8ba06acad190.png)

Thus far I've only noticed the issue with Powershell commands.

---

Windows
Terminal Version(s): 0.11.1121.0 and 0.11.1333.0
Powershell Version: Powershell Core 7.0.0
Windows Version: Windows 10 - Insider Preview (Fast Ring), build 19268.

**Comment by skyline75489** [comment]
I've experienced this once with PSCore. Changing the color setting of PSCore itself (using `Set-PSReadlineOption`) effectively fix this. I'm not sure what we can do (or should do) on the terminal side.

**Comment by jdhitsolutions** [comment]
I have found that when using this theme I have to make sure not to set useAcrylic to false and remove the PSReadline module. The problem is the conflict between PSReadline options and the WT theme. I'm not sure that can be fixed. I'd say your best solution is to use `Set-PSReadlineOption` to adjust colors when using the Solarized Dark theme.

**Comment by jdhitsolutions** [comment]
This is the PowerShell script I run when I need to adjust colors.

```powershell
#Update-PSReadline.ps1
# https://en.wikipedia.org/wiki/ANSI_escape_code

if ($IsCoreCLR) {
    $esc = "`e"
}
else {
    $esc = $([char]0x1b)
}

Set-PSReadLineOption -Colors @{
    Parameter = "$esc[96m"
    Operator  = "$esc[38;5;47m"
    comment   = "$esc[92m"
    String    = "$esc[38;5;51m"
}
```

**Comment by j4james** [comment]
This is a very old bug in the Solarized color scheme (https://github.com/altercation/solarized/issues/220).

**Comment by DHowett-MSFT** [comment]
Yeah, this one is unfortunately by design. Solarized was _not_ a good color scheme for us to ship by default, but here we are on the doorstep of v1 being sad about it. ☹️

**Comment by DHowett-MSFT** [comment]
FWIW: some combination of #2661 and #293 are at play here.
