### ISSUE TITLE
"Windows Terminal" name should be localized in start menu/tile

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#5898]
Now Windows Terminal is going to the release candidate channel,and it supports for non-English UI language(Tiles).Now the application name "Windows Terminal" and the short name "Terminal" is not localized.Such as  application name " Windows Terminal" could be translated to "Windows 终端" in Chinese and the short name could be translated to "终端".

现在Windows终端进入了发布候选通道，它支持非英语UI语言的显示。现在应用程序名称“Windows终端”和短名称“终端”没有本地化（磁贴）。如应用程序名称“Windows Terminal”可以翻译成“Windows 终端”,应用短名称"Terminal"可以翻译成"终端"。

**Comment by DHowett-MSFT** [comment]
Sorry. We had to make a choice. :smile:

### If we make "Windows Terminal" localizable

![image](https://user-images.githubusercontent.com/14316954/81882258-238ed000-9547-11ea-849b-a057433f46d6.png)


We had to _force_ the application name to "Windows Terminal" sometimes so it would display properly.

**Comment by skyline75489** [comment]
Well it is actually a fair point. On some Linux DEs such as GNOME, the terminal is precisely named 
"GNOME 终端" or just "终端". But on other DEs such as KDE it's, well, "Konsole". I don't think it would cause any practical misunderstanding, though. I mean. Not to brag but you gotta at least know what "terminal" is and what it can do before working with an actual terminal emulator. So I'm totally with what we have right now.

**Comment by DHowett-MSFT** [comment]
(We actually do intend to have a localized product name (like "Windows-terminal" in German and "Terminal Windows" in Spanish), we just can't slap it on these surfaces because of that limitation.)

**Comment by zadjii-msft** [comment]
@dhowett Don't we have an open work item internally for doing this, considering the whole "ship with the OS" thing?

**Comment by DHowett** [comment]
Indeed!

**Comment by apriil15** [comment]
Is there any way that I can change my terminal display name in start menu to `English`?

It would be more convenient for me to search using English.

It is Chinese now because my localization is Chinese.

Thanks a lot!

**Comment by Hsclone** [comment]
> Is there any way that I can change my terminal display name in start menu to `English`?
> 
> It would be more convenient for me to search using English.
> 
> It is Chinese now because my localization is Chinese.
> 
> Thanks a lot!
> 
> [UPDATE]
> 
> I found a way it worked for me, and maybe it can help others.
> 
> 1. go to language setting, and add English to `first order`
> 
> ![image](https://user-images.githubusercontent.com/24965046/216387093-49b136d5-f70a-414d-b05f-2c254b918374.png)
> 
> 2. restart your PC, and then it should work

I found another way to search and launch Windows Terminal using apps like "Powertoys Run" or just Windows search, don't search "Terminal" but search"wt" or "wt.exe" instead.

**Comment by Gaoyifei1011** [comment]
The issue has been resolved and this issue is being closed
问题得到了解决，这个 Issue 即将关闭

![{3AABD08F-39A9-4C97-A4AB-5EC7B1E71531}](https://github.com/user-attachments/assets/ca673106-1c63-4b74-9c3c-44a32ebf2fb2)
![{03CDF48F-6D72-4BF1-925D-48002425978B}](https://github.com/user-attachments/assets/0162e7ff-23d4-46e7-8b5e-2ebd38530459)
