### ISSUE TITLE
error MSB8036: The Windows SDK version 10.0.17763.0

### ISSUE THREAD

**Issue by esarearthur** [microsoft/terminal#590]
I keep getting error MSB8036: The Windows SDK version 10.0.17763.0 but I have Windows 10 SDK (10.0.18362.0) installed.

How can I resolve this error?

Thank you.

**Comment by zadjii-msft** [comment]
I'm going to need more info than that - what project is giving you that error?

I think there's some more info in #554

**Comment by esarearthur** [comment]
Ok, I got around it using 
msbuild openconsole.sln /p:Platform=x64;WindowsTargetPlatformVersion=10.0.18362.0

**Comment by broken-bytes** [comment]
Getting the same issue, even after the specified build tool is clearly installed.
Happens on Terminal/CascadiaPackage.

**Comment by broken-bytes** [comment]
Also, if that helps. I am using Visual Studio 2019.

**Comment by wahid** [comment]
Is your windows 10 on version 1903?

**Comment by gemengshu** [comment]
I met the same problem and finally solved it  by updating the system to the latest version.  Version of 10.00.18894.1000 works.

**Comment by casperx** [comment]
I have same problem recently and fixed it by using Repair feature of Visual Studio Installer.

**Comment by broken-bytes** [comment]
I actually managed to fix it by uninstalling the tools and install them in a different order(142 before 141>

**Comment by miniksa** [comment]
Looks like this sorted itself out. Closing.
