### ISSUE TITLE
Does current version support drag item path drop to terminal just like cmd.exe?

### ISSUE THREAD

**Issue by halx99** [microsoft/terminal#5902]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Yes. Did you try it?

**Comment by halx99** [comment]
> Yes. Did you try it?

I try the latest release tody, it seems doesn't support

**Comment by DHowett-MSFT** [comment]
There is a bug where it works better if you do it closer to the top left corner of the window. The cursor changes to say “copy path to file”

**Comment by halx99** [comment]
thanks for your reply, I will try later

**Comment by halx99** [comment]
@DHowett-MSFT 
I have tried, but it's seem doesn't work any where.

**Comment by DHowett-MSFT** [comment]
What application are you dragging from?

Here, I have dragged C:\Programs from Explorer to my terminal.

![image](https://user-images.githubusercontent.com/14316954/81900926-9cefe800-9572-11ea-9557-39f939f66eb8.png)

**Comment by halx99** [comment]
any filea or folders doesn't work

**Comment by zadjii-msft** [comment]
@halx99 How did you install the Terminal? Does drag-dropping a file work for other UWP applications on your system (like OneNote? the Mail app perhaps?)

**Comment by halx99** [comment]
I just down the Terminal installer from github release and install it

**Comment by halx99** [comment]
Maybe because I use account administrator

**Comment by zadjii-msft** [comment]
@halx99 That might absolutely be the case. I'm pretty sure drag-drop doesn't work at all for applications running elevated.

**Comment by feerlessleadr** [comment]
I'm having the same issue, although I can't figure out how to run the terminal outside of administrator mode.
