### ISSUE TITLE
Any chance of Mac support?

### ISSUE THREAD

**Issue by zmarkan** [microsoft/terminal#5903]
# Description of the new feature/enhancement

The new Microsoft Terminal is my preferred terminal on my personal laptop which runs Windows, but I use a Mac for work and it doesn't work here. I'd love to be able to use it on a Mac as well.

The app should ship as a DMG and work on a Mac You could verify it working by running it on a computer running Mac OS.

**Comment by oising** [comment]
Hi @zmarkan -- it's great that you enjoy using Windows Terminal so much, but unfortunately it's not the kind of project that lends itself well to be ported to other platforms. The underlying architecture of Windows and Unix-based systems are quite different, and the work would more or less be a complete rewrite. There are many great terminals available on Mac already -- I myself like iTerm2.

**Comment by WSLUser** [comment]
This story will likely get better once we have cmake support and WinUI3 is available (not just Mac but Linux and other flavors of BSD too). The VT support will need to be ported from the Console as well for it to truly stand on it's own but that's the most trivial part what is missing from the Console already have a few PRs pending.  Once merged, it would be almost straightforward to copy it to Terminal's dispatch from Console's dispatch.
