### ISSUE TITLE
Can't change back to default cursor shape after enter and exit out of neovim.

### ISSUE THREAD

**Issue by ianpan870102** [microsoft/terminal#5904]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1251.0

Any other software? neovim, WSL1
```

# Short bug description

Windows Terminal fails to change back to default cursor shape after I enter and exit out of neovim.

# Steps to reproduce

0. Set the cursor shape in Windows Terminal to be "vintage" (i.e. thick underscore) in `settings.json`.
1. Open a terminal session in WSL1 (Ubuntu 18.04).
2. Invoke neovim on a random file with `nvim main.cpp`.
3. Exit neovim with `:q<enter>`

# Expected behavior
1. Invoke neovim at the command line, the cursor shape is vintage before entering the neovim session. So far so good.
2. Entered neovim, the cursor shape is now filled-box in "neovim's normal-mode", and is a vertical thin line in "neovim's insert-mode". So far so good.
3. After I exit out of neovim, Windows Terminal should give me back the vintage cursor shape at the command line, which I specified as the default in `settings.json`.

# Actual behavior

Windows Terminal fails to change back to default cursor shape after I enter and exit out of neovim. The cursor now becomes filled-box shape (as in neovim's normal mode).

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1604 for more discussion.

/dup #1604

**Comment by ianpan870102** [comment]
@zadjii-msft Hey Mike, thanks for the pointer. I'll follow that thread instead :-)
