### ISSUE TITLE
Resizing Terminal window is slow and laggy

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/terminal#5905]
# Steps to reproduce
Resizing the Terminal window is slow and laggy. It feels like I'm resizing the window of a uwp app, instead of a Terminal app. Terminals can't be slow and terminals can't have graphical lags. 

# Expected behavior
Resizing the window should be as smooth as resizing a windows console window.

**Comment by zadjii-msft** [comment]
@phgmacedo Cloud you try disabling a setting for me, to see if that helps here? Could you add `"snapToGridOnResize": false` to your `settings.json` file? That setting forces the terminal to try and snap to the nearest character size - if you disable it, the Terminal will resize more smoothly.

I'm not saying that resizing _isn't_ slow, it's one of the worst functions in the codebase. Heck, optimizing it is what #5800 is all about. But the above setting might make it _feel_ smoother, at least for now.
