### ISSUE TITLE
Terminal window titlebar is too big compared with console and other native windows apps

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/terminal#5906]
# Steps to reproduce
![image](https://user-images.githubusercontent.com/2473545/81935018-52985680-95c6-11ea-804c-fbfbbf4b9413.png)

![image](https://user-images.githubusercontent.com/2473545/81935156-8e332080-95c6-11ea-9981-d326aa630e45.png)

# Expected behavior
The Terminal titlebar size should be the same as that of other windows apps. Currently, Windows Terminal feels like a UWP app. 

# Actual behavior

Windows Terminal titlebar size is too big and feels like a UWP app.

**Comment by zadjii-msft** [comment]
I mean, the Terminal is an application that's using UWP XAML 😉 

You could also try 

```json
"showTabsInTitlebar": false,
"alwaysShowTabs": true
```

to force the Terminal to use a standard windows titlebar. 

Largely, I'm gonna close this as a /dup of #1375, as that thread has much more discussion of the design in it

**Comment by phgmacedo** [comment]
> to force the Terminal to use a standard windows titlebar.

The problem is not about whether or not it has tabs. 
The problem is that the tabs make the titlebar frame larger and it looks odd. If it had tabs, but with a smaller titlebar frame, and with a smaller default window size, it would absolutely not be a problem.

**Comment by phgmacedo** [comment]
@zadjii-msft And it's not a dupe of #1375 insofar as that issue seems like a ignore dump of complaints about terminal. None of the issues mentions the titlebar *height* and *scaling*, and this is also not acknowledged in there as well.

**Comment by mdtauk** [comment]
> > to force the Terminal to use a standard windows titlebar.
> 
> The problem is not about whether or not it has tabs.
> The problem is that the tabs make the titlebar frame larger and it looks odd. If it had tabs, but with a smaller titlebar frame, and with a smaller default window size, it would absolutely not be a problem.
>
You chose not to compare the Titlebar with Google Chrome or Microsoft Edge, despite the tabs being in the titlebar...

![image](https://user-images.githubusercontent.com/7389110/81940990-2265ad80-95f0-11ea-9449-85860a3f509f.png)

When comparing these, Windows Terminal is actually shorter

**Comment by phgmacedo** [comment]
> You chose not to compare the Titlebar with Google Chrome or Microsoft Edge, despite the tabs being in the titlebar...

1. That's not how chrome looks like on my computer, and as far as I know, for lots of people as well, search for discussions about the flag `/force-device-scale-factor=1`. On a 15 inch, fullhd notebook display, which is configured by default to run at 125% scaling, UWP apps look odd, and Chromium based browsers look giant as well without the flags. 
2. Chrome usually runs maximized. Terminal doesn't. When chrome is maximized, the tabs gets smaller. 
3. You're right, Terminal is indeed shorter than these browsers when they aren't maximized, and when they aren't launched with the flags `/force-device-scale-factor=1`. 

I've attached a screenshot comparing Chrome on my machine with windows terminal. 

![image](https://user-images.githubusercontent.com/2473545/81946244-8333bc80-95d5-11ea-81b3-927adc4b1396.png)

I've also attached a comparison with windows explorer, chrome with the flag, and terminal. 
![image](https://user-images.githubusercontent.com/2473545/81946560-e6255380-95d5-11ea-8252-b289973dcaba.png)

**Comment by phgmacedo** [comment]
And as a side note, for Microsoft Edge, making the UI smaller or giving users to option to change the scaling is in actually [in discussion](https://techcommunity.microsoft.com/t5/discussions/top-feedback-summary-for-may-12/m-p/1383568).

**Comment by mdtauk** [comment]
I did not realise you were comparing scaled UI to 100% dpi UI.

When running at 100% dpi scaling, Chrome and Edge are still larger than Windows Terminals however.  So I don't think it is right to expect a standard height TitleBar, with tabs in them.

**Comment by phgmacedo** [comment]
> I did not realise you were comparing scaled UI to 100% dpi UI.

Yes, but at 100% DPI everything else on windows is then too small. 
Currently, my choice is to break everything else, or to break UWP apps and run Chrome with the scaling flag. 

That's why I avoid UWP apps. Is there a way to change the Terminal UI scaling only, without affecting the rest of the OS, or should I not use Windows Terminal instead? 

I really don't think this issue should be closed.

**Comment by zadjii-msft** [comment]
I think what you're really looking for is #5911.

As soon as apps start customizing the titlebar, all bets are off as to what size the titlebar is. 
![image](https://user-images.githubusercontent.com/18356694/81957494-44503780-95d2-11ea-9b17-002eea82bf92.png)

Or take Spotify for an example, which doesn't even really have a titlebar:
![image](https://user-images.githubusercontent.com/18356694/81957580-63e76000-95d2-11ea-9de6-53dd612c20b7.png)

So there's already basically no consistency here. 

We've made a _stylistic_ choice to make the titlebar of the Terminal as big as it is, because it fits the tabs we have rather nicely. Though, I acknowledge that this might not be everyone's preference, so let's make a setting for it. We're already discussing a huge number of "theming" properties in #3327, so this seems like it would be a nice fit.

**Comment by phgmacedo** [comment]
@zadjii-msft Yes, #5911 is the issue. It would be interesting to have one setting to force the entire scaling as well. This is really important for me, and Windows Terminal, as all well as any other UWP app, can't be used without it.

**Comment by phgmacedo** [comment]
Teams UI kind of sucks, office has gotten much worse in recent times - it used to be more compact, and windows terminal also sucks. 
I won't really comment on Spotify. But at least teams and Spotify both provide a zoom option that affects the entire UI. 
AFAIK both terminal and office do not provide that option.

**Comment by MostHated** [comment]
I found this thread due to feeling that the title bar was way too big as well. I would love to be able to specify the size in px or something similar. I realize it has tabs, so it is bigger. It would be ideal if the tab size would just scale with the size of the title bar. It just feels like wasted space
