### ISSUE TITLE
Azure Cloud Shell should not be available by default since I haven't installed it, haven't requested it

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/terminal#5908]
# Steps to reproduce

1. Launch Windows Terminal
2. Click the arrow to see available environments. 

# Expected behavior
I have installed in my machine: 
* CMD
* Powershell
* Ubuntu

I have not installed or configured, or used, or even knew it existed:
* Azure Cloud Shell

While it could be an interesting service if I had found out about it in another place, I really hate it because it feels like Microsoft inserted an Ad into my terminal.

I don't want ads on my terminal.

# Actual behavior

Windows Terminal should not display the Azure Cloud Shell item if I don't use Azure Cloud Shell, if I haven't configured Azure Cloud Shell, if I don't use Azure. 

Windows Terminal should not have ads.

**Comment by phgmacedo** [comment]
Maybe we should frame this as a feature request for an AdBlocker for Windows Terminal?

**Comment by jdhitsolutions** [comment]
Another reason for not including it by default is that it requires some setup on the backend before you can use it. If a non-Azure user sees this and goes to run it, they are immediately met with a roadblock. This doesn't make for a nice user experience. At the very least, the default profile setting should be hidden.

**Comment by DHowett-MSFT** [comment]
Thanks for your input, all. There's a lot of great discussion on this over in /dup #3231. There's also some delightfully toxic discussion over there, so do be careful.

This isn't changing for v1, but it's something we'll continue to evaluate. AZCS was intended to be our first "in-box first-party extension" to prove out that our connection/extension model had legs. The intent was always to make it removable, or even non-default, but v1 is shipping the way that it is shipping.

**Comment by phgmacedo** [comment]
> The intent was always to make it removable, or even non-default, but v1 is shipping the way that it is shipping.

Can't speculate on intentions, only on facts and the fact is that this Terminal app is shipping with an Azure ad as default that can't be disabled, and it is disgusting.

**Comment by DHowett-MSFT** [comment]
Okay.

**Comment by DHowett-MSFT** [comment]
(The thread I linked actually offers two different ways to disable it, but if you’d like us to add a third that’s open for discussion.)

**Comment by Alacritous** [comment]
I deleted the damn thing as too useless after #3231 got locked a year ago. So I just reinstalled it and lo and behold the AZURE cloud profile is still there, still auto-generated and I STILL CAN'T REMOVE IT.  What the hell? 

![image](https://user-images.githubusercontent.com/1443724/129410868-664fac13-a065-4eb3-a164-a424aa2a88cd.png)

**Comment by DHowett** [comment]
Lucky you: #10910 is merging for the 1.11 cycle.
