### ISSUE TITLE
Emoji character width / spacing too large (Black Medium Square)

### ISSUE THREAD

**Issue by R-Broadley** [microsoft/terminal#5910]
# Environment

```
Windows Version: 10.0.18362.836
Terminal Version: 0.11.1333.0
```

# Steps to reproduce
Paste the following into the terminal (command prompt or WSL): ◼◼◼◼◼◼◼◼◼

# Expected behavior
The characters are normally spaced. Screen shot is from Version: 0.11.1251.0.
This has been the previous behaviour and is how other terminals (tested in gnome-terminal) display the same setup.
![block_spacing_correct](https://user-images.githubusercontent.com/14995701/81955789-7083ac80-9602-11ea-87c3-605d64459916.png)

# Actual behavior
The characters are too wide / too much spacing between them and this breaks the layout where mono fonts are expected and relied upon for layout.
Screenshot is from Version: 0.11.1333.0.
![block_spacing_bug](https://user-images.githubusercontent.com/14995701/81955797-737e9d00-9602-11ea-8420-af008bb4e1dd.png)

**Comment by DHowett-MSFT** [comment]
So, I've got to admit. I sorta hate this :smile:

We knew there'd be some regressions when we recategorized some of the codepoints as "wide", but like, I'm at a loss for what to do with this one.

Everything I can find about these two glyphs indicates that we're _supposed_ to give them Emoji treatment.

From the Unicode Character Database (latest version):

```
PS> $chs=($ucd.ucd.repertoire.char | ? cp -in ("25FB", "25FC"))
PS> $chs | ft cp,ea,Emoji,ExtPict

cp   ea Emoji ExtPict
--   -- ----- -------
25FB N  Y     Y
25FC N  Y     Y
```

Perhaps the answer lies in `emoji-sequences.txt`? The emoji whose emoji presentations require `U+FE0F` might be good candidates for reshrinking?
