### ISSUE TITLE
Massive FPS Drops on 144hz monitor/ Not keeping up

### ISSUE THREAD

**Issue by larson-carter** [microsoft/terminal#5912]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): Microsoft Windows [Version 10.0.19041.264]

Any other software?: No
```

# Steps to reproduce

1.) Open windows terminal on any 2004 build. With a 144hz monitor. I'm assuming these issues carry over to monitors greater than 60hz

# Expected behavior

1.) To run like butter. Not lag out the entire system and make hazing effects on the monitor

# Actual behavior

1.) Screen tearing when dragging windows
2.) Random flickers in parts of panel
3.) Massive fps drops

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to [these threads](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+144hz) for more discussion.

/dup #649 #3099
