### ISSUE TITLE
Feature request: When text is selected, pressing 'Enter' copies it

### ISSUE THREAD

**Issue by boxfoot** [microsoft/terminal#5913]
# Description of the new feature/enhancement

I would find it helpful if pressing 'enter' when text is selected would copy that text and stop the selection - basically a synonym for the default CTRL-C keybinding, but only active when there is a selection.

This behavior is common in a lot of other terminals, such as ConEmu and Cmder.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You can already do this today, by adding 

```
        { "command": "copy", "keys": ["enter"] },
```

to your keybindings

**Comment by boxfoot** [comment]
Thanks!
