### ISSUE TITLE
Non-PS command output not logging to transcript.

### ISSUE THREAD

**Issue by rholliday** [microsoft/terminal#5919]
# Environment

```none
Windows build number: 10.0.18363.0 and 10.0.18363.592
Windows Terminal version (if applicable): 0.11.1251.0 and 0.11.1333.0

Any other software?
PSReadline version: 2.1.0-beta1 and 2.0.0-beta5
```

# Steps to reproduce

Run Start-Transcript to start logging. Execute several non-PowerShell commands, i.e. nslookup, dig, ipconfig. Full or partial output will only be logged for the first or second commands.

# Expected behavior

Both commands and output should be logged. This happens in PowerShell when not running via Terminal.

# Actual behavior

Only the first command's full output is written to the transcript file. Sometimes partial output is logged for a second command depending on what it is, but subsequently only commands are logged. PS commands continue to behave properly. I've tested this in Desktop 5.1, Core 6.2.3, and Core 7 preview 5, on two different Windows 10 machines running different versions of Terminal. All log properly when run standalone, and improperly when run via Terminal.

**Comment by DHowett-MSFT** [comment]
_what on earth_, this shouldn't be possible

**Comment by DHowett-MSFT** [comment]
Filed upstream at https://github.com/PowerShell/PowerShell/issues/12689
