### ISSUE TITLE
Keyboard input doesn't work

### ISSUE THREAD

**Issue by DragonNP** [microsoft/terminal#5920]
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): 0.11.1333.0
```

# Steps to reproduce
Run the program

# Expected behavior
Entering text from the keyboard, copying and pasting

# Actual behavior
Keyboard input doesn't work, paste and copy works

**Comment by EricZimmerman** [comment]
I am seeing the same. started within last day or 2.

same terminal version and os build

cannot enter anything via keyboard. powershell launched natively works fine, but all shells inside terminal exhibit same behavior

**Comment by EricZimmerman** [comment]
my guess is this will be closed and this referenced

https://github.com/microsoft/terminal/issues/4448

an issue from Feb.

**Comment by EricZimmerman** [comment]
this workaround fixes it (at least for me)

changed my values from 1 to 0 for both and it started working

https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424

**Comment by DragonNP** [comment]
Thank you, problem solved

**Comment by DHowett-MSFT** [comment]
I do not recommend maintaining this workaround long-term. Your system _will_ break in unexpected ways.

**Comment by EricZimmerman** [comment]
thats all well and good, but until terminal works without it, what can be done? any other ideas?

terminal was working perfectly for me on this box for months until the last update for 2004

**Comment by EricZimmerman** [comment]
can you elaborate on why it will break? in what situation? 

i found this reference to those values:

rem =================================== Windows Settings ===================================
rem ---------------------------------------- Privacy ---------------------------------------
rem ............................... Speech, inking, & typing ...............................

rem ________________________________________________________________________________________
reg add "HKLM\Software\Microsoft\Input" /v "InputServiceEnabled" /t REG_DWORD /d "0" /f
reg add "HKLM\Software\Microsoft\Input" /v "InputServiceEnabledForCCI" /t REG_DWORD /d "0" /f

**Comment by DHowett-MSFT** [comment]
That seems less like a reference (since I can't follow it and figure out where it's from) and more of just a copy/paste from a batch file :smile:

Quote from the input team about this registry key:

> Might fix terminal but will break all IME input and other text integration 

I don't have more info than that. All other non-keyboard input methods (all IMEs) might be broken.

**Comment by EricZimmerman** [comment]
https://gist.github.com/jsEveryDay/548e3cfd51d02077df90428caa9bf218

batch file indeed! =)

**Comment by EricZimmerman** [comment]
Note that v1 fixed the issue for me, even after reversing the settings back to 1 for both
