### ISSUE TITLE
Ligatures unexpected/wrong

### ISSUE THREAD

**Issue by xasx** [microsoft/terminal#5923]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.11.1333.0

Font: Inconsolata NF
```

# Steps to reproduce

Run a Shell. It is sufficient that it outputs the string `fi` somewhere. Fish seems predestined therefore 😉 

# Expected behavior

"fi" is rendered as readable letter combo F-I since this string is a substring of many words.

# Actual behavior

"fi" becomes a telephone symbol. ☎️ 

# Screenshots

## WSL/fedoraremix/fish

![image](https://user-images.githubusercontent.com/1582730/82049809-4b9d4100-96b7-11ea-82c5-297411c979fe.png)

## Windows/PWSH 7

![image](https://user-images.githubusercontent.com/1582730/82049877-6ec7f080-96b7-11ea-9668-82ba50e19521.png)

**Comment by DHowett-MSFT** [comment]
Absolutely fascinating. I can't find "Inconsolata NF", I can only find LGC and Go variants. Can you share a link to the actual font you're using?

I recall seeing this before, but I can't find the issue.

**Comment by DHowett-MSFT** [comment]
Er, found the font.

**Comment by DHowett-MSFT** [comment]
I've got some bad news!

This this how that font is authored. I know that sounds crazy, but here's what an impartial font viewing program suggests:

![image](https://user-images.githubusercontent.com/14316954/82078177-9017e500-9695-11ea-86ee-60e9968687a8.png)

![image](https://user-images.githubusercontent.com/14316954/82078224-a2921e80-9695-11ea-954b-3b4d3adc77a1.png)

**Comment by DHowett-MSFT** [comment]
![image](https://user-images.githubusercontent.com/14316954/82078275-bdfd2980-9695-11ea-9954-0e59d46ca493.png)

**Comment by j4james** [comment]
For the record, I think it's the Nerd Fonts patcher that is to blame. The original font probably had one or more ligatures stored in the private use area, and those glyphs got overwritten when the patcher used the same code points for the Nerd Fonts icons. See the bug report here: https://github.com/ryanoasis/nerd-fonts/issues/254#issuecomment-517526427

**Comment by xasx** [comment]
@DHowett-MSFT thanks for investigating.

@j4james thanks for sorting. So: Happens to all NFs with fi/fl ligatures.
