### ISSUE TITLE
A setting to control the selection outline color

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5925]
![image](https://user-images.githubusercontent.com/18356694/82059807-27783a80-968c-11ea-9a2c-f9d767ad9c38.png)
Like how in sublime, my selection is _cyan_, but it's got a white outline around the selected text as well.

**Comment by DHowett** [comment]
Honestly i'm okay with this. Might be fun.

**Comment by DHowett** [comment]
Given what we've done with Atlas, we're probably not going to add extra text adornments right now. Mike, if you really want this feature, feel free to reopen!
