### ISSUE TITLE
[Questions] Hidden Profiles and Current Session Control?

### ISSUE THREAD

**Issue by mascalia** [microsoft/terminal#5926]
Sorry for being a noob (to WT, not to Powershell), but can someone help me out with a few questions?

1.  How, exactly, do you access hidden profiles in WT command-line?  They don't show up in the drop-down (naturally, which is what I want), but I'd like to be able to spawn them when starting WT with a command-line argument (-p and --profile don't work, they only cause the default profile to come up).

2.  If you start terminal with Powershell, is there any way to control the WT session from within the session?  For example, if I start with a bog-standard Powershell profile, is there any way within that session to split the pane and start a new powershell script? 

The goal with Q2 is to avoid having to write a set of chained command-line WT arguments, and instead simply start a profile and then run a .ps1 script that will configure the running profile however I want.

Thanks in advance for any help.

**Comment by DHowett-MSFT** [comment]
Hey, thanks for asking! These aren't "noob" questions by any means. These are the ones with somewhat complicated answers :smile:

1. Right now, `{profile}.hidden` is a bit of a misnomer. Hidden profiles are actually, uh, deleted. They're ex-profiles. They've joined the choir invisible. We have #4139 tracking fixing that.
2. WT doesn't support any sort of "remote control" mechanism right now, but we're tracking that in #4472. We're putting together our thoughts on a multiprocess model and how we'll handle IPC to make sure we're making the right call here.

Right now, the go-to solution for having Terminal start up the way you want is to make a shortcut to `wt.exe` with the args you want. It's not ideal, but it may suffice for now. :smile:

/dup #4139 #4472.
