### ISSUE TITLE
Can't open settings while installing Visual Studio

### ISSUE THREAD

**Issue by MehediH** [microsoft/terminal#5929]
When installing Visual Studio, it sets the IDE as the default application for opening .json files on Windows. As a result, when trying to open the settings from Windows Terminal, Visual Studio throws an error saying it can't be opened. Going into File Explorer and setting Notepad as the default app for opening .json files fixes the issue and the Terminal is able to open the settings. 

Expected behavior here would be to have a fallback where the default app for opening .json files does not work, and open it on Notepad instead. 

This is not really an issue with Windows Terminal itself, but it could affect the UX where the user may not understand why Windows Terminal is unable to open settings. 

![screenshot showing Visual Studio error](https://i.imgur.com/qWRWG8q.png)

**Comment by DHowett-MSFT** [comment]
Wow, that's unexpected. Unfortunately, from Terminal's perspective, it _has_ successfully opened the settings file.

It just so happens that the application that said it handled it handled it by popping up a dialog.

Terminal does fall back to Notepad, but when the launched process outright lies to us we can't recover from that ☹️
