### ISSUE TITLE
Acrylic turns off when Window is Inactive

### ISSUE THREAD

**Issue by ks-twillsie** [microsoft/Terminal#593]
Your Windows build number: 10.0.18890.1000

What you're doing and what's happening: Acrylic transparency is turned on in config and working when window is active. But as soon as the window becomes inactive the acrylic transparency turns off. Turns back on when window becomes active.

What's wrong / what should be happening instead: Acrylic transparency should likely remain on. Especially in multiple monitor instances, where the window may remain at the front of the stack used for monitoring. Transparency is typically used to show when something is inactive or disabled. So transparency on when active and transparency off when inactive is the opposite of what is expected.

**Comment by rymate1234** [comment]
This is an intended feature of Windows 10 Acrylic I think https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#usability-and-adaptability

**Comment by ks-twillsie** [comment]
Oh look at that, it is, my bad. So this is a none issue since it's outside of this projects control. Apparently it's a "don't" to use acrylic for large portions of the app, it's supposed to be used for menu and title bars, etc, and I see why. Seeing as it's an option to turn on and off in terminal I'm just going to close this issue. Though would be nice if Acrylic worked on inactive windows.

**Comment by NOFUNEVER** [comment]
is there another means to achieve transparency without acrylic at this point so transparency is possible on inactive windows? The traditional windows console has the means to set a static opacity so I can have a separate terminal on each monitor all maintaining simultaneous transparency when running wsl just like I do when I'm running in a native nix env. I see that it's simply not possible with acrylic but is that really the only means for transparency at the moment?  I know it's a weird hang up but having the transparency drop out when i switch terminal windows throws me off enough to keep me using the old console for the time being.

**Comment by zadjii-msft** [comment]
@NOFUNEVER I don't think we actually have the blur % in the json currently, only the transparency %. That'd be a relatively easy starter issue if someone wanted to hop on it :)

I really don't know if there's a non-acrylic way to do transparency. I'm sure there's _some_ way to do it with DWM/Composition tricks, but I can't say for sure.

**Comment by mdtauk** [comment]
Perhaps have an opacity slider and a check box to enable Acrylic.  So the two works together.  Acrylic off but the opacity down to 50%.

When opacity slider is below a certain amount, then a glow or outline appears around the text for legibility

**Comment by SCIEN-00** [comment]
the x410 app stais transparent and blurry when inactive too 🤔

**Comment by Kellen-Stuart** [comment]
I understand this is an intended behavior - is there any way to make this not happen?

**Comment by zadjii-msft** [comment]
> We can't do this, unfortunately! System policy dictates that acrylic is only allowed on the actively focused window. Once the terminal loses focus, the system takes acrylic away from us. ☹️
https://github.com/microsoft/terminal/issues/1747#issuecomment-507505693

And all these other threads: #2326 #1886 #1747 #1546 #1505 #1099 #2698

**Comment by gnomeria** [comment]
You guys probably need some bot to clear duplicated issues 😄

**Comment by NicTanghe** [comment]
this 100% needs to b changed upstream as a nr 1 priority together with al the unstopable titlebarbloat shenanigans in windows.

This specific isue just needs to change to only not work when some other ap is in fulschreen.

**Comment by NicTanghe** [comment]
where do i go complain to have people change the system policy ?

**Comment by zadjii-msft** [comment]
@NicTanghe The issue you want to follow is over here:https://github.com/microsoft/microsoft-ui-xaml/issues/491

**Comment by swpalmer** [comment]
> > We can't do this, unfortunately! System policy dictates that acrylic is only allowed on the actively focused window. Once the terminal loses focus, the system takes acrylic away from us. ☹️
> > [#1747 (comment)](https://github.com/microsoft/terminal/issues/1747#issuecomment-507505693)
> 
> And all these other threads: #2326 #1886 #1747 #1546 #1505 #1099 #2698

Yet another case where Microsoft does things in inexplicably strange ways that diminish the UX.  I want Terminal to work exactly the opposite of how it currently does.  I want the background to go opaque when Terminal has focus so I can easily read it, and go semi-transparent when I switch away so that it doesn't 100% obscure what is behind it while it's just "taking up space" and I'm not directly interacting with it.  I hate that as soon as I click to type in the window suddenly everything is harder to read.

**Comment by hv1pr0** [comment]
geee still not fixed? pfeww...
