### ISSUE TITLE
Windows Terminal Installation Failed

### ISSUE THREAD

**Issue by miketheitguy** [microsoft/terminal#5932]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0

Any other software?
```

# Steps to reproduce

1. Double Click the MSIX Package.
2. Click Install.

# Expected behavior

For the Terminal to Install.

# Actual behavior

App installation failed with error message: Deployment Add operation with target volume C: on Package Microsoft.WindowsTerminal_2020.512.2308.0_neutral_~_8wekyb3d8bbwe from:  (Microsoft.WindowsTerminal_0.11.1333.0_8wekyb3d8bbwe.msixbundle)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)

**Comment by DHowett-MSFT** [comment]
/dup #5932

these use the same underlying technology

**Comment by DHowett-MSFT** [comment]
LOL OOPS wrong bug

**Comment by DHowett-MSFT** [comment]
This shouldn't require elevated rights, but it sounds like your app package catalog is horked. Can you follow the troubleshooting steps linked from that link?

**Comment by dweddig01** [comment]
I know this is closed, but in case others run into this. I was getting this error trying to double click the msix installer. If I run 'add-appxpackager -path filename.msix' it did install Windows Terminal.

**Comment by michaeladamkatz** [comment]
> I know this is closed, but in case others run into this. I was getting this error trying to double click the msix installer. If I run 'add-appxpackager -path filename.msix' it did install Windows Terminal.
> Oh yea, add-appxpackager worked in PowerShell 5.1 - NOT PowerShell 7.

@dweddig01 Thanks for this information. It saved me.

Note that there is a typo in the line. Should be:

`add-appxpackage -path path\to\file.msixbundle`

(Delete stray "r" and add "bundle" to the end of extension, at least for me.)
