### ISSUE TITLE
Add-AppxPackage Installation Failure

### ISSUE THREAD

**Issue by miketheitguy** [microsoft/terminal#5933]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0

Any other software?
```

# Steps to reproduce

1. Open a non-elevated PowerShell session.
2. Execute Add-AppxPackage .\Microsoft.WindowsTerminal_0.11.1333.0_8wekyb3d8bbwe.msixbundle

# Expected behavior

Installation to succeed so that I can run the Terminal.

# Actual behavior

Installation appears to succeed ; and the Terminal shortcut shows up on my Start Menu. However, I receive the following error message when attempting to start it: "Windows cannot access C:\Program Files\WindowsApps\Microsoft.Windows.Termina...\WindowsTerminal.exe"

This is likely due to the fact that I do not have elevated rights on this account to perform the installation.

**Comment by DHowett-MSFT** [comment]
/dup #5932

these use the same underlying technology
