### ISSUE TITLE
Drag & Drop Tab/Pane Arrangement

### ISSUE THREAD

**Issue by OmegaRogue** [microsoft/terminal#5935]
# Description of the new feature/enhancement

Rearranging tabs and panes with Drag & Drop, so that users can use drag & drop to rearrange split tabs and arrange them into panes more easily, especially useful with large numbers of profiles, than to set a keybind to add a new pane with any profile in any arrangement to a tab

action:
![image](https://user-images.githubusercontent.com/24958536/82114098-e438cd00-975a-11ea-9e94-2058a2418a37.png)
result:
![image](https://user-images.githubusercontent.com/24958536/82114111-f9156080-975a-11ea-8382-83f85c5de4e0.png)
action:
a tab bar for each split pane (maybe autohiding depending on profile setting/pane size and reappearing on hover), the user drags the tab from the tab bar of a pane to the main tab bar / the tab bar of another pane
result:
the tab gets moved to the main tab bar / the other pane

**Comment by DHowett** [comment]
Thanks for the request! It looks like this is similar to #4587; I'm going to close it as a duplicate.

/dup #4587
