### ISSUE TITLE
The more options flyout next to the new tab button is not keyboard accessible

### ISSUE THREAD

**Issue by Neurrone** [microsoft/terminal#5937]
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): latest 0.11 preview
NVDA: latest master snapshot alpha-20220,1c4519a6
```

# Steps to reproduce

1. Use the mouse to click on a tab at the top causing keyboard focus to move to the row of controls at the top. It is not possible to do this with a keyboard alone, but that would be a separate issue.
2. Press right arrow until focus is on the new tab button.
    
    NVDA reads the following text for the new tab button: "New Tab  split button  collapsed  Press the button to open a new terminal tab with your default profile. Open the flyout to select which profile you want to open."

# Expected behavior

There should be some way of activating the flyout with a keyboard.

# Actual behavior

Pressing space or enter on the new tab button causes a new tab to be open. 

Surprisingly, pressing the down arrow key causes focus to move back to the last opened tab. Pressing applications doesn't work either.

**Comment by DHowett** [comment]
Thanks for bringing this accessibility issue up!
So, this is very poorly documented. By default, <kbd>Ctrl+Shift+Space</kbd> will open the new tab flyout.

We'll make sure we get this documented.

**Comment by carlos-zamora** [comment]
I submitted this issue on WinUI a while back: https://github.com/microsoft/microsoft-ui-xaml/issues/1238

They said Alt+Down opens the split options. But that keybinding works too and should be rebindable using the "openNewTabFlyout" command.

**Comment by Neurrone** [comment]
> They said Alt+Down opens the split options.

I assume this should happen when focus is on the new tab buttonn which has the flyout. This doesn't work for me as of the v1.0 release.
