### ISSUE TITLE
Need a commandline option like RemoveWorkingDirectoryTrailingCharacter like powershell

### ISSUE THREAD

**Issue by sushovan** [microsoft/terminal#5939]
[Windows Terminal.reg.txt](https://github.com/microsoft/terminal/files/4638644/Windows.Terminal.reg.txt)

I have added "**Open here**" context menu for windows explorer. All working fine except open from any drive.

For this, we need to have a command-line option like RemoveWorkingDirectoryTrailingCharacter (it's in PowerShell context menu).

**Comment by DHowett-MSFT** [comment]
Change your directory from `%V` to `%V\.`. This is a /dupe of #4571
