### ISSUE TITLE
Retroactively recategorized emoji that require variation selection are the wrong size

### ISSUE THREAD

**Issue by giuseppeM99** [microsoft/terminal#5941]
# Environment

```none
Windows build number: Microsoft Windows [Versione 10.0.18363.836]
Windows Terminal version (if applicable): 0.11.1333.0

Any other software?
git bash
```

# Steps to reproduce
1. Open the terminal
2. Open a bash shell
3. Execute `printf "\u2654\u2655\u2656\u2657\u2658\u2659\u265A\u265B\u265C\u265D\u265E\u265F\n"`

# Expected behavior
All the characters should be the same size

![immagine](https://user-images.githubusercontent.com/8383704/82122183-5082f300-9792-11ea-85a5-7370b7d9bbab.png)

# Actual behavior
The black pawn is larger than the other pieces

![immagine](https://user-images.githubusercontent.com/8383704/82122275-dbfc8400-9792-11ea-854f-06050bebddcd.png)

The codepoint for the black pawn is U+265F

**Comment by j4james** [comment]
I think this should be fixed by PR #5934.

**Comment by DHowett** [comment]
Yep. Sorry about breaking all your emoji.

**Comment by DHowett** [comment]
Or, all your non-emoji.
