### ISSUE TITLE
Implement scrolling and selection of output text via the keyboard

### ISSUE THREAD

**Issue by Neurrone** [microsoft/terminal#5948]
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): latest 0.11 preview
NVDA: latest master snapshot alpha-20220,1c4519a6
```

# Steps to reproduce

1. Attempt to use the keyboard to scroll upwards.
2. Attempt to select text in the output buffer.

# Expected behavior

It should be possible to do so

# Actual behavior

As far as I know this hasn't been implemented. I was trying to use the [hotkeys described here](https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/mt427362(v=ws.11)?redirectedfrom=MSDN). The legacy terminal does support this but unfortunately not in WSL.

**Comment by DHowett** [comment]
I believe this will be covered by /dup #715. Thank you!
