### ISSUE TITLE
Tabs leak GDI handles on tab title resizes

### ISSUE THREAD

**Issue by RealDolos** [microsoft/terminal#5949]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0
```

# Steps to reproduce

1. In the preferences, set `"tabWidthMode": "titleLength"` or any other configuration that allows for variably-sized tab titles (to trigger this bug)
2. Run the following  in a powershell tab (or anything similar in any type of tab) to trigger lots of tab title resizes
```powershell
for ($i=0;;++$i) { $host.UI.RawUI.WindowTitle = "oops " + @(Get-Random -Minimum 0.0 -Maximum 100000000.3) + @(Get-Random) + @(Get-Random) + " oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooops"; }
```
# Expected behavior

Windows Terminal should keep running, keep updating the tab title, without leaking GDI handles.

# Actual behavior

Windows Terminal keeps allocating new GDI handles (as seen in Task Manager/ProcessHacker) and will eventually crash and just vanish.

The leaked GDI handles will be retained even when the corresponding tab is closed

![term resource ex](https://user-images.githubusercontent.com/9981466/82151292-1c273980-985b-11ea-9c3f-82612b135f37.png)

# Please note
It is *not* enough to just update the title when tabs are in `equal` mode/are not resized.

**Comment by miniksa** [comment]
This is leaking before any of the user mode GDI code is being hit. I see a single DC getting left behind every time. But breakpointing on literally all the GDI Create and Delete functions... the handle is leaked before we even hit our user mode code.

**Comment by miniksa** [comment]
I think this will have to be found with a KD. Also, I think it's not really our fault as ONE handle is leaked when the tab is stood up by MUX. It's just not leaked again otherwise because it doesn't resize.

**Comment by WSLUser** [comment]
@miniksa  I wonder if that leak exists in 2.4 preview of WinUI. Because this sounds alot like it's coming from there.

**Comment by DHowett** [comment]
Looks like this is a bug in WIL, actually. I failed to update WIL months ago because of static analysis failures, but in so doing I missed microsoft/wil#100.

**Comment by miniksa** [comment]
Oof good catch, Dustin.
