### ISSUE TITLE
Split horizontal can not run

### ISSUE THREAD

**Issue by DoneBootbloader** [microsoft/terminal#5950]
# Environment

```none
Windows build number: [Version 10.0.19628.1]
Windows Terminal version (if applicable):Version: 0.11.1333.0
```

# Steps to reproduce
I can't run the split horizon normally, but this error is reported in vscode
![Annotation 2020-05-17 232524](https://user-images.githubusercontent.com/46632557/82152719-d5a30080-9895-11ea-829a-b71d8d29bf35.png)

# Expected behavior
Normal operation horizontal split

# Actual behavior
I haven't been able to run horizontal split normally, I don't know if my json is wrong or what

**Comment by zsbolyoczki** [comment]
Splitting doesn't work at all.
I always had problem to split pane horizontally or vertically.
Anything I tried just opened a new pane.

Now I have tried DoneBootbloader's config:
```
{ "command": "splitHorizontal", "keys": "ctrl+shift+8"}
```

but that's also opens a new pane.

Version: 0.11.1333.0

**Comment by DoneBootbloader** [comment]
> Splitting doesn't work at all.
> I always had problem to split pane horizontally or vertically.
> Anything I tried just opened a new pane.
> 
> Now I have tried DoneBootbloader's config:
> 
> ```
> { "command": "splitHorizontal", "keys": "ctrl+shift+8"}
> ```
> 
> but that's also opens a new pane.
> 
> Version: 0.11.1333.0

This is really strange. When I use the terminal, the command does not respond.

**Comment by carlos-zamora** [comment]
As of v0.11.1121.0, we've deprecated some legacy key bindings in favor of keybinding arguments. `splitHorizontal` is now replaced with `splitPane` using the `split` argument. So your keybinding should look something like this:

```json
{ "command": {"action": "splitPane", "split": "horizontal"}, "keys": "ctrl+shift+8" }
```

Here's some resources for some other changes and deprecated settings:
- [Release Notes](https://github.com/microsoft/terminal/releases/tag/v0.11.1121.0)
- [Blog Post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-11-release/)

**Comment by zsbolyoczki** [comment]
Then it must be something wrong with my config because this new keybinding example  opens another pane just like all the other keybinding setup I have tried before.
