### ISSUE TITLE
Does not clear WSL output properly

### ISSUE THREAD

**Issue by 3axap4eHko** [microsoft/terminal#5953]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.11.1.333.0
WSL version: 2
```

# Steps to reproduce

1. Open terminal with WSL 2
2. Execute `echo 1`
3. Execute `clear`
4. Scroll up

# Expected behavior

It should clear all previous output

# Actual behavior

You'll see
```bash
$ clear
$
```

**Comment by DHowett** [comment]
Certain implementations of `clear` operate by pushing your screen into scrollback.

Can you share the output of `clear | xxd`?

**Comment by dragondave** [comment]
I think I've got the same issue as @3axap4eHko with subtly different behaviour; the scrollback contains everything since the last clear statement: if we run "echo 1", "clear", "echo 1", "clear", "echo 1", "clear" the scrollback contains:

```
dragon@DESKTOP-M1D2R9R:~$ echo 1
1
dragon@DESKTOP-M1D2R9R:~$ clear
dragon@DESKTOP-M1D2R9R:~$
```

`clear | xxd` as requested gives: `00000000: 1b5b 334a 1b5b 481b 5b32 4a              .[3J.[H.[2J`
`clear -V` gives: `ncurses 6.1.20180127` (Ubuntu-18.04 console)
Windows Terminal Version: 1.0.1401.0

**Comment by 3axap4eHko** [comment]
@DHowett 
In Windows Terminal, for `Ctrl+L` it scrolls up and for `clear` it scrolls up and truncates output leaving 1 last line during WSL usage.
For powershell it just clears everything.
```bash
$ clear |xxd
00000000: 1b5b 334a 1b5b 481b 5b32 4a              .[3J.[H.[2J
```

**Comment by DHowett** [comment]
That's _typically_ how <kbd>Ctrl+L</kbd> and `clear` work, plus or minus that extra line. Thanks for the trace.

**Comment by DHowett** [comment]
Are you using any profile customizations, or is this a totally stock settings file?

**Comment by j4james** [comment]
> `.[3J.[H.[2J`

I'd expect stuff to be left behind in the buffer with that sequence. `CSI 3J` clears the scrollback buffer. `CSI H` moves the cursor to home. `CSI 2J` clears the screen, but does so by moving the current content into the scrollback (could just be 1 line if that's all you had on the screen at the time, or could be a full screen of content).

A better clearing sequence would put the `CSI 2J` first. That way you clear the screen first (which moves the current content into the scrollback buffer), and then you clear the scrollback (leaving nothing behind).

As a test you can try manually clearing the scrollback with the following command:

    printf "\e[H\e[2J\e[3J"

**Comment by j4james** [comment]
Note that this is supposed to have been fixed in a more recent version of clear. See the comment on the VTE issue here: https://bugzilla.gnome.org/show_bug.cgi?id=506438#c19

**Comment by DHowett** [comment]
a-ha! Thanks for connecting this up. I'm gonna resolve this one as External for now, unless evidence comes back 'round that it's us.

**Comment by Dari4sho** [comment]
Is there a solution to this day? I tried different things (wsltty, clear && echo -en "\e[3J", printf '\033c\e[3J') but none of these are working for me. It's driving me nuts 😁

**Comment by DHowett** [comment]
Here's an update from six years ago:

> ncurses recently changed its logic:
> 20180804
> + improve logic for clear with E3 extension, in case the terminal
> scrolls content onto its saved-lines before actually clearing
> the display, by clearing the saved-lines after clearing the
> display (report/patch by Nicholas Marriott).
> This means that no matter which clearing strategy we pick: xterm's which does not scroll out lines, or our current one that scrolls by a page, or a to-be-implemented smart one which takes the onscreen contents into account, the "clear" command consistently does wipe out the entire scrollback buffer.
> This stops the silly behavior of VTE after a Ctrl+L at the bash prompt (or the command "clear -x") that it preserved one pageful of data in the scrollback with older ncurses versions, which didn't make any sense from a user's point of view.

**Comment by DHowett** [comment]
@dari4sho If you're still running into this issue, can you file a new bug report with the updated bug template? If you can tell us what versions of things you're using -- Terminal, WSL, Ubuntu, ncurses, etc. -- that might give us a fighting chance of helping you. As it stands, there's not enough information (considering that this bug was closed four entire years ago) for us to help.
