### ISSUE TITLE
We become aware of the void as we fill it

### ISSUE THREAD

**Issue by ret394** [microsoft/terminal#5956]
# reduce download size for WindowsTerminal

https://github.com/microsoft/terminal/releases/download/v0.11.1121.0/Microsoft.WindowsTerminal_0.11.1121.0_8wekyb3d8bbwe.msixbundle

the current situation negatively effects users and consumers. list goes on. to sum it all, no significant countervailing benefits to users.

compression is not necessary, but would easily work and avoid provoking the build system. please remove excess stuff, result would be ~1/3 reduction for 3-way split for each architecture. 

since the team seems keen on improving stuff, a related, orthogonal goal would be to add checksums. thanks a lot for understanding.

if this goes well, I've got another, similar idea for build requirements and other ideas.
for a passerby thinking did I mi something?  probably not.

`hm sgd gnqmds'r mdrs`
you're welcome, as always. all the best. 👍
don't say '... passim' to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by ret394** [comment]
how to try windows terminal online? there should be a discussions tab for this repo for questions.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by DHowett** [comment]
Thank you for the request. I do not agree that there are no benefits to the user of having all three architectures in one msix file. :smile:

I'm going to close this, because there is nothing we can easily do right now.
