### ISSUE TITLE
support on windows server 2012

### ISSUE THREAD

**Issue by sameerkattel** [microsoft/terminal#5959]
Is this supported on windows server 2012 - I can't see this app on windows store in windows server 2012?
Is there any other way I can install in windows server 2012?

**Comment by DHowett** [comment]
No, Terminal isn’t going to work on an operating system that’s 8+ years old. Sorry!

Terminal requires the 1903 build of Windows 10 or an equivalent version of Server.

**Comment by nmocruz** [comment]
This a bit sad, because I have a also some server with 2012, very stable, and the IT Admin is not going to upgrade just because I want a better terminal.

**Comment by dipique** [comment]
> This a bit sad, because I have a also some server with 2012, very stable, and the IT Admin is not going to upgrade just because I want a better terminal.

I know this doesn't help you, but for anyone reading this, note that you CAN get [PowerShell 7.x](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#msi) on Windows Server 2012 which offers a far superior experience to using the default PowerShell 5. 

With a little effort, an instance of VS Code can be configured to act as a stand-in for Windows Terminal; it supports multiple terminal "types" (e.g. cmd, powershell, bash), multiple "tabs"/terminals, and with extensions, your powershell scripts can be opened and run via keyboard shortcut. I just wanted to offer a nugget of hope for those stuck in the past. :)

**Comment by NAXSISPRO61** [comment]
> This a bit sad, because I have a also some server with 2012, very stable, and the IT Admin is not going to upgrade just because I want a better terminal.

even with that , M/Term isn't the best way to do that. yeah might be better chat with Sys, WSL  etc. There's bunch of tools that can made.

And more importantly Win Svr 2012 adn R2 isn't the best S-OS in the global. more than 6 years of usage Win Srv versions i really fall for Arch and Red Hat distros rather than Win Svr.
