### ISSUE TITLE
Will it possible to provide msi installation file.

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#5962]
# Description of the new feature/enhancement
I work in a new office, and the "windows store" is block by GPO.
"choco install microsoft-windows-terminal" is a good way ,but's not official , and should no be allowed to use choco.
But I have local admin rights to install software if I have the msi installation file.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
You can also double click the files from our releases page. These are the same files that chocolatey installs.

/dup #1386
