### ISSUE TITLE
Windows Terminal seems 30x times slower than mintty/wsltty

### ISSUE THREAD

**Issue by skywind3000** [microsoft/terminal#5963]
# Environment

```none
Windows: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

WSL: Debian10
```

# Steps to reproduce

1. start wsl in Windows Terminal
2. run: `time for i in {1..5000}; do echo "line $i"; done`
3. start wsl in [wsltty](https://github.com/mintty/wsltty).
4. run: `time for i in {1..5000}; do echo "line $i"; done`
5. compare the `real time` result.

# Expected behavior

According to the roadmap:

![图片](https://user-images.githubusercontent.com/3035071/82188487-8655e200-9920-11ea-9aa7-0590a3a6c1ff.png)

> Terminal shall be fast and efficient. Input latency should be eliminated wherever possible. Terminal will be very memory-efficient, and will avoid utilizing unnecessary dependencies to minimize memory consumption and disk footprint

Performance is supposed to be in the first place in the roadmap. And Windows Terminal should, at least, not be slower many times than mintty/wsltty before 1.0 release.

# Actual behavior

- Windows Terminal:

```bash
$ time for i in {1..5000}; do echo "line $i"; done
line 1
line 2 
line 3
...
line 5000

real    0m0.935s
user    0m0.047s
sys     0m0.125s 
```

screenshot:

![图片](https://user-images.githubusercontent.com/3035071/82187601-3a566d80-991f-11ea-91df-6d43648163a9.png)

It requires almost one second to output 5000 lines.

- wsltty:

```bash
$ time for i in {1..5000}; do echo "line $i"; done
line 1
line 2 
line 3
...
line 5000

real    0m0.034s
user    0m0.016s
sys     0m0.016s
```

screenshot:

![图片](https://user-images.githubusercontent.com/3035071/82187616-417d7b80-991f-11ea-9fe5-e78bcb64f947.png)

wsltty uses mintty as the backend, which requires only 0.034s to output 5000 lines.

# Conclusion

Windows Terminal may have the lowest responsive time, but the throughput is really poor, almost 30x times slower than mintty/wsltty.

**Comment by zadjii-msft** [comment]
So, the more useful comparison might be Windows Terminal vs the vintage console host, where the Terminal is nearly 7x _faster_:
![image](https://user-images.githubusercontent.com/18356694/82233960-5c87c580-98f6-11ea-83dc-455da152297b.png)

This might be part of a discussion @miniksa and I were having....

**Comment by miniksa** [comment]
> This might be part of a discussion @miniksa and I were having....

Yes, it's probably the overhead of the console driver and/or we need to do wait chain analysis on it.

Our goal for 1.0 was to be faster than the original conhost while using the Windows Console driver. I'm not surprised that using a customized PuTTY talking directly to the TTY streams from the *nix environment is faster given it doesn't use any of the console system.

Long term, we want to get parity with this.

**Comment by kasper93** [comment]
For me WT is actually slower, 9s vs 5s on con. Anyway I think this is dup of https://github.com/microsoft/terminal/issues/4129
