### ISSUE TITLE
The terminal does not allow use some special characters

### ISSUE THREAD

**Issue by Oskaria** [microsoft/terminal#5964]
# Environment
```none
Windows build number: 1909
```
# Steps to reproduce
Start terminal, connect with ssh to remote *nix server

# Expected behavior
When executing some commands, special characters are required, for example:
find . | grep foo
cd /var/www/html && php7.2 test.php

# Actual behavior
I cannot enter characters | and & in the terminal. Perhaps some more, but these two are often used, so I noticed.

**Comment by WSLUser** [comment]
So I can use those characters just fine and use them often as you noted. Did you update to the latest release of Terminal. Also share your `settings.json` to see if something there is at fault. There's obviously a delta here if by using mostly defaults (me) it works fine. Also mention which shell you used and if the other shells also have the issue (Does PS show the error but cmd does not?)

**Comment by DHowett** [comment]
* What version of SSH are you using?
* Are you using Windows Terminal?

When filing issues, please make sure to include the version information from the issue template. It is very difficult to determine what your problem is when it has been removed.

**Comment by rhuijben** [comment]
What keyboard layout settings are you using?
I have no problem with these characters in western EU keyboards, but I've seen these characters comming in different special keystrokes in the far past in a completely different project.
