### ISSUE TITLE
 "the Help-Wanted label" hyperlink issue in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shivam284** [microsoft/terminal#5965]
The document CONTRIBUTING.md is needed to be corrected.
On clicking "the Help-Wanted label" hyperlink, a page with filters is:open label:Help-Wanted is opened which shows "No results matched your search" (as shown in the picture attached).

![terminalDocError](https://user-images.githubusercontent.com/15786619/82200313-74724000-991c-11ea-804e-5f17dbd1e6bc.png)

I am planning to create a pull request to fix this issue.

**Comment by DHowett** [comment]
Looks like you fixed this in #5967!

**Comment by shivam284** [comment]
@DHowett Thanks!!
