### ISSUE TITLE
Funky behavior when using cat, less, etc. over ssh

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#5966]
# Environment

```none
Windows build number:  Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): Version: 0.11.1333.0

Any other software?
```

# Steps to reproduce

Open a brand new Terminal instance. Ssh to a remote Linux host from Powershell 7. Locate or create a text file that enough lines to scroll through several pages worth. I had results I filtered through from a scan I performed using a script that goes to stdout unless I pass a `> somefile.txt`. Then do `cat sometextfile.txt | more`. Observer the top line is removed after being visible for less than a second and you can not scroll to it. Use ^C to exit then use `clear.` Try using `less` instead. The first line is once again gone after being visible for less than a second. Also the 3rd line  after a newline in my case repeated itself after showing about 7 lines including a newline of other entries before continuing with those entries. Now `clear` again. Here's where it gets really interesting, do a bunch of resizes (just hold onto the bottom right corner and drag it diagonally to shrink and increase the screen size of Terminal). Do a straighup `cat` (no `more` this time) and observe the top line of the text file is now viewable. However you get returned to a somewhat unresponsive prompt at the bottom line of the screen which shows part of a line entry of that text file. You can not press enter or ^C and have it do anything (looks like they are being eaten). You can however use the space bar to clear out the characters that filled the prompt and when they are gone, use backspace until you reach the beginning of the prompt. Then you can use ^C to get a new prompt at the bottom. Do the cat again with `more` used again. Now it appears to actually work the way it's intended.

One last note: In my `settings.json`, I have
```
"rowsToScroll": "100",
"historySize": 12000,
``` 
under "defaults". I also have retro terminal effects enabled but I haven't really used it (i.e. nothing in my terminal looks different)  and I've set Tango Dark as my default color scheme. Otherwise, it's a default `settings.json`.

# Expected behavior

I expect it to show every line correctly and for them all to be scrollable, dependent on your settings.json even after resizes.
# Actual behavior

This does not work as intended. However this used to be just fine. I started noticing this in 1251 but hoped that the latest Terminal might change something.  There might be several bugs here I reported and if so, I apologize. This is just what I did to get my screen to show everything I wanted it to.

**Comment by WSLUser** [comment]
The remote host was a Fedora 31 server if it makes any difference when troubleshooting. And ssh is the 8.1 release on both Win32 and 8.0 on the Fedora server.

**Comment by DHowett** [comment]
If you make a selection, does it start redrawing the right things in the right places?

**Comment by WSLUser** [comment]
bot still haven't had chance to reproduce.
