### ISSUE TITLE
wordDelimiters doesn't work

### ISSUE THREAD

**Issue by zsbolyoczki** [microsoft/terminal#5968]
# Environment

Windows version: Microsoft Windows [Version 10.0.18363.778]
Windows terminal version: 0.11.1333.0

# Steps to reproduce

This is my settings.json:
```
"defaults":
{
"colorScheme": "Dracula",
"wordDelimiters": " :;",
"cursorShape": "vintage"
}
```
My goal was to only stop the double click selection at space, comma and semiciolon.

# Actual behavior

When I double click any part of the path string below ("path", "to", "foo", etc.) only that word will be selected:

```
lorem /path/to/foo/bar/baz/whatever ipsum
```

Triple click selects the whole line as expected.

# Expected behavior

Only select the space delimited string ("/path/to/foo/bar/baz/whatever") instead of some part of it.

**Comment by DHowett-MSFT** [comment]
`wordDelimiters` must be inserted at the top level of the settings file, not inside the profile/defaults blocks. Sorry.

**Comment by zsbolyoczki** [comment]
cool, works as expected. thanks!
