### ISSUE TITLE
Add a shortcut action for executing multiple ShortcutActions

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#5970]
Dispatch a whole bunch of commands all at once.

```json
{
    "action": {
        "command": "executeActions",
        "actions": [
            { "action": "newTab", "profile": "Ubuntu" },
            { "action": "splitPane", "split":"auto", "splitMode": "duplicate" },
        ]
    },
    "keys": []
}
```

We could probably use the same machinery we use for commandline args for this.

**Comment by DHowett** [comment]
<Needs-MiniSpec>

**Comment by DHowett** [comment]
This will be part of Command Palette (#5400), I bet?

**Comment by damnskippy** [comment]
@zadjii-msft does this allow for mapping a key binding to a set of key input, as noted in https://github.com/microsoft/terminal/issues/3799?

**Comment by digitalinfinity** [comment]
@zadjii-msft this feature is ❤️ - in ConEmu, I have a jumplist task to open multiple shell tabs at once. If I understand this issue correctly, until this feature is implemented, that's not possible in terminal today (even if not from the jumplist)?

**Comment by carlos-zamora** [comment]
Just a thought, what if we did it like this:
```json
{
    "action": [
        { "action": "newTab", "profile": "Ubuntu" },
        { "action": "splitPane", "split":"auto", "splitMode": "duplicate" },
    ],
    "keys": []
}
 ```
Just override `action` to support an array.

**Comment by DHowett** [comment]
If `action` supports an array, can you do this?

```
"action": [
   { "action": [
      { "action": [
         { "action": [
            { "action": [
...
```

**Comment by carlos-zamora** [comment]
Sure, why not? That wouldn't break anything, right? It's just inefficient?

**Comment by zadjii-msft** [comment]
Oh my god this is a /dup #3992
