### ISSUE TITLE
Cursor well below prompt, prompt duplicates

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/terminal#5972]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.11.1333.0

Any other software? $PSVersionTable follows

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Steps to reproduce

Exact steps to reproduce unknown. Regular use of the terminal eventually leads to the cursor being well below the prompt and duplicate prompts, odd scrolling / positioning behavior.

# Expected behavior

Cursor always appears at the prompt and the prompt does not duplicate.

# Actual behavior

This is very similar to, if not the same as, my previously reported issue #4812. That was closed on the hope that scrolling fixes corrected the issue but it still exists. See below screenshot and video.

![image](https://user-images.githubusercontent.com/120529/82242208-797ac380-990b-11ea-9671-f50b576b061a.png)

[2020-05-15_14-00-51.mp4.zip](https://github.com/microsoft/terminal/files/4645618/2020-05-15_14-00-51.mp4.zip)

**Comment by DHowett** [comment]
Thanks for the report! This is the same root cause as /dup #2432.

**Comment by thnk2wn** [comment]
Thanks. It may not be relevant but I wasn’t using any of the split pane features before this happened.

**Comment by DHowett** [comment]
Yeah -- it's more of a general resizing issue :smile:
