### ISSUE TITLE
Allow settings to come from multiple files

### ISSUE THREAD

**Issue by pfmoore** [microsoft/terminal#5975]
# Description of the new feature/enhancement

When configuring Windows Terminal, it would be useful to be able to split settings between two files. My use case is that I have a standard settings file that I share across all of my PCs. But some details are not the same on all machines - for example, the startup directory cannot be the same because the drive letters are different.

Ideally I would put all of my common settings in one file, which is automatically synchronised via OneDrive or Dropbox, and the machine-specific overrides in a second file that isn’t synchronised.

An alternative would be to use environment variables for the variable parts of the file - but I don’t believe that is supported at the moment either, and in any case it would not be as flexible (it would only allow strings to vary, not anything more complex (e.g. a key binding).

# Proposed technical implementation details (optional)

None, sorry. I don’t know enough about how Terminal reads its settings to suggest how this could be implemented.

**Comment by DHowett** [comment]
Thanks! I'd really like to see something like this too.

For now, I'm gonna choose to track it with /dup #2933 (storing it elsewhere, roaming it, etc. may require us to add support for `include ...`, perhaps?)

This'll show up in that issue's history.
