### ISSUE TITLE
Autohide scroll bar should be configurable

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#5981]
# Description of the new feature/enhancement

The scrollbar hides automatically, while some users may like that as the default, I would like to have the option to be able to disable that behaviour.

# Proposed technical implementation details (optional)

`scrollbarState: "alwaysVisible"`

**Comment by DHowett** [comment]
Thanks! We're tracking improving the scrollbar (in addition to having an "always" option) in /dup #3454

More info at https://github.com/microsoft/terminal/issues/3454#issuecomment-550329209
