### ISSUE TITLE
Terminal crashes on Select Text -> Copy

### ISSUE THREAD

**Issue by xobs** [microsoft/terminal#5983]
# Environment

Windows build number: `Microsoft Windows NT 10.0.18362.0`
Windows Terminal version (if applicable): `Version: 0.11.1333.0`

# Steps to reproduce

1. Select some text
2. Right-click to copy

# Expected behavior

Text is copied to the clipboard

# Actual behavior

Occasionally the program closes, which I believe is a crash.

# Additional Information

I checked the Microsoft Store, and I'm running the latest version. The Microsoft Store did not report that Terminal was updated.

The following application error appears in Event Viewer:

```
Faulting application name: WindowsTerminal.exe, version: 0.11.2005.4001, time stamp: 0x5eb0c80f
Faulting module name: TerminalApp.dll, version: 0.11.2005.4001, time stamp: 0x5eb0c79c
Exception code: 0xc0000005
Fault offset: 0x000000000000a3f3
Faulting process id: 0x3dcc
Faulting application start time: 0x01d629a506f85949
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.11.1251.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.11.1251.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: 9447907e-b136-4532-874f-91a93dac2647
Faulting package full name: Microsoft.WindowsTerminal_0.11.1251.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

This is a duplicate of https://github.com/microsoft/terminal/issues/5582 which is an issue that is now closed.

As a side note, why does the "Faulting package full name" list the version as "0.11.1251.0", when "About" shows the version as "0.11.1333.0"? I checked in the Microsoft Store and it didn't say an update was available, and I haven't installed any updates myself.

**Comment by DHowett** [comment]
This one is really interesting. I actually think we might have fixed it in #5856, but for some reason you were still running 1251. I bet that's actually because you got the update but hadn't relaunched (and fortunately, the store didn't stop you!)...
Those binary versions do match up with 1251 and not 1333, so . . . ¯\_(ツ)_/¯

**Comment by DHowett** [comment]
Are you, per chance, using `copyOnSelect`?

**Comment by xobs** [comment]
No, I don't have that enabled. The only interesting setting I have changed is `useAcrylic` and the `acrylicOpacity` values.

**Comment by xobs** [comment]
How can I leave Feedback? If I select "Feedback" from the drop-down menu, it takes me to https://github.com/microsoft/Terminal/issues

The documentation at https://github.com/microsoft/terminal/blob/master/doc/user-docs/index.md doesn't include the word "Feedback" at all.

**Comment by xobs** [comment]
Feedback: https://aka.ms/AA8gr1e
Also, opened https://github.com/microsoft/terminal/issues/5985 on the Feedback bot.

**Comment by DHowett** [comment]
Thanks for picking up on the feedback bot issue. :smile:

**Comment by DHowett** [comment]
So, looking at the crash reports for Terminal here it's getting attributed to the same failing function that #5856 fixed. If you end up on 1.0, can you validate whether it's still happening for you?

Thanks!

(Resolving for now, but I will reopen if you can repro it)
