### ISSUE TITLE
msftbot doesn't describe how to give feedback, uses outdated images

### ISSUE THREAD

**Issue by xobs** [microsoft/terminal#5985]
The "Feedback" mechanism appears to be used to get backtraces of issues. As such, the @msftbot provides information on how to send Feedback entries.

However, it does not tell the user that they must use a different program in order to actually send the feedback -- Selecting `Feedback` within `Terminal` simply brings users to https://go.microsoft.com/fwlink/?linkid=2125419 which redirects to https://github.com/microsoft/Terminal/issues

The bot should tell users that they need to open the `Feedback Hub` program in order to generate a Feedback link.

Separately, the bot uses outdated images. The actual title is "Choose a category", and the "Problem" radio button is on the left not the right:

![image](https://user-images.githubusercontent.com/238325/82302092-b6b68280-99eb-11ea-893e-7e6db02e26a1.png)

**Comment by zadjii-msft** [comment]
Yep, someone needs to update these.

**Comment by zadjii-msft** [comment]
Updated this rule this afternoon. Should have images from Windows 11 builds of the Feedback Hub, which is good enough. We also don't have a "Feedback" button anymore, because that generated exactly 0 bug reports. Removed that a few months ago.
