### ISSUE TITLE
操你好

### ISSUE THREAD

**Issue by yfdxzy2010** [microsoft/terminal#5986]
根本无法下载，怎么用啊

**Comment by zadjii-msft** [comment]
For the record, I'm replying based off of an internet translation, so this might be the wrong answer.
![image](https://user-images.githubusercontent.com/18356694/82330493-8ac5dd80-99a8-11ea-9472-2a9f1b0493d1.png)


You can find all the information you might need in our [README](https://github.com/microsoft/terminal#installing-and-running-windows-terminal):
> ## Installing and running Windows Terminal
>
> > 👉 Note: Windows Terminal requires Windows 10 1903 (build 18362) or later
>
> ### Microsoft Store [Recommended]
>
> Install the [Windows Terminal from the Microsoft Store][store-install-link]. This allows you to always be on the latest version when we release new builds with automatic upgrades. 
>
> This is our preferred method.
>
> ### Other install methods
>
> #### Via GitHub
>
> For users who are unable to install Terminal from the Microsoft Store, Terminal builds can be manually downloaded from this repository's [Releases page](https://github.com/microsoft/terminal/releases).
>
> > ⚠ Note: If you install Terminal manually:
> >
> > * Be sure to install the [Desktop Bridge VC++ v14 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=53175) otherwise Terminal may not install and/or run and may crash at startup
> > * Terminal will not auto-update when new builds are released so you will need to regularly install the latest Terminal release to receive all the latest fixes and improvements!



[store-install-link]: https://aka.ms/windowsterminal
