### ISSUE TITLE
Text gets blurry.

### ISSUE THREAD

**Issue by AritraNath** [microsoft/terminal#5987]
![Screenshot (14)](https://user-images.githubusercontent.com/38553944/82330532-9a711080-9a00-11ea-8984-5b3b0d501700.png)

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Windows version - 19041.264
Terminal version - 0.11.1333.0
Any other software?
```

# Steps to reproduce

# Expected behavior

Text must be clear and legible.
# Actual behavior

Text on the terminal interface gets blurry.
Please take a look at the screenshot attached.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #5759 for more discussion.

/dup #5759

There are two new settings you can try to fix this:  `"experimental.rendering.forceFullRepaint": true` and `"experimental.rendering.software": true`.
