### ISSUE TITLE
Parts of text seems to be cut on the top or left, make text incomplete and ugly

### ISSUE THREAD

**Issue by PWAEZQS** [microsoft/terminal#5989]
![Snipaste_2020-05-19_23-05-43](https://user-images.githubusercontent.com/24841978/82343416-652ae980-9a25-11ea-9701-19e77e9d85ae.png)

**Comment by zadjii-msft** [comment]
* What font are you using?
* What display resolution and scaling are you using?

**Comment by PWAEZQS** [comment]
> * What font are you using?
> * What display resolution and scaling are you using?

- I tried Cascadia Code, Cascadia Code PL, Fira Code Retina, Consolas, Courier New, Microsoft YaHei UI Light
- Display resolution: 1920 x 1080, scaling: 124%

- Windows version: 1909(18363.836), Windows Terminal version: 0.11.1333.0

**Comment by zadjii-msft** [comment]
>     * scaling: 124%

That'll do it. This is being tracked over in /dup #4591

You could probably fix this by just using 125% scaling 😄

**Comment by PWAEZQS** [comment]
@zadjii-msft thanks
