### ISSUE TITLE
Azure CloudShell when active looks like inactive and vice versa

### ISSUE THREAD

**Issue by miqm** [microsoft/terminal#5992]
When using Azure Cloud Shell, it's default appearance seems to be the other way round. When active, panel is opaque and it's hard to read things. When inactive - background is plain black.

# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0

Any other software?
```

# Steps to reproduce

Open Azure cloud shell with default settings (schemes property empty).

# Expected behavior

Active window should not be opaque, not the inactive.

# Actual behavior

Active window:
![image](https://user-images.githubusercontent.com/7921224/82345935-23367f00-99f6-11ea-837c-abd6655abbda.png)

 Inactive window:
![image](https://user-images.githubusercontent.com/7921224/82345160-36951a80-99f5-11ea-9dcb-9b3d99e4e6e7.png)

**Comment by DHowett** [comment]
This is how the “acrylic” option works. Active windows are allowed to have seethrough acrylic, but inactive windows are not. You can turn it off with the `useAcrylic` option.

**Comment by miqm** [comment]
@DHowett - thanks. However If I may suggest to reduce the default "force" of the acrylic. it looks pretty fine on dark backgrounds, but on white ones can get pretty unreadable if the console is dark.
