### ISSUE TITLE
Error APPX3217

### ISSUE THREAD

**Issue by esarearthur** [microsoft/Terminal#600]
Can someone help with this error, I have the latest SDK installed

"C:\Terminal\openconsole.sln" (default target) (1) ->
"C:\Terminal\src\cascadia\CascadiaPackage\CascadiaPackage.wapproj" (default target) (62) ->
(_GetAppxManifestSchemaItems target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(835,5): error APPX3217: SDK folder containi
ng 'UAP.props' for 'UAP 10.0.17763.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information. [C:\Terminal\src\cascadia\CascadiaPackage\CascadiaPackage.wa
pproj]

"C:\Terminal\openconsole.sln" (default target) (1) ->
"C:\Terminal\pkg\appx\OpenConsolePackage.wapproj" (default target) (63) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(835,5): error APPX3217: SDK folder containi
ng 'UAP.props' for 'UAP 10.0.17763.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information. [C:\Terminal\pkg\appx\OpenConsolePackage.wapproj]

**Comment by DHowett-MSFT** [comment]
Hey there,
You need to install the `17763` SDK, not just the `18362` SDK. There's some more info on this in #489.
