### ISSUE TITLE
Terminal should support ANSI SGR 53 overline attribute

### ISSUE THREAD

**Issue by rbanffy** [microsoft/terminal#6000]
# Description of the new feature/enhancement

Most recent terminal applications have extensive support for ANSI terminal commands and attributes. One extremely useful one is the overline (SGR 53) attribute that can be used for status lines and other similar uses.

![Windows Terminal on Windows](https://user-images.githubusercontent.com/184714/82364538-52092100-9a07-11ea-92f2-d43396b06584.png)

![Gnome Terminal on Ubuntu](https://user-images.githubusercontent.com/184714/82364620-6a793b80-9a07-11ea-918a-068cd8fe809d.png)

**Comment by zadjii-msft** [comment]
Yep, we probably should.I'm mildly worried that the `ExtendedAttributes` enum used all the flags in a `BYTE`, but we'll figure it out.

https://github.com/microsoft/terminal/blob/c78f264b4b64b58589d4cb34697aaf4e18499266/src/inc/conattrs.hpp#L11-L24

**Comment by DHowett** [comment]
So for this one we also have the LVB gridline attributes, technically. We need to figure out how they combine with underline/overline and grid bottom/top

**Comment by j4james** [comment]
> So for this one we also have the LVB gridline attributes, technically.

Yeah, I was just going to suggest using the `COMMON_LVB_GRID_HORIZONTAL` for this as a quick fix. It's no worse than our current usage of `COMMON_LVB_UNDERSCORE` for underline. I hacked together a quick implementation to test, and it looked OK to me. I'm not exactly sure where the overline is supposed to be rendered, but Mintty at least seems to have it at the very top of the cell. Haven't checked other implementations yet.

As for running out of bits in `ExtendedAttributes` , note that the lower byte of the `_wAttrLegacy` word is actually unused as far as I can tell, so we should have an additional 8 bits to play around with.

**Comment by DHowett** [comment]
> Lower byte of ... legacy ...

Holy crap! I never noticed this. That's clever/evil/cl-evil.

**Comment by zadjii-msft** [comment]
> I was just going to suggest using the `COMMON_LVB_GRID_HORIZONTAL` for this as a quick fix

That's brilliant and I love it

**Comment by j4james** [comment]
FYI, I've got a branch with this implemented, but it's built on top of #6506, so I'll only be able to do a PR once that's merged, which may be a while.
