### ISSUE TITLE
Ctrl+c not working when pinging

### ISSUE THREAD

**Issue by arefg** [microsoft/terminal#6001]
Ctrl+c not working when using ping

When pinging an IP, I can't cancel the ping using Ctrl+c and if I use "ping -t" there is no way of getting out of the ping except closing the entire tab on Windows Terminal.  

[Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal Version: 0.11.1333.0

**Comment by DHowett** [comment]
How did you start ping? Command Prompt? Windows PowerShell? WSL?

**Comment by arefg** [comment]
Thank you for responding so quickly. I've checked it in cmd, PowerShell 7, PowerShell 5.1, and WSL. It seems that the problem is not specific to any of these shells, because the problem exists in one of my PowerShell 7 tabs but at the same time the other PowerShell 7 tab and other shells are fine. I've seen this behaviour over and over in the last month or so.

**Comment by hexnut** [comment]
I was able to reproduce this bug, but only when when connected via RDP. The ping command does not respond to a ctrl-c in Powershell via an RDP session but works fine when testing locally.

**Comment by DHowett** [comment]
So, wow, this is crazy. I was only able to reproduce this after I've launched `ssh` once in the session.

If I press ^C while it's prompting for a password, ^C remains broken for the rest of the session forever.

Does that corroborate your findings?

**Comment by Hallucine** [comment]
> So, wow, this is crazy. I was only able to reproduce this after I've launched `ssh` once in the session.
> 
> If I press ^C while it's prompting for a password, ^C remains broken for the rest of the session forever.
> 
> Does that corroborate your findings?

I can reproduce this fairly reliably using `ssh` and `ssh-agent` after pressing ^C at a password prompt. When it does stop working I found that terminating the ssh-agent process fixes it.

**Comment by oising** [comment]
My guess is the masked input code for passwords is messing with ENABLE_PROCESSED_INPUT and crippling the break handler and it's not getting restored for some reason.

**Comment by arefg** [comment]
@DHowett @Hallucine Exactly, I think this is what happens in my case either, pressing ctrl+c at a password prompt when using ssh produces this problem.

**Comment by DHowett** [comment]
Based on all this, it seems like it's probably an OpenSSH issue. Thanks everyone for letting me know.
Might be worth filing on [the upstream Microsoft OpenSSH fork](https://github.com/powershell/win32-openssh). Better if it comes from a community member than from me! :smile:

**Comment by xobs** [comment]
This was reported to the Microsoft OpenSSH fork at https://github.com/PowerShell/Win32-OpenSSH/issues/1699

**Comment by gunthre** [comment]
Sorry for reviving an old thread, but I just came across this and found a fix that might help others.  Go into Properties (for an existing Powershell instance or a Powershell shortcut), Options tab, Edit Options.  Uncheck "Enable Ctrl key shortcuts."
