### ISSUE TITLE
Clicking a tab steals focus from the terminal

### ISSUE THREAD

**Issue by wasker** [microsoft/terminal#6006]
# Environment

```none
Windows build number: 10.0.18363.836
Windows Terminal version (if applicable): 0.11.1333.0

Any other software?
```

# Steps to reproduce

1. Start terminal
1. Click left button on the tab, once

# Expected behavior

Focus is still in the terminal, I can type and use it.

Try this with the browser (Chrome, Edge, Firefox): put cursor on the text field on some web page, then click the tab once - focus doesn't go away, you can keep typing.

# Actual behavior

Focus went away (focus rectangle is NOT visible), typing doesn't work, pressing F7 in cmd results in the prompt to disable caret browsing.

This happens to me several times a day.

**Comment by zadjii-msft** [comment]
Okay I know this is being tracked somewhere else by some other issue, but this definitely seems to have gotten much more trivial to repro in the recent builds. Hmmmm
