### ISSUE TITLE
There is a long delay between a release being posted to Github and it being fully available through the Microsoft Store

### ISSUE THREAD

**Issue by still-dreaming-1** [microsoft/terminal#6007]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0

Any other software? Microsoft Store
```

# Steps to reproduce

Install Windows Terminal using the Microsoft Store. Subscribe to release notifications for this project on Github. As soon as a notification comes in, open Windows Terminal, and check the version number.
# Expected behavior

A release to GitHub and a release to the Microsoft Store should happen simultaneously, or at least within an hour of each other. The version number shown on Microsoft Store should be what I either have installed, or have available as an update from the store. I should never see a version number on Microsoft Store that is both higher than what I have and not available as an update (since the store is where I installed it).
# Actual behavior

Often the version I have installed is not the latest one from the GitHub release. If I lookup this app in the Microsoft Store, it might claim to be this new version, but there is often no way to update to it yet. Eventually the update is made available and will get installed on my computer, either manually or automatically. When I say it is sometimes manual, I mean sometimes I notice it as an available update in the store prior to it automatically getting installed, and I can then update it. But that is not always an option even if my version is less than the store version.

**Comment by DHowett** [comment]
We can't really help how long the store takes to propagate the published build to everyone. I'm sorry about that!

I publish the releases on GitHub only after I can verify here in redmond that the store _has_ pushed an update to me. That's.. the best I can do, I think.
