### ISSUE TITLE
Tilde isn't appearing when paired with A or a. Same chars with Cascadia Code are OK on Notepad

### ISSUE THREAD

**Issue by vcx** [microsoft/terminal#6012]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

Type ~ then a (without any space, just normal diacritics). You should see ã. Super common char in Portuguese.
Same happens with A. But didn't happen with ñ and Ñ, common in Spanish

Keyboard layout is set to us-intl (like all keyboards used in US) but language is pt-br. This set up is probably the second most frequent in Brazil.

# Expected behavior
ã

# Actual behavior
a

**Comment by DHowett** [comment]
Is this with PowerShell? CMD? WSL?

**Comment by DHowett** [comment]
(This is what I am seeing with Cascadia Code using the US-INTL keyboard layout)

![image](https://user-images.githubusercontent.com/189190/82390274-211ef100-99f3-11ea-8bff-f762d04b8990.png)

**Comment by aaronbell** [comment]
Is it common to type the /tilde first, then the /a? I thought it is usually the other way around.

**Comment by matiasma** [comment]
> (This is what I am seeing with Cascadia Code using the US-INTL keyboard layout)
> 
> ![image](https://user-images.githubusercontent.com/189190/82390274-211ef100-99f3-11ea-8bff-f762d04b8990.png)

I'm facing the same issue, with Powershell only. With Command Prompt, WSL2 (Ubuntu 20) and Cloud Shell it's working as expected (ã) . I'm using Windows Terminal 1.0.1401.0, with the default settings.json file, on Windows 10 v2004 (19041.264). I'm using both US-INTL and PTB2 keyboard layouts.
