### ISSUE TITLE
Can't launch wt.exe elevated (from explorer UI)

### ISSUE THREAD

**Issue by ijprest** [microsoft/terminal#6013]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.778]
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

##Scenario 1:
1. Press Win+R to launch the "Run" dialog.
2. Type "wt" and press Ctrl+Shift+Enter.

**or**

##Scenario 2:
1. Press 'Win' to open the start menu.
2. Type "wt" and press Ctrl+Shift+Enter.

# Expected behavior

In both cases, I expect an elevated instance of Windows Terminal to start.

# Actual behavior

##Scenario 1: 
- Windows Terminal Launches, but it's not elevated.

##Scenario 2:
- I get this error message-box:
```none
[Window Title]
C:\Users\ijprest\AppData\Local\Microsoft\WindowsApps\wt.exe

[Content]
C:\Users\ijprest\AppData\Local\Microsoft\WindowsApps\wt.exe

The file cannot be accessed by the system.

[OK]
```

**Comment by talltoo** [comment]
Agree.

Now Crtl-Shift click on the taskbar icon does NOT work either when you have to elevate with a local admin account.

```
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1401.0
```

See the below error screenshot I get after being prompted twice for elevate permissions:

![Error](https://user-images.githubusercontent.com/16409467/82567629-9e5d7980-9b4b-11ea-9d91-8763dd8fb26b.png)

**Comment by ErikPlachta** [comment]
I have this same issue, and I am able to get it to work if I hold ctrl + shift and click the icon.

**Comment by WSLUser** [comment]
Why don't you just right click it? Wouldn't that be easier? I just have it pinned to the taskbar and rightclick "Launch as Administrator" (this works from Start Menu too). I tested 

> ##Scenario 2

 and that worked for me as well (but is inconvenient way to launch for me.)

> ##Scenario 1 does indeed not launch an elevated Windows Terminal. 

The only difference between OP and my tests is the Windows build: [Version 10.0.19041.264]

**Comment by zadjii-msft** [comment]
Thanks for the bug report! This is actually already being tracked by another issue on our repo - please refer to #4217 for more discussion.

/dup #4217 #4766
