### ISSUE TITLE
When I use vim in WSL2 in terminal, I can not move the cursor to the end of a line by using "l" or "$" or "right" or "End" key.

### ISSUE THREAD

**Issue by Bond171** [microsoft/terminal#6017]
# Environment
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.19041.264]
Chinese Simplified
Windows Terminal version (if applicable):
Version: 1.0.1401.0
Any other software?
WSL2 Ubuntu 20.04
```

# Steps to reproduce
Open a not empty text file with vim in WSL2 in terminal, then press "End" or "$" key, or long press "l" or "right" key. You will see that, the cursor did not move to the end of the line.

https://imgur.com/2iUcGV7

# Expected behavior
When I use vim in WSL2 in terminal, I can move the cursor to the end of a line by using "l" or "$" or "right" or "End" key.

# Actual behavior
When I use vim in WSL2 in terminal, I can not move the cursor to the end of a line by using "l" or "$" or "right" or "End" key.

**Comment by skyline75489** [comment]
I think it's the cursor shape that's bothering you. If you change the cursorShape to `filledBox`, it would be like this:

![image](https://user-images.githubusercontent.com/4710575/82408669-aa3f3200-9a9e-11ea-824f-1710296b6b31.png)

**Comment by Bond171** [comment]
> I think it's the cursor shape that's bothering you. If you change the cursorShape to `filledBox`, it would be like this:
> 
> ![image](https://user-images.githubusercontent.com/4710575/82408669-aa3f3200-9a9e-11ea-824f-1710296b6b31.png)

Thank you, it works correctly now.
