### ISSUE TITLE
Clicking on already active tab header does not allow keystrokes

### ISSUE THREAD

**Issue by chrjorgensen** [microsoft/terminal#6019]
When I click on the tab header when the tab is already active, any keystrokes are not sent to the terminal window.

This is especially annoying when the terminal app is out of focus and I want to switch to the app - I click on the tab header and start typing, but no keystrokes get to the pane as I would expect. But the problem also occurs when the terminal app is in focus and I click on the tab header of the active tab.

There should be no difference whether I click in the pane or on the tab header.

# Environment

```none
Microsoft Windows [Version 10.0.19041.264]
Windows Terminal Version: 1.0.1401.0
```

# Steps to reproduce

Click on the tab header of the already active tab.

# Expected behavior

Any keystrokes should be sent to the pane.

# Actual behavior

No keystrokes are sent to the pane.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3609 for more discussion.

/dup #3609 #6006
