### ISSUE TITLE
Specifying a font with name longer than 32 characters causes the app to crash

### ISSUE THREAD

**Issue by luk1337** [microsoft/terminal#602]
The font handling code uses LF_FACESIZE define from wingdi.h which is set to 32, however some fonts like "Droid Sans Mono Dotted for Powerline" use name longer than that which makes the Terminal app crash when trying to load font.

**Comment by DHowett-MSFT** [comment]
Alas, it’s true. Thanks for the report!

________________________________

**Comment by DHowett-MSFT** [comment]
This will require us to tease apart the `FontInfoBase` parts that pertain to GDI alone and the parts that can be generic for DX.
