### ISSUE TITLE
Japanese translation issue: Should use "Y" or "y" instead of "年"

### ISSUE THREAD

**Issue by nakazax** [microsoft/terminal#6020]
I've tried Azure Cloud Shell on Windows terminal in Japanese. It works well but I've found a following translation issue.

今後のログインのために、これらの接続設定を保存しますか? [年/n]
-> "年" is incorrect - "年" means "year" in English
-> Large "Y" or small "y" is preferable.

![image](https://user-images.githubusercontent.com/42795291/82411485-ce097480-9aac-11ea-8f85-af99b08a6437.png)

# Environment
- Windows build number: Version 10.0.19041.264
- Windows Terminal version: 1.0.1401.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1. Switch Windows display language to Japanese
2. Open Windows Terminal
3. Open Azure Cloud Shell in Windows Terminal
4. Open https://microsoft.com/devicelogin and enter the code
5. Select appropriate Azure AD tenant number

And then the message contains incorrect character will be displayed.

# Actual behavior & Expected behavior
The message "今後のログインのために、これらの接続設定を保存しますか? [年/n]"
-> "年" is incorrect - "年" means "year" in English
-> Large "Y" or small "y" is preferable.

**Comment by DHowett** [comment]
THANK YOU! I had this exact same question when I first saw the translation come back.

**Comment by DHowett** [comment]
Thanks again for the report. I just pulled the latest localization data, and I've confirmed that this has been fixed. It'll be out in the next release. :smile:
