### ISSUE TITLE
Unable to display text file encoded in UTF-8

### ISSUE THREAD

**Issue by BiiigPanda** [microsoft/terminal#6023]
# Environment

```none
Windows build number:
Win32NT 10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable):
Microsoft.WindowsTerminalPreview_1.0.1402.0

Any other software?
no

should i try to set default settings? but i can't find a way to set.
```

# Steps to reproduce
Connect to a linux device via adb, and "cat /tmp/test.txt"the text is encoded in UTF-8

# Expected behavior
UTF-8 encoded text can be shown.

# Actual behavior
Garbled text.

**Comment by zadjii-msft** [comment]
Does this work with the legacy console (`cmd` or `powershell`)? 

What happens if you run `chcp 65001` before running `adb`

(PS `adb` counts as "other software" 😉)

**Comment by wdsouth** [comment]
powershell.


i have tried chcp 65001,but nothing happened.



from D's iPhone


------------------ Original ------------------

**Comment by BiiigPanda** [comment]
> Does this work with the legacy console (`cmd` or `powershell`)?

> > powershell.

> What happens if you run `chcp 65001` before running `adb`

> > i have tried _chcp 65001_,but nothing happened.

> (PS `adb` counts as "other software" 😉)

**Comment by DHowett** [comment]
Unfortunately, this is going to be an `adb` issue. I'm not sure how or when they set the console encoding, but they _must_ do so or properly preprocess the UTF-8 coming out of the remote device.
