### ISSUE TITLE
Feature Request: Workspaces

### ISSUE THREAD

**Issue by dakom** [microsoft/terminal#6026]
# Description of the new feature/enhancement

I often have several different related directories and would like to organize them as tabs in a Terminal window. For example, project "foo" might have "foo-frontend", "foo-backend", "foo-utils", "foo-shared-types", etc.

Currently, spinning this up requires a lot of manual work (open new tab, change directory, etc.)

It would be awesome if Terminal recognized some sort of "workspace" file, such that double-clicking it opened all those directories as separate tabs in a new Terminal window.

This is already an established convention in many other programs, including Microsoft products like VSCode

**Comment by zadjii-msft** [comment]
So there's already #756, which covers the whole "start with multiple tabs open" issue. What that won't get you is a way to have a file that will just run the Terminal with all those tabs automatically.

I suppose you could make a batch script that used the [wt commandline args](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments), and do something like the following:
```cmd
@echo off

wt.exe new-tab -d .\foo-frontend ; new-tab -d .\foo-backend ; new-tab .\foo-utils
```

which will just spawn the terminal with three tabs in the given paths.

**Comment by dakom** [comment]
Ah you're right, I hadn't seen that issue - specifically [this comment](https://github.com/microsoft/terminal/issues/756#issuecomment-512195265)

Nor did I realize that the command line args were a thing. Wow, cool stuff :) 

I'm happy if you want to close this issue. Thanks!

**Comment by zadjii-msft** [comment]
Happy to help 😄

**Comment by dakom** [comment]
btw - in case anyone else lands here, adding `start /b` avoids the intermediary cmd window. e.g.

```bat
@echo off

start /b wt.exe new-tab -d .\foo-frontend ; new-tab -d .\foo-backend ; new-tab .\foo-utils
```
