### ISSUE TITLE
UNC Path non existing / Startup ending up in Crash / Cannot run Windows Terminal from "Launch" (after install) or "Start Menu"

### ISSUE THREAD

**Issue by tebeco** [microsoft/terminal#6027]
# Environment
Windows build number: 10.0.18363.0
Windows Terminal version: since 0.9 or 0.10 on every single release, this one is 
`Microsoft.WindowsTerminalPreview_1.0.1402.0_8wekyb3d8bbwe.msixbundle`

## Only known workaround so far
running manually `C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe`
And then pin it (I hope it's not an issue with the space between "Program" and "Files" as the error look a like like that ^^

Or does the app assume Store install while it was `msixbundle` but as Store is disabled, I suspect that some mechanism might try to resolved installed PATH and it fails (since NO STORE)

If anyone have a list of powershell command I can type in or a Script to extract as much as info on my box (like all the store settings / GPO / stuff disable etc ...)
please send it ... I'm very very whiling to fix this as it just break the Terminal on every single "update" => the install path change

# Steps to reproduce
Restricted machine GPO / No store / no full admin right (just a local grant that i can use to install software)
either:
* Download msixbundle >Install it > click Launch
* `Win` => click on icon
* `Win` > type `Terminal` > click the icon

![image](https://user-images.githubusercontent.com/2266487/82423154-b1a51200-9a83-11ea-9fda-2bcc88856ef3.png)
```
[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

The network location cannot be reached. For information about network troubleshooting, see Windows Help.


[OK]
```

# Expected behavior

Being able to run an installed software out of the box
I would also love to have a way to have Event Viewer logs that i could send you to be able to track down what's wrong here
To be honest, all our laptop at work seems to suffer from the same issue (hard lock down on the store)

# Actual behavior

![image](https://user-images.githubusercontent.com/2266487/82423154-b1a51200-9a83-11ea-9fda-2bcc88856ef3.png)
```
[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

The network location cannot be reached. For information about network troubleshooting, see Windows Help.


[OK]
```

**Comment by DHowett** [comment]
/dup #6010 this looks like the issue we're already tracking and trying to resolve, but nobody knows what causes it and none of our machines seem to reproduce it.
