### ISSUE TITLE
Wrong interface language

### ISSUE THREAD

**Issue by harrym124** [microsoft/terminal#6029]
# Environment

```none
Windows build number:
Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
1.0.1401.0

Any other software?
```

# Steps to reproduce

Install Windows Terminal on English Windows 10, where the system language is English but in Control Panel -> Region -> Formats, the Format is set to "French (France)".
The result is that the interface is in French, meaning all prompts, the menu on the down-arrow icon on top bar and all screens launched from it, all is in French.

# Expected behavior
The interface language should be in English, like the rest of the system.
You should be checking the Windows keyboard layout language, to decide on the language to use for the interface, not the formats.

# Actual behavior
The interface language is in French rather than English.

See image for the down-arrow icon on top bar:

https://i.stack.imgur.com/FzfLj.jpg

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/issues/5497#issuecomment-622998246 ???

**Comment by DHowett** [comment]
In short: terminal is following the windows operating system’s “preferred language list”. This is an ordered list of what languages you want Modern applications to use. This is also what the store, calculator, photos, etc. use. This is the display language for apps.

**Comment by harrym124** [comment]
> In short: terminal is following the windows operating system’s “preferred language list”. This is an ordered list of what languages you want Modern applications to use. This is also what the store, calculator, photos, etc. use. This is the display language for apps.

You are totally wrong:
The rest of the system uses English, which is the display language and the keyboard language.
The Formats option is there for me to use the Euro symbol rather than the dollar.

For your information : Windows has more than one id to define the language, keyboard and region. You guys are using the wrong one. I once did the same error in a product, so I know well the subject.

Don't close this issue before studying the subtleties of languages in Windows.

**Comment by manu3567** [comment]
I meet the same issue. My Windows is configured as English except for the keyboard and the locals (date format, hours etc). All my programs default to an English interface (office, etc). However the terminal is in French. Could you fix it, or give the user the possibility to choose his preferred language for the interface.
Thanks.

**Comment by harrym124** [comment]
manu3567, see this for a workaround:
https://github.com/microsoft/terminal/issues/5497#issuecomment-628913822

**Comment by manu3567** [comment]
I suppose these are settings of the microsoft store. Access to the windows store is unfortunately locked on my company computer ;-) .

**Comment by Hrvat1976** [comment]
Hello I have the same issue, my windows 10 is in my local/mother language and the terminal is in French. Supposedly that this laptop was bought in France. How can I change with command in CMD the language of any terminal? Thank you
