### ISSUE TITLE
Behavior when started in the address bar of explorer

### ISSUE THREAD

**Issue by taroxd** [microsoft/terminal#6031]
# Description of the new feature/enhancement

Currently, when entering `wt` in the address bar of explorer, the terminal opens with current directory being my home directory.

![Screenshot](https://user-images.githubusercontent.com/6070540/82436679-cbb51380-9ac8-11ea-8880-1ae289bb1fc9.png)

That is not the case when entering `cmd` or `wsl`, where the current directory would be changed to the directory in the explorer. One workaround is typing `wt -d .` in the address bar, but that seems rather redundant.

Also, I think it would be better to open a new tab (instead of a new window) in an existing Windows Terminal window when there is such a window available. I suggest adding a configurable option to toggle this behavior.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We wanted to make `wt` behave like `cmd` or `powershell` here, but unfortunately, there were just too many odd edge cases to make this work right. There are more details over in https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 if you want more reading.

As far as opening a new tab in the existing window, I'd follow #4472
