### ISSUE TITLE
Reopen all tabs when opened, in their respective last folder, and maybe with their own history

### ISSUE THREAD

**Issue by softlion** [microsoft/terminal#6032]
# Description of the new feature/enhancement

After the app has been closed, when the app is reopened, it would be nice if it reopens all tabs, like the chrome browser does.
It could reopen the tabs in their respective last folder, and maybe with their own command history.

The command line app of a Mac already has that great feature.
Which will go in the same direction of "reopening your desktop in the state it was when you closed it" paradigm.

**Comment by rhuijben** [comment]
Would be very nice, but also extermely hard to do. The separation between the terminal and the application that is running inside makes information like the current folder and the history unavailable.

**Comment by maciejmiara** [comment]
I think that it'd be great if at least last closed tabs could be opened with respective profiles and panes layout :)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #961 for more discussion.

/dup #961

There's also more discussion in #1056, #960, and #766 with related conversations.
