### ISSUE TITLE
Pane navigation of 2x2 grid, going from bottom-right to left selects top pane instead

### ISSUE THREAD

**Issue by jaw** [microsoft/terminal#6033]
# Environment

```none
Windows build number: 10.0.18363.836
Windows Terminal version 1.0.1401.0
```

# Steps to reproduce

Split panes into 2x2.
Perform moveFocus right action.
Pedrform moveFocus down action.
Bottom-most right pane is now selected.
Perform moveFocus left action.

# Expected behavior

Now the bottom left pane should be selected.
The top left is however selected.

# Actual behavior

Selects bottom left pane.

# Possible solution
If you want to retain current functionality, maybe add another "IReallyMeanLeft" action. (Just for joke/emphasis, call it something better.)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2398 for more discussion.

/dup #2398
