### ISSUE TITLE
Can not set the tabBar color

### ISSUE THREAD

**Issue by holyYodu** [microsoft/terminal#6035]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):
Windows Terminal: 1.0.1401.0
Any other software?
```

# Steps to reproduce
I set `"requestedTheme" : "dark",`  in settings.json, but the tabBar theme still remains the light theme. And if I set the application color as dark in windows setting, then the tabBar color of windows terminal will become dark. 

# Expected behavior
I hope there is a way to set the tabBar color, thx

# Actual behavior
can not set the tabBar color in settings.json file

**Comment by zadjii-msft** [comment]
`requestedTheme` was deprecated in 0.11 - You'll want to use `theme` instead. See #5458 and #5265

/dup #5458

**Comment by holyYodu** [comment]
Thanks for your help, the problem has been solved, btw, terminal is really good!

**Comment by holyYodu** [comment]
And this change has not been updated on the terminal website [https://aka.ms/terminal-documentation]

**Comment by zadjii-msft** [comment]
I'm pretty sure it is https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#darklight-theme

![image](https://user-images.githubusercontent.com/18356694/82458885-de096000-9a7c-11ea-937f-79fd97345a15.png)

**Comment by holyYodu** [comment]
Sorry I misread the text, thanks for your time
