### ISSUE TITLE
error 0x80070002 when launching `powershell.exe'

### ISSUE THREAD

**Issue by sadalhayat** [microsoft/terminal#6039]
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version: 1.0.1401.0 Store/GitHub & 1.0.1402.0 Preview
```

# Steps to reproduce

Open Windows Terminal or open new tab Windows PowerShell

# Expected behavior

Windows PowerShell is open

# Actual behavior

Error message: [error 0x80070002 when launching `powershell.exe']

![image](https://user-images.githubusercontent.com/18193764/82456284-3d4b8c80-9ade-11ea-9608-0ca787024f1a.png)

**Comment by DHowett** [comment]
Weird, this seems like a _file not found_ error. You haven't changed your settings at all? What architecture are you on?

**Comment by EWnb99** [comment]
same error

**Comment by sadalhayat** [comment]
> Weird, this seems like a _file not found_ error. You haven't changed your settings at all? What architecture are you on?

Windows 10 Pro 64-bit.
No issue if I run powershell from Start Menu » Run or from right click Start button » PowerShell

**Comment by qiye2019** [comment]
同样的问题，无法解决

**Comment by hola-str** [comment]
Just add the path of the power shell to the environment variable

**Comment by sadalhayat** [comment]
> 
> Just add the path of the power shell to the environment variable

Thank you. It works!
```%systemroot%\System32\WindowsPowerShell\v1.0```

![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)

**Comment by EWnb99** [comment]
> Just add the path of the power shell to the environment variable

Thanks.

**Comment by qiye2019** [comment]
> Just add the path of the power shell to the environment variable

thanks，it works

**Comment by DHowett** [comment]
Looks like this is resolved, thanks’

**Comment by vincent1890** [comment]
> Just add the path of the power shell to the environment variable

Cool thanks，it works

**Comment by TheNextUchiha** [comment]
It worked like a charm! Thanks, man. ❤️

**Comment by TheNextUchiha** [comment]
> > 
> > Just add the path of the power shell to the environment variable
> 
> Thank you. It works!
> ```%systemroot%\System32\WindowsPowerShell\v1.0```
> 
> ![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)
> 

It worked like a charm! Thanks, man. ❤️

**Comment by NoCz-hub** [comment]
> 
> 
> Just add the path of the power shell to the environment variable

thanks

**Comment by criskrzysiu** [comment]
guys I found solution!
basicly go to C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe //or wherever You app is instaled

copy the content to another folder, somewhere where You definitely have access to modify, i used new folder on my desktop

last step run WindowsTerminal.exe from that folder as admin.

![image](https://user-images.githubusercontent.com/22288449/86794442-d3c31580-c06c-11ea-9b61-f76fa19e6385.png)

**Comment by Lilkedus** [comment]
> Just add the path of the power shell to the environment variable

Thank you so much it works!

**Comment by ouija** [comment]
I suddenly had this issue occur today, not quite sure what has caused it since I haven't modified any path or env variables at all.   Also discovered that I needed to also add `%systemroot%\System32` to the PATH variable as well, since apps like `ping` were no longer working from PowerShell or Command Prompt....  _(good 'ol Windows 10)_

**Comment by StephenHodgson** [comment]
Also ran into this today. Wondering if it was part of the windows update that just rolled out. I have not changed my env vars in quite some time.

**Comment by StephenHodgson** [comment]
Looked into this a bit more the 20H2 windows build completely wiped out my PATHs in my computers env variables.

**Comment by evertoncristiano** [comment]
Thanks

**Comment by BossySmaxx** [comment]
> > Just add the path of the power shell to the environment variable
> 
> Thank you. It works!
> `%systemroot%\System32\WindowsPowerShell\v1.0`
> 
> ![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)

yeah man this wokrs, really worked

**Comment by BossySmaxx** [comment]
just use this method

**Comment by chenzhekl** [comment]
I encountered the same problem while launching Windows Terminal via the "Open in Windows Terminal" context menu. Everything works fine if I directly open Windows Terminal by clicking its icon. 

P.S. I have `powershell` in the `PATH` env variable.

**Comment by braindotai** [comment]
> Just add the path of the power shell to the environment variable

Thanks a lot, works like champ :)

**Comment by jraval** [comment]
Why does this work?  What's going on that this problem occurred in the first place?

**Comment by DHowett** [comment]
@jraval the core issue is that the installation path for PowerShell has been removed from the system `PATH`, probably by some poorly-behaved software.

**Comment by Naresh-CD** [comment]
Hi Guys,

I have tried the solution multiple times but still getting the issue once I close the terminal. Can you please help me out?

![image](https://user-images.githubusercontent.com/81788376/132814042-dec8e45c-71ca-45d3-b485-4c9ff7690d45.png)

![image](https://user-images.githubusercontent.com/81788376/132814160-5a5a4dc0-df86-4b3b-9d76-4decd950327f.png)

**Comment by dylanpoll** [comment]
> 
> 
> Hi Guys,
> 
> I have tried the solution multiple times but still getting the issue once I close the terminal. Can you please help me out?
> 
> ![image](https://user-images.githubusercontent.com/81788376/132814042-dec8e45c-71ca-45d3-b485-4c9ff7690d45.png)
> 
> ![image](https://user-images.githubusercontent.com/81788376/132814160-5a5a4dc0-df86-4b3b-9d76-4decd950327f.png)

I am also going through this one. at first I thought it had to do with validation signatures as within vsc I was having issues as well, so after doing the above I went back and incrementally between reboots disabled signing validations from within windows features but no go there as well. it is odd, I have powershell now working with vsc after running 

bcdedit /set nointegritychecks on

and

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

but windows terminal is still the same exact error as listed for you.

**Comment by hanhathuy2612** [comment]
> > Just add the path of the power shell to the environment variable
> 
> Thank you. It works! `%systemroot%\System32\WindowsPowerShell\v1.0`
> 
> ![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)

It not work for me

**Comment by fahrulseptiana** [comment]
> I encountered the same problem while launching Windows Terminal via the "Open in Windows Terminal" context menu. Everything works fine if I directly open Windows Terminal by clicking its icon.
> 
> P.S. I have `powershell` in the `PATH` env variable.

Same error here

**Comment by owaisishtiaqsiddiqui** [comment]
> > Just add the path of the power shell to the environment variable
> 
> Thank you. It works! `%systemroot%\System32\WindowsPowerShell\v1.0`
> 
> ![image](https://user-images.githubusercontent.com/18193764/82724371-d0afd800-9cff-11ea-874f-da75172fc889.png)

I did this but it does not work for mw

**Comment by gsudhan** [comment]
Somehow my powershell.exe got deleted in that path, copy pasted it from a similar machine, it works now.

**Comment by owaisishtiaqsiddiqui** [comment]
> Somehow my powershell.exe got deleted in that path, copy pasted it from a similar machine, it works now.

What do you mean?
