### ISSUE TITLE
High levels of extreme frustration 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

### ISSUE THREAD

**Issue by itmitica** [microsoft/terminal#6040]
So, the app is burried in WinApps folder. Way way way out of hand to make it ... what? Put it simply in a clear path people!!!

wt or wt.exe does not work, and yes, the alias in enabled. Why is this so hard to accomplish? What is the end purpose is beyond my simpleton imagination, but, apparently you have too much of it when it comes to overly complicate things.

colortool does not set the color theme and the color theme is different in terminal than in the cmd or powershell. Why bother in the first place.

I tried eating this cake but it just won't get down easily. And it's not me! I had very high expectations. I was mistaken. You are incapable of simple order and clarity.

Back to using a desktop for multiple cmds, alt-tab-ing and sanity.

**Comment by DHowett** [comment]
If you cannot engage in discourse following the code of conduct in this repository, I’m afraid I’ll just have to close this issue.
