### ISSUE TITLE
Setting the default colour scheme per each profile ( PowerShell , Windows PowerShell etc)

### ISSUE THREAD

**Issue by westerdaled** [microsoft/terminal#6042]
The official [docs ](https://docs.microsoft.com/en-gb/windows/terminal/customize-settings/color-schemes)are great for defining the "what".  But as to how to set a different scheme for each profile, I 'm totally lost?  

Well I tried these to no avail 😓
`settings.json
`
```
{
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "colorScheme": "Campbell"
            },
```

 or  `default.json `
```
"profiles":
    [
        {
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "colorScheme": "Campbell",
            "antialiasingMode": "grayscale",
            "closeOnExit": "graceful",
            "cursorShape": "bar",
            "fontFace": "Cascadia Mono",
            "fontSize": 12,
            "hidden": false,
            "historySize": 9001,
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%",
            "useAcrylic": false
        },
        {
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "Command Prompt",
            "commandline": "cmd.exe",
            "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "colorScheme": "Campbell",
            "antialiasingMode": "grayscale",
            "closeOnExit": "graceful",
            "cursorShape": "bar",
            "fontFace": "Cascadia Mono",
            "fontSize": 12,
            "hidden": false,
            "historySize": 9001,
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%",
            "useAcrylic": false
        }
    ],

```

**Comment by DHowett** [comment]
So, this is called out [here on the profile color page](https://docs.microsoft.com/en-gb/windows/terminal/customize-settings/profile-settings#color-settings).

In short, you can set a different color scheme for every profile like this:

```jsonc
{
    "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "cursorShape": "emptyBox",
    "colorScheme": "Dracula" // <<< HERE
    ...
},
{
    "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    "name": "Command Prompt",
    "colorScheme": "Solarized Dark" // <<< HERE
    ...
},
{
    "guid": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
    "name": "Debian",
    "source": "Windows.Terminal.Wsl",
    "colorScheme": "Bright Red" /// <<< HERE
    ...
},
...
```

Check out the HERE comments.

**Comment by westerdaled** [comment]
@DHowett  thanks, I realised I was trying incorrectly  trying  change `default.json`  which I gatther is machine generated and should not be changed.

So far my `settings.json` look like this and I am happy with the profile colours
`        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "colorScheme": "Campbell Powershell",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "colorScheme": "Tango Dark",
                "hidden": false
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "colorScheme": "Solarized Dark"
            },     
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure",
                "colorScheme": "One Half Dark"
            },
            {
                "guid": "{a3a2e83a-884a-5379-baa8-16f193a13b21}",
                "hidden": false,
                "name": "PowerShell 7 Preview",
                "source": "Windows.Terminal.PowershellCore"
            }
            
        ]  
    },
`

**Comment by Blocktrician** [comment]
Hey, I have set my color scheme to a theme called Atom. 
`{
        "name": "Atom",
        "black": "#000000",
        "red": "#fd5ff1",
        "green": "#87c38a",
        "yellow": "#ffd7b1",
        "blue": "#85befd",
        "purple": "#b9b6fc",
        "cyan": "#85befd",
        "white": "#e0e0e0",
        "brightBlack": "#000000",
        "brightRed": "#fd5ff1",
        "brightGreen": "#94fa36",
        "brightYellow": "#f5ffa8",
        "brightBlue": "#96cbfe",
        "brightPurple": "#b9b6fc",
        "brightCyan": "#85befd",
        "brightWhite": "#e0e0e0",
        "background": "#161719",
        "foreground": "#c72a2a"//"#c5c8c6"
      }`
I Have verified it works, but only in the profile defaults. I can't set them in the profiles section per profile.

**Comment by DHowett** [comment]
@blocktrician can you share a [gist](https://gist.github.com) of your settings? Thanks!
