### ISSUE TITLE
Add the ability to format the string that displays as the prompt, like in bash shell

### ISSUE THREAD

**Issue by elafnit** [microsoft/terminal#6043]
# Description of the new feature/enhancement
Showing the complete directory path as the prompt string often pushes the cursor far to the right, especially when traversing deep directory paths as often the case with github cloned repos.
It would be nice to have the ability to customize the prompt string as is the case with Bash shell or Cmder terminal.
Allowing this capability would also allow the capability to customize the prompt based on the location. Again as with Cmder, one can added the state of the git directory space with color queuing when in a git repo.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
This is something that's totally at the liberty of your shell. Like you've mentioned, `bash` lets you customize the prompt with `$PS1`. `cmd` configures the prompt with the `PROMPT` environment variable. `powershell` also lets you configure the prompt (though I'm less familiar with the how there).

I personally use something like
```
$e[30;107m[$T]$e[97;46m$P$e[36;49m$e[0m$_$e[0m$e[35;49m[18]$e[m$e[0m$e[94mmigrie$e[0m@$e[32mMIGRIE-SLAPTOP$e[0m$G
```

to get 
![image](https://user-images.githubusercontent.com/18356694/82464074-41968c00-9a83-11ea-90e6-5721fa585420.png)

in `cmd`

**Comment by elafnitzegger** [comment]
Thanks. I didn't consider making the changes at that level for powershell
