### ISSUE TITLE
Can't properly whitelist the Terminal package with Applocker / missing signature

### ISSUE THREAD

**Issue by CTDhelpdesk** [microsoft/terminal#6046]
# Environment
Microsoft Windows NT 10.0.19041.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
1.0.1401.0

Any other software?
Applocker (not separate software, but important)
```

# Steps to reproduce

We use Applocker to restrict both executable and packaged apps in our environments.  I was able to properly whitelist the Terminal app package and it installs as expected, but when actually trying to launch it, Applocker blocks it. In event viewer, rather than showing the package name, it shows a blank.  The error verbatim is " was prevented from running. "

Full event viewer output:

Provider        [  Name]  Microsoft-Windows-AppLocker       [  Guid]  {cbda4dbf-8d5d-4f69-9578-be14aa540d22} | Provider |   |   |   | [  Name] | Microsoft-Windows-AppLocker |   |   |   | [  Guid] | {cbda4dbf-8d5d-4f69-9578-be14aa540d22}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Provider
  |   |   | [  Name] | Microsoft-Windows-AppLocker
  |   |   | [  Guid] | {cbda4dbf-8d5d-4f69-9578-be14aa540d22}

# Expected behavior

Expected Applocker behavior is to properly allow the app to run, since the package Microsoft.WindowsTerminal is whitelisted.  

# Actual behavior
Screenshot of the (blank) package name being blocked by Applocker:
![image](https://user-images.githubusercontent.com/65674594/82474919-997fc380-9a80-11ea-881d-68ce63a857df.png)

**Comment by DHowett** [comment]
So, this isn't great. Would you be able to try the alternate installation method?

* Download the `msixbundle`, rename it to `zip`
* Unzip it
* Find the _x64_ `msix` inside it, rename it to `zip`
* Unzip it
* Run WindowsTerminal.exe?

You might be able to whitelist it if it is a separate executable. I'm not sure which of your organization's AppLocker policies is applying to our package, but do bear a Microsoft code signature so there shouldn't be any trouble. Sorry about that.

**Comment by CTDhelpdesk** [comment]
Hi Dustin, thanks for looking in to this.  I'm able to reproduce it regardless of the installation method, and as far as the rule that prevents installation, I don't think it's the EXE rule (I can manually run the exe without it being blocked).  I'm testing this on the preview branch, and I've successfully applocker whitelisted the Terminal Preview package after downloading it from the MS Store (on an applocker exempted machine).    

![image](https://user-images.githubusercontent.com/65674594/85890004-5f9d8d80-b7a1-11ea-819d-2adfe86f4b55.png)

However, in practice, the installation from the MS Store still fails:

![image](https://user-images.githubusercontent.com/65674594/85890121-9b385780-b7a1-11ea-9818-20327d581e7a.png)

with this error showing in Applocker event viewer:

![image](https://user-images.githubusercontent.com/65674594/85890204-bdca7080-b7a1-11ea-8dca-ed1bcffde0e4.png)

I'd like to try whitelisting it via the MSIX installer (Group Policy Management allows you to whitelist either by pointing to an installed app or to an installer, but won't let you target MSIXBundles, just MSIX or APPX).

Trying to install via Chocolatey gives a similar error:

microsoft-windows-terminal v1.1.1671.0 [Approved]
microsoft-windows-terminal package files install completed. Performing other installation steps.
Progress: 0% - Processing                                                                                              ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073D19, An error occurred because a user was logged off.

error 0x800704EC: Deployment of package Microsoft.WindowsTerminalPreview_1.1.1671.0_x64__8wekyb3d8bbwe was blocked by AppLocker.

NOTE: For additional information, look for [ActivityId] 14f4e94f-4a3d-0003-e52a-fb143d4ad601 in the Event Log or use the command line Get-AppPackageLog -ActivityID 14f4e94f-4a3d-0003-e52a-fb143d4ad601

The install of microsoft-windows-terminal was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-windows-terminal\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 8/9 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

I hope that clarifies things.  My coworkers and I have already become totally enamored with Terminal on our applocker-exempt machines and would love to be able to run it on our company workstations!

**Comment by zadjii-msft** [comment]
> (Group Policy Management allows you to whitelist either by pointing to an installed app or to an installer, but won't let you target MSIXBundles, just MSIX or APPX).

Well that sounds like the real issue here. @DHowett any ideas on who we'd follow up with on that one?

**Comment by DHowett** [comment]
So wait -- just to make sure I totally understand.
If you extract the msixbundle (it's just a signed zip file!) and install the _msix_ from inside it, can it be deployed then? Before I file a bug on the AppLocker folks, i'd like to determine whether the bug I am filing is "applocker cannot be used with **bundles**" 😀
