### ISSUE TITLE
Picking random background image from directory

### ISSUE THREAD

**Issue by eronnen** [microsoft/terminal#6047]
# Description of the new feature/enhancement

In addition to having one fixed background image per profile, I think it would be more exciting if I had the option to set `"backgroundImage"` to a directory of images/GIFs, and when starting the terminal it would randomly pick an image/GIF to view.

Thanks!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3900 for more discussion.

/dup #3900
