### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by ptMuta** [microsoft/terminal#605]
One of the superior features of iTerm2 (sadly only available on macOS) is it's content search.  The search comes in two variants: search from active tab and search from all tabs. For those unfamiliar with iTerm2 and wondering, this feature would roughly equate to almost any editor like Visual Studio Code string search.

I haven't gone in-depth with the output buffering in Terminal yet to validate if this feature is realistically doable at the current state of the Terminal app, but this is a usability feature for multitasking terminal users that would be worth a LOT.

**Comment by DHowett-MSFT** [comment]
I'll repurpose this as our main Search epic issue. I'm glad the community seems to have figured out our backlog and I don't need to go add it myself. :smile:

**Comment by gpotter2** [comment]
That would be pretty great 👀 
With regex support ? 😸

**Comment by Jewsh-S** [comment]
Another thing to keep in consideration about how iTerm2 works, is you can "Ctrl+f" to search, then press Tab when you find what you want, and it will copy what you searched for.  Basically you can easily find something in the output and copy/paste it to the input without ever leaving your keyboard.

**Comment by solacens** [comment]
It will be great if the search history can be traversed with `Arrow up` and `Arrow down` key.

BTW just a suggestion. 😸

**Comment by zadjii-msft** [comment]
(for the record, I believe #3279 was the first step on the path to this feature landing, but it's not quite finished yet. Thanks though msftbot)

**Comment by kell18** [comment]
Amazing! Can we expect a new search feature in the next release?

**Comment by zadjii-msft** [comment]
@kell18 While this feature is in active development currently, I _personally_ don't think it's going to make it quite in time for the next release cut unfortunately. Ideally, it _should_ land in the December release (which is why this is marked for the "1912" milestone), but I'm making no commitments 😝
