### ISSUE TITLE
Drop-down menu style a la Yakuake

### ISSUE THREAD

**Issue by VirusRenamon** [microsoft/terminal#6051]
# Description of the new feature/enhancement

<p>Some users who cannot have multiple monitors due to money or hardware restrictions would benefit from a drop-down as it can show and hide itself from 1 key press for easy and quick command input & output needs.</p>

<p>Terminal already has a tabbed interface and is skinnable, so all that would really need to be added is the drop-down function. Almost all Linux Desktop Environments have some form of implementation of this, so there is a want for this. Would be useful and neat if Terminal could bring this to Windows users too.</p>

# Proposed technical implementation details (optional)

[Official Yakuake Package Description](https://kde.org/applications/en/system/org.kde.yakuake)

<p>Add a settings.json setting to allow drop-down feature via a configurable key bind.
I recommend either F12 (Yakuake default) or Grave (`) key as default.</p>

**Comment by DHowett** [comment]
Hi! Thanks for filing a feature request.

I searched our repo for the term "yakuake" and found that we already have #653. Does that sound like what you're looking for?

**Comment by VirusRenamon** [comment]
> Hi! Thanks for filing a feature request.
> 
> I searched our repo for the term "yakuake" and found that we already have #653. Does that sound like what you're looking for?

Yes that's exactly what I am looking for, guess I should of searched first. Still kind of new to how github works.

**Comment by DHowett** [comment]
That’s alright! I’ll close this one as a duplicate. 

/dup #653.

Thanks again!

**Comment by UsrCletus** [comment]
Hey guys i'm actually working on a project for this: https://github.com/usrcletus/winuake

**Comment by VirusRenamon** [comment]
@UsrCletus I saw that on the other post, Ill be closely watching development!
