### ISSUE TITLE
Please let me change the font.

### ISSUE THREAD

**Issue by skipmeister123** [microsoft/terminal#6052]
# Description of the new feature/enhancement

My shell profiles lean heavily upon powerline and nerd fonts.  The new font is.... ok, I guess, but it doesn't support my symbols.  I'd like to be able to change the font-family to use my own font.
![image](https://user-images.githubusercontent.com/1911919/82483715-d5c61a80-9aa6-11ea-999d-6c45971a2b78.png)

# Proposed technical implementation details (optional)

Add a field to settings.json to allow one to specify the font-family.

**Comment by skipmeister123** [comment]
To compare, here's what my terminal _should_ look like:

![image](https://user-images.githubusercontent.com/1911919/82483848-13c33e80-9aa7-11ea-9d35-2e7ee7f948ab.png)

**Comment by DHowett** [comment]
............................?

https://docs.microsoft.com/en-us/windows/terminal/

![image](https://user-images.githubusercontent.com/189190/82484338-a3a8be80-9a8e-11ea-9bb2-6e7f31b1cbf3.png)


![image](https://user-images.githubusercontent.com/189190/82484358-ae635380-9a8e-11ea-8d78-985dfce71ad4.png)

![image](https://user-images.githubusercontent.com/189190/82484374-b3280780-9a8e-11ea-97ab-54f5fe2f7885.png)

**Comment by skipmeister123** [comment]
😶

I totally missed that in the docs.  My apologies.  Please accept this ruler to beat me to death with. 📏

**Comment by mdtauk** [comment]
I believe there is a PowerLine version of Cascadia Code also, not sure about the full Nerd Fonts however
