### ISSUE TITLE
PowerShell cannot execute Connect-AzAccount command

### ISSUE THREAD

**Issue by aaulmer** [microsoft/terminal#6053]
# Environment

```none
Windows build number: 18363.836
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
no
```

# Steps to reproduce

1. Launch Windows Terminal with a PowerShell tab
2. Type the command ``` Connect-AzAcccount ```

# Expected behavior

I should see the Microsoft sign in prompt with Microsoft Azure heading.

![image](https://user-images.githubusercontent.com/54380458/82485562-7c52f100-9a90-11ea-859b-0ac6b1fd8a59.png)

# Actual behavior

Literally nothing happens.

**Comment by DHowett** [comment]
I believe this is because the window pops up BEHIND terminal. Can you confirm if that's the case?

If so, I can redirect you to a different issue (which we're already tracking)

**Comment by aaulmer** [comment]
Yep, that is exactly what is happening. I didn't notice it because there was no taskbar icon or anything, but that definitely helped. Thank you. I like using Terminal WAY more than I do the raw components.

**Comment by zadjii-msft** [comment]
Thanks for following up! I'll redirect discussion to #2988, which has more details in it.

/dup #2988
