### ISSUE TITLE
Flags are invisible when using default Solarized Dark theme

### ISSUE THREAD

**Issue by JoeUX** [microsoft/terminal#6061]
## Environment

```none
Windows build number: 10.0.18363 (Pro, 64-bit)
Windows Terminal version: 1.0.1401.0
```

## Steps to reproduce

1. Switch theme to Solarized Dark in settings.json
2. Type something like `npm -g outdated` in WT. The `-g` will be invisible. Strangely, it's still invisible if I highlight it.
3. Same with `pip list -o` or any other flags I've tried. Anything attached to a hyphen is invisible (as is the hyphen), **except for numerals**. They show up (as does the hyphen in that case).

## Expected behavior

All text should be visible, including flags.

Settings below:
![WT](https://user-images.githubusercontent.com/8071692/82502080-3a837400-9aab-11ea-9ccc-a1fb7bc89967.JPG)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make [sure for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22solarized+dark%22+invisible+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #4047 for more discussion.

/dup #4047 #2622  #4818
