### ISSUE TITLE
Optionally start commandline executables using wt.exe if available on the system

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#6063]
# Description of the new feature/enhancement

I'd like to launch a command line program from a shortcut using `wt.exe` if it's available on the system instead of it launching automatically using conhost

![image](https://user-images.githubusercontent.com/4319522/82512806-26596a00-9adf-11ea-903a-9096798003f4.png)
However this solution doesn't work on all systems, since not everyone has installed the Windows Terminal.

Is there a way to gracefully fallback if `wt.exe` is not detected.

**Comment by DHowett** [comment]
Thanks for the request! Right now, there's not a really good way to handle this. It requires some OS side work, which we're tracking in #492. That workitem represents the work necessary to bring a customizable "default terminal" system to Windows.

/dup #492.
