### ISSUE TITLE
Icon property in settings.json should use a coma to extract an indexed icon resource from an executable the same way Explorer can

### ISSUE THREAD

**Issue by rbeesley** [microsoft/terminal#6064]
# Description of the new feature/enhancement
The `icon` property in `settings.json` should use a coma to extract an indexed icon resource from an executable the same way Explorer can. If a user is trying to point at another shell, the resource they want to use for showing the shell in Windows Terminal might be an embedded resource and that should be presumed to be the icon used when configuring a profile.

# Proposed technical implementation details
For example, take Yori by @malxau. It is not difficult to add a Yori prompt to Windows Terminal, setting the `commandline` and `statingDirectory` properties, but ideally someone should be able to use `"icon": "C:\\Program Files\\Yori\\yori.exe,1"` to use the icon resource embedded in the shell executable. If the index isn't provided, just referencing the executable without an `icon` property, Windows Terminal should extract the first icon resource as the default icon to associate with the shell. Finally, if the `icon` property is not defined, Windows Terminal should look at the `commandline` executable and use the first icon resource as the default icon, so that the user doesn't need to go the extra step of extracting an .ico resource.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1504 for more discussion.

/dup #1504
