### ISSUE TITLE
xdg-open on bash powershell not working

### ISSUE THREAD

**Issue by yusufabukar** [microsoft/terminal#6069]
# Environment

```none
Windows build number: Version 10.0.18363.836
Windows Terminal version (if applicable): 1.0

Any other software?
Ubuntu
```

# Steps to reproduce

After installing Ubuntu on Windows 10, running the standard upgrades and installing xdg-utils, I can't seem to use xdg-open through Windows Terminal.

# Expected behavior

I created a test folder on my desktop with a blank html file /Desktop/test/index.html. I wanted to use xdg-open to open it.

# Actual behavior

Using xdg-open in the test directory returns this PowerShell error:
![xdg-open bug](https://user-images.githubusercontent.com/65050809/82523329-dc46a780-9b23-11ea-9de0-30502d3fbdb2.PNG)

(The file does exist, despite the error).

**Comment by DHowett** [comment]
Er, we don't control the replacement you're using for `xdg-open`... It looks like it's not doing path translation (evidenced by the `/mnt/c` in the error message coming from a Windows utility.)

**Comment by yusufabukar** [comment]
@DHowett how would the path translation be resolved then?

**Comment by DHowett** [comment]
You'll have to take that up with the author of your `xdg-open` integration. They should be using the `wslpath` utility to translate WSL paths into Windows ones.
