### ISSUE TITLE
user name(s) in tab title

### ISSUE THREAD

**Issue by otalado** [microsoft/terminal#6070]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

<!-- 
Well, if you think that my opinion is valid, implement it. In case you don't think so, I just like that you drop me a line to tell me where may thinking went wrong.

**Comment by DHowett** [comment]
You can put [whatever you want](https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title) in the tab title.
