### ISSUE TITLE
There should be no dead zone on top of maximized terminal

### ISSUE THREAD

**Issue by VFLashM** [microsoft/terminal#6072]
# Description of the new feature/enhancement

When terminal is maximized, tabs cannot be switched if mouse is on top of the screen. There is a dead zone on top of the tab. There should be none.

It may sound weird, but it's a common UX pattern. When you want to switch to the tab using the mouse you bring the mouse all the way up, then only move it horizontally to choose the tab.

If there is a dead zone on the top pixel of the display, it helps no one, but makes it significantly harder to switch terminal tabs using the mouse.

For the record, it's a common problem for all apps providing tabbed interface and all major browsers do it right (as in make tabs clickable all the way up).

# Proposed technical implementation details (optional)

Tab click zone should extend to the top of the terminal.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make [sure for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+maximized+space+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #2541 for more discussion.

/dup #2541

This is also already in a PR - #5881
