### ISSUE TITLE
[Ubuntu18.04] Unable to execute the command if searched using "reverse-i-search"

### ISSUE THREAD

**Issue by prayagsingh** [microsoft/terminal#6073]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce
1. press ctrl R in Ubuntu 18.04 terminal(windows-terminal) to search the command and press Tab key to complete the command.
eg: In my case, i was searching for docker-compose -f docker-compose.yaml up -d command

# Expected behavior
   If pressed `Tab` key to complete the command in `reverse-i-search` then it shouldn't freeze the cursor in the beginning of the command. 

# Actual behavior
  1. I'm trying to run the command using `reverse-i-search (ctrl R)`. Search is working fine but if I'm using `Tab` key while searching to complete the command in `reverse-i-search` then the cursor freezes in the beginning of the command and when I'm trying to `execute` it by pressing `enter key` then it is not happening. It stuck.
  2. Even `ctrl C` is not working. Only way to get out of this is to close the terminal.

**Comment by zadjii-msft** [comment]
Huh, that's certainly weird. It sounds like the focus got out of the Terminal and into some other UI element. Does clicking on the Terminal, in the text area restore focus to terminal (allowing input again)?

**Comment by prayagsingh** [comment]
No. It stop responding. I'm facing this issue from last couple of months. Earlier I reported this bug in WSL project(thought that this is a wsl issue)

**Comment by onomatopellan** [comment]
Same issue. In my case the bash shell hangs because it's scanning every file available in PATH, specially in /mnt/ directories. See https://github.com/microsoft/WSL/issues/4966#issuecomment-640135458

Easiest way to reproduce: From bash type `unshare` and press TAB two or tree times.

**Comment by zadjii-msft** [comment]
Sorry for the delay, we've had a bit of a busy month and are just catching up on triage. 

@prayagsingh does @onomatopellan's fix from microsoft/WSL#4966 help?

> To test if that's the problem, from bash run this:
> 
> ```
> export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> ```
> 
> and after that try again using reverse-i-search. Now there shouldn't be any hangs.

**Comment by prayagsingh** [comment]
@zadjii-msft yes it works but commands like `code .` and `explorer.exe .` stopped working because the `Path` isn't present.
```
alpha@GHOST-RIDER:/c/Users/GHOST-RIDER$ code .

Command 'code' not found, did you mean:

  command 'cde' from deb cde
  command 'ode' from deb plotutils
  command 'tcode' from deb emboss
  command 'node' from deb nodejs
  command 'cobe' from deb python-cobe
  command 'cdde' from deb cdde

Try: sudo apt install <deb name>

alpha@GHOST-RIDER:/c/Users/GHOST-RIDER$ explorer.exe .
explorer.exe: command not found
```

Below is the list of Path's assigned before applying @onomatopellan fix. 
```
/home/alpha/.local/bin:/home/alpha/GoWorkspace/src/github.com/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/Program Files (x86)/NetSarang/Xshell 6/:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client/:/c/Program Files/Intel/iCLS Client/:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Users/GHOST-RIDER/AppData/Local/Programs/Python/Python36-32/:/c/Users/GHOST-RIDER/AppData/Local/Programs/Python/Python36-32/Scripts/:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/c/WINDOWS/System32/OpenSSH/:/c/Android:/d/BlockChain/IPFS/go-ipfs_v0.4.17_windows-amd64/go-ipfs:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Git/bin:/c/MinGW/bin:/c/Program Files/MongoDB/Server/4.0/bin:/c/Program Files (x86)/HP/Common/HPDestPlgIn/:/c/Go/bin:/c/Program Files/PuTTY/:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files/nodejs/:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/MySQL/MySQL Shell 8.0/bin/:/c/Users/GHOST-RIDER/go/bin:/c/Users/GHOST-RIDER/AppData/Local/GitHubDesktop/bin:/c/Users/GHOST-RIDER/AppData/Local/Microsoft/WindowsApps:/c/Users/GHOST-RIDER/AppData/Roaming/npm:/d/Installation/IntelliJ IDEA 2019.3.3/bin:/c/Users/GHOST-RIDER/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin:/snap/bin:/home/alpha/GoWorkspace:/usr/local/go:/home/alpha/GoWorkspace/bin:/home/alpha/GoWorkspace/bin:/usr/local/go/bin
``

**Comment by zadjii-msft** [comment]
Okay well that's good to know. If that's the case, then this definitely isn't a _Terminal_ issue, but something more fundamental to WSL. This will probably be better served by continuing the discussion in microsoft/WSL#4966. Thanks!
