### ISSUE TITLE
For MacOS

### ISSUE THREAD

**Issue by peterwillcn** [microsoft/terminal#6074]
microsoft terminal run in MacOS

**Comment by zadjii-msft** [comment]
Please make sure to search for duplicates when filing new issues.

/dup #2331 #499 #4235

> From https://github.com/microsoft/terminal/issues/4235#issuecomment-574748858
> 
> > We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.
> 
> s/linux/macOS/
> 
> /dup #2331 #504 #563 #624 #2466 #699 #498
