### ISSUE TITLE
copy paste address from windows explorer not working

### ISSUE THREAD

**Issue by ne0rrmatrix** [microsoft/terminal#6079]
When copy pasting text from any app it works as expected with right click

When copy and paste address from windows explorer nothing happens. Selecting copy after right clicking on address bar in Windows explorer copies text to clipboard but when u right click in terminal it does not paste. If i right click on text from any app it paste in terminal. 

If i right click on text in windows explorer it pastes in terminal with no issues. Right clicking on address bar and selecting copy then trying to paste in terminal does not work.

Is this intended?

**Comment by zadjii-msft** [comment]
_wat_

Uh, no, that's not intended. No idea why that doesn't work 😰

**Comment by ne0rrmatrix** [comment]
reply i found another issue. It was user error. I right clicked on windows explorer address bar and it does not copy but if i click on whitespace to the right of text it auto selects all and if i copy paste that it works. But right clicking on copy address does not. 

This does work fine with regular cmd prompt and is only affecting the 1.0 version of terminal i did not notice it on earlier versions. So it is a little UI issue with one method of copy paste. 

To reiterate right clicking on windows explorer address bar and selecting copy address is bugged for paste. Work around is click to right of address on whitespace and it auto selects and and normal right click on selected text will copy paste just fine. Its a weird little issue i must say.

**Comment by DHowett** [comment]
Wait - are you using "Copy Address" or "Copy Address as text"?

**Comment by ne0rrmatrix** [comment]
copy address which works fine with cmd prompt i can use either copy address as text of simply copy address and it will paste in normal cmd.exe window. It would be useful to unify that behavior with cmd prompt window if it is intended. Otherwise it could be confusing.

**Comment by DHowett** [comment]
Thanks. This is very useful info.
