### ISSUE TITLE
Double click seclection of text in terminal.

### ISSUE THREAD

**Issue by Droidzzzio** [microsoft/terminal#6081]
# Description of the new feature/enhancement
While using the terminal as i use a lot because i am a security researcher and while selecting a text by double click on terminal , it is not selecting the appropriate text it should as it runs perfectly fine in command prompt but not working in windows terminal.

# Proposed technical implementation details (optional)
I am attaching two Screenshots of terminal and command prompt so that you can see the text being selected. at once. 
![cmdprompt-terminalissue](https://user-images.githubusercontent.com/34626959/82558028-78a39500-9b8a-11ea-8c46-e778cf68fdbc.PNG)
![windowsterminalissue](https://user-images.githubusercontent.com/34626959/82558033-79d4c200-9b8a-11ea-97a6-4c9df6a3ef2c.PNG)

**Comment by zadjii-msft** [comment]
This is due to the fact that the legacy console and the Terminal have different `wordDelimiters` by default - try changing the [`wordDelimiters`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#word-delimiters) property in your settings to remove the `.`
