### ISSUE TITLE
Feature request: Profile Order property in Settings

### ISSUE THREAD

**Issue by edhcah** [microsoft/terminal#6083]
Would be great to have a property like "profileOrder" to set the position of the Profile in the dropdown based on integer instead of having to insert new profiles in the position you want within the settings file.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571 

I'd also check out #5888, which has got a spec in progress for this feature 😄

**Comment by edhcah** [comment]
> Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1571 for more discussion.
> 
> /dup #1571
> 
> I'd also check out #5888, which has got a spec in progress for this feature 😄

Thanks....did not see these when I was searching before posting!
