### ISSUE TITLE
Add Yaru scheme

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/terminal#6085]
# Description of the new feature/enhancement

I think it would be totally awesome to add Ubuntu's theme to the default schemes considering WSL is a thing.

![Screenshot from 2020-05-10 18-20-44](https://user-images.githubusercontent.com/10495562/82565495-87695800-9b48-11ea-90ac-013cf863fb4c.png)

# Proposed technical implementation details (optional)

In Terminal, using different themes greatly help differentiate which environment we've started. Starting Ubuntu, PowerShell or Command Prompt should have different colours so we know where we're at.

```json
{
    "name": "Yaru",
    "foreground": "#d3d7cf",
    "background": "#300a24",
    "cursorColor": "#eeeeec",
    "black": "#2e3436",
    "red": "#cc0000",
    "green": "#4e9a06",
    "yellow": "#c4a000",
    "blue": "#3465a4",
    "purple": "#75507b",
    "cyan": "#06989a",
    "white": "#d3d7cf",
    "brightBlack": "#555753",
    "brightRed": "#ef2929",
    "brightGreen": "#8ae234",
    "brightYellow": "#fce94f",
    "brightBlue": "#729fcf",
    "brightPurple": "#ad7fa8",
    "brightCyan": "#34e2e2",
    "brightWhite": "#eeeeec"
}
```

**Comment by zadjii-msft** [comment]
Wait, I thought Tango was Ubunutu's default theme?
https://github.com/microsoft/terminal/blob/a472d21d896a4fe37cf01175971d0d582f4a1ec9/src/cascadia/TerminalApp/defaults.json#L226-L247

I mean, we could totally add that one to the defaults too, but it's pretty darn similar to Tango already...

**Comment by NatoBoram** [comment]
That indeed looks *very* similar! But there `"background": "#000000"` instead of `"background": "#300a24"`, could we add this to Ubuntu's default config?

**Comment by NatoBoram** [comment]
That indeed looks *very* similar! But there `"background": "#000000"` instead of `"background": "#300a24"`.

Could we add `"colorScheme": "Tango Dark"` and `"background": "#300a24"` to Ubuntu's default config?

Something like this : 

```json
{
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "Windows.Terminal.Wsl",
    "colorScheme": "Tango Dark",
    "background": "#300a24"
}
```

I'm pretty sure Windows users will have a hard time finding `#300a24` to add it to their Ubuntu config, so I think just adding those two lines would be a very efficient change.

**Comment by DHowett** [comment]
I'm cool with this! I didn't even know it was called Yaru.

**Comment by DHowett** [comment]
I tagged this one up as Help Wanted. I'd do it personally, but my triage queue is too deep for me to _breathe_ at the moment. :smile: If somebody wants to yeet this into defaults.json(c), I'll be grateful.

@cinnamon-msft for the FYI on default color scheme availability!

**Comment by MarcoBarna** [comment]
Here is mine that goes very very well with default windows 10 dark theme.
On every shell settings you have to add : 
```
"useAcrylic" : true,
"acrylicOpacity" : 0.85,
"colorScheme" : "Tomorrow Night Eighties"
```

and here is the color scheme
```
{
  	"name": "Tomorrow Night Eighties",
  	"black": "#000000",
  	"red": "#f2777a",
  	"green": "#99cc99",
  	"yellow": "#ffcc66",
  	"blue": "#6699cc",
  	"purple": "#cc99cc",
  	"cyan": "#66cccc",
  	"white": "#ffffff",
  	"brightBlack": "#000000",
  	"brightRed": "#f2777a",
  	"brightGreen": "#99cc99",
  	"brightYellow": "#ffcc66",
  	"brightBlue": "#6699cc",
  	"brightPurple": "#cc99cc",
  	"brightCyan": "#66cccc",
  	"brightWhite": "#ffffff",
  	"background": "#2d2d2d",
  	"foreground": "#cccccc"
}
```
Here is the result:

![Annotazione 2020-05-22 190358](https://user-images.githubusercontent.com/34555572/82693054-16699380-9c61-11ea-8e2b-035f7a5bc2cd.png)

**Comment by NatoBoram** [comment]
Thanks @MarcoBarna, but you might want to raise a different issue. This issue is about Ubuntu's theme, **Yaru**, which uses **Tango Dark**'s colours and a different background colours.

**Comment by MarcoBarna** [comment]
Will do.

**Comment by egmontkob** [comment]
That terminal looks like gnome-terminal which defaults to the Tango theme (as for the 16 indexed colors). The Yaru desktop theme might provide the default background and foreground colors.

To further complicate: current devel version of gnome-terminal (the 3.37 series) has switched to a new theme ([g-t 72](https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/72)), which is debated and might get further improved or reverted ([g-t 246](https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/246)), we don't know yet.

**Comment by NatoBoram** [comment]
I don't think it's a problem until it actually appears in Ubuntu's latest version by default. At that moment it'll just be a matter of adding the theme.

**Comment by kgnfth** [comment]
it does not look nice to me

**Comment by zadjii-msft** [comment]
Hey we discussed a bit more - we probably shouldn't be the ones shipping this scheme. The _technically correct_ solution would be for Ubuntu to ship this as a [fragment ](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions)alongside their package (if they wanted to customize their profile in such a way). Thanks though!
