### ISSUE TITLE
Launching an Electron app blocks the devtool bar to open

### ISSUE THREAD

**Issue by jchomarat** [microsoft/terminal#6089]
# Environment

```none
Windows build number: windows 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

This is an extremely weird bug ...

Create an electron app using the package.json below

```
{
    "name": "app",
    "version": "0.0.1",
    "description": "",
    "main": "app.js",
    "scripts": {
      "start": "electron app.js"
    },
    "author": "xx",
    "license": "MIT",
    "private": true,
    "devDependencies": {
      "electron": "^8.3.0",
    }
}

```
then add app.js

import { app, BrowserWindow, ipcMain } from "electron";
app.allowRendererProcessReuse = true;
    
```
app.on('ready', async () => {
    const window = new BrowserWindow(
    { 
        width: 800, 
        height: 600, 
        frame: true,
        webPreferences: {
        nodeIntegration: true,
        devTools: true
        }
    }
    );
      window.webContents.openDevTools({
        mode: "right",
        activate: true
      });
});
```

Launching the app will never open the dev tools. I have tried with  embed PowerShell Core 7.0.1 and CMD. And it was working with the latest preview version of the Window Terminal.

When I however launch the same app from the PowerShell Core 7.0.1 terminal, it works

# Expected behavior

Dev tool bar must open

# Actual behavior

It does not

**Comment by zadjii-msft** [comment]
Okay this is a crazy thought, but does the window open "underneath" the Terminal? Like, lower in the window z-order?

**Comment by jchomarat** [comment]
Actually it did not open at all. However, I have passed a Windows update and it resets something because now it came back (and before you asked, yes I rebooted before opening this issue :)). Very weird. I close this ticket
