### ISSUE TITLE
Since 1.0 is out maybe drop the "(Preview)" in the title

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#6091]
1.0 is out already, maybe just remove "(Preview)" from the title when you right click on the task bar icon.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
We recently learned that the title of an application is _saved_ when you first pin it!

To remove Preview from your pin, un-pin and re-pin it.
