### ISSUE TITLE
Clicking above the tab should focus the tab

### ISSUE THREAD

**Issue by Muchiachio** [microsoft/terminal#6092]
# Description of the new feature/enhancement
Now when you try fast focusing the tab by moving mouse to the top of the screen on the full screen terminal it doesn't focus the tab, because there is a few pixel gap at the top. It would be nice if it worked similar to the browsers where tab height covers up to (X, 0) position of the screen.
![image](https://user-images.githubusercontent.com/6647444/82579396-69c2df80-9b96-11ea-9f03-c189264087f4.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make [sure for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+maximized+space+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #2541 for more discussion.

/dup #2541 #6072 

This is also already in a PR - #5881
