### ISSUE TITLE
Font rendering in WSL

### ISSUE THREAD

**Issue by debjan** [microsoft/terminal#6093]
This is screenshot from Windows console running WSL bash:

![console](https://user-images.githubusercontent.com/1919296/82579402-0a60d180-9b8e-11ea-8a80-8f25638e57f0.png)

While this is from Windows terminal:

![terminal](https://user-images.githubusercontent.com/1919296/82579423-13ea3980-9b8e-11ea-8887-fd9d0b05a006.png)

Why can this be an issue?

I noticed it with font shipped with WT and now trying with Consolas, but it's the same result

**Comment by DHowett** [comment]
Can you copy one of those weird characters for me?

**Comment by debjan** [comment]
@DHowett how do you mean I copy the characters?

**Comment by DHowett** [comment]
No, I mean **can you copy one to the clipboard and send it to me as a github comment?**

**Comment by DHowett** [comment]
If you cannot select text because of mc or tmux, you can hold down <kbd>Shift</kbd> and drag to select, then Shift+right click to copy.

Otherwise, you can leave off <kbd>Shift</kbd>

**Comment by debjan** [comment]
ok, character before mc keys ``

**Comment by DHowett** [comment]
Bingo! This is a /dupe of #3487. Thanks!

**Comment by debjan** [comment]
Ok thanks :)
