### ISSUE TITLE
Restart Session in Existing Tab

### ISSUE THREAD

**Issue by AlexBWM** [microsoft/terminal#6094]
Putty has a nice feature where I can
a) duplicate session
b) restart session when I get disconnected but don't close the terminal

I think it would be nice to add this feature when right clicking on the Tab so that I don't have to go through the menu.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3726 for more discussion.

/dup #3726
