### ISSUE TITLE
Adding SubMenus to Group cluster of servers

### ISSUE THREAD

**Issue by AlexBWM** [microsoft/terminal#6095]
Is it possible to add sub-menus which would allow me to cluster servers / connections

If we have 50 different servers or accounts we want to use e.g. dev, test, prod  or servers in different locations it would help to organize these better. Having to find your server in an endless list is a bit of a pain.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22menu+group%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571 #6083

I'd also check out #5888, which has got a spec in progress for this feature 😄
