### ISSUE TITLE
Readline Issue?

### ISSUE THREAD

**Issue by AlexBWM** [microsoft/terminal#6096]
When connecting to a postgres via psql on Centos there seems to be a problem when trying to get previous command back (using UP key).

The command is either not displayed, or the cursor placed in the middle of it. Also when trying to insert some text it will overwrite the following text rather than inserting it.

Is this there a problem with the readline library?  I haven't noticed it when I am just in the shell.

**Comment by zadjii-msft** [comment]
Well, this is certainly hard to debug. Sounds like there's a lot of moving pieces:
* What version of Windows are you running?
* Are you running in the Windows Terminal? If so, which version?
  - If you are using the Terminal, does this repro in a normal console window? (like `cmd.exe`)?
* Which ssh are you using (`ssh.exe` or the WSL `ssh`)? Which version?
* What versions of `postgres`, `pysql`, centos?


There's a lot  of pieces in this report, so we're going to need to narrow it down some...
