### ISSUE TITLE
On Install add Terminal to Win+X toolbar

### ISSUE THREAD

**Issue by kilasuit** [microsoft/terminal#6097]
# Description of the new feature/enhancement

As a user that uses Win+X toolbar, it would be good to natively add Terminal to that Toolbar on the installation of Terminal

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure [to search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Win%2BX%22+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #492 for more discussion.

/dup #492 #1132 #1421 #5942
