### ISSUE TITLE
Start a new prompt in an existing instance of WT

### ISSUE THREAD

**Issue by earth75** [microsoft/terminal#6098]
# Description of the new feature/enhancement

When I open WT from the command line, it starts in a new instance every time. It would be very helpful to be able to spawn the prompt in a new tab on an existing instance of WT.

# Proposed technical implementation details (optional)

It seems natural that putting `new-tab` the first argument would do that.
E.G . : 
` "%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" new-tab -d "%V\." `

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472
