### ISSUE TITLE
Drag and drop tabs between instances (like the new Edge does)

### ISSUE THREAD

**Issue by earth75** [microsoft/terminal#6099]
# Description of the new feature/enhancement

When I am done working with multiple tabs on multiple instances of WT, I sometimes end up with several instances that hold one tab. I do not have a straightforward way to bring back the few remaining tabs together in one instance.

# Proposed technical implementation details (optional)

It would be very efficient to just be able to drag and drop tabs between WT instances.
Ideally dragging a tab outside any WT windows would spawn a new instance? (Sort of like the new Edge does with its tabs)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
