### ISSUE TITLE
Support for Hololens 2

### ISSUE THREAD

**Issue by ifsheldon** [microsoft/terminal#6101]
# Description of the new feature/enhancement
It seems there's no support for Hololens 2 yet, so I wonder whether there will be a version for Hololens 2.

# Proposed technical implementation details (optional)
Maybe only few changes to build configurations are sufficient, since there's support for windows 10 on ARM.

**Comment by DHowett** [comment]
Terminal requires the features present in desktop Windows, and hololens stand-alone use is not one of our targets. Sorry!
