### ISSUE TITLE
Windows Terminal crashes right at launch - File system error (-2015294513)

### ISSUE THREAD

**Issue by retifrav** [microsoft/terminal#6104]
# Environment

```
Windows build number: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

$ Get-ItemProperty -Path .\WindowsTerminal.exe | Format-list -Property * -Force
File:             C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
FileVersion:      1.0.2005.17002
ProductVersion:   1.0.200517002-release1.0
```

# Steps to reproduce

1. Install Windows Terminal from Microsoft Store
2. Try to launch it

# Expected behavior

Windows Terminal launches.

# Actual behavior

Windows Terminal crashes with `-2015294513` error code:

![wt-crash](https://user-images.githubusercontent.com/6904927/82593555-f96e8b00-9ba2-11ea-9c31-26cabc654cd1.png)

If I try to launch it from `PowerShell`, then:

```
$ .\WindowsTerminal.exe
Program 'WindowsTerminal.exe' failed to run: Access is deniedAt line:1 char:1
+ .\WindowsTerminal.exe /?
+ ~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\WindowsTerminal.exe /?
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Event Viewer doesn't have any records that could contain more details.

**Comment by DHowett** [comment]
Oh, that's really quite bad.

Can you file a bug in the feedback hub under the "DEVELOPER PLATFORM > APP DEPLOYMENT" category? Terminal isn't even getting launched, so we don't get a chance to see any crash information.

Afterwards, can you share that feedback item link here using the **Share Link** feature in the Feedback Hub?

**Comment by retifrav** [comment]
I submitted a report using Feedback Hub like you said, but when I clicked on Share, it just opened a new feedback submission form, so I never had a chance to copy the feedback link (there wasn't any). I even submitted it again to check if it was a temporary issue, but no - as soon as I click on Share, I just get a new feedback submission form with no chance to get the previous feedback link.

**Comment by retifrav** [comment]
...Oh well, today I woke up my PC and all of a sudden Windows Terminal launches and works fine. I can't tell what has changed in the system between yesterday and today. If I remember correctly I just installed Definitions Update (`KB2267602`) and that's it. I didn't even restart the PC (*according to the uptime value*).

Either way, the issue is solved for me, so perhaps this report can be closed, but unfortunately I can't what was causing the problem and how to fix it if it happens again.

**Comment by DHowett** [comment]
Ugh, I kinda hate when bugs just go away! Thanks for confirming, and I'm sorry that we can't help track it down. 😦
