### ISSUE TITLE
Add WSL distro default desktop wallpapers as default background

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6105]
# Description of the new feature/enhancement
When you install a distro for WSL, it should automatically launch with the default desktop wallpaper as the background to provide users with a familiar experience.

This is just a visual aesthetic that many people would appreciate. It's the small things that can make such a huge difference.
# Proposed technical implementation details (optional)
Add the background images to `defaults.json` for each distro profile. We should start with the ones in the Store like Ubuntu but we should accept community contributions for other distros that are custom imported as well such as Clear Linux.

I'd like to see background automatically set to the image stored locally on the computer to each distro profile so if I open a distro, I'll see that background by default. Users can still override it in `settings.json`.

**Comment by RobertBernstein** [comment]
@WSLUser I love this idea. I wonder if there are any (copyright) issues with including these wallpapers for different distros with the Terminal itself.

**Comment by WSLUser** [comment]
So we can look up licenses but I'm pretty sure they are MIT or GPL based. @sirredbeard would the Ubuntu wallpaper for example be permitted to be added as a default in this project? Any particular license it's under that isn't already used in this repo?

**Comment by DHowett** [comment]
I would rather leave this up to the distributions after we get a profile model they can plug into. That's the future!

**Comment by WSLUser** [comment]
Here I was hoping to quickly push a PR to get Ubuntu (then probably Pengwin) set up.

**Comment by DHowett** [comment]
I've got some ideas floating around that would let a distribution appx give us some information -- still workshopping it, but this would let them seamlessly add Terminal profile data but not fail when Terminal wasn't installed

**Comment by WSLUser** [comment]
I'm just hoping to provide a "out of box" experience. If the distros can provide it for Terminal then great but if not, then Terminal should help in this scenario.

**Comment by WSLUser** [comment]
@zadjii-msft With https://github.com/microsoft/terminal/pull/10967 in play, could this be done by WT itself now?  I think it would simply be reading the image file in from the registry and creating a profile entry setting it as the wallpaper. This would be an optional setting of course.

**Comment by zadjii-msft** [comment]
Probably not, since it doesn't look like that information is in the registry:
![image](https://user-images.githubusercontent.com/18356694/131369388-ece5121b-6851-46b7-8373-cf35b2ba07ea.png)

Now that I think about this, distros are absolutely free to do this today with [fragment extensions](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions). We can probably close this one out - the onus is on distro maintainers to provide this (if they so choose).
