### ISSUE TITLE
can't find in docs how to automatically open the same pane config

### ISSUE THREAD

**Issue by born2net** [microsoft/terminal#6114]
can't find in docs how to automatically open the same pane config
would love to be able to launch terminal with already 3 opened panes
two on top and one on bottom, is it possible? 
didn't see in docs
Finally, a real terminal for windows, awesome!

**Comment by DHowett** [comment]
> Finally, a real terminal for windows, awesome!

Hey, thanks!

We have _a bit_ of documentation on this on the [commandline arguments](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=powershell#command-line-argument-examples) page.
Right now, we don't support launching multiple panes by default without command line args, but we are considering that over in #756. It says "multiple tabs", but the work overlaps _a lot_ so we would do them at the same time.

For now, you can add a desktop or start menu shortcut that runs wt with the `split-pane` arguments :smile:

/dup #756
