### ISSUE TITLE
Window not maximized

### ISSUE THREAD

**Issue by alreadytakenmyfoot** [microsoft/terminal#6116]
Always opens in partial-screen sized window, not maximized, despite specification "Maximized" in the shortcut that opens it. 
# Environment
Win10 1909  18363.535
Windows Terminal version 1.0.1401.0

Any other software?
```

# Steps to reproduce

<!-- A description of how to trigger this bug. -->
Click shortcut.

# Expected behavior
<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
Maximized

# Actual behavior

<!-- What's actually happening? -->
Not maximized.

**Comment by DHowett** [comment]
Unfortunately, and this is going to sound crazy, _this is a limitation of Store-deployed applications_. I know, I know, that should absolutely not be the case.

We're using #2386 to track the internal operating system bug (MSFT:23202140) for this. I know you won't be able to follow the link, but this is partially for our own book keeping.

/dup #2386.

**Comment by DHowett** [comment]
Oh! You can add `launchMode` to your settings and set it to `maximized`, though, to launch maximized by default. More info at [the launch maximized docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#launch-settings)

**Comment by alreadytakenmyfoot** [comment]
On Thu, 21 May 2020 15:41:37 -0700
"Dustin L. Howett" <notifications@github.com> wrote:
>
> <code>launchMode</code> to your settings and set it to
<code>maximized</code>

Perfect.  Thank you.   



> More info at
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#launch-settings

Dustin, are those all of the settings that are available?

**Comment by DHowett** [comment]
Nah, there's a whole ton of settings. I encourage you to browse those settings docs -- there's an opportunity for you to customize keyboard interaction, colors, profiles, applications to launch, and basic features like copy/copy on select/window snapping and resizing all in that JSON file.
