### ISSUE TITLE
no visible way to adjust text size

### ISSUE THREAD

**Issue by alreadytakenmyfoot** [microsoft/terminal#6117]
# Environment

Win10 1909 18363.535
Windows Terminal version (if applicable):1.0.1401.0

Any other software?
```

# Steps to reproduce

<!-- A description of how to trigger this bug. -->
Run Command Prompt of Windows Terminal 
# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
Settings as in cmd.exe 
# Actual behavior

<!-- What's actually happening? -->
no visible way to adjust text size

**Comment by DHowett** [comment]
Thanks! So, right now, there's no visual way to update your fonts. There _is_ a JSON settings file, though, that you can update following the [settings documentation](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#text-settings) (I've linked directly to the Text Settings page.)

For a graphical property page, I'll refer you to #1564.
