### ISSUE TITLE
Document our telemetry collection and out-out steps

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#6118]
> Thanks for the detailed response. It totally slipped my mind that the gathered data is available to browse at any time at the Windows level.
> 
> Maybe this is really a matter of documentation then? If that information were put forward it would likely put a lot of folks at ease.
> 
> Something like this dropped into the README  "If you're using basic Windows telemetry, nothing is ever collected or sent to Microsoft from the Terminal app, and if you're using more in depth Windows telemetry settings you can see what's collected by going to your Windows privacy settings".
> 
> Or perhaps under a FAQ / wiki for the question of "Why isn't there a telemetry option to toggle?".
> 
> _Originally posted by @nickjj in https://github.com/microsoft/terminal/issues/5331#issuecomment-632395874_

**Comment by DHowett** [comment]
@cinnamon-msft this may need some wordsmithing for the docs site. Putting up a big ole' boyo that says "Go to the diagnostic data page in windows settings (deep link here) and choose Basic".

**Comment by cinnamon-msft** [comment]
I'm going to move this over to the docs repo. :)
