### ISSUE TITLE
Split Window, Multiple Tabs

### ISSUE THREAD

**Issue by mdtauk** [microsoft/Terminal#612]
This idea would be useful to have in the TabView control itself, but the Windows Terminal is a good use case

The ability to tear off a tab, and snap it to one side of the same Windows Terminal window, so you can have multiple types of consoles open in one window.

Support side by side snapping, as well as top and bottom stacking.

Reading values from one screen, like a list of partitions and disks from diskpart - while deleting or manipulating a specific partition for example...

**Comment by DHowett-MSFT** [comment]
Hey there, we're tracking this in #532. Feel free to upvote it with the 👍 button and add your requests and comments!
