### ISSUE TITLE
Add option: Adjust lightness of indistinguishable text

### ISSUE THREAD

**Issue by hectormz** [microsoft/terminal#6121]
# Description of the new feature/enhancement

`ConEmu` has an [option ](https://conemu.github.io/blog/2016/04/28/Build-160428.html) to:
> ‘Adjust lightness of indistinguishable text’ on the ‘Colors’ settings page. The idea is to make text readable if certain foreground and background colors are indistinguishable for current palette. ConEmu will try to change the lightness of the foreground text.

This is useful when two light colors are displayed with each other. Here is an example using `Solarized Git` color scheme with the feature off:

![image](https://user-images.githubusercontent.com/23343812/82617617-73901700-9b85-11ea-8462-b8a178ae99fa.png)

and with it on:

![image](https://user-images.githubusercontent.com/23343812/82617597-65da9180-9b85-11ea-857b-6db88be2e07f.png)

# Proposed technical implementation details (optional)

It would be great to have a similar flag to set as an option in `settings.json`

`ConEmu`'s method could be an inspiration. Here is the [commit](https://github.com/Maximus5/ConEmu/commit/51ba398bea702e68ef439ea66181568b0f85f875) that added it.

**Comment by DHowett** [comment]
Thanks for the request! This is tracked at /dup #2368 (which is also inspired by the ConEmu feature!)

**Comment by DHowett** [comment]
I'm sorry, I meant #2638.

**Comment by hectormz** [comment]
Awesome, I didn't quite find it. I'll check out that issue!
