### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by bum** [microsoft/terminal#6122]
Always get blurry text
![image](https://user-images.githubusercontent.com/962875/82632609-eef3d600-9c22-11ea-9a31-8f61d697a417.png)

**Comment by DHowett** [comment]
https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#the-text-is-blurry

**Comment by bum** [comment]
![image](https://user-images.githubusercontent.com/962875/82743709-63e91c00-9d99-11ea-9a97-e767027bb9e9.png)
Thanks for your reply, it still get blurry when applied those settings.

**Comment by DHowett** [comment]
Sorry, the periods are actually part of the name. I realize now how they can be confused for keypaths.

At the top level,

`"experimental.rendering.software": true`

**Comment by bum** [comment]
Both ways have the same effect. When I save settings.json, the terminal looks clean
![image](https://user-images.githubusercontent.com/962875/82758883-68eab180-9e13-11ea-868f-0b71dba40dae.png)
Then I scroll up and down, it gets blurry again. 
![image](https://user-images.githubusercontent.com/962875/82758900-90da1500-9e13-11ea-9979-bf28ff72241e.png)
Save again, it's clean, scroll again, it's blured again
