### ISSUE TITLE
ctrl + c not break after copy(ctrl + c) & paste(ctrl + v)

### ISSUE THREAD

**Issue by chain710** [microsoft/terminal#6126]
# Environment

```
Windows build number:  Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce
1. ctrl + c copy anything from terminal
2. ctrl + v paste into terminal
3. ctrl + c try to break, won't work

# Expected behavior

step 3 ctrl + c breaks normally

# Actual behavior

step 3 ctrl + c break doesn't work

# More

if ctrl + c copy from notepad, then step 3 ctrl + c works perfectly

**Comment by zadjii-msft** [comment]
This is certainly curious - I'm not seeing this happen with `ping.exe`. Which application are you trying to kill with <kbd>Ctrl+c</kbd>?

**Comment by chain710** [comment]
> This is certainly curious - I'm not seeing this happen with `ping.exe`. Which application are you trying to kill with Ctrl+c?

I was not trying to kill any program: just try to break current input in terminal

**Comment by zadjii-msft** [comment]
@chain710 which shell are you using in the Terminal? `cmd`? `powershell`? `bash`?
