### ISSUE TITLE
Add "Python" new tab to the windows terminal automatically

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#6131]
在安装Windows terminal后，会自动添加CMD,Powershell，Powershell Core和适用于Windows的Linux子系统到Windows Terminal的选择栏中，但是安装完Python后并不会自动添加，我希望可以在以后的版本中可以自动添加Python终端到Windows Terminal中，无论Python安装的来源是Microsoft Store还是官网下载的可执行文件安装包（EXE 或者 MSI）
After installing Windows Terminal,CMD,Powershell,Powershell Core and Windows Subsystem for Linux will be automatically added to the selection bar of Windows Terminal. However, Windows Terminal will not be automatically added after installing Python. I hope that Python terminal can be automatically added to Windows terminal in a future versions.Whether the Python installation comes from the Microsoft Store or the Executable File installation package(EXE or MSI) downloaded from the official website.

**Comment by DHowett** [comment]
Thank you! Because Python can be installed in so many different places, it will be difficult for Terminal to choose what version to offer. We don't want the list to explode with too many different versions, either.

We think it is better to let the users configure their python profiles :smile:

**Comment by Genius-Tools** [comment]
How do we add a chosen python install to the windows terminal please?
