### ISSUE TITLE
Windows terminal doesn't open in other directory

### ISSUE THREAD

**Issue by lieven121** [microsoft/terminal#6132]
# Environment

```none
Windows 1909: build 18363.836
Windows Terminal 1.0.1401.0

```

# Steps to reproduce
Run the windows terminal in a directory
![image](https://user-images.githubusercontent.com/7773244/82663047-3bdda980-9c2f-11ea-969f-c67e96ced3d7.png)
or try to open it from another directory
![image](https://user-images.githubusercontent.com/7773244/82663077-4d26b600-9c2f-11ea-8c0c-bb31c51b664a.png)

# Expected behavior

The windows terminal should open in that directory
![image](https://user-images.githubusercontent.com/7773244/82663603-43518280-9c30-11ea-88d1-41ed85811a42.png)

# Actual behavior
The terminal opens in C:\Users\[user]

![image](https://user-images.githubusercontent.com/7773244/82663578-3765c080-9c30-11ea-9837-6639c012a61d.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+explorer+%22address+bar%22+is%3Aclosed) when filing new issues.  We wanted to make wt behave like cmd or powershell here, but unfortunately, there were just too many odd edge cases to make this work right. There are more details over in #878 (comment) if you want more reading.

/dup #878

**Comment by lieven121** [comment]
> Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+explorer+%22address+bar%22+is%3Aclosed) when filing new issues. We wanted to make wt behave like cmd or powershell here, but unfortunately, there were just too many odd edge cases to make this work right. There are more details over in #878 (comment) if you want more reading.
> 
> /dup #878

Sorry, I only searched the open issues. Thank you for the feeback.

For everyone else who doesnt want to look tough the previous threads the answer to make it work would be.
wt -d .
