### ISSUE TITLE
Insert mode doesn't work

### ISSUE THREAD

**Issue by DjArt** [microsoft/terminal#6133]
# Environment

```none
Windows build number: 10.0.19631.1
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

Type text in console, back to line start, press key `Insert` on your keyboard and type text again.

# Expected behavior

Characters will be replaced.

# Actual behavior

Characters inserted into line without replacing.

**Comment by zadjii-msft** [comment]
This definitely sounds like it's something that should be controlled by whatever shell you're running - are you using `cmd`, `powershell`, `bash`/`zsh`/some other WSL shell?

**Comment by DjArt** [comment]
It's bash.

**Comment by zadjii-msft** [comment]
Have you done anything to modify your system at all? It looks like [bash has an overwrite mode](https://askubuntu.com/questions/641035/does-bash-or-any-shell-for-that-matter-have-an-overwrite-mode), but it's not enabled by default. By default, `bash` should be behaving in insert mode, so there must be something else that's controlling this

**Comment by DjArt** [comment]
No. But old console in WSL doesn't handle insert mode too, so, probably, my issue.
Also, in cmd WT and old console insert mode works.

**Comment by zadjii-msft** [comment]
Great, thanks for following up!
