### ISSUE TITLE
Add the possibility to rename the tabs. 

### ISSUE THREAD

**Issue by mrbaranovskiy** [microsoft/terminal#6135]
Could you please add the possibility to rename tabs. 

For example, if you have a lot of git repos opened it is easy to be confused. 

Regards.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22rename+tab%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1079 for more discussion.

/dup #1079
