### ISSUE TITLE
Unicode characters not rendering correctly

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/terminal#6136]
# Environment

Microsoft Windows [Version 10.0.18363.720]
Terminal v1.0.1401.0

(It's a VM if that makes a difference)

# Steps to reproduce

Install Rich python library (https://github.com/willmcgugan/rich), and run the following:

```
python -m rich.color
```

# Expected behavior

Unicode box characters should render normally. The same output works with OSX / Linux.

# Actual behavior

You should see broken unicode characters in the middle of the tables. Here are some examples:

<img width="1200" alt="Screen Shot 2020-05-22 at 14 38 00" src="https://user-images.githubusercontent.com/554369/82674016-99c3be80-9c3a-11ea-98ba-31638d3b4073.png">

<img width="1193" alt="Screen Shot 2020-05-22 at 14 38 25" src="https://user-images.githubusercontent.com/554369/82674029-9e887280-9c3a-11ea-82ce-4adacc75893f.png">

If I was to hazard a guess I'd say that the utf-8 has been split over some internal buffer, and a multi-byte character was truncated at the boundary.

**Comment by skyline75489** [comment]
This feels like a dup of #714 and/or #455

**Comment by DHowett** [comment]
This feels more like... hmm

We've got a bunch of validation that Terminal and Console properly buffer UTF-8 when it comes in.

This sound suspiciously like #386, which ended up being a CMD issue.

Is this a Python issue? I found [PEP-0528](https://www.python.org/dev/peps/pep-0528/), which discusses getting UTF-8 out of Python onto the console.

Of note: if you run it under WSL, it is _beautiful_. Same library, same terminal, different cpython runtime. :smile:

**Comment by willmcgugan** [comment]
Very curious.

I've discovered that if I write the output to a file rather than to the terminal, and the use the `type` command to write the file to the terminal, the issue is no longer present.

But if I then open the same file in Python and write it to stdout, the issue appears. But *only* if I do the write in a single chunk. If I write in smaller chunks then it's fine.

I tried this on Python 3.8.1, 3.8.3, 3.9.0a6 and all had the same problem.

So it's clearly related to Python, but quite where the fault lies I'm not sure!

Let me know if there is anything I can do to help you diagnose. I could send you the output from the color table if that helps.

**Comment by DHowett** [comment]
So, I'm also unsure of how to proceed. I think the best way forward would be a bug filed on cpython (bugs.python.org). I'm concerned about their buffering, given your remark about doing the write in a single chunk. :smile:

There's a bit of stuff here-
https://github.com/python/cpython/blob/578c3955e0222ec7b3146197467fbb0fcfae12fe/Modules/_io/winconsoleio.c#L979-L988
-that might be of interest. This is the only place they call WriteConsoleW.

I'm gonna close this one out as, perhaps, something we don't have too much control over.

**Comment by DHowett** [comment]
BINGO!

/dup https://bugs.python.org/issue37871
