### ISSUE TITLE
WSL profile not found if Terminal started early

### ISSUE THREAD

**Issue by gozdal** [microsoft/terminal#6138]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

1. Open the Terminal
1. Set WSL 1, Ubuntu 18.04 as default profile
1. Restart Windows

# Expected behavior

WSL terminal should appear after logging in.

# Actual behavior

Terminal complains that the profile cannot be loaded (don't remember the exact wording). If I restart the Terminal, Ubuntu profile loads without a problem.
My guess is that some service responsible for WSL is not yet loaded when Terminal starts.

**Comment by DHowett** [comment]
Not sure what we can do about this one. We can't ask what WSL distributions exist when WSL isn't responding, so the safest option we have is to not list them.

Since there doesn't seem to be a global systemwide notification that WSL is "ready", we can't even subscribe to it ☹️

**Comment by gozdal** [comment]
Maybe a logic that waits for `LxssManager` or `LxssManagerUser_XYZ` service to come up if the started profile is WSL?
