### ISSUE TITLE
bug: ctrl-w does not hide the tab bar

### ISSUE THREAD

**Issue by bef178** [microsoft/Terminal#614]
Reproduce steps:
1 Open Windows Terminal
2 Press ctrl-t, so there's two tab, tab bar shows
3 Close one tab by click tab close button, there is one tab and tab bar hides, so it appears as step 1
3' Close one tab by press ctrl-w, there's one tab but tab bar remains.
![3'](https://user-images.githubusercontent.com/2749912/57436084-8d5c0600-7271-11e9-839e-a732995bcd25.png)

No idea about which is expected but inconsistency is unexpected.

**Comment by zadjii-msft** [comment]
This is a known issue internally, but thanks for filing the issue!

This is definitely not expected - if a user doesn't have `alwaysShowTabs` set to true, then the tabs should definitely hide here.
