### ISSUE TITLE
Update color scheme for any tab/pane on the fly

### ISSUE THREAD

**Issue by hectormz** [microsoft/terminal#6141]
# Description of the new feature/enhancement

I'd like to be able to set the color scheme for any tab or pane I have open in Windows Terminal with a command. If I'm temporarily opening multiple instances of the same profile, I'd like to distinguish them by setting the color scheme for that instance to any of the available color schemes I have. The alternative to this would be to go into settings and duplicate profiles, but with different color schemes etc.

I don't believe this has been raised here so far. If it's possible, I have not found it in any documentation yet.

# Proposed technical implementation details (optional)

I think this is not yet possible because I don't think are Windows Terminal commands from within Windows Terminal yet. I know you can run `wt.exe` with some options to configure how a new instance of Windows Terminal is launched.

Assuming there will be a single executable for commands in the future from within Windows Terminal, something like: 
```
<executable.exe> --color "Campbell"
```
would be nice.

Or even:
```
wt-color "Campbell"
```

**Comment by zadjii-msft** [comment]
So, [colortool ](https://github.com/microsoft/terminal/tree/master/src/tools/ColorTool)can't quite yet read color schemes that you have installed in the terminal settings, but I think you can usually find a colortool compatible version of most colorshemes for the Terminal.

Then the workflow with colortool is just `colortool -x Campbell`.

Then there's also #4472 for "run commands in the current window", and #5401 for "add a shortcut action to switch to a specific color scheme", which will then pair well with #2046/#5400 for "I want to be able to run an action in the current window" (from the command palette). _All_ those together will combine to let you do something like <kbd>Ctrl+shift+P</kbd>, "Change colorscheme", (pick the colorscheme), similar to how vscode works.

**Comment by hectormz** [comment]
@zadjii-msft thanks for all the details and links!
I think `colortool` would help me to start.

#4472/#5401 is more ideal, and picking colorscheme from a command palette would be most ideal.

I have some custom schemes in Terminal settings that would be nice to use instead of figuring out how to hook them up with `colortool`.

**Comment by amapianosa** [comment]
lets see how it goes

**Comment by j4james** [comment]
The idea of having the colortool read schemes from the Terminal settings was suggested once before in issue https://github.com/microsoft/terminal/issues/3687#issuecomment-558175555.

**Comment by zadjii-msft** [comment]
Okay, since the above solutions sound good, I'll close this in favor of the linked threads. Thanks!
