### ISSUE TITLE
Possible to have a search (in text) feature ?

### ISSUE THREAD

**Issue by softlion** [microsoft/terminal#6143]
# Description of the new feature/enhancement

It would be amazing if you could filter out / search text in the terminal windows.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is something we already support today - it's bound to <kbd>Ctrl+shift+f</kbd> [by default](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L279). Please make sure to search for duplicates when filing new issues. 

/dup #605 #1766 #2847 #2940 #3607 #3469
