### ISSUE TITLE
Maximized (not fullscreen) Terminal window blocks return of auto-hidden taskbar

### ISSUE THREAD

**Issue by wightsci** [microsoft/terminal#6145]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

1.0.1401.0

Any other software?
```

# Steps to reproduce

Set Windows taskbar to auto-hide

- Run Terminal
- Maximize Terminal
- Move mouse to bottom edge of screen

# Expected behavior

Taskbar appears

# Actual behavior

Taskbar does not appear

**Comment by DHowett** [comment]
Hmm, we thought we fixed this a long time ago. Your auto-hide taskbar is on the _bottom_?

**Comment by wightsci** [comment]
Yes, it's at the bottom of the screen.

**Comment by wightsci** [comment]
Might be related to multi-screen set up as it's not happening when I'm on one screen only.

**Comment by DHowett** [comment]
So, we explicitly endeavoured to fix this in https://github.com/microsoft/terminal/pull/4857. Interesting notes in the PR body...

> Note to future code archeologists:
This doesn't seem to work for fullscreen on the primary display. However, testing a bunch of other apps with fullscreen modes and an auto-hiding taskbar has shown that none of them reveal the taskbar from fullscreen mode. This includes Edge, Firefox, Chrome, Sublime Text, Powerpoint - none seemed to support this.
>
> This does however work fine for maximized.

Unfortunately, I can't reproduce this even with a multi-monitor setup.

Are you using any shell extensions that might be confounding?
