### ISSUE TITLE
Possible default for dark mode

### ISSUE THREAD

**Issue by MarcoBarna** [microsoft/terminal#6148]
Thanks Scott Hanselman on YT i have set this theme for all of my shells.
I think it goes really really well with default dark mode.
The setting to get this are:
On every shell settings you have add :

```
"useAcrylic" : true,
"acrylicOpacity" : 0.85,
"colorScheme" : "Tomorrow Night Eighties"
```

and here is the color scheme

```
{
  	"name": "Tomorrow Night Eighties",
  	"black": "#000000",
  	"red": "#f2777a",
  	"green": "#99cc99",
  	"yellow": "#ffcc66",
  	"blue": "#6699cc",
  	"purple": "#cc99cc",
  	"cyan": "#66cccc",
  	"white": "#ffffff",
  	"brightBlack": "#000000",
  	"brightRed": "#f2777a",
  	"brightGreen": "#99cc99",
  	"brightYellow": "#ffcc66",
  	"brightBlue": "#6699cc",
  	"brightPurple": "#cc99cc",
  	"brightCyan": "#66cccc",
  	"brightWhite": "#ffffff",
  	"background": "#2d2d2d",
  	"foreground": "#cccccc"
}
```

Here is the result 
![82693215-69dbe180-9c61-11ea-83aa-ca227a404540](https://user-images.githubusercontent.com/34555572/82705833-b1ba3300-9c78-11ea-8611-1baa7e78b373.png)

**Comment by j4james** [comment]
The problem with this color scheme is that the dark and bright colors are identical. This will inevitably result in situations where text is difficult to see, or even completely invisible. It may be fine for your personal usage, but if we're going to include a color scheme in the app by default, there is an expectation that it's going to work reasonably well for all users. Otherwise it's just going to become another source of bug reports.

**Comment by MarcoBarna** [comment]
> The problem with this color scheme is that the dark and bright colors are identical. This will inevitably result in situations where text is difficult to see, or even completely invisible. It may be fine for your personal usage, but if we're going to include a color scheme in the app by default, there is an expectation that it's going to work reasonably well for all users. Otherwise it's just going to become another source of bug reports.

Make sense. What about a marketplace like in the settings interface? Something like vscode but for the terminal. In this way it would be fairly easily for everyone and you could also have a sync option?

**Comment by j4james** [comment]
> Make sense. What about a marketplace like in the settings interface?

Yeah, I believe something like that is in the long term plans. See issue #4000 (that's mostly about plugin extensions, but I think it should cover themes and color schemes too).

**Comment by zadjii-msft** [comment]
Huh, the bot never tagged this with "Needs-Triage", so this got lost. Sorry about that!

@j4james is right - I think the more long-term solution here is we'll have a better story for sharing schemes, themes, and extensions, similar to how VsCode does it. That's still a while off, though we are starting to lay down some foundations in 2.0.

As far as this particular issue is concerned - I think I'm gonna close this mostly based on the fact that this scheme would suffer the same problems that have plagued us with Solarized. If people want it, they're free to add it manually. 

Thanks!
