### ISSUE TITLE
The Windows Terminal task list could lists the latest folders open from the Command prompt

### ISSUE THREAD

**Issue by noeldev** [microsoft/terminal#6149]
# Description of the new feature/enhancement
I think that it would be handy if the Windows Terminal did list the latest folders that were open.

One could click any folder in the task list to open Windows Terminal from the taskbar and have the clicked folder selected right-away, without any CD.

# Proposed technical implementation details (optional)

It's just a suggestion but if you can implement it, it would be very handy for me and hopefully for other users.

**Comment by zadjii-msft** [comment]
So, getting the working directory of another process on Windows is tricky business. You'll want to see [this thread](https://github.com/microsoft/terminal/issues/3158#issuecomment-628628120) for _why_.

We do have plans for adding your profiles to the taskbar jumplist - see #576 and #5350 for more details. @noeldev do you think that would work for your use case?

**Comment by noeldev** [comment]
Thanks for your reply. I ran a quick test and duplicated the **cmd** profile in _settings.json_: I changed the **guid**, **name** and **startingDirectory** strings and now I can open a tab with the folder I need by default. So if all the profiles can appear in the jumplist then it would do exactly what I need. Thanks.

**Comment by DHowett** [comment]
Thanks for following up!
