### ISSUE TITLE
Update PATH Environment Variable without restarting terminal

### ISSUE THREAD

**Issue by JoshHenryJC** [microsoft/terminal#6154]
# Description of the new feature/enhancement

Whenever something new is added to the path environment variable, the user has to close/re-open terminal for it to update. It would be a convenient feature if this change could be detected and updated without restarting the application.

# Proposed technical implementation details

I believe this is could be roughly accomplished with the following steps

- Listen to the WM_SETTINGCHANGE message. 

- Grab the path from registry @HKEY_CURRENT_USER\Environment && 
@HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment 

- Grab the local PATH with getenv_s() / GetEnvironmentVariable()

- Check for changes between the two

- If changes are detected, update the local PATH with the new values with _putenv_s() / SetEnvironmentVariable()

- Reflect these changes in each PowerShell or Command Prompt tab with Get/SetEnvironmentVariable() calls in each child process

I am fairly inexperienced with C++, but would like to attempt this implementation myself if the idea well recieved

**Comment by DHowett** [comment]
Thanks @JoshHenryJC! I would love to see an implementation of this. We're already tracking it in /dup #1125 -- if you want to work on it, feel free!

**Comment by DHowett** [comment]
There's some work to be done to plumb the window message down from IslandWindow/BaseWindow/AppHost (WindowsTerminal C++ project) into the Application layer (TerminalAppLib C++ Project)

**Comment by JoshHenryJC** [comment]
@DHowett Thanks for the reply, I will take a look over at the original issue and see what I can come up with!
