### ISSUE TITLE
Can't send SIGQUIT ( crtl + \ ) to WSL (Debian)

### ISSUE THREAD

**Issue by zimbobway** [microsoft/terminal#6156]
# Environment

 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal
Version: 1.0.1401.0

Debian running on WSL
uname -r
4.4.0-18362-Microsoft

Related info:
https://github.com/microsoft/WSL/issues/169

# Steps to reproduce

Run Terminal
Open new Debian Window
run ping 127.0.0.1
(wait for 3 ping responses)
send SIGQUIT ( crtl + \ )

# Expected behavior

Ping statistics summary is displayed, while ping command continues. For instance:

PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.188 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.033 ms
3/3 packets, 0% loss, min/avg/ewma/max = 0.028/0.083/0.046/0.188 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.032 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.030 ms

# Actual behavior

^\ is printed at the beginning of next ping sequence line and no statistics summary is displayed, ping command continues. For instance:

PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=128 time=0.084 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=128 time=0.100 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=128 time=0.106 ms
^\64 bytes from 127.0.0.1: icmp_seq=4 ttl=128 time=0.108 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=128 time=0.107 ms

**Comment by int3l** [comment]
Maybe this is more related to WSL itself or there is problem between WSL and Windows Terminal, because I can send `Ctrl + \` to my RPi via ssh inside Cygwin that is started as a Windows Terminal tab.

**Comment by zimbobway** [comment]
> Maybe this is more related to WSL itself or there is problem between WSL and Windows Terminal, because I can send `Ctrl + \` to my RPi via ssh inside Cygwin that is started as a Windows Terminal tab.

I agree, when I utilize SSH to connect to another machine, `Ctrl + \` is passed successfully to the remote machine. However, based on this discussion https://github.com/microsoft/WSL/issues/169, the WSL team seems to believe this is an issue with terminal still.

**Comment by DHowett** [comment]
The problem is, though... that we can _definitely_ pass `^\` on to WSL. They're not handling it properly.

At the heart of the issue is the mismatch between signals on Windows and everywhere else. Terminal/Console _do not own the tty layer_, and we don't own WSL's signal model either. There's nothing we can do but faithfully send the `^\` along. :smile:
