### ISSUE TITLE
Add keyboard shortcuts for running a commands in windows terminal

### ISSUE THREAD

**Issue by topzdev** [microsoft/terminal#6158]
# Description of the new feature/enhancement

Im tired of typing a long syntax to open a multiple split-pane in windows terminal for example:

in my daily dev i always type this long command "wt split-pane  -p "Bash" -d . ; split-pane -p "Bash" -d . -V; split-pane -p "Postgres" -d  . -V;"  just to open windows termnial with 3 split pane. its pain in the ass to this method instead of this i propose to add a command line in keybindings so that its easy to lunch a windows terminal with a few clicks just click ctrl-shift-m to run that command line 
 
# Proposed technical implementation details (optional)

```
 "keybindings": [
{"commandLine": "wt split-pane  -p \"Bash\" -d . ; split-pane -p \"Bash\" -d . -V; split-pane -p \"Postgres\" -d  . -V;", "keys":"ctrl+shift+m"}
// other settings here...
]
```

Typing that key bindings it let run the command line to windows terminal and launch the thing you want to run. I hope this kind of feature added to the future updates. Thank you in advance microsoft dev! more coffee to come!

**Comment by j4james** [comment]
This would probably be covered by issue #3799 and/or #2046.

**Comment by DHowett** [comment]
Yep, both of those cover this. One would run commands _inside_ the terminal, and one would run _terminal commands_. /dup #3799 #2046.

This is also tied to #5970 (one action runs multiple actions)

**Comment by DHowett** [comment]
When 5970 lands, you'll be able to specify one action that runs multiple actions.

Mapping:

```
+----------+      +---------+       +---------+
|          +----->+         +<------+         |
| Command- |      | ACTIONS |       | Key     |
| line     +----->+         +<------+ Bidings |
| Args     |      |         |       |         |
|          +----->+         +<------+         |
+----------+      +---------+       +---------+
```
