### ISSUE TITLE
Slowdown when typing fast or pasting

### ISSUE THREAD

**Issue by Cappuchino** [microsoft/terminal#6163]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
None, not even using a remote SSH session.
```

# Steps to reproduce
Go to PowerShell or Command Prompt and type quickly, or mash the keyboard, or paste a line

# Expected behavior
Terminal quickly catches up, and displays the characters in time

# Actual behavior
Terminal slows down, and tries to slowly catch up to what you were trying to type

**Comment by john-h-k** [comment]
what hardware? i am on an i3 and with my most aggressive key smashing i can't repo

**Comment by bhishmapitamah** [comment]
I am using an i7 and I found this issue when using [Retro](https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/retro-command-prompt) (Experimental). The default profiles are fine and the Integrated GPU usage is below 5%. But using retro profile shoots up the usage up to 70% and there is some noticeable delay when typing.

**Comment by DHowett** [comment]
Retro will definitely do that.

@Cappuchino sorry about the slow response here. What sort of hardware are you running on?
