### ISSUE TITLE
Add profiles to taskbar jump list for Terminal

### ISSUE THREAD

**Issue by mave-panda** [microsoft/terminal#6165]
# Description of the new feature/enhancement
It would be great if the jump list supported/listed all the configured and detected profiles available in the tab dropdown

User would then be able to right-click/swipe-up and be able to open a new Terminal session for the desired shell.

**Comment by Eli-1961** [comment]
I had this problem with Ubuntu profiles. Discovered it was not Windows Terminal profiles, but my .bashrc file which turns debian PS1 env variable as the terminal title. Commented this out and all new profiles were displayed.

**Comment by mave-panda** [comment]
> I had this problem with Ubuntu profiles. Discovered it was not Windows Terminal profiles, but my .bashrc file which turns debian PS1 env variable as the terminal title. Commented this out and all new profiles were displayed.  

Not an issue but rather a feature request.

**Comment by j4james** [comment]
This sounds like a duplicate of issue #576.

**Comment by mave-panda** [comment]
> This sounds like a duplicate of issue #576.

Oh yes! Thanks for the link!
