### ISSUE TITLE
The default value of 'startingDirectory' setting  does not work properly

### ISSUE THREAD

**Issue by john-guo** [microsoft/terminal#6166]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

Windows Terminal
Version: 1.0.1401.0

Any other software?

Visual studio 2019
```

# Steps to reproduce

I added  a new profile visual studio developer command prompt:

            "name": "Visual Studio 2019",

            "icon": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\Assets\\VisualStudio.70x70.contrast-standard_scale-80.png",

            "commandline": "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\VsDevCmd.bat\""

As the document, the starting directory will be the %USERPROFILE% if the 'startingDirectory' setting is omitted.

# Expected behavior

The profile should start in the %USERPROFILE%.

# Actual behavior

The profile starts in C:\windows\system32

![批注 2020-05-24 103847](https://user-images.githubusercontent.com/7485003/82744417-d0204b80-9daa-11ea-9337-d94a294cc252.png)

When I set the 'startingDirectory'  to %USERPROFILE% explicitly, the profile starts in the correct directory.
            
            "name": "Visual Studio 2019",

            "icon": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\Assets\\VisualStudio.70x70.contrast-standard_scale-80.png",

            "commandline": "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\VsDevCmd.bat\"",

            "startingDirectory": "%USERPROFILE%"

**Comment by DHowett** [comment]
Sorry, looks like this is a documentation bug. @cinnamon-msft FYI

**Comment by cinnamon-msft** [comment]
Closing in favor of https://github.com/MicrosoftDocs/terminal/issues/53 on our docs site. Thanks!
