### ISSUE TITLE
Windows Terminal does not remember its last window position and size.

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6167]
Hello,
Windows Terminal does not remember its last window position and size.
![Windows Terminal](https://user-images.githubusercontent.com/23485114/82744649-a9edb200-9d90-11ea-8e91-d4ca1164eb5a.gif)
Please fix this issue.
Thanks

**Comment by j4james** [comment]
I think this is covered by issue #766. See also https://github.com/microsoft/terminal/issues/5858#issuecomment-627347667.

**Comment by DHowett** [comment]
It is! Thanks. /dup #766.
