### ISSUE TITLE
I found a text error on an article page

### ISSUE THREAD

**Issue by CharlesPMaxwell** [microsoft/terminal#6170]
I found a text error on an article page written by you in the "**Contributors Who Open the Most Non-Duplicate Issues**" section of the first contributor "Qantex", but changed the name to "Avdax" a few days ago.

1.  [ https://github.com/microsoft/terminal/issues/5245#issuecomment-609961617](https://github.com/microsoft/terminal/issues/5245#issuecomment-609961617)
2. Link: **https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-11-release/**
![](https://user-images.githubusercontent.com/65843794/82747262-811ceb00-9d97-11ea-9f30-1a5380daeeea.png)

The article was written by

**Comment by DHowett** [comment]
We are not going to update old blog posts because somebody changed his name after the blog post was released. Sorry.

**Comment by DHowett** [comment]
Thanks for the report! :smile:

**Comment by CharlesPMaxwell** [comment]
It's okay but what is about j4james

**Comment by CharlesPMaxwell** [comment]
Oh, my bad. I'm sorry.

**Comment by DHowett** [comment]
(Sorry that I was curt!)

**Comment by CharlesPMaxwell** [comment]
That's not a problem! :)
