### ISSUE TITLE
Default target directory should be current working directory, same as "cmd"

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [microsoft/terminal#6171]
Default target directory should be current working directory, same as __cmd__. Currently when opened from other __terminal__ or from __explorer__ its target directory is default home directory of current user.

## This is how "cmd" behaves
![Screenshot (20)](https://user-images.githubusercontent.com/46624268/82749671-3fef0000-9dc4-11ea-99f3-413879dba61f.png)
![Screenshot (21)](https://user-images.githubusercontent.com/46624268/82749674-441b1d80-9dc4-11ea-8815-a8f43d9dfd88.png)

## This is how "terminal" behaves
![Screenshot (22)](https://user-images.githubusercontent.com/46624268/82749729-aaa03b80-9dc4-11ea-8cb2-0f2a00ac8311.png)
![Screenshot (23)](https://user-images.githubusercontent.com/46624268/82749715-92c8b780-9dc4-11ea-81c2-37f021f17847.png)

Have to pass command line arguments to achieve same behavior, `wt -d .`. It would be great to have it behave like __cmd__.

**Comment by j4james** [comment]
This issue has been raised before. I believe `wt -d .` is the recommended way to make this work. See issue https://github.com/microsoft/terminal/issues/878#issuecomment-579508860.

**Comment by muhammad-usman-anwar** [comment]
I know this and mentioned it myself. But It would be great if it does automatically.

**Comment by j4james** [comment]
Yeah, I'm just telling you that what you're doing is the recommended approach. This issue has been raised many times before, and the answer is always that you need to use the method you're already using. See #4287, #4330, #4647, #4787, #4936, #5220, #5796, #6031, and #6132.

**Comment by zadjii-msft** [comment]
Yea, I think I'm going to resolve this one as a dupe. Thanks for triaging @j4james!

/dup #878, #4287, #4330, #4647, #4787, #4936, #5220, #5796, #6031, and #6132.
