### ISSUE TITLE
Scrolling and clicking adds unwanted characters in Vim

### ISSUE THREAD

**Issue by ayushg-bst** [microsoft/terminal#6172]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):1.0.1401.0

Any other software?
```

# Steps to reproduce

I use ssh to login into my work machine which is Linux. I then proceed to open a file with Vim. When I try to scroll around, it  automatically enters insert mode and adds a bunch of characters. 

# Expected behavior

Clicking normally should let me select text and scrolling should not insert text

# Actual behavior

![image](https://user-images.githubusercontent.com/60141064/82751416-ab40ce00-9dd4-11ea-9192-5dba2318fa2e.png)

**Comment by zadjii-msft** [comment]
@ayushg-bst Which version of ssh are you using? Are you using `ssh` from within WSL, or the default `ssh.exe` that ships with Windows?

**Comment by lebe-dev** [comment]
The same issue i have when clicking in Midnight Commander.
![2020-05-27_10-08-05](https://user-images.githubusercontent.com/9587482/82988544-03104c80-a002-11ea-8caa-8fdb9d50e177.png)

I'm using default Windows client, without WSL:

```
ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

With WSL it works as expected.
