### ISSUE TITLE
Unable to install Windows terminal

### ISSUE THREAD

**Issue by HounD** [microsoft/terminal#6174]
Hello!
I failed to install Windows terminal both downloading it from github page and installing with winget tool.

For the dowloaded file I got such output:
PS C:\Users\localuser\Downloads> add-appxpackage Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle
add-appxpackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
error 0x8007007B: Opening the package from location Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle failed.
NOTE: For additional information, look for [ActivityId] 3736654a-298c-0004-6cc8-4f378c29d601 in the Event Log or use the command line Get-AppxLog -ActivityID 3736654a-298c-0004-6cc8-4f378c29d601
At line:1 char:1
+ add-appxpackage Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.ms ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\localu...bbwe.msixbundle:String) [Add-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\localuser\Downloads> Get-AppxLog -ActivityID 3736654a-298c-0004-6cc8-4f378c29d601

Time                      ID           Message
----                      --           -------
5/24/2020 2:36:42 PM      603          Started deployment Add operation on a package with main parameter: Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle and Options: 0 and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
5/24/2020 2:36:42 PM      164          The app bundle signature was validated for core content of the app bundle published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond,
                                       S=Washington, C=US. App packages won't be validated until they are read.
5/24/2020 2:36:42 PM      216          App manifest validation warning: Declared namespace http://schemas.microsoft.com/appx/2018/bundle is inapplicable, it will be ignored during manifest
                                       processing.
5/24/2020 2:36:42 PM      216          App manifest validation warning: Declared namespace http://schemas.microsoft.com/appx/2019/bundle is inapplicable, it will be ignored during manifest
                                       processing.
5/24/2020 2:36:42 PM      465          error 0x8007007B: Opening the package from location Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle failed.
5/24/2020 2:36:42 PM      403          error 0x8007007B: Failure to get staging session for: file:///C:/Users/localuser/Downloads/Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle.
5/24/2020 2:36:42 PM      404          AppX Deployment operation failed for package  with error 0x80073CF0. The specific error text for this failure is: error 0x8007007B: Opening the package from
                                       location Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle failed.

For winget tool:
PS C:\Users\localuser\Downloads> winget install "Windows Terminal"
Found Windows Terminal [Microsoft.WindowsTerminal]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/microsoft/terminal/releases/download/v1.0.1401.0/Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle
  ██████████████████████████████  18.1 MB / 18.1 MB
Successfully verified installer hash
Starting package install...
Install failed: error 0x8007007B: Opening the package from location Microsoft.WindowsTerminal.1.0.1401.0 failed.
0x8007007b : The filename, directory name, or volume label syntax is incorrect.

In the both cases I was unable to install

**Comment by darkRaspberry** [comment]
try installing from microsoft store

**Comment by zadjii-msft** [comment]
That's certainly curious. `0x8007007B` is 

ERROR_INVALID_NAME | The filename, directory name, or volume label syntax is incorrect.
-- | --

Which doesn't totally make sense for this, but I don't know too much about how appx deployment works.

@HounD Which version of windows are you running?

**Comment by HounD** [comment]
> That's certainly curious. `0x8007007B` is
> 
> ERROR_INVALID_NAME	The filename, directory name, or volume label syntax is incorrect.
> Which doesn't totally make sense for this, but I don't know too much about how appx deployment works.
> 
> @HounD Which version of windows are you running?

C:\Users\localuser>systeminfo | findstr Build
OS Version:                10.0.17134 N/A Build 17134
OS Build Type:             Multiprocessor Free

**Comment by zadjii-msft** [comment]
Welp there you go. From the [README](https://github.com/microsoft/terminal#installing-and-running-windows-terminal):

> 👉 Note: Windows Terminal requires Windows 10 1903 (build 18362) or later

**Comment by douchecanoe** [comment]
This is still a problem. Running into it on 1909.

**Comment by Foadsf** [comment]
I have reported a similar issue [here](https://superuser.com/q/1601487/588662). Two reasons come to mind:

- I am using an old version of Windows that doesn't support MSIX 
- I don't have admin rights

Both issues could be solved if Microsoft would publish a portable `.exe` of the Windows Terminal as I have suggested in [this Tweet](https://twitter.com/fsfarimani/status/1326862105828581376?s=20).

**Comment by browolf** [comment]
I get this error on a 2016 server. I guess that's too old.
