### ISSUE TITLE
Setting not work

### ISSUE THREAD

**Issue by EthsonLiu** [microsoft/terminal#6177]
## Environment

```none
C:\Users\liuyi>ver

Microsoft Windows [版本 10.0.18362.836]
```

Windows Terminal version: 1.0.1401.0

## Problem

![Snipaste_2020-05-25_09-48-11](https://user-images.githubusercontent.com/33995130/82770902-de36a080-9e6c-11ea-947e-3879497f44c7.png)

I saved the setting.json file after add theme config, and restart the terminal, but still not work. What's wrong? Below is setting.json content,

```none
// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": true,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "命令提示符",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [{
        "name": "Builtin Solarized Light",
        "black": "#073642",
        "red": "#dc322f",
        "green": "#859900",
        "yellow": "#b58900",
        "blue": "#268bd2",
        "purple": "#d33682",
        "cyan": "#2aa198",
        "white": "#eee8d5",
        "brightBlack": "#002b36",
        "brightRed": "#cb4b16",
        "brightGreen": "#586e75",
        "brightYellow": "#657b83",
        "brightBlue": "#839496",
        "brightPurple": "#6c71c4",
        "brightCyan": "#93a1a1",
        "brightWhite": "#fdf6e3",
        "background": "#fdf6e3",
        "foreground": "#657b83"
      }],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}
```

If you need any other infos, I'll paste here. Thanks in advance.

**Comment by mdtauk** [comment]
You have added a scheme to the list of colour schemes, but you need to set the profile's scheme to the one you have added.

```"colorScheme": "Builtin Solarized Light"```

**Comment by EthsonLiu** [comment]
@mdtauk Yes, you are right,

```none
"profiles":
    {
        "defaults":
        {
            "colorScheme": "Builtin Solarized Light"
            // Put settings here that you want to apply to all profiles.
        },
......
```

Thanks a lot.

**Comment by helloworld10010** [comment]
i add some code to `defaults` as same as above. why still not work...

**Comment by helloworld10010** [comment]
i add some code to defaults as same as above. why still not work...  not support powershell?

**Comment by EthsonLiu** [comment]
@helloworld10010 You should post code here.

**Comment by helloworld10010** [comment]
> @helloworld10010 You should post code and terminal version here.

Same as yours.
`Microsoft Windows [version 10.0.18362.836]`
`
Windows Terminal
版本: 1.0.1401.0
`
settings.json
`
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
	"theme": "light",
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
			"colorScheme": "TangoDark"
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": true,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl"
            }
        ]
    },

    // Add custom color schemes to this array
    "schemes": [{
            "name": "TangoDark",
            "foreground": "#D3D7CF",
            "background": "#000000",
            "cursorColor": "#FFFFFF",
            "black": "#000000",
            "red": "#CC0000",
            "green": "#4E9A06",
            "yellow": "#C4A000",
            "blue": "#3465A4",
            "purple": "#75507B",
            "cyan": "#06989A",
            "white": "#D3D7CF",
            "brightBlack": "#555753",
            "brightRed": "#EF2929",
            "brightGreen": "#8AE234",
            "brightYellow": "#FCE94F",
            "brightBlue": "#729FCF",
            "brightPurple": "#AD7FA8",
            "brightCyan": "#34E2E2",
            "brightWhite": "#EEEEEC"
        }],
	

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
`

**Comment by EthsonLiu** [comment]
@helloworld10010 Terminal give en error? If so, copy them here.

**Comment by helloworld10010** [comment]
> @helloworld10010 Terminal given en error? If so, pls paste them here.

没任何输出

**Comment by helloworld10010** [comment]
这文档上配图好像都是ubuntu的，难道

**Comment by Jacky527** [comment]
![error](https://user-images.githubusercontent.com/49858286/83330047-5b27a700-a2bf-11ea-949f-9b2dd8aafaa8.png)

Windows Terminal Version: 1.0.1401.0

**Comment by siriuscc** [comment]
I use Windows Terminal with verson: 1.0.1401.0, and my set of colorScheme  no work.

there is 
```json
    "profiles": {
        "defaults": {
            "fontFace": "Consolas",
            "fontSize": 14,
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "historySize": 9001,
            "padding": "0, 0, 0, 0"
            
        },
        "list": [
            {
                "guid": "{261416fa-a3b1-11ea-bb37-0242ac130002}",
                "commandline": "ssh admin@172.11.12.13 -p33000",
                "name": "dev-213",
                "colorScheme": "Monokai Night",
                "cursorColor": "#FFFFFF",
                "fontSize": 14,
                "icon": "ms-appdata:///Local/icon/dev.png"
            },
```

and sheme:

```json
        {
            "name": "Monokai Night",
            "background": "#1f1f1f",
            "foreground": "#f8f8f8",
            "black": "#1f1f1f",
            "blue": "#6699df",
            "cyan": "#e69f66",
            "green": "#a6e22e",
            "purple": "#ae81ff",
            "red": "#f92672",
            "white": "#f8f8f2",
            "yellow": "#e6db74",
            "brightBlack": "#75715e",
            "brightBlue": "#66d9ef",
            "brightCyan": "#e69f66",
            "brightGreen": "#a6e22e",
            "brightPurple": "#ae81ff",
            "brightRed": "#f92672",
            "brightWhite": "#f8f8f2",
            "brightYellow": "#e6db74"
        }
```

with  same scheme , is work ok on wsl, but not in openssh

It has some error on built-in openssh?
