### ISSUE TITLE
double click selections should work across wrapped lines

### ISSUE THREAD

**Issue by yellowtailfan** [microsoft/terminal#6178]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.836]
Windows Terminal version (if applicable): Version: 1.0.1401.0
"wordDelimiters":" \\()\"',;<>!@#%^&*|[]{}│",
```

# Steps to reproduce

1. Double click a long path or URL (the path was printed to console without any newlines inside the path)
2. If the path is displayed on a single line in Windows Terminal, then the whole path is selected
3. If the path wraps across to the next line, then only the part of the path on a single line in the window is selected

This can be easily reproduced by double clicking the same long path before and after resizing the window.

# Expected behavior

Double click selection should work across a wrapped line and should work the same regardless of window width and line wrap position.

Thanks for making Windows Terminal, it's really good!

**Comment by DHowett** [comment]
It looks like we never had a workitem for this. Thanks! Connecting it to #6106

**Comment by mailinglists35** [comment]
screen recording

ctrl-click does work correctly though and opens in default browser

https://user-images.githubusercontent.com/2054302/161968239-37bfd755-dd54-4dec-8973-75a82a23c788.mp4

**Comment by zadjii-msft** [comment]
This might just be #4009

**Comment by zadjii-msft** [comment]
Yea this is definitely /dup #4009
