### ISSUE TITLE
Glitched CLI when zooming then dezooming (Ctrl + a lot of time then Ctrl - a lot of time)

### ISSUE THREAD

**Issue by rblxploit** [microsoft/terminal#6179]
# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

First, you have to do Ctrl and + a lot of time to zoom (maybe for 5 seconds). Then do Ctrl - the same amount of time.

# Expected behavior

Go back to normal zoom
(The image here is what you will see if you haven't done the steps)

![](https://i.gyazo.com/05f687b4f9908f8ada82f8f433d5490c.png)

# Actual behavior

When you write your command, it's actually glitched.
Also, it works with all terminals, even Powershell and CMD.
Images:

![](https://i.gyazo.com/9dd3d5fc5953098cd216ea4043079608.png)

**Comment by skyline75489** [comment]
I got this. This is #5666  and #5450 .
