### ISSUE TITLE
How to solve the problem that could not install in windows 10 verison 1709 professional ？instead of update System verison

### ISSUE THREAD

**Issue by oozerone** [microsoft/Terminal#618]
How to solve the problem that could not install in windows 10 verison 1709 professional ？
![image](https://user-images.githubusercontent.com/39056515/57440506-b92fb980-727a-11e9-9fe5-81ee1595503c.png)

**Comment by ysc3839** [comment]
Please read README: https://github.com/microsoft/Terminal#prerequisites
> You must be running Windows 1903 (build >= 10.0.18362.0) or above in order to run Windows Terminal

**Comment by fcharlie** [comment]
Windows Terminal base **Xaml Islands** and **Not support 1709**

**Comment by broken-bytes** [comment]
There is no fix for this as the readme clearly states what build you need.
