### ISSUE TITLE
Wrong "client area" after switching displays with different DPI

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/terminal#6181]
# Environment

```none
Windows build number: 10.0.18363
Windows Terminal version (if applicable): 1.0.1041.0

Any other software? No
```

# Steps to reproduce

1. Connect the PC with remote desktop, using a laptop with **125% dpi** display.
2. Launch Terminal from remote desktop, and do some works that can exceed one screen.
3. Disconnect remote desktop, and login to the PC using **150% dpi** display.
4. Observe the text and _About_ window of Terminal.

# Expected behavior

Everything looks correct.

# Actual behavior

![image](https://user-images.githubusercontent.com/5644458/82783174-8ca00d00-9e90-11ea-94f4-962ad3fa7150.png)
About window displays at correct position.
Areas of text and gray background are incorrect.
The ratio is 125%:150% = 5:6

**Comment by DHowett** [comment]
Does this only happen when the about dialog is open while you change the scaling?

**Comment by huoyaoyuan** [comment]
> Does this only happen when the about dialog is open while you change the scaling?

No. The window is minimized then, and the about dialog is not open.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion.

/dup #2380
