### ISSUE TITLE
set tabTitle in commandline

### ISSUE THREAD

**Issue by dakom** [microsoft/terminal#6183]
The documentation states that a constant static title can be achieved, regardless of shell, by setting the `tabTitle` and `suppressApplicationTitle` settings in the profile blocks.

If `tabTitle` could be set as a commandline argument, then together with `suppressApplicationTitle` in the settings we could do something like this in a `open-workspace.bat`

```bat
@echo off
start /b wt.exe new-tab -d .\frontend --title "Frontend" ; new-tab -d .\backend --title "Backend"; new-tab -d .\types --title "Shared Types"
```

This would allow creating something like a workspace with nicely named tabs :)

I'm not sure what the short name should be since `-t` has meaning in other commands. Though since there's no conflict with `new-tab` I guess it's okay?

**Comment by zadjii-msft** [comment]
Oh huh, this is tracked in #4632, but looks like it never got it's own issue. Congratulations, this is now that issue.
