### ISSUE TITLE
SIGBREAK signal from keyboard not propagated by Windows Terminal

### ISSUE THREAD

**Issue by int3l** [microsoft/terminal#6185]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
1.0.1401.0

PowerShell Core:
7.0.1

PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

# Steps to reproduce

1. Open PowerShell or PowerShell Core in Windows Terminal
2. Simulate blocking behavior with Python command:
`python -c "import time; import threading; t = threading.Thread(None, lambda: time.sleep(9999)); t.start(); t.join()"`
3. Press keyboard shortcut `Ctrl+Break`

# Expected behavior

Terminated Python process

# Actual behavior

Python process is still running

# Additional notes:

I tried the same steps in pure PowerShell (powershell.exe)/PowerShell Core (pwsh.exe)/CMD (cmd.exe) - and the result is terminated Python process.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1119 for more discussion.

/dup #1119
