### ISSUE TITLE
Synchronize panes

### ISSUE THREAD

**Issue by piwy** [microsoft/terminal#6188]
Hi there 
I am glad to use your new terminal. Congrats !
I often use split panes and it would be awesome to integrate panes synchonization on/off feature.
When i connect on multiple ssh servers i  execute both commands on it.
Thanks !

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2634 for more discussion.

/dup #2634
