### ISSUE TITLE
Potential bug with IXON handling in WSL

### ISSUE THREAD

**Issue by srinathh** [microsoft/terminal#6189]
# Environment
WSL Ubuntu 20.04

# Steps to reproduce
1. Enter Raw Mode
2. Turn off IEXTEN behavior by using the IXON flag
3. Press Ctrl + V on 

Here is a small program in Go that demonstrates the issue
```go

package main

import (
	"bufio"
	"io"
	"os"
	"log"

	"golang.org/x/sys/unix"
)

func main() {

	termios, err := unix.IoctlGetTermios(unix.Stdin, unix.TCGETS)
	if err != nil {
		log.Fatalf("could not fetch console settings: %s", err)
	}

	termios.Lflag = termios.Lflag &^ unix.ICANON
	termios.Iflag = termios.Iflag &^ unix.IXON 

	if err := unix.IoctlSetTermios(unix.Stdin, unix.TCSETSF, termios); err != nil {
		log.Fatalf("could not set console settings: %s", err)
	}

	r := bufio.NewReader(os.Stdin)

	for {

		b, err := r.ReadByte()

		if err == io.EOF {
			break
		} else if err != nil {
			log.Fatalf("Error reading from Stdin: %s\n", err)
			os.Exit(1)
		}
		log.Printf("%d\n", b)
	}
}
```

# Expected behavior

Reading Ctrl + V key from keyboard should return 22. This is what happens in the default Ubuntu WSL terminal

# Actual behavior
Returns a whole bunch of characters as keypresses

**Comment by zadjii-msft** [comment]
This is probably because <kbd>Ctrl+V</kbd> is bound to `paste` by default for new settings files. You can remove that binding from your settings by just deleting that line from your `settings.json`. Then, the `^V` will get passed through to the commandline application as normal.
