### ISSUE TITLE
Terminal window does not close when `exit`

### ISSUE THREAD

**Issue by 0x00000FF** [microsoft/Terminal#619]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number: **10.0.18362.30**

* What you're doing and what's happening:
I entered a command `exit` when it has only one tab, however, terminal window didn't close but cursor stops on next line even `closeOnExit` setting was set to `true`.

* What's wrong / what should be happening instead:
Terminal window should be closed without any halt.

Here's my profile.json setting for cmd and powershell:
```
    {
      "guid": "{fe0bb3c3-1426-40e5-a184-d69962c867fb}",
      "name": "cmd",
      "colorscheme": "Campbell",
      "historySize": 9001,
      "snapOnInput": true,
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "commandline": "cmd.exe",
      "fontFace": "Consolas",
      "fontSize": 12,
      "acrylicOpacity": 0.75,
      "useAcrylic": true,
      "closeOnExit": true,
      "padding": "0, 0, 0, 0"
    },
    {
      "guid": "{6e94c9d7-1466-44df-b26d-af96672d85b2}",
      "name": "PowerShell",
      "background": "#012456",
      "colorscheme": "Campbell",
      "historySize": 9001,
      "snapOnInput": true,
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "commandline": "C:\\Program Files\\PowerShell\\6\\pwsh.exe",
      "fontFace": "Courier New",
      "fontSize": 12,
      "acrylicOpacity": 0.5,
      "useAcrylic": false,
      "closeOnExit": true,
      "padding": "0, 0, 0, 0"
    }
```

The terminal was built from commit `af7316c130059ba15fe16ff0d13608d956a2b449`.

**Comment by bef178** [comment]
#460

**Comment by 0x00000FF** [comment]
I've checked the comment that `MSFT:21268795`, understood and let me fix it.
