### ISSUE TITLE
Allow to configure panes/tabs which open at the application start in settings.json

### ISSUE THREAD

**Issue by smykhailov** [microsoft/terminal#6190]
# Description of the new feature/enhancement

Right now it is possible to define which panes/tabs will be opened when in command line args (e.g. `wt -p "Command Prompt" ; split-pane -p "Windows PowerShell" ; split-pane -H wsl.exe`). Would be great to be able to set the same values in the `settings.json`.
Why this is important, because if I'd like to create shortcut and pin it to taskbar or  start menu I have to create `.cmd` or `.ps1` file, create shortcut for it and pin it, in addition it is difficult to apply Windows Terminal icon to that shortcut (it is possible to add it manually to shortcut, but if it will be changed in the future, it has to be changed manually again).

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22multiple+profiles%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #756 for more discussion.

/dup #756
