### ISSUE TITLE
Feature Request：terminal can pass mouse click（left+right） to tmux（3.0 or later ）when use ssh

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/terminal#6196]
# Description of the new feature/enhancement

Tmux can accept mouse event，for example change pannel，show pop up the context menu
but，terminal can‘t work correctly when I use ssh，but it works fine in git bash（windows）

**Comment by DHowett** [comment]
This is a bug in SSH 7.7.

**Comment by xspeed1989** [comment]
> This is a bug in SSH 7.7.

OK，Thanks
I will try to update OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
