### ISSUE TITLE
Windows Terminal: Open terminal in current folder via single command

### ISSUE THREAD

**Issue by nphmuller** [microsoft/Terminal#620]
Currently I can open cmd and powershell in the current folder via typing `cmd` or `powershell` in the address bar of explorer (which opens via CTRL+D, so it's really neat and quick).

It would be great if this was also possible with the new Windows Terminal. But since it's a Windows Store app I can't find an easy way to add it to PATH. It also doesn't respect the current folder when opening. It always starts in the default folder (`C:\WINDOWS\system32` for cmd and `~` for Ubuntu).

It would be great if this was possible:
- Make it possible to add Windows Terminal to PATH.
- Open the command line in the current folder in Windows Terminal.

It would also be nice if it could be opened with a short command.
The executable currently is called `WindowsTerminal`. Would be nice if we could simply type something like `term`.

**Comment by joandrsn** [comment]
What happens if you use `wt.exe` ? 

https://github.com/microsoft/Terminal/blob/af7316c130059ba15fe16ff0d13608d956a2b449/src/cascadia/CascadiaPackage/Package.appxmanifest#L51

The alias should already launch a WindowsTerminal, but I'm not sure if it launches in the path that you specify

**Comment by lennylxx** [comment]
@joandrsn This is great, I didn't know. Thanks.

**Comment by nphmuller** [comment]
@joandrsn Thanks! It even launches in the current directory!

**Comment by RehanSaeed** [comment]
How do you pass a directory path to wt.exe:
```
wt.exe "C:\GitHub"
```

**Comment by CEbbinghaus** [comment]
Tried but Always opens in Default folder for both CMD and PowerShell.

I can open the WSL Ubuntu shell in the current folder with ubuntu run. but wt always opens in the default folder

**Comment by DHowett-MSFT** [comment]
Remove `startingDirectory` from your profiles.json.

**Comment by mstyura** [comment]
Hello @DHowett-MSFT,
is there a way to ask `Windows Terminal` open new tab in the same folder as current tab? I want the same behavior as exist on `Mac OS X`: https://apple.stackexchange.com/questions/178017/how-do-i-open-a-new-terminal-window-for-same-directory-as-the-current-window.
Thanks in advance!

**Comment by MikenTNT** [comment]
> Remove `startingDirectory` from your profiles.json.

@DHowett-MSFT, this doesn't work in the latest version 0.5.2661.0  :(

**Comment by ScientiaEtVeritas** [comment]
> Remove `startingDirectory` from your profiles.json.

For me, it doesn't work either :(

**Comment by zadjii-msft** [comment]
As of v0.5, that actually won't work any longer. You'll need to set `"startingDirectory": null` for this to work actually. That fix regressed unintentionally in #2515.

**Comment by MikenTNT** [comment]
> As of v0.5, that actually won't work any longer. You'll need to set `"startingDirectory": null` for this to work actually. That fix regressed unintentionally in #2515.

Thank you @zadjii-msft.

**Comment by itnavigate** [comment]
I'd also like to open new tabs in the current directory, and in V0.5.2681.0 `"startingDirectory": null` just takes me to "C:\WINDOWS\system32>"

**Comment by payambordbar** [comment]
> As of v0.5, that actually won't work any longer. You'll need to set `"startingDirectory": null` for this to work actually. That fix regressed unintentionally in #2515.

@zadjii-msft , this doesn't work in v0.5.2681.0

**Comment by mantasaudickas** [comment]
> As of v0.5, that actually won't work any longer. You'll need to set `"startingDirectory": null` for this to work actually. That fix regressed unintentionally in #2515.

Does not work with 0.5.2762.0 either..

**Comment by DHowett-MSFT** [comment]
To be clear, _removing `startingDirectory` instead of setting it to `null`_ isn’t a feature that’s coming back; we are looking at alternative approaches regarding when exactly to apply startingDirectory, but the setting will always be able to be suppressed by setting it to null.

**Comment by ozziepeeps** [comment]
> > As of v0.5, that actually won't work any longer. You'll need to set `"startingDirectory": null` for this to work actually. That fix regressed unintentionally in #2515.
> 
> Does not work with 0.5.2762.0 either..
> I have tried removing value, setting to null.. both does not change anything..

`"startingDirectory": null ` works for me - it needs to be put under a specific profile, rather than being a root-level element

**Comment by piotrpalek** [comment]
@DHowett-MSFT it seems to me that an approach of having settings in a config file (`startingDirectory`) which can be overriden by passing in command line params is pretty common in general. Maybe I'm not getting the issue here :)

**Comment by DHowett-MSFT** [comment]
If I recall the conversation from last month, it was:

Clearing the “startingDirectory” setting by deleting it from your user profile (in the specific case of the two or three default shipped profiles), instead of setting it to `null` to clear it, is not a feature that will be coming back.

#607 specifies that we will support command line arguments, one of which will be the starting directory override.

This seems to be in line with my understanding of your understanding of this conversation. :smile:

**Comment by torpederos** [comment]
For me setting "startingDirectory": "." does the job.

**Comment by carlinmack** [comment]
is there another issue for having the terminal default open to say  `"%USERPROFILE%"` but null if launched from windows explorer? the current behaviour is quite annoying

**Comment by VideoPlayerCode** [comment]
@carlinmack I don't think that's necessary.

- The Windows Terminal defaults to the user's home directory if you launch it via the Start menu shortcut or via typing "wt" in Win+R. Which means that if you use `"startingDirectory": "."` they still open in the user's home folder (`%USERPROFILE%`).
- If you launch wt from the Windows Explorer address bar, or via something like cmd.exe (or another shell) navigated to a certain folder, then the `"startingDirectory": "."`  will ensure that Windows Terminal opens in the directory you were in.

**Comment by kerams** [comment]
> The Windows Terminal defaults to the user's home directory if you launch it via the Start menu shortcut or via typing "wt" in Win+R. Which means that if you use "startingDirectory": "." they still open in the user's home folder (%USERPROFILE%).

It defaults to system32 in those case for me.

**Comment by charlyjose** [comment]
Thanks @torpederos 
 
"startingDirectory": "`.`"
"startingDirectory": "%`__`CD`__`%"

Checked. Both works fine for me. [My solution](https://github.com/charlyjose/wt).

@RickStrahl have written a good blog regarding this issue. [Check it out](https://weblog.west-wind.com/posts/2019/Sep/03/Programmatically-Opening-Windows-Terminal-in-a-Specific-Folder).

**Comment by George35mk** [comment]
In my case this worked.

```json
"profiles":
    {
        "defaults":
        {
            "startingDirectory": "."
        },
```

**Comment by AndeYashwanth** [comment]
```"startingDirectory": "."``` works but when I open terminal from search it defaults to system32. 
Is there any way to open in the user directory when the path is not specified?

**Comment by manishprivet** [comment]
> `"startingDirectory": "."` works but when I open terminal from search it defaults to system32.
> Is there any way to open in the user directory when the path is not specified?

I had the same problem. I fixed it by adding the following line at the end of my .bashrc file.

`if [ "$CURR_DIRECTORY" = "/mnt/c/WINDOWS/system32" ]; then
    cd ~
fi`

**Comment by engmrgh** [comment]
Solution of @manishprivet was great, except that In order to work properly, I have changed the `system32` to `System32`. It's a good idea to run `pwd` and copy the output.

**Comment by AndeYashwanth** [comment]
I found a workaround by adding "open terminal here" to right-click.

**step-1:-**
Remove the starting directory from the settings.json for all profiles.

**step-2:-**
Add the open terminal to right-click according to this post.
https://github.com/microsoft/terminal/issues/1060#issuecomment-497539461
I changed the 2nd registry value from ```@="%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wt.exe"``` to ```@="C:\Users\[your username]\AppData\Local\Microsoft\WindowsApps\wt.exe -d  ."```

**Behaviour after modifications:**
So whenever I open terminal using search/taskbar/shortcut it will open in my user folder.
Whenever I want to open the terminal using the explorer, I just right-click and select ```Windows terminal here``` option.

Note 1: Don't forget to add ```-d .``` at the end of the second registry value, otherwise, this will not work.

Note 2: Typing ```wt``` in explorer bar still doesn't work. You should still type ```wt -d .``` if you want to open terminal in the current folder using the "explorer bar".

**Comment by LauKT** [comment]
Just add 
```json
"startingDirectory": null
```

It works with wt V1.0 properly.

If you prefer making wt shown in **SHIFT-Menu** just like "Open PowerShell window here" or Open WSL options, 
 you can merge this registry file to your Registry.

```registry
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt]
@="Open Windows Terminal here"
"ShowBasedOnVelocityId"=dword:00639bc8
"Extended"=""

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt\command]
@="C:\\Users\\LKT\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe"

```

**Comment by connorjak** [comment]
Please note the `startingDirectory` parameter should go in this place in the JSON structure:

``` JSONC
{
    //...

    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            
            // Attempt to start in current directory
            // https://github.com/microsoft/terminal/issues/620
            "startingDirectory": "."
        }
    }
}
```

**Comment by nickraphael** [comment]
I'm yet to see a solution that will do the following:
1.  Allow me to select a default directory when I open Terminal from start menu.
2.  When running wt.exe from explorer window will open Terminal to that directory.

Is this possible?

**Comment by zadjii-msft** [comment]
From [my investigation](https://github.com/microsoft/terminal/issues/878#issuecomment-538511693), that wasn't something that was technically possible. 

If you want both to work, you'll need to use `wt -d .` in the explorer address bar. This will let launching the Terminal from the start menu and the run box work the same as before, and still let you open the Terminal in the CWD in explorer

**Comment by spookyuser** [comment]
@AndeYashwanth That works perfectly, thank you. Now I can have it open in my user directory from the taskbar and only open in the current directory when I right click 😎

**Comment by StJohn3D** [comment]
Thanks @29kartik approach 1 worked for me. I was able to get GitKraken to use a custom terminal command of `wt -d %d` so that now it's terminal shortcut launches WT at the current repo's directory. 💯

**Comment by franzwcom** [comment]
I've added this to open in this specific folder  
```ssh
 "startingDirectory": "C:\\webdev"
```

**Comment by kmantel** [comment]
This is my take on it via context menu shortcut: https://gist.github.com/kmantel/9cd6bf9f0fb25694a5b08119817281b7

**Comment by marcostack** [comment]
> > Remova `startingDirectory`do seu profiles.json.
> 
> Para mim, também não funciona :(

use: 
"profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "startingDirectory": "D:/Ws"

**Comment by kankri** [comment]
@nickraphael:
>I'm yet to see a solution that will do the following:
>
>   1. Allow me to select a default directory when I open Terminal from start menu.
>   2. When running wt.exe from explorer window will open Terminal to that directory.

Having this in `settings.json`:

```json
{
    "profiles": {
        "defaults": {
            "startingDirectory": "."
        }
    }
}
```

makes Windows Terminal start in the current directory for me when launched from Explorer location box, <kbd>win</kbd>+<kbd>r</kbd> or from other programs (VS Code etc.). However, when starting from Start menu, either by searching or navigating to the shortcut, it starts in `C:\WINDOWS\system32`.

To fix the Start menu issue, I pinned a shortcut to `wt.exe` to the Start menu (`where wt` tells its location), renamed the shortcut to my liking and then modified it to have:

    Start in: %USERPROFILE%

Now Windows Terminal starts in my home directory when launched from the Start menu.

It would be nice if Windows Terminal wouldn't change its directory by default to make it more transparent. There aren't many other programs which do that.

I'm also wondering if the shortcut to `wt.exe` could be made by the installer automatically.

**Comment by frankitox** [comment]
So, none of the above answers worked for my use case. What I'd like to do is open a new tab using `alt+shift+-` and keep the previous folder. I tried using `null`, `"."` and `"%__CD__%"` as values for `"startingDirectory"` in different places of the JSON. I'm using version `1.4.2652.0` of Windows Terminal Preview.

One nice solution would be to have a new option like `"keepCurrentDirectoryOnNewTab": true` or something like that. Other way that Kitty uses is having a special value called `current` when specifying the directory.

**Comment by zadjii-msft** [comment]
@frankitox You're probably interested in #3158 and the like 20 issues that are duped to that thread
![image](https://user-images.githubusercontent.com/18356694/96502609-a6fbce00-1217-11eb-8444-ef68c2f4640a.png)


There's been quite the discussion of why this is hard or nearly impossible to do correctly on windows.

**Comment by baddate** [comment]
VERSION: 1.3.2651.0

in my case it works.
```
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "startingDirectory": "."
        },
```

also, you can use `"startingDirectory": "%__CD__%"`

**Comment by odinson8** [comment]
> VERSION: 1.3.2651.0
> 
> in my case it works.
> 
> ```
>     "profiles":
>     {
>         "defaults":
>         {
>             // Put settings here that you want to apply to all profiles.
>             "startingDirectory": "."
>         },
> ```
> 
> also, you can use `"startingDirectory": "%__CD__%"`

This works like a charm!

**Comment by james-poulose** [comment]
I am probably very late to the party, but in Windows 10 Pro 20H2, you can just type `wt` in the address bar and it will do the trick.

**Comment by petref** [comment]
> How do you pass a directory path to wt.exe. Something like this:
> 
> ```
> wt.exe "C:\GitHub"
> ```

I don't know if you found -d and path

**Comment by Combo819** [comment]
```
wt -d .
```
works well in WSL2

**Comment by alexandremucci** [comment]
You can set up the starting directory using your preferred address, either globally or for a specific profile. To have a context menu to open it in the current folder, create and save a .reg file with the content below:

```

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\windowsterminal]
@="Windows Terminal Here"
[HKEY_CLASSES_ROOT\Directory\Background\shell\windowsterminal\command]
@="\"C:\\Users\\{USERNAME}\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe\" -d ."

```

Double click the saved file to add these entries to the registry.

**Comment by sekti92** [comment]
This is working on my laptop
```
"profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "startingDirectory" : "%USERPROFILE%"
        }
}
```

**Comment by viceice** [comment]
Does anybody know why `"startingDirectory": "."` in default profil is no longer working on 1.6.10571.0?

Also `wt nt` will open a new window instead of a new tab. 

clicking the `+` button to open a new tab also no longer reuses the startup directory of the first tab. 😕

**Comment by zadjii-msft** [comment]
> Does anybody know why `"startingDirectory": "."` in default profil is no longer working on 1.6.10571.0?
> 

Nope, you should probably file a new issue so we can follow up with you and figure out what's going on

> Also `wt nt` will open a new window instead of a new tab.
> 

That's how it has always worked - in 1.7 there's `windowingBehavior` and `--window <id>` to help control this.

> clicking the `+` button to open a new tab also no longer reuses the startup directory of the first tab. 😕

Pretty sure that's how it's always worked - it'll always use the `startingDirectory` of the default profile, and if your default profile's `startingDirectory` is `.`, then it'll use the directory the terminal was launched from.

**Comment by viceice** [comment]
> > Does anybody know why `"startingDirectory": "."` in default profil is no longer working on 1.6.10571.0?
> 
> Nope, you should probably file a new issue so we can follow up with you and figure out what's going on
> 
> > Also `wt nt` will open a new window instead of a new tab.
> 
> That's how it has always worked - in 1.7 there's `windowingBehavior` and `--window <id>` to help control this.
> 
> > clicking the `+` button to open a new tab also no longer reuses the startup directory of the first tab. 😕
> 
> Pretty sure that's how it's always worked - it'll always use the `startingDirectory` of the default profile, and if your default profile's `startingDirectory` is `.`, then it'll use the directory the terminal was launched from.

I'm using the context menu to open wt in a specific folder (using the entry generated by wt). That will open the first tab in that folder, but new tab will open in system32.

Before i used my own context menu entry:

```pwsh

**Comment by zadjii-msft** [comment]
Yep, that's exactly how it works. You might be interested in #8933

**Comment by kaaax0815** [comment]
> I had the same problem. I fixed it by adding the following line at the end of my .bashrc file.

@manishprivet Is this possible in windows?

**Comment by manishprivet** [comment]
> > I had the same problem. I fixed it by adding the following line at the end of my .bashrc file.
> 
> @manishprivet Is this possible in windows?

@kaaax0815 Yes this is for windows only

**Comment by kaaax0815** [comment]
> @kaaax0815 Yes this is for windows only

@manishprivet But bashrc would be wsl not native windows. Or where should I put it

**Comment by manishprivet** [comment]
> > @kaaax0815 Yes this is for windows only
> 
> @manishprivet But bashrc would be wsl not native windows. Or where should I put it

@kaaax0815 In the WSL's bashrc file actually

**Comment by kaaax0815** [comment]
@manishprivet the matter has resolved itself. I changed the cmd search shortcut to wt and this fixed the path problem

**Comment by KSneijders** [comment]
You can now just go to `settings -> profiles (Powershell / Command prompt)` And check the checkbox: 'Use parent process directory'

**Comment by rafapaulin** [comment]
@KSneijders unfortunately we do not have that on wsl :(

**Comment by rafapaulin** [comment]
actually we do, but it does not work

**Comment by rafapaulin** [comment]
power shell also does not work

**Comment by pratik0903** [comment]
> So, none of the above answers worked for my use case. What I'd like to do is open a new tab using `alt+shift+-` and keep the previous folder. I tried using `null`, `"."` and `"%__CD__%"` as values for `"startingDirectory"` in different places of the JSON. I'm using version `1.4.2652.0` of Windows Terminal Preview.
> 
> One nice solution would be to have a new option like `"keepCurrentDirectoryOnNewTab": true` or something like that. Other way (that Kitty uses) is having a special value called `current` when specifying the directory.

this worked for me:
1. in windows terminal, under default profile, add startingDirectory value to "."
2. if you are going with explorer, in the address bar type "wt" and it will open your default profile in that directory
3. for every profile add a value of "startingDirectory" to "."

**Comment by krlvm** [comment]
If anyone is looking for a solution without changing the startingDirectory, I have placed such a file in `%SystemRoot\System32` named `wtx.cmd`:
```batch
@ECHO off
wt -d .
exit /B !ERRORLEVEL!
```

**Comment by AEROGU** [comment]
> Remove `startingDirectory` from your profiles.json.

Thanks @DHowett-MSFT, I was making VSCode when pressing ctrl+ñ the external console `wt.exe` appears, because the integrated one has problems with UTF8 in windows and, when I did it, it always started in my %USERPROFILE%, your solution worked, now runs in my project directory.

For those who are interested, I used `wt --window 0 focus-tab` so that if I already have a WindowsTerminal window open, it will be raised instead of creating another instance.

**Comment by ErcinDedeoglu** [comment]
> You can now just go to `settings -> profiles (Powershell / Command prompt)`. And check the checkbox: 'Use parent process directory'
> 
> ![image](https://user-images.githubusercontent.com/32707500/121692065-fb65fd80-cac7-11eb-846a-99e2a73b1557.png)

thank you! this solution is the best solution. and still working

**Comment by sanayvarghese** [comment]
## Current directory in Windows terminal using explorer

You can open current directory in Windows terminal using explorer using 
`wt -d .`

**Comment by aesirot** [comment]
1.15.3465.0
 
 "wt -d ." doesnt work any more for me :-(

**Comment by jleaders** [comment]
Please add wt -d 
![image](https://user-images.githubusercontent.com/2430917/228442998-c7b1ce83-b4ec-4987-8eea-33f23105c9ba.png)

**Comment by zadjii-msft** [comment]
@jleaders the help text is understandably a little confusing in this particular case, because of the implicit `new-tab` subcommand that's used when no subcommand is provided explicitly. You'll note, `-d` is under `wt new-tab --help`

![image](https://user-images.githubusercontent.com/18356694/228525053-a9cb63f5-6fd5-4e2a-94be-8fcaa9266856.png)

It's just that CLI11 doesn't know how to wire the args for `new-tab` up to the help message for the root command's help text.

**Comment by filiSpinelli** [comment]
@nphmuller Referring to the first main discussion of thus topic, you can open a new terminal windows, placed in the current working folder, by typing "cmd" and press Enter in the url   ##bar.
![image](https://user-images.githubusercontent.com/119928321/229056976-f14129eb-9e1a-45ef-b130-d1c6f0fd3726.png)

**Comment by Qypol342** [comment]
solution `wt -d .`

**Comment by 6philipp9** [comment]
![Windows Terminal](https://github.com/microsoft/terminal/assets/158322221/943a960f-23aa-43df-b087-bc2b648d063a)
[ Settings : "Startup" → "standard terminal application" ] change this to windows terminal -> All Terminals open now in the Windows Terminal.

**Comment by candrapersada** [comment]
how to use `%USERPROFILE%` without `Use parent process directory` in start menu?

**Comment by chrisrodrigue** [comment]
The default behavior of `cmd.exe`, `powershell.exe`, and `pwsh.exe` is to start in the current directory when invoked from any shell or the File Explorer address bar, or to open in `%USERPROFILE%` when invoked elsewhere (such as Run or Start Menu shortcuts).

`wt.exe` deviates from this behavior. If you have the starting directory set to `.`,  it will still start in `C:\Windows\System32` when invoked from a shortcut or the Start Menu. Why?

For those frustrated by this, here's a script you can put on your PATH that works from any shell, File Explorer, or Run. 

`wtd` opens a normal window in the current directory.

`wtd a` opens an elevated window in the current directory.

wtd.cmd:
```cmd
@echo off
if "%1"=="a" (
    net session >nul 2>&1 || (
        powershell -c "start -v runas '%~f0'"
        exit
    )
)
wt -d .
```

**Comment by DHowett** [comment]
When you have Terminal set as your default console host, you can also just go back to launching `cmd`, `powershell` or `pwsh` directly from the file explorer address bar or whichever shell...

**Comment by chrisrodrigue** [comment]
> When you have Terminal set as your default console host, you can also just go back to launching `cmd`, `powershell` or `pwsh` directly from the file explorer address bar or whichever shell...

Yeah but all of those are more verbose than typing `wt`. 

Besides, how would you launch Git Bash? Users should be able to invoke their default console host in the current directory when calling `wt` from that directory in File Explorer. 

And it should never, ever default to opening in a system directory such as `System32`.
