### ISSUE TITLE
Command to open a new window

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/terminal#6200]
# The ability to bind a key to opening a new terminal window

Most terminal emulators let you create new windows with a shortcut.  For example, the macOS terminal uses command-N and Konsole uses command-shift-N to create a new window.  This is useful when you want to have independent sets of commands that can be hidden independently or made visible at the same time.  

At the moment, the only mechanism that I could discover for opening a new window was to relaunch the terminal from the start menu or clicking on the task bar and launching it.  I can run wt.exe from within the terminal, but I can't bind this to a shortcut key (unless I am missing something in the config).

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1051 for more discussion.

/dup  #1051

You could maybe hack around this with some keybinding like 
```json
        { "command": { "action": "newTab", "commandline":"wt.exe" }, "keys": [ "ctrl+shift+n" ] },
```

**Comment by davidchisnall** [comment]
Thanks.  I think GitHub's issue search is a bit broken at the moment.  I searched for a bunch of things including 'new window' and did not find #1051.
