### ISSUE TITLE
Drag and drop tabs between windows

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/terminal#6201]
# Drag and drop tabs between two windows

Currently, tabs can be dragged and dropped to reorder them, but they cannot be dragged between windows.  With other terminals, there are two useful variations of this behaviour:

 - Dragging a tab off a window to create a new window.
 - Dragging a tab into another window to dock it.

Neither of these currently work with the Windows terminal.

**Comment by electronic-dk** [comment]
It's in the works: https://github.com/microsoft/terminal/issues/1256

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
