### ISSUE TITLE
Windows terminal's light/dark window theme does not change automatically when changed in windows settings

### ISSUE THREAD

**Issue by public-void-code** [microsoft/terminal#6203]
# Environment

Windows build number: Microsoft Windows NT 10.0.19631.0
Windows Terminal version (if applicable): 1.0.1401.0

# Steps to reproduce 

1. open windows terminal, keep this open
2. in PowerShell(either in that terminal window or elsewhere) type `Start-Process -FilePath 'ms-settings:personalization-colors'` 
3. use the dropdown menu to change the value of the 'change your colour' option
4. notice that all the windows on your screen(setting, windows store apps, chromium Microsoft edge) change from a whatever light/dark theme they were set to, to its opposite. windows terminal does not.

# Expected behavior

I would expect that the light/dark theme of open windows terminal windows would change automatically when it is changed in the system settings.

# Actual behavior

Windows terminal will not change its light/dark theme automatically, instead for it to change you will have to close the window, clearing all session variables, and open a new window where the light/dark theme is as changed in system settings

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #1230 for more discussion.

/dup #1230
