### ISSUE TITLE
Not correct showing arabic words

### ISSUE THREAD

**Issue by PasaOpasen** [microsoft/terminal#6204]
So in windows terminal arabic/presian words (for example) like 'سلام' (hello) are showing reversed and in upper case!

It's like the word 'hello' will be showed like 'OLLEH'

**Comment by zadjii-msft** [comment]
Part of this probably depends on what shell you're using, but I think the bigger problem is that the Terminal doesn't currently support RTL languages pretty much at all. For more info, check out /duplicate #538
