### ISSUE TITLE
Provide manual refresh of settings.json or have refresh code follow symlinks

### ISSUE THREAD

**Issue by brianpepin** [microsoft/terminal#6209]
Provide a way to manually refresh Terminal's reading of settings.json or have the update sniff follow symbolic links.

I like to keep important state for my dev machine in a git repo so I can blow away the machine and easily recreate it if I need to.  I have settings.json living in this repo and I've created a symbolic link at the original location.  This all works fine.  But now if I change settings I need to close reopen terminal windows -- the changes are not automatically updated.  It would be great if there was a way to trigger a re-parse of settings, or have Terminal follow symbolic links and monitor their targets for changes (I couldn't use a hard link -- different drives).

# Proposed technical implementation details (optional)

Ideally the file change monitor for settings would detect if settings is using a symlink and monitor the target.  Less ideally, but probably useful in more situations is to have an option to reload settings manually.

**Comment by zadjii-msft** [comment]
So, there's a specific reason for this: https://github.com/microsoft/terminal/issues/1812#issuecomment-508280785

> 
> So, here's the weird thing about file modifications. We can't subscribe to know when a file has been changed -- we must subscribe to know when its _directory_ changed. The risk in following the symbolic link is that we will probably start listening for file changes in somewhere crazy (with a high event volume) like the user's home directory. ☹️

We do have #2933 tracking "allow importing settings from another file", so in that case you could probably opt-in to storing the settings in another location

I think this largely counts as /dup #1812
