### ISSUE TITLE
 CustomTextRenderer::_DrawGlowGlyphRun text is (sometimes) bold and smeared looking.

### ISSUE THREAD

**Issue by JamesG269** [microsoft/terminal#621]
Microsoft Windows [Version 10.0.18362.86]

Issue: Text rendering for CustomTextRenderer::_DrawGlowGlyphRun seems off.
I did the exact modifications as the dev (Mike) at the build conference to enable glowing text, which required uncommenting the line to call the function (and commenting the default text render call). I'm sorry if this is out of the scope of this issue tracker since it is not the default code, but I thought it should be included as glowing text makes the blurred background many times more usable, and well it seems off on my system.
The first image is the dev's system from the video on top and mine right beneath it, the second image is when I modified the function to draw random colors, to demonstrate that some colors are off (they look bolded and blurred) and others seem correct. Ideally I'm certain all of the colors should look something like Mike's did. I realize Mike was running regular conhost, but even in my pure open terminal window, you can see for instance the WinStore.App looks much better than most the others.

![terminal-text](https://user-images.githubusercontent.com/2309574/57452609-e0aa6600-7229-11e9-80ab-0e525cc6d176.png)
![terminal-text2](https://user-images.githubusercontent.com/2309574/57452657-fc157100-7229-11e9-979d-23703fd6d99d.jpg)

**Comment by zadjii-msft** [comment]
This is probably part of the reason why we haven't enabled it as an official setting yet :P

If anyone in the community wants to help polish the glowtext mode, I'd be happy to wire a setting up to it.

@miniksa for visibility

**Comment by Nacimota** [comment]
It's hard to tell from those screenshots, but it doesn't look like it's broken to me. It just looks like the lighter colours seem to have the effect of adding weight to a similarly light text colour, which makes sense.

**Comment by JamesG269** [comment]
@Nacimota But shouldn't the first screen's text be identical to the video capped one from the build conference demo (First pic, mine is below a screen shot from the build demo?)

**Comment by Nacimota** [comment]
Well possibly, if the code is identical. The red does look darker to me in the video though, and the font size is definitely larger which could make the glow effect present slightly differently. 🤷‍♂️

**Comment by JamesG269** [comment]
I think it's both of those things, but mostly the relation of darkness to brightness in the brush vs. the outline. I limited each of the RGB values to 0-128 in the outlinebrush, instead of 0-256:
![Untitled](https://user-images.githubusercontent.com/2309574/57465800-fb3e0880-7244-11e9-87c2-a99dd8c7f342.jpg)

**Comment by miniksa** [comment]
Please don't get too far on this one. I have some internal discussions that I had prior to Build on how to do glow text better than this sample. The folks who briefed me had great justifications on why this way of doing glow was not optimal, but I'll dig them up in the next week or so and get back to this.

**Comment by Psychlist1972** [comment]
I'd love to see glow working, so I can get that lovely classic monochrome VT terminal or color CRT aesthetic.

**Comment by zadjii-msft** [comment]
You know, with custom shaders (#7013), I don't think we really need to re-explore this. Let's just let folks do their own shader thing, that's been pretty dang flexible so far.
