### ISSUE TITLE
Please add acrylic:"false" to user json if it is not specified in a profile

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#6215]
# Description of the new feature/enhancement

Current version generates two settings json files. A baseline that may not be edited (ctrl+settings) and a user locale one that a user can edit. 
Both will have auto generated profiles for recognized products ex. PoSh 7, cmd etc. 
That's great. 

For all users that might not want to dig deep into all possible settings that a json can possibly hold it's not easy to understand without reading docs and knowing of the existence of the global settings json how to enable acrylic, one of the liked gimmicks of terminal. 

The reason is that in all profiles of the global json  have acrylic set to false by default. 

Again changing the default json isn't possible. 

Adding acrylic manually can be quite some work if one has many consoles installed. 

Adding this frequent option manually is prone to user errors when setting this up or copy and adding from the default json. Especially json formatting issues without using a proper editor like VSC. Not all might want to install VSC or other code aware editors as notepad++ but by default we have Microsoft Notepad (app). 

Currently the local user json is missing acrylic. 

# Proposed technical implementation details (optional)
 
While generating the user local json, parse for profiles that are missing the setting for acrylic. 

Add acrylic:"false", 

If it does exist in a profile don't touch.

This would ease the usage.

**Comment by zadjii-msft** [comment]
This is a bit of a slippery slope though - if we are okay adding `useAcrylic` and `acrylicOpacity`, then why aren't we okay adding all the `backgroundImage*` properties? Following this through to conclusion would lead to the default settings file we generate containing full lists of all the available properties, which is one of the things we're explicitly trying to _avoid_.

The right long-term solution for "easier settings management" is probably just the settings UI in #1564.

**Comment by Karl-WE** [comment]
I would be fine to add all of them. Why not, as long we don't have the GUI for this.

**Comment by zadjii-msft** [comment]
Yea, the full list was horribly unmanagable. It's overall been much easier on users to just include the settings that people want _changed_ in their settings. 

Since we're not about to start adding more settings to the default settings file, I'm gonna close this out. Thanks!

**Comment by DHowett** [comment]
@Karl-WE However, I recognize that you've been with us for quite a long time! The new "default" template settings file is a lot different from the one you got when you started with Terminal 0.1 or 0.2.

If you back up your settings and delete the file, you might have a nicer time. Some of the default bindings changed, which might catch you out. Scott Hanselman wrote up a blog post about [refreshing your settings](https://www.hanselman.com/blog/NowIsTheTimeToMakeAFreshNewWindowsTerminalProfilesjson.aspx), if you're interested.

**Comment by DHowett** [comment]
The new format also supports a defaults block that lets you set a setting once for _all_ profiles.

**Comment by Karl-WE** [comment]
@zadjii-msft @DHowett thanks for your taking time to explain. How about a last idea on this:
users that might have old settings jsons, might get a notification as explained by Dustin on the first start after an upgrade. This will ensure awareness and consistent expierence across the users. What do you think? If you agree I'll take the time for a new issue-feature.
