### ISSUE TITLE
pls add a graphical configuration interface

### ISSUE THREAD

**Issue by lorewalkerpan** [microsoft/terminal#6218]
pls add a graphical configuration interface.The "setting.json" profile is not easy to use by New
请添加图形化的配置界面,json文件配置一点也不友好

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22settings+UI%22+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1564 for more discussion.

/dup #1564
