### ISSUE TITLE
There should be an error dialog for incorrect settings instead of just crashing

### ISSUE THREAD

**Issue by ThomasAunvik** [microsoft/terminal#622]
Windows Build: 10.0.18362.86

Open Terminal.

Opened up settings, to profiles.json.

On a profile, for example cmd, added `"icon": %windir%\\system32\\cmd.exe`. Save.

On trying to focus on the terminal, it crashed. No errors. Almost instant crash.

Removed that line.

Tries to relaunch terminal, unable to launch it again.
Tried rebooting. Tried redeploying, did not work.

Edit: nvm, was just an extra comma in the end. It would launch again. But crashes when that exe is there.
i feel stupid for posting this issue without a second thought.

**Comment by zadjii-msft** [comment]
Yea there's no way for us to get an image from an .exe at this time.

I'd recommend trying a .png, .jpg, or any other image format :)

**Comment by zadjii-msft** [comment]
I am gonna take this issue as an opportunity to create a "there should be an error dialog for incorrect settings instead of just crashing" thread.

**Comment by ThomasAunvik** [comment]
Just noting, that the json files gets resaved as unformatted json when you use the app. Making it difficult to change your settings at the go.

**Comment by xa0082249956** [comment]
Windows Terminal crashed after I upgraded powershell-core from a old version to 7.0.0-preview.1.
This may because it cannot find the main shell. But I think it's better to "fall back" to cmd.
