### ISSUE TITLE
Unable to modify defaults.json

### ISSUE THREAD

**Issue by shakey1** [microsoft/terminal#6221]
# Environment

Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

# Steps to reproduce

Hold down the "alt" key and open settings.  The defaults.json file opens in Notepad (in my case Notepad++).  When I make changes though and try to save, I either get prompted to save the file with another name (when using Notepad) or told to "Please check if this file is opened in another program" when using Notepad++ (running in administrator mode).

# Expected behavior

To be able to change the settings to my liking (color schemes).

# Actual behavior

The file states that it is open in another program, but I have not been able to identify it.

![SaveFailed](https://user-images.githubusercontent.com/10562402/83041419-4e702e00-9ff5-11ea-9c9a-1d6521f06af5.PNG)

**Comment by zadjii-msft** [comment]
This is absolutely by design - `defaults.json` is a readonly reference file that merely shows the default settings for the Windows Terminal.
https://github.com/microsoft/terminal/blob/2af722b43d3213858df156cc42c47e12341b836a/src/cascadia/TerminalApp/defaults.json#L1



If you'd like to change your settings, you should just edit `settings.json`. You might also be interested in [this doc](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings)

>  If you'd like a setting to apply to all of your profiles, you can add it to the `defaults` section above the `list` of `profiles` in your `settings.json` file.

**Comment by willemavjc** [comment]
> If you'd like to change your settings, you should just edit `settings.json`. You might also be interested in [this doc](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings)
> 
> > If you'd like a setting to apply to all of your profiles, you can add it to the `defaults` section above the `list` of `profiles` in your `settings.json` file.

Seems to be no longer accurate: To get something working, I was forced to pass it to `profiles` property.

Example:
```
{
...
    "profiles":
    [
...
        {
            "guid": "...",
            "hidden": false,
            "name": "PowerShell",
            "source": "Windows.Terminal.PowershellCore",
            "fontFace": "JetBrains Mono",
            "fontSize": 10
        }
    ],
...
}
```

**Comment by DHowett** [comment]
I mean, if our settings model regressed that significantly between point releases I'm going to say _you should file a totally separate bug for it instead of commenting on the one about editing a read-only file :smile:_

Please share a copy of your settings.json when it's in the non-working state.

**Comment by willemavjc** [comment]
> I mean, if our settings model regressed that significantly between point releases I'm going to say _you should file a totally separate bug for it instead of commenting on the one about editing a read-only file

Oh right, I focused on `settings.json` (your response) and not on `defaults.json` (the question)

> Please share a copy of your settings.json when it's in the non-working state.

This does not work:
```
    "cursorShape": "filledBox",
    "fontFace": "JetBrains Mono",
    "fontSize": 10,
    "useAcrylic": true,
    "acrylicOpacity": 0.4,
    "profiles":
    [
       ...
```

While this works:
```
    "profiles":
    [
        {
            "guid": "{...}",
            "hidden": false,
            "name": "Debian",
            "source": "Windows.Terminal.Wsl",
            "cursorShape": "filledBox",
            "fontFace": "JetBrains Mono",
            "fontSize": 10,
            "useAcrylic": true,
            "acrylicOpacity": 0.4
        },
        ...
```

**Comment by KalleOlaviNiemitalo** [comment]
@willemavjc, the value of "profiles" should be an object with properties "defaults" and "list" as shown in [Profile settings in Windows Terminal](https://docs.microsoft.com/windows/terminal/customize-settings/profile-settings).
