### ISSUE TITLE
Cannot open Settings 1.0.1401.0

### ISSUE THREAD

**Issue by chandde** [microsoft/terminal#6225]
# Environment

```none
Windows Version: 10.0.18363.836
Windows Terminal Version: 1.0.1401.0
```

# Steps to reproduce

Install windows terminal from store
Open it
Open settings from menu or shortcut (Ctrl + ,), settings does not open either way. When opening from menu, there is a warning sound from speaker.

# Expected behavior

Settings can be opened.

# Actual behavior

Settings does not open

**Comment by DHowett** [comment]
It appears that you do not have a default file association for JSON files.

Can you check what application you have registered to open JSON files?

**Comment by chandde** [comment]
@DHowett thanks for the information, you were right that I don't have editor for json associated, once I did that, I was able to open the settings. Didn't realize it was to open a json file :)
