### ISSUE TITLE
Add ability in menu > above settings > reset / refresh settings

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#6230]
# Description of the new feature/enhancement

some users likely have very old json files (global / user local) that may cause unnecessary questions or usage concerns.

see #6215 #6216 

The root cause was that my json file was very very old and terminal (for good) does not simply upgrade / alter json files with a new version / update via Microsoft Store.

However a new file hits it with this new useful disclaimer in the user json.
My old one did not have this one yet, so I wasn't aware about so many dramatic changes as a casual user of Terminal for my Powershell and cmd.

```
// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.
```

# Proposed technical implementation details (optional)

If you see the drop down menu please add a new entry that is named like "refresh settings"

include a warning like:

Msgbox:
"Starting over can be a good choice to get easier access to new features and configurable settings"
**This will delete all your jsons on next restart of Terminal.** For a backup choose Settings before closing the terminal window."

Msgbox: Yes, delete config to latest defaults / Keep current

- place a trigger file for the yes decision, regenerate all jsons / delete lock files on next start

**Comment by zadjii-msft** [comment]
Hey so there's already  #947 which covers adding this button to the settings UI (#1564), when we eventually get around to the settings UI. I think that's probably a more appropriate place for this button, so I'm gonna close this issue as a dupe. Thanks!


/dup #947
