### ISSUE TITLE
Cheat Sheet for Windows Terminal key bindings

### ISSUE THREAD

**Issue by th0ger** [microsoft/terminal#6233]
# Description of the new feature/enhancement
The learning curve for the keyboard shortcuts is quite steep. This is a shame, especially because of low GUI (pointer) support.
I've created this [Windows Terminal Cheat Sheet](https://cheatography.com/martinthogersen/cheat-sheets/windows-terminal/)

# Proposed technical implementation details (optional)
Feel free to link to this cheat sheet in your docs or repo if you find it useful.

**Comment by Abezzam10** [comment]
> # Description of the new feature/enhancement
> The learning curve for the keyboard shortcuts is quite steep. This is a shame, especially because of low GUI (pointer) support.
> I've created this [Windows Terminal Cheat Sheet](https://cheatography.com/martinthogersen/cheat-sheets/windows-terminal/)
> 
> # Proposed technical implementation details (optional)
> Feel free to link to this cheat sheet in your docs or repo if you find it useful.

**Comment by WSLUser** [comment]
Somebody doesn't know how to check the project for documents: https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md

**Comment by th0ger** [comment]
@WSLUser u talkin to me? what's your point?

**Comment by Luuk34** [comment]
The option to move to a different pane is missing....

**Comment by WSLUser** [comment]
It seems straight forward to me. If you think the docs can be improved then submit a PR.

**Comment by th0ger** [comment]
Sure, I can do a PR. But first I prefer to get some acknowledgement from wt team that this is wanted and where.

**Comment by cinnamon-msft** [comment]
Hey @th0ger, this is awesome. 😊 Would you mind filing a PR on the [docs repo](https://github.com/MicrosoftDocs/terminal)? I think having a "key bindings quick guide" is a wonderful idea.

**Comment by DHowett** [comment]
WOW! This is so cool. It is much better fit for the docs repo as Kayla called out.

**Comment by th0ger** [comment]
Thanks. Yes I only realized later that the docs has it's own repo, will create the PR there.

**Comment by th0ger** [comment]
PR done.
