### ISSUE TITLE
Windows Clipboard Support

### ISSUE THREAD

**Issue by ShayekhBinIslam** [microsoft/terminal#6234]
# Description of the new feature/enhancement
⊞ Win + V allows paste previously copied items in the clipboard. It is not supported now.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22cloud+clipboard%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #322 for more discussion.

/dup #322 #4184
