### ISSUE TITLE
Error "The service has not been started" when running Windows Terminal

### ISSUE THREAD

**Issue by tofferb** [microsoft/terminal#6235]
# Environment

Microsoft Windows [Version 10.0.18362.778]

# Steps to reproduce

I installed Windows Terminal v1.0.1401.0 from the releases page https://github.com/microsoft/terminal/releases as my group policy does not allow me to install apps from the Microsoft Store.

# Expected behavior

Windows Terminal should start correctly

# Actual behavior

After installing Windows Terminal and trying to run it, I receive the following error:

```The service has not been started```

Opening event viewer, the following event is logged for Microsoft-Windows-AppModel-Runtime/Admin:

```0x80070426: Cannot create the process for package Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe because an error was encountered while preparing for activation. [LaunchProcess]```

And also this event:

```Failed with 0x490 modifying AppModel Runtime status for package Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe for user zzz (current status = 0x0, desired status = 0x20).```

**Comment by oising** [comment]
It's one thing to block the vector to install modern apps (the microsoft store), but it seems like your company's IT team have also disabled the parts of Windows that allow _launching_ store apps too. The releases page allow you to bypass the former, but the latter is something you'll have to talk to your company about.

**Comment by jeff-bb** [comment]
This is the result of  wlidsvc / Microsoft Account Sign-in Assistant not running or being disabled. Alternatively or in addition to that, the device does not have internet access or not internet access to login.live.com to acquire a store license. The app should be made available with an offline license to resolve this if you are unable to start the needed service or provide the needed internet access.

**Comment by tofferb** [comment]
@jeff-bb thanks for the advice. Starting the service now allows me to install it from the Store. Problem fixed! :)
