### ISSUE TITLE
Low FPS when terminal is front window

### ISSUE THREAD

**Issue by akfroman** [microsoft/terminal#6237]
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

Just having the terminal as the main window

# Expected behavior

Moving my mouse cursor and terminal window should be smooth with a 120hz monitor.

# Actual behavior

My mouse and terminal window move very slow and jittery. Like they're running at 15fps. The behavior stops when I select any other program.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+FPS+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #649 for more discussion.

/dup #649
