### ISSUE TITLE
WSL window does not remember last size/position

### ISSUE THREAD

**Issue by vanzod** [microsoft/terminal#6239]
# Environment

```
Windows build number: Version 10.0.18363 Build 18363
Windows Terminal version (if applicable): 

Any other software?
```

# Steps to reproduce
To reproduce:
1. Open a WSL screen
2. Modify screen position and size
3. Close the window (ensure it is the last WSL window closed)
4. Open a new WSL window. The position and size do not match the previously closed window.

# Expected behavior
The position/size of a new WSL window should be the same as the latest closed window, consistently with the standard Win 10 behavior.

# Actual behavior
When opening a new WSL window, the position and size does not reflect the position/size of the last closed window. The window is outside the screen, requiring a move/resize operation every time.

**Comment by zadjii-msft** [comment]
*shudders*

This was the first ever feature I ever worked on at Microsoft, nearly 5 years ago. We wanted to grant conhost this capability, but I screwed something up, and we ended up writing the registry on every single window movement. Only, I screwed it up worse, and forgot to free the reg key, so there was a horrible memory leak _every time the window moved_. 

So we backed it out, and never came back to it. 

At this point, we're not about to invest time into the vintage console anymore. There's #766 for tracking the same feature request on the Windows Terminal, so I'm going to close this as a dup of that one.

Thanks!

/dup #766
