### ISSUE TITLE
Windows terminal on linux

### ISSUE THREAD

**Issue by khalil2535** [microsoft/Terminal#624]
I have a feature request for this project.
Can this terminal work on Linux ?

PS : I am serious.

**Comment by Nacimota** [comment]
Unfortunately both the terminal and console rely on a fair bit of Windows specific infrastructure. It's not really possibly to build this project for Linux without porting or replacing all of that underlying tech, so it's not really on the cards.

Fortunately, there's no shortage of good terminals on Linux. :)

**Comment by zadjii-msft** [comment]
Seriously, search before opening a new issue. See #504, #563 for dupes.
