### ISSUE TITLE
Terminal does not play well with a G-Sync enabled monitor.

### ISSUE THREAD

**Issue by Joe-Pena** [microsoft/terminal#6240]
Microsoft Windows [Version 10.0.19041.264]
Terminal: 1.0.1401.0

I have an Nvidia RTX3000 card and a G-sync enabled monitor that has a refresh rate of 144Hz.

When going into the Nvidia control panel and enabling G-Sync, the terminal app has horrible frame rate, causing the monitor itself to dip down to 15-20 fps, as well as the cursor and anything around it, mind you, this only happens if WindowsTerminal is the program that is focused on at the moment.

Now, there's a very easy workaround for apps with this issue, where you exclude the Gsync functionality from running from one particular app, in this case, Windows Terminal, the issue I'm having though, revolves around not being able to find the location of the Windows Terminal executable. I know it's on the `\Program Files\WindowsApps` folder, however, I can only see one `WindowsTerminal.exe`, which when opened, opens up a new Terminal with default settings, however this one doesn't suffer from the performance issue, weird.

So, where is the location of the WindowsTerminal executable that gets ran from the shortcut that you click in the start menu, for example? Nvidia control panel cannot detect the application even if it's running, which doesn't happen with any other application on my pc, even if downloaded from the MS Store as well.

I imagine it has a different method of execution? For now, I'm disabling Gsync whenever I need to use the Terminal app, but it would be nice to not have to do that, which for now, all I need is the location of WindowsTerminal in the way it gets opened from the start menu.

Thanks!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+gsync) when filing new issues. This is already being tracked by another issue on our repo - please refer to #649 for more discussion.

/dup #649
