### ISSUE TITLE
Error of access level while saving default.json after trying to change color scheme

### ISSUE THREAD

**Issue by SlayerCult** [microsoft/terminal#6244]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
This appears at the top of defaults.json:

```jsonc
// THIS IS AN AUTO-GENERATED FILE! Changes to this file will be ignored.
```

defaults.json is not intended to be edited. You can set "default" settings in your own settings.json file by putting them in the `"defaults"` section.
