### ISSUE TITLE
Shell extension displays an error when you launch it from the root of a drive

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#6245]
![image](https://user-images.githubusercontent.com/189190/83201470-62ea1e80-a0fa-11ea-9ab0-20ca4581ec97.png)

**Comment by zadjii-msft** [comment]
what the heck

![image](https://user-images.githubusercontent.com/18356694/83262501-b607b400-a182-11ea-8301-6bdb55153314.png)

I might need you to investigate this one, because I can't repro this 😨

**Comment by DHowett** [comment]
Hmm! I’ll look, since you can’t repro.

**Comment by greg904** [comment]
On my computer, the `IShellItemArray* psiItemArray` argument in `OpenTerminalHere::Invoke` is `nullptr` when I click on the "Open Windows Terminal (Dev Build)" button without selecting anything.

**Comment by zadjii-msft** [comment]
For the record, this is a bug that's being tracked by MSFT:24623699 internally.
