### ISSUE TITLE
FiraCode character render issue

### ISSUE THREAD

**Issue by K-E-N-W-A-Y** [microsoft/terminal#6249]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Windows Terminal version (if applicable): Version: 1.0.1401.0

Any other software?
```
WSL2 + ZSH (oh my zsh) + Starship Prompt

# Steps to reproduce

Set Windows Terminal fontFace to Fira Code.

# Expected behavior

Render Square character as it is.

# Actual behavior

Windows Terminal doesn't render square character as it is BTW I use same Fira Code font in vscode & it renders all characters correctly

Windows Terminal: 
![image](https://user-images.githubusercontent.com/25846872/83216427-d9346280-a186-11ea-92c8-fc75b2d53904.png)

VS Code (correct character render): 
![image](https://user-images.githubusercontent.com/25846872/83216477-fbc67b80-a186-11ea-8731-1c939719f106.png)

**Comment by DHowett** [comment]
Can you share the codepoint of that square glyph? I don’t have “lsd” here to test with.

**Comment by K-E-N-W-A-Y** [comment]
sorry, i don't know the exact codepoint for this square glyph. is there any way to get codepoint from this? so I can provide that :)

**Comment by DHowett** [comment]
It may help if you copy and paste it out of VSCode and terminal into a GitHub comment :)

**Comment by jdebp** [comment]
The code points for the characters that you are looking for can be found in https://github.com/Peltoche/lsd/blob/master/src/icon.rs .  It seems that quite a lot of them are Private Use Area code points.  

The error here is in the erroneous expectation that _private use_ code points will be the same from font to font.  The local fix is to make `lsd` _stop (ab)using them_ and have it use the _standardized_ Unicode characters with `--icon-theme unicode`.  

Sadly, a lot more work could be done on `lsd`'s Unicode mode.  This is [issue #10 for `lsd`](https://github.com/Peltoche/lsd/issues/10) and no-one has fleshed out the Unicode icon set beyond basic characters for file and folder.  Please go to the `lsd` people and suggest a few.

**Comment by skyline75489** [comment]
I can concur that this is more of a font issue. A little debugging told me that is a mixed usage of `U+F115` and `U+E27C`, which are both considered illegal Unicode characters. 

If I'm using Cascadia Code, the `lsd` result looks better:

![image](https://user-images.githubusercontent.com/4710575/83241096-eaa05d80-a1cc-11ea-8fd4-fce77e880fd8.png)

However with Fira Code, this will happen:

![image](https://user-images.githubusercontent.com/4710575/83241163-04da3b80-a1cd-11ea-922c-38390dcc8053.png)

**Comment by K-E-N-W-A-Y** [comment]
> It may help if you copy and paste it out of VSCode and terminal into a GitHub comment :)



**Comment by DHowett** [comment]
Well, I've got some _bad news_. That's `U+E60B`, which is firmly in the private use area. Fira Code doesn't have a glyph for that codepoint, so what you're seeing is the NOGLYPH character. It looks like a box, sometimes a `?`, sometimes a `<?>`, and certain layout engines will display it as a cute box with the characters `E 6 0 B` in it.

In all cases, it's the same issue: there's no glyph there. lsd seems to require a special font.

Resolving as external. :smile:

**Comment by K-E-N-W-A-Y** [comment]
@DHowett @skyline75489 i changed windows terminal font to [patched Cascadia code font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CascadiaCode/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf) from nerd fonts. now icons look better.

![image](https://user-images.githubusercontent.com/25846872/83583631-76fea780-a562-11ea-9e9c-e9045674a8da.png)

thanks in advance for the help <3 :)

**Comment by mrbeardad** [comment]
![image](https://user-images.githubusercontent.com/54128430/91625696-11dd1580-e9dc-11ea-86f0-b8131d3feff5.png)
Why my nerdfont icon is so small?
