### ISSUE TITLE
Become C++20-compliant in our use of span

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6251]
# Description of the new feature/enhancement
After discussing with @DHowett about the issues with updating gsl due to gsl shifting to C++20 std:span behavior and in accordance with below, use of span will be updated to C++20 to minimize changes needed by the update.

# A clear and concise description of what the problem is that the new feature would solve.
This will allow us to update gsl.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
Tagging @zadjii-msft since you've updated the most deps. I'm willing to make the updates if needed but do need to know what this project wants to go with (unless internal conversations at MS are going to results in a reversion in the breakage of gsl:span).

**Comment by DHowett** [comment]
It's more likely that we'll just move to GSL 3 and become CPP20-compliant in our use of `span` so we can transition off `gsl::span` with minimal changes later :smile:

**Comment by WSLUser** [comment]
I'll update this issue to reflect that then as a status tracker. Feel free to edit to add checkboxes if multiple issues need to be created that would tracked in this master issue.

**Comment by DHowett** [comment]
Thanks! :smile:
