### ISSUE TITLE
issue in building and deploying

### ISSUE THREAD

**Issue by shivam284** [microsoft/terminal#6252]
Need help with two issues:
1. While building the terminal, I got 38 errors in file U8U16Test.cpp. 
errors like this one:
syntax error: identifier 'length_error'
'length_error': is not a member of 'std'

I corrected these errors and the build was successful. Does this need to be added to documentation?

2. I faced some linking errors while deploying the Cascadia Package. The reason(I suppose) was this:
Build path is:
   terminal\x64\Release
while deploying, it searches for some libs at this path:
  terminal\bin\x64\Release
I copied and pasted the content of terminal\x64\Release to terminal\bin\x64\Release and it worked. But I am looking for a permanent solution. Can anyone help?

**Comment by shivam284** [comment]
@DHowett Please help!!

**Comment by zadjii-msft** [comment]
Please search before filing new issues. This is already fixed in master, in #6226

**Comment by shivam284** [comment]
@zadjii-msft #6226 is also fixing the second issue I am facing?

**Comment by zadjii-msft** [comment]
I don't really think the second one is a real issue - our build definitely intentionally places some things in both `bin\x64\` and `x64\`, so I'd bet that the error from the first was causing the second error as well. If you apply the patch from #6226 and you're still getting build errors, share them here and I can (try) to help diagnose them.
