### ISSUE TITLE
requesting to add 'Run as Administrator' as task, for quick access.

### ISSUE THREAD

**Issue by iamriajul** [microsoft/terminal#6253]
# Description of the new feature/enhancement

Please add run as administrator into tasks (just like PowerShell does).
and also a new tab with administrator permissions will be more helpful (granting Administrator permission while Terminal is open).

PowerShell Features in Start Menu Tile.
![image](https://user-images.githubusercontent.com/24244379/83278457-71693080-a1f5-11ea-8ca5-36aa843bd39c.png)

Thanks.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22Run+as+Administrator%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #4459 for more discussion.

/dup #4459
