### ISSUE TITLE
Mac or Linux support? 

### ISSUE THREAD

**Issue by diberry** [microsoft/terminal#6255]
# Description of the new feature/enhancement
Is it in the plan to have mac and linux support for the terminal - to get the azure cli and powershell functionality on those operating systems? 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22linux+support%22+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #FILL_ME_IN for more discussion.

/dup #2331 #504 #563 #624 #2466 #699 #498 #6074 #4235
