### ISSUE TITLE
Azure Cloud Shell doesn't work with Azure Government

### ISSUE THREAD

**Issue by agates** [microsoft/terminal#6257]
Signing into the Azure Cloud Shell via the browser fails.

# Environment

Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Azure Government subscription

# Steps to reproduce

1. Open an Azure Cloud Shell
2. Enter code at https://microsoft.com/devicelogin
3. Sign into government cloud account

# Expected behavior

Expected to be signed into Azure Cloud Shell

# Actual behavior

I get two error messages:

```
Sorry, but we're having trouble signing you in.
AADSTS65002: Consent between first party application '245e1dee-74ef-4257-a8c8-8208296e1dfd' and first party resource '797f4846-ba00-4fd7-ba43-dac1f8f63013' must be configured via preauthorization. Visit https://identitydocs.azurewebsites.net/static/aad/preauthorization.html for details
```

Logging into https://identitydocs.azurewebsites.net/static/aad/preauthorization.html gives this:

```
AADSTS900381: Request redirection failed. Tenant 'redacted' specified belongs to the National Cloud 'MicrosoftOnline.COM', but Current Cloud Instance 'microsoftonline.us' does not federate with 'MicrosoftOnline.COM'.
```

Is there another preauthorization page I need to visit for gov cloud?  Or is this just not supported?

**Comment by DHowett** [comment]
Sorry about the issue. We're tracking this one over in /dup #3597. There's some compliance stuff we need to do before we can roll out to sovereign clouds. :smile:
