### ISSUE TITLE
Implement delay or timeout command

### ISSUE THREAD

**Issue by vdurante** [microsoft/terminal#6259]
# Description of the new feature/enhancement

Extending the existing command line arguments to implement a `delay` or `timeout` command.

I have the following `profile`:

```json
{
    "guid": "{d41ee793-1255-4694-b5a6-1f69bd94dc09}",
    "commandline": "C:/cmder/vendor/init.bat",
    "hidden": false
}
```

`init.bat` initializes my developing environment, setting variables and activating environments. Since I am a full stack developer, I like to have 3 panes opened, for managing front and back-end development:

```bat
start wt -d ".\client" ; split-pane -H -d ".\server\web" ; split-pane -d ".\server\ef"
```
The issue is, since all 3 panes open at the same time, there are conflicting file reads running in `init.bat` that causes an initialization problem: `The process cannot access the file because it is being used by another process.`

I would like to know if there could be a command for pausing the execution of command chains, Maybe implementing a `timeout` command that could work like this:

```bat
start wt -d ".\client" ; timeout 1 ; split-pane -H -d ".\server\web" ; timeout 1 ; split-pane -d ".\server\ef"
```

Thank you
```

**Comment by DHowett** [comment]
Thanks for the request! We're not likely to implement something like this, because it doesn't generalize well enough to the rest of Terminal's needs. I can, however, recommend implementing a delay in your startup script.

Sorry!
