### ISSUE TITLE
SSH Client Native support in Windows Terminal ?

### ISSUE THREAD

**Issue by mcarbonneaux** [microsoft/terminal#626]
there a plan to integrate SSH Client directly in Windows Terminal ?

**Comment by zadjii-msft** [comment]
I doubt we'll ship an ssh client directly with the Terminal.

However, we do want to be able to let users set up profiles for ssh connections, and that might involve a bit more configuration than just setting a commandline to `ssh [args] user@server`. We'd probably want to provide an actual UI for configuring those sorts of things. 

Additionally, for an ssh-type connection, you don't really need to go through ConPTY. ConPTY is more for Win32 console apps using the console API, but and ssh connection wouldn't need it. So we could remove a layer of indirection, but that would involve dramatically increasing our VT support in the terminal.

**Comment by musm** [comment]
WHy do you want it directly integrated? That sounds worse. Windows already has openssh see https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by WSLUser** [comment]
Change the feature to handling the terminal portion of win32-openssh. It sucks and will never recover love. They rely on here for fixes only available in newer builds even though they have support to win7. Since this project should at least be macro available for all versions of win 10 starting with AU and up, using this directly (and including the necessary VT sequences) would make more sense. Using ssh in WSL doesn't have many issues because why would it?

**Comment by WSLUser** [comment]
> Change the feature request to handling the terminal portion of win32-openssh. It sucks and will never reciev love. They rely on here for fixes only available in newer builds even though they have support to win7. Since this project should at least be macro available for all versions of win 10 starting with AU and up, using this directly (and including the necessary VT sequences) would make more sense. Using ssh in WSL doesn't have many issues because why would it?

**Comment by musm** [comment]
> win 10 starting with AU 

What's AU.

Yes SSH should handle VT sequences better. How does one support the only and the new version without having to ship two version? I don't think it's possible change Code pages and terminal processing at runtime

**Comment by WSLUser** [comment]
`What's AU.`

The version of Windows that first released WSL and the changes to Console (don't recall the actual version number.)

**Comment by DHowett-MSFT** [comment]
Since `ssh` ships in-box, I'm going to close this. It's better for us to have one common ssh implementation instead of diverging.
Thanks for the request!
