### ISSUE TITLE
Disable Pre-Defined Keybinds or Change Them

### ISSUE THREAD

**Issue by bandwiches** [microsoft/terminal#6261]
# Description of the new feature/enhancement

It would be nice to be able to either change or un-bind predefined key binds.

I'm unable to send break sequences to remote devices due to the overlap in the key bind with Windows Terminal.  The remote break sequence is "Ctrl+Shift+6+X" however, once you hit the 6, you just get a bunch of new default shell tabs.

Defining a new key bind to the same action does not disable or replace the predefined key bind.

# Proposed technical implementation details (optional)

We can already define new key binds in the settings, but we cannot disable or change the ones that are pre-existing.  Even if we can't disable them completely, if we could at least change them to something else, that would solve my issue.

**Comment by zadjii-msft** [comment]
It absolutely is already possible to unbind the default keybindings - see [this doc](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings#unbind-keys) for more details.
