### ISSUE TITLE
Feature Request: Keybinding for Moving to Start/End of Line

### ISSUE THREAD

**Issue by trevor-pope** [microsoft/terminal#6262]
# Description of the new feature/enhancement

The [documentation ](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings) doesn't currently list going to the start/end of a line as a possible command. 

It would be nice to be able to rebind the standard Home/End keys to something else, say ctrl+a and ctrl+e that is popular in many other shells.

**Comment by DHowett** [comment]
So, at the end of the day the Terminal is just a grid of characters. It doesn't really have any particular knowledge about what those characters _are_. Unfortunately, that means this is the _shell's_ responsibility.

To configure this in bash, `set -o emacs` (enable emacs key bindings)

To configure this in PowerShell, `Set-PSReadLineOption -EditMode Emacs``

To configure this in CMD, `powershell`, and then `Set-PSReadLineOption -EditMode Emacs`

:smile:
