### ISSUE TITLE
Powerline tutorial should mention how to modify settings.json

### ISSUE THREAD

**Issue by laike9m** [microsoft/terminal#6267]
In the [Install a Powerline font](https://docs.microsoft.com/zh-cn/windows/terminal/tutorials/powerline-setup#install-a-powerline-font) section, it doesn't mention how to modify your settings. It took me a while to figure out I should 

1. Open settings
2. Modify `setting.json` like this (other ways work too)

```
{
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            
            "fontFace": "Cascadia Code PL"
        },
        ...
    }
}
```

As a new user, I would really expect the documentation could cover that.

**Comment by zadjii-msft** [comment]
Huh, it looks like that paragraph just hasn't been localized yet. In the [en-us version](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup#install-a-powerline-font) of that page:

> To set the Cascadia Code PL font for use with PowerLine (after downloading, unzipping, and installing on your system), you will need to open your [profile settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings) in your settings.json file by selecting Settings (Ctrl+,) from your Windows Terminal drop-down menu.

So that doc will probably be updated shortly with the new text, once it's translated.

**Comment by laike9m** [comment]
Thanks for clarifying.
