### ISSUE TITLE
Windows Hello opens in background

### ISSUE THREAD

**Issue by piotrmocko** [microsoft/terminal#6268]
# Environment

```none
Windows build number: 10.0.18363.836
Windows Terminal version: 1.0.1401.0
Ubuntu 20.04 / 18.04 / 16.04 on WSL1
Windows Hello PAM for Linux 1.2
```

# Steps to reproduce

1. Install and configure Windows Hello PAM for Linux 1.2 on Ubuntu 20.04 / 18.04 / 16.04 https://github.com/nullpo-head/WSL-Hello-sudo
2. In Windows Terminal on Ubuntu run for the first time any `sudo` command.
3. Windows Hello opens in the background and fingerprint scanner gets activated, but Windows Hello does nothing until you activate the window with Windows Hello.

I'm experiencing this issue since I started using Windows Terminal 0.6, while it works without any issue in ConEmu 191012[64] or any earlier version that I used since 3 years.

![hello-in-background](https://user-images.githubusercontent.com/977916/83323005-09016a00-a25c-11ea-8b96-d4d7eaabf568.png)

# Expected behavior

Windows Hello opens in the foreground and recognizes the fingerprint from the scanner.

# Actual behavior

Windows Hello opens in the background and fingerprint scanner gets activated, but Windows Hello does nothing until you activate the window with Windows Hello.

**Comment by zadjii-msft** [comment]
I'm gonna guess that this is is actually #2988. That's the issue tracking most of the [z-order](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22z-order%3A+is%3Aclosed) problems the Terminal sometimes has.

/dup #2988

**Comment by piotrmocko** [comment]
After updating Windows 10 to 20H2 and installing the following two updates, the problem has disappeared for me

- https://support.microsoft.com/en-us/help/4578968/kb4578968-cumulative-update-for-net-framework
- https://support.microsoft.com/en-us/help/4579311/windows-10-update-kb4579311
