### ISSUE TITLE
How can I determine if my PowerShell script is running in Windows terminal?

### ISSUE THREAD

**Issue by kasini3000** [microsoft/terminal#6269]
How can I determine if my PowerShell script is running in Windows terminal?

I wrote a script, a.ps1, which contains some special unicode characters.
I want to check whether my script is running in the powershell executed by windows terminal. How can I detect the windows terminal host?

**Comment by marvhen** [comment]
This is working for me:
```
#Is-WindowsTerminal.ps1

function IsWindowsTerminal ($childProcess) {
    if (!$childProcess) {
        return $false
    } elseif ($childProcess.ProcessName -eq 'WindowsTerminal') {
        return $true
    } else {
        return IsWindowsTerminal -childProcess $childProcess.Parent
    }
}

return IsWindowsTerminal -childProcess (Get-Process -Id $PID)
```

**Comment by kasini3000** [comment]
Great,3q alot！

**Comment by oising** [comment]
@kasini3000 I think it's considerably easier to check for the existence of the `WT_SESSION` environment variable. 

```powershell
function Test-WindowsTerminal { test-path env:WT_SESSION }

# or

if ($env:WT_SESSION) { 
    # yes, windows terminal
} else {
    # nope
}
```

**Comment by marvhen** [comment]
Indeed...much easier.   I was not aware of that variable... do you know if it is documented anywhere? Thanks!

**Comment by TitoAldarondo** [comment]
So I too initially headed down the route of checking $Env:WT_SESSION, but quickly realized that this wouldn't work when SSHing to other hosts.  Instead, I decided to simply check for Unicode support in the current session:

`function Test-IsEmojiFriendly {
	if ("$OutputEncoding".EndsWith('UTF8Encoding')) {
		return $true
	}
	return $false
}`

There are probably other terminal-specific considerations here, but hopefully this helps.

**Comment by DHowett** [comment]
That's just going to tell you if PowerShell thinks it can send UTF-8 data somewhere; it will not tell you anything about the capabilities of the terminal it's talking to.

**Comment by gerardog** [comment]
FYI. I just rewrote `IsWindowsTerminal` but with support for WT as default terminal app, [in this comment](https://github.com/microsoft/terminal/issues/5694#issuecomment-1263783220).

**Comment by gerardog** [comment]
> `function IsWTrun {'WindowsTerminal' -in (Get-Process).Name}`

That returns true if any instance of WindowsTerminal is running. PowerShell could be running on an old Console Host and still return true if a WT is open.

**Comment by mrkey7** [comment]
> > `function IsWTrun {'WindowsTerminal' -in (Get-Process).Name}`
> 
> That returns true if any instance of WindowsTerminal is running. PowerShell could be running on an old Console Host and still return true if a WT is open.

Thanks. Do you have a 100% valid method? Looking for $Env:WT_SESSION not valid too
