### ISSUE TITLE
Closing the last tab doesn't close the Terminal

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#627]
From #460:

> Closing the terminal when the last tab is closed is also something we should be doing, but that might be a bit trickier of a PR. I think we're manually suppressing the close action on the last tab currently, but that could be replaced with just closing the app (somehow).

**Comment by mdtauk** [comment]
You could disable the tabs ability to close when it is the only tab, so to exit you must click on the close button on the window itself

**Comment by tkmikan** [comment]
With `"alwaysShowTabs": true`, the terminal is closed after a middle/wheel click at the last tab, but it takes about 3-5 sec or more.
(nothing happens when clicking the close button of the last tab).

**Comment by bef178** [comment]
Do we settle what is the expected behavior?

**Comment by zadjii-msft** [comment]
@mdtauk that seems like a good and reasonable _setting_, like preventing accidental closing with Ctrl+W. 

@tkmikan I believe the behavior you're seeing is that the terminal actually _crashes_ when you middle click the last tab. I believe that fix is #648, though that just prevents closing the last tab with middle click. 

Should closing the last tab with the tab's close button and Ctrl+W be enabled, we should also make sure it's possible to close the last tab with middle-click again.

**Comment by DHowett-MSFT** [comment]
I believe this is done? Somebody fact-check me?
