### ISSUE TITLE
Ctrl + Z reopens closed tab

### ISSUE THREAD

**Issue by mysticum** [microsoft/terminal#6270]
I see that realy userfull, if you'll add ctrl+z for reopening closed tab.

**Comment by blackliner** [comment]
Isn't the common way CTRL + T to open and CTRL + SHIFT + T reopen a closed tab?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #961 for more discussion.

/dup #961
