### ISSUE TITLE
Always left an character when use chinese input

### ISSUE THREAD

**Issue by zzan1** [microsoft/terminal#6272]
# Environment

```none
Windows build number:

Platform ServicePack Version      VersionString                                                                                                   -------- ----------- -------      -------------                                                                                                    Win32NT             10.0.18363.0 Microsoft Windows NT 1... 

Windows Terminal version (if applicable):

1.0.1401.0

Any other software?

no
```

# Steps to reproduce

It always emerge in chinese input. The IME is Micro Pinyin input. When I input some characters but find pingyin is wrong, so I backspace all the chararcters. But there is always left the first one characters I input. 

# Expected behavior

Delete all the characters I inputed

# Actual behavior

![present](https://cdn.jsdelivr.net/gh/zzan1/markdownPicture/normal/present.gif)

**Comment by skyline75489** [comment]
This should be #5110
