### ISSUE TITLE
Support for tab title prefixes

### ISSUE THREAD

**Issue by Z1ni** [microsoft/terminal#6273]
# Description of the new feature/enhancement

It would be nice to optionally prefix tab titles with the profile names / custom text to ease tab discoverability.
Currently I can have multiple tabs that have the same title and I have no way to know which tab is which (except icons when using different profiles).

E.g. when using SSH the title might be "~/folder" as set by the shell. It would be nice to have a setting that allows me to set a custom prefix per profile (maybe `"tabTitlePrefix": "Foo: "` which would result in a tab titled "Foo: ~/folder") and/or prefix the tab title with the profile name (which would result in a tab titled "Profile name: ~/folder") etc. This of course wouldn't solve situations where there's multiple tabs using the same profile.

**Comment by dakom** [comment]
See: https://github.com/microsoft/terminal/issues/6183

Imho once that exists, then one can use the command-line and shell scripts to have things like automatic directory-prefixed tabs

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1320 for more discussion.

/dup #1320
