### ISSUE TITLE
Block cursor should invert color of current character

### ISSUE THREAD

**Issue by hellyarbm** [microsoft/terminal#6278]
### Environment
```
Windows build number: 10.0.19041
Windows Terminal Version: 1.0.1401.0
```

### Steps to reproduce
1. Open settings
2. Add cursorShape : filledBox to powershell profile

### Expected behavior
Character that the cursor is over should invert the color

### Actual behavior
Underlying character is not visible, and while cursor does blink it breaks visibility enough to break workflow
![cursor_invert](https://user-images.githubusercontent.com/26176863/83341724-8c8e7b80-a29b-11ea-91e0-263abf40fcf7.png)

### Notes
Powershell and CMD both do color invert with the cursor set to a solid box
Issue #3561 may be related

**Comment by j4james** [comment]
This would be issue #1203.

**Comment by zadjii-msft** [comment]
Yep, it sure is. Thanks @j4james! 

/dup #1203
