### ISSUE TITLE
Opening terminal from windows explorer should move to current directory

### ISSUE THREAD

**Issue by NikolasP1998** [microsoft/terminal#6279]
# Description of the new feature/enhancement

Open terminal at current directory when typing "wt.exe" at address bar of windows explorer

# Proposed technical implementation details (optional)

Similar to "cmd" and "powershell" implementation.

Windows terminal should be made consistent with the aforementioned alternatives

**Comment by j4james** [comment]
The recommended way to open the terminal in the current directory is by typing `wt -d .` in the explorer bar. See issue https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 for more details.

**Comment by NikolasP1998** [comment]
Thanks for your answer. Even though this is not ideal and leads to inconsistencies, I understand this is the best solution.
