### ISSUE TITLE
support ability to detach tabs into new window

### ISSUE THREAD

**Issue by fawaf** [microsoft/terminal#6280]
# Description of the new feature/enhancement
currently, one can only rearrange the tab order in a particular window. this new feature would add the ability to detach tabs into new window and/or move tabs into other windows

# Proposed technical implementation details (optional)

**Comment by electronic-dk** [comment]
Looks like a duplicate of https://github.com/microsoft/terminal/issues/1256

**Comment by Xyz00777** [comment]
> Looks like a duplicate of #1256

true

**Comment by fawaf** [comment]
ah, indeed it is
