### ISSUE TITLE
ISE integration

### ISSUE THREAD

**Issue by Xyz00777** [microsoft/terminal#6282]
I would really like to see a ISE for cmd, PS, WSL and Azure. These would be really awesome!
You could implement these like at the moment with powershell. One app without ISE and one without or you can add it threw a button who expand the windows with a ISE.

**Comment by WSLUser** [comment]
You want VSCode then. Install it and then install the following extensions: Powershell, Remote-WSL, Azure -(choose the ones that matter to you).

**Comment by zadjii-msft** [comment]
Yea I'm not really sure if this is best served by the Terminal. Maybe as an extension, but I'd need a better explanation of how the UX might work for that. It's certainly a non-trivial amount of work. I think for the time being you're better served by VsCode with the aforementioned extensions.
