### ISSUE TITLE
replace old cmd/ps/WSL

### ISSUE THREAD

**Issue by Xyz00777** [microsoft/terminal#6284]
For a fast and consequent implementation of the new Terminal, these should be implemented like the windows calculator and should replace the actually commandline, PowerShell and WSL Terminals.
It should get implemented like these that it can get fast updates and that there are no more old burdens like we already have enough in windows!
for a easier transition time after the implementation you could implement search results for commandline, Powershell and wsl to the new terminal

**Comment by DHowett** [comment]
Thanks for the request! We're tracking this one over in /dup #492, actually. That workitem will be used for all the work necessary to make Windows Terminal (_and other third-party terminals_) available as an option for "default terminal" on Windows.
