### ISSUE TITLE
Color0 (black) being set and used as default background in Solarized Light theme

### ISSUE THREAD

**Issue by djwf** [microsoft/terminal#6286]
# Environment

```none
Microsoft Windows NT 10.0.19041.0
Windows Terminal Version: 1.0.1401.0
WSLtty Version: 3.1.4.2
```

# Steps to reproduce

Enable the solarized light theme (add "colorScheme": "Solarized Light" to WSL profile).

Open Windows Terminal WSL console.

Execute the following `printf "\033[49;39mDEFBG-DEFFG\033[40;39mCOLOR0-DEFFG\033[0m\n"`.

# Expected behavior

The expected behavior is demonstrated by executing the `printf` command listed in steps to reproduce in `wsltty`, using the color configuration listed below.

```ini
ForegroundColour=101,123,131 # base00, #657b83
BackgroundColour=253,246,227 # base3,  #fdf6e3
CursorColour=38,139,210      # blue,   #268bd2
# Solarized colors for (min|wsl)tty.
# Color 0
Black=7,54,66           # base02,  #073642
# Color 1
Red=220,50,47           # red,     #dc322f
# Color 2
Green=133,153,0         # green,   #859900
# Color 3
Yellow=181,137,0        # yellow,  #b58900
# Color 4
Blue=38,139,210         # blue,    #268bd2
# Color 5
Magenta=211,54,130      # magenta, #d33682
# Color 6
Cyan=42,161,152         # cyan,    #2aa198
# Color 7
White=238,232,213       # base2,   #eee8d5
# Color 8
BoldBlack=0,43,54       # base03,  #002b36
# Color 9
BoldRed=203,75,22       # orange,  #cb4b16
# Color 10
BoldGreen=88,110,117    # base01,  #586e75
# Color 11
BoldYellow=101,123,131  # base00,  #657b83
# Color 12
BoldBlue=131,148,150    # base0,   #839496
# Color 13
BoldMagenta=108,113,196 # violet,  #6c71c4
# Color 14
BoldCyan=147,161,161    # base1,   #93a1a1
# Color 15
BoldWhite=253,246,227   # base3,   #fdf6e3
```
The result was the following:

![wsltty-color0-defaultbg](https://user-images.githubusercontent.com/73162/83369872-a7401d80-a38b-11ea-8871-d6f774d208e6.png)

The command `colortest-8` can also be used to see the issue, by looking at the reverse section. In `wsltty` the reverse section is as follows.

![wsltty-colortest-8-reverse](https://user-images.githubusercontent.com/73162/83370192-9f34ad80-a38c-11ea-96f1-ae001f55f272.png)

# Actual behavior

The actual behavior is that the default background color seems to be written to color0 ("black" in the color scheme). See the outcome of the `printf` command listed in steps to reproduce executed in a Windows Terminal WSL console below.

![winterm-color0-defaultbg](https://user-images.githubusercontent.com/73162/83369884-adce9500-a38b-11ea-9989-655f4b92d3ea.png)

Note that the default background color in the image is the same as color0, even though the Solarized Light scheme defines them to be different colors. This can also be seen in the output of `colortest-8`, where the background of the header of each row in the reverse section should be gray, and the background of the color named fields in the first row of the reverse section should be whatever the "black" color is set to, as seen below.

![winterm-colortest-8-reverse](https://user-images.githubusercontent.com/73162/83370267-e28f1c00-a38c-11ea-89cb-bf235d885047.png)

I also tried creating my own color scheme by copying the Solarized Light scheme, and making sure the background, foreground, and black (color0) colors were set (see scheme below). The results were the same as using the built in Solarized Light.

```js
        {
            "name": "Solarized Light (djwf)",
            "foreground": "#657B83",
            "background": "#FDF6E3",
            "cursorColor": "#268BD2",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "purple": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightPurple": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3"
        }
```

I think that's it, please let me know if you need more information.

**Comment by DHowett** [comment]
Thanks for the report! This is another version of #293 -- we were changing the palette in legacy applications for compatibility reasons. We'll be fixing that shortly.

/sup #293.

**Comment by DHowett** [comment]
heh. /dup #293. :smile:

**Comment by djwf** [comment]
Whoops: I thought I'd searched sufficiently, but apparently not. Thanks for the heads up and link!
