### ISSUE TITLE
PowerShell exits with code 0xE0434352 (EXCEPTION_COMPLUS)

### ISSUE THREAD

**Issue by jackfoxy** [microsoft/terminal#6287]
# Environment

```
Windows build number: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

other software:
PowerShell 7.0.1
git version 2.18.0.windows.1
posh-git https://github.com/dahlbyk/posh-git
```

# Steps to reproduce

not sure I can always reproduce this
last time was running git push twice

![MsTerminalCrash](https://user-images.githubusercontent.com/1824476/83370731-1a8a6500-a375-11ea-8c44-ab57a4a454c9.png)

# Expected behavior

do not crash

# Actual behavior

[process exited with code 3762504530]

**Comment by zadjii-msft** [comment]
@jackfoxy Does this repro in the legacy console host too, or just the Windows Terminal?

**Comment by jackfoxy** [comment]
@zadjii-msft I use cmdr to get multi-tab terminal
cmdr still uses posh-git, but is currently pointed to a previous PS build

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1
```

I have never had these PS crashes in cmdr. MS Terminal starts crashing on me almost immediately. Sometimes the crash closes the window, sometimes it does not and I see the exit code

**Comment by DHowett** [comment]
Is this, perchance, happening when you press <kbd>Ctrl+C</kbd>? The exit code maps to `E0434352`, which is a .NET issue. I'm surprised that Terminal can cause that.

If you use the vintage console host and run the following, does it eventually crash?

```powershell
$Host.UI.RawUI.BufferSize=$Host.UI.RawUI.WindowSize
```

**Comment by jackfoxy** [comment]
I just ran a dotnet build and pressed `ctrl+c` immediately. Build cancelled, no problem.

**Comment by zadjii-msft** [comment]
I'm going to leave this open for now, but unless we can get a consistent repro, I'm not sure there's much we can do about this 😕

**Comment by loicwolff** [comment]
I'm having the issue with Powershell Core (installed using Scoop).

To reproduce, go to `C:\` (or anywhere with a big number of items in the hierarchy), run `Get-ChildItem -Recurse` and hit `Ctrl + C`.

Environment
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

Windows Terminal version: `1.1.2021.0`

**Comment by liesauer** [comment]
same here.
```
PowerShell 6.2.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 1467ms.
C:\Users\me> cd e:
E:\> cd .\Projects\
E:\Projects> cd .\test\
E:\Projects\test [dev ↑2 +0 ~6 -0 !]> git pull

[已退出进程，代码为 3221225786]
```

**Comment by zadjii-msft** [comment]
Oh hmm, @DHowett any chance this is related to that "global dotnet tool ctrl-c" issue we were seeing a few months ago? #3869 perchance?

**Comment by DHowett** [comment]
Yes. If you are seeing this with PowerShell 6 _specifically_, or _any version of powershell installed via scoop_, this is because the powershell wrapper is being terminated when you press ctrl+c. It should not be doing that. This is an upstream bug that is already being tracked on the scoop repository.

**Comment by jackfoxy** [comment]
I know for sure I did not install powershell with scoop

**Comment by DHowett** [comment]
@jackfoxy can you run `gcm -all pwsh`?

**Comment by liesauer** [comment]
> I know for sure I did not install powershell with scoop

+1

**Comment by DHowett** [comment]
> If you are seeing this with PowerShell 6 specifically

@liesaur based on your comment, this applies to you. If you didn’t install via scoop but you’re seeing this issue, that statement applies to you.

Can you also run the `gcm` command i asked @jackfoxy to run?

**Comment by liesauer** [comment]
@DHowett 
```
C:\Users\aaa> gcm -all pwsh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pwsh.exe                                           0.0.0.0    C:\Users\aaa\.dotnet\tools\pwsh.exe
```

**Comment by DHowett** [comment]
@liesauer you’re seeing https://github.com/PowerShell/PowerShell/issues/11314, which has been fixed in newer versions of PowerShell’s dotnet global tool wrapper. I’m not sure how to update the shim specifically if a standard tool update doesn’t do it.

**Comment by liesauer** [comment]
@DHowett i will try updating powershell later and see if still have this issue.

**Comment by DHowett** [comment]
Thanks! Let me know if it works out.

**Comment by liesauer** [comment]
@DHowett it works! thanks!
```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 1721ms.
C:\Users\aaa> cd e:
E:\> cd .\Projects\
E:\Projects> cd .\project\
E:\Projects\project [dev ↑2 +0 ~6 -0 !]> git pull
E:\Projects\project [dev ↑2 +0 ~6 -0 !]>
```

**Comment by jackfoxy** [comment]
@DHowett 

```
PowerShell 7.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.0.3
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.0.3

PS E:\GitRepos> gcm -all pwsh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pwsh.exe                                           7.0.2.0    C:\Program Files\PowerShell\7\pwsh.exe
```

**Comment by DHowett** [comment]
Okay, thanks everyone. I closed this because _most of the commenters_ reported a <kbd>Ctrl+C</kbd> issue, which is actually off-topic for this thread. That was not the right resolution, as that's not what this bug was reporting. :smile:

**Comment by DHowett** [comment]
As best as I can tell, Terminal is the messenger here--it's reporting that PowerShell has been unexpectedly terminated due to an exception. This issue should be filed on the [PowerShell repository](https://github.com/PowerShell/PowerShell).

**Comment by zadjii-msft** [comment]
@jackfoxy Did you ever figure this out, or report this at the PowerShell repo? From the looks of things, this is a PowerShell bug of some sort that the Terminal happens to be catching. I'm sure their team would have a better job diagnosing the issue.

**Comment by jackfoxy** [comment]
@zadjii-msft  I haven't experienced this in a long time.

**Comment by zadjii-msft** [comment]
Even better! Thanks for following up.
