### ISSUE TITLE
Allow no exit when the terminal is run with a `commandline` argument

### ISSUE THREAD

**Issue by mrahhal** [microsoft/terminal#6288]
# Description of the new feature/enhancement

Assume we want to open a multi tab terminal in several directories, and we want to issue an initial command to be run in these directories. We could do the following:

```
wt -d "C:\directory1" dotnet restore `; -d "C:\directory2" dotnet run
```

When the command finishes, the terminal auto closes.
If we were to run a command like `dotnet run`, and then issue a Ctrl+C to the terminal, the terminal tells me the process exited and doesn't allow me to reuse the tab in the same directory.

![image](https://user-images.githubusercontent.com/4404199/83383268-74c70c80-a3ed-11ea-8ad0-81025c60d8c2.png)

I find this a very common pattern where we would have a script that opens a multi tab terminal, but sometimes I would want to stop and rerun one of the commands in one of the tabs, or simply want the tab to remain open in that directory. And in general, I find that this matches more closely to the behavior of the normal powershell/bash/etc terminals. Hitting Ctrl+C on a running app doesn't close the terminal itself, it simply returns command back to the user.

# Proposed technical implementation details (optional)

I propose to add a new argument to the `new-tab` and `split-pane` commands, something like a `--no-exit` optional argument, which would allow the terminal tab to be reused after the initial command in the `commandline` finishes.

**Comment by DHowett** [comment]
Hey, thanks for the request! Unfortunately, Terminal can't do anything about this -- it doesn't control what the shell does once it processes the command you've started.

There's a couple ways to handle this yourself here: https://github.com/microsoft/terminal/issues/5982#issuecomment-630600270 and https://github.com/microsoft/terminal/issues/5982#issuecomment-631228811

/dup #5982.
