### ISSUE TITLE
Consider adding connection grouping lists

### ISSUE THREAD

**Issue by GentelmanBastard** [microsoft/terminal#6289]
Hey,

I am loving the Windows Terminal however with multiple connection profiles, the list quickly gets unreadable. Is there a plan to implement connection grouping like a list of ssh connections to dev environments and other list of qa environments and another list for production environment. It would also be nice to have ability to import such connection tree from .xml file like putty generates.

Best regards.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+group+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571 #6083

I'd also check out #5888, which has got a spec in progress for this feature 😄
