### ISSUE TITLE
Allow drag&dropping to create and modify panes

### ISSUE THREAD

**Issue by schuelermine** [microsoft/terminal#6291]
# Description of the new feature/enhancement

Currently, dragging a tab allows you to rearrange the tab order.

I suggest that it should also be possible to adjust panes this way. Please see the attached image.

Dragging a tab onto a seam between to panes or near the edge of a tab should create a new pane there and place the tab in there. It should also be possible to swap a tab and a pane by dragging onto the center.

The upper-right example is dubious, as it requires the addition of a draggable icon to every pane. It has been greyed out to clarify this.

![pane-rearrangement-illustration-wt-3 edited](https://user-images.githubusercontent.com/48802534/83412555-91c60480-a41a-11ea-9853-a4106cd67ae4.png)

**Comment by zadjii-msft** [comment]
So there's already #4587 tracking "Drag & Drop Tabs to create a Pane", but I love these mockups so I'm gonna just move your comment to that thread and continue discussion there. Thanks!

/dup #4587
