### ISSUE TITLE
Feature Request:  Right click color selection on tabs

### ISSUE THREAD

**Issue by pgwilliams** [microsoft/terminal#6292]
Loving the new Terminal, great job team!

I've recently moved back to windows after many years developing on a Mac using iTerm2.  I often have many tabs open, ssh'd to various boxes - our development, UAT and production environments.  I like to color code each tab.  Dev green, UAT orange, production red, database blue, and my home media server purple.   So that helps me find the relevant tab I need to use and in particular I know to be vewy vewy careful when I'm typing in a red tab.

# Description of the new feature/enhancement
I would like to be able to set the tab color at will.  I don't mind how that's implemented - command line or as a GUI, as long as it's quick and doesn't require me to remember complex codes.  Right now all tabs are black against a dark grey title bar.   

I see there is support for properties of profiles via .json file.   I would like to be able to change the color more quickly, if I were to ssh into a different box I'd like to change the color without having to close the tab and create a new one with a new profile.

# Proposed technical implementation details (optional)
I'd like to right click the actual "tab" part of a tab and have this bring up context specific menu which would (along with anything else that people have requested) allow me to select a tab color from some selection dialog.   Doesn't have to be many, 16 colors would be more than sufficient.   

Thank you!

**Comment by zadjii-msft** [comment]
Boy oh boy will you be excited that #3789 has already merged 😉 

/dup #2994
