### ISSUE TITLE
Animate VisualState changes of Caption Buttons

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#6293]
# Description of the new feature/enhancement

Win32 apps have a short fade animation on pointer enter and exit events, but UWP apps do not. I propose having a short fade animation only when the pointer hover ends on caption buttons, so the app feels snappy on pointer hover start but has a smooth animation on hover end. Its super nit picky and maybe opinionated, so tell me your thoughts

# Proposed technical implementation details (optional)

Add storyboard coloranimation to MinMaxControl.xaml to animate visual state changes. I would be willing to work on this if the proposal is accepted😊

**Comment by zadjii-msft** [comment]
Sure absolutely, go for it!
