### ISSUE TITLE
Refactor fire_and_forget methods in AppLogic to use weak refs

### ISSUE THREAD

**Issue by jelster** [microsoft/terminal#6295]
... `AppLogic` controls the lifetime of the entire application, so it's actually _never_ going away, and we don't need to really worry about it. Though...it wouldn't _hurt_ to do the right thing there as well.

_Originally posted by @zadjii-msft in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMzQyMzM1NQ==/comments/review_comment_

---
Basically, there's a small handful of `fire_and_forget` methods in `AppLogic` that could be refactored to use the weak reference pattern mentioned in the above

**Comment by zadjii-msft** [comment]
Oaky well first off, github exploded that link. Right one is: https://github.com/microsoft/terminal/pull/4908#discussion_r433423355


Secondly - I think we did this. I don't see any more `fire_and_forget`s in `AppLogic` OR `TerminalWindow` that don't anything bad with `fire_and_forget` anymore. Huzzah!
