### ISSUE TITLE
`wt.exe` should support `-%,--percent` for setting a pane's size on the commandline

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6298]
See also #4632. 

This was in the spec but hasn't been implemented yet. Basically just `wt ; split-pane -% 30 cmd` to open the Terminal with two panes, one that's 70% of the available size, and the other that's got 30%. 

Or `wt ; split-pane -% 30 cmd, split-pane -% 70 wsl` for three panes, one with 70/30 split, and the 30 is then split into 30/70, kinda like:
```
+-------------------+-------+
|                   |       |
|                   |       |
|                   +-------+
|                   |       |
|                   |       |
|                   |       |
|                   |       |
|                   |       |
|                   |       |
+-------------------+-------+

```

**Comment by DHowett** [comment]
Triaged onto backlog; tracked through 4632.

**Comment by MagikEh** [comment]
Likewise, when using the `wt` command to open multiple split-panes at once, It'd be nice to automatically balance between those as default rather than going all Fibonacci 
Current Default vs Proposed:
```
+--------------+      +--------------+
|              |      |              |
|              |      |              |
|              |      |              |
|              |      +--------------+
+--------------+  vs  |              |
|              |      |              |
|              |      |              |
+--------------+      +--------------+
|              |      |              |
|              |      |              |
+--------------+      +--------------+

**Comment by zadjii-msft** [comment]
@MagikEh That might be more possible once #6002 is implemented

**Comment by oising** [comment]
FYI, PowerShell uses `--%` as a hint to stop parsing arguments to find variable substitutions etc. I know that's not the same as single hyphen `-%` but just so you know.

**Comment by zadjii-msft** [comment]
@oising That's part of the reason I actually ended up implementing this as `--size,-s` instead, because `%` is tricky like that 😝
