### ISSUE TITLE
Garbage characters after line in nano

### ISSUE THREAD

**Issue by mobluse** [microsoft/terminal#63]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17093.1000]
Ubuntu is most updated.

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
I'm editing a file in GNU nano and when i go to the end of line there are garbage characters after it. The left part shows WSL Ubuntu with original Console and the right part wsltty 1.8.4 (based on mintty). wsltty is correct in this case.
![nano-beep](https://user-images.githubusercontent.com/5777329/36062286-6eab7082-0e69-11e8-80db-c991f50f2daa.png)
`apt source beep`
`cd beep-1.3/`
`nano beep.c`

* What's wrong / what should be happening instead:
There should not be characters after the last `;` on the line starting with `$vent));`. This bug makes it rather difficult to edit files. The colors are also different, but ought to be the same as in e.g. xterm unless one has some special color scheme. The fonts are the same [teletext2.ttf](https://github.com/peterkvt80/Muttlee/tree/master/public/assets) but they have different sizes (16pt and 11pt, respectively) even though they look the same size. I think if one uses a font size it should be the same size on screen in different programs.

**Comment by zadjii-msft** [comment]
In conhost, can you show me a before/after of pasting the text? 

Does selecting (with the mouse) the text that's erroneous (the `;te(console_fd...` bit) cause the erroneous text to get updated?

It looks to me that we're not clearing the line after the text gets pasted - this could be a VT issue or a possibly a rendering issue.

**Comment by mobluse** [comment]
I have not pasted any text -- just gone to the end of the line using the right arrow key.

**Comment by mobluse** [comment]
I can select it with the mouse and that also get copied to the clipboard, but I cannot move into the garbage text with the arrow keys.
![ubuntu 2018-02-13 18_17_06](https://user-images.githubusercontent.com/5777329/36163876-ff37fc14-10ea-11e8-8422-b662eb609322.png) 
![ubuntu 2018-02-13 18_19_35](https://user-images.githubusercontent.com/5777329/36163853-f2fee9b2-10ea-11e8-8698-fa67b0213372.png)

**Comment by miniksa** [comment]
This should probably be repro'd again. It's been a long time and we've made a lot of VT and buffer fixes in the past year.

**Comment by zadjii-msft** [comment]
@mobluse Are you still seeing this on newer Windows builds? Sorry this got lost in the backlog. I'm guessing this might have been a TERM mismatch, or just a faulty VT implementation that might have been fixed in the last year or so.

**Comment by mobluse** [comment]
No, the bug has disappeared here in Windows 10 21H1 19043.1348.

**Comment by zadjii-msft** [comment]
Awesome, thanks for following up!
