### ISSUE TITLE
Text layout caching by run

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#6300]
# Description of the new feature/enhancement

From old ideas of reusing `CustomTextLayout`, it will be more efficient to cache the entire layout for further usage. A classic space-time tradeoff.

# Proposed technical implementation details (optional)

It's a common practice to cache the glyph layout. On macOS, CoreText will internally keeps a cache about glyphs. [Alacritty](https://github.com/alacritty/alacritty) will prematurely set up a cache which contains the glyphs of common ANSI characters. However because Alacritty does this and rendering on character level, it fails to handle ligature correctly.

We've chosen to render run instead of single character. That gives us ligature. Could we also cache the layout by run? The cache hit rate will of course be worse than caching by character. But I feel it'll still be worth the effort.

**Comment by zadjii-msft** [comment]
Okay, this seems like a valuable path to investigate. @skyline75489 do you want me to assign you, or just leave it unassigned for now?

**Comment by skyline75489** [comment]
I'm not sure if it's valuable as I imagine it would be. So let's leave it unassigned for now. Maybe someone with more experience can provide us with more idea on this.

**Comment by skyline75489** [comment]
Closed in favor of #10461
