### ISSUE TITLE
start a new cmd without user specified active code page 

### ISSUE THREAD

**Issue by huoxingkf** [microsoft/terminal#6310]
# Environment

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Also to cmd.exe

# Steps to reproduce
In simpled chinese Environmet;
(Run tomcat with jdk 8);
Run file "startup.bat" in directory "apache-tomcat-8.5.46\bin";
A started tomcat window with messy code.

# Expected behavior
In started tomcat window the word "info" shoud be printed as "信息" in Simple Chinese Edition；

# Actual behavior
In started tomcat window the word "info" is actually printed as messy code"淇℃伅";

# Suggested.
### This issue is frequently discussed in Chinese forum.
When using comand "Start" to start a new cmd window, the new one is expected to inherit the "Active code Page " from the former one.
Also, the started cmd is expected show in "Windows Terminal" other than a new "cmd" window.

**Comment by DHowett** [comment]
We are not planning to change `start` to pass the codepage on to the new process. Sorry. The console window inherits the active codepage on the system, which should be configured correctly for the display of the system's default language.

**Comment by eryksun** [comment]
The console codepage can be customized based on the initial window title that's set by `lpTitle` in the process `STARTUPINFO`. Create a subkey for the initial window title that contains the "CodePage" value that you want. For example, if the title is "Simple Chinese":

```
reg add "HKCU\Console\Simple Chinese" /v CodePage /d 936 /t REG_DWORD
```

You can pass the title to use as the first quoted string in the `start` command. For example:

```
start "Simple Chinese"
```

This will open a new instance of cmd.exe that's attached to a new console session in which the active codepage is 936. Getting it to allocate the console session within a Windows Terminal session is a separate problem.

**Comment by DHowett** [comment]
@eryksun I was sure that we had support for this but when I went looking through our code I just couldn’t find it. Thanks.
