### ISSUE TITLE
Is there a way to associate a keybinding to run an application as part of mapping this in the json settings file

### ISSUE THREAD

**Issue by anoop1005** [microsoft/terminal#6313]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
If you can create a commandline for launching the app then you can create a profile that specifies the keybindings.

**Comment by DHowett** [comment]
Yep. If you create a profile that runs the command you want, you can bind a key to launch it.
We have another workitem on this repo tracking "injecting input from a key binding", which you could also use to run a command.
