### ISSUE TITLE
printing RTL (Arabic text)

### ISSUE THREAD

**Issue by geohadab** [microsoft/terminal#6315]
Arabic text is not printed correctly in ubuntu, cmd and powershells.  I tried to print Arabic text in a python interpreter  and I get the same wrong result. 
this is how the arabic text is printed 
![cmd](https://user-images.githubusercontent.com/6843773/83562834-e5237a00-a522-11ea-822b-4606db229bb7.JPG)
![ubuntu](https://user-images.githubusercontent.com/6843773/83562847-e81e6a80-a522-11ea-9c3d-0225b9f3f646.JPG)

and this is how the text should be printed in python idle and ipython in spyder ide
![idle](https://user-images.githubusercontent.com/6843773/83563005-2e73c980-a523-11ea-8da8-66c5c0677618.JPG)
![spyder](https://user-images.githubusercontent.com/6843773/83563013-32075080-a523-11ea-9d76-6da47f0b25d5.JPG)

windows terminal version: 1.0.1401

**Comment by skyline75489** [comment]
We do not support RTL yet. See the megathread #538 .

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+arabic+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #538 for more discussion.

/dup #538
