### ISSUE TITLE
Set up multiple tabs, each with multiple panes from command line

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/terminal#6320]
# Description of the new feature/enhancement

I would like to be able to start up Windows Terminal with multiple tabs, with each tab having multiple panes.  Right now, I can only start up with multiple tabs, _or_ multiple panes, but can't start up with panes within each tab.  

# Proposed technical implementation details (optional)

Maybe something like this???

```
wt --multiple_tabs (split-pane -p "Command Prompt" -d "C:\D1" ; split-pane -p "Ubuntu" -d "C:\D1")  (split-pane -p "Command Prompt" -d "C:\D2" ; split-pane -p "Ubuntu" -d "C:\D2")
```

**Comment by DHowett** [comment]
So, this is possible today!

The commandline arguments are more like a set of commands to play back in order.

A couple examples:

```
wt new-tab ; split-pane ; split-pane ; new-tab ; split-pane ; split-pane
#  ^ Tab 1, split two more times        ^ Tab 2, split 2 more times
```

```
wt new-tab ; new-tab ; split-pane ; split-pane
#  ^ Tab 1   ^ Tab 2, split 2 more times
#    No splits
```

```
wt split-pane ; split-pane ; new-tab ; split-pane ; split-pane
# ^ **IMPLICIT** Tab 1       ^ Tab 2, split twice
#   Split twice
```
