### ISSUE TITLE
Copy/Paste - Select with the left mouse button and paste with middle mouse button - which is supported in UNIX terminals.

### ISSUE THREAD

**Issue by CanoeFZH** [microsoft/terminal#6323]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1553 for more discussion.

/dup #1553
