### ISSUE TITLE
I hope the "Settings" page not to be displayed as a code file

### ISSUE THREAD

**Issue by iamliuzhiyu** [microsoft/terminal#6325]
# Description of the new feature/enhancement

I hope the "Settings" page not to be displayed as a code file, I think it display as a page in the program with a graphical interface is better.

(Please forgive me for being Chinese and not knowing much about the code in the settings file.)

**Comment by skyline75489** [comment]
We have #1564 for this.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1564 for more discussion.

/dup #1564
