### ISSUE TITLE
SSH disconnected session is hardly recovered

### ISSUE THREAD

**Issue by gcoppola8** [microsoft/terminal#6326]
# Environment

```
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0
```

Any other software?
``` 
WSL with debian
```

# Steps to reproduce

- Open tab with debian console (WSL)
- Connect ssh to a remote machine
- Provoke reset connection due inactivity ( I say provoke because it is unproductive to stay there waiting the connection to reset by time).

# Expected behavior

I expect to see a disconnected message, or to return to debian local console.

# Actual behavior

What happens is that I continue to see the last message from the ssh connection, and clicking "Enter" or sending "CTRL+C" I am not able to go back to my debian environment. If not closing the tab and opening another one.

**Comment by DHowett** [comment]
If you're not getting returned to your Debian session, and you ran ssh from _inside Debian_, there is **nothing** terminal can do for you. If SSH hangs, that's SSH's fault.

**Comment by gcoppola8** [comment]
Hello,
but if I use "Debian" application from the start menu, it doesn't have the same behavior, and in alternative product like bitvise ssh client I get a "disconnected" message at the center of the terminal. 
And in ssh under native debian again I immediately get the control of the session. 
Because this behavior I found it only using Windows Terminal, I thought to report here.
