### ISSUE TITLE
A Windows Telnet session within the Windows Terminal 1.0.1401.0 is not scrollable

### ISSUE THREAD

**Issue by michael-grammling** [microsoft/terminal#6327]
# Environment

Windows Terminal
Version: 1.0.1401.0

Windows 10 1909 18363.836

Microsoft Surface Book 1 with Performance Base

# Steps to reproduce

Start a command line (it doesn't matter if Powershell or cmd).
Open a telnet session using Windows telnet.

# Expected behavior

The view should be scrollable as in the former cmd.exe

# Actual behavior

The view is not scrollable anymore.

It's not clear if Telnet is just incompatible to Windows Terminal, however this should be backward compatible.

**Comment by zadjii-msft** [comment]
Hey I'm gonna resolve this as a dup of #6056, there's a bit more conversation going on in that thread. Thanks!

/dup #6056
