### ISSUE TITLE
Windows terminal doesnt open with the current directory path as its default

### ISSUE THREAD

**Issue by Coderx7** [microsoft/terminal#6330]
# Environment

```
Platform    ServicePack           Version      VersionString
--------     -----------         -------       -------------
 Win32NT  10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

Navigate to a folder of choice, in the address bar, delete everything (which is the current path to the current directory), and write `wt` and press enter : 
the windows terminal pops up but the defaut path is not the current directory.

# Expected behavior
Like CMD, it should start with the current directory path as its default.

# Actual behavior
It always starts at the C:\Users\UserName\ path

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22current+directory%22+is%3Aclosed) when filing new issues. 

The recommended way to open the terminal in the current directory is by typing `wt -d .` in the explorer bar. See issue https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 for more details.

/dup #878, #4287, #4330, #4647, #4787, #4936, #5220, #5796, #6031, #6132, #6171, #6279

**Comment by Coderx7** [comment]
oh I missed the `.` at the end. `wt -d .` seems good. 
Thanks
