### ISSUE TITLE
Clicking on Settings launches FME Desktop

### ISSUE THREAD

**Issue by caracshi** [microsoft/terminal#6331]
# Environment

Windows build number:  10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?

FME Desktop 2020.0.2.1 (20200511 - Build 20238 - WIN64) https://www.safe.com/fme/fme-desktop/ 

# Steps to reproduce

Click the arrow down button for New Tab then Settings and instead of a Settings Menu/Window launching FME Desktop is launched in Generate Workspace mode.

# Expected behavior

A Settings Menu/Window being displayed

# Actual behavior

When clicking on the Settings button from the New Tab menu FME Desktop is launched.

**Comment by caracshi** [comment]
FME Desktop is assigned as Default App for .json
Windows Terminal should force open ...AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json in a text editor or open it in a terminal tab

**Comment by DHowett** [comment]
> Windows Terminal should force open ...AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json in a text editor or open it in a terminal tab

If your JSON editor is something you don’t want opening when you open a JSON file, you should fix that. Terminal will fall back to a text editor (notepad!) if there is no file association. This is a system configuration issue :smile:

If terminal forced users into a specific editor, our users would shout at us.
