### ISSUE TITLE
Key bindings for mouse click

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/terminal#6333]
# Description of the new feature/enhancement

Right now, it's easy to add key bindings for common keyboard combinations, but it doesn't seem possible to remap mouse clicks.

# Proposed technical implementation details

What I'm envisioning is the following in `settings.json`:
```json
{
    "keybindings":
    [
        { "command": "paste", "keys": "middleclick" }
    ]
}
```
This would allow me to use middle click to paste like I do on the Linux terminal.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1553 for more discussion.

/dup #1553 #6323
