### ISSUE TITLE
Pin prompt at bottom

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#6334]
# Description of the new feature/enhancement

I would like to be able to pin the input prompt below, if possible. Like [here](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif). I know that this can be done by adding `printf '\n%.0s' {1..24}` to `.zshrc` file, but maybe it can be done more nicely using the terminal?

# Proposed technical implementation details (optional)

Pin input prompt at bottom of window

**Comment by skyline75489** [comment]
Well this seems more related to shell, instead of terminal.

**Comment by zadjii-msft** [comment]
Yea I'm gonna agree with @skyline75489. This is something that your shell needs to support. There's not really a good way for the terminal application to do anything about this. How would such a feature work in an application like `vim` or `emacs`?
