### ISSUE TITLE
Click drag and rearrange terminal tabs

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/terminal#6335]
Would be great if I could click drag and rearrange the terminal tabs. Perhaps extending to a web browser like look and feel, i.e. actually undock the tabs to a brand new Windows Terminal instance.

**Comment by DHowett** [comment]
You can rearrange tabs today (in non-Admin terminals (#3581)), and tearoff is tracked in #1256. :smile:

**Comment by mwpowellhtx** [comment]
I see, thank you. Difference between running WT elevated versus not.
