### ISSUE TITLE
Support sending f13-f24

### ISSUE THREAD

**Issue by mb1337** [microsoft/terminal#6342]
# Description of the new feature/enhancement

Some programs use extra function keys, <kbd>f13</kbd>, <kbd>f14</kbd>, <kbd>f15</kbd>, etc. I haven't found a way to enter these into windows terminal. In puTTY it's <kbd>shift</kbd>+<kbd>f5</kbd> to get <kbd>f15</kbd>, etc.

# Proposed technical implementation details (optional)
Allow mapping keys in settings.json
```
{ "command": { "action": "mapKey", "key": "f15"}, keys: "shift+f5" }
```

I want to be able to send function keys that are not on a standard keyboard (f13-f24) to a terminal application.

**Comment by DHowett** [comment]
Thanks for the request! I'm going to track this one with /dup #3799, which will allow you to bind any keyboard shortcut to any string. This will let you send the encoded forms of F13-F24.

**Comment by mb1337** [comment]
I tried to use AutoHotkey as a workaround but it doesn't seem to work. I've also tried in cmd and PowerShell. Those don't work either so I think the problem lies a bit deeper.
It does work in puTTY and git bash (but not bash.exe launched from a tab profile).

Windows Terminal
Version: 1.0.1401.0
