### ISSUE TITLE
Drop Down Windows Terminal

### ISSUE THREAD

**Issue by ABOhiccups** [microsoft/terminal#6344]
Can you make Drop Down feature for Windows Terminal? (Similar to Drop Down Terminal on Linux that I'm using)

![Drop-Down Terminal](https://user-images.githubusercontent.com/17691106/83712883-c097d280-a5f4-11ea-8eb5-c2020ae87e1a.png)

**Comment by skyline75489** [comment]
We have #653 for this.

**Comment by zadjii-msft** [comment]
Yep, this is definitely a /dupe of #653.
