### ISSUE TITLE
Changing monitors (DPI) causes strange display issues.

### ISSUE THREAD

**Issue by burhan** [microsoft/terminal#6346]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

1. Execute a command that does a background task (for example, `Invoke-WebRequest`). This will popup a progress indicator.

2. Shift the window to a secondary monitor (that has different scaling or resolution)

# Expected behavior

Things should look the same.

# Actual behavior

(this is while the command was downloading)

![image](https://user-images.githubusercontent.com/603112/83735460-1900bb80-a659-11ea-92bd-32958f763ca6.png)

(one it is finished)

![image](https://user-images.githubusercontent.com/603112/83735559-35045d00-a659-11ea-85c7-718622629a65.png)

**Comment by zadjii-msft** [comment]
This is probably some sort of combo of #3848 and the super old bug #32

/dup #32 #3848
