### ISSUE TITLE
Option to add divider in profile menu

### ISSUE THREAD

**Issue by mcornille** [microsoft/terminal#6347]
# Description of the new feature/enhancement
In the dropdown menu with all the profiles it would be nice to have an option to add a divider.
For the moment my list with remote and local profiles is growing and it would be nice to add divider so its easier to find the profile you need.

My Workaround for the moment is just creating a dummy profile with the name (-----------)
that creates a devider but it would be nice to just use a tag that puts a line in your profile list.

As lists and possibilities in the profiles are growing it would be a nice way to device your list so its easier to search for that one profile you need.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571

I'd also check out #5888, which has got a spec in progress for this feature 😄
