### ISSUE TITLE
Invalid color for prompt elements

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#6348]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

# Steps to reproduce
Install win terminal, zsh, oh my zsh and powerlevel10k theme

# Expected behavior
No black elements in prompt

# Actual behavior
![image](https://user-images.githubusercontent.com/35394377/83752947-12327280-a672-11ea-9601-009ecc415a7b.png)
Previously, I made an issue for the developers, they sent to you
https://github.com/romkatv/powerlevel10k/issues/800

**Comment by zadjii-msft** [comment]
Can you share your `settings.json`?

**Comment by Mystic8b** [comment]
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "tabWidthMode": "titleLength",
    "initialPosition": "830,200",

    "profiles":
    {
        "defaults":
        {
        },
        "list":
        [
            {
                "name": "Ubuntu",
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "icon": "C:/Users/Mystic/OneDrive/Other/Icons/Terminal/ubuntu_32px.png",
                "suppressApplicationTitle": true,
                "tabTitle": "WSL (Ubuntu)",
                "hidden": false,
                "source": "Windows.Terminal.Wsl",
                "colorScheme": "One Half Light",
                "useAcrylic": true,
                "acrylicOpacity" : 0.8,
                "fontFace" : "MesloLGS NF",
                "fontSize" : 9,
                "historySize" : 9001,
                "startingDirectory":"//wsl$/Ubuntu/home/mystic"
            },
            {
                "name": "PowerShell 7.0",
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "source": "Windows.Terminal.PowershellCore",
                "background" : "#1f62af",
                "foreground" : "#ececec",
                "useAcrylic": true,
                "acrylicOpacity" : 0.8,
                "fontFace" : "Courier",
                "fontSize" : 10,
                "historySize" : 9001
            },
            {
                "name": "cmd",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "icon": "C:/Users/Mystic/OneDrive/Other/Icons/Terminal/CMD_32px.png",
                "commandline": "cmd.exe",
                "hidden": false,
                "background" : "#455566",
                "foreground" : "#ececec",
                "useAcrylic": true,
                "acrylicOpacity" : 0.8,
                "fontFace" : "Courier",
                "fontSize" : 10,
                "historySize" : 9001
            }
        ]
    },

    "schemes": 
    [
        {
            "name": "One Half Light",
            "foreground": "#2b2d31",
            "background": "#FAFAFA",
            "selectionBackground": "#0051ff",
            "cursorColor": "#2e312e",
            "black": "#383A42",
            "red": "#E45649",
            "green": "#50A14F",
            "yellow": "#f3ef16",
            "blue": "#1e8de9",
            "purple": "#A626A4",
            "cyan": "#0bb3d4",
            "white": "#FAFAFA",
            "brightBlack": "#5f6169",
            "brightRed": "#DF6C75",
            "brightGreen": "#98C379",
            "brightYellow": "#e4e26c",
            "brightBlue": "#64b6fa",
            "brightPurple": "#C577DD",
            "brightCyan": "#5dd7e7",
            "brightWhite": "#FFFFFF"
        }
    ],

    "keybindings": 
    [
        {"command": "copy", "keys": "ctrl+c"},
        {"command": "paste", "keys": "ctrl+v"},
        {"command": "closeTab", "keys": "ctrl+w"},
        {"command": "newTab", "keys": "ctrl+t"},
        {"command": {"action": "switchToTab", "index": 0}, "keys": "alt+1"},
        {"command": {"action": "switchToTab", "index": 1}, "keys": "alt+2"},
        {"command": {"action": "switchToTab", "index": 2}, "keys": "alt+3"},
        {"command": {"action": "switchToTab", "index": 3}, "keys": "alt+4"},
        {"command": {"action": "switchToTab", "index": 4}, "keys": "alt+5"},
        {"command": {"action": "switchToTab", "index": 5}, "keys": "alt+6"},
        {"command": {"action": "switchToTab", "index": 6}, "keys": "alt+7"},
        {"command": {"action": "switchToTab", "index": 7}, "keys": "alt+8"},
        {"command": {"action": "switchToTab", "index": 8}, "keys": "alt+9"},
        {"command": "scrollDown", "keys": "ctrl+shift+down"},
        {"command": "scrollDownPage", "keys": "ctrl+shift+pgdn"},
        {"command": "scrollUp", "keys": "ctrl+shift+up"},
        {"command": "scrollUpPage", "keys": "ctrl+shift+pgup"},
        {"command": "find", "keys": "ctrl+f"}
//        {"command": "prevTab", "keys": "alt+left"},
//        {"command": "nextTab", "keys": "alt+right"}
    ]
}

**Comment by Mystic8b** [comment]
Now in that issue they told me:
The fact that Microsoft Terminal confuses foreground color 7 with default foreground is a problem of Microsoft Terminal.

**Comment by zadjii-msft** [comment]
Ah okay, yea this is #2661, the bane of @DHowett. 

/dup #2661

**Comment by Mystic8b** [comment]
oh, half a year has passed since the opening of that issue
pls, boys...

**Comment by zadjii-msft** [comment]
If you think it's an easy fix, we'd be happy to accept your contribution 😉

**Comment by Mystic8b** [comment]
Oh no. I don’t think so) But I think such things are more a matter of priority, in the style of "there are more important things."
In any case, I wish you success, I understand how complicated it is, I myself work in this area.
