### ISSUE TITLE
[Feature Request] Toggleable Maximize/Zoom Pane to 100% of Window Size

### ISSUE THREAD

**Issue by daviddyball** [microsoft/terminal#6349]
# Description of the new feature/enhancement

Coming from the Terminator terminal emulator in Linux, I miss the ability to "zoom" into a specific pane (e.g. If I split my terminal into 3 panes, it's sometimes nice to hide 2 and just have 1 pane taking up the whole available window space).

# Proposed technical implementation details (optional)

Implement a `zoomPane` command that hides any panes that aren't focused and resizes the focused pane to use 100% available space. Issuing `zoomPane` again will restore the previous layout.

```
+--------+--------+          +-----------------+
|        |        |          |                 |
|        |   2    |          |                 |
|        |        |          |                 |
|  [1]   +--------+   +-->   |       [1]       |
|        |        |          |                 |
|        |   3    |          |                 |
|        |        |          |                 |
+--------+--------+          +-----------------+

[x] = focused pane
```

NOTE: Pane `2` and `3` are still alive, they are just hidden.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22zoom+pane%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #996 for more discussion.

/dup #996
