### ISSUE TITLE
OhMyPosh agnoster theme causes command to snap back on typing third character

### ISSUE THREAD

**Issue by hchokshi** [microsoft/terminal#635]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 18362.30 (Enterprise)
oh-my-posh 2.0.263 - `agnoster` theme
posh-git 0.7.3
Screenshots taken using Nerd Fonts `Inconsolata NF`, also tried using `FuraCode NF` with same results.
I am using a build from master as of ~11am PDT today.

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
**Windows Terminal**
![image](https://user-images.githubusercontent.com/10136407/57481005-03527400-7256-11e9-995e-d1f91f5663a9.png)
**Fluent Terminal** (expected result)
![image](https://user-images.githubusercontent.com/10136407/57481119-41e82e80-7256-11e9-86bd-fbd21c09298c.png)
**Windows Terminal** (oh-my-posh disabled, posh-git enabled)
![image](https://user-images.githubusercontent.com/10136407/57481689-80321d80-7257-11e9-84d6-04c28a97733e.png)

**Windows Terminal** with agnoster - the problematic theme
![image](https://user-images.githubusercontent.com/10136407/57482363-4c57f780-7259-11e9-91da-2406dff60231.png)

In this case, I typed `test` then backspaced the 4 characters and typed `cd`.  The `e` from `test` is still rendered in its original position, while the other characters erased as expected.

Typing `tes`, the `te` is rendered in its original position and moved position:
![image](https://user-images.githubusercontent.com/10136407/57482444-80331d00-7259-11e9-9c49-76aaf5540600.png)

Typing further works as expected, removing those characters from the screen: 
![image](https://user-images.githubusercontent.com/10136407/57482498-9f31af00-7259-11e9-8dc4-33c87dbab5c2.png)

* What's wrong / what should be happening instead:
Typing the third character should not cause the command to move its rendering (see `cd ~` and `Get-Command` in first screenshot - first character gets covered, no issues with one or two character commands.

There is no theme with ohmyposh disabled (poshgit still enabled), or with different ohmyposh themes including the others that render those arrows. Only agnoster causes this moving to occur.

**Comment by zadjii-msft** [comment]
This seems like we've got the width of the glyphs wrong. Conpty thinks the cursor advanced by one, but we're trying to render it in two cells, or vice-versa.

I coulda swore @miniksa had a fix for this somewhere...

**Comment by miniksa** [comment]
I didn't have a fix for this, just several internal reports of the same issue in different circumstances. I'll dig in when I get time.

**Comment by ksiazkowicz** [comment]
The easiest way to reproduce that is probably putting this in your PowerShell profile.
```
function prompt {
    return '✔ ';
}
```
Just pasting the text in quotes into Terminal makes it buggy.

**Comment by DHowett-MSFT** [comment]
This is actually, weirdly, the same issue as #633. You wouldn't expect it, but they're two sides of the same coin.

The powerline glyphs are in a region of the character table specified as "ambiguous width." Whenever we get one of those, we ask the _font_ how wide the grapheme cluster is. This is required to eventually support things like Devanagari and other N:M glyph->cell mapping scripts. Anyway, the standard NerdFont patcher installs the powerline glyphs as _double-width glyphs_.

So, Windows Terminal asks how wide the powerline characters are and gets "two cells".

There's a conhost instance backing every tab. That one _also_ (for a long list of legacy compatibility reasons that are better explained in #1739) needs to count cells and widths and characters and stuff. That one **is not using the same font**, so it gets a different answer: "one cell".

They trivially and immediately disagree on where the cursor is, and where _all characters after the mis-identified grapheme cluster_ are.
