### ISSUE TITLE
JetBrains Mono Medium ligatures do not work

### ISSUE THREAD

**Issue by tmakowski** [microsoft/terminal#6354]
# Environment

```none
Windows build number: 10.0.18362.836
Windows Terminal version: 1.0.1401.0
Font: JetBrains Mono Medium (v1.0.6)
```

# Steps to reproduce
1. Install [JetBrains Mono font](https://github.com/JetBrains/JetBrainsMono/releases). Version does not seem to matter - I tried v1.0.0, v1.0.3 and v1.0.6 (latest).
2. Set font face in profiles settings to `"fontFace": "JetBrains Mono Medium"`.

# Expected behavior
I expected the ligatures to work. The below image shows an example of `"fontFace": "JetBrains Mono"` where the ligatures work. I expected the same behavior for `"fontFace": "JetBrains Mono Medium"`.

![JetBrains Mono](https://user-images.githubusercontent.com/38053499/83780829-f937ba80-a68d-11ea-885d-c8d44bc27f7b.png)

I checked these fonts in RStudio Desktop's editor and there both, `JetBrains Mono Medium` and `JetBrains Mono`, displayed ligatures.

# Actual behavior
In the "Medium" version of the font the ligatures do not work as shown below.

![JetBrains Mono Medium](https://user-images.githubusercontent.com/38053499/83780781-e7eeae00-a68d-11ea-9e66-189862df620f.png)

**Comment by DHowett** [comment]
That looks like Consolas. Right now, we only support setting font _family_ names (our setting is terrifically mis-named)... so you're getting the fallback behavior.
When 1.1 is out in Preview, you'll be able to set

```
"fontFace": "JetBrains Mono",
"fontWeight": "medium"
```

/dup #1751
