### ISSUE TITLE
splitMode duplicate does not inherit pwd

### ISSUE THREAD

**Issue by tmoerkerken** [microsoft/terminal#6357]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Windows Terminal version (if applicable): Version: 1.0.1401.0

Any other software?
Ubuntu 20.04 WSL 1

```

# Steps to reproduce
Go to folder other then windows user folder (let's say `/mnt/c/Users/timmo/repos`). 
Split pane with:
`{ "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }`

# Expected behavior
Split pane has `/mnt/c/Users/timmo/repos` as `pwd`.

# Actual behavior
Split pane has `/mnt/c/Users/timmo` as `pwd`.

![screen](https://user-images.githubusercontent.com/6529496/83803190-72460a80-a6ac-11ea-95d8-cad54d35550e.gif)

**Comment by DHowett** [comment]
Thanks for the bug report! We're tracking this one as a feature request in /dup #3158.

**Comment by Dibbyo456** [comment]
@tmoerkerken your background color looks dope, mind to share what color scheme is that?

**Comment by tmoerkerken** [comment]
> @tmoerkerken your background color looks dope, mind to share what color scheme is that?

![maCo_IQpxZHQiKhC3btIbR1uw6Y06aGOpibwtQYkA1E](https://user-images.githubusercontent.com/6529496/85199255-671aed80-b2ee-11ea-9e6a-e02ee9e7d44e.png)

I mix it with https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521.
