### ISSUE TITLE
Reconcile ./docs folder versus using the Wiki feature of GitHub

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#636]
Folks are trying to add Wiki pages, but we already have a pile of docs in the ./docs folder.

This represents figuring out where we want to keep a majority of the authoritative knowledge about the project.

The verbal discussion in triage is that they both use Markdown, so we should probably just pick one.

Kayla said she'd think it through and figure it out.

**Comment by binarycrusader** [comment]
The one big downside I know of is that wikis can't be easily forked; there's chatter about this here:
https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki

**Comment by vapier** [comment]
one downside of not keeping docs in the git repo itself is you can't easily branch/snapshot/version the docs with every release.  the wiki always reflects the latest code which might not make sense for a release from a few months ago.  so projects will often try to balance those competing priorities by keeping some docs in the git repo (which make sense on a per-branch/release basis) and keep everything else as a living/latest doc in the wiki.

**Comment by cinnamon-msft** [comment]
@miniksa I think we're all in agreement that everything should be in the ./docs folder, to allow for version tracking and PRs

**Comment by miniksa** [comment]
@cinnamon-msft, OK. Then we should probably formalize the policy in the `README.md` and maybe also leave a single Wiki page up that says "NO NOT HERE, PUT IT IN DOCS."

Can you do that?

**Comment by cinnamon-msft** [comment]
I'm happy to add something to the `README.md`. I also just noticed we can disable the wiki entirely, would that be a better option to avoid confusion?

**Comment by vapier** [comment]
if the wiki isn't going to be used at all, just disable it ?  you can do that under the project settings in github.  then there won't even be a "wiki" tab at all.

**Comment by cinnamon-msft** [comment]
Policy has been added to `README.md` and wiki has been disabled
