### ISSUE TITLE
windows terminal error 

### ISSUE THREAD

**Issue by marcusdwyer15** [microsoft/terminal#6360]
![Windows PowerShell 6_4_2020 3_22_37 PM](https://user-images.githubusercontent.com/46823882/83817367-6ab93e00-a679-11ea-926d-44efb9ce96da.png)
I get this error every time I open windows terminal

**Comment by DHowett** [comment]
Did you follow the link? It says "For more information, see this web page."

**Comment by marcusdwyer15** [comment]
Yeah I did and I still do not known what to do

**Comment by DHowett** [comment]
It would be best if you deleted your settings file. That will reset you to the newest, best version of the settings.

**Comment by marcusdwyer15** [comment]
how do I deatle the settings file

**Comment by zadjii-msft** [comment]
Just open the settings file, then select all the text, hit <kbd>Bksp</kbd> or <kbd>Delete</kbd>, and then save the file. When the file's totally empty, we'll generate a new one for you.

Or you know,

> 
> Do your settings look like this?
> 
> ```json
> {
>     "globals": {
>         "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
>         "initialCols": 200,
>         "initialRows": 65,
>         "initialPosition": "0,0",
>         "wordDelimiters" : " ()\"'-:,;<>~!@#$%^&*|+=[]{}~?\u2502",
>         "confirmCloseAllTabs": true,
>         "keybindings": [
>             ...
>         ]
>     },
>     "profiles": {
>         ...
>     }
> }
> ```
> 
> Then change them to look like this:
> 
> ```json
> {
>     "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
>     "initialCols": 200,
>     "initialRows": 65,
>     "initialPosition": "0,0",
>     "wordDelimiters" : " ()\"'-:,;<>~!@#$%^&*|+=[]{}~?\u2502",
>     "confirmCloseAllTabs": true,
>     "keybindings": [
>         ...
>     ],
>     "profiles": {
>         ...
>     }
> }
> ```
