### ISSUE TITLE
When I enter and exit fullscreen mode vista style appears!

### ISSUE THREAD

**Issue by CharlesPMaxwell** [microsoft/terminal#6361]
![external-content duckduckgo com](https://user-images.githubusercontent.com/65843794/83823177-89e4b980-a6d3-11ea-8e34-141ba7f21dbe.png)

# Environment

```none
Windows build number: 10.0.19041.264]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce
Go to full screen mode and leave it by pressing and holding F11.
**The mouse pointer should now be on the buttons to minimize, maximize and close the window**

# Expected behavior
Vista mode should not appear

# Actual behavior
vista mode appears

**Comment by CharlesPMaxwell** [comment]
I have found an Duplicate: https://github.com/microsoft/terminal/issues/5089

**Comment by DHowett** [comment]
/dup #5089

Thanks!

**Comment by CharlesPMaxwell** [comment]
lol

**Comment by CharlesPMaxwell** [comment]
@DHowett That was fast! :)
