### ISSUE TITLE
Preserve WT_SESSION across restarts

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/terminal#6362]
The macOS terminal (and iTerm, I believe) provide an environment variable analogous to `WT_SESSION` that is preserved across application restarts.  When the terminal restarts, it will recreate all of the windows and tabs in their original position and with the same working directory.

I use this feature to preserve ssh sessions across restarts.  I use a shell function to wrap ssh.  This function creates a file in a specific location whose name is the terminal session ID and whose contents is the connection string.  It then starts a tmux session on the remote end whose session ID is the terminal session ID.  In .bashrc, I check whether a file exists describing the current session and, if so, automatically reconnect.  

When I install software updates on my Mac, the terminal is killed and all of my remote connections resume after the reboot.  A Windows update was forcibly installed last night causing WT to exit and I lost all of my existing connections and spent 10 minutes this morning restoring the state for my working environment.

**Comment by zadjii-msft** [comment]
This is actually really clever. I've never heard of doing anything like that so that seems like a really cool idea. We'll track this as a sub-point in #961

**Comment by davidchisnall** [comment]
Ah, sorry.  I searched for WT_SESSION and read the related bugs, but didn't see #961.

**Comment by paveldvorak5** [comment]
It would be a cool feature. I hate restoring lost terminal tabs after reboot.

**Comment by zadjii-msft** [comment]
@lhecker sanity check me - we do this now, right?

![image](https://github.com/microsoft/terminal/assets/18356694/2d51481d-8be9-4282-986b-9ff12580b50d)

**Comment by davidchisnall** [comment]
I no longer run Windows, so can't confirm, feel free to close.

**Comment by lhecker** [comment]
@zadjii-msft Yup this should work now.
