### ISSUE TITLE
powershell integration bug

### ISSUE THREAD

**Issue by DH-Illidan** [microsoft/terminal#6363]
I can't use `ctrl + space` to show promts in windows terminal when I'm using powershell 5.1.19041.1.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22ctrl%2Bspace%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #879 for more discussion.

/dup #879 #4999 #4590
