### ISSUE TITLE
Windows Emoji Keyboard characters not rendering in Terminal

### ISSUE THREAD

**Issue by devbyaccident** [microsoft/terminal#6364]
# Environment

```none
Windows build number: 10.0.19635.0
Windows Terminal version (if applicable): 1.0.1402.0

Any other software?
```

# Steps to reproduce

1. Open Emoji Keyboard (Win + .)
2. Enter any emoji
3. See character not recognized
![image](https://user-images.githubusercontent.com/12488263/83865715-975e6b80-a6f4-11ea-973c-e347f50fcf7a.png)

# Expected behavior

Emoji character should render in the terminal

# Actual behavior

Emoji is not being recognized

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #190 for more discussion.

/dup #190 #1503

**Comment by devbyaccident** [comment]
> Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #190 for more discussion.
> 
> /dup #190 #1503

Thanks!
