### ISSUE TITLE
Opening new Terminal with Right-Click like 'Git Bash Here'

### ISSUE THREAD

**Issue by jayeshsaini** [microsoft/terminal#6367]
# Description of the new feature/enhancement
I use Git Bash more often which is already relying on the Command Prompt because of its 'Git Bash Here' functionality . By adding this feature of opening New Terminal anywhere with just a **right click** and the path already navigated in the Terminal, many developers like me would benefit.

# Proposed technical implementation details (optional)
Using a shell script to add a registry key which will let us open new Terminal anywhere with Right Click.

### Right click anywhere and open a Terminal with path of that folder already navigated to.

**I want to work on adding this feature to Windows Terminal.**

Device - Lenovo ThinkPad L480(Intel Core i5-8350U, 8GB RAM, 256GB SSD)
Windows Build - Microsoft Windows [Version 10.0.18363.836]
Apps - VSCode, Anaconda, Terminal, Git Bash, Cmd

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1060 for more discussion.

/dup #1060 

In fact, this was actually already implemented in #6100 😉

**Comment by jayeshsaini** [comment]
Will it be released in the next version?

**Comment by zadjii-msft** [comment]
Sure will ☺️
