### ISSUE TITLE
alt+letter sends ^[ and capitalized letter (alt shift letter) instead of lowercase

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#637]
alt+letter sends ^[ and capitalized letter (alt shift letter) instead of lowercase

From MSFT: 21450985

**Comment by atwok** [comment]
Is this related? (using showkey -a for information)

alt+shift+number sends ^[ and the number instead of ^[ and the punctuation associated with the number.

alt+number doesn't send anything all.

**Comment by zadjii-msft** [comment]
That might end up being related. It's certainly good info to have, thanks!

**Comment by zadjii-msft** [comment]
Possibly related to #1209

**Comment by HBelusca** [comment]
Does it fix the Alt-Gr key too?

**Comment by zadjii-msft** [comment]
@HBelusca I doubt it - I don't really have an alt-gr keyboard to test however :/
