### ISSUE TITLE
Terminal hung when executing 'ssh-keygen -o -t ecdsa -b 521'

### ISSUE THREAD

**Issue by tgtran** [microsoft/terminal#6370]
# Environment
10.0.18363.0 Microsoft Windows NT 10.0.18363.0

 Windows Terminal version (if applicable):
1.0.1401.0

Any other software?
```

# Steps to reproduce

ssh-keygen -o -C noname -t ecdsa -b 521
ssh-keygen -t ed25519

# Expected behavior

Generating public/private rsa key pair.
Enter file in which to save the key (/home/ylo/.ssh/id_rsa): 

# Actual behavior
Terminal hung.  Open another Windows Terminal instance and run the same command - it would run

**Comment by WSLUser** [comment]
This used to work. I generated a 4096 rsa key with win32-openssh in Terminal just fine in preview.

**Comment by DHowett** [comment]
This still works for me, with and without win32 input mode. People report this sometimes, but we've never been able to find a common thread.

What keyboard layout are you using? Does it actually work when you run it again/in another tab?

**Comment by tgtran** [comment]
US keyboard - and yes, it worked if I ran it again in another tab.

**Comment by DHowett** [comment]
This is wild. Unfortunately, given that we can't repro it locally -- and it looks like the repro's gone away -- there's not much we can do here. Really sorry about that.

**If you hit this again**, please let me know!
