### ISSUE TITLE
Code Health: Create codeql-analysis.yml Github Action

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6371]
# Description of the new feature/enhancement
Go to Actions and select the codeql-analysis Github Action. This will allow us to perform a vulnerability scan. It will automatically create a build script that can be ingested. However, since this repository hosts more than just C++ code, extra build steps are required (C# from the WPF Control for example, requires build steps). Once it conducts a successful build, it will perform the analysis and provide results for the codebase.

Adding this will keep Windows Terminal a good citizen of security.
# Proposed technical implementation details (optional)
Review our current build steps and take what we need to get the build to run successfully in CodeQL-Analysis.

**Comment by alannt777** [comment]
@zadjii-msft I would like to try this but I have an existing PR. So I can't use the fork to add CodeQL Analysis.

**Comment by zadjii-msft** [comment]
You could always make another branch in your fork though, right? PR's don't _need_ to come from the `main` branch

**Comment by alannt777** [comment]
I did not even think about that.

**Comment by alannt777** [comment]
Well it seems that the only *choice* is to create the branch from *main*:

![Only option seems to be to create a branch from main](https://user-images.githubusercontent.com/67918878/97879290-d0ebdf00-1d45-11eb-890b-488aa4a669a5.png)

I already have some commits for the PR in *main*

**Comment by zadjii-msft** [comment]
Well yea, you'd create a branch off of main in your fork, then try to make a PR in _this_ repo from that branch in your fork, into the main branch of the terminal repo.

See step 5 on [this page](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by alannt777** [comment]
```
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(413,5): error MSB3191: Unable to create directory "D:\a\terminal\terminal\obj\x64\Debug\LocalTests_SettingsModel\". There is not enough space on the disk. [D:\a\terminal\terminal\src\cascadia\LocalTests_SettingsModel\SettingsModel.LocalTests.vcxproj
```

I wonder if MSFT will have more resources being an enterprise organization in GitHub

**Comment by zadjii-msft** [comment]
@alannt777 I'm sorry, could you give a little more context on your comment? Where are you seeing this error?

**Comment by alannt777** [comment]
> @alannt777 I'm sorry, could you give a little more context on your comment? Where are you seeing this error?

Oh. Building in CodeQL GitHub Action in my fork

**Comment by zadjii-msft** [comment]
Ah, that makes more sense. We've been pretty hard pressed for build resources ourselves - if the build in our CI runs out of disk space, I frankly wouldn't be terribly surprised either. We already had crazy build steps that would delete previous build artifacts as we no longer needed them 😃

**Comment by alannt777** [comment]
See this https://github.com/alannt777/terminal/runs/1345451221

**Comment by alannt777** [comment]
So there is absolutely no way to build without some crazy GitHub actions maneuvers?

**Comment by zadjii-msft** [comment]
Okay so I'm just looking at the build log you've linked there - the CodeQL task needs to build the entire solution _again_? I don't think that's gonna fly. Building the solution on our build lab already takes 15+ minutes and something like 15GB+ of disk space. I'd rather re-use the artifacts from a previous build if possible. If that's not, then I don't think that this is gonna be something we can feasibly add to the CI.

**Comment by alannt777** [comment]
CodeQL is supposed to be used as few steps in an existing GitHub Actions CI that works along with other tests and steps. But terminal does not use GitHub Actions for CI. You will also need a GitHub Actions build for in order for CodeQL to work.

**Comment by zadjii-msft** [comment]
Ah. Well. That would certainly make this task impossible then. I doubt we're about to move off ADO to Github actions any time soon, so I'm gonna just close this issue out. Thanks for investigating!

**Comment by alannt777** [comment]
@zadjii-msft 

I have submitted a feature request to Azure DevOps. Please upvote it.

https://developercommunity.visualstudio.com/idea/1242773/integrate-codeql.html

**Comment by WSLUser** [comment]
Are we sure we can't use this with Azure Pipelines enabled? Powershell recently adopted this: https://github.com/PowerShell/PowerShell/pull/13894/files and looking at their other CI, it uses Azure Pipelines. So I think it should be possible to adopt this without too much trouble.

**Comment by DHowett** [comment]
That looks like a github actions config.
