### ISSUE TITLE
How do I close the confirmation dialog

### ISSUE THREAD

**Issue by juzi214032** [microsoft/terminal#6374]
# Description of the new feature/enhancement
When there are multiple tabs, the closing window pops up a confirmation dialog. How do I close this dialog?

![image](https://user-images.githubusercontent.com/38206169/83915610-2f685d80-a7a6-11ea-9112-6d627eba3417.png)

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
What do the buttons say (when translated?)

I’m worried we have a translation error :)

They are supposed to say “close all” (exit the terminal and close all tabs) and “cancel” (do not perform the destructive action)

**Comment by juzi214032** [comment]
your translation is correct

**Comment by juzi214032** [comment]
I want to exit derectly, don't use the confirm.

**Comment by juzi214032** [comment]
I already know the solution. Thank you very much
