### ISSUE TITLE
[Feature Request] Opening tab in last active instance of Terminal via a cli option

### ISSUE THREAD

**Issue by ZeeWanderer** [microsoft/terminal#6375]
# Description of the new feature/enhancement
An wt option to open a new tab in the existing Terminal window. For example, github desktop can detect Windows Terminal and use it to open a repo folder via `d` option but that will always spawn a new Terminal instance. Since having multiple shells/tabs in a single window is the Windows Terminal thing this feature would be useful if tricky to implement.

link for tracking purposes desktop/desktop#9949

**Comment by DHowett** [comment]
Thanks for the request! This is a priority for us. It's being tracked in /dup #4472; follow the scenario in #4632 if you'd like! :smile:
