### ISSUE TITLE
Why can't I download? 

### ISSUE THREAD

**Issue by GhengisGohan** [microsoft/terminal#6376]
App store tells me that I already own Windows Terminal but I cannot access it on my computer (doesn't exist). I have a new Book 2 that I haven't altered in any way. Does it come with it? It's a requirement for my Windows ROS download.

**Comment by GhengisGohan** [comment]
#windows10 #ros #terminal

**Comment by zadjii-msft** [comment]
What version of Windows are you running?

**Comment by GhengisGohan** [comment]
Windows 10.

**Comment by zadjii-msft** [comment]
Sorry, more specifically, _what build_ of Windows 10 are you running? You can find this with the `winver` command:
![image](https://user-images.githubusercontent.com/18356694/83924044-34e38a80-a749-11ea-9f34-dd969c366eea.png)

**Comment by GhengisGohan** [comment]
Version 1809 OS Build 17763.1217 (Sorry should have known that). It says
that I already own it but that none of my systems are compatible.

[image: image.png]

**Comment by zadjii-msft** [comment]
I'd suggest checking the [README](https://github.com/microsoft/terminal#installing-and-running-windows-terminal)
![image](https://user-images.githubusercontent.com/18356694/83924869-45950000-a74b-11ea-813f-b65df569a46e.png)
