### ISSUE TITLE
Could WT add  the 'Pin' ?

### ISSUE THREAD

**Issue by StevenHobs** [microsoft/terminal#6381]
Cause VS Code terminal cant be **separated** and sometimes I want to move the terminal to some places. Topping the window makes itself more **flexible**. 
I think this is really useful and not too hard to achieve. Maybe you can consider wheather to hide this label by adding a global setting in configure profile.
Thanks!!!  ❤❤❤

**Comment by DHowett** [comment]
I’m sorry, I don’t understand. Could you show an example?

**Comment by StevenHobs** [comment]
Pin！！！

**Comment by StevenHobs** [comment]
Put thw window on the top layer

**Comment by j4james** [comment]
I think this might be a duplicate of #3038.

**Comment by StevenHobs** [comment]
I hope it will come out.
