### ISSUE TITLE
How do I start as an administrator?

### ISSUE THREAD

**Issue by juzi214032** [microsoft/terminal#6382]
# Description of the new feature/enhancement
For example, I started CMD in Windows Terminal, but I need administrator rights. What should I do?

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/83961142-e3f7a180-a8c2-11ea-8bad-9b7b244d82bc.png)
![image](https://user-images.githubusercontent.com/10867563/83961154-fbcf2580-a8c2-11ea-955f-8bc06e171497.png)

I think these screenshot can help you solve your issue.

K.M.

**Comment by juzi214032** [comment]
@MouriNaruto 
Yes, that will solve my issue, but I don't think it's convenient.
I wish I had multiple profiles that contained both normal and administrator modes. Instead of needing to start administrator mode with every right mouse click.

Like this:
![image](https://user-images.githubusercontent.com/38206169/83961417-6aad7e00-a8c5-11ea-978c-c595f68780eb.png)

**Comment by DHowett** [comment]
For mixed elevation, see #1032 #5000

**Comment by juzi214032** [comment]
thanks
