### ISSUE TITLE
How to copy unformatted text to clipboard?

### ISSUE THREAD

**Issue by djfogbr** [microsoft/terminal#6383]
When I select and copy something from a WT window, it goes to clipboard as formatted text. 
Is there any setting to copy plain, unformatted text from WT to clipboard?

Thanks.

**Comment by DHowett** [comment]
[docs here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#copy-formatting) about formatted copy :)

**Comment by djfogbr** [comment]
Thanks, it solved.
