### ISSUE TITLE
Open settings in default code editor

### ISSUE THREAD

**Issue by LinqLover** [microsoft/terminal#6385]
# Description of the new feature/enhancement

Instead of using notepad, open the `settings.json` file in the default code editor. This could be inside the terminal: nano, vim, or whatever, or directly in Windows: VS Code, Notepad++ or whatever.

# Proposed technical implementation details (optional)

Probably a new entry in the settings.json would be required to specify the path to the default editor.

**Comment by DHowett** [comment]
Terminal _always_ opens in your default JSON editor. If and ONLY if that association isn’t set does it open in notepad.

I’d suggest checking your file type association settings.

**Comment by LinqLover** [comment]
I see that WT usees the default associated program at the moment, but I could imagine it would be nice if the configuration file would be opened directly in the terminal, no matter what your default JSON editor is. When I open a JSON file in Windows Explorer, notepad is great, but if I'm in a terminal context, I would like to stay there and not be redirected into another program.

**Comment by DHowett** [comment]
But terminal isn't and doesn't ship with a text editor...

Owing to that, you'll probably want #1564 for "edit settings inside the terminal."

**Comment by LinqLover** [comment]
Ah yes, this is what I was searching for. /dup #1564, thank you.
