### ISSUE TITLE
Regex search

### ISSUE THREAD

**Issue by LinqLover** [microsoft/terminal#6386]
# Description of the new feature/enhancement

After #605 was implemented, it would be nice to perform regex searches, too.

I think we could just adapt the look from VS Code with a small regex icon to toggle regex mode:

![image](https://user-images.githubusercontent.com/38782922/83952353-a3534600-a838-11ea-97cc-3818fa9b8426.png)

**Comment by DHowett** [comment]
We have a case sensitivity toggle, it looks like `Aa`. For regex search, /dup #3920 is tracking search enhancements :)
