### ISSUE TITLE
[0x7FFFBB83E044] ANOMALY: use of REX.w is meaningless (default operand size is 64)

### ISSUE THREAD

**Issue by Cppowboy** [microsoft/terminal#6391]
# Environment

```none
win10 professional, 19041.264
for powershell and ubuntu wsl
windows terminal version 1.0.1401.0
no other softwares
```

# Steps to reproduce

Just open windows terminal, and an error message appears on the top of the terminal.
[0x7FFFBB83E044] ANOMALY: use of REX.w is meaningless (default operand size is 64)
This problem only happens when using powershell and ubuntu wsl.

# Expected behavior

The terminal should not show this error message.
# Actual behavior

An error message appears on the top of the terminal when you start a new terminal tab(powershell or ubuntu wsl).

**Comment by DHowett** [comment]
My team does not own any code that would print this message. Do you have a hook library on your system that is injecting into these processes?

**Comment by lovanya** [comment]
I have this problem on Windows 10 Professional 19041.508 too.
Before I updated to 19041.508, I didn't have this problem.
![image](https://user-images.githubusercontent.com/16385444/93727815-84ae6a80-fbef-11ea-87a3-f06c445dbbdd.png)

**Comment by DHowett** [comment]
> My team does not own any code that would print this message. Do you have a hook library on your system that is injecting into these processes?

I used an internet search engine to look this up and found that it's coming from TrendMicro OfficeScan.

**Comment by Cppowboy** [comment]
> My team does not own any code that would print this message. Do you have a hook library on your system that is injecting into these processes?

https://blog.davidz.cn/inspur-ip-guard-uninstallation/

I hope this can help.

**Comment by Cppowboy** [comment]
> I have this problem on Windows 10 Professional 19041.508 too.
> Before I updated to 19041.508, I didn't have this problem.
> ![image](https://user-images.githubusercontent.com/16385444/93727815-84ae6a80-fbef-11ea-87a3-f06c445dbbdd.png)

https://blog.davidz.cn/inspur-ip-guard-uninstallation/

I hope this can help.

**Comment by lovanya** [comment]
> > I have this problem on Windows 10 Professional 19041.508 too.
> > Before I updated to 19041.508, I didn't have this problem.
> > ![image](https://user-images.githubusercontent.com/16385444/93727815-84ae6a80-fbef-11ea-87a3-f06c445dbbdd.png)
> 
> https://blog.davidz.cn/inspur-ip-guard-uninstallation/
> 
> I hope this can help.

I read the blog too, but don't have the permission to uninstall TrendMicro. I tried to turn off it, but this doesn't help.
Before I updated windows, I didn't have this problem.
BTW, this problem will bring problems to git x64. so I switched git to x86, it works normally now.

**Comment by Cppowboy** [comment]
> > > I have this problem on Windows 10 Professional 19041.508 too.
> > > Before I updated to 19041.508, I didn't have this problem.
> > > ![image](https://user-images.githubusercontent.com/16385444/93727815-84ae6a80-fbef-11ea-87a3-f06c445dbbdd.png)
> > 
> > 
> > https://blog.davidz.cn/inspur-ip-guard-uninstallation/
> > I hope this can help.
> 
> I read the blog too, but don't have the permission to uninstall TrendMicro. I tried to turn off it, but this doesn't help.
> Before I updated windows, I didn't have this problem.
> BTW, this problem will bring problems to git x64. so I switched git to x86, it works normally now.

I deleted all the *.dll files in the system related to the company T.E.C, and the annoying log is gone.

**Comment by 520jefferson** [comment]
i have the same problem when i update to 2004

[0x7FF9F0CAE044] ANOMALY: use of REX.w is meaningless (default operand size is 64)
2020/10/11 17:32:18 failed to install wsl2host: service wsl2host already exists

**Comment by bluehymn** [comment]
if your problem coursed by T.E.C ip-guard but you have not permission to remove it, we can modify Regedit to exclude some application for monitoring by ip-guard.
First, create a key 'hookapi_filterproc_external' in 'HKEY_LOCAL_MACHINE\SOFTWARE\TEC\Ocular.3\agent\config' if does not exist, then add 'cmd.exe; wsl.exe, etc.' to the value;

![image](https://user-images.githubusercontent.com/15361704/108812287-d2d5f880-75e9-11eb-86f7-49cd5459d619.png)

**Comment by frankfancode** [comment]
https://github.com/microsoft/terminal/issues/6391#issuecomment-783969254
I  solve thie puzzle use this way

**Comment by KalleOlaviNiemitalo** [comment]
I wonder if the REX prefix in question is part of the "rex.w jmp reg" required for a tail call via a function pointer, as documented in [RtlVirtualUnwind function (winnt.h)](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-rtlvirtualunwind) and [Quick note about x64 Tail call](https://docs.microsoft.com/en-us/archive/blogs/freik/quick-note-about-x64-tail-call).

**Comment by azhi09** [comment]
> if your problem coursed by T.E.C ip-guard but you have not permission to remove it, we can modify Regedit to exclude some application monitored by ip-guard.
> First, create a key 'hookapi_filterproc_external' in 'HKEY_LOCAL_MACHINE\SOFTWARE\TEC\Ocular.3\agent\config' if does not exist, then add 'cmd.exe; wsl.exe, etc.' or **'*.exe'** to the value;
> 
> ![image](https://user-images.githubusercontent.com/15361704/108812287-d2d5f880-75e9-11eb-86f7-49cd5459d619.png)


I create this new key but auto remove after reboot. @bluehymn

**Comment by bluehymn** [comment]
重启以后 ip-guard 应该会恢复注册表，需要再改回来 @azhi09

**Comment by azhi09** [comment]
> 重启以后 ip-guard 应该会恢复注册表，需要再改回来 @azhi09

这么说来，如果我改了注册表这个地方后没解决问题，就可能不是 ip-guard 导致的了？

**Comment by lovanya** [comment]
I changed the default cmd.exe path to C:\Windows\SysWOW64\cmd.exe. Then solved it😭. ![image](https://user-images.githubusercontent.com/16385444/113143807-2ed21380-925f-11eb-8cdc-5c2dcddc384e.jpeg)

**Comment by noyidoit** [comment]
> 重启以后 ip-guard 应该会恢复注册表，需要再改回来 @azhi09

Thanks for your solution, you saved my day !

Besides, any ideas to fix the reg make it won't change afterr system reboot? (make the change last in a  long time)

**Comment by KeithChao** [comment]
[HKEY_LOCAL_MACHINE\SOFTWARE\TEC\Ocular.3\agent\config]
Add "hookapi_disins"="1" to stop it temporary.

Then search "Ocular" with regedit.
You will find two services: winrdgv3.exe and THlpDrv64.sys.
Locate the folder of these two files, rename all those files with same date/time.

They causes my Qt installation and Qt Creator fail.
They looks like Trojan. THlpDrv64.sys will recover winrdgv3.exe installation.
