### ISSUE TITLE
How to set color theme

### ISSUE THREAD

**Issue by darkworks** [microsoft/terminal#6393]
Am wondering how can we set color template in windows terminal i followed the guide in settings.json but no success. also i think it will be good to have UI to set colors instead of editing these settings files which can lost in future updates

# Environment
windows 10 PRO  
version : 1903
windows terminal version : 1.0.1401  ( latest )

# Steps to reproduce

- download and install latest version of windows terminal
-  open and click down arrow on top menu and then click settings 
- settings,json file will open in note pad then scroll down to color scheme settings 
- As guided in color scheme section visit : https://aka.ms/terminal-color-schemes
- copy color template 

`{
    "name" : "Campbell",
    "cursorColor": "#FFFFFF",
    "selectionBackground": "#FFFFFF",

    "background" : "#0C0C0C",
    "foreground" : "#CCCCCC",

    "black" : "#0C0C0C",
    "blue" : "#0037DA",
    "cyan" : "#3A96DD",
    "green" : "#13A10E",
    "purple" : "#881798",
    "red" : "#C50F1F",
    "white" : "#CCCCCC",
    "yellow" : "#C19C00",
    "brightBlack" : "#767676",
    "brightBlue" : "#3B78FF",
    "brightCyan" : "#61D6D6",
    "brightGreen" : "#16C60C",
    "brightPurple" : "#B4009E",
    "brightRed" : "#E74856",
    "brightWhite" : "#F2F2F2",
    "brightYellow" : "#F9F1A5"
},`

- paste it inside : "schemes": [  ],
- save it and get back to windows terminal it will give error

`Settings could not be reloaded from file. Check for syntax errors, including trailing commas.
* Line 87, Column 1
  Syntax error: value, object or array expected.

Temporarily using the Windows Terminal default settings.`

![image](https://user-images.githubusercontent.com/12841788/83965919-8bc79c00-a8d0-11ea-8928-47fed7c661fc.png)

# Expected behavior

to set collor

# Actual behavior

error

![image](https://user-images.githubusercontent.com/12841788/83965926-9c781200-a8d0-11ea-84e7-d87937bc0ac1.png)

**Comment by hanubeki** [comment]
It seems trailing comma issue, try removing `,` after `}`.

**Comment by darkworks** [comment]
ya it was comma issue
