### ISSUE TITLE
Add an option to make the tab color match the background color 

### ISSUE THREAD

**Issue by GabrielSalach** [microsoft/terminal#6394]
# Description of the new feature/enhancement

Hello everyone ! 
When I'm working in the new terminal, I use a colorscheme with a blue background. However the tab color is always black (or white it depends if you are in dark mode or not). 

So what I'm proposing is to add a new option in the settings.json (either at the root or specific for each profile) to change the color of the tabs depending on the background color or even chose and RGB value for the tab color. It could improve workflow for people like me, who are obsessed with how clean their environment looks.
The option would look like `"tabColorMatching": true` or `"tabColor": "#012456"`

The only problem that I think of at the moment is the fact that many people prefer to use an image as their background so that might be an issue.

Here is an example : 

(Off)
![1](https://user-images.githubusercontent.com/60842220/83967028-56b24e00-a8be-11ea-85b6-462228ae599b.png)

(On)
![2](https://user-images.githubusercontent.com/60842220/83967039-6c277800-a8be-11ea-9abe-2453fa96aefe.png)

I am new here so I don't know if such a feature can be possible, also I didn't find any post similar to mine so I hope that this is not a duplicate !

Sorry if there are grammar errors, english is not my native language. 
Thanks for your attention, and thanks to the MS Team for creating such a useful tool !

**Comment by j4james** [comment]
See issue https://github.com/microsoft/terminal/issues/1337#issuecomment-503764888.

**Comment by GabrielSalach** [comment]
> See issue [#1337 (comment)](https://github.com/microsoft/terminal/issues/1337#issuecomment-503764888).

Oh didn't see it sorry then I'll close the issue I guess :)
