### ISSUE TITLE
GetCurrentConsoleFont(...) always returns size {0,16}

### ISSUE THREAD

**Issue by vladdeSV** [microsoft/terminal#6395]
The API call to `GetCurrentConsoleFont(...)` always yields a size of `{0,16}` (`consoleFontInfo.dwFontSize`)

# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 1.0.1401.0
```

# Steps to reproduce

1. Compile the following C++ program

```c++
#include <windows.h>
#include <iostream>

int main()
{
	HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);

	CONSOLE_FONT_INFO consoleFontInfo;
	GetCurrentConsoleFont(hStdOut, FALSE, &consoleFontInfo);

	std::cout << "Font Size: {" << consoleFontInfo.dwFontSize.X << "," << consoleFontInfo.dwFontSize.Y << "}" << std::endl;
}
```

2. Run the program in Terminal with either CMD or Powershell
3. The output is always `{0,16}`, regardless of `fontSize` in settings.json

# Expected behavior

As with regular `cmd.exe` and `powershell.exe` I would expect the output to display some reasonable data

![resize in regular apps](https://i.imgur.com/z0T2k4e.png)

# Actual behavior

The size outputted is always `{0,16}`, regardless of settings.
![resize in terminal](https://i.imgur.com/19chyku.png)

**Comment by DHowett** [comment]
This is by design. The process is isolated from the Terminal just like it would be if it were over SSH. There is no font in SSH.

Giving the console application access to the font information was a big mistake, so we are only providing bare-minimum compatibility for this API.

What is your use case?

**Comment by vladdeSV** [comment]
Before I call a resize-even in my own code I use it in combination with `GetSystemMetrics(SM_CXMIN)` and `GetSystemMetrics(SM_CYMIN)` to get the minimum size of the console in pixels.

I then calculate how wide and tall the window is based on the font size and check If the console can be set to that size.

See code [here](https://github.com/vladdeSV/scone/blob/develop/source/scone/os/windows/output/windows_output.d#L60-L72).
