### ISSUE TITLE
Reproducible crash bug - resizing tmux SSH window

### ISSUE THREAD

**Issue by kellytrinh** [microsoft/terminal#6396]
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Microsoft Windows [Version 10.0.19041.264]

Windows Terminal version (if applicable):

1.0.1401.0

Any other software?

SSH 

# Steps to reproduce

SSH into VM and run tmux.
Tmux is running on the another concurrent SSH session with different window size (smaller)
resize terminal window to get rid of size bars.
If resize goes to smaller than other sessions window, Windows Terminal will crash.

# Expected behavior

Resizing window shouldn't crash the terminal and take down all the other tabs.

# Actual behavior

Need to restart Windows Terminal

**Comment by DHowett** [comment]
(Did you intend to close this issue?)

**Comment by kellytrinh** [comment]
Yes intentional.

The bug is was definitely there but I couldn't reproduce it when trying to
get the feedback hub diagnostics.  If you still have value in the
description for tracking purposes then can reopen but do note I cannot
supplement with further technical details

**Comment by DHowett** [comment]
If you hit it again, comment here and I’ll reopen. Thanks for cleaning up :)
