### ISSUE TITLE
Invalid vim format when I paste text from windows

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/terminal#6397]
When I copy config from link: https://ubuntu.com/tutorials/install-and-configure-wordpress#3-configure-apache-for-wordpress. Then I paste to vim in wsl2 ubuntu. Format text will invalid

**Comment by DHowett** [comment]
You need to enter insert mode or `:set paste` in vim.

Closing this since it doesn't have an example of what's happening -- we can't really debug it like this.

**Comment by trinhcanhphuc** [comment]
Ok thanks, let me check later
