### ISSUE TITLE
Can't open file wsl2 system by alias windows app

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/terminal#6398]
I make Sublime app on Windows is a alias in wsl2 ubuntu by command ( ```sudo ln -s .../subl.exe /usr/local/bin/subl```). When I call by command sudo subl /etc/...config. I write text in subl and save. It returned a bug not found file with invalid file path.

**Comment by DHowett** [comment]
You may want to file this on the [WSL repository](https://github.com/microsoft/wsl/issues)

**Comment by trinhcanhphuc** [comment]
Yep, it should save in WSL repository, but currently, it show file path in windows repo
