### ISSUE TITLE
Be able to configure the selection highlighting behavior

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#64]
When you highlight text with the Command Prompt (cmd.exe), it just inverts the
colors of whatever you selected:

> ![white](http://stack.imgur.com/s5fjS.png)

However the white is a little bright for me, I would prefer gray background.
Can I change the white highlight color, if so how?

http://superuser.com/questions/1293003

**Comment by zadjii-msft** [comment]
The selection color is chosen automatically based on the background color. There's not currently a way to change that behavior. 

I'm going to make this the "Be able to configure the highlight behavior" issue. Changing that behavior isn't going to be an easy task, and I'd guestimate that it's pretty far down on the backlog.

**Comment by miniksa** [comment]
Moving this to Terminal product. We would take this as a feature request for the new UI, not the old one.

**Comment by Stanzilla** [comment]
Yup, other terminals just let you overwrite the highlight color, would be nice to have here as well.

**Comment by mdtauk** [comment]
Maybe add two settings...
`selectedForeground: "inverted"`
`selectedBackground: "inverted"`

Allow either the word **inverted** or an explicit colour **#000000**

**Comment by ZoeyR** [comment]
I think this should also be tagged as an accessibility issue. The current selection highlighting scheme does not meet contrast ratio requirements for accessibility and with no way to configure it users with impaired sight will have issues.

**Comment by cup** [comment]
@ZoeyR you might need to elaborate on that. While I would certainly like to see this fixed, I dont think the current state fails in regard to accessibility. At least not in the default state.

White on black (and black on white) is perfectly readable. The only exeception to this might be users with light sensitivity. Or if you set the color to gray, I would image you might get some gray on gray thats not very readable.

**Comment by ZoeyR** [comment]
@cup, my bad. I thought this was for customization in the new windows terminal, which doesn't do the inversion, it instead does a 50% opacity of based on the default foreground color.

**Comment by zadjii-msft** [comment]
Oh hey, this issue looks like it got lost.

We merged #3471 _months_ ago which added this to the Terminal. Plus, there's now #3580 for tracking adding a `selectionForeground` color. I'd say that with that in mind, this can be closed. 

Thanks all!
