### ISSUE TITLE
Add keybinding for moving up/down an entire page at a time

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#640]
Ctrl+Shift+PgUp/Dn should move an entire page at a time

Ctrl+Shift+Up/Dn Arrow should move one (N) lines at a time

**Comment by Kapperchino** [comment]
@zadjii-msft Can I be assigned this issue?

**Comment by miniksa** [comment]
@zadjii-msft, can you follow a similar outline to https://github.com/microsoft/Terminal/issues/576#issuecomment-491129438 to get @Kapperchino started when you see this presuming you're good with it?

**Comment by zadjii-msft** [comment]
Absolutely!

* I'd first take a look at how to add a new keybinding event. Take a look at #623, where someone's adding a keybinding for alt+num to go to a particular tab as reference.
* I'd also take a look at the existing keybinding for Ctrl+Shift+pgup/dn as a reference how to scroll one line at a time. See `src/cascadia/terminalapp/app.cpp` for the implementation of `_DoScroll`.
* I'd add another method like `DoScroll`, but instead of scrolling by a specified amount, only specify a direction, and have the method query the active terminal control for how tall it is, and scroll by that amount.
* as an additional note, this involves changing the current keybindings for scroll up/down to Ctrl+Shift+Up/Dn Arrow. Those are setup in `CascadiaSettings.cpp` I believe.

As @miniksa mentioned, you're going to be among the first people we assign to do a feature that aren't on our direct team. It might be rough and neither we nor you know exactly what to expect. Bear with us. We're learning how to be open as much as you're learning how to work in our code.

If you need any help, please feel free to ping me on this thread. I'm happy to help.

**Comment by Kapperchino** [comment]
@zadjii-msft For the height of the terminal, do I get the view height and then calculate how many lines that would be? Or is there a way to get how many lines of text the terminal has?

**Comment by zadjii-msft** [comment]
I think that `Terminal::GetViewport().Height()` would bet you the height of the terminal in rows. You might need to plumb that up through the `TermControl` somehow.

**Comment by Kapperchino** [comment]
How do I make a test for it? I only did some manual Testing so far

**Comment by Kapperchino** [comment]
@zadjii-msft how do I make a test for this? I did some manual testing.

**Comment by zadjii-msft** [comment]
You know, I don't think we actually have any test for this particular area of the code. So I think you're probably fine making a PR without the tests for now. That's on me to add the testing infrastructure :P

**Comment by Kapperchino** [comment]
alright, I'll be doing the pr then, thanks for your help!

**Comment by miniksa** [comment]
Looks like the related PR was completed. Resolving.
