### ISSUE TITLE
[VT Mouse Mode] Release is not fired when a drag begins inside and exits the terminal window

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#6401]
# Environment

```none
Windows build number: 10.0.18363.836
WSL profile
```

# Steps to reproduce

Use WSL profile, enable the mouse tracking mode `SGR (1006)`: 
```cmd
echo -e '\e[?1003;1006h'
```

If you press the mouse button in the terminal window and move the cursor outside the window and release the button there, the application running in the terminal does not receive a message that the button has been released.

When the mouse tracking mode is on, while holding any mouse button and moving the cursor outside the window, the mouse tracking should not stop.

# Expected behavior

If the mouse button was pressed inside the terminal, then the message about releasing the mouse button should come even if the mouse cursor has moved outside the window.

# Actual behavior

А message about releasing the mouse button (and any tracking messages) does not come if the mouse cursor has moved outside the window.

**Comment by DHowett** [comment]
Great catch. Thanks!

**Comment by DHowett** [comment]
(Renamed a bit for tracking purposes.)

**Comment by o-sdn-o** [comment]
I created a resource for testing mouse tracking in the terminal.
If this is useful to someone, it is accessible via telnet:

- Seattle region   
`telnet seattle.netxs.online`
- Frankfurt region  
`telnet frankfurt.netxs.online`

It is possible to add additional functionality there or add a region closer.

**Comment by o-sdn-o** [comment]
Release is not fired also inside the terminal window when the drag starts inside the grid of cells and goes outside of the grid of cells.

![ezgif-7-f0f01bd46440](https://user-images.githubusercontent.com/11535558/89122595-ccfbb700-d4e1-11ea-8a8e-4d4e01da9508.gif)

This causes great difficulties in full-screen mode, when there are inactive fields along the edges, since the mouse cursor stops just at these inactive fields.

**Comment by DHowett** [comment]
I know that this doesn't move the needle much, but _WOW, your TUI looks so cool!_
