### ISSUE TITLE
Search Bar Add to Windows Terminal

### ISSUE THREAD

**Issue by haseebse** [microsoft/terminal#6403]
# Dear windows terminal team first of all I appreciated developed windows terminal. I was using windows terminal since preview build. I suggest to the windows terminal team to develop the Search Bar for the windows terminal. if search bar add-in windows terminal then easy to find the name of such file name or some commands. And Search bar adds to the top of windows terminal. Why I say search bar add to windows terminal because I'm python developer I have a lot of install python PIP but when I find some pip name then I scrolled up and down. That way, I request to wonderful windows terminal team and @cinnamon-msft to develop the search bar /Search Box.

**Comment by DHowett** [comment]
Thanks for the request! We actually have a search bar, all you have to do is press Control+Shift+F. Does that help?

**Comment by haseebse** [comment]
> Thanks for the request! We actually have a search bar, all you have to do is press Control+Shift+F. Does that help?

thank you
