### ISSUE TITLE
Emoji in Ubuntu shell are not deleted correctly

### ISSUE THREAD

**Issue by ivanjonas** [microsoft/terminal#6404]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

1. Open an Ubuntu/bash window
2. Note the position of the cursor. 
3. Type the word "git"
4. Open the Windows emoji picker with Win + period and choose an emoji. For example, the "smiling face with smiling eyes" emoji (😊) or any other emoji that isn't part of the original windows black-and-white emoji set. For contrast, the recycle (♻) emoji does not show this problem because it's part of that set.
5. Press backspace once to delete the emoji. Notice that the emoji is still visible but the cursor is in the middle of it.
6. Press backspace again to "finish" deleting the emoji. The original text "git" will still be visible.
7. Press Enter.

# Expected behavior

The `git` program runs outputting information about subcommands.
If I delete an emoji character that takes up two blocks of space, I expect the cursor to go backward two spaces, and I expect that pressing Enter will execute the command that is displayed. 

# Actual behavior

The command prompt complains "gi: command not found", even though the line above still says "git"

![image](https://user-images.githubusercontent.com/4935079/83986113-a833fa80-a909-11ea-9d87-93310ec476be.png)

Deleting double-width emoji will move the cursor back only one space, and the displayed command is be the command that will be executed.

**Comment by zadjii-msft** [comment]
Hey lemme real quick cross link this with discussion over in #6555, which is seeing some similar disagreement in character width

**Comment by ivanjonas** [comment]
@guilhermetod Heh, you're right, it seems the Windows Terminal came with a powerline out of the box, and it DOES have some issues... but that's a red herring :) I only intended to show you the command itself in line 1 and the output in line 2.

**Comment by DHowett** [comment]
It looks like we root-caused this in /dup #6555, so I'm gonna close this one out. Thanks everyone for reporting!
