### ISSUE TITLE
Cannot Modify defaults.json

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [microsoft/terminal#6405]
# Environment

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

1. Download windows terminal app from Microsoft store without associated account. 
    E.g. Local user account only
1. Open windows terminal
1. Select alt+settings
1. Make a change
1. Try to save

# Expected behavior

Saves changes

# Actual behavior

Refuses to save changes.
Refuses to save changes as admin.
Refuses to save changes from multiple different editors.
Refuses to save changes when taking ownership of file and assigning user full control.
Refuses to save changes when appending via admin command prompt. 
E.g. `echo test >> C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.0.1402.0_x64__8wekyb3d8bbwe\defaults.json`

**Tested with both regular and preview install.**

**Comment by DHowett** [comment]
You're not _intended_ to edit `defaults.json`.

**Comment by DHowett** [comment]
(Even if you can edit the file on disk, it's only there to show you what the default built-in settings are. It isn't used by the application.)

**Comment by Jared-Harrington-Gibbs** [comment]
Thanks for the clarification.
I should have read the documentation/file closer.
