### ISSUE TITLE
Open new tab into existing Windows Terminal process when run "wt.exe new-tab" command

### ISSUE THREAD

**Issue by GitPopcorn** [microsoft/terminal#6407]
# Description of the new feature/enhancement

Could you please considering adding a parameter for the "new-tab" command to open a new tab in existing Windows Terminal process?
Now when I open new terminal using the right click menu item, it always start a new process with a brand new window, that has weakened the meaning of tab function more or less I guess.

# Proposed technical implementation details (optional)

Null.

# Remarks

However I know this feature may be a bit much difficult to implement cuz maybe we need to check the process information to do that and this way might not be stable enough to work in various situations, so just ignore my request if it cost much.

Thanks.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472
