### ISSUE TITLE
Change to split terminal not possible

### ISSUE THREAD

**Issue by stendebach** [microsoft/terminal#6410]
#2450 Environment

Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Version: 0.11.200504001-release1.0

If I split the terminal with atl + shift + d, it is not possible to switch to the other terminal. If I move the window to the primary screen it is possible again.

The problem occurs with powershell as well as with the cmd.

**Comment by zadjii-msft** [comment]
Well, that's insane. I haven't the faintest clue why this would happen. If you split the pane, then open a new tab, then switch back to the first pane, can you switch panes then?

Also, does updating to 1.0 help at all?

**Comment by stendebach** [comment]
With the 1.0 Release the problem is solved.

Thanks a lot

**Comment by DHowett** [comment]
Thanks
