### ISSUE TITLE
"copyFormatting" default value is 'true', while, according to documentation, it should be 'false'

### ISSUE THREAD

**Issue by srdjanjovcic** [microsoft/terminal#6413]
# Environment

```none
Windows build number: 10.0.19642.1
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

- Ensure that "copyFormatting" is not defined for whatever profile you are using.
- Copy something from terminal.
- Paste it in Word, e-mail, anything with RTF support.

# Expected behavior

- Plain text is pasted.

# Actual behavior

- RTF text is pasted.

#Notes

- This behavior is introduced with https://github.com/microsoft/terminal/pull/5299, however, according to [Formatted Copy spec](https://github.com/microsoft/terminal/blob/08df4fc27a7f0a14c5230a690cc96c9b76c2a9a0/doc/specs/%234191%20-%20Formatted%20Copy/spec.md), vast majority of users prefer unformatted copy out of terminal:

> The default should be to only copy plain text, based on the response from this poll on Twitter. 
> ![Twitter poll](https://github.com/microsoft/terminal/raw/08df4fc27a7f0a14c5230a690cc96c9b76c2a9a0/doc/specs/%234191%20-%20Formatted%20Copy/twitter-poll.png)

**Comment by DHowett** [comment]
The default in defaults.json is set to true so as to not disrupt the 300k users who had installed Terminal prior to 0.11. The new user settings template sets it to `false`.

New users get the "ideal" behavior, migrated users get their "accustomed" behavior.

**Comment by srdjanjovcic** [comment]
@DHowett I was never "accustomed" to it 🙂 -- I just assumed that it was a quirk which I never wanted, but I finally decided to file a bug.
