### ISSUE TITLE
Re-enable the "open terminal here" in the background of a directory

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6414]
This is going to regress when I submit the "fix" for #6245.

You currently can't use the "Open Windows Terminal Here" shortcut when clicking on the background of a directory, due to an internal bug, MSFT:24623699. This is fixed in the latest OS builds, but hasn't been brought downlevel quite yet.

This issue is tracking the work to re-enable that functionality, once the internal bug is fixed.

**Comment by xmha97** [comment]
+1

**Comment by zadjii-msft** [comment]
@xmha97  If you'd like to "+1" this feature, the best way to do that is by hitting the 👍 button on this issue

![image](https://user-images.githubusercontent.com/18356694/96140789-ef3c8880-0ec5-11eb-82e0-30ce4977b9a7.png)

That way, you avoid unnecessarily pinging everyone following this thread. Thanks!

**Comment by timonsku** [comment]
This is great! When can we expect a release that includes this?

**Comment by zadjii-msft** [comment]
Soon<sup>TM</sup> 😜

**Comment by timonsku** [comment]
![image](https://user-images.githubusercontent.com/2370185/106185942-d9688000-61a3-11eb-8d30-9ed9545c42fc.png)
❤️

**Comment by shyney7** [comment]
> ![image](https://user-images.githubusercontent.com/2370185/106185942-d9688000-61a3-11eb-8d30-9ed9545c42fc.png)
> ❤️

Was it finally released in the Windows Store?

**Comment by Pytal** [comment]
Yeah it was go and update @shyney7!

**Comment by tiagoboeing** [comment]
I did the test now. Awesome, great work, thanks!! 😀

**Comment by libjared** [comment]
I had to navigate to the store page to get it to update, launch it once, then restart explorer.

**Comment by spiral6** [comment]
It works for me. Thanks for all the work!
