### ISSUE TITLE
"Open Terminal Here" can't be used with both the dev build and preview at the same time

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6416]
The Dev build one seems to always stomp the preview one.

* Is this because they share the same `Verb` string? _This is easy to fix_
* Or maybe is this because they share the same ClsId? _This would be annoying to fix_.

**Comment by KUTlime** [comment]
@zadjii-msft Maybe you could solve this problem prior to [Terminal v2.0](https://github.com/microsoft/terminal/milestone/22) by [OpenHere](https://github.com/KUTlime/PowerShell-Open-Here-Module) module.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/96349631-6a44a100-1076-11eb-9de5-24d6cfb96eee.png)

Yea pretty sure I can't look at that, sorry. I'm not a expert in software licensing, but I know I can't look at GPL code.

**Comment by DHowett** [comment]
Regardless of how other shell extensions do it, if they’re not packaged applications (appx/msix) they will not be encountering or have had to work around this issue and will therefore not be a good model for how to fix it.


This is a limitation in the windows platform with regards to shell extensions _in packaged applications_.

**Comment by KUTlime** [comment]
@zadjii-msft You got it all wrong. The module will not fix the problem for Windows Terminal as an application, it will solve the problem for you as a user of Windows Terminal.

**Comment by zadjii-msft** [comment]
@KUTlime Ah, thanks for the clarification. As one of the maintainers of the Terminal, I'm actually less concerned about using this myself, but more just implementing the fix for the Terminal so this bug won't affect _other users_ ☺️

**Comment by KUTlime** [comment]
@zadjii-msft Sure, no problem. Maybe my advice help someone else. 😉

**Comment by KalleOlaviNiemitalo** [comment]
I have Windows Terminal 1.4.3243.0 and Windows Terminal Preview 1.6.10272.0, and when I choose "Open in Windows Terminal" from a directory or from the background of a directory, it starts Windows Terminal 1.4.3243.0. Is that the same issue?

At HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{9F156763-7844-4DC4-B2B1-901F640F5155}, there are two subkeys:

* Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe
* Microsoft.WindowsTerminalPreview_1.6.10272.0_x64__8wekyb3d8bbwe

At HKEY_CURRENT_USER\SOFTWARE\Classes\PackagedCom\Package, there are identically named subkeys, and a few others besides. Here, each subkey has a REG_DWORD default value that may indicate the order in which the apps were installed; Windows Terminal Preview has 19 and Windows Terminal has 20. If I change the Windows Terminal value to 2 and restart Explorer, then "Open in Windows Terminal" starts Windows Terminal Preview. I think it means [Packaged COM](<https://blogs.windows.com/windowsdeveloper/2017/04/13/com-server-ole-document-support-desktop-bridge/> "COM Server and OLE Document support for the Desktop Bridge - Windows Developer Blog") prefers the package that was installed last.
