### ISSUE TITLE
[Win32 Input] Modifiers are considered input for the purposes of snapOnInput and selection dismissal

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#6423]
This means that pressing <kbd>Ctrl</kbd> to do a <kbd>Ctrl+C</kbd> will clear your selection (!)

**Comment by DHowett** [comment]
A similar issue was fixed in the WPF control when we introduced selection-dismiss-on-key.

**Comment by carlos-zamora** [comment]
Also completely breaks shift+click (ask me how I know haha)

**Comment by DHowett** [comment]
For now, use the new disabling key. Global setting:

```jsonc
"experimental.input.forceVT": true,
```

**Comment by DHowett** [comment]
Nope, that doesn't disable the key behavior. :|

**Comment by zadjii-msft** [comment]
Yikes, well, I'm on it.
