### ISSUE TITLE
Can't see what I type ("-", "%", etc are not displayed)

### ISSUE THREAD

**Issue by CIPop** [microsoft/terminal#6424]
# Environment

```none
Windows build number:  Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 1.0.1402.0

Any other software?

            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false, 
                "fontFace": "Cascadia Code PL",
                "fontSize": 8,
                "colorScheme": "Solarized Dark"
            },
```

# Steps to reproduce
Enter `git -m "123"`
Enter `test -- -- -- -- -- -- -- -- -- --`

# Expected behavior
I expect to see what I typed.

# Actual behavior
![image](https://user-images.githubusercontent.com/8635911/84101282-6e72fa80-a9c2-11ea-8c6b-3878da30a948.png)
![image](https://user-images.githubusercontent.com/8635911/84101342-94989a80-a9c2-11ea-8bf3-df52a5bddfdc.png)

**Comment by DHowett** [comment]
I cannot recommend the solarized color scheme. The defaults in PowerShell do not interact with it properly. I recommend choosing literally any other theme. Sorry!

**Comment by CIPop** [comment]
@DHowett No can do: all other schemes are literally wrong 😜. (I was also not asking for a recommendation: I was pointing out a real bug.)

Joke aside: Cmder works just fine with the same scheme in powershell:
![image](https://user-images.githubusercontent.com/8635911/84102723-15a56100-a9c6-11ea-9f9f-408958a0f4ff.png)

Any workarounds I can do right now to make it work like forcing the console foreground color?

Please re-open the issue: if you don't/can't support solarized, please remove the theme (using this bug to track). If you can fix it, please use this issue to track the resolution.

**Comment by DHowett** [comment]
(I’m assigning myself to fill in the discussion and handle this bug when I’m not on my phone.)

**Comment by DHowett** [comment]
So, there's a few issues at play here.

1. PowerShell defaults to printing parameters in "bright black" (silly name for gray); this is verifiable with `Get-PSReadlineOption` in a terminal that isn't set to Solarized right now. ![image](https://user-images.githubusercontent.com/189190/84217854-16033200-aa82-11ea-9b1b-fb307b16e607.png)
2. It looks like the official Solarized palette makes the "bright black" color invisible or barely visible: https://github.com/altercation/solarized/issues/220 https://github.com/altercation/solarized/issues/376
3. Terminal is crushing some colors out of existence (#2661, #293, don't mind the fact that 293 mentions only the background)
   * PowerShell can be mildly reconfigured to work around issues two and three (footnote 1)
4. We don't have a color bumping algorithm yet. Cmder (which is actually just ConEmu) _does_, using DeltaE101. When two colors are too close to eachother, it will nudge them until they're not quite so close. We're tracking that in #2638.

---

(1)

```
Set-PSReadLineOption -Colors @{ Parameter = "`e[38;5;239m" }
```
This will actually force parameters to be _gray_. Real gray. The way they were intended. It's equally unreadable on the standard Solarized Dark background, but it is at the very least _visible_.
