### ISSUE TITLE
Make it possible to have "closeTab" command have a confirmation

### ISSUE THREAD

**Issue by lucasmeijer** [microsoft/terminal#6426]
# Description of the new feature/enhancement

Problem: I have a keybinding for closeTab.  Sometimes I accidentally hit the key, and I lose
my tab unintentionally.  I'd like the ability to have closeTab require a confirmation dialog.

In the off chance that this is possible: I tried to RTFM and google and could not find how to do it.  In this situation, feel free to treat this as a documentation/discoverability issue :)

Loving terminal.

**Comment by DHowett** [comment]
Thanks for the request! This is tracked in /dupe #5301 :smile:
