### ISSUE TITLE
Feature Request: autocomplete for paths, files and common commands

### ISSUE THREAD

**Issue by mdtauk** [microsoft/Terminal#643]
Not sure how fiesable this is, but it would be neat to have tooltips and tab for autocompleting path folders and files to save typing.  This could also work for common commands.

**Comment by oising** [comment]
Hey @mdtauk these are features that are provided by individual applications/shells (e.g. bash, pwsh, cmd) and not by the terminal itself which is little more than a presentation environment that connect your keyboard and "screen" to the running app/shell.

**Comment by mdtauk** [comment]
I assume CMD is closed to new features what with backwards compatibility, so to implement it would have to be an intellisense feature for the new Terminal.

It could also be displayed as a tooltip or nicely rendered above the text cursor.

**Comment by oising** [comment]
Autocomplete for paths already works for cmd. Powershell/pwsh have a very good experience already with the psreadline module which ships in Windows 10 (and is available online for downlevel.) There is macro support with doskey, which also ships with windows.
