### ISSUE TITLE
CMD & Windows Terminal not the same

### ISSUE THREAD

**Issue by KingWilliam27** [microsoft/terminal#6430]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Please provide _any_ information. I can't really do anything with a blank issue like this.

**Comment by KingWilliam27** [comment]
Will send it in feedback hub Sent from Mail for Windows 10 From: Mike GrieseSent: Tuesday, June 9, 2020 5:39 PMTo: microsoft/terminalCc: KingWilliam27; AuthorSubject: Re: [microsoft/terminal] CMD & Windows Terminal not the same (#6430) Please provide any information. I can't really do anything with a blank issue like this.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zadjii-msft** [comment]
Please don't do that, Feedback Hub is very hard for us to crawl through and have an actual discussion around an issue. This github thread would be a great place for feedback.

**Comment by KingWilliam27** [comment]
Ok, will try GitHub again Sent from Mail for Windows 10 From: Mike GrieseSent: Wednesday, June 10, 2020 3:15 PMTo: microsoft/terminalCc: KingWilliam27; AuthorSubject: Re: [microsoft/terminal] CMD & Windows Terminal not the same (#6430) Please don't do that, Feedback Hub is very hard for us to crawl through and have an actual discussion around an issue. This github thread would be a great place for feedback.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
