### ISSUE TITLE
Triggering tooltip on focused terminal window (UWP) forces fullscreen Windows Remotedesktop App (UWP) to minimize

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/terminal#6432]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable): 1.0.1401.0

Windows Remote Desktop App: 10.1.1215.0
```

# Steps to reproduce

* Open fullscreen Remote Desktop session from store app
* Open Terminal
* Focus Terminal window
* Trigger tooltip on terminal tab

See video: [FocusIssue.zip](https://github.com/microsoft/terminal/files/4752632/FocusIssue.zip)

# Expected behavior
The Remote Desktop app does not minimize

# Actual behavior
Remote Desktop is minimized immediatly on opening tooltip.

**Comment by zadjii-msft** [comment]
By any chance, does this repro with tooltips in the [Xaml Controls Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab)?

**Comment by AliveDevil** [comment]
No, it is not reproducible with Xaml Controls Gallery tooltips on **1.2.15.0**.

**Comment by DHowett** [comment]
So, I found another application that uses the same architecture as Terminal. It behaves the same way: when focused, and a tooltip appears, Remote Desktop *totally nopes out*.

I'm not certain this is a platform bug . . . I think it might be Remote Desktop being very touchy as to what it considers a "foreground" window. I don't expect that they've done a lot of work for multi-monitor support, and the only way to get another window focus without actively taking it away from RD is to have two monitors.

There's not much else we can do for this one, but filing feedback on that application would almost certainly be helpful :smile:

**Comment by AliveDevil** [comment]
For reference I added this feedback to the Feedback Hub (in German):
https://aka.ms/AA8qtzs

**Comment by DHowett** [comment]
Thank you!
