### ISSUE TITLE
Perf Improvement: use DXGI flip model

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6436]
# Description of the new feature/enhancement
A brief history
What is the flip model? What is the alternative?

Prior to Windows 7, the only way to present content from D3D was to "blt" or copy it into a surface which was owned by the window or screen. Beginning with D3D9’s FLIPEX swap effect, and coming to DXGI through the FLIP_SEQUENTIAL swap effect in Windows 8, we’ve developed a more efficient way to put content on screen by sharing it directly with the desktop compositor, with minimal copies. 

This optimization is possible thanks to the DWM (Desktop Window Manager), which is the compositor that drives the Windows desktop.

# Proposed technical implementation details (optional)
Review https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/for-best-performance--use-dxgi-flip-model and linked docs.

**Comment by greg904** [comment]
I think that the terminal is already using it:
https://github.com/microsoft/terminal/blob/f32761849f716db70248854b39160cf58c22ed8d/src/renderer/dx/DxRenderer.cpp#L431

**Comment by DHowett** [comment]
Yup!
