### ISSUE TITLE
Graphics Improvement: Update to DXGI 1.6

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6437]
# Description of the new feature/enhancement
Make use of features described in https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-1-3-improvements, https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-1-4-improvements, https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-1-5-improvements, and https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-1-6-improvements. Probably should bug the DXGI team to consolidate all the features into one header instead needing to import a bunch. 

# Proposed technical implementation details (optional)
Just read the docs and make improvements as described to boost efficiency of the renderer. Related: https://github.com/microsoft/terminal/issues/6436 and https://github.com/microsoft/terminal/pull/6435, which starts the process.

**Comment by DHowett** [comment]
Hey, thanks for bringing this up! Like the performance discussion, I'd like to make sure we scope this to _actual actionable improvements_. Right now, we're restricted from taking on too much of a dependency beyond DXGI 1.2, and I'd like to see individual issues filed for things that will individually benefit the Terminal.

I had a look at the release notes for 1.2 - 1.6, and I'm not seeing anything that sticks out to me. We tried to support variable refresh rate displays, and it didn't help #649; @greg904 is introducing the 1.2 dependency and we're fine with that, but nothing else here seems salient.

I'm gonna close this one out as "non-actionable" - it's a big grab bag of APIs to read through and support, and that's not a committable unit of work.

Separate workitems like "switch to RegisterVideoMemoryBudgetChangeNotificationEvent" are more likely to be accepted, with proper justification, than "read this long list and see if any apply."

:smile:

Also,

> Probably should bug the DXGI team to consolidate all the features into one header instead needing to import a bunch.

They're versioned for a reason. Applications must _choose_ to take a dependency on a newer version. That's not gonna change!
