### ISSUE TITLE
Sort profile in tab drop-down by config filed.

### ISSUE THREAD

**Issue by Suzukaze-Yoru** [microsoft/terminal#6440]
# Description of the new feature/enhancement
Sort profile in tab drop-down by config filed.
When profiles count increase to large, sort the profile in the list field is hard to operate.
Hope to provide configurable fields to determine the order in the drop-down menu

# Proposed technical implementation details (optional)

```json
{      
  "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
  "hidden": true,  
  "name": "Windows PowerShell",        
  "commandline": "powershell.exe" ,
  "weight": 1, // eg. 1-999, If the weights are the same, the order is determined by the actual sorting in the list
 },
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571

I'd also check out #5888, which has got a spec in progress for this feature 😄
