### ISSUE TITLE
liunx shell里面 的 ctrl + u;ctrl + k无法使用

### ISSUE THREAD

**Issue by yangyongyongyong** [microsoft/terminal#6448]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
Please fill the issue template and provide enough information, otherwise literally no one can help you.

请填写 issue 模板，提供足够的用于复现的信息。

**Comment by zadjii-msft** [comment]
Exactly what @skyline75489 said. If you can provide more information, we'd be happy to reopen this issue, but there's nothing we can do with a blank issue.
