### ISSUE TITLE
ctrl + w无法关闭标签页

### ISSUE THREAD

**Issue by yangyongyongyong** [microsoft/terminal#6449]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by Suzukaze-Yoru** [comment]
多半是被其他程序占用了热键。我遇到其他的快捷键不工作的情况，自己摸索了半天，解决了。https://github.com/microsoft/terminal/issues/6439

**Comment by zadjii-msft** [comment]
The `closePane` command is bound to <kbd>ctrl+shift+w</kbd> [by default](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L311). This is because there are other commandline applications, like `nano`, that use <kbd>ctrl+w</kbd> as a keybinding themselves.
