### ISSUE TITLE
ntvdm x64 support

### ISSUE THREAD

**Issue by krezol** [microsoft/terminal#6458]
Hi,
I know there is an old NTVDM code leaked out from IA64 builds. Can we bring back the NTVDM to AMD64 and ARM64 builds of Windows 10? I have really old games I would like to play and NTVDM was the best emulator for DOS based graphic and sound modes.

**Comment by DHowett** [comment]
Sorry, no. There’s a pretty cool project called WINEVDM, though!

**Comment by DHowett** [comment]
(I appreciate that this would be really cool and great, but it would be way more engineering effort to get going for this team than would really be worth it. I’m sorry :()
