### ISSUE TITLE
Pane focus follows mouse

### ISSUE THREAD

**Issue by JelteF** [microsoft/terminal#6459]
# Description of the new feature/enhancement

Pane "focus follows mouse" feature. Instead of requiring to click to switch panes, simply hover the mouse on the pane you want to select. If this changes you select that window. This is supported by iTerm and Terminator.

@Fumler suggested this first in #1000 (it should probably be added to the list somewhere there too)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Oh, so there's #5258, but that's kinda different, isn't it. 

I'll add this to the #1000 backlog, thanks!
