### ISSUE TITLE
ctrl+alt+[arrow key] custom keybindings do not seem to be bound

### ISSUE THREAD

**Issue by Q-Mart** [microsoft/terminal#6460]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce
From a default terminal `settings.json` file, insert the following lines into the `keybindings `array:

```
{ "command": "unbound", "keys": [ "alt+down" ]},
{ "command": "unbound", "keys": [ "alt+left" ]},
{ "command": "unbound", "keys": [ "alt+right" ]},
{ "command": "unbound", "keys": [ "alt+up" ]},

{ "command": { "action": "moveFocus", "direction": "down" }, "keys": "ctrl+alt+down" },
{ "command": { "action": "moveFocus", "direction": "left" }, "keys": "ctrl+alt+left" },
{ "command": { "action": "moveFocus", "direction": "right" }, "keys": "ctrl+alt+right" },
{ "command": { "action": "moveFocus", "direction": "up" }, "keys": "ctrl+alt+up" }
```

Then, open an instance of Windows Terminal (or go to a running instance if you already have it open) and split some panes. Use `ctrl+alt+[arrow keys] ` to move between the panes
# Expected behavior

You should moving focus between panes, in the direction of the arrow key pressed (along with ctrl and alt).

# Actual behavior

Nothing, your focus remains on the pane you were already focused on.

**Comment by zadjii-msft** [comment]
_(I'm assuming that the missing ` },` at the end of the first four lines was uninitentional, and in your actual `settings.json` the lines are correct)_

Well that's weird. I can't seem to repro this locally. 

What keyboard layout are you using? Are you using any IME's?

As an experiment, does binding any of the following keys work?

* `alt+up`
* `ctrl+up`
* `ctrl+alt+up`
* `alt+p` (the `p` is arbitrary, I just wanted a key that's also definitely a character)
* `ctrl+p`
* `ctrl+alt+p`

**Comment by Q-Mart** [comment]
> (I'm assuming that the missing }, at the end of the first four lines was uninitentional, and in your actual settings.json the lines are correct)
You are correct, sorry. I've edited the comment to remove this error

> What keyboard layout are you using? Are you using any IME's?
English GB QWERTY layout, no IMEs.

Here are the results of the keybindings you asked for (✔️  means it worked, ❌ means it didn't):
-  `alt+up` ✔️ 
- `ctrl+up` ✔️ 
- `ctrl+alt+up` ❌ 
- `alt+p` ✔️ 
- `ctrl+p` ✔️ 
- `ctrl+alt+p` ❌ 

One thing I forgot to mention in the original comment (because, honestly I just forgot I was in one) is that I'm using the terminal over a remote desktop connection. It seems that RDP keyboard shortcuts begin with `ctrl+alt` ([source](https://docs.microsoft.com/en-us/windows/win32/termserv/terminal-services-shortcut-keys)) so I assume the reason `ctrl+alt` shortcuts aren't being picked up is because RDP is fiddling with something?

**Comment by DHowett** [comment]
Actually... does your keyboard have an `AltGr` key?

**Comment by Q-Mart** [comment]
Yes

**Comment by zadjii-msft** [comment]
Ah, that'll do it. The Terminal is treating <kbd>Ctlr+alt</kbd> as the same thing as <kbd>AltGr</kbd>. I think you can disable this behavior with `"altGrAliasing": false` - does that change anything?

**Comment by Q-Mart** [comment]
Aha, I don't think I'm able to test this at the moment as the the `altGrAliasing` setting is only in the preview (which I am not using)
