### ISSUE TITLE
Can't go to end of file in `less`

### ISSUE THREAD

**Issue by Geobert** [microsoft/terminal#6463]
# Environment

```none
Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Ubuntu 20.04 in Hyper-V
```

# Steps to reproduce

Run `ssh user@vm_in_hyper_v`
Run `less -RF long_file.txt`
Press "End" key

# Expected behavior

Should go to the end of the file

# Actual behavior

Nothing happened

**Comment by zadjii-msft** [comment]
Which ssh client are you using? The `ssh.exe` that comes with Windows, the WSL one, or maybe some other one? 

Do other keys work in `less`?

What keyboard layout are you using?

**Comment by Geobert** [comment]
Thank you for your answer!

I'm using ssh.exe from Windows (`"commandLine": "ssh geobert@VMUBUNTU"`).

Other keys seems to work fine (up and down, 'q' for quitting, '/' for searching).

`Home` key doesn't work either.

I'm using "bépo" as layout (French version of Dvorak)

**Comment by zadjii-msft** [comment]
> I'm using "bépo" as layout (French version of Dvorak)

Oh that might be it. Could you do a sanity check and see if those keys work in another keyboard layout?

**Comment by Geobert** [comment]
I tried switching to Qwerty, and still have the issue :(

**Comment by zadjii-msft** [comment]
Huh, that's certainly curious. Could you try a couple other things for me?

* Does <kbd>Home</kbd> or <kbd>End</kbd> work in `emacs` (on the VM)?
  - it might be useful to press <kbd>ctrl+h</kbd>, <kbd>k</kbd>, <kbd>End</kbd> in `emacs`, since that can tell you what it _thinks_ is getting pressed.
* what's the output of `infocmp` (on the VM)?

**Comment by Geobert** [comment]
in `emacs testfile`:
- `ctrl+h`: emacs says "Beginning of buffer", so I can't do `ctrl+h, k` (same in qwerty)
- `End`: emacs says "<select> is undefined" (same in qwerty)
- `infocmp`:
```
❯ infocmp
#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
        am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^?,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8, rev=\E[7m,
        ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
        rmam=\E[?7l, rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?%[;0123456789]c,
        u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by zadjii-msft** [comment]
Oh jeez I forgot what the easiest thing would be - 

could you run `showkey -a`, then press <kbd>end</kbd>?

it should look like:
```
zadjii@migrie-slaptop:~$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[F     27 0033 0x1b
         91 0133 0x5b
         70 0106 0x46


```

**Comment by Geobert** [comment]
```
❯ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[4~    27 0033 0x1b
         91 0133 0x5b
         52 0064 0x34
        126 0176 0x7e
```

**Comment by zadjii-msft** [comment]
Well that's _bonkers_. I don't know why End would be sending that - like maybe something's switching the terminal into numeric keypad mode? I thought we disabled that sequence though, and we don't even generate that sequence. So maybe `ssh.exe` is?

@j4james do you have any ideas what would cause this? It can't be conhost/terminal, since we _definitely_ [don't synthesize that sequence](https://github.com/microsoft/terminal/blob/master/src/terminal/input/terminalInput.cpp), right?

There's https://github.com/PowerShell/Win32-OpenSSH/issues/1004 and https://github.com/PowerShell/Win32-OpenSSH/issues/112, but there's very little in those issues to work with.

@Geobert what version of `ssh.exe` is this? (`ssh -V`)

**Comment by Geobert** [comment]
> @Geobert what version of `ssh.exe` is this? (`ssh -V`)

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Comment by DHowett** [comment]
Hey, this looks like the SSH input thing we fixed (somewhat) in version 1.1 preview!

**Comment by Geobert** [comment]
> 
> 
> Hey, this looks like the SSH input thing we fixed (somewhat) in version 1.1 preview!

Yay! Where can I test it to confirm?

**Comment by DHowett** [comment]
[Windows Terminal 1.1 Preview](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-1-release/)

**Comment by j4james** [comment]
I'm assuming this is sorted now, but for the record, I believe `CSI 4~` is the what DEC calls the "VT-style" sequence for <kbd>End</kbd>. It would have been the <kbd>Select</kbd> key on a DEC keyboard. On XTerm you get these sequences by enabling the "VT220 Keyboard" mode. I'm fairly sure we don't support anything like that.

**Comment by Geobert** [comment]
> 
> 
> [Windows Terminal 1.1 Preview](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-1-release/)

Thanks! I'll test that Monday (on my work computer)

**Comment by DHowett** [comment]
Yeah, actually, here's a problem:

https://github.com/PowerShell/Win32-OpenSSH/issues/1310 "OpenSSH is doing its own VT input encoding, should be using ENABLE_VIRTUAL_TERMINAL_INPUT"

They're handling the `VK_END` key [here](https://github.com/PowerShell/openssh-portable/blob/8ab565c53f3619d6a1f5ac229e212cad8a52852c/contrib/win32/win32compat/tncon.c#L329-L342):

```c++
		case VK_END:
			if (!modKey)
				WriteToBuffer((char *)SELECT_KEY, 4);
			else {
```

and sending `SELECT_KEY`

They've defined `SELECT_KEY` as...

```c++
#define SELECT_KEY                  "\x1b[4~"
```

/dup https://github.com/PowerShell/Win32-OpenSSH/issues/1310
