### ISSUE TITLE
no access through Windows store, request intuitive installation option

### ISSUE THREAD

**Issue by raydlevel5** [microsoft/terminal#6468]
The company I work for is fascist and controlling and will not allow access to downloads through the Windows Store.  I attempted to download the "installer/build file" listed on GitHub, but the method to install was not intuitive.

Can you please offer a downloadable *.msi, *.exe, or Windows Update (similar to RSAT) option(s) to install windows terminal so I can actually try it out on my Work Computer with VSCode?  Or, make the manual install process intuitive / easier.

**Comment by DHowett** [comment]
The install file on GitHub should work if you double-click it. Does that not work?

**Comment by raydlevel5** [comment]
@DHowett 

It's probably not going to work. Even though I downloaded the C++ Runtime v14 framework, it looks like our version of Windows is Version 1607 (OS Build 14393.2848).

Sad face emoji con.  :(

When I try to open the package:  Microsoft.WindowsTerminalPreview_1.0.1402.0_8wekyb3d8bbwe.msixbundle

I get:

"Cannot open app package.... The .msixbundle is not supported.  To resolve this error, update to windows 10 1809 (or later) or rebuild the app bundle as .appxbundle."

![image](https://user-images.githubusercontent.com/21373144/84416018-9f7d4600-abe1-11ea-8d72-e2c0e16fa453.png)

**Comment by DHowett** [comment]
Oh. I’m sorry; Terminal really does need Windows 1903 or greater. Build number 18362 and above.

We are evaluating our options :)
