### ISSUE TITLE
Allow opening new tab/pane in same directory

### ISSUE THREAD

**Issue by JelteF** [microsoft/terminal#6472]
# Description of the new feature/enhancement
When opening a new tab or new pane it's nice if it opens in the same directory as the pane that it's being opened from. That way you don't have to `cd` again to the same directory. 

Terminator, supports this as well as XFCE4 terminal (and probably more).

This was also suggested here: https://github.com/microsoft/terminal/issues/532#issuecomment-515180163

I guess it's nice if this is also linked in #1000 

# Proposed technical implementation details (optional)

@zadjii-msft responded to the original comment with this:
> I'm not sure that's possible. Do all processes (including pico-processes used by WSL) have a current working directory? Is it possible for us to query that value from a child process? What if there are multiple processes attached to the console simultaneously, how do we pick which process's working directory to use?
>
>Not saying that it's straight-up impossible, just that it's very unlikely and definitely deserves it's own thread to discuss and spec.

I don't think this needs to be thought of as this complex. I think all other terminal emulators simply use the cwd of the outer process. If you have spawned a subshell, the cwd of that one is simply ignored.

**Comment by DHowett** [comment]
There's also /dup #3158, the solution to which should also help this
