### ISSUE TITLE
Color Display Problems

### ISSUE THREAD

**Issue by Czile-create** [microsoft/terminal#6473]
>Windows 1909 Home, Windows Terminal 0.10.781.0

当我使用ansi转义字符输出带有颜色的背景的文字的时候，保持窗口大小则显示正常，如果此时放大窗口再缩小，那么该行后面都是此颜色背景。
When I use ANSI escape character to output the text with color background, if I keep the window size, it will display normally. If I enlarge the window (or change the size of the window ), the color background is continue until the line is end.

For example: 
```cpp
cout<<"\033[1;46mA\033[0m";
```

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
This is the same root cause as /dup #2089. Thank you!
