### ISSUE TITLE
Paste not work correctly when running vim on remote machine

### ISSUE THREAD

**Issue by BusyJay** [microsoft/terminal#6476]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Windows version: 10.0.18363.0
Windows Terminal version: 1.0.1401.0
Ssh client version: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Powershell Core version: 7.0.1

# Steps to reproduce

1. Ssh to a remote machine
2. Copy some data
3. Start an editor in the remote machine using `vim` and enter insert mode
4. Right click to paste the data copied at step 2.

# Expected behavior

Data copied at step 2 shows up in terminal.

# Actual behavior

Nothing shows up.

Just using powershell core without Windows Terminal work as expected. Using Windows Terminal but using nano instead of vim, it also works.

**Comment by WSLUser** [comment]
> OpenSSH_for_Windows_7.7p1

Can you bump to the 8.1 release?

**Comment by BusyJay** [comment]
Why? If OpenSSH is the one to blame, then why it works on powershell core without Windows Terminal?

**Comment by DHowett** [comment]
Hey, when vim is running in SSH can you still select text?

**If not**, can you try to _<kbd>Shift+Right Click</kbd>_ to paste?

**Comment by BusyJay** [comment]
> when vim is running in SSH can you still select text?

No, I can't select text.

> can you try to Shift+Right Click to paste?

It works.

And just confirm it seems be related to the remote shell. The issue only happens when remote shell is fish shell.

**Comment by DHowett** [comment]
So, this is a weird interaction between the remote app, ssh and terminal.

* Vim and a couple other applications request mouse input ("Terminal, send me info about the mouse!")
* SSH passes this through
* Terminal receives it, and starts to direct mouse input into Vim

This works great in WSL and with OpenSSH 8.
When it's working, left click/right click are supposed to go directly to Vim so it can handle them.

When mouse mode is turned off, right-click goes to the Terminal which turns it into a paste.

What happens with SSH 7.7, however is:

* Terminal sends mouse data to SSH (as requested)
* SSH **intercepts it and ignores it**
* Vim never receives it.

**Comment by BusyJay** [comment]
So mouse mode is disabled when shift is hold?

**Comment by DHowett** [comment]
Correct :)

We used to have a workaround that made it so SSH couldn’t mess up the terminal if it wasn’t going to handle mouse mode. I sent out a pull request that brings that workaround back. It should fix the symptom, but it will not make mouse mode work in SSH. 😄
