### ISSUE TITLE
Run multiple commands on startup in profiles

### ISSUE THREAD

**Issue by WesDowney** [microsoft/terminal#6477]
# Description of the new feature/enhancement
Provide the ability in `settings.json` for an individual profile to run multiple commands at startup.

Currently: `commandline` allows for one command. 

Proposed: Allow an array of commands to run. 

Sample use case: `vagrant up && vagrant ssh`. You currently can't put this in `commandline`. Allowing multiple commands easily set up in `settings.json` would make it easier to automate things. 

# Proposed technical implementation details (optional)

`commandline` could accept an array instead or a new field could be added to settings.json called `commandlines` that accepts an array. As the commands run, it should only run the next command if the previous was successful.

Currently I think the only way to run multiple commands is to make a script and tell `commandline` to run the script. This is messier because you have to deal with more files and then everything you need isn't all in one spot.

**Comment by zadjii-msft** [comment]
What if you tried something like `cmd /k vagrant up && vagrant ssh`?

**Comment by WesDowney** [comment]
This works great! Thank you

**Comment by volviq** [comment]
Unfortunately this doesn't seem to work in a Powershell commandline. 
"commandline": "%windir%/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy ByPass -NoExit -Command C:/Users/Simon/miniconda3/shell/condabin/conda-hook.ps1 && conda activate",
would fail. Is this worth another issue?

**Comment by MrTaylab** [comment]
@volviq Thank god, I found out that it works using :)
$$; 
In my case:
"cmd.exe /K C:\\Users\\User\\anaconda3\\Scripts\\activate.bat &&; conda activate env"
