### ISSUE TITLE
Mouse Input not working at all

### ISSUE THREAD

**Issue by GalHorowitz** [microsoft/terminal#6478]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

After launching the terminal, mouse input is completely broken. I can't select anything, I cant click the plus icon to create new tabs, and I can't click the three icons to minimize/maximize/exit. Right click to paste doesn't work either (but ctrl+v does)
Keyboard input is working correctly and I can still use the terminal.

## Edit:
This seems to happen because of my multi-monitor setup. The problem only happens if the terminal window is in the main monitor. Also, I don't know if this is relevant but I updated powershell to 7.0.2 this morning.

**Comment by klinki** [comment]
@GalHorowitz Are you using multiple screens?

I just noticed I have exactly the same problem, but only on one screen. I'm using multiscreen setup with 3 screens. On my primary screen, I have this problem. On the other 2 screens, everything works just fine.

**Comment by GalHorowitz** [comment]
@klinki Yes! Mouse input works in the second screen.

**Comment by klinki** [comment]
I wanted to create repro video so I moved terminal window to second virtual desktop. And suddenly it started working on all screens! :) 

So as workaround, you can move it to other virtual desktop and back and it will start working again :D

**Comment by GalHorowitz** [comment]
That fix doesn't seem to work for me.

**Comment by mjfusa** [comment]
+1 version: 1.0.1401.0

**Comment by DHowett** [comment]
Are any of you running PowerToys?

**Comment by arpsmack** [comment]
I have the same issue and I am running PowerToys.

**Comment by arpsmack** [comment]
Oh interesting, exiting out of PowerToys fixes the problem.

**Comment by GalHorowitz** [comment]
@DHowett I am. This is so weird, since this only started today, but I installed PowerToys 3 days ago. But exiting PowerToys does fix the issue.

**Comment by klinki** [comment]
@DHowett I can confirm that, I'm also using PowerToys.

**Comment by mjfusa** [comment]
Created <a href='https://github.com/microsoft/PowerToys/issues/4287'>PowerToys Blocks Mouse usage in Windows Terminal · Issue #4287 · microsoft/PowerToys</a>

**Comment by DHowett** [comment]
Thank you! /dup https://github.com/microsoft/PowerToys/issues/4287

**Comment by crutkas** [comment]
@DHowett I think this is still some variant of microsoft/terminal#3325 which is where it can be reproduced without PT running.

**Comment by nickjj** [comment]
Closing PT works for me too, but I also want to add that I've never seen this happen with the MS terminal + PT running unless I run GIMP (the image editor). The lack of mouse input ends up affecting both the MS terminal and various GIMP toolbox icons and exiting PT fixes it for both.
