### ISSUE TITLE
Menu to select-all, copy and paste

### ISSUE THREAD

**Issue by divenex** [microsoft/terminal#6479]
# Description of the new feature/enhancement

Include in the menu an option to select-all, copy and paste text, also providing the corresponding keyboard shortcut. It is far from obvious how to select-all text, given that the usual [CTRL]+A does not work and copy and paste with the mouse does not work in a standard way: selecting some text and right-clicking does not open a menu to copy the text. Currently, these commands are totally non-discoverable, except by Googling them.

**Comment by DHowett** [comment]
Thanks for the request! We're tracking this in /dup #3337.
