### ISSUE TITLE
Retain last screen location, size, etc. & restore on startup

### ISSUE THREAD

**Issue by mws-rmain** [microsoft/terminal#6480]
# Description of the new feature/enhancement

The terminal window appears in a default location & default size when it starts. If the window is resized &/or re-positioned then closed. It returns to the same default location & size when it is restarted.

# Proposed technical implementation details (optional)

The terminal should remember it's last location on the desktop (NOTE: this should INCLUDE which screen in case the PC has more than one), and it's size. The location & size should be restored when the terminal app is re-started.

Using the existing syntax, implement option:
 "initialPosition": last
to remember & restore last positon (Note that 'last' in this context would also remember the 'screen' in case of multiple screens).

Implement option:
"initialSize": last
to remember & restore last size. Note that this could be extended to replace the "initialRows" and "initialCols" options with the syntax:
"initialSize": <rows>,<cols>

**Comment by DHowett** [comment]
Thanks for the request! We're going to solve this holistically with /dup #766
