### ISSUE TITLE
[Win32 Input] PrintScreen counts as 'input' and forces a snap; bad for screenshooting the terminal

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#6481]
When you take a screenshot, input snaps.

**This is also true for <kbd>Win+Shift+S</kbd>**

I think we need to snap only on CharacterHandler, or something? When a key _actually generates a character_.

**Comment by zadjii-msft** [comment]
But what about arrow keys? Home/end/pgup/pgdn? Those seem like snapping keys as well...

I could do characters + [the above keys]. There might even be something convenient about ENHANCED_KEY that I could use...
