### ISSUE TITLE
Terminal does not respond to keyboard input

### ISSUE THREAD

**Issue by Koschei-Project** [microsoft/terminal#6482]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
wsl --list --verbose
  NAME           STATE           VERSION
* Debian         Stopped         1
  fedoraremix    Stopped         2
```

# Steps to reproduce

Open windows terminal, attempt to type or otherwise interact with the shell.

# Expected behavior

Input is directed to the program.

# Actual behavior

Entering keystrokes/etc does not cause any visible change to the chosen program (whether psv5, command prompt, or a wsl distro). (IE the shell prompt loads+displays initial information, but is otherwise unresponsive). Launching outside of terminal produces expected behavior. The terminal window itself responds properly to mouse clicks (can open new tabs, etc).

**Comment by oising** [comment]
Very odd. What other software are you running concurrently in Windows?

**Comment by DHowett** [comment]
On closer inspection, I think this is /dup #4448
