### ISSUE TITLE
Extend planned hyperlink capability to arbitary text

### ISSUE THREAD

**Issue by idleberg** [microsoft/terminal#6484]
# Description of the new feature/enhancement

I'm well aware of existing feature requests to make URLs clickable (e.g. #574). However, there are [many terminal emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) that also support hyperlinks on arbitary text.

**Example:**

```sh
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

Screenshot from iTerm2:

![Screenshot 2020-06-12 at 23 18 59](https://user-images.githubusercontent.com/1504938/84547114-1e1dd480-ad03-11ea-906d-25162d799b90.png)

This feature is especially popular in the NodeJS world, as you can tell from [`terminal-link`](https://www.npmjs.com/package/terminal-link) close to 3 million weekly downloads.

**Comment by DHowett** [comment]
Thanks for the request! This is tracked in /dup #204
