### ISSUE TITLE
Question: Is there a way to get keybinding and convert it to string (text)?

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#6487]
# Description of the new feature/enhancement
Is there a way to get the `appkeybinding` item (e.g. shortcut "Ctrl+T") and convert it to string so we can display it as tooltip/dialog label etc? Thank you in advance!

**Comment by greg904** [comment]
Maybe you can use this:

https://github.com/microsoft/terminal/blob/c0ffc9b6dce9b632c868b6584a0f1c8c9dd1df93/src/cascadia/TerminalApp/TerminalPage.cpp#L1406-L1411

**Comment by zadjii-msft** [comment]
Even better, I'd try `KeyChordSerialization::ToString`. That's what I'm using to similar effect in the command palette:
https://github.com/microsoft/terminal/blob/dd684cbca1002806f4b8b80d80178942f0bcbb81/src/cascadia/TerminalApp/TerminalPage.cpp#L106-L110

**Comment by Chips1234** [comment]
Okay thanks!

**Comment by Chips1234** [comment]
So do I replace `command` with the command (example Copy)?

**Comment by Chips1234** [comment]
@zadjii-msft. So, can you please give me an example (maybe for the copyText shortcut?) Thanks!

**Comment by Chips1234** [comment]
And what should I call the method? `winrt::wstring`?

**Comment by zadjii-msft** [comment]
I'd probably just make a method on `AppKeyBindings` that exposed the map of `KeyChord`->`ActionAndArgs`, and I'd do something like this:

```c++
for (const auto& keyAndArgs : _settings->GetKeybindings().GetKeyMap())
{
    const auto& chord = keyAndArgs.first;
    const auto& actionAndArgs = keyAndArgs.second;
    if (keyChord) 
    { 
        auto label = KeyChordSerialization::ToString(keyChord);
        // Do something with the label here. 
        // EX: Maybe append it to a text box:
        _myTextBox.Text(fmt::format(L"{} - {}", _myTextBox.Text(), label));
    }
}
```

That would be easier than building every possible action and then checking if that action is bound to something.

**Comment by Chips1234** [comment]
Yes, but for the dialog, I think that it is better for a individual one. Thanks anyways!

**Comment by Chips1234** [comment]
Thanks!

**Comment by Chips1234** [comment]
@zadjii-msft I figured out the Dialog Construct from run-time part but can you maybe go to my [branch ](https://github.com/Chips1234/terminal/tree/dev/chips1234/dialog-to-show-all-shortcuts)on my fork and demonstrate the `KeyChordSerialization::ToString` part? I learn much better if I get to see it in action. Thank you so much!

**Comment by zadjii-msft** [comment]
@Chips1234 Sure. 

[This code is a good sample](https://github.com/microsoft/terminal/blob/81eb13542abac72094ce0371a45f99768add9f61/src/cascadia/TerminalApp/AppLogic.cpp#L340-L382) of how to add runs of text to a dialog dynamically at runtime.

Then, I'd just do the code I mentioned above to retrieve all the `KeyChord`'s and convert them into strings of text. You can see something similar over in [this branch](https://github.com/microsoft/terminal/blob/b90cc38f0ffb371f16a3bb5f306f01ddf72ddc5e/src/cascadia/TerminalApp/TerminalPage.cpp#L107-L110), though, you won't be setting `KeyChordText`, you'll probably just be setting `run.Text(KeyChordSerialization::ToString(keyChord));`

**Comment by Chips1234** [comment]
Thanks

________________________________

**Comment by Chips1234** [comment]
And I put the `run.text` where?
