### ISSUE TITLE
Text between box drawing characters is rendered aliased (???)

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#6488]
When I run this in PowerShell (7),

```
"`e[30;47m`u{2500} What `u{2500}`e[m"
```

the text comes out without antialiasing. It looks like it's being drawn with FillGeometry just like a box drawing glyph.

![image](https://user-images.githubusercontent.com/189190/84561566-4e18a800-ad02-11ea-89b8-fe4cc58127bb.png)

If I flip the colors, it comes out antialiased.

![image](https://user-images.githubusercontent.com/189190/84561569-58d33d00-ad02-11ea-83c0-56b763950ae4.png)

To verify my theory that `What` was becoming part of the box drawing run, I put together a debug tool that turns glyph runs into graphviz documents.

![image](https://user-images.githubusercontent.com/189190/84561756-ff6c0d80-ad03-11ea-8e76-447cafa1dc83.png)

Unfortunately, it doesn't look like it's so simple.

**Comment by DHowett** [comment]
It _doesn't_ happen with midnight commander, which uses a lot of box drawing glyphs... because however MC is rendering, they get broken into _different CustomTextLayouts_.

![image](https://user-images.githubusercontent.com/189190/84561813-68538580-ad04-11ea-84d0-56147a81a335.png)

![image](https://user-images.githubusercontent.com/189190/84561816-6f7a9380-ad04-11ea-8cc4-b047c2c21478.png)

**Comment by miniksa** [comment]
what the what.

**Comment by wackoisgod** [comment]
Should be noted that i have the same issue in #6603 and when I run the same `"`e[30;47m`u{2500} What `u{2500}`e[m"` in 1.0 it renders correctly for me but in 1.1 it renders incorrectly as show by @DHowett

**Comment by DHowett** [comment]
@skyline75489 looks like this regressed with 94eab6e39, but I can't figure out why (since box drawing detection happens after the analysis code you changed!)

**Comment by DHowett** [comment]
Okay, this is because we're not populating `_glyphClusters` when text is "simple". When we go to split the run later (**we split runs for things other than text analysis!**), we try to remap the glyph clusters around the split.

Inevitably, we end up falling into DrawGlyphRun with `run.glyphCount` = 0 because `_SplitCurrentRun` stomped the glyphCount because there was no glyph cluster mapping.

Somehow *magically* we end up doing a "get raw geometry, draw" for the entire string which very handily hides the glyph clustering bug!

This fix _works_ but I do not believe it is correct:

```diff
diff --git a/src/renderer/dx/CustomTextLayout.cpp b/src/renderer/dx/CustomTextLayout.cpp
index d19d2d0c3..395a58224 100644
--- a/src/renderer/dx/CustomTextLayout.cpp
+++ b/src/renderer/dx/CustomTextLayout.cpp
@@ -336,6 +336,7 @@ CustomTextLayout::CustomTextLayout(gsl::not_null<IDWriteFactory1*> const factory
             for (size_t i = glyphStart; i < _glyphAdvances.size(); i++)
             {
                 _glyphAdvances.at(i) = (float)_glyphDesignUnitAdvances.at(i) / designUnitsPerEm * _format->GetFontSize() * run.fontScale;
+                _glyphClusters.at(i) = static_cast<UINT16>(i);
             }

             run.glyphCount = textLength;
```

I'm worried about that "magical" rendering fallthrough. With this fix, are we striking the text twice -- once as a geometry and once as a glyph run?

(I commented out the glyph run drawing, and I think the answer is _no_.)

**Comment by skyline75489** [comment]
I don't think this is correct, either. But right now I can not think of a better fix for this.

I kinda hate the fact that "we split runs for things other than text analysis". Is this a final thing or we are gonna change that in the future.

**Comment by skyline75489** [comment]
Per communication with @reli-msft I suggest fixing it by considering all runs containing box-drawing chars as complex. It's a quick fix. It should work as expected, with reasonable performance penalty.

@DHowett

**Comment by reli-msft** [comment]
A proper fix should change `_isEntireTextSimple` into an enum to indicate _how complex_ the text run is, and use that to determine the itemize passes to be enabled and whether we need "glyphing". For now, @skyline75489's fix would work and won't cause a lot of performance lost, since the frequency of box-drawing characters is low.

**Comment by DHowett** [comment]
So, thinking a bit more about this.

I'm going to revert this in the 1.1 and master, so that we can bring it in correctly later. Folks have reported some crashes, and I'd prefer an expedient patch fix for servicing, and a fully-baked solution later :smile:
