### ISSUE TITLE
implement web browser-like shortcuts

### ISSUE THREAD

**Issue by avermeir** [microsoft/terminal#6490]
# Description of the new feature/enhancement

Cfr. Title

# Proposed technical implementation details (optional)

New tab with ctrl+T
Switch tabs with ctrl + PgUp / PgDown
Close tab with ctrl + W
...

**Comment by j4james** [comment]
You can change the key bindings to whatever you want. See the documentation here:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings

**Comment by DHowett** [comment]
Indeed! Thanks, James.
