### ISSUE TITLE
Remove highlights on the directories when running "ls -ltr"

### ISSUE THREAD

**Issue by vow7779** [microsoft/terminal#6496]
# Environment

```none
Windows Terminal Version: 1.0.1401.0
```

# Steps to reproduce

Once successfully installed wsl, navigate to my mount (c or d) and type "ls -ltr". I have a gist of my settings.json file here in case you want to take a look at it:

https://gist.github.com/vow7779/488f4a0c25a28ae0cd7e55d633bee18d

# Expected behavior
Would like to see highlights removed and have plain text or have a way to remove it from user end. 

# Actual behavior
All the folders under c,d drives that have 755 permissions has a highlight to it. In my case, yellow and it makes the text hard to read. Please see screenshot attached. I have seen others having it in green.

![zshsnip](https://user-images.githubusercontent.com/66241362/84580480-0aeb3180-adf5-11ea-982e-82656c287008.png)

Thanks!

**Comment by DHowett** [comment]
These colors are being produced by _ls_. By default, _ls_ will color directories with mode `777` using attributes `34;42`. You can confirm this by checking the contents of the environment variable `LS_COLORS` for the `ow=` entry.

This `ow` entry is generated from the `OTHER_WRITABLE` dircolors entry.

To suppress colors on _ls_, you should clear the `LS_COLORS` environment variable, run `ls --color=never`, *or* simply reconfigure dircolors.

For more information, see `man dircolors`.

**Comment by DHowett** [comment]
(In short: Terminal is not detecting "directories" and coloring them. It is being asked to display colors `34;42` and complying to the best of its ability.)
