### ISSUE TITLE
Add "include" directive to JSON 

### ISSUE THREAD

**Issue by kellytrinh** [microsoft/terminal#6502]
# Description of the new feature/enhancement

Suggest to add an #include or similar to the settings JSON.

I have in a bunch of profiles that launch SSH to connect to difference machines I am using.  The list of machines is different from my laptop / devbox.   Right now I cannot just take the settings JSON and put in another computer because it will mess up the profiles list.

This will allow me separate the profiles part (which may be computer specific) from the keybindings (which would be common).

# Proposed technical implementation details (optional)

I have a common settings JSON that I can take between commons and add/remove profiles on a seperate file on each specific computer.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2303 for more discussion.

/dup #2303
