### ISSUE TITLE
Shift+letters stopped working in a tab

### ISSUE THREAD

**Issue by AgentMC** [microsoft/terminal#6503]
I have opened the Terminal with the default Powershell.
Then I received a Skype call.
After the Skype call ended, I returned to the terminal, but to my surprise I was not able to type with SHIFT key pressed.
This means, Terminal outputed NOTHING when I pressed SHIFT + a letter, e.g. SHIFT + a --> no letter typed.
I was able to type when releasing shift key.  Other modifiers also worked fine. Also, the Shift+special keys worked fine, e.g. shift+. --> > was outputed fine.
When I switched to another app (cmd.exe outside of Terminal), or created a new Tab with PS within Terminal, the Shift + letters was working fine. After returning to problematic tab, it stopped workinng again. 

The workaround is obvious - just create a new tab, but the issue is weird.

**Comment by DHowett** [comment]
I believe the input stack changes in #4999 that came out in 1.1 make this better. That's _very_ strange, though.

If you hit this again, would you let us know?

**Comment by ValZapod** [comment]
Same here. Сору pasting a file (to insert its path) also does not work (as it inserts only little letter, so drive C is missing). Caps Lock fixes it (you are still not able to type with Shift though).

**Comment by ValZapod** [comment]
This is a duplicate https://github.com/microsoft/terminal/issues/9450 fix is also there!! Thanks.
