### ISSUE TITLE
Ghost/dummy window appears in the task bar (DesktopWindowXamlSource)

### ISSUE THREAD

**Issue by ocalvo** [microsoft/terminal#6507]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable):
Windows Terminal Preview
Version: 1.1.1611.0

Any other software?
```

# Steps to reproduce
1. Start Windows Terminal on PowerShell
2. Start wsl

# Expected behavior
Only one mini window should show on the task bar

# Actual behavior
Two mini windows are shown in the task bar:
<img width="336" alt="2020-06-14 (1)" src="https://user-images.githubusercontent.com/2091582/84608486-91405b80-ae67-11ea-90eb-b66bcd042143.png">

The second window shown is the CoreWindow, this is a known issue with Xaml Islands version 1.0.
The workaround is to hide the core window hWnd by calling `::ShowWindow(hWnd, SW_HIDE)`

**Comment by DHowett** [comment]
I don’t believe this happens every time; the extra window usually goes away after it’s been parented. Do you know what causes it to stick around?

When hosting an island, we only have two windows: the terminal Win32 window, and the “interop HWND” we get from DWXS. Since the interop HWND is the one we parent to the terminal window, I’m worried that hiding it will hide our XAML content. 

I’m hoping you know a way to get the best of both worlds :)

**Comment by zadjii-msft** [comment]
Hey @ocalvo, any idea if the root xaml islands bug was solved in Windows 11? I haven't seen this in quite some time now, so maybe it got fixed on your side? 

I suppose even in Windows 10, we should be `ShowWindow(hWnd, SW_HIDE)`'ing the `_interopWindowHandle` around here: https://github.com/microsoft/terminal/blob/main/src/cascadia/WindowsTerminal/IslandWindow.cpp#L311, yea? Will that really not hide our XAML content?

**Comment by DHowett** [comment]
I think W11 shipped with the DWXS window hidden by default!

We should do the hide still -- and yeah, it shouldn't hide our XAML content.

**Comment by zadjii-msft** [comment]
Easy enough to test out, thanks for the confirmation!

**Comment by MouriNaruto** [comment]
Here is my solution for that and hope to give you some help:

```
        // Prevent showing the dummy/empty/ghost DesktopWindowXamlSource window
        // in the task bar.
        // Reference: https://github.com/microsoft/terminal/issues/6507
        // Reference: https://github.com/microsoft/microsoft-ui-xaml/issues/6490
        // Fixes: https://github.com/M2Team/NanaZip/issues/225
        // For also fixing the window with empty content due to CoreWindow is
        // not exist issue, create a host window without message loop is a
        // better workaround.
        g_CoreWindowHostWindowHandle = ::CreateWindowExW(
            0,
            L"Mile.Xaml.ContentWindow",
            L"Mile.Xaml.CoreWindowHostWindow",
            0,
            CW_USEDEFAULT,
            0,
            CW_USEDEFAULT,
            0,
            nullptr,
            nullptr,
            nullptr,
            winrt::get_abi(winrt::Grid()));
        winrt::check_pointer(g_CoreWindowHostWindowHandle);
```
https://github.com/ProjectMile/Mile.Xaml/blob/c5c7af247f7182b94e3e64ae467b8bd823df5a1c/Mile.Xaml/Mile.Xaml.cpp#L519-L540

Kenji Mouri

**Comment by nathpete-msft** [comment]
I'm also experiencing this on launch at startup or just via opening the app normally from the start menu or taskbar.

Windows Terminal 1.18.902.0
Windows 10 22H2 19045.2728

**Comment by samkearney** [comment]
I am having this issue on the newest version of Windows Terminal as of this writing, 1.18.2822.0. I believe it started happening after my company recently pushed an update to our workstations to Windows 10 22H2 build 19045.3570.

**Comment by j4james** [comment]
@samkearney I think the new instance of this bug is being tracked in #16183 now. You may want to follow up there.
