### ISSUE TITLE
Find with color highlights and find with regrex match support

### ISSUE THREAD

**Issue by lpstudy** [microsoft/terminal#6509]
# Description of the new feature/enhancement
1. Currently, to find the text in terminal, it only highlights only one that matches. Do we consider to highlights all the matched texts?

2. Currently `find` do not support regrex expression, do we consider to support it?

3. Bug report
Current `find` dialog in one panel does not disappear even I change the focus to other panels. This may lead to ESC does not work for closing `find ` dialog.

# Proposed technical implementation details (optional)
![image](https://user-images.githubusercontent.com/2081195/84621479-3d884d80-af0d-11ea-82a8-0918bc6ce1fe.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3920 for more discussion.

/dup #3920
