### ISSUE TITLE
enhancements request

### ISSUE THREAD

**Issue by d10deepu** [microsoft/terminal#6510]
1. Would love to see default sdks loaded for gloud and AWS
2. Would you able to add a RDP option for windows servers as a terminal tab?
3. Inbuilt password manager would be great.

**Comment by DHowett** [comment]
Thanks for the request! sorry, though... these are all outside the scope of a Terminal. We don’t handle passwords, we only handle text (no graphics), and we aren’t planning on offering AWS or Google Cloud integration.
