### ISSUE TITLE
Ability to Add a Horizontal Separator in Profile List

### ISSUE THREAD

**Issue by ameer1234567890** [microsoft/terminal#6512]
I suggest to include ability to add a horizontal separator in profile list, similar to the existing separator line just above Settings option. This can be done via a `{ "lineBreak": "horizontalLine" }` or similar entry in `settings.json`. This would be helpful to especially separate types of profiles such as terminal, ssh, etc.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
