### ISSUE TITLE
Merge or split tabs into different Windows Terminal instances

### ISSUE THREAD

**Issue by butchiki** [microsoft/terminal#6514]
# Is it possible to allow tabs to be separated from its main Windows Terminal instance like the tabs in browser or to be inserted to an existing terminal? I hope someone can add this feature of tab management in Windows Terminal. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
