### ISSUE TITLE
Windows Terminal Azure Cloud Shell Token Failure

### ISSUE THREAD

**Issue by PtMcBride** [microsoft/terminal#6515]
I've been having to re-authenticate multiple times through-out the day within Azure Cloud Shell Bash, receiving the following error:

A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'cc-3f22786f-6968b465df-2frxg'

"Could not retrieve token from local cache."

Is this essentially as expected? Most of the time it occurs when the Tab is closed, and I hit 0 to re-establish connection with my saved Tennant.

**Comment by DHowett** [comment]
This looks like another instance of /dup #2371. Thanks for the info!
