### ISSUE TITLE
pasting using Windows' builtin clipboard manager (windows+v) doesn't work

### ISSUE THREAD

**Issue by omartin2010** [microsoft/terminal#6521]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.900]
Windows Terminal version (if applicable): 1.0.1402.0
```

# Steps to reproduce

Copy something in the buffer. Copy something else (so that you have two or more things in the buffer). Use Win+V to paste. The pop up window will appear for pasting something else than the last copy.

# Expected behavior

I expect what I selected to be pasted.

# Actual behavior

I see ^V printed on the console if I'm in a cmd.exe tab, and nothing if i'm in WSL.

**Comment by DHowett** [comment]
Clipboard History works by synthesizing a <kbd>Ctrl+V</kbd> event. If you do not have <kbd>Ctrl+V</kbd> bound to `paste` (which is now in the user default settings as of v1.0, you will get the traditional terminal treatment of _sending 0x16, the control character for ^V._

**Comment by omartin2010** [comment]
excellent, thank you! It works. I carried an older settings than the v1.0.
