### ISSUE TITLE
EndPaint outside of lock for DxEngine

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#6523]
The EndPaint command will naturally send all the queued drawing commands onto the underlying rendering target/bitmap/surface. Since all the data has already been captured and queued, there's no real sense in holding the lock on the I/O thread while the draw commands are performed. So this should probably move into the `Present` phase. But it will have to be reconciled with the invalid rectangle/scroll things that are usually done at `EndPaint` time.

**Comment by zadjii-msft** [comment]
🤔

Why did we never do this? This might have just sorted out like, a bunch of the miscellaneous deadlocks we're tracking (ala #12607)

**Comment by lhecker** [comment]
D2D has an internal batch size limit for draw commands, so given enough text on the screen, it'll try to call D3D functions potentially many times before `EndPaint` is even called.
That said, it can't hurt to merge this. Reduces the chance for our issue even further...

**Comment by zadjii-msft** [comment]
Note to future self: this seemingly did not noticeably improve Terminal perf. Maybe it helps conhost perf, but I didn't have the cycles to further sanity check if this wouldn't just explode (esp. over RDP). 

I'm closing this tab out now, see y'all in two more years when I reopen this 😜

**Comment by lhecker** [comment]
Oh, we do this now in AtlasEngine!
