### ISSUE TITLE
til::bitmap for dxengine should just be X=1 if we're painting one full row 

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#6524]
There's a lot of wasted work twiddling bits if we're setting an entire row worth of them at the time. Which we are to ensure ligatures work. That's fine, but let's save ourselves the bit twiddling time.

**Comment by DHowett** [comment]
Moved into 2.0. @miniksa if this didn't have the impact we were hoping, feel free to close.

**Comment by miniksa** [comment]
> Moved into 2.0. @miniksa if this didn't have the impact we were hoping, feel free to close.

I'll try again before discarding this. I might have been taking crazy pills the day I didn't see a change.

**Comment by zadjii-msft** [comment]
@lhecker this relevant for Atlas engine? If it's not, I'm tempted to close it out as "the DxEngine is less than maintained"

**Comment by lhecker** [comment]
It's not relevant. AtlasEngine doesn't just invalidate entire rows at a time, but holds just a single `[begin, end)` range of rows to invalidate. If you modify row 0 and N-1 then the entire viewport is invalidated (but that's fine because it's seldom and still fast).
