### ISSUE TITLE
[accessibility] Add support for a text selection mode

### ISSUE THREAD

**Issue by ofek** [microsoft/terminal#6528]
# Background

I have a [severe neuromuscular disorder](https://en.wikipedia.org/wiki/Spinal_muscular_atrophy) which makes physical activities extremely strenuous, such as moving the mouse around to copy/paste.

[ConEmu](https://github.com/Maximus5/ConEmu) supports this feature which is why I'm using it but I'd like to switch to a more performant terminal with configuration not in XML or a GUI. Therefore, I have opened a feature request here and to [Alacritty](https://github.com/alacritty/alacritty/issues/3855) 😄 

# Description of the new feature/enhancement

Entering text selection mode can happen in 2 ways:

1.) click and drag (highlight) somewhere with the mouse
2.) press any arrow key while holding shift

At this point you can release the left-click (1) or shift (2). The cursor will change somehow (ConEmu makes it a yellow block) and you can now move anywhere with just the arrow keys. To highlight you then hold shift while using arrow keys similar to the highlighting logic of holding left-click while moving the mouse.

I should emphasize that both methods of entering text selection mode are necessary. If you want to copy something no longer in view, having only 2.) means you'd have to hold the up arrow for a *long* time. With 1.), you have the option to PgUp as needed then initiate with the mouse.

Copying can happen in 2 ways:

1. the standard shortcuts, which **will not** exit text selection mode
1. pressing Enter, which **will** exit text selection mode

Exiting text selection mode can occur at any time by pressing Esc

# Proposed technical implementation details (optional)

No idea!

**Comment by DHowett** [comment]
Thanks for the request! We're actually tracking this in #715 (keyboard-only text selection, navigation), and it's currently in specification review at #2840! There's a sidecar specification that calls out support for a modal keyboard selection mode analogous to the traditional console's "mark mode" in #5804.

/dup #715.

/cc @carlos-zamora for use case visibility.

**Comment by ofek** [comment]
@DHowett That's great, thank you!
