### ISSUE TITLE
how can i use 'sz' and 'rz' tools to transfer file from linux to windows ?

### ISSUE THREAD

**Issue by kelaicai** [microsoft/terminal#6529]
when i send a file name as 'a',it's behavior like this: 
![image](https://user-images.githubusercontent.com/21305726/84726628-e7281700-afbf-11ea-833f-664712b52beb.png)

it's happend on :
  Windows Terminal 0.11.1251.0

help plz!

**Comment by DHowett** [comment]
Our terminal does not support ZModem yet. Sorry. /dup #1999

**Comment by DHowett** [comment]
Also, you are using an old version of Terminal and you should upgrade to the most recent version.

**Comment by blissnmx** [comment]
when support ?

**Comment by blissnmx** [comment]
It`s bean three years
