### ISSUE TITLE
Support specific split pane distribution from command line arguments

### ISSUE THREAD

**Issue by amitbern-aws** [microsoft/terminal#6533]
Hi,
Is there any way to support the following split pane distribution from command line argument?

![image](https://user-images.githubusercontent.com/65345580/84805146-7ce99380-b00c-11ea-8451-c90866b014b2.png)

I've tried the following:
wt.exe -p "Ubuntu-18.04" ; split-pane -H -p "Ubuntu-18.04"; split-pane -H -p "Ubuntu-18.04"
But it didn't work because the the split pane is always splited in relative to the previous pane.

Any idea how?

**Comment by zadjii-msft** [comment]
Not yet - for that we'll need to implement `focus-pane`, which is being tracked in #5464. 

/dup #5464
