### ISSUE TITLE
Quick Access to certain location

### ISSUE THREAD

**Issue by gkgaurav31** [microsoft/terminal#6535]
Often we switch between different locations a lot. It would be great to have something like a "quick access bar" use which we can directly cd to a certain location.
Something similar to "alias" as in Linux would also be helpful.

**Comment by zadjii-msft** [comment]
How would you propose this works with something like `vim` or `emacs`, where `cd <some path>␊` isn't the command for changing directories?

**Comment by gkgaurav31** [comment]
The idea is around navigating to different locations in general. 
For example, I needed cmd to start at a specific location when I open it in the Windows Terminal. I was able to do it using this:

            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0cxyzd-35be-5f56-a8ff-afxyza6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe \/k cd c:\\sandbox",
                "hidden": false
            }
Similarly, it would be nice to switch to other locations easily. (Does not necessarily have to be via the command line). Maybe we can just have a drop down menu where I have the recent or most used locations, and easily switch to that.

**Comment by zadjii-msft** [comment]
Why wouldn't you just use the `startingDirectory` property instead of passing it in the commandline?

I think this will probably end up being solved by #1571/#5888, but I want to make sure I understand the use case fully
