### ISSUE TITLE
Integrated Browser

### ISSUE THREAD

**Issue by gkgaurav31** [microsoft/terminal#6536]
It would be really helpful if we can integrate any browser with the Terminal (in a different tab maybe). That will avoid having to go to another Window to test the application (for example).

**Comment by zadjii-msft** [comment]
Oh man, I tried doing this about a year ago. This is what started #1080. As it turn out, we can't use a WebView with the system XAML Islands, so we actually _can't_ do anything like this until WinUI 3.0 lands, and we can use that implementation of XAML Islands. 

It's a perfectly great idea, so I'm gonna throw it in the #4000 pile.

**Comment by DHowett** [comment]
I'm inclined to NAK this one, actually. We will _never_ be able to host a browser, even as an extension, that is going to be viable for use as a browser with all the right navigation and UI/UX affordances. I don't even think that it's right for an extension author to go down this road, and I don't think we should encourage that by leaving this issue open as even a suggestion.

Browsers serve an incredibly specific purpose, and that purpose overlaps not even a little with that of a terminal emulator.

**Comment by WSLUser** [comment]
I think what's really desired here is simply the ability to combine browser tabs with Terminal tabs like was originally happening with Sets. An extension that supported this would be ideal. If this occurred, the use-case above (a very common one at that) would simply be a matter of switching the tab instead of window. The keybinding for switching tabs would ideally also be supported in this scenario, though that should be left to the browser to decide, not Terminal (which I believe just follows normal Windows conventions by default).

**Comment by DHowett** [comment]
But, like... Terminal is _one component_ of a development environment. It's an important one, yes, but it's not going to grow to encompass typescript compilation or project workboard management or team chat or any number of other things that there are very good dedicated tools to do. Browsers are incredibly diverse and divisive, and we're better served by letting users _choose_ (and mixing and matching) the components of their development environments than by trying to be the be-all end-all tool.

Even VSCode, which _does_ purport to handle a bunch of those things, doesn't seem to have an ordained browser preview extension -- and it's **literally** a browser with a text editor inside it!

**Comment by DHowett** [comment]
So, I'm gonna close this but I'm **not** going to lock it. Let's continue the discussion.

My word is not, and cannot ever be, truly final :smile:

**Comment by oising** [comment]
Zawinski's law of software envelopment: Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can.
