### ISSUE TITLE
switchToTab keybinding doesn't work after renaming tab

### ISSUE THREAD

**Issue by pdaquino** [microsoft/terminal#6539]
1. Configure the settings file to have keybindings like the following:

`        {
            "command" : {
                "action": "switchToTab",
                "index": 0
            },
            "keys" : 
            [
                "alt+1"
            ]
        },`

2. Start Terminal 1.1 and open two tabs. Switch to the 2nd tab.
3. Right click one of the tabs and choose "Rename Tab".
4. Press alt+1.

Expected: Terminal switches to the first tab.
Actual: No effect until I click on the console part of the window (as if to give focus).

**Comment by DHowett** [comment]
This is another instance of /dup #5750. Thanks for the report!
