### ISSUE TITLE
WSL with tmux: lost cursor after resize

### ISSUE THREAD

**Issue by chunliu** [microsoft/terminal#654]
Repro steps: 
![tmux](https://user-images.githubusercontent.com/2128551/57505461-99ec6700-7322-11e9-8575-73e49d729a11.gif)

There is no problem without tmux.

**Comment by DHowett-MSFT** [comment]
I can't reproduce this any longer. Can you still repro it?

**Comment by chunliu** [comment]
No, I don't see this problem anymore as well. It's gone several versions before I think. The issue can be closed.

**Comment by DHowett-MSFT** [comment]
Thank you!
