### ISSUE TITLE
Ctrl+C doen't stop a program in windows terminal powershell console.

### ISSUE THREAD

**Issue by xiaosong0911** [microsoft/terminal#6540]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable):
Version: 1.0.1401.0

Any other software?
Windows built-in ssh:
PS> ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

# Steps to reproduce

1. open a powershell window.
2. try to connect a ssh sever with ssh, press Ctrl+C to quit when it ask for password.
3. run a endless program, for example `ping bing.com /t`, which will not quit by itself. Ctrl+C doesn't end the program.

# Expected behavior

Ctrl+C should end the running program.
# Actual behavior

Ctrl+C does not end the program.

**Comment by xiaosong0911** [comment]
After I report this bug, it suddenly disapears... I can not reproduce the problem now... it's so wierd

**Comment by finsterdexter** [comment]
What version of Powershell were you using? Powershell Core v7? Something else?

**Comment by DHowett** [comment]
> I am seeing this issue in Terminal, as well, while running a long running task. The tab seems to crash with [process exited with code 3221225786] when I press Ctrl-C, and the program keeps running in background.

This is a totally different issue. You have either installed PowerShell Core via Scoop or as a dotnet global tool before v7.0 came out. More info here (dotnet) https://github.com/PowerShell/PowerShell/issues/11314 and (scoop) https://github.com/lukesampson/scoop/issues/3634.

I'm going to mark this comment and yours as "off-topic"; if you continue running into this issue after investigating the dotnet/scoop bug reports, please _file a new issue._

**Comment by DHowett** [comment]
@xiaosong0911 Are you using any other software in the affected tabs? Sometimes when you run "ssh" in the same window, ssh disables <kbd>Ctrl+C</kbd>.

**Comment by xiaosong0911** [comment]
> @xiaosong0911 Are you using any other software in the affected tabs? Sometimes when you run "ssh" in the same window, ssh disables Ctrl+C.

I only used "ssh" and "ping" as described in the steps to reproduce. I have no idea how ssh can disable `Ctrl+C`.

BTW, I noticed this problem also occurs in the windows' built-in powershell window, so it is probably a bug of powershell or ssh rather than windows terminal.

**Comment by DHowett** [comment]
Yes, there is an API that globally disables Ctrl+C for the whole console window. SSH uses it, sometimes, and does not enable it again.

**Comment by DHowett** [comment]
Thanks!
