### ISSUE TITLE
SSH connection password rememberance feature along with storing list of connections

### ISSUE THREAD

**Issue by krishlakshmanan** [microsoft/terminal#6541]
# After ssh connection to the machine is made, the user enter password has to be remembered with the user acknowledgement. Providing a list of ssh connection would make the user not to use the other ssh clients.

**Comment by harmjanwestra** [comment]
If you're using SSH on linux, these things can be arranged using ~/.ssh/config, private/public key pairs and an ssh-agent.

**Comment by fischerdouglas** [comment]
I would like to see som integration with Windows Password Vault, like iTerm2 does with MacOS Keyring.

**Comment by fischerdouglas** [comment]
I mentioned some suggestions for issues like this
https://github.com/microsoft/terminal/issues/5880

https://github.com/microsoft/terminal/issues/5916

**Comment by DHowett** [comment]
Thanks for the request! For the reasons outlined in 5880 and a couple others, I'm gonna close this out. Please follow 5880 and 5916 (parent issue #4000) for more info.

/dup #5880
