### ISSUE TITLE
Search indexing for each console you have in your terminal. (And abbreviations)

### ISSUE THREAD

**Issue by 3rikk** [microsoft/terminal#6543]
# Description of the new feature/enhancement

Currently, if my default console is Ubuntu, and i want to use Powershell, i have to open the terminal and then select powershell from the dropdown menu. This is fine, but being able to search in the start menu and go directly to powershell, or whatever else i plan to use, would be nice. For example:
Searching "Windows Terminal Powershell" would give the option to directly open a Powershell Tab in WT. Same would go for "Windows Terminal Azure" or "Windows Terminal CMD" etc etc.
A step further would be abbreviations, for example "wt" would open windows terminal on default, "wt ps" would be the same as "Windows Terminal Powershell", and this could exist for the other consoles too like "wt cmd" or "wt wsl". 
# Proposed technical implementation details (optional)
**Edit:** I think a good way to determine what abbreviations are used would just be to make them be set in the settings.json file, as an entry like **'**"indexAbbreviation": "pscore"**'**.
<!-- 
<!--

**Comment by DHowett** [comment]
You can already run "`wt`" from the run dialog or start menu, and when we implement #576 you'll be able to pin and automatically find profiles from the start menu.
