### ISSUE TITLE
Windows Terminal (Preview) - App List and Taskbar icon doesn't match with the actual icon.

### ISSUE THREAD

**Issue by sayedarifuddin** [microsoft/terminal#6544]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19645.1]
Windows Terminal version: 1.0.1402.0
```
 
# Expected behavior

The icon should include the **PRE** tag like following.
![image](https://user-images.githubusercontent.com/47639147/84910020-31042080-b0d8-11ea-8690-3ca72be2b239.png)

# Actual behavior

But it doesn't come with the **PRE** tag in the App List and Taskbar icons.
![image](https://user-images.githubusercontent.com/47639147/84910244-76c0e900-b0d8-11ea-90be-b3f223dd501b.png)
![image](https://user-images.githubusercontent.com/47639147/84910259-7a547000-b0d8-11ea-8e99-3b9ba6198b35.png)

**Comment by DHowett** [comment]
This was an intentional design decision to remove the text from the `PRE` label when it would be too small to be read.
