### ISSUE TITLE
Reset command on Ubuntu 20.04 does not work as expected

### ISSUE THREAD

**Issue by thanhnguyen2187** [microsoft/terminal#6547]
![](https://user-images.githubusercontent.com/27758849/84932727-f06bcd80-b0fe-11ea-8faf-13ad35ad4511.gif)

# Environment

```Microsoft Windows Version 10.0.19041.330
Windows Terminal Version 1.0.1401.0
Ubuntu 20.04
```

# Steps to reproduce

- Open Windows Terminal
- Create a new Ubuntu 20.04 tab
- Write a few lines
- Write the command `reset`

# Expected behavior

The screen will be reset. The cursor will be back on the first line.

# Actual behavior

The cursor is stuck in another line.

**Comment by DHowett** [comment]
Weirdly, another reset issue just came up an hour ago. /dup #6545
