### ISSUE TITLE
.clang-format?

### ISSUE THREAD

**Issue by fghzxm** [microsoft/terminal#655]
Will we decide upon a `.clang-format` so that C++ code can be less messy (it is a bit as of 6c98fc1)?

**Comment by zadjii-msft** [comment]
I believe @adiviness has been looking at the feasibility of this. He can weigh in more.

**Comment by adiviness** [comment]
I think I still have a clang-format file laying around somewhere, and someone has also made a PR with one in it. We would like it to match the current style of the codebase as much as possible. I can look more into this early next week.

**Comment by DHowett-MSFT** [comment]
This was finished.
