### ISSUE TITLE
Terminal should support dynamic backgrounds, themes, etc.

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#6553]
It would be great if Terminal was able to, for example, honor key events, including supporting inclusive events throughout the year

For example, PrideShell profile during Pride Month :)

![image](https://user-images.githubusercontent.com/961950/84957071-4e70c480-b0af-11ea-860b-7933e266ad2d.png)

Further, it'd be awesome if users could configure Terminal with a dynamically updating theme which included a color scheme background image, etc. to reflect different events/periods throughout the year. Spring, Summer, Fall, Winter themes, Pride, Black History Month, Oscar Night, Leap Day, etc.

**Comment by DHowett** [comment]
This would be an excellent opportunity for an extension developer to make a name for themselves!

Closing in favor of #4000.

**Comment by DHowett** [comment]
We need to tread carefully. We don't need another VS Code incident.
