### ISSUE TITLE
Titlebar click events don't work on one of the monitors.

### ISSUE THREAD

**Issue by saisandeepvaddi** [microsoft/terminal#6554]
I have two monitors. When I open Windows Terminal, none of the buttons like new tab, drop-down or even minimize,maximize,close buttons don't work in primary monitor. I have to move Windows Terminal to another monitor where everything is fine.
![windows terminal monitor issue](https://user-images.githubusercontent.com/13838175/84957742-d237aa80-b0c9-11ea-8bb8-54e2dcc72c0e.gif)

# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

1. Use dual monitor
2. In one of the monitors, unable to click any button on the titlebar.
3. Move to another monitor, it works.

# Expected behavior
1. Windows Terminal should work regardless of what monitor it is active.

**Comment by DHowett** [comment]
Chance you've got PowerToys installed?

**Comment by saisandeepvaddi** [comment]
Yes, I have PowerToys installed.

**Comment by saisandeepvaddi** [comment]
Now when I checked PowerToys, it is also behaving same. I guess that should go to PowerToys repo.

**Comment by saisandeepvaddi** [comment]
Can confirm if I exit PowerToys, Windows Terminal is working.
