### ISSUE TITLE
Narrow emoji >=U+10000 make WriteCharsLegacy sad ("wrong character insertion when scrolling to bash history")

### ISSUE THREAD

**Issue by francogp** [microsoft/terminal#6555]
_Notes from https://github.com/microsoft/terminal/issues/6555#issuecomment-646206984_

```
[0x4]   OpenConsoleFullPDB!IsGlyphFullWidth + 0x9   
[0x5]   OpenConsoleFullPDB!WriteCharsLegacy + 0x2a3                  <<<<<<<<<<<<<<<<<
[0x6]   OpenConsoleFullPDB!WriteBuffer::_DefaultStringCase + 0xaf   
[0x7]   OpenConsoleFullPDB!WriteBuffer::PrintString + 0x16   
[0x8]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::AdaptDispatch::PrintString + 0x61   
[0x9]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::OutputStateMachineEngine::ActionPrintString + 0x42   
[0xa]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString + 0x197   
```

We're calling `IsGlyphFullWidth` once for each half of the surrogate pair. You can well imagine how nicely that works out.

---

# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1402.0

Using WSL Ubuntu LTS version 20.04
```

# Steps to reproduce

1. Install Microsoft Terminal from Windows Store. Keep the default settings.
2. Enable WSL and install Ubuntu 20.04 from Windows Store.
3. Start Ubuntu 20.04 via WSL2.
4. When bash prompt appears, run exactly this (from the first character until the end):
```bash
echo 🔥🌡  
```
the utf-16 equivalent (just to see the exact characters)
```none
\u0065\u0063\u0068\u006f\u0020\ud83d\udd25\ud83c\udf21\u0020\u0020
```
5. Press enter to see the result.
6. Press key UP 
7. Press key DOWN
8. Go to step 6. 

# Expected behavior

switch from 
```bash
echo 🔥🌡  
```
to 
```none

```
THIS PROBLEM CANNOT BE REPRODUCED ON OTHER TERMINAL EMULATORS 

# Actual behavior
character 'e' inserted at the beginning
 ![](http://g.recordit.co/nrmLGQqtYF.gif)

**Comment by zadjii-msft** [comment]
Ho boy, is the thermometer supposed to be wide, and we're treating it as narrow?

This problem repros in conhost as well as Terminal, so it's not necessarily a conpty miscommunication.

**Comment by j4james** [comment]
I think it's the other way around - it's supposed to be narrow but we're treating it as wide. This could perhaps be because conhost uses different width calculations to WT. My understanding was that this was by design, for backwards compatibility reasons (see issue #4604). But that might result in the conhost cursor being in a different position to whether WT expects it to be. Perhaps we need a way to tell conhost to use the standard width calculations when in a conpty session (assuming that is the problem).

**Comment by DHowett** [comment]
I think this is more likely a width disagreement between _bash and conhost_, actually, coupled with a somewhat “recent” regression where BS can move halfway into a double-width cell.

**Comment by j4james** [comment]
> I think this is more likely a width disagreement between _bash and conhost_

Yeah, but that's to be expected if conhost doesn't use a standard width measurement. You can get the same result with the `U+FFFD` character from my original bug report - you just need to be using a font that renders it as double-width (e.g. MS Gothic).

![widechar](https://user-images.githubusercontent.com/4181424/85048842-cc0a0280-b18b-11ea-8f42-e4a40b184800.gif)

So unless conpty is triggering different behaviour, conhost's view of character widths is assumedly going to be dependent on whatever font is used by default, which is not necessarily in sync with bash or the Windows Terminal renderer.

**Comment by DHowett** [comment]
Huh, we did work to make sure conpty and WT treat ambiguous width glyphs as narrow _always_. cf #2066 for more info on that choice (which I believe is the correct one). Perhaps we regressed that and they disagree once more? Hmm

**Comment by DHowett** [comment]
(Conpty was actually circumstantial: the ambiguous width lookup fell through to the VT renderer, which threw up its hands and said “friend you don’t have a font, so it’s narrow.”)

**Comment by DHowett** [comment]
Ah shit.

```
[0x4]   OpenConsoleFullPDB!IsGlyphFullWidth + 0x9   
[0x5]   OpenConsoleFullPDB!WriteCharsLegacy + 0x2a3   
[0x6]   OpenConsoleFullPDB!WriteBuffer::_DefaultStringCase + 0xaf   
[0x7]   OpenConsoleFullPDB!WriteBuffer::PrintString + 0x16   
[0x8]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::AdaptDispatch::PrintString + 0x61   
[0x9]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::OutputStateMachineEngine::ActionPrintString + 0x42   
[0xa]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString + 0x197   
```

We're calling `IsGlyphFullWidth` once for each half of the surrogate pair. You can well imagine how nicely that works out.

**Comment by j4james** [comment]
I was just going to say I thought it might have something to do with surrogate pairs. The fix I was proposing in #4604 didn't help in this case (although it does fix `U+FFFD`).

**Comment by DHowett** [comment]
_how did we ever expect this to work 😦 _

**Comment by DHowett** [comment]
I'm going to make this the master issue for "narrow emoji that are also surrogate pairs make life very sad"

**Comment by francogp** [comment]
also, some glyph are rendered wrong. for example
![image](https://user-images.githubusercontent.com/2739706/85190756-e4644500-b291-11ea-9f5a-19081910ae9d.png)
the top image is from other terminals, and native linux.
The bottom one is from Windows terminal. Note the sizes...
The font is [JetBrains Mono NF](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
)

**Comment by DHowett** [comment]
@francogp this isn't quite the same issue; that glyph is specified as being "narrow" (only taking up one cell), but it's also considered an emoji. We could render it better, but that's more likely #1472.
