### ISSUE TITLE
When opening wt from explorer in the address bar it should set the current directory as working directory

### ISSUE THREAD

**Issue by allancm** [microsoft/terminal#6559]
When the explorer is used, you can write a command in the address bar.
If you use cmd.exe or only cmd, a new window with the cmd is opened and the current directory of that console is pointing to the directory where the explorer is pointing.
It would be very useful if you write wt.exe or only wt, and the new windows terminal is opened with the current directory as the directory where the explorer is pointing.
Currently the window terminal is heading to a fixed directory no matter where you started the command "wt".

# Proposed technical implementation details (optional)

I would use something similar as launch the powershell.exe -NoExit -command "& {Set-Location EXPLORERPATH}" but with the wt.exe,

![Step1](https://user-images.githubusercontent.com/2113118/84983134-5bb0a200-b0f5-11ea-82cd-99afb60dd979.png)
![Step2](https://user-images.githubusercontent.com/2113118/84983136-5c493880-b0f5-11ea-8d8d-66e47a0fac5f.png)
![Step3](https://user-images.githubusercontent.com/2113118/84983139-5d7a6580-b0f5-11ea-82e8-90d9e8d1e943.png)
![Step4](https://user-images.githubusercontent.com/2113118/84983141-5e12fc00-b0f5-11ea-8fae-1c7ce6b5280a.png)
![Step5](https://user-images.githubusercontent.com/2113118/84983142-5e12fc00-b0f5-11ea-8dfe-0f3e8e957937.png)
![Step6](https://user-images.githubusercontent.com/2113118/84983143-5f442900-b0f5-11ea-9b56-a4f8d6da5eb8.png)

Thanks in advance

**Comment by DHowett** [comment]
So, there’s a limitation here that we’ve worked around by enforcing a startup directory as part of each profile. You can run WT in the current directory by entering `wt -d .`

More info in #3547 (PR Description)
