### ISSUE TITLE
windows terminal can't show the plot  drawed by python matplotlib or R ggplot2 using wsl linux

### ISSUE THREAD

**Issue by zihaoxingstudy1** [microsoft/terminal#6560]
windows terminal  can't show the plot  drawed by python matplotlib or R ggplot2 using wsl . when i use wsl2 connected on xshell,  xshell can show the plot drawed by python or R

**Comment by zadjii-msft** [comment]
I'm not sure how `matplotlib` draws its diagrams, probably with sixel graphic, right? If so, then this is a /dup of #448
