### ISSUE TITLE
Login script needed

### ISSUE THREAD

**Issue by lppsuixn** [microsoft/terminal#6561]
# Description of the new feature/enhancement

Define a login scipt,and auto run it when ssh successful.
Because I should connect services by relay.So I want to use different profile with different scripts like 'ssh service1' or ' ssh service2' .

**Comment by WSLUser** [comment]
You can already create different ssh profiles. Copy and create a separate profile under PS/CMD/WSL/etc. and use the `commandline` option to specify `ssh username@host`.

**Comment by DHowett** [comment]
You can also configure the remote shell’s “profile” (note; different concept than a WT profile) to run commands on startup. Bash, zsh, fish, (almost all linux/Unix shells) and powershell all support this.

Keeping the configuration on the remote machine makes it durable no matter how you access it.
