### ISSUE TITLE
open wt from intellij idea issue

### ISSUE THREAD

**Issue by Ikki-Dai** [microsoft/terminal#6563]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
WT : 1.0.1401.0
Microsoft Windows [版本 10.0.18363.752]

Any other software?

intellij idea
```

# Steps to reproduce

set console in `intellij idea`
1. File -> Settings -> Tools ->Terminal 
2. input shell path : `wt -p "Windows PowerShell" `, then `APPLY`
3. click `Terminal` tab which at the bottom of window

# Expected behavior

wt window pop out and start at project dir

# Actual behavior
show error as below in `Terminal tab`
```
Cannot open Local Terminal
Failed to start [wt -p "Windows PowerShell"] in E:/xxxx/xxx

Error running process: CreateProcess failed. Code 2

See your idea.log (Help | Show Log in Explorer) for the details.
```

**Comment by zadjii-msft** [comment]
Does `idea.log` have anything relevant in it?

As an experiment, does opening another windowed application, like `notepad` as the "shell" work? I'd bet that because the Terminal isn't a _console_ application, IntelliJ prevents it from launching as the "shell"

**Comment by Ikki-Dai** [comment]
yes, as idea.log print `java.io.IOException: Couldn't create PTY`

**Comment by zadjii-msft** [comment]
Huh, that's certainly curious. Does it work with another application with commandline arguments, maybe something like `powershell --noprofile`?

Maybe they're internally escaping the commandline weirdly. Does something like `wt -d c:\users` work? Or even `wt -d .`? I'm thinking that the `"` in the commandline might be confusing IntelliJ

**Comment by fmajestic** [comment]
You need to add .exe to wt and quote it. 
To start in the project folder, add `-d .`

Full command:
```
"wt.exe" -p "Windows PowerShell" -d .
```

I used to have the same problem trying to run bash in the integrated terminal. Can't remember where i found this fix, it was ages ago.

For reference, I am running:
```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
```

**Comment by DHowett** [comment]
Thanks for the info! Looks like something we don’t have control over :) so I’m going to close this out.

**Comment by Ikki-Dai** [comment]
@fmajestic thanks for ur solution
