### ISSUE TITLE
Use split panes by default

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6564]
Hello,

I need split panes by default:

![image](https://user-images.githubusercontent.com/23485114/85012040-aa9f1b80-b177-11ea-871e-ab2a804b384b.png)

What changes should I make to the `settings.json`?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22multiple+profiles%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #756 for more discussion.

/dup #756
