### ISSUE TITLE
Add an option for "scrollbarState" to make vertical scroll bas always wide, as if it is hovered by mouse

### ISSUE THREAD

**Issue by vmalu** [microsoft/terminal#6565]
# Description of the new feature/enhancement
Add an option for "scrollbarState" to make vertical scroll bar always wide. 
This should work as with the "visible" option but with scroll bar is always wide, as if it is hovered by mouse.
Reason: it is hard to point precisely the scroll bar when it is a narrow line and then wait when it is expanded. 
This is the only thing where wt is not as good as cmd yet. In other features the wt exceed the cmd.

# Proposed technical implementation details (optional)
Add an option for "scrollbarState" to make vertical scroll bar always wide, like "visibleExpanded". 
This should work as with the "visible" option but with scroll bar is always wide, as if it is hovered by mouse.

**Comment by vmalu** [comment]
Closed by mistake

**Comment by vmalu** [comment]
I'm aware about system-wide option to make scrollbars always visible, but in console applications it is more need to scroll so it would be convenient to have a separate setting.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #3454 for more discussion.

/dup #3454
