### ISSUE TITLE
Some text not displayed when the screen scrolls

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#6566]
# Environment

Windows build number: Version 10.0.18362.778
Windows Terminal version (if applicable): 1.0.1401.0

# Steps to reproduce

1. Open a bash shell in Windows Terminal.
2. Press <kbd>Enter</kbd> a few times until you've scrolled off the page.
3. Execute the command `printf "\e[2AHello\n\n\n"`

# Expected behavior

I'd expect to see "Hello" output on the line above the prompt I started from.

![image](https://user-images.githubusercontent.com/4181424/85034160-affd6580-b179-11ea-90a4-b7606e29284f.png)

# Actual behavior

The "Hello" is not displayed.

![image](https://user-images.githubusercontent.com/4181424/85034195-b986cd80-b179-11ea-97d9-5ca710b5122b.png)

If you resize the WT window, the text will suddenly appear, so it seems that the conhost buffer does at least know it's there (and it works in a standalone conhost shell).

My guess would be that it isn't invalidating the right area, so that part of the buffer isn't being refreshed over the conpty pipe. It only seems to happen when the newlines are making the window scroll, so that may have something to do with it.

**Comment by zadjii-msft** [comment]
Hey this one looks like it's fixed now. It's a little over a year old, so pretty hard to say for sure what fixed it sadly 😕
