### ISSUE TITLE
Use "default" system sound for terminal bell/beep, as opposed to "critical".

### ISSUE THREAD

**Issue by sirocyl** [microsoft/terminal#6568]
I feel that the "Critical Stop" sound, also known as "SystemHand" or, as referenced [here](https://github.com/microsoft/terminal/blob/10bc1a6532d40d917c24956f97d5d08808bc7061/src/interactivity/win32/windowproc.cpp#L678), `SND_ALIAS_SYSTEMHAND`, is too "critical"/high-priority of an audible feedback for a console beep - it plays out for too long and doesn't 'attack' as quickly as a neutral/default UI bell sound would.

As a counterexample, Ubuntu uses a low and quick hollow "thunk" sound. Mac has Sosumi, Funk, and so forth, for the Terminal beep.

I'd suggest replacing that in the Windows Terminal with `SND_ALIAS_SYSTEMDEFAULT` - the "Default Beep", as it's called in the Sound control panel.

(I'm not sure why Critical Stop was chosen here - if there is a persuasive reason (Human Interface Guidelines, for instance) then it's probably best to stay as such.)

I'll be making a PR which changes that one line, and I'll refer to this issue in the PR.

Usecases: cmd.exe, Ubuntu/WSL, rarely PowerShell.
`ver` is `Microsoft Windows [Version 10.0.18363.900]`
`conhost.exe` is as shipped, with latest Windows Updates installed - file/product version is `10.0.18362.1`.

**Comment by DHowett** [comment]
So, Terminal doesn't actually _support_ the bell right now. The code you've identified is part of the vintage console host--and I'm not about to change how belling works in the vintage console host.

This will become meaningful when we _do_ finally implement bell for Terminal: /dup #4046

**Comment by DHowett** [comment]
(I appreciate that you're working on a PR for this :smile: I just wanted to get out ahead of it!)

**Comment by DHowett** [comment]
:+1:

We offer no warranty for this, but if you want to replace _conhost.exe_ (system32, subject to system file protection) with _openconsole.exe_ built out of this repo. . . I can't stop you!

_(it's the exact same code that gets built and packaged with Windows, it can just move a whole lot faster because it's out here in the open!)_
