### ISSUE TITLE
Profile start and end commands

### ISSUE THREAD

**Issue by tajetaje** [microsoft/terminal#6569]
# Description of the new feature

In my case it's starting/ending a headless virtual machine before ssh-ing into it, but there are a number of cases where opening a particular profile can have prerequisite commands before being useful. I suggest that new profile options be added to automate running a command when a profile is opened and when that profile is closed. An additional suggestion would be a setting to determine if these commands are run per tab or per profile, otherwise a field for each.

# Proposed technical implementation details

1. The user opens windows terminal
2. The user opens a profile with all of these options set
3. Once the profile is opened the on-open command(s) are automatically run (à la .bashrc)
4. The user opens another tab and if the user has set per-tab commands, windows terminal runs those
5. The user closes these tabs and the on-close command(s) are run.

**Comment by intractabilis** [comment]
Via what mechanism commands are issued? Windows Terminal just starts a process, it cannot tell this process what to do. For example, imagine `"commandline": "doom_console"`, how Windows Terminal can tell `doom_console` to execute `iddqd`?

**Comment by DHowett** [comment]
Yeah, that's the thing I'm worried about. There's a bunch of different ways to do this for each different shell, and I think it's best left to the _shell_.

For PowerShell, you can...

```
powershell -noexit -c startup_thing ; powershell ; exit_thing
```

or just customize `Profile.ps1`

for bash, `.bashrc` and `.bash_logout`

for CMD,
don't use cmd, it is not good

This isn't something I'd like to get Terminal mired in figuring out. I'm gonna close this one out as "not terribly actionable" :smile: sorry!
