### ISSUE TITLE
[Preview] "compact" tabs setting is only applied to tabs when the config is reloaded

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#6570]
[Linking: microsoft/microsoft-ui-xaml#2711]

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Windows Terminal version (if applicable): 1.1.1671.0 (Preview)
```

# Steps to reproduce

* Grab the new Windows Terminal Preview off the MS Store.
* Given a config like this:
```json
  "alwaysShowTabs": false, // true also replicates the issue
  "showTabsInTitlebar": false, // true also replicates the issue
  "tabWidthMode": "compact",
```
* Launch Terminal Preview
* No tabs are visible
* Control-Shift-T to open a new tab
* (!) Two tabs are visible, their titles are visible, ala `"tabWidthMode": "titleLength"`
* Control Tab back and forth, the titles remain visible
* Open the config file, and save it _without changes_. (`Ctrl-, Ctrl-s`, or `Ctrl-, :wq` as you prefer)
* Active tab unchanged, the other tab is now compacted down to its icon.
* Control Tab back and forth, only the active tab shows its title.

... And now it gets weird

* Open a new tab
* Three tabs are visible, the third one is active and shows its title, the other two compacted.
* Switch tabs with Control-Tab
* (!) The third tab's title _remains_ visible, the active tab's title is also now visible.

![image](https://user-images.githubusercontent.com/138397/85056093-f71f4100-b1e1-11ea-8e43-d464595617fa.png)

* Switch back to the third tab with Shift-Control-Tab
* Third (active) tab's title is visible, the other tabs are now compacted.
* Switch back with to the first tab with Control-Tab
* Open the config file, and save it _without changes_.
* Active tab unchanged, the other tab is now compacted down to its icon.

# Expected behavior

"compact" mode applies to tabs created since the config file was last saved.

# Actual behavior

"compact" mode applies only to tabs open when the config file was last saved.

----

This took a while to test. I kept launch Windows Terminal by muscle memory. -_-

**Comment by DHowett** [comment]
Linking: https://github.com/microsoft/microsoft-ui-xaml/issues/2711

**Comment by DHowett** [comment]
Thanks for the report :smile:
