### ISSUE TITLE
Emojis display is wider than in a Linux terminal

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/terminal#6579]
# Environment

```none
Windows 10 2004 / PS 7.0.2 / WT 1.1.1671.0
```

# Steps to reproduce

Execute this command in PowerShell:
```
irm https://wttr.in/seattle?format=v2 -UserAgent curl
``` 

# Expected behavior

The display of emojis is more compact such that the right most `|` aligns with the rest of the output.

# Actual behavior

![image](https://user-images.githubusercontent.com/5177512/85066115-97864e80-b16b-11ea-9fd7-5a12dcc0325c.png)

**Comment by DHowett** [comment]
Looking at these glyphs:

![image](https://user-images.githubusercontent.com/189190/85072125-67d84600-b16d-11ea-998d-e0a83fe3a393.png)

An emoji being 3+ cells wide (or centered within a 3-cell range) is an indicator that they're using variation selectors or zero-width joiners.

```
0073120 00000020 000026c5 0000fe0f 00000020
0073140 000026c5 0000fe0f 00000020 000026c5
0073160 0000fe0f 00000020 000026c5 0000fe0f
0073200 00000020 000026c5 0000fe0f 00000020
0073220 000026c5 0000fe0f 00000020 000026c5
0073240 0000fe0f 00000020 000026c5 0000fe0f
0073260 00000020 000026c5 0000fe0f 00000020
0073300 000026c5 0000fe0f 00000020 000026c5
0073320 0000fe0f 00000020 000026c5 0000fe0f
0073340 00000020 000026c5 0000fe0f 00000020
0073360 000026c5 0000fe0f 00000020 000026c5
0073400 0000fe0f 00000020 000026c5 0000fe0f
0073420 00000020 00002601 0000fe0f 00000020
0073440 00000020 0001f326 00000020 00000020
0073460 0001f326 00000020 00000020 00002601
0073500 0000fe0f 00000020 00000020 0001f326
0073520 00000020 00000020 00002601 0000fe0f
```

(Here, U+FE0F is "Variation Selector 15" or "prefer emoji presentation")

We don't handle zero-width glyphs well.

/dup #1472
