### ISSUE TITLE
Building from Command Line

### ISSUE THREAD

**Issue by Tembocs** [microsoft/Terminal#658]
I tried to build Terminal from command line by running `msbuild OpenConsole.sln`. After a successful build I could not see the WindowsTerminal.exe or anything to start it. The other executables either started the cmd or something else in cmd.

If I build from command line with `msbuild OpenConsole.sln` is this enough command to build the Cascadia project as well? Where is the  Is it a must to build from Visual Studio to have Cascadia project built?

**Comment by SneWs** [comment]
Have you read https://github.com/microsoft/Terminal/blob/master/tools/README.md ? It will guide you through the process of building from command line.

**Comment by zadjii-msft** [comment]
Please refer to #489, as there's a lot of good information in that thread.
