### ISSUE TITLE
[Translation] A misused word in Chinese l10n when a nonexistent WSL distribution is accessed

### ISSUE THREAD

**Issue by DaZui** [microsoft/terminal#6582]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software? N/A
```

# Steps to reproduce

First of all, you have to have a Chinese (Simplified) system. 

Try to trigger a WSL distribution that is not present:

1. Open Windows Terminal;
2. Remove a distribution;
3. Try to use tab to open bash of the distribution you just removed.

# Expected behavior

It should notice user that the distribution is missing. 

The notice should be "发行版" (Linux Distribution) but not "分布" (mathematical distribution).

# Actual behavior

![image](https://user-images.githubusercontent.com/5781966/85078581-56516700-b18a-11ea-8f6f-47f69acc70e8.png)

**Comment by DHowett** [comment]
Thanks for the report! `wsl.exe` produces this message, so I moved it to the WSL issue tracker.

/dup https://github.com/microsoft/WSL/issues/5442
