### ISSUE TITLE
How can I set an environment variable for a new tab?

### ISSUE THREAD

**Issue by intractabilis** [microsoft/terminal#6585]
I am trying to start MinGW command prompt, i.e. MSYS2's `bash` with environment variable `MSYSTEM=MINGW64`. `/etc/profile` takes different routes depending on its value. What I tried so far:

- Point `commandline` to a python script that sets environment and starts `bash`. It completely messes up keyboard for some reason.
- Use a powershell script where `"commandline" : "pwsh -Command file.ps1"`. First, bash for some reason screwed reading the history. Second, `pwsh` doesn't exit after exiting `bash`, the tab stays.
- I tried using a `cmd` script with `"commandline" : "cmd -c script.cmd"`. The tab just shows the `cmd` prompt, no `bash` is started.

I am lost. It should be something simple.

**Comment by DHowett** [comment]
So, we definitely should add a way to set environment variables as part of a profile. Thanks!

For your immediate concern, though... would it be better to use:

```
"commandline" : "C:/msys64/msys2_shell.cmd -defterm -no-start -mingw64",
```

It looks like msys2_shell.cmd sets up everything (and more!)

**Comment by intractabilis** [comment]
Specifying just a `.cmd` as `commandline` makes the tab show this on exit from `bash`. Though, it will work as a workaround. Thank you.

![изображение](https://user-images.githubusercontent.com/45959195/85186825-1c4a9880-b250-11ea-9554-813c59829436.png)

**Comment by DHowett** [comment]
That's surprising. Does that happen if you use `cmd /s /c path\to\cmd\file.cmd -args` instead?

You can suppress the exit warning by setting `closeOnExit` to `always` for that profile.

**Comment by intractabilis** [comment]
`cmd /s /c` works. Thanks!!!
