### ISSUE TITLE
Background image doesn't change even if I change the property

### ISSUE THREAD

**Issue by Agent24015** [microsoft/terminal#6588]
Hi, I Have Changed the background image property but it doesn't change the background image,

`    {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
		"backgroundImage":  "C:\\Users\\Administrator\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\img.jpg"
            }`

![image](https://user-images.githubusercontent.com/63150826/85102837-17232480-b223-11ea-89b7-c95b8ec83a18.png)

**Comment by WSLUser** [comment]
Did you restart Windows Terminal? Hot-reloading isn't enabled yet for this setting.

**Comment by DHowett** [comment]
What? It _absolutely is_.

**Comment by Agent24015** [comment]
I have tried restarting Terminal, rebooted my system and tried uninstalling and
reinstalling and set the same property. It still doesn't work!

**Comment by Kironb** [comment]
I had the same issue after updating to windows version 2004. I am not sure as to why this is happening but I know I can still change the image for my powershell instance.

A workaround to display the image for me was to run wsl through Powershell.

For example, for your settings, I would change it to something like:
{
 "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}", 
"hidden": false,
 "name": "Ubuntu", 
"commandline": "powershell.exe -Command \"wsl\"", 
"backgroundImage": "C:\\Users\\Administrator\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\img.jpg"
 } 

If Ubuntu isn't your default wsl instance you can just add a -d flag for the distribution you want to run.

**Comment by DHowett** [comment]
Are either of you using `antialiasingMode` `cleartype`?

**Comment by Kironb** [comment]
No, I am not setting `antialiasingMode`.

**Comment by DHowett** [comment]
But is @Agent24015 using `antialiasingMode`?

**Comment by Agent24015** [comment]
Nope, I am not using it

**Comment by zadjii-msft** [comment]
Hey sorry for the delay, but what happens if you try using an image path that's _not_ under `C:\Users\Administrator\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState`? What if you try moving the image to just `C:\Users\Administrator\img.jpg`?

**Comment by Agent24015** [comment]
Thanks @zadjii-msft, I did that and it worked, but not sure what the problem actually is

**Comment by Agent24015** [comment]
I am closing this issue now.

**Comment by Lukortech** [comment]
The background still doesn't apply even if the image is in another directory in my case.
![image](https://user-images.githubusercontent.com/26508593/140514769-a7879f9b-020b-4c89-90fa-d78c1ad4c784.png)
