### ISSUE TITLE
[Build Error] Cannot open include file: 'winrt/TerminalApp.h': No such file or directory

### ISSUE THREAD

**Issue by toekhaing** [microsoft/Terminal#659]
I have read the same issues and I found it will need to install WinRT C++ library . 
I have installed the WinRT C++ library from both vsix and Nuget. It still get the same errors. 
![image](https://user-images.githubusercontent.com/6739256/57522132-e72eff80-7347-11e9-871c-f43c4c47373f.png)

**Comment by zadjii-msft** [comment]
Please refer to #489. It also looks like you're using VS2019, so #565 might have some help in it as well.

**Comment by xa0082249956** [comment]
Try this one:
Adding a **project reference** in `TerminalApp` to the `TerminalSettings` project.
