### ISSUE TITLE
WT Preview not starting

### ISSUE THREAD

**Issue by AnuthaDev** [microsoft/terminal#6591]
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version (if applicable): WT Preview 1.1.1671.0

Any other software?
No
```

# Steps to reproduce
Install using msixbundle, click on icon in start

# Expected behavior
Terminal window opens

# Actual behavior
This error window pops up
![Screenshot (365)](https://user-images.githubusercontent.com/36439704/85113632-388d0c00-b235-11ea-9f24-67aac168bd8d.png)

When it initially did not work, I went to the Program Files/WindowsApps directory and tried opening the exe file from there, I don't remember how but after taking ownership of the directory, the terminal window opened on clicking the exe file, but did not work from start icon. I then enabled software rendering thinking something was wrong with my graphics drivers and it stopped worling from the exe also. Now I get a "Windows terminal has stopped working" dialog on clicking the exe. I had terminal v1 installed in the beginning but I uninstalled it while trying to make it work, but it did not have any effect. Please help

**Comment by zadjii-msft** [comment]
There is some additional discussion of a similar issue in #6010, does any of that help?

**Comment by AnuthaDev** [comment]
@zadjii-msft It looks like my issue is a duplicate of #2129. Also, the discussion in #6010 is very helpful, I'll see if extracting the msixbundle helps. It might be an issue with the AppInstaller store app becuase fiddling with the file permissions allowed me to open the terminal (although I corrupted it later😅)

**Comment by AnuthaDev** [comment]
I have only ever installed terminal from the store, I'll install v1 using msixbundle and see how it goes...

**Comment by zadjii-msft** [comment]
Thanks for follwoing up!

/dup #2129

**Comment by AnuthaDev** [comment]
@zadjii-msft Update: I restarted my pc, connected to internet and it worked!
