### ISSUE TITLE
Submenus are in a different language.

### ISSUE THREAD

**Issue by ll01** [microsoft/terminal#6594]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):1.0 and 1.1 preview

Any other software?
Chinese language pack. (English local is default)
```

# Steps to reproduce
I really dont know how to define this. 
I Installed the application and the submenus are in chinese. But I have English UK English US Japanese and Chinese installed on the computer

# Expected behavior
all sub menus are in english

# Actual behavior
cmd and settings are in chinese 
![chinese_terminal](https://user-images.githubusercontent.com/6953881/85137017-72abdd00-b238-11ea-93ac-3a28a26b6e11.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5497 and #6029 for more discussion.

/dup #5497 #6029
