### ISSUE TITLE
Keyboard scroll (Scroll Lock plus ↑, ↓, PgUp, PgDn)

### ISSUE THREAD

**Issue by martingbrown** [microsoft/terminal#6595]
Currently when I press the up and down arrows, terminal (or it may be PowerShell/Cmd) switches between my most recently used commands. I'd also like to be able to scroll the screen, similarly to how the scroll bar works, using the keyboard.

My proposal would be to use the Scroll Lock key to toggle between two modes. With scroll lock off it would work as it does now, with scroll lock on the Up and Down arrows would scroll a single line (or repeatedly scroll one line if held down) and the Page Up, Page Down keys would scroll an entire window full.

Excel has similar functionality. With scroll lock off the selected cell moves, with scroll lock on it doesn't.

**Comment by zadjii-msft** [comment]
There's already the following keybindings if you want to use the keyboard to navigate the scrollback:
https://github.com/microsoft/terminal/blob/1fdceb0ea99f968142cb014286baa362c65d6b3f/src/cascadia/TerminalApp/defaults.json#L331-L334

Do those work for you?

**Comment by martingbrown** [comment]
I guess that does work, but I still think it would make the finger gymnastics a bit easier to use scroll lock.

**Comment by DHowett** [comment]
I agree. We've got a couple specs in flight here (#2529, for #980), and #3863 mentions scroll lock. Once we have keyboard selection (#2840 spec), that'll include keyboard buffer navigation, and we can extend #2529 to cover scroll lock as well. We're also considering "mark" mode (a mode you switch into where you can navigate the buffer solely by keyboard)

/dup #3863, #715

**Comment by martingbrown** [comment]
Thanks Dustin, sounds like you've got this covered.
