### ISSUE TITLE
Typing "wt" in Explorer address bar shall open Windows Terminal from the current folder (i.e. "Here")

### ISSUE THREAD

**Issue by SamSig** [microsoft/terminal#6596]
# Description of the new feature/enhancement
Currently if type "wt" in Explorer address bar and press Enter, no matter which folder is currently opened in Explorer, the Windows Terminal will always open in %UserProfile%. Verified in version: 1.0.1401.0

It is expected to go directly to the current folder that is opened in Explorer. Like when you type "cmd" in address bar for the same.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22explorer+address+bar%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #878 for more discussion.

We wanted to make `wt` behave like `cmd` or `powershell` here, but unfortunately, there were just too many odd edge cases to make this work right. There are more details over in https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 if you want more reading. The recommended way to open the terminal in the current directory is by typing `wt -d .` in the explorer bar.

/dup #878 #6559 #6456 #6279 #6031 #5796
