### ISSUE TITLE
Running cat on long file doesn't place prompt at bottom.

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6597]
# Environment

```none
Windows build number: 19041
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.1.1671.0

Any other software? N/A
```
# Steps to reproduce
Copy the WSL2 kernel config file into a text file and save with no extension. https://github.com/microsoft/WSL2-Linux-Kernel/tree/master/Microsoft

Run Terminal in a maximized window: In WSL, run a cat on this file.
# Expected behavior
Prompt should appear at the bottom.

# Actual behavior

```
CONFIG_PROBE_EVENTS=y
CONFIG_DYNAMIC_FTRACE=y
CONFIG_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_FUNCTION_PROFILER=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set
CONFIG_FTRACE_MCOUNT_RECORD=y
# CONFIG_FTRACE_STARTUP_TEST is not set
# CONFIG_MMIOTRACE is not set
# CONFIG_HIST_TRIGGERS is not set
# CONFIG_TRACEPOINT_BENCHMARK is not set
# CONFIG_RING_BUFFER_BENCHMARK is not set
# CONFIG_RING_BUFFER_STARTUP_TEST is not set
# CONFIG_PREEMPTIRQ_DELAY_TEST is not set
# CONFIG_TRACE_EVAL_MAP_FILE is not set
# CONFIG_PROVIDE_OHCI1394_DMA_INIT is not set
# CONFIG_DMA_API_DEBUG is not set
# CONFIG_RUNTIME_TESTING_MENU is not set
# CONFIG_MEMTEST is not set
# CONFIG_BUG_ON_DATA_CORRUPTION is not set
# CONFIG_SAMPLES is not set
CONFIG_HAVE_ARCH_KGDB=y
CONFIG_ARCH_HAS_UBSAN_SANITIZE_ALL=y
# CONFIG_UBSAN is not set
CONFIG_ARCH_HAS_DEVMEM_IS_ALLOWED=y
# CONFIG_STRICT_DEVMEM is not set
CONFIG_TRACE_IRQFLAGS_SUPPORT=y
# CONFIG_X86_VERBOSE_BOOTUP is not set
CONFIG_EARLY_PRINTK=y
# CONFIG_EARLY_PRINTK_DBGP is not set
# CONFIG_EARLY_PRINTK_EFI is not set
# CONFIG_EARLY_PRINTK_USB_XDBC is not set
# CONFIG_EFI_PGT_DUMP is not set
# CONFIG_DEBUG_WX is not set
CONFIG_DOUBLEFAULT=y
CONFIG_HAVE_MMIOTRACE_SUPPORT=y
CONFIG_IO_DELAY_TYPE_0X80=0
CONFIG_IO_DELAY_TYPE_0XED=1
CONFIG_IO_DELAY_TYPE_UDELAY=2
CONFIG_IO_DELAY_TYPE_NONE=3
CONFIG_IO_DELAY_0X80=y
# CONFIG_IO_DELAY_0XED is not set
# CONFIG_IO_DELAY_UDELAY is not set
# CONFIG_IO_DELAY_NONE is not set
CONFIG_DEFAULT_IO_DELAY_TYPE=0
CONFIG_OPTIMIZE_INLINING=y
# CONFIG_PUNIT_ATOM_DEBUG is not set
CONFIG_UNWINDER_ORC=y
# CONFIG_UNWINDER_FRAME_POINTER is not set
# CONFIG_UNWINDER_GUESS is not setuser@hostname/mnt/c/Users/user $
```

**Comment by WSLUser** [comment]
Note if I minimize Terminal, the prompt is restore to the bottom. Going fullscreen again keeps the prompt at the bottom.

**Comment by hongooi73** [comment]
The prompt being appended to the end of the final line is because the file doesn't end in a trailing `\n`. The real bug seems to be when you maximise and restore the window; in this case, the prompt gets moved back to the left side of the screen, overwriting any content that was there.

**Comment by WSLUser** [comment]
Curiously I just noticed the tool tip to shrink the terminal window also says maximize instead of minimize.

**Comment by WSLUser** [comment]
I updated the OP and my comment note as there may be a difference in "fullscreen" vs. "maximized window", which is what I had.

**Comment by DHowett** [comment]
Two things here. First, @hongooi73 is totally right: if you're lacking a newline at the end of your file, you'll see this behavior.
Second, bash _responds to a window size change by re-homing the prompt_. That is: during window resize, bash moves the cursor back to the start of the line. This will necessarily destroy anything that was there. :smile:
