### ISSUE TITLE
Add power shell 7 error

### ISSUE THREAD

**Issue by chuoke** [microsoft/terminal#6598]
I tried some methods searched. still not successful. I don't know what I'm missing.

# Environment

```none
Windows 10 Professional 1909  x64
Windows Terminal: 1.0.1401.0
```

# Steps to reproduce
I certain the files exist. My profile:  
```json
      {
            "guid": "{1a7254b1-b1f5-11ea-89cb-001d090c71d4}",
            "name": "Windows PowerShell 7",
            "commandline": "‪C:\\Apps\\DevTools\\PowerShell7\\7\\pwsh.exe",
            "icon": "‪C:\\Apps\\DevTools\\PowerShell7\\7\\assets\\Powershell_av_colors.ico",
            "hidden": false
        }
```

# Expected behavior
Can open power shell 7 in windows terminal.

# Actual behavior
I got two error :
- the icon is invalid
- ` error 0x80070002 when launching 'C:\Apps\DevTools\PowerShell7\7\pwsh.exe'  `

**Comment by WSLUser** [comment]
That is not a proper path or name. Windows Powershell and PS7 have 2 entirely different profiles and are available by default if you install PS7. Close Windows Terminal, delete the `settings.json `and open Windows Terminal again. This will generate a new `settings.json` and it will also by default launch PS7.

**Comment by DHowett** [comment]
This error code means "file not found.".

Can you run the following PowerShell command (outside of terminal)?

```
Get-FileHash C:\Apps\DevTools\PowerShell7\7\pwsh.exe
```

**Comment by DHowett** [comment]
@wsluser People can install powershell wherever they want to. This profile looks entirely valid.

**Comment by chuoke** [comment]
> This error code means "file not found.".
> 
> Can you run the following PowerShell command (outside of terminal)?
> 
> ```
> Get-FileHash C:\Apps\DevTools\PowerShell7\7\pwsh.exe
> ```
Thanks first.

I got two same results after I run it in Power shell 7 and old Power shell.
![power-shell-hash](https://user-images.githubusercontent.com/17611457/85187946-21522b00-b2d6-11ea-956f-c315cecb0b7f.PNG)

**Comment by chuoke** [comment]
@WSLUser  Thanks first. I did follow the way you said. but there is nothing the change.

**Comment by WSLUser** [comment]
Ok yeah, it seems a weird path but if it's valid then it's valid. So even after Terminal does the path generation for you, it fails to launch correctly. I have the 7.0.1 msix installed manually from the Github release to a default location which works in both 1.0 and Preview. I haven't updated to 7.0.2 yet but I wasn't expecting an error like this to occur. What was used to install Powershell

**Comment by WSLUser** [comment]
in case its valid: Since I installed the msix and not the msi, I have 2 PS7 profiles,  the originsl for msi and another that actually says msix in the name. It  was originally launching using the msi profile. While the schema keeps wanting to keep both, I was able to remove the msi profile and leave only the msix in settings. The current PS tab would have a dialog error but a new tab with PS7 would launch just fine.

**Comment by chuoke** [comment]
I just installed it in the specified directory I want. What a pity If this way is not allowed.

**Comment by chuoke** [comment]
I noticed weird info from the error message：` “‪ C:\Apps\DevTools\PowerShell7\7\pwsh.exe” `, in the console, there is spacing before the `C`. But there have not any spacing in the path of my profile.

**Comment by DHowett** [comment]
Can you attach a copy of your settings file? You might need to put it in a zip so GitHub doesn’t change the formatting. :)

**Comment by chuoke** [comment]
[settings.zip](https://github.com/microsoft/terminal/files/4807335/settings.zip)
All are default generated except the Power Shell 7 profile I added.

**Comment by DHowett** [comment]
Your comment about "spacing" is what tipped me off :smile:

![image](https://user-images.githubusercontent.com/189190/85190803-c0dcd280-b270-11ea-80db-eaeba3de1083.png)

That's a "left-to-right embedding" glyph at the beginning of your path!

**Comment by chuoke** [comment]
That's the point. It works after deleted the invisible spacing. 
Many hands make light work. Thank you very much.

By the way. I don't know why spacing in the path. But it just happens. So if some other guys have the same problem. You just move your cursor to the weird position and enter `DELETE` until the quotation mark or you visible mark.

**Comment by DHowett** [comment]
Glad we figured it out :)
