### ISSUE TITLE
Padding breaks mouse selection

### ISSUE THREAD

**Issue by ghvanderweg** [microsoft/terminal#660]
Adding padding to a profile (e.g. `"padding": "20, 20, 20, 20"`) breaks selecting text with your mouse. The selection is offset with the padding.

![terminal](https://user-images.githubusercontent.com/16590775/57524702-dc18a700-7328-11e9-9c82-86577d1ba0aa.gif)

edit: Windows build 10.0.18890.1000, just in case that's relevant

**Comment by mwidmann** [comment]
I noticed this in 18362.86 as well. It's not as bad as in your case as I have set the padding to be `10, 10, 10, 10` only.

**Comment by zadjii-msft** [comment]
I believe @carlos-zamora is working on this :)

**Comment by carlos-zamora** [comment]
Yeah. It's off by the amount of padding. I have it in code review in our other system (still transitioning over to GitHub) so this'll be fixed soon. 😊
