### ISSUE TITLE
Window Terminal refuses to use PL comaptible fonts

### ISSUE THREAD

**Issue by intractabilis** [microsoft/terminal#6605]
# Environment

```none
Microsoft Windows NT 10.0.18363.0
Windows Terminal Версия: 1.0.1401.0
```

# Steps to reproduce

The issue is intermittent, I am not sure. It changes from one reboot to another.

# Expected behavior
When `fontFace` in `settings.js` is set to any power line compatible fonts, I expect to see special characters in the command line prompt. Here is an example for `Powerlevel10k-Classic` theme and `Hack Nerd Font`, the screenshot is taken from ConEmu, which doesn't have this issue:
![изображение](https://user-images.githubusercontent.com/45959195/85190256-5d03db00-b26b-11ea-97c7-108ac6bcf065.png)

# Actual behavior
Here is a screenshot from Windows Terminal with the same font:
![изображение](https://user-images.githubusercontent.com/45959195/85190322-267a9000-b26c-11ea-8252-63857df10f2c.png)

If you compare `0`s in both screenshots, you can see that Windows Terminal switched to some default font, it's not `Hack Nerd Font`. I have a lot of PL compatible fonts, if the issue is triggered (I mentioned it is intermittent), none of them work, even `Cascadia Code PL`, i.e. Windows Terminal stays with the same default font. Switching to other fonts, e.g. `Cascadia Code` works, but, well, without special symbols of course:
![изображение](https://user-images.githubusercontent.com/45959195/85190411-10b99a80-b26d-11ea-88e3-1850d2c424fe.png)

**Comment by DHowett** [comment]
This looks a lot like #3257. If you install the font `for all users`, does it work more reliably?

**Comment by intractabilis** [comment]
Yep, this looks like exactly the same issue. Thanks! I'll experiment with the place of installation. So far I rebooted to Linux and removed the font cache, it works, will see how stable it is.
