### ISSUE TITLE
Entire TW screen flickers once I have Ctrl+shift+ scrolled mouse wheel to adjust the opacity. It flickers from transparent to opaque and back quickly as I move the window. 

### ISSUE THREAD

**Issue by jroskey** [microsoft/terminal#6609]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.330]
Windows Terminal version:
Windows Terminal
Version: 1.0.1401.0

Any other software?
```

# Steps to reproduce

If I hold ctrl + shift _ scroll the mouse wheel to adjust the opacity, whether it has panes or not, it single or multi tabbed, if I move the window after adjusted the opacity, the WT window will flicker between the transparency setting I set, to all black, to back. It doesn't do this every time, and Can get 'stuck on the wrong setting' i.e. if I have it transparent, it can get stuck fully Black.

# Expected behavior

Remain either transparent or opaque (How I ever I have it set currently) while moving the window and not flicker.

# Actual behavior

WT window flickers between current transparency setting to black and back while moving the window sometimes. Sometimes not.

Thanks in advance!

**Comment by DHowett** [comment]
Wow, this is really wild.

If you set acrylic transparency to always be on with `useAcrylic:true` (and don't use the mouse wheel), does it also flicker then?

**Comment by jroskey** [comment]
To be honest I'm testing now with various tabs open with different opacities that no longer flickers. It now only turns black when the window goes inactive, but as soon as I click on it The transparency setting for that tab goes back into effect. So maybe it was something with that but I'm unable to reproduce the issue now even resizing the window minimizing maximizing switching tabs adding panes all with different levels of transparency.
Thx for the help!

Regards,
Robert Roskey

________________________________

**Comment by DHowett** [comment]
Hey, thanks so much. I hate when bugs just disappear, but sometimes that's just how our jobs work. Please let me know if it comes back!
