### ISSUE TITLE
Add Scroll bars to WT panes!

### ISSUE THREAD

**Issue by jroskey** [microsoft/terminal#6610]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.330]
Windows Terminal version (if applicable):  Windows Terminal Version: 1.0.1401.0

Any other software?
```

# Steps to reproduce

None really, just would love scrollbars in each pane. Maybe the new very skinny ones until you mouse over and then they get wider. Would be Awesome!

# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -To have scroll bars in each window, or more preferably each pane. the new skinny scroll bars they get wider when you mouse over them, as to not take up alot of room in each pane.

# Actual behavior

No scrollbars at all in any pane/window

**Comment by intractabilis** [comment]
I have scroll bars in each pane. They are exactly as you described. Are you talking about Windows Terminal panes? Because there can be panes inside a shell you are running in the terminal.

**Comment by zadjii-msft** [comment]
Each pane definitely has it's own scrollbar:

![image](https://user-images.githubusercontent.com/18356694/85283480-0d800380-b453-11ea-9fee-601bc03e5c09.png)


Are you not seeing them?

**Comment by jroskey** [comment]
No sir. No scroll bars on hover nor clicking on the right side of a pane, or  the main area/pane even if it's not split into panes.

Thanks for your time.

Regards,
Robert Roskey

________________________________

**Comment by zadjii-msft** [comment]
Could you share your `settings.json`? It's possible that the `scrollbarState` is set to `hidden` or `false` 🤔

**Comment by jroskey** [comment]
Yes sir, I'd be happy to. We're traveling right now and I'll be back home later tonight and I'd be happy to send you the settings .json file, or just I'll try to set the scroll bar state to true if it isn't already. Thanks for the heads up and have a good day.

Regards,
Robert Roskey

________________________________

**Comment by jroskey** [comment]
Setting the scrollbarState to true fixed it. That line wasn't there until I added that line setting it to true. Thank you!

Regards,
Robert Roskey

________________________________

**Comment by DHowett** [comment]
I'm so glad that worked! Thanks for following up.
