### ISSUE TITLE
Color Tabs

### ISSUE THREAD

**Issue by gedeonych** [microsoft/terminal#6612]
Yes, these are color tabs. Allows the user to quickly navigate many connections. For example: danger zones. Red, Yellow, Green. Or another criteria.

Maybe something like the "colorTabs" parameter

**Comment by zadjii-msft** [comment]
This was actually already added in [version 1.1](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-1-release/#color-picker)

> ## Color picker
>
> You can now color your tabs by right-clicking on them and selecting “Color…”. This will open the tab color menu where you can select a predefined color or expand the menu to select any color using the color picker, hex code, or RGB fields. The colors for each tab will persist for that terminal session. A huge thank you goes out to gbaychev for contributing this feature!
>
> ![image](https://user-images.githubusercontent.com/18356694/85283020-479cd580-b452-11ea-9974-d600d4079363.png)

/dup #2994 #3789 #3327
