### ISSUE TITLE
Exit code 1 when exiting an Ubuntu multiplexed pane

### ISSUE THREAD

**Issue by guillaumemeyer** [microsoft/terminal#6614]
# Environment

OS:
![image](https://user-images.githubusercontent.com/1385518/85207307-3061c900-b328-11ea-8ee0-e61c1d213d0b.png)

Terminal:
![image](https://user-images.githubusercontent.com/1385518/85207317-3d7eb800-b328-11ea-9255-81fbae484520.png)

SubSystem:
![image](https://user-images.githubusercontent.com/1385518/85207342-6f901a00-b328-11ea-9fec-ad3de2551783.png)

# Steps to reproduce

1. Open an Ubuntu tab, then open a second multiplexed ubuntu session in a pane
2. Run some commands in the right pane, such as htop
3. Go back to the prompt and type `exit`

# Expected behavior

The right pane should close, leaving only the first pane.

# Actual behavior

The right pane doesn't close and raises an error code 1:
![image](https://user-images.githubusercontent.com/1385518/85207282-fdb7d080-b327-11ea-99ac-1aa13bd4b2cd.png)

**Comment by TrueshotBarrage** [comment]
I can reproduce the same error using the steps outlined above.

**Comment by DHowett** [comment]
This is interesting. Before you `exit`, can you run `echo $?` to show the error code from the previous process?

**Comment by DHowett** [comment]
Oh, and, how do you exit `htop`?

bash reflects the exit code of the last process _as its own exit code_. That means that when htop exits with code `1`, bash says "I HAVE FAILED" and Terminal picks that up. That's be design - Terminal defaults to preserving the window when the process inside it has exited.

To turn off this behavior, set `closeOnExit` to `always`. :smile:

**Comment by guillaumemeyer** [comment]
I'm exiting htop with `ctrl+c`, and you're right about the exit code @DHowett  :
![image](https://user-images.githubusercontent.com/1385518/85871546-d69d4b00-b7ce-11ea-8739-ec71695ce2ea.png)

**Comment by guillaumemeyer** [comment]
And yes using `"closeOnExit": "always"` in the terminal settings solves the issue.
