### ISSUE TITLE
The terminal emulator is ignoring my font for certain characters/emoticons

### ISSUE THREAD

**Issue by francogp** [microsoft/terminal#6615]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1402.0

Using WSL Ubuntu LTS version 20.04
```

I'm using this font, but can reproduced with others too: [JetBrainsMono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf)

# Expected behavior

image taken by using other windows terminal emulators, like Terminus on windows, and Tilix or Terminator on Ubuntu. All the same results
![image](https://user-images.githubusercontent.com/2739706/85209354-94c35f00-b30d-11ea-8d77-e6779d68df98.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/2739706/85209296-1961ad80-b30d-11ea-86d7-4b95fd9bbc5a.png)
Lots of characters/emoticons have a wrong size at render. This is just an example. Look up the check emoticon ✔
It seems that its ignoring my font.

**Comment by DHowett** [comment]
Thanks! I think this is just a specific case of #956, so I'm going to move your report into there and add a note that we should consider range-based emoji suppression. The core of the issue here is that _DirectWrite prefers the emoji presentation for that glyph_ (unfortunately!)

/dup #956
