### ISSUE TITLE
After few hours externals command are executed externally

### ISSUE THREAD

**Issue by sbugalski** [microsoft/terminal#6621]
# Environment

```none
Windows build number: Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):

Any other software: Az CLI, Kubectl, chocolatey
```

# Steps to reproduce

* Run Windows Terminal with Windows Powershell
```
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.
```

* Use it for long time
* Execute external program (like az, kubectl)

# Expected behavior

Run application in command line 

# Actual behavior

* It pops out application in external process.
![Hv0EektpEX](https://user-images.githubusercontent.com/45152735/85225752-a707d080-b3d3-11ea-9e96-71cd891264a6.png)
When run in new tab it works as expected

**Comment by zadjii-msft** [comment]
_what_

I have no idea how this would happen. Maybe there's something bugged in powershell that's causing it to start running commands in another window always?

Does it usually start happening after running a specific command? Or a sequence of commands?

**Comment by tamlin-mike** [comment]
@sbugalski Please check HANDLE counts (using e.g. TaskMgr) net time this happens. USER handles could be a prime suspect.

@zadjii-msft I suspect there's a leak (probably a HWND) in the window-hosting. I believe it would perfectly match that bug behavior.

**Comment by DHowett** [comment]
@tamlin-mike the Terminal doesn’t host console windows inside it; it uses the pseudoconsole API which communicates process state over a pair of pipes. There isn’t an HWND in sight :)

**Comment by tamlin-mike** [comment]
@DHowett Damn, there goes that theory. :-)

It still has a strong smell of resource leak though, or table overflow, plus some lack of error checking for function returns (otherwise some code would have cought this and reported error, right? :-) ).

Could it be a pipe leak (`DuplicateHandle`, impersonation, ...)? Leak or race in the pseudoconsole API implementation?

**Comment by sbugalski** [comment]
> Does it usually start happening after running a specific command? Or a sequence of commands?
@zadjii-msft:
It happened me twice, I was using kubectl and az cli mainly.


> @sbugalski Please check HANDLE counts (using e.g. TaskMgr) next time this happens. USER handles could be a prime suspect.
@tamlin-mike 
Sure, once it happens me again I'll check that.
