### ISSUE TITLE
Supporting font family for alternative font

### ISSUE THREAD

**Issue by StevenKangWei** [microsoft/terminal#6627]
Supporting font family for alternative font\

**Comment by srisuk2519** [comment]
เมื่อ จ. 22 มิ.ย. 2563 เวลา 18:09 Steven <notifications@github.com>
เขียนว่า:

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22font+family%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1163 for more discussion.

/dup #1163
