### ISSUE TITLE
Folders/Groups for Profiles

### ISSUE THREAD

**Issue by cburj** [microsoft/terminal#6629]
# Description of the new feature/enhancement

I would really like the ability to group/nest profiles together. For example having multiple connections to the same server grouped under one folder. I currently have a lot of ssh profiles and it's getting out of control 😁

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22profile+folder%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571 #6602 #6512 #6440 #6347 #6289 #6095 #6083 #5850 #5548 #4880 #4535 #4241 #2870 #2608 #2330 #2216
