### ISSUE TITLE
WinForms dialog not popping up on top of Windows Terminal

### ISSUE THREAD

**Issue by camellia256** [microsoft/terminal#6633]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable):
1.1.1671.0 (Preview) and 1.0.1401.0 (Stable)
Any other software?
Windows PowerShell 5.1 and PowerShell 7.0.2
```

# Steps to reproduce
1. Run the following command in Windows PowerShell 5.1 or PowerShell 7.0.2
```powershell
Add-Type -AssemblyName System.Windows.Forms
$d = New-Object System.Windows.Forms.FolderBrowserDialog
$d.ShowDialog()
```
2. Close the dialog and run this command twice
```powershell
$d.ShowDialog((New-Object System.Windows.Forms.Form -Property @{TopMost = $true }))
```

# Expected behavior
1. A folder browser dialog should pop up _on top of_ Windows Terminal window (this is the behavior in conhost.exe)
2. A folder browser dialog should pop up _on top of_ Windows Terminal window (this is the behavior in conhost.exe)

# Actual behavior
1. The dialog pop up _behind_ Windows Terminal window. On PowerShell 7 the dialog is big so I can see part of it behind Terminal. On Windows PowerShell 5.1 the dialog is small and completely hidden behind. `System.Windows.Forms.OpenFileDialog` is also affected
2. The dialog pop up _behind_ Windows Terminal window on first try, and only pop up _on top of_ Windows Terminal window on second try

**Comment by zadjii-msft** [comment]
I'm gonna guess that this is is actually #2988. That's the issue tracking most of the z-order problems the Terminal sometimes has.

/dup #2988
