### ISSUE TITLE
Buttons(Minmize, close etc) are unclickable after leaving the process idle for some time

### ISSUE THREAD

**Issue by satishrdd** [microsoft/terminal#6637]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.18363.900]
Windows Terminal version (if applicable):
1.0.1401.0
Any other software?
```

# Steps to reproduce

Opened the terminal used it for some time, left it idle for long(working on something else).
Bring the terminal app to focus and click on any of the buttons on the app. 

# Expected behavior

I should be able to click buttons on the app(new tab, minimize, close etc.)

# Actual behavior

Cant click anything on the app. Seen this multiple times.

**Comment by DHowett** [comment]
Are you running PowerToys?

**Comment by satishrdd** [comment]
Yes I have PowerToys Running

**Comment by zadjii-msft** [comment]
Great, this is probably #6120 or #3325 - I'm really not sure which one of those threads is the master thread anymore tbh. PowerToys seems to do something strange with Windows Terminal windows, though we haven't tracked it down quite yet.

/dup #3325 #6120
