### ISSUE TITLE
can't open setting

### ISSUE THREAD

**Issue by coctavian** [microsoft/terminal#6642]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
You gotta fill out the issue template for us to be able to help you.

Make sure you've got a application set as the default `.json` file editor, because the settings file is going to open in that application.
