### ISSUE TITLE
Make keys in the command palette look like actual keys, like in VS Code

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6645]
Omitted from initial implementation in #6635.

Add little borders & boxes to really emphasize that the keys are _keys_ to press. I don't know how to do this in XAML, but I think it would be a bit of nice polish.

**Comment by mdtauk** [comment]
> Omitted from initial implementation in #6635.
> 
> Add little borders & boxes to really emphasize that the keys are _keys_ to press. I don't know how to do this in XAML, but I think it would be a bit of nice polish.

I think PowerToys does something similar with its Key Remapping.
![image](https://user-images.githubusercontent.com/7389110/85791420-b10a3600-b729-11ea-8434-e1052cdee5d3.png)

Maybe you could decide on a "house style" to try to be consistent?

**Comment by DHowett** [comment]
> Strong veto. When we have key _chords_ (as opposed to just key _notes_, see #1334), then we'll definitely want to keep the current design, for something like <kbd>Ctrl+K</kbd>+<kbd>Ctrl+U</kbd>.

_from @zadjii-msft_

This is at odds with #1334 now. We currently have a version that displays each key _chord_ in its own pill.

**Comment by zadjii-msft** [comment]
When we have chords composed of notes (i.e, when implementing #1334), we should come back around to update this UI too 😉
