### ISSUE TITLE
Cannot type in Windows Terminal regardless of profile

### ISSUE THREAD

**Issue by Cairo2k18** [microsoft/terminal#6651]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

1. Open Windows Terminal
2. Select a profile
3. Attempt to type into it

# Expected behavior

For it to let me type into the command line and actually work

# Actual behavior

Whenever I type it does not show up, it's like my keyboard isn't attached and I try to type, but only happens in Windows Terminal.
If I open up cmd or pwsh and type into them directly it has no issues, but does when I use winterm.

**Comment by skyline75489** [comment]
What is your locale setting? What keyboard layout are you using? Are you using IME or something?

**Comment by Cairo2k18** [comment]
> What is your locale setting? What keyboard layout are you using? Are you using IME or something?

I use the US keyboard layout and my windows display, apps and website, regional format and keyboard language is en-NZ (English New Zealand) and my speech language is en-GB (English UK).

And, no, I am not using IME.

**Comment by zadjii-msft** [comment]
By any chance, does the workaround in #4448 do anything for you?

**Comment by Cairo2k18** [comment]
Awesome! It did, thank you.
