### ISSUE TITLE
overwrite mode on FreeBSD when crossing space in command line

### ISSUE THREAD

**Issue by zsbolyoczki** [microsoft/terminal#6652]
### Environment

Windows Version: Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version: 1.0.1401.0

### Issue description

On FreeBSD based servers (and appliances too) the prompt switches to 'overwrite mode' when navigating through a space from the end of the line to the beginning of the line.

### Steps to reproduce

1. Log in to a FreeBSD server (or FBSD based appliance) with ssh. (It doesn't matter which shell (bash, csh, etc.) is being used.)
2. Try to type a command that's made of more words (or only one word but with a space after it)
3. Start to navigate from the end of the line to the beginning of the line (either with 'left arrow' or 'Home' or any other way)
4. Until the 1st space from the right is passed in the command, the command line is in 'insert mode'
5. Just when the 1st space is passed from the right, the command line switches to 'overwrite mode'

Example #1:
$ commandX

When one is navigating on this one word, it's OK, command line is in 'insert mode'
Once one is typing a space at the end of the line and starts to navigate back to any other letter, the command line changes to 'overwrite mode'

Example #2:
$ commandX paramY paramZ

When navigating backwards from right to left, command line is in 'insert mode' until letter 'Y' is reached. Once the space is crossed next to letter 'Y' the command line switches to 'overwrite mode'.

### Expected behavior

Crossing any space in the command line shouldn't switch the command line to 'overwrite mode'.

Working examples which doesn't have this 'switching' behaviour:
- putty
- any native linux terminals.

**Comment by zadjii-msft** [comment]
Couple of questions:
* Which version of `ssh` are you using? The inbox `ssh.exe`, or the `ssh` from a linux distro installed with WSL?
* does this repro with a legacy console window (conhost.exe)?

**Comment by zsbolyoczki** [comment]
- I'm using ssh from WSL (Ubuntu-18.04 (Default))
- I couldn't find proper way to get current WSL version but "uname -a" returns "4.4.0-18362-Microsoft" if that helps.
- The issue is there with ssh.exe from cmd and with ssh client from WSL.

**Comment by DHowett** [comment]
I believe this is because we don't support #1947...

**Comment by zsbolyoczki** [comment]
seems to be the same issue to this #125 and xterm-256color is affected.

**Comment by DHowett** [comment]
Thanks for following up. I'm gonna make /dup #1947 the master issue for IRM.
