### ISSUE TITLE
WSL under Terminal (preview) exposes Windows file system.

### ISSUE THREAD

**Issue by mayureshkathe** [microsoft/terminal#6653]
# Environment

```none
Microsoft Windows [Version 10.0.19041.329]
Windows Terminal version: latest preview build downloaded via Microsoft Store.
Widows Command Prompt
```

# Steps to reproduce

# Expected behavior

When I run the "ls" command under WSL running with Windows Terminal it should only show the files related to that WSL instance as it works under "Command Prompt".

# Actual behavior

The entire file listing and hierarchy of all files (including files belonging to Windows) in that directory is shown.

**Comment by zadjii-msft** [comment]
This is by design. Filesystem interoperability is one of the main features of WSL - this means you can use linux tools with you Windows files, and vice-versa. 

If you have any other WSL questions, https://github.com/microsoft/WSL would be the appropriate place to ask.

**Comment by DHowett** [comment]
What part of our documentation made you believe that WSL would be isolated from Windows, and that this was a bug? I'd like to bring it to the attention to the WSL team to make sure we're communicating effective.

**Comment by DHowett** [comment]
The by-default resource sharing is one of the core tenets of WSL. It’s not a primary/secondary OS situation, it’s intended to enable hybrid workflows that span both operating systems.

You can disable the integration, but since this is the terminal repo and it’s late in the evening I’ll have to direct you to the WSL docs to learn how :smile:

**Comment by mayureshkathe** [comment]
If by-default resource sharing is one of the core tenets of WSL and this so-called feature (which you categorize as "not bug") isn't being considered a Terminal related issue, then why is it so that this so-called feature of "WSL" is only available under Terminal and absolutely absent under "Command Prompt"?
I think you people are confused about the situation.
It's high time you exhibited maturity and got your act straight.

**Comment by zadjii-msft** [comment]
I'd just like to take a quick moment to remind to you please make sure you're following our [code of conduct](https://opensource.microsoft.com/codeofconduct/) when contributing here. There's clearly a bit of a misunderstanding in this thread, no need to resort to insults.

Is what you're really reporting that `wsl` from `cmd.exe` gives different results for `ls` than when run from the Terminal? 
![image](https://user-images.githubusercontent.com/18356694/85724288-afa12500-b6b9-11ea-86eb-d1f7c3cdae52.png)


That's certainly highly unusual. Perhaps you've got multiple different distros configured? Could you share the output of `wsl -l`?

**Comment by mayureshkathe** [comment]
Firstly, I apologise for uttering harsh words towards the glorious work being done by a bunch of snowflakes.
Secondly, after this comment, I pledge never to turn brutal in spite of any moronic behaviour exhibited by any of those who'eve pledged allegiance to your "code of conduct".
Third, I am now proceeding with a reinstall of my Windows 10 system from scratch, I'll run the tests you've asked me to and submit the results at the earliest which might help you deliver an improved product.

**Comment by zadjii-msft** [comment]
See, I don't think that "be respectful" is too much to ask. That's like, human decency 101. If you want more help on this issue, you can either try to show some basic respect for the people you're working with, or I'm gonna have to lock this thread. Thanks!

**Comment by oising** [comment]
@mayureshkathe It seems your magnificent intellect is being underutilized by way of repeated feeble attempts to troll the developers. Perhaps it would be better spent on discerning an optimal solution to the core problems of the troubled Korean Armistice Agreement, or maybe unravelling the secrets of the Riemann Hypothesis.

Or, you could spend ten or twenty minutes challenging your own assumptions about the goals of WSL.
