### ISSUE TITLE
Bring Windows Terminal to Specific Folder When Run From File Explorer

### ISSUE THREAD

**Issue by MikeMcCollister** [microsoft/terminal#6655]
# Description of the new feature/enhancement

If I have the File Explorer open to "C:\Windows\System32\drivers\etc" and then type "cmd" (without the quotes) in the address bar it opens a Command Prompt in the "C:\Windows\System32\drivers\etc". Please have Windows Terminal do the same if I type "wt" (without the quotes" in the File Explorer address bar.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22explorer+address+bar%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #878 for more discussion.

We wanted to make `wt` behave like `cmd` or `powershell` here, but unfortunately, there were just too many odd edge cases to make this work right. There are more details over in https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 if you want more reading. The recommended way to open the terminal in the current directory is by typing `wt -d .` in the explorer bar.

/dup #878 #6596 #6559 #6456 #6279 #6031 #5796

**Comment by MikeMcCollister** [comment]
Thanks for the explanation of the issue. I can now use "wt -d ." and it works like a charm.
