### ISSUE TITLE
SSH handler

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#6656]
# Description of the new feature/enhancement

I'd like to do something like

<kbd>Win</kbd><kbd>R</kbd> `wt admin@myserver.com`  <kbd>Enter</kbd>

and it will start up or open an new tab in an existing Windows Terminal that will perform an SSH connection.

# Proposed technical implementation details (optional)

Note this request is NOT to embed SSH itself to Windows Terminal, but provide some sort of generic handler for command lines with a username@host pattern along with <proto>://<username>@<host>:<port>/<path> pattern the protocol and ports should be defaultable (in my case if I had the configuration I would default to `ssh` since I generally work with that.

I was thinking it will be a `profile` that if not hidden will ask for a URL if selected and the "command" allows for extra fields that would be used to pass in the components 

```json
{
    "defaultUriProtocol": "ssh",

    "defaultUriProtocolHandlers":
    {
       "ssh": "{00000000-0000-0000-ba54-000000000001}"
    },

    "profiles":
    [

        {
            "guid": "{00000000-0000-0000-ba54-000000000001}",
            "commandline" : "%UserProfile%/scoop/apps/git/current/usr/bin/ssh.exe -p ${uri.port} ${uri.user}@${uri.host}",
            "startingDirectory": "%UserProfile%",
            "background": "#000000",            
            "fontFace": "Source Code Pro",
            "icon" : "c:\\opt\\icons8-console-96.png",
            "backgroundImage": "C:\\Users\\trajano\\OneDrive\\app-background\\terminal.png",
            "backgroundImageOpacity": 0.1,
            "name" : "SSH",
            "handlesUriProtocol" : "ssh"
        },
```

Note I used `uri.` to prefix it so we don't pollute the default namespace.

**Comment by zadjii-msft** [comment]
I mean it seems a _lot_ easier to just do <kbd>win+r</kbd>`wt ssh admin@server.com`<kbd>enter</kbd> then hook all that up, right?

**Comment by trajano** [comment]
@zadjii-msft except it seems less seamless 

If Terminal had this capability then it can probably register itself as a protocol handler for Windows as well so if we click on a link that looks like ssh://me@foo.com it will start up terminal

**Comment by vbyrd** [comment]
I created a small launcher script and protocol registry entries to do exactly this.

https://github.com/vbyrd/windows-terminal-ssh-protocol-handler

**Comment by DHowett** [comment]
Thanks @vbyrd! Yeah -- in general, I think this is something the community is better-equipped to handle than us. Registering a protocol handler, especially by default like that, is something that I'd like the user to explicitly opt into.

At the same time, I'm not liable to put too many ssh-specific features into Terminal itself. If anything, it would be part of the extension that /dup #1280 turns into.
