### ISSUE TITLE
Automatically switch between dark and light themes based on global operating system dark/light setting

### ISSUE THREAD

**Issue by cdmihai** [microsoft/terminal#6658]
# Description of the new feature/enhancement

To reduce eye strain, add a feature to Terminal to automatically change themes based on the global operating system dark/light theme setting.
Right now this is tedious and time consuming to do in Terminal, as it requires the user to manually edit the settings.json and alternate between two themes.

Working with a dark theme in a strongly lit environment, or with a light theme in a gloomy/dark environment puts a lot of strain on my eyes, as I have to squint a lot. Ideally I'd want dark themes on all the OS apps in dark environments, and light themes on all the OS apps in light environments.
Most of the places I work at transition from strong light to gloom throughout the day. I manually transition everything from dark to light and vice versa, as the light changes. This is tedious and time consuming, as very few apps change their theme based on the global OS setting. I change the OS, and then manually change VSCode, Visual Studio, Terminal, and Teams. It would be awesome if all of these automatically changed based on the OS, including Terminal.

# Proposed technical implementation details (optional)

Introduce another setting that chooses between two themes, based on the OS settings:
```json
"switch.themes.based.on.os": "true",
"light.os.theme": "One Half Light",
"dark.os.theme": "Campbell"
```

**Comment by DHowett** [comment]
Thanks for the request! This is being tracked in /dup #6491.
