### ISSUE TITLE
Some UTF-8 characters take two placeholders in render buffer

### ISSUE THREAD

**Issue by 5HT** [microsoft/terminal#666]
Microsoft Windows [Version 10.0.18894.1000]

Reproduce. In both WSL and CMD consoles create files with UTF-8 in name or content. Try to display this content by using either MC or FAR. The character takes two placeholders in render buffer (unexpected), but it should take only one (expected). Here are some examples with RU language in UTF-8 (chcp 65001).

FAR:

![Capture](https://user-images.githubusercontent.com/144776/57538502-3594cc00-7351-11e9-8aa9-da85d91ab6e1.PNG)

MC:

![Capture2](https://user-images.githubusercontent.com/144776/57538505-37f72600-7351-11e9-9217-c475b736478f.PNG)

**Comment by zadjii-msft** [comment]
@miniksa related to the other character sizing issues probably, yea?

#633 and maybe #455 seem similar

**Comment by PhMajerus** [comment]
I don't think this is related to the issue I described in #455, I see random � being inserted between characters that are rendered fine on other lines, and can even appear and disappear when the zoom level is changed. So it's not the width for some specific characters that gets consistently assumed to be two columns.

**Comment by miniksa** [comment]
I was trying to narrow down where the � are coming from prior to the Build conference and didn't finish. So I'll just hold onto these until I get a moment and try to track them all down (and any similarities/differences among them)

**Comment by munchumunch** [comment]
I have a similar issue where terminal applications become misaligned vertically and � characters are occasionally drawn in place of  a '─' character, (e.g.  ─────���────). I notice it particularly with the application slack-term (https://github.com/erroneousboat/slack-term). The potentially interesting part is that closing and reopening slack-term will usually remove the � characters and properly render them as a line. When repeatedly opening and closing slack-term the � characters appear only occasionally, but when they do they appear, they appear in exactly the same location.  I hope this information is useful.

**Comment by miniksa** [comment]
![image](https://user-images.githubusercontent.com/18221333/80040430-e9ce2a80-84ae-11ea-904e-22c80c8e6059.png)

Looking decent to me.
