### ISSUE TITLE
Enable word wrapping like in original cmd.exe shell

### ISSUE THREAD

**Issue by CarlosOnline** [microsoft/terminal#6663]
Original cmd shell provides screen buffer size / window size settings that allow long lines to stay on a single view line instead of wrapping to next line.

Please add the same functionality.  

![image](https://user-images.githubusercontent.com/3691895/85621940-f429b380-b61a-11ea-999f-7f7baf3e11a4.png)

**Comment by DHowett** [comment]
We are not adding an option to _disable_ line wrapping. Sorry.

**Comment by CarlosOnline** [comment]
I am not using your product.

**Comment by zadjii-msft** [comment]
For the record, this is explained in greater detail in https://github.com/microsoft/terminal/issues/1860#issuecomment-509311231. Having rows of text that are longer than the width of the viewport is something that' pretty fundamentally incompatible with traditional terminal emulation. Conhost had far too many bugs related to non-wrapped lines not working with VT sequences, and we're not about to hop back in to that pit of snakes.

If non-wrapped lines are something that you _really_ want, there are commandline tools that you might be able to use to achieve the same effect. I believe that `less` allows you to pipe text to it, and view it "unwrapped".
