### ISSUE TITLE
Subpanels to open with the same type as the initial panel, rather than the default profile

### ISSUE THREAD

**Issue by wduraes** [microsoft/terminal#6666]
I set my default profile as Linux/Ubuntu. But I have multiple profiles, one for Azure, one for SSH into my Raspberry pi, one for Git CMD, etc. 

When I have -say- a CMD tab opened, and I create a subpanel (ALT/Shift/+ or ALT/Shift/-) a new subpanel will be opened - splitting the screen vertically/horizontally, but this new subpanel won't be a CMD subpanel, it will be an Ubuntu subpanel, because that's my default profile. 

As a user, if I'm in a CMD tab, and I open a subpanel I would expect this to continue to be CMD, not the default profile. 

One implementation approach could be to open subpanels to follow whatever the initial panel was (example: I opened a PowerShell tab, and create a subpanel, so I would see this new subpanel to be PowerShell too). 

One alternative, could be a  new setting to say: "open subpanels with the same type of the initial tab" or "open subpanels with the default profile".

**Comment by DHowett** [comment]
So, you can set this up yourself. Right now, we offer three bindings (by default);

* <kbd>alt+shift+d</kbd>: open auto-sized split with the current active profile
* the two you are talking about, which open the default profile

Fortunately, you can configure customize any key binding. For the split pane ones, you can add `"splitMode": "duplicate"`

**Comment by wduraes** [comment]
Thank you, " alf+shif+d" works fine indeed!
