### ISSUE TITLE
Powerline glyphs hidden and some characters scaled improperly on re-rendering

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#6669]
/cc @miniksa

# Environment

```none
Windows build number: 10.0.20156.1000
Windows Terminal version: 1.2.1751.0
```

# Steps to reproduce

1. Open Terminal (my default profile is PowerShell 7 w/ Powerline theme, Cascadia Code PL font)
2. Open new tab (CMD)
3. Switch back to first tab
4. Switch back to second tab

# Expected behavior

Text looks consistent and all of it is present

# Actual behavior

![Repro Gif](https://user-images.githubusercontent.com/11050425/85638331-7c6b8100-b63a-11ea-8038-6ed1ca1a9bd7.gif)

**Comment by DHowett** [comment]
Chatted, seen, triaged.

**Comment by DHowett** [comment]
Got a repro here too.

![image](https://user-images.githubusercontent.com/189190/85894284-4c8ebb80-b7a9-11ea-9565-a7624ae1a0b0.png)

**Comment by DHowett** [comment]
Symptom: the _first glyph of every run_ gets crunked down to a tinier size.

**Comment by miniksa** [comment]
looking.

**Comment by miniksa** [comment]
<code>"`u{fffd}"</code>

**Comment by miniksa** [comment]
`_glyphScaleCorrections` wasn't being cleared between uses of the layout.
