### ISSUE TITLE
Split Panes Issue

### ISSUE THREAD

**Issue by abexultan** [microsoft/terminal#6672]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.0.1401.0

WSL with Ubuntu 20.04 installed 
```

# Steps to reproduce

1. Open a terminal with WSL of your choice
2. Split the pane with `alt-shift-plus` or `alt-shift-minus`

# Expected behavior

New pane should operate with terminal of your WSL.

# Actual behavior

New pane opens Windows PowerShell.

## Note:
`alt-shift-d` creates the pane as in **Expected behavior**, but it splits only horizontally.

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/issues/6666#issuecomment-649066525

/dup #6666 
You can customize it however you please.
