### ISSUE TITLE
bind "copy" to "alt+c",  "alt(the left) + c" can't copy the text  

### ISSUE THREAD

**Issue by ymkun** [microsoft/terminal#6673]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Windows build number: [20H2, wsl]
Windows Terminal version (if applicable): 1.1.1671.0  (Preview)

# Steps to reproduce

1. Bind "copy" to "alt+c",   part of my settings.json : 
    "keybindings":
    [
    	{"command" : "copy", "keys" :"alt+c",},
        {"command" : "paste", "keys" :"alt+v",}
    ]

2. Press "alt(the left) + c"

# Expected behavior

Copy the selection text,  if no selection,  empty string will be copied.

# Actual behavior

 can't copy the text, but will terminal the runing process like "ctrl+c".  While  "alt(the right) + c" can copy the text.

**Comment by ymkun** [comment]
Even I didn't  bind  anything to "alt+c",   press "alt(the left) + c" will terminal the runing process like "ctrl+c"......

**Comment by zadjii-msft** [comment]
That's certainly curious. 
* Does <kbd>LeftAlt + V</kbd> work to paste? 
* What keyboard layout are you using?

**Comment by ymkun** [comment]
Sorry,  I have found the reason.  I remaped the "LeftAlt + C" to "Ctrl+C" in "PowerToys".  Thanks.

**Comment by zadjii-msft** [comment]
Glad you figured it out!
