### ISSUE TITLE
The Tab Color Picker should be navigable with the arrow keys

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6675]
Especially following #6567 (and moreso following #6635).

Once we open the picker, I want to be able to navigate the buttons with the arrow keys, and then hit <kbd>enter</kbd> to select a color.

You can cycle through the entire list with <kbd>tab</kbd>, but the arrow keys seem like they'd be more intuitive IMO.

**Comment by BenConstable9** [comment]
Hello @zadjii-msft, I have implemented this as was looking for a very easy starter to do. I will submit a PR.
