### ISSUE TITLE
Import/export command line arguments for settings

### ISSUE THREAD

**Issue by erichiller** [microsoft/terminal#6676]
# Description of the new feature/enhancement

*note*: this is not for exporting only color schemes as I understand `colortool` already does this, this request is for actual **wt** settings.

Add `-import <path>` and `-export <path>` flags to `wt` which will then import/export from/to the given path.

It could be a simple copy and paste of the user settings or export user defined settings and on import check the schema to see if the settings file format has updated. To tell the version of the file being imported, just put a comment at the top of the settings file when it is exported.

This would provide portability between computers and easy sharing of settings between users.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Hey, thanks for the request!

@zadjii-msft likely has an opinion here, but I'm inclined to say that this is better served by #2933 ("let me move my settings, or roam it" -- once it's moved, it's in an easier place from which to share it) or perhaps something subjugate to #1564 (an [export]/[import] button pair?)

I'm going to tag this up for the backlog, but: Mike, will you be my triage-second, or close this as a dupe?

**Comment by zadjii-msft** [comment]
Honestly yea, in my opinion the other two would serve this use case better. IMO, let's just close this one as a /dup #2933 #1564. @erichiller if you've got a compelling reason why the two aforementioned solutions _wouldn't_ work for you, we can continue the discussion and possibly reopen.
