### ISSUE TITLE
How does the PowerShell Core function get the path of PowerShell Core?

### ISSUE THREAD

**Issue by haydennyyy** [microsoft/Terminal#668]
The function in question is in Terminal/TerminalApp/CascadiaSettings.cpp (line 328). I wondered... Does it check for an environment variable called `PowerShell`, or is it looking for that in PATH?
I'm asking because I want to try and detect installed WSL environments to script in an automatic profile creation function for WSL distros.

**Comment by zadjii-msft** [comment]
I believe what's happening in `CascadiaSettings::_IsPowerShellCoreInstalled` is we're trying to expand any environment variables that are in the path in `programFileEnv`, then appending "Powershell" to that path, and checking if `pwsh.exe` exists underneath that path.

I don't believe there's a `%Powershell%` we're checking for. We're actually just looking in either `"%ProgramFiles%"` or `"%ProgramFiles(x86)%"`

**Comment by haydennyyy** [comment]
Ah, so could I do something similar but look for `%Windows\System32%` and then `ubuntu`, `wsl`, `debian`, etc.?

**Comment by zadjii-msft** [comment]
Ah see, that's not where those actually live. The wsl exe's are actually App Execution Aliases, and they live in `%localappdata%\Microsoft\WindowsApps\`. Note that _all_ app execution aliases live there, not just the WSL distros.

**Comment by haydennyyy** [comment]
Right. So going straight to the WSL exe's would be a bad idea then? 😅
