### ISSUE TITLE
Remove workaround "When we add a new tab in compact mode, re-enforce Compact mode"

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6681]
When we get a version of WinUI with a fix for https://github.com/microsoft/microsoft-ui-xaml/issues/2711, we can go ahead and revert #6670. This task is tracking that future work.

**Comment by DHowett** [comment]
Triaged

**Comment by chingucoding** [comment]
The new prerelease of WinUI (2.5.0.prerelease.200708003) contains the fix for TabView, so with that prerelease, the workaround can be removed.

**Comment by chingucoding** [comment]
I would like to work on this issue.

**Comment by zadjii-msft** [comment]
Go right ahead! You'll probably need to bump our MUX version up across the entire solution. I'd take a look at https://github.com/microsoft/terminal/blob/master/doc/building.md#updating-nuget-package-references for a quick and dirty script for doing that part ☺️

**Comment by chingucoding** [comment]
Thanks for the link, I just noticed that for some reason, in the documentation I chose to make the Oldversion higher then the Newversion. Mind if I create a separate PR to fix this? The current way it is presented might be a bit confusing for other folks reading that part.

**Comment by zadjii-msft** [comment]
Oh yea totally - that's probably my bad from the last time I used this script. It probably also bumped the version number _within the script itself_ 😃

**Comment by chingucoding** [comment]
Oh right haha, just noticed it doing this on my machine too! Maybe we should choose some nonexistent versions so this doesn't happen again 🤔?

**Comment by zadjii-msft** [comment]
Yea probably haha
