### ISSUE TITLE
Proposal: Add support for compact overlay\always on top

### ISSUE THREAD

**Issue by yaichenbaum** [microsoft/terminal#6683]
# Support for compact overlay or always on top functionality
Adding an option to keep Terminal on top of other windows would be really helpful, there are several ways this could work and either of them would be a welcome addition.
- **Compact Overlay** where there are less options and the window size is more compact (Calculator does it this way).
- **Always on top**, this would be the regular window and the only thing that would change is that the app stays on top of other windows.

![image](https://user-images.githubusercontent.com/39923744/85798944-64643200-b70c-11ea-992b-7d0879bcad11.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestions! You're probably looking for:
* #2238 - "borderless" / "compact" mode
* #3038 - Always on Top

/dup #2238
/dup #3038
