### ISSUE TITLE
Emojis work properly but sometimes they don't.

### ISSUE THREAD

**Issue by debopamgupta** [microsoft/terminal#6688]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version : 1.0.1401.0

Git Bash might not really be tied to only this.
```

# Steps to reproduce

Have a javascript file which console.logs emojis and some text. run that thru node or do a `yarn install` with `--emoji true` flag.

# Expected behavior

To display emojis perfectly alright

# Actual behavior

It works for some emojis and not always but if `cat` or `type` is run then it shows emojis perfectly.

![](https://i.imgur.com/TtLtpx7.png)
The sparkles emoji is fine but the others are not

![](https://i.imgur.com/7HV9nn8.jpeg)

As you can see, in node it doesnt work. but while catting it it does work and the check mark and some others are the only that works

**Comment by debopamgupta** [comment]
I just tested the same on Hyper Terminal and can say that the issues with yarn occurs there as well and in  a same way, the single width characters such as ✅ or ✨ show up correctly.

**Comment by debopamgupta** [comment]
An update, i had a screen recording for a vide dated in Apr 2 2020, in which i used a tool callled vercel to deploy my website. Their CLI just like yarn used emojis and the emojis worked fine although the check mark was small.
![](https://cdn.discordapp.com/attachments/704635164386525235/726058206580965436/unknown.png)

But in my version now, only the checkmark shows up not the other ones.
![](https://cdn.discordapp.com/attachments/704635164386525235/726058660437950555/unknown.png)

**Comment by DHowett** [comment]
If you copy/paste those <?> characters into a text editor, do they come back out as Emoji?

**Comment by DHowett** [comment]
Debugging: _the character coming out of node has already been replaced with U+FFFD_. It's been corrupted before the console subsystem even gets it.

They must have changed something that made them even worse console citizens than they already were.

**Comment by debopamgupta** [comment]
#### 1

> If you copy/paste those <?> characters into a text editor, do they come back out as Emoji?

If i just  copy and paste, they still remain the same <?> characters.

#### 2

If i put the output to a file while in node, it works fine and are emojis.

![image](https://user-images.githubusercontent.com/51162936/85913801-61c12400-b855-11ea-960e-56dadf229bd1.png)

And this is more interesting 

![image](https://user-images.githubusercontent.com/51162936/85913865-1ce9bd00-b856-11ea-9b2f-de4c204ffb87.png)

maybe it is infering when to use emojis if it is in console or not.

**Comment by debopamgupta** [comment]
This condition checks for the os and the platform/terminal 
https://github.com/yarnpkg/yarn/blob/ac21dbf16a5d2d5f4cb032f5da5313949db3fb71/src/cli/index.js#L112

So yarn kinda will not bother much. But the thing still will persist with Vercel as they render emojis whatsoever and also with a tool called [now-config](https://www.npmjs.com/package/now-config) which prints emojis whatsoever

**Comment by debopamgupta** [comment]
hey @DHowett any updates / investigations / thoughts about this issue?

**Comment by DHowett** [comment]
Unfortunately, all I can find here is applications or runtimes that are failing to pass the emoji through. 

Node for Windows refuses to send the emoji correctly. Evidence: node under WSL works fine, with the same javascript file. ☹️ 

![image](https://user-images.githubusercontent.com/189190/87106419-43bed080-c212-11ea-9b2d-7bc5a2618bea.png)

**Comment by DHowett** [comment]
I've gotta resolve this one as external. If we go make enough noise over on the Node repo, perhaps they'll listen.

**Comment by DHowett** [comment]
Some more info here; https://github.com/nodejs/node/commit/086482da6dc50693c72a25a64774103e6c1a5e1a

**Comment by DHowett** [comment]
And here is the code where they make an incorrect assertion about our Unicode support.

https://github.com/nodejs/node/blob/1198aebd2db710b22bfed003edcf8cca2db8a174/deps/uv/src/win/tty.c#L2124-L2129
