### ISSUE TITLE
Scroll Lock button support to lock the terminal from scrolling

### ISSUE THREAD

**Issue by lcsondes** [microsoft/terminal#6694]
# Description of the new feature/enhancement

Support Scroll Lock to lock text from scrolling if I want to look at something that was briefly visible but is now off screen because there's a constant stream of new output from, e.g., compiling or watching some logs live with `tail`.

# Proposed technical implementation details (optional)

If I have Scroll Lock on, new output arriving into the terminal should not scroll it down so I can keep reading what's currently visible on screen. Having Scroll Lock off would restore the behavior that's the only one as of writing.

**Comment by DHowett** [comment]
I agree. We've got a couple specs in flight here (#2529, for #980), and #3863 mentions scroll lock. Once we have keyboard selection (#2840 spec), that'll include keyboard buffer navigation, and we can extend #2529 to cover scroll lock as well. We're also considering "mark" mode (a mode you switch into where you can navigate the buffer solely by keyboard)

/dup #3863, #715
