### ISSUE TITLE
In Solarized themes, some things aren't visible in powershell

### ISSUE THREAD

**Issue by jszabo98** [microsoft/terminal#6696]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

Set theme to Solarized Dark or Solarized Light and run Powershell.

# Expected behavior

For Solarized Light, I expect to be able to see numbers and members.  For Solarized Dark, I expect to be able to see operators and parameters.

# Actual behavior

I cannot.

In Solarized Light, bright white is set to the same color as the background.  So any token set to bright white becomes invisible.  This is from get-psreadlineoptions:

```none
Member             "$([char]0x1b)[97m" # bright white
Number             "$([char]0x1b)[97m" # bright white
```

In Solarized Dark, bright black is set to the same color as the background.  So any token set to bright black becomes invisible.  This is from get-psreadlineoptions:

```none
Operator           "$([char]0x1b)[90m" # bright black
Parameter          "$([char]0x1b)[90m" # bright black
```

A workaround for Solarized Light (console colors and ansi colors have slightly different names):

```powershell
if (test-path env:wt_session) { set-psreadlineoption -colors @{member =
  'darkblue'; number = 'red'}}
```
I didn't understand how the themes "redefine" colors like black, red, green, etc.  This could be better explained in the docs for schemes.

**Comment by DHowett** [comment]
/dup #6424 #6390 #6286 #6283 #6208 #6121 #6061 #5896, resolved by #6617 #6618 #6489 (all three are currently in review)

**Comment by jszabo98** [comment]
Fyi, here's the commonly used ansi colors in powershell:

```powershell
Command            "$([char]0x1b)[31m" red # 93 bright yellow
Comment            "$([char]0x1b)[32m" green
ContinuationPrompt "$([char]0x1b)[37m" white # 33 yellow
DefaultToken       "$([char]0x1b)[37m" white
Emphasis           "$([char]0x1b)[96m" bright cyan
Error              "$([char]0x1b)[91m" bright red
Keyword            "$([char]0x1b)[92m" bright green
Member             "$([char]0x1b)[97m" bright white
Number             "$([char]0x1b)[97m" bright white
Operator           "$([char]0x1b)[90m" bright black
Parameter          "$([char]0x1b)[90m" bright black
Selection          "$([char]0x1b)[30;47m" black on white # 35;43 magenta;yellow
String             "$([char]0x1b)[36m" cyan
Type               "$([char]0x1b)[37m" white
Variable           "$([char]0x1b)[92m" bright green
```

**Comment by jszabo98** [comment]
Maybe you should leave one of these open?  People are less likely to search closed issues and pull requests.

**Comment by SubaruArai** [comment]
For anyone coming here from googling, #14859 is an ongoing issue tracker for light themes overall.
