### ISSUE TITLE
include where as keyword

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/terminal#6697]
# Description of the new feature/enhancement
Include `where` as keyword, it is really pain in the ass to write `where.exe` instead of `where` in powershell. Just like old cmd, include `where` as a keyword, in is awesome cool project. I think it will be worth it.

**Comment by DHowett** [comment]
Terminal is running a completely normal "old cmd" inside it, if you choose to run command prompt.

![image](https://user-images.githubusercontent.com/189190/85906179-5ffa5080-b7c2-11ea-833a-7fd9e2b4ab3e.png)

If you're using powershell, that's a request you'll need to file on [the powershell repository](https://github.com/powershell/powershell)

Remember, terminal is not a new shell. It's a new box for your old shells to live in.
