### ISSUE TITLE
Provide Windows Terminal (Administrator) in the quick list.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/terminal#6701]
# Description of the new feature/enhancement

It's annoying having to open the Terminals quick list then right click Windows Terminal then Run as Administrator. It feels like I'm doing a step twice.

Can we please have an entry for Windows Terminal (Administrator) right there in the quick list. So launching terminal as admin would involve..

1. Right click Terminal Icon on the task bar.
2. Select Windows Terminal (Administrator).

# Proposed technical implementation details (optional)

I don't know if quick lists support launching an app in admin mode, but it would be helpful if they did.

**Comment by j4james** [comment]
Is this not the same thing as #4459?

**Comment by Gavin-Williams** [comment]
@j4james Yes it is.

**Comment by DHowett** [comment]
Thanks! /dup #4459
