### ISSUE TITLE
Add support for SGR 2 Faint

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/terminal#6703]
We do not support Faint text.

<details>
<summary>Original content</summary>

# Description of the new feature/enhancement

Windows Terminal doesn't appear to support the *dim* ansi escape code (SGR 2) or *italic* (SGR 3). Adding support for these would I think bring WT up to feature parity with most OSX and Linux terminals.

There are other SGR escape codes that would be nice to have, but aren't as common or as useful as dim and italic.

# Proposed technical implementation details (optional)

Dim strikes me as an easy one to achieve. I imagine italic would be a little trickier.

</details>

**Comment by DHowett** [comment]
Thanks!

This is a curious issue. We're tracking all manner of different versions of "terminal doesn't render specific attributes":

* #109 enable bold (this is a very divisive issue), #5384 "should bold apply to ITU indexed colors", #5682 "is bold 1;39 a separate color?"
* #2916 support parsing faint/a couple others
* #5461 italics aren't being rendered

I just started tackling #109, despite it being divisive, and I think the infrastructure we need to build to get it off the ground (a "base + variant" system for fonts) is going to be required for this.

I'm going to close this shortly but rework all of the above issues into an amalgamated "we should support different attributes, from parsing through to rendering" issue. Does that sound good?

**Comment by willmcgugan** [comment]
Sounds good to me 👍

**Comment by csdvrx** [comment]
> I'm going to close this shortly but rework all of the above issues into an amalgamated "we should support different attributes, from parsing through to rendering" issue. Does that sound good?

I added #6779 which provides a test script and an expected output.

It links another issue: there is no font switching, which would be useful for mixing different fonts.

**Comment by j4james** [comment]
@DHowett I've just realised this has been assigned to you, and wanted to check exactly which parts you're working on, or planning to work on. Reason being I was about to start on the faint attribute, as a follow up to the color refactoring in PR #6853, but if you already have plans for that, I can leave it to you.

**Comment by DHowett** [comment]
@j4james it’s assigned to me for administrative reasons; I’m going to create a scenario for the various attributes impacting the display of text, and then close/rework some of the ones we already have open to fit under it. If you want to do work in this area, you’re welcome to :smile: I just may change which issue number your PR eventually closes

**Comment by DHowett** [comment]
I've repurposed this to track Faint, and crossed out mention of Faint in #2916. Your pull request can unabashedly close this issue and drop mention of 2916.

**Comment by DHowett** [comment]
I've filed #6879 to track "all" attributes.
