### ISSUE TITLE
Allow explorer location bar shortcut

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#6704]
# Description of the new feature/enhancement

With Windows Explorer, you can go to the location bar and type in `cmd` to bring up the command prompt at the proper location.  I'd like to be able to do the same with `wt` and setting the current path accordingly.  (wt should just add a new tab rather than starting up a new process)

![image](https://user-images.githubusercontent.com/110627/85937068-1dbe3580-b8ce-11ea-9664-b9a4dddd1bf1.png)

After pressing enter

![image](https://user-images.githubusercontent.com/110627/85937080-2d3d7e80-b8ce-11ea-87ff-79a654cd3427.png)

# Proposed technical implementation details (optional)

Some miracle? :P not exactly sure how it will be implementable.

**Comment by DHowett** [comment]
Try out `wt -d .`. Because a profile can contain a "starting directory", this is the most reliable way to override it.

For "opening a new tab in an existing window", you'll want to follow #5000.
