### ISSUE TITLE
Open the terminal for the explorer location bar

### ISSUE THREAD

**Issue by arnaudlegout** [microsoft/terminal#6709]
# Description of the new feature/enhancement

A poorly known feature of the windows explorer is that you can open the cmd from the explorer location bar. 
1. open the explorer
2. navigate to the desired directory (in this example `C:\Program Files (x86)\Microsoft Office\Office16`)

<img width="962" alt="Sans titre" src="https://user-images.githubusercontent.com/7670869/85988934-11ca9480-b9f0-11ea-8a06-c6ad0a1794bd.png">

3. write `cmd` in the location bar (by replacing the directory location) and hit enter

<img width="962" alt="Sans titre2" src="https://user-images.githubusercontent.com/7670869/85988957-1db65680-b9f0-11ea-9b41-82d5617e5c21.png">

=> it opens the cmd in the current directory. 

![image](https://user-images.githubusercontent.com/7670869/85989396-bbaa2100-b9f0-11ea-890e-b28842cb7789.png)

This is the most convenient and streamlined way to open a cmd from the explorer, way faster and more convenient than the right click. 

My proposed feature is to be able to open the terminal from the explorer location bar by entering `term` (instead of `cmd` when
you want to open the command prompt)

![image](https://user-images.githubusercontent.com/7670869/85989449-cc5a9700-b9f0-11ea-92f2-2b4623239d17.png)

depending of the default shell, it will open this shell as a Windows directory, or as a linux directory. 

# Proposed technical implementation details (optional)

I don't have any hint to how to implement this feature.

**Comment by DHowett** [comment]
Thanks for the request! You can use `wt` or `we -d .` for this.

**Comment by hughian** [comment]
> Thanks for the request! You can use `wt` or `wt -d .` for this.

can `wt` open in the current directory just like 'cmd',  because `wt -d .` seems a little inconvenient.

**Comment by arnaudlegout** [comment]
it is really inconvenient.

With cmd
- click the location bar
- write cmd
- hit return
done!

with wt
- click the location bar
- go left
- write wt -d
- hit return
done!

the go left step is error prone and very inconvenient when you do that 
all the time.

Also, using the location bar to open a terminal that is not in the 
current directory is a
very strange use case (instead I would go on [windows key] term, which 
is way faster and more
standard). The default use case (when we enter `wt` in the location bar) 
must be to open a
terminal in the current directory. Why do we want enter `wt -d` for that?



Le 02/07/2020 à 05:07, hughian a écrit :

**Comment by arnaudlegout** [comment]
it is really inconvenient.

With cmd
- click the location bar
- write cmd
- hit return
done!

with wt
- click the location bar
- go left
- write wt -d
- hit return
done!

the go left step is error prone and very inconvenient when you do that 
all the time.

Also, using the location bar to open a terminal that is not in the 
current directory is a
very strange use case (instead I would go on [windows key] term, which 
is way faster and more
standard). The default use case (when we enter `wt` in the location bar) 
must be to open a
terminal in the current directory. Why do we want enter `wt -d` for that?

Le 02/07/2020 à 05:07, hughian a écrit :

**Comment by zadjii-msft** [comment]
Don't bother with the "go left" step. Use `wt -d .`. The `.` is important - it means "open the Terminal in the current directory". That way, the work flow is
- click the location bar
- write `wt -d .`
- hit return 
done!
