### ISSUE TITLE
Terminal: UIA test harness

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#671]
Terminal project needs UIA tests set up in a similar vein to the conhost tests.
Should use WinAppDriver.
Probably C#.

Need to add it to the runuia.cmd in the tools directory too.

Then in either this issue (or another one if it doesn't happen here), we need to get it running in the azure pipeline one way or another too. (I'd rather have the test harness checked in and locally runnable first even if it can't be a part of azp yet.)

Assigning directly to Hassan because he was working on this before Build,

**Comment by adiviness** [comment]
if we're adding it to runia.cmd then it should also be added to the powershell module in that same directory.

**Comment by hassanuz** [comment]
Not know about adding this to runuia.cmd - mostly because it's calling on TAEF, and I'm not sure how compatible TAEF would be inside DevOps.

**Comment by DHowett-MSFT** [comment]
Our tests _only_ exist in TAEF, so it practically must work in devops.

**Comment by carlos-zamora** [comment]
@DHowett-MSFT This might be a fun thing for us to discuss offline. Especially now that accessibility is in a more stable position.

**Comment by zadjii-msft** [comment]
@miniksa Oh uh hey, this was totally done in #10071 wasn't it?

**Comment by miniksa** [comment]
> @miniksa Oh uh hey, this was totally done in #10071 wasn't it?

YEP
