### ISSUE TITLE
Terminal color output not displaying as expected 

### ISSUE THREAD

**Issue by laballab** [microsoft/terminal#6711]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18363.900]
Windows Terminal version (if applicable): Version: 1.0.1401.0

All steps/tests are done in a git-bash profile in windows terminal. 
```

# Steps to reproduce

I can consistently reproducing this issue by running k9s with invalid kubeconfig. K9s will output a red-colored warning regarding this which is not rendered properly on windows terminal. 

# Expected behavior

A colorful error message warning us about the invalid kubeconfig:
![image](https://user-images.githubusercontent.com/12739256/86019757-ff9f2500-b9f4-11ea-97b9-fe894332579e.png)

# Actual behavior

Windows terminal is not rendering the color output properly: 
![image](https://user-images.githubusercontent.com/12739256/86019602-cd8dc300-b9f4-11ea-9956-e3093d3592ed.png)

**Comment by laballab** [comment]
It seems the color commands are being interpreted as utf-8 arrows for some reason.. It's strange this bug isn't present in the bash prompt as the same color commands are used there and the colors are rendered properly.

**Comment by DHowett** [comment]
Huh, thanks for the report.

This is the same root cause as https://github.com/microsoft/terminal/issues/6634

More info at https://github.com/microsoft/terminal/issues/6634#issuecomment-647726408

/dup #6634 
Unfortunately, this is an application bug ☹️
