### ISSUE TITLE
Debug logs for wt.exe?

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#6713]
Hello.

When I install and run Windows Terminal in our company environment (W10 1903) I get an error message. The error message says "Service has not been started".

For me it's really hard to analyze this error without knowing the name of the missed service.

**Question:** Is there a parameter or something to get detailed debug logs, where I can see more details on the problem?

Thank you for helping me.

**Comment by DHowett** [comment]
Unfortunately, wt isn't even getting started to the point where our debugging infrastructure would be helpful for you. This sounds like **AppXSvc** may not be running.

**Comment by htcfreek** [comment]
The interesting thing is, that other built-in apps like Paint3D working without error.

**Comment by htcfreek** [comment]
I have fixed the issue in our environment.

Solution:
Enable the **"Microsoft account cloud authentication service" (wlidsvc)**.

Maybe this can be added to a wiki or to the readme.md under prerequisites or faq section.

**Comment by DHowett** [comment]
Thanks for the info. I appreciate you contributing to our other offline access threads as well :smile:

Once we've coordinated with the licensing team, I'll make sure our docs are updated to match.
