### ISSUE TITLE
windows server 2019 - no go...?

### ISSUE THREAD

**Issue by ecc256** [microsoft/terminal#6717]
Tried to install to windows server 2019:

`choco install microsoft-windows-terminal`

_ERROR: This package requires at least Windows 10 version 1903/OS build 18362.x.
The install of microsoft-windows-terminal was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-windows-terminal\tools\chocolateyInstall.ps1'._

Is it even possible?

**Comment by DHowett** [comment]
It is not. You need a version of windows equivalent to 1903 or greater. Sorry.

**Comment by ecc256** [comment]
Got it, will be waiting for 2019R2 to try then...
Thanks for clarification!
