### ISSUE TITLE
Inconsistent clearing of selection/text on ESC key press

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#672]
Here's the scenarios:
1. No text in the interactive line. Active selection.
2. Text in the interactive line. Active selection.

## Windows Terminal (before bugfix #647 )
| Shell | Scenario 1 | Scenario 2 |
|-----|-----|-----|
| CMD | selection *cleared* | Text and selection *cleared* |
| Powershell | selection *active* | text and selection *cleared* |
| Ubuntu | selection *active* | text and selection *active* |

## Windows Terminal (after bugfix #647 )
| Shell | Scenario 1 | Scenario 2 |
|-----|-----|-----|
| CMD | selection *cleared* | Text and selection *cleared* |
| Powershell | selection *cleared* | text and selection *cleared* |
| Ubuntu | selection *cleared* | selection *cleared* (pressing again *DOES NOT* clear text) |

## Individual shells
| Shell | Scenario 1 | Scenario 2 |
|-----|-----|-----|
| CMD | selection *cleared* | selection *cleared* (press again to clear text) |
| Powershell | selection *cleared* | selection *cleared* (press again to clear text) |
| Ubuntu | selection *cleared* | selection *cleared* (pressing again *DOES NOT* clear text) |

I can probably match the "selection *cleared* (press again to clear text)" behavior. Is Ubuntu's behavior a bug though? I noticed that though pressing ESC again doesn't clear text, pressing backspace then clears the text (as opposed to just one character).

**Comment by miniksa** [comment]
What did conhost do?

**Comment by eryksun** [comment]
> I noticed that though pressing ESC again doesn't clear text, pressing backspace then clears the text (as opposed to just one character)

bash uses [GNU Readline](https://tiswww.case.edu/php/chet/readline/rluserman.html). It defaults to Emacs edit mode. In this case, pressing <kbd>Escape</kbd> followed by <kbd>Backspace</kbd> (or <kbd>Alt</kbd>+<kbd>Backspace</kbd>) is BackwardKillWord: "Kill from the cursor the start of the current word, or, if between words, to the start of the previous word." 

PowerShell uses [PSReadline](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-6). It defaults to "Windows" edit mode (mislabeled as "Cmd" mode in some of the documentation).  In this case, <kbd>Escape</kbd> is RevertLine: "Reverts all of the input to the current input." You can change to Emacs mode (like bash) via `Set-PSReadLineOption -EditMode Emacs`.

Like most simple console applications, CMD uses the console's (conhost.exe) cooked read. In line-input mode, the console implements command-line editing, aliases, and history for `ReadConsole` and `ReadFile`. (CMD is also one of the few console applications that I know of that actually uses the `pInputControl` parameter of `ReadConsoleW` for command-line completion.)

**Comment by carlos-zamora** [comment]
/dup #3911 
I'm pretty sure that _that's_ the real issue here. Closing as dup
