### ISSUE TITLE
Administrator Powershell And CMD Support For Dropdown Menu

### ISSUE THREAD

**Issue by Thallium000** [microsoft/terminal#6723]
# Description of the new feature/enhancement

Administrator Powershell And CMD Support For Dropdown Menu

# Proposed technical implementation details (optional)

running commands that require admin permissions

**Comment by marveloo** [comment]
I think you should be able to make your own profile with something like:

```
"commandline": "runas /user:administrator powershell"
```

Or alternatively, open Windows terminal as an administrator and you are good to go.

**Comment by arbaazlaskar** [comment]
But lets say you open the windows terminal in the current directory by typing `wt -d .` in the address bar . It opens the terminal in non-elevated mode and there is no option to enter elevated mode in the current directory that i know of. Is there a way to do that? If not, can we add this feature?

**Comment by marveloo** [comment]
I agree, it would be great to have Windows Terminal integration in Windows Explorer's "File" menu in the same way as we have Windows Powershell now:

![image](https://user-images.githubusercontent.com/36376767/86342436-4775b480-bc60-11ea-9836-b87fa3554b5e.png)

So here we need an option "File"->"Open Windows Terminal"->"Open Windows Terminal as administrator".

**Comment by DHowett** [comment]
Thanks for the info! I'm going to fold this into /dup #5000
