### ISSUE TITLE
Open Windows Terminal Here

### ISSUE THREAD

**Issue by GreatZardasht** [microsoft/terminal#6724]
# Description of the new feature/enhancement

Open Windows Terminal Here button when we press shift right click on windows 10.

# Proposed technical implementation details (optional)

Open Windows Terminal Here button when we press shift right click on windows 10 which would open windows terminal to the directory you're in and also an open "WSL ubuntu/linx in windows terminal here" for any WSL things we download off Microsoft store, that would be really useful instead of typing out directories.

**Comment by DHowett** [comment]
This is available on the preview channel today.
