### ISSUE TITLE
title tab bar doesn't update after `.exe` is exited

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#6727]
# Environment

```none
Windows build number:  Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable):

```

# Steps to reproduce

![1](https://user-images.githubusercontent.com/4319522/86146178-e0bc9380-bac5-11ea-9aaa-a4c81409c541.gif)

# Expected behavior

It should update back to `Ubuntu` or whatever is set in `PROMPT_COMMAND`

# Actual behavior

Executables name remains in title tab bar.

**Comment by DHowett** [comment]
Can you confirm that `PROMPT_COMMAND` _is actually setting the title_? because it totally looks like it is blank.

`printf "$PROMPT_COMMAND" | hexdump`

**Comment by musm** [comment]
It does indeed look like it's blank. So launching the `exe` sets the title, but then exiting the `exe` doesn't revert back to the original prompt, because ubuntu doesn't set it to anything?

**Comment by DHowett** [comment]
That’s correct! Sometimes it’s also part of PS1 itself.
