### ISSUE TITLE
Cannot copy text using enter key

### ISSUE THREAD

**Issue by dgolub** [microsoft/terminal#6729]
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): 1.0

Any other software?
```

# Steps to reproduce

Select some text in the Windows Terminal.  Then, either press the enter key.

# Expected behavior

The selected text should be copied to the clipboard.  This is what happens when you follow the same steps in a legacy console window.

# Actual behavior

The enter key is sent to the program running in the terminal.  If you were in the process of typing a command, the command gets executed prematurely.  Your selection is lost and you have to go back, reselect the text, and use Ctrl+C to copy it.

**Comment by DHowett** [comment]
You can add a new key binding that maps `enter` to `copy` and it will work the way you expect. The overwhelming majority of users didn’t want this, by default so we made it a configuration option. 

More info here: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings#clipboard-integration-commands

**Comment by UweKeim** [comment]
For anyone (like me) coming here, this is the string to add to the JSON configuration inside the `keybindings` for [copying with the <kbd>Enter</kbd> key](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#copy):

```json
{ "command": {"action": "copy", "singleLine": false }, "keys": "enter" },
```
