### ISSUE TITLE
Microsoft Visual Studio  --  The Application Data folder for Visual Studio could not be created.

### ISSUE THREAD

**Issue by BartManX** [microsoft/terminal#6731]
Environment:

 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Steps to reproduce:

click settings on tab menu

Expected behavior:

Edit Settings

Actual behavior:

Just a error saying - Microsoft Visual Studio  --  The Application Data folder for Visual Studio could not be created.

![Untitled](https://user-images.githubusercontent.com/1782043/86150270-ce8d2600-bac2-11ea-9235-269422af5714.jpg)

**Comment by DHowett** [comment]
Your default JSON editor appears to be configured to be a broken instance of Visual Studuo. You’ll want to go into your file association settings and fix that :)
