### ISSUE TITLE
Midnight Commander (mc) output is screwed when using the 'ms-terminal' as $TERM

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#6733]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.1.1671.0

Any other software? WSL Ununtu 20.04 LTS
```

# Steps to reproduce

1. Use the latest Ubuntu LTS as the WSL environment.
2. Set the `TERM=ms-terminal`.

    [terminfo.src](https://invisible-island.net/ncurses/terminfo.src.html#tic-ms-terminal)

3. Run `mc`.

# Expected behavior

![image](https://user-images.githubusercontent.com/7956686/86160238-230cc180-bb14-11ea-9aaf-e0facb4115e7.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/7956686/86160104-f658aa00-bb13-11ea-88d9-8512652d3a2a.png)

**Comment by DHowett** [comment]
> Q: Doctor, it hurts when I do this
> A: Don't do that

Do not use the `ms-terminal` terminfo.

**Comment by DHowett** [comment]
We do not maintain that terminfo file, we do not own it, and we have not suggested its use.
