### ISSUE TITLE
Cascadia code included in update, yet old version is reported in filesystem

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#6736]
According to the release documents updating the Windows Terminal, installs and updates Cascadia Code. Where are these fonts located on the Windows filesystem? For example, after todays update, I checked both `C:\Users\Mus\AppData\Local\Microsoft\Windows\Fonts` and `C:\Windows\Fonts` and both of them were on the old release of the font.

**Comment by DHowett** [comment]
The fonts shipped in the terminal package are not stored in the system or user font folders, and any old versions you may have had in those folders are not going to be updated. Terminal doesn't have an installer that is allowed to write to random folders on your system.

You'll need to delete or manually update any copies you have installed of Cascadia Code that are not in the Terminal package.

**Comment by DHowett** [comment]
(point of note: the release notes do not say that it installs or updates Cascadia Code, just that it ships with it :grin:)
