### ISSUE TITLE
Branch rename: master -> main

### ISSUE THREAD

**Issue by jelster** [microsoft/terminal#6739]
# Description of the new feature/enhancement
I know that there could be a decent amount of effort involved in this for a repos with such a large footprint, but I think there's no time like the present to "commit" ourselves (oh god the pun! the 🔥) to (seriously) Doing Better as people, developers, and as global citizens. 

I propose renaming the current `master` branch to `main` as an acknowledgement of the community's commitment to recognizing the existence of racial injustice. However small or trivial an act it may seem to some, I feel that it's a worthwhile undertaking.

As a phrase I'm oft known to cite goes, "excellence is a game of inches". 

 The IETF [presents a detailed discussion](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1) of the reasons why this it is important to note the terminology of branch names, and should be considered a highly useful resource for basing any discussions around context, pertinence, or applicability. 

# Proposed technical implementation details (optional)

Just spitballing OTOMH the things that might be considered as part of executing on this. Obviously, whomever does this would need to have appropriate repos perms :) 

0. Coordinate with any dependent repos' owners on logistics/timing(if needed) ❓ 
1. Disable CI/CD pipelines and PR bots
2. Create `main` branch via operation with `master` checked out via `git branch -m master main` (note the `-m` to keep history intact)
3. Push to `main` origin
4. change default branch in GH from `master` to `main`
5. Configure `main` branch protection, security, etc rules in GH
5a. Archive/lock or otherwise deprecate `master` branch
6. Re-Enable CI/CD, test/adjust build scripts (if/as needed) 
7. Notify downstream repos ❓

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/PowerShell/PowerShell/issues/12951#issuecomment-643525573> suggests that GitHub might do something to make renaming less disruptive. It may be better to wait for that.

**Comment by DHowett** [comment]
I'm in support of this, and will assign myself. If there's the possibility that MSFT will roll out a self-service tool that'll properly update refs, PRs, and internal forks I'd prefer to wait for that.

**Comment by DHowett** [comment]
We now have a self-service tool that'll do this and retarget all open PRs and stuff, so here goes!

![image](https://user-images.githubusercontent.com/189190/96663611-d983f480-1305-11eb-9995-d5f74c87523f.png)

(I'll press it once #7985 merges.)

**Comment by jelster** [comment]
👍 That’s great news! Thanks for staying on top of this - looks like it should be pretty smooth

________________________________

**Comment by WSLUser** [comment]
I'm sad to see MS is giving in to politics. I'm strongly in disagreement to this but MS is a large corporation and can do whatever it wants regardless of what anybody else thinks.

**Comment by DHowett** [comment]
Done!
