### ISSUE TITLE
I get 0xx80070002 error

### ISSUE THREAD

**Issue by Angel0726** [microsoft/terminal#6742]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

when i start my terimal with right click，I get 0xx80070002 error。but when i lanuch it from Microsoft store，it's ok。
![image](https://user-images.githubusercontent.com/32816780/86197679-77ea1f80-bb88-11ea-90db-97eb4867f6b4.png)

![image](https://user-images.githubusercontent.com/32816780/86197620-58eb8d80-bb88-11ea-8221-d6fcbfa1477f.png)

![image](https://user-images.githubusercontent.com/32816780/86197705-89332c00-bb88-11ea-874d-5bb434aa3fae.png)
![image](https://user-images.githubusercontent.com/32816780/86197736-9b14cf00-bb88-11ea-8a20-f8959cf74498.png)

**Comment by DHowett** [comment]
That looks like a custom right click menu option, so you’re on your own for figuring out why it is launching the wrong commands. You might have to check your registry.
