### ISSUE TITLE
Windows Terminal can't use new Cascadia variable font width

### ISSUE THREAD

**Issue by otaconjh** [microsoft/terminal#6745]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1811.0

```

# Steps to reproduce

Install Cascadia Code PL, open settings.json and add 
`"fontWeight": 200`
to defaults and save.

# Expected behavior
Expect terminal to use the new Cascadia Code variable font.

# Actual behavior

fontWeight property not supported by schema and font weight remains the same. This happens for Cascadia (Code | Mono) and Cascadia (Code | Mono) PL.

**Comment by DHowett** [comment]
You need to be on the preview channel to use fontWeight right now.
