### ISSUE TITLE
Windows terminal crashing when RivaTuner is working in background

### ISSUE THREAD

**Issue by Baryczka** [microsoft/terminal#6746]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.330]
Windows Terminal version (if applicable): 1.0.1811.0 and previous stable

Event viewer log:
Faulting application name: WindowsTerminal.exe, version: 1.0.2005.17002, time stamp: 0x5ec1a30d
Faulting module name: RTSSHooks64.dll, version: 0.0.0.0, time stamp: 0x5d76621d
Exception code: 0xc0000005
Fault offset: 0x0000000000004959
Faulting process id: 0x41f4
Faulting application start time: 0x01d64f1ce6b31e4e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
Report Id: 608de0a1-5417-4094-80f4-4387f777f6ff
Faulting package full name: Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Any other software?

**RivaTuner Statistics Server**

# Steps to reproduce
1. Run RTSS
1. Run WindowsTerminal
1. Try to split terminal few times, move between splits, resize window or drag tab

# Expected behavior
Not crashing randomly

# Actual behavior
Randomly crashing without notification, just disappearing 

# Workaround
Set in RTSS WindowsTerminal.exe - Application detection level as none to disable dll hook load

**Comment by DHowett** [comment]
We've seen a good number of crashes, but they're all attributed to RTSSHooks64.dll. Unfortunately, that's _outside of our code_, and I believe there's nothing we can do about it.

It might be worth filing a support request with the developer of RivaTuner to see if they can fix their code.

**Comment by DHowett** [comment]
This is likely related to our choice in UI stack. Magnifier and Perception Input Simulator will probably be seeing similar issues...

**Comment by emergy** [comment]
Same problem
`
Имя сбойного приложения: WindowsTerminal.exe, версия: 1.2.2008.25001, метка времени: 0x5f45901e
Имя сбойного модуля: RTSSHooks64.dll, версия: 0.0.0.0, метка времени: 0x5c83708c
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000005a0c
Идентификатор сбойного процесса: 0x893c
Время запуска сбойного приложения: 0x01d6eb1d09dd78e9
Путь сбойного приложения: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Путь сбойного модуля: C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
Идентификатор отчета: 3ca4b0f2-b6db-4e8b-aaeb-ad15a1278947
Полное имя сбойного пакета: Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe
Код приложения, связанного со сбойным пакетом: App
`

**Comment by Baryczka** [comment]
@emergy Try to update to the latest WT and RTSS. I don't have that problem since long pretty long time.

PS. I forgot! In the RTSS you can add application profile WindowsTerminal.exe - application detection level to none. It should stop injecting that dll and problem for sure will disappear.

**Comment by ragnarsson03** [comment]
Hi, I'm experiencing RTSS crashes on games, for example, RE4 Remake. Nier Automata does get RTSS, but Monster Hunter World Iceborne doesn't, it crashes.

Here's an example of the RE4 Remake crash report:

Callstack's:
Stack[0] : 0x00007ffe9857b699 ( C:\Windows\System32\KERNELBASE.dll )
Stack[1] : 0x000000018008b5cd ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[2] : 0x000000018008b3f4 ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[3] : 0x0000000180009d35 ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[4] : 0x000000018000d558 ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[5] : 0x0000000180014a83 ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[6] : 0x00000001800416e6 ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[7] : 0x000000018004527c ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[8] : 0x00000001800453ff ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[9] : 0x000000018003ae6b ( D:\Program Files\MSI Afterburner\RivaTuner Statistics Server\RTSSHooks64.dll )
Stack[10] : 0x00000001443bfadd ( D:\My Games\Resident Evil 4 2023\re4.exe )
Stack[11] : 0x00000001440b3f44 ( D:\My Games\Resident Evil 4 2023\re4.exe )
Stack[12] : 0x0000000155049b58 ( D:\My Games\Resident Evil 4 2023\re4.exe )
Stack[13] : 0x000000014409ba47 ( D:\My Games\Resident Evil 4 2023\re4.exe )
Stack[14] : 0x00000001436b9b15 ( D:\My Games\Resident Evil 4 2023\re4.exe )
Stack[15] : 0x00007ffe9ab37374 ( C:\Windows\System32\KERNEL32.DLL )
Stack[16] : 0x00007ffe9ac7cc91 ( C:\Windows\SYSTEM32\ntdll.dll )
