### ISSUE TITLE
Unable to save updated defaults.json - even when running as Administrator

### ISSUE THREAD

**Issue by fmorriso** [microsoft/terminal#6749]
# Environment

```none
Windows build number: 1909 (OS Build 18363.900)
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
```
Visual Studio Community 2019 version 16.6.3
# Steps to reproduce

1. Open Windows Terminal

2. While holding down the ALT key, click the dopdown arrow and click on Settings.

3. Wait for default.json to open up in Visual Studio Community 2019 version 16.6.3

4. Within the profiles portion of default.json, change the colorScheme from "Campbell" to "Campbell PowerShell".

5. Try to save the changes - this is where the error begins to happen.

# Expected behavior

Changes to defaults.json would save correctly.

# Actual behavior
Instead of saving the file, the Save File As dialog comes up. 

I'm informed that defaults.json already exists. "Do you want to replace it?"

Any attempt to save the file results in the following error:

Access to path C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1811.0_x64_8wekyb3d8bbwe\defaults is denied.

**Comment by DHowett** [comment]
Your settings—all of them, even ones you wish to apply to every profile—go in your settings.json file. Defaults.json is representative of the compiled-in settings and isn’t even used by the application; it is not intended for user manipulation. 

This is intended to be documented by the comment at the top of the file and the very restrictive permissions. Any ideas on how we can do better here? :smile:

**Comment by joshuasanderson** [comment]
Thanks for the clarification, as this issue was happening to me when I tried to edit the defaults.json file. 

After reading this, I simply opened the settings.json file by clicking the gear icon > Settings. That opened the file in VS2019 and I was able to add my colorScheme of choice to the "profiles" array like so:
![image](https://user-images.githubusercontent.com/4237741/86311278-0349cc00-bbee-11ea-8048-b8df643d6761.png)

Upon saving that file (which I received no warnings about), the Terminal app automatically adjusted to that new theme without having to close and reopen it.

Only thing I would suggest is to update this page here https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes as the wording is a bit confusing leading me to think I have to update the defauts.json file. Thanks!

**Comment by fmorriso** [comment]
The real problem is that the keyboard combination of ALT+Settings within Windows Terminal opens defaults.json when it should instead open settings.json.

I second the suggestion by Joshua Anderson to change the Customize Settings to emphasize that those changes go into settings.json, but the real problem is how ALT+Settings leads people to the wrong file to customize.  Fix that primary issue and the "documentation issue" will be just icing on the cake.

**Comment by DHowett** [comment]
Thanks, I appreciate that insight! We'll work to do better here.

I do have to ask, though: is it normal to hold down <kbd>Alt</kbd> when clicking menu items? If so, we weren't aware and we should move defaults off of alt+click. If not, however, is this really the root cause?

**Comment by fmorriso** [comment]
I don't remember where I read it, but holding down ALT while clicking Settings in the dropdown listbox control within Windows Terminal opens up defaults.json instead of settings.json.   As I stated in an earlier post, fix that issue first and then update the documentation to correspond to the fix.

**Comment by DHowett** [comment]
I mean to ask,
Why would somebody hold down ALT when clicking on the menu item unless they already knew about this? I interpreted what you said as “I found myself on the defaults file accidentally, and you need to remove the alt-click feature”... but my reading of that suggests that hold down alt while clicking menu items is a standard thing to do that we’ve accidentally interfered with  :smile:

**Comment by fmorriso** [comment]
I suggest that perhaps the ALT key usage to open up the settings should be replaced with an explicit fly-out menu that is part of the dropdown listbox to make it explicit rather than somewhat "magic" the way it works now.  The new menu item could be labeled Details.  It could open up settings.json automatically and would allow editing.  The idealist in me would even like to see IntelliSense to provide further guidance when viewing/editing setting.json, but I'll forgo that in favor of this one small step in the right direction.

**Comment by zishon** [comment]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes   
this is where alt + click operation comes from.

**Comment by DHowett** [comment]
Thank you. Yes, that is unclear.

/dup https://github.com/MicrosoftDocs/terminal/issues/84
