### ISSUE TITLE
Tab title is not updated after logout from a session

### ISSUE THREAD

**Issue by fanshaoshan** [microsoft/terminal#6750]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable):
1.0.1401.0

Any other software?
```

# Steps to reproduce

Open a WSL tab, then ssh login to a remote machine, e.g. raspberry pi or Azure VM, notice terminal tab title been updated to reflect new session (username@host), then logout from that session and back to WSL, notice terminal tab title still show the old session which cause confusion.

# Expected behavior

After user exit remote ssh session, terminal tab title should be updated to reflect current session

# Actual behavior
After user exit remote ssh session, terminal tab title is still about the old session

**Comment by DHowett** [comment]
If the remote shell is setting the title (using OSC `l`), and the local shell is _not_, this must be fixed with your local shell. The local shell should be restoring the title when it reasserts control.
