### ISSUE TITLE
Key combinations do not work for particular terminal programs

### ISSUE THREAD

**Issue by pawelsampolski** [microsoft/terminal#6752]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
Debian Buster installed through Microsoft Store
Emacs installed from default Debian repository :  1:26.1+1-3.2+deb10u1 - but this fault occurred on all Emacs version,
and in default Windows command prompt.
```

# Steps to reproduce

Run emacs, and try call key combination ctrl and meta, for example, typed some, C-x h  mark whole buffer, and then try use C-M-\ that runs indent region, but don't work.
# Expected behavior

Function call indent-region
# Actual behavior
Nothing

**Comment by DHowett** [comment]
This sounds the same as #6722... does emacs prefer 8-bit alt?

**Comment by pawelsampolski** [comment]
> This sounds the same as #6722... does emacs prefer 8-bit alt?
Yes, after my investigation seem like the same problem

**Comment by zadjii-msft** [comment]
Awesome, thanks for following up!

/dup #6722

**Comment by pawelsampolski** [comment]
I wonder why I didn't get any message about needing my feedback?

**Comment by DHowett** [comment]
That's a good question! The process we usually follow in this repo is that an investigator will ask a question (which should generate an e-mail or notification from GitHub) and mark the bug for followup later. Four days after the initial question, the bot will generate another reminder message (which should generate an e-mail or notification from GitHub in much the same way as the first.)

**Comment by pawelsampolski** [comment]
@DHowett Thanks for the answer to my question!
