### ISSUE TITLE
Cascadia Font Weight Variants Not Working

### ISSUE THREAD

**Issue by Rob-Wal** [microsoft/terminal#6753]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.900]
Windows Terminal version (if applicable): 1.0.1811.0 with Cascadia Mono 2007.001

Any other software?
```

# Steps to reproduce
Edit WT settings.   "fontFace" : "Cascadia Mono ExtraLight" or  "fontFace" : "Cascadia Mono SemiLight". Save settings.

# Expected behavior
Terminal should change to Cascadia Mono variant.

# Actual behavior
Terminal reverts to Consolas.

# Additional Notes
The font works in cmd or powershell as standalone.  Also all works with Word.
I have seen similar behavior with VSCode.  I don't know if this issue is with the Font it self or support of the Terminal.
I have gone as far as completely uninstall WT and deleting its installation directories then re-installing.

**Comment by DHowett** [comment]
To use the new weights in Terminal, you need to:

1. Use terminal _preview_ (version 1.1 or greater)
2. Use the fontFace name `Cascadia Code`
3. Use the new `fontWeight` option

**Comment by Rob-Wal** [comment]
Dustin this is not working for me in Preview 1.1.1812.0.
I am following the settings in the docs> https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#text-settings

I am running preview and 1.1.1811.0 side by side.  I have deleted and regenerated settings.json a few times.  The schema doesn't appear to have fontWeight property as an option.
![wt-111812-fontweight](https://user-images.githubusercontent.com/12755848/86310247-92091980-bbeb-11ea-8507-36381f79448d.jpg)


Did I miss something?

**Comment by DHowett** [comment]
Oof our settings are unfortunately case sensitive. Sorry about that! I think we should probably not be case sensitive there :p

**Comment by DHowett** [comment]
(The schema issue is.. unfortunate and depressing. Tracked in #6601)

**Comment by Rob-Wal** [comment]
> Oof our settings are unfortunately case sensitive. Sorry about that! I think we should probably not be case sensitive there :p

That was it.    "fontWeight": "extra-light" works.

I suggest that a comment gets added the settings.json and default settings file about case sensitivity.  That's not expected Windows behavior but I am getting used to it for some cross platform apps.

I'm all set. thanks for your help.
