### ISSUE TITLE
WSL --export & --import broke the look of the Terminal?

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [microsoft/terminal#6756]
# Environment

```none
Windows build number: Win32NT            10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce
In Powershell
```none
wsl --export Ubuntu ubuntu.tar
```
On second machine
```none
wsl --import Ubuntu C:/Data C:/Data/ubuntu.tar
```

# Expected behavior
Copy my settings and installed programs over to my other desktop.
Starting Ubuntu in a new tab yields this as the process starts
https://i.imgur.com/oXVOtZU.png

# Actual behavior
This is what actually happens
https://i.imgur.com/qPU7OiG.png
No scheme colors, no correct user display
(I also copied over my Windows Terminal settings.json too)

Is there another way to export settings?
Sorry if this isnt the correct place for this.

**Comment by DHowett** [comment]
When you reimported the distribution, your user changed from `[username]` to `root`. `root` does not have the same configuration files _inside your WSL distribution_ as your user.

You'll need to search on [the WSL repository](https://github.com/microsoft/wsl) for a remediation here. Sorry about that!

**Comment by DHowett** [comment]
I believe there's a way to set your user ID for the new distro, but I think you'll be able to find it faster than I will :smile:
