### ISSUE TITLE
Support Split Pane via New Tab button

### ISSUE THREAD

**Issue by jawn** [microsoft/terminal#6757]
# Description of the new feature/enhancement

There are two ways to add a pane:

*   from the profile menu
*   using the New Tab button.

A a user, I wish to have auto split pane in both cases. Currently, in version 1.1 preview, only the profile menu supports this.

<table><tbody><tr><td><strong>Ways to add a pane</strong></td><td>From the profile menu</td><td>Using the New Tab button (the button with a plus symbol).</td></tr><tr><td>Auto split pane supported?</td><td>Alt+Click <span class="mention" data-mention="#5928">#5928</span>&nbsp;</td><td><p>Not supported yet</p><p>&nbsp;</p><p><strong>Suggestion: Alt+Click on the New Tab putton auto-splits using the default profile</strong></p></td></tr></tbody></table>

# References

#5928  
#5025

**Comment by DHowett** [comment]
I am shocked that we missed this.

Thanks.

**Comment by carlos-zamora** [comment]
That's fair, didn't think of that.
