### ISSUE TITLE
ConIoSrvComm::Connect memory leak

### ISSUE THREAD

**Issue by dmex** [microsoft/terminal#6759]
The ConIoSrvComm::Connect function has a memory leak from using the RtlCreateUnicodeString function incorrectly:

https://github.com/microsoft/terminal/blob/396cbbb151ccd6fc9ae0356771ce1a5af5623e48/src/interactivity/onecore/ConIoSrvComm.cpp#L101-L106

RtlCreateUnicodeString creates a copy of the string on the process heap and the PortName variable has local-scope. The string doesn't get freed with RtlFreeUnicodeString before the function returns creating a memory leak.

CIS_ALPC_PORT_NAME is a constant string and the PortName variable should instead be initialized using the RTL_CONSTANT_STRING macro:

`static UNICODE_STRING PortName = RTL_CONSTANT_STRING(CIS_ALPC_PORT_NAME);`

It could alternatively use RtlInitUnicodeString but since the string is hard-coded it should be using the macro.

**Comment by DHowett** [comment]
Hey, good find! It's nice to have someone looking at this code, especially given that it doesn't even build in the solution today :smile:
