### ISSUE TITLE
Disable Ctrl + MouseWheel zooming

### ISSUE THREAD

**Issue by rdsecops** [microsoft/terminal#6761]
# Description of the new feature/enhancement

 Problem: Cant't disable "Ctrl+MouseWheel" Zooming in the settings.json file.

# Proposed technical implementation details (optional)

 Make disabling "Ctrl + MouseWheel" zooming in the settings.json file possible.
It would look like this:

"keybindings": [
	{
      		"command": "unbound",
      		"keys": [ "ctrl+MouseWheel" ]
    	}
]

**Comment by DHowett** [comment]
Thanks for the request! This is related to #6692 and will be fixed by /dup #1553.
