### ISSUE TITLE
I can't change text color in terminal.

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#6764]
![test](https://user-images.githubusercontent.com/23658192/86391809-59de0580-bcd5-11ea-93b5-3d8f291699e4.png)

As you can see "import", "# aaaa" string is little similar.
Please, just, i want to use default terminal like Linux.
So, I tried change settings.json. but, not work.
Please, Could you check my setting?

...
		"defaults":
		{
			"alwaysShowTabs": false,
			"fontSize": 12,
			"name" : "Vintage",
            "foreground": "#C0C0C0",
            "background": "#000010",
            "black": "#000000",
            "red": "#800000",
            "green": "#008000",
            "yellow": "#808000",
            "blue": "#000080",
            "purple": "#800080",
            "cyan": "#008080",
            "white": "#C0C0C0",
            "brightBlack": "#808080",
            "brightRed": "#FF0000",
            "brightGreen": "#00FF00",
            "brightYellow": "#FFFF00",
            "brightBlue": "#0C297E",
            "brightPurple": "#FF00FF",
            "brightCyan": "#00FFFF",
            "brightWhite": "#FFFFFF"
		},
...

**Comment by DHowett** [comment]
Unfortunately, you'll need to add another color scheme and then set up your profiles to use that color scheme.
Like this:

```json
{
    // all my settings ...
    "schemes": [
        {
            "name": "CatCatCatDog's Theme",
            // "white", red, black, blue, ...
        }
    ],
    // more settings
    "profiles": [ { . . .
        "colorScheme": "CatCatCatDog's Theme",
    } ],
}
```

**Comment by CatCatCatDog** [comment]
I think, this is not colorScheme setting problem.
I changed Windows terminal command color.
But, If i open file with vim, 'import' string is not change.
I think, this is bug something. I tried many time, but, i can't changed color.

**Comment by DHowett** [comment]
I have looked closer. It appears that vim is using its own color scheme. This is a thing that text-mode applications are allowed to do. You will want to look at your vim settings.
