### ISSUE TITLE
Black background in PowerShell commands

### ISSUE THREAD

**Issue by krzysdz** [microsoft/terminal#6767]
Since commit ddbe370 (#6506) a black background appears after space in commands while using PowerShell.

# Environment

```none
Windows build number: 10.0.19041.329
Windows Terminal versions: all since commit ddbe370
```

# Steps to reproduce

1. Open PowerShell (tested in 5.1 and 7.0.2)
2. Do either of these:
   - press space,
   - write anything and press space,
   - use the arrow up to display a command from history that contains a space character.

# Expected behavior

The background colour does not change and the acrylic effect is visible.
![terminal_PS_older](https://user-images.githubusercontent.com/12915102/86419104-978d5f00-bcd2-11ea-8459-a14c1a2b2588.gif)

# Actual behavior

A weird black background appears after the space character.
![terminal_PS_black_bg](https://user-images.githubusercontent.com/12915102/86418848-ca832300-bcd1-11ea-88ae-ec00bf11166a.gif)

**Comment by DHowett** [comment]
/dup https://github.com/PowerShell/PSReadLine/issues/830

There is going to be a very long tail of issues like this that stem from Terminal being _more correct_. There's a pull request out to PSReadline that fixes this, and it will take time for it to get reviewed and released.

**Comment by Remearex** [comment]
I'm getting literally the exact same issue, here is my vscode info:

Version: 1.115.0 (user setup)
Commit: 41dd792b5e652393e7787322889ed5fdc58bd75b
Date: 2026-04-07T22:04:57Z
Electron: 39.8.5
ElectronBuildId: 13703022
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by Remearex** [comment]
setting "terminal.integrated.minimumContrastRatio": 1 does NOT fix the problem. In fact, after setting to 1 and changing it back to 4.5 in the "workspace" tab, it still has that yellow bar on the left which should have disappeared when i changed it back to the default value:

<img width="1757" height="627" alt="Image" src="https://github.com/user-attachments/assets/cfa64936-c680-4d10-a530-0966388112b2" />

what on earth is going on???

**Comment by DHowett** [comment]
> I'm getting literally the exact same issue

Upgrade PSReadline. It is the PowerShell component responsible for displaying your input!
