### ISSUE TITLE
winget install doesn't unblock files after downloading. "Open File - Security Warning" hangs deploy

### ISSUE THREAD

**Issue by RMMSecurity** [microsoft/terminal#6768]
# Environment

```none
Windows build number: 10.0.18363.900
```

# Steps to reproduce

Attempted to install Firefox on the latest build with and without -h for silent installs.  

`install -h -e --id Mozilla.Firefox`

# Expected behavior

```
Found Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/77.0.1/win64/en-US/Firefox%20Setup%2077.0.1.msi
  ██████████████████████████████  50.5 MB / 50.5 MB
Successfully verified installer hash
Installing ...
Successfully installed!
```

# Actual behavior

```
Found Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/77.0.1/win64/en-US/Firefox%20Setup%2077.0.1.msi
  ██████████████████████████████  50.5 MB / 50.5 MB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 1223
```

![image](https://user-images.githubusercontent.com/802527/86418923-bfaf9a80-bc9f-11ea-84f4-dbcbf7af48c7.png)

The installer downloads the file then doesn't unblock it which gives the end user a security warning. This doesn't work under a non-interactive session like as LocalSystem. This incredibly limits automated deployments. 

Packages downloaded that match the hash in the winget repo should be trusted and unblocked. If there was ever any concern they shouldn't be in the main repo to begin with.

**Comment by DHowett** [comment]
Sorry, you might need to file this at https://github.com/Microsoft/winget-cli
