### ISSUE TITLE
A color is always brighter as Foreground than Background

### ISSUE THREAD

**Issue by krokofant** [microsoft/Terminal#677]
**Environment**
Windows build number: 10.0.18362.86
At Commit: 6c98fc19f53fdf30b1473190608f35a66621d66c

**What you're doing and what's happening:**
Open a PowerShell prompt via the Terminal and execute a command that paints the foreground same as the background:
```powershell
Write-Host "FOO BAR" -ForegroundColor DarkBlue -BackgroundColor DarkBlue
```
**What's wrong / what should be happening instead:**
The foreground is always a little bit brighter
![image](https://user-images.githubusercontent.com/5908498/57547690-5106d380-735f-11e9-81ca-dbcb555fa83d.png)

**Edit:**
With the standard PowerShell theme it's easier to spot when using red:
```powershell
Write-Host "FOO BAR" -ForegroundColor DarkRed -BackgroundColor DarkRed
```
![image](https://user-images.githubusercontent.com/5908498/57549282-667dfc80-7363-11e9-8020-192e7ce6d582.png)

**Comment by zadjii-msft** [comment]
I'm not seeing lighter, but I am seeing different. That's crazy.
![image](https://user-images.githubusercontent.com/18356694/57548957-e38b8080-7327-11e9-91c2-9d7bbdda10f6.png)

**Comment by krokofant** [comment]
It actually seems like _it's the background_ that is darker in the Terminalen compared to pwsh only.
![image](https://user-images.githubusercontent.com/5908498/57555375-689c8700-7374-11e9-97b5-fb62cb7015a8.png)

**Comment by Ghosty141** [comment]
I found the issue/line that causes this, I'm not sure though, if removing it is ok. I'll submit a pull-request. The issue is in DxRenderer.cpp where the following line changes the background brush color:

    _d2dBrushBackground->SetOpacity(.9f);

Removing it fixes the issue.

**Comment by krokofant** [comment]
@Ghosty141 Great!

**Comment by PhMajerus** [comment]
Good catch !
I was wondering why I was seeing modified colors in ANSI-art that used both background and foreground in my screenshots on #455.
