### ISSUE TITLE
Path showing in tab title

### ISSUE THREAD

**Issue by privacyguy123** [microsoft/terminal#6770]
As far as I know it used to say which shell you were using rather than the full path you're in - is there a way to change this behaviour?

**Comment by KalleOlaviNiemitalo** [comment]
You could set [`"suppressApplicationTitle": true](https://docs.microsoft.com/windows/terminal/customize-settings/profile-settings#suppress-title-changes-from-the-shell) in the profile.

**Comment by sentakuhm** [comment]
> 
> 
> You could set ["suppressApplicationTitle": true](https://docs.microsoft.com/windows/terminal/customize-settings/profile-settings#suppress-title-changes-from-the-shell) in the profile.

if this enabled you wont see if terminal run as Admin or not, need other solution.

**Comment by zadjii-msft** [comment]
@privacyguy123 which shell are you using? Are you using the `tabTitle` setting at all?

**Comment by sentakuhm** [comment]
> 
> 
> @privacyguy123 which shell are you using? Are you using the `tabTitle` setting at all?

me have the same issue i'm using powershell 7 and zsh in linux 
[issue in image](https://i.imgur.com/Qt03ZCo.jpg).
