### ISSUE TITLE
Shell selection in start menu tile context menu

### ISSUE THREAD

**Issue by halloamt** [microsoft/terminal#6773]
# Description of the new feature/enhancement

My default shell in Terminal is the good old ```cmd``` but sometimes I just need to start a Debian in WSL. With Terminal you can start a normal shell and enter ```debian``` or you can open a new linux tab in an existing windows. It yould be nice if you could select the shell for a new Terminal window using the context menu of the tile.

# Proposed technical implementation details (optional)

I did a mock-up, but I cannot implement that change...
![grafik](https://user-images.githubusercontent.com/10853957/86471367-862d6c80-bd3d-11ea-87ff-3bf3f9a21a76.png)

**Comment by DHowett** [comment]
Thanks for the request! This is another version of /dup #576.
