### ISSUE TITLE
Could you make window split and coalescence?

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#6774]
iterm2 possible feature, just i will example with chrome browser.
If click to second tab then drop second tab, It's will make new window.
Could you make window split and coalescence? like my picture? 

![1](https://user-images.githubusercontent.com/23658192/86485669-46de3a80-bd94-11ea-9946-a1ee0de05e29.png)
![2](https://user-images.githubusercontent.com/23658192/86485671-480f6780-bd94-11ea-9c11-7144e7d1f500.png)

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of <https://github.com/microsoft/terminal/issues/1256>.

**Comment by DHowett** [comment]
/dup #1256 thanks for the triage @KalleOlaviNiemitalo  :smile:
