### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by LukasAlstrup** [microsoft/terminal#6778]
Hello **Microsoft**!
Your work is impressive and I have an idea to improve your project. In web browsers the **Ctr** + **w** closes a window, and I think it should be the same in the new **Windows Terminal**.  Thanks in advance and keep up the good work!

**Comment by DHowett** [comment]
Thanks for the request! You can set any custom key bindings you want by following the guide in our documentation at https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings

This includes being able to customize Ctrl+W to close the tab.

**Comment by LukasAlstrup** [comment]
Thank you for your awesome help!
