### ISSUE TITLE
"Quake style" slide down feature (just like ConEmu Terminal)

### ISSUE THREAD

**Issue by mkanet** [microsoft/terminal#6780]
(An optional feature while Terminal is docked)

When Terminal is started/opened, the window to slide down from the desktop border.  When Terminal is closed, the window will slide up.  

![Quake-Style](https://user-images.githubusercontent.com/811008/86500479-3010f700-bd46-11ea-8f41-4c399211a4f0.gif)

**Comment by j4james** [comment]
This sounds like a duplicate of issue #653.

**Comment by zadjii-msft** [comment]
Yep, thanks for the triage @j4james!

/dup #653
