### ISSUE TITLE
The command line parsing may erroneously parse the parameters of the subcommand

### ISSUE THREAD

**Issue by fcharlie** [microsoft/terminal#6781]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Microsoft Windows [版本 10.0.19041.329]
```
![image](https://user-images.githubusercontent.com/6904176/86505120-a1f34a00-bdf3-11ea-8f97-f853e19b3c57.png)

# Steps to reproduce

Create a helloworld.ps1 file:

```powershell
# helloworld
Write-Host "Hello world"
```

Run the following command in CMD:

```cmd
wt pwsh  -NoExit -File %CD%/helloworld.ps1
```

# Expected behavior

Start Windows Terminal correctly.

# Actual behavior

Windows Terminal abnormal full screen

![image](https://user-images.githubusercontent.com/6904176/86505085-2f826a00-bdf3-11ea-95a4-180508688141.png)
![image2](https://user-images.githubusercontent.com/6904176/86505087-36a97800-bdf3-11ea-94cf-c55a32a606de.png)

![image](https://user-images.githubusercontent.com/6904176/86505119-9142d400-bdf3-11ea-9c65-99302c61f0de.png)

Looking at the use of Windows Terminal, I speculate that this problem is caused by an error in parsing the command line.

If you start wt as follows, you can run it correctly:

```cmd
wt -- pwsh  -NoExit -File %CD%/helloworld.ps1
```

**Comment by DHowett** [comment]
I'm wondering if we're holding CLI11 wrong, or if it's a bug on their side. `--` is the canonical way to get around this, but like... it shouldn't match `-File` just because `-F` is a substring of it. I don't love that.

**Comment by fcharlie** [comment]
> I'm wondering if we're holding CLI11 wrong, or if it's a bug on their side. is the canonical way to get around this, but like... it shouldn't match just because is a substring of it. I don't love that.`--``-File``-F`

I think CLI11 does not correctly handle the boundaries of the command line, that is, when we parse the subcommand, we should stop parsing.

**Comment by stax76** [comment]
> -- is the canonical way to get around this

Is this documented somewhere?

I couldn't find it in the docs of Windows Terminal and PowerShell.

https://docs.microsoft.com/en-us/windows/terminal

https://docs.microsoft.com/en-us/powershell

**Comment by Don-Vito** [comment]
@zadjii-msft - I think that https://github.com/microsoft/terminal/pull/8315 solves this as well.

**Comment by DHowett** [comment]
Excellent! Thank you.
