### ISSUE TITLE
Maximizing while opening outdated PowerShell uses wrong background color

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#6782]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.1.1812.0
PowerShell: 7.0.1
```

# Steps to reproduce

1. open a new PowerShell terminal
2. while it shows the message below, double-click the title bar to maximize the window
```none
A new PowerShell stable release is available: v7.0.2
Upgrade now, or check out the release page at:
  https://aka.ms/PowerShell-Release?tag=v7.0.2
```

# Expected behavior

The terminal has, aside from the message, a black background.

# Actual behavior

![image](https://user-images.githubusercontent.com/15714253/86505770-267ca300-bdc9-11ea-97d3-f3e5356a875f.png)

**Comment by zadjii-msft** [comment]
You know, someone could probably correct me if I'm wrong here, but I'm pretty sure this is /dup #3848
