### ISSUE TITLE
Implement CTRL V "Safe Paste" from Windows PowerShell console

### ISSUE THREAD

**Issue by yllekz** [microsoft/terminal#6785]
# Description of the new feature/enhancement

Windows PowerShell in Windows 10 allows you to paste code using CTRL V without the lines immediately executing.
Windows Terminal doesn't appear to have this feature yet, as the only method of pasting content is right clicking, and if you have multiple lines, the lines execute immediately.
I would love if the CTRL V "safe paste" feature from the Windows PowerShell console could be implemented.

# Proposed technical implementation details (optional)
Press CTRL V; the contents are put into the line, but are not immediately executed.

The contents are put into the line, but are not immediately executed, especially if the paste queue is multi-line.

**Comment by KalleOlaviNiemitalo** [comment]
Just remove the Ctrl+V binding from `settings.json` of Windows Terminal. Then, Windows Terminal will pass the Ctrl+V key combination to PSReadLine, and you will have your "safe paste" feature.

It might be better if Windows Terminal did not add the Ctrl+C and Ctrl+V bindings to `settings.json` in the first place.

**Comment by DHowett** [comment]
> might be better if

You and I agree on that point, but exactly 50% of our community will riot regardless of which paste option we make default (or which option we detect and pop up a dialog box about).

**Comment by DHowett** [comment]
@KalleOlaviNiemitalo is correct. Letting PSReadline handle this binding will work great if you only use powershell. 
If you don’t, follow /dup #395.
