### ISSUE TITLE
Cannot install on LTSC

### ISSUE THREAD

**Issue by MatthewCroughan** [microsoft/terminal#6789]
I am 100% aware that this is not supported. I'm making this issue in absolute protest to the idea that there is a good reason to arbitrarily limit this application from being distributed to different versions of Windows. 
Without knowing the engineering struggles that have made this necessary, what a complete shambles of package management, libraries, dependencies this ordeal must be if there are any actual reasons for this beyond arbitrary segmentation and hating users.

#2480
#1643 
#1909
#841
#4980 
#1893
#2024

**Comment by MatthewCroughan** [comment]
May I also point out that your repo image shows the terminal operating on `10.0.17134.590`? Does this magical build of the terminal exist and can I install it? Or is this all just marketing?

![image](https://user-images.githubusercontent.com/26458780/86532688-cc143d00-bec3-11ea-8332-d2f7d49b0c12.png)

**Comment by MatthewCroughan** [comment]
I have just tested installing all the versions dating back to 0.2, the mythical version of Terminal running on `Windows  10.0.17134.590` does not exist.

**Comment by MatthewCroughan** [comment]
Extracting the `msixbundle` with 7zip and getting to the executable file does not produce any console output and does not run. 

I am not surprised it does not run. I am very surprised there is no terminal output. I'm told this is just the way it's designed as there is no console attachment or something, seems very unhelpful. I have no idea how anybody is supposed to debug this thing.

![image](https://user-images.githubusercontent.com/26458780/86533498-940ff880-bec9-11ea-886f-6fdc9c31f631.png)

**Comment by j4james** [comment]
> I'm making this issue in absolute protest to the idea that there is a good reason to arbitrarily limit this application from being distributed to different versions of Windows.

Did you not see the explanations posted in https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691 and https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323?

> May I also point out that your repo image shows the terminal operating on 10.0.17134.590?

I believe that's a screenshot from the initial marketing video. It's really just a pretty picture. The real terminal is also not 3D.

**Comment by MatthewCroughan** [comment]
@j4james Yes, it's shocking and I did not anticipate that the OS would have to change to make a proper terminal, that's the real thing I've learned. I just did not assume that so much underlying in the OS and conhost would have to change to allow for this terminals existence. I understand from that point of view.

**Comment by DHowett** [comment]
Our infrastructure runs down to Windows 8.1. Unfortunately, our UI doesn’t. Sorry.

This has been addressed handily in all the linked issues. If the situation changes, you’ll be among the first to know.

**Comment by xianghongai** [comment]
7z → 【Microsoft.WindowsTerminal_1.11.2921.0_8wekyb3d8bbwe.msixbundle】 → 【Microsoft.WindowsTerminal_1.11.2921.0_8wekyb3d8bbwe】 → 【CascadiaPackage_1.11.2921.0_x64.msix】 → 【CascadiaPackage_1.11.2921.0_x64】 → 【WindowsTerminal.exe】, it works for me.
