### ISSUE TITLE
Grouping of panes?

### ISSUE THREAD

**Issue by tomuxi** [microsoft/terminal#6791]
It would be great if it was possible to group selected panes into a single input target, similar to e.g. Terminator's grouping mechanism.

**Comment by KalleOlaviNiemitalo** [comment]
This looks like a duplicate of <https://github.com/microsoft/terminal/issues/2634>.

**Comment by DHowett** [comment]
Yep! Thanks @KalleOlaviNiemitalo 

/dup #2634
