### ISSUE TITLE
New Tab Option for "Developer PowerShell for VS 2019"

### ISSUE THREAD

**Issue by sahitya0000** [microsoft/terminal#6793]
Please add an option for opening a "Developer PowerShell for VS 2019" shell in the new tab options. 

I am attaching a screenshot. 

![Screenshot (25)](https://user-images.githubusercontent.com/5067007/86561884-48b82180-bf7f-11ea-8fdb-6a2a1492df15.png)

**Comment by DHowett** [comment]
You are free to add your own profiles to do anything you want :smile:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings

**Comment by zadjii-msft** [comment]
@sahitya0000 I'd also recommend: [Developer Command Prompt for Visual Studio](https://github.com/microsoft/terminal/blob/master/doc/user-docs/ThirdPartyToolProfiles.md#developer-command-prompt-for-visual-studio)

**Comment by sahitya0000** [comment]
Thank you @zadjii-msft for the link. 
Can you please suggest similar settings for "Developer Powershell for Visual Studio"?
