### ISSUE TITLE
Cant rename tab on double click 

### ISSUE THREAD

**Issue by darkworks** [microsoft/terminal#6794]
# Environment

Windows build number: windows 10 pro  1903
Windows Terminal version (if applicable):  v1.0.1811.0

# Steps to reproduce

install terminal version :  v1.0.1811.0
double click on tab  it will not pop up or allow to rename tab however according to this merged request : https://github.com/microsoft/terminal/pull/6628    on double click user should rename tab

# Expected behavior

on double click tab rename tab

# Actual behavior

no renaming tab

**Comment by DHowett** [comment]
A version containing that change has not yet been released.
