### ISSUE TITLE
Cursor supports gif animation

### ISSUE THREAD

**Issue by kasini3000** [microsoft/terminal#6795]
# Cursor supports gif animation

This is a very interesting idea

# Proposed technical implementation details (optional)
supports gif animation，support emoji char。
Support single letter width, support 2 letter width.

**Comment by iricigor** [comment]
"Cursor" technically is just inverting certain pixels. Here is for example cursor over small letter j
![image](https://user-images.githubusercontent.com/15923171/87051743-46b0c580-c200-11ea-8782-ad96d7e0f11f.png)

It should work for any text size and it should work fast. I think implementing it as GIF animation would be overkill.

**Comment by DHowett** [comment]
This would be a great idea for an extension. My team's not likely to implement something like this, and we're not in a place where we can accept a change that does it right now, so I'm going to link it up to #4000 and close it out.
