### ISSUE TITLE
Trying to launch multiple panes crashes WT

### ISSUE THREAD

**Issue by aviatrix** [microsoft/terminal#6796]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version : 1.0.1811.0
```
# Steps to reproduce

run
```none
wt -p "PowerShell" -d ./api/ nodemon `; split-pane -V -p "PowerShell" -d ./shop_admin npm run dev `; split-pane -H -p "PowerShell" -d ./shop_frontend_nuxt npm run dev `; focus-tab -t 1
```

# Expected behavior

WT starts 3 panes and runs the 3 commands
# Actual behavior

WT starts, opens 3 panes, but they error out with `[error 0x80070002 when launching ``npm run dev']`

![image](https://user-images.githubusercontent.com/151474/86589628-ad32ab00-bf96-11ea-90c6-0ce205403e62.png)

**Comment by DHowett** [comment]
These error messages indicate that Terminal cannot find `npm` or `nodemon`. Are those in your `%PATH%` environment variable?

**Comment by aviatrix** [comment]
@DHowett ,  Yes `npm` and `nodemon` are in my `%PATH%` systemwide.
I've just opened the path folder for npm, and there are 2 files for each global package like this `npm` and `npm.cmd`, `nodemon` and `nodemon.cmd` , etc.  The files without extensions are `bash` files. So, i think the console is trying to start those instead of the `.cmd` files.

i've reworked the command to do this 

```cmd
@echo off
start wt -p "PowerShell" -d ./api/ nodemon.cmd `; split-pane -V -p "PowerShell" -d ./shop_admin npm.cmd run dev `; split-pane -H -p "PowerShell" -d ./shop_frontend_nuxt npm.cmd run dev `;
exit
```
And it works.

Maybe this needs some `NB` in the documentation or is it a bug?

**Comment by aviatrix** [comment]
P.S.
This is the script i've used so far that works as expected : 

```cmd
@echo off
start cmd /k "title GraphQL API && cd ./api && nodemon server"
start cmd /k "title Shop Admin && cd ./shop_admin && npm run dev"
start cmd /k "title Shop FrontEnd Nuxt && cd ./shop_frontend_nuxt && npm run dev"
exit
```
As you can see no explicit `.cmd` passed here.

**Comment by zadjii-msft** [comment]
Ah yea, that'll do it. The Terminal cant just call `CreateProcess("npm.cmd")`, because `npm.cmd` _isn't an executable file_. It needs to first launch a process that knows how to run a `.cmd` file, like `cmd` or Powershell. Thanks for following up!

**Comment by aviatrix** [comment]
But since I'm specifying profiles `Powershell` that launches Powershell 7 (same when using `Command Prompt`, and it has no problem starting `npm` when i type `npm` (or anything else really). So my expectation is that it shouldn't need the extra `.cmd` since it's supposed to run the command `npm run dev` from PS context. 😕
