### ISSUE TITLE
Add support for macOS Terminal's Marks and Bookmarks features

### ISSUE THREAD

**Issue by ralph-snart** [microsoft/terminal#6801]
On macOS, its built-in Terminal app provides a really handy way to navigate up and down through all the prompts and also user-defined locations in the terminal window's visible history, in the form of "Marks" and "Bookmarks", complete with their own keyboard shortcuts and various menu items.

This would be a very convenient feature to port over to and adapt in Windows Terminal as well.

For specifics on macOS Terminal's "Marks" and "Bookmarks" features, please see:
- https://support.apple.com/en-ca/guide/terminal/trml135fbc26/mac
- https://www.howtogeek.com/256548/how-to-use-marks-in-os-xs-terminal-for-easier-navigation/
- https://scriptingosx.com/2017/03/terminal-the-marks-the-spot/

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We're already tracking this over in #1527, but I'm gonna move your comment there, since it seems like well sourced info. 

/dup #1527
