### ISSUE TITLE
Allow to update terminal without having to go to store.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/terminal#6802]
# Description of the new feature/enhancement

I have installed terminal on my office system (through a long and lengthy process I could get access to Microsoft Store for a day). Normally this would not be the issue as all the other software I use does not depend on Microsoft Store for an update, usually, there is a "Check for Updates" option, but with Terminal its not the case (or at least I did not see it).
As per company policy, I will not get permanent access to store. it would be nice to have an option to update the Terminal without having to go to Microsoft Store.

# Proposed technical implementation details (optional)

Expected: An option to check for updates and install available updates without having to depend on Microsoft Store.

**Comment by DHowett** [comment]
Thanks for the request! If you've already installed Terminal from the store, you should be able to download and double-click the msixbundle from our [releases page](https://github.com/microsoft/terminal/releases). For everything else -- a different updater, a different distribution format, etc. -- I'd like to keep discussion over in /dup #1386. :smile:

**Comment by sanket-bhalerao** [comment]
@DHowett even if the Store access is restricted the bundle will get installed/updated?

**Comment by DHowett** [comment]
I believe so.

**Comment by sanket-bhalerao** [comment]
will try this, I have installed preview version so expecting to face this really soon 😄

**Comment by sanket-bhalerao** [comment]
Hi @DHowett,  
downloading and double-clicking on the package does not install the Microsoft Terminal if the Microsoft store access is restricted. it shows the following error

![image](https://user-images.githubusercontent.com/9264813/86882513-ffe2a300-c10d-11ea-81b3-d6e0058b3632.png)
