### ISSUE TITLE
Hot key Window key + T key to open Window Terminal

### ISSUE THREAD

**Issue by dinhanhx** [microsoft/terminal#6811]
# Description of the new hot key

When users press Window key and T key, Window Terminal should open in the folder if they are in one, if not then open in Desktop.

**Comment by shifenis** [comment]
Maybe you are talking about this? https://github.com/microsoft/terminal/issues/3158

**Comment by dinhanhx** [comment]
Hmm I have read the comments until I found [this](https://github.com/microsoft/terminal/issues/3158#issuecomment-654539219) The idea of that comment is similar to this. Therefore you can mark this one duplicate and close it or just close this when you push commits to add this feature.

**Comment by zadjii-msft** [comment]
If you're in explorer.exe, you can press <kbd>ctrl+l</kbd>, then type `wt -d .`, and that'll open the Terminal automatically in the current working directory. 

I'm pretty confident that it's not possible to install a global hotkey on the system that can read the state of the active window and get the CWD of that process unfortunately. So I'll just resolve this as a /dup of #878, /dup #3158, /dup #653 for now.
