### ISSUE TITLE
"acrilycOpacity" value is not respected

### ISSUE THREAD

**Issue by adescre** [microsoft/terminal#6813]
The acrilycOpacity value doesn't seem to be respected, or something is going wrong in the rendering.

# Environment

```none
Windows build number: Version 10.0.19041.329
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce

This follows the [frosted glass theme](https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/frosted-glass-theme) setup.

Here are the settings for the profile entry:
```json
    {
      "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
      "hidden": false,
      "name": "PowerShell",
      "source": "Windows.Terminal.PowershellCore",

      "fontFace": "Cascadia Code PL",
      "fontSize": 10,
      "colorScheme": "Frost",
      "acrylicOpacity": 0.7,
      "useAcrylic": true,
      "cursorColor": "#000000"
    }
```

for the scheme:

```json
  "schemes": [
    {
      "name": "Frost",
      "background": "#FFFFFF",
      "black": "#3C5712",
      "blue": "#17b2ff",
      "brightBlack": "#749B36",
      "brightBlue": "#27B2F6",
      "brightCyan": "#13A8C0",
      "brightGreen": "#89AF50",
      "brightPurple": "#F2A20A",
      "brightRed": "#F49B36",
      "brightWhite": "#741274",
      "brightYellow": "#991070",
      "cyan": "#3C96A6",
      "foreground": "#000000",
      "green": "#6AAE08",
      "purple": "#991070",
      "red": "#8D0C0C",
      "white": "#6E386E",
      "yellow": "#991070"
    }
  ]
```

# Expected behavior

This was done using the exact same settings.json file:
![image](https://user-images.githubusercontent.com/6208560/86696525-6195f680-bfc2-11ea-8629-18a262d126cc.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/6208560/86696571-6b1f5e80-bfc2-11ea-834b-398568d9d2d6.png)

**Comment by DHowett** [comment]
* Are you on battery power?
* Are you on Power Saver mode?
* Do you have the "enable transparency effects" setting enabled in Windows Settings > Personalization > Colors?

**Comment by adescre** [comment]
> * Are you on battery power?
> * Are you on Power Saver mode?
On both question: Desktop computer so no battery. Performance is set on Ultimate in the .

> * Do you have the "enable transparency effects" setting enabled in Windows Settings > Personalization > Colors?
Yes.
![image](https://user-images.githubusercontent.com/6208560/86701290-bf2c4200-bfc6-11ea-9c0b-a85450cc79eb.png)

**Comment by zadjii-msft** [comment]
@adescre Is there acrylic in the Calculator app? The Start Menu? The taskbar?

**Comment by adescre** [comment]
@zadjii-msft Yes on all 3.

**Comment by adescre** [comment]
I just opened the Terminal app and I am getting proper acrylic transparency now. Was any update pushed recently?

**Comment by zadjii-msft** [comment]
> Was any update pushed recently?

Nope. There's really not much we do to control the acrylic, we just ask the system for it. Since this has gone away for you, I'm gonna close this out, but feel free to reply if it starts happening again and we can try and debug further.
