### ISSUE TITLE
Window title is inconsistently updated with tab rename

### ISSUE THREAD

**Issue by jtippet** [microsoft/terminal#6814]
# Environment

```none
Windows build number: 10.0.19041.329
Windows Terminal version (if applicable): d350a8932485f618b1658353a0573ac2422a3c36 and also repros in 1.1.1812.0
```

# Steps to reproduce

1. Launch Terminal
2. Create a 2nd tab
3. Rename the inactive tab to anything, like "bananas"
4. Switch to the inactive tab
5. Check the top-level window's title text (e.g., by looking at the label in the ALT+TAB experience)

# Expected behavior

I'd expect the top-level window's title text to always match the active tab's title (`_runtimeTabText`).

# Actual behavior

The top-level window's title text is just the default tab title.  If you rename the tab while it's the *active* tab, then the top-level window title is updated... until you switch away from the tab.  Once you return back to the tab, the top-level window has returned to the default title for the tab.

This is the console:
![image](https://user-images.githubusercontent.com/10259764/86709258-9c059080-bfce-11ea-92fa-e81f288898a7.png)

But this is what ALT+TAB thinks it's titled -- I'd expect it to say "bananas" at the top, not "PowerShell":
![image](https://user-images.githubusercontent.com/10259764/86709196-8db77480-bfce-11ea-9bd3-ffbc7300bb9a.png)

**Comment by DHowett** [comment]
We should definitely go audit our event handlers and the stack that carries titles up out of the application to its final termini. Thanks!

**Comment by JakubKoralewski** [comment]
Even with this bug fixed, I could see a use case for me where I would like for the custom title tab to overwrite all other titles. Could this be a profile setting, or even better ", a more flexible solution - a little lock icon when renaming the title tab to lock that title to the window title regardless of the number of tabs inside that window/instance? Or even simpler to be able to change the window's title directly and independently from the tab title?

I got confused with lots of ideas 😅

I often open a few instances of the terminal each with a few tabs, grouped by e.g.: frontend, backend etc. specific commands so the use case I'm thinking of is labeling the window as one of the above, so when I have ten instances minimized I can quickly see which is which and binary search for the problem.

Sorry for the rant.

**Comment by zadjii-msft** [comment]
@JakubKoralewski You mean something like this?
![rename-tab-002](https://user-images.githubusercontent.com/18356694/88065433-34088b80-cb32-11ea-90a8-2a46b4a0b390.gif)

#1079, #6600, #6557 

If your use case is "one window per environment", then (once this bug is fixed) you could rename the tab for each environment, and the window title should reflect the active tab's title.

Otherwise, there's also #4183 which looks like it's related
