### ISSUE TITLE
Make the scroll bar easier to use.

### ISSUE THREAD

**Issue by aaron-oxford** [microsoft/terminal#6815]
# Description of the new feature/enhancement

The scrollbar is ridiculously hard to grab. It probably works great on the right hand side of your physical display area, but when it's on the edge of one screen it's a real pain, especially at high resolutions.

This could be a real usability issue for someone with poor eyesight or motor skills.

# Proposed technical implementation details (optional)

Make the scrollbar either configurable to stay visible, or make it more than 1px wide when hidden, or both.

**Comment by electronic-dk** [comment]
AFAIK you can make the scrollbars permanently visible by disabling the Settings > Display > Automatically hide scroll bars in Windows
![image](https://user-images.githubusercontent.com/2945527/86772416-a8d0c580-c05c-11ea-86da-10e3feb64497.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3454 for more discussion.

/dup #3454
