### ISSUE TITLE
Add submenu for each profile on Open in Windows Terminal explorer context menu extension

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#6816]
# Add submenu for each profile on Open in Windows Terminal for explorer context menu extension

Hello
In the current preview of Windows Terminal  (Windows Terminal Preview Version: 1.1.1812.0) a context menu item is available for directories in the Windows Explorer which open the default profile in the selected directory. It should be better if this menu item contains a submenu for each available profile.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6111 for more discussion.

/dup #6111
