### ISSUE TITLE
[Feature Request] Profiles accessible from the taskbar context menu

### ISSUE THREAD

**Issue by Uburuu** [microsoft/terminal#6818]
Much like Putty having a "recent sessions" list in its taskbar context menu, it would convenient, if such a thing would be available for profiles/tabs.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22taskbar+context+menu%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #576 for more discussion.

/dup #576
