### ISSUE TITLE
Powerline font customization for PS fails

### ISSUE THREAD

**Issue by timheuer** [microsoft/Terminal#682]
When trying to use my already-customized PowerShell enviornment, Terminal doesn't render the same:
![image](https://user-images.githubusercontent.com/4821/57551631-64457f00-731e-11e9-93b4-1039e4fcfcf4.png)

Second screen is Cmder/ConEmu with the configuration from: https://gist.github.com/jchandra74/5b0c94385175c7a8d1cb39bc5157365e

**Comment by timheuer** [comment]
My own dang fault.

**Comment by mosamlife** [comment]
Did you resolve the issue?

**Comment by timheuer** [comment]
@mosamlife yes i had forgot to change the FontFace for my profile to actually use the powerline-modified font :-)

**Comment by mosamlife** [comment]
which font are you using I just added font face to profile.json but it is not working

Thanks

**Comment by timheuer** [comment]
See https://timheuer.com/blog/archive/2019/05/13/building-windows-terminal-navigating-source-and-profile-settings.aspx and my power shell configuration in one of the snippets. I also linked to the customization steps I took for powershell
