### ISSUE TITLE
It won't run (the service has not been started)

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#6823]
Now I have installed "Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle".  It will not run.  A message box says:

C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
The service has not been started.

dcomlaunch and AppXSvc are running.

I asked about this 3 months ago.  My issue was closed with no solution given.  Please tell me how to get it running.

**Comment by DHowett** [comment]
If other reports on this repository are correct, you will need to enable `wlidsvc`.

**Comment by vefatica** [comment]
Thanks!  That did it.

**Comment by DHowett** [comment]
Thanks!
