### ISSUE TITLE
Tab completion completes current directory name being typed and then autocompletes the first subdirectory

### ISSUE THREAD

**Issue by oluf** [microsoft/terminal#6825]
# Environment

```none
Windows build number: Version 10.0.19042.330
Windows Terminal version (if applicable):1.1.1812.0

Any other software? none
```

# Steps to reproduce
I installed it directly from the Microsoft Store and haven't changed any settings. I reset the app although the issue didn't resolve.

# Expected behavior
When I use the tab key to autocomplete a directory name, I expect that only the directory name that I am currently typing will autocomplete (assuming that there is a matching directory name).

# Actual behavior
In PowerShell:
Given I am on `C:`
I enter `cd Windows` and autocomplete with tab, it autocompletes to`cd .\Windows\addins\`

In Ubuntu:
Given I am in my home directory with a folder '~/projects/project_1'
I enter `cd projects` and autocomplete with tab, and it autocompletes to `cd projects/project_1'

Other comments:
- I compared behaviour directly in PowerShell and Ubuntu and tab autocomplete works as expected.
- I am also experiencing the issue described in #4448 No keyboard input, and needed to set InputServiceEnabled to 0 as a workaround
- I don't have any issues with the tab key in any other applications
- On the other computer on my desk (Windows 10.0.19041.329) and Windows Terminal 1.0.1811.0 tab completion works as expected - no issues there, and not experiencing the issue described in #4448.

I know there isn't much to go on here, so please advise if I can provide any additional information.

**Comment by zadjii-msft** [comment]
As described in https://github.com/microsoft/terminal/issues/4448#issuecomment-648177283 (and subsequent comments), the "double tabbing" might be a side effect of the "InputServiceEnabled 0" workaround. 

I think I'm going to just close this as "related to #4448". It's not really it's own unique bug, just one that's tightly coupled to it. Ideally, if #4448 is ever fixed, then the workaround won't be needed, and this will go away.
