### ISSUE TITLE
Logging all commands that are run

### ISSUE THREAD

**Issue by Rand-o** [microsoft/terminal#6829]
What would be the best way to automatically log every session, all the commands that were run and outputs, to its own log file?

**Comment by DHowett** [comment]
Thanks for the request! We've got a similar request for transcription support, so I'm going to mark this one up as a duplicate of that.

/dup #642

**Comment by jantari** [comment]
fyi, PowerShell has this functionality built-in:

https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html
