### ISSUE TITLE
font size artifacting

### ISSUE THREAD

**Issue by msftwindowslinux** [microsoft/terminal#6831]
tmux split bars seem to disappear with smaller font sizes, see below

```
            {
                "hidden": false,
                "name": "Ubuntu-18.04",
                "source": "Windows.Terminal.Wsl",
                "commandline": "wsl.exe ~ -d Ubuntu-18.04",
                "fontSize" : 9, // 9 is okay, 8 causes bars split bars to disappear
                "fontFace" : "Consolas",
            },
```
![9](https://user-images.githubusercontent.com/68022544/86944026-cc534900-c10c-11ea-8084-9c33169a2140.png)
![8](https://user-images.githubusercontent.com/68022544/86944024-cbbab280-c10c-11ea-87c6-1ac47053a417.png)

happens for vertical and horizontal split, regardless of window size.

**Comment by DHowett** [comment]
I believe this is another instance of #6161 -- we cross the threshold between being able to render the box drawing glyphs at 1px and at <1px in width, and because we're not doing any subpixel rendering for them we round that down to _zero pixels._

/dup #6161
