### ISSUE TITLE
Feature Request - Allow CTRL-F4 to close shell tabs like browsers

### ISSUE THREAD

**Issue by stunney** [microsoft/terminal#6834]
In Windows applications with multi-tabs, such as Edge, Chrome, etc. pressing the CTRL-F4 key combination closes the current tab out.  I would really like to see this in the application.

Thank you so much for a great app!

**Comment by DHowett** [comment]
Thanks for the request! You're free to bind whatever you'd like in your [key bindings settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings).
