### ISSUE TITLE
The combination of keys Alt-Enter is used in terminal programs.

### ISSUE THREAD

**Issue by pawelsampolski** [microsoft/terminal#6836]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
Any other software?
Debian Buster installed through Microsoft Store
mc installed from default Debian repository :  3:4.8.22-1 - but this fault occurred also on in default Windows command prompt.
```

# Steps to reproduce
The key combination (Alt-Enter) is used for resizing the terminal window, but this combination is necessary for particular applications in the terminal. For example in mc is used to copies current filename to command. I can't find an option which can disable the window resize, for passing it for a terms program. 

# Expected behavior
Passing the Alt-Enter combination to the application

# Actual behavior
Resize window of terminal

**Comment by DHowett** [comment]
You can unbind any key binding by setting its command to `null` or `"unbound"`.

```json
"keybindings": [
    { "command": null, "keys": "alt+enter" },
    // ...
]
```
