### ISSUE TITLE
Introduce abstraction layer between TermControl and TerminalCore (aka Interactivity)

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#6842]
# Description of the new feature/enhancement

We have some redundant code between the WPF Control and the UWP TermControl. This indicates a missing layer of abstraction between the TerminalCore and the TermControl. Some benefits that we could/would get from introducing an "interactivity" layer includes...
- better parity between both controls
- less duplicated code
- better separating scrolling in both layers

# Proposed technical implementation details (optional)

Specific interactions that could be abstracted better include (but are not limited to)...
- Selection
- Scrolling
- VT Mouse Mode (sorta)

\cc @DHowett

**Comment by zadjii-msft** [comment]
Alright, as of 2ac83180f, this is fundamentally pulled into 3 files, but there's still a lot of work to do. I'm using this comment to track that.
* [ ] Move `ControlCore` and `ControlInteractivity` to `Microsoft.Terminal.Core` so I can unittest them
* [ ] Mousewheel transparency is busted
* [ ] Acrylic actually doesn't work at all
* [ ] auto-detecting hyperlinks doesn't work
  - oh good this actually has a `TODO!`
* [ ] Trying to make a second selection while one is active is weird
* [x] multi-click selection does seem to work
* [ ] The scrollbar _never moves_!
* [ ] Scrolling with the mouse is fine. With the trackpad though: Scrolling up seems to work, but scrolling down is _very_ unsmooth
* [x] wheel scrolling of the font size seems to work
* [x] keybinding changing of the font size seems to work
* [x] changing DPI seems fine
* [x] Find dialog opens, works
* [ ] more...

Other scenarios to check:
* Click+drag out of the window to autoscroll the buffer
* shift+click extend selection
* toggling renderer settings at runtime
* reloading settings
* read-only mode
  * keyboard input
  * mouse input in VT mode
* Mouse mode still work?
* snap to grid - does that still work? 
* copy on select

**Comment by DHowett** [comment]
* [ ] moving between DPIs does not introduce any issues in VT mouse events, rendering, scrolling, dragging, etc
