### ISSUE TITLE
Cursor is blinking while I am using zsh on WSL.

### ISSUE THREAD

**Issue by F-Unction** [microsoft/terminal#6844]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable):
1.0.1811.0

Any other software?
WSL2 Ubuntu20.04
```

# Steps to reproduce
```powershell
pwsh
wsl
[backspaceKey]
```

# Expected behavior
Nothing will happen, the cursor will not move any more

# Actual behavior
The cursor is always blinking, it moves to next line then move back.
![In WindowsTerminal](https://user-images.githubusercontent.com/51352133/86910510-625a9400-c14c-11ea-8ad4-e2e2377bd8ee.gif)
 I am not sure is it a bug of windows terminal or WSL.
WSL says
> If this is a console issue (a problem with layout, rendering, colors, etc.), please post the issue to the Terminal tracker: https://github.com/microsoft/terminal/issues

so I come here.
When I do this in VSCode Remote-WSL, it won't happen, but when I do it in VSCode Terminal or cmd directly, it will happen.
![In VSCode Remote-WSL](https://user-images.githubusercontent.com/51352133/86910971-19570f80-c14d-11ea-900d-b28a3c450554.gif)
![In VSCode terminal](https://user-images.githubusercontent.com/51352133/86984116-41cc2180-c1c0-11ea-8cee-d13ebe431bc0.gif)
![In cmd](https://user-images.githubusercontent.com/51352133/86984121-42fd4e80-c1c0-11ea-806d-93f4b731415a.gif)

**Comment by DHowett** [comment]
This is an unfortunate side effect of the syntax highlighting plugin you're using for zsh. It has to redraw the entire line to change the colors, and terminal is _very fast_ about updating the cursor position. We have work booked in /duplicate #6217 to fix that. :smile:
