### ISSUE TITLE
Bug report (missing icon for newly added application profile)

### ISSUE THREAD

**Issue by Dylmm** [microsoft/terminal#6846]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.19041.329]
Windows Terminal version (if applicable):  full release- non preview build (from microsoft store)

Any other software?
powershell 7(pwsh.exe)
```

# Steps to reproduce

-Install powershell 7(pwsh)
-get new-guid for pwsh
-added new profile to settings. (v this)
     
{
      "guid": "{3e2c7a89-eb66-45b5-998c-ac754249d13e}",
      "name": "Windows PowerShell 7+",
      "commandline": "pwsh.exe",
      "hidden": false,
      "colorScheme": "Powershell"
},

# Expected behavior

application should launch and work in terminal application

# Actual behavior

application launches and works in terminal, but missing applications icon.

![terminal-snapshot](https://user-images.githubusercontent.com/545098/86988669-a732fa80-c14d-11ea-9a58-39bb5df33fc8.png)

**Comment by zadjii-msft** [comment]
The terminal can't automatically find the icon from the executable in `commandline`. You'll need to set `icon` manually for now. 

There's work tracking auto locating the icon in #705
