### ISSUE TITLE
Logging out of WSL after failed SSH results in error

### ISSUE THREAD

**Issue by manie204** [microsoft/terminal#6849]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1811.0
WSL v2 running Ubuntu
Unmodified OpenSSH client running in WSL 2
```

# Steps to reproduce

1. Open a WSL tab in the Windows Terminal.
2. Try to connect to any hostname via ssh that cannot be resolved, example:
```none
$ ssh foobar
$ ssh: Could not resolve hostname foobar: Name or service not known
```
3. Exit the session via logout or ctrl+d to receive the following error message:
```none
[process exited with code 255]
```

# Expected behavior

The terminal window/tab/pane closes.

# Actual behavior

The terminal window/tab/pane stays open displaying the aforementioned error message. In case of panes, this is problematic since they cannot be closed any more without closing the entire window.

I realize that this might be a bug in WSL but cmd and powershell don't show an error when exiting from WSL in this case.

**Comment by electronic-dk** [comment]
AFAIK that's the default tab exit behavior: if the underlying process (last executed command) finishes with an error, then the tab shows this message with the error code. This can be changed with the "closeOnExit" option (e.g. "closeOnExit": "always").

**Comment by manie204** [comment]
Excellent, I was unaware of this option. I will close this issue then.
