### ISSUE TITLE
Improvements to TerminalInput

### ISSUE THREAD

**Issue by Nicholas-Baron** [microsoft/terminal#685]
This line could use ` = default` syntax. This would also reduce the number of lines in the associated cpp.

https://github.com/microsoft/Terminal/blob/bf460ab7feed7e203f1c5cf1bc06a1c732742870/src/terminal/input/terminalInput.hpp#L26

**Comment by DHowett-MSFT** [comment]
Hey Nicholas,
Thanks for the report. We’re glad to accept pull requests for issues like this!

________________________________

**Comment by zadjii-msft** [comment]
Oh weird, this was fixed in #690, just never marked as closed.
