### ISSUE TITLE
Allow users to create a 'collection' of tabs that will open specified command lines with different starting directories.

### ISSUE THREAD

**Issue by AlphaCreative-Mike** [microsoft/terminal#6851]
# Description of the new feature/enhancement
I often need to open the same 4+ tabs with different starting directories.  It would be nice to have a feature similar to the 'collections' in MS Edge that will open several tabs to a specific command line and starting directory.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
You technically can do this now using combination of profiles with the commandline parameter set and using the wt argument parser (to get your tabs and/or panes). You could also just script it out purely using the argument parser (so you don't need to enter it every time you close Terminal).

**Comment by WSLUser** [comment]
Perhaps when the Settings UI is created, this could be an enhancement to remove the need to script it out yourself and configure it in the Settings UI instead (possibly as an extension).

**Comment by AlphaCreative-Mike** [comment]
> Perhaps when the Settings UI is created, this could be an enhancement to remove the need to script it out yourself and configure it in the Settings UI instead (possibly as an extension).

Thanks for the response.  I figured there was a way to script it.  I was hoping to be able to do it through the UI.

**Comment by WSLUser** [comment]
They're still going over the spec https://github.com/microsoft/terminal/pull/6720. Once that's been flushed out, they'll begin implementing it. I'm sure they'd appreciate any feedback regarding this feature request.

**Comment by zadjii-msft** [comment]
As @WSLUser points out, you can use the `wt` commandline currently do do a little bit of this. I actually have a profile with the following:
```json
{
    "name": "Good Morning",
    "commandline": "cmd.exe /k wt cmd.exe /k #work 15 ; split-pane cmd.exe /k #work 15 ; split-pane -H cmd.exe /k media-commandline ; new-tab powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; focus-tab -t 0",
}
```
which opens up 4 tabs, and the first has 3 panes, for my initial dev environment. This unfortunately opens it in a new window currently, but it _works for me_. We've got lots of plans on how to improve this:

* Opening initially with a set group of panes/tabs: #756
* Creating actions / commands for performing multiple tasks:
  - via a `wt` commandline: #6537 
  - via a list of actions: #5970
  - once either of the above two are done, this will be exposed via the command palette, #5400
* Customize the new tab dropdown to be able to include custom actions (like "open these 4 tabs...") #1571/#5888
