### ISSUE TITLE
Windows Terminal not detecting my keyboard (can't type anything, just click)

### ISSUE THREAD

**Issue by GonzaDDV** [microsoft/terminal#6852]
# Environment

```none
Windows build number: Microsoft Windows 10.0.19041.329
Windows Terminal version (if applicable): 1.0.1811.0 (lastest as of 7/9/2020

Any other software?
```

# Steps to reproduce

I just installed the Windows Terminal from the Microsoft Store, and even tried installing it from the github download installer

# Expected behavior

The terminal should let me type

# Actual behavior

I can't type anything, the terminal just is not working at all with my keyboard, I just can paste with my right click and open new tabs and the config file, but there I can't figure how to solve the problem. I have already tried to reinstall, install the preview, rebooting, deleting cache and temporal files, and none of that seems to work.

Thank you!

**Comment by zadjii-msft** [comment]
By any chance, does anything in #4448 help you?

**Comment by GonzaDDV** [comment]
Yes, changing some registry values helped.
More info in #4448 
Thanks!
