### ISSUE TITLE
Clickable hyperlinks in terminal

### ISSUE THREAD

**Issue by ticktockhouse** [microsoft/terminal#6854]
# Description of the new feature/enhancement

If a hyperlink is printed in the terminal, make it clickable, to be opened in the default browser, this could be done with e.g. a context menu or a modifier key

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+hyperlink) when filing new issues. This is already being tracked by another issue on our repo - please refer to #574/#204 for more discussion.

/dup #574 #204
