### ISSUE TITLE
[discussion] Initialize Terminal Preview settings from Terminal settings 

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#6855]
If Terminal Preview is installed for the first time, can it initialize settings from Terminal settings?

Usecase is trying out Preview with same settings as regular version. Currently it's reset to default settings.

In any case, this is not a big issue

**Comment by zadjii-msft** [comment]
I don't think this is a terrible idea, just needs someone to go write the migration code.

**Comment by vadimkantorov** [comment]
One non-intrusive way could be implementing a context-menu item: "Replace current WT Preview settings by settings from WT". It could even be just "wtp.exe import-settings" command or sth like this.

**Comment by zadjii-msft** [comment]
Or the even simpler solution - when the Terminal settings are empty, do a quick check if we're the Preview version. If we are, and there's also a `settings.json` file under the non-preview path, then just copy that instead of using the `userDefaults.json`

**Comment by vadimkantorov** [comment]
Reset may still be useful for a situation: I generally use non-preview. But occasionally install fresh Preview to check if a particular bug was fixed. Then settings import function (at least being able to fire it manually) is useful even when a previous version of Preview was installed

**Comment by Dannihu01** [comment]
Hi, this is my first time making a contribution to an open source project and I would like to work on this!

**Comment by zadjii-msft** [comment]
@Dannihu01 awesome, go for it! I don't think you'd be stepping on anyone's toes here. Let us know if you need any pointers ☺️

**Comment by Dannihu01** [comment]
I was wondering if I could get some guidance on this issue - my partner and I edited existing commands and tried to add a new one in AppCommandLineArgs.cpp but nothing changed when we built and ran. What could we be doing wrong here?

**Comment by zadjii-msft** [comment]
... That might be overkill in this case. I'd start here:

https://github.com/microsoft/terminal/blob/fe618fd2ae1eb07a963aa58ceaa23f53aa5db9ba/src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp#L713-L728

That's the function that loads the settings from the `settings.json` file. It can tell if the settings file was initially empty/missing entirely. When the settings are missing (`firstTimeSetup`), and we're a Preview build of the Terminal, we should try loading the settings from the "stable" file path, if they exist. I believe we have a preprocessor define (`WT_BRANDING_PREVIEW`) that's set when we're a preview build. We're using that elsewhere like so: https://github.com/microsoft/terminal/search?q=WT_BRANDING_PREVIEW

That's where I'd start at least. Does that make sense @Dannihu01?

**Comment by vadimkantorov** [comment]
I would say that one also needs a manual button in settings "Import settings from non-preview" (or sth like that)

**Comment by Dannihu01** [comment]
Thank you, that did make sense. We have made good progress with that info above - 

However, what is the most efficient way to extract the stable file path?

Will all the package names always end in "8wekyb3d8bbwe?" For example at the end of "\\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe?" I understand that this is Microsoft's publisher ID, but will that ever change? If it never changes then our first idea was to hard code the stable file path and extract settings.json from there.

But we think that hard coding the stable file path and doing string manipulation isn't the right direction. What else can we do to extract the correct file path?
