### ISSUE TITLE
Error 0xd0000022 when launching any shell (PS, cmd, git bash, PS7, Azure Cloud Shell) in WT

### ISSUE THREAD

**Issue by quadzz** [microsoft/terminal#6862]
# Environment

```
Windows build number 10.0.18363.0

Windows Terminal (Unpackaged)
Version: 1.0.200629001-release1.0
```

# Steps to reproduce

Run the terminal without admin privileges and open any cli (powershell, cmd, git bash - whatever)

# Expected behavior

Terminal opens shells

# Actual behavior

[error 0xd0000022 when launching `powershell.exe']
[error 0xd0000022 when launching `cmd.exe']
[error 0xd0000022 when launching `"%PROGRAMFILES%\git\usr\bin\bash.exe" -i -l']
[error 0xd0000022 when launching `C:\Program Files\PowerShell\7\pwsh.exe']

# Additional info
I tried to open with full path to powershell, to shortcut, created the profile, none of that worked. 
Actually, any of the programs I tried to run in WT - did not work. 
I have read/write access to the folder I have WT in. 
I have access to the folder the powershell starts in
I am now using unpacked version instead of installed - both of them not working.
To open the shell you need to run WT as admin and this is actually not acceptable for me.

I was about to move to WT, but ConEmu still wins with it, for now. It's opening any shell like a charm.
I attached ConEmu that runs powershell without admin rights and Windows Terminal that runs the same command and doesn't work. 
![image](https://user-images.githubusercontent.com/28461795/87147129-63a2d280-c2ac-11ea-8089-7782c01f59f6.png)

**Comment by quadzz** [comment]
I'd like to add, that my PATH has entries with system32 - both in LocalMachine and CurrentUser scopes. 
When I run powershell command in Run - it works like a charm. 

Any of the solution in existing issues did not work for me

**Comment by zadjii-msft** [comment]
Well that's just the damndest thing I've ever heard. I have no idea why the Terminal would be failing to launch processes unelevated for you. _Especially_ if they work jut fine in ConEmu, or a standard conhost window. 

_probably irrelevant_: 0xc0000022 is `STATUS_ACCESS_DENIED`, which isn't terribly helpful. That's what our internal error search returns for `0xd0000022`, along with a message about how this was probably an NTSTATUS code (converted using HRESULT_FROM_NT).

Do you have anything installed that might be hooking conhost.exe launches? Does git bash's default terminal emulator work unelevated, and can that spawn powershell, cmd? I'm really just spitballing for anything here.

**Comment by quadzz** [comment]
I have programs installed that I thought are blocking the WT behavior (I work in banking company so we have limitations), yet I've got all the "guarding" software uninstalled with the company admins and absolutely nothing has changed.
ConEmu still works, WT still doesn't.

The only way I can get the WT to work is running it with elevated privileges.

**Comment by quadzz** [comment]
Just straight out of curiosity, I ran git bash from ConEmu and run powershell from it. Works like a charm :)
![image](https://user-images.githubusercontent.com/28461795/87154676-eaaa7780-c2b9-11ea-8d46-fc72b543e291.png)

**Comment by zadjii-msft** [comment]
What about if you don't involve conemu at all? What happens when you launch those applications from a standard `cmd.exe` window? Or what about from the terminal that ships with Git Bash (mintty)?

![image](https://user-images.githubusercontent.com/18356694/87157502-fd09be80-c283-11ea-9149-5bb8bc7e08e3.png)

**Comment by quadzz** [comment]
![image](https://user-images.githubusercontent.com/28461795/87157571-c1d8b100-c2be-11ea-9ed1-001b8e3bd340.png)
![image](https://user-images.githubusercontent.com/28461795/87157717-efbdf580-c2be-11ea-9a95-2f60ebb6cbad.png)

Works a-ok

**Comment by DHowett** [comment]
Since you're running unpackaged...
does it work if you double-click `OpenConsole` in the WT folder? It won't be the Terminal itself, but it will verify that one of its components works properly.

**Comment by quadzz** [comment]
Doesn't work until I run it as administrator.

**Comment by zadjii-msft** [comment]
That's bizarre. Are there any weird permissions set on that OpenConsole.exe? There _shouldn't_ be, but maybe there's something corrupted with the installation.

**Comment by quadzz** [comment]
No, I've downloaded new bundle, unpacked it and run OpenConsole.exe from it. Same result.


I don't know if it's connected, but I've started to see problems with vs code console - maybe this will guide you:
14.07.2020 09:25:59 [NORMAL] - pwsh.exe started.
14.07.2020 09:25:59 [NORMAL] - Waiting for session file
14.07.2020 09:29:59 [NORMAL] - Timed out waiting for session file to appear.
14.07.2020 09:29:59 [NORMAL] - Language server startup failed.
14.07.2020 09:29:59 [ERROR] - The language service could not be started: 
14.07.2020 09:29:59 [ERROR] - Error: Timed out waiting for session file to appear.

**Comment by quadzz** [comment]
That's just in: WSL doesn't work either: 
![image](https://user-images.githubusercontent.com/28461795/87424454-43d91a80-c5dc-11ea-8715-c76be7c4a8f2.png)

and ConEmu:
![image](https://user-images.githubusercontent.com/28461795/87424707-b3e7a080-c5dc-11ea-80fc-2354223cd690.png)

**Comment by zadjii-msft** [comment]
> I've downloaded new bundle, unpacked it and ran OpenConsole.exe from it. Same result.

That's definitely unexpected. All of the Terminal tabs are run through `OpenConsole.exe`, so it makes sense that if that doesn't work, then the Terminal won't be able to launch anything. 

Does renaming `OpenConsole.exe` to something else, like maybe `conhost.exe`, allow you to launch that exe?

This is a really _dumb_ idea, and it's definitely going to work poorly, but can you copy-paste `conhost.exe` from `C:\windows\system32` into the Terminal install, and rename it to `OpenConsole.exe`, and have _that_ launch successfully? `conhost` and `OpenConsole` are the same binary, but the `OpenConsole` version is quite a bit more up to date.

**Comment by randyridge** [comment]
fwiw i have the same issue with terminal and 0xd000022 and all shells under it.  Works as admin.  I had recently upgraded to win10 2004, I had to install terminal via Add-AppxPackage.  after installing terminal vscode is also now failing to open powershell7 without admin privileges...

**Comment by quadzz** [comment]
> Does renaming OpenConsole.exe to something else, like maybe conhost.exe, allow you to launch that exe?

No. I've changed OpenConsole.exe to conhost.exe, doesn't work until I run it as admin.

> This is a really dumb idea, and it's definitely going to work poorly, but can you copy-paste conhost.exe from C:\windows\system32 into the Terminal install, and rename it to OpenConsole.exe, and have that launch successfully? conhost and OpenConsole are the same binary, but the OpenConsole version is quite a bit more up to date.

No success. Still the same error. 


BTW. I've requested once again to my corporate admins to check on their side in parallel.

**Comment by eryksun** [comment]
Check `cacls openconsole.exe /s`. The `/s` option returns SDDL, which includes conditional access-allow entries (XA) such as `(XA;ID;0x1200a9;;;BU;(WIN://SYSAPPID Contains "Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe")`. The latter grants  the given access (0x0012_00a9) to users (BU) only if their access token contains the particular "WIN://SYSAPPID" attribute value.

**Comment by quadzz** [comment]
Ok, after digging through crap tons of logs I found out where the dragon lies. 
So - I've got EPM software installed since I need to have "secured" station.

So the thing is - I need you guys (from Microsoft) to try to find solution to not run ANYTHING that requires elevated privileges. I checked under every rock - every shortcut of mine is running without admin - yet still it's being blocked as malware.

Plz fix, as I really dig the new Terminal and its a bummer I can't use it.

**Comment by quadzz** [comment]
I've also made a task in vs code repo: https://github.com/microsoft/vscode/issues/103562 as it's connected with the same reason behind both of these issues.

**Comment by zadjii-msft** [comment]
Well, that's still bizarre. Unless you're running the Terminal as elevated, we're not going to be doing anything that requests any other permissions. This isn't the _first_ time that the Windows Terminal has been erroneously flagged by some faulty 3rd party AV software. I'd probably follow up with the EPM vendor to get this fixed on their end.

**Comment by randyridge** [comment]
So I think I've narrowed this down to something to do with conpty vs winpty, as I can toggle vscode to use winpty and I no longer require elevating.  I'm not yet sure what's seeing conpty as requiring elevation, no doubt some sort of corporate 'security' software.

**Comment by zadjii-msft** [comment]
I wonder if it's because we're making handles to condrv manually in pty mode, rather than letting the OS create them for us.

See https://github.com/microsoft/terminal/blob/master/src/server/DeviceHandle.cpp

**Comment by DHowett** [comment]
But double-clicking OpenConsole.exe also doesn't work, and it should work the same as double-clicking conhost from the same integrity level. Hm.

**Comment by quadzz** [comment]
> So I think I've narrowed this down to something to do with conpty vs winpty, as I can toggle vscode to use winpty and I no longer require elevating. I'm not yet sure what's seeing conpty as requiring elevation, no doubt some sort of corporate 'security' software.

Yes, since I discovered it yesterday -it IS issue with corporate EPM software, yet ConEmu still works. And that's the reason I created this ticket. Why does ConEmu not require elevating when running any console, yet Windows Terminal has to be elevated to run?

**Comment by DHowett** [comment]
We would love to figure that out too. We haven’t written any code that would require WT to be elevated to run. This bug report is the first time we have heard of WT requiring elevation :smile:

ConPTY works by running either `conhost` or `OpenConsole` in a specific way. ConEmu doesn’t use ConPTY, so it runs `conhost` in the normal way.

To help us troubleshoot this issue, we asked you to try to run `OpenConsole` directly. Since that didn’t work, it helped us narrow something down: it’s not because of ConPTY, because double-clicking OpenConsole doesn’t activate ConPTY. It’s something about OpenConsole.exe itself.

This is where it gets weird: we also asked you to copy the normal console host (conhost) in place of OpenConsole. That application runs un-elevated all the time as part of Windows just doing its job. It still failed, which rules out something about _the contents of OpenConsole.exe_.

That’s why we are so confused: the system version of conhost is supposed to be a sure-fire way to run console sessions. If the exact same code, with the exact same code signature as the rest of the OS, can’t be run when it’s copied and renamed... something is amiss.

If there are any logs that your EPM software produces about launching applications, they might be very helpful.

**Comment by quadzz** [comment]
I won't give you EPM logs, since these are my corporate ones with corporate data in it :C

Protip: In Visual Studio Code terminal is running when I changed ConPTY settings.

`"terminal.integrated.windowsEnableConpty": false`

**Comment by zadjii-msft** [comment]
Alright well I'm not really sure what to do with this then. There's nothing special about what `OpenConsole.exe`/`conhost.exe` is doing. Maybe the creating condrv handles since we're doing that when the exe is double-clicked directly, without being spawned on behalf of the OS. Conhost will do that when double clicked (even when not in conpty mode). That being said, there's really no way for conhost (in conpty mode) to work _without_ doing that, 

I think in the past when we've gotten reports about someone's A/V software being overzealous and preventing the Terminal from working appropriately, we've resolved the issue as "external", since there's nothing else we can really do to make someone else's faulty software work. If they are blocking our access to ConDrv, then I'm not really sure there's anything else we could do on our end...

**Comment by quadzz** [comment]
Same issue was in Visual Studio Code. EPM software was blocking the terminal with any shell session to open. 
After disabling conpty it works (and even powerhsell code snippets are there!).
So - since I've got no knowledge about C++ (I'd really love to help with this) - I need you guys to try and find a solution that will not be treated as a threat from A/V or EPM software :C

**Comment by randyridge** [comment]
In my case the software in question was RSA Netwitness' ecatservice.  Uninstalling returned terminal and vs code's conpty to working order.  Updating the RSA software to version 11.4.1.0 from 11.3.0 also seems to work.

**Comment by madrum** [comment]
I have to run Terminals as administrator, otherwise, I get this error.

**Comment by DHowett** [comment]
We got a positive ID from a customer on this. The error code is being generated **before the OpenConsole process even starts**. There's no way for us, as a normal (better than normal! code-signed just like the rest of the OS!) caller to CreateProcess, to tell the EPM software to step off and not interfere. I'm unfortunately going to have to close this one as "External"+"No-Repro" until we get some Cylance or ForcePoint or whomever customer to file a bug with them.
