### ISSUE TITLE
Click link to open browser and 'open terminal here'

### ISSUE THREAD

**Issue by yzqdev** [microsoft/terminal#6863]
# Description of the new feature/enhancement
1. when we are developing vue apps the terminal always show us 'http://localhost:8080' or 'http://192.168.2.125:8080' ,i hope if i could open this url with browser  . a click to open url ,maybe , a good idea
2. is there a way to way to register terminal as a context? when we look into a folder ,then we can right click  and use 'open windows terminal in the folder' command. Or we could register windows terminal as 'terminal 'command ,like 'cmd'. We could also use commands like `terminal.exe /REGISTER ALL` to register terminal as a global terminal

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestions! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22click+link%22) when filing new issues. These requests are being tracked in a bunch of threads already:

* Clickable links: #574
* "Open Terminal Here": #1060
* Default Terminal application: #492


/dup #574
/dup #1060
/dup #492
