### ISSUE TITLE
Extra IntelliSense errors caused by include paths and precompiled headers

### ISSUE THREAD

**Issue by rpjohnst** [microsoft/terminal#6866]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): master branch, commit fc083296b98a2c45126da7a0a61a2ccb37786e48
Visual Studio 2019, 16.6
```

# Steps to reproduce

* Clone the project as described in the README.
* Open `OpenConsole.sln` in Visual Studio, switch the platform from "Any CPU" to "x64," and build the TerminalAppLib project.
* Open `TerminalPage.cpp` (under `controls/TerminalPage.xaml` in the solution explorer).

# Expected behavior

IntelliSense should not show any errors/red squiggles, given that the build succeeded.

# Actual behavior

IntelliSense finds the wrong `pch.h` file and goes on to produce a few hundred errors about missing definitions.

Specifically, it finds `src\cascadia\TerminalApp\pch.h` instead of `src\cascadia\TerminalApp\lib\pch.h`. You can confirm this by using Go To Definition/F12 on the `#include "pch.h"` at the top of `TerminalPage.cpp`. Changing this to `#include "lib/pch.h"`, or making an equivalent change to the project include paths, lets IntelliSense find the right header and all the errors disappear.

The build succeeds because the compiler does not use the usual include path search for this header when PCH is enabled, while IntelliSense fails because its PCH implementation does not work this way.

**Comment by DHowett** [comment]
This is the first time we've ever had a lead on exactly why IntelliSense is busted in our project. Thank you!

**Comment by mpela81** [comment]
Thanks @rpjohnst for filing this following my post on Developer Community!
