### ISSUE TITLE
file listing in WSL via Terminal varies depending on invocation of WSL

### ISSUE THREAD

**Issue by mayureshkathe** [microsoft/terminal#6868]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): Windows Terminal, Windows Terminal Preview, Fluent Terminal.

```

# Steps to reproduce

Run the WSL invocation from PowerShell command prompt (such as "debian") and run "ls" and the Windows file-system isn't shown, but invoke WSL via the sub-menu on Windows Terminal Preview (such as pull-down menu item "debian") and run "ls" in the reulting WSL environment and the Windows file-system is shown.

# Expected behavior

Either ways, either show the Windows file-system, or don't show the Windows file-system when WSL is invoked in any manner.
Didn't know if this was a bug with Terminal or WSL, so going to file it with both projects.

# Actual behavior

Everything is mentioned above.

**Comment by DHowett** [comment]
This is because the two instances are running in different folders.

**Comment by mayureshkathe** [comment]
What are you talking about?
Either ways, whether you invoke a WSL instance from the Terminal (such as by running "debian" in a Terminal window) or via the pull-down menu on Terminal Preview, I am always placed in my Linux "home folder", but running "ls" during those two different invocations leads to different results.
Have you now _understood_ what I am trying to convey?
You should not close an issue till it's been resolved, and this issue reported by me is still unresolved, so I request you to not shutter it any further, please leave it open for discussion so that the Terminal team can get to the root of the issue.

**Comment by DHowett** [comment]
Can you share the output of `pwd` when it is displaying the Windows files, and when it displaying the Linux files?

**Comment by mayureshkathe** [comment]
Happy to help.
Please find attached screenshots of both situations.
The first screenshot (named "onDebian") is of the situation when WSL was invoked by typing "debian" at the Terminal prompt, while the second screenshot (named "onPullDown") is of the situation when WSL was invoked by clicking on the pull-down and clicking on the menu entry "Debian".
Please note, "/mnt/c/Users/mayur" is the actual location on the Windows file-system which is masked and shown as "/home/mayur".
![onDebian](https://user-images.githubusercontent.com/67787149/87221241-14ca6b00-c388-11ea-92c6-b30987812585.jpg)
![onPullDown](https://user-images.githubusercontent.com/67787149/87221280-6a9f1300-c388-11ea-902c-62710c782493.jpg)

**Comment by DHowett** [comment]
Thanks! So, the default configuration for Windows Terminal is to run applications in your Windows user profile folder — even if they are in WSL — for consistency.
It’s possible to configure the starting directory for a given profile by specifying the `startingDirectory` setting. We have a bit of documentation about this [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#starting-directory) on our documentation page.

This is something we’re hoping to improve, but if you set your starting directory to `//wsl$/Debian/home/mayur` you’ll have a better experience until we get the defaults changed.

**Comment by mayureshkathe** [comment]
Okay, I experimented a bit more, and followed your hint, those two paths are actually "not" the same.
And running "ls" on those two "different" locations displays different results.
I'll follow your suggestion.
Till then, thanks for taking the efforts.
