### ISSUE TITLE
Reopen/save terminal tabs state

### ISSUE THREAD

**Issue by javidmuhammed** [microsoft/terminal#6872]
# Description of the new feature/enhancement

The existing terminal tabs can be reopened to same state when the system restarts or when the entire terminal is closed.
A persistence memory can be enabled to have the terminal state saved.

# Proposed technical implementation details (optional)

Since the new terminal has a tab like structure, I must be able to reopen the last state of the terminal like chrome/edge tabs. Or I  may be able to save the current terminal state.

**Comment by j4james** [comment]
Is this not the same as #961?

**Comment by javidmuhammed** [comment]
Yes.. Closing the issue-feature
