### ISSUE TITLE
Add icon to "Open Windows Terminal here" Explorer context menu

### ISSUE THREAD

**Issue by felipecassiors** [microsoft/terminal#6875]
Add icon to the "Open Windows Terminal here" Explorer context menu.

## Current: 
![image](https://user-images.githubusercontent.com/29582865/87228828-2c9af280-c37a-11ea-8dd6-34ab5ab3d16d.png)
(took image from https://github.com/microsoft/terminal/pull/6100)

## Proposed:
![image](https://user-images.githubusercontent.com/29582865/87228985-0de92b80-c37b-11ea-9ace-6f42bad27ff4.png)
(see the icon in the red circle, nevermind the secondary context menu, this is just for the sake of beauty. This was generated by using [kerol2r20/Windows-terminal-context-menu](https://github.com/kerol2r20/Windows-terminal-context-menu))

By the way, PowerToys already does it. Other Microsoft apps do as well, OneDrive for example.

**Comment by felipecassiors** [comment]
This is a duplicate of https://github.com/microsoft/terminal/issues/6246. Perhaps, the text on the other issue should be updated with more keywords: context menu, explorer, "Open Windows Terminal here".

**Comment by zadjii-msft** [comment]
It sure is, thanks!

/dup #6246
