### ISSUE TITLE
Add "Python" new tab to the windows terminal automatically

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6877]
After installing Windows Terminal, Command Prompt, Windows Powershell, Powershell Core and Windows Subsystem for Linux will be automatically added to the selection bar of Windows Terminal.
However, Windows Terminal will not be automatically added after installing Python.
I hope that Python can be automatically added to Windows Terminal in a future versions.
![Windows Terminal](https://user-images.githubusercontent.com/23485114/87233997-0d37b000-c3e2-11ea-93d1-cb9ef4b9610a.png)
This issue is duplicate: #6131
cc: @DHowett

**Comment by DHowett** [comment]
As explained in /dup #6131, we're not going to do this by default. Our users have so, so many different things they want that we opted to allow for _customization_ rather than _automatic detection_ for third-party software.

**Comment by xmha97** [comment]
> 
> 
> As explained in /dup #6131, we're not going to do this by default. Our users have so, so many different things they want that we opted to allow for _customization_ rather than _automatic detection_ for third-party software.

OK, Thanks.

**Comment by DHowett** [comment]
Sure thing! Sorry about that :) I know it would be pretty cool if we detected everything, though... 😁
