### ISSUE TITLE
Allow per-profile default  tab colors in settings.json

### ISSUE THREAD

**Issue by rafd123** [microsoft/terminal#6878]
# Allow per-profile default tab colors in settings.json

The ability to specify a custom tab color is great, but having to manually set it is tedious when the motivation is to have a ["seamless experience"](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-1-release/#color-picker) with the profile background as hinted [here](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-1-release/#color-picker):

> ![image](https://user-images.githubusercontent.com/3956545/87235326-050f4e80-c3a9-11ea-991a-0742664d1c84.png)

It'd be nice if one had the ability to specify a per-profile default tab color in settings.json.

For example:

```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    // <snip>

    "profiles":
    {
        "defaults":
        {
            "background": "#000000"
            "tabColor": "#000000" // <------------ Default tab color for all profiles
        },
        "list":
        [
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "background": "#171717",
                "tabColor": "#171717" <------------ Profile-specific default tab color
            },

            // <snip>
        ]
    }

    // <snip>
}
```

Alternatively, instead of adding a new `tabColor` setting, it might be slick if a profile tab color just defaulted to the corresponding profile `background` color to provide the "seamless experience" by default.

**Comment by DHowett** [comment]
Thanks for the request! This is /dup of #1337
