### ISSUE TITLE
Window being moved around causes incredible lag until mouse is stop moving, then rapidly accelerates through path to final point

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/terminal#6880]
# Environment

Specs: AMD Ryzen 3700X, 24GB RAM, AMD Radeon 5700XT
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): Version: 1.0.1811.0

Any other software?
```

# Steps to reproduce

When dragging the terminal window around, the movement will be extremely slow and laggy, when the mouse stops the window will move incredibly fast through the drawn path to the final place of the mouse. I'm not quite sure what causes it as I don't know when the effect started, only noticed the issue recently as I usually snap the window to the sides using 'Win+Arrows'

Sorry if this issue is bad, or I did something wrong, let me know if I need to do something or provide additional info

# Expected behavior

Window moves correctly and doesn't weigh down the mouse, moving at the same speed as every other window in the system

# Actual behavior

Window is incredibly slow to move, and almost acts like its weighing the mouse down, when the mouse is slowed or stopped the window rapidly speeds through the drawn path until it snaps to the final spot the mouse is at.

**Comment by DHowett** [comment]
So, this is weird. Do you have PowerToys installed?

**Comment by Masamune3210** [comment]
Yeah I do, actually forgot I had it installed though as I dont use them. The only ones that are enabled are the File Explorer addons and Window Walker. When I opened the app it said that there was a update, but I'm hesitant to update it now in case there is a conflict that needs to be examined or something

**Comment by Masamune3210** [comment]
It's ver 0.16.1

**Comment by Masamune3210** [comment]
Can upload a video if needed to see the issue, if that would help as well

**Comment by DHowett** [comment]
Well, first, does it reproduce with PowerToys not running? If it’s still a problem with PT disabled, I’m not too worried about conflicts! :)

**Comment by Masamune3210** [comment]
So I just noticed it does the same thing with the PowerToys Settings, so I'm now worried that it may be a certain way of handling the window thats causing the issue?

The issue still occurs with every option in PowerToys turned off

**Comment by Masamune3210** [comment]
The issue does not occur with normal windows like Explorer, or apps like Chrome, or Metro apps like the Settings app or Windows Security

**Comment by Masamune3210** [comment]
So I'm assuming that some other program that I had open was messing with things, because its working fine now. Will reopen if the issue reappears or I find a way to reproduce it, sorry for any wasted time!

**Comment by Masamune3210** [comment]
Strike that, I literally just found the app causing the issue. Its Chrome, but something must have changed because I literally always have chrome open when I have terminal open, as I'm usually using both at once. Let me know if I need to test anything

**Comment by Masamune3210** [comment]
Could it have something to do with the fact that I updated to a new mouse that has a high polling rate? Have been trying to read up on anyone having this issue and some people have noticed a correlation with high polling rates on mice

**Comment by Masamune3210** [comment]
Found it! Lowered the mouse polling to 500 from 1000 and it went away, set it back to 1000 and it came back! Don't know if you can do anything with this information or not, as it seems like a general Windows issue unfortunately, so close this issue if you can't do anything about it. Sorry for the message spam and wasting time if I have

**Comment by zadjii-msft** [comment]
No problems! I'm glad you figured it out, and I'm extra glad you followed up. Hopefully this will help someone else in the future!
