### ISSUE TITLE
I have installed Windows PowerShell 7 and in my settings.json file, I have included:

### ISSUE THREAD

**Issue by SaprativRay** [microsoft/terminal#6881]
I have installed Windows PowerShell 7 and in my settings.json file, I have included:
```
{
  "guid": "{fb0ad4d6-a0de-48b8-8feb-14df8467ad31}",
  "hidden": false,
  "name": "Windows PowerShell 7",
  "commandline": "pwsh.exe"
}
```

Now when I am starting this profile, it says:
`[error 0x80070002 when launching `pwsh.exe']`

_Originally posted by @SaprativRay in https://github.com/microsoft/terminal/issues/4228#issuecomment-657175164_

**Comment by DHowett** [comment]
This means that pwsh.exe isn’t on your system PATH. Either give Terminal the full path to pwsh.exe, or add the directory it’s in to the PATH environment variable.
