### ISSUE TITLE
WSL1 + Windows Terminal broken scroll

### ISSUE THREAD

**Issue by krax1337** [microsoft/terminal#6883]
Hello everyone When I run vim or tmux I can scroll. And I get my past entries in the buffer. On real Linux distributions, this is not present. How can I fix this?

![1](https://user-images.githubusercontent.com/20024303/87246380-df4c7d00-c46e-11ea-92c4-d5201be767e4.PNG)

**Comment by j4james** [comment]
I believe the problem is that Windows Terminal isn't aware that VIM has switched to the alternate buffer, which is what would usually prevent the scrollback from being visible. In which case this is a duplicate of issue #381.

**Comment by krax1337** [comment]
> 
> 
> I believe the problem is that Windows Terminal isn't aware that VIM has switched to the alternate buffer, which is what would usually prevent the scrollback from being visible. In which case this is a duplicate of issue #381.

Thanks for the answer. Well, we can only wait for the problem to be fixed.
