### ISSUE TITLE
FontSize not working

### ISSUE THREAD

**Issue by frostbitefalls** [microsoft/terminal#6884]
# Environment
Windows 10 Pro, 10.0.18362.900

# Steps to reproduce
Windows Terminal 1.0.1811.0 -- edit settings.json, add the line below with any quoted numbers to "defaults",
or to any profile, or both;  save settings.json; any active tabs do not change, exit and restart Windows Terminal.

    "fontSize" : "24"

(line ends with or without a trailing comma , as needed; no errors reported after saving settings.json and none after restart)

# Expected behavior
Font size should change as directed

# Actual behavior
Always the same default font size, never changes; same result with or without specifying any "fontFace".

note: ctrl-+ and ctrl-0 always work OK

**Comment by DHowett** [comment]
You may need to remove the `"` around `24`!

**Comment by frostbitefalls** [comment]
Too easy ;)  About everything else requires quotes.
This item relates to early struggles with misleading error messages from additions to settings.json .
After the wakeup to drop quotes there's a mild surprise the parser didn't gripe about them;
might be worth enhancing the parser, possibly reducing duplicates.
fontSize works OK, thanks.

**Comment by DHowett** [comment]
Yeah, we have a couple things coming that’ll make the parser more strict and the settings more obvious. #6590 is a pull request that unifies our JSON parsing around a couple type-checking helpers that’ll carp about things like this, and of course we have #1564 (spec: #6720) for the settings UI that’ll hopefully obviate the need for folks editing JSON.

Thanks for the feedback :)

**Comment by frostbitefalls** [comment]
Excellent.
After seeing an options UI with `mintty` and the experience editing settings.json, I'd expect a UI for WT settings
will be welcomed.  I'll add votes for options to set scrollbar color and a `solid` cursor!  (eg `rxvt`).
FWIW, consider the wide dissent against the HTML tag \<blink> and when that was dropped.

Meanwhile, thanks again.

**Comment by XilefNori** [comment]
You should really make button "check config" to make user aware that his settings will not apply!
Not just silently discard erroneous config.

**Comment by DHowett** [comment]
So, like this?

(quote from two comments above yours, from @DHowett)

> Yeah, we have a couple things coming that’ll make the parser more strict and the settings more obvious. #6590 is a pull request that unifies our JSON parsing around a couple type-checking helpers that’ll carp about things like this, and of course we have #1564 (spec: #6720) for the settings UI that’ll hopefully obviate the need for folks editing JSON.
