### ISSUE TITLE
wordDelimiters not working, always breaks on a dot '.' or dash '-'

### ISSUE THREAD

**Issue by frostbitefalls** [microsoft/terminal#6885]
# Environment
Windows 10 Pro, 10.0.18362.900

# Steps to reproduce
Windows Terminal 1.0.1811.0 -- edit settings.json, add the line below to "defaults", or any profile, or both; exit and restart;
display some text, eg a set of files including several with extensions like .c, .html, .css, .jpg, .png, others;
double-click any displayed file name.

    "wordDelimiters" : "`'&()*,;<=>?@[]{|}:"

(this example has no '.' and no '-' chars; the line ends with or without a trailing comma , as needed; no errors reported after saving settings.json and none after restarting Windows Terminal)

# Expected behavior
For any displayed file name absent of any delimiter chars shown above, the entire file name should be selected / inverted.

# Actual behavior
Selection / inversion includes characters only up to the first occurrence of '.' or '-' in both directions.

**Comment by DHowett** [comment]
Sorry for the confusion. The word delimiters setting has to be placed at the top level of settings (outside of the profiles area.)

**Comment by frostbitefalls** [comment]
Thanks.  For docs I read [this MS page](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings).
Probably missed the keyword root or the meaning wasn't clear.  After your update I made the change and the feature works OK.
