### ISSUE TITLE
Clicking (not dragging) inside the terminal window shouldn't flush the clipboard

### ISSUE THREAD

**Issue by berzi** [microsoft/terminal#6888]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce

Copy anything to the clipboard, then click in the terminal window, anywhere but the title bar.

# Expected behavior

Dragging text in the terminal replaces the clipboard's contents with it.
Clicking without selecting any text does not impact the clipboard.

# Actual behavior

Dragging text does behave as expected, however when simply clicking, without selecting anything, the clipboard is flushed completely, which also affects data copied from outside Windows Terminal and may result in unexpected data loss as a result of interacting with it.

**Comment by zadjii-msft** [comment]
I'm presuming you have `copyOnSelect` enabled, right?

**Comment by DHowett** [comment]
For what it's worth, I exclusively use `copyOnSelect` and I cannot reproduce this. This is supposed to explicitly guard against it:

https://github.com/microsoft/terminal/blob/09471c3753d888abcfd160dae524988003da862a/src/cascadia/TerminalControl/TermControl.cpp#L1109-L1114

**Comment by berzi** [comment]
It doesn't seem to happen anymore, regardless of the copyOnSelect setting. I assume the behaviour was linked to some specific other application I tried it with. I will update with more information if it happens again (and if the problem seems tied to WT and not this other application).
