### ISSUE TITLE
Some utf-8 characters disappear(not all)

### ISSUE THREAD

**Issue by Kiona0405** [microsoft/terminal#6894]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362. 720]
Windows Terminal version (if applicable): 1.1.1812.0
```

# Steps to reproduce

1. copy "あいう・えお" to clipboard
2. paste clipboard to windows terminal

# Expected behavior
 "あいう・えお"

# Actual behavior
"あいうえお"

I think both "あいうえお" and "・” are utf-8.
But behaviors are different. 

I also try same thing with other editor/terminals(ex. メモ帳, cmder),
and I got expected results.

**Comment by DHowett** [comment]
Are you using powershell, or cmd, or WSL inside Terminal?

**Comment by Kiona0405** [comment]
I use cmd and powershell.
Behaviors are little bit different.

Powershell

- same as above

cmd

- I can paste as expected.
- open some file with nevim(v0.4.3), and paste it, then fail
- connect remote host with ssh, and paste it, then fail.(remote host is centOS7)

**Comment by zadjii-msft** [comment]
Okay so I can confirm that removing `PSReadline` fixes the powershell case here, so this is probably a PSReadline bug that should be filed over in [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine). It's up to each of the client applications to make sure that they can handle the input correctly.
