### ISSUE TITLE
Ability to disable line wrapping in Windows Terminal

### ISSUE THREAD

**Issue by CHerSun** [microsoft/terminal#6895]
# Description of the new feature/enhancement

Currently Windows Terminal wraps lines by default. It would be great to give an option (in settings json) or a shortcut to toggle line wrapping.

Why? One of the reasons are tables printed in console, like "oc get all" for OpenShift. Table lines get wrapped, sometimes more than once - this makes table unreadable (example from my mini cluster, on normal cluster all the tables would be much longer):
![oc get all example](https://user-images.githubusercontent.com/14203878/87297942-f001ff00-c511-11ea-9d41-a3eae0399cdb.png)
Without line wrapping last table would be perfectly readable.

Another example - Linux messages log. 1 message per line would be perfect, but with line wrapping output becomes a mess.

I saw several closed issues on this, but none of them had clear reason why this feature is requested. Like, #6378 , #1860, 

# Proposed technical implementation details (optional)

How? I don't know internal structure of Windows terminal, but I suspect it should be possible to make width larger than window width and use something like a viewport with horizontal scrollbar.

From configuration point of view - it could be one of the options in settings (i.e. separate profile with wrapping disabled), or like this is done in VScode - a shortcut:

&nbsp;&nbsp;&nbsp;&nbsp;![VScode line wrapping example](https://user-images.githubusercontent.com/23485114/84158552-3f6f8e00-aa81-11ea-878a-353061422eec.gif)

**Comment by DHowett** [comment]
Thanks for the request! This is one of the things we're absolutely not going to do -- it's been discussed in a couple different places across the repository, but it all comes back to the same problem: we're not going to add a horizontal scroll bar, because no terminal anywhere _has_ a horizontal scroll bar. The windows console host caused so much trouble by allowing the text buffer to be wider than the actual screen.
/dup #1860, with more info at https://bugzilla.gnome.org/show_bug.cgi?id=769440#c1 (for gnome-terminal, one of our peers)

**Comment by imthenachoman** [comment]
> because no terminal anywhere has a horizontal scroll bar

Is WS Terminal trying to be like every other terminal or better/best?

**Comment by tfiers** [comment]
A semi workaround: temporarily decrease the font size (`ctrl-minus`)

**Comment by marek-stoj** [comment]
> > because no terminal anywhere has a horizontal scroll bar
> 
> Is WS Terminal trying to be like every other terminal or better/best?

In Visual Studio Code we can open a terminal in Editor Area and it does support word wrapping and horizontal scrolling 😌

**Comment by tfiers** [comment]
fyi, upvote https://github.com/microsoft/terminal/issues/1860 to get this higher on the priority list

([zadjii-msft:](https://github.com/microsoft/terminal/issues/1860#issuecomment-908425786) "We've got to prioritize all community asks, and the best way we can do that is with 👍's on issues. As of right now, this issue isn't even on the first 3 pages of [microsoft/terminal/issues (is:open sort:reactions-+1-desc](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)").

**Comment by imthenachoman** [comment]
@DHowett 

> because no terminal anywhere _has_ a horizontal scroll bar

Command prompt does. And isn't Microsoft trying to replace Command Prompt with Terminal? Can't exactly call it a upgrade replacement if it can't do the same thing.

**Comment by DHowett** [comment]
You've all made good points in favor of this feature. Thanks! I'd love to redirect you to #1860 (and am locking this issue to move discussion over there).
