### ISSUE TITLE
Not running after installation with chocolaty

### ISSUE THREAD

**Issue by Ratulhasan14789** [microsoft/terminal#6896]
![image](https://user-images.githubusercontent.com/34002411/87305307-12a70e80-c538-11ea-8e68-a5ffedf38e26.png)
Getting this error after installing the windows terminal with chocolaty. My Microsoft store was causing an error to install any app with it (acquiring license error). So I chose the unofficial build to install and tada! Another error after installing Terminal. Will reboot my system now and give another response.

**Comment by zadjii-msft** [comment]
Well that's a fully useless error message:

<hr>
Inverting error code: query was -2147416359 which is more commonly expressed as 0x800106d9.

HRESULT information | Severity | Facility
-- | -- | --
FAILURE (1) | FACILITY_DEBUGGER (0x001),  FACILITY_RPC (0x001)


Error Code | Symbolic Name | Error Description | Header
-- | -- | -- | --
0x6d9 1753 | `EPT_S_NOT_REGISTERED` | There are no more endpoints available from the endpoint mapper. | `winerror.h`
0x6d9 1753 | `SQL_1753_severity_16` | Column '%.*ls.%.*ls' is not the same length as referencing column '%.*ls.%.*ls' in foreign key '%.*ls'. | `sql_err`

<hr>


Does the Terminal work if you install with `winget`? What version of Windows are you running? What if you install the Terminal directly from our [Releases](/releases) page?

**Comment by Ratulhasan14789** [comment]
Was working fine before the store issue. My brother (owner of the pc) removed terminal and store. Then reinstalled store and the issues started.
Couldn't install winget too (store issue)
Windows 10 1903
Don't know how to install from release page (not clear)

**Comment by DHowett** [comment]
The only way to really restore the store to a system where it's been removed is to reinstall windows. It's not trivial to remove the store, and it is incredibly invasive to the system. Removing the store bears a high risk of breaking your system.
