### ISSUE TITLE
Open 'powershell as administrator' tabs (as a profile type)

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/Terminal#691]
It's pretty frequent for Windows users to need 'powershell as administrator'.

Rather than opening a second instance of Windows Terminal via the Start Menu, it would be better to allow the 'down' menu to include powershell as administrator (by making it a profile type):

    powershell
    powershell (administrator)
    cmd

**Comment by oising** [comment]
I'm not sure the ConPTY support is quite there yet, see #332

**Comment by Kryptos-FR** [comment]
Isn't there a risk of elevation of privileges leaking to other tabs?

I could be wrong but I suppose that to be able to run a powershell tab as administrator, the whole Terminal app would need to also be elevated. Are there ways to prevent that?

**Comment by oising** [comment]
There are ways to do it, but it's not trivial: https://github.com/parkovski/wsudo

**Comment by mdtauk** [comment]
Without implementing a per command UAC elevation similar to 'nix's **Sudo** for all the various consoles and WSL - I think a _Process per Tab_ implementation, with a UAC prompt on profile adding would be sensible.

It will require security protection and all the careful coding needed to make it possible, so may not be an achievable V1 goal.

**Comment by zadjii-msft** [comment]
This is a dupe of #632, so I'll redirect discussion there.

**Comment by BlarneyBarris** [comment]
Wouldn't it be possible to use something like `"commandLine" : "powershell.exe runas /env <define elevated .pc1 file>"` variable of PowerShell, specifying a profile file that elevates the user from functions available, similar to automatically elevating a profile when opening PS from the ISE?

**Comment by heyJonBray** [comment]
Wouldn't it be possible to change the `"commandLine" : "powershell.exe /profile <elevated user profile .pc1 file>"` variable to the PS function(s) you would do within the ISE to start a profile in elevated mode?

**Comment by ckasabula** [comment]
Have been using ConEmu for years, which supports a mix of elevated and non-elevated tabs. I was thinking Windows Terminal would be a good alternative, but I don't want to run 2 instances when I can run just 1 ConEmu instance.

**Comment by mikemaccana** [comment]
All: there's no doubting that various other apps have the ability to run elevated instances inside them, the reason Microsoft haven't added this feature for Terminal yet is that's there's a security risk within Windows of doing so. The other apps have that security risk, Microsoft for good reason don't want to expose their users.

With any luck Microsoft folk might fix Windows itself to allow elevated subprocesses (which may be very difficult), but otherwise the best best is for some other solution (eg, the ability to spawn a separate elevated window being easier)

**Comment by zadjii-msft** [comment]
@ckasabula Thanks for the feedback, but we won't be allowing mixed elevated and unelevated instances in the same window, because it presents too large a security risk. You can refer to this thread: https://github.com/microsoft/terminal/issues/632#issuecomment-519375707 for more details. ConEmu can offer that functionality and accept that risk, but unfortunately we can't.

**Comment by dranovsk** [comment]
Try [gsudo](https://github.com/gerardog/gsudo) as workaround.

**Comment by survivant** [comment]
it's the first time that I'm using Windows Terminal.  Really nice to have PowerShell and WSL in a terminal.  But I still don't understand why I can't have a tab with PowerShell as Administrator.  In my taskbar I have Powershell pinned there and I right click on it.. Open as Administrator.  Why can I have the same thing with Windows Terminal ?   I'm never using powershell and cmd.exe in normal user.

**Comment by zadjii-msft** [comment]
@survivant  I mean, you can definitely open the Terminal as an administrator:

![image](https://user-images.githubusercontent.com/18356694/111172829-2649bf80-8574-11eb-8a20-658c272eea78.png)

We're just not going to let you put elevated instances inside an unelevated window. There's a bunch of other quality-of-life improvements for running the terminal elevated we've got planned over in #8455.

**Comment by PanosGreg** [comment]
kudos to @dranovsk for the gsudo mention!
to install just: `choco install gsudo -y` (from an elevated console, you need chocolatey obviously)

Just create a new windows terminal tab, for ex. _PowerShell (Admin)_
and then in the command line text field: `gsudo pwsh`
and that's it, every time you open that tab, you'll get a UAC prompt (cause it 's an elevated process)
and in the end, you'll have normal (non-elevated) tabs and elevated (admin) tabs in the same windows terminal app.

**Comment by RobBiddle** [comment]
Clearly there's a potential security risk of running elevated console tabs inside a non-elevated Windows Terminal.

**Comment by flatline-studios** [comment]
> kudos to @dranovsk for the gsudo mention!
> to install just: `choco install gsudo -y` (from an elevated console, you need chocolatey obviously)
> 
> Just create a new windows terminal tab, for ex. _PowerShell (Admin)_
> and then in the command line text field: `gsudo pwsh`
> and that's it, every time you open that tab, you'll get a UAC prompt (cause it 's an elevated process)
> and in the end, you'll have normal (non-elevated) tabs and elevated (admin) tabs in the same windows terminal app.
> 
> Also, to distinguish the tab from the regular PowerShell, here's an icon with red powershell
> [Powershell ico Files](https://drive.google.com/drive/folders/1DRlxa1wnbf9xbOplVNxCiTFRfmw2P6Lv)

I get:

```
> gsudo pwsh
pwsh : The term 'pwsh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ pwsh
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pwsh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by blalonde-tryeverything** [comment]
> kudos to @dranovsk for the gsudo mention!
> to install just: `choco install gsudo -y` (from an elevated console, you need chocolatey obviously)
> 
> Just create a new windows terminal tab, for ex. _PowerShell (Admin)_
> and then in the command line text field: `gsudo pwsh`
> and that's it, every time you open that tab, you'll get a UAC prompt (cause it 's an elevated process)
> and in the end, you'll have normal (non-elevated) tabs and elevated (admin) tabs in the same windows terminal app.
> 
> Also, to distinguish the tab from the regular PowerShell, here's an icon with red powershell
> [Powershell ico Files](https://drive.google.com/drive/folders/1DRlxa1wnbf9xbOplVNxCiTFRfmw2P6Lv)

Thanks to @PanosGreg for this tip!

FYI: If you're using Powershell 7.x (aka Powershell Core, **pwsh**) you'll want to use `gsudo pwsh.exe`

**Comment by ylluminate** [comment]
Thanks so much for the `gsudo pwsh.exe` tip @PanosGreg - shame Microsoft doesn't work towards developer intuitiveness and needs like Apple once did (and now doesn't either). Tip: after doing the above you have to also restart Terminal if you've had it running while installing Chocolatey + gsudo.

**Comment by oising** [comment]
> shame Microsoft doesn't work towards developer intuitiveness and needs

@ylluminate This is completely unfounded and absolutely incorrect. Balancing intuitiveness/easy of use and security is a delicate dance, and one that Microsoft does far better in the last ten to fifteen years than Apple ever has. The reason you're seeing Apple leaning this way now too is that they too are coming to grips with this balance.

**Comment by ylluminate** [comment]
@oising after 30 years of experience in this area I'm allowed to disagree with you and could also demonstrably say that you're wrong with **_unequivocal refutation_**, but we'll stop this now before it get's too hot in here.

**Comment by oising** [comment]
> @oising after 30 years of experience in this area I'm allowed to disagree with you and could also demonstrably say that you're wrong with **_unequivocal refutation_**, but we'll stop this now before it get's too hot in here.

You can disagree with me anyway you wish, but it's less convincing if you attempt to do so via _**argumentum ad verecundiam**_ ;) Have a nice day.

**Comment by DHowett** [comment]
> we'll stop this now before it get's too hot in here.

This seems to be a classic tactic: firing another salvo while saying "This will be the last one -- I do not expect you to respond" is clearly bait and that sort of behavior is not one I'm ready to tolerate in my repository. If you want to have a disagreement, do so in a fundamental and evidence-based way.

This project wouldn't exist if we weren't working to address the needs of developers in our ecosystem. Refute that if you'd like, but we've gotten here _against all the odds_ by making our case to the people in the company who would hear us.
