### ISSUE TITLE
Support for cursor change from normal to insert mode in Vim 

### ISSUE THREAD

**Issue by coldspark29** [microsoft/terminal#6914]
**Description of the new feature/enhancement**
Vim has a block cursor in nomal mode and a line cursor in insert mode. The Windows terminal does not support this function, but always shows the same cursor. This feature should definitely be supported, because it is crucial to the Vim experience.

**Comment by DHowett** [comment]
/dup #68 this is supported, you just need to configure vim to do the right thing
