### ISSUE TITLE
Entering many empty lines in PowerShell causes overwriting instead of scrolling

### ISSUE THREAD

**Issue by rjb3977** [microsoft/terminal#6916]
# Environment

```none
Windows build number: 10.0.19042.330
Windows Terminal version: 1.0.1811.0

Any other software?
```

# Steps to reproduce

Open PowerShell in Windows Terminal, and hold Enter until the `PS ...> ` prompt fills the entire screen.

# Expected behavior

You can scroll back up to see the initial splash message (copyright, try the new PowerShell, etc). This is what happens in a non-Windows-Terminal PowerShell window.

# Actual behavior

The lines are overwritten rather than actually scrolled. You cannot scroll up at all.

**Comment by zadjii-msft** [comment]
@rjb3977 Could you share your `settings.json`?

**Comment by DHowett** [comment]
This sounds dangerously similar to https://github.com/PowerShell/PSReadLine/issues/724

**Comment by rjb3977** [comment]
Yep, that sounds like it. I'll close this then.
