### ISSUE TITLE
Resetting WSLv1 shell does not start from terminal top

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#6917]
Version: 1.0.1811.0

After typing `reset` in my WSLv1 shell, I get this. Unfortunately, I do not have a stable repro. Stumbled on this in a long-running Terminal session.
![image](https://user-images.githubusercontent.com/1041752/87479266-75c59d80-c62b-11ea-95a8-7bef304e08e8.png)

**Comment by zadjii-msft** [comment]
I'd bet that @j4james magically knows exactly what this is. If he doesn't, then I'm not really sure what we can do to investigate this without some sort of stable repro...

**Comment by DHowett** [comment]
Thanks for the report! This was fixed in PR #6763, and is a /dup of #6545

**Comment by vadimkantorov** [comment]
In general it may be cool to somehow enable « tracing » mode that would collect information about current state of terminal and could record characters/events. Then this trace/log could be uploaded here for cases when a repro is hard to find.

Maybe there can be a limited, but still useful scope of this idea

**Comment by DHowett** [comment]
So, we do actually have something like that! It's the "debug tap", and it shows what's coming out of the PTY infrastructure.

If you set the global setting `debugFeatures` to `true` and then hold own left+right <kbd>Alt</kbd> while opening a new tab, you'll get this:

![image](https://user-images.githubusercontent.com/189190/87480715-c369e800-c5e2-11ea-8f70-ee787b61a9f0.png)

(the red on the right is the input stream -- right now, i'm running in win32 input mode where each key is transformed into an entire sequence capturing scancode/vkey/repeat/modifiers (#4999), so it's a little verbose.)

**Comment by DHowett** [comment]
There's also local tracing accessible through a `wprp` file in our source folder. :smile:

**Comment by vadimkantorov** [comment]
Wow. I think it would be super-cool to make it more accessible to users (with an instruction how to record and view/upload such a trace?) :) Probably many more "stable repro"-less bugs would be less frustrating to report.

What is  "source folder"? (I didn't build terminal from source)

**Comment by DHowett** [comment]
Ah, I definitely meant "the folder with the source code in it". The tracing tools that ship with windows are not particularly user-friendly, and as such neither is our wprp file. 😦
