### ISSUE TITLE
Forms of communication between developers?(Discord/Teams/Slack/Email)

### ISSUE THREAD

**Issue by Puthranps** [microsoft/terminal#692]
Will, there be a teams/slack/discord or email listing that where we can collaborate in real time? If this proposal can get approved for a discord server I can submit a pr on the Readme with a permalink. I would like there to be a way to communicate with the developers without having to post new issues.

**Comment by zadjii-msft** [comment]
I believe this is a question for @DHowett-MSFT or @bitcrazed

**Comment by Puthranps** [comment]
That would be great I think it would be more convenient than doing Twitter dm',s and some non Microsoft maintainers may get the chance to communicate with each other on one platform

**Comment by Puthranps** [comment]
For preference I think we should discord because slack can erase message history and doesn't scale too well and teams I think would be more accessible than teams and email.

**Comment by bitcrazed** [comment]
We are definitely looking into options re. discussions & chat. Please bear-with us while we figure out a plan here.

**Comment by Puthranps** [comment]
@bitcrazed no rush at all I just wanted to make this suggestion thanks for taking this issue into consideration.

**Comment by MooseA** [comment]
https://discord.gg/eDGKaZ

**Comment by DHowett-MSFT** [comment]
This is not the official team Discord. There is no official team discord.

**Comment by DHowett-MSFT** [comment]
@MooseA Please don't post unrelated social links to unrelated communities. Thanks!

**Comment by nishp77** [comment]
Please could we have some means of communicating ?? rather than the issues??

**Comment by bitcrazed** [comment]
Update 2019-09-11 - We have begun discussions with a team that's working on a generalized solution in this space, but it's going to be a few months until its viable.

In the meantime, please continue to post issues here: The Terminal dev team are constantly monitoring and responding to issues in this repo, ensuring a good likelihood of a response.

If you want to ping us elsewhere, you'll likely have some luck by pinging us on Twitter: [Rich](https://twitter.com/richturn_ms) or [Kayla](https://twitter.com/cinnamon_msft)

**Comment by zadjii-msft** [comment]
You know, it's been a could years, and IMO we've had a pretty good flow here on GitHub alone. I'd rather not fragment our communication into multiple platforms. Discussing features and bug fixes here on github has been a reliable way of communicating with our external contributors, so I think we'll just stick with that. Thanks for the suggestion!
