### ISSUE TITLE
Allow to reposition tabs

### ISSUE THREAD

**Issue by anubhms** [microsoft/terminal#6927]
Currently the position of tabs in the Terminal are fixed, and when working with large number of tabs it's natural to try and position them together for easier access. And the current fixed tabs layout prevents that, so can we allow to reposition the tabs like you can do in a browser?

**Comment by leejy12** [comment]
Are you running the terminal in administrator mode?

**Comment by OptimiliaStudios** [comment]
Yes

**Comment by anubhms** [comment]
Yes, I am running it in administrator mode. 
Just now checked and it allows to re-position tabs in non-elevated mode. Any reasons for that?

**Comment by leejy12** [comment]
Seems like it's due to platform limitation. See #6893

**Comment by zadjii-msft** [comment]
Yep, @leejy12's right here. 

/dup #6893 #4874 #5564
