### ISSUE TITLE
quick command binding like xshell

### ISSUE THREAD

**Issue by wfireleaves** [microsoft/terminal#6928]
# What & Why
Using binding keys to input some commands or just a string to terminal. It's very useful for common commands and complex commands.

Type 'ctrl+1' to actually input a common command like 'ps -ef | grep server | grep -v grep'
It also can use to send command to all opened tab.

# How 
By using setting keys binding. we can set a new command action like 'input', we can bind it to keys like 'ctrl+0~ctrl+9' or any other keys. 
for example.
```
{
	"command":{"action":"input", "argument":"my common command 1"},
	"keys":["ctrl+1"]
}
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3799 for more discussion.

/dup #3799
