### ISSUE TITLE
git log cannot print correct chinese charecter

### ISSUE THREAD

**Issue by shinegrin** [microsoft/terminal#6929]
I'm running powershell with windows terminal, with ENV `LESSCHARSET=utf-8` and gitconfig as following:
```gitconfig
[difftool "sourcetree"]
	cmd = '' \"$LOCAL\" \"$REMOTE\"
[mergetool "sourcetree"]
	cmd = "'' "
	trustExitCode = true
[i18n]
	commitencoding = utf-8
	logoutputencoding = utf-8
[core]
	quotepath = false
[gui]
	encoding = utf-8
```
It works well when i using powershell without windows terminal.
Anyone knows how to fix it?

**Comment by chana71** [comment]
for followers who met this problem please [see ](https://answers.microsoft.com/zh-hans/windows/forum/all/win-10/07ca1410-cc2b-47e1-a424-c01b57dabdbe)
