### ISSUE TITLE
Windows Terminal for Azure Cloud Shell is transparent in active

### ISSUE THREAD

**Issue by MakurodaHotmail** [microsoft/terminal#6930]
# Environment

```none
**Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]**
PS C:\Users\makuroda> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

**Windows Terminal version (if applicable):**
Windows Terminal
Version: 1.0.1401.0


Any other software?
```

# Steps to reproduce
Create new Azure Cloud Shell tab after starting Windows Terminal.

# Expected behavior
When Windows Terminal is Active, Terminal is not transparent.

# Actual behavior
But my Windows Terminal does not work.
When tab is active, Terminal is transparent. In non-active, Windows terminal is not transparent.

//non-active
![image](https://user-images.githubusercontent.com/62370373/87543134-204ac880-c6df-11ea-8005-db033974f537.png)

//active
![image](https://user-images.githubusercontent.com/62370373/87543184-3789b600-c6df-11ea-836f-a66715281660.png)

**Comment by zadjii-msft** [comment]
This is probably due to that profile enabling acrylic in the settings. You can disable the transparency by opening the settings file, and adding `"useAcrylic": false` to the Azure Cloud Shell profile.

**Comment by MakurodaHotmail** [comment]
@zadjii-msft 
Thank for comment! It works fine!!
