### ISSUE TITLE
Terminal doesn't adhere to the system language setting

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/terminal#6931]
# Environment

```none
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1811.0

Any other software? -
```

# Steps to reproduce

1. Have the Windows display language set to English, but the "localisation" (date etc.) setting set to another language, e.g. Switzerland.
2. Open Windows Terminal. Its text labels are all German, while the "main content" is all English, as it should be.

# Expected behavior

All my Explorer, Desktop, Settings panels etc are in English. Terminal should be English too.

# Actual behavior

See above description plus below screenshots.

![image](https://user-images.githubusercontent.com/4967343/87557273-98999580-c6af-11ea-8f87-7f7432c8de02.png)

![image](https://user-images.githubusercontent.com/4967343/87557296-a2bb9400-c6af-11ea-8006-4eb72123346d.png)

![image](https://user-images.githubusercontent.com/4967343/87557734-31301580-c6b0-11ea-8e87-1007e134557a.png)

Everything else is (correctly) English:

![image](https://user-images.githubusercontent.com/4967343/87557379-c1ba2600-c6af-11ea-9acb-776f806b2cce.png)

![image](https://user-images.githubusercontent.com/4967343/87557434-d0a0d880-c6af-11ea-9843-77e2a1a1de0a.png)

![image](https://user-images.githubusercontent.com/4967343/87557612-05149480-c6b0-11ea-9ffd-0a1d72e25225.png)

**Comment by zadjii-msft** [comment]
This seems like it's related to the discussions in either #5497 or #6029 - should we close this as a dupe of one of those two?

**Comment by patrikhuber** [comment]
@zadjii-msft Yes, these are the same issues. I searched for this before posting to avoid a duplicate issue but haven't seen those.

I disagree with some of the MSFT comments there that this is a "feature" (of the Windows Store) and this is working correctly. TO me this is clearly a bug. But let's close this, I will post in #5497! :)
