### ISSUE TITLE
input chinese in vim by using git bash stuck

### ISSUE THREAD

**Issue by wfireleaves** [microsoft/terminal#6933]
# Environment
I add git bash into windows terminal.

Windows build number: `[10.0.18363.900]`
Windows terminal version: `[1.0.1811.0]`
Git bash version: `[mintty 2.5.0(x86_64-pc-msys)]`

here is my setting:
`{
        "guid": "{980753ab-1977-4cef-9c66-c9765f9f98d5}",
	"commandline" : "C:\\Program Files\\Git\\bin\\bash.exe -i -l",
	"fontSize" : 10,
	"historySize" : 9001,
	"icon" : "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
	"name" : "Git bash",
	"startingDirectory" : "%USERPROFILE%"
}`

# Steps to reproduce
 I can use git bash without windows terminal to input Chinese in vim.
 I can use git bash opened in windows terminal input Chinese in normal command line.
 I can use windows terminal ssh to my remote Linux server using vim input Chinese.
 I cannot using windows terminal open git bash to input Chinese in git bash's vim, when I do it, it will stuck and cannot type any command, even if `Esc` or `Ctrl + Q`
 I'm really confused.

# Expected behavior

I can using windows terminal open git bash as I add it into settings to input Chinese in vim.

# Actual behavior

I cannot input Chinese in git bash which opened in windows terminal.

**Comment by zadjii-msft** [comment]
By any chance, could you try out the [Windows Terminal (Preview)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwid4c6E-NHqAhWbK80KHegjD68QFjACegQIARAB&url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fp%2Fwindows-terminal-preview%2F9n8g5rfz9xk3&usg=AOvVaw1UGFZxJy-lyItUQVHb-VZF) version and see if that works? There's a bunch of input changes in 1.1 that might help here.

**Comment by wfireleaves** [comment]
OK, I'll try it ASAP, thanks a lot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wfireleaves** [comment]
> By any chance, could you try out the [Windows Terminal (Preview)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwid4c6E-NHqAhWbK80KHegjD68QFjACegQIARAB&url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fp%2Fwindows-terminal-preview%2F9n8g5rfz9xk3&usg=AOvVaw1UGFZxJy-lyItUQVHb-VZF) version and see if that works? There's a bunch of input changes in 1.1 that might help here.

I have try it, unfortunatly, the preview version worked in one of my computer, but not work in another.
maybe there is some difference of Git Bash version between two computer. I will try latter.
Thank you.

**Comment by wfireleaves** [comment]
When I update my Git Bash version to 'mintty 3.2.0(x86_64-pc-msys)[Windows 18363]', it seems works.
Thanks all.
