### ISSUE TITLE
Add retroTerminaleffect scheme to defaults.json

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#6934]
# Description of the new feature/enhancement
Under https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/retro-command-prompt, the shown prompt has a scheme listed but if you simply enable the effect, it does nothing without configuring the scheme. I think this scheme should be added to defaults.json so when users enable the retroTerminalEffect, they automatically get the retro theme. I also think it should configured under CMD profile as false so users can copy/paste the setting and set it to true.

# Proposed technical implementation details (optional)
Just add it to the list of schemes in `defaults.json`.

**Comment by zadjii-msft** [comment]
The retro terminal effect will work just fine regardless of which color scheme you're using - that sample just shows one way of configuring the terminal with both the retro effect and a retro scheme. 

Which version of the Terminal are you running? I don't think that 1.0 has support for hot-reloading the retro terminal effect. Maybe that's what you're seeing?

**Comment by WSLUser** [comment]
I tried it on Windows Terminal Preview v1.1.1812.0. I was going to create a PR to add the scheme but if it's separate from the setting then I won't add it.

**Comment by zadjii-msft** [comment]
You know what, I don't think 6551 has shipped in Preview quite yet. That probably explains it. 

Since the setting is in fact, totally unrelated to the scheme, I'm gonna close this one out. Thanks!
