### ISSUE TITLE
Can't use some fonts

### ISSUE THREAD

**Issue by ocitrev** [microsoft/terminal#6936]
# Environment
Microsoft Windows [Version 10.0.19041.329]
Windows Terminal Version: 1.0.1811.0
Same issue latest sources 592c63457781c9d753ae6648f03c96d998a0080e

# Steps to reproduce

Install CascadiaCodePL.ttf version 2007.001
In the settings.json file, add this line in the `defaults` section
```
"fontFace": "Cascadia Code PL Light"
```

# Expected behavior
The font used to render the termial should be `Cascadia Code PL Light`

# Actual behavior

The font used to render the terminal is `Consolas`

using the regular Cascadia Code PL font works as expected:
```
"fontFace": "Cascadia Code PL"
```
# Note
Other applications, like VSCode, will render text using `Cascadia Code PL Light` font on the same system.

**Comment by DHowett** [comment]
Unfortunately, Terminal expects a font _family_ (we realize that we named the setting improperly). In the latest preview (1.1, which is entering the stable channel soon) we added support for `fontWeight`. Once you're hit with the update, you'll have to ...

```
"fontFace": "Cascadia Code PL",
"fontWeight": "light",
```

/dup #1163 #6048

**Comment by Cypher1** [comment]
@microsoftopensource can the @msftbot be updated to link the duplicate? I'd love to see the resolution of this bug. Thanks

**Comment by DHowett** [comment]
@cypher1 with the way we usually use the bot, the duplicate IDs are in the comment directly above the bot's response.
In this case, they're #1163 #6048.

**Comment by DHowett** [comment]
Along with an explanation of why and how to fix it. :smile:

**Comment by Cypher1** [comment]
Ahh! Thank you, had only got the notification and wasn't used to the bot behaving that way. Cheers
