### ISSUE TITLE
mouse clicking generates chars

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#6941]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows [Version 10.0.19042.388]
nothing special

# Steps to reproduce

not 100% reproduce,might be:
1. ssh on a server and works for a while
2. leave it until ssh session timeout and disconnected
3. click on Windows Terminal THE LEFT HALF PART, it will generate meaningless(?) chars each click,like "r/#q/ |N#|N {N#~N(", or say "blah#blah", looks like relevant to mouse position.

# Expected behavior
no strange behavior

# Actual behavior

![image](https://user-images.githubusercontent.com/1884240/87634214-6bacb780-c76f-11ea-8463-f947186c5d92.png)

**Comment by DHowett** [comment]
So, this is the same as #6909; I explained what happens in a couple comments down that thread.
/dup #6909
