### ISSUE TITLE
Windows Terminal shows texts in Cyrillic, although my default UI language is English.

### ISSUE THREAD

**Issue by kypeli** [microsoft/terminal#6943]
# Environment

```none
Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce
I just opened Windows Store, searched for "Windows Terminal", launched it when it was installed and tapped on the arrow down next to the terminal window title to open another terminal screen. I noticed that most of the text was in Cyrillic, as is the "About" screen, although my default language is English. I have a Russian language pack installed, but I haven't even activated it for my input type.

# Expected behavior
All texts are in English.

# Actual behavior
Most of the texts are in Cyrillic (I don't speak Russian, so I don't know what it says)

Please see the screenshots below of the issue and please notice that my UI default language is set to English.

![2020-07-16](https://user-images.githubusercontent.com/39245/87645698-84f53a00-c756-11ea-9ce7-8c8e25929f0b.png)
![Capture](https://user-images.githubusercontent.com/39245/87645705-86266700-c756-11ea-98be-bb56f6d2a87b.PNG)
![2020-07-16 (1)](https://user-images.githubusercontent.com/39245/87645701-858dd080-c756-11ea-83a8-2613738eff4e.png)

**Comment by kypeli** [comment]
Removing the Russian language pack fixed the issue apart from one sentence in the menu. 

I would still not expect the UI to be in Russian as it's not my UI language.
![2020-07-16 (2)](https://user-images.githubusercontent.com/39245/87646399-78bdac80-c757-11ea-8c94-c25588500359.png)
![2020-07-16 (3)](https://user-images.githubusercontent.com/39245/87646402-79564300-c757-11ea-8bca-934682108361.png)

**Comment by j4james** [comment]
I suspect the problem may be that Windows Terminal doesn't have a specific translation for UK-English, and the way you ordered your language packs indicated that you wanted Russian and Finish in preference to US-English. If you move US-English further up the list you'll probably get better results.

**Comment by kypeli** [comment]
I am not familiar with how localizations on the Windows platform are done. But somehow I would have expected that there is a common translations for English in general for both the US and UK locales and then only the differences are translated for each locale separately.

**Comment by kypeli** [comment]
I have now rebooted my machine and also removed the English-UK locale. I can, however, still see the one menu item in Russian, which is weird to me.
 
![2020-07-16 (6)](https://user-images.githubusercontent.com/39245/87673039-876a8a80-c77c-11ea-8397-605de800066d.png)
![2020-07-16 (5)](https://user-images.githubusercontent.com/39245/87673056-8e919880-c77c-11ea-87b5-069cc1b44a96.png)

**Comment by j4james** [comment]
Ah, that may just be part of your settings file now. I suspect it auto-generated your initial set of profiles when you still had the Russian language pack installed. If you want to change the name of that profile entry now, you'll need to edit your settings and then just rename it to whatever you want.

**Comment by kypeli** [comment]
Yes, you are right! Deleting the settings.json file fixed the issue. Looks like all strings are in English now.

Since I am not familiar with how Windows localizations should behave, feel free to close this issue if you feel it works as intended.

**Comment by zadjii-msft** [comment]
Glad this got sorted out! I'm gonna link this up to #5497, #6029, #6931 for future readers, which have all had similar discussions as well. 

Thanks!
