### ISSUE TITLE
Feature Request: Active Pane Maxmise / Minimise hotkey

### ISSUE THREAD

**Issue by lgisler** [microsoft/terminal#6944]
# Description of the new feature/enhancement

I have looked in the Issues, and in the default.json settings file under //Pane Management and have been unable to find this feature.

I have just recently moved from developing in Linux to Windows. I have really enjoyed the Linux application Byobu to manage my terminal experience. One feature that I used extensively was "zoom into a split, zoom out of a split". In Microsoft Terminal language that might be "zoom into a pane, zoom out of a pane". 

I would be happy to implement this feature if it is deemed useful, but I have not contributed to this project before so some guidance to point me in the right direction would be greatly appreciated. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #996 for more discussion.

/dup #996
