### ISSUE TITLE
No "Open Windows Terminal here" entry in context menu.

### ISSUE THREAD

**Issue by NonoHh** [microsoft/terminal#6945]
# Environment

```none
Windows build number: 10.0.19041.388
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
```

# Steps to reproduce

The feature in PR [#6100](https://github.com/microsoft/terminal/pull/6100) has been merged in v1.1.1671.0. My version is later than it, but when I right click a selected directory, there is no such an entry.
I haved tried to reinstall Windows Terminal in Microsoft Store and reboot my PC. Still no entry.
This is the entries of right click.
![image](https://user-images.githubusercontent.com/38282832/87656945-bf79c980-c78c-11ea-9815-1232695c468d.png)

This is the entries of shift + right click. 
![image](https://user-images.githubusercontent.com/38282832/87657372-547cc280-c78d-11ea-82ea-50eefffbe3a3.png)

# Expected behavior

How to enable this feature?

# Actual behavior

No entry neither in right click nor shift + right click

**Comment by kanadaj** [comment]
@NonoHh I'm having the same trouble, did you figure this one out?

**Comment by DHowett** [comment]
@kanadj just to make sure: **what version of terminal do you have installed**

**Comment by kanadaj** [comment]
> @kanadaj just to make sure: **what version of terminal do you have installed**
Latest on the Windows Store (normal, not  the preview version). Literally downloaded today.

**Comment by petibear** [comment]
how is this solved, please?  I'm on 1.1.2021.0, yet I can't see Windows Terminal when I shift right click.

**Comment by zadjii-msft** [comment]
@petibear It's not on the shift+right click menu, it's on the normal right-click menu, but only when you directly right click on a folder. There are [a bunch of open work items ](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3AArea-ShellExtension)tracking the right-click menu, so make sure to check those out.

<hr>

@kanadaj That's certainly weird. I know that while I was working on developing this, it often wouldn't load until I rebooted `explorer.exe`, so maybe a restart is needed?

**Comment by petibear** [comment]
thanks a lot for the clarification. I see, and this works, true, never noticed as my habit has been to shift right click when inside. this is good enough, thanks !

**Comment by kanadaj** [comment]
> It's not on the shift+right click menu, it's on the normal right-click menu, but only when you directly right click on a folder.
Aaaah I see. That's... Not great. 

Though I've found this project https://github.com/lextm/windowsterminal-shell which is a fair bit better since it adds an option for each different console, as well as a separate option to open as administrator.
