### ISSUE TITLE
Windows Terminal keeps forgetting/can't find my default WSL Ubuntu profile

### ISSUE THREAD

**Issue by DuncanSimon** [microsoft/terminal#6946]
# Environment

```none
Windows build number: Version 1909 (OS Build 18363.900)
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
Ubuntu 18.04 LTS for WSL
```

# Steps to reproduce

1. WSL and Ubuntu 18.04 are already installed and configured. 
2. Install Windows Terminal from the Microsoft Store.
3. Upon first installation, it will automatically pick up the Ubuntu profile
4. Set the Ubuntu profile as default in `settings.json`
5. After e.g. restarting the pc, Windows Terminal can no longer find the default profile and does not list Ubuntu in the drop-down

# Expected behavior

Ubuntu 18.04 for WSL to persist as the default profile that Windows Terminal uses when it launches.

# Actual behavior

After e.g. restarting the pc, Windows Terminal can no longer find the default profile and does not list Ubuntu in the drop-down.
The following error occurs when launching Windows Terminal:
"
_Encountered errors while loading user settings
Could not find your default profile in your list of profiles - using the first profile. Check to make sure the "defaultProfile" matches the GUID of one of your profiles._
"
 
The defaultProfile guid matches that of the Ubuntu profile. JSON for Ubuntu profile:
```
           {
                "guid": "{some_guid}",
                "hidden": false,
                "name": "Ubuntu-18.04",
                "source": "Windows.Terminal.Wsl",
		"startingDirectory": "//wsl$/Ubuntu-18.04/home/my_username"
            }
```

**Comment by DHowett** [comment]
If you relaunch terminal some time later, does the Ubuntu profile show back up?

**Comment by DuncanSimon** [comment]
No, it seems to lose track of it forever.

**Comment by DHowett** [comment]
Can you share the output of `wsl -l -v --all`? If that fails, can you just run `wsl -l`?

**Comment by DuncanSimon** [comment]
It didn't like the `-v` flag, but `wsl -l` gives:
```
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
```

**Comment by DHowett** [comment]
Wow, this is really unexpected. Can you share your entire `settings.json`?

**Comment by DuncanSimon** [comment]
I wonder if it's something to do with `"source": "Windows.Terminal.Wsl"`, because when I comment this line out, it does seem to launch into Ubuntu. Although it's not quite right, because it doesn't set all the colour/font scheme settings I have, doesn't have the Linux icon, and doesn't like me passing in a starting directory. 

Here's the full `settings.json`:

```
// This file was initially generated by Windows Terminal 1.0.1811.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
                "hidden": false,
                "name": "Ubuntu-18.04",
                "source": "Windows.Terminal.Wsl",
		"startingDirectory": "//wsl$/Ubuntu-18.04/home/<user>",
		"colorScheme": "Ubuntu",
		"fontFace": "DejaVuSansMono"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [
		{
			"name": "Ubuntu",
			
			"background": "#300a24",
			"foreground": "#eeeeec",
			
			"black": "#2e3436",
			"red": "#cc0000",
			"green": "#4e9a06",
			"yellow": "#c4a000",
			"blue": "#3465a4",
			"purple": "#75507b",
			"cyan": "#06989a",
			"white": "#d3d7cf",
			"brightBlack": "#555753",
			"brightRed": "#ef2929",
			"brightGreen": "#8ae234",
			"brightYellow": "#fce94f",
			"brightBlue": "#729fcf",
			"brightPurple": "#ad7fa8",
			"brightCyan": "#34e2e2",
			"brightWhite": "#eeeeec"
			
		}
	],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}
```

**Comment by DHowett** [comment]
Interesting. So, when you comment out `source` two things happen.

* Terminal stops deleting the profile
* Terminal launches _cmd.exe_ (lol), not wsl

When a profile has a _source_ and a _guid_, Terminal queries to make sure that the source (in this case, "wsl") still thinks it exists. When Terminal asks, unfortunately, WSL reports that there aren't any installed distributions.

Are you running WT at a different user than your desktop session?

**Comment by DuncanSimon** [comment]
Yeah that's basically what happens. I'm running WT as the same user. It's so odd because whenever I do a fresh install of WT it always works fine, and then at some point it just breaks.

**Comment by DuncanSimon** [comment]
Is there some hidden guid that my Ubuntu installation has that causes a conflict?

**Comment by DuncanSimon** [comment]
By commenting out `"source"` using `"commandline" : "wsl -d Ubuntu-18.04"` (from the docs [here ](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#setting-the-startingdirectory-of-wsl-profiles-to-)) instead, it seems to work more or less the same way as it does on a fresh install that uses `"source"`

So what do you think is happening with `"source": "Windows.Terminal.Wsl"`?

**Comment by DHowett** [comment]
So, going out even further on a limb ... does it take a while for `wsl` to respond when you run `wsl -l` or start up Ubuntu?

**Comment by DuncanSimon** [comment]
When it was in a broken state, I would say yes. Compared to now (no errors because I'm using `"commandLine"` rather than "source"`. When it was broken, it would take a little while to list Ubuntu, and then a bit longer to complete the command. Now it's instantaneous.

**Comment by DuncanSimon** [comment]
Also, erm, now if I comment out the `commandLine` option and uncomment `source`, it works...

**Comment by DuncanSimon** [comment]
It's like running it using `commandLine` has made it remember about WSL. Though I suspect this fix won't last?

**Comment by DuncanSimon** [comment]
When it was broken, it would also take some time to launch and close down Terminal. Especially closing down - it would quit the UI but the application would stay 'active' in the taskbar for a little while.

**Comment by DHowett** [comment]
For a little bit of backstory... Terminal queries which WSL distributions exist every time it's launched, by running `wsl -l`. That might seem strange, but it's based on the official guidance from the WSL team. Now, sometimes `wsl` fails to return anything in time. That used to cause Terminal to hang indefinitely on startup!

I reached out to the dev lead who owns some of the WSL usermode experience, and he suggested that two seconds is "long enough" to give WSL to respond. Pursuant to that, we added a timeout: if WSL doesn't respond within 2 seconds, Terminal will move on as though WSL is wedged, stalled or stopped. Our launch issues went away overnight!

It seems like you're one of the suffering few that have lingering WSL issues. I might have to bounce you over to the WSL repository for this one, if only because they'll know best how to handle an issue like this. 😕

**Comment by DHowett** [comment]
If you'd like to make startup fully deterministic and move back to manual control for WSL, here's what you can do.

1. Add `"disabledProfileSources": [ "Windows.Terminal.Wsl" ]` to the root node of your settings file
2. Get rid of the `source` line from your WSL profile
3. Add `"commandline": "wsl -d Ubuntu-18.04"`
4. Add `"icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png"` to get the Tux icon back

**Comment by DHowett** [comment]
Note that doing this will disable all WSL distribution autodetection!

**Comment by DuncanSimon** [comment]
Interesting! Well, for my circumstances the fact that I can use the `"commandLine"` option as a permanent fix is fine; I'm not worried about auto-detecting additional WSL distributions. I suppose any number of things could be causing WSL to be a bit slow? Whatever's happening is somewhat inconsistent as I've restarted my machine in the past few hours, which has always caused it to break in the past, and now it's fine. The only thing in the chain of events I've done differently is temporarily removing `"source"` and adding `"commandLine": "wsl -d Ubuntu-18.04"`, which brought recognition of the default profile back, and then removing `"commandLine"` and putting `"source"` back in.

Regardless, I'm fine with the proposed solution and don't personally need further investigation (although I am personally curious!). Thanks for your help, that's some great detective work.

And of course getting Tux back is the most important thing ;)

**Comment by DHowett** [comment]
Much appreciated. Thanks for debugging with me! :smile:

**Comment by mikesigs** [comment]
I just had this problem today. Seems like Windows Terminal uses a sort of well-known GUID value for the WSL profile (it also does for PowerShell.Core). If you have custom profile using `"source": "Windows.Terminal.Wsl"` and the guid doesn't match the expected value (for me it's `"{2c4de342-38b7-51cf-b940-2309a097f518}"`) then you get this error. In fact, if you don't use this guid value in your custom profile, Terminal seems to add the "missing" profile automatically, and then you end up with two profiles using the same `source` but with different `guid` values.

**Comment by DHowett** [comment]
If you have a profile with a `source` _that the source doesn't know about_, it will be ignored. The GUID is the only way it can know. :smile:

If you add a custom profile with a `source`, it's not likely to work unless that profile was actually generated by that source.

**Comment by remarcbalisi** [comment]
1. Restart
2. Open the original ubuntu terminal. (The one that you downloaded from microsoft store
3. Wait for the Welcome login to be finished (This message is shown once a day. To disable it please create the
/home/<your_username>/.hushlogin file.)
4. Close it, and go back to your windows terminal, it should work fine now.

**Comment by Kaarel** [comment]
Happened to me (seemingly) after updating Docker for Windows.

Haven't had any issues with WSL2 for months. I updated Docker for Windows from 2.4.0 to 2.5.0 as prompted by the tool recently. Had no issues with updating Docker for Windows in the past. This time too everything continued to work at first. But today the WSL option had disappeared from WT dropdown selection. `wsl.exe` was not responding at all. Docker for Windows too would get stuck in its Starting stage.

What fixed it for me:
1. Run `optionalfeatures.exe` as admin
2. Unselect Windows Subsystem for Linux
3. Restart
4. Run `Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")` as admin
5. Restart
6. Everything back to normal

**Comment by lemonez** [comment]
@Kaarel so glad you mentioned the Docker update. Same thing happened for me and I never would have connected the dots. Your solution fixed it, thank you!

**Comment by Stripy42** [comment]
I think I've solved it, ish.

It seems that in a new terminal install there is something wrong with the defaultProfile line. On two completely different computers I had the same issue. Copying the guid value always ended with the same error as you, nothing to do with Ubuntu by the way, I'm using OpenSUSE.

But copy and paste all of it, quote makes, comma, new line, etc. And it now takes it.
I think the default settings.json seems to be corrupt or gets corrupt in some unnoticeable way, like uses the wrong quote symbol or something.

**Comment by lmatter** [comment]
Just upgraded to 20H2 (OS Build 19042.789) and started getting this problem.  Fortunately I don't need wsl autodetection, but just wanted to mention this still happens,.

**Comment by d-mankowski-samsung** [comment]
I changed my default shell from Bash to ZSH on Ubuntu 20.04:

```
PS C:\Users\d.mankowski> wsl -l -v --all
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
```

And after restarting OS, Windows Terminal prints `Could not find your default profile in your list of profiles - using the first profile. Check to make sure the "defaultProfile" matches the GUID of one of your profiles` even though the file has not changed at all.

Here is the weird part: after commenting out `"source": "Windows.Terminal.Wsl",` the problem is gone and everything works as expected (Windows Terminal launches ZSH on Ubuntu). I also changed `guid` to one showed by `uuidgen` command.

```
            {
                "guid": "{f9b0ce25-0fd1-4d9b-91c0-6258bf4f08d1}",
                "hidden": false,
                "name": "Ubuntu WSL2",
                // "source": "Windows.Terminal.Wsl",
                "startingDirectory": "//wsl$/Ubuntu-20.04/home/dmankowski",
                "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
                "historySize": 9001,
                "snapOnInput": true,
                "cursorColor": "#FFFFFF",
                "cursorShape": "bar",
                "commandline": "wsl ~",
                "fontFace": "Consolas",
                "fontSize": 12,
                "acrylicOpacity": 1,
                "useAcrylic": true,
                "closeOnExit": false,
                "padding": "0, 0, 0, 0"
            },
```

**Comment by ShenhanQian** [comment]
I encountered the same problem after installing the pre-release version along with the standard version that I have used for a long time. It seems that the pre-release one accidentally corrupted the setting file (but I didn't notice anything weird when I was checking the setting.json).

Here is my solution:
1. Exit the terminal.
2. Delete the setting.json file
3. Relaunch the terminal to let it generate a fresh new setting.json.

Then, I get my WSL profile back.

**Comment by DHowett** [comment]
Curious. The preview and stable versions do not interact.

**Comment by ShenhanQian** [comment]
Now, I have uninstalled the preview version. But when I tried to set the default profile to WSL, the problem occurs again. I have to re-install the stable version to see my WSL again.

I'm not aware of the internal mechanism and this might be misleading, but I began encountering this problem after installing the preview version.

**Comment by gliss** [comment]
Using the Preview version this has happen to me tonight after an update to docker today. Using @Kaarel fix of removing WSL work.

**Comment by aziraphale** [comment]
I just had Ubuntu disappear from my WT profiles drop-down after installing Docker Desktop (v3.2.2; fresh install, not upgrade), logging out, and logging back in (as the Docker Desktop installer requests).

I have WT configured to start on login (`"startOnUserLogin":  true`), so maybe the freshly-installed Docker, in the midst of all the other Windows startup/logon tasks, lagged WSL to the point that it didn't respond in time to WT's initial `wsl -l` request (as per @DHowett's [very useful comment above](https://github.com/microsoft/terminal/issues/6946#issuecomment-659613005))?
This PC is running an Intel Core i5-2500 from almost 10 years ago, so it wouldn't take much to slow it down :)

I saw [the comment asking if `wsl -l` is slow](https://github.com/microsoft/terminal/issues/6946#issuecomment-659579260), and for me *it wasn't slow at all* (by the time I tried running that), but I found that *just adding a comment* to my `settings.json` was enough to get the WSL distro to appear in the profiles drop-down again!

Presumably the `settings.json` file modification, despite not changing the actual JSON data, caused WT to reload its settings and re-request the list of distros from WSL, and this time WSL responded in time because it wasn't competing with whatever else was running at login?

I don't know how practical it would be for WT to just *try again later* if WSL fails to respond in time to the initial `wsl -l` request?

Either way, "changing anything (even a comment) in `settings.json`, and saving it" might at least help some people recover their WSL profiles in WT! :)
(I don't yet know if I'm going to be losing my WSL profiles *every* time I log in. I'm hoping this was just a one-off caused by the fresh Docker install. We'll see!)

- Windows Terminal 1.6.10571.0
- Windows 10 20H2 19042.867
- Ubuntu 20.04.2

**Comment by Grinnz** [comment]
Just started getting this issue, I have not messed with my settings at all, but I get this message and my Debian install is missing from the dropdown randomly. It started working again and then stopped again. Trying to launch the Debian shell directly on another comment's suggestions, it just hangs forever. I am still on Windows 10 2004.

**Comment by DHowett** [comment]
> Trying to launch the Debian shell directly on another comment's suggestions, it just hangs forever. I am still on Windows 10 2004.

This sounds like a very good thing to report [on the WSL repository](https://github.com/microsoft/wsl)!

**Comment by stfuanu** [comment]
> Just started getting this issue, I have not messed with my settings at all, but I get this message and my Debian install is missing from the dropdown randomly. It started working again and then stopped again. Trying to launch the Debian shell directly on another comment's suggestions, it just hangs forever. I am still on Windows 10 2004.

same , my default ubuntu install is just missing , Also downloaded ubuntu shell isn't responding , hang forever . Only "unexpected" thing I can think of is that I closed all 4 opened tabs in one go few hours ago , maybe that , idk .

**Comment by pavankalyannv** [comment]
> I changed my default shell from Bash to ZSH on Ubuntu 20.04:
> 
> ```
> PS C:\Users\d.mankowski> wsl -l -v --all
>   NAME                   STATE           VERSION
> * Ubuntu-20.04           Running         2
> ```
> 
> And after restarting OS, Windows Terminal prints `Could not find your default profile in your list of profiles - using the first profile. Check to make sure the "defaultProfile" matches the GUID of one of your profiles` even though the settings file has not been changed at all.
> 
> Here is the weird part: after commenting out `"source": "Windows.Terminal.Wsl",` the problem is gone and everything works as expected (Windows Terminal launches ZSH on Ubuntu). I also changed `guid` to one showed by `uuidgen` command.
> 
> ```
>             {
>                 "guid": "{f9b0ce25-0fd1-4d9b-91c0-6258bf4f08d1}",
>                 "hidden": false,
>                 "name": "Ubuntu WSL2",
>                 // "source": "Windows.Terminal.Wsl",
>                 "startingDirectory": "//wsl$/Ubuntu-20.04/home/dmankowski",
>                 "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
>                 "historySize": 9001,
>                 "snapOnInput": true,
>                 "cursorColor": "#FFFFFF",
>                 "cursorShape": "bar",
>                 "commandline": "wsl ~",
>                 "fontFace": "Consolas",
>                 "fontSize": 12,
>                 "acrylicOpacity": 1,
>                 "useAcrylic": true,
>                 "closeOnExit": false,
>                 "padding": "0, 0, 0, 0"
>             },
> ```

I didn't have that source

**Comment by zabbidou** [comment]
This also happened to me. I don't think I did any update at all, between when it worked and now.

I started the default terminal "Ubuntu 20.04 LTS", said the machine was not responding. `wsl -l` in PowerShell responded instantly. 

I typed just `wsl` in PowerShell, it switched over to Ubuntu and restarted Windows Terminal. Now it works as expected

**Comment by abhineet-space** [comment]
I have been facing same problem but i made a small changes in setting of default terminal after which the same dialogue box doesn't appear.
Go to Settings -> Privacy & Security -> For Developers 
Go to Terminal Section
Change the default terminal host From ''Windows Terminal'' to ''Windows Console Host''.

**Comment by theAkito** [comment]
Wow, so I found a non-painful way to solve this. No reboot required, no fiddling around, no scratching heads.

1. Go to Windows Terminal's Settings.
2. On the left, there is a list of settings icons.
3. Scroll down, until you see each distribution.
4. Click on the Plus, which is the very last entry of the list.
5. You will have the option to add, duplicate or modify one of the profiles.
6. This is the only place, that even lists the profile, that is not showing up anywhere, else.
7. Now, duplicate the profile entry, which is not working for you.
8. Reload `settings.json` in a text editor.
9. Edit the new profile entry.
10. Everything you set up now with that automatically added (duplicated) profile works now.

**Comment by craiglandis** [comment]
Should it help anyone else, I randomly hit this too where it "Could not find your default profile".

I delete the "source" line from this profile I had set as default, problem went away.

```
"commandline": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe -NoLogo",
"guid": "{a3a2e83a-884a-5379-baa8-16f193a13b21}",
"hidden": false,
"icon": "ms-appx:///ProfileIcons/pwsh-preview.png",
"name": "PowerShell Preview",
"source": "Windows.Terminal.PowershellCore"
```

**Comment by The-Monkey-King** [comment]
>     7. Now, duplicate the profile entry, which is not working for you.
> 
>     8. Reload `settings.json` in a text editor.
> 
>     9. Edit the new profile entry.

This works; I can confirm. (I was missing my Debian profile after installing and even rebooting the PC.)

Additionally, you can just select "Settings" and then click on your duplicated Linux entry. (Mine said, "Debian (Copy)")  This brings up the settings profile for your Linux entry. All I had to do was edit the name, everything else looked good. Then just save your settings and you are good to go.
