### ISSUE TITLE
_compareCommandNames should use locale-aware string comparisons

### ISSUE THREAD

**Issue by jtippet** [microsoft/terminal#6953]
[_compareCommandNames ](https://github.com/microsoft/terminal/blob/934ad98786e33407e5549c36e2288601a3a083d8/src/cascadia/TerminalApp/CommandPalette.cpp#L253)operates on strings that are presented to the end-user, so it should sort like a human, not by codepoint.  I'm not sure whether this project prefers `CompareStringEx` or `lstrcmp` or some CRT routine.

**Comment by DHowett** [comment]
If there's some STL wstring locale-sensitive compare, I'd index towards that one. Thanks for pointing this out!

**Comment by Don-Vito** [comment]
@DHowett - is something like this STL enough?

```
static bool _compareCommandNames(const Command& lhs, const Command& rhs)
{
        const auto& f = std::use_facet<std::collate<wchar_t>>(std::locale());
        const auto lhsName = lhs.Name();
        const auto rhsName = rhs.Name();
        return f.compare(lhsName.data(), lhsName.data() + lhsName.size(), rhsName.data(), rhsName.data() + rhsName.size()) < 0;            
}
```
I am just confused what locale should we use.. just written commands in 3 languages and now wondering what should happen 😄

**Comment by PankajBhojwani** [comment]
Based on what I see [here](https://www.oreilly.com/library/view/c-cookbook/0596007612/ch13s06.html), @Don-Vito 's way seems correct

**Comment by Don-Vito** [comment]
@PankajBhojwani - I can absolutely create a PR, but I am not sure what locale should be used. Is std::locale() good enough?

**Comment by PankajBhojwani** [comment]
I think `std::locale("")` obtains the native locale ([source](https://stdcxx.apache.org/doc/stdlibug/24-3.html)), so that might be what we want actually. Will look into it more and let you know!

**Comment by PankajBhojwani** [comment]
@Don-Vito at this point I want to say it probably is a fine implementation for now, and to go ahead and make the PR for it if you'd like! We can handle potential issues in post

**Comment by Don-Vito** [comment]
@PankajBhojwani - great! I am creating one.

**Comment by Don-Vito** [comment]
@PankajBhojwani - made it work by explicitly invoking winapi's GetUserDefaultLocaleName. Still need to cleanup the code but please take a look.

**Comment by zadjii-msft** [comment]
After some additional thought, we're going to try and solve this with #7039 instead. Thanks for all the investigation everyone!
