### ISSUE TITLE
Automatic tab creation for remote GNU screen session

### ISSUE THREAD

**Issue by bugeaud** [microsoft/terminal#6955]
# Description of the new feature/enhancement

GNU screen command is a quite versatile tool that enable admin to get a workspace with multiple text "screen" opened on a machine. It is widely used in conjunction with ssh.

I am requesting that creation of screen tab could result in creation of an actual real wt tab.

Doing so, would avoid people to mess with the screen commands to get the right screen tab required.

The name of such a synthetic tab created will be fetched from the screen session itself.

# Proposed technical implementation details (optional)

Detecting a screen process is running (tracking escaping), the terminal will try to interract with the process to list the tabs (wsl or any ssh session). If it fail, this might not be a screen session terminal. If it succeed, it will create a terminal tab for each and every terminal screen. Pointing to any of the synthetic thus created would switch the active tab of the screen tab by sending the tab switching command to the screen session.

**Comment by DHowett** [comment]
So, I know tmux has a built-in control protocol for letting a Terminal take ownership of its tabs and panes.

Does screen have the same thing?

**Comment by zadjii-msft** [comment]
See also #3656, #5321
