### ISSUE TITLE
Terminal for Windows Server 2019 on ARM64

### ISSUE THREAD

**Issue by brunoborges** [microsoft/terminal#6956]
I'm running Windows Server 2019 on ARM.
I don't have the Windows Store, and the binary available on GitHub does not work at all.
The Windows Store says it works on Windows ARM.

Where can I find the installer for download?

**Comment by DHowett** [comment]
Server 2019 is not new enough; you must be running Windows 10.0.18362 or greater, regardless of whether it's Server or Desktop.

**Comment by XBZJ-QEMU** [comment]
Can you share the installation disk of Windows Server 2019 arm64？
