### ISSUE TITLE
German language instead of Polish

### ISSUE THREAD

**Issue by wolkonowski** [microsoft/terminal#6957]
# Environment

Windows build number: Version 10.0.18363.959
Windows Terminal version (if applicable): 1.0.1811.0
Region: Poland
Windows language: Polish

# Steps to reproduce

Right click on title bar or left click on arrow near "new card" or hover on "minimize", "maximize", "close" buttons.

# Expected behavior

All text and labels should be in Polish or English.

# Actual behavior

All text and labels are in German. (e.g. "Eingabeaufforderung" instead of "Command prompt" or "Wiersz polecenia")

![titlebar](https://user-images.githubusercontent.com/43011989/87734174-28376500-c7d2-11ea-95ac-cb5a061c46e8.png)
![context](https://user-images.githubusercontent.com/43011989/87734191-371e1780-c7d2-11ea-9b2a-2d78999f14a6.png)

**Comment by DHowett** [comment]
Can you share a screenshot of the "preferred languages" list from the system settings? The order of that list dictates the languages _all modern applications_ (specifically: not the OS!) use.

**Comment by wolkonowski** [comment]
Oh, that was the point. Never mind. Thanks for your answer
