### ISSUE TITLE
Prevent multiple instance of windows terminal

### ISSUE THREAD

**Issue by anoop1005** [microsoft/terminal#6959]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.900]
Windows Terminal version (if applicable): Version: 1.0.1811.0

Any other software?
```

# Steps to reproduce

1. Click start->run->wt.exe
2. Every time a new instance of windows terminal is launched instead of opening in the existing instance of the application


# Expected behavior

Only one instance of windows terminal with a new tab should be opened instance of new windows terminal application

# Actual behavior

Always new instance of windows terminal is launched

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2227 for more discussion.

/dup #2227
