### ISSUE TITLE
Reopen closed tab 

### ISSUE THREAD

**Issue by JRC86** [microsoft/terminal#6960]
No big deal, but a nice feature for those of us who are a bit clumsy!
I accidentally closed a tab.  I would like to reopen it. 

Some sort of temporary tab/pane-history, that is cleared when terminal shuts down.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #960  for more discussion.

/dup #960
