### ISSUE TITLE
Adding a list of profiles to Taskbar icon context menu

### ISSUE THREAD

**Issue by psisis** [microsoft/terminal#6964]
# Description of the new feature/enhancement

Icons on the Windows Taskbar often include key features in its right-click context menu, for example Windows Explorer shows you pinned and frequent folders. If Windows Terminal had the option to choose profiles from the context menu, without having to launch the app first, it would help the working environment very much.

![WinTerm](https://user-images.githubusercontent.com/58538286/87812198-18fef880-c860-11ea-9fca-b37d2d9e10be.png)

# Proposed technical implementation details (optional)

**Comment by psisis** [comment]
Oh, sorry for bothering you then. Seems like its heavily requested

**Comment by DHowett** [comment]
That's no problem; it's not a bother! :smile:
