### ISSUE TITLE
System Environment Variables Not Updated

### ISSUE THREAD

**Issue by TheBull963** [microsoft/terminal#6968]
# Environment

```none
Windows build number: Version 10.0.19041.330
Windows Terminal version (if applicable): 1.1.1812.0

Any other software? n/a
```

# Steps to reproduce

Step 1: Modify your system Environment Variables through sysdm.cpl (i.e. update the Path variable)
Step 2: Open a new tab within Terminals, new Path variable is not reflected
Step 3: Test outside of Terminals or launch new instance of Terminals, path variables are properly reflected.

# Expected behavior

Expected behavior is for the path variables to be updated within a new tab.

# Actual behavior

Path variables are not being updated, would need to close Terminals completely and relaunch.

**Comment by j4james** [comment]
I think this is probably a duplicate of #1125.

**Comment by zadjii-msft** [comment]
It sure is!

/dup #1125
