### ISSUE TITLE
Losing the settings when switching to another language. 

### ISSUE THREAD

**Issue by ms2052001** [microsoft/terminal#6971]
# Environment

```none
Windows build number: 10.0.18362.959
Windows Terminal version: 1.0.1811.0
```

# Steps to reproduce

I have English and Arabic languages installed with win10 so that I can type in either of them. The main language of the win10 (for menus, settings, apps, ...) is English.
*Open the terminal when language is set to Arabic*, by switching using (win_key + space_bar) or (alt+shift).

# Expected behavior

Find the same settings That I have configured, before by clicking (ctrl+,).

# Actual behavior

When I open this terminal while the typing language is Arabic, I lose the settings I have configured, the profiles schemes, etc.

**Comment by DHowett** [comment]
Thanks for reporting this, and sorry to take so long to get to it. I switch languages pretty often on my main machine, and I have not been able to reproduce this. It looks like you're referring to the _input language_?

Do you mean that the settings you have configured go back to defaults?
Or do you mean that when you use <kbd>Ctrl+,</kbd> you can no longer get to those settings?
