### ISSUE TITLE
Unable to open at current working Folder using "wt" 

### ISSUE THREAD

**Issue by palashjain2801** [microsoft/terminal#6972]
OS Used: Windows 10

Default Terminal is Powershell 7 
When I try to open Windows Terminal using "wt". It opens at the default folder setting. 

Can anyone know how to fix this issue

**Comment by j4james** [comment]
You need to use `wt -d .` to have it start in the current folder.

**Comment by palashjain2801** [comment]
Thank you for your response.

"wt -d . " works.
I also figured out that if you use

![image](https://user-images.githubusercontent.com/15762905/87886903-27771c80-c9e6-11ea-9d62-e8d6b01f8635.png)

at defaults section, you can only use "wt" command and it open windows terminal at the working folder

**Comment by anil-shrestha** [comment]
I think this should be default behavior similar to PS or cmd
