### ISSUE TITLE
Extremely lower performance when displaying too many box-shading glyphs

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/terminal#6974]
Environment

```none
Windows build number: 19619
Windows Terminal version (if applicable): 1.0.1811.0

Any other software? No
```

# Steps to reproduce
1. Use ``WriteConsoleOutputW`` function to fill console with block characters and random foreground colors. 

# Expected behavior
Smooth and high performance

# Actual behavior
1. The new windows terminal performs very bad (same with powershell or cmd), only refreshing at a few fps. While the old terminal can easily get to a few hundred.
2. And selecting the filled area after that is very laggy in new windows terminal, but it's very smooth in old windows console. See my gifs below.
![new_terminal](https://user-images.githubusercontent.com/42881734/87873051-b9017280-c983-11ea-853e-4dc5f6799e9a.gif)
![old_terminal](https://user-images.githubusercontent.com/42881734/87873052-b99a0900-c983-11ea-9e2a-4c5f95eb3a90.gif)

**Comment by zadjii-msft** [comment]
Huh, that's bizarre. 

![select-rgb](https://user-images.githubusercontent.com/18356694/87937282-09e39a80-ca5a-11ea-94a2-227fdc78aa96.gif)


Maybe there's something odd about your hardware that's causing this. The Terminal and the vintage console use different rendering stacks, so it's possible that the newer DX features the Terminal is using don't work as nicely on your machine. 

* Do you possibly have a gsync monitor / graphics card?
* Does setting [`experimental.rendering.forceFullRepaint`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#rendering-settings) or [`experimental.rendering.software`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#software-rendering) help by any chance?

**Comment by HO-COOH** [comment]
@zadjii-msft 
I am using an AMD gpu and the latest stable driver and FreeSync is not enabled. 
Setting ``experimental.rendering.forceFullRepaint`` to ``false`` and ``experimental.rendering.software`` to ``true`` I get a slight smoothness improvement, but significantly higher CPU usage, still nowhere as close to the old console.
I noticed this character specifically causes the slow down
░░░ <- This is the character, which is a ``wchar_t``, code ``0x2592``

**Comment by HO-COOH** [comment]
Yes, can confirm. If you can compile this C++ program under windows, you will see the huge difference
```cpp
#include <iostream>
int main()
{
    char c[] = "▒";
    for (int i = 0; i < 5000; ++i)
        std::cout << c;
}```
![vs](https://user-images.githubusercontent.com/42881734/87947689-4f5b9400-ca69-11ea-8338-ac0e41e9e0e9.gif)

**Comment by DHowett** [comment]
This is probably because of the separate rendering pass for box drawing glyphs. @miniksa might be interested in the pathological test case.

**Comment by miniksa** [comment]
> This is probably because of the separate rendering pass for box drawing glyphs. @miniksa might be interested in the pathological test case.

Man, I just can't make everyone happy, now can I? :P

There's probably something I can do here to not recalc every scale or something. I'll dig.

**Comment by schorrm** [comment]
@miniksa could this be related to GlyphRun splitting on scale issues?

**Comment by schorrm** [comment]
I don't think the scaling is breaking this. It seems to show up as just the one GlyphRun.

**Comment by magiblot** [comment]
This makes certain text-based applications nearly unusable:

https://user-images.githubusercontent.com/20713561/119904815-4241e800-bf4b-11eb-8762-2945e60f06ee.mp4

That separate rendering pass for box-drawing glyphs @DHowett mentioned, can it be disabled? I don't know if it's related to this, but in my opinion box-drawing characters look notably uglier in Terminal than in Conhost (for example, the background dot grid in the video above).

**Comment by lhecker** [comment]
If anyone would like to do so, please feel free to try out the new rendering engine we just released today:
https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-13-release/#new-rendering-engine

Unfortunately we made a mistake during packaging, due to which this version was released with English translations only, but I expect this issue to be solved soon.

In either case: While we haven't specifically tested the new renderer for proper box character drawing yet, it's performance is inherently unaffected by the kind of content you're drawing. As such box character drawing backgrounds now look like this:

https://user-images.githubusercontent.com/2256941/152468973-f554c8c5-5ca0-4953-93e0-db15142fe59d.mp4

Unless anything unexpected comes up, I expect this engine to be the default in the future.

**Comment by miniksa** [comment]
FWIW #12375 will bring the languages back and should be deployed early next week. It just took until EOD Friday to figure out what to do... and we're not shipping anything on a Friday.
