### ISSUE TITLE
Per Tab, Admin Mode

### ISSUE THREAD

**Issue by ParkHost** [microsoft/terminal#6975]
- Decide per tab if I want to open it in Administrator mode (Run as Administrator)
- Default setting 'Open as Administrator'

**Comment by korki43** [comment]
Possible dublicate of #1032. Also look here: #632

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5000 for more discussion.

/dup #1032 #632 #5000
