### ISSUE TITLE
Can not install via PS: Deployment failed with HRESULT: 0x80073CFD

### ISSUE THREAD

**Issue by ckgio99** [microsoft/terminal#6977]
Please help me. I'm using Win 10 Enter x64

PS C:\Users\Admin\Downloads> add-appxpackage Microsoft.WindowsTerminal_1.0.1811.0_8wekyb3d8bbwe.msixbundle
add-appxpackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe because this package is not
compatible with the device. The package requires OS version 10.0.18362.0 or higher on the Windows.Mobile device
family. The device is currently running OS version 10.0.17763.1339.
NOTE: For additional information, look for [ActivityId] e9dcd8da-5e4a-0003-c0df-dce94a5ed601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID e9dcd8da-5e4a-0003-c0df-dce94a5ed601
At line:1 char:1
+ add-appxpackage Microsoft.WindowsTerminal_1.0.1811.0_8wekyb3d8bbwe.ms ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Admin\...bbwe.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\Admin\Downloads>

**Comment by DHowett** [comment]
> The package requires OS version 10.0.18362.0 or higher on the Windows.Mobile device
family. The device is currently running OS version 10.0.17763.1339.

The version of windows you are running is too old. Sorry.

**Comment by Sadi224** [comment]
Hello Good Morning:)

**Comment by ckgio99** [comment]
> Hello Good Morning:)

Hello, Good Afternoon :)

**Comment by Sadi224** [comment]
It's morning with us now, that's why I said good morning to you my friend.
