### ISSUE TITLE
Profile Drop Down - add an additional property for a divider within Profile Settings

### ISSUE THREAD

**Issue by jasonturner** [microsoft/terminal#6978]
# Description of the new feature/enhancement

Within Profile Settings -> Drop Down settings enable an additional property that can allow a user to add a menu divider within the terminal's drop down. This divider would also have a name as an optional Property.

This would allow the menu drop down to look like

```
------Prod------
profile 1
profile 2
-----Dev------
profile 3
profile 4
-------------- 
profile 5
profile 6
```
The last one is without the dividename set.

Why: When managing a lot of servers where you have set-up multiple profiles its handy to be able to seperate the menu into different groups of profile (for example, dev, pre-prod, prod) and means its easier to see which environment I'd be working on.

# Proposed technical implementation details (optional)
Within Profile Settings and the Settings "list"
```
"list":
        [	   
 {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
		"backgroundImageOpacity" : 0.1,
		"backgroundImageStretchMode": "uniform"
            },
             {
                "divide": true,
		"dividename" : "preprod"
	    },            
	    {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false,
		"backgroundImageOpacity" : 0.1,
		"backgroundImageStretchMode": "uniform"
            },   ......

```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
