### ISSUE TITLE
Add Terminal to Win+X menu

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/terminal#6980]
Hi, 

# Description of the new feature/enhancement

It would be great if, in the menu opened by Win+X, Powershell and Powershell (Admin) could be replaced with Windows Terminal and its "Admin" version.

Apologies if this is a duplicate, I searched and couldn't find this yet.

**Comment by KalleOlaviNiemitalo** [comment]
Similar issues have been marked as duplicates of <https://github.com/microsoft/terminal/issues/492>.

**Comment by patrikhuber** [comment]
Yes, nice find! I will close this as a duplicate of #492.
Since that issue is locked and I can't upvote it, I'll just ping @DHowett-MSFT here as an additional interested party ;)
