### ISSUE TITLE
Bugs "windows 10 new terminal can't type on it"

### ISSUE THREAD

**Issue by HeiderJeffer** [microsoft/terminal#6990]
Hello, 

![1](https://user-images.githubusercontent.com/23063237/88068280-499ca600-cb70-11ea-9146-a7fd324a3647.PNG)

**Comment by zadjii-msft** [comment]
@HeiderJeffer Could you take a look at #4448 and tell me if the workaround listed in that thread works for you?

**Comment by HeiderJeffer** [comment]
> @HeiderJeffer Could you take a look at #4448 and tell me if the workaround listed in that thread works for you?
Hi. I take a look at #4448  and It is not solve the Bugs.

**Comment by DHowett** [comment]
So, just to be sure, you tried the `InputServiceEnabled` workaround?

You seem to have deleted the bug template and we do not know what version of Windows or what version of Windows Terminal you are using.

**Comment by bigjimlefou** [comment]
InputServiceEnabled workaround disable keyboard in some other management windows...
