### ISSUE TITLE
Make Drakula theme a native theme for windows terminal

### ISSUE THREAD

**Issue by morallito** [microsoft/terminal#6995]
# Make Drakula theme a native theme for windows terminal
Make the drakula theme a native theme on the terminal. 100% of the devellopers on my team work in VScode using Drakula as a color scheme. When we go to the terminal, we usually use a similar color scheme. If it's a native theme it will be very usefoul!

P.S.: Like @cinnamon_msft says, the red-yellow scheme is very nice  ;-)

**Comment by zadjii-msft** [comment]
I think somewhere we're going to need to draw the line between schemes that we ship built-in vs ones that we don't. I'd like to really avoid another Solarized debacle. I'm open to the idea of adding Dark+ in #6176 since that's a well-defined scheme that's default for another first-party application, but maybe I'd be more wary for something like Drakula. Is there a specific proposal for the color values to use with this scheme? 

I think long-term, the plan is to have a "theme marketplace" which will make it easier for users to upload various schemes and make adding them to the Terminal as easy as clicking a button, so I'm reluctant to expand the defaults _too much_.

**Comment by morallito** [comment]
Like Dark, drakula is a well defined theme and provide packs to a lot of IDE's and OS. You can see this on they GitHub page [here](https://github.com/dracula).


The color table can be seen below. 



## Color Palette

Palette      | Hex       | RGB           | HSL             | ![Color Picker Boxes](https://draculatheme.com/static/img/color-boxes/eyedropper.png)
---          | ---       | ---           | ---             | ---
Background   | `#282a36` | `40 42 54`    | `231° 15% 18%`  | ![Background Color](https://draculatheme.com/static/img/color-boxes/background.png)
Current Line | `#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Current Line Color](https://draculatheme.com/static/img/color-boxes/current_line.png)
Selection    | `#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Selection Color](https://draculatheme.com/static/img/color-boxes/selection.png)
Foreground   | `#f8f8f2` | `248 248 242` | `60° 30% 96%`   | ![Foreground Color](https://draculatheme.com/static/img/color-boxes/foreground.png)
Comment      | `#6272a4` | `98 114 164`  | `225° 27% 51%`  | ![Comment Color](https://draculatheme.com/static/img/color-boxes/comment.png)
Cyan         | `#8be9fd` | `139 233 253` | `191° 97% 77%`  | ![Cyan Color](https://draculatheme.com/static/img/color-boxes/cyan.png)
Green        | `#50fa7b` | `80 250 123`  | `135° 94% 65%`  | ![Green Color](https://draculatheme.com/static/img/color-boxes/green.png)
Orange       | `#ffb86c` | `255 184 108` | `31° 100% 71%`  | ![Orange Color](https://draculatheme.com/static/img/color-boxes/orange.png)
Pink         | `#ff79c6` | `255 121 198` | `326° 100% 74%` | ![Pink Color](https://draculatheme.com/static/img/color-boxes/pink.png)
Purple       | `#bd93f9` | `189 147 249` | `265° 89% 78%`  | ![Purple Color](https://draculatheme.com/static/img/color-boxes/purple.png)
Red          | `#ff5555` | `255 85 85`   | `0° 100% 67%`   | ![Red Color](https://draculatheme.com/static/img/color-boxes/red.png)
Yellow       | `#f1fa8c` | `241 250 140` | `65° 92% 76%`   | ![Yellow Color](https://draculatheme.com/static/img/color-boxes/yellow.png)

For more details about how to apply these different colors to represent different code symbols, please see the [Dracula Specification](https://spec.draculatheme.com).

**Comment by j4james** [comment]
> I'm open to the idea of adding Dark+ in #6176 since that's a well-defined scheme

I don't think this Dracula theme is good, and wouldn't recommend adding it by default, but it's arguably less broken than Dark+. As I pointed out in #6176, the Dark+ bright white and dark white colors are identical, which is just asking for trouble. It's not as serious as having bright black the same as dark black, but it's still going to break a few things.

**Comment by zadjii-msft** [comment]
I'm inclined to agree. From [their docs](https://spec.draculatheme.com/#sec-ANSI)

name | normal color | bright color 
-- | -- | --
Black | `#21222C` | `#6272A4`
Red | `#FF5555` | `#FF6E6E`
Green | `#50FA7B` | `#69FF94`
Yellow | `#F1FA8C` | `#FFFFA5`
Blue | `#BD93F9` | `#D6ACFF`
Magenta | `#FF79C6` | `#FF92DF`
Cyan | `#8BE9FD` | `#A4FFFF`
White | `#F8F8F2` | `#FFFFFF`

<details>
<summary>raw table</summary>

name | color
-- | --
`AnsiBlack` | `#21222C`
`AnsiRed` | `#FF5555`
`AnsiGreen` | `#50FA7B`
`AnsiYellow` | `#F1FA8C`
`AnsiBlue` | `#BD93F9`
`AnsiMagenta` | `#FF79C6`
`AnsiCyan` | `#8BE9FD`
`AnsiWhite` | `#F8F8F2`
`AnsiBrightBlack` | `#6272A4`
`AnsiBrightRed` | `#FF6E6E`
`AnsiBrightGreen` | `#69FF94`
`AnsiBrightYellow` | `#FFFFA5`
`AnsiBrightBlue` | `#D6ACFF`
`AnsiBrightMagenta` | `#FF92DF`
`AnsiBrightCyan` | `#A4FFFF`
`AnsiBrightWhite` | `#FFFFFF`

</details>

which would be the following scheme:

```jsonc
{
    "name": "Dracula"
    "black": "#21222C",
    "red": "#FF5555",
    "green": "#50FA7B",
    "yellow": "#F1FA8C",
    "blue": "#BD93F9",
    "purple": "#FF79C6",
    "cyan": "#8BE9FD",
    "white": "#F8F8F2",
    "brightBlack": "#6272A4",
    "brightRed": "#FF6E6E",
    "brightGreen": "#69FF94",
    "brightYellow": "#FFFFA5",
    "brightBlue": "#D6ACFF",
    "brightPurple": "#FF92DF",
    "brightCyan": "#A4FFFF",
    "brightWhite": "#FFFFFF",
    
    // foreground? background?
}
```

**Comment by j4james** [comment]
You can see a WT-compatible version of the color scheme on their github page here:
https://github.com/dracula/windows-terminal/blob/master/dracula.json

It seems the foreground and background colors are just taken from the _Standard_ section in the docs.
https://spec.draculatheme.com/#sec-Standard

Note that they also have mini web pages for each terminal and app that they support, but the colors listed on the [Windows Terminal page](https://draculatheme.com/windows-terminal) are not correct (at least it doesn't match the linked github page or the spec).

**Comment by skyline75489** [comment]
> I think somewhere we're going to need to draw the line between schemes that we ship built-in vs ones that we don't.

I use Drakula for quite some time and despite the fact I want it to be built-in, I'll have to agree with @zadjii-msft . We should not have many built-in themes and let users have their own fun. I honestly do not want see another 200+ issues in the future complaining Drakula and Dark+ being bad in some way.

**Comment by zadjii-msft** [comment]
I think that's enough consensus on the issue. Thanks for the discussion all!
