### ISSUE TITLE
"Windows Terminal" app package cannot be debugged in default VS configuration

### ISSUE THREAD

**Issue by bkot88** [microsoft/Terminal#700]
If anyone can help me get started, I can't seem to get debugging to work in VS2019. I am able to build, run and deploy the app, however, any breakpoints I set don't work when I try to debug with F5 (I saw @miniksa on youtube debug, so I know it should work).

When I stop/terminate debugging I get the following:
![image](https://user-images.githubusercontent.com/19501248/57566969-e49adb80-7415-11e9-96c2-0fe8e56956d1.png)
Perhaps this is related?

* Windows build number:  10.0.18362.86
* VS 2019 16.0.3 (Community)

**Comment by DHowett-MSFT** [comment]
This problem _haunts_ us. The secret is something you'd never expect, and something that belongs in our getting started guide.

Go to the properties for the _CascadiaPackage_ project, choose Debug, and change the project type from "_Mixed (Managed and Native)_" to "_Native Only_".

**Comment by pavlkara1** [comment]
Can you explain why this happens in more detail than the Error thrown provides?

**Comment by DHowett-MSFT** [comment]
Sure. The “Windows app packaging” (`wapproj`) project type in the Visual Studio project system is a derivative of the C# project type `csproj`. Owing to that, VS assumes that by default any application launched from WAP projects will start up the CLR.

Since this one doesn’t, it can’t be debugged until we tell VS to give up on the CLR.

**Comment by krystian-mwebdev** [comment]
I was wondering, wouldn't be anyone be generous enough to host a prebuilt version??? Looking at others and myself there is a lot of struggle to actually get it working

**Comment by oising** [comment]
@krystian-mwebdev Wrong place to ask. Any links placed here will be immediately removed because there will be a non-trivial amount of people who will assume because it's on the official repo, it's a supported release.

**Comment by bkot88** [comment]
I am happy to update README to reflect this.

**Comment by bkot88** [comment]
On second thought, it looks like it is being addressed in #704.

**Comment by zadjii-msft** [comment]
I'm not sure this is actually in #704, @bkot88 feel free to make another pr

**Comment by TheCloudSaver** [comment]
I've not added any new info in my PR, just fixed typo's ;)

**Comment by bkot88** [comment]
It seems when debugging in "Native Only" mode, the app throws an exception when drop down is clicked (to open a new tab).

![image](https://user-images.githubusercontent.com/19501248/57591634-c8ae4b80-7575-11e9-881e-6b2f7ce89327.png)

This is in src/cascadia/WindowsTerminal/main.cpp.

**Comment by zadjii-msft** [comment]
@bkot88 That's known, but the cause is very unknown at this time. Could you open a second issue to track that particular bug?

**Comment by curtisgray** [comment]
> 
> 
> This problem _haunts_ us. The secret is something you'd never expect, and something that belongs in our getting started guide.
> 
> Go to the properties for the _CascadiaPackage_ project, choose Debug, and change the project type from "_Mixed (Managed and Native)_" to "_Native Only_".

The `CascadiaPackage` crashed Visual Studio when the `Properties` (right-click) menu is selected. To fix that select `x64` in the Platform dropdown.

![cascadiapackage-properties-fix](https://user-images.githubusercontent.com/48138103/78856594-2ef55580-79f5-11ea-9347-24135b854c3c.jpg)
