### ISSUE TITLE
Double-clicking on wrapped word selects whole line

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#7002]
`Version: 1.0.1811.0`
![image](https://user-images.githubusercontent.com/1041752/88171107-12390280-cc1f-11ea-8557-20b94bf128e5.png)

![image](https://user-images.githubusercontent.com/1041752/88171216-40b6dd80-cc1f-11ea-8364-12ad6796a555.png)

It would be good to select the whole word (including the wrapped part)

**Comment by DHowett** [comment]
Whoa, really? Does this still reproduce in 1.1 or 1.2? Where did you double-click? We've never seen this behavior before.

**Comment by vadimkantorov** [comment]
I double-clicked on the word without any specifics. I'll check 1.1 / 1.2. This is in SSH + screen if that matters

**Comment by vadimkantorov** [comment]
I mean, the bug here is that clicking on wrapped word does not ever select the wrapped word fully.

Clicking many times on any word would at some point select the full line...

**Comment by DHowett** [comment]
I mean, that's definitely a different bug than "double-clicking on wrapped word selects the whole line".
We already have one tracking "double-click selection _should select word-wrapped words_"  (#4009) :smile:

Just to be clear: you're only seeing the line-selection behavior when you click more than _twice_, right?

**Comment by vadimkantorov** [comment]
Yes, it happens when I click twice, and then very quickly one more time

**Comment by vadimkantorov** [comment]
But originally I wanted to report the issue in https://github.com/microsoft/terminal/issues/4009, unfortunately could not find it

**Comment by DHowett** [comment]
So, clicking quickly three times in the same place is what we’ve decided to call a triple-click; like most text editors, we will select the whole line on a triple-click.

For the core issue, /dup #4009. 😄
