### ISSUE TITLE
1.1.2021.0 is Released, but not available in the MS Store

### ISSUE THREAD

**Issue by IanKemp** [microsoft/terminal#7003]
I'm watching the Releases in this repo and got an email ~13 hours ago that v1.1.2021.0 has been released, which I assume means it's been pushed to the Microsoft Store. However, if I open the Store app on my PC, then go to "Downloads and updates" and click "Get updates", Windows Terminal is listed at version 1.0.1811.0 with no option to update.

Am I incorrect in assuming that a Release from this repo implies availability in the Store?

**Comment by Rob-Wal** [comment]
I received the email as well and looking forward to this upgrade. The MSI is not available for download here on github either.  There is also no release notes here yet.  They either found a bug or the email went out early.

**Comment by korki43** [comment]
v1.1.2021.0 and v1.2.2022.0 are no releases, but tags. These are just to mark specific timestamps in the code. maybe these tags will be the next releases, but they are not yet.

To get the preview versions of microsoft terminal, also make sure to download [the Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3) from the Microsoft store and not the regular Terminal.

_Correct me, if I have said something wrong._

**Comment by Rob-Wal** [comment]
> v1.1.2021.0 and v1.2.2022.0 are no releases, but tags. 
I understand that, but I received an email with release notes for v1.1.2021.0 from Dustin.  It rolls up the changes in the preview and more into the stable branch.  So yes, that email was probably sent prematurely or they found a bug and delayed it.

**Comment by Rob-Wal** [comment]
> v1.1.2021.0 and v1.2.2022.0 are no releases, but tags. These are just to mark specific timestamps in the code. maybe these tags will be the next releases, but they are not yet.
> 
> To get the preview versions of microsoft terminal, also make sure to download [the Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3) from the Microsoft store and not the regular Terminal.
> 
> _Correct me, if I have said something wrong._

I understand that, but I received an email with release notes for v1.1.2021.0 from Dustin.  It rolls up the changes in the preview and more into the stable branch.  So yes, that email was probably sent prematurely or they found a bug and delayed it.

**Comment by WSLUser** [comment]
@DHowett Can you republish the release if it was intended? This isn't the first time a release notification was sent but the Store wasn't updated. The github release page doesn't even have the msixbundle either for those who don't want to wait for the Store package to pickup (or can't use the Store).

**Comment by zadjii-msft** [comment]
I believe he's still drafting the official release notes. Your patience is appreciated, it is only 7am in Seattle after all ☺️ 

The Store does take some time to finish ingesting a release - sometimes up to 24 hours. So while it might not be available immediately on the Store, it is _on it's way_.

**Comment by DHowett** [comment]
The release was published to GitHub unintentionally and will be available at some future point.

**Comment by WSLUser** [comment]
https://dev.azure.com/ms/terminal/_build/results?buildId=95799&view=artifacts&type=publishedArtifacts provides an unsigned version of the release if anybody wants it. I would prefer to wait for a signed release.
