### ISSUE TITLE
Improvement: Match the Terminal frame and Tab color scheme to Edge

### ISSUE THREAD

**Issue by bonzibudd** [microsoft/terminal#7005]
# Description of the new feature/enhancement

-This enhancement would match the color scheme to the Chromium version of Edge, it would improve consistency between apps

-The app wouldn't be used differently, but it would look nicer and follow the fluent design language more closely. The current implementation has the tabs too dark and the background too light.
# Complete description
-I would like the color scheme for the Tab bar and frame of Windows Terminal to match Microsoft Edge in the light and dark theme. Additionally, the bottom corners of the tabs should be curved like Edge, and not be at a solid 90 degree angle as it is right now.

**Comment by zadjii-msft** [comment]
This might be a neat idea for a default theme once #3327 lands, but I don't think we're about to change the default colors before that. I could imagine a default theme with 

```jsonc
        {
            "name": "Edge",
            "window.applicationTheme": "system",
            "tab.background": "#whatever-color-edge-is",
            "tabRow.background": "accent",
        },
```

would get the same effect
