### ISSUE TITLE
Don't warn about multiline paste to editor

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#7006]
# Description of the new feature/enhancement

I want the <https://github.com/microsoft/terminal/issues/2349> warning when pasting multiline text to a shell, but not when pasting to an editor that won't execute the lines as commands.

# Proposed technical implementation details (optional)

Potential ways to detect such an editor:

* If the alternate screen buffer is active (regardless of whether it has been temporarily hidden by <https://github.com/microsoft/terminal/issues/6451>). However, this heuristic would be fooled by `less`, which does execute lines starting with `!` as commands.
* If bracketed paste mode (<https://github.com/microsoft/terminal/issues/395>) is active. That would first have to be implemented. [GNU Nano supports it.](<http://savannah.gnu.org/bugs/?40060> "bug #40060: [Request] implement bracketed paste mode, to suppress auto-indentation")
* If any of the [mouse tracking](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking) modes is active.

Whichever heuristic is used, there is a risk that the editor is killed and the modes are left active. Perhaps the configuration should have a separate opt-in for each heuristic.

**Comment by zadjii-msft** [comment]
Of those three options, the bracketed paste one is my favorite. Consider something like `tmux`, which is going to use the alt buffer and mouse tracking, but is also likely sitting at a shell prompt.

**Comment by vadimkantorov** [comment]
Stumbled on this. This is annoying when copy-pasting code into vim, since there is no way to suppress the message after first appearance.

**Comment by zadjii-msft** [comment]
I mean, there is [these settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#paste-warnings) so there's not _no_ way...

**Comment by vadimkantorov** [comment]
I meant no quick UI way, many apps would ask right away if one wants to suppress the message: "Do not show again" button kind of way

**Comment by UID1** [comment]
Agree on this issue. When copying and pasting into a running ipython console or a Scala REPL then this warning is merely a nuisance.  Those interactive enviroments know how to handle multi-line pastes.
