### ISSUE TITLE
Version 1.2.2022.0 deletes user's settings

### ISSUE THREAD

**Issue by garyo** [microsoft/terminal#7007]
# Environment

```none
Windows build number: 10.0.19041
Windows Terminal version (if applicable): 1.2.2022.0

Any other software?
```

# Steps to reproduce

Install vers 1.2.2022.0 from store, over previous version

# Expected behavior

It continues to use my settings (font, bindings etc.)

# Actual behavior

It replaces `settings.json` with a new auto-generated version, deleting all my customized settings. Bummer!

**Comment by DHowett** [comment]
What version were you on before?

**Comment by DHowett** [comment]
Just to be clear.

**1.2 is in the preview channel**. If you are coming from 1.0, 1.2 stores its settings in a completely different place so that it doesn't interfere with your existing installation. If you came from 1.0, you have two versions of Terminal installed side-by-side.

**Comment by garyo** [comment]
Seems I was on 1.0.1811.0, which stores its settings in `Microsoft.WindowsTerminal_8wekyb3d8bbwe`. So at least my settings are _somewhere_, whew. Thanks!
Would be nice if it would copy over anything the user customized from the old version, at least profiles.defaults and the user's default profile.

**Comment by DHowett** [comment]
That's being tracked over in #6855  :smile:

/dup #6855
