### ISSUE TITLE
How to remove "Open in Windows Terminal" from context menu?

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#7008]
Hi All

how to remove "Open in Windows Terminal" from context menu?

I was looking into Registry but could not find anything...

What is the implementation of that feature?

Thank you.

**Comment by DHowett** [comment]
It can't be removed right now. We're tracking a workitem to only show it when SHIFT is held down.

We're not going to add the ability to delete it entirely. Sorry.

/dup #6113

**Comment by vitaminj** [comment]
To remove this manually, open regedit, go to the folder `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked` (you may have to create the `Blocked` key) then add a string value on the right with the name `{9F156763-7844-4DC4-B2B1-901F640F5155}` and the value `WindowsTerminal`

**Comment by arturnowok** [comment]
> To remove this manually, open regedit, go to the folder `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked` (you may have to create the `Blocked` key) then add a string value on the right with the name `{9F156763-7844-4DC4-B2B1-901F640F5155}` and the value `WindowsTerminal`
> 
> Bookmark the folder if you're likely to want to come back and re-enable the menu item when they add the option to only show it on holding shift

Cool stuff man. Thank you.

**Comment by 4k3or3et** [comment]
> To remove this manually, open regedit, go to the folder `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked` (you may have to create the `Blocked` key) then add a string value on the right with the name `{9F156763-7844-4DC4-B2B1-901F640F5155}` and the value `WindowsTerminal`
> 
> Bookmark the folder if you're likely to want to come back and re-enable the menu item when they add the option to only show it on holding shift

Cool stuff. Thank you.

**Comment by Wosser1sProductions** [comment]
> To remove this manually, open regedit, go to the folder [...]

Nice, I already added my own shortcut on shift only, so this removed the duplicate.

**Comment by skaesdorf** [comment]
> It can't be removed right now. We're tracking a workitem to only show it when SHIFT is held down.
> 
> We're not going to add the ability to delete it entirely. Sorry.
> 
> /dup #6113

Hi, sorry to hear that, since this feature is simply not working when you choose wsl as the defualt profile in terminal. It will open the terminal, but the path is not mapped to the mounts in wsl. If you dont plan to add the ability to disable the context menu entry, you should at least make it work with wsl by default.

Cheers

**Comment by patricknelson** [comment]
I use this in combination with https://github.com/BroJenuel/Explorer-Context-Menu-Integration-for-windows-terminal to address issues with Windows Terminal not being able to properly retain the `CWD` when opening new tabs and panes (#8933).

**Comment by jayagami** [comment]
> I use this registry hack in combination with https://github.com/BroJenuel/Explorer-Context-Menu-Integration-for-windows-terminal to address issues with Windows Terminal not being able to properly retain the `CWD` when opening new tabs and panes (#8933).


I think this one is better:

https://github.com/lextm/windowsterminal-shell

![](https://github.com/lextm/windowsterminal-shell/blob/master/default.png)

**Comment by pundoo** [comment]
@vitaminj Unfortunately that doesn't work for 'Open in Windows Terminal Preview'. Any idea of the correct CLSID for that?

**Comment by vitaminj** [comment]
@pundoo it seems to be `{02DB545A-3E20-46DE-83A5-1329B1E88B6B}` for the preview version (you can use any string for the value but `WindowsTerminalPreview` is probably a good idea so that you remember what it was)

**Comment by pundoo** [comment]
@vitaminj Ahh.. its literally just there. I went over the source code atleast twice. How could I possibly overlook that.. smh

**Comment by ThisOneIsForPosting** [comment]
@vitaminj 
Thank you for finding that string!  Now **Windows Terminal Preview** no longer shows up in my Windows 11 context menu 👍

**Comment by itsmeshibintmz** [comment]
> To remove this manually, open Regedit, go to the folder `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked` (you may have to create the `Blocked` key) then add a string value on the right with the name `{9F156763-7844-4DC4-B2B1-901F640F5155}` and the value `WindowsTerminal` Then restart Explorer.
> 
> Bookmark the folder if you're likely to want to come back and re-enable the menu item when they add the option to only show it on holding shift

Thank you.

**Comment by musm** [comment]
> @pundoo it seems to be `{02DB545A-3E20-46DE-83A5-1329B1E88B6B}` for the preview version (you can use any string for the value but `WindowsTerminalPreview` is probably a good idea so that you remember what it was)

Thank you. How about how to remove it from the extended context menu on Windows 11, after you click "Show More Options"?

**Comment by itsmeshibintmz** [comment]
> > @pundoo it seems to be `{02DB545A-3E20-46DE-83A5-1329B1E88B6B}` for the preview version (you can use any string for the value but `WindowsTerminalPreview` is probably a good idea so that you remember what it was)
> 
> Thank you. How about how to remove it from the extended context menu on Windows 11, after you click "Show More Options"?

the same registry edit you can apply in Windows 11 too.

**Comment by nazihhawi** [comment]
> To remove this manually, open regedit, go to the folder `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked` (you may have to create the `Blocked` key) then add a string value on the right with the name `{9F156763-7844-4DC4-B2B1-901F640F5155}` and the value `WindowsTerminal` Then restart Explorer.
> 
> Bookmark the folder if you're likely to want to come back and re-enable the menu item when they add the option to only show it on holding shift

What would be the identifier for the Windows Terminal Preview version?
