### ISSUE TITLE
Really hard to resize via top margin when toggleFocusMode is enabled

### ISSUE THREAD

**Issue by iamsergio** [microsoft/terminal#7012]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version: 1.2.2022.0

```

# Steps to reproduce

Hide the terminal's title bar and tabs by enabling the new setting 'toggleFocusMode'.
For example, by adding `{ "command": "toggleFocusMode", "keys": "ctrl+shift+t" },` to your keybindings.

Once you've hidden the title bar, hover over the top window border with your mouse and resize it a bit.
Try resizing it a second time, it no longer works.

Resizing via left, bottom or right margins continue to work though.

# Expected behavior

Expected that resizing via the top frame/border still worked.

# Actual behavior

Not possible to resize vertically via top-border.

**Comment by WSLUser** [comment]
That's by design. Enable borderless mode for another app, most common in games and try doing it. Some may allow it but many will not. However you should be able to move the whole window if you're not in fullscreen mode.

**Comment by DHowett** [comment]
This is not by design, lol.

**Comment by WSLUser** [comment]
Really? I've seen many games where you couldn't. But you could move the window or toggle fullscreen on.

**Comment by DHowett** [comment]
If we're going to support resize on the bottom, left and right borders we should support it on the top too.

**Comment by zadjii-msft** [comment]
Oh derp, I mentioned this is #6804, but forgot to file an issue for it
> **KNOWN ISSUE**: Upon resizing the NCIW, the top frame margin disappears, making that border disappear entirely. 6356aaf has a bunch of WIP work for me trying to fix that, but I couldn't get it quite right.

**Comment by Don-Vito** [comment]
@zadjii-msft  - upon NCIW sizing we retrieve the height of the top border by:
```
int NonClientIslandWindow::_GetTopBorderHeight() const noexcept
{
    // No border when maximized, or when the titlebar is invisible (by being in
    // fullscreen or focus mode).
    if (_isMaximized || (!_IsTitlebarVisible()))
    {
        return 0;
    }

    return topBorderVisibleHeight;
}
```

I believe that 0 should be only in maximized state, while in other states where the title bar is not visible it should be 1, so we still have thin border to drag?

WDYT?

Creating a PR since it is a one liner :smile:
