### ISSUE TITLE
Feature Request: Allow background image to be pixel/fragment shader specified by me

### ISSUE THREAD

**Issue by mrange** [microsoft/terminal#7013]
# Description of the new feature/enhancement

Shadertoy.com has many amazing examples what one can do with what is called fragment/pixel shader. I would like to be able to download or implement my own pixel shaders and have that as a background in the terminal.

For exampel this one would be cool (making a bit darker to actually see the text) : https://www.shadertoy.com/view/3lyXDm

Configuring the feature be used using already existing background image but with support for shader file extensions?

```
"backgroundImage": "c:/myshader.ps"
```

```
"backgroundImage": "c:/myshader.glsl"
```

**Comment by WSLUser** [comment]
Sounds like a cool extension idea. Related: https://github.com/microsoft/terminal/pull/6242

**Comment by zadjii-msft** [comment]
Okay this is pretty slick not gonna lie.

I'd again accept this as a community contribution, probably in the same vein as the experimental retro effects, until we get extensions sorted out. 

See also #4000.
