### ISSUE TITLE
cursorShape and cursorColor ignored

### ISSUE THREAD

**Issue by mguthaus** [microsoft/terminal#7020]
# Environment

```none
Microsoft Windows [Version 10.0.20170.1000]
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce

Add following to settings:
    "cursorShape": "filledBox",
    "cursorColor": "#FF0000",

# Expected behavior

This should change the cursor to a red filled box. 

# Actual behavior

I closed the app and restarted for good measure, but it remains a white vertical bar. Other settings such as the colorScheme take effect properly.

**Comment by mguthaus** [comment]
I've confirmed that this also happens with a fresh install (and settings.json) using version Windows Terminal Preview
Version: 1.2.2022.0.

If it matters, I am using Ubuntu WSL as the terminal shell, but it also seems to not affect other shells.

**Comment by DHowett** [comment]
Wow, this is really unexpected.

Can you share your whole settings file? Even on a clean install, I get this:

![image](https://user-images.githubusercontent.com/189190/88237752-c42ef980-cc34-11ea-83c8-a9b2ab796327.png)

![image](https://user-images.githubusercontent.com/189190/88237759-c8f3ad80-cc34-11ea-843c-099d4fc48cfa.png)

![image](https://user-images.githubusercontent.com/189190/88237807-e58fe580-cc34-11ea-9c53-934171d79dfa.png)

![image](https://user-images.githubusercontent.com/189190/88237814-ea549980-cc34-11ea-8454-56475610d2e9.png)

**Comment by mguthaus** [comment]
Ah! I thought this was a global parameter and not a per profile parameter. User error.
