### ISSUE TITLE
https://aka.ms/terminal-profiles-schema still linking to v1 schema

### ISSUE THREAD

**Issue by tavrez** [microsoft/terminal#7021]
# Environment

```none
Windows build number: 18363.900
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
```

# Steps to reproduce

Go to https://aka.ms/terminal-profiles-schema 🤣

# Expected behavior

Redirect to https://raw.githubusercontent.com/microsoft/terminal/release-1.1/doc/cascadia/profiles.schema.json

# Actual behavior

Redirect to https://raw.githubusercontent.com/microsoft/terminal/release-1.0/doc/cascadia/profiles.schema.json

**Comment by DHowett** [comment]
@cinnamon-msft

**Comment by tavrez** [comment]
Please also add the $schema into defaults.json file aswell

**Comment by DHowett** [comment]
Thanks for reporting this. I've fixed it.

`defaults.json` isn't intended to be edited; since the schema is primarily for user-driven editing scenarios, there's not much value in adding the schema... right?
