### ISSUE TITLE
Open another profile in same directory

### ISSUE THREAD

**Issue by tavrez** [microsoft/terminal#7022]
# Description of the new feature/enhancement

Imagine I have a terminal open at some directory like c:\project\something
Now I want to open another terminal in this directory(wsl, or my custom added mingw terminal).
It would be good if I able to this by holding somthing and pressing that terminal profile hotkey(e.g instead of ctrl+shift+3 I go with ctrl+shift+alt+3 and new terminal startingDirectory is now same as where I am)
Little hard for wsl terminals I guess, but for the rest it can be helpful

**Comment by DHowett** [comment]
Thanks for the request! This is a /duplicate of #3158.
