### ISSUE TITLE
Using new SGR codes and resizing the terminal window after leads to incorrect rendering

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#7023]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.2.2022.0

Any other software? WSL Ubuntu
```

# Steps to reproduce

1.  `$ echo -e '\e[53mTEST\e[55m'`

2. Resize (maximize) the terminal window.

# Expected behavior

![image](https://user-images.githubusercontent.com/7956686/88236670-2e23bf00-cc86-11ea-846e-4c4131676ce8.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/7956686/88236686-3a0f8100-cc86-11ea-968f-ff455cd2e5a2.png)

**Comment by DHowett** [comment]
Thanks for the report!
This is another instance of #32 (holy wow, look at that low number!)

https://github.com/microsoft/terminal/issues/32#issuecomment-334814519

since we're sharing the buffer code with the console host, the same issue applies :smile:

/dup #32
