### ISSUE TITLE
Terminal keeps adding empty ubuntu option to menu 

### ISSUE THREAD

**Issue by AndyWDev** [microsoft/terminal#7026]
# Environment

Windows 10 2004

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
no

# Steps to reproduce

Install WSL 2, Ubuntu (latest version)

# Expected behavior

Single Ubuntu menu in dropdown for selecting shells

# Actual behavior

I get an Ubuntu menu that works (loads WSL 2 prompt) and a second menu 'Ubuntu 18.04' that throws the error - system cannot find the path specified.

In settings.json I can see an entry for it. If the setting is removed, the menu is updated, however, it seems to come back again the next time terminal is loaded.  18.04 was a previous version and no longer installed.

**Comment by DHowett** [comment]
So, you definitely still have an old WSL distribution registered named "Ubuntu-18.04".

Can you share the output of...

```
wsl -l -v
```

**Comment by AndyWDev** [comment]
> So, you definitely still have an old WSL distribution registered named "Ubuntu-18.04".
> 
> Can you share the output of...
> 
> ```
> wsl -l -v
> ```
Ubuntu-18.04    Stopped         1
Ubuntu              Stopped         2

There was registry entry for the 18.04 and the path it pointed to did not exist.  Removed the entry and the menu has gone.  I think this may have been a left over from WSL 1.
