### ISSUE TITLE
“Open In Windows Terminal” Only work in the first tab, other new tabs still start dirctory with default

### ISSUE THREAD

**Issue by shykai** [microsoft/terminal#7027]
# Environment

```none
Windows build number:  10.0.19041.0
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

1. RightClick Floder and choose "Open In Windows Terminal"

2. Click "NewTab" and create a new Tab "PowerShell"

# Expected behavior
![image](https://user-images.githubusercontent.com/393084/88251589-db75f180-ccdd-11ea-8b54-e952f811bcbc.png)
 The first Tab PowerShell starts with the right dirctory `D:\TestWT\OpenInWindowsTerminal`
 In this Terminal, any new Tabs should starts with the same Path `D:\TestWT\OpenInWindowsTerminal`

# Actual behavior

The New Tab starts with the defualt dirctory `C:\Windows\System32`.
![image](https://user-images.githubusercontent.com/393084/88251942-0f054b80-ccdf-11ea-8b06-326094308e2d.png)

# Else
I found the function "Open In Windows Terminal" works with the parmeter `-d`, and it only effects "defaultProfile" in settings.json.
Actually when new Profiles were created,they were only effected by the "wt.exe"'s start dirctory, like the pic below.
![image](https://user-images.githubusercontent.com/393084/88252432-b20a9500-cce0-11ea-9b9c-f92acd270dc6.png)

**Comment by DHowett** [comment]
Unfortunately, yes, new tabs will assert the default starting directory from their profiles. This is going to be helped by /dup #3158.
