### ISSUE TITLE
No line wrap at the bottom of the Terminal window when entering text in TCC

### ISSUE THREAD

**Issue by mgieseki** [microsoft/terminal#7028]
# Environment

```none
Windows build number: 10.0.18363.959
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
JPSoft TCC v26
```

# Steps to reproduce
* Run `tcc.exe` in Terminal
* Press Return multiple times until the prompt reaches the last line of the terminal window
* Enter any long text that exceeds the number of characters per line

# Expected behavior

The window content should be scrolled up one line and further characters appear on a new line at the bottom.

# Actual behavior

There's no line wrap. The characters that are supposed to go on a new line overwrite the characters at the beginning of the current line.

![tcc](https://user-images.githubusercontent.com/3620467/88261257-3ac80780-ccc6-11ea-8622-0f2b1c375d77.png)

**Comment by zadjii-msft** [comment]
For future reference: https://jpsoft.com/help/index.htm

**Comment by DHowett** [comment]
TCC exhibits this behavior in a standard console host window when it's at the bottom of the buffer as well. It is trivially reproduceable by printing 9000 lines of text and then attempting to write a command wider than the screen using TCC.

This is a bug in TCC; it should be taken up with the vendor.

**Comment by mgieseki** [comment]
Oh. Thank you for the investigation, and sorry for the noise.
