### ISSUE TITLE
Save Windows terminal window split status

### ISSUE THREAD

**Issue by danieleliberti** [microsoft/terminal#7029]
Function widely used on terminals such as iTerm and others of the kind to report the preferred working status.

**Comment by zadjii-msft** [comment]
There's not a lot of details to go off of in this issue, but it sounds a lot like either #961 or #756

**Comment by danieleliberti** [comment]
Perfect signaling #961 with saving the internal division status of each card.
THX for your work ,)

**Comment by zadjii-msft** [comment]
Awesome, thanks for following up!

/dup #961
