### ISSUE TITLE
Draw shadows around glyphs

### ISSUE THREAD

**Issue by fghzxm** [microsoft/terminal#703]
When the background opacity is low, text can become less readable when the Terminal window is atop another window that has a background color similar to the Terminal's foreground color...
![](https://i.imgur.com/AdbPk3Y.png)
... which makes acrylic less useful.  Neither is acrylic useful, however, if the background opacity is high enough so that things below the Terminal window cannot influence its visuals.

I suggest an option to draw background-colored shadows around the glyphs displayed on the Terminal.  This will make areas that contain text more resistive to color changes underneath, while empty areas remain the acrylic visuals.

**Comment by MarioLiebisch** [comment]
Sounds reasonable. I'd even think about making it configurable to use drop shadows and/or outlines.

**Comment by mdtauk** [comment]
Gradually fade in the outline as the opacity for the background decreases

**Comment by Chirishman** [comment]
Having it be manually settable also helps with certain background images.
