### ISSUE TITLE
Paste from clipboard history

### ISSUE THREAD

**Issue by bobvandevijver** [microsoft/terminal#7031]
# Description of the new feature/enhancement

We can use several configurable key strokes to paste anything inside the terminal, but the clipboard history (win + v) does not seem to have any effect at all. 

I am not sure what causes this, but I am sure I would love seeing support for it!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+win%2Bv+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #322 for more discussion.

I believe it _will_ work if you add <kbd>ctrl+v</kbd> as paste to the keybindings:

```json
{ "command": "paste", "keys": "ctrl+v" },
```

/dup #322 #4184 #3176 #6521 #6234 #4914
