### ISSUE TITLE
Add Run as Administrator Option for Profile

### ISSUE THREAD

**Issue by Agent24015** [microsoft/terminal#7033]
Hi, 

Can you please add an option to run as administrator when right clicking the profile from the drop-down menu

**Comment by WSLUser** [comment]
This is a dupe and is now in works. You could work around this by using the runas option on the commandline. Add `"commandline" : "runas .... someshell.exe"` to the profile you want.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Run+as+Administrator%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #632 and #1032 for more discussion.

/dup #632, #1032, #5000
