### ISSUE TITLE
Alt+Enter keybinding for copying selected filename to commandline in Midnight Commander (mc) doesn't work

### ISSUE THREAD

**Issue by niiiksh** [microsoft/terminal#7035]
Alt+Enter keybinding in mc supposed to copy selected file name to commandline but in Windows Terminal it does open full screen mode. I don't know how to workaround this because it is quite useful keybinding. Can I disable Alt+Enter full screen in Windows Terminal and leave only F11 key for full screen support?

**Comment by zadjii-msft** [comment]
Yep. Just add the following to your `keybindings`:

```json
{ "keys": "alt+enter", "command": "unbound" }
```

See also: [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings#unbind-keys)

**Comment by zadjii-msft** [comment]
@niiiksh What version are you using? That might be fixed in 1.1+

**Comment by niiiksh** [comment]
@zadjii-msft I'm using version 1.1.2021.0 currently, latest from Microsoft Store

**Comment by niiiksh** [comment]
Also when I hold _**Esc**_ and press _**Enter**_ for the second time it acts as _**Enter**_ but I expect it to work as _**Esc+Enter**_ in that case.

**Comment by jerzy-wachowiak** [comment]
As of Windows Terminal version 1.4, the keybindings array has been renamed to actions inside the settings.json file.
