### ISSUE TITLE
The WT window always appears behind the active Explorer window.

### ISSUE THREAD

**Issue by capedghost** [microsoft/terminal#7036]
After the latest update,there is an explorer context menu item appear:
![S20200723183339](https://user-images.githubusercontent.com/44280081/88278416-e8fa9e00-cd14-11ea-9add-55da4462dbc6.png)
Use it:
![S20200723183616](https://user-images.githubusercontent.com/44280081/88278552-265f2b80-cd15-11ea-9978-de6f04102353.png)
The WT window always appears behind the active Explorer window.
---
And please add a explorer background context menu item,maybe called "Windows Terminal here".
---
And, The color of the tabs is always black, I think it should be the same as the background.
![S20200723190329](https://user-images.githubusercontent.com/44280081/88279968-85be3b00-cd17-11ea-99b7-4630f35d8618.png)
Look,it's so ugly,isn't it?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2988 for more discussion.

/dup #2988


Also:
#6414, Tab Background color (#702/#1337/#2994)
