### ISSUE TITLE
Cannot run terminal when Windows Store is not available

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/terminal#7037]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): v1.1.2021.0

```

# Steps to reproduce

On my domain-joined PC, Windows Store apps are disabled. So I downloaded the latest release from here: https://github.com/microsoft/terminal/releases/download/v1.1.2021.0/Microsoft.WindowsTerminal_1.1.2021.0_8wekyb3d8bbwe.msixbundle

I then double-click the file to install it, and installation goes through as expected. In the Start menu I now have an icon for Windows Terminal. I click that to launch the app.

# Expected behavior

I expect Windows Terminal to open.

# Actual behavior

I get an error:
![image](https://user-images.githubusercontent.com/10893522/88284482-c608c380-cced-11ea-8ca0-6f536aae0076.png)

I verified that the file exists. The text about it being a network location is non-sensical, as it is on my laptop hard drive. The error code (0x800704cf) is the same as I get when trying to sign into a Windows Store app, then with the message "You will need the Internet for this." Internet access is working fine, I'm not connected to a VPN, and I don't have a proxy specified.

Windows Firewall is also turned off, but I do have Cylance installed.

**Comment by WSLUser** [comment]
This is a dupe and what's really need is use get the diagnostic data you can generate from Feedback Hub. It's a known issue issue and is the same on a host with no Internet with Windows Firewall enabled and Defender as the only A/V. You can work around this but changing .msixbundle to .zip and extract. Then take the relevant CacadiaPackage msix (arm/x86/x64) and change that to .zip as well. Extract it. Open the folder. You'll find WindowsTerminal.exe inside. Some things will not work as intended with this method ( you can't have it launch at log in for example) but for the most part everything works.

**Comment by CobusKruger** [comment]
@WSLUser I would love to give you the diagnostic data from Feedback hub, but that gets the same error code 0x800704cf when I try to sign in. I looked at the data in Documents\FeedbackHub, but there's a lot of stuff in there. If you can point me to where I can find the diagnostics to attach, I will.

Meanwhile, thank you very much for the workaround.

**Comment by WSLUser** [comment]
It doesn't go to me. I'm not with MS. Have you installed Feedback Hub? If so, try opening it. If not, see if you can remove your host from the domain and disable the group policy.  My money is on something in group policy but which setting causes this is a mystery.  Then install/sign in with proper creds (don't use your personal unless that's your company policy) Feedback Hub. Tell it to remember login (in Windows settings). Add machine back to domain.  Reapply group policy. Try opening Feedback Hub. If it works and you have it connected to Internet then look for Windows Terminal and submit feedback. You should have option to record the issue. Choose it. Attempt to re-open Terminal from Start Menu and press ok with error. End the data gathering in Feedback Hub and click submit. A URL should appear for you for the data dump.  Paste that URL here.

**Comment by CobusKruger** [comment]
Thanks for the explanation, but I'm pretty sure that removing and re-adding the machine to the domain isn't going to happen, based on previous experience with our infrastructure team. So for the moment, I'll use the workaround. Thanks again.

**Comment by DHowett** [comment]
Thanks for the report! I'm going to accumulate this with the rest of /dup #1386 :smile:
