### ISSUE TITLE
Switching Windows Terminal Language

### ISSUE THREAD

**Issue by espresso3389** [microsoft/terminal#7040]
# Description of the new feature/enhancement

We need some settings.json setting to change localization of Windows Terminal GUI.

Sometimes localization may break certain functionality and we want to turn off localization (back to plain English mode).

For me, #7039 is a critical issue and want to disable Japanese localization somehow...

**Comment by DHowett** [comment]
Thanks for the request (and reporting the command palette localization issue!). We're tracking this in /dup #5497
