### ISSUE TITLE
Whitespace characters added to start of each line when pasting text

### ISSUE THREAD

**Issue by atifraza** [microsoft/terminal#7041]
# Environment

```none
Windows build number: 19041.388
Windows Terminal version: 1.1.2021.0 (applicable to version too 1.0.1811.0)

Any other software?
WSL2 running Ubuntu 20.04
```

# Steps to reproduce

Copy a multiline text file using
- `cat config | clip.exe`

or
- `cat config` followed by selection with mouse and right-click or `Ctrl+Shift+C`

Open nano and paste the text using
- Right-click

or
- By pressing `Ctrl+Shift+V`

# Expected behavior

Text is pasted as displayed by `cat`, without any whitespace characters at the start of individual lines

Sample of displayed text:
![InkedScreenshot 2020-07-23 16 20 38_LI](https://user-images.githubusercontent.com/24366479/88299424-9f08bc80-cd02-11ea-8269-b92ea63a9bb6.jpg)

# Actual behavior

Multi-line text which does not have whitespaces at the start of new lines is pasted correctly.
Multi-line text with some indented lines is not pasted correctly, whitespaces start getting appended at the start of each line after the first occurrence of a whitespace character.

Sample of how text gets pasted:
![InkedScreenshot 2020-07-23 16 38 17_LI](https://user-images.githubusercontent.com/24366479/88299901-2ce4a780-cd03-11ea-9db2-63c719ca2a46.jpg)

**Comment by DHowett** [comment]
Your text editor is in autoindent mode, but the pasted text contains literal whitespace.

If I’m reading between the lines, this is a request for bracketed paste mode (so nano knows when to ignore the leading whitespace)

/dup #395

**Comment by atifraza** [comment]
> Your text editor is in autoindent mode, but the pasted text contains literal whitespace.
> 
> If I’m reading between the lines, this is a request for bracketed paste mode (so nano knows when to ignore the leading whitespace)
> 
> /dup #395

Exactly, I did have `autoindent` enabled for nano. Disabling it allows to paste correctly.
