### ISSUE TITLE
arrow keys are not working in menus

### ISSUE THREAD

**Issue by waterfox207** [microsoft/terminal#7044]
Hello Together,

since the update from today (1.1.2021.0) I have the problem that the arrow keys are not working anymore into menus. 
I have only the example of the esp idf menu. If I run it I can use all buttons but not the arrow keys anymore. 
This is how the menu looks like. I want to go up and down with the arrow keys:
![image](https://user-images.githubusercontent.com/59448194/88323773-06366900-cd23-11ea-8832-b4d3bc6c5895.png)

I also tested it in powershell and cmd. There is everything working fine. 

EDIT: this Problem exist also at the powershell preview and also if you are using powershell into the VSCode terminal. 

EDIT 2: I rolled now back to v1.0.1811.0 and there is everything working fine

**Comment by zadjii-msft** [comment]
For future reference:
https://github.com/espressif/esp-idf

Does adding `"experimental.input.forceVT": true` to the root of your settings help by any chance?

**Comment by waterfox207** [comment]
Perfect. That works. 

Beside this. Do you have any idea how to get this working at VSCode?

**Comment by Chips1234** [comment]
> Perfect. That works.
> 
> Beside this. Do you have any idea how to get this working at VSCode?

Just use Visual Studio to build then run (F5)

**Comment by DHowett** [comment]
Thanks for confirming. This sounds an awful lot like #7074 ... can you follow the troubleshooting steps in https://github.com/microsoft/terminal/issues/7074#issuecomment-664668844?

**Comment by waterfox207** [comment]
![image](https://user-images.githubusercontent.com/59448194/88712467-116e0800-d11a-11ea-8624-a3247a17f97c.png)

**Comment by DHowett** [comment]
So, that's with `experimental.input.forceVT` turned _on_, which is the workaround. I'd be interested in seeing what happens with it turned _off_ :smile:

**Comment by waterfox207** [comment]
![image](https://user-images.githubusercontent.com/59448194/88714387-0d8fb500-d11d-11ea-887a-c462a461a30f.png)
That's also not working correct. It will give either on true nor on false the same values. After switching a few times it gave other values. But now I'm not able to get those numbers back.

**Comment by DHowett** [comment]
Thanks for following up. Those numbers are the ones I was looking for. You can return `forceVT` to `true` and use it in the future.

This is the same as /dup #7074, which I now understand. :smile:
