### ISSUE TITLE
Feature Request/Idea 🚀: Add "Open Windows Terminal here" in context menu

### ISSUE THREAD

**Issue by juliandresbv** [microsoft/terminal#7046]
# Description of the new feature/enhancement

It would be helpful to be able to open a Windows Terminal in a specific directory via context menu (just like it is possible to open Powershell, Command line, WSL, etc., from ```Shift + secondary click button``` on the current directory then ```"Open ( Powershell | Command line| WSL ) here").```

Thanks :grinning:

**Comment by DHowett** [comment]
This exists today, but due to a Windows issue it only works if you actually right-click on a folder itself. We're tracking the rest of the work in /dup #6414.
