### ISSUE TITLE
My Windows version was 1909, and PowerShell was downloaded from the Microsoft store, and I opened a PowerShell Window, a PowerShell Window that ran the NPM command, and four PowerShell windows that ssh to, and after connecting successfully, four hours later, the PowerShell application window can not be clicked, closed, or typed, and can only be restarted

### ISSUE THREAD

**Issue by Fcscanf** [microsoft/terminal#7050]
My Windows version was 1909, and PowerShell was downloaded from the Microsoft store, and I opened a PowerShell Window, a PowerShell Window that ran the NPM command, and four PowerShell windows that ssh to, and after connecting successfully, four hours later, the PowerShell application window can not be clicked, closed, or typed, and can only be restarted

**Comment by thisVioletHydra** [comment]
What a dirty headline... ☹

**Comment by zadjii-msft** [comment]
@Fcscanf could you please fill out the issue template?

```md
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Windows Powershell Version:

Any other software?

# Steps to reproduce

A description of how to trigger this bug. List off the exact steps you took to reproduce the issue.

# Expected behavior

A description of what you're expecting, possibly containing screenshots or reference material.

# Actual behavior

What's actually happening?

```

There are a few other issues on the repo that are similar, but honestly, I can't make heads or tails of that sentence. Are you running this in the Windows Terminal, or a legacy console window?
