### ISSUE TITLE
when the text is zoomed in and zoomed out for multiple times by scrolling on trackpad the application unexpectedly closes

### ISSUE THREAD

**Issue by asutoshgha** [microsoft/terminal#7053]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by asutoshgha** [comment]
Windows Terminal 0.11.1191.0 is the version

**Comment by DHowett** [comment]
You are on an extremely old version of Terminal. There is a high likelihood that your bug has been fixed already. It is impossible to tell when you are four months out of date. Please upgrade.
