### ISSUE TITLE
Mouse input bindings/configuration

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#7059]
# Description of the new feature/enhancement

A way to configure mouse behaviours where they are governed by the Terminal, rather than passed through to the shell.

Specifically, I want to unbind Ctrl+Scrollwheel so I stop accidentally resizing my terminal font (or making my background transparent!) when I'm control-shift-arrow scrolling and try to switch to mouse-scroll before I've fully released the other keys.

# Proposed technical implementation details (optional)

Looking at [TermControl.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/TermControl.cpp) I guess all the code-paths where `_CanSendVTMouseInput` was `false` ought to be controlled by configuration options.

A brief glance suggests it's only the [mouse wheel handling](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/cascadia/TerminalControl/TermControl.cpp#L1370-L1384) that doesn't already have associated configuration options right now.

I'm not sure if there should just be specific configuration options for these cases ([transparency](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/cascadia/TerminalControl/TermControl.cpp#L1404-L1448)/[zoom](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/cascadia/TerminalControl/TermControl.cpp#L1450-L1459)/[scroll](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/cascadia/TerminalControl/TermControl.cpp#L1480-L1517)) or if some kind of bindings system, like the keybindings, is appropriate.

Maybe we can find a use for horizontal scrolling, and buttons other than left and right, for those who have such capable mice.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1553 for more discussion.

/dup #1553

**Comment by TBBle** [comment]
Ah, drat, I did search for that. Apparently I didn't go back far enough or searched on the wrong terms... Oh well, thank you for finding it for me.
