### ISSUE TITLE
Regression in handling Environment Variable updates

### ISSUE THREAD

**Issue by adehad** [microsoft/terminal#7060]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version:
1.1.2021.0

Any other software?
Powershell 7.0.3
Chocolatey to manage Powershell and Windows Terminal
```

# Steps to reproduce
1) Open Terminal with a Powershell 7 tab
2) Update the Path or add a new Environment variables
3) Open a new WindowsPowershell OR cmd window (not via a tab in Terminal) 
4) Try to access an newly added item in the Path  or environment variable

# Expected behavior
1) Able to access new items in Path

# Actual behavior
1) Terminal needs to be closed before any new Powershell / WindowsPowershell / cmd instances can access new environment variables.

(If I recall correctly, previously I did not even need to open a new tab/instance of Powershell to access the new environment variables, and I definitely did not need to close Terminal to gain access - maybe opening a new tab at most)

**Comment by zadjii-msft** [comment]
So this definitely never worked. It's being tracked over in #1125 ☺️ 

/dup #1125
