### ISSUE TITLE
Focus is not moved to cursor when switching from another application

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#7061]
# Environment

```
Windows build number: Version	10.0.19041 Build 19041

Windows Terminal version:1.2.2022.0

```

# Steps to reproduce

- Ensure  "snapOnInput": true, is set in default profile settings.

- Start a new terminal session/window.

- Ensure that there are two shell tabs open in the window.  (I use 2 powershell tabs but it doesn't seem important exactly which are used).

- Open Notepad or some other application of your choice.

- Change the focus to notepad and type into the window.

- Click on the first tab header in Terminal  (important - must be header, not editing pane)

- Start typing - note that no text appears at the cursor in the Terminal pane pane.  

- The **expected behavior** would be that text would appear the cursor

- _Note that if you then click on the header of the second tab and start typing, text _is_ displayed at cursor so this appears to be an issue to do with the initial application focus._

# Expected behavior

As above, changing focus to terminal from another application by clicking on a tab header should move text-entry focus to the editing pane.

# Actual behavior

See above.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3609 and #6680 for more discussion.

/dup #3609

**Comment by NeilMacMullen** [comment]
Thanks @zadjii-msft !  I did have a look through the backlog of "focus" issues but missed that one.  Keep up the great work - I'm liking the new terminal a lot.
