### ISSUE TITLE
Setting to disable "Paste multiline text may execute code" popup message introduced in WT 1.2 Preview

### ISSUE THREAD

**Issue by ChrisLynchHPE** [microsoft/terminal#7063]
# Description of the new feature/enhancement
In the newly released Windows Terminal 1.2.2022.0 Preview, pasting multiple lines of text produces a new dialog message:

![image](https://user-images.githubusercontent.com/6956305/88414668-15a0cb00-cd92-11ea-936c-b71e6c459343.png)

There is no documented setting to disable this prompt (likely not implemented at all).  Please implement a settings option to never prompt this message again.  As a developer and power user, this message is pointless to me.  This breaks my flow of development, as this message is displayed every time I paste multiple lines of code into the terminal, regardless of the tab, and I have to click `Paste anyway` button.  The average user might find this new setting helpful too.

# Proposed technical implementation details (optional)

Similar to the `confirmCloseAllTabs` setting property, a similar one for this should be created:

```
Property name: confirmMultiLinePasteMessage
Necessity: Optional
Accepts: true, false
Default value: true
``

**Comment by DHowett** [comment]
You mean like [this one](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#warn-when-the-text-to-paste-contains-multiple-lines-preview)?

**Comment by DHowett** [comment]
> likely not implemented at all

ye of little faith ☹️

**Comment by ChrisLynchHPE** [comment]
Well, when I searched the docs, I didn't find it.  So thank you for pointing it out.

**Comment by ChrisLynchHPE** [comment]
Also, this isn't in the settings schema.  So if editing in VSCode, neither `largePasteWarning` or `multiLinePasteWarning` appear in Intellisense results.

**Comment by aybiss** [comment]
This is really really terrible. And when are we going to get a settings editor better than Notepad?

**Comment by aybiss** [comment]
Even if the settings files contained all the settings so we could look through them it would be better than just stabbing in the dark. Do you know how many possible settings there are with 26 letters, lower and upper case, the length of multiLinePasteWarning? 

1.0866013e+36.

That's how many settings you want people to try out in order to find something. 

:-P

**Comment by DHowett** [comment]
I don't know -- the editor I have configured to edit JSON files (which is very much not Notepad) is significantly more helpful than would force me to try options at random 😉 

![image](https://user-images.githubusercontent.com/189190/92059194-76360700-ed45-11ea-9b5d-ee31e9e518c0.png)

**Comment by aybiss** [comment]
Ahhh, you must have access to the internet while you're editing those files. Would be good if all the settings were there in the file.

**Comment by sudomyju** [comment]
@DHowett .... sorry that link of yours -> ```You mean like this one?``` kind of doesn't aim to anything meaningful regarding this issue.

Is that a problem for you to add the exact json attribute what should go in the jsonsettings in order to disable the multiple lines paste warning? 

As like pointing to a page (which obviously updates not regarding to your post) and being obscure about what settings attributes should go in is not helpful at all.

Can you perhaps add a plaintext json attribute that fixes this?

perhaps it is already fixed half year later ?

**Comment by zadjii-msft** [comment]
@sudomyju Sorry about that, our docs site got updated in the last 7 months since that post. Some of the URLs must not forward as expected. The new link is here:

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#warn-when-the-text-to-paste-contains-multiple-lines

> ### Warn when the text to paste contains multiple lines
> 
> When this is set to `true`, trying to paste text with multiple lines will display a dialog asking you whether to continue or not with the paste. When it's set to `false`, the dialog is not shown and instead the text is pasted right away. In most shells, one line corresponds to one command so if you paste text that contains the "new line" character into a shell, one or more command(s) might be executed automatically upon paste, without you having time to validate the commands. This can be useful if you often copy and paste commands from untrusted websites.
> 
> **Property name:** `multiLinePasteWarning`
> 
> **Necessity:** Optional
> 
> **Accepts:** `true`, `false`
> 
> **Default value:** `true`

**Comment by sudomyju** [comment]
Thank you Mike @zadjii-msft 
great post btw 👍 :-)

**Comment by crackwitz** [comment]
Now if only that property were presented in the settings UI. At this time, it does not appear to be.
