### ISSUE TITLE
Improved Prompts in Find Box.

### ISSUE THREAD

**Issue by roopeshvs** [microsoft/terminal#7066]
# Description of the new feature/enhancement

I would like to have a '**Current out of Total Results Found**' and '**Not Found**' prompt when searching for a word in the Terminal Window. Currently, no information of this kind is available.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3920 and #6319 for more discussion.

/dup #3920
