### ISSUE TITLE
You can install this tool in an easy way(保证让你安装成功!!!)

### ISSUE THREAD

**Issue by cuishuang** [microsoft/Terminal#707]
https://www.dashen.tech/2019/05/11/%E6%89%8B%E6%8A%8A%E6%89%8B%E5%B8%A6%E4%BD%A0%E4%BD%93%E9%AA%8C%E6%9C%80%E6%96%B0Windows-Terminal/

下载编译好的文件,https://pan.baidu.com/share/init?surl=N-_UA8P46i081Y-sUSfzIQ
提取码:7mux

运行文件

过程中可能会报错你需要为此应用包安装新证书，或者使用带受信任证书的新应用包。系统管理员或应用开发人员可以提供帮助。已处理证书链，但处理过程因根证书不受信任而终止 (0x800B0109),

可参考此文步骤轻松解决

过了这个坎是新的沟,应用安装失败，

错误消息: 由于程序包 Microsoft.WindowsTerminal_2019.5.6.0_x64__8wekyb3d8bbwe 与设备不兼容，Windows 无法安装该程序包。该程序包要求 Windows.Universal 设备系列运行操作系统版本 10、0、18362、0 或更高版本。该设备当前运行的操作系统版本为 10、0、17763、316。 (0x80073cfd)

这个报错是说需将windows版本从17763升级至18362,查看当前版本信息

可通过该网站下载对应操作系统最新的版本,点此,
对64位系统,可直接复制ed2k://|file|cn_windows_10_consumer_editions_version_1903_x64_dvd_8f05241d.iso|4905476096|F28FDC23DA34D55BA466BFD6E91DD311|/至迅雷或电骡下载.

经过漫长的下载,点击iso安装最新版本

然后便可一马平川安装体验~

如链接失效,可发送邮件至i@dashen.tech

同行不是冤家,在一起就是力量;
让我们一起抵制996

**Comment by DHowett-MSFT** [comment]
Hi there,
Please don’t post links to binaries. The project will have a binary release when it’s ready.
