### ISSUE TITLE
syntax highlighting underline messes up when window resized 

### ISSUE THREAD

**Issue by kellytrinh** [microsoft/terminal#7070]
# Environment

```none
Microsoft Windows [Version 10.0.19041.388]
Windows Terminal 1.1.2021.0

Any other software?

zsh with syntax highlighting
https://github.com/zsh-users/zsh-syntax-highlighting
```

# Steps to reproduce

1. Do something that results in underlining of the syntax (e.g 'cd /tmp/' will underline the tmp as a folder)
2. resize the window

# Expected behavior

the underlining does not change due to window size changes

# Actual behavior

the underline now extends to the right edge of the window

**Comment by j4james** [comment]
I think this is just a variant of issue #32.

**Comment by zadjii-msft** [comment]
Yep, sure is!

/dup #32
