### ISSUE TITLE
希望加入类sudo功能

### ISSUE THREAD

**Issue by dihaoxuan** [microsoft/terminal#7072]
我小白，啥都不懂，就是每次用choco安装啥都要重新以管理员身份运行，否则就会报错，很不方便

**Comment by KayLeung** [comment]
感覺機會不大
https://github.com/microsoft/terminal/issues/146

非官方
https://github.com/gerardog/gsudo

**Comment by skyline75489** [comment]
This is #146 in another language.

**Comment by zadjii-msft** [comment]
Sure looks like it!

/dup #146 #1032 #632 #5000
