### ISSUE TITLE
Default tab color for a profile

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#7073]
Hello,
How I can set default tab color for a profile?
![Windows Terminal](https://user-images.githubusercontent.com/23485114/88459416-aec30500-ceaa-11ea-9c01-ad81406af374.png)
I tried this but it does not work:
![ٰVisualStudio Code](https://user-images.githubusercontent.com/23485114/88459337-e0879c00-cea9-11ea-994b-3d5d01751c28.png)
Please answer me.
Thanks

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22default+tab+color%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1337 and the spec #5772 for more discussion.

/dup #3327 #1337 #6878 #6707
