### ISSUE TITLE
Allow moving panes to other tabs

### ISSUE THREAD

**Issue by dan1994** [microsoft/terminal#7075]
# Description of the new feature/enhancement

Simply put, I would like to be able to take a single pane and either transform it into a tab, or add it as a pane of a different tab.
In my opinion this is useful when a specific tab gets overcrowded with panes, and gets cumbersome.
You could close the panes you want to move and reopen new ones in a different tab, but then you lose output of previous commands, environment changes you made, etc.

As for how this might appear to the user, I think it would have to be a drag & drop kind of thing for the use case of moving the pane to an existing tab (Also allowing to rearrange panes in the same tab which would be nice). Keyboard shortcuts might work too, but I think it'll make it hard to reach the exact arrangement of tabs.

**Comment by zadjii-msft** [comment]
You know what, we shockingly _don't_ have a dupe for this in #1000. I think we were already planning on adding this, but it looks like it wasn't previously tracked. Thanks for keeping us honest!

**Comment by dan1994** [comment]
Thank you for the great work. As someone coming from linux, transitioning to Terminal + WSL is a delight!

**Comment by usama8800** [comment]
Does this also include swapping panes on the same tab?

**Comment by Don-Vito** [comment]
> 
> 
> Does this also include swapping panes on the same tab?

I thinks it is tracked separately, here https://github.com/microsoft/terminal/issues/4922
