### ISSUE TITLE
About dialog should include link to GitHub repository

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#7078]
# Description of the new feature/enhancement
The about dialog should include a link to the GitHub repository for enhanced discoverability to the repository and more contributors.

# Proposed technical implementation details (optional)
Have a hyperlink string "Check out the repository on GitHub".

**Comment by DHowett** [comment]
The Feedback link in the menu already goes to the GitHub repo, and the documentation links to it as well. I’m not sold on whether we should add another link.

The links we do have are _required_; I think users might get tired of seeing so many links?

**Comment by Chips1234** [comment]
Hmm. Maybe we should at least have a line of text “Terminal is made possible by the MIT License” ?

**Comment by DHowett** [comment]
I'll engage with design on this. For now, I don't think we're going to add more About dialog text ... but we'll think about it :smile:

**Comment by Chips1234** [comment]
Alright
________________________________
