### ISSUE TITLE
Windows Terminal should be translated in every language that Windows 10 supports including LIP languages

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/terminal#7079]

**Comment by DHowett** [comment]
So, we reached out to the localization team about this exact issue. Their official guidance was that it should be localized like the rest of our _developer tools_, which is the 10-13 languages that we have made available. 

What language are you specifically looking for?

**Comment by Jaiganeshkumaran** [comment]
@DHowett Tamil (ta-IN)

**Comment by Jaiganeshkumaran** [comment]
I don't think Windows Terminal is a developer tool. Conhost is available on every language so Windows Terminal should also be available in every language. Windows Terminal can also be used for other purposes.
