### ISSUE TITLE
0xc0000022 startup error when opening wt from file explorer or Run window

### ISSUE THREAD

**Issue by JakubKoralewski** [microsoft/terminal#7081]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
```
Found this in my PATH:
```
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
```
Alias settings:
![image](https://user-images.githubusercontent.com/43069023/88475842-e3c76a00-cf33-11ea-8e65-68dfcf63a184.png)

I tried turning my computer off and on again :wink: This error started popping up very recently, maybe I could try to install an old version to try to find the one that triggers this. I install from Windows Store, and don't really know how to do that.
I think this shows the time of last update:
![image](https://user-images.githubusercontent.com/43069023/88475891-4caee200-cf34-11ea-9d45-3c309c9e889e.png)
I think the time when the bug started to appear might coincide.

# Steps to reproduce

Type `wt` in the file explorer, or `Run` window.

 It works if I search for `wt` and open it. Also works if I navigate to `C:\Users\<USERNAME>\AppData\Local\Microsoft\WindowsApps` and run it manually. Doesn't work though from both the `Run` window and file explorer.

I also tried typing `wt` in the Run window, then pressing Ctrl+Shift+Enter, a popup appeared to ask for permission, but the same error appeared after allowing.

# Expected behavior

It opens.

# Actual behavior

I get 0xc0000022 error
![image](https://user-images.githubusercontent.com/43069023/88475594-d1e4c780-cf31-11ea-9e76-ad0fd16630b9.png)

**Comment by DHowett** [comment]
If you turn this switch off and on again, does it work?

![image](https://user-images.githubusercontent.com/189190/88490870-6b70a100-cf53-11ea-850c-bb0f55cda4f3.png)

Can you open up Command Prompt and run `where wt`? I wonder if there is another copy somewhere that is broken.

**Comment by JakubKoralewski** [comment]
> If you turn this switch off and on again, does it work?

Unfortunately not.

> Can you open up Command Prompt and run where wt? I wonder if there is another copy somewhere that is broken.

From command prompt:
```
C:\Windows\System32>where wt
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe
```

From Windows Terminal (git bash):

```bash
$ where wt
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe\wt.exe
```

I guess the preview shouldn't be there? And why would it only show up when called from the Windows Terminal?

I thought this was because of git bash so I changed directory into the same folder as before with Windows Terminal, but the output from git bash is kind of different:

```bash
$ where wt
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe
(base)
```
Also opening from the cmd prompt by typing `wt` works fine. The cwd working directory is correctly assigned and all is good, but Run window and File explorer still throws the error.

Also trying to open `wt` from git bash:

```bash
$ wt
bash: /c/Users/Admin/AppData/Local/Microsoft/WindowsApps/wt: Permission denied
(base)
```

**Comment by DHowett** [comment]
If you turn the non-preview one off and the preview one on, does the behavior change?

**Comment by JakubKoralewski** [comment]
I uninstalled the Preview version and now everything seems to work.

> If you turn the non-preview one off and the preview one on, does the behavior change?

It didn't. I restarted, tried again and it was the same error. Only difference was `where wt` showed only the path to `WindowsApps\wt.exe` and the Preview had disappeared.

**Comment by DHowett** [comment]
This is very strange. Thank you for reporting. Just to confirm: now that you've removed preview, it works fine? That is very unexpected :smile:

**Comment by JakubKoralewski** [comment]
Yes, it's been working fine since I removed Preview. Seems weird, but I'm just happy everything's working 🥰 . Also since it seems tab renaming has hit stable, Preview lost the major thing I've been using it for, so all is good now in my book.

**Comment by DHowett** [comment]
Thanks for following up! I'm gonna close this out as not reproducing, but please do let me know if it comes back.

**Comment by JakubKoralewski** [comment]
> please do let me know if it comes back.

It did :(
![image](https://user-images.githubusercontent.com/43069023/94405962-96ed5300-0171-11eb-9f8e-a8a588a3eb3c.png)

It seems when I type `wt` into the explorer it's using this path: `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\wt.exe` (it flashes very briefly in the explorer *URL* input and can be retrieved), while `where wt` returns a more sane `C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe`. And opening the first path in `cmd` returns the same error as running in explorer, but running the second path is not a recognized command...:
```cmd
C:\Windows\System32>"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\wt.exe"

C:\Windows\System32>C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe
'C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\wt.exe' is not recognized as an internal or external command,
operable program or batch file.
```

After the above, I tried reinstalling, but the same error happens. So I tried to uninstall it again and this time I tried removing all these folders:
![image](https://user-images.githubusercontent.com/43069023/94407356-a66d9b80-0173-11eb-91e9-630b04289dd6.png)
but I can't remove it all because some files are either opened in another program or I need "SYSTEM" permissions to remove them. I tried changing one of the folder's owner to myself, but when trying to uninstall it says I need permissions from myself to uninstall.

After reinstalling, I removed `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` folder from user `Path` and now the error remains when starting from the explorer, but it doesn't work at all when typed into the `cmd`:

```
C:\Windows\System32>wt.exe
'wt.exe' is not recognized as an internal or external command,
operable program or batch file.
C:\Windows\System32>where wt
INFO: Could not find files for the given pattern(s).
```

Is there a way to force the use of `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` instead of `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe` ?

**Comment by DHowett** [comment]
This usually happens when you change the permissions on `C:\Program Files\WindowsApps`. It is an important part of the app platform on Windows and not something Terminal can recover from when it is broken.

Given that you had no trouble _accessing that folder_, consider restoring the permissions and removing and reinstalling all instances of Terminal so that they get put back with the correct permissions.

**Comment by JakubKoralewski** [comment]
This is crazyyy. I did a restore first with and then without keeping data, but [the WindowsApps permissions problem was still there](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store-winpc/windows-10-store-and-most-apps-wont-open/727305b7-9f1b-46a7-a548-d5dd0fe25234), where the Windows Store or any other built-in app for that matter would not turn on. I am now very finickly at a reverse stage where it works when called from the explorer, but doesn't (incorrect parameter) when called from a shortcut.

I have no idea how a permission problem can persist after system reinstall. This is crazy. I guess somehow it's in the cloud in my Windows user profile... 🤷

**Comment by zachThePerson** [comment]
I am getting this issue starting this morning. Windows updated something (I think security related) and when I booted up I get the same error. Unfortunately for me, drive formatting isn't really an option as it's just not worth it.

Currently I'm just switching back to powershell, but it would be nice if there was a fix/solution for this

**Comment by dwright726** [comment]
I too started getting this error out of the blue this morning no updates have been applied (to my knowledge) worked yesterday afternoon, I've already spent 1-2hours trying to figure it out.  My answer is just to abandon the terminal all together this is the second time I have ran into issues with it that has led to multiple hours of troubleshooting, at this point the benefits of wt are no longer worth the technical debt

**Comment by dexeonify** [comment]
I've found a solution from another thread which seems to solve this issue.
> Just taking ownership and granting read/execute permission to "Users" for single file "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\vcruntime140.dll" fixed issue for me. No need to mess with whole WindowsApps folder permissions

**Comment by zachThePerson** [comment]
@dexeonify I had to take control of the WindowsApps folder first, and while I was able to take ownership of vcruntime140.dll, when I go to edit permissions it gives me an error saying "The access control entry is corrupt. Delete it and Create a new one." Guides online on how to do this seem spotty at best.

**Comment by dexeonify** [comment]
Hmm, weird. I didn't face any issues when using that method. You don't have to take ownership of the whole WindowsApps folder, just vcruntime140.dll.

Here's how I did it:
1. Head over to "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe" and find `vcruntime140.dll`.
2. Click "Properties" > "Security" > "Advanced" and change the ownership to your current user.
3. Click "Apply" and "Ok" and close the Properties window.
4. Reopen "Properties" > "Security" > "Edit", select "PCNAME\Users" and grant it read/execute permission.

If it's corrupt, I guess you have to remove it and add a new one.

**Comment by zachThePerson** [comment]
The problem was I wasn't able to access WindowsApps without first taking ownership. I also have no idea how to delete that file, or where it is.

**Comment by Gameghostify** [comment]
Suddenly got this issue as well, without touching my installation

**Comment by cjpellicci** [comment]
Just for another data point, I am also suddenly experiencing this issue since a few days ago. I do have permission to the WindowsApps folder, but wt previously worked fine despite that until a few days ago. Same as above, the issue only occurs when trying to run wt from the start menu or file explorer.

It appears as if I have three copies of wt.exe as well, in the same locations as above:
`C:\Users\cjpel\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe`
`C:\Users\cjpel\AppData\Local\Microsoft\WindowsApps\wt.exe`
`C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\wt.exe`

It seems as if an update to either Windows or Windows Terminal has done something to suddenly cause this issue, as I and others have chimed in saying that it just started happening in the past few days without changing anything.

**Comment by cjpellicci** [comment]
I was able to fix the issue by resetting permissions to the WindowsApps folder. wt works as expected after running the command below in an elevated PowerShell:

`icacls "C:\Program Files\WindowsApps" /reset /t /c /q`

**Comment by sokolinivan** [comment]
> Мне удалось решить проблему, сбросив разрешения для папки WindowsApps. wt работает должным образом после выполнения следующей команды в PowerShell с повышенными привилегиями:
> 
> `icacls "C:\Program Files\WindowsApps" /reset /t /c /q`

Thank you so much. This really solves the problem.

**Comment by zachThePerson** [comment]
I tried 

> 
> 
> I was able to fix the issue by resetting permissions to the WindowsApps folder. wt works as expected after running the command below in an elevated PowerShell:
> 
> `icacls "C:\Program Files\WindowsApps" /reset /t /c /q`

And said "Access Denied," on each line that appeared. I tried it with System, and myself as the folder owner and same result

**Comment by zachThePerson** [comment]
Ok, now terminal just refuses to open from the start menu. I can't use "wt" to open it from explorer, running "wt" from powershell (which worked until yesterday), or Start > Terminal to open it, or Start > typing "Terminal," and then opening it that way.

After a reinstall, launching from start, search, and "wt" from powershell worked correctly, but file explorer still gave the 0x0...2 error

**Comment by butgit** [comment]
I found this problem yesterday when I tried running it by typing wt and Enter from start menu. I reinstalled it from MS Store but still get the same error message. I tried `icacls "C:\Program Files\WindowsApps" /reset /t /c /q ` to no avail. I don't think the installation is not corrupt because typing windows terminal and Enter in the start menu opens the terminal normally. Really strange.

**Comment by 0x15f2d** [comment]
I thought this issue was my SSD breaking up files since it has signs of making files incorrectly usable (a jar file broken).

So I went through a DISM, SFC, DSKCHK but they aren't working at all.

Plus upgrading to 20H2 doesn't seem to fix it since upgrading windows will reinstall drivers, Windows apps.

**Comment by KyleCrowley** [comment]
I'm running into this same error seemingly out of nowhere (I suspect a Windows update as others have alluded to).

Steps I've taken to try and resolved:

1) Ran `icacls "C:\Program Files\WindowsApps" /reset /t /c /q` with Windows Terminal installed **[FAIL]**
2) Uninstalled Windows Terminal (using @0x15f2d suggestion above) and re-installed, resetting permission before and after (using the command in step 1) **[FAIL]**

Neither solution worked.

I should point out that I'm installing Windows Terminal via chocolatey, not through the Windows Store (my organization prevents me from doing so), so this issue doesn't seem to be isolated to just the Windows Store installation method.

**Comment by 0x15f2d** [comment]
@KyleCrowley doing `icacls "C:\Program Files\WindowsApps" /reset /t /c /q` **does not** actually restore 100% WindowsApp's folder original permissions and owners. It just restores to **default owners and permissions**. Usually You (Part of the Administrators). You need an actual  backup of owners and permissions from WindowsApps folder so `icacls` can use the **backed up permission file** to restore the folder's owners and permissions correctly.

Otherwise, **Upgrading** existing Windows **will** fix this since it's like a reinstallation (better than doing `dism` and `sfc` thing. I tried and it **partially** works for the WindowsApps folder alone. The rest of the folder's content that has permissions altered must be reinstalled (**deleted**).

**Comment by KyleCrowley** [comment]
@0x15f2d Thanks for the note about restoring the original permissions. You led me down a path that eventually allowed me to get Windows Terminal working again.

The method I followed was the one laid out [here](https://superuser.com/a/1507948). At some point, I must've taken control of the WindowsApps folder via my local admin account (separate account my organization provisions). Once I followed the procedure, things started working again (barring some irregularities with the Chocolately install, but that is out of scope as far as this issue is concerned).

**Comment by zachThePerson** [comment]
@KyleCrowley Wow for some reason this worked. When I first started getting the bug, somebody else here suggested modifying the some files in the folder, but I didn't have access. I took ownership to gain access to WindowsApps and edit the files, but it didn't fix my problem. Restoring ownership to TrustedInstaller fixed my problems. Weird.

**Comment by 0x15f2d** [comment]
> The method I followed was the one laid out [here](https://superuser.com/a/1507948). 

@KyleCrowley oh yeah that makes sense to me now. because reinstalling windows is like using SYSTEM to do stuff.
`psexec.exe -s -i cmd`

**Comment by 0x15f2d** [comment]
@zachThePerson there will be more issues to come if you still can see if you still have permissions to see _(read permissions)_ who owns **WindowsApps** folder (not its contents) because i have multiple built in apps reinstalled from ms store (not actually deleting the folder itself because altered ownerships and I don't know this method yet) and they are all starting up crashed like Weather app or Xbox Companion app.

Repairing, clean app data won't help from Settings app.

**Comment by zachThePerson** [comment]
It happened again. Same error, but nothing I did last time seems to fix it. As far as I can tell all the permission settings are the same

**Comment by JamesWZM** [comment]
`icacls` does not work for me at all!

The WindowsTerminal.exe is still available, but wt.exe just won't work and returns to me a 0xc0000022 error.
I have no idea what has happened to it. It's still working well yesterday and I have not restarted my computer.

Also, OpenConsole.exe returns to me the same error.

**Comment by wuqiling97** [comment]
`icacls` not working, but I found a workaround: 

- Uninstall Windows Terminal. 
- Goto Settings → System → Storage → Change where new content is saved and change "New apps will save to" from C: to D:. 
- Install Windows Terminal. 

Then I can run `wt` from `Run` window.

**Comment by zachThePerson** [comment]
Great workaround! Wouldn't be surprised if a future update breaks this folder too though

**Comment by barnemesh** [comment]
A solution I found-
changing the values in the following registries:
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe
from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\

**Comment by zachThePerson** [comment]
Changing the registry path worked like a charm. Since it points to an AppData folder, I think this should be the default as we wouldn't ever have to worry about security bugs like this

**Comment by DHowett** [comment]
> security bugs like this

App packages are installed and registered _per-user_; this is the only effective way to give users specific control over which app package is invoked :)

**Comment by zachThePerson** [comment]
Ok. Also it broke again so I retract my previous statement. Don't know why it only worked once or twice, registry entries are still the new value so idk what is going on anymore

**Comment by mihirsavadi** [comment]
> A solution I found-
> changing the values in the following registries:
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe
> from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\

This worked perfectly!!!!!!!!! Tried literally everything else in this thread only more problems, but this worked

**Comment by pashza** [comment]
> I was able to fix the issue by resetting permissions to the WindowsApps folder. wt works as expected after running the command below in an elevated PowerShell:
> 
> `icacls "C:\Program Files\WindowsApps" /reset /t /c /q`

This worked perfectly!

**Comment by PennRobotics** [comment]
For anyone else who messed up their WindowsApps permissions running the command above, running the script at https://github.com/AgentRev/WindowsAppsUnfukker made everything (mostly) well again. Except now Windows Store thinks Terminal Preview is installed while it cannot be found via Start Menu or Add/Remove Programs. (It is, in fact, installed.)

**Comment by liudonghua123** [comment]
> A solution I found- changing the values in the following registries: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\

This method works for me. I found that `"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\wt.exe"` is a uwp, and can not directly run. You should run `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` (It's a zero sized file, maybe called app execution alias) instead.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/2276718/158008607-e580c05b-cefe-4521-af40-74cc760b6620.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2276718/158008627-49ccc91e-28c7-4f0f-8721-b2f279e511eb.png">

But I find other items in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths` are using path like `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemforLinux_0.51.3.0_x64__8wekyb3d8bbwe`.

**Comment by Plutonium-239** [comment]
@liudonghua123 Thank you so much!
Finally works after 6 months lol

**Comment by Anonymous87549236** [comment]
https://superuser.com/questions/1288014/reset-default-acls-for-c-program-files-windowsapps worked for me.

**Comment by LeoZeolite** [comment]
> A solution I found- changing the values in the following registries: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\

This method works for me.

**Comment by petryaevve** [comment]
> > A solution I found- changing the values in the following registries: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\
> 
> This method works for me. I found that `"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\wt.exe"` is a uwp, and can not directly run. You should run `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe` (It's a zero sized file, maybe called app execution alias) instead.
> 
> <img alt="image" width="823" src="https://user-images.githubusercontent.com/2276718/158008607-e580c05b-cefe-4521-af40-74cc760b6620.png">
> 
> <img alt="image" width="773" src="https://user-images.githubusercontent.com/2276718/158008627-49ccc91e-28c7-4f0f-8721-b2f279e511eb.png">
> 
> But I find other items in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths` are using path like `C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemforLinux_0.51.3.0_x64__8wekyb3d8bbwe`.

Thanks!!! It works good

**Comment by igorhbs** [comment]
Why won't Microsoft fix this registry issue on Windows Terminal installation?

**Comment by smurpau** [comment]
I've run into this issue as well, reproducibly, by building a Hyper-V VM with Vagrant, the "gusztavvargadr/windows-10-22h2-enterprise-nocm" base box, chocolatey, and `choco install microsoft-windows-terminal` (tried the latest version as well as 1.18.2822.0 which is running fine on my host Win10 machine).

`icacls "C:\Program Files\WindowsApps" /reset /t /c /q` doesn't work, nor does the registry change.

**Comment by r1ght0us** [comment]
> > 我找到的解决方案-更改以下注册表中的值： Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe 从 C:\Program Files\WindowsApps\ 路径更改为 C:\用户\用户名\应用程序数据\本地\微软\WindowsApps\
> 
> 这个方法对我有用。我发现`"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe\wt.exe"`是一个uwp，并且不能直接运行。您应该运行`%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe`（这是一个零大小的文件，可能称为应用程序执行别名）。
> 
> <img alt="图像" width="823" src="https://user-images.githubusercontent.com/2276718/158008607-e580c05b-cefe-4521-af40-74cc760b6620.png">
> 
> <img alt="图像" width="773" src="https://user-images.githubusercontent.com/2276718/158008627-49ccc91e-28c7-4f0f-8721-b2f279e511eb.png">
> 
> 但我发现其他项目`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths`正在使用类似的路径`C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemforLinux_0.51.3.0_x64__8wekyb3d8bbwe`。

thanks, this work for me

**Comment by petryaevve** [comment]
> A solution I found- changing the values in the following registries: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe from the C:\Program Files\WindowsApps\ path, to the path in C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps\

Thank you! It's working now
