### ISSUE TITLE
Hard disk problem

### ISSUE THREAD

**Issue by kikiroxYT** [microsoft/terminal#7083]
```none
Windows build number: Microsoft Windows [version 10.0.19041.388]
Windows Terminal version (if applicable): 1.2.2022.0
```

# just do 'cd E(another hard disk):/'

# when we try to do cd E:/ it doesn't change the path
![Capture](https://user-images.githubusercontent.com/43090601/88488972-7ba77100-cf91-11ea-8d9c-9b1f3deea8e7.PNG)

**Comment by DHowett** [comment]
This is how the command prompt has always worked in Windows, and this behavior has its roots in MS-DOS 1

See more [here](https://superuser.com/questions/135214/using-cd-command-in-windows-command-line-cant-navigate-to-d).

**Comment by kikiroxYT** [comment]
its strange because in the normal terminal it works fine
