### ISSUE TITLE
Command line shifted upwards, overlaying with previous text

### ISSUE THREAD

**Issue by leo-carmo** [microsoft/terminal#7085]
# Environment

```none
Windows build number: 19041.388
Windows Terminal version: 1.1.2021.0

```

# Steps to reproduce

1. Select the PowerShell environment within Windows Terminal — not a Linux distro under WSL or Windows CMD.
2. Type any command that produces a lot of output, like `dir`.
3. After the output is printed, begin typing the next command and watch where the characters are being inserted.

# Expected behavior

The characters in step 3 above were supposed to appear in the bottom line, a.k.a "*the* command line" without covering other characters already on-screen.

# Actual behavior

The characters in step 3 above are not aligned with the command line; rather, they're overlaying with previous characters printed on the Terminal.
![Windows terminal bug](https://user-images.githubusercontent.com/51187764/88499134-646d8100-cf9b-11ea-9379-6ffe55d9e09a.gif)

**Comment by skyline75489** [comment]
Fascinating. Can you share your config file with us? I can not reproduce it with `dir` and I do not have that many local packages installed with choco.

**Comment by DHowett** [comment]
Usually when we see this it’s because a person has a powershell profile.ps1 that changes the size of the console window for some unknown reason :)

**Comment by leo-carmo** [comment]
> 
> 
> Fascinating. Can you share your config file with us? I can not reproduce it with `dir` and I do not have that many local packages installed with choco.

Sure, you mean the settings json? Here https://pastebin.com/VBkPcgTg

**Comment by leo-carmo** [comment]
> 
> 
> Usually when we see this it’s because a person has a powershell profile.ps1 that changes the size of the console window for some unknown reason :)

Here it goes my PowerShell profile:

	set-location C:
	$Shell.WindowTitle="Powershell do Leo"
	$Shell = $Host.UI.RawUI
	$size = $Shell.WindowSize
	$size.width=80
	$size.height=25
	$Shell.WindowSize = $size
	$size = $Shell.BufferSize
	$size.width=70
	$size.height=5000
	$Shell.BufferSize = $size
	Clear-Host
	# Chocolatey profile
	$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
	if (Test-Path($ChocolateyProfile)) {
	  Import-Module "$ChocolateyProfile"
	}

**Comment by DHowett** [comment]
Thanks!

```
$size = $Shell.WindowSize
$size.width=80
$size.height=25
$Shell.WindowSize = $size

$size = $Shell.BufferSize
$size.width=70
$size.height=5000
$Shell.BufferSize = $size
```

There’s your problem! Your powershell profile is enforcing the window size, which isn’t going to work properly in a multi-tabbed environment. Remove those lines and you’ll be fine.

(The traditional console already supports window and buffer size options; why does your profile set them manually?)

**Comment by leo-carmo** [comment]
> 
> 
> Thanks!
> 
> ```
> $size = $Shell.WindowSize
> $size.width=80
> $size.height=25
> $Shell.WindowSize = $size
> 
> $size = $Shell.BufferSize
> $size.width=70
> $size.height=5000
> $Shell.BufferSize = $size
> ```
> 
> There’s your problem! Your powershell profile is enforcing the window size, which isn’t going to work properly in a multi-tabbed environment. Remove those lines and you’ll be fine.
> 
> (The traditional console already supports window and buffer size options; why does your profile set them manually?)

Thanks DHowett! That's it!
I don't know for sure, but I might have changed the settings in the classic PowerShell/cmd window in the past. I remember those values 80 and 25, for example. That could have got written to my profile file.
