### ISSUE TITLE
Add new tab dropdown shortcut

### ISSUE THREAD

**Issue by TailyFair** [microsoft/terminal#7086]
# Description of the new feature/enhancement

As a user I want to have a keyboard shortcut to open new tab dropdown menu. I sometimes don't remember exact shortcut for specific tab profile (multiple SSH profiles), so opening new tab dropdown menu with shortcut and selecting correct SSH profile using up/down keys would be very convenient.

# Proposed technical implementation details (optional)

Add shortcut to toggle new tab dropdown list.

**Comment by KalleOlaviNiemitalo** [comment]
`openNewTabDropdown` is already bound to ctrl+shift+space by default, as documented in [Custom key bindings in Windows Terminal](https://docs.microsoft.com/windows/terminal/customize-settings/key-bindings#open-the-dropdown). It is not a "toggle", though.

**Comment by TailyFair** [comment]
Oh, I somehow missed it while skimming through docs...
