### ISSUE TITLE
PowerShell via Terminal blocks capital letters

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#7087]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

Try to print capital letters or Paste something like this in **Powershell**: `echo $Env:ProgramFiles`

# Expected behavior

![image](https://user-images.githubusercontent.com/17201690/88523406-9533d180-d000-11ea-89d2-bc1f88f08e49.png)

# Actual behavior

Capital letters don't print
![image](https://user-images.githubusercontent.com/17201690/88523366-80573e00-d000-11ea-818b-1a639f448f1c.png)

**Comment by zadjii-msft** [comment]
Will capital letters be printed if you try using <kbd>tab</kbd> autocomplete? 


Does setting `"experimental.input.forceVT": true,` in your settings fix this?

**Comment by lego963** [comment]
1. I didn't try to use `tab`
2. Nope, i dont use any exp features
3. In cmd capital letters were working fine
4. PS version: 5.1.19041.1

Sorry, now capital letters work. I don't know how and why.
I think it could be closed.
If I get full bug scenario I will reopen.

**Comment by zadjii-msft** [comment]
Great, thanks for following up!

**Comment by lego963** [comment]
Hi, i stuck again with same problem!

**Comment by bloodyearth** [comment]
I have same problem :/

**Comment by TrueBers** [comment]
Same problem here.
Appears randomly, only tab reopening fixes the issue.

**Comment by gamepirog** [comment]
I have the same problem sometimes. I didn't find out why and when it happens but I just switch input language in the powershell console and paste works fine.

**Comment by Gamzat** [comment]
Same issue on every windows PC which I have and had. You can't copy-paste capital letters into PowerShell, they will be deleted. Also you can input capital letter only by using Caps Lock. Shift + key combination doesn't work neither.

**Comment by vgdh** [comment]
I have the same issue.
If I close this PS window and open it again it works fine.

**Comment by josephswan** [comment]
Same issue. No capital letters using shift (caps lock works though).
Sometimes restart the app works, sometimes does not.

**Comment by ivanstepanovftw** [comment]
Same

**Comment by ivanstepanovftw** [comment]
@lego963 reopen please

**Comment by zadjii-msft** [comment]
@ivanstepanovftw What version of PsReadline are you using? From elsewhere in the repo: https://github.com/microsoft/terminal/issues/9450, https://github.com/PowerShell/PowerShell/issues/10794

> Also the issue was fixed in latest PSReadline preview version (2.0 Beta.5) and you can install it.

**Comment by schebotar** [comment]
1.11.2921.0 version from Windows Store is affected with capital Cyrillic letters.
Latin letters works fine

**Comment by schebotar** [comment]
I checked out all standard russian cyrillic layout.
I can't type capitals which I kept lowercase on screenshot below
![image](https://user-images.githubusercontent.com/51533848/144197016-f65fd1ab-f14a-40c3-823c-62974872581d.png)

**Comment by zadjii-msft** [comment]
@schebotar As described in https://github.com/PowerShell/PowerShell/issues/10794, you need to update PsReadline. This will be present in _all_ Terminal versions, because it's a PsReadline bug. 

You can find your current PsReadline version with 

```pwsh
$(Get-Module PSReadLine).Version
```

**Comment by DintonBQ** [comment]
Right click - bug, Ctrl+V - no bug
