### ISSUE TITLE
Updating via Microsoft Store app silently kills Windows Terminal and all shells running therein

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#7088]
# Environment

```
Windows build number: 10.0.19041.388
Windows Terminal version (if applicable): 1.1.2021.0 (version after update)

```

# Steps to reproduce

- Start Windows Terminal, with at least one tab (in my case, was running PowerShell 7.1 preview 5)
- Launch the "Microsoft Store" app
- Hit "Get Updates"
- let the updates run, including Windows Terminal's (might require hitting "Update all")

# Expected behavior

The update to Windows Terminal should be delayed until all tabs have been closed

# Actual behavior

Windows Terminal is forcibly closed, causing all shells therein (in my case, PowerShell was even running a script) to be killed

**Comment by Lo0oG** [comment]
Duplicate issue

- #6743
- #6726
- #3915

**Comment by zadjii-msft** [comment]
Yep, sure is!

/dup #3915 #6726 #6743
