### ISSUE TITLE
An Error is emitted when passing a path, containing spaces, to the "Target a directory" [-d] command line argument.

### ISSUE THREAD

**Issue by AceTheWiz** [microsoft/terminal#7090]
# Environment

```none
Microsoft Windows [Version 10.0.18362.959]
Windows Terminal Preview [Version: 1.2.2022.0]
```

# Steps to reproduce

Launch _Windows Terminal_ from the Start menu ```Win+R``` passing a path containing spaces as a parameter.

```console
wt -d c:\Program Files (x86)\Microsoft\
```
OR with the path enclosed in quotes.

```console
wt -d "c:\Program Files (x86)\Microsoft\"
```
# Expected behavior

_Windows Terminal_ should launch and open a _Tab_ running PowerShell with the current directory set to the supplied "Target directory", passed as a parameter. In this example the current directory, in PowerShell, should be set to ```c:\Program Files (x86)\Microsoft\```

# Actual behavior

_Windows Terminal_ opens and displays an error in a PowerShell _Tab_.

for the first case i.e. path without quotes.
```console
[error 0x80070002 when launching `Files (x86)\Microsoft\']
```
for the second case i.e. path with quotes.
```console
[error 0x8007010b when launching `powershell.exe']
```

The _Tab_ is not usable, iaw it does not respond to any user input.

**Comment by DHowett** [comment]
I can't reproduce this with 1.1 or 1.2. The key, however, is the `\"` at the end. The `\` is being used to escape the quote (and therefore corrupting the path). Either leave the `\` off or use `\.` :smile:

**Comment by AceTheWiz** [comment]
> I can't reproduce this with 1.1 or 1.2. The key, however, is the `\"` at the end. The `\` is being used to escape the quote (and therefore corrupting the path). Either leave the `\` off or use `\.` 😄

Great thanks it works. Was the only variation I didn't try.

**Comment by DHowett** [comment]
Happy to help! Thanks!
