### ISSUE TITLE
Add more warning dialog settings

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#7094]
# Description of the new feature/enhancement
Note: copied/split from @zadjii-msft's https://github.com/microsoft/terminal/issues/6549#issuecomment-646113805

Add a new setting boolean, `alwaysWarnCloseWindow` with default as false. 

# Proposed technical implementation details (optional)
Add a global setting to always warn the user when closing the window instead of only when there are multiple tabs (and in the future, warn multiple clients in panes (#6549), and warn multiple panes in when closing tab(#7077))

_If possible, I would like to implement this._

**Comment by Chips1234** [comment]
Ooh, actually this is a duplicate of #2976. Sorry

**Comment by DHowett** [comment]
/dup #2976 
thanks!
