### ISSUE TITLE
add size to terminal ?

### ISSUE THREAD

**Issue by ydainna** [microsoft/terminal#7096]
Good evening, sir.

I'm coming to you because I have a little problem with the view and I'd like to know if it would be possible to add a zoom feature on the terminal?

Thank you very much.

**Comment by DHowett** [comment]
If you hold down <kbd>Ctrl</kbd> and use the mouse wheel, the font will get bigger or smaller. Is that acceptable?

**Comment by ydainna** [comment]
Yes, but I think making a backup in the settings would be nice (for when we re-open the terminal once closed).

**Comment by DHowett** [comment]
If you want the font size to persist between sessions, you can just _set the font size in your settings._ Docs [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#font-size).

**Comment by ydainna** [comment]
okey thank you
