### ISSUE TITLE
Menu bar interaction points clicks do not work on 3440x1440 resolution

### ISSUE THREAD

**Issue by seangwright** [microsoft/terminal#7097]
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```
Windows Terminal version (if applicable): Version: 1.1.2021.0

Any other software?
posh-git, oh-my-posh, PowerToys 0.19.2

Displays: 
1) 3440x1440, 100% scaling
2) 1920x1080, 100% scaling

# Steps to reproduce

Open Windows Terminal on a 3440x1440 resolution display
Try to use any of the interaction points on the top Terminal bar (new tab, options, minimize, maximize, close)

# Expected behavior

Interactions work

# Actual behavior

Interactions do not respond to mouse clicks

![windows-terminal-resolution-issue](https://user-images.githubusercontent.com/1382768/88614650-2edd9c00-d05e-11ea-8282-5faae4f6073a.gif)

(yellow bubbles signify clicks)

# Notes

When I move the Terminal to my 1920x1080 display, everything works as expected. When I move it back to my 3440x1440 display, the menu interaction points do not work.

**Comment by DHowett** [comment]
Are you using PowerToys, or do you have it running in the background?

**Comment by seangwright** [comment]
Yup, I'm using PowerToys 0.19.2.

**Comment by DHowett** [comment]
If you exit it, does mouse input start working again?

**Comment by seangwright** [comment]
@DHowett Yup, closing PowerToys immediately made the bar interactive again and I could add new tabs/close ect...

It's weird - I'm noticing that sometimes there isn't an issue and sometimes there is, but the issue, when it does appear, is always on my 3440x1440 display.

**Comment by zadjii-msft** [comment]
Thanks for following up! I'm gonna mark this as a dup of #6120 since they seem to have the same root cause.

/dup #6120
