### ISSUE TITLE
Erroneous text formatting and wrapping after window resize

### ISSUE THREAD

**Issue by Alvin-Seville** [microsoft/terminal#7100]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version (if applicable): 1.1.2021.0

WSL is installed.
```

# Steps to reproduce
- Open Windows Terminal
- Open new Ubuntu tab:
![image](https://user-images.githubusercontent.com/42812113/88658388-f7d8ac00-d098-11ea-8e83-ee136fcde891.png)
- Try shrink window size:
![image](https://user-images.githubusercontent.com/42812113/88658432-0b841280-d099-11ea-87f1-2004fe9ab1af.png)

# Expected behavior
Normal text wrapping.

# Actual behavior
Text wrapping is broken after window shrinking.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3088 for more discussion.

/dup #3088
