### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by YChienHung** [microsoft/terminal#7101]
I must press second Backspace to delete a Chinese character，but  it should press only once

**Comment by zadjii-msft** [comment]
So I'm not sure if any of these are the same, but linking them up to save future us some time:
* #5054 
* #5110
* #5282

@YChienHung Which version of the Terminal are you using? Which version of Windows?

**Comment by YChienHung** [comment]
I'm sorry. I found it is a git-bash issue.

**Comment by zadjii-msft** [comment]
Oh, that's good to know! Thanks for following up.
