### ISSUE TITLE
OSC 12 cursor colour update doesn't appear to be working

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#7102]
# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.19041.388]`
Windows Terminal version: `1.2.2022.0` (Preview)

Any other software?
```

# Steps to reproduce

In a bash shell:

```bash
echo -e '\e]12;rgb:fd/f6/e3\e\'
```

I've confirmed that changing the 12 to a 10 correctly changes the text foreground colour, and 11 correctly changes the background colour.

I've also tried the same thing in PowerShell, with the same lack of effect.

```PowerShell
${ESC}=[char]27
Write-Host "${ESC}]12;rgb:fd/f6/e3${ESC}\"
```

I've tried both the default `cursorShape`, and the `filledBox` shape.

Changes to the `cursorColor` in the current scheme do take effect correctly.

# Expected behavior

The cursor should change from the theme-defined colour into the off-white background of Solarized Light.

# Actual behavior

Cursor colour does not change.

**Comment by zadjii-msft** [comment]
Weird, that _should_ be working. It looks like `SetCursorColor` was never implemented in `TerminalDispatch` 😧 

Maybe we shouldn't have `TerminalDispatch` extend from `TermDispatch`, so we know when we forget to implement a method in the Terminal side of things?

**Comment by TBBle** [comment]
Speaking of Easy Fixes, whoever picks this up might want to fix the comment on [`AdaptDispatch::SetCursorColor`](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/terminal/adapter/adaptDispatch.cpp#L2202-L2209), since it's currently a copy of the comment on [`AdaptDispatch::SetColorTableEntry`](https://github.com/microsoft/terminal/blob/76de2aedc2d805481ae323bba6f34cb41878a461/src/terminal/adapter/adaptDispatch.cpp#L2230-L2237).

**Comment by DHowett** [comment]
-triage +2.0 good call on "easy starter"
