### ISSUE TITLE
FR: Persist window location\size on close

### ISSUE THREAD

**Issue by sitefinitysteve** [microsoft/terminal#7103]
# Description of the new feature/enhancement

When I open terminal I move the window to a specific spot on a specific monitor, and resize.  However when the Terminal window\app closes and I re-open it resets back to the main monitor as a small(er) window (default I guess)

# Proposed technical implementation details (optional)

Simply persist the size and location on close and restore to where it was.  This is how my terminal on OSX works and it's fantastic.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22Persist+window%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766

**Comment by sitefinitysteve** [comment]
@zadjii-msft I did check, sorry guess I didn't get the terms right, never been so happy to have a duplicate issue :) Apologies!
