### ISSUE TITLE
Ctrl + Click -> open Paths/URLs

### ISSUE THREAD

**Issue by icavalheiro** [microsoft/terminal#7104]
# Description of the new feature/enhancement

Be able to "Ctrl + Click" in a URL/path inside the terminal and have it opened in default browser/explorer.
![image](https://user-images.githubusercontent.com/11912413/88701900-00ed6b80-d0e1-11ea-994d-a1bf7dc314c5.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+click+url) when filing new issues. This is already being tracked by another issue on our repo - please refer to #574/#204 for more discussion.

/dup #574 #204
