### ISSUE TITLE
Poor graphics rendering performance in Windows when Terminal is the foreground/active app

### ISSUE THREAD

**Issue by afefer** [microsoft/terminal#7108]
# Environment

```none
Windows build number: 10.0.19041.388
Windows Terminal version (if applicable): 1.1.2021.0
CPU: Ryzen 9 9300X
GPU: GeForce 2080 Ti
Monitor settings: 3840x1600 @ 144 Hz w/ Nvidia G-Sync enabled
```

# Steps to reproduce

1. Open Windows Terminal and ensure Terminal is the foreground (active selected) app.
2. Move mouse cursor OR shake Terminal to minimize all other apps on screen.

# Expected behavior

General rendering performance in Windows should not be affected by Terminal.

# Actual behavior

The mouse cursor appears slow/choppy when Terminal is in the foreground, and the problem immediately goes away when you click on another window to make Terminal no longer the foreground app. This problem not only affects the rendering of the mouse cursor, but other graphics as well (e.g. if you shake the Terminal window to auto-minimize all other open apps, the visual effects for the minimize action also appears sluggish).

Note this can also be repro'd when Terminal is minimized and the taskbar icon is clicked to restore the app - the visual effects for the restore action is sluggish.

**Comment by jack775544** [comment]
Almost certainly this issue https://github.com/microsoft/terminal/issues/649

Adding the setting `"experimental.rendering.software": true` is the recommended temporary workaround right now.

**Comment by afefer** [comment]
Yup, that looks like it. Thanks @jack775544 for the quick pointer to that bug. This can be closed as duplicate.

**Comment by DHowett** [comment]
Thanks everyone!
