### ISSUE TITLE
is there someway to start a SSH connection with password?

### ISSUE THREAD

**Issue by meteordragon** [microsoft/terminal#7109]
with WT ,i start ssh connection with 'ssh root@1.1.1.1' ,then wait to enter the password
and in xshell i can do it once for all: ssh://username:passwd@ip:port

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
You will need to set up a script that forwards the password into ssh.exe. You should not be doing this. You should be using SSH key authentication. It is more secure than storing a password in a configuration file.

Windows Terminal is not a dedicated SSH client, so it is not going to add support for storing your SSH password. You should be using SSH key authentication.
