### ISSUE TITLE
Open a file by Ctrl+Click-ing on the file location string 

### ISSUE THREAD

**Issue by stagefright5** [microsoft/terminal#7110]
# Description of the new feature/enhancement

If there is a file location (absolute or relative) string on terminal, `ctrl+click`ing on that location string will open the file in the default application for that file type.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22click+path%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #574 for more discussion.

/dup #574
