### ISSUE TITLE
I can't click, type, or close anything

### ISSUE THREAD

**Issue by Fcscanf** [microsoft/terminal#7112]
# Environment

```none
Windows build number: [run `[Win]::10 1909` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):1.2.2022.0

Any other software?
Window Notes
```

# Steps to reproduce
I opened up the Window Notes Tab, and he couldn't type anything, and then I shut him down, and then I opened him up again, and the Window Notes tab was working, and when I copied the tab to Terminal, he stopped moving, and he couldn't type anything, or even shut him down, except from the task manager. I had the same problem last time, but it wasn't triggered by the Window Notes Tab. Instead, I used Terminal to connect to four remote Linux hosts, and after four hours of inactivity, when I tried to use it, I couldn't do it or shut it down. What you are currently experiencing are two remote hosts, three powershells, two of which run the NPM command

# Expected behavior
![image](https://user-images.githubusercontent.com/27654200/88767802-b802e900-d1ac-11ea-8054-05f612ff8430.png)

# Actual behavior
I can't click, type, or close anything

**Comment by skyline75489** [comment]
This issue may be related to #7097 . Out of curiosity, are you using PowerToys?

**Comment by Fcscanf** [comment]
Yes，I’m using PowerToys?

**Comment by skyline75489** [comment]
I've actually run into the problem myself and guess what, I'm also having PowerToys running in the background. But it only happened once and I can not reliably reproduce it.

**Comment by Fcscanf** [comment]
Yes, my PowerToys is running, I rebooted the Terminal, and I'll try to shut it down next time, but, even though the problem is random and occasional, the solution is to restart the other one, there's enough tolerance for this kind of problem

**Comment by zadjii-msft** [comment]
Could you take a look at #6120? From that thread:

* Are you using the Terminal on a high DPI display? 
  - If so, and if possible, does dragging the window to a 100% scaling display magically restore mouse functionality to the Terminal?
* Similarly, are you using the Terminal on your primary display? 
  - If so, and if possible, does dragging the window to another display magically restore mouse functionality to the Terminal?
* Does the PowerToys settings app similarly not respond to mouse input?
* Do you have the Shortcut Guide enabled in PowerToys?
  - If so, does it actually work if you long press <kbd>Win</kbd>?
* By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

If you're experiencing this, and you can interact with the PowerToys settings app (you might need to drag it to another monitor), then
* can you fix the issue by disabling "Shortcut Guide" in PowerToys?

**Comment by Fcscanf** [comment]
@zadjii-msft ，yes,I'm  using the Terminal on a high DPI display,I'm not as bad as # 6120, just occasionally, just restart the Terminal, thank you
