### ISSUE TITLE
about dialog black mask size error

### ISSUE THREAD

**Issue by xcyl** [microsoft/terminal#7113]
![QQ图片20200729160637](https://user-images.githubusercontent.com/3195665/88774305-d8837100-d1b5-11ea-91ec-f109cc19cb89.png)

**Comment by skyline75489** [comment]
Is #2380 what you trying to describe?

**Comment by xcyl** [comment]
> Is #2380 what you trying to describe?

Yes, it looks like the same problem.

**Comment by skyline75489** [comment]
Thanks for the report. I'll close this in favor of #2380 for now. 

/dup #2380

**Comment by zadjii-msft** [comment]
@skyline75489 we really should configure the bot to obey you too 😝 

@miniksa can we get him dupe powers?

(also, /dup #2380)

**Comment by skyline75489** [comment]
Oh the bot is ignoring me. Well at least I tried.

**Comment by DHowett** [comment]
@zadjii-msft i actually did give him triage powers. Apparently the bot isnt happy about that! Sorry :)
