### ISSUE TITLE
Dropdown mode

### ISSUE THREAD

**Issue by Serkonda** [microsoft/terminal#7114]
# Description of the new feature/enhancement
Often I only want to quickly type one or two commands. It's a lot of overhead to open the terminal and close it afterwards to not fill my taskbar.

# Proposed technical implementation details (optional)
Therefore I suggest implementing a dropdown-mode similar to KDE's Yakuke.
The terminal should be expandable by pressing a keyboard shortcut.
To close it either press it again or click outside the terminal.

**Comment by KalleOlaviNiemitalo** [comment]
Seems to be a duplicate of <https://github.com/microsoft/terminal/issues/6051> and <https://github.com/microsoft/terminal/issues/653>.

**Comment by Serkonda** [comment]
Agree, will close it
