### ISSUE TITLE
Add an option to disable the Windows menu on alt+space in Terminal

### ISSUE THREAD

**Issue by nwn** [microsoft/terminal#7125]
# Description of the new feature/enhancement

This is in some sense the opposite feature from #5833: I'm requesting an option to _not_ open the Windows menu when `alt+space` is pressed.

I have until now been working with WSL from the Powershell terminal, where the `alt+space` shortcut to open the Windows menu is disabled. This is convenient since I have `alt+space` mapped as a shortcut in several WSL applications (such as screen/tmux prefixes), but it no longer works when switching to Terminal.

The usual way of unbinding keys doesn't seem to do anything here:
```
{ "command": "unbound", "keys": "alt+space" }
```
It would be nice to have some way of unbinding this in Terminal.

**Comment by DHowett** [comment]
Fair enough. Thanks for the request!

**Comment by FWest98** [comment]
I have a similar usecase: I would like to associate <kbd>Alt</kbd> + <kbd>Space</kbd>to a command (tab search to be specific). This works, but the system dialog also still shows up. In Visual Studio and JetBrains-IDEs, this is prevented. So it would be nice if the system dialog no longer shows up when these keys are associated with a command.
