### ISSUE TITLE
issue with control characters appearing in command window

### ISSUE THREAD

**Issue by manbearian** [microsoft/terminal#7126]
suddenly my command window starting show control characters instead of doing the actions (e.g. image shows pushing the up arrow on the keyboard and then the down arrow). Other shells/tabs in the same terminal window don't have this issue.

![image](https://user-images.githubusercontent.com/25087458/88950899-23e75f00-d24a-11ea-8e24-81d33d989ffd.png)

Unfortunately i don't have a repro, and i don't know how i got into this state. I have a DMP of WIndowsTerminal.exe if that helps.

**Comment by DHowett** [comment]
So, this is usually caused by an application leaving `ENABLE_VIRTUAL_TERMINAL_INPUT` enabled when it exits. The input state is, unfortunately, global for a given console session (in Terminal, that's the tree of processes under one terminal pane)... which means applications can trivially mess with eachother like this.

**Comment by manbearian** [comment]
thanks for the quick response; is there an manual fix i can run? i'd love to save this terminal session :)

**Comment by DHowett** [comment]
Hmm.. so, if you just run `powershell` and then exit it, it should restore the input mode. I just gave that a shot over here.

**Comment by manbearian** [comment]
Btw, now that i can get my history for that shell, i believe that the culprit is vi. the last few previous commands were `git diff` invocations.

**Comment by DHowett** [comment]
Thanks for that! Yeah, it'll do that sometimes. Sorry :smile:

For this one, by-design is appropriate, even though that's a little unfortunate. We're kicking around the idea of making the input mode per-process state, but our input queue is appalling right now. I tried to hack this up for hackathon!

/dup #4954
