### ISSUE TITLE
Vim Starts in Replace Mode Randomly

### ISSUE THREAD

**Issue by rsynnest** [microsoft/terminal#7128]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.2.2022.0 (Preview Build)
WSL2 Debian or Ubuntu
```

# Steps to reproduce

1. Open a Debian or Ubuntu WSL2 instance in a Windows Terminal 
2. Open vim and it will sometimes open in REPLACE mode. This happens seemingly at random, so you may need to quit and reopen vim a few times until you see the `--REPLACE--` on the bottom left.
3. I've reproduced the same behavior over SSH on various systems running different versions and flavors of Linux with various vanilla or custom `.vimrc` files. This behavior is not reproducible in other terminal emulators (specifically MobaXterm). This behavior also does not appear to affect Neovim in Windows Terminal.

# Expected behavior

vim opens in Normal mode every time.

# Actual behavior

vim randomly opens in Replace mode sometimes.

**Comment by DHowett** [comment]
Thanks for the report! This is https://github.com/microsoft/terminal/issues/1637, which is marked an external tracking bug for win32-openssh. Unfortunately, the SSH client shipped with Windows is emitting an unusual or unexpected sequence in reply to Vim. More info at https://github.com/microsoft/terminal/issues/1637#issuecomment-663865934.

/dup #1637
