### ISSUE TITLE
Command Palette Doesn't Show up 

### ISSUE THREAD

**Issue by sumanth-vs** [microsoft/terminal#7132]
# Environment

Microsoft Windows [Version 10.0.19041.329]

Windows Terminal version (if applicable): 1.1.2021.0

# Steps to reproduce

 - Add    { "command": "commandPalette", "keys": ["ctrl+shift+p"] }   to the keybindings 

# Expected behavior

- Command Palette shows up

# Actual behavior

- ^P gets printed on the terminal -->> Command Palette Does not show up.
- In fact, Command Palette does not seem to be working for any key combinations ( I tried shift+P, ctrl+p, etc)

**Comment by zadjii-msft** [comment]
The Command Palette isn't in 1.1, it's in Windows Terminal **Preview** currently, version 1.2
