### ISSUE TITLE
The rounded bottom corner on a tab doesn't get colored by the color picker

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7133]
![image](https://user-images.githubusercontent.com/18356694/89040985-3a54ef80-d30a-11ea-9ead-06e84b8c8d27.png)

_enhance.gif_:
![image](https://user-images.githubusercontent.com/18356694/89041160-856f0280-d30a-11ea-99e2-a3cc0d0af5a5.png)

Probably regressed when we ingested the latest MUX that included the rounded corners. I'm _hoping_ that we don't need to get this updated in MUX itself, and we can just set some other key on the TabViewItem ourselves.

**Comment by DHowett** [comment]
One more reason to ask MUX to add tab item backrounds for us. :smile:

**Comment by mdtauk** [comment]
Is there not a "light weight" style you can override?

**Comment by DHowett** [comment]
No. TabView was not designed with this use case in mind.

**Comment by Adrian94F** [comment]
It looks familiar when using light theme in Windows:
![a](https://user-images.githubusercontent.com/9122153/97273398-978e0d80-1833-11eb-88e6-1e045187d3d1.png)
