### ISSUE TITLE
Reduce brightness of unfocused panes

### ISSUE THREAD

**Issue by Ennea** [microsoft/terminal#7135]
# Description of the new feature/enhancement

To allow users to quickly tell at a glance which pane currently has focus, in addition to the accent colored border, it would be nice to reduce the brightness of all the unfocused panes. Terminator does this as well:
![Terminator reference screenshot](https://i.imgur.com/rlJ6ZFG.png)

In Terminator, only the colors are adjusted (and not even all of them, as you can see from the background color still being the same everywhere). In Windows Terminal, considering the support of background images and all that other nifty stuff, just straight up adjusting the brightness of everything in unfocused panes might be a good idea.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3062 for more discussion.

/dup #3062

**Comment by Ennea** [comment]
Oh snap, you're right. Apologies, I didn't find that ticket when searching.

**Comment by zadjii-msft** [comment]
No problems! That one's not the most discoverable 😜
