### ISSUE TITLE
Overwrites Settings

### ISSUE THREAD

**Issue by ivannp** [microsoft/terminal#7137]
# Environment

```none

 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

```

# Steps to reproduce

Editing the settings while I have terminals open. At some point, when I hit Ctrl-S in the editor to save the file, my settings went back to the default - lost all my changes.

# Expected behavior

Ctrl-S saves the settings in front of my face, not some defaults.

# Actual behavior

Editing the settings while I have terminals open. At some point, when I hit Ctrl-S in the editor to save the file, my settings went back to the default - lost all my changes. I have the editor and the terminal open for a bit.

**Comment by DHowett** [comment]
Which text editor are you using? We may be a little overzealous in how we reload settings from disk, and we might be hitting the settings file while the editor is still saving and finding it empty.
