### ISSUE TITLE
Ability to bind "applications" key

### ISSUE THREAD

**Issue by simonratner** [microsoft/terminal#7144]
# Description of the new feature/enhancement

Ability to create key bindings for the "applications" (a.k.a. "menu") key found on many modern keyboards.

# Proposed technical implementation details (optional)

Add a new recognised key <kbd>app</kbd>, allowing the following:
```
{ "command": "openNewTabDropdown", "keys": "app" }
```

**Comment by zadjii-msft** [comment]
If this key is just `VK_APPS`, that should be fairly trivial


Constant/value | Description
-- | --
VK_APPS 0x5D | Applications key (Natural keyboard)
