### ISSUE TITLE
Terminal: Support keyboard text selection & navigation

### ISSUE THREAD

**Issue by MarkusAmshove** [microsoft/terminal#715]
Hello,

I'm using tmux on Linux machines and ConEmu on Windows machines and I really love that I can do text selection with the keyboard.

In ConEmu, there is a keybinding for "Start text selection (like text editors)", whereas in tmux there is the same thing with `<prefix><b>` (I think that is default), where I get a cursor that I can move with the arrow keys around the console window.
While doing this, I can select text while holding shift and (in case of ConEmu) press ENTER to copy the text into the clipboard and end the text selection.
It can also be compared with Vim's visual mode.

It would be nice if the new Windows Terminal could support this out of the box, so I can use it in e.g. PowerShell :-)

**Comment by zadjii-msft** [comment]
@carlos-zamora this may be of interest

**Comment by danthe1st** [comment]
Also, if the tmux property _mouse-mode_ does not work in the new Terminal.
It works well in conhost.

**Comment by kuesa** [comment]
One possible implementation would be just to do what cmd does, where if the user has selected text and presses "Enter", it will just copy the selected text to the clipboard.

**Comment by danthe1st** [comment]
Or maybe it would be possible to let the application running control what's happening when marking...
Or that the user can change between the "cmd mode" and other things

**Comment by mdtauk** [comment]
If keyboard text selection is added, please don't forget about things like Shift+Home and Shift+End.

You could also have a selection go up and down a line/row with Shift+Up and Shift+Down.

Oh and with all these ligatures, copying and pasting text should probably uncombine those ligature characters - so the font choice does not affect what may get pasted in another place.

**Comment by carlos-zamora** [comment]
Added the "Help-Wanted" label. Most of this work should be able to go in `TermControl` (probably `KeyDownHandler()`). If the selection is active, edit the `Terminal`s `_endSelectionPositionAnchor` by using `_terminal->SetEndSelectionPosition(terminalPosition);`

`Terminal`s `_ExpandWideGlyphSelectionLeft()` and `_ExpandWideGlyphSelectionRight()` can be used to expand the selection on wide glyphs appropriately. We'd just have to make them public or have something else call them.

**Comment by RichardSlater** [comment]
Terminal is slowly driving me crazy because unlike ConEmu pressing <enter> clears the selection without copying it to the clipboard, having full-on keyboard only text selection would be a massive addition.

**Comment by pingzing** [comment]
One fun wrinkle--PSReadLine handles buffer selection and navigation for Windows PowerShell and PSCore. So if this does get implemented, there should also be an option to disable it per-profile, so a shell can handle selection itself.

**Comment by MarkusAmshove** [comment]
@pingzing I'm also using PSReadLine, but I'm unaware of the feature. Can you give me a hint? (can't find any documentation on this).

What I'm talking about in this issue is the following (beware awesome screencapturing):

![4urdJqAMlL](https://user-images.githubusercontent.com/2401875/62821852-babf9500-bb7b-11e9-9a83-a599a5b79384.gif)

**Comment by pingzing** [comment]
I think it only works for the input buffer, and not previously-written text. No idea if it's documented, but it's definitely in the keybindings. For example, invoking `Get-PSReadLineKeyHandler` yields the following for me:

```
Selection functions
===================
Key                   Function            Description
---                   --------            -----------
Ctrl+a                SelectAll           Select the entire line. Moves the cursor to the end of the line
Shift+LeftArrow       SelectBackwardChar  Adjust the current selection to include the previous character
Shift+Home            SelectBackwardsLine Adjust the current selection to include from the cursor to the end of the line
Shift+Ctrl+LeftArrow  SelectBackwardWord  Adjust the current selection to include the previous word
Shift+RightArrow      SelectForwardChar   Adjust the current selection to include the next character
Shift+End             SelectLine          Adjust the current selection to include from the cursor to the start of the line
Shift+Ctrl+RightArrow SelectNextWord      Adjust the current selection to include the next word
```

**Comment by xoofx** [comment]
> One possible implementation would be just to do what cmd does, where if the user has selected text and presses "Enter", it will just copy the selected text to the clipboard.

I completely agree. I'm hitting this issue several times a day with Windows Terminal. After using cmd and ConEmu for years, I have been always using copy from text selection by pressing "ENTER", but the fact that Windows Terminal doesn't replicate that existing behavior is quite a burden so far. I'm constantly loosing my selection by pressing enter while I should not but use right mouse click. I really love Windows Terminal, but the missing legacy behavior of "ENTER" for copy is really hurting my productivity (I'm probably also starting to feel old that my brain is not able to quickly adapt to the new mouse right click, but that's a different story! 😅)

Is there any implementation problems to allow "ENTER" on copy - even if it is not the default but we can turn it on via config?

**Comment by MarcoRossignoli** [comment]
I agree with @xoofx on all.

**Comment by bitcrazed** [comment]
Also asked-for here: https://twitter.com/Larswa/status/1203458135245107206

**Comment by jayallen** [comment]
> Is there any implementation problems to allow "ENTER" on copy - even if it is not the default but we can turn it on via config?

If you're going to support it, please do not add **_only_** copy on ENTER.  I cannot stand that. BUT, since others swear by it, and everyone either _loves_ or _hates_ each possibility, there is only one solution:  **Leave it to the user!**

Given that you have already enabled a way to control copy/paste, I assume I don't need to say this but because it will make a difference in whether people continue to use and even love Windows Terminal.

**Bonus points for also supporting mouse buttons** (e.g. middle and custom specialty buttons) with or without modifier keys (shift+button to copy, button to paste).  Again, unlock the possibilities and leave it to the user to customize.  <3

**Comment by daler-rahimov** [comment]
It would be great to have text selection movement configurable. For example if someone want to configure it as in VIM's visual mode ('w' for word forward, 'b' for backsword ...)

**Comment by zadjii-msft** [comment]
We're not planning on adding <kbd>enter</kbd> as copy by default. The user is absolutely free to add that keybinding if they'd like though.

Configuring what the mouse buttons do is currently tracked by #1553.

**Comment by mahmoudajawad** [comment]
I see @cinnamon-msft set this for v2. Any expectations on when we can see v2 even as beta? A rough estimate would be fine.

**Comment by danthe1st** [comment]
![image](https://user-images.githubusercontent.com/34687786/95051877-46847100-06ee-11eb-8da7-f2bf6494a2cb.png)
> Due by May 31, 2021

**Comment by zadjii-msft** [comment]
@mahmoudajawad We basically release features as they're developed. When we say this is in the 2.0 milestone, that just means we want to get to it before 2.0 ships, sometime next year. When there's a more concrete timetable, we'll update the milestone accordingly (e.g. if it's going to land in the 1.6 release, we'll move it to that milestone).

**Comment by mrxdkox** [comment]
I'm used to press "Shift + Arrow" (+Ctrl to jump words or Home, End, PgUp, PgDn) keys, what allow me to instantly select any text in terminal window and "Ctrl+C/Ctrl+V" to copy/paste in a very simple and fast manner (like in any text editor). 

That behavior is available in ConEmu. And it's common keyboard shortcuts behavior in all [CUA](https://en.wikipedia.org/wiki/IBM_Common_User_Access) appliactions what is majority in Windows, Linux, MacOS (basicaly almost every [GUI](https://en.wikipedia.org/wiki/Graphical_user_interface) app). 

It would be great to use same hotkeys for all apps on ones pc - less overhead about keyboard shortcuts more concentration on work. It would be even greater to have this in Windows Terminal.

**Comment by sinapis** [comment]
Shift + Arrow / Home / End is working in Powershell but not for WSL. When I hit Shift + Home / End in WSL this sequence is pasted: [1;2H and [1;2F respectively.

Is there a way to configure WSL the work the same as Powershell?

**Comment by zadjii-msft** [comment]
@sinapis I'm pretty sure that's just how `bash` works. PowerShell manually handles the <kbd>shift+home</kbd> keys to highlight text, while `bash` doesn't know how to handle then, and just echos part of the keys to the input line. From some [simple searching](https://www.google.com/search?client=firefox-b-1-d&q=bash+select+text+with+keyboard), it looks like this is a tricky issue with linux shells: [here's one post](https://askubuntu.com/questions/302263/selecting-text-in-the-terminal-without-using-the-mouse), [here's another](https://stackoverflow.com/questions/1536757/selecting-text-in-terminal-without-using-the-mouse). 

Frankly, both of those don't seem to list any solutions I'd be happy with, so I think your best bet would be to wait for this to land, so the Terminal can take care of this for you 😉

**Comment by ofek** [comment]
Has this been implemented yet?

**Comment by zadjii-msft** [comment]
@ofek Nope. This issue is still open, the spec (#2840) is still in review, and the PR (#3758) is still open. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by AspireOne** [comment]
So what's the progress on this after 3 months?

**Comment by zadjii-msft** [comment]
As you can see, we haven't posted any updates since the last time someone asked. The team has been busy on other tasks (specifically, the settings UI). When there are updates, there will be comments made here, or on the spec in #2840, or in the PR in #3758.

**Comment by sheikki** [comment]
> 
> 
> As you can see, we haven't posted any updates since the last time someone asked. The team has been busy on other tasks (specifically, the settings UI). When there are updates, there will be comments made here, or on the spec in #2840, or in the PR in #3758.

You have really weird priorities. This feature should have been there from the very start. It's even more infuriating because there is some bug that makes mouse text selection extremely slow/laggy after Windows Terminal has been running a few days..

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/113185000-80f14580-921b-11eb-86c0-6a5cffe6f1c3.png) vs ![image](https://user-images.githubusercontent.com/18356694/113185037-8e0e3480-921b-11eb-9d73-4d744881aebb.png)

I serve at the pleasure of the community, and the community feels that the settings UI is a higher priority. 

<hr>

That being said, we had a team discussion _literally two days ago_ about resurrecting the simple selection part of this (without finalizing the "mark mode" bits) sooner than later. Both are unanimous ship-blockers for 2.0, if that's any consolation.

**Comment by ofek** [comment]
When is v2.0 expected?

**Comment by sinapis** [comment]
> When is v2.0 expected?
31-12-2021

https://github.com/microsoft/terminal/blob/main/doc/terminal-v2-roadmap.md

**Comment by ofek** [comment]
Has this been implemented/released in a preview build?

**Comment by spookyrecharge** [comment]
I can't believe this is taking so long

**Comment by MrM40** [comment]
If/when this is implemented I hope it will be an option! I've build in my own functionality in my application (CTRL+C, CTRL+V, CTRL+X, text-selection with SHIFT+ARROWS,  SHIFT+HOME, SHIFT+END etc). I would be unhappy if my hard work gets corrupted by an native implementation....so please make it possible to disable it in settings. 

It's a real pain in the Windows legacy console (in advance mode).....the text-selection is forced so pushing e.g. SHIT+HOME is captured by the console and are not parsed on to the application, please don't make same mistake.

**Comment by MrM40** [comment]
Ohh....hard to keep up with speedy team :-)

I'm running 1.15.220719002-preview

Don't have any text-selection functionality in the default "Command Prompt" profile, it works in the profile "Windows PowerShell" 
They have the same settings:
![image](https://user-images.githubusercontent.com/16258063/187672906-d932ee5d-317f-4ab2-8390-05be263ee4b0.png)

Should it work in the cmd prompt too?

**Comment by zadjii-msft** [comment]
>  it works in the profile "Windows PowerShell"

PowerShell has its own text selection it maintains, as a part of the shell itself. You'll note that PowerShell's text selection works the same in 1.15 as it did in previous versions, even the same as it did in the vintage console. 

The text selection added in the Terminal needs to be started first, either with a keyboard selection, or the `markMode` action (bound to <kbd>ctrl+shift+m</kbd> by default).

**Comment by MrM40** [comment]
OK, I see. Expected it to work the same was as in legacy console in advance mode, where it just work natively (but make it impossible to make you own implementation, as e.g. SHIFT-LEFT never get parsed to your application).
I'm very happy with the way WT implemented this.

**Comment by cool-RR** [comment]
@carlos-zamora  Two years after this feature was implemented, I want to say that it's an absolute joy. This was the one thing that prevented me from using Microsoft Terminal, and now I use it so often. Thank you so much for implementing it.

**Comment by myudak** [comment]
is this already supported? i cant use it

**Comment by OZ1** [comment]
> is this already supported? i cant use it

Did you press Ctrl+Shift+M as zadjiiii mentioned?

**Comment by Gercius** [comment]
> > is this already supported? i cant use it
> 
> Did you press Ctrl+Shift+M as zadjiiii mentioned?

Ctrl+Shift+M is nearly useless. Using zsh with zsh shift select is a decent alternative https://github.com/jirutka/zsh-shift-select

**Comment by cool-RR** [comment]
@Gercius Why is Ctrl+Shift+M "nearly useless"? I use it often with great success.

**Comment by Gercius** [comment]
@cool-RR I think I stand corrected and commenting on the wrong issue, since I use windows terminal with WSL, which is a little different experience than the default terminal usage, and manipulating text is more painful.

**Comment by cool-RR** [comment]
I also use Windows Terminal in WSL and Ctrl Shift M works perfectly there for me. What's not working well there for you?

**Comment by Gercius** [comment]
@cool-RR Simple things like cutting text, pressing backspace to delete selected text. I'm using zsh shift select and it seems like it's the best of both worlds, marked for selecting text that you can't with zsh shift select, and zsh shift select for text manipulation.

**Comment by cool-RR** [comment]
@Gercius I've now been using `zsh-shift-select` for a while and it's pretty cool. Thanks for recommending.
