### ISSUE TITLE
Keyboard does not work in the console

### ISSUE THREAD

**Issue by authorless** [microsoft/terminal#7150]
Hello. Recently I've had such a problem that when I press the keyboard, nothing happens. I reinstalled the Terminal many times, didn't help. I even decided to download the pre-release version, but it wasn't successful either. I've downloaded all versions exclusively from the Microsoft Store. Please help me to fix my problem...

**Comment by zadjii-msft** [comment]
Could you check out #4448 and see if that thread helps workaround this issue?

**Comment by xCONFLiCTiONx** [comment]
I came here with the same issue and https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424 is what fixed it for me.
