### ISSUE TITLE
Opacity Controls

### ISSUE THREAD

**Issue by Trent-Farley** [microsoft/terminal#7151]
# Description of the new feature/enhancement
Hello! 
I just want to say this team is doing fantastic work and is very inspiring. The feature that I am proposing is adding controls for opacity to the terminal. The same controls for opacity can be seen in PowerShell and command propmpt. 

This new feature would allow users to personalize their terminal while still being able to see the underlying window. 
# Proposed technical implementation details (optional)

Adding controls for opacity in windows terminal.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #603 for more discussion.

/dup #603
