### ISSUE TITLE
Keyboard commands like backspace or left/right don't account for Zero Width Joiner (ZWJ) unicode in emoji

### ISSUE THREAD

**Issue by SkylerA** [microsoft/terminal#7153]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

New Terminal w/ a ubuntu wsl tab opened
```

# Steps to reproduce

1. Open New Terminal
2. Open a Ubuntu Tab
3. Press Win + . to bring up the emoji selector
4. Select the "Hacker Cat" or any emoji that is a composite of multiple unicode characters
_The hacker cat emoji should now be in the terminal w/ the input cursor behind it_
5. Press left twice
_note that the terminal moved the cursor 2 times even though there is 1 displayed emoji_
6. Press enter
7. Press up to bring back the hacker cat emoji
8. Press backspace once
_note that the emoji has changed to just a cat instead of erasing the entire emoji_
9. Press enter
10. Press up twice to bring back the hacker cat emoji
11. Press backspace twice
_note that the emoji changes from a hacker cat to a regular cat emoji and finally to a smaller cat emoji w/ the input cursor down the middle of it_
_note that pressing backspace or arrow keys will ignore the cat emoji_
12. Hit enter
_note that even though a cat was still in the terminal line, the terminal input command was recorded as blank_

# Expected behavior
1 character commands like backspace or left/right should treat composite emoji as 1 character

# Actual behavior
It appears the terminal is treating each modifier emoji in a composite emoji as an individual character. As far as i understand it, emoji start w/ a base emoji (the cat emoji) and then are modified by adding the [ZWJ](https://emojipedia.org/emoji-zwj-sequence/) character and then adding unicode that modifies the previous unicode. My guess is when you do a backspace or left, you need to look and see if the previous character is a unicode ZWJ(there might be other types of modifiers to support in unicode as well, no sure) and if it is, keep parsing until you read a unicode character that isn't proceeded by a ZWJ.

**Comment by KalleOlaviNiemitalo** [comment]
I suspect the backspace behavior is implemented not by Windows Terminal but by the shell (e.g. Bash) you're using in Ubuntu.

**Comment by zadjii-msft** [comment]
🐱‍💻

Yea, the emoji support isn't exactly right quite yet. There's #190 and #1472 which I _think_ should cover this scenario. Someone on the team can overrule me if they want, but I _believe_ this will be fixed when we get to finishing those.

/dup #190
/dup #1472
