### ISSUE TITLE
Allow command color customization

### ISSUE THREAD

**Issue by mrbiggfoot** [microsoft/terminal#7154]
Right now, all commands are colored with "brightYellow" color from the color scheme. It may look like this, which is not ideal for a white background scheme:
![image](https://user-images.githubusercontent.com/12175496/89135621-a179cc00-d4e3-11ea-8102-46237e92d955.png)
I honestly tried searching for a solution, but found nothing except "brightYellow" redefinition. I think a cleaner way would be to allow setting the command color to any color from the scheme, e.g. "commandColor": "blue". Or even allow direct \#rrggbb color setting.
Apologize if it is something that can be done already, in that case can someone please post the solution? Thanks!

**Comment by KalleOlaviNiemitalo** [comment]
[Set-PSReadLineOption](https://docs.microsoft.com/powershell/module/PSReadline/Set-PSReadlineOption?view=powershell-5.1#parameters) -Colors @{ Command = _something_ }

**Comment by mrbiggfoot** [comment]
Thanks @KalleOlaviNiemitalo !
