### ISSUE TITLE
add windows ui setting

### ISSUE THREAD

**Issue by zhangxd** [microsoft/terminal#7155]
add windows ui setting, not edit json file

**Comment by skyline75489** [comment]
There is #1564 for this.

Let's see if the bot's having a good mood.  /dup #1564 

And @zadjii-msft I feel that the dup bot in VSCode repo we once talked is actually not a bad idea. I mean why not. Using another bot to fix the current bot. What could go wrong.

**Comment by zadjii-msft** [comment]
Yea, this is definitely being tracked in #1564.

/dup #1564

@skyline75489 Honestly, I emailed the VsCode team and got access to the dupe detection bot source, but the documentation wasn't straight forward, and I don't really have a lot of experience setting up docker containers nor do I have any experience with ML, so I kinda abandoned it. After seeing all these dupes this morning though, I'm gonna probably reopen that thread and see if we can't get that set up
