### ISSUE TITLE
Open new window if tab pulled out of top bar

### ISSUE THREAD

**Issue by Venipa** [microsoft/terminal#7156]
# Description of the new feature/enhancement
Open new window if tab pulled out of top bar
![example](https://i.mavis.moe/f/wZbMBQbuCG/2020-08-03-09-59-16gif.gif)

# Proposed technical implementation details (optional)
On pulling out the tab of the window it should create a new Window with the pulled context/history

**Comment by KalleOlaviNiemitalo** [comment]
See "tab tearoff" in <https://github.com/microsoft/terminal/issues/1256>.

**Comment by zadjii-msft** [comment]
Yep, this is #1256. Thanks!

/dup #1256
