### ISSUE TITLE
Windows Terminal error 0x800700c1 when launching `powershell.exe' 

### ISSUE THREAD

**Issue by dwram** [microsoft/terminal#7160]
# Environment

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable): The latest as of this posting. No clue how to be certain.I believe  v1.0.1401.0 

Any other software?

# Steps to reproduce

1. Downloaded 64bit NodeJs with npm (with all required dependancies including chocolatey packages, which forcefully installed python 3.8 despite already having python) from **https://nodejs.org/** in Powershell (Terminal)
2.  `npm install -g javascripting` ran this command in Powershell (Terminal ).
3. Tried to run **Javascripting**. Was failing due to some Powershell scripting security error. 
4. Ran commands on https://www.opentechguides.com/how-to/article/powershell/105/powershel-security-error.html via Terminal (Powershell). Commands used were `powershell.exe -executionpolicy -bypass` `Unblock-File -Path C:\Downloads\script1.ps1`
5. Restarted terminal
6. Powershell is default shell: [error 0x800700c1 when launching `powershell.exe']
7. Have tried playing around with adding new PATH (system and user) to my folder containing Python3.exe to no avail!

A description of how to trigger this bug.

1. Open up Windows Terminal (Powershell)

# Expected behavior

1. Working Windows Terminal (Powershell)

A working powershell. Whereas I can actually use it in Windows Terminal.

# Actual behavior

<img src="https://i.gyazo.com/b8089b85b7ac5754c038b1bf7a1ba4ad.png">

"[error 0x800700c1 when launching `powershell.exe']"

extra: Path information

![image](https://user-images.githubusercontent.com/64813795/89199386-5f658e80-d5a6-11ea-9591-76d206d7668d.png)

**Comment by zadjii-msft** [comment]
As a quick sanity check:
if you add a new custom profile that _hardcodes the path to Windows PowerShell_... does it work?

```json
{
	"name": "PowerShell Test",
	"commandline": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

**Comment by dwram** [comment]
> As a quick sanity check:
> if you add a new custom profile that _hardcodes the path to Windows PowerShell_... does it work?
> 
> ```json
> {
> 	"name": "PowerShell Test",
> 	"commandline": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
> }
> ```

![image](https://user-images.githubusercontent.com/64813795/89199912-30035180-d5a7-11ea-96db-5a13fa57409c.png)

Yes it seems to work. How do I rectify this so I don't need the "fake" test powershell?

**Comment by DHowett** [comment]
For the quickest/easiest fix, delete the entire line containing `commandline: powershell.exe` (38) in your settings. Terminal will fall back to the "default" value (which is specified in another file), which we changed with #6684.

Thanks for troubleshooting with us!
