### ISSUE TITLE
Start a tab as admin

### ISSUE THREAD

**Issue by hanahige** [microsoft/terminal#7169]
# Description of the new feature/enhancement
Please create an option to create a new tab running as admin.  I don't currently see a way to start a new tab running as an administrator, but I would love having one terminal window with multiple tabs at different elevation, rather than opening an entirely new window.  I realize there's a use-case for having a window of admin tabs and a window of normal tabs, however I think the flexibility of opening an admin tab in a single window would be helpful.  With the new tab dropdown menu, if the option to run as admin were available with a right click on the tab type, that would be great.  Maybe an Alt+Shift+# hotkey option?

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
I think this is covered in #1032 if I'm not mistaken.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22admin%22+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1032 for more discussion.

/dup #1032 #632 #5000
