### ISSUE TITLE
A GUI for editting settings

### ISSUE THREAD

**Issue by Destroyer-LDB** [microsoft/terminal#7170]
# A GUI for editting settings

Well, I have worked with config files before ( also JSON ). It is the settings.json of Visual Studio Code. But VSC has a GUI page for the ''Settings'' command. When I clicked the ''Settings'' in Windows Terminal for the first time, I felt surprised because no settings window showed in my screen, but a VSC window opening the settings.json. Though I know how to write in JSON files, I still felt uneasy to edit settings in a JSON file. If Windows Terminal could have a GUI for editting settings, it would be easier for beginners to use. What's more, not everyone has a text editer for JSON, and if the settings.json is opened as plain text, it will be hard to read.
I hope Windows Terminal can have a GUI for editting settings.

**Comment by skyline75489** [comment]
We have #1564 for this. There are many related discussion and designs in that issue you may find interersting.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22settings+gui%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1564 for more discussion.

/dup #1564

**Comment by Destroyer-LDB** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chester Liu"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 中午1:49
收件人: "microsoft/terminal"<terminal@noreply.github.com&gt;; 
抄送: "私は党博"<3041653369@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/terminal] A GUI for editting settings (#7170)





 
We have #1564 for this. There are many related discussion and designs in that issue you may find interersting.
