### ISSUE TITLE
azerty keyboards: unavailable characters

### ISSUE THREAD

**Issue by gpotter2** [microsoft/Terminal#718]
Some characters are unusable when the keyboard used it AZERTY, which is quite a bummer
Here's the AZERTY layout:

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/1024px-KB_France.svg.png)

- **Characters that use [ALT-GR]+[something] are unusable**. For instance, If I try to make a pipe (`|`), it's [ALT-GR]+[6]. This will instead do
![image](https://user-images.githubusercontent.com/10530980/57581691-3e091600-74bb-11e9-8fe9-fa6a46a0f180.png)
vs in cmd:
![image](https://user-images.githubusercontent.com/10530980/57581706-6e50b480-74bb-11e9-98f1-b554068442da.png)

**Comment by mKay00** [comment]
Probably the same issue as #521.

**Comment by gpotter2** [comment]
Definitely, nice catch !
