### ISSUE TITLE
Connection via ssh remove ` back quote symbol

### ISSUE THREAD

**Issue by tomvitale** [microsoft/terminal#7187]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version: 1.1.2021.0
```

# Steps to reproduce

0. open a terminal Windows PowerShell
1. paste something with "back quote" symbol: textfile_listing=\`ls *.txt`
2. connect with built-in ssh to a linux server
3. paste again the same with "back quote" symbol: textfile_listing=\`ls *.txt`

--> the result is without the ` symbol: textfile_listing=ls *.txt

# Expected behavior

I expect that by connecting via ssh I can paste the back quote

# Actual behavior

when I paste a command with the back quote via ssh removes the symbol

**Comment by DHowett** [comment]
Does this only happen when you paste the backtick character? It works fine if you type it?

**Comment by tomvitale** [comment]
happen both, when I paste a command with ` and also when I type it

**Comment by DHowett** [comment]
Can you test it with the latest release of Win32-OpenSSH? https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by tomvitale** [comment]
with ssh.exe from OpenSSH v8.1.0.0p1-Beta works great

**Comment by zadjii-msft** [comment]
Great, sounds like it was just an issue in Win32-OpenSSH v7 then. Thanks for following up!
