### ISSUE TITLE
Add Antialiasing to the custom icons of terminals

### ISSUE THREAD

**Issue by SinanAkkoyun** [microsoft/terminal#7189]
# Description of the new feature/enhancement

Add an "anti-aliasing-icon" feature or something like that.

# Proposed technical implementation details (optional)

Add an "anti-aliasing-icon" feature or something like that.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #6787 for more discussion.

/dup #6787

**Comment by SinanAkkoyun** [comment]
Oh, whoopsie, thanks anyways
