### ISSUE TITLE
error 0x80070005 when launching `cmd.exe'

### ISSUE THREAD

**Issue by mapitman** [microsoft/terminal#7193]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.1.2021.0

Any other software?
```

# Steps to reproduce

Open Windows Terminal, open a new tab with Command Prompt

# Expected behavior

A new tab with a running cmd shell

# Actual behavior

New tab opens with
```none
[error 0x80070005 when launching `cmd.exe']
```

# Notes

I updated to this version of Windows from a previous version (not sure of the exact build number, but it was Windows 10 1909). Windows Terminal was working properly before the update. I can run a cmd shell directly, just not from Windows Terminal. I have seen references to this error code in relation to WSL, but WSL works fine with Windows Terminal on my machine.

# Things I've already tried

1. Reboot
1. Uninstall/reinstall Windows Terminal
1. Delete  C:\Users\xxx\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe

**Comment by DHowett** [comment]
Does this apply only to the _Command Prompt_ profile, or does it happen for all of your profiles?

**Comment by mapitman** [comment]
Just Command Prompt. I am also checking with our IT staff to see if it is possible that Carbon Black Defense is blocking this. Although it was working earlier today before I updated to the new Windows build.

**Comment by mapitman** [comment]
After installing a Visual Studio update and rebooting, this suddenly started working again. Not sure what happened 🤷‍♂️

**Comment by DHowett** [comment]
Wow, that's quite unexpected. Thanks/sorry!

**Comment by mapitman** [comment]
For future visitors, this was indeed caused by anti-virus/anti-malware software blocking Windows Terminal from executing `cmd.exe`.

**Comment by sudo-nikhil** [comment]
THIS IS NOT CAUSED BY ANTIVIRUS OR ANYTHING. PLEASE READ THIS. Alright so after some research I realised that the problem is with the environment variable. Open **Environmental Variables** and under System Variables, click on "PATH" and then click new. **Now add this - %SystemRoot%system32**
Click exit, now **restart your System**. Everything should be working perfectly fine now. Glad I could help!

**Comment by ahmedalnuaimi** [comment]
> %SystemRoot%system32

I think that it should be %SystemRoot%\system32.
Didn't work for me

**Comment by dataspun** [comment]
Yes indeed, @mapitman:
The application ~\windowsapps\microsoft.windowsterminal_1.12.10982.0_x64__8wekyb3d8bbwe\windowsterminal.exe invoked the application C:\windows\system32\cmd.exe. The operation was blocked by Carbon Black Cloud

**Comment by nasserakhter** [comment]
Just putting this here from anyone who might be in the same boat as me. If you changed permissions on the C:/Program Files/WindowsApps folder or the %LOCALAPPDATA%/Packages folder, windows terminal will stop working.

**Comment by zadjii-msft** [comment]
It sure will!

# DO NOT TOUCH `C:/Program Files/WindowsApps`. 

It **will** mess up your machine.
