### ISSUE TITLE
moveFocus to panel using cycle

### ISSUE THREAD

**Issue by mfeiertag** [microsoft/terminal#7194]
# Description of the new feature/enhancement

Currently terminal only supports moveFocus to up/down/left/right. This feature would allow cycling through panes like going trough tabs with
` { "command": "nextTab", "keys": "ctrl+tab" }`
and 
`{ "command": "prevTab", "keys": "ctrl+shift+tab" }`

# Proposed technical implementation details (optional)

New panes get assigned increasing IDs. 
`{ "command": { "action": "moveFocus", "direction": "next" }, "keys": "ctrl+alt+tab" }`
focuses the pane with the next ID
`{ "command": { "action": "moveFocus", "direction": "prev" }, "keys": "ctrl+alt+shift+tab" }`
focuses the pane with the previous ID

IDs could be in order of creation or in order of last used.
| Property | Necessity | Type | Default | Description |
| -------- | --------- | ---- | ------- | ----------- |
| `paneCycleMode` | Optional | String | `created` | Defines the order of panes when cycling. Possible values: `created` or `lastUsed`  |

Related to #5803 and #5464 
Similar to #4692

### Example (pane in focus bold):
Single Pane:
| **1** |
Duplicate pane:
| 1 | | **2** |
Pressing ctrl+alt+tab:
| **1** | | 2 |
Duplicate Pane 1, than pane 2:
| 1 | | 2 |
| 3 | | **4**  |
Pressing ctrl+alt+tab would go to pane 1:
| **1** | | 2 |
| 3 | | 4  |
Pressing ctrl+alt+shift+tab would go back to pane 4:
| 1 | | 2 |
| 3 | | **4**  |
Pressing ctrl+alt+shift+tab again would go to pane 3:
| 1 | | 2 |
| **3** | | 4 |

**Comment by mfeiertag** [comment]
Duplicate of #2871

**Comment by zadjii-msft** [comment]
Wow this is a super well written write-up. I love that it also includes an affordance for MRU-order pane switching as well. I'm gonna slap the body of this into a comment in #2871. Thanks!
