### ISSUE TITLE
UX: Terminal Tab - Pin feature request.

### ISSUE THREAD

**Issue by onurakkaya** [microsoft/terminal#7196]
# Description of the new feature/enhancement

Could you add terminal tab pinning feature like in the browsers?

Think, you're running "batch scripts" in a terminal page and it will be end at 2 hour later. If i can pin this tab it's not confused me when i'm using other pages.

# Proposed technical implementation details (optional)

If Tab state is pinned, shrinks , comes to front order and can be prevents accidentally close. 

Like bellow;

![image](https://user-images.githubusercontent.com/24228123/89497746-a382aa00-d7c5-11ea-9292-a87872224c4d.png)

**Comment by skyline75489** [comment]
We have #5969 for this. I'd say it's indeed a good idea.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22pin+tab%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #5969 for more discussion.

/dup #5969
