### ISSUE TITLE
Surround selection with quotes

### ISSUE THREAD

**Issue by avi12** [microsoft/terminal#7198]
# Description of the new feature/enhancement
The current behavior: Pressing `'` or `"` while a selection is present will replace the text under that selection with that character.
The proposed behavior: Surround the selected text with the pressed character.

**Comment by zadjii-msft** [comment]
That's not really how terminal emulators work unfortunately. They're not really a text editor where the entire buffer is mutable like that. In a terminal the only place where text can be written to the buffer is the cursor position.

However, client applications should be able to support something similar. Take for instance `vim`, which has it's "visual" mode. I'm sure there's a way to wrap a visual selection in vim with quotes. I bet there's even a similar way for `emacs`. Heck, it's probably not _totally_ out of the question for `powershell` to be able to implement something similar as well.

What application are you trying to use this functionality in?

**Comment by LuanVSO** [comment]
there is a script that does this in the psreadline repo:
[script](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/SamplePSReadLineProfile.ps1)
but it only works on the prompt line and you have to select the text using powershell key bindings (ctrl+shift+arrows), selecting with the mouse won't work
