### ISSUE TITLE
GIT Bash has bad flicker

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/terminal#7200]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.423]
Windows Terminal version (if applicable):  1.1.2021.0  

Any other software?
Git for windows:  v2.28.0
```

# Steps to reproduce

1.  Open a "GIT Bash" terminal session
2.  Press backspace key
3.  ![BashFlicker](https://user-images.githubusercontent.com/966863/89535209-02f4b000-d7ee-11ea-96c5-ae16ad043871.gif)

# Expected behavior

No nasty flicker

# Actual behavior

Nasty flicker

**Comment by zadjii-msft** [comment]
That looks to me like they're using the "visual bell". Is there anything about `bell-style` in your `~/.inputrc` or `/etc/inputrc`?

**Comment by GordonSmith** [comment]
I don't have a `~/.inputrc` file and this is GIT Bash on windows so no `/etc` folder either - but I suspect you are correct.

**Comment by KalleOlaviNiemitalo** [comment]
Git for Windows does install an `/etc` directory (perhaps mapped to `C:\Program Files\Git\etc`) and an `/etc/inputrc` file that includes `set bell-style visible`.

<https://github.com/git-for-windows/build-extra/blob/1227299bc78df003c3b246edbd04a583ac162dc7/git-extra/inputrc#L1-L2>

**Comment by GordonSmith** [comment]
Ok - I will close invalid - can it be disabled in Terminal settings, or do I need to do the local `/etc/inputrc`?

**Comment by GordonSmith** [comment]
Closing invalid - Terminal is honouring inputrc settings...

**Comment by KalleOlaviNiemitalo** [comment]
I believe the visual bell uses the `flash` capability from terminfo. For `xterm-256color`, the value is `\E[?5h$<100/>\E[?5l`. AFAIK, Windows Terminal does not provide a way to disable the `\E[?5h` and `\E[?5l` control sequences. It might be best to `set bell-style audible` or `set bell-style none` in `~/.inputrc` so that the setting will survive Git for Windows upgrades.

**Comment by KalleOlaviNiemitalo** [comment]
On the other hand, if DECSCNM is primarily used for visual bell, then it might make sense for Windows Terminal to disable it when animations are disabled according to [SystemParametersInfo SPI_GETCLIENTAREAANIMATION](https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-systemparametersinfow#spi_getclientareaanimation).

**Comment by thomasaarholt** [comment]
To fix: `nano ~/.inputrc` and add the text `set bell-style none` or `set bell-style audible`. Press `Ctrl + O` and `Ctrl + X` to Save and Exit.

I found this behaviour to be really distracting/disurbing.
The regular Git Bash terminal does exhibit this behaviour, though I can confirm that `/c/Program Files/Git/etc/.inputrc` does contain `set bell-style visible` (and that command is not overwritten by anything in `.inputrc`.

Note that `set bell-style audible` does not give a ping sound in Git Bash in Windows Terminal, but it does do so in regular Git Bash.

**Comment by DHowett** [comment]
So, that’s because we only recently got support for visual bells at all. There’s an escape sequence that inverts the entire screen, and a visual bell is typically implemented by sending it, waiting a bit, and then sending it again.

Git Bash will start doing this inbox in Windows at some point with the next Desktop release, as it is required by standard for us to support it.

**Comment by KalleOlaviNiemitalo** [comment]
> `set bell-style audible` does not give a ping sound in Git Bash in Windows Terminal

Seemingly covered by <https://github.com/microsoft/terminal/issues/1608> and <https://github.com/microsoft/terminal/issues/4046>.

**Comment by fzzio** [comment]
Thank you!

**Comment by rluvaton** [comment]
I'm keep coming back here way to much times 🤣

**Comment by brighamband** [comment]
If anyone has issues saying 'Permission Denied', make sure that in Git Bash (or whatever terminal you use to open `inputrc` in nano) as administrator.

**Comment by MachineLearning-Nerd** [comment]
> Although the backspace is fixed, I still met the same issue during vi editing in git bash, and the workaround mentioned above is not working

`set t_vb=`

in .vimrc

**Comment by danfly09** [comment]
I just made a copy to my local folder and commented that bell style line as follows 

`cd`  go to your home directory
`cat /etc/inputrc > .inputrc`   print inputrc content to .inputrc file in your home directory... don't forget the DOT

Now edit your local file
`set bell-style visible`  before
`# set bell-style visible`  after

Restart your shell.

**Comment by ToxicSmurf** [comment]
This little quirk was the main reason I wasn't using Git bash as my default shell, now I have no reason...

Thank you!!

**Comment by xudyang1** [comment]
For those who don't want a `.inputrc` polluting your home directory, add the following to your `.bashrc` file:

```bash
bind 'set bell-style none'
# or bind 'set bell-style audible'
```

**Comment by opensuse1** [comment]
https://www.youtube.com/watch?v=VxHT88haAPU&t=162s

**Comment by FunctionPoint** [comment]
I just encountered this very annoying behavior for the fist time in the new Git Bash 2.54.0 in Windows.
Odd that this is turned on by default, who would want this?
There are lots of duplicate issues complaining about the same thing.
To turn in off I'm shortly re-iterating the great answer of @thomasaarholt above:
In the file `~/.inputrc` , add the line `set bell-style none` .
