### ISSUE TITLE
Replace the InOrderCounter in the ATS with something more sensible

### ISSUE THREAD

**Issue by leonMSFT** [microsoft/terminal#7205]
Inside of `CommandPalette.cpp`'s filtering function lives a `counter` whose sole purpose is to guarantee a stable sort when the `WeightedCommands` are thrown into the priority queue. This definitely should be replaced with something more pleasing.

**Comment by Don-Vito** [comment]
@leonMSFT - I guess this one can be closed as weighted command exists no more.

**Comment by zadjii-msft** [comment]
Oh, wow yea it totally can. Must've missed this one!
