### ISSUE TITLE
Commandline: `split-pane` does not honor focus pane

### ISSUE THREAD

**Issue by jevad** [microsoft/terminal#7206]
# Environment

```none
Windows build number: Version 1909 (OS Build 18363.592)
Windows Terminal version (if applicable):  7.0.0
```

# Steps to reproduce

Run the following command:
```
wt `; split-pane -V `; split-pane -H `; focus-tab -t 0 `; split-pane -H
```

Screenshot of the command:

![what_i_ran](https://user-images.githubusercontent.com/1743373/89588005-625fb980-d808-11ea-93d7-f1eee0656883.png)

# Expected behavior

I expect a Windows Terminal split into four panes of equal size.  Pane 0 should have been split down the middle, vertically. Then pane 1 should have been split down the middle horizontally.  Then pane 0 should have been split down the middle horizontally.

Screenshot of what I expect:

![what_i_expect](https://user-images.githubusercontent.com/1743373/89587814-faa96e80-d807-11ea-97ab-c3b9f39b0f09.png)

# Actual behavior

What I actually get is a window with a half-size pane, a quarter size pane and two eighth size panes.  The behavior seems to be that the final `split-pane` command is ignoring the fact that the focus has been reset to pane 0, so it splits pane 2 instead of pane 0.

Screen shot of what actually happened when I ran the command:

![what_i_get](https://user-images.githubusercontent.com/1743373/89588038-773c4d00-d808-11ea-8b31-3276ad00f11d.png)

**Comment by zadjii-msft** [comment]
The command you're running is focus-**tab**, not focus-**pane**. There actually isn't a command for moving focus between panes quite yet. For that, I'd follow #5464

/dup #5464

Thanks!
