### ISSUE TITLE
The default font renders the same character in different glyphs depending on the context

### ISSUE THREAD

**Issue by denilsonsa** [microsoft/terminal#7209]
# Environment

Microsoft Windows [Version 10.0.19041.388]

# Steps to reproduce

* Type a digit, followed by `x`, followed by another digit. (e.g. type `5x5`)

# Expected behavior

Since this is a monospaced terminal, I expected the same character to be rendered the same way, regardless of the surrounding characters. This is specially important when editing a text file in the terminal, to make sure the `x` character I see there is the real `x`, and not the multiplication sign `×`.

# Actual behavior

When `x` is between two digits, its glyph changes. It is now rendered exactly the same the multiplication sign `×`. Look at this zoomed in screenshot, they are all the lower-case latin `x`:

![image](https://user-images.githubusercontent.com/121676/89623740-7271aa80-d895-11ea-90b5-4e6020bdc412.png)

It took me a couple of minutes staring at a text file I was editing to convince me that character was `x` instead of `×`

Look at this other screenshot. One of these is the multiplication sign. Can you spot it (before looking at `xxd` output)?

![image](https://user-images.githubusercontent.com/121676/89624284-4a367b80-d896-11ea-95a8-b0eb69c5ac4a.png)

# Possibly related issues

[Investigate/implement renderer setting to disable ligatures](https://github.com/microsoft/terminal/issues/759)

**Comment by zadjii-msft** [comment]
Yep, you're definitely right. This is because the glyphs are being ligatured together. 

IIRC, we ship a non-ligatured version for Cascadia Code in the package as well, something like "Cascadia Mono". You might be able to work around this by using that font instead.

/dup #759
