### ISSUE TITLE
New tab should refresh environment (variables)

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/terminal#7211]
# Description of the new feature/enhancement

When opening a new tab, especially with Powershell / cmd, environment vars aren't reloaded. It'd be nice to be able to get a clean and fresh environment, for instance, if I've just installed/configured something in Windows and don't want to close the terminal.

**Comment by KalleOlaviNiemitalo** [comment]
May be the same as <https://github.com/microsoft/terminal/issues/1125>.

**Comment by bruno-brant** [comment]
#1125 would solve environment changes as well.
