### ISSUE TITLE
settings.json is lies

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/terminal#7212]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?

```
![image](https://user-images.githubusercontent.com/36889813/89637949-f0887e00-d8a2-11ea-8337-e6b1351f440f.png)

# Steps to reproduce
- Install Powershell 7 from https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3
I used the msix

- Update entry in terminal's settings.json to point to pwsh.exe instead of powershell.exe

- Restart Windows Terminal

- Now I have two powershell entries in the new window menu

# Expected behavior

I my single powershell entry starts powershell 7, not 5.

The easiest way to describe this issue is with a paste of my settings.json, a screenshot of my terminal, and the question "how does this file represent this menu?"

`
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    // Default to PowerShell
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    "initialCols": 140,
    "initialRows": 30,
    "profiles":
    [
        {
            // Make changes here to the cmd.exe profile
            "guid": "{DB7EBB6F-0DEE-462F-8D0E-3288AAB04073}",
            "name": "Command Prompt",
            "icon": "C:\\Windows\\System32\\SHELL32.dll",
            "commandline": "cmd.exe",
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "hidden": false
        },
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "name": "PowerShell",
            "source": "Windows.Terminal.PowershellCore",
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "hidden": false,
            "startingDirectory": "E:\\repos"
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "VS 2017",
            "icon": "C:\\Windows\\System32\\SHELL32.dll",
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "hidden": false,
            "startingDirectory": "E:\\repos",
            "commandline": "%comspec% /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017 15.9\\Professional\\Common7\\Tools\\VsDevCmd.bat\""
        },
        {
            "guid": "{C8F1B58D-FC58-462A-87F1-CC8CEB91C076}",
            "name": "VS 2019",
            "icon": "C:\\Windows\\System32\\SHELL32.dll",
            "hidden": false,
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "startingDirectory": "D:\\Development\\repos",
            "commandline": "%comspec% /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019 16.3\\Professional\\Common7\\Tools\\VsDevCmd.bat\""
        },
        {
            // Make changes here to the NodeJS.exe profile
            "guid": "{3b47f3c3-ed09-4301-a139-826c8151ee5c}",
            "name": "NodeJS",
            "icon": "C:\\Windows\\System32\\SHELL32.dll",
            "commandline": "%comspec% /k \"C:\\Program Files\\nodejs\\nodevars.bat\" && node && exit",
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "hidden": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "background": "#3a3939",
            "foreground": "#ececec",
            "cursorColor": "#ececec",
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [
        {
            "name": "Nathan",
            "background": "#3a3939",
            "foreground": "#ececec"
        }
    ],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
`

# Actual behavior

![image](https://user-images.githubusercontent.com/36889813/89637366-f6319400-d8a1-11ea-901d-976634ebd3ab.png)

Why have I got a second powershell entry when none is listed in the settings.json?

I've signed out & in again to try to make Windows forget stuff, but it hasn't worked. I still have two powershell entries when only one is listed in settings.json

**Comment by ncook-hxgn** [comment]
Also, the Powershell entry that I've added for Powershell 7 is always bold in the menu, for no discernable reason (that I can see in settings.json)

**Comment by KalleOlaviNiemitalo** [comment]
It is bold because it is your default profile.

**Comment by ncook-hxgn** [comment]
> It is bold because it is your default profile.

.. ah good point! I'll delete my superflous comment 👍

**Comment by zadjii-msft** [comment]
This is maybe one of the more confusing edge points of the terminal settings - the `cmd` and `Windows Powershell` profiles are "default" profiles, which means they're included in the Terminal's `defaults.json`. They;re always included in a user's settings, no matter what. You can delete them from your `settings.json`, but they'll still be in your final runtime settings, because the settings are composed from multiple places.

If you'd like to prevent it from showing up in the list of profiles, you can use:

```jsonc
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": true
            },
```

to "hide" it from the list of profiles.

For more reading, I'd check out [this doc](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#settings-layering).

**Comment by ncook-hxgn** [comment]
@zadjii-msft aha, the mystery of the extra PowerShell entry was solved. It is a thing of beauty once again.

Thank you for explaining. If I find defaults.json and hack it up a bit, I guess I can expect it to change if Windows Terminal gets updated? (Not that I need to, your solution seems the advisable one)

![image](https://user-images.githubusercontent.com/36889813/89662415-f6df2000-d8cb-11ea-967e-64ec7f9f488d.png)

**Comment by zadjii-msft** [comment]
Yea so `defaults.json` is actually _not a real file_. Technically, it's just a blob of json that's compiled directly into the application itself - `defaults.json` is just a placeholder file we ship that represents what that file _would_ look like. The Terminal actually totally ignores the one that's on disk 😄
