### ISSUE TITLE
Moving focus with a zoomed pane should just zoom the adjacent pane

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7215]
From discussion in #6989

> move focus:
> * or switch panes but make that other pane be zoomed in?

<hr>

Okay, this is _not_ trivial. When we move the focus to another pane, it takes a dispatcher loop to be able to mark the newly-focused pane as the "active" one. So if we do it all in the `moveFocus` handler, then when we try to zoom in on the active pane, it's still _technically_ the current pane, not the new one.

I got it to _sorta_ work with

```c++
    void TerminalPage::_MoveFocus(const Direction& direction)
    {
        if (auto index{ _GetFocusedTabIndex() })
        {
            auto focusedTab{ _GetStrongTabImpl(*index) };
            const bool wasZoomed = focusedTab->IsZoomed();
            _UnZoomIfNeeded();
            focusedTab->NavigateFocus(direction);
            if (wasZoomed)
            {
                _tabView.Dispatcher().RunAsync(CoreDispatcherPriority::Low, [this, focusedTab]() {
                    focusedTab->ToggleZoom();

                    // Update the selected tab, to trigger us to re-add the tab's GetRootElement to the UI tree
                    _UpdatedSelectedTab(_tabView.SelectedIndex());
                });
            }
        }
    }
```

But that causes a frame where we re-attach the zoomed-out UI, then go back to the zoomed-in UI (zoomed to the new pane). Unfortunately, that forces 2 resizes (resize the current pane smaller, then resize the new pane bigger), and those resizes in debug are fairly laggy.

**Comment by carlos-zamora** [comment]
> But that causes a frame where we re-attach the zoomed-out UI, then go back to the zoomed-in UI (zoomed to the new pane). Unfortunately, that forces 2 resizes (resize the current pane smaller, then resize the new pane bigger), and those resizes in debug are fairly laggy.

With the animation, I bet that would look really neat. And as long as the release build works fine, I think I'm ok with the perf impact. But that's just my 2 cents. :P
