### ISSUE TITLE
Neofetch colors don't withstand resize

### ISSUE THREAD

**Issue by Passific** [microsoft/terminal#7217]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.959]
Windows Terminal version: 1.1.2021.0
WSL: Debian GNU/Linux 10 (buster) on Windows 10 x86_64
```

# Steps to reproduce

1. install neofetch on WSL Debian
1. run `neofetch`
1. resize the Windows Terminal window

# Expected behavior

Colored boxes are part of the neofetch output, and appears correctly.
If you resize the windows they correctly stay displayed.

# Actual behavior

Colored boxes are part of the neofetch output, and appears correctly.
![image](https://user-images.githubusercontent.com/2100205/89657184-f09d7380-d8cc-11ea-81d4-5dc965627231.png)

But if you resize the windows they vanish instantly...
![image](https://user-images.githubusercontent.com/2100205/89657248-0dd24200-d8cd-11ea-9082-0df37bfe966a.png)

**Comment by zadjii-msft** [comment]
Oh man, you've stumbled across one of the oldest bugs in the console: #32

There's more info in #4300:

> Since the console buffer can't know the difference between "no character" and "space", when the console buffer resizes, it doesn't know to copy that color information over.

/dup #32

**Comment by Passific** [comment]
My bad, I tried the `resize` and `neofetch` keywords without luck, so I posted the issue.

**Comment by zadjii-msft** [comment]
No problems! That one's fairly tricky to find in the list of issues ☺️
