### ISSUE TITLE
Windows taskbar label "forgets" custom tab names after switching tabs

### ISSUE THREAD

**Issue by stamminator** [microsoft/terminal#7218]
# Environment

Windows build number: 10.0.19041.0
Windows Terminal version: 1.1.2021.0
Additional info: In Windows Settings > Personalization > Taskbar, my "Combine taskbar buttons" setting is set to "When taskbar is full" instead of the default "Always, hide labels" option.

# Steps to reproduce

1. Give a WT tab a custom name by right-clicking and selecting "Rename Tab"
2. Observe that custom name is respected in the Windows taskbar label.
3. Open a new tab in WT.
4. Observe that the new tab's default name is now shown in the Windows taskbar because it is the active tab, as expected.
5. Close the new tab.
6. Observe that the original tab's custom name is still in place, but the Windows taskbar has gone back to displaying its default, path-based name.

# Expected behavior

If an active tab has a custom name, that custom name should always be displayed in the Windows taskbar.

# Actual behavior

![VevCJr9x4y](https://user-images.githubusercontent.com/10633170/89661190-5a535880-d8a0-11ea-87da-35ff88142b49.gif)

**Comment by DHowett** [comment]
Hey @PankajBhojwani, your change fixed this one right?

**Comment by PankajBhojwani** [comment]
Yep! Closed by #7119

**Comment by stamminator** [comment]
Sorry for the duplicate! I'll look in closed issues as well as open ones before submitting next time.

**Comment by DHowett** [comment]
Oh, no worries! This one was only recently closed, and the more issues we fix the harder it'll be to find ones in the Closed list :smile:
