### ISSUE TITLE
Make all the `ICoreSettings` / `IControlSettings` properties getters-only

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7219]
We've discussed this for a while now, but it's possible now this the other work Carlos is doing with settings.

I've got a WIP branch here: [`dev/migrie/f/settings-getters-only`](https://github.com/microsoft/terminal/tree/dev/migrie/f/settings-getters-only), with only a few errors. 

I think for each of these, the TermControl is going to need to cache a local copy of the value, to represent it's actual runtime value, rather than use the `IControlSettings` as a buffer.

I'm filing this so someone else can pick that up where I left off.

**Comment by MichelleTanPY** [comment]
Hi, I thought of picking this up, and made the changes according to the WIP dev branch there. But I got a lot of errors from multiple files complaining that the argument takes 1 parameters. Any pointers or examples ?
Thanks

**Comment by zadjii-msft** [comment]
@MichelleTanPY That's basically the whole task here actually. _Currently_, the `TermControl` stashes a bunch of run time changes to the settings in it's `IControlSettings` object. In that WIP branch, I made all the properties getters-only, but I haven't yet changed `TermControl`  to do the right thing here. For any of the properties where there's a compile error, you'll need to change TermControl to have some member variable that it uses to store the runtime value instead.
