### ISSUE TITLE
Show a validation warning when someone sets a `setColorScheme` action with an invalid scheme

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7221]
Follow up from #6993.

Basically the title. 

We'll have to scan the tree of actions manually for all the "set color scheme" actions, and ensure each of them has a valid scheme. We can't do this during the parsing of the arg itself, we'll have to do this manually in the Validate phase

**Comment by mpela81** [comment]
Some random thoughts while checking this:
- iterate over all commands in the settings, if at least one "set color scheme" action refers to an unknown scheme, raise the warning
- check for nested commands as well
- noticed that the global commands list includes this non-expanded command from default json:
```
{
    // Select color scheme...
    "name": { "key": "SetColorSchemeParentCommandName" },
    "commands": [
        {
            "iterateOn": "schemes",
            "name": "${scheme.name}",
            "command": { "action": "setColorScheme", "colorScheme": "${scheme.name}" }
        }
    ]
}
```
What could be a good way to skip validating these? 🤔

**Comment by zadjii-msft** [comment]
You could probably ignore any commands with `"iterateOn": "schemes"`, at least for now. That's going to create one action for each color scheme, so you could reasonably assume that the provided colorScheme (which will be expanded out once we know what the set of schemes is) will be valid.
