### ISSUE TITLE
Incorrect color for white

### ISSUE THREAD

**Issue by wawaforya** [microsoft/terminal#7226]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):
(Installed via Scoop, https://scoop.sh/)
Windows Terminal (Unpackaged)
Version: 1.1.200720001-release1.1

Any other software?
No.
```

# Steps to reproduce

1. Configure a color scheme as shown in the picture.  Also refer to [this gist](https://gist.github.com/wawaforya/0c2de893d91730421c0e572843b7e9cf) for the details.
![Colorscheme](https://user-images.githubusercontent.com/19285014/89710760-4c90f680-d9b8-11ea-8aea-34a9024ef9ac.png)

2. Open a new PowerShell or PowerShell Core tab in Windows Terminal and run a script.
```powershell
$esc = "$([char]27)"; for ($i = 30; $i -le 37; $i++) { Write-Host "$esc[${i}mNormal: (0;$i); $esc[${i};1mBright: (1;$i)" }
```
The color for `Normal: (0;37);` should be #a0a0a0 as configured, while it's displayed in black.
![PowerShell](https://user-images.githubusercontent.com/19285014/89711016-37b56280-d9ba-11ea-8930-d0ae71c5688f.png)
![PowerShell Core](https://user-images.githubusercontent.com/19285014/89711021-3b48e980-d9ba-11ea-82d8-63345b80d58d.png)

Or open a WSL tab (I use Arch Linux personally) and run a script.
```bash
for ((i = 30; i < 38; i++ )); do echo -e "\033[0;"$i"m Normal: (0;$i); \033[1;"$i"m Light: (1;$i)"; done
```
The color for `Normal: (0;37);` has the same issue as PowerShell.
![WSL Arch](https://user-images.githubusercontent.com/19285014/89711024-3d12ad00-d9ba-11ea-8d65-8e1b65e2bdf7.png)

# Expected behavior
The color for `Normal: (0;37);` should be displayed in #a0a0a0 as configured.

# Actual behavior
The color for `Normal: (0;37);` is incorrect.

**Comment by j4james** [comment]
Considering the version number you're on, this is probably a symptom of issue #2661, which was fixed in v1.2.2022.0. That said, upgrading isn't really going to help, because we still have a color compatibility hack in place for PowerShell (PR #6810) that retains that incorrect color, because fixing it makes things worse. If you're using the cmd shell or a WSL shell, though, the colors should be correct in the latest preview version of WT.

**Comment by j4james** [comment]
For reference, here's what your WSL test case looks like in the latest version:
![image](https://user-images.githubusercontent.com/4181424/89715150-ccf52e80-d99b-11ea-973d-ce52fa6698dd.png)

**Comment by wawaforya** [comment]
@j4james, thanks you very much.  Just installed the latest preview version and it works fine in WSL now.
