### ISSUE TITLE
Disable PowerShell logo by default or make it easy to disable

### ISSUE THREAD

**Issue by Zingam** [microsoft/terminal#7229]
Add an option to easily disable all sorts of logos or unnecessary information printed by the shells on start. I would even prefer this to be the default setting or there could be a global setting to disable the logos.

This could be applied to PowerShell or any other supported shells.

I like the classic Command Prompt's way:

```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users>
```

https://stackoverflow.com/questions/59671389/suppress-try-the-new-cross-platform-powershell-https-aka-ms-pscore6
https://stackoverflow.com/questions/48262269/how-to-i-remove-the-powershell-start-text

It isn't really that necessary to spam the users with:

```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users>
```

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32>
```

**Comment by skyline75489** [comment]
This is not really what a terminal can/should do. We have just the right explanation for this.

https://github.com/microsoft/terminal/blob/master/doc/Niksa.md#whats-the-difference-between-a-shell-and-a-terminal

**Comment by Zingam** [comment]
@skyline75489 The terminal provides startup options to the shell like working directory. It also detects and configures them. If you are providing a GUI for settings.json, why not provide that option in the GUI?

**Comment by WSLUser** [comment]
This is under complete control of the Powershell team. If you don't want to see it, raise an issue on their repo. https://github.com/powershell/powershell. But likely there's already an issue so give it a thumbs up instead.

**Comment by zadjii-msft** [comment]
Yep, the other posters in this thread are correct. 

You could even pass `-NoLogo` to the `commandline` yourself if you wanted.
