### ISSUE TITLE
Emoji Support for Windows Terminal

### ISSUE THREAD

**Issue by pawarashish564** [microsoft/terminal#7231]
# Description of the New Feature 

When we see any emojis in windows terminal it shows their unicode data. Not the emoji itself. See the following screenshot

![image](https://user-images.githubusercontent.com/29516182/89775290-263c9980-db25-11ea-901c-254590119a4d.png)

Most of the time I use emojis in git commit messages. Also on macOS terminal emojis are visible by default. So It would be great if we have that feature on windows terminal.

Let me know about this feature request.

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22emoji+support%22+is%3Aopen) when filing new issues. This is already being tracked by another issue on our repo - please refer to #190 for more discussion.

As far as your _specific_ scenario goes, I'm fairly certain there's some sort of flag or mode you can use to make sure `git.exe` knows about emoji. Maybe it's doing a `chcp 65001` before the `git diff`? I can't find the exact command at the moment unfortunately.
