### ISSUE TITLE
Resizing the terminal window results in glitchy text-rendering behavior. (Duplicate #3088)

### ISSUE THREAD

**Issue by Va1a** [microsoft/terminal#7242]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

Run any program which re-writes a line of text (such as a python script which overwrites the current line by moving the cursor up and clearing it, and then re-writing a new line- and does this action frequently in a loop, and attempt to resize the window.

# Expected behavior
Resizing the window should not affect the text at all, it should remain as it was properly printed before the resize.
Like so: https://gyazo.com/33d6e441d0bb8105ec118c6a9e69f900

# Actual behavior
The text being constantly overwritten is printed multiple times as if the line up and line clear ansi escape codes are not properly functioning while the windows is being resized.
Like so: https://gyazo.com/47d1ddba7916222121417d2e4776788a

**Comment by skyline75489** [comment]
Is this somewhat related to #3088 ?

**Comment by Va1a** [comment]
Yep. That's exactly what it is. My bad on the dupe, I don't think I would've ever found it as I do not know the exact wording of this scenario. Hope it gets fixed though. 👍
