### ISSUE TITLE
Azure Cloud Shell has acrylic on with default settings

### ISSUE THREAD

**Issue by jim-liu** [microsoft/terminal#7245]
# Environment

```none
Windows build number: 2004 build 19041
Windows Terminal version (if applicable): 1.1.2021
```

# Steps to reproduce

1. In **settings.json**, make sure nothing is inside **profiles.defaults**
1. In Windows Terminal, open a Windows PowerShell tab, and notice that acrylic is off
1. Open an Azure Cloud Shell tab, and notice that acrylic is on
1. In **Settings.json**, set **profiles.defaults.useAcrylic** to `false`
1. Switch back to the Azure Cloud Shell tab, and notice that acrylic is off

# Expected behavior

Because https://aka.ms/terminal-profiles-schema states that **profiles.defaults.useAcrylic** defaults to `false`, I expect/assume an Azure Cloud Shell tab would have acrylic off by default.

# Actual behavior

Azure Cloud Shell tabs have acrylic on by default.

**Comment by KalleOlaviNiemitalo** [comment]
I was surprised to see acrylic there.

<https://github.com/microsoft/terminal/blob/fda80eaf64b6f4bb41f248f5c6b355d672ad64f8/src/cascadia/TerminalApp/AzureCloudShellGenerator.cpp#L39-L41>

If the non-default theme and acrylic are required by some branding guideline, then perhaps Windows Terminal should write those settings of the Azure Cloud Shell profile to settings.json when it creates that file. Doing so would at least make it easier to understand which settings are making Azure Cloud Shell look different from other profiles.

**Comment by DHowett** [comment]
Fair points.

**Comment by KnapSac** [comment]
I'd like to take a look at fixing this, should the acrylic settings be written to the settings.json file, or should they be removed entirely?

**Comment by DHowett** [comment]
Meh, you can probably just remove it from the Azure generator and be done with it :smile:
