### ISSUE TITLE
Putting an equal to sign as 1st character in terminal changes ">" to a ligature.

### ISSUE THREAD

**Issue by PawanKartikS** [microsoft/Terminal#725]
Here are the steps to reproduce the bug:
1) Open terminal
2) Put "="

Before
![1](https://user-images.githubusercontent.com/19567657/57587074-e26f7480-751c-11e9-92db-bdd997e4174b.PNG)

After
![2](https://user-images.githubusercontent.com/19567657/57587075-e602fb80-751c-11e9-85d4-6b4140163437.PNG)

After putting an equal to sign, the ">" changes to ">=".

**Comment by DHowett-MSFT** [comment]
This is indeed how ligatures work.

Duplicate of #514

**Comment by Luuk34** [comment]
This should NOT happen between command-prompt and something the user typed.
