### ISSUE TITLE
Certain pane zoom operations make the terminal go blank

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7252]
* open two panes
* zoom the first one (definitely repros with cmdpal)
* `exit`

expected:
* just the second pane is visible

actual:
* the first pane is removed from the UI tree, and the second is never re-attached.

**Comment by DHowett** [comment]
@cinnamon-msft reported that she hit this all the time during her GIF recording, and we yanked the announce for it. I've pinned this issue in case users run into it :smile:

**Comment by zadjii-msft** [comment]
OKAY I see what's happening here. The `ActivePaneChanged` handler in `TerminalPage`doesn't re-attach the tab content to the tree, it just updates hte title of thewindow.

So when the pane is `exit`ed, the pane's control is removed and re-attached to the parent grid, which _isn't in the XAML tree_. And no one can go tell the `TerminalPage` that it needs to re-setup the tab content again.

The `Page` _manually_ does this in a few places, when various pane actions are about to take place, it'll unzoom. It would be way easier if the Tab could just manage the content of the page.

Or if the `Tab` just had a `Content` that was observable, that when that changed, the page would auto readjust. That does sound like a LOT of work though.
