### ISSUE TITLE
Why is the background image trimmed?

### ISSUE THREAD

**Issue by rediffusion** [microsoft/terminal#7255]
Hello! 🙂

# Environment

«Windows 10 2004»
«Windows Terminal 1.0.1811.0»

# Expected behavior

 💾 **PowerShell**

> "hidden": false,
> "tabTitle": "PowerShell",
> "closeOnExit": "always",
> "startingDirectory": "C:\\Users\\SASHKA\\Downloads",
> "backgroundImage": "C:\\Users\\SASHKA\\Pictures\\Windows Terminal\\HACKERMAN.png",
> "backgroundImageAlignment": "bottomRight",
> "backgroundImageStretchMode": "none",
> "backgroundImageOpacity": 0.8,
> "acrylicOpacity": 0.4

![image](https://user-images.githubusercontent.com/30071027/89999299-45f3cf00-dc97-11ea-9185-f77053b524f3.png)

🔗 Link to the ORIGINAL [picture](https://github.com/rjcarneiro/windows-terminals/blob/master/hackerman.md).

  💾 **Ubuntu**

> "hidden": false,
> "backgroundImage": "C:\\Users\\SASHKA\\Pictures\\Windows Terminal\\Ubuntu1.png",
> "icon": "C:\\Users\\SASHKA\\Pictures\\Windows Terminal\\Ubuntu-18.04_icon.png",
> "backgroundImageAlignment": "bottomRight",
> "backgroundImageStretchMode": "none",
> "backgroundImageOpacity": 0.55,
> "acrylicOpacity": 0.3

![image](https://user-images.githubusercontent.com/30071027/89999768-f235b580-dc97-11ea-8138-81ca10f5b373.png)

🔗 Link to the ORIGINAL [picture](https://www.iconfinder.com/icons/2993667/ubuntu_icon).

### As you can see, the picture on the right is a bit cropped!

 Please HELP If you can, cheers! 💊👍

**Comment by zadjii-msft** [comment]
Form the screenshot you've posted, it looks like it's just being slightly covered by the scrollbar on the right.

If I add the image to my own profiles, and _don't_ hover over the scrollbar:

![image](https://user-images.githubusercontent.com/18356694/90020079-f69ca700-dc74-11ea-88e3-48aef53da2f8.png)


But as soon as I hover over the scrollbar:

![image](https://user-images.githubusercontent.com/18356694/90020103-00260f00-dc75-11ea-8ec0-97738b77ae01.png)

The scrollbar usually also takes a couple of seconds to dismiss itself after you've moved the mouse off of it. I believe there's also a system-wide setting that forces scrollbars to always be visible, is it possible you're using that setting?

**Comment by rediffusion** [comment]
@zadjii-msft 

> is it possible you're using that setting?

 Yes, you got me! 💣
 I find manual [here](https://www.howtogeek.com/365325/how-to-always-show-scroll-bars-in-windows-10/), thanks to a lot, the problem was [SOLVED]. 
Cheers! 👍

**Comment by rediffusion** [comment]
@zadjii-msft 

 One more question! I saw in your setting this:

`"antialiasingMode": "grayscale"`

 What does that give?

**Comment by zadjii-msft** [comment]
Oh, that's because I have `cleartype` anti-aliasing set up in my profile defaults (so that it applies to all profiles), but there are also some long-standing bugs with cleartype AA and background images, so I disabled it for testing.
