### ISSUE TITLE
KB4565351  breaks Terminal (Specified User has invalid profile)

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/terminal#7256]
# Environment

```none
Microsoft Windows [Version 10.0.18363.959]
Windows Terminal Version: 1.1.2021.0

# Steps to reproduce
install KB4565351, try to launch terminal


# Expected behavior

terminal starts

# Actual behavior

Error box:
Specified User has invalid profile




Uninstalling the KB helps
Dunno if this is a KB issue (other store apps do work) or a terminal issue (only terminal has the profile issue)

**Comment by zadjii-msft** [comment]
"Specified User has invalid profile" isn't an error message that the Terminal itself is generating, so it must be originating somewhere else lower on the system.

#5030 and #4237 both reported similar issues, and they were resolved with just a simple reboot, so maybe there's some other OS state that's busted. Could you try just doing another reboot after you see this error and see if it goes away on its own?

**Comment by yamcenutzer** [comment]
A reboot didn't help, I uninstalled the KB, And am now waiting for others stuck on 1909 to to see what they get. I'll try the rebooting thing later when the KB is forced upon me
