### ISSUE TITLE
Cannot load PSReadline module.  Console is running without PSReadline.

### ISSUE THREAD

**Issue by aboelkassem** [microsoft/terminal#7257]
when starting the terminal its shows that and it features has to disable

# Environment
```none
PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Cannot load PSReadline module.  Console is running without PSReadline.
```

**Comment by aboelkassem** [comment]
> 
> 
> Does this happen in the vintage console window (i.e. running powershell directly), or only in the Windows Terminal?
> 
> What version of PSReadline are you using? (`Get-Module PSReadline`)

no, it happens only in Windows Terminal.
and this command `Get-Module PSReadline` did not work in the windows terminal also. 

but it works in normal PowerShell
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


```

**Comment by zadjii-msft** [comment]
That's certainly weird. How did you install PowerShell 6?

**Comment by aboelkassem** [comment]
> 
> 
> That's certainly weird. How did you install PowerShell 6?

yeah, that was the problem. my PowerShell version is 5.1 but I had installed version 7 and that works fine

**Comment by AmirrezaG** [comment]
> when starting the terminal its shows that and it features has to disable
> # Environment
> 
> ```
> PowerShell 6.2.3
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> https://aka.ms/pscore6-docs
> Type 'help' to get help.
> 
> Cannot load PSReadline module.  Console is running without PSReadline.
> ```

Hi I find my solution Here [https://stackoverflow.com/questions/54636948/entity-framework-powershell-script-cannot-be-loaded-by-visual-studio-because-its](URL)
Solution was:
The error may be occurring because of an invalid certificate from Microsoft. Check-in Control Panel => Internet Options => Content => Certificates on the Untrusted Publishers tab. Remove Microsoft Corporation from this list.

**Comment by DJ2211** [comment]
i am also having same type of problem when I run powershell 5 below message appears

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

One or more errors occurred.
One or more errors occurred.
Cannot load PSReadline module.  Console is running without PSReadline.
PS>Get-Module PSReadline
An error occurred while creating the pipeline.

and i installed powershell 7 it's work fine but i dont know how to make powershell 7 as default in visual studio

**Comment by mcurly** [comment]
@AmirrezaG hero of the day, solved the issue for me as well!

Thank you!!!

P.s.: Logged in precisely to do this! Cheers!

**Comment by icedterminal** [comment]
Out of no where I experienced this after running several software updates. I did not have an untrusted Microsoft certificate listed that's been suggested here. I traced this back to a profile reset which changed the execution policy to `Restricted`. Reverting it back to `RemoteSigned` solved it. Not sure what exactly caused a profile reset.

**Comment by afroeagle** [comment]
> Out of no where I experienced this after running several software updates. I did not have an untrusted Microsoft certificate listed that's been suggested here. I traced this back to a profile reset which changed the execution policy to `Restricted`. Reverting it back to `RemoteSigned` solved it. Not sure what exactly caused a profile reset.

That did it - appreciate you!

**Comment by tekeburak** [comment]
Check your execution policy is set to `Restricted `or not. If it is `Restricted`, setting it to `AllSigned` solved the issue for me.

`Set-ExecutionPolicy AllSigned`

**Comment by Ibtisamhaider12** [comment]
> > when starting the terminal its shows that and it features has to disable
> > # Environment
> > ```
> > PowerShell 6.2.3
> > Copyright (c) Microsoft Corporation. All rights reserved.
> > 
> > https://aka.ms/pscore6-docs
> > Type 'help' to get help.
> > 
> > Cannot load PSReadline module.  Console is running without PSReadline.
> > ```
> 
> Hi I find my solution Here [https://stackoverflow.com/questions/54636948/entity-framework-powershell-script-cannot-be-loaded-by-visual-studio-because-its](URL) Solution was: The error may be occurring because of an invalid certificate from Microsoft. Check-in Control Panel => Internet Options => Content => Certificates on the Untrusted Publishers tab. Remove Microsoft Corporation from this list.

You are a life saver Man.. Thanks..!!

**Comment by ttodua** [comment]
Installed latest PS and worked for me:
1) ` winget search Microsoft.PowerShell`
2) `winget install --id Microsoft.Powershell --source winget`
3) set PS7 as default in vscode - https://stackoverflow.com/a/73846532/2377343

**Comment by hostat404** [comment]
> Out of no where I experienced this after running several software updates. I did not have an untrusted Microsoft certificate listed that's been suggested here. I traced this back to a profile reset which changed the execution policy to `Restricted`. Reverting it back to `RemoteSigned` solved it. Not sure what exactly caused a profile reset.

that worked, Thanks !

**Comment by homerious** [comment]
> > when starting the terminal its shows that and it features has to disable
> > # Environment
> > ```
> > PowerShell 6.2.3
> > Copyright (c) Microsoft Corporation. All rights reserved.
> > 
> > https://aka.ms/pscore6-docs
> > Type 'help' to get help.
> > 
> > Cannot load PSReadline module.  Console is running without PSReadline.
> > ```
> 
> Hi I find my solution Here [https://stackoverflow.com/questions/54636948/entity-framework-powershell-script-cannot-be-loaded-by-visual-studio-because-its](URL) Solution was: The error may be occurring because of an invalid certificate from Microsoft. Check-in Control Panel => Internet Options => Content => Certificates on the Untrusted Publishers tab. Remove Microsoft Corporation from this list.

Thank you！ You saved my day!
