### ISSUE TITLE
set variable syntax

### ISSUE THREAD

**Issue by novalagung** [microsoft/terminal#7259]
# Environment

```none
Microsoft Windows [Version 10.0.19041.450]
1.1.2021.0 downloaded via microsoft store
```

# Steps to reproduce

The `set` keyword used to define variable in cmd. I tried to use it in windows terminal, but got nothing.

```bat
PS E:\Workspace> echo $var
PS E:\Workspace> set var=hello
PS E:\Workspace> echo $var

```

After quite a while I found out that to set a variable, a space character must be used instead of `=`.

```bat
PS E:\Workspace> echo $var
PS E:\Workspace> set var hello
PS E:\Workspace> echo $var
hello
```

is this expected behaviour? can't I use `=` to set the variable instead of space?

**Comment by DHowett** [comment]
Windows Terminal does not change how the powershell or CMD command parsers behave. This is operating as expected.

As a note: you are using PowerShell (evidenced by the PS on your prompt), which is a totally different shell than CMD. It acts differently and has a different syntax. You will want to make sure that you’re using the right syntax for the shell you are using.
