### ISSUE TITLE
A nested cmdpal menu should show the parent command above the list of commands

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7265]
Follow-up to #6856 

mockup:

![image](https://user-images.githubusercontent.com/18356694/90069046-5025c580-dcb7-11ea-822b-d8126f033593.png)

I'm talking about the "Split pane with... > " label in the above mockup. 

_Did that mock-up take longer than implementing it would have? Perhaps!_

**Comment by DHowett** [comment]
This is a hilarious mockup. :smile:
