### ISSUE TITLE
Background image scale mode

### ISSUE THREAD

**Issue by ZeroCoolGOS** [microsoft/terminal#7267]
# Description of the new feature/enhancement

Within the settings file we have the option to set the background image stretch mode.  What would also be nice is if we can scale the image as well.  Could be done via pixels, or percentage based.

# Proposed technical implementation details (optional)

"backgroundImageScaleXY": (640,480)
or 
"backgroundImageScaleX": 640
"backgroundImageScaleY": 480
or
"backgroundImageScale": 100%

**Comment by skyline75489** [comment]
I think this is another form of #2370 .

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2370 for more discussion.

/dup #2370
