### ISSUE TITLE
Profile/Settings enhancements for portability and organization

### ISSUE THREAD

**Issue by ZeroCoolGOS** [microsoft/terminal#7268]
# Description of the new feature/enhancement

1. Portable or Cloud Profiles: Have the ability to store/use our profiles remotely, such as attached to our Microsoft accounts (for example).  This would allow us to set our settings once and have them accessible on any machine access.  Copy and Paste the settings.json to a OneDrive account does not lend well to sync and simplicity.

2. Multiple Profile Support:  Creation for a "Work" profile, "Home" profile, "Dev" profile and "Prod" profile. (names are just examples of multiple profiles).  And have them accessible at the same time if desired.  Allowing for nesting or grouping of profiles.

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
I think #2933 and #4566 are related issues.

**Comment by zadjii-msft** [comment]
Yea I think @skyline75489 is right. You might also be interested in 
* Allow dropdown menu customization in profiles.json #1571
* Need a way to have per-machine profiles in settings #641
* Feature Request - use a directory for profiles #2303

/dup #2933
/dup #4566
/dup #1571
/dup #641
/dup #2303
