### ISSUE TITLE
ssh session becomes unresponsive when changing VPN

### ISSUE THREAD

**Issue by suBOTai3** [microsoft/terminal#7269]
# Environment

```Windows
Windows 10 x64 build number: 20161.1000
Windows Terminal version (if applicable):

Any other software?
WSL2 Ubuntu 20.04
```

# Steps to reproduce

* connect to VPN
* open terminal in Ubuntu / WSL2
* ssh to another machine
* while the ssh session is open, change vpn to another vpn

# Expected behavior

ssh session should exit

# Actual behavior

ssh terminal becomes unresponsive. Cursor still flickers, so its not frozen, just not responding to keyboard input

![terminal](https://user-images.githubusercontent.com/5020751/90119676-25d91400-dd5a-11ea-8841-a3c48c7520fd.png)

**Comment by fran-f** [comment]
Does this happen only in Terminal? Does it work fine in the basic WSL console?

**Comment by suBOTai3** [comment]
Hi @fran-f 

I've just been able to replicate in basic wsl console, so I suppose that would have to be logged under a different issue then as it's not strictly related to the terminal project

Thanks for your support

**Comment by zadjii-msft** [comment]
Yea, this sounds like something that should be filed against `ssh` itself, though I don't know where their issue tracker is. Thanks for following up!

**Comment by DHowett** [comment]
Isn’t changing the VPN like _disconnecting the network_? Unless you’re using software that has automatic network failover support, it’s going to fail _any active network connections_ when you do that. That’s like pulling the network cable out and wondering why your file download stopped working 🤨

**Comment by suBOTai3** [comment]
Hi @DHowett 

Yes you're right that is an accurate analogue. But at the same time, good software should indicate that there is no longer a connection when attempting to continue inputting characters.

But remember, as @fran-f and I concluded in our previous messages - this should rather be logged on the WSL2 github page because WSL2 is failing to notify the end user that you cannot continue input.

Think of it like a browser. If for some reason your internet connection drops / the network is disconnected, the browser doesn't stop being responsive. It still accepts input. It's only when you attempt to launch an action that requires a server connection / an update that the UI responds, and then it responds with the appropriate error  message.

What I was expecting, as an end user, is to type and then be informed that the input cannot be processed....or something similar. I'm not sure how that can be achieved, but the current solution of a 'blank screen' with a blinking cursor made be do a double take the first couple of times.
