### ISSUE TITLE
Powershell window opens instead of windows terminal

### ISSUE THREAD

**Issue by nullLoginError** [microsoft/Terminal#727]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.86]
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
When I set CascadiaPackage as my startup project in VS2017 with WindowsTerminal as the entry point, all I get is a powershell window.
![image](https://user-images.githubusercontent.com/8340128/57590530-b686cb80-74e9-11e9-9084-e9449939088b.png)

* What's wrong / what should be happening instead:
How do I get the windows terminal to run?

**Comment by adiviness** [comment]
What happens if you press ctrl+t?

**Comment by nullLoginError** [comment]
> What happens if you press ctrl+t?

![image](https://user-images.githubusercontent.com/8340128/57590944-154d4480-74ec-11e9-853b-0d9aabce272a.png)

**Comment by adiviness** [comment]
Yup! ctrl+t makes a new tab. You can change the tab bar to be hidden or visible by default in you profiles.json.
