### ISSUE TITLE
Add support for the "windows menu" key for shortcuts

### ISSUE THREAD

**Issue by jtnord** [microsoft/terminal#7270]
# Add support for the "windows menu" key for shortcuts

#6635 introduced the `commandPalette` command.  I would really like to be able to bind this to the "windows menu key" however this does not seem to be possible.

Either it is possible and the keyname is not documented, or the documentation is correct and this is not possible.

As a user I expect to be able to use any key on my keyboard in order to bind commands (including keys that may be special for example some extended MS keyboards with a calculator button) by specifiying a keycode if required and the key does not have a common name.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3184 for more discussion.

/dup #3184

**Comment by jtnord** [comment]
@zadjii-msft is this a duplicate? on reading #3184   it seems to only be talking about the winkey and it appears there may be issues with that.  here I am talking about the win-menu (that by default does almost a right mouse click and is located in the UK layout on the right hand side of the soacebar) which is a different key.
happy if they are to be handled together that they are merged but it sounded like technically there may be issued to do so.

**Comment by jtnord** [comment]
incorrect dupe - more likely 7144 now implemented?

**Comment by zadjii-msft** [comment]
Yes - you're right about that. My bad for not catching the difference earlier!
