### ISSUE TITLE
Using screen in git-bash is not normal

### ISSUE THREAD

**Issue by travonf** [microsoft/terminal#7271]
![image](https://user-images.githubusercontent.com/18564432/90123223-10331100-dd91-11ea-8b18-597a70b9207b.png)
When I use git-bash to create the screen, the bottom status bar is abnormal, and there is no problem if I use powershell

**Comment by travonf** [comment]
`~/.screenrc`

```
# Set default encoding using utf8
defutf8 on

defencoding utf8
encoding utf8 utf8

shell -$SHELL

#set the startup message
startup_message off
term screen

#termcapinfo xterm|xterms|xs ti@:te=\E[2J
# Change the xterm initialization string from is2=\E[!p\E[?3;4l\E[4l\E>
# # (This fixes the "Aborted because of window size change" konsole symptoms found
# #  in bug #134198)
termcapinfo xterm* 'is=\E[r\E[m\E[2J\E[H\E[?7h\E[?1;4;6l'

altscreen on

defscrollback 10000

#hardstatus alwayslastline  "%{= kw}%-w%{= kG}%{+b}[%n %t]%{-b}%{= kw}%+w %=%d %M %0c %{g}%H%{-}"
caption always "%{= kw}%-w%{= kG}%{+b}[%n %t]%{-b}%{= kw}%+w %=%d %M %0c %{g}%H%{-}"

vbell off

#Keboard binding
# bind Alt+z to move to previous window
bindkey ^[z prev
# bind Alt+x to move to next window
bindkey ^[x next

# bind Alt`~= to screen0~12
bindkey "^[`" select 0
bindkey "^[1" select 1
bindkey "^[2" select 2
bindkey "^[3" select 3
bindkey "^[4" select 4
bindkey "^[5" select 5
bindkey "^[6" select 6
bindkey "^[7" select 7
bindkey "^[8" select 8
bindkey "^[9" select 9
bindkey "^[0" select 10
bindkey "^[-" select 11
bindkey "^[=" select 12
# bind F5 to create a new screen
bindkey -k k5 screen
# bind F6 to detach screen session (to background)
bindkey -k k6 detach
# bind F7 to kill current screen window
bindkey -k k7 kill
# bind F8 to rename current screen window
bindkey -k k8 title
```

**Comment by DHowett** [comment]
You have deleted the bug template. Please don't do that -- it makes it very hard for us to triage bugs.

* What version of Terminal are you using?
* What version of Windows?
* What version of Git for Windows?

**Comment by travonf** [comment]
> You have deleted the bug template. Please don't do that -- it makes it very hard for us to triage bugs.
> 
> * What version of Terminal are you using?
Windows Terminal 0.11.1251.0

> * What version of Windows?
Windows 10 enterprise 1909 18363.959

> * What version of Git for Windows?
Git for Windows 2.23.0.1

**Comment by DHowett** [comment]
You are using a very old prerelease version of terminal. Please check if your bug still reproduces on 1.1, the latest version. The version you are using is from March. :)

**Comment by travonf** [comment]
> You are using a very old prerelease version of terminal. Please check if your bug still reproduces on 1.1, the latest version. The version you are using is from March. :)

![image](https://user-images.githubusercontent.com/18564432/90239148-a9c5f580-de59-11ea-94c2-2c58bb6ddcb3.png)

I entered the wrong version number, and there are still problems after upgrading the version,
I think it's a git-bash problem, but I couldn't find a place to ask, so I asked for help here

**Comment by DHowett** [comment]
Thanks for the info! That is an older verison of git for windows. Does it still happen with Git for Windows 2.28?

**Comment by travonf** [comment]
> Thanks for the info! That is an older verison of git for windows. Does it still happen with Git for Windows 2.28?

Thanks, when I upgraded to the latest version of git, it was normal

**Comment by DHowett** [comment]
Thank you for confirming!
