### ISSUE TITLE
Selecting two .bat files and hitting "enter" key on the keyboard and Windows triggered/ran only one bat file

### ISSUE THREAD

**Issue by pavangayakwad** [microsoft/terminal#7275]
**Problem:**
I am selecting two .bat files and hitting "enter" key on the keyboard and Windows triggered/ran only one bat file. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1834890/90161574-f7d2ee80-ddb0-11ea-9e98-a164bdf6598b.gif)

**Expected behavior:**
All selected files must trigger at once.

**Comment by DHowett** [comment]
The invocation of icons is handled by File Explorer. This would be a great opportunity to file feedback on the Desktop Shell using the Feedback Hub.
