### ISSUE TITLE
Feature Request: Randomize background images from an array of filesystem paths

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/terminal#7279]
# Description of the new feature/enhancement

At the moment, a `backgroundImage` can be specified in a Windows Terminal profile. However, if I `splitPane`, the same background image is used in my duplicate pane. I would like the ability to specify an array of filesystem paths in the `backgroundImage` property, in my profile(s), and have Windows Terminal randomly select one from the array upon initialization.

Using a different background image for each pane helps to keep the interface lively and makes each pane more visually distinguishable from the others.

# Proposed technical implementation details (optional)

Unsure

**Comment by DHowett** [comment]
Hey, I like this. I'll tag it up as a possible extension idea!
Ref: #4000.
