### ISSUE TITLE
Custom Dynamic Tab Names

### ISSUE THREAD

**Issue by dirthsj** [microsoft/terminal#7287]
# Description of the new feature/enhancement
I would like to configure dynamic tab names per profile. For example, I have a git profile and it would be very useful for the tab name to list the current repository. 

# Proposed technical implementation details (optional)

A simple implementation would be a config setting which points to an executable script (eg. `tab_name.sh`) and a list of events that trigger the script to execute or how often to execute it. When executed, the script will write the desired text to `stdout`.

**Comment by DHowett** [comment]
Thanks for the request! The absolute best way to have a dynamic title is to just plug the title generator right into your shell -- perhaps your shell prompt or something that runs very often. It's not going to be broadly possible for us to run the right thing _in the right context_ for you... (like, directory, env vars, parent process, using the right WSL distribution or Cygwin or MSYS2 for the `sh` file, etc.)
But, there's an absolute wealth of resources on how to have a custom dynamic title for any shell you might use :)

Here's some examples:

* [dynamic title in bash](https://unix.stackexchange.com/questions/104018/set-dynamic-window-title-based-on-command-input)
* [dynamic title for all xterm-compatibles](https://unix.stackexchange.com/questions/9007/display-command-in-xterm-titlebar)
* [dynamic title for zsh](https://stackoverflow.com/questions/20727730/dynamic-window-title-in-urxvt-with-zsh)
* [setting a title from powershell](https://devblogs.microsoft.com/scripting/powertip-change-the-powershell-console-title/)

We've also got a deliverable tracking the terminal automatically creating a dynamic title based on things that it _can_ know here: #1320.

Closing as external/question/answered :smile:
