### ISSUE TITLE
No keyboard input (#4448)

### ISSUE THREAD

**Issue by nickpage221** [microsoft/terminal#7288]
# Environment

Windows 10 - 19041

# Steps to reproduce

Fresh install of current version with default settings.json file.

# Expected behavior

Being able to type commands.

# Actual behavior

No normal input accepted from keyboard. Same behavior for cmd, powershell, and powershellcore.

On-screen keyboard also does not work.

Pasting from clipboard works.

If I hold 'alt' while typing Command Prompt will register input from the keyboard but only while I'm holding 'alt'.
If I hold 'alt' while typing PowershellCore will register input from the keyboard but selecting any numbers changes the prompt to "digit-argument:"
If I hold 'alt' while typing Powershell will register some input, no letters but ;'-=/ are accepted and selecting any numbers changes the prompt to "digit-argument:"

I tried to remove and install the wt preview version also, same thing in both regular and preview.

I have no idea what to try next here. This appears to be a known issue with no solution.

**Comment by zadjii-msft** [comment]
I'm gonna move the relevant info over to #4888, unlock that discussion, and ping the input team to see if there are any updates. We still don't have a permanent solution, only the workaround that's listed in #4448. Heck, we still don't even understand what's causing the terminal to get into this state if the first place. We'll update that thread as soon as we find anything out. Thanks!

/dup #4888
