### ISSUE TITLE
option to autodetect desktop wallpaper for use as backgroundImage

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/terminal#7295]
My current setting for backgroundImage is

```json
"backgroundImage": "C:\\Users\\<user>\\AppData\\Local\\Microsoft\\Windows\\Themes\\RoamedThemeFiles\\DesktopBackground\\<file>"
```

The problem is the file name is not static. So i would like an (default)option to autodetect dekstop wallpaper like

```json
"backgroundImage": "DesktopBackground"
```

**Comment by zadjii-msft** [comment]
Is there an API to get the path of the current desktop background image? I'm not sure there is, but I've been wrong before.

I suppose [this StackOverflow post](https://superuser.com/questions/966650/path-to-current-desktop-backgrounds-in-windows-10) has some answers. I'm not sure how stable those answers are, but they _might_ work.

**Comment by bennettnicholas** [comment]
@zadjii-msft I am a student and looking to help out in my free time. This would be my first attempt at any open source issue and my first time helping on the Terminal project. Would this be something you guys would like my help with? This looks fairly straight forward.

**Comment by cjwijtmans** [comment]
@bennettnicholas  The problem is there is no standard way to get the background image on windows. So this might be more difficult than you believe.

**Comment by cjwijtmans** [comment]
Then the second thing to consider is using file watcher API to update the backgroundimage when the desktop wallpaper is changed but i dont think its very  neccesary.

**Comment by bennettnicholas** [comment]
@cjwijtmans I think using the SPI would work the best.

**Comment by bennettnicholas** [comment]
I have been attempting to implement this. I am new to the code base, so I am having some issues getting used to where things are and how to debug.

Correct me if I am wrong, but I thought checking for a string value such as "Desktop" where you normally place the path could be checked in **void CascadiaSettings::_ValidateMediaResources()** in the file **CascadiaSettings.cpp** alongside when we check if the path converts to a URI, but I am having some issue extracting the backgroundimagepath to a sting. If it is "Desktop" then we could replace the path with the SPI_GETDESKWALLPAPER path.

**Comment by cjwijtmans** [comment]
another option would be to add another setting `"backgroundImageWallpaper": true` which will override the path used in the code where it pulls the `"backgroundImage"` setting.

**Comment by bennettnicholas** [comment]
Yea I like that idea much more, it just will require me to know a bit more on how terminal processes the settings. I will look into it. Thanks.

**Comment by cjwijtmans** [comment]
Did you look into profile settings?

**Comment by bennettnicholas** [comment]
Not yet. I actually just started to process of interviewing with Microsoft, which consumed the last few days of mine. I will try looking more into it tonight.

**Comment by bennettnicholas** [comment]
@cjwijtmans I am pretty close. I have it working, but it has some bugs. Trying to figure that out now. 

![image](https://user-images.githubusercontent.com/46642544/95281217-dd971900-0813-11eb-9d7b-c87a578787ac.png)

**Comment by bennettnicholas** [comment]
@cjwijtmans I fixed the bug. Seems to work as expected after some minor testing. Would you be willing to pull down my branch and test it yourself? https://github.com/bennettnicholas/terminal.git (Branch: autoDetectBackgroundImage)
