### ISSUE TITLE
**RELEASE BUILD FAILING**

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#7301]
We may have angered the gourds.

src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2220: the following warning is treated   as an error
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:implicitNoexcept' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:threadSafeInit' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:sizedDealloc' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:alignedNew' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:referenceBinding' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:noexceptTypes' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option '/std:c++'   inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:hiddenFriend' inconsistent with precompiled header
src\cascadia\TerminalApp\lib\Generated   Files\XamlTypeInfo.g.cpp(9,10): Error C2855: command-line option   '/Zc:externC' inconsistent with precompiled header

**Comment by DHowett** [comment]
Idly wondering if this is related to the build agents ditching the PCH files? We definitely worked around that _for TerminalApp specifically_, though...

**Comment by zadjii-msft** [comment]
Wait hold on, did we solve this one?

**Comment by DHowett** [comment]
Oop, good catch.
