### ISSUE TITLE
Cannot paste "─" character in WSL

### ISSUE THREAD

**Issue by G-Rath** [microsoft/terminal#7302]
# Environment

```none
Windows build number: [Version 10.0.18363.1016]
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
```

# Steps to reproduce

Copy the "─" character and attempt to paste it into WSL in Windows Terminal or conhost.

# Expected behavior

The character is pasted fine.

# Actual behavior

It is not pasted fine.

--------

This is an odd bug that's really hard to google, so it might not actually be a microsoft/terminal bug? However, I can successfully paste "─" into WSL via the IntelliJ terminal which I believe isn't using terminal/conhost.

I can paste this character fine into cmd, powershell, and pswh (both in Terminal, and in the windows opened by running those commands via Run, which I assume is/means conhost?).

I originally noticed this when copying from the output of [`audit-app`](https://github.com/G-Rath/audit-app):

```
┌────────────┬────────────────────────────────────────────────────────────────────┐
│ low        │ Prototype Pollution (#577)                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Package    │ lodash v3.10.1                                                     │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched in │ >=4.17.5                                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More info  │ https://npmjs.com/advisories/577                                   │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

Pasting the above into WSL via Terminal or conhost results in:

```
┌┬┐
│ low        │ Prototype Pollution (#577)                                         │
├┼┤
│ Package    │ lodash v3.10.1                                                     │
├┼┤
│ Patched in │ >=4.17.5                                                           │
├┼┤
│ More info  │ https://npmjs.com/advisories/577                                   │
└┴┘
```

This behaviour happens regardless of what program I copy the text from.

**Comment by 0xd4d** [comment]
It's possible to paste it but it doesn't seem to be possible to paste more than one at a time, eg. try pasting "─────────────────────────────────────────" without the quotes

- PowerShell 7: doesn't work
- PowerShell 5: works
- cmd: works
- WSL Ubuntu: works

so this looks like a PowerShell issue, maybe a PSReadLine issue. If you remove it `Remove-Module psreadline`, it works again.

**Comment by G-Rath** [comment]
For me I'm not able to past it at all - pasting "─" right now into WSL results in nothing. Doing paste twice results in `^V` appearing 🤷

**Comment by DhruvaSambrani** [comment]
It works for me. 
![image](https://user-images.githubusercontent.com/44899822/90309451-69708100-df06-11ea-904b-9044e40e140c.png)
Maybe you are using a font that doesn't have the ─ character

**Comment by G-Rath** [comment]
@DhruvaSambrani I'd think if the font didn't have the character, then either it wouldn't render it at all, or otherwise paste "fine" and the render would be broken:

![image](https://user-images.githubusercontent.com/3151613/90309988-621a9900-df41-11ea-9df7-92b0ec18bef6.png)

I've not changed the font from the one that ships with Terminal.

What version of powershell are you using in your screenshot?

**Comment by DhruvaSambrani** [comment]
> What version of powershell are you using in your screenshot?

@G-Rath  5.1.19041.1

**Comment by zadjii-msft** [comment]
> For me I'm not able to paste it at all - pasting "─" right now into WSL results in nothing. Doing paste twice results in `^V` appearing 🤷

Well, sounds to me like you're trying to use <kbd>Ctrl+V</kbd> to paste - can you confirm that you've got ctrl+v bound to paste in your `settings.json`?

Also, what application are you trying to paste into? It looks to me like `bash` and `pwsh` (v7.0.0) in WSL work just fine:
![image](https://user-images.githubusercontent.com/18356694/90401014-fa5c6f00-e062-11ea-8b2c-e41ad4a1238e.png)

**Comment by G-Rath** [comment]
@zadjii-msft I do indeed have it bound as that:

```
{ "command": "paste", "keys": "ctrl+v" },
```

This also happens if I try pasting using right-click as well.

In terms of application, I'm using WSL, started both by running `wt` and `wsl` (which I believe runs conhost) via Run:

![image](https://user-images.githubusercontent.com/3151613/90451043-17667000-e13f-11ea-9fbc-042a369826a8.png)

![image](https://user-images.githubusercontent.com/3151613/90451086-28af7c80-e13f-11ea-8ed4-e261ae3af780.png)

**Comment by zadjii-msft** [comment]
Oh here's a thought - what keyboard layout are you using? That might help explain why pasting doesn't work in conhost or the Terminal

**Comment by G-Rath** [comment]
afaik the "standard" keyboard layout: 

![image](https://user-images.githubusercontent.com/3151613/90561037-307d2880-e1f4-11ea-8b6b-9219f7fa91bc.png)

I say as far as I know as I've seemed to have a little trouble with keyboards on Windows on my new laptop, mainly around the international keyboard, but that presents with IntelliJ's alt +enter not working as it becomes AltGr and so I've confirmed I'm on the US Keyboard when this happens.

I've also reproduced this behaviour happening on my old laptop, which has a very similar setup to my current one (they're roughly the same Windows version, both WinPro, etc).

**Comment by eryksun** [comment]
Can you paste any of the following characters in WSL, with either a regular console window or under Windows Terminal?

|Character|Ordinal
|    :-:      |     --:
|̀ |U+0300
؀|U+0600
܀|U+0700
ࠀ|U+0800
ऀ|U+0900
਀|U+0a00
଀|U+0b00
ఀ|U+0c00
ഀ|U+0d00
฀|U+0e00
᐀|U+1400
᠀|U+1800
ᬀ|U+1b00
 |U+2000
℀|U+2100
∀|U+2200
⌀|U+2300
␀|U+2400
─|U+2500
☀|U+2600
✀|U+2700

In PowerShell 7, in a regular console window or Windows Terminal, can you paste more than one of the above characters as a repeated sequence? For example, does pasting "⌀⌀⌀" work, or does it just paste a single "⌀"? If the latter, does it work correctly after running `Remove-Module psreadline`?

**Comment by G-Rath** [comment]
I've only tried with `⌀⌀⌀` right now, but that's already gotten interesting results:

No pasting in WSL at all, both WT & conhost.
If I start `pwsh.exe` in WT via WSL, then pasting doesn't work, but opening a native `pwsh` tab in WT lets me paste but it only pastes the one character.

`Remove-Module psreadline` does restore my ability to paste the complete string properly.

I think you're having a similar thought that I had when I opened this: that this is something to do with the fact that they're the '00 codes.

I've not tried all the chars everywhere, but quick testing with the majority confirms I can't paste them in WSL

**Comment by eryksun** [comment]
It's something peculiar going on with processing those ordinal values. I checked the Unicode data for the characters, and I don't see any pattern based on the character category, bidirectional class, or East-Asian width. The only pattern I see is that it's the first  (0th) ordinal in some, but not all, Unicode blocks. 

Do the following characters work normally for you?

|Character|Ordinal
| :-: | --: 
|Ā|U+0100
|Ȁ|U+0200
|Ѐ|U+0400
|Ԁ|U+0500
|ༀ|U+0f00
|က|U+1000
|ᄀ|U+1100
|ሀ|U+1200
|ጀ|U+1300
|ᔀ|U+1500
|ᘀ|U+1600
|ᜀ|U+1700
|ᤀ|U+1900
|ᨀ|U+1a00
|ᰀ|U+1c00
|ᴀ|U+1d00
|Ḁ|U+1e00
|ἀ|U+1f00

**Comment by G-Rath** [comment]
Yeah those characters work normally for me :)

**Comment by 0xd4d** [comment]
This looks like a bug in .NET Core's `ConsolePal` class (Windows)

`ReadKey(bool)` doesn't use the same logic as the `KeyAvailable` property. It does read the chars correctly so I assume that code is correct.

https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L285-L288

https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L346-L375

**Comment by 0xd4d** [comment]
PSReadLine sets the output encoding to UTF8. When it's UTF8, .NET Core's `ConsolePal` (Windows) class behaves differently, it ignores the characters. Its `KeyAvailable` property has different logic than its `ReadKey(bool)` method (`KeyAvailable` returns false and eats valid chars when `ReadKey()` would return success).


https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L285-L288

vs

https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L339-L375

```C#
using System;

namespace ConsoleApp1
{
    class Program
    {
        static int Main(string[] args)
        {
            if (args.Length != 1 || (args[0] != "yes" && args[0] != "no"))
            {
                Console.WriteLine("yes or no arg needed (change output encoding)");
                return 1;
            }

            Console.WriteLine($"Input encoding: {Console.InputEncoding.EncodingName}");
            Console.WriteLine($"Output encoding: {Console.OutputEncoding.EncodingName}");

            if (args[0] == "yes")
            {
                Console.OutputEncoding = System.Text.Encoding.UTF8;
                Console.WriteLine($"Output encoding: {Console.OutputEncoding.EncodingName}");
            }

            for (; ; )
            {
                Console.WriteLine("Paste something eg. ⌀⌀⌀ if you can see it");
                var key = Console.ReadKey(intercept: true);
                Dump(key);
                while (Console.KeyAvailable)
                {
                    Console.WriteLine("Key available, reading it");
                    key = Console.ReadKey(intercept: true);
                    Dump(key);
                }
            }
        }

        static void Dump(ConsoleKeyInfo key)
        {
            Console.WriteLine($"KeyChar  : {key.KeyChar}");
            Console.WriteLine($"Key      : {key.Key}");
            Console.WriteLine($"Modifiers: {key.Modifiers}");
        }
    }
}
```

**Comment by DHowett** [comment]
Wow, yeah, this is truly wild. I actually _can_ paste ⌀⌀⌀ in WSL. However, I've seen issues pasting emoji/other unusual characters into my shell that were only resolved by installing my distribution's localization packages and getting full unicode support. zsh was particularly snarky about it, if I'm honest, because it would print out `<ffffffff>` for every character it was upset about.

I may have to mark this one external, but please feel free to keep the discussion going. If you can't get UTF-8 support going in your shell in WSL, let's hash that out. :smile:

**Comment by G-Rath** [comment]
@DHowett all good on the close - when I opened the issue I was 50/50 expecting this to be how it played out.

In saying that, yeah any help on how to get UTF-8 support going in my shell would be appreciated. I've not done any customizing of shells, and so expected that the defaults provided by Windows included that support - not really sure where to go to next for setting that up 😅

**Comment by G-Rath** [comment]
@DHowett I've still not had a lot of luck in getting UTF-8 support working on my terminal, so would appreciate some pointers (and/or links) if you've got them.

I'm sort of hoping this is whats causing some other odd artifacts when using webpack in tmux:

![image](https://user-images.githubusercontent.com/3151613/109370279-87cb2680-7904-11eb-8b25-f47bb351a524.png)

The issue seems to be caused by the webpack build output when its being displayed in a side-by-side panel in tmux, and I've got no idea what to look into to investigate further 😅
