### ISSUE TITLE
[process exited with code 130]

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#7306]
# Environment

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

`Windows Terminal -- Version: 1.1.2233.0`

# Steps to reproduce

run ubuntu 20.04 and then type exit from ubuntu terminal

# Expected behavior

return to windows terminal without problem.

# Actual behavior

Sometimes it shows me [process exited with code 130], but not every time.

I don't know what kind of other log I need to provide.

It happens on every workstation I used , and just some times

**Comment by j4james** [comment]
See issue #5214. This is typically the result of some previous application having set the shell error code to 130, and that's what is reported when you exit. If you don't want to see those errors you can set the "closeOnExit" setting to "always".

**Comment by zadjii-msft** [comment]
Yea, @j4james is right about this one. There's more discussion over in #5214, so I'll redirect you over there. Thanks!

/dup #5214

**Comment by Thazzbelly** [comment]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

**Comment by Thazzbelly** [comment]
> # Environment
> ```
> Platform ServicePack Version      VersionString
> -------- ----------- -------      -------------
>  Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
> ```
> 
> `Windows Terminal -- Version: 1.1.2233.0`
> 
> # Steps to reproduce
> run ubuntu 20.04 and then type exit from ubuntu terminal
> 
> # Expected behavior
> return to windows terminal without problem.
> 
> # Actual behavior
> Sometimes it shows me [process exited with code 130], but not every time.
> 
> I don't know what kind of other log I need to provide.
> 
> It happens on every workstation I used , and just some times
