### ISSUE TITLE
[Windows] vim.exe mouse does not work

### ISSUE THREAD

**Issue by rekaerst** [microsoft/terminal#7307]
# Environment

```none
Windows build number: Windows NT 10.0.19041.388 amd64
Windows Terminal version (if applicable):1.1.2233.0

VIM
```

# Steps to reproduce

add set mouse=a to .vimrc
run vim and use the mouse in vim

# Expected behavior

The mouse events should be sent to vim

# Actual behavior

The mouse does not work in VIM.EXE in the windows terminal.

The mouse does work in vim in old cmd.
The mouse does work in vim in WSL sessions.

also, other windows CLI programs that using the mouse does not work too.

**Comment by zadjii-msft** [comment]
Thanks for the report! Nope, mouse sure doesn't work quite yet. It'll work in the WSL vim, but not in any Win32 applications quite yet. For more info, I'd follow #376.

/dup #376
