### ISSUE TITLE
Windows Terminal With Git Bash Flickering

### ISSUE THREAD

**Issue by TrevorBrown-dev** [microsoft/terminal#7308]
# Environment

```none
Microsoft Windows [Version 10.0.18362.1016]
Surface Pro X
Windows Terminal version: 1.1.2233.0

Any other software?
Git Bash version 2.28.0.windows.1
```

# Steps to reproduce
Running Git Bash in windows terminal. When pressing tab or backspace on an empty line the terminal flickers as shown here
[https://gfycat.com/calmslimbarnswallow](https://gfycat.com/calmslimbarnswallow)

# Expected behavior
The terminal doesn't flicker.

# Actual behavior
The terminal flickers.

**Comment by KalleOlaviNiemitalo** [comment]
That's caused by `set bell-style visible` in the default settings of Git for Windows. See <https://github.com/microsoft/terminal/issues/7200#issuecomment-672786518> for how to disable.

**Comment by zadjii-msft** [comment]
Yep this is the same root as #7200, so I'll just redirect discussion to that thread. Thanks!

/dup #7200
