### ISSUE TITLE
Tab Switcher in Focus Mode does not switch properly

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#7309]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable):1.3.2251.0 
```

# Steps to reproduce

1. Enter focus mode
2. Open a new tab (ctrl+shift+t)
3. Open the tab switcher
4. Use tab switcher to switch to other tab

# Expected behavior

You are now on the other tab

# Actual behavior

You stay on your current tab, regardless of the option. This behavior persists after exiting focus mode.

Specifically, using the tab switcher to switch tabs from Tab 2 (the new tab) is broken from this point forward, it seems. I can still switch from Tab 1 to Tab 2 regularly.

**Comment by DHowett** [comment]
This sounds like a /dupe of #7278, which is not yet fixed in build because of #7301
