### ISSUE TITLE
Weird spaces inside Weechat from Discord relay bot

### ISSUE THREAD

**Issue by ryanrms** [microsoft/terminal#7311]
On our IRC channel there's a relay between it and the Discord server.  When someone types a message in IRC it shows up in Discord. and vice versa.;  But only in weechat via Windows Terminal does it display a space between the first two letters of the sender's name.  I'm connected to a bouncer and have tried weechat with wsltty (which appears to be a fork or continuation of mintty) and the spaces don't appear.  The space also doesn't appear in graphical clients either, like Hexchat, or in terminals on a Linux based OS connected to the same bouncer instance..  

I'm going to investigate more if it some sort of highlight protection on the part of the bouncer, but as of press time the bot owner hasn't replied.

![space problem](https://user-images.githubusercontent.com/2936638/90349913-b03ea380-dff8-11ea-8e72-8eb1a704d2f4.png)

**Comment by DHowett** [comment]
Huh! Would you mind copying a nickname produced by Whalebot from a graphical client and paste it into...

```
xxd
```

inside WSL? (Hit <kbd>Enter</kbd> <kbd>Ctrl+D</kbd> after doing so.)

I'm guessing that it inserts a `U+200D ZERO-WIDTH JOINER` after the first character of the name for--you're likely right--highlight protection. _I believe_ terminals are solidly split on whether they allocate `U+200D` a cell. :smile:

**Comment by ryanrms** [comment]
$ xxd
     <M​onday>
     00000000: 3c4d e280 8b6f 6e64 6179 3e0a            <M...onday>.

Is this one of those zero-width joiners?

**Comment by DHowett** [comment]
```
% echo "e2808b" | xxd -p -r | iconv -f utf-8 -t utf-16le | od -t x2
0000000 200b
```

It sure is :smile:

/dup #1472
