### ISSUE TITLE
Tab scroll button inconsistent and clipped

### ISSUE THREAD

**Issue by simonratner** [microsoft/terminal#7313]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Windows Terminal Preview [Version: 1.2.2022.0]

Display scale: 125%.
```

# Steps to reproduce

Open more tabs than fit horizontally across the window, and observe the tab scroll buttons.

# Expected behavior

Tab scroll buttons consistent in size and style to other buttons in the tab/title bar (new tab, dropdown, min/max/close), and aligned to the same baseline

# Actual behavior

Tab scroll buttons differ in style and alignment from all other buttons, and the icon within the scroll-right button appears clipped.

![image](https://user-images.githubusercontent.com/667283/90361717-c443ce80-e013-11ea-99ed-cea9edccb08a.png)

**Comment by zadjii-msft** [comment]
Huh, I'm seeing the same thing even in the XAML controls gallery, so I'm betting that this is something more fundamental to the TabView itself.

![image](https://user-images.githubusercontent.com/18356694/90400151-aac97380-e061-11ea-9e79-c69b581c2a49.png)


I'm going to move this over to their repo. Thanks!

**Comment by zadjii-msft** [comment]
Moved to microsoft/microsoft-ui-xaml#3144
