### ISSUE TITLE
Caption button animations use wrong color

### ISSUE THREAD

**Issue by HaoxuanDi** [microsoft/terminal#7314]
# For titlebar of terminal:

![image](https://user-images.githubusercontent.com/57934391/90369003-91461d00-e09d-11ea-86f0-7f4a5bc2b182.png)
![image](https://user-images.githubusercontent.com/57934391/90369064-a91da100-e09d-11ea-8541-8bc3eea45007.png)

## When the hover effect is about to end, the icon turns black, but it turns to white when it done

> I'm not sure you can understand my bad English clearly

**Comment by DHowett** [comment]
Are you using `"theme":"dark"` even though you are on a Light-theme OS?

**Comment by dihaoxuan** [comment]
![image](https://user-images.githubusercontent.com/57934391/90373396-6e6b3700-e0a4-11ea-8789-e567a63a213f.png)

## maybe?

There is no problem in light theme
![image](https://user-images.githubusercontent.com/57934391/90373719-f3eee700-e0a4-11ea-9a3d-bb7a2b1300b3.png)
![image](https://user-images.githubusercontent.com/57934391/90373732-f94c3180-e0a4-11ea-8289-48fdb10bc0e8.png)

**Comment by dihaoxuan** [comment]
I can't understand why it needs to "turn black" in dark theme when hover

**Comment by DHowett** [comment]
It is a bug. Thank you for the info.

**Comment by AnuthaDev** [comment]
@DHowett Can I get some pointers on where to start with this🙏

**Comment by skyline75489** [comment]
@AnuthaDev  The caption control are defined in `MinMaxCloseControl.xaml` and related. You may found it useful.

**Comment by AnuthaDev** [comment]
> @AnuthaDev The caption control are defined in `MinMaxCloseControl.xaml` and related. You may found it useful.

Thanks @skyline75489 , but I already know that😅. 

Unfortunately I won't be able to contribute for ~2 months (exams!) , so feel free to work on it😊

**Comment by skyline75489** [comment]
You're always welcome to contribute . Good luck with the exam 😄 . By the way Dustin is the leader of this project so he's kinda busier. Feel free to reach me as I'm more of a community member.
