### ISSUE TITLE
CHANGE OF MOUSE type position

### ISSUE THREAD

**Issue by Fcscanf** [microsoft/terminal#7315]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Windows Terminal Preview [Version: 1.2.2234.0]

Display scale: 250%.
```

# Steps to reproduce
I connected to the remote server host via SSH and did a command from Screen, and when I exited the Screen and returned to the original Shell, the mouse position changed and it appeared above the original output
![image](https://user-images.githubusercontent.com/27654200/90379147-e9d0e680-e0ac-11ea-8dc3-1962b29352e4.png)

# Expected behavior
Generally, operations in the Shell display the location of the type below, not the other location

# Actual behavior

**Comment by zadjii-msft** [comment]
Bizarrely enough, I bet this is #381. `screen` is usually using the "Alternate screen buffer", and exiting screen should return to the main screen buffer. However, since terminal/conpty don't _quite_ understand this scenario quite yet, the buffers can get corrupted like that. 

/dup #381
