### ISSUE TITLE
Duplicate line in TermControl

### ISSUE THREAD

**Issue by dannyd89** [microsoft/terminal#732]
I've found a duplicate line in the TermControl::Create function, either its missing to initialize the vertical alignment or it's just double setting the horizontal one.

https://github.com/microsoft/Terminal/blob/1e478ae99d53a5f54483becfb6c3b379077b8fd9/src/cascadia/TerminalControl/TermControl.cpp#L80

I would have filed a PR but I don't have the environment to do this currently, I hope it's helpful anyway.

**Comment by bef178** [comment]
I think a Help-Wanted label will be add soon lol

**Comment by zadjii-msft** [comment]
Huh. that should almost certainly be `Vertical` instead of `Horizontal`.

I'm a little curious that this works at all without it, but hey ¯\\\_(ツ)\_/¯

**Comment by zadjii-msft** [comment]
This looks like it got fixed in #\<some PR\>
