### ISSUE TITLE
Bug: Font size of Command Palette doesn't scale with terminal font size

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/terminal#7324]
# Environment

```none
Windows Terminal Preview
Windows 10 version 2004
```

# Steps to reproduce

1. Install Windows Terminal Preview
2. Add a keybinding for command palette
3. Scale up your font size (CTRL + PLUS)
4. Invoke the command palette
5. Notice that command palette text doesn't scale up with the profile

# Expected behavior

Command Palette font size should scale proportionally to the current profile's font size.

# Actual behavior

Command Palette font size doesn't scale proportionally to current profile's font size.

![image](https://user-images.githubusercontent.com/466713/90457642-581ba600-e0b9-11ea-91c2-eb706553b086.png)

Contrast this behavior with how VSCode works. The command palette font scales along with the rest of the entire user interface.

**Comment by zadjii-msft** [comment]
Huh. Hadn't considered doing that. Thanks for the suggestion! I suppose the one in Sublime Text's command palette doesn't scale with the editor font size, so there's certainly precedent for either option. The "increaseFontSize" action is really just about increasing the font size of the focused terminal, not the font size of the entire UI. What if the user had multiple panes open side by side, with different font sizes in each?

![image](https://user-images.githubusercontent.com/18356694/90513270-fa24a800-e124-11ea-8b6f-33881b0eb092.png)

I'm thinking that having a constant font size for the palette would look better than having it change font size constantly to reflect the size of the focused terminal. 

So I think I'm gonna close this for now, but I'm open to being convinced the other way. Thanks!

**Comment by DHowett** [comment]
The command palette should follow the application font size set in the accessibility or display settings, FYI.
