### ISSUE TITLE
Visual Error - shortcut CTRL+SHIFT+[dash,equals]

### ISSUE THREAD

**Issue by kellytrinh** [microsoft/terminal#7325]
# Environment

```none
WT Version 1.1.2233
```

# Steps to reproduce

1. Have  lots of different profiles defined.
2. In `settings.json` extend additional shortcuts from the existing 1 to 9 for 0, - (dash), and = (equals) so that CTRL+SHIFT+[key] opens respective profile

# Expected behavior

In the menu for opening a tab/profile, the shortcut for extended shortcuts should appear as logically expected 

# Actual behavior

In the menu for opening a tab/profile, the shortcut newly defined 0 is appear next to relevant profile but the shortcut for dash and equals do not appear.

**Comment by zadjii-msft** [comment]
Could you share the actual json you've added for these keybindings?

**Comment by kellytrinh** [comment]
The relevant lines below; the shortcut themselves do work and I can open the tab/profiles with them fine.

```
        { "command": { "action": "newTab", "index": 7 }, "keys": "ctrl+shift+9" },
        { "command": { "action": "newTab", "index": 8 }, "keys": "ctrl+shift+0" },        
        { "command": { "action": "newTab", "index": 9 }, "keys": "ctrl+shift+-" },                
        { "command": { "action": "newTab", "index": 10 }, "keys": "ctrl+shift+=" },                

```

**Comment by DHowett** [comment]
It looks like we only actually do this for the first 9 profiles:

https://github.com/microsoft/terminal/blob/93d266925cfce92c1f321c43e10809d624cd2b94/src/cascadia/TerminalApp/TerminalPage.cpp#L465-L468

This is probably because we had 9 hardcoded "switch to tab" commands and it was not possible to add a custom index when we first wrote this code :smile:

**Comment by zadjii-msft** [comment]
Ho boy would you look at that. Yep, we should fix that

**Comment by kellytrinh** [comment]
Just noticed - for some reason there seems to be some bug in the shortcut handling - with the JSON snippet above; CTRL+SHIFT+9 works.  So does CTRL+SHIFT+[dash].  But the one in the middle CTRL+SHIFT+0 oddly does nothing.

So there is two bugs, the OP with [dash] [equals] shortcuts not appears and additionally the sequence CTRL+SHIFT+0 not being handled.

**Comment by DHowett** [comment]
If you have multiple keyboard layouts enabled, Ctrl+Shift+0 is reserved by Windows as a keyboard layout switch command.

**Comment by kellytrinh** [comment]
If you mean multiple languages - no I don't have anything like that installed.

Not sure what other layouts you could mean but happy to look into if you give me a pointer on where to check the windows setting.

Anyway; if you are sure this is not a bug and expected behaviour due to windows outside; then can ignore.
