### ISSUE TITLE
I don't have ubuntu terminal like everyone else

### ISSUE THREAD

**Issue by whyiseverynamealreadytaken** [microsoft/terminal#7327]
I think the title says it all.

**Comment by Guiorgy** [comment]
Just gonna quite @DHowett 
> You have deleted the bug template. Please don't do that -- it makes it very hard for us to triage bugs.
> 
> * What version of Terminal are you using?
> * What version of Windows?
> * What version of Git for Windows?

**Comment by zadjii-msft** [comment]
@whyiseverynamealreadytaken Have you installed WSL and the Ubuntu distro from the Store? The Terminal doesn't come with any linux distros on its own, you need to install them separately.
