### ISSUE TITLE
Sometimes the text cursor does not move immediately.

### ISSUE THREAD

**Issue by ba0bab1024** [microsoft/terminal#7330]
# Environment
![image](https://user-images.githubusercontent.com/34526003/90518271-7eb50c00-e1a1-11ea-80d7-8fe1deea2357.png)

```none
Windows Terminal version (if applicable): Downloaded the latest version from the Microsoft store.
```

# Steps to reproduce
I don't know root cause.
While using Windows Terminal, this bug suddenly occurs.
Because of this bug, it is inconvenient to use various command(like vim).
![terminal_bug](https://user-images.githubusercontent.com/34526003/90519068-875a1200-e1a2-11ea-997b-f9fc2a54c9b1.gif)

It can be resolved by reboot, but it repeats continuously.

# Expected behavior

Tell me how to get rid of bug.

**Comment by zadjii-msft** [comment]
> the latest version from the Microsoft store.

Could you provide the exact version number? There's no way to know if you're using the preview or stable version, or if the Store decided to actually give you all the most recent updates or not.

Are you using any sort of IME (like perhaps the Korean IME)?

**Comment by ba0bab1024** [comment]
The version I use is stable 1.1.2233.0. (But, It also occurs in the preview version.)


>Are you using any sort of IME (like perhaps the Korean IME)?

Yes I use Korean IME. 
My friends around me are having the same problem.

**Comment by zadjii-msft** [comment]
Thanks for confirming! This is actually already tracked by #3730 - please refer to that thread for more discussion. Thanks!

/dup #3730

**Comment by bradkim06** [comment]
I used Korean IME and had the same problem. In my case this problem was solved by deleting the Hangle & Computer IME (Hancom Input Method Editor). Check it out and hope it's resolved.

**Comment by ba0bab1024** [comment]
@bradkim06 You're right. This issue is caused by two or more IMEs. The solution is to delete one, but i found out that we can choose Microsoft Korean IME through the ctrl + shift shortcut.
![image](https://user-images.githubusercontent.com/34526003/99756016-7b7a4500-2b2f-11eb-81e4-2c0cc9823b4d.png)
I write it in case people in the same position as me see it.
