### ISSUE TITLE
Strange WSL behaviour

### ISSUE THREAD

**Issue by lego963** [microsoft/terminal#7331]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version (if applicable): 1.1.2233.0
WSL 2
```

# Steps to reproduce

Open WSL type `yes`

# Expected behavior

`-bash: yes: command not found`

# Actual behavior

![image](https://user-images.githubusercontent.com/17201690/90523982-2ddbee00-e176-11ea-9c7e-4c9115fa14f2.png)

**Comment by lego963** [comment]
Should I open issue in WSL repo?

**Comment by zadjii-msft** [comment]
That's absolutely the expected behavior. `yes` is a utility that's shipped with ubuntu (and I bet it's shipped with most linux distros, as it's part of the GNU coreutils). Why would you expect `yes` to not exist?

**Comment by lego963** [comment]
sorry for my misstake
