### ISSUE TITLE
Auto Sync/Hot reload the System environment variables in the current Windows terminal session

### ISSUE THREAD

**Issue by sairaghavak** [microsoft/terminal#7336]
# Description of the new feature/enhancement

**Problem:**
The System environment variables aren't refreshed automatically or synced up in the current windows terminal session, which is forcing the users to reopen a new windows terminal to reflect the changes.

**Steps to Reproduce the problem**
1. Set the powershell as default CLI in windows terminal
2. Open Windows terminal
3. Try to access a system environment variable for example: `${env:JAVA_HOME}` 
4. Then, try to update the `JAVA_HOME` property and lastly
5. Access the same variable from the current windows terminal session, which is printing the cached/old value, isn't reflecting the latest environment variable value.

# Proposed technical implementation details (optional)

**Comment by Weilet** [comment]
Windows Terminal version `1.19.10302.0`
I can't hot load new environment variables in the current tab. Is this by design?
This happens when I use winget to install something. I have to create a new tab to use the newly installed app application.
