### ISSUE TITLE
VS Code linter for settings reports valid commands as errors

### ISSUE THREAD

**Issue by burhan** [microsoft/terminal#7341]
# Environment

```none
❯ [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0


VSCode:

Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z (5 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19042
```

# Steps to reproduce

The visual studio code hints/linter for the terminal settings gives this warning when specifying a new command, where the command is just a string.

(the example was copied from the [1.2 preview release blog](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-2-release/))

![image](https://user-images.githubusercontent.com/603112/90598227-53f7a180-e1fb-11ea-98d3-b05dfd92ee2c.png)

At first, it looked like this is only there for the newer commands, the existing command `{ "command": "paste", "keys": "ctrl+v" },` not does trigger the linter; but the problem is with the case, because if you change `paste` to `pasteThis`:

![image](https://user-images.githubusercontent.com/603112/90603654-45fa4e80-e204-11ea-9767-0ed7834ec08b.png)

# Expected behavior

No squigglies.

# Actual behavior

Squigglies ☹

**Comment by zadjii-msft** [comment]
Ah okay I'm seeing what's happening here. The schema we have listed is always pointing at the _stable_ schema, not the preview one.  If you go to https://aka.ms/terminal-profiles-schema, it'll take you to https://raw.githubusercontent.com/microsoft/terminal/release-1.1/doc/cascadia/profiles.schema.json, which is the schema as it was in 1.1.

This is actually already being tracked in #6601. Thanks!

/dip #6601
