### ISSUE TITLE
Cannot compile when system language is not set to English

### ISSUE THREAD

**Issue by mafriese** [microsoft/Terminal#735]
I have noticed that if you try to compile the project and the system language is not set to English, there will be errors when compiling the CascadiaPackage. The reason for that is (in my opinion) that the buildscript gives an invalid response when it reaches 
```
23>Does C:\Users\Marcel\Documents\Terminal\x64\Debug\TerminalApp.dll specify a file name
23>or directory name on the target
23>(F = file, D = directory)? f
23>C:\Users\Marcel\Documents\Terminal\x64\Debug\TerminalApp\TerminalApp.dll
23>1 File(s) copied
23>Does C:\Users\Marcel\Documents\Terminal\x64\Debug\TerminalApp.pdb specify a file name
23>or directory name on the target
23>(F = file, D = directory)? f
23>C:\Users\Marcel\Documents\Terminal\x64\Debug\TerminalApp\TerminalApp.pdb
23>1 File(s) copied
```
. I tested it in German where the letters for File and Directory are different and therefore the script throws an error and cannot build. However if I change the system language to English, everything build successfully.

**Comment by sagood** [comment]
maybe same to #507

**Comment by PikaFan123** [comment]
Duplicate of #507

**Comment by mafriese** [comment]
Duplicate of #507
