### ISSUE TITLE
Prompt file system error when starting (12002).

### ISSUE THREAD

**Issue by ReputationZH** [microsoft/terminal#7351]
After the installation of Windows terminal, the file system error (12002) will be prompted when starting, and the runtime V14 has been installed.

See the attachment for details

**Comment by ReputationZH** [comment]
Local installation is adopted.

**Comment by zadjii-msft** [comment]
There's no attachment in your original post unfortunately. It might be easier for you to just paste a screenshot of the error. If you just paste an image into github, it'll automatically upload it for you
![upload-image-to-gh](https://user-images.githubusercontent.com/18356694/90766923-eeb2b780-e2b1-11ea-83af-1584382e0c16.gif)
