### ISSUE TITLE
terminal customization problem

### ISSUE THREAD

**Issue by Skipper1117** [microsoft/terminal#7352]
failed in trailing commas,windows terminal is using the default settings, go to line 52,and column 24-error
whenever trying to change the background image.
whats the solution of this.

**Comment by DHowett** [comment]
We cannot help you with settings errors if you do not share your settings file.

**Comment by Skipper1117** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/69949793/90716451-9f2cb580-e2ca-11ea-92bc-97b449999356.png)

This is the problem

**Comment by DHowett** [comment]
Because this is JSON you must use `\\` or `/` instead of `\`. It is because `\` is an “escape character”.

**Comment by vadimkantorov** [comment]
Maybe this would be a common mistake on Windows, since default Windows path format is different. A better error message would be helplful, maybe even some special check about specifically this mistake...
