### ISSUE TITLE
Global properties are considered "not allowed" by schema when placed in "default".

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7353]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]  10.0.19041.0
Windows Terminal version (if applicable): 1.2.2234.0

Any other software? Any text editor or IDE 
```

# Steps to reproduce

Open Windows Terminal. Open Settings. For me, that defaults to opening VS Code. Add alwaysOnTop, largePasteWarning and multiLinePasteWarning properties to defaults. Notice the json linter reports those properties are not allowed.

# Expected behavior

I expect no errors to be raised by the schema.

# Actual behavior

Schema doesn't accept those properties even though they are defined within the schema.

**Comment by zadjii-msft** [comment]
Are you trying to add them to a profile, or to the global settings? These settings are definitely already in the schema:

https://github.com/microsoft/terminal/blob/2c4b868b2093367f5f195399c98d870bc61e05fa/doc/cascadia/profiles.schema.json#L489-L497

https://github.com/microsoft/terminal/blob/2c4b868b2093367f5f195399c98d870bc61e05fa/doc/cascadia/profiles.schema.json#L513-L522

Have you pointed the `"$schema"` property at the preview/master version of the schema?

**Comment by WSLUser** [comment]
Yes. I placed them under "defaults" as specified in the OP. I did already check the schema in master and pointed to it. Still had those errors. https://raw.githubusercontent.com/microsoft/terminal/master/doc/cascadia/profiles.schema.json is what I used. I verified it matched the master in github by checking for the new Pane setting you added.

**Comment by WSLUser** [comment]
I added a  'globals' property that encompassed the settings and also added yet another, the `confirmCloseAllTabs`. Got an error stating globals was depreciated. However I like to keep my settings organized. Just placing them in a stand-alone fashion on top of defaults isn't what I'd like to see. Can we remove the depreciation unless there's a new name to use instead?

**Comment by zadjii-msft** [comment]
> Can we remove the depreciation unless there's a new name to use instead?

Nope, we're not gonna go back into that. It complicated the deserialization process unnecessarily. Once #1564 lands, hopefully people will come to rely less on the layout of the properties in the file itself. 

>  I placed them under "defaults" as specified in the OP

Wait where _exactly_ did you place the properties? If you placed them:


```jsonc
{
    "alwaysOnTop": true, // Good
    "largePasteWarning": true, // Good
    "multiLinePasteWarning": true, // Good
    "profiles": {
        "defaults": {
            "alwaysOnTop": true, // BAD
            "largePasteWarning": true, // BAD
            "multiLinePasteWarning": true, // BAD
        },
        "list": [ ... ]
    }
}
``` 
Could you just share the entire `settings.json`?

**Comment by WSLUser** [comment]
I ended up doing it like you said. I think I should be able to place them in "defaults" if we're not bringing back globals to better organize the settings. Is it possible for you to add them to there (at least until Settings UI can take care of them instead.)

**Comment by DHowett** [comment]
`profiles.defaults` is intended for _settings that can be applied to a profile_. Those settings aren't that. Sorry.
