### ISSUE TITLE
Kex desktop fails to start in Kali Linux on WSL2

### ISSUE THREAD

**Issue by faysl** [microsoft/terminal#7354]
I installed Kex desktop in WSL2 for my Kali Linux on windows 10. It fails to launch in Terminal and gives a a misleading error about wrong password. 

Please use this form and describe your issue, concisely but precisely, with as much detail as possible.

-->

# Environment

```none
Windows build number: 19041.450
Windows Terminal version : Version: 1.1.2233.0

Any other software?
```

# Steps to reproduce

Install WSL2 on windows 10. Then install Kali Linux from Microsoft store and then install Kex desktop by using the following commands:

Step by step

https://www.kali.org/docs/wsl/win-kex/ 

# Expected behavior

Desktop should launch

# Actual behavior

It fails to launch the desktop.

error : CConn:       Opening password file failed

# Workaround

Launch terminal from Kali and then initiate the command Kex and desktop opens up.

**Comment by WSLUser** [comment]
It would be better to assume this is an issue with WSL unless this works using just plain old Conhost. https://github.com/microsoft/wsl

**Comment by zadjii-msft** [comment]
Yea, this doesn't sound like an issue that's caused by the Terminal. I'd take @WSLUser's suggestion and follow up on the WSL repo. Thanks!
