### ISSUE TITLE
Need ability to merge one existing tab into another as a split pane

### ISSUE THREAD

**Issue by ameltzerMSFT** [microsoft/terminal#7356]
# Description of the new feature/enhancement

The ability to split a window in an existing tab is really cool, but I am finding more often than not I have a tab that I've already created and I want to merge it into another existing tab as a split pane. 

For instance, I have one tab where I'm executing a long-running command that I want to keep an eye on, and I have another tab where I'm doing something interactive. I have no options to merge the two tabs together so I have a split between the two. I have to split an existing one and start over (and if the tab I want to merge isn't a default environment, too bad!).

**Comment by ameltzerMSFT** [comment]
After doing some more careful searching this looks like it may be a dupe of #4587.

**Comment by DHowett** [comment]
It sure is! Thanks for finding that. /dup #4587
