### ISSUE TITLE
Duplicate Tabs

### ISSUE THREAD

**Issue by Hamcker** [microsoft/terminal#7359]
# Description of the new feature/enhancement

Ability to duplicate a currently open tab, the new tab will open in the same address with the same color schema.

# Proposed technical implementation details (optional)

I want a new option to be added to the context menu of tab (when user right clicks on the tab), which by clicking on it, a new with the same address will open.

**Comment by DHowett** [comment]
Thanks for the request! We actually do have a duplicate tab option today, on ctrl+shift+d, which you can rebind with the `duplicateTab` action.
We're also tracking being able to copy a tab's working directory to a new tab with /dup #3158.

**Comment by DHowett** [comment]
In addition, the command palette can be used to look this up on 1.2+:

![image](https://user-images.githubusercontent.com/189190/90835514-af13bc00-e301-11ea-9910-30602163363e.png)

**Comment by Hamcker** [comment]
Thank you for your reply, this command doesn't route to the same addrsss.
for example In a tab I'm at the `D:\Projects\Abcd\Docs`, now I want to open a new tab in the same address, not shells default address. it would be usable I think

**Comment by zadjii-msft** [comment]
@Hamcker Sure won't - duplicating the current working directory of a tab is actually a **H**ard problem on Windows. I'd check out #3158 and 


https://github.com/microsoft/terminal/issues/1756#issuecomment-520048598
https://github.com/microsoft/terminal/issues/2315#issuecomment-519317472
https://github.com/microsoft/terminal/issues/1536#issuecomment-519107586
https://github.com/microsoft/terminal/issues/2427#issuecomment-523005110

for _why_
