### ISSUE TITLE
dircolors with background color set highlights to end of line

### ISSUE THREAD

**Issue by zedtools** [microsoft/terminal#7360]
# Environment

```none
Windows build number: 10.0.19041.450
Windows Terminal version 1.2.2234.0

Any other software? No
```

# Steps to reproduce
I am using zsh on WSL Ubuntu.

Put the following in ~/.dircolors:
`OTHER_WRITABLE 30;42`

Then run:
`eval $( dircolors -b $HOME/.dircolors )`

Finally, fill up the terminal screen (e.g. pressing ENTER repeatedly) so that prompt is at the bottom of the window, and run:
`ls -l`

# Expected behavior
When running `ls -l` to view a writable directory, the directory name should be highlighted.

# Actual behavior
If the highlighted directory name spans across a newline, and the ls output scrolls past the bottom of the window, then the entire second line is highlighted.

See screenshot below. The second `ls -l` caused the terminal to scroll past the bottom of the window, and long_dir_name is incorrectly highlighted.

![image](https://user-images.githubusercontent.com/30283145/90845855-47fe1200-e3aa-11ea-9f65-4c8d2fb278ac.png)

**Comment by zadjii-msft** [comment]
Oh, okay, thanks for the follow up! I guess I triaged this without even checking other terminals 😅 

As far as the color highlighting till the end of the line issue, that'll be #32.

Thanks!
