### ISSUE TITLE
Scroll via click in scroll bar?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7367]
When I click in terminal's vertical scroll bar, above or below the slider, the window scrolls 4 lines.  In most other places, including the Window's console, such a click results in the window scrolling 1 page.  Is this by design?  Do I have any control over it?   - Vince

**Comment by DHowett** [comment]
Yep, this is a simple fix. Good catch! :smile:

**Comment by vefatica** [comment]
I'm surprised it wasn't caught earlier.

How do I submit a feature suggestion/request?

Thanks.   - Vince

**Comment by DHowett** [comment]
We can use this issue (which I've left open) to track fixing the scroll bar. There's no need for you to file a separate suggestion if it's about the same problem :smile:

We use this issue tracker for all feature requests, tasks, bugs, scenarios, etc.

**Comment by vefatica** [comment]
It's unrelated but I'll post it here anyway.  :-)

For my purposes, easily opening a pre-configured app in an auto-split pane would be convenient.  I can Ctrl-Shift-N to open app N in a new tab.  And I can Ctrl-Shift-Space to open the drop-down, then scroll to item N and Alt-activate.  How about Ctrl-Shift-Alt-N to do it all (without seeing the drop-down)?

**Comment by vefatica** [comment]
Never mind.  I remembered keybindings.  That was easier than I thought it would be.

{ "command": { "action": "splitPane", "split": "auto", "profile": "Ubuntu"}, "keys": "ctrl+shift+u" }

That's a very nice feature!
