### ISSUE TITLE
Setting 'altGrAliasing' to 'false' disables AltGr

### ISSUE THREAD

**Issue by skrysmanski** [microsoft/terminal#7372]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2233.0

Any other software? No
```

# Steps to reproduce

1. Open Windows Terminal
1. Edit its settings and set `altGrAliasing` to `false` in `profiles/default`
1. Switch back to Windows Terminal and try to enter a character via `AltGr+...`

# Expected behavior

The appropriate character should appear.

# Actual behavior

Nothing is written.

**Comment by DHowett** [comment]
What keyboard layout are you using? Is it custom or did it come with Windows?

**Comment by skrysmanski** [comment]
@DHowett I'm using the regular German keyboard layout that came with Windows.

**Comment by zadjii-msft** [comment]
I suppose the next thing to do with this is 

/summon @lhecker

**Comment by lhecker** [comment]
[This](https://github.com/microsoft/terminal/blob/6acb9f8c90b1e4bc7837fd83fd60afddb46760bf/src/cascadia/TerminalCore/Terminal.cpp#L460) is missing a `&& !states.IsAltGrPressed()`.
