### ISSUE TITLE
Mouse Support not working for lazygit

### ISSUE THREAD

**Issue by ueberBrot** [microsoft/terminal#7378]
# Environment

Windows build number: Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.1.2233.0

Any other software?
[lazygit](https://github.com/jesseduffield/lazygit/)

# Steps to reproduce

I listed the issue first in the [lazygit repo (jesseduffield/lazygit/issues/759)](https://github.com/jesseduffield/lazygit/issues/759) but the author (@jesseduffield) let me know that it seems to be a problem of the Windows Terminal. So I'll post it here:

When trying to use the [basic mouse support](https://github.com/jesseduffield/lazygit/pull/529) from lazygit with Cmd or Powershell in Windows Terminal it doesn't work. When using Cmd and Powershell as a stand-alone application the mouse support for lazygit works just fine.

1. Install [lazygit](https://github.com/jesseduffield/lazygit/)
2. Add to your Path
2. With Powershell inside Windows Terminal cd into a repository and type `lazygit`
3. Try using the mouse to navigate the commits / branches / etc.

# Expected behavior

You should be able to use the mouse support the same way inside the Windows Terminal with Powershell or Cmd as with the stand-alone applications.

Expected using Powershell:
![Expected](https://user-images.githubusercontent.com/32489486/77770997-669fed00-7046-11ea-8420-6f368a54bd2d.gif)

# Actual behavior

When using Powershell inside the Windows Terminal you can't use the mouse at all for navigation. When I try to click on commits or branches, I can't do this, because the behavior of highlighting words is always executed.

Actual in Windows Terminal using Powershell:
![Actual](https://user-images.githubusercontent.com/32489486/77771129-964ef500-7046-11ea-93a7-331efd72d516.gif)

---

I don't know if it is a specific issue with lazygit or if other similar applications are also affected. I personally don't know of any other program that uses the mouse support in the same way.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+%22mouse+support%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #376 for more discussion.

/dup #376
