### ISSUE TITLE
better move focus to right if possible when removing focus, rather than to left

### ISSUE THREAD

**Issue by bef178** [microsoft/terminal#738]
The more often used tabbed application, Chrome (as well as Edge), uses the strategy to move the focus to right when removing focus.
That is: a **b** c d => a **c** d, when b removed

While, currently we: a **b** c d => **a** c d, when b removed

**Comment by zadjii-msft** [comment]
Seems like a good and just fix to me.

**Comment by Summon528** [comment]
Should we close this one because of #767 ?

**Comment by zadjii-msft** [comment]
Yes we should, I guess the "the" in that PR broke github's auto-linking.
