### ISSUE TITLE
Windows Terminal should open at the same position and screen it was closed before

### ISSUE THREAD

**Issue by t-mxcom** [microsoft/terminal#7381]
# Save window position

Windows Terminal always opens on the primary screen, a few pixels to the right and below it's last opening-position.
Most of the applications I use remember their window position when they get closed and re-open at the same position, on the same screen and in the same state (restored or maximized).

It would be great, if Windows Terminal does that too!

# Save and restore window position

Windows Terminal should save
* Window state (restored or maximized)
* Screen
* Position
and restore the values when it gets started again.

The only thing that should be considered is, that between closing Windows Terminal and re-opening it, the screen setup may have changed (screen removed), so that the saved position is in an invisible area. In this case, Windows Terminal should open at it's current "default" location.
In addition, I think that the window state "minimized" could be safely ignored when restoring the window position.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766
