### ISSUE TITLE
ssh password with special char(s) not working

### ISSUE THREAD

**Issue by tiolan** [microsoft/terminal#7393]
I connect from Windows Terminal (either cdm or ps) to Ubuntu 20.04 via ssh using password-only authorization.
My password has a special case "ü".
(I do not want to start a discussion on whether this is good practice or not)

The password is not accepted.
I verified with putty that everything works fine.
When typing "ü" in the terminal, I get the correct character.

Screenshot:
PS C:\Users\xxxxxx> ssh dev@Ubuntu-dev.mshome.net
Password:
Password:

Windows Terminal
Version: 1.1.2233.0

Note: This might not be directly related to Terminal, since I see the same problem with PS directly. Feel free to forward to the correct place.

**Comment by skyline75489** [comment]
This feels like a PowerShell issue. Are you using stock PowerShell, or PowerShell Core?

**Comment by tiolan** [comment]
This is the version I use:
PS C:\Users\xxxxx> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1

It is the one originally delivered with standard Windows.
Note: Using either powershell or cmd results in the same issue.

**Comment by zadjii-msft** [comment]
@tiolan Which `ssh` are you using? `ssh.exe` that ships with Windows? `ssh` from a WSL distro? Or some other `ssh`? And which version of `ssh`?

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/PowerShell/Win32-OpenSSH/issues/1620> could be related.

**Comment by tiolan** [comment]
Hey @zadjii-msft ,

I am using this one:
```
PS C:\Users\xxxxx> Get-Command ssh
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            7.7.2.1    C:\WINDOWS\System32\OpenSSH\ssh.exe
```

It is the one coming with standard Windows. Nothing else is installed, also WSL is _not_ installed.

**Comment by zadjii-msft** [comment]
@KalleOlaviNiemitalo Thanks for finding that!

@tiolan thanks for following up - this is definitely <https://github.com/PowerShell/Win32-OpenSSH/issues/1620> then. Thanks!

**Comment by tiolan** [comment]
Thanks @KalleOlaviNiemitalo ,
looks like a duplicate - I face the same problem. I will find out how to upgrade to v8.
