### ISSUE TITLE
Invalid characters when using pipe and npm package

### ISSUE THREAD

**Issue by Idered** [microsoft/terminal#7394]
# Environment

```none
Windows build number: 10.0.19041.450
Windows Terminal version (if applicable): 1.0.1401.0
Shell: CMD
Node.js: v10.16.3
```

# Steps to reproduce

* In CMD run `npx lsi` - [related package](https://www.npmjs.com/package/lsi) for directory listing
* It will print characters like `├` or `─` which is ok
* Run command again but piped to `find`: `npx lsi | find "git"`
* It will return `Γö£ΓöÇΓöÇ` instead of `├──`

# Expected behavior

✅ `echo "├─" | find "├"` returns `"├─"`
✅ `npx lsi` returns `├──`
✅ `npx lsi | find "git"` returns `├──`
✅ `npx boxen-cli "I ❤ unicorns"`: returns
```
┌────────────┐
│I ❤ unicorns│
└────────────┘
```

# Actual behavior

✅ `echo "├─" | find "├"` returns `"├─"`
✅ `npx lsi` returns `├──`
🟥 `npx lsi | find "git"` returns `Γö£ΓöÇΓöÇ` 
🟥 `npx boxen-cli "I ❤ unicorns" | find "unic"` returns
```
ΓöéI Γ¥ñ unicornsΓöé
```

**Comment by zadjii-msft** [comment]
I'm not sure who's mangling the text here, but I know that this can be worked-around by first doing a `chcp 65001` in `cmd`. I'd bet that `npx lsi` is emitting the line drawing characters as utf-8, and then `cmd` is treating them as your active code page (which probably isn't 65001)

**Comment by Idered** [comment]
@zadjii-msft thanks, I've added `chcp 65001` to my cmd startup file and it's now working properly 👍

**Comment by DHowett** [comment]
npx should be setting the codepage to 65001 on startup if it wants to print UTF-8 . . .

**Comment by zadjii-msft** [comment]
Yea, this sounds like an application bug to me. I don't really know whether this should be filed on `npx` or the individual tools themselves, but it's definitely expected behavior.

Thanks for following up!
