### ISSUE TITLE
Some system-defined environment variables are undefined

### ISSUE THREAD

**Issue by nathpete-msft** [microsoft/terminal#7399]
# Environment

```none
Windows build number: 10.0.20201.0
Windows Terminal version (if applicable): 1.3.2372.0

Any other software? Nope
```

# Steps to reproduce

In Powershell: `$Env:UserName`

In cmd: `echo %UserName%`

It looks like this variable is defined here: `HKEY_CURRENT_USER\Volatile Environment`

There are a couple of other variables defined there that are also undefined: `%USERDOMAIN%` and `%USERDNSDOMAIN%`

This is only happing after updating to the preview version of Terminal 1.3. The variables are still defined in Terminal 1.2, and when running pwsh/Windows Powershell/cmd outside of Terminal.

# Expected behavior

The variable should contain the current user name.

# Actual behavior

The variable is undefined.

**Comment by zadjii-msft** [comment]
Should this block 1.3?

**Comment by DHowett** [comment]
Yeah probably.

**Comment by DHowett** [comment]
Investigating: profile API _does_ **EXPLICITLY** add these vars (!) so i bet it's my token code
