### ISSUE TITLE
Keybinding for increasing fontSize (Swedish Keyboard layout)

### ISSUE THREAD

**Issue by einarpersson** [microsoft/terminal#7407]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2233.0

Any other software? No.
```

# Steps to reproduce

Note: This bug applies to **Swedish Keyboard Layout**.
Fresh install of Windows Terminal

**can** decrease fontSize by pressing `ctrl AND -`
**cannot** increase fontSize by pressing `ctrl AND +`
(note: the keybindings above is "default" in other apps, including Google Chrome and VS Code)

Notice that the default keybinding (reached by alt-clicking on settings) for increase fontSize is `ctrl+=`. The `=` is a key that does not exist on my Swedish Keyboard. I have a `+` instead.

Open `settings.json` in order to change keybindings.

**cannot** change the keybinding for increasing the fontSize from `ctrl+=` to `ctrl++` (it is marked as an error).

# Expected behavior

1. I expect that the default keybindings for increasing / decreasing fontSize "just works" for my Swedish Keyboard layout, just as it does in VSCode

2. I expect it to be possible to make keybindings to the `+`-key which I have on my keyboard.

# Actual behavior

See above.

**Comment by zadjii-msft** [comment]
I'm not sure how different the Swedish and German keyboard layouts are, but maybe #3788 might be useful?


(as a matter of linking related threads, #3737 looks related as well)

**Comment by carlos-zamora** [comment]
Oh, if you want to represent <kbd>Ctrl</kbd>+<kbd>+</kbd> as a keybinding, write it as `ctrl+plus`. We use '+' as a separator so that's why you were getting the error.

**Comment by einarpersson** [comment]
> Oh, if you want to represent Ctrl++ as a keybinding, write it as `ctrl+plus`. We use '+' as a separator so that's why you were getting the error.

@carlos-zamora That solved it! Thanks! I wonder however how you could help all these people with different keyboard layouts who expect this keybinding to work out of the box (once again: as it works in VSCode, Google Chrome, etc.).

I'm closing this now since I'm happy
