### ISSUE TITLE
Kerberized ssh client

### ISSUE THREAD

**Issue by Bugenhagen64** [microsoft/terminal#7408]
# Description of the new feature/enhancement
The built-in ssh clint in windows terminal can only do 'password' and ssh-keys.
It would be really nifty to be able to remote-login to servers using kerberos-tickets.
When being logged in to windows; we al-ready have the kerberos tgt.

# Proposed technical implementation details (optional)
SSO, using kerberized ssh client. Add capabilities to built in ssh client.
Putty's 'plink' can already do this but it has other problems.

**Comment by zadjii-msft** [comment]
This sounds like a feature request that's better suited for [](https://github.com/PowerShell/Win32-OpenSSH/issues), which is the home of the `ssh.exe` that ships on Windows. Thanks!
