### ISSUE TITLE
When selecting a new tab with the tab switcher, preview the selected tab in the Terminal

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7409]
The new tab switcher is great. But I think it'd be even cooler if as I was switching tabs with it, the content of the terminal changed to reflect the tab I had selected. 

So if I had [cmd, ubuntu, pwsh] open, with cmd focused, and opened the tab switcher to the "next tab", then the terminal would show me the ubuntu tab underneath the tab switcher. If I hit next tab again, then I want to see powershell underneath the switcher. Then, if I release the anchor key, just close the tab switcher. If I hit escape instead, then return me back to the tab I started on (cmd).

This is kinda a specialization of "Allow commands to be previewed in the command palette #6689", but this might be easier to do with the tab switcher, considering we already know that the original tab was (the state to restore to), and the command to use as the "preview".

I tried trivially implementing this today, but as I dispatched the commands from the cmdpal, the focus moved out of the cmdpal into the terminal, so that might be something to watch out for.

/cc @leonMSFT

**Comment by BartXZX** [comment]
One of the reasons I switched back to the old switching behaviour is because I often have 5+ tabs open with the same name, and selecting a tab without actually seeing what is on it is hard.

**Comment by nphmuller** [comment]
The lack of this feature is the main reason I disabled the tab switcher. I really like the switcher, but I like the previous behavior of seeing the content during "tabbing" better.
