### ISSUE TITLE
[Documentation] Please consider briefly explaining what .msixbundle is

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/terminal#7410]
Hello developers who maintain/program on the Terminal project.

Before I explain my issue, allow me to briefly (I try to be succint) the situation.

On my main machine (oldschool desktop) I use slackware linux, compiling almost everything from source via
ruby. On my laptop, I actually use win10 (for various reasons). On that win10 machine I have WSL1 too, 
ubuntu, and it works fine.

Oddly enough, I was also using oldschool cmd.exe quite a lot on that win10 machine, and while that works (I
can run my ruby code just fine), I actually grew tired of cmd.exe in general. This has many reasons, but one
big one is unicode-related problems aka the unicode symbols are not displayed properly.

There are some ways how to work around, so this is more my own lack of investing time here; I can use 
other terminal clients too such as Console or cmder - the latter is quite nice.

HOWEVER had, I also read about Terminal, and after the blog post here: 

https://devblogs.microsoft.com/commandline/introducing-windows-terminal/

and looking at screenshots (very important by the way!), I decided to skip console and cmder for now
and give Terminal a try. Actually my primary use case is to make unicode symbols work; for some
reason I really began to use LOTS of unicode symbols. So my commandline scripts are a tiny bit
GUI-like, since I use unicode symbols for additional information. :)

Anyway ... before I write too much, I was looking at the main README.md of Terminal here:

https://github.com/Microsoft/Terminal

Right now I am most interested in how to install it. The readme encourages the windows store; I am
using it, but the store actually annoys me (also asking me to "go login ... but I don't want to login,
I just want to download+install ... "). It is also a bit slow to start, a few seconds ...

So my second choice was oldschool release page - this one is MUCH faster and so much more
convenient for linux folks ;)

https://github.com/microsoft/terminal/releases

And here I typically see four Assets:

    Microsoft.WindowsTerminal_1.2.2381.0_8wekyb3d8bbwe.msixbundle
    Microsoft.WindowsTerminal_1.2.2381.0_8wekyb3d8bbwe.msixbundle_Windows10_PreinstallKit.zip
    Source code (zip)
    Source code (tar.gz)

I can skip Source code for the time being. However had, I have ABSOLUTELY no idea what a
".msixbundle" is ... I am used to .exe and .msi but what is .msixbundle? Will that work? Right now
I don't know; I may try at a later time.

But here is my request: Would it be possible that the main README also very BRIEFLY mentions
what a msixbundle is or how to install it? I assume double-click may suffice ... but, as said, right
now I don't know, so perhaps a sentence there could be helpful. Another reason I try to avoid the
story is that I actually keep track of what I am installing/downloading in text-files, which I can then
use for ruby to batch-install stuff (on linux typically, but I am adjusting to win10 as well right now,
although I have not yet reached the fully-automated batch-installation there). Hopefully extending
the main README with a brief mention or explanation what is .msixbundle, and also what the
difference is to the "PreinstallKit", would be helpful. Thanks! Please feel free to close this issue
at any moment in time, to keep the issue tracker smaller. :)

**Comment by DHowett** [comment]
Hey, thanks for the feedback! You're right -- we should document this a little better.

For now:

The msixbundle is like a `msi` that installs a "packaged application". You can just double-click the msixbundle and it will choose the right version of Terminal (probably 64-bit/amd64/x64) from inside the bundle to install.

It looks like this:

![image](https://user-images.githubusercontent.com/189190/91336109-46579400-e786-11ea-9fc3-68e83c3a689d.png)

**Comment by ShadowWalker98** [comment]
Hello, I've never contributed to open-source before, is there any way I can help with this?

**Comment by zadjii-msft** [comment]
@ShadowWalker98 sorry for the late reply - must've been lost in my inbox. 

After re-reading the original report, I'm thinking that the update to the README in https://github.com/microsoft/terminal/pull/9474 might actually satisfy this issue. I think that PR clarifies enough what an `.msixbundle` is, or at least what to do with one.

**Comment by ShadowWalker98** [comment]
@zadjii-msft Hi, thanks for the update! Is there anything else I can check out?

**Comment by zadjii-msft** [comment]
Generally this list is a good place to start: https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+label%3A%22Easy+Starter%22+-label%3A%22In-PR%22+

#8924 might be a simple place to start - I think it should be as simple as setting the [`Placement`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutbase.placement?view=winrt-19041#Windows_UI_Xaml_Controls_Primitives_FlyoutBase_Placement) of the new tab menu to `FlyoutPlacementMode::BottomEdgeAlignedLeft` in `TerminalPage::_CreateNewTabFlyout`. Hopefully that's a one-line change? If it's not, then pick really anything on that list ☺️

**Comment by biggestsonicfan** [comment]
I found this when searching for "msixbundle vs msixbundle_Windows10_PreinstallKit", but the difference isn't actually described [here](https://github.com/microsoft/terminal/issues/7410#issuecomment-681016838).

**Comment by DHowett** [comment]
The preinstall kit is documented [here](https://learn.microsoft.com/en-us/windows/terminal/distributions) now.
