### ISSUE TITLE
Tab Background Extend Terminal

### ISSUE THREAD

**Issue by bnb** [microsoft/terminal#7411]
# Description of the new feature/enhancement

As an extension of the idea of Tab Colors that was announced today, it would be wonderful if tab backgrounds could fully extend whatever's in the Terminal. For example, if I've set my background to pure black, extend that into the tab. If I've set it to an image, include the tab height in the image rendering and show the tab with the image as the background.

# Proposed technical implementation details (optional)
¯\\\_(ツ)_/¯

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #702 for more discussion.

/dup #702
