### ISSUE TITLE
Support keyboard interaction in tab color selector

### ISSUE THREAD

**Issue by guywaldman** [microsoft/terminal#7412]
# Description of the new feature/enhancement

Choose "Set tab color..." from the Command Palette (or right click on a tab and choose "Color...") - the tab color selector pops up:

![image](https://user-images.githubusercontent.com/6546430/91338276-5e0e3700-e7dd-11ea-943a-d40d57d806ca.png)

It currently does not support keyboard interaction, which would be really nice for us terminal nerds who like to keep the fingers off the mouse as much as possible.

P.S. Thanks for Windows Terminal, you folks are doing an awesome job!

**Comment by DHowett** [comment]
The tab color picker should follow the same keyboarding flow as all other UI -- namely that you can navigate it with <kbd>Tab</kbd> and select things with <kbd>Space</kbd> or <kbd>Enter</kbd>.

Is that not working?

**Comment by zadjii-msft** [comment]
I'm guessing you're looking for "The Tab Color Picker should be navigable with the arrow keys", issue #6675?

**Comment by guywaldman** [comment]
@DHowett Yes, @zadjii-msft beat me to it :)
<kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> are working for navigation, was just expecting arrow keys navigation over anything else.

Thank you both, closing for deduplication (didn't find the other issue when searching for it).
