### ISSUE TITLE
Colored tab bug

### ISSUE THREAD

**Issue by scriptingstudio** [microsoft/terminal#7413]
v1.2.2381.0 on Windows 10.
You can see on the images uncolored bottom curve.

![part1](https://user-images.githubusercontent.com/17237559/91339746-94e54c80-e7df-11ea-9fea-1852c5967720.png)

![part2](https://user-images.githubusercontent.com/17237559/91339755-99116a00-e7df-11ea-8adc-4d02e150a9d0.png)

![part3](https://user-images.githubusercontent.com/17237559/91339760-9b73c400-e7df-11ea-9f19-13ff49be86fa.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #7133 for more discussion.

/dup #7133
