### ISSUE TITLE
Support synchronization among panes please~

### ISSUE THREAD

**Issue by Panlichen** [microsoft/terminal#7426]
# Description of the new feature/enhancement

Please support synchronization among panes, like `Shift+Cmd+i` in iTerm2 on Mac, and `:setw synchronize-panes` in tmux, it's quite useful sometimes.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2634 for more discussion.

/dup #2634
