### ISSUE TITLE
Open a new-tab in the same terminal window

### ISSUE THREAD

**Issue by ShauryaAg** [microsoft/terminal#7429]
# Description of the new feature/enhancement

A feature to open a new-tab in the same terminal windows as current one just by using the command **wt new-tab -p "CMD"**. The current implementation offers to open a completely new window which defeats the purpose of having multiple tabs. 
**Alternatively:** Being able to merge tabs from one window to another just by dragging and dropping (similar to what we find in 
google chrome and other browsers)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472

As far as tab tear-out goes, please refer to #1256, and more broadly #5000
