### ISSUE TITLE
setcolorscheme command producing an error

### ISSUE THREAD

**Issue by cis-admin** [microsoft/terminal#7432]
Running the latest Windows Terminal Preview, Version: 1.3.2382.0, and I'm seeing the following error when trying to invoke the setcolorscheme command:

> Warnings were found while parsing your keybindings:
> • Found a keybinding that was missing a required parameter value. This keybinding will be ignored.

Here is the command I am using in my settings.json:

> { "command": { "action": "setColorScheme", "name": "One Half Dark" }, "keys": "ctrl+shift+i" },

The color scheme, One Half Dark, is present in my schemes. Any idea why I may be seeing that error?

**Comment by zadjii-msft** [comment]
The parameter is "scheme", not "name" ☺️ 

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings#set-the-color-scheme-preview

**Comment by DHowett** [comment]
Closing answered. Thanks!

**Comment by cis-admin** [comment]
Thanks for letting me know! It looks like the release notes need to be updated since it says "name" and not "scheme":

https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-3-release/

**Comment by zadjii-msft** [comment]
@cinnamon-msft Hey could you go fix the blog post?

**Comment by cis-admin** [comment]
So it looks like I still get the same error when inputting:

> { "command": { "action": "setColorScheme", "scheme": "One Half Dark" }, "keys": "ctrl+shift+i" }

**Comment by cinnamon-msft** [comment]
https://github.com/microsoft/terminal/pull/6993

Should the schema require "colorScheme" rather than "name"?

**Comment by cis-admin** [comment]
> 
> 
> #6993
> 
> Should the schema require "colorScheme" rather than "name"?

That worked!

**Comment by zadjii-msft** [comment]
Yea, I derped and posted the wrong thing _after literally opening the docs to the right page_ 😅 my bad!
