### ISSUE TITLE
Insider Dev / Release preview do not receive Terminal preview

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#7437]
# Environment

```none
Windows build number: Insider Dev 20201
Windows Terminal version (if applicable): 1.1.2233.0

Any other software?
nothing related
```

# Steps to reproduce

- sign in to Windows Release Preview, Beta or Dev Channel
- install / update Terminal App from Store

# Expected behavior

Supposely all channels will receive store based apps as soon as possible also previews.
The expection is to receive 1.3.x as an Insider.

# Actual behavior

Terminal does not receive previews, but stays at release channel via Store

**Comment by zadjii-msft** [comment]
Did you install the "Windows Terminal" app, or the "Windows Terminal (Preview)" app? They are different apps so that users can have our own release channels side-by-side, like edgium does.

**Comment by Karl-WE** [comment]
Thanks for the hint I was not aware there is a preview app seperately.
yet I have the non preview Terminal it correct my expectations it should update to 1.2.x but it does not either. 

https://github.com/microsoft/terminal/releases/tag/v1.2.2381.0?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEwOTkwMDgwODM6NDU2NTc3NTI%3D

**Comment by zadjii-msft** [comment]
Yea, that's just how the Store works some times. It's not necessarily the best at rolling out updates - I'm pretty sure half our users are still on 1.0 😆

**Comment by Karl-WE** [comment]
@zadjii-msft are you sure to close? we might want to bring this up? Even when seeking for updates manually in the Store App it does not provide me 1.2

**Comment by Karl-WE** [comment]
have a look at me comment over here. https://github.com/microsoft/winget-cli/pull/367#pullrequestreview-444320484

**Comment by zadjii-msft** [comment]
Yea, there's nothing we can do on our end to bump the Store to try and have it roll updates out to users faster. If you're already working with the winget folks, they're the most likely people to be able to change this for the better.
