### ISSUE TITLE
The keyboard shortcut: "ctrl + j = ←", "ctrl + i = ↑", "ctrl + l = →", "ctrl + k = ↓" is broken.

### ISSUE THREAD

**Issue by haosmos** [microsoft/terminal#7438]
# Environment

```none
Windows build number: 10.0.20201.0 Microsoft Windows NT 10.0.20201.0
Windows Terminal version: 1.2.2381.0

Any other software?
```

# Steps to reproduce

I have set up the replacement of keyboard shortcuts in "PowerToys" using the "Keyboard Manager" option: 

```
ctrl+j = ← 
ctrl+i = ↑ 
ctrl+l = → 
ctrl+k = ↓
```

This is very convenient — it will allow you to hold both hands in the center of the keyboard without having to often use the arrows on the side of the working area on the keyboard. 

In v1.2.2381.0 version these key combinations are broken. 

But the combination: "ctrl + h = Backspace" works.

I had to roll back to v1.2.2234.0 where the keyboard shortcuts work. 

There is also a problem with keyboard shortcuts in Windows Terminal Preview v1.3.2382.0.

# What I expect

By pressing the key combination ctrl+j I expect to get the command "←". 

By pressing the ctrl+i key combination I expect to get the "↑" command. 

By pressing the ctrl+l key combination I expect to get the command "→". 

By pressing the ctrl+k key combination, I expect to receive the command "↓". 

# What happening actually

By pressing "ctrl+j", "ctrl+i", "ctrl+l", "ctrl+k", Windows Terminal does not react in any way — nothing happens. In other programs, the specified keyboard shortcuts work correctly. In the Windows Terminal v1.2.2234.0 version, the specified keyboard shortcuts also worked correctly.

**Comment by zadjii-msft** [comment]
I wonder if they're sending these re-mapped keys with a scan code of 0.

Actually I'd bet on it.  That's the only thing I can think of that changed in that timeframe

**Comment by DHowett** [comment]
It is funny that we have issues going both directions. "PowerToys remapepd keys send garbage to my terminal" "PT remapped keys no longer work"

I bet the answer is more nuanced than "ignore/keep scancode=0 events"

**Comment by mathiasringhof** [comment]
Not sure if this is related, I'm using the software Talon to control the computer by voice. Since the last date the cursor keys stopped working.

**Comment by lesleyrs** [comment]
Hi, how come `Ctrl+i` does not do anything in windows terminal or powershell? Can't see it being bound to an action and an application I'm using requires it. Same goes for some other key combinations.

**Comment by DHowett** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/189190/203650970-dd82538b-033d-4cf8-aa7e-b4c59f63e182.png">

They look like they are working fine!

FYI: this issue has been closed for _two years,_ and whatever you are experiencing is probably not the same thing. I'd encourage you to file a new issue.
