### ISSUE TITLE
Shift-Tab through powershell window goes back one command then switches outside of window

### ISSUE THREAD

**Issue by mtquigley** [microsoft/terminal#744]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  Microsoft Windows [Version 10.0.18895.1000]

* What you're doing and what's happening: entering get- and hitting shift-tab to cycle through available options

* What's wrong / what should be happening instead: should be cycling through available commands, instead only cycles back one command then focus leaves window. Regular tab cycling works as expected.

![image](https://user-images.githubusercontent.com/49215683/57638958-80425e00-7574-11e9-88c1-1e72d0939a85.png)

**Comment by zadjii-msft** [comment]
Hmmmm. 

Looks like the TermControl doesn't totally eat `tab` keypresses, and lets focus escape to other controls. This should be fixed.

**Comment by LukeDearden** [comment]
seems to be left shift + tab  moving focus to the menu in the top right. I keep accidentally opening new tabs all the time. Different behavior to last week

**Comment by corbob** [comment]
Did this fix make it into the preview that's in the Windows Store?
