### ISSUE TITLE
process exited with code ...

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7440]
In a new Ubuntu (split pane) these two commands

tmux list-client
exit

lead to

[process exited with code 1]

I don't know who's at fault there but I would like to know how to get rid of the dead split pane when this happens.

**Comment by DHowett** [comment]
Set `closeOnExit` to `always`. There is a number of these issues on the repo already 😄

**Comment by vefatica** [comment]
I like getting the message; it has already exposed a bug in one of my own!  :-)

Ctrl+Shift+w is what I was after (didn't look hard enough earlier).

**Comment by DHowett** [comment]
Ah! Excellent.
