### ISSUE TITLE
Can't launch Terminal, "the service has not been started" error.

### ISSUE THREAD

**Issue by asvc** [microsoft/terminal#7442]
# Environment

```none
Windows build number:  Microsoft Windows NT v10.0.18363.0
Windows Terminal version: v1.3.2382.0
```

# Steps to reproduce
1. Download `Microsoft.WindowsTerminalPreview_1.3.2382.0_8wekyb3d8bbwe.msixbundle`
2. Install via `Add-AppxPackage`

# Expected behavior
1. Windows terminal can be started as usual

# Actual behavior
1. Error window pops-up, complaining about an undefined service:
![image](https://user-images.githubusercontent.com/300146/91526285-c8fd6200-e8f2-11ea-9d87-c1a016e46df5.png)
2. Using "Reset" function in WFP preferences does nothing.
3. There is no "Windows Terminal" or similar service. It is not obvious what should be started.

**Comment by DHowett** [comment]
Can you check `appxsvc` or `wlidsvc`? They may be required on your first installation.

**Comment by asvc** [comment]
Thanks, `wlidsvc` is indeed disabled. Any insight as to why "Microsoft Account Sign-in Assistant" is necessary to run a terminal emulator?

Started the service:
```cmd
$ sc query wlidsvc

SERVICE_NAME: wlidsvc
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
Trying to start the Terminal:
![image](https://user-images.githubusercontent.com/300146/91549876-2d321d00-e917-11ea-8e6e-430e67f8c555.png)

**Comment by zadjii-msft** [comment]
IIRC (and I might be wrong here, haven't had much coffee yet) - that service is needed by the Store to ensure that all the dependencies are installed. There's a lot more discussion over in #6010, so in the interest of consolidating all the relevant info to one thread, I'd recommend following up in that thread. Thanks!

/dup #6010

**Comment by asvc** [comment]
@zadjii-msft , thanks, can confirm that un-packing the bundle and running it manually works.
