### ISSUE TITLE
New "actions" structure not recognized in schema

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#7443]
Missing a few things in the schema:
- "actions" (in place of "keybindings")
   - it'd be nice if we could do a schema deprecation thing for "keybindings" but it might be too soon for that :/
- "name" (in the context of commands, not profiles)
   - this also means that "keys" is no longer required
- "commands"
   - should accept a list of "command" objects

**Comment by zadjii-msft** [comment]
We'll also need `icon`, `iterateOn` added as well.

Also `name` can also be an object in `{ "key": string }` format.
