### ISSUE TITLE
I cant start terminal

### ISSUE THREAD

**Issue by Keynars** [microsoft/terminal#7444]
[Hello](url) I installed the program but can't run it
![Ekran Görüntüsü (109)](https://user-images.githubusercontent.com/70369222/91539518-1fce6000-e922-11ea-87d5-c50b03ee679a.png)

**Comment by zadjii-msft** [comment]
Hey so a rudimentary internet translation of that error message looks like it's the same message as #7442, just translated to Turkish. I'd take a look at that thread for more details. Thanks!

/dup #7442
