### ISSUE TITLE
Weird scrolling problem (one-off)

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/terminal#7445]
# Environment

```none
Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): `Version: 1.2.2381.0`
```

# Steps to reproduce

I can't tell whether that had anything to do with it, but I opened VS 2019, while it was loading my project I was starting Windows Terminal with a PowerShell 6.2.4 shell, and started to `cd` into my project's git repo folder (I also have poshgit installed). Then suddenly Windows Terminal started scrolling and wouldn't stop. It scrolled both when maximised and non-maximised. I switched focus to a different window and back to Windows Terminal and it kept happening. It always scrolled to a specific point and started scrolling again as soon as I typed a letter. Interestingly, when I pressed "Stop Recording" in OBS to finish my video, the Terminal stopped doing that weird scrolling... I cannot completely rule out that this was some form of "stuck key on my mouse/keyboard" but I rather don't think so, as this behaviour was so specific and it stopped scrolling by itself too, always at exactly the same point.

The video shows me trying to "scroll back down" to see the prompt, and then the weird, automatic "line-by-line" scrolling. (I have a higher quality .mkv but GitHub won't let me upload MKV or a gif larger than 10 MB).
![scrolling_bug mkv](https://user-images.githubusercontent.com/4967343/91542694-222abd00-e916-11ea-8cb3-c36f8170ae93.gif)

# Expected behavior

Normal scrolling behaviour.

# Actual behavior

See above.

**Comment by DHowett** [comment]
*wow*, this is really wild. I wonder if something's driving terminal through the accessibility infrastructure?

It might be enlightening to run something like KeyboardStateView (nirsoft) to see if there's some keyboard keying events being emitted . . . but otherwise, I'm at a total loss for how to investigate this.

**Comment by patrikhuber** [comment]
Yep... I think it's unlikely this will happen again, so feel free to do whatever you like with the issue... :) Perhaps it makes sense to close it, and if it happens again, there's a record of this having happened already.

**Comment by DHowett** [comment]
Fair enough. Do let us know if it comes back! :smile:
