### ISSUE TITLE
Feature Request: Ability to open a split pane the existing tab's profile.

### ISSUE THREAD

**Issue by Jack-Punter** [microsoft/terminal#7450]
# Description of the new feature/enhancement
Keybinding like `alt+shift+plus` and `alt+shift+minus` that open the new panel with the same profile as the existing (or current if there are multiple panels already open) profile, apposed to the default profile.

Having multiple panes is useful, however as I am starting to WT more. I am finding it very annoying to use the `alt` + click in the drop down method of opening new split panels when I am not using my default profile. I.e. When I am using the WSL this is not a problem (as this is my default profile), however when I'm using the developer command prompt/powershell provided with visual studio, the extra time/clicks can get quite annoying. I have worked around this issue for now, by simply creating shortcuts that start the WT in these, non-default, profiles with two panes already open

**Comment by zadjii-msft** [comment]
You can already duplicate a pane with an action like the following:

```json
        { "command": { "action": "splitPane", "split":"auto", "splitMode": "duplicate" }, "keys": [ "ctrl+alt+t" ] },
```

Which will show up as a "Duplicate pane" in the command palette.

When #1571 lands, you'll be able to add the same action to the new tab dropdown as well.
