### ISSUE TITLE
Double middle click on taskbar preview to close despite confirmation modal

### ISSUE THREAD

**Issue by Ariane-B** [microsoft/terminal#7451]
# Description of the new feature/enhancement

If I want to close a program/window, I'll often hover it in the taskbar, then middle-click the preview that appears. If there are multiple tabs open, though, a modal shows up asking me if I'm sure. That's fine. I like those kinds of warnings. But it completely blocks me from closing the window from the taskbar.

What several (sadly not all) programs do in those cases is interpret the second middle click as a confirmation and close right away. I wish Windows Terminal did this as well.

# Proposed technical implementation details (optional)

When there's currently a confirmation modal and I send another "close" command through a taskbar middle click, I wish Windows Terminal would interpret this as "Yes, I'm sure" and close.

**Comment by zadjii-msft** [comment]
This seems like a reasonable request to me. Thanks!

**Comment by DHowett** [comment]
That's definitely a good idea. Thanks!
