### ISSUE TITLE
Global hotkey to toggle terminal

### ISSUE THREAD

**Issue by Inndy** [microsoft/terminal#7453]
# Description of the new feature/enhancement

[iTerm 2](https://www.iterm2.com/documentation-hotkey.html) has a feature called `Toggle All Windows`
You can specify a global hotkey to toggle terminal window. It would be nice to have this feature in Windows Terminal. 😏 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
[Please search before filing new issues.](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22Global+hotkey%22+)

/dup #653

**Comment by Inndy** [comment]
@zadjii-msft I had found this issue before I create this issue. But it said "drop down" which is different from "toggle".

**Comment by zadjii-msft** [comment]
That's kinda the megathread for that entire scenario. There's a [whole ton of variation](https://github.com/microsoft/terminal/issues/653#issuecomment-661370107) on that theme in that thread, and I don't think we need a separate thread for "appear" vs "dropdown"
