### ISSUE TITLE
Right click on Terminal icon in the taskbar to open a pop-up menu to let me select the shell to open.

### ISSUE THREAD

**Issue by GrantMeStrength** [microsoft/terminal#7455]
# Description of the new feature/enhancement

Right click on Terminal icon in the taskbar to open a pop-up menu to let me select the shell to open.
Saves me having to open at least one shell before I can open another of the type I happen to want at this instant.

# Proposed technical implementation details (optional)

Right click, menu, same list of shells as when I click the (not style consistent ahem) down arrow in the terminal title bar.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #576 for more discussion.

/dup #576
