### ISSUE TITLE
"Run as administrator" not working consistently

### ISSUE THREAD

**Issue by MikeMcCollister** [microsoft/terminal#7456]
My primary account is a standard user account. I have a separate account which I use for admin. I rarely ever log into my admin account. That said, sometimes I would like to bring up a Windows Terminal as admin. I get some real strange results.

Here is my setup:

- Mike is my standard user account.
- MikeAdmin is my admin account.
- Mike always has the latest Windows Terminal installed. Currently 1.2.2381.0
- MikeAdmin may or may not have the latest Windows Terminal installed, depending on the Microsoft Store.
- Windows Terminal is pinned to my task bar on the Mike account.

**Strangeness #1**

1. Have Windows Terminal on the Mike (standard user) account.
2. Right click on the Windows Terminal task bar icon, click on "Windows Terminal" and select "Run as administrator".
3. Type in password for MikeAdmin account.
4. Note that nothing happens.
5. See that the Windows Terminal in the Start Menu is transparent and has a progress bar on it, like it is being updated.
6. Close the Windows Terminal for the standard user and pinned Windows Terminal icon in the taskbar goes away.
7. Reboot and the Windows Terminal in the Start Menu is back to normal.
8. Pin Windows Terminal back on the task bar.

**Strangeness #2**

1. Don't have Windows Terminal running with the Mike account.
2. Right click on the Windows Terminal task bar icon, click on "Windows Terminal" and select "Run as administrator".
3. Type in password for MikeAdmin account. Note that I have to do this twice.
4. Get the following error message

![image](https://user-images.githubusercontent.com/67375253/91609154-e22efe80-e944-11ea-827b-8fdd79012be1.png)

That's all for now.

Regards,

Mike

**Comment by WSLUser** [comment]
Dupe: https://github.com/microsoft/terminal/issues/5000, probably others underneath that.

**Comment by DHowett** [comment]
Yeah -- there are some lingering issues with store installation. There's a lot of into in the linked threads, and in other closed issues on our repo. The long/short of it is that **you must register terminal as an application for any user account that wants to run it.** Store applications are nominally per-user, and you can't easily cross a user boundary with them.
