### ISSUE TITLE
Underline extended after window resize

### ISSUE THREAD

**Issue by IFICL** [microsoft/terminal#7459]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.2.2381.0

Any other software? No
```

# Steps to reproduce

When I am using WSL. I installed Oh-my-zsh and used plugins `zsh-syntax-highlighting` and `auto-suggestion`.
When I enter the path in the terminal, it will be underlined because of `zsh-syntax-highlighting` plugin. Everything is fine here as you can see.
![image](https://user-images.githubusercontent.com/20180169/91629199-d5d29200-e994-11ea-8e84-583ccfb2cd13.png)

But once I resize the window or hide the window, the underline will be extended to the longest range and cannot get recovered. 
![image](https://user-images.githubusercontent.com/20180169/91629234-2ba73a00-e995-11ea-800c-3c8e13f6b7a8.png)

# Expected behavior
Resize the window won't have any effect on the display.

# Actual behavior

Resize the window or hide the window, the underline will be extended to the longest range and cannot get recovered.
![image](https://user-images.githubusercontent.com/20180169/91629260-6d37e500-e995-11ea-98e6-f168cd0489c7.png)

**Comment by j4james** [comment]
This is essentially the same bug as issue #32.

**Comment by DHowett** [comment]
Yep! Thanks @j4james. /dup #32

**Comment by Sourav8457** [comment]
I'm also facing the same issue
