### ISSUE TITLE
Windows Terminal presence breaks Windows Start Quick Launch of any Folder

### ISSUE THREAD

**Issue by zakutin** [microsoft/terminal#7461]
# Environment

```none
Windows build number: Microsoft Windows 10 Pro 2004 x64 [Version 10.0.19041.450]
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
- N/A (freshly installed Windows)
```

# Steps to reproduce
After Windows 2004 update I noticed that the quick launch of any folder using Windows Start became buggy. I got used to launch the folders and any apps with help of Win button. And after the fresh installation of the Windows 2004 I experimentally detected, that the presense of Windows Terminal in the system breaks the usual behavior of the quick and fluent folder opening. I created an empty user account and installed Windows Terminal from Microsoft Store. The behavior is clearly reproducible. On the previous version of Windows 1909 everything was working well with Terminal installed. This issue is observed on both of my laptops.

I'm not sure if this is a Terminal issue or new Windows version 2004, that's why I'm reporting this here.

It does not brake the quick launch of the apps. It only relates to folders, as far as I noticed.

Steps to reproduce (assume Windows Terminal is installed):
1. Press Win button (or click Start with mouse)
2. Type any existing folder name you want to open
3. Press Enter
4. The search window is **stuck** and **not disappeared** to bring the focus on the opened folder.

# Expected behavior
The folders shall be launched fluently. Search window shall disappear after Enter is pressed.

# Actual behavior
You can see this on the video. I create a test account in Windows only to install the Terminal. At the beginning the quick folder launch works well, the focus goes to the opened folder and search window disappears after Enter is pressed. As soon as Terminal is installed, the quick folder launch is stuck and folder is blinking on background. That interrupts the fluent and quick usage of the search, as the user has to make some additional actions to switch on the opened folder (win+tab or mouse action).

Can anyone confirm this behavior?

https://youtu.be/16ULVHmZOvk

**Comment by skyline75489** [comment]
This is like what know in #7122 and it’s currently a known issue. You may found that thread helpful

**Comment by DHowett** [comment]
Yep! Thanks, @skyline75489. /dup #7122

Thanks for the additional info @zakutin

**Comment by zakutin** [comment]
Thanks for info!
