### ISSUE TITLE
Document Ctrl-A and Select All Capabilities (If it exists)

### ISSUE THREAD

**Issue by imanabu** [microsoft/terminal#7463]
I was unable to find any information on how to perform Select All capability with the Terminal. The current key bindings description describes Copy and Paste, but not Copy All (in the buffer).

Ctrl-A works to the extent that when I paste a line and perform Ctrl-A, it does select the entire line I have pasted.

The expected behavior is as you would get in the MacOS Terminal, that it will select everything in the buffer.

**Comment by KalleOlaviNiemitalo** [comment]
I believe <https://github.com/microsoft/terminal/issues/4993> covers this. Ctrl+Shift+A for `selectAll` is listed in the spec <https://github.com/microsoft/terminal/pull/2840>.

Windows Terminal currently passes Ctrl+A to the session. If you run PowerShell there, then PSReadLine implements a Select All for Ctrl+A. But this is not available if you run Command Prompt instead.
