### ISSUE TITLE
Cannot type or interact with terminal

### ISSUE THREAD

**Issue by lucasyvas** [microsoft/terminal#7464]
# Environment

```none
Windows build number:  Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): Version: 1.2.2381.0
```

# Steps to reproduce

Try to type or click into the terminal

# Expected behavior

Can type characters in the terminal, right-click, etc.

# Actual behavior

Cannot type any character or interact with the terminal in any way. Previously it worked fine, but something has changed and now I cannot do anything with the terminal.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/4448> suggests that disabling "Touch Keyboard and Handwriting Panel Service" could cause this.

**Comment by lucasyvas** [comment]
@KalleOlaviNiemitalo Thanks for the suggestion, but that service is already set to Manual and has the recommended default registry values from that post. I've not ever messed with that.

**Comment by FenderBaba** [comment]
> #4448 suggests that disabling "Touch Keyboard and Handwriting Panel Service" could cause this.

Thanks a lot !
That was the tip. Everything is ok now.

**Comment by DHowett** [comment]
@lucasyvas If you explicitly _start_ that service, does keyboard input start working?

**Comment by FenderBaba** [comment]
After, enable the **Ink Workspace** and the **Tablet Input Service** again, the Terminal works as it should. It's strange to understand, why this 2 services should be enabled on a pure Desktop machine. 
Because i was looking for un-needed resource eater on my DAW, I did this "cleanup task" to disable some services, and the receipt followed immediately: "punishment after self-experiment".

**Comment by lucasyvas** [comment]
@DHowett Nope... is it possible this is permission related? I may have recently altered some innocuous looking Windows privacy settings, but that's all I can think off.

**Comment by lucasyvas** [comment]
OK weird it now works. Everything looks the same but I did it once more and tossed in a reboot for good measure. Maybe at that to the list of recommended steps after flipping all the correct switches :)

**Comment by DHowett** [comment]
That's really quite strange, and I'm not sure where to go from here.

Somebody mentioned that they've got MSI Afterburner running, and exiting it made input start working again. That doesn't seem like a completely reasonable thing to do, but ... you know. Software is rarely reasonable!

**Comment by lucasyvas** [comment]
I'll take a look at what else is running and report back.

**Comment by lucasyvas** [comment]
I believe this is caused by running Rivatuner Statistics Server in my case, which is a utility that caps framerate to smooth frame times.
