### ISSUE TITLE
"Open in Windows Terminal"

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7468]
Nice touch!  It is also convenient to have such a menu item for "HKCR\Drive" and "HKCR\Directory\Background".  "HKCR\Directory\Background" gets you a right-click on the desktop (along with backgrounds in Explorer windows).

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by KalleOlaviNiemitalo** [comment]
"HKCR\Drive" seems to be <https://github.com/microsoft/terminal/issues/6654>.

"HKCR\Directory\Background" is <https://github.com/microsoft/terminal/issues/6414>, blocked by a Windows bug.

**Comment by vefatica** [comment]
Thanks. I couldn't read the MSFT report.  I know you're using a shell extension.  Experimenting with the registry-shell-command mechanism for directory\background and drive showed me that something was wrong.  More experimenting led to a couple kludges (below) that make it work everywhere, that is, for drives and directory\backgrounds (including drive backgrounds).  I have no idea why they work.  Note the extra space and backslashes. 

Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\Directory\Background\shell\WT]
@="TerminalHere"
[HKEY_CLASSES_ROOT\Directory\Background\shell\WT\command]
@="\"wt.exe\" nt -d \"%V\\ \""
[HKEY_CLASSES_ROOT\Drive\shell\WT]
@="TerminalHere"
[HKEY_CLASSES_ROOT\Drive\shell\WT\command]
@="\"wt.exe\" nt -d \"%V\\\""

**Comment by DHowett** [comment]
Thanks for the additional info here. So, @KalleOlaviNiemitalo is right about this being a /dup of #6654,#6414 :smile:
