### ISSUE TITLE
support environment variables in --startingDirectory param

### ISSUE THREAD

**Issue by jmlucjav** [microsoft/terminal#7469]
# Description of the new feature/enhancement

It would be very nice to be able to use environment variables (most useful to open with some script with predefined tabs in diff places etc)

# Proposed technical implementation details (optional)

Envvars are resolved

**Comment by DHowett** [comment]
What specific issue are you seeing? This definitely works today.

![image](https://user-images.githubusercontent.com/189190/92186891-0be89980-ee0d-11ea-8102-870082bea749.png)

**Comment by jmlucjav** [comment]
my bad! indeed it works
