### ISSUE TITLE
Wrong color in some places

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#7471]
# Environment

```none
Windows build number: 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.3.2382.0
MC version: 4.8.24
```

# Steps to reproduce

Open a centos7 server via ssh or open any file with vim with a dark terminal theme. Not sure if this is a bug, but can I somehow fix it using the terminal? There are simply no such shades in my settings.json
![image](https://user-images.githubusercontent.com/35394377/91654875-33f69680-eab5-11ea-88fd-fa64871a3ac7.png)
![image](https://user-images.githubusercontent.com/35394377/91654898-64d6cb80-eab5-11ea-8180-d99b7d322275.png)

# Expected behavior

The yellow and green colors will correspond to the colors specified in the terminal settings

# Actual behavior

Colors don't match settings

**Comment by Mystic8b** [comment]
Okay, there are 256 colors displayed, can there be some way to reduce the number of shades or display forcibly 8/16 colors?

**Comment by DHowett** [comment]
You will need to set your `TERM` environment variable to `xterm` or some other terminal that does not have 256-color support. There is no way to suppress the support for 256 colors _on Terminal itself._

Alternatively, you can simply reconfigure those applications (bash, vim) to not emit 256-color color indices.
