### ISSUE TITLE
Not obvious how refer to CMD.exe batch file extensions - Google Cloud SDK shell 

### ISSUE THREAD

**Issue by JulesVerny** [microsoft/terminal#7473]
I am having a real problem trying to set up the Google Cloud SDK Shell in Windows terminal, which is just a cmd.exe extension. 

I need to execute the command: C:\WINDOWS\system32\cmd.exe /k ""C:\Program Files (x86)\Google\Cloud SDK\cloud_env.bat""

But Windows Terminal Fails with an error C:Program not recognised.

**Comment by skyline75489** [comment]
You may want to tweak the path a little bit. Obvious it's the `Program Files` being recognized as `Program`. You can check out https://github.com/microsoft/terminal/blob/master/doc/user-docs/ThirdPartyToolProfiles.md for some example.

**Comment by JulesVerny** [comment]
Yes its a lot escape wrangling, but following your advice, I followed the Visual Studio command example, which also via Program Files(x86) . And use the following:- 

"commandline": "cmd.exe /k \"C:/Program Files (x86)/Google/Cloud SDK/cloud_env.bat\"",
 "icon": "C:\\Program Files (x86)\\Google\\Cloud SDK\\cloud_platform_logo.ico",

Works well, so I can invoke the Google SDK shell in Windows Terminal now. 

Many Thanks
