### ISSUE TITLE
Keyboard shortcut for 'set mark' in nano no longer working via ssh

### ISSUE THREAD

**Issue by kmlucy** [microsoft/terminal#7474]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.2.2381.0
```

# Steps to reproduce

1. Have an ssh profile to a Debian machine setup as follows:
```
{
	"name": "NAME",
	"commandline": "ssh USER@FQDN",
	"hidden": false
},
```
2. Edit a file in nano
3. Attempt to use the keyboard shortcut `ctrl+6` to set the mark

# Expected behavior

The mark to be set. This works in a local Debian profile, as well as locally on the server I am ssh'ed to. It used to work as described in a previous version of Terminal (a few months ago).

# Actual behavior
Nothing happens

**Comment by DHowett** [comment]
There have been some changes to terminal input that give _more information_ to applications. Unfortunately, this exposed an issue in Win32-OpenSSH 7.7. It is fixed in Win32-OpenSSH 8.1.

More information in the upstream bug, /dup https://github.com/PowerShell/Win32-OpenSSH/issues/1310
