### ISSUE TITLE
font size 11 is the same as 12 on 100% scaling

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#7475]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.3.2382.0
screen resolution: 1366x768
scaling: 100%
(also happens at 720p 100% scaling and 1080p 100%.
doesn't repro at 1080p 150% scaling)

Any other software?
```

# Steps to reproduce

1. make sure "fontsize" is set to 12
2. set it to 11 and save settings file

# Expected behavior

font size 11 is smaller than 12

# Actual behavior

they are the same size

**Comment by dsevolve23** [comment]
STOP ALL THIS SHIT NOW DANIEL...I SAW TERRA IN HERE..PRETTITERA GODDAMN IT!!!

**Comment by skyline75489** [comment]
What is the font you are using?

**Comment by LuanVSO** [comment]
Cascadia Mono

**Comment by DHowett** [comment]
This is due to a difference in how we render hinted text. I believe it is covered by /duplicate #5093 as part of #1790. Thanks!
