### ISSUE TITLE
Execute default commands => terminal launch or new tab

### ISSUE THREAD

**Issue by V1NAY8** [microsoft/terminal#7477]
# Description of the new feature/enhancement
- I want a terminal configuration where I should be able to run a command automatically on launching it.
- No need to check if the command is working.
- Support for multiple commands.

### Whom this is helpful for?
- Developers who want to setup environment using script. ( ./runWhileTerminalLaunches.sh)
- Execute git any commands (git fetch --dry-run)

# Proposed technical implementation details (optional)
For Example:
- Consider a Scenario using python virtual environment.
- So each time opening a new tab, a command has to be executed to activate the virtual environment.
- Assume I created a virtualenv for python named **venv**.
- In settings.json add "defaultCommand" along with the command to execute
```json
{
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "Windows.Terminal.Wsl",
    "defaultCommand": "source /mnt/c/Work/venv/bin/activate"
}
```
- So when I open a new tab it runs the command and sets my environment.

```bash
source /mnt/c/Work/venv/bin/activate
(venv)
```

**Comment by WSLUser** [comment]
Have you read https://docs.microsoft.com/en-us/windows/terminal/tutorials/ssh? 

So `"commandline": "source /mnt/c/Work/venv/bin/activate"`

**Comment by V1NAY8** [comment]
@WSLUser 
I think it only works with ssh.
I am trying to execute a command in WSL 2 in Ubuntu with the following:
settings.json
```json
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "fontFace": "MesloLGS NF",
                "commandline": "source /mnt/c/Work/venv/bin/activate"
            }
```
![image](https://user-images.githubusercontent.com/33659563/91800106-0725b900-ec46-11ea-9fb8-96d5dbdbf0d5.png)

**Comment by DHowett** [comment]
We will not be offering startup commands, because they are wildly different for every shell. Look up how to start cmd, or powershell, or bash, or zsh, or ssh (which will later spawn one of the above shells) and configure your profile to launch that shell with the command pre-seeded. This is easy for users to configure because they know what shell they’re using, but hard for us to offer because we do not.
