### ISSUE TITLE
Windows Terminal Remote Desktop New Tab Key CTRL+SHIFT+2 not working

### ISSUE THREAD

**Issue by ket000** [microsoft/terminal#7480]
I am using Windows Terminal Version 1.2.2381.0 on Windows 10 1909 (18363.1016) and when ever I press CTRL+SHIFT+2 thru 9 on a remote desktop session, it does not launch the new tab. I can manually launch the new tab using Mouse. This seems to be specific to remote desktop session only. It works fine when not using Remote Desktop. Please suggest a fix or workaround.

**Comment by DHowett** [comment]
I'm not having any trouble doing this over remote desktop. What keyboard layout are you using on the client and server?

**Comment by ket000** [comment]
Not sure what keyboard Layout I am using. It is english keyboard. Again on
my local machine using the same keyboard it works fine. On remote machine,
Pressing ctrl+shift+1 or 2 and nothing happens. I can launch them using
mouse.

**Comment by zadjii-msft** [comment]
@ket000 Do other <kbd>Ctrl+Shift</kbd> key chords work via remote desktop, or is it just <kbd>Ctrl+Shift+1</kbd> and <kbd>Ctrl+Shift+2</kbd> that don't work?

Do <kbd>Ctrl+Shift+1</kbd> and <kbd>Ctrl+Shift+2</kbd> work in other applications via remote desktop? Usually browsers will use <kbd>Ctrl+Shift+num</kbd> as a shortcut for "go to tab _num_"

**Comment by ket000** [comment]
Sorry for not responding earlier. I tested again today using Remote Desktop and CTRL+SHIFT+2 is working now. Version of Temrinal is : 1.2.2381.0. I have uninstalled an app clipclip which may be conflicting with the keyboard shortcut. Thanks for looking into it.

**Comment by zadjii-msft** [comment]
Glad to hear it! Hopefully that info will be helpful for future readers ☺️
