### ISSUE TITLE
Cross tab/pane variable use

### ISSUE THREAD

**Issue by M-Watson** [microsoft/terminal#7483]
# Description of the new feature/enhancement
The ability to declare variables in one pane or tab and call them from another. This might be difficult/impossible across different types of pane instances (e.g. one PowerShell and one bash), but at least for panes that are the same type. 

A user could use this for a multi-pane set up where one is for live data that sets a variable as it continuously runs and the other pane is used for any quick analytics on the most recent variable declaration. 

This could be accessed by the tab/pane ID or name along with the variable. Something like a declaration of variable $users in Tab-2. Then in Tab-1 someone could call Tab-2.$users and retrieve the data set in Tab-2.

**Comment by WSLUser** [comment]
Can you provide a bit more detail for your example of how this would be used? Pretend what you wanted existed, how does that look to you from a practical perspective. (I have some data i've grabbed from a mongo db that I want to call in a variable that can be reached from another tab/pane). Something like that (not sure if I accurately got the sentiment down).

**Comment by KalleOlaviNiemitalo** [comment]
In principle, part of this could be implemented with a format similar to xterm's OSC 52 (Manipulate Selection Data). However, it would require changing the shells as well, and I think those changes would be unlikely to be accepted if the feature were not supported by any other terminals.

PowerShell variables have the extra complication that their values might not be serializable.

**Comment by DHowett** [comment]
Thanks for the request! I'd rather offer application developers, and shell users, better forms of IPC than "they happen to be living in the same Terminal". Sorry!

I'm going to close this one out in favor of ecosystem improvements that everybody can get behind, not something that's specific to one or two terminal emulators on Windows.
