### ISSUE TITLE
Cannot load PSReadline module..

### ISSUE THREAD

**Issue by Grace2705** [microsoft/terminal#7484]
Anytime i open windows terminal i get Cannot load PSReadline module.  Console is running without PSReadline.
I tried runing the Get-Module PSReadline, but it doesn't do anything

**Comment by KalleOlaviNiemitalo** [comment]
If you are using Windows Terminal Preview 1.3 and 32-bit PowerShell 5.1, then this could be a duplicate of <https://github.com/microsoft/terminal/issues/7418>.

To confirm, what are the values of the following variables in your PowerShell session?

```
$PSHome
$PSVersionTable
$Env:PSModulePath
```
