### ISSUE TITLE
How to install pre-release versions without screwing up the official version ?

### ISSUE THREAD

**Issue by reckoner** [microsoft/terminal#7488]
Hi,

I have a lot of personal configurations that I don't want to lose, but I still would like to try the prerelease versions. I have the official release installed via the Windows Store. How can I install the prerelease versions and still go back to my official version if things don't work out. Thanks!

**Comment by LuanVSO** [comment]
you can install them both side by side from the store. 
make sure to set the right alias in settings>apps>apps and resources>app execution alias
otherwise it might set wt to point to the preview version

**Comment by reckoner** [comment]
Actually, I was referring to installing the prerelease versions of "Windows Terminal Preview". So, the issue is between the official version of "Windows Terminal Preview" and its prerelease versions [here](https://github.com/microsoft/terminal/releases)

**Comment by LuanVSO** [comment]
have you installed it through the Microsoft store or downloaded directly from GitHub
?

**Comment by DHowett** [comment]
You can’t install two different versions _of the prerelease version_ at the same time. Preview installs over Preview and Stable installs over Stable.

The latest versions available on GitHub are also the same as the latest versions available on the store.

**Comment by LuanVSO** [comment]
in any case "Windows Terminal" and "Windows Terminal Preview" are two completely different packages and one can't interfere in the behavior of the other with only this exeption:
> otherwise it might set wt to point to the preview version
