### ISSUE TITLE
cursor disappears after backspace on input method

### ISSUE THREAD

**Issue by robinZhao** [microsoft/terminal#7491]
The problem remains in 10.0.18363.1016
![](https://raw.githubusercontent.com/robinZhao/images/master/issue.gif)

_Originally posted by @robinZhao in https://github.com/microsoft/terminal/issues/158#issuecomment-684135117_

**Comment by j4james** [comment]
This sounds like issue #810. It has been fixed, but the fix was only released in Insider Build 20161.
