### ISSUE TITLE
fat-arrow ligature (and others?) are rendered incorrectly in some cases

### ISSUE THREAD

**Issue by Kirides** [microsoft/terminal#7493]
# Environment

```none
Windows build number: `Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0`
Windows Terminal version (if applicable): `Windows Terminal Preview Version: 1.1.1812.0`
```

# Steps to reproduce

1. use Powershell with `AgnosterPlus` theme from `oh-my-posh`
    - `Import-Module oh-my-posh`
    - `Set-Theme AgnosterPlus`
1. Use `Cascadia Code PL` or `Cascadia Mono PL` as `fontFace`
1. enter `() =>` into the terminal

# Expected behavior

image taken from VS Code:
![grafik](https://user-images.githubusercontent.com/13602143/91840394-e9aa1c80-ec50-11ea-8ec4-010efebc3309.png)

# Actual behavior

image taken from Windows Terminal:
![grafik](https://user-images.githubusercontent.com/13602143/91840444-fcbcec80-ec50-11ea-8c01-597b79a39e5f.png)

typing any character after the closing paren.:
![grafik](https://user-images.githubusercontent.com/13602143/91840747-7d7be880-ec51-11ea-9c3b-83bc01546197.png)

**Comment by DHowett** [comment]
Ligatures do not render when the color changes in the middle of the ligature.
