### ISSUE TITLE
Background color of current line turns black after first space in Powershell Core

### ISSUE THREAD

**Issue by rageshkrishna** [microsoft/terminal#7494]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

1. Start a Powershell Core tab
2. Enter anything, space, anything

# Expected behavior

The background color of the current line remains the same after a space.

# Actual behavior

The background color of the current line turns black from the point after the first space

![image](https://user-images.githubusercontent.com/1134972/91858715-36a8e580-ec87-11ea-8ac6-4567ae1bb5fc.png)

**Comment by j4james** [comment]
See issue #6767. There was apparently a fix in the works for PSReadLine, although I'm not sure if it's available yet. You may just need to upgrade.

**Comment by rageshkrishna** [comment]
Thanks @j4james, that did the trick.

For anyone else that ends up here, follow the instructions at https://github.com/PowerShell/PSReadLine#upgrading to upgrade PSReadLine.
