### ISSUE TITLE
Automatically change to replace mode, if run vim on WSL

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#7497]
# Environment
 
Windows build number: 2004(OS build 19041.450)
Windows Terminal version (if applicable): v1.2.2381.0

Any other software?
Ubuntu 20.04 WSL
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)

# Steps to reproduce
Just, I tried vim for file edit. if run vim, Automatically change to replace mode. not every time.
If i five time run vim, two, three time change to replace mode.
If you want see this bug, do not open new file. must open exist file with vim.
and I never run SSH.

**Comment by DHowett** [comment]
Please search before filing new issues.
