### ISSUE TITLE
空行

### ISSUE THREAD

**Issue by gj1279** [microsoft/terminal#7500]
最下面总有一行或者多行空行

**Comment by DHowett** [comment]
@skyline75489 Mind helping out with this one? :smile:

**Comment by skyline75489** [comment]
I think this is #7445 or similar but I'm not sure because the description is uttely vague.

为了社区的良好发展，请不要删除 issue 模板，提供尽可能多的信息（For the sake of the community, please do not remove the issue template and provide as much as information as you can)。
