### ISSUE TITLE
Hide text cursor indicator in terminal

### ISSUE THREAD

**Issue by DarrellDD** [microsoft/terminal#7503]
Hide the new "text cursor indicator" in the terminal, or have an option to.

The text cursor indicator looks off while having the block cursor on, it obscures text above the line which could be important to see. Modern IDE's like intelliJ already hide the text cursor indicator, so I think the Windows terminal should do aswell.

![image](https://user-images.githubusercontent.com/22918553/91943388-cf2d7d00-ecfc-11ea-8cc3-b67ec901dfc6.png)

I think the removal, of the option to disable the text cursor indicator in the terminal would look better, less distracting and wouldn't obscure important text above the input line.

**Comment by DHowett** [comment]
When you enable this _global, system-wide accessibility feature_, Terminal will follow the _global, system-wide accessibility settings_. Sorry.
