### ISSUE TITLE
No bright colors under screen/irssi in SSH session

### ISSUE THREAD

**Issue by sec** [microsoft/terminal#7506]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version 1.2.2381.0 and Preview 1.3.2382.0
```

# Steps to reproduce
1. SSH to remote machine (FreeBSD used here)
2. run 'screen irssi'
3. under irssi: /exec colors.sh

[colors.sh](https://gist.github.com/sec/e13173521d9742302f7db83bb3594c84)

# Expected behavior

Bright colors (bottom part of the image)

# Actual behavior

Only "normal" colors are visible (top part of the image), like the bright/bold are replaced by normal ones:
![image](https://user-images.githubusercontent.com/288111/91970058-6273ac00-ed17-11ea-9606-6a83c7bc89ad.png)

Bottom part is when irssi is launched without "screen".
Colors are working fine when using Windows Terminal v1.1.2233.0

**Comment by DHowett** [comment]
_screen is another terminal emulator_, and as such it has the chance to manipulate all colors that come through it.

Can you share the output of `echo $TERM; infocmp` inside and outside screen?

**Comment by sec** [comment]
> _screen is another terminal emulator_, and as such it has the chance to manipulate all colors that come through it.
> 
> Can you share the output of `echo $TERM; infocmp` inside and outside screen?

Yes I know that, but weird it started to behave that way after upgrade to 1.2.
TERM inside screen is `screen`
TERM outside screen is `xterm-256color`

I don't have `infocmp` as I'm on 11.4 (can provide more info when I'll upgrade the box to 12).

I tried setting TERM to `xterm-256color` and even `screen-256color` inside screen, then launching irssi - still no bold colors.
Weird this is, that under screen, colors are ok, it's just that launching irssi is causing this weird behavior.

Just found that if I set TERM to xterm and then `screen -r` - colors are fine. Looks like `xterm-256color` is broken, at least for me :)
Any way I can set TERM to something else under Windows Terminal ?

**Comment by DHowett** [comment]
I believe I've seen this before, actually. When `screen` believes that the outer terminal is true-color-compatible, but cannot handle certain other sequences, it will _translate_ the colors on the inside. In 1.2 we actually improved color rendition... which tends to expose applications doing unexpected things.

Can you run `script`, and then reproduce the screen+irssi color issue? It should produce a document named `typescript` that contains the raw output from screen that we're receiving in the Terminal. I'd be interested in seeing that document.

**Comment by sec** [comment]
[Issue with colors](https://gist.github.com/sec/7b8b18251e2e3fac1a203a9ca3a33f53)
[No issue with colors, launched irssi outside screen](https://gist.github.com/sec/7b8b18251e2e3fac1a203a9ca3a33f53)

**Comment by DHowett** [comment]
Thanks! So, bad news. (Those two pastes are the same thing, but:)

The inbox termcap for screen-256color suggests that _all colors must be rendered using ITU extended sequences_. This means that irssi is translating `\e[91m` to `\e[38;5;1m\e[1m`. We (and many other terminal emulators) decided that brighten/intensity should not apply to the extended ITU colors (#5384)... so this translation is "incorrect" from the perspective of modern terminal emulation.

The updated terminfo seems to specify that colors should be treated with more care (cf [this entry](https://invisible-island.net/ncurses/terminfo.src.html#tic-xterm_256setaf) for `xterm+256setaf`, which is the base type for screen-256color), but perhaps that hasn't reached your ports tree yet.

The resolution to this one is, for now, "by design". Sorry!

**Comment by jdebp** [comment]
* https://github.com/irssi/irssi/blob/a0544571a80196e5b7705f56e6e2cbcdf7b4d80e/src/fe-text/term-terminfo.c#L429
* https://github.com/irssi/irssi/blob/a0544571a80196e5b7705f56e6e2cbcdf7b4d80e/src/fe-text/term-terminfo.c#L405

These seem to be the parts of irssi to look at.  Notice that they are triggered when irssi thinks that it is talking to an 8-color terminal, which of course the termcap database says that the `screen` terminal type is.
