### ISSUE TITLE
Updates break current running instances

### ISSUE THREAD

**Issue by narfanar** [microsoft/terminal#7509]
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0 . But also:
![image](https://user-images.githubusercontent.com/5769148/92007181-e8a6e700-ed45-11ea-935e-7caadb2ca8bf.png)
Take your pick :T
Windows Terminal version (if applicable): 1.3.2382

# Steps to reproduce

1. Have an open instance.
2. Install update from Store (stupid of me, I know; but IT were debugging another issue and enabled all the update flags you could think of...)

# Expected behavior

Update fails OR waits until I close my instance.

# Actual behavior

Update succeeds. My instance icon disappears from the taskbar. All jobs started in consoles in the instance seem to be alive in the background. But now I gotta kill them all and restart :((((

![image](https://user-images.githubusercontent.com/5769148/92008180-1a6c7d80-ed47-11ea-836e-bdd0d7c4c44d.png)

**Comment by DHowett** [comment]
This is discussed at length in /dup #6726 :smile:
