### ISSUE TITLE
[Documentation] Please provide an explanation or a link from the main README.md towards "how to start/use WSL with Windows Terminal"

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/terminal#7512]
I was finally able to install Windows Terminal; had to use the powershell command for this. I just mention this because in my last issue request I asked for a short comment how to install these .msiaxbunddle thingies. Anyway.

I am testing WSL1 a lot and I would like to start it from Windows Terminal (this one is ubuntu from the store).

Would it be possible to add, onto the main README.md, a short link towards this? Something like:

"Making use of Windows Terminal with WSL (Windows Subsystem for Linux)" or something like that?

Just a quick link. This would help save me googling for random documents which can be quite tedious.

I'd even suggest to make it easily possible to start the WSL from within Windows Terminal, but I'd just
need documentation right now. I look more on the main README as the entry point; it's ok to use
external links to point to other documentation, just a few helpful points for the main README would
be nice here. Thanks for reading this issue request; please feel free to close it at any moment in time.

**Comment by DHowett** [comment]
I am not sure I understand the issue. Every WSL distribution you have installed is automatically added to the dropdown menu...

![image](https://user-images.githubusercontent.com/189190/92021170-3869bc00-ed0e-11ea-82cf-0984ac0a5480.png)

they even have penguin icons so you know they are Linux...

**Comment by vadimkantorov** [comment]
Maybe the author refers to help with guidance about enabling WSLv1 / WSLv2 and installing a distro from store. E.g. WSLv1 requires enabling a windows feature, and WSLv2 would often require going to BIOS to enable virtualization (in addition to installing a windows feature update)...
