### ISSUE TITLE
terminal gives error when up arrow key is pressed

### ISSUE THREAD

**Issue by abhi887** [microsoft/terminal#7517]
whenever up arrow key is pressed more than 10 times in a row , terminal gives out following error - 
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -44.

**Comment by skyline75489** [comment]
Please do not remove the issue template. Which version of Windows Terminal are you using? Are you using CMD, PowerShell or WSL?

**Comment by KalleOlaviNiemitalo** [comment]
If this is in PowerShell, please try upgrading PSReadLine as recommended in <https://github.com/PowerShell/PSReadLine/issues/1306>.

**Comment by abhi887** [comment]
> Please do not remove the issue template. Which version of Windows Terminal are you using? Are you using CMD, PowerShell or WSL?

Windows Terminal version 1.2.2381.0
I'm using powershell

**Comment by DHowett** [comment]
As the error message indicates, you must report the issue on the PSReadline repository.

For now, /dup https://github.com/PowerShell/PSReadLine/issues/1306
