### ISSUE TITLE
error 0x800702e4 when launching `C:\Program Files\Far Manager\Far.exe'

### ISSUE THREAD

**Issue by ipizhenko** [microsoft/terminal#7520]
# Environment

```none
Windows version:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version: : 1.2.2381.0

Far Manager 3.0.5656 x64
```

# Steps to reproduce

1. Install Far Manager under default path (get latest "stable" MSI package from https://www.farmanager.com/)
2. Add Far Manger to Terminal configuration:
```json
		{
			"guid": "{A5B49406-27A2-49C1-8E03-A878A158C852}",
			"name": "Far Manager",
			"commandline": "C:\\Program Files\\Far Manager\\Far.exe",
			"hidden": false
		},
```
3. Try to create new tab in the Terminal

# Expected behavior

Far Manager runs in the new tab

# Actual behavior

Getting error message:
```none
[error 0x800702e4 when launching `C:\Program Files\Far Manager\Far.exe']
```

**Comment by DHowett** [comment]
That error code indicates that you have configured `Far.exe` to **require** admin permissions.

**Comment by ipizhenko** [comment]
Hi, yes, that's true. I need Far to run with admin privileges to be able to operate on any files in the system w/o extra questions each time. So what should I do now to allow Far working this way?

**Comment by DHowett** [comment]
Until #1032 is complete, you will need to run Terminal as admin to run Far inside it as admin.
/dup #1032
