### ISSUE TITLE
unlimited history

### ISSUE THREAD

**Issue by davidbIQ** [microsoft/terminal#7525]
I'd like to have the ability to set how much scrollback history the terminal handles, ie if I set 1,000,000 lines I'd like to be able to scrollback that far.  the limit of I think 9999 in current powershell.  It's one thing that putty offered that always drove me crazy as a short coming of powershell.

**Comment by DHowett** [comment]
Thanks for the request! We are tracking this in /dup #1410

**Comment by DHowett** [comment]
The current practical limit for Terminal is 32000

**Comment by davidbIQ** [comment]
Thanks :), usually I needed to just bump mine to be 20,000 in putty, it would be nice to have it configurable higher still for the odd time it's needed, but I can understand not wanting to have it default to alot more than that :)
