### ISSUE TITLE
Bash Powerline in ssh and Git bash

### ISSUE THREAD

**Issue by dobbleg1000** [microsoft/terminal#7527]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```
git bash
powerline installed on remote linux system

# Steps to reproduce
Produce Actual:
install git bash on windows
add git bash to windows terminal (I used https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal)
open bash in windows terminal
ssh into remote system with properly installed powerline

Produce Expected:
open git bash
ssh into remote system 

# Expected behavior

colors to be displayed properly for powerline as they are when running git bash directly 
![expected](https://user-images.githubusercontent.com/11370810/92188593-9f789500-ee22-11ea-868b-f454becd4714.png)

# Actual behavior

colors are just grey 
![actual](https://user-images.githubusercontent.com/11370810/92188587-9c7da480-ee22-11ea-8532-85614dd5b758.png)

**Comment by DHowett** [comment]
What version of Git for Windows have you installed? How are you accessing that server? Are you using the version of `ssh` that comes with git bash, or are you using the version of ssh that comes with Windows?

**Comment by DHowett** [comment]
(There are certain versions of git-for-windows that use an older cygwin/msys runtime that cannot support many of the color codes in use by powerline.)

**Comment by dobbleg1000** [comment]
Thanks for the quick response

which ssh 
produces this
/usr/bin/ssh

so i presume that it is the one that came with git bash

I was using Git for windows version 2.24.0. I am updateing to  2.28.0
(Slow internet)
And will retest

**Comment by dobbleg1000** [comment]
That worked  🤦‍♂️ 
Thanks for the help

**Comment by DHowett** [comment]
I’m glad that it worked! Thanks!
