### ISSUE TITLE
Preview, nextTab, prevTab. default bindings?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7529]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1016 (1909)
Windows Terminal Preview 1.3.2382.0
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
With more than one tab open, press Ctrl-Tab or Ctrl-Shift-Tab.

# Expected behavior

As documented, nextTab or prevTab

# Actual behavior
Either gives tabSearch.

**Comment by DHowett** [comment]
Set `useTabSwitcher` to false if you don’t want the new tab switcher experience.

**Comment by DHowett** [comment]
(This is called out in the release notes, which are handcrafted for every single release so preview users know what they are previewing.)

**Comment by vefatica** [comment]
The documentation and the release notes give contradictory information.

**Comment by DHowett** [comment]
It would be helpful if you would point out how they are contradictory! That’s the only way we’ll be able to fix it...

**Comment by vefatica** [comment]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings ("Tab Search (Preview)" section) says tabSearch is not bound.

https://github.com/microsoft/terminal/releases says it's bound to nextTab and prevTab.

**Comment by DHowett** [comment]
I mean... the release notes say that next/prevTab will now display an ephemeral tab switching UI. They also go on to say that _there is a separate action, tabSearch, that can be bound._ The binding hasn’t changed, and they do not open tabSearch.

**Comment by DHowett** [comment]
(The ephemeral tab switching UI and the tab search feature use the same list, but they are intentionally distinct UI surfaces.)

**Comment by vefatica** [comment]
Then the discrepancy is here:
![image](https://user-images.githubusercontent.com/61856645/92193983-9b0aa700-ee37-11ea-9697-45684ba9bd36.png)

 versus

![image](https://user-images.githubusercontent.com/61856645/92194035-b5dd1b80-ee37-11ea-8582-416868502770.png)
