### ISSUE TITLE
Support command snippet and quick command

### ISSUE THREAD

**Issue by oyealex** [microsoft/terminal#7531]
When some common commands are used, some command fragments can be cached and quickly invoked by shortcut keys or buttons. This function is similar to the Xshell's quick command set.

**Comment by skyline75489** [comment]
Lately sendInput was added to fix #3799. It should help you do what you want to some extent.

**Comment by oyealex** [comment]
> Lately sendInput was added to fix #3799. It should help you do what you want to some extent.

ok, got it, thx
