### ISSUE TITLE
Minicom: can't press ctl+a z to bring up help

### ISSUE THREAD

**Issue by tyeth** [microsoft/terminal#7533]
# Environment

```none
Windows build number: Win32NT  Microsoft Windows NT 10.0.20175.0 
Windows Terminal version (if applicable):  1.2.2381.0

Any other software? git for win latest 
```

# Steps to reproduce
load terminal (PS by default).
ssh to pi zero
run minicom on a serial port
try to activate in-app help with CTRL+A Z

# Expected behavior
help will load

# Actual behavior
nothing, and have to kill terminal

**Comment by zadjii-msft** [comment]
@tyeth Which `ssh` are you using? `ssh.exe` that ships with Windows? `ssh` from a WSL distro? Or some other `ssh`? And which version of `ssh`?

**Comment by tyeth** [comment]
Forgotten sorry, but looks like I'm describing running powershell with
windows insider (recent powershell) with git for windows providing ssh via
mingw I believe.

**Comment by zadjii-msft** [comment]
Okay, when you're `ssh`'d into the pi, could you run `showkey -a` and hit <kbd>ctrl+a</kbd>, <kbd>z</kbd>? It should look something like this:

![image](https://user-images.githubusercontent.com/18356694/94799673-19138c80-03a9-11eb-9690-7eb07be3d9b2.png)

**Comment by tyeth** [comment]
Strangely unrecreatable. All keys fire as expected, thanks a lot for your support. I will remember the showkeys if it comes up again.
