### ISSUE TITLE
Define vim color scheme related to the windows terminal theme

### ISSUE THREAD

**Issue by pumpingiron** [microsoft/terminal#7535]
Hello,

I'd like to be able to apply the good vim's color scheme in accordance with the windows terminal theme defined.
In putty or Iterm, I use a variable defined when loading the profile whether it is a dark or bright theme that  I can reuse later according to what I wanna do.

So, Is there an already integrated solution or has anyone ever tried to do that ?

Thanks in advance.

**Comment by DHowett** [comment]
What variable is that? If there is prior art for exposing the terminal's color scheme to connected applications, we could consider following it.

**Comment by pumpingiron** [comment]
I don't understand.

I just wanna apply the correct color scheme in my vim editor related to my terminal color scheme.

For example, If I launch my terminal in a bright mode, i wanna get my vim editor in a bright mode too, so how can i get the terminal color scheme information in order to be able to detect it in my vimrc file and apply it when it's needed, and the same in reverse for a dark display ?

**Comment by skyline75489** [comment]
#3718  could be a solution. Unfortunately WT has not yet support it.

**Comment by pumpingiron** [comment]
Sorry, I had forgotten this issue.

I've found the solution in the meantime, you juste have to get WT_PROFILE_ID variable's content which corresponds to your loaded profile's id with colorization etc ...
Then from there, if your .bashrc configuration is well designed, you can autodetect all other colorization's parameters like in vim for example.

I'm gonna close the issue.
