### ISSUE TITLE
Add ability to quickly launch Windows Terminal with a desired profile instead of the one set currently as default.

### ISSUE THREAD

**Issue by sleepyeldrazi** [microsoft/terminal#7540]
# Description of the new feature/enhancement

Allow users to choose which profile to start from the task bar when right clicking the icon. In other words, add a similar functionality to the "Pinned", "Frequent" folders which show when right clicking File Explorer. This will be helpful if for example a WSL developer who has set WSL as the default profile needs to run CMD or Powershell commands, not to have to open terminal, open the correct profile and close the WSL profile. It will be a time and frustration saver.

**Comment by skyline75489** [comment]
Well you’re a lucky man. We just have #7515 merged which should be available in a month or two.

**Comment by sleepyeldrazi** [comment]
That's great news! I'm closing this then.
