### ISSUE TITLE
Does wt support C-a C-u C-e C-k ... , just like the Linux or macOS terminal?

### ISSUE THREAD

**Issue by ccwanggl** [microsoft/terminal#7541]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Those key bindings are handled by the shell. PowerShell can be configured to use them. Look up “Set-PSReadlineKeyHandler”.

If you are using bash inside Terminal, they will automatically work (depending on your `.inputrc`).
