### ISSUE TITLE
Please add scrollHome and scrollEnd

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7542]
# Description of the new feature/enhancement

actions:
scrollHome - scroll to earliest history
scrollEnd - return to input line

# Proposed technical implementation details (optional)
 bindings:
scrollHome - Ctrl+Shift+Home
scrollEnd - Ctrl+Shift+End

**Comment by DHowett** [comment]
Proposal: `scrollToTop` and `scrollToBottom`.
Counterbalance: `selectAll` (part of #715)

If there was a special mode, selection mode, that you could enter and it would let you move around the cursor with all your keys... would that be acceptable?

If so, #5804 is a spec for that mode. :smile:

**Comment by vefatica** [comment]
It's not a matter of acceptability.  I didn't follow that thread well.  I don't want to move the cursor; I want to scroll the history. If you're suggesting more than one keystroke to scroll the history, I won't like it.  Up, down, pgup and pgdn are fine as they are ... it just needs a couple more.

**Comment by vadimkantorov** [comment]
This would be very useful, since when the program prints very fast and scrollbar isn't at very bottom, then it's impossilbe to dock it back to bottom, since printing is faster than human moving the scrollbar
