### ISSUE TITLE
Text cut off using Powershell + SSH

### ISSUE THREAD

**Issue by slothrop49** [microsoft/terminal#7543]
# Environment

Microsoft Windows [Version 10.0.19041.450]
Windows Terminal Preview 1.2.2382.0

Any other software?
No

# Steps to reproduce

Open Terminal
Open PowerShell (7.0.3)
SSH into router (Asus AX88U)
run any command where the output is wider than the Terminal window

# Expected behavior

Output will wrap when at end  of line.

# Actual behavior

Test stops at end of line - wider window more text, narrower window less text

Running SSH from PowerShell directly produces expected behaviour (wrapping)- the problem only exists if PowerShell is started from Terminal.  Text wrapping in Terminal is normal otherwise (when not using SSH).

**Comment by DHowett** [comment]
When you SSH to your router, can you run `echo $TERM; stty -a`?
What command are you usually encountering this with?

**Comment by slothrop49** [comment]
stty is not complied in to Asuswrt (or Asuswrt-Merlin which I use) not available from entware, so I get `-sh: stty: not found`

I first noticed this where I was looking at Firewall stats  `/jffs/scripts/firewall stats search ip 10.55.63.150 10
`  , but I get this with any command where the output extends beyond the terminal width - e.g. if i run dig in a narrow window

As noted originally, this only happens if Terminal > Powershell > ssh.  If I run run Powershell > ssh directly (Windows inbuilt or 7.0.3) then I get the expected text wrapping.

**Comment by DHowett** [comment]
So, this is a long shot. Can you grab a "debug tap" trace for me? It'll capture your input and output, and I'm interested in figuring out whether the data is getting lost in Terminal or in the layer underneath terminal.

Here's the info:
https://github.com/microsoft/terminal/issues/6634#issuecomment-647728401

**Comment by slothrop49** [comment]
Sorry to be dense but I cannot get 'debug tap' to work,  I have tried adding 
	"debugFeaturesEnabled": true, 
 to settings.json, both directly under "defaultProfile" and then under "defaults" 

What am I doing wrong?

**Comment by zadjii-msft** [comment]
Sorry, there's a typo in that comment. The setting is `"debugFeatures": true`, and just put that directly under `defaultProfile`, not under `defaults`. Sorry for the confusion!

**Comment by slothrop49** [comment]
I have set "debugFeatures" and it is now working.   With this enabled the content in the left hand window is now wrapping correctly.  How do you want the data output saved and sent (e.g. 2 x plain text files or something else).

**Comment by DHowett** [comment]
Sorry -- somehow this didn't show up in my inbox. You can feel free to e-mail me (address is in my profile) any bug report info you still have. Really sorry about missing this update!
