### ISSUE TITLE
Ligatures stop working on some devices when a string exceeds three characters

### ISSUE THREAD

**Issue by lygamac** [microsoft/terminal#7545]
![image](https://user-images.githubusercontent.com/49118209/92314087-86631600-efd3-11ea-92f9-b1be7bbef094.png)

As the image shows, ligatures work only when a string is less or equal than 3 characters.

It **only fails on my main desktop**: My Surface device does not have this problem and works flawlessly with infinite long strings.
- The configuration files on both devices are exactly the same.

However, I tried the same font and ligatures in **vscode and both of them are working correctly**.

--------------------

The font and the windows-terminal itself are downloaded from the same source:
- https://chocolatey.org/packages/firacodenf
- https://chocolatey.org/packages/microsoft-windows-terminal/

---------------------

Any ideas?

**Comment by DHowett** [comment]
Can you check the version of the Fire Code NF font on your desktop and laptop? I believe "infinite arrows" were added in a recent update, and Windows is occasionally bad about handling font updates.

**Comment by lygamac** [comment]
Thanks for the tip.

I got two version of Fira Code NF installed on my desktop (2.0 and 5.0). After deleting the 2.0, ligatures are working correctly.

It seems that while other applications uses the newest version found and Windows Terminal uses the first one it finds.
