### ISSUE TITLE
Aclylic change to solid background after entering a space when using Cascadia Code PL font with PowerShell Core

### ISSUE THREAD

**Issue by TheBlueSky** [microsoft/terminal#7548]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.2.2381.0
```

# Steps to reproduce

1. Set `fontFace` to `Cascadia Code PL` for PowerShell Core (`"source": "Windows.Terminal.PowershellCore"`).
1. Set `useAcrylic` to `true`.
1. Set `acrylicOpacity` to any number.
1. Launch Windows Terminal and open PowerShell Core (if it is not your default profile).
1. Type anything with space; e.g., `cd /`

# Expected behaviour

All the entered text has the same background, the one with Acrylic effect.

# Actual behaviour

All the text from the space onwards has a solid background.

![wt](https://user-images.githubusercontent.com/807685/92321587-72e39980-f02b-11ea-995b-0370b793c9d0.png)

**Comment by j4james** [comment]
This is a PowerShell bug (see issue #6767). I believe it should be fixed if you upgrade PSReadLine. You can get the latest version by following the instructions here: https://github.com/PowerShell/PSReadLine#upgrading

**Comment by TheBlueSky** [comment]
Thanks, @j4james.
I updated PSReadLine from v2.0.2 to v2.0.4, and I do not have the issue anymore.
