### ISSUE TITLE
Taskbar Jumplist entries open in `wt.exe` instead of the application the jumplist belongs to (e.g., `wtd.exe`)

### ISSUE THREAD

**Issue by Sidneys1** [microsoft/terminal#7554]
# Environment

```none
Windows build number: 10.0.20206.0
Windows Terminal version (if applicable): dev build at master 9279b7a7
```

# Steps to reproduce

1. Right-click on "Windows Terminal Dev" from the start menu or taskbar
2. Click a jumplist item

# Expected behavior

The jumplist item opens the selected profile in "Windows Terminal Dev" (`wtd.exe`), since it was the application I right-clicked.

# Actual behavior

The jumplist item attempts to open the selected profile in "Windows Terminal" from the Microsoft Store (`wt.exe`).

![cG5lE2KJpC](https://user-images.githubusercontent.com/1771233/92391976-9241fb80-f0eb-11ea-9df8-2ad2466b7e00.gif)

Additionally, common profiles (like "Command Prompt" or "Windows PowerShell") open as expected in "Windows Terminal" `wt.exe`, but obviously profiles that are configured for "Windows Terminal Dev" (`wtd.exe`) don't exist in "Windows Terminal" (`wt.exe`) and open the default profile instead.

**Comment by DHowett** [comment]
You know, this is probably actually the result of running Windows Terminal outside of its package. Can you check the Version of the spawned instance? I bet it’s 0.0.0.1 or something equivalent to _dev_...

**Comment by Sidneys1** [comment]
> Can you check the Version of the spawned instance?

`0.0.1.0`:

![image](https://user-images.githubusercontent.com/1771233/92396100-71c96f80-f0f2-11ea-802b-adb3641d77cd.png)

Should I be using a different workflow to build/install a Dev instance? Currently just "Build" and "Deploy" options on CascadiaPackage in Visual Studio.

**Comment by DHowett** [comment]
No, no, this is just one of the unusual things we’ve learned about the app model. Since WT was layout-deployed (the way VS installs applications), the jumplist invocation is pointing at the actual binary on disk. Because WT supports unpackaged activation (activating by just double-clicking the EXE) file, it’s possible to run it “outside of the package”.

This is fixable, just surprising!

**Comment by DHowett** [comment]
We’ll need to make the jump list entries optionally point at `%LOCALAPPDATA%\Microsoft\WindowsApps\CurrentTerminalPFN\wt.exe` instead of `C:\Program Files\WindowsApps\PFN\WindowsTerminal.exe`

**Comment by Sidneys1** [comment]
And here I was all excited about the jump-lists! Guess I'll have to wait a bit longer. :) Thanks for the quick responses!

**Comment by Sidneys1** [comment]
Once the fix comes I won't be able to use it until #7553 is fixed as well, that was my other report of the morning...

**Comment by DHowett** [comment]
I mean, _using the dev version as your daily driver is not recommended_... but i’m definitely not here to stop you! 😁

**Comment by Sidneys1** [comment]
I also have Stable and Pre installed from the store, but I do like having my mitts on new bits, like the taskbar jumplists :)

**Comment by DHowett** [comment]
I also reverted the MUX update, so you should be good to go ;)

**Comment by Sidneys1** [comment]
Awesome, thank you sir.
