### ISSUE TITLE
Ability to clear the Terminal

### ISSUE THREAD

**Issue by kube** [microsoft/terminal#7555]
# Description of the new feature/enhancement

VSCode Terminal or iTerm allow you to entirely clear the buffer of a tab.

For example, in VSCode, it's possible to create a keybinding to clear the terminal this way:

```json
{
  "key": "ctrl+k",
  "command": "workbench.action.terminal.clear"
}
```

This is still not possible in Terminal.

**Comment by j4james** [comment]
I think this is probably a duplicate of issue #1882.

**Comment by kube** [comment]
> I think this is probably a duplicate of issue #1882.

@j4james Indeed. Thanks!
