### ISSUE TITLE
Ctrl+Alt+[arrow keys] are not working after update 1.2.2381.0

### ISSUE THREAD

**Issue by atifraza** [microsoft/terminal#7556]
# Environment

```none
Windows build number: 19041.450
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
WSL: 2
Distro: Ubuntu 20.04
```

# Steps to reproduce
Keyboard layout: US (QWERTY) or US-International (QWERTY)

Terminal key bindings: default

"altGrAliasing": false

# Expected behavior
Tmux in WSL has pane switching keybindings set to Ctrl+Alt+[arrow keys].
Before the update to 1.2.2381.0, the keybindings were working and switching panes in a window was possible with these keybindings.
Pressing `Ctrl+Alt+[arrow keys]` should be passed to the WSL instance so that tmux keybindings are triggered.

# Actual behavior
After the update, the keybindings don't work anymore.
The `"altGrAliasing": false` setting has also been tested, and the checks as per pull request [7400](https://github.com/microsoft/terminal/pull/7400) show the correct/expected characters.

Example:
```bash
$  showkey -a

Press any keys - Ctrl-D will terminate this program
# Pressed AltGr+Q
ä       195 0303 0xc3
        164 0244 0xa4
# Pressed Ctrl+Alt+Q
^[^Q     27 0033 0x1b
         17 0021 0x11
# Pressed AltGr+Q
ß       195 0303 0xc3
        159 0237 0x9f
# Pressed Ctrl+Alt+S
^[^S     27 0033 0x1b
         19 0023 0x13
```

**Comment by atifraza** [comment]
Something seems to have fixed the issue.

**Comment by DHowett** [comment]
I hate bugs like that! Thanks for letting us know.

I'll reopen this if you comment and let me know that it's come back :smile:

**Comment by dihmandrake** [comment]
I am seem to have the same issue. None of the shortcuts assigned to "ctrl+alt+XY" seem to work anymore. I am quite sure it used to work last week and it therefore might an issue with Windows, but I cannot guarantee that.

Terminal Version: Version: 1.2.2381.0
Windows Version: 10.0.19041.508

See the last few lines for examples.
Settings:
`// This file was initially generated by Windows Terminal 0.11.1121.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,
    
    "alwaysShowTabs": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "acrylicOpacity" : 0.9,
            "useAcrylic" : true,
            "background" : "#000000",
            "hidden": false
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe"
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure",
                "hidden": true
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybinding":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "ctrl+alt+d" },

        // These shortcuts do not work anymore
        { "command": { "action": "splitPane", "split": "vertical", "splitMode": "duplicate" }, "keys": "ctrl+alt+right" },
        { "command": { "action": "splitPane", "split": "horizontal", "splitMode": "duplicate" }, "keys": "ctrl+alt+down" },
        { "command": "closePane", "keys": ["ctrl+alt+w"] }
    ]
}
`

**Comment by dihmandrake** [comment]
For anyone that might stumble upon this issue: I finally figured out what caused the problem on my machine. Intel Graphics Command Center. Even though Hotkeys are disabled they sometimes block the keyboard combinations with `crtl+alt` in applications. Enabling and disabling the combinations in the Intel Graphics Command Center solves the issue for me. Still, it appears that the Intel implementation contains some bugs and they block combinations after a while (might be reboot releated).

![image](https://user-images.githubusercontent.com/16025288/94138568-9babc180-fe68-11ea-8627-959d8d3601a8.png)

**Comment by Edstar3000** [comment]
what about shift+ arrow keys? output is a d in wsl2 
very frustrating to needing the mouse in this context

**Comment by zadjii-msft** [comment]
@Edstar3000 first off, this thread is like two years old and totally unrelated to shift+arrows selection. You're probably interested in ["Mark mode"](https://docs.microsoft.com/en-us/windows/terminal/selection#keyboard-support), which I believe shipped in 1.15 builds.

**Comment by Edstar3000** [comment]
Damn this was fast.
Thanks a lot!
However, I still cannot mark words by using shift + arrow keys as it is
easily done with Linux.
On the thread stated above I could not find a solution either, am I stupid?

Mit freundlichen Grüßen

Edgar Kretschmann

**Comment by zadjii-msft** [comment]
@Edstar3000 Try binding

```json
        {
            "command": "markMode",
            "keys": "shift+left"
        },
```

in the settings.

![dfb022fb-4dfc-4fbd-b7e4-22ba739604b2](https://user-images.githubusercontent.com/18356694/187252911-4241e257-9403-4394-91d4-dac814bd0fd3.gif)
