### ISSUE TITLE
Cannot start windows terminal after creating  AppData/Local as a directory junction

### ISSUE THREAD

**Issue by sameerkattel** [microsoft/terminal#7558]
1. Windows Terminal was working fine 
2. my c drive as running out of space because of appdata huge size
3. Created a mklink /J "C:\Users\sameer\AppData\Local"  "D:\sameer\AddData\Local"
4. Tried to run windows terminal but now it's not working
5. Uninstalled and reinstalled windows terminal 
6. Still not working
![image](https://user-images.githubusercontent.com/6128234/92432739-cdf7c680-f1ba-11ea-90d0-e3765e0b8546.png)

**Comment by DHowett** [comment]
I do not believe this is a supported configuration for any of the Windows-owned user data directories. If you need to use Terminal in a non-standard or non-supported Windows configuration, you will need to extract the `msixbundle` (it’s just a ZIP file) and manage the installation yourself.
