### ISSUE TITLE
Anaconda with PowerShell

### ISSUE THREAD

**Issue by peter197321** [microsoft/terminal#7559]
Is it possible to document/explain adding a profile for Anaconda running within PowerShell while assuming it's installed Anaconda

**Comment by WSLUser** [comment]
Just add it to the `commandline` parameter in `settings.json` for Powershell.

**Comment by peter197321** [comment]
what to add?

**Comment by WSLUser** [comment]
https://github.com/microsoft/terminal/issues/5852#issuecomment-627189853
Calling this 
/dupe https://github.com/microsoft/terminal/issues/5852

**Comment by peter197321** [comment]
PS C:\> cd ms-appx:///ProfileIcons/
cd : Cannot find drive. A drive with the name 'ms-appx' does not exist.
At line:1 char:1
+ cd ms-appx:///ProfileIcons/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ms-appx:String)
[Set-Location], DriveNotFoundException
    + FullyQualifiedErrorId :
DriveNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\>

**Comment by peter197321** [comment]
& : The term 'C:\Miniconda3\shell\condabin\conda-hook.ps1' is not
recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the
path is correct and try again.
At line:1 char:3
+ & 'C:\Miniconda3\shell\condabin\conda-hook.ps1' ; cond ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound:
(C:\Users\conda-hook.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

conda : The term 'conda' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:66
+ ... rs\nxa18908\Miniconda3\shell\condabin\conda-hook.ps1' ; conda activat
...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [],
CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\System32>

**Comment by peter197321** [comment]
It's not working on my side :( even issue closed. Thank you for your not useable advice!
