### ISSUE TITLE
Installing Microsoft Windows Terminal on Windows Server 2019 editions

### ISSUE THREAD

**Issue by Jayonics** [microsoft/terminal#7560]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

# Environment

Windows Version: Windows Server 2019 - Standard

Windows build number: Win32NT 10.0.17763.0 Microsoft Windows NT 10.0.17763.0
Windows Terminal version: None successfully installed, attempted installation on version 1.2.2381.0 

Any other software? 
Chocolatey (As an attempted alternate means of installation besides PowerShell 'Add-AppxPackage' )

# Steps to reproduce

1. Use any non-core editions of Windows Server (Any year). My use case is Windows Server 2019 Standard.

2. Attempt installation of Microsoft Windows Terminal by either (2a) Add-AppxPackage from release on GitHub OR (2b) via chocolatey package manager.

2a. 

![image](https://user-images.githubusercontent.com/45290659/92467974-529e1100-f1ca-11ea-9146-312b4e94b571.png)

2b.

![image](https://user-images.githubusercontent.com/45290659/92468026-69dcfe80-f1ca-11ea-91b7-344278126654.png)

# Expected behavior

Microsoft Windows Terminal Installs successfully and can be run the same way it is run on Windows 10 editions that do not install it via the Microsoft Store.

# Actual behavior

Errors in the installation of Microsoft Windows Terminal due to incompatible OS builds of Windows Server editions (Non-core) that are behind the OS builds of Windows 10.

For method (2a - Powershell AppxPackage install):
![image](https://user-images.githubusercontent.com/45290659/92467247-2afa7900-f1c9-11ea-93a7-82410d9a2e4e.png)

For method (2b - chocolatey package manager install):
![image](https://user-images.githubusercontent.com/45290659/92467331-52e9dc80-f1c9-11ea-87d8-7982c70bff48.png)

NOTES: It seems unlikely that this can be resolved via installing the current Windows Terminal version in any way on Non-core versions of Windows Server. Perhaps a less eloquent solution to this problem would be installing the last compatible Microsoft Windows Terminal release with a supported OS version of 10.0.17763.1432 (My Windows Server 2019 Standard current OS version)  or lower. If anyone knows what release of Microsoft Windows Terminal last supported that version it could, at least be a temporary fix for installation of this program.

Sorry if this is a comment, but it appears as if the thread content has disappeared so I am reposting it here.

**Comment by WSLUser** [comment]
@nunix can provide some useful info here.

**Comment by j4james** [comment]
I'm fairly sure Windows Server 2019 isn't supported (see issues #2177, #6717, and #6956). Also see issue #1643 for more info on what would be required to get the Windows Terminal running on older versions of Windows.

**Comment by WSLUser** [comment]
Yes but nunix found a way to get it working. Hence why I tagged him.

**Comment by DHowett** [comment]
Terminal has never run on a version of Windows below 18362. Sorry!

/dup #2177 #6717 #1643

**Comment by AndrewSav** [comment]
@DHowett is the terminal going to work on  [Windows Server 2022](https://cloudblogs.microsoft.com/windowsserver/2021/03/02/announcing-windows-server-2022-now-in-preview/)?

**Comment by DHowett** [comment]
If it has the desktop experience package, yes.

**Comment by gahan9** [comment]
Any minimalistic implementation of windows terminal can be provided for Server 2019? since I find most helpful feature is using tabs for different terminal [powershell, command prompt, git bash etc] and also allows connection to quick connect to ssh system. 

Don't care much about graphics experience and rendering, but how about having a window capable of at least launching session as per json structure? I just think that performance and experience of windows terminal is better than [ConEmu](https://conemu.github.io/) and certainly want that experience to expand to Server 2019

**Comment by cwanized** [comment]
Any chance to see a Windows Terminal version for Windows Server 2019? We currently update 70 environments to SfB 2019 which only is supported with Windows Server 2019 (thanks MS) - Windows Server 2019 is supported till 2029 and it would be a bummer if we can't use Windows terminal for our next server generation. As others already said, we can live with a subset of the features but a basic version of Windows terminal would be helfpul for the future...

**Comment by zadjii-msft** [comment]
@cwanized Sorry, but probably not. There aren't just optional parts of the Terminal we could disable on server 2019, there's fundamental OS features we rely on that are missing entirely. If server is what you need, then Server 2022 is where you're gonna get the Terminal.

**Comment by Jayonics** [comment]
> @cwanized Sorry, but probably not. There aren't just optional parts of the Terminal we could disable on server 2019, there's fundamental OS features we rely on that are missing entirely. If server is what you need, then Server 2022 is where you're gonna get the Terminal. 

At the time Windows server 2022 was not out but as you said, windows terminal works fine on windows server 2022.
