### ISSUE TITLE
Feature Request: Highlight all finding

### ISSUE THREAD

**Issue by krispetkov** [microsoft/terminal#7561]
# Description of the new feature/enhancement

A good and handy feature  will be the option to highlight all the find when using the ctrl+shift+f 
Something like the GitBash alt+f3 search option:

![2020-09-08_16-01-42](https://user-images.githubusercontent.com/6774998/92480374-7a52a080-f1ed-11ea-8850-f1988c2019c1.png)

This is really helpful when looking for something or doing some comparison

**Comment by WSLUser** [comment]
I actually like how the terminal scrolls to the next selection when searching a term but this can be useful too. Can this be a sub-setting?

**Comment by zadjii-msft** [comment]
Linking this to #3920. Thanks!

**Comment by mjclancyau** [comment]
Please to implement this - it's dreadfully useful 🙏
