### ISSUE TITLE
Pane focus movement does not match alt+direction

### ISSUE THREAD

**Issue by anthonyyoshimura** [microsoft/terminal#7566]
### Steps to reproduce
Create a vertical split. Then on the left pane, create another vertical split, like so
`|_1_|_2_|___3___|`
With the focus on pane 3, moveFocus left

### Expected behavior
The focus should move to 2

### Actual behavior
The focus moves to 1

**Comment by DHowett** [comment]
Thanks! This is a combination of /dup #4692 and #2398, both of which are important and might actually be in conflict. :smile:
