### ISSUE TITLE
In WT version 1.2.2381.0, everytime I enter VIM it starts in replace mode

### ISSUE THREAD

**Issue by djfogbr** [microsoft/terminal#7569]
It seems to me it began happening after upgrade from WT preview. If I use putty for connecting to the same host and username, it doesn't happen.
I tested in RHEL 6.7 and Oracle Linux Server release 7.7.

Any clues?
Thanks in advance.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Does it start in insert mode or _replace mode_?

**Comment by djfogbr** [comment]
I'm using Windows 10 1909.

**Comment by djfogbr** [comment]
> Does it start in insert mode or _replace mode_?

Goop point! In fact, it starts in replace mode. My bad.

**Comment by DHowett** [comment]
Thanks! In that case, this is a /duplicate of #1637.
