### ISSUE TITLE
Settings reload forces cursor to be visible/blinking even when terminal is out of focus

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7571]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1016 (1909)
Windows Terminal Preview
Version: 1.3.2382.0

# Steps to reproduce

From the dropdown, choose "Settings".  Make any change to settings.json and save.

# Expected behavior

None

# Actual behavior
Cursor becomes visible in WT though it has neither foreground nor input focus.

That's actually quite disconcerting ... to be working in an editor while WT (inactive and on another monitor) is blinking at me

**Comment by DHowett** [comment]
Thanks! Tagged.
