### ISSUE TITLE
Build Fails on 1H20 Insider Preview with VS2017 or VS2019

### ISSUE THREAD

**Issue by xpwn3rx** [microsoft/Terminal#758]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18894.1000]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Build will not succeed in VS2017 or VS2019 Preview. I followed @DarqueWarrior tutorial from here: http://www.donovanbrown.com/post/Building-the-new-Windows-Terminal-with-Visual-Studio-2019

![image](https://user-images.githubusercontent.com/19785522/57660289-be527880-759a-11e9-86e9-9dd52ba6a8f4.png)

I have tried building the TerminalSettings project separately before trying to build the solution but that didn't succeed either.

* What's wrong / what should be happening instead:

I expected it to spit out a complete build then be able to deploy the application and install it.

**Comment by DHowett-MSFT** [comment]
This should be covered in #489.

**Comment by xpwn3rx** [comment]
Will test, directions appear similar to Donovans guide.
