### ISSUE TITLE
Add POSIX shell support

### ISSUE THREAD

**Issue by MarcusJohnson91** [microsoft/terminal#7582]
I don't even think this would be difficult to do.

bundle the bash compatible, permissively licensed zsh shell, detect when a script starts with a hashbang and names a shell, have zsh take over.

----

I personally would find this useful because my project FoundationIO uses a shell script to generate Unicode tables that can't be ran on Windows.

not to mention I have to put about half of my cmake script into if Unix/Windows blocks to enable very basic functionality.

----

What's the point of writing a whole new Terminal if you're not going to turn a new leaf?

**Comment by DHowett** [comment]
Well, we would also have to ship an entire compatibility layer that let you run POSIX-compliant things on Windows. Incidentally, we [did this](http://aka.ms/wsl) with WSL, and you can use bash/zsh/etc. to your heart's content.

**Comment by MarcusJohnson91** [comment]
> Well, we would also have to ship an entire compatibility layer that let you run POSIX-compliant things on Windows. Incidentally, we [did this](http://aka.ms/wsl) with WSL, and you can use bash/zsh/etc. to your heart's content.

Yes but wsl in a major PITA.
