### ISSUE TITLE
Add portable (stand alone) build for releases

### ISSUE THREAD

**Issue by yekanchi** [microsoft/terminal#7587]
# add a portable release alongside with `msixbundle`

- This is useful so people can put terminal on their USB stick with their custom profile. 
- Now that `PowerShell Core` (version 7 ) also provide a stand alone version so a portable `terminal` can be used with it.
- Other terminals like `cmder` and `ConEmu` provide such capability which is very useful.

**Comment by skyline75489** [comment]
Somewhat related to #7492

**Comment by DHowett** [comment]
Thanks! this is a /duplicate of #1386
