### ISSUE TITLE
Automatically connect to Exchange from profile

### ISSUE THREAD

**Issue by Kail0** [microsoft/terminal#7592]
# Environment

```none
Windows build number: Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
```

# Steps to reproduce
Create profile that automatically create remote PS session to Exchange (on premise).
```powershell
"name": "Exchange",
"commandline": "powershell.exe ; $UserCredential = Get-Credential ; $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://contoso.com/PowerShell/ -Authentication Kerberos -Credential $UserCredential ; Import-PSSession $Session -DisableNameChecking",
"colorScheme": "One Half Dark"
```

# Expected behavior
After opening tab with Exchange profile and typing credentials you should have active session with Exchange cmdlets.

# Actual behavior
After typing credentials, the session starts to download cmdlets and after it's done it force close the tab with current session.

**Comment by dsolodow** [comment]
Try this for the commandline:

"powershell.exe -noexit -command $UserCredential = Get-Credential ; $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://contoso.com/PowerShell/ -Authentication Kerberos -Credential $UserCredential ; Import-PSSession $Session -DisableNameChecking",

**Comment by BinaryZeph** [comment]
> Try this for the commandline:
> 
> "powershell.exe -noexit -command $UserCredential = Get-Credential ; $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://contoso.com/PowerShell/ -Authentication Kerberos -Credential $UserCredential ; Import-PSSession $Session -DisableNameChecking",

This worked perfectly for me. Thanks!

**Comment by Kail0** [comment]
> Try this for the commandline:
> 
> "powershell.exe -noexit -command $UserCredential = Get-Credential ; $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://contoso.com/PowerShell/ -Authentication Kerberos -Credential $UserCredential ; Import-PSSession $Session -DisableNameChecking",

Indeed, it works perfectly! Thank you so much!
