### ISSUE TITLE
`?.` Characters at the end of the new line when doing `sudo apt update && sudo apt upgrade`  

### ISSUE THREAD

**Issue by asolopovas** [microsoft/terminal#7593]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable):
Windows Terminal
Version: 1.2.2381.0

Any other software?
Fresh Ubuntu WSL Install 
```

![image](https://user-images.githubusercontent.com/6893216/92732419-55396b80-f36e-11ea-9cb5-91d6de30daef.png)

**Comment by DHowett** [comment]
If you copy/paste those characters out of the window, what do you get?

What font (and what version of that font?) are you using?

**Comment by asolopovas** [comment]
If I copy the `?.` and paste it elsewhere I do get `..`, I am using `FuraCode Nerd Font Mono` the version of which is version `1.206`

**Comment by DHowett** [comment]
I cannot find a NerdFont version of Fira that is both 1.206 and still has the name "Fura". At the same time as they upgraded to 1.206, they got an agreement from the Fira Code owner to use the name "Fira."

I would suggest updating to the latest version of the Fira NerdFont--it looks like you might be using a custom version that was authored with a ligature issue.

**Comment by DHowett** [comment]
In fact, this is a known issue filed on the NF repository.

/dup https://github.com/ryanoasis/nerd-fonts/issues/435

**Comment by DHowett** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/337
