### ISSUE TITLE
Tab key triggers twice in shell

### ISSUE THREAD

**Issue by dgliwka** [microsoft/terminal#7598]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19041.508]

Windows Terminal version (if applicable): 1.3.2382.0
```

# Steps to reproduce

1. Start either cmd, PowerShell or wsl (Ubuntu 20.04) profile (with default settings.json).
2. Hit `Tab ↹` button.
3. `Tab ↹` action is executed by shell twice,

# Expected behavior

Shell receives Tab key once, and therefore executes it's action once.

# Actual behavior

Shell (bash on wsl, PowerShell or cmd) executes Tab key twice, resulting with two \t characters in vim, or advancing shell's directory autocompletion by two directories.

# Notes:
1. After mapping another key to `Tab` input code with:
`{ "command": { "action": "sendInput", "input": "\u0009" }, "keys": "f2" }`
F2 key sends `Tab`'s input code only once.
2. It is not a problem with keyboard, as the problem appears only in Windows Terminal.

**Comment by DHowett** [comment]
Interesting. Are you using a physical or virtual keyboard? What layout is it?

**Comment by DHowett** [comment]
(I ask because this doesn't seem to reproduce with US (QWERTY) hardware keyboards for anyone on the team.)

**Comment by dgliwka** [comment]
It's physical keyboard. 
I am using Polish layout, but the problem appears also with English US and UK layout.
Also tried to change system language to English UK, but it did not help.

**Comment by zadjii-msft** [comment]
By any chance, did you try the workaround earlier in #4448, with setting `InputServiceEnabled: 1`?

**Comment by dgliwka** [comment]
`InputServiceEnabled: 1` does not help.

**Comment by DHowett** [comment]
Sorry, I do not understand.

`InputServiceEnabled: 1` is the default, but you need to enable the "Touch Keyboard and Handwriting Panel Service" service. When you have `InputServiceEnabled: 1` and service started, does the keyboard continue working for Terminal?

If so, does the Tab bug still happen?

**Comment by dgliwka** [comment]
Thank you for clarification. It solved the issue.

So for anyone in the future setting
```
HKLM\SOFTWARE\Microsoft\Input:
  InputServiceEnabled: 1
  InputServiceEnabledForCCI: 1
```
and setting service `Touch Keyboard and Handwriting Panel` to `manual` solves the problem.

**Comment by DHowett** [comment]
Thanks.

I will add this to the list of issues caused by disabling random windows services!
