### ISSUE TITLE
 Shell unexpectedly exits or crashes when elevating a new PowerShell instance.

### ISSUE THREAD

**Issue by daniefer** [microsoft/terminal#7599]
# Environment

Windows build number: 
```none
PS >[Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

```
Windows Terminal version (if applicable):

![image](https://user-images.githubusercontent.com/5559147/92771242-54014200-f360-11ea-91c1-196e901367e2.png)

Any other software?
```none
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS > $PSHOME
C:\Windows\System32\WindowsPowerShell\v1.0
```

# Steps to reproduce
1. Run the command ``Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello world`"";``
1. Approve the windows prompt for elevation
1. Repeat steps 1 and 2 between 2-5 times in a row
1. The host tab will close even though the user did not exist the shell.

This was discovered with an auto elevating script such as [this example](https://stackoverflow.com/a/57035712). The script will run 1 or 2 times and then the host Windows Terminal tab will close unexpectedly. I have tried replicating with other shells with no luck. I am not certain this is only a PowerShell issue.

# Expected behavior
The user should be able to run the command ``Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello world`"";`` any number of times and not have Windows Terminal close the tab.

# Actual behavior

Run the command ``Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello world`"";`` between 2-5 times in a row and the host tab will close.

**Comment by DHowett** [comment]
If you set `closeOnExit` to `"never"` for that profile, what do you see when it exits?

**Comment by daniefer** [comment]
```none
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS > Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello`"";
PS > Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello`"";
PS > Start-Process PowerShell -Verb RunAs "-NoProfile -ExecutionPolicy Bypass -Command `"cd '$pwd'; & echo hello`"";
PS >
[process exited with code 0]
```

**Comment by daniefer** [comment]
I was able to reproduce this in PowerShell v7 and v5 terminals. So this might not be a WT problem. I also noticed this morning that this might be related to an overly aggressive antivirus. I will post again/reopen if that proves not to be the case.

**Comment by DHowett** [comment]
Ah! Thanks for following up. :smile:
