### ISSUE TITLE
Add optional margins to Windows console to improve readability.

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/Terminal#76]
_From @PhMajerus on October 22, 2017 21:28_

This is a very simple suggestion, and should be easy to implement while providing great benefits.

Text flush with windows borders are not great for readability (I remember the Microsoft Reader or Typography team ran experiments on this years ago, deciding to include margins to ebooks on Pocket PC screens), and most CUI apps do not spare characters around their display to provide a margin.

So how about adding configurable margins in conhost?
This would be part of the layout options, defining a number of pixels width (left & right) and height (top & bottom). Conhost would then extend the window client area by these margins, using the current console background color but centering the buffer display within it.

This small modification would have no impact unless a user sets margins other than 0, and would greatly improve readability in the console.
For greater customization, you could even allow different margins for main and alternate buffer modes, making the interactive/buffer-log mode different from the one of CUI-apps that control their display precisely.

After all, if the goal is to make Windows the best workstation OS for cross-platform development, we shouldn't settle for just usable, we should aim for comfort and differentiate from the others in that area.

![conhost margins](https://user-images.githubusercontent.com/25664275/31866497-84d1b6cc-b780-11e7-962c-165d02c9bf20.png)

_Copied from original issue: Microsoft/WSL#2589_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on October 23, 2017 16:39_

Already on the backlog :)

**Comment by bitcrazed** [comment]
_From @Oeffner on October 26, 2017 16:15_

Better still would be to reinstate the option of setting window border thickness to something else than 0 pixel width from the control panel. This would have a similar effect as adding a marging within the window. This was possible in Windows 7 and earlier. With the current zero border width it takes a lot of time to correctly position the mouse on the border when attempting to resize a windows. This generally reduces productivity of the desktop.

**Comment by miniksa** [comment]
Windows Terminal has this. Resolving.

**Comment by mdtauk** [comment]
It's a shame there isn't a distinction between drawing modes and text modes, or else you could have included line height settings too

**Comment by zadjii-msft** [comment]
Who's to say we _won't_ ;)

**Comment by philpowers** [comment]
> Windows Terminal has this. Resolving.

Can you clarify? I don't see anything about Margin or Border settings. Please tell me where to find this if it's already implemented.
