### ISSUE TITLE
Microsoft.UI.Xaml causes an exception when any flyout menus are generated

### ISSUE THREAD

**Issue by bkot88** [microsoft/terminal#760]
After modifying Cascadia project to debug in "Native Only" mode, I come across this exception, when clicking dropdown menu (to open a new tab in the terminal):

![image](https://user-images.githubusercontent.com/19501248/57662896-f4443b00-7634-11e9-81bd-c4bd3af09aff.png)

File: src/cascadia/WindowsTerminal/main.cpp
Win Version: 10.0.18362.86
VS19: 16.0.3

I would like to investigate if anyone can point me in the right direction.

**Comment by DHowett-MSFT** [comment]
This seems to only happen when `Microsoft.UI.Xaml` is loaded into the process. I'd like to hold on to it to make sure that it's not some weird prerelease bug we're hitting.

I'll assign it to myself, to do two things:
1. Make sure we always have symbols for MUX.dll
2. Drive the discussion with them on why this might be happening.

**Comment by drekryan** [comment]
I hit an abort() similar to this in debug with outdated profiles.json after the starting directory changes were made and rendered my previous settings invalid crashing the app or causing an abort(). Dont know if this is related but thought it might give some direction into investigating it.

I deleted my profiles.json file from %LOCALAPPDATA%\packages\Microsoft.WindowsDevTerminal_8wekyb3d8bbwe\RoamingState and allowed it to be regenerated and my build stopped hitting the abort() without a rebuild needed.

**Comment by fghzxm** [comment]
The interesting part is that I only get this exception thrown when I'm _debugging_ Terminal, not when running it from Start.
