### ISSUE TITLE
Some users report ssh.exe exiting with long pasted content

### ISSUE THREAD

**Issue by PPointCharles** [microsoft/terminal#7601]
The connection crashes when making a multi-line copy on a remote host.

**Comment by DHowett** [comment]
Can you give us _any_ more information than that? Literally anything? Version numbers, what application, what it looks like when it crashes, etc.?

**Comment by PPointCharles** [comment]
my WindowsTerminal version is **v1.3.2382.0**, remote host is a kali linux, When I type in a very long string like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'，it would crash. For example, when i excute command `echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`,it would exit the ssh connect,error info: **echo aaaaaapacket_write_poll: Connection to xx.xx.xx.xxx port 22: eother  [Exited process, code 255] ** .There is no such bug if it is not a preview release,

**Comment by DHowett** [comment]
@Z-LL reported the same issue in #7651 without the preview release. I tried, but I cannot make this happen!

**Comment by DHowett** [comment]
What verison of the ssh server are you using on Kali Linux (@PPointCharles) and your remote host (@Z-LL)? Please run `ssh -V` on the server.

**Comment by Z-LL** [comment]
> 
> 
> What version of the ssh server are you using on Kali Linux (@PPointCharles) and your remote host (@Z-LL)? Please run `ssh -V` on the server.

```
ssh -V

OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
```

**Comment by PPointCharles** [comment]
**My Kali Linux version**: OpenSSH_8.1p1 Debian-1, OpenSSL 1.1.1d  10 Sep 2019
**Windows Terminal version**: 1.3.2382.0
**Windows ssh.exe version**: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5 
PS:  As long as it's a copy operation, it crashes, single-line replication also triggers this problem.

**Comment by DHowett** [comment]
Can you try `ssh -d -d -d` instead of just `ssh`? It will enable debug logging.

I cannot reproduce this issue, even with my system locale set to zh-CN.

What keyboard layout are both of you using?

**Comment by DHowett** [comment]
(Sorry - I meant to say `-v -v -v`. I updated the comment.)

**Comment by Z-LL** [comment]
# 1 enter directly: "commandline": "ssh -v user1@ip"
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\user/.ssh/config
debug1: C:\\Users\\user/.ssh/config line 1: Applying options for ip
debug1: Connecting to ip [ip] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\user/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to ip:22 as 'user1'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:zlHmnr6lkVxh6s6B2kZO/1qNsaaW4hJ3r3nPtfSefhE
debug1: Host 'ip' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\user/.ssh/known_hosts:2
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:V1bsjGlaK+VtByYnbnDLldurkjaTEVnn6uetr6YePAc C:\\Users\\user/.ssh/id_rsa
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug1: Authentication succeeded (publickey).
Authenticated to ip ([ip]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: console supports the ansi parsing
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-106-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

363 packages can be updated.
36 updates are security updates.

*** System restart required ***
Last login: Tue Sep 22 12:22:59 2020 from ip
user1@user1-X9DRL-3F-iF:~$

**Same paste problem**

# 2 Indirect entry: "commandline": "cmd.exe", then command “ssh -v user1@ip”
$ ssh -v user1@ip
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
debug1: Reading configuration data /c/Users/user/.ssh/config
debug1: /c/Users/user/.ssh/config line 1: Applying options for ip
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ip [ip] port 22.
debug1: Connection established.
debug1: identity file /c/Users/user/.ssh/id_rsa type 0
debug1: identity file /c/Users/user/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_dsa type -1
debug1: identity file /c/Users/user/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/user/.ssh/id_xmss type -1
debug1: identity file /c/Users/user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to ip:22 as 'user1'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:zlHmnr6lkVxh6s6B2kZO/1qNsaaW4hJ3r3nPtfSefhE
debug1: Host 'ip' is known and matches the ECDSA host key.
debug1: Found key in /c/Users/user/.ssh/known_hosts:2
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /c/Users/user/.ssh/id_rsa RSA SHA256:V1bsjGlaK+VtByYnbnDLldurkjaTEVnn6uetr6YePAc
debug1: Will attempt key: /c/Users/user/.ssh/id_dsa
debug1: Will attempt key: /c/Users/user/.ssh/id_ecdsa
debug1: Will attempt key: /c/Users/user/.ssh/id_ecdsa_sk
debug1: Will attempt key: /c/Users/user/.ssh/id_ed25519
debug1: Will attempt key: /c/Users/user/.ssh/id_ed25519_sk
debug1: Will attempt key: /c/Users/user/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /c/Users/user/.ssh/id_rsa RSA SHA256:V1bsjGlaK+VtByYnbnDLldurkjaTEVnn6uetr6YePAc
debug1: Server accepts key: /c/Users/user/.ssh/id_rsa RSA SHA256:V1bsjGlaK+VtByYnbnDLldurkjaTEVnn6uetr6YePAc
debug1: Authentication succeeded (publickey).
Authenticated to ip ([ip]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-106-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

363 packages can be updated.
36 updates are security updates.

*** System restart required ***
Last login: Tue Sep 22 09:58:15 2020 from 192.168.40.18
user1@user1-X9DRL-3F-iF:~$

**No paste problem**

# 3 Keyboard layout
Only Microsoft Pinyin

**Comment by DHowett** [comment]
In `v` mode, are there any extra messages before the crash?

**Comment by Z-LL** [comment]
> In `v` mode, are there any extra messages before the crash?

I commented "closeOnExit": "always", ans get the following result: 

```
sindebug3: send - ERROR: Unexpected IO state, io:00000216D927FB10
packet_write_poll: Connection to IP port 22: eother
debug3: Successfully set console output code page from 65001 to 936
debug3: Successfully set console input code page from 65001 to 936
```

**Comment by PPointCharles** [comment]
I also did the same test with CMD.exe and found that the copy operation will still quit,so maybe this is a bug in ssh.exe or the system settings, not windows terminal.

**Comment by DHowett** [comment]
Wow! Thank you for testing that.

Based on that message, it looks like the code in ssh that handles "partial send" (when you give it too much input at one time, it has to send part of it now and part of it later) on Windows is broken.


This would be a good bug to file on [the win32-openssh GitHub](https://github.com/PowerShell/Win32-OpenSSH).

Thank you again.

**Comment by Z-LL** [comment]
I find a solution!
The openssh version of windows is 7.x. I uninstalled the openssh that comes with win10 and switched to git ssh. There is no such problem!

The current version of openssh on win10:
OpenSSH_8.3p1, OpenSSL 1.1.1g 21 Apr 2020

**Comment by gitsang** [comment]
Hve not resolved yet

```
debug1: console supports the ansi parsidebug3: send - ERROR: Unexpected IO state, io:000001BEC2E72270
packet_write_poll: Connection to 10.200.112.67 port 22: eother
debug3: Successfully set console output code page from 65001 to 936
debug3: Successfully set console input code page from 65001 to 936

[已退出进程，代码为 255]
```

**Comment by gitsang** [comment]
![image](https://user-images.githubusercontent.com/49085035/140679092-96be4bf5-1127-43db-91c9-ffa8cd34d906.png)

solved by using git's ssh
