### ISSUE TITLE
Nothing Appears When Typing in Terminal or Terminal Preview

### ISSUE THREAD

**Issue by mourneris** [microsoft/terminal#7604]
# Environment

```
Windows build number: 10.0.19041.508
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

1. Installed Windows Terminal (and/or Windows Terminal Preview)
2. Boot up once and type some commands, open a few tabs
3. Edit the settings.json to remove Azure from the display options
4. Return to the Terminal and close it
5. Open the Terminal again and try to type

# Expected behavior

When typing, letters should appear in the terminal corresponding to the keys pressed on the keyboard.

# Actual behavior

When typing, no letters appear at all in the terminal.

**Comment by zadjii-msft** [comment]
By any chance, did you disable the "Touch Keyboard and Handwriting Panel Service"? See also #4448

**Comment by mourneris** [comment]
Yes, the service is disabled as it directly conflicts with the operation of the "Halo: Master Chief Collection" game. If the service is on, it interferes with the menu system in-game causing the game to run incredibly sluggish due to conflicting inputs.

**Comment by DHowett** [comment]
Unfortunately, that service is required for Terminal to operate. Do you have documentation (like a feedback hub item?) about the conflict? I'd love to start the discussion with the input team about how this is a problem for Halo.

/dup #4448.
