### ISSUE TITLE
Extra whitespace when running jest tests in a PowerShell window. 

### ISSUE THREAD

**Issue by Butters646** [microsoft/terminal#7605]
I don't know if this is specific to jest, that is just how I observed this behavior. I get large "chunks" of whitespace in my terminal session when I run my tests. This doesn't happen when I use PowerShell directly or when I use the command prompt in Windows Terminal, so it looks like it is an issue with the PowerShell window in Window Terminal. 

I have attached screenshots of the issue. This is just one example of the extra space. Huge chunks of blank lines appear throughout the run in the PowerShell window. 

![cmd prompt Window in Windows Terminal](https://user-images.githubusercontent.com/35573003/92928991-da279200-f40d-11ea-8a2c-6adba62a4459.png)
![PowerShell stand alone Window](https://user-images.githubusercontent.com/35573003/92928993-da279200-f40d-11ea-98b6-9d84e264878b.png)
![PowerShell Window in Windows Terminal](https://user-images.githubusercontent.com/35573003/92928995-dac02880-f40d-11ea-997b-0596bda7b267.png)

**Comment by DHowett** [comment]
This is very unexpected. When you run it in a normal powershell window, does the _size_ of the window change?

**Comment by Butters646** [comment]
@DHowett It doesn't appear to. I see no observable window size changes.

**Comment by zadjii-msft** [comment]
@Butters646 could you share your powershell profile? I've got a theory that some customization in there is what's tripping the Terminal up

**Comment by Butters646** [comment]
[Microsoft.PowerShell_profile.zip](https://github.com/microsoft/terminal/files/5298878/Microsoft.PowerShell_profile.zip)

Sure. Attached.

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/94752579-7c1d0900-0340-11eb-9fca-a155631127f8.png)


that'll do it!

/dup #5094

alternatively, don't force the screen or buffer size in the file that powershell runs for every new session (including when it's spawned by other poorly-behaved tools sometimes!)
