### ISSUE TITLE
Set the social media image for the project ...

### ISSUE THREAD

**Issue by Jaykul** [microsoft/Terminal#761]
There are two things that go together so beautifully:

1. The Social Preview setting in github projects
2. The glass in the terminal video y'all posted to YouTube

Can someone set the image?

E.g. 
![image](https://user-images.githubusercontent.com/192942/57671803-4d837e80-75e3-11e9-94ee-c07c381e8a02.png)

I just took a capture from YouTube ... Shhh! Don't tell Microsoft! 😉

![console](https://user-images.githubusercontent.com/192942/57671825-62601200-75e3-11e9-8711-4b3badf0ce40.png)

**Comment by zadjii-msft** [comment]
@bitcrazed / @cinnamon-msft sounds like a PM task to me :)

**Comment by cinnamon-msft** [comment]
I got this!
