### ISSUE TITLE
Unable to re-order tabs

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7610]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 10.0.18363.0
Windows Terminal version (if applicable): 1.3 Preview (but is on 1.2 as well)

Any other software? None
```

# Steps to reproduce

Open Windows Terminal. Create a few tabs. Doesn't matter what profile. Try dragging them to change the order. They don't change.
# Expected behavior

I expect the tabs to get re-ordered
# Actual behavior

Doesn't react to the mouse click and makes it undraggable.

I can still use the "Rename Tab" and "Color" options if I right-click on them. So this is specific to the placement of tabs.

I also looked and while there are issues concerning the re-ordering of tabs, none of them are about the fact this feature died a silent death.

**Comment by DHowett** [comment]
And you're not running as admin?

**Comment by WSLUser** [comment]
I verified I can do it if I was running unelevated. If I run Windows Terminal as Admin, then the tab re-order doesn't work.

**Comment by zadjii-msft** [comment]
Yep, this is by design. See /dup #3581, #6893
