### ISSUE TITLE
Terminal Crashing when trying to open new tab

### ISSUE THREAD

**Issue by Michael974479** [microsoft/terminal#7614]
# Environment

```None
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]: Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): Latest from Microsoft Store

Any other software?
```None

# Steps to reproduce

<!-- A description of how to trigger this bug. -->
1. Launch Windows Terminal
2. Try to open new tab

# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
It should open new tab normally

# Actual behavior

<!-- What's actually happening? -->
It's trying to open new tab, but then it crashes

**Comment by zadjii-msft** [comment]
Could you provide the actual version number? "latest from the store" doesn't tell me if you're on stable or preview builds 😉

Also: /feedback

**Comment by Michael974479** [comment]
I don't know number, but it's latest stable, I forgot that there is Preview
too

sob., 12 wrz 2020, 09:10 użytkownik Mike Griese <notifications@github.com>
napisał:

**Comment by Renalrazi** [comment]
IF you have Rivatuner Statistics Server on your machine, you need to add WT.exe and WindowsTerminal.exe to the application and set the "application detection" to "None" to fix the crashes. 
 
https://forums.guru3d.com/threads/rtss-causes-windows-terminal-to-crash.433951/

**Comment by zadjii-msft** [comment]
You can find the version number in the About Dialog:
![image](https://user-images.githubusercontent.com/18356694/92996523-effe8b00-f4d1-11ea-9bf3-7a3a9b107de7.png)
![image](https://user-images.githubusercontent.com/18356694/92996532-f856c600-f4d1-11ea-9e00-1a4e2a4ec09d.png)

**Comment by Michael974479** [comment]
Oh, thanks, that would be probably that, because I use RivaTuner, thanks

sob., 12 wrz 2020, 15:13 użytkownik Renalrazi <notifications@github.com>
napisał:

**Comment by zadjii-msft** [comment]
Thanks for following up! 

/dup #5697 #5793 #6746
