### ISSUE TITLE
Mouse input not being sent to applications (eg vim)

### ISSUE THREAD

**Issue by montooner** [microsoft/terminal#7616]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.2.2381.0

Any other software? No
```

# Steps to reproduce

- Launch "vim" in Powershell
- Enter `:set mouse=a`
- Try clicking with mouse, cursor does not respond
- (Repeat with other shells in wt: Close Powershell, repeat with vim on cmd, vim on git-bash)
- (Repeat with Git Bash outside wt: open Git Bash, and observe that `set mouse=a` DOES allow mouse interaction with vim)

# Expected behavior

The blog article about v0.10 (https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-10-release/) says that mouse support was added, but I'm able to exercise that functionality. I expect to be able to move the text cursor in vim, but I'm unable to.

# Actual behavior

When I click the mouse in vim, the mouse clicks are not transmitted.

Thanks for your help!

**Comment by zadjii-msft** [comment]
Mouse support was added for WSL applications, but unfortunately there's still a bit of work to do to enable mouse input for Win32 applications (like vim.exe)

For more info, I'd check out: /dup #376 
Thanks!
