### ISSUE TITLE
[feature-request] right clicking icon in taskbar has links to start different terminal types

### ISSUE THREAD

**Issue by daves-dabblins** [microsoft/terminal#7617]
# Description of the new feature/enhancement

Windows Terminal is a great way to interact with different shells, however, many people will have common shells they use for tasks and currently it is 3 clicks to:
* open terminal
* click the down arrow
* click the shell of choice

If right clicking on terminal in taskbar offered the shell options (or 5 most recently used) then a user could jump straight to their shell of choice.

# Proposed technical implementation details (optional)

Add a right click context menu for Terminal on the taskbar to include the last 5 shells used by the user, where selecting one of those opens Terminal straight into that shell

**Comment by skyline75489** [comment]
I think this was closed by #7515

**Comment by DHowett** [comment]
Yep! /dup #576
