### ISSUE TITLE
Feature Request: Define profile to start new tab with multiple panes

### ISSUE THREAD

**Issue by fr43nk** [microsoft/terminal#7620]
**Description:**
Ability to create a profile that opens a new tab in the current window.
This tab is defined to open multiple panes.

**Situation until now:**
It is only possible to open such a tab along with a new Window by using the `wt` command.

**Comment by j4james** [comment]
Is this not the same request as issue #3759?

**Comment by DHowett** [comment]
It definitely is. Thanks @j4james! /dup #3759
