### ISSUE TITLE
Store Settings.json in Documents

### ISSUE THREAD

**Issue by dreigo42** [microsoft/terminal#7621]
It would be awesome if the Settings.json file for Terminal was stored in the Documents folder somewhere. 

Perhaps check for a specific folder in the Documents folder before defaulting to the current location when Terminal is launched? Similar to how PowerShell checks for scripts and Modules in the Documents\WindowsPowershell folder?

**Comment by j4james** [comment]
I'm not exactly sure whether this would meet your needs, but you could always create a symbolic link from your documents folder to the location that Windows Terminal uses.

For example, something like this:

```
mklink /D %USERPROFILE%\Documents\WindowsTerminal %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState
```

**Comment by DHowett** [comment]
Yep -- symlinking is what we're recommending for now. For updates on our plan, though, follow /dup #2933
