### ISSUE TITLE
Settings option to make mouse operations behave like Xterm (middle button pastes)

### ISSUE THREAD

**Issue by wnpaul** [microsoft/terminal#7624]
# Description of the new feature/enhancement

It would be useful if Windows Terminal had an option to make it behave like Xterm, i,e. middle mouse button pastes. The way it currently behaves, every time I switch from an X environment to Win10 I keep pressing the wrong button.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This is likely covered by issue #1553.

**Comment by DHowett** [comment]
It indeed is. Thanks @j4james! /dup #1553.
