### ISSUE TITLE
Why is my Windows Terminal in Russian?(solved)

### ISSUE THREAD

**Issue by virag3** [microsoft/terminal#7631]

**Comment by j4james** [comment]
Check what your "Preferred languages" are set to in the Windows Language Settings. What sometimes happens is you might have some version of English (that isn't US English) as your preferred language, but your second or third preference is Russian for some reason. And while Window Terminal has a US English translation, it probably doesn't have a translation for the particular version of English you're using. As a result, it ends up looking further down the list to find a match, and ends up with Russian. If that's the case, either remove Russian from the list, or make sure that you've got US English included in that list at a higher position.

**Comment by j4james** [comment]
See also issue #6943 for an example of someone with a similar problem.

**Comment by DHowett** [comment]
Since you marked this bug solved, I will close it. Thanks!

**Comment by VectorBCO** [comment]
this issue still exists
