### ISSUE TITLE
Close Tabs to the Right

### ISSUE THREAD

**Issue by sfxworks** [microsoft/terminal#7633]
# Description of the new feature/enhancement
Similar to chrome/edge, would be cool to have a "Close tabs to the right" feature. I find myself opening a lot of tabs. 

![image](https://user-images.githubusercontent.com/5921035/93191850-00ea0f00-f713-11ea-8781-b0c4c48851ad.png)

**Comment by skyline75489** [comment]
Let's see if the bot likes me now /dup #5524

**Comment by DHowett** [comment]
Alas! It doesn't yet. Sorry!

/dup #5524.
