### ISSUE TITLE
Zsh produces escape sequences as they were actual strings.

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#7635]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]  10.0.19041.508]
Windows Terminal version (if applicable):  1.2.2381.0

Any other software?
```

# Steps to reproduce

I'm using Ubuntu(WSL 2.0) and try to use `zsh` through `bash`.

# Expected behavior

It works.

# Actual behavior

![image](https://user-images.githubusercontent.com/4710575/93212929-d55c3880-f795-11ea-97c4-21cc9d67df1b.png)

I think there is another similar issue like this but I can not find it..

**Comment by jdebp** [comment]
If you are thinking of issues #7091 and #6634 note that the output processing differs and that they aren't running on WSL.

**Comment by jdebp** [comment]
If you are thinking of issues #7091 and #6634 note that the output processing differs and that they aren't running on WSL.

**Comment by jdebp** [comment]
If you are thinking of issues #7091 and #6634 note that the output processing differs and that they aren't running on WSL.

**Comment by DHowett** [comment]
This doesn't look like the stock zsh configuration. Can you share your zshrc?

**Comment by skyline75489** [comment]
Yes I'm using a custom zshrc and the PROMPT is here https://github.com/skyline75489/mydotfiles/blob/master/.zshrc#L41

This also happens with conhost. What interests me is that, in the OpenSUSE WSL distro which I mainly use, the issue does not exist. Be it zsh on bash, bash on bash, you name it. It all works. But in the Ubuntu WSL2 distro it collapses for some reason.

When I'm finished with the OSC things I'll see if I can find out why.

**Comment by skyline75489** [comment]
Now that I think about it, it may be just my zshrc is broken since it contains invisible characters. Maybe just a false alarm.

**Comment by skyline75489** [comment]
OK I can confirm it's a false alarm. Something happens to my local zshrc file. It no longer contains actual `\e` escape codes any more..

**Comment by DHowett** [comment]
Weird!

**Comment by skyline75489** [comment]
Maybe it's just me doing some copy-paste thing that ruined the zshrc in the past but I didn't realize that. Never mind. Still a false alarm.

**Comment by jdebp** [comment]
It's a lot easier to instead use the Z shell's built-in mechanisms for coloured prompts, e.g. `%F{green}`, `%B`, `%b`, and `%K{254}`.  One does not have to calculate or hardware any control sequences at all, and this problem does not occur.

**Comment by trajano** [comment]
@skyline75489  are you using zsh from Windows like git-bash or WSL2?

**Comment by zadjii-msft** [comment]
He was using WSL; his `.zshrc` was corrupted.
