### ISSUE TITLE
Add Github Action: OneFuzz

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7638]
# Description of the new feature/enhancement

https://www.microsoft.com/security/blog/2020/09/15/microsoft-onefuzz-framework-open-source-developer-tool-fix-bugs/

> What was once attached—at great expense—can now be baked into continuous build systems through:
> 
> Crash detection, once attached via tools such as Electric Fence, can be baked in with asan.
> Coverage tracking, once attached via tools such as iDNA, Dynamo Rio, and Pin can be baked in with sancov.
> Input harnessing, once accomplished via custom I/O harnesses, can be baked in with libfuzzer’s LLVMFuzzerTestOneInput function prototype.

# Proposed technical implementation details (optional)
It's already being used internally by Windows. As this is a MS project, this should be able to be easily adopted. Source code will be published at https://github.com/microsoft/onefuzz during CppCon 2020.

**Comment by DHowett** [comment]
Thanks for looking out for us! We're already engaged with this team internally. :smile: I'm gonna close this one out until our/their investigation comes to a close.

**Comment by WSLUser** [comment]
Great, hope we'll see it show up in the public repo. It'll be interesting to see what it shows for the Console.

**Comment by DHowett** [comment]
You may be happy to know we've already _got_ a fuzzer for our whole VT stack. That's one of the biggest/most important targets, since all application output goes through it.

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/tree/master/src/terminal/parser/ft_fuzzer and https://github.com/microsoft/terminal/tree/master/src/terminal/parser/ft_fuzzwrapper

**Comment by WSLUser** [comment]
Yes, I'm hoping/thinking the OneFuzz will replace those.

**Comment by DHowett** [comment]
Based on our discussions with them, their work will build on our existing test cases but replace the fuzzing driver.
