### ISSUE TITLE
Show profiles in task bar jump list when not running

### ISSUE THREAD

**Issue by Klikini** [microsoft/terminal#7641]
# Description of the new feature/enhancement

Creating separate task bar shortcuts for each profile is tedious and takes up a lot of screen space, so it would be nice if the application would show the list of profiles in the jump list when pinned to the task bar, allowing users to open a terminal window with any profile, not just the default profile.

![image](https://user-images.githubusercontent.com/1693960/93272484-31659380-f77b-11ea-9f9c-33020fcb6e9c.png)

In case my terminology is outdated, I mean a list of profiles to open in a terminal window similar to Edge's task list.

![image](https://user-images.githubusercontent.com/1693960/93272539-535f1600-f77b-11ea-8ea5-69d93912a920.png)

**Comment by DHowett** [comment]
/dup #576 we just landed this for 1.4, which is coming out soon (TM)
