### ISSUE TITLE
auto closed

### ISSUE THREAD

**Issue by lvzhuangzhuang** [microsoft/terminal#7642]
Windows Terminal

version: 1.2.2381.0

Now wt will exit by itself when the screen is locked, or shut down when it is not used for a long time.

**Comment by DHowett** [comment]
In addition, have you set `closeOnExit` to `always`?

**Comment by lvzhuangzhuang** [comment]
> 此外，您是否设置为 ？`closeOnExit``always`

no, closeOnExit is not set， It should be a default value

**Comment by lvzhuangzhuang** [comment]
I can't find the location of your collapse
