### ISSUE TITLE
After Paste, Undo removes one character at a time

### ISSUE THREAD

**Issue by Joe-Zer0** [microsoft/terminal#7647]
# Environment

```none
Windows build number:  [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0


Windows Terminal version (if applicable):  Version: 1.1.2021.0

Any other software?
```

# Steps to reproduce
Paste any text into the terminal.  Press "Ctrl+Z".

# Expected behavior
After pasting text into the terminal. Pressing "Ctrl+Z" should remove the entire text that was just pasted.

# Actual behavior
After pasting text into the terminal. Pressing "Ctrl+Z" currently just removes one letter.

**Comment by DHowett** [comment]
Paste works in almost all terminal emulators by printing the string character by character. In addition, the Terminal itself does not implement <kbd>Ctrl+Z</kbd>, so it is the job of the shell.

Once we support bracketed paste (#395) and PowerShell (which I presume you are using) supports bracketed paste (https://github.com/PowerShell/PSReadLine/issues/1471), this will work better.

/dup #395

**Comment by Joe-Zer0** [comment]
Doing directly in both PowerShell and PowerShell Core works.  After pasting, hitting "Ctrl+Z" remove the entire pasted string.

**Comment by DHowett** [comment]
This is because powershell/core are handling ^V themselves. If you remove the ^V key binding, you can get this behavior back, but ^V will not work in CMD or WSL.

**Comment by Andy-AO** [comment]
> 

So does this mean that basically can't get the same pasting effect in Windows Terminal as you can in PowerShell Core?

One time paste revocation is very convenient or has a high efficiency.

**Comment by zadjii-msft** [comment]
As mentioned above in https://github.com/microsoft/terminal/issues/7647#issuecomment-693608879, #9034 just added support to the Terminal for bracketed paste. PowerShell / PsReadline still needs to add support on their side, too. That's tracked in https://github.com/PowerShell/PSReadLine/issues/1471
