### ISSUE TITLE
commandline: ssh, When pasting, the tab crashes

### ISSUE THREAD

**Issue by Z-LL** [microsoft/terminal#7651]
# Environment 

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

1.2.2381.0
```

# Steps to reproduce

**settings.json:**
```
{
                "guid": "{***}",
                "name": "ip",
                "commandline": "ssh user@ip",
                "closeOnExit": "always",
                "icon": "path.png",
                "colorScheme": "nord"
}
```
This is the second tab setting, So I press ctrl+shift+2, I can directly enter the terminal after ssh remote, it works well, except for this problem: when I paste(ctrl+v,ctrl+shift+v,right click), this tab always closes automatically (may be pasted once or twice, Sometimes I pasted for nearly 10 times in a row, and ended up being closed), and the rest were not directly ssh tabs (such as entering cmd first, and then ssh remote) working normally.
In pane, the same problem.

# Expected behavior

I commented "closeOnExit": "always" in settings.json, When I paste, I have the following problems:
```
1:
packet_write_poll: Connection to IP port 22: eother

2:
A descriptionpacket_write_poll: Connection to IP port 22: eother

3:
Last loginpacket_write_poll: Connection to IP port 22: eother

4:
Lapacket_write_poll: Connection to IP port 22 : eother
```
The first type of abnormality is the most.

# Expected behavior

The current ssh tab is closed.

**Comment by DHowett** [comment]
This is very strange! It sounds like the same issue as /dup #7601
