### ISSUE TITLE
Portable tabs between windows.

### ISSUE THREAD

**Issue by yasintz** [microsoft/terminal#7652]
# Description of the new feature/enhancement

It would be nice to move the tabs to another window like chrome or create a new window from the tab. If not fully understood, the gif and video link below may be more explanatory.
[Video Url](https://ysnv.vercel.app/?videoUrl=https://cdn.discordapp.com/attachments/504592835782115330/756116519947075655/input.mkv)
![ss](https://user-images.githubusercontent.com/36041339/93464921-b2936680-f8f2-11ea-8132-ed4040211cdb.gif)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
