### ISSUE TITLE
Shortcut for renameTab.

### ISSUE THREAD

**Issue by yasintz** [microsoft/terminal#7653]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1082]
Windows Terminal version (if applicable): Windows Terminal Preview 1.3.2382.0
```

# Steps to reproduce
The renameTab command does not work with hotkeys.
![Screenshot_8](https://user-images.githubusercontent.com/36041339/93466424-e5d6f500-f8f4-11ea-849d-1e31511b85b2.png)

**Comment by DHowett** [comment]
This is very similar to https://github.com/microsoft/terminal/issues/1079#issuecomment-693536525 (which I don't expect you to have found!)

> You can do this with a key binding for `renameTab`, but right now you can only hardcode a title. There's an open PR (#7462) that adds `openTabRenamer`. We need to circle back to that open PR.

`renameTab` takes a hardcoded title value right now, but `openTabRenamer` will open the tab renamer.
