### ISSUE TITLE
WT中使用WSL,ALT无法正确使用

### ISSUE THREAD

**Issue by oTMaN-chengQ-G** [microsoft/terminal#7656]
我在WT中打开WSL使用VIM进行编辑,无法映射ALT键.(WT中使用PowerShell 则正常).

**Comment by skyline75489** [comment]
Translation:Alt can not be mapped in Vim when using WT in WSL. In PowerShell it’s good.

**Comment by DHowett** [comment]
This is by design. Sorry. http://vimcdoc.sourceforge.net/doc/map.html#:map-alt-keys
