### ISSUE TITLE
Cannot reorder tabs when terminal open on remote computer during RDP

### ISSUE THREAD

**Issue by RyanChomistek** [microsoft/terminal#7658]
# Environment
Client computer Windows Build: NT 10.0.19041.0

Remote computer Windows Build: 10.0.19041.0
Remote computer windows terminal version: 1.2.2381.0

# Steps to reproduce

1. log into client, and RDP into remote
2. in the remote computer open windows terminal and open 2+ tabs of any kind
3. try to drag the tabs in order to reorder them

# Expected behavior

The tabs reorder like how they do when terminal is open on a client computer

# Actual behavior

tabs do not move or reorder

**Comment by DHowett** [comment]
Are you running as admin on the remote machine?

**Comment by ificator** [comment]
I noticed this as well, and yes the instances that are not working are running as Administrator.
