### ISSUE TITLE
Quick SSH/Telnet Connection button

### ISSUE THREAD

**Issue by gil906** [microsoft/terminal#7660]
## **Please add a quick connect button.**

Please add a quick connect button so it will be like putty, that we can just put the IP, connection type (Telnet, SSH, Serial, etc) and  click connect, without the need to edit the settings.json file.

Sometimes we don't need to save a session, just a quick connect to a device and exit, it will be a great time saver if it has that feature, that the main difference with simple programs as Putty and more complete as SecureCRT.

**Comment by DHowett** [comment]
Thank you for the request!

Windows Terminal does not want to be a generic SSH client, so we are not likely to add a Quick Connect feature. It's a little too specific of a use case for a local Terminal, but it's something we can discuss for the future.

For now, it's easy enough to run `ssh 12.34.56.78` from another WT profile. :smile:
