### ISSUE TITLE
how to disable shortcut key: Ctrl+Shift+F ？

### ISSUE THREAD

**Issue by elegance** [microsoft/terminal#7665]
I want to disable the shortcut key: `ctrl+shift+f `, because it conflicts with other shortcut keys.

I have tried the following:
1.  Comment it:  // { "command": "find", "keys": "ctrl+shift+f" },
2.  Replace it:  { "command": "find", "keys": "ctrl+f" },

But `ctrl+shift+f` still works，It prevents the behavior i want.

**Comment by DHowett** [comment]
I believe there is a comment in that file about “unbound”. You should be able to set ctrl+shift+F to “unbound”.
