### ISSUE TITLE
Windows Terminal randomly closes when "RivaTuner Statistics Server" is running (MSI Afterburner + RivaTuner)

### ISSUE THREAD

**Issue by leterio** [microsoft/terminal#7666]
# Environment

```none
Windows build number: 19041.508
Windows Terminal version (if applicable): 1.3.2382 x64

Any other software?
MSI Afterburner: v4.6.2.15745
RivaTuner: 1.2.3 (installed with Msi Afterburner)
```

Log from Event View
![image](https://user-images.githubusercontent.com/15060358/93557346-22d0d500-f951-11ea-8177-5f97fb9fd55a.png)

# Steps to reproduce

Have installed MSI Afterburner with RivaTuner
Open Windows Terminal with some tabs (in my case, using wsl 2 with ssh session in some tabs)
Use for a few moments then terminal closes without any warning

# Expected behavior

Windows Terminal running without problems when MSI Afterburner with RivaTuner enabled is running

# Actual behavior

Windows Terminal closes without warning randomly

**Comment by DHowett** [comment]
Every time we see a crash here it is attributed to the library RivaTuner injects into every process. We don’t believe there is anything we can do until they fix the library.
