### ISSUE TITLE
Enhacements

### ISSUE THREAD

**Issue by smcguffee** [microsoft/terminal#7669]
# Description of the new feature/enhancement

Please make a GUI for the settings.
Please make ways to manage groups of windows with which system is open, what directory we are in, and what the tab titles are. We should be able to click a button and get all our tabs set the way we want for each of the various workflows we have.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Please search for duplicates before filling new issues.

/dup #1564
