### ISSUE TITLE
There are two settings.json, they take effect in different terminals.

### ISSUE THREAD

**Issue by loren5555** [microsoft/terminal#7671]
I'm using Win10,there're two settings.json
one of them is in
C:\Users\XXX\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
and the other one is in
C:\Users\XXX\AppData\Local\Microsoft\Windows Terminal\settings.json
opening from the start menu the first one tekes effect,but starting from the run window, the second takes effect.
why does this happen

**Comment by DHowett** [comment]
You have installed two copies of Terminal, one from the store and one from a broken package manager like Scoop that decided to run Terminal outside of its package.

**Comment by loren5555** [comment]
But I didn't do that. Both mine and my firend's conputer have this problem. We just installed it onetime in the store.
