### ISSUE TITLE
Ability to Create Profiles Groups in 'New Tab' Drop-Down Profile Menu

### ISSUE THREAD

**Issue by folsom** [microsoft/terminal#7672]
# Description of the new feature/enhancement

I have a lot of profiles, such that the drop-down menu listing of them runs off the bottom of my screen and requires scrolling to reach those at the bottom.

I'd like to be able to construct groupings of profiles within the 'settings.json' file such that the group would have a name that would show up in the main drop-down, with its own drop-down menu listing the contained profiles.

# Proposed technical implementation details

Here is an example 'profiles' object with a 'list' containing a 'group' object as a member that names and defines a group of profiles:

<pre>
{
   "profiles":{
      "defaults":{
         "useAcrylic":true,
         "acrylicOpacity":0.7,
         "cursorShape":"filledBox",
         "cursorColor":"#00FF00",
         "closeOnExit":true
      },
      "list":[
         "group":{
            "name":"Profile Group",
            "members":[
               {
                  "guid":"{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                  "name":"Windows PowerShell",
                  "commandline":"powershell.exe",
                  "hidden":true
               },
               {
                  "guid":"{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                  "name":"Command Prompt",
                  "commandline":"cmd.exe",
                  "hidden":false
               }
            ]
         },
         {
            "guid":"{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden":false,
            "name":"PowerShell",
            "colorScheme":"Campbell Powershell",
            "source":"Windows.Terminal.PowershellCore"
         }
      ]
   }
}
</pre>

Given the above, there would be a 'Profile Group' listed in the New Tab drop-down, with an arrow to the right indicating a sub-menu.  Hovering or clicking on the sub-menu would display profile names 'Windows PowerShell' and 'Command Prompt'.

The 'group' object could also have other contained properties that would define characteristics of the profile name in the New Tab drop-down--probably identical to the properties used for the profile name display itself. 

The 'group' object could also contain other 'group' objects that would define sub-groups within the top-level group, with some reasonable limit to group nesting.

**Comment by DHowett** [comment]
Thanks for writing this up! It looks like we've got some of this covered in #1571, and a spec accepted in #5888 :smile:

I'm gonna close this one out as a duplicate.

**Comment by lakani** [comment]
is this really implemented , it doesn't exists in Version: 1.18.2681.0

**Comment by zadjii-msft** [comment]
@lakani It sure is! #1571 was closed by #13763, which shipped in 1.17.

See: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#new-tab-dropdown

**Comment by lakani** [comment]
many thanks, it works now

**Comment by folsomke** [comment]
@lakani ...thanks for checking on this and @zadjii-msft ...thanks for the link to the documentation.  This is a great addition to Windows Terminal!
