### ISSUE TITLE
A newWindow command would be very convenient

### ISSUE THREAD

**Issue by cva** [microsoft/terminal#7674]
# Description of the new feature/enhancement

I regularly want to open an entirely new Windows Terminal window (vs. creating a new tab within an existing window). Presently, the only way I can determine how to do this requires me to go to the taskbar in windows, right-click the application icon, and choose Windows Terminal.

# Proposed technical implementation details (optional)

I would love for there to be a `newWindow` command similar to the existing `newTab` command that I can bind to a keyboard shortcut of my choosing.

**Comment by DHowett** [comment]
Thanks for the request! I believe this is a /duplicate of #1051.
