### ISSUE TITLE
Cann't disable "Ctrl+l/h/k/j/\"

### ISSUE THREAD

**Issue by ethercflow** [microsoft/terminal#7680]
I tried this one is OK:

```
{ "command": "unbound", "keys": [ "ctrl+shift+f" ] },
```

But these are not:
```
{ "command": "unbound", "keys": [ "ctrl+h" ] },
{ "command": "unbound", "keys": [ "ctrl+l" ] },
{ "command": "unbound", "keys": [ "ctrl+j" ] },
{ "command": "unbound", "keys": [ "ctrl+k" ] },
{ "command": "unbound", "keys": [ "ctrl+\\"] }
```

I need these because I want to use https://github.com/laishulu/emacs-tmux-pane , 

My terminal version is:  1.2.2381.0
WSL version: 2
Ubuntu 20.04 with wsl2

Thanks!

**Comment by DHowett** [comment]
Interesting. Terminal does not use those keys!

**Comment by ethercflow** [comment]
> Interesting. Terminal does not use those keys!

@DHowett Thanks, maybe related to wsl2? I find in wsl2, ssh to my server, my server's tmux is ok, but wsl2's tmux not.

**Comment by ethercflow** [comment]
@DHowett I found the reason,  only "reboot" <Distro> can let tmux load the modified .tmux.conf.local. Thank you for developing such a great app，also sorry to raise the issue without careful investigation.

**Comment by DHowett** [comment]
No need to apologize! It's a strange issue, for sure. :smile:

Glad you got it figured out.
