### ISSUE TITLE
Where can I find the Windows Terminal Icon?

### ISSUE THREAD

**Issue by imthenachoman** [microsoft/terminal#7682]
I created a shortcut to `C:\Users\nacho\AppData\Local\Microsoft\WindowsApps\wt.exe` but it has the default/generic Windows icon:

![image](https://user-images.githubusercontent.com/83817/93694379-0495e100-fad9-11ea-813e-da7a2b5bbbdb.png)

I would prefer it to use the Windows Terminal icon:

![image](https://user-images.githubusercontent.com/83817/93694384-16778400-fad9-11ea-83fc-ff1573de5c52.png)

But I cannot find the source icon anywhere so I can set it in the shortcut properties.

**Comment by j4james** [comment]
I'm not sure if this is what you want, but you can always download the icon from the github source tree here:
https://raw.githubusercontent.com/microsoft/terminal/master/res/terminal.ico

**Comment by imthenachoman** [comment]
Thank you so much. I searched everywhere but couldn't find it. Not sure why. Thank you so much!

**Comment by calebTree** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/2682726/209910904-b53be674-1cc3-45bd-9847-3efd108809bd.png)
Here is my WT icon issue if anyone has any ideas?

**Comment by stephenskett** [comment]
I had this problem too - very weird!! Thanks @j4james for highlighting the location of the official icon file.
(My solution at the time was to download the rasterized PNG icon from [the relevant Wikimedia Commons page](https://upload.wikimedia.org/wikipedia/commons/f/f9/Windows_Terminal_Logo.png) then convert to ICO using some random ICO-converter-tool, but this way is much better!)

**Comment by pilgrimlyieu** [comment]
> You can user "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10262.0_x64__8wekyb3d8bbwe\wt.exe" for the icon.

However, when it updates, its path changes. So it may not so stable.
