### ISSUE TITLE
Add support for custom WSL clients like MinTTY

### ISSUE THREAD

**Issue by benzhi** [microsoft/terminal#7684]
I've tried to integrate MinTTY, which is a WSL terminal that feels most like a genuine Linux terminal. So far, opens as a standalone Window, not as a tab in the Windows Terminal.

**Comment by skyline75489** [comment]
I'm not gonna say it's not possible. But it's highly unlikely to happen in Windows Terminal. One of the reason Windows Terminal exist is to (partially) replace terminals like MinTTY. MinTTY itself is a fully functional terminal. So is Windows Terminal. I don't see a good motivation to merge these two.

**Comment by benzhi** [comment]
If Ubuntu WSL look and feel improves to the level of MinTTY, you're totally right

**Comment by zadjii-msft** [comment]
Are there any features in particular you're missing from mintty?

**Comment by skyline75489** [comment]
@benzhi Trust me. Many people are working hard to improve Windows Terminal to its finest.

**Comment by benzhi** [comment]
> Are there any features in particular you're missing from mintty?

I think, it is already a huge improvement from te Ubuntu terminals for WSL, especially the tabs. I read some things on customizing color-schemes which are already very helpful, although I didn't find font family and size so far. Especially the size way too large to me.
I'll try to pay attention to the small details that differ, although they may be a bit hard to spot when working on remote clusters. The biggest thing that is annoying, is the fact that double clicking on an ls-ed path only selects a single word, then clicking again selects the whole line. On Linux distro's, and on MinTTY for that matter, you select the full path when double clicking. Addionally, when pressing the mousewheel next, the selected text is copied and pasted back to the terminal instantly, which makes life really more pleasant when bashing with long paths :-)

**Comment by zadjii-msft** [comment]
@benzhi I'd take a look at [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings), they include lots of different ways of customizing your terminal profiles, including schemes, fonts, background images, and more.

As far as double clicking on the path, #3196 is a discussion about changing the default `wordDelimiters` setting to remove `/` and `\` so that they're not counted as characters that separate words.

Then, you might also be interested in #1553, which could potentially include the mousewheel to copy & paste config

**Comment by benzhi** [comment]
> @benzhi I'd take a look at [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings), they include lots of different ways of customizing your terminal profiles, including schemes, fonts, background images, and more.
> 
> As far as double clicking on the path, #3196 is a discussion about changing the default `wordDelimiters` setting to remove `/` and `\` so that they're not counted as characters that separate words.
> 
> Then, you might also be interested in #1553, which could potentially include the mousewheel to copy & paste config

Thanks for the hints! I'll have a look at them
