### ISSUE TITLE
Build issue with CascadiaPackage

### ISSUE THREAD

**Issue by AkhilJose2019** [microsoft/terminal#7685]
Following the debug tutorial steps in the github page for making Application process and Background proccess to 'Native Only' in the CascadiaPackage it shows this error

![image](https://user-images.githubusercontent.com/47634643/93708465-0b156e80-fb54-11ea-9469-8ca66d2cc48f.png)

My system
OS: Windows 10 
Version: 2004
OS Build: 19041.508
IDE: VS 2019
CPU Intel Core i3-4005U
RAM: 4GB
System Type: 64Bit

**Comment by skyline75489** [comment]
You'll need to change the Configuration to "x64".

**Comment by skyline75489** [comment]
And by the way you'll be likely to need a more powerful machine to compile and run WT in Visual Studio. I don't think you'll be happy about the performance with i3 + 4GB.

**Comment by DHowett** [comment]
Looks like this was answered. Thanks @skyline75489!
