### ISSUE TITLE
Autocompletion in git bash for windows flashes/blinks

### ISSUE THREAD

**Issue by mlewand** [microsoft/terminal#7688]
# Environment

```
Windows build number: Version 10.0.19041.508
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
Git(git for Windows): 2.28.0
```

# Steps to reproduce

1.  Open a new git bash tab.
2.  Navigate to your windows directory.
3.  Type "cd syst".
4.  Press <kbd>tab</kbd> twice.

# Expected behavior

Screen doesn't flash, your command is unfolded to "cd system".

# Actual behavior

Screen flashes gray for a moment.

![](https://user-images.githubusercontent.com/5353898/93742000-a870b100-fbed-11ea-9bb6-86833984b7ec.gif)

If you inspect the gif frame-by-frame it actually inverts colors, rather than make it all single color:

![](https://user-images.githubusercontent.com/5353898/93741988-a3136680-fbed-11ea-833c-87b0a2fd1c0b.png)

Interestingly it doesn't happen consistently. If I <kbd>backspace</kbd> it twice (so that it is "cd syst" again) and press tab, there might be no flash this time.

It's not reproducible in git bash console app itself.

It's a regression that happened over last quarter or so, but I'm surprised I didn't find any existing issue on that.

Here's how the prfilefor bash is defined:

```
   "profiles": [
        {
            "acrylicOpacity": 1,
            "closeOnExit": true,
            "colorScheme": "Campbell",
            "commandline": "<basePath>\\usr\\bin\\bash.exe\" -i -l",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Consolas",
            "fontSize": 8,
            "guid": "{0504d9fc-deca-44e1-83c4-213dca5023e7}",
            "historySize": 9001,
            "icon": "<basePath>\\mingw64\\share\\git\\git-for-windows.ico",
            "name": "Bash",
            "padding": "0, 0, 0, 0",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%",
            "useAcrylic": true
        },
```

**Comment by skyline75489** [comment]
It may sounds crazy but I think this is actual expected. It's a so-called "Visual Bell".

**Comment by DHowett** [comment]
Yes, this is a "visual bell". [Here is a comprehensive list of ways to turn of visual bells.](https://tldp.org/HOWTO/Visual-Bell-8.html)

**Comment by mlewand** [comment]
Oh, thanks! Didn't know about that 👍

**Comment by splitcells** [comment]
Considering the fact, that this effect does not appear in git bash for Windows itself,
wouldn't it be helpful to add an FAQ to https://docs.microsoft.com/de-de/windows/terminal/tips-and-tricks or even the APP?

**Comment by DHowett** [comment]
> Considering the fact, that this effect does not appear in git bash for Windows itself,

It will on a version of Windows where the console host has the aforementioned change. Promise.
