### ISSUE TITLE
Using Microsoft Telnet in Windows Terminal display and inputs bug

### ISSUE THREAD

**Issue by rhdlilj** [microsoft/terminal#7689]
# Environment

```none
Windows build number: 10.0.18363.1082
Windows Terminal version (if applicable):1.2.2381.0

Microsoft Telnet
```

# Steps to reproduce
1. Using Microsoft Telnet in Windows Terminal, if the output lines more then the window size, the scroll bcak context display is wrong。
![image](https://user-images.githubusercontent.com/55023294/93743691-11bee700-fc23-11ea-9070-904118a27863.png)

2. And then, if changing the window size smaller, input will be failed too.
![image](https://user-images.githubusercontent.com/55023294/93743899-79753200-fc23-11ea-8800-06bf6f643224.png)

# Expected behavior
1.the scroll bcak context display shuld be correct.
2.input  shuld be ok.

# Actual behavior

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6056 for more discussion.

/dup #6056
