### ISSUE TITLE
Moving window after opening drop down

### ISSUE THREAD

**Issue by Larsklopstra** [microsoft/terminal#769]
**ver:** 
Microsoft Windows [Version 10.0.18362.86]

**problem:**
Moving the window after opening the drop down menu causes the drop down menu to be stuck/fixed relative to your screen.

![image](https://user-images.githubusercontent.com/25669876/57704635-9890a680-7662-11e9-8621-051b841520db.png)

**Comment by zadjii-msft** [comment]
I'm pretty sure this is a XAML islands bug, but there might be something we can do to mitigate it.

Summoning @marb2000, maybe he can direct this to the right parties.

**Comment by Larsklopstra** [comment]
This problem does not occur in the maximized mode

**Comment by oising** [comment]
@Larsklopstra What do you mean exactly? If the window is maximized, then you can't really move the window, so yes, I'd expect this bug not to manifest. Or do you mean something else?

**Comment by Larsklopstra** [comment]
@oising Nevermind, it still does. I might be able to show you a recording

**Comment by zadjii-msft** [comment]
Hey look, we lost track of this bug. This was resolved as #2028, in #2438, and was released some time in _August 2019_.
