### ISSUE TITLE
Please add  "next search match" and "prev search match" bind-able key for find operations

### ISSUE THREAD

**Issue by lsemprini** [microsoft/terminal#7695]
Hi, thanks so much for Terminal!  I would like to be able to bind a key to go to the next and previous search match in an existing "find" that I already have started.  I don't see a way to do this at:

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings

**Comment by DHowett** [comment]
Good idea! I'll hook this up to the Search epic #3920.

**Comment by Hegunumo** [comment]
I'd like to try work on this!
