### ISSUE TITLE
Unable to open options on microsoft/terminal

### ISSUE THREAD

**Issue by joltar** [microsoft/terminal#7696]
I would like to open Win 10 Ubuntu each time I open the terminal.  The default semms to be to open Windows PowerShell.  I can add Ubuntu 20.04 root by using the down arrow, so I am able to switch from one to the other.  Wonderful!
But when I try to open the "options", if I click on the symbol, The photo editing program , Affinity Photo, opens.  And the shortcut, Ctrl +, does not do anything

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):1.2.2.381.0 Win 10 

Any other software? I have Vivaldi Browser open, and Win 10 64 bit build 18363. and Xming X server running.
```

# Steps to reproduce

# Expected behavior

I expect a menu of options to open.

# Actual behavior: Affinity Photo opens.  Or nothing opens, if I try the shortcut keys combination, Ctrl+.

I am unsure. Terminal works brilliantly otherwise.

**Comment by KalleOlaviNiemitalo** [comment]
If you right-click some other `.json` file in File Explorer and choose "Open with", "Choose another app", select a text editor such as Notepad, check "Always use this app to open .json files", and click "OK", then the "Settings" menu item in Windows Terminal should use that editor from then on.

Alternatively, you may be able to use "Choose default apps by file type" in the Settings app to choose an editor for `.json` files.  However, that does not appear to offer a "Look for another app on this PC" option.

**Comment by KalleOlaviNiemitalo** [comment]
The shortcut key for Settings is Ctrl+comma, not Ctrl+period.

**Comment by DHowett** [comment]
Yes, this has to do with the default json file association. You can reset it using the method @KalleOlaviNiemitalo suggests, or by visiting the File Associations page in settings.

When we land #1564, JSON editing will become less necessary.

**Comment by joltar** [comment]
Sorry, typing mistake.  That's what I get for learning to type at the Fort Ord U.S.Army clerk school, instead of in high school.  Thanks for noticing.

**Comment by joltar** [comment]
I did as you suggested, clicked on a json file and changed the properties to open it in a text editor.  However, when I click on the icon for settings, the photo ass, Affinity Photo, opens.  Apparently the desktop shortcut to open preferences in Affinity Photo is also Ctrl+,  I should have thought of this before.

Since Terminal works just fine, I'll just live with it until the promised revision.  Thanks
