### ISSUE TITLE
Hyperlinks: Please allow "file" schema

### ISSUE THREAD

**Issue by daniel-liuzzi** [microsoft/terminal#7699]
# Description of the new feature/enhancement

At the moment, hyperlink support [seems limited](https://github.com/microsoft/terminal/blob/49b9d41caf1ae03180af3744bdb5d910d702fb10/src/cascadia/TerminalApp/TerminalPage.cpp#L1809) to just `http` and `https` schemas. It would be nice if `file` was supported as well.

A sample use case for this is https://github.com/dandavison/delta, an excellent viewer for git and diff output that, among other things, shows line numbers in a git diff as links pointing to the given file. This currently doesn't work due to Windows Terminal blocking the file schema:

![image](https://user-images.githubusercontent.com/143884/93928043-01d5fe80-fd1a-11ea-8257-ffedfdc5541a.png)

**Comment by DHowett** [comment]
I hate duping things to PRs, but this one has some active discussion on it. 

> We were having a long discussion over on #7526 about it, and never came to anywhere we felt comfortable with. The same discussion is playing out in #7668, because of how hard it is for the Terminal alone to map paths...

**Comment by DHowett** [comment]
ON second though, I'll reopen this bug as a landing site to redirect folks / point the PR at.
