### ISSUE TITLE
Colortool can find scheme, but can not load it

### ISSUE THREAD

**Issue by lu-ym** [microsoft/terminal#770]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17763 Build 17763 (Windows 10 Enterprise)
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
![image](https://user-images.githubusercontent.com/15881320/57706698-d6a8bd00-7698-11e9-95f8-650d19f36d46.png)
* What's wrong / what should be happening instead:
should set this scheme to my power shell

**Comment by zadjii-msft** [comment]
What colortool version are you running?

Where exactly are the `WildCherry.itermcolors` and `colortool.exe` files?

**Comment by lu-ym** [comment]
![image](https://user-images.githubusercontent.com/15881320/57739812-a1778b80-76e7-11e9-84ee-6b2f1d27f79d.png)
I installed the colortool via scoop.

**Comment by zadjii-msft** [comment]
Okay, that's helpful.

Looks like this isn't the only report of this either, so something's probably messed up.

**Comment by lu-ym** [comment]
So this is a bug? There is no solution for now?

**Comment by mdtauk** [comment]
I was playing with my console and powershell colours last night, and had to use the older release of the tool as the current release would not work.

**Comment by zadjii-msft** [comment]
I'm not sure, but it seems like it is a bug. Someone will need to debug it further.

**Comment by lu-ym** [comment]
Thank @mdtauk and @zadjii-msft .
I rollback colortool to 1810.02002 version. This bug disappeared. But the schemes can not work well. Just take a example:
![image](https://user-images.githubusercontent.com/15881320/57787947-daa41000-7768-11e9-8492-f2fb1eff3990.png)
Hope for next stable version.

**Comment by lefb766** [comment]
Looks like the program is now accepting scheme filename (with file extension) instead of scheme name. :joy:

Try `colortool campbell.ini`.

**Comment by surmann** [comment]
I think, I have the same problem, see below. Any ideas?

    > ColorTool.exe -v
    colortool v1.0.1904.29002
    user@PS C:\ProgramData\chocolatey\lib\colortool\content\schemes
    > ls
        Directory: C:\ProgramData\chocolatey\lib\colortool\content\schemes
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----       24.01.2020     14:11      122,60 KB AtomOneLight.itermcolors
    -a----       24.01.2020     14:13      120,19 KB ayu_light.itermcolors
    -a----       24.01.2020     14:12      155,31 KB BlulocoLight.itermcolors
    -a----       24.01.2020     14:12      120,53 KB Bright Lights.itermcolors
    -a----       24.01.2020     14:12      154,78 KB Builtin Light.itermcolors
    -a----       24.01.2020     14:12      155,52 KB Builtin Solarized Light.itermcolors
    -a----       24.01.2020     14:12      155,24 KB Builtin Tango Light.itermcolors
    -a----       25.04.2018     22:31      746 Bytes campbell.ini
    -a----       25.04.2018     22:31      441 Bytes campbell-legacy.ini
    -a----       25.04.2018     22:31      454 Bytes cmd-legacy.ini
    -a----       25.04.2018     22:31        7,44 KB deuteranopia.itermcolors
    -a----       24.01.2020     14:13      135,75 KB Night Owlish Light.itermcolors
    -a----       02.10.2018     18:12        9,65 KB OneHalfDark.itermcolors
    -a----       25.04.2018     22:31        9,61 KB OneHalfLight.itermcolors
    -a----       24.01.2020     14:13      120,89 KB PencilLight.itermcolors
    -a----       24.01.2020     14:13      120,53 KB Piatto Light.itermcolors
    -a----       24.01.2020     14:13      155,08 KB Pro Light.itermcolors
    -a----       02.10.2018     18:12        6,59 KB solarized_dark.itermcolors
    -a----       25.04.2018     22:31        7,69 KB solarized_light.itermcolors
    -a----       24.01.2020     14:13      155,47 KB Violet Light.itermcolors
    
    user@PS C:\ProgramData\chocolatey\lib\colortool\content\schemes
    > ColorTool.exe .\AtomOneLight.itermcolors
    Could not find or load ".\AtomOneLight.itermcolors"

**Comment by felipesix** [comment]
Thank you @lefb766 it has worked for me by specifying the file extension name.

Someone has to fix the documentation because the instructions don't ask the user to use the extension name, in fact as far as I could understand I should **NOT** use extension name and let the tool lookup for files in the order `.ini > .json > .itemcolors`

**Comment by lu-ym** [comment]
fixed. Just forget to close this issue.
