### ISSUE TITLE
New 1.4 VT colors bug, foreground color not applied to " " (space) cells when hyperlinked

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#7700]
Come on, you knew this was coming, it's almost the same as #5502 😅

So we now have hyperlinks that show dotted underline under characters that are part of a link (since 1.4.2652.0)
You're probably delaying taking the attributes into account until they have a visible effect, which is sensible.
So foreground colors are not applied until a non-space character is shown.

But for hyperlinks, you're using the foreground color to draw the dotted underline, so you should now check if cell is a non-space or part of a hyperlink.

The following should only have the "Red" 3 cells with a red foreground color, but instead the red foreground is kept for two extra cells until the 'h' character is encountered, incorrectly making the dotted underline red in those cells.
`echo -e '\e]8;;http://www.example.com/\aSample  \e[31mRed\e[m  hyperlink\e]8;;\a'`

![image](https://user-images.githubusercontent.com/25664275/93941906-a7479d00-fd2f-11ea-9dc6-6ffb1973da62.png)

**Comment by DHowett** [comment]
YUP, you caught us

**Comment by DHowett** [comment]
@PankajBhojwani this is an error carried forward by `HasIdenticalVisualRepresentationForBlankSpace` that impacts conpty _and_ the dx renderer -- we have to treat hyperlink like underline (has vs not has) instead of just checking if they're the same. Ideally we'll do both.

**Comment by PankajBhojwani** [comment]
Thanks for catching this! Fix is in PR

**Comment by PhMajerus** [comment]
@PankajBhojwani Thanks for fixing it.
