### ISSUE TITLE
copying from Vim editor to windows notepad, changes too much of spaces and not alligned

### ISSUE THREAD

**Issue by shettypriy** [microsoft/terminal#7703]
When I copy the contents from a WSL unbuntu terminal using vim to a windows notepad it add too many spaces for the text and all will be wrapped in a single line with scroll bar creating horizontally. There is no proper alignment of the text . Could you please help me on this

**Comment by DHowett** [comment]
Do you have an example? Copying text from vim works for me in WSL in Windows Terminal.

**Comment by shettypriy** [comment]
<img width="196" alt="vim" src="https://user-images.githubusercontent.com/42608605/94647901-16fcef80-030f-11eb-9f5a-735fa031f5b1.png">
<img width="950" alt="notepad" src="https://user-images.githubusercontent.com/42608605/94647912-1cf2d080-030f-11eb-8509-a2da6beffb24.png">

In the first screenshot, I have opened a file using vim and copied those contents from the terminal to the notepad. When pasting the contents to notepad in Windows, it adds many spaces as shown in the second screenhot

**Comment by shettypriy** [comment]
<img width="196" alt="vim" src="https://user-images.githubusercontent.com/42608605/94648079-604d3f00-030f-11eb-9419-9c64ab5a2d05.png">
<img width="950" alt="notepad" src="https://user-images.githubusercontent.com/42608605/94648084-62af9900-030f-11eb-890a-b25df06c82a0.png">

In the first screenshot I am copying the contents from a file which is opened uisng vim in the terminal and when pasting the same contents to the windows notepad it adds to many spaces to the text and is not alligned correctly as shown in the screenhot

**Comment by skyline75489** [comment]
Looks like a classic CRLF vs LF issue. If the text you copied uses LF, it will not have proper line ending in notepad.exe which uses CRLF by default. The latest notepad.exe actually has a nice indicator at the bottom:

![image](https://user-images.githubusercontent.com/4710575/95651340-5223cd80-0b1c-11eb-8975-68834d690461.png)

**Comment by DHowett** [comment]
This isn't a regression, but we could handle the end of line behavior vim needs better. /dup #3088
