### ISSUE TITLE
White square around elements

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#7705]
# Description of the new feature/enhancement

Not sure if this is a future, but ... This white square pokes me out of myself when using a hotkey.
By the way, this is a problem with the windows 10 interface as a whole, I see this in office, in the calculator, and in many other places in modernUI applications.
![image](https://user-images.githubusercontent.com/35394377/93979387-f0c2d700-fd85-11ea-9f57-6bbe7e70bbc5.png)

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
Yeah...I think this is out the scope of this repo.

**Comment by Mystic8b** [comment]
In some programs, I have never noticed this, or it seems to me that this is also a windows 10 problem?

**Comment by jdebp** [comment]
[When you are using flat menus, a highlighted menu item is surrounded by a border with a different system colour.](https://docs.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-getsyscolor#COLOR_MENUHILIGHT)  This is not a Windows Terminal thing.

**Comment by DHowett** [comment]
Indeed. This is the keyboard focus indicator, and it is going to be present anywhere you access ancillary UI by using the keyboard.
