### ISSUE TITLE
Jumplist doesn't show user defined icons

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#7706]
# Environment

```none
Windows build number: 10.0.19041.508
Windows Terminal version (if applicable): 1.4.2652.0
```

# Steps to reproduce

Add an `icon` entry to a profile that contains a path like

```json
"icon": "C:/Users/Frank/ubuntu.ico",
```

# Expected behavior

The icon is shown in the jumplist

# Actual behavior

There is no icon for that entry in the jumplist

Note that default icons with ms-appx do show up in the jumplist

```json
 "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
```

**Comment by DHowett** [comment]
Try with `\\` (backslash plus JSON escaping rules) instead of `/`

**Comment by ffes** [comment]
Weird, but it solves the problem (or is it a work-around?). In no other place using a `/` in a profile path that is a problem but apparently for the jumplist it is.
