### ISSUE TITLE
Can't run command line programs if COMSPEC is set to wt.exe

### ISSUE THREAD

**Issue by dancojocaru2000** [microsoft/terminal#7707]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

Set the COMSPEC environment variable to `PS > Get-Command wt | Select-Object -ExpandProperty Source`

Double click a command line executable from Windows Explorer.

# Expected behavior

The program running in Windows Terminal instead of Command Prompt.

# Actual behavior

A dialog box shows up saying:

```none
The following argument was not expected: /c
Run with --help for more information.
```

**Comment by zadjii-msft** [comment]
Why are you changing COMSPEC? I was under the impression that it was always supposed to be the path to a command line shell (specifically cmd.exe), _not_ the path to a terminal

**Comment by dancojocaru2000** [comment]
Because I would want command line executables to open in Windows Terminal, not cmd. A random Google search said that would be a way to do it. I'm not really an expert on this stuff 😅

**Comment by zadjii-msft** [comment]
Well that random Google search was definitely wrong, because that's not currently possible 😄 you'll want to take a look at #492, which covers that exact scenario

/dup #492
