### ISSUE TITLE
Add more control options

### ISSUE THREAD

**Issue by donno2048** [microsoft/terminal#7708]
# Description of the new feature/enhancement:
`ctrl + z`, `ctrl + s`, `ctrl + o`, etc (for undo, save as batchfile, open a batchfile)
(The `i` `a` `f` `h` `v` `c` `x` `m` keys are already working with `ctrl`)

**Comment by DHowett** [comment]
Terminal isn’t a text editor and it does not edit batch files. Those shortcuts do not have any meaning to the Terminal.

You can use those shortcuts with whatever application you want _inside_ Terminal.

**Comment by DHowett** [comment]
Thanks for the request! 💯
