### ISSUE TITLE
Ctrl-Tab switching needs a 'most-recently used order' option

### ISSUE THREAD

**Issue by pbradshawAUS** [microsoft/terminal#7709]
# Need an option for Ctrl-Tab to switch tabs in MRU order

# Proposed technical implementation details (optional)

**Comment by KalleOlaviNiemitalo** [comment]
This was already requested in <https://github.com/microsoft/terminal/issues/973>.

**Comment by DHowett** [comment]
Thanks for finding the duplicate! /dup #973.
