### ISSUE TITLE
Preview v1.4.2652.0 - after a window resize Hyperlinks are applied up to the end of line

### ISSUE THREAD

**Issue by jogo-** [microsoft/terminal#7713]
# Environment

```none
Windows build number: 10.0.18363.1082
Windows Terminal version (if applicable): 1.4.2652.0
```

# Steps to reproduce

1. Download then run this [raw win10colors.cmd](https://gist.githubusercontent.com/mlocati/fdabcaeb8071d5c75a2d51712db24011/raw/b710612d6320df7e146508094e84b92b34c77d48/win10colors.cmd) CMD file
2. Resize the terminal window

# Expected behavior

Standard underline or hyperlinks dotted underline is just applied to the text (the same with background colors)
![image](https://user-images.githubusercontent.com/4701169/94055429-3959af00-fddd-11ea-81b7-14007f0d33d2.png)

# Actual behavior

Standard underline or hyperlinks dotted underline is applied up to the end of line (the same with background colors)
![image](https://user-images.githubusercontent.com/4701169/94056141-2f847b80-fdde-11ea-8fb3-2427f11935b8.png)

**Comment by j4james** [comment]
This is issue #32.
