### ISSUE TITLE
如果有图形配置界面就更香了，当然如果设置界面还是中文那就更香了！

### ISSUE THREAD

**Issue by WangJincheng4869** [microsoft/terminal#7717]
如果有图形配置界面就更香了，当然如果设置界面还是中文那就更香了！

**Comment by skyline75489** [comment]
请不要删除 issue 模板，并且在提出新 issue 之前搜索有没有类似的存在。

Please do not remove the issue template and search for similar issues before submitting new one. /dup #1564

**Comment by WangJincheng4869** [comment]
> [问题]，]，]，
> 
> 请不要删除问题模板，并在提交新问题之前搜索类似的问题。/杜普#1564

不好意思，英文不好，看不懂模板里写的都是些什么（建议模板中加入中文翻译，毕竟百度和谷歌的机器翻译还是差点意思）。搜索了中文关键字没有搜索到类似的反馈，英文该搜索什么关键字不清楚，因为我英语很差！

**Comment by zuozishi** [comment]
设置UI已经在[2.0开发计划](https://github.com/microsoft/terminal/blob/master/doc/terminal-v2-roadmap.md#terminal-20-roadmap)中列为首要任务了，而且现在已经支持中文了，设置UI肯定也是。

**Comment by zadjii-msft** [comment]
Thanks for the help triaging this one @skyline75489!

/dup #1564
