### ISSUE TITLE
ssh断开之后能重连就好了

### ISSUE THREAD

**Issue by hanhua1994** [microsoft/terminal#7719]
ssh断开之后能重连就好了

**Comment by hanhua1994** [comment]
最好是能一键重连，就像xshell一样。希望这个以后能代替xshell使用。

**Comment by skyline75489** [comment]
This is about restore SSH session like XShell. I don't honestly know if #961 covers this.

**Comment by DHowett** [comment]
961 may cover this; however, Terminal isn't intending on adding SSH-specific features right now :smile:
