### ISSUE TITLE
Deploy Terminal to Microsoft Store (either as beta/Insider builds)

### ISSUE THREAD

**Issue by jcoutch** [microsoft/Terminal#772]
Would it be possible to release preview/Insider builds of Terminal in the Microsoft Store?  Having to install 30 GB of C++/UWP tooling, followed by a compilation that takes up another 20 GB of storage, seems pretty excessive just to try out the terminal.

Or at a minimum, maybe release the binaries on GitHub with a PowerShell script to install Cascadia.  Then, you'd be able to do nightly/weekly builds.

**Comment by oising** [comment]
This is exactly what is going to happen in June, when the terminal will be in a better, more usable state. The current build of the terminal is really only intended for experienced developers, not for admins and power users (hence the proliferation of issues regarding building it!) This also helps us debug issues with building the terminal across a wide range of scenarios, environments and platforms. Publishing the current terminal to Windows Store now will undoubtedly cause an absolute torrent of issues to be logged, most of them duplicates and probably already solved by the time we get around to triaging them :) So, please be patient -- it's coming.
