### ISSUE TITLE
startup commands from command line for wt

### ISSUE THREAD

**Issue by alper-batioglu** [microsoft/terminal#7720]
# Ability to set startup commands from command line startup.
What I want is to be able to set startup command of the terminal tab/pane from a command line option for wt.
Something like "--startup" option. There is an example of the usage down below. 

# Proposed technical implementation details 

Example is for settings an environmental variable for git bash. Each pane in each tab gets its own prefix group name preceeded by the path. Open wt and 2 split panes with git bash and just execute TITLEPREFIX=G1 in each pane and see for yourself. :)

But basically it is for executing a command initially for each tab/pane.

**example usage:** (imagine as single line, switched to multiline for readability)
wt  -d {PATH1} --startup "TITLEPREFIX={Group1}" ;
 split-pane -V -d {PATH2} --startup "TITLEPREFIX={Group1}" ;
 split-pane -V -d {PATH3} --startup "TITLEPREFIX={Group1}";
 new-tab -d {PATH4} --startup "TITLEPREFIX={Group2}";
 split-pane -V -d {PATH5} --startup "TITLEPREFIX={Group2}" ;
 new-tab --title web -d {PATH6} --startup "TITLEPREFIX={Group3}";
 split-pane -V -d {PATH7} --startup "TITLEPREFIX={Group3}";
 new-tab --title mobile -d {PATH8} --startup "TITLEPREFIX={Group4}";
 focus-tab -t 0

**Comment by skyline75489** [comment]
Maybe #6776 ?

**Comment by alper-batioglu** [comment]
yes, seems like #5528
