### ISSUE TITLE
Script Snips

### ISSUE THREAD

**Issue by torrentx** [microsoft/terminal#7721]
# Description of the new feature/enhancement

A way to save and quickly use common command line inputs. For example git commands such as: 
> git.exe pull --progress -v -no-rebase "origin"

# Proposed technical implementation details (optional)
Add a Snips folder to the drop down next to tabs at the top. Functionality here would be edit/delete/add/reorder snippets. 

From the command line Alt-Shift-<number or letter of script> would copy it to the command line and allow for immediate running. 

For example 
alt-shift-1  Enter would pull the snippet and run it.

**Comment by KalleOlaviNiemitalo** [comment]
You can already edit `settings.json` to bind Alt+Shift+1 to the [`sendInput` action](https://docs.microsoft.com/windows/terminal/customize-settings/actions#send-input) (<https://github.com/microsoft/terminal/issues/3799>) with the snippet as a parameter. <https://github.com/microsoft/terminal/issues/1564> mentions that key bindings would be part of the settings UI in the future.

**Comment by DHowett** [comment]
Indeed. `sendInput` is going to be our story for now, and once we get the ability to bind actions into the menu and toolbar and stuff it'll be easy to build up a compendium of snippets.

Gotta ask, though: why not use an alias in your shell? They're way more flexible than a "blast this input into the terminal" button...
