### ISSUE TITLE
Have an option to centre the terminal if a certain InitialPosition value is given

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/terminal#7722]
# Description of the new feature/enhancement

I would like to be able to tell Windows Terminal to centre itself on the screen, rather than provide a numerical InitialPosition value.

# Proposed technical implementation details (optional)

1. Provide a value such as "auto-centre" or "centre" to InitialPosition
2. ???
3. Profit!

**Comment by zadjii-msft** [comment]
I... don't hate this actually. I don't think this would be too hard to do, thanks for the suggestion!

**Comment by Hegunumo** [comment]
I'm on this!
