### ISSUE TITLE
In the recent Update the CTRL+Tab is showing a list of tabs on top of the windows which distracts and impacts the performance

### ISSUE THREAD

**Issue by jiveshwar** [microsoft/terminal#7723]

**Comment by jiveshwar** [comment]
useTabSwitcher is the setting I was looking for.

**Comment by shusson** [comment]
thanks @jiveshwar, this really bothered me as well. For other people who don't know what the settings look like: https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json
