### ISSUE TITLE
Windows Terminal not working in S-mode

### ISSUE THREAD

**Issue by vkocjancic** [microsoft/terminal#7724]
# Environment

```none
Windows build number: Windows 10 in S-mode (I don't think build number matters, to be honest)
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Install Windows Terminal app from app store.
2. Run Windows Terminal app
3. Try opening cmd terminal

# Expected behavior

I would see a powershell or cmd.exe window.

# Actual behavior

I get an error ```[error 0x800711c7 when launching 'powershell.exe']``` or ```[error 0x800711c7 when launching 'cmd.exe']```.
Is that in any way related to the s-mode limitations?

**Comment by KalleOlaviNiemitalo** [comment]
0x800711c7 = HRESULT_FROM_WIN32(ERROR_SYSTEM_INTEGRITY_POLICY_VIOLATION), "Your organization used Device Guard to block this app. Contact your support person for more info."

**Comment by KalleOlaviNiemitalo** [comment]
The improved error reporting <https://github.com/microsoft/terminal/issues/7186> would be nice here.

**Comment by DHowett** [comment]
It definitely would.

Terminal is not intended to work in S mode, however. Terminal is a window through which you see other applications, and those “other applications” are restricted.

**Comment by vkocjancic** [comment]
Ok I get that. Maybe it would be worth considering not offering the app to S mode OS in app store then.

**Comment by DHowett** [comment]
Unfortunately, the store has not given us that option. Sorry!
