### ISSUE TITLE
Running `wt` in command line wont start windows terminal

### ISSUE THREAD

**Issue by Sardonyx78** [microsoft/terminal#7725]
# Environment

Windows build number: Win32NT 10.0.20215.0 Microsoft Windows NT 10.0.20215.0
Windows Terminal version (if applicable): 1.3.2651.0

# Steps to reproduce
run `wt`

# Expected behavior
Windows Terminal Opening Correctly

# Actual behavior
Getting an error

<img src="https://i.sardonyx.studio/‍🐯😡🐻😩💘🧡😏" >

**Comment by Sardonyx78** [comment]
The problem magically fixed itself I'm closing this issue.

**Comment by DHowett** [comment]
Oh, I hate when bugs just go away like that! Thanks for following up. :smile:
