### ISSUE TITLE
Dotted and dotless i are not handled properly for Turkic languages

### ISSUE THREAD

**Issue by gokcehan** [microsoft/terminal#7726]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
```

# Steps to reproduce

1. Change keyboard input language to Turkish Q
2. Type `ı` on the keyboard (<kbd>i</kbd> key in English layout)
3. Type `İ` on the keyboard (<kbd>Shift+'</kbd> key in English layout)

# Expected behavior

It should type `ıİ` in the terminal

# Actual behavior

It types `i` in the terminal

The above description may not be the best way to describe this issue. We have this confusing language feature in my native language Turkish as well as other Turkic languages. We have two separate characters for `i` for dotted and dotless versions. As you know fonts draw regular `i` with a dot when it is lowercase (i.e. `i`) and without a dot when it is uppercase (i.e. `I`). Therefore unicode conforming applications need to change the character value when the case is changed and the locale is Turkish. Examples below:

```
istanbul <-> ISTANBUL   (incorrect)
istanbul <-> İSTANBUL   (correct)
ıstanbul <-> ISTANBUL   (also correct but that is not the name of our city)
```

I would not mind this much but windows terminal shows `ı` as `i` which can be confusing when you forget to change your keyboard layout. Also hitting uppercase `İ` does not seem to type anything to the terminal which is kind of weird.

This issue happens in Windows terminal and powershell terminal, but cmd.exe terminal and most other applications like notepad seems to handle this properly.

Some related links below:

https://en.wikipedia.org/wiki/Dotted_and_dotless_I
https://unicode.org/faq/casemap_charprop.html

**Comment by DHowett** [comment]
If you use “command prompt” (cmd) inside Windows Terminal, what happens?

Terminal is a way for you to interact with many different text-mode applications; it will be important to identify if this is a client-specific issue.

**Comment by gokcehan** [comment]
@DHowett Oh, I haven't thought about it. Indeed, there is no problem when I run `cmd.exe` inside windows terminal. So this seems like a powershell issue and not related to windows terminal. Should I report this to somewhere else then?

**Comment by Sardonyx78** [comment]
<img src="https://i.sardonyx.studio/😀😩🐸😛🤭🤡🐲😫">
I dont have the problem tho

**Comment by DHowett** [comment]
@Sardonyx78 excellent background image choice!

@gokcehan interesting! Before I suggest filing the bug elsewhere... one more question: in PowerShell (inside Terminal), does it work when you `Remove-Module PSReadline`?

**Comment by gokcehan** [comment]
@DHowett Yes, I can confirm running `Remove-Module PSReadline` fixes the problem.

**Comment by DHowett** [comment]
Excellent! In that case, the appropriate place to file this issue is https://github.com/powershell/psreadline.

Thanks!
