### ISSUE TITLE
Command Palette should support page up/down to move faster thru the options

### ISSUE THREAD

**Issue by azchohfi** [microsoft/terminal#7729]
# Description of the new feature/enhancement
After pressing Ctrl+Shift+P, the only way to navigate thru the options is to use the key up/down. If I press Page Up or Page Down, it should move faster thru the options. Right now, I have to press the down key many times, or leave it pressed, which is far from an optimal experience.

# Proposed technical implementation details (optional)
I don't believe we need this to be customizable, so a fixed "page down/up" should just go to the end of the visible list, showing more options available, similar to how XAML's ListView already handles this scenario.

**Comment by DHowett** [comment]
I mean, sure, but command palette is meant to be _searched_.

**Comment by azchohfi** [comment]
Yes... but if you want the last option on the list after typing only a few characters, it should support moving thru the options slim faster. Other keys, such as "End" and "Home", should also work as expected. Its frustrating that this is a list, yet doesn't behave like one.

Example:
![image](https://user-images.githubusercontent.com/527713/94186659-cf341f00-fe5b-11ea-87bc-d017cccdfc09.png)
I want to reset the font size (which is the last option on the list), and I don't want to remember shortcuts, or I just forgot one of them. I want to press End or PageDown and not KeyDown 6 times.

**Comment by zadjii-msft** [comment]
Yeah I totally intended to do this and just forgot about it. My bad!

**Comment by DHowett** [comment]
Triaged, tagged "easy starter", marked for 1.5.
