### ISSUE TITLE
Multiple profile for the same WSL instance

### ISSUE THREAD

**Issue by ajit555db** [microsoft/terminal#7732]
Primarily each profile mapping to different default folders (startingDirectory setting).

**Comment by jack775544** [comment]
You can do that already by doing something like this in your settings.json

```json
{
    "guid": "{d8a4a45a-cca2-45d0-9b26-06b227f1a140}",
    "name": "My New WSL",
    "commandline": "wsl -d Ubuntu",
    "startingDirectory": "C:\\Program Files"
}
```

**Comment by zadjii-msft** [comment]
Yep, you can do this exactly as @jack775544 mentions above.
