### ISSUE TITLE
Stopped responding and was closed

### ISSUE THREAD

**Issue by mkahvi** [microsoft/terminal#7733]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2641.0

Any other software? Node.js
```

# Steps to reproduce
Unknown. Node.js was run. Desktop was locked. These don't cause it to happen on their own tho.

# Expected behavior
No crash.

# Actual behavior
Terminal crashed. The Node.js server kept running with no live terminal to control it by.

Windows application log has following entry:

> The program WindowsTerminal.exe version 1.2.2008.25001 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
>  Process ID: 1c50
>  Start Time: 01d691043827f38c
>  Termination Time: 4294967295
>  Application Path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
>  Report Id: d667144b-73e4-4526-9fcb-5f660e582e7f
>  Faulting package full name: Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe
>  Faulting package-relative application ID: App
>  Hang type: Quiesce

Judging by the error above, the terminal was automatically updated during or shortly after the problem before I noticed it?

There was also these errors logged at the same time, possibly related to it:

> Fault bucket 2028434469579443634, type 5
> Event Name: MoAppHang
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe
> P2: praid:App
> P3: 1.2.2008.25001
> P4: 5f45901e
> P5: 0c21
> P6: 2097152

And this:

> Fault bucket 1707257287759330481, type 5
> Event Name: PowerShell
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: powershell.exe
> P2: 10.0.19041.1
> P3: System.InvalidOperationException
> P4: System.InvalidOperationException
> P5: unknown
> P6: System.Console.ReadKey
> P7: unknown

**Comment by zadjii-msft** [comment]
I'm almost _certain_ that this is caused by the Microsoft Store auto-updating the Terminal for you. I believe there's threads linked to #6726 that have more details. IIRC, we've got an open thread with the app platform team right now to try and find a better way to prevent us from getting terminated. (@ future me: the thread is titled "hits for HANG_QUESCE that don't point to anything"). 

See also #7350,  #6726

/dup #6726
