### ISSUE TITLE
Easy way to duplicate tab and preserving current working directory

### ISSUE THREAD

**Issue by MartyIX** [microsoft/terminal#7734]
# Description of the new feature/enhancement

**Feature:**

* I open Terminal. 
* I work a bit and I often need to open the same tab again with the same working directory. 

Typically I need this to do some minor task and I don't want to navigate away from my opened tab just to return back again. This is easy with Ubuntu terminal where I just press CTRL+SHIFT+T to duplicate the tab as specified earilier.

**Notes:**

* I'm not sure there is a way to do that with Terminal now. Please let me know if Terminal can already do it.
* I'm not sure whether other people work in similar fashion so I'm not sure how large the target audience would be.
* I find this behavior useful for all sorts of tabs (Windows PowerShell tab, any WSL tab, etc.).

# Proposed technical implementation details (optional)

Unfortunately not.

**Comment by skyline75489** [comment]
There's #3158 for this particular issue and I've filed #7668 which is a working proposal. You'll find a lots of useful info in those two threads. Unfortunately due to various technical issues I don't think this feature can be shipped very soon. Sorry about that 😓 .

**Comment by MartyIX** [comment]
Thank you! I'll subscribe the issue. Would love that feature :-)
