### ISSUE TITLE
User-friendly profile editing/visualization (Enhancement)

### ISSUE THREAD

**Issue by serle** [microsoft/terminal#7735]
1) Given that there are multiple profile files i.e. all users on machine profile, current in user profile etc; and these are located in "user unfriendly" system locations, it would far more user friendly to be able to edit or at least initiated an edit action from a menu item than force the user to hunt down and edit the files manually.

2) Provide a GUI-based comprehensive profile view showing all active profile elements available to a given terminal config, showing which level of profile they are being activated in. e.g. I want to see which profile added what alias or commandlets and their order of precedence so I can debug any clashes.

3) Provide a standardised mechanism for packaging, sharing and installing profile extensions into given terminals e.g. sets of alias, additional commandlets etc which embody best practices or productivity enhancing toolsets e.g. git commands, github commands, bash aliases etc.

**Comment by DHowett** [comment]
Thanks for the request! For _terminal_, we're tackling a few of these things over in /dup #1564, #7584 ("fragments/snippets") and #2933.

However, based on a couple things ("commandlets", "user, system, etc.", and "aliases") I think you're talking about PowerShell profiles. All of those features are totally outside the scope of the terminal, and we unfortunately can't control them. Terminal is, at the end of the day, a window through which you interact with _other_ applications. The main one people are using these days is PowerShell . . . so therefore:

This might be a very good feature request to file against the PowerShell team! [Their repository](https://github.com/powershell/powershell) is quite active and they're very receptive to feedback.

Cheers!
