### ISSUE TITLE
The new popup on ctrl+tab is horrendous

### ISSUE THREAD

**Issue by TheDirigible** [microsoft/terminal#7737]
I need to see the tab I'm going to highlighted, not a separate window pop up.

**Comment by pmorch** [comment]
Or give me a way to disable it or *something*.

**Comment by zadjii** [comment]
This isn't really _constructive_ feedback though, is it? Any ideas how it could be improved?

Maybe "When selecting a new tab with the tab switcher, preview the selected tab in the Terminal", #7409?

Maybe you want to disable the tab switcher, with `"useTabSwitcher": false`?

**Comment by TheDirigible** [comment]
Really constructive feedback would be, don't create any UX change without user feedback, and try not to fix what isn't broken.  But this being Microsoft, I'll settle for, please give me a way to disable it.

**Comment by zadjii** [comment]
> don't create any UX change without user feedback,

You mean feedback like:
"Feature Request: An advanced tab switcher" #1502

**Comment by DHowett** [comment]
Yeah, we created this feature due to overwhelming community feedback in support of it. We also gave folks the option to turn it off due to our community's likewise-overwhelming ability to be curmudgeonly.

**Comment by TheDirigible** [comment]
You're mistaking a few people requesting something with a majority, leading you to turn this on by default.  Defying the conventional logic of every other terminal in existence should require a more detailed user survey.  Programmers should not be making these decisions, that's what UX people are for.  This kind of thinking is what leads a company to think a full screen "your files are exactly where you left them" is a good idea.  That's not curmudgeonly, that's logic and more than a passing understanding of UX.

The effect of mistakes like this could be lessened by showing release notes when there's an update, like Sublime Text does.  Instead, this thing silently updated, closing all my tabs in the process.  Same old Microsoft, 40 years of telling the user what they want.
