### ISSUE TITLE
Pasting into terminal uses second to last item in clipboard

### ISSUE THREAD

**Issue by thatchux** [microsoft/terminal#7739]
# Environment

```none
Windows build number:  10.0.19042.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
Amazon Workspaces
```

# Steps to reproduce

Copy an item from Win 10 host, then copy an item from Win10 workspace, and paste into terminal. 

# Expected behavior

Last item copied is pasted

# Actual behavior

Second to last item on clipboard is pasted into the terminal.

If I paste into another app, ie: Notepad, VSCode, etc., the last item copied is pasted, which is different behavior than Win Terminal

**Comment by DHowett** [comment]
The weird thing is, Terminal is just saying "hey system, give me the clipboard".

Is this consistent? Does it only reproduce with Amazon Workspaces? Is it possible to test Workspaces without shelling out too much money?

**Comment by thatchux** [comment]
I filed a bug to AWS about it as well in case it's on their side; but it's 100% consistent behavior. I'm in the process of transposing ~500 single lines from in the terminal to out; and I need to copy a line out of my notepad on my host in between the copy/paste, and every single time, the terminal is taking what I copy out of notepad. I'll hit [esc] and clear the line, then paste again, and the line I copied from my workspace is pasted.

**Comment by DHowett** [comment]
Any response from the AWS folks? We haven't seen any other reports of this with any other software, and we're just using the supported Windows clipboard APIs. :/

**Comment by thatchux** [comment]
I'm so sorry I haven't followed up Dustin!
I haven't gotten a response from them, no, but I have been able to reproduce the issue with other applications into and out of their workspaces app.
You can close this for sure.
________________________________

**Comment by zadjii-msft** [comment]
Thanks for following up!
