### ISSUE TITLE
Pasting into PowerShell Core omits some characters

### ISSUE THREAD

**Issue by redactedscribe** [microsoft/terminal#7740]
# Environment

```none
Windows build number: 10.0.19041.508
Windows Terminal version (if applicable): 1.2.2381.0
PowerShell Core: 7.0.3
```

# Steps to reproduce

In Windows Terminal, paste a string containing an mdash ("—"), such as `a—string`, into a tab running PowerShell Core.

# Expected behavior

Pasting should paste every character.

# Actual behavior

The string is pasted, but the mdash is omitted, resulting in `astring`. The same is true of *n*dashes too, and likely some other more uncommon symbols. Manually inserting an mdash (Alt+0151) works without issue, only pasting is the problem.

If pasting into either PowerShell 5 (installed on Windows by default) or Command Prompt via WT, the paste will succeed.

If running PS Core directly (not contained inside of WT), pasting will succeed here too.

It seems the problem is between WT and PS Core.

I couldn't find any open issues, but I assume I don't know what to search as I imagine this would be a quickly-noticed bug by many. This issue has been around for some months at least.

Thanks.

**Comment by DHowett** [comment]
Thanks for the report! This is going to seem like I'm directing you in circles, but the thread below is enlightening even though it just points to _another_ repository's issue :smile:

/dup https://github.com/PowerShell/PSReadLine/issues/760
