### ISSUE TITLE
Add option to make tab colors permanent.

### ISSUE THREAD

**Issue by shubhsboson** [microsoft/terminal#7745]
# Description of the new feature/enhancement

An option to make tab colors non-volatile so the changes stay .

# Proposed technical implementation details (optional)
There could be a option such as 'setTabColor' is settings.json .

**Comment by DHowett** [comment]
You can actually do this with `tabColor` in the profile!

**Comment by shubhsboson** [comment]
Oh, I am so sorry for my poor research capabilities and wasting your time. Also thanks a lot for helping.

**Comment by shubhsboson** [comment]
And the faster than Flash response.
