### ISSUE TITLE
One report of a runaway RegOpen/Query loop

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7748]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1082 (1909)
WindowsTerminalPreview_1.4.2652.0_x64
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

Right now WT has one tab, one pane, and one command processor idling.  It's using about 3.5 seconds of CPU (kernel + user) every minute, by far the busiest process I have after for "System Idle Process".  ProcessExplorer is monitoring all categories and reporting over 100 events per second.  They look like this.

![image](https://user-images.githubusercontent.com/61856645/94345312-00932300-fff3-11ea-8ecd-cfb95072a0ec.png)

**Comment by vefatica** [comment]
I'm not so sure about that RegOpen/Query thing.  WT seems to do that a lot and I'm not very good at interpreting what ProcessMonitor is showing.  This thread is probably not aptly titled.  One thing is for sure, opening and closing split panes ups the subsequent CPU use.  You need some sort of tool to see this.

One way is with ProcessExplorer.  Start WT and ProcessExplorer.  In ProcessExplorer, open WindowsTerminal.exe, go to the "Threads" tab and watch WT's main thread (here that's WindowsTerminal.exe+0x12AD0).  After startup and settledown, and while idling, "CyclesDelta" is in the neighborhood of 10,000,000 (here anyway).  Now open and close a split pane 5 times (close it with the "exit" command).  Here, "CyclesDelta" (idling) is now in the 50,000,000 range.  Open/close 5 more.  "CyclesDelta" is now in the 100,000,000 range.

If you can automate the opening/closing of split panes you can get more get striking results.  I've had TaskMgr showing a constant 4% CPU for an idling WT.

**Comment by DHowett** [comment]
This is weird! We don't actually use those anywhere in Terminal, directly, so this smells like a framework issue. I can't explain why the system would be querying for display scaling every .03 seconds.

**Comment by vefatica** [comment]
As I said I'm not sure the increase in CPU use is related to the registry thing (see my second post).  Maybe when the buffer is too small it's increased only modestly ... try again ... increase again ... try again ... until it works.  That's what my pic might be showing.  That sort of thing also seems to happen with other registry queries.

But there's definitely increased CPU usage AFTER opening and closing a split pane.  You only have to do a few to see a difference.  If you have ProcessExplorer, try my experiment.  There's a small memory leak too but that's harder to detect.

**Comment by DHowett** [comment]
To be fair, I'm responding to the issue you _reported and put in the title_ :wink:

**Comment by vefatica** [comment]
Yes I realize that.  And I admitted earlier that the thread may not be aptly titled.

**Comment by vefatica** [comment]
This appears to be the same issue as #8625.  It does not seem to be related to any Reg* loop.

**Comment by DHowett** [comment]
Oh, I see. Thanks for identifying the duplicate -- you can tell how far back I am in triaging. /dup #8625.
