### ISSUE TITLE
Feature: Blurless, simple background transparency

### ISSUE THREAD

**Issue by hcsong213** [microsoft/terminal#7750]
# Description of the new feature/enhancement
Transparent background, kind of like cmder.

I use the terminal extensively for web dev and change tabs very frequently to see what the web page looks like and what the console is outputting. Having a semi-transparent background (with no aesthetic acrylic blur) eliminates the need to do this since I can see both at once.

This sort of echos the suggestion to change the blur level of the acrylic effect (#1753 ), though I assume this feature would be a bit easier to implement.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I think the feature you're looking for is #603.
