### ISSUE TITLE
Add Git Bash to available shell when installed

### ISSUE THREAD

**Issue by gyssels** [microsoft/terminal#7756]
All good? Then proceed!
--> yes

# Description of the new feature/enhancement
Add Git Bash to the available shell when installed on the system

# Proposed technical implementation details (optional)
1)Add Git Bash option between the available choices
2)I propose to look up to the standard installation folder and is not there a file-path to the binaries. Actually, I didn't search on your implementation how is done, but ignore this point is not fit.
3) keep your good work, I'm loving it!

**Comment by floh96** [comment]
Duplicate see #1394

**Comment by DHowett** [comment]
Indeed. In addition to this, we're not intending on adding much more automatic detection. It doesn't scale, and it often does things users _don't_ want. It's harder to get it right when we're just guessing what folks want, so we're looking at features that allow applications to specify their profiles (so Git Bash could add itself, if you opt in) instead. Hope that helps!

/dup #1394.
