### ISSUE TITLE
custom profiles don't scale

### ISSUE THREAD

**Issue by cadayton** [microsoft/terminal#7759]
I have hundreds of potential ssh sessions and I don't want to create 100s of custom profiles for each instance.  It would helpful if parameterized custom profiles was supported.  Also, looking forward to when new-tab can actually open a new tab rather than a new window.

Today, I do the following with ConEMU.  Define a PowerShell alias 'ldp' (load putty) that does the following.
```putty.exe -new_console -load $hostname```

In a ConEMU's powershell console, entering 'ldp $hostname' launches a new tab with the ssh session to the host.

This is the only issue preventing me from dropping ConEMU in favor of Windows Terminal.

**Comment by jack775544** [comment]
If you use the ssh command line tool instead of putty you can get something similar. If you create a [ssh config file](https://futurestud.io/tutorials/simplify-your-ssh-connections-with-ssh-config-file) then you can connect by using `ssh myServer` on the command line. Combine this with the ability to run arbitrary commands in new tabs with the ctrl+shift+p menu by prefixing the command with a `>` character you can open whatever connection you want just by going `ctrl+shift+p` and then typing `>ssh myServer`.

**Comment by zadjii-msft** [comment]
> Combine this with the ability to run arbitrary commands in new tabs with the ctrl+shift+p menu by prefixing the command with a `>` character you can open whatever connection you want just by going `ctrl+shift+p` and then typing `>ssh myServer`.

Wow I didn't even think about that as a potential use case, but that's a great use of the commandline mode of the command palette. Thanks for sharing!

<hr>

We've got: 
* Add support for inheriting and overriding another profile's settings #3818
* Add support for wt.exe to run commands in an existing Terminal Window #4472 

If you're okay with it opening a new window, `wt ssh $hostname` will let you run `ssh $hostname` in a new WT window, with the default profile.

I bet that #4472 would really be the best way to solve this for you, to be able to just do something like `wt -s 0 new-tab ssh $hostname`. Does that sound like a good solution to you?

**Comment by cadayton** [comment]
I tried the recommendation of ctrl-shift-p and enter '>ssh <hostname>'.  The ssh config was setup up correctly but the console wasn't able to present the password prompt.  When I used the full host domain name all worked as expected.  Note  the new tab value was just duplicated from the original tab.  It would be nice if the new tab could have the hostname.

The #4472 option sounds like potential solution.  I see making using of the ssh config would be nice too, but not sure why my config is being ignored for some reason.

Here is a work around, I did but the tab value is always a static 'ssh' when using this work around.  In the settings, I defined a profile containing:

```"command" : "powershell.exe -NoExit psSSH.ps1"```

The PowerShell script simply prompts for the needed info to launch a ssh session.

**Comment by cadayton** [comment]
I locked down the .ssh directory so only my account can access it now.  The >ssh <hostname> method has terminal emulation issues when not using the full host domain name and the target host is RHEL.  Can ssh to a Cisco switch using PKI and just the hostname and it works perfectly.   I'm sort of favoring my work around because I have the option of customizing the profile attributes.  I think that I'll trick up the powershell script to use the ssh config file though.

**Comment by zadjii-msft** [comment]
Alright, so I'm gonna close this in favor of #4472. Thanks for following up!

/dup #4472
