### ISSUE TITLE
Fix activatableClass warning during build

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#776]
This happens during the build:

```
##[warning]WindowsTerminal.manifest(0,0): Warning 81010002: Unrecognized Element "activatableClass" in namespace "urn:schemas-microsoft-com:winrt.v1".
    51>WindowsTerminal.manifest : manifest authoring warning 81010002: Unrecognized Element "activatableClass" in namespace "urn:schemas-microsoft-com:winrt.v1". [d:\a\1\s\src\cascadia\WindowsTerminal\WindowsTerminal.vcxproj]
```

I don't want this to happen because it will get in the way of seeing other more valid errors.

I think @zadjii-msft knows something about this. Hopefully we can find a way around it (suppressing this one, using the right schema, etc.)

**Comment by DHowett-MSFT** [comment]
In the absence of a warning suppression flag for mt, the quickest way around this one is to use the 10.0.18362.0 SDK. The manifest tool there supports these new entries.

**Comment by miniksa** [comment]
Wonder if these are in the managed agents yet given this is like a bleeding edge/just released SDK. Maybe someone can figure this out...

**Comment by DHowett-MSFT** [comment]
This fixed itself with the 18362 SDK.
