### ISSUE TITLE
Manually configured Git Bash popped up in a standalone window

### ISSUE THREAD

**Issue by jerryc05** [microsoft/terminal#7760]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): 1.4.2652.0

Any other software? 
    Git 2.28.0.windows.1
```

# Steps to reproduce
1. I added these lines to `profiles.list` in WT settings and saved:
```
            {
                "guid": "{00000000-0000-0000-0000-000000000000}",
                "name": "Git Bash",
                "closeOnExit" : "always",
                "commandline": "D:/Program Files/Git/git-bash.exe",
                "hidden": false
            },
```
2. I started Git Bash from WT's dropdown menu.

# Expected behavior
Git Bash shall run inside WT.

# Actual behavior
Git Bash popped up as a standalone window, not inside WT.
[Screenshot here:](https://ibb.co/JCDyT6L)
![](https://i.ibb.co/R7RBKrn/Screenshot-20200927161801.png)

**Comment by tomad8** [comment]
Hi @jerryc05 

Try using this path instead for your commandline property: 
D:/Program Files/Git/bin/bash.exe

This worked for me when I had the exact same issue.

**Comment by jerryc05** [comment]
> Hi @jerryc05
> 
> Try using this path instead for your commandline property:
> D:/Program Files/Git/bin/bash.exe
> 
> This worked for me when I had the exact same issue.

Thanks! Worked like a charm!
