### ISSUE TITLE
The system detected an overrun of a stack-based buffer in this application 

### ISSUE THREAD

**Issue by rekaerst** [microsoft/terminal#7763]
# Environment

```none
Windows build number:  19041.388
Windows Terminal version (if applicable): 1.3.2651.0

```

# Steps to reproduce
- on Windows PowerShell execute ```cat <a big file: lager than 2MB>```, using vim to edit the big file, list files in the directory, use any terminal program to deal with big files will cause error ```The system detected an overrun of a stack-based buffer in this application ```

- on WSL execute ```htop```,```top```,```cat <a big file>```, using any programs to process file larger than 2MB, use resources intensive programs such as MySQL server will cause error ```The system detected an overrun of a stack-based buffer in this application ```

- on cmd, PowerShell core, git bash, etc. is the same

the error only occurs when running shell on Windows Terminal , not the programs them self.
# screenshots
![image](https://user-images.githubusercontent.com/52642831/94420094-3c2a1a80-01b6-11eb-843e-834e170e564f.png)
![image](https://user-images.githubusercontent.com/52642831/94420122-477d4600-01b6-11eb-9f44-5a1c76dc5216.png)
![image](https://user-images.githubusercontent.com/52642831/94420126-49470980-01b6-11eb-8d6a-8bd6cb99fe62.png)
![image](https://user-images.githubusercontent.com/52642831/94420382-a8a51980-01b6-11eb-8c73-773d0bf16f89.png)
![image](https://user-images.githubusercontent.com/52642831/94420502-d4280400-01b6-11eb-8057-0a21cf73c0fd.png)
![image](https://user-images.githubusercontent.com/52642831/94420499-d38f6d80-01b6-11eb-938b-ae8828ed4c75.png)
# PS
The shell and programs are still running after Windows Terminal crashed.

**Comment by KalleOlaviNiemitalo** [comment]
I hit something similar on 2020-09-25. Windows Terminal Preview 1.4.2652.0 on Windows 10 build 19041.508 crashed several times with exception code 0xc0000409 (STATUS_STACK_BUFFER_OVERRUN) when I was trying to use "git log". There were no message boxes but the reliability history and the Application event log show this code. I have not been able to reproduce the error later.

**Comment by rekaerst** [comment]
The error could temporarily disappear after reboot the computer but after a period of time, I can still reproduce the error. From Windows Terminal beta to now, this is the first time I get those errors. Windows Terminal Preview 1.4.2652.0 crashes on my computer too.

**Comment by DHowett** [comment]
I can't reproduce this. Can one of you use task manager to capture a dump file of Terminal when that dialog pops up?

**Comment by rekaerst** [comment]
[WindowsTerminal.dmp](https://github.com/rekaerst/rekaerst.github.io/raw/master/WindowsTerminal.zip)

**Comment by KalleOlaviNiemitalo** [comment]
@rekaerst's dump file has `Windows_UI_Xaml!CXamlIslandRoot::OnIslandPointerWheelChanged + 0x12` in the call stack of the thread that called `KERNELBASE!RaiseFailFastException`. I am pretty sure I was not using the mouse wheel when Windows Terminal Preview crashed. But if the bug is in rendering, then it could crash in both situations anyway.

**Comment by rekaerst** [comment]
I was not using a mouse when it crashed too. I was just running cat some_text_file command.

**Comment by KalleOlaviNiemitalo** [comment]
Apparently, [`WilFailFast` uses `STATUS_STACK_BUFFER_OVERRUN`](https://github.com/microsoft/wil/blob/b74575e9feb6477c52208fbc60557ad22f8bf42b/include/wil/result_macros.h#L3599) even if the error is not a buffer overrun. The instructions immediately before the return address `TerminalControl!DllGetActivationFactory+0x27a3c` set R8 = "E:\BA\127\s\src\buffer\out\textBuffer.cpp" and EDX = 280, so I think it blew up in `TextBuffer::_PrepareForDoubleByteSequence` here: <https://github.com/microsoft/terminal/blob/d4614bf04176cc57cd9b1ee4acace8126e76450d/src/buffer/out/textBuffer.cpp#L278-L280>

**Comment by DHowett** [comment]
So, this is interesting! This dump is the same as in #4907. We've tried to tackle this issue before, but not quite gotten there. It seems that there's some buffer corruption where a DBCS character gets split and the trailing half gets duplicated (by a function that _isn't_ checking its legality), which then explodes when it hits this function (Reflow) that does check.

We usually only see it during resize, which includes mouse wheel scrolling.

@KalleOlaviNiemitalo I'll keep this open to see if you can produce a dump that's different?

[Symbols for 1.4.2652](https://terminalnuget.blob.core.windows.net/packages/CascadiaPackage_1.4.2652.0_x64.appxsym)

**Comment by KalleOlaviNiemitalo** [comment]
OK, I added a Registry key as instructed in [Collecting User-Mode Dumps](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps), so that I'll get a dump if `WindowsTerminal.exe` crashes again.

**Comment by DHowett** [comment]
Thanks!
