### ISSUE TITLE
test bug

### ISSUE THREAD

**Issue by Chandresh1007** [microsoft/terminal#7764]
test

**Comment by DHowett** [comment]
It is not usually appropriate to file testing issues on other peoples’ repositories. How can we help?

**Comment by Chandresh1007** [comment]
testing access of labels

**Comment by zadjii-msft** [comment]
Again, please do not use someone else's repo for testing.

**Comment by DHowett** [comment]
Just figured this out - hi @Chandresh1007! I didn't realize you were with HCL. Sorry about that! :smile:

**Comment by Chandresh1007** [comment]
@Dhowett Yeah, you got it right.  I was just checking the access to add labels but I am still not able to add. 
Can we add labels in the bugs created by other?

**Comment by Chandresh1007** [comment]
Got access now.
