### ISSUE TITLE
The list of terminals is in wrong place when using screen magnifier

### ISSUE THREAD

**Issue by Pit-Storm** [microsoft/terminal#7765]
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
* Screen magnifier (Windows 10 Built in)
```

# Steps to reproduce
* Open Terminal and Press `Windows` + `+` to magnify the screen.
* Click the down-arrow near the Plus-Button to open the menu list.

# Expected behavior

* The List-Menue should open next to the down-arrow like when the screen is not magnified

# Actual behavior

* The list-menu opens somewhere (most times bottom-right) on the whole screen outside the magnified area.
* The list-menu ist much bigger then the magnifier zoom-level would expect.

**Comment by zadjii-msft** [comment]
Which magnifier view are you using?
![image](https://user-images.githubusercontent.com/18356694/94509721-86bd8e00-01da-11eb-89cb-def5869878fb.png)

I can't get this to repro with the "Docked" view, but maybe it repros with another?

I'd bet that this isn't something Terminal-specific though, and is something that would repro with any WinUI MenuFlyouts. Could you check the XAML Controls Gallery app to see if that app also exhibits the same behavior?

**Comment by Pit-Storm** [comment]
@Mike Griese
Sorry I missed the additional  information.

I‘m using full screen mode of magnifier. Indeed there are simolat problems with other apps. Last time I saw it was with the right click menu of sticky notes.

I can check XAML Controls Gallery later if you still need the information from there.

**Comment by zadjii-msft** [comment]
Oh, no need to check the XAML Controls Gallery app too - if this also repros with the Sticky Notes app then this definitely isn't a Terminal-specific issue. Would you mind filing this issue upstream over at https://github.com/microsoft/microsoft-ui-xaml/? That's the repo responsible for the entire UI framework that the Terminal (and Sticky Notes) is using

**Comment by DHowett** [comment]
Thank you for filing this on the microsoft-ui-xaml repo! I'll close this one out (unfortunately) as an external duplicate.

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/1875
