### ISSUE TITLE
Sysprep fails if Microsoft Terminal ist installed.

### ISSUE THREAD

**Issue by tron03** [microsoft/terminal#7767]
Regardless if Preview or stable is installed: Syspreping a Machine with Microsoft.Terminal fails. 
Setupact.log says The App is installed for a User but not provisioned for all users. Onle Uninstall the App can Fix this.

**Comment by DHowett** [comment]
If you want to provision the application as part of a system image, you will need to use the preinstallation kit.

More information here, excerpted from the release page:

> A [preinstallation](https://docs.microsoft.com/en-us/windows/msix/desktop/deploy-preinstalled-apps) kit is available for system integrators and OEMs interested in prepackaging Windows Terminal with a Windows image. More information is available in the [DISM documentation on preinstallation](https://docs.microsoft.com/windows-hardware/manufacture/desktop/preinstall-apps-using-dism). Users who do not intend to preinstall Windows Terminal should continue using the _msixbundle_ distribution.
