### ISSUE TITLE
Default profile for powershell (on new windows terminal)

### ISSUE THREAD

**Issue by EArminjon** [microsoft/terminal#7769]
Hi,

I spent always long minutes to setup terminal for people and i didn't understand why the following profile is not the default one for every windows terminal with powershell :

`````
Import-Module PSReadLine

Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
Set-PSReadLineOption -predictionsource history
Set-PSReadLineOption -HistorySearchCursorMovesToEnd 
````

It requiert "PSReadLine 2.1.0-beta2" 
(didn't know why these features are just in beta, because they exist on every other OS since many years, but that's not the point.)

**Comment by DHowett** [comment]
Terminal cannot control the _configuration of PowerShell_. Terminal is just a pretty box that you can use to _access_ powershell. It would be very good for you to file this as a request for new defaults on the [powershell repository](https://github.com/powershell/powershell)! They would like to hear this.
