### ISSUE TITLE
New warning without warning?

### ISSUE THREAD

**Issue by CubeSyVal** [microsoft/terminal#7772]
Why does the new command prompt now say 
"Warning
You are now about to paste text that contains multiple lines. If you paste this text into your shell, it may result in the unexpected execution of commands. Do you wish to continue?"

This is not necessary and I was enjoying using this software as my primary putty replacement until this warning was put in to "help" me.
I cannot find out how to remove this warning and it was added randomly in a background update.

How do you remove this? It is really annoying because it doesn't happen just _once_, it happens every time I paste something that _dares_ to have multiple lines.

I need to be able to paste multiple lines dozens, maybe hundreds of times throughout my working day and I would appreciate being able to turn it off.

Thank you

**Comment by zadjii-msft** [comment]
If you take a look at [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#paste-warnings), you'll find the following setting will do what you want:

```jsonc
"largePasteWarning": false
```
