### ISSUE TITLE
Terminal context Environment variables

### ISSUE THREAD

**Issue by arqtiq** [microsoft/terminal#7773]
# Description of the new feature/enhancement

Numerous times I tried to automate some settings / profiles edits on the Terminal settings themselves, and I usually lack informations about the current tab environment :
- What is the current loaded profile / scheme ?
- Is the host the preview package ?

I'm sure there are also more info we could export to env vars based on people needs.
This would be veery useful to manage the terminal settings / themes / profiles directly from the command line !

# Proposed technical implementation details (optional)

When opening a new tab, set:

- $WT_CURRENT_PROFILE (*Microsoft PowerShell, CMD, ...*)
- $WT_CURRENT_SCHEME
- $WT_IS_PREVIEW (1 / 0, if the current terminal running package is the preview one)

**Comment by zadjii-msft** [comment]
This looks like it's roughly the same as the discussion that's taken place in #4566, so I'm gonna forward this discussion to that thread. Thanks!

/dup #4566
