### ISSUE TITLE
Ability to clear the terminal using keyboard shortcut

### ISSUE THREAD

**Issue by joebui** [microsoft/terminal#7775]
# Description of the new feature/enhancement

It would be great to have a feature to clean the terminal using keyword shortcut such as Ctrl + K, which is similar to Cmd + K on iTerms 2

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22cmd%2BK%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1882 for more discussion.

/dup #1882
