### ISSUE TITLE
Force splitPane to use the same shell

### ISSUE THREAD

**Issue by dabljues** [microsoft/terminal#7776]
Hi. 

So I have a few profiles defined, I mainly use Windows plain cmd and Ubuntu from WSL. Sometimes I want to split my tab using `splitPane`. Which is great, but `splitPane` defaults to the default profile. I can fix this by specifying the `profile` field in `splitPane` configuration in my `keybindings` sections, but then it's fixed for all the tabs.

What I want to achieve is: when I split the pane of plain `cmd` I want the newly created pane to be a `cmd`. But when I split the pane in Ubuntu tab I want the newly created pane to be Ubuntu.

Is there a way to configure something like that via the `settings.json`?

Thanks in advance.

**Comment by DHowett** [comment]
Yes, you can customize the `splitPane` binding to use a split type of `duplicate`. Check out the alt+shift+d binding that comes in your settings file as an example.

**Comment by dabljues** [comment]
> Yes, you can customize the `splitPane` binding to use a split type of `duplicate`. Check out the alt+shift+d binding that comes in your settings file as an example.

Don't have any examples in my `settings.json` (can I somehow check the default keybindings somewhere? - not in the docs, but like in some kind of file), but I used `splitMode` as you suggested. Thanks for a quick response, couldn't find this in docs.

**Comment by DHowett** [comment]
Ah, you must have had a settings file that originated in Terminal <0.9 :smile: Thanks for following along so long!

You can see the default settings by holding down <kbd>Alt</kbd> when you click on settings (or open settings with <kbd>Ctrl+,</kbd>)

**Comment by dabljues** [comment]
True, been here since the beta. Thanks!
