### ISSUE TITLE
Restore differential drawing to DirectWrite renderer

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#778]
For some reason, I turned this off in the haste to get things "working" well enough.

But it's definitely a performance hog. We should get differential drawing back inside the DirectWrite renderer.

Most of the provisions are already there with the invalid rectangle, we're just not using them.

I'm not sure if I'll be able to do cell-by-cell differential drawing like the GDI renderer because the more advanced glyphs/runs we support now (like ligatures) might necessitate that we instead just mark "invalid lines" and redraw the whole line. That would be mildly better than the whole screen.

This also would re-enable the use of the `Present1` call to the DX infrastructure which is more efficient at scrolling and dirty regions.

**Comment by oising** [comment]
I think line invalidation is an honorable first pass and would be welcome.

**Comment by skyline75489** [comment]
I've tried enable differential drawing on https://github.com/microsoft/terminal/commit/db797580923472c08613f054364097be06d73229 . To my surprise, it does not help much of the performance as I originally anticipated. 

First with #2959 and co the raw rendering performance is faster than before. In a way it is "fast enough" to deliquate the effect of differential drawing. Second, AFAIK most terminal operations requires entire screen redrawing, at which differential drawing makes little difference.

**Comment by miniksa** [comment]
A comparison:

Running each of these commands for ~15 seconds under WPR on the same dev box.
Cleaned up as many bg processes as possible, graphs scoped to just the `WindowsTerminalDev` package.

**Master**
- PTY - individual cells
- Term - intersecting rectangles

**DX cells**
- PTY - individual cells
- Term - individual cells

*note:* Ligatures and multi-cell glyphs don't work well with this.

**DX lines**
- PTY - individual cells
- Term - individual complete rows


## cmatrix 
### master
![image](https://user-images.githubusercontent.com/18221333/77964754-790f6600-7294-11ea-9c1d-2e6969179c3c.png)
### dx cells
![image](https://user-images.githubusercontent.com/18221333/77964629-3a79ab80-7294-11ea-8639-4ced716157a7.png)
### dx lines
![image](https://user-images.githubusercontent.com/18221333/77964984-f509ae00-7294-11ea-87c5-0a456e575453.png)

## cmatrix -u0
### master
![image](https://user-images.githubusercontent.com/18221333/77964838-a65c1400-7294-11ea-80fd-407cc24e9add.png)
### dx cells
![image](https://user-images.githubusercontent.com/18221333/77964723-64cb6900-7294-11ea-8273-c6dcd83711b6.png)
### dx lines
![image](https://user-images.githubusercontent.com/18221333/77964962-ec18dc80-7294-11ea-9c1a-d25aae94ccd5.png)


## cacafire
### master
![image](https://user-images.githubusercontent.com/18221333/77964858-b247d600-7294-11ea-9968-06fd5bd96e21.png)
### dx cells
![image](https://user-images.githubusercontent.com/18221333/77964710-5d0bc480-7294-11ea-8eb7-ed7c188915ef.png)
### dx lines
![image](https://user-images.githubusercontent.com/18221333/77964938-de635700-7294-11ea-8b1c-6cd792e6c0c2.png)


---------------

And for flavor, this is what `cacafire` graphs look like. It's kinda fun. You can see it ramping up in the amount of work required to draw the growing fire.
![image](https://user-images.githubusercontent.com/18221333/77965052-166a9a00-7295-11ea-8dcf-f83af8c13e24.png)

**Comment by miniksa** [comment]
Figuring out why `dx lines` `cacafire` is so much slower than the others
![image](https://user-images.githubusercontent.com/18221333/77965806-ab21c780-7296-11ea-9a69-76d659640845.png)
The act of setting all the bits in the rows appears to be taking a long time.

Updated trace changing `void til::bitmap::set(const til::rectangle)` to use `dynamic_bitset<>::set(pos, len)` to set the whole row at once:
![image](https://user-images.githubusercontent.com/18221333/77966723-6d25a300-7298-11ea-955a-71a19d1a9389.png)

Back to almost normal.

**Comment by miniksa** [comment]
`dxlines` `cmatrix`:
![image](https://user-images.githubusercontent.com/18221333/77967139-5a5f9e00-7299-11ea-9483-b0a46a1e9211.png)

**Comment by miniksa** [comment]
`dxlines` `cmatrix -u0`: (with fix to setting rectangles)
![image](https://user-images.githubusercontent.com/18221333/77967424-ed003d00-7299-11ea-8b1f-35b31356ab49.png)

I think that's justification for using the row/line invalidator for DX. It's better than painting the whole screen and works for ligatures. Not as fast as individual cells, but scoping it down further can be a later problem.

**Comment by miniksa** [comment]
I have to back this out for 1.0. I can't land #5345. There are too many loose ends.

**Comment by DHowett-MSFT** [comment]
Closing this one out again pending our decision on differential drawing. We think we can stick the landing for v1.

**Comment by BarrettStephen** [comment]
using the terminal is *so much faster* now. its just crazy fast. a git pull used to scroll so slowly and now its just boom done
