### ISSUE TITLE
Transparent background (not blurred)

### ISSUE THREAD

**Issue by PyICoder** [microsoft/terminal#7781]
# Description of the new feature/enhancement
A transparent background, acrylic is a blurred background not a transparent background
 it will provide users to see info they need to see behind the terminal

# Proposed technical implementation details (optional)

 Add an option for transparent background just like acrylic, just not blurred.

**Comment by zadjii-msft** [comment]
Please [search for existing duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Transparent+background%22+is%3Aclosed) before filing new issues.

/dup #603
