### ISSUE TITLE
Windows Terminal Universal is not using Build Common

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#7782]
# Steps to reproduce

Add an additional include directory in Build Common

# Expected behavior

Windows Terminal Universal uses the additional directory

# Actual behavior

Windows Terminal Universal does not use the additional directory, causing Terminal Cl checks to fail

**Comment by miniksa** [comment]
This is likely my fault. Going to assign to me. Though @DHowett could probably fix it too especially since he's been up in this project's business recently.

**Comment by DHowett** [comment]
One of us will definitely hit this.

**Comment by DHowett** [comment]
Well, we probably won't be doing this any time soon.
