### ISSUE TITLE
Add the ability to use the command line arguments when opening a profile

### ISSUE THREAD

**Issue by jmahlers** [microsoft/terminal#7785]
# Description of the new feature/enhancement

Right now, in order to have the initial launch of windows terminal look like this:
![wtscreenshot](https://user-images.githubusercontent.com/49463671/94651934-d8d7df80-02be-11eb-856b-a13f516e6df7.png)
where I have split screen at launch, first you have to pin a shortcut of windows terminal to the taskbar (Seperate issue of why does shift+rightclick perform differently for windows terminal compared to other apps). Like so:
![wtshort](https://user-images.githubusercontent.com/49463671/94652320-73d0b980-02bf-11eb-9360-8f5b56b503a1.png)
so that you can edit the target:
![wttarget](https://user-images.githubusercontent.com/49463671/94652412-9793ff80-02bf-11eb-8d14-3a709de1efbf.png)
with the target of:
```
C:\Users\Jeff\AppData\Local\Microsoft\WindowsApps\wt.exe -d C:\Starting\Dir; split-pane -p "Ubuntu-20.04"  -d C:\Starting\Dir
```
This is all overly complicated for the simple result and rather homebrew. For example, since I had to make a shortcut to the .exe to edit the target, the windows no longer nicely stack:
![image](https://user-images.githubusercontent.com/49463671/94652699-16893800-02c0-11eb-8908-6f2d5e6b373a.png)

Rather than being built in functionality, this is just what I threw together after a bunch of tinkering.

# Proposed technical implementation details (optional)
Have a setting for a profile where a user can tack on arguments to the launch of windows terminal. So that rather than doing the above, I could simply put 
```
LaunchArguments: "-d C:\Starting\Dir; split-pane -p "Ubuntu-20.04"  -d C:\Starting\Dir"
```
or any other parameters into the setting json. This would unlock a lot of functionality for customizing how profiles appear at creation.

**Comment by DHowett** [comment]
Thanks for the request! This sounds like an intersecting set with /dup #756, so I'm going to track it over there. They're pretty much the same thing, and we do have some ideas on how we'll tackle it. I don't blame you for not finding it, though. It's not particularly discoverable. :smile:
