### ISSUE TITLE
No Keyboard input and Problematic Keyboard Mapping 

### ISSUE THREAD

**Issue by HeiderJeffer** [microsoft/terminal#7786]
* BUG: User can only typing by holding (ALT) + Typing.  
* BUG: Keyboard Mapping bug: Holding Alt + Enter key = Full screen and,
* Holding Alt + F11 = no full screen, 
* Holding Alt+ All FN = 0 , the keys are not working  in the way that supposed to be. For example Holding ALT + Enter = F11 (Full Screen). Holding Enter + FN keys = Zero. 
* Let hope you fix these bugs.
* Stay safe and thank you in advanced.

**Comment by DHowett** [comment]
Do you have PowerToys installed? Any unusual keyboard layout software? _What version of Windows, and what version of Terminal?_

**Comment by HeiderJeffer** [comment]
> Do you have PowerToys installed? Any unusual keyboard layout software? _What version of Windows, and what version of Terminal?_

Yes. PowerToys installed. US layout  Microsoft. Windows 10 RPO 2004,  latest version of Terminal from Microsoft Store.
