### ISSUE TITLE
Tearing fonts and ghost letters

### ISSUE THREAD

**Issue by smerkousdavid** [microsoft/terminal#7787]
# Environment
```none
Windows build number: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version: 1.3.2651.0 (and below)
```

# Steps to reproduce
Just open the terminal, with any font, even with cleartype enabled open powershell, cmd, any terminal and look at any text

# Expected behavior
The text to be clear, especially with cleartype to have AA, and not any weird artifacts or cuts

# Actual behavior
On multiple PCs and laptops I've been experiencing this issue, including previous versions of terminal. I'm no font guru, but something is up with the font rendering, and it's really my only major gripe with the terminal is that no matter where I go I see broken fonts.

Here's an example of turning on cleartype, my custom theme was enabled and with a custom font SourceCodePro NF
Weird issues:
- vertical blue bar behind the h in PowerShell
- s seems like it's shifted at the top or has an extra a pixel on the inner crest
- powerline arrow is not straight jumps at a random point on the tip (it's not a reproducible point)
![image](https://user-images.githubusercontent.com/8923525/94712979-6dfec680-0307-11eb-8d92-6039ae44b8e8.png)

Example of everything turned off, no themes, or custom fonts
Weird issues:
- still that vertical blue bar/ghost behind the i
![image](https://user-images.githubusercontent.com/8923525/94713010-79ea8880-0307-11eb-91b1-a690e1f695f4.png)

Example of using CMD and not powershell (no custom font)
Weird issues:
- ghost letters, that r has another r shifted by a pixel or two
![image](https://user-images.githubusercontent.com/8923525/94713136-a3a3af80-0307-11eb-9e34-a6560a8e04e9.png)

Please note this isn't a duplicate of the AA issue, just the focus on tearing fonts and weird jumps in what appears to be the rendering both vertically and horizontally

**Comment by zadjii-msft** [comment]
What display scaling are you using?

**Comment by smerkousdavid** [comment]
@zadjii-msft that did the trick when I set my scaling to be 100% or 150%. I originally had it at 110% and got that issue, any non-standard scaling seems to break it

As you can see it removes the "ghost" letters
![image](https://user-images.githubusercontent.com/8923525/94720558-df437700-0311-11eb-9def-e9ca102128c9.png)

**Comment by zadjii-msft** [comment]
Thanks for following up! This is actually already tracked over in #4591

/dup #4591
