### ISSUE TITLE
Optimize the creation of the jumplist entries

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7791]
Taken from some rudimentary tracing that was done in #7774:

![](https://user-images.githubusercontent.com/5862883/94674924-d0a89000-0310-11eb-8426-b5ee20bb0436.png)

`CShellLink::SetPath` seems to be quite performance intensive for some reason. This is probably unnecessarily slowing down our startup. 

Idea: maybe we could dispatch a background thread to update the jumplist? We don't _really_ need to do that on the main thread, right?

**Comment by DHowett** [comment]
Yeah we should def dispatch this to the background with a copy of the profile list so it doesn’t get all mutated under us if there’s two quick back2back saves
