### ISSUE TITLE
Dragging a tab from Visual Studio Code onto Windows Terminal causes it to crash.

### ISSUE THREAD

**Issue by bhelyer** [microsoft/terminal#7804]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
VS Code: 1.49.2
```

# Steps to reproduce

1. Open Windows terminal (Powershell or Cmd, doesn't seem to matter)
2. Open Visual Studio Code
3. Drag the 'Welcome' tab (or any other) onto Windows Terminal 

(Note that this occured because I missed when using VS Code, not because I thought it would do something meaningful.)

# Expected behavior

Nothing, or an error to be generated. I don't rightly know what VS Code sends out when you drag a tab, I'm just expecting Windows Terminal not to crash.

# Actual behavior

Windows Terminal closes, taking all my tabs with it as punishment for my failure to accurately use a mouse.

**Comment by DHowett** [comment]
Whoa, that's _wild_. That's totally unexpected.

**Comment by DHowett** [comment]
Looks like VSCode generates a malformed clipboard/drop object; we should be more resilient.

The WinRT DataItems API is failing when we ask "give us the files you said were dropped on me" here:

https://github.com/microsoft/terminal/blob/4a114971f966be4d85113bf160a9a4603a62fc02/src/cascadia/TerminalControl/TermControl.cpp#L2850-L2853

**Comment by skyline75489** [comment]
I can easily reproduce this. And it is easy to fix the crash by simply catching it. But I kinda want it to *work* and haven't figured out a way to do so.

For reference, both Edge and Firefox handles the tab dropping from VSCode as a file URI (file://something). Surprisely `explorer.exe` handles it as an *actual* file and will paste it to the current directory.

A side note: Should we also support `ApplicationLInk` and `WebLink`? Then you can drag and drop an URL from browser and it will be pasted into the terminal. I've tested it and it works pretty well.
