### ISSUE TITLE
Allow custom dynamic profile generator sources

### ISSUE THREAD

**Issue by jnovick** [microsoft/terminal#7805]
# Description of the new feature/enhancement

A plug and play approach to dynamic profiles. This would allow people who want profiles generated dynamically to easily do so. Instead of Windows Terminal having to support lots of dynamic profile generators that different users suggest with lots of configuration options, users could create them themselves and possibly share via git. I tried searching to see if this was already suggested and was surprised it wasn't. If an issue already does exist and I just missed it then I apologize. Currently, there isn't even a way to easily script editing the settings file. Here are a few use cases:

## Docker

One example use case is if someone wanted a dynamic profile for all docker containers that are currently running or maybe all containers regardless of whether they are running or not. This would address https://github.com/microsoft/terminal/issues/4892 without locking in everyone to the same command. Some people may want volumes to be included while others may want to exec into the container without modifying it at all. Some may want to pass in specific environment variables or something. Point is, it would be customizable.

## Customizing WSL profiles

Instead of the built in `Windows.Terminal.Wsl` generator, someone may want to allow specifying a different shell (commandline) or to pass in extra flags, etc. This would also address https://github.com/microsoft/terminal/issues/5571 which does mention dynamic profiles as plugins.

## SSH

If a user wants to dynamically generate profiles that directly ssh into other machines based off `~/.ssh/known_hosts`. CUrrently, these can easily be added manually and look something like this:

``` json
{
    "guid": "{1190852f-d156-4583-853f-1f57e20eb4b5}",
    "hidden": false,
    "name": "ssh my-host.something.com",
    "commandline": "ssh my-user@my-host.something.com"
 }
```

Or if someone prefers to use ssh from WSL2 distro instead of openssh (Not sure if there is any advantage),

``` json
{
    "guid": "{1190852f-d156-4583-853f-1f57e20eb4b5}",
    "hidden": false,
    "name": "ssh my-host.something.com",
    "commandline": "wsl -d Ubuntu-20.04 ssh my-user@my-host.something.com"
 }
```

# Proposed technical implementation details (optional)

My suggestion would be to add another top-level section that is an array of objects containing the source name and a script for generating profiles. Maybe this script is required to be a powershell or bash script with functions that match specific names. Maybe this script is allowed to be any language as long as it is executable. Perhaps it is required to be written in c and adhere to the `IDynamicProfileGenerator.h` that already exists. I am not sure whether it would be better for the script plugin to output json array that gets merged into the list of profiles automatically or whether it should just output list of names and guids and then have a second call based on `source` that actually determines what should happen for that profile which is what the existing dynamic profiles do. For example

``` jsonc
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
    "customProfileSources":
    [
        {
            "name": "Docker",
            "script": "C:\\Path\\To\\Script"
        }
    ],
    "profiles":
    {
        "list":
        [
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{d77a2c51-7ad9-4bc5-995e-ac634f732a5b}",
                "hidden": false,
                "name": "container_name_or_id",
                "source": "Docker"
            }
        ]
    },
    "schemes": [],
    "actions": []
    // Other stuff...
}

```

**Comment by WSLUser** [comment]
/dup https://github.com/microsoft/terminal/issues/4000 FWIW, this is actually in discussion now for https://github.com/microsoft/terminal/pull/7774 to possibly serve as a test case.

**Comment by zadjii-msft** [comment]
Hey thanks for the great writeup! We're actually working on something just like this over in #7584/#7632. We're going for more of an approach of "tools can generate profiles for the Terminal, and leave them somewhere the Terminal will know to look for them". The more elaborate case, where the Terminal runs the 3rd party generator at launch, is largely being tracked by #4000.

I'm gonna close this in favor of those threads, but feel free to hop on the discussion!

/dup #7584 #7632

**Comment by jnovick** [comment]
Thank you for the response. I look forward to being able to utilize those features.
