### ISSUE TITLE
Can't start Terminal with admin privileges

### ISSUE THREAD

**Issue by TheChilliPL** [microsoft/terminal#7806]
# Environment

```none
Windows build number: Windows 10 v 2004 build 19041.508
Windows Terminal version (if applicable): preview 1.4.2652.0
```

# Steps to reproduce

Right click on any Windows Terminal icon and select `Run as Administrator`.

# Expected behavior

Windows Terminal should open normally, with administrator privileges.

# Actual behavior

After asking for admin password 2 times, it doesn't start and throws an error instead:
![image](https://user-images.githubusercontent.com/18823939/94899985-8a7c3980-0494-11eb-8a4c-3144a8ca3bbf.png)

**Comment by conioh** [comment]
Are you trying to elevate the same user or are you trying to "Run as Administrator" as another user?

**Comment by TheChilliPL** [comment]
I'm clicking `Run as Administrator` in the context menu of the exe, but I'm not logged in as one, so I'm prompted to type in the password of another administrative user.

**Comment by zadjii-msft** [comment]
Unfortunately, this scenario doesn't work quite right today. IIRC you need to have the Terminal installed for the admin user as well. There are more details in #4217, which is tracking this issue with the platform team as well. Thanks!

/dup #4217

**Comment by conioh** [comment]
> I'm clicking `Run as Administrator` in the context menu of the exe, but I'm not logged in as one, so I'm prompted to type in the password of another administrative user.

As @zadjii-msft said you need to have WT installed for the other user too, but from what I recall you also need to have WT in both users _at the same version_. If you've updates it through the store in your non-admin user but haven't updated it in your admin user, you'd get this error.
