### ISSUE TITLE
New tab cluster/titlebar have <1px region of color mismatch on high-DPI displays

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#7807]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.4.2652.0 (Preview)
```
The line between the title bar and the actual shell(?) is of a different color from where the tab is attached.
(Again, I don't know how to explain it better, so please look at the screenshot)
![bug](https://user-images.githubusercontent.com/71010204/94908534-6f72ef00-04bf-11eb-89de-950c3f23179f.png)

**Comment by jdebp** [comment]
The bottom border of the X and V menus, adjoining the client area, is a different colour to the bottom borders of the tab(s) and the rest of the titlebar.  This may be intentional, note, to give the tabs and the menus their Z order appearance.

**Comment by DHowett** [comment]
Good eye! This actually isn't on purpose. :smile:

**Comment by DHowett** [comment]
I took a crack at titling it. Thanks for the extra pair of eyes, @jdebp!

**Comment by zadjii-msft** [comment]
Yeah I bet the tabviewitem is casting a shadow on the rest of the tab view, but the tabview only extends to the end of the new tab button, not the end of the row

**Comment by zadjii-msft** [comment]
Looking at this again with magnifier, it looks like this might have just been fixed for us by a MUX update in the past.
