### ISSUE TITLE
Acrylic not working when terminal window is inactive / unfocused 

### ISSUE THREAD

**Issue by UID1** [microsoft/terminal#7808]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.4.2652.0

Any other software?
```

# Steps to reproduce
Configure Windows terminal to enable useAcrylic, e.g.:

      "defaults": {
        // Put settings here that you want to apply to all profiles.
        "useAcrylic": true,
        "acrylicOpacity": 0.7
      },
as  settings and launch it. Then inactivate window.

# Expected behavior

Acrylic to still be there on an inactive window.

# Actual behavior
The window turns into a black opaque  background.

Perhaps adding options on how windows should behave when becoming inactive/unfocused in the configuration may address this issue. Perhaps some users may want the acrylic may want the acrylic material to change to a darker tint when inactivated. Perhaps adding options for configuring the blending color and degree of blur / blur radius could be added although it is beyond the scope of this bug report.

**Comment by KalleOlaviNiemitalo** [comment]
Acrylic in inactive windows was previously discussed in <https://github.com/microsoft/terminal/issues/7158>.

**Comment by DHowett** [comment]
Indeed. This is by design and automatically handled by the platform. Acrylic is only applied to active windows.
