### ISSUE TITLE
Possibility to set font background color

### ISSUE THREAD

**Issue by kabukimurder** [microsoft/terminal#7809]
The customization lacks possibility to change font background color. When using custom image backgrounds it's often crucial to make your text visible no matter how the background looks. Just changing font color with "foreground" is often not enough to make the text visible and the current "background"-setting is actually a "windowBackground"-property. You should be able to change the font background color to not get your text lost in the colors from your mondo cool background gifs. 

Renaming of "foreground" to "fontForeground" and "background" to "windowBackground" and implementation of a correct font foreground setting.

**Comment by DHowett** [comment]
Sorry -- the actual text colors, both background and foreground, are inevitably controlled by the connected client application.

Is there a specific issue you're seeing? It might help to have illustrative examples.

**Comment by LuanVSO** [comment]
I think he is asking for a text outline color setting

**Comment by kabukimurder** [comment]
I'm looking for the equivalent of System.Console.BackgroundColor in C#.

**Comment by zadjii-msft** [comment]
@kabukimurder You should still be able to use that API in the Terminal - could you elaborate more on exactly how that _isn't_ working in the Terminal?

**Comment by hc970** [comment]
I agree with this feature request. It would be great to just add a property to the settings.json such as:

fontColor: “#[colorValueInHex]

I have a light colored gif as the background and have experimented with changing the color scheme to make the text visible. I was only partially successful (the color scheme changes but the text is still to light). A new configuration such as that above would be a simpler solution.

Thanks.

**Comment by DHowett** [comment]
_it is already possible to set the font color; please read our docs_

**Comment by LuanVSO** [comment]
yeah, every profile has a  `"foreground" :"#xxxxxx" ` which is exactly that.
furthermore, you can override select colors from a color scheme by:
1. adding a scheme with the same name on your user settings file.
2. provide only the colors that you want changed.
3. setting the profile's ` "colorScheme": ""` setting accordingly.

**Comment by hc970** [comment]
> _it is already possible to set the font color; please read our docs_



> yeah, every profile has a `"foreground" :"#xxxxxx" ` which is exactly that.
> furthermore, you can override select colors from a default color scheme by:
> 
> 1. adding a scheme with the same name on your user settings file.
> 2. provide only the colors that you want changed.
> 3. set the profile's ` "colorScheme": ""` setting accordingly.

Excellent; many thanks to you both for this information. I didn't create this ticket but I believe it can be closed.

**Comment by zadjii-msft** [comment]
That's just the thing though - the `System.Console.BackgroundColor` API should work exactly the same in the Terminal as it does in the vintage console window. If that's not the case for your application, could you provide a minimal repro of the issue you're seeing?
