### ISSUE TITLE
Glow text exploration

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#781]
OK. The glow text example I gave that's currently inside the code (but unused) isn't great.

I've received feedback from @MilesMSCohen that it has a fundamental flaw:
- It loses all font hinting which makes it hard to read, especially at small sizes.

Ouch. I want hinting. The recommended alternative is to render the text to a command list and use the command list as input to an effect that can cause a glow.

@DHowett-MSFT already had a sample lump of code to do something like this that he was playing around with a few weeks ago because glow text is cool. It's around here somewhere.

Also, I got the warning from @MilesMSCohen that this might have worse performance, but we'd have to decide if that's worth it.

**Comment by miniksa** [comment]
This may be a duplicate of #621. I'm just putting all my internal notes/bugs into GitHub.

**Comment by MilesMSCohen** [comment]
Cool, let me know how it turns out.

-Miles

**Comment by weswigham** [comment]
I'd love for the ability to declare glow parameters for text of specific colors (rather than for all text or none), mostly just to complete a synthwave terminal theme.

**Comment by WSLUser** [comment]
https://github.com/microsoft/terminal/pull/3468 added glow effects. Not sure if your original code was replaced in the process (but most likely). But this issue may be fixed already.

**Comment by zadjii-msft** [comment]
You know, with custom shaders (#7013), I don't think we really need to re-explore this. Let's just let folks do their own shader thing, that's been pretty dang flexible so far.
