### ISSUE TITLE
Background not consistently drawn correctly while in VIM via OpenSSH 8.1

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7811]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 18363 or 19041
Windows Terminal version (if applicable): 1.4 Preview

Any other software? Win32-OpenSSH 8.1, Vim on F31
```

# Steps to reproduce

Ssh into F31 host. Create a file or edit an existing file with VIM (doesn't matter which display mode you're in when doing this.)
# Expected behavior

Consistent UI background
# Actual behavior

A lovely white strip in the background. 
![Vim_screen-issue](https://user-images.githubusercontent.com/33032910/94941939-245bda80-04c5-11eb-9bbc-afa61d994242.png)

Pretty sure this a dupe of an issue I've seen before but couldn't find it so assuming it's closed (though couldn't find it there either).

**Comment by DHowett** [comment]
That looks almost exactly like what you get with `:set colorcolumn=`... It uses a color strip to highlight the indicated column so you know when you're writing lines that are too long.

Can you check if it's set?

**Comment by WSLUser** [comment]
Yep in .vimrc, I have
`set colorcolumn=116        " highlight the column that is too long`

This is part of a generic vimrc that everyone has. If that's what that is, then I can close this.

**Comment by WSLUser** [comment]
That's actually pretty awesome Terminal can detect the vimrc settings over ssh.

**Comment by DHowett** [comment]
Vim reads the settings file and produces a stream of output for ssh to send to terminal. :smile:
