### ISSUE TITLE
Add settings for default window size, font size, font

### ISSUE THREAD

**Issue by alxwndr** [microsoft/terminal#7813]
# Description of the new feature/enhancement
It would be great to add settings controlling window and font size when you launch terminal. Default size is too big.

![image](https://user-images.githubusercontent.com/10734450/94968355-69096500-0509-11eb-923e-3e1bdf478107.png)

**Comment by DHowett** [comment]
These can all be customized today.

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#columns-on-first-launch
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#rows-on-first-launch
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#font-face
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#font-size
