### ISSUE TITLE
New tab defaults to first item in list

### ISSUE THREAD

**Issue by clarke94** [microsoft/terminal#7814]
# Environment

```none
Windows build number: OS Build 19041.508
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

Add `newTab` command

```
{ "command": { "action": "newTab", "index": 0 }, "keys": "ctrl+T" }
```

Set default shell to anything other than the first in the array

```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{ubuntu-guid}",
    "copyOnSelect": false,
    "copyFormatting": false,

    "profiles": {
        "defaults": {},
        "list": [
            {
                "guid": "{powershell-guid}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                "guid": "{ubuntu-guid}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
            },
        ]
    },
    // ...
}
```

Create new tab with command

```
ctrl+T
```

# Expected behavior

Expect it to take the default shell

# Actual behavior

It takes the first in the list, in this case `Windows PowerShell`. It's not really an issue that would block anyone as you simply move the default object to the first item in the list, its just unexpected.

**Comment by DHowett** [comment]
```
{ "command": { "action": "newTab", "index": 0 }, "keys": "ctrl+T" }
                                   ^^^^^^^^^^
                                   this part means "first profile in the list"
```

**Comment by clarke94** [comment]
> ```
> { "command": { "action": "newTab", "index": 0 }, "keys": "ctrl+T" }
>                                    ^^^^^^^^^^
>                                    this part means "first profile in the list"
> ```

Stupid moment... thanks, without thought I figured that was tab index, not array index

**Comment by DHowett** [comment]
Hopefully #1564 goes some way towards helping! :smile:
