### ISSUE TITLE
Caption drag

### ISSUE THREAD

**Issue by spargo-protek** [microsoft/terminal#7815]
Just drag some tab 10 times and you get:

![image](https://user-images.githubusercontent.com/55238788/94977403-3ff4ce80-0521-11eb-9fc9-a625312748aa.png)

**Comment by zadjii-msft** [comment]
@spargo-protek does this repro with the TabView in the "XAML Controls Gallery" app?

**Comment by spargo-protek** [comment]
No, subsequent drags do not lead to this bug in XAML Controls Gallery.

**Comment by DHowett** [comment]
I can't reproduce this, no matter how much I try. Is the issue just that it gets stuck in drag mode?
