### ISSUE TITLE
How to turn off / disable the FPS overlay?

### ISSUE THREAD

**Issue by Qix-** [microsoft/terminal#7816]
```
Windows build number: [Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): 1.3.2651.0
```

This may be another application doing this, but the only place I ever see it is the Windows Terminal. If it is the case it's another program, feel free to close.

Is there a way to disable this? It pops up randomly, I have absolutely no idea what causes it to appear and there doesn't seem to be any UI option to disable or remove it.

![image](https://user-images.githubusercontent.com/885648/94983162-552d2580-0540-11eb-8770-5d67316a2dca.png)

It's completely useless to me and I'd rather just never see it again.

Sometimes it decides to disappear later on, and leaves graphical artifacts as well:

![image](https://user-images.githubusercontent.com/885648/94983202-c5d44200-0540-11eb-826f-88d3ecf04bb9.png)

Quite annoying. Again, it could be another application on my machine doing this, but I've never seen it anywhere other than the terminal app.

**Comment by DHowett** [comment]
This overlay is from your graphics card’s support software, because it thinks Terminal is a game. We have not implemented an FPS meter.

**Comment by JesseMaurais** [comment]
For anyone else who has experience this (and because this page is the top Google result): I found that it was coming from NZXT CAM software and can be disabled from the settings > overlay menu. The overlay is triggered by certain key combinations, in my case CTRL+O which I was using in GNU Nano to write 'out' to a file.

**Comment by Qix-** [comment]
Yes, sorry - I never updated. You're absolutely right, it's coming from the NZXT CAM software. I never figured out the combo that was causing it to come up, so thanks @JesseMaurais.

**Comment by SebasTheCreator** [comment]
Thank you @JesseMaurais that was definitely causing this problem in my Terminal.
