### ISSUE TITLE
error 0x80070002 when launching most commands against WSL2

### ISSUE THREAD

**Issue by FredyC** [microsoft/terminal#7817]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
PowerShell: 7.0.1
```

# Steps to reproduce

Running `wt top` within Powershell while having WSL `Ubuntu-20.04` as the default profile.
Specifying `-p "Ubuntu-20.04` yields the same result.
Tried several other commands that work when executed manually from bash.

# Expected behavior

I want to run `wt yarn` (among other commands in split panes) to set up my environment for development easily.

# Actual behavior

The new terminal opens with the correct profile and only shows the error

![image](https://user-images.githubusercontent.com/1096340/94985523-d93ed780-0557-11eb-8557-c31f6378a927.png)
![image](https://user-images.githubusercontent.com/1096340/94985792-dba23100-0559-11eb-9cac-c83d7200bbcc.png)
![image](https://user-images.githubusercontent.com/1096340/94985665-d55f8500-0558-11eb-9cd1-fe4a01caa423.png)

I have a feeling that WT is trying to run these commands too soon before WSL is properly initialized.

**Comment by zadjii-msft** [comment]
Yea, that's not exactly how the `commandline` parameter to `wt` works. When you pass in `foo` as the commandline, it doesn't _append_ it to the profile's commandline, it _overrides_ the commandline of the profile. So in your examples, above, the Terminal is literally looking for `top.exe`, `pwd.exe`, `yarn.exe`, when what you really want is `wsl -d Ubuntu-20.04 top`.

"Add support for appending a commandline to a profile's commandline" is being tracked over in /dup #5528

**Comment by FredyC** [comment]
Wait, how is `wsl` going to help me here? I mean sure it will run `top` inside Powershell, but that's not what I am looking for. I want to set up a one-liner that would line launch a new WT window with several split panes and run some command in each.

I guess I will follow #5528 as that indeed seems the same problem I am facing. Thanks!

**Comment by zadjii-msft** [comment]
When you're running a WSL profile, the commandline is _technically_ `wsl.exe -d <the distro's name>`. So the commandline for the Ubuntu-20.04 profile is `wsl.exe -d Ubuntu-20.04`. So you definitely could get what you're looking for with the wt parameters, it'll just be V E R B O S E

```
wt wsl -d Ubuntu-20.04 top ; sp wsl -d Ubuntu-20.04 yarn ; wsl -d Ubuntu-20.04 pwd
```

(using `sp` as the short form of `split-pane`, introduced in #6576)
