### ISSUE TITLE
Open a new tab when I run wt

### ISSUE THREAD

**Issue by alannt777** [microsoft/terminal#7818]
# Description of the new feature/enhancement
Currently when I type `wt` into PowerShell (In Windows Terminal), It opens a new window. I would like it open a new tab

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #4472 for more discussion.

/dup #4472
