### ISSUE TITLE
OSC52 does not handle UTF-8 correctly ("copying content using tmux copy mode doesn't paste properly")

### ISSUE THREAD

**Issue by AndysonDK** [microsoft/terminal#7819]
# Environment

Windows build number: `Microsoft Windows [Version 10.0.19041.508]`
Windows Terminal version: 1.3.2651.0

Other software:

Tmux version: `tmux 3.0a`
Running Ubuntu 20.04.1 LTS inside of WSL2

# Steps to reproduce

All the steps to reproduce this issue are stated in this [issue](https://github.com/tmux/tmux/issues/2407) that I created.
Please read that issue as it contains some more information about my environment and some relevant comments.

It seems like this issue doesn't relate to a problem with tmux but rather a problem with the Windows Terminal or the windows clipboard.

# Expected behavior
When I copy content using tmux copy mode I would like to have the ability to paste it outside of tmux containing the exact same characters which can be seen here in a browser search bar:
![image](https://user-images.githubusercontent.com/28491857/94988784-14e59b80-0570-11eb-98d6-faba599bc93f.png)

# Actual behavior
The content is not pasted properly as [this character](https://www.fileformat.info/info/unicode/char/2019/index.htm) shows up as cryptic characters:
![image](https://user-images.githubusercontent.com/28491857/94988868-b1a83900-0570-11eb-9fd9-0704382046a7.png)

**Comment by DHowett** [comment]
/cc @uzxmx 
It looks like `s_Decode` in base64 is transforming the raw bytes that come out of the base64 encoded clipboard data _directly into UCS-2 codepoints_ instead of running them through UTF-8->UTF-16 conversion.

**Comment by PetterS** [comment]
In the meantime, you can execute `tmux show-buffer | clip.exe` which will put the correct string on the Windows clipboard.
