### ISSUE TITLE
CustomTextLayout/CustomTextRenderer performance tweaks

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#782]
I cribbed most of the `CustomTextLayout` and `CustomTextRenderer` code from samples. One of these samples was written by @fwdr in the first place. He dropped by on email and said that there are a lot of things that could be done in this space to optimize the performance and workload for the Terminal specifically.

So this represents his e-mail based commitment to come back around to this and show us the right way to do it.

**Comment by zadjii-msft** [comment]
We're pretty sure we did this with a series of enhancements to the Dx Engine over the course of 2020 & 2021. Also, the new atlas renderer seems like it totally obsoletes the need for this one 😄
