### ISSUE TITLE
Add switch-to-next/prev-tab commands to switch tabs fast without cycling

### ISSUE THREAD

**Issue by marektoman** [microsoft/terminal#7821]
# Description of the new feature/enhancement

The recent feature that shows a tab cycler when switching tabs (`ctrl+tab`) is slow. Typically, apps have a direct way to go to the next tab.

# Proposed technical implementation details (optional)
Add new commands: `switchToNextTab`, `switchToPrevTab`. Invoking each will result in a direct switch without showing the tab cycler. The default keybinding can be `ctrl+pgdn` and `ctrl+pgup`, which is standard for such behavior in other console etc. apps.

The commands must be bindable to `ctrl+tab` and `ctrl+shift+tab` as well so the user can bring back the old behavior as default because it is faster.

**Comment by DHowett** [comment]
You can disable the new tab switching experience by setting, globally, `useTabSwitcher: false`. We did not want to introduce two new bindings because that makes it onerous to switch from one to the other.

**Comment by aaron-613** [comment]
Glad I found this... the tab switcher showing me a list of 6 identically named tabs was not useful at all.  Wondering why `useTabSwitcher` is not `false` by default, retaining the original behaviour..?  Thanks.
