### ISSUE TITLE
Keyboard does not work

### ISSUE THREAD

**Issue by DeveloperNfk** [microsoft/terminal#7823]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
@DeveloperNfk By any chance, have you disabled the "Touch keyboard and handwriting service"? See #4448

**Comment by benfavre** [comment]
Have had this issue for a while ... what's the point of this repo/project if you don't test keyboard support ?

**Comment by DHowett** [comment]
@benfavre instead of reading the linked issue or applying critical thinking about the question earlier in the thread, you’ve decided that for the entire _year or more_ that terminal has existed nobody has tested KEYBOARD SUPPORT? Come now.
