### ISSUE TITLE
Split pane extends underlining

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7824]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1082 (1909)
WindowsTerminalPreview_1.4.2652.0_x64
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

In the shell of your choice, use ESC[4m to echo something underlined; be sure to terminate with ESC[0m.  Use Alt+Shift+Plus to get a vertically split pane [note extended underlining].  Close the new pane [note underlining extended further].

# Expected behavior

Underlining remains unchanged.

# Actual behavior
See above and below.

Having managed to set the environment variable "esc" in cmd ...

![image](https://user-images.githubusercontent.com/61856645/95020851-ac63f080-063b-11eb-87dd-29c200a52a4a.png)

Now I'll split vertically.

![image](https://user-images.githubusercontent.com/61856645/95020879-c9002880-063b-11eb-8a8d-f915599e8902.png)

Now I'll close the new pane.

![image](https://user-images.githubusercontent.com/61856645/95020898-df0de900-063b-11eb-8171-824acdca1f44.png)

**Comment by vefatica** [comment]
Ubuntu/bash is probably easier.  Start here:

![image](https://user-images.githubusercontent.com/61856645/95021870-b12ba300-0641-11eb-89dc-58deeb9790d5.png)

**Comment by DHowett** [comment]
/dup #32 (it’s the same issue: hyperlink is a text attribute, and color is just a really visible one)

**Comment by vefatica** [comment]
That's pretty old ... hard to fix or just low priority?

**Comment by DHowett** [comment]
Both.

**Comment by vefatica** [comment]
Switching to/from full-screen does it too.  This post is over a year old, #32 over **four** years old.

**Comment by DHowett** [comment]
Yeah? It's both hard to fix and low-priority. Our text buffer isn't equipped to handle performant right-side measurement today.

**Comment by vefatica** [comment]
It affects colors too as you probably know.  I can imagine that it's hard to fix; probably will require a very fundamental change.  But I don't get the low priority.  It seems a show-stopper as far being as ready-for-prime-time is concerned.  And doesn't it get harder to fix the longer it goes unfixed?  

Underlining is an attribute (COMMON_LVB_UNDERSCORE) ... yes/no?  Isn't it stored?  Or is nothing at all stored after the last character?

Is there any plan at all?

**Comment by zadjii-msft** [comment]
I mean, this has been a bug in the Console since the days immemorial. It wasn't a show stopper 1989 so it's still not a show stopper now 😅 

Underlining, colors, italics, _any_ attribute of the text is stored in a `TextAttribute`, and those are stored in a `TextAttributeRun`, and the last one of those just gets resized to the width of the window on a resize, rather than filling in a placeholder "use the default attributes" `TextAttributeRun`. 

Our "plan" to deal with that is largely in #8000

**Comment by vefatica** [comment]
I have a kludgy workaround, at lease for the visual part of it.  After turning off underlining (at the end of a line) I write a nbsp (0xA0).  I imagine that would also work for other attributes.  Why doesn't writing a real space (0x20) work ... are trailing spaces not saved?
