### ISSUE TITLE
focusMode option for launchMode setting

### ISSUE THREAD

**Issue by Memphizzz** [microsoft/terminal#7825]
# Description of the new feature/enhancement
Besides having maximized and fullscreen, would it be possible to please also have the option to start the terminal in FocusMode?

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Yes yes yes. I could have swore I already filed this one - this is something I've been wanting to do. Thanks!

**Comment by Don-Vito** [comment]
Duplicate of https://github.com/microsoft/terminal/issues/7124
