### ISSUE TITLE
Hi Unable to integrate the Google Cloud SDK from the terminal

### ISSUE THREAD

**Issue by cmanduva** [microsoft/terminal#7828]
Hi Team,

I am facing issue while integrating the Google Cloud SDK cmd.exe to the terminal window. 

This is my path, which has a shortcut has been created. 

C:\windows\system32\cmd.exe /k ""C:\Program Files (x86)\Google\Cloud SDK\cloud_env.bat""

Please suggest to me, how to specify the path in our settings code. Here is my block which I have updated.
             {
                "guid": "{e0f44572-3d2d-4927-8c5a-9b486928aaaa}",
                "name": "Google Cloud Shell",
                "commandline": "C:\\Program Files (x86)\\Google\\Cloud SDK\\cloud_env.bat",
                "icon": "C:\\Program Files (x86)\\Google\\Cloud SDK\\cloud_platform_logo.ico",
                "hidden": false
            },

**Comment by zadjii-msft** [comment]
Try

```json
{
  "guid": "{e0f44572-3d2d-4927-8c5a-9b486928aaaa}",
  "name": "Google Cloud Shell",
  "commandline": "cmd.exe /k C:\Program Files (x86)\Google\Cloud SDK\cloud_env.bat",
  "icon": "C:\Program Files (x86)\Google\Cloud SDK\cloud_platform_logo.ico",
  "hidden": false
},
```

**Comment by cmanduva** [comment]
No Luck, Still am facing the issue. It is not loading the binaries, when we
tried to get that command it is not working. Thanks for your help in this
regard.

I tried this one as below, please suggest me if  anything has to be done
here.

             {
                "guid": "{e0f44572-3d2d-4927-8c5a-9b486928aaaa}",
                "name": "Google Cloud Shell",
                "commandline": "cmd.exe /k C:\\Program Files (x86)\\Google\\
Cloud SDK\\cloud_env.bat",
                "icon": "C:\\Program Files (x86)\\Google\\Cloud SDK\\
cloud_platform_logo.ico",
                "hidden": false
            },

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\windows\system32>gcloud
'gcloud' is not recognized as an internal or external command,
operable program or batch file.

C:\windows\system32>gcloud init
'gcloud' is not recognized as an internal or external command,
operable program or batch file.

Thanks & Regards
Chaitanya Manduva | Mobile:+91-9666826999 | E: chaitanya.manduva@gmail.com

**Comment by zadjii-msft** [comment]
Oh derp, you'll also need to wrap the path in quotes:

```json
{
  "guid": "{e0f44572-3d2d-4927-8c5a-9b486928aaaa}",
  "name": "Google Cloud Shell",
  "commandline": "cmd.exe /k \"C:\\Program Files (x86)\\Google\\Cloud SDK\\cloud_env.bat\"",
  "icon": "C:\\Program Files (x86)\\Google\\Cloud SDK\\cloud_platform_logo.ico",
  "hidden": false
},
```

**Comment by cmanduva** [comment]
Sorry, I didn't get you, could you please send me the example code how you
would like to have that.
Thanks & Regards
Chaitanya Manduva | Mobile:+91-9666826999 | E: chaitanya.manduva@gmail.com

**Comment by zadjii-msft** [comment]
I literally put the code in the comment....

![image](https://user-images.githubusercontent.com/18356694/95348349-90529000-0883-11eb-8c1d-15841fb0e544.png)

**Comment by cmanduva** [comment]
Thank you very much, it helped a lot.


Thanks & Regards
Chaitanya Manduva | Mobile:+91-9666826999 | E: chaitanya.manduva@gmail.com

**Comment by cmanduva** [comment]
Thanks a lot for your help.
