### ISSUE TITLE
Allow instantaneous tab switching again

### ISSUE THREAD

**Issue by sboukortt** [microsoft/terminal#7832]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.508]
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Bind a shortcut to action “`prevTab`” or “`nextTab`”. (In my case, the shortcuts are “shift+left” and “shift+right” respectively.)

2. With several tabs open, execute the shortcut.

# Expected behavior

The tab switches as soon as the key (“left” or “right” for me) is pressed down, as used to be the case from what I remember.

# Actual behavior

The tab doesn’t change until the modifier key (e.g. “shift”) of the shortcut is released. Instead, while it is held, a menu like this is presented, and left/right in my example only change the selection in the menu:

![tab-switching](https://user-images.githubusercontent.com/16757512/95133185-32c62280-0761-11eb-827f-7eae22b06086.png)

Presumably, the change is intentional, so maybe some people like it more, but I really don’t (I can’t quickly glance at the tabs’ contents as I go through them) and I would really like if the old behavior were at least be accessible via a global setting.

Thanks.

**Comment by jack775544** [comment]
Set `"useTabSwitcher": false` in your profile and you will get the old behaviour.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7409 for more discussion.

/dup #7409

**Comment by sboukortt** [comment]
> Set `"useTabSwitcher": false` in your profile and you will get the old behaviour.

Oh, I was redirected to the [`fr-ch`](https://docs.microsoft.com/fr-ch/windows/terminal/customize-settings/global-settings) version of the documentation on global settings and not the `en-us` one, and so I didn’t see that option (the translation doesn’t list it). Thanks for pointing it out.
