### ISSUE TITLE
App crashed not long after receiving focus

### ISSUE THREAD

**Issue by lpd-au** [microsoft/terminal#7837]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Feedback Hub Link

https://aka.ms/AA9vg1i

# Steps to reproduce

At the time I had 3 tabs open, 2 Debian WSL1 and 1 Cygwin. The active tab was Debian running a ssh client. I had just foregrounded/focused the app from a background/minimised state.

# Expected behavior

Doesn't crash.

# Actual behavior

Windows Terminal silently crashed at 6/Oct/2020 8:48:48 PM UTC+11, with no hang/freeze or report error dialog.

```
Faulting application name: WindowsTerminal.exe, version: 1.3.2009.21001, time stamp: 0x5f693325
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff8d2e40000
Faulting process ID: 0x3e80
Faulting application start time: 0x01d69bac6a0546c0
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: unknown
Report ID: 0e2ccb02-9214-4871-ac4c-b7b3c74790b1
Faulting package full name: Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett** [comment]
_Interesting_.. the report indicates that code from outside our package was running.

Do you happen to have _RivaTuner_ installed?

**Comment by lpd-au** [comment]
@DHowett Yes I do; I didn't have any exclusions set for it although it wasn't actually displaying anything in the window. I added one now to be sure. Thanks!

**Comment by DHowett** [comment]
Thanks! I'll close this out for now, but please do let us know if it happens with Terminal excluded from RivaTuner!
