### ISSUE TITLE
Powershell Write-Progress flicker when text scrolls underneath

### ISSUE THREAD

**Issue by jgardsentry** [microsoft/terminal#7838]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): 1.3.200921001-release1.3

Any other software? Powershell 5.1, pwsh 7.0.3, and cmd.exe loading pwsh 7.0.3.
```

# Steps to reproduce
Powershell:
```powershell
1..50|%{Write-Progress "Looping"; $_; start-sleep -Milliseconds 50}
```

# Expected behavior
Powershell's Write-Progress bar remains solid above the top few lines of output.  From Windows Powershell natively:
![PowershellNoFlicker](https://user-images.githubusercontent.com/47949180/95221829-79496a80-07bd-11eb-83e8-674889ac0bc1.gif)

# Actual behavior
The progress bar flickers while output scrolls underneath it.
![TerminalFlicker](https://user-images.githubusercontent.com/47949180/95221012-a47f8a00-07bc-11eb-9cb2-978262356d4a.gif)

**Comment by LuanVSO** [comment]
PowerShell 7 flickers on conhost too

**Comment by DHowett** [comment]
Yes, this happens without Terminal as well. PowerShell (dubiously) backs up and redraws the content of the screen when displaying progress.

This looks like it's tracked in /dup https://github.com/PowerShell/PowerShell/issues/3366
