### ISSUE TITLE
tabTitle to be preserved after connecting to SSH

### ISSUE THREAD

**Issue by GentelmanBastard** [microsoft/terminal#7844]
As per title, I have some of the profiles configured to facilitate SSH connections, however after inputting password the TabTitle changes to the user@host. Is it possible to preserve tabTitle after connecting?

**Comment by zadjii-msft** [comment]
Sure is! Check out [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#suppress-title-changes-from-the-shell):


> ### Suppress title changes from the shell
> 
> When this is set to `true`, `tabTitle` overrides the default title of the tab and any title change messages from the application will be suppressed. If `tabTitle` isn't set, `name` will be used instead. When this is set to `false`, `tabTitle` behaves as normal.
> 
> **Property name:** `suppressApplicationTitle`
> 
> **Necessity:** Optional
> 
> **Accepts:** `true`, `false`
