### ISSUE TITLE
User-supplied GSSAPI library path

### ISSUE THREAD

**Issue by davidebenato** [microsoft/terminal#7845]
# Description of the new feature/enhancement
In the corporate environment where I work, we use MIT Kerberos to get tickets. 
At the moment I'm using Putty to ssh into different servers, and I added a User-supplied GSSAPI library path, pointing to the MIT Kerberos gssapi64.dll.
In Putty this can be done in Connection/SSH/AUTH/GSSAPI

I would like to migrate to Windows Terminal but I couldn't find how to supply a custom GSSAPI to it. 
Is it something that can potentially be implemented?

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I'm certain there's some way to configure ssh to do this, but unfortunately I'm not familiar enough with GSSAPI to be able to tell you exactly _how_.

I'm guessing based off of [PowerShell/Win32-OpenSSH#1295](https://github.com/PowerShell/Win32-OpenSSH/issues/1295) that this is possible somehow...

This actually might be a better request for the https://github.com/PowerShell/Win32-OpenSSH repo - they're more well versed in the details of ssh than we would be, and might be able to get you more specific feedback than we can provide.

**Comment by davidebenato** [comment]
thanks, that's a good point. 
I'll try to see if there's a way to configure Win32-OpenSSH to achieve what I'm trying to do.
