### ISSUE TITLE
Add a hover tip to let user know that holding "Alt" opens profile in a new pane

### ISSUE THREAD

**Issue by alexandair** [microsoft/terminal#7851]
# Description of the new feature/enhancement
If we hold "Alt" when clicking "+" or a profile name, profile will open in a new pane instead of a tab. Very cool, but undiscoverable. A hover tip like "Hold Alt to open as a new pane" would help a user know about a possible action.
Same applies to "Settings" to let a user know that with "Alt" could open `default.json`.

# Proposed technical implementation details (optional)

**Comment by MisinformedDNA** [comment]
Cool. Nice tip.

**Comment by PankajBhojwani** [comment]
Thank you for pointing this out! In a PR now :)

**Comment by DHowett** [comment]
@misinformeddna there's a lot of cool pane stuff linked from #1000, including resize by handle. We're trying to burn down that list :smile:
