### ISSUE TITLE
Add support for the DECREQTPARM report

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#7852]
# Description of the new feature/enhancement

[`DECREQTPARM`](https://www.vt100.net/docs/vt100-ug/chapter3.html#DECREQTPARM) was a sequence used on the VT100 to report the serial communication parameters - things like baud rate, parity, etc. There's absolute no use for it nowadays, and I don't think it was even supported on later DEC terminals, but it seems to be quite widely implemented by modern terminal emulators. This includes XTerm (in VT100 mode), VTE (since around v0.53.0 I think), Konsole, Urxvt, Mintty, and many others.

I have no idea why everyone supports it, but I'd like for us to do so too. It's an easy addition, and If nothing else, it lets us pass another test in Vttest.

# Proposed technical implementation details (optional)

It's fairly straightforward to implement. Everyone just returns a hard coded response (technically two responses, since the first response value depends on the request parameter). I've got a PR ready to go if you're happy to include it, but it's branched from PR #7799, so I'm waiting for that to merge first.

**Comment by DHowett** [comment]
Happy indeed to include it. :smile:
