### ISSUE TITLE
Can't type inside Windows Terminal PowerShell or Command Prompt

### ISSUE THREAD

**Issue by scotto88** [microsoft/terminal#7855]
# Environment

```none
Windows build number:   Windows 10 Pro - 2004 | OS build:  19041.508
Windows Terminal version (if applicable):  1.3.2651.0

Any other software?
```

# Steps to reproduce

Can't type inside Windows Terminal PowerShell or Command Prompt
# Expected behavior

Should show the text characters I typed with my keyboard.

# Actual behavior

No text characters are displaying. Just the blinking cursor.

**Comment by DHowett** [comment]
Have you disabled the "Touch Keyboard and Handwriting Panel Service"?

**Comment by scotto88** [comment]
Yes, that service is showing Disabled.

**Comment by scotto88** [comment]
I changed the service to Startup type: Manual and rebooted. I am now able to type in Windows Terminal. The service is "Touch Keyboard and Handwriting Panel Service" is showing running.

**Comment by DHowett** [comment]
Thank you! This is a /duplicate of #4448.

**Comment by secretgspot** [comment]
This is BS, why do I need to have "Touch Keyboard and Handwriting Panel Service" when I don't use touch or pen on my PC and my mouse/keyboard should be sufficient!  Is there some sort of malware/spyware running with "Touch Keyboard and Handwriting Panel Service" that it must work in order to capture my keystrokes and passwords?!

**Comment by zadjii-msft** [comment]
Read that instead as the "Touch, Keyboard, and Handwriting Panel Service". It's responsible for shuttling input to applications on Windows. #9890 has more info on the inner working of what's going on there.
