### ISSUE TITLE
Running "wt" from Start->Run no longer works

### ISSUE THREAD

**Issue by shooshx** [microsoft/terminal#7858]
# Environment

Microsoft Windows [Version 10.0.18363.904]
Windows Terminal 1.3.2651.0

# Steps to reproduce

Click WinKey+R to open the "Run" window, write "wt", press OK

# Expected behavior

This used to work with the previous version and open windows terminal, as it does work with "cmd"
This is a regression in the latest version
Previous version had "wt.exe" in a different place which is accessible
Running "wt" from within the terminal does work and open a new terminal window

# Actual behavior

I get this message box:

[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\wt.exe

[Content]
Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

[OK]

**Comment by sergiokessler** [comment]
same here, but only if I click on "run as administrator"...

**Comment by DHowett** [comment]
Do you have both preview and stable installed at the same time?

@sergiokessler you need to register the application for both your normal user and the administrator user. I believe that's a different (but similar!) issue.

**Comment by alannt777** [comment]
> Do you have both preview and stable installed at the same time?
> 
> @sergiokessler you need to register the application for both your normal user and the administrator user. I believe that's a different (but similar!) issue.

I had the same issue when I had both the stable and preview version. But now I only use WT preview.
You can fix that by using only one of them

I think the preview version should be named as `wt-preview.exe` like `code-insiders` for Visual Studio Code Insiders . That would be better

**Comment by sergiokessler** [comment]
nope, I don't have the preview version.

![image](https://user-images.githubusercontent.com/14111329/95595574-aea2c200-0a22-11eb-9a12-e53bd796a792.png)

![image](https://user-images.githubusercontent.com/14111329/95595684-d3973500-0a22-11eb-8697-4c0b38a7a776.png)

started normally:
![image](https://user-images.githubusercontent.com/14111329/95595740-e447ab00-0a22-11eb-9dbd-133d87c6725c.png)

**Comment by alannt777** [comment]
Oops

**Comment by shooshx** [comment]
anything on this?

**Comment by zadjii-msft** [comment]
@shooshx As Dhowett mentioned above, do you have both preview and stable installed at the same time?

**Comment by shooshx** [comment]
Sorry, I missed that, how can I tell if I do?  
Going into C:\Program Files\WindowsApps using an administrator cmd.exe I see:

1/08/2020  09:55    <DIR>          Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe
11/08/2020  09:55    <DIR>          Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe
22/08/2020  20:04    <DIR>          Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe
23/09/2020  08:06    <DIR>          Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe

How do I remove the old versions?

**Comment by DHowett** [comment]
/dup #7188 

I don't have any more info, unfortunately. 😦
