### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by OgreTransporter** [microsoft/terminal#7859]
# Description of the new feature/enhancement

I would like there to be a global configuration file - e.g. in the program directory - where you can enter the available consoles for all users of a computer.

I have Anaconda, Python, Git-Bash, Gnuplot, GNU Octave, Lua and YACAS as consoles. It is annoying to have to re-enter the consoles for every new user on the computer.

# Proposed technical implementation details (optional)

You can assign GUIDs, so that individual consoles can be deactivated if necessary via the local `settings.json` and the parameter `hidden` by the local user.

**Comment by j4james** [comment]
Have a look at issue #2933. The general concept being proposed there is to have a way to import settings from another path. I think that probably covers what you're wanting to do.

**Comment by OgreTransporter** [comment]
The discussion is interesting. But I don't want to use one settings.json for all users. I want a global configuration file for all users with some basic settings. If a user does not like the color he can overwrite it in his local configuration file.

**Comment by j4james** [comment]
The solution proposed in that issue was the ability to import settings from other files. See the comment here: https://github.com/microsoft/terminal/issues/2933#issuecomment-536652883

Given that functionality, each user could have their own settings file with their local overrides, and then some kind of import directive that linked in the shared configuration from a global settings file. Is that not what you want?

**Comment by PankajBhojwani** [comment]
This is very much on our roadmap! #7584 /#7632 outline the initial work needed and this will come at some point after

**Comment by zadjii-msft** [comment]
Interesting. You raise an good idea about the ordering mattering here. We'll want to make sure that the user can have files that they import _before_ loading their settings file, and other settings that they load _after_.

"Proto extensions" might be the easiest solution here. With that, you'll be able to drop a fragment of profiles & settings into a global install location, and then all users should be able to have that fragment of settings applied before their own `settings.json`. I'm going to call this a dupe, even if it's not _exactly_ the same thing, you should be able to get the same effect.

/dup #7632
