### ISSUE TITLE
Terminal won't accept keyboard input and shortcut keys 

### ISSUE THREAD

**Issue by malisancube** [microsoft/terminal#7860]
# Environment

```none
Windows build number: 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version: Windows Terminal Preview Version: 1.4.2652.0

```

# Steps to reproduce

Suddenly the console does not accept any input from the keyboard but allows pasting commands

# Expected behavior

The console should allow the user to type commands

# Actual behavior

Typing does not result in any display of input and this is not about colors, since even after trying to type and pressing enter does not yield any response. Running `cmd.exe` works normally. Key bindings don't work either. I'm using the default settings file.

**Comment by alannt777** [comment]
could be a dup of #7855

**Comment by DHowett** [comment]
/dup #7855 which is a /dup of #4448.
