### ISSUE TITLE
Windows Terminal Crashed abruptly.

### ISSUE THREAD

**Issue by raveensrk** [microsoft/terminal#7861]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by alannt777** [comment]
It would be more helpful to the Windows Terminal team if you give information such as your Windows version and Terminal version and additional information if possible
