### ISSUE TITLE
Extract last command typed in the session

### ISSUE THREAD

**Issue by RobOrd** [microsoft/terminal#7867]
I would like to have an option in the terminal.
With this option I can extract the last (success) commands typed in the terminal.

**Comment by DHowett** [comment]
Are you hoping for something like command history? PowerShell supports command history by default.

**Comment by RobOrd** [comment]
Yes.

But made it general.

Can extract command history for a Linux distro (WSL), cmd, poweshell, azure cli.



Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Dustin L. Howett<mailto:notifications@github.com>
Enviado: jueves, 8 de octubre de 2020 05:25 p. m.
Para: microsoft/terminal<mailto:terminal@noreply.github.com>
CC: Roberto Vazquez<mailto:rvazquez@orioncid.mx>; Author<mailto:author@noreply.github.com>
Asunto: Re: [microsoft/terminal] Extract last command typed in the session (#7867)


Are you hoping for something like command history? PowerShell supports command history by default.

**Comment by DHowett** [comment]
All of those products, except for CMD, can do this already. Terminal does not need to do any work here :smile:
