### ISSUE TITLE
add    frequent phrases(or code ) panel

### ISSUE THREAD

**Issue by dokijianhua** [microsoft/terminal#7872]
# Description of the new feature/enhancement
add    frequent phrases(or code ) panel  to help insert command quick;
1.Sometimes we need to type a lot of repetitive commands.
2.Although CMD can use up arrow and down arrow to switch the previously entered command，But after inputting more commands, it is very difficult to find them, This is even more troublesome
3. add like  a  todo list panel,Custom add shortcut command into  frequent phrases,

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This sounds a lot like both #7721 and #1595. While #1595 might be closer to what you're looking for long-term, the workaround listed in #7721 should certainly work well enough for you now, especially with integration with the command palette.

/dup #1595 #7721
