### ISSUE TITLE
Windows terminal not working in multiple desktops for windows 10

### ISSUE THREAD

**Issue by Krrishdhaneja** [microsoft/terminal#7878]
# Environment

```none
Windows build number:  Microsoft Windows NT 10.0.18363.0
Windows Terminal version : Preview 1.4.2652.0


```

# Steps to reproduce

The wt team must fix the issue / bug for users using task view

# Expected behavior

Expected that the wt will not open in the Desktop 2.

# Actual behavior

But what happened was it just opened in the desktop 2.
See the screenshots below for reference...
![wt2](https://user-images.githubusercontent.com/65185487/95649200-fa746a80-0af9-11eb-8eac-25d04c32a9e7.png)
![wt](https://user-images.githubusercontent.com/65185487/95649205-052eff80-0afa-11eb-8840-b501890ea4c6.png)

**Comment by skyline75489** [comment]
OK I'm confused. Who's with me?

You need to give us more information on "steps to reproduce".

**Comment by Krrishdhaneja** [comment]
ok, so the team must fix the issue . And the issue is that the windows terminal does not support multiple desktops. 
so is it ok now or i have to elaborate it more

**Comment by skyline75489** [comment]
Yes, please elaborate. Which operation do you perform with WT to end up in a screenshot like that, and what is the behaviour you expect but does not work.

**Comment by Krrishdhaneja** [comment]
I use the task view very much and i thought of running multiple windows terminal instances on my win 10 machine.
So the behaviour i expected is that i can open a new terminal window on the desktop 2 . 
But this doesn't happen .

**Comment by skyline75489** [comment]
Look, there's like 5 different ways to accomplish what you described. And I believe you are not the only one who use task view very often. Please, just please give us the **exact** steps to reproduce the problem you described, otherwise we got nothing to work with.

**Comment by Krrishdhaneja** [comment]
Briefly : I meant that windows terminal isn't compatible with task view.

**Comment by skyline75489** [comment]
OK I give up. I'll trust @DHowett on this one. I believe many people inside and outside Microsoft use task view on a daily basis. Personally I do not use it that often. And I can not reproduce the issue. Fact I don't even know what exactly the issue is...

**Comment by alannt777** [comment]
I am not having any trouble with Task View

![image](https://user-images.githubusercontent.com/67918878/95652091-52b46800-0b0c-11eb-9b83-09e65d2a9fd6.png)

**Comment by Krrishdhaneja** [comment]
But i was . This is the only issue.

**Comment by Krrishdhaneja** [comment]
**Any suggestions ??**

**Comment by DHowett** [comment]
Nobody can reproduce the error you are encountering.

What other software are you using? Are you using anything that interferes with Task View?

**Comment by zadjii-msft** [comment]
@Krrishdhaneja When you right click on the Terminal in task view, what does it look like?

![image](https://user-images.githubusercontent.com/18356694/95785404-4c082b00-0c9b-11eb-9307-63e99a369fb8.png)

**Comment by alannt777** [comment]
Now I can repro it! ;-)

**Comment by skyline75489** [comment]
@zadjii-msft Yeah that's probably the cause, proving that I don't know nothing about Windows 10..

**Comment by alannt777** [comment]
I am ashamed of myself. I thought I knew something about Windows 10. 😢

**Comment by Krrishdhaneja** [comment]
![wt3](https://user-images.githubusercontent.com/65185487/95821446-8d561480-0d47-11eb-81af-d88458797e0e.png)
Thanks to all who tried to solve the issue especially @zadjii-msft . I am so grateful that I am a part of github where the people try their level best to solve the issue 😊😊 .

**Comment by zadjii-msft** [comment]
Thanks for following up. In the future, the best practice for getting help with issues on GitHub is being able to clearly describe the issue. "When I open the terminal, it appears on all my desktops in task view" is _far_ more useful than "The wt team must fix the issue"

**Comment by Krrishdhaneja** [comment]
Thanks! For suggestion @zadjii-msft . Will be remembering it next time ....

**Comment by Krrishdhaneja** [comment]
Is any one interested in contributing to my repo https://github.com/Krrishdhaneja/virtual-assistant cuz i can't develop it alone to a great extent. Please!

**Comment by Krrishdhaneja** [comment]
## _Anyone, Please!_

**Comment by alannt777** [comment]
This is not a place to advertise your projects. Especially considering that when I took a look at your code. I found a security vulnerability.

**Comment by Krrishdhaneja** [comment]
What's that

**Comment by Krrishdhaneja** [comment]
And am not advertising

**Comment by Krrishdhaneja** [comment]
I just want more people to help me

**Comment by Krrishdhaneja** [comment]
If there is no one to contribute/help you code, how would you be able to develop the code

**Comment by alannt777** [comment]
I do everything myself

**Comment by Krrishdhaneja** [comment]
Ok . Would not be doing this again

**Comment by Krrishdhaneja** [comment]
But i just feel bad , when I don't see anyone contributing to my code

**Comment by Krrishdhaneja** [comment]
So that's why i did it

**Comment by alannt777** [comment]
I feel the same but I don't care

**Comment by Krrishdhaneja** [comment]
Sorry for this

**Comment by Krrishdhaneja** [comment]
But https://github.com/alannt777/LicenseItCLI this one is cool. Would be trying it tomorrow

**Comment by Krrishdhaneja** [comment]
So @alannt777 would you like to contribute to my repo

**Comment by alannt777** [comment]
Well I haven't released any ".exe"s

**Comment by Krrishdhaneja** [comment]
So i have to build it

**Comment by zadjii-msft** [comment]
@alannt777 You're absolutely right. The Terminal repo isn't a place to promote your side projects, especially if they're not related to the Terminal.
