### ISSUE TITLE
Single-key binds for tab switching cause crash

### ISSUE THREAD

**Issue by vvekic** [microsoft/terminal#7879]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Bind a single key (not a key combination such as the default `crtl+tab`) to either `nextTab` or `prevTab`. I used `f3` for `prevTab` and `f4` for `nextTab`.
2. Spawn multiple tabs.
3. Either quickly press your new `nextTab` or `prevTab` keys consecutively, or press and hold them.

# Expected behavior

Tab switching should work even if switching tabs quickly or holding down the respective keys.
I expect to be able to bind `byobu`-like keys to tab control, i.e. `f2`, `f3`, `f4` and use them effectively.

# Actual behavior

The application crashes.

Note: I suspect it has something to do with the tabs context menu that spawns when switching tabs.

**Comment by alannt777** [comment]
While you wait for it, you can use [PowerToys's](https://github.com/microsoft/PowerToys) Keyboard Manager to bind a key to <kbd>ctrl</kbd>+<kbd>tab</kbd>

**Comment by vvekic** [comment]
> While you wait for it, you can use [PowerToys's](https://github.com/microsoft/PowerToys) Keyboard Manager to bind a key to ctrl+tab

thanks! but alas, PowerToys only support remapping keys globally.

**Comment by DHowett** [comment]
Excellent catch. Thanks!

**Comment by zadjii-msft** [comment]
Well this is bizarre - I can't seem to get this to repro with either 1.3.2651.0 or 1.5.3011.0 (a recent internal build off `main`).  I threw the following in my `actions`:

```json

        { "command": "prevTab", "keys": "f1" },
        { "command": "nextTab", "keys": "f2" },
```

and they seem to be working fine, albeit, if I hold them for too long, the window does glitch out for a bit and stop actually changing tabs, as if it can't keep up with the switching. 

> I suspect it has something to do with the tabs context menu that spawns when switching tabs.

anything in particular that makes you think this?

We've got a bunch of changes in the works for how the tab switcher operates, maybe this will just go away in 1.5?

**Comment by Don-Vito** [comment]
@vvekic - can you please check if it still happens to you in 1.6 preview?
