### ISSUE TITLE
conhost.exe crashes when inserting emoji

### ISSUE THREAD

**Issue by savatia** [microsoft/terminal#788]
Steps to repro:

1. Open cmd.exe or Powershel.exe
2. Press Win+. in order to open the Emoji Picker overlay
3. Click on any emoji, multiple times, until the console crashes

**Comment by oising** [comment]
Duplicate of #678

**Comment by miniksa** [comment]
I actually need to un-dupe this. I have a solution to the conhost emoji-picker part, but not the terminal hang part.

Reactivating this so I can fix it (along with the internal crash bug MSFT: 20990158 that has been reported)
