### ISSUE TITLE
windows terminal can not work after ssh long time

### ISSUE THREAD

**Issue by VegeBun-csj** [microsoft/terminal#7881]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

i start two windows terminal to ssh to the virtual box .
when i do something after two hours, i find the terminal do not works. so i try to close the window,but it not works!!!!!,until i close the threads in the manager task.

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by jdebp** [comment]
What happens when you simply and only terminate the SSH client?  Because if Windows Terminal keeps on going, then this is likely the things discussed in #7829 .  Path MTU Discovery problems are not _terminal_ problems, and this possibility needs to be eliminated.

**Comment by VegeBun-csj** [comment]
ok,this issue dose not happen again.I will pay attention to this terminal continually.
