### ISSUE TITLE
setting are not working in my windows

### ISSUE THREAD

**Issue by Adwart2000** [microsoft/terminal#7882]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by Adwart2000** [comment]
how to fix windows terminal (preview) settings are not working please fix it....
I want to customize windows terminal (preview), like font colours nd changing background.

**Comment by DHowett** [comment]
You’re going to have to provide more information than “it doesn’t work.” _what is happening?_
