### ISSUE TITLE
Add notice if service disabled: "Touch Keyboard and Handwriting Service"

### ISSUE THREAD

**Issue by benfavre** [microsoft/terminal#7886]
Re #4448
If the service "Touch Keyboard and Handwriting Service" is not available, a notice should be displayed with a link to a README or the open unresolved issue.

**Comment by DHowett** [comment]
I’m not sure Terminal can really detect this unless it’s running as administrator ☹️

**Comment by KalleOlaviNiemitalo** [comment]
In Windows 10.0.19041.508, the security descriptor of TabletInputService in grants INTERACTIVE (IU) these [access rights on the service](https://docs.microsoft.com/windows/win32/services/service-security-and-access-rights#access-rights-for-a-service):

- SERVICE_QUERY_CONFIG = 0x0001 (CC)
- SERVICE_QUERY_STATUS = 0x0004 (LC)
- SERVICE_ENUMERATE_DEPENDENTS = 0x0008 (SW)
- SERVICE_INTERROGATE  = 0x0080 (LO)
- SERVICE_USER_DEFINED_CONTROL = 0x0100 (CR)
- READ_CONTROL = 0x00020000 (RC)

I imagine Windows Terminal would normally have INTERACTIVE in its token. SERVICE_QUERY_CONFIG lets QueryServiceConfig check whether the service is disabled. SERVICE_QUERY_STATUS lets QueryServiceStatus check whether the service is running. If Windows Terminal cannot open the service control manager or the service for some reason, then just write telemetry and don't warn the user.

```
C:\>sc.exe GetDisplayName TabletInputService
[SC] GetServiceDisplayName SUCCESS
Name = Touch Keyboard and Handwriting Panel Service

C:\>sc.exe sdshow TabletInputService

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;RP;;;WD)

C:\>sc.exe qc TabletInputService
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: TabletInputService
        TYPE               : 20  WIN32_SHARE_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\WINDOWS\System32\svchost.exe -k LocalSystemNetworkRestricted -p
        LOAD_ORDER_GROUP   : PlugPlay
        TAG                : 0
        DISPLAY_NAME       : Touch Keyboard and Handwriting Panel Service
        DEPENDENCIES       : RpcSs
        SERVICE_START_NAME : LocalSystem
```

**Comment by zadjii-msft** [comment]
More docs

* [OpenSCManager](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-openscmanagera)
* [OpenService](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-openservicea)
* [QueryServiceConfig](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-queryserviceconfiga)

**Comment by DHowett** [comment]
I'm usually against stuff like this, because we have no way of knowing all of the random conditions that _might_ result in an issue. If we try to detect them all and provide UI about it, we'll go mad.

This one, however. This one comes up routinely. This one comes up enough that we should use an InfoBar or something more obtrusive and smack the user with a warning that terminal won't work properly for them.

We can, by necessity, only do this in the Win32 builds (not the UWP builds)... but I'm betting that's the only place there's an issue :smile:

Thanks for the suggestion, and thanks @KalleOlaviNiemitalo for the research.

**Comment by download13** [comment]
Is there any way to turn off the warning? I'm aware of the issue, but it works fine for me with the service off and I don't want to have to click past the warning every time

**Comment by KalleOlaviNiemitalo** [comment]
> Is there any way to turn off the warning?

Windows Terminal has no such setting. According to <https://github.com/microsoft/terminal/pull/8095#issuecomment-718909607>, you are expected to leave the service enabled.

Hypothetically, if Windows Terminal were not able to open the service for SERVICE_QUERY_STATUS access, then that would disable the warning. I can think of a few ways to achieve that but they seem likely to cause problems elsewhere.

**Comment by piscisaureus** [comment]
> Is there any way to turn off the warning? I'm aware of the issue, but it works fine for me with the service off and I don't want to have to click past the warning every time

I would really appreciate that too.
I have the service in question is disabled for a reason: enabling it makes keyboard lag unbearable(*). And I don't use touch text input anyway, so there's no reason to leave it enabled.

(*): Unsurprising: the service causes ctfmon.exe to be started and stopped every time a key is pressed. Solving that would be the even better than a no-warning flag...

**Comment by levicki** [comment]
> This one, however. This one comes up routinely. This one comes up enough that we should use an InfoBar or something more obtrusive and smack the user with a warning that terminal won't work properly for them.

@DHowett 

Can you please explain why Windows Terminal wouldn't run without Touch Keyboard and Handwriting Service except for those users who don't have a physical keyboard (such as those using tablets or kiosks)?

Also, could you please explain your "smack the user" attitude? It sounds really condescending.

In my opinion as a seasoned Windows developer, throwing a warning (and the one that cannot be disabled/dismissed after being seen once) is always (ab)used as an easy way out of designing a proper solution to the actual problem.

**Problem:**
Users with no physical keyboard cannot use application which requires keyboard input if service providing virtual keyboard is disabled.

**Solution:**
If:
 - running on a device that has no physical keyboard attached (easy to check)
 - Touch Keyboard service is disabled (easy to check, already done)
 - warning wasn't already shown or is disabled in settings (one DWORD registry key and one bool setting in JSON)
 Then:
 - Show the warning
 - Remember it has been shown in the registry
End.

**Comment by levicki** [comment]
@download13 

If you really can't wait for Microsoft to get smarter about the way it smacks users in the face you can do this:

1. Make sure Touch Keyboard service is stopped and disabled.
2. Export `HKLM\System\CurrentControlSet\Services\TabletInputService` registry key to a file (say `TabletInputService.reg`).
3. Open command prompt as an Administrator and run `sc delete TabletInputService`.

In case you decide you need the service back you can import it from the file you made in step 2. However, keep in mind that restoring registry keys like that will most likely not restore their security permissions so the service or anything else that relies on it might not work and you might end up having to reinstall Windows.

**Comment by LinuxOnTheDesktop** [comment]
Should the notice informing the user of the strange and uncheerful fact at issue inform the user of the further strange and uncheerful fact that, as per #4448, the user must also reboot?

**Comment by shiomiyan** [comment]
I have read through the thread.
But please, please, please add a way to not give a warning :(

**Comment by zadjii-msft** [comment]
There's a PR like, right above your comment that adds support for disabling the warning:
![image](https://user-images.githubusercontent.com/18356694/115142120-9e892200-a005-11eb-9494-2e856d86e0d7.png)

The setting is:

```jsonc
// If disabled, don't show warning if 'Touch Keyboard and Handwriting Panel Service' disabled.
"inputServiceWarning": false,
```

**Comment by Sorin-M-Oprea** [comment]
> The setting is:
> 
> ```js
> // If disabled, don't show warning if 'Touch Keyboard and Handwriting Panel Service' disabled.
> "inputServiceWarning": false,
> ```

Thank you!
