### ISSUE TITLE
Terminal unresponsive to keystrokes when outputting large amount of text

### ISSUE THREAD

**Issue by cshei** [microsoft/terminal#7890]
# Environment

```none
Windows build number: 10.0.19042.541
Windows Terminal version (if applicable): 1.4.2652.0 (Preview)

Any other software?  SSH from Windows or WSL
```

# Steps to reproduce

* SSH to another machine
* run 'yes' command
* Press CTRL-C or CTRL-Z

# Expected behavior

Terminal output stops shortly after keypress.

# Actual behavior

Terminal output continues for an extended period of time (10-30+ seconds).  It's worse if you open WSL2 and SSH from there (I just measured it continuing even after 30 seconds and had to close the window because CTRL-C was ineffective), but even launching SSH from PowerShell, it took 9 seconds for the output to stop.

In any Linux terminal, or even the SSH Extension for Chrome, CTRL-C takes less than a second to stop in these cases.  I've noticed this behavior since the initial preview releases of Windows Terminal, and it makes using Windows Terminal difficult because if I'm running "emerge" in Gentoo (either in WSL2 or remotely over SSH), the massive amount of compiler commands that get printed cause Windows Terminal to frequently become unresponsive, making it take a really long time to switch TMUX windows away from the emerge or disconnect from the TMUX session.

Running VIM over SSH or mosh also feels sluggish compared to other SSH clients, and when running VIM remotely over mosh in WSL2, I can see the window redrawing when I scroll down with CTRL-F.  It shouldn't be an issue of slow hardware, since I see this on both my X1 Carbon gen 7 laptop and my desktop with an i7-8700K and NVIDIA Titan X GPU.

Other than this one issue, Windows Terminal is an awesome piece of software, and I'd definitely use it as my preferred SSH client host if this could be fixed!  I'm currently using the SSH and Mosh extensions for Chrome because they do not suffer from this issue.

**Comment by skyline75489** [comment]
I think #198 the first issue that described the similar issue.

**Comment by jdebp** [comment]
It is ironic that you mention Mosh, because one of the selling points of Mosh has always been that this _is_ a problem in Linux.  Specifically, it's a problem when one has SSH or some other remote terminal mechanism in the mix.  As such, it is better to reproduce this issue _without_ any involvement of SSH, which only serves to obscure things.  But #198 as mentioned already deals in that.

**Comment by DHowett** [comment]
Yep -- there's a couple known issues floating around for this. The one that's had the most research put in, specifically around ^C and SSH, is /dup #6258. Notes in comment https://github.com/microsoft/terminal/issues/6258#issuecomment-649762617.
