### ISSUE TITLE
terminal emoji not shown

### ISSUE THREAD

**Issue by xaotag** [microsoft/terminal#7895]
windows terminal 
![image](https://user-images.githubusercontent.com/40427877/95735737-cc3c8980-0cb7-11eb-9853-3be2fc7a54e0.png)
![image](https://user-images.githubusercontent.com/40427877/95735808-eaa28500-0cb7-11eb-960f-a345c4515900.png)
git-bash 
![image](https://user-images.githubusercontent.com/40427877/95735919-13c31580-0cb8-11eb-883f-905e895fd117.png)
### help me

**Comment by DHowett** [comment]
Is `gitmoji` written in Javascript?

**Comment by DHowett** [comment]
Did some investigation: Yes, gitmoji is written in Javascript.
NodeJS's I/O library, libuv, deletes emoji when run on Windows. We have filed a bug on them, and they have fixed it.

/dup https://github.com/libuv/libuv/issues/2909

**Comment by magicLaLa** [comment]
@xaotag Is it possible to use nvm to switch the node version? Try it, I used node-10.14.2 to show it intact, and the display on node-12.17.0 is the same as yours

**Comment by magicLaLa** [comment]
@xaotag Is it possible to use nvm to switch the node version? Try it, I used node-10.14.2 to show it intact, and the display on node-12.17.0 is the same as yours。

**Comment by ialexanderbrito** [comment]
I have the same problem, how can I fix it?

**Comment by DHowett** [comment]
You need to put pressure on your javascript runtime vendor to update their dependencies.
