### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Korporal** [microsoft/terminal#7897]
This is just a question. I can't find any details of what are "stable" versions and what are "beta" etc. If I wanted the most recent stable version, how would I locate that? and what is the difference between a "preview" and not preview?

Thanks

**Comment by DHowett** [comment]
Tapping in @cinnamon-msft to give more info on this one.

In short, we keep the releases on [our releases page](https://github.com/microsoft/terminal/releases) marked "pre-release" (preview) or "stable" (stable). Preview is where all new features go, automatically. Those builds are produced from the main branch of this repository every month.

![A prerelease build](https://user-images.githubusercontent.com/189190/95764128-e26d2a00-0c64-11eb-95e4-61a5599a6a0f.png) ![A stable build](https://user-images.githubusercontent.com/189190/95764157-eb5dfb80-0c64-11eb-86a9-24f0f4c63979.png)

All changes in a preview release become stable one month after they were released in preview.

If you want the most stable version, install from the store using the ["Windows Terminal" product listing](https://aka.ms/terminal).

![image](https://user-images.githubusercontent.com/189190/95764266-121c3200-0c65-11eb-8d5e-38573762576d.png)

If you want the most preview'y version, install from the store using the ["Windows Terminal Preview" product listing](https://aka.ms/terminal-preview).

![image](https://user-images.githubusercontent.com/189190/95764289-1b0d0380-0c65-11eb-8bdd-c7a6a4d78708.png)

**Comment by Korporal** [comment]
@DHowett  - This is much appreciated, thanks!
