### ISSUE TITLE
Shortcut terminal similar to Yakuake?

### ISSUE THREAD

**Issue by Ashvith** [microsoft/terminal#7903]
Is there any means by which a dock-like terminal can be added to the topmost part of Windows? So that it pops from the topmost part on pressing aby shortcut, like F12 for instance?

Or maybe a desktop widget?

**Comment by skyline75489** [comment]
This is #653. Please subscribe to that thread instead opening new ones.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Yakuake+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #653 for more discussion.

/dup #653
