### ISSUE TITLE
Windows Terminal turns completely opaque when I load Vim

### ISSUE THREAD

**Issue by Chaoticsys101** [microsoft/terminal#7905]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version (if applicable): Windows Terminal 1.3.2651.0

Any other software?  Vim 8.2
```

# Steps to reproduce
First open Window Terminal, turn acrylic on.
It works fine. Execute vim.exe. Windows Terminal turns opaque.
Exit vim.exe. Windows Terminal goes back to normal. 

# Expected behavior
Acrylic transparency should stay the same.
This behaviour does not occur with cmd.exe (transparency stays the same).

![Capturar](https://user-images.githubusercontent.com/67800528/95847895-35b6a980-0d45-11eb-8b22-0501d1e0ab38.PNG)
![Capturar2](https://user-images.githubusercontent.com/67800528/95847900-37806d00-0d45-11eb-9056-6a6976148b03.PNG)

**Comment by alannt777** [comment]
@Chaoticsys101 

I am not having any issues with vim but can you share your .vimrc to let me try to repro this issue

**Comment by DHowett** [comment]
This is intentional behavior. Vim is requesting that the background color be set, so Windows Terminal _must_ set the background color. More info [here](https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#my-colors-look-strange-there-are-black-bars-on-my-screen).

**Comment by Chaoticsys101** [comment]
Could you please be a bit more specific? I put "background" : "#000000" in
defaults in the config file but it stayed the same.

Dustin L. Howett <notifications@github.com> escreveu no dia quinta,
15/10/2020 à(s) 18:57:

**Comment by alannt777** [comment]
@Chaoticsys101 

Vim is setting the console color to be that color, that's what @DHowett meant. Even though I am not having any troubles with vim.

Must have something to do with your vimrc or you can just create an issue in vim

**Comment by Chaoticsys101** [comment]
Thanks. If I do 'vim -u NONE -U NONE' it works fine. So the problem is in my vimrc. Do you have a public email or some place where we could talk? I would like to share my vimrc to see if we could figure out what is wrong

**Comment by alannt777** [comment]
@Chaoticsys101 This will help -> https://vi.stackexchange.com/questions/18212/prevent-colorscheme-from-changing-background-color

**Comment by Chaoticsys101** [comment]
Unfortunately it did not... BTW how did you set your vimrc to 256 color?

**Comment by alannt777** [comment]
@Chaoticsys101 Ok. I got a random vimrc that I got from the internet (I installed vim in WSL Ubuntu)

**Comment by alannt777** [comment]
@Chaoticsys101 try using a different vimrc and add settings back individually and see which is causing the trouble.

**Comment by Chaoticsys101** [comment]
I will send my vimrc in a few hours, I'll share a link or something

**Comment by Chaoticsys101** [comment]
I tried but it either worked with the default colorscheme or didn't

**Comment by Hammster** [comment]
For anyone who wants to change this behaviour I created a shader to solve this issue. 

You have to adjust the color inside the shader as explained in the settings section. but after that you can run xterm colors + transparency. For now, it can only turn 1 color into transparency though that should be enough for 99% of the use cases, cheers.

https://github.com/Hammster/windows-terminal-shaders#Transparent

**Comment by DHowett** [comment]
While it’s cool that we can do that with shaders, it seems like the wrong speed to delete an entire color when someone could just reconfigure vim :)

**Comment by Hammster** [comment]
If the configurations solve the issue sure, and deleting the color is more or less a workaround, but it get's the job done when. Especially when using xterm based color themes especially when `hi Normal ctermbg=NONE guibg=NONE ` isn't working at all and your only other option is to disable xterm colors :)
