### ISSUE TITLE
Support for 'Modern Terminal' editors

### ISSUE THREAD

**Issue by novachief101** [microsoft/terminal#7909]
# Description of the new feature/enhancement
'Modern Terminal' editors do not work (editors like [Micro](https://github.com/zyedidia/micro)). If you try to select something wih the cursor, it doesn't select it in the terminal properly. Also, when I click somewhere, it doesn't change the cursors position. This is **not** a problem with the editor, it works fine in Command Prompt.
   
**Windows Terminal (text isn't really selected, cursor does not move):**
![Windows Terminal not working properly for Micro](https://user-images.githubusercontent.com/65995389/95853670-69a8c380-0d73-11eb-8bb7-a615f7a83bad.png)
**Command Prompt (properly working):**
![Screenshot (206)](https://user-images.githubusercontent.com/65995389/95853914-c310f280-0d73-11eb-80b1-0ce00b31e691.png)

# Proposed technical implementation details (optional)
Add an option to disable selecting and somehow make it more Command Propmt like.

**Comment by zadjii-msft** [comment]
Thanks for the report! From trying to read between the lines here, this sounds like this is actually caused by the terminal not supporting win32 mouse input quite yet. I'd follow #376 for more details.

/dup #376
