### ISSUE TITLE
Surface keyboard shortcuts in Menu when shown

### ISSUE THREAD

**Issue by timheuer** [microsoft/terminal#791]
Proposal: Ensure the Menu items show the keyboard shortcuts
Guidance: [Keyboard accelerators](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)

![image](https://user-images.githubusercontent.com/4821/57726820-cf57c400-7644-11e9-8b0d-bc348e524262.png)
(note: yes the CTRL+Down is incorrect for settings, working on fixing that)

When enabling keyboard users, helping them not have to hunt for productive shortcuts is a good user experience.  When using menus, it is best practice if a shortcut exists, to surface that to the user like above.

Changes are simple since the keyboard shortcuts are already there, changes to TerminalApp\App.cpp are all that are needed.

Questions:
[] How would this affect custom keybindings in #537 ?

**Comment by miniksa** [comment]
@timheuer are you working on this? Should we assign you?

**Comment by timheuer** [comment]
Yes.  There is a potential blocker in UWP APIs that I'm investigating, but I can take this.

**Comment by mdtauk** [comment]
The JumpList items should match the order, and the profile order needs to persist so those keyboard accelerators can become almost muscle memory

**Comment by timheuer** [comment]
@mdtauk this is not the JumpList item. But the menu already matches the order in profile.json file.

**Comment by mdtauk** [comment]
@timheuer noted :) - just wanted to emphasise the idea of keeping these consistent if the Shortcut Keys are numerical. Ctrl+Shift+1, 2, 3 etc

**Comment by timheuer** [comment]
The existing keybindings here are activated within the app. I can’t recall if you can trigger a jump list via a shortcut but good to add this feedback on that work item.
