### ISSUE TITLE
[Functional-Command Palette]- User is not able to move back from the New Tab sub menu as there is no functionality provided to move out of Sub menu.

### ISSUE THREAD

**Issue by DasaradhaKamjula** [microsoft/terminal#7910]
**User Experience:**
Users who rely on screen reader/Keyboard will not be able to navigate efficiently if there is no option provided to move out of Sub menu

**Test Environment:**
App: Windows Terminal Preview
Feature: Command Palette
Screen Reader: Narrator
OS: Win 10 2004 Build (19041.508)

**Repro Steps:**
1.Open Windows terminal Preview app
2.Open Command Palette using shortcut (Ctrl+shift+p)
3.Search for New tab command in the search field
4.Navigate to New Tab list item having sub menu and activate it .
5.Verify whether there is any option provided to move back.

**Actual**:
User is not able to move back from the sub menu as there is no functionality provided to move out of Sub menu.

Note: Same issue repro for Split pane and Set color scheme controls having Sub menu

**Expected:**
Functionality should be provided to move back from sub menu by using back button or some other way other wise user has to close command palette and open it again to get all commands

**Comment by zadjii-msft** [comment]
This is a really good idea

**Comment by DHowett** [comment]
@DasaradhaKamjula This has been fixed pending future release. I've reopened the bug so that you can track it.

**Comment by zadjii-msft** [comment]
@Chandresh1007  If this is confirmed as fixed, can we close this issue now?

**Comment by Priyanka-Chauhan123** [comment]
Issue is fixed. Verified on Windows terminal version: 1.8.1521.0 and OS version: Win 10 build 21390.2025. Hence, closing the bug.
