### ISSUE TITLE
[Functional-Command Palette]- User is not able to perform action using shortcuts when command palette is open.

### ISSUE THREAD

**Issue by DasaradhaKamjula** [microsoft/terminal#7914]
**User Experience:**
Users who rely on screen reader/Keyboard will not be able to perform action efficiently if shortcuts are not working when command palette is open

**Test Environment:**
App: Windows Terminal Preview
Feature: Command Palette
OS: Win 10 2004 Build (19041.508)

**Repro Steps:**
1.Open Windows terminal Preview app
2.Open Command Palette using shortcut (Ctrl+shift+p)
3.Verify whether user is able to perform any shortcut operation when command palette is open. 

**Actual:**
User is not able to perform action using shortcuts when command palette is open.

**Expected:**
User should be able to perform the shortcut operation even when the command palette is open.

**Comment by zadjii-msft** [comment]
@cinnamon-msft @DasaradhaKamjula What's the process for resolving these issues as dupes? We've already got #6679 tracking this same issue

**Comment by Hegunumo** [comment]
I’m going to work on this.

**Comment by zadjii-msft** [comment]
@Hegunumo thanks! Be careful while working on this one - it might be trickier than it seems on the surface. I tried doing this before, by passing the `ShortcutActionDispatch` to the `CommandPalette`, but there were enough weird edge cases that I never followed up on it. There's a bunch more notes of the pitfalls I found in #6679. 

If you need any help, feel free to ask questions ☺️

**Comment by zadjii-msft** [comment]
@Chandresh1007 @Priyanka-Chauhan123 @DasaradhaKamjula I believe this is fixed in newer versions of the Terminal. (fixed in #8586). Could you confirm and close this?

**Comment by Priyanka-Chauhan123** [comment]
Issue is fixed. Verified on  Windows Terminal Version: 1.9.1942.0. Hence, closing the bug.
