### ISSUE TITLE
Remapping keys via PowerToys does not work in Windows Terminal

### ISSUE THREAD

**Issue by Reisse** [microsoft/terminal#7918]
# Environment

```
Windows build number: 10.0.19041.0
Windows Terminal version: 1.3.2651.0
Microsoft PowerToys v0.20.1
```

# Steps to reproduce
Go to Keyboard Manager in PowerToys. Remap Ctrl + Left Arrow to Home, Ctrl + Right Arrow to End, Ctrl + Up Arrow to PgUp, Ctrl + Down Arrow to PgDn.
Start Windows Terminal, try using remapped shortcuts.

# Expected behavior
Ctrl + Arrows should behave as Home/End/PgUp/PgDn.

# Actual behavior
Ctrl + Arrows do nothing at all.

**Comment by DHowett** [comment]
/dup #7438 #7495 #7843 https://github.com/microsoft/PowerToys/issues/6849 https://github.com/microsoft/PowerToys/issues/6024

**Comment by MedouneSGB** [comment]
![image](https://user-images.githubusercontent.com/40875400/197274289-2ac21887-ef62-4989-8556-42ed8a79f7c7.png)
Link : https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager

Hi this may help new comers as this topic appear firts when googling 
"Remapping keys via PowerToys does not work in Windows Terminal"

Nice job guys really appreciate the Terminal.💯
