### ISSUE TITLE
Type in mutiple panes simultaneously

### ISSUE THREAD

**Issue by simonnylund90** [microsoft/terminal#7919]
# Description of the new feature/enhancement

Is there plans to make it possible to type in mutiple panes simultaneously. Would be nice IF you want to run the same commands on multiple servers e.g.

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
This can be thrown in the list for #4000 but this should definitely be third-party maintained. There are plenty of cli tools to do what you want from a single Terminal window. For example you could use fabric from python to launch some commands or a script over multiple hosts.

**Comment by zadjii-msft** [comment]
I actually disagree that this should be an extension - this is something iTerm2 has had for a while. We're actually already tracking this over in #2634, so feel free to continue the discussion there. Thanks!

/dup #2634
