### ISSUE TITLE
Move hard-coded strings and UI text to Resources

### ISSUE THREAD

**Issue by timheuer** [microsoft/terminal#792]
There are a few places in current iteration that are hard-coding UI-shown values and should move those to resources for easier updating and localization.

Need to determine if following UWP-style resources or RC based.

**Comment by DHowett-MSFT** [comment]
Thanks for filing this, it's actually the reason we haven't bitten off some of the more interesting things. I think we should be able to use UWP-style resources, but that'll require a good bit of integration work.

The build tools don't seem capable of rolling up multiple levels of component resources into the toplevel app package `.pri` file. ☹️

**Comment by timheuer** [comment]
There is a merge capability for PRI (or used to be) that existed for this reason (a component with it's own PRI + app with it's own PRI == single package PRI).  It's possible.  Good thing is I don't think that you have many strings that will be a part of the host here that are problematic.  But you may want resources for other reasons of course too (defaults, etc.)

**Comment by DHowett-MSFT** [comment]
It's possible, but the "Windows Application Packaging" project doesn't play too nicely with multiple dynamic library components rolling up through a Win32 EXE (that doesn't support resw/resx) to make that happen easily. There's work here.

**Comment by zadjii-msft** [comment]
Hey so for the record, the branch I have with the error dialog ([dev/migrie/f/gh-error-dialog](https://github.com/microsoft/terminal/blob/dev/migrie/f/gh-error-dialog/src/cascadia/TerminalApp/App.cpp#L187-L190)) does some of this. I just haven't gotten the UI tweaked exactly right to make this branch ready to PR quite yet.
