### ISSUE TITLE
Keyboard text selection with Shift not working

### ISSUE THREAD

**Issue by dylank** [microsoft/terminal#7921]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1082]
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Steps to reproduce

Text selection with keyboard no longer working

In regular command prompt, you can highlight text with the keyboard by holding shift and using arrow keys/home key. It also works with word groups (e.g. ctrl+shift+left arrow)

This doesnt work with windows terminal

# Expected behavior
Text is selected, as is copy paste, like regular command prompt

# Actual behavior

Shift doesn't seem to do anything

**Comment by zadjii-msft** [comment]
Nope, sure doesn't. This is a feature request that's actually already being tracked over in #4993, feel free to follow that issue for more discussion. Thanks!

/dup #4993
