### ISSUE TITLE
Option to entirely disable right-click-to-paste

### ISSUE THREAD

**Issue by iarna** [microsoft/terminal#7922]
# Description of the new feature/enhancement

Option to entirely disable right-click-to-paste.

# But why?

I primarily use Windows Terminal from a Surface Laptop 3, which is a single button laptop. In order to be able to right click, I have two-finger-tap-to-right-click enabled. This works well enough. However when typing furiously into a Terminal it's easy to accidentally brush the touchpad with my hands, resulting in stray right-clicks. This would only be a minor annoyance except that every time I do this, Terminal does a paste. I find myself frustrated, regularly having to either dismiss the "are you sure you want to paste that giant thing" warning or undo the changes it pasted in.

# Proposed technical implementation details (optional)

A config option would suffice, similar to the existing one that controls select-to-copy.

**Comment by alannt777** [comment]
Will be addressed by issue #1553

**Comment by zadjii-msft** [comment]
Thanks for the help triaging @alannt777!
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1553 for more discussion.

/dup #1553
