### ISSUE TITLE
Scoop install 

### ISSUE THREAD

**Issue by guestdj** [microsoft/terminal#7934]
The documentation for installing Terminal via scoop is not correct, you have missed a first step which is to add the extras bucket to the searchable list of repos
When I type: 
> scoop install windows-terminal
Reponse:
Couldn't find manifest for 'windows-terminal'.

To add the extras bucket into the list of known repos:
scoop bucket add extras

It then installs!

**Comment by WSLUser** [comment]
@DHowett I'm looking to bump the Super-Linter GH Action version to remove some bugs and update the linters. This doc change would seem to be perfect for testing everything works as it should. Would it be ok if I submitted both in the same PR and use the README update as the tester?

**Comment by DHowett** [comment]
Sure.

**Comment by WSLUser** [comment]
PR added. Everything looks good.
