### ISSUE TITLE
Localize UI Strings

### ISSUE THREAD

**Issue by timheuer** [microsoft/Terminal#794]
Host UI elements should be localized.  I imagine this is a known TODO, but ensuring it is captured

**Comment by DHowett-MSFT** [comment]
Let's use #792 as the master issue for making sure the right things are localized _and localizable_.

**Comment by timheuer** [comment]
Ok, wasn't sure if you wanted to treat them separately.  I would have treated them as separate tasks, but 🤷‍♂  :-)
