### ISSUE TITLE
Cannot use ALT to split panes after opening `Close...` tab submenu

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#7941]
# Environment

```none
Windows Terminal version (if applicable): 1.5.2892
```

Regression from #7728.

It looks like every time we try to _split a pane_, we try to re-register the menu items against the tab.
We try to reparent the menu items into a new context menu. Because of that, we eat an exception that they already have parents.

All Tab event registration fails afterwards for that tab.

**Comment by DHowett** [comment]
(/cc @mpela81, if you want to have a fun debugging session :smile:)

**Comment by mpela81** [comment]
Fantastic 😄 

As far as I can see, when splitting panes we call `Tab::Initialize` again, which re-builds the context menu from scratch. But we keep a reference to the closeTabsAfter/closeOtherTabs sub-menu items (to enable/disable them at runtime), so the same end up being appended to a new parent and 💣

To fix it, we could re-create the sub-items as well. Alternatively, the question is why creating the context menu again in the first place?

**Comment by DHowett** [comment]
> why creating the context menu again in the first place?

If I had to guess, I'd say... "oversight'!

**Comment by mpela81** [comment]
> 
> 
> > why creating the context menu again in the first place?
> 
> If I had to guess, I'd say... "oversight"!

so... we could just move the `_CreateContextMenu()` call to the Tab's constructor, couldn't we?
