### ISSUE TITLE
Hello I cannot customize my terminal backgrounds neither fonts popup message showing trailing commas errror. I am unable to find the root of this issue. What to do ?

### ISSUE THREAD

**Issue by Skipper1117** [microsoft/terminal#7943]

**Comment by Skipper1117** [comment]
There are problems in customization in window terminals such as
background image, font etc. Whenever I tried to make some changes in the
json file its showing the error `ERROR IN TRAILING COMMAS`. What to do?
[image: terminal error.png]

**Comment by zadjii-msft** [comment]
@Skipper1117 Could you share your `settings.json`?
