### ISSUE TITLE
Turn off antialiasing completely

### ISSUE THREAD

**Issue by gim913** [microsoft/terminal#7946]
# Environment

```none
Windows build number: ersion 10.0.19041.572
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.4.2652.0
```

# Steps to reproduce

1. Clear type turned off
2. Smoothing of font edges turned off

![image](https://user-images.githubusercontent.com/496298/96250911-e7591300-0faf-11eb-8115-776b4fc488b0.png)

# Expected behavior

Add an ability to turn of antialiasing completely within windows terminal.
Currently `antialiasingMode` takes only following values:
`Accepts: "grayscale", "cleartype", "aliased"`

# Actual behavior

Even with both clear type turned off and font smoothing turned off,
windows terminal is using own antialiasing mechanism, that doesn't allow "NONE/NO" option.

Compare same font in cmd vs windows terminal (bottom one is wanted/expected)

![image](https://user-images.githubusercontent.com/496298/96251342-9695ea00-0fb0-11eb-88e9-807d784b87da.png)

**Comment by zadjii-msft** [comment]
Did you perhaps try the `aliased` setting? You know, the anti-anti-aliasing mode?

**Comment by gim913** [comment]
Now I feel silly. Indeed, setting to `aliased` makes it work.

I've tried all 3 modes earlier, and it didn't seem like they were working.
After re-reading the docs it's clear why, I haven't restarted the terminal when changing that value.

Thank you, very, very much ❤️

**Comment by gim913** [comment]
One more comment on this... on documentation page:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#antialiasing-text

animated image showing the differences between various settings looks gets **resized** and looks like this
![image](https://user-images.githubusercontent.com/496298/100999474-1d9d2280-355d-11eb-8362-909eafdd9719.png)

the same image, when opened in full view is ok however:
![image](https://user-images.githubusercontent.com/496298/100999560-360d3d00-355d-11eb-95dd-58530ed27072.png)
