### ISSUE TITLE
Random newline insterted with full screen applications

### ISSUE THREAD

**Issue by Nosamdaman** [microsoft/terminal#7947]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
Debian for WSL
Vim
Curl
Fish
```

# Steps to reproduce

1. Run some commands to produce enough output to require a scrollback
![image](https://user-images.githubusercontent.com/54364725/96257346-325f3000-0f88-11eb-92ce-035969360399.png)
2. Open a fullscreen application. (`vim` or `htop` for example)
![image](https://user-images.githubusercontent.com/54364725/96257253-0643af00-0f88-11eb-8625-b0478e481aa8.png)
3. Close the application

# Expected behavior

After closing the application, the output from previous commands should not be affected. This is properly handled in the default `conhost` terminal for Debian for WSL.

# Actual behavior

![image](https://user-images.githubusercontent.com/54364725/96257300-1e1b3300-0f88-11eb-88e5-64de939876fd.png)
A random newline is inserted into the console output where it shouldn't be.

**Comment by DHowett** [comment]
Sorry -- something about closing/reopening this must have mixed up our triage queue.

This is definitely something to do with how we manage the alternate buffer in the console session backing the terminal.

I think that this will be fixed when we resolve #381. Then, Terminal will know there's an alt buffer in use and it will not break its own scrollback.

/dup #381
