### ISSUE TITLE
[GitHub Issues] Add config.yml in .github/ISSUE_TEMPLATES

### ISSUE THREAD

**Issue by alannt777** [microsoft/terminal#7953]
Add config.yml to [.github/ISSUE_TEMPLATES](https://github.com/microsoft/terminal/tree/master/.github/ISSUE_TEMPLATE)

## Why?

This allows to have finer control over issue creating experience of the end user (or a dev). You can do things like add a redirect to Microsoft Security Response Center as an option for submitting an issue (for reporting a security vulnerability).
<hr>

Learn more [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)
<hr>

cc @zadjii-msft @DHowett

**Comment by alannt777** [comment]
I would like to make a PR for this if you think that this ☝️ is a good idea.

**Comment by zadjii-msft** [comment]
I'm not sure why we'd need a `config.yml` in addition to the [existing `ISSUE_TEMPLATE`s](https://github.com/microsoft/terminal/tree/master/.github/ISSUE_TEMPLATE) we have. Do you have a specific suggestion of something to add? 

I don't think blindly directing people directly to MSRC would be helpful to us as a dev team, I think I'd rather have us notified of the request as well, so we could at least follow up on it.

**Comment by alannt777** [comment]
Use cases include:

- Documentation issues (in docs.microsoft.com) redirects to [MicrosoftDocs/terminal](https://github.com/MicrosoftDocs/terminal) 
- Security vulnerabilities issues redirects to Microsoft Security Response Center

**Comment by DHowett** [comment]
@zadjii-msft yea, the cool thing about the yml file is that you can add things that _aren't_ issue templates. That's the biggest deal.

Here's what PowerShell uses it for:

![image](https://user-images.githubusercontent.com/189190/96524736-ec2afa80-122d-11eb-8ddd-371b65282239.png)

**Comment by alannt777** [comment]
I would like to  make a PR for this. Just tell me what to add to it.

**Comment by alannt777** [comment]
This is what PowerToys uses it for:

![image](https://user-images.githubusercontent.com/67918878/96535893-7ae05b80-12b0-11eb-944d-7d39d4e37819.png)

**Comment by alannt777** [comment]
You can also stop people from using blank issue template if you want to:

![image](https://user-images.githubusercontent.com/67918878/96538121-6a7eaf80-12b5-11eb-820f-ccf816e097c5.png)

**Comment by alannt777** [comment]
I am going to work on this. I will add or remove as changes are requested in PR
