### ISSUE TITLE
VT underline, overline, strikethrough, hyperlink are not high-DPI aware

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#7954]
In Windows Terminal 1.4, the rendering of VT attributes such as underline, double underline, overline, crossed and hyperlinks are always 1px thick and hyperlink dashes are always 3;1 pixels regardless of the screen DPI and UI scaling factor.

This makes it very think, and the dashes of hyperlink almost invisible on high DPI displays such as the Surface Book 2 (which defaults at 200%).

It would be more consistent and more readable if the lines and dashes were also scaled according to the scaling factor or to the current font size.

See the following screenshot on Surface Book 2:
`echo -e "\e[4mUnderline\e[24m \e[21mDblUL\e[24m \e[53mOverline\e[55m \e[9mCrossed\e[29m \e]8;;http://www.example.com\aHyperlink\e]8;;\a"`
![image](https://user-images.githubusercontent.com/25664275/96336018-f35ed680-107c-11eb-8206-c5ee38eee093.png)

**Comment by j4james** [comment]
They are definitely DPI aware. It's just that they have a minimum size of a pixel (so they're not invisible at low resolution), and some fonts are styled to use a very narrow width that is only 1 pixel even when the DPI is high. So while that would technically be less than a pixel at a lower DPI, it gets rounded up to 1, and thus there doesn't appear to be any difference between the two.

I know Cascadia is particularly thin - Consolas uses a more reasonable width in my view. But note that if your font size is small, that's also more likely to result in an underline that could still be 1px at high DPI.

**Comment by DHowett** [comment]
This one is operating by design. Thanks for filling in the details @j4james! :smile:

**Comment by PhMajerus** [comment]
Just for reference, this was an issue with the Cascadia font (https://github.com/microsoft/cascadia-code/issues/395) and got resolved in Feb 2021 releases with the new font version.
