### ISSUE TITLE
No -k or /k (such as the one in %comspec%) command to keep terminal open after script finishes

### ISSUE THREAD

**Issue by robbydaigle** [microsoft/terminal#7956]
# Description of the new feature/enhancement

When trying to create a windows shortcut to open up a dev environment, It does not appear that there is an argument to keep the terminal open after the target script has been run. This would be very useful for devs who use windows shortcuts for dev environments. 

# Proposed technical implementation details (optional)

A command line argument such as --keep-open or -k to keep the terminal open after target script finishes.

**Comment by robbydaigle** [comment]
Sorry I totally messed up the description. Fixing.

**Comment by DHowett** [comment]
Terminal runs other shells; it is not in/of itself a command shell.

You’re free to use `wt %comspec% /k whatever` to run your `%comspec%` inside WT and keep it running after it runs the specified commands. :smile:
