### ISSUE TITLE
Terminal fails to refresh/display tabs after VM resumes from suspend

### ISSUE THREAD

**Issue by strw22** [microsoft/terminal#7957]
# Environment

```none
Windows build number: 10.0.19041.388
Windows Terminal version (if applicable): 1.3.2651.0

Any other software? 
Parallels Desktop 16.0.1 VM running Win10
```

# Steps to reproduce

Launch Windows Terminal
Open a few tabs
Run any command
Suspend the VM:  Go to Parallels Desktop (MacOS app), and choose Action -> Suspend
Resume the VM
The display does some sort of redraw
Windows Terminal renders the content in the active tab (good)
Entire titlebar/tabs region is gray (bug)

Typing into the content area doesn't result in a refresh.
Pressing Ctrl-Tab to switch tabs fixes the issue, but is annoying.
Resizing the Terminal window also fixes the issue.

# Expected behavior

Tabs should refresh when VM resumes

# Actual behavior

Entire tab area is gray.

Let me know if there is some tool I can run (I tried Spy++) to see what messages the Terminal window is receiving during suspend/resume.

<img width="950" alt="Terminal-BlankTabArea" src="https://user-images.githubusercontent.com/53409149/96353251-2013ed80-107f-11eb-8364-2ad1b66fd589.png">

**Comment by DHowett** [comment]
Hmmmm. This seems like the inverse issue from #3446. Nobody on the team has ever seen _either_, which is somewhat alarming.

I'm concerned that this is a platform issue (in XAML islands.)

I wonder what's happening when Parallels resumes the VM.

**Comment by DHowett** [comment]
This is gonna be a weird question, but if you run `c:\windows\system32\PerceptionSimulation\PerceptionSimulationInput.exe` and then suspend/resume... does its UI do the same thing as Terminal?

**Comment by strw22** [comment]
Good call -- yes, I see the same issue with PerceptionSimulationInput.exe 
Screenshot attached. 
<img width="592" alt="Parallels_Resume_ PerceptionSimulationInput exe" src="https://user-images.githubusercontent.com/53409149/96960254-c8c6b080-14b6-11eb-8451-19253da545d3.png">

When Parallels resumes, the display goes blank for a moment, as if it's restarting the video card driver.

**Comment by DHowett** [comment]
Thanks! I filed this upstream on XAML!

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/3472
