### ISSUE TITLE
Disabling Video Output on High Refresh Rate Monitor

### ISSUE THREAD

**Issue by cweinst1** [microsoft/terminal#7958]
# Environment
Microsoft Windows [Version 10.0.18363.1139]
Windows Terminal v.1.3.2651.0

# Steps to reproduce
Open Windows Terminal whiile using High Refresh Rate (HRR) Monitor.
(My monitor is an Acer XF250Q, which is 1080p and 240 Hz)

I have tried turning off G-Sync Compatibility, limiting my HRR monitor's application refresh rate to < 60 Hz, and turning off other unnecessary settings in the Nvidia Control Panel, with no luck. Furthermore, I have tried switching from display port to HDMI, and switched around cables and ports.

# Expected behavior
The application opens like normal and without impacting any video output.

# Actual behavior
The application opens, but my HRR monitor (I am using two monitors) goes black as if disconnected. Changing the focus to another windows (whether by ALT-TABing or moving my mouse to my second monitor and clicking away) restores the output to my HRR monitor. Refocusing on WT causes my HRR monitor's display to turn black again.

**Comment by DHowett** [comment]
What video card and driver version are you using? WT isn't doing anything it's not supposed to with its graphics pipeline, so this is rather concerning.

**Comment by cweinst1** [comment]
> 
> 
> What video card and driver version are you using? WT isn't doing anything it's not supposed to with its graphics pipeline, so this is rather concerning.

I have an NVIDIA 2070 with driver version 456.38.

I have experienced this exact issue before with some old games and a very old media player once, so I always thought it was a compatibility issue between the older applications and the newer NVIDIA drivers. However, this was the first time I have not been able to fix the issue by manually setting the application's FPS to 60 in the NVIDIA control panel.

**Comment by zadjii-msft** [comment]
I'm gonna summon @miniksa and @lhecker to this thread, since they've got a bit more experience with weird rendering edge cases, and might have a vague idea of what to investigate next

**Comment by lhecker** [comment]
@cweinst1 Do you have G-Sync for windowed applications enabled? Does your setting look like this?
![image](https://user-images.githubusercontent.com/2256941/89332321-80f07400-d693-11ea-9434-4ae6eb6a1142.png)

I've had such issues before and it was caused by a too long Mini-DP cable. But you said that you swapped the cable for a HDMI one, which should rule that out... My gut feeling is that this is an issue with your particular monitor, but obviously I can't prove that.

**Comment by cweinst1** [comment]
@lhecker 
Sorry for the long delay, I have been busy with finals and overlooked this email. 

Yes, I do have G-Sync for Windowed Applications enabled; I can disable this and see if this solves the issue.

I was worried that it was my particular monitor, though I don't have a second HRR monitor to check. Hopefully this resolves the issue. Thank you!
