### ISSUE TITLE
"Encountered errors while loading user settings" after machine reboot

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#7965]
Immediately after reboot, I often get this message when I launch Terminal (v1.3.2651.0) - It also does not detect my WSLv1 Ubuntu 18.04. When I close and relaunch it, everything works. It's as if it genuinely cannot load the profile file. Are there any log files that I could provide to you?
![image](https://user-images.githubusercontent.com/1041752/96487880-821a5180-123d-11eb-9fa1-868d86d01864.png)

**Comment by zadjii-msft** [comment]
Thanks for reporting this - at the end of the day, this is the same root cause as #7199, so we can continue the discussion over there. Fundamentally, this issue is being caused by your default profile being a WSL profile, and WSL doesn't reliably report the list of installed distros 😕 

/dup #7199

**Comment by vadimkantorov** [comment]
Duplicate of https://github.com/microsoft/terminal/issues/6160?

It could be that just CPU is busy: I'm loading a big Chrome process at the same time. But even if CPU is buys / WSL is slow to respond, it should not throw this error or discard a profile from the list (even if WSL is slow or does not respond). Maybe it should ask the user if I want to retry or maybe show some welcome "no terminal opened" screen instead (e.g. Speed Dial like in browsers)

**Comment by zadjii-msft** [comment]
OH MY GOSH THERE'S A BETTER DUPE! Thanks for finding that!
