### ISSUE TITLE
Close Menu, "Close other tabs

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#7968]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Uh #7969?

**Comment by DHowett** [comment]
It turns out that when i fat-fingered ctrl shift enter i _submitted the issue form and opened it in a new window_ (?!?)
