### ISSUE TITLE
Close Menu, "Close other tabs" and "Close tabs to right" always operate on tab index 0, are always enabled

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#7969]
I'm not sure if this is an issue in main or an issue in feature/settings-ui.

/cc @mpela81

**Comment by mpela81** [comment]
Looks fine on master, maybe it wasn't fully merged onto the feature branch?

![immagine](https://user-images.githubusercontent.com/1140981/96576414-7331ae80-12d2-11eb-9880-fdbb78ce0ee1.png)

**Comment by DHowett** [comment]
Excellent. In that case, it's on me :smile:

**Comment by zadjii-msft** [comment]
Uh oh, I'm seeing this on the  1.5.2941.0 selfhost the team is working with as well.

**Comment by DHowett** [comment]
Fortunately, that is built off feature/settings-ui!

**Comment by DHowett** [comment]
Looks like this was @carlos-zamora's merge commit

```
commit 0ce05b5405df96a829d4756f44e4b1daffe28083
Merge: e00275232 743283e43
Author: Carlos Zamora <cazamor@microsoft.com>
Date:   Fri Oct 16 12:48:21 2020 -0700

    Merge branch 'master' into feature/settings-ui
```

Carlos, this commit lost the call to `_EnableCloseMenuItems` in the various tab implementations that controlled whether the menu items were enabled/disabled.
