### ISSUE TITLE
cant edit the settings

### ISSUE THREAD

**Issue by JohnnyXP64** [microsoft/terminal#7975]
out of the box installation in a windows 10 with vs2017 and the settings menu is trying to open a file i guess with my vs to edit, and i jsut get vs17 opening in a blank enviroment. what is the file and where is located and why do you allow it to open with the default editor when clearly is not?

**Comment by alannt777** [comment]
Have you tried opening the file using another editor other than Visual Studio?

#### **How to change your default editor**

![change-default-json-editor](https://user-images.githubusercontent.com/67918878/96597531-962c8480-130b-11eb-973a-046bff4061ff.gif)

<hr>

Try using something like Visual Studio Code (the JSON schema will give you IntelliSense on possible parameters in Terminal Settings). If you don't want to install VS Code, use another text editor of choice

**Comment by zadjii-msft** [comment]
There currently isn't a settings UI - opening the settings file will open in whatever your default editor for `.json` files is. 

/dup #1586
/dup #1460
