### ISSUE TITLE
problem with pin to taskbar

### ISSUE THREAD

**Issue by swarnakrishnan** [microsoft/terminal#7976]
# Environment

```none
Windows build number: Windows 10 ver 2004 build 19041.208
Windows Terminal version (if applicable): 1.3.2651.0

```

# Steps to reproduce

After installing, Open the terminal and then pin it to taskbar, Later when you unpin it from the taskbar the app closed but a space is created in the taskbar.

# Expected behavior

Get unpin normally.

# Actual behavior

![Report](https://user-images.githubusercontent.com/48626335/96596894-d8a19180-130a-11eb-91b0-dadd032bea90.gif)

**Comment by zadjii-msft** [comment]
That's the darndest thing, I can't repro this at all. Does this persist across a machine reboot?

**Comment by v1peractual** [comment]
I am currently having this issue. Could I do something to help debug?

**Comment by v1peractual** [comment]
Yes, it persists across reboots.

**Comment by JFLarvoire** [comment]
I have the same problem with the Windows Terminal Preview 1.11.2421.0.

Other annoying symptoms possibly related:
I have two links to start Windows Terminal Preview:

- Apps / Windows Terminal Preview
- Programs / Windows System / Windows Terminal Preview

Both allow starting the terminal preview. But...

* The first one displays the icon correctly on the task bar.
  But if I pin it, I can't start a new instance from the task bar.
  The error popup says:
  Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

* The second one displays a blank icon on the task bar.
  If I pin it, I can start new instances from the task bar.

In both cases, unpinning the icon leaves a blank spot.

I tried uninstalling and reinstalling WTP, but this does not resolve the issue.
My system in running Windows 10.0.19044.123, with all updates installed.
