### ISSUE TITLE
Optimize images across the repo

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7979]
# Description of the new feature/enhancement

Optimize images added from PRs automatically to reduce image size while retaining image quality.  (Looking at https://github.com/microsoft/terminal/pull/7971 in particular). This will help keep the disk size of Windows Terminal down when updating or adding new images.
# Proposed technical implementation details (optional)
Add the yaml file. Also, if this is accepted, I have another image optimization PR I can do to optimize our current images (reducing the overall image size by 23% for this repo) which I'd prefer to do prior to adding this Action as the images were optimized from separate tooling and don't want any corruption added to the images (it does detect if an image doesn't require optimization).

**Comment by DHowett** [comment]
I'm interested in optimizing the existing ones, but I don't think it's necessary to add another action that enforces it.

For the terminal app resource directories, it looks like we save a grand total of ~42kb/flavor or about 11%. Where are you seeing the greatest savings?

**Comment by WSLUser** [comment]
So the Action can't handle svg files so it skips those due to it's dependencies but using ImgBot, all png and svg files had a file reduction size. This is mostly to help reduce the footprint for hosts that don't have a bunch of storage available where even a few MB might matter. Compared to other things, it's probably not the biggest change that can help but it's a quick easy one. I did a visual inspection from several types of devices to verify the images looked the same.

**Comment by WSLUser** [comment]
If you're not interested in adding the Action, I can repurpose this issue for general image optimization and link the PR against it.
