### ISSUE TITLE
Alias for commands

### ISSUE THREAD

**Issue by edoardottt** [microsoft/terminal#7980]
# Description of the new feature/enhancement

I've used Linux for 2 years. Now switched back to Windows. Is there a similar way to define aliases like in Linux?
In Linux I can go in .bashrc file and append a line like `alias command=ls -la` and when I type `command`
in the terminal, it executes `ls -la` wherever I am in the folder structure.

# Proposed technical implementation details (optional)

I don't have any idea... Maybe I can insert the path of the executable in the PATH variable?
I don't know if this is a good idea.

Thanks by the way for all the work you do. 

Good work!, edoardottt

**Comment by DHowett** [comment]
Yes. If you're using PowerShell, look into `nal` or `New-Alias`. If you're using Command Prompt, check out `doskey`.

**Comment by DHowett** [comment]
Thanks!
