### ISSUE TITLE
Context menu on tabs doesn't close when clicking in the title bar

### ISSUE THREAD

**Issue by jroessel** [microsoft/terminal#7988]
# Environment

```none
PS> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal
Version: 1.3.2651.0
```

# Steps to reproduce

1. Right click on a tab in Windows Terminal to open the context menu.
2. Click somewhere else to close it again.

# Expected behavior

The context menu closes, regardless of where the click in step 2 goes.

# Actual behavior

The context menu closes in pretty much all places, even different applications (presumably because losing focus also closes it), but doesn't close when clicking the title bar of WIndows Terminal. It does close when clicking controls in the title bar, though, even the default window buttons in the upper right.

**Comment by zadjii-msft** [comment]
Well that's the darndest thing. I bet this is the same thing as #2028 (which was fixed in #2438), but with the tab context fylout menu, not the new tab flyout.

**Comment by jroessel** [comment]
Coming only from higher-level UI toolkits in managed code I always thought the popup was somewhat responsible for closing itself by getting mouse capture and reacting to clicks elsewhere and closing itself. But perhaps that's the more complicated or otherwise undesirable option in native Win32. No actual idea, though :)

**Comment by DHowett** [comment]
> Coming only from higher-level UI toolkits in managed code I always thought the popup was somewhat responsible for closing itself by getting mouse capture and reacting to clicks elsewhere and closing itself. But perhaps that's the more complicated or otherwise undesirable option in native Win32. No actual idea, though :)

You're totally right, @jroessel! We're in the unfortunate position of using two different UI frameworks at the same time (XAML and Win32). To get our titlebar draggable while still being able to theme it like the rest of the application, we had to eat mouse clicks in a region at the top of the window. Doing that obscures the click target that would dismiss the flyout menu :smile:
