### ISSUE TITLE
NiceToHave feature - "on top of all the windows"

### ISSUE THREAD

**Issue by werejaguar** [microsoft/terminal#7989]
Hi, WinTerminal dev team! I think it will be useful to add "on top of all the windows" feature. Thx a lot!

**Comment by zadjii-msft** [comment]
We actually already have this feature - it's called "always on top" mode. Check out the [docs here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#always-on-top-mode). You can also [toggle this mode](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#toggle-always-on-top-mode) with a keybinding or command in the command palette.

See also #6903
