### ISSUE TITLE
:tada:This issue was addressed in #6100, which has now been successfully released as `Windows Terminal Preview v1.1.1671.0`.:tada:

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/terminal#7990]
> :tada:This issue was addressed in #6100, which has now been successfully released as `Windows Terminal Preview v1.1.1671.0`.:tada:
> 
> Handy links:
> * [Release Notes](https://github.com/microsoft/terminal/releases/tag/v1.1.1671.0)
> * [Store Download](https://www.microsoft.com/store/apps/9n8g5rfz9xk3?cid=storebadge&ocid=badge)
> 
> _Originally posted by @msftbot[bot] in https://github.com/microsoft/terminal/issues/1060#issuecomment-646178548_

Not work for me:

![image](https://user-images.githubusercontent.com/4510984/96726775-e9263a80-13e4-11eb-8e1f-fa4901b35400.png)

**Comment by zadjii-msft** [comment]
I'm guessing that you're right clicking in the "background" of the directory in explorer. If you actually click on a folder in explorer, the entry will appear. This is an issue that' being tracked by #6414 - please follow that thread for more information.

/dup #6414
