### ISSUE TITLE
Allow build artifacts from Azure DevOps to be downloaded

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#7992]
# Description of the new feature/enhancement

I follow some issues on this repo closely, and when something that interests me is done I build the terminal myself to start using it. I've done it since the code was first published on Github. Sometimes I find issues and then report them back here. I'm aware of the release channels, but I like to be able to access features faster than they can deliver.

But pulling from Github and building takes time. I'd rather be able to download a compiled installation package, like the one produced from a build from Visual Studio, it would save me time and the project storage space (several GBs). It seems you are already producing those packages on your [CI build on AzDO](https://dev.azure.com/ms/terminal/_build?definitionId=136&_a=summary&repositoryFilter=68&branchFilter=2915). But anonymous users on AzDO (like me) can't download them.

# Proposed technical implementation details (optional)

Allow the artifacts produced from the CI build on the master branch to be downloaded.

Related to: #774 and #7925

**Comment by giggio** [comment]
Ok, makes sense. Thanks, @DHowett.
@clairernovotny are you still running that build train?

**Comment by clairernovotny** [comment]
I haven't been running a nightly build in quite some time. It broke due to some build script changes and then never fixed it. 

If there's reasonable interest in having a nightly, I can have have it fixed again. Better yet, I'd take a PR that fixes it.

**Comment by clairernovotny** [comment]
The repo is here https://github.com/clairernovotny/Terminal
