### ISSUE TITLE
Recognizing the new terminal as an application

### ISSUE THREAD

**Issue by Bios-Marcel** [microsoft/terminal#7995]
Depending on what feature set is a available on a terminal, an application might want to act differently. For example, using emojis and such should be avoided in the old windows terminal. Is there some easy way, that applications can use to know they are running on the new version of the windows terminal? Whether this is possible or not, it would be great to mention this somewhere in `/doc` I assume.

**Comment by Bios-Marcel** [comment]
Somebody just hinted me that the variable introduced with https://github.com/microsoft/terminal/pull/897 (`WT_SESSION`) could probably be used for this.

**Comment by DHowett** [comment]
Applications should not attempt to detect whether they're running in WT. Any assumption they make will be invalidated with time. Any application that attempts to ascribe specific behavior to Windows Terminal will be wrong and cause unnecessary vendor lock-in when it inevitably fails to work on Hyper, Alacritty, Mintty, and ConEmu even though those terminals support all the same features.

> For example, using emojis and such should be avoided in the old windows terminal.

This is only true today, and will not be true once the rendering engine in this repository converges with the one in Windows.

All of the code in this repository that pertains to the inbox console host eventually goes into Windows, and goes out into the "old" windows "terminal."

/dup #1060.

**Comment by DHowett** [comment]
Sorry, I meant /dup #1040!
