### ISSUE TITLE
Color Setting not working

### ISSUE THREAD

**Issue by huangzonghao** [microsoft/terminal#8001]
I am trying to change the color scheme of the terminal. But it seems that windows terminal is not responding to any of my settings related to color in settings.json, except for foreground, background and cursor color. No matter color scheme I entered in the settings file, the terminal would simply stay at the default color scheme, even after relaunch, reboot, reinstall. Plus setting the color directly in the profiles is not working as well. Is there something else in my system that might affect the behavior of windows terminal? or how could I possibly get it right?

My settings.json
```
{
    // "startOnUserLogin": true,
    "launchMode": "maximized",
    "showTabsInTitlebar": true,
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": [],
    "useTabSwitcher": false,
    "copyFormatting": false,
    "copyOnSelect": false,
    "defaultProfile": "{-removed-}",
    "profiles": {
        "defaults": {
        },
        "list": [
            {
                "colorSheme": "PaperColor",
                "cursorShape": "filledBox",
                "cursorColor": "#000000",
                "foreground": "#000000",
                "background": "#eeeeee",
                "selectionBackground": "#000000",
                "fontSize": 11,
                "fontFace": "Menlo",
                "fontWeight": "thin",
                "guid": "{-removed-}",
                "hidden": false,
                "name": "Ubuntu",
                "scrollbarState": "visible",
                "source": "Windows.Terminal.Wsl",
                "suppressApplicationTitle": false,
                "closeOnExit": "always",
                "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\huangzonghao",
                // "tabTitle": "bash",
            },
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{-removed}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{-removed-}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false,
            },
            {
                "guid": "{-removed-}",
                "hidden": true,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [
        {
            "background": "#eeeeee",
            "black": "#000000",
            "blue": "#005faf",
            "brightBlack": "#1c1c1c",
            "brightBlue": "#005faf",
            "brightCyan": "#0087af",
            "brightGreen": "#008700",
            "brightPurple": "#d70087",
            "brightRed": "#af0000",
            "brightWhite": "#e4e4e4",
            "brightYellow": "#000000",
            "cursorColor": "#005faf",
            "cyan": "#0087af",
            "foreground": "#000000",
            "green": "#008700",
            "name": "PaperColor",
            "purple": "#d70087",
            "red": "#af0000",
            "selectionBackground": "#FFFFFF",
            "white": "#e4e4e4",
            "yellow": "#000000"
        }
    ]
}
```

**Comment by High-Flyer** [comment]
TBH I dont know anything. what difference i seen is name of the scheme. consider adding
"name": "PaperColor",
"background": "#eeeeee",

**Comment by huangzonghao** [comment]
The name is actually in the scheme, it is under `"green": "#008700"` and above `"purple": "#df0087"`, it was VS that automatically adjusted the order of entries and hide the name in the color definitions. You can see it with a quick search.

**Comment by High-Flyer** [comment]
// Make changes here to the powershell.exe profile.
                "guid": "{-removed-}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
		"coloScheme": "PaperColor" << this was missing 
am sorry thats the only problem i saw i loaded ur jason file to my terminal no errors but unfortunately its stays default.

**Comment by DHowett** [comment]
Yes, you did not set `"colorScheme": "PaperColor"`.

If you add that, does it work?

**Comment by huangzonghao** [comment]
Oh sorry, I was talking about the Ubuntu proflie, that is the first one in the profiles list. The color scheme was indeed set. (and the settings for powershell doesn't work as well even if I added that `colorScheme` entry.
Sorry about the confusion here.
```
            {
                "colorSheme": "PaperColor",
                "cursorShape": "filledBox",
                "cursorColor": "#000000",
                "foreground": "#000000",
                "background": "#eeeeee",
                "selectionBackground": "#000000",
                "fontSize": 11,
                "fontFace": "Menlo",
                "fontWeight": "thin",
                "guid": "{-removed-}",
                "hidden": false,
                "name": "Ubuntu",
                "scrollbarState": "visible",
                "source": "Windows.Terminal.Wsl",
                "suppressApplicationTitle": false,
                "closeOnExit": "always",
                "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\huangzonghao",
                // "tabTitle": "bash",
            },
```

**Comment by High-Flyer** [comment]
"colorSheme": "PaperColor", > spelling is wrong colorScheme: "PaperColor"
"cursorShape": "filledBox",
"cursorColor": "#000000",
"foreground": "#000000",
                "background": "#eeeeee",
                "selectionBackground": "#000000",
                "fontSize": 11,
                "fontFace": "Menlo",
                "fontWeight": "thin",
                "guid": "{-removed-}",
                "hidden": false,
                "name": "Ubuntu",
                "scrollbarState": "visible",
                "source": "Windows.Terminal.Wsl",
                "suppressApplicationTitle": false,
                "closeOnExit": "always",
                "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\huangzonghao",
                // "tabTitle": "bash",
            },

**Comment by huangzonghao** [comment]
OH man, I was an idiot. Going to bed early is a good habit which I failed to obey. Thanks buddy :)
