### ISSUE TITLE
WT command line args not working for powershell core

### ISSUE THREAD

**Issue by smezger** [microsoft/terminal#8003]
# Environment

```none
Windows build number: 10.0.18363.0 
Windows Terminal version (if applicable): 1.4.2652
Powershell Core: 7.0.3
```

# Steps to reproduce
*    wt -p PowerShell -d D:\git\dir\repoName\ --title mytitle

# Expected behavior
* Opens wt with powershell profile with title "mytitle" and in the directory "D:\git\dir\repoName\"

# Actual behavior
* Opens wt with powershell profile with title only showing up for a a second before going to dir name and with the defualt directory specified in mytitle" and in the directory specified in settings.json

_Note: doing the same with command prompt works as expected_

**Comment by DHowett** [comment]
Sorry, I’m having trouble understanding what you’re seeing. Would you mind sharing a screen recording? The “xbox game bar” (Win+G) can take one in a pinch.

**Comment by smezger** [comment]
![WindowsTerminal](https://user-images.githubusercontent.com/19730006/96835263-a5165280-1443-11eb-8013-d275af10a32d.gif)
@DHowett : Thanks for the quick reply! I hope the gif explains it a little bit better.

**Comment by smezger** [comment]
@DHowett I figured out the directory part of this was due to a command in the $PROFILE of ps core, but tab titles does not seem to work for ps core. --> I've opened a new bug for this #8005 and close this one.
