### ISSUE TITLE
Settings Button

### ISSUE THREAD

**Issue by MMS2005** [microsoft/terminal#8004]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

HI There, I Was Expecting the Settings Button to Open Some Sort of Settings Stuff, But It Did not Do Anything.

# Actual behavior

There's no Response From the Terminal

**Comment by j4james** [comment]
The _Settings_ menu just opens the `settings.json` file in whatever application you've got configured as your default `.json` editor. If it's not doing anything, that probably means you haven't got an application set as the default editor. For more info see issue https://github.com/microsoft/terminal/issues/7975#issuecomment-712880743.

**Comment by zadjii-msft** [comment]
The settings button will open the settings file (`settings.json`) in whatever your default editor for json files is configured to be. If there's not one already set, the OS will take a little while before displaying a "what application would you like to open this file in?" dialog. 

/dup #1564 
/dup #442
