### ISSUE TITLE
tab title only showing up short for powershell core

### ISSUE THREAD

**Issue by smezger** [microsoft/terminal#8005]
# Environment

```none
Windows build number: 10.0.18363.0 
Windows Terminal version (if applicable): 1.4.2652
Powershell Core: 7.0.3
```

# Steps to reproduce
* Either specify a title in settings.json `("tabTitle": "PS Core")` or through command line argument (`--title PSCore`) and open a new tab with that

# Expected behavior
* Tab title is persistent

# Actual behavior
* title is only shown shortly before it changes to the directory name
refer to gif below: ![WindowsTerminal](https://user-images.githubusercontent.com/19730006/96835263-a5165280-1443-11eb-8013-d275af10a32d.gif)

**Comment by DHowett** [comment]
If I had to guess, there’s code in your powershell profile.ps1 that sets `$Host.UI.RawUI.WindowTitle`. By default, “title” is advisory and provided to the shell as additional information it can use to determine what you want the title to br. If you want terminal’s “title” to _win_ over the application’s title in all circumstances, you’ll want to look into `suppressApplicationTitle` (profile setting, boolean).

Personally, I just make my shells set their titles. It lets me use different titles for different remote machines without having to manage fiddly bits of local configuration.

**Comment by smezger** [comment]
@DHowett Thanks for pointing this out, solved it for me! 👍  
 And also thank you for your always fun to read release notes 😄

**Comment by DHowett** [comment]
> always fun to read

Hey, thanks! I appreciate that 😄
