### ISSUE TITLE
Way to lock/pin tabs

### ISSUE THREAD

**Issue by Nosamdaman** [microsoft/terminal#8007]
# Description of the new feature/enhancement

I think a feature that would allow a user to "lock" a tab or whole window could be extremely useful. If I'm running a particularly long command/job in a remote session for example, being able to lock that tab so that no input could be sent to the tab would help prevent accidental cancelations if the window regained focus without me knowing it. It would then also be nice if the close window/tab button popped up a warning or confirmation dialogue when attempting to close the tab/window in question regardless of the `confirmCloseAllTabs` option when a locked or pinned tab is present. Using this feature in combination with the always on top mode would be a great way to ensure that you could monitor the progress of jobs without having to worry about accidentally interfering with them.

# Proposed technical implementation details (optional)

**Comment by alannt777** [comment]
dup of #5969

**Comment by Nosamdaman** [comment]
Ah, I didn't see that when writing this issue. Though I'd still argue that the locking of inputs makes this at least somewhat a separate feature.

**Comment by alannt777** [comment]
That is a dup of #6981

**Comment by Nosamdaman** [comment]
So it is. Thanks, I guess I was just searching with the wrong keywords.
