### ISSUE TITLE
[COOKED_READ] Ctrl+Backspace does nothing if the input length limit has been reached

### ISSUE THREAD

**Issue by SecondFlight** [microsoft/terminal#8008]
# Environment

```none
Windows build number: 10.0.18363.1139
Windows Terminal version: 1.3.2651.0
```

# Steps to reproduce

1. Open a new terminal tab
2. Type or paste text into the prompt until the length limit is reached.
3. Press Ctrl+Backspace.

# Expected behavior

Some text is removed.

# Actual behavior

No text is removed:

![2020-10-22_12-00-30](https://user-images.githubusercontent.com/6700184/96899085-76f23c00-145e-11eb-8d06-bfdbf95e1e3f.gif)

**Comment by zadjii-msft** [comment]
What shell are you using? `cmd`, `powershell`, `pwsh` (powershell core), some WSL shell like `bash`, `zsh`, `fish`...?

**Comment by SecondFlight** [comment]
Sorry! I'm using my default, which is `cmd`.

**Comment by alannt777** [comment]
I was unable to repro this issue using cmd in Windows Terminal Preview 1.4.2652.0:

![test-cmd](https://user-images.githubusercontent.com/67918878/96893680-96ae5200-14a8-11eb-805c-e4f0d707045b.gif)

> My prompt look different because I customized it using a bat file

**Comment by alannt777** [comment]
But there is a weird problem with Ctrl+Backspace in VS Code's terminal:

![vscode-terminal-problem](https://user-images.githubusercontent.com/67918878/96895182-c6118e80-14a9-11eb-9738-df563dda2854.gif)

I know that it is not really relevant to this repo but just mentioning

**Comment by SecondFlight** [comment]
Hi @alannt777, thanks for investigating. Is your length limit set artificially low? The input size limit needs to be reached for this bug to be reproduced; see step 2.

Here's how it looks on my setup:

![2020-10-22_12-00-30](https://user-images.githubusercontent.com/6700184/96899085-76f23c00-145e-11eb-8d06-bfdbf95e1e3f.gif)

**Comment by alannt777** [comment]
Oops. I should have read the description properly. But I don't think anyone would use a command (and its arguments) that would be this long.

**Comment by TaeckSeung** [comment]
I think this is default problem in CMD, not in Terminal.
Cause it happened as same on origin CMD and CMD on Powershell too.
This problem is could solved with press backspace onetime and then CTRL+Backspace is working well.
I guessing cursor is over range with full length, so couldnt flush command on last.

**Comment by DHowett** [comment]
Interesting. CMD's line editor is actually part of the console host, so this issue is valid here. Thanks!
