### ISSUE TITLE
When I run 5-9 tabs Windows terminal work very slowly 

### ISSUE THREAD

**Issue by volerster** [microsoft/terminal#8009]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Could you give us any more details? What are you running in those tabs? What does your `settings.json` look like? What version of the Terminal? Is input laggy, or is there a delay when opening tabs, or is the output slower than expected? 

We can't really help with a blank issue.

**Comment by volerster** [comment]
I open tabs and run very simple program - ping 
https://yadi.sk/i/KzYK0sP4uneS0Q

I have PC on I7, 16gb, ssd 512
https://yadi.sk/i/XFzzMF_cLgml7w

Why you use powershell for simple command?

**Comment by DHowett** [comment]
There isn't enough information in this bug for us to help you, I'm sorry.
You can configure your default shell to be Command Prompt/cmd.exe if you do not want the resource overhead of PowerShell.
