### ISSUE TITLE
Splitting Terminals

### ISSUE THREAD

**Issue by ismail1147** [microsoft/terminal#8014]
# Description of the new feature/enhancement
There could be a feature allowing to split terminals, rather than the current tabs functionality like your other products like Visual Studio Code or as is Linux Terminator so that user can see other terminals at the same time without having to change the tab.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Wha? You can totally do this today. Use alt+shit+plus or alt+shift+minus and [read our docs](https://docs.microsoft.com/windows/terminal).

![image](https://user-images.githubusercontent.com/189190/96921128-ef5afc00-1462-11eb-9273-54c16d280595.png)
