### ISSUE TITLE
Unable to type anything in Windows Terminal

### ISSUE THREAD

**Issue by High-Flyer** [microsoft/terminal#8015]
USB keyboard working fine in notepads/ cmd / powershell.
but unable to type anything in Windows terminal.
nothing is changed both version from microsoft store tried regular and preview no change.
tried to install windows terminal from chocolatey no change again.
tried to switch powershell 4.0 3.0 2.0 no change.
on system i have chocolatey scoop installed both are with gui interface.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Sounds like #4448. Can you try one of the workarounds in that thread?

**Comment by High-Flyer** [comment]
sure i will go through that thread thank you.

**Comment by High-Flyer** [comment]
Thank you Enabling "Touch keyboard and and handwriting panel service" to automatic and rebooting solved the problem for me.

**Comment by DHowett** [comment]
I'm glad! Thanky you!
