### ISSUE TITLE
[host] If a line is exactly the width of the buffer and you increase the buffer width, it will wrap incorrectly resize reflow

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#802]
This is another one that needs #796 before it can be changed and may or may not be related to #797.

![image](https://user-images.githubusercontent.com/18221333/57736706-d3441000-765d-11e9-9cbd-8348321f7751.png)

> See the line with "OpenConsoleFullPDB.pdb" on it. 
> 
> 1. execute `dir`.
> 2. pick a line you like. Resize the window so that the line completely fills the width of the buffer, with no spaces on the right.
> 3. execute the same `dir` command. That line you picked should exactly fill one line.
> 4. Increase the width of the window. See that the line below the line you picked has now wrapped up to the previous line.
> 
> 
> Repros with both `dir` and `ls -lA`, so it's not WSL/VT specific.

**Comment by ExE-Boss** [comment]
This is&nbsp;also reproducible in&nbsp;PowerShell with a&nbsp;[PowerLine&nbsp;prompt](https://github.com/Jaykul/PowerLine) that&nbsp;uses the&nbsp;[Right&#x2011;aligned blocks](https://github.com/Jaykul/PowerLine/blob/master/README.md#right-aligned-blocks) feature.

**Comment by zadjii-msft** [comment]
Hey so this is exactly the same as #3088. I've got way more info in that issue (because I totally forgot about this one), so I'm going to resolve this as a dupe.

/dup #3088
