### ISSUE TITLE
Color scheme has no effect

### ISSUE THREAD

**Issue by MinhHuong** [microsoft/terminal#8021]
# Environment

```none
Windows build number: 10.0.19041.572
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

Open Windows Terminal. I use the Command Prompt profile. Click the caret down button then select Settings to open `settings.json` file. Add `"colorScheme" : "Campbell"` to `"defaults"` to apply the scheme to all profiles.

# Expected behavior

I expect the texts to have different colors.

# Actual behavior

All I see is white texts. Even if I choose different schemes like Tango Light or One Half Dark, the only thing that changes is the background color but no change in text colors. Or did I understand it wrong? Is it how color schemes supposed to work?

![terminal](https://user-images.githubusercontent.com/5687533/96973387-1b848480-1518-11eb-803a-fd369830dc64.PNG)

This seems to work for Powershell (at least I see some colors when typing the command) but not for Command Prompt.

![powershell](https://user-images.githubusercontent.com/5687533/96973385-1aebee00-1518-11eb-8a57-065e8bb38de8.PNG)

**Comment by DHowett** [comment]
Command prompt does not use colors on its own. The color scheme only changes how the colors are presented; it will not add *new* colors.
