### ISSUE TITLE
{ "type": null } in profiles.schema.json violates JSON Schema draft 2019-09 meta-schema

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#8024]
<https://aka.ms/terminal-profiles-schema> redirects to <https://raw.githubusercontent.com/microsoft/terminal/release-1.3/doc/cascadia/profiles.schema.json>, i.e. the raw view of <https://github.com/microsoft/terminal/blob/release-1.3/doc/cascadia/profiles.schema.json>.  That schema uses the <https://json-schema.org/draft/2019-09/schema#> meta-schema:

<https://github.com/microsoft/terminal/blob/327ddd702307952c315b07fc7a815d56fd68f7ba/doc/cascadia/profiles.schema.json#L3>

The `#/definitions/CloseOtherTabsAction` and `#/definitions/CloseTabsAfterAction` schemas have a subschema ` { "type": null }`:

<https://github.com/microsoft/terminal/blob/327ddd702307952c315b07fc7a815d56fd68f7ba/doc/cascadia/profiles.schema.json#L401>
<https://github.com/microsoft/terminal/blob/327ddd702307952c315b07fc7a815d56fd68f7ba/doc/cascadia/profiles.schema.json#L420>

That is not valid according to <https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.1.1>, referenced by <http://json-schema.org/specification-links.html#2019-09-formerly-known-as-draft-8>. The value of **type** "MUST be either a string or an array"; `null` is neither.

`{ "type": "null" }` would be valid according to the meta-schema, but it would not match the documentation <https://docs.microsoft.com/windows/terminal/customize-settings/actions#close-tabs-after-index>, which says that the `index` property is optional but does not say that an explicit `{ "index": null }` is allowed.

The `null` literals were added in <https://github.com/microsoft/terminal/pull/7390>.  Meta-schemas were also discussed in <https://github.com/microsoft/terminal/issues/7683>.

**Comment by KalleOlaviNiemitalo** [comment]
`"default": ""` for the `index` property seems a bit dubious too, as it is not valid against the schema of that property. On the other hand, <http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.2> only recommends validity and does not require it.

**Comment by Don-Vito** [comment]
@KalleOlaviNiemitalo - I don't think that it is that important to forbid `"index": null` (and actually not sure how to do it). But it is definitely a time to make our schema compliant. Issuing a PR.

**Comment by KalleOlaviNiemitalo** [comment]
> I don't think that it is that important to forbid `"index": null` (and actually not sure how to do it).

AFAIK, one would do it like this:

```json
            "index": {
              "type": "integer",
              "description": "Close the tabs other than the one at this index. If no index is provided, use the focused tab's index."
            }
```

If the `"index"` property is not listed in `"required"`, then the object can be valid without having that property. If the lack of property does not mean the same thing as any valid value, then don't specify a `"default"`. That's how I understand JSON Schema, anyway.
