### ISSUE TITLE
Windows Terminal Does not use one language constantly.

### ISSUE THREAD

**Issue by joshuag1000** [microsoft/terminal#8027]
# Environment

Running default and latest build as of today (23/10/2020) (Version: 1.3.2651.0)
Windows Build: 2004
OS Build: 19041.572
Windows 10 Pro

# Steps to reproduce

Install More than one Language Pack

# Expected behavior

Should use default language pack

# Actual behavior

Does not use my windows display language or the highest language pack i have installed.

![image](https://user-images.githubusercontent.com/28513051/97055399-a7c99280-157e-11eb-8925-cab00b954f6e.png)
![image](https://user-images.githubusercontent.com/28513051/97055432-b3b55480-157e-11eb-87bd-55aa0a41a0da.png)
![image](https://user-images.githubusercontent.com/28513051/97055476-cc256f00-157e-11eb-9717-6e2fa0c5d610.png)

**Comment by alannt777** [comment]
dup #5497

**Comment by zadjii-msft** [comment]
Yep, sure is. Thanks for the triage pass @alannt777!

I'd also take a look at some of the other linked issues in that thread - #6029 in particular goes into more details.

/dup #5497
