### ISSUE TITLE
WT does not open in the current folder when typing 'wt' in the File Explorer address bar

### ISSUE THREAD

**Issue by claudiofreda** [microsoft/terminal#8029]
A very common shortcut to open a powershell or cmd window in the current File Explorer folder is to type 'cmd' or 'powershell' into the address bar. This passes the current folder as an argument to the shell, which opens alread cd'd into that folder.

This does not work with windows terminal, and typing 'wt' into the address bar results into opening 'wt' with the user home folder as current directory.

Surprisingly, this even works for WSL prompts.

I argue this is a desirable feature and behaviour and should be introduced to Windows Terminal.

**Comment by obsgolem** [comment]
This feature does exist, it is just not enabled by default. To enable it, add 
```
"startingDirectory" : ".",
```
to your default profile.

**Comment by DHowett** [comment]
Or, you can run `wt -d .`. This has been discussed ina  bunch of places on our repo, and none of the solutions we can offer are quite beloved. :smile:

**Comment by Lycantant** [comment]
> 
> 
> This feature does exist, it is just not enabled by default. To enable it, add
> 
> ```
> "startingDirectory" : ".",
> ```
> 
> to your default profile.



> 
> 
> Or, you can run `wt -d .`. This has been discussed in a bunch of places on our repo, and none of the solutions we can offer are quite beloved. 😄

thanks, it work 😁

**Comment by zadjii-msft** [comment]
@claudiofreda There's commentary in #3547, #878, and the very many linked threads as to why this is the way it is.

**Comment by thedarkfalcon** [comment]
@zadjii-msft you posted links to threads where everyone hates the behaviour. Opening in a users home directory is to prevent it from opening in system32. But always opening in users home directory is worse behaviour in my opinion than opening in the current directory. CMD opens in system32 by default, but also opens in whatever directory you launch it from, this is far preferable in my opinion.

**Comment by avail** [comment]
this only started happening with 1.23.
https://github.com/user-attachments/assets/18eea4e9-dd59-4486-827e-62353607da4a
