### ISSUE TITLE
CTRL C doesn't work properly on gitbash

### ISSUE THREAD

**Issue by shirshak55** [microsoft/terminal#8034]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable): v1.3.2651.0

Any other software? Gitbash
```

# Steps to reproduce

# Expected behavior
Ctrl C works on gitbash when i run tsc --watch  (tsc is microsoft typescript compiler) . But in windows terminal CTRL + C doesn't work it only response once typescript --watch is fully ready. I would like to ctrl +c before tsc --watch  command start to be ready.

Its not just this app but most cli apps i use have similar issue. 

# Actual behavior

When i do ctrl + c it stucks for few moment till command line is fully ready and only it interrupts the program.

**Comment by DHowett** [comment]
Does this happen outside of Windows Terminal?

It is possible that the program is not ready to respond to ^C yet. This is a normal thing.

**Comment by shirshak55** [comment]
No it doesn't happen in gitbash
but it happens in windows terminal

**Comment by svn-dys** [comment]
I am also seeing this through my gitbash tab. Cannot close out a chrome instance with "CTRL + C".

Version: 1.3.2651.0

**Comment by shirshak55** [comment]
Its so annoying. Windows terminal responds like after 20 seconds :(

**Comment by zadjii-msft** [comment]
Is the command that you're trying to send `^C` to actively outputting text when you're pressing <kbd>Ctrl+C</kbd>?

This is going to sound insane, but what happens if you do something like hit <kbd>Ctrl+C</kbd>, then resize the window a little bigger or smaller (at least one row/column different in size)? Does that cause the `^C` to get handled immediately?

**Comment by shirshak55** [comment]
@zadjii-msft no windows terminal doesn't show ^C . The issue is hisen bug. Sometime `Ctrl + C` works sometime it doesn't. I have been confused so much with this issue. And after 20 seconds or 1 minute if I do ctrl + c it works . I am unable to understand whats happening.

Regarding window sizing i haven't checked it will let you know.

**Comment by zadjii-msft** [comment]
Okay, but like, with the command actively outputting text when you try pressing <kbd>Ctrl+C</kbd>? We had a bug a few years ago where there was weird locking issue where `^C` signals wouldn't get delivered until _something else_ happened to the console server, something that _wasn't_ input. So you could press <kbd>Ctrl+C</kbd> as many times as you wanted, but they wouldn't get processed until the commandline application (`tsc --watch` in this case) actually output some new text.

The resizing thing is just me spitballing, trying to trick the commandline into outputting something, breaking the lock. I suppose you could achieve the same thing by pressing <kbd>Ctrl+C</kbd>, then editing & saving a `.ts` file that's being watched, and seeing if the `^C` gets handled immediately.

**Comment by svn-dys** [comment]
Nothing I do will execute `CTRL + C` to the command line. Resizing etc.

Anything I can do to see errors etc?

**Comment by shirshak55** [comment]
i tried resizing and ctrl + c is still not working for some commands. It doesn't happen two me but happens like 1 out of 10time. and I have to close terminal manually . I wish i could open tab in same folder and close that hanged tab. But currently the folder doesn't open in same location that previous tab was previously making this problem more worst :(

**Comment by wsy** [comment]
I encountered same issue since many months ago, and this bug is stil there.
I'm using Windows Terminal (Windows App Store version ```v1.6.10571.0```) with PSCore ```7.1.3```

I type ```ping -t <someIPAddress>```
![image](https://user-images.githubusercontent.com/2684991/112823720-36a58280-90bc-11eb-851d-20f7dcd2db6a.png)

I can Ctrl+Break and print statistic information.
![image](https://user-images.githubusercontent.com/2684991/112823999-90a64800-90bc-11eb-88e4-0035d9dd4abc.png)

But I can't Ctrl+C and stop ping command.
This does NOT repro EVERY TIME. So I guess this will be hard to fix.

I suggest you open many tabs in Windows Terminal and ping some IP address for many hours with "-t" parameter and then try to terminate them with Ctrl+C shortcut.

**Comment by armordog** [comment]
I can reproduce this running gitbash in Terminal by _holding_ `ctrl` and rapidly pressing `C` several times.

**Comment by DHowett** [comment]
Sorry, you can reproduce it _not_ working by holding ctrl and rapidly pressing C several times? But if you do not do it rapidly, it works just fine? I don't understand.

**Comment by armordog** [comment]
Sorry. =]
If I hold Ctrl and then press "C" rapidly several times, I will get the stall.
But if I press "C" less often it prints `^C` to the terminal and I get a new prompt, as usual.

Here's an example of me holding down ctrl+c (frame-rate is low but you can see what's happening).
It stays unresponsive for almost exactly 60 seconds.

![ctrlcgif](https://user-images.githubusercontent.com/1992702/116340421-feb15e00-a793-11eb-8473-26bb0b782f69.gif)

**Comment by KalleOlaviNiemitalo** [comment]
> Also, for what it's worth, running `exit` after it becomes responsive again shows `[Process exited with code 130]`

That is normal; ^C causes the shell to set $? = 128 + SIGINT = 130, `exit` causes the shell process to exit with the current value of $?, and Windows Terminal then displays the value. You can disable that by changing the [closeOnExit](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior) setting.

**Comment by armordog** [comment]
@KalleOlaviNiemitalo 
Oh weird, I'd never noticed that ^C always caused the exit code to be set. =]

**Comment by armordog** [comment]
When this happens, is there any way to determine what is unresponsive?
If it's Git Bash or Terminal?

**Comment by Strategic271** [comment]
I have the same issue with ctrl + c it prints ^C

**Comment by Strategic271** [comment]
The only solution I found so far is to actually use ctrl + shitf for copy, and ctrl + shift + ins to paste

**Comment by zadjii-msft** [comment]
Hey so this thread has kinda become conflated with a bunch of different topics here. Let's just focus in on the original post here - Ctrl+C not sending a sigint in git bash, in Terminal, _sometimes_. However, this thread is a few years old now. Is this still happening/? We can't manage to get this to repro locally. 

There's also been the mention of  PowerShell/Win32-OpenSSH#1699 in linked threads. That issue's predicated on using `ssh`, but that could also be a factor here.

**Comment by svn-dys** [comment]
@zadjii-msft I can no longer reproduce this issue.

**Comment by ValYouW** [comment]
@zadjii-msft Hi, I am still experiencing issues with ctrl+c not working properly within Windows Terminal.
Windows Terminal version: 1.15.2874.0

The setup is:
Windows Terminal
Git bash
And running a script via `npm start`

My git tab has this command line defined: `"commandline": "\"%PROGRAMFILES%\\Git\\bin\\bash.exe\" -i -l"`

Here is the script I'm using to reproduce the issue:

```js
---
package.json
---
{
  "name": "testsignint",
  "version": "1.0.0",
  "description": "",
  "main": "a.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start":"node main.js"
  },
  "author": "",
  "license": "ISC"
}
```

```js
---
main.js
---
let http = require('http');

http.createServer((req, res) => res.end('hi')).listen(5555, () => console.log('Listening'));

process.on('SIGINT', () => {
    console.log('SIGINT')
    process.exit(0);
});
```

When tapping `ctrl+C` I DO see the "SIGINT" console log but then the terminal is stuck for quite some time before returning to prompt.
It does NOT happen all the time, couldn't find any pattern or anything (like tapping "enters" when the server is listening etc)

Thx.

**Comment by jsilveira** [comment]
Same problem, makes the terminal really unusable. I think this issue should be reopened

**Comment by TheBestPessimist** [comment]
I have this problem too
