### ISSUE TITLE
Make it possible to click links with Ctrl + left mouse click

### ISSUE THREAD

**Issue by patrick-hintermayer** [microsoft/terminal#8036]
When working with JS scripts, you often get links like **Listening on localhost:3000**. In Visual Studio Code and other programs, I'm used to have the option to open that links in my browser if I hold ctrl and do a left mouse click.

**Comment by alannt777** [comment]
dup of #5001

**Comment by DHowett** [comment]
/dup #5001 
even after we complete link autodetection, it's only gonna work if it explicitly starts with `http://` or `https://`. I am not going to sign off on a feature that tries to turn any word+colon+number into a URI. :smile:
