### ISSUE TITLE
Better workflow(s) for multiple displays.

### ISSUE THREAD

**Issue by wusticality** [microsoft/terminal#8040]
# Description of the new feature/enhancement

Currently, I open two Windows Terminal instances so that I can code in Emacs on multiple displays at the same time. The only way to navigate between these two terminal windows is Alt-Tab to my knowledge. It would be helpful if there was a way to customize this.

# Proposed technical implementation details (optional)

**Comment by fran-f** [comment]
To move only between Terminal windows, you can use `Win+[1..9]`, with the number being the position of Terminal in the taskbar, from the Start menu.

**Comment by zadjii-msft** [comment]
@wusticality Do you have any concrete proposals, or is this issue just "make it better"?

For example, we've already got #7848 for a keybinding to switch directly between active Terminal windows - is that what you're looking for?

**Comment by wusticality** [comment]
Hey @zadjii-msft, here's a few things that I think could make it better:

* Have an option to open any of the various shells in a new window instead of in a new tab.
* Have the option to specify the shortcut(s) for switching between open windows / tabs (apologies if this exists already, if so, I'm not sure where).

Hope this helps! -K

**Comment by zadjii-msft** [comment]
Okay yea you're looking for 
* /dup #1051 for a `newWindow` keybinding
* /dup #7848 for and action for switching directly between WT windows

Thanks!
