### ISSUE TITLE
cmd does not support ctrl-V paste but host CMD.exe does

### ISSUE THREAD

**Issue by OzBob** [microsoft/terminal#8043]
# Environment

```
Windows build number: 10.0.19041.0
Windows Terminal version:1.3.2651.0

```

# Steps to reproduce
With a section in settings.json in profiles: "commandline": "cmd.exe",
Open Windows Terminal
Open new cmd tab
Ctrl-V (to paste)

# Expected behavior
Paste works as it does on the current host CMD.EXE: %windir%\system32\cmd.exe

# Actual behavior
^V printed to screen

**Comment by alannt777** [comment]
Is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> working?

**Comment by DHowett** [comment]
Yes, <kbd>Ctrl+V</kbd> is by default sent to the application inside Terminal. You may rebind it to `paste` if you want it to paste.
