### ISSUE TITLE
Close button doesn't use a tab's text color when hovered

### ISSUE THREAD

**Issue by TylerEich** [microsoft/terminal#8046]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
No.
```

# Steps to reproduce

Open a tab. Color it yellow. Hover over its close button.

![47103599-d504-44ba-bc36-a39aa98ef7c4](https://user-images.githubusercontent.com/3460063/97187427-cd21f080-1778-11eb-8d3d-4f391d4383e6.gif)

# Expected behavior

The × should be black, like it was before I hovered.

# Actual behavior

The × is white, like the default text color.

Related to #5789

**Comment by zadjii-msft** [comment]
Wow yep, that's a real bug. Probably similar to #5780, but for the tab hover color.

**Comment by dcheatha** [comment]
I fixed the tab text coloring issue, however this fix seems to introduce another problem.

Light theme white tab mouse hover effect:
![Screenshot_2020-11-07_152110_3](https://user-images.githubusercontent.com/7143383/98625373-503c5e00-22c4-11eb-86f6-49bc0c18a3b4.png)

Dark theme white tab mouse hover effect:
![Screenshot_2020-11-07_153021_2](https://user-images.githubusercontent.com/7143383/98625415-69dda580-22c4-11eb-80ec-094f249fae0f.png)

Should I calculate and set the button shadow manually here, or is there some way to set the button theme?

**Comment by Don-Vito** [comment]
@dcheatha - I think that the behavior you describe already exists prior to you fix. I checked this with vanilla, but please give it a try as well. (Hence I think your fix is already of high value 😊).

Regarding your question, I am not an author, but given that in the current implementation all brushes are computed manually, I guess the same should apply to the button shadow.
