### ISSUE TITLE
Setting for zoom level at startup

### ISSUE THREAD

**Issue by timskovjacobsen** [microsoft/terminal#8054]
# Set desired zoom level when opening a new tab

When opening a new terminal window (or tab), it opens with the default zoom level. One can hold CTRL and scroll the mouse wheel to adjust the zoom level.
This can get tedious if one always wants a different zoom level.

I was expecting a zoom setting to appear as autosuggestion either in [global settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings) or the profile settings for each terminal in the json settings file. However, it doesn't seem to be supported yet.

The setting could be named as below and would be nice to have for each profile rather than a global setting:

```json
"zoomLevel": "90"
```

where `"90"` denotes the zoom percentage compared to the default zoom level.

**Comment by zadjii-msft** [comment]
So here's a little secret - when you "zoom" the terminal with the mouse wheel, we're actually just making the font size _bigger_. So if you wanted to "set the zoom" level of the Terminal, you could actually just set the `fontSize` bigger or smaller.

Does that work for you?

**Comment by timskovjacobsen** [comment]
It does work like magic! I now feel like I should have tried that before posting, but didn't think of it. Thanks a lot for the quick response.

**Comment by zadjii-msft** [comment]
No problem! Happy to help ☺️
