### ISSUE TITLE
Is mouse supported for win32 console applications?

### ISSUE THREAD

**Issue by igorkuzuro** [microsoft/terminal#8056]
Mouse can be used only for copy/paste but not for working with Far Manager https://farmanager.com

Not depend on versions of Terminal or Far Manager

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+mouse+win32+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #376 for more discussion.

/dup #376
