### ISSUE TITLE
keybinding openWindow

### ISSUE THREAD

**Issue by lttweak** [microsoft/terminal#8057]
is there any way to create a keybinding for opening a new WT window? Does this action exist and the documentation has been overlooked or has this action been overlooked?

For example, this exists { "command": "closeWindow", "keys": "alt+f4" }
This seems to be missing { "command": "openWindow", "keys": "alt+n" }

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1051 for more discussion.

/dup #1051
