### ISSUE TITLE
Cursor movement in Vim/Neovim is slower in Terminal

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#806]
Ported from internal issue MSFT: 21185335

> When using Vim or Neovim in WSL, cursor movement appears much slower in Terminal than in vanilla wsl.exe.
> I've attached a few screen recordings of me moving the cursor vertically in Vim and Neovim in both vanilla wsl.exe and WSL in Terminal.
> 
> Two Vim options I have enabled that I've noticed significantly exacerbate the issue are `cursorcolumn` and `cursorline`, but it is still noticeably slower even with them disabled.
> 
> WSL Version: Ubuntu 16.04.5 LTS
> Vim Version: 8.1.1-744
> Neovim Version: 0.4.0

@nathpete-msft, can you re-attach the recordings here if you can still see this?

**Comment by BarrettStephen** [comment]
I came to file a bug on this, but It appears this is it here. I also found these related issues: #1311 and #2047 

This gets worse the more panes you have open. I see some sort of update cursor fly around the screen whenever I scroll around. Its miles slower than regular terminal

**Comment by BarrettStephen** [comment]
The rendering speed is so bad that I run some scripts in the regular terminal so they dont go as slow

**Comment by BarrettStephen** [comment]
Attached a demo of this issue, in vim, comparing legacy and windows terminal.

![windows_terminal](https://user-images.githubusercontent.com/9559818/62752246-8765f480-ba1b-11e9-91cd-c869698aa5b9.gif)
![legacy_terminal](https://user-images.githubusercontent.com/9559818/62752229-75845180-ba1b-11e9-811a-e846d3ef5a1a.gif)

The framerate of gifs isnt awesome, so its worse in person, but you get the gist.

**Comment by BarrettStephen** [comment]
this appears to get worse depending on how much of the display is static vs how much is moving.

**Comment by dz14** [comment]
I'd just want to add that it would be awesome to not only match the performance of vanilla wsl.exe but to surpass what it's currently capable of. With `set cursorline`, scrolling is very laggy on both wsl.exe and the new Terminal. Compared to my mac, scrolling through the same file with the same vimrc and configurations is buttery smooth on iTerm2.

**Comment by BarrettStephen** [comment]
This is still a problem in 0.5 (1909)

Its not just vim. Any console update is very slow when some parts are static (like with tmux).

**Comment by skyline75489** [comment]
I've cooked up several PRs that's intended to boost up performance. With the help of those PRs, rendering performance is indeed better. However it's still not ideal because the redrawing is just too much. I believe @miniksa has better plan for this.

**Comment by skyline75489** [comment]
For those of you who are crazy about `cmatrix`, I've make it fluent with my PRs on my own laptop with a Release build, which at least counts for something 😄
