### ISSUE TITLE
Vertical cursor movement stops working when terminal runs out of vertical space

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#8063]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Open a new PowerShell terminal tab
2. Make sure that there are plenty of vertical space available
3. Run `Write-Output "$([char]27)[5BHELLO WORLD"`
4. Notice the 5 empty lines before `HELLO WORLD`. All is fine.
5. Continue running `Write-Output "$([char]27)[5BHELLO WORLD"` until you run out of vertical space

# Expected behavior

I expect the 5 empty lines to continue showing (since we moved the cursor 5 lines down)

# Actual behavior

The 5 empty lines are not shown, the cursor is not moved.

![image](https://user-images.githubusercontent.com/357872/97360263-3e0ef880-189e-11eb-81f0-7775e382580e.png)

**Comment by DHowett** [comment]
(per https://vt100.net/docs/vt510-rm/CUD.html)

**Comment by zadjii-msft** [comment]
I'm pretty sure that's exactly how the cursor up/down/left/right sequences work - they're constrained by the size of the Terminal viewport. @j4james sanity check me?

**Comment by patriksvensson** [comment]
Ok, my bad. I misunderstood how it was supposed to work. Thank you for the explanation.
