### ISSUE TITLE
Change tab icon according to remote machine name & own config

### ISSUE THREAD

**Issue by georgewheatcroft** [microsoft/terminal#8064]
# Description of the new feature/enhancement

I use windows sub-system for linux (WSL) a lot with windows terminal (WT) to SSH remote machines, I have created profiles for some of the main machines I SSH, so that when I open the profile for that remote machine SSH, it has an identifiable icon 

![image](https://user-images.githubusercontent.com/58346897/97365809-318aa000-189e-11eb-8a95-aa47708d854d.png)

It would be great if rather than create a profile for each machine I SSH to, and have to stay in it (else I lose the icon change)
there could be a feature that allows a user to set up a config of machine names in their settings.json, which points to specific icons they have set, then have WT automatically update the tab icon with the icon that has been associated with the machine name, when they SSH over to the different machine

**Comment by DHowett** [comment]
Thanks for the request! /dup #1868

**Comment by DHowett** [comment]
If we're going to make this configurable I'd rather just go all the way and make it app-driven. I think that WT trying to _detect_ a hostname is going to be error-prone, and isn't going to get us what we want. :smile:

**Comment by georgewheatcroft** [comment]
Sorry for the dup.

Would it be possible to define what you mean by app-driven please?

**Comment by DHowett** [comment]
Sure! So, just like the app can set the title, there's a couple well-defined VT sequences that let the application set an icon. That'd be more like your remote shell or something saying "here, set the icon to this PNG file". It would let you go above/beyond simple hostname recognition and have the icon change when an operation was in-progress or when you were connected to a production cluster, etc.

**Comment by georgewheatcroft** [comment]
Thanks for that clarification 

In which case I think the discussion on the original ticket and your good point highlights how using VT sequences would be a fundamentally better way around this

I am assuming that because the existing VT Sequence I see on Console APIs (https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#output-sequences) are by Microsoft, creation of new VT sequences would be reserved for the Microsoft team?

**Comment by DHowett** [comment]
Nope! We actually try to _avoid_ making our own VT sequences whenever possible. We use a bunch of other standard and quasi-standard documented sequences, like the [xterm ones](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) and many things that [DEC terminals](https://vt100.net/docs/vt510-rm/) can handle

**Comment by georgewheatcroft** [comment]
Great! 

So it sounds like the way to resolve #1868 any other tickets relating to similar dynamic terminal content, would be to create a new issue in this project for inventing a custom Windows Terminal VT sequence (I can't find an issue which is already covering this, but as shown by the dup. my git issue searching skills are wanting...)
