### ISSUE TITLE
duplicate tab feature 

### ISSUE THREAD

**Issue by SaltyBuckets** [microsoft/terminal#8069]
# Description of the new feature/enhancement
When right clicking a tab an additional 'Duplicate Tab' option would appear. upon clicking it a new tab with the same commandline would open with the same working directory, which would speed up the navigation.

**Comment by SaltyBuckets** [comment]
I would like to work on this feature.

**Comment by alannt777** [comment]
Go ahead a create a draft PR and and wait for triage from the WT Team.

The WT Team may or may not agree on this idea.

**Comment by SaltyBuckets** [comment]
draft pr?

**Comment by LuanVSO** [comment]
#3158 #7668

**Comment by skyline75489** [comment]
There are plenty of discussions about this particular issue in #3158 and #7668 . As I said in other issues, this is currently a backlog issue which means that it is not the WT team's highest priority to get it done.

**Comment by skyline75489** [comment]
@SaltyBuckets  As the author of #7668 I encourage you to thoroughly read the comments and discourses in those existing issues before you really want to chime in. There are certain dilemmas that we have to tackle before actually shipping a feature like this. 

You're more than welcome to contribute to this project. Many people are working hard to make this project better and the voices from the community will be heard.
