### ISSUE TITLE
 Szrz command in Linux is not supported

### ISSUE THREAD

**Issue by lovkei** [microsoft/terminal#8071]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1999 for more discussion.

/dup #1999
