### ISSUE TITLE
Maximizing a Windows Terminal window triggers Windows 10's focus assist

### ISSUE THREAD

**Issue by zimmerrol** [microsoft/terminal#8072]
Maximizing a Windows terminal window will trigger the "When I'm using an app in full screen"-rule of Windows 10's focus assist.

# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 1.3.2651.0
```

# Steps to reproduce

1. Activate the automatic "When I'm using an app in full screen"-rule in Windows 10's focus assist settings
2. Start Windows Terminal
3. Make sure focus assist is not triggered/active
3. Make sure the Windows Terminal window is not maximized
4. Maximize the window

# Expected behavior

The window should be maximized and focus assist should not but turned on.

# Actual behavior

The window will be maximized but focus assist gets turned on.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1840 for more discussion.

/dup #1840
