### ISSUE TITLE
Set tab color in command line 

### ISSUE THREAD

**Issue by alisd23** [microsoft/terminal#8075]
# Description of the new feature/enhancement

When opening tabs/panes with the `wt` command, It would be great to be able to set the **color** of a tab, in a similar way as we can currently set the `title` with `wt --title something`.

I use the `wt` to command to open my terminal "workspace", and I use colours to easily distinguish the different tabs, so allowing this to be set by command line instead of manually each time the tabs are opened would be even nicer.

This could be as simple as something like the following, allow a hex value to be set:
```bash
wt --color "#111111" ; new-tab --color "#FF0000"
```

**Comment by zadjii-msft** [comment]
This isn't a bad idea. We've already got `tabColor` in the profile, might as well be able to override that from the commandline. We've already got the precedent with `--title` for `tabTitle`. Thanks for the request!

**Comment by Don-Vito** [comment]
@alisd23 - do you plan to implement this? If not I can work on this - sounds quite useful and straightforward.

**Comment by alisd23** [comment]
> @alisd23 - do you plan to implement this? If not I can work on this - sounds quite useful and straightforward.

Hey, I don't really have enough time at the moment so I won't be able to any time soon, so please go ahead - that'd be great!

**Comment by Don-Vito** [comment]
@zadjii-msft - I added an optional tab color to the NewTerminalArgs, and used it to override terminal settings.... and it was a very bad decision on my side 😆. I mean everything worked but then during the testing I noticed that the color disappears after splitting the pane, or reloading the settings. This was a very hard way (aka at least an hour of my life) to learn that there is a runtime tab color :smile:. So I switched to setting it. 

@zadjii-msft - Can you explain why we would want to use it for split-pane? I can understand why we might want it for duplicate tab though.
