### ISSUE TITLE
Ctrl + W Conflict With Nano Editor in Bash/WSL (not an issue in normal WSL or CMD)

### ISSUE THREAD

**Issue by robinwilson16** [microsoft/terminal#808]
Nano is a popular text editor in the bash/Linux environment but this uses Ctrl + W (for where) to initiate a search (same command Windows uses for closing the active window/tab) so it is a bit unexpected when this command closes the session down leaving the open file locked for editing.

Should Ctrl + W close the tab or should it be something else?

So this is sort of an issue although not exactly a bug as this functionality is obviously intended but it just conflicts with the Nano command and the standard CMD and WSL windows instead treat Ctrl + W as input so do not have this issue/conflict.

**Comment by miniksa** [comment]
I think our goal is to fix this with #537

**Comment by DHowett-MSFT** [comment]
Indeed. We'll close this one in favor of rebindable hotkeys.

**Comment by robinwilson16** [comment]
Ok thanks fair enough but I think maybe it would be good if the default mapping was to leave this key combination unmapped so it functions the same as CMD and WSL do.
