### ISSUE TITLE
Add Option to set blur type in Windows transparency effects

### ISSUE THREAD

**Issue by Tanishq-Banyal** [microsoft/terminal#8092]
# The acrylic blur has some graphical issues on old devices. It looks very noisy. 

So there should be an option to select blur type to use in Windows. Like "Gaussian blur", "lens blur", "windows 7 style blur" and an option to choose the intensity of blur.

I hope you will listen to thousands of people requesting this.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+blur) when filing new issues. This is already being tracked by another issue on our repo - please refer to #603 and #1753 for more discussion.

/dup #603
/dup #1753
