### ISSUE TITLE
Refresh issue when quitting a full screen console application

### ISSUE THREAD

**Issue by jchomarat** [microsoft/terminal#8094]
After quitting a full screen console application on a terminal window that has been resized while having the application opened, the new portion is not refreshed hence some remaining of the application UI sticks on the console

# Environment

```none
Windows build number:  Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
VIM version 8.2
or
[wttop](https://github.com/jchomarat/wttop) version 1.1
```

# Steps to reproduce

1. Launch The Windows Terminal
2. Open a PowerShell core tab
3. Install either vim or wttop
  a. 
```sh
/> choco install vim -y
```
4. open a file 
```sh
/> vim test.txt
```
5. Resize the terminal windows (make it bigger)
6. Quit vim (ESC + : + q + Return)

# Expected behavior

The Terminal should completely refresh

# Actual behavior

We can see the bottom of the application on the terminal

![image](https://user-images.githubusercontent.com/6317287/97551770-aca1a280-19d3-11eb-8a3f-a14321508934.png)

**Comment by DHowett** [comment]
This is unfortunately a weird interaction between Win32 vim and the console infrastructure. It actually takes a full copy of the screen (!) and when you exit, it writes that copy back to the screen. If the buffer size has changed, it can get confused and write the wrong portion of the screen.

I'm gonna close this here and file an issue on vim to use the alternate buffer differently. :smile:

**Comment by DHowett** [comment]
Sorry for the delay, and thank you for the report!
