### ISSUE TITLE
MINOR: Environment Variable in CMD Prompt not resolved.

### ISSUE THREAD

**Issue by FDFessler** [microsoft/terminal#8096]
This is VERY MINOR: Environment Variable in CMD Prompt not resolved.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.19041.572]
Windows Terminal version (if applicable):
Windows Terminal Preview
Version: 1.4.2652.0
Settings for Command Prompt:
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "startingDirectory": "P:\\",
                "hidden": false

Any other software?
```

# Steps to reproduce

Launch Command Prompt in WT

# Expected behavior

While I have a fairly long (and "crazy") prompt string in my environment settings it seems to do everything right except resolve an environment name (in this case my PC name %ComputerName%).
Current Prompt:
$E[1;33;45m[$D--$T$H$H$H$H$H$H]$S$E[7;33;44m$C$N:$Q$M$H$F$_$E[0;34;47m$P$E[0;37;44m$_[%ComputerName%]:$S$+$G$S
Prompt should look like this:
[10/29/2020-- 9:38] (P:=\\ServerName\Dir1\Dir2)
P:\
[**MyActualPCName**]: >

# Actual behavior

I get this (with all the correct colors) but the %ComputerName% is not resolved.
[10/29/2020-- 9:32] (P:=\\ServerName\Dir1\Dir2)
P:\
[**%ComputerName%**]: >

**Comment by zadjii-msft** [comment]
So here's the weird thing with the PROMPT command - environment variables in it are only expanded when the command is run, _not_ when the prompt is displayed. So when you do:

```cmd
PROMPT %COMPUTERNAME%$g
```

cmd evaluates `%COMPUTERNAME%` to whatever (in my case, `MIGRIE-SLAPTOP`, _then_ sets the prompt to `MIGRIE-SLAPTOP$g`

![image](https://user-images.githubusercontent.com/18356694/97584669-42cecc00-19c6-11eb-9c64-c13afb96d86b.png)


So I'm betting that your prompt variable literally has `%ComputerName%` in it, rather than the evaluated value of `%ComputerName%`, right?

**Comment by FDFessler** [comment]
That is correct and it what I posted above.
It works if I just open a "normal" CMD prompt however.  So, I'm OK if this is a limitation, just wanted to make sure this was not an "oversite".
You can duplicate the problem very easily by setting your Prompt **environment** string to just %ComputerName%$g
... and then seeing the difference between standard CMD prompt and WT CMD prompt.

**Comment by DHowett** [comment]
This is likely a side effect of us giving CMD a new environment block. I swear sometimes, this OS is too fragile to write code for.

**Comment by FDFessler** [comment]
This NOT a big deal (very minor IMO), I can just run my prompt manually after opening the COMMAND Prompt windows in WT.  Like I said earlier, just wanted to make sure this was not an "oversite".
Thanks.

**Comment by LuanVSO** [comment]
this works for me 
![image](https://user-images.githubusercontent.com/43626415/97808853-090cf800-1c48-11eb-9ad3-591b805b51fb.png)
don't know why though ¯\_(ツ)_/¯

**Comment by DHowett** [comment]
Alright, after sitting on this issue for a while I've come to a conclusion.

This is technically the same as #7418, but for a different reason. The solution to both is the same, however: _we have to do a 3-way merge **and** expand the environment block in Terminal before we start the next process._

Thanks :smile:

/dup #7418
