### ISSUE TITLE
diacritics not supported

### ISSUE THREAD

**Issue by nExoRek** [microsoft/terminal#8097]
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal
Version: 1.3.2651.0

# Steps to reproduce
run console with some language using diacritics - e.g. i'm writing in polish where we have a lot of ąśćęłóżź 
try typing them... even the trick with using the tilde is not working - diacritics are 'blocked' /:

# Expected behavior
be able to type diacritics

# Actual behavior
...which you currently cannot

**Comment by alannt777** [comment]
Which shell are you using? CMD/PowerShell/WSL Bash ?

**Comment by nExoRek** [comment]
PowerShell... indeed i just run CMD and diacritics works fine there /:

**Comment by alannt777** [comment]
It works fine in CMD

But does not work in PowerShell. Is that correct?

If that's the case, it is a PowerShell issue. Are you using PowerShell Core or the Windows PowerShell that comes with Windows?

**Comment by nExoRek** [comment]
Windows PS. 
hmm... you're correct, i checked on the console and don't have diacritics there either... i do most of the job from within VSC, didn't notice this glitch before.
lol. found that https://github.com/PowerShell/PowerShell/issues/10298

i installed recent psreadline version and all's working fine.

sorry for bothering, didn't notice it's a global issue

**Comment by alannt777** [comment]
Well you can then close this issue

**Comment by zadjii-msft** [comment]
Glad you were able to figure this out! Hopefully this will help someone in the future ☺️
