### ISSUE TITLE
[Feature Request ⚙] GIF Capture tool for the Windows Terminal 

### ISSUE THREAD

**Issue by alannt777** [microsoft/terminal#8098]
# Description of the new feature/enhancement
Extremely useful for demonstration and in GitHub (Why are you not supporting videos in markdown, GitHub?)

**Note** that PowerToys is planning to make a GIF capture tool. But this is going to be different because this feature will be dedicated to capturing the Terminal. This will allow the user to modify the contents and change things like fonts before rendering the GIF. unlike any other GIF recording tool.

# Proposed technical implementation details (optional)
*You can edit this section and add ideas*

**Comment by zadjii-msft** [comment]
So we've already got #469 tracking recording the Terminal, though, that's turned its focus directly to asciinema as the format (which I think we all agree is a good and reasonable format). 

I don't see the value in bloating the Terminal with another gif recorder, especially if PowerToys is already going to be shipping their own GIF recorded. Seems like the user story should be "Use the GIF recorder in PowerToys". 

I suppose I can leave this open as a potential extension idea - something that someone _could_ implement, and that someone _could_ add directly to the Terminal, but I'm confident that our team is not going to be spending resources maintaining our own GIF recorder if PowerToys ships one. I'll throw it in #4000, but someone else in the team can feel free to close this if they feel like it in my opinion.

There is https://github.com/microsoft/PowerToys/issues/143 - though, that doesn't seem like it has any firm commitments from the PT team. [This section of the roadmap](https://github.com/microsoft/PowerToys/wiki/Roadmap#post-stabilization) is the closest thing to a confirmation, in a release "post stabilization"

**Comment by DHowett** [comment]
For this one, I would much rather a better third-party tool do it than Terminal. We're an ecosystem! Terminal isn't Emacs, after all -- it doesn't want to replace your operating system or your existing toolbox filled with very useful tools. :smile:
