### ISSUE TITLE
specifying a directory on a mounted drive or a symbolic link to a directory on a mounted drive as the starting directory does not work 

### ISSUE THREAD

**Issue by gkamendje** [microsoft/terminal#8103]
# Environment

```none
Windows build number:  19041.572
Windows Terminal version (if applicable): 1.2.2381.0

Any other software?
```
In the Windows Terminal Json file, specifying a directory on a mounted drive or a symbolic link to a directory on a mounted drive as the starting directory does not work at all.
# Steps to reproduce
For example for me, the following works well. 
`"startingDirectory" : "//wsl$/Ubuntu/home/<User>/"`
This works also
`"startingDirectory" : "//wsl$/Ubuntu/home/<User>/a_sub_dir_of_my_home"`

However, setting a directory on a mounted drive as the starting directory  does not work. 
`"startingDirectory" : "//wsl$/Ubuntu/mnt/e/mydir_on_drive_e"`
This does not work either
`"startingDirectory" : "//wsl$/Ubuntu/home/<User>/<Symbolic_link_to_a_directory_located_on_one_of_the_mounted_drives>"`

# Expected behavior
WSL should open in the specified directory

# Actual behavior
WSL opens into the default directory

**Comment by skyline75489** [comment]
For what it's worth, you can actually use the Windows path instead of the transferred WSL path of the mounted drives:

```json
{
    "startingDirectory": "D:/Projects"
}
```

**Comment by zadjii-msft** [comment]
Out of curiosity, is there a reason you want to provide the path as the `//wsl$/<distro>/mnt/<drive>/<path>` format, over the `<drive>:/<path>` format? Because the second does seem like a lot less hassle...

**Comment by gkamendje** [comment]
These are all valid workarounds. The only problem I see is the fact that with a symbolic link in the user home directory, the resulting prompt in the shell can be made arbitrarily short. Something like ~/my_sym_link_to_bar$ whereas with the Windows path option, the path  becomes
/mnt/drive/project/dir/sub/foo/bar$. I am aware that there are ways to play around with the prompt but this is certainly another story.  I was just curious to see if there was a way to make the symbolic link option work (It should work technically given that it is a valid path inside the Linux Distro).

**Comment by skyline75489** [comment]
As far as I know, `startingDirectory` is a parameter that we passed to `wsl.exe` (or whatever program in the profile) for it to consume and and know where the desired working directory is. This happens on the Win32 level. This is also the reason why `<drive>:/<path>` works in the first place. Everything in `startingDirectory` strictly belongs to the Win32 realm. The transformed format `//wsl$/<distro>/mnt/<drive>/<path>` is in fact a network path that is mounted internally by Windows, to make files in Linux accessible. 

A symbolic link, if I'm not mistaken, is a Linux OS & filesystem specific thing, that is currently not recognized in the process we described. Part of the reason why it's not supported might be the fact that Windows does not support ext4 or any Linux filesystem.

If you really want to know whether this will be supported in the future, https://github.com/microsoft/WSL is probably the best place to ask.

**Comment by DHowett** [comment]
Sorry, yeah, this is ... complicated.

The starting directory is processed by wsl.exe _before it actually boots linux_. This is critical: it hasn't run any automounting, it hasn't even found most of your files. It's not _ready_ to handle a path that symlinks into a mounted drive.

I can offer you this: we're working in /dup #7197 to handle this better and get support from WSL itself to take care of the starting directory. Hopefully that work will help your use case :smile:
