### ISSUE TITLE
Feature Request: show an indicator if there's a bell in the tab

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#8106]
# Description of the new feature/enhancement

This is a pretty straight-forward one. I know iTerm2 has this. As a ex-iOS developer I found it very useful to not only hear the bell but also know *which tab* is actually triggering the bell.

# Proposed technical implementation details (optional)

I think we need a spec for this, to display some kind of accessories in the tab, besides icon and title.

**Comment by skyline75489** [comment]
OK now that I think of it, the title is kinda bad. @zadjii-msft Please help me with my English and change the title to something more explanatory.

**Comment by zadjii-msft** [comment]
> OK now that I think of it, the title is kinda bad. @zadjii-msft Please help me with my English and change the title to something more explanatory.


Oh I knew exactly what you meant by this, don't sweat 😆 

We've had mockups of this dating back to some of the earliest Terminal mockups actually. I'm surprised we didn't already have an issue for it, but that makes sense considering we only just landed the bell in #7679. 

I'm _mildly_ worried that we're going to be stuffing a lot of info into the tab pretty soon - the "zoom" indicator, the progress ring, the bell/mute indicator, but I'm not _that_ worried. I think the number of people who are doing all simultaneously will be fairly low.

**Comment by mdtauk** [comment]
> > OK now that I think of it, the title is kinda bad. @zadjii-msft Please help me with my English and change the title to something more explanatory.
> 
> Oh I knew exactly what you meant by this, don't sweat 😆
> 
> We've had mockups of this dating back to some of the earliest Terminal mockups actually. I'm surprised we didn't already have an issue for it, but that makes sense considering we only just landed the bell in #7679.
> 
> I'm _mildly_ worried that we're going to be stuffing a lot of info into the tab pretty soon - the "zoom" indicator, the progress ring, the bell/mute indicator, but I'm not _that_ worried. I think the number of people who are doing all simultaneously will be fairly low.

If you decide to implement the status bar, things like Zoom indication could go there.  I see little reason you need to know a tab's console has been zoomed, unless it is the current active tab.

**Comment by j4james** [comment]
This is closely related to #1608, if not a duplicate.

**Comment by zadjii-msft** [comment]
I agree that this is closely related, but I'm gonna hold off calling this a dupe. I think I'd rather have this issue specifically track displaying the bell icon in the _tab_, and the other issue for displaying the alert in the taskbar. They're pretty similar, but I could see people wanting one or the other (or neither, or both), so we should probably have them all configurable independently.

I'll add both of them over to #6700, because they're sorta related. They're all about displaying some state to the user either with the tab or the taskbar.

**Comment by mpela81** [comment]
How long should a bell indicator stay on the tab btw?

**Comment by zadjii-msft** [comment]
Maybe like 1 second, then a 1 second fade? I suppose it should be just about the same as if a Edgium tab played a bell, for consistency.

**Comment by zadjii-msft** [comment]
Also, @mpela81, if you're interested in working on this, you might want to hold off until #8227 is merged. That might make adding the XAML element to the header a bit easier 😉

**Comment by sarim** [comment]
While the audible bell is very annoying, the visual bell is kinda hard to notice. Maybe instead of plan bell icon, 🔔 can be used? Also bell icon only prepends to tab title, maybe It can be appended to taskbar title too. Or superimpose a little bell icon to taskbar's terminal icon....
