### ISSUE TITLE
'wt' in the File Explorer address bar is failed to open in current folder when path consists '[' or ']'

### ISSUE THREAD

**Issue by LazyRen** [microsoft/terminal#8107]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Steps to reproduce

1. Go to any location that contains '[' or ']' in the path.
2. Type wt in the file explorer address bar
3. Windows Terminal fails to run on the current folder. (Instead runs on C:\WINDOWS\System32\WindowsPowerShell\v1.0>)

4. IT DOES NOT happens iff path doesn't have '[' or ']'.

My guess is that in order to cd to the path with '[' or ']'

you actually have to type `[ instead of plain [, but it fails to do so.

```
// Expected
cd '.\SVN\02_Softech\01_Problem\2020\`[2021`] Oct _1\'

// Actual
cd '.\SVN\02_Softech\01_Problem\2020\[2021] Oct _1\'
```

# Expected behavior

It should have opened in the current folder. Even if the path contains [ or ].

# Actual behavior

It fails to do so.

**Comment by DHowett** [comment]
This appears to be a bug in Windows PowerShell. When I run `wt -d . powershell.exe`, it happens... but when I run `wt -d . cmd` it doesn't.

**Comment by DHowett** [comment]
(It also happens if I remove WT from the equation and just run `powershell.exe`. Sorry.)

**Comment by LazyRen** [comment]
Got it. Thanks.
I'll post bug report via Windows feedback hub.
Hope it will be fixed soon.
