### ISSUE TITLE
commandline use more one command show error

### ISSUE THREAD

**Issue by lmcmceo** [microsoft/terminal#8108]
if I input "echo '12345';ssh lotteryprod@192.168.1.1", it show 12345 and then require my password,
but I use the following settings
{
            "closeOnExit": true,
            "commandline": "echo '12345';ssh lotteryprod@47.242.87.207",
            "guid": "{592D0432-1020-4DF6-83D4-928A7BE1D31B}",
            "name": "Test"
          }

it shows 
[start“echo '12345'” error 0x80070002]
is this a bug ?

**Comment by lmcmceo** [comment]
![image](https://user-images.githubusercontent.com/71498780/97674552-2a82ae00-1aa7-11eb-874e-ac5a4893ff2d.png)

**Comment by skyline75489** [comment]
No I don't think this is a bug. The `commandline` is not the same as whatever you type inside a *shell* (in this case powershell). The `commandline` needs to be a *program* that can be found and spawned by the terminal. In this case you need to use something like this:

```json
{
    "commandline": "powershell -Command echo '12345';ssh lotteryprod@47.242.87.20",
}
```

**Comment by skyline75489** [comment]
See [here](https://github.com/microsoft/terminal/blob/main/doc/Niksa.md#whats-the-difference-between-a-shell-and-a-terminal) for the difference between a shell and a terminal. Or search online for more detailed explanation. If you're really interested , the keywords would be "shell", "terminal", "CLI" and "tty". 

And BTW you should not leak sensitive information like IP addresses, just for your own sake.
