### ISSUE TITLE
Transparency effect disappears when switching to other applications

### ISSUE THREAD

**Issue by CausingBrick** [microsoft/terminal#8110]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
Nope
```

# Steps to reproduce

1. Settings JSON like below
```json
"useAcrylic": true,
"acrylicOpacity": 0.7
```
2. Open Windows Terminal with any shell , now it has transparent effect.

3. Switching to any other desktop application, Windows Terminal will lose transparent effect.

4. Switching back to Windows Terminal, now it has transparent effect again.

# Expected behavior

I expect Windows Terminal always keep the transparent effect

# Actual behavior
But in fact , when I switch to other desktop application the transparent effect will lose like below
![image](https://user-images.githubusercontent.com/37139489/97692983-b7a11500-1a5d-11eb-96ff-a22f52ba5226.png)
When I Switch back to Windows Terminal like below
![image](https://user-images.githubusercontent.com/37139489/97693630-b02e3b80-1a5e-11eb-9e5c-35018f463c2a.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+acrylic+inactive+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #7158 for more discussion.

/dup #7158
