### ISSUE TITLE
property icon of profiles/list[] is not working, while the value is emoji

### ISSUE THREAD

**Issue by notxx** [microsoft/terminal#8111]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Windows Terminal version (if applicable): Windows Terminal Preview 1.4.2652.0

Any other software? no
```

# Steps to reproduce

edit settings.json
create now item in `profiles/list[]`
set property `icon` of new created item to `⚡`

# Expected behavior

the profile list add one item with ⚡ to be its icon

# Actual behavior

poping up a warning
![image](https://user-images.githubusercontent.com/785476/97698757-fbd6f880-1ae3-11eb-83d9-a50ad7e67d3c.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! I believe this will only work once #7830 is released, which won't be until 1.5 comes out. I'd follow that PR - the bot will post a message when a build is available with that fix. 

/dup #7830

**Comment by mishak87** [comment]
What is the point of having official docs pointing to unreleased feature?
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings

**Comment by DHowett** [comment]
We usually tag those features when they are part of a preview release. Sorry for the mistake.

**Comment by DHowett** [comment]
And, hey, it _is_ released... in the preview channel, which is pretty much every bit as stable as Stable is.
