### ISSUE TITLE
Bring back old Windows ways of launching Cmd

### ISSUE THREAD

**Issue by ck2510** [microsoft/terminal#8113]
# Description of the new feature/enhancement

In early versions of Windows10 it was still possible to launch Cmd from Windows Explorer context menu and also to place an icon into the Windows Explorer "QuickAccessToolbar". Then at some point it was decided to promote PowerShell and those possibilities where removed and strange registry hacks emerged to control the behavior of cmd vs. powershell involving keys like HideBasedOnVelocityId  and ShowBasedOnVelocityId, see also [1].

Now there a strange hacks qith questionable security to bring back the old UX or workarounds with less integration as shell commands.

[1]
https://github.com/microsoft/terminal

# Proposed technical implementation details (optional)

Encourage Windows to again give user the choice between PowerShell and Cmd and have both with equal level of integration in the system, as it is still the case for Win-X menu.

Edit: removed mistake of referring to command line, actually Windows Explorer context menu was meant

**Comment by WSLUser** [comment]
This will never happen. CMD is still available for use. When right click selection in Explorer is brought back for Windows Terminal, you'll get this behavior if you set CMD as your default (eventually a selection between profiles will also be added). CMD is not equal to Powershell and never will be. You are heavily encouraged to use Powershell, which continues to get support in the form of Powershell Core.

**Comment by DHowett** [comment]
No. You can configure whatever you like on your own machine; we are not stopping you.

**Comment by DHowett** [comment]
You are free to put shortcuts to CMD _anywhere on your system that you like_. Put 100 of them on your taskbar, type cmd into the address bar, change the default profile of Terminal to CMD. We only control one of these surfaces.
I do not understand why you have cited this repository, _the repository on which you filed this issue_, as a hack?

**Comment by ck2510** [comment]
Sorry my mistake with the link I can understand that the request is outside the scope of this project. Anyway I have a hard time to understand MS strategy here. This project promotes CMD/terminal, Windows tries to push it out from UX.

**Comment by zadjii-msft** [comment]
I think there's a bit of a misunderstanding here - `cmd` != console.

`cmd.exe` is a _shell_, like `powershell` or `bash`.

These commandline clients can run attached to a console. Whenever you open `cmd.exe`, the window that you're actually seeing is `conhost.exe`, the _Console_. That's the window that serves all console application on Windows, including `cmd` _and_ `powershell`.

This is the repo for both the Console and the Windows Terminal. Both their codebases live in this repo. The Console is getting occasional maintenance, and the Terminal is actively maintained and updated frequently. What we're _not_ doing is actively promoting `cmd`. The official party line is "if you want a modern shell, that receives updates, use PowerShell".
