### ISSUE TITLE
Make terminal tabs movable to other terminal windows.

### ISSUE THREAD

**Issue by JoshMerlino** [microsoft/terminal#8120]
# Description of the new feature/enhancement

A feature that allows the combination of terminal tabs in other windows. Similar to modern web browsers where you can drag a tab off the title bar and into its own window and/or combine tabs from multiple windows into one.

**Comment by alannt777** [comment]
dup #1256

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22move+tabs+%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
