### ISSUE TITLE
Pipe terminal buffer to an editor (vim)

### ISSUE THREAD

**Issue by alekstheod** [microsoft/terminal#8122]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Hey could you give us any more details? Why do you want this feature? How would you expect it to work? How is this different from other open issues on the repo, like:
* "ability to pipe scrollback buffer to a pager or terminal editor like kitty" #7749
* "Feature request: export console history as txt" #642


We can't really do anything with a blank issue.

**Comment by alekstheod** [comment]
> Hey could you give us any more details? Why do you want this feature? How would you expect it to work? How is this different from other open issues on the repo, like:
> 
>     * "ability to pipe scrollback buffer to a pager or terminal editor like kitty" #7749
> 
>     * "Feature request: export console history as txt" #642
> 
> 
> We can't really do anything with a blank issue.

Seems to be a duplicate of #7749 
I wanted to ask about exactly this functionality.
