### ISSUE TITLE
Only underline hyperlinks on hover

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#8123]
# Description of the new feature/enhancement

I can understand that some people will feel differently about this, but could we at least have an option to underline the hyperlinks only when the mouse is hovered over them, instead of showing the underline all the time?

On explicit hyperlinks (via `OSC 8`) I feel it should really be up to the app generating the link to choose how it wants that rendered. For example, you might be trying to make a link look like a button, but then we add dashed underlines everywhere which totally mess up the effect.

In the case of the autodetected hyperlinks, it's already obvious when something is a link. And the annoying thing is the underline doesn't track very well when you scroll, so ends up lingering on areas of the page that don't even have a link. I don't know if that's something we can fix, but either way I'd rather it just didn't underline at all until you hovered.

And as a point of comparison, every terminal I've tried so far that autodetects links does so my showing the underline only when you hover over the link. This includes Gnome Terminal, Konsole, Alacritty, Kitty, Terminator, and Mintty - the latter only showing the underline when you're pressing `Ctrl` at the same time.

For `OSC 8` links, Gnome Terminal displays a dotted underline without having to hover, but it's at least more subtle than our dashed underline. Mintty again only shows an underline when actually hovering over the link with the `Ctrl` key pressed.

**Comment by DHowett** [comment]
Yeah, I’m actually totally in support of this. It hides a chosen deficiency (scanning for URLs on a delay) and makes the screen less cluttered.

How about:

* we use a less obtrusive dotted line, eventually configurable, for OSC 8
* that dotted line becomes a solid line on hover
* for detected URLs, we use no treatment but offer a solid line on hover

Eventually, we can add configuration for different treatments for both types of link.

**Comment by DHowett** [comment]
This is now in PR in #8148.
