### ISSUE TITLE
Out-Gridview launches behind Windows Terminal

### ISSUE THREAD

**Issue by lenihan** [microsoft/terminal#8127]
# Environment

```none
Windows build number:  Win32NT, 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 14.2652.0

Any other software? No
```

# Steps to reproduce

Open PowerShell tab
`ls|Out-Gridview`

# Expected behavior
New window should be in front of terminal (works correctly with PowerShell original terminal)
![image](https://user-images.githubusercontent.com/22015149/97834395-9eca7680-1c8c-11eb-89d5-104f711ea417.png)

# Actual behavior
Window is behind Windows Terminal
![image](https://user-images.githubusercontent.com/22015149/97834312-60cd5280-1c8c-11eb-9f95-628fd57d74d2.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! As bizarre as it might seem, this is actually already being tracked by another issue on our repo - please refer to #2988 for more discussion.

/dup #2988
