### ISSUE TITLE
CTRL + C seems ineffective

### ISSUE THREAD

**Issue by Ushernrt** [microsoft/terminal#813]
When I used SSH to connect to Ubuntu, the program did not stop when I press Ctrl + C.

Does anyone have the same problem?
![image](https://user-images.githubusercontent.com/13357418/57744733-04275200-76fd-11e9-8a02-d48cabc3d2ab.png)

**Comment by mdtauk** [comment]
Ctrl+C is a keyboard shortcut for copy on Windows.  Could that be causing a conflict?

**Comment by DHowett-MSFT** [comment]
Based on the way the output stopped and was followed by a ^C, it seems like it was effective? Is it slower than you’d expect to respond?

**Comment by Ushernrt** [comment]
@DHowett-MSFT Yes, when I press Ctrl + C, It can't stop immediately.

**Comment by zadjii-msft** [comment]
Does this repro in other shells, or just OpenSSH? For example, does it repro in wsl? Could you try wsl's ssh?

How about other commands? Perhaps there's a chance that that _particular_ command is slow to respond to a Ctrl+C, while something else (`ping`?) might be more responsive.

If you're seeing it consistently in lots of different commandline applications, then this is probably a connection or conpty issue.

**Comment by Ushernrt** [comment]
@zadjii-msft Yes, When I use ping, it is more responsive.

**Comment by dropdevrahul** [comment]
can we close this issue now? or any further checks are required?
