### ISSUE TITLE
HDPI issue: Windows Terminal scales everything down

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#8131]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows [version 10.0.19041.610]
Windows Terminal: 1.3.2651.0

# Steps to reproduce

I am not sure how to reproduce, but I have an external monitor that's not HDPI connected to my Surface Dock. After some time, opened up the Surface and noticed the Windows Terminal window was incorrectly scaled: display is way too small, just like the terminal window was on the other screen.

Notice how other apps, like Edge, that were also opened previously are correctly scaled.

Note that if at this point I open a new Windows Terminal window, it will be scaled correctly.

More information:

- internal monitor: 3000x2000 Surface Book screen, scale set to 200% in Windows settings app
- external monitor (that was switched to another computer when this happens): 2560x1440, scale set to 100% in Windows Settings

To sum up:

- I started a Windows Terminal that was opened on the internal screen of the Surface Book
- the external monitor was used to extend Windows's desktop (but the WT window was still on the internal monitor)
- then the Surface Book was put to sleep, and the monitor disconnected (by switching to another computer)
- then I woke up the laptop, and the WT window appeared to use the scaling (100%) of the external monitor instead of the 200% of the monitor it is displayed on

# Expected behavior

Scaling should be correct.

# Actual behavior
Scaling is wrong.

- left: this is how Windows Terminal looked after I opened up my laptop
- right: this is how it's supposed to look after a fresh start

![image](https://user-images.githubusercontent.com/199648/97902966-a77b8500-1d3e-11eb-84f8-871a795ec037.png)

**Comment by zadjii-msft** [comment]
What happens if you just jiggle the size of the window a little bit - does it update to the correct scaling?

**Comment by warpdesign** [comment]
> What happens if you just jiggle the size of the window a little bit - does it update to the correct scaling?

I tried moving it, resizing it, maximizing it: didn't change anything, it still using incorrect scaling.

**Comment by DHowett** [comment]
Yep, this one is totally baffling. Thanks for all the info :smile:

You're not using any scaling compatibility options, right? Does this happen all the time? Is this a one-off?

**Comment by warpdesign** [comment]
@DHowett This doesn't seem to happen all the time and I don't know what triggered it.

Not sure what you mean by scaling options but here are my display settings for the internal Surface Book screen (it's the default options, never touched them):

![image](https://user-images.githubusercontent.com/199648/100084061-93610a00-2e4a-11eb-8326-6778b9c90fe1.png)

**Comment by warpdesign** [comment]
This happened to me again.

This may help: I noticed that when Terminal window has incorrect scaling, close/maximize/minimize buttons aren't working anymore (moving the mouse over them doesn't even highlight them). Only double-clicking on title bar works as expected to min/maximize window.

**Comment by DHowett** [comment]
Unfortunately, we still haven't been able to reproduce this. How regularly does it happen for you?

(Sorry for the delay here -- it's been busy with Windows 11 ;P)
