### ISSUE TITLE
GUI plugin / extension

### ISSUE THREAD

**Issue by dsl400** [microsoft/terminal#8132]
# Description of the new feature/enhancement
A solution to create a graphical user interface with form elements (buttons, labels, icons, etc) that can be programmed to inject commands into the current terminal and also read data from the current terminal and change the state of the GUI based on the received data

these days it is very easy to create a graphical user interface with a number of buttons / text fields 
but it is very hard to create a console window for your application that accepts all the abuse

# Proposed technical implementation details (optional)
the solution should provide the ability to easily share "the creation" 

easy interaction with console based devices.
automation of specific commands with the ability to create a layout that simulates the shape of the hardware
in the image below you can see a form that helps me debug a multiplexer board by manually activating a specific relay based on the position on the board
![image](https://user-images.githubusercontent.com/4988046/97907812-802cb400-1d4e-11eb-897a-e37f7c308265.png)

**Comment by DHowett** [comment]
Thanks for the suggestion! This is something that you can do by using WPF from PowerShell. We aren’t planning on offering a GUI creator because it is a very complicated feature that is better-implemented by so many other applications.

**Comment by dsl400** [comment]
there is no need for gui creator, only for a solution to inject commands and read the output.
the gui can be created using any existing technology

**Comment by zadjii-msft** [comment]
I think what you're actually looking for is broadly covered by #4000 - in that thread we're covering all sorts of possible things that "extensions" could be used for. These extensions include running 3rd party GUI code inside the Terminal, and possibly writing input to the Terminal as well.
