### ISSUE TITLE
Lines are pasted in reverse order

### ISSUE THREAD

**Issue by JVimes** [microsoft/terminal#8138]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. In a PowerShell tab, type this multi-line command using <kbd>Ctrl+Enter</kbd> for the newlines:
```
1
2
3
```
2. Press <kbd>Enter</kbd> to run it
3. Press <kbd>Up Arrow</kbd> to load the command again
4. Press <kbd>Ctrl+A</kbd> to select it
5. Press <kbd>Ctrl+X</kbd> to cut it
6. Press <kbd>Ctrl+V</kbd> to paste it
7. Select "Paste anyway" on the multi-line paste warning

# Expected behavior

I expect it to paste this:
```
1
2
3
```

# Actual behavior

It actually pasted this:
```
3
2
1
```

# Screen cap of the issue

![2020-11-02_17h10_34](https://user-images.githubusercontent.com/6148201/97932907-6aa79200-1d2e-11eb-9b80-2594d8878ff5.gif)

**Comment by DHowett** [comment]
/dup #5821 for now you can use PowerShell’s paste binding (remove ctrl+v from your settings file, which will let Powershell handle it)
