### ISSUE TITLE
How to Change Scrollbuffer #Lines

### ISSUE THREAD

**Issue by vectorfaucet** [microsoft/terminal#8141]
# Environment

```none
Windows: 19042
Windows Terminal: 1.3.2651.0
```

# Steps to reproduce

Is there a way to increase or reduce the scrollbuffer number of lines available?

# Expected behavior

I would think the following would be the correct method:  
Settings cog > with appropriate keywords and syntax, insert appropriate lines amount (with defined limit).  

Or I would expect to find info about it on a page similar to this, or on the msdocs for windows terminal: `https://github.com/MicrosoftDocs/terminal/issues/6`

# Actual behavior

Confession, I was a little aimless.  
I sifted through issues about scrollbuffer and lines, read the docs on msdocs and had a good hunt around.  
It could be my misunderstanding.

Thanks for your time.

**Comment by DHowett** [comment]
Sorry about that! It’s called `historySize`.
