### ISSUE TITLE
when i first open the windows terminal it goes to the Default startingDirectory but when i reopen it then it goes to the one i assigned

### ISSUE THREAD

**Issue by pachualcacer** [microsoft/terminal#8151]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Alright well, there's not really any actionable information in this issue, so I'm gonna close it. Please make sure to actually fill out the template with repro steps, version numbers, screenshots, anything that could be used to investigate your issue.

I'm also gonna try and be psychic and guess that you're using WSL, and the `startingDirectory` you've set is somewhere under `\\wsl$\`, right? If so, then this is already being tracked in #7197
