### ISSUE TITLE
Feature request: option to hide tab icons

### ISSUE THREAD

**Issue by wdscxsj** [microsoft/terminal#8157]
# Description of the new feature/enhancement

The `"compact"` [tab width mode](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings) hides inactive tab titles and only shows icons for them. With multiple tabs of a same profile, it's hard to tell the difference without a descriptive title (which is controllable from the shell).

A "compact" thing means to pack enough information into a small space, often in an unattractive way. A workaround is to use a non-existent `"icon"` target for all profiles in `settings.json`, but that's hacky, and doesn't save enough space as expected. Let's compare Terminal and [ConEmu](https://github.com/Maximus5/ConEmu), both snapped to the right half side of my screen:

![Screenshot046](https://user-images.githubusercontent.com/863369/98061542-051ae900-1e87-11eb-8389-a5db67c703b2.png)

Thus I propose a new tab width mode, say `"textOnly"`, that hides icons (even for the active tab) and shows compact titles only.

**Comment by zadjii-msft** [comment]
Thanks for the request! This is something that I've already got written down as an idea for #3327, so I'll make sure to link the two up ☺️

**Comment by austin-beer** [comment]
I would love to see this feature implemented as well. Hopefully some progress can be made on this as part of #3327.

**Comment by zadjii-msft** [comment]
> **Note**
> ## Walkthrough

I'm gonna combine this with a related ask for monochrome tab icons. 

* [ ] Start by modifying the `Tab` Theme object.
  * [ ] Add an `IconStyle` enum to `Theme.idl`, with `Default`, `Hidden` and `Monochrome` as options.
  * [ ] add a new property to `TabTheme` in `Theme.idl`. `Icon` which accepts an "IconStyle". 
  * [ ] In `MTSMSettings.h`, add a new setting under `MTSM_THEME_TAB_SETTINGS`. The key for this one should just be `"iconStyle"`
* [ ] Actually use this new setting
  * [ ] `TerminalTab::UpdateIcon` is probably the right place for this. You probably want to add another parameter to this. 
  * [ ] `IconPathConverter::IconSourceMUX` may need some plumbing to support colored OR monochrome icons.

**Comment by BenConstable9** [comment]
@zadjii-msft can I attempt to pick this up shortly?

**Comment by zadjii-msft** [comment]
Go for it ☺️

**Comment by zadjii-msft** [comment]
(you can also skip the monochrome bit if you want. I put that in the original spec because "I'm sure someone out there wants this" but I'm not actually sure anyone does)
