### ISSUE TITLE
Close an unfocused tab (using mouse) results in focus switched

### ISSUE THREAD

**Issue by bef178** [microsoft/terminal#816]
This bug comes with #737. Very sorry for not having a full test.

Repo:
open tab a,b,c,d
activate c
mouse close a
expect c is shown and is the only highlight in tabview
alt-1
expect b is shown and is the only highlight in tabview

**Comment by bef178** [comment]
Manual test cases:

open tab a,b,c,d
activate a
ctrl-w
ctrl-w
expect c is shown and is the only highlight in tabview

open tab a,b,c,d
activate a
mouse close a
mouse close b
expect c is shown and is the only highlight in tabview

open tab a,b,c,d
activate c
mouse close a
expect c is shown and is the only highlight in tabview
alt-1
expect b is shown and is the only highlight in tabview

open tab a,b,c,d
activate c
mouse close a
expect c is shown and is the only highlight in tabview
mouse activate b
expect b is shown and is the only highlight in tabview

open tab a,b,c,d,e
activate c
ctrl-w
ctrl-w
ctrl-w
expect d is shown and is the only highlight in tabview
ctrl-w
expect e is shown and tabview is hided

**Comment by bef178** [comment]
And is there any place to put manual test cases? In case of unconsciously / accidentally breaking other features.

**Comment by zadjii-msft** [comment]
We actually don't have any UI tests set up quite yet, though I think someone is working on them, so you don't really need to worry about adding them yourself quite yet.

**Comment by bef178** [comment]
I wish I will not break other features.

**Comment by binarycrusader** [comment]
> I wish I will not break other features.

Any work worth doing always has a chance of bugs, the important thing is to record them when found, learn the cause, and work on getting them fixed 🙌

**Comment by bef178** [comment]
You're right

**Comment by bef178** [comment]
The described behavior should be gone in master. Closing.

**Comment by zeimao77** [comment]
linux vim ctrl-w 
Switching the VIM window causes the terminal to close
