### ISSUE TITLE
Support Windows 10 Alt-Tab expansion for Terminal tabs.

### ISSUE THREAD

**Issue by hougaard** [microsoft/terminal#8160]
Windows 10 20H2 added support for expanding the Alt-Tab view with tabs from Microsoft Edge. 

![image](https://user-images.githubusercontent.com/3357237/98141485-866c7e80-1e7b-11eb-8b1a-f397b29dddce.png)

I would love for Terminal to have the same support, I love the concept of grouping all my active terminal session in one window from a screen real estate perspective, but switching to a specific session is now Alt-Tab then Ctrl-Tab.

**Comment by zadjii-msft** [comment]
Thanks for the request! We've actually already got this tracked over in #6783. Unfortunately, 

> This is not currently possible via public API. I'm going to close this for now, but bring it back when there's an SDK that would allow for us to accomplish it.

/dup #6783
