### ISSUE TITLE
Pane operation demands

### ISSUE THREAD

**Issue by 8solo** [microsoft/terminal#8164]
# Pane Split & Switch Mode

1. Add pane split mode that made panes equal-width and equal-hight like iterm2
2. Add key binding in switch pane that support switch pane with specific number, alt + direction is not such convinient

# Proposed technical implementation details (optional)

1. Split all pane in equal
2. Switch pane using number key binding like ctrl + 1

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. These requests are already being tracked by another issue on our repo - please refer to #1000 for more discussion.

More specifically, see:
1. #6002
2. #5803

/dup #6002
/dup #5803

P.S. The word "demands" is a bit _strong_ of a word to use when asking for new features - the word "request" might be more what you're looking for ☺️
