### ISSUE TITLE
An right click menu

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/terminal#8170]
# Description of the new feature/enhancement
An right click menu that allow you to select whether to paste, cut, copy. Here is a screenshot of what I mean: ![](https://i.imgur.com/bf3qcLU.png). It would solve the problem of accidently copying and pasting things into the terminals which occur really often

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3337 for more discussion.

/dup #3337
