### ISSUE TITLE
Tab re-order when running as Administrator doesn't work

### ISSUE THREAD

**Issue by newtoniumx3** [microsoft/terminal#8176]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Steps to reproduce
Open windows terminal as administrator (right click > "run as administrator")

# Expected behavior

Tab re-ordering should work.

# Actual behavior

Tab re-ordering is broken when windows terminal is running as administrator.

**Comment by alannt777** [comment]
seems to be related to #5564

But it's fixed. I had compared the versions.

**Comment by alannt777** [comment]
BTW, I *can* repro this issue.

**Comment by DHowett** [comment]
This is disabled on purpose. Sorry. 

More info at https://github.com/microsoft/terminal/issues/6893#issuecomment-657554241
