### ISSUE TITLE
Home and End keys do not work when connected through OpenSSH and ZSH

### ISSUE THREAD

**Issue by felipecrs** [microsoft/terminal#8179]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 1.3.2651.0
OpenSSH: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Ubuntu: 20.04.1 LTS
ZSH: zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

# Steps to reproduce

Connect from Windows to an Ubuntu server through the builtin OpenSSH:

```jsonc
{
        "guid": "{2c4de342-38b7-51cf-b940-2309a097f519}",
        "name": "Ubuntu (SSH)",
        "commandline": "ssh -o ServerAliveInterval=240 root@ubuntu-desktop"
},
```

# Expected behavior

The Home and End key to properly work.

# Actual behavior

![lwz7taVYTd](https://user-images.githubusercontent.com/29582865/98378782-54822600-1ffb-11eb-9139-8568356837fd.gif)

**Comment by DHowett** [comment]
The Windows build of OpenSSH 7.7 has its own “input generator” that does not properly handle Home and End. You can upgrade to a newer version of use the SSH client from WSL. :smile:

**Comment by felipecrs** [comment]
In that case, I wonder how it works in VSCode with the Remote - SSH extension. I don't face this problem in VSCode integrated terminal and I doubt it uses WSL's OpenSSH. 

Do you know anything about it? Perhaps the Remote - SSH extension carry its own OpenSSH?

**Comment by felipecrs** [comment]
![image](https://user-images.githubusercontent.com/29582865/98679279-87e7ec00-233e-11eb-9598-6f84a9035713.png)

The same issue persists even with the latest version of OpenSSH. I believe this is something else since as I said, it works properly in VSCode integrated terminal.

/cc @DHowett

**Comment by DHowett** [comment]
Glad it works. :smile:

**Comment by felipecrs** [comment]
By the way, if others run into this problem, this is the steps to fix it currently:

```sh-session
choco install openssh --version 8.1.0-beta
```

Then, make sure you have `C:\Program Files\OpenSSH-Win64` before `C:\Windows\System32\OpenSSH\` in your `PATH` environment variable:

![83FC8OjXgI](https://user-images.githubusercontent.com/29582865/107235818-d7a08700-6a03-11eb-869a-005a7f8dc732.gif)

**Comment by willparsons** [comment]
I get this same issue but just with git bash.

**Comment by willparsons** [comment]
Sorry, I mean I'm not even using ssh, just git bash by itself is doing this.

**Comment by felipecrs** [comment]
Here I do not have this problem, and just out of curiosity, this is my Git Bash profile in Windows Terminal:

```json
{
  "commandline": "\"%PROGRAMFILES%\\git\\usr\\bin\\bash.exe\" -i -l",
  "guid": "{00000000-0000-0000-ba54-000000000002}",
  "icon": "%PROGRAMFILES%\\Git\\mingw64\\share\\git\\git-for-windows.ico",
  "name": "Git Bash",
  "startingDirectory": "%USERPROFILE%"
}
```

And I'm using the latest version of both Git Bash and WT.

**Comment by willparsons** [comment]
Seems like windows terminal preview doesn't flicker.

**Comment by zhouzhendiao** [comment]
`export TERM=xterm-256color` on server works, Ubuntu ssh to Centos

**Comment by sryze** [comment]
Same issue with Home/End keys in Preview 1.16.3463.0, but without SSH, just plain Git Bash.

**Comment by pedroangelini** [comment]
OK - I had a similar problem, I think it has something to do with multiple layers of special-character treatment.
I'm running `Windows Terminal  1.22.12111.0`, `git for windows 2.50.1.windows.1` (including git bash) and ssh client `OpenSSH_10.0p2, OpenSSL 3.2.4 11 Feb 2025`.
If open a `cmd` terminal profile and use ssh to connect to my Debian server, the Home and End keys work normally. If I do it from git bash, the keys don't work. 
I'm not smart enough to debug this deeply, but what worked for me was to set `TERM=xterm-256color`, by adding `SetEnv TERM=xterm-256color` my git `~/.ssh/config` file for the host in question. 
Now when running ssh both via git bash and cmd, the Home and End keys work normally.
