### ISSUE TITLE
When saving new settings should check for missing font and alert.

### ISSUE THREAD

**Issue by bwilsonms** [microsoft/terminal#8180]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal Preview
Version: 1.4.2652.0

Any other software?
```

# Steps to reproduce

1. Download LiterationMono NF font from nerdfonts.com
2. Edit settings for pwsh 7+ with the following lines:
                 "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "useAcrylic": true,
                "acrylicOpacity": 0.7,
                "fontFace": "LiterationMono NF ",    <<<<<< Notice trailing space
                "colorScheme": "Frost",
                "cursorColor" : "#000000",

# Expected behavior
An alert that font is not found

# Actual behavior
Setting file saves without warning but font is not found and icon packs are not in use.

**Comment by miniksa** [comment]
Thanks for the report!

This happens to be a duplicate issue, but I'll go try to make sure the linked issue is ranked for Terminal 2.0.

/dup #1017
