### ISSUE TITLE
exit command failure

### ISSUE THREAD

**Issue by ayaankhan98** [microsoft/terminal#8186]
# Environment

```none
Windows build number: 10.0.18363 Build 18363
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Steps to reproduce
After working for a while if we type `exit` then instead of closing the current tab it shows `[process exited with code 1]` but doesn't closes the tab and disables the keyborad input therefore no further command can be typed.

# Expected behavior
on `exit` it tab must be closed

# Actual behavior
not closing the tab showing  `[process exited with code 1]`

**Comment by alannt777** [comment]
The shell is returning a non-zero exit code. So the Terminal does not close the tab to let you see it.

You can add 
```json
"closeOnExit": "always"
```

to your profile

**Comment by DHowett** [comment]
Correct!
