### ISSUE TITLE
Custom icons in the jump taskbar list

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#8187]
# Environment

```none
Windows build number: Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.4.2652.0
```

# Steps to reproduce
Add something with a custom icon. For example:
```
 // Backup server
"name": "Backup",
"guid":  "{5061f744-37f9-4c7c-aba5-51fa0789ee01}",
"icon": "C:/Users/Mystic/OneDrive/Software/Resources/Icons/Terminal/centos.png",
"commandline": "ssh user@ip",
"suppressApplicationTitle": true,
"tabColor": "#147967",
"fontFace": "MesloLGS NF",
"fontSize": 9,
"cursorShape": "vintage",
"historySize": 9001  
``` 
And my icons are [here](https://1drv.ms/u/s!AuvdOhv7oayD7CkXX16Cu9uUrMIP?e=Zb6fhO)

# Expected behavior

Icons are displayed on the taskbar (by right-clicking)

# Actual behavior

Only the standard powershell icon is displayed
![image](https://user-images.githubusercontent.com/35394377/98438175-96919180-20f9-11eb-885f-487cd7b9d1e3.png)

But everything is fine in the terminal itself.
![image](https://user-images.githubusercontent.com/35394377/98438147-56caaa00-20f9-11eb-91ba-f03173503ad5.png)

**Comment by ShubhamBelwal** [comment]
> "icon": "C:/Users/Mystic/OneDrive/Software/Resources/Icons/Terminal/centos.png",

Convert the `/` to `//` or `\\`.

More information in thread #7706

**Comment by Mystic8b** [comment]
Need to be replaced all the way, or just at the beginning? If it's not difficult, can you give an example? Maybe I'm doing something wrong, but nothing has changed for me.

**Comment by ShubhamBelwal** [comment]
Change it to:

"icon": "C://Users//Mystic//OneDrive//Software//Resources//Icons//Terminal//centos.png",

**Comment by Mystic8b** [comment]
It didn't work for me. Only like this:
`"icon": "C:\\Users\\Mystic\\OneDrive\\Software\\Resources\\Icons\\Terminal\\centos.png",`

**Comment by ShubhamBelwal** [comment]
Cool. If your issue has been fixed you can close this issue now.
