### ISSUE TITLE
Command Palette: page up/down "wrap" backwards when you're too close to the bottom of the list

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#8189]
We may need to clamp the index when moving down/up.

![A video of me reproducing the issue.](https://user-images.githubusercontent.com/189190/98450751-23d1e780-20f4-11eb-9177-df73262b1a12.gif)

/cc @Hegunumo

**Comment by Don-Vito** [comment]
@DHowett - I was sure it was a feature when it was released 😄

**Comment by Hegunumo** [comment]
Sorry I didn’t notice that.

**Comment by Don-Vito** [comment]
@Hegunumo - please ignore my PR if you want to work on this. I did something quick and dirty. I will gladly abandon it if you are working on this.

**Comment by Hegunumo** [comment]
@Don-Vito - Oh it's fine. You don't need to abandon it.

**Comment by Don-Vito** [comment]
> 
> 
> @Don-Vito - Oh it's fine. You don't need to abandon it 😊

Then may I ask you to help reviewing it? :blush:
