### ISSUE TITLE
Alt-* makes a bell noise

### ISSUE THREAD

**Issue by bef178** [microsoft/terminal#819]
> This makes a bell noise everytime I switch to a tab via alt+1, alt+2 etc.

_Originally posted by @krokofant in https://github.com/microsoft/terminal/issues/573#issuecomment-491463293_

Test shows alt-number/letter/punctuation all will produce a bell.

**Comment by zadjii-msft** [comment]
I'm trying to dig in to this a bit, but I haven't had any luck quite yet. 

I have found this documentation that might point in the right direction:

https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh868161(v=win.10)#keyboard-shortcuts

> * An access key is a shortcut to a piece of UI in your app. Access keys consist of the Alt key plus a letter key.

Maybe there's something else in the stack that's trying to look for access keys when Alt+key is pressed.

This very noticeably only repros with Alt+key or Alt+Shift+key. Alt+Ctrl+key does _not_ produce the sound.
