### ISSUE TITLE
how to specify startingdirectory when terminal launch?

### ISSUE THREAD

**Issue by candrewtemenoscom** [microsoft/terminal#8192]
I tried to specifying it in startingdirectory in setting.json. But it does not work. I would like to set the directory when I launch the terminal.

**Comment by LuanVSO** [comment]
how does it not work? 
mind sharing your settings.json?

**Comment by alannt777** [comment]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#starting-directory

**Comment by zadjii-msft** [comment]
Yea you gotta give us some more info. What have you set it to? What's the `commandline` you're using? By any chance, are you using a WSL distro (which might make this #7197)?

**Comment by candrewtemenoscom** [comment]
It is working now. I put the startingdirectory property in the wrong section. Now I moved it to the default profile. Thanks for the quick response and the pointers.

A quick suggestion. I find that sometimes it is not easy to know where to set the property and its value especially when there are multiple nested properties. I find that the swagger doc for setting properties in its json file quite intuitive in which it pre-specify (but commented out) all the optional property and users can choose to enable it by uncommenting out the property. It prevents making mistakes.

**Comment by zadjii-msft** [comment]
I'm glad you were able to figure it out!

We actually previously would include all the possible properties in the settings file, but it turned out to be much to unwieldy. There's just a lot of settings, and it largely made the file harder to read. Hopefully this won't be much of an issue when the settings UI ships (soon<sup>TM</sup>)
