### ISSUE TITLE
Pasting too many lines into Terminal results in disconnect. Also ssh -L disconnects if I send too many lines of text to server. This does not happen on Putty.

### ISSUE THREAD

**Issue by SebastianDix** [microsoft/terminal#8196]
**Microsoft Windows [Version 10.0.19041.572]**      
Windows terminal version 1.3.2651

Any other software?
Chrome, but not necessary to reproduce
# Steps to reproduce

in windows terminal open Ubuntu Focal
ssh to remote server
open vim
:set paste
paste ~100 lines of text
observe the remote host disconnecting

OR
connect to remote host and then
just paste any larger (like more than 20 lines of text) code into terminal and try to run it 

OR
ssh -L (local port forwarding) from port localhost:1234 on local computer to external host port 5000. Then run an app (I use python Flask development server) on port 5000
then when you access localhost:1234 on local machine, try submitting a lot of text (more than 20 lines) through html form - the local port forwarding will disconnect

# Expected behavior

Accept pasting / submitting of multi-line input

# Actual behavior
Remote host disconnects (but doesn't from Putty) - wrong Message Authentication Code

When I run port forwarding through putty, or paste multi-line text into putty or do any of the steps in Putty, nothing happens, everything is fine.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7601 for more discussion.

/dup #7601
