### ISSUE TITLE
Tab tooltip is empty when zooming pane

### ISSUE THREAD

**Issue by mpela81** [microsoft/terminal#8199]
# Environment
```none
Microsoft Windows [Version 10.0.19041.572]

Windows Terminal version (if applicable): dev mainline
```

# Steps to reproduce
- Split pane
- Zoom pane
- Hover on the tab

# Expected behavior
The tooltip shows the active title

# Actual behavior
The tooltip is blank

**Comment by mpela81** [comment]
As I can see it, when pane is zoomed the tab's header is set with a `StackPanel` including zoom icon and title, instead of just the title. The tooltip isn't shown automatically in that case.

Fix may be just setting the tooltip explicitly in this case.

**Comment by zadjii-msft** [comment]
Good catch!

Maybe when we're thinking about doing this, we should add a little blurb like "(zoomed)" or "15%" (for the progress in #6700) to the tooltip as well
