### ISSUE TITLE
Running ngrok.exe from WSL hangs

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#82]
_From @CherryDT on August 16, 2017 11:28_

Windows build number:  15063.540

I have the Windows version of [ngrok](https://ngrok.io) stored in a folder in DrvFS.

When I run ngrok.exe in Windows as `ngrok.exe http 3000`, it instantly connects and displays the status.
When I run it in WSL, it appears to hang and do nothing. (Ctrl+C will go back to bash but not close ngrok.exe, but that's probably due to #1614.) Running only `ngrok.exe` which just outputs the usage help works fine.

_Copied from original issue: Microsoft/WSL#2428_

**Comment by bitcrazed** [comment]
_From @benhillis on August 17, 2017 19:10_

Thanks for reporting this.  It looks like ngrok doesn't handle redirected output (when the output of the program is a file or a pipe).  When launching NT processes via interop stdin / stdout / stderr will look like pipes or files to the Windows process.  We have some plans to make our tty / pty file descriptors behave like Windows console handles in the future.

**Comment by miniksa** [comment]
This is old, it needs a re-repro.

**Comment by DHowett-MSFT** [comment]
Presuming that this was because "It looks like ngrok doesn't handle redirected output", we may just want to close this since WSL moved to ConPTY.
