### ISSUE TITLE
Scrolling with the keyboard doesn't update the scrollbar

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#821]
Use Ctrl+Shift+Arrows/PgUp/PgDn to scroll the contents of the buffer. 

Expected: The scrollbar on the control updates as the viewport moves.

Actual: It doesn't.

From discussion in #747.

**Comment by Kapperchino** [comment]
@zadjii-msft Quick question, what checks do I need to do for the scroll bar. Currently I just set the value without doing much checking other than clamping it.

**Comment by zadjii-msft** [comment]
You probably need this bit from `void TermControl::_MouseScrollHandler(const double mouseDelta)`

```
        // Clear our expected scroll offset. The viewport will now move in
        //      response to our user input.
        _lastScrollOffset = std::nullopt;
```

Otherwise you can get some real weird behavior if (for example) the terminal is currently outputting text and the user tries to scroll with the mouse/keyboard

**Comment by zadjii-msft** [comment]
Hey look, this was merged
