### ISSUE TITLE
"theme": "dark" has no effect in 1.4.2652.0

### ISSUE THREAD

**Issue by savchenko** [microsoft/terminal#8210]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): v1.4.2652.0
```

# Steps to reproduce

1. Add `"theme": "dark"` to your settings.
2. Ensure "App mode" is set to light "Light":
![image](https://user-images.githubusercontent.com/300146/98670673-efa43400-234a-11eb-9591-17a73a65c1e1.png)
3. Launch Terminal

# Expected behavior

Terminal has "dark" look, like this:
![image](https://user-images.githubusercontent.com/300146/98670748-106c8980-234b-11eb-8fba-33b8de8ad854.png)

# Actual behavior

Terminal disregards `theme` property:
![image](https://user-images.githubusercontent.com/300146/98670808-2c702b00-234b-11eb-9d4c-1b3f21a2122c.png)

**Comment by zadjii-msft** [comment]
Did you restart the Terminal after changing `theme` to `dark`? I think that's one of the few properties that doesn't hot-reload

**Comment by savchenko** [comment]
> Did you restart the Terminal after changing theme to dark? 

Yes.

**Comment by zadjii-msft** [comment]
Well that's certainly weird. Could you share your entire `settings.json` file?

**Comment by savchenko** [comment]
@zadjii-msft , https://github.com/stoptracking/playbook/blob/442bdff131ab5f9c07223cff4e48129f5d8d3023/roles/dotfiles/files/wt.json

**Comment by DHowett** [comment]
Move `theme` up above line 4. It's what we consider an "application" setting -- it doesn't apply to a profile, so it doesn't go in the profiles section.

**Comment by savchenko** [comment]
> Move theme up above line 4.

Works, thank you.
