### ISSUE TITLE
Implement session reset feature

### ISSUE THREAD

**Issue by Fiury00** [microsoft/terminal#8211]
# Description of the new feature/enhancement

I would like to have a possibility to reset terminal (like it is in vscode) so I would not have to close this one and open new one. This is especially useful when connecting to Linux over ssh and there is need to restart server/session.

# Proposed technical implementation details (optional)

Maybe right click on the tab of the relevant terminal window.

**Comment by zadjii-msft** [comment]
Thanks for the request! I think in general, we're tracking this over in #4772. That one's a _little_ different (automatically reconnect vs have a manual button to restart), but I think the fundamentals are the same.

/dup #4772
