### ISSUE TITLE
Allow to start a profile directly from Windows taskbar

### ISSUE THREAD

**Issue by Fiury00** [microsoft/terminal#8212]
# Description of the new feature/enhancement
It would be nice to have a possibility to start a chosen profile directly from the icon pinned to Windows taskbar. Now we can only start Windows Terminal with the default profile.

# Proposed technical implementation details (optional)
Extend context menu of the Windows Terminal application pinned to Windows taskbar.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22taskbar+context+menu%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #576 for more discussion.

/dup #576

(This already shipped in Terminal Preview 1.4 😉)
