### ISSUE TITLE
New Tabs do not read Environmental variables a-new

### ISSUE THREAD

**Issue by kingfetty** [microsoft/terminal#8217]
WindowTerminal Version: 1.3.2651.0
Windows 10 1909 build 18363.1139

**Summary:**

If you've already opened windows terminal and change an environmental variable such as PATH and then spawn a new tab, the new tab does not include the latest updates to the variable.  This requires users to completely close the entire windows terminal application to get it to read the variable.  Each sub process / tab should read the environment variables anew on spawn preventing the need to close any windows that may be open already and losing possible work in the process.

**To reproduce:**

- Open Windows Terminal and have an existing window opened
- Change the system path to include a new test item in the path
- spawn a new tab in the existing windows terminal
- echo the system path and note that the changed path is not included

**Comment by j4james** [comment]
I think this might be a dup of #1125.

**Comment by DHowett** [comment]
Indeed. This was fixed in #7243, but I have been holding it back from Stable builds because it breaks WOW64 PowerShell. (#7418). /dup #7243
