### ISSUE TITLE
Just feedback

### ISSUE THREAD

**Issue by hsmgitr** [microsoft/terminal#8223]
I love this new terminal, Just what I have been looking for

**Comment by skyline75489** [comment]
Thanks for the positive feedback. I think we mark this as a dup of #7428 . Maybe in the future we should just pin #7428 on the top ? So people actually have a centered thread for it.

**Comment by DHowett** [comment]
Thanks for the positive feedback! The team really loves hearing that folks appreciate their work. :smile:
I'll merge this with /dup #7428 for now.
