### ISSUE TITLE
Not accepting keystrokes

### ISSUE THREAD

**Issue by opensslonzos-github** [microsoft/terminal#8226]
After the Windows update on 11/10, my machine restarted and now the Windows Terminal does not accept keystrokes.
I have tried all forms of input that I can think of including running OSK (on screen keyboard).
I can type into every other application on my system except Windows Terminal
I can drop down the menu containing "About",. "Settings", and all of the configured terminals I have.  Once that is down, I can move up and down with arrows.  I can select a terminal to open and a new window will be created and it will run whatever is configured to run (OpenSSH, PowerShell, CMD.exe) which will start up in a new tab as expected.
Once the tab is up and running, no keys are passed into the shell.
I have tried Powershell, CMD.exe and OpenSSH.  None of them are getting anything I type. 
Nothing.

# Environment
```
Windows build number:   Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0
Any other software?  I am a developer, so Visual Studio and about a hundred other things. None of them have updated recently.
```

# Steps to reproduce

Start Windows Terminal.  Allow the default window to be created (which is powershell for me)
Type "dir" or "ls" or anything.   Nothing is echoed to the terminal window.
Run OSK and use it to type characters into the Windows Terminal window.  Nothing happens.
Run Notepad. Type letters. All works as expected. I see letters appear in Notepad.
Run Powershell by itself (not inside Windows Terminal).  All works as expected. Commands run, letters are echoed. Joy
Run CMD.exe by itself (not inside Windows Terminal).  All works as expected. Commands run, letters are echoed. Joy

# Expected behavior

Powershell starts normally and is sitting waiting for me to type a command.
There is a blinking cursor there.
I can select the text in the window.
I expect to type commands into the shell, see the commands echoed to the terminal and have them execute.

# Actual behavior

Shell starts fine.
When I type, no characters appear in the shell, so no actions are taken.

**Comment by zadjii-msft** [comment]
Please search for duplicates before filing new issues. See: #4448, #8045

/dup #4448 
/dup #8045
