### ISSUE TITLE
Some panes stop resizing after other panes are closed

### ISSUE THREAD

**Issue by valorin** [microsoft/terminal#8230]
There appears to be an issue caused by animations when panes are closed. With animations enabled and multiple panes (3+) in use, when you close a panel and attempt to resize the remaining panes, some of the panes don't resize correctly. I haven't tested extensively, however it appears that the created panes are the ones that cannot resize, while the original pane does get resized.

This is on the new Preview that was released today.

**UPDATE:** This doesn't appear to require animations enabled. I've experienced it with animations disabled when moving around and closing panes. It seems to be triggered first by removing a pane, as everything works as expected until I close something. After that point, the behaviour is weird and some panes stop resizing.

I'll leave the steps below as-is, as that's the most reliable way to replicate that I've discovered.

# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: Preview 1.5.3142.0
```

# Steps to reproduce

1. Ensure animations are enabled in the config (`"disableAnimations": false`),
2. Split the terminal into three panes. I've been using a vertical then a horizontal split:
    ```
    { "command": { "action": "wt", "commandline": "split-pane -V ; split-pane -H" }, "keys": "ctrl+alt+shift+l" },
    ```
3. Close the second panel. For me this is top-right. _The third pane correctly resizes to fill the gap left from the closed panel._
4. Resize the remaining pane divider

# Expected behavior

The pane divider should resize, with both panes included.

# Actual behavior

The first pane is resized, but the second (originally the third) stays where it is. As a result, you either have a gray gap between the two panes, or the first pane covers up the second pane.

Toggling `"disableAnimations": true` to disable animations fixes the issue and the panes resize correctly.

**3 panes showing `top` before the second pane is closed**

![image](https://user-images.githubusercontent.com/897369/98879873-425c2800-24d2-11eb-9640-2615968dd260.png)

**Remaining two panes showing the second pane no resizing with the the first:**

![image](https://user-images.githubusercontent.com/897369/98879968-6a4b8b80-24d2-11eb-900d-46e05490c7c1.png)
![image](https://user-images.githubusercontent.com/897369/98879974-6e77a900-24d2-11eb-8a3d-3ffd40351f06.png)

**Comment by Don-Vito** [comment]
@valorin - for me the problem occurs only when animations are enabled. Could not reproduce it with animations disabled.

**Comment by valorin** [comment]
Yeah that's exactly what happened with me. It's simple with animations, but harder and more random without them.

**Comment by Don-Vito** [comment]
BTW, it looks that disabling animation applies only to the "close pane" animation, but not to pane entrance animation.
@zadjii-msft - is it intentional?

**Comment by zadjii-msft** [comment]
@Don-Vito It most certainly is _not_

**Comment by Don-Vito** [comment]
> 
> 
> @Don-Vito It most certainly is _not_

NP. I creating a PR to allow disabling :blush:

**Comment by Don-Vito** [comment]
In any case with animations fully disabled (both close and entrance), I am currently unable to reproduce the issue.. of course probably the issue is somewhere else and animations just increase the probability.

**Comment by Don-Vito** [comment]
@zadjii-msft  - I think I have a direction here 😊 This is a race. If you split the panes manually and slowly (aka after the animation has finished) no problem occurs. 

My guess is that in the completion of the animation, when you access the pane, it already has other children. Checking this

**Comment by Don-Vito** [comment]
@zadjii-msft - actually I am not sure what is the best fix. What I am doing in PR is to ensure that the correct control gets the stretch alignment back. 

However the problem is more severe: during the animation the pane children might change. This applies not just for entrance animation but for the close animation as well. I am not sure what should be the approach - to lock the panes during the animation?

**Comment by Don-Vito** [comment]
Related to https://github.com/microsoft/terminal/issues/7942

**Comment by zadjii-msft** [comment]
You know, locking the panes during the animation _sounds_ like a really good idea, one that would probably resolve a whole host of these issues.
