### ISSUE TITLE
HyperLink CTRL Clicking in Windows Terminal Preview v1.5.3142.0 not working

### ISSUE THREAD

**Issue by NinjaRMMTheming** [microsoft/terminal#8232]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Held down CTRL and clicked link. Rebooted computer and started fresh terminal, same result.

# Expected behavior

URL should open from terminal

# Actual behavior

Nothing happened. Hovering over showed hyperlink underline but clicking did nothing

**Comment by DHowett** [comment]
Some application must have displayed the link you tried to click, but you didn’t list anything in the “additional software” section. Alas, this means we can’t actually help.

**Comment by NinjaRMMTheming** [comment]
Sorry, I actually used the default powershell link that shows in PWSH to test

https://aka.ms/powershell


Thye link shows and highlights in Windows Terminal, but wont actually go to the site.





Thanks,

Dennis Fair  |  I.T Systems Admin
Four Peaks Landscape Management
p: 480-967-0376<tel:480-967-0376>  |  f: 480-967-0406
m: 480-319-5345<tel:480-319-5345>
e: it@fourpeakslandscape.com<mailto:it@fourpeakslandscape.com>
[http://fourpeakslandscape.com/images/four-peaks-landscape-management.png]



________________________________

**Comment by NinjaRMMTheming** [comment]
Okay, just tried it on my work computer and seems to be working. Something is obviously going on with the computer I used last night. I apologize. All is well. Sorry for the bogus ticket.




Thanks,

Dennis Fair  |  I.T Systems Admin
Four Peaks Landscape Management
p: 480-967-0376<tel:480-967-0376>  |  f: 480-967-0406
m: 480-319-5345<tel:480-319-5345>
e: it@fourpeakslandscape.com<mailto:it@fourpeakslandscape.com>
[http://fourpeakslandscape.com/images/four-peaks-landscape-management.png]


________________________________

**Comment by zadjii-msft** [comment]
No problems, thanks for following up!

**Comment by joshuabiddle** [comment]
Is there a way to get this to work for opening html files on remote computers? If I type "& \\UNC\to\file.html" it will open, and if I try to plug that in to this function it attempts to link it but it doesn't open.
