### ISSUE TITLE
explorer.exe crashes when selecting profile from the jumplist

### ISSUE THREAD

**Issue by arknu** [microsoft/terminal#8234]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3141.0

Any other software?
```

# Steps to reproduce

Select a profile from the jumplist (either on the taskbar or in the start menu). 

# Expected behavior

Windows Terminal opens with the selected profile.

# Actual behavior

explorer.exe crashes and Windows Terminal doesn't open.

**Comment by zadjii-msft** [comment]
Well that's just the darndest thing. I don't have the faintest clue why that might be happening - are there any events that are logged to the Event Viewer? Do jumplist entries from other applications still work? Do you have any sort of anti-virus software installed?

I'd think it shouldn't be possible for an app to register a jumplist item in such a way that would cause _explorer_ to crash, but I guess here we are.

**Comment by arknu** [comment]
I have the following in Event Viewer:

```
Navn på program med fejl: explorer.exe, version: 10.0.19041.610, tidsstempel: 0xab30c679
Navn på modul med fejl: KERNELBASE.dll, version: 10.0.19041.572, tidsstempel: 0x1183946c
Undtagelseskode: 0x0eedfade
Forskydning med fejl 0x0000000000023e49
Proces-id 0xa954
Programmets starttidspunkt 0x01d6b8ce5d08ec6c
Programsti: C:\WINDOWS\explorer.exe
Modulsti: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: 28e6167c-79dd-4cd8-8a78-d17d9d235906
Fuldt navn på program med fejl: 
Relativt program-id for program med fejl: 
```

**Comment by zadjii-msft** [comment]
Okay, well that's good that it's getting logged there. Would you mind reproing this again, but this time with the Feedback Hub tracing the issue?

You can do this with the "recreate my problem" button in the feedback hub, after picking "Desktop Environment" / "Taskbar" as the category
![image](https://user-images.githubusercontent.com/18356694/98923868-d231b000-2499-11eb-9285-3b11b9ce36a3.png)

Once you've filed the feedback, can you share the link it gives you? We can use that to follow up with the taskbar team. Thanks!

**Comment by arknu** [comment]
Here you go: https://aka.ms/AAabo7b

**Comment by DHowett** [comment]
So, in your feedback item I found one pretty interesting thing. There's a library crashing explorer called **PASHLEXT64**. That looks like PowerArchiver.

If you disable PowerArchiver, does it stop crashing?

It looks like they're mishandling something about packaged applications. That's not good, but that'll need to be fixed on their side.

**Comment by DHowett** [comment]
/dup #7702

It looks like one of our community members has already reached out to them. "The beta/RC version ... doesn't seem to have the issue"

**Comment by arknu** [comment]
@DHowett Thank you! I updated to PowerArchiver 2021 (v 20.00.58) and it now works. I had no idea that shell extensions were involved when activating a jumplist item.
