### ISSUE TITLE
Release notes uses `useTabSwitcher` while it should be `tabSwitcherMode`

### ISSUE THREAD

**Issue by DevWouter** [microsoft/terminal#8235]
The release notes of https://github.com/microsoft/terminal/releases/tag/v1.5.3142.0 describe the following:

> * The tab switcher is now more flexible: you can use it in Most-Recently Used (MRU) order, in tabstrip order, or not at all (#8076)
>   * There's a new global setting, `tabSwitcherMode`, which supports the following enumerated values: `mru`, `inOrder` or `disabled`

But the global setting that one needs to change in this version is `useTabSwitcher` and not `tabSwitcherMode`

**Comment by zadjii-msft** [comment]
I'm pretty sure both settings will actually work 
https://github.com/microsoft/terminal/blob/d5bfd237e55cd88fca6df9a882d77ff92fb714f6/src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp#L40-L41
https://github.com/microsoft/terminal/blob/d5bfd237e55cd88fca6df9a882d77ff92fb714f6/src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp#L290-L294

They both end up deserializing to the same member. Is `tabSwitcherMode` _not_ working for you?
