### ISSUE TITLE
Crash opening/closing close... submenu multiple times

### ISSUE THREAD

**Issue by mpela81** [microsoft/terminal#8238]
# Environment

```none
Windows 10.0.19041.572
Windows Terminal Preview Version: 1.5.3142.0
```

# Steps to reproduce
The application exits when you:
- right click a tab to open context menu
- hover to open the Close... submenu
- click away to close the menu
- repeat until it crashes

![crash1](https://user-images.githubusercontent.com/1140981/98926692-ed231500-24d7-11eb-8ff4-dd220f445029.gif)

# Expected behavior
It does not crash

# Actual behavior
It crashes

# Other info
Feedback hub link: https://aka.ms/AAabnvq

See also https://github.com/microsoft/terminal/pull/7728#issuecomment-701365493 and https://github.com/microsoft/terminal/pull/7728#issuecomment-704909853. Unfortunately I don't know how to debug it myself...

**Comment by zadjii-msft** [comment]
Oh hey, I'm glad there's an actual issue for this now. We've known about this for some time, just never filed an issue for it. 

We're pretty confident that this is a XAML Islands bug, but it'll be good to have a thread tracking it on our side.

**Comment by zadjii-msft** [comment]
I'm punting this to 2.0, because we don't have LoS on a fix from the Terminal side. It might need a system XAML fix, which would be especially annoying.

**Comment by zadjii-msft** [comment]
Oh NO. This is also gonna have to block #1571. People really want to stick their profile in nested menus. As soon as this is available, people are going to use it, and inevitably hit this. Yikes.

**Comment by sylveon** [comment]
It would be awesome if you could push internally for a fix because this is blocking on my app too.

**Comment by NeilMacMullen** [comment]
FWIW I think there is an easier repro case if you need one.  Just open the context menu and move the mouse up and down...
![termreproc](https://user-images.githubusercontent.com/9131337/106490226-82b5bb80-64ad-11eb-8bb1-30974d35b85e.gif)

**Comment by mpela81** [comment]
I suppose this is going to take some time to be fixed at the system XAML level. Considering the context menu is not so crowded at the moment, would it be bad placing the items right above the Close one, for the time being? At least people could use the feature.
![immagine](https://user-images.githubusercontent.com/1140981/114271501-f0ccb080-9a11-11eb-9e2c-3426cda95f28.png)

**Comment by sylveon** [comment]
Seeing as the upstream issue is flagged needs-winui-3, I don't even expect it to get ever fixed in system Xaml islands (which is annoying me because I can't migrate to WinUI 3 right away it's missing features from system Xaml I rely on)

**Comment by mpela81** [comment]
> Considering the context menu is not so crowded at the moment, would it be bad placing the items right above the Close one, for the time being? At least people could use the feature.

I'm sending a PR for this, feel free to throw it away if you don't like it 😄
