### ISSUE TITLE
v1.4.3141.0 show Windows Terminal (Preview) when right clicked on Task Bar

### ISSUE THREAD

**Issue by ShubhamBelwal** [microsoft/terminal#8239]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18363.900]
Windows Terminal version (if applicable): 1.4.3141.0
```

# Steps to reproduce

1. Open Windows Terminal
2. Right Click on the Windows Terminal Icon in the Task Bar

# Expected behavior

Windows Terminal should be displayed

# Actual behavior

Windows Terminal (Preview) is displayed in the Task Bar

![image](https://user-images.githubusercontent.com/36201797/98927779-fd9ab600-24fe-11eb-9dea-f2ef672c4e5a.png)

**Comment by zadjii-msft** [comment]
That's bizarre, this doesn't repro for me:
![image](https://user-images.githubusercontent.com/18356694/98951677-2bacd580-24c0-11eb-8af3-686dc699ce4a.png)

Maybe we're using the wrong resource to populate the app name?

**Comment by ShubhamBelwal** [comment]
The issue is gone for me as well.

![image](https://user-images.githubusercontent.com/36201797/98952670-bb36a080-2521-11eb-9dbb-a09fc19f4af7.png)


The screenshot was taken a couple minutes after upgrading to the latest version. 
Do you plan on investigating it further? If not, I can close it.

**Comment by zadjii-msft** [comment]
Weird. Since there's no live repro, I'd say there's not gonna really be a way for us to investigate it any further. Thanks for following up though!
