### ISSUE TITLE
a new wsl ubuntu 18.04 install failed with code 0x8007001

### ISSUE THREAD

**Issue by wyfha** [microsoft/terminal#824]
The installation follows these two documents: https://docs.microsoft.com/en-us/windows/wsl/install-on-server and https://docs.microsoft.com/en-us/windows/wsl/install-manual
The previous steps had some minor problems but were not fatal until the execution of ubuntu.exe, the ubuntu folder only has a ubuntu1804.exe but not ubuntu.exe so I executed the ubuntu1804.exe, but immediately received an error:
`Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070001
Error: 0x80070001 ??????

Press any key to continue...
`
the attachments

[logman-ubuntu-exe.zip](https://github.com/microsoft/terminal/files/3183347/logman-ubuntu-exe.zip)

 is the logman of executed the ubuntu.exe

**Comment by zadjii-msft** [comment]
This belongs on the [WSL repo](https://github.com/microsoft/wsl)
