### ISSUE TITLE
Controlling tooltip delay for URLs

### ISSUE THREAD

**Issue by codenotworking** [microsoft/terminal#8242]
# Environment

```none
Windows build number: Windows 10 version 2004 (10.0.19041.0)
Windows Terminal version (if applicable): 1.4.3141.0
```

This isn't a bug, and I have no idea where to post a general question like this.  Is there a way to control the tooltip delay when hovering the mouse over a URL link?  Is there a setting for this?

I've searched through the [Windows Terminal documentation](https://docs.microsoft.com/en-us/windows/terminal/), but I didn't find it.

<img src="https://i.imgur.com/bvpfVup.png" />

**Comment by zadjii-msft** [comment]
Oh, no, there isn't a setting for that currently. _There should be_. Thanks for the request!

**Comment by DHowett** [comment]
I'd rather understand what the use case is -- and why it should be controllable -- before agreeing to add a feature. What's up? Do you want it to be shorter or longer? Why?

**Comment by codenotworking** [comment]
I personally want it to be shorter, instantaneous if possible, once the mouse hovers over a URL link.  As you can see in the screenshot I shared, it's not readily apparent that the text is a clickable URL link within a console output (the color and underlining is a result of a particular Python module I used).  There's no visual indicator, such as how HTML URL links generally stand out.  Having the tooltip appear much quicker, especially in a console output that has a lot of text, it can be easier to discern.

**Comment by zadjii-msft** [comment]
I don't disagree - I generally like my tooltip popups to be faster. FYI, there's also #7563, which IMO will really make the links more obviously clickable, but a shorter timeout won't hurt.

**Comment by PankajBhojwani** [comment]
As far as I know, the [tooltip service](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.tooltipservice?view=winrt-19041) and [tooltip](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.tooltip?view=winrt-19041) classes we use don't offer any way to change the delay for tooltip display (curiously enough, the [.NET Core version](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tooltipservice.initialshowdelay?view=net-5.0) does though). 

So I think the only way we can support this right now is by creating our own timer and tooltip.

**Comment by DHowett** [comment]
So, unfortunately, it looks like this is another platform limitation. Since I'd rather not implement yet another tooltip¹ and deal with the tens of different ways in which we'll get it wrong--not the least of which will be Accessibility related--I'm going to close this one out as "sorry, not now."

Tracking upstream at https://github.com/microsoft/microsoft-ui-xaml/issues/3820.

Thanks!

¹ I'm not even sure we _can_ do it inside our app because of the rules about xaml content displaying outside the window frame

**Comment by DHowett** [comment]
XMAL repo redirected me to https://github.com/microsoft/microsoft-ui-xaml/issues/2262.
