### ISSUE TITLE
Detaching panes and tabs

### ISSUE THREAD

**Issue by ivancho-ifa** [microsoft/terminal#8244]
Hello team!

First I want to congratulate you on the great job. The Terminal looks awesome! Here is a suggestion that I think will boost productivity and usability.

It would be nice if there is an option to detach tabs and panes to separate Terminal windows. This will be very useful when working with multiple screens or use consoles a lot.

My vision is to be able to drag and drop a tab out of the Terminal window so that it becomes a separate Terminal window which I could send to another screen or virtual monitor. To detach a pane I think there should be a palette command to send the current pane to a separate tab and then I could drag and drop it to a new window.

What do you think of the idea? Let me know if I could help with something!

Best regards,
Ivan Mollov

**Comment by zadjii-msft** [comment]
Thanks for the request! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+detach+tab+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256
/dup #7507
/dup #4587

**Comment by ivancho-ifa** [comment]
Sorry for the duplication!
