### ISSUE TITLE
Paste dialog overlay does not cover entire terminal window if resized

### ISSUE THREAD

**Issue by cdhgee** [microsoft/terminal#8245]
# Environment

```none
Windows build number: 10.0.19041.630
Windows Terminal version (if applicable): preview build 1.4.2652.0

Any other software? No
```

# Steps to reproduce

- Open a terminal window
- Resize the terminal to a larger size than its default size (or maximize the terminal window)
- Copy multiple lines of text from another program, such as notepad
- Paste using Ctrl-V or right-click
- The multi-line paste warning appears

# Expected behavior

The entire terminal window behind the dialog should be darkened. This screenshot shows the correct behavior when the terminal has not been resized.

![image](https://user-images.githubusercontent.com/1256233/98963743-96b0d900-24cd-11eb-9ba6-cbeada371072.png)

# Actual behavior

Part but not all of the terminal window behind the dialog is darkened; it appears that the darkened part is the same size as the terminal window's default size.

![image](https://user-images.githubusercontent.com/1256233/98963133-ee9b1000-24cc-11eb-9d8b-3ad598819ea6.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion. Although that's about a different dialog, the underlying issue will certainly have the same root cause.

/dup #2380
