### ISSUE TITLE
Profiles reappear after deleting them from settings.json

### ISSUE THREAD

**Issue by jschroedl** [microsoft/terminal#8246]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Could you give more details? which profiles?

**Comment by jschroedl** [comment]
oops, I thought I cancelled this. A coworker explained how PowerShell, Azure cloud shell and other profiles keep getting re-added to my list. Lost a LOT of time before I asked around.  He pointed out that I need hidden = "true" in settings.json which fixed it for me. So undiscoverable!  This is maddening behavior btw.

**Comment by zadjii-msft** [comment]
I mean, there is a [whole docs page](https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles) dedicated to this functionality...

I'm glad you were able to figure it out, hopefully it will help other people searching for issues in the future.
