### ISSUE TITLE
Acrylic/Semi-Transparent when lost focus instead of when focused

### ISSUE THREAD

**Issue by tigerinus** [microsoft/terminal#8252]
# Description of the new feature/enhancement

I have `alwaysOnTop` set to `true`. The problem with that is, when Terminal app is fullscreen, and when I try to launch another app, I often thought the button does work, since I can't see the app launched behind the Terminal app. 

# Proposed technical implementation details (optional)

Have a setting that allows setting Terminal app to be acrylic/semi-transparent when lost focus. That way, even when it's fullscreen and always on top, I can still see what's happening behind it.

Appreciated!

**Comment by DHowett** [comment]
Thanks! This is actually Windows policy. It is unfortunate, but they've decided that acrylic can only apply to the current _active_ window. I know, that seems strange. We're investigating our options over in /dup #603!

**Comment by tigerinus** [comment]
> Thanks! This is actually Windows policy. It is unfortunate, but they've decided that acrylic can only apply to the current _active_ window. I know, that seems strange. We're investigating our options over in /dup #603!

What about solve my original problem is a different way?

E.g. alwaysOnTop only when window is not maximized. 

E.g. dock the window at one side of the screen. It's like half screen alwaysOnTop.

The root need is I want to always be able to see the terminal. It doesn't necessarily mean alwaysOnTop of other applications.

**Comment by zadjii-msft** [comment]
So, in addition to the global `alwaysOnTop` setting, there's also a `toggleAlwaysOnTop` action, which you can invoke from the command palette (which is default bound to bound to <kbd>ctrl+shift+p</kbd>, "always on top"). That might make your scenario a little easier, where you don't _always_ want always on top. That action will let you toggle the always on top setting at runtime

![image](https://user-images.githubusercontent.com/18356694/99066724-04f9a800-256f-11eb-9219-be5ef05c1caa.png)
