### ISSUE TITLE
Tab key doubling

### ISSUE THREAD

**Issue by sadguitarius** [microsoft/terminal#8253]
# Environment

```none
Windows build number:
10.0.19042.0

Windows Terminal version (if applicable):
1.4.201109001-release1.4

Any other software?
Ubuntu, Powershell
```

# Steps to reproduce
Open a terminal in Ubuntu or Powershell and type the tab key in any program that allows you to see the result of the tab key being pressed, e.g. Vim, Fish shell tab completion.

# Expected behavior
One tab should be produced.

# Actual behavior
The terminal behaves as if the tab key was pressed twice.

**Comment by zadjii-msft** [comment]
By any chance, did you do the `InputServiceEnabled` hack from https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424 ?

We've had reports in the past that causes tab to get sent twice: https://github.com/microsoft/terminal/issues/4448#issuecomment-648177283, #7598

**Comment by sadguitarius** [comment]
That was absolutely it. I'd done that before the other issue about keyboard input was properly resolved. I couldn't find anything about the doubled tab key in any searches though, maybe because the comments in the other thread were hidden. Thank you!

**Comment by DHowett** [comment]
Thanks! Marking as fixed :smile:
