### ISSUE TITLE
Link clicking doesn't work in tmux with mouse support

### ISSUE THREAD

**Issue by krishnachittur** [microsoft/terminal#8254]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): preview 1.5.3142.0

Other software: tmux 2.6, GNU bash version 4.4.20(1)-release on WSL 2
```

# Steps to reproduce

1. Open bash via WSL 2 on Windows Terminal Preview 1.5.

```bash
# this produces a clickable link
echo https://example.com
# this also works
tmux -f /dev/null
echo https://example.com
# but now, stay in the tmux session and try this
tmux set -g mouse on
echo https://example.com
# you will see that the link is not clickable
```

# Expected behavior

All three of the above links should be clickable.

# Actual behavior

After setting mouse mode to on, links are no longer clickable.

**Comment by DHowett** [comment]
Yes, we give mouse applications absolute control over the mouse. Just like with scrolling and text selection, you will need to hold down <kbd>Shift</kbd> to interact with things at the _terminal_ level.

**Comment by krishnachittur** [comment]
I see, I wasn't aware of holding `Shift`, thanks!
