### ISSUE TITLE
Locale set to nb-NO, UI is in Korean.

### ISSUE THREAD

**Issue by NotAFedoraUser** [microsoft/terminal#8255]
# Environment

```powershell
> [System.Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

> Get-Culture
LCID             Name             DisplayName
----             ----             -----------
1044             nb-NO            Norsk (bokmål) (Norge)
```

# Steps to reproduce

- Default locale is `nb-NO`
- Install Korean language pack
- Launched `wt`, the UI is mostly in Korean? 🤔

# Expected behavior

I have my language set to Norwegian, and I would like the UI to be in that language or English.

# Actual behavior

The UI displays korean letters in some parts of the UI, in particular, the dropdown that displays the various shells that
one can launch, the command palette, in the grey text before I've made any input, sometimes when I rightclick on the
title bar, the little dropdown is also in Korean.

This isn't something that breaks the usage of the Windows Terminal for me, but it'd be nice to know what caused it,
or at the very least, how to fix it.

**Comment by Don-Vito** [comment]
@NotAFedoraUser - I guess this one is related to https://github.com/microsoft/terminal/issues/5497. 
Specifically see: https://github.com/microsoft/terminal/issues/5497#issuecomment-625654227

**Comment by zadjii-msft** [comment]
Yea, we've been tracking this issue in #5497 in general, so I'd follow that thread for updates.

Thanks!

/dup #5497
