### ISSUE TITLE
Default value of background image stretch mode is `fill` instead of `uniformToFill`

### ISSUE THREAD

**Issue by CookieHCl** [microsoft/terminal#8256]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3141.0, installed from chocolatey
```

# Steps to reproduce

Add a background image to profile settings.  
Don't set `backgroundImageStretchMode` so it can have default value.

# Expected behavior

Background image should stretch like `uniformToFill`, because according to the [documentation](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#background-image-settings), this is the default value of `backgroundImageStretchMode`.

# Actual behavior

Background image stretch like `fill`.

`uniformToFill` setting works if you explicitely set `backgroundImageStretchMode`, but it won't work in default value.

**Comment by Don-Vito** [comment]
Yep.. in the code the default behavior of BackgroundImageStretchMode within Profile is Fill.
I guess this is not intentional, as in TerminalSettings the default is UniformToFill (but it gets overridden by Profile).
If you want to contribute a fix for it I will gladly assist.

**Comment by zadjii-msft** [comment]
Oh well that's weird, and definitely not intentional. Good catch!
