### ISSUE TITLE
Accessibility: wrong mouse cursor is used when hovering over a link

### ISSUE THREAD

**Issue by joukevandermaas** [microsoft/terminal#8258]
# Environment

```none
Windows build number:
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable): 1.5.3142.0

Any other software?
```

# Steps to reproduce

Hover over a URL in the terminal. A tooltip says "ctrl+click to follow link", but the mouse cursor stays the "normal select" cursor.

# Expected behavior

I expect the "link select" mouse cursor to be used when hovering over links.
![image](https://user-images.githubusercontent.com/1257578/99056946-57e95480-259b-11eb-9cb5-0e42e9e89760.png)

# Actual behavior

This cursor is used: 
![image](https://user-images.githubusercontent.com/1257578/99056929-50c24680-259b-11eb-969c-b67d9ce191fb.png)

I couldn't figure out how to take a screenshot that includes the mouse cursor, Windows hides it when pressing the print screen button. But this is the context:

![image](https://user-images.githubusercontent.com/1257578/99057141-a860b200-259b-11eb-826f-eb1322729a5b.png)

**Comment by PhMajerus** [comment]
The hand is typically only displayed when a click would immediately follow the link.
In MS Office apps for example, the cursor hovering a hyperlink only turns into a hand when Ctrl is held down, to make it clear to the user that a click without Ctrl has the normal selection behavior, while a click with Ctrl down would follow the link.
Windows Terminal should follow the same behavior for clarity, arrow cursor when hovering and hand cursor when Ctrl is down.

**Comment by joukevandermaas** [comment]
Yeah perhaps accessibility is not the right word, I am not sure how to categorize the issue.

To be 100% clear, when holding ctrl, it currently does *not* change the mouse cursor. The solution you describe makes perfect sense to me.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7563 for more discussion.

/dup #7563
