### ISSUE TITLE
Commands nextTab and prevTab have unexpected behaviour

### ISSUE THREAD

**Issue by VisserJ-RTT** [microsoft/terminal#8261]
There is either a change or a bug resulting in new (erratic) behavior of the nexttTab and prevTab commands. Previously when using these commands you'd switch between tabs left and right of your current one. Currently it appears this is happening in the order they were last active. 

The documentation still states the previous (left+right) behavior: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions

If this is supposed to happen and is new behavior, I am unable to find any relevant info to that change. Also would there be a way to disable this "new" behavior?

# Environment : 

```
Microsoft Windows [Version 10.0.19042.630]
Windows Terminal 1.4.3141.0
```

# Steps to reproduce

Use CTRL+TAB to swtich between tabs.

# Expected behavior

Swap between tabs left and right of the currently active one.

# Actual behavior

Swapping between tabs in the order they were last active.

**Comment by Don-Vito** [comment]
@VisserJ-RTT - This is a gap in documentation, starting from 1.4.3141.0 the navigation might occur either "in order" or "MRU" with a default value being MRU.

**Comment by VisserJ-RTT** [comment]
Thank you for the info. You comment also handed me the right search terms to find the blog post to this change.

https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-5-release/

For finding this issue and looking for a solution (this is from the blogpost):

`// Enables the tab switcher
"useTabSwitcher": "mru",
"useTabSwitcher": "inOrder"

// Disables the tab switcher
"useTabSwitcher": "disabled"`

**Comment by Don-Vito** [comment]
@cinnamon-msft  - I could create a PR for docs, but:
1. My English is far from perfect.
2. I have no clue how to explain it without confusing the end-user (good luck explaining the difference between move to next tab and move to previous tab in MRU mode)

**Comment by Don-Vito** [comment]
> 
> 
> Thank you for the info. You comment also handed me the right search terms to find the blog post to this change.
> 
> https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-5-release/
> 
> For finding this issue and looking for a solution (this is from the blogpost):
> 
> ```
> "useTabSwitcher": "mru",
> "useTabSwitcher": "inOrder"
> 
> // Disables the tab switcher
> "useTabSwitcher": "disabled"
> ```

@VisserJ-RTT - starting from 1.5 you are encouraged to use `"tabSwitcherMode"` rather than `"useTabSwitcher"` (which is still supported, but is marked as deprecated). 

I guess that introduction of MRU in the late 1.4 release and introduction of `"tabSwitcherMode"` configuration in the next preview, create some sort of confusion. 

Here you can can see another discussion from today, that might help if you want to use to the old behavior: https://github.com/microsoft/terminal/issues/973#issuecomment-726665238

**Comment by AntonOfTheWoods** [comment]
This is a bit of a WTF. Is there any way to opt out of having our options randomly changed? I can understand wanting to change default settings for *new* users (or new profiles) but this just seems pointlessly annoying. Aren't we all grumpy old fart(ette)s that don't like people changing our shortcuts without asking VERY nicely first? Couldn't there be a "update me to the latest snazziest whatever as you please" option (on by default if you must) but then have a way to say "don't change my shortcuts unless the code to make them work has actually been removed from the codebase"?

That way you get less friction and still migrate (probably) the bulk of users to your new fandangle settings, no?

**Comment by DHowett** [comment]
@AntonOfTheWoods Right now, there's not. I'm sorry about that. I wrote up a bit more in https://github.com/microsoft/terminal/issues/8247#issuecomment-730169446.

In short, we're reverting the change on both preview and stable and making it opt-in.

I recall being upset when Firefox switched Ctrl+Tab to do a switcher like this by default. I am not sure why I felt like we were alright doing the same thing. :thinking:

Marking closed w/ the updates that are going out today.
