### ISSUE TITLE
microsoft / terminal

### ISSUE THREAD

**Issue by adminwep** [microsoft/terminal#8262]
Request Id: f60b075c-e696-4d56-9bab-45277fcc4d00
Correlation Id: b8ccf235-d551-4aa6-90ef-ef2f42d9ed84
Timestamp: 2020-11-13T15:17:38Z
Message: AADSTS165000: Invalid Request: The request did not include the required tokens for the user context. One or more of the user context values (cookies; form fields; headers) were not supplied, every request must include these values and maintain them across a complete single user flow. The request did not return all of the form fields. Failure Reasons:[Token was not provided;]

**Comment by zadjii-msft** [comment]
What? How is this related to the Terminal? You're gonna need to provide more info.
