### ISSUE TITLE
-d CLI parameter is not in the command list

### ISSUE THREAD

**Issue by saschanaz** [microsoft/terminal#8265]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3141.0
```

# Steps to reproduce

```
wt -h
```

# Expected behavior

`-d` should be there, or at least "see also `wt new-tab -h`".

# Actual behavior

![image](https://user-images.githubusercontent.com/3396686/99106855-37de8300-25e5-11eb-8b2f-c8dcacb3f85b.png)

(Why a popup instead of stdout?)

**Comment by DHowett** [comment]
> where is -d

It is an argument to "new-tab" and "split-pane" (the subcommands)
![image](https://user-images.githubusercontent.com/189190/99107043-1015fd80-259a-11eb-967d-37598fa510af.png)

> why a dialog

It's horrible.
More info in the "displaying output in a dialog" section [here](https://github.com/microsoft/terminal/issues/4570#issuecomment-586551445).

**Comment by saschanaz** [comment]
> at least "see also wt new-tab -h".

How about this part?

**Comment by DHowett** [comment]
As we add more subcommands, that's going to grow to be a very long list... isn't it?

**Comment by saschanaz** [comment]
> As we add more subcommands, that's going to grow to be a very long list... isn't it?

My current assumption is that the optional subcommand defaults to new-tab, maybe worth to make it clear so that I can try `wt new-tab -h`. Not sure how more subcommands would make it longer.
