### ISSUE TITLE
Unable to activate a python Venv on profile startup

### ISSUE THREAD

**Issue by leElvyn** [microsoft/terminal#8271]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
```

# Steps to reproduce

create a python venv with  the `python -m venv [envname]`
add a profile with the `commandline` parameter pointing to the env script ( like `C:/Users/username/pythonenv/Scripts/activate.ps1`

profile : 

            {
                // Make changes here to the powershell.exe profile.
                "guid": "{51b54bbd-c2c8-5271-96e7-009a87ff44bf}",
                "name": "venv",
                "commandline": "C:/Users/ordi/redenv/Scripts/activate.ps1",
                "hidden": false
            },

# Expected behavior

the venv would be activated

# Actual behavior

[error 0x800700c1 when launching  `C:/Users/username/pythonenv/Scripts/activate.ps1']

![image](https://user-images.githubusercontent.com/45512739/99149490-adeaf480-268e-11eb-8724-9b57604d4677.png)

**Comment by skyline75489** [comment]
Similar to #8108, you need to have a valid executable in “command line”. This is not a bug.

**Comment by zadjii-msft** [comment]
Yea, I think you could fix this pretty easily by appending `powershell ` to the commandline. So 

```jsonc
        {
            "guid": "{51b54bbd-c2c8-5271-96e7-009a87ff44bf}",
            "name": "venv",
            "commandline": "powershell C:/Users/ordi/redenv/Scripts/activate.ps1"
        },
```

should do the trick

**Comment by leElvyn** [comment]
I tried both answers, but 

```
        {
            "guid": "{51b54bbd-c2c8-5271-96e7-009a87ff44bf}",
            "name": "venv",
            "commandline": "powershell C:/Users/ordi/redenv/Scripts/activate.ps1"
        },
```
but it just close instantly. 
same happens with 
```
"commandline": "powershell -Command C:/Users/ordi/redenv/Scripts/activate.ps1"
```

i also tried 
```
"startingDirectory": "C:/Users/ordi/redenv/Scripts/activate.ps1"
```
but it just goes to the default dir without activating the venv

**Comment by zadjii-msft** [comment]
Alright so I'm not a powershell expert, sorry for the bad advice 😕 For more bad advice, maybe try

```json
        {
            "guid": "{51b54bbd-c2c8-5271-96e7-009a87ff44bf}",
            "name": "venv",
            "commandline": "powershell -NoExit -Command C:/Users/ordi/redenv/Scripts/activate.ps1"
        },
```

Maybe that'll leave the powershell instance open?

**Comment by leElvyn** [comment]
Thanks !
