### ISSUE TITLE
CMD tabs no longer show the command prompt in the title when prompt is $E]0;$P$E;$P$G

### ISSUE THREAD

**Issue by awhewell** [microsoft/terminal#8273]
# Environment

Microsoft Windows [Version 10.0.18362.1139]
Windows Terminal 1.4.3141.0

# Steps to reproduce

1. Set the global PROMPT environment variable to $E]0;$P$E;$P$G
2. Open a CMD tab.

# Expected behavior

The $E]0;$P$E;$P$G prompt sets the current directory as a command prompt (e.g. "C:\Users\Me>"). It also sets the CMD window title to the current directory and, until recently, set the Windows Terminal tab title for CMD windows to the current directory.

When you change directory within the CMD window or the CMD Windows Terminal tab the window title (CMD) or tab title (WT) changes to reflect your current working directory.

In Windows Terminal this means that when you have many CMD tabs open you can tell at a glance which tab is in which directory.

# Actual behavior

As of 1.4.3141.0 it now only shows the profile name (cmd in my case) in the tab title. The title does not update as you change directories. If you have many tabs open then you cannot tell which tab is in which directory.

Regressing to version 1.3.2651.0 fixes the issue.

Regressing to preview 1.4.2652.0 re-introduces the bug. Whatever change caused the problem came in between 1.3.2651.0 and 1.4.2652.0.

**Comment by j4james** [comment]
There's a mistake in the escape sequence you're using in your prompt. It should be:

    $E]0;$P$E\$P$G

That fact that it worked previously with a `$E;` was a bug.

**Comment by awhewell** [comment]
You're quite right, when I replace the ; with \ it works just fine in both cmd.exe and Windows Terminal. I'll close the issue, thanks for that.
