### ISSUE TITLE
REPL for Windows Host Script engines JScript and VBScript

### ISSUE THREAD

**Issue by Foadsf** [microsoft/terminal#8275]
# Description of the new feature/enhancement

I know WSH is not very popular, but `wscript.exe` and `cscript.exe` are shipped with almost all Windows machines out there. IMHO it could be a nice idea to provide a simple interactive read–eval–print loop (REPL) for JScript and VBScript.

# Proposed technical implementation details (optional)

A primitive version of the JScript REPL inspired by Node.js, written in JScript:

~~~javascript
var inputLine = ".start";

var findVariableName = /^[ ]*(var[ ]+)?([_A-Za-z][_A-Za-z0-9]*)[ ]*=([^=][ ]*[^\n;,]*);?/;
var temporaryRegexResult;

function print(inputVariable) {
    var outputString;
    if (inputVariable instanceof Array) {
        outputString = "[" + myArray.join(", ") + "]";
    } else if (inputVariable == null) {
        outputString = "undefined";
    } else {
        outputString = inputVariable;
    }
    WScript.StdOut.WriteLine(outputString);
}

do {
    if (inputLine != ".start") {
        try {
            eval(inputLine);

            if (findVariableName.test(inputLine)) {
                eval("print(" + RegExp.$2 + ");");

            } else {
                eval("temporaryOutput = (" + inputLine + ");");
                print(temporaryOutput);
            }

        } catch (error) {
            print(error.message);
        }
    }

    WScript.StdOut.Write("> ");
    inputLine = WScript.StdIn.ReadLine();
} while (inputLine != ".exit");
~~~

**Comment by DHowett** [comment]
We talked on twitter and I let @Foadsf know about @PhMajerus's AXSH. Seems to be what they wanted :smile:

In general, this is a good place for a third party developer to take up the charge. It doesn't have to be part of the Terminal project!

**Comment by Foadsf** [comment]
@DHowett I have written a REPL myself. And I realized that I can add it to the `setting.json`. It seems to be working fine for now. I will FLOSS the code and then you might think of adding or not adding it to the Windows Terminal. 

![JScript.js inside Windows Terminal](https://i.imgur.com/121FWRZ.png)
