### ISSUE TITLE
Installation: File Explorer / Right Mouse Button Context Menu Integration

### ISSUE THREAD

**Issue by tommai78101** [microsoft/terminal#8276]
# Description of the new feature/enhancement

When installing Windows Terminal, I would like to see an option to have the Window Terminal with the right mouse button context menu integration, which I believed is tied to File Explorer integration.

This means, for example, if I open up my workspace in File Explorer, I would like to be able to launch Windows Terminal directly using the right mouse button context menu.

I could've missed this. Or that when you compile Windows Terminal, there are no batch scripts available for me to run to install File Explorer integration for Windows Terminal.

Is it possible to have a File Explorer integration for Windows Terminal, or is there a way to run a batch file script that allows me to install Windows Terminal File Explorer integration when cloning the source code project?

**Comment by DHowett** [comment]
This already exists, and is shipped by default for every supported installation method.

![image](https://user-images.githubusercontent.com/189190/99202950-caa62b80-2765-11eb-8229-5af9069caec5.png)

There's an OS bug that prevents us from offering it when you right-click in the empty space inside a folder.

How did you install Terminal? What version are you using?

**Comment by tommai78101** [comment]
Hello @DHowett 

That explains everything. 

I used the Windows 10 Store to install Windows Terminal at the moment.

**Comment by DHowett** [comment]
Thanks for confirming! You’ll want to follow /dup https://github.com/microsoft/terminal/issues/6414 to know when we’ve worked around the OS bug (or it’s otherwise been fixed :))
