### ISSUE TITLE
Looks like the is no Background Image Padding Option

### ISSUE THREAD

**Issue by MosesOnGithub** [microsoft/terminal#8277]
Settings Example
"backgroundImage": "C:/Users/GitHub/Documents/Windows Terminal Background/ubuntu.png",
"backgroundImageAlignment": "bottomRight",
"backgroundImageStretchMode": "none",
"backgroundImageOpacity": 0.7,

SUGGESTION
"backgroundImagePadding": "10, 10, 10,10",

The background image is touching the window's edges

**Comment by DHowett** [comment]
Thanks for the request! This looks like a subset of /dup #2370. :smile:
