### ISSUE TITLE
Nothing happens when I press 'Get' in Microsoft Store. 

### ISSUE THREAD

**Issue by ThomasCarlsenDelegate** [microsoft/terminal#8282]
Nothing happens when I press 'Get' in Microsoft Store.

**Comment by zadjii-msft** [comment]
Okay just pasting the title in the body doesn't really give us any actionable info.

What version of Windows are you on?

**Comment by ThomasCarlsenDelegate** [comment]
Oh, sorry my man.

Because of your question, I just found out that it is because that I have a win10 system below 18362.
I have:
![image](https://user-images.githubusercontent.com/56817530/99191228-9897c800-276b-11eb-87ca-68bde2f51fb1.png)
and just found out the system requirements should be 18362 or higher.

But it was a bit confusing that nothing happened - would be nice if a message says that I have a version to premature.

**Comment by ThomasCarlsenDelegate** [comment]
If it is not possible for you guys to make an alert, it is okay to close the issue :)

**Comment by zadjii-msft** [comment]
Yea, there's nothing really more we can do about this. I'm sure there's work on the Store team already to display some sort of better dialog. Kinda mind boggling that it doesn't IMO. Anywho, this is definitely on the Store team, so I'll close this issue out. Thanks!
