### ISSUE TITLE
Memory leak with several ANSI sequences

### ISSUE THREAD

**Issue by ZEDCWT** [microsoft/terminal#8283]
# Environment

```none
Windows build number: 10.0.19042.508
Windows Terminal version (if applicable): 1.5.3142.0

Any other software?
Node v15.2.0
```

# Steps to reproduce

+ Save the following content in a file, say, name it with `test.js`
```js
var readline = require('readline'),count = 0;
setInterval(() =>
{
	console.log(++count,new Date)
	readline.moveCursor(process.stdout,0,-1)
},10)
```
+ Open the cmd.exe in the terminal
+ Run the script saved above with `path\to\node.exe path\to\test.js`

# Expected behavior

No significant memory increasing should be observed

# Actual behavior

To compare with, another cmd.exe is also directly started by `Win+R` and run the same script.
Here is the initial memory usage
![Initial memory usage](https://user-images.githubusercontent.com/7867810/99187506-f7703800-2791-11eb-90ca-ca0daf64e6bf.png)
Also, reported by `Process Explorer`, the `WS Private` and `Working Set` are
```
WindowsTerminal.exe	36976 K	101816 K
```

Then, leave them run for hours, and here is the memory usage after the counter hit 400k+.
![Memory usage after 400k+](https://user-images.githubusercontent.com/7867810/99187576-5b92fc00-2792-11eb-8b2c-9f930be7f8a7.png)

Next, `Ctrl+C` to end both node processes, and wait for 5min.
![Memory usage after node killed](https://user-images.githubusercontent.com/7867810/99187598-81200580-2792-11eb-865e-37f21c5f1a0e.png)
```
WindowsTerminal.exe	96444 K	157840 K
```

It seems that it memory leaked.
And by roughly counting during the progress, the memory usage grow about 0.1 MB / 10 sec.

**Comment by DHowett** [comment]
Hmm, you're right. Interesting.

**Comment by DHowett** [comment]
Good catch!
