### ISSUE TITLE
why I can't see profiles.json file

### ISSUE THREAD

**Issue by a-omar109** [microsoft/terminal#8284]
I can't find profiles.json file anywhere 
I've deleted the program and reinstall it but the problem didn't solved

**Comment by DHowett** [comment]
1. how did you install Terminal
2. the file has been called "settings.json" for almost a year.

**Comment by amunger3** [comment]
Did you originally install & or reinstall it using the Microsoft Store Service or the GitHub release directly? An inconsistency there could explain it. I assume you've tried going to %LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_...\LocalState, yes? If it's not there, try this: 

On PowerShell, install the MSTerminalSettings Module from the PowerShellGallery and after importing it run `Find-MSTerminalFolder` and `Get-MSTerminalSetting` to see if they return the paths you can't find.

```powershell
Install-Module -Name MSTerminalSettings
Import-Module -Name MSTerminalSettings

# See if the search function comes up with any answers
MSTerminalFolder
Get-MSTerminalProfile -Name "PowerShell Core"

# Or just try to make a new profile
New-MSTerminalProfile -Name pwsh -CommandLine "C:\Program Files\PowerShell\7\pwsh.exe" -WorkingDirectory ~
```
