### ISSUE TITLE
Windows Terminal crashing when resizing panes

### ISSUE THREAD

**Issue by wolffberg** [microsoft/terminal#8287]
# Environment

```none
Windows build number....: 10.0.19041.0 (issue also seen on earlier versions)
Windows Terminal version: 1.4.3141.0
Pwsh version............: 7.1.0        (issue also seen on earlier versions)
```

# Steps to reproduce

- Open Windows Terminal
- Maximize window to have more space for resizing (optional but makes it easier to reproduce)
- Split the terminal horizontally and then vertically into panes
- Resize bottom two panes up and down repeatedly using keyboard shortcuts

# Expected behavior

The panes should resize without issues

# Actual behavior

Windows Terminal crashes

# Notes

- The crash can happen at any given time while resizing panes. Some times you will be able to resize a lot, some times the crash happens instantly.
- The issue have been observed on multiple different devices.
- The issue is tested with `pwsh`, `wsl` and `cmd` running in the panes.

**Comment by DHowett** [comment]
That's almost certainly not right. Would you mind filling out a feedback item to see if we can get some crash logs?

If that doesn't work, I'll write up tracing steps. :smile:

**Comment by wolffberg** [comment]
Sure thing https://aka.ms/AAae833 🤞

**Comment by webnoob** [comment]
I too have a similar issue. I have a powershell script which loads scripts into 2 tabs with 1 pane on one tab and 5 panes on the other. When it's loading, if I grab the bottom right corner of the terminal and drag it quickly to resize, it closes the terminal.

This is the command I use (specific to my project but the general idea should help): `wt `; new-tab -p "DevTestingApi" powershell.exe -command "yarn start:testing" `; new-tab -p "DevApi" powershell.exe -command "yarn start:dev" `; split-pane -p "DevApp" powershell.exe -command "yarn dev" `; split-pane -p "DevCommon" powershell.exe -command "yarn dev" `; split-pane -p "DevApp" powershell.exe -command "yarn test:e2e" `; split-pane -p "DevApp" powershell.exe -command "yarn test:unit:ui"`

**Comment by DHowett** [comment]
Alright, this is gonna seem like I'm giving you the runaround. Sorry for that.

On Monday, I set up better tracing for our feedback hub entry! Unfortunately, it requires a "repro mode" feedback hub capture.

Would you mind filing another feedback hub item? It'll help us capture those new traces.
Please make sure you do the following:

1. Use the Apps, "Windows Terminal" category. There shouldn't be a "(Preview)" version any more.
   * This is what enables the terminal-specific tracing
2. Use "start recording" .. you can choose "include data about ... general". ![image](https://user-images.githubusercontent.com/189190/100270447-f3b88000-2f0c-11eb-8444-3c4d98170d8d.png)
3. Crash Terminal while it's recording!
4. Stop recording, submit, share link like before.

Thanks again :smile:

**Comment by wolffberg** [comment]
There you go https://aka.ms/AAaetoj 

Yesterday I tried replicating the issue on a fresh Windows 10 installation and weren't able to reproduce. I only added my keybindings to `settings.json` but didn't install any fonts. I usually use https://github.com/powerline/fonts 🤔
```
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore",
            "fontFace": "Meslo LG S DZ for Powerline",
            "fontSize": 10
        },
```

**Comment by zadjii-msft** [comment]
Oh no, with the holidays at the end of the year, it looks like this one got lost. Now that it's been more than 60 days, the feedback got flushed from the backend ☹️ 

Would you mind submitting it again? I'm fairly confident that this is the same issue as #4907, but it'll be good to know for sure.

Sorry about that!

**Comment by VanVan** [comment]
I have the same problem, I will open a new thread
