### ISSUE TITLE
SyntaxError: JSON.parse when opening settings

### ISSUE THREAD

**Issue by nomisto** [microsoft/terminal#8292]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Windows Terminal version (if applicable): 1.4.3141.0
```

# Expected behavior

When opening the settings Firefox opens ../AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json

and displays

![grafik](https://user-images.githubusercontent.com/28439912/99300895-7aa29400-284d-11eb-979f-45d96c96b275.png)

**Comment by DHowett** [comment]
This is because your "default JSON editor" is, for some reason, a web browser. Set it to be a text editor and you'll be able to edit your settings.
