### ISSUE TITLE
AcrylicOpacity doesn't work

### ISSUE THREAD

**Issue by arnabanimesh** [microsoft/terminal#8295]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.4.3141.0

Any other software? No
```

# Steps to reproduce

Set Acrylic Opacity to any value with Use Acrylic as true

# Expected behavior

The window goes translucent

# Actual behavior

The window remains opaque.

**Comment by DHowett** [comment]
If you're not in battery saver mode, or have transparency effects disabled across the OS, this is a /dup of #7047. Sorry!
