### ISSUE TITLE
Add "recent commands' to Command Palette in commandline mode

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#8296]
# Description of the new feature/enhancement

The idea is to store the history of the recent commands dispatched from command palette in command line mode. This history will be presented below the search bar. Typing in the search bar will filter the relevant history items (similar to the behavior we already have with filtering commands in action mode).

![image](https://user-images.githubusercontent.com/4639110/99311239-f5c37480-2864-11eb-8c2b-3b46e5ea66e8.png)

Usually when I use command palette in the command line mode I do it to run the same commands.
This feature will save me a lot of typing and prevent typos.

# Proposed technical implementation details (optional)
I am not sure what is the best place to store the history, and what are the security concerns if exist.
We can start with storing the history in memory for the current session.

**Comment by skyline75489** [comment]
I like this! VSCode will show recent commands history in its command palette and I found it useful.

**Comment by zadjii-msft** [comment]
dang this is a good idea

We could certainly start with work with just stashing the recently used commands in memory while a window is open, and then once #7972 is implemented, we could actually write the mru list to disk and load it from there. 

I'll stick this in #5400. Thanks!

**Comment by Don-Vito** [comment]
@zadjii-msft - then I would like to work on this 😊

**Comment by zadjii-msft** [comment]
Go for it!

**Comment by Don-Vito** [comment]
Implemented in-memory, MRU list (not set) of 10 (hard-coded). 
There is no auto-completion, the history entries get filtered out, however-to invoke the entry you need to select the item:
![CommandHistory2](https://user-images.githubusercontent.com/4639110/99545851-78ac1280-29be-11eb-88de-3534da26c645.gif)
