### ISSUE TITLE
Window Terminal + PowerShell/CMD + vim visualization problem

### ISSUE THREAD

**Issue by NemoHoHaloAi** [microsoft/terminal#8297]
# Environment

Windows build number: Microsoft Windows [version 10.0.18363.1198]
Windows Terminal version: Windows Terminal version: 1.4.3141.0
Vim

# Steps to reproduce

1. Open windows terminal
2. create a powershell or cmd tab
3. vim something, moving up and down.

this problem show in powershell and cmd but git-bash, so wired.

# Expected behavior

![wtbug](https://user-images.githubusercontent.com/17694712/99333150-5f6e6d80-28bb-11eb-8505-3bb914c8c191.gif)

# Actual behavior

vim can work as well.

**Comment by NemoHoHaloAi** [comment]
Seem like the output buffer problem, but i dont kown how to fix that.

**Comment by skyline75489** [comment]
OK this is not expected. Git bash use its own VT parser so perhaps that's why it's working fine.

Does this happen all the time, or occasionally? Does this happen on WSL or over SSH? Is there any other operation that you have performed that may lead to this? For example, resizing the windows,  pane operations?

**Comment by NemoHoHaloAi** [comment]
Thanks for response.

- it happen all the time.
- no another operation, just  start windows terminal, and in powershell or cmd windows use vim.
- in WSL(ubuntu 20.04), it works as well as git-bash.

**Comment by DHowett** [comment]
Do you have a vim configuration that resizes the screen?

**Comment by NemoHoHaloAi** [comment]
Yeah, i had set the vim winpos and lines, that make this problem happen.

Now it is good, so much thanks to you guys, and respect for your great job in windows terminal, really cool tool.

**Comment by DHowett** [comment]
I am glad it helped! I'll close this. It is hard for Terminal to handle resize options right now. :smile:

**Comment by NemoHoHaloAi** [comment]
Keep going!!!😊
