### ISSUE TITLE
Ctrl + Shift + Mouse Wheel doesn't change transparancy with useAcrylic set to true

### ISSUE THREAD

**Issue by PolarToCartesian** [microsoft/terminal#830]
I am new to the new windows terminal but I am experiencing an issue where the transparency is not applied with "useAcrylic" set to true in my "profiles.json" file as shown in another issue post. I built it with visual studio 2017 and "Microsoft Windows [version 10.0.18898.1000]". I cloned the repository today.

Is there an issue or is it because of my lack of knowledge with this awesome new fancy terminal? 
Thanks!

It is in the txt format because github doesn't accept .json files.
[profiles.txt](https://github.com/microsoft/terminal/files/3188365/profiles.txt)

**Comment by mKay00** [comment]
What if you set the transparency manually in the profiles.json? Does the transparency work? Is the window in focus? Are you sure you have saved the changes of your profiles.json? Try deinstalling and rebuilding it and then change again to true.

**Comment by zadjii-msft** [comment]
There are other things that affect acrylic that are out of our control. For example, acrylic doesn't render through remote desktop sessions, and IIRC, it doesn't render on battery saver either. It is also well documented that it only renders on windows that are actively focused.

If your profile has useAcrylic set, you can change the opacity of the acrylic with Ctrl+Shift+mouse wheel

**Comment by PolarToCartesian** [comment]
Thank you for your suggestions but I have rebuilt it several times with fresh clones of the repo. I have verified that low battery mode was off and I am not using it through a remote session and the window is focused. Changing the AcrylicOpacity setting doesn't do anything. I will provide the profiles.json file.

**Comment by mKay00** [comment]
I tried your profiles settings and they work for me. Maybe an issue with the Windows version? I am on 18362.

**Comment by PolarToCartesian** [comment]
Would me uploading my compiled version help?

**Comment by garyparrot** [comment]
I can't change the transparency by Ctrl+Shift+Mouse wheel too.

I have checked the source code of [CascadiaSettings.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/CascadiaSettings.cpp) and [AppKeyBindings.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/AppKeyBindings.cpp).
And seems there doesn't exist any key binding about Ctrl+Shift+Mouse for change transparency.

But at the [conference](https://youtu.be/KMudkRcwjCw?t=919), they actually perform this key binding.

I guess they didn't commit this feature yet.
Just a guess, I am not sure that is the reason.

**Comment by PolarToCartesian** [comment]
The key binding must exist since mKay00 said it worked for him.. I will try to find it when I have time. What is your windows version garyparrot? It seems to be linked somehow but I am not sure.

**Comment by garyparrot** [comment]
I am running 18362.30

I just find out I can actually change the transparency by mouse wheel.
But I have to keep scrolling the wheel in the same direction very hard.

**Comment by PolarToCartesian** [comment]
I have tried setting the scroll sensitivity to the maximum but it still doesn't work... It is very interesting that it works for you! We are getting close!

**Comment by zadjii-msft** [comment]
The "keybinding" isn't actually set as a `KeyBinding`, since `KeyBinding`s are for key combos, while this is a mouse interaction. 

Mouse wheel events are handled here:
https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/TermControl.cpp#L696-L717

I'd set a breakpoint there to make sure it's getting hit for you.

**Comment by garyparrot** [comment]
Wow, that makes sense.
Mike Griese thanks for your reply! It helps me make this clear.

**Comment by PolarToCartesian** [comment]
Thanks I’ll try!

**Comment by zadjii-msft** [comment]
@PolarToCartesian Did you ever figure this out?

**Comment by PolarToCartesian** [comment]
Yes, sorry I forgot to report it here... I had issues with windows insider (I received updates too fast) which meant that things weren't as stable as other versions. I decided to wait for the release version!

**Comment by PolarToCartesian** [comment]
I just realized that the issue was due to me having transparency off in windows because of my visual handicap.

**Comment by Rob-S** [comment]
In the release version, 1.0, neither backgroundTransparency / acrylicTransparency with useAcrylic set to true with a backgroundImage (tried both png and jpg) in settings.json nor the ctrl + shift + mouse wheel work for me, no matter how hard/long I scroll. The Transparency Effects is set on in Windows.
