### ISSUE TITLE
Add a bit of animation when switching tabs

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#8300]
# Environment

```none
Microsoft Windows [Version 10.0.19042.630]
Windows Terminal Version: 1.4.3141.0
```

# Steps to reproduce

```json
"useTabSwitcher": false,
```

<kbd>ctrl</kbd>+<kbd>tab</kbd>
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd>

# Expected behavior

Provide some sort of animation (configurable) I was thinking the highlight area shifts to the right and the main terminal window fades for a configurable duration.

# Actual behavior

Switches immediately.

**Comment by skyline75489** [comment]
Out of respect, I don't think any of the terminal emulators out there has animation when switching tabs. Personally I do not want one. I want the switching to be instantaneous.

**Comment by zadjii-msft** [comment]
Actually I'm gonna go even further, is there any precedent for some animation like this in _any_ tabbed application? If we're taking inspiration from the way browsers handle tabs, they always have the tabs switch instantly, right?

I'd love to have _any_ precedent for this before committing to it

**Comment by trajano** [comment]
Maybe better to have a discussion on [UX Stack Exchange](https://ux.stackexchange.com/questions/135629/should-we-animate-tab-switching) rather than here, since this may be a bigger design language change.  Anyway example of it would be in analytics.google.com switching tabs has a slight delay, not instant.

![image](https://user-images.githubusercontent.com/110627/99719638-9343c180-2a7a-11eb-8ffd-3b59075c1280.png)

**Comment by DHowett** [comment]
Here's what I'll give you.

If _Windows_' (not a web application) design language moves towards having tabbed applications animate the entire window frame out/in, we will follow them. We aren't here to introduce new unfamiliar UI paradigms, we're here to be a really dang good terminal emulator that looks like it was written for Windows. :smile:
