### ISSUE TITLE
MSBuild issues warning on CascadiaPackage in VS 16.8

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#8301]
> The project 'CascadiaPackage' ran into a problem during the last operation: The value of the 'TargetFrameworkMoniker' and 'NuGetTargetMoniker' properties in the 'Release|x64' configuration are both empty. This configuration will not contribute to NuGet restore, which may result in restore and build errors. You may need to reload the solution after fixing the problem. 

Is it just me? It keeps showing when I launch the project using VS 16.8

**Comment by Don-Vito** [comment]
@skyline75489 - I have the same error as well.

**Comment by DHowett** [comment]
This would not be the first time the WAP Packaging Project has spontaneously and aggressively broken our project. Does it still deploy?

**Comment by skyline75489** [comment]
Deployment seems fine. Only the warning keeps poping up.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DHowett** [comment]
Marked help wanted & backlog but it's not on fire so I don't mind it. :smile:

**Comment by skyline75489** [comment]
One thing that bothers me is that the warning somehow interferes with the font setting. When I open the OpenConsole solution, the font used by Visual Studio will fallback to system default, instead of the "good-looking" one I chose. However this does not happen with other solutions. So I suspect it's because of the warning.

**Comment by zadjii-msft** [comment]
Guh, I got the 16.8 flight over the holidays. Boy, InfoBars with warnings that are totally irrelevant sure are annoying 😅 

I _think_ the fix is just 

```diff
diff --git a/src/cascadia/CascadiaPackage/CascadiaPackage.wapproj b/src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
index 3d918935a..dd88eb674 100644
--- a/src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
+++ b/src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
@@ -5,6 +5,7 @@
   <PropertyGroup Label="Configuration">
     <!-- This is necessary so the build system doesn't think we're a .NET project... -->
     <TargetRuntime>Native</TargetRuntime>
+    <NuGetTargetMoniker>win</NuGetTargetMoniker>
     <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
     <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
     <!--
```

I have _no idea_ if that's the real fix or not. I bet this is because VS _thinks_ that a `wapproj` is technically a C# project, when really it's not. So it thinks it needs to find this property. I'll ping our internal contact to see if he knows about this.

**Comment by skyline75489** [comment]
Am I the only one getting the infobar that says “1ES want you to upgrade VS for security reasons” then listened? Yeah then I got this infobar. One bar for another.

**Comment by zadjii-msft** [comment]
LOL Yea, I just usually let someone else on the team bite the bullet first, considering how frequently VS updates break our project
