### ISSUE TITLE
Open vscode after click on setting windows terminal

### ISSUE THREAD

**Issue by omides248** [microsoft/terminal#8304]
I have click  **setting** **ctrl+,**  terminal open vscode !!!!!??!!!!

**Comment by zadjii-msft** [comment]
That's exactly what's supposed to happen - it opens the settings.json file in whatever your default `.json` editor is. 

See [is:issue settings editor is:closed ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+settings+editor+is%3Aclosed+)
* /dup #1710
* /dup #7481
* /dup #8240
* /dup #6642 
* /dup #8004 
* /dup #7975 
* /dup #7355
