### ISSUE TITLE
.. ligature renders incorrectly in Windows Terminal

### ISSUE THREAD

**Issue by arnabanimesh** [microsoft/terminal#8306]
# Environment

```none
Windows build number: 10.0.18363.1198
Windows Terminal version (if applicable): 1.4.3141.0

Any other software? No
```

# Steps to reproduce

Type `..` with ligature enabled fonts (like FiraCode or CascadiaCode font). I used FiraCode. The problem also exists with the Cascadia Code font albeit to a lesser degree.

# Expected behavior

It should appear as `..`

VSCode renders it just fine: 
![image](https://user-images.githubusercontent.com/6032584/99423657-c6753c00-2926-11eb-9cf0-3754d8f90d09.png)

# Actual behavior

It is appearing as:
![image](https://user-images.githubusercontent.com/6032584/99422981-19022880-2926-11eb-9521-3914e69666f4.png)

**Comment by zadjii-msft** [comment]
What display scaling is your display set to?

**Comment by arnabanimesh** [comment]
I set a custom scaling of 135. Since 125% is too small, and 150% is a bit big for my tastes and some windows tend to overflow.

The problem seems to appear only when custom scaling is set. Other apps are working fine though.

It would be great if there would be more granular control over scaling by default.

**Anyways, custom scaling support for Windows Terminal would be nice as of now.**

**Comment by zadjii-msft** [comment]
Thanks for following up! We're already tracking this over in #4591.

/dup #4591
