### ISSUE TITLE
Selected text should populate search box

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8307]
# Description of the new feature/enhancement

If there is an active selection in the terminal, opening the search box should be populated with the selected text.

**Comment by DHowett** [comment]
What if there's already a needle in the search box?

**Comment by zadjii-msft** [comment]
I vote replace it with the new selection.

**Comment by Don-Vito** [comment]
This one is quite straightforward, but I am not sure what to do with multi-line selection.

Options are:
1. Do not populate the search if multiple lines are selected
2. Populate only with the first line
3. Populate with the trimmed selection returned by `RetrieveSelectedTextFromBuffer(true)`.

I personally played with the 3rd option and liked it more. 
WDYT?

**Comment by Don-Vito** [comment]
The funny stuff that multi-line selection works.. but I am not sure I can assume it works in all scenarios. 
![SelectText](https://user-images.githubusercontent.com/4639110/101292873-d3e16000-381a-11eb-8264-7aee193268d5.gif)

However after some thoughts.. I suggest to start with what VS Code do.. populate only if single line selected.
