### ISSUE TITLE
It'd be nice if a new pane started in the same folder as the one you split from 

### ISSUE THREAD

**Issue by paulsmith74937** [microsoft/terminal#8308]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #3158 for more discussion.

* /dup #3158 "Open new terminal tab in same directory as existing tab (OSC 7?)"
* /dup #7850 "split pane "splitMode:duplicate" not working." 
* /dup #7734 "Easy way to duplicate tab and preserving current working directory" 
* /dup #7544 "duplicate tab: working directory not duplicated" 
* /dup #7049 "🔥 [wt +Powerline ] duplicateTab not working" 
* /dup #7022 "Open another profile in same directory" 
* /dup #1437 "Feature Request: Option to open new tabs in the same directory as the current tab" 
* /dup #4259 "Open a new pane with the environment vars of the parent" 
* /dup #4970 "Feature Request: duplicate current path with panes"
