### ISSUE TITLE
Single terminal window option

### ISSUE THREAD

**Issue by perneky** [microsoft/terminal#8314]
Hello,

There could be an option if I open a new terminal, open a new tab inside an already running terminal window if there is any, instead of opening a new window. It would make sense to have a global option and be able to override it from the command line as well.

Laci

**Comment by Don-Vito** [comment]
@perneky - this seems to be a duplicate of https://github.com/microsoft/terminal/issues/2227, which is handled as a part of terminal process model overhaul: https://github.com/microsoft/terminal/issues/5000

**Comment by zadjii-msft** [comment]
Sure is, and is also covered heavily in the spec over in #8135. Thanks!

/dup #2227
