### ISSUE TITLE
Cursor and focus leaves current window after clicking on tab

### ISSUE THREAD

**Issue by RodBarnes** [microsoft/terminal#8323]
# Environment

```none
Microsoft Windows [Version 10.0.18363.1139]
Windows Terminal Version: 1.4.3141.0

Any other software? None pertinent to the issue
```

# Steps to reproduce

1. Open Windows Terminal.  Focus is placed in the initial terminal window and the cursor appears.
2. Click on the tab again.  The cursor disappears and focus is removed from the terminal window.
3. Click on the [+] or the [V] to open a new tab.  A new terminal window opens and focus is placed in the new window.
4. Again, click on the currently open tab.  The cursor disappears and focus is removed from the terminal window.
5. Click on some other tab (not currently in focus).  The window is made current and focus is moved to that new window.

# Expected behavior
Clicking on the currently open tab or in the currently open window should place focus in the window and display the cursor.  This is standard behavior in all multi-window apps.

# Actual behavior
Clicking on the currently open tab actually <B>removes</B> focus from the current window.  This behavior is confusing because the user has to only click in the window -- not click the tab -- in order to place focus in the window after having been working in another application.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3609 for more discussion.

/dup #3609
