### ISSUE TITLE
"Continue where you left off" behavior

### ISSUE THREAD

**Issue by stagefright5** [microsoft/terminal#8329]
# Description of the new feature/enhancement

Behavior somewhat similar to the browser where on start up, the terminal will remember the tabs that were opened.
The things to remember:
- Type of the tab (cmd, powershell etc)
- The directory
...etc

# Proposed technical implementation details (optional)
NA

**Comment by Don-Vito** [comment]
This a great and old idea: please review #766 and see if the spec there covers you needs. 

I am not from the team, but lately I've seen a lot of work around state persisting, so I guess this one will be addressed in the future.

**Comment by Don-Vito** [comment]
This a great and old idea: please review #961 and see if the spec there covers you needs. 

I am not from the team, but lately I've seen a lot of work around state persisting, so I guess this one will be addressed in the future.

**Comment by DHowett** [comment]
/dup #961

Thanks @Don-Vito! Appreciate you helping us out with Triage :smile:
