### ISSUE TITLE
Feature request: Add support for background images

### ISSUE THREAD

**Issue by d-bingham** [microsoft/terminal#833]
Terminal currently has support for static background colors and Fluent's Acrylic background, but does not allow the selection of background images for further customization.

**Comment by DHowett-MSFT** [comment]
@yodurr claimed this before //build, actually! Assigned to him.

**Comment by d-bingham** [comment]
@yodurr do you have work on this?  I've got a PR ready with a basic implementation if not.

**Comment by yodurr** [comment]
Sorry I was slow to reply here.  I'm excited to see what you did.  Thanks for stepping in!
