### ISSUE TITLE
Confirming/Closing tab renamer should return focus to pane

### ISSUE THREAD

**Issue by BartXZX** [microsoft/terminal#8334]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1198]
Windows Terminal version 1.5.3142.0
```

# Steps to reproduce
1. Bind openTabRenamer and open it (or open from the command window)
2. Type desired name
3. Press Enter/ESC

# Expected behavior
Focus returns to the pane, and I can continue my work.

# Actual behavior
The focus goes to the 'plus' button, see screeenshot.

![image](https://user-images.githubusercontent.com/5583518/99665328-c7fb4d00-2a69-11eb-95fb-a36ceef0df4c.png)

**Comment by DHowett** [comment]
Thanks for the report! Yeah, we've got some lingering focus issues. We're tracking them over in /dup #6680.
