### ISSUE TITLE
Option to set the tab default background color

### ISSUE THREAD

**Issue by jvzaniolo** [microsoft/terminal#8337]
# Description of the new feature/enhancement
I think it would be nice to have a setting to change the tab default background color, which is black.

# Proposed technical implementation details (optional)
Currently we have the option to set a color to a tab by right-clicking the tab itself. But it would be really satisfying to have an option in settings.json to change the default black color.

**Comment by Don-Vito** [comment]
Like this: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#tab-color?

**Comment by DHowett** [comment]
Thanks @Don-Vito! Yeah, we've got this already: you can set the `tabColor` for any profile! :smile:
(You can also set it for the "defaults" profile which applies to everything.)
