### ISSUE TITLE
Horizontal Scroll Bar Persisting and Covering Content (WSL1)

### ISSUE THREAD

**Issue by GHBrown** [microsoft/terminal#8340]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.572]
Your Distribution version: Ubuntu 20.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com)
(gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020
```

# Steps to reproduce
Open Ubuntu from task bar, snap Ubuntu/WSL to right side so it covers half of screen (issue seems less prevalent when snapped to left side, and it doesn't seem to matter if there is a window covering the other half or if it's clear to desktop). Open vim or emacs from the command line. Resize WSL window by dragging the center edge. Greyed out uninteractable horizontal scroll bar should appear and persist for the rest of the session, covering part of the displayed content in the window.

# Expected behavior
Horizontal scroll bar appears and is interactable only when really needed (which seems like never in my experience) and does not cover content at bottom of window. If it does appear, it will disappear when it is no longer needed (window is fullscreened, etc.).

# Actual behavior
Uninteractable\greyed out horizontal scrollbar appears and covers content at bottom of screen, even when no scrollbar is needed. Scrollbar persists even when window is resized or fullscreened. In general, this wouldn't but such a big deal, but it covers the Emacs minibuffer almost completely.

**Comment by DHowett** [comment]
Thanks for the detailed write-up! You may be surprised to learn we've got an issue tracking this one too :smile:

/dup #5868

It seems to be related to the use of the alt buffer. I'll quote you over there.

**Comment by GHBrown** [comment]
No worries, I saw that thread, but wasn't sure if it was exactly the same thing. Thanks for the quick response.
