### ISSUE TITLE
langugage problem

### ISSUE THREAD

**Issue by Tarvey** [microsoft/terminal#8342]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

idk
# Expected behavior

# Actual behavior

i have korean langugage out of german

**Comment by zadjii-msft** [comment]
Okay, so there's almost nothing to work with in this issue, so I'm gonna have to use psychic debugging here. I'm guessing that what you're seeing is "The Terminal is localized in one language, but my OS is set to another one". That's an issue we're tracking over in /dup #5497. (There are lots of similar issues linked to that one)

If that's _not_ the issue you're seeing, feel free to provide more info and we can reopen this. Thanks!
