### ISSUE TITLE
Cross-platform `win32-input-mode` usage

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#8343]
# Description of the new feature/enhancement

By creating this issue, I would like to start a public discussion about what could be changed in the current design of the [`win32-input-mode` protocol](https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md) before it becomes widespread and cross-platform.

The `Considerations` section states:

https://github.com/microsoft/terminal/blob/612b00cd445470fa85d2f71dc94930f03ebe4823/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md?plain=1#L60-L62

At the same time, the section `Future Considerations` allows cross-platform use:

https://github.com/microsoft/terminal/blob/612b00cd445470fa85d2f71dc94930f03ebe4823/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md?plain=1#L411-L416

## Improvements

List of possible improvements, issues and use cases not covered by this keyboard protocol:
- ~~No way to restore the normal mode of the terminal when the connection is lost or the application crashes.~~
  https://github.com/microsoft/terminal/issues/8343#issuecomment-1586225095
- Support `win32-input-mode` request acknowledgment with the current state of keyboard modifiers.
  - Req: `^[[?9001h`
  - Ack: `^[[0;0;0;0;CtrlState;0_`
- Support for <kbd>LeftShift</kbd> and <kbd>RightShift</kbd> modifiers along with <kbd>Shift</kbd>.
- Support for Unicode codepoint decimal value (for BaseCharacter) instead of UnicodeChar (Uc), which currently represents one UTF-16 code unit (wchar_t).
  `^[[Vk;Sc;Uc;Kd;Cs;Rc_` => `^[[Vk;Sc;BaseCharacter;Kd;Cs;Rc_`
- Support for passing/receiving an entire [grapheme cluster](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries) as one keyboard event in order to get it by a single ReadKey call, e.g. getting an accented letter `á` represented as a sequence of [codepoints](https://en.wikipedia.org/wiki/Code_point). (`GC` = `BaseCharacter` + `Codepoint1` + `Cp2` + … + `CpN`).
  #2853
  https://github.com/microsoft/terminal/issues/8343#issuecomment-1586225095
  https://github.com/microsoft/terminal/issues/8343#issuecomment-1586288563

  Possible solution:
  - Add continuing codepoints as optional arguments to the event sequence:
  `^[[Vk;Sc;BaseCharacter;Kd;Cs;Rc [ ; Codepoint1 ; Cp2 ; … ; CpN ] _`
- Sending clipboard data without additional generation of keystroke sequence, since this data must already be enclosed (mandatory [bracketed paste mode](https://en.wikipedia.org/wiki/Bracketed-paste)).

## Example

When the user presses in the console
* ...
* Press <kbd>Key1</kbd>
* Release <kbd>Key1</kbd>
* Press <kbd>á</kbd>
* Release <kbd>á</kbd>
* Press <kbd>🏴‍☠️</kbd>
* Release <kbd>🏴‍☠️</kbd>
* Press <kbd>Ctrl</kbd>
* Press <kbd>Key2</kbd>
* Release <kbd>Key2</kbd>
* Release <kbd>Ctrl</kbd>
* ...
* Paste from clipboard by mouse right click
* ...
* Press <kbd>F5</kbd>
* Release <kbd>F5</kbd>
* ...

Note: `🏴‍☠️` = `U+1F3F4 Black Flag` + `U+200D ZWJ` + `U+2620 Skull and Crossbones` + `U+FE0F VS16`

The input stream would look like the following:
```
...
^[[x;x;x;pressed;0;1_
^[[x;x;x;released;0;1_
^[[x;x;65;pressed;0;1;769_
^[[x;x;65;released;0;1;769_
^[[x;x;127988;pressed;0;1;8205;9760;65039_
^[[x;x;127988;released;0;1;8205;9760;65039_
^[[17;29;0;1;8;1_
^[[x;x;x;pressed;8;1_
^[[x;x;x;released;8;1_
^[[17;29;0;0;0;1_
...
^[[200~ clipboard_utf-8_raw_data ^[[201~
...
^[[116;114;0;1;0;1_
^[[116;114;0;0;0;1_
...
```

**Comment by j4james** [comment]
> No way to restore the normal mode of the terminal when the connection is lost or the application crashes.

This is a general problem that can apply to a lot of terminal states. Some of them you could potentially recover from by blindly typing `reset` in a WSL shell, or echoing an appropriate escape sequence, but that's not a realistic solution for most users. We need something like a `Reset Terminal` action that'll allow the user to easily recover from any messed up state - not just this one particular keyboard protocol.

This is a fairly common feature in terminal emulators, and I could have sworn we already had an issue for it, but I can't find it now. It's possible it was just something that was discussed in an unrelated issue, but we definitely should open an issue for it if there isn't one.

> No way to get an entire grapheme cluster via single read key call, i.e. get accented a-letter `á` that represented as a codepoint sequence.

But the win32-input-mode is a direct representation of the key events we receive. If there was keyboard that allowed you to enter grapheme clusters, that would have to be in the form of multiple key events, and this is something that applications would already be expected to handle. Same goes for any characters outside the BMP for that matter - they're going to appear as two separate key events to represent the surrogate pair. We can't report a UTF-8 representation for combined events that we haven't received yet.

**Comment by o-sdn-o** [comment]
I believe that it is necessary to avoid unreasonable fragmentation of the grapheme cluster for the following reason.
The application must be able to compose codepoints into clusters. At the same time, it should mark how the cluster was composed. In the general case, it makes sense to distinguish a grapheme cluster assembled with several keystrokes from a grapheme cluster generated with one keystroke, since when deleting it with Backspace, in the first case, the codepoints will have to be deleted one-by-one, in the second, the whole cluster at a time. By using the Del key in both cases, we can delete the entire cluster.

For example, a user can compose a cluster by typing codepoint by codepoint using Alt+Num, and in the process correct errors using Backspace. Also, the user can use IME with one keystroke to get a complex cluster, and delete it with Backspace also in one keystroke.

**Comment by o-sdn-o** [comment]
In a scenario where the terminal does not support win32-input-mode, the application falls into an undefined state. It has received the cluster and is waiting for the win32-input sequence. Oops.

It turns out that it is possible to transfer a complete cluster as one event only by adding optional continuing codepoints as additional arguments to the event sequence.

```
^[[Vk;Sc;BaseCharacter;Kd;Cs;Rc [ ; Codepoint1 ; Cp2 ; … ; CpN ] _
```

**Comment by o-sdn-o** [comment]
Closing this issue in favor of [`kvm-input-mode` protocol](https://github.com/netxs-group/vtm/issues/400) (backward compatible with `win32-input-mode`).

**Comment by j4james** [comment]
> For example, a user can compose a cluster by typing codepoint by codepoint using Alt+Num, and in the process correct errors using Backspace. Also, the user can use IME with one keystroke to get a complex cluster, and delete it with Backspace also in one keystroke.

Assuming this was possible, what happens when your editor saves these two different clusters to disk and later reloads them? Now there's no way to distinguish between the two, and a backspace would work in exactly the same way for both of them. To a user, the backspace behavior would just seem random.

I really cannot imagine an editor going to all that effort, when it's just going to cause confusion. If anything, it might make sense to backspace over the entire cluster with one keystroke in _all_ cases, regardless of how the cluster was entered. That at least would be consistent.

**Comment by o-sdn-o** [comment]
It would be important for me here to clarify that we are talking only about the current open cluster in which code points are currently being added.

**Comment by j4james** [comment]
Then I don't understand why you'd need to tell the difference between a cluster entered as a single keystroke and one entered with multiple keystrokes. If the keyboard protocol splits a cluster into multiple keystrokes, the final keystroke would assumedly close the cluster, so it's still going to immediately become atomic isn't it?

**Comment by o-sdn-o** [comment]
The last entered cluster must be kept open, since it is not known whether an additional joiner will arrive or not, for example, with a skin tone modifier.

**Comment by o-sdn-o** [comment]
User can manually construct a grapheme cluster of any length they want by stringing together multiple zero-width joiners.

**Comment by j4james** [comment]
We seem to be going in circles here. I refer you back to my comment here: https://github.com/microsoft/terminal/issues/8343#issuecomment-1588876569

I understand what you're suggesting - I just don't think it's a very good idea. That's just my opinion.

**Comment by o-sdn-o** [comment]
> it might make sense to backspace over the entire cluster with one keystroke in all cases, regardless of how the cluster was entered.

For example GitHub web interface allows you to ZWJ+codepoint-by-ZWJ+codepoint backspace a complex cluster. Try to backspace the following cluster 🏴‍☠️. I am using FF as my desktop browser. It may behave differently in other browsers. Windows Notepad and Notepad++ allows you to backspace codepoint-by-codepoint.

**Comment by o-sdn-o** [comment]
And it's annoying when you insert a complex cluster with a single keystroke, and to remove it you have to press the backspace a dozen times. This does not apply to rare emoji. It seems to me when using a Devanagari-like writing system with complex clusters in each syllable, this is critical.

**Comment by j4james** [comment]
This seems like something I'd want to configure in my editor though. Sometimes I might prefer backspacing over individual parts of a cluster, and sometimes I might prefer deleting the entire thing with a single backspace. That should be my choice to make, so I know it's going to work exactly the way I expect. I definitely wouldn't want the behavior randomly changing depending on which IME I happened to use, and then potentially changing again when I reload the content from disk.

**Comment by o-sdn-o** [comment]
I agree that disputes about what atomic or piecewise grapheme clusters should be is a matter of settings. But that's not the point.

I am based on the assumption that a certain operating system can output an entire cluster at a single keystroke, and I consider it fundamentally wrong to split it into a sequence of distinct keypresses and releases, as required by the current win32-input-mode implementation.

**Comment by j4james** [comment]
> I consider it fundamentally wrong to split it into a sequence of distinct keypresses and releases

I sympathise with that viewpoint, but from my understanding of your proposed protocol, you're just creating more work for app devs. They already have to accept a cluster split into distinct keypresses, but now they also have to check for additional parameters at the end of the sequence that might be continuing codepoints. So unless there is some value to them in distinguishing between the two, it's just bunch of extra work for nothing.

Also, if an app has already been designed to work with win32-input-mode, they're not going to be expecting those continuing codepoints, so they'd lose half of the cluster. That is not what I would consider backwards compatible. So if you want to extend the protocol like this, I'd encourage you to use a different mode number.

The additional viewport and mouse stuff is an even bigger issue, but I don't want to get into a discussion about protocol design. As long as it's a separate mode that an application has specifically requested, you can do whatever you want.

**Comment by o-sdn-o** [comment]
> Also, if an app has already been designed to work with win32-input-mode, they're not going to be expecting those continuing codepoints

I adapt the protocol model in case of undefined behavior of existing win32-input-mode-aware applications.

**Comment by o-sdn-o** [comment]
It also seems to me that using the win32-input-mode protocol, it is quite difficult to determine two simultaneously pressed buttons if at least one of them generates a complex cluster. What should the incoming stream look like for <kbd>á + 🏴‍☠️</kbd>? Eight (powered by surrogate pairs?), six or two keys pressed and released?

**Comment by o-sdn-o** [comment]
What about auto-repeat keys? It also seems to be difficult to distinguish an auto-generated key event between the original press and release.

**Comment by o-sdn-o** [comment]
> The additional viewport and mouse stuff is an even bigger issue, but I don't want to get into a discussion about protocol design.

To be honest, this is strange to me. A couple of remarks on this subject, if you will, without continuing the discussion.

I haven't seen a command shell whose prompt didn't get corrupted when the terminal window is resized. The secret is that after resizing, the shell loses all coordinate reference points: cursor coordinates, sizes of scrollable fields, etc. And the solution is almost on the table. First: The shell does not get the size of the window synchronously. Second The shell does not receive information about what else has changed after the resize.

Let's send the window size to the application synchronously and what we see:
Note: The Calc app is a standalone external TUI app that just receives window size synchronously instead of SIGWINCH.

https://github.com/microsoft/terminal/assets/11535558/c56c6565-7c85-4d79-9d43-6161fba9bebe

Let's update the coordinate reference points for the application after window resize and what we see:
Note: cmd.exe as a standalone TUI application, and they don't loose their prompt after terminal window resize!

https://github.com/microsoft/terminal/assets/11535558/909598a6-9f5d-4139-9063-4965203abf1c
