### ISSUE TITLE
Preview what actions will be run in commandline mode of the CmdPal

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#8344]
So we've already got an open work item tracking "display the parse error (if any) in commandline mode",  #7284. What if, when we determine that the commandline is valid, we then display what commands are about to be executed, instead of the parse error?

So if you type in 
```
nt ssh user@server.com
```

We'll parse that, and that won't generate an error message, it'll instead successfully turn into a `newTab(commandline="ssh user@server.com")` action. We'll then take that action, and call `GenerateName` on it, and we'll get "Open a new tab, commandline: ssh user@server.com". We'll then display _that_ text to the user, as a preview of what they're about to run.

**Comment by Don-Vito** [comment]
@zadjii-msft - we need to consider the UX as I already put the history into the palette..

**Comment by zadjii-msft** [comment]
Yea, I've been thinking about that. The history is definitely better - but is there a sensible way of having both these things?

This is my terrible mockup:
![image](https://user-images.githubusercontent.com/18356694/99807240-d5194a00-2b04-11eb-82c9-dbcda6ffd3db.png)

(too lazy to bold results in the mockup)

So in this case, the user is typing a command, and they _could_ select the `nt -p Ubuntu ; ...` command from the history, but until they do, we'd display the error (or results) after a short delay. I'm not sure how that really feels. 

Or I guess when it's successful:
![image](https://user-images.githubusercontent.com/18356694/99807678-77393200-2b05-11eb-9631-35ec2843fd0c.png)

**Comment by Don-Vito** [comment]
@zadjii-msft - some off-topics

1. how do you create the mockups - this is really cool! 
2. There is another aspect that I was thinking of is prediction from history.

Here how it goes:
1. You start typing
2. Then you go down to the history
3. Once you navigate through the items there, the text in the search box receives a relevant suffix in a weaker font
4. If you press tab key it makes the suffix to be a part of the search box

So you can:
1. Write nt
2. Go to nt -p Ubuntu; sp --tabColor #ff00ff
3. Press tab
4. Continue typing "; sp" to get nt -p Ubuntu; sp --tabColor #ff00ff ; sp
4. And then to continue typing to get something like

**Comment by zadjii-msft** [comment]
It's an app called [XAML Studio](https://www.microsoft.com/en-us/p/xaml-studio/9ntls214tkmq?rtc=1), which is an absolute lifesaver.

I certainly like the "tab complete" functionality you've suggested here. I dunno how hard it'd be to actually implement, I'm not sure how hard it would be to have multiple styles of text in a single text box. Maybe there's another type of control that would allow for it, but my XAML-fu is not that strong.

**Comment by Don-Vito** [comment]
> 
> 
> It's an app called [XAML Studio](https://www.microsoft.com/en-us/p/xaml-studio/9ntls214tkmq?rtc=1), which is an absolute lifesaver.
> 
> I certainly like the "tab complete" functionality you've suggested here. I dunno how hard it'd be to actually implement, I'm not sure how hard it would be to have multiple styles of text in a single text box. Maybe there's another type of control that would allow for it, but my XAML-fu is not that strong.

Thanks! I will try to use it!
I guess we will need to overlay some transparent label or something like this.

**Comment by Don-Vito** [comment]
Hey. I played for an hour with this. I will open a PR for some initial step :blush:

**Comment by zadjii-msft** [comment]
Y A Y

**Comment by Don-Vito** [comment]
![CmdPalPrediction](https://user-images.githubusercontent.com/4639110/101365312-51a17c00-38ac-11eb-9a72-de367eb3a0cd.gif)
