### ISSUE TITLE
Use sccache on CI to reduce the build time

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#8349]
# Description of the new feature/enhancement

I just found this amazing project [sccache](https://github.com/mozilla/sccache) by Mozilla, which is a improved version of ccache and can be used to speed up the build.

I found it in the PyTorch CircleCI run like [this one](https://app.circleci.com/pipelines/github/pytorch/pytorch/241977/workflows/d0eb985d-94c9-428c-9c2e-e58bb8217fcf/jobs/9103296).

Per the documentation of sccache:
>sccache is a ccache-like compiler caching tool. It is used as a compiler wrapper and avoids compilation when possible, storing cached results either on local disk or in one of several cloud storage backends.
>
>sccache includes support for caching the compilation of C/C++ code, Rust, as well as NVIDIA's CUDA using nvcc.
>sccache also provides icecream-style distributed compilation
 

# Proposed technical implementation details (optional)

By simply storing cached compilation result on cloud storage, I think we can speed up the compilation dramatically. And there's more - distributed compilation!

I'm not sure Azure DevOps builtin sccache support, though. That would be a problem.

**Comment by zadjii-msft** [comment]
> I'm not sure Azure DevOps builtin sccache support, though. That would be a problem.

That's certainly problem number 1. The other thought I have is, and I might just not be understanding how `sccache` works, but what artifacts would we exactly be caching? The majority of the build time is spent on pch.h generation, and we already can't share those across projects
