### ISSUE TITLE
run "Windows Terminal" on ubuntu

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#8350]
# Description of the new feature/enhancement
I work in windows and linux platform. windows terminal is more and more better. I want to use it in ubuntu , but I see the package is for windows only, any idea ?

# Proposed technical implementation details (optional)

**Comment by alannt777** [comment]
wontfix

**Comment by alannt777** [comment]
The name is "Windows" Terminal

**Comment by alannt777** [comment]
Also the Terminal calls APIs that are not available or different in Linux

**Comment by skyline75489** [comment]
/dup #2331 #504 #563 #624 #2466 #699 #498 #6074 #4235

**Comment by tlsalex** [comment]
Thanks, but "Microsoft Edge is for Windows" ,and it's available for Linux now. -- [https://blogs.windows.com/msedgedev/2020/10/20/microsoft-edge-dev-linux/](url)

Hope the same thing happen for Windows Terminal.

**Comment by alannt777** [comment]
But the it's "chromium" Edge which is cross platform. The UWP Edge can't. The same way, Windows Terminal uses UWP XAML.

**Comment by DHowett** [comment]
Thanks for the request! We are definitely not planning on doing this. There are so many very good terminals on Linux :smile:
