### ISSUE TITLE
Close command palette on focus loss

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#8355]
# Description of the new feature/enhancement
Currently we dismiss command palette programmatically if user clicks in the bounds of "Tab Content" (second grid row of the terminal page), however if the click is performed outside of these boundaries (e.g., outside of the terminal window or in the tab row) we do not dismiss the palette.

And this is problematic for many reasons. 

Here is the simplest example - opening a tab while palette is open leaves it open an without a focus (meaning it can be closed only with mouse):

![PaletteLostFocusOpenTab](https://user-images.githubusercontent.com/4639110/99885047-eb292680-2c3a-11eb-9d6f-3264abaaf0c3.gif)

Same can be achieved by clicking on menu, and then click outside of it (but now you cannot even type)

![PaletteLostFocusOpenMenu](https://user-images.githubusercontent.com/4639110/99885050-ef554400-2c3a-11eb-9f50-c1763303a893.gif)

Same of course happens for the tab switcher 
![PaletteLostFocus](https://user-images.githubusercontent.com/4639110/99885175-c3868e00-2c3b-11eb-85e5-a0c185455ee0.gif)

This might might be a root cause for https://github.com/microsoft/terminal/issues/8319.

The idea here is to close the palette upon focus loss.
There are two approaches to it:
1. Close the palette upon focus loss - this approach is taken in VS Code.
 * This approach is more hermetic
 * This approach introduces a more significant change in user experience, since now clicking another window closes the palette
2. Close palette when clicking on the tab row (or more precisely on any row of the terminal page which is not the one that palette resides in)
 * This will have lesser impact on the experience
 * But it will not help us if the focus is somehow lost no by clicking
3. Close palette when tabs items are modified

**Comment by DHowett** [comment]
My opinion: we should definitely do (1). It’s an ephemeral UI, users should not expect that it will hang around forever. 

@zadjii-msft what does Sublime do?

**Comment by Don-Vito** [comment]
I am checking how to do it hypothetically.. so if @zadjii-msft likes this approach I will probably have some draft..
I guess we will need to do both 1 and 3 (because closing tab doesn't modify the focus)..

**Comment by Don-Vito** [comment]
@zadjii-msft - if you like the idea I have the code.. but it is probably the worst one I wrote since I was 10: there are several small nuances that I had to handle each one of them.. probably there is some better solution, but I am still not in enough to see it.

**Comment by Don-Vito** [comment]
Added the PR Draft so it won't get lost.

**Comment by zadjii-msft** [comment]
(I want to get back to this before the EOD but I'm also worried I might not, and I'm about to start a 6 day vacation. Just wanted to give a heads up)

**Comment by Don-Vito** [comment]
> 
> 
> (I want to get back to this before the EOD but I'm also worried I might not, and I'm about to start a 6 day vacation. Just wanted to give a heads up)

Thanks for the heads up and enjoy your vacation! 
Don't be worried - IMHO this quite standalone and not urgent (it can probably resolve #8319, but I don't even now what Priority-2 means in terms of SLAs 😄 )
Happy holidays!
