### ISSUE TITLE
Acrylic Opacity renders incorrectly when used with the Windows Magnifier

### ISSUE THREAD

**Issue by jrconradt** [microsoft/terminal#8356]
# Environment

```
Windows build number: Microsoft Windows NT 10.0.20262.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
Magnifier
```

# Steps to reproduce

Set 
```
            "acrylicOpacity": 0,
            "useAcrylic": true
```
Enable magnifier, zoom to >3x while looking at the terminal to see impact clearly.

# Expected behavior
Zoom on terminal, terminal background stays consistent.
![image](https://user-images.githubusercontent.com/49211734/99889932-d9ca2500-2c0e-11eb-9400-1ed90a7fe80b.png)

# Actual behavior
Transparent background grabs zoomed viewport, scales down to viewport size relative to actual, and renders this smaller image as background from top left. 
![image](https://user-images.githubusercontent.com/49211734/99889952-14cc5880-2c0f-11eb-9b6a-b707d52d7928.png)

**Comment by DHowett** [comment]
This is, unfortunately, an issue with the Magnifier application.
