### ISSUE TITLE
ssh: connect to host github.com port 22: Network is unreachable fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by allonint** [microsoft/terminal#8359]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by allonint** [comment]
ssh: connect to host github.com port 22: Network is unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DHowett** [comment]
We are not at fault for your computer being unable to reach github. Sorry.
