### ISSUE TITLE
Some characters can not be recongized by Python shell in docker

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#8360]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 10.0.19041.572
Windows Terminal version (if applicable): master on 67dfbd21a6b37025ebc0cc435c2ddf791e32811a

Any other software?
```

Docker

# Steps to reproduce

Using Python installed by `apt install python3` in a `ubuntu:18.04` docker image, and Microsoft Chinese IME, type `中文` in Chinese mode in Python shell.

# Expected behavior

It works

# Actual behavior

Something weird happens:

![image](https://user-images.githubusercontent.com/4710575/99894339-228ce700-2cbe-11eb-989f-02daca917777.png)

It feels like I'm using and `alt` + something.

And I'm using `’` (a Chinese `'`), sometimes nothing happens. Somethings it feels like I'm typing a `(` (and backwards):

![image](https://user-images.githubusercontent.com/4710575/99894437-74ce0800-2cbe-11eb-8ddd-8e202bac5597.png)

It actually works in Python provided by anaconda:

![image](https://user-images.githubusercontent.com/4710575/99893697-b5c51d00-2cbc-11eb-859f-03d07ba9ae8b.png)

**Comment by skyline75489** [comment]
I found some similarity in #7589 , however I'm not sure it's the same thing. I found in `convert.cpp`, there's `CharToKeyEvents` which will convert `中文` into `alt` + `中文`, which I do not fully understand.

**Comment by skyline75489** [comment]
OK, I've tried this with Guake on Linux. It behaves exactly the same. Now that I think of it, perhaps I should not expect dockered Python without UTF-8 support to naturally accept UTF-8 content.

**Comment by zadjii-msft** [comment]
>  I've tried this with Guake on Linux. It behaves exactly the same

So, presumably that would mean this is an external bug, yea?
