### ISSUE TITLE
Can this be a object in C# UI design?

### ISSUE THREAD

**Issue by xeriax** [microsoft/terminal#8362]
Hi there,
Can this be a object in C# UI design?
if this can be use as an object in my application then it would be great!

**Comment by KalleOlaviNiemitalo** [comment]
There is some advice in <https://github.com/microsoft/terminal/issues/4572#issuecomment-586060398> and subsequent comments. See also WpfTerminalTestNetCore: <https://github.com/microsoft/terminal/blob/f3cdf6841fa116c79b49273bb8df0039a1366a49/src/cascadia/WpfTerminalTestNetCore/WpfTerminalTestNetCore/MainWindow.xaml#L11>

**Comment by zadjii-msft** [comment]
@xeriax Do you have a tech stack in mind? Either WPF or UWP? The advice is a little different depending on what you're pursuing.

**Comment by xeriax** [comment]
No, only WinForm.

**Comment by alannt777** [comment]
> @xeriax Do you have a tech stack in mind? Either WPF or UWP? The advice is a little different depending on what you're pursuing.

@zadjii-msft Can you give advice for both?

**Comment by DHowett** [comment]
@alannt777 not at the moment, no. Our UWP and WPF controls are not a contract we're ready to support. :smile:

@xeriax ah, that's unfortunate. Our infrastructure supports rendering to a random window handle, but we do not currently have a control that will let you do so.

**Comment by alannt777** [comment]
But what did @zadjii-msft meant by "advice"? He could have straight up said no...

**Comment by zadjii-msft** [comment]
In retrospect, I should have probably just said no. If someone was _particularly motivated_, they could find a WpfControl and a UWP TerminalControl within this repo, and they could theoretically embed them in another app. But as Dustin correctly calls out, it's not a contract we're prepared to support officially, so any use of them would be subject to us changing the interface at our own discretion. So, here be dragons.
