### ISSUE TITLE
Allow setting environment variables in profiles

### ISSUE THREAD

**Issue by xnoreq** [microsoft/terminal#8364]
# Description of the new feature/enhancement

Allow setting environment variables in profiles.
This eliminates the need to launch wrapper tools or scripts that set environment variables and then launch a shell.

# Proposed technical implementation details (optional)

Add a new "environmentVariables" property to profiles, which contains an object with additional environment variables.
The "commandline" is then started with these environment variable set.

Example:
```
{
	"guid": "{some guid}",
	"name": "Bash",
	"commandline": "C:\\bash.exe",
	"hidden": false,
	"environmentVariables": {
		"ENVVAR1": "VALUE1",
		"ENVVAR2": "VALUE2
	}
}
```

**Comment by KalleOlaviNiemitalo** [comment]
Also requested in <https://github.com/microsoft/terminal/issues/2785> and <https://github.com/microsoft/terminal/issues/6604>.

**Comment by zadjii-msft** [comment]
Yep, sure is. Thanks for the help @KalleOlaviNiemitalo!

/dup #2785
