### ISSUE TITLE
Tab title stop changing dynamically after rename textbox is dismissed

### ISSUE THREAD

**Issue by mpela81** [microsoft/terminal#8365]
# Environment
```none
Windows Terminal version (if applicable): current main branch
```

# Steps to reproduce
- Open WSL in a new tab (the tab title reflects the current working dir)
- Double-click tab header to rename
- Dismiss the rename text box (e.g. press Esc)
- Change the current working directory in WSL

# Expected behavior
The tab title reflects the new current working directory

# Actual behavior
The tab title does not change, as if it was overridden by the rename operation

Maybe related to changes in #8227?

**Comment by Don-Vito** [comment]
I believe it is related. Once you click escape it reverts the contents of the HeaderRenamerTextBox to be the original one (e.g., mnt/c) but still calls _TitleChangeRequestedHandlers, that invokes TerminalTab::SetTabText that invokes UpdateTitle, that calls SetTabText that sets _runtimeTabText, that won't be overridden by control.

**Comment by DHowett** [comment]
@Don-Vito some discussion here about why it was not given control over the title: https://github.com/microsoft/terminal/pull/8227#discussion_r524407402

The whole comment chain is pretty good.

It seems very similar to TabView's TabCloseRequested: the view is not the datamodel, it should not be allowed to be the datamodel, it should only communicate desired state changes to its keepers. :smile:
