### ISSUE TITLE
Specify an audio file for the audible bell

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#8366]
# Description of the new feature/enhancement

Please let me configure the audible bell so that it plays a sound other than "Critical Stop". I'd like to select a sound with a shorter duration and perhaps lower volume.

This request is for Windows Terminal, not the console host.

# Proposed technical implementation details (optional)

Ever since <https://github.com/microsoft/terminal/pull/7679>, the implementation of the audible bell hardcodes SND_ALIAS_SYSTEMHAND: <https://github.com/microsoft/terminal/blob/67dfbd21a6b37025ebc0cc435c2ddf791e32811a/src/cascadia/TerminalApp/Pane.cpp#L373-L374>

I can think of two ways to make this configurable:

* Let me specify the path of a sound file in settings.json.  I think this should be configurable per profile, like the bellStyle setting (<https://github.com/microsoft/terminal/issues/2360>) is.

* Alternatively, register Windows Terminal with the "Change system sounds" feature in Control Panel so that I can choose a sound there. According to [C++ at Work: Web Version Checking, Adding Sound to an App](https://docs.microsoft.com/en-us/archive/msdn-magazine/2006/may/c-at-work-web-version-checking-adding-sound-to-an-app), this involves the HKEY_CURRENT_USER\AppEvents\Schemes\Apps Registry key and the SND_APPLICATION flag. I suspect that the MSIX packaging of Windows Terminal won't allow writing to such Registry keys, though.

**Comment by zadjii-msft** [comment]
I absolutely agree that this is a reasonable feature request. From our team's internal Teams channel:

![image](https://user-images.githubusercontent.com/18356694/99960844-08511880-2d53-11eb-9e91-f9c0d09bb6ee.png)

**Comment by electronic-dk** [comment]
Which audio file types will the terminal be supporting in this case? Only wav?
P.S. The bruh sound looks like a perfect choice for the bell, but I'd definitely like to set john cena theme as the bell sound.

**Comment by zadjii-msft** [comment]
It probably shouldn't just be .wav - hopefully XAML/WinRT have some convenient APIs we could use for loading and playing audio files that'll accept a wide gamut of file types

**Comment by WSLUser** [comment]
> Alternatively, register Windows Terminal with the "Change system sounds" feature in Control Panel so that I can choose a sound there. 

I would like this to be an option as well if possible or make the sounds available at least.

**Comment by KalleOlaviNiemitalo** [comment]
If WinRT has spatial audio APIs, I might be able to hear which monitor contains the terminal that is ringing the bell.

**Comment by j4james** [comment]
If there's not a lot of demand for a per-profile setting, I'd also be on favour of us handling this with a custom sound event that could be configured from the control panel. That way it could (hopefully) be shared with conhost too.

There's no reason why it couldn't also be set from within the Terminal settings GUI, once that's in place. It's just that the underlying config would be stored in the registry rather than the current json file.

See also: https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-sound

**Comment by PhMajerus** [comment]
> If WinRT has spatial audio APIs, I might be able to hear which monitor contains the terminal that is ringing the bell.

I think this should be global in Windows instead of a Terminal feature.

I've suggested years ago, especially for multi-monitor setups, to have all apps audio be spatially located according to their position. It can be difficult since Windows typically knows which process the sound is coming from but not which window precisely, but anchoring the sound to the top level window of each process would be a great option.
Locating the sound according to the desktop coordinate would require some calibration step to know where the monitors and speakers are and how their coordinates map, so it would be better as a global Windows setting.

Note Windows Mixed Reality actually does this for UWP apps already, as it is even more important when your apps are all around you in the WinMR home 3D environment instead of in a 2D desktop.

**Comment by KalleOlaviNiemitalo** [comment]
PSReadLine 2.1.0 seems to be using Console.Beep(1221, 50) by default: [Cmdlets.cs](<https://github.com/PowerShell/PSReadLine/blob/3856776b1d215873a51ab0d0fe0f9a91f6ac2d67/PSReadLine/Cmdlets.cs#L121-L126> "PSReadLine/Cmdlets.cs at 3856776b1d215873a51ab0d0fe0f9a91f6ac2d67 · PowerShell/PSReadLine"), [Render.cs](<https://github.com/PowerShell/PSReadLine/blob/3856776b1d215873a51ab0d0fe0f9a91f6ac2d67/PSReadLine/Render.cs#L1240> "PSReadLine/Render.cs at 3856776b1d215873a51ab0d0fe0f9a91f6ac2d67 · PowerShell/PSReadLine"). Perhaps Windows Terminal could offer a configurable beep as an alternative to an audio file.

* How to specify the parameters in settings,json? Could be `"bellFrequency": 1221, "bellDuration": 50`. IIRC, some media player supported encoding frequencies and durations in a URI, but I presume that would be more difficult to map to the settings UI, and I can't find it in [IANA's list of URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).
* The [Beep](<https://docs.microsoft.com/windows/win32/api/utilapiset/nf-utilapiset-beep)> "Beep function (utilapiset.h) - Win32 apps | Microsoft Docs") function waits until the sound ends. That could slow down Windows Terminal. Could be avoided by having Windows Terminal instead generate a waveform in memory and then play it with some other API.

**Comment by steevenlee** [comment]
Pretty noisy, need a way to disable it ASAP.

**Comment by Don-Vito** [comment]
> 
> 
> Pretty noisy, need a way to disable it ASAP.

Consider using
```
"bellStyle": "none"
```

**Comment by steevenlee** [comment]
> Consider using
> 
> ```
> "bellStyle": "none"
> ```

not sure why it doesn't work for me. 1.5.10411.0

**Comment by Don-Vito** [comment]
@steevenlee - can you please attach your settings?

**Comment by steevenlee** [comment]
> @steevenlee - can you please attach your settings?
Tried again, applying it to server profile works. Better to have a global setting IMHO.

**Comment by Don-Vito** [comment]
> 
> 
> > @steevenlee - can you please attach your settings?
> > Tried again, applying it to server profile works. Better to have a global setting IMHO.

You need to put it in the default profile to have it globally.

**Comment by bbhoss** [comment]
It would be nice if the bell were configurable per-profile. That way if you had something that emitted a bell when it was finished executing a long-running process, you could easily distinguish it from the default bell.

**Comment by zadjii-msft** [comment]
@bbhoss yep, we're definitely planning on making this per-profile. In fact, the `"bellSound": "bruh.wav"` example from earlier was exactly what convinced the team to make the bell settings per-profile in the first place 😉

**Comment by Lexicality** [comment]
🎉 Thank you so much for implementing my suggestion! Do you know when the next release is likely to be?

**Comment by zadjii-msft** [comment]
@Lexicality At this moment, no. We've been on a bit of a slow burn leading up to the holidays. I imagine it won't be for at least a few more weeks.
