### ISSUE TITLE
need an option to set the color of autocomplete

### ISSUE THREAD

**Issue by shuizhongyueming** [microsoft/terminal#8373]
# Description of the new feature/enhancement

I'm using the Windows Terminal Preview with Version 1.5.3242.0 and using the PowerShell.

I have set the `backgroundImage` with `desktopWallpaper`, it's a nice feature, but the autocomplete will be hard to identify

![image](https://user-images.githubusercontent.com/2059860/99936451-27c16300-2d9e-11eb-872d-9c4dcce01511.png)

I have tested the color scheme for windows terminal, but it seems that none of the color will affect the color of the autocomplete.

```javascript
// profile
            {
              "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
              "hidden": false,
              "name": "PowerShell",
              "source": "Windows.Terminal.PowershellCore",
              "closeOnExit": true,
              "colorScheme": "Dracula",
              "cursorColor": "#FFFFFF",
              "cursorShape": "bar",
              "fontSize": 12,
              "fontFace": "Cascadia Mono PL",
              "acrylicOpacity": 0.5,
              "historySize": 9001,
              "snapOnInput": true,
              "padding": "20, 10, 20, 20",
              "backgroundImage": "desktopWallpaper",
              "backgroundImageOpacity": 0.1,
              "useAcrylic": false
            },

// color scheme
        {
          "background": "#282A36",
          "black": "#21222C",
          "blue": "#BD93F9",
          "brightBlack": "#6272A4",
          "brightBlue": "#D6ACFF",
          "brightCyan": "#A4FFFF",
          "brightGreen": "#69FF94",
          "brightPurple": "#FF92DF",
          "brightRed": "#FF6E6E",
          "brightWhite": "#FFFFFF",
          "brightYellow": "#FFFFA5",
          "cyan": "#8BE9FD",
          "foreground": "#F8F8F2",
          "green": "#50FA7B",
          "name": "Dracula",
          "purple": "#FF79C6",
          "red": "#FF5555",
          "white": "#F8F8F2",
          "yellow": "#F1FA8C"
        },
```

# Proposed technical implementation details (optional)

Did I miss some option for this feature, or can we add an option to set he color of autocomplete and its opacity?

**Comment by DHowett** [comment]
You will need  to configure this using the PSReadline options. Terminal does not offer autocomplete, PowerShell does. Sorry.

**Comment by shuizhongyueming** [comment]
Thank you, I have found the options from the PSReadline

https://github.com/PowerShell/PSReadLine/issues/1550
