### ISSUE TITLE
REPL / shells installed from store (non-linux / non-MS) not added to the new terminal

### ISSUE THREAD

**Issue by bhramchari** [microsoft/terminal#8381]
![Screenshot 2020-11-23 175922](https://user-images.githubusercontent.com/43825927/100028961-bb525e00-2db5-11eb-933f-a4187b37a8d5.jpg)

REPL / shells installed from store (non-linux / non-MS) not added to the new Terminal. Attached image for reference, can this be fixed/enabled/added in future releases ? Due to this limitation we can't use the new Terminal to access Python or other shells installed from the Store. 

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
❯ [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal version (if applicable): Version: 1.4.3243.0

Any other software? 
Python 3.7 installed from the MS Store, PS Core 7.1 from MS Store
```

# Steps to reproduce

Install Python from the Store

# Expected behavior

With the new terminal ver 1.4+ the jumplist and other options should auto-populate the new options

# Actual behavior

Python 3.7 is not accessible from the new Terminal app, it launches its own console upon launching

**Comment by DHowett** [comment]
Alright, so..

1. The jumplist only updates when Terminal is launched
2. We autodetect like 7 different shells right now
3. If we keep autodetecting more, we're going to start driving users CRAZY (!)
4. There's a couple requests kicking around for this, but the one that is important is #7584  (spec) which will let Python _tell us where it is_. That's going to be easier than us searching high and low to find it.

/dup #7584
