### ISSUE TITLE
Always force-closed when auto-updated by windows store.

### ISSUE THREAD

**Issue by WestXu** [microsoft/terminal#8383]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0


Windows Terminal
1.4.3243.0

```

# Steps to reproduce

Auto-updated by windows store.

# Expected behavior

Postpone update when active process running in WT.

# Actual behavior

A warning suddenly pops up asking do I want to close all tabs just as if I clicked the close button on the top-right corner. I then click cancel, the warning disappeared normally. After about a minitue, the WT just closed itself, and windows store finished updating WT. I then checked those processes that were inside the WT, some of them just died, some still working in the background. I open a new WT, it's fresh with nothing resumed.

That's a serious issue.

**Comment by skyline75489** [comment]
I think #6726 covers part of this, if not all.

**Comment by WestXu** [comment]
Oh right it's a duplicate. Somehow I missed it. Sorry for that.
