### ISSUE TITLE
Install without Windows Store???

### ISSUE THREAD

**Issue by K2ouMais** [microsoft/terminal#8385]
Hello everybody,

is there a way to install the Windows Terminal without the Windows Store.

I would love to use this on my works developer maschine, but I dont have access to the windows store and I dont have administrator rights to install anything.

I would love to have a portable terminal, so that I can store into a folder and start it from there.

Is there a way to do this?

Thanks in advance for your help.

**Comment by pawel-miczka** [comment]
Portable version of Windows Terminal would be dope.

**Comment by Don-Vito** [comment]
You can definitely install without the store: on the home page of the project there are several ways of installing terminal without store, including download of binaries from GitHub. 

BUT :blush: I believe that, despite the title of the ticket, what you are mostly asking is whether there is a portable mode. I am not sure there is an official one, but I've seen few workarounds - please address the discussion in https://github.com/microsoft/terminal/issues/1386

**Comment by K2ouMais** [comment]
I have found a workaround myself.

I just had to unzip the package and I could start it with the exe in the files.

Yes, I would love to get a portable version and that should be the title anyway.

Thank you for your help.

**Comment by DHowett** [comment]
This is going to be covered by /dup #1386. Thanks!

**Comment by rismoney** [comment]
How can microsoft not figure out how to release using it's own installer technology after 3 years of that issue being opened.  jfc, #1386 shows this is just clown school.
