### ISSUE TITLE
Error 0xd0000022

### ISSUE THREAD

**Issue by magicmouses** [microsoft/terminal#8386]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable):

1.4.3141.0

Any other software?
```

# Steps to reproduce

when Windows Terminal start.

# Expected behavior

display command prompt

# Actual behavior

display error " start 'powershell.exe' error 0xd0000022"
start 'Windows Powershell', 'cmd', 'Azure Cloud Shell' and 'Ubuntu-20.04' have same error code 0xd0000022.

run Windows Terminal as administrator is ok.

**Comment by Don-Vito** [comment]
I believe there is an ongoing discussion on this here: https://github.com/microsoft/terminal/issues/6862

**Comment by DHowett** [comment]
Yes, this seems like the same 0xd0000022 as in /duplicate #6862. Please make sure you search before filing a new issue!
