### ISSUE TITLE
Run as admin/sudo button

### ISSUE THREAD

**Issue by tiziodcaio** [microsoft/terminal#8387]
# Description of the new feature/enhancement

Add run as administrator button/sudo mode

# Proposed technical implementation details (optional)

Really, it wouldn't be too hard...

**Comment by Don-Vito** [comment]
Please check if https://github.com/microsoft/terminal/issues/7715 covers you feature suggestion.

**Comment by tiziodcaio** [comment]
Yeah... Close??

**Comment by tiziodcaio** [comment]
Or merge?

**Comment by Don-Vito** [comment]
@tiziodcaio - I am not sure what does "merge" in this case mean :blush: But if everything is covered there, I believe you can close this one, as there is already a two-way link between the tickets.

**Comment by tiziodcaio** [comment]
Transferred on #7715
