### ISSUE TITLE
How to interrupt program without Ctrl-C?

### ISSUE THREAD

**Issue by 1vasari** [microsoft/terminal#839]
* Your Windows build number

`Microsoft Windows [Version 10.0.17134.765]`

* What you're doing and what's happening: 

I often use Ctrl-C to interrupt and restart a program however with the copy/paste functions now using the control key I'm not seeing a way to do this?

**Comment by eryksun** [comment]
If no text is selected, typing Ctrl+C in a cooked read should generate a `CTRL_C_EVENT` in all processes that are attached to the console. If text is selected, Ctrl+C copies to the clipboard and clears the selection. Press Ctrl+C a second time to generate the event. 

It's up to a program how it should handle this control event. It can ignore it or exit gracefully. By default a program started in a new console process group ignores Ctrl+C (e.g. CMD's `start /B` creates a new process group).  Try Ctrl+Break if Ctrl+C seems to be ignored. Ctrl+Break is rarely ignored, except by shells such as CMD. Usually Ctrl+Break is left to the default handler (i.e. exit immediately with `STATUS_CONTROL_C_EXIT`) or at least is handled by exiting gracefully.

**Comment by binarycrusader** [comment]
As @eryksun says, this is up to the shell you're running, not to the Windows Terminal program.

**Comment by binarycrusader** [comment]
See also #813

**Comment by 1vasari** [comment]
@eryksun I am using CMD and I can't seem to be able to do Ctrl-Break due to a lack of a Break key on my keyboard. Do you know of any alternatives? 

I appreciate the help.

**Comment by eryksun** [comment]
You may have an fn key that shifts another key to pause/break. Otherwise use the on-screen keyboard.

**Comment by K4pt4n** [comment]
using powershell 7.2.5 to run a ping -t command is not interruptible. Ctrl+c does not work. Ctrl+Break from the on-screen keyboard does not work.
Any other ideas? Kinda annoying.
