### ISSUE TITLE
DBCS characters rendered incorrectly when scrolling horizontally in conhost

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#8390]
# Environment

Windows build number: Version 10.0.18363.1198
Windows Terminal version (if applicable): Commit 1fbcf34ba8a5edfe2d78ffcf69496f10b9cc3d25

# Steps to reproduce

1. Build _OpenConsole_.
2. Run _Host.EXE_ with a bash shell.
3. Open the console properties and turn off _Wrap text output on resize_.
4. Also make sure the _Screen Buffer Size_ is wider than the _Window Size_ so there's a horizontal scrollbar.
5. Enter some DBCS characters at the prompt (the example below uses `子小尒尢`).
6. Wiggle the horizontal scroll bar backwards and forwards a few times, so those characters are being scrolled in and out of view.

I should add that I just picked these characters at random from charmap, so my apologies if they mean anything offensive.

# Expected behavior

The characters should always be rendered correctly.

![image](https://user-images.githubusercontent.com/4181424/100147658-946a5980-2e93-11eb-874a-78f6e3a365e2.png)

# Actual behavior

Sometimes the characters get chopped in half, or rendered in the wrong place so they're overlapping other characters.

![image](https://user-images.githubusercontent.com/4181424/100147691-9af8d100-2e93-11eb-94ed-d9d5870ba02f.png)

I can't reproduce this in the conhost that comes with my current version of Windows, so it looks like it might be a regression. But I also checked out the initial commit of _OpenConsole_ and it seems to have already been broken then. Is it possible my version of Windows is so old that it's prior to the first open source release?

Anyway, I think I know what the problem is - a couple of problems actually. I'll try and write up an explanation later with my proposed fix.

**Comment by j4james** [comment]
As far as I can tell, the problem is in the `Renderer::_PaintBufferOutputHelper` method. When the content starts with the trailing half of a DBCS character, it tries to move the `screenPoint` back a position, so it can safely render the full character. See below:

https://github.com/microsoft/terminal/blob/26ca73b823cde97cd2425baec62961947a8f85ee/src/renderer/base/renderer.cpp#L767-L783

But as you can see, if the X position is already in column 0, it instead moves forward one position and "skips" that character. At least that's the intention, but the code doesn't actually increment the iterator, so it just ends up rendering the character in the wrong place. And even if it worked as intended, at best you're going to end up with half a character not rendered.

My suggested fix for this is just to drop that check. If the X position is already in column 0, let it go negative. It should then paint the character exactly as expected, with half of it off screen. At least that seems to work for the GDI engine.

But that brings us to the next problem. When we're dealing with the second half of a DBCS char, the `it->Columns()` value is 1, so we set the `columnCount` to `it->Columns() + 1` to allow for the fact that it's actually going to occupy two cells. However, that `columnCount` variable is also used to increment the iterator, so it ends up incrementing too much, and any subsequent characters will be rendered in the wrong place, or possibly skipped altogether. See below:

https://github.com/microsoft/terminal/blob/26ca73b823cde97cd2425baec62961947a8f85ee/src/renderer/base/renderer.cpp#L797-L799

My suggested fix is to use the `it->Columns()` value itself for the increment, since that should always be correct. So something like this:

```cpp
it += std::max<size_t>(it->Columns(), 1);
```

I'm not sure if we still need to make sure the increment is non-zero, but it probably wouldn't harm.

**Comment by DHowett** [comment]
I believe @miniksa changed something in here recently (after 1836x, as you've observed) that fixed an issue with ConPTY; blame might be enlightening here. :smile:

Otherwise, this looks like the right fix. I hope we have test coverage for the ConPTY thing!

**Comment by j4james** [comment]
@DHowett I think the PR you're thinking of is #4668, but that didn't introduce this bug. It was an attempt to fix a related issue with fullwidth glyphs (#2191), but didn't correctly handle this particular case. I've now created a PR with my proposed changes, and confirmed that the test cases described in #2191 are still working correctly with those changes.

However, I should note that the #2191 issue is no longer reproducible in Terminal even with this whole section commented out (i.e. the fix introduced in #4668). I suspect that might be because the DX engine now always invalidates a full line at a time. I could reproduce the problem with the GDI engine in conhost, though, so could confirm that the fix does still work there.
