### ISSUE TITLE
CAM Overlay shortcut / positioning issues.

### ISSUE THREAD

**Issue by misterHippo** [microsoft/terminal#8394]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.630]
Windows Terminal version (if applicable): Whatever the current live channel pushed out.
```
# Steps to reproduce

Press `Ctrl + O`

# Expected behavior
1) Expected to be able to interact with ssh connection through Terminal without having config window appear.

2) Expected to be able to reliably move CAM Overlay somewhere out of the way without having it stranded in the middle of the terminal window.

3) Expected to be able to disable CAM Overlay via settings somehow.

# Actual behavior

**1)** While using nano / pico on linux server, `Ctrl + O` brings up the CAM interface for MS terminal over the top of the file saving process on the actual ssh connection.

**2)** CAM was positioned top left losing two or three lines of terminal space. I attempted to grab & move as instructed in the CAM Overlay Config, but was only able to interact with CAM Overlay bar because it overlapped the tab section. Once I accidentally dropped in mid-window, I was no longer able to move it. The "move cursor" appears over the top of the CAM Overlay, but the cursor interacts with the terminal contents behind it - not the CAM Overlay.

**3)** Doesn't appear to be much information about this, nor any config section specifically about this.

**Comment by DHowett** [comment]
Thanks for the report. Unfortunately, we have no control over this “CAM” software or any overlay it produces. If we had a configuration element for every random software that might _also_ be running on your system, it would be a complicated mess indeed.

You may need to find this CAM and tell it to clear off.

**Comment by misterHippo** [comment]
Thanks DH. I wasn't aware that this was something else installed on my machine. I will investigate further.

**Comment by DHowett** [comment]
Some graphics card suites detect Terminal as a game and give it the full-on game treatment (fps overlay, GPU memory usage, etc.), which always gives us a good laugh 😁

**Comment by misterHippo** [comment]
Found the culprit. NZXT CAM (PC monitoring, hardware driving/config, cooling, overclocking interface etc). (Edit: So yes! it was one of those things.)

I had been presuming that CAM was a TLA That wasn't familiar with. 

For anyone else that might find this in the future, there is a settings section in which you can change/remove the hotkey.
