### ISSUE TITLE
Make disk file paths clickable (open a folder or a file in its default application)

### ISSUE THREAD

**Issue by BurstX** [microsoft/terminal#8395]
# Description of the new feature/enhancement

It would be very convenient to be able to open a file (in its default associated application) or folder (in Windows Explorer) from the terminal's output by clicking this very file or folder path.

E.g. I've got a script compiling a complex project. Then MSBuild outputs an error in one of the projects. I know what the error is about, but I have to open the file myself via finding the open application (or opening one), finding/opening the file. Instead, I could just click the disk path, it would open the file immediately and I will do the necessary correction.

![image](https://user-images.githubusercontent.com/3790231/100191495-45f3a400-2f01-11eb-9c7a-eeb0592a8f8f.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7562 for more discussion.

/dup #7562

**Comment by Don-Vito** [comment]
@zadjii-msft - just to make sure that the discussion in https://github.com/microsoft/terminal/issues/7562  covers this one: we are not talking about another URI scheme - the idea is to allow clicking on the file path (aka no URI scheme)
