### ISSUE TITLE
ctrl+c hot keys

### ISSUE THREAD

**Issue by EfimenkoAndrew** [microsoft/terminal#8396]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1198]
Windows Terminal version (if applicable): 1.4.3243.0


Any other software? No
```

# Steps to reproduce

1) Open the terminal
2) Open PowerShell tab 
3) Select text
4) Press ctrl+c to copy it
5) Press ctrl+v to pass the copied values

# Expected behavior

The same behaviour as Windows PowerShell or ConEmu 
![image](https://user-images.githubusercontent.com/26180535/100211902-60d01380-2f15-11eb-9802-e4212cc0df13.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/26180535/100212006-81986900-2f15-11eb-9c25-a345ca0d3185.png)
The ctrl+v passes the previously copied value. It is very uncomfortable to use Windows Terminal after PowerShell. Please fix that. I am not sure that CMD behaviour is actually expected one.

**Comment by Don-Vito** [comment]
The default bindings for terminal are:
* copy - ctrl+shift+c / ctrl+insert
* paste - ctrl+shift+v / shift+insert

You can also bind ctrl+c  / ctrl+v at your own risk (as it might be a disabler for some scenarios) by adding the following to keybindings in settings file:

```
        {
            "command" : "copy",
            "keys": "ctrl+c"        
        },
        {
            "command" : "paste",
            "keys": "ctrl+v"        
        }
```

**Comment by Don-Vito** [comment]
@EfimenkoAndrew - btw do you have a fresh installation?

Interestingly, according to https://github.com/microsoft/terminal/issues/5187, the following should appear by default in your settings file:
```
{ "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
{ "command": "paste", "keys": "ctrl+v" }
```

**Comment by DHowett** [comment]
Right: we bound ctrl+c by default only for users who installed after... maybe 0.7? 0.5? So we didn’t mess up everyone who installed before then.
