### ISSUE TITLE
Duplication and deletion of content on window resize. (Only on WSL - Ubuntu)

### ISSUE THREAD

**Issue by umeshmk** [microsoft/terminal#8401]
# Environment

    Windows build number....: 10.0.19042
    Windows Terminal version: 1.4.3243.0
    Bash version............: 5.0.17(1)-release
    WSL.....................: 2
    Ubuntu..................: Ubuntu 20.04.1 LTS

# Steps to reproduce

**Issue 1**

    Open Windows Terminal
    Open Wsl Ubuntu Tab
    Type : echo "Line 1"  (press enter)
    Type : echo "Line 2"  (press enter)
    Type : echo "This is a very loooooooooooooooooooong string."
    Try to resize window horizontally

**Issue 2**

    Open Windows Terminal
    Open Wsl Ubuntu Tab
    Split tab in 2 (vertically)
    Type(on both panes) : echo "Line 1"  (press enter)
    Type(on both panes) : echo "Line 2"  (press enter)
    Type(on both panes) : echo "This is a very looooooooong string."
    Try to resize window horizontally

**Issue 3**

    Open Windows Terminal
    Open Wsl Ubuntu Tab
    Type : echo "Line 1"  (press enter)
    Type : echo "Line 2"  (press enter)
    Type : echo "This is a very long string."
    Try to resize window VERTICALLY till only 1 line is visible.

# Expected behavior

The window should resize without duplication of text on text wrapping.

# Actual behavior

**Issue 1**

    Text keeps duplicating on each line break.
    Text duplication : Both text before `$` & the typed text
    Line duplication : Only the current active line duplicates.
    Line deletion    : Only the line above active line gets deleted each time the active line gets out of line break.
    Persistent       : Duplication is mostly not persistent.

**Issue 2**

    Similar to behavior in issue 1
    Line deletion    : Unpredictable
    Persistent       : Duplication is persistent (but unpredictable).

**Issue 3**

    Similar to behavior in issue 1 (except no line breaks needed)
    Line deletion    : No.
    Persistent       : Duplication is persistent.

# Notes

`Powershell` and `cmd` has no issues.
This issue happens with split panes, powerline too.

**Screenshots - Steps to reproduce**
https://drive.google.com/drive/folders/1slLfsEOPh4QNHZw_9MQKlckJYwHcGOea?usp=sharing

**Comment by DHowett** [comment]
Thanks for the reports! Unfortunately, while I know that this is a really strange thing, it's _by design_. What's happening here is that bash is receiving the "window size changed" event and responding by re-printing the prompt. It forgets where the cursor is, or fails to move it properly, and ends up duplicating text all over the place.

This is what it looks like in gnome-terminal (which isn't running any of our code)

![image](https://user-images.githubusercontent.com/189190/100271149-dafc9a00-2f0d-11eb-9653-838ba1bc4d4d.png)
