### ISSUE TITLE
How to change pane divider color and width?

### ISSUE THREAD

**Issue by sweihub** [microsoft/terminal#8406]
Hi, the pane divider is ugly with dark mode, the divider is too wide and color is inconsistent with the dark theme, I cannot find a way to change it,  anyone can help？ Thanks! 

Windows Terminal Preview Version: 1.5.3242.0

![image](https://user-images.githubusercontent.com/5334841/100302314-08604b00-2fd5-11eb-961a-b59dc4bcb572.png)

**Comment by DHowett** [comment]
Unfortunately, due to a bug the pane divider will always match the system-wide application light/dark mode. More info in /duplicate #3917

Width is tracked in https://github.com/microsoft/terminal/issues/3063
