### ISSUE TITLE
Link SSH

### ISSUE THREAD

**Issue by Jian0326** [microsoft/terminal#8407]
Link SSH.
Use the screen command. After exiting, the current line is displayed to the first line, and should be displayed to the last line

**Comment by DHowett** [comment]
Please include a video or a GIF.

**Comment by Jian0326** [comment]
![screen](https://user-images.githubusercontent.com/11675406/100318615-48d1c000-2ff9-11eb-804d-229cedb46104.gif)

**Comment by Jian0326** [comment]
![screen](https://user-images.githubusercontent.com/11675406/100319454-969af800-2ffa-11eb-8ea8-bf00e94ebd8c.gif)

**Comment by zadjii-msft** [comment]
Thanks for sharing the gif! Based on the gif, I'm gonna say this is a result of the Terminal not truly supporting the alternate screen buffer quite yet. That'll make fixing this a combo of  #381 and  #3492. 

/dup #381 
/dup #3492
