### ISSUE TITLE
Control+A-Z prints character from alternative language

### ISSUE THREAD

**Issue by mmdmine** [microsoft/terminal#8408]
e.g. when I press Ctrl+C, instead of entering `^C` and terminating program, prints `ز` from Persian Keyboard (while language is set to english). when I press C, it prints `C` character.

**Comment by zadjii-msft** [comment]
Well that sure is weird. Few questions:
* What application do you have running in the Terminal? (powershell, cmd, wsl, etc)
* What version of the Terminal are you using? 
* What version of Windows?
* Are you using anything like ssh? If so, which version?
* What keyboard layout are you using, and are you using any IME software?

**Comment by mmdmine** [comment]
> Well that sure is weird. Few questions:
> 
> * What application do you have running in the Terminal? (powershell, cmd, wsl, etc)
> * What version of the Terminal are you using?
> * What version of Windows?
> * Are you using anything like ssh? If so, which version?
> * What keyboard layout are you using, and are you using any IME software?

* I noticed it on Powershell, I'm not sure if it's there on other apps or not
* Latest version from Store
* Build 20H2 19042
* No
* English and Persian Standard

**Comment by zadjii-msft** [comment]
> I noticed it on Powershell, I'm not sure if it's there on other apps or not

Which version of Powershell? Is PSReadline enabled, and if so, which version?

> Latest version from Store

That's actually not that helpful, because there's both the Stable and Preview versions of the Terminal in the Store, and the Store has a tendency to not always roll out updates as timely as we'd like them. Could you be specific?

**Comment by mmdmine** [comment]
> > I noticed it on Powershell, I'm not sure if it's there on other apps or not
> 
> Which version of Powershell? Is PSReadline enabled, and if so, which version?
> 
> > Latest version from Store
> 
> That's actually not that helpful, because there's both the Stable and Preview versions of the Terminal in the Store, and the Store has a tendency to not always roll out updates as timely as we'd like them. Could you be specific?

* Powershell 7, I didn't do anything with PSReadline, it should be enabled, I'm not sure about version, it should be the version that comes with Powershell.
* I'm using stable version

**Comment by DHowett** [comment]
Thanks for the report! Sorry about the delay here.

If you'd like to give us a quick debug trace, would you mind following the "input log" trace steps in [this issue comment](https://github.com/microsoft/terminal/issues/7067#issuecomment-664670923)? Type out a couple <kbd>Ctrl+\\</kbd> sequences and send a screenshot (so we can see which records are red and which are not)

Thanks!

**Comment by mmdmine** [comment]
> Thanks for the report! Sorry about the delay here.
> 
> If you'd like to give us a quick debug trace, would you mind following the "input log" trace steps in [this issue comment](https://github.com/microsoft/terminal/issues/7067#issuecomment-664670923)? Type out a couple Ctrl+\ sequences and send a screenshot (so we can see which records are red and which are not)
> 
> Thanks!

OK, I don't know exactly which condition reproduces this bug, somedays i get a lot of this, somedays i don't get it at all; But i'll send logs as soon as i got it again.

**Comment by mmdmine** [comment]
I guess you have already fixed it, because It's not happening anymore. I'll close it myself.

**Comment by Don-Vito** [comment]
@mmdmine - there was no version release for more than a month, so I guess there is something else in your system that changed.

**Comment by mmdmine** [comment]
> @mmdmine - there was no version release for more than a month, so I guess there is something else in your system that changed.

I removed Powershell 7, because Windows Powershell was enough for me. It could be Powershell's bug.
