### ISSUE TITLE
Background image not shown when "antialiasingMode": "cleartype", "useAcrylic": false

### ISSUE THREAD

**Issue by ks2k2d** [microsoft/terminal#8409]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
```

# Steps to reproduce
"antialiasingMode": "cleartype", "useAcrylic": false, "backgroundImage": "...some_file"

# Expected behavior
Opaque image is shown as background

# Actual behavior
Black background is shown and the image is visible only around the padding.
![image](https://user-images.githubusercontent.com/67361981/100348953-5c2c5d80-2ff0-11eb-8bd5-f131959e339a.png)

**Comment by pinxau1000** [comment]
You need to specify ```backgroundImageOpacity```!

example:
```json
{
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
		"commandline": "wsl -d Ubuntu",
		"tabTitle": "Ubuntu",
		"acrylicOpacity":0.75,
		"closeOnExit":true,
		"colorScheme":"Campbell",
		"fontFace":"Consolas",
		"fontSize":12,
		"historySize":9001,
		"backgroundImage": "<PATH>",
		"backgroundImageStretchMode": "none",
		"backgroundImageOpacity": 0.1,
		"icon":"<PATH>",
		"padding":"0, 0, 0, 0",
		"snapOnInput":true,
		"useAcrylic":true
}
```

![ubuntu_windowsTerminal_2](https://user-images.githubusercontent.com/31994143/100353481-75301100-2fe6-11eb-948a-a5eba9c7f3e5.png)

**Comment by ks2k2d** [comment]
One difference I see between you and my case is that I have specified the configuration in the "defaults" section.

**Comment by ks2k2d** [comment]
It is not caused only by "useAcrylic": false
instead it is caused by the combination of "useAcrylic": false and "antialiasingMode": "cleartype"
I will update the description.

**Comment by pinxau1000** [comment]
Indeed. Background image didn't shows when ```"useAcrylic": false``` and ```"antialiasingMode": "cleartype"```.

**Comment by zadjii-msft** [comment]
Thanks for the report and the investigation! It looks to me like this is the same root cause as #5703, so I'll redirect discussion to that thread. Thanks!

/dup #5703
