### ISSUE TITLE
Allow tabs on the left/right side

### ISSUE THREAD

**Issue by ks2k2d** [microsoft/terminal#8412]
# Description of the new feature/enhancement
Allow tabs to be placed left, right, top or bottom.
With default "top".

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
This probably classifies as a duplicate of #835.

**Comment by ks2k2d** [comment]
This one specifies any of the sides to be configurable.
The #835 is specific only for the bottom side. 
So, #835 is subset of this one. :)

**Comment by zadjii-msft** [comment]
Although I'm _really_ inclined to close this one as a dupe, I'm thinking that the work for "tabs on the side" is different enough from "tabs on the bottom" that we can leave this open.

**Comment by DHowett** [comment]
I'm inclined to merge them. :smile:
