### ISSUE TITLE
az cli cmd shall open default windows browser automatically

### ISSUE THREAD

**Issue by cforce** [microsoft/terminal#8413]
```
 % az login
To sign in, use a web browser to open the page https://microsoft.com/deviceloginchina and enter the code ?? to authenticate.
use a web browser to open the page https://microsoft.com/deviceloginchina


```Is there anyway to let call the windows default browser within wls insteaf of manually to force device login.?

**Comment by skyline75489** [comment]
This isn't really a terminal issue. The azure cli repo is https://github.com/Azure/azure-cli .

By the way if you're using the latest preview version, you should be able to Ctrl+click the URL to open it in default browser.

**Comment by zadjii-msft** [comment]
I'm not sure that there is a way to make a browser within WSL the default browser on Windows. With the COM registrations that would need to happen, I'm pretty confident that it's _not_ possible, unfortunately. I suppose someone could hypothetically create a shim application that would act as a browser on Windows, but really just invoke the WSL browser with the correct arguments, but the place for that discussion probably isn't on this repo 😄 You'll either have to use your default Windows browser, or copy/paste the path into the browser running on WSL, sorry.
