### ISSUE TITLE
Terminal crashes when navigating in empty palette

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#8421]
# Environment

```
Windows Terminal version (if applicable): both 1.4 and 1.5
```

# Steps to reproduce
1. Open command palette
2. Type filter that is not matched by any command
3. Press "UP"
4. Enjoy postmortem debugger

The reason is double bug here
```
void CommandPalette::SelectNextItem(const bool moveDown)
    {
        const auto selected = _filteredActionsView().SelectedIndex();
        const int numItems = ::base::saturated_cast<int>(_filteredActionsView().Items().Size());
       
        const auto newIndex = ((numItems + selected + (moveDown ? 1 : -1)) % numItems);
        _filteredActionsView().SelectedIndex(newIndex);
        _filteredActionsView().ScrollIntoView(_filteredActionsView().SelectedItem());
    }
```

We both do the math when numItems=0, and when we go up starting from selected=-1.

I have a fix here: https://github.com/microsoft/terminal/pull/8420.
But I will probably extract it to a separate PR.

**Comment by zadjii-msft** [comment]
_G U H_

Yep that's an easily repro-able crash alright, thanks for hoping on the fix so quick
