### ISSUE TITLE
[Feature Request] Ability to pin scripts to the pinned Terminal icon on taskbar. 2nd take.

### ISSUE THREAD

**Issue by gamagan** [microsoft/terminal#8423]
# Description of the new feature/enhancement

1.5 years ago, I requested the following feature:
[Feature Request] Ability to pin scripts to the pinned Terminal icon on taskbar.
https://github.com/microsoft/terminal/issues/5261

It was quickly closed, with a comment saying that it was tracked as part of a different task. That other task was closed, and the feature was not actually implemented. All that was done as part of that 'jump-list' task was a shortcut to open the Terminal starting at a different shell. Wack.

Please implement the ability to pin ***SCRIPTS*** to the Terminal icon on the taskbar. This is a very time-saving feature when you have several scripts that you run on a regular basis: you don't have to go looking for these scripts, and you don't have to keep explorer windows open just in case you need to run them. You already have the 'jump-list' feature done, so this shouldn't be that much of a stretch to do.

**Comment by zadjii-msft** [comment]
This is definitely possible now with jumplist support. For example, I'll make the following profile:

```json

            {
                "name": "Run my script",
                "icon": "C:\\Users\\migrie\\dev\\private\\OpenConsole\\res\\terminal.ico",
                "commandline": "cmd.exe /c my_script.bat",
            },
```

And that'll show up in the jumplist as:
![image](https://user-images.githubusercontent.com/18356694/100464173-bb42ae80-3092-11eb-9bad-019e5ac25d15.png)

Is that not what you're looking for?

**Comment by gamagan** [comment]
Is not exactly drag and drop onto the icon to pin, and right-click to unpin, but I suppose it will do.

Thanks

**Comment by zadjii-msft** [comment]
No worries, happy to help!
/dup #5261
