### ISSUE TITLE
After renaming tab with a long string it crashes or a blackscreen occures

### ISSUE THREAD

**Issue by retfloww** [microsoft/terminal#8428]
Windows 10 19042.620
Windows Terminal 1.4.3243.0
Windows Terminal Preview 1.5.3242.0

# Steps to reproduce
Rename the Tab. Paste a long string

# Expected behavior

No crash
No Blackscreen

# Actual behavior

Windows Terminal Preview 1.5.3242.0:
Crash and Blackscreen

Windows Terminal 1.4.3243.0:
Blackscreen

![image](https://user-images.githubusercontent.com/67190487/100484612-fb655980-30b1-11eb-9582-a0c34c085fe8.png)

**Comment by Don-Vito** [comment]
@retfloww - after pasting the long title and getting to this weird screen, please try to hit Esc (alternatively, click outside of the terminal window so the Terminal window will loose focus, and then switch back to Terminal)

For me this fixes the screen in both in 1.4 in 1.5.
Though if you click the same title again, you will get the weird screen again.

What happens behind the scene is that there is a control for renaming, which is rendered incorrectly with long strings, but when it gets collapsed (via Esc or by loosing its focus) the weird UI is hidden.

**Comment by retfloww** [comment]
Yes this actually works, thank you very much. Will this in any future be fixed?

**Comment by Don-Vito** [comment]
@retfloww - I am neither an expert nor from the team, but from what I learned about this community - everything gets solved at some point (unless it is an external dependency) ☺️ 

I will take a look at this later on to see if something catches my eye.

**Comment by Don-Vito** [comment]
@retfloww - BTW, wondering what should be the correct behavior: do we really want to allow such long name, or should we instead truncate it / fail with a message.

**Comment by retfloww** [comment]
I would go for the second idea, I cannot imagine someone using a long tab name, there should be a cap for max. name lenght.

**Comment by zadjii-msft** [comment]
Good job finding a really bizarre bug, and thanks @Don-Vito for hoping on a fix so quick!
