### ISSUE TITLE
Settings.json file won't open

### ISSUE THREAD

**Issue by bitzs-alex** [microsoft/terminal#8429]
I installed and uninstalled the windows terminal three times but still, the settings.json file is not opening. I tried making VSCode as a default editor but nothing happens. I tried installing some text editors from Microsoft Store and made them default apps for .json files, but still no response.

# Environment
```
Windows build number: Version 10.0.19042.630
Windows Terminal version: 1.4.3243.0
```

# Actual behavior
Settings.js file is not opening

**Comment by bitzs-alex** [comment]
I installed Notepad++ and it worked

**Comment by DHowett** [comment]
Seems you've gotten it fixed. Thanks for reporting back!

**Comment by konopka** [comment]
FYI for anyone who will end up here still searching for a solution. In my case I had some random app associated with json file type.
So fix was [Windows 11]:
1. Open Windows settings
2. Go to Apps
3. Go to Default Apps
4. Search for json file type
5. Change your default app to your preferred app that can actually open json file

**Comment by jstafford5380** [comment]
For me, when I went into default apps to see what .json was assigned to, I found 2 different VSCode, so I think the VSCode installer probably lost its mind during some upgrade. I chose the second one and it works now.
