### ISSUE TITLE
Clicking a file path with Ctrl + Click opens the file

### ISSUE THREAD

**Issue by Zerotask** [microsoft/terminal#8431]
# Description of the new feature/enhancement
If the terminal shows a file with it's full path, it would be handy if you could simply click it, like you can do with URLs.

For example, I executed a NPM command within my PowerShell 7.1.0 and it showed me
![image](https://user-images.githubusercontent.com/20150243/100517281-d17f6600-3189-11eb-944f-4e07e1a5b8b7.png)

Then I want to open this file to get further information. Right now, I have to copy this file path and open it with the explorer or with `code <filePath>`.
I'd like to click on it and it opens in my default editor (e.g. Visual Studio Code)

**Comment by Don-Vito** [comment]
@Zerotask - please check if https://github.com/microsoft/terminal/issues/8395 covers all aspects of your idea

**Comment by Zerotask** [comment]
@Don-Vito Yes, thank you.
