### ISSUE TITLE
Emacs(spacemacs) not inheriting shell colors on ubuntu

### ISSUE THREAD

**Issue by yusaira-khan** [microsoft/terminal#8436]
# Environment

```none

Windows build number:  [Version 10.0.19042.630]
Windows Terminal Version: 1.3.2651.0
Ubuntu 20.04 wsl 2
emacs 26.3  (spacemacs environment)

```

# Steps to reproduce
install emacs on ubuntu 20.04 . 
download spacemacs configuration https://github.com/syl20bnr/spacemacs
run emacs

# Expected behavior

emacs should have the same color scheme as the scheme for windows terminal.  this is the behavior i see for  terminal emulation on regular ubuntu.
![color scheme A](https://user-images.githubusercontent.com/5526796/100526820-7ace5800-319a-11eb-8e54-c6355fc62219.PNG)
 

# Actual behavior
spacemacs opens with this color instead (color difference highlighted in red circle).
![emacs different color A](https://user-images.githubusercontent.com/5526796/100526831-a0f3f800-319a-11eb-8de8-1ca1c1f67691.png)

# -- What's actually happening? --
Emacs(spacemacs) not inheriting shell colors on ubuntu/wsl. i'm trying to use solarized theme, but emacs is using a black color theme instead. This behaviour doesn't happen in emacs on terminal emulators i've used on non-wsl ubuntu?

**Comment by DHowett** [comment]
Emacs is specifically requesting a gray background.

**Comment by DHowett** [comment]
You can observe this behavior with `printf "\e[40m"` from your shell. There's a bit of an annoying dichotomy between the paletted colors (of which 0 is typically black) and the non-paletted colors (like the "default background"). An application needs to either explicitly request the "default background" (SGR, 49) _or_ not explicitly request a different background color.

This is observable on other terminal emulators, as well, and gets worse when the "default background" is inaccessible through other SGRs (like, it has transparency or something.)

**Comment by DHowett** [comment]
Unfortunately, at the end of the day we have to (mostly*) respect applications' wishes.

(*) For PowerShell on Windows, we explicitly _reject_ its wishes when it asks for `40` (0, background, "solid black") because otherwise the display will get right mangled :smile:

**Comment by yusaira-khan** [comment]
is there a way to disable this?

**Comment by DHowett** [comment]
Unfortunately, I'm not familiar with emacs' configuration such that I could offer advice there. Sorry!

**Comment by yusaira-khan** [comment]
sorry, i mean is there a way to disable it the way you do it with powershell?

**Comment by DHowett** [comment]
Unfortunately, no. Doing that could break countless other applications since we can't really restrict it to a specific _thing_ running in WSL. Honestly, the best way to fix broken client applications is to unbreak those client applications. When a client app can be configured out of a weird situation, it's infinitely easier than adding detection to Terminal for that app actig up.

The only reason we quirked PowerShell is that _despite us fixing it_, there's two whole versions of Windows that shipped with the broken behavior. Those are way less fixable than one's emacs config file :grin:
