### ISSUE TITLE
Different terminals in split panes within same tab?

### ISSUE THREAD

**Issue by stealthsploit** [microsoft/terminal#8437]
It would be great if you could run different terminals in separate panes within a _single_ tab, i.e. vertical split 2 ways one pane PSH the other pane Ubuntu etc. As far as I can see you can only run the same terminal type in a single tab?

**Comment by DHowett** [comment]
You can definitely do this today. Couple different ways.

![image](https://user-images.githubusercontent.com/189190/100528623-d5b08100-3193-11eb-9afd-81d97c344c94.png)

1. A `splitPane` binding can take the `profile` argument
2. You can hold down alt while launching any profile with the menu
   * ![image](https://user-images.githubusercontent.com/189190/100528641-10b2b480-3194-11eb-82b7-4b250063b37c.png)
3. The command palette (<kbd>ctrl+shift+p</kbd> by default)
   * ![image](https://user-images.githubusercontent.com/189190/100528647-1f996700-3194-11eb-842b-9f746e317b2f.png)
   * ![image](https://user-images.githubusercontent.com/189190/100528664-258f4800-3194-11eb-98df-0473a1ce84b3.png)

**Comment by stealthsploit** [comment]
Thanks for this, couldn't find anything when initially looking. Cheers!
