### ISSUE TITLE
Add Stories to Windows Terminal 

### ISSUE THREAD

**Issue by filmgirl** [microsoft/terminal#8441]
# Add a “Stories” Feature to Windows Terminal
Stories are the new hotness. Snapchat invented Stories but the paradigm of ephemeral updates has since been adopted by Instagram, WhatsApp, Facebook, LinkedIn, Twitter, and most recently, Spotify. There is even a VS Code extension that adds this feature. 

Why should LinkedIn get all the fun?! Windows Terminal might be a singular experience (but with user profiles, is it really), but that doesn’t mean we shouldn’t create an ephemeral social layer into it. 

Windows Terminal “Stories” could be in gist form (a la GitHub) or scripts in your favorite shell language (PWSH or BASH or ZSH, in da clurb we all fam), they could also be print screens of your current terminal session. Because who doesn’t want to show off their latest Neofetch/winfetch ASCII art! 

As a longterm goal, there could even be a way to share a gist/link to your config file to share your specific terminal preferences and font/color information. 

# Proposed technical implementation details (optional)
In order to see Stories from others (assuming we don’t want to focus just on local users), we would need to run some sort of web server that ties into some type of social network for followers/displays. GitHub would probably be ideal for that. 

Having said all this, as good of a feature as I believe Stories would be, it would probably require a lot of resources and overhead, not to mention possible performance concerns. Perhaps this is a better request for Hyper, since it is Electron and basically running a web browser anyway. (No shade to Hyper — Hyper is great and beautiful and I’m just teasing out of love!)

In fact, the more I write about this. Maybe it’s a bad idea.

**Comment by estruyf** [comment]
You got my support on this @filmgirl. +1

**Comment by LuiseFreese** [comment]
rooting for you @filmgirl 🎉

**Comment by girlgerms** [comment]
11/10, want to see this happen! 💜

**Comment by pandom** [comment]
Knowing that this is possible my life will not be the same without it

**Comment by GossiTheDog** [comment]
We need this.

**Comment by alannt777** [comment]
I thought the Terminal was for productivity. Am I wrong?

**Comment by Lazza** [comment]
I guess probably something could be hacked together with Cowsay and Fortune. This would get closer to feature parity with a real Linux machine. 😏

**Comment by mvandemar** [comment]
I can't believe it hasn't already been implemented, this is a must have feature.

**Comment by okms** [comment]
This needs a kickstarter campaign

**Comment by alannt777** [comment]
Can this be integrated with #469?

**Comment by leo60228** [comment]
> most recently, Twitter

I think Spotify was more recent

**Comment by filmgirl** [comment]
> > most recently, Twitter
> 
> I think Spotify was more recent

Right you are!

**Comment by alannt777** [comment]
I haven't seen any feature request in this repo having this much reactions (and upvotes) in such short amount of time. 🤯

**Comment by snickler** [comment]
This has my full support \o/

**Comment by kylesethgray** [comment]
I would love to see this happen.

**Comment by giggio** [comment]
How have I been using Terminal without this feature for so long? I'm using plain old terminal until we have it!

**Comment by Don-Vito** [comment]
Wondering if Terminal users are mentally prepared to such amount of social activity in their lives.. switching from 0 social life to this directly might be... overwhelming 😄

**Comment by alannt777** [comment]
> Wondering if Terminal users are mentally prepared to such amount of social activity in their lives.. switching from 0 social life to this directly might be... overwhelming 😄

@Don-Vito Are you talking about me? 😄

**Comment by Don-Vito** [comment]
> 
> 
> > Wondering if Terminal users are mentally prepared to such amount of social activity in their lives.. switching from 0 social life to this directly might be... overwhelming 😄
> 
> @Don-Vito Are you talking about me? 😄

About myself actually 😄

**Comment by suadev** [comment]
Doesn't it look cool?   https://twitter.com/kose__suat/status/1329514405818732545

**Comment by zadjii-msft** [comment]
Well this thread was a good hilarious read to start my week. Thanks for that 🤣 

I know that this is [90% a meme post from twitter](https://twitter.com/cinnamon_msft/status/1333341760848740352), but this is also our actual work tracker, so I've gotta be at least 5% serious here:

I don't believe the Terminal is the place to implement most of this. 
* We've already got a commandline ecosystem problem of users just executing random scripts that they download with `curl` - if we're letting users install scripts that they saw on someone's story, then i can guarantee you there'll be scripts like "Run Graphical Applications in WSL!!!" that actually just `rm -rf /mnt/c`. I don't want to be held responsible for contributing to that problem.
* I think GitHub gists are already better suited for a lot of this - they've already got syntax highlighting for different languages, they've already got accounts set up, and authentication, and hey, they've already got a web-scale website that can host all this, and frankly I'm not prepared, nor is anyone on the team, to build that ourselves.
* We've also already got #469 on the backlog for recording Terminal output to the asciinema format, for sharing on https://asciinema.org. Again, that's another site that's probably better suited for hosting recordings of terminal sessions, rather than us standing this up on our own. 

So those are reasons why _I_ would reject this feature request. However, this thread is definitely @cinnamon-msft's responsibility, so I'll let them handle it.

<hr>

As far as the following is concerned:
>  there could even be a way to share a gist/link to your config file to share your specific terminal preferences and font/color information.

I believe there's been discussion about that in the past, and that I'm on board with. "Stories", not so much.

**Comment by bnb** [comment]
+1 this is a vital feature. pls ship @cinnamon-msft 🙏🏻

**Comment by cinnamon-msft** [comment]
This definitely was a fun read, but I agree with @zadjii-msft that this doesn't really make sense for Terminal. Kudos to @filmgirl for writing such an entertaining feature request, however I will have to close this issue since we aren't planning to implement it. 😄

**Comment by Don-Vito** [comment]
On the other hand a native support for twitter could prevent us from missing the meme post:
![image](https://user-images.githubusercontent.com/4639110/100654756-f8d55f00-3352-11eb-98e6-ddc9a8cedce3.png)

![image](https://user-images.githubusercontent.com/4639110/100654937-3f2abe00-3353-11eb-8671-8ac3a09f75b0.png)

**Comment by trylaarsdam** [comment]
Command + Story = Cory?

**Comment by Darth4212** [comment]
No. Just no. This isn't social media this is for code

**Comment by Spriithy** [comment]
@Darth4212 but is it really ?

**Comment by Supesu** [comment]
@Darth4212 You use the terminal for coding?

**Comment by Finermeerkat137** [comment]
@Supesu Terminal? Coding? You must be insane, that is impossible!

**Comment by Don-Vito** [comment]
> 
> 
> @Supesu Terminal? Coding? You must be insane, that is impossible! The terminal exists only for `cmatrix`

@Finermeerkat137 - you should try it. I recently switched to Terminal from VS 2019 and am really happy since then: same level of code completion and refactoring with almost twice less memory!

**Comment by tkore** [comment]
![200 (1)](https://user-images.githubusercontent.com/4380333/100679379-3ff82b80-3324-11eb-8895-a9ec1f075fc6.gif)

**Comment by thenexus00** [comment]
Could you maybe engage who ever is doing the visual studio code stories: https://marketplace.visualstudio.com/items?itemName=bar9.stories

Having something that is uniform across Microsoft development platforms will have a far better chance of being more than just a gimmick and have a solid base to grow.

**Comment by shanselman** [comment]
:shipit:

**Comment by GossiTheDog** [comment]
Btw can we call this Stories for Terminal E5 X?

**Comment by alannt777** [comment]
I think someone could implement this as an extension

**Comment by Midi-In** [comment]
I seriously hope this is just a joke post

**Comment by TheThunderGuyS** [comment]
@Supesu ~~I use Terminal to access Vim on WSL as my main editor~~

**Comment by rubyFeedback** [comment]
It's a fun-take and I wanted to upvote it for the fun part, but then I thought it may send the wrong message so I had to downvote it, just to not confuse newcomers. ;)

Many people want super-simple stories - the terminal story. They want a terminal, that's the story! But if people want pink ribbon hipster dancing marquee tags in the terminal, well, the terminal can always be as customizable as possible. Perhaps make the themes epic as much as possible. But for me personally? Simplicity. (It's ok to have more options). And the simplest story is to keep it so simple that stories are not necessary. USING the terminal is already the best story. ;)

(Admittedly I am actually more likely to use e. g. KDE Konsole + WSL on windows these days than windows Terminal BUT this is not always possible, and in these cases, then, Windows Terminal is so much nicer than oldschool cmd.exe ...)

**Comment by rubyFeedback** [comment]
It's a fun-take and I wanted to upvote it for the fun part, but then I thought it may send the wrong message so I had to downvote it, just to not confuse newcomers. ;)

Many people want super-simple stories - the terminal story. They want a terminal, that's the story! But if people want pink ribbon hipster dancing marquee tags in the terminal, well, the terminal can always be as customizable as possible. Perhaps make the themes epic as much as possible. But for me personally? Simplicity. (It's ok to have more options). And the simplest story is to keep it so simple that stories are not necessary. USING the terminal is already the best story. ;)

(Admittedly I am actually more likely to use e. g. KDE Konsole + WSL on windows these days than windows Terminal BUT this is not always possible, and in these cases, then, Windows Terminal is so much nicer than oldschool cmd.exe ...)

**Comment by mvandemar** [comment]
> Could you maybe engage who ever is doing the visual studio code stories: https://marketplace.visualstudio.com/items?itemName=bar9.stories
> 
> Having something that is uniform across Microsoft development platforms will have a far better chance of being more than just a gimmick and have a solid base to grow.

@thenexus00 I thought you were kidding, but 11,819 installs...

**Comment by RUSshy** [comment]
This explains a lot and why microsoft made ton of bad decisions recently, maybe the people at the top are delusional?

now question, how she got the job?

**Comment by ntoskernel** [comment]
![image](https://user-images.githubusercontent.com/11661706/100717393-062e3000-33cb-11eb-84dc-3c1703899cd7.png)

**Comment by alannt777** [comment]
Even the Windows Kernel says NO!

**Comment by TameemS** [comment]
no

**Comment by NSG650** [comment]
no thanks

**Comment by zCri** [comment]
nsg 650

**Comment by emwno** [comment]
+1

**Comment by nitelite** [comment]
Please don't fill the issue tracker with jokes.

**Comment by alannt777** [comment]
@zadjii-msft or @DHowett Please lock this thread

**Comment by zadjii-msft** [comment]
Alright yea, I thought we could all play along and enjoy a nice, lighthearted joke thread, but I guess I was wrong. I'm not gonna take lightly to comments disparaging any of our colleagues. Perhaps having a sense of humor is a desirable trait in an employee, something some participants in this thread are clearly lacking. 

Obviously, we're not adding Stories to the Terminal. Anyone can _read the thread_ and figure that out, if that's not asking too much.

**Comment by DHowett** [comment]
> This explains a lot and why microsoft made ton of bad decisions recently, maybe the people at the top are delusional?
> 
> now question, how she got the job?

get out of here with your misogynist shit, @russhy
