### ISSUE TITLE
Support configuring a profile to run as Administrator / Elevated Permissions

### ISSUE THREAD

**Issue by Jaans** [microsoft/terminal#8442]
# Description of the new feature/enhancement
As a Full Stack Developer using Visual Studio 2019, Service Fabric, NodeJS, and VS Code I have multiple profiles configured for various PowerShell command line scenarios. Some of these require elevated / administrative permissions in order to function correctly.

I would like to be able to have some profiles **always** run with elevated / administrative permissions. 
Alternatively, a less ideal solution is for the entire Windows Terminal application to support configuration to start with administrative permissions. 

# Proposed technical implementation details (optional)
Ideal would be to configure - at profile level - that it must elevate.  E.g. an additional property in the profile.

If it is only viable to start the entire Windows Terminal application with elevated permissions, then there seems behaviours coming from Windows Store Apps that prevent the traditional method of ensuring an application always starts with elevated prompt.

Normally applications can be configured to automatically elevate at start-up by configuring it with either a shortcut and the relevant shortcut settings, or my using my preferred method which is via Compatibility Settings.

However, it seems that applications delivered as Windows Store Apps do not offer the same capability or shortcut. You can manually right-click and "Run as Administrator", but not set it as a default start up.

**Comment by alannt777** [comment]
You can't mix elevated and non-elevated tabs and BTW, this is also a dup of #632.

**Comment by zadjii-msft** [comment]
Yep, this is a pretty specific /dup of #632. We're also tracking a bunch of related work in #5000, and this is also something that [I'm writing the spec for currently](https://github.com/microsoft/terminal/blob/dev/migrie/s/1032-elevation-qol/doc/specs/%235000%20-%20Process%20Model%202.0/%231032%20-%20Elevation%20Quality%20of%20Life%20Improvements.md).

Thanks!

**Comment by alannt777** [comment]
> Elevation Quality of Life Improvements

Nice title :smile:
