### ISSUE TITLE
cannot copy any print in powershell

### ISSUE THREAD

**Issue by harpdogg** [microsoft/terminal#8444]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Gonna need a lot more info than that. How are you copying? What's happening?

**Comment by DHowett** [comment]
What version of Terminal?
What version of Windows?

You can't leave the template blank and expect help.

**Comment by harpdogg** [comment]
I am very disappointed that I cannot copy any text off of PowerShell, especially links. Although I am a novice/student, I do find this irritating and not as efficient as I had hoped.

**Comment by DHowett** [comment]
You can copy by selecting text and clicking the right mouse button or pressing <kbd>Ctrl+C</kbd>. Please detail what you are doing so we can help you.

**Comment by harpdogg** [comment]
I am using the newest Windows Terminal that I downloaded yesterday. If I highlight the text and right click the mouse the highlight disappears.

**Comment by DHowett** [comment]
Yes, and then you can paste that text anywhere you want -- notepad, Edge, etc. It is on your clipboard, because you have copied it.

**Comment by DHowett** [comment]
I shall assume that your issue was solved. :smile:
