### ISSUE TITLE
running "wt.exe" as administrator or with runas/sudo returns no permission error (user context is a normal user)

### ISSUE THREAD

**Issue by Venipa** [microsoft/terminal#8447]
# Environment

```none

Platform ServicePack Version      VersionString                    
-------- ----------- -------      -------------                    
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0


Windows Terminal version (if applicable):
Windows Terminal Preview
Version: 1.5.3242.0 (also latest stable)
Any other software?
> chocolatey - sudo (just like runas but easier)
```

# Steps to reproduce

- go to %userprofile%\AppData\Local\Microsoft\WindowsApps
- run wt.exe as administrator from explorer or with runas command
- error shown

Gif:
![reproductionGif](https://i.mavis.moe/f/nKoLFaUtXY/2020-11-30-23-28-05mp4gif.gif)

# Expected behavior

run without error message

# Actual behavior

errors out a message: "The system is unable to access the file"
![image](https://user-images.githubusercontent.com/17952364/100674824-1b24a800-3366-11eb-828c-b33dd0dfa9a9.png)

**Comment by zadjii-msft** [comment]
This kinda sounds to me like a bug report that should be filed on `sudo`, not the Terminal, right? Like, this bug would theoretically reproduce for other "app execution aliases" as well, right? All the other exes in that path are app execution aliases, so can you launch any of those with `sudo`? (`python.exe` might be a good example, if you have that installed)

**Comment by Venipa** [comment]
> This kinda sounds to me like a bug report that should be filed on `sudo`, not the Terminal, right? Like, this bug would theoretically reproduce for other "app execution aliases" as well, right? All the other exes in that path are app execution aliases, so can you launch any of those with `sudo`? (`python.exe` might be a good example, if you have that installed)

i've also tried running via runas or explorers right click > run as administrator, python works fine but wt.exe always returns the error mentioned above.

![](https://i.mavis.moe/f/tfWW7xe52W/2020-12-01-14-18-58gif.gif)

**Comment by zadjii-msft** [comment]
That's bizarre - @DHowett help me figure this one out?

**Comment by Venipa** [comment]
after upgrading to Windows 10 20h2 (19042.662) this issue dissappeared
@zadjii-msft

**Comment by zadjii-msft** [comment]
Thanks for following up. That is super weird. I'm glad it went away! Hopefully your discovery will be helpful for future people who hit this.
