### ISSUE TITLE
error on remote spacemacs via ssh

### ISSUE THREAD

**Issue by TicktW** [microsoft/terminal#845]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18362.113

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
ssh host@ip
emacs -nw (the spacemacs version)
enter insert mode by typing 'i', then type **ESC**, it  doesn't work

* What's wrong / what should be happening instead:
when type ESC the spacemacs should enter the normal mode, but show **"ESC <escape> is undefined"**, it works well in xshell or mobaxterm.

**Comment by zadjii-msft** [comment]
Are you using WSL's ssh or OpenSSH's ssh.exe?

**Comment by TicktW** [comment]
No, I use the the native windows OpenSSH's ssh.exe

**Comment by zadjii-msft** [comment]
I'm almost certain that's the problem then. Their keyhandling is notoriously wonky. I'd test with WSL's ssh to see if that works. If WSL's ssh _does_ work, then I'd follow up with the OpenSSH team at [powershell/Win32-OpenSSH](https://github.com/powershell/Win32-OpenSSH/issues)
