### ISSUE TITLE
Windows Terminal stops accepting capital Latin letters when I type or paste them in command line, after some time being used

### ISSUE THREAD

**Issue by BurstX** [microsoft/terminal#8450]
# Environment

```none
Windows build number:
Platform      : Win32NT
ServicePack   :
Version       : 10.0.18362.0
VersionString : Microsoft Windows NT 10.0.18362.0

Windows Terminal version:
1.4.3243.0

Any other software?
OMG, it's a dev environment: MSSQL, Visual Studio 2019. VSCode, text editors like Notepad++, Notepad-2-mod,
PDF viewers, TotalCommander, Azure Data Studio, MS Office, Firefox, Google chrome, Edge browser (latest), IIS,
Git for Windows, Greenshot ... and God knows what else.
```

# Steps to reproduce

1. Run Windows Terminal as administrator. You've got the only __tab__ with the only __pane__ in it (Powershell as default environment.)
1. Open second __pane__ with vertical split in the same __tab__. (Powershell)
1. Open second __tab__ (PowerShell). Open second __pane__ (Powershell) with vertical split in this second newly opened __tab__.
1. Here comes the fuzzy part, because the terminal stays in this configuration (2 tabs with 2 panes in each). for quite some time (a couple of days) while I'm working in the terminals: run PowerShell scripts, execute commandlets, run .exe files, etc. I'm not sure what I'm doing in particular that can be the cause.

# Expected behavior
At all times, Latin capital letters are typed in the terminal flawlessly. If I paste (from clipboard) a string with Latin capital letters into the command line, the string is pasted as is.

# Actual behavior

**After a couple of days** of being used, this is what happens in the terminal (PowerShell):
- When I type a capital Latin letter (English US keyboard), it is not typed in the terminal command line
- When I paste a string containing Latin capital letters, the string is pasted without Latin capital letters as if they are filtered out explicitly. E.g. I copy a string "bugfix/**KK**-12345" to the clipboard and then paste it to the terminal's command line. The pasted string is "bugfix/-12345", without "AC".
Note: If I open a new tab (Powershell) (keeping the problematic tabs open) in the same Windows Terminal instance, there is no issue with capital letters in the new tab. (But maybe it will misbehave again after a couple of days of usage.)

**Comment by zadjii-msft** [comment]
Okay, so this is bizarre. We've seen this intermittently once before, over in #7087. From that thread:https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this [PowerShell/PowerShell#10794](https://github.com/PowerShell/PowerShell/issues/10794) and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

@BurstX Could you try that, and see if that resolves the issue?

**Comment by AmRo045** [comment]
I have the same issue and I attached a video for better demonstration of the issue:
https://www.dropbox.com/s/78zkkvgv4kqpjcs/WindowsTerminalCapitalLettersIssue.mp4?dl=0
Windows Terminal version: **1.6.10571.0**

**Comment by BurstX** [comment]
> I have the same issue and I attached a video for better demonstration of the issue:
> https://www.dropbox.com/s/78zkkvgv4kqpjcs/WindowsTerminalCapitalLettersIssue.mp4?dl=0
> Windows Terminal version: **1.6.10571.0**

In my case, an update to the latest version of PSReadLine helped (see comment above). No issues since the update.

**Comment by AmRo045** [comment]
@BurstX The problem solved after installing PSReadLine module.
