### ISSUE TITLE
unicode not showing correctly

### ISSUE THREAD

**Issue by 0xd114** [microsoft/terminal#8451]
when writing this, I realized this maybe a powershell bug, but I'm not so sure.

# Environment

```
shell: powershell
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.4.3243.0
```

# Steps to reproduce
pasting unicode character that needs more than 1 bytes, such as 𢊩

# Expected behavior
showing 𢊩

# Actual behavior
�

**Comment by alannt777** [comment]
Does it work in WSL?

**Comment by zadjii-msft** [comment]
Does this repro in a vintage console window running powershell? Which version of powershell? Are you using PsReadline, and if so, which version?

**Comment by 0xd114** [comment]
yep it's reproducible in powershell 6.2.1 as well (although the character shown was 2 boxes), I don't use PsReadline

I'm using vagrant and ubuntu 20.04 it happens inside the shell as well (again showing 2 boxes).

**Comment by DHowett** [comment]
It looks like this is a powershell bug -- please visit [the psreadline issue tracker](https://github.com/PowerShell/PSReadLine/issues). I think they already have one or two bugs for this... 

This one looks very similar, but with Emoji. /dup https://github.com/PowerShell/PSReadLine/issues/1329
