### ISSUE TITLE
Colorscheme for the terminal previewed in the dev blogpost

### ISSUE THREAD

**Issue by karanjitsingh** [microsoft/terminal#846]
Where can I get the colorscheme (preferably the profiles.json itself) from the terminal previewed in 
https://devblogs.microsoft.com/commandline/introducing-windows-terminal/

![image](https://user-images.githubusercontent.com/4632805/57843077-47f88500-77eb-11e9-8b84-48c6b2b52875.png)

**Comment by Larsklopstra** [comment]
But, this is the default theme?

**Comment by karanjitsingh** [comment]
@Larsklopstra, not for me see https://github.com/microsoft/terminal/issues/727. I had to click on settings and edit to customize

**Comment by Larsklopstra** [comment]
@karanjitsingh Ah.. Maybe it's because they're using a new version of PowerShell? My terminal looks almost the same as the one in the picture but with less blur/transparency, I'm using CMD.

**Comment by mdtauk** [comment]
The image at the top is CMD/Command Line - the one in the lower image is Powershell

**Comment by zadjii-msft** [comment]
If I had to guess, that's @bitcrazed's profile.

You'll probably want to bump down the `"acrylicOpacity"` setting - maybe something like `.25`? The colorscheme otherwise is probably set to `"Campbell"`, and there's no `background` key in his profile.
