### ISSUE TITLE
Cannot remap Ctrl+Shift+F Key binding

### ISSUE THREAD

**Issue by abhijeetviswam** [microsoft/terminal#8460]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630]
Windows Terminal version (if applicable): Version: 1.5.3242.0

Any other software? No
```

# Steps to reproduce

1. Open settings.json
2. Remap "find" key binding to from the default "ctrl+shift+f" to "" or any other key binding e.g. "ctrl+f"
3. Open terminal window and press ctrl+shift+f

# Expected behavior

If a key binding entry is modified in settings.json, only the new key binding should be functional

# Actual behavior

Both old key binding and new key binding works (Specific to "find" command. Working as expected in other commands)

**Comment by zadjii-msft** [comment]
Ah, yes, this one is a bit confusing. The <kbd>ctrl+shift+f</kbd> keybinding is actually also defined in `defaults.json`:

https://github.com/microsoft/terminal/blob/f8edcf57bd1902617525d814453395fff443e45c/src/cascadia/TerminalSettingsModel/defaults.json#L287

So if you really want to remove that keymapping, you'll need to also re-bind <kbd>ctrl+shift+f</kbd> to `unbound`, like so:

```json
{ "command": "unbound", "keys": "ctrl+shift+f" }, 
```
