### ISSUE TITLE
[Functional-Open dropdown]- User is not able to perform action using shortcuts defined for the dropdown menu items.

### ISSUE THREAD

**Issue by Chandresh1007** [microsoft/terminal#8462]
**User Experience:**
Users who rely on screen reader/Keyboard will not be able to perform action efficiently if shortcuts are not working for the dropdown menu items.

**Test Environment:**
OS: Win 10 2004 Build (20262.1010)
App: Windows Terminal 
App version: 1.4.3243.0

**Repro Steps:**
1. Open Windows terminal app
2. Press "Ctrl+shift+Space" key to open the dropdown control.
3. Navigate to the Menu items.
4. Now press shortcut key defined for menu item say "Ctrl+," (which is defined for settings menu item).
5. Observe the issue.

**Actual Result:**
User is not able to perform action using shortcuts defined for the dropdown menu items.
Pressing shortcut key defined for menu items, nothing is getting activated.

**Expected Result:**
User should be able to perform action using shortcuts defined for the dropdown menu items.
Pressing shortcut key "Ctrl+," settings should get open.

[Functional_dropdown_menu keys not working.zip](https://github.com/microsoft/terminal/files/5629395/Functional_dropdown_menu.keys.not.working.zip)

**Comment by zadjii-msft** [comment]
Yep, that makes sense. This is a variant of #6679, but with the new tab dropdown, instead of the command palette.

**Comment by Hegunumo** [comment]
I'm on this!

**Comment by KalleOlaviNiemitalo** [comment]
Do users really expect keyboard shortcuts to work while a menu is open? Compare to Notepad in U.S. English:

1. Start Notepad.
2. Press Ctrl+Shift+S. The "Save As" dialog box opens.
3. Press Esc. The "Save As" dialog box closes.
4. Press Alt+F. The "File" menu opens.
5. Press the Down arrow key four times. The "Save As… Ctrl+Shift+S" menu item becomes highlighted and the menu remains open.
6. Press Ctrl+Shift+S. The "Save As" dialog box does not open. Instead, there is a sound, and the menu remains open.

**Comment by v-akkak** [comment]
> Do users really expect keyboard shortcuts to work while a menu is open? Compare to Notepad in U.S. English:
> 
> 1. Start Notepad.
> 2. Press Ctrl+Shift+S. The "Save As" dialog box opens.
> 3. Press Esc. The "Save As" dialog box closes.
> 4. Press Alt+F. The "File" menu opens.
> 5. Press the Down arrow key four times. The "Save As… Ctrl+Shift+S" menu item becomes highlighted and the menu remains open.
> 6. Press Ctrl+Shift+S. The "Save As" dialog box does not open. Instead, there is a sound, and the menu remains open.

@KalleOlaviNiemitalo 
I completely  agree with your point.
If we are inside the menu and we'll use the shortcut key, it won't work.
@Chandresh1007 
If the behaviour is just like @KalleOlaviNiemitalo then it is not an issue.
Else, please describe.

**Comment by Chandresh1007** [comment]
As the shortcut keys are working when the menu is closed. Hence, closing this bug.
