### ISSUE TITLE
support setting title bar color by title bar content

### ISSUE THREAD

**Issue by uishon** [microsoft/terminal#8465]
When running a WSL session or `ssh`-ing to some remote machine - terminal tab title is changed accordingly (shows `user@host: <folder-name>`). Would be nice if it'd be possible to define the title bar color (and, possibly, also icon) as a function of some regex expression over the title text (instead of having to define a profile per such case).

**Comment by Don-Vito** [comment]
@uishon - please review if https://github.com/microsoft/terminal/issues/7906 covers all aspects of your idea.

**Comment by uishon** [comment]
Missed it... It does, more-or-less. The only thing that's missing there is the option to extend this to something a bit more generic - supporting not just the tab color but, also, additional profile attributes (e.g., title icon, terminal background, etc.). I'll add it as a comment there and close this one.

**Comment by zadjii-msft** [comment]
Thanks for the help triaging @Don-Vito, and thanks for following up!
