### ISSUE TITLE
Background color is not reset correctly after using tig

### ISSUE THREAD

**Issue by grawity** [microsoft/terminal#8467]
# Environment

```none
Windows build number: 10.0.19042.630
Windows Terminal version (if applicable): 1.4.3243.0 and 1.5.3242.0

Any other software?
  - https://github.com/jonas/tig
```

# Steps to reproduce

1. Connect to a Linux server using `ssh`. (I'm using OpenSSH_for_Windows_8.1p1 so that I would have mouse support.)
2. While in a Git repository, run `tig`.
3. **Resize** the terminal window while tig is running.
4. Exit tig and run something like `ls -la`.

# Expected behavior

Output should have black background as it did before.

(The problem does not occur in other terminal emulators.)

# Actual behavior

For all lines which have no formatting codes, the empty space following the text has blue background instead of the normal black background. This persists even after disconnecting SSH and returning to local PowerShell.

![image](https://user-images.githubusercontent.com/31021/100913526-914a1b80-34da-11eb-9960-c1fa4907957d.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #3848 for more discussion.

/dup #3848
