### ISSUE TITLE
If I create a file named config on ~/.ssh, SSH will fail

### ISSUE THREAD

**Issue by vagrant2046** [microsoft/terminal#8470]
# Environment
Windows build number:
Platform      : windows10 Home
ServicePack   : 1909
Version       : 18363.1198

Windows Terminal version:
Windows Terminal Preview
1.4.2652.0

Steps to reproduce
1. Run Windows Terminal as administrator. 
2. cd ~/.ssh
3. touch config
4. ssh root@127.0.0.1 (SSH to any server)
Next, an error will be reported
"Bad owner or permissions on C:\\Users\\xxx/.ssh/config"

**Comment by skyline75489** [comment]
This isn't really a terminal issue. The error is very clear: the permission of the `config` file is too broad. Please only open issues about the terminal *itself*, instead of whatever running inside it.

**Comment by vagrant2046** [comment]
> This isn't really a terminal issue. The error is very clear: the permission of the `config` file is too broad. Please only open issues about the terminal _itself_, instead of whatever running inside it.

What permissions should I set? Because I've tried a lot of permission schemes, and they haven't been successful

**Comment by skyline75489** [comment]
Honestly I do not know. Be it on Linux, the correct permission should be `600`. But on Windows with openssh-win32, I have no idea what it should be. Personally I've never have a problem with just a simple config file created by myself.

You can leave this open for the core devs of this project to decide whether the terminal is the one to blame.

**Comment by vagrant2046** [comment]
if your computer name is the same as your username and you still haven't fixed this issue with permissions dialog, then probably renaming your computer could help.
