### ISSUE TITLE
Settings parsing error. 

### ISSUE THREAD

**Issue by dmytrobaranovskyi** [microsoft/terminal#8472]
After updating to the latest version all the settings are failed to parse.  

Some setting.json works in Preview

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Our settings validation is usually pretty specific about the error it detected. Could you share the exact error message you're getting, and your `settings.json`?

**Comment by dmytrobaranovskyi** [comment]
i've just copy-pasted this one. 
Works in 1.5.3242.0  Preview. 

Crashes in the latest release. 


{
  "$schema": "https://aka.ms/terminal-profiles-schema",

  "alwaysShowTabs": true,
  "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
  "initialCols": 120,
  "initialRows": 30,
  "keybindings": [
    {
      "command": "closeTab",
      "keys": [
        "ctrl+w"
      ]
    },
    {
      "command": "newTab",
      "keys": [
        "ctrl+t"
      ]
    },
    {
      "command": "copy",
      "keys": [
        "ctrl+c"
      ]
    },
    {
      "command": "paste",
      "keys": [
        "ctrl+v"
      ]
    },
    {
      "command": "newTabProfile2",
      "keys": [
        "ctrl+shift+3"
      ]
    },
    {
      "command": "newTabProfile3",
      "keys": [
        "ctrl+shift+4"
      ]
    },
    {
      "command": "newTabProfile4",
      "keys": [
        "ctrl+shift+5"
      ]
    },
    {
      "command": "newTabProfile5",
      "keys": [
        "ctrl+shift+6"
      ]
    },
    {
      "command": "newTabProfile6",
      "keys": [
        "ctrl+shift+7"
      ]
    },
    {
      "command": "newTabProfile7",
      "keys": [
        "ctrl+shift+8"
      ]
    },
    {
      "command": "newTabProfile8",
      "keys": [
        "ctrl+shift+9"
      ]
    },
    {
      "command": "nextTab",
      "keys": [
        "ctrl+tab"
      ]
    },
    {
      "command": "openSettings",
      "keys": [
        "ctrl+,"
      ]
    },
    {
      "command": "prevTab",
      "keys": [
        "ctrl+shift+tab"
      ]
    },
    {
      "command": "scrollDown",
      "keys": [
        "ctrl+shift+down"
      ]
    },
    {
      "command": "scrollDownPage",
      "keys": [
        "ctrl+shift+pgdn"
      ]
    },
    {
      "command": "scrollUp",
      "keys": [
        "ctrl+shift+up"
      ]
    },
    {
      "command": "scrollUpPage",
      "keys": [
        "ctrl+shift+pgup"
      ]
    },
    {
      "command": "switchToTab0",
      "keys": [
        "alt+1"
      ]
    },
    {
      "command": "switchToTab1",
      "keys": [
        "alt+2"
      ]
    },
    {
      "command": "switchToTab2",
      "keys": [
        "alt+3"
      ]
    },
    {
      "command": "switchToTab3",
      "keys": [
        "alt+4"
      ]
    },
    {
      "command": "switchToTab4",
      "keys": [
        "alt+5"
      ]
    },
    {
      "command": "switchToTab5",
      "keys": [
        "alt+6"
      ]
    },
    {
      "command": "switchToTab6",
      "keys": [
        "alt+7"
      ]
    },
    {
      "command": "switchToTab7",
      "keys": [
        "alt+8"
      ]
    },
    {
      "command": "switchToTab8",
      "keys": [
        "alt+9"
      ]
    }
  ],
  "Theme": "system",
  "showTabsInTitlebar": true,
  "showTerminalTitleInTitlebar": true,
  "profiles": [
    {
      "acrylicOpacity": 0.75,
      "background": "#012411",
      "closeOnExit": true,
      "colorScheme": "One Half Dark",
      "commandline": "powershell.exe",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Consolas",
      "fontSize": 10,
      "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
      "name": "Windows PowerShell",
      "padding": "0, 0, 0, 0",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    },
    {
      "acrylicOpacity": 0.85,
      "closeOnExit": true,
      "colorScheme": "One Half Dark",
      "commandline": "cmd.exe",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Consolas",
      "fontSize": 10,
      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
      "name": "cmd",
      "padding": "0, 0, 0, 0",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": true
    },
    {
      "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
      "hidden": false,
      "name": "Ubuntu-18.04",
      "source": "Windows.Terminal.Wsl"
    },
    {
      "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
      "hidden": false,
      "name": "Azure Cloud Shell",
      "source": "Windows.Terminal.Azure"
    },
    {
      "guid": "{00000000-0000-0000-ba54-000000000002}",
      "acrylicOpacity": 0.75,
      "closeOnExit": true,

      "colorScheme": "Campbell",
      "commandline": "\"%PROGRAMFILES%\\git\\usr\\bin\\bash.exe\" -i -l",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Consolas",
      "fontSize": 10,
      "historySize": 9001,
      "icon": "%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
      "name": "Git",
      "padding": "0, 0, 0, 0",
      "snapOnInput": true,
      "startingDirectory": "E:\\source\\",
      "useAcrylic": true
    },
    {
      "guid": "{00000000-0000-0000-ba54-000000000003}",
      "acrylicOpacity": 0.75,
      "closeOnExit": true,
      "background": "#5d81a3",
      "colorScheme": "Campbell",
      "commandline": "%PROGRAMFILES%\\Far Manager\\Far.exe",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Consolas",
      "fontSize": 10,
      "historySize": 9001,
      "name": "Far Manager",
      "padding": "0, 0, 0, 0",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": true
    },
    {
        "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
        "hidden": false,
        "name": "Ubuntu-20.04",
        "source": "Windows.Terminal.Wsl"
    }
  ],
  "schemes": [
    {
      "background": "#0C0C0C",
      "black": "#0C0C0C",
      "blue": "#0037DA",
      "brightBlack": "#767676",
      "brightBlue": "#3B78FF",
      "brightCyan": "#61D6D6",
      "brightGreen": "#16C60C",
      "brightPurple": "#B4009E",
      "brightRed": "#E74856",
      "brightWhite": "#F2F2F2",
      "brightYellow": "#F9F1A5",
      "cyan": "#3A96DD",
      "foreground": "#F2F2F2",
      "green": "#13A10E",
      "name": "Campbell",
      "purple": "#881798",
      "red": "#C50F1F",
      "white": "#CCCCCC",
      "yellow": "#C19C00"
    },
    {
      "background": "#282C34",
      "black": "#282C34",
      "blue": "#61AFEF",
      "brightBlack": "#5A6374",
      "brightBlue": "#61AFEF",
      "brightCyan": "#56B6C2",
      "brightGreen": "#98C379",
      "brightPurple": "#C678DD",
      "brightRed": "#E06C75",
      "brightWhite": "#DCDFE4",
      "brightYellow": "#E5C07B",
      "cyan": "#56B6C2",
      "foreground": "#DCDFE4",
      "green": "#98C379",
      "name": "One Half Dark",
      "purple": "#C678DD",
      "red": "#E06C75",
      "white": "#DCDFE4",
      "yellow": "#E5C07B"
    },
    {
      "background": "#FAFAFA",
      "black": "#383A42",
      "blue": "#0184BC",
      "brightBlack": "#4F525D",
      "brightBlue": "#61AFEF",
      "brightCyan": "#56B5C1",
      "brightGreen": "#98C379",
      "brightPurple": "#C577DD",
      "brightRed": "#DF6C75",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#E4C07A",
      "cyan": "#0997B3",
      "foreground": "#383A42",
      "green": "#50A14F",
      "name": "One Half Light",
      "purple": "#A626A4",
      "red": "#E45649",
      "white": "#FAFAFA",
      "yellow": "#C18301"
    },
    {
      "background": "#073642",
      "black": "#073642",
      "blue": "#268BD2",
      "brightBlack": "#002B36",
      "brightBlue": "#839496",
      "brightCyan": "#93A1A1",
      "brightGreen": "#586E75",
      "brightPurple": "#6C71C4",
      "brightRed": "#CB4B16",
      "brightWhite": "#FDF6E3",
      "brightYellow": "#657B83",
      "cyan": "#2AA198",
      "foreground": "#FDF6E3",
      "green": "#859900",
      "name": "Solarized Dark",
      "purple": "#D33682",
      "red": "#D30102",
      "white": "#EEE8D5",
      "yellow": "#B58900"
    },
    {
      "background": "#FDF6E3",
      "black": "#073642",
      "blue": "#268BD2",
      "brightBlack": "#002B36",
      "brightBlue": "#839496",
      "brightCyan": "#93A1A1",
      "brightGreen": "#586E75",
      "brightPurple": "#6C71C4",
      "brightRed": "#CB4B16",
      "brightWhite": "#FDF6E3",
      "brightYellow": "#657B83",
      "cyan": "#2AA198",
      "foreground": "#073642",
      "green": "#859900",
      "name": "Solarized Light",
      "purple": "#D33682",
      "red": "#D30102",
      "white": "#EEE8D5",
      "yellow": "#B58900"
    }
  ]
}

**Comment by zadjii-msft** [comment]
Huh. I'm not seeing a crash on 1.4.3243.0 with your settings, nor am I seeing a crash on `main`.
![image](https://user-images.githubusercontent.com/18356694/101000430-85cf1280-3523-11eb-92c4-27dd7b8c1b00.png)
![image](https://user-images.githubusercontent.com/18356694/101000822-ffff9700-3523-11eb-8c9d-67952762b101.png)


What editor are you using to edit the file? Maybe a garbage byte snuck its way into the file, that doesn't round-trip through github?

**Comment by dmytrobaranovskyi** [comment]
Wtf... I've reinstalled and it is ok... 
Sorry for disturbing you.

**Comment by zadjii-msft** [comment]
Don't worry about it! Glad it's fixed itself ☺️
