### ISSUE TITLE
Underline hyperlink on hover, even if not focused

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#8475]
# Description of the new feature/enhancement

I'd like Windows Terminal to underline the hyperlink on which I hover the mouse pointer, even if the pane and the Windows Terminal window do not have the focus. This would feel more consistent because a single Ctrl+click already suffices to open the hyperlink regardless of where the focus is.

I suppose it should then show the tool tip as well.

**Comment by zadjii-msft** [comment]
Huh, I don't think we're doing any special logic if the control is focused or not. WE might not get mouse events _at all_ if the control isn't focused 😕 

There might be a way to tell XAML to give us the events though, we'll need to investigate.

**Comment by Don-Vito** [comment]
@zadjii-msft - not sure if it is related, but:

```
 void TermControl::_PointerMovedHandler(Windows::Foundation::IInspectable const& /*sender*/,
                                           Input::PointerRoutedEventArgs const& args)
{
...
        if (!_focused)
        {
            args.Handled(true);
            return;
        }
...
}
```

I can take a look if it helps

**Comment by zadjii-msft** [comment]
🤦‍♂️ 

Well that's on me for triaging at 4:30am without coffee. Thanks!

**Comment by Jspooner09** [comment]
Got cumuter virus


Jimmy R. 

CONFIDENTIALITY: The information contained in this transmission may contain privileged and confidential information. It is intended only for the use of the person(s) named above. If you are not the intended recipient, you are hereby notified that any review, dissemination, distribution or duplication of this communication, and the information contained in it, is strictly prohibited. If you are not the intended recipient, please contact the sender and immediately destroy all copies of the original message.



On Thursday, December 3, 2020, 10:59 AM, Mike Griese <notifications@github.com> wrote:




 🤦‍♂️
 
Well that's on me for triaging at 4:30am without coffee. Thanks!

**Comment by PhMajerus** [comment]
Related, if a hyperlink is highlighted because of a mouse hover, and user alt-tab to activate another app, the hyperlink will stay in that state regardless of mouse position until Terminal receives the focus again.

I agree with @KalleOlaviNiemitalo that hyperlinks should still react to mouse hover when Terminal doesn't have the focus as it would be consistent with the hover behavior of common controls since Windows 98, but if the current behavior is to be kept for performances reasons or something, all hyperlinks should return to non-highlighted state when Terminal loses the focus.

**Comment by KalleOlaviNiemitalo** [comment]
If I start selecting text with the mouse in Windows Terminal, and Alt+Tab to a different window while keeping the mouse button down, then the selection no longer reacts to the position of the mouse cursor; but if I Alt+Tab back to Windows Terminal without having released the mouse button, then the selection starts reacting again. I presume this is a consequence of the previously quoted source code.
