### ISSUE TITLE
Feature request: Images rendered as inline output

### ISSUE THREAD

**Issue by lukepuplett** [microsoft/terminal#848]
Back in the XAML days and when I first learned PowerShell, I fantasized about being able to write a little control that would take some inputs and render a graphic, and then perhaps even stream into that control and have the graphic change in realtime.

Imagine a little chart printed out in the console as the result of a command. People could write little graphical widgets and package them up.

A bit like `Out-Grid` in PowerShell but a little rectangle graphic would pop out in the console itself on the next line. Today we have Jupyter Notebooks which are a similar idea.

I guess this could be done with SVG today?

Perhaps if SVG can be rendered inline within a bounding rect and if the SVG source markup can be referenced and updated and then dynamically the UI redraws, then people will figure out a way to build up the pieces from other stuff already out there.

Or perhaps printing bitmap/rasters into the console is all that's needed, so long as the source bitmap can be dynamically updated (to animate it), and then the vector rasterization part is something pluggable in the pipeline before it.

**Comment by mKay00** [comment]
I guess you mean something like #448?

**Comment by lukepuplett** [comment]
:-O yes! Thanks. Can close as dupe.

This: https://github.com/rs/jplot/issues/6

**Comment by lukepuplett** [comment]
Closing as a duplicate.
