### ISSUE TITLE
[Usable - Windows Powershell]: An onscreen element must not have a null BoundingRectangle property.

### ISSUE THREAD

**Issue by Chandresh1007** [microsoft/terminal#8484]
**Test Environment:**
OS: Win 10 2004 Build (20262.1010)
App: Windows Terminal
App version: 1.4.3243.0
Tool: Accessibility Insights for Windows

**Repro Steps:**
1. Open Windows terminal app.
2. Now run accessibility insight tool on the application.
3. Observe the issue.

**Actual Result:**
An onscreen element must not have a null BoundingRectangle property.

**Expected Result:**
- If the element is offscreen, set its IsOffscreen property to TRUE.
- If the element is onscreen, provide a BoundingRectangle property.

![Usable_Bounding rectangle property_Details](https://user-images.githubusercontent.com/53220700/101027445-0599c300-359e-11eb-8efb-437ad4a45c31.png)

![Usable_Bounding rectangle property_How to fix](https://user-images.githubusercontent.com/53220700/101027452-07638680-359e-11eb-9a16-09ed23f249cd.png)

**Comment by carlos-zamora** [comment]
Taking a closer look at the full tree via Inspect.exe:
![Inspect.exe UIA Tree](https://user-images.githubusercontent.com/11050425/101067032-e2462800-354b-11eb-8208-b1b813f0edd0.png)

"DesktopWindowXamlSource" is added by XAML Islands. It's children basically make up the entirety of Windows Terminal's UI. This unnamed pane (type `Windows.UI.Input.InputSite.WindowClass`) is presumably a part of that XAML Islands. I don't think we even have access to it, so I'll have to file a bug on them.

**Comment by zadjii-msft** [comment]
That makes sense, thanks!

**Comment by zadjii-msft** [comment]
@carlos-zamora did we ever end up filing an internal bug on the XAML team for this one?

**Comment by carlos-zamora** [comment]
> @carlos-zamora did we ever end up filing an internal bug on the XAML team for this one?

Whoops. Looks like I never did. That's my bad.

That said, I'm not seeing this on v1.9.1942.0. @Chandresh1007 can you verify if this is fixed?

**Comment by zadjii-msft** [comment]
(this also may have been fixed in Windows 11 - hard to say for sure)

**Comment by v-rpundir** [comment]
@carlos-zamora @zadjii-msft Issue is not coming on v1.9.1942.0 on OS Windows 11 Version 21H2 (OS Build 22000.120) as shown in below screenshot:

![image](https://user-images.githubusercontent.com/86412703/128974101-34208e8f-dcd7-4f12-9b09-149fb4d3449e.png)

**Comment by zadjii-msft** [comment]
@v-rpundir Great, so can we close this one?

**Comment by v-rpundir** [comment]
Yes @zadjii-msft You can close this one.
