### ISSUE TITLE
[Supporting the Platform - Windows Powershell]: Tab text "Windows Powershell" does not get properly visible after resizing the system setting.

### ISSUE THREAD

**Issue by Chandresh1007** [microsoft/terminal#8486]
**User Experience:**
If any application does not support resizing of text (Except for captions and images of text)up to 200 percent without loss of content or functionality, the users with mild visual disabilities who scales the text instead of using the assistive technology would be impacted as zooming will not work as desired.

**Test Environment:**
OS: Win 10 2004 Build (20262.1010)
App: Windows Terminal
App version: 1.4.3243.0

**Pre-Requisite:**
1. Set the resolution to 1280*768 
2. Make text size bigger slider to 225% and Apply.

**Repro Steps:**
1. Open Windows terminal app.
2. Observe the issue.

**Actual Result:**
Tab **text "Windows Powershell" does not get properly visible after resizing** the system setting.
Also, **'Dropdown' button and 'Edit area' text does not adapt resize mode setting**.

**Expected Result:**
Tab **text "Windows Powershell" should get properly visible after resizing** the system setting.
Also, **'Dropdown' button and 'Edit area' should adapt resize mode setting**.

**MAS Reference:**
**MAS1.4.4**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7Bb69e5ccc-dde2-4406-b550-4deb38648f6d%7D&cid=5b9ee2c7-2919-4bfe-a2aa-85d3f1a7d77d

![MAS1 4 4_text powershell of tab does not get properly visible after resizing the browser](https://user-images.githubusercontent.com/53220700/101043185-0a617580-35a4-11eb-8d3d-2df79afaa075.png)

**Comment by zadjii-msft** [comment]
All this seems like it needs to be moved upstream to WinUI. The default tab sizing behavior is `equal` tab widths, which uses the default size of the tabs as defined by MUX. It seems to me like if the text on the tabs gets bigger at 225% font size, then the tabs should as well.

Same logic applies to the tab close buttons and the `SplitButton` (responsible for the dropdown).

**Comment by Chandresh1007** [comment]
XAML team rejects bug. The tab is not intended to get bigger when the text size changes. Terminal does not control this.

Hence, closing the bug.
