### ISSUE TITLE
How to add ubuntu terminal support to my windows terminal ? & Solution that can't open

### ISSUE THREAD

**Issue by nestripo** [microsoft/terminal#849]
I've got windows executable files from Internet so I can install successfully by steps that follows:

- Install `CascadiaPackage*.cer` with option `Trusted Institutional Certificate`
- Double click the execuable file and then `start`

> To get platform_x64 execuable files, contact me at swmdxbg@163.com.

I'd like to firgure out solution about how to add **ubuntu termina**l support to my windows terminal. Great thanks !

What's more, you may find that if you modified `profile.json` uncorrectly before unable to reopen it.

Solution to *unable to open windows terminal` is :
> Delete `C:\Users\YourName\AppData\Local\Packages\Microsoft.WindowsTerminal_*` . Then click `Windows Terminal` Icon. (Directory varies according to Your Account and computer)

You'll see it works again !

**Comment by mKay00** [comment]
Don't use random executables from random sources! And don't give them away if they ask you on your contact. You could help spread a virus.

To get Linux, you have to use Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10). This has nothing to do with the Windows Terminal.

**Comment by nestripo** [comment]
> Don't use random executables from random sources! And don't give them away if they ask you on your contact. You could help spread a virus.
> 
> To get Linux, you have to use Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10). This has nothing to do with the Windows Terminal.

Thanks for your care. But I have pick a new problem as I running `bash.exe` in `Windows Terminal` :
```
/mnt/c/WINDOWS/system32$
sudo chmod -R 777 /mnt/c/Users/nestripo/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/nestripo/                                                  chmod: cannot access '/mnt/c/Users/nestripo/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/nestripo/': Permission denied
```
And I've given absolutely control permission to that DIRECTORY in **windows 10**. When I try to `source .bashrc`, I got :
```
/mnt/c/WINDOWS/system32$ 
source /mnt/c/Users/nestripo/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/nestripo/.bashrc                                                      -bash: /mnt/c/Users/nestripo/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/nestripo/.bashrc: Permission denied
```

I have no idea about it.

**Comment by mKay00** [comment]
As I said, this has nothing to do with Windows Terminal and belongs to https://github.com/microsoft/WSL

**Comment by nestripo** [comment]
> As I said, this has nothing to do with Windows Terminal and belongs to https://github.com/microsoft/WSL

I just installed the Windows Subsystem for Linux . I've found the final solution that is :
```
cd $HOME
```
And then command `source .bashrc` runs properly !

**Comment by zadjii-msft** [comment]
I'm gonna re-emphasize this here, because some people aren't getting the picture.

# DO NOT install binaries from untrusted 3rd party sources.
There's no way for you to guarantee that the application you installed from them did not also secretly include some sort of virus, compiled in by the distributor of the binary.

If you don't want to build the terminal from source, please be patient as we continue polishing the terminal for a preview release this summer.
