### ISSUE TITLE
It does not recognize python

### ISSUE THREAD

**Issue by talley** [microsoft/terminal#8493]
I downloaded it to replace the current ConEmu i have on my machine. When i type python on the new terminal,it tries to open a file.
Normally is supposed to lunch python compiler prompt.
FIX IT.
Thank You

**Comment by zadjii-msft** [comment]
You gotta provide like, a lot more info here. What version of the Terminal? Of Python? What command are you executing? What program is it opening the file in?

There's not really a python "compiler" so your whole question is confusing.

Thank you!

**Comment by oising** [comment]
@zadjii-msft it's a _lunch python_ compiler. Maybe it gathers mice and larger rodents?

**Comment by j4james** [comment]
It might be something like [this issue](https://stackoverflow.com/questions/58754860/cmd-opens-window-store-when-i-type-python), where typing `python` at the command prompt opens up the Window Store application.

**Comment by alannt777** [comment]
Running `py` should work if you are using the python ***interpreter*** from PSF or `python` if you are using conda

**Comment by talley** [comment]
I will  try your suggestions and  will get back to you.
