### ISSUE TITLE
Drag and drop tabs into different instances

### ISSUE THREAD

**Issue by gabahey** [microsoft/terminal#8494]
Allow tabs to be dragged and dropped into different instances of terminal.  Or drag an existing tab out of terminal so that it is in a new instance.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to the following for more discussion.

/dup #5000
/dup #1256
