### ISSUE TITLE
ls --color and vim incorrect colors

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#85]
_From @nickolasclarke on July 29, 2017 8:20_

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16232.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

when I use `ls --colors` all subsequent prompts have a highlighted background applied to them when using hyper terminal and vs code terminal. This also happens when I use vim in those terminals.

Hyper:
![capture](https://user-images.githubusercontent.com/2177320/28743272-b18c023a-7478-11e7-9db4-9c9c165fbf9b.JPG)

VS Code:
![capture2](https://user-images.githubusercontent.com/2177320/28743273-b7ef361a-7478-11e7-9787-a913e7e655f5.JPG)

vim on the BashOnWindows terminal and in Hyper (same thing happens in vscode):
![capture3](https://user-images.githubusercontent.com/2177320/28743306-7ed8985c-7479-11e7-8c3a-fcfaa9af4eda.JPG)

* What's wrong / what should be happening instead:

there should not be a alternative background color applied to all lines, and it should not remain after the  the command completes.

I'm honestly at a bit of a loss on how to troubleshoot this. I thought it my be my some things I did with LS_COLORS and .dircolors, but I've backed everything out of those and its still doing this. I dont believe it is an issue with the hyper terminal since I am seeing it from the VS Code terminal as well. 

_Copied from original issue: Microsoft/WSL#2378_

**Comment by bitcrazed** [comment]
_From @nickolasclarke on July 29, 2017 8:50_

update: This also happens if I try to use `fish` and `git`

**Comment by bitcrazed** [comment]
_From @zadjii-msft on July 31, 2017 20:53_

It's probably an issue with mintty if it's affecting both hyper and vscode. They both mintty to attach to a conhost instance. 

I don't believe there's any terminal out there that's figured out a way to get conhost's RGB colors working quite yet. We don't plan on changing the API surface, so they can't query the contents of the buffer to get RGB colors back out, instead we round the color to the nearest color table entry. 

As an example, `vi` in hyper (top) vs `vi` in `gnome-terminal` (bottom left), vs `vi` in conhost (bottom right):

![image](https://user-images.githubusercontent.com/18356694/28797334-d5b85392-75f5-11e7-81e6-7d0132a44c59.png)

@mintty can comment more, I don't know too much about the solution space for this issue.

**Comment by zadjii-msft** [comment]
You know, this might just be a close-by-design now. The original post might predate us announcing conpty in the first place. Hyper (et al) should be using conpty if they want to act as Terminal emulators. Using the Console API to try and get color and text information out of the buffer simply isn't going to work the way they want.
