### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matthewsaccount** [microsoft/terminal#850]
Hi I'm having a hard time trying to reset my password for live.com I know my email address I have used in the past its matt-thompson12@live.com 
I can't remember password and I use different email now so when I try to reset it it always sends stuff to hotmail address I can't access it:

**Comment by mKay00** [comment]
This has nothing to do with Windows Terminal and this here is not a Microsoft Support page. If this steps don't help, use the email link at the bottom to contact support: https://support.microsoft.com/en-us/help/12429/microsoft-account-sign-in-cant
