### ISSUE TITLE
Use startingDirectory only when windows terminal is started from start menu / task bar / a terminal is started from windows terminal itself

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/terminal#8508]
# Description of the new feature/enhancement

Currently I am setting `startingDirectory` to ` "."`. So when I type `wt` in explorer address bar, I get a windows terminal in that directory. But this also makes any terminal starting from start menu in `C:\WINDOWS\System32`.

I could also set `startingDirectory` to ` "~"`. So terminals starting from start menu start properly in my user folder. But to have a terminal in current folder, I have to type `wt -d .`

I think it makes more sense to only use `startingDirectory` when it can not be inferred from the environment. (From Starting menu, task bar, selection menu). If `wt` is called then it is very likely user would want it in the folder it is called.

# Proposed technical implementation details (optional)

I kind of think right click menu open in windows terminal can do the same thing. But why it only appears when a folder is selected? Sometimes I want to start it in the folder I am in.
![image](https://user-images.githubusercontent.com/28442838/101274297-d4a4d280-37d7-11eb-868f-f791a215147b.png)
![image](https://user-images.githubusercontent.com/28442838/101274300-da021d00-37d7-11eb-8d4c-0a403da6c688.png)

**Comment by DHowett** [comment]
Unfortunately, we tried this and it was a disaster. There is no reliable way to know how it was launched ☹️ 
More info in the PR discussion here: https://github.com/microsoft/terminal/pull/3547

The folder bug is https://github.com/microsoft/terminal/issues/6414.
