### ISSUE TITLE
When launching ssh session straight from task bar, pressing enter on password opens a new terminal window.

### ISSUE THREAD

**Issue by mathew123456** [microsoft/terminal#8511]
Windows Terminal Version: 1.4.3243.0

Right-clicking on taskbar icon, and launching SSH.exe session, upon pressing enter for password, a new window is launched.
This will happen indefinitely, if I put in password again on new window, another new window opens.

settings:
{
            "acrylicOpacity": 0.75,
            "closeOnExit": "always",
            "commandline": "ssh.exe casper",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Roboto Regular",
            "fontSize": 13,
            "guid": "{1777cdf0-b2c4-5a63-a204-1111f349e123}",
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
            "name": "casper",
            "padding": "0, 0, 0, 0",
            "snapOnInput": true,
            "startingDirectory": "%USERPROFILE%"
        }

**Comment by DHowett** [comment]
What version of `ssh.exe` are you using? Please run `ssh.exe -V`

**Comment by mathew123456** [comment]
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

**Comment by zadjii-msft** [comment]
Is the window that opens a new _Terminal_ window, or is it a vintage console window? Does this happen with any other profiles, where hitting enter spawns another instance? Does this happen if you open the profile without using the taskbar jumplist?

**Comment by mathew123456** [comment]
Hopefully this GIF makes sense?

First scenario, I right click on task bar to launch
Second scenario, I launch a terminal AFTER command prompt..

**Comment by zadjii-msft** [comment]
@mathew123456 I'm not sure the GIF survived getting emailed to GitHub - you might need to actually log in to post it 😕

**Comment by mathew123456** [comment]
take 2 :)
![WindowsTerminalBug](https://user-images.githubusercontent.com/29786955/101416150-52ceb980-393d-11eb-9311-38addbb65f21.gif)

**Comment by zadjii-msft** [comment]
_what the heck_

I've never seen anything like that before. Does the second window only open up after actually submitting your password, or just on hitting the <kbd>enter</kbd> key? It looks like the first terminal window you hit <kbd>enter</kbd> in didn't actually start the ssh login, which makes me think it didn't get _any_ input. If you just hit <kbd>enter</kbd> right away, will a second terminal open like this? I'm thinking maybe the focus is stuck on the taskbar, not the Terminal. 

Does this repro for other profiles at all? Like, if you just open a powershell profile with the taskbar, and hit <kbd>enter</kbd>, does that open another powershell window?

What version of Windows are you on? I'm thinking this might be a shell bug, but I'm not positive

**Comment by LuanVSO** [comment]
can confirm terminal don't receive input after opening a profile from taskbar jump list, need to click the window to make it work.
which is very strange since background acrylic is active on the window (suggesting it is in foreground)

**Comment by mathew123456** [comment]
Ok - after right-clicking launch from taskbar...

ssh shell - pressing enter without password, still launches a new window.
Windows Powershell - same - pressing enter on terminal launches a new window as well

**Comment by DHowett** [comment]
What version of Windows is this? We've seen issues with the application receiving focus on launch, but never been able to figure them out. FWIW: we are creating a completely normal window and giving it focus in a completely normal way (letting the OS do it.)

**Comment by mathew123456** [comment]
I had this issue running Windows 10 1909 – Having said that – my pc was upgraded to 20H2, and the issue is no longer there.

**Comment by DHowett** [comment]
Ah, **that** may explain why none of us Microsofties have been able to repro this issue. 😁 
I'm gonna mark this Not-Repro & close it out, but if you hit it again please come let us know!
