### ISSUE TITLE
Writing "š" to powershell shows only "s" even though "š" is correctly recorded

### ISSUE THREAD

**Issue by petrroll** [microsoft/terminal#8512]
# Environment
- `Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0`
- Powershell: `5.1.19041.610`
- Terminal: 1.4.3243.0

# Steps to reproduce
Open new powershell tab. Switch keyboard to CZ keyboard. Write "š".

# Expected behavior
"š" appears on screen.

# Actual behavior
"š" doesn't appear on screen. "s" appears on screen instead. "š" is actually recorded, however.

# Note: 
- Works correctly in plain cmd (might be powershell issue).

**Comment by zadjii-msft** [comment]
Does this happen in a powershell window that's running in the vintage console, _not_ the Terminal? (i.e. just by running `powershell.exe` directly)?

Does this repro even after removing `PSReadline` (`Remove-Module PSReadline`)?

**Comment by petrroll** [comment]
Apologies, you are right. The issue appears even when run through `powershell.exe` directly. As for PSReadline, it is not recognized as cmdlet, ... .

**Comment by petrroll** [comment]
As for PSReadline, the issue, indeed, goes away when PSReadline is removed.

**Comment by zadjii-msft** [comment]
Well that's good to hear! It sounds like this is an issue that should be filed over at https://github.com/powershell/PSReadline then ☺️ Thanks!
