### ISSUE TITLE
It is slow to load when you install custom themes. When you try to open a tab/new tab it takes a long time.

### ISSUE THREAD

**Issue by hirwablessing** [microsoft/terminal#8518]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by Don-Vito** [comment]
@hirwablessing - I guess the team will need more details, as I am using custom themes and the terminal works quite as usual. Can you please provide some more details, like:
* The version of the terminal
* The theme that you are using.
* With what profile.
* How slow it is (approximately in second, compared to the same profile without a theme)?

**Comment by hirwablessing** [comment]
Sometimes it works well and other times it works slowly. When it slows down it takes about 5 seconds to open a new tab while in it's normal state it only takes 1 second.

Terminal version: 1.4.3243.0
Theme: Paradox
 colorScheme: One half dark
fontFace: Cascadia Mono PL,
Profile: powershell.exe

**Comment by skyline75489** [comment]
Do note that CPU is a valuable resource. If there are some CPU-consuming tasks running in the background, it could reasonably lead to slow startup time in the terminal.

**Comment by zadjii-msft** [comment]
Does this happen for _all_ profiles, or just the powershell profile?

**Comment by hirwablessing** [comment]
Only powershell.

**Comment by zadjii-msft** [comment]
That sure sounds like it's a powershell problem then, right? PowerShell is known to have a fairly long startup. Do you have any other powershell config in your powershell profile (`Profile.ps1`)? 

You might want to try starting powershell with `-noprofile` or `-nologo`, those can help speed up the launch of powershell.

**Comment by hirwablessing** [comment]
Okay sure, I'll try that one. And thanks for all the help.
