### ISSUE TITLE
Tab Renamer appearance broken in 1.6.3371.0

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#8519]
Version 1.6.3371.0

Try to rename a tab:
![image](https://user-images.githubusercontent.com/18356694/101478614-8ea25880-3916-11eb-9b3a-25169a9f99c5.png)

I'm guessing this is either the upgrade to MUX 2.5 (@DHowett) or this was the TabHeaderControl (@PankajBhojwani). Thoughts?

Oh weirdly, it's only broken when the renamer is _w i d e_. Gif:
![tab-renamer-visual-bug-000](https://user-images.githubusercontent.com/18356694/101479227-7a129000-3917-11eb-83d6-5b38eded893f.gif)

**Comment by Don-Vito** [comment]
@zadjii-msft - I think this was before MUX upgrade. I've seen it ~2 weeks ago.. thought it is some setting on my side.

**Comment by zadjii-msft** [comment]
Oh well that's a good data point to have. I'm less worried about this being a recent regression then. It's like a weird z-ordering bug, but I really don't know enough about XAML to be sure.
