### ISSUE TITLE
We need a way to disable the bell

### ISSUE THREAD

**Issue by nikatjef** [microsoft/terminal#8523]
# Environment

```
Windows build number: [run `[Version 10.0.19041.630]`
Windows Terminal version (if applicable): 1.5.3242.0

Any other software?
Multiple variants of Linux and BSD
```

# Steps to reproduce

In a WSL terminal and at a command prompt, press tab or any direction key.  

# Expected behavior

Bell will sound

# Actual behavior

Bell will sound

# Request

Give us a mechanism in Terminal settings to disable the bell without having to silence the bell every where.  Perhaps a profile setting to disable sound in general for the specific profile or possible an option to disable CTRL-G

**Comment by zadjii-msft** [comment]
[`bellStyle`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#bell-settings-preview) is already a per-profile setting. So you can set it to `"none"` for your WSL distros and leave it `"audible"` for the rest

**Comment by nikatjef** [comment]
Awesome, thank you so much.  Not sure how I missed that.

**Comment by KarelPeeters** [comment]
For anyone else finding this issue: the option is now documented in https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced.

**Comment by mangelozzi** [comment]
Out of interest does anybody actually enjoy the beep and is glad this feature was added?

**Comment by zadjii-msft** [comment]
I mean, there were at least 8 people who 👍'd #4046

![image](https://user-images.githubusercontent.com/18356694/133987016-678f79d3-f613-49bd-8e6b-71f27c920be9.png)

so I'm guessing there are plenty of people who like it.

**Comment by void32** [comment]
Well I don't; it's not a pleasant experience to hear this sound when wearing a headset :-S 

Anyways, setting "bellStyle" to "none" doesn't work for me. Atleast not in PowerShell...

![image](https://user-images.githubusercontent.com/6043260/134487714-e5db0162-a2dd-4462-9827-f942b13904e2.png)

**Comment by zadjii-msft** [comment]
Could you share your whole `settings.json`?

**Comment by mangelozzi** [comment]
> I mean, there were at least 8 people who 👍'd #4046
> 
> ![image](https://user-images.githubusercontent.com/18356694/133987016-678f79d3-f613-49bd-8e6b-71f27c920be9.png)
> 
> so I'm guessing there are plenty of people who like it.

Thanks for pointing that out, I guess it takes all types to make the world go around, cheers!

**Comment by zadjii-msft** [comment]
Boy I can't get PowerShell to beep at all. I'm worried that they're doing something weird like calling `[console]::beep()` rather than emitting a `BEL`, which we wouldn't be able to stop, but since I can't even get powershell to beep outside of the Terminal I can't be more help 😕

**Comment by HoffiMuc** [comment]
is there a (possible) setting for visual bell (e.g. flickering the background) ?

**Comment by DHowett** [comment]
> for windterm portable:
> 

We don't own "Windterm". This is not the appropriate place to file issues on "Windterm". :)

**Comment by gigberg** [comment]
> 

open powershell in wt，cilck Ctrl+R for history search, then click backspace, I heard a beep noise, which not emitting a BEL.

**Comment by gigberg** [comment]
open powershell in wt，cilck Ctrl+R for history search, then click backspace, I heard a beep noise, which not emitting a BEL. It‘s caused by powershell.exe, nothing about wt.

**Comment by techsk8** [comment]
Thank you!
I hate that bell

**Comment by RealMuDao** [comment]
> For anyone else finding this issue: the option is now documented in https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced, and can also be set the the GUI settings, but only per profile and not as a global setting.
> 
> It's at the bottom of this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/7887115/129742354-966e9c73-8889-47ab-a823-73811a4b35c9.png)

Version 1.16.10261.0 has a Defaults profile, which is gloabal seeting.
![image](https://user-images.githubusercontent.com/19743480/221388199-6b5dc526-3c7f-4162-8876-4082d3dfe4cc.png)
