### ISSUE TITLE
Win+V Clipboard History not working

### ISSUE THREAD

**Issue by XDracam** [microsoft/terminal#8526]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.662]
Windows Terminal version (if applicable): 1.4.3243.0

Any other software? No
```

# Steps to reproduce

1. Copy any text with Ctrl+C
2. Paste into terminal using Win+V copy history

# Expected behavior

The text is pasted into the terminal

# Actual behavior

Nothing happens

**Comment by DHowett** [comment]
Thanks for the report! This is a /dup of #322

**Comment by DHowett** [comment]
You can bind ^V to paste to fix this.
