### ISSUE TITLE
Mouse input support not working

### ISSUE THREAD

**Issue by r-devulap** [microsoft/terminal#8528]
# Environment

```none
Windows build number: 10.0.19041.423
Windows Terminal version (if applicable): Version: 1.4.3243.0

```

# Steps to reproduce

Installed Version: 1.4.3243.0 from the Github release page. According to https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-10-release/, it should support mouse input, but my terminal doesn't seem to. How do I fix it?  

# Expected behavior

Should support mouse input (example: should be able to select panes in tmux via mouse click)

# Actual behavior

Unable to switch panes in tmux using mouse.

**Comment by DHowett** [comment]
Since you are not using "any other software" and have deleted it from the template, I can't help you.

**Comment by DHowett** [comment]
If I had to guess, it's because you're using ssh.exe version 7.7 that comes with Windows. That version of SSH _blocks_ mouse input.

**Comment by r-devulap** [comment]
yup

```
ssh -V 
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5. 
```

What do you mean by "any other software" ? I was only using a WSL terminal. Does that use ssh underneath?

**Comment by DHowett** [comment]
So, this terminal mostly runs Windows applications. The one you’re using is the version of SSH that was shipped with Windows :smile: which unfortunately has broken mouse support. 

(Terminal can also run WSL, and it does so well. If you use SSH inside WSL, mouse support will work fine!)

**Comment by r-devulap** [comment]
I was trying to follow the instructions provided here https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH to upgrade the ssh to release 8.1. I am stuck at step 3 - _Make sure binary location has the Write permissions to just to SYSTEM, Administrator groups_ Would appreciate any help. (sorry, I am novice developer in Windows)
