### ISSUE TITLE
Virtual keyboard not raising in Tablet mode

### ISSUE THREAD

**Issue by mcandre** [microsoft/terminal#8529]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Microsoft Windows [Version 10.0.18363.1198]

Windows Terminal version (if applicable):

1.4.3243.0
```

# Steps to reproduce

1. Fold Surface Cover back.
2. Launch Windows Terminal.

# Expected behavior

The virtual keyboard should appear.

# Actual behavior

No input device available. Even after tapping on the terminal screen.

**Comment by zadjii-msft** [comment]
My brain initially thought this was #7495, but that was about the arrow keys not working on the virtual keyboard, not it failing to appear. 

Then I came across #2055, #3639 and #4689 which are all basically the same report, but we thought they were fixed in #1919 and #4867.

I guess it's time to dig out the old Surface Pro 3 and see if we can get a repro.

**Comment by DHowett** [comment]
Triaged into 2.0. This is important.

**Comment by Poopooracoocoo** [comment]
@zadjii-msft just out of curiosity, what device do you usually use?

**Comment by itsme-alan** [comment]
@Poopooracoocoo I guess you shouldn't ping him while he is enjoying his holidays

**Comment by Poopooracoocoo** [comment]
Ah. Well my question wasn't related to his work anyway :P It was a personal question.

**Comment by zadjii-msft** [comment]
I don't mind getting ping'd on the holidays, it's mot like I'm about to check my mail on vacation 😆 

My work laptop is a Surface Laptop 2. My Surface Pro 3 is a personal device that I bought a while back, but it's still kicking. Handy for testing bugs like this that won't repro on the slaptop.

**Comment by leonMSFT** [comment]
Wasn't able to get this to repro on my surface book with the screen detached 😕, though I tested it on ver. 1.9.1942. @mcandre Do you think you could try this again and see if you experience the same issue?
