### ISSUE TITLE
Different setting.json is used

### ISSUE THREAD

**Issue by limo520** [microsoft/terminal#8530]
# Environment

```none
Windows build number: Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.4.3243.0
```

# Steps to reproduce
open "Windows Terminal" from start menu.
open "Windows Terminal" from Explorer by typing "wt".

# Expected behavior

They use same setting file.

# Actual behavior

The 1st setting file is "C:\Users\someone\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json".
The 2nd is "C:\Users\someone\AppData\Local\Microsoft\Windows Terminal\settings.json".

**Comment by DHowett** [comment]
You have two separate installations of Terminal. I don’t know why- it isn’t normal, and you’ll need to figure out why.
