### ISSUE TITLE
Terminal does not remember where it was on screen, upon re-opening

### ISSUE THREAD

**Issue by clounie** [microsoft/terminal#8531]
# Environment

Windows build number: `10.0.19041.0`
Windows Terminal version (if applicable): `1.4.3243.0`

Any other software? N/A

# Steps to reproduce
Tried these steps with and without tabs. Same result.

1. Open Terminal
2. Move Terminal window to a different place in desktop than it was when it opened
3. Close Terminal
4. Re-open Terminal

# Expected behavior
When Terminal is re-opened, it should re-open at the _exact same coordinates_ it was at when I closed it.

# Actual behavior
It opens at the very top-left of my screen - which on a 4k monitor is fairly annoying.

I know where I want Terminal placed. It should not argue with my opinion.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+remember+position) when filing new issues. 

If you really want to set an initial position for the Terminal window, you could always set it with [`initialPosition`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#launch-position).

This is already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766

**Comment by clounie** [comment]
Thanks Mike. I did search, just didn't find because I wasn't thinking that generic.
