### ISSUE TITLE
Wrong text rendering when custom monitor scaling is set

### ISSUE THREAD

**Issue by LinoBarreca** [microsoft/terminal#8533]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
```

# Steps to reproduce

Set 110% in display settings, custom scaling

# Expected behavior

no problems in text rendering

# Actual behavior

glitches on some characters
See pictures
![image](https://user-images.githubusercontent.com/897723/101629976-76b7fb00-3a22-11eb-8e43-e7ff2f3298ed.png)
![image](https://user-images.githubusercontent.com/897723/101630038-951df680-3a22-11eb-9d85-bd74c8374d68.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22custom+scaling%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #4591 for more discussion.

/dup #4591
