### ISSUE TITLE
不能访问网络位置

### ISSUE THREAD

**Issue by Jesn** [microsoft/terminal#8535]
![image](https://user-images.githubusercontent.com/5728274/101642684-3d0ce180-3a6e-11eb-86d4-0cfda514af67.png)

**Comment by zadjii-msft** [comment]
I rough machine translation of this title gave me "Can't access network location".

Looking through our issue tracker, I'm finding the following issues:
* #7037
* #4424


Which have all been closed as a duplicate of #1386. Without more info, I'm inclined to do the same with this one.

/dup #1386

**Comment by 1990chs** [comment]
你解决了吗？1386爬楼爬的头疼！

**Comment by 1990chs** [comment]
@zadjii-msft  How to solve this problem, The answers in #1386 are so many and  I cn't find the solution

**Comment by socialYouth** [comment]
> @zadjii-msft How to solve this problem, The answers in #1386 are so many and I cn't find the solution
you can solve it as follow：

This is a dupe and what's really need is to get the diagnostic data you can generate from Feedback Hub. It's a known issue issue and is the same on a host with no Internet with Windows Firewall enabled and Defender as the only A/V (that's still domain joined). You can work around this by changing .msixbundle to .zip and extract. Then take the relevant CascadiaPackage msix (arm/x86/x64) and change that to .zip as well. Extract it. Open the folder. You'll find WindowsTerminal.exe inside. Some things will not work as intended with this method ( you can't have it launch at log in for example) but for the most part everything works.
