### ISSUE TITLE
Check status of TextBuffer Unit Tests in CI

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#854]
If the TextBuffer unit tests aren't named `.Unit.Tests.` then I'm pretty sure the CI isn't running them.

_Originally posted by @miniksa in https://github.com/microsoft/terminal/pull/843_

**Comment by metathinker** [comment]
Unfortunately, you are right. I looked at test results for my PR here:
https://dev.azure.com/ms/Terminal/_build/results?buildId=15717&view=ms.vss-test-web.build-test-results-tab

- Searching for "defaultcolor" should find TextBuffer.UnitTests.dll!TextColorTests::TestDefaultColor , but in fact matches nothing.
- Searching for "boxarea" should find Terminal.Core.Unit.Tests.dll!TerminalCoreUnitTests::SelectionTest::SelectBoxArea, and it does.

**Comment by DHowett-MSFT** [comment]
So, question. Is it better to change this:

https://github.com/microsoft/terminal/blob/master/build/pipelines/templates/build-console-steps.yml#L53

or to change this:

https://github.com/microsoft/terminal/blob/master/src/buffer/out/ut_textbuffer/TextBuffer.Unittests.vcxproj#L25

?

**Comment by DHowett-MSFT** [comment]
... github, you have failed me :(

**Comment by miniksa** [comment]
> So, question. Is it better to change this:
> 
> https://github.com/microsoft/terminal/blob/fd98145af268dffff0125d18d4ac48d2012aa205/build/pipelines/templates/build-console-steps.yml#L52-L54
> 
> or to change this:
> 
> https://github.com/microsoft/terminal/blob/fd98145af268dffff0125d18d4ac48d2012aa205/src/buffer/out/ut_textbuffer/TextBuffer.Unittests.vcxproj#L25
> 
> ?

The latter, @DHowett-MSFT, is what I want to do. I commented on your PR #913 earlier that we should make this consistent across all testing projects. And the latter works toward consistency.
