### ISSUE TITLE
Feature request: is possible move windows terminal window between 2 screens when in focus mode

### ISSUE THREAD

**Issue by jacquen** [microsoft/terminal#8540]
Hi

I have 2 screens, when I launch in focus mode, I am not able move terminal window from screen 1 to screen 2, is possible enable this feature?

thanks

**Comment by Don-Vito** [comment]
@jacquen - how do you see the UX implementation of this (there is no UI element you can grab)?
Doesn't moving with WinKey satisfy your needs?

**Comment by zadjii-msft** [comment]
The way I usually do this is with the <kbd>Alt+Space</kbd> menu. I usually do a <kbd>Alt+Space</kbd>, <kbd>M</kbd> (to activate "Move"), <kbd>arrow key</kbd> (any direction will do), then use the mouse to move the window to the other display. Does that work?

**Comment by Don-Vito** [comment]
> 
> 
> The way I usually do this is with the Alt+Space menu. I usually do a Alt+Space, M (to activate "Move"), arrow key (any direction will do), then use the mouse to move the window to the other display. Does that work?

@zadjii-msft - isn't it simple to Press `Win+Arrow` 3 times to move between screen? :smile:

**Comment by zadjii-msft** [comment]
Well yea, but I like my window floating, not maximized, so the <kbd>Win</kbd> thing doesn't totally work. 

Oh there is that one  <kbd>Win+arrow</kbd> combo that restores the window down from maximized. That might actually be simpler after all 😆

**Comment by Don-Vito** [comment]
> 
> 
> Well yea, but I like my window floating, not maximized, so the Win thing doesn't totally work.
> 
> Oh there is that one Win+arrow combo that restores the window down from maximized. That might actually be simpler after all 😆

@jacquen, @zadjii-msft - actually `Win+Shift+Arrow` accomplishes the job in one combo.

**Comment by zadjii-msft** [comment]
Wow you just changed my life. Thanks!

**Comment by slopra** [comment]
@Don-Vito beat me to the simple global shortcut for monitor moves.
Although, what I've been doing with WT in particular is binding focus mode to `Alt+Shift+W`.

I launch in focus mode by default (PowerToys remembers my preferred window location/size).
Then if I need to move/resize, I can quickly toggle focus off with my keybinding to do so.
Then toggle focus back on 😁

**Comment by DHowett** [comment]
Looks like the OS handles this quite well! Thanks all :smile:
