### ISSUE TITLE
Feature request: switching between tab using CTRL+Pgdn and CTRL+Pgdn, Create new tab using CTRL+T, closing tab using CTRL+W

### ISSUE THREAD

**Issue by mudiadamz** [microsoft/terminal#8541]
Thank you Microsoft, this is such an awesome project, the coolest terminal i've ever encountered, but I have this problem. Usually I don't want to rely on using mouse, or even touchpad, because it hurts my finger, because I only want to use the keyboard to navigate anything. In chrome and probably many other apps i know, the basic command to CREATE, MOVE and Close between tab is like this:

CTRL+Pgdn: move tab right
CTRL+Pgdn: move tab left
CTRL+t: Create new tab
CTRL+w: close tab

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! You can actually bind these actions to whatever keys you want in your `settings.json`. Most of these actions are bound to keys by default:

```json
{ "command": "closePane", "keys": "ctrl+shift+w" },
{ "command": "newTab", "keys": "ctrl+shift+t" },
{ "command": "nextTab", "keys": "ctrl+tab" },
{ "command": "prevTab", "keys": "ctrl+shift+tab" },
```


Moving tabs isn't bound to a key, but it is in Preview with the following actions:
```json
        { "command": { "action" : "moveTab", "direction": "forward" }},
        { "command": { "action" : "moveTab", "direction": "backward" }},
```

You can feel free to bind those actions to whatever keys you'd like, and make sure to check out [the docs ](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions) for more details

**Comment by KalleOlaviNiemitalo** [comment]
> Moving tabs isn't bound to a key, but it is in Preview

Doesn't seem to have been published to Microsoft Store yet.

**Comment by zadjii-msft** [comment]
Oh, That might be wrong. That's in `main`, not preview. #8338 is _not_ in preview yet. My mistake!
