### ISSUE TITLE
How can one deploy Windows Terminal from command line?

### ISSUE THREAD

**Issue by Tembocs** [microsoft/terminal#855]
I've built Windows Terminal successful from command line. Running WindowsTerminal.exe gives a white blank window. How can I deploy it from command line? I couldn't see any instructions on how to do this.

**Comment by zadjii-msft** [comment]
We don't currently have any guidance on this. If you can deploy the CascadiaPackage from the command line, that would install the terminal.
There should be a script named `Install-AppxPacage` or similar that should install it

**Comment by oising** [comment]
I'll write some guidance, @zadjii-msft

**Comment by Tembocs** [comment]
> I'll write some guidance, @zadjii-msft

Thanks, @oising

**Comment by mdtauk** [comment]
A command line option to load a particular profile perhaps?  And maybe even an override to hide the tabs so its a single console instance only?

**winterminal.exe -p "ubuntu_dark" -s**
-p = Profile
-s = Single Instance

**Comment by zadjii-msft** [comment]
@mdtauk this isn't about adding support for commandline args, this is about deploying the appxpackage on your machine without opening Visual Studio. This workflow used to be better understood, but since the process of deploying the app was just marginally faster with Visual Studio, I've stopped deploying it from the commandline myself :/

**Comment by mdtauk** [comment]
@zadjii-msft  My apologies, I thought it was about opening from the Command Line

**Comment by Tembocs** [comment]
> 
> 
> We don't currently have any guidance on this. If you can deploy the CascadiaPackage from the command line, that would install the terminal.
> There should be a script named `Install-AppxPacage` or similar that should install it

@zadjii-msft I can't see a script with such a name in the repository.

**Comment by zadjii-msft** [comment]
That's my bad, I tried replying on mobile. *This is why you don't check work email on your phone*.

The actual script is `Add-AppDevPackage.ps1`, It'll be under something like `src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_1.0.0.0_x64_Debug_Test`

**Comment by mKay00** [comment]
Are you sure it isn't this one ".\Terminal\build\scripts\Create-AppxBundle.ps1"?

**Comment by DHowett-MSFT** [comment]
@mKay00 It is extremely _not_ that one.

**Comment by oising** [comment]
> That's my bad, I tried replying on mobile. _This is why you don't check work email on your phone_.
> 
> The actual script is `Add-AppDevPackage.ps1`, It'll be under something like `src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_1.0.0.0_x64_Debug_Test`

This is the one I'm looking at and it doesn't work as advertised - surprise lol. it just blows up with a signing error for me, almost immediately. As with building the solution has proven to be for many, I think installing the package from the CLI is going to be just as hairy. I'm trying to cover all angles by using the Windows 10 sandbox as a clean-room environment to install the AppX. I can imagine people are going to be emailing and exchanging zips of the appx with each other behind the scenes and I don't want to accidentally rely on something that's part of my development environment. I thought this would be a quick win but... hahaha, they never are.

**Comment by oising** [comment]
@miniksa "Mass-Chaos?" LOL -- we're gonna need that one often.

**Comment by oising** [comment]
btw, Windows Sandbox rocks hard.

**Comment by miniksa** [comment]
> @miniksa Michael Niksa FTE "Mass-Chaos?" LOL -- we're gonna need that one often.

I needed something to trigger the bot and was feeling a bit silly.

**Comment by oising** [comment]
Just an update here, albeit a rather pathetic one. I spent an unreasonable amount of time struggling with `SignTool` as it spat out arcane error after error and I had to give up. It seems that signing an AppX is best left to Zeus, or Loki or something. I have no problems making the pfx, ensuring the OIDs are correct, that the Issuer matches that in the AppManifest.xml, that the correct hash algorithm is used etc etc, and the thing just keeps spewing failure codes and writes absolutely nothing in the ETW logs either. 

I am going to just suggest that people continue to deploy by using Visual Studio unless someone else knows definitively why SignTool won't play ball with appx, appxsym nor msix files.

**Comment by zadjii-msft** [comment]
> 
> 
> Note the README _does_ say
> 
> > make sure you're building & deploying CascadiaPackage in Visual Studio
> 
> But I (and many others) have no idea how to do this (or why, since we already just built the app in powershell per the instructions).
> 
> It seems like there's a command missing in the powershell instructions, which tells us how to either a) install or b) run the Terminal.

(from @mikemaccana)

@adiviness How do you deploy Cascadia?

**Comment by DHowett-MSFT** [comment]
Duping to #926 (more info in there)
