### ISSUE TITLE
MRU mode: when you close a tab, it goes to the nearest adjacent instead of the last used

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#8550]
As in the title: tab closing logic doesn't take the MRU order into account.
Might be a feature, rather than a bug, if we consider MRU as a property of TabSwitcher only

**Comment by Don-Vito** [comment]
I will try to solve it

**Comment by Don-Vito** [comment]
I guess it is silly idea.

**Comment by DHowett** [comment]
I’ve actually kinda found myself being surprised when it _didn’t_ use MRU on close. Maybe there’s a case to be made for having it do so?

**Comment by DHowett** [comment]
@zadjii-msft if you agree, yank triage. Backlog, bug, p3.

**Comment by zadjii-msft** [comment]
Honestly yea, I like this. I'll yank triage. Heck, let's put it in 2.0.

**Comment by Don-Vito** [comment]
> 
> 
> Honestly yea, I like this. I'll yank triage. Heck, let's put it in 2.0.

@zadjii-msft - why 2.0? I can try to do it earlier :smile:

**Comment by zadjii-msft** [comment]
In my head I thought "why bother with 2.0, Don-Vito will probably have the PR out before lunch :P"

I'll stick you as the Assignee if you're interested 😄

**Comment by Don-Vito** [comment]
@zadjii-msft - I absolutely interested! Unfortunately, it won't happen before launch - all these holidays and family for some reason constantly interfere with focusing on what is really important :smile:

**Comment by zadjii-msft** [comment]
Lol don't worry about it. We're **all** about to take the rest of the year off. So it won't be reviewed before the new year anyways 😆

**Comment by Don-Vito** [comment]
@zadjii-msft - as expected, it didn't make it for lunch - hope it made it for dinner..
