### ISSUE TITLE
Auto tmux on startup fails with error "Not a terminal"

### ISSUE THREAD

**Issue by jediahkatz** [microsoft/terminal#8553]
# Environment

```none
Windows build number: 10.0.19041.630
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?

I am running `zsh` 5.8 (with `oh-my-zsh`) in WSL 2.
```

# Steps to reproduce

1. Add the following to `~/.zshrc`:
```
# Always work in a tmux session if tmux is installed
# Based on https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
    tmux new-session -A -s main; exit
  fi
fi
```
2. Set Windows Terminal default to WSL and set default shell to `zsh`.
3. Try repeatedly opening Windows Terminal (if it opens successfully, then do CTRL+D and try again).

# Expected behavior

Windows Terminal should always open normally with `zsh` inside `tmux`.

# Actual behavior

Windows Terminal frequently fails on startup with:
```
open terminal failed: not a terminal

[process exited with code 1]
```

**Comment by skyline75489** [comment]
Does this only happen with zsh? How often does this fail if you try it repeatedly

**Comment by jediahkatz** [comment]
I was unable to reproduce this with vanilla bash by putting the same code in my `.bashrc`.  I would say it fails about 1/3 of the time... you need to actually make sure the tmux session closes (rather than just detaching) in order to reproduce this exact error, although sometimes if you just detach you can still get a different error. 

Right now I am using a temporary workaround that automatically opens a new Windows Terminal window when tmux fails, basically "trying again" -- so far, it seems like tmux never fails the second time around (in the new window). Also, if you modify the `.zshrc` to not `exit` after tmux fails, then you can just run `tmux new-session -A -s main` manually in the terminal and it also seems to never fail.

**Comment by DHowett** [comment]
Thanks for the report! As far as I can tell, this is either a WSL or tmux issue. The terminal presents the same interface to all client applications, on all startups -- that of an interactive Windows Console console session. This would be the same as running `conhost wsl` repeatedly -- the window might just disappear too quickly to be seen.

This would probably be a good issue to file [on the WSL repo](https://github.com/microsoft/wsl).
