### ISSUE TITLE
Provide support for changing tab order by dragging

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/terminal#8555]
# Description of the new feature/enhancement

Provide support for changing tab order by dragging so that we can re-order them based on how we want to, not the order in which we've opened them.

# Proposed technical implementation details (optional)

N/A

**Comment by DHowett** [comment]
You can already do this, unless you are an administrator (in which case there’s a weird Windows bug that prevents this from working. We’re working with the team that owns drag/drop to figure out a way around that.)

**Comment by tomkerkhove** [comment]
Can we keep it open to trackthat weird bug thingy or can I subscribe somewhere on it? Because that's what I'm seeing.

**Comment by Don-Vito** [comment]
@tomkerkhove - if this happens when terminal is running elevated, you can track it in #6661

**Comment by tomkerkhove** [comment]
Thanks!
