### ISSUE TITLE
The parameter is incorrect.

### ISSUE THREAD

**Issue by killz0ne** [microsoft/terminal#8559]
Hi team,

I just installed Terminal app from store.
But app can't start. It throw exception:

_[Window Title]_
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

_[Content]_
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

**The parameter is incorrect.**

**Comment by zadjii-msft** [comment]
Which version of Windows?

Is you r issue the same as any of [these issues](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22The+parameter+is+incorrect%22+is%3Aclosed)?

**Comment by killz0ne** [comment]
It is v.1909, OS build 18363.1198.

And I try to start the terminal with -m and --minimized --focused
parameters.
But it didn't work.

**Comment by zadjii-msft** [comment]
Well that makes sense - `--minimized` isn't supported (yet) 😄 

https://github.com/microsoft/terminal/blob/a1f42e87a8f7670a405f9df38ee1803db76fc516/src/cascadia/TerminalApp/AppCommandlineArgs.cpp#L163-L172

See also /dup #7374

**Comment by killz0ne** [comment]
That's cool, but I have the same error.
