### ISSUE TITLE
Preview all tabs in taskbar

### ISSUE THREAD

**Issue by ks2k2d** [microsoft/terminal#8561]
# Description of the new feature/enhancement

With sessions toward multiple servers it would allow to view if something is happening on any of them without the need to switch between tabs.

# Proposed technical implementation details (optional)

Show preview of all tabs in taskbar.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #687 for more discussion.

/dup #687
