### ISSUE TITLE
Add a shortcut to restart the console

### ISSUE THREAD

**Issue by ta1fukawa** [microsoft/terminal#8567]
# Description of the new feature/enhancement

In Setting.json, set "ssh cinnamon@roll" for "commandline" and start the terminal, and when it exits with a timeout, `process ended with exit code 255` will be displayed.
In this case, I have to reopen the pane again to connect again.
So, I would like you to add a shortcut to restart the console.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3726 for more discussion.

/dup #3726 

See also  #4772
