### ISSUE TITLE
Tabs in title bar are cut off when scrolling the tabs + tabs not scrolling automatically

### ISSUE THREAD

**Issue by steinm07** [microsoft/terminal#857]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
**Microsoft Windows [Version 10.0.18898.1000]**
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
[Video demonstration of both issues below](https://youtu.be/SL61SMN4baI)
    - A newly created tab doesn't scroll the tab bar to the end - could possibly be a config variable
    - When using tabs in the title bar and creating a new partially hidden tab, the tab gets cut off.

* What's wrong / what should be happening instead:
    - The tab should not be cut off.

**Comment by zadjii-msft** [comment]
@teaP might be interested in this

**Comment by steinm07** [comment]
I just pulled this repo and recompiled, and it works fine. But please test it for yourself before closing this issue, because it may break again in the next commmit. 😀

**Comment by krzysdz** [comment]
I've just experienced the same issue, but in my case it also caused some tabs not to be displayed at all.
The invisible and cut off tabs appear again after resizing the window.

Details:
 - Commit: b9d83ba
 - Windows build: 18362.145

**Comment by ArtexJay** [comment]
My tab is not even scrolling on my computer. If i have too many tabs open I just can access it until i close a few tabs.
Also it would be great if the tabs would only display the name and not the directory, so for Command Prompt tab it could say CMD, or Command, for Ubuntu terminal it could say Ubuntu, same for any other Linux terminal, for Powershell it could just say Powershell.
Having the entire directory in the tab feels and looks strange.
