### ISSUE TITLE
Problem with a change in the defaul.json

### ISSUE THREAD

**Issue by plak-plak-plague** [microsoft/terminal#8570]
Hey. I have a problem with a change in the default.json. There is no permission to open this file even though I opened notepad as administrator. I was looking for a solution to the problem on the Internet and nothing works.

![image](https://user-images.githubusercontent.com/48829865/101993519-5f039f80-3ccc-11eb-93c8-057a6326cc07.png)

**Comment by DHowett** [comment]
You are not supposed to edit that file. Put your own options in your own `settings.json`.

**Comment by DHowett** [comment]
If you manage to edit that file, it will be ignored. Do not edit that file.
