### ISSUE TITLE
Drag & Drop folder on Windows Terminal problems with Window screen scaling (HDPI)

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#8571]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.685]
Windows Terminal version (if applicable): 1.4.32.43.0
```

# Steps to reproduce
- Set Windows display scaling to 200% (I am using a Surface Book: this is the default scaling: I never changed it)
- Open a Windows Terminal Window
- Try to drag and drop a folder from Windows Explorer to the Windows Terminal Window

# Expected behavior
Dropping the folder anywhere in the Terminal window should work.

# Actual behavior
It only works in the upper left area of the window: dropping on the right/bottom of the window isn't allowed.

Note: the area where the drop works appears to correspond to the size of the window without the Window scaling. Disabling the Windows screen scaling makes the drop area work as expected.

Video: https://www.youtube.com/watch?v=Cs9bf-yAzRg

As you can see: depending on the position of the dragged element inside the Terminal window, drag & drop is allowed or forbidden.

**Comment by DHowett** [comment]
Thanks for the report. Unfortunately, we've traced this back to a platform limitation. I know, that sucks.

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/2101

**Comment by warpdesign** [comment]
@DHowett Sad :( Does it mean every app using XAML are having the same problems? Any ETA for WinUI 3?

**Comment by zadjii-msft** [comment]
Only "XAML Islands" apps (Win32 apps using XAML, not UWP apps) will have this problem. Unfortunately, DHowett and I don't work on the WinUI team, so we don't really comment on the release schedule for WinUI 3 (because we don't know it 😜)
