### ISSUE TITLE
Pressing tab once in fish, bash, zsh inside Ubuntu acts as If pressing tab twice

### ISSUE THREAD

**Issue by asolopovas** [microsoft/terminal#8575]
# Environment
Platform     ServicePack  Version      VersionString
--------       -----------     -------      -------------
 Win32NT  10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
Ubuntu 20.04

# Configuration 
```js
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
  "$schema": "https://aka.ms/terminal-profiles-schema",
  "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
  "alwaysOnTop": true,
  "profiles":
  {
    "defaults":
    {
      "fontFace": "Inconsolata Nerd Font Mono",
      "fontSize": 12,
      "colorScheme": "Legacy",
      "initialRows": 50
    },
    "list": [
    {
      // Make changes here to the powershell.exe profile
      "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
      "name": "Windows PowerShell",
      "commandline": "powershell.exe",
      "hidden": false
    },
    {
      // Make changes here to the cmd.exe profile
      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
      "name": "cmd",
      "commandline": "cmd.exe",
      "hidden": false
    },
    {
      "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
      "hidden": false,
      "name": "Ubuntu",
      "source": "Windows.Terminal.Wsl",
      "startingDirectory": "//wsl$/Ubuntu/home/andrius"
    },
    {
        "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
        "hidden": false,
        "name": "Azure Cloud Shell",
        "source": "Windows.Terminal.Azure"
    }
    ]
  },
      "disabledProfileSources": [
        "Windows.Terminal.Azure"
    ],
  // Add custom color schemes to this array
  "schemes": [
  {
    "name": "Legacy",
    "background": "#14191f",
    "black": "#000000",
    "blue": "#F7FFC1",
    "brightBlack": "#555555",
    "brightBlue": "#4565AD",
    "brightCyan": "#8BE9FD",
    "brightGreen": "#50FA7B",
    "brightPurple": "#FF79C6",
    "brightRed": "#FF5555",
    "brightWhite": "#FFFFFF",
    "brightYellow": "#F1FA8C",
    "cyan": "#6272A4",
    "foreground": "#F8F8F2",
    "green": "#005CCB",
    "purple": "#6272A4",
    "red": "#FF5555",
    "white": "#aec2e0",
    "yellow": "#FFB86C"
  }],
  // Add any keybinding overrides to this array.
  // To unbind a default keybinding, set the command to "unbound"
  "keybindings": [
  {
    "command": "closeTab",
    "keys": ["ctrl+w"]
  },
  {
    "command": "newT
ab",
    "keys": ["ctrl+shift+t"]
  },
  {
    "command": "copy",
    "keys": "ctrl+shift+c"
  },
  {
    "command": "paste",
    "keys": "ctrl+shift+v"
  }
]
}
```
# Steps to reproduce
Pressing tab once in `fish`, `bash`, `zsh` inside Ubuntu acts as If pressing tab twice. 

# Expected behaviour
Tab should not be double-clicked when clicked once, PowerShell window does act in same manner. 

# Actual behaviour

![3kaK1BTf55](https://user-images.githubusercontent.com/6893216/102014088-1ee40180-3d4c-11eb-8f52-28bc006d38ec.gif)

**Comment by skyline75489** [comment]
Does this also happen with conhost, aka cmd.exe?

**Comment by zadjii-msft** [comment]
By any chance, did you do the `InputServiceEnabled` hack from https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424 ?

We've had reports in the past that causes tab to get sent twice: https://github.com/microsoft/terminal/issues/4448#issuecomment-648177283, #7598

See also #8253 or [any of these](https://github.com/microsoft/terminal/issues?q=is%3Aissue+InputServiceEnabled)

**Comment by asolopovas** [comment]
> Does this also happen with conhost, aka cmd.exe?

Yes it does happen with cmd as long as it is opened via "Windows Terminal" it works fine in default windows though.

**Comment by asolopovas** [comment]
> By any chance, did you do the `InputServiceEnabled` hack from [#4448 (comment)](https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424) ?
> 
> We've had reports in the past that causes tab to get sent twice: [#4448 (comment)](https://github.com/microsoft/terminal/issues/4448#issuecomment-648177283), #7598
> 
> See also #8253 or [any of these](https://github.com/microsoft/terminal/issues?q=is%3Aissue+InputServiceEnabled)

Touch input service is enabled...
![lqYXtkYNJS](https://user-images.githubusercontent.com/6893216/102252735-58f50500-3efe-11eb-8540-fd2254aed527.gif)

**Comment by asolopovas** [comment]
> By any chance, did you do the `InputServiceEnabled` hack from [#4448 (comment)](https://github.com/microsoft/terminal/issues/4448#issuecomment-617290424) ?
> 
> We've had reports in the past that causes tab to get sent twice: [#4448 (comment)](https://github.com/microsoft/terminal/issues/4448#issuecomment-648177283), #7598
> 
> See also #8253 or [any of these](https://github.com/microsoft/terminal/issues?q=is%3Aissue+InputServiceEnabled)

Thank https://github.com/microsoft/terminal/issues/7598 this solves my issue...

**Comment by DHowett** [comment]
So just confirming: you _did_ have `InputServiceEnabled` set to 0 in your registry, even though you answered the question above with a screenshot of services.msc and not regedit?"
