### ISSUE TITLE
Help building from source: I need conpty.dll and OpenConsole.exe

### ISSUE THREAD

**Issue by ndavidpsi** [microsoft/terminal#8576]
How do I build Windows Terminal from source in order to obtain those 2 files?

I need those because I want to fix an issue in my Alacritty build.

**Comment by ndavidpsi** [comment]
I am talking about the files mentioned in https://github.com/alacritty/alacritty/pull/4501

**Comment by j4james** [comment]
You can find the build instructions on the home page of this repo:
https://github.com/microsoft/terminal#developer-guidance

Once the build has completed, you should find the `conpty.dll` and `OpenConsole.exe` files in the `bin\x64\Release` directory (assuming a release build on a 64-bit architecture).

**Comment by ndavidpsi** [comment]
Thank you! I will try and let you know how it worked out

**Comment by ndavidpsi** [comment]
Do I really need VS2019 or would the VS Build Tools 2017 suffice?

**Comment by ndavidpsi** [comment]
Update: it worked out great, thanks! Even using the VS Build Tools
