### ISSUE TITLE
Snappy windowing with different Terminal windows

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/terminal#8578]
# Description of the new feature/enhancement
It would be awesome to be able to split/combine multiple windows to just one with more tabs and vice versa, the same that Chrome or other browsers have.

[Chrome Demo](https://streamable.com/v9uhjd)

[How Terminal works right now](https://streamable.com/ofhk11)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22drag+tabs%22+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1256 for more discussion.

/dup #1256

See also #5000
