### ISSUE TITLE
when is type a wrong command in cmd, and then type exit will give a msg "code 9009",and not give next prompt.

### ISSUE THREAD

**Issue by cangarooSJJ** [microsoft/terminal#8582]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment]
OK I have no idea what this is about. Can you post at least a screenshot or something?

**Comment by skyline75489** [comment]
Try to follow the issue template and do not just ignore it. Fill the issue template with necessary information will help everyone towards a basic idea of what's happening.

**Comment by cangarooSJJ** [comment]
[cid:image001.png@01D6D21B.EC00BE70]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Chester Liu<mailto:notifications@github.com>
发送时间: 2020年12月14日 13:19
收件人: microsoft/terminal<mailto:terminal@noreply.github.com>
抄送: cangarooSJJ<mailto:cangaroo_sjj@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [microsoft/terminal] when is type a wrong command in cmd, and then type exit will give a msg "code 9009",and not give next prompt. (#8582)


OK I have no idea what this is about. Can you post at least a screenshot or something?

―

**Comment by skyline75489** [comment]
Yeah...a lot of things do not work with email. I learned this a while ago.

**Comment by skyline75489** [comment]
If you're experiencing this:

![image](https://user-images.githubusercontent.com/4710575/102060838-a9506200-3e2d-11eb-83c9-0c607c3ac5f0.png)

This is expected. You can find out more in the documentation about [closeOnExit](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#how-the-profile-closes-when-exiting).

**Comment by zadjii-msft** [comment]
Yea, you gotta use the template friend. I'm guessing you're seeing what @skyline75489 mentioned. Or something like any of these [11 other threads](https://github.com/microsoft/terminal/issues?q=is%3Aissue+9009).

If you can provide some additional info, we'll be happy to reopen this and investigate further.

/dup #3869 #4263 #4573 #4627 #4736 #5003 #5214 #6518 #7836 #8172
