### ISSUE TITLE
Terminal crashes on startup when initial rows on screen (`initialRows` setting) is set too high

### ISSUE THREAD

**Issue by metathinker** [microsoft/terminal#859]
Using this commit: e3764b2081b74c67fb901b2c133380c5bd3787af

1. Make sure there is no existing Terminal settings file at: `%LocalAppData%\Packages\WindowsTerminalDev_8wekyb3d8bbwe\RoamingState\profiles.json`
2. Build Terminal with `tools\razzle.cmd & bcz`.
3. Open the OpenConsole.sln in Visual Studio, select debug/release and CPU architecture to match your build, and hit F5 to deploy and run the Terminal .appx package.
4. Open the newly created Terminal settings file, and change the `initialRows` setting from 30 to 1637.
5. Close and restart Terminal.

Observe that Terminal does not start at all. If you start Terminal under a debugger, you'll see that the release build crashes with an unhandled C++ exception. (I haven't tried the debug build.)

Setting `initialRows` to 1636 or less does not cause the problem, but setting it to 1637 (as above) or greater does cause it.

_Originally posted by @metathinker in https://github.com/microsoft/terminal/pull/843#discussion_r284818080_ - that PR does not fix or otherwise affect this bug.

**Comment by mKay00** [comment]
For me it crashes >= 820

**Comment by dkter** [comment]
For me it crashes >= 1559 at 100% scaling. Changing my primary display resolution doesn't change the result but changing the scaling does (my primary display is 1920x1080, I have two other displays but they don't seem to be relevant):

| Scaling | Max value of `initialRows` |
| -------- | ----------- |
| 100% | 1558 |
| 125% | 1246 |
| 150% | 1038 |
| 175% | 889 |

**Comment by dkter** [comment]
This definitely looks like an integer overflow issue. From https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/TermControl.cpp#L1119 it looks like the program crashes when `height` > 32728.0 (2^15 - 40).

It would be pretty reasonable to assume that window decorations (titlebar, borders, shadows) add up to 40px. Does Windows have a max window height?

**Comment by zadjii-msft** [comment]
Great work finding that @dkter. Seems like a simple enough fix for someone to submit a PR for :)

**Comment by dkter** [comment]
For consistency it might be helpful to use the existing `_ClampToShortMax` helper from #843, but it seems to be in `Terminal.cpp` -- is there a better place to put it?

**Comment by zadjii-msft** [comment]
@dkter usually for things like that, we'll throw them in `src/types/utils.cpp` (and `src/types/inc/utils.hpp`). That's kinda our dependency-free helper lib that's used by a ton of things.

**Comment by dkter** [comment]
I wanted to add unit tests, but I wasn't sure where to put them for the `WindowsTerminal` project?

**Comment by zadjii-msft** [comment]
Right now the only tests we have are in `src\cascadia\unittests_terminalcore`, and they only really test the "TerminalCore" project. I'm working on adding a test framework for the rest of the projects, but that's proving to be a bit harder that we hoped (see #1042 for _way_ more detail)

**Comment by Reelix** [comment]
Even though this bug is closed, it still exists in the newly released Version 0.6.2951.0
