### ISSUE TITLE
Click backspace to blink the window

### ISSUE THREAD

**Issue by juzi214032** [microsoft/terminal#8591]
# Environment

```none
Windows build number: 10.0.19041.572
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?  No
```

# Steps to reproduce
Use git bash, then hit the backspace key, and the window content area will blink
![](https://i.loli.net/2020/12/16/fbeAhawqU3JXLym.gif)

# Expected behavior
No flicker

# Actual behavior
Will flash

**Comment by j4james** [comment]
See issue #7200.

**Comment by DHowett** [comment]
Yep! By design, see /dup #7200

**Comment by juzi214032** [comment]
Problem solved! Thanks
