### ISSUE TITLE
byobu tmux press shift up, crash

### ISSUE THREAD

**Issue by sbarzaghialteaup** [microsoft/terminal#8593]
# Environment

```none
Windows build number:
Microsoft Windows [Versione 10.0.19041.630]
Windows Terminal version (if applicable):
1.4.3243.0 and 1.5.2011.19002
release 1.3.2009.21001 don't have the problem

Any other software?
wsl ubuntu
byobu tmux installed inside ubuntu
```

# Steps to reproduce
launch windows terminal
wsl ubuntu 20.03
install byobu: "apt install byobu"
launch byobu: "byobu"
split screen: press "shift f2" 
goto to split 1: press "shift+up arrow"

# Expected behavior
Focus on split 1

# Actual behavior
Crash

Link to feedback crash:
https://aka.ms/AAamszg

**Comment by skyline75489** [comment]
I can not reproduce this. Can you share your settings? Does this happen with good old cmd.exe?

**Comment by DHowett** [comment]
Thanks for the feedback link! Unfortunately, it didn't come back to us with crash information.

Would you mind running the trace capture steps from https://github.com/microsoft/terminal/issues/8358#issuecomment-731670909/? Thank you!

**Comment by sbarzaghialteaup** [comment]
> I can not reproduce this. Can you share your settings? Does this happen with good old cmd.exe?
Settings: https://cl1p.net/issue8593

No problems with cmd.exe and no problems with windows terminal 1.3.2009.21001


> Thanks for the feedback link! Unfortunately, it didn't come back to us with crash information.
> 
> Would you mind running the trace capture steps from [#8358 (comment)](https://github.com/microsoft/terminal/issues/8358#issuecomment-731670909)? Thank you!

Sent to you the terminal.etl file just now, subject of the email is "Windows terminal issue 8593"

Thank you for support

Regard,
Sam

**Comment by DHowett** [comment]
Thanks! Looks like it's an issue in character rendering. That's curious.

Do you have a fancy prompt set up? What's your byobu config look like? It doesn't seem like this reproduces with stock configs.

**Comment by sbarzaghialteaup** [comment]
No fancy prompt.
The problem was releated to clipboardmaster hotkeys , https://www.clipboardmaster.com/
Maybe I upgraded to 1.4 the same day of clipboardmaster installation.
Solution, removed clipboardmaster.

Thank you for support
Regards,
Sam

**Comment by DHowett** [comment]
Wow! Thanks for the info.
