### ISSUE TITLE
replace the default conhost with new terminal

### ISSUE THREAD

**Issue by fyc132** [microsoft/terminal#8599]
![world](https://user-images.githubusercontent.com/16433238/102388121-48cb4b80-400c-11eb-8110-2413ecd856e3.gif)

1.

we should build newhost to forward execute
![image](https://user-images.githubusercontent.com/16433238/102385009-4a931000-4008-11eb-917d-4c9822bfc537.png)
build and copy to system32 dir.
![image](https://user-images.githubusercontent.com/16433238/102385168-7d3d0880-4008-11eb-8b33-1853d057b79a.png)

2.
when the console program starts. the condrv.sys will create conhost process and modify the process command line.
![image](https://user-images.githubusercontent.com/16433238/102385470-d6a53780-4008-11eb-96a1-db702afeb4d4.png)
we should modify the path to our newhost.
![image](https://user-images.githubusercontent.com/16433238/102385575-fb011400-4008-11eb-9041-bbb30ffd8d10.png)
build the driver and load.

3.
set HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Windows\ErrorMode to val 2. ignore the error windows diag.
![image](https://user-images.githubusercontent.com/16433238/102385745-2f74d000-4009-11eb-9a6b-52c068b9456a.png)

4.
end

**Comment by DHowett** [comment]
Thank you. We are working on an official solution to this in /dup #492.

**Comment by DHowett** [comment]
**I do not recommend patching OS files, especially the console driver, to accomplish this.**
