### ISSUE TITLE
Increase compatibility with xterm's supported terminfo capabilities

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/Terminal#86]
_From @mqudsi on July 18, 2017 2:14_

I know that conhost has recently undergone a great number of improvements to improve the compatibility with WSL applications, and really appreciate the dramatic changes and increased capabilities in 15063 as compared to the initial release.

If it's not out of the question, these are some useful xterm key mappings that are missing in `15063.483`. This isn't by any means an exhaustive list, but just a few that I've run into:

* `back tab` (shift + tab). Should be `\E[Z`, currently returns `^I` (regular tab). Supporting this enables backwards navigation in any command line interface presenting lists (shell completions, vim, etc)
* `ctrl + bkspc`: as far as I can tell, this should generate the value in (`^H`, `^?`) that is not generated by bkspc (currently bkspc generates `^?`, so ctrl+bkspc should generate `^H`. This will allow Windows-compatible delete-previous-word operations. Currently, `ctrl+bkspc` returns the same thing as `backspace`.
* `ctrl+/` currently generates (as far as I can tell) no codes at all. It should return the same as `^_` (`0x1f`). This is mapped to undo for a lot of console applications (emacs-compatible) and is a common user shortcut in vim.

An awesome one to have would be `<ctrl+tab>`, but there's no agreed upon code for that, as far as I can tell.

Some references:

* http://invisible-island.net/xterm/terminfo.html
* http://pubs.opengroup.org/onlinepubs/7908799/xcurses/terminfo.html
* ftp://invisible-island.net/shuford/terminal/swedish_vt102_codes.txt
* http://www.ibb.net/~anne/keyboard.html

_Copied from original issue: Microsoft/WSL#2350_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on July 18, 2017 16:18_

Lemme take a look, I thought we implemented those, but they may have regressed when I added support for arrows+modifier.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on July 18, 2017 17:25_

> back tab (shift + tab). Should be \E[Z, currently returns ^I (regular tab). Supporting this enables backwards navigation in any command line interface presenting lists (shell completions, vim, etc)

Whoops, looks like I only added support for parsing a `\E[Z`, but not also sending it.

> ctrl + bkspc: as far as I can tell, this should generate the value in (^H, ^?) that is not generated by bkspc (currently bkspc generates ^?, so ctrl+bkspc should generate ^H. This will allow Windows-compatible delete-previous-word operations. Currently, ctrl+bkspc returns the same thing as backspace.

I concur that we're not sending `C-h` on `Ctrl+Bkspc`, which is different from xterm et al. Though, I don't think that `Ctrl+Bkspc` is usually bound to delete-previous-word (or `backward-kill-word`). It does appear that typically `Alt+Bkspc` is commonly also bound to delete-previous-word, and that does work. 

> ctrl+/ currently generates (as far as I can tell) no codes at all. It should return the same as ^_ (0x1f). This is mapped to undo for a lot of console applications (emacs-compatible) and is a common user shortcut in vim.

I was not aware of that.  Seems pretty straightforward to me.

<hr>

These all look like pretty reasonable requests to me. I'll get started on them, but I'm not sure they'll be able to get in for this release.

**Comment by bitcrazed** [comment]
_From @mqudsi on July 18, 2017 17:39_

@zadjii-msft thanks a bunch! Really appreciate it!

**Comment by bitcrazed** [comment]
_From @mqudsi on September 17, 2017 17:22_

@zadjii-msft could we possibly add alt+del to that list? The delete key sends `\e\[3~`, alt-del under xterm sends `\e\e\[3~` (you can try it out under putty with, I think, the default key bindings). It can be used to delete the next word (complement to alt+bkspc).

**Comment by bitcrazed** [comment]
_From @zadjii-msft on September 18, 2017 15:54_

No problem! That should have probably bee added a while ago, my bad. Added to the others.

**Comment by bitcrazed** [comment]
_From @mqudsi on September 18, 2017 16:34_

@zadjii-msft  Thanks a bunch. Additionally, `ctrl+w` does not seem to be sent; it seems to only send `w` in my testing.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on September 18, 2017 16:39_

@mqudsi  Well that's odd. Ctrl+W seems to be just fine on mine end. I just tested in bash and emacs and both seemed to pick it up just fine. Are you sure there's nothing in a configuration somewhere (.inputrc, .tmux.conf, .vimrc, etc) that might be eating the C-w?

Pressing Ctrl+V, Ctrl+W in bash:
![image](https://user-images.githubusercontent.com/18356694/30553149-2367773c-9c55-11e7-8496-f5495ea7882a.png)


Pressing Ctrl+H, k, Ctrl+W in emacs:
![image](https://user-images.githubusercontent.com/18356694/30553177-3da207ac-9c55-11e7-9bc1-789f3359c4e4.png)

**Comment by bitcrazed** [comment]
_From @mqudsi on September 18, 2017 16:54_

I can't get it to work in even in bash, launched directly without any customization. I thought maybe it was related to "insert mode" or "enable ctrl key shortcuts" but that does not seem to be the case.

I'm still on Creators Update, perhaps this was fixed in a build since then? (Presuming you're running something more recent.)

I use demo_altkeys from the ncurses-examples package (not installed to PATH by default, found under `/usr/lib/ncurses/examples/demo_altkeys`) to test key sequences; I've found it to be a reliable alternative to `showkeys` (which is broken under WSL because of its incorrect tty tests).

**Comment by bitcrazed** [comment]
_From @mqudsi on September 19, 2017 17:24_

I apologize, the `ctrl+w` issue was due to a Windows program running in the background that was globally intercepting (and then selectively forwarding) that particular key sequence.

**Comment by bitcrazed** [comment]
_From @chradcliffe on December 20, 2017 20:41_

I am experiencing a similar issue with `Alt-Backspace` in terminal emacs on WSL.

In emacs, `C-h k Backspace` shows `Backspace` bound to `DEL` (i.e. `^?`), but `C-h k Alt-Backspace` shows `Alt-Backspace` bound to `Ctrl-Alt-h`. 

`Alt-Backspace` works fine in the shell, since `Ctrl-h` is interpreted as traditional Backspace (delete previous char), but in emacs (where the delete sequence is `^?` and distinct from `Ctrl-h`) it seems to fall down.

I was wondering if this ticket is intended to cover the `Alt-Backspace` issue as well -- I was thinking it might be related to the `Ctrl-Backspace` issue mentioned above.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on January 11, 2018 17:54_

I just checked in some code to add support for these keystrokes. Should be on the way out to insiders over the next month.


@chradcliffe I believe the fix I checked in should also address `M-Bksp` as well as `C-Bksp`

**Comment by bitcrazed** [comment]
Should now be fixed in Win10 Spring 2018 Update. Let us know if this still repro's 1803 or newer builds

**Comment by chradcliffe** [comment]
I updated to 1803 and I am still seeing the issue with `M-Backspace`. I am using Emacs version 24.5.1 from 
the main Ubuntu repo. Running `C-h k M-Backspace` still shows help for `C-M-h`. In case it helps the value of `TERM` in my shell is `xterm-256color`. Let me know if there's any more information you need.

**Comment by mqudsi** [comment]
@bitcrazed I presume you meant 1809/RS5?

**Comment by CoryOwens** [comment]
@bitcrazed - I am on 1803 and still having this issue. 

Repeating @mqudsi's question from May: Did you mean 1809?

**Comment by bitcrazed** [comment]
1809 hasn't yet been released - was referring to Win10 Spring 2018 Update - 1803 … in which we _thought_ we'd fixed these issues. Looks like we may need to make further improvements here. 

Could I ask that you reply to this thread with specific keys/chords/combos that are still lacking/problematic on 1803 or later?

Many thanks.

**Comment by CoryOwens** [comment]
The only one I know of the top of my head is that `Ctrl+Backspace` still produces the same thing as just `Backspace`. I'll test other combinations later.

**Comment by mqudsi** [comment]
@bitcrazed @CoryOwens I have another machine that's running the latest official release (17134.165/1803) and can confirm that all of the following work correctly and with unique control codes:

* BKSPC (`0x7f`)
* CTRL+BKSPC (`0x8`)
* ALT+BKSPC (`0x1b,0x8`)
* CTRL+/ (`0x1f`)
* TAB (`0x9`)
* SHIFT+TAB (`0x161`)

CTRL+TAB cannot be distinguished from TAB, but that is understandable.

Tested with `demo_altkeys` from the ncurses examples package.

**Comment by CoryOwens** [comment]
I have confirmed I am on the same build and version (17134.165/1803).
![version](https://user-images.githubusercontent.com/8702020/43116119-71437b66-8ec3-11e8-8ec9-7336e1c4d272.PNG)
I launched Powershell, `ssh`ed into a Linux server and launched `demo_altkeys` and went through the same sequence as you. 
`Backspace`: `127`, `^?`
`Ctrl+Backspace`: `127`, `^?`
`Alt+Backspace`: `639`, `ESC-^?`
`Ctrl+/`: _Nothing_
`Tab`: `9`, `^I`
`Shift+Tab`: `9`, `^I`
![demo_altkeys_ps](https://user-images.githubusercontent.com/8702020/43116424-e7d79bee-8ec4-11e8-98af-a0dcb2fc16c0.PNG)
I then re-ran the same sequence using cmd, and got the same results.
![demo_altkeys_cmd](https://user-images.githubusercontent.com/8702020/43116402-be38766e-8ec4-11e8-9cec-1a25d0adead1.PNG)

 Then, to verify to myself that it wasn't an issue with my Linux box, or SSH, I did the same test using MinGW/msys, and got different results. 
`Backspace`: `263`, `KEY_BACKSPACE`
`Ctrl+Backspace`: `127`, `^?`
`Alt+Backspace`: `775`, `ESC-KEY_BACKSPACE`
`Ctrl+/`: _Nothing_
`Tab`: `9`, `^I`
`Shift+Tab`: `9`, `^I`
![demo_altkeys_mingw](https://user-images.githubusercontent.com/8702020/43116434-f8f65f14-8ec4-11e8-8991-71e907048216.PNG)

If there are any other tests or information I can provide to be helpful, just let me know.

**Comment by DHowett-MSFT** [comment]
Powershell/openssh-portable (the implementation for Powershell/Win32-OpenSSH) does [its own key translation](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/tncon.c#L339) from raw key events, and as such cannot be trusted. It does this, ironically, in "raw mode" (which seems to be engaged by ssh requesting a terminal.)

**Comment by DHowett-MSFT** [comment]
Here's a quick ~40-liner that'll show what a raw VT consumer will get:

```c++
#include <stdio.h>
#include <tchar.h>
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>

int main()
{
  HANDLE inputHandle = GetStdHandle(STD_INPUT_HANDLE);
  DWORD consoleMode = 0;
  GetConsoleMode(inputHandle, &consoleMode);
  consoleMode |= ENABLE_VIRTUAL_TERMINAL_INPUT;
  consoleMode &= ~
    ( ENABLE_PROCESSED_INPUT
    | ENABLE_ECHO_INPUT
    | ENABLE_LINE_INPUT
    | ENABLE_MOUSE_INPUT
    | ENABLE_INSERT_MODE
    | ENABLE_WINDOW_INPUT
    );
  SetConsoleMode(inputHandle, consoleMode);
  char buffer[16];
  DWORD read = 0;
  fprintf(stderr, "^Z TO EXIT\n--\n");
  while(ReadFile(inputHandle, &buffer[0], 16, &read, nullptr) && read != 0) {
    for(unsigned int i = 0; i < read; ++i) {
      const auto& c = buffer[i];
      fprintf(stderr, "%2.02x ", c);
      if(iscntrl(c)) {
        fprintf(stderr, "^%c", c + '@');
      } else {
        fprintf(stderr, "%c", c);
      }
      fprintf(stderr, "\n");
    }
    fprintf(stderr, "--\n");
  }
  return 0;
}
```

When I run this and press `backspace`, `ctrl+backspace`, `alt+backspace`, `ctrl+/`, `tab`, `shift-tab`, I get:

```
^Z TO EXIT
--
7f ^┐
--
08 ^H
--
1b ^[
08 ^H
--
1f ^_
--
09 ^I
--
1b ^[
5b [
5a Z
--
```

**Comment by DHowett-MSFT** [comment]
It'll also leave your console in an unpleasant state, as it does little to no state restoration 👍

**Comment by CoryOwens** [comment]
Yep, that shows it working correctly. Bash must be misinterpreting it somehow. Strange that it doesn't do that in msys, though. I'll have to do some more digging. Thanks.

**Comment by mqudsi** [comment]
@CoryOwens bash isn't the problem; as @DHowett-MSFT said, it's an SSH under Windows thing. `demo_altkeys` running under WSL/bash indicates the keys are recognized OK there.

**Comment by CoryOwens** [comment]
This SSH implementation issue would affect bash.exe (distributed with git) running on Windows in cmd?

**Comment by DHowett-MSFT** [comment]
[This](https://github.com/Alexpux/Cygwin/blob/4de8754bac676fc7f29082ccf8281b1c73ce629e/winsup/cygwin/fhandler_console.cc#L422) may be the culprit for git-for-windows and msys2. It looks like they're doing a raw key event translation similar to that of Win32-OpenSSH.

**Comment by CoryOwens** [comment]
Alright, thanks.

**Comment by asinha94** [comment]
bit late to the party but I'm having similar issues with a few of the `ctrl+H` commands under wsl. I use `ctrl-H`.  Typically this works out alright but in a recent build (not sure when) the keystroke is not registered with tmux and I always get the backspace instead. I have tested on a few different bash shells and the `C-H` always registers with Tmux, just not under wsl...

**Comment by albaropereyraatfayebsg** [comment]
Fantastic, glad someone is working on a fix. Is there a quick way to patch this? perhaps remapping the key in the init.el file? 

Please advise,

**Comment by zadjii-msft** [comment]
@albaropereyraatfayebsg Could you file a new issue with specific repro steps for whatever problem you're seeing? The issue at the core of this thread seems to have been resolved quite some time ago, and I'd rather not necro dead threads with unrelated information.

**Comment by albaropereyraatfayebsg** [comment]
@zadjii-msft How can I determine the version of terminal I am running, I have the same error. I hit back space and it generates ctrl + h . I had to program my keyboard to do a back button delete( <- + delete ) to mitigate the issue.

**Comment by zadjii-msft** [comment]
I'd suspect you're running conhost.exe, not the new Windows Terminal. Conhost's versions are tied directly to Windows version numbers. To find out what version of windows you're running, you can simply open up a new cmd.exe window:
![image](https://user-images.githubusercontent.com/18356694/57775063-ccf77780-76e1-11e9-92a6-ad39c73fe582.png)
