### ISSUE TITLE
Cannot type @[at] symbol without opening new tab

### ISSUE THREAD

**Issue by DarkEyeDragon** [microsoft/terminal#860]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.475]
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
I'm trying to connect to my linux server through SSH using PowerShell. However every time i try to type the @ [at] symbol it just opens a new window and doesnt type @ at all. I use AZERTY so for me the key combination is ctrl+alt+2 or altgr+2.
![image](https://user-images.githubusercontent.com/6131099/57877452-31b4ee00-7818-11e9-8385-d8d2e1a00379.png)

* What's wrong / what should be happening instead:
it should just type the @ symbol normally. I looked through the keybinds and theres not really something representing ctrl+alt combinations.

EDIT.
![image](https://user-images.githubusercontent.com/6131099/57878015-70977380-7819-11e9-9841-b37864be4c8b.png)
Seems like theres a shortcut defined already. Is there a way to change those?

Edit again... yeah nvm i'ma just close this issue haha.

**Comment by DHowett-MSFT** [comment]
(Just for anybody else coming to this issue: it looks like this is a third-party terminal emulator that is breaking @DarkEyeDragon's keyboard input.)
