### ISSUE TITLE
Powerline doesn't show glyphs when used within WSL2

### ISSUE THREAD

**Issue by ghosh-r** [microsoft/terminal#8606]
# Environment

```none
Windows build number:  Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0
WSL: WSL2
```

# Steps to reproduce

```bash
# installing powerline via pip3
sudo apt-get install python3-pip
sudo pip3 install powerline-status

# installing powerline fonts
sudo apt-get install fonts-powerline
```
Add the following line to `~/.bashrc`
```bash
# load powerline
if [ -f `which powerline-daemon` ]; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
fi
if [ -f /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh ]; then
    source /usr/local/lib/python3.8/dist-packages/powerline/bindings/bash/powerline.sh
fi
```

Set `"fontFace": "Cascadia"` in the appropriate place in the `settings.json` file. Tried with different values such as `"Cascadia Mono"`, `"Cascadia Code"`, and `"Cascadia Regular"`. (Cascadia Code fonts support Powerline glyphs.)

source the bashrc file or restart the terminal.
# Expected behavior

I am trying to use [Powerline](https://github.com/powerline/powerline) with proper glyphs displayed. Like this shown in [the Windows Terminal docs site](https://docs.microsoft.com/en-us/windows/terminal/)-

![](https://docs.microsoft.com/en-us/windows/terminal/images/overview.png)

Refer to the left pane.
# Actual behavior

Glyphs used by Powerline are not appearing. Seeing question marks instead.
![image](https://user-images.githubusercontent.com/58001482/102512502-1e32ce80-40b0-11eb-976f-23be40f77cc0.png)

**Comment by zadjii-msft** [comment]
The Cascadia fonts don't support powerline characters by default. You'll have to use one of the "Cascadia PL" variants. 

See [this docs page](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup#set-cascadia-code-pl-as-fontface-in-settings) for more details.

**Comment by ghosh-r** [comment]
@zadjii-msft thanks. It works now.

I use Cascadia Code in Linux- the regular variant, and it happens to support Powerline glyphs without any issues.

**Comment by DHowett** [comment]
It's really not supposed to. Only the "PL" variants of Cascadia support powerline glyphs. You may hve a font fallback set up that supports them.

**Comment by ghosh-r** [comment]
@DHowett that could be the case. But I did not do so explicitly.
