### ISSUE TITLE
Move MUX and Taef into a dev.azure.com/ms NuGet feed

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#861]
Only until they're fully publicly released.

**Comment by miniksa** [comment]
Oh. Justification: don't have the giant blobs of those packages in the freaking repository.

**Comment by Hades32** [comment]
Did you implement this yet? I'm (trying to) building Terminal in my own Azure DevOps pipeline and am getting errors for not being able to access "TAEF NuGet Feed"...

**Comment by DHowett-MSFT** [comment]
Not just yet. This issue will be closed when it's been implemented.
The "TAEF NuGet Feed" is only required for the "VSTest adapters," which are being moved out into the public TAEF package. That work is done, we just need to complete validation and consume the new package.

**Comment by DHowett-MSFT** [comment]
@miniksa I knew we had a workitem for this!

**Comment by miniksa** [comment]
> @miniksa Michael Niksa FTE I knew we had a workitem for this!

Aha!
