### ISSUE TITLE
 Crashing when using tabSearch triggered via shortcut Ctrl + N

### ISSUE THREAD

**Issue by qwertynik** [microsoft/terminal#8612]
# Environment

```none
Windows build number: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable):
Version: 1.4.3243.0
```

# Steps to reproduce

When triggering the tabSearch using a shortuct `Ctrl + N` the terminal crashes. Not always though.

# Expected behavior

Tab search popup should open

# Actual behavior

Sometimes instead of the tab search popup opening, the Terminal crashes.

# Additional Info
More often than not, whenever the terminal crashed, I had 4 tabs with SSH connections and one with Powershell. VPN turned on. So a total of 5 tabs. To me, this looks like a coincidence. 
PS: This information might not help in root-causing the bug. But adding it anyway, just in case it helps!

**Comment by qwertynik** [comment]
Would be willing to upload any log data if required. Adding steps on how to do so would be essential and helpful.

Thanks!

**Comment by skyline75489** [comment]
Is there any other software running in the background?

**Comment by qwertynik** [comment]
@skyline75489 
In the background via the terminal? If you are speaking about other apps running on windows, here are they:
- PHPStorm
- Chrome
- Firefox
- Airtable
- Google Chat App
- jMeter

**Comment by skyline75489** [comment]
Recently we received report about `clipboardmaster ` causing crashes. Back then `PowerToys` can also cause malfunction in the terminal. So yeah something like that, which might interferer keyboard, interaction, etc.

**Comment by qwertynik** [comment]
@skyline75489 
No such tool is currently being used the only exception being the new Clipboard tool. That allows me to paste items that were copied much earlier.
If there are any crash logs that could be shared securely that can be done.

**Comment by skyline75489** [comment]
Well the bot does not like me, but yeah. Normally people could use feedback hub like this https://github.com/microsoft/terminal/issues/8287#issuecomment-730827473

**Comment by zadjii-msft** [comment]
Yea, I'd follow the steps in that thread, including in [this link](https://github.com/microsoft/terminal/issues/8287#issuecomment-733893742)

**Comment by qwertynik** [comment]
@skyline75489 @zadjii-msft 
Thanks for sharing the steps. Here is the [feedback](https://aka.ms/AAanhx1). 
Hopefully, this is resolved at the earliest.

**Comment by qwertynik** [comment]
@skyline75489 @zadjii-msft 

Do let me know if any additional information is required in resolving this issue and making the Terminal app even better.

**Comment by DHowett** [comment]
Thanks again for the report, and the feedback hub link
! I just gave it a shot _a lot_ in the 1.6 preview, and I believe that one of @Don-Vito's _many_ command palette changes fixed it. I can't be sure, of course, but so much code changed in that area that it's going to be hard to correlate.

Please reopen this in a couple days if the 1.5 and 1.6 updates have the same problem.
