### ISSUE TITLE
RIS does not reset mouse mode state or encoding

### ISSUE THREAD

**Issue by amie42** [microsoft/terminal#8613]
Notes from @DHowett:
> In xterm, `RIS` disables mouse mode and (probably) resets the encoding.
> `DECSTR` _does not_

# Environment

```none
Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 1.5.3242.0 AND 1.4.3243.0

Debian 9.13 in WLS; RHEL7.8 on remote server
```

# Steps to reproduce
ssh connect to the remote server do some actual work there vim, gcc, gdb, the whole daily work sh**
After you're done with work, do not disconnect the remote connections, just put your windows Laptop to "Energy saving", remove it from the dock, put it into your bag and have a nice evening with the kids.
Next day resume the Laptop, click into the one of the still open terminal panes trying to reconnect the remote machine.
Try to scroll in the terminal

# Expected behavior
After Wakeup from standby, I'd expect to have all the normal mouse interaction. recall the ssh login command using [Cursor up] and resume work. Vim and terminal scrolling should work.

# Actual behavior
Any Mouse interaction with the terminal will spam the prompt with more or less random text (same button press creates different input in different panes) 
Wheel scrolling is impossible as just spams the promt.
Only solution: kill all the panes, have new ones. 
I could live with issues like these if they would be solvable with the bash `reset` command. 
The behavior is not always reproducible. some panes work just fine. Others show even more strange behavior like flashing on mouse interaction.

**Comment by skyline75489** [comment]
So, are you using mosh or just using plain ssh? I'd recommend mosh if you need to resume work smoothly.

**Comment by amie42** [comment]
I'd love to use mosh but its not compatible with our setup. I'm new on this job maybe I'll make them to implement some improvements. That would be definitely one. Another one would be: get rid of Windows Workstations at all. But for now, I'm glad I have Windows Terminal at least.

**Comment by skyline75489** [comment]
I'm not a pane user so I don't have much say about this issue. I believe someone in the team will have more insights.

**Comment by amie42** [comment]
Yeah, maybe I should return to tmux.

**Comment by zadjii-msft** [comment]
What random text are you seeing exactly? We might be able to better diagnose if we knew what the text was exactly. 

Are you using mouse mode in vim? Does pressing <kbd>↟</kbd> _not_ recall the previous command? Because that should work even if the `ssh` session didn't exit cleanly.

It sounds to me like something on the remote machine is requesting mouse mode input, then the connection is being broken, leaving the Terminal in mouse mode without `bash` expecting it. 

This might also be related to #381, maybe a little bit of #8020,

**Comment by amie42** [comment]
Yes, I'm using mouse mode in vim
↟ does work. but I don't use it as the terminal stays useless even after ssh reconnects
some example "random output":
` 9+#9+` (on left click)
` 2'#2'` (left click a couple of seconds later without even moving the mouse)
` 0.#0.` (left click after moving the mouse a little)
`<backtick>0.` (small scroll upwards)

It sounds you have a  great theory  as it's reproducible in Gnome Terminal 3.38.1 on my native debian that way as well. I had to kill -9 the ssh client though. 
Anything I could do from user perspective to reset the "mouse mode"? Maybe something for a bashrc?

**Comment by amie42** [comment]
In Gnome Terminal `reset` fixes the issue. this is probably the reason why I wasn't annoyed by that issue that much before

**Comment by oising** [comment]
@amie42 If you're on windows 10 and you have WSL installed, you can either run `reset` from there, or if you're running powershell / cmd or another windows shell, `wsl reset` will work. 

@zadjii-msft It would nice to build terminal reset a la tset(1) directly into windows terminal on the GUI.

**Comment by zadjii-msft** [comment]
I'm mildly concerned that `reset` doesn't fix this. I don't know how to check whatever `reset` is emitting off the top of my head, but if that works in `gnome-terminal` it should work in WT. I'd bet that there's some component of it that's being lost in the conpty layer, so the Terminal is still in mouse mode, but the client and conpty aren't.

**Comment by oising** [comment]
@zadjii-msft 

```text
reset - reinitialization
       When invoked as reset, tset sets the terminal modes to "sane" values:

       o   sets cooked and echo modes,

       o   turns off cbreak and raw modes,

       o   turns on newline translation and

       o   resets any unset special characters to their default values

       before doing the terminal initialization described above.  Also, rather
       than  using  the  terminal initialization strings, it uses the terminal
       reset strings.

       The reset command is useful after a program dies leaving a terminal  in
       an abnormal state:

       o   you may have to type

               <LF>reset<LF>

           (the line-feed character is normally control-J) to get the terminal
           to work, as carriage-return may no  longer  work  in  the  abnormal
           state.

       o   Also, the terminal will often not echo the command.
```
https://invisible-island.net/ncurses/man/tset.1.html

**Comment by oising** [comment]
if WT is xterm-color, it seems the reset string is:

```text
oisin@BEASTIEBOOK3:/mnt/c/Users/OisinGrehan$ infocmp xterm-color | grep rs[123].*
        rs2=\E[m\E[?7h\E[4l\E>\E7\E[r\E[?1;3;4;6l\E8, sc=\E7,
```

**Comment by zadjii-msft** [comment]
I guess I'm more concerned with whatever @amie42's client actually is emitting, rather than what it _should be_ emitting. I believe that WSL sets the TERM to `xterm256-color`, but who knows if it's getting changed before it's being used.

@amie42 could you share the output of ` infocmp | grep rs[123].*` from your Debian instance, without running `ssh`?

**Comment by amie42** [comment]
IIRC, `reset` on native Debian Gnome Terminal fixes the issue. In Windows Terminal it does not. I'm going to check back on Monday. But I won't even remotely touch a windows box in my spare time. Have a great weekend everyone!

**Comment by amie42** [comment]
From my native Debian Laptop: New Terminal Window. I never ran ssh from this process :
`infocmp | grep rs[123].*
	rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
`

**Comment by amie42** [comment]
Confirmed: `reset` in the windows terminal does not fix the issue: neither in version 1.5, nor in 1.4.
I'll post the output of  `infocmp | grep rs[123].*` of the Windows Terminal in a new comment

**Comment by amie42** [comment]
WT1.4: 
`
xterm-256color|xterm with 256 colors,
	colors#256, cols#80, it#8, lines#24, pairs#32767,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	rmso=\E[27m, rmul=\E[24m, rs1=\Ec\E]104\007,
	rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
`	
WT 1.5: 
`
	rmso=\E[27m, rmul=\E[24m, rs1=\Ec\E]104\007,
	rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
`

**Comment by amie42** [comment]
Any update here?  would you need any other input from my side?

**Comment by amie42** [comment]
The problem still persists in v1.5.10271.0

**Comment by amie42** [comment]
The Problem still persists in v1.5.10411.0

**Comment by amie42** [comment]
The Problem still persists in v1.7.1033.0

**Comment by zadjii-msft** [comment]
Alright, it's been a few months since I've looked at this thread, so lemme make sure I've got this right. The issue at hand is that when you enter energy saving mode, the `ssh` connection gets terminated. When that happens, the terminal is left in mouse input mode, despite the local shell not expecting it. `reset` usually would fix this scenario, but doesn't seem to in Windows Terminal. 

Am I missing anything?

**Comment by DHowett** [comment]
It looks like neither `DECSTR` nor `RIS` reset the mouse mode state. Thanks!

**Comment by DHowett** [comment]
Renamed appropriately, triaged to Terminal 2.0 and marked Help Wanted.

It also looks like for **xterm**, only `RIS` resets the mouse mode. `DECSTR` _does not_, and so we will not.

**Comment by DHowett** [comment]
@PankajBhojwani you may be interested in this. I'm gonna take triage off and move it up to 1.10 as we discussed for mouse mode changes!

**Comment by amie42** [comment]
I commented on the fix you might want to revisit that.

**Comment by amie42** [comment]
The fix works like a charm, thank you everybody!
