### ISSUE TITLE
Display has overlay or Screen looks cracked on menus and dropdowns and modals.

### ISSUE THREAD

**Issue by StevenTCramer** [microsoft/terminal#8620]
![image](https://user-images.githubusercontent.com/357219/102679360-e9269900-41e1-11eb-894a-d86b473f2f91.png)

# Environment

Microsoft Windows [Version 10.0.19042.685]
Windows Terminal Preview Version: 1.5.3242.0

# Steps to reproduce

Run terminal and select drop down or any other Modal.

![image](https://user-images.githubusercontent.com/357219/102679415-5afee280-41e2-11eb-8d05-9ded78f2fd9e.png)

**Comment by zadjii-msft** [comment]
I'm absolutely positive we've seen this once before, but I'm having a hard time finding the original issue. There was something wrong with WinUI and the CornerRadius. You can note that all the elements that are experiencing this artifact are ones where there should be a rounded corner.

**Comment by zadjii-msft** [comment]
I found it! This was previously /dup #6142, which is being tracked upstream at microsoft/microsoft-ui-xaml#2550. The WinUI team would definitely be interested in hearing from you. Thanks!
