### ISSUE TITLE
Resizing Terminal Scatter and make Duplicate Characters

### ISSUE THREAD

**Issue by garvit-joshi** [microsoft/terminal#8624]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19042.685]
Windows Terminal version (if applicable): 1.4.3243.0

Ubuntu: 20.04 WSL-2
```
In Ubuntu:
1. ZSH 
2. [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh)
3. [powerlevel10k](https://github.com/romkatv/powerlevel10k)

# Steps to reproduce
 1. Open Ubuntu 20.04  (WSL-2), with ZSH, ohmyzsh, powerlevel10k.
 2. When Resizing the window of Terminal, Characters scatter.

# Expected behavior

Resizing the window should not Scatter and Duplicate Characters.

# Actual behavior

![1 ter](https://user-images.githubusercontent.com/55401175/102692600-62ea7100-423a-11eb-90fc-b3cb9b6d7d4d.PNG)

![2  ter](https://user-images.githubusercontent.com/55401175/102692602-641b9e00-423a-11eb-8c8c-09c231ac0f27.PNG)

# Note
 **In Second Picture I just resized the window.**
 **Powerlevel10k uses Unicode Characters**

**Comment by j4james** [comment]
I suspect this is an example of the "exact wrap" bug. See issue #3088 and the various linked duplicates.

**Comment by zadjii-msft** [comment]
That looks right to me. Thanks @j4james!

/dup #3088
