### ISSUE TITLE
Unfinished UI in the title bar (new tab icon and drop down)

### ISSUE THREAD

**Issue by iseeghosts** [microsoft/terminal#8627]
There seem to be unfinished UI elements in the tile bar, namely new tab (plus icon) and dropdown icon. As I understand it, the core team is going for chromium style title bar - if so, there should be a uniform padding and the icon itself should have a highlighted square with rounded corner in background when hovered,
![image](https://user-images.githubusercontent.com/34771316/102715722-685cbf80-42fd-11eb-9bec-5bb2c4c075b4.png)
instead it appears there is no space netween the existing tabs and new tab icon when hovered or a clear background.
![image](https://user-images.githubusercontent.com/34771316/102715715-5d099400-42fd-11eb-849d-b96eca237fbe.png)
Also, there seem to be a weird bug (maybe?) when I click on the dropdown as both the new tab and dropdown are highlighted with an unusual background.
![image](https://user-images.githubusercontent.com/34771316/102715730-701c6400-42fd-11eb-8ce4-9af929c266dc.png)

# Environment

Windows build number: Windows 10 version 2004, build 21277.1000
Windows Terminal version (if applicable): Windows Terminal Preview / Version: 1.5.3242.0

# Steps to reproduce
Simply click on plus icon, or dropdown

# Expected behavior
![image](https://user-images.githubusercontent.com/34771316/102715865-1cf6e100-42fe-11eb-936f-262b3582d678.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/34771316/102715869-254f1c00-42fe-11eb-8deb-1d08831ce19c.png)

**Comment by DHowett** [comment]
No, that UI is definitely finished. The split button control in the Windows UI toolkit highlights both halves when the dropdown is open, and it has tab styling so that it lines up with each tab (including spacing). Thanks for the report!

**Comment by iseeghosts** [comment]
But the new tab overlaps or touches the existing tabs, shouldn't there be some padding. I mean there is a clear space separating new tab icon and dropdown. I mean it looks bad, should I expect changes to UI anytime soon?
