### ISSUE TITLE
C setlocale() not setting codepage

### ISSUE THREAD

**Issue by clinton-r** [microsoft/terminal#8630]
# Environment

Microsoft Windows [Version 10.0.19041.685]
Windows Terminal Version: 1.4.3243.0
(Also occurs in conhost)

Any other software?
Microsoft Visual Studio Community 2019 Version 16.8.3

# Steps to reproduce

Compile this in Visual Studio, and run it in Windows Terminal/cmd or conhost/cmd:

#include <stdio.h>
#include <locale.h>
#include <windows.h>

int main(void)
{
    UINT oldCP = GetConsoleOutputCP();

    if (!setlocale(LC_ALL, ".utf-8"))
    {
        printf("setlocale() failed!\n");
    }

    printf("old CP = %d, new CP = %d\n", (int)oldCP, (int)GetConsoleOutputCP());
    printf(u8"I8Σπ\n");

    SetConsoleOutputCP(oldCP);
    printf("Restored CP to %d\n", (int)GetConsoleOutputCP());

    return 0;
}

# Expected behavior

Reference: https://docs.microsoft.com/en-us/cpp/text/locales-and-code-pages?view=msvc-160#:~:text=The%20locale%20and%20code%20page,is%20used%20for%20Japanese%20Kanji.

Expected output:
old CP = 850, new CP = 65001
I8Σπ
Restored CP to 850

# Actual behavior

Actual output:
old CP = 850, new CP = 850
I8Sp
Restored CP to 850

# Extra Notes

Hi,
If I use SetConsoleOutputCP(65001) instead of setlocale(LC_ALL, ".utf-8"), then it does work correctly.
Thanks!

**Comment by DHowett** [comment]
Ugh! I'm sorry we missed this in our triage queue. It's now been six months.

I think that this is an issue with the CRT, which would be better to file on devcom ([developer community](https://developercommunity.visualstudio.com/home)). Unfortunately, we don't have any control over whether setlocale passes through to the console CP.

This seems, on its front, to be related to the UTF-8 issue in #4551. They probably don't want to make setlocale do that until input works properly?

/dup #4551

tagging external as well -- for visibility. sorry!

**Comment by eryksun** [comment]
The decision to modify the console session lies with the application. Typically this is a user-driven setting via "chcp.com" or the registry "CodePage" value in "HKCU\\Console\\\<session title\>".  It wouldn't be as much of an issue if modifying the console I/O code pages only affected the current process and child processes. As it stands, the C runtime is justified in choosing to not modify the console session automatically. Instead, if it isn't using the default "C" locale, it addresses the mismatch as best as it can via translation between locale multibyte text and console multibyte text.
