### ISSUE TITLE
Out for the holidays! ❄😴🐱‍💻🥳🎄😊

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#8633]
Most of the Terminal team is taking some much needed vacation through the remainder of the year. Thank you for being patient while we relax, recharge, and return to a normal responsiveness in January ~2021~ 2024. In the meantime feel free to continue to pose questions, open issues, and make feature requests - you just may not get a response right away.

**Comment by movenight** [comment]
新年快乐

**Comment by itsme-alan** [comment]
I will rewrite the [Powerline setup docs](https://docs.microsoft.com/windows/terminal/tutorials/powerline-setup) to use [oh-my-posh v3](https://github.com/JanDeDobbeleer/oh-my-posh3/). This is my Christmas gift for the Awesome Terminal Team 🎉
