### ISSUE TITLE
Dividing line between panes when setting "theme" to be "dark"

### ISSUE THREAD

**Issue by ppwetcc** [microsoft/terminal#8635]
<img width="739" alt="屏幕截图 2020-12-22 161713" src="https://user-images.githubusercontent.com/42940597/102865735-2d7b9880-4471-11eb-9998-3de8802dfaca.png">
The dividing line between panes is still on light mode when set to dark mode ("theme": "dark"). But when set to be consistent with the system ("theme": "system"), and set light mode on the system, the dividing line is actually on dark mode...

**Comment by Don-Vito** [comment]
Please review if https://github.com/microsoft/terminal/issues/3917 already covers this.

**Comment by DHowett** [comment]
It does.

thanks!

/dup #3917
