### ISSUE TITLE
Launch Terminal in Snap Right mode

### ISSUE THREAD

**Issue by hrishikesh-kadam** [microsoft/terminal#8636]
# Description of the new feature/enhancement

I would like to snap the terminal in Snap Right or pinned to the right half of the screen.

Currently, I am able to do by <kbd>Win</kbd> + <kbd>Right</kbd> followed by <kbd>Esc</kbd>.

In version 1.4 there is no appropriate setting to do it.
I have read all the launch-related settings from the [Launch settings Doc](https://docs.microsoft.com/en-in/windows/terminal/customize-settings/global-settings#launch-settings).

I have also tried the following for my 1920 x 1080 screen - 
```json
{
    "initialPosition": "960,0",
    "initialCols": 76,
    "initialRows": 40
}
```
But I am unable to resize it the way Snap Right does it perfectly.

It would be helpful if the team adds two more `launchMode` - `snapLeft` and `snapRight`.
```json
{
    "launchMode": "snapRight"
}
```

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Because snapping is an inherent property of the window manager, I do not believe an application can request it. Sorry.
