### ISSUE TITLE
Terminal tabs can become very sluggish/unresponsive 

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#8640]
# Environment
```
Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal Preview Version: 1.5.3242.0

```

# Steps to reproduce

Open a windows terminal with multiple tabs (In my case 4 powershell tabs).  At least one of the tabs should produce large amounts of output.

# Expected behavior
Switching between tabs should be fast and fluid

# Actual behavior
Over time (6-24 hours) , the terminal becomes slower and slower to respond to clicks on the tab headers - eventually it can take >10 seconds to switch tabs after a click.  The '+' and "open menu" controls in the title bar are similarly unresponsive.

Even if all the tabs are removed and new empty tabs are added, switching remains extremely slow.  Note that the problem is limited to the particular terminal instance though - if another instance is opened on the same machine, it is performant and other applications are responsive.  Task manager shows no obvious CPU/Memory load.

**Comment by NeilMacMullen** [comment]
The issue also affects keyboard input - when typing into the terminal keystrokes can take a couple of seconds to appears.  As described above, other terminal instances and applications are not affected.

**Comment by skyline75489** [comment]
We have seen similar reports, noticeably #7710. It's holiday season now, so the response from the team may be delayed.

**Comment by NeilMacMullen** [comment]
@skyline75489  Thanks - looking at ##7710 I agree this is almost certainly a duplicate of that.  I'll add further findings there.
