### ISSUE TITLE
Output color oddness

### ISSUE THREAD

**Issue by SonOfDiablo** [microsoft/terminal#8642]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.4.3243.0

PowerShell: 7.1.0
Custom C# application using [Colorful.Console](http://colorfulconsole.com/)
```

# Steps to reproduce

1. Create a new C# .Net Core Console Application.
2. Install the following NuGet package: https://www.nuget.org/packages/Colorful.Console
3. Add the following code:
```
using System;
using System.Drawing;
using Console = Colorful.Console;

namespace ColorTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!", Color.White);
        }
    }
}
```
4. Build the application and run it inside of Windows Terminal.

# Expected behavior

The "Hello World" text should be white (as seen here, in PowerShell console window outside of Windows Terminal):
![image](https://user-images.githubusercontent.com/9123250/103027555-617cb980-4556-11eb-9a7c-f1ed49012aa8.png)

# Actual behavior

The "Hello World" text is, for some reason, blue...
![image](https://user-images.githubusercontent.com/9123250/103027610-7bb69780-4556-11eb-8537-7adccd584f56.png)

# More Info

I thought it had something to do with my custom color-scheme, so I tried pasting the default settings over my custom Windows Terminal settings, but the issue were still there.
I then got a friend to test it since it could be something local to my machine, same issue occurred.

I have tried with CMD, PowerShell 6 and 7.
This specific color weirdness ONLY happens inside of Windows Terminal.

I'm not sure whether the issue is on Windows Terminal's site or Colorful.Console, but some kind of incompatibility is happening.

**Comment by j4james** [comment]
I think this is a duplicate of #2985. _Colorful.Console_ actually changes the console's color table to get the color scheme it uses, and those change are not propagated over the conpty connection to Windows Terminal.

**Comment by SonOfDiablo** [comment]
> I think this is a duplicate of #2985. _Colorful.Console_ actually changes the console's color table to get the color scheme it uses, and those change are not propagated over the conpty connection to Windows Terminal.

Yup seems like a duplicate, so I'm going to close this one ^^
