### ISSUE TITLE
Copy Paste Text. Warning Message causes overlay 

### ISSUE THREAD

**Issue by retfloww** [microsoft/terminal#8643]
# Environment
Windows 10 202h 19042.685
Windows Terminal 1.4.3243.0
WSL2 Ubuntu 

# Steps to reproduce
Copy Text and paste it in Terminal until you get a Warning message.

# Expected behavior

No overlay.

# Actual behavior

Black transparent overlay

![image](https://user-images.githubusercontent.com/67190487/103037955-69942380-456d-11eb-8569-41d05edc1030.png)

**Comment by KalleOlaviNiemitalo** [comment]
The same problem was reported earlier as <https://github.com/microsoft/terminal/issues/2380> and is being tracked as <https://github.com/microsoft/microsoft-ui-xaml/issues/3577>.

**Comment by retfloww** [comment]
I must overseen it. Alright thank you!
