### ISSUE TITLE
Iosevka Term Extended font gets reset to Consolas

### ISSUE THREAD

**Issue by agr** [microsoft/terminal#8645]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?

Iosevka fonts 4.1.1
```

# Steps to reproduce

1. Install Iosevka Term [fonts](https://github.com/be5invis/Iosevka/releases/tag/v4.1.1). (direct link: https://github.com/be5invis/Iosevka/releases/download/v4.1.1/ttf-iosevka-term-4.1.1.zip)
2.  Start Windows Terminal
3.  Open the configuration file (Ctrl+,)
4.  Paste `"fontFace": "Iosevka Term Extended"` under `profiles.defaults` or a profile of your choice
5.  Save the configuration file
6.  Notice the terminal is using Consolas font
7.  Try `Iosevka Term` instead, notice that it works as expected.
8.  Same with just `Iosevka` and `Iosevka Extended` (need to install those separately though).

# Expected behavior

`Iosevka Term Extended` font is rendered.

# Actual behavior

Consolas font is rendered.

![image](https://user-images.githubusercontent.com/102933/103046608-b19b5200-453d-11eb-96f5-497b4ea2ef5b.png)

# Other thoughts

I use extended variants in other programs fine, whenever a drop down with a list of fonts appears, those are there as separate fonts. VS  for example:

![image](https://user-images.githubusercontent.com/102933/103047121-4eaaba80-453f-11eb-95bb-d93c2d738654.png)

VS Code, however, seem to have similar issue: https://github.com/microsoft/vscode/issues/95493, so it might be that some more font options need to be surfaced through the configuration file to be able to select those particular fonts.

**Comment by DHowett** [comment]
This will likely come as a surprise, but the actual font face name is "Iosevka Term". The other two names are auxiliary fields that provide additional information to an application displaying the name of the font.

**Comment by DHowett** [comment]
This is mostly the same as /dup #1163.
