### ISSUE TITLE
Not able to type anything on terminal

### ISSUE THREAD

**Issue by sujeet-agrahari** [microsoft/terminal#8646]
I am getting this warning after clicking on okay, I can't type anything I also tried restarting my PC, still nothing works.

![image](https://user-images.githubusercontent.com/22151975/103065144-d34b1680-45db-11eb-8a6a-f12a31d5d383.png)

How this suddenly happened? I have no idea.

If you show some warning, also give some doc to resolve it.

There is still issue open for the same on github having no effective solution.

![image](https://user-images.githubusercontent.com/22151975/103065205-01305b00-45dc-11eb-9c98-99ed7a5d6250.png)

```
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎Sun ‎25-‎10-‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by DHowett** [comment]
/dup #4448 there is so, so much info about this problem, including a fix, in this thread. Don’t disable system services. The warning says “if you disable this service, you won’t be able to type in Terminal”, and you have reported that you read the warning and now cannot type in Terminal.

**Comment by sujeet-agrahari** [comment]
@DHowett  Unfortunately couldn't find anything there, maybe I was in rush. I downloaded .bat file from here http://batcmd.com/windows/10/services/tabletinputservice/ after downloading and executing. It is working.
Did not get any help from above mentioned issue, thanks.

**Comment by DHowett** [comment]
Sorry, thanks for the additional info!
