### ISSUE TITLE
I can't stop interacting with the windows terminal, it doesn't receive keyboard input.

### ISSUE THREAD

**Issue by anwariroki** [microsoft/terminal#8650]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by anwariroki** [comment]
I can't stop interacting with the windows terminal, it doesn't receive keyboard input.

**Comment by skyline75489** [comment]
Can you try the methods mentioned in #8595 and see if any of it works?

**Comment by skyline75489** [comment]
Also #4448
