### ISSUE TITLE
How to change the settings.json file location ?

### ISSUE THREAD

**Issue by garymaxallen** [microsoft/terminal#8652]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

By default, the settings.json is in C:\Users\xxx\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json.
How to change the default location ?

**Comment by skyline75489** [comment]
I don't think you can do that now. See #2933 .

**Comment by KalleOlaviNiemitalo** [comment]
@DHowett, you mistyped the issue number. Does that affect any automation?

**Comment by DHowett** [comment]
Nope, just my flawless sense of style. Thanks :)
