### ISSUE TITLE
No Mouse Scrolling on any Profile

### ISSUE THREAD

**Issue by wulfalpha** [microsoft/terminal#8657]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.19041.685]
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
```

# Steps to reproduce
On any page with multiple lines that exceed the window size mouse scrolling does not work. Scroll bars do not appear.

# Expected behavior
when scrolling through multiple lines of output mouse scrolling should allow you to scroll up and down to the end of the output.

# Actual behavior
It's just not scrolling

**Comment by Don-Vito** [comment]
@wulfalpha - this sounds very unusual, I guess the team will need more details like:
* What shell are you running
* What are your settings
* Screenshot if possible

**Comment by zadjii-msft** [comment]
Does mouse input work at all in the terminal? Can you select text, new tabs, etc? 

Do you have PowerToys installed?

**Comment by wulfalpha** [comment]
sorry i thought what i sent a couple of days ago had actually posted. What I tried to say is I do not have power toys installed. I will try it also selecting text does not always work but i can select new tabs. Thanks

**Comment by DHowett** [comment]
* What shell are you running
* What are your settings
* Can you share a screenshot?
Thanks!
