### ISSUE TITLE
[Feature request] Highlight all found results

### ISSUE THREAD

**Issue by SiqingYu** [microsoft/terminal#8658]
# Description of the new feature/enhancement

Related to the Find tool: Ctrl+Shift+F

Currently, Windows Terminal only highlights one in found result: 

![Screenshot 2020-12-26 172604](https://user-images.githubusercontent.com/22290018/103148918-d4c53c00-479f-11eb-9ba8-d271721a1945.png)

Users need to input Enter key to iterate all the results.

What I propose is to highlight all results at once, like what Konsole and iTerm do:

![Screenshot 2020-12-26 172500](https://user-images.githubusercontent.com/22290018/103148953-1524ba00-47a0-11eb-9bb0-3a9df76adfdc.png)

![image](https://user-images.githubusercontent.com/22290018/103149030-d3484380-47a0-11eb-9ac3-556250d13ce4.png)
([Credit](https://apple.stackexchange.com/questions/162315/iterm2-how-to-change-the-color-used-to-highlight-search-results))

This feature can be useful in many ways:

- Developers would like to monitor keywords like ERROR, FATAL in **real-time** output. A Find tool that highlights the keywords as they appear would be helpful.
- Developers can see all highlights at a glance without hitting Enter many times.
- `Grep` can't replace this feature because `grep` removes lines that don't contain the keywords but are informational and should be shown.

**Comment by Don-Vito** [comment]
@SiqingYu - please review if #7561 satisfies your needs

**Comment by SiqingYu** [comment]
@Don-Vito Yes. This issue duplicates #7561
