### ISSUE TITLE
Allow to set Margin (per side) at Properties

### ISSUE THREAD

**Issue by birbilis** [microsoft/terminal#8659]
# Description of the new feature/enhancement

The console text seems to be touching the sides of the console app window, I'd expect to be able to define a margin but can't find such option at the Properties dialog

# Proposed technical implementation details (optional)

should be able to define a margin in the same way as done in printer/page settings dialogs, aka separate values per side with probably a helper UI to define same value for all sides at once

**Comment by Don-Vito** [comment]
@birbilis - please review if [padding settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#padding) satisfy your needs

**Comment by birbilis** [comment]
indeed, isn't this settable though via the UI?

**Comment by DHowett** [comment]
It is settable in the same place as all other Terminal settings today: the JSON file. When we have a UI, it will be in there. 

This is not available in the traditional Windows Console.
