### ISSUE TITLE
How to close [FPS CPU GPU RAM...] Panel

### ISSUE THREAD

**Issue by evangerlions** [microsoft/terminal#8660]
![image](https://user-images.githubusercontent.com/32103614/103152911-76ac4f00-47c7-11eb-9343-cf3338cf6667.png)
What's this? Can somebody tell me how to close it? It's so obstructive.

**Comment by KalleOlaviNiemitalo** [comment]
There is a similar-looking screen shot in <https://github.com/microsoft/terminal/issues/7816>, in which the overlay was said to be added by some third-party software. Might be related to <https://github.com/microsoft/terminal/issues/8394> as well. Windows Terminal itself does not provide an FPS gauge; <https://github.com/microsoft/terminal/issues/6025> requests adding one but it has not been implemented yet.

**Comment by evangerlions** [comment]
> There is a similar-looking screen shot in #7816, in which the overlay was said to be added by some third-party software. Might be related to #8394 as well. Windows Terminal itself does not provide an FPS gauge; #6025 requests adding one but it has not been implemented yet.

 THANK YOU VERY MUCH!

I finally found out who did this:  NZXT CAM

**Comment by illnesse** [comment]
Thanks, I've been wondering too

**Comment by rakslice** [comment]
The default global shortcut for it is Ctrl + O which is a truly evil and terrible idea
