### ISSUE TITLE
Cursor shaking in oh-my-zsh

### ISSUE THREAD

**Issue by HernandoR** [microsoft/terminal#8661]
# Environment

```none
Windows build number: [Microsoft Windows NT 10.0.19042.0]
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
MSYS2  oh-my-zsh  zsh-syntax-highlighting
```

# Steps to reproduce

install and config msys2 in Terminal, install zsh and oh-my-zsh, install and enable  zsh-syntax-highlighting plugin. open MSYS2 tab in Terminal, input any letters.

# Expected behavior

The cursor should be steadily alone with the inputted letters.

# Actual behavior

In the first few letters of any lines,(I guess the plugin is trying to scan whether the command is valid), the cursor will change position to 3 letters front, then change back.

https://user-images.githubusercontent.com/45709656/103154549-f2f85f80-47d2-11eb-9e3e-69cddbcfdd1a.mp4

https://user-images.githubusercontent.com/45709656/103154551-f4c22300-47d2-11eb-80d4-0cb6f381f80e.mp4

close the plugin OR directly use MYSL2 will not reproduce.

**Comment by DHowett** [comment]
What version of the MSYS2 runtime are you using?

**Comment by HernandoR** [comment]
![image](https://user-images.githubusercontent.com/45709656/103190084-681a8080-490a-11eb-89df-5d1edd9b095f.png)

**Comment by carlos-zamora** [comment]
/dup #6217

Sorry for the radio silence for so long. We're duplicating this with an earlier issue. This is a new issue.

**Comment by aquapaka** [comment]
This is not a duplicate of the #6217. This issue happen only when zsh-syntax-highlighting enabled. I'm still getting the issue despite of having the latest version Window Terminal.

**Comment by phakeandy** [comment]
The issue is still occurring in the latest version of Windows Terminal (1.21.2911.0). I agree that it only happens when zsh-syntax-highlighting is enabled. By the way, the cursor doesn't seem to shake in the VSCode terminal.
