### ISSUE TITLE
Use the currently opened tab as the default layout for the next startup

### ISSUE THREAD

**Issue by xianghongai** [microsoft/terminal#8665]
# Description of the new feature/enhancement

I want to use the currently opened tab as the default layout for each startup.

![Windows Terminal](https://user-images.githubusercontent.com/2075006/103185140-0e0fc000-48f6-11eb-97ef-cda4e2990a34.png)

# Proposed technical implementation details (optional)

There can be a quick way to save the layout of all currently opened tabs and the directories entered.

**Comment by skyline75489** [comment]
I think this is covered or partially covered by #961 .

**Comment by zadjii-msft** [comment]
Yea, this is gonna be something like #961 or even #756. Right now you can kinda workaround this by creating an action that will open the layout you want. For example, I use the following as the action I tun in the first terminal of the day:

```jsonc
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole ; split-pane --title OpenConsole ; split-pane -H cmd.exe /k media-commandline ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },
```

That creates 4 tabs, running a few different environments, and some splits inside them. 

/dup #756
