### ISSUE TITLE
Connecting to a raspberry pi with plink.exe and a usb serial cable: keyboard input doesn't work on apps like vim or htop (ncurses apps presumably)

### ISSUE THREAD

**Issue by jdarias** [microsoft/terminal#8666]
# Environment

```none
Microsoft Windows [Versión 10.0.19041.685]
Windows Terminal Versión: 1.4.3243.0

Any other software?
putty.exe
plink.exe

Hardware:
raspberry pi
USB Serial cable CP2102
```

# Steps to reproduce
1. Connect the cable to the raspberry pi as instructed here: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable
2. Set a windows terminal profile like this:
		{
			// Serial cable to my raspberry pi
			"guid": "{6620a8ea-b9a7-4ed3-974e-03171cf68fbe}",
			"name": "Serial to Raspberry Pi (plink)",
			"commandline": "plink.exe -serial COM4 -sercfg 115200,8,n,1,N",
			"hidden": false,
			"padding": "2,2,2,2",
			"icon": "D:\\Dropbox\\aaa Webs\\Recursos\\fugue-icons-3.4.1\\icons\\network-ethernet.png"
		},
3. log into your pi using windows terminal with this profile, and the console cable
4. use a program like htop or vim
5. esc and the function keys won't work. They do if you use putty.exe, but that's outside windows terminal. the idea here is to be able to use plink.exe inside windows terminal.

# Expected behavior
Esc and function keys should work

# Actual behavior
Esc and function keys don't work and you're stuck

**Comment by KalleOlaviNiemitalo** [comment]
I wonder if the [`-no-sanitise-stderr` `-no-sanitise-stdout`](<https://the.earth.li/~sgtatham/putty/0.74/htmldoc/Chapter7.html#plink-option-sanitise> "7.2.3.5 -sanitise-stream: control output sanitisation") options of Plink would help here. I presume Plink cannot distinguish stderr from stdout on a serial connection anyway.

**Comment by jdarias** [comment]
I tried both options but it made no difference. htop won´t take keyboard
input at all. Plink fails horribly when running from cmd.exe, ncurses apps
look all garbled and they won't take keyboard input. In WT they can at
least be looked at. It may be an issue with plink not windows terminal...

**Comment by zadjii-msft** [comment]
~~Could you share the output of `infocmp` when connected to the raspberry pi?~~

> Plink fails horribly when running from cmd.exe, ncurses apps look all garbled and they won't take keyboard input. In WT they can at least be looked at. It may be an issue with plink not windows terminal...

This sure sounds like it's probably a `plink` issue, not a Terminal one. The Terminal is just giving the appearance that it's working, when it really isn't. I'd bet that plink needs to enable both `ENABLE_VIRTUAL_TERMINAL_INPUT` and `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. Those will cause the Terminal to send the keystrokes in a linux-friendly format. WSL uses those modes (as an example).

**Comment by DHowett** [comment]
Unfortunately, this does look like a plink issue. We're sending it Win32 console events (because it's a win32 console application that predates the 2015-era VT support), and it's not handling them properly. Sorry.
