### ISSUE TITLE
I couldn't run the Setting window 

### ISSUE THREAD

**Issue by seohyeonShin** [microsoft/terminal#8668]
# Environment
windows10, install visual studio 2013 prof. install VSCode, WSL 2. 

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

0. windows10, install visual studio 2013 prof. install VSCode, WSL 2. 
1. run windows terminal with ubuntu(actually, I think that is not matter)
2. right click and select the setting on windows terminal upper bar. 
3. and than Visual studio2013 is executed without any file or any information. 
# Expected behavior
just open setting text file on VS CODE or other text edit program. 

![image](https://user-images.githubusercontent.com/17170771/103199274-d9b7f600-492d-11eb-8ef9-39280488b852.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/17170771/103199199-a8d7c100-492d-11eb-98e5-de4a9f283ee2.png)
![image](https://user-images.githubusercontent.com/17170771/103199230-b8570a00-492d-11eb-9c09-7ca0400828d6.png)

Visual Studio runs if i click the setting, without any informataion. 
I use visual studio 2013 for work.

**Comment by KalleOlaviNiemitalo** [comment]
If you double-click the `settings.json` file in File Explorer, does Visual Studio 2013 likewise start without opening the file? If it does, I think the fault is not in Windows Terminal.

**Comment by carlos-zamora** [comment]
@seohyeonShin Windows Terminal opens your `settings.json` file with the default text editor for json files. Sounds like you have Visual Studio 2013 set as your default there. Try this:
1. go to the Settings app for Windows
2. select Apps > Default apps > Choose default apps by file type
3. scroll down to .json and set the default app to VS Code

![Relevant Settings App page](https://user-images.githubusercontent.com/11050425/103225370-5ecfea80-48ef-11eb-9442-17e80a22d86b.png)

Let me know if this works for you 😊

**Comment by seohyeonShin** [comment]
![image](https://user-images.githubusercontent.com/17170771/103251026-44af0e80-49ba-11eb-97c6-d2dc8c796344.png)
I couldn't choice other tool,,, 
I can't understand that why I can choice only visual studio and only find in MS store.

**Comment by Chips1234** [comment]
@seohyeonShin You have VSCode installed, yes?

**Comment by seohyeonShin** [comment]
wow,, Thanks! I never expected it to be a problem. 
I was able to fix it by referring to your advice.

**Comment by Chips1234** [comment]
You’re welcome

________________________________
