### ISSUE TITLE
Feature Request: make the version number visible somewhere in the UI (menu maybe?)

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#867]

**Comment by mdtauk** [comment]
The settings window would make the most sense for this, once they add a GUI for editing profiles and colours etc

**Comment by DHowett-MSFT** [comment]
Well, once _we_ add a GUI for editing profiles. For the 0.2 milestone, it'll probably live in the menu and be generally inert.

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/57903980-c0515b80-7868-11e9-94a1-dcc4aa2aea26.png)

**Comment by DHowett-MSFT** [comment]
@mdtauk we are in agreement, but we probably aren’t getting a whole settings UI in the next two weeks. I’ve seen this design in a number of places, would it help for us to have a consolidated design discussion thread instead of using every issue as one?

**Comment by mdtauk** [comment]
> @mdtauk we are in agreement, but we probably aren’t getting a whole settings UI in the next two weeks. I’ve seen this design in a number of places; would it help for us to have a consolidated design discussion thread instead of using every issue as one?

Ah ok, so if its needed for an initial store release, you could put it in the flyout with the profiles listed?

**Comment by DHowett-MSFT** [comment]
Yep! I know it’s less than ideal :)

**Comment by zadjii-msft** [comment]
I'm gonna suggest `wt --version`? The new tab flyout could get very busy very fast.

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/59385175-b2a1cf80-8d5b-11e9-8a89-9e3f08621c05.png)

Change logs and Version numbers should be contained within a settings dialog

**Comment by DHowett-MSFT** [comment]
Yes. Thank you.

**Comment by DHowett-MSFT** [comment]
Just to set some context, we're talking about _0.2_ here, not _1.0_
