### ISSUE TITLE
wt doesn't start in directory given from explorer

### ISSUE THREAD

**Issue by csm10495** [microsoft/terminal#8672]
# Environment

```none
Windows build number: 10.0.18363.1256
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?

I don't think it matters but I am using clink in cmd and a profile in powershell. Same stuff happens without them.
```

# Steps to reproduce

If I open wt from a directory via Windows Explorer, it doesn't start in the correct directory. This behavior is different from cmd/powershell.

# Expected behavior

If i run wt in Windows Explorer in a directory, it should start in that directory.

# Actual behavior

wt seems to start in the user's home directory.

Attaching a video of the behavior difference

https://user-images.githubusercontent.com/5749838/103238307-233d1c80-48ff-11eb-8b5b-d435035fce89.mp4

**Comment by j4james** [comment]
The recommended way to make this work is by entering `wt -d .` in the explorer bar. For more info see https://github.com/microsoft/terminal/issues/878#issuecomment-579508860.

**Comment by zadjii-msft** [comment]
Yep, this is by design. /dup #878
