### ISSUE TITLE
disable right mouse click to paste

### ISSUE THREAD

**Issue by 354651432** [microsoft/terminal#8674]
# Description of the new feature/enhancement
I dislike the right mouse button click to paste, so I want a configuration to disable it 

# Proposed technical implementation details (optional)
A configuration like this :
```json
{"disableRightMousePaste":true} // and its value may be false by default
```

**Comment by KalleOlaviNiemitalo** [comment]
This was also requested in <https://github.com/microsoft/terminal/issues/3424> and <https://github.com/microsoft/terminal/issues/7922>, which were folded into <https://github.com/microsoft/terminal/issues/1553>.

**Comment by zadjii-msft** [comment]
Yep, we'll be addressing this in /dup #1553. Thanks!
