### ISSUE TITLE
Nice application. 

### ISSUE THREAD

**Issue by Conrad6** [microsoft/terminal#8675]
This isn't a bug, but a request for a new feature. Could there be an option for Windows Terminal to be always on top of other windows?

**Comment by KalleOlaviNiemitalo** [comment]
Windows Terminal already supports [Always on top mode](https://docs.microsoft.com/windows/terminal/customize-settings/global-settings#always-on-top-mode).

**Comment by KalleOlaviNiemitalo** [comment]
The feature was documented in <https://github.com/MicrosoftDocs/terminal/pull/89> but the Italian and German translations of the page don't seem to have been updated yet. I did not check other languages.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3038 for more discussion.

/dup #3038
