### ISSUE TITLE
receive Permission denied when running wt command line from  git bash

### ISSUE THREAD

**Issue by zivni** [microsoft/terminal#8676]
trying to run wt command line tool in git bush will result in  Permission denied

```
$ wt
bash: /c/Users/myuser/AppData/Local/Microsoft/WindowsApps/wt: Permission denied
```

**Comment by KalleOlaviNiemitalo** [comment]
Might be a duplicate of <https://github.com/microsoft/terminal/issues/4765>, which was redirected to <https://github.com/microsoft/WSL/issues/4969>.

**Comment by KalleOlaviNiemitalo** [comment]
Might be <https://github.com/msys2/MSYS2-packages/issues/1943>, instead.

**Comment by DHowett** [comment]
Yes, this is a bug in the msys/cygwin runtime. Thanks @KalleOlaviNiemitalo!

/dupe https://github.com/msys2/MSYS2-packages/issues/1943
