### ISSUE TITLE
app crashed on mouse dragging of tab

### ISSUE THREAD

**Issue by ErroKokkarda** [microsoft/terminal#8683]
# Environment

```none
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):  1.4.3243.0

Any other software?
```

# Steps to reproduce

drag tab to middle of terminal I tried dragging ubuntu tab

# Expected behavior

open new window

# Actual behavior

crashes entire app almost consistently out of 5 times tried got 3 crashes and often get them

**Comment by skyline75489** [comment]
Hi! Can you try the steps in https://github.com/microsoft/terminal/issues/8287#issuecomment-733893742 ? This will collect useful information about the crash.

**Comment by zadjii-msft** [comment]
Also, @ErroKokkarda are you running elevated? Or, do you have UAC disabled?

**Comment by alxwndr** [comment]
It happened to me couple times on Windows Terminal Preview Version: 1.5.3242.0, but stopped immediately after reinstalling, so maybe try that.

**Comment by jdunham22** [comment]
This happens to me a fair amount, but I'm having a hard time repro'ing.  I typically have 8-10 tabs open, mostly running openssh inside a powershell terminal.  It seems much more common after the windows have been open for several hours which usually means at least one sleep or hibernate, but I don't know yet whether that is required.  If I try to reorder the tabs by dragging one with the mouse, then when I release the mouse button, the Terminal window completely disappears. 

I'll keep trying to figure out how to reproduce this reliably.

**Comment by jdunham22** [comment]
Whenever it crashes, I drag the tab down into the client area, and I see the red-circle-with-slash glyph being dragged by the mouse. Then mouse cursor changes to the windows wait cursor, and then after about a second or two, (I'm still holding the left mouse button down) it crashes (the whole Terminal window disappears)  I don't think it crashes if I don't drag the tab into the window client area (below the title bar), but not totally sure. But even when I do drag the tab down over the client area, it only crashes a few percent of the time. 

I always see the windows wait cursor first when it's about to crash. If I don't see the wait cursor it doesn't crash.
