### ISSUE TITLE
Ideographic comma and other characters disappear when pasting to the Windows Terminal Preview Windows Powershell's

### ISSUE THREAD

**Issue by Xwth** [microsoft/terminal#8684]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.3242.0

Windows PowerShell with or without profile
```

# Steps to reproduce

Have `1、2` on your clipboard, or any other text that doesn't start with any of these `♪` `～` `、` as the first character.

Paste it onto the terminal.

# Expected behavior

To paste:
`1、2`

# Actual behavior

But instead shows:
`12`

**Comment by DHowett** [comment]
Does it work in Command Prompt?

**Comment by DHowett** [comment]
Also, does it work in Windows PowerShell outside of Terminal?

**Comment by e1970180** [comment]
Hi! 
I have same problem.
E.g. then I copy  
#! | $new 'sc' 
to clipboard
The result of paste to Terminal is 
!  new sc
There is no such problem with Power Shell

**Environment**

Microsoft Windows [Version 10.0.19042.685]
Windows Terminal Version: 1.4.3243.0

**Comment by clovk** [comment]
Same issue

Microsoft Windows OS build 19043.1620
Windows Feature Experience Pack 120.2212.4170.0
Windows Terminal Version: 1.12.10732.0

**Comment by clovk** [comment]
Nevermind, it seems to work now... I had issues pasting multiple lines to an ssh connection...
And yes i'm Slovenian and locals are often an issue, thx!

**Comment by zadjii-msft** [comment]
Glad to hear it resolved itself? Yea I'd bet that ssh might further complicate things 😝

**Comment by clovk** [comment]
There was (another) windows update during this conversation, something just probably got reset

**Comment by Xwth** [comment]
Problem solved a bit ago for me.

The problem used to happen anywhere but in the terminal preview, in any of the default profiles, with any of the rendering options, or command line executables listed, occurred in a clean install and my locale was also English(US).

Giving a bit more detail on the problem I had, if it helps in any way: 
Problem surged when I wanted to copy certain file names and paste them into the terminal, worked just fine if the problematic character was repeated anywhere in the text.

(Sorry life happened so I couldn't respond.)
