### ISSUE TITLE
Enable "Discussions" GitHub feature

### ISSUE THREAD

**Issue by bgr** [microsoft/terminal#8685]
It might be beneficial to enable the "Discussions" feature to separate the project development issues from "how do I do X" types of issues, and build a community.

See [ImageMagick's discussions](https://github.com/ImageMagick/ImageMagick/discussions/categories/help) for example.

My motivation for proposing this is that I've started using the Windows Terminal few days ago and I've probably spent several hours searching for ways to configure settings to my liking, and there are a few I still haven't figured out but I feel like I'd be spamming the "Issues" by asking there.

**Comment by j4james** [comment]
Enabling the GitHub "discussions" feature was suggested before in issue #7428. The argument against it was that it has a tendency to turn into a second bug tracker (here's one example: https://github.com/microsoft/terminal/issues/7428#issuecomment-725660615).

**Comment by DHowett** [comment]
/dup #7428 since they sorta share a common thread

**Comment by itsme-alan** [comment]
@DHowett I don't think this is a duplicate. The conversation became off-topic discussing about Discussions (pun intended) but the original ask is different
