### ISSUE TITLE
Retro theme bad performance and high GPU usage

### ISSUE THREAD

**Issue by hichemfantar** [microsoft/terminal#8686]
# Environment

```none
Windows build number: [10.0.18363.1256]
Windows Terminal version (if applicable): 1.4.3243.0
GPU: Intel UHD Graphics 630, Terminal is not using my Nvidia GPU GTX 1050TI but the integrated graphics should be plenty to handle a simple terminal theme.
```

# Steps to reproduce

Enable Retro theme found in the official docs: https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/retro-command-prompt

# Expected behavior

A simple theme like this simply shouldn't be consuming the resources like it currently does

# Actual behavior

Extremely high GPU usage: Not only does GPU usage reach +80%, but the performance is very bad, there's obvious delay when displaying key strokes.
![image](https://user-images.githubusercontent.com/34947993/103419000-67dfe680-4b91-11eb-9f50-e8dfa8e891ec.png)

**Comment by DHowett** [comment]
It's a pixel shader marked "experimental" with known performance issues. This is by design.
