### ISSUE TITLE
improve the default settings

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#869]
Followup to #430. Here's what I'm thinking.

* [ ] `alwaysShowTabs` -> `true`
* [ ] `experimental_showTabsInTitlebar` -> `true`
* [ ] always include Windows Powershell (`background`: `#012456`)
* [ ] include PowerShell Core separately (`background`: unset)
* [ ] drop `Courier New` for powershell

**Comment by zadjii-msft** [comment]
We're automatically making powershell (core) the default now. If core is installed, should that be the default? or Windows powershell always?

Also, if we're making show tabs in titlebar the default, then we should probably pull `experimental_` off of it.

**Comment by mdtauk** [comment]
> We're automatically making powershell (core) the default now. If core is installed, should that be the default? or Windows powershell always?
> 
> Also, if we're making show tabs in titlebar the default, then we should probably pull `experimental_` off of it.

I would suggest you read the registry setting to see if the user has changed the setting to use Command instead of Powershell.

![image](https://user-images.githubusercontent.com/7389110/57929342-f3b4da00-78aa-11e9-9012-246e0aa1dcf5.png)

### HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\DontUsePowerShellOnWinX

**Comment by fearthecowboy** [comment]
What's your detection mechanism for seeing if pwsh is installed?

**Comment by DHowett-MSFT** [comment]
Today, it’s “crawl through Program Files to find telltale signs of it.” Tomorrow, however, maybe it’s “look into the installer database (using supported APIs) to see where the user really put it.”

**Comment by DHowett-MSFT** [comment]
> I would suggest you read the registry setting to see if the user has changed the setting to use Command instead of Powershell.

We've debated about this for a while internally. It's a good idea, and we should do it, but _the registry is not a contract, and we are not supposed to go groveling about in other peoples' registry keys._ It's the same fundamental issue as was brought up in #695.

What we should be doing is driving API dependencies, as we are with WSL, so that we can detect how the user's configured their machine.

**Comment by mdtauk** [comment]
I agree this should be a default app type and WinRT should provide a read only API to receive a friendly package name, and entry point path for all ~~default~~ apps that are installed.

I personally always switch my default to CMD, and avoid powershell (unless I need to trouble shoot some store apps)

**Comment by zadjii-msft** [comment]
I propose also changing the default font size, as caught in #903. The default font size of `12` was originally 12px, but since then we changed the DX renderer such that 12 meant 12 point. 12 point is definitely bigger than 12px tall
