### ISSUE TITLE
settings.json/backgroundImage bug report

### ISSUE THREAD

**Issue by hitcbw** [microsoft/terminal#8690]
Description: when i want to change the background image by editing the settings.json in Terminal , if i choose one image which filename contains '_', it will cause a fatal error : a pop-up window will show and told me the path doesn't point to a image.

Solution: fix the filename process

**Comment by skyline75489** [comment]
Would you mind showing up the exact error and the way to reproduce this? What is the path you’re using? A screenshot of the popup would be good.

**Comment by hitcbw** [comment]
It's weird that I reinstall the terminal after i raise this issue, but that problem can't be reproduced again. But that's a pop-up window which told me the property background image doesn't point to a valid image file. Anyway, it works fine now, even i point to a path which doesn't point to any file, the pop-up window wouldn't show again. That's so weird!
