### ISSUE TITLE
Incomplete font when 113% custom zoom is enabled

### ISSUE THREAD

**Issue by Xiaotian0617** [microsoft/terminal#8691]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment]
Please search for existing issues before filing a new one. This is #4591.

**Comment by zadjii-msft** [comment]
Yep, thanks for the triage help @skyline75489!

/dup #4591
