### ISSUE TITLE
Shortcut to Clear Screen - analogue to `clear`

### ISSUE THREAD

**Issue by ottovw** [microsoft/terminal#8693]
# Description of the new feature/enhancement

Shortcut to clear the Screen, similar to entering `clear`. 

E.g. iTerm uses `cmd+k`, bash `ctrl+l`

Suggestion for shortcut on Windows: `ctrl + k`

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Ctrl+L works in powershell and bash already. Follow /dup #1882for a bindable hard clear.
