### ISSUE TITLE
Organise profiles in folders in the dropdown

### ISSUE THREAD

**Issue by tforster** [microsoft/terminal#8694]
# Description of the new feature/enhancement

The ability to specify optional folder names for profiles in the profiles dropdown menu.

I am a consultant that works on multiple projects for multiple clients. I typically create a per-client/per-project directory structure in my filesystem and corresponding Terminal profiles rooted to each location. My dropdown list is growing and becoming long-scrolling/unusable. It would be great to have the option to drop down a list of folders, with a rollover/click on each folder revealing a cascading dropdown of profiles. 

# Proposed technical implementation details (optional)

I see two potential methods of organisation:

1. Add a new and optional "folder" property in the profile schema. When detected the UI creates the corresponding value as the dropdown entry and groups all profiles sharing that property value below the new entry.

1. Introduce support for a profile hierarchy along the lines of 
    ```
    profiles/{group-name}/default
    profiles/{group-name/list
    ```
    along with the existing
    ```
    profiles/default
    profiles/list
    ```
    This would allow profiles below any optionally created {profile-name} to be grouped and displayed in the dropdown while also providing a more intuitive hierarchy for organisation and setting of default values.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+profiles+folder+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
