### ISSUE TITLE
Assignment operators in til::spsc don't return anything

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#8695]
# Environment

Windows build number: Version 10.0.18363.1198
Windows Terminal version (if applicable): 

# Steps to reproduce

I was trying to use the `til::spsc` class to do something like this:

```
auto channel = til::spsc::channel<QueueItem>(100);
auto producer = std::move(channel.first);
channel.first = std::move(producer);
```

# Expected behavior

The code should compile.

# Actual behavior

It fails with the error:
```
C:\terminal\src\inc\til\spsc.h(429): error C4716: 'til::spsc::producer<QueueItem>::operator=': must return a value
```

I believe the problem is that the assignment operators in the `producer` and `consumer` classes don't actually return anything. 

See here:
https://github.com/microsoft/terminal/blob/ae550e0969595f062b15c2ff5cc33d4afe8ebc3f/src/inc/til/spsc.h#L424-L428

and here:
https://github.com/microsoft/terminal/blob/ae550e0969595f062b15c2ff5cc33d4afe8ebc3f/src/inc/til/spsc.h#L542-L546

I'm assuming they should have a `return *this;` or something along those lines.

**Comment by DHowett** [comment]
Whoops. Good catch!

**Comment by DHowett** [comment]
(You can safely ditch the bug template at this point :smile:)

**Comment by j4james** [comment]
> (You can safely ditch the bug template ~at this point~ for things like this 😄)

There are 10 red warning lights at the top of that bug template. I'm not willing to risk deleting it! 😄
