### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by smcguffee** [microsoft/terminal#8701]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
 [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
 
Any other software?
```

# Steps to reproduce

I put the windows terminal in my startup folder so that it will be open when I get started. However, it has some bug in that there is a dependency that doesn't seem to be available at startup.

# Expected behavior

I expect the windows terminal to open on startup.

# Actual behavior
The windows terminal crashes with a popup about a missing dependency.

**Comment by zadjii-msft** [comment]
Could you share the popup that lists which dependency it's missing? That would be a good place to start the investigation...

**Comment by smcguffee** [comment]
https://drive.google.com/file/d/1HVXxr34pwKGE4Kvh_wMangrF_n_GF9Yf/view?usp=sharing

**Comment by zadjii-msft** [comment]
Wait _what_? `TerminalThemeHelpers.dll` is missing? That shouldn't be possible, that should have been installed when you installed the Terminal. 

What _exactly_ did you do when you "put the windows terminal in my startup folder"? I haven't ever heard of someone doing that when they want to have the Terminal run on startup. Typically, you should be using the [`startOnUserLogin`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#launch-on-startup) setting...

**Comment by DHowett** [comment]
You cannot just copy random EXE files out of a package into other folders and expect them to work. Use the `startOnUserLogin` setting.

**Comment by viratnigam18** [comment]
terminal theme helper  .dll missing but it is already there and i try replacing it doest not work any idea >???

**Comment by zadjii-msft** [comment]
@viratnigam18 

`TerminalThemeHelpers.dll` is included in our packaged whenever you download the Terminal. I'm assuming you did something between "download the terminal" and "it doesn't work" - can you elaborate?

You should probably file a new issue. This one was closed more than 3 years ago.
