### ISSUE TITLE
Tabs Become Irresponsive After Long Use

### ISSUE THREAD

**Issue by yakobyd** [microsoft/terminal#8702]
### Environment

```
Microsoft Windows [Version 10.0.19041.685]
Windows Terminal Version: 1.4.3243.0
```

## Steps to reproduce

**Issue:** The terminal becomes irresponsive after few days of use. Specifically, switching tabs is very slow.

I often leave my terminal app open for a week of continuous use. Usually, after three days, the terminal becomes very slow to interact with. This has been happening consistently for the past month. Namely, I have experienced this issue at least four times by now.

To reproduce, open the terminal and use it for three days without closing the app. The terminal should become very slow at this point. If one closes the terminal and reopens it, it becomes responsive again.

Additional functionalities that become slower:
- Typing.
- Opening new tabs and closing existing tabs.

I have not included these functionalities in the videos below as they are slightly harder to notice.

## Expected behavior

Below is the behavior of a freshly opened terminal. Note that tab switching is immediate after each click.

https://user-images.githubusercontent.com/39068219/103559013-26677800-4ebe-11eb-89fd-c4545bd07f5e.mp4

## Actual behavior

Below is the behavior of a terminal that was used for three days (I have cleared all output). Note that after clicking, tab switching is very slow. Clicks are not apparent in this video, but I tried to click as soon as the mouse hovers over the tab. Hopefully, the difference is clear when comparing with the expected behavior above.

https://user-images.githubusercontent.com/39068219/103559035-2cf5ef80-4ebe-11eb-8b3e-be2a4a1c987d.mp4

**Comment by Don-Vito** [comment]
@yakobyd - this seems very similar to https://github.com/microsoft/terminal/issues/7710. Please check if they can be "merged".

**Comment by yakobyd** [comment]
Thanks, indeed, #7710 describes the same problem. I didn't see it was already an open issue, sorry.

**Comment by Don-Vito** [comment]
> 
> 
> Thanks, indeed, #7710 describes the same problem. I didn't see it was already an open issue, sorry.

With more than 1K open issues I also have hard times to find existing ones! :blush: 
I remembered this one as it is especially popular lately (though I could never repro it).

In any case, I suggest to follow that ticket and resolve this one by now.

**Comment by yakobyd** [comment]
Thanks, I will follow the existing ticket.

@Don-Vito - As for reproduction, I use the terminal for ssh + tmux. Similar to https://github.com/microsoft/terminal/issues/7710#issuecomment-719803095, I suspect that excessive command/output history is being saved when using tmux.  

**Quick check:** When printing a large text file during a tmux session, the memory consumption of the terminal process almost doubles (60MB -> 120MB). After closing the tmux session, and clearing the terminal, there is no way to access the printed text. However, the memory of the terminal process does not clear.

**Comment by Don-Vito** [comment]
> g a tmux session, the memory consumption of the terminal process doubles (60MB -> 120MB). After closing the tmux session, and clearing the terminal, there is no way to access

This is extremely interesting - I think this observation needs to be added to the main ticket.
I will also try to do the same to repo locally !
Thanks!
