### ISSUE TITLE
Can windows terminal support the GBK encoding

### ISSUE THREAD

**Issue by 756764634** [microsoft/terminal#8705]
I used the terminal to linked our server，but i see garbled code when i view Chinese

**Comment by skyline75489** [comment]
You need to provide more context. What OS is the server running? How do you connect to the server? Is it ssh? If it’s ssh, is it OpenSSH-win32 or SSH in WSL? What exactly is the “garbled” text? Some screenshots would be nice.

**Comment by skyline75489** [comment]
Also does this happen with conhost aka cmd.exe? How do you know this is caused by GB2312/GBK?  Please make sure enough information is given if you really need help from others. Not only in this repo, but in all repos anywhere, to be frank.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps you could use [luit](https://invisible-island.net/luit/) on the server to convert the encoding.
