### ISSUE TITLE
WT doesn't close process handles to openconsole.exe

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8706]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.19042.685 (2009, 20H2)
WindowsTerminalPreview_1.5.3242.0_x64

Release version does it too.
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Monitor WT's open "Process" handles while opening/closong new tabs or panes.

# Expected behavior
WT will close its newly acquired handle to OpenConsole.exe 

# Actual behavior
WT does not close the handle

Using HANDLE64.EXE (Sysinternals, could also use their ProcessExplorer) ...

```
v:\> rem New Instance

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A04: Process       cmd.exe(3136)

v:\> rem Open a second tab

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A00: Process       OpenConsole.exe(9848)
  A04: Process       cmd.exe(3136)
  AC8: Process       cmd.exe(8480)

v:\> rem Close the newly opened tab

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A00: Process       <Non-existant Process>(9848)
  A04: Process       cmd.exe(3136)
```

**Comment by DHowett** [comment]
_How do you keep finding these things?_ Do you just routinely check out the handles for all the stuff you run on your machine?

I'm not complaining, but it _is_ strange :wink:

**Comment by vefatica** [comment]
I'm generally concerned with performance, especially that of apps which have captured my fancy in some way.  And I have several tools (some my own) for observing performance (and I enjoy using them).

In this case, I was trying to find differences between instances of WT which use little CPU when idling and ones which use a lot of CPU when idling (see #8625).
