### ISSUE TITLE
Better settings file location

### ISSUE THREAD

**Issue by zsimic** [microsoft/terminal#8708]
# Description of the new feature/enhancement

Current location for WindowsTerminal settings seems to be quite **obnoxious**:
```
C:\Users\...\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```

Several things seem gratuitously complicated:
- very long path
- not in a "standard" place (like `%APPDATA%`)
- has weird looking id in there `_8wekyb3d8bbwe` (makes me wonder: are these settings like part of a scratch/cache folder?)

# Proposed technical implementation details (optional)

Can you simplify this to be something much simpler? like for example:
```
%APPDATA%/Microsoft/WindowsTerminal/settings.json
```

**Comment by DHowett** [comment]
The settings are stored in a permanent app-specific folder (not a cache or scratch folder). Please follow /dup #2933 for updates on the settings file location :smile:
