### ISSUE TITLE
Flashing the window title (and the task bar) via FlashWindowEx has no effect

### ISSUE THREAD

**Issue by UweKeim** [microsoft/terminal#8713]
# Environment

Windows build number: Microsoft Windows [Version 10.0.19042.685]
Windows Terminal version: 1.4.3243.0

Any other software? Any program that flashes the window title like e.g. my own tool to do so: https://github.com/UweKeim/console-flasher

# Steps to reproduce

I'm trying to acchieve that when a program, that runs in a CMD instance inside Windows Terminal, does makes a call to the [`FlashConsoleEx` Windows API call](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex), the flashing of both the window title and the task bar icon of Windows Terminal does happen.

1. Open a new Terminal instance with a cmd tab (i.e. _no_ PowerShell)
2. Run a program that flashes the window title (and also the task bar icon)

# Expected behavior

The window title and the task bar icon of Windows Terminal flashes.

# Actual behavior

The window title and the task bar icon of Windows Terminal does not flash.

# Additional remarks

Try running a program that flashes the window title in a regular cmd.exe (i.e. not in Windows Terminal) to see a live example of the expected behaviour.

**Comment by zadjii-msft** [comment]
Ah, this is another one of those things that won't work in Windows Terminal because conpty is returning garbage for the result of `GetConsoleWindow`. (Another one of these is #2988). That's one of the APIs that we're trying to discourage users from using in the future, because it won't work cross-platform, and it won't work in remote scenarios (like ssh).

One of the things we are working on is a VT sequence version of this functionality. Have a look at #6700. I'm not sure it does taskbar _flashing_, per say, but we can set the "progress" state of the window. I'm gonna tag in @PankajBhojwani to see if he has any other thoughts on the matter.

**Comment by PankajBhojwani** [comment]
What zadjii-msft said! We do already have the infrastructure in place to flash the taskbar (#8215 added the ability to flash the taskbar when BEL is emitted) so adding a VT sequence for this should be straightforward I think

**Comment by DHowett** [comment]
We may want to avoid having our own VT sequence for stuff like this. The bell, or the ConEmu Progress API (OSC 9;4) should be sufficient and more expressive. :smile:

Whether the window flashes is a _user preference_, and no application should be able to override that.

**Comment by DHowett** [comment]
(Closing as answered, but do feel free to continue the discussion!)

**Comment by UweKeim** [comment]
Trying to get my head around the (to me rather new) concept of "VT sequences" (short for "Virtual Terminal Sequences"), here are some resourcen about that topic.

- "[Console Virtual Terminal Sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)" – Microsoft Docs
- "[Using ANSI colour codes in .NET Core Console applications](https://www.jerriepelser.com/blog/using-ansi-color-codes-in-net-console-apps/)" –  Random blog post about this topic

--------------------

Basic example:

```csharp
Console.WriteLine("\u001b[31mHello World!\u001b[0m");
```

This code would set the color of the text to red through the escape sequence `ESC[31m`. (`31` for red), prints "Hello World!" and then finally uses `ESC[0m` to reset the color.

As another example the following would position the cursor two lines up, by using the [escape sequence `ESC[2A`](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#cursor-positioning). 

```csharp
Console.Write("\u001b[2A");
```

-----------------

For the Bell VT sequence (`^G`, as described in https://github.com/microsoft/terminal/pull/8215) I did not get it to work with this:

```csharp
Console.Write("\u001b[G");
```

and also not with this:

```csharp
Console.Write("\a");
```

But probably the reason it is not _yet_ working is that my version of Windows Terminal does not yet include https://github.com/microsoft/terminal/pull/8215.

-----------------------------------

I hope this helps others in the future, too.

**Comment by UweKeim** [comment]
One and a half year later, this still does not work, as #8215 still seems to be not included, not even in the Preview of Windows Terminal. Sad.
