### ISSUE TITLE
Bad default selection background color with light schemes

### ISSUE THREAD

**Issue by austin-beer** [microsoft/terminal#8716]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 1.4.3243.0
```

# Steps to reproduce

1. Update settings.json to use the `One Half Light`, `Solarized Light`, or `Tango Light` color schemes.
1. Use the mouse to highlight some text.

# Expected behavior

It's easy to see which text was selected.

# Actual behavior

It's hard to see which text was selected because the default selectionBackground value is white, and that doesn't work well with light color schemes.

# Proposed solution

Add selectionBackground values to all of the color schemes in defaults.json (or at least the light color schemes).

# Related to

This issue is related to #3326, #3561, and #3580.

**Comment by zadjii-msft** [comment]
Okay, you're not wrong here. Part of the trick with these schemes is that they don't canonically include a selection color. Usually, they're just defined as a set of (foreground, background, 16-color table). The selection color is almost always just set by the terminal emulator. So if we were to add selection BG colors to these schemes, that would be some other customization that we're making to these schemes other than their usual definitions. 

Though, I think I agree - until #3561 lands, the experience with these themes is just _bad_. I wonder if we could just use the "bright black" color for each of these schemes and have it work _good enough_.

**Comment by 1994bluemoon** [comment]
1. Select One Half Light, Solarized Light, or Tango Light color schemes
2. Input number
==> can't see the number inputed

![image](https://user-images.githubusercontent.com/26895558/123279232-dfd00d80-d531-11eb-9cd0-e78afad5471f.png)
