### ISSUE TITLE
Could you pls add Minimize to Taskbar Status Area

### ISSUE THREAD

**Issue by scutxd** [microsoft/terminal#8717]
# Description of the new feature/enhancement
Terminal is a useful tool, and the frequency of usage is very high. But sometime i don't need it, do not want it appears in the taskbar, because i switch between lots of windows with Alt+Tab. So i think we can add one feature minimize to TSA. If we want to use it again, we can invoke it quickly by hotkey such as Ctrl+~ like in VSCode.

# Proposed technical implementation details (optional)
See above.

**Comment by j4james** [comment]
I think you might be asking for #5727.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #5727 for more discussion.

/dup #5727
