### ISSUE TITLE
[FEATURE] Adding preferences (settings.json) synchronization method.

### ISSUE THREAD

**Issue by hadialqattan** [microsoft/terminal#8721]
# Description of the new feature/enhancement

I think it would be great if we have a method to enabled the Windows Terminal preferences (```settings.json```) synchronization, such as syncing with the singed in Microsoft Store account.

# Proposed technical implementation details (optional)

Adding a preference to the ```settings.json``` to enable the syncing.

**Comment by KalleOlaviNiemitalo** [comment]
This seems to be a popular request; please see <https://github.com/microsoft/terminal/issues/2933> and issues linked to it.

**Comment by DHowett** [comment]
Thanks! /dup #2933.
