### ISSUE TITLE
Customize profile appearance using emoji

### ISSUE THREAD

**Issue by vmp1r3** [microsoft/terminal#8722]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#icon
According to this document, on paragraph **Icon** I can set emoji as icon to my profile
I'm basically pasting emoji into settings like this `"icon": "📲"`, but Terminal runs with error without applying my emoji
I also tried variations with `"icon" : "smile"` and `"icon" : ":smile:"`

What am I doing wrong?

**Comment by skyline75489** [comment]
The PR related is #7830, which should be available in 1.5.3242.0. Are you using this version? Please do not just delete the issue template and fill in as much as info as possible.

**Comment by vmp1r3** [comment]
@skyline75489 No, unfortunately I'm using 1.4.3243.0 from Microsoft Store :(
No updates available for now

**Comment by skyline75489** [comment]
That's expected. 1.5.3242.0. is still in preview. If you are eager to have the shiny new features, you can search for "Windows Terminal Preview" in the Microsoft Store. The preview version can coexist with the stable version.

**Comment by zadjii-msft** [comment]
Yep, there's two release channels of the Terminal available - "Stable" is the one you have, which is currently v1.4.3243. There's also the "Preview" channel, which is v1.5.xxxx currently. Preview is a little less stable than release, but has access to new features faster. Preview can be aquired from the store entry for "Windows Terminal (Preview)".
