### ISSUE TITLE
System.ArgumentOutOfRangeException the actual value was -4

### ISSUE THREAD

**Issue by HermasciousLevander** [microsoft/terminal#8724]
# Environment

Windows build number: Win32NT 10.0.18363.0  Microsoft Windows NT 10.0.18363.0
Windows Terminal version: 1.3.2651.0

# Steps to reproduce

I'm honestly not sure what triggered this bug in the first place, but I'll do my best. Don't know it the terminal has a way to send logs or not, but inform me if it does, I'll see if they are still there once I'm back at work.

I encountered this error when I copied the script mentioned in [this post](https://www.reddit.com/r/PowerShell/comments/3egeo9/can_i_get_the_version_of_an_installed_application/cteve1f/).

I simply selected all the code from the pastebin preview on the post and pasted it into the terminal.

The script ended up being run before `Win32_Product -serverName $env:computername -displayName 'partial-app-name'` was because of the linebreak.

# Expected behavior

Assumed it would not cause an out of range exception.

# Actual behavior

[Prints this error](https://pastebin.com/B2VKvfwp).

**Comment by HermasciousLevander** [comment]
This error keeps being written to the terminal when I edit parts of the script.

CTRL + C does not cancel, left click produces the error.

Running the script stops the error, so long as you don't go back to it.

**Comment by zadjii-msft** [comment]
The error you shared pretty specifically states:

> `Oops, something went wrong.  Please report this bug with the details below.`
> `Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new`
  

So this looks like a PSReadline error that should be filed over at https://github.com/Powershell/PSReadline ...
