### ISSUE TITLE
Adjust width of PaneBorderSize

### ISSUE THREAD

**Issue by ycaedes** [microsoft/terminal#8726]
# Description of the new feature/enhancement
The width of the pane border is kind of **bold** and I'd like to request a feature that allows me to adjust its size. @zadjii-msft 

# Proposed technical implementation details (optional)

**Comment by mdtauk** [comment]
There would need to be a minimum size to account for touch targets, sure they could add a setting for it, but by time you add settings for every thing - it becomes a bit ridiculous

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #3063 for more discussion.

/dup #3063
