### ISSUE TITLE
The way Settings works sucks!  You should give us a a menu to select color and opacity settings!

### ISSUE THREAD

**Issue by RCooley56** [microsoft/terminal#8728]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.
2. If I list multiple bugs/concerns in this one issue, the core team may close my issue without further explanation or engagement.
3. If I write an issue that has many duplicates, the core team may close my issue without further explanation or engagement (and without necessarily spending time to find the exact duplicate ID number).
4. If I leave the title incomplete when filing the issue, the core team may close my issue without further explanation or engagement.
5. If I file something completely blank in the body, the core team may close my issue without further explanation or engagement.

All good? Then proceed!
-->

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by mdtauk** [comment]
A full Settings UI is in development, and will be released when it is done.

![image](https://user-images.githubusercontent.com/11050425/102535156-6ed50800-406d-11eb-94a8-7f4a99f968f2.png)

**Comment by RCooley56** [comment]
AWESOME!!!  You Rock!

**Comment by DHowett** [comment]
By the way? If you phrase things more kindly, rather than saying “THIS SUCKS!”, project maintainers are more likely to take you seriously. At the end of the day, we are people with feelings and stuff, so do consider that when you engage with an open-source project.
