### ISSUE TITLE
Right-click paste preserves the selection, but keyboard paste clears it

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#8729]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.685]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.5.3242.0
```

# Steps to reproduce

1. Configure `"copyOnSelect": true`.
2. Open a Command Prompt session in Windows Terminal.
3. Type `the longest wait`.
4. Press <kbd>Home</kbd> to move the cursor to the start of the command.
5. Double-click `longest` to select it. Windows Terminal copies `longest` to the clipboard, as well.
6. Click the right mouse button to paste `longest`.

# Expected behavior

`longestthe longest wait`, where nothing is selected.

# Actual behavior

`longestthe longest wait`, where `estthe ` is selected.

# Justification

If you change step 6 to paste by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> or <kbd>Shift</kbd>+<kbd>Insert</kbd>, instead of clicking the right mouse button, then Windows Terminal clears the selection. It feels inconsistent that pasting with the keyboard clears the selection but pasting with the mouse preserves it, especially when pasting also changes the text in the selected cells.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/3884> is for copying and this one is for pasting.

**Comment by zadjii-msft** [comment]
You're right, mouse pasting probably should also clear the selection. Thanks!

**Comment by Don-Vito** [comment]
@zadjii-msft - I can do it
