### ISSUE TITLE
The cursor position looks to be incorrect after output IVS ( Ideographic Variation Sequence : U+E0100 to U+E01EF)

### ISSUE THREAD

**Issue by zetamatta** [microsoft/terminal#8731]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
```

* Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

```
Windows Terminal version (if applicable):
```

*  1.4.3243.0

```
Any other software?
```

*  go1.15.6 windows/amd64 **OR** node.js v15.5.1

( I consider that any programming language program that supports Unicode(UTF8) can reproduce the behaviour. )

# Steps to reproduce

By **Golang**, execute `go run sample.go`

```sample.go
// sample.go
package main

import (
	"fmt"
)

func main() {
	fmt.Print("[\u908A\U000E0104]\n")
	fmt.Print("[\u908A\U000E0104")
	fmt.Print("]\n")
	fmt.Print("[ABCD")
	fmt.Print("]\n")
}
```

Or, on **node.js** 's command line , execute as below

```js
process.stdout.write("[\u908A\u{E0104}]\n")
process.stdout.write("[\u908A\u{E0104}") ; process.stdout.write("]\n")
process.stdout.write("[ABCD") ; process.stdout.write("]\n")
```

# Expected behavior

I expect that these text are output as below.

```
[邊󠄄]
[邊󠄄]
[ABCD]
```

The first line and the second line are same and no blank(space) exist anywhere.
The third line exists to show that the print/write function does not insert any blank.

# Actual behavior

The cursor position after output IVS( Ideographic Variation Sequence : U+E0100 to U+E01EF) seems to be  incorrect

```
[邊󠄄]
[邊󠄄 ]
[ABCD]
```

![image](https://user-images.githubusercontent.com/3752189/104117969-b72fcf00-5368-11eb-8fa9-75d24c3cba15.png)

![image](https://user-images.githubusercontent.com/3752189/104117512-34f1db80-5365-11eb-8a7d-134cc2c54812.png)

Would you please confirm the behaviour above ?

**Comment by skyline75489** [comment]
I think this is covered in #3546. The Unicode support is not complete yet.

**Comment by zadjii-msft** [comment]
I'm inclined to agree. Thanks @skyline75489!

/dup #3546
