### ISSUE TITLE
”Win + .” key combination inserts ”??”

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#8735]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.4.3243.0
```

# Steps to reproduce

If I press the `Win + .` key combination and insert an emoji in Windows terminal, it inserts ”??” even if the terminal input/output encoding should support it. 

Writing a Unicode sequence representing the emoji from a C# program or PowerShell script outputs the emoji as expected.

# Expected behavior

It insert the selected emoji.

# Actual behavior

It doesn't insert the emoji.
It inserts "??" instead.

**Comment by mdtauk** [comment]
What font are you using with Windows Terminal?

**Comment by patriksvensson** [comment]
The default one, Cascadia Code.

**Comment by j4james** [comment]
I think this is probably #1503.

**Comment by DHowett** [comment]
Hard to tell without the bug template including version number, which shell/other software you're using, etc. :smile:

**Comment by patriksvensson** [comment]
@DHowett Sorry, someone linked to the blank issue template on Twitter. Will fill out info once I'm at a computer.

**Comment by patriksvensson** [comment]
@DHowett I've updated the information in the issue.

**Comment by zadjii-msft** [comment]
This sure looks like #1503 and #190 to me. Emoji in the input line just don't play nice quite yet.

/dup #190
/dup #1503

**Comment by DHowett** [comment]
If you're using PowerShell, there's an additional PSReadline issue preventing this from working properly.
