### ISSUE TITLE
backspace cause flash in git bash profile if no characters to delete

### ISSUE THREAD

**Issue by DailyShana** [microsoft/terminal#8737]
# Environment

```none
Windows build number: [10.0.19042.685]
Windows Terminal version (if applicable): 1.4.3243.0

Any other software? git for windows 2.30.0
```

# Steps to reproduce
1. add the following profile to the settings.json (suppose git for windows in installed in C:/Program Files)
```json
        {
            "name" : "Git Bash",
            "commandline" : "C:/Program Files/Git/bin/bash.exe",
            "startingDirectory": "%USERPROFILE%",
            "icon" : "C:/Program Files/Git/mingw64/share/git/git-for-windows.ico",
            "colorScheme": "Mintty",
            "cursorColor": "#BFBFBF"
        }
```
also add the following color scheme to the settings.json
```json
        {
            "name": "Mintty",
            "foreground": "#BFBFBF",
            "background": "#000000",
            "black": "#000000",
            "red": "#BF0000",
            "green": "#00BF00",
            "yellow": "#BFBF00",
            "blue": "#0000BF",
            "purple": "#BF00BF",
            "cyan": "#00BFBF",
            "white": "#BFBFBF",
            "brightBlack": "#404040",
            "brightRed": "#FF4040",
            "brightGreen": "#40FF40",
            "brightYellow": "#FFFF40",
            "brightBlue": "#6060FF",
            "brightPurple": "#FF40FF",
            "brightCyan": "#40FFFF",
            "brightWhite": "#FFFFFF"
        }
```

2. open windows terminal, and open git bash in windows termial
3. type backspace
# Expected behavior

nothing happens

# Actual behavior
if there is no character to delete, it flashes:
![aaa1](https://user-images.githubusercontent.com/8469304/104148991-8e164980-540f-11eb-84b0-014dce25418b.gif)

**Comment by DHowett** [comment]
Yes, this is the “visual bell” that git bash uses.

**Comment by DailyShana** [comment]
but the original git bash (C:\Program Files\Git\git-bash.exe or run C:/Program Files/Git/bin/bash.exe directly) do not have this

**Comment by DHowett** [comment]
Yes, the windows console only recently got support for the screen inversion control sequence that bash uses for its visual bell. Once you have the new version of Windows (> 10.0.19042) it will act the same.

**Comment by DailyShana** [comment]
I see, thank you for explanation.
