### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by iandk** [microsoft/terminal#8739]
# Environment

Microsoft Windows [Version 10.0.19042.685]
# Steps to reproduce

Just open Terminal

# Expected behavior
No rendering issues

# Actual behavior
![image](https://user-images.githubusercontent.com/13487247/104202289-03dbde80-542b-11eb-86d7-c93dfdd0c560.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue - please refer to /dup #6142, which is being tracked upstream at microsoft/microsoft-ui-xaml#2550. The WinUI team would definitely be interested in hearing from you. Thanks!
