### ISSUE TITLE
Always run as Administrator

### ISSUE THREAD

**Issue by MFry** [microsoft/terminal#8740]
Currently, to run windows terminal in Administration mode I have to find the app > remember to right click on it  > select more > and run as administrator. 
The problem with this is that I have almost never a reason to not run it in admin mode and its getting frustrating to run some script find out that its not running with elevated privilege's close the program run through the above mentioned flow and start the entire script(s) over. 

So far, I have not found a way to run this app by default with admin rights nor do I see anything online to that effect.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22run+as+Administrator%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #632, #5000, #8455 for more discussion. 

/dup #632
