### ISSUE TITLE
Needs search

### ISSUE THREAD

**Issue by rwrife** [microsoft/terminal#8743]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
"Needs search" => "has search"

press ctrl+shift+f

please file issues that are more descriptive in the future :smile:
