### ISSUE TITLE
FontSize setting control should only accept a number between 0 and 128

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8759]
# Steps to reproduce

1. Go to "Appearance"
2. Get into the font size box.
3. Press Ctrl+Tab and it starts inserting literal tabs. Keep doing it and it becomes a super long boi to the right instead of wrapping like the same behavior in the Font Face text block. 

# Expected behavior

non-numeric content should not be allowed. We should only accept a number between 0 and 128.

# Actual behavior

Expands to the right and tabs are inserted.

# Additional Details

~This is probably a simple fix. Just a matter of adding the wrap styling to CommonResources.xaml. Take a look at what wrap styling was already added to other controls. In fact, if any of the other control styles support wrap styling, feel free to add them there too.~
We need to look into what kind of restrictions we can put on this control. Hopefully it supports limiting content to numbers and limiting the range to 0 and 128. Some of this may have to be filed upstream.

**Comment by DHowett** [comment]
Sorry, is the bug that it doesn't wrap or that you can enter non-numeric content in it such that it needs to wrap? It only ever contains a single number between 0 and 128. There's no need for it to wrap.

**Comment by carlos-zamora** [comment]
> Sorry, is the bug that it doesn't wrap or that you can enter non-numeric content in it such that it needs to wrap? It only ever contains a single number between 0 and 128. There's no need for it to wrap.

Good point. If we only ever accept a value between 0 and 128. We should make the control enforce that (if possible). Updating issue appropriately.

**Comment by zadjii-msft** [comment]
Alright so 90% of this issue is tracked upstream at microsoft/microsoft-ui-xaml#3466.

The Min/Max thing, that we _can_ do.
