### ISSUE TITLE
Missing setting functionality in Settings UI

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8761]
There are a few special behaviors in our setting model for existing settings. The Settings UI could do a better job of representing them:

- "startingDirectory" being null is interpreted as "inherit from parent process"
  - (similar proposed design as above) add a checkbox labelled "use parent process' directory"
  - When checked, the text box and browse button are disabled.

**Comment by zadjii-msft** [comment]
I'm moving the "desktop" background image feature to #8763, so I can just do all of that in one go.
