### ISSUE TITLE
Clickable-hyperlinks don't work?

### ISSUE THREAD

**Issue by rpavlik** [microsoft/terminal#8762]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): Latest store version at filing, default settings file says 1.4.3243.0

Any other software? Powershell Core 7.1.0 is the main shell I use. Also using the "powerline in powershell" per the instructions in the docs. But, I'd be surprised if either of those mattered: I can echo the same URL from below in a WSL shell and it is similarly unclickable.
```

# Steps to reproduce

I push something to GitHub, and a URL is displayed. But, control-click on it does nothing. You might be able to dump this from a file to terminal to repro.

```none
ryanp@RYZENSHINE-WIN  E:\src-ssd\hello_xr_hpp   pr26-210112 ≢                                              [11:53]
❯ git push -u origin pr26-210112
Enumerating objects: 89, done.
Counting objects: 100% (89/89), done.
Delta compression using up to 16 threads
Compressing objects: 100% (80/80), done.
Writing objects: 100% (83/83), 151.65 KiB | 11.67 MiB/s, done.
Total 83 (delta 56), reused 12 (delta 2), pack-reused 0
remote: Resolving deltas: 100% (56/56), completed with 6 local objects.
remote:
remote: Create a pull request for 'pr26-210112' on GitHub by visiting:
remote:      https://github.com/rpavlik/hello_xr_hpp/pull/new/pr26-210112
remote:
To https://github.com/rpavlik/hello_xr_hpp.git
 * [new branch]      pr26-210112 -> pr26-210112
Branch 'pr26-210112' set up to track remote branch 'pr26-210112' from 'origin'.
```

# Expected behavior

Expected underlining on hover with ctrl key down, and upon click on link with ctrl key down, for the page to open in my default browser, just as happens in the vscode terminal.

# Actual behavior

Nothing happens: acts just like I control-clicked any normal text.

I have tried re-generating config file and just transplanting changes, no luck. Changes are pretty minimal: I disabled ctrl-c and ctrl-v as copy/paste, re-arrange some profiles, add two new ones, and add some defaults for powerline and acrylic. (Turning those off doesn't fix it either)

I tried really hard to figure out how to get it to work: waited a long time after release, manually checked for updates in the store, dug through all the docs, but I can't figure out what I'm doing wrong.

**Comment by rpavlik** [comment]
Easier repro: just use the https://aka.ms/powershell that gets printed in each new pscore tab. It does work in terminal preview, which I just installed...

**Comment by zadjii-msft** [comment]
Fortunately, there's nothing in the config that affects how hyperlinks work - they should "just work". 

This is a wild guess - are you sure that the link didn't actually open in your existing browser window, but left the focus on the Terminal? We've had some weird z-ordering issues in the past, and I wouldn't be surprised if the system didn't know how to switch focus away from the Terminal onto the window it just opened a tab in.

**Comment by zadjii-msft** [comment]
Uhg, ignore me. 

Turns out auto-detecting hyperlinks were only added in 1.5+. See [the original PR](https://github.com/microsoft/terminal/pull/7691#issuecomment-725580515). So this is "as expected" - 1.4 doesn't support them yet 😄

**Comment by rpavlik** [comment]
oops, thanks 🤦
