### ISSUE TITLE
Polish Settings UI: Profile page

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8764]
- [x] Appearance:
  - I don't understand what the cursors look like by reading the words. give me pictures plz. 
- [x] Appearance: (MG: I'll do this one)
  - Check/uncheck Enable Acrylic box and the scroll bar dances (because the opacity slider appears off the screen to the bottom…. Which isn't obvious. Can we scroll it onto the screen?) 
- [ ] Browse buttons should be vertical center aligned
  - this one is going to be difficult to do until #8269 lands. The "center" is calculated to be the (header + control)/2. So changing vertical alignment to "center" will look off center. Using "bottom" for now.
  - ![misaligned buttons](https://user-images.githubusercontent.com/11050425/104355862-1fdd8f80-54c0-11eb-967b-89a3b06db0b0.png)
- [x] For Base Layer, we should not be allowed to set "commandline" or "hidden".

**Comment by zadjii-msft** [comment]
Notes:

> * Check/uncheck Enable Acrylic box and the scroll bar dances (because the opacity slider appears off the screen to the bottom…. Which isn't obvious. Can we scroll it onto the screen?)

If we try doing this on `Checked`, then it seems like we can't scroll to the slider quite yet. Since it's not yet in the view, then I think if we do `Appearance_ScrollViewer().ChangeView`, the final delta is greater than the available space, so it just does nothing. We need to wait for the slider to actually become visible before scrolling it in.

We should pop a `PropertyChanged` onto the acrylic slider, then use the visibility->true as a chance to scroll to it.

**Comment by carlos-zamora** [comment]
Since we're removing `commandline` from Base Layer, should we also remove `hidden` from there?

CC @cinnamon-msft @DHowett

**Comment by DHowett** [comment]
**absolutely**

**Comment by zadjii-msft** [comment]
Alright so, more on the acrylic slider. 

We can't scroll down to it when the visibility changes, because it seems like the visibility changes _before_ the new layout with the slider in it is computed. That means we can't use that as a chance to scroll the view either. 

I also tried moving focus to the slider manually when the box is checked. That has the same problem though - the slider isn't visible, so it can't have focus yet.

So here's a novel idea - what if we just moved the "Grouping: Window" _below_ the acrylic slider? That doesn't _really_ fix this, but it makes it less likely the user has scrolled to exactly the position of the acrylic checkbox. This means it's more likely that the slider will appear on-screen. 

Thoughts?

We'll face the same problem inevitably when we hide the BG image settings until they've set a path.

**Comment by DHowett** [comment]
Hey, I’m open to moving stuff around so it hides the issue :)

**Comment by zadjii-msft** [comment]
_whoop_

**Comment by PankajBhojwani** [comment]
> Padding:
> it's weird that it's a free-form entry field that we expect a specific format in w/ no validation?
> "4, 5, 6" silently does nothing
> This could probably use a better design

What do we think of simply having 4 number boxes for left, top, right, bottom padding?

**Comment by carlos-zamora** [comment]
> > Padding:
> > it's weird that it's a free-form entry field that we expect a specific format in w/ no validation?
> > "4, 5, 6" silently does nothing
> > This could probably use a better design
> 
> What do we think of simply having 4 number boxes for left, top, right, bottom padding?
> 
> EDIT: This will mean that we'll probably need some separate function in `Profiles.cpp` that takes all 4 numbers and converts them to one `hstring` to actually set the profile's `Padding` setting however

I'm ok with this design. We'd be missing out on the `#` and `#,#` shorthand, but I think that's ok.

CC @cinnamon-msft for design approval, and curious what other team members think.

**Comment by zadjii-msft** [comment]
Yea I think this is a _way_ better design. This actually makes it obvious what you're doing when you set 1, 2, 3, 4, because honestly, I don't remember what order the properties are in.

**Comment by DHowett** [comment]
I dunno, maybe I'd swing in the other direction. One slider that controls a uniform padding on all sides. If we have a compelling need to surface caddywampus padding we can revisit that decision later?

**Comment by zadjii-msft** [comment]
Well, what happens if I have `1, 2, 3, 4` currently, and a UI that only exposes the single value version of the property? Does that vector end up getting reduced to a scalar value?

**Comment by cinnamon-msft** [comment]
For Dustin's example, what if someone already set caddywampus padding in their JSON?

I like Pankaj's 4 number box idea, with the tooltips saying which direction they're for.

**Comment by DHowett** [comment]
Same even keel behavior we use for all other weird JSON settings. We ignore them, we don't display them, or we simplify them and if the user interacts with the simplified value _they get a simplified result_. They chose to type in some weird numbers into their JSON file, they **always** have that escape hatch.

**Comment by zadjii-msft** [comment]
Well yea, but like, if we try jamming the value `1, 2, 3, 4` into a single number box, let's say we show them `1`. Does `1, 2, 3, 4` roundtrip if they _don't_ edit that particular setting? I'm not sure that it would with the current view model. I thought we didn't have a way of knowing if a setting changed or not, and we ended up just re-serializing the entire profile. I'm worried that would end up round-tripping `1, 2, 3, 4` as `1`.

**Comment by DHowett** [comment]
I just think that this is a terribly confusing UI, don't you?

![image](https://user-images.githubusercontent.com/189190/105075561-c08efa80-5a3e-11eb-87ba-22269f08e024.png)

Tooltips don't make up for a poor experience.

---

The profile view model doesn't call the profile's setters for any property that's not touched. Touch it, it's set. Don't touch it, it's fine. The Profile Settings model still contains `1,2,3,4` until the view connected to the padding is touched and edited.

**Comment by zadjii-msft** [comment]
I suppose I imagined like, 4 boxes in a grid
![image](https://user-images.githubusercontent.com/18356694/105076317-8595c280-5a50-11eb-96cc-68973e690fbc.png)

<hr>

> The profile view model doesn't call the profile's setters for any property that's not touched. Touch it, it's set. Don't touch it, it's fine. The Profile Settings model still contains `1,2,3,4` until the view connected to the padding is touched and edited.

Then I'm okay with 1 box

**Comment by carlos-zamora** [comment]
For reference, FluentTerm uses a single slider with a max of 64px, it seems. I have to admit, the slider looks way cleaner.

How's this for an idea:
- Checkbox --> "Use complex padding"
- unchecked --> slider appears to control all 4 sides with one value
- checked --> 4 number pickers, each labelled appropriately (personally prefer text beside each one, but we can decide on that later)

This way, if the user has a simple padding, we represent it as a slider, and more complex paddings can still be represented.

**Comment by DHowett** [comment]
I'm proposing the same thing as @carlos-zamora, except we skip the entire checkbox and four boxes bit until somebody complains.

**Comment by cinnamon-msft** [comment]
I like the simplicity of the slider. I think I'm just not understanding what the UI will show if someone has `"1, 2, 3, 4"` already set?

**Comment by DHowett** [comment]
Let's just show the largest one. I bet the number of times we hit this in the wild will be less than the number of comments we've spent on it! :wink:

**Comment by mdtauk** [comment]
So is the Slider decided on?  Ideally we would have each of the directions adjustable, and whilst I can think of a UI to use for it, it wont be as compact as a slider or 4 textboxes in a line.

![Box text entry](https://user-images.githubusercontent.com/7389110/105556687-6cb43800-5d02-11eb-8f01-863fa370e6d5.png)
_Box text entry_



![Text entry with guide](https://user-images.githubusercontent.com/7389110/105556730-835a8f00-5d02-11eb-8e93-56476f68c300.png)
_Text entry with guide_


![Dual sliders](https://user-images.githubusercontent.com/7389110/105556769-9bcaa980-5d02-11eb-88ca-88b8c21a0637.png)
_Dual sliders_


----

As it will still be possible to have individual values for each edge by editing the JSON, what will the UI show, if custom values have been set?

**Comment by DHowett** [comment]
@mdtauk The UI will show the max value for right now. When it's not -2 days from our ship stop date for 1.6, we can revisit multi-side padding. I'd love for someone to do this RIGHT, we just didn't have time for today.

**Comment by DHowett** [comment]
(yeah that's a negative two, you can tell how tight a ship I run here!)

**Comment by DHowett** [comment]
I love the middle one. Text entry with guide. Sorry for so many separate comments :smile:

**Comment by carlos-zamora** [comment]
Since there's been a decent amount of discussion revolving around how to represent padding in the settings UI, I've moved that out to #9127.

This issue now mainly covers miscellaneous polish of the profile page.
