### ISSUE TITLE
Make SettingsTab respect keybindings

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8767]
# Description of the new feature/enhancement

Some keybindings should be respected when in the settings tab. At the very least, we should respect "closeTab".

Ideally, we'd respect all app-level keybindings. This includes tab management, mode switching (i.e always on top, focus mode, fullscreen, etc...), and command palette. In the end, we'll really have "support" for "all" keybindings because the architecture checks if there's a terminal that can actually handle the action.

**Comment by Don-Vito** [comment]
@carlos-zamora - does tab-switcher works for you when you attempt to start from the settings tab? As it doesn't for me - I am stuck there and cannot escape :smile:

**Comment by carlos-zamora** [comment]
> @carlos-zamora - does tab-switcher works for you when you attempt to start from the settings tab? As it doesn't for me - I am stuck there and cannot escape 😄
> 
> I mean literally cannot escape - is there a way to leave the settings tab with a keyboard?
> 
> Update: I succeeded to escape, by focusing the tab view item 😊 Wondering why the key event doesn't propagate to the terminal page..

The short version for why it doesn't work is because we handle keybindings pretty weird. When we create a `TermControl`, we pass in the keybindings (via `TerminalSettings`). From there, we detect keystrokes and go back to TermApp to actually do the action.

So basically, we need to pass these keybindings over to the Settings UI and detect them there. But then we get into another problem, not all keybindings should be valid (i.e. copy/paste shouldn't be valid). I think CommandPalette got around this issue by specifically detecting only a few of them?

Long-term, a refactor of our actions model needs to be done. Half of that refactor is being able to identify where a defined action came from (defaults.json vs settings.json). The other half (more relevant to this discussion) is figuring out a better way to detect keybindings. We still get some weird behavior like not being able to detect keybindings in a search box.

**Comment by Don-Vito** [comment]
@carlos-zamora - we recently added keybinding handling to the TerminalPage - see the key-down handler there. So I would expect the routed event to propagate there if not handled by the settings tab. 

For instance this is how it works when you issue a chord in the command palette or when focused on the searchbox. 

The terminal control is a special case because we wanted to reverse the order of handling (I am still not sure why preview key down in the TerminalPage won't do the job).

However here I hoped it will work the same. But something seems to swallow the events.

**Comment by zadjii-msft** [comment]
GAH

Okay, it was trivial enough to just hook the settings UI up to the action dispatcher. 

```diff
diff --git a/src/cascadia/TerminalApp/TerminalPage.cpp b/src/cascadia/TerminalApp/TerminalPage.cpp
index f5d700e4e..a1c618702 100644
--- a/src/cascadia/TerminalApp/TerminalPage.cpp
+++ b/src/cascadia/TerminalApp/TerminalPage.cpp
@@ -2806,6 +2806,7 @@ namespace winrt::TerminalApp::implementation
             {
                 sui.SetHostingWindow(reinterpret_cast<uint64_t>(*_hostingHwnd));
             }
+            sui.PreviewKeyDown({ this, &TerminalPage::_KeyDownHandler });

             sui.OpenJson([weakThis{ get_weak() }](auto&& /*s*/, winrt::Microsoft::Terminal::Settings::Model::SettingsTarget e) {
                 if (auto page{ weakThis.get() })
```

That'll do the job. However, then we have the very real problem that we don't actually check if the control is valid when we do things like 

```c++
    void TerminalPage::_HandleAdjustFontSize(const IInspectable& /*sender*/,
                                             const ActionEventArgs& args)
    {
        if (const auto& realArgs = args.ActionArgs().try_as<AdjustFontSizeArgs>())
        {
            const auto termControl = _GetActiveControl();
            termControl.AdjustFontSize(realArgs.Delta());
            args.Handled(true);
        }
    }
```

So we'll need to audit _all_ the actions to make sure they're safe to use from the context of the SUI.

**Comment by Don-Vito** [comment]
> 
> 
> GAH
> 
> Okay, it was trivial enough to just hook the settings UI up to the action dispatcher.
> 
> ```diff
> diff --git a/src/cascadia/TerminalApp/TerminalPage.cpp b/src/cascadia/TerminalApp/TerminalPage.cpp
> index f5d700e4e..a1c618702 100644
> --- a/src/cascadia/TerminalApp/TerminalPage.cpp
> +++ b/src/cascadia/TerminalApp/TerminalPage.cpp
> @@ -2806,6 +2806,7 @@ namespace winrt::TerminalApp::implementation
>              {
>                  sui.SetHostingWindow(reinterpret_cast<uint64_t>(*_hostingHwnd));
>              }
> +            sui.PreviewKeyDown({ this, &TerminalPage::_KeyDownHandler });
> 
>              sui.OpenJson([weakThis{ get_weak() }](auto&& /*s*/, winrt::Microsoft::Terminal::Settings::Model::SettingsTarget e) {
>                  if (auto page{ weakThis.get() })
> ```
> 
> That'll do the job. However, then we have the very real problem that we don't actually check if the control is valid when we do things like
> 
> ```c++
>     void TerminalPage::_HandleAdjustFontSize(const IInspectable& /*sender*/,
>                                              const ActionEventArgs& args)
>     {
>         if (const auto& realArgs = args.ActionArgs().try_as<AdjustFontSizeArgs>())
>         {
>             const auto termControl = _GetActiveControl();
>             termControl.AdjustFontSize(realArgs.Delta());
>             args.Handled(true);
>         }
>     }
> ```
> 
> So we'll need to audit _all_ the actions to make sure they're safe to use from the context of the SUI.

Or we can bind only switch tab. The way we did it in cmdpal? If this is OK I can try to do it.

**Comment by zadjii-msft** [comment]
Here's my thought though - like _real long term_, I want to be able to have panes that don't host terminals in them. So _eventually_, we'll want this work to be done. Might as well do it now. 

Plus, we definitely want `SwitchToTab`, but also probably `NewTab`, `CloseTab`... I'm not sure if that's it or now. May as well just go for it and do 'em all.

**Comment by Don-Vito** [comment]
> 
> 
> Here's my thought though - like _real long term_, I want to be able to have panes that don't host terminals in them. So _eventually_, we'll want this work to be done. Might as well do it now.
> 
> Plus, we definitely want `SwitchToTab`, but also probably `NewTab`, `CloseTab`... I'm not sure if that's it or now. May as well just go for it and do 'em all.

So let's do it now.
2 questions:
1. Is it a blocker for 1.6 preview?
2. Are we OK to push a fix for all bindings to 1.6 preview?

**Comment by zadjii-msft** [comment]
IMO yes and yes? @DHowett back me up on this decision though. I'm working through em all now, but we're running short on runway

**Comment by Don-Vito** [comment]
> 
> 
> IMO yes and yes? @DHowett back me up on this decision though. I'm working through em all now, but we're running short on runway

OK.. there are hardly 7 lines that require a fix.

**Comment by zadjii-msft** [comment]
From @rashil2000 in #8987:

> # Environment
> ```
> Windows build number: 10.0.19042.746
> Windows Terminal version (if applicable): 1.6.10272.0
> ```
> 
> # Steps to reproduce
> Multiple ways. Open the Settings UI tab using your keybind (like Ctrl+Shift+,). Now use other keybindings, like `toggleFocusMode` (Shift+F11), or Command Pallete (Ctrl+Shift+P), or JSON file (Ctrl+,), or new tab (Ctrl+Shift+T).
> 
> # Expected behavior
> They should open their respective actions, like any other tab.
> 
> # Actual behavior
> None of these commands seem to work.
> Nothing happens.
> 
> ## Context
> I have set my `launchmode` to `focus`, so each WT sessions opens in focus mode. But when I open the Settings UI from there, I get stuck on that tab, because the toggleFocusMode keybind does not do anything, and I can't even open a new tab.

**Comment by zadjii-msft** [comment]
If we're nor going to have all keybindings work, then we'll definitely want to add
* close window
* toggleFocusMode
* toggleFullscreen
* command palette?

**Comment by tabedzki** [comment]
I agree about wanting to have at a minimum those four features. I disagree about the copy/paste not being required since there is a section to input the whitespace characters as well as paths for the profiles. 

I personally am not a fan of the new Windows Settings/the newer Metro (Fluent design?) style. I still try to use Control Panel for as much as possible since the older one included more information without feeling as visually bloated as the newer one. The below screenshot has a ton of whitespace on the right hand side, on the sidebar and for the "Discard changes" and "Save" buttons while also requiring the user to scroll down to see all the options within the same section ("Appearance"). 
Is there an easy way to use something similar to VSCode's settings menu (I am fully aware that I have no idea how long it takes to make a UI so this may be the user asking for something unrealistic)? 
![image](https://user-images.githubusercontent.com/35670232/118569963-16538500-b749-11eb-9086-173ce78c5ae4.png)

**Comment by zadjii-msft** [comment]
> I disagree about the copy/paste not being required since there is a section to input the whitespace characters as well as paths for the profiles.

Oh, we can't have the copy and paste keybindings that you've set for the Terminal work in the SUI, because of the way those keybindings are handled. Those two are keybindings specific to the `TermControl` (the control hosting the terminal content), that specifically tell it to use those keystrokes for copy/paste. We can overwrite those keystrokes, because we own the entire input to the TermControl. 

Normal xaml `TextBox`s throughout the SUI will still have copy/paste on <kbd>ctrl+c</kbd><kbd>ctrl+v</kbd>, but we can't overload those controls.


> The below screenshot has a ton of whitespace on the right hand side, on the sidebar and for the "Discard changes" and "Save" buttons while also requiring the user to scroll down to see all the options within the same section ("Appearance").
(I am fully aware that I have no idea how long it takes to make a UI so this may be the user asking for something unrealistic.)

Trust me, the Settings app team hears this feedback _constantly_. We're just trying to be consistent with the rest of the platform, and that means following their choices.

**Comment by rashil2000** [comment]
> Trust me, the Settings app team hears this feedback constantly. We're just trying to be consistent with the rest of the platform, and that means following their choices.

The system settings app tries to utilize the whitespace on the right by showing help links, extra useful info etc. Maybe the terminal can do that too...

**Comment by zadjii-msft** [comment]
@rashil2000 it's a good thing we're already tracking that in #9824

**Comment by tabedzki** [comment]
> 
> Oh, we can't have the copy and paste keybindings that you've set for the Terminal work in the SUI, because of the way those keybindings are handled. Those two are keybindings specific to the `TermControl` (the control hosting the terminal content), that specifically tell it to use those keystrokes for copy/paste. We can overwrite those keystrokes, because we own the entire input to the TermControl.
> 
> Normal xaml `TextBox`s throughout the SUI will still have copy/paste on ctrl+c,ctrl+v, but we can't overload those controls.

Ahh, so it is the user-defined copy/past you all were talking about. I should've thought that through before commenting. Apologies.

> 
> Trust me, the Settings app team hears this feedback _constantly_. We're just trying to be consistent with the rest of the platform, and that means following their choices.

I forgot that Terminal was a UWP app as opposed to a traditional .exe like vscode and others are. I've noticed in Terminal, Settings and Feedback Hub, you cannot drag the size of sidebar. Is that something that is hard defined in the UWP design language or can that be implemented on an app-by-app basis? 

Lastly (and out of scope of terminal), is there a way to give feedback to MSFT about the Settings app in general and asking them to not get rid of Control Panel in a future update?  (I don't know if they were planning on removing it in favor of Settings UWP completely.)

**Comment by zadjii-msft** [comment]
>  Terminal was a UWP app as opposed to a traditional .exe like vscode and others are. 

That's not strictly true - it doesn't really make sense to think about apps as Win32 vs UWP apps anymore. The Terminal actually is a traditional exe, that just so happens to be using UWP XAML for its UI. Nowadays, win32 applications have access to basically the whole gamut of UWP APIs, so the line between the two is blurrier and blurrier.

> I've noticed in Terminal, Settings and Feedback Hub, you cannot drag the size of sidebar. Is that something that is hard defined in the UWP design language or can that be implemented on an app-by-app basis?

I believe that's just a hardcoded part of the `NavigationView` in WinUI.

> Lastly (and out of scope of terminal), is there a way to give feedback to MSFT about the Settings app in general and asking them to not get rid of Control Panel in a future update? (I don't know if they were planning on removing it in favor of Settings UWP completely.)

Frankly, I don't really know. Every team happens to have their own ways of doing things. Typically the Feedback hub is a good place to start. I don't know if UserVoice is still a thing, but I know we used that before we moved to being entirely on GitHub.
