### ISSUE TITLE
Polish Settings UI: Keyboard navigation (w/ tab key)

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8768]
This is a list of issues we've found when trying to navigate the Settings UI using _only_ the keyboard:
- [ ] On Color Schemes edit page (with a custom scheme open so it's editable) use the tab key to navigate between controls. Press Tab from +AddNew and it will go select nothingness. One more tab will select the Black box. It should probably never select nothingness. 
  - It also selects nothingness between Bright White and Foreground. Bright White (Tab) Nothingness (Tab) Foreground. 
- [x] On all pages, it appears that once you tab all the way to Apply in the bottom right corner… you get stuck. I think tab navigation is supposed to be fully circular (going back to the first thing or the most Shift+Tabby thing) and around again. 
- [x] Open SUI. Switch to a TerminalTab. Invoke "open Settings UI" kbd again. Hamburger menu focused.
  - Expected: highlight last highlighted setting

Potentially upstream issues:
- [ ] tab navigation when in left bar...
  - <space> updates header, but not frame
- [ ] individual radio buttons cannot be selected via keyboard (See https://github.com/microsoft/microsoft-ui-xaml/issues/3156)
- [ ] pressing letter key in a combobox does not navigate to first combobox starting with that letter

**Comment by carlos-zamora** [comment]
Ok. I've done a bit of research on this issue. Here's some notes:
- color schemes page
  - will be fixed as a part of the color schemes redesign
- focus doesn't cycle on save button
  - #9126 - not that bad
- highlight last highlighted setting
  - Tried using the `FocusManager` to store the last focused item (in `SettingsTab` and `MainPage`). Neither worked. This will require a more complex solution.
  - I'll be pulling this out into its own issue and labelling it as help wanted. I feel that it doesn't have that high of a priority (at least compared to other things).
- tab navigation in left bar
  - this one now feels like it's by design. Closing.
- radio buttons
  - already tagged
- combobox
  - This one's tough. `ComboBox` has an `IsTextSearchEnabled` property that enabled this functionality. However, it only works if the list of items are "strings". Since we're defining an item template to add an icon or directly bind to the settings model, we can't explicitly use this feature _and_ have icons at the same time.
  - I'm going to file a feature request on XAML for this one.

**Comment by carlos-zamora** [comment]
The ComboBox feature request is being tracked in https://github.com/microsoft/microsoft-ui-xaml/issues/4182

**Comment by DHowett** [comment]
Did you try StMoy's suggestion?

**Comment by carlos-zamora** [comment]
> Did you try StMoy's suggestion?

Not yet. I've been working on the color schemes page redesign.
