### ISSUE TITLE
Polish Settings UI: Very annoying functionality

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8769]
- [x] Go to any profile -> Go to Appearance or Advanced tab -> Hit 'Apply': SUI automatically switches to the General tab (can be annoying if the user just wants to check out what a setting does) 
- [x] Appearance -> Open 'Color scheme' dropdown -> Cannot dismiss the dropdown by clicking somewhere else 
	- Moved to Light-dismiss doesn't work on ComboBox in XAML Islands https://github.com/microsoft/microsoft-ui-xaml/issues/3961
- [ ] tooltips on radio buttons currently describe entire set of options. Need descriptions on each individual setting options.
	- [ ] Case in point: What does "uniform to fill" mean? On Profiles/Appearance. It's impossible to know what these enum values really mean.
	- [x] we got rid of these

**Comment by zadjii-msft** [comment]
RE: the Profile pivot resetting

In a5a46af73, I'm doing something similar to how we want to fix this. We need to stash internal navigation state in the `{page}NavigationState`, and keep a singleton instance of each page's state in the `MainPage`. That way, we can have the `Profiles` page update the selected pivot within the NavigationState, and the _next_ instance of `Profiles` will be able to look up that state.

**Comment by carlos-zamora** [comment]
> - [ ] tooltips on radio buttons currently describe entire set of options. Need descriptions on each individual setting options.
	- [ ] Case in point: What does "uniform to fill" mean? On Profiles/Appearance. It's impossible to know what these enum values really mean.

So, this is a tough one. It looks like we can either do a single tooltip on the entire `RadioButtons` (note the plural) control, or on each individual `RadioButton`. Not both.

In general, we should make the choices and header as descriptive as possible to get around this issue. But that's not always possible, unfortunately.

I think we should go with the individual `RadioButton` descriptions and that way we can attach tooltips and automation properties to them. That's probably the cleanest way around this issue.

**Comment by zadjii-msft** [comment]
RE: tooltips on radio buttons: The RadioButtons were removed in 1.13, so now we need to add the tooltips to the entries in the dropdown.

**Comment by zadjii-msft** [comment]
> Cannot dismiss the dropdown by clicking somewhere else


We got rid of almost all of these with Controlsv2. Except the default profile one...? (#13731)
