### ISSUE TITLE
PROMPT_COMMAND (with current time) breaks cursor position

### ISSUE THREAD

**Issue by black-snow** [microsoft/terminal#8776]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal
Version: 1.4.3243.0

WSL2 Ubuntu 20.x
```

# Steps to reproduce

Set your `PROMPT_COMMAND` to pretty much anything.

```bash
export PROMPT_COMMAND="echo -n \[\$(date +%H:%M:%S)\]\ "
```

Now use the arrow keys or ctrl+r to go back in history to some earlier command, preferably a long one.
Navigate your cursor left with the home key. (Or arrow up two times+)
Your cursor should now be somewhere before the actual prompt space, somewhere in your path or pc name.

# Expected behavior

The cursor should be right after the `$`.

# Actual behavior

Described above. Cursor is not aligned with the visible content.

**Comment by zadjii-msft** [comment]
Weird so I'm trying this just by running a quick
```
PROMPT_COMMAND="echo -n \[\$(date +%H:%M:%S)\]\ " bash
```

but I can't get this to repro. I do seem to get some weird behavior with the <kbd>ctrl+r</kbd> reverse search, but not with the arrow/home navigation. It's almost like bash is just ignoring the `PROMPT_COMMAND` part of the prompt when it's redrawing:

![image](https://user-images.githubusercontent.com/18356694/104484668-2be45280-558f-11eb-947a-3de445529528.png)
![image](https://user-images.githubusercontent.com/18356694/104484725-3bfc3200-558f-11eb-9098-8d98e76e8e58.png)


But you know, the same thing happens with `gnome-terminal`
![image](https://user-images.githubusercontent.com/18356694/104484851-61893b80-558f-11eb-85c8-b4f019d2f5d1.png)


So I doubt that what I'm seeing is unique to the Terminal

**Comment by black-snow** [comment]
@zadjii-msft thanks for the quick reply. This does, however, not happen with the bash exe. It's just a minore issue but quite annoying from time to time.

**Comment by zadjii-msft** [comment]
> This does, however, not happen with the bash exe.



Wait, if this isn't happening with `bash`, then which shell are you using inside WSL?

**Comment by black-snow** [comment]
I was talking about `C:\Windows\System32\bash.exe`

**Comment by zadjii-msft** [comment]
Oh, that's actually just an alias for starting up `bash` in WSL. `bash` is typically the default shell for most distros, so I'm assuming that's the one you're using. It looks to me like you might be running afoul of the following: https://unix.stackexchange.com/a/31643

**Comment by DHowett** [comment]
Yes, that is exactly it. Bash tries to count how long the prompt is, and when you run a command _before_ the prompt is printed it cannot count that command's characters. :smile:

**Comment by black-snow** [comment]
Yup, indeed. Thanks!

Moved my `PROMPT_COMMAND` stuff into `PS1`.
