### ISSUE TITLE
Currently-active tab isn't always visible in the tab bar

### ISSUE THREAD

**Issue by austin-beer** [microsoft/terminal#8785]
# Environment

```none
Windows build number: 10.0.18363.1198
Windows Terminal version (if applicable): 1.5.3242.0
```

# Steps to reproduce

1. Set tabSwitcherMode to "disabled" in settings.json.
2. Open enough tabs that you have to scroll the tab bar to see them all.
3. Use the keyboard to cycle through all of the tabs.

# Expected behavior

The currently active tab is always visible in the tab bar. This requires that the tab bar sometimes scroll itself so that the currently active tab remains visible.

# Actual behavior

The currently active tab is **not** always visible.

**Comment by zadjii-msft** [comment]
This seems reasonable. That being said, I'm not sure we can do this with the `TabView` currently. It almost seems like something the `TabView` should be doing for us. I'll file something upstream, since it doesn't look like there are any existing issues.

**Comment by Don-Vito** [comment]
@austin-beer , @zadjii-msft - this looks very similar to #3638

**Comment by zadjii-msft** [comment]
It sure is! Thanks!

/dup #3638
