### ISSUE TITLE
GetConsoleScreenBufferInfoEx, return value, GetLastError?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8788]
# Environment
v:\> ver
TCC 27.00.18 x64
Microsoft Windows 10 Pro for Workstations
10.0.19042.746 (2009, 20H2)
WindowsTerminalPreview_1.5.3242.0_x64

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

See below.
# Expected behavior
Something else.

# Actual behavior

Here's some code I'm using to test an unrelated ussue.  Sorry it uses a bit of plugin interface language.  You'll get the gist.

```
	CONOUT conout;
	CONSOLE_SCREEN_BUFFER_INFOEX csbiex = {sizeof(CONSOLE_SCREEN_BUFFER_INFOEX), 0};
	if ( GetConsoleScreenBufferInfoEx(conout.h, &csbiex) == FALSE );
		TCError(GetLastError(), NULL);
	for ( INT i=0; i<16; i++ )
		Printf(L"Color %d = 0x%06lX\r\n", i, csbiex.ColorTable[i]);
```

If it's run in WT, in OpenConsole, or in conhost it produces (snipped) ...

![image](https://user-images.githubusercontent.com/61856645/104546488-4e5f8580-55fa-11eb-81b6-9a1201ccbb50.png)

... apparently succeeding but returning FALSE with GetLastError() == 0.

**Comment by vefatica** [comment]
And those color values look more like RGBs than COLORREFs.

**Comment by vefatica** [comment]
As for the return value ... my mistake (misplaced semicolon) ... sorry.

But are they supposed to look like RGBs?  Color 1 is red and red's COLORREF is 0x000080.

**Comment by KalleOlaviNiemitalo** [comment]
> Color 1 is red

But the [CHAR_INFO structure](https://docs.microsoft.com/en-us/windows/console/char-info-str) documentation says `FOREGROUND_BLUE` is 0x0001.

**Comment by KalleOlaviNiemitalo** [comment]
The color numbering of the Windows console API originates from the [IBM CGA color palette](https://en.wikipedia.org/wiki/Color_Graphics_Adapter#Color_palette), I think. It's not the same as what is used in [SGR control sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting).

**Comment by DHowett** [comment]
Just to confirm: your return value issue was caused by user error?

@KalleOlaviNiemitalo is correct. The colors are not indexed the same as in VT. The colors match the values you get if you OR together the `FOREGROUND_` constants.

**Comment by vefatica** [comment]
Yes, indeed! ... user error on the return value part.

What's CHAR_INFO got to do with it?

The docs say GetConsoleScreenBufferInfoEx gives an array of COLORREFs and the docs for COLORREFs give examples where red is in the low byte.  Is the meaning of COLORREF subject to interpretation?

**Comment by DHowett** [comment]
No, COLORREF is always BGR.

> The low-order byte contains a value for the relative intensity of red; the second byte contains a value for green; and the third byte contains a value for blue.

The low-order byte is the last one in the hex-text representation `0x00BBGGRR`.

The `CHAR_INFO` structure, as linked by @KalleOlaviNiemitalo, **documents the values of the color constants.** Are you looking for a way in which it has _even more_ to do with the color ordering? :wink:

**Comment by vefatica** [comment]
Try again ... GetConsoleScreenBufferInfoEx uses a CONSOLE_SCREEN_BUFFER_INFOEX, one member of which is

`COLORREF   ColorTable[16];`

The numbers that GetConsoleScreenBufferInfoEx puts in that array are in the format 0x00RRGGBB which is not the format of a COLORREF.

**Comment by zadjii-msft** [comment]
Wait I'm not so sure about that. 

ColorTable[1] in the console is `DARK_BLUE`, so `0x800000` as a `0xBBGGRR` color would be `rgb(0, 0, 128)`. Right? 

It might be easier to debug by changing the colors first a little, so red is something like 0x40, green as 0x60, blue as 0x80, so you'd know exactly which ones were getting returned.

**Comment by vefatica** [comment]
Thanks, Mike.  I experimented a bit with the values in HKCU\Console.  User error again.  I don't know where I got the idea that ColorTable 1,2,4 were R,G,B ... maybe from the 31, 32, 34 used in the control sequences (but those didn't come from MS).  Sorry for bugging you guys.

**Comment by zadjii-msft** [comment]
No worries, glad you got it figured out! The Windows Console is definitely the odd one out with the color table being in BGR order, _and_ the COLORREFs being BBGGRR. Everyone else on the planet has them in RGB order 🤷‍♂️

**Comment by DHowett** [comment]
> Try again

I’m glad you got your problem sorted out, but I have to tell you that _this_ comes off as particularly unkind. I am here _trying_ to help and point you towards relevant documentation[1], but the page Kalle linked being a few short hops away from does not really mean that I should “try again.” If I fail to provide you details you find relevant or interesting, you can say that without ordering me to take twenty. 

I know you probably didn’t intend that, but I figured I’d let you know how it reads.

1: we all use a common infrastructure here in the console; the color orders are dictated by history and _documented with CHAR_INFO_. The table you called out would therefore be in the order documented for other parts of the console, right? :smile:

**Comment by vefatica** [comment]
I may have been adamant (thinking I was right).  I never mean to be unkind.  I'm sorry if you took offense.  I have great respect for the members of the Windows Terminal team.

**Comment by DHowett** [comment]
We like you too 😉 you keep us on our toes!

Thanks
d
