### ISSUE TITLE
Select long wrapped text with mouse

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#8789]
What follow occurs on WT-1.4.3243.0 with this in `settings.json`:

```
"wordDelimiters": " ()\"',:;<>!^&*|=[]{}?\u2502",
[...]
"padding": "8, 8, 8, 8",
[...]
```

When a long file name (or other text) is wrapped on the right margin, I cannot select it with a double click of the mouse. If I double click on the text of second line, the first is not selected. See this:

![from-WT](https://user-images.githubusercontent.com/35931460/104564418-2c422380-564b-11eb-9163-3c3328e33e1c.png)

If I click on the first line the same occurs.

I tried the same with MinTTY terminal and it works as expected:

![from-mintty](https://user-images.githubusercontent.com/35931460/104564806-a5417b00-564b-11eb-82c0-66c9d236ac43.png)

Notice also the _big_ gap on the right margin in WT image. 

BTW, to take the screenshot for WT I had to use the old Capture Tool because with  the new  Capture and Annote the selectin goes away. This happens only with WT and not with MinTTY..

**Comment by zadjii-msft** [comment]
> to take the screenshot for WT I had to use the old Capture Tool because with the new Capture and Annote the selectin goes away. This happens only with WT and not with MinTTY..

Oh well that's a real bug. Yikes.

**Comment by zadjii-msft** [comment]
The main point of your issue, though, is actually already tracked over in /dup #6178
