### ISSUE TITLE
Win+Shift+S dismisses the selection

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#8791]
> to take the screenshot for WT I had to use the old Capture Tool because with the new Capture and Annote the selectin goes away. This happens only with WT and not with MinTTY..

Oh well that's a real bug. Yikes.

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/issues/8789#issuecomment-760166470_

<hr>

This has evolved into "do not dismiss selection if key combination contains <kbd>win</kbd>"

**Comment by Don-Vito** [comment]
@zadjii-msft - I believe this has the same root-cause as in https://github.com/microsoft/terminal/issues/5366: we clear selection and scroll almost upon every input, no matter if it results in any kind of buffer update.

I was always wondering, why are we cleaning selection in `_TrySendKeyEvent`, and do not wait for `onReceiveOutputFn`. I mean, does the user expect the selection to be preserved when a new output appears?

**Comment by KalleOlaviNiemitalo** [comment]
If I have scrolled back and the new output is coming to a line that is not even currently visible, then I surely expect the selection to be preserved.

**Comment by zadjii-msft** [comment]
It probably does have the same root cause. I knew this felt familiar, I guess we never really resolved that one. 

> why are we cleaning selection in `_TrySendKeyEvent`, and do not wait for `onReceiveOutputFn`. I mean, does the user expect the selection to be preserved when a new output appears?

I'm not sure there's an explicit reason - I think we were mostly trying to copy the way conhost worked. 

It does kinda seem like output is a application-initiated event, while making a selection and entering input are user-initiated. You know, now that I've typed that up I'm not sure that has anything to do with it. But I do agree that we'd want to keep the selection when new output arrives. That does just make the problem tricky, cause it's hard to know when a key actually resulted in output.

**Comment by Don-Vito** [comment]
@zadjii-msft - this is exactly the dilemma:
* If you handle the selection on input - you don't know if this input will lead to any kind change in the buffer, so you might clear selection for no reason
* If you handle the selection on output - you don't know if you were the one initiating the output.

The question, can we do something like: if the the output happened within the view port then clean, otherwise do not?

**Comment by KalleOlaviNiemitalo** [comment]
Can you make an exception just for key combinations that involve the Windows key?

**Comment by imaginary-person** [comment]
@zadjii-msft: Hey Mike, currently it seems hard to figure out which `Easy-Starter` issues are up for grabs. For instance, it looks like your team is working on this one. Please let me know if any `Easy-Starter` issue is yet to be worked on. Thanks!

**Comment by zadjii-msft** [comment]
Nope, no one on the team is currently working on this. Usually when someone starts working on a fix, they'll assign it to themselves.

We'll throw _everything_ in milestones, regardless of if someone is assigned or not. By putting this in the 2.0 milestone, that's just us saying "this needs to be fixed before 2.0". If no one in the community gets to it by then, one of us will need to do it ourselves. 

We're still trying to work out which "Help Wanted" issues are really "Easy Starter"s or not. I'm not confident that we've really figured that out quite yet, but this one shouldn't be _too_ bad. IIRC we only started using the "Easy Starter" label a few months ago, so there's probably a good number of older "Help Wanted" issues that should _also_ be tagged with "Easy Starter". I'll make an effort later this week to try and go through and update the labels of older issues.

If you want to take a look at this (or anything else), I'd be happy to assign it to you. Let me know!

**Comment by Don-Vito** [comment]
@imaginary-person, @zadjii-msft - I guess this one is not a really easy starter.. at least not yet.. we have not still figured out how to approach it product-wise.  

@zadjii-msft  - if you agree with the approach of ignoring `Win`-key combinations that  @KalleOlaviNiemitalo  suggested, then it can be a good easy-starter for sure.

**Comment by imaginary-person** [comment]
@zadjii-msft & @Don-Vito, thanks for the clarification!

**Comment by zadjii-msft** [comment]
> if you agree with the approach of ignoring `Win`-key combinations that **KalleOlaviNiemitalo** suggested, then it can be a good easy-starter for sure.

Seems like a sensible enough solution for now. Might as well not ignore an incremental improvement in the pursuit of perfection.

**Comment by Don-Vito** [comment]
@zadjii-msft  - can you please update the description then? :blush:

@imaginary-person - I would be glad to assist if you want to work on this: it should be something like "do not dismiss selection if key combination contains `win`-key"

**Comment by imaginary-person** [comment]
@Don-Vito: Thanks in advance for your help! I'd ping you for help if I'd get stuck, or if I'd have any doubt.
