### ISSUE TITLE
Passphrase prompt for pinentry is not displayed on the same tab/pane

### ISSUE THREAD

**Issue by ealap** [microsoft/terminal#8796]
# Environment

```none
Windows build number: 19042.746
Windows Terminal version: 1.5.3242.0
WSL: fedoraremix 33

Any other software?
gpg (GnuPG) 2.2.25
pinentry 1.1.0

```

# Steps to reproduce

1. Enable SSH access using a GPG key for authentication. I followed this [how-to article](https://opensource.com/article/19/4/gpg-subkeys-ssh).
2. Open a new WSL session in a new tab or new pane and open any Vim session
3. Go back to previous tab and test SSH access with GPG key authentication. In my case, I tested my GPG key in Github
```
ssh -T git@github.com
```

# Expected behavior

- Pinentry should spawn asking for passphrase credential.

# Actual behavior

- Pinentry spawns on the other tab/pane.
![image](https://user-images.githubusercontent.com/15620712/104700075-97285300-574e-11eb-93ce-4087767ef964.png)

The case is the same even when pinentry-curses is used instead of pinentry-tty

**Comment by zadjii-msft** [comment]
Well this is mental. But it looks like this is actually an issue in `pinentry-tty`:
* https://unix.stackexchange.com/questions/280879/how-to-get-pinentry-curses-to-start-on-the-correct-tty
* https://lists.gnupg.org/pipermail/gnupg-users/2002-September/015079.html

Looks like this is just something that can happen when working with multiple terminal instances and `pinentry`.

**Comment by ealap** [comment]
I had no idea. Executing the `updatestartuptty` did solve the issue. Thanks for checking this 🍻
