### ISSUE TITLE
Remote SSH into Mac unicode prompt characters not rendered correctly

### ISSUE THREAD

**Issue by amoldeshpande** [microsoft/terminal#8798]
# Environment

Windows build number: 18363.1256
Windows Terminal version (if applicable):Version: 1.4.3243.0

Any other software?
Mac OS : Catalina

# Steps to reproduce

1. ssh into MacOS configured with "oh my posh" unicode prompt.
2. Unicode characters render as junk

Please note  that in the same terminal I can see unicode correctly in my local prompts. I have Nerd Fonts installed and everything oh-my-posh-wise works fine locally.

I am using ssh from the latest Git For Windows (2.30)

# Expected behavior

Prompt should render correctly

# Actual behavior

Unicode characters are not renedered instead I see squares.

Is there something I should be doing to make this work ? 

thanks

**Comment by zadjii-msft** [comment]
Which font are you using specifically? Could you share your `settings.json` (or at least the relevant profile)?

**Comment by amoldeshpande** [comment]
I am using MesloLGM NF. This is my global setting for all profiles.   A Windows pane in the same terminal has no trouble with the glyphs.

 "defaults":
        {
            // Put settings here that you want to apply to all profiles.
          "fontFace" :  "MesloLGM NF",
          "colorScheme": "Solarized Dark"
        },

**Comment by DHowett** [comment]
Can you share the output of running `locale`? I am betting that git bash is not configured properly to pass UTF-8 to the Terminal.

**Comment by amoldeshpande** [comment]
I was using my own tcsh, not bash. But I also tried powershell and git bash to eliminate that variable.

I cannot access my work Mac until Monday, but interestingly my old macbook at home seems to behave correctly. `locale` in both cases is empty (I can't verify the work Mac right now, but that is what I recall from trying to troubleshoot yesterday) :

This is from my macbook at home, running powershell in Windows Terminal,  which seems to have no trouble with emoji.
```
~>set prompt="(%{\360\237\230\201%})>"

Correct to set prompt(%{\360\237\230\201%})>" ?(y|n|e) no
(😁)>locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
(😁)>
```

The only difference is that the work Mac mini is Catalina, while this one is High Sierra.  I will append the output of `locale` from the mini on Monday.

**Comment by DHowett** [comment]
> I am betting that git bash (me)

> I was using my own tcsh (you)

Sorry, I should be more clear. I am betting that the msys2 runtime that the version of SSH shipped with git bash is using, and that your build of tcsh (I'm guessing) also likely uses, is not passing UTF-8 properly. :smile:

**Comment by amoldeshpande** [comment]
> > I am betting that git bash (me)
> 
> > I was using my own tcsh (you)
> 
> Sorry, I should be more clear. I am betting that the msys2 runtime that the version of SSH shipped with git ~bash~ is using, and that your build of tcsh (I'm guessing) also likely uses, is not passing UTF-8 properly. 😄

Actually it doesn't.  Which is why also I tried the other two shells  :-)

**Comment by DHowett** [comment]
Right, but since the version of SSH shipped with git _does_, it’s still in the mix.

**Comment by amoldeshpande** [comment]
ok, turns out to be user error. LANG was not set and once I set it as above, it works fine.  thanks!
