### ISSUE TITLE
[Question] Behaviour when changing settings file external

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#8800]
At the moment I can change the settings file in an external app and wt updates its behaviour automatically. I don't have to close it before editing settings file.

Will this behaviour change after the changes for/implenting the settings ui? So is it necessary to close wt before backup/restore/change settings file in the future?

**Comment by zadjii-msft** [comment]
No, this behavior is not going to change. Is there any reason in particular you think it might?

**Comment by htcfreek** [comment]
I read something that you did changes on the settings backend/handling behind the ui. So I thought it could change.

**Comment by htcfreek** [comment]
Closed because question is answered. - Thank you.
