### ISSUE TITLE
Alt+Shift+Plus ... lose focus

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8801]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Microsoft Windows 10 Pro for Workstations
10.0.19042.746 (2009, 20H2)
WindowsTerminalPreview_1.5.3242.0_x64
Any other software?
```

# Steps to reproduce

With another GUI app on the desktop (Notepad or Firefox will do) and working in WT, press Alt-Shift+Plus (split) AND BE SLOW ABOUT RELEASING THE KEYS.

# Expected behavior

Further splitting of panes (as happens if there's no other window on the desktop).

# Actual behavior

Focus switches to the other desktop app.

I've done this a dozen times while composing this post.  If I'm slow to release Alt-Shift-Plus, focus goes to Firefox.  FWIW, I use a rather old PS/2 keyboard.

**Comment by zadjii-msft** [comment]
Is there a particular key up that seems to trigger this? Like, is it the keyup while <kbd>Alt+Shift</kbd> is presssed, or <kbd>Alt+plus</kbd>, <kbd>Shift+plus</kbd>? I can't get this to repro at all, but I also can't really release the keys on the slaptop _slowly_, I can only release them one at a time.

**Comment by vefatica** [comment]
It's the delay in releasing Alt which triggers it.  That is, If I release Plus right away and pause a bit, or release Plus and Shift right away and pause a bit, it happens.  If I release Plus and Alt (or just Alt) right away and pause a bit, it does not happen.

This is an interesting exercise in manual dexterity!

I'm trying to repro with SendInput (not much success yet).

**Comment by zadjii-msft** [comment]
That's mental. It _sounds_ like alt-tab is getting triggered, but tab isn't involved here at all.

* does this repro with both alt keys? 
* does the focus always move to the same program (firefox/notepad), or does it alway move to the "previous" window?
* For a truly mental repro, does it repro with the on-screen keyboard? (I suppose that'd only work on a touchscreen device)

**Comment by vefatica** [comment]
I have only one Alt key (left) the other one is scan-code mapped to Win.

Focus usually (?, see below) goes to whatever other app was started first, not, as a rule, to the previous window.

It does happen using the on-screen keyboard via the mouse.  If the click on =/+ is quick, all's OK.  If I hold the mouse button down a bit on =/+ the change of focus is triggered.  And in four such experiments a moment ago, focus went to Notepad twice and to Firefox twice.

**Comment by vefatica** [comment]
This will do it too.  If I change the Sleep() to 300, it won't.

```
	INT i;
	INPUT z[6];
	for ( i=0; i<6; i++ )
	{
		z[i].type = INPUT_KEYBOARD;
		RtlZeroMemory(&z[i].ki, sizeof(KEYBDINPUT));
		if ( i > 2 )
			z[i].ki.dwFlags = KEYEVENTF_KEYUP;
	}
	z[0].ki.wVk = z[5].ki.wVk = VK_LMENU;
	z[1].ki.wVk = z[4].ki.wVk = VK_SHIFT;
	z[2].ki.wVk = z[3].ki.wVk = VK_OEM_PLUS;
	SendInput(3, z, sizeof(INPUT)); // down
	Sleep(400);
	SendInput(3, z+3, sizeof(INPUT)); // up

```

**Comment by vefatica** [comment]
Strange ... focus seems to go to the lowest window in the Z-order.  Running the code from my last post, in WT, 9 times in a row, each time back to WT with a mouse click, focus changed to Firefox, Notepad, DevEnv, Firefox, Notepad, DevEnv, Firefox, Notepad, DevEnv.

**Comment by vefatica** [comment]
User error again!  (Bad week!)  Sorry for wasting your time, Mike.  The start-up script for my default shell was generating <Esc> (to kill the warning about the service).  That, together with an <Alt> left over from the pane splitting, was triggering a cycle-through-the-windows KB shortcut.
