### ISSUE TITLE
Represent Inheritance in Settings UI

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#8804]
**Original issues name**: Base layer is ignored when profile setting is deleted in SUI

The following bug report is a particular example of inheritance not being represented properly in the Settings UI. In order to fix this, #8269 needs to be implemented.

# Environment

```none
Windows build number: 10.0.21286.0
Windows Terminal version (if applicable): 1.6.10101.0

Any other software?
```

# Steps to reproduce

Apply a setting in Base layer, then remove the same setting from a specific profile. For example, set the Base layer font face to Cascadia Code and remove Cascadia Code PL from the font face section of PowerShell.

Note that I didn't test other settings with Base layer, so this may be the only one I'm not entirely sure.

# Expected behavior

PowerShell should use Cascadia Code because it's defined in Base layer.

# Actual behavior

Terminal shows an error saying `"" is not a font face, using Consolas instead.` and Cascadia Code is ignored from the Base layer.

![image](https://user-images.githubusercontent.com/48369326/104782717-86b9ad80-5739-11eb-8887-68e04d596a49.png)

**Comment by cinnamon-msft** [comment]
The same error occurs if you used to have a font face in your Base layer, then remove it. Then if you create a new profile and don't set its font, the error occurs again because `"defaults"` has `"fontFace": ""` in it now.

**Comment by carlos-zamora** [comment]
This is all caused by `"fontFace": ""` being interpreted as "set the font face to ''", rather than "un-set the font face". The same applies to other string settings like "backgroundImage".

This is really a case of us needing to implement #8269, so that users can explicitly clear/inherit a setting.

**Comment by DHowett** [comment]
Carlos, repurpose this issue to be the per-field inheritance implementation for 8269.
