### ISSUE TITLE
[conhost] Windows 7/Vista (non aero) style title bar showing up in Console Host

### ISSUE THREAD

**Issue by itsme-alan** [microsoft/terminal#8806]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21286.1000]

Any other software? Not relevant 
```

# Steps to reproduce

1. Open cmd.exe in conhost
2. Press Alt + Enter to toggle full screen multiple times quickly as shown in the GIF below

# Expected behavior

Title bar appears normally when full screen is toggled off.

# Actual behavior

For a split second, the title bar has a Windows 7/Vista style without the Aero effect

![  ](https://user-images.githubusercontent.com/75578443/104806837-60127a00-5800-11eb-826f-8f04b862ace2.gif)

**Comment by Don-Vito** [comment]
@itsme-alan - this seems to be duplicate to https://github.com/microsoft/terminal/issues/5089

**Comment by itsme-alan** [comment]
That's correct! I did not search for duplicates because I thought no one would have noticed that.

**Comment by Don-Vito** [comment]
> 
> 
> That's correct! I did not search for duplicates because I thought no one would have noticed that.

Makes sense! I didn't look to the duplicated too - I simply remembered the shock from seeing the original ticket once, because I thought no one would have noticed that :smile:
