### ISSUE TITLE
bellStyle 'visual'

### ISSUE THREAD

**Issue by josswright** [microsoft/terminal#8807]
In my Linux setup I have always had the terminal itself set to use a visual bell, allowing console programs to send their normal beep without any per-app or per-shell configuration and see a visual bell.

I was happy to see bellStyle added to Windows Terminal, but I'd love to see `"visual"` added alongside `"audible"` and `"none"`.

**Comment by Don-Vito** [comment]
@josswright - it seems that the visual bell has been already implemented in https://github.com/microsoft/terminal/pull/8215. I am not from the team, so cannot tell if it goes to 1.5 or into 1.6 preview.

In addition a very cool stuff related to the bell is happening here: https://github.com/microsoft/terminal/pull/8637.

**Comment by DHowett** [comment]
This should be out in the 1.6 preview :smile:
