### ISSUE TITLE
Can we copy and paste emoji into terminal and display it right away?

### ISSUE THREAD

**Issue by krave1986** [microsoft/terminal#8808]
# Description of the new feature/enhancement
If I copy 🚀 and paste it into windows terminal, it will be presented as a �
I hope windows terminal could present the emoji as it was copied.

Terminal info related:
PowerShell: 7.1.1
OS: Microsoft Windows 10.0.18363

**Comment by skyline75489** [comment]
I think this is https://github.com/PowerShell/PSReadLine/issues/1329, but I'm not sure

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #1503 and #190 to me. Emoji in the input line just don't play nice quite yet.

/dup #190
/dup #1503

**Comment by krave1986** [comment]
Thanks, subscribe to those issues.
