### ISSUE TITLE
Suggestion: Consider enabling title bar inline tabs by default

### ISSUE THREAD

**Issue by oising** [microsoft/terminal#881]
Consider enabling tabs inlined in the title bar by default, and also showing a single visible tab for the starting shell (e.g. always show tabs, even if there's only one process.)

This might reduce the every other day issue or comment asking why terminal "doesn't work" because they don't know to press ctrl+T (understandably)

**Comment by DHowett-MSFT** [comment]
#869 😄

**Comment by oising** [comment]
Hah! But will it always show tabs with a single process?

**Comment by DHowett-MSFT** [comment]
So long as they default to being in the titlebar, I think that's a reasonable thing to do!

**Comment by oising** [comment]
duplicate of #869
