### ISSUE TITLE
Opening behavior at start.

### ISSUE THREAD

**Issue by Conan179** [microsoft/terminal#8815]
I know this is not a problem, but I don't know where as a German user I can get help.
When I start the preview, a Powershell window always appears first, how do I have to change the settings.json, that 2 tabs are always opened, a Powershell and next to it a cmd?

**Comment by Don-Vito** [comment]
@Conan179 - currently the terminal starts by default with a single tab.

You can open the Terminal with additional tabs by passing command line parameters, like this:
```
wt -p "Command Prompt" ; new-tab -p "Windows PowerShell"
```

For more details see https://docs.microsoft.com/de-de/windows/terminal/command-line-arguments?tabs=windows


In addition as a part of https://github.com/microsoft/terminal/issues/756 we have added "startupActions" (https://github.com/microsoft/terminal/pull/8770) to allow running actions like "new-tab" by default, but it was not released yet.

**Comment by zadjii-msft** [comment]
Yep, this is being tracked over in /dip #756. Thanks!

**Comment by Conan179** [comment]
I'm sorry, my eng is not the best and I wasn't sure if my question was right here at all.

**Comment by Don-Vito** [comment]
> 
> 
> I'm sorry, my eng is not the best and I wasn't sure if my question was right here at all.

Ihr Englisch ist sehr schön und Ihr Frage war gantz verständlich! Ich habe an der Universität Deutsch gelernt, aber alles vergessen 🤦

**Comment by Conan179** [comment]
@Don-Vito Ich hab Google translate genutzt :p
