### ISSUE TITLE
WSL Not Available After Windows 10 Updates

### ISSUE THREAD

**Issue by JohnBussoletti** [microsoft/terminal#8817]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Hey, you gotta give us like any info. We can't do anything with a blank issue.

**Comment by JohnBussoletti** [comment]
Mike,

I did enter some information, but apparently not correctly for it to have been relayed.  In any case, restarting the WSL associated processes restored access to the Ubuntu 20.04 installation under Windows terminal.  Apparently one or more updates shut down the virtual machine server.

John

**Comment by zadjii-msft** [comment]
Ah, you left it in the commented-out section of the template. Everything in-between `<!--` and `-->` is commented out in markdown, like HTML.

> After an update to my Windows 10 system, the drop-down tab no longer shows my Ubuntu 20.04 as an option in Windows Terminal.  The Settings icon opens Notepad on a JSON file which still has all the information/specifications of the Ubuntu option, but I don't see it available when I click on the down-arrow tab.

This sounds like the same symptoms as /dup #7199.
