### ISSUE TITLE
Can't assing hotkey Cntrl + \ for "Split the Screen" command 

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/terminal#8818]
# Environment
Win 10 

# Steps to reproduce

1) Open settings.json  ( `cntrl+,` )
2) Add command  `{ "command": { "action": "splitPane", "split": "horizontal" }, "keys": "alt+shift+-" }`
3) Everything is fine. The command works. 
4) Replace it with the new command and with the hotkey `Cntrl + \`
`{ "command": { "action": "splitPane", "split": "horizontal" }, "keys": "cntrl+\\" }`

# Expected behavior
`Cntrl + \` hotkey splits the screen

# Actual behavior
Nothing happened.

**Comment by DHowett** [comment]
The settings language requires `ctrl`, not `cntrl`.

**Comment by ArturGudiev** [comment]
Thanks! It works!
