### ISSUE TITLE
Clicking the active tab removes focus from active shell session

### ISSUE THREAD

**Issue by corbob** [microsoft/terminal#8822]
# Environment

```none
Windows build number: 10.0.19042.0

Windows Terminal version (if applicable): 1.5.3242.0 (Preview)

Any other software? none
```

# Steps to reproduce

With a tab active, click the tab in the title bar.

# Expected behavior

The tab stays active, and focus remains in the shell session

# Actual behavior

Focus is removed from the shell session.

# Further details

I have searched issues for multiple different ways to describe this issue and cannot find any currently open issues. This issue is particularly annoying when switching applications into Windows Terminal by clicking the title bar and hitting the active tab. Expecting to be able to start typing and finding that you can't because focus is no longer in the shell.

Edit to include a gif of reproduction:
![terminalissue](https://user-images.githubusercontent.com/30301021/104978933-ea510e80-59b7-11eb-9260-ac7b442a3caa.gif)

**Comment by j4james** [comment]
I think this is probably being tracked by issue #3609.

**Comment by zadjii-msft** [comment]
Sure is! Thanks!

/dup #3609
