### ISSUE TITLE
Right click paste need the second click

### ISSUE THREAD

**Issue by SainoNamkho** [microsoft/terminal#8824]
# Environment

```none
Windows build number: 10.0.19042.685
Windows Terminal version: 1.4.3243.0
I'm using an elan touchpad with microsoft precision driver.
```

# Steps to reproduce

1. Copy some text.
2. Right click to paste.
# Expected behavior
Send clipboard entry to input.

# Actual behavior
When I use the right button of mouse, everything is ok.
But when I click by two fingers on the touchpad, the text is not pasted.
_n_ consecutive two-finger clicks result in _n-1_ pasted text.
_n_ consecutive two finger clicks preceded by an `ESC` key or left/middle/right button click on the mouse or a scroll or any action on the toupad results in _n_ pasted text.
But in other programs the text is pasted at any two-finger click.

**Comment by SainoNamkho** [comment]
Additional information:
If use a clipboard manager called [ditto](https://www.microsoft.com/en-us/store/p/ditto-cp/9nblggh3zbjq), choose a clipboard entry and press enter, the text is not pasted either, whereas double cick works.
In legacy console host, the text if pasted immediately if not running in administrator mode, but in windows terminal, an extra `ctrl+v` is always needed.
So I think the problem has nothing along with the touchpad driver.

**Comment by zadjii-msft** [comment]
> But in other programs the text is pasted at any two-finger click.

That's certainly suspicious - I wasn't aware of many other applications that used right-click/two-finger-click as a paste. Out of curiosity, which applications are you pasting into where a two finger click paste works correctly? 

Does this repro without Ditto installed/enabled?

Do you have any sort of IME software installed/enabled?

**Comment by SainoNamkho** [comment]
> That's certainly suspicious - I wasn't aware of many other applications that used right-click/two-finger-click as a paste. Out of curiosity, which applications are you pasting into where a two finger click paste works correctly?

I just intended to mention the traditional conhost.
> Does this repro without Ditto installed/enabled?

Yes.
> Do you have any sort of IME software installed/enabled?
I have IMEs, but the problem holds when the IME is deactivated.
When the IME is enabled, there are random cases when I need three or more two finger clicks.

**Comment by carlos-zamora** [comment]
Sorry to let this one linger. Are you still experiencing this? Also, are you using any other assistive input software?

**Comment by SainoNamkho** [comment]
> Sorry to let this one linger. Are you still experiencing this? Also, are you using any other assistive input software?

Thanks a lot for keeping the problem in mind after a year, I haven't been experiencing it since a rather early fix. Sorry to not close the issue in time

**Comment by zadjii-msft** [comment]
No worries, glad it went away!
