### ISSUE TITLE
Wrong encoding on powershell `import-module`

### ISSUE THREAD

**Issue by SainoNamkho** [microsoft/terminal#8825]
# Environment

```none
Windows build number: 10.0.19042.685
Windows Terminal version: 1.4.3243.0

```

# Steps to reproduce
I use oh-my-posh to change the theme.
```
Set-Theme Material
```
which uses `import-module` inside.

# Expected behavior
![image](https://user-images.githubusercontent.com/23036788/105041220-af290b00-5a9d-11eb-809a-4b657bf67267.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/23036788/105040274-99ffac80-5a9c-11eb-9757-29edd099e373.png)

The module file is encoded in utf8.
```
 gc "$home\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.496\Themes\Material.psm1"
```
gets
> ...
> $sl = $global:ThemeSettings #local settings
$sl.PromptSymbols.PromptIndicator = '+'
$sl.PromptSymbols.HomeSymbol = '馃彔'
$sl.Colors.PromptSymbolColor = [ConsoleColor]::Green
$sl.Colors.PromptHighlightColor = [ConsoleColor]::Blue
...

But
```
 gc "$home\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.496\Themes\Material.psm1" -encoding utf8
```
gets
![image](https://user-images.githubusercontent.com/23036788/105041796-66258680-5a9e-11eb-955a-500b4af364a1.png)

**Comment by DHowett** [comment]
This is almost certainly going to be a powershell issue. Can you share the output of `$PSVersionTable` in both VS Code and Terminal?

**Comment by SainoNamkho** [comment]
> $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Since they're using the same powershell executable, I illustrated the VSCode version just for an example.
The encoding is correct when I directly run powershell.exe as well as in VSCode integrated terminal, so I wonder if there will be any solution with terminal despite the issue's belongingness to powershell.

**Comment by DHowett** [comment]
> The encoding is correct when I directly run powershell.exe

This is concerning, because when running in the vintage console (conhost) powershell has no ability to display emoji ...

**Comment by DHowett** [comment]
Can you share the output of the following powershell command?

```
(gi hkcu:/console),(gci hkcu:\console -rec) | % { gp $_.PSPath CodePage -EA:Ignore }
```

I wonder if you have a codepage set globally that Terminal is not using?

**Comment by SainoNamkho** [comment]
> Can you share the output of the following powershell command?
> 
> ```
> (gi hkcu:/console),(gci hkcu:\console -rec) | % { gp $_.PSPath CodePage -EA:Ignore }
> ```
> 
> I wonder if you have a codepage set globally that Terminal is not using?

Thanks a lot. The default ANSI codepage in terminal was indeed not compliant with the global setting as UTF8.
It's now correct after a reinstall.

**Comment by DHowett** [comment]
Thank you for the info!
