### ISSUE TITLE
re-arrange tabs

### ISSUE THREAD

**Issue by riback** [microsoft/terminal#8828]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
You gotta give us **any** info. We can't do anything with a blank issue like this. Feel free to add more details, and we can reopen this.
