### ISSUE TITLE
Git Bash in Terminal will be shining continously when using 'backspace' to remove the empty line

### ISSUE THREAD

**Issue by pplmx** [microsoft/terminal#8830]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

$ git --version
git version 2.30.0.windows.2
```

# Steps to reproduce

1. Integrate Git Bash to Terminal
2. Use 'backspace' to remove the empty line

# Expected behavior

Without the continuous shining

# Actual behavior

Shining Continuously

# BTW

Directly using GitBash without integration will not produce the above behavior

**Comment by DHowett** [comment]
Git Bash is using a "visual bell", which the windows console (and terminal) did not previously support. Now that it _does_ support a visual bell, this support will also propagate to Windows itself.

Info [here](https://tldp.org/HOWTO/Visual-Bell-8.html)
