### ISSUE TITLE
Windows Terminal and the LxssManager service?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8834]
With WT not running and the LxssManager service stopped, issue "wsl exit" in the Win+R dialog.  You'll have a very brief WSL session, the LxssManager service will start, and given no further reason to run, the LxssManager service will automatically stop 5 minutes later.  I rarely use WSL so I appreciate that behavior.

With WT configured NOT to automatically do anything WSL-related (as best you can) and the LxssManager service stopped, start WT and immediately exit WT.  The LxssManager service will start, and given no further reason to run, it will NOT automatically stop (I waited 45 minutes).

Must starting WT cause the LxssManager service to start at all?  If so, can it be started in such a way that it automatically stops if not used further in some reasonable amount of time?

**Comment by DHowett** [comment]
Terminal queries the available WSL distributions on launch. You can disable this by setting up `disabledProfileSources` as documented [here in the dynamic profile docs](https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles#prevent-a-profile-from-being-generated)

**Comment by DHowett** [comment]
It does so by running `wsl.exe -l`. You may want to file a bug on them for the seventeen kilobytes of memory their service takes when quiescent. :smile:

**Comment by vefatica** [comment]
Thanks, Dustin.  I read about that setting ages ago.  If I had any idea what it was all about, I might have remembered it.
