### ISSUE TITLE
strange behavior with tab[char] +line wrap + backspace in conhost/conpty

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#8839]
# Environment

```none
Windows build number: 10.0.19042.746
Windows Terminal version (if applicable):1.5.3242.0

Any other software?
```

# Steps to reproduce
compile and run this simple code:
```C
#include <stdio.h>
#include <stdlib.h>
int main(void)
{
	scanf("%*s",NULL);
	return 0;
}
```
 * then type [tab] + [any character]
 * hold tab again until the cursor goes to next line
 * hold backspace to delete all character's
# Expected behavior
 the character inserted gets removed
# Actual behavior
it doesn't 
![image](https://user-images.githubusercontent.com/43626415/105271953-34342300-5b77-11eb-87f6-7bfd5cb3ba34.png)

**Comment by j4james** [comment]
It's worth mentioning that this also happens when you start conhost in the legacy v1 mode, so I don't think it's a new bug.

**Comment by zadjii-msft** [comment]
Oh wow this happens all the way back to v1? That's crazy. I'm sure there some horrifying thing that's happening in `WriteCharsLegacy` to cause this.

**Comment by DHowett** [comment]
Since it's not a regression, I moved it into the console backlog. Some buffer changes are coming that might make this more or less bad. We'll evaluate.
