### ISSUE TITLE
Missing features from the windows command prompt!

### ISSUE THREAD

**Issue by HristoNedelkov** [microsoft/terminal#8842]
When you use the cmd in windows and press (**CTRL** + **upArrow**) OR (**CTRL** + **downArrow**). You can move the page _up and down_! Please, add this feature, beacause I often need to scroll big text files! And you are not a real programmer if you use the mouse!!

Thank you for reading this request!

**Comment by zadjii-msft** [comment]
These are actions that are already supported in the terminal. Refer to [the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#scrollback-commands). 

You can add this on the original keybindings with

```json
{ "command": "scrollUp", "keys": "ctrl+up" },
{ "command": "scrollDown", "keys": "ctrl+down" }
```
