### ISSUE TITLE
Screen Redraws Written to Screen Buffer using WSL

### ISSUE THREAD

**Issue by loganp** [microsoft/terminal#8843]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.3242.0

Any other software?
WSL 2
Ubuntu 20.04
```

# Steps to reproduce

* Open WSL tab
* Open vim
* CTRL+L to redraw screen
* Scroll up

# Expected behavior
 Not scrollable

# Actual behavior
Scrollable

**Comment by zadjii-msft** [comment]
You know, this is either /dup #3492 or /dup #381, or just some combo of the two. I think 3492 is "implement support for the alt buffer in terminal", while 381 is "make sure conpty lets terminals know about requests for the alt buffer", so the two are tied together.
