### ISSUE TITLE
Scroll forward in terminal (past the end of the last line)

### ISSUE THREAD

**Issue by al-yakubovich** [microsoft/terminal#8845]
# Description of the new feature/enhancement

Please allow the terminal to be scrolled past the end of the last line.

# Proposed technical implementation details (optional)

![1](https://user-images.githubusercontent.com/12928778/105417995-0cd66800-5c02-11eb-8d77-d1c735152fc2.png)
![2](https://user-images.githubusercontent.com/12928778/105418001-0f38c200-5c02-11eb-8d4f-8abe61585383.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22Scroll+forward%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #8623 for more discussion.

/dup #8623
