### ISSUE TITLE
Improve "Rename Tab" action

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/terminal#8847]
# Description of the new feature/enhancement

It's convenient to have an action renameTab which will not just set the tab's name to a predefined string but will allow a user to enter the name dynamically. 

# Proposed technical implementation details (optional)

Currently, there is an action 
`{ "command": { "action": "renameTab", "title": "some string"}, "keys": "" }`

but it just sets the name using the predefined value. The result of this action should be the same as if a user makes a right-click on a tab and presses "Rename Tab".

**Comment by Don-Vito** [comment]
@ArturGudiev - I think an "openTabRenamer" action was added here #7462 and released into 1.5 Preview.

**Comment by zadjii-msft** [comment]
Yea, it sure sounds like `openTabRenamer` is exactly what you're looking for. 

/dup #7462

**Comment by ArturGudiev** [comment]
@Don-Vito @zadjii-msft when will it be moved from PREVIEW to the stable version?

**Comment by Don-Vito** [comment]
@ArturGudiev - preview is the new stable :smile:. I am not from the team, but if I understand correctly, the rollout will happen very soon (my guess it is a matter of days)

**Comment by ArturGudiev** [comment]
@Don-Vito ok, thanks. Do you know if the new version will be updated automatically? Or will I need to download manually the newer version?

**Comment by Don-Vito** [comment]
> @Don-Vito ok, thanks. Do you know if the new version will be updated automatically? Or will I need to download manually the newer version? 

@ArturGudiev - I guess it depends on the way you installed the Terminal. If you installed it via Windows Store and have a default policy there, it will simply rollout. However if you installed the binary manually from GitHub you will need to deploy explicitly.

**Comment by zadjii-msft** [comment]
Yea I'd second pretty much everything Don-Vito said. Whenever we release a new preview version, we'll also move everything currently in preview to the stable channel. Though, Preview isn't really "unstable", it's more "you might get some new features before they're totally polished".
