### ISSUE TITLE
Extend acrylic to the tab page bar and title bar area. (Build a streamlined but uniform color setting)

### ISSUE THREAD

**Issue by Shomnipotence** [microsoft/terminal#8850]
As discussed in the following issue, there are too many ideas to achieve, including but not limited to the title bar, the current label, the hover label, the background color, and the different settings for the title bar. There is no doubt that it will eventually Import to build a theme system. My confusion lies in whether such a "grand" personalized setting system is needed for WindowsTerminal? I think I can sort out which parts can be prioritized (although Microsoft may not be interested in this).
＃1963，＃1337，＃3061 / ＃3062，＃2994

The Fluent Design System is constantly evolving, it is always in development, and less than 1/3 of the system applications adopt them, so Windows will never have a unified user interface, because the speed of applications using the latest design language will never keep up The speed of design updates. Moreover, before the release of WinUI3, I am afraid that all Win32 applications will not have much design changes-this is because Microsoft seems to be hesitant on whether to use XAML to build new applications.

Based on this, we discuss the design of Windows Terminal to minimize design changes and be compatible with existing designs as much as possible.

Windows Terminal allows you to set the background, but when the background uses acrylic, you will encounter an extremely ugly title bar (tab page bar), so the first consideration is to extend the acrylic effect to the title bar (tab page bar).

![image](https://user-images.githubusercontent.com/6630660/105501888-be0ef800-5cff-11eb-98b9-0adde8304514.png)

Here is a question, how to deal with the current label color, I personally think that the label color and the background of the current page can be consistent. If the current background color is a picture, the theme color will be automatically extracted from the picture.
If you do this, you only need to specify two colors:
1. Title bar color
2. Window background color (=label color)

![WindowsTerminal1](https://user-images.githubusercontent.com/6630660/105503193-4346dc80-5d01-11eb-930d-897d25ee8454.png)
![WindowsTerminal2](https://user-images.githubusercontent.com/6630660/105503215-48a42700-5d01-11eb-98b3-213add764ecf.png)
![WindowsTerminal5](https://user-images.githubusercontent.com/6630660/105503252-50fc6200-5d01-11eb-84ef-048072fc4119.png)

--------------------------------------------------------------------------------------------------------------------
There is another solution here, which I saw in the Files App, using a completely floating tab design.

In this case, the color of the title bar (tab page bar) is the same as the background color of the window. If a picture is used, the picture is tiled or full in the current window. Add a rounded rectangle background to the current label to show the selection, as shown in the figure.

![WindowsTerminal3](https://user-images.githubusercontent.com/6630660/105503784-f8799480-5d01-11eb-9e8e-fc14fb1dbced.png)
![WindowsTerminal4](https://user-images.githubusercontent.com/6630660/105503795-fa435800-5d01-11eb-8d9a-9861b6d1907a.png)
![WindowsTerminal6](https://user-images.githubusercontent.com/6630660/105504453-bef55900-5d02-11eb-85ce-179ec25e41a8.png)

I think these adjustments will not increase too much workload and are in harmony with Fluent Design. I want Microsoft to work as quickly as possible. I really look forward to Sun Valley, but so far, I think the biggest changes may be the "alarm and clock app" and the news flow of the taskbar.

**Comment by zadjii-msft** [comment]
Thanks for the suggestions, and the great mockups. The plan of record right now is to enable a lot of the customizations you've called out through "Themes". We're tracking that functionality over in #3327, and there's a spec that's in progress over in #5772. The goal with themes is to allow the most flexibility possible. So with the design we've proposed, the user could set something like

```jsonc
"tab.background": "terminalBackground",
```

in their theme, and that would make the tab's color match that of the active terminal. Similarly, `"tabRow.background": "terminalBackground",` would match the titlebar to the background of the terminal. 

There's a whole bunch of ideas there, far beyond just customizing the tab row. What we're aiming for is building the most customizable terminal possible. It's my personal favorite scenario, so you don't need to worry about the prioritization of that feature.  It's coming soon<sup>TM</sup>

/dup #3327
