### ISSUE TITLE
Command line mode in command palette behaves different from what doc describes.

### ISSUE THREAD

**Issue by krave1986** [microsoft/terminal#8853]
Windows Terminal version: 1.4.3243.0

Related doc: https://docs.microsoft.com/en-us/windows/terminal/command-palette#command-line-mode

Doc states that

> If you'd like to enter a wt command into the command palette, you can do so by deleting the > character in the text box. 

But in practice, if you invoke the command palette and want to enter a wt command, there is no > character to be deleted.
On the other side, you have to add > character to enter a wt command.

![image](https://user-images.githubusercontent.com/16416541/105540063-93896300-5d30-11eb-92d0-bca9be586d69.png)

**Comment by DHowett** [comment]
We changed this recently -- it looks like the documentation update was released before the terminal update. Sorry.

/dup #7935
