### ISSUE TITLE
I don't think I'm supposed to see this

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8854]
![image](https://user-images.githubusercontent.com/61856645/105541827-5f795800-5cc6-11eb-89fa-de55e36c7d14.png)
Here's how it came to be.

Scheduled task:
"WTElevated" run_on_demand, highest priveleges, action: C:\Users\vefatica\AppData\Local\Microsoft\WindowsApps\wt.EXE

Then from any Windows shell in WT, 

`schtasks.exe  /run /tn WTElevated`

That window is:

```
Handle:  0x00140470
Process: 2380
Module:  N/A
Class:   PseudoConsoleWindow
Title:   [none]
Enabled: Yes
Visible: Yes
Show:    NORMAL
LTRB:    380 74 516 113

```
It's from the elevated WT that was started:

```
01/22  15:36:37.794   8888   6724        0.953      73.0  WindowsTerminal.exe
01/22  15:36:37.916   9168   1120        0.016      12.4  RuntimeBroker.exe
01/22  15:36:37.992   2380   8888        0.031       9.1  OpenConsole.exe
01/22  15:36:37.995   6680   8888        0.156      33.2  tcc.exe
```

If I "X" it, it disappears, OpenConsole.exe keeps running, and the elevated WT/TCC session remains intact.

**Comment by DHowett** [comment]
This is the result of doing a ShowWindow on the pseudoconsole pseudowindow.

**Comment by DHowett** [comment]
We could probably fix it, but ... why? :P

**Comment by vefatica** [comment]
Why is the ShowWindow being done?  Normally a PseudoConsoleWindow class window started by WT is not visible.

**Comment by DHowett** [comment]
Presumably, somebody's calling it. We never show it on our own -- somebody has to be getting the window handle and showing it directly.

**Comment by DHowett** [comment]
(Since that's not one of the console APIs, I can't help you trace it in conhost ;P)

**Comment by vefatica** [comment]
Hmmm!  I wonder who's doing that; it's not me.  If I check "Hidden" for the task I still see it (and I still see WT also).
