### ISSUE TITLE
Ability to create new tabs / panes from scripts in current session

### ISSUE THREAD

**Issue by g0blue** [microsoft/terminal#8855]
# Script support for new tabs and panes in current session

I would like the ability to add tabs and panes to the current terminal window from a script.  I would imagine it would look something like:

```
wt.exe --session %WT_SESSION% split-pane -p %WT_PROFILE_ID% [cmd [cmd_args]]
```

Given the security issues involved, I would also imagine that there would be a global setting to enable this functionality (that defaults to `disabled`).  It would be ideal if the script could query (through environment variables or some command) if the functionality is enabled, but it may also suffice if the wt.exe command failed with a specific (non-common) result value if the feature is disabled.

## Background

This is for debugging multi-process workloads where the child-processes are spawned automatically from a master process.  Having everything in the same window / tab makes debugging much easier. :) It would be even better if we could have windows terminal panes in Visual Studio or Visual Studio Code integrated terminals.

# Proposed technical implementation details (optional)

**Comment by g0blue** [comment]
I've also filed a feature request for adding a `--wait` parameter with #8856.

Ideally, I would like to combine that feature with this so I could fork a thread, launch a process in a new pane and wait for it to finish (or kill it programmatically).

**Comment by j4james** [comment]
I think this feature is covered by issue #4472.

**Comment by g0blue** [comment]
Agreed, my apologies.  Duplicate of #4472.
