### ISSUE TITLE
Terminating SSH connection when visiting the tunneled website

### ISSUE THREAD

**Issue by glitchcodes** [microsoft/terminal#8858]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.14.3243.0
```

# Steps to reproduce

I only encountered this when working on Laravel Artisan PHP Server. Not sure on other built-in servers.
1. Run `php artisan serve`
2. On another tab, open a ssh connection to localhost.run `eg: ssh -R 80:localhost:8000 localhost.run`
3. localhost.run will give a domain to view the website
4. Terminal will terminate the connection when you visited the website.

# Expected behavior

Terminal should not terminate the connection

# Actual behavior

Compared with Git Bash (working)
![image](https://user-images.githubusercontent.com/56838797/105566532-ab300e00-5d67-11eb-8ab8-83c8f783ea4b.png)

Terminal
![image](https://user-images.githubusercontent.com/56838797/105566445-41176900-5d67-11eb-9091-00a112aa77b1.png)

**Comment by DHowett** [comment]
This looks like either an issue with the remote service or the windows port of openssh, which you are using _through_ terminal. It would be worth filing this bug at https://github.com/powershell/win32-openssh.
