### ISSUE TITLE
Cursor not working

### ISSUE THREAD

**Issue by lik173** [microsoft/terminal#8860]
Hello, Im using Windows Terminal Preview from ms-store
I have batbox.exe (activate cursor in bat)
if im using that cursor not active.
if im using cmdmenusel, cursor unactive too but with arrows i can change pos of selection

Please help!

**Comment by skyline75489** [comment]
Ok this is just very vague description. Does the same issue happens with cmd.exe? Can you share a screenshot or something?

**Comment by zadjii-msft** [comment]
Yea could you share a video, or a gif? 

What version of the Terminal are you using? What version of Windows? What versions of the other software you're using? Could you share some links to that software?

Could you share some specific repro steps?

**Comment by lik173** [comment]
Windows 10 Pro x64
Windows Terminal Preview from ms-store
In cmd that works
Imuploaded this soft to my gh page
This files need:
lik173.github.io/pkg/batbox.exe
lik173.github.io/pkg/GetInput.exe
lik173.github.io/pkg/Button.bat
lik173.github.io/pkg/cmdmenusel.exe

Im activate cmdmenusel by that:
cmdmenusel f870 "Function1" "Function2"
Im activate batbox by that:
Batbox /h 0
:button
Call Button  4 2 " Function " # Press
Getinput /m %Press% /h 70

And take info from %errorlevel% (1,2,3,4...)


Cmdmenusel video:
https://www.youtube.com/watch?v=31_nXpWn0L0
Batbox button:
https://youtu.be/j6BrEhms450

See in end of video

Tomorrow i will demonstrate apps and share screenshots

**Comment by lik173** [comment]
And github
Cmdmenusel:
https://github.com/TheBATeam/CmdMenuSel-by-Judago

Buttons:
https://github.com/TheBATeam/Button-Function-2.0-by-Kvc

Screenshots in their repos: /preview
Gif cmdmenusel im uploaded
![CmdMenuSel](https://user-images.githubusercontent.com/70771696/106367238-21c5a080-6352-11eb-9038-e8e32a623e35.gif)

**Comment by zadjii-msft** [comment]
Yep, that'll do it. This is because they're using Win32-style mouse input. That's being tracked in #376 

/dup #376

Thanks!
