### ISSUE TITLE
Ignore applications behind the Terminal for transparency / acrylic (or) Link acrylic effect directly to the desktop's background

### ISSUE THREAD

**Issue by axcadsd** [microsoft/terminal#8863]
# Description of the new feature/enhancement

I don't know how to describe it properly, so i will explain through screenshots.

Current acrylic scenario -
![acrylic1](https://user-images.githubusercontent.com/71010204/105580430-5d8cc300-5db2-11eb-95e4-4f3316a7672c.png)
![acrylic2](https://user-images.githubusercontent.com/71010204/105580431-5f568680-5db2-11eb-8792-13b5b7907495.png)
![acrylic3](https://user-images.githubusercontent.com/71010204/105580432-5fef1d00-5db2-11eb-857f-d28981754e08.png)

Visibility of background applications through acrylic sometimes makes text hard to read on the terminal itself.

What I want -
Backtrack Linux had a terminal, which ignored applications behind the terminal as well as any icons on the desktop, for its transparency effect, i.e. **the transparency was linked directly to the desktop's background.**

![backtrack5](https://user-images.githubusercontent.com/71010204/105580447-7d23eb80-5db2-11eb-97e8-136962c36a05.png)
(screenshot taken from a very old youtube video)

I use acrylic / transparency only because it looks good and not to read text from some other application running behind it. So a setting to do the above with acrylic would be lovely. (a system wide windows setting would be even better, though it will release with god knows which windows version if this feature request is considered.)

EDIT: Also, see this mockup (in an unrelated but *important* (:D) issue) https://github.com/microsoft/terminal/issues/7158#issuecomment-737432327

# Proposed technical implementation details (optional)

**Comment by axcadsd** [comment]
instead of ignoring applications behind the terminal / linking to the desktop's background, it might be easier to link acrylic to the terminal's background image, so that we see that image behind the acrylic effect and no other application / desktop icon would be visible through acrylic.

**Comment by j4james** [comment]
This sounds similar to #6497.

**Comment by axcadsd** [comment]
Yeah, it looks similar. i can add my comments over there and close this issue if required. 
However, from what i gathered from that issue is that this should be created as an extension which themselves are a long time away :(

**Comment by zadjii-msft** [comment]
Yea, we're gonna track this all in one place in #6497. 

The reason I've got that called out as an extension is because _we_ (the Terminal team) probably won't be the ones to implement that feature. But, we should make it possible for external developers to build something like this. 

/dup #6497
