### ISSUE TITLE
If all WT windows are closed from the taskbar hover preview, it stays bugged while hovering

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/terminal#8872]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?

Not that I find relevant or that would affect this.
```

# Steps to reproduce

1. Settings > Personalization > Taskbar > Combine taskbar buttons must be turn on
2. Open multiple Windows Terminal windows
3. Hover with mouse on the Windows Terminal icon on taskbar
4. Close each WT window from the hover preview thumbnails on taskbar

# Expected behavior

All of Windows Terminal windows are closed as with every application, leaving no traces of old instances behind.

# Actual behavior

All of Windows Terminal windows are closed, but a new one is created, without a title or thumbnail. It has a very small size, indicating it is probably an invisible left-behind of the aforementioned windows that were closed.

The acrylic preview container, that typically has all of an application's windows inside it, is now occupying the whole screen horizontal space.

![image](https://user-images.githubusercontent.com/19749621/105639855-376e2e00-5e59-11eb-8d9b-c3e73f1b40c1.png)

**Comment by Lechenx** [comment]
Reproduce successfully. I recording it on put it on youtube. 
Here is the link. https://youtu.be/0C-GPHt1prY

**Comment by zadjii-msft** [comment]
I know this is crazy, but we've actually seen this before. We're currently tracking this in #4774. Thanks!

/dup #4774
