### ISSUE TITLE
Allow specifying which pane to split in the split-pane command

### ISSUE THREAD

**Issue by skotekar** [microsoft/terminal#8873]
# Description of the new feature/enhancement
Currently when you using split-pane commend with wt.exe, each successive split by default further splits the new pane. This is it is not possible to split my screen into 4 quadrats of equal size.

# Proposed technical implementation details (optional)
It would be nice if split-pane command would accept an optional target parameter (similar to focus-tag command) specifying which page we want to split.

**Comment by DHowett** [comment]
This is coming out with #8546 in 1.6 :)
