### ISSUE TITLE
Exit exception

### ISSUE THREAD

**Issue by luweijun1992** [microsoft/terminal#8874]
Exit exception
Win 10 [版本 10.0.19042.746]
Windows Terminal : 1.5.3242.0
![image](https://user-images.githubusercontent.com/58923704/105659486-cafc3900-5f03-11eb-8a07-ea50d153dbb0.png)

**Comment by skyline75489** [comment]
When the return code of the process is `1` instead of `0`, this is expected. 

You can find out more in the documentation about [closeOnExit](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#how-the-profile-closes-when-exiting).

**Comment by skyline75489** [comment]
See also #4223, #5003.

**Comment by zadjii-msft** [comment]
Yep, this is totally by-design. Thanks!
