### ISSUE TITLE
Unexpected buffered Keyboard inputs 

### ISSUE THREAD

**Issue by SunghoLee** [microsoft/terminal#8877]
# Environment
Windows build number: Windows 10 Home. 19041.746
Windows Terminal version: 1.4.3243.0

# Steps to reproduce
I cannot reproduce this unexpected behavior, since I do not know the condition triggering it.

# Expected behavior
Shell or other programs running on Windows Terminal recognize user keyboard inputs, and response for them immediately.

# Actual behavior
User keyboard inputs look like being buffered, so shell or other programs running on Windows Terminal do not react for the inputs immediately. When typing some texts, the texts are shown on Windows Terminal as gray-scaled and underlined texts and they are actually recognized by the shell or programs after typing tab, arrows, and etc. This behavior makes me really inconvenient to use Vim or other text editors on Windows Terminal. I attached a GIF for the behavior. 
![issue](https://user-images.githubusercontent.com/5790819/105685843-e6823680-5f39-11eb-87bf-24e92141cf60.gif)

**Comment by skyline75489** [comment]
Are you using an IME of some sort? This looks like what IME does.

**Comment by SunghoLee** [comment]
@skyline75489, As you mentioned, an IME may introduce it, since I'm using an IME for Korean. But the same behavior does not occur on other terminals (cmd and powershell) except for Windows Terminal. I additionally attached a GIF for what I tested on the three terminals. 
![comp_issue](https://user-images.githubusercontent.com/5790819/105689420-17646a80-5f3e-11eb-8fcb-e380170de06c.gif)

**Comment by SunghoLee** [comment]
@skyline75489, thank you for giving me insight to check this problem. After I disabled the IME that I'm using, the behavior was disappeared. I think that the Hancom Korean IME is not compatible well with Windows Terminal. I just removed the IME.. Thanks again! I close this issue.
