### ISSUE TITLE
Opening via Windows explorer and typing wt in the path box should open wt to the current directory

### ISSUE THREAD

**Issue by TheNerdMan** [microsoft/terminal#8878]
# Description of the new feature/enhancement

Currently if a user navigates to a directory in windows explorer and types `cmd` in the path input then CMD will open to the correct path. Windows Terminal should mimic this behaviour if the default profile allows it.

Example of pre `cmd` usage
![image](https://user-images.githubusercontent.com/17830051/105687333-3b995a80-5ef0-11eb-9792-378691767e6f.png)

Example of post `cmd` usage.
![image](https://user-images.githubusercontent.com/17830051/105687209-14db2400-5ef0-11eb-9c05-985561da0e0d.png)

**Comment by skyline75489** [comment]
This is by design. See https://github.com/microsoft/terminal/issues/878#issuecomment-579508860, #8672

**Comment by TheNerdMan** [comment]
> This is by design. See [#878 (comment)](https://github.com/microsoft/terminal/issues/878#issuecomment-579508860), #8672

Will need to re-train the brain to add that then, thanks for the link
