### ISSUE TITLE
Could not find MsBuild on your machine. Please set the MSBUILD variable to the location of MSBuild.exe and run razzle again.

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/terminal#8887]
# Steps to reproduce

From A 2019 Dev Prompt Run: in the terminal root

.\tools\razzle.cmd

# Expected behavior

environment variables set

# Actual behavior

![Untitled](https://user-images.githubusercontent.com/8218836/105781328-41f6f900-5f27-11eb-8e0f-ea5b9b1d2b61.png)

The Powershell commands work it's razzle that does not and I don't know the format or -MSBuildPath.

**Comment by DHowett** [comment]
Honestly, your best bet is going to be to just build it inside VS. We use vswhere to find msbuild, and if your VS install isn't showing up that will be an interesting discussion to have.

**Comment by jdm7dv** [comment]
I got it to build using 'nuget restore *.sln' and then msbuild. Razzle  just does not work right now 

![Untitled2](https://user-images.githubusercontent.com/8218836/105782982-4b359500-5f2a-11eb-8148-812be69efd2b.png)

**Comment by jdm7dv** [comment]
![Untitled3](https://user-images.githubusercontent.com/8218836/105786026-17aa3900-5f31-11eb-9275-0f4abb8e5bb0.png)

**Comment by jdm7dv** [comment]
set the build config to x64

**Comment by jdm7dv** [comment]
\OpenConsole.sln  /m /p:Configuration=Debug /p:Platform=x64 works there are 8 errors in the master branch.

**Comment by zadjii-msft** [comment]
For the record, I don't run `razzle` from a VS dev prompt. I use that from a plain old `cmd.exe`.
