### ISSUE TITLE
Visual bell style should optionally affect the entire terminal pane

### ISSUE THREAD

**Issue by lzybkr** [microsoft/terminal#8889]
In 1.6 - the `visual` `bellStyle` briefly displays a bell in the tab. I find this too subtle and easy to miss, especially when one's eyes are looking at the bottom of the terminal.

I'd originally envisioned a visible bell as briefly **inverting** the terminal - that would be hard to miss.

After experimenting with the shaders (and there is even a shader for inverting) - I think the visual bell feedback should be a customizable shader. Invert or even Retro could be good defaults, but I'm sure someone will come up with a really nice shader for a nice full window visual feedback effect.

**Comment by skyline75489** [comment]
Are you expecting something that Git bash does in #8737 ? The "Visual Bell" effect?

**Comment by lzybkr** [comment]
I didn't realize there was an escape sequence for that and that it is now supported. That is certainly a reasonable choice, but that could be jarring too, which is why I suggested a configurable shader.

I do like the idea of applications just sending BEL and the terminal deciding how to notify the user rather than each tool needing configuration option to choose visual versus audible.

**Comment by DHowett** [comment]
I tend to agree. We can add more visual cues to the visual bell style.

**Comment by DHowett** [comment]
Triaged into backlog. An enterprising youth could come along and add a cool visual effect if they wanted. :smile:

**Comment by garyo** [comment]
Perhaps a different issue, but could we have a preference for the sound to play for the bell? Then we could have something less loud & intrusive, more bell-like, whatever.

**Comment by zadjii-msft** [comment]
@garyo you're looking for #8366

**Comment by zadjii-msft** [comment]
You know, we did this in #9270
