### ISSUE TITLE
Choosing command prompt pop up a new window

### ISSUE THREAD

**Issue by remygrandin** [microsoft/terminal#8897]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
The workstation is managed by intune with default win 10 security baseline
My account is tenant admin and by extension local admin of the workstation
```

# Steps to reproduce

Install windows terminal and launch it.
Select in the tab dropdown "Command Prompt"
the cmd pop up a a separate cmd window (not integrated as a tab)

# Expected behavior
We expect the cmd to be created as a tab in the windows terminal app

# Actual behavior
The cmd is created as an external, separate window

**Comment by zadjii-msft** [comment]
Fascinating. I don't think I've heard of anything like that before. 

Does the same thing happen with powershell? Or only `cmd.exe`?

**Comment by remygrandin** [comment]
Only cmd.
Powershell or wsl is oppening a new tab as expected.

However, I just tested and the same thing happened in a standard standalone powershell windows if I run cmd.

**Comment by zadjii-msft** [comment]
Fascinating. That raises more questions. Could you share the output of `where cmd` (from any command prompt)? Do you have anything installed that might be hooking cmd.exe? Maybe something like yori, cmder, clink, conemu?

**Comment by DHowett** [comment]
In addition to answering that, would you mind running...

```powershell
reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cmd.exe"
```

**Comment by remygrandin** [comment]
I think i have tracked donw the source. It seem to be the local admin access solution that we use (Admin By Request) that was causing the behavior (once remove, cmd operate as expected)

It was futher proven by @DHowett command :

```
C:\Windows\system32>reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cmd.exe"

HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cmd.exe
    VirtualizerType    REG_SZ    1
    Debugger    REG_SZ    "C:\Program Files (x86)\FastTrack Software\Admin By Request\AdminByRequest.exe" /Block
```

We will contact them to know if the behavior is expected and if so if they can do anything about it.

**Comment by zadjii-msft** [comment]
Ah good to know. Thanks for following up!
