### ISSUE TITLE
Turn arbitrary text into a hyperlink

### ISSUE THREAD

**Issue by oxo42** [microsoft/terminal#8902]
# Turn arbitrary text into a hyperlink

As of Windows Terminal Preview 1.4 (I think) you can Ctrl+click on text that matches a URL and it will open in a browser.  This feature request would be to match on certain text and turn that into a clickable link using some of the text as a parameter.  

## Example

Let's say the following is on the terminal, from the output of `git log`

```
Fixes issue in T1234
```

I would like to setup a regex `\b(T\d+)\b` and when I Ctrl+click on `T1234`, open up `https://example.com/tasks/T1234`.

I would like this to be configured in `settings.json` something like
```
"arbitrarylinks": [
    {
        "pattern": "\\b(T\\d+)\\b",
        "link": "https://example.com/tasks/$1"
    }
]
```

## Not OSC-8 

This is not [OSC-8](https://github.com/microsoft/terminal/issues/204).  I don't have the ability to re-write text so OSC-8 can't be used.  My use case is primarily source control logs.

**Comment by zadjii-msft** [comment]
Alright so I've moved this discussion to #8849, because we're gonna make this a general-purpose solution to both problems. Thanks!

/dup #8849
