### ISSUE TITLE
Can't exit new SUI with Focus mode enabled

### ISSUE THREAD

**Issue by 33b5e5** [microsoft/terminal#8905]
# Environment

```text
Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal Dev from main at b50df20
```

# Steps to reproduce

1) Build Windows Terminal Dev from main. Head was at b50df20 when I built. Notably this includes the new Settings UI (SUI), as well as #8882 and #8885.

2) Enable Focus mode on launch. I used `"launchMode": "focus"` in settings.json to do this.

3) Launch Windows Terminal Dev. My config loads an Ubuntu WSL2 session in Focus mode by default.

4) Open the new SUI with CTRL+SHIFT+S.

# Expected behavior

There should be an easy way to exit SUI and return to your other pane(s).

# Actual behavior

There's no way to exit SUI with the mouse. In Focus mode, the X to close the tab is hidden.

Most of the keybindings I tried to use here also don't work. Specifically, I tried these first in an attempt to exit SUI:

CTRL+SHIFT+P (for the switcher)
CTRL+SHIFT+W (close pane)
ALT+F4 (close window)

After a while, I figured out I could use CTRL+TAB to switch tabs. Then I can use CTRL+SHIFT+P to open the switcher, Toggle Focus Mode, and finally I can close SUI with the mouse.

After some discussion with @cinnamon_msft she suggested I file a bug here. See: https://twitter.com/33b5e5/status/1353929089137041408

**Comment by DHowett** [comment]
This is fixed as of #8903

**Comment by Don-Vito** [comment]
@DHowett - ctrl+w should work as well. Quite sure I tested it.

**Comment by 33b5e5** [comment]
For what it's worth, CTRL+W does not close the SUI for me (from b50df20). I will pull in the latest and try again.

**Comment by DHowett** [comment]
@don-vito Ages upon ages ago (version 0.3), we changed the default bindings from `ctrl+t->newTab` and `ctrl+w->closeTab` to `ctrl+shift+t->newTab` and `ctrl+shift+w->close*Pane*`. Have you really been carrying around settings from 0.2? :smile:

**Comment by Don-Vito** [comment]
@DHowett - hmm... I don't remember configuring this.. but I think I started using terminal around 0.4..

**Comment by 33b5e5** [comment]
Okay, after pulling in the latest, CTRL+SHIFT+W does work to close the SUI. CTRL+W does not work. I would love to see CTRL+SHIFT+P work here as well, because that would allow you to close the pane OR disable Focus mode (or switch panes, or whatever). Thanks for listening.

**Comment by Don-Vito** [comment]
@33b5e5 - yeah CTRL+W works only for me, because it is a binding to a `closeTab` which appears to be not bound by default. 

Regarding Command Palette, I am worried what happens if the user clicks on action like "Find" which is not supported in the settings UI.
