### ISSUE TITLE
URLs with unicode characters are not recognized as clickable.

### ISSUE THREAD

**Issue by mrrcollins** [microsoft/terminal#8907]
# Environment

```none
Windows build number: [Version 10.0.19041.685]
Windows Terminal version 1.5.3242.0:

Any other software?
WSL1 - Ubuntu 18.04
```

# Steps to reproduce

Show a [URL with a unicode character in it](https://⌘v.ircd.xyz/o.gif):

```
https://⌘v.ircd.xyz/o.gif
```

# Expected behavior

Mouse over the link and control click on it to open.

# Actual behavior

The link is not recognized as a URL that can be clicked on.

**Comment by skyline75489** [comment]
Yea I can confirm this bug does exist. I don't know if #8321 covers this, though.

**Comment by zadjii-msft** [comment]
Yea, I'll say they're the same. Or at least, we'll use that one issue to track this too. Thanks!

/dup #8321
