### ISSUE TITLE
Content and history of a terminal tab is lost when DPI of the system/display changes.

### ISSUE THREAD

**Issue by michkot** [microsoft/terminal#8911]
# Environment

```none
Windows build number: 10.0.18363.1256
Windows Terminal version : 1.4.3243.0
```

# Steps to reproduce
Have a running WT instance with output in it.
Disconnect/connect a display (where different displays have differently set DPIs), which triggers "desktop reconfiguration".
Focus the WT window.

# Expected behavior

You will see a (now DPI-rescaled) WT windows with an active tab with the previous content and you can scroll to history.

# Actual behavior

There is no content in the tab, you don't see newly rendered content. You have to resize the WT window to resume functionality, but the last content is lost and so is the scroll history for that tab!

**Comment by zadjii-msft** [comment]
This is bizarre. I dock and undock my laptop a few times a day, and never have any issues with this. 

What graphics card are you using?

If you just try and type some input into the terminal instead of resizing when this occurs, what happens?

I've never heard of anything like this so I'm totally grasping at straws. Especially the 
> but the last content is lost and so is the scroll history for that tab!

That seems to imply that the entire buffer was resized to some ungodly small or large size, such that the entire buffer cycled. Does the scrollbar stay in the same place, with just empty content above it? Or does the scrollbar reset to the top?

**Comment by michkot** [comment]
> This is bizarre. I dock and undock my laptop a few times a day, and never have any issues with this.
> 
> What graphics card are you using?
It's Quadro T1000 with Optimus disabled (no active iGPU)

> If you just try and type some input into the terminal instead of resizing when this occurs, what happens?
I don't see anything (I assume I just don't see the input being echoed by the shell)
> I've never heard of anything like this so I'm totally grasping at straws. Especially the
> 
> > but the last content is lost and so is the scroll history for that tab!
> 
> That seems to imply that the entire buffer was resized to some ungodly small or large size, such that the entire buffer cycled. Does the scrollbar stay in the same place, with just empty content above it? Or does the scrollbar reset to the top?
I think the scrollbar completely disappeared, as if the buffer would fit a single screen.

I have just docked my computer  before a while (and tried again now) and it did not happen. What would be the best way to capture info if this happens again?

**Comment by zadjii-msft** [comment]
You know, I'm not sure. This is one of those bugs where once it's happened, it's too late to get any more useful info - the interesting event is already lost. 

Does it happen in every shell? Or is the problem specific to `cmd`/`powershell`? Again, grasping at straws.

**Comment by michkot** [comment]
I am actually using almost exclusively msys2 bash, which feels like a red
flag to write . I could try keeping an open window with cmd for comparison,
if the problem might be application specific.

**Comment by michkot** [comment]
happened today again (with msys2 bash); the active terminal got completely cleared; the other two terminals are fine (there was just this "jumpy" effect when switching to the tab first time after the DPI change - the text resizes inside the active tab)
I make a mini and full dump of the process using procexp + made a video of it the empty buffer, is that of any use?

**Comment by zadjii-msft** [comment]
That might help, yea. Maybe there's a needle in that haystack that could be informative

**Comment by michkot** [comment]
@zadjii-msft Sorry, I was out, so I missed the bot deadlines. Is there some secure storage for uploading the dumps, so I don't have to leave them "accessible to anyone seeing this repo" in case some sensitive data is in the buffers? I took the dumps, but forgot to ask that question...

**Comment by michkot** [comment]
So today it happened more or less again - after hibernating, disconnecting displays, starting pc again, the WT buffers "froze; I could see the latest content of my (2) tabs, until I tried to add any input or scroll in them -> after that, both of the tabs went blank, and now I can't see the history; When I write something, the tab works; when I try to scroll, the tab goes black, until I write something again - then the last screen content appears - this repeats (if I try to scroll again, -> black, write something -> current content).

Also my question regarding a private way to share a dump file with you is still valid :)

**Comment by zadjii-msft** [comment]
Hey we've made a _lot_ of renderer changes in the last few months. Does this still repro on 1.15/1.16/?
