### ISSUE TITLE
We should put the progress ring, zoom indicator, etc, in the tab switcher

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#8912]
![image](https://user-images.githubusercontent.com/18356694/106001001-0e29e980-6075-11eb-903d-a9233d56147f.png)

In the tab running `bx`, it's got a progress ring (and the icon is hidden to show the ring). We should make those other indicators also show up in the tab switcher, so you can view them at a glance. 

This might be _extra hard_, because right now the CommandPalette is just a set of `{label, icon}`-like objects. All those other icons and indicators are a LOT more content. That would make it something more like a set of `{Content, Icon}`-like objects.

**Comment by Don-Vito** [comment]
@zadjii-msft - this can be much simpler once filtered list view is extracted. Until then we can select item template dynamically.

If this is not urgent, I can absolutely work on this

**Comment by Don-Vito** [comment]
![ProgressInTabSwitch](https://user-images.githubusercontent.com/4639110/106678601-bbe04f80-65c3-11eb-9174-7a90a5e602f5.gif)

**Comment by zadjii-msft** [comment]
😍
