### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#8915]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):1.4.3243.0

Any other software?
```

# Steps to reproduce

Click on settings.
# Expected behavior
Open the settings.

Opening the settings.
# Actual behavior
"

When I open it it says "choose a app to open json 

`

**Comment by zadjii-msft** [comment]
This is because our Settings are stored in a JSON file.
/dup #1564
