### ISSUE TITLE
Can't type more command after run 'git' command

### ISSUE THREAD

**Issue by HppZ** [microsoft/terminal#8922]
# Environment

```none
Microsoft Windows [Version 10.0.19041.631]
Windows Terminal version 1.4.3242.0
git version 2.29.2.windows.2
```

# Steps to reproduce

just run 'git' command

# Expected behavior

I can type more command.

# Actual behavior

I can type nothing.

![image](https://user-images.githubusercontent.com/12285582/106144664-7977d680-61af-11eb-9919-dcd0885960c3.png)

**Comment by zadjii-msft** [comment]
Does `git` work for you from a legacy console window (like `powershell.exe`)? It looks like it's never even returning to the prompt...

**Comment by HppZ** [comment]
works fine in PS and cmd.

![image](https://user-images.githubusercontent.com/12285582/106150428-4f75e280-61b6-11eb-9c36-6be1ff5b39b3.png)
![image](https://user-images.githubusercontent.com/12285582/106150509-64527600-61b6-11eb-83b7-00ffd928962b.png)

**Comment by HppZ** [comment]
Is there any log file ( Windows Terminal  / git / powershel / cmd ) I can check?

**Comment by zadjii-msft** [comment]
Hmmmmmmmmm. Interesting. There's seemingly a scrollbar in the screenshot of the terminal window, with content below it? What happens if you scroll down, is there anything visible down there?

Do you have anything in your powershell config that might resize the window?

**Comment by HppZ** [comment]
> There's seemingly a scrollbar in the screenshot of the terminal window, with content below it? What happens if you scroll down, is there anything visible down there?

Nothing below it. can't scroll down any more. nothing visible down there.

> Do you have anything in your powershell config that might resize the window?

No

**Comment by HppZ** [comment]
need help here.👀
