### ISSUE TITLE
Menu opens in the up direction

### ISSUE THREAD

**Issue by hwti** [microsoft/terminal#8924]
# Environment

```none
Windows build number: 10.0.19042.746
Windows Terminal version : 1.6.10272.0
```

# Steps to reproduce
With the Terminal window NOT near the top of the screen, open the menu by clicking on the down arrow icon.

# Expected behavior
The menu opens in the down direction (unless the window is really near the bottom of the screen).

# Actual behavior
With the 1.6 preview, the menu opens in the up direction (1.5 preview was OK).
![image](https://user-images.githubusercontent.com/827856/106182038-9c4dbf00-619e-11eb-8456-0f827cc98b2a.png)

**Comment by DHowett** [comment]
Menus open in whatever direction they best fit. This is true all over Windows.

**Comment by hwti** [comment]
1.5 was best fit, this is not.

This seems to prefer the up direction by default (when the menu has the space to open in both directions), and only open in down direction when there is no space above the window.

**Comment by DHowett** [comment]
It looks like you have a different set of key bindings in your menu in 1.6 (which was a bug fix. your personal bindings were hidden, and now they are not), which changed the size of the menu items.

**Comment by zadjii-msft** [comment]
This looks related: https://github.com/microsoft/microsoft-ui-xaml/pull/2806

**Comment by hwti** [comment]
This is AZERTY, so profile `Ctrl+Shift+&` and tab switch `ctrl+alt+1` use the same final key, but described in a different way.

But this is probably off-topic, I don't see how the menu direction would be affected by the key bindings, which would only change its width.

**Comment by hwti** [comment]
> 
> 
> This looks related: [microsoft/microsoft-ui-xaml#2806](https://github.com/microsoft/microsoft-ui-xaml/pull/2806)

So maybe `TerminalPage::_CreateNewTabFlyout` should set the placement.
But I wonder why `Auto` would prefer the up direction. The tab context menu doesn't have the issue.

https://github.com/microsoft/terminal/blob/ae8347f336d308997e40e8a46e7d2053c88a1dd1/src/cascadia/TerminalApp/TerminalPage.cpp#L669 sets the placement, so when using the key binding (ctrl+shift+space), the menu opens in the down direction.

**Comment by KalleOlaviNiemitalo** [comment]
The chevron in the menu button always points down. Can you make it point up if the menu is going to open upwards?

**Comment by DHowett** [comment]
I’m not sure we can know that before the OS chooses where to put the menu.

**Comment by hwti** [comment]
But why the OS chooses to open the menu up if there is enough space down ?

**Comment by zadjii-msft** [comment]
> But why the OS chooses to open the menu up if there is enough space down ?

Honestly, we have no idea. The folks at https://github.com/microsoft/microsoft-ui-xaml would be the ones to ask. We're just using the control they built.

**Comment by hwti** [comment]
Btw, the key binding uses `BottomEdgeAlignedLeft`, and does what expected : the menu opens down, unless there isn't enough space.

**Comment by thijsputman** [comment]
> 
> 
> Btw, the key binding uses `BottomEdgeAlignedLeft`, and does what expected : the menu opens down, unless there isn't enough space.

In other words, compare this (clicked on the arrow):

<img src="https://user-images.githubusercontent.com/4418373/106313474-8e647080-6268-11eb-80ba-f6cc65bc6fd1.png" width="480">

With this (`Ctrl`+`Shift`+`space`):

<img src="https://user-images.githubusercontent.com/4418373/106313528-a936e500-6268-11eb-9dc0-5e7dc9c48ed7.png" width="480">
