### ISSUE TITLE
Minor Error in Command Prompt Appearance Setting in New UI

### ISSUE THREAD

**Issue by nobozo** [microsoft/terminal#8928]
The ""Underscore" settings shows a double underscore, and the "Double Underscore" setting shows a single underscore. They should be reversed.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.6.10272.0

Any other software?
```

# Steps to reproduce

Cntl-Shift-, to bring up the new UI. Click on "Command Prompt" or "Base layer".  Select the "Appearance" tabl. Scroll down to "Cursor". Notice the "Underscore" and "Double Underscore" settings.

# Expected behavior

The "Underscore" setting should show a single underscore, and the "Double Underscore" setting should show a double underscore.

# Actual behavior

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/106199318-e1f89080-617a-11eb-86b8-1caaf7e75dc2.png)


What system language are you using? Maybe one of the localizations got messed up?

**Comment by nobozo** [comment]
On 1/28/2021 1:11 PM, Mike Griese wrote:
> image 
> <https://user-images.githubusercontent.com/18356694/106199318-e1f89080-617a-11eb-86b8-1caaf7e75dc2.png>
> 
> What system language are you using? Maybe one of the localizations got 
> messed up?

No, it's more embarrassing than that.

I have a 28" 4K monitor. Because the pixels are so fine, I didn't see
the double underscore as 2 underscores, 1 on top of the other. I just
saw 1 underscore that was twice as short horizontally than the other.
In other words, I thought that "double" was referring to the horizontal
dimension, not the vertical dimension.

It would be nice if both underscores were the same length, but I don't
know if there's a character for that.

You can close this issue.

Thanks for the quick reply.

Jon

**Comment by zadjii-msft** [comment]
Don't worry about it! Thanks for following up. I think we're tracking "fix the characters in that menu" somewhere in the Setting UI project. It's definitely something on our radar ☺️
