### ISSUE TITLE
Right Click on tab closes window

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#8929]
# Environment

```none
Microsoft Windows [Version 10.0.19042.746]

Windows Terminal
Version: 1.5.10271.0


```

# Steps to reproduce

Right click on a tab and move the mouse.. (see picture)
![rightclick_closes](https://user-images.githubusercontent.com/7850737/106204059-a2eb2f00-61bc-11eb-819a-05cba745fd2c.gif)

# Expected behavior

Windows Terminal should not close without clicking....

# Actual behavior

Windows Terminal closes...

**Comment by KalleOlaviNiemitalo** [comment]
Previously reported as <https://github.com/microsoft/terminal/issues/8238>.

**Comment by zadjii-msft** [comment]
oof yea this is /dup #8238. We accidentally slipped this feature into the release, when we should have held it back. Yikes.
