### ISSUE TITLE
deploy error on visual studio 2017

### ISSUE THREAD

**Issue by ThomasAndreatta** [microsoft/terminal#893]
![image](https://user-images.githubusercontent.com/37804658/57966953-1f8e9900-7959-11e9-8452-d6a49a629f23.png)

i'm actually running the lastest version of windows 10 and i've installed everything in vs, done all the command for the nuget and submodule but when i try to deploy the app vs return me this 3 errors, some help?
(2^ error : uscita dal comando = exit from the command
 3^ error: con codice 1 = with code 1)

**Comment by itsrrworld** [comment]
Hey @ThomasAndreatta , 
Can you please share the steps you followed for building the solution?

**Comment by DHowett-MSFT** [comment]
It looks like we still have an error with spaces in the folder name where you’ve checked out the code.

**Comment by DHowett-MSFT** [comment]
For now, try not to build in a folder name with spaces. Sorry!
