### ISSUE TITLE
Open a new tab in an existing window using the command line

### ISSUE THREAD

**Issue by juzi214032** [microsoft/terminal#8932]
# Description of the new feature/enhancement
I created a right-click menu in the background of the directory with the following command:
```shell
C:\Users\Juzi\AppData\Local\Microsoft\WindowsApps\wt.exe new-tab -d "%V"
```
Currently it opens a new window to run terminal each time, but what I want to achieve is to not open a new window if there is already a terminal instance, but to add a new tab to the existing terminal instance.

Can such a function be implemented? Thanks.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/4472> would cover this feature.

**Comment by juzi214032** [comment]
> #4472 would cover this feature.

thanks

**Comment by zadjii-msft** [comment]
Yes, that's the one. Thanks!

/dup #4472
