### ISSUE TITLE
Context Menu -> Open in Windows Terminal -> "The server threw an exception"

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#8936]
Note:
1. Right Clicking on a folder and then opening the terminal works.
2. Going inside the folder, then right clicking on empty space, and then opening the terminal gives error.
3. I believe this was a known issue with older windows versions, that is why it was disabled earlier, but i think i saw a PR that implemented the functionality differently for older windows, but it is still not working for me
4. I restarted explorer.exe, still gives the error. Maybe restarting the computer will make it work? I will try later and update the issue if it works. EDIT: Nope, still not fixed.

![image](https://user-images.githubusercontent.com/71010204/106245149-04011a00-6232-11eb-95a8-b7ebba67a6e9.png)

![image](https://user-images.githubusercontent.com/71010204/106245156-082d3780-6232-11eb-993e-9fc77f0195f5.png)

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1256]
Windows Terminal version: Windows Terminal Preview v1.6.10272.0

Any other software?: Not applicable
```

# Steps to reproduce

Context Menu -> Open in Windows Terminal -> "The server threw an exception"

# Expected behavior

It should work

# Actual behavior

It doesn't

**Comment by LucaBlackDragon** [comment]
The same is happening both with Preview (1.6.10272.0) and Stable (1.5.10271.0) release.

The Preview release writes the following error event in the Windows Registry (I have translated the message since my system language is Italian):
```
Name of application that generated the error: WindowsTerminal.exe, version: 1.6.2101.27002, timestamp: 0x6011c2d5
Name of module that generated the error: VCRUNTIME140.dll, version: 14.28.29334.0, timestamp: 0x5fa9a822
Exception code: 0xc0000005
Error offset 0x00000000000012de
ID of process that generated the error: 0x23e0
Start time of application that generated the error: 0x01d6f6121a1edfc5
Path of application that generated the error: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.6.10272.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Path of module that generated the error: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.6.10272.0_x64__8wekyb3d8bbwe\VCRUNTIME140.dll
Report ID: 49018434-096f-4cef-bc1a-bd7dff740a23
Complete name of package that generated the error: Microsoft.WindowsTerminalPreview_1.6.10272.0_x64__8wekyb3d8bbwe
ID of application relative to the package that generated the error: App
```
The Stable release, on the other hand, keeps its own secrets and doesn't write anything in the Windows Registry.

**Comment by zadjii-msft** [comment]
Curious. 

@axcadsd do you also have both the Stable and Preview versions of the Terminal installed? It might be helpful to get this crash dump:

/feedback

**Comment by LucaBlackDragon** [comment]
> Curious.
> 
> @axcadsd do you also have both the Stable and Preview versions of the Terminal installed? It might be helpful to get this crash dump:
> 
> /feedback

Hi @zadjii-msft, I have sent a report with the Feedback Hub as instructed, after having uninstalled both Preview and Stable and performed a fresh install of Stable (unfortunately the issue remains).
You can find it here:
https://aka.ms/AAaz4tf
I have also put the URL of this issue in the feedback description.

**Comment by axcadsd** [comment]
@zadjii-msft 
I only use the Preview version, stable is not installed.
Also, on my computer, the preview version is not creating any logs in the Event Viewer.
Also, restarting the computer does not fix the issue.

Hopefully LucaBlackDragon's logs will help fix the issue.

**Comment by zadjii-msft** [comment]
Huh, that got bucketed to `6c7b8911-e1ad-4e2c-4d48-c5aa5aacca38`, but unfortunately the crash dump doesn't have anything useful in it. Just a single useless stack frame for `diagtrack.dll` in `svchost.exe`. That doesn't mean anything to me unfortunately 😖

**Comment by axcadsd** [comment]
any instructions on how to debug / provide useful information?

**Comment by zadjii-msft** [comment]
If it's not too much trouble, we might be able to figure this out by building from source and throwing breakpoints at the top of `OpenTerminalHere::_GetPathFromExplorer`, in `...src\cascadia\ShellExtension\OpenTerminalHere.cpp`. Since this only repros when right clicking in the empty space in explorer, then I'm pretty sure it's due to the code in that function. 

/cc @hereafter, because they might have some ideas what's going on here (#8638)

**Comment by nc-x** [comment]
Note to anybody else debugging the issue:
Set the breakpoint after this line, otherwise GetForegroundWindow() returns wrong HWND (of something inside Diagnostics Tools pane in VS)
https://github.com/microsoft/terminal/blob/e7d32625befb85e5b40380de20c62172e7275c5e/src/cascadia/ShellExtension/OpenTerminalHere.cpp#L242

Anyways, this is the line that fails -
https://github.com/microsoft/terminal/blob/e7d32625befb85e5b40380de20c62172e7275c5e/src/cascadia/ShellExtension/OpenTerminalHere.cpp#L269

**Comment by ahmedDev20** [comment]
Same issue for me, still not working 😟

**Comment by Kiyo5hi** [comment]
Same issue for me.

**Comment by wd30x** [comment]
Same issue +1

**Comment by zadjii-msft** [comment]
If you'd like to "+1" this feature, the best way to do that is by hitting the 👍 button on this issue

![image](https://user-images.githubusercontent.com/18356694/96140789-ef3c8880-0ec5-11eb-82e0-30ce4977b9a7.png)

That way, you avoid unnecessarily pinging everyone following this thread. Thanks!

**Comment by hereafter** [comment]
i am not able to repro the issue.

I suspect it is due to the context
so could you please change the line to 
 auto shell = create_instance<IShellWindows>(CLSID_ShellWindows, CLSCTX_ALL);

**Comment by nc-x** [comment]
@hereafter 
```cpp
auto shell = create_instance<IShellWindows>(CLSID_ShellWindows, CLSCTX_ALL);
```
gives -
![image](https://user-images.githubusercontent.com/43749640/106386364-a4a23600-63fa-11eb-922a-a03ab47ed872.png)

**Comment by hereafter** [comment]
@nc-x could you kindly please set up a remote session for me? 
my email is : tu.tong@outlook.com

**Comment by hereafter** [comment]
@nc-x 

could you please take the code here

https://github.com/hereafter/terminal/tree/dev/hereafter/context-menu-patch


![image](https://user-images.githubusercontent.com/1483954/106387090-0cfd1180-6413-11eb-8ca4-6d1f9f857dd7.png)

to see if it works for you now

**Comment by nc-x** [comment]
Thanks, it works perfectly.
```diff
diff --git a/src/cascadia/ShellExtension/OpenTerminalHere.cpp b/src/cascadia/ShellExtension/OpenTerminalHere.cpp
index bd748338..1c2649df 100644
--- a/src/cascadia/ShellExtension/OpenTerminalHere.cpp
+++ b/src/cascadia/ShellExtension/OpenTerminalHere.cpp
@@ -266,7 +266,7 @@ std::wstring OpenTerminalHere::_GetPathFromExplorer() const
         return path;
     }
 
-    auto shell = create_instance<IShellWindows>(CLSID_ShellWindows);
+    auto shell = create_instance<IShellWindows>(CLSID_ShellWindows, CLSCTX_ALL);
     if (shell == nullptr)
     {
         return path;
@@ -285,6 +285,7 @@ std::wstring OpenTerminalHere::_GetPathFromExplorer() const
         com_ptr<IWebBrowserApp> tmp;
         if (FAILED(disp->QueryInterface(tmp.put())))
         {
+            disp = nullptr;
             continue;
         }
 
@@ -293,8 +294,10 @@ std::wstring OpenTerminalHere::_GetPathFromExplorer() const
         if (hwnd == tmpHWND)
         {
             browser = tmp;
+            disp = nullptr;
             break; //found
         }
+        disp = nullptr;
     }
 
     if (browser != nullptr)
```
I have also set up teamviewer, so in case any more debugging is required, please let me know.

**Comment by hereafter** [comment]
alright that would good enough i am making a pr to the mess i left

**Comment by zadjii-msft** [comment]
Wow, good work on the investigation here everyone! Thanks!

**Comment by typedefstructer** [comment]
was here to report this issue...how do I get this now?

**Comment by zadjii-msft** [comment]
Right now, we've committed the fix to `main`. We're working on a couple other hot bugs right now, and should have a servicing release out later this week. Thanks for the patience!

**Comment by AlJohri** [comment]
hi @zadjii-msft! just wanted to check in to see if this fix was released? I see that the issue is assigned to the v1.7 milestone- should I check back on February 28th?

**Comment by CodingCreate101** [comment]
Maybe a point worth noting - When I use context menu as the OP has shared, it gives me an error but if I right-click on the folder itself and choose `Open in Windows Terminal`, it does work.

![image](https://user-images.githubusercontent.com/13194757/107460226-b8c60000-6b7d-11eb-90fe-c24871c89a01.png)

![image](https://user-images.githubusercontent.com/13194757/107460451-27a35900-6b7e-11eb-8fab-4d199e9b6a90.png)

**Comment by DHowett** [comment]
This is due to be released in a bugfix update to 1.6 this week.

**Comment by schlamar** [comment]
But stable 1.5 won't get an update?

**Comment by zadjii-msft** [comment]
1.5 won't get an update because the bug _wasn't present in 1.5_. The support for the context menu in the background of a directory was only added in 1.6. That feature had a bug that would cause this error message for some users. We can patch that bug in 1.6, but we're not going to bring the whole feature down a level (since clearly, it needs more time to bake in Preview).

**Comment by schlamar** [comment]
@zadjii-msft I have 1.5.10271.0 installed, there is this entry in the context menu and I'm getting this error. I haven't installed the Preview version.

**Comment by zadjii-msft** [comment]
Well, that's certainly not expected. @DHowett we didn't sneak this context menu entry into 1.5, did we?

**Comment by schlamar** [comment]
It's in the changelog: https://github.com/microsoft/terminal/releases/tag/v1.5.10271.0

**Comment by zadjii-msft** [comment]
Well then this should probably be serviced to 1.5 too. That's what we get for sneaking features into the stable builds.

**Comment by zadjii-msft** [comment]
@arthursoas Please read the thread. This is fixed in `main`, and is going to get serviced (_read: pushed to the store as an update_) to 1.6 (**and 1.5**) later this week.
