### ISSUE TITLE
how to close "open in windows terminal"

### ISSUE THREAD

**Issue by juzi214032** [microsoft/terminal#8937]
# Description of the new feature/enhancement
How to close the right-click menu of "open in windows terminal"

![image](https://user-images.githubusercontent.com/38206169/106247163-1d15c500-624a-11eb-8c3f-d04bbe51b659.png)

**Comment by zadjii-msft** [comment]
Right now, there's not a way to do that. We're tracking adding a setting to remove it in #8105. Thanks!

/dup #8105
