### ISSUE TITLE
Clicking on empty space doesn't dismiss the colour scheme list in the new Settings UI

### ISSUE THREAD

**Issue by AgrMohit** [microsoft/terminal#8938]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```

# Steps to reproduce

Open the list of colour schemes in the Settings UI and click anywhere on empty space
# Expected behavior

There is an expectation that like most apps clicking on empty space will dismiss the list
# Actual behavior
On clicking on empty space the list is not dismissed

Image for reference
![image](https://user-images.githubusercontent.com/32242258/106247399-7de6d280-6235-11eb-9de1-33fd95c541ed.png)

**Comment by axcadsd** [comment]
This is not specific to the color scheme list, most (all?) elements in the settings ui are currently behaving like this (for me atleast).

**Comment by zadjii-msft** [comment]
Yea, this is unfortunately due to a bug in WinUI itself. We're tracking this on our side in #8769, and the upstream bug is microsoft/microsoft-ui-xaml#3961.

> Appearance -> Open 'Color scheme' dropdown -> Cannot dismiss the dropdown by clicking somewhere else
> * Moved to Light-dismiss doesn't work on ComboBox in XAML Islands [microsoft/microsoft-ui-xaml#3961](https://github.com/microsoft/microsoft-ui-xaml/issues/3961)



/dup #8769
