### ISSUE TITLE
Warning "Unable to find the selected font " and still loading the selected font

### ISSUE THREAD

**Issue by lolcatnip** [microsoft/terminal#8939]
# Environment

```none
Windows build number: [Version 10.0.19042.746]
Windows Terminal Preview: 1.6.10272.0
```

# Steps to reproduce

Open Windows Terminal with the custom font set in settings file.

# Expected behavior

Load font and do not show any warning.

# Actual behavior

The warning is showed but also the font is loaded correctly.

![wt_font_warning_ad](https://user-images.githubusercontent.com/25205029/106248729-ac52b680-6211-11eb-9c2f-55d2a97c799d.png)

**Comment by zadjii-msft** [comment]
Uh, that font isn't SF Mono Regular...
![image](https://user-images.githubusercontent.com/18356694/106268983-7ac9f300-61f1-11eb-83fd-4fe85ed5439b.png)

That looks like Consolas to me...

**Comment by lolcatnip** [comment]
> 
> 
> Uh, that font isn't SF Mono Regular...
> ![image](https://user-images.githubusercontent.com/18356694/106268983-7ac9f300-61f1-11eb-83fd-4fe85ed5439b.png)
> 
> That looks like Consolas to me...

That's true, closing this "issue"
