### ISSUE TITLE
Going to the settings option launches Altova XMLSpy 2020 !

### ISSUE THREAD

**Issue by richcbaker** [microsoft/terminal#8940]
Hi,
Going to the settings option launches Altova XMLSpy 2020 ! and not the settings.

Thanks
Richard

# Environment
Windows 10 

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows 10 Pro 20H2 (OS Build 19042.746)

Windows Terminal version (if applicable):
Windows Terminal Preview 1.6.10272.0
Any other software?
```

# Steps to reproduce

Going to the settings option launches Altova XMLSpy 2020 ! and not the settings.

# Expected behavior

go to the Settings dialogue 

# Actual behavior

 Altova XMLSpy 2020 is launching

**Comment by zadjii-msft** [comment]
Is Altova XMLSpy 2020 set as you default json editor? Because the Settings button is still going to launch the `settings.json` file in your default json editor.

**Comment by richcbaker** [comment]
thanks it is, what would it need to be to work as Scott Hanselman demonstrated here ?
Thanks
Richard

Scott Hanselman (@shanselman) tweeted at 7:01 am on Fri, Jan 29, 2021:
Did you get the new Windows Terminal Preview?
🚨THERE IS A SETTINGS UI🚨
https://t.co/2Sww8rXSKJ https://t.co/wgFwHKOagR
(https://twitter.com/shanselman/status/1355048497343459329?s=03)

**Comment by zadjii-msft** [comment]
From our [release notes](https://github.com/microsoft/terminal/releases):

> * **IN PREVIEW TODAY**: Terminal now has an optional graphical settings editor! Until it's ready for prime time, it's hidden behind a NON-DEFAULT key binding. (#8048)
>    * To bind the settings UI to <kbd>Ctrl+Shift+,</kbd>, add the following to your `keybindings`/`actions`.
> ```json
> { "command": { "action": "openSettings", "target": "settingsUI" }, "keys": "ctrl+shift+," },
> ```
> *
>    * The settings editor will become the default action for the Settings menu item and key binding in a future release.
>    * Follow along at #6800 for completion stats and community feedback!

**Comment by richcbaker** [comment]
Thanks that's great.
