### ISSUE TITLE
Powershell is always default

### ISSUE THREAD

**Issue by reya-create** [microsoft/terminal#8941]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
You gotta provide a little bit of information for us to work with. We can't really help investigate a blank issue like this. 

If you can provide more info, we'd be happy to reopen and help investigate.
