### ISSUE TITLE
Interrupt (ctrl+c) closes Windows Terminal instead of the currently running program

### ISSUE THREAD

**Issue by bogdanm** [microsoft/terminal#8942]
# Environment

Windows build number: 

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```

Windows Terminal version: Windows Terminal Preview version 1.6.10272.0 (but note that this also happened in previous versions)

Powershell version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  610
```

# Steps to reproduce

- Open a Powershell window in Windows Terminal.
- Install Lua 5.1, for example using "scoop" (`scoop install lua-for-windows`) (my version is 5.1.5-52). **NOTE**: this behavior was noticed in other programs too, not just the Lua REPL (for example, the Python 3.8.7 REPL behaves in the exact same way).
- Start the Lua REPL ("lua")
- Press CTRL+C after the REPL starts.

# Expected behavior

The Lua REPL exists and the Powershell prompt is displayed again.

# Actual behavior

The Powershell window closes completely. If the Powershell window was the single window inside Windows Terminal, then Windows Terminal exits too.

# Other information

This doesn't happen if I run Powershell separately (Win+R then "powershell"). In this case, the Lua REPL exists as expected.

This doesn't happen if I run the lua REPL in a command prompt window (not Powershell) inside Windows Terminal. Again, in this case, the Lua REPL exists as expected.

**Comment by zadjii-msft** [comment]
This sounds _a lot_ like #4899. That one was using pwsh 7 from `scoop`, but I wonder if installing Lua from `scoop` would do the same thing. 

/cc @DHowett

**Comment by bogdanm** [comment]
Thanks for your reply. It might be a different issue here though:

- I did not install Powershell via `scoop`
- The same thing happens when I run the Python 3.8.7 REPL (which is not installed via `scoop` either).

**Comment by bogdanm** [comment]
I just did another experiment:

- I downloaded the SQLite CLI from https://sqlite.org/download.html (https://sqlite.org/2021/sqlite-tools-win32-x86-3340100.zip) and unpacked it somewhere in my PATH.
- I ran `sqlite3` from Powershell inside Windows Terminal.

The exact same thing happened. It looks like a lot of programs that expose a REPL-like interface are affected.

**Comment by skyline75489** [comment]
What's the version of your PowerShell & PSReadline? I can't reproduce this issue on my machine.

**Comment by bogdanm** [comment]
> What's the version of your PowerShell & PSReadline? I can't reproduce this issue on my machine.

Unfortunately I didn't write down the previous version of the PSReadline package on my machine, however I updated it using the instructions from https://github.com/PowerShell/PSReadLine/ and now everything else as expected. Thank you, I didn't even think about PSReadline as a possible cause for this issue.
