### ISSUE TITLE
After upgrading to 1.6, mouse input is not working on my primary screen (works on screen 2+3)

### ISSUE THREAD

**Issue by oocx** [microsoft/terminal#8943]
# Environment

```none
Windows build number: 10.0.21296.1010
Windows Terminal version (if applicable): 1.6.10272.0

Any other software?
```

# Steps to reproduce

1) Upgrade to wt 1.6 (I did not see the problem with previous versions)
2) Use wt on my primary screen -> mouse input does not work
3) Move wt to screen 2 or 3 -> mouse input works

# Expected behavior

Mouse input should work on all screens.

# Actual behavior

After upgrading to 1.6, mouse input stopped working when I use wt on my primary screen. It works on screen 2 +3.

This includes interaction with the title bar like clicking on the "close", "maximize", "minimize" buttons, tab selection, new tab and so on, but also interaction with the terminal area like text selection. It just does not accept any mouse input at all.

If I move the terminal to another screen, mouse input works. When I move it back to my primary screen, it stops working. If it is partly on my primary screen and partly on another screen, then only the part that is on screen 2/3 accepts mouse input.

**Comment by zadjii-msft** [comment]
Do you have PowerToys installed?

**Comment by oocx** [comment]
Yes, PowerToys 0.16.1.0

Quitting PowerToys fixes the problem. Thanks! :)

Is this a PowerToys or a WT Bug? If it is a PowerToys Bug, I would open an issue in the PT repo.

**Comment by zadjii-msft** [comment]
Thanks for confirming. I'm _pretty sure_ it's a Powertoys bug. We're tracking this in #6120, #3325, and
* microsoft/PowerToys#4360
* microsoft/PowerToys#3833
* microsoft/PowerToys#3250
* microsoft/PowerToys#3090

I haven't heard any reports of this on newer PowerToys versions. Thanks for sharing the version too - I think you'll probably never see this again if you update PowerToys.

/dup #3325
