### ISSUE TITLE
Why Don't You Make It Like ConEmu But Better?

### ISSUE THREAD

**Issue by opticyclic** [microsoft/terminal#8945]
# Description of the new feature/enhancement

Make it like ConEmu but better.

ConEmu already exists as a multi-tabbed, multi-shell application.
It has been around for 13 years.

Why don't you just take all the useful features from that and then improve on it?

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Thanks for filing, but sorry, this isn’t a particularly useful request. It amounts to saying “it is bad. Make it better” without any actionable feedback.

**Comment by opticyclic** [comment]
That's true. I probably should have been more specific.
However, my first impression of terminal was surprisingly poor.

Whilst this is not a useful that can be actioned, perhaps the developers can use ConEmu for a while and identify the features of it that _they_ like.

Based on the tiny feature set of terminal, it seems like the developers haven't used any multi-tabbed, multi-shell application before and could do with some inspiration.

**Comment by zadjii-msft** [comment]
We _have_ identified the features we like, and we add them all the time. We've got tabs, we've got panes, we've got progress bars, commandline arguments, background gifs, pixel shaders, clickable hyperlinks. We've got plenty more on the backlog too - quake mode, theming, extensions. 

What features are _you_ missing? What part of ConEmu do _you_ think the terminal is missing?

**Comment by opticyclic** [comment]
I guess it is related to this https://github.com/microsoft/terminal/issues/8946

The `settings.json` still pops up from the Setting menu even with 

> Windows Terminal Preview
> Version: 1.6.10272.0

which then leads to the _seemingly_ missing features:

- There is no _visible_ option to change the default shell
- There is no _visible_  way to add new shells e.g. PowerShell admin
- There is no Help or Documentation in the _usual_ location until you realise it is weirdly linked in the About page
- There is no obvious way to change colour schemes or fonts
- No option to split terminal screens
- Quake mode

Based on some of the things you have helpfully pointed out I probably should have made this issue "Make features more discoverable"

Sorry about that.

**Comment by zadjii-msft** [comment]
Okay, so this boils down to "I want a settings UI. I didn't read the documentation, so I can't find features". We are trying our best to make settings more discoverable. Until we had a settings UI, the best way to find features was on our [docs page](https://docs.microsoft.com/en-us/windows/terminal/), which is linked to in the settings json file: 
https://github.com/microsoft/terminal/blob/2c603ef953752b315f3c1e1c4b49368c76390cf3/src/cascadia/TerminalSettingsModel/userDefaults.json#L7


There you can find docs on:
* [Changing the default profile](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#default-profile)
* [Adding new profiles](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-general)
* [Changing the appearance of a profile](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance)
* [Adding color schemes](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes)
* [Splitting panes](https://docs.microsoft.com/en-us/windows/terminal/panes)

The Settings UI is [currently in preview](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-6-release/#settings-ui), and is still being polished before we roll it out broadly.

Quake mode we're tracking in #653, which is something I'm _currently writing a spec for_. Anything else you're missing?
