### ISSUE TITLE
Add A Settings Page

### ISSUE THREAD

**Issue by opticyclic** [microsoft/terminal#8946]
# Description of the new feature/enhancement

There doesn't _appear_ to be any way to change the settings from the GUI.
The settings button opens a generated json file and not the actual settings file.
Provide a UI to change the settings.

# Proposed technical implementation details (optional)

Its fine to store the settings in a json file and allow people to edit it as an advanced option.

However, provide a UI for people to click on and change common settings easily.
e.g. 
- Tick a button to set my default shell
- Select from a drop down the font I want to use
etc etc

**Don't** just pop up the json file to edit though.

**Comment by KalleOlaviNiemitalo** [comment]
This week's [Windows Terminal Preview v1.6.10272.0](https://github.com/microsoft/terminal/releases/tag/v1.6.10272.0) already has a settings UI. Users have been finding bugs in it today.

**Comment by zadjii-msft** [comment]
Yea, please search before filing new issues. 

/dup #1564
