### ISSUE TITLE
Cannot Change Tab Switcher Interface Style on Preview v1.6.10272.0

### ISSUE THREAD

**Issue by ShubhamBelwal** [microsoft/terminal#8947]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.746]
Windows Terminal version (if applicable): Windows Terminal Preview v1.6.10272.0

Any other software? NA
```

# Steps to reproduce

1. Open Settings UI
2. Navigate to Interaction -> Tab switcher interface style
3. Try to select option other than the selected one

# Expected behavior

Tab switcher interface style should change to the new value

# Actual behavior

Tab switcher interface style defaults to the previous value.

![2021-01-29_19-41-26](https://user-images.githubusercontent.com/36201797/106286453-aee1fa00-626b-11eb-92f8-6e803369d622.gif)

**Comment by zadjii-msft** [comment]
Hmm. That's weird. Doesn't happen to any of the other settings on that page. Wonder if the two-way binding is broken on that one....

**Comment by carlos-zamora** [comment]
Yup! Looks like we forgot to add `Mode="TwoWay"` for TabSwitcherMode. Same issue for launch mode. PR incoming!
