### ISSUE TITLE
Terminal crashes instantly when exploring an invalid icon path in Settings UI.

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#8950]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 19042
Windows Terminal version (if applicable): 1.6 Preview

Any other software?
```

# Steps to reproduce

Unzip the msix bundle until you can launch WindowsTerminal.exe from CascadiaCodex64. Bind the Settings UI using the action listed in Github release notes. Note this requires the settings.json from 1.5 as 1.6 doesn't appear to generate a new one if the old is deleted (separate issue).  Open the Settings UI. Navigate to the Windows Powershell profile. Click "Browse" from the icon field to attempt to browse to the icon.  The entire terminal window crashes and dies instantly. 

# Expected behavior

I expect either the WIndows Powershell icon to load or for an error to be raised saying the path is invalid and also offer to let me navigate to the path. It should never crash.

# Actual behavior

It crashes so fast, it's almost faster than the blink of an eye.

Context: When using Windows Terminal completely offline, the only way to launch it is to extract it. When this happens, it appears that the icons no longer appear in the dropdown menu. I was hoping to use the Settings UI to conveniently change the filepath. It would be even more preferable if the icon was searched for when opening Windows Terminal if the icon fails to load and the proper path added in. The CMD icon is also missing.

**Comment by DHowett** [comment]
Just so you know:

* unpackaged execution is not officially supported. If it works, it is by luck, *not* by explicit design. If it doesn’t work, “oh well”
* not seeing any icons in the dropdown is a symptom of incorrectly extracting the MSIX file
* when using Terminal completely offline, _on a machine that will never go online_, we offer a preinstallation kit that contains the software licensing data Windows would otherwise get from the store.

**Comment by WSLUser** [comment]
I still would think we would want to prevent crashes from happening however. There are a great deal of people who use this offline. We have issues dedicated to that support and discussion. Terminal should never crash regardless if it was through an offline installation. I have a Store installed version on a different host so I can check if I can reproduce but likely the reproducer is having an invalid path. Use of the offline likely makes it easier to hit faster than it would otherwise (since the paths do exist correctly on a Store installed version of Terminal).

**Comment by DHowett** [comment]
I don’t disagree with you about the crash, but I want to make this one thing perfectly clear:

_This is not an offline install. This is not an installation of Windows Terminal. This is an implementation detail that happens to work for some people. This is not an installation of Windows Terminal._

**Comment by DHowett** [comment]
I do still think that the crash is worth investigating, as is whatever caused your settings file to not be recreated (!).

**Comment by DHowett** [comment]
And lastly:

Schema validation is only a helpful editor feature. It is not required for Terminal to function, and in many cases the schema you are seeing (stable version) will not match the features your terminal (preview version). The worst thing this will cause is some red squiggles in VSCode.

Schema compliance is just one indicator of the ability to use a feature. If your editor says the schema is invalid, _but you have a good authority telling you that a JSON snippet will work_, and you are using the appropriate version of terminal: **it will work.**

**Comment by WSLUser** [comment]
Hmm, well on the Store installed version, it says that settingsUI is invalid and expects something like "settingsfile" and reloads to default settings. That's unrelated to this issue though and don't want to clutter it up anymore. I did notice the settings.json being used on the Store installed version is from 1.2. That also likely needs to be regenerated though I'm not comfortable now that it will be. Probably should file another issue for that.

**Comment by DHowett** [comment]
The default settings file hasn’t changed since 1.0, so regenerating yours won’t make a difference :) the schema issue is just because the default schema URL is for the stable version of terminal, which is missing the settings UI of course.

**Comment by WSLUser** [comment]
Yeah, I'm not worried abou the schema. I redirected it to point to the main branch directly. I had this previously but lost it when I had to regenerate my settings.json some months ago.

**Comment by WSLUser** [comment]
https://github.com/microsoft/terminal/issues/8955 created for the settings file not getting regenerated.

**Comment by extratype** [comment]
You can fix icons by renaming files in `ProfileIcons` directory. Replace `%7B` by `{` and `%7D` by `}`.

**Comment by WSLUser** [comment]
In my instance, I had to remap the path to the icon files included in the msix directly (removing the ms:appx prefix and using C:\...) Then clicking browse was successful and correctly loaded the icon. Replacing an icon on any existing profile with an invalid path (due to a typo or the file was deleted, etc.) will result in the same crash.

**Comment by DHowett** [comment]
> Navigate to the Windows Powershell profile. Click "Browse" from the icon field to attempt to browse to the icon. The entire terminal window crashes and dies instantly.

I cannot reproduce this, even when unpackaged.

Can you file feedback using the Applications->Windows Terminal section and send us a link to it? Please make sure you use the "Recreate my problem" button and crash it while recreating your problem.
