### ISSUE TITLE
Moving tabs between windows

### ISSUE THREAD

**Issue by ekolis** [microsoft/terminal#8951]
# Description of the new feature/enhancement

Sometimes I have multiple terminal windows open (for instance, "Open in Windows Terminal" in File Explorer or the desktop creates a new window)  and I want to merge them together. Other times I have several tabs in a single terminal window that I want to split apart into their own windows, because they have separate purposes.

# Proposed technical implementation details (optional)

I would like to be able to drag terminal tabs between windows: both from one window to another (to move the tab), and from a window to the outside (to make a new terminal window). This feature already exists in browsers (e.g. Chrome and Edge), so it makes sense to implement in other tabbed interfaces.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to the following for more discussion.

/dup #5000
/dup #1256
