### ISSUE TITLE
Context menu on the tab bar expands in the wrong direction

### ISSUE THREAD

**Issue by DustRespirator** [microsoft/terminal#8953]
# Environment

```none
Windows build number: Windows 10 Pro x64 20H2 19042.746
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce

click the button to expand the context menu on the right side of tab bar

# Expected behavior

the menu expands down and it is aligned. I found a screenshot from internet because I do not have previous version.
![image](https://user-images.githubusercontent.com/32119993/106311722-365b4900-622b-11eb-9b0a-0dc6251192a7.png)

# Actual behavior

the menu will expand upward and it does not align the button.
![image](https://user-images.githubusercontent.com/32119993/106311954-8c2ff100-622b-11eb-8c4c-505ee8e204f3.png)
I uninstalled terminal and reinstall again to test with default settings to make sure it is unrelated to settings.json.
I think it would be a feature to avoid blocking the window, but it is annoying and in fact if user uses context menu they will not stay on the menu too long and it does not matter to block the window for some seconds.

**Comment by Don-Vito** [comment]
@DustRespirator - please see https://github.com/microsoft/terminal/issues/8924

**Comment by zadjii-msft** [comment]
Yep, that looks like a duplicate to me.

/dup #8924
