### ISSUE TITLE
Browse buttons crash when running as admin

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8957]
The optional graphical settings editor worked properly when I ran Windows Terminal as a regular user. However, if I ran Windows Terminal as Administrator, the app would crash if I clicked the "Browse..." button for either "Command line" or "Starting directory".

_Originally posted by @huang63 in https://github.com/microsoft/terminal/issues/6800#issuecomment-769568274_

**Comment by carlos-zamora** [comment]
Did a bit of digging on this one. Here's my findings:

Relevant PR: #8391 

The culprit is this call right here:
https://github.com/microsoft/terminal/blob/e7d32625befb85e5b40380de20c62172e7275c5e/src/cascadia/TerminalSettingsEditor/Profiles.cpp#L348

I'm not exactly sure what is going on though. Looks like `PickSingleFolderAsync()` failed, and `GetResults()` returns a bad HRESULT.

Assigning @DHowett for now to provide some ideas/insight on next steps.

**Comment by DHowett** [comment]
You’re gonna need to give me that HRESULT!

I’m guessing this is the same class of problem as “i can’t drag tabs in admin mode”. Same team, same APIs...

**Comment by WSLUser** [comment]
I'm now betting https://github.com/microsoft/terminal/issues/8950 is extremely related. It didn't matter if it was elevated or not so I think invalid paths are still an issue that likely correlate to this bug. Perhaps they have the same fix (one can hope).

**Comment by carlos-zamora** [comment]
> You’re gonna need to give me that HRESULT!
> 
> I’m guessing this is the same class of problem as “i can’t drag tabs in admin mode”. Same team, same APIs...

`-2147467259` --> `0x80004005 : 'Unspecified error'.` --> `E_FAIL` is returned from the `GetResults()` call.

**Comment by carlos-zamora** [comment]
@DHowett friendly bump on this thread to get it on your radar

**Comment by zadjii-msft** [comment]
In #9341, @rileysea was also seeing this _unelevated_ 😬
