### ISSUE TITLE
Terminal tile in Start menu goes very dark

### ISSUE THREAD

**Issue by truckee** [microsoft/terminal#8961]
# Environment

```
Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal
Version: 1.5.10271.0

```

# Steps to reproduce

I wish I knew. Behavior is unpredictable

# Expected behavior

I would expect the Windows Terminal tile not to change contrast.

# Actual behavior

Here is a screenshot showing the tile while the mouse hovers
![terminal_tile](https://user-images.githubusercontent.com/2782760/106340660-63215780-624f-11eb-86ac-5c550403e95c.jpg)
:

I have observed this several times. The only known solution is to uninstall/reinstall

**Comment by zadjii-msft** [comment]
I'm _pretty sure_ this is just the Store getting confused. You'll note the roughly halfway-full progress bar at the bottom of the tile: for whatever reason, the Store made the Start Menu think the app is still updating, even when it's finished. So you should still be able to launch the Terminal just fine, it's just the Start Menu is bugged.

If it really bothers you, I'm pretty sure just rebooting your machine will fix this - no need to reinstall the app entirely
