### ISSUE TITLE
Color scheme environment variable 

### ISSUE THREAD

**Issue by flippidippi** [microsoft/terminal#8963]
# Description of the new feature/enhancement
Add environment variable, similar to WT_PROFILE_ID, that indicates the currently selected color scheme name. This would allow programs like VIM to read this variable and change their color scheme based on the current terminal color scheme.

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
My understanding was that VIM achieved this by querying the color scheme using the OSC 4/10/11 escape sequences. See issue #3718.

**Comment by zadjii-msft** [comment]
Yea, I'd much rather support those OSCs. One thing to keep in mind is that the color scheme can change at runtime, with the "Set Color Scheme" action. If the user does that, then the WT_SCHEME` (or whatever) variable would be out-of-date, with no way for VIM to read the correct values. 

The OSC 4/10/11 solution _would_ reflect any runtime changes to the scheme, which I think is a much better solution.
