### ISSUE TITLE
Default input method is ALWAYS Chinese IME

### ISSUE THREAD

**Issue by ElizabethEmilia** [microsoft/terminal#8964]
# Environment

```none
Windows build number: [Environment]::OSVersion
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?   
* Windows 10 Simpified Chinese version
* Default IME is "Simpified Chinese (US Keyboard)", with "using language bar" on and "different programs using different IME" on. (Shown in figure 1)
```
![RNKOQV2Q4813FD@L%TL 8_8](https://user-images.githubusercontent.com/9192383/106349642-7e04d200-630a-11eb-8510-2488daf7864f.png)
Figure 1,  Language bar (with `Simpified Chinese (US Keyboard)` selected)

# Steps to reproduce

1. Open the windows terminal in enviroment discribed above.
2. Input from keyboard.

# Expected behavior

Input and echo characters directly if current input method is "Chinese (US Keyboard)" instead of using any Chinese IME, just like any other programs (i.e.  cmd.exe, PowerShell),

![7T2YXJ66IY{5JXPYS`R1%}J](https://user-images.githubusercontent.com/9192383/106349830-1cddfe00-630c-11eb-95d3-93e9fdd8ce5c.png)
Figure 2. The way it expected to be

# Actual behavior

When pressing keyboard, the character is under an IME (Probably "Microsoft Pinying IME", shown in figure 3), and after pressing `space` on keyboard, the input string become Chinese characters (shown in figure 4), although current input method is "US Keyboard".

![LG0JPC1A8UEUUNO0V$Z4%%M](https://user-images.githubusercontent.com/9192383/106349748-7d207000-630b-11eb-82c2-6f8834d962d7.png)
Figure 3 When input from keyboard without manually pressing `SHIFT` key

![9G71LU5{3JR2@AYTV($B2SI](https://user-images.githubusercontent.com/9192383/106349885-90800b00-630c-11eb-8fdc-14cb54763c6b.png)
Figure 4 Then pressing `SPACE`

**Comment by skyline75489** [comment]
I think it's cause by "搜狗输入法(Sogou IME)". See https://github.com/microsoft/terminal/issues/1304#issuecomment-705682131

**Comment by zadjii-msft** [comment]
Okay yea, this sounds a lot like what's going on in that thread. I'm not gonna close it as a duplicate - it seems like that thread is mainly about another issue. But I am going to close this issue as answered. Thanks @skyline75489!

**Comment by ElizabethEmilia** [comment]
> I think it's cause by "搜狗输入法(Sogou IME)". See [#1304 (comment)](https://github.com/microsoft/terminal/issues/1304#issuecomment-705682131)

It may not caused by  Sougou IME, I have tested in another enviroment without Sougou IME installed, but the problem is still. (Shown  in figure 1)
![71Z5LBT_NZ0E1~NJ3}%%HMH](https://user-images.githubusercontent.com/9192383/106603134-dfda6b80-6598-11eb-9164-df6bc9d5f047.png)
Figure 1.

And I replace the `Simpifed Chinese (US Keyboard)` to `English (US Keyboard)`, it works (but also need to switch between languages instead of just between IMEs). Maybe because Windows 10 does not natively add `US Keyboard` to `Simpified Chinese`  IME list  in Settings?

**Comment by JryChn** [comment]
@ElizabethEmilia Check your system input language. You need to add EN/US input method keyboard
![image](https://user-images.githubusercontent.com/22426265/109608174-6e281a00-7b64-11eb-8fc6-5dfcdf72272a.png)
![image](https://user-images.githubusercontent.com/22426265/109608224-813aea00-7b64-11eb-8f67-2ea13db7ac21.png)

**Comment by robeyang** [comment]
Exactly the same issue in my ARM-based Windows 11 24H2 running on Snapdragon(R) X Elite in year 2024.

OS: Windows 11 Home, 24H2, 26100.1457
IME: Microsoft Traditional Chinese IME, 
Windows Terminal: 1.20.11781.0

No matter what kind of settings, it always automatically changes to Chinese input mode instead of "Chinese(English Keyboard) mode" when I switch from other Apps back to Windows terminal.

**Comment by lhecker** [comment]
@robeyang Please try Windows Terminal Preview (v1.21) as it has a new IME implementation. If the problem still occurs then, please open a new issue where we can discuss this.
v1.21 will be the new stable Windows Terminal version later this week.
