### ISSUE TITLE
Sounds not muting with system sounds

### ISSUE THREAD

**Issue by maciejpankanin** [microsoft/terminal#8966]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce
1. Mute system sounds. 
![image](https://user-images.githubusercontent.com/33896387/106351576-7ed33f00-62dd-11eb-897c-f6eb177c7434.png)
2. Open any Linux terminal in Windows Terminal (via SSH or WSL)
3. Use autocomplete when there is nothing to autocomplete.

# Expected behavior
No sound is expected.

# Actual behavior
There is sound.

I encountered this problem when muted system sounds for new Microsoft Edge (there is notification sound when you unsuccessfully search for something with CTRL + F). With Edge it works properly, so I think is unproper behaviour in Windows Terminal.

**Comment by zadjii-msft** [comment]
If you emit a BEL in the vintage console (`conhost.exe`) with system sounds muted, does the sound still play?

**Comment by maciejpankanin** [comment]
It does not.

**Comment by zadjii-msft** [comment]
I wonder if the Terminal bell counts as a system sound. It's a sound emitted by an app, so it might not count as a "system sound".

FYI you can also disable the bell with the profile setting [`"bellStyle": "none"`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#bell-notification-style)

**Comment by j4james** [comment]
On my system, Windows Terminal is just another application in the Volume Mixer, so if you want to control the volume of the bell you can do so from there. Same goes for conhost. I definitely wouldn't have expected our sound to be controlled by the System Sounds volume. The whole point of the volume mixer is so you can control the volume of each app separately.

**Comment by zadjii-msft** [comment]
Yea, that sounds like the right resolution to me. Since the Terminal isn't a part of the OS, it doesn't make sense for it's sounds to be controlled by the System Sounds setting.
