### ISSUE TITLE
Can't save settings.json

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/terminal#8967]
# Environment

```none
Windows build number: 10.0.18363.0  
Windows Terminal version (if applicable): Version: 1.5.10271.0


```

# Steps to reproduce
1. Open Windows Terminal (both with user permissions and with administrator permissions)
2. Open Settings (Cntrl + Alt + ,)
3. Add a new line (e.g. in Application Level Keys `{ "command": "openTabRenamer", "keys": "ctrl+alt+r" },`) 
4. Try to save it 

# Expected behavior

Everything is saved

# Actual behavior

The error appears

`Failed to save 'defaults.json': Command failed: "C:\Users\gudiea\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --file-write "c:\Users\gudiea\AppData\Roaming\Code\code-elevated-pwezjf" "c:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10271.0_x64__8wekyb3d8bbwe\defaults.json" Error using --file-write: EPERM: operation not permitted, open 'c:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10271.0_x64__8wekyb3d8bbwe\defaults.json'`

**Comment by j4james** [comment]
The user settings are opened with <kbd>Ctrl</kbd>+<kbd>,</kbd>. You're opening the _default_ settings, which aren't intended to be editable.

**Comment by ArturGudiev** [comment]
@j4james you are right! Thank you!
