### ISSUE TITLE
Show single wallpaper across split panes, please

### ISSUE THREAD

**Issue by ghaxx** [microsoft/terminal#8968]
I hope it's not too late to change wallpaper engine but it would be nice to see a single image across all split terminal panes. 

Even better would be to configure this behaviour. An image of a forest looks better as a single image for whole terminal. But a texture from Fallout terminal should definitely be duplicated for each split pane.

Perhaps implementation of this could be somehow related to implementation of #6497.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/6028> looks similar.

**Comment by ghaxx** [comment]
It does look similar. Before creating the issue I did a search for possible duplicates. I guess my choice of keywords was poor.
