### ISSUE TITLE
Pixel shader config file

### ISSUE THREAD

**Issue by amoldeshpande** [microsoft/terminal#8971]
I am aware this is looking that gift horse straight in the chompers, but I'd like to see a separate config file for pixel shaders.  

My evil scheme is to extend one of the prompt configuration utilities (like oh-my-posh) to change the shader based on some external state .  I mean, who doesn't want an actual dumpster fire with smoke in the terminal when they're working in the COBOL repo ? 

I can see doing this now by changing the settings file, but it would be nice to be not screw up the entire profile if something goes wrong (race conditions with other things changing the file etc.)

# Proposed technical implementation details (optional)
add a setting like `experimental.pixelShaderStandalonePath`  to a file that contains just a filename (or if you want consistency, a json snippet like the current settings for pixel shaders)

**Comment by zadjii-msft** [comment]
Hmm. This might sound like a crazy idea, but this could be an application for settings fragments (#7632). Like, you have just a single file that's 
```jsonc
{
  "profiles": [
    {
      "extends": "{whatever the guid is for the profile in question}",
      "experimental.pixelShaderPath": "whatever.hlsl"
    }
  ]
}
```

then you could modify just that file, and have the Terminal hot-reload the settings when that file changes.

I guess, this isn't that much better than just modifying the `settings.json` file directly, but at least you could be relatively confident that no one else would be touching that file. 

/cc @PankajBhojwani as an fyi

**Comment by amoldeshpande** [comment]
Sounds good. I didn't much like the idea of a one-off config key myself.

**Comment by zadjii-msft** [comment]
Okay cool. That should be coming in 1.7 (along with docs how to use it)!
