### ISSUE TITLE
Secondary (not main) locales chosen when Terminal opens

### ISSUE THREAD

**Issue by 108adams** [microsoft/terminal#8972]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): any, currently on the latest Pre version  1.6.10272.0

Any other software?
My main system language is Polish. I have also Russian language pack installed (for Russian keyboard). No system area is configured to use Russian as the primary, everything works with Polish locale
```

# Steps to reproduce

# Expected behavior
Opening Terminal provides the menus and all the context either in Polish, or - if not available - in English

# Actual behavior
Terminal is using Russian locales, resulting in Russian entries in all the menus etc. When I start clean and the new JSON gets created, it gets Russian entry for "Command line": "name": "Командная строка",

Terminal assumes Russian locales as main locales, effectively ignoring system-wide settings.

**Comment by zadjii-msft** [comment]
#5497

* Wrong interface language #6029
* Submenus are in a different language. #6594
* Terminal doesn't adhere to the system language setting #6931
