### ISSUE TITLE
dot (.) rendering issue

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#8973]
![bug](https://user-images.githubusercontent.com/71010204/106360969-6a289280-6341-11eb-8d44-c457abaddf85.gif)

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1256]
Windows Terminal version: Windows Terminal Preview v1.6.10272.0

Any other software?: Not applicable
```

# Steps to reproduce
Type dots repeatedly.
Spacing around the dots keeps on changing till the first 4 dots. Afterwards it is fine.

**Comment by j4james** [comment]
The effect you are seeing is the result of font ligatures - when multiple characters are combined to render as a single glyph. If you're using the _Cascadia Code_ font, you can switch to _Cascadia Mono_ for the equivalent style but without the ligatures.

For more information see https://docs.microsoft.com/en-us/windows/terminal/cascadia-code

**Comment by zadjii-msft** [comment]
Yea, this is just how ligatures work. Let us know if you have any other questions!
