### ISSUE TITLE
Text entry closes when using context menu.

### ISSUE THREAD

**Issue by DaMammoth** [microsoft/terminal#8975]
Windows build number: [Version 10.0.19042.746]
Windows Terminal version: 1.5.10271.0 
This isn't a serious issue, but is annoying.
# To reproduce
Open a new tab, then select "rename", on the context menu. Next, enter some text, then press Right Click *or* the context menu button on your keyboard (You may have to highlight text). It will close the context menu without warning. 

# Expected behavior
You should have the ability to open the context menu without it closing.

# Actual behavior
The context menu closes instead of staying open, even though there are "cut", "paste", and "copy" options.

**Comment by Don-Vito** [comment]
Yep - annoying for sure :blush: I will commit a fix later on today.
