### ISSUE TITLE
Documentation Issue - "Build the Code" section

### ISSUE THREAD

**Issue by coderitual** [microsoft/terminal#898]
`/README.md` needs to be updated to show correct path of build tools in `Building the Code` section. Following the current version of instruction the user will get
```
'bcz' is not recognized as an internal or external command, operable program or batch file.
```

Side note: after using `bcz` command from within `tools` folder it looks it is being added to the path for the current session.

**Comment by DHowett-MSFT** [comment]
If you use `.\tools\razzle` from within CMD, `bcz` will be on your path.
If you use it from within PowerShell, don't do that. The `razzle` tool somewhat expects that it's been run from CMD.
There's a (somewhat underdocumented!) PowerShell module @adiviness maintains for building this code.

**Comment by coderitual** [comment]
Thanks @DHowett-MSFT ! Didn't know that. I have run both commands from within `git-bash`. What do you suggest to have this fixed? Maybe a simple comment that `cmd.exe` is recommended would work?

Do you want me to push this PR further and edit according to the comment I received from @oising ?

**Comment by zadjii-msft** [comment]
Yea, I'd change the PR to simply mention that the commands should be called from `cmd.exe`.

**Comment by coderitual** [comment]
@zadjii-msft @DHowett-MSFT Done.
