### ISSUE TITLE
Long ssh/docker sessions result in strange behavior.

### ISSUE THREAD

**Issue by StoneyEagle** [microsoft/terminal#8980]
# Environment

```none
Windows build number: Win32NT 10.0.21296.0 Microsoft Windows NT 10.0.21296.0 
Windows Terminal version: 1.5.10271.0

Any other software?
Docker 3.1.0
```

# Steps to reproduce
Have a long (1+ hours) SSH session that's killed by the remote host or docker exec session that's killed by the docker daemon.

# Expected behavior
Screen is cleared with only the username and path showing.

# Actual behavior
After a long session gets terminated by the server or docker container the windows terminal is bugged with lots of strange behavior like adding characters when clicking the mouse.
![image](https://user-images.githubusercontent.com/45034970/106394829-f220a200-63fe-11eb-8cbf-bd6cd288aa86.png)
Or when running a commando on the remote host that outputs many lines of code, the background color changes to blue after the outputted text.
The longer the session the stranger the behavior. Sounds like a memory leak.

**Comment by zadjii-msft** [comment]
Those sequences of characters that are emitted when clicking the mouse seem to indicate that the remote server requested mouse input mode, but didn't reset the mode when connection was exited. This is something that happens from time to time, ESPECIALLY when an application like `ssh` or `docker` forcefully terminates the connection. When the connection is terminated forcefully, the remote app doesn't have a chance to reset the terminal modes itself. Then, when control returns to `bash` or whatever you're running locally, `bash` doesn't know that the remote app left the modes polluted. It doesn't know to reset the modes manually. 

I believe `reset` _should_ set these modes back to the default.

**Comment by StoneyEagle** [comment]
Yeah i let myself go on the mouse haha.
I never had this issue with putty before, it's a minor annoyance but you can't fix what you don't know that's broken.
Restarting the application fixes the issue. How do i reset the program without killing other tabs?

**Comment by zadjii-msft** [comment]
I'm pretty sure the linux command `reset` should cover it - lemme know if it doesn't.

**Comment by StoneyEagle** [comment]
Sure thing.

**Comment by DHowett** [comment]
> How do i reset the program without killing other tabs?

You can also just close the broken pane/tab without exiting the entire Terminal. :smile:

**Comment by StoneyEagle** [comment]
Now i got permission to crash stuff.... it takes forever lol
The reset command does not reset the mouse input.

**Comment by DHowett** [comment]
Just a quick question- what SSH client are you using here? Is it the one that comes with Windows, or one inside WSL? Is the docker client the Windows one?

**Comment by StoneyEagle** [comment]
I installed it from the MS store when you needed to run the insiders build to get it, so im not sure on that. 
Long and sad story short I run a fresh copy of Windows 10 pro (retail) now and i haven't installed Docker on it yet.
The issue only happened to me once or twice with an external Docker server on Ubuntu 20.04 since then.
When it happens the arrow keys give me an audible error and weird characters typed out, typing any command and executing it seems to fix the issue.

**Comment by zadjii-msft** [comment]
Huh, you know what, this is actually the same underlying issue as /dup #8613
