### ISSUE TITLE
file:// URLS not supported

### ISSUE THREAD

**Issue by derSchtefan** [microsoft/terminal#8981]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable):  1.5.10271.0
```

# Steps to reproduce
Construct a file:// URL like referenced here:
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#file-uris-and-the-hostname
Which is referenced here: 
https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-4-release/#hyperlink-support
Like this: (WSL)
printf '\e]8;;file://'`hostname`'/C:\\temp\e\\This is a link\e]8;;\e\\\n'

And CTRL+Click on it.

# Expected behavior
The folder referenced (in this case C:\Temp) opens. 

# Actual behavior
Error message: This link type is currently not supported:
file://derRyzen/C:\temp

# Comment
This is sad, it would enable amazing ls integration (via scripting) and make workflows so much easer. Also the working directory in your prompt would become clickable.

**Comment by j4james** [comment]
See issue #7699.

**Comment by zadjii-msft** [comment]
Thanks for the help triaging!

/dup #7699
