### ISSUE TITLE
Settings UI incompatible with keybindings

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#8987]
# Environment

```none
Windows build number: 10.0.19042.746
Windows Terminal version (if applicable): 1.6.10272.0
```

# Steps to reproduce

Multiple ways. Open the Settings UI tab using your keybind (like Ctrl+Shift+,). Now use other keybindings, like `toggleFocusMode` (Shift+F11), or Command Pallete (Ctrl+Shift+P), or JSON file (Ctrl+,), or new tab (Ctrl+Shift+T). 

# Expected behavior

They should open their respective actions, like any other tab.

# Actual behavior

None of these commands seem to work. 
Nothing happens.

## Context

I have set my `launchmode` to `focus`, so each WT sessions opens in focus mode. But when I open the Settings UI from there, I get stuck on that tab, because the toggleFocusMode keybind does not do anything, and I can't even open a new tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8767 for more discussion.

/dup #8767
