### ISSUE TITLE
Terminal just crashed when renaming tab

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/terminal#8988]
I raised a feedback hub report which I labelled with "20d02aa3-09d9-4c5b-8ede-f7057e42d5f3" for searchability.

Terminal Preview (1.6.10272.0) just crashed on me when attempting to rename a tab.

I had 5 powershell tabs open
Each of these had already been renamed and recolored but right clicking on the tab header.

I opened another tab and right clicked to change the color (this succeeded)
Immediately afterwards I right clicked to change the name.  The new-name edit box did not appear.  After a couple of seconds the entire terminal crashed and disappeared.

**Comment by NeilMacMullen** [comment]
I have been trying to reproduce this without success so far.  If I find a good recipe I'll post it here.

**Comment by zadjii-msft** [comment]
By any chance, did you hover over the "Close..." option while trying to open the tab renamer? That menu flyout pretty consistently crashes the Terminal :(

**Comment by NeilMacMullen** [comment]
You mean close for the tab rather than close for the whole terminal?

It's certainly _possible_ I did either by accident - the tabs would have been quite narrow and close to the right hand side of the title bar by this stage.  I still haven't been able to reproduce it though, even with deliberately heading for the close icon!

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/106488517-67c95400-6479-11eb-9933-51f2c609d9b6.png)


^ This boy right here. There's a bug in XAML islands with nested menu flyouts that ends up crashing the app. We're tracking that in #8238 (et al)

**Comment by NeilMacMullen** [comment]
Yes - I think it must be a dup of that.  I can crash it every time now just by opening the menu and moving the mouse up and down over and past the the Close option. I suspect I did this accidentally on the original bug report by "overshooting" the rename tab option.  I'll close this one.

**Comment by zadjii-msft** [comment]
No worries, just glad there's not a _new_ crash to worry about 😅

**Comment by NeilMacMullen** [comment]
Always nice when there's just one root cause ;-)
