### ISSUE TITLE
Error when launching via context menu from folder background

### ISSUE THREAD

**Issue by timonsku** [microsoft/terminal#8990]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1316]
Windows Terminal version (if applicable): Preview from Store - Version: 1.6.10272.0
```

# Steps to reproduce
Right click in the background of a folder and click open Terminal (e.g. this fixed regression https://github.com/microsoft/terminal/issues/6414 )
This worked once after installing the update and restating explorer. After a subsequent restart the below error started to happen. It still works fine when I open by right clicking a folder instead of the background within that folder.

# Expected behavior
Terminal opens with path set to the current folder

# Actual behavior
This error pops up
![image](https://user-images.githubusercontent.com/2370185/106470018-50519180-64a0-11eb-877d-12800022a69a.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #8936 for more discussion.

/dup #8936
