### ISSUE TITLE
Simplified Chinese translation issue: "丙烯酸" should be replaced with "亚克力"

### ISSUE THREAD

**Issue by KenwayDai** [microsoft/terminal#8992]
I've tried latest Windows terminal in Simplified Chinese. It works well but I've found a following translation issue. 

![1](https://user-images.githubusercontent.com/12065395/106480070-f5428d80-64e5-11eb-8755-e78c4188f2ff.png)

# Environment

```none
Windows build number: 10.0.19042.746
Windows Terminal version: 1.6.10272.0
```

# Steps to reproduce

1. Open Settings UI
2. Switch to "Profiles"-"Base Layer"-"Appearance"
3. Scroll down. 
 
Then you will find the inappropriate translation of "Acrylic", which is translated as "丙烯酸". 
In addition to the "Base Layer" setting page, there is also this error in the setting pages of other types of terminals. Such as cmd, Windows PowerShell, etc. 

# Expected behavior & Actual behavior
"丙烯酸" should be replaced with "亚克力". In the context of Simplified Chinese, if "Acrylic" means an UI effect, it should be translated as "亚克力"(or "亚克力效果"), which will be more appropriately.

**Comment by skyline75489** [comment]
Yeah I agree. Also the translation of "Base Layer" is strange to me. It should be "基本层” instead of "基本图层"。 The name "基本图层“ is more commonly seen in photo editing apps.

**Comment by lhecker** [comment]
I don't speak Chinese, but I believe this issue has been fixed in the latest Preview version, which shows:
![image](https://user-images.githubusercontent.com/2256941/123163245-c9fb1380-d471-11eb-8ef1-c88263c93be8.png)

@KenwayDai @skyline75489 Can either of you confirm whether the above is correctly translated?

**Comment by skyline75489** [comment]
Yes. This is fixed as in 9328
