### ISSUE TITLE
"start" command should reuse Terminal window

### ISSUE THREAD

**Issue by asklar** [microsoft/terminal#8996]
- run cmd in Terminal
- `start myCommand.cmd` to start the command in a new "window"
## Expected
new tab in Terminal
## Actual
will start a cmd instance in a new conhost window, separate from the Terminal window it started in.

**Comment by DHowett** [comment]
@asklar good news! We're working on this in the _extremely near future_ windows build timeframe. Can't say more than that here on github. :smile:
