### ISSUE TITLE
tab title unreadable with chinese

### ISSUE THREAD

**Issue by gateslu** [microsoft/terminal#8998]
![image](https://user-images.githubusercontent.com/1697700/106563349-9bce7300-6566-11eb-8d8d-6aed209ae885.png)

this is my settings.json

{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{c453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
            //"scrollbarState":"hidden",
            //"padding" : "10, 10, 10, 10",
            "acrylicOpacity" : 0.9,
            "background" : "#000",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Cascadia Code",
            "fontSize" : 14,
            "useAcrylic": false,
            //"startingDirectory": "L:\\work\\terminal",
            "startingDirectory": ".",
            "backgroundImage":"C:\\Users\\xxx\\Pictures\\slogan-logo.png",
            "backgroundImageAlignment": "bottomRight",
            "backgroundImageOpacity" : 0.12,
            "backgroundImageStretchMode" : "none"
        },
        "list":
        [
            {
                "guid": "{c453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "msys2 64",
                "commandline": "C:\\msys64\\msys2_shell.cmd -mingw64 -msys -defterm -no-start -here",
                "icon": "C:\\msys64\\msys2.ico",
                "startingDirectory": null
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b7}",
                "hidden": false,
                "name": "git bash",
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "icon": "C:\\Users\\xxx\\Pictures\\git.png"
            },
            {
                // Make changes here to the powershell.exe profile
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    "schemes": [],
    "keybindings": []
}

**Comment by skyline75489** [comment]
I can't reproduce this on my system. What version of git are you using? Do you have the experimental winconpty feature enabled?

**Comment by zadjii-msft** [comment]
Hey we've seen this once before, in #7172. What version of `git` / the msys runtime are you using? Looks like you might need to update
