### ISSUE TITLE
Cyrilic font issue in ohmyzsh

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#90]
_From @casufi on July 1, 2017 14:12_

I set Zsh as my default shell for bash for Windows after that I installed "oh my zsh" as default theme for Zsh https://github.com/robbyrussell/oh-my-zsh
I am using default theme "rubyshell" for command prompt  but I have some issue with the unicode characters and me unable to set "Ubuntu" as default font for the bash for windows

![bash](https://user-images.githubusercontent.com/9831298/27762745-7b16015a-5e80-11e7-9bd8-e34e875c8720.png)

https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme

_Copied from original issue: Microsoft/WSL#2275_

**Comment by bitcrazed** [comment]
_From @fpqc on July 3, 2017 2:44_

You can't use opentype fonts in conhost right now.

**Comment by bitcrazed** [comment]
_From @SummerSad on July 12, 2017 2:9_

You can change the default font in CMD with fonts here https://github.com/powerline/fonts

**Comment by TheSolly** [comment]
Having the same issue, i did install couple of fonts from https://github.com/powerline/fonts
Still the same issue, icons and glyohs in zsh theme doesnt show properly on Ubuntu bash...

Any fix for this?!

**Comment by bitcrazed** [comment]
We've some interrelated explorations going on right now, but nothing to announce at this time.

**Comment by miniksa** [comment]
This is probably going to be resolved with the font fallback support of the DX renderer in Terminal, but leaving open to verify.

**Comment by zadjii-msft** [comment]
Hey I know this issue is like, 4 years old now, but @casufi - does this work in the Windows Terminal now? can you set the font you were looking for and get the right powerline characters?

**Comment by casufi** [comment]
Hello @zadjii-msft I am using https://github.com/powerline/fonts/tree/master/DejaVuSansMono font and everything is working fine
