### ISSUE TITLE
"copyOnSelect": true - not working?

### ISSUE THREAD

**Issue by cusco** [microsoft/terminal#9003]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): (latest just re installed with winget)

Any other software?
WSL
```

# Steps to reproduce

select text, requires right click to copy, instead of copying on selection. Would like to right click once only to paste.
If I select text, then press escape, text is not copied.

# Expected behavior
Right click once should be pasting instead of copying and requiring a second right-click.

# Actual behavior
Right-clicking while text is selected will copy.. where it should have been copied on select, and right-click should paste instead.

**Comment by WSLUser** [comment]
The latest is now 1.6 preview. Winget takes a few days to get it updated once an updated manifest is provided. Please specify the version you are running. Incidentally it that setting workings just fine for me. If you are on 1.6 preview, did you open the Settings UI first? There's a slightly different setting name that appears to encompass more than one of the normal settings such as `copyonSelect.`

**Comment by zadjii-msft** [comment]
Yea, the specific version would be helpful. You can find this with the command `wt -v` (it'll open a message box)

**Comment by cusco** [comment]
Hello @WSLUser and @zadjii-msft 

Thank you kindly for your replies. Running wt -v shows that the version I have is: `1.5.10271.0`.
This probably means this feature is not yet available right?

If the 1.6 preview will be available in a week or so, I will wait and update. 
If it is longer I will find how to update another way..

This sounds something simple but is a big habit. I I change my habit here, I will break my own usage of other apps :/

Thank you for your replies, and sorry for this non-issue report.

**Comment by DHowett** [comment]
> Winget takes a few days to get it updated once an updated manifest is provided.

as an aside: winget does not automatically update packages.

**Comment by DHowett** [comment]
This is curious. `copyOnSelect` has been around since 0.3 or 0.4. You should not need a new version to get it working.

Would you mind sharing a copy of your `settings.json` file? You can upload it to [GitHub's gist service](https://gist.github.com)

**Comment by cusco** [comment]
> This is curious. `copyOnSelect` has been around since 0.3 or 0.4. You should not need a new version to get it working.
> 
> Would you mind sharing a copy of your `settings.json` file? You can upload it to [GitHub's gist service](https://gist.github.com)

yes: https://gist.github.com/cusco/722d792887dee00daf354d9143a28578

**Comment by cusco** [comment]
> > This is curious. `copyOnSelect` has been around since 0.3 or 0.4. You should not need a new version to get it working.
> > Would you mind sharing a copy of your `settings.json` file? You can upload it to [GitHub's gist service](https://gist.github.com)
> 
> yes: https://gist.github.com/cusco/722d792887dee00daf354d9143a28578

Upon reading my own settings.json I found the same option being set to false bellow. I don't know how this escaped me before, I'm pretty sure I used search in notepad before before adding the option...


I'm so sorry to waste your attention on this! It works as intended !

Thank you once more!

**Comment by zadjii-msft** [comment]
No worries, glad you figured it out (and that we didn't somehow regress this 😜)
