### ISSUE TITLE
Feature Request: Add support for profile grouping

### ISSUE THREAD

**Issue by jwbreedlove** [microsoft/terminal#9005]
Adding support for profile grouping would help when navigating to specific profiles that don't have a shortcut enabled. For example, I have over 40 profiles for various linux distributions and ssh connections to VMs/servers. My most frequently used profiles have a shortcut but the other profiles reside in a long list in the profile dropdown making the specific profile I need hard to identify. Grouping or a similar feature would help tidy the dropdown list!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+group+profile+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1571 for more discussion.

/dup #1571
