### ISSUE TITLE
If tab title updates when terminal window isn't in focus, Terminal Title doesn't update in taskbar

### ISSUE THREAD

**Issue by sarim** [microsoft/terminal#9007]
# Environment

```none
Windows build number: Version 10.0.19042.746
Windows Terminal version (if applicable):   Windows Terminal Preview Version: 1.6.10272.0
```

# Steps to reproduce

can be reproduced in both wsl or in powershell. 
1. run this and then switch to another application
    ```
    sleep 5; cd .\Documents\
    ```
2. after 5 secs, tab title will be updated, but title in taskbar won't.

# Expected behavior

title in taskbar updates properly even when terminal is not in focus.

Here's two screenshot:
![image](https://user-images.githubusercontent.com/1235888/106647066-aade1100-65b8-11eb-9215-e555fdafc6b1.png)
![image](https://user-images.githubusercontent.com/1235888/106647083-b03b5b80-65b8-11eb-83bb-dc3716701022.png)

# Actual behavior

title in taskbar stays old value when terrminal is not in focus.

**Comment by zadjii-msft** [comment]
_huh_. Good catch!

**Comment by DHowett** [comment]
This seems like another shade of #8704, actually. I wonder what happened.

**Comment by DHowett** [comment]
/dup #8704 

I'm going to make this the master issue for fixing title propagation issues.
