### ISSUE TITLE
Saving changes in Settings UI changes Precision for Decimal Values in settings.json

### ISSUE THREAD

**Issue by ShubhamBelwal** [microsoft/terminal#9008]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.746]
Windows Terminal version (if applicable): Windows Terminal Preview v1.6.10272.0

Any other software? NA
```

# Steps to reproduce

1. Note decimal values for fields `acrylicOpacity` & `backgroundImageOpacity`
2. Open Settings UI, make some change & click on Save
3. Observe that precision for the values  have changed.

# Expected behavior
The precision for the decimal values should not change

# Actual behavior

Values now have precision of 17 digits instead of 2.

Before:
![image](https://user-images.githubusercontent.com/36201797/106646359-a8c58380-65b3-11eb-9321-9b13fddc8fb8.png)

After:
![image](https://user-images.githubusercontent.com/36201797/106646301-96e3e080-65b3-11eb-84d5-e329c573d243.png)

**Comment by DHowett** [comment]
So, this is only half correct. The precision _isn't changing_, it's just being exposed to you. IEEE954 rules!

**Comment by zadjii-msft** [comment]
Should we just include this with #8991 for ""settings UI reformats my file?

**Comment by DHowett** [comment]
Yes, that would be good.
