### ISSUE TITLE
Error 0x87E10BC6 when attempting to run the app

### ISSUE THREAD

**Issue by asajadi84** [microsoft/terminal#9009]
Hey there. I downloaded the msixbundle file from the repo release page but when I try to launch the app it gives me the following error:
`Something happened on our end. Here’s the error code, in case you need it: 0x87E10BC6`

**Comment by DHowett** [comment]
If you are doing a fully offline install on a machine that cannot reach the Microsoft Store, you must use the preinstall kit. The preinstall kit comes with a license document that you can install with DISM.

**Comment by showintime** [comment]
> If you are doing a fully offline install on a machine that cannot reach the Microspreinsoft Store, you must use the preinstall kit. The preinstall kit comes with a license document that you can install with DISM.

what is `preinstall kit`?

**Comment by KalleOlaviNiemitalo** [comment]
@showintime , there are preinstallation kits downloadable from GitHub releases, e.g. <https://github.com/microsoft/terminal/releases/tag/v1.6.10571.0>, which also has links to documentation about preinstallation.
