### ISSUE TITLE
Custom emoji sets are not properly displayed

### ISSUE THREAD

**Issue by SCOTT0852** [microsoft/terminal#9016]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce

1. Replace the emoji in the system fonts with another set (in this case, done with https://github.com/eosrei/twemoji-color-font/)
2. Attempt to display an emoji in the terminal.

# Expected behavior

The emoji should be properly rendered like in other applications.
Example screenshot from the built-in Windows emoji picker:

![image](https://user-images.githubusercontent.com/33875157/106690260-56ba3900-6586-11eb-8d8b-34b6ce7aa94f.png)

# Actual behavior

The emoji just shows as a "missing character" box.
Screenshot with ~~Terminal-Icons (places appropriate emojis to the left of file names) and~~ (edit: turns out those aren't actually emojis) an administrator Powershell (places ⚡ to the left of the command line):

![image](https://user-images.githubusercontent.com/33875157/106690191-38543d80-6586-11eb-8251-b0868094387e.png)

**Comment by DHowett** [comment]
Replacing a system font, you’re already in unsupported territory. Still, we should support SVG fonts.

**Comment by DHowett** [comment]
Actually... What are those emoji supposed to be next to the filenames? I think they’re supposed to be NerdFont characters, _not_ emoji.

**Comment by SCOTT0852** [comment]
I wasn't aware that NerdFont characters were used for terminal-icons, but I know the top left ⚡ is definitely an emoji because it used to display properly. And yeah, I'm not a fan of having to patch system fonts, but unfortunately there isn't a better way to do emoji set replacement.

**Comment by DHowett** [comment]
Would you mind dumping the charcter code for that lightning bolt? Copy it to your clipboard (directly out of Terminal) and run `[int]((Get-Clipboard)[0])` (PowerShell 6+)

**Comment by SCOTT0852** [comment]
I don't have PS 6, but running it in 5.1.19041.610 gives the output 61671.

**Comment by DHowett** [comment]
Sorry, that's another codepoint in the private use range (which NerdFonts uses to add all these fun glyphs.)

**Comment by DHowett** [comment]
Best choice is gonna be to find a nerdfont version of the font you're using or the font you like -- it'll look a lot better!

**Comment by SCOTT0852** [comment]
...then why did it work before? I was just using the default font. Guess I have more troubleshooting to do...
