### ISSUE TITLE
Explorer.EXE Server Execution Failed on Open in Windows Terminal in the Background of the Folder With Chinese Windows Username

### ISSUE THREAD

**Issue by 2540825244** [microsoft/terminal#9019]
# Environment

```none
Windows build number: 10.0.18363.1316
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce

1. Have a Chinese Username (That is, the folder in C:\User is in Chinese and I've tested account with non Chinese user folder but with the same Microsoft account and it is okay)
2. Go in any folder in explorer and open the context menu in the backround
3. Select "Open in Windows Terminal"

# Expected behavior

A windows terminal prompt open with the directory as the current directory in explorer
![Desktop Screenshot 2021 02 03 - 11 36 50 59](https://user-images.githubusercontent.com/23135859/106727519-3df86480-6614-11eb-9d56-9e174d2a1304.png)
(note that this screenshot is taken on another laptop with higher version of Windows so I cannot test if version actually affects the problem)

# Actual behavior

A prompt opens and displays a server execution failed error
![2021-02-03 (2)](https://user-images.githubusercontent.com/23135859/106727700-67b18b80-6614-11eb-9d6c-0d6c9a646660.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that was being tracked in #8936, and was fixed in #8977. Thanks!

/dup #8936
