### ISSUE TITLE
Failed to Compile  

### ISSUE THREAD

**Issue by davidbuckleyni** [microsoft/terminal#902]
Failed to compile 
14>e:\work#\terminal-master\src\inc\libraryincludes.h(48): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
12>e:\work#\terminal-master\src\inc\libraryincludes.h(48): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
11>e:\work#\terminal-master\src\inc\libraryincludes.h(48): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
14>Done building project "win32.LIB.vcxproj" -- FAILED.
12>Done building project "InteractivityBase.vcxproj" -- FAILED.
11>Done building project "tsf.vcxproj" -- FAILED.
17>e:\work#\terminal-master\src\inc\libraryincludes.h(48): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
16>e:\work#\terminal-master\src\inc\libraryincludes.h(48): fatal error C1083: Cannot open include file: 'wil/Common.h': No such file or directory
17>Done building project "terminalinput.vcxproj" -- FAILED.
19>------ Build started: Project: TerminalAdapter, Configuration: Debug x64 ------
16>Done building project "parser.vcxproj" -- FAILED.
20>------ Build started: Project: TerminalCore, Configuration: Debug x64 ------
19>precomp.cpp
20>pch.cpp

**Comment by zadjii-msft** [comment]
My guess is that you didn't [read the README](https://github.com/microsoft/terminal#building-the-code).

>This repository uses git submodules for some of its dependencies. To make sure submodules are restored or updated, be sure to run the following prior to building:
> ```
> git submodule update --init --recursive
> ```
