### ISSUE TITLE
Putty/Kitty integration?

### ISSUE THREAD

**Issue by Conan179** [microsoft/terminal#9020]
Hello everybody.

I personally work a lot with Putty and the fork kitty.
I just had the idea whether it would be possible to open a tab from the Windows Terminal, where you can then run a Putty / Kitty instance, by which I do not mean that the Putty / Kitty is programmed into the terminal, but one kind of external call and then the terminal is only used as a display.

Would that even be possible?

Greetings Conan

**Comment by zadjii-msft** [comment]
So, you want to embed a kitty instance _inside_ a Windows Terminal window? May I ask _why_? Is there some feature in particular you're looking for?

**Comment by Conan179** [comment]
Why not?
I am currently working with ubuntu on wsl2, then I would like to do that on my ubuntu server too, click the down arrow, open a new tab, Putty appears, I select my server and can then switch between the tabs.
It just happened to me when I was working on my Linux.

**Comment by zadjii-msft** [comment]
Okay, I don't know why you'd need putty for that though. If you're accessing your server via ssh, you could just create a new profile with a commandline like:
```json
"commandline": "ssh username@myserver.com"
```

and access the server that way. There would likely be other flags and configurations that you'd want to pass in that commandline, but the principle should remain the same. I'm not sure why we'd need to get putty (a whole terminal emulator) involved here.

**Comment by Conan179** [comment]
I close this, there is want an interest in my idea.

**Comment by zadjii-msft** [comment]
Alrighty then. Lemme know if you need any help getting that set up!
