### ISSUE TITLE
Mouse isn't working in CLI text editors

### ISSUE THREAD

**Issue by EmiSan1998** [microsoft/terminal#9022]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.5.10271.0 and 1.6.10272.0

Any other software? No
```

# Steps to reproduce

1. Run a CLI text editor from Powershell or CMD on Windows terminal
2. Insert some line of text
3. Try to scroll or highlight text

# Expected behavior
The text scrolls or is properly highlighted

# Actual behavior
The text doesn't scroll or isn't properly highlighted (the line numbers are highlighted with the texts)

Here there's a comparation between Windows Terminal (where mouse doesn't work) and the Windows built-in terminal emulator (which behaves as I expect)
![image](https://user-images.githubusercontent.com/23716404/106762212-e79c1d80-6635-11eb-98eb-803f0e665e5f.png)

**Comment by zadjii-msft** [comment]
> Run a CLI text editor 

Which text editor would that be specifically?

**Comment by EmiSan1998** [comment]
> > Run a CLI text editor
> 
> Which text editor would that be specifically?

I tried Vim with
`set mouse=a`
and “micro”
https://github.com/zyedidia/micro

**Comment by DHowett** [comment]
Okay, are you using them under WSL? Windows native? through SSH? Through WSL + SSH?

**Comment by EmiSan1998** [comment]
> 
> 
> Okay, are you using them under WSL? Windows native? through SSH? Through WSL + SSH?

I'm using them under Windows native (PowerShell 7)

**Comment by zadjii-msft** [comment]
Thanks for clarifying! What you're seeing boils down to the terminal not supporting win32-style mouse input quite yet. That's being tracked over in #376. Thanks!

/dup #376
