### ISSUE TITLE
Tab or Pane not closing

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#9027]
# Environment

Windows Terminal Preview: Version: 1.6.10272.0 installed from Microsoft Store.
Any other software running in terminal.

# Steps to reproduce

For example, you run pwsh.exe and cmd.exe in different tabs/panes and want to kill cmd.exe from pwsh.exe:
```
Get-Process cmd | Stop-Process # or
(Get-Process cmd).kill()  #or
taskkill /im cmd.exe /f 
```
The panel or tab where the cmd.exe was launched does not close after it is killed. This applies to any application and to any method of closing it. Even from the Task Manager.

#Expected behavior

The tab or panel must close when the application is stopped.

# Actual behavior

The tab or the pane does not close if you close an application running in it from another one.
![ss-20210204014424](https://user-images.githubusercontent.com/78153320/106819265-966a4900-668a-11eb-9fbb-b99b8f216c89.png)

**Comment by DHowett** [comment]
Set `closeOnExit` to `always`. This is working as intended: _cmd effectively crashed_, so Terminal leaves the pane open so you can see what happened.

**Comment by DHowett** [comment]
`closeOnExit` dictates when panes are automatically destroyed :smile:

**Comment by 237dmitry** [comment]
Thanks! Strange, but I passed by this option.
