### ISSUE TITLE
Pane Focus should be moved with respect to natural positions rather than how they were created

### ISSUE THREAD

**Issue by arvindsree** [microsoft/terminal#9029]
# Description of the new feature/enhancement

The window is split into four panes using Alt+Shift+D.
Lets name the tabs with respect to their position
A B 
C D

This is created by spliting the main window vertically to AC and BD. Then splitting BD and AC horizontally
![image](https://user-images.githubusercontent.com/21178759/106835583-6f8d2200-664c-11eb-9275-8ea13e8324b6.png)

The issue is that 
- when we move focus right from pane C, the focus goes to pane B rather than pane D.
- when we move focus left from pane D, the focus goes to pane A rather than pane C.

The same issue is observed when we move focus up/down if the main window was split horizontally first

# Proposed technical implementation details
- when we move focus right from pane C, the focus should go to pane D
- when we move focus left from pane D, the focus should go to pane C
- If there is no pane exactly to the left/right/top/down it should go to the closest/recently visited one rather than going to the pane it was split from

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2398 for more discussion.

/dup #2398
