### ISSUE TITLE
Set the startingDirectory of WSL2 Kali Linux to ‘/’, not starting with root directory but ‘/mnt/c’

### ISSUE THREAD

**Issue by dokcn** [microsoft/terminal#9030]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10272.0
```

# Steps to reproduce

Set the startingDirectory of WSL2 Kali Linux to ‘/’

# Expected behavior

Starting with root directory

# Actual behavior

Starting with  ‘/mnt/c’ directory

***
![Snipaste_2021-02-04_10-25-58](https://user-images.githubusercontent.com/24841978/106836075-6e530800-66d3-11eb-89c3-2a3298446e4d.png)
***
![Snipaste_2021-02-04_10-26-15](https://user-images.githubusercontent.com/24841978/106836082-714df880-66d3-11eb-940d-5faf7cc3adff.png)

**Comment by skyline75489** [comment]
You cannot directly use a Linux path here. You'll need to use UNC path. See https://github.com/microsoft/terminal/issues/5377#issuecomment-614724488

**Comment by dokcn** [comment]
@skyline75489 thanks

**Comment by dokcn** [comment]
memo: type '\\wsl$' in address bar of explorer or type 'wsl -l' in powershell you can find your linux distro name, then set startingDirectory to '\\\\wsl$\\{your linux distro name}'(escape needed), start directory will be root directory.
