### ISSUE TITLE
Terminal crashes when settings.json has an unnamed "scheme".

### ISSUE THREAD

**Issue by danrozenberg** [microsoft/terminal#9033]
# Environment

Microsoft Windows [Version 10.0.18363.1316]

# Steps to reproduce

I had a `settings.json` file generated, then modified by Windows Terminal `1.5.10271.0`
After updating to latest, Terminal would open and instantly crash.

Upon resetting the json and experimenting, it turns out that the culprit was the following element of my `schemes` array:

`{"colorScheme": "Solarized Dark"}`

Further inspection leads me to believe that Windows terminal will crash as long as there is any element in the `schemes` array _without_ a name. Thus, the scheme 

`` 	{			
	"name": "So Dark",
	"colorScheme": "Solarized Dark"			
	}
``

does not make the application crash.

# Expected behavior

Terminal should open and function normally, and/or complain about any incorrect configurations in `settings.json` (for example "a scheme must have a name").

# Actual behavior

Terminal simply crashes after loading the json. Subsequent attempts to open Terminal fail since it keeps trying to use the afflicted `settings.json`

**Comment by Don-Vito** [comment]
@danrozenberg - I guess this can be related to https://github.com/microsoft/terminal/issues/8986, which was fixed two days ago and was not released yet.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #8986 for more discussion.

/dup #8986
