### ISSUE TITLE
Unable to input Chinese punctuation and Emoji

### ISSUE THREAD

**Issue by xieang123** [microsoft/terminal#9035]
# Environment

```none
Windows build number: 19042.746
Windows Terminal version: 1.6.10272.0

```

# Steps to reproduce

Use Windows Terminal, config commandline or input command 'ssh name@IP',unable to input Chinese punctuation,but WSL/CMD/PowerShell no problem

This is ssh,unable to input Chinese punctuation and Emoji,but can input Chinese words.
![ssh](https://user-images.githubusercontent.com/70886372/106855672-475afd00-66f8-11eb-9347-ea1c107c7645.png)

This is wsl,can input Chinese punctuation/Chinese words/Emoji.
![wsl](https://user-images.githubusercontent.com/70886372/106855667-45913980-66f8-11eb-9811-c2f4dd16161f.png)

This is PowerShell ,can input Chinese punctuation/Chinese words.
![PowerShell ](https://user-images.githubusercontent.com/70886372/106855671-46c26680-66f8-11eb-9488-6437bf18a6e1.png)

## more
On the CMD client/PowerShell client/Git Bash use ssh,can input Chinese punctuation/Chinese words.

![PowerShell client](https://user-images.githubusercontent.com/70886372/106857328-dec14f80-66fa-11eb-8650-be502905e9eb.png)

# Expected behavior

Can input Chinese punctuation

# Actual behavior

Unable to input Chinese punctuation

**Comment by skyline75489** [comment]
I think this is one of those issues that are caused by [openSSH-portable](https://github.com/PowerShell/openssh-portable).

**Comment by xieang123** [comment]
> I'm using 19042.746 and I can confirm this issue.
> 
> I think this is one of those issues that are caused by [openssh-portable](https://github.com/PowerShell/openssh-portable).

Thinks!You are right. After  ssh upgraded, the problem was solved.
But I don't know why the CMD client/PowerShell client/Git Bash doesn't have a problem
