### ISSUE TITLE
Delete whole words by pressing Ctrl+Backspace

### ISSUE THREAD

**Issue by xerosugar** [microsoft/terminal#9037]
# Description of the new feature/enhancement
In Windows you can usually delete whole words by pressing Ctrl and then Backspace. I would like to be able to do this in Windows Terminal.

# Proposed technical implementation details (optional)
The point of this feature is simply to able to delete text faster. Maybe you pasted something in the terminal but you need to change the path to some file you're working with, and instead of holding your finger on the Backspace button you can just press Ctrl+Backspace a few times.

# A clear and concise description of what you want to happen.
To delete whole words when pressing Ctrl+Backspace, but stop deleting at: '.', ',', '-' or other special characters. Maybe a setting somewhere could dictate what characters to stop deleting at?

**Comment by zadjii-msft** [comment]
This absolutely works today - what shell are you using? `cmd`, `powershell`, `bash`...? Are you using `ssh` or something else in the middle?

**Comment by xerosugar** [comment]
Hm, it stops working when I'm using `ssh`... but now I noticed that it does indeed work in `powershell` when I'm not using `ssh`.

**Comment by zadjii-msft** [comment]
Yep, that'll do it. Looks like this is [a known issue with ssh.exe](https://github.com/PowerShell/Win32-OpenSSH/issues?q=is%3Aissue+ctrl%2Bbackspace+is%3Aclosed).

**Comment by hossam43** [comment]
control + backspace works in both `powershell `and `cmd `and for `bash `use control  + w
