### ISSUE TITLE
Drag and drop from File Explorer should put full path at cursor location in Windows Terminal

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#904]
# Summary of the new feature/enhancement

Drag and drop of file or folder from File Explorer should behave the same way that it does in conhost.  Conhost will add the text of the full path of the item dropped at the current cursor location.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
Ref. #331 for linking purposes.
Thanks!

**Comment by RobertBernstein** [comment]
I'm just wondering if there's any update on when this will be enabled.  I saw that there are issues with capturing path information under WSL, but will this be implemented for cmd.exe and/or PowerShell anytime soon?  Thanks!

**Comment by zadjii-msft** [comment]
@RobertBernstein At the time of writing, this particular feature hasn't had any progress. It's still sitting on our backlog - it's something that we want to do, but we unfortunately don't think we'll be able to get to before the 1.0 release of the Terminal. We'd be happy to accept a community contribution for this feature! 

There's code in `Window::_HandleDrop` in the conhost code in this repo that already handles a `WM_DROPFILES` message, it shouldn't be _too_ hard to add a similar listener to the `IslandWindow` class that writes the path to the input of the `TerminalApp`.

**Comment by jingyu9575** [comment]
Hi, I've downloaded today's CI build to try this new feature. It sometimes works but randomly stops working. Strangely, the success rate has a noticeable increase if `initialCols <= 63`:

![rDrkDxyqkU](https://user-images.githubusercontent.com/8923139/73556268-62dd5900-444f-11ea-8c8d-85449f6eb420.gif)

Also, some area is not available for dropping, which I suspect to be related with the DPI scaling (I use 150%).

![xuNyAiIRSd](https://user-images.githubusercontent.com/8923139/73556567-f747bb80-444f-11ea-98e4-51f8114e1162.gif)

Thank you!

**Comment by SJang1** [comment]
@jingyu9575 Maybe opening a new issue?

**Comment by jingyu9575** [comment]
@SJang1 In today's release, I cannot reproduce the first problem, but the second one is still not fixed. I've opened a new issue #4567.
