### ISSUE TITLE
Pattern highlight

### ISSUE THREAD

**Issue by horseinthesky** [microsoft/terminal#9040]
# Description of the new feature/enhancement
iTerm2 has really nice feature - pattern highlighting. You can use complex regexp's to match what you want.
This is very helpful when finding IP addresses, hostnames, etc.
![image](https://user-images.githubusercontent.com/19948672/106952490-3b942880-6742-11eb-96e0-b2e1862ba971.png)
Sorely need this in Windows terminal

**Comment by zadjii-msft** [comment]
So I think broadly we're tracking this in #8849. That one specifically calls out hyperlinks, but I think could be used for any match really. We also briefly mentioned it in #3920. Coulda swore there was something more specific on the reop, but those two seem to cover it. 

Thanks!

/dup #8849
