### ISSUE TITLE
Bind TabHeaderControl to TerminalTab properties

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#9043]
# Description of the new feature/enhancement

As a part of https://github.com/microsoft/terminal/pull/9041 we are adding indicators (like progress value) to the terminal tab (so it can be rendered in different places).

Currently the `TabHeaderControl` is updated manually in the code behind.
Instead we could bind the `TabHeaderControl` to the properties upon initialization.

**Comment by zadjii-msft** [comment]
Yea I agree with doing this as a follow up. Thanks for filing!

**Comment by zadjii-msft** [comment]
I'm just gonna mention this here so it's not lost from my review on #9041.

> Almost seems like there should be a common interface for both `TabPaletteItem` and `TabHeaderControl`, so whenever we add a property to one of them, it automatically needs to be implemented in the other too (even if just to no-op it)

**Comment by DHowett** [comment]
@Don-Vito I think your tab header thing actually made this better. Should we close?

**Comment by Don-Vito** [comment]
> @Don-Vito I think your tab header thing actually made this better. Should we close?

I think we should close, as long as we don't plan to make this control reusable. Which I guess is not the case.

**Comment by zadjii-msft** [comment]
Okay yea, I doubt anyone's going to be re-using that control any time soon. We can revisit if that ever changes.
