### ISSUE TITLE
Binding enter to copy breaks Command Palette

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#9044]
# Environment

```none
Windows build number: 10.0.19042.789
Windows Terminal version (if applicable):1.6.10272.0
Any other software?
```

# Steps to reproduce

1. put this in actions:
```json
{"command": {"action": "copy","singleLine": false},"keys": "enter"}
```
2. try to use cmdpallet
# Expected behavior

when enter is pressed in cmdpall the highlighted action is executed
# Actual behavior
nothing is executed

# Observations
regression from 1.5

**Comment by Don-Vito** [comment]
@LuanVSO - this is absolutely a regression.

@zadjii-msft - I think I found why key -binding are not working in settings UI

**Comment by zadjii-msft** [comment]
@Don-Vito you're the man. I'll throw you on the Assigned-to line, since I had a feeling you had a beat on this one 😄

**Comment by Don-Vito** [comment]
@zadjii-msft - the scope of the issue is wider: copy and paste interact with terminal rather than a search box
