### ISSUE TITLE
Terminal cannot find installed font

### ISSUE THREAD

**Issue by Yongjun042** [microsoft/terminal#9048]
# Environment

```none
Windows build number: 10.0.19042.746
Windows Terminal version (if applicable): 1.5.10271.0, 1.6.10272.0(Preview)
```

# Steps to reproduce

On setting Fontface : "Cascadia Code PL Light"

# Expected behavior

Cange font to Cascadia Code PL Light

# Actual behavior

It cannot detect Cascadia Code PL Light

![Capture](https://user-images.githubusercontent.com/24871665/107019958-a3e81600-67e5-11eb-86fd-95f939e8e1b0.PNG)

Terminal Perview shows Warning message ' There is no selected font Cascadia Code PL Light. Consolas is selected. install missing font or select other font.'(Normal version just use Consolas without showing warning message.) Terminal only decect 'Cascadia Code PL' and 'Cascadia Code PL SemiLight'. I installed Cascadia Code PL and visual studio code is showing cascadia Code PL Light correctly.

**Comment by DHowett** [comment]
You’re going to want to set the font to “Cascadia Code PL” and the fontWeight to “light”

**Comment by Yongjun042** [comment]
> 
> 
> You’re going to want to set the font to “Cascadia Code PL” and the fontWeight to “light”

Yes. The reason why I think this is strange is that when I Type “Cascadia Code PL SemiLight” it works. Now I'm thinking “Cascadia Code PL SemiLight” is unusual case.

**Comment by DHowett** [comment]
I agree, that is unusual!
