### ISSUE TITLE
click "Open in Windows Terminal"   random show "Service has unexpected situation"

### ISSUE THREAD

**Issue by oqoehbeaopgc** [microsoft/terminal#9049]
click "Open in Windows Terminal"  random show "Service has unexpected situation"
![image](https://user-images.githubusercontent.com/73050941/107030075-068fe080-67eb-11eb-92cb-67c8c5e48da6.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that was being tracked in #8936, and was fixed in #8977. Thanks!

/dup #8936
