### ISSUE TITLE
when I type wt on file explorer address bar it won't open with the current location rather open with default location. (C:\users\current_user)

### ISSUE THREAD

**Issue by mimamulhassankhan** [microsoft/terminal#9050]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
That's by design. You'll want `wt -d .` to open wt in the working directory.

See also https://github.com/microsoft/terminal/issues/878#issuecomment-538511693 (and that whole thread) for more discussion.

/dup #878
