### ISSUE TITLE
Feature request: vscode-style sidebar to navigate really long lines of output

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#9051]
# Description of the new feature/enhancement

Terminal users have these small 25-row windows on what is often many hundreds of lines of text.

![image](https://user-images.githubusercontent.com/172594/107042653-e85dbc80-67b9-11eb-8336-d1f34a623fe4.png)

It would be super cool if Terminal had a sidebar, just like VScodes - to help users work out where they are, and navigate to the right place more efficiently!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2226 for more discussion.

/dup #2226

**Comment by mikemaccana** [comment]
Woohoo! Thanks Mike.
