### ISSUE TITLE
WSL default directory forced to windows filesytem

### ISSUE THREAD

**Issue by aarware** [microsoft/terminal#9055]
There seems to be no way to set the default directory to the root or any directory under the wsl file system.

No mater what I use for "**startingDirectory**" it always resolves to 
`/mnt/c/<startingDirectory>`

I have tried using

- ""  converts to  /mnt/c/windows/system32
- "/"   converts to  /mnt/c
- "~"   converts to current windows user home directory
- "/home/\<my linux user\>"   converts to current windows user home directory

This is the current settings I have for the wsl terminal
```
{
  "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
  "hidden": false,
  "name": "Ubuntu-20.04",
  "source": "Windows.Terminal.Wsl",
  "startingDirectory": "~",
  "tabColor":"#d35115"
   }
```

**Comment by LuanVSO** [comment]
the starting path is always a windows path. use this:
```json
"startingDirectory": "\\\\wsl$\\<distro name>\\<wsl path>",
```

**Comment by aarware** [comment]
Thanks for the fast response.
Seems weird, if you open the linux shell directly the starting path is not windows file system but linux and functions as one would expect, so I don't understand why this would be coded to force it to windows file system, seems a bit counterintuitive. 

I tired the suggestion "assuming i did it right", still does not work

I tried
- "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\~"
- "startingDirectory": "\\\\wsl$\\Ubuntu-20.04"
-  "startingDirectory": "\\\\wsl$"
- "startingDirectory": "wsl$"

Thanks

**Comment by LuanVSO** [comment]
did you escape the 2 backslashes at the start of the path in the json? it has to be `\\\\`  because `\\` is interpreted as `\`

**Comment by sarim** [comment]
try this:
```json
"startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\username"
```

put your ubuntu username in `username`.

**Comment by Don-Vito** [comment]
@aarware
* The original discussion is 2-years old and can be found here: https://github.com/microsoft/terminal/issues/592.
* More recent discussion of how to write the path correctly is here: https://github.com/microsoft/terminal/issues/5377#issuecomment-614724488

**Comment by DHowett** [comment]
Thanks @Don-Vito. This looks like a rehash of 592/5377 plus a little bit of "sometimes WSL doesn't do the right thing." We're working on it, and we think the solution we're working on will make it better even in case WSL doesn't start up the network share.

**Comment by aarware** [comment]
Sorry for the late response, Thanks @sarim and @LuanVSO that was it, I just did not have the "wsl path" as home\\\username.

I still think its strange for the default to open the windows user root, nevertheless, Thanks to all for making this I definitely will get a lot of use of it.
