### ISSUE TITLE
Resizing window breaks the terminal appearance

### ISSUE THREAD

**Issue by kaysond** [microsoft/terminal#9060]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): 1.5.10271.0 and 1.6.10272.0
```

# Steps to reproduce

1. Start terminal
2. Run some commands
3. Resize terminal

# Expected behavior

Terminal resizes appropriately

# Actual behavior
Initial terminal window:
![image](https://user-images.githubusercontent.com/1147328/107099545-d5051e00-67c6-11eb-808c-c6d471aa2fcc.png)

Make it bigger:
![image](https://user-images.githubusercontent.com/1147328/107099556-dcc4c280-67c6-11eb-84ed-fd8b7e3297c2.png)

Make it smaller:
![image](https://user-images.githubusercontent.com/1147328/107099570-e2baa380-67c6-11eb-9c5e-b25f6ded1904.png)

Might be related to #7405, but none of the mentioned workarounds fix this

**Comment by zadjii-msft** [comment]
I'm pretty sure this more closely matches the symptoms of #3088 than anything else. 

/dup #3088
