### ISSUE TITLE
New install unable to Launch via Start Menu

### ISSUE THREAD

**Issue by sbingner** [microsoft/terminal#9062]
# Environment

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

I just installed the latest release file Microsoft.WindowsTerminal_1.5.10271.0_8wekyb3d8bbwe.msixbundle and installed it. When I try to launch after install or launch from the start menu it gives me an error

# Expected behavior

Windows Terminal Opens

# Actual behavior

Windows gives an error saying it can't access the path.  I can browse to the path (After taking owndership of `C:\Program Files\WindowsApps`) and open it with no problems.  [Screenshot](https://www.bingner.com/WindowsStrangeness.png)

**Comment by sbingner** [comment]
So this just magically started working when I left everything alone for about 30 minutes...

**Comment by DHowett** [comment]
The appx/msix deployment platform works in mysterious ways :| sorry about that

**Comment by DHowett** [comment]
Collecting all these issues in #9452
