### ISSUE TITLE
Open new tab with same current working directory as an other one

### ISSUE THREAD

**Issue by scls19fr** [microsoft/terminal#9063]
# Description of the new feature/enhancement

Currently when opening a new tab, current working directory is `C:\Users\MyUser`.

After changing current working directory, it could be very convenient to be able to open a new tab with the same current directory.

My use case is that I often need one tab for running `julia file.py` and see output, an other tab with a Julia REPL opened in the same directory... but I think the problem of having 2 or more tabs opened with same directory is a quite common practice.

# Proposed technical implementation details (optional)

Right click on a tab could have a "New" contextual menu (between rename tab and close) which could show same entries as those in the "+" tab.

The main difference would be that a new tab will be created with the "context" of a tab which was opened previously (context being here the current working directory)

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/3158> would cover most of this, but the proposed UI is different.

**Comment by scls19fr** [comment]
Ok so closing as duplicate of #3158
