### ISSUE TITLE
Unable to find the provided shader "".

### ISSUE THREAD

**Issue by rolflobker** [microsoft/terminal#9064]
Microsoft Windows NT 10.0.19042.0
Windows Terminal Preview Version: 1.6.10272.0

# Steps to reproduce

Open a new tab, with following profile;

-----
      {
        "guid": "{a232ec02-ced9-4160-a72d-16cbc00786c6}",
        "name": "SomeServer",
        "commandline": "c:/profile/someserver.cmd",
        "tabTitle": "SomeServer",
        "backgroundImage": "C:/profile/backdrops/somebackground.jpg",
        "backgroundImageStretchMode": "uniformToFill",
        "backgroundImageOpacity": 0.5,
        "closeOnExit": "always",
        "bellStyle": "none",
        "fontWeight": "light",
        "colorScheme": "Solarized Dark Higher Contrast"
      },
-----

c:/profile/someserver.cmd contains;

-----
set display=localhost:0.0
ssh -Y -C -c aes128-ctr myserver
-----

And myserver is ofc configured in .~/ssh/config as follows

-----
Host *
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
    IdentityFile ~/.ssh/mykey
    ServerAliveInterval 60
    ServerAliveCountMax 2
    User myusername

Host myserver 
	Hostname <SOMEIP>
	LocalForward 3306 localhost:3306
	IdentityFile ~/.ssh/otherkey
------

# Expected behavior

Open the session without popups, being notified about missing shaders, 
And WT remaining active. I noticed it sometimes completely dissappears, but have not been able to pinpoint exactly if that coincides with the "Unable to find the provided shader ""." message

# Actual behavior

Almost always pops up saying "Warning: Unable to find the provided shader ""."

Below animation shows me opening several tabs with pwsh, powershell, cmd
Before opening the sshserver.cmd profile.
I made a copy of the profile pointing to a different background image, this did not change the behaviour

At the end, we see 1 succesful open, then an open with warning message, then another open with warning message before WT just complete closes (all gone)

![ShaderGifSki2](https://user-images.githubusercontent.com/904530/107117288-aac06880-6879-11eb-9e0a-87560cb7285d.gif)

**Comment by rolflobker** [comment]
Addendum:

If I run this batchfile, from a pswh session in Terminal Preview the Terminal also crashes.

I think it has to do with the fact that I change the background image in settings.json;

Batch executed;

@echo off
set display=localhost:0.0
@pwsh.exe -noprofile "C:\profile\Scripts\Powershell\Change-WindowsTerminalBackground.ps1"
ssh -Y -C -c aes128-ctr ssh -Y myhost

Change-WindowsTerminalBackground.ps1

$profilesJson = "C:\Users\user\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json"
$json = Get-Content $profilesJson -Raw | ConvertFrom-Json

$backgrounds = Get-ChildItem "C:\profile\backdrops\view\"

$background = (($backgrounds[(Get-Random -Minimum 0 -Maximum ($backgrounds.Count))]).VersionInfo.FileName) -replace ("\\","/")

$pwsh = $json.profiles.list | where {$PSItem.Name -eq 'PowerShell'}

$pwsh.backgroundImage = $background
$pwsh.backgroundImageStretchMode = "uniformToFill"
#$pwsh.backgroundImageOpacity = 0.5

$json | ConvertTo-Json -Depth 100 | Set-Content $profilesJson

**Comment by zadjii-msft** [comment]
Hmm. This is certainly bizarre. I wonder if this has anything to do with #8723.

For the record, I don't think there's any reason why just hot-reloading your settings file to change the background image should cause the terminal to think you provided an empty string to the pixel shader... Does it consistently happen with a particular image? Maybe it has something to do with the path to that image. No idea really.

**Comment by rolflobker** [comment]
It happens with any image.

I have scheduled a Windows Task to run my script every 5 minutes, every so often it just crashes WT or gives me the shader error popups.

A reload of WT (with unchanged file paths) works just fine.

I have a feeling it has to do with some timings.
When I write back the (whole) settings.json file (using set-content) maybe this causes an event to fire and WT to re-read the file just a millisecond to early?

You should be able to try it out using my script (above) and placing some images in the specified folder.
Then surround that script in a while loop, with start-sleep -seconds 30 or something

**Comment by DHowett** [comment]
Thanks for the report! This has the same root cause as /dup #8723, actually, and there's a fix in #9092!
