### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by huanx9** [microsoft/terminal#9065]
my English is bad 

settings.json 

sometimes 
C:\Users\*\AppData\Local\Microsoft\Windows Terminal
sometimes 
C:\Users\*\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_*\LocalState

**Comment by DHowett** [comment]
Did you change the permissions of `C:\Program Files\WindowsApps`?

**Comment by huanx9** [comment]
if `C:\Program Files\WindowsApps` = root , than wirte  `C:\Users*\AppData\Local\Microsoft\Windows Termina\setting.json`

else 

wirte `C:\Users*\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_*\LocalState\setting.json` ?

**Comment by DHowett** [comment]
If the application is running “inside a container” (correctly deployed, permissions on WindowsApps correct), “Local\Packages\WindowsTerminalPreview...\LocalState”.

if application is running outside a container, or the permissions on WindowsApps are incorrect, sometimes “Local\Microsoft\Windows Terminal\”
