### ISSUE TITLE
ui suggestion: "focus" mode add a title to display the shell title in the play.

### ISSUE THREAD

**Issue by oqoehbeaopgc** [microsoft/terminal#9067]
ui suggestion: "focus" mode add a title to display the shell title in the play.

**Comment by zadjii-msft** [comment]
I'm sorry could you elaborate more? "In the play" - what does that mean? Do you mean like, in the titlebar? In the window frame?

This might be solved with pane titlebars (#4717 / #4998), but I'm not really sure what you're asking for here.

**Comment by oqoehbeaopgc** [comment]
> I'm sorry could you elaborate more? "In the play" - what does that mean? Do you mean like, in the titlebar? In the window frame?
> 
> This might be solved with pane titlebars (#4717 / #4998), but I'm not really sure what you're asking for here.

o9ssce0u

> I'm sorry could you elaborate more? "In the play" - what does that mean? Do you mean like, in the titlebar? In the window frame?
> 
> This might be solved with pane titlebars (#4717 / #4998), but I'm not really sure what you're asking for here.
