### ISSUE TITLE
BEL sound should be customizable

### ISSUE THREAD

**Issue by ARitz-Cracker** [microsoft/terminal#9069]
# Description of the new feature/enhancement

I'm not sure who's idea it was to make the BEL "critical stop", but it was a terrible one. (I know, something something conpty something something beep.sys, either way, I acknowledge the reasons why things are the way they are)

I have custom sound schemes and hearing the "critical stop" sounds when I hold down backspace is annoying. It would be great if a path to a sound file could be specified, other than the binary enable/disable option

**Comment by j4james** [comment]
See issue #8366.

**Comment by ARitz-Cracker** [comment]
> See issue #8366.

My apologies! This didn't show up in my searches 😅

**Comment by DHowett** [comment]
/dup #8336

thanks all!

**Comment by DHowett** [comment]
Ugh. I typoed it, of course. It doesn’t mean anything in the backend, fortunately. :)
