### ISSUE TITLE
Menu is opening in the wrong direction in Terminal Preview

### ISSUE THREAD

**Issue by alshdavid** [microsoft/terminal#9070]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]: 
Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal version (if applicable): 
Version: 1.6.10272.0
```

# Steps to reproduce

Fresh install of windows 10 H2 and installed windows terminal preview on it. 

# Expected behavior

The menu opens in the direction the arrow suggests

# Actual behavior

It opens in the opposite direction

![image](https://user-images.githubusercontent.com/12656294/107181272-96719c80-6a2e-11eb-8897-fa8ca20936df.png)

**Comment by skyline75489** [comment]
I have seen this on one of my laptops several times. I guess it has something to do with WinUI framework itself.

**Comment by Don-Vito** [comment]
@alshdavid - seems duplicate to the discussion in https://github.com/microsoft/terminal/issues/8924
