### ISSUE TITLE
Cannot enable pixel shaders

### ISSUE THREAD

**Issue by bozho** [microsoft/terminal#9071]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10272.0
```

GPU: Nvidia RTX 3070, driver version 461.40.

# Steps to reproduce
I am unable to get pixel shaders working. I've downloaded a few samples (retro, invert, rasterbars) and put them into `F:\Temp`

I've tried putting `"experimental.pixelShaderEffect": "F:\\Temp\\invert.hlsl"` into both profile defaults and individual profiles. I've added `{ "command": "toggleShaderEffects", "keys": "ctrl+shift+."}` to `actions`. The only thing this command seem to do is toggle the built-in "retro" effect (whether `experimental.pixelShaderEffect` setting is present or not makes no difference).

I've renamed my `settings.json` file and tested with a default one, no difference.

# Expected behavior

Shaders to work :-)

# Actual behavior

Shaders not working :-(

**Comment by zadjii-msft** [comment]
The setting is `experimental.pixelShaderPath`, not `experimental.pixelShaderEffect` ☺️

**Comment by bozho** [comment]
@zadjii-msft

Ah, thank you :-) `experimental.pixelShaderPath` is mentioned in pixel shader samples.

However, `experimental.pixelShaderEffect` is mentioned both on 1.6.10272.0 [release notes page](https://github.com/microsoft/terminal/releases/tag/v1.6.10272.0) and [devblog page](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-6-release/). I copy/pasted the setting from one of those two and failed to spot the difference.

**Comment by zadjii-msft** [comment]
GAH that's a typo then. @cinnamon-msft can you go fix those docs quick?

**Comment by DHowett** [comment]
I've fixed the release notes. Sorry about that!

**Comment by sylvain69780** [comment]
Hello

I just downloaded 1.7.572.0 and was not able to enable "experimental.pixelShaderPath".
"experimental.pixelShaderPath": "C:\\Sylvain\\shadertoy\\hlsl\\Grayscale.hlsl"

Only able to use the retroTerminalEffect.

I wanted to make a demo to some colleagues. Too bad. :-)

**Comment by zadjii-msft** [comment]
@sylvain69780 Did it give you any sort of error message when you changed the settings / launched the Terminal? 

You might also need to use double-backslashes, like `"experimental.pixelShaderPath": "C:\\Sylvain\\shadertoy\\hlsl\\Grayscale.hlsl"`

**Comment by DHowett** [comment]
This is #9354.
