### ISSUE TITLE
Pixelshader Time always stays 0

### ISSUE THREAD

**Issue by fredlllll** [microsoft/terminal#9072]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.685]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.6.10272.0
```

# Steps to reproduce

use any pixel shader using the Time value for animation, e.g. https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Animate_scan.hlsl or just set color.r=Time

i do use Shutup 10 from OOSU which could mess with the time, but i havent had any other software freeze in time, granted i also dont use msoft store apps

# Expected behavior

animation should play, Time should not stay 0 but count up, if color.r=Time is set, most of the terminal should turn fully red after a second

# Actual behavior

no animation playing. Time stays 0, color.r = Time just leaves the terminal black and text cyan

**Comment by WSLUser** [comment]
Dupe: https://github.com/microsoft/terminal/issues/8935. This has been addressed but not yet released.
