### ISSUE TITLE
mouse continues hidden after movement

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#9073]
# Environment

```none
Windows build number:10.0.19042.789
Windows Terminal version (if applicable):1.6.10272.0

Any other software?
```

# Steps to reproduce

1. position mouse over the current tab
2. type a character to get the mouse hidden
3. move the mouse around the tab area.

# Expected behavior

mouse gets unhidden

# Actual behavior

https://user-images.githubusercontent.com/43626415/107252713-61585080-6a14-11eb-9467-3053aa718425.mp4

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #8918 for more discussion.

/dup #8918

**Comment by LuanVSO** [comment]
oh sorry 😅
