### ISSUE TITLE
SUI: Add settings for initalPosition, centerOnLaunch

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9075]
Basically the title. `initialPosition` is a weird setting because there's an x and y component, and that has to become a string like `x, y`. 

Center on launch is also weird, because it doesn't _disable_ other settings, it just has weird interactions with `launchMode`, specifically any of the modes where the terminal is maximized.

See also: #6800, #9036

**Comment by vefatica** [comment]
Has this been implemented?  I can't find it in WindowsTerminalPreview: 1.16.2212.12003

**Comment by zadjii-msft** [comment]
Nope. This was first merged in #13605, which should be released in 1.17.

**Comment by vefatica** [comment]
Thanks.  I had looked (quickly) at #13605.  Should I have been able to figure out when it would be released?
