### ISSUE TITLE
Manually creating a Linux profile.

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9077]
I manually created this profile in settings.json.
```
            {
                "commandLine": "wsl.exe",
                "cursorShape": "vintage",
                "guid": "{4ba2fd44-db0a-44c1-95c2-ee4e55916fa1}",
                "hidden": false,
                "name": "**Ubuntu**"
            },
```

When I try to activate it (from the dropdown in Start\Run ... wt -p **Ubuntu**) I get a tab with CMD.EXE in it?

Am I expecting too much or doing something wrong?

**Comment by DHowett** [comment]
`commandline` (note the lowercase l). Our settings are case-sensitive. :smile:

**Comment by vefatica** [comment]
Thanks.  I would have taken me forever to spot that.

So I changed it to "commandLine".  It's still coming up with CMD.EXE (which is not my default profile).  In fact, just starting WT with no options gives me CMD.EXE?

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/107290535-8ef4c800-6a1b-11eb-8285-c583decacbf2.png)


![image](https://user-images.githubusercontent.com/189190/107290537-91572200-6a1b-11eb-8731-98f1cc3a4d6f.png)

![image](https://user-images.githubusercontent.com/189190/107290540-93b97c00-6a1b-11eb-9748-e26be159121d.png)

![image](https://user-images.githubusercontent.com/189190/107290546-961bd600-6a1b-11eb-976f-7ef59f8cc505.png)

**Comment by DHowett** [comment]
🎹 🎵one of these things 🎶 is not like the others 🎼

**Comment by vefatica** [comment]
Huh!

**Comment by DHowett** [comment]
(Did it work when you changed it to a lowercase `l`?)

**Comment by vefatica** [comment]
I don't know exactly what I did, but I'm almost certain it was my error.  I started over with the settings.json fron the non-preview install (which was pretty up-to-date) and made the Linux profile.  All seemd OK now.
