### ISSUE TITLE
Vertical tabs!

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#9082]
# Description of the new feature/enhancement

Now that the Settings UI is here, I'm thinking this might be possible. Vertical (open) tabs on the left side, like the ones in Edge browser.

# Proposed technical implementation details (optional)

Pardon my poor prototyping skills, but here's how it can look: 

![Screenshot 2021-02-0s9 152413](https://user-images.githubusercontent.com/46838874/107348746-6fc66b00-6aed-11eb-9936-e6cbb445b3ae.png)

The current tab would probably have a white-ish background, in the list of tabs on the left.

**Comment by Don-Vito** [comment]
Seems duplicate to #835

**Comment by zadjii-msft** [comment]
Sure is, thanks Don-Vito!

/dup #835
