### ISSUE TITLE
Win10 Enterprise Edition Terminal in the folder right - click can not open

### ISSUE THREAD

**Issue by Burt2o2o** [microsoft/terminal#9085]
Right click on the desktop to open it，but right click in the folder after the quick open,Error: (Explorer. exe: unexpected condition on the server).

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #8936 for more discussion.

/dup #8936
/dup #8990
/dup #9019
/dup #9049
