### ISSUE TITLE
Context menu option for "Open in Windows Terminal" throws exception when launching from folder background

### ISSUE THREAD

**Issue by ekillops** [microsoft/terminal#9086]
# Environment

```
Windows build number: 18363.900
Windows Terminal version: 1.5.10271.0
```

# Steps to reproduce

1. Open a directory in Windows Explorer
2. Right click folder background to open context menu
3. Click "Open in Windows Terminal"

# Expected behavior

Windows Terminal should open with current directory as path.

# Actual behavior

An Explorer.EXE exception popup is displayed stating: "The server threw an exception"

![image](https://user-images.githubusercontent.com/22737511/107405806-8ef8d480-6abc-11eb-9847-ddfdc49feb35.png)

**Comment by zadjii-msft** [comment]
What the heck github? If you search for literally this message:
[?q="The+server+threw+an+exception"](https://github.com/microsoft/terminal/issues?q=%22The+server+threw+an+exception%22)

then you only get _this issue_. HOWEVER, there's another issue with _exactly that text in the title_: #8936. So even if you did try and search for this issue, github wouldn't give it to you. THATS WEIRD YO.

Anyways, /dup #8936
