### ISSUE TITLE
Line-wrap breaks detected links

### ISSUE THREAD

**Issue by Just-Insane** [microsoft/terminal#9089]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 1.5.10271.0

Any other software? Tested in PowerShell, haven't tried WSL or CMD, using a Format-Table with and without the -Wrap parameter.
```

# Steps to reproduce

When a URL is shown on the terminal that is longer than the width of the window, it is either wrapped or truncated to fit to the width of the window. Both wrapped and truncated links are clickable (due to the initial http/https:// section, presumably), however, parameters might be cut off when ctrl+clicking on the links to open them in the browser.

# Expected behavior

Ctrl+clicking on a link should always open the full URL as passed into the terminal output.

# Actual behavior

The end of the URL is not included when ctrl+clicking on the link.

**Comment by DHowett** [comment]
Sorry, I am not sure I understand. The region that is underlined is the region whose text is copied into the hyperlink activation when you ctrl+click on the link.

If the link is truncated by the application, _the parameter data is lost and can never be recovered_. Likewise if the application manually wraps the text (by inserting a hard newline in it) then we cannot complete the link as the application has told us that it's broken in the middle.

Terminal doesn't truncate text unless it is pushed off the top of the scrollback buffer during a resize, and even then that would prefer to delete the _beginning_ of the link, not the end.

Do you have an example of the behavior you're experiencing?

**Comment by Just-Insane** [comment]
Ah, you're correct.

By default PowerShell limits table output to the width of the window, which makes sense.

I was able to find a solution from this [StackOverflow thread](https://stackoverflow.com/a/38576389), using the `Format-Table | Out-String -Stream -Width <int>` option seems like it will work best for me.

Though, manually setting the BufferWidth before and after output (`[console]::BufferWidth = <column-count>`) would also work.

I'm going to close this, as it is not an issue with the Terminal.

**Comment by DHowett** [comment]
So, one thing PowerShell could do is use `OSC 8` to glue the hyperlinks back together. It's a control sequence that lets an application tell a terminal that multiple different runs of text are logically part of the same link. It's intended to be used for this exact scenario. :smile:
