### ISSUE TITLE
Unexpected pane switching behaviour

### ISSUE THREAD

**Issue by otaconjh** [microsoft/terminal#9095]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): 1.6.10272.0
```

# Steps to reproduce

1. Have  4 panes open , one in each corner
2. Using a bottom pane `alt+left/right` to switch between panes
# Expected behavior

1. Pane should switch from bottom-left
![image](https://user-images.githubusercontent.com/41576511/107490271-933af580-6b81-11eb-9e25-9dc9ce1004a0.png)
2. To bottom-right
![image](https://user-images.githubusercontent.com/41576511/107491125-a69a9080-6b82-11eb-8415-7522fdfc7262.png)

# Actual behavior
1. Pane switches from bottom-left
![image](https://user-images.githubusercontent.com/41576511/107490271-933af580-6b81-11eb-9e25-9dc9ce1004a0.png)
2. To top-right
![image](https://user-images.githubusercontent.com/41576511/107491280-d6499880-6b82-11eb-9540-58a5d144a390.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another pair of issues on our repo - please refer to:

* #2398 Move focus to the visually adjacent pane, not just the first pane on the other side of the separator.
* #4692 Pane focus movement doesn't remember where it came from

/dup #2398
/dup #4692
