### ISSUE TITLE
Tab opens in new window on using 'open in windows terminal' feature when another windows exists

### ISSUE THREAD

**Issue by AgrMohit** [microsoft/terminal#9097]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```

# Steps to reproduce
On clicking 'Open in Windows Terminal' in File Explorer the current location opens in a tab in a new window even when another window already exists. This is unexpected and unnecessarily creates one more window to keep track of when alt+tabbing

Furthermore, the inability of being able to drag a tab from the new window to the old one is sorely felt but that is in the scope of another issue

# Expected behavior
It is expected that the new tab will open in the same window which is already open

# Actual behavior
The new tab is opened in a new window

## Possible solution
There could be a user-configurable setting to decide whether tabs should open in a new window or in an already open one

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7071 for more discussion.

/dup #7071
