### ISSUE TITLE
Shell extension "Open Windows Terminal here" should start in current window

### ISSUE THREAD

**Issue by schlamar** [microsoft/terminal#9098]
With #8898 landed wt.exe can now start a terminal tab in an existing window.

I would expect that the new default for the "Open Windows Terminal here" shell extension is starting in the current window, as this is the common default for other sort of applications. For example browsers open a new tab when clicking on a HTML file in the Explorer or VS Code opens a new tab when opening a registered file extension.

However, right now the shell extension doesn't pass a window argument (https://github.com/microsoft/terminal/blob/e207236/src/cascadia/ShellExtension/OpenTerminalHere.cpp#L151) so there will be a new window.

Maybe there should be an option to control this behavior, but new tab in current window should be default.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7071 for more discussion.

/dup #7071
