### ISSUE TITLE
Ability to add Web and File Browser Tabs with Side By Side Split Screen

### ISSUE THREAD

**Issue by dtsai123** [microsoft/terminal#9099]
# Description of the new feature/enhancement

It would be nice to be able to add Web Browser as Windows Terminal Tabs so that I could have all my tasks in one place.  I use Powershell to build websites and command line to run batch jobs.   I would like to be able to view the status of the jobs in the Web Browser Tabs.    But I also want to be able to file the file system in another tab.  Additionally, I would also like to be able to split the screen so that the powershell is on the left and the web browser tab is on the right.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Thanks for the request! 
/dup #997.
