### ISSUE TITLE
New Terminal app icon design

### ISSUE THREAD

**Issue by itsmichaelwest** [microsoft/terminal#910]
Setting out some ideas for a new icon design for the Terminal app. The design aims to stay true to the heritage of the Windows command line, but also fits in more with the Fluent Design System (as well as looking "more modern").

There are two different styles: one for the Taskbar/app list (or any small icon) and a larger, more complete version for use on the Start Menu tile. The taskbar app icon is adaptive, changing its color based on the user's Windows shell theme. The Start Menu tile background also matches that of other Microsoft developer apps (Visual Studio, Code).

![Screenshots showing examples of the new icons](https://user-images.githubusercontent.com/19785650/58054577-e91c6e00-7b52-11e9-9f9d-cd71792e158b.png)

There is a [Figma document containing these icons](https://www.figma.com/file/UO8NGpgj876sK41XAAsDjof4/Terminal?node-id=0%3A1) for anyone wishing to inspect with more detail.

There is also a [more detailed post](https://www.michaelwe.st/blog/2019/05/17/creating-a-new-windows-terminal-icon/) where I discuss some of the design decisions (this also shows some other variants). Both the icons here and in the post are purely proposals, and may only serve as ideas for the design team.

I've [made a fork](https://github.com/itsmichaelwest/terminal/tree/fluent-icon-dev) with the new icons added, but there might be some asset conflict issues.

**Comment by Joshua-Ashton** [comment]
Looks very cool! Good work @itsmichaelwest! <3

**Comment by mdtauk** [comment]
Inspired by Michael's Icon design, I also made an attempt at one.  Inspired by the Office Icons.  I focused on the Colour and Tabs (which are some of the biggest features) as well as some hint at shadows and acrylic.

![Windows Terminal](https://user-images.githubusercontent.com/7389110/58056685-eec98200-7b59-11e9-99e0-fd327b3e22e4.png)

**Comment by Joshua-Ashton** [comment]
fight fight fight

**Comment by vitorgrs** [comment]
> Inspired by Michael's Icon design, I also made an attempt at one. Inspired by the Office Icons. I focused on the Colour and Tabs (which are some of the biggest features) as well as some hint at shadows and acrylic.
> 
> ![Windows Terminal](https://user-images.githubusercontent.com/7389110/58056685-eec98200-7b59-11e9-99e0-fd327b3e22e4.png)
 
I think you should PR this in Powershell. The blue fit them better :)

**Comment by mdtauk** [comment]
@vitorgrs  Ideally it would be possible to match the colour to the chosen accent colour - or even update the icons to match the default profile's colour scheme.  Powershell is one of the Terminals you can add as a profile, and in order for the icon to stand out on dark and light backgrounds, you need to pick a colour.

But I am happy for the colour to not match Powershell 🙂

![ubuntu term](https://user-images.githubusercontent.com/7389110/58057881-a06ab200-7b5e-11e9-9e12-6866a5ba79c6.png)

![custom term](https://user-images.githubusercontent.com/7389110/58058070-6057ff00-7b5f-11e9-948c-838ded1835dd.png)

**Comment by Joshua-Ashton** [comment]
Solarized Light terminal! Hah, nice.

**Comment by yaichenbaum** [comment]
The icon by @itsmichaelwest keeps it similar enough to the old design but makes some necessary changes as things changed a lot since the last time the icon was updated.
I really like the icons from @mdtauk which look really good but somehow they don't seem to fit in. Perhaps making it not as tall and more like Michael's idea, it would fit in better.

**Comment by Joshua-Ashton** [comment]
I think the icon for @mdtauk would be much better suited for a new Powershell icon

**Comment by yaichenbaum** [comment]
@mdtauk's I think would be good for in the tabs for Powershell (with some tweaks to the design to not be as tall) but for the app itself I think Michael's icon is a better option.

**Comment by cinnamon-msft** [comment]
Thank you for all your feedback and designs! We have been working with a design team on creating a new icon for a few weeks now.
We love all of the enthusiasm and creations you have made and I made a note to show our designers as well. We are working on an icon that fits Windows' design guidelines and will keep you updated with our latest version and will ask for feedback once it's ready!
Thanks for being so involved; we look forward to seeing what you think! :)

**Comment by yaichenbaum** [comment]
@mdtauk 
![image](https://user-images.githubusercontent.com/39923744/58059627-c6cb2600-7b3b-11e9-8033-199646a0e754.png)

**Comment by mdtauk** [comment]
It works either way I think.

Having it more square would fit a little better in a live tile, and matches the height of the Office Fluent Icons.

**Comment by mikemaccana** [comment]
Oh sweet I'll close this and move my comment there.

**Comment by mikemaccana** [comment]
Oh wait I can't close it. Anyway someone else can!

**Comment by mikemaccana** [comment]
Hah I filed a dupe for this but I see folks are already working on it. Echoing my comment from #937:

Requirements I can see are:

 - Look like a Windows icon (Windows Terminal is Windows specific) and follow Windows design guidelines.
 - Not be specific to a particular shell - can't look too specifically like `pwsh`, `bash` or `cmd`.
 - Have dark and light mode variants

**Comment by miniksa** [comment]
I don't think this needs to be reactivated. Kayla is on this and working with the design teams.

**Comment by DHowett-MSFT** [comment]
We now have a passable v1 icon in. We can probably get working on a different shell mode variant (light/dark) but for now this’ll do!

It doesn’t look too much like any particular shell, either, so that’s a bonus!

**Comment by mdtauk** [comment]
> We now have a passable v1 icon in. We can probably get working on a different shell mode variant (light/dark) but for now this’ll do!
> 
> It doesn’t look too much like any particular shell, either, so that’s a bonus!

![terminal-256](https://user-images.githubusercontent.com/7389110/59649392-7e267d00-917a-11e9-9aa3-35eb98684616.png)

**Comment by yaichenbaum** [comment]
@DHowett-MSFT do you have a screen shot?

**Comment by mdtauk** [comment]
> @DHowett-MSFT do you have a screen shot?

@yaichenbaum See my post above, that is the new icon

**Comment by itsmichaelwest** [comment]
The new icon looks awesome, great job by the design team! 😃 Also cool to see it incorporate features from our various designs (if unintentionally).

**Comment by yaichenbaum** [comment]
Ha, I thought that was @itsmichaelwest icon, they look quite similar, great job!

**Comment by vermaakarsh** [comment]
> Inspired by Michael's Icon design, I also made an attempt at one. Inspired by the Office Icons. I focused on the Colour and Tabs (which are some of the biggest features) as well as some hint at shadows and acrylic.
> 
> ![Windows Terminal](https://user-images.githubusercontent.com/7389110/58056685-eec98200-7b59-11e9-99e0-fd327b3e22e4.png)

@mdtauk Is this icon copyrighted or open for use.. really liked it and wanted to use it on my You tube channel

**Comment by mdtauk** [comment]
> > Inspired by Michael's Icon design, I also made an attempt at one. Inspired by the Office Icons. I focused on the Colour and Tabs (which are some of the biggest features) as well as some hint at shadows and acrylic.
> > ![Windows Terminal](https://user-images.githubusercontent.com/7389110/58056685-eec98200-7b59-11e9-99e0-fd327b3e22e4.png)
> 
> @mdtauk Is this icon copyrighted or open for use.. really liked it and wanted to use it on my You tube channel

It is close enough to the final logo design used by Terminal, that I would advise you find a different design to use.
