### ISSUE TITLE
Vertical Tabs Option

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/terminal#9100]
# Description of the new feature/enhancement

The terminal can sometimes suffer from tab clutter like web browsers. A useful enhancement would be the option to enable vertical tabs, similar to the Edge browser.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22vertical+tabs%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #835 for more discussion.

/dup #835
