### ISSUE TITLE
Multiple startup profiles

### ISSUE THREAD

**Issue by maicol07** [microsoft/terminal#9101]
# Description of the new feature/enhancement
Currently, when you open WT only a profile starts (for example WSL). It would be great to open more than one profile when WT starts. Obviously, all the profiles should start from the directory they were called (if I open WT from Documents via right click, all the profiles should start with root directory set to the calling directory)

**Comment by zadjii-msft** [comment]
You might want to check out [`startupActions`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/startup#startup-actions-preview) which was added in v1.6. So you can do something like:
```json
"startupActions": "new-tab; split-pane wsl.exe; new-tab pwsh.exe"
```

and get 3 tabs, one with the default profile, one with wsl, and the third with `pwsh.exe`.

/dup #756
