### ISSUE TITLE
[Question]: Show tabbar only when multiple tabs present

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#9104]
```
Windows: 10.0.19042.804
Windows Terminal: 1.6.10272.0
```

Hi, is there a way to configure WT's behavior like this?

When only single tab is present -

![image](https://user-images.githubusercontent.com/46838874/107563409-0b97ca00-6c07-11eb-82c3-641e6b92f60d.png)

And when more than one tab is present is present -

![image](https://user-images.githubusercontent.com/46838874/107563569-413cb300-6c07-11eb-9b54-bfac7a2150e1.png)

---
I tried fiddling around with `alwaysShowTabs` and `showTabsInTitleBar` settings, but I keep getting this -

![image](https://user-images.githubusercontent.com/46838874/107563501-279b6b80-6c07-11eb-8246-2a16ec509a17.png)

Is what I ask possible? Because the last image looks pretty ugly.

**Comment by DHowett** [comment]
`"alwaysShowTabs": false`

**Comment by DHowett** [comment]
We're not going to support moving the tab strip _into_ the titlebar when the number of tabs goes from 1 to 2, but we _will_ support alwaysShowTabs false + showTabsInTitlebar false forever.
