### ISSUE TITLE
Settings UI doesn't respond to Ctrl+F4

### ISSUE THREAD

**Issue by bhardwajs** [microsoft/terminal#9108]
# Environment

```none
Windows build number: 21311.1000
Windows Terminal version (if applicable): 1.6.10272.0

Any other software?
```

# Steps to reproduce
1. Open Settings UI
2. Ctrl + F4

# Expected behavior
Settings UI should close

# Actual behavior
No effect on settings UI.
If I change to another tab, Ctrl + F4 closes that tab.

**Comment by zadjii-msft** [comment]
Do you have <kbd>Ctrl+F4</kbd> bound in your settings? I'm trying to figure out if the "close tab" behavior you're getting is the one built-in to the tab control, or the one that the Terminal implements. 

I'm thinking that this is a blend between #8585 and #8767

**Comment by bhardwajs** [comment]
@zadjii-msft I don't have `Ctrl+F4` bound in my settings. Testing right now, behavior is close to #8585  in that `Ctrl+F4` has no effect until I am on the title bar.

**Comment by zadjii-msft** [comment]
Alright, then I'm gonna close this one as a duplicate. Thanks!

/dup #8585
