### ISSUE TITLE
Bottom lines of terminal display blocked off after closing vim

### ISSUE THREAD

**Issue by noncomputable** [microsoft/terminal#9110]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): Preview
Profile: PowerShell

Any other software?
```

# Steps to reproduce

1. Open a file with vim: `vim file.txt`
2. Close it: `:q`
3. Enter any input to the terminal

# Expected behavior

The terminal input prompt should appear on the line after `vim` was entered, and the next line after that should be the output to your input. Any lines after that should be blank.

# Actual behavior

Your input is copied to the bottom line of the terminal, and the output is printed on the bottom lines before it. Then the new terminal input prompt appears on the line above the output. If I open any other program, these bottom lines are still blocked off, e.g. after opening a file with vim, the bottom lines of the screen will be the output of my last terminal command followed by the input I last gave to the terminal.

For example, running `[Environment]::OSVersion` (top line), fills the bottom as follows:
![image](https://user-images.githubusercontent.com/12204924/107599906-1dba3e00-6bf0-11eb-8496-74c1be08a4d8.png)

If I run `clear`, the bottom clears but is still unusable, and my next input/output into the terminal is again copied to those bottom lines.

**Comment by DHowett** [comment]
Do you have any `set lines` or `set columns` directives in your vimrc?

**Comment by noncomputable** [comment]
> 
> 
> Do you have any `set lines` or `set columns` directives in your vimrc?

Nope

**Comment by DHowett** [comment]
Sorry for the delay here.

What version of Vim are you using? Does this still reproduce with the latest Preview?
