### ISSUE TITLE
Bug when deleting

### ISSUE THREAD

**Issue by syauqeesy** [microsoft/terminal#9111]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

not blinking

# Actual behavior

the terminal blinking when i tried deleting

**Comment by KalleOlaviNiemitalo** [comment]
@syauqeesy, are you using Bash, e.g. from the Git for Windows package? If so, the blinking could be the "visual bell" and by design; see <https://github.com/microsoft/terminal/issues/7200> for how to disable it.

**Comment by zadjii-msft** [comment]
Yea, you gotta provide us some more info here. This sure does _sound_ like a visual bell, but you haven't given us any info about what shell you're using, what version of the Terminal, etc. If you need more help, please provide more details and we'll be happy to reopen this. Thanks!
