### ISSUE TITLE
"The server threw an unexpected exception" when trying to open Windows Terminal from File Explorer

### ISSUE THREAD

**Issue by Dobby007** [microsoft/terminal#9112]
### Environment
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
![image](https://user-images.githubusercontent.com/2484265/107620543-ebe3be80-6c65-11eb-81ec-9e667df215fc.png)

### Steps to reproduce
After re-installing Window Terminal from Windows Store go to an arbitrary folder in File Explorer, click on empty space to show up the context menu and click on Open in Windows Terminal.

### Expected behavior
Windows Terminal is shown up with the working directory set to the current folder.

### Actual behavior
An error saying "The server threw an exception" is shown up
![image](https://user-images.githubusercontent.com/2484265/107621109-d0c57e80-6c66-11eb-9f5d-4a6c2b953a6c.png)

### Notes
The error does not show up when trying to open WIndows Terminal in one of the sub-directories in the current folder. Windows Terminal opens normally in this case. The error only pops up in case if Windows Terminal is opened in the current directory and not in one of its sub-folders.

**Comment by zadjii-msft** [comment]
For whatever reason, github searches are having a hard time with this one. From #9086:

> What the heck github? If you search for literally this message:
> [?q="The+server+threw+an+exception"](https://github.com/microsoft/terminal/issues?q=%22The+server+threw+an+exception%22)
> 
> then you only get _this issue_. HOWEVER, there's another issue with _exactly that text in the title_: #8936. So even if you did try and search for this issue, github wouldn't give it to you. THATS WEIRD YO.
> 
> Anyways, /dup #8936

Anyways, /dup #8936
