### ISSUE TITLE
Windows terminal doesn't handle SIGWINCH properly

### ISSUE THREAD

**Issue by alvinseville7cf** [microsoft/terminal#9113]
# Environment

```none
Windows build number: Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce
Execute this Bash script and try resize Windows Terminal window:
```bash
#!/usr/bin/env bash
function outputText()
{
  local text=$1
  local -i textLength=${#text}

  local -i line="$(tput lines) / 2"
  local -i col="$(tput cols) / 2 - $textLength / 2"

  clear
  echo -en "\e[$line;${col}H$text"
}

trap "outputText 'Hello world!'" SIGWINCH

outputText 'Hello world!'
while true
do
    :
done
```
As you see Windows Terminal doesn't handles [SIGWINCH](https://man7.org/linux/man-pages/man7/signal.7.html) properly. However everything works fine when I execute my script directly from Cygwin Terminal without Windows Terminal.

# Expected behavior
Centered text is drawn on the screen after window resize.

# Actual behavior
Text isn't centered after window resize.

**Comment by alvinseville7cf** [comment]
> Just a question - are you doing this in WSL or git bash?

I'm doing it via Cygwin Bash.

**Comment by j4james** [comment]
> You know, I coulda swore we were tracking this somewhere.

In issue #305 you decided that issue #281 would be the master thread for all window WINDOW_BUFFER_SIZE_EVENT / SIGWINCH discussion, so I suspect that's the one you're thinking of.

**Comment by zadjii-msft** [comment]
You know, I might have actually been thinking of #5094

**Comment by j4james** [comment]
I wouldn't have thought #5094 had anything to do with it. Unless I've misunderstood what is going on here, the script isn't resizing the window, it's just redrawing the text after it detects a resize. It works for me in both conhost and Windows Terminal when run from a WSL bash shell. I assumed the issue was something specific to Cygwin.

**Comment by zadjii-msft** [comment]
Oh, maybe I'm misunderstanding what the sample was supposed to be doing. I thought it was trying to resize the terminal to some size, not listen for buffer size events. 

This is working perfectly fine in WSL, so I'd agree that this is probably a cygwin-specific issue and should be filed on their issue tracker.

**Comment by DHowett** [comment]
Marking this one external. Thanks all!

**Comment by alvinseville7cf** [comment]
> This is working perfectly fine in WSL, so I'd agree that this is probably a cygwin-specific issue and should be filed on their issue tracker.

I issued this problem to Cygwin developers and waiting for feedback now. ;)

**Comment by determin1st** [comment]
SIGWINCH is unreliable, ive tested it in fresh Debian install with gnome desktop. it should be abolished in preference to polling
