### ISSUE TITLE
URL hover doesn't work when VT mouse mode is enabled

### ISSUE THREAD

**Issue by ondras** [microsoft/terminal#9117]
# Environment

```none
Windows build number:  [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.5.10271.0
```

URLs are not underlined (nor clickable) when displayed in a tmux session (in a Windows Terminal window). They work fine when displayed without tmux.

**Comment by zadjii-msft** [comment]
Are you using mouse mode with tmux? If so, you'll probably need to hold <kbd>Shift</kbd> to make the hyperlinks work. When an app has requested mouse mode, the app gets the first shot at mouse detection.

This isn't strictly consistent with other terminals though. `gnome-terminal` will still highlight hyperlinks, even when an app is in mouse mode. @DHowett do we have a dupe for this?

**Comment by ondras** [comment]
> Are you using mouse mode with tmux? If so, you'll probably need to hold Shift to make the hyperlinks work. When an app has requested mouse mode, the app gets the first shot at mouse detection.

Yeah, that is the case. Thanks for suggesting the `Shift` workaround. It would be nice to be on par with other terminal apps (`xfce-terminal` in my case), though, to provide consistent cross-platform behavior/UX.

**Comment by DHowett** [comment]
Don't think we have a dupe, but I'll title this one appropriately.

**Comment by DHowett** [comment]
Here's what _I_ think we should do. When VT mouse mode is on, hover should work fine ... but the tooltip should say "ctrl+shift+click" instead of "ctrl+click". What do you think?

**Comment by ondras** [comment]
> `gnome-terminal` will still highlight hyperlinks, even when an app is in mouse mode.

My `xfce4-terminal` will still ctrl-click hyperlinks, even when an app is in mouse mode. What is preventing Windows Terminal from working the same?

**Comment by DHowett** [comment]
@ondras because we didn’t implement it like that? And you reported it to us, in this bug that you reported, and we accepted into our backlog to fix? ???

**Comment by ondras** [comment]
> @ondras because we didn’t implement it like that? And you reported it to us, in this bug that you reported, and we accepted into our backlog to fix? ???

So it might be misunderstanding on my side. Because after reading this comment of yours, 

> the tooltip should say "ctrl+shift+click" instead of "ctrl+click".

it seemed to me that you are suggesting to leave in the current "ctrl+shift+click" implementation (and change the tooltip accordingly), instead of changing the behavior to "ctrl+click" (and leaving the tooltip in its current state).

Sorry for causing confusion.

**Comment by DHowett** [comment]
Oh, yes, sorry. I was confused. I was wondering if we should maintain the shift behavior for user consistency with VT mouse applications :smile:

**Comment by Don-Vito** [comment]
@DHowett , @ondras  - probably this is a stupid question, but in the suggested solution, should ctrl+click only handle the hyperlink or also send the input to VT?

**Comment by j4james** [comment]
I would think if an app has enabled mouse mode, then we probably *shouldn't* be intercepting clicks on links, unless we're talking about `OSC 8` hyperlinks that the app has specifically indicated are meant to be handled by the terminal. For example, if the app is something like a web browser, I wouldn't think it would want the terminal taking over links in the web pages it is showing.

I've just been looking at how Mintty handles this, and they have options to let the user decide how it should work, but by default it seems that clicks are passed through to the app, unless you override with Shift (so you need Ctrl-Shift-Click to intercept a link click).

![image](https://user-images.githubusercontent.com/4181424/110186537-866e9200-7e0d-11eb-8e0f-441e2e53c94a.png)

**Comment by Don-Vito** [comment]
> 
> 
> I would think if an app has enabled mouse mode, then we probably _shouldn't_ be intercepting clicks on links, unless we're talking about `OSC 8` hyperlinks that the app has specifically indicated are meant to be handled by the terminal. For example, if the app is something like a web browser, I wouldn't think it would want the terminal taking over links in the web pages it is showing.
> 
> I've just been looking at how Mintty handles this, and they have options to let the user decide how it should work, but by default it seems that clicks are passed through to the app, unless you override with Shift (so you need Ctrl-Shift-Click to intercept a link click).
> 
> ![image](https://user-images.githubusercontent.com/4181424/110186537-866e9200-7e0d-11eb-8e0f-441e2e53c94a.png)

Yeah. I like this direction. It also requires minimal change in code :smile:
Major concern is that the user might be not aware that the app is in mouse mode.. and will expect that ctrl+click will work.

**Comment by j4james** [comment]
> Major concern is that the user might be not aware that the app is in mouse mode.. and will expect that ctrl+click will work.

Is it too late to make Ctrl+Shift+Click the key combo to use for *all* auto-detected links? Then the user doesn't need to know whether the app is in mouse mode or not, but we also aren't hijacking one of the main click types.

Otherwise maybe there needs to be a mode that apps can set to enable or disable this functionality. It's possible some other terminals already have something like that actually.
