### ISSUE TITLE
Pressing ALT+SHIFT+D to split the current pane into two panes causes PWSH to start incorrectly

### ISSUE THREAD

**Issue by JasonWThompson** [microsoft/terminal#9119]
# Environment
```
OS Version:
[Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Terminal version: 
Windows Terminal Preview
Version: 1.6.10272.0
```

Any other software?
```
pwsh --version
PowerShell 7.1.1
```

# Steps to reproduce

Open up a tab configured to start with Powershell 7.1.1. Press ALT+SHIFT+D

# Expected behavior

A new Powershell instance starts in a separate pane.

# Actual behavior

I get a pane that says ``[error 0x8007010b when launching `pwsh.exe']``

# Other notes
Splitting the broken pane creates a working pane. Splitting that pane gives a broken pane. And so on...

Additionally splitting the pane with `ALT+SHIFT+-` or `ALT+SHIFT+=` works every time.

Here's an example of me splitting the pane over and over again. You may need to zoom out since this is from my 4k screen.

![image](https://user-images.githubusercontent.com/7197333/107681765-1aad6500-6c65-11eb-8ade-56ee7c063cf4.png)

**Comment by JasonWThompson** [comment]
I didn't notice this when initially searching for the issue, but this is very similar to #9114 The only difference is that the author of #9114 is duplicating the tab and I'm splitting the pane. I'm guessing the cause is the same.

**Comment by zadjii-msft** [comment]
Yep, these are the same root cause, which is fundamentally #8930.

/dup  #8930
