### ISSUE TITLE
ctrl+click url does not change virtual desktop

### ISSUE THREAD

**Issue by ondras** [microsoft/terminal#9123]
# Environment

```none
Windows build number:  [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.5.10271.0
```

My browser runs on Virtual Desktop 1, my Windows Terminal runs on Virtual Desktop 3. When I Ctrl-click a link inside the terminal, the URL is correctly opened in the browser - but I remain at Virtual Desktop 3. I understand that this behavior might be preferred by some, but there are at least two other UX patterns worth considering (that are implemented in other OSes) as well:

  1. switching to the browser's desktop (I would prefer this one)
  1. bringing the browser to terminal's desktop

**Comment by DHowett** [comment]
All we do is tell the OS to "please launch this URL". Anything that happens after that is out of our control -- otherwise, we would have to run a detection pass for windows belonging to any browser--manually!--and try to focus them. That seems like the wrong thing to do.

**Comment by ondras** [comment]
I see. 🤷
