### ISSUE TITLE
Open in Windows Terminal shortcut causes Exception

### ISSUE THREAD

**Issue by hichemfantar** [microsoft/terminal#9125]
# Environment
Windows build number: 1909
Windows Terminal version (if applicable): 1.5.10271.0

# Steps to reproduce

Open any folder in windows explorer then right click in an empty area and click "Open in Windows Terminal"

# Expected behavior
Windows Terminal should open in current directory

# Actual behavior
Error. "Explorer.EXE "The server threw an exception.""

![image](https://user-images.githubusercontent.com/34947993/107713328-495e2680-6ccb-11eb-8302-1e807976e2ad.png)
![image](https://user-images.githubusercontent.com/34947993/107713344-5418bb80-6ccb-11eb-8980-b27a55f78bc2.png)

**Comment by DHowett** [comment]
Update to 1.5.10412.
