### ISSUE TITLE
Arrow keys no longer work in the Tab Switcher 

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9130]
This is on Preview Version: 1.7.413.0, which is basically just `main`. Usually you can open that tab switcher and use the arrow keys to navigate the list, like the command palette. Now it seems that interaction no longer works?

Might have been broken in #9056? Unsure if that made the 1.7 selfhost though.

/cc @Don-Vito as an fyi

**Comment by Don-Vito** [comment]
@zadjii-msft - please assign to me. I will try to take a look during the weekend

**Comment by Don-Vito** [comment]
Like it is sure that change. When merging the handlers, I was not aware that arrows are in use in tab switcher (because you still need an anchor to be held) and added a short circuit.
