### ISSUE TITLE
Toggle terminal to and from dock

### ISSUE THREAD

**Issue by iipom** [microsoft/terminal#9131]
# Description of the new feature/enhancement
Ability to toggle terminal to and from the taskbar dock, essential a visibility toggle for the terminal.

**Comment by brunovieira97** [comment]
You mean Quake-style Terminal, except coming from the taskbar instead of always from the top border?

**Comment by zadjii-msft** [comment]
Could you possibly mean either one of:
* hot key drop down ala quake/guake/tilda #653
* Minimize to tray #5727 

?

**Comment by iipom** [comment]
> 
> 
> Could you possibly mean either one of:
> 
>     * hot key drop down ala quake/guake/tilda #653
> 
>     * Minimize to tray #5727
> 
> 
> ?

I think those suggestions are a good alternative to mine
