### ISSUE TITLE
Tabs Switcher

### ISSUE THREAD

**Issue by dmitrycrivoy** [microsoft/terminal#9133]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

I'm sorry, but (I think it's just because of new version of MS Terminal) now I see visualization of tabs switching and I remember that I didn't see that. So how can I disable this small window? Because, I think, it's inconvenient to look at the Terminal window. Thanks.

![2021-02-12_172559](https://user-images.githubusercontent.com/19807208/107787150-65a7a500-6d57-11eb-9784-3aca0eda9a90.png)

**Comment by WSLUser** [comment]
If you don't want to use the Advanced Tab Switcher, you can disable it in settings. Check the docs

**Comment by dmitrycrivoy** [comment]
> If you don't want to use the Advanced Tab Switcher, you can disable it in settings. Check the docs

Thanks a lot for the hint, I didn't find this option in the documentation right away. So, maybe it will help someone - the 'useTabSwitcher' parameter should be set to false (in my case it was like "useTabSwitcher": "inOrder").

**Comment by nmtitov** [comment]
Now this settings is here: 
Settings - Interaction - Tab switcher interface style - Traditional navigation, no separate window
