### ISSUE TITLE
Cannot change theme (neither in default nor in list item)

### ISSUE THREAD

**Issue by Trophime** [microsoft/terminal#9136]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce

Create a key "theme" in settings.json in default section
ex: "theme": "light"
# Expected behavior

The theme shall change to value of the "theme" key

# Actual behavior

Nothing actually change. The theme remains as before "dark"

**Comment by zadjii-msft** [comment]
* What theme is your OS set to? Light, Dark, High Contrast...?
* Could you share your whole `settings.json` file? 

This has worked for a number of releases now and hasn't been touched recently, so I'd be surprised to see it regress...

**Comment by DHowett** [comment]
Sorry -- just caught this. "In the default section" may be the wrong place. Can you put it at the top level of the settings file _outside of `profiles` completely_?

**Comment by Trophime** [comment]
I've tried to apply the change you suggest without success. See my settings.json:
```
// This file was initially generated by Windows Terminal 0.11.1251.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
  "$schema": "https://aka.ms/terminal-profiles-schema",

  "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

  // You can add more global application settings here.
  // To learn more about global settings, visit https://aka.ms/terminal-global-settings

  // If enabled, selections are automatically copied to your clipboard.
  "copyOnSelect": false,

  // If enabled, formatted data is also copied to your clipboard
  "copyFormatting": false,
  "theme": "system",
...
```

**Comment by zadjii-msft** [comment]
Wait so, where are you adding `"theme": "light"`? Because that file says that it's explicitly requesting the `"system"` theme...

**Comment by Trophime** [comment]
Actually I've tried to switch to light theme on windows. Then I've added "them": "system" since as the docs suggest it would change my windows terminal to the one used by the system. And it doesn't. That was just another trial to change the theme.

My problem may come from my settings.json which correspond to an old version of windows terminal..
How can I force it to be recreate for newest version? Simply remove it and relaunch windows terminal?

**Comment by zadjii-msft** [comment]
I wouldn't worry too much about the version of the settings file - the `theme` property hasn't changed since like, 0.10, so that's not the issue here. 

This is maybe gonna sound crazy, but could you share a screenshot?

**Comment by Trophime** [comment]
![wterminal](https://user-images.githubusercontent.com/1309311/109305291-cba72880-783d-11eb-86c7-8e613cd8238a.png)

**Comment by Trophime** [comment]
@zadjii-msft As you can see my windows theme is Light; I've also set theme to light in windows terminal 
And still the terminal is not what I've expected with a  white background..

**Comment by zadjii-msft** [comment]
Ah! That's what I thought! You actually _have_ changed the app's theme to light - note that the titlebar is white. What you want is to change the _color scheme_. The `colorScheme` property in your profiles is what actually controls the appearance of the terminal content itself. For more info, you can [check out the docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes)

**Comment by Trophime** [comment]
Ok got it. Thanks sorry for the trouble
