### ISSUE TITLE
Opening wt.exe can no longer open as administrator (both WT and WT Preview)

### ISSUE THREAD

**Issue by ackrumb** [microsoft/terminal#9138]
# Environment

```none
Windows build number:  Microsoft Windows NT 10.0.21301.0 (aka 21301.1010 via WinVer)
Windows Terminal version (if applicable):
- WT Preview: 1.6.10412.0
- WT: 1.5.10411.0

```

# Steps to reproduce
## Scenario 1: directly Run as Administrator
- Navigate to install directory in Explorer (in my case, C:\Users\[USERNAME]\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe
- Right Click on wt.exe and click Run As Administrator
## Scenario 2: Creating a shortcut to wt.exe
- Create a shortcut to the path above.
- Change the shortcut's properties to Run as Adminstrator

# Expected behavior
Terminal shows a UAC prompt and launches elevated.

# Actual behavior
A dialog box:
![image](https://user-images.githubusercontent.com/11276745/107811940-d1701a80-6d23-11eb-8f2d-b5a1eed66a5e.png)
I can confirm the path is correct, and left click on the icon launches WT correctly.

Interestingly, clicking Run as Adminstrator when launching from Start _does_ succeed.

**Comment by DHowett** [comment]
Was this working before either the WT or Windows update? You're using a dev build of Windows that has perhaps had some churn in app execution alias handling.

If you go to the "manage app execution aliases" page and disable/re-enable the wt.exe alias, is the issue resolved?

**Comment by ackrumb** [comment]
Yup! Resolved by turning on and off wt.exe alias. 

Could be a dupe of #7188?

**Comment by zadjii-msft** [comment]
Very well might be. The Store has been working in mysterious ways as of late:
* #9017
* #9159
* #7188
* #9062

All these are similar, but I don't think we've got a single root cause narrowed down.

/dup #7188
