### ISSUE TITLE
pppoe connection problem

### ISSUE THREAD

**Issue by c2xusnpq6** [microsoft/terminal#9139]
I cannot share the network via a Windows laptop connected with PPPoE
![image](https://user-images.githubusercontent.com/75058881/107815987-142b0480-6daf-11eb-9adc-a88d6f16a9fd.png)

and I found a software can do that `connectify`
https://www.connectify.me/

it's nothing about `wsl`, i know that...
just... fix this shi*! microsoft!!!!!!!!! ^_^

(i'm not eng guy, so I use a lot of google translate~ just...... FIXXXXXXXXXXXX ITTTTTTTTTTTT thx~ and it's not cheap... so...... FIX IT QUICK~

**Comment by zadjii-msft** [comment]
Yea, there's nothing actionable for us here. This doesn't look like it's even slightly an issue related to the Windows Terminal. If it is, feel free to add some details to help clarify, and make sure to refer to our [code of conduct](https://github.com/microsoft/terminal/blob/main/CODE_OF_CONDUCT.md) when posting here. Thanks!
