### ISSUE TITLE
The term 'ssh' is not recognized even though openSSH is installed

### ISSUE THREAD

**Issue by zaidajani** [microsoft/terminal#9145]
# Environment

```powershell
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ssh
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

# Steps to reproduce

1. Open windows terminal or PowerShell
2. run `ssh`

# Expected behavior

As I have OpenSSH installed, The behavior should happen to be like this.

```powershell
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```

# Actual behavior

Even though I have OpenSSH installed on my pc, It shows this error which is unexpected. In my windows terminal ( `PowerShell` ) This annoying error comes not allowing me to connect to my server on the cloud.

**Comment by DHowett** [comment]
I suspect you're using 32-bit (x86) PowerShell. Can you run `gci env:/PROCESSOR*`?

**Comment by zaidajani** [comment]
It says I use x86 `PROCESSOR_ARCHITECTURE`

```powershell
PS C:\Users\Admin> gci env:/PROCESSOR*

Name                           Value
----                           -----
PROCESSOR_ARCHITEW6432         AMD64
PROCESSOR_REVISION             1801
PROCESSOR_LEVEL                23
PROCESSOR_IDENTIFIER           AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
PROCESSOR_ARCHITECTURE         x86


PS C:\Users\Admin>
```

**Comment by DHowett** [comment]
This is a bug with how Windows automatically registers OpenSSH. Because it lives in “system32”, a folder which 32-bit processes _redirect_, it cannot be found by looking in the PATH. You should prefer to use a native/64-bit shell unless you have a specific reason not to, or use the full _redirected_ path to OpenSSH, `c:\windows\sysnative\openssh\ssh.exe`.

**Comment by mehmetakifaksoy** [comment]
If you are using openssh for windows you can go to this path and after run on the cmd on administrator It works!
