### ISSUE TITLE
make it possible to use a custom settings.json in a command line argument

### ISSUE THREAD

**Issue by jmlucjav** [microsoft/terminal#9146]
# Description of the new feature/enhancement

Make it possible to use a custom settings.json in a command line argument (being different to the default one on disk). My use case: I have my settings in the default file for when I use the terminal as a terminal. But I also use wt to host neovim (with the TUI, so no GUI). When I use it like that, I would like to set some settings I want to keep in the general case (disable mutiple lines pasted etc).

# Proposed technical implementation details (optional)

Add an arg to explicitly set a custom setttings.json, then that setttings is preferred.

**Comment by Don-Vito** [comment]
@jmlucjav - please see if #6687 already covers your idea.

**Comment by jmlucjav** [comment]
yeah what is is asked in #6687 is exactly what I meant (it didn't show up in my searches). You can close this as dup.
