### ISSUE TITLE
Undo function for closing tabs and windows.

### ISSUE THREAD

**Issue by mingwandroid** [microsoft/terminal#9147]
# Undo feature for closing tabs and windows.

# Proposed technical implementation details (optional)

**Comment by KalleOlaviNiemitalo** [comment]
There is a long discussion about similar features in <https://github.com/microsoft/terminal/issues/961>.

**Comment by mingwandroid** [comment]
OK, that issue talks about "restoring" state which is very complicated. My idea is to side-step this by not actually killing anything during this grace-period. I will add the idea over there though if you think them related. I wouldn't personally touch "restoring" state as something I would want to implement.

**Comment by Don-Vito** [comment]
@mingwandroid, @KalleOlaviNiemitalo  - I think you are off by one :smile:. Please see https://github.com/microsoft/terminal/issues/960

**Comment by zadjii-msft** [comment]
Okay yea, this is definitely #960. The set of #960, #961 and #766 are all super closely related, so I don't fault anyone for getting them mixed up 😄 

/dup #960
