### ISSUE TITLE
Let the user save tabs when closed

### ISSUE THREAD

**Issue by zurgeg** [microsoft/terminal#9149]
# Description of the new feature/enhancement

Currently, Windows Terminal does not save tabs when closed. This can be quite annoying when you are trying to remember what you were working on earlier. This could be helpful, if say, a user had a piece of Command Prompt code they kept going back to, and didn't want to lose it. Additionally, it could also help the user remember their tab layout (this would be especially helpful for me, who puts my PC into Hibernate and uses Keyboard shortcuts to switch between tabs **a lot**)

**Comment by j4james** [comment]
Have a look at issue #766. Is that the same functionality you're requesting?

**Comment by zurgeg** [comment]
Yes. I will close.
