### ISSUE TITLE
Where is the source from which the MUX package in the repo is built?

### ISSUE THREAD

**Issue by fghzxm** [microsoft/terminal#915]
I have to make experimental changes to the MUX package used by the Terminal.  `deps/packages/README.md` only mentions it is built from a custom branch, but _where_ is that branch?

**Comment by zadjii-msft** [comment]
That package is actually built from [microsoft/microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml) I believe. I don't think the tab control is actually in their master yet. I don't know for sure, but I'd guess it's one of these two branches:
![image](https://user-images.githubusercontent.com/18356694/58099954-52779d80-7ba2-11e9-8ba0-345533df2f56.png)

@teap who might be able to help more.
