### ISSUE TITLE
Over SSH, vim configuration for cursor shape is not respected

### ISSUE THREAD

**Issue by Melandel** [microsoft/terminal#9154]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.804]
Windows Terminal version: 1.5.10411.0
```

# Steps to reproduce

* Open a powershell tab inside Windows Terminal
* `ssh` another Windows machine 
  * that has the latest vim version
  * and the following vim configuration content:
  ```
    let &t_ti.=" \e[1 q"
    let &t_SI.=" \e[5 q"
    let &t_EI.=" \e[1 q"
    let &t_te.=" \e[0 q"
  ```
* run `vim` over ssh on that machine

# Expected behavior

* The vim configuration for cursor shape **is** respected, ie:
  * The cursor has a blinking box shape in Normal mode
  * The cursor has a blinking bar shape in Insert mode

# Actual behavior
* The vim configuration for cursor shape is **not** respected
* Instead, the cursor always has the shape defined in local Windows Terminal's settings file

# Additional note
* The vim configuration is correctly respected if I use vim without ssh

**Comment by skyline75489** [comment]
What specific SSH client are you using? If you're using the SSH client provided by Windows itself, you may need to switch to a newer version at https://github.com/powershell/Win32-OpenSSH

**Comment by Melandel** [comment]
* The SSH client I'm reproducing the issue with: `OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`
* The SSH client downloaded from your link: `OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2`

Using the latter, I can still reproduce the issue

**Comment by zadjii-msft** [comment]
Weird. This definitely doesn't repro in WSL locally, so I'm guessing that this is definitely a openssh issue. I don't have a remote machine handy to ssh into to confirm unfortunately. I'd file a bug upstream on https://github.com/PowerShell/Win32-OpenSSH/issues, to see if they can verify.
