### ISSUE TITLE
Terminal will not honor to seperate PowerShell 7.2 preview x86 or x64 in UI / JSON

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#9155]
# Environment

```none
Windows build number: Windows 10 b21131
Windows Terminal version (if applicable): Terminal / Terminal preview (as current at 13 Feb. 2021)
Terminal: 1.5.1411.0
Terminal Preview: 1.6.10412.0
```

Any other software?
[PowerShell Preview 7.2  Preview 2 x86 MSI](https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.3/PowerShell-7.2.0-preview.2-win-x86.msi)
[PowerShell Preview 7.2 Preview 3 x64 MSI](https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.3/PowerShell-7.2.0-preview.3-win-x64.msi)

Does not affect Powershell 7.1 release x86 / x64

# Steps to reproduce

Have Terminal / Terminal Preview and PowerShell 7.2 preview 2 x86 installed via MSI. 
Install PowerShell 7.2 preview 3 x64 installed via MSI. 

# Expected behavior

Terminal should detect 2 instances of PowerShell 7.2 Preview and implement it in new shell dropdown with the specific architecture like PowerShell 7.2 Preview 2 (x86) and  PowerShell 7.2 Preview 3 x64

# Actual behavior

It will only detect the first Powershell  7.2 

# Proposal for technical implementation:

you can check the version in get-childitem version string, when generating / updating the json
you can check the programfiles path of the pwsh.exe to determine the architecture and add it to the caption.

**Comment by DHowett** [comment]
Curious! We do actually enumerate the instances in the `Program Files (x86)` directory and assign them separate names.

Can you share your settings.json? It should contain a couple generated profile snippets.

My menu looks like this after I install the cross-architecture x86 version alongside preview and stable:

![image](https://user-images.githubusercontent.com/189190/107866122-18443a00-6e22-11eb-87ea-f882b815d64d.png)


```
            {
                "guid": "{a3a2e83a-884a-5379-baa8-16f193a13b21}",
                "hidden": false,
                "name": "PowerShell 7 Preview",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{d6ebd50a-738a-58da-95a8-41e7782f6f7e}",
                "hidden": false,
                "name": "PowerShell 7 Preview (x86)",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            },
```

(commandlines are, of course, autogenerated.)

```
PS> gci \program` files,\program` files` `(x86`)  -filter pwsh.exe -recu | select -exp fullname
C:\Program Files\PowerShell\7\pwsh.exe
C:\Program Files\PowerShell\7-preview\pwsh.exe
C:\Program Files (x86)\PowerShell\7-preview\pwsh.exe
```

**Comment by Karl-WE** [comment]
I have to review this.

**Comment by Karl-WE** [comment]
Hi @DHowett I have tested it again with same PShell versions installed preview and release in x64 and x86

Cannot repro in 
Windows Terminal v1.5.10411.0
Windows Terminal Preview v1.6.10412.0

![image](https://user-images.githubusercontent.com/45657752/108487169-3df89580-729f-11eb-951f-ae36b88e5d18.png)
