### ISSUE TITLE
Fine-grained DWrite text analysis based on text complexity

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#9156]
# Description of the new feature/enhancement

Inspired by https://github.com/microsoft/cascadia-code/issues/411, certain ASCII characters sometimes break the simplicity of the entire text, depending on the font being used. The current implementation skips dwrite analysis when the entire text is simple:

```cpp
if (!_isEntireTextSimple)
{
    // Call each of the analyzers in sequence, recording their results.
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeLineBreakpoints(this, 0, textLength, this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeBidi(this, 0, textLength, this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeScript(this, 0, textLength, this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeNumberSubstitution(this, 0, textLength, this));
    // Perform our custom font fallback analyzer that mimics the pattern of the real analyzers.
    RETURN_IF_FAILED(_AnalyzeFontFallback(this, 0, textLength));
}
```

With for example `Fira Code`, in most cases the optimization only applies to lines with 120 spaces, which is not good.

# Proposed technical implementation details (optional)

`GetTextComplexity` can provide a breakdown report of the text, showing which specific range of the text is simple, we should be able to utilize it like this:

```cpp
for (auto range : complexRanges)
{
    // Call each of the analyzers in sequence, recording their results.
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeLineBreakpoints(this, range, this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeBidi(this, range , this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeScript(this, range , this));
    RETURN_IF_FAILED(_fontRenderData->Analyzer()->AnalyzeNumberSubstitution(this, range, this));
    // Perform our custom font fallback analyzer that mimics the pattern of the real analyzers.
    RETURN_IF_FAILED(_AnalyzeFontFallback(this, range));
}
```

See #6695 for the introduction of text complexity analysis.

**Comment by skyline75489** [comment]
This should also help users who use non-English locales, for example avoid analyze entirely:

`版权所有 (C) Microsoft Corporation。保留所有权利。`

**Comment by skyline75489** [comment]
I've done some experiment and I found that the text complexity is not the same as run splitting. For example with the following text:

版权所有 (C) Microsoft Corporation。保留所有权利。

The text complexity analysis reports (a, b is pos, length pair) :

* 0, 4: Complex
* 4, 26: Simple
* 30, 8: Complex
* 38, 70: Simple

The run analysis split it into the following runs:

* 0, 6
* 6, 25
* 31, 77

We might also need some sort of RLE implementation to find it a run is entire simple and then optimize the shaping process for the run.

**Comment by miniksa** [comment]
I agree that we should make use of the additional analysis information to improve performance in this way.

I do think that we could just further split the `Run`s and give them an additional simple-or-not parameter (`bool`) during the initial `_AnalyzeTextComplexity` that is just picked up during `_AnalyzeRuns` to determine the full analysis or skip and again during `_ShapeGlyphRuns` to determine the quick-mapping or slow-mapping to glyphs. In lieu of the whole thing being simple, a `Run` would be simple or not.

I'm not quite sure why your example maps as it does. Are some of those characters UTF-16 surrogate pairs?

**Comment by skyline75489** [comment]
those are just normal Chinese characters. Originally I thought text complexity analysis would split the text the same way as run splitting. Just want to add an example to show that it’s not. 

>  a Run would be simple or no

This is likely undetermined. In the example above:

“版权所有 (”

This is a Run. But according to text complexity, the first 4 characters are complex, the last 2 characters are simple. This is what frustrates me. We can’t just simply know a Run is simple or not easily and optimize based on that.

**Comment by miniksa** [comment]
Yeah but what I'm saying is that we can just call `_SetCurrentRun` and `_SplitCurrentRun` inside of `_AnalyzeTextComplexity` when we start listening to the length of the complexity and add the additional data.

So then you have a [0,4) complex run. [6,8) simple run. [8, 26) simple run. etc. etc.

**Comment by skyline75489** [comment]
Doesn’t that bring more fragmentation into the process? Will it affect the line breaking and script analysis result? I need to dig more into this...

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Michael Niksa <notifications@github.com>
发送时间: Wednesday, February 17, 2021 8:23:00 AM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/terminal] Fine-grained DWrite text analysis based on text complexity (#9156)


Yeah but what I'm saying is that we can just call _SetCurrentRun and _SplitCurrentRun inside of _AnalyzeTextComplexity when we start listening to the length of the complexity and add the additional data.

So then you have a [0,4) complex run. [6,8) simple run. [8, 26) simple run. etc. etc.

―

**Comment by miniksa** [comment]
To your questions: oh probably. It's worth a try though to see if it just works. Sometimes the simple answer is "good enough". If it turns out to not be, we can refine further from there. Feel free to try/dig!

**Comment by skyline75489** [comment]
Can we reopen this?  #9202 was reverted.

#10036 is a unsuccessful attempt to patch #9202.

**Comment by lhecker** [comment]
AtlasEngine does this! 💖
