### ISSUE TITLE
[bug] Cannot use different styles of Input Mono font

### ISSUE THREAD

**Issue by WojciechThomas** [microsoft/terminal#9157]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.5.10411.0
```

# Steps to reproduce

Use any editor to configure **fontFace** setting.

# Expected behavior

Accept different versions of Input Mono font, e.g.:
```none
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "fontFace": "Input Mono Narrow"  // or Condensed or Compressed
        },
```

# Actual behavior

With font faces different than "Input Mono" Terminal falls back to Consolas font.
![image](https://user-images.githubusercontent.com/15376250/107875447-2ba5e280-6ec0-11eb-9665-9ad6c2782f38.png)

With "Input Mono" font everything works correctly:
![image](https://user-images.githubusercontent.com/15376250/107875496-96efb480-6ec0-11eb-9165-dfba72ce6a8e.png)

**Comment by skyline75489** [comment]
I've tried installed all 3 variants of Input Mono:

![image](https://user-images.githubusercontent.com/4710575/108460032-bae13a80-72b2-11eb-88d4-bc35510e6766.png)

The DWrite API actually reports that `Input Mono Condensed` does not exist in the system. However `Input Mono` does exist. @zadjii-msft @DHowett any idea why this is happening?

**Comment by epyonavenger** [comment]
It's not just "Input Mono", the same behavior can be seen with Hack. I normally use "Hack Regular", but since the update that falls through to Consolas.

**Comment by DHowett** [comment]
It's more probable that since the update it _tells you_ that it fell back to Consolas. That error dialog is hooked up to the renderer actually failing to find the font, even after it's tried a couple different ways. It was perhaps never working properly, and the dialog only now alerts you to that fact. :smile:

**Comment by epyonavenger** [comment]
Well, it was definitely using Hack Regular at some point, though to your point, it's possible it was never quite right, and only now is it notifying me. Still, I'd trade not being notified for using the right font again. 🤔

**Comment by zadjii-msft** [comment]
This looks like a real bug, but I've got no idea why this isn't working. I'll stick it in 2.0 - we'll figure it out eventually 😄

**Comment by derekslenk** [comment]
Hmm - this has been making Windows Terminal unusable. So much for WSL

**Comment by Diablo-D3** [comment]
The workaround, currently, is *only* install the variant of Input you want. This works in Windows Terminal but not other apps.

Whatever Input Mono is doing on the prebuilt versions also confuses Alacritty (it can't find Input Mono unless the regular width variant is installed; it can't see any others, and using ex: "Input Mono Narrow" can't find narrow (et al.) either.

**Comment by derekslenk** [comment]
If you use oh-my-posh, it seems to download and install the fonts correctly

**Comment by falleng0d** [comment]
![Screenshot1853](https://user-images.githubusercontent.com/3948733/201119405-55ce4903-20a5-47e9-a4bc-3af3ed379b0a.png)
Font is recognized in other apps and it has a lot of weights such as "compressed" that are not recognized by windows terminal

**Comment by DHowett** [comment]
Huh, thanks! I believe that "Compressed" (like "Condensed") is a name for the _width_ axis, not the _weight_ axis.

You can use custom font axes like [width (`wdth`)](https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth) by adding an `"axes"` field to your `"font"` like this:

```jsonc
"font": {
    "axes": {
        "wdth": 100 // Width axis; 100 is regular width; values range from 0 to (unknown)
    }
    ...
}
```

**Comment by DHowett** [comment]
For font names that contain axis tags in general, we're tracking that in /dup #9744 (because it has more technical information on the problem, even though it is a newer issue than this one). Some preliminary work was done in #10777, but it proved difficult to work into our font selection engine at the time. We're in a better place now :smile:

That having been said, please subscribe to #9744 for updates. In the meantime, you can use the `axes` override to specify specific widths.
