### ISSUE TITLE
Windows terminal installation from microsoft store is not working after being crashed by McAfee antivirus.

### ISSUE THREAD

**Issue by vksdev** [microsoft/terminal#9159]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): latest store version

Any other software?
```

# Steps to reproduce

# Expected behavior

Terminal opens normally.

# Actual behavior

![windowsterminalerr](https://user-images.githubusercontent.com/54206239/107877734-34181080-6ef4-11eb-95a5-ce052962c6ef.jpg)

I have been using Windows Terminal installed from Microsoft Store for a long time now. Just today McAfee crashed running windows terminal and added some file from AppData folder in quarantined items, which I have deleted from that list, so that I can fresh install windows terminal form store.

I have tried installing terminal several times but it do not work. If gives me error as shown in above image.

How will I be able to reinstall Windows Terminal from Microsoft Store?

**Comment by zadjii-msft** [comment]
The Store has been working in mysterious ways as of late:
* #9017
* #7188
* #9062
* #9138

All these are similar, but I don't think we've got a single root cause narrowed down.

**Comment by zadjii-msft** [comment]
Can you try repairing the Terminal app?

![image](https://user-images.githubusercontent.com/18356694/109302106-7861b580-77fe-11eb-8f4f-9517365e3fb5.png)


Some internal users reported a measure of success with that. I have no idea how that'll interact with McAfee though

**Comment by vksdev** [comment]
I have tried that many (repair, reinstall and repair) times, it changes nothing for me.

**Comment by vksdev** [comment]
I installed latest version from store just now and it is working fine for now. 😀

**Comment by zadjii-msft** [comment]
Well. That's annoying that the repro is gone before we could figure it out. But I'm glad that it's fixed! I still have no idea what might have caused this. I suppose I'll keep my eyes open for future reports.

Thanks!
