### ISSUE TITLE
The "Rename tab" action removes focus from terminal 

### ISSUE THREAD

**Issue by ArturGudiev** [microsoft/terminal#9160]
# Environment
Windows 10.0.18363.0

# Steps to reproduce
1. Add the hotkey for the "rename tab" action in the settings
`{ "command": "openTabRenamer", "keys": "ctrl+alt+r" },`

2. Rename a tab using this hotkey 

# Expected behavior
A tab is renamed. The focus is still in the terminal. 

# Actual behavior
A tab is renamed. The focus is on the tabs panel.

![1](https://user-images.githubusercontent.com/4563342/107885804-5cf8cf80-6f0d-11eb-80f9-3a761f34a33f.png)

**Comment by Don-Vito** [comment]
@ArturGudiev - I see you got the newer version in the end :blush:
@zadjii-msft - actually the bug is wider, for some reason the focus doesn't return to the terminal, no mater if renamer is opened with shortcut or by clicking.

**Comment by ArturGudiev** [comment]
@Don-Vito Yes🙂
But I ran into this problem only when I pressed the hotkey.

**Comment by zadjii-msft** [comment]
@Don-Vito Oh don't you worry, the problem is _even wider_. If you wanna be sad, go ahead and check out #6680
