### ISSUE TITLE
Settings UI removes comments in settings.json

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/terminal#9167]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.6.10412.0
```

# Steps to reproduce
Open the settings UI `settingsUI`, make some changes, *save*

# Expected behavior
I would assume that the `settings.json` is just changed with new values. Whatever is changed is written.

# Actual behavior
It seems that the settings are completely rewritten by the `settingsUI` - meaning my order of things in the json is completely gone and more importantly *some* comments are gone. I'm playing around with different fonts for example and the section looked like this:

```
"defaults": 
        {
            //"fontFace": "Cascadia Code",
            "fontFace": "CaskaydiaCove NF"
        },
```

After saving with the settings UI, the commented out `fontFace` is gone. The same behavior I observed for `colorScheme` within the list of profiles. Other comments are still there (e.g. in the `keybindings` section)

**Comment by Don-Vito** [comment]
There is a discussion about similar problems here: https://github.com/microsoft/terminal/issues/8991.
Probably worth adding this issue there as well.

**Comment by DennisGaida** [comment]
Good link, I tried to find a related issue before. My "removing comments" issue isn't addressed in the original issue though.

**Comment by DHowett** [comment]
/dup #8991 these are all part of the same umbrella of issues -- we don't have good "in-place" editing for the settings file. thanks for bringing this up!

(We re-serialize the entire document, but since the settings UI doesn't support key bindings we just move that part of the serialization tree over from the original... this is why comments remain with bindings but nothing else.)

**Comment by DennisGaida** [comment]
@DHowett thanks for the additional information. This is how you close an issue. I'll follow #8991 closely.
