### ISSUE TITLE
add pbcopy and pbpaste support

### ISSUE THREAD

**Issue by hirschnase** [microsoft/terminal#9168]
pbcopy and pbpaste is a way to interact with the operating system clipboard on the command line. It allows the user to add something to the clipboard by using Linux pipes or reading a file content from STDIN, etc.. There is an implementation for MacOS and Linux (using xclip / xsel) but no way to make this work for Linux under Windows using the Terminal application.

It would be great to have a similar functionality in the terminal application!

For a brief description, please have a look at https://medium.com/@codenameyau/how-to-copy-and-paste-in-terminal-c88098b5840d

**Comment by DHowett** [comment]
Thanks for the request! I'm sorry -- while we're the best place to request this, we're probably not going to ever implement it. This is something a third-party developer can nail better/faster than us (given that for commandline tools, we are tied to the Windows release cycle.) I wish that weren't the case :smile:


Also, we have `CLIP` (it only works one-way though :()

**Comment by ms4720** [comment]
scoop extras bucket has pasteboard, pbcopy and pbpaste clone
