### ISSUE TITLE
There's still a problem in the post-compile commands.

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#917]
There's still a problem in the post-compile commands.

Some paths are unquoted, i was able to fix it like this.

![image](https://user-images.githubusercontent.com/23284823/58079867-4b588b80-7bb2-11e9-8331-f737a42f9178.png)
![image](https://user-images.githubusercontent.com/23284823/58079882-54495d00-7bb2-11e9-8a37-b2f82d7d5761.png)

_Originally posted by @zugazagoitia in https://github.com/microsoft/terminal/issues/438#issuecomment-494291345_

**Comment by dipzzzz** [comment]
Are you using python compiler to execute this code? I think you are using visual Studio and hence you are getting problem in post compile commands

**Comment by dipzzzz** [comment]
Use pycharm or run from terminal

**Comment by dipzzzz** [comment]
Where are you executing this code? Terminal?

**Comment by DHowett-MSFT** [comment]
@zugazagoitia it looks like you've got a fix for this. Would you mind submitting a pull request?

**Comment by flynnham** [comment]
I think it might be a better solution to just tell people in the readme to have the source code within a non-spaced path. I tried this in reverse (added the quotes and then attempted to move the repo to `C:\dev\terminal), and I still get this error.

Looks like there is something else that's escaping the quotes when it's being passed through.
