### ISSUE TITLE
Can "Cascadia Code PL" and "Cascadia Mono PL" be installed by default?

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#9170]
# Description of the new feature/enhancement

Add "Cascadia Code PL" and "Cascadia Mono PL" with the Windows Terminal package.  This saves an extra installation step for users.  Especially since it gets updated regularly and there's no "Windows Update" for Cascadia Code fonts.

# Proposed technical implementation details (optional)

Add "Cascadia Code PL" and "Cascadia Mono PL" with the Windows Terminal package

**Comment by DHowett** [comment]
We're actually trying to get away from Cascadia being shipped by default, too, so we're not planning on adding _yet more_ fonts to the package. I'm sorry.
