### ISSUE TITLE
No possibility to copy in windows terminal which is a blocker

### ISSUE THREAD

**Issue by JeroenDronkers** [microsoft/terminal#9172]
# Environment
Windows 10

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Try to copy text in WIndows terminal. It is not possible

# Expected behavior
The possibility to copy text

# Actual behavior
Copy text not possible

**Comment by trajano** [comment]
The default key bindings are Ctrl-Shift+C and Ctrl+Shift+V for copy and paste.  You can alter it 

See my gist for example
https://gist.github.com/trajano/24f4edccd9a997fad8b4de29ea252cc8#file-settings-json-L112-L121

**Comment by zakaryan2004** [comment]
Right click will also work for both copy AND paste, so you can select a text, right click, select the command line(or whatever input field you have) and right click again, and get the text pasted.

**Comment by trajano** [comment]
@zakaryan2004  thanks for the tip, I didn't know about that feature.  I'm used to having right click to paste from CMD days.  Though my old habit with CMD terminal which is to press `enter` for copy which actually made me raise this bug https://github.com/microsoft/terminal/issues/9177

**Comment by DHowett** [comment]
Looks like this was answered? Th
anks!
