### ISSUE TITLE
Hard to differentiate active/inactive dark theme tabs 

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#9173]
I only have a few tab based apps, namely the browsers, text editor and Windows Terminal.  However, the way they render tabs specifically the colors differ and it's not really usable in Windows Terminal

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): Version: 1.5.10411.0

Edge
Firefox
```

# Steps to reproduce

Use Dark Mode in system settings
Set accent color
![image](https://user-images.githubusercontent.com/110627/107977141-a76b6200-6f88-11eb-84ba-0907abe176d3.png)

Open multiple tabs

# Expected behavior

Color consistency between tabs on the app

Edge accent color is blue and the active tab is black so it's distinguishable.

![image](https://user-images.githubusercontent.com/110627/107977087-8d318400-6f88-11eb-8a11-fb737efd693d.png)

Firefox looks similar I like the bar on top but I guess that's a custom firefox implementation  HHowever it still takes the accent color correctly.

![image](https://user-images.githubusercontent.com/110627/107977248-cb2ea800-6f88-11eb-90be-3abd5be57083.png)

# Actual behavior

The dark mode tabs are hard to distinguish in Terminal when active.  

![image](https://user-images.githubusercontent.com/110627/107977281-d71a6a00-6f88-11eb-8be8-479d01c8496d.png)

Light mode is at least distinguishable.

![image](https://user-images.githubusercontent.com/110627/107977318-e4375900-6f88-11eb-99a3-b24609d3ccf6.png)

**Comment by DHowett** [comment]
I think we have an issue for this sitting around somewhere, but I am worried that you have a display contrast issue. The contrast ratio for the dark theme in your screenshots is 1.66:1, and the contrast ratio for the light theme is 1.6:1. They're very much _extremely the same_ distinction between selected/unselected.

You might be interested in #3327, which would let you specify that the titlebar have an accent color background (like Firefox in your screenshot above.)
