### ISSUE TITLE
Allow "vintage" cursor to have values lower than 25

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#9175]
# Description of the new feature/enhancement

Allow "vintage" cursor to have values lower than 25, it is presently capped between 25 to 100.  I just want to have the capability of setting it to a smaller value that is larger than `underline`

# Proposed technical implementation details (optional)

Remove the bottom limit and allow floating point values.

**Comment by DHowett** [comment]
The vintage cursor is intended to provide compatibility with folks' expectations of the windows console. It's not meant to be a good fun and expressive cursor for people to personalize with. What specifically are you looking for? Why do you want this capability?

> and allow floating point values

So, you want a cursor with a fractional percentage height? I'm gonna say _no_ to that one.

**Comment by trajano** [comment]
Well can you at least make it allow 1-24?

**Comment by zadjii-msft** [comment]
I guess I don't see why not

**Comment by maggch97** [comment]
![vintage](https://user-images.githubusercontent.com/23057110/109766102-b1e85580-7c30-11eb-913f-e0e6f28d9ebb.gif)

Windows Terminal Preview v1.7.572.0

allowed input range may be too large

**Comment by zadjii-msft** [comment]
Mmmm nope, this _wasn't_ closed by #9370. We still need to update `_drawCursor` in `CustomTextRenderer.cpp` to allow `MinCursorHeightPercent` to be `1`
