### ISSUE TITLE
Pressing `enter` when there's a selection should just copy and not pass the `enter` key.

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#9177]
Pressing `enter` when there's a selection should just copy and not pass the `enter` key.
Workaround:

```
{ "command": {"action": "copy", "singleLine": false }, "keys": "enter" },
```

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Select some text on the terminal
Press the enter key

# Expected behavior

Clear the selection and copy the selected text to clip board
nothing else

# Actual behavior

Clear the selection and copy the selected text to clip board
Enter key gets passed to the terminal

**Comment by DHowett** [comment]
You can bind `enter` to `copy` in your personal key bindings (in your settings file)!

**Comment by astral-sa** [comment]
If I may, why is that binding not part of the default configuration to more closely mirror cmd.exe/powershell behavior? It certainly feels like a loss of functionality (or some kind of bug) when someone initially tests Windows Terminal after having used cmd.exe/powershell.
