### ISSUE TITLE
command palette should recognize profiles directly

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#9180]
# Description of the new feature/enhancement

Right now it is too difficult to open a new tab with a specific profile using the command palette. These are currently the keystrokes, you need to type:

- `Ctrl+Shift+P`
- `..` (the "New Tab..." item is now selected, which luckily happened to be alphabetically the top item for that search string)
- `Enter` to activate that "New Tab" command.

At this point you get a list of the profiles, that you can select and open.

For me, this is too cumbersome, so to open a new tab a non-current profile I always use the mouse and never use the command palette. The "New Tab, profile index: X" entries don't really help either. I can't remember what number is what profile on what machine. And since all the entries with the names of the profiles are in nested/submenus there is no way that typing a part of the profile name would show them in the command palette.

The command palette should help me, to do the common tasks quickly and opening a new tab with a certain profile is my most used task. On a normal day I have at least 3 tabs open from different profiles (Ubuntu, Git Bash, VS 2019 Developer CMD)

In the ideal world, I would press `Ctrl+Shift+P`, type a part of the profile name and the "New Tab" of that profile would be the first entry shown, the three "split pane" entries would be underneath that.

_Disclaimer_: I can't imagine this hasn't been requested before. I searched the issues, but couldn't find any issue. I probably missed some keywords while searching.

**Comment by skyline75489** [comment]
I think we have a fuzzy-search request somewhere but it might not be what you expect. 

Generally I think this is a good idea.

**Comment by zadjii-msft** [comment]
So we actually explicitly decided not to have the profiles pollute the top level of the command palette by default. Some users might just have a _lot_ of profiles, and if we're adding top level "new tab" actions for each profile, should we also add actions for "split pane" with each profile? It just made more sense to group the commands by the action first, then nest the profiles under that. 

That being said, you can totally customize how the command palette is laid out. Right now we're building the "New Tab... > [profiles]" entries with the following:

```jsonc

        {
            // New tab...
            "name": { "key": "NewTabParentCommandName" },
            "commands": [
                {
                    "iterateOn": "profiles",
                    "icon": "${profile.icon}",
                    "name": "${profile.name}",
                    "command": { "action": "newTab", "profile": "${profile.name}" }
                }
            ]
        },
```

That's what creates the nested entries. If you wanted to add the profiles as a top-level entry, you could instead add the following:
```json
{
    "iterateOn": "profiles",
    "icon": "${profile.icon}",
    "name": "New tab with profile: ${profile.name}",
    "command": { "action": "newTab", "profile": "${profile.name}" }
}
```

Is that more what you're looking for?

**Comment by ffes** [comment]
> So we actually explicitly decided not to have the profiles pollute the top level of the command palette by default.

Not sure why it would pollute the command palette. When you start to type it shortens very quickly to the entries that match your query. VS Code has way more commands (especially with extensions installed) and their command palette works great.

But since you said this was the decision the team made, I guess we'll have to live with it. Thankfully you made it configurable. I was unaware of that.

> If you wanted to add the profiles as a top-level entry, you could instead add the following

That works great! I tweaked it a bit, put two more blocks with split horizontally and split vertically. Now finally the command palette adds value for me!

IMHO this should be the default (let's agree to disagree :wink:), at least mentioned in the docs. I'm considering adding this to the docs myself, but English is not my native language, so I'll have to see how far I will get with that.

**Comment by zadjii-msft** [comment]
Okay great! Glad I could help. Theoretically this could be added as a tutorial on the docs site, so I'll file a follow up on the docs rep for that.

**Comment by schuebel** [comment]
Is there a way to assign a shortcut that directly opens the "New Tab..."  menu? Adding "keys": "ctrl+alt+t" in the settings.json did  not seem to work. 

```
{
   // New tab...
   "name": { "key": "NewTabParentCommandName" },
   "commands": [
       {
           "iterateOn": "profiles",
           "icon": "${profile.icon}",
           "name": "${profile.name}",
           "command": { "action": "newTab", "profile": "${profile.name}" }
       }
   ],
   "keys": "ctrl+alt+t"
},

```

**Comment by BWWIT** [comment]
Are you adding this in the `actions` section in the settings file?
And how does the complete command-element look like, I tried this but it didn't work:
```
{
        "command": 
        {
		"iterateOn": "profiles",
		"icon": "${profile.icon}",
		"name": "New tab with profile: ${profile.name}",
		"command": { "action": "newTab", "profile": "${profile.name}" }
	},
        "keys": "ctrl+o"
}
```

**Comment by BWWIT** [comment]
> That works great! I tweaked it a bit, put two more blocks with split horizontally and split vertically. Now finally the command palette adds value for me!
> 
@zadjii-msft: Will you share your settings element(s)? :-)

**Comment by zadjii-msft** [comment]
Sorry, which elements are you looking for?

**Comment by BWWIT** [comment]
Ups, wrong tagging, it should have been "ffes", sorry.
But he wrote above
"That works great! I tweaked it a bit, put two more blocks with split horizontally and split vertically. Now finally the command palette adds value for me!"
I assume he's talking about some elements in the json-settings-file he made.

**Comment by zadjii-msft** [comment]
Probably something like:

```json
{
    "iterateOn": "profiles",
    "icon": "${profile.icon}",
    "name": "New tab with profile: ${profile.name}",
    "command": { "action": "newTab", "profile": "${profile.name}" }
},
{
    "iterateOn": "profiles",
    "icon": "${profile.icon}",
    "name": "Split ${profile.name} vertically",
    "command": { "action": "splitPane", "profile": "${profile.name}", "split": "vertical" }
},
{
    "iterateOn": "profiles",
    "icon": "${profile.icon}",
    "name": "Split ${profile.name} horizontally",
    "command": { "action": "splitPane", "profile": "${profile.name}", "split": "horizontal" }
}
```

**Comment by ffes** [comment]
@zadjii-msft is absolutely right.

I even wrote a blogpost about it, back in the day: https://www.fesevur.com/2021/02/17/windows-terminal-command-palette/
Today I added an update to the blogpost.

**Comment by BWWIT** [comment]
> @zadjii-msft is absolutely right.
> 
> I even wrote a blogpost about it, back in the day: https://www.fesevur.com/2021/02/17/windows-terminal-command-palette/ Today I added an update to the blogpost.

NICE! Thank you very much for effort, it works perfectly :-)
