### ISSUE TITLE
Make Features/Shortcuts More Visible

### ISSUE THREAD

**Issue by opticyclic** [microsoft/terminal#9181]
# Description of the current difficulty

I accidentally pressed `Alt-Shift-D` thinking it would open the Settings UI (currently in preview).
I had previously put the recommended value in the settings.json at the bottom so a quick glance at the last value showed this shortcut.
Obviously this is wrong as it is the shortcut to split the pane; but I couldn't work out what was correct nor how to close the split pane.
I opened the settings.json again to look for the correct value to open the settings ui when I coincidentally saw `// To learn more about panes, visit https://aka.ms/terminal-panes`

Scrolling to the end of that web page I found the way to close the pane.

This is quite a cumbersome way to work out how to use the application.

# Description of the new feature/enhancement

Add an easier way to find out how to use the application _within_ the application rather than having to open a browser and read a large page of documentation.

Suggestions:

- Add a context menu in the terminal window
- Add a context menu in the tab 
- Add a keyboard shortcut window

An equivalent of the last option in VSCode is:

> File - Preferences - Keyboard shortcuts

**Comment by zadjii-msft** [comment]
Big picture, the plan is just to have the Settings UI enabled by default, and have the keybindings all listed in there. So when you click on the settings button, you'll just get the Settings UI. 

We've also already got:
* Request: Right-click menu inside TerminalControl (w/ Copy & Paste?) #3337
* Feature Request: Context Menu for  #1912
* Feature request: Keyboard shortcut to show all keyboard shortcuts #4695

Sound good?

**Comment by opticyclic** [comment]
Sounds good.
I'm not sure how you managed to find those when I couldn't when I searched for them.

Its probably due to the wrong search terms.

**Comment by zadjii-msft** [comment]
Probably some combination of:
* Github issue search is pretty awful
* I work 40 hours a week in this repo, so I have a pretty good recollection of what things we're already tracking ☺️
