### ISSUE TITLE
Scroll-Forward last output

### ISSUE THREAD

**Issue by Ronan-Lenor** [microsoft/terminal#9186]
# Description of the new feature/enhancement

Hello,
When i scroll down with my mouse wheel i can't go beyond the last output :

![0](https://user-images.githubusercontent.com/11092781/108081652-7b77db80-7071-11eb-90da-dbf674f1431c.jpg)

But i would like to be able to go beyond upto that the last output reaching the top of the windows (max) :

![1](https://user-images.githubusercontent.com/11092781/108081688-83d01680-7071-11eb-80f2-4e668dab45d8.jpg)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22scroll+forward%22) when filing new issues. This is already being tracked by another issue on our repo - please refer to #8623 for more discussion.

/dup #8623
