### ISSUE TITLE
font render issue

### ISSUE THREAD

**Issue by Nelson-Atema** [microsoft/terminal#9199]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): Version: 1.5.10411.0

Any other software?
```

# Steps to reproduce

Open up terminal

# Expected behavior

Fonts just render normally

# Actual behavior

Im experiencing horizontal and vertical duplicating 1px line glitches in text rendering:

Last line:
![afbeelding](https://user-images.githubusercontent.com/78723987/108336348-3a4c0c80-71d4-11eb-8ff4-084d6588fc62.png)

First column:
![afbeelding](https://user-images.githubusercontent.com/78723987/108336412-4c2daf80-71d4-11eb-988e-90f69966a5b9.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4591 for more discussion.

/dup #4591
