### ISSUE TITLE
Open Windows Terminal Here as a new tab

### ISSUE THREAD

**Issue by momt99** [microsoft/terminal#9215]
# Description of the new feature/enhancement
When I click on `Open Windows Terminal Here` (`Open in Windows Terminal`) in the context menu it opens up a new instance of WT with a tab pointing to the current directory. I think this makes the multi-tab feature of WT unused (at least for me). Instead, it can open up a new tab in a running instance of WT (like web browsers).

**Comment by KalleOlaviNiemitalo** [comment]
Please see <https://github.com/microsoft/terminal/issues/7071>.

**Comment by momt99** [comment]
Duplicate of #7071
