### ISSUE TITLE
When PS is installed on a system with Windows Terminal, please default to that console.

### ISSUE THREAD

**Issue by sharpninja** [microsoft/terminal#9220]
# Description of the new feature/enhancement

From [this discussion](https://github.com/PowerShell/PowerShell/discussions/14817#discussioncomment-381959) in PowerShell.

Please allow setting WindowsTerminal to the default conhost.

# Proposed technical implementation details (optional)

Add setting to specify default conhost is WindowsTerminal.

**Comment by skyline75489** [comment]
See #492 #7414

**Comment by zadjii-msft** [comment]
Yep, this is the whole point of #492. 

/dup #492
