### ISSUE TITLE
Light mode in settings UI only

### ISSUE THREAD

**Issue by Lombra** [microsoft/terminal#9231]
# Description of the new feature/enhancement

Since my shells are all dark, it makes sense to use dark mode to get the dark title bar, however Windows' idea of dark mode design means the new settings UI is an eyesore. I would like to have the settings UI use light mode.

**Comment by zadjii-msft** [comment]
Okay, sure. I'll slap this into the megathread for "theming", #3327. Something like `settingsUi.requestedTheme: light|dark|system`. Why not.

**Comment by zadjii-msft** [comment]
> **Note**
> ## Walkthrough

* [ ] Start by adding a new Theme object for the settings UI:
  * [ ] `SettingsTheme` in `Theme.idl`, quite similar to `WindowTheme` in the same file
  * [ ] Add a single `ElementTheme RequestedTheme` to that `runtimeclass`. 
  * [ ] In `MTSMSettings.h`, define a new `MTSM_THEME_SETTINGS_SETTINGS`, again taking cues from the tab row version. The key for this one should just be `"settings"`
  * [ ] Add a `THEME_OBJECT(SettingsTheme, MTSM_THEME_SETTINGS_SETTINGS);` to `Theme.h`
  * [ ] Add the sui theme to the other places theme objects appear in Theme.cpp as well.
* [ ] Actually use this new setting
  * [ ] `MainPage::_UpdateBackgroundForMica` is probably the right place for this, as it's already trying to set the `RequestedTheme` for the settings page.
  * [ ] Instead, use the `settings.requestedTheme`, if it is set.

**Comment by zadjii-msft** [comment]
> I assume the isMicaAvailable check is there for a reason for backward compatibility?

That was introduced in https://github.com/microsoft/terminal/pull/14675. That might have more context

(it's almost 5pm here so I can take a look deeper in the morning)

**Comment by Stromlight** [comment]
> # Description of the new feature/enhancement
> 
> Since my shells are all dark, it makes sense to use dark mode to get the dark title bar, however Windows' idea of dark mode design means the new settings UI is an eyesore. I would like to have the settings UI use light mode.

I don't think dark and white mode had any good feature so far I use lots of app but I don't find it's better use then brightness.instead of dark and white mode what about adding overview of app so user can get must out of it .
