### ISSUE TITLE
The current profile in the menu is not highlighted in bold

### ISSUE THREAD

**Issue by cy6x** [microsoft/terminal#9236]
**[Default profile]** is always highlighted in bold when you open the menu, but the profile that is currently open should be highlighted.

![Screenshot](https://user-images.githubusercontent.com/73636513/108625039-aee3ad00-7459-11eb-898a-b6d5811b3cb7.png)

Stable version installed (not preview). 1.5.10411.0. [settings.json](https://github.com/cy6x/dotfiles/blob/main/wt/.config/wt/settings.json)

**Comment by DHowett** [comment]
The bold menu item is the _default_ profile.
