### ISSUE TITLE
Windows Terminal - PowerShell customization via oh-my-posh/posh-git Set-Theme error?

### ISSUE THREAD

**Issue by nihaltowfiq** [microsoft/terminal#9237]
### Windows Terminal - PowerShell customization via oh-my-posh/posh-git Set-Theme error?

I follow the exact tutorial of Microsoft link: [Link Here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup) video link: [Video Link Here](https://www.youtube.com/watch?v=lu__oGZVT98&feature=youtu.be)

I have installed Posh-Git and Oh-My-Posh: via this code -
`Install-Module posh-git -Scope CurrentUser`
`Install-Module oh-my-posh -Scope CurrentUser`

I have installed PSReadLine: via this code -
`Install-Module -Name PSReadLine -Scope CurrentUser -Force -SkipPublisherCheck`

I am also created Microsoft.PowerShell_profile.ps1 file by typing- code $PROFILE, in my PowerShell profile and copy/paste this code:
`Import-Module posh-git`
`Import-Module oh-my-posh`
`Set-Theme Paradox`

But I get this error:  

> Set-Theme Paradox
> The term 'Set-Theme' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

ScreenShot: [Screenshot of error](https://i.stack.imgur.com/hUy8j.png)

![ssss](https://user-images.githubusercontent.com/62647867/108628039-c2573e00-7482-11eb-9f4c-e8e13f403435.PNG)

**Comment by DHowett** [comment]
Thanks for letting us know. There's a bunch of discussion over in our [documentation repository](https://github.com/microsoftdocs/terminal) about this, so I'll have to redirect you there. Cheers!

**Comment by JustDre** [comment]
It seems the "Set-Theme" cmdlet was renamed to "Set-PoshPrompt".

**Comment by wys-wys** [comment]
> It seems the "Set-Theme" cmdlet was renamed to "Set-PoshPrompt".
thank you,i have solved it

**Comment by glaucia86** [comment]
Hi! Any updates about it? I've been received the same message error!

![image](https://user-images.githubusercontent.com/1631477/117228645-d529af80-adef-11eb-8dc8-5405f66b5d37.png)

**Comment by nihaltowfiq** [comment]
> Hi! Any updates about it? I've been received the same message error!
> 
> ![image](https://user-images.githubusercontent.com/1631477/117228645-d529af80-adef-11eb-8dc8-5405f66b5d37.png)

please, read the previous comment >>> It seems the "Set-Theme" cmdlet was renamed to "Set-PoshPrompt".

**Comment by iulianoana** [comment]
For anyone still struggliong with this issue use Set-PoshPrompt, as JustDre said above, followed by the -Theme option. Here is an example:
`Set-PoshPrompt -Theme pixelrobots`
I am using posh-git version 1.0.0 and oh-my-posh version 3.157.2.
Hope this helps

**Comment by sajadshafi** [comment]
> It seems the "Set-Theme" cmdlet was renamed to "Set-PoshPrompt".

Yeah it did work fine. Change "Set-Theme" to "Set-PoshPrompt"

**Comment by Wineric** [comment]
I installed the latest version of oh-my-posh i.e. if you follow the guide on [microsoft](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup) don't use the required version but let it install the latest.

**Comment by GeoBrodas** [comment]
Hey I'm getting this error, does anyone have a fix?

![image](https://user-images.githubusercontent.com/68821192/129168945-7b7b1f7c-218d-4b43-ba4e-3806af922c46.png)

**Comment by jiyulei** [comment]
> Hey I'm getting this error, does anyone have a fix?
> 
> I followed the tutorial in the Terminal docs [here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup)
> 
> ![image](https://user-images.githubusercontent.com/68821192/129168945-7b7b1f7c-218d-4b43-ba4e-3806af922c46.png)

same here

**Comment by jiyulei** [comment]
> Hey I'm getting this error, does anyone have a fix?
> 
> I followed the tutorial in the Terminal docs [here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup)
> 
> ![image](https://user-images.githubusercontent.com/68821192/129168945-7b7b1f7c-218d-4b43-ba4e-3806af922c46.png)

Hey, I had the same issue. I did `Update_Module` in Powershell, it will update the oh-my-posh module to lastest version (actually all modules, you can also update oh-my-posh only). Then i got no errors. Hope this works for you too.

**Comment by GeoBrodas** [comment]
Hey, thanks for the tip. It's working now!

**Comment by SubwayMan** [comment]
I was having the same issue as the users above me. I followed the tutorial as well. I believe this error occurs because a command given by the documentation installs an older version, see:
`Install-Module oh-my-posh -Scope CurrentUser -RequiredVersion 2.0.412`
This conflicts with the given PowerShell configuration, as it is intended for newer versions of `oh-my-posh`. The version installed by the tutorial command works if you switch from Set-PoshPrompt back to Set-Theme, although I would suggest following the advice given above - although a small correction is required, since the command is `Update-Module` instead of `Update_Module`.

**Comment by abiriadev** [comment]
I've tried all the above things,
but still some error.

```ps1
> Set-PoshPrompt -Theme Paradox

& : The term 'C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules\oh-my-posh\3.133.1\bin\posh-windows-amd64.exe'
is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At line:1 char:23
+ ... ression (@(&"C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\<username>\...ndows-amd64.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At line:1 char:19
+ ... -Expression (@(&"C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Mod ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
   keExpressionCommand
```

I don't know where the path `C:\Users\oro36\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules\oh-my-posh\3.133.1\bin\posh-windows-amd64.exe`  came from.
from what I've checked, that path doesn't exist on my device.

**Comment by abiriadev** [comment]
Strangely enough, `Set-Theme` works.

```ps1
> Set-Theme Paradox

Hi there!

It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation.
https://ohmyposh.dev/docs/upgrading


Hi there!

It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation.
https://ohmyposh.dev/docs/upgrading

(it actually printed out twice)

> Set-PoshPrompt Paradox
& : The term 'C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules\oh-my-posh\3.133.1\bin\posh-windows-amd64.exe'
```

so I went to the mentioned site, then ran `Update-Module -Name oh-my-posh -Scope CurrentUser`, but nothing changed.

after I delete forcibly the "...\OneDrive\document\WindowsPowerShell\Modules\oh-my-posh" and install `oh-my-posh` by using `choco`, it works.

I think it was just another path issue that doesn't relate to this issue.

**Comment by rjitsu** [comment]
> I've tried all the above things,
> but still some error.
> 
> ```powershell
> > Set-PoshPrompt -Theme Paradox
> 
> & : The term 'C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules\oh-my-posh\3.133.1\bin\posh-windows-amd64.exe'
> is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
> or if a path was included, verify that the path is correct and try again.
> At line:1 char:23
> + ... ression (@(&"C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\Users\<username>\...ndows-amd64.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
> At line:1 char:19
> + ... -Expression (@(&"C:\Users\<username>\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Mod ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
>    keExpressionCommand
> ```
> 
> I don't know where the path `C:\Users\oro36\OneDrive\δ¼╕∞ä£\WindowsPowerShell\Modules\oh-my-posh\3.133.1\bin\posh-windows-amd64.exe` came from.
> from what I've checked, that path doesn't exist on my device.

It works without the -Theme flag. Do this: Set-PoshPrompt Paradox

**Comment by as-if-khan** [comment]
Just use
 
```
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```
``
on  Microsoft.PowerShell_profile.ps1 file
and enjoy.

**Comment by Pipecord403** [comment]
> For anyone still struggliong with this issue use Set-PoshPrompt, as JustDre said above, followed by the -Theme option. Here is an example:
> `Set-PoshPrompt -Theme pixelrobots`
> I am using posh-git version 1.0.0 and oh-my-posh version 3.157.2.
> Hope this helps
> Set-PoshPrompt -Theme Paradox work!

**Comment by najima1** [comment]
Hey I'm getting this error, does anyone have a fix this error ?

**Comment by najima1** [comment]
Hey I'm getting this error, does anyone have a fix this error ? I'm trying fix this error since last 3 days. But i can't do this properly becouse i'm new here in this sector.
![Screenshot_2](https://user-images.githubusercontent.com/91420693/135069930-eff8f8c5-92fa-4493-bcfa-91b307dce963.png)

**Comment by zadjii-msft** [comment]
@najima1 From literally 8 comments up in this thread: https://github.com/microsoft/terminal/issues/9237#issuecomment-897701306

>  I did `Update_Module` in Powershell, it will update the oh-my-posh module to lastest version

**Comment by Guezza** [comment]
I did Update-Module in Powershell,

**Comment by Guezza** [comment]
I did Update_Module in Powershell,

**Comment by hanskoppvi** [comment]
I have tried everything of the above but nothing worked. `oh-my-posh` was the only command that my powershell would find.

What worked for my is using the following command that is in this [guide](https://ohmyposh.dev/docs/windows#replace-your-existing-prompt) (I had to use the whole path to where the themes are):
```
oh-my-posh --init --shell pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\bubblesline.omp.json | Invoke-Expression
```

Saved this in the `Microsoft.Powershell_profile.ps1` file and it works now.

I was also missing some characters so i downloaded the `cascadia-code-nerd-font` (I used chocolatey for it).
```
choco install cascadia-code-nerd-font
```
And then selected it in the windows terminal go to Settings -> Profiles -> PowerShell -> Appearance -> Font face on the windows terminal

I hope this methods helps someone!

**Comment by none-08** [comment]
> It seems the "Set-Theme" cmdlet was renamed to "Set-PoshPrompt".

THANKS A LOT )

**Comment by snowlyg** [comment]
> > For anyone still struggliong with this issue use Set-PoshPrompt, as JustDre said above, followed by the -Theme option. Here is an example:
> > `Set-PoshPrompt -Theme pixelrobots`
> > I am using posh-git version 1.0.0 and oh-my-posh version 3.157.2.
> > Hope this helps
> > Set-PoshPrompt -Theme Paradox work!



> > For anyone still struggliong with this issue use Set-PoshPrompt, as JustDre said above, followed by the -Theme option. Here is an example:
> > `Set-PoshPrompt -Theme pixelrobots`
> > I am using posh-git version 1.0.0 and oh-my-posh version 3.157.2.
> > Hope this helps
> > Set-PoshPrompt -Theme Paradox work!

It's worked!

**Comment by Maracaipe611** [comment]
I updated my ExecutePolicy to Unrestricted and then installed the Modules Again, and finally worked!
` Set-ExecutionPolicy unrestricted
Install-Module oh-my-posh -Scope CurrentUser
Install-Module posh-git -Scope CurrentUser
Set-PoshPrompt -Theme Paradox`

**Comment by gumodi35** [comment]
Segui los pasos de actualizar el ExecutionPolicy a Unrestricted y luego instale los modulos de nuevo y sigue saliendo el error 😢 

Alguna idea de como resolverlo? ❓ 
![Captura de pantalla (2)](https://user-images.githubusercontent.com/80011796/168404345-3bdb622f-753d-4011-8672-1fbe7d9344a3.png)

**Comment by EdgarIgnite16** [comment]
Hey guys! How I can update/upgrade OH-MY_POSH to the latest version?

**Comment by LeonardoCalazans** [comment]
Eu não entendo porque este aviso e o porque como admin não funciona o tema.
I don't understand why this warning and why as admin the theme doesn't work.

![image](https://user-images.githubusercontent.com/60453161/218326948-5c8a5c95-9fc3-45cf-89c9-a12f24b11916.png)

**Comment by DHowett** [comment]
Please file a bug on the Oh-My-Posh project. :)
