### ISSUE TITLE
Area-Localization: the french translation of the Settings UI is... terrible

### ISSUE THREAD

**Issue by gpotter2** [microsoft/terminal#9238]
## Brief explanation of the issue

The french translation of the settings UI is full of mistakes. I corrected a single pane  but please note the rest of the settings follow a similar pattern. Most verbs are wrongly conjugated, especially in the context of software (maybe the loc. team was not given context or something?)+ some words are just missing (see "Alt+Click d'ouvrir votre fichier default.json" ?!).

(The use of `-ez` indicates a polite, 2nd person plural meaning: All of those would mean "Please re-draw the screen... (by yourself)", "Please open your default.json file..." etc 😅)
![image](https://user-images.githubusercontent.com/10530980/108633081-9fbd2900-7472-11eb-9bb4-557c82048357.png)

I know localization are very minor issues, but it looks so dumb, it's kind of a shame. Is there a proper place to report them (likely not here.. this is a waste of your time..) ? If so, please include it in [ your .github/ISSUE_TEMPLATE/config.yml](https://github.com/microsoft/terminal/blob/main/.github/ISSUE_TEMPLATE/config.yml) file.

Meanwhile the UI works great ! Thanks for your amazing work !

**Comment by DHowett** [comment]
Thanks for this report! I'll file these on the localization team. Unfortunately for them, this _is_ the right place to file product localization bugs.

If there's anything else you can find, I would love to have you report it. I wish I could tell them, "This whole page is bad in French please revisit it", but I know they would like to have specific individual callouts.

I suspect that some of this is machine-translated.

If you wouldn't mind typing them out as strings, it would be most helpful. I'd love to transcribe them from this image, but I will almost certainly mistype any special characters you'd have to put in. :smile:

**Comment by gpotter2** [comment]
***I will update this page with the rest of the localization. Please bare with me***

| Key | String        | Tooltip           | Comment |
| ------------- |:----------:| --------:| -----:|
| `defaultProfile`      | ✔️  | Profil qui s'ouvre lorsque vous cliquez sur l'îcone "+" ou que vous utilisez le raccourci clavier "nouvel onglet".  | Wrong word order |
| `startOnUserLogin` | ✔️ | L'activation [...] | Correct except the space between L and ' |
| `launchMode` | `Par défaut`, `Maximisé`, `Plein écran`, `Focus`, `Focus maximisé` | ✔️ | Translating focus here is a mistake |
| `snapToGridOnResize` | Ajuste*r* [...] | Lorsque désactivé, la fenêtre se redimensionne sans à-coups | The current tooltip means "When disabled, the window resizes without any issues" |
| `tabSwitcherMode` | (title ok) 1. `Fenêtre séparée, dans l'ordre des derniers onglets utilisés` 2. `Fenêtre séparée, dans l'ordre de la barre d'onglets` 3. `Navigation traditionelle, sans fenêtre séparée` | ✔️ |  |
| `alwaysShowTabs` | ✔️ | Lorsque désactivé, la barre d'onglets ne s'affiche que lorsque plus d'un onglet est présent | |
| `showTerminalTitleInTitlebar` | ✔️ | Lorsque désactivé, le titre de l'application est "Windows Terminal" | |
| `toggleAlwaysOnTop` | Toujours au premier plan | ✔️ | |
| `tabWidthMode` | title: `Largeur des onglets`, 1. ✔️ 2. ✔️ 3. `Compact` | Compact réduit les onglets non actifs | Keeping "mode" here is weird. |
| `disableAnimations` | Désactiver les animations | | pane can't really be translated in context. volet is terrible |
| Title of the "Rendering" tab | Ces paramêtres permettent parfois de résoudre des problèmes, mais auront un impact sur la performance. | | must use the plural of problem for it to make sense here |
| `experimental.rendering.forceFullRepaint` | Redessine*r* l'intégralité de l'écran entre chaque trame | Lorsque désactivé, le terminal n'affiche que les modifications entre les trames | The notion of "entire" was lost in translation. Makes little sense |
| `experimental.rendering.software` | ✔️ | Lorsque activé, le terminal utilise le rendu logiciel (i.e. WARP) à la place du rendu matériel | The tooltip made 0 sense. WARP was translated by "bend" |
| Name of the "Profile - General" settings tab (currently "Couche de base") | Paramêtres par défaut | | |

I am now almost certain this was machine translated, especially because of `experimental.rendering.software` which was translated literally and makes 0 sense.

**Comment by gpotter2** [comment]
That should be all of it 😄

**Comment by DHowett** [comment]
Thank you!

**Comment by DHowett** [comment]
(When I say "thank you", I mean _wow, thank you so much. this is such a comprehensive work and I appreciate it!_)

**Comment by DHowett** [comment]
I have converted your list into the list of actual string keys in our software that are incorrect and forwarded it to the translation team. Thank you!

| Key                                                                                               | Recommendation                                                                                                                              | Comment
| -------------                                                                                     | :----------:                                                                                                                                | :-:
| Globals_DefaultProfile.HelpText                                                                   | Profil qui s'ouvre lorsque vous cliquez sur l'îcone "+" ou que vous utilisez le raccourci clavier "nouvel onglet".                          |
| Globals_StartOnUserLogin.HelpText                                                                 | Change to `L'activation`                                                                                                                    | Correct except the space between L and '                                                                                                               |
| Globals_LaunchModeDefault.Content                                                                 | `Par défaut`                                                                                                                                |                                                                                                                                                        |
| Globals_LaunchModeMaximized.Content                                                               | `Maximisé`                                                                                                                                  | Wrong translation for maximized                                                                                                                        |
| Globals_LaunchModeFocus.Content                                                                   | `Focus`                                                                                                                                     | Translating "Focus" was incorrect                                                                                                                      |
| Globals_LaunchModeMaximizedFocus.Content                                                          | `Focus maximisé`                                                                                                                            | Translating "Focus" incorrect; wrong Maximized translation                                                                                             |
| Globals_SnapToGridOnResize.Header                                                                 | Ajuste*r* [...]                                                                                                                             | Change to Ajuster with `-r`                                                                                                                            |
| Globals_SnapToGridOnResize.HelpText                                                               | Lorsque désactivé, la fenêtre se redimensionne sans à-coups                                                                                 | The current tooltip means "When disabled, the window resizes without any issues"                                                                       |
| Globals_TabSwitcherModeMru.Content                                                                | `Fenêtre séparée, dans l'ordre des derniers onglets utilisés`                                                                               |                                                                                                                                                        |
| Globals_TabSwitcherModeInOrder.Content                                                            | `Fenêtre séparée, dans l'ordre de la barre d'onglets`                                                                                       |                                                                                                                                                        |
| Globals_TabSwitcherModeDisabled.Content                                                           | `Navigation traditionelle, sans fenêtre séparée`                                                                                            |                                                                                                                                                        |
| Globals_AlwaysOnTop.Header                                                                        | Toujours au premier plan                                                                                                                    |                                                                                                                                                        |
| Globals_TabWidthMode.Header                                                                       | `Largeur des onglets`                                                                                                                       | Keeping "mode" here is weird.                                                                                                                          |
| Globals_TabWidthMode.HelpText                                                                     | Compact réduit les onglets non actifs                                                                                                       | Keeping "mode" here is weird.                                                                                                                          |
| Globals_TabWidthModeCompact.Content                                                               | `Compact`                                                                                                                                   |                                                                                                                                                        |
| Globals_RenderingDisclaimer.Text                                                                  | Ces paramêtres permettent parfois de résoudre des problèmes, mais auront un impact sur la performance.                                      | must use the plural of "problem" for it to make sense here                                                                                             |
| Globals_ForceFullRepaint.Header                                                                   | Redessine*r* l'intégralité de l'écran entre chaque trame                                                                                    | The notion of "entire" was lost in translation. Makes little sense                                                                                     |
| Globals_ForceFullRepaint.HelpText                                                                 | Lorsque désactivé, le terminal n'affiche que les modifications entre les trames                                                             | The notion of "entire" was lost in translation. Makes little sense                                                                                     |
| Globals_SoftwareRendering.HelpText                                                                | Lorsque activé, le terminal utilise le rendu logiciel (i.e. WARP) à la place du rendu matériel                                              | The tooltip made 0 sense. WARP was translated by "bend"                                                                                                |
| Profile_General.Header                                                                            | Paramêtres par défaut                                                                                                                       |                                                                                                                                                        |
| Profile_StartingDirectory.HelpText                                                                | Répertoire dans lequel le shell démarre                                                                                                     | Tech-savvy french people use the proper "shell" word in french. The Windows terminal is likely aimed at them, translating this would lose its meaning. |
| Profile_StartingDirectoryUseParentCheckbox.Content                                                | Utiliser le répertoire *du* processus parent                                                                                                |                                                                                                                                                        |
| Profile_StartingDirectoryUseParentCheckbox.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Si cette option est activée, le shell démarrera dans le répertoire duquel le terminal a été lancé.                                          |                                                                                                                                                        |
| Profile_Icon.HelpText                                                                             | Emplacement de l'image ou un emoji                                                                                                          | The tooltip says "file location to the image or to the emoji" and is misleading.                                                                       |
| Profile_TabTitle.Header                                                                           | Titre de l'onglet                                                                                                                           | Can't be translated directly (current makes 0 sense). Same idea                                                                                        |
| Profile_TabTitle.HelpText                                                                         | Si spécifié, remplace le titre du shell au démarrage.                                                                                       | Can't be translated directly (current makes 0 sense). Same idea                                                                                        |
| Profile_ColorScheme.Header                                                                        | Jeu de couleurs                                                                                                                             | Funnily enough, this was translated correctly in the tab name "Color schemes", but not here.                                                           |
| Profile_ColorScheme.HelpText                                                                      | Nom du jeu de couleurs à utiliser.                                                                                                          | Funnily enough, this was translated correctly in the tab name "Color schemes", but not here.                                                           |
| Profile_RetroTerminalEffect.Header                                                                | `Effet terminal retro` (no s)                                                                                                               | The tooltip translation was literal.                                                                                                                   |
| Profile_RetroTerminalEffect.HelpText                                                              | Lorsque activé, le terminal émulera les lignes de balayage et le flou d'un écran à tubes cathodiques                                        | The tooltip translation was literal.                                                                                                                   |
| Profile_BackgroundImage.Header                                                                    | Emplacement de l'image d'arrière plan                                                                                                       |                                                                                                                                                        |
| Profile_BackgroundImage.HelpText                                                                  | Emplacement du fichier de l'image utilisée en arrière plan.                                                                                 |                                                                                                                                                        |
| Profile_BackgroundImageStretchMode.Header                                                         | Mode d'étirement de l'image d'arrière plan                                                                                                  |                                                                                                                                                        |
| Profile_BackgroundImageStretchMode.HelpText                                                       | Définit comment l'image d'arrière plan est redimensionnée pour remplir la fenêtre.                                                          |                                                                                                                                                        |
| Profile_BackgroundImageStretchModeUniform.Content                                                 | `Uniforme`                                                                                                                                  |                                                                                                                                                        |
| Profile_BackgroundImageStretchModeUniformToFill.Content                                           | `Remplissage uniforme`                                                                                                                      |                                                                                                                                                        |
| Profile_BackgroundImageStretchModeFill.Content                                                    | `Remplissage`                                                                                                                               |                                                                                                                                                        |
| Profile_BackgroundImageStretchModeNone.Content                                                    | `Pas d'étirement`                                                                                                                           |                                                                                                                                                        |
| Profile_BackgroundImageAlignment.Header                                                           | Alignement de l'image d'arrière plan                                                                                                        |                                                                                                                                                        |
| Profile_BackgroundImageAlignmentBottom.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip     | En bas                                                                                                                                      |                                                                                                                                                        |
| Profile_BackgroundImageAlignmentTop.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip        | En haut                                                                                                                                     |                                                                                                                                                        |
| Profile_AcrylicOpacity.Header                                                                     | Opacité de l'acrylique                                                                                                                      |                                                                                                                                                        |
| Profile_Padding.Header                                                                            | Marges                                                                                                                                      | Note the `s`                                                                                                                                           |
| Profile_SuppressApplicationTitle.Header                                                           | `Forcer le titre de l'onglet`                                                                                                               | I've opted for a literary translation. `suppress` can't be translated by `supprimer`..                                                                 |
| Profile_SuppressApplicationTitle.HelpText                                                         | Lorsque activé, les modifications du titre provenant de l'application sont ignorées et le titre spécifié dans la configuration est enforcé. | I've opted for a literary translation. `suppress` can't be translated by `supprimer`..                                                                 |
| Profile_AntialiasingMode.HelpText                                                                 | Contrôle le mode d'anticrénelage du rendu.                                                                                                  |                                                                                                                                                        |
| Profile_AntialiasingModeGrayscale.Content                                                         | `Grayscale`                                                                                                                                 | Don't try to literally translate anti aliasing techniques                                                                                              |
| Profile_AntialiasingModeAliased.Content                                                           | `Désactivé`                                                                                                                                 | Don't try to literally translate anti aliasing techniques                                                                                              |
| Profile_CloseOnExitNever.Content                                                                  | `Ne jamais se fermer automatiquement`                                                                                                       | Lacking consistency                                                                                                                                    |
| Profile_BellStyleVisual.Content                                                                   | `Visual (flash dans la barre de tâche)`                                                                                                     |                                                                                                                                                        |
| Nav_AddNewProfile.Content                                                                         | Nouveau profil                                                                                                                              |                                                                                                                                                        |
| Settings_SaveSettingsButton.Content                                                               | Enregistrer                                                                                                                                 | This one hurts to look at                                                                                                                              |
| Nav_OpenJSON.Content                                                                              | Ouvrir le fichier JSON                                                                                                                      |                                                                                                                                                        |

**Comment by DHowett** [comment]
Thanks again for this! The translation has been fixed and will be available in the next build.

**Comment by gpotter2** [comment]
Great news, thanks !

**Comment by gpotter2** [comment]
@DHowett I believe this made its way into the latest build(?)
Feel free to close the issue !

**Comment by DHowett** [comment]
That's great news. Thank you for confirming!

**Comment by sba923** [comment]
I've stopped using Microsoft products in French (my native language) ever since Microsoft moved the localization of their products from the local subs (which was the case when I started my professional career with a MS-DOS OEM in France in 1987) to Redmond. This is just one of a zillion issues...
