### ISSUE TITLE
Please confirm that Simple Cursor Positioning (ESC A B C D) sequences are not supported (while ESC F is)

### ISSUE THREAD

**Issue by zzwx** [microsoft/terminal#9240]
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.5.10411.0
```

# Steps to reproduce

* Print `ESC A`, `ESC B`, `ESC C`, `ESC D` in Windows Terminal. (CUU, CUD, CUF, CUB)
* Print them in regular PowerShell or Command Prompt and observe the difference.

For example, `TestC.` will output `Test.` without space in Windows Terminal, and `Test .` in a regular PowerShell / Command Prompt.

# Expected behavior

Those sequences should move the cursor within the window dimensions as described at https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#simple-cursor-positioning.

# Actual behavior

Printing `ESC A`, `ESC B`, `ESC C`, `ESC D` seems do nothing, however `ESC F` is supported.

**Comment by j4james** [comment]
Those cursor movement controls are actually VT52 escape sequences, which should only work when the VT52 mode is enabled (in ANSI mode they are undefined or do something else). The original console implementation incorrectly interpreted them as cursor movement regardless of the mode, but Windows Terminal has since been updated with the correct behaviour. The documentation still needs updating.

**Comment by zzwx** [comment]
Good to know, thank you! Does the repo actually have a place with a list of supported sequences? I couldn't find them unfortunately (must be blind).

**Comment by vefatica** [comment]
Using the OpenConsole.exe from Windows Terminal Preview Version: 1.6.10412.0 as if it were conhost.exe, ^eD does a cursor down (which does not agree with any documentation I've seen).  Is that right?

![image](https://user-images.githubusercontent.com/61856645/108641604-0e4bb800-746e-11eb-9998-3ee4a60e2254.png)

**Comment by j4james** [comment]
> Does the repo actually have a place with a list of supported sequences?

There's a PowerShell script at `doc/reference/Build-SupportedSequenceIndex.ps1` which attempts to generate a list of the supported sequences by scanning the source code. It's not perfect, but that's probably the best we have.

> Using the OpenConsole.exe from Windows Terminal Preview Version: 1.6.10412.0 as if it were conhost.exe, ^eD does a cursor down (which does not agree with any documentation I've seen). Is that right?

That's correct. That's the [`IND`](https://vt100.net/docs/vt510-rm/IND.html) (Index) escape sequence.

**Comment by DHowett** [comment]
James is right - these were erroneously supported outside of VT52 mode until #4044 (conhost in windows builds 19603+). We have a list [in the Windows Console docs](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) which is somewhat out-of-date, but we're working to bring it up to date and add some finer-grained version callouts.

We also have some stuff in the repo that will generate a list of _currently_ supported sequences, but that doesn't spit out a build artifact anywhere. Unfortunate.

Whoop, @j4james beat me to commenting. 😀

**Comment by vefatica** [comment]
> That's correct. That's the IND (Index) escape sequence.

Thanks.  I didn't know about that one.  My only reference is the console doc that @DHowett just mentioned.
