### ISSUE TITLE
Double click select Large Strings longer than line

### ISSUE THREAD

**Issue by hofingermarkus** [microsoft/terminal#9244]
# Environment

```none
Edition	Windows 10 Home Insider Preview
Version	Dev
Installed  ‎15.‎02.‎2021
build	21313.1000
```

# Steps to reproduce

Windows terminal allows to select a fully connected string with a single double click, which is nice.
However, this functionality stops at the line end, even if the string continues on the next line.
Reproduce:

Create a file/foldername with a long connected file name that it is longer than the currently shown line length of terminal. 
For example something like this "20200110_1985_ML_Experiment01_SettingsA_SettingsB_SettingC_Lorem_ipsum_dolor_sit_amet_consectetur_adipiscing_elit_sed_do_eiusmod_tempor_incididunt" 
Using a small window size is also a viable option to simulate this with shorter file names.
Show the file with e.g. `ls` and select the filename with a double click.
Selection will end at the end of the line

# Expected behavior

The double clicking a string normally selects a full connected string.
This selection should continue, even if "word wrap" spreads the string across multiple lines.
# Actual behavior

The string is only selected until the end of the line

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+double-click+line+wrap+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #6178 for more discussion.

/dup #6178
