### ISSUE TITLE
Windows Terminal is forcibly closed without notice whenever the app is updated

### ISSUE THREAD

**Issue by snevs** [microsoft/terminal#9245]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable): **All versions**
```

# Steps to reproduce

Open **Microsoft Store** > "**Downloads and updates**" > "**Get updates**"

# Expected behavior

Microsoct Store update should either:
- state that the app needs to close for update
- ask the user to proceed or postpone the update
- after the app is updated, offer the option to postpone app restart

# Actual behavior

Whenever Windows updates the Windows Terminal app from the Microsoft Store, the application closes without any prior notice.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6726 for more discussion.

/dup #6726
