### ISSUE TITLE
Replace / Add Win+x/ Start Context Menu

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [microsoft/terminal#9250]
# Description of the new feature/enhancement

It would be great if there were an option to replace the CMD/Windows Powershell options or add Windows Termina as an option in the Win+x/Start Context Menu with Windows Terminal.  If you could also set the terminal to start, that would be a bonus.

# Proposed technical implementation details (optional)

**Comment by jack775544** [comment]
Already a big issue created for this https://github.com/microsoft/terminal/issues/492

It is one of the things that the team has actively said they have been working on.

**Comment by skyline75489** [comment]
Yeah. Do understand that fixing #492 requires modification to the Windows OS itself and wouldn't be available until the next release of Windows. Please be patient about it.

**Comment by zadjii-msft** [comment]
Yep, this will be solved when we implement support for a "default terminal application". Thanks!

/dup #492
