### ISSUE TITLE
Windows Terminal on the desktop right click menu display width is a little long, I hope to simplify the name

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#9251]
Windows Terminal on the desktop right click menu display width is a little long, I hope to simplify the name.
Windows Terminal在桌面右键菜单显示的宽度有点长，希望可以简化一下名称。
For example, I could change the name to "open in Terminal".
例如可以将其名称改为“在 Terminal 打开”。

**Comment by Gaoyifei1011** [comment]
![Uploading 屏幕截图 2021-02-23 124712.png…]()

**Comment by skyline75489** [comment]
I don't think this will be configurable in the near future...

**Comment by zadjii-msft** [comment]
Okay so maybe I'm missing something here, but is this request just "I think that `Open in Windows Terminal` is too long, I want it to say `Open in Terminal`"?

Yea I'm pretty sure we're not going to let that be configurable. The Terminal's proper name is "Windows Terminal", I'm sure there's some branding requirement to not shorten that. Plus, there's #6112 tracking localizing that menu, which is certainly going to change the text of that entry.

**Comment by skyline75489** [comment]
@zadjii-msft You understand this perfectly 😃
