### ISSUE TITLE
"Disclaimer" text boxes are not read in narrator

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9255]
(not @zadjii-msft's fault, but still relevant) This text block is _not_ read by a screen reader (same with the disclaimer in base layer). I'll file a separate issue to track this one.

_Originally posted by @carlos-zamora in https://github.com/microsoft/terminal/pull/9253#discussion_r581256430_

**Comment by zadjii-msft** [comment]
Tentatively thrown on 1.7 b/c I thought we were going to make sure to fix this for 1.6 stable?

**Comment by DHowett** [comment]
There's no settings UI in 1.6, so there's no disclaimer to be had :smile:

**Comment by zadjii-msft** [comment]
🤦

**Comment by carlos-zamora** [comment]
This is 100% a Xaml Islands issue. See #4399.

**Comment by zadjii-msft** [comment]
(you maybe meant https://github.com/microsoft/microsoft-ui-xaml/issues/4399)

**Comment by zadjii-msft** [comment]
Oh would you look at that, we got rid of this page entirely! Problem solved 🤣
