### ISSUE TITLE
emojis not showing up correctly when pasting them into the command line.

### ISSUE THREAD

**Issue by vanitasboi** [microsoft/terminal#9259]
# Environment

```none
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```
Powershell, Windows Terminal Version 1.5.10411.0

# Steps to reproduce

✨ Use `win + .` to access the emoji menu and click on an emoji, which will insert that emoji into the command line. Alternatively, the emoji can also be pasted from the clipboard.
![image](https://user-images.githubusercontent.com/64850647/108976318-b092b800-7687-11eb-9024-26f02aff47c8.png)

# Expected behavior

✨ Windows Terminal has emoji support, which means that it should display those emojis across the whole interface, when printing output and when typing in the input.

# Actual behavior

✨ When typing in the input, emojis don't appear correctly, they just appear as question marks. Thanks 🤗

**Comment by DHowett** [comment]
What application is running inside Terminal? What version of Terminal? I can't tell because you removed the "Terminal version" and "any other software" section of the template :smile:

**Comment by vanitasboi** [comment]
Sorry, it's late for me right now 🤦‍♂️ hope this suffices

**Comment by skyline75489** [comment]
This is probably https://github.com/PowerShell/PSReadLine/issues/1329

**Comment by vanitasboi** [comment]
> This is probably [PowerShell/PSReadLine#1329](https://github.com/PowerShell/PSReadLine/issues/1329)

It does seem quite similar, although not even the `⏰` emoji was working in my original configuration.
I have tried `Remove-Module PSReadline`, which results in that emoji working. Very strange.
(I have included a screenshot in the original post)

**Comment by zadjii-msft** [comment]
Thanks for all the info! Emoji **_input_** straight up just doesn't work quite right in the console, and by extension, the Terminal. That's generally what we're tracking in #190 at this point. 

/dup #190
