### ISSUE TITLE
WT titlebar does not match color scheme of Windows 10 system

### ISSUE THREAD

**Issue by uservictor** [microsoft/terminal#9260]
# Environment

Windows build number:
Microsoft Windows [Version 10.0.19042.631]
CMD.exe [Version 10.0.19041.546]

Windows Terminal version (if applicable):
Windows Terminal [Version 1.5.10411.0]

# Steps to reproduce

Run actual Windows Terminal on actual Windows 10 Home.

# Expected behavior

Titlebar of Windows Terminal should match color theme in Windows 10 Personalization settings.

# Actual behavior

Titlebar of Windows Terminal is white (active and inactive) while all other application windows have the color that is set on Windows 10 Personalization settings.

# Note

I use Windows 10 Home x64 and this Personalization settings:
Start -> Settings -> Personalization -> Colors
Choose your color -> Custom

accent color -> Grey

Show accent color on the following surfaces:
Title Bars and window borders

It works fine on all applications except for Windows Terminal.

**Comment by skyline75489** [comment]
Probably related to #3327

**Comment by DHowett** [comment]
Unfortunately, yes. We don't offer "titlebar = accent color" today -- this option will only apply to the _window borders_ until we get 3327. /dup #3327
