### ISSUE TITLE
Crash on pressing cursor keys in command palette input box

### ISSUE THREAD

**Issue by harig** [microsoft/terminal#9265]
Windows Terminal Version: 1.5.10411.0
Microsoft Windows [Version 10.0.19042.804]

After opening a sub-command list from command palette and erasing the > to go to wt command mode, if up or down cursor keys are pressed windows terminal crashes.

Steps:
- Run wt.exe, press ctrl+shift+p to open command palette.
- Open any item which opens its own sub commands list, e.g. "select colorscheme..." or "new tab..."
- Now press backspace to delete the > from input box and to switch to wt commands mode.
- Press up or down arrow.
- wt.exe crashes and application stopped working dialog is shown.

When > is erased, the items from the sub-command list are removed, but it still shown the command title and button to go back to main view. Probably everything should be reset leaving just the input box as it does when we are in the main view.

**Comment by zadjii-msft** [comment]
Woah crazy, we just had another report of this over in #9241. This is already fixed in 1.6, and we believe it was fixed by #8422.

/dup #9241
