### ISSUE TITLE
Hololens build

### ISSUE THREAD

**Issue by peter-clemenko** [microsoft/terminal#9267]
Having a terminal build that works on hololens 2 (preferably able to be booted in a mixed reality app like edge can be), would be extremely useful

**Comment by zadjii-msft** [comment]
So FYI, The Terminal does work in an MR environment: https://github.com/microsoft/terminal/issues/693#issuecomment-525364333

I'm not sure about Hololens 2 - I have almost no context on how that actually works. @PhMajerus do you happen to know any more?

**Comment by peter-clemenko** [comment]
Yeah I saw this, but having it on the store as a hololens app would help as well. I'm not sure what needs to be done for that.

**Comment by zadjii-msft** [comment]
To be totally honest, neither do we! We'd accept any contributions to make the Terminal work on Hololens. But I'm not sure we could officially support it in the Store. No one on the team has a Hololens, so it would be basically impossible for us to be able to support it sufficiently. There'd be no way for us to validate bug fixes on our own end. 

I'll throw this on the backlog for now. Maybe in 2030 when we're all working in fully MR environments, this will be easier to address 😝

**Comment by peter-clemenko** [comment]
Is there someone from the mixed reality team that could be asked?

**Comment by DHowett** [comment]
So, unfortunately, an application designed like ours (with a XAML page hosted in a Win32 host using Xaml Islands) isn't able to be a MR/AR native citizen. This would have to be part of our longer-term effort to turn Windows Terminal Universal (which dispenses with the Win32 hosting component) into a shippable product, which just isn't something we're equipped for today.

Right now, the benefits are minimal ("works on hololens") but the costs are high ("needs a version of Windows that pretty much doesn't exist yet"). Sorry.
