### ISSUE TITLE
Add extra shortcuts (ordinal numbers) to the New Tab Dropdown menu

### ISSUE THREAD

**Issue by eugenesvk** [microsoft/terminal#9268]
# Description of the new feature/enhancement

I'd like to have every item in the "__openNewTabDropdown__" menu (a dropdown list of shells for a new tab) to have a number that can be used as a very convenient shortcut

__In Conemu__: when I open a dropdown menu/list of all the shells for a new tab, in Conemu I can use <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd> etc. keys to select an item (<kbd>1</kbd> for "Group17", <kbd>2</kbd> for "wsl", <kbd>3</kbd> for "Shells")

![Conemu](https://user-images.githubusercontent.com/12956286/109013358-1bfa7b00-76c4-11eb-81c3-67ea41b75287.png)

__In WT__: I can't do that — I either have to use the less convenient shortcuts (e.g. <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>1</kbd> for "Windows PowerShell"), which can never be made as convenient as <kbd>1</kbd><kbd>2</kbd><kbd>3</kbd>, or select with a cursor/mouse

![WT](https://user-images.githubusercontent.com/12956286/109013364-1e5cd500-76c4-11eb-8654-3bc04ae3bdeb.png)

This is very helpful for opening __less frequently used__ shells, for which I don't have to memorize the order/special shortcuts, but instead I can use an open new tab-kind of shortcut and select a number

**Comment by zadjii-msft** [comment]
Okay I don't hate this. I do _personally_ hate the verbosity of the `1: {profile}` text. I'd almost want this to be a totally hidden feature that "just works". Like have no UI indicating it, but the 1-9 keys would just work to open the 1st-9th entries in the dropdown.

I'm sure there's some accessibility doc somewhere that says I can't just do that, and would _need_ to have some text there. So I'd probably want to make the `1: ` text configurable. That's just personal preference. 

Thanks for the suggestion!

**Comment by eugenesvk** [comment]
> I'd almost want this to be a totally hidden feature that "just works". Like have no UI indicating it, but the 1-9 keys would just work to open the 1st-9th entries in the dropdown.

Why would you force users to count the entries to make it work? I'm not sure everyone uses the same defauled numbered shortcuts to have a # hint (like, maybe they use a shortcut with a first letter of a shell there?)

> So I'd probably want to make the 1: text configurable

But yeah, for those that do rely on the numbered shortcuts, having an option to make the text invisible might be worth it since there is already an UI indication of a #, so I'm all up for that

By the way, if you make the text of the same keyboard-shortcut-grey color, you definitely don't need the colon `:`, so that would cut down some verbosity :) 
Also, you could add this number to the left of the current shortcuts (after all, this is also a shortcut), but to the right of the shell name (in the second/middle column) and the colon would even stop making sense

**Comment by zoredache** [comment]
I will probably create an issue, but it sure seems like a more useful generic solution would be to allow users to assign a keyboard shortcut of their choosing to any profile.

**Comment by FWest98** [comment]
> 
> 
> I will probably create an issue, but it sure seems like a more useful generic solution would be to allow users to assign a keyboard shortcut of their choosing to any profile.

That is already possible: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#new-tab. It is possible to set the profile name in the action definition.

**Comment by zadjii-msft** [comment]
You know what, I think I'm gonna dedupe this with #6213. That one generically suggested "access keys" for the menu. This thread was talking specifically about using the numbers. Whatever we come up with should make sure to resolve both ideas. 

/dup #6213
