### ISSUE TITLE
Additional password to launch a profile session

### ISSUE THREAD

**Issue by AliMickey** [microsoft/terminal#9277]
# Description of the new feature/enhancement

An option to add an additional password to a specific session when opening a new profile. 
I already use ssh keys, however anyone with access to my system can launch a session easily. 

Adding a password would make profile more secure.

# Proposed technical implementation details (optional)

Simple password checker on specific/global profile launch

Enable local password security per profile.

**Comment by DHowett** [comment]
I'm sorry. Windows Terminal has no intention of becoming a security product, and I do not want to offer our users something that would ultimately be less safe for them then ensuring that they have secure user accounts.
