### ISSUE TITLE
Tab/Menu Display Error

### ISSUE THREAD

**Issue by jlm222** [microsoft/terminal#9278]
![display](https://user-images.githubusercontent.com/59456904/109093432-4114db00-7710-11eb-872f-4fa261bc7082.jpg)

# Environment

```none
Windows build number:  Microsoft Windows [Version 10.0.18363.1379]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Starting the application, it's like this from the start

# Expected behavior

It should display the shell name in the tab, the cross to close the tab, the new tab button and a dropdown to display a menu. The menu should display when clicking on the dropdown button.

# Actual behavior

None of these things are being displayed, they're there and clickable and working, they just aren't displayed. If I click the dropdown button the menu will appear briefly, then disappear and leave a black shadow. I can still click the options, I just can't see them.

**Comment by KalleOlaviNiemitalo** [comment]
There was an unexpected shadow in <https://github.com/microsoft/terminal/issues/7532> as well.

In your first screenshot though, the top of the profile menu is aligned with the top of the tab bar, not with the bottom where it normally would be. This might indicate that it is not just a layering problem.

**Comment by zadjii-msft** [comment]
Weird. This is like half of #7532, and half of #8948.

Out of curiosity: 
* Which version of the Terminal are you running? (check the about dialog, or `wt -v` from the commandline)
* does this happen on every launch?
* If you type <kbd>ctrl+shift+p</kbd>, you should see the [command palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette). Does that have the same effect?
* Does saving the settings (while the Terminal is open) cause the tabs to appear?
* Does clicking on "About" in the dropdown cause a dialog to appear? 

I'm curious if everything that's casting a shadow is somehow... removed from the visual tree? It's just so bizarre.

**Comment by jlm222** [comment]
- It's version 1.5.10411.0 
- Yes it does, I'd like to use it but it never works and never has done.

- Yep there's just a shadow instead of the palette it seems.
![palette](https://user-images.githubusercontent.com/59456904/109298168-123f5780-782b-11eb-93ff-32cfc4dfb250.png)

- I'm not sure how to save the settings I'm afraid. Although when I click where settings is I get this 
![settings](https://user-images.githubusercontent.com/59456904/109298556-b0332200-782b-11eb-91e0-416b543e92ab.png)

- About causes the whole window to darken
![about](https://user-images.githubusercontent.com/59456904/109298784-0607ca00-782c-11eb-8678-56d2e0cf9233.png)

**Comment by zadjii-msft** [comment]
Okay well that's totally crazy. Can you file a bug on https://github.com/microsoft/microsoft-ui-xaml/issues? It seems like anything that casts a shadow in the Terminal is not showing up in the UI tree at all. That's something totally unexpected, and I have no idea if there's anything we can do in code to prevent that. Hopefully the XAML experts will have some insights here
