### ISSUE TITLE
Add SSH option to log in some vps/dedicated servers

### ISSUE THREAD

**Issue by trilianx** [microsoft/terminal#9279]
Add SSH option to log in some vps/dedicated servers

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment]
You can easily add SSH profiles. See https://docs.microsoft.com/en-us/windows/terminal/tutorials/ssh

**Comment by zadjii-msft** [comment]
Yea I'm not sure what you want from us here. Just add whatever profiles you want?
