### ISSUE TITLE
Drag & Drop File Path completion for WSL-Distribution

### ISSUE THREAD

**Issue by Gandalf1783** [microsoft/terminal#9281]
# Description of the new feature/enhancement

I'd like to request a new feature. Usually, when you drag n' drop files or folders into the CMD, the path gets autocompleted, however this is not the case with wsl-paths.

# Proposed technical implementation details (optional)

Instead of pasting the windows-path (e.g. "C:\Users\User\Documents") it should paste a linux path (e.g. "\mnt\c\Users\User\Documents") so you can handle files more easily.

**Comment by skyline75489** [comment]
I think this is covered in #1772.

**Comment by Gandalf1783** [comment]
Yes it is.
I only searched for "C Path refactor", but couldnt find the issue.
