### ISSUE TITLE
Last Closed Window/Location

### ISSUE THREAD

**Issue by andybcom** [microsoft/terminal#9282]
**Description**
Provide the ability to allow the application to recall its last opened/closed position

**Feature Request**
When Windows Terminal is opened, it defaults to screen0. On multi-display systems, providing an option to recall the screen/location where the application was last closed would allow users to automatically keep the layout of a desktop they are used to manually laying out each time.

**Comment by j4james** [comment]
I think this will probably be covered by issue #766. Note the last line of the issue description:

> This also includes restoring things like previous window positions.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #766 for more discussion.

/dup #766
