### ISSUE TITLE
Taskbar title and tab title of currently logged server over ssh

### ISSUE THREAD

**Issue by marbaa** [microsoft/terminal#9284]
Hi there,

documentation is not very rich about it. Here is the scenario.

I start up Debian WSL1 distro, taskbar and tab title shows user@host:pwd format. Thats good. If I do ssh to another server, title is not changed to newly logged server but still shows the title from WSL distro.

Am I doing something wrong or Windows Terminal does not have feature that will change tab/taskbar title whereever I do ssh to some server?

**Comment by KalleOlaviNiemitalo** [comment]
Windows Terminal does not itself try to detect that you ssh to a server. Instead, the server has to ask Windows Terminal to change the tab title. See [Tutorial: Configure tab titles in Windows Terminal](<https://docs.microsoft.com/windows/terminal/tutorials/tab-title>).

**Comment by zadjii-msft** [comment]
Already, when the terminal is showing the `user@host:pwd` text, that's the local WSL instance changing the title to display that text. I'm guessing that your remote shell isn't configured to change the title as part of the prompt. What shell are you using on the remote server?

**Comment by marbaa** [comment]
Actually it is working as I expected. I was just testing it on server which had somehow corrupted .bashrc. When I made ssh to another from that corrupted server, title was changed to actual server, as expected.

**Comment by DHowett** [comment]
Thanks for letting us know.
