### ISSUE TITLE
[on start] "Incorrect Function"

### ISSUE THREAD

**Issue by Lagicrus** [microsoft/terminal#9285]
https://aka.ms/AAbc3m9

# Environment

```none
Windows build number: Win32NT             10.0.21322.0 Microsoft Windows NT 10.0.21322.0
Windows Terminal version (if applicable): 1.5.10411.0

Any other software?
```

# Steps to reproduce

1. Click the Icon in Taskbar or Start menu
2. Wait a few seconds for it to "Load"
3. Have a popup appear in your face telling you it is an "Incorrect function."
![image](https://user-images.githubusercontent.com/24227350/109150179-6af5ee00-7760-11eb-9b90-efc31f58c05a.png)

# Expected behaviour

It should load

# Actual behaviour

It isn't loading

**Comment by skyline75489** [comment]
So you are using insider preview? I’m not sure the core team’s goal about WT running on insider builds.

**Comment by zadjii-msft** [comment]
I mean, we're all on Insiders builds ourselves, so that _shouldn't_ have anything to do with it 😄. We'll have to dig in on the feedback link, but I'm worried that it's crashing before even loading the terminal, so that might not be useful...

**Comment by Lagicrus** [comment]
> I mean, we're all on Insiders builds ourselves, so that _shouldn't_ have anything to do with it 😄. We'll have to dig in on the feedback link, but I'm worried that it's crashing before even loading the terminal, so that might not be useful...

Ye.. I have even ran the "Repair" function from the Windows App view or whatever it is called if that helps
If you can point me at ways to get more logs or dumps, feel free to ping, I want this working again 😄 I use it way too much

**Comment by Lagicrus** [comment]
Minor update, after my PC crashed which caused me to reboot, I tried to reopen Terminal
I couldn't printscreen due to it being a Windows popup, but it mentioned something about it not being able to open it due to the storage being offline?
I will see if i can get this to happened again later

**Comment by zadjii-msft** [comment]
FYI on a `MessageBox` like that, you can just hit <kbd>ctrl+c</kbd> and it'll actually copy the text of that dialog. Handy for bug reports like this ☺️ 

The specific text that it shows you might be helpful in narrowing down the cause of this.

**Comment by Lagicrus** [comment]
> FYI on a `MessageBox` like that, you can just hit ctrl+c and it'll actually copy the text of that dialog. Handy for bug reports like this ☺️
> 
> The specific text that it shows you might be helpful in narrowing down the cause of this.

I had no idea that was a thing..  Everyday you learn something new :+1:

```
[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10411.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10411.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

Incorrect function.


[OK]
```

**Comment by Lagicrus** [comment]
I got the window to appear on windows start again
```
Windows Terminal can’t open because it is offline. The storage device might be missing or disconnected.
```
That is what I get when I hit the copy button, this was after a Green screen with it working fine

**Comment by zadjii-msft** [comment]
Weird. This is another feedback that ended up getting bucketed to `utc_feedbacc_diagtrack.dll`, which is totally useless 😕 On the bright side, it doesn't seem to think that the Terminal is actually involved in the crash at all. On the down side, that kinda means there's nothing left for me to be able to investigate. I can't track down the crash outside our codebase ☹️

Does re-installing the app from the store help? (make sure to back up your settings from `%localappdata%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json` first!)

**Comment by Lagicrus** [comment]
> Weird. This is another feedback that ended up getting bucketed to `utc_feedbacc_diagtrack.dll`, which is totally useless 😕 On the bright side, it doesn't seem to think that the Terminal is actually involved in the crash at all. On the down side, that kinda means there's nothing left for me to be able to investigate. I can't track down the crash outside our codebase ☹️
> 
> Does re-installing the app from the store help? (make sure to back up your settings from `%localappdata%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json` first!)

I'll try that later, so far I have found that waiting and then trying again seems to fix it? 
I haven't bothered to time it as that is too variable, but ye. If I get the warning, wait a bit, then try again, "when everything has calmed down". And it seems to work again?

**Comment by zadjii-msft** [comment]
Sorry this one's stayed hidden on the backlog so long - @Lagicrus you still seeing this? Is there anything that gets logged in Event Viewer when this happens? I honestly have no idea what's going on here, or why letting the OS "settle down" would fix this...
