### ISSUE TITLE
[Feature Request] Let us use the middle mouse button click to scroll (like Command Prompt)

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#9286]
# Description of the new feature/enhancement
Let us use the middle mouse button click to scroll (like Command Prompt)
![Windows Terminal](https://user-images.githubusercontent.com/23485114/109155971-81fb0700-7785-11eb-9093-7ddb74418ad0.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #1701 for more discussion.

/dup #1701
