### ISSUE TITLE
[1.7] Tab indicators in the cmdpal aren't working (sometimes?)

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9288]
Build is 1.7.552.0.

* run `wt ; nt`
* mark the second pane as read only
* open the tab switcher

You should see a lock:
![image](https://user-images.githubusercontent.com/18356694/109203820-3b4be380-776a-11eb-83e6-30dcf65e89a2.png)

But sometimes you don't?
![image](https://user-images.githubusercontent.com/18356694/109204056-8108ac00-776a-11eb-8dcf-8928beb7e9c5.png)

> On the debug build, I wasn't able to get them to appear, until I stepped through it once, and now they _always_ appear. Like, no launches of the terminal ever had them, now all launches of the terminal have them

When I was first debugging through this, it looked like `PaletteItemTemplateSelector::_TabItemTemplate` was null. However when debugging the release build that doesn't repro this, `_TabItemTemplate` definitely isn't null, so that can't be it.

**Comment by Don-Vito** [comment]
I hope to get back to work on Terminal - I missing all the action

**Comment by zadjii-msft** [comment]
woah today I got a new variation of this:

![image](https://user-images.githubusercontent.com/18356694/110827179-70bcfa80-825b-11eb-90bd-70d6930f05c2.png)

That's the tab switcher, and one of the tabs has the nested command arrow in it. That's not right 😮

**Comment by Don-Vito** [comment]
> 
> woah today I got a new variation of this:
> 
> ![image](https://user-images.githubusercontent.com/18356694/110827179-70bcfa80-825b-11eb-90bd-70d6930f05c2.png)
> 
> That's the tab switcher, and one of the tabs has the nested command arrow in it. That's not right 😮

Holly mother of God.. I will take a look..

**Comment by Don-Vito** [comment]
So it appears that ListView (_filteredActionViews) recycles ListViewItems. 🤦 

To reproduce the problem simply:
1. Start terminal
2. Open command palette
3. Open tab with too panes, and zoom one
4. Open another tab
5. Switch between the tabs

No zoom icon will be shown.

Still considering how to fix this.

**Comment by DHowett** [comment]
**HUH**. I would have expected ListViewItems to be recycled only based on data template (!!!) so this is sorta scary.

**Comment by DHowett** [comment]
Ah. ["Container-recycling with heterogeneous collections"](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-gridview-and-listview#container-recycling-with-heterogeneous-collections)

> ChoosingItemContainer is an event that allows you to provide an item (ListViewItem/GridViewItem) to the ListView/GridView whenever a new item is needed during start-up or recycling. You can create a container based on the type of data item the container will display (shown in the example below). ChoosingItemContainer is the higher-performing way to use different data templates for different items.

**Comment by Don-Vito** [comment]
> 
> 
> **HUH**. I would have expected ListViewItems to be recycled only based on data template (!!!) so this is sorta scary.

According to the documentation it does:

>When recycling an item (ListViewItem/GridViewItem), the framework must decide whether the items that are available for use in the recycle queue (the recycle queue is a cache of items that are not currently being used to display data) have an item template that will match the one desired by the current data item. If there are no items in the recycle queue with the appropriate item template then a new item is created, and the appropriate item template is instantiated for it. If, on other hand, the recycle queue contains an item with the appropriate item template then that item is removed from the recycle queue and is used for the current data item. An item template selector works in situations where only a small number of item templates are used and there is a flat distribution throughout the collection of items that use different item templates.

**Comment by Don-Vito** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/2121
