### ISSUE TITLE
Open new tab instead of window

### ISSUE THREAD

**Issue by uservictor** [microsoft/terminal#9291]
Please note: I don't know if this is an intended behaviour.

Windows 10 [Version 10.0.19042.631]
Windows Terminal [Version 1.5.10411.0]

# Description of the actual behaviour.

If you are running windows terminal and want to open over right-click (Open in Windows Terminal) an wt window with this path of click destination, an new wt window opens, so you have two wt windows.
Basicly it opens every time an new window if you use "Open in Windows Terminal" option.

# A clear and concise description of what you want to happen.

My suggestion is to **open a new tab** with new path **instead of opening an window**, so only one windows terminal is running with multiple tabs.

Thanks, have a nice day

**Comment by DHowett** [comment]
Thanks for the request! This is coming as an option with #9118 (soon to be released).

/dup #2227.

**Comment by KalleOlaviNiemitalo** [comment]
There's also <https://github.com/microsoft/terminal/issues/7071> still open for the shell extension.

**Comment by DHowett** [comment]
Ah, indeed. Thanks.

@zadjii-msft we may want to deduplicate 7071 with the new windowing behavior setting.

**Comment by zadjii-msft** [comment]
Meh, i thought that would fit as a explicit setting. Like, I want `useNew` most of the time but I want the shell extension to `useExisting`? I feel like we've had settings for more trivial things in the past
