### ISSUE TITLE
Code health: update every call of initializing TermControl with settings

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#9292]
In #8602, we started passing a child of the `TerminalSettings` to the control upon tab initialization, we need to make sure that we are doing this for every call of initializing a new TermControl (we initially forgot to do this for controls initialized during pane split, which led to #9280). 

EDIT: Ideally, we do this by having a helper that handles the creation of new TermControls, see DHowett's comment below.

**Comment by DHowett** [comment]
I'd rather us use this bug for making it so we _don't have so many places_. Like, "Unify TerminalControl creation in TerminalApp to reduce duplication and regression risk"
