### ISSUE TITLE
All instances updated when settings.json changes?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9298]
I wanted a side-by-side comparison of Colsolas and Cascadia Code in two instances of WT and my default profile.  With two instances running, both were updated when I saved the settings file (so I didn't get my comparison).  Al running instances are updated regardless of which (if any) caused the settings file to be opened (including Settings UI).  I'm not complaining but I was quite surprised.  It's rather peculiar behavior.  I can't think of another app that behaves that way.

**Comment by DHowett** [comment]
Yup! Terminal supports hot reloading when you edit the settings file. This is 100% by design and something we've spent a lot of time on getting right! :smile:
