### ISSUE TITLE
Programs not accepting input

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#93]
_From @coreysharris on May 31, 2017 9:20_

* Your Windows build number:  10.0.16199.1000

* What you're doing and what's happening:  
Starting a program in bash works, but input does not.  
This problem occurs for vim, emacs, sagemath
but everything works in mc, w3m

* What's wrong / what should be happening instead:
After the program starts, it should accept input from the keyboard.

For SageMath, I reinstalled from source to try to fix this (before I realized it was a problem for other programs) and when it starts I get this error before the initial prompt: /home/corey/.local/lib/sage-7.6/local/lib/python2.7/site-packages/psutil/_pslinux.py:364: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)

* Strace of the failing command, if applicable: Example shown with "vim -u NONE" (the flag prevents loading of my .vimrc)
[strace.txt](https://github.com/Microsoft/BashOnWindows/files/1040751/strace.txt)

_Copied from original issue: Microsoft/WSL#2177_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on May 31, 2017 20:56_

Possibly #2092?

**Comment by bitcrazed** [comment]
_From @coreysharris on June 1, 2017 8:54_

Ok, the workaround given there fixes the problem for vim, but not for emacs or sage.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on June 1, 2017 16:47_

I'll take a look.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on June 5, 2017 21:10_

@coreysharris have you done anything to modify your emacs configuration at all? I just installed a fresh 16199 build and emacs seems to run just fine, so there's probably some configuration that is breaking this.

Does changing your `TERM` setting (and launching bash in the same window again) change anything?

What about running emacs inside of `screen` or `tmux`?

**Comment by bitcrazed** [comment]
_From @zadjii-msft on July 13, 2017 20:55_

I've been out for a few weeks, but I'd like to make sure this gets resolved or at least understood before the next release.

@coreysharris is this still happening for you in new insider's builds? Does any of the other suggestions make a difference? Does running the Ubuntu instance from the store make a difference?

**Comment by DHowett-MSFT** [comment]
This never received author feedback; closing `Resolution-Won't Fix`
