### ISSUE TITLE
WinUI3 : Would it be a technical solution to ship Windows Terminal outside the store ?

### ISSUE THREAD

**Issue by tebeco** [microsoft/terminal#9302]
# Description of the new feature/enhancement

As WinUI 3 is supposed to 
* be able to ship application to older version of windows and still keeping compatibility with new feature
* Enhance current UWP state
and few other thing. That would be the perfect opportunity to use that to remove the infamous bug of

"If the Store is locked, you won't ever be able to run WT be double clicking `msixbundle` and this will also 
* Not be needed to manually rename
* Manually unzip
* Manually renamed what was in the zip to ... another zip
* Manually unzip again
* Update the Path
* Can't be used as a $PROFILE script because WT cannot update itself

Would that be a more ideal way to ship to company ? (which mostly have the store lockdown)

**Comment by zadjii-msft** [comment]
Maybe, but I'd doubt it.  I think WinUI 3 is supposed to help blur the lines between Win32 and UWP, so that we can have a more UWP-like experience, and don't need to do all the XAML islands tricks we're currently doing. I **don't** think that there's anything about WinUI 3 that's really going to change how packaged applications work, however.

**Comment by tebeco** [comment]
Could it be coupled with click once or equivalent then ?

**Comment by huoyaoyuan** [comment]
I wonder why msix double clicking is disabled when the store is disabled. Msix is meant to act more than store. It can contain win32 applications.

**Comment by DHowett** [comment]
As far as we are aware, double-clicking an MSIX has nothing to do with the store.

Mike answered this very well -- I'm gonna close it out as an answered question. We're not in a place where we can benefit from WinUI3 today.
