### ISSUE TITLE
Will be good, if terminal have simple opacity like a CMD

### ISSUE THREAD

**Issue by hwhovo** [microsoft/terminal#9305]
acrylicOpacity has blur effect and terminal back side doesn't visible. It is hard to read backside text. Will be good, that windows will have hotkey, which will minimize and maximize terminal, because terminal usage for programmers and Dev OPS is very often. That feature available at the ConEmu application.

Thanks.

**Comment by j4james** [comment]
The simple opacity feature is already being tracked in issue #603, and having a hotkey to minimize and maximize the terminal is covered by issue #653.

**Comment by jv987865** [comment]
Put down a function()

**Comment by zadjii-msft** [comment]
Yep, I think j4james covered this.

/dup #603
/dup #653
