### ISSUE TITLE
Failed to reload settings windows terminal

### ISSUE THREAD

**Issue by Piot1998** [microsoft/terminal#9309]
I have such a problem. Namely, when he wants to make such modifications https://www.bleepingcomputer.com/news/microsoft/windows-terminal-now-has-a-hidden-graphical-settings-editor/ in the windows terminal, he receives this error ![](https://user-images.githubusercontent.com/10755858/71671836-147a6300-2d9a-11ea-9910-8aeb0845e952.png). And now my question. Where does such an error come from if I do everything in accordance with what is given in the guide? How to fix it?

**Comment by Omega172** [comment]
@Piot1998 you are missing a closing curly brace on line 42, column 1. If you could pastebin your settings I wouldn't mind fixing it for you.

**Comment by Piot1998** [comment]
// This file was initially generated by Windows Terminal 1.0.1401.0  // It should still be usable in newer versions, but newer versions might have additional  // settings, help text, or changes that you will not see unless you clear this file  // and let us generate a new one for you.   // To view the default settings, hold &#34;alt&#34; while clicking on the &#34;Settings&#34; button.  // For documentation on these settings, see:  aka.ms aka.ms  {      &#34;$schema&#34;: &#34; aka.ms aka.ms &#34;,       &#34;defaultProfile&#34;: &#34;{61c54bbd-c2c6-5271-96e7-009a       // You can add more global application settings here.      // To learn more about global settings, visit  aka.ms aka.ms       // If enabled, selections are automatically copied to your clipboard.      &#34;copyOnSelect&#34;: false,       // If enabled, formatted data is also copied to your clipboard      &#34;copyFormatting&#34;: false,       // A profile specifies a command to execute paired with information about how it should look and feel.      // Each one of them will appear in the &#39;New Tab&#39; dropdown,      //   and can be invoked from the commandline with `wt.exe -p xxx`      // To learn more about profiles, visit  aka.ms aka.ms      &#34;profiles&#34;:      {          &#34;defaults&#34;:          {              // Put settings here that you want to apply to all profiles.          },          &#34;list&#34;:          [              {                  // Make changes here to the powershell.exe profile.                  &#34;guid&#34;: &#34;{61c54bbd-c2c6-5271-96e7-009a                  &#34;name&#34;: &#34;Windows PowerShell&#34;,                  &#34;commandline&#34;: &#34;powershell.exe&#34;,                  &#34;hidden&#34;: false              },              {                  // Make changes here to the cmd.exe profile.                  &#34;guid&#34;: &#34;{0caa0dad-35be-5f56-a8ff-afce                  &#34;name&#34;: &#34;Command Prompt&#34;,                  &#34;commandline&#34;: &#34;cmd.exe&#34;,                  &#34;hidden&#34;: false              },              {                  &#34;guid&#34;: &#34;{b453ae62-4e3d-5e58-b989-0a99                  &#34;hidden&#34;: false,                  &#34;name&#34;: &#34;Azure Cloud Shell&#34;,                  &#34;source&#34;: &#34;Windows.Terminal.Azure&#34;              }          ]      },       // Add custom color schemes to this array.      // To learn more about color schemes, visit  aka.ms aka.ms      &#34;schemes&#34;: [],       // Add custom keybindings to this array.      // To unbind a key combination from your defaults.json, set the command to &#34;unbound&#34;.      // To learn more about keybindings, visit  aka.ms aka.ms      &#34;keybindings&#34;:      [          // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.          // These two lines additionally bind them to Ctrl+C and Ctrl+V.          // To learn more about selection, visit  aka.ms aka.ms          { &#34;command&#34;: {&#34;action&#34;: &#34;copy&#34;, &#34;singleLine&#34;: false }, &#34;keys&#34;: &#34;ctrl+c&#34; },          { &#34;command&#34;: &#34;paste&#34;, &#34;keys&#34;: &#34;ctrl+v&#34; },           // Press Ctrl+Shift+F to open the search box          { &#34;command&#34;: &#34;find&#34;, &#34;keys&#34;: &#34;ctrl+shift+f&#34; },           // Press Alt+Shift+D to open a new pane.          // - &#34;split&#34;: &#34;auto&#34; makes this pane open in the direction that provides the most surface area.          // - &#34;splitMode&#34;: &#34;duplicate&#34; makes the new pane use the focused pane&#39;s profile.          // To learn more about panes, visit  aka.ms aka.ms          { &#34;command&#34;: { &#34;action&#34;: &#34;splitPane&#34;, &#34;split&#34;: &#34;auto&#34;, &#34;splitMode&#34;: &#34;duplicate&#34; }, &#34;keys&#34;: &#34;alt+shift+d&#34; },  { &#34;command&#34;: { &#34;action&#34;: &#34;openSettings&#34;, &#34;target&#34;: &#34;settingsUI&#34; }, &#34;keys&#34;: &#34;ctrl+shift+s&#34; }      ]  }   
            
          
     
      
       
        Dnia 28 lutego 2021 23:14 Omega172 &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 github.com @Piot1998  you are missing a closing curly brace on line 42, column 3. If you could pastebin your settings I wouldn&#39;t mind fixing it for you.

**Comment by Piot1998** [comment]
Hold on. Here you have my current settings.json file  ```js  // This file was initially  // It should still be usa  // settings, help text, or  // and let us generate a�   // To view the default se  // For documentation on th aka.ms aka.ms  {       &#34;$schema&#34; :  &#34; aka.ms aka.ms &#34; ,        // &#34;defaultProfile&#34;: &#34;{61c54        // You can add more globa       // To learn more about gl aka.ms aka.ms        // If enabled, selections        &#34;copyOnSelect&#34; :  false ,        // If enabled, formatted d       &#34;copyFormatting&#34; :  false ,        // A profile specifies a        // Each one of them will�       //   and can be invoked�       // To learn more about pr aka.ms aka.ms       &#34;defaultProfile&#34; :  &#34;{00000000-0000-0000-ba88-0000 ,       &#34;profiles&#34; : {           &#34;defaults&#34; : {               // Put settings here that�          },           &#34;list&#34; : [{                  &#34;guid&#34; :  &#34;{00000000-0000-0000-ba88-0000 ,                  &#34;commandline&#34; :  &#34;C: \\ Program Files \\ Git \\ bin \\ bash.exe&#34; ,                  &#34;name&#34; :  &#34;Git Bash&#34; ,                  &#34;background&#34; :  &#34;#012456&#34; ,                  &#34;hidden&#34; :  false              },              {                  // Make changes here to t                  &#34;guid&#34; :  &#34;{61c54bbd-c2c6-5271-96e7-009a ,                  &#34;name&#34; :  &#34;Windows PowerShell&#34; ,                  &#34;commandline&#34; :  &#34;powershell.exe&#34; ,                  &#34;hidden&#34; :  false              },              {                  // Make changes here to t                  &#34;guid&#34; :  &#34;{0caa0dad-35be-5f56-a8ff-afce ,                  &#34;name&#34; :  &#34;Command Prompt&#34; ,                  &#34;commandline&#34; :  &#34;cmd.exe&#34; ,                  &#34;hidden&#34; :  false              },              {                  &#34;guid&#34; :  &#34;{2c4de342-38b7-51cf-b940-2309 ,                  &#34;hidden&#34; :  false ,                  &#34;name&#34; :  &#34;Ubuntu&#34; ,                  &#34;source&#34; :  &#34;Windows.Terminal.Wsl&#34;              },              {                  &#34;guid&#34; :  &#34;{b453ae62-4e3d-5e58-b989-0a99 ,                  &#34;hidden&#34; :  false ,                  &#34;name&#34; :  &#34;Azure Cloud Shell&#34; ,                  &#34;source&#34; :  &#34;Windows.Terminal.Azure&#34;              }          ]      },        // Add custom color scheme       // To learn more about co aka.ms aka.ms       &#34;schemes&#34; : [],        // Add custom keybindings        // To unbind a key combin       // To learn more about ke aka.ms aka.ms       &#34;keybindings&#34; : [            // Copy and paste are bou           // These two lines additio           // To learn more about se aka.ms aka.ms          {               &#34;command&#34; : {                  &#34;action&#34; :  &#34;copy&#34; ,                  &#34;singleLine&#34; :  false              },               &#34;keys&#34; :  &#34;ctrl+c&#34;          },          {               &#34;command&#34; :  &#34;paste&#34; ,               &#34;keys&#34; :  &#34;ctrl+v&#34;          },            // Press Ctrl+Shift+F to o          {               &#34;command&#34; :  &#34;find&#34; ,               &#34;keys&#34; :  &#34;ctrl+shift+f&#34;          },            // Press Alt+Shift+D to op           // - &#34;split&#34;: &#34;auto&#34; makes           // - &#34;splitMode&#34;: &#34;duplicat           // To learn more about pa aka.ms aka.ms          {               &#34;command&#34; : {                  &#34;action&#34; :  &#34;splitPane&#34; ,                  &#34;split&#34; :  &#34;auto&#34; ,                  &#34;splitMode&#34; :  &#34;duplicate&#34;              },               &#34;keys&#34; :  &#34;alt+shift+d&#34;          },           {                &#34;command&#34; : {                   &#34;action&#34; :  &#34;openSettings&#34; ,                   &#34;target&#34; :  &#34;settingsUI&#34;                },                &#34;keys&#34; :  &#34;ctrl+shift+s&#34;            }      ]  }  ```  and a message   
            
          
     
      
       
        Dnia 28 lutego 2021 23:14 Omega172 &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 github.com @Piot1998  you are missing a closing curly brace on line 42, column 3. If you could pastebin your settings I wouldn&#39;t mind fixing it for you.

**Comment by zadjii-msft** [comment]
@Piot1998 could you post your settings in github itself? Your email client seems to be mangling the contents pretty aggressively 😮

**Comment by Piot1998** [comment]
OK  
            
          
     
      
       
        Dnia 1 marca 2021 13:19 Mike Griese &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 github.com @Piot1998  could you post your settings in github itself? Your email client seems to be mangling the contents pretty aggressively  😮

**Comment by Piot1998** [comment]
Just to be clear about the situation. I am using the official windows terminal version, not the preview version.

**Comment by Piot1998** [comment]
I'm sending my settings.json file
``js
// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    // "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "defaultProfile": "{00000000-0000-0000-ba88-000000000002}",
    "profiles": {
        "defaults": {
            // Put settings here that you want to apply to all profiles. 
        },
        "list": [{
                "guid": "{00000000-0000-0000-ba88-000000000002}",
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "name": "Git Bash",
                "background": "#012456",
                "hidden": false
            },
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings": [

        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        {
            "command": {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },

        // Press Ctrl+Shift+F to open the search box
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        {
            "command": {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        },
        { 
            "command": { 
                "action": "openSettings", 
                "target": "settingsUI" 
            }, 
            "keys": "ctrl+shift+s" 
        }
    ]
}
``

**Comment by zadjii-msft** [comment]
Weird. I pasted that into my own settings file and I can't repro this. What editor are you using to modify the file? I'm worried that there's a stray character that's messing up your file for some reason.

**Comment by Piot1998** [comment]
I am using Visual Studio Code

**Comment by zadjii-msft** [comment]
Well, that's probably fine then. This is gonna sound ridiculous, but what if you copied the entire text of the file from here on github, pasted it into a new file, then moved that file to be `settings.json`. Does that fix the issue?

**Comment by Piot1998** [comment]
I mean, what exactly should I do? Can you clarify?

**Comment by Piot1998** [comment]
Should I copy the entire contents of the settings.json file to a new file and then move it to settings.json? Please tell me what to do exactly because I would like to know more

**Comment by Omega172** [comment]
Instead of copying the settings.json from the repo just delete the contents of your settings.json and it should recreate it. And see if that works.

**Comment by Piot1998** [comment]
Ok. And where to save this new settings.json file. The new one. In the directory related to windows terminal or rather it may be on the desktop. Sorry for this question, but I want to be 100% sure

**Comment by zadjii-msft** [comment]
You can just go ahead and save that file right where the old `settings.json` lives. The idea here is that we're totally rewriting the settings file, to hopefully blow away whatever bad byte is hiding in it.

**Comment by Piot1998** [comment]
Ok. Just one more question. Should I delete the old settings.json file or overwrite it with the new one?

**Comment by zadjii-msft** [comment]
@Piot1998 To be safe, let's just delete the file entirely first.

**Comment by Piot1998** [comment]
Finished. What's next?

**Comment by zadjii-msft** [comment]
Try booting the Terminal?

**Comment by Piot1998** [comment]
But what exactly should I do? Create this settings.json file again, save it on the desktop or rather in the old location of this file where the old settings.json file was?

**Comment by zadjii-msft** [comment]
If you just reboot the terminal without creating a new `settings.json` file, then the Terminal will create you a fresh `settings.json` that should work. If that works, then open up that file, delete all the contents, paste in the contents from your old file here on github, and save the file.

**Comment by Piot1998** [comment]
Because I completely deleted this settings.json file from its default location

**Comment by zadjii-msft** [comment]
Yep, that should be fine. The Terminal will work without a settings file - it will create one for you when it's first launched.

**Comment by Piot1998** [comment]
This is the contents of the old settings.json file
```js

// This file was initially generated by Windows Terminal 1.0.1401.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    // "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "defaultProfile": "{00000000-0000-0000-ba88-000000000002}",
    "profiles": {
        "defaults": {
            // Put settings here that you want to apply to all profiles. 
        },
        "list": [{
                "guid": "{00000000-0000-0000-ba88-000000000002}",
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
                "name": "Git Bash",
                "background": "#012456",
                "hidden": false
            },
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings": [

        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        {
            "command": {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },

        // Press Ctrl+Shift+F to open the search box
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        {
            "command": {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ]
}
```

**Comment by Piot1998** [comment]
Like you said, the terminal created a new settings.json file the first time you started the terminal. That file was created by the windows terminal by default on first run, and I didn't touch anything there

**Comment by zadjii-msft** [comment]
Okay, so you've 
* Deleted `settings.json`
* Re-launched the terminal 

Does the Terminal work now? If not, is it displaying an error (and what _exactly_ is the error message)? 

I believe it should be working with the default settings. If it is, then I'd go ahead and add parts of your old `settings.json` file into the newly generated one bit at a time, and keep re-launching the Terminal to make sure it keeps working.

**Comment by Piot1998** [comment]
Ok. I'll check it. So now I can easily implement this command from this site https://www.bleepingcomputer.com/news/microsoft/windows-terminal-now-has-a-hidden-graphical-settings-editor/. Because I want to add that this windows terminal is not a preview version, but a normal one.

**Comment by zadjii-msft** [comment]
Nope. The Settings UI is still only in the preview builds. From the [release notes](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-7-release/):

> version 1.6, which includes all of the features from this [previous blog post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-6-release/) except for the settings UI. 

If the settings file is working for you again, I'm gonna go ahead and close this issue out. Thanks!

**Comment by Piot1998** [comment]
Thanks
