### ISSUE TITLE
Support maximising split panes

### ISSUE THREAD

**Issue by perfectlysensible** [microsoft/terminal#9311]
# Description of the new feature/enhancement
It would be useful to be able to toggle between the current split pane view, and a maximized view of the current pane.

Maximizing a split pane involves making the current split pane occupy the whole window. This is a useful feature in cases where the user temporarily wants a fullscreen view of the current split pane (e.g. viewing a wide log file) but later wants to use the original layout size.

# Proposed technical implementation details (optional)

A user would commonly use this feature with a shortcut (e.g. ctrl-alt-m -> maximize). Typing the shortcut once would make the currently selected split pane occupy the whole window; typing it again would restore the split pane layout.

**Comment by zadjii-msft** [comment]
We actually already support this feature! We call in "zooming" a pane. It was first added in #6989, in Preview v1.3. I don't think it's currently bound to a key by default, but it is in the command palette. You can add a keybinding for it with:

```json
{ "keys": "ctrl+alt+m", "command": "togglePaneZoom" }
```

/dup #996

**Comment by perfectlysensible** [comment]
Thanks @zadjii-msft, I did search for existing feature requests but apparently missed searching for existing features.

I've tried out the feature just now, it's awesome. 👍
