### ISSUE TITLE
How to build and run the WPF samples?

### ISSUE THREAD

**Issue by StefanKoell** [microsoft/terminal#9314]
Hi,

I was able to clone and build the terminal solution using the PowerShell build script but I have no idea on how to run the WPF sample and further include the terminal in a WPF/WinForms project. Can this be added to the docs?

Thanks,
Stefan

**Comment by zadjii-msft** [comment]
I'm not sure that the WPF controls are really ready for production use in a 3rd party application, hence why they're not documented better. They're used for Visual Studio, but that's with the understanding that we're working fairly closely with that team, so if we break that control, we can work with them to get it fixed. I'd be worried that if you did start using it, we'd change the interface out from underneath you and break you unintentionally. 

I'd follow #6999, which is tracking the work that still needs to be done in this area. When it is ready for consumption, I assure you there will be useful docs ☺️ 

/dup #6999

**Comment by mitchcapper** [comment]
@StefanKoell if you are still interested in this I put together a more straightforward example in #15053 note it is still not designated for any sort of production use, but at least shows a WPF terminal app.

**Comment by StefanKoell** [comment]
@mitchcapper this is awesome. Thanks for putting that together. Will definitely look into that!

cheers,
Stefan
