### ISSUE TITLE
Settings dialog

### ISSUE THREAD

**Issue by aybiss** [microsoft/terminal#9316]
# Description of the new feature/enhancement

Instead of spending time creating settings in json, documenting settings, fielding bug reports from people who can't find settings in json, and describing how to use the settings in json, how about creating the json file ONCE in entirety, and (optional) using it to create a settings dialog? 

# Proposed technical implementation details (optional)

1. Instead of shipping a json file with like 2 out of the hundreds of options and then spending time documenting the possible options and values, put all the options in the json with descriptions of the values. 

2. Having created the json, second phase is to use it for populating a settings dialog in the program.

**Comment by zadjii-msft** [comment]
Please search before filing new issues.

/dup #1564
/dup #6800
