### ISSUE TITLE
Tab is faded unselected tab color after choosing a color or creating a new pane

### ISSUE THREAD

**Issue by douglaswth** [microsoft/terminal#9319]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

Select a color for the the current terminal tab or create a new pane in a tab that already has a color selected.

# Expected behavior

The color I selected would be the tab color.

# Actual behavior

The tab shows as the faded version of the color that an unselected tab would have, but when I mouse over, or do some other action like switching panes, the right color does appear.

![windows_terminal_color_faded](https://user-images.githubusercontent.com/77890/109561188-aa3e7a80-7a91-11eb-851d-a0e84a9687c9.gif)

**Comment by zadjii-msft** [comment]
Hmm. This is another version of #8948, which potentially a cleaner repro. Might help us track this down. I'm gonna merge this with the other thread. Thanks!

/dup #8948
