### ISSUE TITLE
Faild to reload settings, when add keybinding for the Settings UI

### ISSUE THREAD

**Issue by smykhailov** [microsoft/terminal#9321]
# Environment

```none
Windows build number: Windows 10
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

Add keybindings to open Settings UI into settings.json

```
  "keybindings": [
    { "command": { "action": "openSettings", "target": "settingsUI" }, "keys": "ctrl+shift+," },
```

# Expected behavior

Settings UI opens

# Actual behavior

the following error 
![image](https://user-images.githubusercontent.com/5530260/109566355-07631c00-7ae4-11eb-8b6d-bf8197e0c70d.png)

**Comment by zadjii-msft** [comment]
The settings UI isn't in 1.6 stable, it's still only in Preview. You'll need to use Windows Terminal (Preview) to try out the settings UI.
