### ISSUE TITLE
Is it possible to change the font size of Windows Terminal

### ISSUE THREAD

**Issue by Sys-key-design** [microsoft/terminal#9323]
I was just wondering if it is possible to change the font size of text on Windows Terminal. I don't see anything related to font size in the settings. The font size is really big for some reason and I don't know how to make it smaller. Thanks

**Comment by goodandrewsoft** [comment]
Please, anybody  ....

**Comment by zadjii-msft** [comment]
@goodandrewsoft Yep, it absolutely is possible to change the font size - there are plenty of answers in [the docs](https://docs.microsoft.com/en-us/windows/terminal/). Presumably, OP found those docs, and closed the issue on their own.

**Comment by unphased** [comment]
I found a way to override an action by finding the action list [here](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions), so now i can use alt-+ or alt-= to change the font size, however the ctrl-+ and ctrl-= bindings remain and I need these to not be there anymore. I can probably work around it by overriding them with  "action": "sendInput" commands, but please tell me if I can do it without defining that.
