### ISSUE TITLE
Update should be on the menu

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/terminal#9327]
There are myriad ways to install WT. I should have to remember which path on which machine

# Proposed technical implementation details (optional)
Add menu item. Bonus -- add automatic update options

Click update rather than scurrying around to remember how to update and even if there is an update available.

**Comment by zadjii-msft** [comment]
Yea I mean, the officially supported way to install the Terminal is with the Store. That'll auto-update the Terminal for you. If you've installed the Terminal via some other mechanism (chocolatey, winget, just downloading the package off of the Releases page, etc) then you've kinda taken things into your own hands. It'd be impossible for the Terminal to know of all the different ways on installing the Terminal and then invoke the proper way of updating the app. That would quickly become unmaintainable.
