### ISSUE TITLE
Settings UI Simplified Chinese translation recommendation

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#9328]
Inspired by #9238, this is the recommendation for Simplified Chinese.

| Key | Recommendation | Comment|
| -- | -- |-- |
| Globals_LaunchModeMaximized.Content | 最大化 |  There should be an adjective here |
| Globals_LaunchModeFocus.Content | 专注 | The translation of "focus" is a mistake. This term is being used widely, even inside windows ("Focus assist"). It should be used here, too. |
| Globals_LaunchModeMaximizedFocus.Content | 最大化专注 | Same as above |
| Globals_LaunchMode.HelpText |  Change ”焦点" to "专注" | Same as above |
| Globals_WindowingBehavior.Header | 新建实例行为 or 创建实例行为 | The current translation means "the behavior of newly created instance", which is confusing. It should be "the behavior of *creating* instance. |
| Globals_AlwaysOnTop.Header | 置于顶层 | The current translation is hard to understand. This is the term used in Task Manager, which is way better. |
| Globals_CopyOnSelect.Header | 自动将所选内容复制到剪贴板 | The current translation is very wrong. The current translation means "can't copy the selection to clipboard". | 
| Globals_CopyFormatNone.Content | Drop the "只用于" | |
| Globals_TabSwitcherMode.HelpText | Drop the "终端“ | |
| Globals_TabSwitcherModeMru.Content | 独立窗口，按最近使用顺序切换 | The translation is very misleading. I can't say my translation is perfect, but it's definitely better.|
| Globals_TabSwitcherModeInOrder.Content | 独立窗口，按选项卡显示顺序切换 | Same as above. | 
| Globals_TabWidthMode.Header| Drop the "模式" |  |
| Globals_TabWidthModeEqual.Content | 等宽 | The current translation is wrong. |
| Globals_TabWidthModeCompact.Content | 紧凑 | The current translation is hard to understand. |
| Globals_TabWidthMode.HelpText | Change the translation of "compat" to "紧凑" | Same as above|
| Globals_KeybindingsDisclaimer.Text | Change "密钥” to "快捷键“ | The current translation is the "keys" as in "SSH keys".|
| Nav_ProfileDefaults.Content | Change "图层” to "层“ | The term "图层" refers to the layer in image processing. |
| Profile_CursorShape.Header | Drop the "的" | Simplified & cleaner. |
| Profile_CursorHeight.Header | Drop the "的" | Same as above. |
| Profile_ScrollbarVisibility.Header | Drop the "的" | Same as above. |
| Profile_ScrollbarVisibilityHidden.Content | Drop the "已" | There should be an adjective here. | 
| Profile_AcrylicHeader.Text | 亚克力效果 | The current translation is a chemical term. See #8992 | 
| Profile_UseAcrylic.Header | 启用亚克力效果 | Same as above. |
| Profile_Hidden.Header | Drop the "个人资料" | The current translation is the profile as in "Facebook profile". |
| Profile_CloseOnExit.Header| 关闭行为 | This is way cleaner & easy to understand. |
| Profile_CursorShapeFilledBox.Content | Change to "实心框" | The current translation does not make sense. |
| Profile_CursorShapeEmptyBox.Content | Change to "空心框" |  The current translation is a bit vague. |
| Profile_StartingDirectoryUseParentCheckbox.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Drop the ”从中" | |
| Profile_SuppressApplicationTitle.HelpText | Drop the "可”. Change "禁止" to "忽略" | |
| Profile_AntialiasingMode.Header | Change "消除锯齿" to "抗锯齿" | This is the more tech-savvy saying |
| Profile_AntialiasingModeAliased.Content | 无  | The current translation is very wrong. 'Aliased' means "do not use antialiasing". |
| Profile_SnapOnInput.Header | Append "位置" at the end | To make it less confusing.  |
| Profile_HistorySize.Header | Drop the "调整“ | Same as above. |
| Profile_BellStyleVisual.Content | 视觉（闪烁任务栏） | I don't get it why "flash" is left as it is. |
| Profile_BellStyleAudible.Content | 声音 |  Just my two cents. |

**Comment by zadjii-msft** [comment]
Thanks for this! I'm gonna assign this to @DHowett to communicate this to the loc team, when he gets done moving 😄

**Comment by driver1998** [comment]
focus here is a window state, and not the same as in "focus assist".
"焦点" should be more appropriate.

**Comment by skyline75489** [comment]
@driver1998 Actually no. The "focus mode" here is a mode that hides the toolbar & everything, leaves only the console content, not the "focus" you think it is.

**Comment by driver1998** [comment]
> @driver1998 Actually no. The "focus mode" here is a mode that hides the toolbar & everything, leaves only the console content, not the "focus" you think it is.

Okay now it makes sense, thanks for the explanation.

**Comment by skyline75489** [comment]
np. 

I'm open to suggestions. Just make sure you really use the terminal & understand how every option works.

**Comment by skyline75489** [comment]
@DHowett can I ask for a link to internal tracking ticket for this? I'm kinda upset when I found none of these in 1.8.1032.0.

**Comment by DHowett** [comment]
@skyline75489 I'm so sorry; this one fell so far down my inbox that I missed it while I was moving.

MSFT-32515306

**Comment by skyline75489** [comment]
It's ok. It's not really an urgent task, anyway.

I'm glad we can ship new versions of Terminal through Microsoft Store nowadays. So people won't really stuck with the inbox version. I hope this can be included before 2.0.

**Comment by reli-msft** [comment]
Some items not mentioned:
 * `Globals_KeybindingsDisclaimer.Text`
   * Recommended translation "下面是目前已绑定的快捷键，可以通过编辑 JSON 配置文件加以修改。"
   * Term "Key" is incorrectly translated to "密钥", which means keys used in encryption.
 * `Profile_AntialiasingModeAliased.Content`
   * Recommended translation "保留锯齿"
   * Term "Aliased" is incorrectly translated to "别名", which means alternate name.

**Comment by skyline75489** [comment]
Closed. Move on to #10174.
