### ISSUE TITLE
Cannot type in Chinese full-angle punctuations in SSH connections

### ISSUE THREAD

**Issue by zhangzq** [microsoft/terminal#9329]
When I used terminal to connect SSH server, I couldn't type in any Chinese full-angle punctuation. Normal Chinese characters are OK. 

And there is no problem in powershell and wsl window.

The terminal version is 1.5.10411.0. The problem remains when I upgraded to newest version 1.7.572.0.

**Comment by skyline75489** [comment]
See #9035 #9283.

**Comment by zadjii-msft** [comment]
Yea, this sounds like those issues. Thanks!

/dup #9035 
/dup #9283
