### ISSUE TITLE
Add a specific alias for Windows Terminal Preview

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#9333]
# Description of the new feature/enhancement

It's may be useful to create a specific alias to target Windows Terminal preview for example `wtp.exe` like you do with the `wtd.exe`  when the terminal is build from source.
With that we can choose which version of Windows terminal we want when we invoke it by command line.
You can also keep the `wt.exe` alias for the preview version to allow us to select in the settings app the "default" version of windows terminal we want. for `wt.exe`

# Proposed technical implementation details (optional)

I think this is what the `CascadiaPackage/Package-Pre.appxmanifest` should look like

``` xml
      <Extensions>
        <uap3:Extension Category="windows.appExecutionAlias" Executable="wt.exe" EntryPoint="Windows.FullTrustApplication">
          <uap3:AppExecutionAlias>
            <desktop:ExecutionAlias Alias="wtp.exe" />
          </uap3:AppExecutionAlias>
        </uap3:Extension>
        <uap3:Extension Category="windows.appExecutionAlias" Executable="wt.exe" EntryPoint="Windows.FullTrustApplication">
          <uap3:AppExecutionAlias>
            <desktop:ExecutionAlias Alias="wt.exe" />
          </uap3:AppExecutionAlias>
        </uap3:Extension>
------
      <Extensions>
```

**Comment by zadjii-msft** [comment]
Hey so the last time we had this discussion was over at: #6788

> Preview and Stable are only intended to be installed side-by-side and switched between when you're worried about the stability of Preview. We're not intending both channels to be in active simultaneous use. If you're encountering an issue that means you make to switch between them more than once in a single session I'd rather we just fix the issue instead of bandaging it with another app execution alias. If you are, please do let us know what those issues are.


I'm gonna redirect discussion to that thread, to try and keep the discussion in one place. Thanks!

/dup #6788
