### ISSUE TITLE
When you create custom default profile and launch wt via context menu item on any folder, it launches custom profile instead of command prompt

### ISSUE THREAD

**Issue by barisahmet** [microsoft/terminal#9334]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.844]
Windows Terminal version (if applicable): 1.7.572.0
```

# Steps to reproduce

- Create a custom profile with command "ssh", (ie. Command line: "**ssh user@myserver**")
- Set default profile to newly created one
- Open explorer and right click in any folder
- Choose "**Open in Windows Terminal**"

# Expected behavior

It should open a cmd instance in selected folder.

# Actual behavior

It logs into server via ssh.

I don't know if this is intended behavior, but it's confusing and I couldn't find a workaround for this.

**Comment by zadjii-msft** [comment]
Yep, that's totally by design. We're tracking "let the user pick which profile to open" in #6111, which would probably fix this for you

**Comment by DHowett** [comment]
However: the “default profile” is like a browser homepage. That’s what you get when you launch the browser, afterall!
