### ISSUE TITLE
Shading behind About Box does not fill whole window after resize

### ISSUE THREAD

**Issue by Lo0oG** [microsoft/terminal#9336]
# Environment

Windows build number: 10.0.18363.1379
Windows Terminal version (if applicable): 1.7.572.0

# Steps to reproduce

Make the window reasonably small and show the about box. Then dismiss the about box and make the window bigger.  Then show the About box again.

Also, just resizing the window while the about box is shown does not resize the shaded area.

# Expected behavior

# Actual behavior

![image](https://user-images.githubusercontent.com/50969206/109644679-b12ac300-7b4d-11eb-98c5-cb5c103b12d4.png)

**Comment by Lo0oG** [comment]
Also seems to similarly affects the Close all tabs and Paste Warning dialogs.
![image](https://user-images.githubusercontent.com/50969206/109646025-8f324000-7b4f-11eb-826b-c0947bb366e4.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2380 for more discussion.

/dup #2380
/dup microsoft/microsoft-ui-xaml#3577
