### ISSUE TITLE
Settings UI navigation view has a transparent background when opened as an overlay

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#9337]
# Environment

Windows build number: Version 10.0.18363.1316
Windows Terminal version (if applicable): 1.7.572.0 (preview)

# Steps to reproduce

1. Open the Settings UI.
2. Make the Terminal window narrow so the _NavigationView_ is forced to open as an overlay.
3. Open the navigation view.

# Expected behavior

The navigation panel should have an opaque background, covering the content that it is overlaying.

# Actual behavior

The navigation panel seems to have a transparent background, so you can still see the content below it, making the menu items unreadable.

![image](https://user-images.githubusercontent.com/4181424/109659475-9f521b80-7b5f-11eb-8552-35994a2e5979.png)

**Comment by zadjii-msft** [comment]
Holy gosh that looks bad. Unfortunately, I don't have a local repro for this 😢. It looks like the blur from the acrylic just is _not_ getting applied. Does acrylic work anywhere else in the app? I'm trying to think of somewhere else that would have in-app acrylic to test. I'm not sure there's any in the Terminal. Maybe try the XAML Controls Gallery app? That should have a sample NavigationView to compare with

**Comment by j4james** [comment]
Ah OK. I have "Transparency Effects" turned off in the in the System settings. If I turn that on (and change my power mode to "Best Performance", which is needed for acrylic to work), then the navigation panel displays correctly. If I turn "Transparency Effects" off, it immediately goes transparent again. In other apps, the acrylic area just becomes completely opaque.

**Comment by j4james** [comment]
Just checked the XAML Controls Gallery (version 1.2.17.0 in case that makes any difference), and the _NavigationView_ example has an acrylic overlay which works correctly, i.e. it's acrylic when "Transparency Effects" are enabled, and opaque when disabled.

**Comment by huoyaoyuan** [comment]
Sounds like the fallback brush of acrylic is set to transparent. In practice, it should be set to non transparent.

**Comment by zadjii-msft** [comment]
> Sounds like the fallback brush of acrylic is set to transparent. In practice, it should be set to non transparent.

Huh, I didn't think that you could set a fallback brush to Transparent. I bet that's exactly happening. 

It's extremely trivial to repro this by disabling "transparency effects" in the Settings app, so yea I bet we're doing something wrong here.

**Comment by mdtauk** [comment]
Has someone failed to add a fallback colour for the Acrylic brush, or is it maybe not being used like it should be?

**Comment by huoyaoyuan** [comment]
I remember that no fallback would cause transparent be used.
