### ISSUE TITLE
Scroll wheel does not work in settings UI

### ISSUE THREAD

**Issue by otaconjh** [microsoft/terminal#9340]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.7.572.0

```

# Steps to reproduce

Open Windows Terminal tab & settings UI tab
# Expected behavior

Scrolling with mouse wheel should work on both tabs

# Actual behavior

![scroll_test](https://user-images.githubusercontent.com/41576511/109673583-142c5200-7b6e-11eb-8e2d-4d8bc2101b00.gif)

**Comment by zadjii-msft** [comment]
oh my gosh is this that weird trackpad bug? Lemme try finding that in the history.

@otaconjh What mouse are you using to scroll the Terminal? Is it by any chance a synaptics trackpad?

**Comment by otaconjh** [comment]
It occurred on my work laptop but I was using a bluetooth mouse. 'HID-compliant mouse'  in Device Manager

**Comment by otaconjh** [comment]
- Hovering buttons highlights them fine
- Scrolling does not work anywhere in the settings UI
- Scrolling does not work in the Command Palette

Issues with scrolling are with mouse only, scrolling works fine when a trackpad is used. Have tested with multiple mice.

**Comment by zadjii-msft** [comment]
> Issues with scrolling are with mouse only, scrolling works fine when a trackpad is used. Have tested with multiple mice.

what the heck? That's even weirder than I had expected. I'm gonna leave this open for now. My guess is that the hack we're doing to manually pass mouse events into the `TermControl` is what's making the mouse work for you in terminal tabs, but not the settings tab (or command palette). However, I'm not sure we can do that same hack for those UI elements. I don't know how to narrow the issue down more at this point, unfortunately. I'd bet that this is a Xaml Islands bug, but  unsure where the root cause is exactly.

https://github.com/microsoft/PowerToys/issues/3400 also looks like another case of this, an one where they're similarly seeing this with a mouse, not a trackpad. @otaconjh Out of curiosity, which mice did you try?

**Comment by jackemerson** [comment]
> [microsoft/PowerToys#3400](https://github.com/microsoft/PowerToys/issues/3400) also looks like another case of this, an one where they're similarly seeing this with a mouse, not a trackpad. @otaconjh Out of curiosity, which mice did you try?

Just to add some additional information, this issue occurs for me across PowerToys' and Windows Terminal's settings panels. It occurs only on my desktop, and not my laptop.

## Desktop

The issue occurs independent of mouse used. Tested with the following:
- Logitech MX Master 2S
- Logitech G703
- Steelseries RIVAL
- Razer Viper Ultimate

<sub>_...I may need to take a look at my mice hoarding habit._</sub>
<details>
  <summary>System Info</summary>
  Microsoft Windows Pro 64-bit [Version 10.0.19042.928]
  Windows Terminal Version: 1.7.1033.0
  Microsoft PowerToys Version: 0.35.0

  CPU: Intel i7-7700K
  GPU: NVIDIA GTX 1070

  User DPI Setting: 120 DPI (125 percent)
  System DPI Setting: 96 DPI (100 percent)

  Monitor, Primary: 27", 2560 x 1440 (32 bit) (144Hz) Acer XB271HU
  Monitor, Second: 34", 3440 x 1440 (32 bit) (60Hz)   Dell U3419W
</details>

## Laptop
For my laptop (Dell XPS 9360), there are no issues with scrolling the settings panel, with either the trackpad or with a mouse (tested with MX Master 2s & G703).

<details>
  <summary>System Info</summary>
  Microsoft Windows Home 64-bit [Version 10.0.19042.867]
  Windows Terminal Version: 1.7.1033.0
  Microsoft PowerToys Version: 0.35.0

  CPU: Intel i7-7500U
  GPU: NVIDIA GTX 1070
  User DPI Setting: 144 DPI (150 percent)
  System DPI Setting: 144 DPI (150 percent)

  Monitor: 13", 1920 x 1080 (32 bit) (60hz)
</details>

Changing the DPI and/or resolution for my desktop and laptop did not (respectively) allow me to, or stop me from, scrolling the settings panel.

I'll test this further with a restart following the DPI and/or resolution change, and report back.

**Comment by landonth** [comment]
I am also unable to scroll in Terminal v1.8.1444.0 Settings, I'm using a Kensington Expert Mouse Trackball USB on WIndows 10 ver 1909 build 18363.1379

**Comment by jaortizco** [comment]
I have the same problem, I can scroll everywhere with my touchpad (Synaptics) except in the settings tab. It works fine when I use my Bluetooth mouse. 

Windows Terminal
Version: 1.8.1521.0

**Comment by timadye** [comment]
I had this same issue, but only in a specific set of circumstances, and now have a work-around. Here's what I observed:

  * Scroll doesn't work in Settings tab only (works in Terminal tabs)
  * Only with an external mouse (Evoluent VerticalMouse2; not tested with other external mice). Trackpad scrolling works on two different laptops.
  * Only when I have [X-Mouse Button Control](https://www.highrez.co.uk/downloads/XMouseButtonControl.htm) enabled and have the (default) option to "scroll window under cursor". Note that the behaviour is the same whether or not Windows Terminal is the active window.

That last point indicates that it's something going on with XMBC. If it were a problem, I could take it up with them. But actually it's easier just to "Disable Scroll Window Under Cursor".
![XMBC](https://user-images.githubusercontent.com/115933/126824449-3111d4c2-31ee-438f-92ae-0eae75fffe4d.PNG)
That option doesn't seem to do anything - I guess Windows now has this behaviour built-in, so there's no need to have XMBC do it. I didn't see a problem like this before I saw it in Windows Terminal Settings, so there is some funny interaction between the two programs.

I hope that gives a clue as to what's going on for other people who aren't so lucky to have an easy fix as (it looks like) I have. It might be possible for a developer to reproduce the issue by installing XMBC (making sure that option is not selected) and using an external mouse.

So this isn't a problem for me, but I hope my observation helps.
Tim.

Windows Terminal v1.9.1942.0.
X-Mouse Button Control v2.19.2.
Windows 10 20H2.

**Comment by jackemerson** [comment]
Well, you're absolutely right. I've run XMBC for so long, I didn't even consider it.

**Comment by landonth** [comment]
I also use  X-Mouse Button Control and @timadye's workaround resolved the issue for me. Same for https://github.com/microsoft/PowerToys/issues/3400

**Comment by zadjii-msft** [comment]
Wow that's crazy. Glad someone was able to get to the bottom of this!

**Comment by landonth** [comment]
> Wow that's crazy. Glad someone was able to get to the bottom of this!

for posterity sake, this issue hasn't been isolated / confirmed to be caused by X-Mouse Button Control or due to a conflict with this software exclusively. Only that a workaround has been found in this case. According to reports here and in the still open Power toys sister issue, This maybe also be happening with Synaptics and/or Logitech input devices, due to a conflict or flaw with their configuration software, drivers, and/or Windows.

**Comment by rozele** [comment]
This issue also repro's when using WizMouse.

**Comment by rozele** [comment]
In case anyone is interested, I implemented a workaround for this for a react-native-windows app built on XAML Islands:
https://gist.github.com/rozele/a4b26810b9a4f68373e421a49d06a5ab

**Comment by rozele** [comment]
Also, just noticed that the bug "goes away" if you open Spy++ and put it in focus while trying to scroll the Settings tab 😮
