### ISSUE TITLE
Crashes during Background Customization [1.7.572.0]

### ISSUE THREAD

**Issue by rileysea** [microsoft/terminal#9341]
# Environment

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal Preview 1.7.572.0
```

# Steps to reproduce
Open Settings menu, select Base Layer under Profiles, Click Appearance Tab, Click Browse for Background Image Path.

The app consistently crashes after attempting to open the browse file explorer window. The "Use desktop background" option works fine.

# Expected behavior

I should be able to modify my background for the terminal without having to edit the JSON settings file. I want to use the UI to do this work.
# Actual behavior
See steps to reproduce. It's crashing after clicking "browse".

**Comment by zadjii-msft** [comment]
Are you running the Terminal elevated / as an admin?

**Comment by rileysea** [comment]
> Are you running the Terminal elevated / as an admin?

Yes. Behavior is consistent as admin/non-admin

**Comment by zadjii-msft** [comment]
Hmm. Bizarre that you're seeing this unelevated as well. That's not what you want. We're generally already tracking this over in #8957 so I'll make a note there. Thanks!

/dup #8957
