### ISSUE TITLE
NewTerminalArgs should include `suppressApplicationTitle`

### ISSUE THREAD

**Issue by darkdescendant** [microsoft/terminal#9345]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.7 Preview

Any other software?
```

# Steps to reproduce

1) Add a command to the settings.json file similar to this:

```
        {
            "command": 
            {
                "action": "newTab",
                "index": 1,
                "profile": "<whatever profile you want>",
                "startingDirectory": "<Whatever you want>",
                "tabTitle": "Test Title"
            },
            "keys": "ctrl+1"
        },
```

2) Save file.
3) In Terminal Window, press `ctrl+1` to create a new tab based on that command.

# Expected behavior

Expected (Ver 1.6): Tab title is "Test Title"

# Actual behavior

Actual: Tab title is the path the terminal window/tab is currently in.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps the profile runs a program that changes the title. How is the profile defined?

**Comment by cinnamon-msft** [comment]
If you want the tab title to persist, you'll have to add `"suppressApplicationTitle": true,` to the profile you're opening. Otherwise the tab title is being set by the command then reset by the shell.

**Comment by KalleOlaviNiemitalo** [comment]
If the `"splitPane"`, `"newTab"`, and `"newWindow"` actions support `"tabTitle"`, then perhaps they should support `"suppressApplicationTitle"` as well.

**Comment by zadjii-msft** [comment]
> If the `"splitPane"`, `"newTab"`, and `"newWindow"` actions support `"tabTitle"`, then perhaps they should support `"suppressApplicationTitle"` as well.

I actually don't hate that. Wouldn't be that hard to plumb through. I'm gonna re-open this just to track that idea. Thanks!

**Comment by Don-Vito** [comment]
On it.
