### ISSUE TITLE
The mouse does not work in third-party applications.

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#9348]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): Version: 1.7.572.0

Any other software?
Far manager, musikcube, NTop
```

# Steps to reproduce

The mouse does not work in third-party applications. Neither the mouse cursor nor the scroll wheel.  The cursor shape and color settings (`cursorShape`,`cursorColor`) from the configuration file (`settings.ini`) are also ignored.   
In PowerShell (Windows and Core) and in Command Prompt, everything works without problems.

# Expected behavior

Working mouse and settings from the configuration file in all applications.

# Actual behavior

The mouse does not work in third-party applications. The cursor settings (shape and color) are ignored.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #376 for more discussion.

/dup #376
