### ISSUE TITLE
[FR] Add ability to inherit starting directory when launching from the context of other apps

### ISSUE THREAD

**Issue by Kein** [microsoft/terminal#9349]
# Description of the new feature/enhancement
Just as the title say, inherit the working directory from the context of the app that launches it if possible. 
For example, [Total Commander](https://www.ghisler.com/) has a command line you can launch default `cmd` from and it will inherit current working/active directory.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
You can already do this with the commandline args to `wt.exe`. If you launch `wt.exe -d .` it will inherit the CWD of the caller. `wt -d c:\windows\system32` and it'll launch in `c:\windows\system32`. Does that work for you?

**Comment by Kein** [comment]
Yes it works albeit not exactly the way current cmd does it.
Hmm, is there a way to set config up so if Terminal is called directly via shortcut on desktop or tile in Start it will use `startingDirectory`, otherwise, it will use `-d .` by default. Basically, is there way to somehow distinguish context?
I know I can use `-d .` as a default startup command but this will apply to every single launch, which is not always desirable.

**Comment by zadjii-msft** [comment]
Unfortunately, no. There's no good way to distinguish between those types of launches. #3547, https://github.com/microsoft/terminal/issues/878#issuecomment-538511693 and https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 have more details.

**Comment by Kein** [comment]
At least you could have alias `-d .` to empty `-d` or another flag that will do `-d .` automatically to reduce the crumblesomeness of the approach.
