### ISSUE TITLE
Windows Terminal Preview closing or crashing

### ISSUE THREAD

**Issue by casret** [microsoft/terminal#9350]
# Environment

```none
Windows build number:  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable):  1.7.572.0

Any other software?  WSL2 Ubuntu
```

# Steps to reproduce

Not sure how to repro, I've had the terminal shutdown on me several times today (I think it may be related to the new version that was pushed out).  I'm not sure if it's closing or crashing, but I always have a few tabs open so I would expect that I get the "close all tabs" prompt if I was closing the app by mistake.  I'm not sure where I would find any crash logs if there are any.  The WSL environment is still running some daemon processes when I start the terminal back up, so I know it's not crashing.

**Comment by skyline75489** [comment]
I think this is probably #6726.

**Comment by casret** [comment]
Ah thanks, that could certainly be it, I'll keep an eye out to see if it coincides with an update in the future.
