### ISSUE TITLE
How do I start a new tab "launched as admin" ?  Im missing that option.

### ISSUE THREAD

**Issue by NN33NN** [microsoft/terminal#9351]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment]
Well there isn't an option yet. This is what we called "mixed elevation", see #1032 #5000.

**Comment by satoshi0x** [comment]
This is an insane project I just wanted to say it worked great right clicking to launch as an admin for the first tab :P

**Comment by zadjii-msft** [comment]
Yea, and unfortunately mixed elevation isn't exactly going to be possible. We are working on other QoL improvements (#8455) to make working in mixed-elevation scenarios, but each elevation context is going to need its own window. 

/dup #632
