### ISSUE TITLE
scrollToBottom command makes viewport jump between the top and the bottom of the output buffer

### ISSUE THREAD

**Issue by et342** [microsoft/terminal#9353]
# Environment

```none
Windows build number: [10.0.21292.1010]
Windows Terminal commit: [7b1a660e590012893407a64f4321f01ba74a6e9b]
```

# Steps to reproduce

- `Ctrl+Shit+End` is bound to `scrollToBottom`
- Have some text in the output buffer exceeding the height of the terminal window
- Scroll to the the middle of the buffer, not to the top or the bottom.
- Start repeatedly pressing `Ctrl+Shift+End`

# Expected behavior

- Viewport jumps to the bottom of the buffer and stays there.

# Actual behavior

- Viewport first jumps to the *top* of the buffer and then jumps between the bottom and the top of the buffer on each keystroke.

**Comment by zadjii-msft** [comment]
WOAH yea that's wrong. Good catch, thanks!

**Comment by Don-Vito** [comment]
On it
