### ISSUE TITLE
Unable to load font X, using font X instead?!?

### ISSUE THREAD

**Issue by greggman** [microsoft/terminal#9360]
# Environment

```none
Windows build number: Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce

Run Windows Terminal on my machine (sorry)

# Expected behavior

It runs normally

# Actual behavior

It displays this nonsense message

![WindowsTerminal_BGD4W2SnLW](https://user-images.githubusercontent.com/234804/109840715-b857eb00-7c8b-11eb-92fe-f5ad9b5c2810.png)

Was working until I let the Microsoft Store upgrade it 10 minutes ago

**Comment by DHowett** [comment]
HA! Sorry! That's a really funny bug. If you change the `b` in your config file (`Jetbrains`) to `B` (`JetBrains`)... does it go away?

@miniksa you may like this one

**Comment by DHowett** [comment]
What seems to be happening is that we're asking the OS for a font with the wrong case, and it's saying "I couldn't find that. Found this really similar one instead" and we dutifully present that ... "error" ... to the user.

**Comment by zadjii-msft** [comment]
Maybe we should relax the scenario where we display that error - if we pick one with the same (case-insensitive) name, then maybe just skip the warning.

**Comment by miniksa** [comment]
I like @zadjii-msft 's idea. Just do an insensitive compare and don't show if it matches.

**Comment by skyline75489** [comment]
Sorry is #9157 the same as this? I think that one is also worth noticing.

**Comment by greggman** [comment]
It was a case issue but ... it worked before the latest update so some change took it from case insensitive to case sensitive.

**Comment by zadjii-msft** [comment]
The warning was only added in 1.6 (see #8207), so that's what happened there 😉

**Comment by vibonacci** [comment]
![image](https://user-images.githubusercontent.com/9674553/111022416-e4cdde80-83d2-11eb-844e-cd7f6f06515c.png)

Very funny.

**Comment by DHowett** [comment]
Yes, that is the central thesis of this bug report. Have you tried the suggested workaround?

**Comment by miniksa** [comment]
/dup #9375 
I will be handling this case in the PR attached to the dupe I'm linking this to.

Thanks
