### ISSUE TITLE
Tabs on left

### ISSUE THREAD

**Issue by krishvk** [microsoft/terminal#9361]
Can we have tabs on left and with a matching theme as the terminal itself. WIll be scifi like

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+%22tabs+on+left%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #835 for more discussion.

/dup #835
