### ISSUE TITLE
Make the Settings drop down able to switch back to the json

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#9362]
# Description of the new feature/enhancement
It appears the settings.json has become unbound and using the previous keybinding for it still opens the Settings UI. I can add a custom keybinding for the settings.json but I usually am lazy and simply click on the Settings drop down button as it's quicker and easier for me.  So I'd like the ability to switch out the default experience for the Settings drop down. 

# Proposed technical implementation details (optional)
Add a global setting that allows the user to switch out the default experience. This should be able to be set from both the Settings UI and the settings.json.

**Comment by DHowett** [comment]
I don't hate this idea. @zadjii-msft -- i'd rather make this part of the "edit the menu to put ANY ACTION in it" arc though. WDYT?

**Comment by zadjii-msft** [comment]
Yea, we should unify this with that effort. The spec for #1571 originally just had "we're gonna force [Settings, Feedback, About]" into the dropdown always. But now there are multiple possible "Settings" entries that make sense, so maybe those should be customizable too. Hmm. That might require a bit more noodling on, and an addendum to [#1571 - New Tab Menu Customization.md](https://github.com/microsoft/terminal/blob/main/doc/specs/%231571%20-%20New%20Tab%20Menu%20Customization/%231571%20-%20New%20Tab%20Menu%20Customization.md)

**Comment by WSLUser** [comment]
I agree that it should be considered part of that effort. I was just hoping to have something possibly in place for 1.8 and wasn't sure if a slightly different approach could be used while waiting for the New Tab Menu Customization. Alternatively, that would make a great 1.8 feature if possible (I'm sure everyone who uses custom keybindings and is told by the Settings UI to use the json would appreciate it too due to the format changes the UI does to the json).
