### ISSUE TITLE
JSON schema URL still points to 1.5 release schema

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#9363]
The aka.ms link https://aka.ms/terminal-profiles-schema used for the settings JSON still points to https://raw.githubusercontent.com/microsoft/terminal/release-1.5/doc/cascadia/profiles.schema.json and should probably be https://raw.githubusercontent.com/microsoft/terminal/release-1.6/doc/cascadia/profiles.schema.json.

Or do you wait a while until adoption numbers from Windows Store are up from previous releases?

**Comment by DHowett** [comment]
@cinnamon-msft please fix!

**Comment by DHowett** [comment]
We're supposed to update the redirect as part of release engineering. Thanks @heaths!

**Comment by DHowett** [comment]
I've updated the aka link. May take a bit to propagate!
