### ISSUE TITLE
Needs an amazing icon! 😃

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#937]
The current Windows Terminal icon looks a bit like a placeholder next to other Microsoft icons:

![image](https://user-images.githubusercontent.com/172594/58168179-8a0b4600-7c85-11e9-83ea-8b961bf18ca0.png)

I'm presuming the Microsoft folk may already have an amazing in-house designer working on the icons (question: do you get designers from other teams? Can you get the vscode icon designer? The Office icon designer? They do amazing work.)

But it's worth making an issue just in case the community feel like contributing something.

Only requirements I can see are:

 - Look like a Windows icon (Windows Terminal is Windows specific)
 - Not be specific to a particular shell - can't look too specifically like `pwsh`, `bash` or `cmd`.
 - Have dark and light mode variants

**Comment by mdtauk** [comment]
This will be worked on. #910 started this discussion and Myself and the awesome @itsmichaelwest even contributed some ideas...

**Comment by mikemaccana** [comment]
Oh sweet - I'll close this one and move my comment there.
