### ISSUE TITLE
PgUp and PgDown to navigate

### ISSUE THREAD

**Issue by Filip-Tomasko** [microsoft/terminal#9372]
# Description of the new feature/enhancement

Currently (as far as I know) the only way to navigate the Windows Terminal is to use the scroll wheel. You can't use arrow keys as they are used for auto-completion selection. 

My idea is to make the buttons Page Up and Page Down work with Windows Terminal. Maybe they just move up one line or up a whole page.

**Comment by zadjii-msft** [comment]
The Terminal already supports scrolling with the keyboard, you just need more modifiers 😃 

https://github.com/microsoft/terminal/blob/2961a104afac20cc3a9aad6c70e1518fa1250253/src/cascadia/TerminalSettingsModel/defaults.json#L353-L358

If you really want scrolling on pgup/pgdown, you could add something like the following to your keybindings:
```json
{ "command": "scrollUpPage", "keys": "pgup" }, 
```

And of course, if you really don't want `ctrl+shift+pgup` to scroll, you can unbind it with:
```json
{ "command": "unbond", "keys": "ctrl+shift+pgup" }, 
```

**Comment by Filip-Tomasko** [comment]
Thank you so much! Sorry for making an issue for such a thing

**Comment by kurisu-red** [comment]
This doesn't work. Setting it to `pgup` doesn't allow for scroll with only those keys without modifiers.
