### ISSUE TITLE
Enhancement of the right context menu for tab bar. 

### ISSUE THREAD

**Issue by MicyToy** [microsoft/terminal#9373]
# Description of the new feature/enhancement
I wonder if we can add an enhancement for the tab bar, such as "Duplicate", "Duplicate with Last command".

Many thanks to you for the wonderful terminal!  🥇 

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
This isn't the first time someone requested this feature. I don't think #1571 covers this, though.

**Comment by MicyToy** [comment]
@skyline75489 thanks for your reply.

I don't mean the dropdown menu. I want to say the right context menu of "Title bar".

**Comment by skyline75489** [comment]
Yeah I know. See https://github.com/microsoft/terminal/issues/3158#issuecomment-774434692 for similar requests.

**Comment by MicyToy** [comment]
Got it.

**Comment by zadjii-msft** [comment]
Yep, this is a good idea. We can only really do "duplicate tab" - the terminal has no concept of what the last command in each tab was. But "Duplicate Tab" is definitely a good idea. I've linked this up with #1912. Thanks!
