### ISSUE TITLE
On some computers, OSC 9;4;3;100 ST shows progress indication on tab but no animation on taskbar icon

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#9374]
# Environment

```none
Windows build number: 10.0.19042.804
Windows Terminal version (if applicable): 1.7.572.0 Preview
PowerShell 7.1.2
```

# Steps to reproduce

Run this from PowerShell:

````
Write-Host "`e]9;4;3;100`a"
````

# Expected behavior

The progress indicator should be shown on the Windows Terminal tab, and the taskbar icon should show a progress animation:

![2021-03-04-12-32-03 (Small)](https://user-images.githubusercontent.com/12860484/109958311-62fcf780-7ce6-11eb-85f3-02667d7310c3.gif)

# Actual behavior

On some computers, the tab animation is present but the taskbar icon animation is not (the taskbar icon changes colors, that's all):

![2021-03-04-12-26-40 (Small)](https://user-images.githubusercontent.com/12860484/109958471-8de74b80-7ce6-11eb-9e72-35f05069a77b.gif)

**Comment by zadjii-msft** [comment]
Weird. Clearly, the taskbar knows something's supposed to happen, but then just, doesn't? Seems like an external bug on the shell. I'll dig through the internal bug tracker, see if anything looks similar.

**Comment by zadjii-msft** [comment]
@sba923 Any chance you have System Properties / Performance Options, "Animations in the taskbar and Start Menu" disabled?

see:
https://stackoverflow.com/a/10645907

**Comment by sba923** [comment]
Where is this exactly? Found this: 
![image](https://user-images.githubusercontent.com/12860484/109985102-b2eab700-7d04-11eb-9a3f-409c3e496e7e.png)

**Comment by sba923** [comment]
How can I troubleshoot this?

**Comment by zadjii-msft** [comment]
Frankly, I've got no idea. On the PC where the Terminal's progress indicator doesn't work in the taskbar, do other apps? Like, I think Edge will show download progress in the taskbar?

**Comment by sba923** [comment]
Yes, Edge progress indication **does** work

So do `OSC9;4;1;xST`, `OSC9;4;2;100ST` and `OSC9;4;4;100ST`

Only the "indeterminate" status is broken.

**Comment by zadjii-msft** [comment]
Weird. I'm not sure I know of any other apps that use the indeterminate progress, but if we could find one, that would be useful to help validate.

**Comment by DHowett** [comment]
How about this one?

Settings > Ease of Access > Display

![image](https://user-images.githubusercontent.com/189190/111349270-fb806980-864e-11eb-9c23-6e95c040bc03.png)

**Comment by sba923** [comment]
Oh, it's off. I swear: I didn't do it ;-)

![image](https://user-images.githubusercontent.com/12860484/111349573-88dcb180-8681-11eb-9a3a-b9178c868d9b.png)

**Comment by sba923** [comment]
That was the culprit!

**Comment by sba923** [comment]
@DHowett  is the winner.

**Comment by DHowett** [comment]
Excellent! Thanks.

**Comment by sba923** [comment]
> That was the culprit!

Note: something keeps turning that off. I RD to that machine from my (WFH) work laptop everyday. Could that be the reason? Will need to find a way to script turning that on...

**Comment by sba923** [comment]
> Excellent! Thanks.

It seems that _something_ turns that option back off under some circumstances. Any clue?

**Comment by sba923** [comment]
> > Excellent! Thanks.
> 
> It seems that _something_ turns that option back off under some circumstances. Any clue?

Just reinstalled my home desktop (21H1 10.0.19043.1165.amd64fre.vb_release.191206-1406). Animations were turned off by default... How come?

**Comment by zadjii-msft** [comment]
> Animations were turned off by default... How come?

Honestly, no idea. Though I would be interested to know!

**Comment by sba923** [comment]
> > Animations were turned off by default... How come?
> 
> Honestly, no idea. Though I would be interested to know!

Someone at MSFT should know 😆

**Comment by sba923** [comment]
> Submitted https://aka.ms/AAehwy4

Can anyone (internally within MSFT) get some traction on this issue? (as far as I can tell, it is *not* closed!)
