### ISSUE TITLE
wordDelimiters not working inside tmux with [shift]+[left mouse click]

### ISSUE THREAD

**Issue by Kristijan** [microsoft/terminal#9382]
# Environment

```none
Windows build number: 10.0.18363.1379
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
Ubuntu using WSL 1
tmux 3.2-rc2 (set-option -g mouse on)

I run tmux from another Linux server, so the flow is:
Windows Terminal --> Ubuntu WSL 1 --> SSH to remote host --> tmux
```

# Steps to reproduce

I updated from Microsoft WindowsTerminal 1.5.10271.0 to 1.6.10571.0 and have been using the following configuration for wordDelimiters `"wordDelimiters": " ()\"':,;<>~!@#$%^&*|+=[]{}~?│"`.

With 1.5.10271.0, the wordDelimiters were honored in both my Ubuntu WSL 1 zsh shell (double click left mouse button), and inside tmux (shift + double click left mouse button).

With 1.6.10571.0, the wordDelimiters are honored in my Ubuntu WSL 1 zsh shell (double click left mouse button), but not inside tmux (shift + double click left mouse button). Holding the shift key and double clicking to select text from within tmux only partially selects text (such as entire words), and doesn't honor the wordDelimiters confugration.

# Expected behavior

The expected behavior is that selecting text from within tmux with (shift+double click left mouse button) works as it did in Microsoft WindowsTerminal 1.5.10271.0.

# Actual behavior

The actual behavior is that selecting text from within tmux with (shift+double click left mouse button) only partially selects text with Microsoft WindowsTerminal 1.6.10571.0.

**Comment by Don-Vito** [comment]
@DHowett - I will try to take a look in the next few days.

**Comment by Don-Vito** [comment]
So the problem is following:  currently shift+click selects a single cell. When the second tap occurs, instead of applying the double-click logic we simply extend the selection, resulting in partial selection. 

To address this I suggest to extend selection extension only with shift+single-click. I will issue a PR with more details.
