### ISSUE TITLE
Shell Profile not added if source field

### ISSUE THREAD

**Issue by Alouxndre** [microsoft/terminal#9385]
# Environment
Windows 10 Pro 20H2
Windows Terminal Preview
Version: 1.7.572.0

# Steps to reproduce

I have a lot of Shell profiles with different GUID (some with "source" field).

Now I want to add a new one.

The profile I want to add is:

```
            {
                "guid": "{19cb11a0-758c-494a-906a-890361b34509}",
                "hidden": false,
                "name": "Workspace",
                "source": "Windows.Terminal.PowershellCore"
            }
```

But it does not work The profile is not added.

Now if I remove the source field -> The profile is added

Is the "source" field handled in the last version of Terminal ?

Terminal last update is on March 1 2021

**Comment by skyline75489** [comment]
You can not do this at this moment. See https://github.com/microsoft/terminal/issues/8333#issuecomment-730278183

**Comment by zadjii-msft** [comment]
Yea, the `source` field is _only_ for auto-generated profiles. Get rid of that, and set the commandline to something. You can even toss out the `guid` if the `name` is unique.
