### ISSUE TITLE
Wrong mouse pointer when hovering an http link

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#9387]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19042.844]
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce
- type `echo "http://www.foo.fr"`
- move the mouse over the text that was printed and hold the `ctrl` key

# Expected behavior
The mouse pointer should turn into a hand indicating that's a link that can be clicked.

# Actual behavior
The mouse pointer still shows an arrow.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7563 for more discussion.

/dup #7563
