### ISSUE TITLE
Ubuntu font rendering incorrectly (extremely wide)

### ISSUE THREAD

**Issue by ebrodlic** [microsoft/terminal#9393]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.844]
Windows Terminal version (if applicable): Version: 1.6.10571.0

Ubuntu 20.04.2 LTS for WSL2
Ubuntu (Font) 0.83 Dalton Maag Ltd
```

# Steps to reproduce

In the Windows Terminal settings.json, set the entry `"fontFace": "Ubuntu"` for any profile and list out the directory structure.

# Expected behavior

Entries get printed out with a font that resembles the Ubuntu font in the font preview app:
![image](https://user-images.githubusercontent.com/8537027/110130163-04f51080-7dc9-11eb-8f0b-730b9c8ea2ab.png)

# Actual behavior

The rendered font has the look of the Ubuntu one, but the horizontal spacing of characters is extremely wide (due to excess whitespace):
![image](https://user-images.githubusercontent.com/8537027/110129721-89935f00-7dc8-11eb-8571-6d42151b1a60.png)

Example with command-prompt profile using the same font:
![image](https://user-images.githubusercontent.com/8537027/110129871-b9dafd80-7dc8-11eb-93be-b24f08589962.png)

# Additional Info
I am not sure where the Ubuntu (Font) 0.83 Dalton Maag Ltd font came from, as I cant seem to uninstall it with the fonts app. (Perhaps while installing Ubuntu LTS via the store?).

Weirdly, the font was actually rendering fine until today, when Terminal complained about the inability find the "Ubuntu-R" font which was installed and set previously by me. (Off of the Ubuntu Font official site). The custom font has the same version (0.83), but the actual registered name was "Ubuntu-R", which now suddenly shows just as "Ubuntu" and conflicts with the built-in one.

Reinstalling the custom downloaded one has no effect on Windows Terminal.

Details:
![image](https://user-images.githubusercontent.com/8537027/110131156-26a2c780-7dca-11eb-8ed5-ba3309c381bc.png)

Custom downloaded font:
![image](https://user-images.githubusercontent.com/8537027/110131302-4b973a80-7dca-11eb-9612-770c3d345e3e.png)

After install:
![image](https://user-images.githubusercontent.com/8537027/110131633-a466d300-7dca-11eb-9c68-b7a04f14fe68.png)

**Comment by KalleOlaviNiemitalo** [comment]
There is related discussion in <https://github.com/microsoft/terminal/issues/3498> and <https://github.com/microsoft/terminal/issues/7596>.

**Comment by ebrodlic** [comment]
Thanks for chipping in @KalleOlaviNiemitalo but those discussions seem to be related to line (vertical) height?
Concretely line height, not font size.

I am talking about horizontal whitespace between characters (almost as if its some forced extra wide monospaced font), and I am quite happy with vertical line height.

**Comment by skyline75489** [comment]
Funny that this happens to me a lot when I'm using Linux terminals with a non-monospace font. Can you try the UbuntuMono to see if it helps?

**Comment by zadjii-msft** [comment]
Yea, I agree with @skyline75489's thought here. Can you try "Ubuntu Mono" instead? Just plain "Ubuntu" technically isn't a monospace font, so we're probably calculating the wrong width for all those glyphs.

**Comment by ebrodlic** [comment]
I've tried "Ubuntu Mono" and it looks great!
Thanks for the tip @zadjii-msft and @skyline75489 

Is WT intended to be using monospaced fonts?

**Comment by zadjii-msft** [comment]
@ebrodlic Yea, monospaced fonts are definitely the way to go. The Terminal will let you set whatever font you want, but monospaced ones are the only ones that'll really work right. If you set it to Papyrus and get weird rendering, that's on you 😆
