### ISSUE TITLE
Shift+Click on a profile opens a new window

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#9395]
# Description of the new feature/enhancement

We already ship `Alt+Click` to split a new pane of a profile from the dropdown menu. Now that we have the `newWindow` action, it would be cool if we allowed `Shift+Click` to open a new window of a profile from the dropdown menu.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Okay yea, I'll upgrade https://github.com/microsoft/terminal/projects/5#card-50760137 to this one.

**Comment by KalleOlaviNiemitalo** [comment]
Should and could the same modifier keys apply to the jump list and the shell extension as well?
