### ISSUE TITLE
Windows Terminal asks to close unprompted, does so even after telling it no, leaves processes hanging

### ISSUE THREAD

**Issue by Daiz** [microsoft/terminal#9398]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce

Unsure. Occasionally, seemingly some time after waking Windows 10 up from sleep, the Terminal on its own will prompt for "do you want to close all tabs?" and even after being told no, it still closes itself. This can also leave certain things hanging, for example I was running a webpack dev server in one of my terminals, which is still alive and now I have to kill it via Task Manager to get rid of it.

# Expected behavior

1 Windows Terminal shouldn't randomly prompt me to close it without reason.
2. Even if it has a reason for wanting to close itself (updating?) it should respect the fact that I said "no".
3. When closing, active running processes should get killed accordingly.

# Actual behavior

1. Windows Terminal seemingly randomly prompts user to close all tabs.
2. Closes itself even if told no.
3. Can leave running processes hanging in limbo.

**Comment by j4james** [comment]
Do you perhaps have the _App Updates_ option in the Microsoft Store set to update automatically? That would possibly explain what happened. The problem of the app terminating because of an update is being tracked in issue #3915.

**Comment by Daiz** [comment]
That seems to have been the case, so the shutting down is most likely tied to the same issue. The only thing I can't say for sure is whether the hanging processes are tightly tied to the updating issue, but it does seem to only happen when WT forcefully closes itself.

**Comment by zadjii-msft** [comment]
Yea, we see a lot of these a few days after an update is pushed. We're working on pursuing an internal fix.

/dup #3915
/dup #6726
