### ISSUE TITLE
Always crashes with 0xc0000022

### ISSUE THREAD

**Issue by alancnet** [microsoft/terminal#9399]
# Environment

```none
Windows build number: Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? WSL2
```

# Steps to reproduce

1. Install Windows Terminal
2. Run Windows Terminal
![image](https://user-images.githubusercontent.com/2042102/110213150-ad4fb700-7e53-11eb-8d3b-b5ab36504b49.png)

# Expected behavior

I am expecting Windows Terminal to launch

# Actual behavior

Windows Terminal always fails with 

```
---------------------------
wt.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000022). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

This happens regardless of the version I install, or the method I use to install, including Microsoft Store, chocolatey, or Github Releases.
I've also cleared out my user settings to no avail.

**Comment by alancnet** [comment]
I continued to investigate this issue, and used Process Explorer to see what was going on. I got Access Denied on `vcruntime140.dll` in `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe`. Notably, Users lacked the execution privilege, so I took ownership of the file (previously owned by SYSTEM) and added Full Control to users. This resolved the issue.. but it is still a mystery to me how this could happen.

**Comment by zadjii-msft** [comment]
@DHowett is this another one of those deployment issues we've been seeing? 

Taking full permission of something in `.../WindowsApps` is probably not the _best_ long term solution, but it's certainly weird that this was happening at all

**Comment by sungvzer** [comment]
I'd like to add that, while running WindowsTerminal.exe or wt.exe from explorer results in a failure, running it from the Search Bar or an already instance of wt or pwsh makes it run properly.

**Comment by DHowett** [comment]
This points to a permissions issue on `WindowsApps` itself -- not the Terminal directory.

Can you share the output of ...

```
icacls "\Program Files\WindowsApps"
```

?

From an admin shell, of course.

Mine are:

```
\Program Files\WindowsApps NT SERVICE\TrustedInstaller:(F)
                           NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                           S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(GR,GE)
                           NT AUTHORITY\SYSTEM:(F)
                           NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                           BUILTIN\Administrators:(CI)(RX)
                           NT AUTHORITY\LOCAL SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\NETWORK SERVICE:(OI)(CI)(RX)
                           NT AUTHORITY\RESTRICTED:(OI)(CI)(RX)
                           BUILTIN\Users:(Rc,S,RD,REA,X,RA)
```

These are the expected permissions. Anything else somewhat contravenes expectations and can cause all sorts of app activation issues.

**Comment by sungvzer** [comment]
There it is!

```
C:\Program Files\WindowsApps\ NT SERVICE\TrustedInstaller:(F)
                              NT SERVICE\TrustedInstaller:(OI)(CI)(IO)(F)
                              S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(RX)
                              S-1-15-3-1024-3635283841-2530182609-996808640-1887759898-3848208603-3313616867-983405619-2501854204:(OI)(CI)(IO)(RX)
                              NT AUTHORITY\SYSTEM:(F)
                              NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
                              BUILTIN\Administrators:(CI)(RX)
                              NT AUTHORITY\SERVIZIO LOCALE:(OI)(CI)(RX)
                              NT AUTHORITY\SERVIZIO DI RETE:(OI)(CI)(RX)
                              NT AUTHORITY\RESTRIZIONI:(OI)(CI)(RX)
                              BUILTIN\Users:(Rc,S,RD,REA,X,RA)
                              SALVIO\Salvio:(OI)(CI)(F)
```

**Comment by DHowett** [comment]
If you remove `SALVIO\Salvio` (`icacls "C:\Program Files\WindowsApps" /remove SALVIO\Salvio`), does the issue go away?

**Comment by DHowett** [comment]
I'm gonna close this one out in favor of /dup #9452 -- please follow up there with the permissions discussion. I'd love to know if that helps, because if it does we can put together a FAQ document.
