### ISSUE TITLE
Explorer context-menu is missing when Windows Terminal is installed side-by-side with Windows Terminal Preview

### ISSUE THREAD

**Issue by conioh** [microsoft/terminal#9401]
# Environment

```none
Windows build number: 19042
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
Windows Terminal Preview 1.7.572.0
```

# Steps to reproduce

1. Install Windows Terminal from the Microsoft Store.
2. Install Windows Terminal Preview from the Microsoft Store.
3. Open a folder in Windows Explorer, for example `C:\`.
4. Right click.

# Expected behavior

Two distinct options: _Open in Windows Terminal_ and _Open in Windows Terminal Preview_.

Windows Terminal and Windows Terminal Preview are distinct packages. They have distinct package names and AUMIDs. They can be installed independently. They can run independently. They have distinct configurations in separate directories.

I expect to be able to run both of them (or at least the one of my choosing!) from Windows Explorer.

# Actual behavior

Note the icon is for Windows Terminal _Preview_ and indeed it opens the Preview.

![image](https://user-images.githubusercontent.com/10606081/110220480-a2863800-7ece-11eb-88fc-818401e5ab43.png)

# Possible implementation

I suspect using distinct CLSIDs for the two packages would suffice.

If you can have different strings, icons, etc. having different CLSIDs shouldn't be that hard.

![image](https://user-images.githubusercontent.com/10606081/110245912-f85ded00-7f6d-11eb-9fa5-785e7baa10de.png)

**Comment by KalleOlaviNiemitalo** [comment]
Also <https://github.com/microsoft/terminal/issues/6416>. I expect that distinct CLSIDs would indeed be required.

**Comment by zadjii-msft** [comment]
Yea, we're tracking this in #6416. Thanks!

/dup #6416
