### ISSUE TITLE
Microsoft Terminal sets TERM=xterm-256color instead of TERM=ms-terminal

### ISSUE THREAD

**Issue by pagerc** [microsoft/terminal#9402]
Microsoft Terminal is *not* `XTerm` and does not conform with `xterm-256color` and therefore should not claim conformance to its terminfo capabilities.

Please update the terminfo database (per #8303) with Thomas Dickey to match more closely to Microsoft Terminal as it is today, and change the default TERM value from `xterm-256color` to `ms-terminal`.

A possible workaround is to add configuration options so that users can configure their MSTerm profile and specify the TERM variable that will be set instead of using the default `xterm-256color`.

**Comment by pagerc** [comment]
Other resolutions are to add configuration options so that users can configure their profile and specify the TERM variable that will be applied instead of using the default `xterm-256color`.

**Comment by pagerc** [comment]
In a possibly related issue, setting WSLENV=TERM/u causes TERM to be undefined in MS Terminal, with wsltty it gets set to `wsltty`. This might not be relevant, but seems tangentially related.

**Comment by DHowett** [comment]
We don’t set TERM, WSL does. Sorry!

**Comment by pagerc** [comment]
> We don’t set TERM, WSL does. Sorry!

Then that's the bug, that MS Terminal doesn't provide a means of overriding the TERM environment variable at launch time of the chosen shell.

**Comment by DHowett** [comment]
Unfortunately, WSL sets that environment variable _after_ it launches. It’s hard to override things that happen after you’ve ceded control :)

**Comment by pagerc** [comment]
Must be a discrepancy in how WSLTTY and MS Terminal launch WSL. I think WSLTTY is using wslbridge2, so that's probably what it's able to have set the environment on the shell before execing it.
