### ISSUE TITLE
Piping Text to Select-String Shows ANSI Escape Sequences Instead of Color

### ISSUE THREAD

**Issue by chrisbehanna** [microsoft/terminal#9404]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Windows 10 Enterprise 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? PowerShell Core 7.1.2
```

# Steps to reproduce

`git ls-remote | Select-String git_gc`

# Expected behavior

A listing of the matching remote branches, with the string "git_gc" highlighted in color

# Actual behavior

ff0f34e411366ca6a25b7e94ff2df0a1827e3bc8        refs/heads/build/←[7mgit_gc←[0m

**Comment by DHowett** [comment]
This is because git is disabling ANSI coloring shortly after it launches, even when it is redirected. This is a long-standing Cygwin/msys2 bug.

**Comment by chrisbehanna** [comment]
> This is because git is disabling ANSI coloring shortly after it launches, even when it is redirected. This is a long-standing Cygwin/msys2 bug.

Then how does `git log --graph --color --decorate` apply color?

**Comment by DHowett** [comment]
So truthfully, it's a little more nuanced than that. There's a more detailed write-up here: https://github.com/microsoft/terminal/issues/4921#issuecomment-599135352

There's some combination of process entry/exit and mode transition that results in VT being disabled when it should be enabled when git or a subprocess exits after control has returned to something that required VT to be on. In the `git log` case, nobody appears to be exiting and reconfiguring the console.

**Comment by chrisbehanna** [comment]
Thanks for the additional detail.  For now, I'll just use `Select-String -NoEmphasis` when running `git ls-remote` to look for particular branches.
