### ISSUE TITLE
Symbolic links created in additional panes/tabs don't work

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/terminal#9405]
# Environment

```none
Windows build number: Windows 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? PowerShell 7.1.2
```

# Steps to reproduce

1. open Windows Terminal with a default profile of PowerShell 7.1.2
2. in a folder X, create a directory `target`: `New-Item -ItemType Directory -Path target`, and a symbolic link `link` pointing to `target`: `New-Item -ItemType SymbolicLink -Path link -Value target`
3. open a new pane/tab, navigate to X, and create another symbolic link `link2` pointing to `target`

# Expected behavior

Both `link` and `link2` are valid symbolic links pointing to `target`

# Actual behavior

Only `link` is a valid symbolic link pointing to `target`. Any symbolic links created in a pane/tab that isn't the original one, doesn't work.

**Comment by DHowett** [comment]
This seems to me like a powershell issue? All terminal is doing is running two copies of PowerShell.
