### ISSUE TITLE
ARM build: terminal canvas has incorrect margins

### ISSUE THREAD

**Issue by meta-inf** [microsoft/terminal#9407]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.844]
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? 
```

This is the ARM version of Windows. My screen resolution is 1920x1080 with 100% scaling.

# Steps to reproduce

* Install Ubuntu 20.04 from windows store, using either WSLv1 or v2 instance.
* Launch `vim` or `neovim` (installed from `apt`) 

# Expected behavior

The margin of the screen canvas should be correct, similar to the behavior of `cmd.exe` (or windows terminal on x86 windows) as shown below:
![correct margins (using `cmd.exe`)](https://user-images.githubusercontent.com/4392226/110244055-e85b0300-7f97-11eb-9ac6-229b7850f83f.png)

# Actual behavior

There are wide extra margins around the vim screen, as shown below (best seen with a light vim colorscheme)

![image](https://user-images.githubusercontent.com/4392226/110244074-07599500-7f98-11eb-9e17-35c0f9ceb4c6.png)

**Comment by DHowett** [comment]
This is because vim is setting a background fill color that differs from the rest of the terminal background. I believe we have another issue tracking this- @zadjii-msft?

**Comment by meta-inf** [comment]
Just noted the config file on my x86 machine has set "padding" to "0,0,0,0", while the default is "8,8,8,8". Sorry... feel free to close this.

**Comment by zadjii-msft** [comment]
No worries, glad you figured it out!
