### ISSUE TITLE
Allow tab drag between windows (Chromium like)

### ISSUE THREAD

**Issue by raythurnevoid** [microsoft/terminal#9408]
# Description of the new feature/enhancement
It would be great to being able to drag tabs between different windows like in edge/chrome.
![image](https://user-images.githubusercontent.com/53383860/110245032-e7a77a00-7f61-11eb-888c-737816f9474b.png)

**Comment by KalleOlaviNiemitalo** [comment]
This seems like the "tab merge" part of <https://github.com/microsoft/terminal/issues/1256>.

**Comment by zadjii-msft** [comment]
Sure is a duplicate.

/dup #1256
