### ISSUE TITLE
Unable to access settings in Windows Terminal

### ISSUE THREAD

**Issue by Verson-tech** [microsoft/terminal#9409]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Do you have any more info? At all? We can’t really help you without even knowing your version number.

**Comment by Verson-tech** [comment]
![Capture](https://user-images.githubusercontent.com/77786047/110250100-5694cb00-7f82-11eb-8551-fc2253ca165b.JPG)

**Comment by Verson-tech** [comment]
fixed via VS Code
