### ISSUE TITLE
Static folder to link and open wt.exe

### ISSUE THREAD

**Issue by Qynklee** [microsoft/terminal#9414]
Windows Terminal 's installation path always change after update or change version. So some settings like "_Right-click menu_" dont work after update and need to be update too.
I think we can choose a static-link for call wt.exe to execue. It's easy and make everything better to reconfigure our settings (special when we reinstall windows because some reasons).
Thanks for your read 😄 
![image](https://user-images.githubusercontent.com/23394219/110287584-5e537e80-8019-11eb-8e48-ccd0ad1fc6f3.png)

**Comment by KalleOlaviNiemitalo** [comment]
If you enable the `wt.exe` _app execution alias_, then the alias resides in a directory whose name does not change when you upgrade Windows Terminal. This is not the same as `wt.exe` in the Windows Terminal installation directory.

**Comment by zadjii-msft** [comment]
Yea, the app execution alias is the expected solution here.
