### ISSUE TITLE
Handle error with try catch blocks system()

### ISSUE THREAD

**Issue by Goru1890** [microsoft/terminal#9415]
Does anyone know how I can handle system() errors with try catch in C++ ?
I want to throw an excepctions when a error ocurres in the terminal, like Cuda Out of Memory or something else
Now I have this, but of course it's stucked in the system() line

![](https://cdn.discordapp.com/attachments/787383971012411414/818418846222254100/unknown.png)

![](https://cdn.discordapp.com/attachments/787383971012411414/818418928119185418/unknown.png)

**Comment by KalleOlaviNiemitalo** [comment]
If the [system](https://docs.microsoft.com/cpp/c-runtime-library/reference/system-wsystem?view=msvc-160) function detects the error, then it returns 0 and sets `errno`; so you should check the return value. However, the program that `system` runs may fail in ways that `system` does not detect.

None of this seems specific to Windows Terminal, though.

**Comment by zadjii-msft** [comment]
Yea, this isn't really a Terminal-specific issue. This almost seems like a question better suited for StackOverflow. 

Thanks!
