### ISSUE TITLE
Arrow glyph not rendering vertically centered (ohmyzsh)

### ISSUE THREAD

**Issue by ebrodlic** [microsoft/terminal#9416]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19042.844]
Windows Terminal (if applicable): Version: 1.6.10571.0
```

# Steps to reproduce

Copy the arrow glyph: `➜`
Paste into windows terminal
Select the pasted text with the mouse to more easily see the vertical position related to the full line height

# Expected behavior

Glyph is centered vertically, examples with text editors or browsers:
![image](https://user-images.githubusercontent.com/8537027/110331594-9bbb0a80-801f-11eb-93e7-5c05d9357234.png)
![image](https://user-images.githubusercontent.com/8537027/110331634-a70e3600-801f-11eb-88e2-5233b3782879.png)

# Actual behavior

Glyph is lowered below center:
![image](https://user-images.githubusercontent.com/8537027/110331816-e046a600-801f-11eb-9d02-7038550417d2.png)
![image](https://user-images.githubusercontent.com/8537027/110331928-fe140b00-801f-11eb-8247-cadad821c465.png)
![image](https://user-images.githubusercontent.com/8537027/110331968-0cfabd80-8020-11eb-866b-9f15a5151a34.png)

# Additional info

Tested with multiple fonts in Windows Terminal (Cascadia Code and all the PL variants, Consolas etc) but same result.

**Comment by hodjaev** [comment]
Hi @ebrodlic, I have the same issue
![image](https://user-images.githubusercontent.com/69766846/110684410-2e110900-81ee-11eb-8c77-f323c902a003.png)

**Comment by DHowett** [comment]
/dup #6864 this comes down to a choice Terminal made about glyphs that don't "fit" in their boxes. That arrow is spilling out of its box.
