### ISSUE TITLE
Closing the SettingsUI with a keystroke?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9419]
X-ing the SettingsUI with the mouse will always close it (unconditionally, BTW).  Is there an equivalent single keystroke?  I have only found Ctrl+F4 which works only if the tab (where the "X" is) has been given focus.

Thanks!

**Comment by zadjii-msft** [comment]
<kbd>Ctrl+Shift+W</kbd> should work, or whatever you have `closePane` bound to.

**Comment by vefatica** [comment]
Thanks!  Remembering it will be the hard part.  I have a (physical) key which sends "exit[Enter]" and that's what I use in all my shells.
