### ISSUE TITLE
Une fenêtre un peu plus large pour PowerShell, avec la pub de la nouvelle version qui passe a la ligne pour 1 caractère ce n'est pas top

### ISSUE THREAD

**Issue by alaing13** [microsoft/terminal#9420]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Could you share a screenshot perhaps? It's impossible to know what exactly you're reporting without more details. Version numbers for the Terminal, for PowerShell, those might be helpful too. As it is, there's nothing more we can do with this blank issue. If you can provide more details, we'd be happy to reopen this thread.
