### ISSUE TITLE
scp in this Terminal cannot resolve local paths with Chinese characters in them

### ISSUE THREAD

**Issue by driftee** [microsoft/terminal#9421]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): WindowsTerminalPreview_1.7.572.0

Any other software?
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

# Steps to reproduce
command line:
```
scp [-r(for folder)] [local path(with Chinese chars in it)] [remote path]
```
And then enter password for authentication.

# Expected behavior
In original powershell, the scp works well as it does. It can resovle Chinese chars in the local path and do the transmission. 

# Actual behavior
In this terminal, scp won't take out the transmission(it says the path does not exist). Some other commands like `ls`, `cat`, `rm`, `mv`, work well in this situation.

**Comment by skyline75489** [comment]
I can't repro this locally. Please provide the exact failure you encountered. Screenshots would be nice.

**Comment by driftee** [comment]
See in F disk, I have a folder named '文档' and want to use scp to upload a file and a forlder to a server, both of which failed. And some garbled code can be seen.
![1](https://user-images.githubusercontent.com/48539371/110424204-6117a780-80dd-11eb-800b-48ae2a00a7d4.png)
Well, I think this may be a problem of scp.  Because I encountered the same problem in original powershell.
![2](https://user-images.githubusercontent.com/48539371/110426897-d6857700-80e1-11eb-8246-c32a367dbb40.png).
