### ISSUE TITLE
" [40;5R" auto appare on new line when i press "Enter" key

### ISSUE THREAD

**Issue by iqianxing** [microsoft/terminal#9423]
# Environment
Windows build number: MSYS_NT-10.0-18363  3.1.7-340.x86_64
Windows Terminal version (if applicable):1.6.10571.0
# Steps to reproduce
1. use ssh connect to remote linux in cmd environment;
2. ```docker exec -it containerName /sh/bin```
3. press enter key, "[40;5R" auto appare on new line 
![image](https://user-images.githubusercontent.com/2938263/110426442-113adf80-80e1-11eb-8fc7-525ae3e881c8.png)

or like bellow:
![image](https://user-images.githubusercontent.com/2938263/110426524-39c2d980-80e1-11eb-9dbb-20a5f2a2c010.png)

**Comment by zadjii-msft** [comment]
Weird. Something's asking for the cursor position, but then not reading the response - it's just echoing it to the input of `sh`. 

Which `ssh` are you using? `ssh.exe` that ships with Windows? `ssh` from a WSL distro? Or some other `ssh`? And which version of `ssh`?

Does this repro if you run `/bin/bash` in the docker container? Or just with `sh`?

**Comment by jdebp** [comment]
People have been hitting these problems from long before Windows Terminal came along, and they are always a matter of a prompt string or a pre/post-input hook of some sort emitting a terminal control sequence that causes the terminal to send back a response, without then reading the response.

I'd say talk to your Linux system's administrator about shell prompts on that machine, except that apparently you _are_ the system administrator.  &#9786;  Check out what is in your prompt shell variables, and your `PROMPT_COMMAND` shell variable.  On many distributions there's often all sorts of stuff, from hooks into `git` to XTerm title manipulation.  This is not a Windows Terminal problem.  It is just obeying the output that your remote Linux system has sent.

**Comment by zadjii-msft** [comment]
Yea, this sure does sound external to me.
