### ISSUE TITLE
New tabs in WT should reload PATH enviroment variable

### ISSUE THREAD

**Issue by NoamDev** [microsoft/terminal#9426]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce

1. Open Windows Terminal
2. Run `echo $env:PATH`
3. Change the PATH enviroment variable
4. Open a new WT tab
5. Run `echo $env:PATH

# Expected behavior

The printed PATH should be the updated PATH enviroment variable
# Actual behavior

the printed PATH is the PATH before the changes (i.e. the PATH of when WT was opened).

**Comment by j4james** [comment]
This sounds like issue #1125.

**Comment by zadjii-msft** [comment]
Yep that's definitely the one we're tracking it in. Thanks!

/dup #1125
