### ISSUE TITLE
Terminal blinking while deleting in git-bash

### ISSUE THREAD

**Issue by timocov** [microsoft/terminal#9430]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.867]
Windows Terminal version (if applicable): 1.7.572.0

Any other software? git-bash v2.30.1.windows.1
```

# Steps to reproduce

1. Open git-bash
2. Press backspace button multiple times in a row

# Expected behavior

No blinking (probably related to #9111).

# Actual behavior

The whole terminal blinking (see attached gif). It looks like it switches text and background colors between them, gut it's just a guess.

Also, I'm able to reproduce it on 2 of 3 my PCs, let me know what I can provide additional to investigate this issue.

git-bash itself works fine.

The gif of the issue:
![terminal-blinking](https://user-images.githubusercontent.com/3112183/110592891-e9548600-818b-11eb-90d6-96062c6cb6db.gif)

Picture of "normal" state (extracted from gif):
![image](https://user-images.githubusercontent.com/3112183/110593006-0c7f3580-818c-11eb-9081-1a00cd7a2508.png)

Picture of "blinking" state (extracted from gif):
![image](https://user-images.githubusercontent.com/3112183/110592962-01c4a080-818c-11eb-88ab-4159b7a917d1.png)

**Comment by Don-Vito** [comment]
@timocov - the blinking you see is a visual bell, which is a feature of git-bash. You can turn it off (will find the link in a second)

**Comment by timocov** [comment]
Oh, really... Thank you so much @Don-Vito!
