### ISSUE TITLE
Display problem when using "less" command

### ISSUE THREAD

**Issue by TypicalSEE** [microsoft/terminal#9431]
Windows: Microsoft Windows [版本 10.0.19041.804]
Terminal: 1.6.10571.0

Hi, I'm using OpenSSH to connect to a remote Linux server under Windows Terminal. But the output of "less -SN" seems not normal. The first screenshot shows it: the 19th line appears besides the 1st line. The second screenshot is the normal output (after I quit and type that command again). Unexpected output were not about a fixed line. Sometimes it's the 1st line overlapping with another line but other times it was some other lines repeating themselves. I had been using Putty to connect to a remote servers before but nerver met this problem so I think it might be a bug of Windows Terminal. Thanks.
![issue](https://user-images.githubusercontent.com/22927497/110595671-47e42900-81b9-11eb-8157-7431ac5bbaa6.png)

![normal](https://user-images.githubusercontent.com/22927497/110595697-4f0b3700-81b9-11eb-82e5-c67261681a66.png)

**Comment by zadjii-msft** [comment]
@TypicalSEE Which version of `ssh` are you using?

**Comment by DHowett** [comment]
This sounds like #9176.

**Comment by TypicalSEE** [comment]
> @TypicalSEE Which version of `ssh` are you using?

"OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5", installed from Windows 10 “Optional Feature”.

**Comment by DHowett** [comment]
In that case, I suspect that you're hitting the screen size change buffering issue in https://github.com/PowerShell/openssh-portable/pull/426. Even though it doesn't look like the screen size is changing, less is turning on the "alternate buffer" which reports a window resize. OpenSSH, until pull 426, had trouble handling the resize event.

If you run OpenSSH 8.1 from the [win32-openssh releases page](https://github.com/PowerShell/Win32-OpenSSH/releases), does it go away?

**Comment by TypicalSEE** [comment]
Downloaded OpenSSH 8.1 from that page and tried it, the problem still exists. By the way, ssh version of my remote server is "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017". Should I also upgrade that one?

**Comment by jdebp** [comment]
Three answers will help the Microsoft (and other) people:
* Does this happen as you scroll up and down?  Or initially when `less` first displays the file?
* What happens when you tell `less` to redraw the screen?
* What is the value of the `TERM` environment variable on the system that is actually running the `less` program?

**Comment by DHowett** [comment]
I apologize. The pull request that fixes the buffering/repeat issue merged on April 2, 2020 but the 8.1 release came out in Dec 2019. I do not know why I thought it might help. :smile:

**Comment by zadjii-msft** [comment]
@TypicalSEE There's now an OpenSSH 8.6 (https://github.com/PowerShell/Win32-OpenSSH/releases/tag/V8.6.0.0p1-Beta), mind trying that one? We think that might have the fix

**Comment by sarbian** [comment]
I had a similar issue and that version fixed it.

**Comment by zadjii-msft** [comment]
I'll count that, thanks for confirming!
