### ISSUE TITLE
ENABLE_VIRTUAL_TERMINAL_PROCESSING is set by default in pseudo console on Windows 10 20H2.

### ISSUE THREAD

**Issue by tyan0** [microsoft/terminal#9432]
# Environment
Windows 10 20H2 (Version 10.0.19042.804)

# Steps to reproduce
1. Compile the following test code.
2. Run the test program in pseudo console (e.g. in WSL).

```
#include <windows.h>
#include <stdio.h>

int main()
{
	DWORD mode;
	GetConsoleMode(GetStdHandle(STD_OUTPUT_HANDLE), &mode);
	printf("%d\n", mode & ENABLE_VIRTUAL_TERMINAL_PROCESSING);
	return 0;
}
```

# Expected behavior
At least on older Windows 10 such as 1809, the result is:
```
0
```

# Actual behavior
On Windows 20H2, the result is:
```
4
```

Is this the intentional behavior?

**Comment by eryksun** [comment]
>Is this the intentional behavior?

Yes. See [src/host/srvinit.cpp](https://github.com/microsoft/terminal/blob/8f9ccc55d16d1f803f01488f8b78d3cf09503fe5/src/host/srvinit.cpp#L155).

**Comment by tyan0** [comment]
Thank you for your quick response. Just a question from my interest, is it possible to disable this flag by default in pseudo console?

**Comment by tyan0** [comment]
I asked just because I was interested. I don't have the scenario in which this behavior causes any problem so far.

**Comment by zadjii-msft** [comment]
@vefatica Sure is. That statement is basically two parts:
1. `CheckDefaultAppPolicy` will get the state of the "default app policy", and stick it into the bool passed in. `CheckDefaultAppPolicy` will return true if it succeeded in looking that value up.
2. Was the "default app policy" enabled?

**Comment by vefatica** [comment]
In that case I'd expect it to look like this:

`if (SUCCEEDED(Microsoft::Console::Internal::DefaultApp::CheckDefaultAppPolicy(&isEnabled)) && isEnabled)`

**Comment by zadjii-msft** [comment]
Meh, stylistic difference. Taking a param by reference means the callee doesn't need to worry about if the out param is null or not. Most of our newer code with out params (as few as those are) uses params by reference, rather than pointers.

**Comment by eryksun** [comment]
> ```
> bool isEnabled = false;
> if (SUCCEEDED(Microsoft::Console::Internal::DefaultApp::CheckDefaultAppPolicy(isEnabled) && isEnabled))
> ```

The only argument of the `SUCCEEDED` macro should be the `HRESULT` that's returned by `CheckDefaultAppPolicy`, in order to get a boolean result of success or not. Negative `HRESULT` values indicate failure. Doing a logical `&&` on an `HRESULT` and a `bool` is incorrect.
