### ISSUE TITLE
Terminal crashes Windows 10X 

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/terminal#9433]
# Environment

```none
Windows build number: Windows 10X 10.0.19578.0
Windows Terminal version (if applicable): v1.6.10571.0

Any other software?
```

# Steps to reproduce

1. Open terminal on Windows 10 X
2. It crashes (Mouse pointer still works)

# Expected behavior

An error message for non supporting Windows 10X

# Actual behavior

Just crashing

**Comment by zadjii-msft** [comment]
How are you installing on 10X? Are you using the "Universal" version of the Terminal, or the desktop (normal) one?

**Comment by DHowett** [comment]
Sorry, 10X isn't a supported platform for Terminal. Also, I don't believe that users have been licensed to test it out? I may not be fully up-to-date on Microsoft news, however.
