### ISSUE TITLE
search field on click on "v" in the titlebar

### ISSUE THREAD

**Issue by big-burger-1966** [microsoft/terminal#9434]
I have a lot of different terminal settings.
![image](https://user-images.githubusercontent.com/66484098/110672701-35c1b500-81d0-11eb-8c64-220190b5a64e.png)

It would be great to have a search field after opening the "v" in the titlebar:
- klick on "v" or strg-shift-t
- type "xyz" and enter opens the terminal "xyz"

**Comment by zadjii-msft** [comment]
You might be interested in the "Command Palette", on <kbd>Ctrl+Shift+P</kbd>
![](https://docs.microsoft.com/en-us/windows/terminal/images/command-palette-iterable-commands.gif)

which actually _does_ have a searchable list of all your profiles (as well as other things as well).  

#1571 is the issue we're tracking for customizing the contents of the new tab dropdown, though that's not really what you're after here.

**Comment by big-burger-1966** [comment]
It's almost a solution. I have to scroll 10 Lines to the "New Tab" entry in the command palette. 

Maybe it can be easier reached:
strg-alt-t opens the Search Dialog like your sample after selecting "New Tab"

**Comment by zadjii-msft** [comment]
So the command palette also offers fuzzy matching as you type. So you can just type in `n.` and it'll automatically filter straight to "new tab..."

![image](https://user-images.githubusercontent.com/18356694/110676781-f8423500-8199-11eb-99d0-5ad70272c906.png)

Heck, with the way my actions are ordered, I can actually get there with just `.`
![image](https://user-images.githubusercontent.com/18356694/110676878-190a8a80-819a-11eb-8c50-145f16541f4d.png)


but the sort order might be different.
\I think we have another issue somewhere tracking "have a keybinding to open directly to a nested list in the command palette", but I can't remember which off the top of my head.

**Comment by big-burger-1966** [comment]
I'm using the german version of terminal
n. doesn't help:
![image](https://user-images.githubusercontent.com/66484098/110677818-e3839280-81d5-11eb-8550-1930e150a2a3.png)

**Comment by Don-Vito** [comment]
@big-burger-1966 - isn't `Neue Registerkarte..`. is the one you are looking for? If you write `nr.` you can get even closer.

**Comment by zadjii-msft** [comment]
You know, I'm gonna close this. The Command Palette is our definitive "filterable action UI" solution, I don't think we need to slap filters on _everything_.
