### ISSUE TITLE
Trying to access settings pulls up the 'Open with' popup dialog 

### ISSUE THREAD

**Issue by rectified95** [microsoft/terminal#9439]
# Environment

```none
Windows build number: Win32NT             10.0.21322.0 Microsoft Windows NT 10.0.21322.0
Windows Terminal version (if applicable): 1.6.10571.0
Any other software?
```

# Steps to reproduce

1. Press "Ctrl+,' in order to open terminal settings.

# Expected behavior

Can access terminal settings -  would expect to be able to change font size/color there.

# Actual behavior

A popup dialog comes up prompting me to choose the app with which to open some file - 'how do you want to open this file?'

**Comment by zadjii-msft** [comment]
You didn't mention a version for the Terminal, but I'm presuming you're running <1.7.*.

That's exactly by design - the settings for the Terminal are in a json file - when you click on "Settings", it'll try and open the `settings.json` file in whatever your default `.json` editor is. If there isn't one configured, then you'll get that dialog.

**Comment by rectified95** [comment]
I'd say it should default to at least Notepad, and/or inform that settings are stored in a JSON file.

**Comment by zadjii-msft** [comment]
Unfortunately, when we ask the OS to open the "default json editor", I'm not sure there's a way for us to know that it couldn't find an app and let us fall back to notepad gracefully. 

In 1.7 (in preview _now_), the terminal actually defaults to the new Settings UI, so this won't really be an issue in one release ☺️.

**Comment by rectified95** [comment]
Thanks for getting back to me. 
> the terminal actually defaults to the new Settings UI

 do you mean that the 'default apps' page in the Windows Settings app will be opened when the terminal can't find a default JSON editor?

**Comment by DHowett** [comment]
> Thanks for getting back to me.
> 
> > the terminal actually defaults to the new Settings UI
> 
> do you mean that the 'default apps' page in the Windows Settings app will be opened when the terminal can't find a default JSON editor?

Nope! This is what you'll get:

![image](https://user-images.githubusercontent.com/189190/110712178-6ac90a00-81c6-11eb-929c-d84755e9c6b9.png)
