### ISSUE TITLE
Failed to build latest upstream

### ISSUE THREAD

**Issue by Soumil07** [microsoft/terminal#944]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.116]
Windows Terminal version (if applicable): 83b139596fdbf0073655efd086b25172d4e578b1 (Git)

Any other software?
```

# Steps to reproduce
Pull the latest commit, and build with VS2017.

# Expected behavior
It builds correctly.

# Actual behavior
1 error while building:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'LastTabClosed': is not a member of 'winrt::TerminalApp::App'	WindowsTerminal	c:\users\soumil\documents\terminal\src\cascadia\windowsterminal\apphost.cpp	73	
```

**Comment by DHowett-MSFT** [comment]
@soumil07 that's weird, it looks like something is missing from the c++/winrt-generated headers. would you mind trying a full clean build?

**Comment by binarycrusader** [comment]
@Soumil07 Check the full build output for errors.  My experience was that some of the UWP-related projects won't get built with VS2017 if you don't have every single dependency installed you'll get build errors exactly like the one described.

**Comment by vhanla** [comment]
Same happened, but it was due to not rebuilding all Terminal projects before WindowsTerminal, try rebuilding them one by one.

**Comment by Soumil07** [comment]
A fresh rebuild works, so I'll close this - but I'd like to know what caused the build errors on pulling latest and rebuilding. I pulled the repo, nuget restored it and built it. Did I miss a step?

**Comment by sryze** [comment]
Same error, clean & rebuild didn't help:

```
1>------ Build started: Project: WindowsTerminal, Configuration: Debug x64 ------
1>AppHost.cpp
1>f:\sources\windows-terminal\src\cascadia\windowsterminal\apphost.cpp(73): error C2039: 'LastTabClosed': is not a member of 'winrt::TerminalApp::App'
1>f:\sources\windows-terminal\src\cascadia\windowsterminal\x64\debug\generated files\winrt\impl\terminalapp.2.h(167): note: see declaration of 'winrt::TerminalApp::App'
1>Done building project "WindowsTerminal.vcxproj" -- FAILED.
2>------ Build started: Project: CascadiaPackage, Configuration: Debug x64 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(199,5): error MSB4044: The "GenerateDesktopBridgeAppxManifest" task was not given a value for the required parameter "EntryPointExe".
2>Done building project "CascadiaPackage.wapproj" -- FAILED.
```
