### ISSUE TITLE
select to copy and right click to paste

### ISSUE THREAD

**Issue by dev2y** [microsoft/terminal#9442]
Is it possible to copy the selected text automatically? 
and paste the copied text on right click?

if not, can I request this feature for ssh command?

Thank you

**Comment by DHowett** [comment]
[here!](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#automatically-copy-selection-to-clipboard)

**Comment by zadjii-msft** [comment]
Paste on right click is already a part of the Terminal.

Copy on select is also already implemented, see the docs:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#automatically-copy-selection-to-clipboard
