### ISSUE TITLE
Snap Layouts Support: WM_NCHITTEST should return HTMAXBUTTON, HTMINBUTTON, ... for caption buttons

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9443]
Right now, our implementation of WM_NCHITTEST only covers the "caption" portion of the drag bar. To properly support accessibility tools, we'll need to return more than HTCAPTION.

This may require some rearchitecting to make sure the drag bar can pass input to the XAML input site.

**Comment by DHowett** [comment]
This one was filed for a very specific reason. :smile:

**Comment by itsme-alan** [comment]
> This one was filed for a very specific reason. 😄

There has been a lot of teases in this repo

**Comment by zadjii-msft** [comment]
Dead ends in: [`dev/migrie/titlebar-shenannigans`](https://github.com/microsoft/terminal/compare/dev/migrie/titlebar-shenannigans), [`dev/mgirie/b/more-nchhittest-ideas`](https://github.com/microsoft/terminal/compare/dev/mgirie/b/more-nchhittest-ideas)

**Comment by augustresende** [comment]
If anyone is interested, snap layouts does not work in flutter desktop apps if title bar is customized/disabled:

https://github.com/flutter/flutter/issues/156791
