### ISSUE TITLE
wt.exe should start powershell/cmd in CURRENT folder

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/terminal#9445]
# Steps to reproduce

Type `wt.exe` in command prompt, windows commander, or anywhere else

# Expected behavior

Windows Terminal should launch in the CURRENT FOLDER. That is how command line works. Look at `git` - when you type it in - it starts working in the current folder.

# Actual behavior

It always launches in %user% folder

**Comment by zadjii-msft** [comment]
This is by-design - the terminal is obeying your `startingDirectory` setting.  If you launch `wt.exe -d .` it will inherit the CWD of the caller. `wt -d c:\windows\system32` and it'll launch in `c:\windows\system32`. #3547, https://github.com/microsoft/terminal/issues/878#issuecomment-538511693 and https://github.com/microsoft/terminal/issues/878#issuecomment-579508860 have more details. 

/dup #878

**Comment by alex-jitbit** [comment]
@zadjii-msft 

>that is by design

Well, consider this a bad design report then

**Comment by zadjii-msft** [comment]
Thanks for the constructive feedback! As I linked above, there's a lot of complicated factors as to why this can't work the way you want, without breaking some other scenario. If you have some idea on how to fix this scenario holistically, I'd be happy to review a PR ☺️
