### ISSUE TITLE
Bracketed paste works strangely in WSLv1 with ZSH/oh-my-zsh shell

### ISSUE THREAD

**Issue by tleepa** [microsoft/terminal#9447]
# Environment

```none
Platform      : Win32NT
ServicePack   :
Version       : 10.0.19041.0
VersionString : Microsoft Windows NT 10.0.19041.0

Windows Terminal version (if applicable):
Preview 1.7.572.0

WSLv1 running Fedora 33 and Ubuntu 20.04 with zsh/oh-my-zsh shell
PowerShell Core 7.1.2
```

# Steps to reproduce

Type some text and then paste whatever in the terminal.

# Expected behavior

Paste should work as in PowerShell - quickly with no overwriting.

# Actual behavior

Paste starts with overwriting command (though re-positions itself later), slowly adding characters, and leaves pasted text highlighted (until another key is pressed) when completed (left tab is PowerShell, right is Fedora on WSLv1 with oh-my-zsh).

![paste_pwsh-vs-wsl](https://user-images.githubusercontent.com/7734919/110775837-abc12d00-825f-11eb-9eec-5eeda657cf2a.gif)

I have been checking other scenarios:

- PowerShell Windows, PowerShell Core, cmd - ok
- when I run the same WSLv1 but with bash as a shell - ok
- when I run WSL/oh-my-zsh session using Windows Terminal stable 1.6.10571.0 - ok (understandable - no bracketed paste there)
- when I paste text in python/ipython/vim from WSL/oh-my-zsh session - ok
- when I ssh from the WSL/oh-my-zsh session to a remote server running bash - ok
- when I ssh from the WSL/oh-my-zsh session to a remote server running similar zsh/oh-my-zsh combo - ~ok (paste works in a similar way - command will get overwritten first, but paste is very quick and text is not highlighted)
- when I run WSL with ZSH shell but without oh-my-zsh - ~ok (paste is quick, does not overwrite the command, but stays highlighted until another key is pressed)
- when I run WSL with ZSH shell with oh-my-zsh but disabled plugins (zsh-autosuggestions) - ~ok (paste is quick but delayed, does not overwrite the command, stays highlighted until another key is pressed)

From above, it looks that the problem may be related to zsh plugins, but I wonder, whether you could confirm whether this is or not Terminal's fault?

**Comment by skyline75489** [comment]
OK first PowerShell & PowerShell Core do not even have bracketed paste support. You can rule them out first. Second, stock ZSH has support for bracketed paste mode, so you don't need oh-my-zsh or other plugins to use it. If it's working with stock ZSH, then bracketed paste should be working fine. So I think about 80% of the chance this is caused by your zsh configuration, which somehow messes up the bracketed paste handling.

**Comment by tleepa** [comment]
Thank you for prompt reply.

I have found how to solve/work around this particular problem in [one of zsh-autosuggestions issues](https://github.com/zsh-users/zsh-autosuggestions/issues/351#issuecomment-575549779).
