### ISSUE TITLE
Windows Terminal crashes when nested command does not have command field

### ISSUE THREAD

**Issue by waf** [microsoft/terminal#9448]
Crash happens in the latest release of Windows Terminal 1.6 and Preview 1.7.

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable):
  Version: 1.6.10571.0
  Version: 1.7.572.0
```

# Steps to reproduce

1. Add the following command to the `actions` array:
```json
{
    "name": "Cause a crash",
    "commands": [
        { "name": "hello" },
        { "name": "world" }
    ]
}
```
2. Try to run "Cause a crash" from the Command Palette
3. Windows Terminal crashes

From some experimentation, the crash is caused by the missing `"command"` field in the nested commands. While the example JSON above is not real-world, I originally found this when I typo'd the `"command"` field name, which could also happen to other users.

It might be related to #8422, but it's still happening in the latest release of Windows Terminal (both 1.6 and 1.7 preview).

I've submitted a Feedback Hub reproduction with the exact same title as this GitHub issue, but I wasn't signed in, so it appears I didn't get a hyperlink or ID. Let me know if you'd like me to submit another one (signed in this time).

**Comment by zadjii-msft** [comment]
Welp that's a pretty trivial repro. We'll make sure to add it to test cases so that this doesn't regress in the future. Thanks!

**Comment by Don-Vito** [comment]
It doesn't seem related to #8422, as it modified only the CmdPal (fixed an underflow there) and here it is a bug in the ShortcutActionDispatch that doesn't verify the parameters.

I will add protection in ShortcutActionDispatch, but we also need to improve the parsing of the commands.
