### ISSUE TITLE
Allow Profile Icon to reference an executable

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/terminal#9449]
# Description of the new feature/enhancement

I've just added a profile for the "x64 Native Tools Command Prompt for VS2019", using the following:

```
        {
            "guid": "{70903acb-55e7-41c4-9480-70fae317ba9b}",
            "name": "VS Tools",
            "commandline": "%comspec% /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat\""
        },
```

I would like to change the default icon to be the VS icon so I can quickly differentiate between that, and the regular `cmd` profile.

# Proposed technical implementation details

Given a path to an executable, I suggest looking for the first available icon in the resources:

```
"icon": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe"
```

`devenv.exe` contains 5 icons, so an additional option may be useful to allow an index or ID to be specified:

Load icon at index 2:
```
"icon": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe,2"
```

Load icon with ID 1203:
```
"icon": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe,@1203"
```

**Comment by Don-Vito** [comment]
@MarkIngramUK  - please see https://github.com/microsoft/terminal/issues/1504

**Comment by MarkIngramUK** [comment]
Apologies, I did try searching 🤦🏻‍♂️
