### ISSUE TITLE
Can't enter upper case letters in a PowerShell (sometimes)

### ISSUE THREAD

**Issue by akivanov** [microsoft/terminal#9450]
Not sure whether it is a PowerShell issue or a Terminal one.

# Environment
Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0
Windows Terminal
Version: 1.6.10571.0

# Steps to reproduce
Occurs randomly 

# Expected behavior
I could type and paste uppercase letters as much as I want.
# Actual behavior
Sometimes when I'm pasting copied text string that contains uppercase letters or trying to type them manually (using keyboard) they simply refuse to appear. 

Very embarrassing bug that can only disappear after I relaunch the shell.

**Comment by zadjii-msft** [comment]
Okay, so this is bizarre. We've seen this intermittently before, over in #7087 and #8450. From that thread: https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this [PowerShell/PowerShell#10794](https://github.com/PowerShell/PowerShell/issues/10794) and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

@akivanov Could you try that, and see if that resolves the issue?

**Comment by akivanov** [comment]
It turned out that STR from [https://github.com/PowerShell/PowerShell/issues/10794]() were indeed triggering the bug. And after installing a new version of PSReadLine STR doesn't lead to bug anymore. Thank you, @zadjii-msft!

**Comment by ValZapod** [comment]
THANK YOU! It was driving me insane for the last year. There are at least two duplicates of this issue:  #6503 and  #9343. Thanks again!
