### ISSUE TITLE
Getting weird blue screen trying to move in vim editor. 

### ISSUE THREAD

**Issue by AzadKshitij** [microsoft/terminal#9451]
# Environment

```none
Windows build number: Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce

```cmd
vim fileName.c
```
After opening file in vim editor write some code 
```c
int main(){
        return 0;
}
```
Try to go further left from the starting point of line..

# Expected behavior
Nothing should change

# Actual behavior
![6e4b54e31ae9a2f42fd4cccc4bb2d35c6f4f635c](https://user-images.githubusercontent.com/54288405/110832649-76cecd80-8293-11eb-9b72-818ed67888e2.gif)

**Comment by DHowett** [comment]
This is a "visual bell" -- vim is telling us to invert the screen colors for a split second to tell you that you did something it didn't like.

**Comment by DHowett** [comment]
[Here's some info on disabling belling, both audible and visual](https://unix.stackexchange.com/questions/5310/how-can-i-disable-bells-visualbells-in-vim)

**Comment by AzadKshitij** [comment]
But I'm not getting that same thing in command prompt!! What's the reason??

**Comment by zadjii-msft** [comment]
> But I'm not getting that same thing in command prompt!! What's the reason??

That's because conhost (the vintage console application) _doesn't support visual bells_.

**Comment by DHowett** [comment]
> doesn't support visual bells

YET. The next version of Windows will almost certainly have support for visual bells in conhost.
