### ISSUE TITLE
[REGRESSION] Multi-click selection broken in main

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9453]
IN RETROSPECT: I don't think this is right. We might have lost the case where there's no selection, and you double/triple click on a word

@Don-Vito as an fyi

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/pull/9403#r592604796_

**Comment by DHowett** [comment]
I may stage a revert for this until we can get it in and get it right.

I'd like to see manual test runs for the following scenarios:

* [ ] single click = no selection
* [ ] single click and drag = selection starting from first point
* [ ] single click in unfocused pane and drag = focus pane, selection starting from first point
* [ ] double-click = selects a whole word
* [ ] triple-click = selects a whole line
* [ ] double-click and drag = selects a whole word, drag selects whole words
* [ ] triple-click and drag = selects a whole line, drag selects whole lines
* [ ] <kbd>Shift</kbd> single-click = defines start point
* [ ] second <kbd>Shift</kbd> single-click = defines end point
* [ ] <kbd>Shift</kbd> double-click = selects entire word
* [ ] <kbd>Shift</kbd> triple-click = selects entire line
* [ ] <kbd>Shift</kbd> double-click and drag = selects entire word, drag selects whole words
* [ ] <kbd>Shift</kbd> triple-click and drag = selects entire line, drag selects whole lines

**Comment by Don-Vito** [comment]
@DHowett, @zadjii-msft - can you explain what is broken? I am quite sure I tested this case.

**Comment by DHowett** [comment]
So, when I double-click select something on `main`, I get ... no selection :(

**Comment by Don-Vito** [comment]
> 
> 
> So, when I double-click select something on `main`, I get ... no selection :(

OK. I see. I will fix it today. and also run all the tests you mentioned.

The previous version is not working with shift+double-click, so it is equally broken.

**Comment by DHowett** [comment]
Thanks :smile:

**Comment by Don-Vito** [comment]
I mean it should be a one-liner. I simply forgot that shift is not required for multi-selection :)

**Comment by Don-Vito** [comment]
Sorry for missing the scenario without shift 👼 
Wondering if there is a good way to add UT for this one

**Comment by zadjii-msft** [comment]
Yea the unittesting scenario for the TerminalControl binary is awful. Fixing that is what I'm actually working on today, because we've _got to do something about it_.
