### ISSUE TITLE
Environment not inherited by new instances/tabs of windows terminal

### ISSUE THREAD

**Issue by HudsonMC16** [microsoft/terminal#9456]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
```
```
Windows Terminal Preview
Version: 1.7.572.0
```
# Steps to reproduce
Not sure this is *exactly* the right way to describe this issue and I'm not exactly sure how to test it explicitly, so I will describe the a short, (hopefully) reproducible situation in which I encountered this inconsistency between 1.6 and 1.7-preview.

1) activate a python virtual environment
2) run `wt -d .`
3) in newly-opened terminal instance, run `python`
4) at python repl, run `import sys` then `sys.executable`
# Expected behavior
In 1.6 (non-preview), the new terminal instance would inherit the python environment from the calling terminal, so the above steps would print the path to the python interpreter inside the venv.

I used this behavior often in batch scripts to launch applications (mostly vim). The batch script (usually launched from the address bar in an explorer window) would check for a venv, if it existed, it would activate it then launch the application from inside the venv. 
# Actual behavior
In 1.7 (preview), the new terminal instance did not inherit the python environment and the above steps printed the path to the system python interpreter.

**Comment by HudsonMC16** [comment]
@DHowett I'm sorry, I actually saw that issue when searching, but didn't read closely or far down enough to see the connection to what I'm experiencing. Mea culpa. 

So, maybe you could clear something up for me, though? Maybe I'm dense, but reading through that and related issues, it's still not clear for me what the intended behavior is, for current or future versions of wt. My current solution is kind of hacky, so I'd like to know if I can expect the old behavior to return or if I need to refine my current workflow. Sorry, I know you don't really owe me answer, but hoping you could point me in the right direction.

**Comment by DHowett** [comment]
The correct behavior going forward _should_ be to produce a new environment block from the system and then merge in other environment variables that were set when WT was spawned. That's not something we have today.

Ideally, we would do this:

```
Env at WT Spawn       Original system Env         New system env         Final env as seen by client app
---------------       -------------------         --------------         -------------------------------
ProgramFiles          ProgramFiles                ProgramFiles           ProgramFiles
PATH                  PATH                        PATH (edited)          PATH (edited)
LocalEnv1                                                                LocalEnv1
                                                  NewSystemEnv1          NewSystemEnv1
```

> Sorry, I know you don't really owe me answer, but hoping you could point me in the right direction.

You're a community member! I may not owe you one, but you do _deserve_ one.

**Comment by HudsonMC16** [comment]
Great, thanks for the clarification. And thanks for giving me the answer, then!
