### ISSUE TITLE
[DefApp] Pass LNK/EXE data from OpenCon to ITerminalHandoff

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#9458]
brain notes from chat

> if we get the lnk filename or the exe path from ITerminalHandoff, we can cobble together a fake profile (based on the console settings in the lnk or registry) that "looks-like-" what conhost would have looked like for that lnk or exe

_Originally posted by @DHowett in https://github.com/microsoft/terminal/issues/7489#issuecomment-796993690_

**Comment by zadjii-msft** [comment]
Ahg I hate to be a pain, but I don't think we technically did this one. I think a big part of this one is the "if we're launched from a .lnk, we need to crack that lnk open and create a dummy profile for those settings". Or at least we need to experiment with trying that. It's a very 98052 issue, but one I bet we're gonna hear a few more times this year. 

also related: #1793

**Comment by miniksa** [comment]
What happened was that I believe I added the information to do this to the interface so it **could** be implemented, but then never actually used that information to implement anything.
