### ISSUE TITLE
Document the use of Add-AppxPackage

### ISSUE THREAD

**Issue by glawrence** [microsoft/terminal#9467]
Reading README.md I could not find how to install Windows Terminal from the command line when the Microsoft Store is not available, however I did find https://github.com/microsoft/terminal/pull/6942 which worked perfectly but looks like it was never merged. I want to raise a PR to update README.md because in Windows Sandbox the Microsoft Store is not available, and this PowerShell solution is the quickest and easiest way to get Windows Terminal installed in the sandbox, as you can't just double-click the .msixbundle file.

I am creating this issue before raising a PR, as I believe this to be the correct process.

**Comment by WSLUser** [comment]
The old PR went stale as the author never addressed the concern brought up there.  If you want to simply recreate the PR with the correction found [here](https://github.com/microsoft/terminal/pull/6942/files#r465791906), that would be accepted.

**Comment by glawrence** [comment]
I noticed that and was planning to take those comments on board and any future comments to see this to completion

**Comment by glawrence** [comment]
I think I have done everything necessary and got suitable wording etc, but very happy to take any feedback
