### ISSUE TITLE
'wt' in explorer address bar.

### ISSUE THREAD

**Issue by XeonG** [microsoft/terminal#9469]
if 'wt' is used in the explorer window.. why doesn't it work like 'cmd' where it will open the terminal at that location?

obviously this is even more useful in 'wt' if using ubuntu.. as the path names for windows are completely different and in a mount drive section.., so why isn't it the default behavior!?

**Comment by zadjii-msft** [comment]
This question's been answered a huge number of times before. Please [search before filing new issues. ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22explorer+address+bar%22)

/dup #878
