### ISSUE TITLE
Unable to open Windows Terminal Preview after installing PowerShell 7.1.3

### ISSUE THREAD

**Issue by tstephansen** [microsoft/terminal#9473]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.7.572.0

Any other software?
Microsoft Store
```

# Steps to reproduce

Install powershell 7.1.3.
This causes Windows Terminal Preview to not open.
Repair Windows Terminal Preview in settings.
Reset Windows Terminal Preview in settings.
Uninstall Windows Terminal Preview.
Reinstall Windows Terminal Preview from the Microsoft Store.

# Expected behavior

Windows Terminal Preview should open after installing Powershell 7.1.3.

# Actual behavior

Windows Terminal Preview does not open.

EDIT:
I am unable to share feedback for it through the feedback hub. However, I've included the information below from the Diagnostic Data Viewer.

WindowsTerminal.exe

Description
Faulting Application Path:	 C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.7.572.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Creation Time:			 3/12/2021 2:03:03 PM
Problem:			 Stopped working
Status:				 Report sent

Problem signature
Problem Event Name:           MoAppCrash
Package Full Name:            Microsoft.WindowsTerminalPreview_1.7.572.0_x64__8wekyb3d8bbwe
Application Name:             praid:App
Application Version:          1.7.2102.26002
Application Timestamp:        60394d91
Fault Module Name:            Microsoft.Terminal.Settings.Model.dll
Fault Module Version:         1.7.2102.26002
Fault Module Timestamp:       60394b83
Exception Code:               c0000005
Exception Offset:             00000000000713c1

Extra information about the problem
Bucket ID:			 b30ad9210bb5f0c21b3f7f2d191cb448 (1963427794228393032)

**Comment by tstephansen** [comment]
I tried to debug this myself on my computer and I'm getting the following exception thrown in the Windows.Storage.h file. I'm not an expert at debugging C++ by any means but hopefully this information helps.

Exception thrown at 0x00007FFFAE9A49A7 (Microsoft.Terminal.Settings.Model.dll) in WindowsTerminal.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

It is being called from CascadiaSettingsSerialization.cpp line 493.

auto path = winrt::to_string(foundFolder.Path());

**Comment by DHowett** [comment]
Whoa. _Whoa_. @PankajBhojwani this is in fragment parsing!

**Comment by DHowett** [comment]
@tstephansen There's a feature that we added in v1.7 that allows a WSL distribution (or other application package) to add a profile to Terminal, or to add a specific configuration to Terminal.

Somebody may need to report to them that their fragment is actually breaking Terminal. We should also not _crash_ when this happens.

**Comment by DHowett** [comment]
Then again: we have this wrapped in an exception handler. _Huh._

**Comment by tstephansen** [comment]
Any ideas on why this started happening after installing Powershell 7.1.3? Everything seemed to be working fine until I ran the install. After that I was unable to open terminal. It could be coincidence or either Terminal or Raft could have updated been today. I don't know how to see the version history or update dates for applications in the Microsoft Store so I'm not really sure.

**Comment by DHowett** [comment]
If you recently got updated from 1.6 to 1.7, that could've caused this. If you go to the "Downloads & Updates" page in the Store (`...` menu), it'll show you when each application was last updated. Hopefully.

**Comment by crramirez** [comment]
Hello,

I am sorry for that. A new version of Raft WSL is on the way. I will notify you here when it is life. I couldn't find any workaround.

Regards,
Carlos

**Comment by DHowett** [comment]
@crramirez You're our first public user of fragments, by the way! Would you/one of yours mind e-mailing me and my PM (duhowett@microsoft, cinnamon@microsoft) to chat about them? Thanks.

**Comment by crramirez** [comment]
@DHowett sure thanks a lot.

**Comment by crramirez** [comment]
Raft WSL version 21.3.1 is live with the regression in Windows Terminal 1.7 fixed

**Comment by rbeesley** [comment]
Good catch resolving this. I had this problem for a little while now with the Preview and not on the Production release, so I started diving into Event Viewer to gather details. I was getting the same fault bucket and after updating Raft WSL it resolved the crash.
