### ISSUE TITLE
[defapp] Reconcile with process model/monarch-peasant glomming

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#9475]
How does this work with process model/monarch-peasant glomming

_Originally posted by @DHowett in https://github.com/microsoft/terminal/issues/7489#issuecomment-797766144_ 

My reply was to probably make the monarch register itself to receive inbound connections like the `-Embedding` flag will do when COM cannot find a server and then follow the existing glom rules.

**Comment by leonMSFT** [comment]
resolved by #10823
