### ISSUE TITLE
Run Store-app pwsh As Administrator, but administrator is a different user

### ISSUE THREAD

**Issue by NebulousPsychology** [microsoft/terminal#9480]
# Environment

```none
Windows build number: Win32NT  10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.7.572.0

Any other software?
pwsh (Microsoft.PowerShell_8wekyb3d8bbwe) 7.1.3, via the Store
powershell.exe 5.1.19041.610 present by default
```

# Steps to reproduce

- In an environment with a local admin user and a non-admin user, both user accounts having installed Terminal Preview and Pwsh from the Store.  (installed in no particular order, could that matter?)
  > aside: it was some time before realizing both user accounts would need a copy of each app
- logged in *as the non-admin user*, from the taskbar or Start, select Run As Administrator on Terminal Preview
- UAC launches, log in as the Admin user account without complaint

# Expected behavior

A pwsh tab, as admin, in admin's $Home directory.  

# Actual behavior
A pwsh tab appears:
```text
[error 0x80070780 when launching `C:\<admin's $home>\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe']
```

# Additionally
- If a Powershell Desktop tab is opened in the same window, it correctly opens to the admin user's $Home directory (Terminal is correctly elevated, so it's pwsh specifically that isn't being normal)
- If pwsh is Run As Administrator'd directly from Start, it opens an elevated `C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.3.0_x64__8wekyb3d8bbwe\pwsh.exe` 
  -  note differing file path though: yet both exist
  - Terminal has perhaps mapped pwsh from a path that is somehow wrong, but ONLY when run as administrator?

**Comment by KalleOlaviNiemitalo** [comment]
This seems related to <https://github.com/microsoft/terminal/issues/4217>, which has unfortunately been locked.

**Comment by zadjii-msft** [comment]
Good news, this is going to be fixed in an upcoming Insiders build. I don't know the version number off hand. 

/dup #4217
