### ISSUE TITLE
Pixel shaders no longer work in v1.7.572.0 preview

### ISSUE THREAD

**Issue by cyanite** [microsoft/terminal#9483]
# Environment

```none
Windows build number: Windows 10 1909 (10.0.18363.1379)
Windows Terminal version (if applicable): v1.7.572.0

Any other software?
```

# Steps to reproduce

Configure a pixel shader.

# Expected behavior

It works.

# Actual behavior

It doesn't work. Nothing happens. The same pixel shader works as it's supposed to on v1.6.10571.0. No pixel shaders work on v1.7.572.0.

**Comment by Nacimota** [comment]
This is a dup of #9354, which has since been fixed. Basically, the path to the shader file was not being loaded/set correctly. To get it to work you can use an earlier preview build, build the terminal yourself from main, wait for the next preview release, or run the 1.6 stable build.

**Comment by cyanite** [comment]
Gotcha, thanks 👍
