### ISSUE TITLE
There are two apps in the Windows Store, Windows Terminal and Windows Terminal Preview. Are they both going to continue to be recieving updates?

### ISSUE THREAD

**Issue by pbakes** [microsoft/terminal#9484]

**Comment by DHowett** [comment]
Yes, they are both receiving updates.

**Comment by DHowett** [comment]
There is actually a bug preventing both of them from showing up in the context menu at the same time, so it is surprising that for you they would (1) both show up and (2) stick around after being uninstalled :)

**Comment by pbakes** [comment]
@DHowett gotcha. So now after uninstalling 1.6 (and spending yesterday afternoon performing a reformat) I've got a different probem. Right-click shows the correct menu item 
![Screenshot 2021-03-14 084504](https://user-images.githubusercontent.com/38716120/111074854-5163de80-84a2-11eb-84cd-eb2ee247a49b.jpg)

but now Shift+RMB is missing the Open Command Prompt window here. It's only showing the first two items.
![Screenshot 2021-03-14 084716](https://user-images.githubusercontent.com/38716120/111074883-76585180-84a2-11eb-95c9-8b638256dd6c.jpg)

Looks like the issue is close to #1060.

**Comment by zadjii-msft** [comment]
> but now Shift+RMB is missing the Open Command Prompt window here. It's only showing the first two items.

The terminal isn't actually creating that "Open PowerShell window here" entry. That's actually provided by the OS. The Terminal doesn't list all of your profiles in the context menu (yet!) - that work is being tracked over in #6111.

There are a bunch of other open bugs, so make sure to check out: https://github.com/microsoft/terminal/labels/Area-ShellExtension
