### ISSUE TITLE
settingsUI is unreadable in setting.json

### ISSUE THREAD

**Issue by ekrecker** [microsoft/terminal#9488]
# Environment

My terminal could not read `settingsUI` in `setting.json`.
Of course, I've checked `,` and syntax errors.
Has anyone encountered the error ?
My stupid mistakes ?
```
 Line 132, Column 60 (target)
  Have: "settingsUI"
  Expected: settingsFile | defaultsFile | allFiles
```

```
Windows Terminal
Version 1.6.10571.0
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by Nacimota** [comment]
I don't think the Settings UI is enabled in the stable build you're using. If that's so, it makes sense that the `settingsUI` wouldn't be a valid target in your JSON.

**Comment by skyline75489** [comment]
The settings UI is deliberately hidden in 1.6 (See #9225) . You'll need 1.7 preview or wait for 1.7 stable.

**Comment by DHowett** [comment]
Yup.

**Comment by ekrecker** [comment]
Thank you for advices.
