### ISSUE TITLE
URL Click Browser Setting

### ISSUE THREAD

**Issue by EnigmaPatrick** [microsoft/terminal#9491]
# Description of the new feature/enhancement

A profile setting to define which browser you wish for the clickable url to automatically be opened in, bypassing windows default browser. (i.e. chrome being windows default but forcing clicked link to open in firefox)

Allows the usage of multiple browsers for different use cases. i.e. separate browsers for work & personal usage. 

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I suppose it's not the worst idea. I wonder if we're able to enumerate all the apps that say they're "browsers".

**Comment by DHowett** [comment]
I'd rather not get us into the business of launching specific applications for _URLs specifically_. Once we add configurable pattern detection and matching (which is on the backlog somewhere), we'll also add pattern _execution_. That'll let folks customize which browser launches for which patterns.

/dup #8849
