### ISSUE TITLE
Broken mouse in Neovim

### ISSUE THREAD

**Issue by Sebastian-byte** [microsoft/terminal#9499]
# Environment

```none
Windows build number: 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? Neovim: 0.4.4
```

# Steps to reproduce

1. Download Neovim (https://neovim.io)
2. Open it on Windows Powershell or the Command Line (in WSL works perfectly)
3. Try to select something with the mouse.

# Expected behavior

Working mouse (Visual mode)
![image](https://user-images.githubusercontent.com/62727185/111094604-9ff89380-8509-11eb-85c0-dafdf465b550.png)

# Actual behavior

Broken mouse (it's actually selecting)
![image](https://user-images.githubusercontent.com/62727185/111094262-ed283580-8508-11eb-9340-a2a1ced94892.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #376  for more discussion.

/dup #376
