### ISSUE TITLE
Terminal selects lines when scrolling down the scroll bar and crashes when right clicked afterwards

### ISSUE THREAD

**Issue by Kapperchino** [microsoft/terminal#950]
Windows terminal exits with code -1073741189 (0xc000027b). When clicking on a spot in the terminal, dragging down the scroll bar, then right clicking.

# Environment

```none
Windows build number: [Version 10.0.18898.1000]  
Using powershell
```

# Steps to reproduce

- Populate the terminal with ls until scroll bar is around 1/3 height of the terminal
- Scroll up top the top
- Left click within the terminal
![Capture1](https://user-images.githubusercontent.com/30029892/58218447-e2b5ff80-7cd4-11e9-9d80-fcb6ccae2c2b.PNG)

- Drag the scroll bar down
![Capture2](https://user-images.githubusercontent.com/30029892/58218452-eba6d100-7cd4-11e9-9472-2162c0898c2e.PNG)

- Right click within the terminal

# Expected behavior

Expected the terminal to do nothing.

# Actual behavior
Exited with code -1073741189.

**Comment by mscodebum** [comment]
Confirmed. It may be due to the amount of data being send to clip.

**Comment by zadjii-msft** [comment]
AH.

Yea that looks bad. Looks like the Control needs to eat any mouse events that the scrollbar is handling. Kinda shocked that the scrollbar doesn't handle this by default.

@carlos-zamora has been doing most our mouse things, so I'll ping him here to get his eyes on it, but I'll also mark it help-wanted, if someone in the community wants to try and snipe this one from him :)
