### ISSUE TITLE
Can't reorder tabs when I launch as admin

### ISSUE THREAD

**Issue by armaansood** [microsoft/terminal#9500]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.867]
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

Hold down Shift + CTRL and click on the Windows Terminal icon. Open a second tab. Try dragging around the tabs.
# Expected behavior

I expect to be able to drag around and reorder the tabs.

# Actual behavior

I can't reorder the tabs.

**Comment by skyline75489** [comment]
This is actually by design. See #3581, #6893

**Comment by zadjii-msft** [comment]
Yep, thanks!

/dup #3581
/dup #6893
