### ISSUE TITLE
Git bash profile results in error

### ISSUE THREAD

**Issue by aarav2you** [microsoft/terminal#9501]
# Environment

```
Microsoft Windows [Version 10.0.18363.1379]
```

# Steps to reproduce
       Make a new profile for gitbash:
            {
                // Git Bash
                "guid": "{idhere}",
                "name" : "Git Bash",
                "commandline" : "‪D:\\Program Files\\Git\\usr\\bin\\bash.exe",
                "hidden": false,
                "icon" : "D:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "backgroundImage": "F:\\ThisPC\\Pictures\\Downloaded\\spaceman.png",
                "backgroundImageOpacity": 0.3,            
                "startingDirectory": "F:\\ThisPC\\Desktop"
            },

# Expected behaviour
It would execute gitbash
![image](https://user-images.githubusercontent.com/37036762/111117859-1939ca00-858e-11eb-9d9f-6a5195b0ce11.png)

# Actual behavior
Provies error `[error 0x80070002 when launching `‪D:\Program Files\Git\usr\bin\bash.exe']`
![image](https://user-images.githubusercontent.com/37036762/111117950-32427b00-858e-11eb-8c7a-04c5477fe6c2.png)

**Comment by skyline75489** [comment]
Please make sure the path you're using is correct. Looks like you're using an incorrect path.

**Comment by zadjii-msft** [comment]
Yea, I agree with skyline75489 here. it looks like the error message has a space at the start of it

```
[error 0x80070002 when launching ` ‪D:\Program Files\Git\usr\bin\bash.exe']`
                                  ^
                                  right here 
```

are you absolutely sure the `commandline` is correct?

**Comment by DHowett** [comment]
Be aware that this might be a "zero-width" space, which may not be visible in your JSON file!

**Comment by aarav2you** [comment]
> Yea, I agree with skyline75489 here. it looks like the error message has a space at the start of it
> 
> ```
> [error 0x80070002 when launching ` ‪D:\Program Files\Git\usr\bin\bash.exe']`
>                                   ^
>                                   right here 
> ```
> 
> are you absolutely sure the `commandline` is correct?



> Be aware that this might be a "zero-width" space, which may not be visible in your JSON file!

Thanks a lot! there was an invisible whitespace, which wasn't visible like @DHowett mentioned. However, not really a hindering bug whenever I open git bash in windows terminal it says `bash: cut: command not found`
![image](https://user-images.githubusercontent.com/37036762/111190422-14e8cd80-85dd-11eb-8304-ed26cf6ca899.png)

**Comment by DHowett** [comment]
To get a git bash profile properly set up, you're going to want to pass the `-l` and `-i` arguments to bash. `bash.exe -l -i` will make sure that you receive a full, clean _login environment_.

**Comment by aarav2you** [comment]
> To get a git bash profile properly set up, you're going to want to pass the `-l` and `-i` arguments to bash. `bash.exe -l -i` will make sure that you receive a full, clean _login environment_.

Thanks so much!
