### ISSUE TITLE
Severe slowdown in interface after extended ssh session

### ISSUE THREAD

**Issue by BryceEakin** [microsoft/terminal#9504]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19041.867]
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?  OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

# Steps to reproduce

Using the windows command line, create a ssh session with a remote ubuntu server including port forwarding (-L option), and monitor a long-running process with large quantities of printing to the terminal over ~3 days (from a process displaying through a remote `screen` if that's relevant).

Windows Feedback link for diagnostic data: https://aka.ms/AAbj0dj

# Expected behavior

Windows Terminal continues to respond normally.

# Actual behavior

All inputs to Terminal (mouse, keyboard, touch) across the core interface as well as all active terminal tabs slow down dramatically.  Keypresses take from 0.5-1 second to respond (per key press), mouse input takes 2+ seconds for each input including hover, click, etc.  

# Attempted remediation

Terminating the ssh session does not improve interface performance.

Terminating the tab (and all other previously active tabs) does not improve interface performance.

Completely closing and reopening Terminal (and thus destroying the active sessions) does restore performance.

**Comment by DHowett** [comment]
This does not seem to be different from /dup #7710. Thanks for the report!
