### ISSUE TITLE
Click on Settings opens Visual Studio 2019

### ISSUE THREAD

**Issue by gfries** [microsoft/terminal#9511]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.867] Deutsch
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

Click on Settings ("Einstellungen") or Ctrl+,

# Expected behavior

Settings should open

# Actual behavior

Visual Studio 2019 opens

**Comment by DHowett** [comment]
Version 1.6 only supports editing the settings as a text file (JSON file, really). Your JSON file editor is set to be Visual Studio 2019. You can use the preview version (1.7, from https://aka.ms/terminal-preview) or set a different JSON editor to get around this. :smile:
