### ISSUE TITLE
Can we have command set like tmux ?

### ISSUE THREAD

**Issue by eromoe** [microsoft/terminal#9513]
For example, I'd like run and monitor some scripts at system startup.

In wsl2 tmux , would like

```
tmux new-session -d -s $session -n vim #"vim -S ~/.vim/sessions/kittybusiness"

# first split to 3 vertical rows
tmux splitw -v -p 66
tmux splitw -v -p 50

# Select pane 1 , split to 3 horizontal columns
tmux selectp -t 1
tmux splitw -h -p 66
tmux splitw -h -p 50

tmux selectp -t 1
tmux send-keys "python $ZVT_EXAMPLE/joinquant_fund_recorder.py" C-m 

tmux selectp -t 2
tmux send-keys "python $ZVT_EXAMPLE/joinquant_kdata_runner.py" C-m 

tmux selectp -t 3
tmux send-keys "python $ZVT_EXAMPLE/joinquant_other_data_runner.py" C-m 

# Select pane 4
tmux selectp -t 4
....

# Select pane 6
tmux selectp -t 6
.....


```

But tmux only work under linux , if windows terminal support tmux-compatibled command set would be much nicer to ship such feature to all shells , e.g. run multiple cmd、powershell scripts/commands in specific panes/windows at same time..

**Comment by skyline75489** [comment]
I don’t hate the idea. It might be possible to implement this using some kind of CLI tool that talks to the terminal (wrapping wt.exe?)

**Comment by zadjii-msft** [comment]
Wait but what part of the current [commandline arguments to wt.exe](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows) don't satisfy what you're looking for? I know they're not _exactly_ the same thing as the `tmux` commands, but they're pretty similar:
