### ISSUE TITLE
Windows Terminal can not display Chinese text correctly with `ls -alh` git-bash command

### ISSUE THREAD

**Issue by Holinc19** [microsoft/terminal#9514]
Windows OS : 1909 (18363.1440)
PowerShell Version : 7.1.3
Windows Terminal Version : 1.0.1811.0
![image](https://user-images.githubusercontent.com/28728567/111251440-3633d300-864a-11eb-9e32-4de634d15b9e.png)

**Comment by DHowett** [comment]
What is the output of `locale`

**Comment by Holinc19** [comment]
> What is the output of `locale`

PS C:\Windows\System32> locale
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

**Comment by DHowett** [comment]
`PS C:\Windows\System32>` this is not "git bash"

**Comment by Holinc19** [comment]
> `PS C:\Windows\System32>` this is not "git bash"

Holinc@DESKTOP-VQU2DOI MINGW64 ~
$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8

**Comment by DHowett** [comment]
I see. You are not in the proper git bash environment. `ls` is not intended to run outside of `git bash`.

When run outside of `git bash`, ls is not properly configured to display Chinese text.

You must run it inside `git bash`, or set the environment properly (set the environment variable LANG=zh_CN.UTF-8) :smile:

**Comment by Holinc19** [comment]
> I see. You are not in the proper git bash environment. `ls` is not intended to run outside of `git bash`.
> 
> When run outside of `git bash`, ls is not properly configured to display Chinese text.
> 
> You must run it inside `git bash`, or set the environment properly (set the environment variable LANG=zh_CN.UTF-8) 😄

ok. It works while I set $env:LANG='zh_CN.UTF-8'
