### ISSUE TITLE
Doesn't start on server 2022 preview

### ISSUE THREAD

**Issue by matsmcp** [microsoft/terminal#9515]
# Environment

Windows build number: 10.0.20303.1
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
no

# Steps to reproduce
Download. 
Install with add-appxpackage -path "path to your download"
Click on windows terminal in start menu. 
A white line is shown for a short period under the Windows terminal line. 
The terminal never starts

# Expected behavior
Running windows terminal

# Actual behavior
Nothing

This is on a machine without internet access. That is the norm for our servers

**Comment by skyline75489** [comment]
Well, theoretically Server 2022 should have everything in 1903 (18362), I think @DHowett might be interested in this.

**Comment by matsmcp** [comment]
I did some more digging. 
It works on a 2022 with Internet access so it seems to be an airgap issue

**Comment by WSLUser** [comment]
You're hitting https://github.com/microsoft/terminal/issues/6010. See this comment: https://github.com/microsoft/terminal/issues/6010#issuecomment-792800655. As stated in the issue a few times, the only possible workaround would be the pre-installation kit.

**Comment by DHowett** [comment]
/dup #6010

This is just the appLicensing issue.

**Comment by matsmcp** [comment]
Extracting the files did work. 
Now looking at building a MSI for it

**Comment by DHowett** [comment]
If you're trying for offline deployment, why can you not just use the "Preinstall Kit" shipped with Windows Terminal Stable? It contains an offline licensing package and everything you need to ship terminal offline... _without_ resorting to our unsupported unpackaged activation path.
