### ISSUE TITLE
Launching Windows Terminal with a file path that has a trailing backslash (in quotes) breaks the launch

### ISSUE THREAD

**Issue by routerino** [microsoft/terminal#9518]
# Environment
```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): Believe this has happened on previous versions, but 1.7.572.0

Any other software?
Fresh install of Windows
```

# Steps to reproduce
run `wt -d "%userprofile%\"` (edited, missed the -d parameter before)

# Expected behavior
windows terminal handles trailing backslashes and still launches in the correct folder

# Actual behavior
error 0x8007010b. Note that this does not happen if you leave out the quotes (but that will also break on folders with spaces)

![Nkr4pXAc6T](https://user-images.githubusercontent.com/45954722/111419453-99526200-873d-11eb-893f-49b0649ec626.gif)

**Comment by skyline75489** [comment]
This isn't really about the backslash. You should use:

```text
wt -d %userprofile%
```

**Comment by routerino** [comment]
yep, dumb error on my end when retesting. Closing in shame :(.

**Comment by routerino** [comment]
Well that was a dumb error, but there's actually still a problem. Trying with `wt -d "%userprofile%\"` still breaks. However, `wt -d %userprofile\` does not. Reopening!

![Nkr4pXAc6T](https://user-images.githubusercontent.com/45954722/111419453-99526200-873d-11eb-893f-49b0649ec626.gif)

**Comment by routerino** [comment]
Well that was a dumb error, but there's actually still a problem. Trying with `wt -d "%userprofile%\"` still breaks. However, `wt -d %userprofile\` does not. Reopening!

![Nkr4pXAc6T](https://user-images.githubusercontent.com/45954722/111419453-99526200-873d-11eb-893f-49b0649ec626.gif)

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps this is caused by the "special interpretation of backslash characters when they are followed by a quotation mark character" in [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw). Try doubling the backslash.

**Comment by routerino** [comment]
> Perhaps this is caused by the "special interpretation of backslash characters when they are followed by a quotation mark character" in [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw). Try doubling the backslash.

That does appear to resolve the issue, but I don't think that's intended behavior. It does identify the problem though.

**Comment by zadjii-msft** [comment]
That's exactly what the cause is:

https://github.com/microsoft/terminal/blob/c6a31710d915f2f1b470bd01cde74602e048f533/src/cascadia/TerminalApp/AppCommandlineArgs.cpp#L821

You might have better luck with `wt -d "%userprofile%"\` instead - IIRC, `CommandLineToArgv` will still treat that as a single argument, and append the trailing slash.

**Comment by routerino** [comment]
> That's exactly what the cause is:
> 
> https://github.com/microsoft/terminal/blob/c6a31710d915f2f1b470bd01cde74602e048f533/src/cascadia/TerminalApp/AppCommandlineArgs.cpp#L821
> 
> You might have better luck with `wt -d "%userprofile%"\` instead - IIRC, `CommandLineToArgv` will still treat that as a single argument, and append the trailing slash.

I'm not sure I'd consider that a solution. Most people are going to be adding a trailing slash on purpose, not because they intentionally included it. These people will get confused by the error. I know it took me about 30 mins to track down why (a keyboard shortcut in multicommander to launch windows terminal in the open directory automatically adds a trailing slash).

Not going to reopen this myself, but I wouldn't consider that a satisfactory answer.

**Comment by DHowett** [comment]
We briefly considered rewriting the argument parser, but we realized that doing so would bring us out of line with every other Windows application. Unfortunately, we're just not willing to do that. Sorry!

If there comes a day when we can do that without feeling like it breaks with established precedent, I'd be happy to do so :smile:

**Comment by DHowett** [comment]
> We briefly considered rewriting the argument parser, but we realized that doing so would bring us out of line with every other Windows application. Unfortunately, we're just not willing to do that. Sorry!
> 
> If there comes a day when we can do that without feeling like it breaks with established precedent, I'd be happy to do so 😄

**Comment by mikejhill** [comment]
For anyone else who comes across this, this can become an issue when resolving root drive paths programmatically. Certain Windows access patterns resolve root drives with trailing backslashes, but not directories. For example:
```cmd
> cd C:\
> echo %CD% 
C:\

> cd C:\Users\
> echo %CD%
C:\Users
```

This same challenge shows up when writing Windows Explorer context menu entries. E.g., the command `wt.exe -p "Cygwin" -d "%V"` succeeds in `C:\Users` but errors in `C:\` with the same `Could not access starting directory "C:\""` message mentioned above.

A straightforward workaround is to suffix paths with `.`. This is the pattern Git Bash uses as well. Example: `wt.exe -p "Cygwin" -d "%V."`

As far as I can tell, directory paths for `wt.exe -d "..."` can be consistently suffixed in this way to address this. Windows will resolve `C:\Users` and `C:\Users\.` identically.
