### ISSUE TITLE
Launching wt.exe with administrator rights fails

### ISSUE THREAD

**Issue by ValeJappo** [microsoft/terminal#9519]
Unable to launch `wt.exe` with administrator rights. `WindowsTerminal.exe` works instead.

# Environment

```none
Windows build number: version 1909 build SO 18363.1440
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce
*Open Windows Terminal's folder `C:\Program 
Files\WindowsApps\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe` and try launching `wt.exe` with administrator rights
*This can also be done by searching `wt` in Cortana

# Expected behavior
Launch terminal with administration rights

# Actual behavior
Throws the error `Windows cannot access the specified device, path, or file`

**Comment by zadjii-msft** [comment]
You shouldn't be touching that version of `wt.exe`. That's the place the store laid the files down on disk and has all sorts of special permissions. Does launching `%userprofile%\AppData\Local\Microsoft\WindowsApps\wt.exe` as admin work?

**Comment by ValeJappo** [comment]
> Does launching `%userprofile%\AppData\Local\Microsoft\WindowsApps\wt.exe` as admin work?

@zadjii-msft No, it throws the same error.

**Comment by ValeJappo** [comment]
I have just updated Windows: not sure if it is related to this, but now it seems working.
