### ISSUE TITLE
Character out of place

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9522]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.19042.867 (2009, 20H2)
WindowsTerminal: 1.7.572.0
WSL2
TCSH (Astron 6.20.024 November 2016)

# Steps to reproduce

In a 43 character wide WT (6 pixels padding), Consolas font, TCSH in WSL2, echo "<46 asterisks>".   Look at the second-last character echoed; it's misplaced!  I wouldn't have thought it possible.

![image](https://user-images.githubusercontent.com/61856645/111516551-65ba0c80-872a-11eb-8bc1-4dc73138ed18.png)

This happens with other WT widths, other font sizes, and other numbers of asterisks echoed ... but only (and always) when there are exactly three on the last line.

![image](https://user-images.githubusercontent.com/61856645/111517223-36f06600-872b-11eb-906c-da9df7ee0ebd.png)
![image](https://user-images.githubusercontent.com/61856645/111517588-9b132a00-872b-11eb-8c93-b7f0d16f9eee.png)

Here's another, seeming related observation.  Below, recall the first echo command and add 'x' to the end of the string ... the last '\*' drops down (remove the 'x' and the '\*' goes back up).

![image](https://user-images.githubusercontent.com/61856645/111518530-897e5200-872c-11eb-9f4e-05a1d03167e8.png)

Having fooled around a lot, I might sum it up like this (all I did was type three asterisks).

![image](https://user-images.githubusercontent.com/61856645/111519414-7029d580-872d-11eb-9abf-81776314a2a3.png)

# Expected behavior
Character not misplaced.

# Actual behavior

**Comment by DHowett** [comment]
This is a ligature applied to `***` by the font you're using.

**Comment by vefatica** [comment]
What's it supposed to represent?

**Comment by DHowett** [comment]
The other one (`*x`) is a ligature applied by the font you're using to `*` followed by an alpha character.

Cascadia Code is a coding font. It has ligatures that make it look slightly different for certain types of code. Like the ones for `<$` and `##` and even `!=`.

It's supposed to represent "I don't actually know, but Fira Code does it too. Since people use `***` to mean something in some language, it seemed reasonable to give it a special visual treatment."

**Comment by vefatica** [comment]
Actually (my fault) that was Cascadia Code.  Consolas doesn't do it.

Thanks.

**Comment by DHowett** [comment]
If you happen to like the Cascadia style, there's `Cascadia Mono` (also included by default) which does not have ligatures.

**Comment by vefatica** [comment]
Cascadia's OK but I prefer Consolas because it's more vertically spread out.
