### ISSUE TITLE
Wrap/nowrap when copying multiple lines ... SetConsoleMode?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9528]
How is the wrap/nowrap behavior when copying multiple lines handled?  Is it controlable with SetConsoleMode?

Thanks!

**Comment by DHowett** [comment]
Applications what write off the end of the line force a wrap. You can disable "deferred EOL" with SetConsoleMode.

**Comment by vefatica** [comment]
Can you be more specific?

I select two lines with the mouse and copy with a right-click.  They comprised output which reached the end of the first line and was continued on the next line.  What determines how they will paste (anywhere) ... as a single line or as two lines with a CRLF between them?

**Comment by vefatica** [comment]
Wasn't my question well-posed?  Let me try a different way.  Don't bother trying to reproduce this; it's apparently an anomaly of the shell I'm using.  Here's a command and its output, both selected (left button drag) from a console's history.

![image](https://user-images.githubusercontent.com/61856645/111669526-459f5180-87ed-11eb-90a0-3b898dc1c281.png)

When I copy (right-click) and paste into an editor, I get 

![image](https://user-images.githubusercontent.com/61856645/111669145-dde90680-87ec-11eb-8b08-4ad8adb04446.png)

What can lead to this ... the command not wrapped and the output wrapped after copy/paste?

**Comment by DHowett** [comment]
> Wasn't my question well-posed?

Try as I might, I have been unable to defeat the need for _sleep_. Your question will be processed in the order in which it was received.

**Comment by vefatica** [comment]
Sorry about that!  I'm noted for impatience.  I can't be the only person who has grown accustomed to your attentiveness.

**Comment by DHowett** [comment]
So! Wrapping.

Wrapping is a source of a bunch of issues for us.

In general, text is considered wrapped in the following circumstances.

* **Traditional Console Output**
   * `ENABLE_WRAP_AT_EOL_OUTPUT` on: Text is written in the rightmost column.
      * The cursor automatically moves into the next row, and the previous row is considered wrapped.
   * `ENABLE_WRAP_AT_EOL_OUTPUT | DISABLE_NEWLINE_AUTO_RETURN`: Text is written in the rightmost column, _and then another non-control character is written in the "deferred" position_.
      * The first write moves the cursor "off the right edge", and the next character is placed on the next row.
* **VT Output**
      * Writing a newline in the "deferred" position does not cause a wrap, because it expresses _intent_ to move to a new line.
   * VT output behaves like `ENABLE_WRAP_AT_EOL_OUTPUT | DISABLE_NEWLINE_AUTO_RETURN` (_only_ because it is recommended that you use both of these in addition to `ENABLE_VIRTUAL_TERMINAL_PROCESSING`, I think?)

Moving the cursor between writes breaks wrapping.

Some applications, especially when they draw the prompt themselves, _explicitly_ hard-wrap their output. What's likely happening is that the input line is being sent as `V:\>echo fooooooooo` `\n` `ooooo`, and when the command is processed `foooooooooooooo` is being generated as a single screen write (subject to the rules above.)

> I can't be the only person who has grown accustomed to your attentiveness.

😅 you're right

**Comment by DHowett** [comment]
(Sorry -- edited the above to fix an out of order bullet that somewhat changes the meaning.)

**Comment by vefatica** [comment]
Hmmm!  I've been trying to figure out how to ...

```
WCHAR szString[] = L"************************************************\n";
// this will wrap
WriteConsoleW(GetStdHandle(STD_OUTPUT_HANDLE), szString, lstrlen(szString), &dwWrote, NULL);
// do something to the console mode
WriteConsoleW(GetStdHandle(STD_OUTPUT_HANDLE), szString, lstrlen(szString), &dwWrote, NULL);
```

... then copy all the output, paste it somewhere, and have one wrap and the other not wrap.  No success yet; both wrap!  Any ideas?

**Comment by DHowett** [comment]
Nope, both of those will wrap. There is no console mode that will disable wrapping.

Sorry! :smile:

**Comment by DHowett** [comment]
Hard wrapping must be done by the application -- measure the screen, print hard-wrapped sections of line with newlines between the sections. That's also the way voted most likely to work with all other terminal emulators.

**Comment by zadjii-msft** [comment]
FYI - we are also tracking an intermittent issue where sometimes the Terminal decides that a line that should have wrapped actually didn't. We're tracking that broadly in #5800 and more specifically in #6901. I haven't the damndest clue what causes that, but if you could get a specific repro for it, then I could fix it and make a test ☺️

**Comment by vefatica** [comment]
(#6901) I can repro this much.  TYPE the file in CMD (or TCC) in WT ... copy the wrapped line and paste into notepad ... result: one line.

SSH (in WT) to localhost (no WSL involved) ... TYPE the file in the SSH session ... copy the wrapped line and paste into notepad ... result: several lines.

But I can't (as in #6901) get a different (single line) result after resizing WT.

[TCC is my SSH shell.]

**Comment by DHowett** [comment]
SSH uses an old version of ConPTY :smile: which did not support line wrapping!

**Comment by vefatica** [comment]
> SSH uses an old version of ConPTY 😄 which did not support line wrapping!

I'm not sure what you mean.  SSH is using the usual conhost.exe on both ends and mine seems pretty good at line wrapping.

**Comment by DHowett** [comment]
When you SSH to a Windows machine, it hosts the console application using the version of conhost _on that machine_. That version of conhost contains whatever version of contpy existed at the time. The old version of ConPTY¹ cannot properly communicate which lines "wrapped" when it reproduces the screen content. The old version of ConPTY¹ will therefore emit any lines, wrapped or not, with a newline at the end of them. They will appear to be "hard-wrapped" from the perspective of any recipient.

¹ I promise you are using an old version of conpty if you're SSHing _to a Windows machine_.

**Comment by vefatica** [comment]
I'm SSHing to localhost and I see this.  Both conhosts are c:\windows\system32\conhost.exe.  I just want to understand.

```
Start  Time            Pid   PPid       CPU(s)     WS(M)  Name
--------------------------------------------------------------------------------
03/19  12:04:46.178   6428   9536        0.016       7.8  sshd.exe
03/19  12:04:46.180  11212   6428        0.016      13.3  conhost.exe
03/19  12:04:48.492  10572   6428        0.000       7.7  sshd.exe
03/19  12:04:48.503  11912  10572        0.047       5.4  conhost.exe
```

**Comment by DHowett** [comment]
I can't figure out what you do not understand.

On the server, ConPTY reproduces the "screen" for the hosted console application. -AND-
ConPTY cannot reproduce wrapped lines. -THEREFORE-
ConPTY hard-wraps the screen for the hosted console application. -SO-
When you select text that came out of ConPTY, it is hard-wrapped.

**Comment by vefatica** [comment]
I don't have a good idea what ConPTY is ... a capability of conhost.exe separate from that of supplying the usual console window?  And while console windows do wrapping, ConPTY doesn't?  I gather an up-to-date OpenConsole.exe is better at this?

**Comment by DHowett** [comment]
You have been on, like, fourteen threads where I talk about ConPTY in an answer to your question yet you haven't ventured to ask what it _is_? Oi!

Yep! ConPTY is a way for conhost to convert Win32 console application output to VT sequences (and the same for input) such that normal terminal emulators can "host" windows console applications.

**Comment by zadjii-msft** [comment]
You might also want to read: #57, https://docs.microsoft.com/en-us/windows/console/pseudoconsoles

**Comment by DHowett** [comment]
As well as [JDeBP's answer page about hosting console apps](http://jdebp.info./FGA/capture-console-win32.html), which documents why it was _so hard, for so long_.
