### ISSUE TITLE
`main` is horked, bought farm, etc.

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9529]
Maybe this is just my machine?

**Comment by DHowett** [comment]
```
ModLoad: 00007ffc`04af0000 00007ffc`04afe000   C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.8.761.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
(16d4.3e64): Windows Runtime Originate Error - code 40080201 (first chance)
(16d4.3e64): C++ EH exception - code e06d7363 (first chance)
(16d4.3e64): C++ EH exception - code e06d7363 (first chance)
TerminalApp.dll!00007FFBCBA879DE: ReturnHr(1) tid(3e64) 800401F9 Error in the DLL
    Msg:[winrt::hresult_error: Error in the DLL] 
```

**Comment by DHowett** [comment]
Backtrace lands us in XAML Loading.

**Comment by DHowett** [comment]
**Terminal.Control.dll is 36kb -- it's empty!**

**Comment by skyline75489** [comment]
I'm seeing the same thing:

```text
Exception thrown at 0x00007FF96441D759 (KernelBase.dll) in WindowsTerminal.exe: 0x40080202: WinRT transform error 
Exception thrown at 0x00007FF96441D759 (KernelBase.dll) in WindowsTerminal.exe: WinRT originate error - 0x800401F9 : 'DLL 中出错'.
```

**Comment by DHowett** [comment]
I have tried `/WHOLEARCHIVE` (to encourage TermControl.dll to link the entire lib) and `UseLibraryDependencyInputs` (to make MSBuild include _every `.obj` file_ instead of the `.lib` files).

Neither one worked. I got a 200kb library that's still missing the Xaml Metadata Provider ... even though it's _in the link line_ and _in the lib file_(!)

**Comment by zadjii-msft** [comment]
ho boy

**Comment by zadjii-msft** [comment]
Things I've tried unsuccessfully: 
* [x] `/opt:noref`
* [x] add WindowsApps.lib to AdditionalDependencies
* [x] Add types to the project references?
* [x] add the headers to the dll project?

**Comment by skyline75489** [comment]
These are what I've tried unsuccessfully:

* add WindowsApps.lib to AdditionalDependencies
* add the headers to the dll project
* correct the package.config path (the path [here](https://github.com/microsoft/terminal/blob/acdcdcaccb63064e5967f573198c5a05f483a55f/src/cascadia/TerminalControl/dll/TerminalControl.vcxproj#L49) is actually incorrect, should be `../package.config`)

**Comment by zadjii-msft** [comment]
Yep, it was definitely the projectname thing. I'm gonna update all the .dll's `.def` mentions to 
```
    <None Include="$(ProjectName).def" />
```

so it's immediately obvious to the next person who hits this

**Comment by DHowett** [comment]
ARGH

**Comment by miniksa** [comment]
Wow that's a trip.

**Comment by skyline75489** [comment]
random: I never get what is "horked" and what the heck is "bought farm"? I honestly don't get it 😂

**Comment by zadjii-msft** [comment]
Oh, those are all just euphemisms for "died". The Terminal crashed so much in the pre-0.4 days that we had to keep coming up with new things to say. Some highlights:
* bought the farm
* went to beeftown
* took a trip upstate
* experienced an unexpected loss of altitude

**Comment by skyline75489** [comment]
Ha that makes sense. Guess I still have a lot to learn about English.

The “loss of altitude”, it’s definitely Halo, right? 🤣

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Mike Griese ***@***.***>
发送时间: Friday, April 16, 2021 7:38:42 PM
收件人: microsoft/terminal ***@***.***>
抄送: Chester Liu ***@***.***>; Comment ***@***.***>
主题: Re: [microsoft/terminal] `main` is horked, bought farm, etc. (#9529)


Oh, those are all just euphemisms for "died". The Terminal crashed so much in the pre-0.4 days that we had to keep coming up with new things to say. Some highlights:

  *   bought the farm
  *   went to beeftown
  *   took a trip upstate
  *   experienced an unexpected loss of altitude
