### ISSUE TITLE
windows terminal will send one more character when use vim view mode to select characters send to repl

### ISSUE THREAD

**Issue by ZihaoXingUP** [microsoft/terminal#9530]
windows terminal will send one more character when use vim view mode to select characters send to repl

**Comment by skyline75489** [comment]
OK a lot of things are missing. What repl are you using? Are you using PowerShell? Are you using WSL?

You can't expect us to help you with almost no useful information.

**Comment by ZihaoXingUP** [comment]
> OK a lot of things are missing. What repl are you using? Are you using PowerShell? Are you using WSL?
> 
> You can't expect us to help you with almost no useful information.

i use vim-repl [vim-repl](https://github.com/sillybun/vim-repl.git), [Nvim-R](https://github.com/jalvesaq/Nvim-R.git) , both of them in windows terminal will send one more character in WSL vim environment. but when i use vim-repl or Nvim-R in xshell or linux system's terminal ,they are working fine and won't send one more character. 
so , i think it's windows terminal's problem and need to be solved.

**Comment by skyline75489** [comment]
Can you attach a screenshot of something to illustrate this issue? Also, what is the terminal version you are using? And the Windows version?

**Comment by skyline75489** [comment]
Yeah there's probably a lot of hidden problems in Windows Terminal and we all want to solve them. We'd love to hear feedbacks from the community. Just we need like a lot of information to determine what exactly the problem is and possibly find a way to fix it. So please be sure to provide as much as information as you can when you submit issues on Github.

**Comment by ZihaoXingUP** [comment]
> Yeah there's probably a lot of hidden problems in Windows Terminal and we all want to solve them. We'd love to hear feedbacks from the community. Just we need like a lot of information to determine what exactly the problem is and possibly find a way to fix it. So please be sure to provide as much as information as you can when you submit issues on Github.

i only select the 'a' in vim view mode ,but it sent the 'a=' in windows terminal preview 1.7.572.0 in windows 10 1909 for a long time of all version windows terminal i have used, but it will be ok in Xshell or linux terminal's vim .

![image](https://user-images.githubusercontent.com/68001792/111570838-99576e00-87e0-11eb-8ad2-675b3cf640ab.png)

**Comment by skyline75489** [comment]
OK I've tried the plugin (nice plugin, btw) but I can't repro this locally. I'm using WSL2 (Ubuntu 20.04) and Vim 8.1. Are you using WSL2?

**Comment by ZihaoXingUP** [comment]
i use the WSL1(Ubuntu20.04), but when i use windows terminal's cmd or wsl to connect the linux sever by ssh , it also will send one more character in vim view select mode.

**Comment by ZihaoXingUP** [comment]
> OK I've tried the plugin (nice plugin, btw) but I can't repro this locally. I'm using WSL2 (Ubuntu 20.04) and Vim 8.1. Are you using WSL2?

i meet this problem in cmd , wsl of cmder's terminal or windows terminal. but in xshell or linux system's terminal, it work ok.

**Comment by ZihaoXingUP** [comment]
> OK I've tried the plugin (nice plugin, btw) but I can't repro this locally. I'm using WSL2 (Ubuntu 20.04) and Vim 8.1. Are you using WSL2?

it will always send one more character and will report error unless there is a space after it in windows terminal,

**Comment by DHowett** [comment]
Can you send a screenshot from xshell?

This is a common problem people have with vim.

The character _under the cursor_ is part of the visual selection. This is true on every terminal emulator.

Here is putty.

![image](https://user-images.githubusercontent.com/189190/111574836-7a1df980-876a-11eb-8532-715f274f352b.png)

![image](https://user-images.githubusercontent.com/189190/111574854-80ac7100-876a-11eb-8e9c-ac514676d013.png)

**Comment by ZihaoXingUP** [comment]
> Can you send a screenshot from xshell?
> 
> This is a common problem people have with vim.
> 
> The character _under the cursor_ is part of the visual selection. This is true on every terminal emulator.
> 
> Here is putty.
> 
> ![image](https://user-images.githubusercontent.com/189190/111574836-7a1df980-876a-11eb-8532-715f274f352b.png)
> 
> ![image](https://user-images.githubusercontent.com/189190/111574854-80ac7100-876a-11eb-8e9c-ac514676d013.png)

i send you the screenshot on xshell, it works very well and won't sent one more character ,it is the windows terminal's problem, you can also check it on xshell.
![image](https://user-images.githubusercontent.com/68001792/111581734-c44bbd00-87f4-11eb-878c-3c9146a94738.png)

**Comment by DHowett** [comment]
How do you select `a`? Mouse? Keyboard?

If keyboard, what do you press? Please help me reproduce this issue 😄

**Comment by ZihaoXingUP** [comment]
i sleep last night when you reply me . now ,i just wake up. i use the keyboarkd and do not use the mouse in vim.
using vim-repl plugin, first , i press the 'v' in keyboard to start the visual vim mode, then, i press 'hjkl' to select the words or lines that i want to send , at last , i press the '<leader>+w'  to send the words or lines i selected to run them in vim.
you can check more details on [vim-repl](https://github.com/sillybun/vim-repl) or [Nvim-R](https://github.com/jalvesaq/Nvim-R]

**Comment by ZihaoXingUP** [comment]
> How do you select `a`? Mouse? Keyboard?
> 
> If keyboard, what do you press? Please help me reproduce this issue 😄

i sleep last night when you reply me . now ,i just wake up. i use the keyboarkd and do not use the mouse in vim.
using vim-repl plugin, first , i press the 'v' in keyboard to start the visual vim mode, then, i press 'hjkl' to select the words or lines that i want to send , at last , i press the '+w' to send the words or lines i selected to run them in vim.
you can check more details on [vim-repl](https://github.com/sillybun/vim-repl) or [Nvim-R](https://github.com/jalvesaq/Nvim-R)

**Comment by skyline75489** [comment]
OK this is what I got:

1. Enter visual mode:

![image](https://user-images.githubusercontent.com/4710575/111725686-77262480-88a2-11eb-88e7-869e4df19d92.png)

Then `+w` will send `a` only

2. Press `l`

![image](https://user-images.githubusercontent.com/4710575/111725733-8efda880-88a2-11eb-9558-56c960e7472a.png)

Then `+w` will send `a=`.

Is this what you seeing?

**Comment by ZihaoXingUP** [comment]
> OK this is what I got:
> 
> 1. Enter visual mode:
> 
> ![image](https://user-images.githubusercontent.com/4710575/111725686-77262480-88a2-11eb-88e7-869e4df19d92.png)
> 
> Then `+w` will send `a` only
> 
> 1. Press `l`
> 
> ![image](https://user-images.githubusercontent.com/4710575/111725733-8efda880-88a2-11eb-9558-56c960e7472a.png)
> 
> Then `+w` will send `a=`.
> 
> Is this what you seeing?

yeah, the method is just like what you said, in windows terminal, if you select 'a', it will send 'a=' because it will send one more character in windows terminal, but in xshell, it will only send 'a',  so, it can work well in Xshell. 
so ,the windows terminal have this problem in vim-repl.

**Comment by skyline75489** [comment]
How about just do not press `l`? This way it only sends "a", right?

Seems to me entering visual mode will automatically select "a".

**Comment by ZihaoXingUP** [comment]
> How about just do not press `l`? This way it only sends "a", right?
> 
> Seems to me entering visual mode will automatically select "a".

i just never press 'l' to select the right side character '=', i only select the 'a' character in the vim visual mode ,but it will send 'a=' in windows terminal,
for example, there is a 'year=5' code, ,in windows terminal, if you select "yea", it will send "year", if you select "year", it will send "year=",  so , it will always send one more character in windows terminal automatically.

**Comment by skyline75489** [comment]
So you're saying if you repeat what I did,  just press `v`, enter the visual mode, the terminal will send `a=`?

**Comment by ZihaoXingUP** [comment]
> So you're saying if you repeat what I did, just press `v`, enter the visual mode, the terminal will send `a=`?

i repeat it, in windows terminal's vim , if you just press `v,` it will send `a`, if you also select `a` , it will send `a=` 

`year=5` ,if you select `yea` ,it will send `year` ,if you select `year`, it will send `year=`

**Comment by skyline75489** [comment]
OK, now I see. Listen to me very carefully:

> if you just press v, it will send a

when you press `v`, it already selected `a`! That's why it sends `a`.

>  if you also select `a` , it will send `a=`

How do select `a`? Are you pressing `l` ? If you press `l`, it selects `a=`, that's why it sends `a=`. I know it looks like you're selecting only `a`. That's the point in https://github.com/microsoft/terminal/issues/9530#issuecomment-801621599 . It's not exactly the same as what you see.

**Comment by ZihaoXingUP** [comment]
> OK, now I see. Listen to me very carefully:
> 
> > if you just press v, it will send a
> 
> when you press `v`, it already selected `a`! That's why it sends `a`.
> 
> > if you also select `a` , it will send `a=`
> 
> How do select `a`? Are you pressing `l` ? If you press `l`, it selects `a=`, that's why it sends `a=`. I know it looks like you're selecting only `a`. That's the point in [#9530 (comment)](https://github.com/microsoft/terminal/issues/9530#issuecomment-801621599) . It's not exactly the same as what you see.

i think you do not know it , `a` is too short, many times ,the variable is a long word ,you want to select the whole word to run it , ,`year=5`， if i select `year` and the cursor is `year`, it will send `year=` in windows terminal. if i can't select the whole word , i will feel very terrible every times

if i select `year` and the cursor is `year`, it will just send `year` in xshell, it works very well in xshell. 

it is so terrible that if i want to send `year`, i only can select `yea` in windows terminal, rather than i can select the whole word `year` in xshell or linux terminal. 

if  you use the windows system ,i hope you can use xshell to run it  , it works very well .  in windows terminal ,it was really terrible and unfriendly, that you only can select `yea`, you can't select `year`

**Comment by ZihaoXingUP** [comment]
> i hope you can use xshell to run it , it works very well . in windows terminal ,it was really terrible and unfriendly, that you only can select `yea`, you can't select `year`



> OK, now I see. Listen to me very carefully:
> 
> > if you just press v, it will send a
> 
> when you press `v`, it already selected `a`! That's why it sends `a`.
> 
> > if you also select `a` , it will send `a=`
> 
> How do select `a`? Are you pressing `l` ? If you press `l`, it selects `a=`, that's why it sends `a=`. I know it looks like you're selecting only `a`. That's the point in [#9530 (comment)](https://github.com/microsoft/terminal/issues/9530#issuecomment-801621599) . It's not exactly the same as what you see.

Do you know Xshell  in windows systerm？ you can use xshell to run it , Xshell terminal can works very well . in windows terminal ,it was really terrible and unfriendly, that you only can select `yea` to run it, you can't select `year`

**Comment by skyline75489** [comment]
OK. Can you repeat what I did in https://github.com/microsoft/terminal/issues/9530#issuecomment-802507510 and attach the screenshot? I'd like to see how it looks like.

**Comment by skyline75489** [comment]
Yeah I know XShell. We all know what it is. First, XShell is a commercial software that we can not just grab and use. Do understand the strict copyright restrictions in Microsoft about what we can use. Second, this isn't about how XShell behaves, this repo is about Windows Terminal. And we all want it to be better.

**Comment by ZihaoXingUP** [comment]
> Yeah I know XShell. We all know what it is. First, XShell is a commercial software that we can not just grab and use. Do understand the strict copyright restrictions in Microsoft about what we can use. Second, this isn't about how XShell behaves, this repo is about Windows Terminal. And we all want it to be better.

### in windows terminal 

#### select `yea`

in the widnows terminal ,if i select `yea`, it will send `year`

![image](https://user-images.githubusercontent.com/68001792/111747369-36420600-88ca-11eb-8eae-7eb03973104f.png)

#### select `year`
 
if i select `year`, it will send `year=` in windows terminal

![image](https://user-images.githubusercontent.com/68001792/111747641-85883680-88ca-11eb-8105-88ee2ee61bfc.png)

### In Xshell
####  slelect `yea` 
if i select `yea`, it will send `yea`

![image](https://user-images.githubusercontent.com/68001792/111748548-a43afd00-88cb-11eb-851d-fb07cc6ed816.png)

#### select `year`
if i select `year` , it will send `year`
![image](https://user-images.githubusercontent.com/68001792/111748992-25928f80-88cc-11eb-99ab-3d65f8a9a291.png)

**Comment by skyline75489** [comment]
OK. I completely understand what you mean. I can think of two options. 

1. Put these in your `.vimrc`:

```vimrc
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
```

2. Put this in your terminal settings.json:

```json 
"cursorShape": "bar",
```

See [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#cursor-shape) for more options.

**Comment by ZihaoXingUP** [comment]
> OK. I completely understand what you mean. I can think of two options.
> 
> 1. Put these in your `.vimrc`:
> 
> ```
> let &t_SI = "\<Esc>[6 q"
> let &t_SR = "\<Esc>[4 q"
> let &t_EI = "\<Esc>[2 q"
> ```
> 
> See [#4335 (comment)](https://github.com/microsoft/terminal/issues/4335#issuecomment-577365966) for details.
> 
> 1. Put this in your terminal settings.json:
> 
> ```json
> "cursorShape": "bar",
> ```
> 
> See [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#cursor-shape) for details about the `cursorShape` option.

ok, i change the window terminal settings , thanks!

**Comment by skyline75489** [comment]
You're welcome. 

Please try to understand & describe your problem before getting into discussions like this one. If you want us to help you, first you need to make sure we understand you. If you issue was "I want block cursor instead of bar cursor", this issue would've been solved yesterday, without 20+ emails sent to everyone subscribe this repo. Keep saying "the windows terminal have this problem in vim-repl" does NOT helps anyone. 

Please understand that reading the issues and get involved in discussions takes time. We all want to help the community but time is valuable for everyone.

Check out [How-To-Ask-Questions-The-Smart-Way（中文）](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md) to learn how to answer a good question.
 
If you don't feel comfortable writing in English, write in Chinese and I'll translate for you. Just make sure you're asking a *good question.

**Comment by skyline75489** [comment]
If the article feels too long, I've picked the most important section I can think of: 

**Don't rush to claim that you have found a bug**

[**别动辄声称找到 Bug**](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%88%AB%E5%8A%A8%E8%BE%84%E5%A3%B0%E7%A7%B0%E6%89%BE%E5%88%B0-bug)

**Comment by ZihaoXingUP** [comment]
> If the article feels too long, I've picked the most important section I can think of:
> 
> **Don't rush to claim that you have found a bug**
> 
> [**别动辄声称找到 Bug**](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%88%AB%E5%8A%A8%E8%BE%84%E5%A3%B0%E7%A7%B0%E6%89%BE%E5%88%B0-bug)

haha, i see and learn the artical, thanks!  ^_^
