### ISSUE TITLE
[off-topic] Which version of C++?

### ISSUE THREAD

**Issue by mayureshkathe** [microsoft/terminal#9531]
Would you please mention which version of C++ is being used for developing the "Terminal" project?
I dug-in, but couldn't find the required details.
Sorry for this off-topic note.

**Comment by skyline75489** [comment]
I think as long as you are using the latest version of Visual Studio, you'll be find. The exact C++ version is probably C++ 14?

**Comment by mayureshkathe** [comment]
Glad to know. Thank you.

**Comment by DHowett** [comment]
We use C++17, and we want to use C++20 in the future. :smile:

**Comment by skyline75489** [comment]
Wait, does VC++ has *full support* of C++17 now? I always had the impression that it has only partial support of C++17, and most of C++14. Guess I'm not following the trend.
