### ISSUE TITLE
windows terminal will send one more character when use vim view mode to select characters send to repl using vim-repl or Nvim-R plugin

### ISSUE THREAD

**Issue by ZihaoXingUP** [microsoft/terminal#9532]
windows terminal will send one more character when use vim view mode to select characters send to repl using [vim-repl](https://github.com/sillybun/vim-repl.git) or [Nvim-R](https://github.com/jalvesaq/Nvim-R.git) plugin ,but when i use xshell, it won't send one more character and can work well. so ,i think it is the windows terminal's problem , and need to be solved. 

use vim-repl to send 'a' on windows terminal :

![image](https://user-images.githubusercontent.com/68001792/111582657-1b05c680-87f6-11eb-9c7e-221001aaae3d.png)

use vim-repl to send 'a' on xshell:

![image](https://user-images.githubusercontent.com/68001792/111582854-661fd980-87f6-11eb-988f-9008fa8c9fb9.png)

**Comment by skyline75489** [comment]
Please do not open duplicate issue. 

#9530

**Comment by ZihaoXingUP** [comment]
> Please do not open duplicate issue.
> 
> #9530

the windows terminal worker said to me "This is a common problem people have with vim. The character under the cursor is part of the visual selection. This is true on every terminal emulator on windows". he said "this problem also in putty."
but when when i use the xshell on windows, it can work well and won't send one more character. but he din't see it work on xshell in windows.

**Comment by skyline75489** [comment]
Yeah I get it. I happen to know this "windows terminal worker" personally. My point is you can just use that issue for discussion. Please do not open duplicate issue for the same problem, because this causes unnecessary noises for people who subscribe this repo.

**Comment by ZihaoXingUP** [comment]
> Yeah I get it. I happen to know this "windows terminal worker" personally. My point is you can just use that issue for discussion. Please do not open duplicate issue for the same problem, because this causes unnecessary noises for people who subscribe this repo.

because he know the problem in windows terminal, but he close the issue  so that i can't find my issue and reply him.

**Comment by skyline75489** [comment]
Oh man, Here, just click the link #9530 .

You can reply to closed issue. You can even reopen them, if you like.

**Comment by ZihaoXingUP** [comment]
> Oh man, Here, just click the link #9530 .
> 
> You can reply to closed issue. You can even reopen them, if you like.

ok, thank's your reply.

**Comment by skyline75489** [comment]
No problem. 

Please do not take this personally. It's just an issue. It's not a Bitcoin or something. No one want to "steal" your issue away. We all trying to help. We just need to understand the problem better. That "windows terminal worker" is a good guy who leads a great team. But as you can see there's 1200+ open issues. It takes time (sometimes a very long time) to understand and solve an issue. We like to hear feedbacks from everyone. Just please be patient.
