### ISSUE TITLE
Mouse scroll in vim like iTerm2 and Konsole

### ISSUE THREAD

**Issue by myy1966** [microsoft/terminal#9534]
# Description of the new feature/enhancement

The mouse scroll in the windows terminal when using vim is different from iTerm2 and Konsole. After "set mouse=a" in vim, when scrolling down, the cursor will stay on the sixth line.  But in iTerm2 or Konsole, the cursor will stay on the first line.

Scrolling behavior in windows terminal with WSL2:
![wt-wsl-vim](https://user-images.githubusercontent.com/10590090/111601946-d6862500-880d-11eb-9954-ac9150d6eb13.gif)

Scrolling behavior in iterm2  with MacOS:
![iterm2-vim](https://user-images.githubusercontent.com/10590090/111602062-f3baf380-880d-11eb-9865-57f32b65b1b0.gif)

And in iTerm2, there is a setting to send the arrow keys when in alternate mode. When setting this to yes, Without "set mouse=a" in vim, scroll the wheel can move the arrow and screen. Konsole has a similar function.

![iterm2-vim-alternate](https://user-images.githubusercontent.com/10590090/111602562-6d52e180-880e-11eb-90a8-8a4cbf152f6b.gif)

# Proposed technical implementation details (optional)

1. Change the cursor position to the first line and last line when scrolling down and up, respectively.
2. Add a setting to send the arrow keys when in application link vim.

# Software Version
Windows Terminal: 1.6.10571.0
WSL2: Ubuntu 18.04
iTerm2: 3.2.5
Konsole: 19.12.3

**Comment by zadjii-msft** [comment]
I'm pretty sure this will work when the Terminal fully supports the alternate buffer - check out #381 for more info

/dup #381

**Comment by j4james** [comment]
See also #3321.

**Comment by myy1966** [comment]
> I'm pretty sure this will work when the Terminal fully supports the alternate buffer - check out #381 for more info
> 
> /dup #381

Yes, I know the wheel scroll can use in vim, but I found the behavior is slightly different from iTerm2 and Konsole.  When I scroll down or scroll up, the cursor position is different.  The iTerm2 and Konsole will make the cursor stay on the first and the last line, but the windows terminal makes the cursor stay on the sixth line.

My second suggestion is the same as #3321.
