### ISSUE TITLE
Feature: A option to disable alert sound.

### ISSUE THREAD

**Issue by andrewaldasoro** [microsoft/terminal#9540]
# Environment
Windows 10 Pro 20H2 (Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0)
Windows Terminal 1.6.10571.0

Any other software?
Git Bash 3.4.4

# Steps to reproduce
1.- Open Windows Terminal
2.- Open a file to explore with less. Ex: `less file.txt`
3.- Press Upwards Arrow multiple times
4.- Feel the annoying sound, unless you have disabled it from the OS or changed the default to a better one.

# Expected behavior
An option to disable terminal alert sound from the terminal and just for the terminal.

# Actual behavior
There is no option to disable sound from the terminal and you can do it, finding workarounds but it could be cool to have that option.

**Comment by WSLUser** [comment]
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#bell-notification-style.

Seriously suggest checking docs and issues first.

**Comment by zadjii-msft** [comment]
Yep, this can be turned off with `"bellStyle": "none"`

**Comment by DHowett** [comment]
**HOWEVER**. Some applications do not _use_ bell support. They actually play the sound directly. _We cannot stop them when they do that._
