### ISSUE TITLE
Setting startingDirectory to WSL path causes indefinite application hang

### ISSUE THREAD

**Issue by zaxbux** [microsoft/terminal#9541]
# Environment

```none
Windows build number: 19041.867
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce

Add the following `startingDirectory` to a profile like so:

```json
{
  "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
  "hidden": false,
  "name": "Ubuntu-20.04",
  "source": "Windows.Terminal.Wsl",
  "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\zach"
}
```

# Expected behavior

Terminal launches profile in starting directory. This has worked for awhile, issue started occuring after some recent updates (either Windows or Terminal).

# Actual behavior

Terminal hangs forever when starting profile from new tab dropdown, jumplist, etc.

![wt_bug](https://user-images.githubusercontent.com/5186921/111687952-27832280-87e8-11eb-92ec-2a49be457537.png)

Note: this screenshot was taken after the `startingDirectory` was added in my `settings.json` while application was running. Terminal crashes as soon as the updated profile was clicked. Terminal launched fine and profile worked before adding line.

**Comment by DHowett** [comment]
Sorry -- all we do is pass that path off to CreateProcess. If the WSL interop implementation is hanging, it'll be bad...

I wonder if Terminal can/should have a process startup watchdog? "[process failed to start in 10 seconds; you likely don't want to try to continue]"

**Comment by Nacimota** [comment]
> I wonder if Terminal can/should have a process startup watchdog? "[process failed to start in 10 seconds; you likely don't want to try to continue]"

Separate but related: WSL2 takes about 5 seconds to start up cold on my system, and I notice the terminal UI hangs for the duration.

**Comment by zadjii-msft** [comment]
Oh that's why my "Good Morning" script seems to hang. Not because it's asking the Terminal to do too much, but because the launch of WSL is slow. 

I wonder if we can start the process maybe on a background thread? Or if we're waiting for the connection to actually start before doing UI work, could we just, not?

**Comment by DHowett** [comment]
@zadjii-msft not without risking the WSL profiles (and if one is set as default, a pop-up dialog saying "lol you messed up somehow").

This is, in part, why I keep talking about caching generated profiles 😉

**Comment by zaxbux** [comment]
@DHowet I ended up nuking my WSL distros, and the issue went away. Watchdog of some sort would be nice, since the only way I could kill the terminal process was though Terminal's PC Settings "Terminate" button.

**Comment by DHowett** [comment]
Oh, I realize now @zadjii-msft that you're talking about spawning the connection in the background, not launching WSL to scan for things.

We also _evaluate the starting directory_ for validity (!) during settings load.

**Comment by zadjii-msft** [comment]
Ohkay good, I thought there must have been a miscommunication.



> We also _evaluate the starting directory_ for validity (!) during settings load.

Oh well that's probably what's doing it. Maybe we should just ditch that 🤔

**Comment by zadjii-msft** [comment]
I'm bumping this to 1.8 - we might want to preemptively fix this, esp. before pushing OSC9;9 to stable

**Comment by zadjii-msft** [comment]
Oh no, this isn't what I thought it was. I thought we had some quick path validation if a path existed for the OSC9;9 case. But we actually don't...

* in #8330, the only validation is: during duplicate(Tab|Pane), if the control has a path, use that. Doesn't matter what it is, no checking if it's good, just use it. 
* #8934 did not add any other validation, it just mde the list of paths we accept bigger.
* #9397 furthermore additionally did not add any extra validation. 
* #8898 & #9118 did add a step where `wt` will switch it's CWD when spawning a new commandline. This is my only theory right now. 
  ```c++
            std::wstring cwdString{ wil::GetCurrentDirectoryW<std::wstring>() };
            std::filesystem::path cwd{ cwdString };
            cwd /= settings.StartingDirectory().c_str();
  ``` 
   If we do a `auto p = std::filesystem::path{L"C:\Windows"} \ std::filesystem::path{L"\\wsl$\home\zadjii"}`, does that need to hit the filesystem to resolve the path? That would be ultra annoying.

**Comment by stevenbrix** [comment]
for the record, i'm not seeing this issue with it hanging, i used the path:

`\\wsl.localhost\Ubuntu\home\stevenki`

windows ver: 21364.1
terminal ver: 1.7.1033.0
