### ISSUE TITLE
scrolling in emacs scrolls the screen, not emacs buffer

### ISSUE THREAD

**Issue by tsengalb99** [microsoft/terminal#9545]
In linux terminals (gnome terminal, konsole, termux, etc.), scrolling in an emacs window moves the cursor, not the actual output. Currently (version 1.6.10571.0), scroll behavior in Windows Terminal appears to be captured by the terminal and not passed on to the application, as it should. I am almost certain this is an issue with Terminal since MinTTY handles scrolling fine with GitBash, but Terminal does not.

Will this be fixed (when I last used windows terminal half a year ago, I noticed this problem), and if so, when?

**Comment by skyline75489** [comment]
what version of emacs are you using? Are you using WSL? Are you using SSH?

**Comment by skyline75489** [comment]
It's a bit complicated, but although MinTTY (GitBash) looks like Terminal, the underlying tech stacks are very different.

**Comment by tsengalb99** [comment]
ssh to an ubuntu machine, emacs 25.2.2, but the version of emacs does not seem to make a difference (tried this on multiple machines)

**Comment by skyline75489** [comment]
OK that makes sense. I know it sounds easy, there's actually a lot of things that need to be fixed, OpenSSH on Windows being an example. See https://github.com/microsoft/terminal/issues/8528#issuecomment-741544578 .

You can try the newer version of OpenSSH in [Win32-OpenSSH repo](https://github.com/PowerShell/Win32-OpenSSH).

**Comment by tsengalb99** [comment]
I installed the newer version of openssh, but the cursor still doesn't scroll. The screen stops scrolling, which is nice, but the cursor is still stuck.

**Comment by tsengalb99** [comment]
Also, it doesnt completely make sense to me why openssh on windows would be the issue. Git Bash ships with its own version of ssh (presumably also openssh), which works fine in mintty but not windows terminal. Doesn't this imply terminal's handling of scrolling and ssh is wonky?

**Comment by skyline75489** [comment]
You see, the MinTTY (together with its openssh) runs inside MSYS, which is kind of a minimal Linux environment on Windows. But the Win32-OpenSSH you're using is a *native* version of OpenSSH running on Windows. These two versions of OpenSSH are mostly the same, but remarkably different about how they interact with *terminals*. That's why you may find the SSH shipped with Git Bash is not working inside Windows Terminal. I don't want to bore you with all the technical details. The conclusion is that, the entire terminal ecosystem on Windows is not (yet) as complete as Linux. MSYS was the "old" solution that simulate what Linux does on Windows. Windows Terminal is the new kid in town.

**Comment by tsengalb99** [comment]
Interesting. How would I go about getting functioning scroll behavior then? It appears that the latest openssh still doesn't handle scrolling correctly.

I would use mintty except it doesn't offer tabs, and the other features of windows terminal are useful too.

**Comment by skyline75489** [comment]
I wish I could help but I'm a Vim user. And I don't know the SSH side of the story that well. Please be patient and wait for the response for the core developers of this project. I know it sounds a simple issue that should be solved a long time ago.

**Comment by zadjii-msft** [comment]
This sounds a lot like #9534. I think at the end of the day, this is caused by the Terminal not properly supporting the alternate screen buffer. 

/dup #381
/dup #3321
