### ISSUE TITLE
Windows Terminal hangs up and disappears on window resizing.

### ISSUE THREAD

**Issue by Hamayama** [microsoft/terminal#9547]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?

vim 8.2

```

# Steps to reproduce

1. vim aiueo.txt
   
   ( [aiueo.txt](https://github.com/microsoft/terminal/files/6170588/aiueo.txt) is text file including wide characters. )

2. Narrowing the window width by mouse.

# Expected behavior

The window is resized normally.

# Actual behavior

Windows Terminal hangs up (few seconds) and disappears.

( the condition seems to be a line wrapping of wide characters. )

**Comment by zadjii-msft** [comment]
Well, this could be any of:
* #8730
* #8596
* #8287
* #4907

Could you send us a Feedback Hub trace of the crash, to help identify the root cause?

/feedback

**Comment by Hamayama** [comment]
I sent feedback.

https://aka.ms/AAbm3go

**Comment by zadjii-msft** [comment]
@DHowett Is there anyone on the team that can actually still access feedback hub links? Or are we all locked out now 😑

**Comment by DHowett** [comment]
If I had to simply _guess_, this is the `PrepareForDoubleByteSequence` resize crash we know about. @zadjii-msft hit me up on Teams -- there's a way :smile:

**Comment by zadjii-msft** [comment]
```
 "providerName": "Microsoft.Windows.Terminal.Control",
 "lineNumber": "286",
 "fileName": "E:\\BA\\3\\s\\src\\buffer\\out\\textBuffer.cpp",
 "hresult": "2147549183",
```

Yep, it was `_PrepareForDoubleByteSequence`, which is #7417, which is #4907

/dup #4907

**Comment by Hamayama** [comment]
I understood this issue is a duplicate of #4907.
But, I will try to investigate a little by myself.

- type aiueo_unicode.txt → resize → no problem

- vim aiueo_unicode.txt → resize → problem occurs

So, there might be a display conflict with vim and windows terminal.

--
file: [aiueo_unicode.txt](https://github.com/microsoft/terminal/files/6300087/aiueo_unicode.txt)

**Comment by Hamayama** [comment]
I set up VS2019 and checked the call stack.

- vim aiueo_unicode.txt

```
src/buffer/out/textBuffer.cpp
  TextBuffer::Reflow
      ↓
  newBuffer.InsertCharacter
      ↓
  _PrepareForDoubleByteSequence
      ↓
  _AssertValidDoubleByteSequence
    // N, T failing case (uncorrectable) or
    // L, N and L, L failing cases (correctable) or
    // T, T failing case (uncorrectable)
    return false;
      ↓
  _PrepareForDoubleByteSequence
    FAIL_FAST_IF → Unhandled exception
```

**Comment by Hamayama** [comment]
I made a quick fix.

```
diff -u -r src_orig/buffer/out/textBuffer.cpp src/buffer/out/textBuffer.cpp
--- src_orig/buffer/out/textBuffer.cpp	2021-04-11 20:24:10.253074800 +0900
+++ src/buffer/out/textBuffer.cpp	2021-04-12 22:05:31.059636600 +0900
@@ -2192,6 +2192,12 @@
                 const auto dbcsAttr = row.GetCharRow().DbcsAttrAt(iOldCol);
                 const auto textAttr = row.GetAttrRow().GetAttrByColumn(iOldCol);
 
+                // workaround for https://github.com/microsoft/terminal/issues/9547
+                if (!newBuffer._AssertValidDoubleByteSequence(dbcsAttr))
+                {
+                    break;
+                }
+
                 if (!newBuffer.InsertCharacter(glyph, dbcsAttr, textAttr))
                 {
                     hr = E_OUTOFMEMORY;
```

There seems to be multiple error handling methods.
1. hr = E_OUTOFMEMORY; break;
2. CATCH_RETURN();
3. FAIL_FAST_IF();

But, no method seems to be useful for this issue ...

**Comment by DHowett** [comment]
Sorry -- we actually have a fix for this one coming back in from the Windows OS code. I haven't merged it into this repository yet!

**Comment by DHowett** [comment]
Thanks for the reminder, though -- i need to do that before we ship 1.7 (!)
