### ISSUE TITLE
Right click menu improvement

### ISSUE THREAD

**Issue by ThiagaoPlusPlus** [microsoft/terminal#9548]
# Description of the new feature/enhancement
**Right click menu today:**

![image](https://user-images.githubusercontent.com/51840085/111785978-0bd95400-889c-11eb-8e18-bb7286550fe3.png)
![image](https://user-images.githubusercontent.com/51840085/111786986-2d870b00-889d-11eb-8bc4-f4d14d2b6e77.png)

**Problem:**
If the user wanted to open an WSL shell (or other shell):
![image](https://user-images.githubusercontent.com/51840085/111788338-bc485780-889e-11eb-8688-996e24bf574d.png)
![image](https://user-images.githubusercontent.com/51840085/111788500-eb5ec900-889e-11eb-88d4-c5114a9345a2.png)
The directory path is lost.

# Proposed technical implementation details (optional)
Add the shell types as submenus:

![image](https://user-images.githubusercontent.com/51840085/111788667-19440d80-889f-11eb-9f6c-eba51e02970c.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6111 for more discussion.

/dup #6111
