### ISSUE TITLE
links are no longer clickable when there's an escaped underscore in one

### ISSUE THREAD

**Issue by zevaverbach** [microsoft/terminal#9549]
# Environment

```none
Windows build number:  10.0.18363.1379
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

Put a URL containing an escaped underscore (`\_`) in it, as you might do in a markdown document to prevent it being italicized in the markdown. Try to ctrl-click the link: it doesn't work anymore because it ignores everything after the backslash.

# Expected behavior

I expect the link to still work -- when I click it, I expect it to open in a browser or whatever the appropriate app is for a given link.

# Actual behavior
When I click such a link, it tries to open the URL up to the point of the backslash, which obviously doesn't match the complete link, which includes everything after the backslash as well.

**Comment by DHowett** [comment]
A link like that isn't decorated for direct use. It's not _supposed_ to be used -- it's been escaped, for both markdown _and the terminal_.

A link containing a `\` isn't particularly valid... and almost certainly wouldn't link to the place you intend to if we _did_ let you click it. Are you proposing that terminal detect and handle _markdown escaped_ links? Why markdown? What about ones escaped for bash? PowerShell? C?

**Comment by DHowett** [comment]
This is one in a category of issues around "things printed directly to the terminal that should have been parsed first." To make that link valid from its source format, run it through a parser for the source format. I dunno -- maybe that's heavyhanded?
