### ISSUE TITLE
Title bar color does not change when switching between dark/light mode on Windows

### ISSUE THREAD

**Issue by dmoncada** [microsoft/terminal#9554]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

(Apologies if this is a dup of another bug report. It is not AFAIK.)

1. Launch Windows Terminal
2. On Windows 10, go to: "Settings" -> "Personalization" -> "Colors"
3. Under "Choose your color" switch between the "Light" and "Dark" modes.
4. Every window should now change colors (if it supports light/dark modes.)

### Expected Behavior

The color of the Windows Terminal title bar should change to match the current mode.

### Actual Behavior

The Windows Terminal title bar retains the color it had at the time it was launched (light grey if "Light", dark grey if "Dark".)

![image](https://user-images.githubusercontent.com/26721319/111855391-ea02c000-88e1-11eb-9e2a-5a83a4df9085.png)

**Comment by j4james** [comment]
I believe this is a duplicate of issue #1230.

**Comment by dmoncada** [comment]
Got it, closing.
