### ISSUE TITLE
Support switching tab with Alt+Tab (like edge chromium)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/terminal#9555]
# Description of the new feature/enhancement
Edge chromium browser has a delightful feature: switching tab using alt+tab. If multiple tabs are opened in edge chromium, all the tabs will show separately in the alt+tab menu, along with other windows.
![image](https://user-images.githubusercontent.com/54425948/111868650-24d62800-89b6-11eb-8993-07fdfa521df3.png)
However, if multiple tabs are opened in windows terminal, only one tab is shown in the alt+tab menu. I hope that windows terminal can behave like microsoft edge, showing all tabs in the alt+tab menu. This feature is very useful when jumping from another application to a certain tab in windows terminal.

![image](https://user-images.githubusercontent.com/54425948/111868687-551dc680-89b6-11eb-8330-5245a6bed341.png)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment]
I believe this is not currently feasible for Windows Terminal. See issue #6783.

**Comment by oxygen-dioxide** [comment]
> I believe this is not currently feasible for Windows Terminal. See issue #6783.

Microsoft can provide a closed-source enhanced version of windows terminal ("windows terminal plus").

**Comment by DHowett** [comment]
> > I believe this is not currently feasible for Windows Terminal. See issue #6783.
> 
> Microsoft can provide a closed-source enhanced version of windows terminal("windows terminal plus") with this feature.

Two problems with that.

First: most of the community wouldn’t agree with that decision and it is deeply against our values as a project. 

Second: the API is not designed to be used by anyone but edge ☹️ 

/dup #6783
