### ISSUE TITLE
Unsmooth Animation on left-panel of settings

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/terminal#9556]
### Windows Terminal version (or Windows build number)

10.0.19042.0 1.7.572.0

### Steps to reproduce

1. Open settings
2. Watch the left-panel of settings (containing Startupt, Interactions...)
3. Switch very quickly between the horizontal "tabs" e.g. click on appearance and right after it (don't wait for the window to update) click on Startup

### Expected Behavior

Blue "pointer" at the left indicating what "tab" of settings is selected should smoothly move.

### Actual Behavior

When you click on a "tab" of settings and you don't wait the pointer to finish its animation and click on another "tab" while the pointer is still doing the animation it will suddenly appear next to the "tab" you selected without moving to it smoothly

Sorry for my English I hope my issue is at least understandable. A small a minor UI bug but still it is unpleasant

**Comment by zadjii-msft** [comment]
This looks pretty reproducible in the Xaml Controls Gallery, which makes me believe that it's a bug in the `NavigationView` itself, and not in the Terminal. The should probably be filed upstream at:

https://github.com/microsoft/microsoft-ui-xaml/issues

Thanks!

**Comment by cl-ement05** [comment]
> This looks pretty reproducible in the Xaml Controls Gallery, which makes me believe that it's a bug in the `NavigationView` itself, and not in the Terminal. The should probably be filed upstream at:
> 
> https://github.com/microsoft/microsoft-ui-xaml/issues
> 
> Thanks!

Oh alright so I should open an issue there ? May I close this one ?

**Comment by zadjii-msft** [comment]
Yes and yes ☺️
