### ISSUE TITLE
Popup about graphics driver issue

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9557]
![image](https://user-images.githubusercontent.com/61856645/111873956-3c3af400-8969-11eb-8958-b5fe3c05a0b3.png)

I almost always leave a WT running at night.  Sometimes I initiate a shutdown of the monitors, sometimes not, in which  case Windows turns them off after half an hour.  Last night I let Windows handle it.  This morning I found the popup pictured above.  I have never seen anything like it before.  Having pressed resume, all seems OK.  Is there anywhere I can look for more info?

Microsoft Windows 10 Pro for Workstations
10.0.19042.867 (2009, 20H2)
WindowsTerminal: 1.7.572.0
Display adapter: Intel UHD Graphics P630
Driver: Intel, Date 2020-10-14, Version 27.20.100.8853 (Microsoft signed)

**Comment by vefatica** [comment]
According to the System event log, the driver was updated overnight.

![image](https://user-images.githubusercontent.com/61856645/111875148-ab671700-896e-11eb-93c1-0dc208b452f2.png)

I don't see that version in Device Manager.  In fact, when I search for an update, DevMgr says the best driver (the version from my previous post) is already installed. [So what's up with the Windows update?]  I'll see what a restart does.

**Comment by DHowett** [comment]
So, when Terminal tries to present a rendered frame using the Direct3D device it might encounter an error. If that error is anything except “the device was not ready and must be recreated,” it will try again _three more times_ with a backoff interval of 150, 300, and 450 milliseconds.

You’ll only see that message when all three retries have failed. Sometimes the graphics driver goes away for longer than Terminal is willing to wait!

All it means is that we are going to stop retrying until you tell us your system is in a safe and stable state.

We used to simply crash in this circumstance ... 😄

**Comment by vefatica** [comment]
Sounds like no big deal.  After a restart, DevMgr still shows 27.20.100.8853 as the driver version.  I have no clue what the WindowsUpdate event was all about.

**Comment by DHowett** [comment]
(I’m glad that that popup is working as intended!)

**Comment by vefatica** [comment]
Regarding the update ... apparently "extension" and "display [driver]" are different things.  I'm not so puzzled now,

![image](https://user-images.githubusercontent.com/61856645/111885162-62c65280-899c-11eb-98d0-d018164b2d45.png)

I wonder what actually happened that caused the interruption.

**Comment by DHowett** [comment]
If you're encountering a new issue, I'd encourage you to file a separate workitem -- it's easier for us to track that way :)

**Comment by vefatica** [comment]
I didn't know if any of it was issue-worthy.  It's no big deal, only some observations.
