### ISSUE TITLE
[Settings] An option to disable colour font emoji

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#956]
Is there any merit to having an option to disable colour font emoji?

So any emoji used will be single colour using the font colour settings?

_Originally posted by @mdtauk in https://github.com/microsoft/terminal/issues/190#issuecomment-495192220_

**Comment by DHowett-MSFT** [comment]
There's some discussion about getting options into the renderer in #817.

**Comment by DHowett** [comment]
From @francogp

> # Environment
> ```
> Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
> Windows Terminal version (if applicable): 1.0.1402.0
> 
> Using WSL Ubuntu LTS version 20.04
> ```
> 
> I'm using this font, but can reproduced with others too: [JetBrainsMono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf?rgh-link-date=2020-06-20T18%3A47%3A05Z)
> 
> # Expected behavior
> image taken by using other windows terminal emulators, like Terminus on windows, and Tilix or Terminator on Ubuntu. All the same results
> ![image](https://user-images.githubusercontent.com/2739706/85209354-94c35f00-b30d-11ea-8d77-e6779d68df98.png)
> 
> # Actual behavior
> ![image](https://user-images.githubusercontent.com/2739706/85209296-1961ad80-b30d-11ea-86d7-4b95fd9bbc5a.png)
> Lots of characters/emoticons have a wrong size at render. This is just an example. Look up the check emoticon ✔
> It seems that its ignoring my font.

I believe DirectWrite _prefers_ a color glyph for this.

I wonder if we should like to add emoji "range" settings for fine-grained control of this. Maybe I want to disable emoji WHITE SMILING FACE only?

**Comment by zadjii-msft** [comment]
Curious if this is a font feature that we added by happenstance back in #10433

**Comment by alexrsagen** [comment]
> Is there any merit to having an option to disable colour font emoji?

Yes! For example, [some CLI libraries](https://github.com/console-rs/dialoguer) may use colored text emojis in order to display a "selected" (green) / "not selected" (gray) state in a multi-select list.

For applications using such CLI approaches to work, it is important to be able to prefer text emoji over colored emoji.
