### ISSUE TITLE
How to open Windows Terminal always with Admin rights?

### ISSUE THREAD

**Issue by LazieWouters** [microsoft/terminal#9560]
How to open Windows Terminal always with Admin rights?

**Comment by 237dmitry** [comment]
I am using [gsudo](https://github.com/gerardog/gsudo/releases) to open elevated tab.
![1](https://user-images.githubusercontent.com/78153320/111882992-b00ce900-89c9-11eb-9cd6-72d31548a62f.png)

**Comment by skyline75489** [comment]
#632 #5000

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+always+admin+is%3Aclosed+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #632 for more discussion.

/dup #632
