### ISSUE TITLE
Unable to find the selected font "Jetbrains Mono". "JetBrains Mono" has been selected instead.

### ISSUE THREAD

**Issue by psidex** [microsoft/terminal#9561]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

Open Windows Terminal

### Expected Behavior

Don't show any error

### Actual Behavior

![Screenshot 2021-03-20 170143](https://user-images.githubusercontent.com/14183909/111878005-f6e4e980-899d-11eb-8434-3434884dc24c.png)

**Comment by DHowett** [comment]
Please make sure you search for duplicates before filing a new issue.

**Comment by psidex** [comment]
@DHowett Could you let me know what this is a duplicate of? I'm aware of #9375 and #8939 and this is not a duplicate of those

**Comment by DHowett** [comment]
This one’s a duplicate of https://github.com/microsoft/terminal/issues/9360 :) (I searched JetBrains!)

**Comment by psidex** [comment]
Perfect, thanks!
