### ISSUE TITLE
About popup fixed size background overlay

### ISSUE THREAD

**Issue by KristofKekesi** [microsoft/terminal#9563]
### Windows Terminal version (or Windows build number)

10.0.19043.867

### Steps to reproduce

Open Windows Terminal, open the new tab dropdown, and click the about button, then resize the window.

### Expected Behavior

Dynamic size for the background overlay.

### Actual Behavior

The background overlay size is static.

## Expected Behavior:
![image](https://user-images.githubusercontent.com/64812024/111884033-2d7f2c00-89bf-11eb-891f-49d39c508e18.png)
## Actual Behavior:
![image](https://user-images.githubusercontent.com/64812024/111883993-f0b33500-89be-11eb-9910-cac57c350604.png)

**Comment by KalleOlaviNiemitalo** [comment]
That's <https://github.com/microsoft/terminal/issues/2380>,  said to be caused by <https://github.com/microsoft/microsoft-ui-xaml/issues/3577>.

**Comment by KristofKekesi** [comment]
@KalleOlaviNiemitalo should I close the issue?

**Comment by DHowett** [comment]
Yes please. Thanks!
