### ISSUE TITLE
Stop closing terminal after a commandline arg program ends

### ISSUE THREAD

**Issue by Ratulhasan14789** [microsoft/terminal#9564]
# Description of the new feature/enhancement

I'm running WT 1.6.10571.0 . I was trying the command line args to open a python program. When i ran this `wt.exe  py D:\Pythons\asd.py` the WT opened with the desired python program as expected. However when the program ended, I was expecting that the terminal will keep on and i can do other stuffs there.
But unfortunately the terminal closed. Tried using with new tab arg, different profiles, different terminal args. Still it produced same result. Anything you can do with this?

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
You can configure the termination behavior with the `closeOnExit` setting. The `never` setting will stop Terminal from exiting, _even when a process has signalled successful completion_.

**Comment by vefatica** [comment]
Will any setting leave OpenConsole.exe running and allow starting a new shell (effectively replacing the old one)? ... as happens, for example, with CMD, running in a console, if you issue

`start /b & exit`

or powershell with

`start -NoNewWindow powershell ; exit`

**Comment by DHowett** [comment]
No, and leaving OpenConsole running wouldn’t be the right way to do that. That’s the ConPTY host, it does not have any process management capabilities anyway.

Terminal is somewhat different from conhost in this regard: it tracks the root process, and terminates the session if that root process exits.

**Comment by vefatica** [comment]
Does conhost actually have process management capabilities?  I (naively) figured it just hung around as long as someone had open handles to its I/O.

**Comment by DHowett** [comment]
Sort-of. If you launch conhost directly from the Run dialog, it will spawn a connected client.
