### ISSUE TITLE
Settings dialog: Not possible to switch radio buttons with the keyboard

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/terminal#9566]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.7.572.0

### Steps to reproduce

1. Open Terminal.
2. Open Settings by pressing CTRL+,.
3. Tab to the radio buttons for the start mode. This is set to "Default" by default, but has options such as "Maximized" etc.
4. Try to switch between the set of five radio buttons using the keyboard, up and down arrows, or left and right arrows.

### Expected Behavior

Focus should switch to the other radio buttons, and the selection/check mark moves with it.

### Actual Behavior

Nothing happens.

Using arrow keys is the standard way to interact with a set of radio buttons.

**Comment by zadjii-msft** [comment]
Huh, that's weird. Those should work, because they definitely work in the XAML Controls Gallery. Thanks!

**Comment by MarcoZehe** [comment]
Yes, I know other XAML-based apps where this works, so it is a problem specific to the way this XAML is marked up. I also reported another issue where the radio buttons aren't associated with a true group element. Perhaps these two are related.

**Comment by zadjii-msft** [comment]
Oh jeez, this is https://github.com/microsoft/microsoft-ui-xaml/issues/3156

**Comment by carlos-zamora** [comment]
@DHowett Here's a thought: should we replace any instance of `RadioButtons` in Windows Terminal with `ComboBox`? `ComboBox` doesn't have this issue.

**Comment by DHowett** [comment]
I don't hate that. We still can't provide a tooltip for each entry ... but maybe we could display some tiny subtitle text underneath it explaining what happens (like this:)

![image](https://user-images.githubusercontent.com/189190/112221610-a5cf3280-8bf5-11eb-8127-64df6f50e2aa.png)
