### ISSUE TITLE
duplicateTab says "This makes a copy of the current tab and opens it." but what is copied ?

### ISSUE THREAD

**Issue by Pasb4js** [microsoft/terminal#9577]
Here:
[https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions)
I read

```
**Duplicate tab**
This makes a copy of the current tab and opens it.
```

but what is copied ?  What is the difference with a "New tab" ?
I mean: not what was printed previously in cmd.exe for example.

And, for cmd.exe, modified/added ENV VARIABLES are not "copied" =)

**Comment by skyline75489** [comment]
Boy where do I start. First with "new tab", the profile used will always be the default profile. With "duplicate tab", the profile used to create the tab will be the same as the current tab (the "source" of the duplication). Second, you can also duplicate the current working directory in the tab. See #3158 for instructions. And finally, the environment variables not being copied is a known issue. See #1125.

**Comment by zadjii-msft** [comment]
You know, this is a good docs bug, so I'm moving it over to https://github.com/MicrosoftDocs/terminal/issues/292.

As skyline75489  mentioned, the profile and working directory are duplicated, but not the underlying processes (because that would be impossible)
