### ISSUE TITLE
"experimental.retroTerminalEffect" with bad readability on bulked letters.

### ISSUE THREAD

**Issue by JianyueZ** [microsoft/terminal#9578]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

When listing files in a linux command-line by "$ ls", some of the file (or directory) names may display in bulk. These letters is not very much readable.

### Expected Behavior

Hope they can be more readable if the letters displayed in bulks.

### Actual Behavior

Not readable as the letter is not well distinguished from the bulk.

With customised fontface and colorscheme
![image](https://user-images.githubusercontent.com/49962826/111977511-c6d44c80-8b3d-11eb-8fb5-343d55a2287b.png)

With default fontface and colorscheme
![image](https://user-images.githubusercontent.com/49962826/111977782-1a469a80-8b3e-11eb-91ed-b393c4376e43.png)

**Comment by zadjii-msft** [comment]
Yea, that's just kinda how it works. It is an `experimental` feature after all 😉 

You might try changing your [LS_COLORS](https://man7.org/linux/man-pages/man5/dir_colors.5.html) so directories don't have backgrounds set, or maybe try [forking the retro shader itself](https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Retro.hlsl) and come up with something less egregious when used with background colors.
