### ISSUE TITLE
Terminal crashes when trying to run it as administrator from a non administrator windows user

### ISSUE THREAD

**Issue by Mavv3006** [microsoft/terminal#9584]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19042.868], Windows Terminal [Version 1.6.10571.0]

### Steps to reproduce

1. have a windows user with admin rights and a windows user without admin rights
2. log in to the user without admin rights
3. try to run the new windows terminal as an administrator
4. when the promt to give the admin password: do that
5. the app crashes

### Expected Behavior

I expect to open the windows terminal in administrator mode

### Actual Behavior

The windows terminal crashed with the below error message.

Error message:
![image](https://user-images.githubusercontent.com/52504463/112119485-b499f300-8bbd-11eb-9e5a-0c2d1181c08b.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! This currently isn't possible for applications installed from the Store. If you want to run the Terminal as an administrator, then you'll need the account the Terminal is installed for to also be an admin.

This is actually already being tracked by another issue on our repo - please refer to #4217 for more discussion.

/dup #4217
