### ISSUE TITLE
First shown output line in window is ommitted after next command

### ISSUE THREAD

**Issue by ribeach** [microsoft/terminal#9588]
### Windows Terminal version (or Windows build number)

10.0.19042.0, 1.4.3243.0

### Steps to reproduce

- Create text file with multiple lines (e.g. 01-10)
- Resize Terminal window to not show all line (e.g. only show 02-10)
- Output content of file (Get-Content or cat)
- execute another command that will output multiple lines
- Scrolling up Terminal will now omit the "02" line

### Expected Behavior
```powershell
PS C:\> Write-Host "only 02-09 visible in window:"
only 02-09 visible in window:
PS C:\> Get-Content test.txt
01
02 <<<< This output is missing in "actual behaviour"
03
04
05
06
07
08
09
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
PS C:\> Write-Host "Resizing Window. Now all numbers are visible in window:"
Resizing Window. Now all numbers are visible in window:
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
```
### Actual Behavior
```powershell
PS C:\> Write-Host "only 02-09 visible in window:"
only 02-09 visible in window:
PS C:\> Get-Content test.txt
01
03
04
05
06
07
08
09
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
PS C:\> Write-Host "Resizing Window. Now all numbers are visible in window:"
Resizing Window. Now all numbers are visible in window:
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
PS C:\> Get-Content test.txt
01
02
03
04
05
06
07
08
09
```
Windows Size:
![image](https://user-images.githubusercontent.com/12139878/112169615-a4e8d180-8bf2-11eb-9dcb-2878336f4cbb.png)

**Comment by DHowett** [comment]
I believe this is the same as /dup https://github.com/PowerShell/PSReadLine/issues/724

The old version of PSReadline that came with Windows PowerShell uses a "hard scroll" operation when the prompt is displayed. This "hard scroll" deletes the content that was scrolled off the screen.
