### ISSUE TITLE
Starting 'vi' (cli version of 'vim') renders tildes all over screen and content not visible until resize of terminal

### ISSUE THREAD

**Issue by davidmpatterson** [microsoft/terminal#9591]
After installing terminal onto Windows 10, then running 'vi' (the cli version of 'vim') to edit a file, I get a number of tildes onscreen and content in the text file is lost until the terminal is resized. Not sure why this occurs, as  no other terminal seems to do this.

**Comment by zadjii-msft** [comment]
Which version of the Terminal, of the OS, of vim, are you using any vim plugins, are you using WSL... etc. There's a great [bug template](https://github.com/microsoft/terminal/issues/new?assignees=&labels=&template=Bug_Report.yml&title=) that you seem to have ignored entirely here.
