### ISSUE TITLE
curl executable in cmd.exe terminal does not display download interface correctly.

### ISSUE THREAD

**Issue by hello-smile6** [microsoft/terminal#9593]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Other Software

The curl executable for Windows (built-in)

### Steps to reproduce

Download a large file using curl with the smallest window size possible.

### Expected Behavior

A normal download.

### Actual Behavior

The download numbers were skewed.

![image](https://user-images.githubusercontent.com/73048226/112198952-e4032c80-8bca-11eb-8200-029723c05e65.png)

**Comment by DHowett** [comment]
It is because the window is not wide enough to display the download status. This is just how curl works.

**Comment by hello-smile6** [comment]
@DHowett Could the command line spam be fixed, though?

**Comment by DHowett** [comment]
No. It is a _direct_ result of curl not having enough space to print the status bar.

The way curl prints the status bar is by sending the cursor to the beginning of the line and printing a long line of text.

When the line wraps, the first step ("go to beginning of line") gets the _beginning of the wrapped portion of the line_.

It then just... does that over and over again.

This is how it was implemented by curl the open-source project. It is not special for the Windows version of curl.

**Comment by DHowett** [comment]
If you want to suppress the spam, use `curl -s` (or `--silent`)
