### ISSUE TITLE
Fonts in font face dropdown are not alphabetized

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#9594]
### Windows Terminal version (or Windows build number)

1.8.771.0

### Steps to reproduce

Open the settings UI
Navigate to the appearance section for a profile
Click on the dropdown for font face

Also have a variety of fonts installed(?)

### Expected Behavior

Fonts are listed in alphabetical order by their name

### Actual Behavior

Fonts appear to be in a somewhat random order

<img width="868" alt="font-face-screenshot" src="https://user-images.githubusercontent.com/48369326/112214690-ba530100-8bdc-11eb-8996-4ffc5307ccef.png">

**Comment by carlos-zamora** [comment]
This is actually a really easy fix.

https://github.com/microsoft/terminal/blob/da24f7d9390a71648a81f17fc1eefc6e2d27bcbf/src/cascadia/TerminalSettingsEditor/Profiles.cpp#L155-L160

We're already "sorting" the fonts, but at one point, I switched from storing a list of `hstring`s to a list of `Font`s. It's just a matter of adding some kind of comparator to that `sort` call.

**Comment by smholvoet** [comment]
Was digging through issues trying to find  a "font autocomplete" issue, and wound up here 🤷‍♂️

I notice @cinnamon-msft's screenshot has a dropdown containing all the font faces, whilst mine looks like this:

![image](https://user-images.githubusercontent.com/13507392/112984253-f4814d00-915e-11eb-8780-e37c0ad87cf1.png)

I'm obviously still able to manually enter a font face, but autofill makes way more sense.

I'm running the latest preview version (1.7.572.0), so I'm guessing this feature will be contained in one of the future releases (1.8.771.0)... or is this a genuine 🐛 bug?

**Comment by zadjii-msft** [comment]
@smholvoet The font face input was only changed to a ComboBox in #9275, which hasn't shipped to _any_ official builds yet
