### ISSUE TITLE
Opening a new-tab after a split-pane causes two tab bars being highlighted

### ISSUE THREAD

**Issue by furente** [microsoft/terminal#9595]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.6.10571.0

### Steps to reproduce

Run the following command:
wt ; split-pane -H ; new-tab

OR, for a better visual understanding:
wt --title wrong-tab --tabColor "#ff0000" ; split-pane -H --title wrong-tab --tabColor "#ff0000" ; new-tab --title correct-tab --tabColor "#04ff00"

### Expected Behavior

Only one tab bar highlighted. The one from the last command.

### Actual Behavior

Two tab bars highlighted.

After switching between tabs or hovering the wrong highlighted tab bar, it fix itself.

![bug-tabBarHighlighted-wt-1 6](https://user-images.githubusercontent.com/23699968/112216485-d75df300-8c21-11eb-9796-c1c49ececfdf.gif)

**Comment by zadjii-msft** [comment]
Man those are some great repro steps. Thanks!

I'm guessing this is related to whatever's causing #8948. That's what we get for hot-swapping XAML resources like this 😝

**Comment by zadjii-msft** [comment]
Hey guess what, I think this is just going to be fixed by magic by #11720
