### ISSUE TITLE
Tab remains open even on process exit

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#9596]
### Windows Terminal version (or Windows build number)

10.0.19042.870 1.7.572.0

### Steps to reproduce

This doesn't happen _each_ time, but it does happen often enough to be annoying - leading me to file this issue.

Shell is mostly irrelevant - I use a variety of them - CMD, Powershell, Powershell Core, Msys Bash, Msys Zsh, WSL1/2, SSH sessions etc.

Open a shell. Do some work. Exit it with `Ctrl+D`. (This is a fairly preferred way of closing a shell without typing 'exit' or reaching for the mouse to close the tab)

### Expected Behavior

The tab to get closed.

### Actual Behavior

This happens instead (screenshot below):

The tab remains open.

![image](https://user-images.githubusercontent.com/46838874/112283017-b17e3000-8cad-11eb-94f3-cd613adea40f.png)

**Comment by skyline75489** [comment]
When the return code of the process is 1 instead of 0, this is expected.

You can find out more in the documentation about closeOnExit.

See also #4223, #5003.

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22process+exited+with+code%22) when filing new issues. Like skyline75489 mentioned, this is by-design for the [`closeOnExit`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior) setting.

**Comment by rashil2000** [comment]
Thanks for the link @zadjii-msft! 

The reason I filed a new issue was because of a possible resolution I had in mind - namely - having a keybind that closes a tab. I searched _for that_ and couldn't find anything in the issues, hence a new one. Would you mind reopening this if such a feature doesn't exist?

**Comment by zadjii-msft** [comment]
[`closePane`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-pane) will close the tab if there's only one pane in the tab. That's why it's the action bound to <kbd>ctrl+shift+w</kbd> by default.

There's also a [`closeTab`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-tab) action, which will close the tab even when multiple panes are open.

**Comment by rashil2000** [comment]
Okay, thanks for the help!
