### ISSUE TITLE
Let us launch Terminal by typing "Terminal" in the File explorer address bar

### ISSUE THREAD

**Issue by Cortana-117** [microsoft/terminal#9598]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/72892766/112310532-54d94000-8cc2-11eb-9e09-53889d4501c8.png)

I want to be able to type "Terminal" in the address bar of file explorer in Windows and open it like I open CMD.

**Comment by zadjii-msft** [comment]
Man that would be so handy - what if it was even shorter than "Terminal"? What if it was something like, [`wt`](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments)?

note: you'll probably want `wt -d .` to open in the current directory

**Comment by Cortana-117** [comment]
Hi @zadjii-msft , thanks but when I type "wt -d" I get this error:

![image](https://user-images.githubusercontent.com/72892766/112369059-6a1d9100-8cf9-11eb-9047-daa0d9fd1ee9.png)

**Comment by zadjii-msft** [comment]
> you'll probably want `wt -d .`

the `.` is important 😉

**Comment by Cortana-117** [comment]
oops, Thank you! 😀

**Comment by Cortana-117** [comment]
> > you'll probably want `wt -d .`
> 
> the `.` is important 😉

Thank you, i totally didn't notice it!

is it possible to run it as admin too? like with an additional argument or from inside the Terminal UI after launching it with that command?
i tried `wt -d . runas /admin` but didn't work.

Thanks again!

**Comment by zadjii-msft** [comment]
> is it possible to run it as admin too? like with an additional argument or from inside the Terminal UI after launching it with that command?
> i tried `wt -d . runas /admin` but didn't work.

Not currently, but there's other threads on the repo tracking that, as well as a open spec proposal and an open PR that implements something similar. You can go subscribe to those threads if you'd like to be updated when that feature's ready ☺️

**Comment by Cortana-117** [comment]
Sounds good, will do, ty!
