### ISSUE TITLE
How to install Terminal offline

### ISSUE THREAD

**Issue by Austzhu** [microsoft/terminal#9599]
How to install Terminal offline, My computer can't access the Internet.
I can't run after downloading and installing from this address (https://github.com/microsoft/terminal/releases/download/v1.7.572.0/Microsoft.WindowsTerminalPreview_1.7.572.0_8wekyb3d8bbwe.msixbundle)

**Comment by zadjii-msft** [comment]
There's actually [a bunch of threads](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22install+offline%22) that have covered this previously. Please make sure to search before filing new issues. Most notable of the pre-existing threads is #6010. Please check that thread to see if it helps answer any questions.

/dup #6010
