### ISSUE TITLE
Keyboard Shortcut to clear terminal

### ISSUE THREAD

**Issue by trustedmercury** [microsoft/terminal#9603]
# Description of the new feature/enhancement

I clear my terminal after almost every command as I prefer keeping things clean, without having to scroll up; I think quite a few other people use the ``clear`` command a lot too. Always typing in clear or cls is a hassle.

# Proposed technical implementation details (optional)

Add a keyboard shortcut that automatically clears the open terminal using ``cls`` or ``clear``. I was wondering if it was possible to have a built-in keyboard shortcut that automatically clears the terminal, something that is easy to access but not already used by another function.

**Comment by 237dmitry** [comment]
A good idea. But do not remove scroll-up `Ctrl+L`

**Comment by clvrk** [comment]
You damn near read my mind.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! #1802 has a lot more details on why this is currently hard to do. 

You might be able to get away with 

```json
        { "command": { "action": "sendInput", "input": "clear\r" }, "keys":"ctrl+k", "name": "clear terminal" },
```

which will manually send "clear<kbd>enter</kbd>" to the terminal. Adjust as needed for your preferred shell. 

/dup #1882
