### ISSUE TITLE
Understanding wt.exe version that is being used

### ISSUE THREAD

**Issue by FallenHoot** [microsoft/terminal#9606]
Currently, when you look up the version within PowerShell it provides a System.Windows.MessageBox

![image](https://user-images.githubusercontent.com/19664186/112385390-db584680-8cef-11eb-9d57-d1d74ae4ce85.png)

Reproduce with: `wt --version`

I am looking for something like this:
`$PSVersionTable.PSVersion`
or
`cmd --version`

I want to verify if WT or WT Preview is installed. I also want to know what release version of WT or WT Preview is being used without the MessageBox.

**Comment by zadjii-msft** [comment]
Yep, this is exactly by design (currently). You'll want to see #7258 for a longer discussion on the subject.

/dup #7258
