### ISSUE TITLE
awscli cloudwatch logs tail ANSI color codes not being interpreted

### ISSUE THREAD

**Issue by costincaraivan** [microsoft/terminal#9607]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.6.10571.0

### Other Software

aws --version
aws-cli/2.1.19 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

Cygwin
zsh

### Steps to reproduce

1. aws logs tail /aws/lambda/my-log-group

### Expected Behavior

2.  `2021-03-24T21:23:41.766000+00:00 2021/03/24/[$LATEST]` + colors should be visible in the console.

### Actual Behavior

2. `←[32m2021-03-24T21:25:48.784000+00:00←[0m ←[36m2021/03/24/[$LATEST]` all over the place

For some reason Windows Terminal is not interpreting the ANSI escape codes, see the "Actual behavior".

**Comment by DHowett** [comment]
It seems like python is disabling `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. The application has explicitly told us to ignore color codes.

/dup https://bugs.python.org/issue29059
/dup https://mail.python.org/pipermail/python-ideas/2016-December/044033.html

Python devs rejected doing this in 2016.

**Comment by trajano** [comment]
AWS CLI is fixed now.  It processes codes with no issues.
