### ISSUE TITLE
Sync settings across devices

### ISSUE THREAD

**Issue by BenyErnest** [microsoft/terminal#9609]
# Description of the new feature/enhancement
It would be nice to have a feature to synchronize my terminal configuration across devices.
Some time I reinstall my PC or change this one and I have to reconfigure from start the 
Windows Terminal, so it would be nice to have a feature like VS Code does, that allow me to signing 
and load my settings. Greets.

**Comment by skyline75489** [comment]
Yeah that would be nice. You may found #1770 helpful.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #2933 for more discussion.

/dup #2933
