### ISSUE TITLE
Indicate tabs that received any output in it console

### ISSUE THREAD

**Issue by iuricarraro** [microsoft/terminal#9611]
# Description of the new feature/enhancement
When you have many tabs it is would be interesting to signal when a tab is outputting data and which tab doing this.

The idea is show a little bubble in the right corner of the tab to indicate this.

In many job we uses many tabs to watch logs in real time.
```
Get-Content -Path .\test.log -Wait | Select-String -Pattern 'ERROR' 
```
It is used for many different parallel environments, and this signal will be usefully to monitor efficiently this tabs.

# Proposed technical implementation details (optional)

When a tab, without focus, receives some output data, a ball/bubble of some color should appear indicating that there has been an update on that console.
Just like second image.

![1](https://user-images.githubusercontent.com/4460055/112417735-f2eef980-8d06-11eb-9118-118ae1fdd478.png)
![2](https://user-images.githubusercontent.com/4460055/112417736-f3879000-8d06-11eb-982a-136fa9a46e3d.png)

**Comment by skyline75489** [comment]
I think #7955 covers this?

**Comment by zadjii-msft** [comment]
Yep, sure does!

/dup #7955
