### ISSUE TITLE
Drag in focus mode

### ISSUE THREAD

**Issue by richeney** [microsoft/terminal#9615]
# Description of the new feature/enhancement

Configure window padding border as a draggable zone when in focus mode.

# Detail

It would save a user having to exit focus mode to move a terminal with the mouse. I'm constantly grabbing the window in that area and highlighting text rather than moving it! 

I understand that the `Win`+`Cursor` and `Win`+`Shift`+`Cursor` exist, but they won't easily reposition a terminal on my 40" 5k2k monitor with Fancyzones installed! #firstworldproblems

**Comment by zadjii-msft** [comment]
I coulda swore we had an issue open for this already. Not necessarily adding a margin, pre se, but something like holding a key that would let you drag the window while the key was held. 

Part of the trick with this is the way the XAML Island eats input events before the root HWND can get to them, which might prevent anything inside the client area from manipulating the window position.

FYI my usual workflow for this is <kbd>Alt+Space</kbd>, <kbd>m</kbd>, <kbd>any arrow key</kbd>, then move the window with the mouse to the desired location.

**Comment by zadjii-msft** [comment]
Ho boy it was far down the backlog: /dup #539
