### ISSUE TITLE
Need configurable (or unlimited) buffer size

### ISSUE THREAD

**Issue by adamh128** [microsoft/terminal#9616]
Many command line tools I use for development output a lot of lines to stdout, having a fixed sized buffer means I can't scroll back to see the entire output.  Many modern terminals support configurable or unlimited buffer sizes (even cmd.exe was configurable!).

**Comment by DHowett** [comment]
Something tells me that one of our other 9615 issues covers this. 😄

**Comment by WSLUser** [comment]
Dupe https://github.com/microsoft/terminal/issues/1410

**Comment by DHowett** [comment]
Found it! /dup #1410

**Comment by DHowett** [comment]
Thanks @wsluser, you beat me to it
