### ISSUE TITLE
Terminal suddenly replaces all characters by gibberish if a process produces huge amount of text output

### ISSUE THREAD

**Issue by phip1611** [microsoft/terminal#9620]
### Windows Terminal version (or Windows build number)

1.6.10571.0, 10.0.18363.0

### Other Software

Apache Maven 3.6.3
Oh-My-Posh V3

### Steps to reproduce

I'm working on a machine that uses german as language.
It happens when I trigger a big maven build which produces thousands of lines. It is reproducible, i.e. also after restarts or in new tabs.

### Expected Behavior

Show original text output.

### Actual Behavior

During the build it suddenly switches to the gibberish as shown in the appended screenshot.

I'm confident this worked in earlier versions.

![windows-terminal-gibberish-bug](https://user-images.githubusercontent.com/5737016/112546980-73226700-8dba-11eb-8d24-1d115439bd05.png)

All new lines also only show gibberish including characters I type. A "clear" also doesn't solve the problem. To solve, I have to open a new tab or window.
![windows-terminal-gibberish-bug-2](https://user-images.githubusercontent.com/5737016/112547256-d14f4a00-8dba-11eb-9c1d-b5866f6586bd.png)

**Comment by DHowett** [comment]
Ah yes, it's going to be very important to figure out who is requesting that!

More info here- https://github.com/microsoft/terminal/issues/8554#issuecomment-743027484

/dup #8554

You can probably recover from this by printing... (powershell)

```
"`u{000f}"`

**Comment by DHowett** [comment]
That should have been u{000e}, actually!

![image](https://user-images.githubusercontent.com/189190/112548155-c7612300-8d89-11eb-90ac-dabd3394183b.png)
