### ISSUE TITLE
"Open Windows Terminal Here" in the context menu is missing

### ISSUE THREAD

**Issue by lululus** [microsoft/terminal#9626]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

i am using windows 10 home 20h2

### Steps to reproduce

Install Windows Terminal.
I tried to install windows terminal via `released package in github`, via `Microsoft Store`, via `scoop`, but they all lead to the same result.
I also tried to install the most recent pre-release version on my another computer, but that does not work either

### Expected Behavior

Show the "Open Windows Terminal Here" at the same place of "Open Powershell Window Here".

### Actual Behavior

I notice that v1.6.10272.0 has released the "open windows terminal here" shell extension. but i cann't find that in my context menu anywhere. The "Open Powershell Window Here" works perfectly.

**Comment by skyline75489** [comment]
The "Open in Windows Terminal" entry in the context menu will only show when you right click the *blank* space in the File Explorer. Can you confirm if this works?

**Comment by lululus** [comment]
> The "Open in Windows Terminal" entry in the context menu will only show when you right click the _blank_ space in the File Explorer. Can you confirm if this works?

I tried  both "shift + right-click" and "right-click" in my desktop and file explorer, the "open windows terminal here" is missing.

below is "right-click" in the file explorer
![image](https://user-images.githubusercontent.com/30972308/112598663-ddceb380-8e49-11eb-83e5-d038df01e542.png)

below is "shift + right-click" in the file explorer
![image](https://user-images.githubusercontent.com/30972308/112598759-05258080-8e4a-11eb-85f4-850f8f5373db.png)

below is "right-click" in the desktop
![image](https://user-images.githubusercontent.com/30972308/112598837-1c646e00-8e4a-11eb-958b-6ca3e500ec9a.png)

below is "shift + right-click" in the desktop (FYI, i disabled the git gui in this one, normally git gui context menu would show up here)
![image](https://user-images.githubusercontent.com/30972308/112598913-31d99800-8e4a-11eb-8df0-45fd427d09fb.png)

**Comment by Disembleergon** [comment]
for me, it works, even when I right click a folder

**Comment by lululus** [comment]
> for me, it works, even when I right click a folder

yeah, i find it weird, the "Open PowerShell window here" works just fine, the windows terminal shouldn't be like this😥

**Comment by Disembleergon** [comment]
take a look [here](https://github.com/microsoft/terminal/issues/1060) or [here](https://stackoverflow.com/questions/61403081/how-to-add-windows-terminal-to-context-menu) .
Maybe try with [this small script](https://github.com/lextm/windowsterminal-shell)

I hope this helps!!!

**Comment by lululus** [comment]
> take a look [here](https://github.com/microsoft/terminal/issues/1060) or [here](https://stackoverflow.com/questions/61403081/how-to-add-windows-terminal-to-context-menu) .
> Maybe try with [this small program](https://github.com/lextm/windowsterminal-shell)
> 
> I hope this helps!!!

These links would definitely work, but......, actully i have waited for a few months, trying to get the official support for this function 
 on my computer by reinstalling windows terminal once in a while.😂

And you can see that I installed wsl2 on my computer, which has successfully added a "Open Linux Shell here" entry to my context menu.

Now I just wanna know why this context menu doesn't show up on my computer by default.

I'll try with the links if i failed to find the reason, thanks a lot!!!😁

**Comment by zadjii-msft** [comment]
Also FYI, you might need to reboot after installing the version of the Terminal that includes #6100. `explorer.exe` caches the results of context menu entries, so the Terminal won't show up when it's first updated to v1.1+

**Comment by lululus** [comment]
> Also FYI, you might need to reboot after installing the version of the Terminal that includes #6100. `explorer.exe` caches the results of context menu entries, so the Terminal won't show up when it's first updated to v1.1+

ohhhh, it is the explorer cache problem! i replaced the install source to `scoop` every time before rebooting.

so, `scoop install windows-terminal` didn't get me the context menu...

thx a lot!

**Comment by DHowett** [comment]
Sorry, this may be a scoop problem. Scoop is installing Terminal _manually_ (!!!!!) which it should NOT HAVE DONE. When it installs Terminal manually, it is missing the entire shell extension.
