### ISSUE TITLE
publish an .exe

### ISSUE THREAD

**Issue by teknopaul** [microsoft/terminal#9627]
# Description of the new feature/enhancement

Provide an .exe installer or just a precompiled binary as output to CI process, I cant install from windows store and the downloads do not contain an installer.

# Proposed technical implementation details (optional)

How about NSIS? by the folks at winamp.

**Comment by lululus** [comment]
how about install it via [scoop](https://github.com/lukesampson/scoop)? this is a cl installer for windows, `scoop install windows-terminal` would do all the work.

**Comment by zadjii-msft** [comment]
There's an `msixbundle` on our [Releases](https://github.com/microsoft/terminal/releases), which is an installer. Does that work for you? You could also try `winget` or `chocolatey` (though, the `scoop` and `choco` installs are maintained by third parties. )

**Comment by DHowett** [comment]
All of these are valid installation methods. The `msixbundle` _IS_ an installation package.

**Comment by teknopaul** [comment]
Corporate build of windows 10 did not recognize that extension.
