### ISSUE TITLE
Support Proper Word Wrapping ; can't read

### ISSUE THREAD

**Issue by ecovio1** [microsoft/terminal#9631]
### Windows Terminal version (or Windows build number)

Windows build number: [Version 10.0.19042.870]    Windows Terminal version : Preview 1.7.572.0

### Other Software

Powershell 7.1.3

### Steps to reproduce

see the screenshot below

### Expected Behavior

Proper word wrapping, can't even read. windows powershell 5.1 is even worse

### Actual Behavior

word wrapping is broken , don't know if it is related to #8000 or not.

![Screenshot 2021-03-27 001309](https://user-images.githubusercontent.com/74822870/112677721-4a6ea000-8e94-11eb-9df2-8c7a35e7d148.jpg)

**Comment by DHowett** [comment]
Unfortunately, this is going to be a common issue among _all_ character cell based terminals. There is no such thing as _word_ wrapping when the application is sending us data character-by-character.


Wrapping at the appropriate point, in this case, is something that needs to be done per application.

**Comment by ecovio1** [comment]
@DHowett so are you saying this needs to be fixed in powershell itself?

**Comment by DHowett** [comment]
So, this is something that would need to be fixed in `wmic`. PowerShell's WMI object representation should already do word-based wrapping (since it uses "Format-Table")
