### ISSUE TITLE
Arrow navigation dismisses tab renamer

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#9632]
### Windows Terminal version (or Windows build number)

Dev - latest

### Steps to reproduce

With 1 open tab,  open tab renamer
Go to the end of the title
Click Right.
The renamer is dissmissed

With 2 tabs, open tab renamer in the second tab
Go to beginning of the title
Press Left
The renamer is dismissed

Same applies to Up and Down

### Expected Behavior

The renamer shouldn't be dismissed if by mistake the user clicks extra arrow.

### Actual Behavior

The renamer is dismissed.

Reported initially by @KalleOlaviNiemitalo in https://github.com/microsoft/terminal/issues/9520.

The root-cause is that if witin renamer we hit Left but the cursor cannot move as it is already in the beginning, the KeyDown event propagates to the parent control. This way it bubbles up, until it reaches the TabView that handles this key as a navigation between tabs.

**Comment by Don-Vito** [comment]
I guess I know how to fix this.

**Comment by KalleOlaviNiemitalo** [comment]
I don't think the keypress navigated between tabs, though. The tab that I was renaming remained selected.

**Comment by Don-Vito** [comment]
> I don't think the keypress navigated between tabs, though. The tab that I was renaming remained selected.

This is probably because you had one tab. In this case, focus moves to the + button, and then auto resets to the terminal.

In any case the problem is that text box doesn't handle an arrow if the cursor cannot move, and leaves it to the parent. It is a feature. But in our case it is dangerous as it commits the tab name.

**Comment by KalleOlaviNiemitalo** [comment]
I tried it again on Windows Terminal Preview 1.7.572.0. I have three tabs open. I double-click the title of the second tab to start renaming it, then press the Left arrow key twice. Approximately half of the time, a black focus rectangle briefly flashes around the tab header of the first tab. Very soon after that, the session in the second tab gets the focus again.

**Comment by Don-Vito** [comment]
@KalleOlaviNiemitalo  - what you describe sounds like some race between TabRenamerDeactivated and  _OnTabSelectionChanged  handler in the TerminalPage. I think it probably should be a separate issue. Though preventing the arrows from switching focus render it no reproducible :smile:
