### ISSUE TITLE
SIGQUIT is sent to terminal when switching to non-existent tab

### ISSUE THREAD

**Issue by Christilut** [microsoft/terminal#9635]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

Ubuntu 18.04.3 LTS

GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Steps to reproduce

I use tabs in Windows Terminal by using CTRL+number (eg CTRL+3 goes to tab 3).
When there is a running command in bash (eg `sleep 10` for demo purposes) and I switch to a tab that does not exist (eg CTRL+4 when there are 3 open tabs), the process is exited with a SIGQUIT signal.

### Expected Behavior

Nothing should happen when pressing the hotkey to go to a tab that does not exist

### Actual Behavior

```
chris@pc:~/workspace$ sleep 10
^\Quit
```

Process is terminated when pressing CTRL+4

**Comment by DHowett** [comment]
So, this is an interesting case! We implemented this on purpose for a bunch of different key bindings. When they don't _act_, they pass the input through. The one we really, really wanted to get right for Windows users was <kbd>Ctrl+C</kbd>. Copy if there's a selection (and they've bound it to copy), send a literal ETX if not.

We can probably adjust the "switch to tab" key bindings to mark the binding as handled even if there's no tab at that index.
