### ISSUE TITLE
Set current directory when launched from windows explorer address bar.

### ISSUE THREAD

**Issue by Giorgi** [microsoft/terminal#9639]
# Description of the new feature/enhancement

When terminal is launched by typing wt in the Windows Explorer address bar the current directory is set to %HOMEPATH% instead of the directory that it was launched from. If you do the same by typing cmd it will launch cmd with the current directory set correctly.

CMD:

![image](https://user-images.githubusercontent.com/580749/112734653-8a9b5480-8f60-11eb-9555-3f3a138eedff.png)

WT:

![image](https://user-images.githubusercontent.com/580749/112734659-9e46bb00-8f60-11eb-9a67-f91a69be45ab.png)

**Comment by Giorgi** [comment]
Works for PowerShell too:

![image](https://user-images.githubusercontent.com/580749/112734882-e2868b00-8f61-11eb-8121-a3812df4c8bb.png)

**Comment by j4james** [comment]
The recommended way to make this work is by entering `wt -d .` in the explorer bar. For more info see #878 (comment).
