### ISSUE TITLE
Bug Report, settings not showing

### ISSUE THREAD

**Issue by ws0h3ll** [microsoft/terminal#964]
# Environment

```none
Windows build number: 1903
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

load up windows terminal (dev build) after clean install
# Expected behavior

I'm expecting to see a settings drop down where i can select to use, powershell, windows etc.
# Actual behavior

When i open the console i can only see powershell (see attatched)
![here](https://user-images.githubusercontent.com/45339471/58283592-8fa97e80-7da0-11e9-9b74-8a85bd5013b8.png)

**Comment by Summon528** [comment]
Do you try pressing Ctrl + t ?

**Comment by zadjii-msft** [comment]
Please read the [README](https://github.com/microsoft/terminal#i-built-and-ran-the-new-terminal-but-it-looks-just-like-the-old-console-what-gives) before filing new issues.
