### ISSUE TITLE
[Question]Is support for GUI-less systems (server core) planned?

### ISSUE THREAD

**Issue by AndrewSav** [microsoft/terminal#9640]
# Description of the new feature/enhancement

Let me start with saying that I saw all these prior issue, and then mine is different: https://github.com/microsoft/terminal/issues/7560 https://github.com/microsoft/terminal/issues/2177 https://github.com/microsoft/terminal/issues/6717 https://github.com/microsoft/terminal/issues/6956 https://github.com/microsoft/terminal/issues/1643

The difference is that most of those issues ask about Windows 2019 server which is not on or past 1903, where Windows _Core_ Server is, which is the key.

Windows Server Core, by the nature of not having GUI needs a comfortable terminal the most. Arguably on a GUI system, there may be other than command line ways to achieve one's goals, on a server core there are not. It has to be done in a terminal. And the terminal does not seem to be able to run on those systems.

So the question is: can it be supported on the windows server _core_ systems that have at least 1903?

**Comment by floh96** [comment]
Instead of trying to run the terminal on the Server directly I think it would be the better approach if you run the terminal on your local machine and connect to the server via SSH/winrm.

**Comment by miniksa** [comment]
No. This is not planned. The Windows Terminal is a graphical application that requires much of the desktop experience unavailable on core. Server Core will continue to have the classic console host window (that DOES receive updates from this repository).

For the most part though, you're not supposed to administrate from the local machine for server core. The point of Server Core isn't a comfortable local CUI experience; the point is minimal attackable surface. It is supposed to be administrated remotely with the local session as a last-chance recovery environment. 

As such, the previous poster is correct. It is expected you use another machine as your terminal and remote to your server core machine.
