### ISSUE TITLE
Windows Terminal prevents search dialog from closing automatically when searching for folders

### ISSUE THREAD

**Issue by renard11** [microsoft/terminal#9642]
Hello!
I've never written a bug report before, so I don't really know how to do this...

For about a year I'm having an issue with Windows that drives me crazy. Not only me, also a few colleagues of mine and my brother (so I'm not an isolated incident). Whenever I press the Windows-Key and search for a folder, or press Windows-Key+S and search, or click on the search icon and conduct a search, after finding the folder and pressing "Enter", Windows Explorer opens that folder, but the search dialog does not close automatically as it is supposed to do. It stays open, and Windows Explorer opens in the background, and the symbol in the taskbar starts blinking because it's blocked by the search dialog. This is highly annoying, because you always have to manually look for the opened folder in the taskbar. The same happens if you pin a folder to the start menu. If you click on it, explorer opens in the background, and the start menu does not close automatically and blocks everything. This is even more annoying if you have set your start menu to open in full screen, and you always have to press Esc! I have written my Masters Thesis while both of my Laptops (a Surface Pro 7 and an Acer Aspire) drove me mad when I had to open folders! This only happens for folders, files and apps open as they should. I contacted Microsoft several times because of this, but I was always told to reinstall Windows by downloading an ISO.
Now I asked a couple of my friends and colleagues if they had this problem because I couldn't work like this any longer, and some of them did. And by pure chance we figured out that all of us who had this problem had Windows Terminal installed. We uninstalled it, and now everything works smoothly (at least as smooth as Windows can be)! Now I also found a thread on answers.microsoft.com where other people are having the same issue (since July 2020)! Please fix that!!

[https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_menu/start-menu-not-closing-after-opening-anything-from/eaae4553-a746-47f8-ae6a-acd62bbf6187?page=1](https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_menu/start-menu-not-closing-after-opening-anything-from/eaae4553-a746-47f8-ae6a-acd62bbf6187?page=1)

[https://answers.microsoft.com/en-us/windows/forum/all/windows-search-doesnt-close-after-opening-a-folder/6d9be224-0f02-4ab8-a2f8-24ad6a8c26aa](https://answers.microsoft.com/en-us/windows/forum/all/windows-search-doesnt-close-after-opening-a-folder/6d9be224-0f02-4ab8-a2f8-24ad6a8c26aa)

**Comment by DHowett** [comment]
Thanks for filing this, @renard11! It looks like you and @willcampbell7 filed similar issues at the same time, with similar links. Just in case you both know eachother, I should say: Try not to file duplicate issues! :smile:
