### ISSUE TITLE
Prompt, history

### ISSUE THREAD

**Issue by goodandrewsoft** [microsoft/terminal#9645]
1. Is it possible to make PROMPT in wt like on screen
![image](https://user-images.githubusercontent.com/2471892/112803719-4604db80-907c-11eb-9206-11b13fd4275d.png)
In settings or ..... ?

2. Is it possible to use `history` in cmd like in bash ?

**Comment by zadjii-msft** [comment]
You can customize your `cmd.exe` prompt however you like - you just need to set the `PROMPT` variable. Mine is set like so:
![image](https://user-images.githubusercontent.com/18356694/112826635-df1efc80-9052-11eb-8aa3-9827cf62fcb4.png)

to give me:
![image](https://user-images.githubusercontent.com/18356694/112826665-ea722800-9052-11eb-820c-96fc0939149d.png). I'd check out: https://stackoverflow.com/questions/12028372/how-do-i-change-the-command-line-prompt-in-windows.

<hr>

There isn't a good replacement for `history` for use with `cmd.exe`. You could try hitting <kbd>F7</kbd> which will get you a menu like this:
![image](https://user-images.githubusercontent.com/18356694/112826837-23aa9800-9053-11eb-89c7-e9c2bf3a72eb.png)

**Comment by inoyakaigor** [comment]
@zadjii-msft Can you provide your prompt as text?

**Comment by KalleOlaviNiemitalo** [comment]
You can export the command history with **[doskey](https://docs.microsoft.com/windows-server/administration/windows-commands/doskey) /history**, and clear it with **doskey /reinstall**. (I imagine **/reinstall** harks back to the terminate-and-stay-resident DOSKEY program on MS-DOS.)

**Comment by zadjii-msft** [comment]
Sure: 

```
$e[30;107m[$T]$e[97;46m$g$P$e[36;49m$g$e[0m$e[K$_$e[0m$e[94mmigrie$e[0m@$e[32mMIGRIE-SLAPTOP$e[0m$G
```

of course, replace `migrie` and `MIGRIE-SLAPTOP` with `%username%` and `%computername%` as necessary.
