### ISSUE TITLE
[Feature] Allow for defining the settings.json path as a command line parameter. 

### ISSUE THREAD

**Issue by ByronMayne** [microsoft/terminal#9647]
# Description of the new feature/enhancement

Right now the settings.json configuration file is hard coded to look in %LocalAppData% and load whatever is there. I would like to have the ability to override this as a command line parameter when launching Windows Terminal. In our use case we have tooling that creates development environments for the users machine. One of the things I would like to do is to define a custom settings.json for each environment without having to override the users own. 

> ps: Windows Terminal is awesome and I just want to share it more!

**Comment by WSLUser** [comment]
> One of the things I would like to do is to define a custom settings.json for each environment without having to override the users own.

You might be interested in the new extension support, which is what you really want. https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6687 for more discussion.

/dup #6687
