### ISSUE TITLE
Windows Terminal

### ISSUE THREAD

**Issue by Chaitanya-art-sys** [microsoft/terminal#9651]
How to use the new windows terminal as administrator?

**Comment by zadjii-msft** [comment]
You can get there by right clicking on the taskbar entry:

![image](https://user-images.githubusercontent.com/18356694/112867435-8a927600-9080-11eb-9039-5cd24b0ba8c5.png)

By using the start menu:
![image](https://user-images.githubusercontent.com/18356694/112867531-a8f87180-9080-11eb-9e01-c2fe8b74c372.png)

Or by using the run dialog to launch `wt.exe` as you would launch any other process elevated.
