### ISSUE TITLE
设置默认配置文件的时,如果没有确定选择而操作鼠标滚轮,就会出现这个情况

### ISSUE THREAD

**Issue by Vzz1c** [microsoft/terminal#9657]
![image](https://user-images.githubusercontent.com/49944812/113003163-0a196580-91a5-11eb-9d13-2b1f70cc5452.png)

**Comment by skyline75489** [comment]
Translation: when in the setting page, if you don’t do selection but use your mouse scrolling wheel, this will happen. 

I honestly don’t know how to repro this even I understand the language. It’s still vague...

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually already being tracked by another issue on our repo - please refer to #9320 for more discussion.

/dup #9320
