### ISSUE TITLE
Bug Report - Ubuntu not working/tab only shows icon and cant type.

### ISSUE THREAD

**Issue by NyTR0SGaM1NG** [microsoft/terminal#966]
![jshsptBP8g](https://user-images.githubusercontent.com/19482930/58286199-13dd1100-7d63-11e9-8c7c-728302941509.png)
# Environment
Microsoft Windows [Version 10.0.18362.116]
# Steps to reproduce
Just open the windows terminal app.
# Expected behavior
for me to be able to use the ubuntu side of things.
# Actual behavior
when I open it it just shows the ubuntu logo  and does not show anything at all. and it just wont let me type anything at all.

**Comment by zadjii-msft** [comment]
Could you share your settings file? If I had to guess, we failed to launch whatever your `commandline` is.

**Comment by NyTR0SGaM1NG** [comment]
> 
> 
> Could you share your settings file? If I had to guess, we failed to launch whatever your `commandline` is.

do you mean the settings.json? if so here. . . 

[settings.txt](https://github.com/microsoft/terminal/files/3214214/settings.txt)

**Comment by zadjii-msft** [comment]
Is wsl installed? Do you have the Ubuntu distro installed from the store?

Your profiles.json seems fine to me - the commandline for the default profile is wsl.exe, which seems normal to me.

**Comment by Eduardopinatec** [comment]
Does some one has already solve this problem?? If yes can you tell me how. Thanks

**Comment by NyTR0SGaM1NG** [comment]
Hey sorry for the delayed response but no I guess I did not have.ubuntu installed at all. But yes if you are having the same problem then just go to the windows Store and download the app and install it

**Comment by zadjii-msft** [comment]
Great! I'm glad installing Ubuntu solved your problem.
