### ISSUE TITLE
system commands not working 

### ISSUE THREAD

**Issue by pauliee99** [microsoft/terminal#9663]
Hello, am having issues running commands in the Windows Terminal app located in ```C:\Windows\System32``` with cmd and powershell (ssh, ipconfig, e.t.c.) and i get the following error:
```
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ssh
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
The directory ```C:\Windows\System32``` is located in the environment variables and they are working properly in powershell and cmd applications.

**Comment by DHowett** [comment]
You're welcome! Sometimes we see systems where it never got updated -- usually when the system was running a much older version of Windows 10.

I'm glad it's fixed.
