### ISSUE TITLE
Cannot access the settings tab when certain settings are active

### ISSUE THREAD

**Issue by poaeowiz** [microsoft/terminal#9666]
### Windows Terminal version (or Windows build number)

10.0.19041.867

### Steps to reproduce

In settings, turn "Always Show Tabs" and "Hide the title bar" off, then restart WT. Make sure you only have one tab open.

### Expected Behavior

I would imagine there would be another way to access the settings tab apart for the keybind, especially since the only way to learn about the keybind is in the settings. This is unintuitive because if someone wants to access the settings tab with this configuration they would have to memorize the keybind. I would suggest that you would be able to access the settings by right clicking on the title bar, like in the command prompt.
  
### Actual Behavior

If you have "Always Show Tabs" and "Hide the title bar" off, you cannot access the settings in any way but the keybind (CTRL+, ). This only occurs if you have one tab open.

**Comment by zadjii-msft** [comment]
That seems like "working as expected" to me. What would you expect the behavior to be here?

**Comment by DHowett** [comment]
We probably should offer something in the title bar right-click menu that affords for access to the settings, honestly. It would provide a "complete" story. :smile:

**Comment by pandrwizard** [comment]
Apologies for the sudden close and reopen, I'm still new to using github and I didn't know that just hitting enter would cause it to close. I also couldn't figure out a way to reply to your message directly @zadjii-msft so I edited the issue to explain my thoughts.

**Comment by zadjii-msft** [comment]
I'm cool with keeping this open to stick a "settings" entry in the titlebar context menu like conhost did.

**Comment by sourabh112** [comment]
Hi @zadjii-msft @DHowett, I tried and recreated this issue. I want to try solving this issue but as I'm new to this, I need some guidance to start working on this.

**Comment by sourabh112** [comment]
Where are the relevant files in which I have to add "setting" for it to appear in the titlebar? I tried finding it but was unsuccessful.
