### ISSUE TITLE
[Feature] Auto-detecting file URLs and make them clickable 

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#9669]
Inspired by https://github.com/microsoft/terminal/issues/8166#issuecomment-724151089, we can also make the result of `ls` clickable if the CWD is provided. This is also possible in iTerm2. I'm not sure which sequence or technology it uses to detect the CWD, though. Anyway, with OSC9;9 recently added, this is also possible in WT.

_Originally posted by @skyline75489 in https://github.com/microsoft/terminal/issues/7526#issuecomment-766674544_

**Comment by skyline75489** [comment]
I think this is what I prefer over #9661. And there is precedent like iTerm2 who handles the file URL detection very well.

**Comment by zadjii-msft** [comment]
You know, this sounds just like #2671, so I'm just gonna move these comments there. Thanks though!
