### ISSUE TITLE
Number parameters in Powershell are barely visible under light color schemes.

### ISSUE THREAD

**Issue by CyanideCentral** [microsoft/terminal#9673]
# Environment
Windows version: 18363.1440
Terminal version: 1.6.10571.0

# Steps to reproduce
Set color theme to light color schemes, such as One Half Light, Tango Light or 3rd party light themes.
Enter command "abcd 1234" in a Powershell tab, or simply "1234". Weirdly this doesn't happen in CMD tabs.

# Expected behavior
I should be able to see the number displayed on screen.

# Actual behavior
I can barely tell the number from the white background. Effects of entering "abcd 1234":
### One Half Light
![image](https://user-images.githubusercontent.com/25578198/113111694-046e5f00-923b-11eb-836b-a3952cb04216.png)
I actually entered '1234' after the 'abcd '.
### Tango Light
![image](https://user-images.githubusercontent.com/25578198/113111878-31227680-923b-11eb-8c8c-b5e1849c7309.png)
Slightly better, but not clear at all.

# Proposed solution
Change the color setting for numbers entered in Powershell.

# Related to
#8033 #8716

**Comment by skyline75489** [comment]
As Dustin pointed out in https://github.com/microsoft/terminal/issues/8033#issuecomment-716058667 , this is actually by design. You'll need to do some configuring to make the color-emitting application more suitable for your needs.

**Comment by zadjii-msft** [comment]
Yea, this is by design. PSReadline's default config for text attributes doesn't really work all that well with light themes.
