### ISSUE TITLE
can't open the setting file

### ISSUE THREAD

**Issue by meiyuqingping** [microsoft/terminal#9675]
can't change the setting

**Comment by zadjii-msft** [comment]
I'm sorry, but there's nothing we can do with this issue as it is. There's a [perfectly good bug template](https://github.com/microsoft/terminal/issues/new?assignees=&labels=&template=Bug_Report.yml&title=) that's got important questions to answer, like:
* what version of the Terminal are you using?
* What version of windows?
* What _exactly_ are you doing?
* What's happening?

Additionally:
* What program is configured to be the editor for `.json` files on your PC?

If you can answer these questions, we can reopen and help investigate.
