### ISSUE TITLE
Mouse disappearing hovering over window and typing

### ISSUE THREAD

**Issue by hacker3983** [microsoft/terminal#9676]
### Windows Terminal version (or Windows build number)

10.0.19043.906

### Steps to reproduce

So i move my mouse over the window.
Then start typing in the terminal my mouse disappears

### Expected Behavior

When i type the Mouse should not disappear.

### Actual Behavior

Disappearing mouse while typing

When i type my mouse disappears on my end. but when i video it. it does not show it has disappeared

**Comment by DHowett** [comment]
This is true of text fields all over the operating system :smile: Terminal is operating by design.

**Comment by hacker3983** [comment]
ok is there away to disable it

**Comment by hacker3983** [comment]
ok thank you

**Comment by hacker3983** [comment]
but how do i disable it

**Comment by hacker3983** [comment]
ok thank you never mind i got it

**Comment by hacker3983** [comment]
wait i did it and it is still disappearing
