### ISSUE TITLE
Sometimes it refuses to input capital letters

### ISSUE THREAD

**Issue by chyvonomys** [microsoft/terminal#9678]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Steps to reproduce

Launch terminal application, start typing command, once in a while it doesn't let you input any capital letters. This issue persists during the session. Restart of terminal fixes that. 

### Actual Behavior

Pressing shift+letter does not input that capital letter.

**Comment by zadjii-msft** [comment]
Okay, so this is bizarre. We've seen this intermittently twice before, over in #7087 and #8450. From that thread:https://github.com/microsoft/terminal/issues/7087#issuecomment-676782357

> Found a fix. If you have the same problem as me, then updating PSReadLine to the latest preview version can help you. Check out this [PowerShell/PowerShell#10794](https://github.com/PowerShell/PowerShell/issues/10794) and this [PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine) for more information.

@chyvonomys Could you try that, and see if that resolves the issue?

**Comment by chyvonomys** [comment]
@zadjii-msft Yes, that seems to be the same issue, I did not realize I was starting terminal with keyboard layout switched to Ukrainian (in my case).
Updating PSReadLine fixed that! Thanks!

**Comment by zadjii-msft** [comment]
Okay awesome, thanks!

/dup #7087
