### ISSUE TITLE
Hotkeys: some emacs hotkeys are being eaten by Terminal

### ISSUE THREAD

**Issue by Pitta** [microsoft/terminal#9681]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

emacs 26.3
Ubuntu 20.04.2 LTS via WSL

### Steps to reproduce

emacs file.org
input to the file:
```
* header 1
* header 2
```

with the cursor at the end of the first line, hit `ctrl + RET`

### Expected Behavior

```
* header 1
* 
* header 2
```

A new header line on the next line

### Actual Behavior

```
* header 1

* header 2
```

emacs reacts as if I just hit `RET`, not `ctrl + RET`

Its very possible I'm missing something. I did try to unbind this hotkey from the terminal like i have a cople other.  Here is my unbind block.

```
        //unbinds
        { "command": "unbound", "keys": "alt+enter"},
        { "command": "unbound", "keys": "ctrl+enter"},
        { "command": "unbound", "keys": "ctrl+shift+d"},
```

**Comment by DHowett** [comment]
As far as I can tell, there is no distinct encoding for Ctrl+Enter that a console application can detect. Here, I'm testing rxvt (which follows xterm, and may have been forked from xterm? I'm not certain; xterm is our compatibility beacon however):

![image](https://user-images.githubusercontent.com/189190/113326145-e9edc180-92de-11eb-80b6-e394302b62a3.png)

How is this intended to work?

**Comment by Pitta** [comment]
Whelp - I'm a bit embarrassed that I took a YouTube video on face value as I was learning some stuff. Very possible this guy has remapped keys and just forgot.

I'm going to go ahead and say this is me being a dummy and shut this down. I was not able to see any specific encoding for ctlr+enter either. If I find more examples that are more concrete all reopen this issue.

**Comment by DHowett** [comment]
Now, there's something cool you can do. I suspect that xterm's "modify other keys" option would come in handy here... it is terminal-specific, but it MIGHT allow ^Enter to go through.

You can try to add a custom key binding for this:

```
{"command":{"action":"sendInput", "input": "\u001b[27;5;13~"}, "keys": "ctrl+enter"}
```

**Comment by DHowett** [comment]
(This is the xterm modifier encoding for enter w/ control, as enabled by xterm modifyOtherKeys (`\e[>4;1m`))
