### ISSUE TITLE
Out-of-box terminal cannot display Emoji

### ISSUE THREAD

**Issue by xlinush** [microsoft/terminal#9683]
I just got a new laptop and installed Windows Terminal from the store. The weird thing is emojis cannot be displayed correctly. Initially i thought it was that my font doesn't support powerline, so I verified that and realized it was actually emoji. This never happened on my old machines. Where should I start investigating? Thanks!

![image](https://user-images.githubusercontent.com/42554807/113263428-9cde0100-9286-11eb-9d8f-51bbda144baf.png)

**Comment by 237dmitry** [comment]
> Where should I start investigating?

Choose correct font. For example "Cascadia Code **_PL_**"

```
        "defaults":
        {
         .....
        //  "fontFace": "TerminessTTF NF",
        //  "fontFace": "Cascadia Code PL",
            "fontFace": "Fantasque Sans Mono",
        .....
```

**Comment by zadjii-msft** [comment]
Yep, @237dmitry is correct. You need to select a font that supports power line glyphs

**Comment by xlinush** [comment]
@zadjii-msft the screenshot might be misleading. the font i use (Fira Code) supports power line glyphs and they are showing fine. this is what looks like with `"fontFace": "Cascadia Mono PL"`

![image](https://user-images.githubusercontent.com/42554807/113317754-89ea2180-92c4-11eb-8cde-38f126f52deb.png)

**Comment by DHowett** [comment]
Sorry, we mis spoke. These are “nerd font” glyphs.

**Comment by xlinush** [comment]
hey @DHowett what "nerd font" glyphs are you referring to here?

**Comment by DHowett** [comment]
Each glyph in your screenshot that is displayed as an empty box. The PowerLine glyphs are working fine, but some prompts use the additional 1,200 glyphs added by the "Nerd Font" patcher.

**Comment by xlinush** [comment]
i don't remember doing any patching on other machines but thanks so much for the help. Aren't nerd fonts already included in Cascadia Code/Mono **PL**?

**Comment by DHowett** [comment]
No. Like all other powerline-patched fonts, only powerline glyphs are included in the PL variant. We aren't distributing "NF" variants because of the licensing concerns about the company logos and other glyph in the NF variant ☹️

**Comment by xlinush** [comment]
@DHowett gotcha thanks so much background 👍 i'll try some other fix later today
