### ISSUE TITLE
Folder Name as Tab Title

### ISSUE THREAD

**Issue by tthrash** [microsoft/terminal#9684]
Please add a setting to have the tab title be the folder name. Ideally as <folder name>(shell). Currently for me it just shows the shell title.

For example, if I have a PowerShell Core instance open in myApp folder then have the tab title be: "myApp (PowerShell)" or simply "myApp".

There's possibly an existing way to do this, but what I'm suggesting is to have an easy setting instead.

**Comment by WSLUser** [comment]
Please check the docs before filing issues like this: https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title

**Comment by DHowett** [comment]
Yup! This is totally possible with the cooperation of your shell.

**Comment by tthrash** [comment]
I did see those docs, but I was wondering if there was an way that the tab title could be set with a simple, universal setting in Windows Terminal. This was rather a feature request. Such as having tabTitle configurations (for example, static string, absolute path, relative path), and based on the shell instance have code within Windows Terminal to do that for the most popular shells.

For anyone wondering I was able to set this up for PowerShell Core shell by adding the following code to my PowerShell Core profile in `Documents\PowerShell\Microsoft.PowerShell_profile.ps1` 
```
function Prompt
{
  $host.UI.RawUI.WindowTitle = Split-Path (Get-Location) -Leaf
}
```

**Comment by DHowett** [comment]
I'd love for us to offer this, but unfortunately it's difficult for Terminal to know what folder you're operating in. PowerShell doesn't update its process-level working directory; SSH targets a remote machine; you might have run a shell inside your shell (`cmd` -> `wsl`; which one should it report? what if you're running `wmic` and it changes to system32 _just because_?); WSL operates in a totally different filesystem environment;

The list goes on. We have a couple other things that would depend on the active working directory path that we'd love to land . . . but unfortunately we don't think we can.

**Comment by tthrash** [comment]
That's unfortunate, but makes sense. 

Maybe there could be some sort of api standards in the shell world to work with tools like Terminal better. I'm not sure if that would make sense or not, but if anyone could make that happen it would be a company like Microsoft. I guarantee Terminal is going to be hugely popular over time, so there would be leverage in that as well.

Thank you for your quick responses, and keep up the great work!

**Comment by zadjii-msft** [comment]
> Maybe there could be some sort of api standards in the shell world to work with tools like Terminal better

FYI there is such a "standard", called Escape Sequences (also ANSI escape sequences, VT sequences). See [this page](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) for probably the most complete documentation. A shell can already use VT sequences to tell a terminal emulator to do all sorts of things,. For examplem, setting the title of the window with `\e]0;YourTitleHere\a`, which is [exactly what we recommend](https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title#set-the-shells-title) doing 😉

**Comment by catamphetamine** [comment]
> The list goes on.

Then it would be easier to have a page in the docs describing how to set up "Folder Name as Tab Name" for each popular shell.

No, I won't be writing something like that. I don't currently use this application.
