### ISSUE TITLE
Mouse doesn't work in CMD console applications 

### ISSUE THREAD

**Issue by nredko** [microsoft/terminal#9685]
Example: Far Manager http://farmanager.com

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #376 for more discussion

/dup #376

**Comment by nredko** [comment]
Hi

No, it’s not duplicate!

The issue you refer to concerns Linux subsystem. In current terminal app with wsl the mouse works well. 

I’m reporting about native windows console applications like Far Manager. 
It receives mouse input well if run in regular cmd window, but doesn’t in TerminalApp. 

Thanks,
Nik

**Comment by DHowett** [comment]
376 tracks support for windows mouse applications.
