### ISSUE TITLE
Could initialPosition support negative coordinates?

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [microsoft/terminal#9686]
# Description of the new feature/enhancement
I'd love to specify the initial position of the terminal from the bottom left corner of the screen. My CSS influence tempts me to put a negative number for top, which in my mind would mean that many pixels from the bottom of the screen (and extend the height upwards instead of downwards).  

I'm constantly switching between large and small screens and having to move and resize the window every time I open it is annoying. True per-display-size profile settings would be a more complete solution but this seems like a more easily workable idea.

# Proposed technical implementation details (optional)

Coordinates are (left, top).

Position (50, 100) = 50 from left, 100 from top. Height measures down from 100, width rightward from 50.
Position (20, -25) = 20 from left, 25 from bottom. Height measures upward from (viewport - 25). Width rightward from 20.

**Comment by DHowett** [comment]
Unfortunately, we already do support negative values! They don't do what you would expect, coming from CSS, however (sorry!). Coordinates in this coordinate space act with (0,0) at the top left of the _primary display_; negative coordinates push the application (nee all windows applications) into monitors to the left of or above the primary display. It's the only way to specify that Terminal, say, maximize itself on the non-default display.
