### ISSUE TITLE
Default to pwsh.exe then powershell.exe for cli app profiles

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#9687]
# Description of the new feature/enhancement

If you create a custom profile for running a cli app such as the SSH profile, default to using pwsh.exe for running that cli app. If it's not installed, then default to powershell.exe.

# Proposed technical implementation details (optional)
Looks like cli apps such as SSH are registered to CMD automatically by WIndows Terminal. So change this to powershell.exe instead and add logic to prioritize use of pwsh.exe if installed before attempting to use powershell.exe.

An aside: I notice defining powershell.exe in the commandline parameter works as expected. However setting pwsh.exe does not. It opens a tab and immediately closes and in the brief second it's open, you can notice an error about not recognizing ssh even though in a normal pwsh tab, ssh works just fine (you might need to flash the tab a few times to get enough of the error to read it, or better yet, use some screen recording software to capture it and simply review the recording). So likely there's some env var issues there on WT side (PS7 is at top of env vars with SSH right below it).

**Comment by DHowett** [comment]
Terminal does not launch CLI applications using another shell; it launches them directly using CreateProcess. I do not think that we should add powershell's start-up time to the start-up process for every profile; it would waste time and confer no benefit.

**Comment by DHowett** [comment]
You can tell this by looking at Process Explorer -- the spawned CLI application has no parent process other than WindowsTerminal.exe. :smile:

**Comment by DHowett** [comment]
> An aside: I notice defining powershell.exe in the commandline parameter works as expected. However setting pwsh.exe does not. It opens a tab and immediately closes and in the brief second it's open, you can notice an error about not recognizing ssh even though in a normal pwsh tab, ssh works just fine (you might need to flash the tab a few times to get enough of the error to read it, or better yet, use some screen recording software to capture it and simply review the recording). So likely there's some env var issues there on WT side (PS7 is at top of env vars with SSH right below it).

I would guess that you are using a 32-bit version of pwsh. If you leave 'closeOnExit' set to its default setting, you will get to see the error message.
