### ISSUE TITLE
URL is not detected correctly

### ISSUE THREAD

**Issue by wasker** [microsoft/terminal#9689]
### Windows Terminal version (or Windows build number)

10.0.19042.867, 1.6.10571.0

### Steps to reproduce

Our logs display URLs that look like the one shown below. Terminal's URL detection doesn't pick up parts after opening square bracket:

```
https://somedomainname.net/?x=y&y=z&z=q&q=w&w=a&a=s&s=d&d=f&f=[["xxx","yyy"],["zzz","qqq"]]
```

### Expected Behavior

The whole URL is detected.

### Actual Behavior

Only this part is underlined when mouse is hovering on the URL: "https://somedomainname.net/?x=y&y=z&z=q&q=w&w=a&a=s&s=d&d=f&f="

**Comment by j4james** [comment]
I think this is probably covered by issue #8321.

**Comment by zadjii-msft** [comment]
Yea, I think that's the bucket we're putting these discussions in. Thanks!

/dup #8321
