### ISSUE TITLE
[Question] When this terminal will be the default in windows 10?

### ISSUE THREAD

**Issue by thedonator** [microsoft/terminal#9691]
Is there a milestone that takes this terminal in windows 10, substituting the current terminal?

**Comment by zadjii-msft** [comment]
There is a plan, but not one with a timeframe that I don't think we're sharing publicly at this time. Any particular reason you're asking? The Terminal does already ship in Windows in recent Insider's builds.

**Comment by thedonator** [comment]
@zadjii-msft it was just a curiosity because i use a lot the new terminal because i prefer it from the default terminal and it would be very good running the terminal without every time searching fo the new teminal

**Comment by zadjii-msft** [comment]
Cool! Well you'll be very glad that we're actively working on adding support for making the Terminal the default experience - see #492, #7489, and other linked threads for more details.
