### ISSUE TITLE
Copy Paste is from Terminal(Powershell) -> VSCode is just broken

### ISSUE THREAD

**Issue by colemickens** [microsoft/terminal#9696]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Other Software

Nope, just plain old Powershell built into Win10

### Steps to reproduce

Start Terminal.
Copy some text.
Paste it into VSCodium.

### Expected Behavior

It is readable? Usable? Not useless?

### Actual Behavior

It is indeed a single useless line of text. 

I don't feel like I've always had this issue, maybe something bad slipped into the Preview builds? I don't know, for know I just am not using Terminal right now.

(Also, unrelated, but complete LOL at the fact that "Cod" still can't autocomplete to "VSCodium" in Win10. Stunning.)

**Comment by colemickens** [comment]
Well, even worse, it's seemingly rather inconsistent when making this repro video: https://youtu.be/YUTGcPrOueA (enjoy the extra win10 bug of being unable to close the Terminal repeatedly).

I can't tell what I'm doing differently between when it works correctly vs not.

**Comment by skyline75489** [comment]
You’re disappointed. I get it. But can you elaborate on the “useless text” part? A screenshot would be nice. I have no idea what exactly the issue is after reading all your complaints.

**Comment by skyline75489** [comment]
Oh. A YouTube video. Didn’t see that. But, I’m in China so that video can be problem for me.

**Comment by colemickens** [comment]
Sometimes when you copy-paste from the terminal, it respects line breaks, other times it copies a single line of text with tons of spaces embedded. Sorry the emotion got in the way of a better issue description; a screenshot would've made sense. I can provide one now:

![vscode-wrap](https://user-images.githubusercontent.com/327028/113460591-2d732900-93ce-11eb-9bb3-4131bea4b0d5.PNG)


Again, sometimes it copies and pastes as expected, sometimes this, it's hard to tell when each will happen. When making this screenshot, it actually worked correctly several times before I stopped/restarted and then it reprod. (And the same behavior is observed with `notepad.exe`).

**Comment by 237dmitry** [comment]
What the string is between Logo and prompt? If you are using custom $profile then maybe something wrong in it. Something that may affect the text being copied.

**Comment by colemickens** [comment]
The string between the logo and the prompt is the output of `ssh-add -l`.

But, again, the video shows multiple attempts. All attempts include that line of text. And yet it only pastes correctly about half the time.

**Comment by zadjii-msft** [comment]
Are you always copying in the same way? i.e. always pressing the same keybinding or always right clicking, with the same modifiers each time?

**Comment by skyline75489** [comment]
Is #6901 somewhat related to this?

**Comment by zadjii-msft** [comment]
Very likely, though, I'm more confused here that the same rows of text are sometimes copying with newlines and sometimes without. The bug that's hiding in #6901 seems more to be that conpty doesn't always mark the rows as wrapped correctly. In that case, the lines would consistently copy wrong, because they're in the buffer wrong. In this issue's case, the lines are sometimes copying with newlines and sometimes without, and that's mysterious and new.

**Comment by DHowett** [comment]
We shouldn't necessarily let the bot mark this one just yet. Not sure whether this is a new issue or another face of 6901.

**Comment by colemickens** [comment]
Oh, I'm used to holding shift while selecting things (tmux, etc). So I hold shift, drag, right click.

If I'm still holding shift when I right click, it's copied as a single line. Now I'm worried this is maybe in fact expected behavior.

**Comment by zadjii-msft** [comment]
> Now I'm worried this is maybe in fact expected behavior.

It most certainly _is_ expected behavior:

https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalControl/TermControl.cpp#L1443

where `shiftEnabled` is filling the `copySingleLine` param. Glad we were able to figure this one out!

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/9933
