### ISSUE TITLE
Fontface not working

### ISSUE THREAD

**Issue by gauravcanon** [microsoft/terminal#9698]
Here is my piece of setting.json. 
```json
{
                "colorScheme": "Argonaut",
                "commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command \"& C:\\Users\\%USERNAME%\\anaconda3\\shell\\condabin\\conda-hook.ps1 ; conda activate C:\\Users\\%USERNAME%\\anaconda3 \"",
                "experimental.retroTerminalEffect": false,
                "fontFace": "Cascadia Code PL",
                "fontSize": 12,
                "fontWeight": "normal",
                "guid": "{09dc5eef-6840-4050-ae69-21e55e6a2e95}",
                "hidden": false,
                "icon": "C:/Users/%USERNAME%/anaconda3/Menu/anaconda-navigator.ico",
                "name": "Anaconda",
                "startingDirectory": "C:/Users/%USERNAME%",
                "suppressApplicationTitle": true
            },
```
Result - Earlier same thing was working fine

![Error](https://user-images.githubusercontent.com/897747/113474271-ab960500-948c-11eb-8d8e-37b7e3b39c95.png)

But the same is working without using conda 
```json
{
                "colorScheme": "AlienBlood",
                "commandline": "powershell.exe",
                "fontFace": "Cascadia Code PL",
                "fontSize": 12,
                "fontWeight": "light",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Terminal"
            },
```

Result - this should be expected and was working before 
![wroking](https://user-images.githubusercontent.com/897747/113474311-e9932900-948c-11eb-8152-65f949eaad9d.png)

Everything was working fine after running `conda init` . Now "font face" not working

**Comment by skyline75489** [comment]
What’s the thing that’s not working, exactly? You mean the symbol is not correctly displayed?

**Comment by gauravcanon** [comment]
> What’s the thing that’s not working, exactly? You mean the symbol is not correctly displayed?

Sorry, I can't explain you better. 
Symbols are not even displayed.

First: image what I am getting currently

But before my command `conda init` 
I was getting symbols perfectly like second image

**Comment by LuanVSO** [comment]
something is overriding your prompt?

**Comment by gauravcanon** [comment]
@LuanVSO Can't be sure but look like that might be an issue. How to check?

**Comment by gauravcanon** [comment]
@LuanVSO Thanks for suggesting that. found issue and fixed it 
Now when I run `conda init ` it updated file `C:\\Users\\%USERNAME%\\anaconda3\\shell\\condabin\\conda-hook.ps1`
conda-hook.ps1 
```
$Env:CONDA_EXE = "C:\Users\gaura\anaconda3\Scripts\conda.exe"
$Env:_CE_M = ""
$Env:_CE_CONDA = ""
$Env:_CONDA_ROOT = "C:\Users\gaura\anaconda3"
$Env:_CONDA_EXE = "C:\Users\gaura\anaconda3\Scripts\conda.exe"

Import-Module "$Env:_CONDA_ROOT\shell\condabin\Conda.psm1"
Add-CondaEnvironmentToPrompt   
```
Last line 
`Add-CondaEnvironmentToPrompt `
This was the culprit of the overriding prompt. Now it fixed and works as earlier.
