### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Pavui** [microsoft/terminal#9705]
### Windows Terminal version (or Windows build number)

Version 10.0.21343.1000

### Steps to reproduce

Opening Windows Terminal

### Expected Behavior

I love the look, I just wish the text had a higher resolution.

### Actual Behavior

Looks more 360p than HD resolution.

**Comment by DHowett** [comment]
We might need a screenshot to help you with your issue. We can’t really do anything about visual glitches if we can’t actually see what they are ;)

**Comment by Pavui** [comment]
![image](https://user-images.githubusercontent.com/73035923/113612678-25a9c380-961e-11eb-85cd-b77883b35cc4.png)

It just looks alittle low res in my opinion

**Comment by ianpan870102** [comment]
@Pavui Can you provide side-by-side screenshot with another app that you consider higher res?

**Comment by zadjii-msft** [comment]
Yea, that _looks_ high res to me... Maybe what you want is a different type of antialiasing? (see the `antialiasingMode` setting)
