### ISSUE TITLE
Rectangular select copies trailing spaces

### ISSUE THREAD

**Issue by randomascii** [microsoft/terminal#9706]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

When doing a rectangular copy of text Windows Terminal copies trailing spaces. If the different lines being copied are of different lengths then this means the clipboard contents end up with varying numbers of spaces. Cleaning this up is a nuisance. Trailing spaces are rarely desirable when pasting text. For instance, if the terminal contained this text:

1:   blah blah blah     Column 3
2:   foo                       Column 3

then I might want to copy the first two columns of data ("1:   blah blah blah" and the subsequent data below or perhaps just the second column of data ("blah blah blah" and the subsequent data below) but I (personally), never want to copy the trailing spaces. I think that this is a change of behavior. I think it is a regression. It is certainly a change from cmd.exe, and not a welcome one.

### Expected Behavior

No trailing spaces copied to the clipboard.

### Actual Behavior

Trailing spaces copied to the clipboard.

**Comment by DHowett** [comment]
@Don-Vito here’s your callback! ;)

**Comment by zadjii-msft** [comment]
So the original discussion was over here: #6740.

There's not a clear consensus on whether block selection should copy the trailing space or trim them. Both options seem to suck equally.

**Comment by randomascii** [comment]
I'm definitely of the opinion that the old behavior was excellent and the new option sucks greatly.

It sounds like a setting would be worthwhile. There seem to be some developers/workflows that require the full rectangle of characters, but for my purposes I never want it and the presence of those spaces has been making me cranky. I haven't quite gone to the stage where I write a program to trim trailing spaces in the clipboard but that is my mood.

Rather than do that I'd much rather have a setting that trims all trailing spaces, like cmd.exe did.

**Comment by DHowett** [comment]
Yep, this should be a setting. Thanks :smile:

**Comment by Don-Vito** [comment]
@DHowett  - please assign this to me. What should be the default?

**Comment by DHowett** [comment]
We're about to drop 1.7 to stable, so we will have **ample** data on which one people hate more. I am truly uncertain.

**Comment by Don-Vito** [comment]
![image](https://user-images.githubusercontent.com/4639110/114705336-4b2a8180-9d30-11eb-91ae-eecfb226d6c8.png)

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/12536
