### ISSUE TITLE
Activating terminal by clicking on the tab does not set input focus

### ISSUE THREAD

**Issue by randomascii** [microsoft/terminal#9707]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

When I activate the Windows Terminal it is because I want to type into it. However if I activate the Windows Terminal by clicking on the tab (i.e.; the tab-switcher component at the top of the window) then input focus is not set and will actually be taken away.

To be more precise, if I click on the tab-switcher for the _current_ tab then focus is taken away. If I click on a different tab then focus is set.

### Expected Behavior

When I click on a tab-switcher, whether to give the terminal focus or just because I feel like it, input focus should be set to that tab. The cursor should flash and any characters that I type should be displayed.

### Actual Behavior

When I click on the tab-switcher for the currently selected tab then input focus is turned off, the flashing cursor goes away, and my keystrokes go nowhere.

**Comment by j4james** [comment]
This sounds like issue #3609.

**Comment by zadjii-msft** [comment]
Sure is!

/dup #3609
