### ISSUE TITLE
Add "Open Elevated" task item to right click menu

### ISSUE THREAD

**Issue by terrajobst** [microsoft/terminal#9709]
# Description of the new feature/enhancement

Very often one needs an elevated terminal instance. I recently (relearned) about CTRL+SHIFT for launching items from the taskbar or the start menu, which is awesome, but not very discoverable.

# Proposed technical implementation details (optional)

I'd love to have an "Open Elevated" as a task item in the jump list menu of the terminal:

![image](https://user-images.githubusercontent.com/5169960/113612440-b7a4d280-9604-11eb-8713-1d6652f16354.png)

**Comment by WSLUser** [comment]
You can alright right click for it the same way you open the jumplist. But from Explorer, you are unable to do this. The list of profiles doesn't show up either. However the request for profiles already has existing issue (forget issue#).

**Comment by 237dmitry** [comment]
Until this is implemented I use  [gsudo](https://github.com/gerardog/gsudo/releases)

![menu](https://user-images.githubusercontent.com/78153320/113637454-4c4b1700-967d-11eb-8d78-bfb09c66938d.png)

```
 {                                                                               
     "name": "Windows PowerShell (Admin)",                                       
     "guid": "{4f4b29ca-00a4-4bb5-88b6-88da926c0775}",                           
     "hidden": false,                                                            
     "icon": "%UserProfile%\\Documents\\WindowsPowerShell\\powershell-admin.png",
     "colorScheme": "Admin",                                
     "tabColor": "#151515",                                                      
     "commandline": "%UserProfile%\\bin\\gsudo.exe powershell.exe -NoLogo"         
 },                                                                              
```

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+elevated+jumplist+is%3Aclosed) when filing new issues. This is something that's already possible today:

![image](https://user-images.githubusercontent.com/18356694/113700158-1ff2c300-969c-11eb-896a-7ee70aac836f.png)

/dup #632
