### ISSUE TITLE
Font is blurry

### ISSUE THREAD

**Issue by ox15** [microsoft/terminal#9710]
### Windows Terminal version (or Windows build number)

 10.0.19042.868, 1.6.10571.0

### Steps to reproduce

Open Terminal and you'll get a blurry font that's hard to read.

### Expected Behavior

I was expecting the font to be normal, not blurry.

### Actual Behavior

The font was blurry. I changed it to Courier New, but it was still blurry.

The font is blurry in Terminal, but appears normal when PowerShell is run as a standalone application. It's also blurry in Command Prompt inside Terminal.

![image](https://user-images.githubusercontent.com/64105193/113622634-44fb1d80-962b-11eb-94ec-b37cc310e8cd.png)

**Comment by zadjii-msft** [comment]
Can you try out the [experimental rendering properties](https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#the-text-is-blurry) and see if that helps resolve the issue?

**Comment by JewceCookie** [comment]
you used the wrong anti-aliasing
