### ISSUE TITLE
Feature request: Ability to change window appearance when window is not in focus

### ISSUE THREAD

**Issue by deadlydog** [microsoft/terminal#9711]
We already have the ability to customize the appearance of the Windows Terminal via profiles. I'm requesting that a "lostFocus" profile be supported, where it would take effect when the Windows Terminal is not in focus. This would allow us to give the Windows Terminal a different appearance when not in focus, allowing you to easily differentiate when the window has focus and you can type in it, and when another application has focus. e.g. decrease the acrylicOpacity of the window when it's not in focus. If no "lostFocus" profile is defined, then it would continue to work as it does today.

Since not all of the settings in a profile are related to appearance, another alternative would be to instead support a separate color scheme when the window is not in focus. Really all I'm looking for is a way to easily distinguish when the window has focus or it doesn't. Currently the only visual indicator that the window has focus is the small blinking cursor, and that only shows up if your terminal window isn't scrolled up; if it is scrolled up then there's absolutely no visual indicator that the Windows Terminal has focus, besides the Windows taskbar, which isn't always noticeable, especially with multi-monitor setups.

**Comment by zadjii-msft** [comment]
Boy, are you gonna be excited about this PR we've got in flight: #8392. That's not _exactly_ what you've asked for, but it should accomplish the same goal.

/dup #3062
/dup #2316
