### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by ansariabr** [microsoft/terminal#9712]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎20-‎06-‎2020
OS build	19042.870
Experience	Windows Feature Experience Pack 120.2212.551.0

### Steps to reproduce

I am searching and opening Terminal from start menu.
Just a point here which I think is causing this issue is, I have space in my windows user directory name, it is "C:\Users\Abdul Rahman"

### Expected Behavior

Terminal should start

### Actual Behavior

Immediately crashing on startup

Following is the error I managed to grab after video recording,
![image](https://user-images.githubusercontent.com/1421986/113662520-e2a32b00-96c5-11eb-93de-17127e105fc0.png)

Following is the error logged in Event Viewer
![image](https://user-images.githubusercontent.com/1421986/113662976-c784eb00-96c6-11eb-9c8d-2b778b7e313e.png)

**Comment by zadjii-msft** [comment]
What's the `commandline` and `startingDirectory` of your default profile?

**Comment by DHowett** [comment]
I suspect that this is an issue with the powershell dotnet global tool wrapper. I'm guessing your only powershell core install came from `dotnet tool install ...`

Feedback hub link of our crash would be most helpful, though. Even if powershell can't start, we shouldn't crash.

**Comment by ansariabr** [comment]
> 
> 
> What's the `commandline` and `startingDirectory` of your default profile?

I am not sure how to get these, can you help me how to pull out these values @zadjii-msft?

**Comment by zadjii-msft** [comment]
Can you just share your whole `settings.json` file?

**Comment by ansariabr** [comment]
I dont see the settings.json in Windows Terminal folder inside WindowsApps folder. But I do see defaults.json file (renamed to .txt to upload here), attaching it here. Hope this helps @zadjii-msft.
[defaults.json.txt](https://github.com/microsoft/terminal/files/6308935/defaults.json.txt)

**Comment by zadjii-msft** [comment]
Actually, no, `defaults.json`  is a static file that ships with the terminal. So I actually already have that file [right here](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json) 😆 

You can get to the settings file by clicking on the new tab dropdown and clicking on "settings". That'll open the file in whatever your default `.json` editor is

**Comment by ansariabr** [comment]
@zadjii-msft But thats the issue, Windows Terminal is crashing on startup only. Windows Terminal is not opening at all.

**Comment by zadjii-msft** [comment]
Ah right, derp. The path to the settings file should be something like:

```
C:\Users\<your username>\AppData\Local\Packages\WindowsTerminalDev_8wekyb3d8bbwe\LocalState\settings.json

C:\Users\<your username>\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json

C:\Users\<your username>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
```

depending on which version of the app you've got installed

**Comment by ansariabr** [comment]
Got the settings file in this path - C:\Users\Abdul Rahman\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe

[settings.json.txt](https://github.com/microsoft/terminal/files/6312421/settings.json.txt)

**Comment by zadjii-msft** [comment]
Can you modify that file to add 
```json
"closeOnExit": "never"
```

to the defaults object? It should end up like:
```jsonc
...
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
			"closeOnExit": "never"
        },
        "list":
        [
...
```

then re-launch the terminal? That should at least leave it open long enough to see what the whole error is

**Comment by ansariabr** [comment]
Error is same as the one I mentioned earlier,
![image](https://user-images.githubusercontent.com/1421986/114749336-77fe8900-9d70-11eb-80d9-64d96eadcbe2.png)

**Comment by ansariabr** [comment]
@zadjii-msft I am able to open new tab with Command Prompt and Windows PowerShell. Looks like default PowerShell has some issue.

![image](https://user-images.githubusercontent.com/1421986/114750986-3b339180-9d72-11eb-9d88-e7d3140ce765.png)

**Comment by DHowett** [comment]
Okay, there's two bugs here.

1. The dotnet global tool is broken when you have spaces in your user name.
2. The dotnet global tool _says that it was successful_ after it prints out the error message, so Terminal doesn't get a chance to present the error to you.

Terminal prefers PowerShell Core. You have installed powershell core as a dotnet global tool.

You can either reinstall it as a normal msi/msix, or wait for them to fix the dotnet global tool.

**Comment by DHowett** [comment]
Okay, I did some investigation. **They fixed this bug 2 years ago**.

https://github.com/PowerShell/PowerShell/pull/10461

You really should update your powershell installation.

**Comment by ansariabr** [comment]
After updating Powershell to latest one from https://github.com/PowerShell/PowerShell/releases/tag/v7.1.3, it is now working as expected. Thanks you @zadjii-msft and @DHowett
