### ISSUE TITLE
Terminal background color changes in area without text input

### ISSUE THREAD

**Issue by mingsxs** [microsoft/terminal#9713]
### Windows Terminal version (or Windows build number)

1.6.210226001-release1.6

### Other Software

Vim 8.1/8.0
Git 2.25.1

### Steps to reproduce

Open vim to edit some text file, and make some random operations like editing, searching, and wait for a while like minites, and then exit vim, the background of the area without text will change to strange color.
Issue git log command with interactive(less) output, and sometimes the same occasion will happen. 
Some other scenarios will also trigger this to happen, which I don't remember quite clearly.

### Expected Behavior

The terminal returns back to the original appearance before it enters some programs.

### Actual Behavior

The background color of the non-text area will just mess up sometimes, and it's intermittent. 

[
![Screenshot 2021-04-06 134701](https://user-images.githubusercontent.com/46848431/113698432-09ce1c80-9707-11eb-80e2-679107c92ef4.png)
](url)

**Comment by zadjii-msft** [comment]
Crazily enough, I think this is #3848.

/dup #3848
