### ISSUE TITLE
[BASH] Settings UI: Two issues in automatic profile naming

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9714]
### Windows Terminal version (or Windows build number)

1.8

### Steps to reproduce

* Add a new profile. The automatic name is (for example) "Profile 8". 
* Rename it to "Profile 9" (because you are trying to break Terminal, and for no other reason). 
* Add a new profile, which will be named "Profile 9".

### Actual Behavior

When you hit save, one disappears from the UI.

_originated in 4/2 bug bash_

**Comment by zadjii-msft** [comment]
_Two_ issues?

**Comment by DHowett** [comment]
Duplication of the number, stomping of the entry. I also don't think it _matters_ that much. There's easier ways to break Terminal :smile:

**Comment by carlos-zamora** [comment]
I'm marking this as help wanted. `CascadiaSettings::CreateNewProfile()` just needs to check if the newly generated name is taken, and, if it is, generate a new one.

Relevant code: https://github.com/microsoft/terminal/blob/361877cf1b1be2824f9f0373f1cf524b81cebb12/src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp#L222-L232

Today, we're naming the new profile "Profile <num of profiles>". We should probably just try "Profile <num of profiles + 1>" and keep incrementing it until we find one that works? I'm mildly annoyed that from that point forward, all new profiles would be called "Profile <num of profiles + 1>" but there's no reason for that to be annoying haha.
