### ISSUE TITLE
Theme change does not apply properly to settings UI

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9716]
![image](https://user-images.githubusercontent.com/189190/113726044-82a68780-96b9-11eb-8d73-f3835ec36ea3.png)

_originated in 4/2 bug bash_

**Comment by carlos-zamora** [comment]
@zadjii-msft just to be clear, this is an "easy-starter" because you have to basically do what we did in https://github.com/microsoft/terminal/pull/9732 to the entire SUI?

**Comment by zadjii-msft** [comment]
I think it's even easier than that. We probably don't need to do the whole recursive dance. We might be able to just set `RequestedTheme` on the `MainPage` itself. I only did the recursive-upwards thing because I presumed that TeachingTips were the same weird edge case that ContentDialogs were.

**Comment by Don-Vito** [comment]
I cannot reproduce it - any specific steps?

**Comment by carlos-zamora** [comment]
I was able to get a similar issue over in #9949. Couldn't get the resource to appear when the app's theme was different from the Windows OS theme.

Setting `RequestedTheme` on `MainPage` didn't fix it 😢

**Comment by Albert-Jokelin** [comment]
Hey! Can I work on this?

**Comment by zadjii-msft** [comment]
@Albert-Jokelin Sure, go right ahead! Though, we maybe should have yanked `Easy-Starter` off this one... if "Setting `RequestedTheme` on `MainPage` didn't fix it", then I'm not really sure where to start with this.

**Comment by Albert-Jokelin** [comment]
I'll try my best and if I need any help, I'll reach out to you guys.

**Comment by Albert-Jokelin** [comment]
@zadjii-msft I'm unable to recreate the issue. I'm running Windows 10 Home Ver. 20H2, Build: 19042.928

**Comment by zadjii-msft** [comment]
Son of a gun, you're right. Huh. Wonder when that got fixed? Glad to know it is though! Thanks for helping check that one out!
