### ISSUE TITLE
[BASH] Window Rename TeachingTip does not handle mixed system + terminal theme

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9717]
It's another problem with the app theme being a sack of lies.

_originated in 4/2 bug bash_

**Comment by zadjii-msft** [comment]
![img](https://media2.giphy.com/media/1APhNxj9slv0RdgHlL/giphy.gif)

**Comment by zadjii-msft** [comment]
Oh my god:
![image](https://user-images.githubusercontent.com/18356694/113752459-9f02ee00-96d2-11eb-944d-634274cd58e3.png)

Just naively setting `RequestedTheme` on the `TeachingTip` is not good enough. Apparently that doesn't cascade down to contents of the `TeachingTip`??
