### ISSUE TITLE
Selection is still super busted in 1.8 / `main`

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9725]
### Windows Terminal version (or Windows build number)

1.8.921.0

### Steps to reproduce

* Make a selection
* release the mouse
* Click somewhere inside the terminal, outside the original selection
* drag the mouse, as to create a new selection

### Expected Behavior

We should start a new selection

### Actual Behavior

The original selection dismisses, but a new one doesn't start :(

@Don-Vito as an FYI

**Comment by Don-Vito** [comment]
OK. I see the bug.. I am such a noob 😭
