### ISSUE TITLE
Rendering problem observed with NeoVim

### ISSUE THREAD

**Issue by jeapostrophe** [microsoft/terminal#9731]
### Windows Terminal version (or Windows build number)

Windows Terminal Preview Version: 1.7.572.0

### Other Software

NVIM v0.4.4
Pengwin WSL

### Steps to reproduce

The problem happens when I have vertical splits and modify one on the right. I have attached a video. But this also reproduces for me:

```
$ seq 800 > /tmp/a.py
$ seq 800 > /tmp/b.c
$ nvim /tmp/a.py
:vsp /tmp/b.c
# Select right frame
# Navigate to right of 9
i
# Press enter and it looks really messed up... the LHS is being modified and the RHS is wrong
```

### Expected Behavior

It should show the same file contents with no problems

### Actual Behavior

https://user-images.githubusercontent.com/232698/113761970-0f673a80-96e6-11eb-92c8-feae6db75c15.mp4

**Comment by jeapostrophe** [comment]
This error may depend on syntax coloring being turned on and other similar things that are enabled in my setup

**Comment by zadjii-msft** [comment]
> This error may depend on syntax coloring being turned on and other similar things that are enabled in my setup

Just to be sure, does this repro in neovim without any custom config enabled at all? (something like `nvim --clean` might work)

**Comment by jeapostrophe** [comment]
I does not without any custom config. I intend to record the sequence of terminal commands and submitting that
