### ISSUE TITLE
"Edit with vim in Windows Terminal" context menu option

### ISSUE THREAD

**Issue by kkuhle** [microsoft/terminal#9735]
# "Edit with vim in Windows Terminal" context menu option

- My apologies if this is already possible or already has been requested as I wasn't able to find it.

**Comment by zadjii-msft** [comment]
I'm thinking that the best way of addressing this will be with #492. That'll let you configure a "default terminal application" on Windows. That means your already existing "Edit with vim" context menu entries will open up in the Windows Terminal by default.
