### ISSUE TITLE
Tab reordering failed

### ISSUE THREAD

**Issue by JackZxj** [microsoft/terminal#9736]
### Windows Terminal version (or Windows build number)

10.0.19042.0 1.6.10571.0

### Steps to reproduce

I don't know.  I tried the version of MS Store and GitHub Release, but both of them could not reorder the TAB. I also upgraded from Windows1903 to Windows20H2 which is still useless.

My device：HP ProBook 440 G6 with Windows 10 Professional 

### Actual Behavior

In markdown

**Expected Behavior:**
I just want to reorder my tab like this:
![image](https://user-images.githubusercontent.com/48369326/69386670-208de380-0c78-11ea-9f2c-afa3894de3ef.gif)

**Actual Behavior:**
I dragged the tab bar, but it could not reorder:
![windows terminal](https://user-images.githubusercontent.com/26180598/113805786-b81fa380-9793-11eb-9f1b-3f0c519a5b25.gif)

**Comment by zadjii-msft** [comment]
Would you happen to be running the Terminal as an Administrator?

**Comment by JackZxj** [comment]
What's the diffrent between those? I launch it from the start menu. @zadjii-msft

**Comment by zadjii-msft** [comment]
I ask because tab reordering is explicitly disabled when running elevated. There are more details in https://github.com/microsoft/terminal/issues/6661#issuecomment-649895371, #4874, #3581. My second question is: Do you have UAC disabled? If so, then this will end up as a duplicate of #7754

**Comment by JackZxj** [comment]
@zadjii-msft Thanks a lot! This is really caused by UAC!
