### ISSUE TITLE
issue when i open settings in windows terminal 

### ISSUE THREAD

**Issue by adarshpajeesh09** [microsoft/terminal#9738]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Steps to reproduce

open terminal click on the dropdown menu and click settings

### Expected Behavior

to open settings

### Actual Behavior

it is searching json in microsoft store

this is what happening

[screen-capture.zip](https://github.com/microsoft/terminal/files/6269093/screen-capture.zip)

**Comment by zadjii-msft** [comment]
If you click on the "settings" button in the dropdown, the Terminal will attempt to open the settings file, `settings.json`. This will cause the OS to try and launch your configured `.json` file editor. This might be Visual Studio, or Notepad, or some other completely unexpected application. If there isn't a configured `.json` editor on your machine, then the OS will eventually show you the "How do you want to open this file" dialog.

> [!TIP]
> You can also use the settings UI to configure your settings if you are using [Windows Terminal Preview](https://aka.ms/terminal-preview). You can learn how to open the settings UI on the [Actions page](./customize-settings/actions.md#application-level-commands).
