### ISSUE TITLE
Can't delete azure cloud shell

### ISSUE THREAD

**Issue by matsmcp** [microsoft/terminal#9742]
### Windows Terminal version (or Windows build number)

10.0.20303.1 1.7.210226002

### Steps to reproduce

Try to delete the azure cloud shell

### Expected Behavior

The Azure cloud shell configuration gets deleted

### Actual Behavior

It cant be deleted since it's built in

For Customers that are legally prevented from using cloud services it's rather bad to have a mandatory config to a MS cloud service. Therefore it should be possible to delete it.

IT's also rather unpractical for AWS or Google users.

**Comment by zadjii-msft** [comment]
The Azure Cloud Shell is a ["dynamic" profile](https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles#hide-a-profile), which can be hidden with   

```json
"hidden": true
```

**Comment by matsmcp** [comment]
@zadjii-msft 
Hiding it doesn't prevent it from being in the config and so on so that didn't meet the need but you did solve it anyway by mentioning and linking dynamic profiles. 

By using "disabledProfileSources": ["Windows.Terminal.Azure"] in the config file we can prevent it from being created so that will solve the issue :)

**Comment by LoganDark** [comment]
On the newest version of Windows Terminal, it looks like your global settings are initialized with the defaults, and you can just completely delete the azure shell section and it disappears forever.
