### ISSUE TITLE
Progress state doesn't update correctly between panes

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9743]
1. Set the progress to indeterminate state in a pane.
2. Open a new tab. Note that the taskbar and tabs display as expected.
3. Switch back to the first tab. Note that the taskbar and tabs display as expected.
4. Open a new pane. Note that the tab and taskbar _still display the progress state!_ 
5. Switch to the second tab. Note that the taskbar and tabs display as expected.
6. Switch back to the first tab.  Note that the taskbar and tabs display as expected. (no progress, because the second pane does not have progress state)
7. Switch to the first pane. Note that the tab and taskbar _still have no progress state!_ 

Seemingly the progress state doesn't update when the active pane changes, only when the active tab does.

I might have a fix for this that's paired with #6842, but do we want to bite off a 30 file PR just for this fix?

**Comment by DHowett** [comment]
> do we want to bite off

Well, not exactly, but one takes the fix out of the 30 file PR ;)

**Comment by Don-Vito** [comment]
I guess I don't fully understand the logic, but I am not sure why `TaskbarProgressChanged` is called in `TerminalTab::Focus` rather than upon pane activation. I will create a draft PR with this :)
