### ISSUE TITLE
SSH session running neovim with custom color plugin, then resize causes whole terminal to turn bright yellow

### ISSUE THREAD

**Issue by horvatic** [microsoft/terminal#9747]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Neovim with the following plugins: 'https://github.com/joshdick/onedark.vim', 'vim-airline/vim-airline-themes', 'https://github.com/vim-airline/vim-airline'

### Steps to reproduce

Prerequisite: 
- An SSH box with Neovim Installed. 
  - It must have the following plugins: 'https://github.com/joshdick/onedark.vim', 'vim-airline/vim-airline-themes', 'https://github.com/vim-airline/vim-airline'

Steps:
1) ssh into box
2) start neovim
3) maximize window
4) exit neovim

### Expected Behavior

The normal color scheme of the terminal 

### Actual Behavior

Screenshot attached. The whole terminal color scheme is yellow

![image](https://user-images.githubusercontent.com/18469499/113966975-b38bd700-97f5-11eb-81ba-504a87015466.png)

**Comment by horvatic** [comment]
Running ```clear``` will remove the yellow. It seems to be a buffer issue. Redoing the steps will cause the issue to reappear, so  ```clear``` is more of a hack than a fix

**Comment by zadjii-msft** [comment]
Crazily enough, I think we've seen this before.

/dup #3848
