### ISSUE TITLE
Capability of Rearranging and Moving Tabs Accross Multiple Windows

### ISSUE THREAD

**Issue by pethaniakshay** [microsoft/terminal#9748]
It will be instrumental if Terminal's tabs can be rearranged/reordered and can be move across windows like the browsers tab.

As of now, Terminal's tab can't be dragged and reordered like tabs browser tabs. I often simultaneously work on the terminal's multiple tabs, and sometimes It becomes essential to rearrange the tabs for ease of switching the tabs.

**Comment by skyline75489** [comment]
Hi, this is being tracked at #1256
