### ISSUE TITLE
Turn all these old-school pointer/size things into `std::wstring_view` and `std::string_view` throughout the parser/adapter

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#975]
Yuck. We should file a follow on task to turn all these old-school pointer/size things into `std::wstring_view` and `std::string_view` throughout the parser/adapter...

_Originally posted by @miniksa in https://github.com/microsoft/terminal/diffs_

**Comment by dlong11** [comment]
The link is 404.

**Comment by zadjii-msft** [comment]
Uhg, thanks for catching that. Dunno why github horked it there.

The original issue with this discussion was https://github.com/microsoft/terminal/pull/891

**Comment by zadjii-msft** [comment]
Hey look, this was actually fixed by #3956

**Comment by miniksa** [comment]
> Hey look, this was actually fixed by #3956

Nice catch.
