### ISSUE TITLE
When displaying the empty space, windows terminal sometimes displays it as if it was selected with the mouse

### ISSUE THREAD

**Issue by grandemk** [microsoft/terminal#9750]
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

git bash

### Steps to reproduce

It seems to happen more frequently when I call programs that generate lots of lines of text but it can also happen on a simple ls. 

### Expected Behavior

The terminal doesn't show empty space as if it was selected (or white ?)

### Actual Behavior

The terminal sometimes shows empty space as if it was selected. Sometimes every new white space / space after a line return ? becomes white after the bug triggers and you need to shutdown the terminal and start another to get rid of the display bug.

![image](https://user-images.githubusercontent.com/5851912/114014017-757bcb00-9868-11eb-8eae-e621d19d4585.png)

**Comment by zadjii-msft** [comment]
Do you happen to have any more specific repro steps? "It happens sometimes" doesn't really give us a lot to work with. 
* What types of programs specifically?
* Are you resizing the Terminal at all?

"it can also happen on a simple ls" would be a great place to start, if you can get it to happen consistently.

This does look vaguely like #3848 (and the threads that are dupe'd to that one), but it's almost impossible to say for sure.

**Comment by grandemk** [comment]
The program doesn't seem to matter.
I had it happen in vim, with make, with ls or any program really.

I am not resizing the terminal.

I will do more tests. It happens frequently on my machine.
One intuition I want to verify is if the white lines start to appear when the output text reaches the last line of the terminal.

**Comment by grandemk** [comment]
Couldn't get the bug to happen yesterday. I'll retry this weekend.

**Comment by akapoorcern** [comment]
> 
> 
> Couldn't get the bug to happen yesterday. I'll retry this weekend.

Hi @grandemk I am also seeing this issue on the windows terminal. Were you able to solve this? I have to clear the screen each time this happens.
![image](https://user-images.githubusercontent.com/8407736/123336881-145cbd00-d564-11eb-8cd7-39d4bfa04a4e.png)
