### ISSUE TITLE
What's this visual artefact in the Settings UI?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9751]
... the little vertical scroll bar to the right of "Open JSON file" ... what is it?  It has always been there.  It's alive (buttons light up) but it doesn't do anything.  This morning I looked at 6 (or so) images of the whole Settings UI window and didn't see it.

![image](https://user-images.githubusercontent.com/61856645/114054141-95f25800-985d-11eb-9953-10fd9c96f399.png)

**Comment by zadjii-msft** [comment]
That's a good question, I've certainly never seen that before. Out of curiosity, what's this setting set to on your machine?

![image](https://user-images.githubusercontent.com/18356694/114056630-7ce6a880-9857-11eb-851c-6bb9870442e1.png)

**Comment by vefatica** [comment]
It's off.  Turning it on gets rid of the artefact.  But I don't like it's effect and I don't wish to leave it on.

**Comment by zadjii-msft** [comment]
Would you look at that:

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/3771

**Comment by vefatica** [comment]
There hasn't been much progress on it.  Has it been forgotten?

**Comment by DHowett** [comment]
Probably.
