### ISSUE TITLE
enhancement : right click on tab -> open a new terminal in the same folder

### ISSUE THREAD

**Issue by survivant** [microsoft/terminal#9755]
### Windows Terminal version (or Windows build number)

 10.0.21354.0

### Steps to reproduce

right click on a tab

### Expected Behavior

will be useful to be able to open a new terminal in the same folder as the one in that terminal.  Now when I open a new terminal it's open in my home folder instead

### Actual Behavior

the option is not there

**Comment by skyline75489** [comment]
Yeah we have #1912 which includes this.

**Comment by zadjii-msft** [comment]
More specifically, this was tracked in /dup #9373, which was implemented in #9388 and should be released in 1.8
