### ISSUE TITLE
Line break with errors in MongoDB Shell

### ISSUE THREAD

**Issue by petronaMX** [microsoft/terminal#9756]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Other Software

MongoDB shell version v4.4.4

### Steps to reproduce

1. Launch the MongoDB console in Windows Terminal Preview
2. Execute some statement that spans beyond the width of the console

### Expected Behavior

When reaching the maximum writing width, it is expected that a line break will be made, in order to continue writing.

### Actual Behavior

A line break is made, but it overlaps what is already written

**Comment by skyline75489** [comment]
A screenshot would be nice, you know.

**Comment by zadjii-msft** [comment]
@petronaMX would this happen to be #5797?

**Comment by petronaMX** [comment]
Hello, excuse me, it is the first time that I report something, I added the screenshots, but I don't know why they did not come out, I attach them again, and yes, apparently it is the same error that is mentioned in that issue [#5797](https://github.com/microsoft/terminal/issues/5797)
![MongoDB_Shell](https://user-images.githubusercontent.com/34947287/114187598-08fedb80-98fd-11eb-8980-2d62e23b11e3.JPG)
![Error](https://user-images.githubusercontent.com/34947287/114187629-10be8000-98fd-11eb-9dc8-c9088fe06f4d.png)

**Comment by zadjii-msft** [comment]
/dup #5797

Thanks for following up!
