### ISSUE TITLE
Help switch "/?" should print help in console window

### ISSUE THREAD

**Issue by jwlodek** [microsoft/terminal#9757]
# Description of the new feature/enhancement

Currently, when the windows terminal executable is ran with the "help" switch (`/?` or `-h`) a windows popup opens. I think it would be a better idea to have it print the help in the terminal window. This is how most terminal commands print help information, and the popup isn't wide enough to easily read the help info as well.

![image](https://user-images.githubusercontent.com/29227305/114117256-4db25480-98b4-11eb-95c6-53efd69212f4.png)

**Comment by skyline75489** [comment]
Thanks for the feedback! This is a known issue. We have #7258 for this
