### ISSUE TITLE
Add command line option to windows terminal to open window and execute command

### ISSUE THREAD

**Issue by jwlodek** [microsoft/terminal#9758]
# Description of the new feature/enhancement

It would be nice to have an option to start a windows terminal from the command line and immediately run a command in it. I use this feature a lot in other terminals for example to open a new terminal directly into an ssh session.

# Proposed technical implementation details (optional)

Something similar to the following would be good:

```
xfce4-terminal -x COMMAND
gnome-terminal -- COMMAND
start cmd.exe /C COMMAND
start powershell.exe /C COMMAND
```

example with cmd:

![image](https://user-images.githubusercontent.com/29227305/114117809-7b4bcd80-98b5-11eb-8891-2bb767a4d6d9.png)

**Comment by jwlodek** [comment]
Actually in `cmd`'s case, the `/K` switch is more what I would like to see, but both `/K` and `/C` would be welcome

**Comment by zadjii-msft** [comment]
That's a great idea! Good thing we already implemented this! 

https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows

You can use `wt -- python.exe`, or get more elaborate and do something like `wt new-tab python.exe ; split-pane wsl.exe`

**Comment by jwlodek** [comment]
Oh wow awesome! It didn't show up in the `/?` popup for me which is why I asked, sorry for the clutter
