### ISSUE TITLE
Unable to Drag and Drop files from Windows Explorer

### ISSUE THREAD

**Issue by rainerzufalldererste** [microsoft/terminal#9759]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

Windows Explorer (Windows 10 Version 2004)

### Steps to reproduce

1. Open a Command Prompt tab in Windows Terminal 1.6.10571.0
2. Open a folder in Windows Explorer
3. Drag a file from Windows Explorer onto the Windows Terminal Window

### Expected Behavior

The file path should appear at the cursor location, potentially wrapped in quotes if it contains a space. (I at least assume it should, since https://github.com/microsoft/terminal/issues/904#issuecomment-585892437 states that the feature has been implemented)

### Actual Behavior

Nothing happens. Before I let go of the mouse the "not-allowed" cursor is displayed.

**Comment by WSLUser** [comment]
Are you running Terminal as elevated or regular user when attempting this? Did you try doing both and still have issue?

**Comment by rainerzufalldererste** [comment]
I just learned something new about this issue. I've had it on two devices, but the root seems to be different.

**Device 1:**
The user is Administrator, UAC is disabled (and Windows Terminal therefore as well, displays "Administrator: " in the title bar, etc.)
However I haven't started Windows Terminal as administrator and Dragging and Dropping files does work with cmder, cmd and powershell no matter if they're elevated or not (obviously as long as they're not attached to the Windows Terminal).

**Device 2:**
The user is Administrator of the machine, but UAC is enabled (and Windows Terminal doesn't display "Administrator: " in the title bar)
Here it works perfectly if I use cmd via Windows Terminal, but it doesn't work at all if I use cmder via Windows Terminal.

I thought this was one and the same issue (because I usually use cmder via Windows Terminal), but have just realized that one of the two appears to be caused by cmder (via Windows Terminal) and one (potentially) by disabling UAC.
If this appears to be a duplicate of https://github.com/microsoft/terminal/issues/7754, feel free to close this issue.

**Comment by zadjii-msft** [comment]
> The user is Administrator, UAC is disabled

Yep, sure does sounds like a dupe to me, thanks!

/dup #7754
