### ISSUE TITLE
Community Guidance Requests no longer exist but still in contributing.md documentation

### ISSUE THREAD

**Issue by hessedoneen** [microsoft/terminal#9765]
Terminal Contributor's Guide states we should file a Community Guidance Request if we don't know how to do something. I think this might need to be updated, because Community Guidance Requests no longer exist as a type of Issue.

**Comment by zadjii-msft** [comment]
Huh, I'm not sure that type of issue _ever_ existed 😆 We should definitely just yank that from `CONTRIBUTING.md`.
