### ISSUE TITLE
runxamlformat doesn't work in the tools directory

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#9768]
### Windows Terminal version (or Windows build number)

7f5a19b627037353fc988755ed25e6ecb5bf4675

### Steps to reproduce

1. Checkout the _Windows Terminal_ source code.
2. Open a cmd shell.
3. Change to the `tools` directory.
4. Execute the `razzle.cmd` script to setup the dev environment.
5. Execute the `runformat.cmd` script to validate the source code formatting.

### Expected Behavior

The `runformat` script should execute successfully without any errors.

### Actual Behavior

I got an error generated by the xstyler utility.

```
ERROR(S):
  Option 'f, file' has no value.
```

This seems to be caused by the new `runxamlformat` script (added in PR #9589), which is now called from the `runformat` script. As far as I can tell, it only works correctly if run from the root of the project. Not a major problem, but it's more convenient to run those tools from the actual tools directory where you have easy autocomplete.

**Comment by zadjii-msft** [comment]
Weird. I surely messed something up.
