### ISSUE TITLE
TestWindowRename unit tests are failing

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#9769]
### Windows Terminal version (or Windows build number)

10.0.18363.1379, 7f5a19b627037353fc988755ed25e6ecb5bf4675

### Steps to reproduce

Build the app and run the unit tests (`runut.cmd`).

### Expected Behavior

All the tests should pass.

### Actual Behavior

The two `TestWindowRename` tests cause TAEF to crash.

TAEF: A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in process "TestHostApp.exe" (pid:11864).
Error: TAEF: [HRESULT 0x800706BE] A failure occurred while running a test operation: 'TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful'. (A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in the process hosting the test code while invoking a test operation.)
EndGroup: TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful [Failed]

TAEF: A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in process "TestHostApp.exe" (pid:9296).
Error: TAEF: [HRESULT 0x800706BE] A failure occurred while running a test operation: 'TerminalAppLocalTests::TabTests::TestWindowRenameFailure'. (A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in the process hosting the test code while invoking a test operation.)
EndGroup: TerminalAppLocalTests::TabTests::TestWindowRenameFailure [Failed]

**Comment by j4james** [comment]
In case this isn't easily reproducible, and you need more details, this is the full log leading up to the crash for `TestWindowRenameSuccessful`:

StartGroup: TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful
Verify: IsNotNull(settings0)
Construct the TerminalPage
Verify: SUCCEEDED(result)
Verify: IsNotNull(page)
Verify: IsNotNull(page->_settings)
Create() the TerminalPage
Verify: IsNotNull(page)
Verify: IsNotNull(page->_settings)
Create()'d the page successfully
Added a single newTab action
Verify: SUCCEEDED(result)
Wait for the page to finish initializing...
Verify: SUCCEEDED(waitForInitEvent.Wait())
...Done
Ensure we set the first tab as the selected one.
Verify: SUCCEEDED(result)
Verify: AreEqual(1u, page->_tabs.Size())
Verify: SUCCEEDED(result)
TAEF: A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in process "TestHostApp.exe" (pid:11864). 

And this is for `TestWindowRenameFailure`:

StartGroup: TerminalAppLocalTests::TabTests::TestWindowRenameFailure
Verify: IsNotNull(settings0)
Construct the TerminalPage
Verify: SUCCEEDED(result)
Verify: IsNotNull(page)
Verify: IsNotNull(page->_settings)
Create() the TerminalPage
Verify: IsNotNull(page)
Verify: IsNotNull(page->_settings)
Create()'d the page successfully
Added a single newTab action
Verify: SUCCEEDED(result)
Wait for the page to finish initializing...
Verify: SUCCEEDED(waitForInitEvent.Wait())
...Done
Ensure we set the first tab as the selected one.
Verify: SUCCEEDED(result)
Verify: AreEqual(1u, page->_tabs.Size())
Verify: SUCCEEDED(result)
TAEF: A crash with exception code 0xC0000005 occurred in module "TerminalApp.LocalTests.dll" in process "TestHostApp.exe" (pid:9296).

**Comment by zadjii-msft** [comment]
oh no, I'll take a look. Thanks!
