### ISSUE TITLE
Task: Remove unused methods in ConGetSet and SCREEN_INFORMATION

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#9771]
# Description of the new feature/enhancement

I've been investigating steps that could be taken to simplify the `ConGetSet` interface, with a view towards merging the `AdaptDispatch` and `TerminalDispatch` classes (#3849), and I noticed that the `GetConsoleCursorInfo` and `SetConsoleCursorInfo` methods are not actually used anywhere. While it's possible we may need something of similar functionality in the future, we wouldn't want it tied to a conhost-specific structure like `CONSOLE_CURSOR_INFO` if we're going to share the interface with `TerminalDispatch`, so I think it's probably best to just nuke them for now.

I also noticed that the `SCREEN_INFORMATION::GetScrollingRegion` is not used anywhere either. It was originally called from the `ScrollRegion` function, but that usage was removed in PR #2764, so I definitely think it's safe to delete this one.

# Proposed technical implementation details (optional)

If there are no objections, I would like to remove these methods.

**Comment by DHowett** [comment]
I love this.
