### ISSUE TITLE
Add tab and pane management controls to context menus where appropriate

### ISSUE THREAD

**Issue by proimage** [microsoft/terminal#9773]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

Not a bug; a feature request. Right-clicking on the various parts of the app do not even reveal the existence of panes, nor does it show all the tab management options available.

### Expected Behavior

I would expect that all app features would be discoverable via the context menu of various parts of the GUI. I would expect that the menu items would show their currently-bound hotkeys, in greyed-out text, right aligned next to each menu item (so we can learn both the available functions, and the hotkeys for those functions). This is common Windows program behavior.

### Actual Behavior

Minimal tab management actions were revealed, an no indication of pane management actions were shown. One should not have to poke around the settings `json` code to figure out what the app can do.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This sounds a lot like the gist of #5025 to me.

/dup #5025
