### ISSUE TITLE
GetCurrentConsoleFontEx unable to work normally

### ISSUE THREAD

**Issue by zmcj1** [microsoft/terminal#9774]
### Windows Terminal version (or Windows build number)

10.0.19043.906

### Other Software

In Windows Console(conhost)

### Steps to reproduce

        CONSOLE_FONT_INFOEX cfi;
        cfi.cbSize = sizeof(CONSOLE_FONT_INFOEX);
        ::GetCurrentConsoleFontEx(GetStdHandle(STD_OUTPUT_HANDLE), false, &cfi);

### Expected Behavior

cfi.dwFontSize represents the font size of current console.

### Actual Behavior

cfi.dwFontSize.X always eqauls to 0, but other structure members are in line with expectations.
//In fact, this should be a bug introduced by the recent Windows update.

**Comment by OpenGreatDream** [comment]
After many tests, this exception seems to be related to UseDx in the registry, When UseDx is 1, the behavior of  GetCurrentConsoleFontEx will produce an exception.

**Comment by OpenGreatDream** [comment]
I don’t know, whether the new version of Windows 10 has the UseDx option turned on by default.

**Comment by zadjii-msft** [comment]
Why are you setting `UseDx` at all? That shouldn't do anything on _any_ version of Windows...

**Comment by OpenGreatDream** [comment]
After debugging, the console program I was running modified the registry without authorization.
Thank you for your reply!

**Comment by DHowett** [comment]
Who authored this console application? UseDx is not supported and I bet that the author thought they were very clever.

**Comment by vefatica** [comment]
> Why are you setting UseDx at all? That shouldn't do anything on any version of Windows...

It does something here.  When set in HKCU\Console all console apps start with a larger font, and, as @OpenGreatDream said, GetCurrentConsoleFontEx always gives dwFontSize.X == 0.

**Comment by DHowett** [comment]
> 
> 
> > Why are you setting UseDx at all? That shouldn't do anything on any version of Windows...
> 
> It does something here. When set to 1 in HKCU\Console all console apps start with a larger font, and, as @OpenGreatDream said, GetCurrentConsoleFontEx always gives dwFontSize.X == 0.

`UseDx` shipped as an undiscoverable, **unsupported** feature in 10.0.19041. It enables conhost to use the same DirectWrite rendering engine as Terminal (trivia: it was first authored for conhost before Terminal existed). It is unsupported, and should not be used. Support requests indicating that `UseDx` is enabled will be rejected. :smile:

**Comment by DHowett** [comment]
Now, I would very much like to know which console application thinks it is so clever as to change the rendering engine conhost uses for a single version of Windows so that I can soundly chastise its author.

**Comment by OpenGreatDream** [comment]
I am writing a wrapper library for the Windows Console API: https://github.com/OpenGreatDream/MinConsole

Inadvertently I saw this article: https://devblogs.microsoft.com/commandline/understanding-windows-console-host-settings/
This inspired me, so I decided to start testing every console registration item.

I find something something interesting when I read the Windows Console source code: https://github.com/microsoft/terminal/blob/main/dep/Console/winconp.h

By Using this tool : (https://github.com/GiovanniDicanio/WinReg) I have conducted many tests, almost every console registry key, but I forgot to restore the registry! Next, when I opened the console, I found that the layout of the console output buffer changed significantly.
When i use again GetCurrentConsoleFontEx , I got this exception.

**Comment by OpenGreatDream** [comment]
I have realized the error of the problem, at the same time, I’m curious why you don’t update the existing Conhost renderer engine? Afraid of breaking compatibility with older Windows programs?

Check this out: https://github.com/OneLoneCoder/videos/blob/master/olcConsoleGameEngine.h

I currently think that the feasible way is to use DirectWrite and Direct2D technology to write a new console emulator to support my ambitions(Create a brand new terminal that supports most of the Windows Console API, so that most loyal fans of the Windows Console API like me can continue to enjoy using the Win32 API instead of the tiresome VT sequence to build awesome terminal games).😄😄😄

**Comment by DHowett** [comment]
> Create a brand new terminal that supports most of the Windows Console API, so that most loyal fans of the Windows Console API like me can continue to enjoy using the Win32 API (@OpenGreatDream)

I’m pretty sure that’s what Windows Terminal is. It uses Direct2D, it hosts console applications that use the Win32 console API, it is new, etc.!

**Comment by vefatica** [comment]
> I’m pretty sure that’s what Windows Terminal is. It uses Direct2D, it hosts console applications that use the Win32 console API, it is new, etc.!

 ... some of the Win32 console API anyway.  Is the scrollback buffer still off-limits to the API functions?

**Comment by DHowett** [comment]
The good and correct parts of the Win32 console API are available. The rest are APIs we should have jettisoned _years ago_.

**Comment by vefatica** [comment]
Do you know of software which will allow video capture of a Windows console?

**Comment by zadjii-msft** [comment]
Probably anything that you can use to record your screen? I think the Game Bar (on <kbd>Win+G</kbd>) has built-in recording. I personally use Screen2Gif for making gifs for PRs.

**Comment by vefatica** [comment]
But (at least here) the game bar won't appear if a console app is in the foreground.  What's a "PR"?

**Comment by zadjii-msft** [comment]
Meh yea, good point. I suppose the Game Bar has some logic in it to only allow recording of actual games or something.

A "PR" is a ["Pull Request"](https://github.com/microsoft/terminal/pulls)

**Comment by vefatica** [comment]
Thanks, Mike.  Screen2Gif is certainly easy enough to use.  Here's the sort of thing I miss.  I can only do it in TCC because, there, I have a plugin keystroke handler programming interface.  Ctrl+Delete does what you see (one line at a time);  Ctrl-Shift-Delete will do it one page at a time.  This is quite useful if I'm trying to [re]produce a sequence of steps and I botch one of them.

![buffer](https://user-images.githubusercontent.com/61856645/114433886-59419c00-9b90-11eb-9950-8bac1e3296f6.gif)

**Comment by DHowett** [comment]
This discussion is not suitable for this issue.

**Comment by vefatica** [comment]
Where shall I take it?

**Comment by DHowett** [comment]
File a new discussion issue or _find the original one where you and I talked about which APIs were supported_.

**Comment by zadjii-msft** [comment]
Hey so this thread came across my triage queue again, and it looks like it has run it's course. You shouldn't be using `UseDx` with conhost (even if it's supported in this repo, it doesn't ship in the OS). We've identified who was setting that flag. I don't believe there's any more discussion to be had here.
