### ISSUE TITLE
Throttle the bell sound (and visual indication) to avoid overloading audio stack

### ISSUE THREAD

**Issue by benthillerkus** [microsoft/terminal#9776]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Software
NVidia Game Ready Drivers v465.89
Windows Build 19042.867

### Hardware
NVidia Geforce GTX 970
I'm using HDMI on the GPU for video and audio

### Steps to reproduce

1. Trigger the bell repeatedly (for example by pressing backspace on an empty line in SSH)
2. Brace your ears

### Expected Behavior

Lots of Windows Alert sounds

### Actual Behavior

First the sounds will appear normally, but then it's just break down in loud audio glitching / corruption. To get rid of it you'll have to shut down the PC (restarting didn't help in my experience)

**Comment by DHowett** [comment]
Thanks for the report! I'm not sure how we're tripping over some driver issues, but I think it would be a good idea for us to limit the number of bells we emit (throttle them to 1/second or so?)

I'm going to repurpose this issue as the "throttle bells" task. I hope that it'll help!
