### ISSUE TITLE
doc/building.md Possibly Outdated

### ISSUE THREAD

**Issue by AKKaygin** [microsoft/terminal#9777]
>[/doc/building.md (9 April 2021)](https://github.com/microsoft/terminal/blob/b310b1cffc5df62f652ab1781d282ccfac3bb050/doc/building.md)
When using Visual Studio, be sure to set up the path for code formatting. This can be done in Visual Studio by going to Tools > Options > Text Editor > C++ > Formatting and checking "Use custom clang-format.exe file" and choosing the clang-format.exe in the repository at /dep/llvm/clang-format.exe by clicking "browse" right under the check box.

/dep/llvm thus /dep/llvm/clang-format.exe does not exist in the [last commit](https://github.com/microsoft/terminal/tree/b310b1cffc5df62f652ab1781d282ccfac3bb050) and [README.md](https://github.com/microsoft/terminal/blob/main/README.md#building-the-code) doesn't mention about this step. Either way one of these files needs to be updated.
(Additionally, do I need this file? If yes where can I find it?)
Thanks.

**Comment by skyline75489** [comment]
If you have successfully used `runformat` (see [Building in Cmd](https://github.com/microsoft/terminal/blob/b310b1cffc5df62f652ab1781d282ccfac3bb050/doc/building.md#building-in-cmd)), you should have `clang-format.exe` in `packages/clang-format.win-x86.10.0.0/tools`.

**Comment by DHowett** [comment]
Technically since VS _ships with clang-format 10 or 11_ it doesn't... actually matter that it's not using the specific one from our repo. Still, it's a bonus to make sure it keeps working. Thanks for the fix!
