### ISSUE TITLE
After changed the font, strange padding appeared

### ISSUE THREAD

**Issue by yanke1311** [microsoft/terminal#9778]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Other Software

vim 8.2

### Steps to reproduce

- change the font of wsl to Cascadia Code PL
- add a background
- remove the background

### Actual Behavior

![image](https://user-images.githubusercontent.com/23717792/114326413-3f3f9380-9b67-11eb-918a-2ced31ecb7c6.png)
the padding that I marked are strange, which never happend before.
And I found not only wsl have this problem, also powershell do as it, but I only changed the setting of wsl

**Comment by zadjii-msft** [comment]
That was actually always there - maybe in a different color, but it was definitely always there. You can remove it with: 

```json
"padding": "0"
```

in your profile.
