### ISSUE TITLE
Unable to find the selected font "Cascadia Mono"

### ISSUE THREAD

**Issue by tgriff** [microsoft/terminal#9786]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

My OS rebooted after an update. Windows Terminal may also have been updated. At any rate, now when I run Windows Terminal (and any time I open a new tab), I get the following error:
![image](https://user-images.githubusercontent.com/34492055/114411512-17e5c800-9b61-11eb-8818-3728d8764a8e.png)

I figured I could just set the font to "Consolas" permanently to get rid of the error message, but when I look at my settings.json file, I don't see where "Cascadia Mono" may have been configured. Other than setting the "fontSize" I haven't modified any settings w.r.t. fonts.

Also note that, as far as I am aware, I did not explicitly/intentionally uninstall "Cascadia Mono", although quick peek in "C:\Windows\Fonts" shows that it is no longer there.

### Expected Behavior

I don't expect to see any errors about fonts, especially considering I didn't explicitly configure any in my settings.json.

### Actual Behavior

Every time I open a new tab in Windows Terminal I get an error saying "Unable to find the selected font 'Cascadia Mono'. 'Consolas' has been selected instead. Please either install the missing font or choose another one."

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Unable+to+find+the+selected+font+%22Cascadia+Mono%22+) when filing new issues. This is already being tracked by another issue on our repo - please refer to #9375 for more discussion.

/dup #9375

**Comment by tgriff** [comment]
Apologies for the noise, it seems I only searched for Active issues when I was looking for dupes for this one.

**Comment by ismailhkose** [comment]
@zadjii-msft 

According to this message, the bug was resolved at Windows Terminal v1.7.1033.0, and the issue was closed, however I still see the same issue at Windows Terminal v1.10.2714.0
https://github.com/microsoft/terminal/issues/9375#issuecomment-819677048

![image](https://user-images.githubusercontent.com/353824/136893266-a1fe8855-9217-4acc-b113-56d68191c1da.png)
![image](https://user-images.githubusercontent.com/353824/136893300-c02f095e-270c-4c76-a805-8fe063ae7778.png)

**Comment by Rafagd** [comment]
Worked for me on v1.10.2714.0

**Comment by mugwhump** [comment]
> 
> 
> > Apparently this can be worked around by repairing the instalation in Settings -> Apps & Features -> Windows Terminal -> Advanced Options.
> 
> Worked for me, v1.11.2921.0

Interesting, didn't work for me in the exact same version.

**Comment by donfiguerres** [comment]
> Apparently this can be worked around by repairing the instalation in Settings -> Apps & Features -> Windows Terminal -> Advanced Options.
> 
> [#11451 (comment)](https://github.com/microsoft/terminal/issues/11451#issuecomment-938115593)

Thanks! This worked for me.
Version: 1.12.10732.0

**Comment by franciscoestevao** [comment]
> Apparently this can be worked around by repairing the instalation in Settings -> Apps & Features -> Windows Terminal -> Advanced Options.
> 
> [#11451 (comment)](https://github.com/microsoft/terminal/issues/11451#issuecomment-938115593)

The repair workaround fixed it for me 👍
Version: 1.12.10732.0

**Comment by bisk-e** [comment]
Had this issue occur on Version: 1.12.10982.0. Repairing it resolved the issue.

**Comment by LostInBrittany** [comment]
I still have the problem with version 1.12.10983.0.
Repairing or reset hasn't solved it 😢

**Comment by mreduar** [comment]
It happens every time I reboot my PC. With any font I choose I have this problem. I have to reinstall the font to get it to work. None of the above solutions or the FAQ's work. I am coming to think it is the antivirus corrupting the font, I don't know.

**Comment by ysertbas** [comment]
1.15.3466.0 I still have the problem.

**Comment by ysertbas** [comment]
> It happens every time I reboot my PC. With any font I choose I have this problem. I have to reinstall the font to get it to work. None of the above solutions or the FAQ's work. I am coming to think it is the antivirus corrupting the font, I don't know.

Seeing your comment I tried it a few times and yes. As soon as I reinstall the fonts, the problem is fixed, but when I reboot, it breaks again.
