### ISSUE TITLE
shift-click-drag resets selection start point

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9787]
To add to @Don-Vito's test cases :smile:

* [ ] click-drag (set selection), shift-click-drag (extend selection while dragging)

Right now, shift-click-drag resets the start point when the drag happens (but successfully extends when the click happens!)

**Comment by DHowett** [comment]
Marking P1 for servicing into 1.7, since we've taken all the other selection fixes in there.

Alternatively, I can back out all the selection changes from 1.7 and we'll go back to the thing we shipped in 1.6. It's got some known issues, but at least they're known ones!

**Comment by Don-Vito** [comment]
@DHowett - I will take a look later on today! I really hope we fix all in 1.7 rather than revert.

**Comment by Don-Vito** [comment]
On it.

**Comment by yamlCase** [comment]
Is there an option available to reset selection?  Those of us using tmux or vim with mouse support usually use "shift" to disable that app's mouse input so we can select and copy text straight to the Windows clipboard.  It is a minor but often frustration that trying to go back and select some more and different text just extends the previous selection.  Hitting esc will clear the selection for me, but 99% of the time I forget thus causing the frustration.

**Comment by Don-Vito** [comment]
@yamlCase - currently there is no option but ESC. I suggested to allow clearing the selection by shift-click on one of the selection ends (I know that ConEmu does this), but waiting for @DHowett to approve this idea.

**Comment by yamlCase** [comment]
Maybe a round-about way to achieve this behavior would be a 'deselect on copy' option while also having 'copyOnSelect' set to true.
