### ISSUE TITLE
Please make disk paths clickable (folders - opened in Windows Explorer, files - opened in a default app) like the URLs are made

### ISSUE THREAD

**Issue by BurstX** [microsoft/terminal#9793]
# Description of the new feature/enhancement

URLs now are clickable within the Terminal output. Once clicked, they are opened in the browser. Please make the same clickable behavior for disk paths, so that a clicked folder path is opened in Windows Explorer, and a clicked file path is opened in its respective default assigned app.

# Proposed technical implementation details (optional)
n/a

**Comment by zadjii-msft** [comment]
FYI, the terminal will make `file://` URIs clickable - see #7526

Broadly, this is tracked in #2671. Part of the trick is what regex is used to detect these file paths - something that works for Windows paths won't work for WSL/cygwin paths, and vice-versa. Furthermore, WSL paths by themselves wouldn't have any way of indicating _which_ WSL distro they belong to.

/dup #2671
