### ISSUE TITLE
Typing `renameWindow` key binding types into terminal prompt

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#9803]
### Windows Terminal version (or Windows build number)

1.8.1022.0

### Steps to reproduce

Add this key binding to your actions:

```
{ "command": { "action": "renameWindow", "name": "Foo" }, "keys": "ctrl+u" },
```

### Expected Behavior

Nothing should be typed into the prompt.

### Actual Behavior

It's renaming the window and also typing into my prompt.

![image](https://user-images.githubusercontent.com/48369326/114634909-7e113e80-9c78-11eb-94e9-a561bfdd32ea.png)

**Comment by Don-Vito** [comment]
On it.

**Comment by Don-Vito** [comment]
@zadjii-msft - you can assign this to me - so you need one reviewer less
I will finish it today.

**Comment by zadjii-msft** [comment]
Oh okay sure, it's definitely a oneline fix haha
