### ISSUE TITLE
How to change key value of <Alt> to 0x27 (i.e. <Meta>)?

### ISSUE THREAD

**Issue by ParadoxZW** [microsoft/terminal#9805]
I've used the following Python script to observe the behavior of `<Alt>` in Windows Terminal (WT, for short)
```Python
s = input()
print(s.encode().hex())
```
When I pressed `<Alt-x>` (before press Enter), I got 1b78, meaning the WT transport byte code `\0x1b\0x78` to the shell.

I'd like `<Alt-x>` works as `\0x27\0x78` in WT. How should I config to achieve that?

**Comment by zadjii-msft** [comment]
Why `\0x27\0x78`? Isn't `0x27` the single quote character `'`? 
![image](https://user-images.githubusercontent.com/18356694/114699891-7a1c0580-9ce6-11eb-82a5-54c1ddf53e87.png)

I think there's another issue floating around for "Alt sends meta, not escape", but is there any terminal emulator out there that lets you configure alt to send an _arbitrary_ character?

**Comment by DHowett** [comment]
On my machine, xterm seems to send `\xc3\xb8` to the shell when in `altIsNotMeta` mode. This is true regardless of the setting of `eightBitMeta`. This is different from `\x27\x78` as well.

**Comment by ParadoxZW** [comment]
> Why `\0x27\0x78`? Isn't `0x27` the single quote character `'`?
> ![image](https://user-images.githubusercontent.com/18356694/114699891-7a1c0580-9ce6-11eb-82a5-54c1ddf53e87.png)
> 
> I think there's another issue floating around for "Alt sends meta, not escape", but is there any terminal emulator out there that lets you configure alt to send an _arbitrary_ character?

<Alt-x> is `\0x27\0x78`, where `\0x78` means key `x`.
In your machine, the WT sends meta for key `<alt>`? Why does it send escape in my case？

**Comment by zadjii-msft** [comment]
Wait no, sorry, that was a screenshot of asciitable.com.

On my machine, <kbd>x</kbd>, <kbd>shift+x</kbd>, <kbd>ctrl+x</kbd>, and <kbd>alt+x</kbd> emit the following:
![image](https://user-images.githubusercontent.com/18356694/114860676-edd71480-9db1-11eb-9989-4108becb0354.png)

which is the same as `gnome-terminal`:
![image](https://user-images.githubusercontent.com/18356694/114860814-14954b00-9db2-11eb-84c5-2dd5eccd64e5.png)


I don't think _any_ emulator would ever send `\0x27` for <kbd>alt</kbd>

**Comment by ParadoxZW** [comment]
> On my machine, xterm seems to send `\xc3\xb8` to the shell when in `altIsNotMeta` mode. This is true regardless of the setting of `eightBitMeta`. This is different from `\x27\x78` as well.

I just want alt work as meta, rather than `^[`. How should I config in the WT.

**Comment by zadjii-msft** [comment]
So, we don't currently have that setting. There's also a lot of discussion over in #6722 on this topic already. The summary:

> Alright, I did a quick investigation of a few of our competitors.
> 
> It looks like gnome-terminal (vte) and konsole don't offer 8-bit meta mode any longer.
> 
> Given that it'll be really difficult to support and keep our core tenet of supporting more than just ASCII, and that the number of applications that are going to require it will trend towards zero with the inexorable march of time, I'm going to close this one out as, regrettably, **Won't Fix**
> 
> It also seems like it might be impossible for us to support. Windows applications generally receive UTF-16 or "native codepage" encoded input. Many of them, however, immediately convert that input to UTF-8. We can't encode an unjacketed character >= 0x80 (high bit set) in UTF-8 and expect it to come across as a high bit set in a 7-bit ASCII glyph through all of the cross-process communication channels that Windows requires.
> 
> Since WSL is just a Windows application, at the end of the day, it has to follow suit. We already have an issue where we can't send mouse coordinates using the legacy system >= 93 because they would require a high bit!


/dup #6722
