### ISSUE TITLE
Space becomes    in Windows Termial  powerline

### ISSUE THREAD

**Issue by zhangbowen-github** [microsoft/terminal#9806]
### Windows Terminal version (or Windows build number)

 Microsoft Windows NT 10.0.19041.0  ， Windows Terminal : 1.6.10571.0

### Steps to reproduce

font is  Cascadia Code PL
PSVersion     5.1.19041.610
Windows Terminal  Version   1.6.10571.0
```json

{
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
                "acrylicOpacity" : 0.7,
                "colorScheme" : "Campbell",
                "cursorColor" : "#FFFFFD",
                "fontFace" : "Cascadia Code PL",
                "useAcrylic" : true
            },
```

### Expected Behavior

Normal Space  in  powershell.exe
![image-20210414173814189](https://gitee.com/zhangbowen-1/my-gallery/raw/master/img/image-20210414173814189.png)

### Actual Behavior

Space becomes    in Windows Termial 
![image-20210414172703793](https://gitee.com/zhangbowen-1/my-gallery/raw/master/img/image-20210414172703793.png)

**Comment by zadjii-msft** [comment]
@zhangbowen-github Could you share your powerline config? I think that's actually supposed to be a "delta" character, or at least outlook thinks so:

![image](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)

So maybe that's just a character missing from Cascadia Code PL. Impossible to know for sure without knowing what the actual character is supposed to be

**Comment by zhangbowen-github** [comment]
> @ zhangbowen-github您能分享您的电力线配置吗？我认为这实际上应该是一个“三角形”字符，或者至少外表如此认为：
> 
> ![图像](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)
> 
> 因此，也许这只是Cascadia Code PL中缺少的一个字符。在不知道实际字符应该是什么的情况下不可能肯定地知道

**Comment by zhangbowen-github** [comment]
> @ zhangbowen-github您能分享您的电力线配置吗？我认为这实际上应该是一个“三角形”字符，或者至少外表如此认为：
> 
> ![图像](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)
> 
> 因此，也许这只是Cascadia Code PL中缺少的一个字符。在不知道实际字符应该是什么的情况下不可能肯定地知道

**Comment by zhangbowen-github** [comment]
> @ zhangbowen-github您能分享您的电力线配置吗？我认为这实际上应该是一个“三角形”字符，或者至少外表如此认为：
> 
> ![图像](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)
> 
> 因此，也许这只是Cascadia Code PL中缺少的一个字符。在不知道实际字符应该是什么的情况下不可能肯定地知道



> @zhangbowen-github Could you share your powerline config? I think that's actually supposed to be a "delta" character, or at least outlook thinks so:
> 
> ![image](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)
> 
> So maybe that's just a character missing from Cascadia Code PL. Impossible to know for sure without knowing what the actual character is supposed to be

How to view pwerline config?

**Comment by zhangbowen-github** [comment]
> @zhangbowen-github Could you share your powerline config? I think that's actually supposed to be a "delta" character, or at least outlook thinks so:
> 
> ![image](https://user-images.githubusercontent.com/18356694/114704290-0ed53200-9cec-11eb-851d-02e2ddc6750b.png)
> 
> So maybe that's just a character missing from Cascadia Code PL. Impossible to know for sure without knowing what the actual character is supposed to be
Solved the problem !
![image](https://user-images.githubusercontent.com/55389796/114845441-56ec7580-9e0e-11eb-8c6c-d2512fdc7bf8.png)
In this document  https://ohmyposh.dev/docs/fonts/
I changed the font to   Meslo LGM NF
```json
"fontFace" : "MesloLGM Nerd Font"
```

**Comment by zhangbowen-github** [comment]
This question comes from  Cascadia Code PL   in  Oh my Posh  V3 ， Oh my Posh  V3  prefers  Nerd Fonts 😕

**Comment by zadjii-msft** [comment]
Ah yep, that'll do it. You'll need the Nerd Fonts version of Cascadia Code (or whatever font you choose)
