### ISSUE TITLE
unicode typing problem

### ISSUE THREAD

**Issue by ghost1372** [microsoft/terminal#981]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.116]   
Windows Terminal version (if applicable):latest commit

```

# Steps to reproduce

Put the keyboard language in Persian And type

# Expected behavior
Type Without text resizing and changing text location

# Actual behavior

When typed, the size of the text changes and the location changes
[Untitled Project.zip](https://github.com/microsoft/terminal/files/3217496/Untitled.Project.zip)

please watch this video

**Comment by zadjii-msft** [comment]
As excited as I am to download that zip, I think that without even watching the video, this is a dupe of #538
