### ISSUE TITLE
[DefApp] TerminalHandoff does not hook up signal channel properly, resize events are ignored

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9810]
### Windows Terminal version (or Windows build number)

1.9

### Steps to reproduce

Launch a console application in Terminal via def. app.

### Actual Behavior

Resizing the terminal does not resize the backing buffer.

**Comment by miniksa** [comment]
#10170 finished hooking up this channel. I missed it in the kerfluffle. #9811 will handle setting up first size on connection
