### ISSUE TITLE
Open in Windows Terminal not using app alias

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9819]
### Windows Terminal version (or Windows build number)

Microsoft Windows 10 Pro for Workstations10.0.19042.928 (2009, 20H2)

### Steps to reproduce

I just installed WindowsTerminal 1.7.1033.0 and 1.8.1033.0, the latter being the new preview.  My app alias points to the preview.  "Open in Windows Terminal" starts 1.7.1033.0.  It may be that this behavior is not new and I'm noticing it for the first time.  Is it as expected?

### Actual Behavior

See above.

**Comment by DHowett** [comment]
The versioned shell extension launches the version of Terminal that it was packaged with. It does not launch your preferred version. You probably have one menu entry with the normal icon and one with the preview icon.

This is by design as of #9510.

**Comment by vefatica** [comment]
I don't quite understand. I uninstalled both and reinstalled only the preview.  Now I don't have "Open in Windows Terminal".  Is that expected?

**Comment by DHowett** [comment]
That's not expected, but also not something we can exactly help. Explorer has some cache that it uses for shell extension availability, and I suspect that when it gets rebuilt things will settle. Terminal _only_ registers to say "I have a shell extension" and everything after that is up to the shell.

**Comment by DHowett** [comment]
(ugh. another MSIX issue. :smile:)

**Comment by vefatica** [comment]
> I uninstalled both and reinstalled only the preview. Now I don't have "Open in Windows Terminal".

And now, a couple hours later, I (re)installed 1.7.1033.0 and I have "Open in ..." again (while the alias still points to the preview).  Does the Preview have a context menu handler and an installer for it?

**Comment by DHowett** [comment]
Yes, both have context menu handlers. Pre and Stable use the same mechanism--namely, the declarative app manifest--to announce their shell extensions. All of the _processing_ for those registrations happens completely out of our control, as is intended.

FYI- With the three versions, my shell does show them all (it is rather a lot)

![image](https://user-images.githubusercontent.com/189190/114778552-9d70a000-9d3a-11eb-9138-3c6116bd3be0.png)

**Comment by vefatica** [comment]
I went through the whole process again ... uninstalled both ... installed the preview ... no context menu ... installed the stable version ... context menu.  To me, it doesn't look like the two behave the same.

Can anything be done about settings.json being deleted when you uninstall?  I was lucky; I also had a settings.json for the un-packaged installation (in "C:\Users\vefatica\AppData\Local\Microsoft\Windows Terminal\").  Without that I would have had to do quite a bit of work.

**Comment by vefatica** [comment]
Hmmm!  I've had both stable and preview installed for a long time (maybe a year or so).  I have never seen multiple "Open in Windows Terminal" context menu items.

**Comment by DHowett** [comment]
> Can anything be done about settings.json being deleted when you uninstall?

I wish.

> This is by design as of #9510.

9510 only shipped in 1.7.1033 and 1.8.1032.
