### ISSUE TITLE
Add Ctrl+W handling

### ISSUE THREAD

**Issue by hello-smile6** [microsoft/terminal#9823]
# Description of the new feature/enhancement
Allow `Ctrl+W` to close a tab, similar to the behavior of Chromium

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
You can do this yourself within settings.json. Just bind the keybinding to the Close Tab Action.

**Comment by DHowett** [comment]
indeed!

**Comment by zadjii-msft** [comment]
For the record, the docs can be found here: https://docs.microsoft.com/en-us/windows/terminal/

Also, closing a pane is already bound to `ctrl+shift+w`, you'll find that'll probably work for you 😉

**Comment by hello-smile6** [comment]
Oh!
