### ISSUE TITLE
Settings: Add links to documentation in the settings UI 

### ISSUE THREAD

**Issue by Armin2208** [microsoft/terminal#9824]
The new Windows Terminal version has a settings UI. Great! But in a regular/typical window size it contains too much blank space, as you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/32982430/114781237-b7c96e80-9d78-11eb-80e3-638ff5c3c8f7.png)

I mostly use my Terminal in a medium size to complete quick tasks. Maximizing or resizing the window just to have a better view of settings is inconvenient. 

- [ ] Add help links or link to documentation at the right side, just like system settings. 
- [ ] Make the footer smaller. 

~~My idea would be to expand the hamburger menu much sooner at smaller window sizes. Like showing it already on the 120x30 size. Because the main content of the settings doesn't fill much area in the width anyways. This is the minimum size to have an always expanded hamburger menu and you can see: there is still room left.~~
![image](https://user-images.githubusercontent.com/32982430/114782148-e431ba80-9d79-11eb-9fbc-7c8f2a3d98e9.png)

My screenresolution is 2736x1824 and I use 200% scaling (device: Surface Pro 7).

**Comment by zadjii-msft** [comment]
@cinnamon-msft this seems like a question up your alley

**Comment by cinnamon-msft** [comment]
We could possibly shrink the size of the footer for a more compact look. We're following the UWP design guidelines when it comes to the main page content. We are planning to add helpful links to the right side of the pages, to help fill in the space and provide links to documentation.

Maybe this issue can be repurposed to: "Add links to documentation in the settings UI" ?

**Comment by Armin2208** [comment]
Hi!

Shrinking the footer would be a great step forward :)

It's important to follow the UWP design guidelines, I understand. So there's nothing we can change about this. But it's still sad to have so much space in the settings, just because the hamburger menu is shrinking down too early. And I don't think having a three columns UI makes the app great for users (same goes for windows settings btw). 

But hey, it would fit to the settings app and microsoft style, so we can rename this issue.

**Comment by Armin2208** [comment]
Closed, because new Settings UI doesn't need this
