### ISSUE TITLE
Settings: Alt + F4 doesn't work / doesn't respond

### ISSUE THREAD

**Issue by Armin2208** [microsoft/terminal#9825]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Open Windows Terminal -> Open the new Windows Terminal settings page -> run the keyboard shortcut Alt + F4 -> nothing happens

### Expected Behavior

Windows Terminal should show the same dialog as clicking on the close-button of the window. Asking the user if he realy wants to close all tabs (or maybe even asking if he wants to throw away his settings, because he needs to save before closing).

### Actual Behavior

Pressing the keyboard Shortcut Alt + F4 while settings are open makes just nothing.

**Comment by skyline75489** [comment]
I think this is /dup #8767 #9042

**Comment by zadjii-msft** [comment]
Yep. We missed this in #8885.

/dup  #8767
