### ISSUE TITLE
windows-terminal 1.7.1033.0 flashback

### ISSUE THREAD

**Issue by DoveBoy** [microsoft/terminal#9829]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

Use `scoop update windows-terminal` to `1.7.1033.0`, Open application flashback. The previous version `1.6.10571.0` of the program worked properly

### Expected Behavior

![image](https://user-images.githubusercontent.com/19201447/114796213-fd128e00-9dc2-11eb-8915-cf44ddcf1906.png)

### Actual Behavior

Please fix

**Comment by DHowett** [comment]
/dup #9821 

Scoop installs terminal in an unsupported way. We're working on fixing it, but we have _never_ supported the wya that they installed us.
