### ISSUE TITLE
Add a profile setting to specify the title for the tab

### ISSUE THREAD

**Issue by DJackman123** [microsoft/terminal#983]
# Summary of the new feature/enhancement

Right now when I create a tab the title displayed in the tab is "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe", which is really long (and is even longer if I'm running as administrator and has the "Administrator:" prefix.  I can change the title with a PowerShell command, but this is really klunky. It would be much better if I could specify in the profile what I want the title text to be.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
This'll be #608. Thanks!
