### ISSUE TITLE
setfont - Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by dotnetCarpenter** [microsoft/terminal#9830]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

Ubuntu 20.10
setfont  (inside WSL2) - man page says "11 Feb 2001"

### Steps to reproduce

Various commands will all lead to  `Couldn't get a file descriptor referring to the console`.

+ `setfont`

+ `sudo apt install  cmatrix-xfont`
    + `setfont cmatrix`
    + `setfont -m /usr/share/fonts/X11/misc/mtx.pcf.gz`

+ `sudo apt install  cmatrix`
    + `cmatrix -l`

### Expected Behavior

That `setfont` can get a file descriptor referring to the console.

### Actual Behavior

Running as root appears to work but rendered font consist purely of `^` and `+` characters.

`sudo setfont -m /usr/share/fonts/X11/misc/mtx.pcf.gz && sudo cmatrix -l`

![image](https://user-images.githubusercontent.com/43763/114800147-6d0c1e80-9d99-11eb-9d5d-88e5962a20be.png)

**Comment by dotnetCarpenter** [comment]
According to @space-pagan https://github.com/abishekvashok/cmatrix/issues/81#issuecomment-740200979, then there is a fork of `cmatrix` that works on multiple distros.

But in Microsoft Terminal [that fork](https://github.com/space-pagan/cmatrix) renders very different characters than expected.

After building and installing beforementioned fork:

```
cmatrix -l
Couldn't get a file descriptor referring to the console
 There was an error running setfont. Please make sure the
 setfont program is in your $PATH.  Try running "setfont matrix" by hand.
```

```
setfont cmatrix
Couldn't get a file descriptor referring to the console
```

```
sudo setfont cmatrix
Bad input file size
```

```
sudo cmatrix -l
```

![image](https://user-images.githubusercontent.com/43763/114801200-84e4a200-9d9b-11eb-8a79-48a41e6752a8.png)

**Comment by DHowett** [comment]
Sorry, no terminal emulator except for the Linux framebuffer console and its derivatives (and perhaps the Linux VGA console) supports PCF console fonts. Somewhat by design, but somewhat because setfont is just Linux-console-specific and they’re not using a standard like DRCS for downloadable character sets.

we have a backlog item tracking DRCS fonts, which I bet will bring out the right characters. 

/dup #9164
