### ISSUE TITLE
Startup Crash Frequently 

### ISSUE THREAD

**Issue by mingsxs** [microsoft/terminal#9831]
### Windows Terminal version (or Windows build number)

Windows build number: 18363.1440 Windows Terminal version: 1.7.1033.0

### Other Software

Nothing

### Steps to reproduce

Just double click it will crash and exit, very little chance it can start up successfully.

### Actual Behavior

double click to open and then it crashes and exits.

**Comment by mingsxs** [comment]
[](url)[](url)

**Comment by mingsxs** [comment]
Sorry that I closed it accidentally.

**Comment by mingsxs** [comment]
![Uploading Screenshot 2021-04-15 140840.png…]()

**Comment by mingsxs** [comment]
![Screenshot 2021-04-15 140840](https://user-images.githubusercontent.com/46848431/114822789-2cda8980-9df5-11eb-926b-64a272c332a4.png)

**Comment by mingsxs** [comment]
You can see clearly from the screenshot, after opening the terminal, the window leaves blank and soon it will exit with No Response.

**Comment by igitur** [comment]
@mingsxs Same here. I installed Terminal using scoop package manager. I'm just wondering how you installed it. Maybe that's relevant here.

**Comment by godeater** [comment]
Almost the same symptom here, except mine has never launched successfully at all. I just get the brief appearance of the white window, and then it vanishes again.
I can't install via the Windows Store as on a corporate network which blocks it - so I installed the .msixbundle manually via PowerShell.

**Comment by igitur** [comment]
If I uninstall my current instance (that I originally installed through scoop package manager) and I download the .msixbundle file from https://github.com/microsoft/terminal/releases/tag/v1.7.1033.0 and install it manually using `Add-AppPackage` in PowerShell, then Windows Terminal opens successfully.

If I remove it again using `Remove-AppPackage` and reinstall it via scoop package manager, it fails again. So I'm guessing something is wrong with the scoop install script.

**Comment by justinkb** [comment]
> If I uninstall my current instance (that I originally installed through scoop package manager) and I download the .msixbundle file from https://github.com/microsoft/terminal/releases/tag/v1.7.1033.0 and install it manually using `Add-AppPackage` in PowerShell, then Windows Terminal opens successfully.
> 
> If I remove it again using `Remove-AppPackage` and reinstall it via scoop package manager, it fails again. So I'm guessing something is wrong with the scoop install script.

https://github.com/lukesampson/scoop-extras/blob/master/bucket/windows-terminal.json

doubtful anything is wrong with the script, most likely it's just intermittent failures and it happened to work a few times when you installed it manually

**Comment by zadjii-msft** [comment]
/dup #9821

Scoop installs terminal in an unsupported way. We're working on fixing it, but we have never supported the way that they installed us.

**Comment by mingsxs** [comment]
@igitur Hey there, yeah, I do install with scoop, didn't release that it could be relevant to it. Thanks for this information
