### ISSUE TITLE
Open a new tab in the current Directory

### ISSUE THREAD

**Issue by ghost1372** [microsoft/terminal#9832]
# Description of the new feature/enhancement

Consider that the terminal is running in a Directory, Now We need to open another terminal in the same Directory.
Is this feature currently supported? if not, Can you implement it?
It would be great if we could open a new tab that opens in the current Directory.

# Proposed technical implementation details (optional)

**Comment by skyline75489** [comment]
There's a ton of discussions about this in #3158 . The short answer is: yes, it's possible to do this. Unfortunely you'll need to tweak the settings of you shells. You can checkout https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033 to see how it's done for PowerShell, as a starter. Theoretically it should work with any shell.

**Comment by ghost1372** [comment]
@skyline75489  thank you, so i close this issue
