### ISSUE TITLE
unfocusedAppearance not working as expected.

### ISSUE THREAD

**Issue by pnunn** [microsoft/terminal#9834]
### Windows Terminal version (or Windows build number)

Version: 1.8.1032.0

### Steps to reproduce

This profile`setting.

```json
{
                "acrylicOpacity": 0.96999999999999997,
                "antialiasingMode": "cleartype",
                "bellStyle": "visual",
                "colorScheme": "Tango Dark",
                "cursorShape": "vintage",
                "experimental.retroTerminalEffect": false,
                "fontFace": "FiraCode NF Retina",
                "fontWeight": "normal",
                "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
                "hidden": false,
                "name": "Ubuntu-18.04",
                "source": "Windows.Terminal.Wsl",
                "useAcrylic": true,
                "unfocusedAppearance": {
                    "acrylicOpacity": 0.1,
                    "useAcrylic": true,
                    "backgroundImageOpacity": 0.2,
                    "colorScheme": "Tango Light",
                    "backgroundImage": "C:\\Users\\pjn_o\\Documents\\MarketDispatch\\Market Dispatch LOGO.jpg",
                    "backgroundImageStretchMode": "uniform"
                }
            },
```

### Expected Behavior

A terminal looking something like this unfocused (this is the focused settings)

<img width="714" alt="Screenshot 2021-04-15 162900" src="https://user-images.githubusercontent.com/1034315/114824264-feb27500-9e07-11eb-93a3-1404a813372c.png">

### Actual Behavior

The background goes white instead of dark... the other bits seem to work though.

<img width="718" alt="Screenshot 2021-04-15 163003" src="https://user-images.githubusercontent.com/1034315/114824162-d9256b80-9e07-11eb-9d28-f3979694bb2d.png">

**Comment by zadjii-msft** [comment]
Doesn't "Tango Light" have a white background by default?

https://github.com/microsoft/terminal/blob/cdbcc174580dec27cee9cd93e81e7ff4210fc8bf/src/cascadia/TerminalSettingsModel/defaults.json#L255-L258

So this _seems_ like it's working as expected. It's changing the scheme to tango light, _including_ the `background` color

**Comment by pnunn** [comment]
How embarrassing... yep.. should be tango dark.. 

Now, what I'd really like is for the background to go almost transparent when its not focused but try as I might with acrylicOpacity values, I can't seem to get the desktop to show through. Is that even possible? I tried values from 0 to 1 with no real change.

Thanks for pointing out the stuff up with the theme though.

**Comment by zadjii-msft** [comment]
Glad I could help!

Transparency already doesn't work on unfocused windows, so it didn't make sense to add that as a property in `unfocusedAppearance`. We're tracking adding support for that in #7158 though, so go give that a 👍 and subscribe if you're interested.
