### ISSUE TITLE
Tab closes on middle button mousedown rather than full click

### ISSUE THREAD

**Issue by lbmaian** [microsoft/terminal#9836]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

1. Open a new tab
2. Middle button mousedown on the tab itself

### Expected Behavior

Tab does not close until middle button mouseup on the same tab occurs, i.e. a full middle button click action.

This is the most typical behavior for tab closing in tabbed applications (web browsers, IDEs, etc.).

### Actual Behavior

Tab closes immediately on middle button mousedown, without waiting for middle button mouseup on the same tab.

**Comment by skyline75489** [comment]
Huh it is true. I can easily repro this. Perhaps we should move this to upstream repo.

**Comment by zadjii-msft** [comment]
This might not be on WinUI. Looks like we're the one's that did it on PointerPressed, not PointerReleased. See `TerminalPage::_OnTabClick`

**Comment by lbmaian** [comment]
Also something to point out:

Most tabbed interfaces (including Chrome, Edge, Firefox, Visual Studio Code) require that mousedown happen on the button, then subsequent mouseup on the same button, allowing pointer to move outside the button while button is still held down as long as it returns to the button when the mouseup happens.

Others (including Notepad++) only require mouseup on the button, without requiring mousedown on that button, i.e. pointer can be off the button when mousedown happens, move pointer over button, then mouseup.

Aside: I found Visual Studio (not VS Code) tabs also close on middle mousedown.
