### ISSUE TITLE
Settings UI Startup screen - Launch mode tooltip/help text is the same for all options

### ISSUE THREAD

**Issue by jeanfrancoislarente** [microsoft/terminal#9837]
### Windows Terminal version (or Windows build number)

10.0.19042 Build 19042

### Steps to reproduce

Launch latest Terminal preview version from App Store
Browse to settings UI and click on Startup
Hover over each of the "Launch mode" options.

### Expected Behavior

Text that accurately describes the behavior of each selection

### Actual Behavior

Same text for all options

**Comment by zadjii-msft** [comment]
Weirdly enough, this is kinda already being tracked in https://github.com/microsoft/terminal/issues/8769#issuecomment-778420188. We can't easily set individual tooltips on the individual radio buttons, only on the entire group. 

/dup #8769

**Comment by jeanfrancoislarente** [comment]
Thanks @zadjii-msft  - I searched before creating the issue but clearly I didn't use the correct terms!
