### ISSUE TITLE
"Open in Windows Terminal" doesn't work on renamed drive letter

### ISSUE THREAD

**Issue by prabhumns** [microsoft/terminal#9838]
### Windows Terminal version (or Windows build number)

1.8.1032.0

### Other Software

Create and format hard disk partitions

### Steps to reproduce

Change the drive letter to any one of the attached drives and check the context menu

### Expected Behavior

The 'Open Windows Terminal Here' option should exist even after a drive letter has been changed.

### Actual Behavior

I have recently re-installed windows insider version and it came with windows terminal (non preview) already installed in it. I can see 'Open Windows Terminal here' option in the context menu of folders (even in background). Then I installed windows terminal preview in my system, then the context menu option is opening the terminal preview version instead of non preview version. After a couple of days I re assigned drive letter for non windows drives, from then I cant see 'open windows terminal here' option in the context menu (even in the shift + right click context menu).

**Comment by zadjii-msft** [comment]
> After a couple of days I re assigned drive letter for non windows drives, from then I cant see 'open windows terminal here' option in the context menu (even in the shift + right click context menu).

Hmm. Lemme reach out to my file explorer contact, see if he has ever heard of anything like this. 

By any chance, have you restarted your PC since updating the drive letter? `explorer.exe` is notoriously finicky about caching the context menu entries. Maybe it's possible it's just a bad cache...

**Comment by prabhumns** [comment]
I restarted multiple times since then

**Comment by zadjii-msft** [comment]
Okay, I've filed a bug internally. This is now MSFT:32535359

**Comment by zadjii-msft** [comment]
Huh. This came back to us internally 😕 

Sorry it's been a LONG time OP. What OS version are you on/? There's been a pile of bugs with context menus on drive letters that I think were all sorted out in the Windows 11 timeframe...

**Comment by zadjii-msft** [comment]
> After a couple of days I re assigned drive letter for non windows drives, from then I cant see 'open windows terminal here' option in the context menu (even in the shift + right click context menu

Wait, you mean for some file like `f:\foo\bar`, where `f:\` is some drive that used to be `d:\`, that doesn't work anymore? 

#6654 suggests that Terminal still won't ever work on any _drive_ directly in explorer, but it should work for any subdirectory in a drive...
