### ISSUE TITLE
Pasting of portions of data devided by "\" stop working correctly in 3.2.0(0.340/5/3)  ( was ok on 3.1.7(0.340/5/3)).

### ISSUE THREAD

**Issue by kas1e** [microsoft/terminal#9839]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.14393]

### Other Software

basic Win7 clipboard and Cygwin's bash running via default cygwin.bat

### Steps to reproduce

1. Run "cygwin.bat"
2.  Just copy that part of text data to the Windows clipboard:

```
mkdir build
cd build 

cmake \
-DCMAKE_SYSTEM_NAME=Generic \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER="/usr/local/amiga/bin/ppc-amigaos-gcc" \
-DCMAKE_CXX_COMPILER="/usr/local/amiga/bin/ppc-amigaos-g++" \
-DCMAKE_CXX_FLAGS="-Wno-deprecated -Wno-deprecated-declarations -Wno-narrowing" \
-DCMAKE_LINKER="/usr/local/amiga/bin/ppc-amigaos-ld" \
-DCMAKE_AR="/usr/local/amiga/bin/ppc-amigaos-ar" \
-DCMAKE_RANLIB="/usr/local/amiga/bin/ppc-amigaos-ranlib" \
-DCMAKE_FIND_ROOT_PATH="/usr/local/amiga/ppc-amigaos/" \
-DUSE_FRIBIDI=0 \
-DUSE_WIIUSE=0 \
-DOPENAL_INCLUDE_DIR="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/include/AL/" \
-DOPENAL_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libopenal.a" \
-DOGGVORBIS_VORBIS_INCLUDE_DIR="/usr/local/amiga/ppc-amigaos/SDK/Local/common/include/vorbis" \
-DOGGVORBIS_OGG_INCLUDE_DIR="/usr/local/amiga/ppc-amigaos/SDK/Local/common/include/ogg" \
-DOGGVORBIS_VORBIS_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libvorbis.a" \
-DOGGVORBIS_VORBISFILE_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libvorbisfile.a" \
-DOGGVORBIS_OGG_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libogg.a" \
-DCURL_INCLUDE_DIR="/usr/local/amiga/ppc-amigaos/SDK/Local/common/include/curl" \
-DCURL_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libcurl.a" \
-DOPENGL_INCLUDE_DIR="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/include/GL/" \
-DOPENGL_gl_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libgl4es.a" \
-DPTHREAD_LIBRARY="/usr/local/amiga/ppc-amigaos/SDK/Local/newlib/lib/libpthread.a" \
..
```

3. Click on Cygwin'ss terminal window, and choose "paste".

Now, this part is not placed correctly and interrupts in the middle.

On 3.1.7(0.340/5/3) and on older ones it pasted correctly, like one single paste.

### Expected Behavior

One single paste, and not a few different ones.

### Actual Behavior

Broken pasting in the middle causing 2 different pieces of paste instead of one.

**Comment by zadjii-msft** [comment]
Wait so are you suggesting that you updated cygwin, and some functionality broke, but this is somehow the console's fault? This sounds like something that should be filed on their issue tracker, right?

**Comment by kas1e** [comment]
Not that I suggest anything there, just with previous versions of Cygwin installs all works as expected, once I installed fresh one to the different directory I have such a behavior (on the same OS, the same machine, etc). Just have 2 different directories with the older Cygwin and the new one. I can run at the same time any of them, and in older all works as expected, in new one pasting is broken. I of course can be out of the logic, but for me, it looks like something was done in Cygwin which cause this. At least IMHO it sounds logical to think about Cygwin's changes first.

**Comment by zadjii-msft** [comment]
>  At least IMHO it sounds logical to think about Cygwin's changes first.

Yep, I'd agree. Looks like [this is their issue reporting guide](https://cygwin.com/problems.html). 

Thanks!
