### ISSUE TITLE
Automatically switch profile color scheme according to selected Windows color theme (light/dark)

### ISSUE THREAD

**Issue by MauricioRobayo** [microsoft/terminal#9840]
# Description of the new feature/enhancement

Be able to automatically switch profile color scheme according to the selected Windows theme (light/dark).

# Proposed technical implementation details (optional)

Like VSCode auto detect color scheme.

Include settings for:

- Preferred Dark Color Scheme
- Preferred Light Color Scheme
- Auto Detect Color Scheme (toggle)

Once the last one is enabled, automatically switch to the preferred color scheme based on Windows appearance.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #4066 for more discussion.

/dup #4066
