### ISSUE TITLE
Import/export color schemes in Settings UI (using a file format)

### ISSUE THREAD

**Issue by inferno986return** [microsoft/terminal#9841]
# Description of the new feature/enhancement

First of all well done on implementing the Settings UI, it was my most anticipated feature and I look forward to seeing it mature. One way to do this for me would be to implement _importing and exporting color schemes_ so they can be shared to another Windows Terminal.

This means that if I want the [Dracula](https://draculatheme.com/) theme (a popular UI colouration that supports just about every program that has adjustable colour options) I can import that into my Windows Terminal.

# Proposed technical implementation details (optional)

In the Settings UI (and referenced in the Settings.json files) there is a separate file format (such as .wtcolor) for color schemes allowing modularity.

**Comment by skyline75489** [comment]
I had almost the same idea in #8639. Never thought about exporting, though.

**Comment by zadjii-msft** [comment]
Yea, this is basically the same idea as /dup #8639
